### ISSUE TITLE
pedestrian route calculation issue

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd#10006]
A piece of a dirt road between 
47.61492° N, 11.03442°
and
47.61520° N, 11.03829°
is not considered for the pedestrian route calculation

![image](https://user-images.githubusercontent.com/50198677/95743991-4dd1ee80-0c9b-11eb-9c03-af70d15b097e.png)

### Routing Profile
pedestrian

start 47.61492° N, 11.03442°
end 47.61520° N, 11.03829°

OsmAnd 3.8.3

offline Bavaria Upper Bavaria map

**Comment by thompehw** [comment]
For the direct route you have in mind, after it crosses the Früllbach stream the walkable track (Way: 687430013) transitions into a different highway=track (Way: 30154110) which is tagged access=no, foot=no, hiking=no, amongst other restrictions. So it looks to me that OsmAnd is doing the right thing - the route it calculates gets closer to the destination than the end of the track for which there is foot access.
