### ISSUE TITLE
Simply add interval next to public transport routes

### ISSUE THREAD

**Issue by IpswichMapper** [osmandapp/OsmAnd#10000]
I have recently been mapping quite a few bus routes in openstreetmap. I found that your app can creates routes using these relations.

However it does not factor in interval or opening hours

One EASY fix is to display the interval next to the route, both in the main part as well as more details.

 
![](https://user-images.githubusercontent.com/72318451/95625705-d6b91200-0a70-11eb-8c31-c295a42f7adb.jpg)

Ideally, the interval should be shown on the next line so that it is clearer, but I can't place it there in this photo I made.

If there are multiple buses/public transport taken in a route, just show the interval of the lowest one.

You could also add colours. Lower intervals is red, high intervals is green, etc..

<hr>

![](https://user-images.githubusercontent.com/72318451/95625891-2d265080-0a71-11eb-988b-64bbe3ad8701.jpg)

It would be great if you could implement this by next update. I'm pretty sure it is very easy to implement

**Comment by aceman444** [comment]
This would be nice. There is also the "duration" tag which may be useful here, as OsmAnd calculates some theoretical duration time which may be far from reality.

**Comment by Janjko** [comment]
It would also be nice if it could write that the route is outside of operating hours right now. And push it to the bottom of the list if that is the case.

**Comment by OpenSourceForEver** [comment]
Interval should be displayed based on the time, a public transport route can have different intervals based on the time

**Comment by vshcherb** [comment]
Information has been added to context menu of each transport route (click on the transport stop)

**Comment by OpenSourceForEver** [comment]
> Information has been added to context menu of each transport route (click on the transport stop)

I can not see information. Last nightly build downloaded may, 23th 10:50

**Comment by Dima-1** [comment]
![Screenshot_1621245250](https://user-images.githubusercontent.com/31807095/119499466-6ba61c80-bd6f-11eb-9460-f89f95f87ed2.png)
  This is example of context menu view with public transport interval. Intervals will appear after next maps update

**Comment by aceman444** [comment]
Thanks.
