### ISSUE TITLE
one can't rename track name from lowercase to uppercase

### ISSUE THREAD

**Issue by mariush444** [osmandapp/OsmAnd#10007]
It is not possible to rename track name from lowercase to uppercase and vice versa.
e.g. existing track name is "abc". You can't chang it to "Abc" because error msg "Existing name already exists"
(screenshot: real name "trasa-lcac-nr5-mazowasze-brok-pultusk" was traid to change to "**T**rasa-lcac-nr5-mazowasze-brok-pultusk")

Probably the solution can be generally the same as proposed in https://github.com/osmandapp/OsmAnd/issues/9990

### Your Environment
OsmAnd Version: 3.8.3
Android/iOS version: 9
![Screenshot_20201012-160640](https://user-images.githubusercontent.com/66887280/95757728-cdfe5100-0ca7-11eb-94b4-248bbc197b31.png)

**Comment by mariush444** [comment]
This problem still exists in 3.9.10.
It is impossible to rename track name from lower case to upper case.
Should I provide more clarification?

**Comment by vshcherb** [comment]
You can rename to another name and then rename it again. It's not possible to do in 1 action looks like

**Comment by mariush444** [comment]
This workaround is known for me. I thought that it's bug that should be fixed. 
It can be closed it in the case that is impossible to fix it.
