### ISSUE TITLE
Show road steepness chevrons

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd#10012]
# 🚀 feature request

### Description

In OS maps and in Europe, they show </>, <</>>, or <<</>>> on roads to indicate those with steepness over certain incline %s. It may be convenient to display the same, without needing to go into the OsmAnd route-planning process.
If it can be shown, it would be great to be able to toggle the zoom-layer from which it's displayed for.

**Comment by promeneur** [comment]
I agree with this. Before using osmand i was using Michelin paper maps. This chevron symbol is used on these maps for many years and is very useful for bike trekking and more useful than contour line or shadowing because with contour line or shadowing we do not get any measure of the steepness.

**Comment by xmd5a2** [comment]
Year ago we introduced slope maps. They are available in OsmAnd downloads interface.

**Comment by promeneur** [comment]
Where do you find them ? I cannot find them.

When I search I find "standard map", "road map", that's all. If you mean "contour line" we are ok.

But you did not understand the wish. We know there is "contour line" feature, but we want something more practical, more easy to read. We wish "chevron" to indicate the incline.

**Comment by xmd5a2** [comment]
@promeneur see https://osmand.net/blog/osmand-3-7-released

**Comment by promeneur** [comment]
@xmd5a2 and @vshcherb 

Yes I know this. But I keep on saying I want something more practical, more easy to read. I wish "chevron" to indicate the incline.

**Comment by AndyB69** [comment]
I will give this a try. I am doubtful whether it will work well, per my original suggestion (open by katerynakocherhina following my email) because I don't want to lose the regular map display colours/scheme. I want to keep my normal map presentation, but just have the steeper sections of road indicated by chevrons per european road map systems.

**Comment by promeneur** [comment]
> I will give this a try. I am doubtful whether it will work well, per my original suggestion (open by katerynakocherhina following my email) because I don't want to lose the regular map display colours/scheme. I want to keep my normal map presentation, but just have the steeper sections of road indicated by chevrons per european road map systems.

I agree with you. Only steeper incline must be signaled. A good example are the Michelin maps. If I remember, there are 3 grades and for steeper inclines. It is sufficient.

Another solution is using colors. For example, yellow, orange, red along the road.

**Comment by AndyB69** [comment]
Hello promeneur - the trouble with road colouring is that different roads
are all colour-coded anyway, so could make it hard to read/interpret?

**Comment by AndyB69** [comment]
Hello - I have now tested the slope shading and can categorically say that it does not help - in any convenient way - with the original suggestion of this ticket (adding chevrons to roads to indicate hill steepness). 

Reasons being: 
1. When you have slope-shading on, there is no on-screen key to tell you what the colours mean.
2. You can configure the transparency of the shading, and if any significant transparency is selected then the colours no longer match the key anyway.
3. Zero transparency hides other map features. 
4. You can't easily turn the slope shading on/off - there is the 'quick actions' icon you can add to the map screen to turn/off certain features, and it does provide a 'hide-terrain' option, but that simply turns on/off the currently selected terrain style - so to turn on/off slope shading you'd first have had to select slope shading in the deeper Menu > Configure Map > Terrain... menu... (i.e. it would be helpful if the 'quick action' set could include something like "Switch terrain", which would switch between hill-shading and slope-shading).

It's points 1-3 that are the main ones against using slope shading to address the feature requested in this thread. 

Can you please reconsider adding chevrons, per many european paper map styles? They are super-helpful when planning road routes. 

Regards.

**Comment by AndyB69** [comment]
Hello, this issue was closed (by xmd5a2, on 19 Nov 2020) but the solution provided at that point does not resolve the issue, for the reasons I stated after testing it just 3 weeks ago.

Can this item be re-opened please? The chevron solution approach, as in initially suggested in this thread still appears to be the best approach for showing road steepness and not losing any other other information.

**Comment by vshcherb** [comment]
Chevron solution needs to be mapped on OpenStreetMap as a point, so it can be displayed precisely. Other solutions now are not possible to support
