### ISSUE TITLE
Arabic translation of POIs

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd#10014]
in every category of POIs, there are at least a couple of subcategories that remain to be in English.
### How to reproduce?
Search - Category - Custom search - open every category one by one
![image](https://user-images.githubusercontent.com/50198677/95835031-63e8b900-0d46-11eb-82af-53140a0f92a4.png)
![image](https://user-images.githubusercontent.com/50198677/95835051-6ba85d80-0d46-11eb-835c-e17628c2e5f0.png)
![image](https://user-images.githubusercontent.com/50198677/95835074-7105a800-0d46-11eb-881d-51212b99afe5.png)
![image](https://user-images.githubusercontent.com/50198677/95835095-75ca5c00-0d46-11eb-9f49-01f2920bfb1d.png)
![image](https://user-images.githubusercontent.com/50198677/95835109-79f67980-0d46-11eb-921e-879f883a0389.png)
![image](https://user-images.githubusercontent.com/50198677/95835127-7f53c400-0d46-11eb-8fc5-516dde23c73d.png)

OsmAnd Version: 3.8.3

**Comment by vshcherb** [comment]
We can help contributor to add them. Some of them could be translated via Weblate
https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/res/values/phrases.xml#L1643

**Comment by saad-eid** [comment]
https://github.com/osmandapp/OsmAnd/tree/master/OsmAnd/res/values-ar

**Comment by vshcherb** [comment]
@saad-eid 
Can you please create a pull-request from your branch - https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request
