### ISSUE TITLE
Can not select any POI since OsmAnd~ 3.8.3

### ISSUE THREAD

**Issue by Heiner-Sch** [osmandapp/OsmAnd#10030]
### Description
Since the update from OsmAnd~ 3.7.4 to 3.8.3 it's not possible to select a POI anymore.
Instead of the data of the POI, there is the message: searching for address ...
So it's also not possible to edit POI's.

### How to reproduce?
This happens all time and with all offline maps on the phone.

### Your Environment
OsmAnd Version: OsmAnd~ 3.8.3
Android/iOS version: Andoid 8.1.0 
Device model: bq Aquaris X Pro

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
offline maps Germany
Deutschland Nordrhein-Westfalen 01.10.2020
Deutschland Hessen 01.08.2020

Luxemburg 01.07.2020

In all maps teh same issue.

**Comment by Codain** [comment]
I also had this issue yesterday (I was able to select a node POI but not a way POI, and there was some glitches in rendering) but today I can again select POI and rendering is fine. Unfortunately I did not make any screenshot convinced that this weird behaviour would last longer. Strange.

**Comment by Heiner-Sch** [comment]
Here you can see the screen with the issue.
The Petersberg Hotel is marked, but you don't see the data of the POI, like web site, phone no., opening hours, ... 
You see only the address.

![Screenshot_20201016](https://user-images.githubusercontent.com/38109491/96251855-5e42db80-0fb1-11eb-9d3b-d9f6fd25d3c5.png)

**Comment by Heiner-Sch** [comment]
Need to add another comment here:
The issue is also in OSMand~ 3.8.5

To be sure, that it's not related to the data of an older version, I've uninstalled OSMand and removed the data folder.
No old configuration, no old maps.
But even with the complet fresh installation with a new downloaded map I have the problem.

Am I really the only one, who has this bug?
What information do you need to troubleshoot?

**Comment by Heiner-Sch** [comment]
Checked another Android device.
Here is the problem also available.

Environment
OsmAnd Version: OsmAnd+ 3.8.4
Android/iOS version: Andoid 8.1.0
Device model: Tablet Medion P10606

offline maps Germany
Deutschland Nordrhein-Westfalen 01.11.2020

To have access to the details of POI's is for me an important function of the app.
Only here have users access to phone numbers, website or Wikipedia articles related to POI's.

**Comment by sonora** [comment]
This looks to me like you are performing a **long tap** on the map, which will select the precise location of where you are tapping, vs. a **short tap** which will select a tappale map object (if one is around).?

**Comment by Heiner-Sch** [comment]
I agree, that was the problem.
But I'm wondering, because I use OsmAnd for some years now and never had this before.
Have the timers for a short tap changed with version 3.8.3?
Or is it really only human related?

**Comment by vshcherb** [comment]
We had to change the behavior to make point selection to be precise for example for pen-point selection. Probably 5-6 years ago short tap was not present but I don't remember that anymore :-)

**Comment by bege10** [comment]
Sorry, that was the wrong thread where I posted. Deleted the post there but the entry here remains.

**Comment by AnastasiaTiutina** [comment]
Try to disable the Accessibility plugin and enable OsmAnd development. Click on 3 vertical dots behind the OsmAnd development plugin and choose Settings. Make sure there is no mark on the save mode.

**Comment by vshcherb** [comment]
It's also possible that app is running in "Safe mode" (app was crashed during initialization), sometimes restart of the app could help or reinstall.

You can check it under Development Plugin -> Settings -> Safe mode.


Note:  Accessibility plugin disables single tap that's normal behavior for accessible people.

**Comment by vshcherb** [comment]
Does it work again?

**Comment by sonora** [comment]
I think this issue was solved, see https://github.com/osmandapp/OsmAnd/issues/10030#issuecomment-730509514 ?
