### ISSUE TITLE
Always show "name" tag for bus stops even if there is a "ref" tag

### ISSUE THREAD

**Issue by cyclingcat** [osmandapp/OsmAnd#10037]
### Description

Bus stops with a _ref_ tag show this tag on the map instead of the bus stop name. This is misleading information as any kind of signs (at the bus stops themselves, in time tables, on displays inside the buses) show the bus stop names while the _ref_ tag can contain different kinds of information which are less relevant for the map (e. g. internal numbers, platform identifiers or bus route numbers). This is valid at least for Germany.

### How to reproduce?

1. Find a node with the following combination of tags (e. g. via overpass):

```
highway=bus_stop
ref=*
```

2. Scroll to this node in the displayed map

### Examples:

See the following screenshot where two bus stops are shown on the map:

**(1)** is the bus stop with the name "Marktplatz". Shown with this name on the map as there is no _ref_ tag. **Node id 573840689**.

**(2)** is the bus stop with the name "Friedhof". Instead of its name the content of the _ref_ tag is shown (here it seems to be a list of the bus routes served here). **Node id 352741502**.

![bus_stop](https://user-images.githubusercontent.com/32601012/107777177-cd072a00-6d42-11eb-98e0-fc2ba8f688a0.png)

### Your Environment
OsmAnd Version: 3.8.3 from F-Droid
Android/iOS version: 5.1 and 9.0 respectively
Device model: bq Aquaris M4.5 and Cubot Quest

**Maps used (online or offline):**   
Offline, Germany - Baden-Württemberg, 01 October 2020.

The cycling cat

**Comment by cyclingcat** [comment]
Hi there,

today OsmAnd~ v3.9.4 came in through F-Droid, but this issue is still there - doesn't _"milestones: **3.9-android, 3.9-backend**"_ mean that this fix should have been implemented in any version >= 3.9?

The cycling cat

**Comment by vshcherb** [comment]
Yes should be part of 3.9

**Comment by cyclingcat** [comment]
Oops... sorry: I have edited my posting some hours ago: It was obviously a problem with the OsmAnd~ installation on my phone, after a reinstall the change was visible. Nevertheless the question remains (see the screenshot above): Is the content of the "ref" tag really so important that it justifies the ugly and lengthy label for this group of bus stops?

The cycling cat

**Comment by xmd5a2** [comment]
@cyclingcat so mapped in OSM. We have no responsibility for that.

**Comment by cyclingcat** [comment]
Yes, of course it's tagged this way but why has this information to be included in the map display? I checked it with some more bus stops., the scheme seems always to be
```
if [ref] exists then
    show [name] + " (" + [ref] + ")"
else
    show [name]
endif
```

Why not simply don't care about any existing "ref" tags for bus stops at all?

The cycling cat

**Comment by sonora** [comment]
Looks to me like in the examples above "ref" may have been used to denote the transport line refs the bus stop serves - which is a mistake as per the OSM's use of the ref tag.

Ref's should denote the official reference **of the object itself**, which for bus_:stops I am not aware it is used much, but certainly possible in some networks or environments.

Where it is used, it may be useful to display on the map! The problem is that it is "misused" so often, we may in deed have to hide it to not clutter the map ...

**Comment by Famlam** [comment]
The change made also affects platforms, correct? Is it perhaps possible to still display the refs if they're simple [example: A1, 3a, ...]? To my knowledge, all train stations in NL should have numbers with sometimes an a or b suffix (although some abuse the name tag for that), to indicate where a train will arrive?

**Comment by sonora** [comment]
I know that some different practices are in use, but using local_ref for that should be the standard...
