### ISSUE TITLE
OsmAnd erroneously routes bicycles over footpaths in the Netherlands

### ISSUE THREAD

**Issue by joepie91** [osmandapp/OsmAnd#10035]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, OpenRouteService, OSRM, etc.)

### Routing Profile

bicycle

### Start and end points

From https://www.openstreetmap.org/node/2744540955 to https://www.openstreetmap.org/node/2744600215

### Actual and expected routes

OsmAnd *should* be routing around the park, as the paths in the park are footpaths, and cycling on footpaths is not permitted in the Netherlands (in fact, there are anti-bicycle barriers installed here). However, it routes straight through it.

The same issue occurs for some other arbitrary routes I've picked where a footpath is the shortest path.

### Is this a regression?

Unknown

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>
OsmAnd~ 3.7.4

</code></pre>

**Device and Android/iOS version:** Oukitel WP5, Android 10

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

I don't know how to find the relevant map filename. However, it's most likely the "Netherlands North Brabant" map from Jul 1, 2020.

**Anything else relevant?**

**Comment by carstenhag** [comment]
See #9826, pretty sure that it fixes this issue. I haven't tested it myself yet or know whether it has actually been integrated yet.

**Comment by joepie91** [comment]
Oh, sorry, I'm not sure why that didn't show up in my search of the existing issues.

Just to confirm: from looking at the change, it seems to only add an "avoid footways" switch, but does not enable it by default (neither globally nor in specific countries) - is that correct? For a good out-of-the-box experience, I feel like this should be enabled by default in at least the countries which are known to not allow cycling on footways.

**Comment by carstenhag** [comment]
I've added a Screenshot to the other ticket. Yeah, it's only a toggle that has to be manually set.

I fully agree with you that this should be decided automatically per country, and only overridable by the user.

**Comment by vshcherb** [comment]
Yes we need to introduce country specific settings

**Comment by matthijskooijman** [comment]
It seems this issue is duplicate with #9361.

**Comment by vshcherb** [comment]
I think original issue is fixed https://osmand.net/map/navigate/?start=51.721964,5.357133&end=51.722060,5.358160&profile=bicycle#19/51.72184/5.35768
