### ISSUE TITLE
Santa Fe to Tucson unnecessarily routes through Las Cruces

### ISSUE THREAD

**Issue by earksiinni** [osmandapp/OsmAnd#10050]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, OpenRouteService, OSRM, etc.)

### Routing Profile

Car

### Start and end points

Start: Santa Fe, NM, United States (https://www.openstreetmap.org/relation/171264)
End: Tucson, AZ, United States (https://www.openstreetmap.org/relation/253824)

### Actual and expected routes

Expected: Take I-25 south toward Hatch, NM, then turn right onto NM 26 west until meeting up with I-10 near Deming, NM. Then take I-10 west to Tucson, AZ.

Actual: Take I-25 south toward Las Cruces, NM until meeting up with I-10. Then take I-10 west to Tucson, AZ. This route adds about 37 miles.

### Is this a regression?

 Not sure? This is my first time using OsmAnd.

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>3.81</code></pre>

**Device and Android/iOS version:**

iPhone 6S Plus, iOS 14.0.1

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**
This is my first time using OsmAnd. I signed up for a yearly subscription--I'm proud to support your work!

**Comment by sonora** [comment]
Yes, in deed, this should definitely take State Route 26.

**Comment by xmd5a2** [comment]
There were wrong oneway highways in Deming which caused routers to go around via residential lanes. Also trunk suddenly becomes primary https://www.openstreetmap.org/way/119089378#map=17/32.28279/-107.76118. I've corrected oneway issue but don't know how to fix highway classes.

**Comment by sonora** [comment]
@xmd5a2 Well spotted, thanks!  ;)
