### ISSUE TITLE
"cycleway:both" is ignored

### ISSUE THREAD

**Issue by McLondon** [osmandapp/OsmAnd#10053]
In cycling mode, roads tagged with <code>cycleway:both=\*</code> don't render as having cycle lanes/tracks on the map.

Ideally these should render the same as the roads tagged with <code>cycleway=\*</code>, i.e. with dashed blue lines.

**Comment by vshcherb** [comment]
Rendering could render only separate ways having 1 OSM way to render multiple layers like bridge, tunnel, tram line causes quite much trouble to maintain rendering style

**Comment by axelos** [comment]
Hello,

I noticed that yesterday for the bus lanes that are allowed for bikes. (cycleway:both=share_busway).
It's a practice that is growing since the arrival of the StreetComplete application.
I will try to implement this in OsmAnd in the next days.

Axel.
