### ISSUE TITLE
Plan a route saving issue

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd#10054]
### Description
After saving the changes in Plan a route - Options - Save changes/ Save as new track, the changes are not considered, even after saving the track again before leaving the Plan a route mode
the issue reoccurs both in Nightly and released OsmAnd versions

![image](https://user-images.githubusercontent.com/50198677/96717169-bc573080-13ae-11eb-91dc-4ad279aca9d3.png)
![image](https://user-images.githubusercontent.com/50198677/96717197-c24d1180-13ae-11eb-9ec2-37b552cbbff7.png)
![image](https://user-images.githubusercontent.com/50198677/96717211-c7aa5c00-13ae-11eb-92b6-b763a9d638d6.png)

[plan a route.zip](https://github.com/osmandapp/OsmAnd/files/5415693/plan.a.route.zip)

### How to reproduce?

create a track with multiple points
open it with Plan  a route and remove the required point
save it in Options
exit the Plan a route mode
open the track's Altitude/ Slope graph or open it with the Plan a route mode
the changes are supposed to be not considered 

### Your Environment
OsmAnd Version: 3.8.3

**Comment by alex-osm** [comment]
Fixed already
