### ISSUE TITLE
displaying of hiking trails

### ISSUE THREAD

**Issue by MichaelV99** [osmandapp/OsmAnd#10052]
with the new version 3.8 of Osmand, a function does not work any more which was working in the past without problems:

with function "configure map" - last item "routes" - "overlay of hiking symbol" - "colouring according OSMC-Symbols", hiking trails in colour an with the symbol at the trail (like a coloured cross, circle or dash) were displayed in the map.
In version 3.8 the hiking trails appear now mostly only underlayed in grey without symbols, only at a few places colour and symbols are displayed (see second screenshot)

As I use the german version of Osmand, I can only guess how the menu-items I mentionned are called in the english version, so I write them again in german:"Karte konfigurieren" - "Routen" - "Wandersymboleinblendung" - "Einfärbung gemäss OSMC-Wandersymbol"

The issue may be related to issue #9947, but as it is another implication I opened a new one.

### How to reproduce?

Pos 49.67581 N, 11.28962 E
![Screenshot_20201021-090945_OsmAnd](https://user-images.githubusercontent.com/73224524/96701375-cff39e80-1390-11eb-9fed-bacad3619de0.jpg)

Pos 49.66374 N, 11.26003 E
![Screenshot_20201021-091046_OsmAnd](https://user-images.githubusercontent.com/73224524/96701542-04675a80-1391-11eb-9925-057377f1b1bd.jpg)

### Your Environment
OsmAnd Version: 3.8.3
Android/iOS version: Android 8.0.0
Device model: Samsung A3

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
Used Offline map Germany_bayern_europe_2.obf, version of Oct 1st 2020

**Comment by pebogufi** [comment]
If you want to know english menu names, switch to english language:
3-lines menu / globe symbol / verwalten / osmand-Einstellungen / Anzeigesprache. When you are ready just switch back.

**Comment by pebogufi** [comment]
This is a screendhot with version OsmAnd~  3.9.0#30762m.apk dated 2020-10-19. I. My opinion it was not a problem in last weeks.
Try switch that setting off and on again.

![Screenshot_20201021-155417_OsmAnd~~01](https://user-images.githubusercontent.com/18628183/96730372-61293c00-13b6-11eb-9681-e7c179ba2ceb.jpg)

**Comment by vshcherb** [comment]
Maps needs to be redownloaded. I see on previous screenshot it looks incorrect cause the segments were randomly switched from one route to another. Now all routes are sorted by priorities, unfortunately routes could be hidden under most prioritized. There are another issues to display many routes on 1 segment
