### ISSUE TITLE
Map Crator Changes between 2020-10-10- and 2020-10-20

### ISSUE THREAD

**Issue by MAlfare** [osmandapp/OsmAnd#10055]
Hi!
My POI-files generated  with the latest MC gets about 50% lager in size, generated from identical OSM-files.
Why?
See attached example
[MC_20201010-20201020_Example.txt](https://github.com/osmandapp/OsmAnd/files/5415874/MC_20201010-20201020_Example.txt)

**Comment by vshcherb** [comment]
I think tag "description" wasn't indexed before

**Comment by vshcherb** [comment]
Actually in your example you printed POI section which didn't change size at all. I checked rendering_types and description shouldn't be indexed any more

**Comment by MAlfare** [comment]
Thank you very much!
