### ISSUE TITLE
Create custom folders for tracks

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd#10068]
# 🚀 feature request

### Description

In Plan a route mode, you can build a custom route and save it in the Tracks folder only. That would be convenient to have an option to create a new folder and select it for storage.
![image](https://user-images.githubusercontent.com/50198677/96964778-b7f85800-1513-11eb-90df-b9981051aff4.png)

**Comment by Chumva** [comment]
You can write subfolder name in the filename field. It will save the track in a subfolder in the selected folder. For example, this will create a track in rec/someNewSubfolder/Mon_23_Nov_2020.gpx.

![Screenshot_1606138594](https://user-images.githubusercontent.com/19220417/99968440-ce5b3300-2da1-11eb-9d91-eb30087f5c27.png)

**Comment by dmpr0** [comment]
![plan_routes_groups](https://user-images.githubusercontent.com/9365308/99982722-98bf4580-2db3-11eb-8ef7-b70a6cae5842.png)

**Comment by sonora** [comment]
@vshcherb Before we put effort in that design, please note that we have several  different dialog UIs for folder-related functionality, see https://github.com/osmandapp/OsmAnd/issues/9918#issuecomment-732450692 and  https://github.com/osmandapp/OsmAnd/issues/9918#issuecomment-733926671.

Probably worth to first unify by selecting **one functional look&feel first** (I suggest that e.g. vertical scrolling through a folder list usually is more functional, ergonomic, and space-optimized than vertical scrolling through a row of buttons), and then put the effort in?

**Comment by dmpr0** [comment]
# Review 
- [ ]  "Tracks" folder doesn't show in all folder list
- [ ] Recently added folder doesn't show in in the folder list.
- [ ] Add new folder dialog: show with an empty name, start typing a name with a capital letter 
- [ ] Save as new track dialog: show "Add new folder" button (like in adding favorite)

**Comment by Skalii** [comment]
[Fix for custom track folders](https://github.com/osmandapp/OsmAnd/pull/10941)
