### ISSUE TITLE
Right turn is not considered

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd#10067]
# 🐞 routing report

### Routing engine

- [ ] OsmAnd's in-app offline routing

### Routing Profile

Car profile

### Start and end points

29.82885/-95.37646

29.85472/-95.37098

### Actual and expected routes

The turn to the right is supposed to be announced from Fulton street to Tidwell road, but it is not announced.
![image](https://user-images.githubusercontent.com/50198677/96963066-a95c7180-1510-11eb-89db-a14955d1e89f.png)

![image](https://user-images.githubusercontent.com/50198677/96963118-bda06e80-1510-11eb-9101-2cc8e99fb853.png)

## 🌍 Your Environment

**OsmAnd Version:**

3.7.4
3.8.3

**Maps used (online or offline):**

Offline Texas map

**Comment by vshcherb** [comment]
Please check that data has "turn:lanes" specified

**Comment by scaidermern** [comment]
The [way](https://www.openstreetmap.org/way/423145509) before the turn has `turn:lanes=left||` set, which is correct according to Bing aerial imagery. The [link](https://www.openstreetmap.org/way/306651656) has no `turn:lanes` set but `turn=right` instead (not really sure what this tag is for).

There is a road change from secondary (Fulton Street) to secondary_link (unnamed) and to secondary again (Tidwell Road). Shouldn't this be sufficient for OsmAnd to detect a right turn?

**Comment by xmd5a2** [comment]
```
<test regions="" description="" best_percent="" vehicle="car" 
  start_lat="29,84493" start_lon="-95,37736" target_lat="29,84557" target_lon="-95,37647"  routing_time="Infinity" loadedTiles="2" visitedSegments="13" complete_distance="215,70" complete_time="28,08" >
	<segment id="685028660" oid="43841834275" start="5" end="6" time = "4.102019" rspeed = "0" name = "Fulton Street" maxspeed = "56" secondary distance = "63.50533" turn = "Go ahead" turn_angle = "0.0" start_bearing = "-23.374165" end_bearing = "-23.374165" height = "[0.0, 21.123823, 33.264233, 21.0]" description = "Go ahead and go 81,24 meters" />
	<segment id="423145509" oid="27081312585" start="0" end="1" time = "1.1456445" name = "Fulton Street" maxspeed = "56" secondary distance = "17.736275" start_bearing = "-23.198591" end_bearing = "-23.198591" height = "[0.0, 21.0, 17.736275, 22.0]" description = "" />
	<segment id="306651656" oid="19625705995" start="0" end="4" time = "16.9765" name = "" distance = "32.502434" turn = "Turn right(TL|C|+TR,C)" turn_angle = "44.053047" lanes = "[4, 2, 43]" start_bearing = "20.854458" end_bearing = "57.14428" height = "[0.0, 22.0, 5.815019, 22.0, 7.3235474, 22.0, 4.578015, 22.0, 14.785854, 22.0]" description = "Turn right(TL|C|+TR,C) and go 134,46 meters" />
	<point 2 highway="give_way"/>
	<point 3 crossing="uncontrolled" highway="crossing"/>
	<segment id="597602530" oid="38246561935" start="0" end="2" time = "2.779859" name = "Tidwell Road" maxspeed = "64" secondary distance = "48.390133" start_bearing = "90.0" end_bearing = "89.47914" height = "[0.0, 22.0, 19.924866, 22.0, 28.46527, 22.0]" description = "" />
	<segment id="473786250" oid="30322320051" start="0" end="2" time = "3.0771506" name = "Tidwell Road" maxspeed = "64" secondary distance = "53.565212" start_bearing = "89.572426" end_bearing = "89.17566" height = "[0.0, 22.0, 34.675404, 21.494553, 1.3194451, 21.475319]" description = "" />
</test>
```

```
"Turn right(TL|C|+TR,C)" turn_angle = "44.053047" lanes = "[4, 2, 43]" start_bearing = "20.854458" end_bearing = "57.14428" height = "[0.0, 22.0, 5.815019, 22.0, 7.3235474, 22.0, 4.578015, 22.0, 14.785854, 22.0]" description = "Turn right(TL|C|+TR,C) and go 134,46 meters"
```

Can't reproduce with current OSM data. Right turn should be announced correctly.

**Comment by aceman444** [comment]
Does OsmAnd really announce the turn when it is only 44 degrees angle?

**Comment by skquinn** [comment]
I can confirm it's been fixed, I just drove the route a few minutes ago and OsmAnd now calls out the right turn.

@aceman444 This is a right turn even if the initial angle is only 44 degrees; it's a turning bay from Fulton onto Tidwell.
