### ISSUE TITLE
Upload GPX to OSM: default track visibility

### ISSUE THREAD

**Issue by 532910** [osmandapp/OsmAnd#10072]
Please add support to set default track visibility on upload to osm.
I'd like it to be private by default.

**Comment by dmpr0** [comment]
We need to:
• Remember the last select visibility option for track uploading.

**Comment by dmpr0** [comment]
# Review
- [ ]  Fix visibility selector scroll position.
![Снимок экрана 2021-04-06 в 15 52 38](https://user-images.githubusercontent.com/9365308/113713531-23179e80-96f0-11eb-9b64-5feb102a7f55.png)
