### ISSUE TITLE
My Places bottom menu not displayed in landscape screen orientation

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd#10070]
### Description

When switching the screen orientation, in My Places the bottom menu is displayed in the portrait orientation only. 
The issue occurs in all of the My Places folders - Favorites, Tracks, A/V notes, etc. 

![image](https://user-images.githubusercontent.com/50198677/96981501-5098d300-1528-11eb-8ef3-0fa9452503b4.png)
![image](https://user-images.githubusercontent.com/50198677/96981581-54c4f080-1528-11eb-8495-a391aa18c568.png)

### Your Environment
OsmAnd Version: 3.8.3

**Comment by vshcherb** [comment]
it's on top
