### ISSUE TITLE
Switching overlays / underlays on should not bring up the dialogue to change their source

### ISSUE THREAD

**Issue by mikehgentry** [osmandapp/OsmAnd#10078]
At present, if you switch an overlay / underlay off and back on again, you're presented with the popup to choose which source it should be.

In my opinion that's a little awkward, because I imagine most people aren't changing which overlays / underlays they're using anywhere near as regularly as they're switching them on and off. The '...' menu lets you change the source and is easily discoverable, so the switch should act as a simple on / off toggle.

(the obvious exception being when no source has yet been chosen, when the present behaviour makes sense)

Osmand+ 3.8.3

[edited typo]

**Comment by vshcherb** [comment]
Can't reproduce the issue. 
Configure menu
- Switch on Overlay 
- Select source via dialog
- Switch off Overlay
- Switch on Overlay

---- No select source dialog is vislble

**Comment by mikehgentry** [comment]
Sorry, I missed a step. Exiting and re-entering the menu after switching it off seems to trigger it.
