### ISSUE TITLE
Add "Truck" and "Motorcycle" profile by default

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#10080]
- [x]  Move them below "Walking".
- [x]  Show plugin profiles

We could add the "Truck" and "Motorcycle" profile as default but disabled, as "AirCraft" or "Skiing".
Custom profile profile

**Icons:**
Motorcycle – ic_action_motorcycle_dark
Truck – ic_action_truck_dark

**Comment by vshcherb** [comment]
We can add automatic default limitation for width / height

**Comment by dmpr0** [comment]
# Review 
- [ ]  Move them below "Public transport".

**Comment by dmpr0** [comment]
+1h over estimate
+6h for fix

**Comment by androiddevkotlin** [comment]
Show plugin profiles - not in the master
