### ISSUE TITLE
OsmAnd tracker has an issue with resending MAP (issues with OsmAnd widget and tracker status)

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#10083]
Need to check all log files from OsmAnd tracker.

An issue with resending map:
we share location - Map and Text (or only Map). When we have a problem with the internet, OsmAnd tracker keeps dotes to buffer. But when we have a good connection and dotes are sent again. After that, new Map session in Telegram has a problem, it's not updating. Status has an issue in Tracker, and with Widget in OsmAnd.
Proposal: resend new map in Telegram if we have this issue.

**Comment by Chumva** [comment]
This should be fixed here https://github.com/osmandapp/OsmAnd/pull/10156, but it needs further testing
