### ISSUE TITLE
World basemap contains mysterious trunk/motorway

### ISSUE THREAD

**Issue by Famlam** [osmandapp/OsmAnd#10104]
### Description
Compare the screenshots at a zoom level for the local maps (2km scale bar) and the zoom level for the world basemap (5km zoom bar) near Bemmel, Gelderland, The Netherlands.
In the world basemap, there's an additional Trunk/Motorway-like road in the vicinity of Bemmel. In the local maps, such a road doesn't exist for at least several years. World basemap was updated 22-10-2020

### How to reproduce?
1. Install the following maps: World Basemap & The Netherlands -> Gelderland
2. Compare Bemmel (between the cities of Arnhem and Nijmegen) at different zoom levels

### Your Environment
OsmAnd Version: 3.8.3
Android/iOS version: Android 9
Device model: LG

**Maps used (online or offline):**   
- world basemap mini (offline, 1-10-2020)
- world basemap (offline, 22-10-2020)
- The Netherlands -> Gelderland (offline, 1-10-2020)

![WhatsApp Image 2020-10-29 at 09 22 11](https://user-images.githubusercontent.com/1315520/97546565-e622df80-19cc-11eb-8f9a-526b97f286ea.jpeg)
![WhatsApp Image 2020-10-29 at 09 22 51](https://user-images.githubusercontent.com/1315520/97546796-35691000-19cd-11eb-8051-096734a5fd10.jpeg)

See the way near the red arrows in the screenshot. Please note that the road involved is probably a tertiary way.

**Comment by sonora** [comment]
Here are other occurrences:
40.60781° N, 15.29183° E
49.04952° N, 13.02913° E

Those primary or secondary highways seem to somehow be interpreted on the world basemap as continuations of a motorway which actually ends.

**Comment by vshcherb** [comment]
This is an issue related of merging roads by REF. OSM has lots of small roads and lots of small segments (errors potentially) which change the class road, so on the basemap we sometimes merge class roads too aggressively though it's strange that highway refs match in that case.

**Comment by sonora** [comment]
Checking OSM for the cases I am reporting:

- Near 40.60781° N, 15.29183° E several segments of primary rosd SP36/a are shown in the basemap as motorway, but the motorwas nearbyy do not have that ref.

 - In the case of 49.04952° N, 13.02913° E, secondary road St 2136 is shown as continuation of motorway A92. No common ref there, either. But it looks the stretches of secondary road we show as motorway are part of relation E53. So is A92. But E53 continues much further into the Czech Republic than we interpret it as motorway.

**Comment by aceman444** [comment]
Thanks for reporting this. I have also seen this in our country. And it is NOT that a road and a motorway would have the same ref. I have seen differently numbered roads displayed as as motorway extension.

**Comment by Dima-1** [comment]
osmandapp/OsmAnd-tools#415
