### ISSUE TITLE
White text on white background

### ISSUE THREAD

**Issue by Famlam** [osmandapp/OsmAnd#10100]
### Description
In the help menu, there are two large icons. Accidentally I discovered that under these icons there happens to be some text. However, it's white-on-white until you press it.

### How to reproduce?
Go to menu -> Help (the last entry), scroll down a bit

### Your Environment
OsmAnd Version: 3.8.3
Android/iOS version: Android 9
Device model: LG

**Maps used (online or offline):**   
irrelevant

![WhatsApp Image 2020-10-29 at 09 24 52](https://user-images.githubusercontent.com/1315520/97544483-f71e2180-19c9-11eb-880d-2168c4899918.jpeg)

**Comment by Chumva** [comment]
This should be fixed here https://github.com/osmandapp/OsmAnd/commit/46c5c04a012e524342f52032f3ceb4c0fb58e8de.
