### ISSUE TITLE
Wants to update TTS files daily

### ISSUE THREAD

**Issue by Famlam** [osmandapp/OsmAnd#10101]
### Description
I removed all-but-English and Dutch TTS files. Since then, it wants to update the English and Dutch TTS files nearly every day. Note that I'm not on Live, so I shouldn't get updates more than once a month. (However, if it's on purpose rather than a bug, it might be nice to do these mini-files automatically, without me having to press the download button after seeing I have two pending map updates)

### How to reproduce?
Not entirely sure, I guess it's related to deleting the -for me irrelevant as I can't speak the language- TTS files

### Your Environment
OsmAnd Version: 3.8.3
Android/iOS version: Android 9
Device model: LG

**Maps used (online or offline):**   
Irrelevant

![WhatsApp Image 2020-10-29 at 09 21 18](https://user-images.githubusercontent.com/1315520/97544955-99d6a000-19ca-11eb-94a9-f67e2a1a749b.jpeg)

**Comment by vshcherb** [comment]
Fixed
