### ISSUE TITLE
Recording shouldn't stop after saving track

### ISSUE THREAD

**Issue by AntiSol** [osmandapp/OsmAnd#10105]
### Description
OsmAnd no longer records tracks by default, I now have to press the 'rec' button to start recording.

In the past, when I start the application or choose 'save current track', osmand would immediately start recording a new track. This has been changed so that in both cases I'm now required to manually press 'rec'.

I have been using osmand for many years now and have a long-established habit of expecting it to record everything automatically. I have already not recorded several tracks simply because I expected it to be recording automatically when it wasn't.

Perhaps there's some option to restore the previous behaviour and have it record tracks by default? I looked through the settings but I don't see any. The closest I see is "settings->profile->trip recording->auto-record track during navigation", but this only applies if I'm using the application for navigating, something I rarely do (I use it mostly as a trip recorder and map).

I contacted the support email to see if there was an option, but their response was... shall we say... "unhelpful", suggesting several things that I had already mentioned in my email, and not really answering my question about restoring the previous behaviour.

### How to reproduce?
1. Start OsmAnd
2. Observe that tracks are not being recorded

### Your Environment
OsmAnd Version: 3.8.3
Android/iOS version: LineageOS
Device model: Samsung Galaxy

**Maps used (online or offline):**   offline
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by AntiSol** [comment]
Oh, I forgot to say: thanks for OsmAnd! it's great! :)

**Comment by pebogufi** [comment]
Choose your profile
Configure profile
Trip Recording
Auto record track during navigatikn -> ON
---
you have to set it for each profile, where you need it.

**Comment by pebogufi** [comment]
I don't think, that it is now different than in older versions.
Either you use "auto-record track during navigation" which is only during navigation, or you have to start it manually.

**Comment by AntiSol** [comment]
it is most certainly different. I've never had to start it manually in the ~4 years I've been using it.

**Comment by vshcherb** [comment]
I think since long time OsmAnd records track only for navigation, probably you've started using without navigation.

**Comment by vshcherb** [comment]
And yes many things changed since Android 10, cause there are many regulations how it should run in background and which notifications should be displayed

**Comment by AntiSol** [comment]
no, I haven't just started using it without navigation. I rarely use navigation.

So... you're saying that it hasn't changed, but that it has changed? Which is it?

**Comment by AntiSol** [comment]
if it hasn't changed, perhaps you can explain why downgrading to 3.7.4 restores the behaviour I'm describing?

**Comment by sonora** [comment]
I am not aware we've had 'automatic track recording', ever.

But what I think maybe going on is this: We have a setting somewhere which inhibits recording when the app is not in the foreground. So maybe you have this active. And before version 3.8 we further had the behavior that tapping 'Save current track' closed and saved the track, **but continued recording** (see #8911).

So I guess what may have happened in 3.7 and before is you never actually stopped recording (because tapping 'savd current track' never had that effect), but now it has?

**Comment by AntiSol** [comment]
Aha! Now we're getting somewhere!

I have, indeed, never stopped recording in 4 years. My primary use for OsmAnd is as a track recorder, using it as an offline map and navigation being secondary uses for me. If OsmAnd is open (or running in the background), I want it recording. When I don't want it recording, I kill it using lineageos' "long-press back button" feature.

It looks like #8911 is indeed the change that has caused this issue, assuming the app will resume its previous record state when it is restarted(?).

I see your comment on that ticket saying "it appears the use cases for 'Save track but continue to record' are slim to none". I wish I'd known about that discussion before the change was implemented, I would have chimed in and given a use case for a "save track and continue recording" option ;)

I think that the best solution would probably be to have a "keep recording" toggle on the "save track" dialog which remembers my preference from the last time I saved.

Here's a mockup of what I mean:
![osmand_keep_recording_mockup](https://user-images.githubusercontent.com/351169/97770605-ea93f780-1b88-11eb-8566-775a8019101f.jpg)

There could be some debate around the wording of the option, i.e should it be something like "keep recording (as new track)" to indicate that it will be recording into a new file, not the one you just saved.

Would you prefer for me to close this issue and reopen #8911, or continue discussing here? Or maybe I should rename this one to something like "add a 'keep recording' option"

**Comment by sonora** [comment]
Yeah  there's always the odd use case which is not on the majority's radar ... sorry!

As a temporary workaround, have you checked if always immediately tapping the REC button again after saving a track exactly restores the previous behavior?

If that works, but is not an acceptable workaround for you, I guess leaving this issue here open as is should be enough to get this discussed and decided with our product manager (@vshcherb ). 

I have to say that for myself I am always skeptical about introducing too many bells and whistles in the form of additional settings and options, where maybe only one percent of users ever use it, for the rest it creates clutter (and sometimes confusion, not to mention the risk of mis-tapping something and drain their battery in this case). And for us every line of code creates a mandate to maintain it. And for support, every new option is one more thing staff needs to know about amd understand in the first place, then create a fork in each ticket analysis, and check with or explain to the user.. It can quickly become a nightmare where good support becomes increasingly difficult, or, in your words, _'unhelpful'_. ;)

**Comment by AntiSol** [comment]
Well thanks, but there's no need to apologise, I don't expect you to be telepathic or to consult with me on every change ;)

Yeah, pressing rec immediately does start recording again. The issue with that is that I am long-habituated to not having to do that, so I have already not recorded a bunch of stuff that I wanted to be recording. I've remembered to press it a couple of times, but more often I forget. And now that I've reverted back to the older version I'm even less likely to remember (since it has my preferred behaviour and I don't have to remember, I'm probably pretty likely to stick at this version rather than upgrade tbh)

My philosophy WRT software development is different. Maybe you'd be interested to hear it: I think that you should (almost, every rule has exceptions) never change behaviour without giving users an option to revert to the old behaviour. So I think that you *should* add new options just about every time you change user-facing behaviour. The reason I have this philosophy is precisely because there's always that weird, odd guy who uses your software in a way that nobody knows about or would have ever considered, and that guy *will* notice when you change that thing that "nobody" cares about, and it *will* break his workflow, and he *will* raise an issue on your tracker, all indignant and annoyed because you changed the thing he relies on (and maybe also because he inadvertently trashed all his map files while downgrading to ensure that it wasn't something he imagined, necessitating restoring from a backup, putting him in a less-than-an-optimal-mood ;) ). Adding an option to revert to the previous behaviour solves that issue before it happens - if you label your option clearly that user is likely to find it by himself and never annoy you about it  :)

If you're worried about clutter, the option doesn't have to go on the save dialog, I'm not married to that idea, I just think it's probably the best place for it. But if you want to bury it somewhere in settings to avoid clutter on the save dialog, that's fine too, as long as I can revert it back to how it was.

As for the "every line of code creates a mandate to maintain it" argument, I see your point, and you're not wrong, but my philosophy there boils down to (to put it bluntly) "welcome to software development" ;). Every job has work that isn't fun. Maintaining your stuff is the not-fun part of coding, but it's a necessary evil we just need to deal with as coders. As for support staff, I feel like they should probably be watching changelogs and be across changes to the software as part of their job - changes to functionality are likely to cause support enquiries, so support staff should generally be across them, IMO. Communication is the key there. But having said that, I don't expect them to be all-knowing, that's not a reasonable expectation to have of any human.

To clarify, my "unhelpful" comment was aimed not at the lack of knowledge in the response I received from support, but in the fact that the response suggested the "auto-record track during navigation" option despite my having mentioned that I had already tried that option in my email. This gave me an impression that my email wasn't properly read and that my concern was being dismissed, and that's what ticked me off, not that the support staff aren't all-knowing :). But it's not a big deal, I just wanted to clarify that lack of knowledge wasn't the thing I was bothered by when I made that comment.

Anyway, enough philosophy. I'll leave this ticket here in the hope that we can get an option added to restore the previous behaviour. Thanks for your help.

**Comment by sonora** [comment]
Thanks for your thoughts, much appreciated!

There is definitely truth in every aspect mention. I just feel that often I have to stand up and play the advocate for "let's not bloat the tool too much", partly because everyone else seems often in a "the heck, let's add what we can" mode, and partly because I know a lot of people who appreciate simple, reliable tools that work over complex software dealing with which eats more time from their lives than it provides benefits in return.  :)

**Comment by AntiSol** [comment]
Hehe, and you know what? I totally appreciate your efforts in that respect, too: people doing what you're doing (and who I'll argue with in the name of functionality) mean that the code isn't too bloated. Because I'll *also* whinge if that happens ;)

But In my book, OsmAnd is already on the 'complicated' end of the scale. I think that people who prefer simple tools over complex software are all using the google spyware that came preinstalled on their phones, no? ;)

**Comment by vshcherb** [comment]
Hi @AntiSol 

Looks like use a bug as a feature, we've never designed that recording could work all time and actually never thought of that. So, I think the behavior might have changed between some releases. https://github.com/osmandapp/OsmAnd/issues/8911

**Comment by AntiSol** [comment]
It's SP3, apparently.
I'm not sure what the MD5 of the file should be? I checked it against a freshly downloaded copy on my Linux box and got the same md5 (which you can see in the attached screenshot, along with some other stuff)
![Screenshot from 2020-11-03 20:16:24](https://user-images.githubusercontent.com/351169/97968217-766c8480-1e12-11eb-8754-d4755b10e3f6.jpg)

**Comment by kocjs** [comment]
Me too...
Used this as future, i often just roam around. I helped me to find a nice place again...
I really hope this comes back as real future.

Thanks for this great app

**Comment by vshcherb** [comment]
New dialog is introduced, please test it.

**Comment by sonora** [comment]
Two issues I see immediately:
1. Hitting 'Save' on the mew dialog displays the wrong filename in the popup, it is missing the recording time. (But the file name actually used is correct).
2. To stop a recording you would natrually tap 'Stop', right? Now you are just one tap away from accidentally losing your entire recording, namely by accidentally hitting 'Stop without saving'. Please note that users may stop recordings while wearing gloves  or after exhausting races. We either need yet another nagging dialog asking if you are sure, or better entirely remove the option to discard recordings unsaved. Data safety first. Users can always delete unwanted tracks later?

**Comment by AntiSol** [comment]
where can I get an apk to test it?

**Comment by pebogufi** [comment]
https://download.osmand.net/latest-night-build/OsmAnd-android-full.apk

**Comment by AntiSol** [comment]
Thanks!

hmmm. i get:
````
$ wget https://download.osmand.net/latest-night-build/OsmAnd-android-full.apk
$ adb install OsmAnd-android-full.apk
Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package net.osmand.plus signatures do not match the previously installed version; ignoring!]````

**Comment by sonora** [comment]
The developer version is signed differently. You could try it on another device, or on the same device (and without uninstalling your primary installation) additionally install the developer of the **free **version, iz should be linked under downloads on osmand.net.

**Comment by sonora** [comment]
In addition to the technical blunders I report above: After playing with it some more, I find dialog and user guidance is totally bloated, we need to streamline: Nobody wants to tap 4 cosecutive buttons
- tap the widget
- tap Stop
- tap Save and stop recording
- tap Close
after just sprinting across the finish line, just in order to save the recording?!?

**Comment by pebogufi** [comment]
The free version is
https://download.osmand.net/latest-night-build/
OsmAnd-default.apk

**Comment by dmpr0** [comment]
@sonora 
Save button currently working as before, it saves the track just after tap. 
Now new users can see the "Stop" button, that clearly understandable. Mostly all other apps for trip recording have a "Stop" button. Before the new dialog, OsmAnd stopped recording after taping the "Save" button, that how I think understandable.
And it taping "Stop" doesn't stop it immediately, it has a second confirmation dialog.

**Comment by vshcherb** [comment]
Yes, agree we need to move "dangerous action" - 2 of them into 1 place:  
- Clear current recorded data
- Stop without saving. 

Practically I think it's better to have Save and always ask "Save & continue" / "Save & stop" with "Remember my choice".
In that sense we will have 4 actions:
1. Pause
2. Save
3. Clear
4. Start new segment

**Comment by pebogufi** [comment]
Gps is on.
immediately after starting recording new track i see the following window. What is it good for ?
version 31555 ( this morning)

![new window](https://user-images.githubusercontent.com/18628183/108206104-38c40b00-7126-11eb-85e2-bc89eb330342.jpg)

**Comment by dmpr0** [comment]
> Gps is on.
> immediately after starting recording new track i see the following window. What is it good for ?
> version 31555 ( this morning)
> 
> ![new window](https://user-images.githubusercontent.com/18628183/108206104-38c40b00-7126-11eb-85e2-bc89eb330342.jpg)

Hello!
I see few options:
Show on map
Clear recorded data
Start new segment
Save
Peuse
Stop
Close.

Also, you can change UI language in Menu – Settings – OsmAnd Settins – Display language.

**Comment by vshcherb** [comment]
This issue is closed (basically it's implemented). I started follow up to consider suggested changes. You can still comment here and use as a discussion issue. https://github.com/osmandapp/OsmAnd/issues/10924

**Comment by pebogufi** [comment]
@dmpr0 
I am sorry I am a bit late.
My posting was silly, because the first part of the handling was missing:
thwe windows posted above was the second window, this is the 
first windows:
![first window](https://user-images.githubusercontent.com/18628183/108228260-f955e880-713e-11eb-86cc-2424b358772c.jpg)

so:
Show on map  -- is duplicate
Clear recorded data  --is useless direct on start
Start new segment  --should be in first window 
Save  --is useless direct on start
Pause  --is useless direct on start
Stop  --is useless direct on start
Close --this button is ok.

For me the mentioned "second window" is useless at this position in the handling of starting the recording.
