### ISSUE TITLE
Bugs with Plan Route GPXs

### ISSUE THREAD

**Issue by SergeyP2** [osmandapp/OsmAnd#10118]
I've updated to 4.8.4 from 4.7, read "OsmAnd 3.8 (Android)" article and tried new "Plan Route" mode. I've added a few point with straight segments and one point with pedestrian auto-routing. Then I found a few problems:

1) I cannot split GPX on map. I go into GPX, set Split Interval, see splitting there, but when I return to map OsmAnd doesn't show me marks on track, and it also don't remember Split Interval when I return to GPX window again.

2) When I look a properties of GPX, like altitude graph, I see only part of the graph for pedestrian auto-routing section, but not for manual straight segments. Yet I have file with altitude lines downloaded for my region, so the app can easily find an altitude for straight segments - it can find approximate altitude for beginning and end point, and it can find exact altitude where straight segment crosses the altitude line. 

![Screenshot_2020-10-31-16-17-32](https://user-images.githubusercontent.com/22505250/97780775-4c576000-1b8f-11eb-8201-b7f4d288cebb.png)
![Screenshot_2020-10-31-16-18-22](https://user-images.githubusercontent.com/22505250/97780779-4f525080-1b8f-11eb-8183-fd7f0410d9f5.png)
[Gpx file.zip](https://github.com/osmandapp/OsmAnd/files/5469170/Gpx.file.zip)

**Comment by dmpr0** [comment]
Hello! Thank you for the feedback.
"Split interval" screen is made for analyzing data in the view of tables. If you want to view split marks on the map, you need to set in in the "Appearance" dialog.
OsmAnd gets altitude data for routing only from roads (not from Contour lines). When you use "Plan a route" altitude data will be available only for the parts with calculated routes, it was not available for straight-line segments.

**Comment by SergeyP2** [comment]
1. Thanks, "Appearance" dialog splits good!

2. I see no reasons why you can't add altitude from Contour lines. This is such a complex math? This also would help when a user open GPX without altitude information. Why to have a feature (altitude graphs) that works only in some conditions and don't work in some others -- this only to confuse the users of your app.
