### ISSUE TITLE
Moto G 8 Plus: map does not orient to compass direction

### ISSUE THREAD

**Issue by cdot** [osmandapp/OsmAnd#10110]
### Description
Orienting the map to the compass direction does not work; the map stays oriented stubbornly north. Other apps that use the compass work fine (such as Google Maps and SimplyWerx Compass 3.0.2).

### How to reproduce?
Switch to compass orientation

### Your Environment
OsmAnd Version: 3.8.3 2020-09-29
Android/iOS version: 10, build QPI30.28-Q3-28-26
Device model: Moto G(8) Plus, XT2019-1

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by KaiJan57** [comment]
Can confirm this issue on Moto G6 Plus running LineageOS, Android 11. All sorts of apps using the magnetometer can retrieve the device's orientation (e.g. GPSTest), but OsmAnd doesn't seem to recognise it at all; neither does orienting the map to compass direction work nor does the orientation indicator show up.

**Comment by cdot** [comment]
Sorry, I can't understand why this was closed. The original report stands, against OsMand 4.0.7. The device is a Moto G(8) Plus, which has a hardware magnetometer that works fine in other apps, just not in OsMand. There is no "Use magnetometer" setting either in OsMand or anywhere I can find in Android 10 settings.

**Comment by KaiJan57** [comment]
Yes, it's an extremely well hidden option in OsmAnd. I found it by navigating these menus:
Hamburger menu (sidebar that can be pulled out by swiping right) -> configure profile -> general settings. Scroll down and find the option 'use magnetic sensor' (sorry, my first translation did not match exactly). Here is the relevant section in the docs: https://docs.osmand.net/en/main@latest/osmand/personal/profiles#other
I hope this helps.

**Comment by cdot** [comment]
Good grief, that IS well hidden! Thank you. I can confirm that it is functional on my G8.
