### ISSUE TITLE
Slow download: 50kB/s

### ISSUE THREAD

**Issue by quazgar** [osmandapp/OsmAnd#10139]
### Description

For at least the last few days, download of maps have been very slow.  I first noticed this on the app (OsmAnd 3.8.4), but downloading files from http://download.osmand.net/list.php in the browser on a PC is just as slow:

- map data http://download.osmand.net/list.php: 50kB/s
- test files from https://speed.hetzner.de/: 8MB/s

### How to reproduce?

Download files from http://download.osmand.net/list.php

### Your Environment
OsmAnd Version: 3.8.4
Android/iOS version: Same on every machine
Device model: independent of hardware

**Maps used (online or offline):**   
Maps for several German states.

**Comment by vshcherb** [comment]
https://download.osmand.net/download?standard=yes&file=Anguilla_centralamerica_2.obf.zip
Main servers are not Hetzner
https://dl2.osmand.net/download?standard=yes&file=Anguilla_centralamerica_2.obf.zip
https://dl7.osmand.net/download?standard=yes&file=Anguilla_centralamerica_2.obf.zip
https://dl8.osmand.net/download?standard=yes&file=Anguilla_centralamerica_2.obf.zip

**Comment by vshcherb** [comment]
I think now servers are free to update
