### ISSUE TITLE
Search by category and filter by name

### ISSUE THREAD

**Issue by Spielmops** [osmandapp/OsmAnd#10137]
### Description
Search for a category, lets say "museum". Increase radius until you have a dozen results. Now go to settings of the category and type anything in " filter by name" and Ok it. Filter working. Good. Now try to reset this filter, remove the entry in "name". You can not Ok it, so it stays there.

Workaround: remove the name-entry and insert a space, then you can Ok it ...

Spielmops

### Your Environment
OsmAnd Version: 3.8.3
Android/iOS version: 8.0 Lineage 16
Device model:
Samsung Tablet S2

**Comment by dmpr0** [comment]
We couldn't reproduce the issue on the current release 3.9.10 and nightly version.
