### ISSUE TITLE
Add support for beauty=nails, shop=beauty

### ISSUE THREAD

**Issue by MarkusGaugg** [osmandapp/OsmAnd#10133]
OSMand don't support beauty=nails, shop=beauty as POI. Should be shown on the map like the rest of the beauty shops.

**Comment by xmd5a2** [comment]
OsmAnd does support them as POI. You can search by this tag. I disagree that `shop=beauty + beauty=nails` should have it's own icon because `beauty=nails` is additional tag and it doesn't changes meaning of main tag `shop=beauty`
