### ISSUE TITLE
water tap (potable water) icon

### ISSUE THREAD

**Issue by mariush444** [osmandapp/OsmAnd#10136]
May I ask you to add water tap icon to favorites (e.g. service tab)?

![image](https://user-images.githubusercontent.com/66887280/98163968-d67f2b80-1ee3-11eb-9d3f-643b3ff2a034.png)

**Comment by dmpr0** [comment]
Hi!
We have already added it, currently it only available in the nightly builds.
![Снимок экрана 2020-11-05 в 10 44 09](https://user-images.githubusercontent.com/9365308/98217983-e5052b80-1f53-11eb-9dbf-eadca77bc70a.png)
