### ISSUE TITLE
Search with 2 characters won't show any results

### ISSUE THREAD

**Issue by sedrubal** [osmandapp/OsmAnd#10141]
# Description
It looks like that it is not possible to search for POIs with a 2 characters name like the German drug store "dm". No results will be found, even if there are POIs with the exact same name near to the current position.

### How to reproduce?
Search for "dm" near a drug store called "dm".

### Your Environment
OsmAnd Version: 3.8.3
Android/iOS version: Android 9 (lineageos 16)
Device model: OnePlus 5

**Maps used (online or offline):** offline: Germany Bavaria

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/pull/10519

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/commit/ae9fc3234cbb766fa742e393fcbd3053e72c4173
