### ISSUE TITLE
'German (casual)' version of de TTS

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#10150]
Just to create a reference here to https://github.com/osmandapp/OsmAnd-resources/pull/646.

I have put in some work to implement, see https://github.com/osmandapp/OsmAnd-resources/commit/8ba9ea4a86df958d783d5c45fd07816d374e5d30, and also did some work to better initialize our TTS engine, which previously failed to set parameters correctly on some occasions (https://github.com/osmandapp/OsmAnd/commit/e9d00aef39c7a171ac757a82d4837a2a333566b7).

I would like to see some feedback here if this version 'German (casual)' of the de voice prompts is better than the traditional ones. I guess we should just leave both and let the user select?

**Comment by sonora** [comment]
PS: When testing, please pay particular attention to the facts that

- some prompts are significantly shortened ("links","raus"), which may or may not add to how easily they are understood with e.g. background noise or when in a conversation
- the turn pre-announcements (some distance out) are entirely suppressed
- that the voice contains "fahren" (as in "weiterfahren") and as such is not well suited for e.g. pedestrian routing.

Please give feedback and make suggestions so we can refine this!

**Comment by Hedaja** [comment]
Couple changes I would probably change in opinion



`
```
dictionary["follow2"] = tts ? "weiter auf" : "follow2.ogg";


dictionary["exceed_limit"] = tts ? "Höchstgeschwindigkeit" : "exceed_limit.ogg";
	
// OTHER PROMPTS
dictionary["location_lost"] = tts ? "Position verloren" : "location_lost.ogg";   // maybe change to "tschie pie es" because of pronounciation
dictionary["location_recovered"] = tts ? "Position gefunden" : "location_recovered.ogg";  // maybe change to "tschie pie es" because of pronounciation`
```

**Comment by sonora** [comment]
Thanks for the ferdback! But please note that 'weiter auf' das not fit the grammar here. And your other suggestions bring things length wise back to the ballpark of the original Grrman TTS voice, so the intended shortening is not achieved?

Please keep the feedback coming, I will monitor this issue from time to time.

**Comment by comradekingu** [comment]
Don't mess with the spelling to improve how it sounds. People might have other TTS engines, and it will likely improve.
Is it possible to use phonetic spelling?

**Comment by sonora** [comment]
Yes, definitely. But this is not the intent here, anyway. This is about shorter prompts by sometimes more casual language, and entire omission of some prompts.

**Comment by Spielmops** [comment]
I have edited the German-files several times, so i'm familiar with that. I do not find, how I can erase the announcements for long distances. They are all the same: "Kreiverkehr in 4km", "Kreisverkehr in 2km", "Kreisverkehr in 500m". If I delete "Kreisverkehr in" then I do not get any announcement "Kreisverkehr in" (text is example".

Spielmops

**Comment by sonora** [comment]
You are using the wrong tts voice, please download the new German (casual). In old versions of OsmAnd is is maybe displayed as de-casual. It contains no roundabout pre-announcements, and neither the word "Kreisverkehr".

**Comment by Spielmops** [comment]
> text is example

Where this new German-file? In Osmand the last version is from 21.11.

Speilmops

**Comment by Spielmops** [comment]
I  copied the text of "de-casual.js" into an editor (Linux) and stored the file in the normal folder of Osmand. In Osmand I can change to that language-file and test it: no speech. The logfile gives:
Couldn't retrieve ISO 3166 country code for locale de_modifiziert (the name of the folder).

Spielmops

**Comment by sonora** [comment]
@Speimops `voice/de-casual-tts/de-casual_tts.js`

**Comment by Spielmops** [comment]
On my device? No! Which version of Osmand? I have 3.8.5 installed ...
Spielmops

**Comment by sonora** [comment]
What I am saying is that if you name your folder/file as I specify above,, it should work, even before the next release?

**Comment by Spielmops** [comment]
Worked. I had a hyphen in the filename and no underline ...

**Comment by sonora** [comment]
You're welcome.

**Comment by pebogufi** [comment]
@sonora I love German casual, thanks for this idea.
Happy eggs searching !

**Comment by sonora** [comment]
@pebogufi  Thanks for the feedback! ;)
