### ISSUE TITLE
unit tests are broken

### ISSUE THREAD

**Issue by MakiWolf** [osmandapp/OsmAnd#10160]
1. The SearchUICoreTest
2. The OpeningHoursParserTest: I think that this is because in German it is "Fr" and and in English it is "Fri" 

![grafik](https://user-images.githubusercontent.com/73300633/98804475-8853b600-2416-11eb-8131-3563d73fd4cc.png)
![grafik](https://user-images.githubusercontent.com/73300633/98804671-b6d19100-2416-11eb-81f5-eddb9811d5b2.png)

**Comment by vshcherb** [comment]
That's interesting... Probably you can specify locale before you run unit tests cause all the tests passing at our site https://builder.osmand.net:8080/view/OsmAnd%20Builds/job/OsmAndMapCreator/lastCompletedBuild/testReport/

simply running gradle build

**Comment by vshcherb** [comment]
JVM params like https://stackoverflow.com/questions/8809098/how-do-i-set-the-default-locale-in-the-jvm

**Comment by Serjaru** [comment]
How disable tests?

Erros, erros!

SearchUICoreTest. testSearch[0: 100_bridge_street]
SearchUICoreTest. testSearch[13: olc]
SearchUICoreTest. testSearch[17: rolandstr]
SearchUICoreTest. testSearch[1: abbreviations]
SearchUICoreTest. testSearch[7: free_street_portland]
SearchUICoreTest. testSearch[9: hisar]
OpeningHoursParserTest. testOpeningHours

**Comment by Serjaru** [comment]
Mismatch for '55.79606, 37.56194' != '55,79606, 37,56194'. Result: 
CURRENT RESULTS: 
	"55,79606, 37,56194 [[0, LOCATION, 1,000, 6,52 km]]",
EXPECTED : 
	"55.79606, 37.56194 [[1, LOCATION, 1.000, 6.52 km]]",

. and , ???????????

**Comment by Serjaru** [comment]
1. You cant work with locale!!! WTF? For success test need set javas var:

JAVA_ARGS=-Duser.language=en -Duser.region=EN %JAVA_ARGS%
JAVA_TOOL_OPTIONS=-Duser.country=EN -Duser.language=en -Duser.variant=EN

2. Need set very big size Heap!!!!!!!
	dexOptions 
        {
		javaMaxHeapSize "4g"
	}

3. Gradle.prepo...
org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

4. Resources files: h_bare_rock2.xml, h_topo_bare_rock_night.xml, h_topo_bare_rock2.xml - VERY LONG VECTOR!!!!!!!! What are you thinking about?! Vector is very slow!!!!!!

**Comment by vshcherb** [comment]
@Serjaru too many exclamations, so I have almost missed a point. Thanks for the info how you've got the tests passing

**Comment by Serjaru** [comment]
i am update my comment above

**Comment by ravenfeld** [comment]
Hello, I have the same problem. I did not understand how you had disabled the test during the build.

**Comment by Serjaru** [comment]
> Hello, I have the same problem. I did not understand how you had disabled the test during the build.

add string to gradle.properties

org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -Duser.country=EN -Duser.language=en -Duser.variant=EN


"-Xmx2048m -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError " for more heap if need
and
"-Dfile.encoding=UTF-8 -Duser.country=EN -Duser.language=en -Duser.variant=EN" for success tests!

**Comment by joheb-mohemian** [comment]
Why was this closed? It looks like there are tests that depend on the user locale, and that is definitely a problem that should be solved.
