### ISSUE TITLE
gps usage is not always needed

### ISSUE THREAD

**Issue by alexbodn** [osmandapp/OsmAnd#10167]
hello friend, and thank you for osmand+.

the main purpose of this issue is saving expensive battery while outdoors. a good phone may work in the rain, but may rarely change.

currently, the gps is getting activated when osmand launches, and closes when osmand closes, with quite frequent calls for a fix in between.

it is not needed all the time, especially when standing for planning, or even when walking slowly, frequently calling a fix won't necessarily show any move.

I'm asking you to allow some profile to leave the gps activation to the user, so s/he could use the map view only and save battery.

the gps fix call may even annoy, think of planning a trip in a moving bus.

since another way to save battery would be using an external nmea gps, i would dare to ask for it, in the fashion that earthmate app is using inreach device.

thanks in advance,
alex

**Comment by pebogufi** [comment]
> I'm asking you to allow some profile to leave the gps activation to the user, so s/he could use the map view only and save battery.

Switching off gps on system menu is a good way for control, which is available without changing osmand. I use that since about 7 years !

**Comment by scaidermern** [comment]
> > I'm asking you to allow some profile to leave the gps activation to the user, so s/he could use the map view only and save battery.
> 
> Switching off gps on system menu is a good way for control, which is available without changing osmand. I use that since about 7 years !

This is a workaround, but not a very good once. Switching off GPS/Location services also affects other apps as well as Bluetooth Low Energy (BLE).

**Comment by vshcherb** [comment]
Well I would say switching off GPS globally is a better of other options than we've discussed.
