### ISSUE TITLE
Missing update 3.8.4 in F-droid

### ISSUE THREAD

**Issue by bege10** [osmandapp/OsmAnd#10185]
### Description
In Play Store I see version 3.8.4 from October 29, in F-droid the latest version is 3.8.3 from October 3.

Is this an issue of F-droid or of OsmAnd?

**Comment by Zahnstocher** [comment]
> Is this an issue of F-droid or of OsmAnd?

F-Droid

**Comment by comradekingu** [comment]
@bege10 OsmAnd devs aren't responsible for F-Droid builds, so you should close this and check the status of the build over at https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/net.osmand.plus.yml
I think you may have incompatible builds turned off in the settings.
