### ISSUE TITLE
Germany Saarland: can not update local map via download

### ISSUE THREAD

**Issue by monochromec** [osmandapp/OsmAnd#10188]
### Description

When trying to download a contour line, the download fails and the map reappears on the list of map to download 
### How to reproduce?

Download maps->Updates->Click on download arror

### Your Environment
OsmAnd Version: 3.8.3
Android/iOS version: Bardock (LOS 17.1)
Device model: Aquaris X

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
Germany, Saarland, Contour lines, Nov 12, 2020

More than happy to provide more info, just let me know.

[osmand.log](https://github.com/osmandapp/OsmAnd/files/5540768/osmand.log)

**Comment by vshcherb** [comment]
Unfortunately I'm not able to reproduce it. Probably it was a temporary issue

**Comment by monochromec** [comment]
I just doubled-checked and got the same result including similar log output. The only way to update these files was to delete them and to download them again manually.

**Comment by pebogufi** [comment]
Can't fix the problem by deleting the file (Saarland, Contour lines, Nov 12, 2020), nor by deleting inside app nor with a filemanager 
with two devices.
1 - Samsung tab S5e, android 10, OsmAnd~  3.9.0#30875m.apk
2 - Samsung S7, android 8, OsmAnd~  3.9.0#30900m.apk

Don't get a error message, no log file available. Just contour file remains same as before, in register for update.

**Comment by monochromec** [comment]
I suppose this is a stock OS, has anybody tested this with LO?

**Comment by marsianer** [comment]
Same issue on LineageOS

**Comment by marsianer** [comment]
![OsmAnd](https://user-images.githubusercontent.com/4650127/99909507-33068700-2ce9-11eb-962a-5c41687ec995.png)

**Comment by AnastasiaTiutina** [comment]
The same problem
Android 9 и 10 (Samsung Note9 and Lineage on Samsung S5)
![Screenshot_20201124-233432_OsmAnd_](https://user-images.githubusercontent.com/72389175/100217825-962c2f80-2f1c-11eb-97e4-96a9cfd74c44.png)

**Comment by AnastasiaTiutina** [comment]
the same problem
![Screenshot_20201128-204637](https://user-images.githubusercontent.com/72389175/100625259-f5c77800-332c-11eb-8eb5-9dce43777af2.png)

**Comment by AnastasiaTiutina** [comment]
The same problem 
Contur Lines: Germany Berlin, Hamburg and Mecklenburg Vorpommern

Device model: Sony G8441
Android: 9
Betrifft Update 12.11.2020, Höhenlinien **Deutschland Berlin, Hamburg und
Mecklenburg Vorpommern**

Device model: lenovo TB-8704F
Android: 8.1.0
Betrifft Update 12.11.2020, **Höhenlinien Deutschland
Mecklenburg-Vorpommern**

**Comment by AnastasiaTiutina** [comment]
![Screenshot_20201209-100120_OsmAnd+](https://user-images.githubusercontent.com/72389175/101806369-8ae02300-3b1c-11eb-8dfa-a9f74b8a93a1.jpg)
contour lines for Sweden

**Comment by LeBrunoG** [comment]
Hi everybody
Same problem on my side, with Sweden contour lines.
This is a recurring problem, as I have had it a few months ago with other contour lines.

Device model: Samsung Galaxy S9+, SM-G965W
Android/iOS version: 10
OsmAnd type: OsmAnd +
OsmAnd version: 3.8.4
The Latest maps update: 2020-Dec-10

**Comment by vshcherb** [comment]
We updated the map and unfortunately now we can't reproduce it any more. If it's still reproducible can you please share a screen or data from file manager and show what's the timestamp in OsmAnd / File System

**Comment by pebogufi** [comment]
![Saarland srtm problem](https://user-images.githubusercontent.com/18628183/101900911-8bc29480-3bb0-11eb-8c57-e6647c4e1214.jpg)

**Comment by Chumva** [comment]
I have added some logs about files to update, can anyone share them? 
Open `download maps` - `updates` - `reload`, then open `plugins` - `OsmAnd development` -  `logcat buffer` - `share` ( logs type - `*:I`)

**Comment by theraser** [comment]
Just hit this issue, too. Updates for contour (and only contour) aren't working for **some** regions for a couple of months. I could reproduce the issue i.e. with Berlin, but after deleting it via OsmAnd I could successfully re-download the contour file. There were no errors or anything else related to the downloads in the logcat.

Looking at the file timestamps: is it possible that the files are already updated but only the update notification got stuck?

I didn't delete und re-download the remaining contour files (see screen shot) and could offer a web based live screen sharing if this helps.

<img src="https://user-images.githubusercontent.com/7988080/103441264-ffeed600-4c4c-11eb-8744-8905998aef77.png" width="300">

> /Android/data/net.osmand.plus/files # ls -al srtm/                                                                                                                                                                     
> total 2359424
> drwxrwx--x  2 u0_a103 sdcard_rw      32768 2021-01-01 16:10 .
> drwxrwx--x 15 u0_a103 sdcard_rw      32768 2021-01-01 15:36 ..
> -rwxrwx--x  1 u0_a103 sdcard_rw   54163921 2020-11-12 13:01 Germany_baden-wuerttemberg_europe.srtm.obf
> -rwxrwx--x  1 u0_a103 sdcard_rw  110524747 2020-11-12 13:57 Germany_bayern_europe.srtm.obf
> -rwxrwx--x  1 u0_a103 sdcard_rw     610682 2020-11-12 11:54 Germany_berlin_europe.srtm.obf
> -rwxrwx--x  1 u0_a103 sdcard_rw   13657847 2020-11-13 08:01 Germany_brandenburg_europe.srtm.obf
> -rwxrwx--x  1 u0_a103 sdcard_rw  306680532 2020-11-13 09:27 Germany_europe.srtm.obf
> -rwxrwx--x  1 u0_a103 sdcard_rw     592686 2020-11-12 11:48 Germany_hamburg_europe.srtm.obf
> -rwxrwx--x  1 u0_a103 sdcard_rw   31721511 2020-11-12 12:23 Germany_hessen_europe.srtm.obf
> -rwxrwx--x  1 u0_a103 sdcard_rw    8660699 2020-11-12 11:51 Germany_mecklenburg-vorpommern_europe.srtm.obf
> -rwxrwx--x  1 u0_a103 sdcard_rw   17436944 2020-11-13 08:01 Germany_niedersachsen_europe.srtm.obf
> -rwxrwx--x  1 u0_a103 sdcard_rw   38505341 2020-11-12 12:31 Germany_nordrhein-westfalen_europe.srtm.obf
> -rwxrwx--x  1 u0_a103 sdcard_rw   42389569 2020-11-12 12:35 Germany_rheinland-pfalz_europe.srtm.obf
> -rwxrwx--x  1 u0_a103 sdcard_rw    8943195 2020-11-12 11:55 Germany_saarland_europe.srtm.obf
> -rwxrwx--x  1 u0_a103 sdcard_rw   11200247 2020-11-13 08:03 Germany_sachsen-anhalt_europe.srtm.obf
> -rwxrwx--x  1 u0_a103 sdcard_rw   19381007 2020-11-12 11:55 Germany_sachsen_europe.srtm.obf
> -rwxrwx--x  1 u0_a103 sdcard_rw    2789240 2020-11-12 11:49 Germany_schleswig-holstein_europe.srtm.obf
> -rwxrwx--x  1 u0_a103 sdcard_rw   30522379 2020-11-12 13:13 Germany_thueringen_europe.srtm.obf
> -rwxrwx--x  1 u0_a103 sdcard_rw    8611573 2020-11-12 12:04 Netherlands_europe.srtm.obf
> -rwxrwx--x  1 u0_a103 sdcard_rw 1299039733 2020-10-05 23:36 Norway_europe.srtm.obf
> -rwxrwx--x  1 u0_a103 sdcard_rw  410223504 2020-10-07 20:44 Sweden_europe.srtm.obf

**Comment by debyos** [comment]
Hi All,

the problem persists for me as well.

_Gábor_

![2020-12-30 19 37 11](https://user-images.githubusercontent.com/26843901/103443715-4438a100-4c62-11eb-8ba8-18fae56689db.jpg)

**Comment by vshcherb** [comment]
Help wanted: Anyone who is using latest nightly and have the bug reproduced, please share the Log file as mentioned here  https://github.com/osmandapp/OsmAnd/issues/10188#issuecomment-752041424

**Comment by pebogufi** [comment]
Used version: OsmAnd~  3.9.0#31226m.apk
srtm/Germany_saarland_europe.srtm.obf deleted with filemanager
then dnl within the app.  Again is available for dnl in register diwnload maps / updates. Need more help ?

[logcat_log.zip](https://github.com/osmandapp/OsmAnd/files/5765992/logcat_log.zip)

**Comment by vshcherb** [comment]
Log says the local saarland map is 09/13/2020 do you have any map from September?

**Comment by pebogufi** [comment]
As you can see in my posting above 24 days ago, screenshot with black background, the srtm file was from 2020-11-12 11:55.
But when downloading again after deleting with filemanager it was with orange symbol, which is wrong, is should have been black, so garbage in cache ?
Now again:
deleted with filemanager
then dnl within the app. Now symbol is black, no more dnl in update available. So, now it fixed? ---NO.
After opening update page and refresh, update is available again.
One mog logcat:
[Logcat2_log.zip](https://github.com/osmandapp/OsmAnd/files/5766237/Logcat2_log.zip)

**Comment by pebogufi** [comment]
from logcat:
date 12.11.20 indexActivatedDate 14.09.20 indexFilesDate 14.09.20
I think both indexes are wrong.

**Comment by LeBrunoG** [comment]
Retried to load the Sweden contour lines.
No success
This is a recurring problem, as I have had it a few months ago with other contour lines.

LogCat included:
Device : star2qltecs
Brand : samsung
Model : SM-G965W
Product : star2qltecs
Build : QP1A.190711.020.G965WVLU8FTK1
Version : 10
App Version : OsmAnd+
Apk Version : 3.8.4 384

[logcat.log](https://github.com/osmandapp/OsmAnd/files/5771302/logcat.log)

**Comment by vshcherb** [comment]
@LeBrunoG plese change debug level to Info, cause logcat has only errors and no interested information

**Comment by vshcherb** [comment]
@pebogufi 
Well one of the file is 14.09.20 but I couldn't understand what's file
- Saarland, Contour lines, - date 12.11.20 11:55 CET. Size without zip 8943195, with zip 6064862.

Could you try to delete indexes.cache, so the index cache is fully rebuilt.

**Comment by pebogufi** [comment]
Deleted ind.cache, Germany_saarland_europe.srtm.obf with file manager, cleared osmand from tasklist, restarted, dnl saarland srtm.
opening update page and refresh.
no more update possible, so
PROBLEM IS FIXED FOR ME.
Test with second device, latest nightly, same processing, also OK.
Thanks a lot. Peter

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/commit/f27c397835cfdbad581f963723479d86b1e7dfbc fixed

**Comment by LeBrunoG** [comment]
> 
> 
> @LeBrunoG plese change debug level to Info, cause logcat has only errors and no interested information

Don't know how?
Debug plugin - parameters - buffer logcat ? what else?

**Comment by pebogufi** [comment]
If logcat is open (visible) look in the upper right corner. Tap (multiple) on the symbol, it can have the values:
*:I, *:D, *:W, *:E
Looks like a filter.
"Info" looks like *:I ?

**Comment by vshcherb** [comment]
The issue is identified and fixed. As a workaround you can delete indexes.cache

**Comment by LeBrunoG** [comment]
Same for me.
Sweden contour file deleted
Osmand+ stopped
idexes.cache deleted,
Osmand+ restarted
Sweden contour file reloaded.
After completion does not appear in the map update list.
THANKS.
Bruno

**Comment by LeBrunoG** [comment]
Here's the logcat *:i
But the workarond worked for me.
THKS

Device : star2qltecs
Brand : samsung
Model : SM-G965W
Product : star2qltecs
Build : QP1A.190711.020.G965WVLU8FTK1
Version : 10
App Version : OsmAnd+
Apk Version : 3.8.4 384
[logcat.log](https://github.com/osmandapp/OsmAnd/files/5783989/logcat.log)
