### ISSUE TITLE
Feature Request: Add "Coordinates widget" toggle to Quick action button

### ISSUE THREAD

**Issue by speleoluc** [osmandapp/OsmAnd#10196]
Toggling the display of the Coordinates widget should be added to the list of possible actions of the Quick action button.

**Comment by dmpr0** [comment]
We need to 
- add a new section in the quick action list "Configure screen"
- Name "Show/Hide coordinates widget"
- Icon "ic_action_coordinates_widget"

**Comment by dmpr0** [comment]
We need to:
**add a new section in the quick action list "Configure screen"**
Name "Show/Hide coordinates widget"
Icon "ic_action_coordinates_widget"

**Comment by vshcherb** [comment]
Naming of "Show/hide ... " is very inconsistent - make a unique expression to clean up it

**Comment by dmpr0** [comment]
# Review 
- [ ]  Added action list, should use the same scheme for naming "Show/Hide – Coordinates widget"
- [ ]  Quick action bar on the map: implement similar scheme "Show – Coordinates widget" or "Hide – Cooridnates widget"

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/112013770-97681480-8b2a-11eb-8bd2-def308bc5396.png)

**Comment by dmpr0** [comment]
# Review 3
- [ ]  Quick action list: name should contain "Show/Hide – Finance" for "Show/Hide – POI" action. Currently, it shows only "Finance". The quick action bar on the map works perfectly (changing between Show/Hide depending on the state).   
**Example:**
Original action name: "Show/Hide - POI".
Action edit screen: "Finance"
Quick action list: "Show/Hide - Finance"
Quick action bar on the map: "Show – Finance", "Hide – Finance" depending on state.
