### ISSUE TITLE
Routing: Cycleways avoided in favor of parallel roads

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#10191]
OsmAnd avoids cycleways and takes parallel roads instead. The route is straight along a road which has a cycleway (lane, shared_lane and track). Instead of taking this road OsmAnd prefers to route along a parallel road:

![photo_2020-11-15_19-18-09](https://user-images.githubusercontent.com/1040784/99193166-7c018d00-2777-11eb-9da8-4cc0cf25f8d9.jpg)

When setting many via points OsmAnd finally sticks to the road with the cycleways:
![photo_2020-11-15_19-18-13](https://user-images.githubusercontent.com/1040784/99193169-7e63e700-2777-11eb-8f63-6973ff835829.jpg)

The second option is both faster and safer.

Route:[ 51.04220, 13.79798](https://www.openstreetmap.org/#map=16/51.0422/13.79798) to [51.03543, 13.81753](https://www.openstreetmap.org/#map=16/51.03543/13.81753)

- BRouter (fine): https://brouter.de/brouter-web/#map=16/51.0396/13.8090/osm-mapnik-german_style&lonlats=13.797981,51.0422;13.817526,51.035435
- GraphHopper (fine): https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=51.0422%2C13.7980%3B51.0354%2C13.8175
- OSRM (also somewhat weird): https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=51.0422%2C13.7980%3B51.0354%2C13.8175

**Comment by xmd5a2** [comment]
11 traffic signals are located on this highway. Routing decide to avoid them by taking parallel roads. Yes, some traffic signals are counted twice because engine for now can't distinguish two close signals when they actually are one, but anyway, looking at map data I suppose that routing engine is taking right decisions.

**Comment by scaidermern** [comment]
> looking at map data I suppose that routing engine is taking right decisions.

No, it definitely isn't.

The route suggested by OsmAnd crosses the large secondary road three times (2x at the beginning, 1x at the end), which is both slow and dangerous. Furthermore the suggested route is along many residential crossings. At each crossing you need to slow down because vehicles from the right have right-of-way. This is also pretty slow (and somewhat dangerous).

OsmAnd's penalty for traffic lights is too high and it doesn't handle the `traffic_signals:direction` key correctly.

Please fix the above routing issue. OsmAnd's bicycle routing in cities is currently pretty useless.

**Comment by vshcherb** [comment]
Unfortunately we don't support roads intersection and to be honest it doesn't mean it should be penalized immediately. 
Obviously we can ignore traffic_signals and it will make routing straight though it doesn't mean that's good approach cause traffic_signals is quite a significant waste of time comparing to roundabout or bridge. 

So I think we need to find how it could be tagged properly or introduce a local setting to disable traffic signals penalty

**Comment by scaidermern** [comment]
The traffic signal penalty feels a little bit incomplete given that the direction of the traffic signals is ignored and that no corresponding penalty for intersecting roads of the same class is applied. Either penalize all of these cases or none of them. The current implementation leads to large roads being penalized because small roads usually have fewer traffic signals. This can't be correct.

**Comment by vshcherb** [comment]
I don't think intersections should be penalized, there should be a rule why person should stop at intersection if it is not present then that route is simply faster.

**Comment by scaidermern** [comment]
No, there is no need for penalizing all intersections. However in this case the route proposed by OsmAnd leads through many intersections with roads of the same class and priority. On each intersection there is [_priority to the right_](https://en.wikipedia.org/wiki/Priority_to_the_right). There are neither _give way_ nor _priority road_ signs (see examples [01](https://www.mapillary.com/map/im/8YOUlBPIC5hCXrIiWd4vdA), [02](https://www.mapillary.com/map/im/h37TeAQS53ldCNVGc1iALg) and [03](https://www.mapillary.com/map/im/oJK6oPwA7OwR02eB_8LuNA) at Mapillary) because this is an implicit traffic rule. At each intersection you have to slow down, check if there is any traffic coming from the right, then accelerate again. This is slow, and especially exhausting on a bicycle. If you want to drive fast through these intersections then this becomes dangerous in case you overlook the vehicle coming from the right or the vehicle coming from the left overlooks you. So you have to choose between slow+safe or fast+dangerous (as usual, of course).

This right-of-way system is pretty common all over Europe. If you want to penalize traffic lights, fine, this is a good thing because they slow you down. However there are other things which slow you down as well. Either consider all of them, or you will end up with such bad routing advises as in the initial screenshots.

**Comment by vshcherb** [comment]
In original issue the line is pretty straight except the first segment which deviates to the left -> right - obviously this is very inconvenient. I think the first segment depends very much on the starting point (lower point won't have it), though of course fine tuning of routing will improve it. However fine mapping would also change situation, so I don't think we need to close the bug, so later we could combine with other issues and reiterate it.

**Comment by scaidermern** [comment]
Slightly improved route with OsmAnd 4.0.2.

![photo_2021-07-30_07-20-06](https://user-images.githubusercontent.com/1040784/127604420-6f548fd2-12e2-4336-9988-fd12b021dcb7.jpg)

The detour to the north right at the beginning of the route is gone. However most of the route is still not on the cycleway that is on the parallel road to the north.

**Comment by xmd5a2** [comment]
Issue is related to routing engine bug https://github.com/osmandapp/OsmAnd/issues/12238

**Comment by Flexmaen** [comment]
I did to several tests with bike navigation recently and noticed that commercial solutions are currently the best while OSMAnd isn't really doing well. In some cases it even tried to send me through walking paths and forbidden private roads, etc.

However, Graphhopper as open source solution is getting close and doing a good job. Why not taking the code from there?

**Comment by ivanPyrohivskyi** [comment]
https://www.openstreetmap.org/way/210462946

**Comment by alisa911** [comment]
Hi @scaidermern. Thanks for reporting this. The expected route has longer routing time due to a lot of traffic lights. We will reconsider this penalty and possibly reduce it. 
To solve this particular issue we need to reduce the penalty from 15 to 5.

**Comment by alisa911** [comment]
The expected route has longer routing time due to a lot of traffic lights. To solve this particular issue we need to reduce the penalty from 15 to 5.

**Comment by scaidermern** [comment]
I'm not sure if this is a good idea since 5 seconds seems rather low to me. Adding a penalty for traffic lights is a good idea in general. But only if there are other penalties, too. For example penalties for intersections with right-of-way (see https://github.com/osmandapp/OsmAnd/issues/10191#issuecomment-732019605). Without these additional penalties the router will make bad decisions as in this example.

**Comment by vshcherb** [comment]
@scaidermern in case you know that traffic signals direction mapping or calculation is wrong (for example because traffic signals don't affect cyclists), please let us know. In other case we consider that parallel routing is simply faster because of too many traffic signals

**Comment by scaidermern** [comment]
> @scaidermern in case you know that traffic signals direction mapping or calculation is wrong (for example because traffic signals don't affect cyclists), please let us know. In other case we consider that parallel routing is simply faster because of too many traffic signals

Traffic signals directions should be fine. Also they _do_ affect cyclists. Nevertheless I consider it a bad choice to avoid the road that has both cycling infrastructure and the right of way. The parallel road has neither a cycling infrastructure nor the right of way. Instead, on the parallel road you have to slow down before _every_ intersection because there is right of way from the right. Not doing this will be dangerous.

But I'm repeating myself. In my opinion this ticket needs to stay open. Routing decisions like this make OsmAnd a bad router for cyclists.

**Comment by vshcherb** [comment]
>  Instead, on the parallel road you have to slow down before every intersection because there is priority to the right

We could/ should introduce the penalty for that as we do for car routing especially if there is no cycling infrastructure. Please let us know if give_way is properly mapped

> But I'm repeating myself. In my opinion this ticket needs to stay open. 
Only the tickets that has clear path to fix should stay open, if we don't understand how to change weights or what new tags should be calculated or from top level analysis the route is not worse (we're not talking about real experience) there is no sense keep it open, as no action could be done

**Comment by scaidermern** [comment]
> > Instead, on the parallel road you have to slow down before every intersection because there is priority to the right
> 
> We could/ should introduce the penalty for that as we do for car routing especially if there is no cycling infrastructure. Please let us know if give_way is properly mapped

Do you mean `highway=give_way` signs? No. There aren't any signs present at these intersection. The priority to the right is implicit since all roads are of the same class. This implicit rule exists in many countries. I don't know of any tagging scheme to represent this in OSM. But maybe I missed something?

**Comment by vshcherb** [comment]
Well in that case we can consider to introduce penalty for every 4 road intersection let's say

**Comment by scaidermern** [comment]
That could be a possible approach. Not sure how it would influence such situations.

**Comment by mnalis** [comment]
> Well in that case we can consider to introduce penalty for every 4 road intersection let's say

So, _"a 1000 meter road with cycling infrastructure and 4 crossings"_ would have a same priority as _"a 1000 meter road **without** cycling infrastructures but also **without** any crossings"_ ? 

That might be a good starting point. The exact number would need to be tested in practice, though. In my opinion, road with cycling infrastructure should definitely have much higher priority in bicycle routing mode than one without any cycling infrastructure - there is a reason that money is being thrown into developing extra cycling infrastructure...

Is there (or could there be) a way an advanced user can change such crossing penalty without recompiling the code (perhaps like an advanced setting, or editing importing JSON/XML file, etc)?

**Comment by vshcherb** [comment]
Unfortunately there is no parameter yet to put a penalty for a junction but we can open a new issue to implement it :-)

**Comment by vshcherb** [comment]
Note: I'm not saying there is nothing could be done with actual configuration though unfortunately none of our team managed to find any configuration parameter except traffic signals which we don't want to do for other tests. 
@scaidermern feel free to play around with routing xml and OsmAndMapCreator.
