### ISSUE TITLE
Set lower buttons when creating an OSM note

### ISSUE THREAD

**Issue by franco999** [osmandapp/OsmAnd#10193]
### Description
When writing a long note, the lower buttons are lowered so much that they end up disappearing from the screen. 
**Can this be corrected so that they remain fixed, no matter how long the note is?**

<img src="https://user-images.githubusercontent.com/12088580/99195050-1d7de400-2762-11eb-903b-1e14647da173.jpg" width="30%" height="30%">

### Your Environment
OsmAnd Version: OsmAnd~ Nightly v3.9.0#30882m (390)
Android/iOS version: Android 10 (crDroid v6.12)
Device model: Xiaomi Mi A2 Lite

**Comment by vshcherb** [comment]
Fixed

**Comment by franco999** [comment]
No fixed. The buttons are hidden at the bottom and no options can be made with the notes.
<img src="https://user-images.githubusercontent.com/12088580/100234025-42fcb180-2f09-11eb-9ec6-94ea6cfac661.jpeg" width="30%" height="30%">

**Comment by Chumva** [comment]
This should be fixed here - osmandapp/OsmAnd#10319.
