### ISSUE TITLE
Feature Request: Simple tool to measure a straight line distance between two points

### ISSUE THREAD

**Issue by speleoluc** [osmandapp/OsmAnd#10208]
I use OSMAnd+ for paddling, without directions, just to follow my current position and sometimes record my track. I wish it had a simple tool to measure a straight line distance between two points (two fingers?).

**Comment by sonora** [comment]
Already exists: Menu/Configure screen/Radius ruler will enable the 2 finger distance tool.

**Comment by speleoluc** [comment]
I had turned on this radius ruler, but thought only the circle mode existed. Thanks!
