### ISSUE TITLE
Make OsmANd GPX compatible with BaseCamp

### ISSUE THREAD

**Issue by AnastasiaTiutina** [osmandapp/OsmAnd#10209]
### Description

Faulty import file for Garmin Basecamp 

![gcflmekafoacpinl](https://user-images.githubusercontent.com/72389175/99291205-1af5ba00-2848-11eb-893c-1fd1425b444a.png)
![gcflmekafoacpinl](https://user-images.githubusercontent.com/72389175/99291224-20530480-2848-11eb-9e9d-20e28970a79a.png)
![icikfldmlnamcaoc](https://user-images.githubusercontent.com/72389175/99291229-22b55e80-2848-11eb-888a-2e5757ae1406.png)
![noemjjdiaohhdlac](https://user-images.githubusercontent.com/72389175/99291233-23e68b80-2848-11eb-8c35-a7653a7e3b7c.png)

### How to reproduce?

In your guide on the web you describe how to make GPX files from Osmand 
compatible to Garmin-BaseCamp / Mapsource using GPS-Babel.

I converted the file with these parameters with GPS-Babel:

The file format does not fit:

The files can be found in the attachment.

From my point of view it would be much better if the XML format of 
OsmAnd was basically compatible, so there would be no conversion at all.

One more hint: Planning GPS tracks for Garmin devices works without any 
problems. I like to show in my GPS trainings how easy it is to create a 
GPX track for an Edge or Fenix device with OsmAnd and transfer it to the 
device with Garmin-Connect. This can be an alternative for Komoot for 
many people. I have subsripted the OsmAnd version for iOS and Android.

**Comment by jensMF** [comment]
related to #1326

**Comment by jensMF** [comment]
@AnastasiaTiutina can you open this file in BaseCamp:

[2021-01-02_20-28_Sat_test.txt](https://github.com/osmandapp/OsmAnd/files/5760984/2021-01-02_20-28_Sat_test.txt)
(You need to rename it from .txt to .gpx)

?

**Comment by vshcherb** [comment]
Looks like it's fixed with merge #1326
