### ISSUE TITLE
Copy whole group of favorites / edit appearance for whole group

### ISSUE THREAD

**Issue by AnastasiaTiutina** [osmandapp/OsmAnd#10210]
- Mark all favorites in a folder
- copy single or multiple selected favorites and paste them into another favorite folder
- if all favorites in a folder are marked, they can be assigned to another/new symbol in one go.

**Comment by dmpr0** [comment]
+1 Request from the user to add an option to copy a whole group of favorites into another.

**Comment by vshcherb** [comment]
This issue should be split into copy appearance and copy favorites. For now we don't allow to copy favorites at all but we allow to move favorites from one group to another. Copying will make unmanageable duplicate on the map

**Comment by Rafael921026** [comment]
Hola se que se puede mover un punto de un favorito a otro pero lo que yo necesito por mi trabajo es mover todo un grupo de favoritos a otro. Gracias
