### ISSUE TITLE
Un-gzip 'descritption' field's content for POI menu

### ISSUE THREAD

**Issue by MadWasp79** [osmandapp/OsmAnd#10226]
### Description
After adding 'description' key to POI data in maps, we have a problem with showing it's content in mapContextMenu
![image](https://user-images.githubusercontent.com/13146346/99642382-1ef62780-2a54-11eb-9a58-6647ec0e0c58.png)

### How to reproduce?
For now it could be reproduced with live update of germany-saxony map.
https://www.openstreetmap.org/node/4515797208#map=19/50.56626/12.13139

### Your Environment
OsmAnd Version: 3.9.3
Android/iOS version: -
Device model: -

**Maps used (online or offline):**   
Live updates for November Offline maps

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/commit/9fa21ef01c305364e507996cf681dacf4c136da7

**Comment by Chumva** [comment]
Should be fixed here - https://github.com/osmandapp/OsmAnd/commit/88edf800d0fc3e28835fbbf514161dd0335315c6. But there might be additional fix in maps creator.

**Comment by Ivans-Git** [comment]
Also in urls
