### ISSUE TITLE
TTS: Portuguese European = Portuguese Brazilian in OsmAnd

### ISSUE THREAD

**Issue by AnastasiaTiutina** [osmandapp/OsmAnd#10232]
TTS problems with Portuguese European
Check Portuguese European and the Portuguese Brazilian.
They sound the same and it looks like both variants are Brazilian Portuguese during navigation

Link to differences between Portuguese European (autocarro) and Brazilian (ônibus )
https://youtu.be/EA429o8uFxk

**Comment by sonora** [comment]
Can you please temporarily enable OsmAnd's development plugin, go to its settings, use entry 'Test voice prompts', and provide one screenshot each for the populated test button (11.1).

**Comment by vshcherb** [comment]
There is no difference if you select pt-br or pt tts voice.
But there is a difference if you select in Android settings -> Preferrred System settings. So probably we don't pass extra locale parameters 


![telegram-cloud-photo-size-4-5911254530362816374-y](https://user-images.githubusercontent.com/1042025/146810969-c420b54f-365f-4a3c-9953-bbb1383e4ad8.jpg)

**Comment by vshcherb** [comment]
Linked to https://github.com/osmandapp/OsmAnd/issues/13737
