### ISSUE TITLE
Gpx-editing issue

### ISSUE THREAD

**Issue by MScos** [osmandapp/OsmAnd#10245]
### Description
In former versions it was possible to edit gps-recorded tracks. I often delete some points at the beginning or the end to have more accuracy..

### How to reproduce?
Now, when I want to edit my record, OSMand tells "route between points: next, snap your track to the nearest allowed road with one of your navigation profiles to use this option"
It doesn't matter, what I choose, OSMand converts my record into a track with a minimum of points and without timestamps.

I was so happy to find "trim before" / "trim after", but this is useless for me with the issue told above. 

Please resolve this.  

### Your Environment
OsmAnd Version: 3.8.5
Android version: 10
Device model: Poco F1

**Comment by vshcherb** [comment]
I think you should be able to edit track without converting it to "route between points", you probably missed cancel button to click.

**Comment by MScos** [comment]
Unfortunatly I did not miss to click the cancel button. It doesn't matter, what to click.
After this, I can make my changes, for example delete some points. With "Done" or "Save changes" to finish my edit OsmAnd makes a copy of my recorded track. The original recorded track is then not changed. The new copy has the changes included, but does not have any timestamps. The overview in My Places is then confusing too.. Before and after pics following.
 
![Screenshot_20201120-225136_OsmAnd~](https://user-images.githubusercontent.com/74782748/99853310-07698c80-2b83-11eb-9142-0f7f9b9b08f9.png)

![Screenshot_20201120-223507_OsmAnd~](https://user-images.githubusercontent.com/74782748/99852966-5d8a0000-2b82-11eb-973f-6af2bbe6c2f1.png)

I musst say, that I'm using the f-droid version of OsmAnd..

**Comment by alex-osm** [comment]
Should be fixed in the next release
