### ISSUE TITLE
Gpx-editing issue

### ISSUE THREAD

**Issue by MScos** [osmandapp/OsmAnd#10248]
### Description

First of all:
By GPS recorded gpx-file: "record" 
By e.g. Plan a route produced gpx-file: "track" 

Refers to #10245 (imo closed without solution, tried to make a better description now)

Edit of record produces a copy of type track, which contains changes -> without time information. Original record is not changed. 

In former versions it was possible to edit records. I often deleted some points at the beginning or the end to have more accuracy..

### How to reproduce?
My Places -> Tracks
My example in folder Hike -> "2020-06-12 11-14 Fri" (see pics below)
-> Edit
-> Dialoge:
"route between points: next, snap your track to the nearest allowed road with one of your navigation profiles to use this option"
-> It doesn't matter, what I choose (Cancel / Continue) 
-> make edits
-> Done / Save changes (doesn't matter) 

Before edit:
![Screenshot_20201121-224712_OsmAnd~](https://user-images.githubusercontent.com/74782748/99888659-d8205180-2c4e-11eb-82f9-4fbc9031e175.png)
![Before](https://user-images.githubusercontent.com/74782748/99888586-40bafe80-2c4e-11eb-93f1-8a818609fea5.png)

After edit:
In my example I changed segment 1 of 2. Only the changed segment is saved as track.
Consusing overview in My Places (0m record/track-lenght) 
![Screenshot_20201121-230952_OsmAnd~](https://user-images.githubusercontent.com/74782748/99888668-e40c1380-2c4e-11eb-8cf6-1535b90b155a.png)
![After](https://user-images.githubusercontent.com/74782748/99888599-50d2de00-2c4e-11eb-913a-1b9c200a8e8e.png)

Original record is not changed.
It doesn't matter, if it is a 1 segment or 2 segment record.

Refers to F-droid versions 3.8.5 + 3.8.3
Worked fine with 3.7.4

### Your Environment
OsmAnd Version: F-droid 3.8.5
Android version: 10
Device model: Poco F1 + Huawei P Smart 2019

**Comment by AnastasiaTiutina** [comment]
We are not responsible for the F-Droid version of the app. That version is assembled by the F-Droid staff from our source code on Github.

**Comment by AnastasiaTiutina** [comment]
Osmand 
version 3.8.4 released 29.10.20
I am editing a recorded track:
1) Open menu in the lower-left corner (Burger Menu)
2) Select  My places
3) Select a recorded track under Tracks
4) Track overview with data like distance. duration, start time, altitude profile... appears
5) Move this overview to the top.
6) Open menu in the lower-left corner (Kebab menu)
7) Select Edit
8) Close dialog "Route between points" with "Cancel
9) Move the map as desired and set an additional point
10) Press the "Add" button at the bottom right
11) Press "Done" in the upper right corner
12) Track is saved with the same name but in a different directory
13) Open this track
14) You only see the route points, not the data as described under 4)

On the execute overview page (point 1) and 2) you see two tracks with the same name.
One of them is the original track and the other one is the one described in points 13) and 14).

If you open the original track, you will see the added point there, but you will have two "destination points".
If you now delete the non-original track, the waypoint added in point 10) will disappear from the original track.

So you will not be able to add points to the original track anymore, e.g. if you started recording the track too late.

**Comment by MScos** [comment]
> We are not responsible for the F-Droid version of the app. That version is assembled by the F-Droid staff from our source code on Github.

This is what I thought and its really ok.
But although I'm no programming specialist, I wondered if this could be a general problem.
Am I right, that you reproduced your second comment in the Play Store-Version?

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/10245 cause it's the same issue
