### ISSUE TITLE
Is OsmAnd support the Gyroscope?

### ISSUE THREAD

**Issue by bozzlab** [osmandapp/OsmAnd#10253]
Hi, I would like to ask, Is OsmAnd support  the Gyroscope?   
or it already have it. I just have to enable some configuration?

**Comment by vshcherb** [comment]
I'm not aware, so I think no

**Comment by sonora** [comment]
Gyroscopes are massive battery eaters. And gyroscopes measure rotation, i.e. when you tilt your device.

**Comment by bozzlab** [comment]
> Gyroscopes are massive battery eaters. And gyroscopes measure rotation, i.e. when you tilt your device.

I see, Thanks for comment
