### ISSUE TITLE
lack of linked picture when data name contain any special characters

### ISSUE THREAD

**Issue by AnastasiaTiutina** [osmandapp/OsmAnd#10257]
The linked picture is only displayed if the data name does not contain any special characters.

It must be a problem with the URL-coding and/or conversion URL-coding to ASCII.

ALL linked pictures, which use URL-coding (special characters in URL) will not work/display in OsmAnd.

In German, there is an 'ö, ä, ü, ß' as special characters, the described problem occurs whit every language, as soon as using special characters.
https://www.openstreetmap.org/node/7856116041
![screenshot-1606126086449](https://user-images.githubusercontent.com/72389175/99951095-33a12b00-2d86-11eb-94d4-9cd2cd62be55.jpg)

https://www.openstreetmap.org/node/6737828651
![screenshot-1606126816449](https://user-images.githubusercontent.com/72389175/99951154-487dbe80-2d86-11eb-9ef6-0c8debb01097.jpg)

**Comment by Katze0815** [comment]
Hi,

I'm Steffen, I reported the issue.
But OsmAnd support does a little mistake.

**WORKING nodes:** 
[https://www.openstreetmap.org/node/7856116041](https://www.openstreetmap.org/node/7856116041)
[https://www.openstreetmap.org/node/7856116041](https://www.openstreetmap.org/node/7856116041)

In both examples the filenames of the linked pictures contain no special characters. 



**Examples who NOT working in OsmAnd, picture was NOT displayed:**

[https://commons.wikimedia.org/wiki/File:%C3%84lvkarleby_June_2013_(2).jpg](https://commons.wikimedia.org/wiki/File:%C3%84lvkarleby_June_2013_(2).jpg)

**URL/file names that nor working:**
File:Білий слон.jpg
File:縦 横 (5233856489).jpg
File:さざんか.jpg
File:ಅಲುಮೀನಿಯಮ್ ಹಾಳೆಯ ಮೇಲೆ ಹಾಕಿರುವ ಪಲ್ಪ್.jpg
File:அண்ணா நூற்றாண்டு நூலகம்.jpg
File:تزیینات زیر برج.JPG
File:تصویری از برج آزادی.JPG
File:אצת הספירולינה.jpg.
I think this is an important problem, thousands of linked pictures were not displayed in OsmAnd!

**Kind Regards,
Steffen**

**Comment by Katze0815** [comment]
Add comment:

**Both screenshot from OsmAnd support (not my own), in first posting DO NOT SHOW THE NODES!!!! Therefor no pictures was displayed!**

Kind Regards,
Steffen

**Comment by AnastasiaTiutina** [comment]
Katze0815, can you add coordinates to check. Not the pictures

**Comment by Katze0815** [comment]
Hello,

here is an OSM node, linked picture will NOT displayed in OsmAnd:

https://www.openstreetmap.org/node/8126709325

I hope this will help you. 👍 

Kind Regards,
Steffen

**Comment by AnastasiaTiutina** [comment]
This object was added recently (7 days ago). It will appear in OsmAnd in a month. By the way, there are no special characters in the object that you have sent.
There are special characters but they are in the link. The image in the tag displays correctly.
![2020-11-23 17 12 02](https://user-images.githubusercontent.com/72389175/99979078-690e3e80-2daf-11eb-9a25-df807699fb29.jpg)

**Comment by Katze0815** [comment]
@ Anastasia

Thank you for helping.

Well, the node was edited by user Raymond 4 days ago. Raymond confirmed the problem to me. And I can see, 4 days ago, he edited the node again.

I use OsmAnd Live, so I must not wait 1 month to get the actual map. 👍 

As you can see, there is one other problem with the description text. I reported this issue here: 
https://github.com/osmandapp/OsmAnd/issues/10226

I will try to find a not working example, or I create a test object by myself.

I will post here again.

Kind Regards,
Steffen

**Comment by Katze0815** [comment]
@ Anastasia

I created this test object:

https://www.openstreetmap.org/node/8155136347

Please see OsmAnd screenshot here:

[screenshot](https://i.imgur.com/Oq12oHv.jpg)

Please see the node image tag in OSM and the resulat in OsmAnd.


Kind Regards,
Steffen
