### ISSUE TITLE
Routing takes > 5min for a 5km route on a straight road

### ISSUE THREAD

**Issue by tobip** [osmandapp/OsmAnd#10265]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, OpenRouteService, OSRM, etc.)

### Routing Profile

Car

### Start and end points

Route from Golubac to Brnjica in east Serbia, just along the road Nr. 34 next to the big Danube river.
Start: https://www.openstreetmap.org/#map=14/44.6609/21.6829
End: https://www.openstreetmap.org/#map=14/44.6519/21.7286

### Actual and expected routes

Eventually when the routing process comes to an end, te result is fine, but it takes an unnormal amount of time to get to that result.
Other routes are calculated in a reasonable time like around 2-15 seconds depending on distance up to 300km.

Example:

![photo_2020-11-24_16-01-31](https://user-images.githubusercontent.com/3918330/100112640-c073e380-2e6f-11eb-87e5-3d5a71a0ed14.jpg)

### Is this a regression?

 I actually just did update the app, but unfortunately I don't know about routing times along this exact piece of road from the previous version.

## 🌍 Your Environment

**OsmAnd Version:**
<pre><code>

OsmAnd~ 3.8.5

</code></pre>

**Device and Android/iOS version:**
Xiaomi Redmi Note 7
Lineage OS 17.1
based on Android 10
Using the f-droid app store.

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.
- [ ] Online (tile / raster) maps 
My offline map of Serbia seems to be up to date, it says `Serbia 265.2 MB • 1 Nov 2020`.

**Anything else relevant?**

**Comment by xmd5a2** [comment]
Can't reproduce. Route calculation takes 0.6 seconds. Are you sure you have actual maps? I don't see a quarry on them near finish.
