### ISSUE TITLE
"Plan a route" point to point "magnetic bearing"

### ISSUE THREAD

**Issue by miramikes** [osmandapp/OsmAnd#10278]
Hello,

When using "plan a route" and setting new point there is distance and bearing visible ... What is definitely useful.
Just bearing is displayed in (to me) strange way:
North 0 deg East 90 Deg West -90 Deg
I think it would be more convenient to be displayed in common "magnetic bearing" like this:
North 0 deg East 90 Deg West 270 Deg
Alternative option would be to have possibility switch between both if first one is useful in some situations I am not aware of.

Thank you for great job you doing on this app.

mira

**Comment by Dima-1** [comment]
We already have setting for this:  Settings -> [Profile] -> General settings -> Angular unit -> Degrees 360

**Comment by miramikes** [comment]
Oh ... That's great!!! I simply couldn't find it.
Thank you

m.
