### ISSUE TITLE
Preloaded raster map at scale 16 is empty at scale 18 or show previous scaled tiles

### ISSUE THREAD

**Issue by inquartatech** [osmandapp/OsmAnd#10275]
### Description
Preloaded raster map at scale 16 is empty at scale 18 or show previous scaled tiles
### How to reproduce?
1. Go to the desired area on the map, on a scale of 16 (it doesn't matter, any less than 17).
2. Turn on the Map source - Yandex Satellite RU
3. Long press on screen, Actions, Preload map
4. Choose to load a scale of 18 or 19, it doesn't matter. We are waiting.
5. Turn off all Internet connections
6. On the map, poke "+" to the loaded scale of 18, and there - either empty or scaled tiles of the previous scale.

Tried it on Android 4.4 tablet and 4.2 smartphone - the same
In fact, it shows from some kind of cache, since if you delete osmand / files / tiles / Yandex Satellite RU / * it still shows the same thing.
Deleting application data, clearing the cache - does not change anything.

### Your Environment
OsmAnd Version: 3.8.4
Android/iOS version:4.4.2
Device model: Asus K018 - ASUS Transformer Pad TF103CG

**Comment by vshcherb** [comment]
It's probably that tile source doesn't provide tiles beyond 16 level

**Comment by inquartatech** [comment]
> It's probably that tile source doesn't provide tiles beyond 16 level
No. Provide to 19 level.

**Comment by inquartatech** [comment]
OsmAnd Map Creator successfully loaded level 19 and created sqlite map. But downloading with osmand is easier and faster.

**Comment by xmd5a2** [comment]
For some reason OsmAnd doesn't load zooms 17+ but OsmAndMapCreator does:
OsmAnd:
```
11-30 12:04:40.131 25566 25598 D net.osmand: TilesCache Start loaded file : Yandex Satellite RU/16/40130/20492.jpg.tile Loader map objects (synchronizer)
11-30 12:04:40.131 25566 25598 D net.osmand: TilesCache Start loaded file : Yandex Satellite RU/16/40130/20491.jpg.tile Loader map objects (synchronizer)
11-30 12:04:40.132 25566 28572 D net.osmand: MapTileDownloader Start downloading tile : https://sat01.maps.yandex.net/tiles?l=sat&x=40130&y=20492&z=16
11-30 12:04:40.132 25566 25598 D net.osmand: TilesCache Start loaded file : Yandex Satellite RU/16/40130/20490.jpg.tile Loader map objects (synchronizer)
11-30 12:04:40.133 25566 28571 D net.osmand: MapTileDownloader Start downloading tile : https://sat01.maps.yandex.net/tiles?l=sat&x=40130&y=20491&z=16
11-30 12:04:40.133 25566 28570 D net.osmand: MapTileDownloader Start downloading tile : https://sat01.maps.yandex.net/tiles?l=sat&x=40130&y=20490&z=16
```

OsmAndMapCreator:
```
FINE: Downloading tile : http://sat01.maps.yandex.net/tiles?l=sat&x=160516&y=81960&z=18 successfull 63 ms
ноя 30, 2020 12:09:08 PM net.osmand.map.MapTileDownloader run
FINE: Downloading tile : http://sat01.maps.yandex.net/tiles?l=sat&x=160518&y=81960&z=18 successfull 68 ms
ноя 30, 2020 12:09:08 PM net.osmand.map.MapTileDownloader run
```
