### ISSUE TITLE
"Add photo" button does not work / error message

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#10271]
### Description
When tapping in details of a poi the small "add photo" button (NOT the one with mappilliary) i can select a photo with a file manager, then i get the message
"Cannot upload image please try again later"
I suppose this should connect to https://openplacereviews.org ?
Login in openplacereview via OAuth / OSM works.

Edit: within osmand i often use poi updates to osm, so osm account is known and works without problems.

### Your Environment
OsmAnd Version: OsmAnd~  3.9.0#30950m.apk (2020-11-25)
Android version: 10
Device model: Samsung Galaxy Tab S5e SM-T720

**Comment by vshcherb** [comment]
Well in some sense it's duplicated cause we didn't get it working, so I will close it for now to not confuse cause I don't have milestone yet to assign.
If the feature stays this week, then we're going to let it work
