### ISSUE TITLE
Minor road Stop is reported when driving on major road.

### ISSUE THREAD

**Issue by HubMiner** [osmandapp/OsmAnd#10281]
### Description
When driving on a major road and approaching a stop sign which is tagged minor, the app incorrectly reports an upcoming stop sign.  This is very annoying when there are a lot of intersections with minor roads, but the stop signs do not apply to major roads.

### How to reproduce?
Example: driving north or south and approaching: https://www.openstreetmap.org/node/232692825

### Your Environment
OsmAnd Version: 3.8.4
Android/iOS version: 10
Device model: Samsung S10

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
US-Wisconsin, Sep 2020

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/pull/11016

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-resources/pull/673

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/pull/11043

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/pull/11075

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-core/pull/210
