### ISSUE TITLE
2 Kilometers are 1.5 for the app

### ISSUE THREAD

**Issue by Spielmops** [osmandapp/OsmAnd#10282]
### Description
There is a navigation-announcement with the distance "2 Kilometers". The real distance is 1.5 Kilometer.

### Your Environment
OsmAnd Version: 3.8.5
Android/iOS version: LinageOS 7 and 8, Android 5, 7, 8 and 9

Spielmops

**Comment by pebogufi** [comment]
Yes, distances are rounded. That is a feature.

**Comment by vshcherb** [comment]
It depends on the voice package and on exact value, I think 1.5 km should be announced as 1.5

**Comment by Spielmops** [comment]
My voice package is German. And 4 Kilometers are announced at 4 Kilometers. All the other announced distances are OK too. 
Spielmops

**Comment by sonora** [comment]
I guess what you are talking is the pre-announcements, signposted on motorways mostly 2000m out in metric countries and 1 mile out in the US. What you see is rounding for brevity, saying the exact "1-point-soemething" is just a lot longer than saying 1 or 2 in most languages, and irrelevant for a preannouncement, which just alerts you of soemthing coming up in a minute.

Please try voice package German (casual), where we experiment with suppressing some prompts entirely, it is designed for more brevity and fewer prompts.

**Comment by Spielmops** [comment]
> I guess what you are talking is the pre-announcements, signposted on motorways mostly 2000m out in metric countries and 1 mile out in the US. 
No, if so I had said that. And why should I? I'm talking about the actual distance, shown within Osmand in the upper left corner while navigating. These distances are accurate!
And  I wrote:
> All the other announced distances are OK too.
Spielmops

**Comment by sonora** [comment]
Yeah, that's the 'prepare' prompt, it says '1 mile' or '2k'. We use mathematical rounding to full integers for brevity. But current trend is to drop prepare prompts entirely, as you also  have suggested elsewhere, so I invite to test a voice without them.

**Comment by Spielmops** [comment]
And two miles are 4 Kilometer? :-)

**Comment by sonora** [comment]
3.218688

**Comment by sonora** [comment]
Humor aside, as I  said it is obviously a **huge** change. We would have to work through 4 dozen of tts voices, plus need re-recordings of the corresponding recorded voices.

And account for regional preferences: some languages will prefer"one-point-seven kilometers", others would speak "seventeenhundred meters", yet others say "one and three quarters".

All have in common they sacrifice brevity. In my judgement there is little return of invest for a prompt many are suggesting is too chatty for them anyway and should better be suppressed.

**Comment by Spielmops** [comment]
It's OK, if I can get avoice-file, which does not announce such distances, then I'm happy ...
Spielmops

**Comment by sonora** [comment]
What I am saying is that if you name your folder/file as I specify,, it should work, even before the next release?
