### ISSUE TITLE
Problem with editing and then saving gpx-track

### ISSUE THREAD

**Issue by Lans-K** [osmandapp/OsmAnd#10297]
After editing a gpx-track from the segment editing submenu, the "save changes" button, as well as the "Done" button, create a new track with the same name and write the changes to the new track; and the "add to track" button overwrites the previous track data along with waypoints and replaces them with new data. The waypoints are then lost.

Everything described happens regardless of whether the track was recorded using GPS or created using the "plan a route" function.

Only editing track with the "plan a route" function allows you to correctly save the changes in the track.

Changes made from the track edit menu itself will prevent them from being saved, losing data from other legs (previous segments) and waypoints.

By opening the track with a tap on the map and using the "open track" button, the track is also recalculated, from which there is no way to refuse, and there is no way to save it correctly.

In other issues, this problem is not fully described.

Version 3.8.4.
Android 6.

     После редактирования gpx-трека из подменю редактирования сегмента в самом треке, кнопка "сохранить изменения", равно как и кнопка "Готово" вместо записи изменений в существующий трек создают новый трек с аналогичным названием и записывают изменения в новый трек. 
       Функция "добавить к треку" затирает данные предыдущего сегмента выбранного трека вместе с путевыми точками и заменяет их новыми данными. Путевые точки при этом теряются.
       Всё описанное происходит независимо от того, был ли трек записан с помощью gps или создан с помощью функции "plan а route ".
       Только лишь редактирование с помощью функции "plan а route " позволяет корректно сохранить изменения в треке.
       Внесение же изменений из самого меню редактирования трека не позволяет ни каким из способов корректно сохранить трек; при этом происходит потеря данных других отрезков (предыдущих сегментов) и путевых точек.

     Открывая трек тапом на карте и с помощью кнопки "открыть трек", -- также производится непременный пересчёт трека, от которого нет возможности отказаться, и проявляется описанная проблема невозможности его корректного сохранения.
     В других issue я не нашёл эту проблему описанной в полной мере.

**Comment by vshcherb** [comment]
In new release 3.9.2 (beta is out) it should be fixed
