### ISSUE TITLE
Wrong opening times information if tag opening_hours:last_check is used

### ISSUE THREAD

**Issue by cyclingcat** [osmandapp/OsmAnd#10304]
### Description

When a node contains the tag _**opening_hours:last_check**_ the opening times erroneously contain the text "24/7 - Last_check"

### How to reproduce?

- Search for a node with the tag _opening_hours:last_check_
- Click on this node in order to see its opening times

### Example (node id 4381312869):

![last_check](https://user-images.githubusercontent.com/32601012/100709258-0d931080-33ae-11eb-8949-a2c2a51b752a.png)

According to [taginfo](https://taginfo.openstreetmap.org/keys/opening_hours%3Alast_check), this tag is rarely used, however, the text "24/7" is definitely wrong here. Even worse: The opening times are shown green here, although this shop is closed today (= Tuesday).

### Your Environment
OsmAnd Version: 3.8.5 (from F-Droid)
Android/iOS version: Android 5.1/9.0
Device model: bq Aquarius M4.5/Cubot Quest

**Maps used (online or offline):**   
Offline map, Germany/Baden-Württemberg, version 1 November 2020.

**Comment by vshcherb** [comment]
I think this tag has been moved to
https://taginfo.openstreetmap.org/keys/opening_hours%3Alast_check ->
https://taginfo.openstreetmap.org/keys/opening_hours%3Alastcheck
and later to
https://wiki.openstreetmap.org/wiki/Key:check_date
