### ISSUE TITLE
Change sign "railway crossing" in Canada

### ISSUE THREAD

**Issue by AnastasiaTiutina** [osmandapp/OsmAnd#10308]
The sign that OsmAnd shows in the lower-left corner of the screen when approaching a railway level crossing is not the sign that is used in Canada. 
It shoud be like this :
https://www.google.ca/maps/@49.2638295,-124.1994549,3a,30y,60.17h,86.88t/data=!3m6!1e1!3m4!1sKEBv7wjZCs7fVB1K63qgLw!2e0!7i13312!8i6656

**Comment by DENelson83** [comment]
SVG of the Canadian "railway crossing ahead" sign can be found here.
https://commons.wikimedia.org/wiki/File:Ontario_Wc-4.svg

**Comment by dmpr0** [comment]
@androiddevkotlin image https://github.com/osmandapp/OsmAnd/blob/4acb3981e00d76e08607aa24608092f5db69e8e7/OsmAnd/res/drawable/warnings_railways_ca.xml
