### ISSUE TITLE
`animal_keeping=horse` tag is not a business POI

### ISSUE THREAD

**Issue by noerw** [osmandapp/OsmAnd#10305]
### Description
Area with the `animal_keeping=horse` tag is shown as a business ('Dienstleistung') in the app. [This is semantically wrong](https://wiki.openstreetmap.org/wiki/Tag:landuse%3Danimal_keeping). This is *very* wrong when the node also has the `access=private` tag.

```
animal_keeping=horse
landuse=animal_keeping
```

If you want to show such business, use `leisure=horse_riding` only.

### How to reproduce?
Check out [this way](https://www.openstreetmap.org/way/781378027#map=15/50.82073/6.30629)

### Your Environment
OsmAnd Version: 3.8.5
Android/iOS version: android 8
Device model: -

**Maps used (online or offline):**   offline, 2020-11-01
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by noerw** [comment]
Also: How are these categories generated? Is this a bug in an upstream project? I'm wondering if other apps also have this issue..

**Comment by xmd5a2** [comment]
> Also: How are these categories generated? Is this a bug in an upstream project? I'm wondering if other apps also have this issue..

No, these categories doesn't have any connection with other projects.
What category do you propose? "Service" is most suitable from our categories list.
See https://github.com/osmandapp/OsmAnd-resources/blob/master/poi/poi_types.xml

**Comment by noerw** [comment]
@xmd5a2 Thanks for the pointer to the category list!

This is not a service either, it's just a place where horses are sheltered.
So `animal_keeping` should not be a POI at all. At least not shown by default, as is currently.
As mentioned above, the semantics of `leisure=horse_riding` are a much better fit.

Context for this: I tagged our small, private horse paddock, and occasionally people show up, expecting to find some public horse riding business, which can get quite annoying

**Comment by xmd5a2** [comment]
Ok, now it is in "landuse" category. `animal_keeping=horse` is not POI at all, it is additional tag for `landuse=animal_keeping'
