### ISSUE TITLE
Open the <url> specified in a gpx file

### ISSUE THREAD

**Issue by delaitre** [osmandapp/OsmAnd#10312]
# 🚀 feature request

### Description

I have some gpx files with an html file "attached" to them (same name as the gpx file, but with .html extension).
This html file is specified with the <url> tag in the route/track tag of the gpx.

It would be nice to have that link displayed and opened when the user clicks on it.

In my case, those html contains formatted description of the track as standalone html files. I guess this could be extended to support any type of url so that it would open the linked website on click.

### Describe the solution you'd like

Show (in the track details area) the url specified with the <url> tag in the top level gpx route/track node and open the url on click.

### Describe alternatives you've considered

I considered using a stipped down version of the html in my case and put that in the `<desc>` field of the track in gpx file, but it is not displayed neither, hence #10311

I also tried to use the OsmMapCreator to create travel sqlite files but OsmAnd crashes when I open the generated sqlite file...

**Comment by vshcherb** [comment]
You can create OBF file using https://test.osmand.net/gpx.html

**Comment by delaitre** [comment]
Well given that I have about 1000 gpx like this, I either need something I can script (hence me trying to use OsmMapCreator to create a "travel") or the functionality directly supported by the app itself (hence this thicket).
Thanks for the link though :)

**Comment by vshcherb** [comment]
I've thought OsmMapCreator had support for it, but actually not.

**Comment by Dima-1** [comment]
Fix request: osmandapp/OsmAnd-tools#393
