### ISSUE TITLE
please add healthcare:speciality=vaccination to search items

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#10318]
# 🚀 feature request
please add **healthcare:speciality=vaccination** to search items Healtcare, sub-categorie speciality.

### Description
Due to corona/covid19 problem **vaccination centers** are planned and will be created in europe. The tagging is proposed here:
https://wiki.openstreetmap.org/wiki/Proposed_features/vaccination

We can expect it will be tagged like that:
    **healthcare:speciality=vaccination
    vaccination=covid19**
Please support search in release which currently prepared.

**Comment by pebogufi** [comment]
@xmd5a2 
Sorry, bit I can't get it work.
OsmAnd~  3.9.0#31068m.apk 2020-12-10 22:25.
Example is:

**Comment by xmd5a2** [comment]
If should work. Otherwise it is related to something else.
![Screenshot_2020-12-11-11-33-51-954_net osmand plus](https://user-images.githubusercontent.com/5829014/101881166-130a0b00-3ba5-11eb-9103-220f6c25dd7f.jpg)

**Comment by pebogufi** [comment]
@xmd5a2 
Yes, I see the object, but don't find it with search, that is the problem. We should be able to search for any object like that in the region....

**Comment by pebogufi** [comment]
@xmd5a2 
With version OsmAnd~  3.9.0#31080m.apk 2020-12-14 08:56 
I can't get it work, searching for vaccination in a region.
Map is current, i see the vaccination centers.

**Comment by xmd5a2** [comment]
Yes, there is not possible now to view POI on map using "vaccination" search filter. This is clearly a bug.

**Comment by pebogufi** [comment]
@xmd5a2 @vshcherb 
I am sorry, I don't want to bother you.
But the vaccinarion will start in germany on dec 27. In Great Britain and USA it has already started. A lot of people are working to tag theese centrers in Germany, and I suppose also in a lot of other countries.
This is not only a matter of personally interest but a global need to help against this pandemia.
It would be very helpful to get the search work as soon as possible.
Thank very much.
Regards Peter

**Comment by xmd5a2** [comment]
@pebogufi please explain what exactly is not working in your case

**Comment by xmd5a2** [comment]
There is another proposal for such centres but almost no uses
https://wiki.openstreetmap.org/wiki/Proposed_features/Tag:healthcare%3Dvaccination_centre

**Comment by pebogufi** [comment]
In germany the proposal of first comment is used.
For explaining i switch to english user language. (my default is German).
Searching for categorie Healthcare i see a lot of objects, include the vaccination which is tagged like described in first posting. But there all all subcategories of Healthcare, that is to much ...
Then i go in search to setting, looking for subcategory "Health Speciality". After tapping on SHOW ALL  i find subcategory "vaccination" which exists since a few days only (i suppose due to this thread?).
After checking "vaccination" and APPLY FILTERS i expect to get a list of Healthcare+vaccination objects, but the result list is empty.
The search started with a vaccination in center of screen, so this one should be in the list.
Example in Freiburg see above.

**Comment by pebogufi** [comment]
In Germany Baden-Württemberg are currently tagged **41** objects with
healthcare:speciality=vaccination
vaccination=covid19
Other regions are also in progress. A lot of people are working on it.

**Comment by xmd5a2** [comment]
vaccination should be in obf maps starting from january. In my tests (with newly created obf) objects with vaccination are searched, search list is displayed, but the problem is that the search results are not displayed on the map if I click "Show on map". It is a separate issue
https://github.com/osmandapp/OsmAnd/issues/10454

**Comment by pebogufi** [comment]
With live is not working ?

**Comment by xmd5a2** [comment]
It **is** working, but with nightly version.
https://www.openstreetmap.org/node/8207083844
![Screenshot_2020-12-22-13-48-20-977_net osmand plus](https://user-images.githubusercontent.com/5829014/102880612-aa504780-445c-11eb-9407-c7dd2303a9aa.jpg)
![Screenshot_2020-12-22-13-47-54-782_net osmand plus](https://user-images.githubusercontent.com/5829014/102880616-ab817480-445c-11eb-8733-facf0474a302.jpg)

**Comment by pebogufi** [comment]
Yes, but not within search.
You can use this
https://umap.openstreetmap.fr/de/map/impfzentren-covid-19_533082#8/48.716/6.196
for getting an overview.

**Comment by vshcherb** [comment]
- You can use search
- You can create custom filter
- You can't see them on the map as special layer (same applies for fuel types and other searches) - so another bug is created in Issues
