### ISSUE TITLE
Show Upcoming Elevation Graph from GPX

### ISSUE THREAD

**Issue by Dollarius** [osmandapp/OsmAnd#10313]
I use OsmAnd for cycling and I love it.
I usually load on my Android phone a computer-made GPX track, display it in cycling mode, and just manually follow the route (with navigation DISABLED).

It would be very helpful for me to be able to see the elevation graph from the GPX track.
The ideal thing would be to have a graph (possibly overlayed at the bottom of the map) showing the elevation of the last 3km and the upcoming 3km, with the current position at the centre, based on the GPX track.
Is there a way to implement such a feature? Could it be made through a widget?

I am aware of the existing function under MyPlaces/Tracks/GPX file/"Analyse on Map", but I find this function cumbersome to use while riding for the following reasons:

1. The current position on the gpx file has to be manually selected by sliding the finger left/right on the bottom graph. It is very complicated/dangerous to do this while cycling and it is impossible to get the needed precision

2. The elevation graph shows the plot of the whole GPX file, without any option to zoom in. This is inconvenient for long rides (i.e., >100km), making it very difficult to find crucial information like "where is the peak" and "how much more uphill do I have to ride".

3. While entering the "Analyse Map" mode, all the widgets (speed, current elevation, battery percentage, etc.) disappear because this function is not meant to be used while moving.

Any help/suggestion would be gladly appreciated!
Thank you very much for your help in improving this amazing app.
Giordano

**Comment by njohnston** [comment]
I know it's not the main point of your issue, but you mention:

"The elevation graph shows the plot of the whole GPX file, without any option to zoom in"

You can zoom by "pinching" and "pulling" on the graph with two fingers. The map view changes accordingly.

**Comment by Dollarius** [comment]
Thank you njohnston for your suggestion!
As you say, it is not the main point of my issue because it adds another level of complication that is difficult/dangerous to address while riding (especially with gloves).
Anyway, zooming in as you suggested is very helpful: thanks for pointing it out!

**Comment by vshcherb** [comment]
This is a duplicate issue to show elevation graph during navigation which is currently in development. 
You are right you can use analyze on map to see upcoming graph though it works without other widgets. This functionality will need to be integrated as a separate widget for navigation mode as well.

**Comment by j-schneid** [comment]
I would like to add: When recording a track, the recording widget shows the accumulated distance. Something equivalent for elevation would be nice.

**Comment by davewood** [comment]
this is quite old but i still cant see the elevation profile from a gpx track, right?

**Comment by sonora** [comment]
Yes, you can. But if the track itself does not contain elevation data per se (like recorded tracks normally would), you can first build a route using the track, so OsmAnd uses the elevation data (if downloaded for the region) to match it to the track.
