### ISSUE TITLE
Display issue when editing POI if the tag is too long

### ISSUE THREAD

**Issue by letypequividelespoubelles** [osmandapp/OsmAnd#10324]
Hi all, 

When editing a POI, when I go to "etendue" (in french, I guess it's "extended" in english) to see all the tags, the one which are long are not shown completely, because it lacks space and word "tag" remains. 

See pictures for exemple to see the display issue.

![photo5926974544457872607](https://user-images.githubusercontent.com/54240434/101017980-1e3cb580-356b-11eb-9bfa-c4ca261d5e53.jpg)

I'm using Osmand 3.8.5 from F-Droid on a BV9500 plus device with android 9. I remember that it was not the case with previous version of the app (I don't remember since which version I see this issue, sorry) ; before the tag used to be split on 2 or more line that the user can see it all. 

Thanks all for this wonderfull app.

**Comment by vshcherb** [comment]
As I see it's already fixed in 3.9 (coming this week)
