### ISSUE TITLE
Display errors at coastline, Auckland NZ

### ISSUE THREAD

**Issue by robinpaulson** [osmandapp/OsmAnd#10323]
See attached file. If I disable the worldwide overview map it works fine![](https://i.imgur.com/thhZolf.png)

**Comment by robinpaulson** [comment]
36.82974° S, 174.64368° E

**Comment by xmd5a2** [comment]
Fixed in new basemap

**Comment by robinpaulson** [comment]
Excellent! For future reference, was there a problem with the coastline?

**Comment by xmd5a2** [comment]
@robinpaulson problem was with coastline used when creating basemap. It was too different from current OSM coastline and this led to the fact that in some places it was displayed (low-detailed) instead of high-detailed OSM coastline from detailed maps.
