### ISSUE TITLE
add an option to put default profile as the last used profil

### ISSUE THREAD

**Issue by letypequividelespoubelles** [osmandapp/OsmAnd#10346]
# 🚀 feature request

### Description

Please add an option to put "default profile" while opening the app as the last used profil. I use OsmAnd in many differents sutuation : hiking, cycling, driving, preparing city holiday (with Wikipedia on), contributing to the map, etc ... all of them with different profile. I usualy do the same activity for few hours or days, so if I don't want to switch theap every time I open the app I have to change the "prefered profile" every time I change my activity. Not very user friendly.

### Describe the solution you'd like

We should have an option to open the app with the last used profile instead of a prefered profile. 

### Describe alternatives you've considered

None. Thanks all of you for this wonderful app.

**Comment by dmpr0** [comment]
![last_used](https://user-images.githubusercontent.com/9365308/102084120-579fdb80-3e1d-11eb-856e-ad72d2757eb3.png)
[figma](https://www.figma.com/file/qzrNQj0chuME6gyO038i6M/Settings?node-id=2%3A28618)
