### ISSUE TITLE
Simplify track selection in 'Plan a route'

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#10341]
Why do we invent a new user interface for` Plan a route / Open existing track`? I suggest to use exactly the same as for `Plan a route /  Import track`, just with the starting point in the OsmAnd tracks folder.

That one is also a lot more performant and ergonomic.

**Comment by vshcherb** [comment]
2nd option is completely different and device dependent, so it's better to have it only for external tracks.
Also please bear in mind since Android 11, Import track  dialog will only work for external storage

**Comment by sonora** [comment]
Ah, that's true, thanks!
