### ISSUE TITLE
Invalid routing for roads with "class:bicycle" tags?

### ISSUE THREAD

**Issue by maciej-galuszewski** [osmandapp/OsmAnd#10340]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, OpenRouteService, OSRM, etc.)

### Routing Profile

Cycling, balanced style

### Start and end points

Start point: [54.53568, 18.45725](https://www.openstreetmap.org/#map=18/54.53568/18.45725)
End point: [54.52777, 18.46038](https://www.openstreetmap.org/#map=17/54.52777/18.46038)

### Actual and expected routes

I have marked expected route on the screenshot in red. After my investigation, I found out that invalid routing might be related to the fact that some parts of the preferred road have "class:bicycle=1" tag (I did not find any particular differences between the tags besides that).

According to openstreetmap wiki, "class:bicycle=1" tag should be used for preferred bicycle routes (not for those that should be avoided).

In my opinion the tags for the preferred road are correct, because the road is shorter, has good surface and low traffic (not to mention the fact that the route calculated by Osmand has unpaved paths and tunnel with stairs).

I did some other tests with routes with "class:bicycle=1" tag and it seems that for each case such roads are avoided, instead of being preferred.

![Screenshot](https://user-images.githubusercontent.com/23149326/101226617-550eea80-3695-11eb-9b71-fe3241854336.jpg)

### Is this a regression?

I don't know unfortunately 😞 

## 🌍 Your Environment

**OsmAnd Version:**
<pre><code>OsmAnd+ 3.8.4</code></pre>

**Device and Android/iOS version:**
Samsung Galaxy S7 Edge, Android 8

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.
Poland_pomeranian_europe, 1 Dec 2020
- [ ] Online (tile / raster) maps

**Comment by xmd5a2** [comment]
![Screenshot from 2020-12-09 15-22-47](https://user-images.githubusercontent.com/5829014/101629489-7c1d4180-3a32-11eb-956f-ccd24dd8e5d4.png)
