### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by user08777** [osmandapp/OsmAnd#10359]
Hi devs,

want to change road sign design, because in my country our road signs looks a little bit different than other. (I live in switzerland) So please add function that can change replace/change road sign with png.
EDIT: Also, please add road sign of "traffic lights". (Screen Alerts)

Thanks!

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/101480296-cb407500-3953-11eb-8dd2-f17db453a8ac.png)
I don't see much difference with European road signs, could you please specify which ones need to be updated

**Comment by user08777** [comment]
![1280px-CH-Vortrittssignal-Stop svg](https://user-images.githubusercontent.com/74828705/101480912-a0a2ec00-3954-11eb-8658-cc521c915ff2.png)

**Comment by dmpr0** [comment]
I update our stop sign with the new one 20e2293f9b.
![Снимок экрана 2020-12-11 в 18 42 27](https://user-images.githubusercontent.com/9365308/101930291-9f85ef00-3be0-11eb-917e-d11a45715586.png)
