### ISSUE TITLE
strange square on some zoom levels

### ISSUE THREAD

**Issue by 532910** [osmandapp/OsmAnd#10361]
zoom Z-1:
![image](https://user-images.githubusercontent.com/14617699/101301199-1faafe00-3849-11eb-9a47-b79270fd19df.png)

zoom Z:
![image](https://user-images.githubusercontent.com/14617699/101301317-7fa1a480-3849-11eb-8b70-1d122ba9945a.png)

zoom Z+1:
![image](https://user-images.githubusercontent.com/14617699/101301336-8a5c3980-3849-11eb-9b59-6025a9678733.png)

**Comment by vshcherb** [comment]
List of tasks:
- [ ] Background near coastline edge (Original issue - Sankt Peterburg, comment xmd5a2 - 1. ) 
- [ ] Lack of background tiles (comment xmd5a2 - 2.)
- [ ] Analize "ocean" background in children tiles(comment xmd5a2 - 3.)

**Comment by ivanPyrohivskyi** [comment]
Fix for "Background near coastline edge (Original issue - Sankt Peterburg, comment xmd5a2 - 1. )"
https://github.com/osmandapp/OsmAnd-core/pull/254

For task "Lack of background tiles (comment xmd5a2 - 2.)" can see as solution the variant to move basemap poly (coastline) inside to water Großer Jasmunder Bodden
![iOS rendering](https://user-images.githubusercontent.com/1040293/135446941-66d0df28-5d63-48e5-9c35-ee193ec01446.png)

**Comment by ivanPyrohivskyi** [comment]
xmd5a fixed base coastline for Großer Jasmunder Bodden
Need regenerate world basemap. According to server workload best time to do it from October 12 2021
![2021-10-01 11 10 45](https://user-images.githubusercontent.com/1040293/135587317-fefb39c3-bba9-4d38-89b8-9b033c71d18b.jpg)

**Comment by vshcherb** [comment]
Basemap should not be regenerated cause it's not necessary for basemap to have such details

**Comment by DicePenguin** [comment]
I'm seeing this issue on in parts of Central New Jersey in the United States along the Raritan River. I would also like it fixed please.

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-core/pull/280

Statistic for point 54.56640,13.38830
[outBinaryMapObjects.size.txt](https://github.com/osmandapp/OsmAnd/files/7641434/outBinaryMapObjects.size.txt)

**Comment by ivanPyrohivskyi** [comment]
Tested. Bug fixed.
Found new bug described in https://github.com/osmandapp/OsmAnd-Issues/issues/1074

**Comment by 532910** [comment]
Page not found
