### ISSUE TITLE
Corrupted contour lines near N51 ° E16 °

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/OsmAnd#10376]
![изображение](https://user-images.githubusercontent.com/5829014/101736247-27320780-3ad4-11eb-9d4c-2e45352710e2.png)

**Comment by xmd5a2** [comment]
Fixed

**Comment by mp13mp13** [comment]
Niestety, częściowo rozwiązane. Nadal jest problem z poziomicami na południe oraz na wschód od pozycji 50° N 16° E . Poziomice na zachód od tej pozycji zostały poprawione.
![Uploading Screenshot_20201211-143257_OsmAnd+.jpg…]()
