### ISSUE TITLE
Elevation graphs only for 'Snap to road'?

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#10374]
I am wondering why we have the limitation that we offer elevation and gradient graphs under 'Plan a route' only after a route calculation?

We certainly have the data necessary to show these graphs for arbitrary tracks? (And we even show graphs  for any recorded track when opened via MyPlaces/Tracks, without any prior route calculation or snap to road.).

**Comment by vshcherb** [comment]
There is a dialog already that suggest that you need to approximate track with roads (attach to roads) during that procedure we can retrieve elevation information. For arbitrary tracks that's not possible.

Showing elevation graph for snapped track while displaying original track on the map could be very misleading and erroneous in certain situations.

**Comment by sonora** [comment]
But how do we do it for the recorded tracks? They are arbitrary, meaning not snapped to road ... and still we show the graphs?

**Comment by vshcherb** [comment]
For recorded tracks elevation is inside tracks, so it works easy.

**Comment by sonora** [comment]
Ah yes, true. ;)
