### ISSUE TITLE
Missing and doublicated clock times on x-axis when analyze track on map

### ISSUE THREAD

**Issue by AljoschaE** [osmandapp/OsmAnd#10373]
### Description
When I analyze a recorded track with "ANALYZE ON MAP" and select "Time of day" there are some clock times missing and some doublicated as shown below.
![OsmandTimelineBug](https://user-images.githubusercontent.com/75755488/101681596-aedf2e00-3a62-11eb-8179-5f55d0526449.png)

### How to reproduce?
When you record a track, finish it, use "ANALYZE ON MAP" with the option "Time of day" and zoom.

### Your Environment
OsmAnd Version: OsmAnd+ 3.8.4 
Android/iOS version: Android
Device model: LG G5, Nokia 8.1

**Comment by dmpr0** [comment]
Available in the latest nightly builds.
