### ISSUE TITLE
Allow private access doesn't work

### ISSUE THREAD

**Issue by AnastasiaTiutina** [osmandapp/OsmAnd#10385]
OsmAnd create a wrong track
Started 53.83377° N, 22.39061° E
End 53.79567° N, 22.42780° E

The OSM create the right path with the same coordinates:
![track OSM](https://user-images.githubusercontent.com/72389175/101882411-86f4e500-3b9e-11eb-94cc-f0720d2e32a0.jpg)
![track OsmAnd](https://user-images.githubusercontent.com/72389175/101882428-89efd580-3b9e-11eb-82f9-c4fa842c2786.jpg)

**Comment by dmpr0** [comment]
Part of "Lesna" street is marked as private and should be accessible with "Allow private access" enabled, but in the current nightly build, 3.9 it seems doesn't work.
