### ISSUE TITLE
UX Bug when opened for the first time through Android Intents

### ISSUE THREAD

**Issue by RichardSilveira** [osmandapp/OsmAnd#10396]
### Description

I have an Android app that calls OsmAnd through Android Intents, but **most users get confused** because they don't realize they need to click on the ["My position" button](https://drive.google.com/file/d/1m6yw95kyvdfsG5IRiOUuRdJbE-H9jbTv/view?usp=sharing) in the OsmAnd app - that display the `location` permission option.

[Video recorded showing the user interaction with issues]( https://drive.google.com/file/d/1EmYxHf3EgHblVcUM-UhNQLyldE0QVe1G/view?usp=sharing)

### How to reproduce?

From another app that integrates with OsmAnd by Android Intents, call the OsmAnd app for the first time.

[Video recorded showing the user interaction with issues](https://drive.google.com/file/d/1EmYxHf3EgHblVcUM-UhNQLyldE0QVe1G/view?usp=sharing).

### Suggestion

I'm working with the `OsmAndIntentBuilder`, which has a couple of awesome params that helped us a lot to deliver a good user experience to our users. **But** I need to suggest the addition of one more parameter that is **extremally necessary in terms of UX** that allows the third-apps to request that `location` permission has requested as soon the OsmAnd app is open to the user.

_Just to show the parameters that I'm using to integrate my Android app with OsmAnd._
```
@ReactMethod
	public void navigate(String startName, double startLat, double startLon,
						 String destName, double destLat, double destLon,
						 String profile, boolean force) {

		mActivity = getCurrentActivity();
		// test navigate
		Map<String, String> params = new HashMap<>();
		params.put(PARAM_START_LAT, String.valueOf(startLat));
		params.put(PARAM_START_LON, String.valueOf(startLon));
		params.put(PARAM_START_NAME, startName);
		params.put(PARAM_DEST_LAT, String.valueOf(destLat));
		params.put(PARAM_DEST_LON, String.valueOf(destLon));
		params.put(PARAM_DEST_NAME, destName);
		params.put(PARAM_PROFILE, profile);
		params.put(PARAM_FORCE, String.valueOf(force));
		sendRequest(new OsmAndIntentBuilder(NAVIGATE).setParams(params));
	}
```

_* This video shows the second part after the user is redirected to the OsmAnd app._

### Your Environment
OsmAnd Version: 3.8.4
Android/iOS version: Android Samsung S9
Device model:

**Maps used (online or offline):**   
offline

**Comment by vshcherb** [comment]
If you can create pull-request along it, it would speed up how fast we could process the issue
