### ISSUE TITLE
OSM Editing plugin doesn't show 'wikipedia' as tag

### ISSUE THREAD

**Issue by Heiner-Sch** [osmandapp/OsmAnd#10390]
I add tags to POI's often via the OSM edit plugin in OsmAnd.

Unfortunately the tag 'wikipedia' is not suggested in the tag names.
So I have to type it every time.

Is it possible to add 'wikipedia' to the list of suggested tag names?

**Comment by Heiner-Sch** [comment]
Until version 4.0.9 'wikipedia' was available.
Since v4.1.9 not.
Is there a reason for this?
Or is it a mistake?

**Comment by vshcherb** [comment]
Yes regression

**Comment by dmpr0** [comment]
# Reviev
- [ ]  Difference between iOS and Android version in one tag `wikidata:en`

| iOS               | Android              |
| :---------------- | -------------------  |
| wikidata:en       |                      |
| wiki_link         | wiki_link            |
| wikidata          | wikidata             |
| wikipedia         | wikipedia            |
| wikimedia_commons | wikimedia_commons    |
| wikipedia         | wikipedia            |

**Comment by vshcherb** [comment]
we don't display language ```wikidata:en```
