### ISSUE TITLE
Sakhalin Contour lines error

### ISSUE THREAD

**Issue by Kivasya** [osmandapp/OsmAnd#10398]
![photo_2020-12-14 10 37 22](https://user-images.githubusercontent.com/75778939/102058588-632cdb80-3df8-11eb-96a3-30716f3bdf0b.jpeg)

**Comment by AnastasiaTiutina** [comment]
![Screenshot_20201214-094512_OsmAnd+ (1)](https://user-images.githubusercontent.com/72389175/102071547-464cd400-3e09-11eb-8541-62beecc21f79.jpg)
![Screenshot_20201214-094512_OsmAnd+](https://user-images.githubusercontent.com/72389175/102071558-4b118800-3e09-11eb-8cd4-a7940e29bda1.jpg)

**Comment by AnastasiaTiutina** [comment]
51° 16°

**Comment by mp13mp13** [comment]
51° 16° fixed.  Thanks🍺
