### ISSUE TITLE
navigation incorrect on imported gpx-files

### ISSUE THREAD

**Issue by K-Krs** [osmandapp/OsmAnd#10393]
Osmand reroutes the predefined route of an imported gpx file. If the hiking path isn't available in Open Street Map, Osmand reroutes via an alternative path. This meshed up the navigation completely.
see attached schreenshots in Osmand. 

The route in Komoot browser shows (including warnings) shows where Osmand recalculates the route. 

### How to reproduce?
Import a gpx file in Osmand (I use Google drive), selecting the gpx-file in Google Drives opens Osmand

Start navigation
click on setting
Follow track
select imported GPX file
Start routing
The navigation takes a different route as the gpx file (orange is the gpx-track)

### Your Environment
OsmAnd Version: 3.8.4
Android/iOS version: 8.0
Device model: Samsung Galaxy S7

**Maps used (online or offline):**   
offline
![Screenshot_20201213-164113_OsmAnd](https://user-images.githubusercontent.com/75943571/102017184-a5590d00-3d65-11eb-9988-a8e0ea13897b.jpg)
![Screenshot_20201213-165121_OsmAnd](https://user-images.githubusercontent.com/75943571/102017185-a8ec9400-3d65-11eb-8b9c-227e1d0183a6.jpg)
![complete route in Komoot](https://user-images.githubusercontent.com/75943571/102017188-ad18b180-3d65-11eb-951a-455b4474edfb.JPG)
![warnings in komoot](https://user-images.githubusercontent.com/75943571/102017191-b0ac3880-3d65-11eb-8416-aac1da996ae4.JPG)

**Comment by vshcherb** [comment]
Is it possible for you to attach GPX file (zip), so we can try to reproduce it.
