### ISSUE TITLE
Issue - instead of picture special charaters was displayed, or no image. used by image tag + screenshots

### ISSUE THREAD

**Issue by Katze0815** [osmandapp/OsmAnd#10423]
### Description

Hello,

I'm created some nodes in OSM, see links in ### How to reproduce?

I use the image tag for the objekt in OSM, to show an picture of the objekt.

When I check this in OsmAnd, short tip on objekt, then details, I see not the picture, I see special characters, blue text on white ground. Please see screenshots.

In the 3 links/nodes OsmAnd show 2 times the blue text, one time nothing, no picture or text.

When I check the nodes in OSM, I found no error. 

[Screenshot 1](https://i.imgur.com/9MgThVG.jpg)

[Screenshot 2](https://i.imgur.com/rNjeZTT.jpg)

---------------------------------
Some weeks ago, we had a comparable issue. When in tag description is a longer text, not text was displayed, special characters was displayed:

[Similiar issue](https://github.com/osmandapp/OsmAnd/issues/10226)
-------------------------------------------

### How to reproduce?

Every time use OsmAnd. Short tip on objekt, then details.

Memorial: https://www.openstreetmap.org/node/8226266702
no picture displayed

Viewpoint: https://www.openstreetmap.org/node/312549400
instead of picture special characters displayed

war memorial: https://www.openstreetmap.org/node/2577256118
instead of picture special characters displayed

### Your Environment
OsmAnd Version: 3.8.4
Android/iOS version: 10, actual
Device model: Honor View 20 

**Maps used (online or offline):**   
I use live maps, offline, actual version every houer

Sorry for my bad English, I hope you will found out, what I mean. :)

Kind Regards,
Mietz

**Comment by Katze0815** [comment]
Change title of picture was not an solution. URL decoding works in every other app, but not in OsmAnd. In German language we use ü,ä,ö,ß, so this characteres is our normale language.

**With this issue, OsmAnd can't display thousend of linked pictures that use special characters.**

**Comment by vshcherb** [comment]
This is fixed with 3.9 version (available as beta) unfortunately we're not able to release yet cause of special Google moderation which is blocking release

**Comment by Katze0815** [comment]
Hello,

this is fine!

Actual, there is no version 3.9 available in Google App Store. 

Whre I get the V 3.9 APK?

**Comment by vshcherb** [comment]
3.9 is available only for beta now on Google Play, release is pending

**Comment by Katze0815** [comment]
@ vshcherb

Thank you. :)

As I can see, the source code of OsmAnd is on Github. It is possible to compile the APK by myself? 


Kind Regards

**Comment by vshcherb** [comment]
Yes, of course. we compile every day here - https://download.osmand.net/latest-night-build/OsmAnd-default.apk

**Comment by Katze0815** [comment]
Thank you! Well, this will install a separate App. I use OsmAnd+, hourly actualisation of my maps. This I cant use this in OsmAnd Nightly. I get message: Please pay subscription.

Can I use my payed subscription from OsmAmd+ also for Nichtly?

Kind Regards

**Comment by Katze0815** [comment]
... solved. Found OsmAnd-master.

Kind Regards
