### ISSUE TITLE
UI: Sort base profiles to the front again

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#10438]
We recently added the special use profiles Truck and Motorcycle, and per app default throughout the UI these do now appear between the Browse map and the other standard Driving/Cycling/Walking /Public Transport base profiles.(In e.g. the Manage profiles list, or also in the iconized profile selector.)

I suggest they should per app default be sorted behind these base profiles, they serve special purposes and will clearly never be used by the vast majority of users.

**Comment by vshcherb** [comment]
Sorting is Fixed now

**Comment by sonora** [comment]
![Screenshot_20201229-214917_OsmAnd~](https://user-images.githubusercontent.com/845735/103313381-34ca1580-4a20-11eb-957d-6743a4b7f62a.jpg)

**Comment by vshcherb** [comment]
Not critical I guess
