### ISSUE TITLE
Sorting menu at the top right. Configurable speed display and right at the top

### ISSUE THREAD

**Issue by suntri-star** [osmandapp/OsmAnd#10433]
Sorting menu at the top right. Configurable speed display and right at the top

I've been bothered by always looking for the speedometer while driving a car. I can set other OSMAND menus in which order they appear. Why not the menu at the top right where the speed is unfortunately right in the middle. I would always want that at the top. And bigger if possible. But only this bigger. Maybe also red if I drive too fast. Or in any other color that I could set. THANKS

**Comment by vshcherb** [comment]
Actually I like the idea cause everything else you can change the order but not here

**Comment by dmpr0** [comment]
Release 4.6 is allows to add Speed limit (or any other) widget to the Top panel in Configure Screen.
