### ISSUE TITLE
Wiki articles switch the display language

### ISSUE THREAD

**Issue by Heiner-Sch** [osmandapp/OsmAnd#10437]
I use a German Android but switched the display language of OsmAnd to English.
That works fine most of the times.

I select an offline Wikipedia article from the map and read it, all OK.
But if I copy text from this wiki article to the clip board, parts of the display language switch to German.
So I have a mix of English and German now.
After a restart of OsmAnd it's all in English. 

The context menu in the wiki article is German, even if I selected to English for OsmAnd.
The language switches after using the context menu.
It's independent from the language of the wiki articles.
It switches always to German.

Maybe it's also good to know, that this will not happen with OsmAnd context menus.
If I switch to English, the context menus there are also English.

### Your Environment
OsmAnd Version: OsmAnd~ 3.8.5
Android/iOS version: 8.1.0
Device model: bq Aquaris X Pro

**Maps used (online or offline):**   
offline Wikipedia , June 2020
offline Germany NRW, Dec 2020
offline Luxemburg, Dec 2020

**Comment by vshcherb** [comment]
Quite messed up. Article should be always in Display Language (or System language) if the language is present. Wikipedia languages could be specified in Configure Menu -> Wikipedia. Then all these languages will be displayed

**Comment by Heiner-Sch** [comment]
Here are some screenshots.

Here is all in EN:

![01-All_EN](https://user-images.githubusercontent.com/38109491/103067325-ebf70480-45ba-11eb-85f4-12b58eeb052d.png)

Now I go into an wiki article and mark the head line, to copy it on the clip board.
And there you see the context menu in DE.

![02-Menu_DE](https://user-images.githubusercontent.com/38109491/103067459-37111780-45bb-11eb-8703-dc626e1b0d27.png)

And now back in OsmAnd.
There is no EN anymore.

![03-Language_DE-EN](https://user-images.githubusercontent.com/38109491/103067527-69227980-45bb-11eb-9b97-2ca0e3530ca3.png)

If I check now the Display language in the settings, it's EN.
After a restart of OsmAnd it's all in EN again.
And then I can start the game again.

It's not depending on the language of the wiki article.
Even if I take a FR one, the language of the context menu in the wiki article is DE.

Takes the wiki reader the language settings from the system?
