### ISSUE TITLE
Routing: preference for hiking routes in routing profile

### ISSUE THREAD

**Issue by pelderson** [osmandapp/OsmAnd#10439]
# 🚀 feature request

### Description

I kindly request a switch in the walking profile to make routing/navigating strongly prefer walking/hiking/foot routes (relations). 

This may already be "tweakable", in that case I would suggest making it a standard feature. Why? Because hiking along named routes is increasingly using digital navigation, and this feature would enable direct routing along the predefined routes in OSM, bypassing the whole online-search/gpx-export/transfer-to-device/gpx-import-in-OsmAnd thing. 

A similar mechanism already exists, probably a tweak. It uses a tag "route_bicycle" in router.xml to assign weights in various sections, switched on by a parameter "Oldtimer". The tag route_bicycle is not set in router.xml, so it must be in the database, probably set during osm2obf conversion. The rendering_types.xml also uses route_bicycle as a tag - I can't find where it is set, but it looks like a composed tag-name, which leads me to think maybe "route_hiking" works the same and might also be in the obf already. 

So, to put it as a question: is the tag "route_hiking" available for routing.xml? 

### Describe the solution you'd like

 If you have a solution in mind, please describe it.

In the routing profile for walking, add a boolean switch e.g. "Prefer Named Routes". When it is on, routing should heavily prefer member ways of an lwn/rwn/nwn/iwn route relation. Node networks should not be preferred (but also not excluded).
The effect should be that when the user is on a known route, (s)he stays on it, even when it seems to go in the wrong direction. If If the route crosses another route which leads more directly to the destination, that one will be preferred; that's fine. 

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

I see gpx-transfer as a workaround for direct routing, and this feature request as the better solution! It will not replace the gpx-thing altogether, because it is not guaranteed to follow one route exactly; it will will still choose the fastest/shortest route via the hiking route network. Hardcore one-named-route hikers will still have to use gpx-tracks (or a few via points).

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/5256dc0dde7edc615030657cf657a680750541b8

**Comment by pelderson** [comment]
Hi! Thanks for the quick fix! Sorry to be a dummy, but when will this fix work though on our mobile devices?

**Comment by xmd5a2** [comment]
@pelderson this will work with january maps and next release/nightly version

**Comment by pelderson** [comment]
Thanks!

Mvg Peter Elderson

**Comment by pelderson** [comment]
I have found and activateded the feature in the new OsmAnd version. I can't tell yet if the end result is as expected but as it is now, I can play with the "weights" in router.xml.  I have several contacts using the preference during their hikes, so they will report back to me.

**Comment by Sarkasper** [comment]
@pelderson where can I activate this feature?

**Comment by pelderson** [comment]
Osmand > Route > Foot > Options > Navigation Settings > Route parameters > Prefer... > Prefer hiking routes > ON > Apply

(Hope I can make a shortcut for this...)
