### ISSUE TITLE
Map style issue

### ISSUE THREAD

**Issue by MakiWolf** [osmandapp/OsmAnd#10442]
### Description
(highway = path and sac_scale = mountain_hiking) is rendered the same as (highway = track and tracktype = grade3). There is not much difference.
I think that it is good when (highway = path and sac_scale = mountain_hiking) is displayed as the same as (highway = path and sac_scale = hiking)

Osmand Style (highway = path and sac_scale = mountain_hiking) is displayed so:
![grafik](https://user-images.githubusercontent.com/73300633/102696017-983b9280-422b-11eb-8634-5b5fa3262331.png)
Osmand Style (highway = track and tracktype = grade3) is displayed so:
![grafik](https://user-images.githubusercontent.com/73300633/102696254-4a278e80-422d-11eb-9b55-bcf6eabb3f39.png)
But Osmand Style (highway = path and sac_scale = hiking) is displayed so:
![grafik](https://user-images.githubusercontent.com/73300633/102696039-cae58b00-422b-11eb-9361-2f8da957bd10.png)

### Your Environment
OsmAnd Version: 3.8.5
Android/iOS version: 9
Device model: Samsung Note 8

**Comment by letypequividelespoubelles** [comment]
Plus the problem is that the legend is not available offline (see #7441 for exemple ), and that we can't click on a path to see it's tag.
