### ISSUE TITLE
App still suggests to download sqlite Wikivoyage

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#10440]
This may still be WiP, but: to be sure we do not overlook:

If you you downloaded the obf Wikivoyage file and deleted the sqlite version: every time you open Menu/Travel, the first thing you see is the suggestion to download the Worldwide Wikivoyage Articles (I assume the sqlite version) again, which should be obsolete?

**Comment by vshcherb** [comment]
Yes work in progress. There is pull request to fix it. Please don't report it yet. I think in in 1 week it will be ready for reports. It's a huge refactoring of changing sqlite -> obf.
