### ISSUE TITLE
Add an opportunity to find an address from Calendar with OsmAnd 

### ISSUE THREAD

**Issue by AnastasiaTiutina** [osmandapp/OsmAnd#10456]
### Description
Cant opens an address via OsmAnd. The location is in the Calendar event

### How to reproduce?
Open Calendar on the device
Create an event
Add the address to the event
Save event
Open event
Click 'Find on map' 
Open with OsmAnd
The address should appear on the map

![bug](https://user-images.githubusercontent.com/72389175/102895756-f0fa6d80-446d-11eb-80f8-e7e9ec668def.jpg)

**Comment by jfburke3** [comment]
Might be helpful to specify which calendar app this is for, as they don't necessarily all require the same address data.  E.g., Samsung's calendar is notoriously picky about exactly how the address must be formatted, and even then doesn't always like what you enter. Google's calendar is more user-friendly, but doesn't necessarily produce address data in an OSM-friendly format.

**Comment by Chumva** [comment]
This should be added here - https://github.com/osmandapp/OsmAnd/pull/10494.
