### ISSUE TITLE
Fuel types and vaccination are not shown on map when tapping "Show on map" in search results list

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/OsmAnd#10454]
But when tapping on POI filter from context menu POIs are shown correctly
https://user-images.githubusercontent.com/5829014/102879362-af13fc00-445a-11eb-84fd-04fca3999d15.mp4

**Comment by dmpr0** [comment]
# Review 
- [ ]  no result for "vacc", but there is search results for "vac"
- [ ] After entering "vaccination" tapping on **increase** duplicates search results.
- [ ] Tappin on "vaccination: covid 19" shows "could not find anything", but if tap in "vaccination" and select one of the results it contains "vaccination:covid19" Impfzentrum, Location: geo:52.4827,13.393579?z=16, https://osmand.net/go?lat=52.4827&lon=13.393579&z=16

**Comment by vshcherb** [comment]
- no result for "vacc", but there is search results for "vac"
No result for "vac", the result is is visible only for full search result "vaccination"
