### ISSUE TITLE
Language packages are updated every day

### ISSUE THREAD

**Issue by Kivasya** [osmandapp/OsmAnd#10464]

**Comment by nickw7coc** [comment]
Mine's been updating 0.1MB voice prompt files for many months now...!?  
I've not been checking daily, but every time I do check they're there waiting to be downloaded, which they do successfully...

**Comment by nickw7coc** [comment]
But it's still doing it...

**Comment by vshcherb** [comment]
@nickw7coc is it still reproducible with night build? Which OsmAnd version are using ?

**Comment by nickw7coc** [comment]
I'm using dark mode and light mode for different profiles, and it's happening all the time, has done since early last year...
Version 3.8.4 with no further updates when I do so in Google Store, at least twice a week, on Huawei Mate P20 Pro running Android 10.1.0.329.

**Comment by nickw7coc** [comment]
Here are various screen grabs going back to 7thJan... I have more of needed... 🤔 
![Screenshot_20210118_115439_net osmand](https://user-images.githubusercontent.com/1060345/104912283-f9b66480-5983-11eb-9ab8-f3c16763db24.jpg)
![Screenshot_20210117_171818_net osmand](https://user-images.githubusercontent.com/1060345/104912311-03d86300-5984-11eb-8faa-5687e8dc4fd0.jpg)
![Screenshot_20210117_132752_net osmand](https://user-images.githubusercontent.com/1060345/104912332-0935ad80-5984-11eb-91f8-cb661f298915.jpg)
![Screenshot_20210114_211044_net osmand](https://user-images.githubusercontent.com/1060345/104912359-1357ac00-5984-11eb-8b4f-afea9e3455d4.jpg)
![Screenshot_20210107_073445_net osmand](https://user-images.githubusercontent.com/1060345/104912414-210d3180-5984-11eb-993b-ff9f678eb816.jpg)

**Comment by vshcherb** [comment]
It's going to be Beta this week, so this issues will be fixed there

**Comment by nickw7coc** [comment]
Thank you and good luck :)
