### ISSUE TITLE
Add POI address / type to share / copy it

### ISSUE THREAD

**Issue by AnastasiaTiutina** [osmandapp/OsmAnd#10466]
# Review 
- [x]  "Nearby POI" doesn't show up if poi is a polygon.
- [x] Use "ic_action_street_name" for "Copy address"
- [x] Show POI Name in line (and distance) - wikipedia as well
- [x] Don't show for public transport
- [x] "Show on map" as last button - wikipedia as well, show on map open map UI + search bar with category name (already implemented) / Hide POI (if already visible)
----------------
### Description
Add the POI address in the context menu with an opportunity to copy it 

### How to reproduce?
Open OsmAnd 
Find POI
Tap on POI
In the context menu, there are POI coordinates
Add the line Adress

**Comment by vshcherb** [comment]
We need to add to context menu rows:
- Address
- POI category
So user can copy it.

**Comment by vshcherb** [comment]
We could add to Share
- [ ] Share address (copy it)
We could add to Poi Context menu:
- [ ] Poi type
So user can search from it similar POIs and copy it

**Comment by Chumva** [comment]
This should be added here - https://github.com/osmandapp/OsmAnd/pull/10533

**Comment by dmpr0** [comment]
# Review 
- [ ]  "Nearby POI" doesn't show up if poi is a polygon.
- [ ] Use "ic_action_street_name" for "Copy address"
