### ISSUE TITLE
Quick action map: suggestion to display current map name

### ISSUE THREAD

**Issue by suntri-star** [osmandapp/OsmAnd#10473]
In the quick action I made a menu item for "Overlay" and "Underlay" maps as well as "Map display" (see picture). In the overview (see picture) the first entry in the list is always shown and not what is currently selected. It would be great if the currently selected map is always displayed. I hope you understand.

Pictures here: 
https://www.rigert.com/overlander-forum/viewtopic.php?f=17&t=7&p=8#p8

**Comment by vshcherb** [comment]
![Uploading image.png…]()

**Comment by vshcherb** [comment]
Main suggestion is to display current name cause it's impossible to fit 2 names:
“Offline Maps → …”

In another case it's possible to shrink 2 names but it looks weird
"Offline ... → Slope ..."

**Comment by dmpr0** [comment]
# Review 
- [ ]  Use this arrow LTR: "▶", RTL: "◀".
- [ ] Check how it work with RTL

**Comment by Nine-Tailed** [comment]
If create two quick action buttons for an overlay or underlay map, the name displayed on the button no longer matches the active map. 

Если создать две кнопки быстрого действия для слоя наложения или слоя подложки, то отображаемое на кнопке название перестает соответствовать активному слою.

OsmAnd~ 4.0.0#32267m, дата выпуска: 2021-06-29

**Comment by vshcherb** [comment]
If there are only 2 maps, then we show next map and not current

**Comment by Nine-Tailed** [comment]
Not obvious behavior, thought it was a bug. Thanks for the explanation.
