### ISSUE TITLE
Add support for club key on the map

### ISSUE THREAD

**Issue by MarkusGaugg** [osmandapp/OsmAnd#10486]
OSMand don't support the club Key as POI on the map. Should be shown on the map like the rest of the POI’s.

 

https://wiki.openstreetmap.org/wiki/Key:club

 

It would be important that all under keys are also supported:

 

Cultural

• club=culture A cultural club that doesn't fit in other categories. Consider using a specific new value instead of this.

• club=ethnic A club to promote ethnic or inter-ethnic culture.

• club=politics

• club=history A club devoted to (local) history and traditions

• club=art

• club=cinema

• club=theatre

• club=music A club where people sing or play music

Doityourself

• club=doityourself Do it yourself club (electronics, clothes,..)

• club=filmmaking A club of people making films together, non-professionally.

• club=cooking

Electronics

• club=amateur_radio An amateur radio club, usually part of national association.

• club=computer

• club=linux A Linux User Group (LUG)

Gaming

• club=game A club devoted to games. See also club=card_games and club=board_games.

• club=board_games A club devoted to board games. See also club=game.

• club=card_games A club devoted to games involving regular playing cards. See also club=game.

• club=chess

Philanthropic

• club=charity A club devoted to charitable activities: blood/tissues donation (for blood donation facilities, use healthcare=blood_donation instead), humanitarian,..

• club=environment_protection

Recreation

• club=equestrian A club for equestrian activities

• club=fishing (for competitions see club=sport + sport=fishing)

• club=hunting (see also club=sport+sport=shooting)

• club=nature A club devoted to nature study: mushrooms, rocks, flowers, birdwatching, and so on. Consider creating specific values for each of these.

• club=sport + sport=*

• club=sailing

• club=tennis

• club=yachting

• club=rowing

• club=scuba_diving

• club=aviation

Social

• club=social

• instead: amenity=community_centre + community_centre:for=senior

• club=religion + religion=* + denomination=*

• club=freemasonry A Masonic Lodge/temple/hall used by Freemasons.

• club=veterans A club of war veterans (e.g., in Italy "Gruppo alpini" or "Gruppo partigiani").

• club=smoke

• club=nudism Nudist club

• club=fan A fan club.

• club=gardening

Other

• club=dog

• club=student

• club=photography

• club=tourism

• club=astronomy An amateur astronomy club

• club=motorcycle A club of motorcyclists

• club=automobile

• club=bicycle Promote and enjoy bicycle usage (for competitions see club=sport + sport=cycling)

• club=scout A scout group base. For Scouts, Guides or any similar groups.

• club=surf_life_saving A surf life saving club

• instead: amenity=community_centre + community_centre:for=juvenile

• club=youth_movement Organisation for children that typically meets weekly. Distinctly different from Scouts. Mainly used in Flanders but not limited to.

**Comment by vshcherb** [comment]
I guess we would support only with more > 100 appearances

**Comment by scaidermern** [comment]
See  #9190

**Comment by MarkusGaugg** [comment]
@scaidermern Thanks for the hint. Would be nice.

**Comment by frasty** [comment]
I guess extended support to club=* should be considered due to the uncertainity for amenity=clubhouse to be an [approved tag](https://wiki.openstreetmap.org/wiki/Proposed_features/clubhouse) in the near future. There seems to be a general sentiment with dealing the club=* tag like shop=* and office=* are: official physical places where people meet. So to me these places should be supported and visibile on the map just like shop and office are.

**Comment by vshcherb** [comment]
We probably can solve it differently i.e. for low frequent POI we can create POI category "Club=generic" with translations and add subtype to the POI name itself like. Anyway on the map we don't need to make separation and have generic icon

Club Movie (filmmaking)

**Comment by vshcherb** [comment]
I think most of the popular clubs is added new story could be continued in 4.3
