### ISSUE TITLE
Dashcam video loop

### ISSUE THREAD

**Issue by bikebon** [osmandapp/OsmAnd#10499]
Option to set loop recording in video note settings
10 20 30 minute loop perhaps
As in dashcam safety recorders

**Comment by alex-osm** [comment]
The feature is already implemented. You may adjust it at Audio-Video notes plugin settings - Recorder split / Clip length / Storage size.

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/74016125/103411473-32cb9800-4b81-11eb-8dfd-b095ccabcbce.jpeg"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by alebalweb** [comment]
But how does it work? I open the navigator, start driving, and it starts recording? I can't find any buttons to start it or any options to select anywhere...
