### ISSUE TITLE
Make  Wikipedia Languages Global setting

### ISSUE THREAD

**Issue by letypequividelespoubelles** [osmandapp/OsmAnd#10503]
# 🚀 feature request

### Description

As I don't speak every Wikipedia languages, I don't need all articles to be download! Most of the shown on the map (with quick action) wikipedia article will be useless for me, as I can't understand it. It's especially the case while visiting a foreign country and using Wikipedia as a travel guide. (Will be even better when #6407 will ne corrected, all dates are nos missing).

### Describe the solution you'd like
Add an option that specify for which differents languages you want to DL wikipedia articles.

### Describe alternatives you've considered

I don't see. Thanks for this app

**Comment by aceman444** [comment]
This already existed in the past (every language was a separate download), but on the other hand the articles in the file were for the whole world, not only the countries selected. So again some waste of bandwidth.

In the newest OsmAnd you can select which languages to show in the Wikipedia layer, so while you have to download all, only your wished langs are displayed.

**Comment by vshcherb** [comment]
That idea was stopped cause 50% of the disk space is English and it was needed by majority of users cause English is usually a second language after native people can read and somehow understand.
So from disk space there is no benefit to distribute English + Native language packages but it's also will be overcomplicated way to package stuff.

**Comment by letypequividelespoubelles** [comment]
>That idea was stopped cause 50% of the disk space is English 

OK, I didn't expect English to be that predominant.

>In the newest OsmAnd you can select which languages to show in the Wikipedia layer

Which version?  I have 3.8.5 from F-Droid and I don't see this option. This would be enough imho to close the ticket.

**Comment by vshcherb** [comment]
3.8.5 
![image](https://user-images.githubusercontent.com/1042025/104353644-6b1b9080-5508-11eb-9c92-18f70d3099d6.png)

**Comment by letypequividelespoubelles** [comment]
@vshcherb I just saw the option, thanks, but we have to select the languages for every different profile, maybe better to have the possibility to select languages for every profiles.

Many thanks.

**Comment by vshcherb** [comment]
Hm... I think it's a bug it should be global.
