### ISSUE TITLE
What3Words support

### ISSUE THREAD

**Issue by bikebon** [osmandapp/OsmAnd#10500]
Support for What 3 words location finding and sharing would be a really useful feature as the format is being widely adopted in many apps now

**Comment by JonnyTech** [comment]
https://wiki.openstreetmap.org/wiki/What3words#Alternatives

**Comment by scaidermern** [comment]
Please don't support this proprietary and closed address system, see #3081.

**Comment by robinpaulson** [comment]
Ugh, no

**Comment by jfburke3** [comment]
One of the problems with What3Words is that it represents 2 dimensional thinking. It would be fairly useless in a Megacity future like the one depicted in Judge Dredd.
