### ISSUE TITLE
Different color for piste:grooming - make them more visible

### ISSUE THREAD

**Issue by miramikes** [osmandapp/OsmAnd#10502]
Hi there,

I am suggesting to use different color for piste:grooming. They are now green and they are not easily distinguished from background as these tracks very often lead trough forest and meadows ( both green ) and are also often mixed with boundaries of National Parks and Protected Areas ( both green ) 
It is especially seen when you zoom out a little bit ... than crosscountry tracks almost disappear and is impossible
to do some visual planning of your route.
Maybe CC tracks should even stay thicker a bit while zooming out to make this "visual planning" possible. 
All is fine if track is part of route=ski than it will get violet boundaries and is perfectly visible.

best regards

mira

**Comment by vshcherb** [comment]
Actually they should be used with Winter map style

**Comment by miramikes** [comment]
Yes, I am using them with style "Winter and ski" 
This style has a low contrast so it should be possible to make crosscountry tracks better visible rather easily I believe.

best regards

mira

**Comment by xmd5a2** [comment]
@miramikes do you mean piste:type=nordic + piste:grooming=* ? Please provide screenshots for clarification.

**Comment by miramikes** [comment]
Hi,

![Screenshot_1](https://user-images.githubusercontent.com/623412/104249258-589f4980-546b-11eb-847c-5df42c37002f.jpg)
Here is first screenshot. You can see map in zoom level which I use for choosing my route.
There is ski route in Czech on left Czech/Polish border in middle and ski route in Poland ... by the way Violet color for ski route is quite confusing with state border line and might be with other border lines too.
So ski routes are visible fine at this zoom level, but ski tracks which are between Czech ski route and state border which are not part of ski:route are visible much worse and green border lines of protected areas make situation even worse.

m.

**Comment by miramikes** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/623412/104250710-71f5c500-546e-11eb-825c-368beb28d9a4.jpg)

Here ... Area "Rybi Loucky" is protected area, but the green line line leading to this place from northwest is piste:grooming=backcountry
Green line above is another protected area and green line below is another piste:grooming=backcountry

Consider please that bad light conditions in field as strong sun shine or snowflakes malting on display make things even worse.

I believe that different color than green for piste:type=nordic + piste:grooming=* would be great
and different color than violet for ski:route too.

m.

**Comment by miramikes** [comment]
Let me know please if you need some other screenshots or comments.

best regards

mira

**Comment by xmd5a2** [comment]
I've changed colour and increased width a bit. Is this better for you?
![Screenshot_2021-01-12_16-19-09](https://user-images.githubusercontent.com/5829014/104319471-f76e8900-54f1-11eb-9d22-0ca0648f28a4.png)
![Screenshot_2021-01-12_16-18-43](https://user-images.githubusercontent.com/5829014/104319476-f89fb600-54f1-11eb-9bd7-7f254dea5737.png)

**Comment by miramikes** [comment]
Hi,
It looks much better to me.
I believe it should be fine like this.
Can't wait to see this change in app.

Many thanks !!!

Mira

**Comment by vshcherb** [comment]
You can always try nighly builds one of the version could be used next to Google Play version

**Comment by miramikes** [comment]
I am already beta tester, but want try nightly builds ... Which file I should install???
https://download.osmand.net/latest-night-build/

thank you 

mira

**Comment by xmd5a2** [comment]
OsmAnd-nightly.apk  or OsmAnd-default.apk

**Comment by miramikes** [comment]
I am not sure that I am succeeded to install nightly builds :( My app says: OsmAnd+ 3.9.1, but skiing tracks on my map is still rather 
green than green-blue like on yours updated style :( Not sure where is problem.
Any idea?

Anyway I found another related issue which could be improved:
At certain zoom level some paths change from grey dashed lines to solid black lines I believe if these black lines stayed rather pale and greyish It would help to keep higher priority for ski tracks.  
![Screenshot_3](https://user-images.githubusercontent.com/623412/104510468-88755b00-55eb-11eb-80b2-258c0c1e1995.jpg)

**Comment by xmd5a2** [comment]
@miramikes It is highway=track. I agree that they are too bold at zooms <=13. Fixed 
![Screenshot_2021-01-14_16-05-57](https://user-images.githubusercontent.com/5829014/104594670-8ca08780-5682-11eb-916c-24c426dbe2b6.png)

**Comment by miramikes** [comment]
I finally manage to install OsmAnd-default.apk to see properly your changes on phone display they looks great and improving situation hugely. Only in some "middle" zoom level I still have subtle problem easily distinguish between boundary=protected_area and ski track ... note please that situation looks better on screenshot rather than on phone display !
Not sure what could help this to improve ... maybe a "touch" more pale green color for boundary=protected_area
What do you think ?

best regards

mira
![Screenshot_6](https://user-images.githubusercontent.com/623412/104682952-32410e80-56f6-11eb-88e2-4ccb86e861c3.jpg)

**Comment by miramikes** [comment]
Thank you for latest change it is better now.
I have couple of other suggestions for improvement for "winter and ski" style if you don't mind
1) I would keep highway=track even a touch thinner and/or paler in higher zoom
![Screenshot_06](https://user-images.githubusercontent.com/623412/105621455-c4889700-5e07-11eb-84ce-f703ee11cd0c.jpg)
2) on my previous screenshot is dashed green line ... I believe it is "ridge" ... it is definitely great feature on winter map,
but I would suggest make this line much thinner and still dashed ... maybe can be thin and dark green ... to be more different from natural reserve boundaries and not to be confused with and kind of tracks
3) ski lift ... ending points could be quite smaller at higher zoom level ... 
![Screenshot_08](https://user-images.githubusercontent.com/623412/105621466-eda92780-5e07-11eb-8b9a-0b002c3c8125.jpg)

best regards

mira

**Comment by xmd5a2** [comment]
https://github.com/osmandapp/OsmAnd/issues/10710
https://github.com/osmandapp/OsmAnd/issues/10766
