### ISSUE TITLE
OsmAnd calculates an invalid route - looks like try very hard to not drive through a crossing

### ISSUE THREAD

**Issue by travnick** [osmandapp/OsmAnd#10514]
# 🐞 routing report

### Routing engine

-  OsmAnd's in-app offline routing

### Routing Profile

car - default

### Start and end points
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=50.48513%2C19.42690%3B50.48529%2C19.42665#map=19/50.48531/19.42748

### Actual and expected routes

I expect the same route as on openstreetmap, but the current is:
![Screenshot_2021-01-03-14-42-50-080_net osmand plus](https://user-images.githubusercontent.com/619590/103480095-81bc3c00-4dd2-11eb-9d63-4849bd8a8495.jpg)
![Screenshot_2021-01-03-13-35-42-467_net osmand plus](https://user-images.githubusercontent.com/619590/103480096-841e9600-4dd2-11eb-93ca-8fa949c09e8c.jpg)

### Is this a regression?

It used to work properly some time ago, but unable to tell if it's a version change or map update.

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>OsmAnd~3.8.5
</code></pre>

**Device and Android/iOS version:**
Redmi 4X with Android 7.1.2.N2G47H

**Maps used (online or offline):**

- Offline maps offered within the OsmAnd app for download.
 "Polska województwo śląskie" 1.12.2020 with OsmLive enabled/disabled
-->

**Anything else relevant?**
When start and destination points are switched, then it routes correctly.

**Comment by alisa911** [comment]
https://www.openstreetmap.org/relation/3998316
