### ISSUE TITLE
Solicitud de características

### ISSUE THREAD

**Issue by ocniel** [osmandapp/OsmAnd#10529]
Es posible crear un círculo en el mapa con un diámetro determinado, y que éste a la vez se desplace junto al mapa??? La opción del menú REGLA RADAL no es lo que necesito. Necesito un  círculo que se desplace al mover el mapa.
Gracias.

![IMG_20210103_113105](https://user-images.githubusercontent.com/50027218/103671324-c23dc600-4f48-11eb-9dde-5407ace1d114.jpg)

**Comment by vshcherb** [comment]
Unfortunately not, it's only possible to have radius-ruler with given radius
