### ISSUE TITLE
city name missing while smaller towns displayed

### ISSUE THREAD

**Issue by kavol** [osmandapp/OsmAnd#10535]
### Description
Trying to find something on map near České Budějovice, I have found that OsmAnd is not displaying this city until very close zoom, while much smaller towns are displayed.

### How to reproduce?
Just display the default map, center it on České Budějovice and try different zoom levels.

### Your Environment
OsmAnd Version: 3.8.5
Android/iOS version: 10 (Ressurection Remix 8.6.5)
Device model: Redmi 6 Pro (sakura)

**Maps used (online or offline):**   
offline - Czech-republic_jihovychod_europe.obf - 2021-01-01

**Comment by kavol** [comment]
![Screenshot_20210106-151707097](https://user-images.githubusercontent.com/2169753/103780644-8c2a4000-5035-11eb-8cf2-7c7161710f11.jpg)
![Screenshot_20210106-152338600](https://user-images.githubusercontent.com/2169753/103780648-8d5b6d00-5035-11eb-8871-8be96249a232.jpg)

**Comment by kavol** [comment]
compare
České Budějovice - https://www.openstreetmap.org/node/1599120629 - city - population 94463 - not displayed
Hluboká nad Vltavou - https://www.openstreetmap.org/node/1599120883 - town - population 5305 - displayed

**Comment by kavol** [comment]
well, thinking about it, the question is not just why České Budějovice is not displayed, but also the other way round, what makes Hluboká nad Vltavou so important to be displayed?

looking at the second screenshot, if Hluboká nad Vltavou is displayed then I would expect also Český Krumlov (https://www.openstreetmap.org/node/1599136536) to be displayed, because it is the same category place=town and the population is 13028 which is more than twice as much

**Comment by JAnDud** [comment]
Also note there is not displayed Roudné (pop 1500), but its hamlet Lorenc with 4 houses - on the first map.
On the second is also missing Písek, but much smaller Bechyně is here

**Comment by vshcherb** [comment]
I don't think problem is related to Hluboká nad Vltavou. Many towns in OSM have population > 100K, so they should be displayed with reasonable priority.

It's not clear why `České Budějovice` not displayed and it should be investigated.

**Comment by letypequividelespoubelles** [comment]
>I don't think problem is related to Hluboká nad Vltavou. 
 
I confirm it's a more global issue. For example zooming in Paris, France will show Levallois-Perret, Pantin, Montrouge, small city around Paris, but not Paris. .. it's strange.

**Comment by sedot42** [comment]
This seems similar to #5415.

**Comment by xmd5a2** [comment]
I've made some corrections and in my tests all issues described here are solved. Also many other regions was improved. Please test.
