### ISSUE TITLE
Outdated data in maps of 1st Jan 2021

### ISSUE THREAD

**Issue by aceman444** [osmandapp/OsmAnd#10538]
In the maps of 1st Jan 2021 data added in Dec 2020 is missing.
The data is old and shows the state maybe of about 1st Dec 2020.
I have seen this at least in the map of Slovakia.

**Comment by vshcherb** [comment]
Maps are now regenerated and they should be redownloaded the process will be catch up tomorrow

**Comment by aceman444** [comment]
Thanks, I confirm the fix.

**Comment by verdulo** [comment]
Poland, Silesian Province, full map of 1st April 2023 does not contain changes added to OSM during March.

**Comment by scaidermern** [comment]
Same problem as #16872?
