### ISSUE TITLE
craft=yes -> Other tags are not read out in the app

### ISSUE THREAD

**Issue by MarkusGaugg** [osmandapp/OsmAnd#10530]
It is a furnace construction company. Because there is no special tag in the OpenStreetMap for this type of business, it was simply tagged as a craft business -> craft=yes.

Unfortunately the OSMand app does not read all the data. The following information is available, but is not displayed in the app:

addr:city=Scharnitz
addr:housenumber=120
addr:postcode=6108
addr:street=Hinterautalstraße
craft=yes
email=elias9er@aon.at
name=Ofenbau Neuner
opening_hours=Mo-Fr 09:00-17:00
operator=Elias Neuner
phone=+43 676 6191792
website=https://www.ofenbau-neuner.at

Source:
https://www.openstreetmap.org/node/8287370116

The app also shows an info symbol, but should display a corresponding craft symbol.

![Screenshot_20210105_201810_net.osmand.plus.jpg](https://user-images.githubusercontent.com/2048093/103689126-2c7b5880-4f93-11eb-846b-c22d95671f99.jpg)
![Screenshot_20210105_201813_net.osmand.plus.jpg](https://user-images.githubusercontent.com/2048093/103689162-38ffb100-4f93-11eb-950a-cd617a35a02c.jpg)

**Comment by xmd5a2** [comment]
craft=yes is not described in wiki. We support POI info only for described POI.

**Comment by MarkusGaugg** [comment]
Thanks for the information. Where can I suggest that the furnace construction company will be included in the official OpenStreetMap as described POI?

**Comment by xmd5a2** [comment]
@MarkusGaugg see https://wiki.openstreetmap.org/wiki/Key:craft. Possible that "furnace construction company" can't be properly described in OSM at that moment.

**Comment by pebogufi** [comment]
@MarkusGaugg 
The tagging is a technique for categorizing things. So, if your special craft is not in the wiki list, it might be appropriate to look for a superior categorie, or something similar, may be hvac or plumber or something else and then add the categorie you need in description as 
description = furnace construction.
I hope this helps as a workaround.
