### ISSUE TITLE
Add or change the speed unit setting for "min/km" to show seconds ("m:s/km") instead of fractional minutes (m.m/km)

### ISSUE THREAD

**Issue by hbierlee** [osmandapp/OsmAnd#10532]
# 🚀 feature request

### Description

The default for the min/km unit of speed in sports (like running) is to show minutes and seconds per kilometer and not fractional minutes per kilometer (e.g., 4:30 min/km instead of 4.5 min/km). The latter is currently the only setting, while on other apps that show the min/km unit (like Strava) it is usually the former, which is arguably more intuitive.

(I am coming from a runner use case perspective who would like to replace Strava for OsmAnd. Perhaps from another viewpoint the fractional view is more intuitive)

### Describe the solution you'd like

My suggestion would be to change the current speed `min/km` unit to show `min:sec/km`, or add a new speed unit for `min:sec/km`.

### Describe alternatives you've considered

Other than using third-party software to analyze my tracks, there doesn't seem to be a current solution except mentally converting fractional minutes to seconds using the current min/km speed unit setting.

**Comment by sonora** [comment]
Indeed a valid request.

**Comment by hbierlee** [comment]
I might take a crack at this. Would you prefer a new separate unit (like `SpeedConstants.MINUTES_AND_SECONDS_PER_KILOMETER`), or should I change the existing unit's formatting? A possible advantage to having fractional minutes is that they are easier to add mentally, maybe that would justify its existence.

Also, the same goes for the `MINUTES_PER_MILE` one, I guess.

**Comment by sonora** [comment]
Just speaking for myself, no final decision yet: I would argue that _min:sec_ is conventional, while displaying decimal fractions of  (time) minutes seems expendable to me.

**Comment by vshcherb** [comment]
Certainly I would change and don't leave decimal option for now, if we've get enough requests we can always bring it back.
I think it was a mistake in original place mm:ss / km or mm:ss / mi is definitely better
