### ISSUE TITLE
Map display errors at Auckland, NZ 

### ISSUE THREAD

**Issue by robinpaulson** [osmandapp/OsmAnd#10534]
36.86265° S, 174.81053° E
Orakei train station floods at close zoom levels. See attached image ![](https://i.imgur.com/pcnrqTw.png)

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-core/pull/198

**Comment by robinpaulson** [comment]
@alisa911 I installed 3.9.5 today, along with february map data, but still get flooding here. Do i need to wait for the march data, or a later version of osmand? Thanks

**Comment by robinpaulson** [comment]
Same deal with 396 today

**Comment by robinpaulson** [comment]
Fixed, cheers!
