### ISSUE TITLE
Search doesn't find street within city with suburb

### ISSUE THREAD

**Issue by Famlam** [osmandapp/OsmAnd#10548]
### Description
In a city with defined suburbs, the user would have to be aware of the exact suburb to find a street within the city. Most of the cases, I'd just search for the city (and thus not the region in the city, which I often don't know).

### How to reproduce?
1. Download The Netherlands-> Gelderland offline maps
2. Start Navigation to an Address
3. Select to choose the city -> select Nijmegen
4. Notice [Couwenbergstraat](https://www.openstreetmap.org/way/112789653#map=18/51.80593/5.82602) (and many others) are missing in the list of streets

### Your Environment
OsmAnd Version: 3.8.4
Android/iOS version: 9
Device model: LG

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
The Netherlands, Gelderland, dec 2020

**Comment by alisa911** [comment]
The bug will be fixed with February maps.
