### ISSUE TITLE
Getting error on android gradle build - Android Studio

### ISSUE THREAD

**Issue by rajeevinimekumar008** [osmandapp/OsmAnd#10555]
Hi, 
I have downloaded the source code and try to build the project on android studio. I am getting error and build failed

`Unable to resolve dependency for ':OsmAnd@freedevQtcoredebugArmv7Debug/compileClasspath': Failed to transform artifact 'OsmAndCore_androidNativeDebug.aar (net.osmand:OsmAndCore_androidNativeDebug:0.1-SNAPSHOT)' to match attributes {artifactType=jar}`

`Unable to resolve dependency for ':OsmAnd@freedevQtcoredebugArmv7DebugAndroidTest/compileClasspath': Failed to transform artifact 'OsmAndCore_androidNativeDebug.aar (net.osmand:OsmAndCore_androidNativeDebug:0.1-SNAPSHOT)' to match attributes {artifactType=jar}`

Getting as such 100 errors on all abi types on build. Please suggest ...

**NOTE - Can anyone confirm would this app runs fine on device with no play services installed**

**Comment by vshcherb** [comment]
https://docs.osmand.net/en/main@latest/development/build-osmand/setup-the-dev-environment
https://docs.osmand.net/en/main@latest/development/build-osmand/how-to-compile-the-android-version
Here it should be compilable

**Comment by rajeevinimekumar008** [comment]
Hi,

I have downloaded all repositories in the respective folders as mentioned in 

[https://docs.osmand.net/en/main@latest/development/build-osmand/setup-the-dev-environment](url) 

I have created a root folder say "OSM" and then sub folders as mentioned in above link. Copy the git repositories to respective sub-folder as mentioned.

But still getting 100 errors on build on android studio

`Unable to resolve dependency for ':OsmAnd@freedevQtcoredebugArmonlyDebugAndroidTest/compileClasspath': Failed to transform OsmAndCore_androidNativeDebug-0.1-SNAPSHOT.aar (net.osmand:OsmAndCore_androidNativeDebug:0.1-SNAPSHOT) to match attributes {artifactType=jar, org.gradle.status=integration}.`

`ERROR: Unable to resolve dependency for ':OsmAnd@freeQtcoredebugFatDebug/compileClasspath': Failed to transform OsmAndCore_androidNativeDebug-0.1-SNAPSHOT.aar (net.osmand:OsmAndCore_androidNativeDebug:0.1-SNAPSHOT) to match attributes {artifactType=jar, org.gradle.status=integration}.`

Please guide. What could be the issue.


`

**Comment by vshcherb** [comment]
I would try to build with gradle first cause it's a reproducible build and we continously build it on our server
