### ISSUE TITLE
piste:type=skitour

### ISSUE THREAD

**Issue by miramikes** [osmandapp/OsmAnd#10552]
Hi there,

I've noticed we have have mentioned piste:type=skitour map legend but they are not visible on map.
I saw on osm map they are often described as piste:type=nordic;skitour ... Are they rendered correctly?
Same "way" ( 19921115 ) also having tag piste:grooming = classic+skating but is not rendered as nordic piste ... nor skitour

best regards

mira

**Comment by miramikes** [comment]
I've checked if I can see piste:type=skitour with latest night build, but I can't ...
There is skitour track zigzaging below summit of Stoh mountain in Krkonose CZ ... it is taged on osm maps .., but it is not visible in OsmAnd
Same on other places in Krkonose ...   
![Screenshot_7](https://user-images.githubusercontent.com/623412/105568824-b3bf1f00-5d3c-11eb-99b3-3bbe238b6cf7.jpg)

**Comment by xmd5a2** [comment]
@miramikes OsmAnd maps are updated monthly
