### ISSUE TITLE
Wrong city for building, despite OSM data being correct

### ISSUE THREAD

**Issue by xavierd** [osmandapp/OsmAnd#10559]
### Description

In San Jose California, several block of buildings are located in OsmAnd in the wrong city. The OSM metadata is properly specified as "San Jose", but for some reason OsmAnd believes that they either belong to Santa Clara, or Campbell. See the address below for an example.

![Screenshot_20210111-220818](https://user-images.githubusercontent.com/50892/104276546-f0943780-5459-11eb-8d7d-98155cad6968.png)

### How to reproduce?

Just open the address shown in the screenshot above.

### Your Environment
OsmAnd Version: 3.8.4
Android/iOS version: Android 11
Device model: Pixel 4

**Maps used (online or offline):**  online

**Comment by letypequividelespoubelles** [comment]
Same as #10036

**Comment by xavierd** [comment]
@letypequividelespoubelles it might be slightly different here, as the POI does have a city specified in the OSM metadata.

**Comment by vshcherb** [comment]
The address from OSM node is not used, the detection happens by given lat/lon coordinates but that doesn't explain why city is different than expected

**Comment by alisa911** [comment]
The bug will be fixed with February maps.

**Comment by Hedaja** [comment]
> @letypequividelespoubelles it might be slightly different here, as the POI does have a city specified in the OSM metadata.


Sorry for bringing this up again in this old issue but we stumbled across it when we talked about this topic in German OSM chat. 
Is there a reason why it was decided to not use the address on the POI/node but instead do the extra step of reverse geocoding. It seem more difficult and more prone to failure.

Thanks 
Christian

**Comment by vshcherb** [comment]
it reduces amount data stored on POI and most of POI don't have address on points anyway
