### ISSUE TITLE
[bug] flooded area while zooming

### ISSUE THREAD

**Issue by letypequividelespoubelles** [osmandapp/OsmAnd#10567]
### Description
Area become flooded while zooming near 44.11670° N, 15.22657° E 
I can provide screenshot if needed

### How to reproduce?
Zoom near this place, the dock of the harbor become flooded.

### Your Environment
OsmAnd Version: 3.8.5
Android/iOS version: 9
Device model: BV9500plus 

**Maps used (online or offline):**   
Latest Croatia live map based on the 01/01/2021 offline maps

**Comment by xmd5a2** [comment]
Please provide screenshot

**Comment by letypequividelespoubelles** [comment]
No problem up to this zoom

![Screenshot_20210112152326](https://user-images.githubusercontent.com/54240434/104645721-b91ec880-56af-11eb-83ca-39485171c3bc.png)

Flooded after this zoom
![Screenshot_20210112152320](https://user-images.githubusercontent.com/54240434/104645726-ba4ff580-56af-11eb-8feb-07e9c41be0c0.png)

**Comment by letypequividelespoubelles** [comment]
ping @xmd5a2

**Comment by xmd5a2** [comment]
Did not found obvious reason for this. Basemap coastline sometimes is displayed instead of detailed coastline.

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-core/pull/198
