### ISSUE TITLE
Rendering: textDy is not calculated for bbox correctly

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/OsmAnd#10569]
bboxes for text are calculated incorrectly: dy is not supported, also wrong proportions. This causes text placement errors.
![Screenshot_2021-01-13_11-43-16](https://user-images.githubusercontent.com/5829014/104440118-02352680-55a3-11eb-9418-4e271146de8a.png)
![Screenshot_2021-01-13_11-31-15](https://user-images.githubusercontent.com/5829014/104440122-03665380-55a3-11eb-86e8-c3146eb175c4.png)
![Screenshot_2021-01-13_11-55-07](https://user-images.githubusercontent.com/5829014/104440402-5a6c2880-55a3-11eb-9280-80a443692b55.png)
They can be viewed by setting style setting
`<renderingAttribute name="debugTextDisplayBBox">`
to **true**

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-core/pull/190

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-core/pull/191

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-core/pull/193
