### ISSUE TITLE
Improve favourities usability

### ISSUE THREAD

**Issue by ioctl-user** [osmandapp/OsmAnd#10560]
I have noticed, that planning travel with OsmAnd requires much more manipulations comparing to apps like Maps.me :

Adding one subsequent mark in group requires:
2 taps in Maps.me, icon selected automatically
4-5 taps in OsmAnd, because icon should be selected manually

Removing mark requires:
2 taps in Maps.me
5 taps in Osmand

At some scales vafourities circles looks like place icons and can be mixed up.

Suggestions:
Add automatic icon type. Make it default type.
Add more icon shapes that clearly distinquished from cirles.
Allow adding and removing favourities in two taps.

**Comment by dmpr0** [comment]
Hello! Thank you for the feedback.
You can add a favorite in two-three taps, select place on map > open context menu > add > save.

**Comment by ioctl-user** [comment]
This short sequence doesn't assume changing icon of mark.
And even in this case, it has twice more taps than in maps.me.

**Comment by dmpr0** [comment]
Select icon, the shape is additional steps, you can skip them. If you need to mark places quickly you can use map markers or create quick action with the template.

**Comment by ioctl-user** [comment]
> Select icon, the shape is additional steps, you can skip them.

Even without shape selection, it twice more difficult that is could be.

> If you need to mark places quickly you can use map markers or create quick action with the template.

Markers are not suitable for sharing and saving travel plans.
Quick action is not user-friendly and even in case of implementation will not allow adding mark in two taps.

**Comment by vshcherb** [comment]
Exactly why we suggest markers to use in such cases - 2 taps in OsmAnd to add and delete
