### ISSUE TITLE
"Plan Route" mode - Track length is different in top view and between points in the list

### ISSUE THREAD

**Issue by RinkBies** [osmandapp/OsmAnd#10562]
### Description
First of all, thanks for all the work you are doing. Osmand is great tool.
However, there is bug in release 3.8 (Android), with the calculation of the track length.
The track length is only calculated correctly for the profile "straight line". When you use another profile, the calculation of the track length is going totally wrong.

### How to reproduce?
1. Select the profile "straight line", and create a simple track. See the attached file "straight-line.jpg".  I have created a track of only 2 points. The distance between the two points is 100 meter. The track length is also 100 meter. So, everything is OK.
2. Now switch to the profile "bike" (or any other profile). See the attached file "bike.jpg". The distance between the two points is still 100 meter, but the track length has now changed to 343 meter....

![straight-line](https://user-images.githubusercontent.com/77327231/104302492-26243980-54c9-11eb-92cb-c1389ec5ad99.jpg)
![bike](https://user-images.githubusercontent.com/77327231/104302499-26bcd000-54c9-11eb-82f0-5b3827fa967e.jpg)

### Your Environment
OsmAnd Version: 3.8 Android
Android/iOS version: Android 10
Device model: Oppo A9

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by vshcherb** [comment]
I think it's not a bug top view displays distance need to be covered and bottom sheet distance is a straight distance without routing. In case of such short routes the routing produces excessive points and even try to step back (?) which is weird and problem of navigation but not a problem of display

**Comment by RinkBies** [comment]
No, it is bug. It was working correctly in the previous version.....
Attached is a picture for a longer track for a bike. This is track with just three straight lines.
The length between based on the points is 2,99 km, but the total track length is 4,11 km....


![bike2](https://user-images.githubusercontent.com/77327231/104428779-25e97400-5585-11eb-97e5-fe00bddc1ba5.jpg)

**Comment by vshcherb** [comment]
Then I clearly can't reproduce it. Probably it has been fixed in 3.9 (beta is available)

![image](https://user-images.githubusercontent.com/1042025/104485887-5522d400-55cb-11eb-9245-40b681d38b1f.png)

**Comment by vshcherb** [comment]
In my case the error is negligible and it is totally explainable difference of straight lines vs roads approximation

**Comment by RinkBies** [comment]
In my version (3.8.4) it is wrong. On your version (3.9) this OK. So, I guess we can close this.

I'm totally new in GitHub:  Is there somewhere an instruction how to download beta version?

**Comment by pebogufi** [comment]
https://download.osmand.net/latest-night-build/OsmAnd-nightly.apk

**Comment by pebogufi** [comment]
@RinkBies
https://download.osmand.net/latest-night-build/OsmAnd-nightly.apk

**Comment by RinkBies** [comment]
Thanks. I installed the beta version, and the bug is solved. I close this issue!
