### ISSUE TITLE
Checkbox same for all in poi upload

### ISSUE THREAD

**Issue by fatuuse** [osmandapp/OsmAnd#10565]
### Description
Checkboxes for uploading poi to own is same checkbox for all. They are linked. 
Upload many poi at once not work. 

### Your Environment
OsmAnd Version: 3.9.1 2020-12-08

https://user-images.githubusercontent.com/26528052/104359045-82aa4780-550f-11eb-94cc-54fdf20e232e.mp4

**Comment by franco999** [comment]
It's been happening to me too for several days now and it's very annoying when you want to upload +100 notes/bugs/modifications after a trip.

**Comment by scaidermern** [comment]
Can confirm. Selecting multiple edits for uploading will only upload one of them.
