### ISSUE TITLE
Turn Angle error: roundabout exit

### ISSUE THREAD

**Issue by pfg21rus** [osmandapp/OsmAnd#10571]
roundabout exits are not displayed correctly.
![fa25cd21-524c-48e3-8f60-95e0ba7a6837](https://user-images.githubusercontent.com/8830474/104453200-1b46d300-55b5-11eb-9554-689f2fc2636f.gif)  
error location https://www.openstreetmap.org/way/456447143   
Osmand+ 3.9.1 data 2020-12-08    
the error appears on obf 12.2020 and 01.2021  
xiaomi redmi note 8t, miui 12.0.2, android 10 QKQ1.200114.002

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/pull/10632

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/pull/10643

**Comment by vshcherb** [comment]
We need to double check this roundabout https://www.openstreetmap.org/#map=16/59.397762/24.673136

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/2745
