### ISSUE TITLE
Change recording track color 

### ISSUE THREAD

**Issue by ANCIENTCW** [osmandapp/OsmAnd#10574]
# 🚀 feature request

### Description

 I would like to change the color of the track which I currently follow WITHOUT pressing the REC button since during every day driving there is no need to record ALL the tracks during the day.
Presently I  can change track color only for the current track that is RECORDING while navigating. In other cases, It doesn't work.
Thank you in advance,
Adam P. Anczykowski

### Describe the solution you'd like

 If you have a solution in mind, please describe 

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by dmpr0** [comment]
Hi! 
Currently, you can change track color, by selecting in on the map or thru Menu – My places - Tracks.
