### ISSUE TITLE
Live update: relations ignored?

### ISSUE THREAD

**Issue by theraser** [osmandapp/OsmAnd#10570]
### Description
Using Osmand live updates the relation data seem not to be updated.

### How to reproduce?
Download latest map for Germany/Hesse (1. December 2020) including live update.
<img src="https://user-images.githubusercontent.com/7988080/104439952-09a00400-5592-11eb-908f-46e98b96dbff.png" width="300">
<img src="https://user-images.githubusercontent.com/7988080/104439962-0d338b00-5592-11eb-946c-d1fefb5d1146.png" width="300">

Example: search for bus station "Cronstettenstraße" in Frankfurt am Main. It will show the bus line N3, which relations were [deleted on 2012-12-12](https://www.openstreetmap.org/changeset/95719143) (See relations 1019392, 404358, 401488). I would expect that using live update these relations were removed from map data, too.

<img src="https://user-images.githubusercontent.com/7988080/104439993-16245c80-5592-11eb-8f1c-91c18f22a1e3.png" width="300">

<img src="https://user-images.githubusercontent.com/7988080/104440102-39e7a280-5592-11eb-8161-80da55a32b8f.png" width="300">

### Your Environment
OsmAnd Version: 3.8.5
Android/iOS version: Android 10
Device model: Fairphone 3

**Comment by xmd5a2** [comment]
Looks like issue lies in "generate-obf-diff" step. Here is change.osm:
```
<action type="delete">
<old>
  <relation id="1019392" version="7" timestamp="2020-10-30T07:12:24Z" changeset="93273128" uid="160894" user="jodd">
    <member type="relation" ref="404358" role=""/>
    <member type="relation" ref="401488" role=""/>
    <tag k="bus" v="regular"/>
    <tag k="by_night" v="only"/>
    <tag k="name" v="Nachtbus n3: Konstablerwache &lt;=&gt; Riedberg"/>
    <tag k="network" v="RMV"/>
    <tag k="operator" v="In-der-City-Bus"/>
    <tag k="ref" v="n3"/>
    <tag k="route_master" v="bus"/>
    <tag k="service" v="night"/>
    <tag k="type" v="route_master"/>
    <tag k="website" v="https://wiki.openstreetmap.org/wiki/Rhein-Main-Verkehrsverbund/Nachtbus_Frankfurt"/>
  </relation>
</old>
</action>
```
diff.obf does not contain ways from which relations consisted. Instead of that bus stops from these relations are marked as "osmand_change=delete".
![Screenshot_2021-01-18_15-01-16](https://user-images.githubusercontent.com/5829014/104912979-0b0c6a80-599e-11eb-9027-56df5848385c.png)

**Comment by xmd5a2** [comment]
Diff-start:
![Screenshot_2021-01-18_15-40-46](https://user-images.githubusercontent.com/5829014/104917549-9ab51780-59a4-11eb-8afa-2f5493d14fe9.png)
Diff-end:
![Screenshot_2021-01-18_15-41-00](https://user-images.githubusercontent.com/5829014/104917545-9983ea80-59a4-11eb-98a1-eb35c16100f9.png)

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-tools/pull/392

**Comment by vshcherb** [comment]
We have 6 possible test cases for this situation:
1. Add relation (or add new tags )
2. Delete relation (or delete tags )
3. Modify relation tags
4. Add relation member
5. Modify relation member
6. Delete relation member

**Comment by dmpr0** [comment]
Similar https://github.com/osmandapp/OsmAnd/issues/13152
