### ISSUE TITLE
Waypoints of the currently recording track are not shown

### ISSUE THREAD

**Issue by martinstingl** [osmandapp/OsmAnd#10572]
I cannot see waypoints on the map which are added to the currently recorded track. The currently recording track is set visible under "My Places". When I click on it the waypoints are shown on the mini-map.

When I remember the position of the added waypoints I can select them by short clicking on them even if they are not shown on the map.

### Your Environment
OsmAnd Version: 3.8.5
Android/iOS version: 10
Device model: Samsung Galaxy A71

**Comment by vshcherb** [comment]
Merged with https://github.com/osmandapp/OsmAnd/issues/10669

**Comment by Skalii** [comment]
https://github.com/osmandapp/OsmAnd/pull/10689

**Comment by martinstingl** [comment]
This issue still exist for me using OsmAnd 3.9.6.
