### ISSUE TITLE
Implementation of IGN OpenData contour lines for France

### ISSUE THREAD

**Issue by Futur3r** [osmandapp/OsmAnd#10578]
# 🚀 feature request

Hi,

The French National Geographic Institute opened their data a few weeks ago and released highly detailed elevation data that they use for their [map (Topo 25)](https://www.geoportail.gouv.fr/carte).

The links for it are under the [BD ALTI section](https://geoservices.ign.fr/documentation/diffusion/telechargement-donnees-libres.html#bd-alti).

Is it possible to update contour lines for the French offline vector maps with these data ?

**Comment by vshcherb** [comment]
cc @xmd5a2

**Comment by xmd5a2** [comment]
We already use very similar (and sometimes much better) data from https://data.opendataportal.at/dataset/dtm-france but I've inspected them more and found that some of them were not properly prepared to match other data. So I redone some France contour maps and uploaded them.
![Screenshot_2021-01-18_17-06-36](https://user-images.githubusercontent.com/5829014/104948042-aec13f00-59cd-11eb-9c6f-2cba04d31eda.png)
