### ISSUE TITLE
wrong altitude given

### ISSUE THREAD

**Issue by letypequividelespoubelles** [osmandapp/OsmAnd#10584]
### Description
The altitude given in OSMAnd is all the time a few ddozens of meter below the "reality" ie the altitude given by the contour line. This is NOT a problem of altitude detection by the device but an OSMAnd issue. Using GPS Test app (with quick link clicking on the number of satellites used) with same device it gives a reasonable good altitude, just look at the screen shot given.

![Screenshot_20210112124621](https://user-images.githubusercontent.com/54240434/104646730-24b56580-56b1-11eb-9bef-f59091643907.png)
![Screenshot_20210112124811](https://user-images.githubusercontent.com/54240434/104646733-254dfc00-56b1-11eb-9120-1bbf632a59e8.png)

I'm not the lonely user to have this issue, I'll link other issues posted.

### Your Environment
OsmAnd Version: 3.8.5
Android/iOS version: 9
Device model: BV9500 Plus

**Maps used (online or offline):**   
Doesn't change anything.

**Comment by letypequividelespoubelles** [comment]
See for example #10051 #8169 #7438 #4057

**Comment by vshcherb** [comment]
Did you download altitude correction package?

**Comment by letypequividelespoubelles** [comment]
Yes I dl the 1.6 MB world altitude correction (last one is of  08/07/2005). (By the way, I don't understand why one have to dl this correction map, it should be DL for everyone right ? ).

**Comment by sonora** [comment]
Not reproducible om my devices. Just a vague idea: How does it look if you disable the altitude correction? (Maybe there are devices now applying a mean sea level correction by firmware or chipset already....)

**Comment by vshcherb** [comment]
Probably in your case you need to delete that file if correction is already done by chipset. This question is not standardized on Android, for example on iPhone altitude is always corrected to Geoid altitude

**Comment by letypequividelespoubelles** [comment]
@sonora @vshcherb  you are totaly right it works perfectly, I should have thought to delete the altitude correction file. My bad.
