### ISSUE TITLE
Crash when displaying/selecting tracks on the map

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#10585]
Unfortunately not sure how to reproduce, I was displaying several tracks, tapping on them in the map, then playing with their context menu: [exception.log.txt](https://github.com/osmandapp/OsmAnd/files/5819332/exception.log.txt)

**Comment by Chumva** [comment]
This should be fixed here - https://github.com/osmandapp/OsmAnd/commit/c4707e415be148985a27115a18d0ce7358cf550e.
