### ISSUE TITLE
Category Wikimedia Commons Images does not load

### ISSUE THREAD

**Issue by MakiWolf** [osmandapp/OsmAnd#10593]
### Description
Wikimedia Commons Images does not load, when there is no picture on wikidata site.

### How to reproduce?
I have seen it on this poi [https://www.openstreetmap.org/node/342738781#map=19/47.09441/15.43331](https://www.openstreetmap.org/node/342738781#map=19/47.09441/15.43331).
There is a wikimedia_commons tag linked, but there is no image on wikidata site. Wikimedia Commons is only linked from wikidata site.

### Your Environment
OsmAnd Version: 3.8.5 from fdroid and also latest build from github (16.01.2021)
Android/iOS version: 9
Device model: Samsung Galaxy Note 8 and also Android Studio Emulutor

**Comment by vshcherb** [comment]
Unfortunately, Category images are not yet supported

**Comment by NotSoImportant** [comment]
looks like they are working / supported now, am I right? At least I can see them.

**Comment by vshcherb** [comment]
Then it was fixed already

**Comment by NotSoImportant** [comment]
Yes I confirmed with the mentioned item and pictures shows up in 3.9.10
