### ISSUE TITLE
Unnecessary popup is shown after replace another point with this one

### ISSUE THREAD

**Issue by 532910** [osmandapp/OsmAnd#10591]
Steps:

1. `Edit Favorite`
2. `Replace another point with this`

![image](https://user-images.githubusercontent.com/14617699/104807253-b2e33600-57ee-11eb-9bc6-db61520db04d.png)

**Comment by Skalii** [comment]
This issue was fixed here - https://github.com/osmandapp/OsmAnd/issues/10091
