### ISSUE TITLE
Install nightly build over beta release fail 

### ISSUE THREAD

**Issue by miramikes** [osmandapp/OsmAnd#10597]
Hi there,

I wanted to install nightly build to check latest improvements to OsmAnd. While OsmAnd-default.apk instaled fine OsmAnd-nightly failed. I belive OsmAnd-default install beside existing app from google play and OsmAnd install "over" app from google play.
Is it right? As I am beta tester of OsmAnd my app is 3.9.1 and nigthly build is marked as 3.9.0 ... Can this be a problem?

Check my screenshots pls ...

![Screenshot_4](https://user-images.githubusercontent.com/623412/104831585-a0b6d580-588a-11eb-8097-27a2857b1c4a.jpg)
![Screenshot_5](https://user-images.githubusercontent.com/623412/104831588-a6acb680-588a-11eb-9e51-ff67e9c9c075.jpg)

**Comment by vshcherb** [comment]
The builds structure will be restructured, to avoid confusion.  You need to use nightly build instead
https://download.osmand.net/latest-night-build/OsmAnd-default.apk
