### ISSUE TITLE
replace another poing with this

### ISSUE THREAD

**Issue by 532910** [osmandapp/OsmAnd#10590]
In fact `Replace another point with this.` replaces this point with another:

![image](https://user-images.githubusercontent.com/14617699/104807124-72cf8380-57ed-11eb-82e2-b7af395736fd.png)

If you have two favs: `A` (with some description) and `B` and do `Replace another point with this` for `A` its description will be dropped.

OsmAnd Version: 3.8.5

**Comment by vshcherb** [comment]
Replace A point (selected) with B point (this) means that A point should get replaced to location of B point (this selected) and description from A will be displayed. So basically everything from B point (this) will be lost. Tested - works as expected.

It doesn't work with newly created point but the description is correct.
