### ISSUE TITLE
Slow app startup on Android 11

### ISSUE THREAD

**Issue by BellHouse** [osmandapp/OsmAnd#10609]
### Description
Since my Samsung Note 10+ received an update to Android 11 some days ago, the startup of the OsmAnd app is very slow. Too slow (see attached video). The OsmAnd splash screen is first shown for 8 s, then the map seems to load for another 34 s.

### How to reproduce?
1. Kill the running OsmAnd task (via the recent apps list)
2. Startup OsmAnd

### Your Environment
OsmAnd Version: 3.8.4 (OsmAnd+)
Android/iOS version: Android 11 build RP1A.200720.012.N975FXXU6ETLL
Device model: Samsung Galaxy Note 10+ (SM-N975F)

https://user-images.githubusercontent.com/1088897/104905290-6f213580-5982-11eb-885a-6c9014b7ec34.mp4

**Comment by vshcherb** [comment]
Duplicated https://github.com/osmandapp/OsmAnd/issues/10453
