### ISSUE TITLE
Doles Ridge Road Limerick: Use addr:city tag for search index

### ISSUE THREAD

**Issue by blackboxlogic** [osmandapp/OsmAnd#10606]
### Description
It seems elements are indexed for search by inferring the city from surrounding administrative elements, and ignoring the `addr:city` tag.

### How to reproduce?
On the USA-Maine map, try searching for address: ["542 Doles Ridge Road Limerick"](https://www.openstreetmap.org/node/7172276643)
But you don't find it because OsmAnd thinks its city is "Lake Arrowhead", which is a [nearby hamlet](https://www.openstreetmap.org/node/158903930).
Since the node has `addr:city=Limerick` I would expect to be able to find it by searching for that. Also, the element should show "Limerick" as the city when viewing element details.

### Your Environment
OsmAnd Version: 3.8.5 downloaded from fdroid
Android/iOS version: Android 11
Device model: Pixel 3

**Maps used (online or offline):**   
Offline map: USA, Maine (December 31)

**Comment by aceman444** [comment]
Yes, according to the wiki addr:city should override boundaries if present. On the other hand, if addr:city is missing, the boundary relations can be used.

**Comment by riccardopastocchi** [comment]
Sorry, I've been mapping house numbers for years, but I'm new to github.com.

Can you explain to me how this problem brought by blackboxlogic can be solved? And to be able to solve it as soon as possible.

Thank you

**Comment by riccardopastocchi** [comment]
"Add: City" disappears in the search phase if there is a "Place" nearby 
![IMG_2184](https://user-images.githubusercontent.com/78115599/106741509-14433b80-661c-11eb-88a2-4583d5a30585.PNG)
<img width="1972" alt="Schermata 2021-02-03 alle 12 22 10" src="https://user-images.githubusercontent.com/78115599/106741518-160cff00-661c-11eb-9f21-ad7e693c3d53.png">

**Comment by blackboxlogic** [comment]
@riccardopastocchi welcome to github! The OsmAnd developers will need to decide to change this, then update their program and release a new version.
To "make it go faster", we (the users) can give them clear information about the problem and show them how it would be valuable to us for it to be fixed, and be polite and patient. I think they have enough information (clear steps to reproduce and the desired behavior) and they will ask if they need more.
You'll notice that @vshcherb set a "milestone" on this issue, which translates into a guess for when this might get fixed.

**Comment by vshcherb** [comment]
There is a fix coming with these map updates. The issue is only relevant to the maps, so it will be either fix in map generation process or in the maps itself (no update of the program will be needed)

**Comment by riccardopastocchi** [comment]
I don't know if it's about the same problem. 
I found house numbers of addr: city Recanati that osmand makes a mistake with a neighboring city addr: city Potenza Picena 

So get the city wrong in the address 

Ex: 
Recanati, Contrada Vallememoria, 53  
Recanati, Contrada Vallememoria, 57 
Recanati, Contrada Vallememoria, 88 
Recanati, Contrada Chiarino, 44 
Recanati, Contrada Chiarino, 46 
Recanati, Contrada Chiarino, 51 etc

**Comment by vshcherb** [comment]
Please wait February maps

**Comment by blackboxlogic** [comment]
I have retested the original example and it behaves as expected (after the map update). Thank you for your work.

**Comment by blackboxlogic** [comment]
I checked another address nearby and get an unexpected result. Searching OsmAnd (with offline Maine, usa map updated February 11th) for
573 Doles Ridge Road Limerick
Finds the correct address (and shows the correct town name in the search list). But when I unselect then reselect that element on the map, osmand shows the town "Limington" (which is the neighboring town). The [element](https://www.openstreetmap.org/node/7172275466) is tagged with addr:city=Limerick and it is within the boundaries of the [Town of Limerick](https://www.openstreetmap.org/relation/2021418) so I see no reason for it to think it is in Limington.

When the element is selected in OsmAnd, I expect it to show that it is in Limerick, not Limington.

This is definitely less serious than the original issues because searching works well.

**Comment by vshcherb** [comment]
Please create another bug then if you have already Feb maps

**Comment by blackboxlogic** [comment]
Thanks. I've made https://github.com/osmandapp/OsmAnd/issues/10877
