### ISSUE TITLE
[regression] track name is changed to "null.gpx"

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#10621]
### Description
I open My places / tracks, then select a subfolder of rec, then select a track, then with the 3-dots menu "rename".
I don't change anything, even don't touch the track name, only press "save".
Now the track is renamed to "null.gpx".

- one more but minor bug: if I rename the file to "xxx.gpx" a ".gpx" will added, so the new name is "xxx.gpx.gpx".

### Your Environment
OsmAnd Version: OsmAnd~  3.9.0#31329m.apk 2021-01-19
Android version: 10
Device model: samsung tab S5e

**Comment by dmpr0** [comment]
# Review 
- [ ]  "Rename" allows saving the track with an empty text field.
