### ISSUE TITLE
SF Alameda: Street Addresses Not Working

### ISSUE THREAD

**Issue by AnastasiaTiutina** [osmandapp/OsmAnd#10624]
2151 Alameda Ave Alameda Ca 94501
Can't find it in OsmAnd via search 
The same address in OSM https://www.openstreetmap.org/way/465431947#map=19/37.76574/-122.24842
![photo_2021-01-20 14 39 37](https://user-images.githubusercontent.com/72389175/105176028-5b660280-5b2d-11eb-80c6-2301507d280b.jpeg)
![photo_2021-01-20 14 39 30](https://user-images.githubusercontent.com/72389175/105176033-5bfe9900-5b2d-11eb-806e-13fcb7a039ba.jpeg)

**Comment by AnastasiaTiutina** [comment]
Can't find it in OsmAnd via search Wolności 223 Zabrze, Polska.
![photo_2021-01-27 13 04 13](https://user-images.githubusercontent.com/72389175/105983015-c5882580-60a0-11eb-836f-c2151ad84ecc.jpeg)
![photo_2021-01-27 13 04 07](https://user-images.githubusercontent.com/72389175/105983019-c6b95280-60a0-11eb-8638-31dcfea36866.jpeg)


The same address in OSM https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=202822279&class=building

**Comment by vshcherb** [comment]
Please don't combine issues.

**Comment by alisa911** [comment]
It is important to enter the correct address. In this case, you need the city of Alameda and not San Francisco.
