### ISSUE TITLE
Task 'assembleFreedevLegacyFatDebug' not found in project ':OsmAnd'.

### ISSUE THREAD

**Issue by MakiWolf** [osmandapp/OsmAnd#10629]
Since commit [https://github.com/osmandapp/OsmAnd/commit/2efb0ac6af8480531423caa458d71bd2e53eee75]( https://github.com/osmandapp/OsmAnd/commit/2efb0ac6af8480531423caa458d71bd2e53eee75) Task 'assembleFreedevLegacyFatDebug' not found in project ':OsmAnd'.

In Android Studio I solved this when selecting 'nightlyFreeLegacyFatDebug' as build variant, but I am also not able to run this from command line. Also the new names that have changed in OsmAnd/build.gradle should be updated in Documentation [https://osmand.net/help-online#dev-compile-android](https://osmand.net/help-online#dev-compile-android)

**Comment by vshcherb** [comment]
Yes I'm going to update it today! :-)

**Comment by vshcherb** [comment]
Fixed https://docs.osmand.net/en/main@latest/development/build-osmand/how-to-compile-the-android-version

**Comment by chrta** [comment]
Somehow related, https://osmand.net/help-online/faq#dev-environment still contains the obsolete task.
