### ISSUE TITLE
OAuth not working for OSM notes, however works for POI editing

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#10625]
When trying to comment or close a OSM note and then upload it, the following error message appears:

![photo_2021-01-20_14-20-57](https://user-images.githubusercontent.com/1040784/105180580-0c1ed280-5b2b-11eb-9c89-ee727bb1690c.jpg)

The error translates to: "You have not permitted the application access to this facility". Actually this error doesn't come from OsmAnd, it comes from OSM (https://github.com/openstreetmap/openstreetmap-website/blob/master/config/locales/de.yml).

The error appears only when using OAuth. I've tried to remove my OSM account from OsmAnd and to readd OAuth credentials but it doesn't resolve the problem. Switching to OSM login by password works.

Interestingly this problem only exists for OSM notes, not for POI editing. I can upload POI changes without problems using OAuth, but upload for OSM notes fails.

OsmAnd 3.9.1. Nightly has the same problem.

**Comment by vshcherb** [comment]
You can change permissions on https://www.openstreetmap.org/user/xxxxx/oauth_clients and revoke and login again.

On OSM Edit you need to logout. New request was introduced "Edit notes", so I had to update OAuth Application settings

**Comment by scaidermern** [comment]
This works, thanks!
