### ISSUE TITLE
3.9 GPS sensor not activated [Google Play Services are needed]

### ISSUE THREAD

**Issue by Thunichgud** [osmandapp/OsmAnd#10637]
### Your Environment
OsmAnd Version: OSMand+Live 3.9.3
Android/iOS version: CyanogenMod 12.1 (Android 5.1.1)
Device model: Samsung Galaxy S4 GT-I9505

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by dmpr0** [comment]
Hello! Thank you for the feedback.
Are you installed OsmAnd+ 3.9.3 from Google Play? Do you have Google Mobile Services installed?

You can try to test the nightly build https://download.osmand.net/latest-night-build/OsmAnd-default.apk, this is the free version so it can be installed separately from the + version.

**Comment by vshcherb** [comment]
Google Play version very likely won't be working correctly if Google Play Services are not installed. There are many limitation in Google Play right now, so we won't be able to distribute previous version that used GPS without Google Play Services.

Please make sure you have Google Play Services activated or please try nightly build / f-droid / amazon.

**Comment by Thunichgud** [comment]
@vscherb
GPS did not mean Google Play Services !! It did mean Global Positioning System. The changed title and probably your answer is wrong (hope so !).
In the beta version 3.9.2 the GPS did work korrekt. So it should do it also in 3.9.3.
Usually I use my mobile offline. That's one reason why I like OSMand. When from now OSMand works only online with active Google Play Services this will be the beginning of the end of OSMand. Very sorry of that.

**Comment by vshcherb** [comment]
It should work offline as well.

**Comment by scaidermern** [comment]
Here, a Samsung Galaxy S4 GT-I9505 works fine with OsmAnd 3.9.1 and gets a GPX fix. LineageOS 14.1 (with GooglePlay services).

**Comment by Thunichgud** [comment]
Version 3.9.4: Still no GPS (Global Positioning System). App ist unuseable !!
Overview:
3.9.1 beta with GPS
3.9.2 beta with GPS
3.9.3 no GPS
3.9.4 no GPS

**Comment by pebogufi** [comment]
I use the current nighlty build updating nearly every day, of course recording my walk every day, no problems.
Android 8 , Samsung S7
Do you switch on GPS on system level ?

**Comment by scaidermern** [comment]
I updated OsmAnd to version 3.9.4 on my Samsung S4 and it still gets a GPS fix.

**Comment by Thunichgud** [comment]
I tested version 3.9.4 now on an other device:
Samsung Galaxy S6
LineageOS 17.1
Offline without active GooglePlayServices
Result: No GPS
It seems, that OSMand is now an new slave of the google services. As vshcherb wrote 
"Google Play version very likely won't be working correctly if Google Play Services are not installed. There are many limitation in Google Play right now, so we won't be able to distribute previous version that used GPS without Google Play Services."
This is the end of the app free of google services. OSMand turns now to a google slave app with build in google spies. This was a very bad decision of the app developer .

**Comment by vshcherb** [comment]
@Thunichgud use Amazon / Huawei / F-droid store there Google Play Services are not required.

**Comment by sonora** [comment]
I checked on my i9195 (S4 mini), stock ROM, Google Play Services disabled in App Manager: There is no issue at all with our dev builds or nightly builds. 

What kind of google dependency did we recently build into the Play Store release, if any?

**Comment by hvdwolf** [comment]
Google build further integration (if you want to call it that way) into Android with every new release.
I don't think your S4 mini runs anything above Android 6.

**Comment by sonora** [comment]
Yes, but remember: The original issue was opened for Samsung S4 i9505, CyanogenMod 12.1 (Android 5.1.1).

Al I'm saying is that (at least dev builds) have no issue with S4 mini i9195, Stock Android 4.4.2.

Plus: The report sounds like something changed between OsmAnd versions 3.9.2 and 3.9.3, and I am wondering why.

**Comment by pebogufi** [comment]
@Thunichgud Please make a test:
First start navigation in Osmand.
Open system menu, location services
Is location activated ?
Open search method. Which option is activated ?
It might be: 
GPS, WLAN, cell phone or a combination of them.

The terms are may be different, i translated from my phone.

**Comment by Thunichgud** [comment]
@pebogufi:
I made these test multiple times:
- location services are activated
- I tested it with gps only and with GPS in combination with cell phone
No result. GPS is dead in OSMand. 
When I start the app "GPSTest" from inside of OSMand (press on-screen-button "Satellites") this app activates GPS but when I return to OSMand GPS is deactivated again.

**Comment by stephan75** [comment]
Is it sure that the installed osmand app has permission to use location services? IIRC each android app has switches for all used app permissions.

Can you verify in app settings by long pressing the app icon on your phones launcher?

**Comment by sonora** [comment]
Yes, exactly, that sounds like the app has been denied location access by the user ...

**Comment by Thunichgud** [comment]
Yes, OSMand has the permission to use the location services without any limitation - on both devices I tested.

**Comment by Test-53** [comment]
Hey,

I got the same problem as @Thunichgud. First of all, I didn't use OSMAND+ in a while, so I can't say anything about previous versions. I didn't change anything@settings and it worked before.

Pocophone F1 with LineageOS 16.0, Android 9 (Gapps is installed, but only a small package)

When I use the nightly build (from above), the GPS position is recognized.
When I use OSMAND+ (3.9.6&3.9.5) it is not, although my GPS app is showing the right location at the same time.

I guess it is easiest to understand with the following screenshots:

![Screenshot_20210205-134859_OsmAnd~](https://user-images.githubusercontent.com/79015586/107854784-9b639100-6e1e-11eb-90e7-ed5e1c042011.png)
This is the nightly build, which is working fine (OSMAND 3.9.0 from 5.02.2021)


Here the OSAMAND+ version, which can't get a location fix anymore (the gps overlay has the position and OSAMAND+ theoretically has 17/22 satellites, so should have a fix)
![Screenshot_20210205-134847_OsmAnd+](https://user-images.githubusercontent.com/79015586/107854876-39575b80-6e1f-11eb-9883-c247953b94f0.png)

Whenever I click on the 'My position'-button the message 'Position not yet know' is showing up, while the GPS app (and the nightly) get a fix within seconds. All other GPS-related Apps also still work.

If I can provide further information, please say so.

Ps: Before anyone invests time looking up coordinates, Germany, Bonn ;)

**Comment by Test-53** [comment]
I don't think this is Google Services related (see #10903), as all my other GPS apps (all loaded from Playstore) are still working.
I got 'Open Gapps Micro' installed btw.

Here is the reason, why probably not Playstore related:
- 'Waze' works fine, as before
- just tried 'Google maps app', works
- 'GPS Status' works

I'd assume that those apps would (most probable) also stop working, if this would be Playstore related (or at least one).

- All the problems occur on custom roms (formerly CyanogenMod & now LineageOS); How about other CustomRoms? (sry, can't test)
- Nightly build works fine (3.9.0 from 05.02.2021), updated versions not

So, a very wild guess, is that some custom roms/LineageOS somehow handel GPS a bit differently, then stock android. Under normal circumstances this is no problem (as all other GPS apps still work), but something was changed in OSMAND+, which now results in our problem and seems to not affect stock users.

As mentioned before, I gladly provide information, but I am, unfortunately, not good at programming.

**Comment by Test-53** [comment]
Update:
Just tested it on my old phone:
OnePlus3, LinageOS16, Android 9, Gapps Micro (as well)

OSMAND, from Playstore, works fine on this device. I guess I was wrong and it's not realated to our custom roms

**Comment by ferpg81** [comment]
Hi,

I've just arrived to this page, because I detected the same problem yesterday. I had purchase Osmand+ on Google Play Store several years ago, and I usually check for updates. Now I have version 3.9.6, and had this "Google Play Services" problem. I don't remember the previous release I had before current one, but that works fine and let's consider it fairly current (maybe 1-2 months older). With Play Store Osmand+ version 3.9.6, having GPS activated, when "Google Play Services" is stopped/disabled, Osmand+ doesn't get GPS info; when turn on "Google Play Services", Osmand+ gets correctly GPS info and works fine.

The nightly build https://download.osmand.net/latest-night-build/OsmAnd-android-full.apk (v.4.0.0#31563m) doesn't has the problem and works fine: GPS activated, Google Play Services disabled, and Osmand gets GPS position OK.

There must be something bad with Play Store build...

Terminal/SO info: Nokia 7 plus, Android 10 updated official, no root.

Regards.

**Comment by scaidermern** [comment]
> With Play Store Osmand+ version 3.9.6, having GPS activated, when "Google Play Services" is stopped/disabled, Osmand+ doesn't get GPS info; when turn on "Google Play Services", Osmand+ gets correctly GPS info and works fine.

If I understood @vshcherb correctly in https://github.com/osmandapp/OsmAnd/issues/10637#issuecomment-765394116 this is the expected behavior, unfortunately.

**Comment by ferpg81** [comment]
> 
> 
> > With Play Store Osmand+ version 3.9.6, having GPS activated, when "Google Play Services" is stopped/disabled, Osmand+ doesn't get GPS info; when turn on "Google Play Services", Osmand+ gets correctly GPS info and works fine.
> 
> If I understood @vshcherb correctly in [#10637 (comment)](https://github.com/osmandapp/OsmAnd/issues/10637#issuecomment-765394116) this is the expected behavior, unfortunately.

Hi, then I understand that it is due to a new limitation for fulfil Google Play requirements... omg... Thanks a lot for the point. I'll keep F-Droid build for now.

Regards.

**Comment by l3afblow3r** [comment]
I'm using OsmAnd 3.6.3 without any Google Services (basically a de-googled phone) and the GPS is working fine.
I am running Location on GPS-Only.

Maybe try that until its fixed?

**Comment by Thunichgud** [comment]
The version 3.6.3 didn't have this problem. The problem came with version 3.9.3 and later. It is not solved.
     Am Freitag, 19. März 2021, 21:04:43 MEZ hat l3afblow3r ***@***.***> Folgendes geschrieben:  
 
 


I'm using OsmAnd 3.6.3 without any Google Services (basically a de-googled phone) and the GPS is working fine.
I am running Location on GPS-Only.

Maybe try that until its fixed?

**Comment by ska-osm2** [comment]
I run osmand+ v3.9.10 (paid Play Store version) on LineageOS 15.1 and I'm facing the same problem.

When I start osmand, the "location" indicator on the right side of the notification area turns on, there is an icon on the left side of the notification area indicating track recording.
osmand does not get no GPS fix.

Starting GPS status or gpstest from osmand works, both get a fix easily, on return osmand says "6/24" in GPS info field, but position is unknown still. If you tap on "center on position", A balloon pops up, telling "unknown" and a-gps downloaded (this minute).

osmand is noted in the list of apps that queried the location service in the near past.

I also noticed that both GPStest and GPS status, but also Locus Map cause to open another icon on the left side of the notification area , in addition to the "location active" icon on the right side.
That icon indicates "gps status" and displays the currently known satelites and fixes and some other infos.

I tried installing the nigthly build from the link mentioned above, the install process starts, stalls a bit, but then simply say "failed".

**Comment by scaidermern** [comment]
> I tried installing the nigthly build from the link mentioned above, the install process starts, stalls a bit, but then simply say "failed".

Try https://download.osmand.net/latest-night-build/OsmAnd-default.apk instead. You can't have both OsmAnd+ and the full nightly version installed at the same time as far as I know.

**Comment by vshcherb** [comment]
This issue is getting too hot without actually solving original issue, it starts looking more like a discussion. Cause there is no plan to fix anything here, it will be closed, feel free to create a spinoff discussion if it's needed - https://github.com/osmandapp/OsmAnd/discussions
