### ISSUE TITLE
Inconsistent appearance of track analysis screens

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#10636]
It may still be work in progress, but just to be sure:

When in recent builds you on the map tap on a track, a context menu opens, there you can select `Open Track`. The screen which opens contains a new `Options` button in the lower right corner, with the superset of all options available.

1.  But when you go via `My Place / Tracks`, and tap a track there, you end up on a screen which is essentially identical, but is missing the `Options` button.

1.  The actual screen in question in both cases has a 3-dots overflow menu (with just options `Edit` and `Delete`), and a `Split interval` button, and an `Analyze on map` button, all of which should be obsolete as they are part of the new `Options` button also?

1.  The context menu when tapping on a track on the map offers the option `Open Track`, which is fine, but also `Analyze on map`, which is a duplication as it is also part of the new  `Options` button?

**Comment by vshcherb** [comment]
Current My Place / Tracks / Track Overview is planned to be deleted next week or week after next. 

Main focus will be on the "context menu screen".
