### ISSUE TITLE
Routing totally wrong in one direction

### ISSUE THREAD

**Issue by RinkBies** [osmandapp/OsmAnd#10642]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, OpenRouteService, OSRM, etc.)

### Routing Profile

bike
### Start and end points
Start: Netherlands, Nootdorp, Dwarskade 26
End: Netherlands, Nootdorp, Dwarskade 2

### Actual and expected routes

![image](https://user-images.githubusercontent.com/77327231/105522478-960e9d00-5cdd-11eb-9f00-a2857d23cae0.png)

Expected was a straight line between the start point and the endpoint.
Actual is marked a yellow...

If you switch the start and end points, the route is correct.

If move the start point a little bit, the route is even going through a house...
![image](https://user-images.githubusercontent.com/77327231/105524030-6791c180-5cdf-11eb-9347-297fc7803442.png)

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 3.8.4 (the latest version in Google Play Store)
## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

OsmAnd~ 3.9.0#31357m

</code></pre>

**Device and Android/iOS version:**
Android 10
**Maps used (online or offline):**
Offline

- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**

**Comment by alisa911** [comment]
Fixed incorrect road restriction in OSM. This will work in the next maps.
