### ISSUE TITLE
Doesn't upload all the tags while uploading a POI

### ISSUE THREAD

**Issue by letypequividelespoubelles** [osmandapp/OsmAnd#10646]
### Description
I try to modify a POI (change name, add email, phone, address and so on), but when I upload it it doesn't change, see history of the POI [here](https://www.openstreetmap.org/node/7108798623/history). 

Below screenshot of the POI modification in OsmAnd.
![photo_2021-01-23_16-29-07](https://user-images.githubusercontent.com/54240434/105606191-2e695800-5d98-11eb-89a2-410b661a47b3.jpg)
![photo_2021-01-23_16-29-15](https://user-images.githubusercontent.com/54240434/105606192-2f01ee80-5d98-11eb-906c-0417780b4702.jpg)

### How to reproduce?
Try to modify this POI, it doesn't work. 

### Your Environment
OsmAnd Version: 3.8.5 from F-Droid
Android version: 9 
Device model: BV 9500 pro 

### Maps used (online or offline)
Haute Savoie map (last dl 01/01/2021) +  live update of this map.

**Comment by scaidermern** [comment]
I also have this from time to time. Sometimes OsmAnd uploads only some changed tags but not all of them.

Could be related to #9093.

**Comment by letypequividelespoubelles** [comment]
>Could be related to #9093. 

In my case, it happened this time even while uploading directly the modified POI (I mean, without modify the modification). I have no idea if it's the first time this happens for me.

**Comment by vshcherb** [comment]
Merged to #9093
