### ISSUE TITLE
[regression] no more nightly.apk in https://download.osmand.net/latest-night-build/

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#10645]
### Description
The OsmAnd~ nightly.apk is no more in the directory
https://download.osmand.net/latest-night-build/
for download.

**Comment by vshcherb** [comment]
Docs updated https://docs.osmand.net/en/main@latest/development/build-osmand/how-to-compile-the-android-version#gradle-tasks--flavors

**Comment by pebogufi** [comment]
@vshcherb 
The "old" nightly osmand-nightly.apk was labeled **plus** version (net.osmand.plus) 
whereas the "new" nighlty OsmAnd-default.apk is labeled  **NON-Plus** version (net.osmand.dev). 
So new nighlty is a restricted version.

But after installing the OsmAnd-default.apk I do NOT see restrictions in numbers of maps to download or live.
Could you please be so kind to give a short explanation, what the change of nightly build means in restrictions for testing users ?
---
I use osmand since 2013, purchased osmand+.
Since years I don't use releases but test nightly on every trip I ever make. 
So I am very interested in a  FULL featured version, not as release but as nightly build for "real live testing" whereever I move by feet, bike, car, caravan.
How to get that ?
Kind regards Peter

**Comment by vshcherb** [comment]
We've "officially" published only default build as nightly (link present on the website), so it's still available under this name. xhttps://download.osmand.net/latest-night-build/OsmAnd-default.apk
There are different flavors in documentation explained will be used for different purpose. Probably you will find here the build  you need https://download.osmand.net/latest-night-build/ but it could be a subject to change in future cause it's internals.

It's possible to use 2 versions (nightly free and paid version) and shared maps folder, so it's possible to update maps via installed paid app.
