### ISSUE TITLE
Melbourne: Wrong city for address

### ISSUE THREAD

**Issue by AnastasiaTiutina** [osmandapp/OsmAnd#10657]
Australia
Shelford Court, Melbourne
Location: geo:-37.968597,145.07198?z=15
https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=28738924&class=highway 
Should be in Cheltenham

Grange Road, Sandringham
Location: geo:-37.97014,145.08614?z=18
https://nominatim.openstreetmap.org/ui/details.html?osmtype=N&osmid=3614820693&class=building 
Should be in Cheltenham

**Comment by alisa911** [comment]
The bug will be fixed with February maps.
