### ISSUE TITLE
Nonvisible snowmobile trails for night mode

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#10663]
### Description

Snowmobile trails are not visible in snowmobile map style :

![image](https://user-images.githubusercontent.com/44466116/105755384-48ec2e80-5f5c-11eb-84a6-b55acbe2a43b.png)
![image](https://user-images.githubusercontent.com/44466116/105755400-4db0e280-5f5c-11eb-8acb-85dda07787d5.png)

### Your Environment
OsmAnd Version: 3.9
Android/iOS version: Android
Device model: Samsung s10e

**Comment by xmd5a2** [comment]
![Screenshot_2021-01-27_18-14-58](https://user-images.githubusercontent.com/5829014/106011627-b36fac80-60cb-11eb-95f3-d00ff33a1524.png)
Fixed
