### ISSUE TITLE
Allée des Aigrettes: Street Addresses Not Working

### ISSUE THREAD

**Issue by AnastasiaTiutina** [osmandapp/OsmAnd#10677]
Allée des Aigrettes Croissy-Beaubourg France
Can't find it in OsmAnd via search
The same address in OSM https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=290266098&class=highway
It was moved to  Lognes by mistake
![photo_2021-01-27 14 00 22](https://user-images.githubusercontent.com/72389175/105992021-3b928980-60ad-11eb-8d38-27f70b8aeec3.jpeg)
![photo_2021-01-27 13 47 22](https://user-images.githubusercontent.com/72389175/105992040-451bf180-60ad-11eb-8465-27adaf27c4c4.jpeg)

**Comment by alisa911** [comment]
The bug will be fixed with February maps.
