### ISSUE TITLE
Wolności 223 Zabrze: Street Addresses Not Working

### ISSUE THREAD

**Issue by AnastasiaTiutina** [osmandapp/OsmAnd#10679]
Can't find it in OsmAnd via search Wolności 223 Zabrze, Polska.
The same address in OSM https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=202822279&class=building

![photo_2021-01-27 13 04 13](https://user-images.githubusercontent.com/72389175/105993297-e48db400-60ae-11eb-9e17-203be8951a5a.jpeg)
![photo_2021-01-27 13 04 07](https://user-images.githubusercontent.com/72389175/105993323-eeafb280-60ae-11eb-9d03-757ee9cc71f2.jpeg)

**Comment by mp13mp13** [comment]
Please check your attention at the address Wolności 223. There are more missing addresses in the index.

**Comment by alisa911** [comment]
The bug will be fixed with February maps.
