### ISSUE TITLE
Potenza Picena Via Galileo Galilei: Street Addresses Not Working

### ISSUE THREAD

**Issue by AnastasiaTiutina** [osmandapp/OsmAnd#10698]
Potenza Picena Via Galileo Galilei
Can't find it in OsmAnd via search
The same address in OSM https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=895189013&class=highway
![photo_2021-01-28 17 13 18](https://user-images.githubusercontent.com/72389175/106158163-23456c00-618c-11eb-80ba-61dccaa8abda.jpeg)

![photo_2021-01-28 17 13 11](https://user-images.githubusercontent.com/72389175/106158166-24769900-618c-11eb-961d-86b0abbaed47.jpeg)

**Comment by alisa911** [comment]
The bug will be fixed with February maps.
