### ISSUE TITLE
Beim Ruhacker 12, Ziegelerden 96317 Kronach, Germany: Bug with Address

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#10699]
### Description
coordinates:    

50.2276  11.2974428

Beim Ruhacker 12, Ziegelerden 96317 Kronach, Germany

Address in OSM:
https://www.openstreetmap.org/way/377218442
![image](https://user-images.githubusercontent.com/44466116/106160310-c00d0700-6196-11eb-94a0-bcf7f3a5e60d.png)

But in OsmAnd :
We see "Kestel" in OsmAnd, but  it is Kronach 

![image](https://user-images.githubusercontent.com/44466116/106160379-d2874080-6196-11eb-8468-ab6f76d814ea.png)

### Your Environment
OsmAnd Version: 3.8.4
Android/iOS version: Android
Device model: Samsung 10e

**Maps used (online or offline):**   
1 January

**Comment by alisa911** [comment]
The bug will be fixed with February maps.
