### ISSUE TITLE
Simplify the insertion of geographic coordinates

### ISSUE THREAD

**Issue by riccardopastocchi** [osmandapp/OsmAnd#10693]
It could be easier to enter geographic coordinates to find the target. Create an entry window to speed up the operation of entering the coordinates, avoiding to write (degrees °) (first ') (seconds'')

See photos
(https://ibb.co/4P7FKny)
[(https://ibb.co/4P7FKny)](url)
..for both android and ios 

![coord](https://user-images.githubusercontent.com/78115599/106123660-81595b80-615a-11eb-916f-6ff3c41f4839.jpg)

**Comment by vshcherb** [comment]
Please use Markers -> Options -> Coordinate Input or similar via GPX -> ... 
![image](https://user-images.githubusercontent.com/1042025/106129067-38a4a100-6160-11eb-95f2-41d466372320.png)

**Comment by riccardopastocchi** [comment]
for ios?

**Comment by vshcherb** [comment]
We have that feature request I guess, it is on our roadmap for 2021. I closed it here cause we have a separate issue tracker for ios https://github.com/osmandapp/osmand-ios.
