### ISSUE TITLE
 Streets from Maisons-Alfort commune were moved to  Saint-Maurice

### ISSUE THREAD

**Issue by AnastasiaTiutina** [osmandapp/OsmAnd#10708]
Streets from Maisons-Alfort commune were moved to  Saint-Maurice
Maisons-Alfort rue du 14 Juillet
Can't find it in OsmAnd via search
The same address in OSM https://www.openstreetmap.org/search?query=Maisons-Alfort%20rue%20du%2014%20Juillet#map=18/48.81263/2.45112
![photo_2021-01-29 14 27 19](https://user-images.githubusercontent.com/72389175/106275190-1da85e80-623e-11eb-86ca-4b72c86d1e9e.jpeg)

 Maisons-Alfort avenue Gambetta
https://www.openstreetmap.org/way/546138584#map=17/48.81008/2.43814

![photo_2021-01-29 14 45 03](https://user-images.githubusercontent.com/72389175/106276675-97414c00-6240-11eb-8fd9-b287dc1b04c3.jpeg)

 Maisons-Alfort rue du 8 Mai 1945
https://www.openstreetmap.org/way/27429426#map=14/48.8135/2.4490

![photo_2021-01-29 14 47 47](https://user-images.githubusercontent.com/72389175/106276941-f99a4c80-6240-11eb-8228-2c6eb03d0e76.jpeg)

 Maisons-Alfort rue Robert Ferrer
https://www.openstreetmap.org/way/29177300#map=15/48.8050/2.4641

![photo_2021-01-29 14 49 36](https://user-images.githubusercontent.com/72389175/106277123-39f9ca80-6241-11eb-92c5-3de8b26d6779.jpeg)

 Maisons-Alfort rue des Pinsons
![photo_2021-01-29 14 52 14](https://user-images.githubusercontent.com/72389175/106277347-9826ad80-6241-11eb-8702-6f43ad451b90.jpeg)

 Maisons-Alfort avenue du Maréchal Foch
 Maisons-Alfort rue Roger François
 Maisons-Alfort rue Guy Môquet

**Comment by Marc959** [comment]
This bug is the same than the #10558

**Comment by vshcherb** [comment]
We have around 7 bugs lately in progress related to it. We're going either fix them or update documentation if they are related to OSM

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/10558
https://github.com/osmandapp/OsmAnd/issues/10698
https://github.com/osmandapp/OsmAnd/issues/10699
https://github.com/osmandapp/OsmAnd/issues/10677
https://github.com/osmandapp/OsmAnd/issues/10702
https://github.com/osmandapp/OsmAnd/issues/10657

**Comment by letypequividelespoubelles** [comment]
I'm not sure, but maybe #10559 and #10036 are linked to thoses issues.
