### ISSUE TITLE
OsmAnd - Myrtle Beach South Carolina : Street Addresses not searchable in OsmAnd, present in OSM

### ISSUE THREAD

**Issue by erice1984** [osmandapp/OsmAnd#10702]
Street addresses are not found in search results in OsmAnd.  They are found in OSM.

I have added probably 100 buildings, included complete addresses.  Addresses are viewable in OsmAnd but search never finds or locates the buildings searched.  It's bizarre OSM finds them no problem.

![OsmAnd](https://user-images.githubusercontent.com/1829302/106217407-2c8e0300-61a3-11eb-9041-6e94515ba91f.jpg)
![OSM](https://user-images.githubusercontent.com/1829302/106217459-47f90e00-61a3-11eb-9bd4-750c5644c2b5.jpg)

**Comment by sonora** [comment]
Please note that OsmAnd by default performs an offline search in its locally downloaded maps on your device.

It looks like the OSM data you refer to has only been created in OSM about 10 days ago, right? So you would have to wait for OsmAnd's February maps to be published, and after downloading (updating) the SC one it should work.

**Comment by vshcherb** [comment]
Yes, address data is not part of live updates.

**Comment by erice1984** [comment]
Thank you.  I didn't find any documentation that stated this.

**Comment by alisa911** [comment]
The bug will be fixed with February maps.
