### ISSUE TITLE
Redirect 'Configure map / Tracks'

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#10704]
I've suggested this before somewhere: It is time to redirect tapping 'Configure map / Tracks' to the very screen you end up when tapping 'Menu button / MyPlaces / Tracks'.

The screen we currently use for 'Configure map / Tracks' is very unusable if you have more than just a handful of tracks or a folder substructure, it should be retired.

This would also increase the discoverability of our much more powerful 'MyPlaces / Tracks' screen, which many users have never seen.

**Comment by vshcherb** [comment]
It's still slightly different. 
- Configure Map screen you can change appearance for ALL visible tracks where on My Places you can't. For other features of course My Places is much better (Search etc...).  
-  Another issue needs to be addressed that Configure Map screens have small window of map, so you can quickly return back to the map! It's much quicker than clicking Back button.

I think we're going to slightly improve  My Places in 4.0 and meantime replace that screen as well.

**Comment by snouup** [comment]
I agree the screens should be consolidated. The first time I discovered the tracks dialog in the profile settings, I expected it would allow me to turn tracks on/off for that specific profile, but it doesn't work that way - the change will affect all profiles.
On the other hand, the track dialog in profiles allows me to turn tracks on/off with a single tap on a checkbox, which is quite convenient.

**Comment by vshcherb** [comment]
This issue is merged to https://github.com/osmandapp/OsmAnd/issues/11974 cause it will be redesigned to align with My Places. The refactoring is quite big and it will go through 2 releases: 4.3 and 4.4
