### ISSUE TITLE
[FR][Favorites]: assign colors to POIs, not just folders

### ISSUE THREAD

**Issue by PetbkA** [osmandapp/OsmAnd#10715]
# 🚀 feature request

### Description
When I'm planning my trip, I'm:
1. Creating folder of a city or place I want to visit;
2. Setting POIs and assigning the color to each of them depending on it's type (e.g. museum, park or just some statue that I want to glance at). This helps in terms of time management and understanding if the city or place is worth to visit at all,

But in OsmAnd I can assign color only to the whole place, i.e. folder, and not the POIs inside it.

### Describe the solution you'd like
Allow to assign color to each POI, not just folder

**Comment by pebogufi** [comment]
First: if you want to talk about favourites, don't tell them "POI", that is a different thing, that might lead to misinterpretation.
(2) should work, if you mean favourites and your app is not too old.
Please tell us your app version, when talking about problems.

**Comment by PetbkA** [comment]
> First: if you want to talk about favourites, don't tell them "POI", that is a different thing, that might lead to misinterpretation.

Thanks for the advice, I just thought that it's better than using the same word for favorites section in the menu and object inside folder in favorites.

> should work, if you mean favourites and your app is not too old.

Yes, indeed. I just thought that I can change Favorite's color in Favorites section, but there was no such option, and long-tapping Favorite did nothing. It turned out that I have to choose object on the map and then press "Edit Favorite". So the functionalilty is really there already, although it would be nice to edit Favorite's settings right in Favorites section.

> Please tell us your app version, when talking about problems.

3.8.4
