### ISSUE TITLE
Navigation broken for destinations further than ~60 kilometers

### ISSUE THREAD

**Issue by antanicus** [osmandapp/OsmAnd#10722]
### Description
Plotting a route to any location further than approx. 60km freezes the routing process, regardless of the destination (eg. small village or large city). 

### How to reproduce?
1. Install the Italy/Latium map
2. Pick "Anguillara Sabazia" as the starting point
3. Pick "Montefiascone" as the destination

Outcome:
The navigation process hangs and no route is plotted

Expected outcome:
The route is plotted correctly

### Your Environment
OsmAnd Version: 3.8.5 (f-droid)
Android/iOS version: LineageOS 16.0
Device model: Samsung Galaxy A5 2017

**Maps used (online or offline):**   
Map version: offline
Map name: Italy_lazio_europe.obf
Map date (as extrapolated from the file manager): 01/01/21

Other installed maps:
World_basemap_mini.obf
World_basemap.obf

**Screenshots**
![1_broken_route](https://user-images.githubusercontent.com/20061793/106384479-54f84600-63cb-11eb-871d-0af6ad932bca.png)
![2_successful_route](https://user-images.githubusercontent.com/20061793/106384480-56c20980-63cb-11eb-9b61-b7c25475c50f.png)

**Comment by alisa911** [comment]
Update to the latest version OsmAnd.
