### ISSUE TITLE
All Travel guides points are red colored

### ISSUE THREAD

**Issue by ArjanOnwezen** [osmandapp/OsmAnd#10723]
All Travel guides points are red colored on the map. Before there was a distinction between the different type, like transport, sightseeing, place to stay, etc..
Currently they all have the same (red) color.

Repreduce:
- Go to Travel guides
- Select any article with gpx point, e.g. Yogyakarta
- Click on points

Version: Osmand~ 3.9.0#31428m

As a bonus it would be good to be able to select the color per poi type (transport, sightseeing, place to stay, etc..).

**Comment by vshcherb** [comment]
Do you use new travel.obf file?

**Comment by ArjanOnwezen** [comment]
Yes, I'm using the World_wikivoyage.travel.obf file, with date of 2021-01-21. Just downloaded it again.

**Comment by vshcherb** [comment]
Ok, will check.

**Comment by ArjanOnwezen** [comment]
Thanks the new version fixed it.
