### ISSUE TITLE
Offline sqlite raster maps (RMaps) don't show up in the beginning

### ISSUE THREAD

**Issue by skitourenguru** [osmandapp/OsmAnd#10729]
### Description
I wrote several tools able to create **Offline sqlite raster maps (RMaps)**. The resulting maps work perfectly on OsmAnd. Nevertheless I have always a problem to **switch** to the map:

1. I make sure OsmAnd shows to a location that is covered by my **Offline sqlite raster map**
2. I change the MapSource to my **Offline sqlite raster map**
3. The map usually doesn't show up in the beginning. Its blank.

In order to make sure the map shows up I do some of the following

1. Zooming in and out for a while
2. Switching back to **Vector maps** and then forward to my **Offline sqlite raster map**
3. Closing and re-opening the app

Some-when suddenly the map appears. Sometimes I do the above steps for half an hour. Once it shows up, it perfectly works, even if I switch back to **Vector Map** and forward to my **Offline sqlite raster map**.

Since long time I try to find out a reproducible procedure that makes sure the map **immediately** displays.

Some remarks:
- I test on Android. As far as I know the problem is not on iPhone (not sure)
- The  Offline sqlite raster maps (RMaps) is 100% correct. I test it as well with other apps like GuruMaps, LocusMap and OruxMaps.
- I suppose you know this problem

**Have you an idea about a reproducible procedure that makes sure the map immediately shows up?**

### Your Environment
OsmAnd Version: 3.8.4 (Android)
Android: 11
Device model: Google Pixel 2

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
The files are big (8 GByte) and can be shared for legal reasons only from 1. March 2021 on (Swisstopo)

**Comment by vshcherb** [comment]
OsmAnd supports only 1 format of sqlite files - https://docs.osmand.net/en/main@latest/development/osmand-file-formats/osmand-sqlite. So they are probably incompatible with this format and somehow needs to be changed.

**Comment by skitourenguru** [comment]
I can add a link to the map on 1. March... 
Do you build up an internal index, which would take its time to be created for big files (8 GGybte)??? Side by side to the sqlite file I see two other files with the same name but other extensions.

**Comment by skitourenguru** [comment]
It seems it only takes time (some minutes) for such big files till some kind of recognizing of the map is successfully executed.

**Comment by skitourenguru** [comment]
Just wait. It takes time (some minutes) for such big files till some kind of recognizing of the map is successfully executed.

**Comment by skitourenguru** [comment]
From this link you can download the 8GByte file containing all topographic maps of Swisstopo (1:25K, 1:50K, 1:100K, 1:200K, 1:1Mio):
https://drive.infomaniak.com/app/share/265437/7badda03-54a9-4270-a04f-0537f7232f19/14/download

There is more doc (in german) here:
https://info.skitourenguru.ch/index.php/swisstopo4guru

**Comment by Keilomatico** [comment]
I was having the same issue on OsmAnd 5.2.13 on a Motorola Edge 60 Neo running Android 15 when copying the map directly to the OsmAnd folder. Even after 15min nothing happened.
The fix was the following: Simply copy the .sqlite file into the download folder, then navigate to it on the phone with the file explorer and tap to open - OsmAnd automatically opens up and correctly imports and indexes the map (which takes a few minutes, depending on the size). Perfect!
