### ISSUE TITLE
Street from Lyon was moved to Villeurbanne

### ISSUE THREAD

**Issue by AnastasiaTiutina** [osmandapp/OsmAnd#10730]
Place Louise, Lyon, France
OSM: hhttps://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=117882881&class=highway

![Screenshot_20210129-141444_OsmAnd](https://user-images.githubusercontent.com/72389175/106486655-8996fb00-64ba-11eb-8643-2c35d9ced6cd.jpg)

**Comment by alisa911** [comment]
The bug will be fixed with February maps.
