### ISSUE TITLE
OsmAnd routing takes unnecessary turns or longer path

### ISSUE THREAD

**Issue by thilokab** [osmandapp/OsmAnd#10736]
We are using OsmAnd version 3.5.5 (Released: 28/11/2019) in Australia and it is prompting users to take unnecessary left turns on our Android devices. Below are examples for Melbourne based locations. Could you please review the below and let us know if there are any settings that we could tweak or if there are later versions that we need to use. Our users have a great liking for the product and we would like to continue use that product and are hoping that the below can be addressed/fixed. 
Thanks

**Example 01 :** 
When the driver is going in a straight way and close to an intersection, it is asking to turn left and take a U turn and join the road again to go straight. See below an example:

![OSM Testing B](https://user-images.githubusercontent.com/78388857/106538710-c6153600-6550-11eb-8371-b179c0b87a21.jpg)

**Example 02 :**  
When there is an instance when a left turn can be taken, the navigation is suggesting a longer way to connect to come back to the same road that we would have taken with the first left turn. See below an example:

![OSM Testing A](https://user-images.githubusercontent.com/78388857/106539312-dbd72b00-6551-11eb-9cb8-dbf1b999bf45.jpg)

**Comment by scaidermern** [comment]
First example seems to be this one: https://www.openstreetmap.org/directions?engine=graphhopper_car&route=-27.43102%2C153.09058%3B-27.43231%2C153.08634

Could be caused by the infamous traffic signal penalty.

**Comment by vshcherb** [comment]
Well we did quite a lot of changes since 3.5! So this is infamous issue could be gone :-)  We will retest on latest & greatest build.

**Comment by Panda991** [comment]
Thanks @scaidermern and @vshcherb for your comments. We have installed the latest release for OsmAnd. We will keep in touch and get back to you if we still find issues related to this in future too.

**Comment by alisa911** [comment]
Both cases now work correctly in the latest version OsmAnd.

**Comment by TBandaraCapital** [comment]
Thanks for all your responses and we have updated the version of the OsmAnd (3.9). We could successfully able to test for above instances and  it is working satisfactory. 

But we found another issue that prompting in our Android devices to take unnecessary U turn directions. Below example is from Queensland. We highly appreciate if you could review the below image and give us some feedback to improve/overcome this issue please.

Thanks!

![image](https://user-images.githubusercontent.com/78388857/107909855-40ac6f80-6fad-11eb-910b-e02a77dc3570.png)

**Comment by alisa911** [comment]
This u-turn is necessary, because a right turn is prohibited (the right road has tag "oneway" for the opposite traffic).

**Comment by thilokab** [comment]
@alisa911 Thanks for your response. But it is not prohibited in that intersection to take right turn. I have attached a screenshot of the satellite view of the Google maps.  

We appreciate your support to overcome these incidents. Thanks

<img width="563" alt="2021-02-16 13_02_29-Chemist Warehouse Mt Gravatt - Google Maps and 8 more pages - Work - Microsoft​ " src="https://user-images.githubusercontent.com/78388857/108010368-cf29fb00-7058-11eb-92d0-ad7cb08cddd3.png">

**Comment by alisa911** [comment]
Yes you are right. Having studied the problem in detail, it appears that your route has two traffic lights, which have a high penalty in Osmand. By default, the application chooses the route with least time to arrive to destination. In this case, a path with an u-turn is faster than driving through two traffic lights.

**Comment by scaidermern** [comment]
> In this case, a path with an u-turn is faster than driving through two traffic lights.

Possibly faster but also way more dangerous. OsmAnd shouldn't suggest such a route just to avoid _one_ traffic light. The route isn't faster if you are dead afterwards.

**Comment by vshcherb** [comment]
We also can create tests for these bugs : https://github.com/osmandapp/OsmAnd/issues/10789

**Comment by thilokab** [comment]
Thanks all. Could we please have an update once this is addressed. Thanks

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/pull/10929
https://github.com/osmandapp/OsmAnd-resources/pull/672
https://github.com/osmandapp/OsmAnd-core/pull/207

**Comment by thilokab** [comment]
@alisa911 Thank you!

How can we get this update?
