### ISSUE TITLE
App Crash Initializer

### ISSUE THREAD

**Issue by juniorandrade123** [osmandapp/OsmAnd#10748]
Personal Hello.
I am new to osmandapp.
When I compile the app at android studio, I get this problem.

Can anyone help me?

![image](https://user-images.githubusercontent.com/16749591/106638957-3036d680-6563-11eb-808c-55445304ea32.png)

**Comment by vshcherb** [comment]
Probably you didn't follow this https://docs.osmand.net/en/main@latest/development/build-osmand/setup-the-dev-environment
