### ISSUE TITLE
:OsmAnd-java:test

### ISSUE THREAD

**Issue by juniorandrade123** [osmandapp/OsmAnd#10742]
### Description

Hello Sir. I am new using OsmAnd. When I am compiling on Android I am getting this problem when I run the unit test.
Could you help me?

**Caused by: java.io.FileNotFoundException at SearchUICoreGenericTest.java:24**

### How to reproduce?
Run project on android

**Comment by njohnston** [comment]
I had the same problem, specifically with this code:

```java
  String fileName = "/test_turn_lanes.json";
  Reader reader = new InputStreamReader(RouteResultPreparationTest.class.getResourceAsStream(fileName));
```

The path in `fileName` looks odd to me, I wonder if this code normally runs inside a Docker container where a directory on the host is exposed as / inside the container.

You can exclude this task by running `gradlew` with `-x :OsmAnd-java:test`.

**Comment by juniorandrade123** [comment]
Thanks for your help.
I executed this command, but it still executes the test.
Now the test returns me this problem.

![bug](https://user-images.githubusercontent.com/16749591/106616990-ef33c780-654c-11eb-83a4-593ada999573.PNG)

**Comment by juniorandrade123** [comment]
More about error

![image](https://user-images.githubusercontent.com/16749591/106617397-5baec680-654d-11eb-9e42-f5c70f918df5.png)

**Comment by njohnston** [comment]
That seems strange, try double checking that Gradle is definitely excluding that task.

**Comment by juniorandrade123** [comment]
Message return after execute command.

![image](https://user-images.githubusercontent.com/16749591/106618219-fd361800-654d-11eb-87ce-8354b0809032.png)

**Comment by njohnston** [comment]
It looks like you haven't actually specified a task to run, so Gradle just runs its own internal help task.

Try running:

```
./gradlew -x :OsmAnd-java:test assembleNightlyFreeLegacyFatDebug
```

**Comment by juniorandrade123** [comment]
Thanks Mister
Working now
