### ISSUE TITLE
Discoverability of the new "Tracks /Overview" card

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#10746]
I noticed that almost no user realizes that after tapping on a track on the map and after eventually ending up on this  new screen

![Untitled](https://user-images.githubusercontent.com/845735/106620193-9de9ff00-6571-11eb-96a7-4e0d52ef1f87.png)

you can actually expand the 'Overview' by pulling up the upper part, and then end up on a dialog with lots of cool action buttons (which again can be tapped to produce e.g. graphical analysis, etc.)

A few suggestions come to mind to enhance the situation:

- We could always show the screen pulled up "a little", so that the top of the first button row is always visible indicating that the dialog can be expanded by pulling up
- We can give the statistic (number) tiles (Distance, Ascent, etc.)) a more button-like look, indicating that they are tappable (much like we do for the action buttons below)
- We could change the behavior of the bottom row of buttons (Overview, Track, Points, Options) to the effect that
  - tapping them once changes to the corresponding tap (we have that), 
  - then tapping the same again would expand the tab to the top,
  - and then tapping again would collapse the tab again. (Today it is quite tricky to collapse an expanded tab again, as not all sections seem to be responsive to a swipe-down gesture.)

**Comment by vshcherb** [comment]
It should be hot-fixed in 3.9

**Comment by vshcherb** [comment]
Temporarily fixed to intermediate middle state .

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/pull/10753/files

**Comment by sonora** [comment]
Since you closed this already, how about the other suggestions (gray background of the statistics buttons and toggle up/down behavior of the bottom row buttons)?

**Comment by vshcherb** [comment]
hm... that's discussible, so will wait till 4.0. If there request will be popular we could come back in 3-4 weeks with a new issue. Now it's time to try current UI
