### ISSUE TITLE
[regression] gpx file with wpt, lost functionality

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#10759]
### Description
I have lot of gpx files with wpt, as outsourced large favourite groups, which worked very well - until now.
With the latest version (OsmAnd~ (2)  3.9.0#31460m.apk) the following fearures does not work any more:
- searching within the gpx/wpt file (for name)
- tapping on a wpt to show it on the map (focus to that point).

### How to reproduce?
Opening gpx file with my places / tracks
Tapping on the file to open it
Select points

Problem came up AFTER OsmAnd~  3.9.0#31325m.apk, which was ok.
(Old osmand-nightly.apk)

Now after osmand-nightly.apk does not exist any more, I use OsmAnd-android-full.apk

### Your Environment
OsmAnd Version: OsmAnd~ (2)  3.9.0#31460m.apk.  2021-02-03
Android version: 10
Device model: samsung tab S5e

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/107063538-c88ac080-67da-11eb-9135-076f0980ee20.png)
Search is in full screen still present

**Comment by vshcherb** [comment]
But focus doesn't work correctly.

**Comment by pebogufi** [comment]
Ok, i found it, thanks for the hint.
But i think a lot of users will not find that.
What about putting the search symbol also in the top line when not in fullscreen.

**Comment by vshcherb** [comment]
Context menu for point will be fixed in 3.9.6

**Comment by pebogufi** [comment]
Test with OsmAnd~ (2)  4.0.0#31504m.apk 2021-02-10
Enclosed a file I tested with, the file is in a subdir of tracks.
[wpt_test.zip](https://github.com/osmandapp/OsmAnd/files/5958938/wpt_test.zip)

- the map focusses to a point before selecting a wpt, this is irritating.
- i select point#3 "Amiens, Le Cafe", the wpt is open with something like details, but does not focus to that point on the map.
- again i open My Places / tracks. In Visible(sichtbar) i see ZWO times my filename ("Gastronomie"), with info as 95 points.
![file doubled](https://user-images.githubusercontent.com/18628183/107530327-0e210200-6bbc-11eb-973c-ae867869ed8b.jpg)


- after some opening/ closing the list, it shows the list as 51 points, the list starts with different points...
![file 51 wpt](https://user-images.githubusercontent.com/18628183/107530371-1711d380-6bbc-11eb-8e93-e789cd9767ed.jpg)
There is something strange...

**Comment by vshcherb** [comment]
Let's double check @Chumva

**Comment by vshcherb** [comment]
@pebogufi we didn't manage to reproduce it, please open another bug and let's investigate somehow videos or log. It's not clear unfortunately yet.
