### ISSUE TITLE
Hillshade maps are now subtitled as 'Online maps'

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#10761]
![Screenshot_20210204-084058_OsmAnd~](https://user-images.githubusercontent.com/845735/106860785-275e1600-66c5-11eb-9763-c30e500f9317.jpg)

**Comment by dmpr0** [comment]
@vshcherb todo?

**Comment by vshcherb** [comment]
Well indeed they online maps and could be used as online maps. We think to keep as for now. It's also better to use Suffix instead of Prefix so maps are sorted by Name.
