### ISSUE TITLE
Translations of territories' names

### ISSUE THREAD

**Issue by debyos** [osmandapp/OsmAnd#10763]
Dear All,

some downloadable territories' names sound a bit strange in Hungarian. (They are old fashioned or not exact.) I would like to revise and, as the case may be, correct them.

Where can I find those names in Hungarian?

Thanks in advance

Gábor

**Comment by vshcherb** [comment]
We take them from OpenStreetMap. Once a year we sync them here https://github.com/osmandapp/OsmAnd-misc/tree/master/osm-planet/osm-data. You can find osm queries as well.
So the right answer is to update on osm.org first.
