### ISSUE TITLE
Poi icons are densely displayed on the map

### ISSUE THREAD

**Issue by Chumva** [osmandapp/OsmAnd#10768]
### Description
There is too much pois displayed on the map.

### How to reproduce?
Enable any poi type and show a whole city with them.

### Your Environment
OsmAnd Version: 3.9.4

This was before - 
![photo_2021-02-04_15-18-03](https://user-images.githubusercontent.com/19220417/106898124-770c0400-66fc-11eb-80c4-22467139cad0.jpg)

Now - 
![photo_2021-02-04_15-17-56](https://user-images.githubusercontent.com/19220417/106898115-74a9aa00-66fc-11eb-895f-50fd242fe3f3.jpg)

**Comment by scaidermern** [comment]
Maybe OsmAnd can reduce the icon size of there are many next to each other.

**Comment by vshcherb** [comment]
Not clear whether the situation getting worse between releases or we need to address something specific

**Comment by goldfndr** [comment]
The "before" looks like only "Cafe and restaurant" is selected, and "Now" includes others (Sightseeing?)
