### ISSUE TITLE
Track context menu: wrong statistic data

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#10777]
# Review 
- [x]  Track info on the "Overview" tab doesn't change after enabling the "Join segments" option.

### Description

The new track context menu on the "Overview" tab is shown distance, time, etc only for the first segment until restart of the app.

**Comment by AnastasiaTiutina** [comment]
The same problem
Original distance of the track is 14 km
![Screenshot_20210202-110426_OsmAnd_](https://user-images.githubusercontent.com/72389175/107049945-5ebae880-67d3-11eb-839c-e0df81f2db8d.jpg)
![20210203_175953](https://user-images.githubusercontent.com/72389175/107049963-64183300-67d3-11eb-82ed-ec823faf66f8.jpg)
![20210203_175148](https://user-images.githubusercontent.com/72389175/107049969-65496000-67d3-11eb-889d-d4dfe73d5d17.jpg)
