### ISSUE TITLE
Weird contour lines on map (artifacts of stitching?)

### ISSUE THREAD

**Issue by stalker314314** [osmandapp/OsmAnd#10772]
### Description

I am seeing weird lines on map, on all zooms. They are visible between various monthly updates, at least for 6 months, since I first noticed them. They form a T letter form and stretch for 100+km. I also see them on exact spots where there is round number of latitude/longitude (in this example 44/20)

### How to reproduce?

* Install map of Serbia (although I guess this is not specific for Serbia) and contour lines of Serbia
* Turn contour lines on
* Go to geo:44.00,20.00?z=17 (https://osmand.net/go?lat=44&lon=20&z=17)
* You should get same thing as attached at the bottom

### Your Environment
OsmAnd Version: 3.8.5 (although I have seen it on earlier versions too)
Android/iOS version: 8
Device model: Xiaomi MI 8

**Maps used (online or offline):**   
Offline map of Serbia of 01.01.2021. and contour lines of Serbia (I don't see date, but they are up-to-date as of 04.02.2021.

![11](https://user-images.githubusercontent.com/188751/106960368-e224fd00-6733-11eb-8472-05f66acd89df.png)
![13](https://user-images.githubusercontent.com/188751/106960438-ff59cb80-6733-11eb-9702-98b3e75ea445.png)
![15](https://user-images.githubusercontent.com/188751/106960502-17c9e600-6734-11eb-95a4-4122bf2e9672.png)
![17](https://user-images.githubusercontent.com/188751/106960537-24e6d500-6734-11eb-9d36-87f58a283911.png)

**Comment by xmd5a2** [comment]
Affected tiles:
```
N44E017.tif
N44E018.tif
N44E019.tif
N44E020.tif
N44E021.tif
```
Thanks for reporting!

**Comment by xmd5a2** [comment]
Fix will be available with next contour maps generation
