### ISSUE TITLE
OpenGL rendering + 2.5D on Android

### ISSUE THREAD

**Issue by capta** [osmandapp/OsmAnd#10770]
Hello, first i want to say i think Osmand is the best and complete software for me.
Last year in 2020 New Year resolutions you said that you eventually add OpenGL rendering + 2.5D on Android (it's seems it's in beta test for Android and already implemented on iOS).
Is there a chance that this feature will be implemented in the stable branch for Android in 2021 ?
Thanks

**Comment by vshcherb** [comment]
Yes, it's still on the roadmap, but it requires right people with right expertise. I hope we will get somebody joined this year and feature will get pushed 2021 summer.
