### ISSUE TITLE
Permission ACCESS_BACKGROUND_LOCATION is missing

### ISSUE THREAD

**Issue by snmich** [osmandapp/OsmAnd#10782]
### Description
On Android 10 this permission must be in the manifest to enable backround access to location services:
<uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />

### How to reproduce?
Start recording a track. Switch to another app. Frequently a toast appears with this resource: R.string.off_router_service_no_gps_available

### Your Environment
OsmAnd Version: 3.9.5
Android/iOS version: Android 10
Device model: Galaxy S9

**Comment by AnastasiaTiutina** [comment]
The same problem
![Screenshot_20210204-103527](https://user-images.githubusercontent.com/72389175/107052897-e22a0900-67d6-11eb-8fa5-d769fdf41e7a.png)

**Comment by Famlam** [comment]
Also on Android 9. Happens since the update from 3.9.4 to 3.9.5 yesterday

**Comment by vmicho** [comment]
Yes, same here. Furthermore I've observed there is only "allow while using app" possibility in the location/osmang settings.
The option "Allow all the time" is missing.

![Screenshot_20210206-194557_Permission_controller](https://user-images.githubusercontent.com/66125746/107150622-f3058680-695e-11eb-8455-ae2c8365d0f7.png)

**Comment by Chris56** [comment]
Why has this been closed???
Trip recording does not work anymore, LineageOS 17.1, Android 10 (e.g. while on a hike, when mobile screen off most of the time ...)
Regards,
Chris

**Comment by sonora** [comment]
Cross-link: https://github.com/osmandapp/OsmAnd/issues/12397#issuecomment-955420132
