### ISSUE TITLE
Car routing is creating loops and turns

### ISSUE THREAD

**Issue by mipri25** [osmandapp/OsmAnd#10789]
# 🐞 routing report

Hello,

after an update to OSMAnd 3.9.5 the car routing is creating strange turns and loops. I've picked 3 examples showing the problem.

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, OpenRouteService, OSRM, etc.)

### Routing Profile
car

### Start and end points
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=48.6736%2C10.0715%3B48.6712%2C10.0681#map=18/48.67237/10.06962

https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=48.5425%2C10.1158%3B48.5365%2C10.1127#map=17/48.53950/10.11432

https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=48.5787%2C10.1609%3B48.5717%2C10.1470#map=16/48.5769/10.1539

### Actual and expected routes
These screenshots show the actual routing. For the expected routing, please see the OSM permalinks above.

![1](https://user-images.githubusercontent.com/78664491/107130127-fea76d80-68ca-11eb-83fc-c801f0f0059d.png)
![2](https://user-images.githubusercontent.com/78664491/107130130-036c2180-68cb-11eb-88d0-f225e185f9f5.png)
![3](https://user-images.githubusercontent.com/78664491/107130133-06ffa880-68cb-11eb-9599-dee66127b111.png)

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 3.8.5

## 🌍 Your Environment

**OsmAnd Version:** 

<pre><code>

3.9.5 unlimited
</code></pre>

**Device and Android/iOS version:**

LG Stylus 2, Android 6.0.1

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**
The screenshots were created using OSMAnd running on Android_x86 8.1 in VirtualBox, but I've double checked that my phone is doing exactly the same routing.

**Comment by hakuchi** [comment]
tested with my version and make same problems.
I also tested coming from south(A7) and driving to "Bissingen". OsmAnd is using the "L1079" and the "Dittinger Weg" to reach "Bissingen"

**Comment by sorcrosc** [comment]
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=43.39844%2C13.55669%3B43.39777%2C13.55402#map=18/43.39737/13.55572
![immagine](https://user-images.githubusercontent.com/7443746/107422277-1c6b1180-6b1b-11eb-8c10-57b136e9f13a.png)

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/pull/10846
https://github.com/osmandapp/OsmAnd-core/pull/201
