### ISSUE TITLE
"Quick Action" object is created at crosshair/center only on GPS follow

### ISSUE THREAD

**Issue by ManDay** [osmandapp/OsmAnd#10788]
The "Quick Action" (for example to add an OSM Note) will create that note precisely at the crosshair position if the the GPS position is followed, which is useful. However, when there is no GPS lock or the GPS position is not followed, but instead the map/crosshair is positioned at will, performing the "Quick Action" will create the object about 2/3 down the screen, rather than at the center/crosshair. This is not useful and prevents "Quick Action" to be used to position objects precisely by crosshair, rather than by long-tap (which is inherently inaccurate).

**Comment by vshcherb** [comment]
Yes that's why you could simply click quick action first and then center map as you need to have it precise.

**Comment by ManDay** [comment]
Would you consider this as a feature request then? I see no reason why the marker would be created besides the crosshair, it only induces an additional step which I find inconvenient when I use it.

**Comment by vshcherb** [comment]
It was implemented on purpose, so there is no screen jump and only for with my location sync, we change the map that you see.
