### ISSUE TITLE
Rare location update

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#10780]
### Description

The Position icon hasn't a smooth movement during navigation.
Position icon bearing changes when we stay in one place (Position icon at rest or Position icon while moving)

### How to reproduce?

During navigation, you see sharp jumps in position (Location update 1 time per 5 sec)

### Your Environment
OsmAnd Version: 3.9.0.#31464)
Android/iOS version: Android 11
Device model: Samsung 10e

**Comment by Rahalteam** [comment]
> ### Description
> The Position icon hasn't a smooth movement during navigation.
> Position icon bearing changes when we stay in one place (Position icon at rest or Position icon while moving)
> 
> ### How to reproduce?
> During navigation, you see sharp jumps in position (Location update 1 time per 5 sec)
> 
> ### Your Environment
> OsmAnd Version: 3.9.0.#31464)
> Android/iOS version: Android 11
> Device model: Samsung 10e

Yes, and I note that also with the latest official version 3.9.5

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/commit/9efe8ffd0afc8cc39ad370eb74ef0e0831538fb1
