### ISSUE TITLE
Logging interval is suddenly 5 seconds (osmand+ 3.9.5)

### ISSUE THREAD

**Issue by vmicho** [osmandapp/OsmAnd#10795]
### Description
Just updated, and observed on the gpx recording that the trace is way too "blocky"
After a look in Viking (gpx editor), I see the interval is 5 seconds between points, pretty unusable.
I set it normally to "continuous" (or 0 sec, it's the same).
On Friday 2021-02-05 mornigng everything was nice and smooth (1 second between recorded points), afternoon a blocky mess (5 seconds between points)
The only change in between was update to 3.9.5.
I also have another phone, I'll wait definitely with update there.

Can this be related to https://github.com/osmandapp/OsmAnd/issues/10782 ?

### How to reproduce?
Start gpx recording, with 1 or 0 second logging interval, no minimal distance (I've tried both 'not set' and '2 m')
Physically move along to record some trace (staying at one place with fix also should be enough, the location moves along a bit due to imprecisions)
Pause, save, open gpx file and check the interval between points.

### Your Environment
OsmAnd Version: 3.9.5
Android/iOS version: android 10 (LineageOS 17.1)
Device model: Mi Mix

**Maps used (online or offline):**
Offline maps.   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

![Screenshot_20210207-161329_OsmAnd+](https://user-images.githubusercontent.com/66125746/107151358-77a5d400-6962-11eb-8ab2-f4b9e794b548.png)

**Comment by kreuzschnabel** [comment]
Confirmed. Even the position pointer on the map is leaping forward every 5 seconds now, instead of moving continuously as it used to. On the car dashboard, the position is always 50-100 metres behind. This is awkward.

**Comment by vshcherb** [comment]
Fixed, will be released on Wednesday.
