### ISSUE TITLE
Position suddenly jumps around during navigation (speed camera or tunnel problem?)

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#10794]
The recent version 3.9.5 introduced a strange bug. When approaching a speed camera the position starts to jump between the actual current position and the speed camera. OsmAnd subsequently recalculates the route every few seconds. This is not a problem of the GPS signal since the recorded track is fine.

I think this even happens during simulation, in a slightly different way. Try to simulate a navigation from 51.0656456,13.767693 to 51.0607707,13.775804. As soon as the speed camera warning is triggered, the car speed goes up to >100 km/h (sometimes even >500 km/h( although the speed limit is at 50 km/h. This also happens in the other direction, e.g. from 51.058188,13.7773919 to 51.0714571,13.7711048

**Comment by vshcherb** [comment]
Can you please provide a recorded GPX for that segment (1-3 km)?

**Comment by scaidermern** [comment]
Unfortunately I don't have the original unmodified track any more. I just got a cropped and simplified version of this track: [foo.gpx.txt](https://github.com/osmandapp/OsmAnd/files/5943676/foo.gpx.txt)

**Comment by scaidermern** [comment]
Here is a screen capture: https://user-images.githubusercontent.com/1040784/107364391-aabfa300-6adb-11eb-8fe2-35289d6dd7f4.mp4
And the GPX recording: [2021-02-09_13-21_Tue.gpx.txt](https://github.com/osmandapp/OsmAnd/files/5951354/2021-02-09_13-21_Tue.gpx.txt)

This jumping continuous endlessly. This time it looks like it jumps between the current position and the upcoming tunnel (which is about 900m away).

**Comment by vshcherb** [comment]
Problem is visible but we couldn't reproduce it yet. Probably it's related to a major fix of location from Google Play Services. Please try nightly or 3.9.6

**Comment by scaidermern** [comment]
I'm not quite convinced that this is a problem caused by the location services. This only happens at this two map locations mentioned in the first post. Both involve a tunnel and a speed camera. So far this problem didn't occur at any other location.

**Comment by scaidermern** [comment]
Looks like you are right, I couldn't reproduce it with the latest nightly.
