### ISSUE TITLE
Dark mode issue

### ISSUE THREAD

**Issue by miramikes** [osmandapp/OsmAnd#10804]
Hello,

when having my phone in "dark mode" i have problem to read some values from my display ( top right corner and bottom center )

![Screenshot_14](https://user-images.githubusercontent.com/623412/107259459-4e0dab00-6a3d-11eb-8ee6-24b22289fc4c.jpg)

When I switch to default  "light mode" all is fine ...

![Screenshot_13](https://user-images.githubusercontent.com/623412/107259578-74cbe180-6a3d-11eb-96b1-b33d3d5bea99.jpg)

Maybe this values shouldn't follow "light/dark mode" and stay all time well readable ... 

best

mira

**Comment by vshcherb** [comment]
OsmAnd has own dark mode which should work fine, so it's not clear where the issue comes from.

**Comment by JoergHW** [comment]
I'm using 3.9.7 and found that the settings for "car" and "bike" work, but "world, pedestrian, public transport/bus" does not. I'd think it is more than a theme setting, as your fix suggests. But I did not look into the details.
