### ISSUE TITLE
Cliff - tweaking

### ISSUE THREAD

**Issue by miramikes** [osmandapp/OsmAnd#10811]
Hello,

I noticed that cliffs are visible quite late ... I mean in very close zoom level and are marked as quite thin line.
I believe that they are very important feature on map because of safety route planning ... especially in hiking skiing and biking profile.
So I think they should be visible in higher zoom level and maybe also in different self-explanatory way for example line of grey triangles ...

best regards

mira

![Screenshot_16](https://user-images.githubusercontent.com/623412/107295971-c17ce000-6a70-11eb-9c98-efa74b96dd7d.jpg)

**Comment by miramikes** [comment]
Now I realize that this issue might not be so easy as it seem to be. There are area which are very dense with "cliffs" as on new screenshot:
![Screenshot_17](https://user-images.githubusercontent.com/623412/107797002-b79dfa00-6d5a-11eb-936e-091643b17b71.jpg)
And showing these cliff in distant zoom might be challenging.
Nevertheless anyway worth to do ... the previous screenshot is a very dangerous area which know very well as I skimountaineered there few times and on map nothing warn you that you approaching such a place.

**Comment by miramikes** [comment]
There is one more related feature which should be investigated with natural=cliff and it is natural=bare_rock.
natural=bare_rock should have a bit more distinctive look in my opinion ... 
Whitish spots on previous screenshot are bare_rocks , but they are difficult notice in phone display so some more clear way of displaying this would be great.
On other hand there would be similar problem like with cliffs ... there are big areas which are all covered with bare_rock like high mountains so make them generally too dark will not make a sense.

**Comment by xmd5a2** [comment]
This issue is not solved in any renderer I know including OSM mapnik styles. I see no way to solve it because OSM data sometimes are very heterogeneous.
