### ISSUE TITLE
Background Navigation Service

### ISSUE THREAD

**Issue by NickSlash** [osmandapp/OsmAnd#10819]
### Description
One of the recent updates has caused navigation to be a lot less responsive and there is a message ("the background navigation service requires a location provider to be turned on") that pops up frequently during navigation. 

I had a look at the permissions for the app and there are two options, "deny" and "allow when in use". I cant be certain but I think that previously there was an "allow" option.

### How to reproduce?
start navigation to any destination

### Your Environment
OsmAnd Version: osmand+ 3.9.5 2021-02-03
Android/iOS version: android 10
Device model: oneplus nord 

**Maps used (online or offline):**   offline map
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by vshcherb** [comment]
Yes, we fixed couple of issues in 3.9.6 - and there is no "Always allow" this is a restrictions from Google Play but the app should be working fine now.

**Comment by sakhnik** [comment]
@vshcherb, I remember "Always allow" was there, and I had to set it to be able to navigate or record tracks with the screen off. Will it still work without "Always allow" or are there new limitations?

**Comment by vshcherb** [comment]
https://docs.osmand.net/en/main@latest/osmand/troubleshooting/track-recording-issues update documentation here about always allow
