### ISSUE TITLE
how do i get my money back?

### ISSUE THREAD

**Issue by nutpantz** [osmandapp/OsmAnd#10829]
The latest version of osmand complains i don't use Google play services. I never have and have been using osm for years.
How do i turn off the complaining or how do i get my money back for buying the app?  
I don't want to support Google play services monitoring my activities

**Comment by vshcherb** [comment]
Yes, it won't be possible to distribute via Google Play without GPlay Services any more. You can either switch
to our
- nightly builds (https://download.osmand.net/latest-night-build/)
- Amazon version (separate paid version) or Huawei
- Request refund (via support)
