### ISSUE TITLE
OsmAnd Live: No appropriate correction after the reconstruction of the national road 66

### ISSUE THREAD

**Issue by Kivasya** [osmandapp/OsmAnd#10827]
https://www.openstreetmap.org/query?lat=52.68663&lon=23.24989#map=17/52.68759/23.25413
![Screenshot_20210207-154718 (1)](https://user-images.githubusercontent.com/75778939/107534257-6d850f00-6bc8-11eb-8e08-10fff6261695.png)
![Screenshot_20210207-153852](https://user-images.githubusercontent.com/75778939/107534305-74138680-6bc8-11eb-86a5-c66493a791a3.png)

**Comment by vshcherb** [comment]
This is OsmAnd Live issue.

**Comment by vshcherb** [comment]
Workaround to clean up live updates and redownload february maps

**Comment by ivanPyrohivskyi** [comment]
Not a bug.
The road was rebuilt in May-July 2020.
![Screenshot 2021-03-26 at 12 01 25](https://user-images.githubusercontent.com/1040293/112615345-0b583480-8e2b-11eb-8913-423e2d22fa96.png)
