### ISSUE TITLE
addr:housenumber is displayed in a wrong order

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#10825]
Probably issue related to iOS
https://www.openstreetmap.org/way/230003896#map=19/48.36087/10.86608
![image](https://user-images.githubusercontent.com/1042025/107524368-fc3c6080-6bb5-11eb-8b86-0261f21cad55.png)

**Comment by xmd5a2** [comment]
This is clearly an OpenGL engine issue:
![Screenshot_2021-02-19_10-46-29](https://user-images.githubusercontent.com/5829014/108475235-7e591300-72a1-11eb-9017-0416c093b2f1.png)
Android:
![Screenshot_2021-02-19_10-46-16](https://user-images.githubusercontent.com/5829014/108475264-85802100-72a1-11eb-9c96-c06964836463.png)

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-core/pull/218
