### ISSUE TITLE
Some waters are missing in Slovakia map

### ISSUE THREAD

**Issue by Kivasya** [osmandapp/OsmAnd#10824]
Water ponds, lakes and water areas added in 2020 (OSM) are not in Osmand Slovakia. „Aljaška“ or „Mláky pod Rozdielňou“ etc are missing.
https://www.openstreetmap.org/way/804838696#map=19/48.91030/22.12781
![IMAGE 2021-02-10 16:13:08](https://user-images.githubusercontent.com/75778939/107521141-dd8c9880-6bba-11eb-9a23-e786ea2b1252.jpg)

**Comment by xmd5a2** [comment]
This is wrong mapping. Lakes surrounded by water should have "inner" roles in wood multipolygons. We render woods above water by default. May be it is possible to improve OsmAnd rendering but obviously this is wrong mapping.

**Comment by scaidermern** [comment]
Indeed.

On https://www.openstreetmap.org/ this water body is also shown with trees on top:
![foo](https://user-images.githubusercontent.com/1040784/108328369-cf4b0780-71cc-11eb-9469-6fb19365bf25.png)

I've fixed the above water body in OSM.
