### ISSUE TITLE
Zig-zags on the route

### ISSUE THREAD

**Issue by Kivasya** [osmandapp/OsmAnd#10823]
On New Zealand routes some zig-zags appear along the route with left turns.
https://www.openstreetmap.org/search?query=-36.7629025%2C%20174.7135806#map=17/-36.77036/174.72625

![image](https://user-images.githubusercontent.com/1042025/107518724-a1a00600-6baf-11eb-8314-822d054fe6a1.png)

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/107519664-cfd21580-6bb0-11eb-9ad0-16bc4c843242.png)
Not reproducible

**Comment by vshcherb** [comment]
In case we have more information how the route was constructed, we could address it better. It looks like "Route approximation" was used but we need to have then original track itself
