### ISSUE TITLE
Navigation calculation issues when using OsmAnd for iOS (v3.92) in the Bergamo province

### ISSUE THREAD

**Issue by Kivasya** [osmandapp/OsmAnd#10839]
Steps to reproduce the issue:
Set an itinerary from 45.71007 09.70285 to 45.78464 09.82148 using Car mode with default Options (no roads avoided, Fuel-efficient way and Consider temporary limitation turned off, etc.). Distance should be 15.1km and time 21mins.

The driver is asked to make two very strange detours from the main road between Torre Boldone and Nembro, and then several times after that (while on the "Strada Provinciale Bergamo - Nembro") the driver is asked to take exits, only to re-enter the main road a few hundread meters after that.
![IMG_9469](https://user-images.githubusercontent.com/75778939/107641450-4f78e680-6c7c-11eb-9614-d05d10220d58.jpg)
![IMG_9471](https://user-images.githubusercontent.com/75778939/107641513-63bce380-6c7c-11eb-9851-72a341539976.jpg)
![IMG_9470](https://user-images.githubusercontent.com/75778939/107641534-6b7c8800-6c7c-11eb-9bd2-63f424c1997b.jpg)
![IMG_9472](https://user-images.githubusercontent.com/75778939/107641564-73d4c300-6c7c-11eb-833a-6f652d5dcd6a.jpg)

In addition, near Varese, Lombardy (Italy) the app would have the car jump off a bridge to exit a road that clearly can't be exited at that point. 
Sometimes while using the car navigator and taking a different road than the one suggested by OsmAnd Maps the app doesn't start recalculating the route right away, which can be very problematic in some circumstances.
![IMG_9522](https://user-images.githubusercontent.com/75778939/107641917-dfb72b80-6c7c-11eb-8870-35951659fe76.jpg)
![IMG_9516](https://user-images.githubusercontent.com/75778939/107641926-e3e34900-6c7c-11eb-8b38-641f9a476fca.jpg)
![IMG_9515](https://user-images.githubusercontent.com/75778939/107641948-eba2ed80-6c7c-11eb-91dc-70e27e90cd8c.jpg)
![IMG_9517](https://user-images.githubusercontent.com/75778939/107641961-efcf0b00-6c7c-11eb-995b-752f907e3c0d.jpg)
![IMG_9525](https://user-images.githubusercontent.com/75778939/107641977-f3629200-6c7c-11eb-9400-8f5f5df48004.jpg)

**Comment by vshcherb** [comment]
Is this issue reproducible?

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/pull/10847
