### ISSUE TITLE
Osmand doesn't record altitude any more

### ISSUE THREAD

**Issue by j-schneid** [osmandapp/OsmAnd#10831]
### Description
Osmand doesn't record altitude any more. At least not correctly: It seems to save the initial value of the first fix it gets for all subsequent trackpoints. So the total altitude gain and loss is 0 m and the curve is flat.
I'm sure it is not an issue of the phone itself because other apps (even simultaneously) still record correct values. 

### How to reproduce?
Record a track, then open it.

### Your Environment
OsmAnd Version: 3.9.5
Android/iOS version: 10
Device model: Samsung XCover 4s

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
I believe this is not map related.

**Comment by vshcherb** [comment]
Please try 3.9.6 where the issue should be fixed.

**Comment by c-peukert** [comment]
I have exactly the same problem with version 3.9.6 from google play. 
With version 3.9.6 from your site https://osmand.net/downloads the problem does not exist. 
Tested on to different devices (redmi note 8 pro and galaxy a30s)

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/10864

**Comment by vshcherb** [comment]
Which android versions do you have?

**Comment by vshcherb** [comment]
So far it looks working on Android 11, but not on Android 10

**Comment by c-peukert** [comment]
note 8 has 10 QP1A.190711.020 
galaxy a30s has 10 QP1A.190711.020.....

**Comment by j-schneid** [comment]
What has changed since the 3.9.6 update is that osmand now records not only one wrong value all the time but one value for the first ~1/2 hour and then it starts to record different values per point.* This applies to my android 10 phone. One my old Android 4 phone everything works fine as before.
*Actually I'm not sure if anything has changed: Maybe when trying before the update I just didn't wait long enough.

**Comment by j-schneid** [comment]
As c-peukert mentioned it I tried the version from your website instead of the one from Google play. Actually it works. But mine used to be Osmand+ which I can not download, so I have to wait for a fix.

**Comment by vshcherb** [comment]
You can contact support to get it, in a short period it's unlikely a fix will be provided. Probably Google Play Services will be updated in a mid-term

**Comment by j-schneid** [comment]
Not fixed in Osmand+ 3.9.9 from Google Play.
Elevation values are not identical any more but they stay very close to the initial value. I started my bike trip at 326m (at least according to Osmand, but reasonable) and values differ by 0.1 steps (min. 324, max. 327) while I cycled up to 523m.

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/10864 but no solution so far as we know
