### ISSUE TITLE
Estimate routing time for hikers

### ISSUE THREAD

**Issue by Kivasya** [osmandapp/OsmAnd#10830]
Osmand version 3.90.2 (iPhone 11, iOS 14.4).When plotting daily crossings between intermediate points, the program suggests suspiciously short, unrealistic travel times. In navigation profile pedestrian, elevation data included, using fresh favorites without importing gpx tracks from other resources or applications.

Here are some examples:

On the way to Mera peak there is a passage Chutanga - pass Zatrwa La - Thuli Karka, distance 5.3 km. Another app gives 8h 15m, Osmand 3h 30m. People spend all daylight hours in this difficult area.

Sagarmatha National Park. Passage Dzonghla - Gorak Shep, 11 km:
Osmand - 3h 45m. Usually, it takes about 7 hours to pass it.

**Comment by xmd5a2** [comment]
To correctly fix this issue we need to introduce absolute altitude penalties. For example: if user gets higher than 4000 m then N seconds penalty applies to all ways.

**Comment by sonora** [comment]
Things are VERY individual one you go beyond the ordinary Naismith rule (60 additional minutes per 600m of ascent). That is primarily because of the effect of terrain (significantly hard to derive from map data), and then again depends on people's technical skills and fitness.

Several attempts have been made in literature, see e.g. here https://blog.hiiker.app/2021/11/02/how-we-calculate-hike-time/. We could adopt one, but should know that for most "standard" hiking tours in not-extreme terrain straightforward Naismith alone is excellent, and for Alpine tours many even more elaborate approximations will be too difficult to rely on no matter what, there individual inquiries must be made (as every mountaineer knows). Maybe it would be better for OsmAnd to produce a warning for tours where we detect extreme elevation changes to the effect that travel times may be several impacted by terrain.

**Comment by sonora** [comment]
In our Android edition, I have meanwhile fixed this:
![Screenshot_20221118-093109_OsmAnd~](https://user-images.githubusercontent.com/845735/202658027-6ae7ae58-74d6-4f6b-a2d0-fe35b2367951.jpg)

Maybe someone can check if this is correctly ported to our iOS code, including the minor fix I had committed last week?

The solution uses the Naismith/Scarf empirical rule which says the elevation gain penalty adds a hiking time of approximately 8 times the time you would take to hike the elevation gain as a horizontal (flat) distance.

The key here is for extreme situations  to adjust your default speed under 'routing parameters'  in OsmAnd's pedestrian app profile, or simply create a second profile like "High elevation hiking".

The standard is set at 4km/h, but that's certainly wrong for 4000m altitude. The screenshot above is the result if you set it to more realistic 2km/h for that terrain and altitude.

Side note: Likewise for joggers or trail runners, they can increase the default speed from the default 4km/h to their individual standard value and then receive good trip time projections.

**Comment by vshcherb** [comment]
@sonora iOS can't use code from java completely, please attach commits as references, so they can be migrated to C++

**Comment by sonora** [comment]
It looks to me from the hiking time projections stated in the issue above that the iOS version already contains my original _"Static" Naismith_ implementation https://github.com/osmandapp/OsmAnd/commit/b81a3abc2caca88f57c1e168cac891a38479e0ef.

These were be my commits upgrading that to the flexible _Naismith/Scarf_ algorithm:
https://github.com/osmandapp/OsmAnd/commit/584289a1918b9c6a96f55ea5bf7c63bad4be300a
https://github.com/osmandapp/OsmAnd/commit/78b6779eaaf437b87799eafbeba7e865a35dd0aa
https://github.com/osmandapp/OsmAnd/commit/790747ac01dfd438970473cbbc61632dc90ad05b
https://github.com/osmandapp/OsmAnd/commit/b72ece047050da790f29b4a4915abf6444100bca
https://github.com/osmandapp/OsmAnd/commit/d07bec6f6edd0ead82c9946106db874b9e1b22b3
https://github.com/osmandapp/OsmAnd/commit/4fbe7055ca38d1be74a9204d3e3e472ebc4325b7
https://github.com/osmandapp/OsmAnd/commit/0ca0bd346dc32c14917fb09b93c9efda18003143
https://github.com/osmandapp/OsmAnd/commit/f9a6726abd51f4ecf7bc1f6a7b200139ac6cfe4a
https://github.com/osmandapp/OsmAnd/commit/ab8c3741184a28f77a1647f7712c79f979a60ea0

**Comment by vshcherb** [comment]
- Extra Check: how we use routing parameter elevation data in iOS?

**Comment by sonora** [comment]
This is an iOS-only issue, should not be in the our 4.3-backend Milestone?

**Comment by sonora** [comment]
@ivanPyrohivskyi i It isas follows:

Go to the  "Walking" profile (or create a separate one 'High altitude hiking'),  then gor that go to `Configure profile > Navigation settings > Vehicle parameters > Default speed`.

The default speed is your individual speed in flat terrain, i.e. for no elevation change.

Our standard setting is 4 km/h, which fits rather well for most people's walking and hiking. But it is of course too small for many runners, and too high for Nepal hiking in low oxygen altitude and difficult terrain.

The exact value depends on your sports and on your fitness. I simply used 2km, I use that myself for hiking above 3000m.

**Comment by sonora** [comment]
PS: Hadn't noticed cpp code still needed syncing...

**Comment by vshcherb** [comment]
Everything needs syncing except pure C++ which is rare
Syncing is not bad ann difficult the main advantage we still develop with simple tools using Java first
