### ISSUE TITLE
Routing by car

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#10837]
### Description
Not built route in 3.9.6 version, for 3.8.3 not have this issue. (the same map data)

3.9.6
![image](https://user-images.githubusercontent.com/44466116/107629293-f5275800-6c72-11eb-85dd-11999abc5d97.png)

3.8.3
![image](https://user-images.githubusercontent.com/44466116/107629319-fe182980-6c72-11eb-9e59-3b27d40471c0.png)

Used apk-files from https://osmand.net/downloads

### Your Environment
OsmAnd Version: 3.9.6 and 3.8.3
Android/iOS version: Android
Device model:

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/pull/10846
