### ISSUE TITLE
Free color choice for favorite groups

### ISSUE THREAD

**Issue by tradavyvy** [osmandapp/OsmAnd#10835]
The latest version 3.9.5. adds free color choice to favorites. MANY thanks for that.
But this does not seem to work for goups of favorites.
Is this a bug, an oversight or a willfull omission?

To reproduce just try to set a free custom color for a favourite group.

OsmAnd Version: 3.9.5.
Android/iOS version: android 10 I think
Device model: multiple samsung devices

**Maps used: off line

I would realy like this option implemented if the ommission is not a bug

Thanks in advance

**Comment by dmpr0** [comment]
We need to:
- Redesign the "Choose category" dialog, to the new bottom sheet, similar to "Add group" in "Plan a Route > Save as track"
- Redesign the "Add new category" dialog. Make bottom sheet, with the new color selection component.
![Add group](https://user-images.githubusercontent.com/9365308/108976115-df149100-768f-11eb-9b44-e2ac41787b80.png)
