### ISSUE TITLE
Typo in dutch version

### ISSUE THREAD

**Issue by tradavyvy** [osmandapp/OsmAnd#10844]
The dutch version of the route setup page has a typo.
Instead of srraatniveau it should say:
straatniveau

![Screenshot_20210211-230751_OsmAnd+](https://user-images.githubusercontent.com/71978409/107704902-3f81f680-6cbe-11eb-854a-32fecc5c411b.jpg)
### Your Environment
OsmAnd Version:
Android/iOS version:
Device model:

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by letypequividelespoubelles** [comment]
Translation of OsmAnd is made [here](https://hosted.weblate.org/projects/osmand/). You can correct the typo, and don't hesitate to enhance traduction if you can!  😃

**Comment by vshcherb** [comment]
Please change it as described below
