### ISSUE TITLE
track with wrong overview data

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#10852]
### Description
Opening a track with **more than one segment** shows SOMETIMES overview data only of the first segment, sometimes the total of the whole track (as expected).
Testfile: 
[ri2021-02.zip](https://github.com/osmandapp/OsmAnd/files/5972774/ri2021-02.zip)

In My places / tracks the track has 13.6km
![track 13 6](https://user-images.githubusercontent.com/18628183/107788766-13638580-6d51-11eb-9ed6-a47537a66e6c.jpg)

Opening this track the overview tab shows 7.18km, which is only the first segment.
![track7 18](https://user-images.githubusercontent.com/18628183/107789550-04c99e00-6d52-11eb-844a-7c7bd79e26a8.jpg)

After several open / close / back, clearing cache and again opening, ... SOMETIMES the overview has the total data 13.6km, as expected.
Sometimes it depends, whether the track is opened from folder 
My Places / tracks / rec / 2021-02 
or from 
My Places / tracks / visible.
... very strange...

Have fun when testing :-), Peter 

### Your Environment
OsmAnd Version: OsmAnd~ (2)  4.0.0#31518m.apk 2021-02-11
Android 8:
Device model: samsung S7 SM-G930F

**Comment by vshcherb** [comment]
We need to fix it in 3.9

**Comment by Skalii** [comment]
done

**Comment by pebogufi** [comment]
@Skalii @vshcherb 
i made the tests with a app version of TODAY !
OsmAnd Version: OsmAnd~ (2) 4.0.0#31518m.apk 2021-02-11
are you shure that it is fixed ?
