### ISSUE TITLE
Some peaks doesn't have show name and elevation + names on curly lines

### ISSUE THREAD

**Issue by miramikes** [osmandapp/OsmAnd#10859]
Hello,

Some names placed on curly "line" feature are unreadable and should be rather placed beside feature in this case.
In my example is cliff with name "Holubnik" ... Cliff surrounds peak "Holubnik" elevation 1070m
But name of this peak and it's elevation is not seen.

best mira
![Screenshot_24](https://user-images.githubusercontent.com/623412/107844025-50bb2800-6dd0-11eb-9ca8-d934ef5354da.jpg)
![Screenshot_23](https://user-images.githubusercontent.com/623412/107844026-56187280-6dd0-11eb-994f-c82678363315.jpg)
![Screenshot_22](https://user-images.githubusercontent.com/623412/107844028-5add2680-6dd0-11eb-8f0e-edf1e464a314.jpg)

**Comment by miramikes** [comment]
Hello,
I just check this issue in latest night build with freshly updated map and peak Holubnik still missing name and elevation ... winter and ski profile

**Comment by xmd5a2** [comment]
Fix was done after Czech map was actually generated

**Comment by dmpr0** [comment]
We need to check this in the next month with the new maps.
