### ISSUE TITLE
Issue with wrong turn (right instead of left)

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#10863]
Location around lat="59.4091475" lon="56.8418888"

![image](https://user-images.githubusercontent.com/1042025/107848382-5c6c1600-6df3-11eb-9ef8-716d93a1b012.png)
Track is attached

**Comment by xmd5a2** [comment]
```xml
	<segment id="39337837" oid="2517621597" start="0" end="1" time = "16.63631" rspeed = "6" name = "Юбилейная улица" distance = "28.877842" turn = "Turn slightly right(C|+TSLR)" turn_angle = "5.2554436" lanes = "[2, 13]" start_bearing = "-44.787006" end_bearing = "-44.787006" height = "[0.0, 191.0, 28.877842, 192.0]" description = "Turn slightly right(C|+TSLR) and go 273,58 meters" />
```

**Comment by alisa911** [comment]
https://www.openstreetmap.org/changeset/100053389#map=17/59.40983/56.83503
<img width="759" alt="Screenshot 2021-02-26 at 15 11 09" src="https://user-images.githubusercontent.com/38911173/109304867-943c7a00-7845-11eb-9157-dd08d62a1502.png">
<img width="664" alt="Screenshot 2021-02-26 at 15 11 17" src="https://user-images.githubusercontent.com/38911173/109304872-96063d80-7845-11eb-8196-08bb76d7d1d3.png">
