### ISSUE TITLE
Routing issue near Oberdorf

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#10860]
https://www.openstreetmap.org/#map=15/47.6145/9.5652
![image](https://user-images.githubusercontent.com/1042025/107847269-7523fe00-6dea-11eb-8c8e-5d95288e7c8f.png)

**Comment by aceman444** [comment]
Strange, there does not seem to be any error in the OSM data, like a turn restriction forbidding to go straight on B31.
(There is a missing one on the spot where OsmAnd u-turs back to K 7706, I will add that one.)

You are using some special routing mode (a campervan/motorhome) :)

**Comment by vshcherb** [comment]
it's not me, taken from support request. So if you can fix it on OSM please me know to close the issue )

**Comment by aceman444** [comment]
I haven't found a problem in OSM data yet.

**Comment by alisa911** [comment]
This has been fixed https://github.com/osmandapp/OsmAnd/commit/1b03867e2c5439ea11628be8882498feb13deddb

**Comment by aceman444** [comment]
Hi, @alisa911 so what was the problem? Did OsmAnd evaluate the turn restriction only_straight_on wrongly? But I haven't noticed that elsewhere.

**Comment by vshcherb** [comment]
It was a bug in implementation of another feature done in 3.9
