### ISSUE TITLE
No numbers with Korean font

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#10862]
We need to include numbers in korean font as a known issue with harfbuzz not implemented yet.
![image](https://user-images.githubusercontent.com/1042025/107847882-7ad01280-6def-11eb-94ff-ac12b944e24e.png)

**Comment by xmd5a2** [comment]
Not reproducible
With and without additional font:
![Screenshot_2021-02-24-22-25-22-923_net osmand plus](https://user-images.githubusercontent.com/5829014/109055057-bf14ba00-76ef-11eb-8de0-dcaecdea28e5.jpg)
![Screenshot_2021-02-24-22-24-28-481_net osmand plus](https://user-images.githubusercontent.com/5829014/109055065-c045e700-76ef-11eb-878a-478b117f1503.jpg)
