### ISSUE TITLE
Routing ignores access=no tag

### ISSUE THREAD

**Issue by xerus2000** [osmandapp/OsmAnd#10876]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, OpenRouteService, OSRM, etc.)

### Routing Profile

bike, standard

### Start and end points

Häusling, Erlangen, Germany to Uttenreuth, Germany

This routes me across https://www.openstreetmap.org/way/4319363 which has had an `access=no` tag for almost half a year now (so outdated maps shouldn't be the issue either, I have just refreshed them anyways).

## 🌍 Your Environment

**OsmAnd Version:** 3.9.4

**Device and Android/iOS version:* Samsung S7 Edge with Android 8

**Maps used (online or offline):** Both

- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**

**Comment by scaidermern** [comment]
Wrong tagging. Access tags are hierarchical, so foot and bicycle tags overwrite the less specific access tag. See https://wiki.openstreetmap.org/wiki/Key:access
