### ISSUE TITLE
Dashboard no longer exists in 3.9.6 for Android

### ISSUE THREAD

**Issue by hvdwolf** [osmandapp/OsmAnd#10879]
The dashboard functionality no longer exists in 3.9.6 for Android (and maybe a few earlier releases as well).

It is nowhere to be found. 

Reported here: https://groups.google.com/g/osmand/c/qwiDnnG3V4Y/m/ehBGDkosBwAJ

**Comment by vshcherb** [comment]
Configure Profile -> UI Customization -> Drawer -> Hidden
