### ISSUE TITLE
Doles Ridge Road Limerick: Use addr:city tag for element details

### ISSUE THREAD

**Issue by blackboxlogic** [osmandapp/OsmAnd#10877]
### Description
In OsmAnd, after selecting [node 7172275466](https://www.openstreetmap.org/node/7172275466), the details on the lower part of the screen show "573 Location, Doles Ridge Road, **Limington**". I would expect this element to show the town name **Limerick** since it has `addr:city=Limerick`, _and_ it is within the bounds of the [Limerick relation](https://www.openstreetmap.org/relation/2021418).

### How to reproduce?
* Download offline map "United States Maine"
* Search for address "573 Doles Ridge Road"
* Select the first result in the list (which shows the town name "Limerick")
* Notice that the details of the selected element show town name **Limerick** 👍 
* Un-select the element (by tapping the map in a blank spot)
* Re-select the element (by tapping the element)
* Notice that the details of the selected element show town name **Limington** 👎 

### Your Environment
OsmAnd Version: 3.9.4 from fDroid
Android/iOS version: Android 11
Device model: Pixel 3

**Maps used (online or offline):**   
Offline "United States Maine", edition "Jan 31, 2021"

**Comment by blackboxlogic** [comment]
I found that many "place=hamlet" in my area should be reclassified as "place=neighborhood" (or similar) and I edit the map to fix the local symptoms of this issue. I'm leaving this issue open as I think it would improve OsmAnd.

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd/pull/11150
