### ISSUE TITLE
3.9 Wikivoyage travel guides can't be downloaded

### ISSUE THREAD

**Issue by MakiWolf** [osmandapp/OsmAnd#10875]
### Description
Wikivoyage travel guides can't be downloaded. Since version 3.9.4 download button does not work.

### How to reproduce?

- Open menu
- Select Travel guides (Beta)
- Click on Cointinue
- Click on Download Button

![issue](https://user-images.githubusercontent.com/73300633/107858909-e38ead80-6e36-11eb-8af1-33574ce25458.gif)

### Your Environment
OsmAnd Version: 3.9.4 and latest build from source (13.02.2021, 20:00)
Android/iOS version: 9
Device model: Samsung Galaxy Note 8

**Comment by vshcherb** [comment]
You can still download via Download Maps -> Travel

**Comment by vshcherb** [comment]
Will be fixed in 3.9.7, now available in nightly builds
