### ISSUE TITLE
3.9 Creating new OSM note no longer focuses the text input box

### ISSUE THREAD

**Issue by aceman444** [osmandapp/OsmAnd#10871]
In OsmAnd 3.9, when creating a new OSM note from the map point context menu, the note dialog opens. but the text input box (for the note text) is no longer focused automatically. So the Android keyboard does not popup. I have to click the box to get the keyboard and only then to type the text. This is an unnecessary slowdown, as there is no other widget other than the text box, so focusing it automatically is logical. This is also what happened in all previous OsmAnd releases so this is a regression.
This regression already happened once in older OsmAnd releases (I have reported it), and was fixed quickly in a point release.
Thanks.

**Comment by vshcherb** [comment]
I think it's duplicate but couldn't find it.

**Comment by aceman444** [comment]
Maybe, but it happened again in 3.9, while it wasn't a problem in 3.8. It seems the Add OSM Note dialog was changed in 3.9, it looks differently to 3.8.

**Comment by pietervdvn** [comment]
Yeah, the regression happened due to the very sexy new input box.
Still there on the latest nightly (4.0.0) version - just downloaded it.
