### ISSUE TITLE
Problem with navigation (Splita do Zagreba) exit 25

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#10873]
On the route from Split to Zagreb, navigation does not allow entry to the A1 motorway at the Dugopolje junction (exit 25-Dugopolje), but takes you to another entrance (exit 24-Vučevica).
I think the problem is on the section from the toll booth (exit 25-Dugopolje) to the junction on the A1.
![image](https://user-images.githubusercontent.com/1042025/107855635-e502aa80-6e23-11eb-9fa9-3bf6daf0a307.png)
![image](https://user-images.githubusercontent.com/1042025/107855657-f8ae1100-6e23-11eb-93e6-0fc9e0c5b01a.png)
![image](https://user-images.githubusercontent.com/1042025/107855682-0a8fb400-6e24-11eb-867f-ca7d300b4a27.png)

**Comment by alisa911** [comment]
This has been fixed and will work in the next version of Osmand.
