### ISSUE TITLE
Other bugs to fix, in Osmand 3.9.5:

### ISSUE THREAD

**Issue by riccardopastocchi** [osmandapp/OsmAnd#10883]
Other bugs to fix, in Osmand 3.9.5:

Route from Recanati Via Nazario Sauro 34
in Recanati Via Nazario Sauro 49

https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=43.3973%2C13.5557%3B43.4030%2C13.5608#map=16/43.4002/13.5582

Instead Osmand chooses an alternative path 

![sauro 34 49](https://user-images.githubusercontent.com/78115599/107885882-fa97d300-6efc-11eb-893e-99c99152e05f.PNG)

Osmand 3.9.5
Profile:Car

**Comment by riccardopastocchi** [comment]
From Recanati, Pound 25
in Montefano, Dolly

https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=43.41447%2C13.45058%3B43.41415%2C13.44875#map=18/43.41415/13.44975

Instead Osmand chooses an alternative path 

![IMG_2237](https://user-images.githubusercontent.com/78115599/107886171-85c59880-6efe-11eb-9f8f-570eeb359f10.PNG)

**Comment by riccardopastocchi** [comment]
From Porto Recanati, Via Gramsci, 98
in Porto Recanati, Rosada Camere
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=43.4248%2C13.6641%3B43.4270%2C13.6630#map=17/43.42586/13.66345


Instead Osmand chooses an alternative path 

![IMG_2238](https://user-images.githubusercontent.com/78115599/107886392-cf62b300-6eff-11eb-9692-d6af8d2864d2.PNG)

**Comment by riccardopastocchi** [comment]
From Potenza Picena, Contrada Terranova, 60
in Porto Recanati, Lions Bar

https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=43.4030%2C13.6745%3B43.4074%2C13.6767#map=16/43.4060/13.6754

Instead Osmand chooses an alternative path

![IMG_2239](https://user-images.githubusercontent.com/78115599/107886631-46e51200-6f01-11eb-8f69-a3da0b267cee.PNG)


But also the reverse path from a bug 

![IMG_2240](https://user-images.githubusercontent.com/78115599/107886632-4fd5e380-6f01-11eb-8009-0707b27d3409.PNG)

**Comment by vshcherb** [comment]
What navigation options did you choose? Car, fastest route, avoid highways ?

**Comment by alisa911** [comment]
Will be fixed in 3.9.7

**Comment by riccardopastocchi** [comment]
A curiosity, do I have to continue to report bugs, or it is not necessary, because they will be automatically fixed at the next update? About when will the next 3.9.7 update happen?

**Comment by alisa911** [comment]
Yes, they will be automatically fixed at the next update. But you can keep reporting bugs as they may not be related to this bug. Next update will probably be released by the end of this week.
