### ISSUE TITLE
Xmas values are not imported to OsmAnd

### ISSUE THREAD

**Issue by HubMiner** [osmandapp/OsmAnd#10886]
# 🚀 feature request

### Description
Christmas related tags are not shown on OsmAnd map.
Looking at:
https://www.openstreetmap.org/node/7113717396

OsmAnd view only shows Xmas: opening hours and Xmas: website

Xmas: name value is not searchable in osmAnd.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by HubMiner** [comment]
Additionally, it would be great if objects with reasonable Xmas tags would appear in default map view. Also, possibly create an option or a plug in to disable those.

**Comment by xmd5a2** [comment]
This node contains tag `xmas:feature=lights` which is undocumented in wiki and used only 3 times in entire world. To search by name object should have "main tag". For example, object with `xmas:feature=event` and `xmas:name=*` is searchable by `xmas:name` tag.
