### ISSUE TITLE
Strange OsmAnd car routing issue

### ISSUE THREAD

**Issue by kreuzschnabel** [osmandapp/OsmAnd#10884]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, OpenRouteService, OSRM, etc.)

### Routing Profile

car

### Start and end points

Start point: https://osm.org/node/387001542
End point: https://osm.org/node/5932217006

### Actual and expected routes

Instead of just following the primary highway across the junction, OsmAnd takes a most complicated route to avoid https://osm.org/way/391473775 . I can see no reason why. No other routing engine shows anything unusual here.

![Screenshot_20210214-232712_OsmAnd+](https://user-images.githubusercontent.com/22165960/107891037-7ce3bf80-6f1c-11eb-88ed-a34ea56a6f93.png)

### Is this a regression?

I am not sure, I think I have observed it before.

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

OsmAnd+ 3.9.6 as of 2021-02-09

</code></pre>

**Device and Android/iOS version:**
OnePlus 5T, LineageOS 17.1, latest nightly build

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**
+ OsmAnd live data used for navigation

**Comment by alisa911** [comment]
Will be fixed in 3.9.7

**Comment by kreuzschnabel** [comment]
Just for curiosity: What was the problem?

**Comment by alisa911** [comment]
It was a restriction bug. 
https://github.com/osmandapp/OsmAnd-core/commit/a333a165cd8d43476080ac64194b75dcc64670c7
