### ISSUE TITLE
Crossroad

### ISSUE THREAD

**Issue by ivanPyrohivskyi** [osmandapp/OsmAnd#10887]
# 🐞 routing report

### Routing engine
- OsmAnd's in-app offline routing
### Routing Profile
Car
### Start and end points
https://www.openstreetmap.org/#map=11/49.1498/28.4944
https://www.openstreetmap.org/#map=11/48.3878/31.1799

### Actual and expected routes
https://www.openstreetmap.org/#map=11/49.2125/28.5786

![Screenshot_20210215-102702_OsmAnd~](https://user-images.githubusercontent.com/1040293/107922292-7be07b80-6f78-11eb-8832-7ec6d4c3dbb9.jpg)

![Screenshot 2021-02-15 at 10 29 29](https://user-images.githubusercontent.com/1040293/107922468-b9dd9f80-6f78-11eb-93ca-5808cc7ef509.png)

### Is this a regression?
I do not know

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

3.9.0#4141des from 2021-01-31
</code></pre>

**Device and Android/iOS version:**
Samsung Galaxy M21
Android 10

**Maps used (online or offline):**
Вінницька обл.
Черкаська обл.
Кіровоградська обл.

**Anything else relevant?**
Bug represent only in the route if using several maps.

**Comment by alisa911** [comment]
This has been fixed and will work in the next version of Osmand

**Comment by alisa911** [comment]
If slightly increase the value in the "priority" tag for "trunk_link", the routing will work correctly. This tag is used when calculating road speed. Therefore, after a small increase, the shorter "trunk_link" segment becomes faster than the longer "trunk" segment.

https://github.com/osmandapp/OsmAnd-resources/pull/676
