### ISSUE TITLE
Routing via parking lot instead of primary road

### ISSUE THREAD

**Issue by tommycrock** [osmandapp/OsmAnd#10893]
Strange routing is appearing for me using the standard offline car routing:

![Screenshot_20210215-065837_OsmAnd+](https://user-images.githubusercontent.com/5749884/107945513-a554d380-6f87-11eb-9734-b3f599b257d8.jpg)

 that doesn't show on other routers (OSRM / GraphHopper). https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=53.87124%2C-1.70726%3B53.87329%2C-1.71138#map=16/53.8724/-1.7092
The osmand router is taking me a long way round to come off the primary road, into a parking lot and back out rather than straight. No turn restrictions should limit straight on. The only advantage in the parking lot I can see is a smoothness tag. I can add a speed limit and give way that may make this less likely but it still seems wrong on available data.

**Comment by alisa911** [comment]
Will be fixed in 3.9.7
