### ISSUE TITLE
Support WikiVoyage listing type Go

### ISSUE THREAD

**Issue by ArjanOnwezen** [osmandapp/OsmAnd#10901]
# 🚀 feature request

### Description

Please support WikiVoyage listing type **Go** (next to the already supported types, like eat & shop) with a separate color and icon on the map.

### Describe the solution you'd like

Add for listing type **Go** (usually used for bus and train stations, airports, etc.) a separate color and icon on the map.

**Comment by Dima-1** [comment]
https://github.com/osmandapp/OsmAnd-tools/pull/428
https://github.com/osmandapp/OsmAnd-resources/pull/709

**Comment by Dima-1** [comment]
https://github.com/osmandapp/OsmAnd-tools/pull/430
