### ISSUE TITLE
No GPS signal

### ISSUE THREAD

**Issue by Arrdiss** [osmandapp/OsmAnd#10903]
### Description
When I start an app on Android there is no GPS signal. In other apps it starts location services or something. But OsmAnd doesn't do it. There is no notification that device starts to search for satellites like it happens when I open other apps.
I don't know  whats wrong, in every other apps GPS works just fine.

### Steps to reproduce
Just start OsmAnd.

### Your Environment
OsmAnd Version:  3.9.6
Android/iOS version: Android 10 (LineageOS 17.1 no Google Services)
Device model: Oneplus 6

**Maps used (online or offline):**   
No problem with maps

**Comment by scaidermern** [comment]
Same issue as #10637?

**Comment by Arrdiss** [comment]
It look similar but I have F-Droid version installed and GPS doesn't even turn on

**Comment by Arrdiss** [comment]
I've downloaded binary from official site and when I click on the file OsmAnd app opens and shows this error 
![Screenshot_20210216-111559_OsmAnd~](https://user-images.githubusercontent.com/57405986/108049305-62a70000-7048-11eb-9435-9c55f4f87bdb.png)

**Comment by Arrdiss** [comment]
I've solved it. Now F-Droid version runs ok

**Comment by scaidermern** [comment]
Great! Can you tell us the cause of the problem and how you fixed it?

**Comment by Arrdiss** [comment]
I had app from Aptoide. It probably requires Google Services. Then I installed app from F-Droid version and nightly version from official site. Both work great, GPS fix is fast and precise out of the box. [#10637 ](https://github.com/osmandapp/OsmAnd/issues/10637) helped me a lot. Thanks!
