### ISSUE TITLE
Show tracks: don't change color automatically on OK

### ISSUE THREAD

**Issue by Kivasya** [osmandapp/OsmAnd#10904]
The most recent update to 3.9 messed up something with track colors.

There are a dozen track files, each with a different color to distinguish what kind of track it is. There is also an extension tag added to the top of the gpx file, so OsmAnd displays the color automatically. It looks like this:

<metadata>
<name>OffTrail</name>
</metadata>
<extensions>
<color>#80ff0000</color>
</extensions>
<trk>
<name>Snowmobile</name>
<desc>This is track no: 15</desc>
<trkseg>

It looks like the custom coloring methods added to 3.9 have invalidated all track colors, because now all tracks are displaying in the default color.

**Comment by dmpiq** [comment]
Update to clarify and include code:

I maintain a dozen different tracks, and I add code to the GPX file to color the tracks in OsmAnd. 

`<metadata>
<name>OffTrail</name>
</metadata>
<extensions>
    <color>#80ff0000</color>
</extensions>
<trk>
<name>Snowmobile</name>
<desc>This is track no: 15</desc>
<trkseg>
`

Since the 3.9 update, OsmAnd no longer recognizes the color code, and all of my tracks show up as the default color.

**Comment by dmpiq** [comment]
Additional question:  Is there any way I can also specify dashed lines and line weight in the gpx file?

**Comment by vshcherb** [comment]
Please attach any gpx-file, so far we didn't manage to reproduce.

**Comment by vshcherb** [comment]
dashed-lines are not possible for now.

**Comment by dmpiq** [comment]
[Brown-21.01.txt](https://github.com/osmandapp/OsmAnd/files/6044471/Brown-21.01.txt)

Attached is a short file of brown tracks.  I renamed the extension from .gpx to .txt for purposes of attaching it on git.

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/109220334-13d03780-77b9-11eb-9250-3823a70ec3bd.png)

**Comment by dmpiq** [comment]
I installed the free version of OsmAnd and it is, indeed, working fine.  OsmAnd+ is where I'm having the issue.

I deleted and reinstalled OsmAnd+ and it's still coloring all if my tracks the default color.

**Comment by dmpiq** [comment]
It was fine in the free version until I went in and changed the line weight.  It then put all of my tracks in the default color.

And then even with uninstalling and installing the free version, it's still doing it.

So it has something to do with changing the line weight, and then it's storing something even after delete and reinstall.

**Comment by dmpiq** [comment]
OK, upon further investigation here is what I've found:

Once I tried to change the line weight in 3.9, it changed all the track colors to the default and I could not get them back.  I tried deleting OsmAnd's cache and data, then uninstalling and reinstalling, and it was still coloring all of the tracks the default color.

The only way I was able to get my track colors back again is to install 3.8 (free version.)

**Comment by vshcherb** [comment]
that's so weird... I don't know what to say. Free and + versions should be identical, probably you can try one of nightly builds or probably you downloaded weird 3.9 plus version.

**Comment by dmpiq** [comment]
I would guess that it has something to do with the custom colors for favorites and waypoints that was added in 3.9.

**Comment by vshcherb** [comment]
doesn't explain why we can't reproduce

**Comment by dmpiq** [comment]
Here is how to reproduce the issue.  It's a problem even if you use OsmAnd's built-in track coloring:

1. Put a track file in your files/tracks folder.
2. In OsmAnd, go to Configure Map -> Tracks and select the track you just loaded.  Track will load in default color.
3. Go to My Places -> Tracks  and select the track you loaded
4. Select the color palette icon and give the track a custom color.  Hit Apply.
5. Now go back to Configure Map -> Tracks and look at your list of tracks.  
6. Without changing anything, just hit "ok" to back out of the tracks list.
7. Your track will return to the default color.

I have attached a track file for test usage, it has no custom color specified.  Rename to .gpx extension to use.
[testOsmand.txt](https://github.com/osmandapp/OsmAnd/files/6214753/testOsmand.txt)

**Comment by vshcherb** [comment]
Yes, indeed that's a bug.
