### ISSUE TITLE
Issues new GPS recording dialog

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#10924]
# ToDo
- Hitting 'Save' on the mew dialog displays the wrong filename in the popup, it is missing the recording time. (But the file name actually used is correct).
Redesign suggestion (combine save actions and dangerous actions)..

Dangerous actions:
- Clear current recorded data
- Stop without saving.

Save actions:
- Save & continue recording
- Save & stop recording

4 actions overall:
Pause / Resume
Save
Clear / Remove
Start new segment

**Comment by pebogufi** [comment]
The current build  with my recommendation

- Clear current recorded data (ok)
- Start new segment (ok)
- Pause. (ok, move up)
- Save.  ---> Save and Stop
- NEW: Save and continue recording
- Stop. --> Stop without saving, (red) with confirm-dialog
- Close. (ok)
 
Remove the currently used  second window after stop. (stop without saving + stop and save)

**Comment by sonora** [comment]
I see these issues currently:

[1] All 'Stop without saving' definitely require a confirmation dialog,  unless we decide to simply not offer such a dangerous choice in the first place.

[2] Bloated user guidance': We now require 4 taps to stop recording with saving for any user chosing this route 
-    tap the widget
-    tap 'Stop'
-    tap 'Save and stop recording'
-    tap 'Close'

We should reduce to 2.

[3] After you start a recording,  the option screen for the interval etc. pops up. After confirming that, a second option screen offering to stop the recording etc. pops up. This screen is useless at this time.

[4] This second option screen now also uselessly pops up after some actions under MyPlaces/tracks, e.g. if you deleted a track there and then exit via the device's back button (while no track is even being recorded)

**Comment by dmpr0** [comment]
Also, the dialog doesn't ask for location permission.

**Comment by Ungoose** [comment]
Some issues with the new dialog (feels more like a dashboard, btw):

1. There's now an extra step for starting the trip recording. After I tap the widget, I see another menu where I have to tap "start recording" again (there is an "always ask" toggle which I turn off but it doesn't help).

2. Once the recording starts, I am presented with a massive dashboard that I have no use for in the beginning of the recording (aside from maybe canceling the erroneously started recording - which, ironically, is the only option that is absent).

3. The "save and stop recording" is hidden behind the "stop" button which seems to serve no other purpose than saving the track. Weirdly, it displays a warning that all unsaved data will be lost but there seems to be no way for doing so - you can either save or "cancel" (which probably should be named "back" as it simply returns to the previous screen and resumes the recording). Meanwhile, there are three other buttons in the dashboard - start new segment, clear recorded data, and save (but continue recording). I personally never use either of these but I can imagine starting new segment is something you'd want as much within reach as possible during the trip. The "save" I don't really get - I don't see a reason to save a track that I want to keep recording, but other people do as seen from #10105 
The "clear recorded data" looks like an elaborate way to cancel the recording then immediately start a new recording (which is what I'd rather do in such a situation) but again, probably important for someone. What surprises me is it is within a single tap's reach despite being described as "dangerous".

4. There's no "cancel recording" button. I understand it's considered a threat to data safety but, in all honesty, I'd rather opt for another nagging confirmation dialog than having to save an erroneously started recording then going through tracks trying to understand which one I should delete (another thing Osmand is not good at).

1 and 2 look like a bug and an oversight. Regarding 3 and 4, I'm in favor of the 4-point control scheme suggested by vshcherb above:

Pause / Resume
Save
Clear / Remove
Start new segment

("clear" being either "clear recorded data" or "cancel", which are essentially the same thing only with "keep recording" being on or off)

Regarding the recording stopping after save - I'm actually in favor of the "keep recording" toggle on the "save track" dialog proposed by AntiSol in #10105, as I'm under impression that most users will just prefer one and not care about the other. I personally feel that "keep recording" is a niche option that is less frequently used, but that's just me, of course.

**Comment by sonora** [comment]
Not to sound too destructive here ;) , but I sonetimes wonder if we spend our developer resources on the right problems. After seeing all this,  is there ANYTHING in the first place we improved with this particular activity?

Plus, the implementationand concept  is technically full of obvious bugs, big obvious ones and smaller ones like  #10996.

**Comment by tommycrock** [comment]
> After seeing all this, is there ANYTHING in the first place we improved with this particular activity?

Personally, I'm really glad that we can change track visibility from the recording dialogue. That seemed to be tucked in a very dark corner before.

**Comment by Ungoose** [comment]
My favorite example of how track recording is handled is [OpenTracks](https://github.com/OpenTracksApp/OpenTracks) - a brilliant tiny FOSS app. 

Before the recording starts, there's a single REC button and a greyed out Stop button at the bottom:

https://github.com/OpenTracksApp/OpenTracks/blob/main/fastlane/metadata/android/en-US/phoneScreenshots/screenshot1.png

Once you tap REC, it turns into a Pause button, so you have Pause and Stop.

https://github.com/OpenTracksApp/OpenTracks/blob/main/fastlane/metadata/android/en-US/phoneScreenshots/screenshot2.png

The Stop has to be held down and will save the track every time, no questions asked. The saved track can then be deleted if necessary. All additional actions (add GPX waypoint, add media note, etc) are smaller buttons at the top of the screen, and the midde displays the information about the recorded track.

Beautiful.

**Comment by tommycrock** [comment]
>     4\. There's no "cancel recording" button.

This seems a problem to me too. With the array of buttons now available I had tried the 'stop' but it didn't work so I had cleared the data, which kept recording, so I paused it and cleared the data. Later I wondered why I couldn't get rid of the trip recording notification and why location services were being kept open, even when I force closed osmand+. I restarted my phone to kill it! Worse, having killed osmand+ there is no sign that anything was ever recording so no hint as to why it is being held open.

**Comment by Ungoose** [comment]
> 
> 
> Not to sound too destructive here ;) , but I sonetimes wonder if we spend our developer resources on the right problems. After seeing all this, is there ANYTHING in the first place we improved with this particular activity?
> 
> Plus, the implementation and concept is technically full of bugs, big obvious ones and smaller ones like #10996.

Sorry to sound too critical, I appreciate the work and I agree with tommycrock here - the new menu is an improvement, there's just some rough edges to fix and we do end up with a better control panel. 

> 
> 
> > ```
> > 4\. There's no "cancel recording" button.
> > ```
> 
> This seems a problem to me too. With the array of buttons now available I had tried the 'stop' but it didn't work so I had cleared the data, which kept recording, so I paused it and cleared the data. Later I wondered why I couldn't get rid of the trip recording notification and why location services were being kept open, even when I force closed osmand+. I restarted my phone to kill it! Worse, having killed osmand+ there is no sign that anything was ever recording so no hint as to why it is being held open.

Yes, the only way to end the recording is to tap "stop" then "save and stop recording." Now that I think of it, we might actually do without the "cancel" button. As long as there is a convenient "Stop and Save" action, I don't mind going to "My tracks" and deleting the track later. So both dangerous actions can actually be removed - they regularly raise concerns about data loss.

My recommendation is:

- Clear recorded data (can be removed - a dangerous action)
- Start new segment (can be removed or moved next to the "show on map" as an icon)
- Save (can be moved next to the "show on map" as a save icon)
- Pause (ok)
- Stop (ok but should save and stop recording with a long tap instead of a confirmation)
- Close (can be removed)
This way we can trim the menu and make it less in obstructive and more intuitive: 
![rrr](https://user-images.githubusercontent.com/59472193/109213619-7d504600-77b9-11eb-85ca-6c274c73f325.jpg)
(icons for "save" and "start new segment" not included)

**Comment by tommycrock** [comment]
Stop doesn't stop or save when paused. It goes through the motions but leaves the track recording paused and unsaved. So if you've paused your recording I don't think there's a way of saving it and ending the recording without adding a new bit of track (resume, 'stop', stop and save)

**Comment by vshcherb** [comment]
Not sure we're going to pick up all conversations going on here but it's definitely going to be v2 in OsmAnd 4.0. We hope to present small important changes next week.

**Comment by tommycrock** [comment]
I'm in favour of keeping clear recorded data (clear and continue). It's useful for starting up and holding the satellites before starting your recording proper. I'd like to see cancel too.

**Comment by Ungoose** [comment]
> 
> 
> I'm in favour of keeping clear recorded data (clear and continue). It's useful for starting up and holding the satellites before starting your recording proper.

That does sound useful. My point is, it would be great to keep the menu slim by reducing the number of rows with buttons to 2 or 3 from the current 5. One way to do that could be by leaving the bottom one to Pause and Stop and add all less common ones (clear, cancel, start new segment, etc.) to the top row alongside the Show on map and Appearance configuration buttons. 



> 
> 
> Not sure we're going to pick up all conversations going on here but it's definitely going to be v2 in OsmAnd 4.0. We hope to present small important changes next week.

Thank you! It would be great to have there 4 issues addressed (looks like the first one already is):

> 
> 
> I see these issues currently:
> 
> [1] All 'Stop without saving' definitely require a confirmation dialog, unless we decide to simply not offer such a dangerous choice in the first place.
> 
> [2] Bloated user guidance': We now require 4 taps to stop recording with saving for any user chosing this route
> 
>     * tap the widget
> 
>     * tap 'Stop'
> 
>     * tap 'Save and stop recording'
> 
>     * tap 'Close'
> 
> 
> We should reduce to 2.
> 
> [3] After you start a recording, the option screen for the interval etc. pops up. After confirming that, a second option screen offering to stop the recording etc. pops up. This screen is useless at this time.
> 
> [4] This second option screen now also uselessly pops up after some actions under MyPlaces/tracks, e.g. if you deleted a track there and then exit via the device's back button (while no track is even being recorded)

Also, as tommycrock pointed out, the paused track should probably be saved without the need to resume it.

**Comment by sonora** [comment]
Regarding "_...holding the satellites before starting your recording_ ": That use case seems a little unclear: Please note that the device location service is engaged, will deteemine a loocation fix, and keep it locked already by merely having OsmAnd show the map scrren. Any additional recording with data you inend to later discard will not create any benefit at all?

**Comment by tommycrock** [comment]
Sorry for the lack of clarity @sonora. The use case involves putting the phone in my pocket so wanting the screen off. Otherwise I have to have my phone out for 30 seconds or a minute waiting for the best lock. Alternative approaches to this welcome

**Comment by vshcherb** [comment]
The redesign is going to continue and new changes will be provided tomorrow.

**Comment by bigfatfrog67** [comment]
Personally I think the changes that have been made make this app almost impossible to use for recording gpx in a vehicle, especially considering the phone is in landscape. I shall probably be stopping subscribing to this app.

**Comment by Ungoose** [comment]
> 
> 
> The redesign is going to continue and new changes will be provided tomorrow.

Just checked the updated menu and it looks amazing! Less clutter, fewer taps, more options, and more convenient to use than the previous one. Also, the option for disabling the confirmation dialog finally works (although I think "Quick start" would be a more appropriate name than "Show start dialog").
One issue remains, though: Starting the recording still brings up the menu that, in most cases, is not needed right away and requires one more tap to return to map. And yes, the menu does look broken in landscape. 

It would also be great to have a way to hide or collapse the chart and the Overview/Altitude/Speed panel - they are take a lot of space and are not as essential during movement as disance and time span.

Thanks for making OsmAnd better!

**Comment by Ungoose** [comment]
Two more suggestions: 
1. The "Close" button (to the left of "Pause") should be called "Close." It doesn't cancel anything - it just closes the menu, and "cancel" sounds more like "Stop without saving."
2. The "Options" button (to the right of "Finish") should probably be called "More" or "Advanced," which would better reflect its contents.

**Comment by dmpr0** [comment]
> Personally I think the changes that have been made make this app almost impossible to use for recording gpx in a vehicle, especially considering the phone is in landscape. I shall probably be stopping subscribing to this app.

Hi! We will fix the landscape layout, we planned to place it on the right side so both menu and map will be visible.

**Comment by Ungoose** [comment]
> 
> 
> > Personally I think the changes that have been made make this app almost impossible to use for recording gpx in a vehicle, especially considering the phone is in landscape. I shall probably be stopping subscribing to this app.
> 
> Hi! We will fix the landscape layout, we planned to place it on the right side so both menu and map will be visible.

Sounds cool, thanks! Hope the rest will be fixed as well.
