### ISSUE TITLE
POI description is not displayed correctly

### ISSUE THREAD

**Issue by Kivasya** [osmandapp/OsmAnd#10920]
App OsmAnd+ Version 3.9.6 on two devices:

- Tablet Huawei Mediapad M3 8.4
- Smartphone Xiaomi Redmi Note 8 Pro

Both have exactly the same settings.

On the tablet everything works fine: A short touch of a POI-symbol and the descripton of the POI (e.g. restaurant infos) pops up. A long touch to the map marks a new map point.

On the smartphone a long touch also marks just a point on the map. But a short touch on a POI-symbol ends up in an error message shown on attached screenshot.

![Screenshot_2021-02-16-12-05-07-132_net osmand plus](https://user-images.githubusercontent.com/75778939/108208201-6498be00-7131-11eb-9776-67d05b1703fe.jpg)

**Comment by scaidermern** [comment]
Check Plugins -> Accessibility -> Accessibility mode and set it to off, or disable the Accessibility plugin completely.

**Comment by vshcherb** [comment]
Yes looks like accessibility plugin issue.
