### ISSUE TITLE
No settings saved when using multiuser storage data location

### ISSUE THREAD

**Issue by JonnyTech** [osmandapp/OsmAnd#10928]
### Description

I am in the UK and although the default length measurement is miles, I prefer kilometers. After changing units of length to kilometers/meters it subsequently resets back to miles/meters.

### How to reproduce?
- configure profile >> general settings >> units of length >> **kilometers/meters**
- apply >> apply to all profiles
- keep units of speed set to **miles per hour**
- plan a route
- no other changes of settings from defaults

The route will start as kilometers/meters but at end of route or at intermediate destinations it will revert to miles/meters. Therefore every time the app restarts or a new route/stop is required then one must change the units of length again.

### Your Environment
OsmAnd Version: 3.9.4 from F-Droid
Android/iOS version: Android 9
Device model: Nokia TA-1032

**Maps used (online or offline):**   
Offline United Kingdom England

**Comment by JonnyTech** [comment]
Upon further investigation it seems that none of my settings are saved. Suspect that it is the location of the data storage folder:

![img_5](https://user-images.githubusercontent.com/3584732/108610519-0dfbe000-73ce-11eb-9d86-12e3f4eabe7b.jpg)

**Comment by vshcherb** [comment]
I think the issue was fixed in 4.0
