### ISSUE TITLE
Need "distance" tag added to rendering_types.xml

### ISSUE THREAD

**Issue by Prusaker** [osmandapp/OsmAnd#10923]
Could you please change rendering_types.xml to add a "distance" tag for highway=milestone?

Now:
tag="highway" value="milestone"  minzoom="15"

Need:
tag="highway" value="milestone" nameTags="distance" minzoom="15"

This is necessary so that the inscription on the kilometer mark can be displayed on the screen in a custom rendering style.
Thanks in advance.

**Comment by vshcherb** [comment]
welcome
