### ISSUE TITLE
Some streets in Pfäffikon are not displayed in OsmAnd, shown in OSM

### ISSUE THREAD

**Issue by Kivasya** [osmandapp/OsmAnd#10921]
some addresses in Pfäffikon Zurich are not found using the search button with entering the city name and the street name. See screenshot attached.

Eg.: Wallikerstrasse is found but Bergstrasse or Bodenackerstrasse is not found.
On the device installed the version 3.9.6 with the latest map of Switzerland.

Checked the addresses in OSM.ORG, and the address is found.
https://www.openstreetmap.org/search?query=Bergstr%20Pf%C3%A4ffikon%20zh#map=18/47.37553/8.78981

![Screenshot_20210216-205735_OsmAnd+](https://user-images.githubusercontent.com/75778939/108214260-a2e5ab80-7138-11eb-9450-6aed0bf3258c.jpg)

**Comment by xmd5a2** [comment]
This street can be found in Berg neighbourhood: "Bergstrasse Berg".
```
			'Bergstrasse (Berg)' [34414], 6 building(s), 0 intersections(s)
				Buildings:
				17
				19
				21
				22
				24
				26
```

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-tools/pull/388

**Comment by ivanPyrohivskyi** [comment]
Quote from [Trace Address Search Issues](https://docs.osmand.net/en/main@latest/development/algorithms/trace-address-search-issues):
"_OsmAnd searches for relations where admin_center / admin_centre refers to a node with place = city, town, village, etc.
Otherwise, the link is checked for an exact match of the name._"

Name of boundary "_Pfäffikon_" is not equal name of admin_centre "_Pfäffikon ZH_".
Added tag place to https://www.openstreetmap.org/relation/1682189

**Comment by ivanPyrohivskyi** [comment]
Fixed [Pfäffikon relation](https://www.openstreetmap.org/relation/1682189), added tag place=village
See [Issue: street or house is found in another city or without](https://docs.osmand.net/en/main@latest/development/algorithms/trace-address-search-issues#issue-street-or-house-is-found-in-another-city-or-without)

**Comment by vshcherb** [comment]
https://docs.osmand.net/en/main@latest/development/algorithms/trace-address-search-issues#possible-causes

**Comment by Hb-** [comment]
The description moved to https://www.osmand.net/docs/technical/algorithms/trace-address-search-issues

Open question is, if both of this two conditions are required or only one:

- Boundary should have a relation member label, admin_centre or admin_center pointing to a place-node.
- Boundary should have exact same name as place-node

**Comment by vshcherb** [comment]
Only one is enough but 1st is preferred.
