### ISSUE TITLE
Navigate directly to end of track to trim

### ISSUE THREAD

**Issue by mysigninname** [osmandapp/OsmAnd#10939]
When completing a ride I frequently like to crop the start and the end of the recorded track prior to uploading the track to a cloud service. This is to hide my home location.

When entering the edit track section of my latest recorded track I can remove the points at the start of the track quite easily. I look to see if, where the points are showing, there is any speed data. If there isn't I can assume that is my home location...I then scroll down until some speed data appears and look to see where the speed data is a reasonable pace. I then select that point and select 'Trim before'. However there is no easy way to get to the end of the track without having to scroll through all the points until I arrive at the end. That takes ages. I then use a similar process but 'Trim after'. So, I would like to see, perhaps in 'Options' in the Points page, a button that enables the ability to 'Go to end of Track'. This would speed things up no end when cropping both ends of a recorded track. I tried reversing the track but this method didn't seem to work for me.

I don't really think the points selection method is the quickest way a track could be trimmed as there are always so many points. Solutions other websites and one android app I can think use is to allow the ability to interactively scroll through the profile of a  track at beginning and then at end and then Crop track can be selected to delete the unhighlighted areas of the profile. 

So, with OSMAnd perhaps when clicking on an area of the track profile, within the Graph tab (next to the Points tab), this action also selects the corresponding Point. At the moment selecting an area of the graph does not show the corresponding point within the Points tab. Then, when clicking on the Points tab shows that selected Point at which point Trim After/Before could be selected. Pressing Done then finalises the cropping change.

**Comment by vshcherb** [comment]
You can select points on the map, it's much quicker and precise

**Comment by mysigninname** [comment]
How does one move to the end of the track, via the points list, without having to laboriously scroll through the entire list of points?

**Comment by mysigninname** [comment]
OK I see how that works now after another attempt at selecting the Points. Very similar to RideWithGPS in that respect, which I like! Thank you.

**Comment by mysigninname** [comment]
With respect to the 'Nice to have' feature of the graph position corresponding to the Point within the Points list shall I close this down?
