### ISSUE TITLE
[bug] Can't install  OsmAnd-android-full.apk since the latest builds

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#10949]
### Description

Can't install 
https://download.osmand.net/latest-night-build/
OsmAnd-android-full.apk

The latest version, which was ok is
OsmAnd~ (2)  4.0.0#31565m.apk. 2021-02-19
With later version (tried 3 versions: ?, 31571, 31573) i get the message: Can't install...

### Your Environment
OsmAnd Version: see above
Android version: 10
Device model: Samsung tab S5e

**Comment by pebogufi** [comment]
I think i understand the problem: 
last version I had. OsmAnd~ (2)  **4.0.0**#31565m.apk 2021-02-19
current vefsion: OsmAnd~ (2)  **3.9.0**#31573m.apk  2021-02-19
... and now, what can i (and all testers of nightly builds ) do ?

**Comment by sonora** [comment]
Here's the culprit: https://github.com/osmandapp/OsmAnd/commit/a3b4796610a9d7ccbc3b97c6dbc30a56df33c8e5

Not sure why the version was downgraded...

**Comment by MAlfare** [comment]
> OsmAnd Version: see above
> Android version: 10
> Device model: Samsung tab S5e

Same problem:
Android 8.1
Motorola G4
Android 4.4
Lenovo Tablet

`Here's the culprit: a3b4796`
As it seems to affect everyone, what can be done by the user?
Is to wait the only option?

**Comment by sonora** [comment]
That commit needs to be reversed

In the interim the only workaround I can think of is an uninstall of the previous version before you install the new one, but be **careful** to not alose all your OsmAnd data files and maps. It is very tricky, e.g. backup everything before or rename the data folder.

**Comment by pebogufi** [comment]
Thanks to all for this very fast response.
