### ISSUE TITLE
Increase Announcement Time Does Not Increase Turn Prepare/Approach Time

### ISSUE THREAD

**Issue by mathys-lab** [osmandapp/OsmAnd#10959]
### Description
Increasing "Announcement Time" does not increase the time and distance intervals for Turn Prepare or Turn Approach. This becomes an issue while driving on the freeway because there is not enough time given to allow you to safely merge through traffic to take an exit. The navigation prompt only gives you a 0.4 mile notice before your exit, even if you have been driving on the freeway for many miles. Setting this to "Early" should give you a 1 or 2 mile heads up before it gives you the standard 0.4 mile notice, etc.

### How to reproduce?
Go to Settings > Configure profile > Configure Driving profile > Navigation Settings > Voice Prompts > Announcement time > expand Time and distance intervals.

Change from Normal to Early and you will see that the Turn Prepare and Turn Approach time and distance intervals do not change.

### Your Environment
OsmAnd Version: 3.9.6
Android/iOS version: Android 10
Device model: Samsung Galaxy S9

**Maps used (online or offline):**  Offline
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by sonora** [comment]
Which voice have you selected?

Please note that some voices have been tweaked to reduce chattiness by intentionally suppressing the 115 second (roughly 1 mile) advanced warning, are you not getting that one?

We also have an additional  5 minute advanced warning, but it is now suppressed for car travel, most users felt this was much too chatty or distractive.

**Comment by mathys-lab** [comment]
Under Navigation Settings > Voice Prompts, I have Voice Guidance set to TTS English.

Is there another location to select more voices?

**Comment by sonora** [comment]
TTS voice English should be fine. You sure you never hear any announcement further out than 4 tenths of a mile?

**Comment by mathys-lab** [comment]
I just tested it driving on some local roads and it gave me a notification at 0.9 miles which is acceptable in my opinion. I'll try it on the freeway where I had the issue next chance I get and will let you know if it is working correctly now.

**Comment by sonora** [comment]
Ok, thanks for testing! If there is any particular route or place: if you care to share the coordinates I can try a simulation myself to see how it performs under those particular circumstances. But it is always better to do some ground truth testing on location ... ;)

**Comment by vshcherb** [comment]
Yes it's done on purpose so only default speed affects these settings - https://docs.osmand.net/en/main@latest/development/algorithms/voice-prompt-triggering.
