### ISSUE TITLE
Navigation: Error number of exit in a roundabout on toll roads

### ISSUE THREAD

**Issue by feuilledegui** [osmandapp/OsmAnd#10958]
Hello,
(my English is not very good)

### Description
Bad exit number in the circle diagram of a roundabout (at the top on the left during the navigation) (and next to a toll roll), and bad exit number in the description of the navigation.

### How to reproduce?
Create a navigation with the option "Avoid toll roll" activated. Choose a route with a roundabout including an exit with the tag "toll=yes". Be sure this exit is before the exit proposed by the app. 
The plan is correct, but in the description and the roundabout diagram, the exit's number you should go is reduced by the number of exit including "toll=yes" tag.
When the option "Avoid toll roll" is not activated, there is no issue.

### Your Environment
OsmAnd Version: 3.9.6
Android/iOS version: Android 8.1.0 (LineageOS 15.1 with micro-G)
Device model: Nexus 5X (Bullhead)

### Maps use 
Offline, but the problem is reproducible at many roundabout (for example in France : https://www.openstreetmap.org/#map=19/48.82270/-0.13089)

Thank you very much

**Comment by martenjj** [comment]
See also #10028 for another roundabout exit problem, but this time counting exits that should not be.

**Comment by feuilledegui** [comment]
I toke screenshots to explain this bug (using 3.9.10 version) :

Without Avoid Toll Roll
![Screenshot_20210325-142534_OsmAnd~without_avoid toll roll](https://user-images.githubusercontent.com/75205749/112518120-60e40100-8d99-11eb-9722-89ed86266ad5.png)

With Avoid Toll Roll
![Screenshot_20210325-142521_OsmAnd~with_avoid toll roll](https://user-images.githubusercontent.com/75205749/112518133-63def180-8d99-11eb-9a15-74be2596cd7e.png)

**Comment by Eyap53** [comment]
I got the same problem today, very disturbing.

Also, this issue is also related : #12438.

I think this issue should be re-opened (otherwise, please explain your reasons for keeping it that way). Thanks !

**Comment by vshcherb** [comment]
The issue has been fixed in 4.1 and release should be out this or next week

**Comment by Eyap53** [comment]
Oh, great news ! Sorry I saw the "Closed" state of the related PR and jumped to conclusion.
Thanks for the reply, and the hard work :)
