### ISSUE TITLE
Turn-by-turn voice guidance isn't working

### ISSUE THREAD

**Issue by lichingyun** [osmandapp/OsmAnd#10955]
### Description
Hello I am using the latest version of OSMamd~ from Fdroid.
All works well execpt the Turn-by-turn voice guidance.
OSMand~ is totally mute.

### Your Environment
OsmAnd Version: 3.9.6 from Fdroid
Android/iOS version: Android 11 ArrowOS
Device model: Xiaomi Redmi Note 5 Whyred

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by sonora** [comment]
This will be hard to debug unless you specify a lot more detail...

Possible causes include:
- voice selected?
- output channel correct?
- are you perhaps accidentally re-routing to some bluetooth output?
- is the correct volume setting up?
- Is the profile's mute setting selected?

Has it ever worked on that device, and have you investigated what you changed before the issue started?

You may temporarily activate the Development plugin and experiment with 'Test voice prompts', maybe post the results of test button 11.1 here.

**Comment by vshcherb** [comment]
Situation is not clear what to fix
