### ISSUE TITLE
Map mode night issue

### ISSUE THREAD

**Issue by MakiWolf** [osmandapp/OsmAnd#10954]
### Description
When using map mode night values on details page are not shown, because there is a black background with a black font. To solve that I think you should make a white color for the text on night mode.
**Map mode night:**
![grafik](https://user-images.githubusercontent.com/73300633/108592859-54baed00-7370-11eb-9ed0-b0fc1d2d8d86.png)
**Map mode day:**
![grafik](https://user-images.githubusercontent.com/73300633/108592873-6f8d6180-7370-11eb-8451-028ec945c843.png)

### How to reproduce?
Open Menu
Configure map
Scroll down to map rendering
Select map mode Night
Calculate a route to have a details page

### Your Environment
OsmAnd Version: 3.9.6 and latest build from source code (20.02.2021)
Android/iOS version: 9
Device model: Samsung Note 8

**Comment by sonora** [comment]
I guess you are talking 'App theme=dark', not 'Map mode=night'?

In any case, at least the latest versions all work for me on other Samsung devices both under Android 9 and 10, so maybe an issue with your particular setup or compilation?

**Comment by MakiWolf** [comment]
Thanks for answer. I use version 3.9.6 from Fdroid and  androidFullLegacyFatDebug as build variante from source code. I also have created a .gif image below to see this in my case.
![issue](https://user-images.githubusercontent.com/73300633/108621928-ffe1aa00-7435-11eb-9520-793f3147de3a.gif)
And I have also seen now that there is a second setting for app theme dark, but also this doesn't work. Also see it in the .gif image below. The difference I have seen between App theme=dark and Map mode=night is what I have seen that one time also the map is dark.
![issue](https://user-images.githubusercontent.com/73300633/108622025-8bf3d180-7436-11eb-920d-4d8592e053e1.gif)

**Comment by sonora** [comment]
Ah, that's right, seems we switch to dark theme now also when the map is in night mode.

In any case, I have checked several devices already and have not yet been able to reproduce, so either it is fixed in our 3.9.8, or it affects only certain systems.

**Comment by MakiWolf** [comment]
Thanks for answer. I have also checked this now and come to the result that on Samsung Note 8 it worked when under settings dark mode is enabled. I also tested it on a virtual device Pixel 4 API 30 from Android Studio Emulator and there it also doesn't work when under device settings > Display > Dark theme is enabled.
In conclusion I would say that as a temporary workaround on Samsung Note 8 devices you can activate dark mode under the device settings. Not to have that issue. But it aslo should be a white color when not using dark mode on Samsung Note 8 and the app in Driving profile has automatically changed it to Night mode, because then is the issue on Samsung Note 8 devices.

**Conclusion:**

**Samsung Note 8 with Android 9:** I have found a workaround
**Samsung S9+ with Android 10:** the same workaround doesn't work
**Pixel 4 API 30 from Android Studio Emulator:** the workaround also doesn't work

These are this devices I have tested.

Hope someone have a clue about it, because it is very difficult to fix it with these many configurations and devices.
