### ISSUE TITLE
Compass points in wrong direction when flipping screen

### ISSUE THREAD

**Issue by Unrud** [osmandapp/OsmAnd#10961]
### Description

The value of [`currentScreenOrientation`](https://github.com/osmandapp/OsmAnd/blob/48cbd60dc71d7ea42e7ccb7355f6000d2ddc90e7/OsmAnd/src/net/osmand/plus/OsmAndLocationProvider.java#L122) in OsmAndLocationProvider is only updated from MapActivity::onCreate.

When the screen orientation changes by 90 degrees and the device changes from Landscape to Portrait mode or vice versa, the activity gets recreated and it works fine.

When the screen orientation changes by 180 degrees and the device stays in Landscape or Portrait mode, the activity does not get recreated. The value of `currentScreenOrientation` of OsmAndLocationProvider is not updated and the compass points in the wrong direction.

### How to reproduce?

Tilt device to change screen orientation by 180 degrees without switching between Landscape and Portrait mode.
The compass points in the wrong direction.

https://user-images.githubusercontent.com/11810547/111071983-e97cba80-84d8-11eb-9e17-9fb427c55a04.mp4

### Your Environment
OsmAnd Version: 3.9.6
Android/iOS version: Android 9

**Comment by vshcherb** [comment]
We need to check with different screen orientation:
- Markers direction 
- Context menu arrow
- Favorites list arrow
- Compass mode (map synchronized with map)
