### ISSUE TITLE
Wrong turn display and voice anouncement on unusual junctions

### ISSUE THREAD

**Issue by dafoxia** [osmandapp/OsmAnd#10968]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, OpenRouteService, OSRM, etc.)
- [x] happens also in OsmStreetMap enginge!

### Routing Profile
car

### Start and end points
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=48.24236%2C14.33395%3B48.24449%2C14.34172#map=17/48.24338/14.33739

### Actual and expected routes
Routing is correct. The turn-display and the announcing is incorrect.
On junction between Kafkaweg and Ennsfeldstrasse (location 48.24349,14.33759) there is a turn right command, should not be there

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

Osmand~ 3,9,4
</code></pre>

**Device and Android/iOS version:**

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**
Routing start at Erich-Fried-Weg 16, A-4030 Linz-Ebelsberg, Destination: any when routing happens over Kafkaweg and Ennsfeldstrasse to north.
![routing](https://user-images.githubusercontent.com/6188849/108624595-1ee83800-7446-11eb-9ee0-8ef82eafd27b.jpg)

**Comment by sonora** [comment]
Your actual position is not on your screenshot, are you sure the right turn you are talking about is not the right turn from Erich-Fried-Weg onto Kafkaweg, as it shows on the top of the screen?

**Comment by sonora** [comment]
In fact, I just checked, you are right, it is a valid issue. Somehow the merging of Ennsfeldweg from the right seems interpreted as a right turn, although it's a straight then left ...

![Screenshot_20210221-204609_OsmAnd~](https://user-images.githubusercontent.com/845735/108636568-6d1d2b80-7486-11eb-9b4b-77782e1beeb0.jpg)

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-core/pull/214/files
