### ISSUE TITLE
Track file shows step changes in Altitude profile

### ISSUE THREAD

**Issue by alejandro350** [osmandapp/OsmAnd#10972]
I upgraded to 3.9.6.  Now the altitude profiles are wrong. If I open the gpx file with garming software the altitude profile is displayed correctly. The route was recorded using osmand.
Thanks
![garmin](https://user-images.githubusercontent.com/63417450/108640991-a9826480-7451-11eb-9b91-cbeb85ece881.png)
![osmand](https://user-images.githubusercontent.com/63417450/108641001-b2733600-7451-11eb-802d-c02752ca4674.png)

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/10864
