### ISSUE TITLE
Units of measurement are not saved

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#10978]
### Description
Units of measurement. After assigning kilometres/metres as selected units to All Profiles or to This Profile, the setting does not persist, and the units keep reverting to the default values of miles/m.

### How to reproduce?
Change "Units of measurement" parameters for all Profiles, restart OsmAnd.

### Your Environment
 The version on my Nokia 5 phone is 3.9.6, released 2021-02-09
and for version 3.9.8 (Samsung 10e)

**Comment by JonnyTech** [comment]
Same as #10928 ?

**Comment by anastasiia936** [comment]
In Osmand + 3.9.10, the settings units of length are working incorrectly.
I checked two types of scenario:
1. For the walking profile, the length units have been set up miles/yards, checked whether the settings are relevant on the track, the data was displayed correctly, then switched to the cycling profile set the length units km / m, checked the indicators were displayed correctly. Then I returned to the walking profile and the length units displayed km / m (should be miles/yards according to the setting).
2. I set up the length units as miles/yards and then close and reopen the application, the length units have displayed km / m.

**Comment by vshcherb** [comment]
Merged from https://github.com/osmandapp/OsmAnd/issues/8463#issuecomment-808931584

**Comment by smason** [comment]
Maybe there could be a option for "From driving region, currently ..." in the "Units of length" dropdown.  That way it could do the right thing and switch automatically for driving, and I could explicitly switch my (e.g.) cycling profile over to kilometers.  It would also help with users discovering the reason behind the current UI behaviour.

**Comment by smason** [comment]
there seem to be lots of awkwardness in the interactions between `METRIC_SYSTEM` and `DRIVING_REGION` that weren't obvious to me before reading the following code: 
 https://github.com/osmandapp/OsmAnd/blob/8aa938090745b43d2619a559e87779ca59453ad3/OsmAnd/src/net/osmand/plus/settings/backend/OsmandSettings.java#L849-L874

but it's the first time I've looked at this code.  we might be talking about different issues, certainly for me switching between profiles while in "automatic driving region" causes my units to reset back to the one from the driving region rather than the one I picked (similar to anastasiia936's comment)

**Comment by Chumva** [comment]
This should be fixed here https://github.com/osmandapp/OsmAnd/pull/11032/commits/38d6183a43d49eb0311f35c6355c3a75fbaca29c, https://github.com/osmandapp/OsmAnd/commit/e3c456fd95da5c149dd8e629b67583beb65fe00a. 
Osmand 3.9.10 don`t have these commits.

**Comment by miklcct** [comment]
On my osmand 3.9.10 the units are automatically reverted to miles / m when doing navigation even after I explicitly set it to km / m. I'm in the UK. Do the commits above fix this issue?

**Comment by JonnyTech** [comment]
Change driving region from "automatic" to your location.

![Imagepipe_2](https://user-images.githubusercontent.com/3584732/116779327-9f8e6a80-aa6d-11eb-9b83-cfe26c168558.jpg)

Then set units as desired and they will no longer revert.
