### ISSUE TITLE
Switch on rendering of access tag by default

### ISSUE THREAD

**Issue by joostschouppe** [osmandapp/OsmAnd#10983]
# 🚀 feature request

### Switch on rendering of access tag by default

The Belgian OpenStreetMap chapter processes more than one complaint per month from people who say a path on their property should not be used by the general public. They generally want us to delete them. But if the path is observable, we explain that it's better to keep it on the map, and (hopefully) correctly map it as private. However, many apps don't show that info clearly on the map. [As a community, we're trying to talk to app-makers to take this info in account](https://github.com/osmbe/community_planning/issues/33). Osmand does a great job at showing the info, BUT the feature to show this info is a little bit hidden. The suggestion is to switch this on by default.

So the suggestion is: on new installs, activate the rendering of accesibility by default.

This is of particular interest to hikers and bikers, so perhaps the default could be associated to just those profiles.
However, for cars, the information is becoming more and more relevant too, as more details are getting mapped. The number of driveways worldwide has doubled in the last year or so - and a lot of them are private. Access roads in general can provide useful shortcuts. Users might be annoyed when they are not used by the routing, showing them as private on the map might make it easier to understand routing choices. The same layer also contains toll road info, which is also always nice to know. 
For 4WD vehicles the info is also of particular interest.

**Comment by vshcherb** [comment]
I tend to disagree cause it needs to come with explanation. It's 1 story if you enable something and starts to see new dashes / strange lines and completely another if app uses it by default without proper introduction. 
If you want to share within specific group it's better to create profile: OpenStreetMap Belgium and share it within group with proper communication. 

I would definitely agree that we need to render more icons that could explain but different types of dashes are not very explanatory .

**Comment by joostschouppe** [comment]
I understand your point. Though red dots on top of a path are pretty self-explanatory IMHO. To realize blue means destination and purple is with a fee, yeah that does take a little more time.

(note that it is exactly the difficulty of communicating to data users, in this case hikers and bikers, that is the difficult part. Hence why we are talking to different map developers to make it more obvious when a path isn't for general use. Different solutions are possible, like showing them only at high zoom, overlaying access icons, not showing them at all,...)

**Comment by vshcherb** [comment]
To do:
Icons needs to be clickable (POI)
![image](https://github.com/osmandapp/OsmAnd/assets/1042025/b583cdb9-4865-4bc9-ac7b-c2b3551f2b2d)

**Comment by vshcherb** [comment]
- [ ] https://github.com/osmandapp/OsmAnd-tools/pull/692#issuecomment-1771494431 needs to be implemented for good rendering

**Comment by xmd5a2** [comment]
**Dev notes:**
It will not be possible to do it as needed with the current implementation of propagateToNodes. That's what I'm doing:
```
<type tag="osmand_access" value="private" minzoom="13"/>
<entity_convert pattern="tag_transform" from_tag="access" from_value="private"  if_tag1="highway" to_tag1="access" to_value1="private" to_tag2="osmand_access" to_value2="private" propagateToNodes="all" notosm="true"/>
```
It is necessary to limit the scope only to roads, otherwise a lot of problems will arise. This is apparently due to the fact that propagateToNodes is working before entity_convert.
No nodes are added, just the osmand_access=private tag is added to the way:
`Way types [osmand_access-private (51), highway-track (15)] add_types [access-private(50),`

**Comment by xmd5a2** [comment]
Fixed. Icons for access restrictions were added. Luxembourg map was regenerated.
[Place to test](http://www.openstreetmap.org/#map=18/49.616257/6.1277876)
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/9490aa0a-6e1b-40ee-a169-6d3f5a81f547)

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#1032m, released: 2023-11-15
In the latest nightly builds, access restrictions can be only enabled/disabled using Hide menu (menu > configure map > hide > access restrictions). But in the *Details* menu (menu > configure map > Details) you can still find *Show access restrictions and toll* option, that do not work anymore.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/b8211b2c-82a5-4ceb-a2a2-b78d93e7c44b"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by pebogufi** [comment]
> But in the _Details_ menu (menu > configure map > Details) you can still find _Show access restrictions and toll_ option, that do not work anymore.

@DmitryAlexei 
But now toll roads are no more visible and i can't switch it on.
I can't check that with Luxembourg map because Lux does not have toll roads, as far as i know. South of it near Saint-Marie-aux-Chenes (France) is a motorroad with toll.  (A4)
49.18558 6.00254

**Comment by vshcherb** [comment]
Probably we need now setting to show toll roads otherwise it's a regression

**Comment by pebogufi** [comment]
> Probably we need now setting to show toll roads otherwise it's a regression

I would prefer setting at position as it was before, only changed name

**Comment by xmd5a2** [comment]
Separate "Show toll restrictions" option was added. Toll rendering is not separate from access.

**Comment by sonora** [comment]
https://github.com/osmandapp/OsmAnd-resources/commit/6c1da2621ac419e9f2b156590c47601847b05ea1 may fix it for default_render, but it is still a regression for many other map styles, or am I mistaken?

**Comment by xmd5a2** [comment]
@sonora this is used only for default map style. Topo and LightRS have different `access` visualizations.

**Comment by sonora** [comment]
I have just tried e.g. Touring view, and it seems the menu points _Dteails>Show toll restrictions_  and _Hide>Access restrictions_ are now entirely effectless?

**Comment by sonora** [comment]
Yes, that would fix it, thank you! Had just not checked if we have a similar situation also in other styles, but perhaps not.

**Comment by sonora** [comment]
Now "Show toll restrictions" appears at the very bottom of the long Details list, should we not move it to where all the other road-related 'Show..." items are like surface, quality, LEZ? I would even put it to the beginning of that group, it seems the most significant in many countries.

**Comment by dmpr0** [comment]
# Review 
* ToDo is missed

**Comment by xmd5a2** [comment]
- [ ] "No access" icons were added by default starting from zoom 17 at the ends of roads with `access=private`,`access=no`, `motor_vehicle=private` (for car rendering profile), `bicycle=no` (for bicycle rendering profile) and so on.
- [ ] "Show access restrictions and toll" option was changed to "Hide access" and moved to `hide` category
- [ ] Added option "Show toll restrictions" to `details` category
- [ ] Fixed access rendering in `Touring view` style

**Comment by dmpr0** [comment]
# Review - 2

<img src="https://github.com/osmandapp/OsmAnd/assets/9365308/78979758-a6ff-42fe-ac76-e3f7abc21af5"  width="300" height="auto"/> 

- [ ] Unable to find **No access** icons

**Comment by johnpercy** [comment]
I think UniRS needs the same treatment as Touring to get access and tolls to work again

**Comment by xmd5a2** [comment]
@johnpercy I've checked UniRS and it already works as expected

**Comment by xmd5a2** [comment]
@dmpr0 see https://github.com/osmandapp/OsmAnd/issues/10983#issuecomment-1805451968

**Comment by ivanPyrohivskyi** [comment]
New access icons will be available in the new December 2023 maps.
For test need regenerate map.

**Comment by vshcherb** [comment]
This looks definitely incorrect, so it's a question whether we are ready to release this feature.
![telegram-cloud-photo-size-2-5454297996075325163-y](https://github.com/osmandapp/OsmAnd/assets/1042025/613b38a0-f52b-4c48-acdb-f78163d4f461)

**Comment by xmd5a2** [comment]
All commits were reverted

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-tools/pull/new/fix10983AndStairs

**Comment by xmd5a2** [comment]
North Holland was regenerated

**Comment by vshcherb** [comment]
Problems
- [ ] Live updates

**Comment by vshcherb** [comment]
- [ ] Show access restrictions move to Details section
- [ ] https://www.openstreetmap.org/way/49063188 (fix bug) but we need to test how much time / memory will be consumed now

**Comment by vshcherb** [comment]
- Europe maps are ready to test

**Comment by xmd5a2** [comment]
Bug: propagated nodes are rendered when tunnels are hidden.
![Screenshot_2024-10-16_12-13-50](https://github.com/user-attachments/assets/fc59ba10-e76d-4ae9-9458-6b75d9e01508)

**Comment by ivanPyrohivskyi** [comment]
Test on countries
Germany_baden-wuerttemberg_europe_2.obf Germany_bayern_europe_2.obf Germany_hessen_europe_2.obf Germany_niedersachsen_europe_2.obf Germany_nordrhein-westfalen_europe_2.obf Ukraine_europe_2.obf

**Comment by vshcherb** [comment]
To summarize what's been done here:
1. With show access option on - we display stop signs where a network of private roads begins.
2. Also with this task we've implemented signs of hidden tunnels begin and end.

For today there is too many stop signs on the map, so we think to not enable it by default cause it overloads the map

**Comment by jbelien** [comment]
I've discovered a bit randomly the access tag rendering and it solved the confusion.

I agree with @joostschouppe , just enabling that setting by default would avoid confusion for new users (or old user like me that didn't find that setting easily - because the name of the setting is a bit confusing).

![Screenshot_20241028-215427.png](https://github.com/user-attachments/assets/28051bcc-0b49-4275-9d3f-61742e2cfc28)
