### ISSUE TITLE
[regression] not possible to rename a recorded file, if filename contains period

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#10988]
### Description

Selecting a file in My Places / Tracks / rec / 2021-02 
then 3-dots-menu Rename, changing the file name, Save 
I get the message 
A File with fhis name already exists.
This message is wrong, there is no file with that name.
Edit: The problem occurs only, if the filename contains a period (additional to that before the extension).
Example: period in new filemame between Fri and Test: 2021-02-19_11-09_Fri.Test.gpx

### Your Environment
OsmAnd Version:  OsmAnd~  4.0.0#31585m.apk 2021-02-23
Android version:  8
Device model:Samsung S7, SM-G930F

**Comment by Chumva** [comment]
@pebogufi Do you have a file in this folder with the name 2021-02-19_11-09_Fri.gpx?

**Comment by pebogufi** [comment]
Before the rename the file was
2021-02-19_11-09_Fri
Then I tried to rename it to
2021-02-19_11-09_Fri.Test
(In the rename dialog there is not extension used, so the real file name has a extension .gpx)
Again I get the message
"A File with fhis name already exists"
Tested again with version OsmAnd~  4.0.0#31668m.apk 2021-03-15

**Comment by Chumva** [comment]
Thank you, it should be fixed here https://github.com/osmandapp/OsmAnd/pull/11155. Probably tomorrow this fix will be in the nightly version.
