### ISSUE TITLE
OsmAnd routing incorrectly directing

### ISSUE THREAD

**Issue by thilokab** [osmandapp/OsmAnd#10995]
We are using OsmAnd version 3.9.5  in Brisbane. It is directing users to incorrect directions.

Could you please review the below example;

This android device has prompted the user to turn right into Algester road. But the Algester road is actually on the left side of the road while Illaweena road is on the left side.

![image](https://user-images.githubusercontent.com/78388857/108957487-a8596d80-76c5-11eb-9512-e14e292cf401.png)

### Your Environment
OsmAnd Version: 3.9.5
Android/iOS version:  7.1.1
Device model: Samsung J2 Pro

**Maps used (online or offline):**   
Offline maps

**Comment by scaidermern** [comment]
Maybe because this small stretch is named Algester Road in OSM? https://www.openstreetmap.org/way/576083313

**Comment by sonora** [comment]
I have changed the name of that median strip  in OSM and believe this will fix it (after the update of OsmAnd's map next month).

It makes sense tome that this is how things will work, but I am not sure if this is common mapping practice, and/or if we should do something in OsmAnd's code to fix those use cases more generally.

**Comment by thilokab** [comment]
Thanks, @sonora. Also, I have got another incident reported the same as the above.

OsmAnd is directing to the right to get into the Alma Rd but it’s on the left side.  

![image](https://user-images.githubusercontent.com/78388857/109440525-b2dd8380-7a86-11eb-9bf2-0021fd4daabc.png)

**Comment by sonora** [comment]
@thilokab I fixed this also.

Couple of hints:

- There is usually a way to take screenshots on your device, often by pressing two buttons like 'Power' and 'Volume down' or similar simultaneously, so no need to take a photograph of your screen. Just google the key combination for your particular device.
- To specify an exact intersection or place, it would be helpful to go to https://www.openstreetmap.org and locate it there, then just post the link from the browser here (like scaidermern did above).
- All map data is public, so you could easily fix things yourself by simply creating an account on https://www.openstreetmap.org, locate the place using their web site, then use their 'Edit' functionality there. To then change the name of a section, you simply tap on it and change the text under "Name". The particular issue with these intersections of dual carriageways you had is that the intersecting one changed names at the intersection: For this to properly be mapped, the 2 small stretches between the opposing lanes must be named accordingly (and differently), i.e. already each must already carry the name of the 'coming' road (depending on the allowed direction of travel on that segment).

**Comment by thilokab** [comment]
Hi @sonora ,

Thanks for your well-explained reply. I really appreciate it.

Also, apologies for the confusion, These screenshots are providing by our site employees and they do not have permissions to take screenshots using these phones they are using. That is why they are providing photos instead.
