### ISSUE TITLE
External bluetooth controller partly works

### ISSUE THREAD

**Issue by RolandsKlussLV** [osmandapp/OsmAnd#10997]
### Description
When connecting bluetooth  controller just part of controls works. Controller is using keys:

- up
- down
- left
- right
- volume up
- volume down

The up/down/left/right keys works, but zoom not working. When enabling general settings -> volume buttons as zoom zoom starts to work, but direction keys not working! :(

### How to reproduce?
Connect bluetooth keyboard to phone and try to control map with arrows and volume up/down buttton. Tur on "volume buttons as zoom" and check the result.

### Your Environment
OsmAnd Version: 3.8.4
Android/iOS version: 9.0 (android)
Device model: Huawei P30 pro, Blackview BV6100

**Maps used (online or offline):**   Both
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by dmpr0** [comment]
Hello, @RolandsKlussLV!
Do you enable "External input devices" in Profile – General settings?. The setting should be enabled for profiles you try to use, also you can select the type of controller from the list.

**Comment by RolandsKlussLV** [comment]
Hi!

Yes, I have enabled this option. I have tested with all three options there (Keyboard, WindwerLINQ, Parrot). As soon as I choose "keyboard" there, none of my BT controls are working! :(

**Comment by vshcherb** [comment]
You can try +/- on keyboard to zoom in.

**Comment by RolandsKlussLV** [comment]
> You can try +/- on keyboard to zoom in.

This is not possible in this case. Rest of controlled apps are using volume_up and volume_down!

**Comment by RolandsKlussLV** [comment]
Hi!

Guys, really need this functinality! buttoner.lv is up and running. Lot of requests for OSMand support!

Please, please!!!!


One more time explaining what I need: created BT controls sending the commands:
- key up;
- key down;
- key left;
- key right;
- volume down;
- volume up.

By default arrow keys works and volume up/down controls wolume.

Trying following settings:
1) Volume buttons as zoom - zoom works, direction keys not working;
2) Enabling external input devices - nothing works.


In my optinion, the first one should work, but something is wrong. I tried with bluetooth keyboard, the same issue! PLEASE FIX, as this would be really cool for our users!

Thank you!

**Comment by vshcherb** [comment]
It's planned to be fixed
