### ISSUE TITLE
[Edit Plugin][4.0.0] "Could not upload" to close a note

### ISSUE THREAD

**Issue by pietervdvn** [osmandapp/OsmAnd#11008]
### Description

Closing a note is not possible

### How to reproduce?

0. Login with OSM
1. Select a node, and click 'close'
2. Click the 'save' and 'upload'-buttons
3. Confirm update
4. See the error message: "Could not upload" "Error: Forbidden - You have not permitted the application access to this facility'

### Your Environment
OsmAnd Version: 4.0.0#31528m, nightly released on 2021-02-14
Android/iOS version: LineageOS 11 (custom ROM)
Device model: Xiaomi Mi9T pro

Maps used: Flanders (but not relevant)

**Comment by scaidermern** [comment]
Did you switch to OAuth? I had the same problem in #10625. The hint from vshcherb fixed it for met:

> You can change permissions on https://www.openstreetmap.org/user/xxxxx/oauth_clients and revoke and login again.

I still don't know why this happens.

**Comment by vshcherb** [comment]
OSM introduced new permission and they didn't enable that permission by default, so relogin is needed.
