### ISSUE TITLE
track recording dialogue Stop oddity

### ISSUE THREAD

**Issue by tommycrock** [osmandapp/OsmAnd#11003]
### Description
When recording a track, hitting stop in the new dialogue shows a message 
"Are you sure you want to stop recording? All unsaved data will be lost." 
But the options are "Save and stop recording" which brings up a save dialogue (different than hitting save!?) Or cancel, which returns you to the track recording dialogue. So I think the message needs to change. Not sure if there should be an option to stop and not save, but I suppose that's pause. I don't know why the save procedure is different this way.

### Your Environment
OsmAnd Version: 3.9.9
Android version: 11
Device model: Samsung galaxy S10e

**Comment by tommycrock** [comment]
#10924

**Comment by Ungoose** [comment]
Yes, that is weird. I also mention it in #10924. Without the "do not save" option, the Stop button seems to serve no other purpose than saving a track, and the message is meaningless. So, if the omission of the "dismiss" option is deliberate, it is just a confirmation dialog for a non-dangerous action that can probably be replaced with a long tap to avoid accidental presses.

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/10924
