### ISSUE TITLE
Wrong display/announcement of the lane

### ISSUE THREAD

**Issue by Berlin53** [osmandapp/OsmAnd#11011]
![Osloer Straße](https://user-images.githubusercontent.com/79656260/109186507-482ffd80-7791-11eb-97c4-292191ac9d93.JPG)

I want to drive straight on Osloer Straße in Berlin in the direction of the Autobahn. The route is displayed correctly in OsmAnd (version 3.9.6). Before the intersection Schwedenstraße (OSM Way-ID =82455845, 483483275, 4544072) OsmAnd leads to the left turn lane. Announcement: "Turn left onto Osloer Straße". Then it continues straight ahead. Obvious mapping errors are not visible in OSM. However, the situation contains a higher hazard potential.

**Comment by Dima-1** [comment]
Issue will be fixed at the next map update
