### ISSUE TITLE
"Use 2-phase A*routing algorithm" switcher does not work correctly

### ISSUE THREAD

**Issue by MakiWolf** [osmandapp/OsmAnd#11019]
### Description
"Use 2-phase A*routing algorithm" switcher does not work correctly. When it is enabled is says when you open the menu it is disabled and when you disable it it says when you open menu it is enabled.
![issue](https://user-images.githubusercontent.com/73300633/109341681-08d5df80-786b-11eb-9a31-bc5122c633bc.gif)

### How to reproduce?

- Open Menu
- Select Directions
- Select Options
- Select Navigation Settings
- Select Route parameters

### Your Environment
OsmAnd Version: 3.9.7 and latest build from source code
Android/iOS version: 9
Device model: Samsung Note 8

**Comment by naoliv** [comment]
It seems to be the same as  #10902
