### ISSUE TITLE
(Europe-UK)-Greater London not included in new England region group

### ISSUE THREAD

**Issue by cebderby** [osmandapp/OsmAnd#11023]
I noted there wasn't a Feb update to the huge England map, and that was no longer offered, so removed that and selected the new England group of (currently 9) regions.  All downloaded ok, but on zooming in on London, got prompted to download Greater London.  If this content is separate from the England South East area, then England Greater London needs to be added as a 10th region in the England group.

OsmAnd Version: OsmAnd+ 3.9.9
Android/iOS version: Android

maps: Europe England (group definition)

**Comment by nazar-kutz** [comment]
PR: https://github.com/osmandapp/OsmAnd/pull/11074
