### ISSUE TITLE
Car routing prioritizes primary road over trunk

### ISSUE THREAD

**Issue by ariadacapo** [osmandapp/OsmAnd#11025]
[The attached route (GPX)](https://github.com/osmandapp/OsmAnd/files/6054952/route.gpx.zip) was created by creating a request for directions between the first and the last point ([GraphHopper route for comparison](https://www.openstreetmap.org/directions?engine=graphhopper_car&route=46.8224%2C9.4079%3B46.7621%2C9.4231#map=13/46.7855/9.4352)). A trunk road is available from start to finish, yet the route proposed by OsmAnd goes on a primary road, which is much longer and much slower. I drove along this road from Chur to Hinterrhein, and OsmAnd kept proposing such detours along the primary road all along.

Navigation options: Navigation type: Car, Screen alerts: On; all other: Off (including temporary limitations)
OsmAnd~ 3.9.4 on Android 7.1.2
Downloaded map: Switzerland, Feb 1, 2021

I send thanks to the developers fort their time programming OsmAnd.

**Comment by pebogufi** [comment]
Can not confirm. If i use only start and end point, osmand navigates throug the tunnel. Profile is car. 
Version OsmAnd~  4.0.0#31595m.apk

**Comment by ariadacapo** [comment]
I upgraded to 3.9.8 and now I cannot reproduce the bug anymore. I think it can be closed. Thank you for your time!
