### ISSUE TITLE
wrong distance and partial track displayed - paused/resumed

### ISSUE THREAD

**Issue by tommycrock** [osmandapp/OsmAnd#11031]
### Description
Track record shows different lengths in My places\Tracks dialogue depending on whether it's visible. When visible it misses almost half of the track and doesn't display it on-screen. Track has recorded though. Only one segment is counted in the 'Overview' dialogue, although most of the track is displayed.
![Screenshot_20210228-133241_OsmAnd+small](https://user-images.githubusercontent.com/5749884/109425639-1b722500-79e1-11eb-9d44-1aa8de79ecb6.jpg)
![Screenshot_20210228-133245_OsmAnd+](https://user-images.githubusercontent.com/5749884/109425644-1dd47f00-79e1-11eb-8f21-b15721019a9f.jpg)
![Screenshot_20210228-133401_OsmAnd+](https://user-images.githubusercontent.com/5749884/109425647-1f9e4280-79e1-11eb-9002-ef60517535a0.jpg)
[2021-02-28_10-20_Sun_Renamed.zip](https://github.com/osmandapp/OsmAnd/files/6057195/2021-02-28_10-20_Sun_Renamed.zip)

### How to reproduce?
I recorded a trip using trip recording, with several pause-resumes along the way. At the end, I stop-saved and renamed. I noticed that the length was wrong and was surprised that the correct length was shown when turning visibility off. Then found a different length in the track overview.

### Your Environment
OsmAnd Version: 3.9.9
Android/iOS version: 11

**Comment by pebogufi** [comment]
In current nighly build OsmAnd-Android-full.apk
OsmAnd~  4.0.0#31601m.apk 2021-02-27 17:57
I did not find differences in distances, all are 3,28 km (i use km!).
But I found differences in duration: 1:57:10, 1:19:21.

![Screenshot_20210228-181837_OsmAnd~~01](https://user-images.githubusercontent.com/18628183/109427264-d73b5080-79f1-11eb-8e3d-c90e1b1ee4f0.jpg)
![Screenshot_20210228-181815_OsmAnd~~01](https://user-images.githubusercontent.com/18628183/109427272-dd313180-79f1-11eb-9236-0b0c8650c36a.jpg)
![Screenshot_20210228-181754_OsmAnd~~01](https://user-images.githubusercontent.com/18628183/109427277-e3bfa900-79f1-11eb-9467-6a2099776078.jpg)
![Screenshot_20210228-181740_OsmAnd~~01](https://user-images.githubusercontent.com/18628183/109427281-e8845d00-79f1-11eb-9325-2468a2c15e13.jpg)

**Comment by tommycrock** [comment]
I think the 1:19:21 you see @pebogufi is correct as the recording duration. The 1:57:10 is the start time to end time (not accounting for pauses). Neither of these are the times I saw. When I look now I see the same as you, but it persisted until osmand was closed.

**Comment by pebogufi** [comment]
There is also a time in movement (see above de:Zeit in Bewegung), which is 1:02:44. I am not shure, what the 1:19:21 should be.

**Comment by cepprice** [comment]
https://github.com/osmandapp/OsmAnd/pull/11180
