### ISSUE TITLE
OSMAnd navigation using street address rather than geo co-ordinates

### ISSUE THREAD

**Issue by thilokab** [osmandapp/OsmAnd#11047]
Hi OsmAnd support team,

We are using OsmAnd version 3.9.9 in Australia. We would like to know if there is a way for us to get geocoded co-ordinates for a street address and then using OsmAnd to navigate to the retrieved geo co-ordinates. It would be great if you could link us to the API calls so that we can integrate that within our mobile application.

Thank you!

**Comment by vshcherb** [comment]
Unfortunately we don't have such functionality yet.

**Comment by thilokab** [comment]
Thanks for the reply.

It would be great if there is a way to navigate to retrieved geo co-ordinates from the geocoded coordinates of a street address.

We can get geocoded co-ordinates for a street address as in the below image;

![image](https://user-images.githubusercontent.com/78388857/110053375-66a78180-7dad-11eb-9a01-ec4b1fa376b8.png)

![image](https://user-images.githubusercontent.com/78388857/110053482-9ce50100-7dad-11eb-9c23-6220f59ac1fa.png)
