### ISSUE TITLE
Option to add a little bit of silence before voice directions.

### ISSUE THREAD

**Issue by jkufner** [osmandapp/OsmAnd#11062]
### Description

Some bluetooth speakers and receivers have a small delay before they actually start palying the sound. So when there is no other app playing any sound, then the bluetooth device sleeps and misses to play beginnings of the voice directions from Osmand. For example, I can hear "fifty meters turn left" instead of "In three hundred fifty meters turn left".

### Describe the solution you'd like

I would like to have a simple option to prepend two seconds of silence before any voice output, so that the bluetooth device will have the time to wake up.

### Describe alternatives you've considered

Alternative option is to keep the audio output permanently open (actively play nothing), but that seems inefficient.

**Comment by skarkkai** [comment]
Also having this problem. I'd argue this is more than a "nice to have", because it makes the whole navigation semi-unusable with some headphones. Also not a problem that seems to be going away, as it's happening with my new, fairly high-end AfterShokz Aeropex headphones.

Solutions will clearly have downsides, but even 2x battery consumption or delayed directions is better than current situation.

**Comment by gzuaps** [comment]
Doesn't the voice prompt delay already exist in plugins development options?

**Comment by sonora** [comment]
This is already implemented: Temporarily activate the Development plugin, then in its Settings go to 'Test viice prompts' and use button 11.2 to select an appropriate delay between 0 and 1500ms. Also the content of the prompts (distances) will be adujsted according to the selected timing.

**Comment by skarkkai** [comment]
When I click "Test voice prompts", I only get a prompt language selector. Nothing that could be a delay selector.

**Comment by jkufner** [comment]
@sonora So the implementation is hidden somewhere there, but it does not have the user interface. Would it be please possible to add this somewhere the user actually can find it and use it? Without the usable and discoverable user interface, the feature is as good as if it wasn't there at all :(

@skarkkai Choose the language, then scroll all the way down.

**Comment by sonora** [comment]
@vshcherb It's true I had implemented this years ago, but it only has this rudinentary UI. At the time it was novel fuctionality needed only in rare cases, but with BT couplings being more common today maybe it is worth to create a more visible access in settings at some point.

(Knowing we have too many settings already, so I'd say our efforts to better  bundle access to  them under a single "Settings" screen or making the settings searchable should have relative priority. 😉).
