### ISSUE TITLE
River Jizerka not dispalyed ... layer=-1

### ISSUE THREAD

**Issue by miramikes** [osmandapp/OsmAnd#11066]
Hello,
river Jizerka and some parts of contributory streams are not displayed I've checked these streams and all are tagged as layer=-1
This problem is visible only in certain profiles ... winter car bicycle ... it is fine in others boat hike overview
EDIT: Just realize that I have option ... "configure map" -> "hide" -> "underground objects" ... checked in some profiles.
Uncheck this option solve this issue.
Anyway I believe river shouldn't considered as "underground object"    
![Screenshot_26](https://user-images.githubusercontent.com/623412/110035504-0f1cfd80-7d3c-11eb-93a8-2a130dc446d1.jpg)
![Screenshot_27](https://user-images.githubusercontent.com/623412/110035512-13e1b180-7d3c-11eb-8b10-5b80e220333d.jpg)

best
mira

**Comment by xmd5a2** [comment]
"Hide" - "Underground objects" does exactly as it named: hides underground objects. If object is marked as layer=-1 then it is considered as underground. If this is a tagging mistake then it is better to fix it in OSM data.

**Comment by miramikes** [comment]
Thank you I just fixed this in OSM data ;)
