### ISSUE TITLE
piste:grooming=backcountry  ... improvement ... "winter and ski" profile

### ISSUE THREAD

**Issue by miramikes** [osmandapp/OsmAnd#11065]
Hello,
I am suggesting following improvement for "winter and ski" profile ...

piste:type=nordic
I like a lot how very different looks piste:grooming=skating and piste:grooming=classic as they are really for different nordic skiers.
It would be great if there would be same clear difference for piste:grooming=backcountry this type of piste might look very similar
like piste:grooming=classic , but it is really meant for different skiers.
There is sporty oriented nordic classic skiers who strongly prefer groomed piste and backcountry piste is almost unacceptable for them.
And there are touristic oriented classic nordic skiers who strongly prefer piste:grooming=backcountry ... much slower travel pace,
less people, slightly more difficult terrain and possibly (not necessarily) even wider skies. 
I am suggesting to display piste:grooming=backcountry same color as other nordic pistes but "dashed" line to be clearly distinguished from groomed pistes.

There is only one a hack in it ... piste:grooming=backcountry shouldn't be mistaken with piste:type=skitour
So probably slightly thinner line than skitour and maybe different dashing ...

best regards

mira

**Comment by xmd5a2** [comment]
You are wrong that nordic pistes with `piste:grooming=classic` looks like `piste:grooming=backcountry`. Here is how `piste:grooming=backcountry` looks like:
![Screenshot_2021-03-19_22-20-17](https://user-images.githubusercontent.com/5829014/111832201-88eae480-8901-11eb-8a47-acafe2b2a8a5.png)
`piste:grooming=classic` was look like regular nordic piste but with darker colour.
So this is the issue I've found:
`piste:grooming=classic` and regular nordic piste without grooming were very similar. I've modified style of classic grooming nordic piste to this (right column):
![Screenshot_2021-03-19_22-18-34](https://user-images.githubusercontent.com/5829014/111832571-06aef000-8902-11eb-8d16-2ebb4e4e2a2f.png)
Is this what you were talking about?

**Comment by miramikes** [comment]
What have you done for piste:grooming=classic is great and helpful, but I was really referring to  piste:grooming=backcountry.
Interestingly piste:grooming=backcountry looks differently on my phone:
![Screenshot_Pavlova_cesta](https://user-images.githubusercontent.com/623412/111837306-001b7b00-88f8-11eb-94c1-a254a68c50a5.jpg)
Pavlova cesta
piste:type=nordic
piste:grooming=backcountry
piste:difficulty=easy
It is just solid line here without dark section ... so it is quite similar to piste:grooming=classic and regular nordic piste without grooming.
Thank you for your great work !!!

mira

**Comment by xmd5a2** [comment]
@miramikes this can be result of recent updates of this way. Our maps are updated monthly.

**Comment by miramikes** [comment]
Yep, I am getting new maps of Czech rep. about 15th each month by there is info that they were build on 1th of that month.
This mean I can confirm result of your work about 16.04 ... 4 weaks later :(
mira

**Comment by xmd5a2** [comment]
@miramikes look at object and determine when this tag was added

**Comment by miramikes** [comment]
You mean when "Pavlova cesta" was tagged as piste:type=nordic piste:grooming=backcountry piste:difficulty=easy? It was on 07.02.2021 and done by me BTW ;)

**Comment by xmd5a2** [comment]
Please provide a link to this object in OSM

**Comment by miramikes** [comment]
https://www.openstreetmap.org/way/30897803#map=16/50.8463/15.2257
Here it is
m.

**Comment by xmd5a2** [comment]
@miramikes Вo you have the "Piste grooming" style option enabled?

**Comment by miramikes** [comment]
Yes I have this option enabled ... My problem was that I checked it with beta version, but not with latest build ...
Sorry for that :( ... 
Your work looks great !
Would be possible to make piste:grooming=backcountry while zoomed out too?
Zoomed in ... Great difference
![Screenshot_backcountry_1](https://user-images.githubusercontent.com/623412/112040314-5cbfa580-8b45-11eb-85ef-dd8d003018ac.jpg)
Zoomed out ... there is no difference between perfectly groomed track and totally unmaintained path made by enthusiast. 
![Screenshot_backcountry_2](https://user-images.githubusercontent.com/623412/112040334-66490d80-8b45-11eb-8781-4c4ab9a7d2de.jpg)

**Comment by miramikes** [comment]
Thank you !!!
