### ISSUE TITLE
Hide option "Boundaries" does not hide all boundaries

### ISSUE THREAD

**Issue by nl112358** [osmandapp/OsmAnd#11069]
### Description
In the area where I live there are many boundaries of estates, parcs, etc. These lines are drawn on top of other 
objects, like footways and bicycle ways. Only starting from a certain zoomlevel you can distinguish them from the 
underlying paths, but this would require you to zoom in and out constantly, which is unconvenient while bicycling. 
See screenshots:
![Screenshot_500m](https://user-images.githubusercontent.com/32866920/110147042-85247180-7ddb-11eb-9f2f-bbaa1c922d4a.jpg)
![Screenshot_200m](https://user-images.githubusercontent.com/32866920/110147038-848bdb00-7ddb-11eb-8ae8-e6d0518f74d5.jpg)
![Screenshot_100m](https://user-images.githubusercontent.com/32866920/110147834-6a063180-7ddc-11eb-8cff-58dfc504b952.jpg)
![Screenshot_50m](https://user-images.githubusercontent.com/32866920/110147029-82c21780-7ddb-11eb-9f1a-cd6232e3be3c.jpg)

I tried to switch off the boundary lines in the hide menu by selecting the Boundaries option, but this has no effect on
these lines. Checking in OSM itself I found out that these lines are not always boundaries, they can also be 
demarcations of so called Leisure area's:
Link | Way Name | Tag name | Tag value
-------------------------------------------------------- | ----------------------------- | -------------- | ------------------
https://www.openstreetmap.org/way/11788950 | Landgoed Huis te Maarn | boundary | protected_area
https://www.openstreetmap.org/way/752846493 | Landgoed Moersbergen | leisure | nature-reserve
https://www.openstreetmap.org/way/11788797 | Kaapse Bossen | leisure | nature_reserve

One way to get rid of these lines is is by hiding Polygons, but then many other interesting information is hidden 
as well. Hiding Overground Objects does also work (starting from zoomlevel 200m and better) but also in this case other 
interesting information is hidden.

Please modify the hide option "Boundaries" so that it includes the class of objects "boundary:protected_area" and 
"leisure:nature_reserve".

### How to reproduce?
Select one of the Way-objects in OSMand, set Map Style to Mapnik and select "Boundaries" in the hide menu. The (light green) boundaries will still be visible in OSMand.

### Your Environment
OsmAnd Version: 3.8.3
Android/iOS version: Resurrection Remix 8.6.2
Device model: Xiaomi Mi 9T pro

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by pebogufi** [comment]
Thanks a lot.
Peter
