### ISSUE TITLE
Some addresses are not showed correctly

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/OsmAnd#11079]
Osmand 3.9
Maps: Comunity of Madrid, 1 mar 2021

Why are some buildings or nodes not showing their address correctly? I have not found any mistake in OSM data.

Examples: 
https://www.openstreetmap.org/way/309660762
https://www.openstreetmap.org/way/309660758
https://www.openstreetmap.org/way/309660764
https://www.openstreetmap.org/way/309660759
https://www.openstreetmap.org/way/612056999
https://www.openstreetmap.org/node/1819049874
https://www.openstreetmap.org/node/3531828041

However, other buildings near them are showing their adress correctly
https://www.openstreetmap.org/way/198954698
https://www.openstreetmap.org/way/199192734
https://www.openstreetmap.org/way/199271175

**Comment by letypequividelespoubelles** [comment]
Similar to #10036 but for a different place.

**Comment by vshcherb** [comment]
Probably similar
 https://osmand.net/go?lat=53.676025&lon=23.859946&z=19.050121 -
https://osmand.net/go?lat=53.671646&lon=23.851839&z=18.867172

**Comment by vshcherb** [comment]
Note: check ios version (likely the fix should be provided by more precise data)

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-tools/pull/390

**Comment by vshcherb** [comment]
Bug fixed but requires new maps, so it will be part of April maps
