### ISSUE TITLE
Review limits for max tile size cache

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#11085]
https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/src/net/osmand/plus/resources/ResourceManager.java#L253
It looks like this formula is
- outdated
- doesn't take into account density (we should have probably 4 layers at least support)
- probably cache size should be dynamic / reevaluated based on number of layers enabled

![image](https://user-images.githubusercontent.com/1042025/110323982-ab355600-8015-11eb-8023-307f65aeae7f.png)

**Comment by Chumva** [comment]
This should be added here - https://github.com/osmandapp/OsmAnd/pull/11404 but it needs some testing.

**Comment by vshcherb** [comment]
We need to make it more smooth feedback from Yurii tablet.
