### ISSUE TITLE
compass ruler not showing the “measure distance” when touching the map with two fingers

### ISSUE THREAD

**Issue by erik55** [osmandapp/OsmAnd#11084]
### Description
[As of this description](https://osmand.net/features/ruler)  the compass ruler should show when touching the map with two fingers to measure the distance. But it is not. 

### How to reproduce?
* Start OSM. 
* go to configure screen menu
* activate the radius ruler
* touch with two fingers on the map
* nothing happens. 

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: 10
Device model: Samsung SM-G960F

**Maps used (online or offline):**   
Standard Osmand map style and topo. Neither work.

**Comment by chris-ca** [comment]
In the recent osmand version the "configure screen" menu has a new option "distance by tap" which needs to be enabled as well (option is almost at the bottom)

**Comment by erik55** [comment]
Ok, then the official description is wrong: https://osmand.net/features/ruler

Compass is not needed for distance measuring. Only distance by tap.

**Comment by vshcherb** [comment]
Documentation is being migrated https://docs.osmand.net/en/main@latest/osmand/widgets/radius-ruler, so it's going to be updated.
