### ISSUE TITLE
Guidepost preset misses one tag

### ISSUE THREAD

**Issue by letypequividelespoubelles** [osmandapp/OsmAnd#11081]
### Description
When creating a POI, the guidepost preset misses the tourism=information tag, as required in [the wiki](https://wiki.openstreetmap.org/wiki/Tag:information%3Dguidepost).

See for exemple [this POI](https://www.openstreetmap.org/node/8494419148/history)

### How to reproduce?
Try to create a guidepost POI

### Your Environment
OsmAnd Version: 3.9.5

**Comment by scaidermern** [comment]
Duplicate of #5958. Unfortunately this is a long-known bug.
