### ISSUE TITLE
False and hopping Altitude of Track Recording

### ISSUE THREAD

**Issue by hmwallner** [osmandapp/OsmAnd#11096]
False and hopping Altitude of Track Recording sometimes more than 30m in height.
Problem occured on Samsung xCover4s.
I tried Recording also with GPSLogger and the recorded altitude there is correct.
Recording the same Track with Osmand 3.9.10 there are hopping altitude stepr in the recorded File.
I attached 3 of the Recordings from GPSLogger and also from Osmand.
How to fix this problem?

[TrackRecording.zip](https://github.com/osmandapp/OsmAnd/files/6110512/TrackRecording.zip)

**Comment by vshcherb** [comment]
I believe it's https://github.com/osmandapp/OsmAnd/issues/10864 should be fixed by Google with update

**Comment by hmwallner** [comment]
Thanks for the Info
