### ISSUE TITLE
Screen timeout does not work when navigating with TTS

### ISSUE THREAD

**Issue by lefou** [osmandapp/OsmAnd#11093]
### Description

The screen timeout does not work once a TTS sound was played in navigation.

### How to reproduce?

1. Enable screen timeout and set a short defined system screen timeout (for me: 15 sec).
2. Ensure screen timeout works in general: Open OsmAnd and ensure, the screen goes of after the timeout
3. Now start navigation mode with a given route/track with TTS instructions turned on
4. Once an navigation instruction was emitted, the screen stays on and never goes off, even long after the timeout period

This can be also reproduced in navigation simulation mode.

### Your Environment
OsmAnd Version: 3.9.8
Android/iOS version: Android 11, Samsung One UI 3.1
Device model: Samsung Galaxy S10e

I also saw this issue previously (summer 2020) on older versions of OsmAnd (recent in summer 2020) and another phone: Samsung Galaxy A3 (2016). So the issue could be related to Samsung devices.

**Comment by vshcherb** [comment]
Is it related only to TTS-navigation? Does it work when you do have voice navigation or without navigation?

**Comment by lefou** [comment]
> Is it related only to TTS-navigation? Does it work when you do have voice navigation or without navigation?

TBH, I have no idea what the difference between TTS and voice navigation is. I'm speaking about the voice navigation with one of the installable languages from OsmAnd (which are called "TTS Sprachansage" (TTS voice message)  in the menu sub-text). I tried it with "German" and "German (informell)". With both I could reproduce the issue.

If I don't use navigation, e.g. when I only use OsmAnd to record the track and get an overview over the track options, screen timeout works as expected. Screen goes black after the timeout period, and after a double-tip to the display, it awakes into OsmAnd without any lock screen as expected.

**Comment by EssBee59** [comment]
> ### How to reproduce?
> 1. Enable screen timeout and set a short defined system screen timeout (for me: 15 sec).
> 2. Ensure screen timeout works in general: Open OsmAnd and ensure, the screen goes of after the timeout

Hello Lefou,

The setting for timeout is "state" dependant!
In other words, you have to configure the timeout in the "start state" (view map) AND in the profile you are using for navigation!

**Comment by vshcherb** [comment]
Tested again and can't reproduce it with 4.1.10

**Comment by lefou** [comment]
Thanks for looking into it. It's a while since I used that kind of navigation, but I will comment, once I can confirm or reproduce.
