### ISSUE TITLE
iOS app crashes immediately

### ISSUE THREAD

**Issue by brocke** [osmandapp/OsmAnd#11107]
### Description
The OsmAnd iOS app crashes immediately after every launch attempt. It happened the first time, on both iPhone and iPad, when I tried to select the topo map style. As soon as I touched “Topo” it crashed.

Note: I’m using the OsmAnd live feature, but it updated map data normally just before the first crash, when I was using the mapnik style. First crash appeared when I wanted to switch map style to topo.

### How to reproduce?
Just switch map style to topo style. It should crash right away. Then (after topo is “selected”) the app crashes immediately after launch.

### Your Environment
OsmAnd Version: 3.9.5
Android/iOS version: 14.4.1
Device model: iPhone 7 Plus

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by geoffmozz** [comment]
Got exactly the same problem. It started today. The app won't even open. Aaaaarrghhhh.

I re-installed the app. It went OK until the maps finished downloading then crashed.

Sadly it's completely unusable.

**Comment by brocke** [comment]
https://twitter.com/osmandapp/status/1369768827731521541?s=20

Sounds good!

**Comment by vshcherb** [comment]
The problem is acknowledged, hopefully 3.9.7 will pass review tomorrow

**Comment by wordplay77** [comment]
Got 3.9.7 just now on iOS crashing problem resolved
