### ISSUE TITLE
CarPlay nav freeze

### ISSUE THREAD

**Issue by wojosc** [osmandapp/OsmAnd#11106]
### Description
The navigation screen on CarPlay freezes when phone screen turnes off/standby.
Other zu like path description will keep running. When turning phone screen back on navigation will refresh and work till next Standby

### How to reproduce?
While navigation turn off the screen of your iPhone

### Your Environment
OsmAnd Version:
Android/iOS version: iOS
Device model: iPhone 12

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by vshcherb** [comment]
Should be fixed with 3.9.7 (already in review)

**Comment by r33zA** [comment]
Hello. This bug is still present in 3.9.7.

**Comment by wojosc** [comment]
> Hello. This bug is still present in 3.9.7.

I can confirm! @vshcherb please consider reopening.
