### ISSUE TITLE
Sea area marked like ground when zoom in/out

### ISSUE THREAD

**Issue by DmytroPetrovV** [osmandapp/OsmAnd#11140]
When zoom in/out near islands and see, in some areas, sea is painting like ground.

STR:
1. Go to map
2. Find islands near turkey region “Mugla, Bodrum”
3. Zoom in/out near peninsula “Datcha”
4. Pay attention to the sea area around the islands

### Your Environment
OsmAnd Version: 3.9.7
iOS version: 14.4.1
Device model: iPhone 11 Pro 

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by xmd5a2** [comment]
Issue is in detailed map, not basemap (Turkey)
http://www.openstreetmap.org/#map=21/36.682575/27.57795
![Screenshot_2021-03-25_11-00-16](https://user-images.githubusercontent.com/5829014/112438822-67eb1f00-8d59-11eb-8f65-f9421ceeda54.png)
![Screenshot_2021-03-25_11-00-35](https://user-images.githubusercontent.com/5829014/112438837-6cafd300-8d59-11eb-9f30-dc9f0efd6205.png)
```
DEBUG: Ocean: line  289101749 (osm 4517214) sx=0,0000 sy=0,3476 ex=0,4053 ey=0,7930 - top/left [1238237184, 838205440] width/height [32768, 32768]
DEBUG: Ocean: line  289101803 (osm 4517215) sx=0,4053 sy=0,7930 ex=0,7750 ey=1,0000 - top/left [1238237184, 838205440] width/height [32768, 32768]
DEBUG: Ocean: line  289101719 (osm 4517214) sx=0,0000 sy=0,3212 ex=0,4053 ey=0,7930 - top/left [1238237184, 838205440] width/height [32768, 32768]
DEBUG: Ocean line touch:   289101719 (osm 4517214) sx=0,0000 sy=0,3476 ex=0,7750 ey=1,0000 - top/left [1238237184, 838205440] width/height [32768, 32768]
ERROR: Error processing multipolygon 0 (osm 0) sx=0,0000 sy=0,3212 ex=0,4053 ey=0,7930 - top/left [1238237184, 838205440] width/height [32768, 32768]
```
