### ISSUE TITLE
healthcare POIs: No POI overlay icon

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#11143]
Healthcare POIs have no POI overlay icon.

Example (`healthcare=physiotherapist`):
![photo_2021-03-15_09-33-12](https://user-images.githubusercontent.com/1040784/111125490-f13c6d80-8571-11eb-9c37-169145571001.jpg)

Instead of showing an orange POI symbol and the name, OsmAnd shows the name only. This makes it very hard to find these POIs on the map.

**Comment by xmd5a2** [comment]
If POI has no icon then no orange shield is displayed at all, but name is displayed. This should be fixed.

**Comment by scaidermern** [comment]
These POIs have an icon as can be seen in the screenshot. There is just no orange icon for the POI overlay.

**Comment by xmd5a2** [comment]
No, this POI doesn't have a special icon. What you see at the map is a fallback icon.

**Comment by scaidermern** [comment]
Oh, I see. So I guess the same issue occurs for some other POIs, too.

Can't the POI overlay just use the fallback icon?

**Comment by vshcherb** [comment]
Issue not reproducible in opengl

**Comment by scaidermern** [comment]
> Issue not reproducible in opengl

I can still reproduce this with OsmAnd 4.3.0 and enabled OpenGL. There is still no orange POI overlay icon for these elements.

**Comment by nnngrach** [comment]
> I can still reproduce this with OsmAnd 4.3.0 and enabled OpenGL. There is still no orange POI overlay icon for these elements.

Hi. I'm testing this place  on developer's brach. And it looks okay. I think this problem has already been fixed. And that it should work in the next app update.

![photo_2022-11-30 18 43 50](https://user-images.githubusercontent.com/35684515/204812864-01768178-fde1-4047-8584-ab810f599b1c.jpeg)
![photo_2022-11-30 18 43 53](https://user-images.githubusercontent.com/35684515/204812877-9d71b313-eeca-4597-86d8-52313d7d77b9.jpeg)

**Comment by scaidermern** [comment]
Yes, I just got the 4.3.1 update and now it is working. Thanks!
