### ISSUE TITLE
Routing (penalty traffic light)

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#11154]
### Description

Wrong routing

### How to reproduce?

Car profile
Start: 2.980615N, 101.737757E
end: 2.935312N, 101.756145E

![image](https://user-images.githubusercontent.com/44466116/111204798-832a9180-85d7-11eb-9c7d-927c6ec55586.png)
![image](https://user-images.githubusercontent.com/44466116/111204817-8a519f80-85d7-11eb-9728-700016b605a6.png)
![image](https://user-images.githubusercontent.com/44466116/111204840-8faeea00-85d7-11eb-8da9-1206f02ce647.png)

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: 
Device model:

**Comment by EugeneZmeuk** [comment]
POint 34 51 48.3 S; 56 09 05.6 W

![image](https://user-images.githubusercontent.com/44466116/111210439-4f069f00-85de-11eb-9114-9c8e53df1939.png)

**Comment by vshcherb** [comment]
It looks like in many these cases the reason is mapping data
