### ISSUE TITLE
Weird navigation Høm Denmark

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#11166]
In Denmark when navigating from Ringsted to Næstved the route is correct trough Høm, but the other way some wierd detour is suggested.

![image](https://user-images.githubusercontent.com/1042025/111317186-3214af00-8664-11eb-97dd-8b6aeb9cecaf.png)

**Comment by MrManor** [comment]
So I did a map update today, and the issue is not longer there.
