### ISSUE TITLE
display osmc: symbol for all paths

### ISSUE THREAD

**Issue by Hades1503** [osmandapp/OsmAnd#11168]
# 🚀 feature request

### Description

Hello,

for hiking the marking is very important to locate. For the moment the "osmc: symbol" tags stand out only if it is a route on Osmand.

### Describe the solution you'd like

is it possible to display the "osmc: symbol" even if it is not a "route" in the next update?

thanks in advance

**Comment by xmd5a2** [comment]
No, it is not possible. It can be fixed only in OSM data.

**Comment by Hades1503** [comment]
Hi,

the osmc: symbol data is on a lot of paths (I added it personally).

osmand only displays osmc: symbol of routes. paths that are not part of a route do not display the osmc: symbol.

I asked this question to OSM for the osmc: symbol and they replied that it is up to the software to make the osmc: symbol appear even if it is not a route because the data is present on the path
