### ISSUE TITLE
Finer grained speed setting for pedestrians

### ISSUE THREAD

**Issue by MaartenDeen** [osmandapp/OsmAnd#11163]
You can set speeds to use for the route calculation for different profiles. All profiles let you change the speed in 1 km/h steps. I find this for pedestrians not accurate enough. When going on long treks I know I do about 4,5 km/h average so I always have to recalculate my ETA.
Is it possible to change the granularity for the speed for pedestrians to 0,1 km/h?

**Comment by vshcherb** [comment]
> Note: If max speed < 30 SOMETHING, then we need to add 1 decimal to choose.
