### ISSUE TITLE
Download maps: Hamburg (DE) missing

### ISSUE THREAD

**Issue by Heiner-Sch** [osmandapp/OsmAnd#11175]
### Description
In the list of maps to download, Hamburg (DE) is not in.
Also in the select list of the German standard map, it's not in.
But it's possible to download Hamburg via the map.

### How to reproduce?
This happen all time

### Your Environment
OsmAnd Version: ~3.9.8
Android/iOS version: 8.1.0
Device model: bq Aquaris X Pro

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

Here some screenshots of this.
All Downloads:
![AllDownloads](https://user-images.githubusercontent.com/38109491/111355399-a1e86100-8687-11eb-8f48-355138a393a9.png)

Select list of Germany:
![StandardMapGermany](https://user-images.githubusercontent.com/38109491/111355545-c0e6f300-8687-11eb-9329-563c84514d43.png)

My local maps - here is Hamburg in, installed via the map:
![local](https://user-images.githubusercontent.com/38109491/111355668-de1bc180-8687-11eb-8631-fd8050509daa.png)

**Comment by vshcherb** [comment]
Fixed together with https://github.com/osmandapp/OsmAnd/issues/11023
