### ISSUE TITLE
Map keycode “C” to map center function

### ISSUE THREAD

**Issue by morse87** [osmandapp/OsmAnd#11184]
# 🚀 Map keycode “C” to map center function

OsmAnd should have some more keycodes built in to make possible the use of remapping physical buttons to functions.

I list a few important functions and suggest what button keycode to use
- Map Center letter “c” (same as LocusMaps)
- Map Direction. Also some letter, maybe “D

Zooming and scrolling is already built in, so we are good there!

**Comment by nazar-kutz** [comment]
@morse87 Centering the map using the "c" key has already been implemented before. Please check if it works for you.

Can you please explain in more detail what exactly should happen when you press the "d" key.

Thanks for your proposal.

**Comment by nazar-kutz** [comment]
@morse87 I asked because I didn't understand what exactly you mean when asked to implement the "Map Direction" on "D" key press. What does "Map Direction" mean?

**Comment by morse87** [comment]
Hi

Thanks for the answer.

By map direction I mean if the screen upp is showin the direction of
driving or noths. So either the map is rotating or not.
To me, this is the most important button besides C, + and -.

I don't know how this is solved in Locus and other apps. I just offered the
letter D, maybe it should be something else.


Kontakt nazar-kutz ***@***.***>) kirjutas kuupäeval T, 30.
märts 2021 kell 15:09:
