### ISSUE TITLE
Timed conditional access doesn't seem to work

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#11191]
OsmAnd for routing and wanted to correct the routing around https://www.openstreetmap.org/node/5026993763 (which seems correct in my opinion).

OsmAnd should be routing correctly, e.g. if it does take the tags into account.
The bollards are free to pass from 09:00-17:00 and prohibit cars passing from 17:00-09:00

![signal-2021-03-18-113712](https://user-images.githubusercontent.com/1651235/111615235-c572ef00-87e0-11eb-9c7c-1fb901bace40.jpeg)

**Comment by habi** [comment]
Is the underlying issue maybe in the `motorcar:conditional=no @ (17:00-09:00)` tag of the [bollard](https://www.openstreetmap.org/node/5026993763), as this tag is not linked to the OSM Wiki in the view in iD?
As opposed to the `motorcycle:conditional=no @ (17:00-09:00)` tag, which *is* linked to the OSM Wiki?

**Comment by scaidermern** [comment]
> Is the underlying issue maybe in the `motorcar:conditional=no @ (17:00-09:00)` tag of the [bollard](https://www.openstreetmap.org/node/5026993763), as this tag is not linked to the OSM Wiki in the view in iD?
> As opposed to the `motorcycle:conditional=no @ (17:00-09:00)` tag, which _is_ linked to the OSM Wiki?

This sounds like a bug in iD. Should be irrelevant here.

**Comment by habi** [comment]
> > Is the underlying issue maybe in the `motorcar:conditional=no @ (17:00-09:00)` tag of the [bollard](https://www.openstreetmap.org/node/5026993763), as this tag is not linked to the OSM Wiki in the view in iD?
> > As opposed to the `motorcycle:conditional=no @ (17:00-09:00)` tag, which _is_ linked to the OSM Wiki?
> 
> This sounds like a bug in iD. Should be irrelevant here.

On a little bit of further investigation this is maybe not an issue with iD, but with the OSM wiki.
[`motorcycle:conditional`](https://wiki.openstreetmap.org/w/index.php?title=Key:motorcycle:conditional&redirect=no) redirects to conditional access while [`motorcar:conditional`](https://wiki.openstreetmap.org/w/index.php?title=Key:motorcar:conditional&redirect=no) did *not* up to now.
I just created the redirect and will see in some days if this is automatically picked up by iD...

**Comment by vshcherb** [comment]
Changed to motorcar:conditional=yes @ (09:00-17:00), cause barrier bollard is not routable by default, so it will be always non-routable in that case.
