### ISSUE TITLE
RTL issue - Menu misalignment

### ISSUE THREAD

**Issue by iriman** [osmandapp/OsmAnd#11198]
### Description
Locale is RTL like Persian. Items in context menus are misaligned.

### How to reproduce?

1. While no map is available restart app to see download map screen. At bottom choose change storage:

![Screenshot_20210319-022300](https://user-images.githubusercontent.com/8467903/111755724-a93d8380-88ae-11eb-89d4-1da3489a2f71.jpg)

2. In local maps screen, choose three dots button for a map:

![Screenshot_20210106-004332](https://user-images.githubusercontent.com/8467903/111756066-089b9380-88af-11eb-8116-9750c4436ecd.jpg)

3. Open a track. Choose track tab. Scroll up a bit, and choose Options:

![Screenshot_۲۰۲۱۰۳۱۹-۱۱۴۷۵۴](https://user-images.githubusercontent.com/8467903/111756839-e8200900-88af-11eb-8eb5-22e023d44cec.jpg)

### Your Environment
OsmAnd Version: 3.9.10
Android version: 7.1.1
Device model: SM-J510F

**Comment by androiddevkotlin** [comment]
Also fix in other places, for example:

![photo_2021-03-24_23-37-23](https://user-images.githubusercontent.com/64539346/112386793-12cbf080-8cfa-11eb-954e-d50709963273.jpg)

**Comment by dmpr0** [comment]
# Review 
- [ ]  First start: Change folder dialog, second text line should be aligned to the right side.
- [ ] Open track > Tracks > 3 dots menu should be closer to the left screen edge.

<img src="https://user-images.githubusercontent.com/9365308/112640604-26866c80-8e4a-11eb-8fb6-4e40306a62bf.png"  width="300" height="auto"/> 
<img src="https://user-images.githubusercontent.com/9365308/112640592-22f2e580-8e4a-11eb-9ca9-2381047e90fd.png"  width="300" height="auto"/>
