### ISSUE TITLE
Plan a route with map markers in landscape mode crashes OsmAnd

### ISSUE THREAD

**Issue by twikedk** [osmandapp/OsmAnd#11192]
### Description
When using map markers to plan a route being in landscape mode OsmAnd crashes.

### How to reproduce?
Use OsmAnd in landscape mode. Create 2 map markers. Go to map markers and choose plan a route.

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: 10.1
Device model: Huawei Matepad T8

**Maps used (online or offline):**   
offline. Maps was updated 1. March.

**Comment by twikedk** [comment]
Just some additional information:
This happens on both Huawei Android 5.1 and 10.1.
It was working fine in OsmAnd version 3.8.5 on both tested units.

I have attached the exception log for each.

[exception.5_1.log](https://github.com/osmandapp/OsmAnd/files/6176999/exception.5_1.log)
[exception.10_1.log](https://github.com/osmandapp/OsmAnd/files/6177000/exception.10_1.log)


It could very well be related to this earlier reported issue: [https://github.com/osmandapp/OsmAnd/issues/10956](url)

**Comment by cepprice** [comment]
Was fixed [here](https://github.com/osmandapp/OsmAnd/commit/1c4484b44c06c7e33b802b46ab469cf7f03c9061)
