### ISSUE TITLE
Wrong number of submaps in 'split' countries

### ISSUE THREAD

**Issue by tradavyvy** [osmandapp/OsmAnd#11196]
### Description
The map download option for uk states 3 maps
But listed are 4 (england, wales, scotland and n.ireland)
I noticed similar problem with germany

### How to reproduce?
Go to map download page

### Your Environment
OsmAnd Version: latest
Android/iOS version: 10
Device model: samsung a40
![Screenshot_20210319-004405_OsmAnd+](https://user-images.githubusercontent.com/71978409/111711926-f8eb6300-884c-11eb-8697-41c8479741dd.jpg)

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/111789958-fd059800-88c1-11eb-9124-3d8341550121.png)
Fixed in 4.0
