### ISSUE TITLE
[feature request] Have full 3D map

### ISSUE THREAD

**Issue by letypequividelespoubelles** [osmandapp/OsmAnd#11204]
# 🚀 feature request

### Description

OsmAnd is clearly one of the best app for outdoor activities (thanks a lot ! ). The Topo style map, combined with hillshade and contour line is very convenient, but it lacks one (major) option : have a full 3D maps, like the one on the screenshot given (comes from FATMAP app). 

![photo_2021-03-19_17-00-03](https://user-images.githubusercontent.com/54240434/111808771-9b025e00-88d4-11eb-9702-e4bf09eed646.jpg)

This option will be a great help to prepare mountains activities.

I don't know how to use the OSM data to generate a 3D map, and I even don't know if it's doable, but it would be amazing.

Combined with a slope layer (#10989, #11975), OSMAnd will be the ultimate app for all mountan and outdoors activity.

### Describe the solution you'd like

Have an option to switch from 2D to 3D map. I assume the size of the 3D map is much bigger than 2D, so maybe it should be another map to dl, for each region. 

### Describe alternatives you've considered
none.

**Comment by letypequividelespoubelles** [comment]
I found this [API](https://elevationapi.com/playground_3dosm) (and its [github page](https://github.com/dem-net/DEM.Net)). I tried it and it seems awesome. It's free to use for small companies (ie less than 100k€ income per year which is not OsmAnd's case i guess). But I hope that it could be a (paid ? ) add-on for OsmAnd users who want a beautiful 3D maps (I'll be one of them).
@vshcherb Do you think it could be faasible in a "near" future ? 
Thanks all for maintaining OsmAnd and OSM !

**Comment by letypequividelespoubelles** [comment]
It seems it will appear [this year](https://www.reddit.com/r/OsmAnd/comments/rt1a2b/2022_new_year_resolutions/) !

**Comment by letypequividelespoubelles** [comment]
And it's there ! Thank you!

**Comment by michaelblyons** [comment]
Is this more than the tilt? If so, can you screenshot and describe how to enable?

**Comment by letypequividelespoubelles** [comment]
First, it's a paid feature, so you need to buy OsmAnd pro (or via FDroid).
Second, it's still in beta, so still not perfect.
To enable it you need (for v4.3.3 from Fdroid) :
- activate openGL (rending engine n2)
- activate heighmlap (available in the Dev plugin)
- DL heightmap of the chosen region (still not available everywhere : France has it, India not for example).
- enjoy and thanks OsmAnd.

**Comment by michaelblyons** [comment]
Ah. I see. No height map for United States.

**Comment by vshcherb** [comment]
Yes we'll generate for US

**Comment by michaelblyons** [comment]
> Yes we'll generate for US

Soon? Or still working on stuff?
