### ISSUE TITLE
RTL issue - Applying correct text direction (ltr or rtl)

### ISSUE THREAD

**Issue by iriman** [osmandapp/OsmAnd#11212]
### Description

4 places that need attention:

1. Terrain menu:

![Screenshot_۲۰۲۱۰۳۲۱-۰۰۲۳۳۱](https://user-images.githubusercontent.com/8467903/111885602-03893200-89de-11eb-9e06-ec4852ff7f80.jpg)

Description should be rtl. It's just right-aligned.

2. Direction of coordinate format in settings is correct (#7721).
But in context menu it is displayed "right to left" and should become left to right to be displayed correctly. Here I don't prefer the ltr_or_rtl_combine_via_ method, because in addition to view, we sometimes copy them to use elsewhere (another app, web, …) so it's better to have no hack on its text. Forcing ltr direction for it is a good choice.

![Screenshot_۲۰۲۱۰۳۲۱-۰۰۵۷۳۲](https://user-images.githubusercontent.com/8467903/111886098-f457b380-89e0-11eb-9024-b1dd72b77b81.jpg)

3. Also after copying a coordinate, a toast is generated. Its first line is a rtl text that is displayed correctly. Second line is the coordinate and should be ltr.

![Screenshot_۲۰۲۱۰۳۲۱-۰۱۰۱۴۲](https://user-images.githubusercontent.com/8467903/111886178-865fbc00-89e1-11eb-9c20-3befedb12160.jpg)

4. Settings > OsmAnd Settings > Storage.
Path line is right to left while its direction should be left to right for readablity (and preferably left-aligned).

![Screenshot_۲۰۲۱۰۳۲۱-۰۱۰۷۲۶](https://user-images.githubusercontent.com/8467903/111886469-dee38900-89e2-11eb-9f0f-7b18056ac3f4.jpg)

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: 7.1.1
Locale: Persian

**Comment by dmpr0** [comment]
## Review
- [ ]  Data storage folder show second slash "/" for path goes to the second line.
![Снимок экрана 2021-03-29 в 16 53 02](https://user-images.githubusercontent.com/9365308/112846937-3f438c00-90af-11eb-9bff-22c5d5291ab8.png)

- [ ]  Please re-check the "Terrain" menu empty state, it looks strange, why URL is on the first line?
![Снимок экрана 2021-03-29 в 16 56 13](https://user-images.githubusercontent.com/9365308/112847536-d90b3900-90af-11eb-9dac-4d4f768daaac.png)
