### ISSUE TITLE
GPX Menu: Time in Motion Info about GPX 

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#11215]
It needs to add next information from 'Analyze split intervals':
-Time in motion
-Min/max altitude
![image](https://user-images.githubusercontent.com/44466116/111906972-56a5c800-8a64-11eb-9ce9-9d1f0fb169ee.png)

To Overview track menu

![image](https://user-images.githubusercontent.com/44466116/111907036-9f5d8100-8a64-11eb-872a-ec5b3edc7a83.png)

**Comment by Skalii** [comment]
[New statistics blocks in GPX Overview](https://github.com/osmandapp/OsmAnd/pull/11256)

**Comment by dmpr0** [comment]
# Review 
- [ ]  We need to select one string for the info item. On the "Overview" tab we named it "Time in motion" but on the "Tracks > Speed" it uses the "Time moving" string.

![Group 136](https://user-images.githubusercontent.com/9365308/112814507-0a700e80-9088-11eb-84c6-92528bbee268.png)

**Comment by Skalii** [comment]
[Fix "Time in motion" elements](https://github.com/osmandapp/OsmAnd/pull/11290)
