### ISSUE TITLE
Navigation dialog laggy

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#11229]
Latest nightlies show laggy behavior when tapping the Directions button (5 sec for the Directions dialog to appear) or then the Cancel or Dismiss button (8 sec before the dialog disappears again).

**Comment by sonora** [comment]
It reminds me of #6740, but this time round it seems independent of whether GPX tracks are shown or not.

Interestingly renough, canceling out of the Directions dialog is immediate **while** the route is being calculated, laggy once the route has been calculated but navigation is not started yet, and immediate again once navigation is in follow mode.

**Comment by vshcherb** [comment]
I confirm Cancel is rather laggish

**Comment by sonora** [comment]
I just notice that tapping the map screen's search button seems also affected,  takes about 5 sec now to show the search screen.

All this is on devices with many favorites and many tracks, not sure if that matters. Also: The issues was introduced after March 12.

**Comment by vshcherb** [comment]
Then probably it's related to favorites & tracks, cause it's not clear yet...

**Comment by sonora** [comment]
This https://github.com/osmandapp/OsmAnd/commit/15326798b17d62d5266e2f1cf13ad8cb517edd5d, i.e. using the dbHelper instead of direct db access, solved the former occurrence of the very similar bug #6740. Since we now play with route line color, could we have introduced the same problem again?

**Comment by sonora** [comment]
I suspect here is where we introduced it; https://github.com/osmandapp/OsmAnd/commit/5f9047cc6d6b3944a5c1dc4041c62bbf2796bed5

**Comment by vshcherb** [comment]
Probably it's possible to create design build with a specific commit hash https://github.com/osmandapp/OsmAnd/commits/master?after=3f0803eb083e24b62f95d8ecbb6c79f20b502a91+489&branch=master

**Comment by vshcherb** [comment]
I suspect only this functionality related to tracks - https://github.com/osmandapp/OsmAnd/pull/11035/files

**Comment by sonora** [comment]
I have now uninstalled the app, then reinstalled it. Just like observed in #6740 at the time, the issue has entirely dissappeared for now, even after re-instating the same 4 digit number of favorites and tracks. Will report if the issue reappears.
