### ISSUE TITLE
Contour lines disconnected

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#11225]
### Description
Near the location:
49.75510 19.00017
Error in displaying contour lines, the lines are not connected, they are interrupted.
![Screenshot_20210320-200640_OsmAnd+](https://user-images.githubusercontent.com/80623554/112012393-d77ec580-8b31-11eb-85cd-b480075c8814.jpg)

### Your Environment
OsmAnd Version:
Android/iOS version:
Device model:

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by xmd5a2** [comment]
These artefacts are negligible

**Comment by sonora** [comment]
It looks like there as up to 20 vertical meter jumps between tiles??

**Comment by letypequividelespoubelles** [comment]
@xmd5a2 Does that mean that you won't fix it ? I just had same issue, in France Grand Est april map
![photo_2021-04-15_23-41-11](https://user-images.githubusercontent.com/54240434/115555469-d4513380-a2af-11eb-98b4-3ec7c7e41e34.jpg)

**Comment by xmd5a2** [comment]
@letypequividelespoubelles It will be partially fixed in next contour maps generation but most of lines at the edges of 1x1 degree tiles will remain disconnected. I don't see how this can be fixed entirely. And I don't consider this a serious issue.

**Comment by Artoria2e5** [comment]
The contour code is at https://github.com/osmandapp/OsmAnd-tools/tree/master/obf-generation for anyone wanting to take a look.

**Comment by vshcherb** [comment]
These artifacts due to tiles & processing of SRTM imagery. They won't be fixed cause would require lots of efforts
