### ISSUE TITLE
Lake havasu doesn't render at higher zoom levels

### ISSUE THREAD

**Issue by Busterama452** [osmandapp/OsmAnd#11239]
### Description
Lake havasu in Arizona usa does not render at higher zooms.  It just disappears.

https://www.openstreetmap.org/relation/374012#map=10/34.4101/-114.2512

### How to reproduce?
Go to 34.48498° N, 114.38162° W

Zoom in and out.

### Your Environment
OsmAnd Version:
Android/iOS version:
Device model: samsung galaxy note  sm-n960u. Android 10 

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

Offline maps for both arizona and california.  I ran loaded recent update, loaded live update.  Even deleted and added the maps.

**Comment by sonora** [comment]
To whoever investigates: Perhaps an issue with recent maps, I run our latest nightly, but with Arizona map of 9/1/2020 and California 3/1/2020, no OsmAnd Live in play, have no issue at all displaying the lake at any zoom level.

**Comment by xmd5a2** [comment]
Role of https://www.openstreetmap.org/way/68695896 was inner instead of outer in Lake Havasu relation (https://www.openstreetmap.org/relation/374012). Fixed in OSM.

**Comment by sonora** [comment]
Well spotted, thanks, Leonid!
