### ISSUE TITLE
Maneuver icons on the map

### ISSUE THREAD

**Issue by pajakgdynia** [osmandapp/Osmand#1124]
There is a nice feature like guidance over the GPX track (with audio).
The only issue is that navigation lose some turns, etc. It is quite difficult to check the route, using prev/next point does not give expected info (it is very easy to miss some turns, etc). Long route simulations is "a bit boring" (especially for long routes).
Possibility to show "actions" on the map (in '0' point) would be very useful. Adding/removing points and/or changing the message would be complete solution for the issue.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/issues/1165
