### ISSUE TITLE
N Evergreen Rd in wrong city

### ISSUE THREAD

**Issue by Hello71** [osmandapp/Osmand#1125]
https://www.openstreetmap.org/relation/171019#map=16/40.5582/-74.3339  
https://www.openstreetmap.org/way/229990593

OsmAnd shows "North Evergreen Road" as in "Metuchen", but the actual road is in "Edison" (township). There is no Edison city in OsmAnd, only one of the two hamlets.

Searching by zip code (08837) also does not show the street. "Search nearby" is required to find it. I do not know whether this is a bug in OSM or OsmAnd.

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/Osmand/commit/acb3b5eae02644b25427ea21ff84e7cb7cab2632
