### ISSUE TITLE
Rename "Configure Screen" to "Widgets"

### ISSUE THREAD

**Issue by Ungoose** [osmandapp/OsmAnd#11253]
# 🚀 feature request

### Description

The name of "Configure screen" option is somewhat misleading as it doesn't really configure the screen (which would involve things like resolution, color palette, and orientation). What it does is allows selecting widgets, and I personally spent a lot of time wandering around the settings before I memorized where to look for them.
### Describe the solution you'd like

Rename "Configure Screen" to "Widgets"

**Comment by muchuelo** [comment]
Seconded. Makes perfect sense.

**Comment by vshcherb** [comment]
That's a plan

**Comment by vshcherb** [comment]
Probably "Map widgets" like in documentation - https://docs.osmand.net/en/main@latest/osmand/widgets

**Comment by Ungoose** [comment]
I'd say _Widgets_ is better than _Map widgets_ (it's not like there are other widgets around and we need to differentiate between the two). Still, even _Map widgets_ is way better than _Configure screen_.

**Comment by oleksandr-nechyporenko** [comment]
"Widgets", or probably "Configure Widgets" (to be consistent with "Configure Map") is definitely much clearer than "Configure Screen". BTW, we also have have "General Settings -> Appearance" which is the third part of puzzle. To be honest (very very IMHO) I was always confusing why there are 3 places from where presentation aspects configured and it always takes couple of seconds to remember which of 3 menu items should be selected to change something. For example, Map Mode which is under the "Configure Map" also affects UI, in the same time App Theme (Dark / Light) is under general settings.

**Comment by Ungoose** [comment]
> To be honest (very very IMHO) I was always confusing why there are 3 places from where presentation aspects can be configured and it always takes couple of seconds to remember which of 3 menu items should be selected to change something.

Exactly. The settings are a labyrinth, and there are many more places that need renaming and rearranging - this is just one of the more apparent ones.

> probably "Configure Widgets" (to be consistent with "Configure Map")


I would advice against "configure widgets" though. "Configure map" and "configure screen" are the only two options on the list that follow this naming convention, and in my opinion the word "configure" is not necessary at all - for example, we don't use "Configure trip recording," "configure profile," or "configure UI." In fact, I'd argue that "Map appearance" would be more consistent (in line with Profile appearance and UI customization).

**Comment by oleksandr-nechyporenko** [comment]
Actually, "Configure Map" currently contains two logical sections:

- What to display, which can be considered as Map Layers
- How to render (styles, fonts, colors), which can be considered as Map Appearance.

So, not sure, if "Configure Map" should be renamed to "Map Appearance" with existing set of settings.

Another part of appearance configuration is located under the general settings in profiles.

Probably, on the main manu level and in profiles it can be grouped as:

- Layers (or Map Layers) (where we can select which map layers to display)
- Widgets (where we can select which widgets to display)
- Appearance (where we will tune how to render, including styles, fonts, colors, map style, day / night mode, etc. It can contain two logical subgroups: Interface Appearance and Map Appearance).

What do you think?

**Comment by Ungoose** [comment]
I think that rearranging the menu items is a great idea that would make OsmAnd less convoluted and more accessible - but that topic probably requires a separate issue.
My original point was that _Widgets_ is a better name than _Configure widgets_ - the word "configure" does nothing for the UI apart from making it inconsistent and it would be much better to remove it from _Configure map_ as well. _Map appearance_ may not be the perfect alternative but I certainly don't see a problem with it - in my opinion, the "what to display" is a part of what I would describe as appearance, and finer details about layers, styles, fonts, colors, etc. can be mentioned in the description (which currently just says "map appearance," btw).

**Comment by dmpr0** [comment]
Configure screen will allow to add/edit widgets, map button and screen alerts in the future.
