### ISSUE TITLE
TravelGuide 'header' image isn't matching the WikiVoyage one

### ISSUE THREAD

**Issue by ArjanOnwezen** [osmandapp/OsmAnd#11262]
### Description
TravelGuide 'header' image isn't matching the WikiVoyage one. The ones on WikiVoyage better reflect the place mentioned. The ones on TravelGuide are often pictures of train stations.

### How to reproduce?
Go to article Vijfheerenlanden (or many others) and compare header image of WikiVoyage with TravelGuide.
See also screenshots.
![IMG_20210326_081853](https://user-images.githubusercontent.com/44684169/112596658-66c6fa00-8e0c-11eb-957a-3558e793cd24.jpg)
![IMG_20210326_081834](https://user-images.githubusercontent.com/44684169/112596661-67f82700-8e0c-11eb-8013-9a17ea4d7a4e.jpg)

### Your Environment
OsmAnd Version:
Android/iOS version:
Device model:

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by Dima-1** [comment]
It fixed in the new version of TravelGuide files, you can already update

**Comment by ArjanOnwezen** [comment]
Thanks for responding so quickly. This indeed is fixed in the latest update.
