### ISSUE TITLE
Night mode: text unreadable (Android 10, LG)

### ISSUE THREAD

**Issue by Famlam** [osmandapp/OsmAnd#11269]
### Description
Check the details of a planned route in night mode (ex. the type of surface). It's a black text on dark background.
![Screenshot_20210326-203130](https://user-images.githubusercontent.com/1315520/112684025-bf30e280-8e72-11eb-896d-f5086dbedf9e.png)

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: Android 10
Device model: LG

**Maps used (online or offline):**   
N/A

**Comment by androiddevkotlin** [comment]
Already fixed on 3.9.9

![photo_2021-04-08_23-41-49](https://user-images.githubusercontent.com/64539346/114093622-03d16a80-98c4-11eb-8119-1c478d24cb6c.jpg)

![photo_2021-04-08_23-41-44](https://user-images.githubusercontent.com/64539346/114093625-046a0100-98c4-11eb-8193-b0ba2c2a91cc.jpg)

**Comment by Famlam** [comment]
But... I see this issue on 3.9.10, meaning it's a regression
