### ISSUE TITLE
Update Approximate map coverage and quality table

### ISSUE THREAD

**Issue by tbertels** [osmandapp/OsmAnd#11267]
That table data below was added back in 2013 9fb2a0f22df3a311e6b36f72ca8fb56a3d3b0e5f

The data source isn't mentioned. But since then, there have been newer studies.
Like this one in 2017: http://wellbeing.ihsp.mcgill.ca/publications/PLOS2017roads/ which includes this streets coverage map: http://wellbeing.ihsp.mcgill.ca/publications/PLOS2017roads/figures_2017_update/OSMmap-frcComplete_best.svg

![World Map](https://user-images.githubusercontent.com/3265870/112626435-7c4e1b00-8e30-11eb-9693-a89b655a6979.png)

There is probably newer data than 2017.

See also https://wiki.openstreetmap.org/wiki/Completeness

Current README table:
**Approximate map coverage and quality:**
| Region         |      |
|----------------|------|
| Western Europe | ++++ |
| Eastern Europe | +++  |
| Russia         | +++  |
| North America  | +++  |
| South America  | ++   |
| Asia           | ++   |
| Japan & Korea  | +++  |
| Middle East    | ++   |
| Africa         | ++   |
| Antarctica     | +    |

**Comment by sonora** [comment]
In deed, thanks for bringing this up, this certainly deserves an update after so many years. I am thinking that a continent/country list is not needed any more here, instead I could imagine we put some descriptive text along these lines, what do you think:

_**Map Coverage and Quality - How Good is OSM Data?**_

_According to research, OSM map data rivals and often surpasses commercially available maps both in terms of data completeness and data actuality. This is indicated by different metrics like the amount of road distance mapped, or the number of objects like points of interest or buildings mapped. The fact that the maps are globally crowd-sourced ensures continuous improvements and updates, the incorporation of local on-the-ground expertise, and reflects things like neighborhood development, ongoing construction, or even the results of recent natural disasters._

_Comparing the different metrics, it is safe to say that OSM maps cover all continents and countries globally for all your travel needs, and you will find their quality and completeness nothing less than stunning in the vast majority of countries. Latest research mentions only few countries in continental Asia and central Africa where e.g the incorporation of a noticeable portion or roadways is still ongoing to catch up with the high levels already reached anywhere else._
