### ISSUE TITLE
Nightly builds could use same maps as normal or beta app 

### ISSUE THREAD

**Issue by miramikes** [osmandapp/OsmAnd#11271]
Hello,

it would be great if "nightly builds" could use same maps as normal app it would be save space on user's devices and could make testing of new features somewhat easier (at least less downloading) .
If someone have AndOsm+ installed also unlimited number should be allowed.

best regards

mira

**Comment by JonnyTech** [comment]
In settings, set the data storage folder to be the same for both.

![Screenshot_20210327-052649_OsmAnd~](https://user-images.githubusercontent.com/3584732/112711001-1b205900-8ebd-11eb-9be5-25a753726f3d.png)

**Comment by miramikes** [comment]
Tried, but not works here :( ... Having "Multiuser storage 1" in both apps but "nighly build" don't see any map ...
m.

**Comment by JonnyTech** [comment]
Is the path displayed for both the same? Sometimes builds label storage 1/2 differently. Please compare.

**Comment by miramikes** [comment]
Paths are different:
/storage/emulated/0/Android/data/net.osmand.plus
/storage/emulated/0/Android/data/net.osmand.dev
I have only 1 External and 1 Multiuser storage on my device.
m.

**Comment by JonnyTech** [comment]
Use the `Manually specified` option to select the same folder for both.

**Comment by miramikes** [comment]
I can't to get it work whatever I am doing ... I am getting message that operation failed :(
Maps couldn't be created in specific directory ...

**Comment by JonnyTech** [comment]
Permissions issue? `Download` folder should be available to all. Make a `maps` folder there and set it manually for both OsmAnd builds.

Or locked files? Make sure each OsmAnd build is fully closed (or force close) before starting the other.

I have neither issue with my device so maybe it is something specific to your system / ROM.

**Comment by miramikes** [comment]
You were perfectly right ... permissions issue ... Works well now.
Thank you !!!

**Comment by JonnyTech** [comment]
Great, thanks fot confirming. Please close this issue.
