### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by khaled-ib** [osmandapp/OsmAnd#11315]
hello
i really do love your app.
and want to suggest something most really want it specially off-road navigation.
i bought this app for my iphone and also for my car android screen, in the car android screen for map markers, if i want to enter coordinates, will go to map markers then other then enter coordinates, it’s easy but the annoying after entering the coordinates i need to name it, and where to save it then need to search for it again , hope if there is a choice GoTo if i enter the coordinates then it immediately go to it, it’s simple and easy and many will love it and hope it will be added to ios as well.
great job and thanks

**Comment by Ungoose** [comment]
Have you tried entering the coordinates into the search field? You will immediately go to the point you are interested in and can place a marker there if you want (no renaming or saving required) or just not mark it at all. Sounds close to what you want.
