### ISSUE TITLE
Same destination time is wrong for different profiles

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#11318]
### Description

When we create a route by Plan a route using a Cycling profile (for example) and after that, we choose this GPX-track for our routing (Follow track), we see that "Time to go" will be one for all Navigation profiles. It will be for our Cycling Profile 38 min for our case.

![image](https://user-images.githubusercontent.com/44466116/113325725-791bc900-9321-11eb-83ce-6ff7097b6539.png)

![image](https://user-images.githubusercontent.com/44466116/113325737-7ae58c80-9321-11eb-82c9-6641117348ee.png)

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: 11
Device model: S10e Samsung

[Thu 01 Apr 2021.zip](https://github.com/osmandapp/OsmAnd/files/6245022/Thu.01.Apr.2021.zip)

**Comment by Sirsil** [comment]
Same issue: create a route by Plan a route using a profile (whatever). Time to go seems to correspond to the pedestrian profil, even if Moto / Auto profile is selected. (25 min for 2,8 km).
![OSM1](https://user-images.githubusercontent.com/83861721/117533162-92ccc200-afeb-11eb-9880-11edffa6a8ff.jpg)
![OSM2](https://user-images.githubusercontent.com/83861721/117533163-93655880-afeb-11eb-90bf-a6918d1f0330.jpg)
![OSM3](https://user-images.githubusercontent.com/83861721/117533164-93fdef00-afeb-11eb-8426-c287d2686bfe.jpg)

**Comment by vshcherb** [comment]
Routing time is 7 h !!! 
[Osterfeine-Steinfeld.gpx.zip](https://github.com/osmandapp/OsmAnd/files/6509940/Osterfeine-Steinfeld.gpx.zip)

**Comment by Artur-debug** [comment]
https://github.com/osmandapp/OsmAnd/issues/11730#issue-897416725
