### ISSUE TITLE
Route statistics (ascent/descent) in Plan Route

### ISSUE THREAD

**Issue by littlehelper** [osmandapp/OsmAnd#11326]
# 🚀 feature request

### Description

The plan route functionality is perfect for planning a biking or hiking route. After saving the planned route as GPX file, when viewing the GPX details, a lot of statistic is shown.
It would be very handy if similar statistics would be shown and updated live while planning the route.

### Describe the solution you'd like

Please show statistics of route (similar to statistics of GPX tracks) while planning within plan route. Live updating of details like expected distance, ascent, descent and travel time would be helpful when adding/moving/removing a route point. It would enable to immediatelly identify what distance, ascent etc. is added by the last edited section.

### Describe alternatives you've considered

The current solution (I know) is to plan the route first, save the route, view route details to see statistics. If the route is too long or hard due to e.g. too much ascent then editing the route is possible but it may take some iterations until the best route is found.

Thanks.

**Comment by littlehelper** [comment]
Similar to or dublicate of #7096?

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/113915212-c5ae4b00-97de-11eb-94a7-d3ed03ca06f7.png)
Should be available already in 3.9 or 4.0 if it's not

**Comment by littlehelper** [comment]
@vshcherb Is there a plan to show track/route summary fields   (e.g. summary of ascent/descent) like in GPX track details too?
Thanks.

**Comment by vshcherb** [comment]
Yes there was a misunderstanding, will reopen the issue

**Comment by dmpr0** [comment]
# ToDo
We need to finish the task, add a statistic block below all graphs.
- [ ]  Statistic below "Overview, Altitude graphs similar to track context menu
- [ ] Information about route segments, similar to "Route details"
