### ISSUE TITLE
Feature Request: External temp sensor (Garmin Tempe) Widget

### ISSUE THREAD

**Issue by Cargotourer** [osmandapp/OsmAnd#11324]
Hi,

I have a Galaxy Xcover Pro phone which supports Ant+ sensors, including my newly purchased Garmin Tempe. I have purchased Osmand+.

However, to read the Garmin Tempe, it needs the app to support such a feature. My bike computer app (Jepster) can do so, but ideally, I'd like Osmand+ to do so instead, so I don't have to open the bike computer app to get the temperature.

I'd like to have it implemented as a widget - either on the right or left or in the "drawer" (doesn't matter to me). It would be nice to be able to have the temperature shown.

The reason I would like to be able to view the Garmin Tempe temperature rather than some internal sensor, is that the sensor can be put in the shade, resulting in much more accurate readings.  As it is, I cannot choose _any_ temperature, internal or not.

Some of the ant+ framework must already be there as the app allows me to search for ANT+  heart rate monitors (which I don't use), but I'd like it to support the ANT+ temperature sensor too. 

I hope you will consider this for a future update.

Kindest,
A cargo bike tourer and commuter from Denmark.

**Comment by zipper11** [comment]
@vshcherb Is it possible to develop general Ant+ sensor support while developing this feature? Implementing features like #11334 will be easier?

**Comment by vshcherb** [comment]
Yes we plan exactly to implement generic Ant+ devices support

**Comment by vshcherb** [comment]
Merged to #11334
