### ISSUE TITLE
Support for external sensors (i.e. heart rate sensors) - ANT+

### ISSUE THREAD

**Issue by zipper11** [osmandapp/OsmAnd#11334]
I would like to see support for external sensors like heart rate monitors or cadence sensors via bluetooth and ANT+. This would help while training on the roadbike.

Being able to see your real time heart rate while riding would be awesome!
Any plans for the future?

**Comment by Cliveptr** [comment]
I feel like it's probably out of the project's scope, but couldn't somebody write a plugin?

**Comment by zipper11** [comment]
For normal riding with your bike OsmAnd works really well. I think this feature is very essential for serious riders. Being able to connect sensors to see my HR or cadence speed would be a great enhancement.

**Comment by Cliveptr** [comment]
If you're using Android you might be able to find an app that has an overlay with the information you want. The first one that came to mind is RunnerUp but I don't think it can do that. Also maybe FitoTrack.

**Comment by zipper11** [comment]
That's a solution, but not ideal. The gpx/tcx ride recording file will not contain the HR data which is a hassle when you want to do some analysis.

**Comment by zipper11** [comment]
@vshcherb merge https://github.com/osmandapp/OsmAnd/issues/7934 into this one? I think both are the same feature requests.

**Comment by vshcherb** [comment]
Indeed following the oldest one
