### ISSUE TITLE
What's the purpose of a Favorite's time tag?

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#11331]
I notice that my _favourites.gpx_ files which I periodically backup from OsmAnd's data folder is recently blown up to some degree by the incorporation of time tag like `<time>2021-03-02T00:03:22Z</time>` for each favorite.

The content of the tag is the same for all favorites. I am a little clueless why we introduce such data, what it should mean, or be good for? (It definitely is not the creation time of the favorites for all cases I have checked ...).

**Comment by pebogufi** [comment]
https://github.com/osmandapp/OsmAnd/pull/10998 
https://github.com/osmandapp/OsmAnd/issues/2869
I suppose, this issue is not finished. 
Currently in my favourites.gpx all points have a time tag and more than 95 % with the **same** time tag contents.

**Comment by sonora** [comment]
Yes, looks like the code change on Mar 1 uselessly modified all my older favorites with time stamp `<time>2021-03-02T00:03:22Z</time>`.  :(

**Comment by pebogufi** [comment]
If i have a gpx file with only wpt, (used as "outsourced" favourites) and change+save a wpt, it also gets a time flag. I suppose, this also is a change of about beginning of march.

**Comment by vshcherb** [comment]
It's a bug that it set the wrong date but there is no way to save correct date. Indeed it's kind of irreversible and it solved the issue of - https://github.com/osmandapp/OsmAnd/issues/2869. So I guess we couldn't take any action here

**Comment by sonora** [comment]
Are you saying it it was a one time problem and is fixed now?

I took my favourites.gpx file, removed all time stamps, then deleted all favs and re-imported from the cleaned file.

Turns out the newly created favourites.gpx file again contains useless time stamps for all favs. I don't think we should leave that behavior in place?

**Comment by vshcherb** [comment]
This is a correct behavior, it displays first occurrence of the point (import or creation), obviously it couldn't retrospectively guess the point time creation. The functionality of storing "time" was introduced on purpose by request and there is nothing wrong (even useful sometimes) to have info when point was created.

**Comment by pebogufi** [comment]
When sharing my favourites.gpx to a second device,  I don't want that the time tag will be changed by import in second device.
So please don't change time, if time is already existant in favourites.gpx.

**Comment by vshcherb** [comment]
yes, agree, it should be last modified time

**Comment by pebogufi** [comment]
> yes, agree, it should be last modified time

@vshcherb   Please be so kind to reopen. 
Thanks Peter

**Comment by vshcherb** [comment]
Why do I need to reopen? It is already last modified time or not?

**Comment by pebogufi** [comment]
As I stated above: 
When sharing my favourites.gpx to a second device, I don't want that the time tag will be changed by import in second device.
So please don't change time by import, if time is already existent in favourites.gpx, just use time from file.

**Comment by vshcherb** [comment]
it won't be changed, ```time tag``` will be processed and set once for all devices

**Comment by pebogufi** [comment]
Here you find a test

  <wpt lat="48.5786667" lon="13.473959">
    <time>2001-01-01T10:00:01Z</time>
    <name>AA test WPT</name>
    <type>A TEST Grp</type>
  </wpt>
[test import wpt.zip](https://github.com/osmandapp/OsmAnd/files/6309186/test.import.wpt.zip)

After import with file manager, select osmAnd, import as favourite, 
then after import close osmand. 
Then open favourites.gpx and search for the wpt. Look at time tag, it will be **current datetime of import**, but **not the create date** like above     <time>2001-01-01T10:00:01Z</time>
What I want is that the time tag will be UNchanged during import. 
If it is changed on every import, the tag is useless.
