### ISSUE TITLE
Analyze on map shows wrong header

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#11337]
(1) I know of at least 4 ways now to enter a track's 'Analyze on map' functionality: Using any of the first 3 results in the functionality showing the track's name on the top of the map screen:
- MyPlaces/Tracks/3-dots context menu/Analyze on map
- Tap a track on the map/tap on button Analyze on map
- Tap a track on the map/Open track/Options/Analyze on map

But this one produces header 'Current track' at the top of the map screen:
- Tap a track on the map/Open track/Tap on any of the statistics buttons e.g. the distance.

(2) This latter functionality is also rather hidden, it is not visible that the stats display doubles as a button.

(3) Further, we may want to evaluate if there are not too many different ways by which we offer to enter this functionality? This creates a degree of clutter in the UI and in the code, and different convoluted user experience and support cases?

**Comment by vshcherb** [comment]
- Yes we need fix to it the name and blue button
 - Yes,  I was not aware of that functionality as well and it is rather hidden
 - I see no problem with hidden functionality if it only helps to discover it. Obviously 'Analyze on Map' should look always the same, 2nd question what could be displayed here instead in future
I feel it could be a combination of "Smoothen Setting" with graph screen. 
For now we don't compute uphill / downhill sometimes correctly and average speed could be messed up with "wrong" points. Obviously screen where you could tune how much original Track information should be filtered out / smoothen could be displayed here and tuned, so the Statistics would look more realistic.

**Comment by sonora** [comment]
Regarding
> - Yes, I was not aware of that functionality as well and it is rather hidden

that's why already in #10746 I had suggested:

> - We can give the statistic (number) tiles (Distance, Ascent, etc.)) a more button-like look, indicating that they are tappable (much like we do for the action buttons below)
