### ISSUE TITLE
Include track search in OsmAnd searchh

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#11341]
While you can search tracks using the search box on MyPlaces/tracks, searching for tracks does not work from the general search button on the map screen.

(Not even if a track is in the search history there. But searching favorites works.)

**Comment by sonora** [comment]
Thanks for fixing this, it works now! 

But I just notice that both favorites and tracks are only found **if already displayed on the map**. This means that the feature can e.g. not  genetally be used to locate a certain recording or tour in your tracks folders, I guess we should still improve that?

**Comment by vshcherb** [comment]
You mean search all waypoints from all tracks?

**Comment by dmpr0** [comment]
Review
- [ ]  Search results jump while loading, I tried to search for "Mon ", search show tracks as top results, second later they two times moved down and were replaced with other search results

**Comment by sonora** [comment]
I think this is well implemented now, thanks to everyone!!
