### ISSUE TITLE
London address search issue: interpolation is not tagged  properly

### ISSUE THREAD

**Issue by daslondon** [osmandapp/OsmAnd#11346]
### Description
When entering an address in the search field, e.g. the ones mentioned above, many choices come up, the top few often being completely wrong. One needs to look down a long list to find the right address, if it appears at all.

Why, for example, is “292 Westbourne Grove, London” not the top option when entering the address like that?

Why are “London Road – Westbourne Grove, Southend-on-Sea” (which is dozens of miles away) and “Westbourne Grove Mews, London” the top three options, with “Westbourne Grove Mews, London” appearing twice?

At option 8 I see “292 Westbourne Park Road (City of Westminster), London” and only at no. 9 do I see “288-292 Westbourne Grove (City of Westminster), London”.

And below that I see two options “Westbourne Grove, Kensington”.

Having now done a new search for the same address I see that the original top recommendation of “London Road – Westbourne Grove, Southend-on-Sea” has disappeared. It should never have appeared there in the first place.

Now the top two are “Westbourne Grove Mews, London”. Still not correct, of course.

Presently I am sitting at my desk at home in London, but I have had to wrestle with this sort of thing when travelling in other parts of the country.

Why is the selected address not the top (or second, at most) option, when it is a unique address?

There is no such problem on HERE WeGo or Google Maps on my phone.

On Google Play I saw a number of recent reviews highlighting this address-search problem.

=>The address-search feature badly needs to be improved!

Sometimes I use OpenStreetMap on my desktop and do not have such issues. The borough boundary is correctly shown there, too.
=>Since your app is based on OpenSteetMap, how come you do have these problems?

### How to reproduce?
Search for an address.

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: Android 10
Device model: Samsung Galaxy A50

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
Online

**Comment by letypequividelespoubelles** [comment]
In previous OSMAnd version, there was an online address search, pretty effective. It should be back a day, see #10463 & #7716

**Comment by vshcherb** [comment]
https://nominatim.openstreetmap.org/ui/search.html?q=292+Westbourne+Park+Road+%28City+of+Westminster%29%2C+London
https://nominatim.openstreetmap.org/ui/search.html?q=292+Westbourne+Grove%2C+London

**Comment by daslondon** [comment]
Hello vshcherb

I am not sure what you are trying to say.

DAS
--

**Comment by vshcherb** [comment]
The problem lies in OpenStreetMap tagging (addr:interpolation is not tagged properly) - https://www.openstreetmap.org/way/357280496. We plan to add simple cases so it will be supported

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/115253288-87911f80-a12c-11eb-87ab-bb84d5e9a5d4.png)
