### ISSUE TITLE
Background downloading of offline maps

### ISSUE THREAD

**Issue by Mosrite** [osmandapp/Osmand#1134]
Hey,
I think it would be great if offline maps could be downloaded in the background. Download progress could be indicated with a notification. At the moment, downloads often get interrupted if the app gets accidentally closed or something.
Thanks for considering my suggestion! :)

**Comment by alexandrz** [comment]
Also it would be great if it was possible to continue interrupted download. I tried to download a map of India for a week being in Nepal, and I couldn't get it even sometimes I got up to 70%.

**Comment by leszekr** [comment]
+1 still unable to download a 160MB map of my area.

**Comment by POTION4** [comment]
Yeah, in order to download I must keep this app running foreground. Thats a little bit annoying.

**Comment by homersimpsons** [comment]
Maybe implement torrent download to download map by segment and allow user to upload map file with computer and/or mobile phone.

**Comment by untitaker** [comment]
OsmAnd could use the Android download manager for this, which as far as I understand does properly keep itself in device memory. But I'm just armchair engineering here.

**Comment by ADepic** [comment]
Is this fixed yet?

**Comment by vshcherb** [comment]
I think it takes quite a lot of effort, the download process is very cumbersome and includes several steps: streamlined unzipping, indexing maps. As of today the application should not be closed during download.

**Comment by Chumva** [comment]
Background downloading should work better now after this fix - https://github.com/osmandapp/Osmand/pull/7050.
