### ISSUE TITLE
subway stations - incorrect name in English

### ISSUE THREAD

**Issue by z-z-z88** [osmandapp/OsmAnd#11367]
### Description
https://www.openstreetmap.org/node/763045997
When map language is English and transliteration option is off, instead of "Subway station" it showes   "stantsiia mietro" 
![Screenshot_20210408-142454](https://user-images.githubusercontent.com/38129009/113989885-11aecd80-987b-11eb-911c-8987c6f5a39f.png)

If you switch map to other languages, for example Spanish, and turn on transliteration, it shows name in Russian.

### Your Environment
OsmAnd Version:3.9.10 
Android/iOS version:7.0 
Device model:Huawei P9

**Comment by vshcherb** [comment]
Same as https://github.com/osmandapp/OsmAnd/issues/11362

**Comment by z-z-z88** [comment]
> 
> 
> Same as #11362

No, it is very different. In #11362 it shows different object, but here it shows correct object with wrong addition to correct label (transliteration instead of translation).
