### ISSUE TITLE
subway station icons are missing in live map updates

### ISSUE THREAD

**Issue by z-z-z88** [osmandapp/OsmAnd#11366]
### Description
Subway icon is missing when you add a new subway entrance 

Here you can see proper icon https://www.openstreetmap.org/node/763045997
![Screenshot_20210408-142454](https://user-images.githubusercontent.com/38129009/113985770-b549af00-9876-11eb-906d-e02a52e01190.png)

here icon is missing https://www.openstreetmap.org/node/8582205547
![Screenshot_20210408-143142](https://user-images.githubusercontent.com/38129009/113986257-40c34000-9877-11eb-96e7-880ddd88c327.png)

### How to reproduce 
Create a new subway entrance and do live map update, use map style "Mapnik" 

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: 7.0
Device model: Huawei P9

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/10570
