### ISSUE TITLE
The name of unerground station displayed inncorect

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#11362]
### Description
The name of the underground station "Spasskaya" is signed correctly on the map, but when you tap on it, it displayed the name "Sadovaia" in the dialogue area. 
![image](https://user-images.githubusercontent.com/80623554/113832284-231bab00-9791-11eb-8b3a-25f031dce4d1.png)
![image](https://user-images.githubusercontent.com/80623554/113833231-15b2f080-9792-11eb-898b-2e78b8095bdc.png)

### How to reproduce?
Assign the name"Spasskaya" to all station names

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: Android 9
Device model: Experience XZ1

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by xmd5a2** [comment]
This subway exit is correctly added to transport data section:
```
  Спасская: [4 subway] Lat 59.926193 Lon 30.317524 Exits: [ 1) [ref:]  Lat 59.926895 Lon 30.319712 ] 179204390253
```
`./inspector.sh -vtransport Test_subway_spb_2.obf > tr.txt`
