### ISSUE TITLE
Bicycle routing breaks in some cases with "cycleway:left:oneway" / "cycleway:right:oneway"

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#11378]
A road tagged with `cycleway:oneway=yes` is treated by OsmAnd like a oneway road for bicycle routing:

![photo_2021-04-09_14-36-08](https://user-images.githubusercontent.com/1040784/114182345-cf50c380-9942-11eb-9d1e-a23aadf3b01b.jpg)

Left image shows the wrong routing, right image shows the correct routing in the opposite direction.

The route is from 51.0545127,13.7777996 to 51.0537237,13.7778425 and the way with the `cycleway:oneway=yes` tag is https://www.openstreetmap.org/way/387461926. Both [GraphHopper](https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=51.05425%2C13.77782%3B51.05366%2C13.77785#map=19/51.05395/13.77783) and [OSRM](https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=51.05425%2C13.77782%3B51.05366%2C13.77785#map=19/51.05395/13.77784) are routing correctly in both directions.

Unfortunately there is no documentation about `cycleway=*` + `cycleway:oneway=yes` in the OSM wiki and this tag isn't used very often (currently about 1k occurrences according to [taginfo](https://taginfo.openstreetmap.org/keys/cycleway%3Aoneway#overview)). However after inspecting several cases the meaning seems to be: _Both_ cycleways are one-way, but each in the direction of the motorized traffic. Or expressed in images:

![cycle_lanes_oneway](https://user-images.githubusercontent.com/1040784/114183571-1d19fb80-9944-11eb-97c5-99eed0bb64a1.png)

Left image shows the current interpretation by OsmAnd. Right image shows the correct interpretation according to the current tag usage. 

Looks like this is a regression from #9782.

**Comment by vshcherb** [comment]
Well its definitely connected but fixing it again vice & versa without OSM documentation is not going to work. So I think it needs to be clarified, I actually would see it as ```cycleway:oneway``` as only 1 direction road if I map my area

**Comment by scaidermern** [comment]
Well, it's not really "fixing it again vice & versa". #9782 is about `cycleway:<dir>:oneway` indicating whether a specific direction is oneway or not. `cycleway:oneway` instead has no direction given and thus seems to apply to both directions. This must not be mistaken with `oneway:bicycle` which has a different meaning.

Alternatively just ignore the `cycleway:oneway` tag completely. This will fix the above case and after all, without documentation it is not clear how to interpret this tag correctly. So just ignore this tag.

**Comment by xmd5a2** [comment]
Issue is not related to `cycleway:oneway`. Problematic way is https://www.openstreetmap.org/way/387461925. It has tags:
```
cycleway:left:oneway=-1
cycleway:right:oneway=yes
```
Previous fix for `cycleway:<dir>:oneway` was:
```
<entity_convert pattern="tag_transform" from_tag="cycleway:right:oneway" from_value="yes"  to_tag1="oneway:bicycle" to_value1="yes" map="no" poi="no"/>
```
but there was a problem: if `cycleway:left:oneway=-1` (that means reverse direction) was on the same way then it was ignored. In short, `cycleway:right:oneway=yes` was converted to `oneway:bicycle=yes` even if way is actually bidirectional for bicycles.
I'm not completely sure but adding ` if_not_tag1="cycleway:left:oneway" if_not_value1="-1"` will fix such issues.
Another possible issue related to this: we currently ignore left or right handed navigation differences.

**Comment by scaidermern** [comment]
You are correct. I compared a few other cases and `cycleway:oneway` is not the problem. So it must be `cycleway:left:oneway` and `cycleway:right:oneway`.

**Comment by scaidermern** [comment]
It would be really nice to have this fixed in the next release. This bug breaks bicycle routing in various places in various cities. Alternatively revert the changes from #9782 because this is a rare edge-case.

**Comment by xmd5a2** [comment]
> It would be really nice to have this fixed in the next release. This bug breaks bicycle routing in various places in various cities. Alternatively revert the changes from #9782 because this is a rare edge-case.

Can't figure out what exactly breaks routing and where. Can you provide more detailed explanation and particular route to test a fix?

**Comment by scaidermern** [comment]
Strangely I can't reproduce the given example anymore although the tags haven't changed (there was an edit, but it got reverted). So I'm going to close this issue.

Thanks for investigation though.
