### ISSUE TITLE
Context menu: support brand:ru, operator:ru etc. when changing map language

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#1137]
Some amenity=fuel contains brand and operator name tags with language indication:
    amenity=fuel
    brand=דלק
    brand:en=Delek
    brand:he=דלק
    brand:ru=Делек
    contact:website=http://www.delek.co.il
    name=דלק
    name:en=Delek
    name:he=דלק
It would be nice to be able to render these localized nametags with rendering style depending of map language.

**Comment by alexkmbk** [comment]
Not sure if owner of the issue meant the same thing as me, so I'd like to add my suggestion: It would be very helpful to be able to switch on in the options, the visualization of the value of "name:en" or "int_name" tags. For some people it's hard to read names written in local alphabet (like arabic or Thai letters) those names just unreadable, but if the names transcripted in english it would be much easier to read. You can read them and pronounciate and ask the route from local people. If there are no "name:en" or "int_name" tags, osmand should visualize normal "name" tag then. Of course this behaviour should be optional.
