### ISSUE TITLE
Does not work with RHVoice

### ISSUE THREAD

**Issue by yaomtc** [osmandapp/OsmAnd#11373]
### Description
I am using GrapheneOS, which (like LineageOS and others) does not include a TTS engine. I should be able to use my TTS engine of choice, [RHVoice](https://f-droid.org/packages/com.github.olga_yakovleva.rhvoice.android/). However it does not work.

### How to reproduce?
On a ROM without Google's TTS engine, install RHVoice, and download the voices you need. Make sure it is set as the default TTS engine (which it was, since it was the only one I had installed). Then start Osmand and start navigating.

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: Android 11
Device model: Pixel 4a

Currently my workaround is to use the pre-recorded voices. This at least tells me when I need to turn.

**Comment by sonora** [comment]
Do your Android  device (not OsmAnd) TTS settings have an itepm called 'Listen to an example',  and does that produce sound in your setup?

Then, in OsmAnd, can you please temporarily enable the Development plugin, then in its settings use the button 'Test voice prompts', and post a screenshot of what button 11.1 produces.

**Comment by yaomtc** [comment]
Well, it's working now. Maybe using "listen to an example" helped fix whatever the issue was, or switching between recorded voice and TTS. Thanks for the response.

**Comment by dane-stevens** [comment]
I just got it working on GrapheneOS. Looks like you have to go to System > Languages and input > Text-to-speech output. Where you see RHVoice, click on it and it will ask if you want to enable it. (even though it is pre-selected as the only engine, it does not actually enable by default.)
