### ISSUE TITLE
Live update doesn't work (OpenGL)

### ISSUE THREAD

**Issue by pieleric** [osmandapp/OsmAnd#11379]
### Description
I'm using the "opengl-arm-nightly", and I've noticed that although the live update appears to be downloaded fine, it doesn't appear in the map. 

### How to reproduce?
Here is a playground added a few days ago: https://www.openstreetmap.org/way/924950011 
Here is a footpath (very nearby): https://www.openstreetmap.org/way/924950006
I have the "Netherlands-South holland" map, (1 april), and use live update up-to-date (~5Mb), but they don't show up. 

### Your Environment
OsmAnd Version: 4.0.0#12726mqta (2021-04-07). It also didn't work with earlier versions.
Android/iOS version: Android 9
Device model: Xiaomi Mi6

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by vshcherb** [comment]
I'm afraid they never work correctly

**Comment by pieleric** [comment]
Just as a data point, the live updates have been working quite flawlessly in last two years. I've switch to the OpenGL nightly build just about a month ago.

**Comment by vshcherb** [comment]
Fixed in 4.2
