### ISSUE TITLE
Search for "Quedlinburg" shows Quedlinburger Strasse in 4 cities, but not the city of Quedlinburg itself

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#11376]
The search for "Quedlinburg" brings you Quedlinburger Strasse in 4 cities, but not the city of Quedlinburg itself

- [ ] Migrate changes to iOS

![photo_2021-04-09 11 53 21](https://user-images.githubusercontent.com/9365308/114155461-301fd200-992a-11eb-88e7-9d918cbebdc0.jpeg)

**Comment by alisa911** [comment]
The search is incomplete until a space is added.

**Comment by thackel** [comment]
On position 3 of the search results there is `Quedlinburg, Town, 986 m` which is the result you expect, or not? :-)

**Comment by vshcherb** [comment]
That's what needs to be double checked once more. The point that with incomplete search it still unexplainable other objects are further away even.

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/pull/11432

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/pull/11433/files

**Comment by alisa911** [comment]
test https://github.com/osmandapp/OsmAnd-resources/pull/680

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/commit/08baaf7004e4c743734ab7ddb0ac915d80d8fd57

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/1171
