### ISSUE TITLE
Synchronize favourites to osmand account

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#1138]
instead of copying favorites.gxp around devices as an entire file,
every single change of a favorite (my place item) shall be synchronized
to an osmand server. whenever a device belonging to same account is online
changes coming from another device will be synchronized. the account and server basically exists already, because you maintain the development contribution of a single user across his/her devices. this feature would be very much in line with what other applications offer (e.g.: google bookmarks, but also the skobbler navigation app)

just for completeness: osmand is the tool i use most (more than my car navigation) and on every business trip -> i like it

**Comment by midnightcomm** [comment]
One thing I've done is use a file sync app such as BitTorrent Sync.

**Comment by sonora** [comment]
Yes, but this must be strictly optional, as this naturally raises significant privacy issues, and (unlike other companies) we are not in the business of collecting people's data and making money with it ....  :-)

**Comment by vshcherb** [comment]
This in the long list of other features, it is not the issue so it is better not to keep it here

**Comment by PanderMusubi** [comment]
Please look into using Firefox Sync for storing favorites. See https://en.wikipedia.org/wiki/Firefox_Sync and discuss it via https://mail.mozilla.org/listinfo/sync-dev and https://mail.mozilla.org/listinfo/services-dev Advantage of using this service is that people can also run such a service themselves. Secondly, when favorites/placemarks are stored in a certain way, you could even have them appear in the bookmarks/favorites of your web browser and use them also there.

**Comment by PanderMusubi** [comment]
Suggested by people from Mozilla, see also https://github.com/mozilla-services/kinto and https://kinto.readthedocs.org/en/latest/ to store, share and sync placemarks.

**Comment by PanderMusubi** [comment]
Kinto has just released version 1.0 https://mail.mozilla.org/pipermail/services-dev/2015-June/002004.html
