### ISSUE TITLE
Map preferred language doesn't work correctly on some zoom levels

### ISSUE THREAD

**Issue by alex73** [osmandapp/Osmand#1139]
Problam exists in the net.osmand-2.0.0-200.apk, like in 1.9.* versions.

Streets have Russian names for Belarus in the 'name' tag and Belarusian names in the 'name:be' tag.

When I set Map language to Belarusian, displays Russian street names(from 'name' tag) for zoom levels 13-14(1km,500m) for Belarus, but displays Belarusian names(from 'name:be' tage) for 200m, 100m, etc.

![screenshot_2015-04-28-11-16-40](https://cloud.githubusercontent.com/assets/749667/7365372/5fbf1712-ed98-11e4-9625-adb0d1d4aa16.png)
![screenshot_2015-04-28-11-17-01](https://cloud.githubusercontent.com/assets/749667/7365371/5fbd6160-ed98-11e4-876b-cbca919a768e.png)

**Comment by vshcherb** [comment]
Fixed
