### ISSUE TITLE
Is there any feature that help me to avoid "toll road" I tried but didn't find. So if this kind if feature doesn't exist please add it on OsmAnd.

### ISSUE THREAD

**Issue by deep0808** [osmandapp/OsmAnd#11401]
# 🚀 feature request

### Describe the solution you'd like

 If you have a solution in mind, please describe it.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by itzikiap** [comment]
Yes.  In the route card, you can press "options" and in the options screen,  select "avoid roads…" inside it you can choose to avoid  toll roads.

**Comment by deep0808** [comment]
Just one more question is there any way to sync my settings with and account or something? so I don't have to huddle around in case I lose, change phone or accidentally uninstalled the app?

**Comment by scaidermern** [comment]
> Just one more question is there any way to sync my settings with and account or something?
Settings -> scroll down -> export
