### ISSUE TITLE
Conditional maxspeed based on time

### ISSUE THREAD

**Issue by keganlance** [osmandapp/OsmAnd#11419]
In the Netherlands, highways have a speedlimit of 130 or 120. Yet between 6:00 and 19:00 this is reduced to 100.

This is defined in OSM as either:
maxspeed=100 en maxspeed:conditional=130 @ (19:00-06:00)
or
maxspeed=130 en maxspeed:conditional=100 @ (06:00-19:00)

This doesn't seem to be used in OsmAnd tho. I always get 130 or 120.

**Comment by vshcherb** [comment]
This was tested in the Netherlands and working for years. Where do you see it's not updated in the widget max speed ?

**Comment by vshcherb** [comment]
A2 good example - 100 - 130
![image](https://user-images.githubusercontent.com/1042025/114775358-7f726200-9d71-11eb-8b6f-0a6e0e9d2ed1.png)

**Comment by scaidermern** [comment]
Maybe you have conditional restrictions disabled? Check the following setting:

Settings -> <profile> -> Navigation settings -> Route paramters -> Consider temporary limitations

**Comment by IIVQ** [comment]
I had not had the temporary limitations enabled. I have now, I can check whether this works in demo mode after 19:00 tonight.
Suggestions:

- Enable the temporary limitations by default (OsmAnd used to accept conditional maxspeed)
- Make the "temporary limitations" a different icon. The current "construction work" did not at all ring a bell to me that this also takes in account roads that are closed / have a different maxspeed for parts of the day or week. A clock would be better icon imho.

**Comment by scaidermern** [comment]
> Suggestions:
> 
>     * Enable the temporary limitations by default (OsmAnd used to accept conditional maxspeed)

I *think* they are already enabled by default. Maybe a developer can confirm. 

>     * Make the "temporary limitations" a different icon. 

I agree, the current icon isn't ideal. I would also go for something with a clock.

**Comment by IIVQ** [comment]
I can not remember seeing this option before. But I might be erroneus and have enabled it by accident.

I checked a simulated route with temporary limitations enabaled and now OSMand correctly shows them. Thanks.

**Comment by Discostu36** [comment]
I think this can be closed. If changing the option is still considered useful, it should have a new issue.
