### ISSUE TITLE
wikimedia_commons files sometimes not shown

### ISSUE THREAD

**Issue by Discostu36** [osmandapp/OsmAnd#11414]
### Description
When I add something like `wikimedia_commons=File:Filename.jpg` to an object, OsmAnd sometimes shows them when clicking on the object and sometimes not. I could not find out what the differences are.

### How to reproduce?
Click on an POI that has a wikimedia_commons tag that links to a file. 

Working POIs:
https://www.openstreetmap.org/node/2645328550 (node, historic=memorial)
https://www.openstreetmap.org/way/319270848 (way, amenity=playground)
https://www.openstreetmap.org/node/3755949044 (node, shop=books)*
https://www.openstreetmap.org/way/103312549 (way, building=apartments)

Not working POIs:
https://www.openstreetmap.org/way/103319277 (way, building=residential)*
https://www.openstreetmap.org/way/103307139 (way, building=apartments)
https://www.openstreetmap.org/way/103307152 (way, building=residential)
https://www.openstreetmap.org/way/103307150 (way, building=residential)

*) These two POIs have the same linked image that was attached in the same changeset. So this problem cannot be related to Osmand Live or have to do with the linked file.

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: Android 10.0.0.195 (EMUI)
Device model: Huawei P30

**Maps used (online or offline):**   
Germany_schleswig-holstein_europe.obf (2021-04-01)
Germany_schleswig-holstein_europe_21_04_13.obf (2021-04-13 11:05:00 CEST)

**Comment by dpriskorn** [comment]
following 😃

**Comment by vshcherb** [comment]
This issue could not be fixed cause these points are not POI, so this is the problem on how OsmAnd process and stores these points. So in order images to be displayed they should be POI in terms of OsmAnd

**Comment by Strubbl** [comment]
> This issue could not be fixed cause these points are not POI, so this is the problem on how OsmAnd process and stores these points.

It would be nice if OsmAnd could display images for all objects which are clickable in the app and which have the corresponding wiki tags in OSM.

**Comment by vshcherb** [comment]
As we have same issue in progress already, this one is going to be merged to https://github.com/osmandapp/OsmAnd/issues/20682
