### ISSUE TITLE
Reimporting Favorites updates timestamp

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#11429]
Spillover from discussion (https://github.com/osmandapp/OsmAnd/issues/11331)
1. Timestamp should represent creation time (or initial favorite point import if timestamp was not already present in import)
2. Timestamp shouldn't update after each reimport
3. Display last modified timestamp in Favorites Context Menu item - "Creation time". The same as in menu for Audio/photo notes.

**Comment by pebogufi** [comment]
Now it works fine, I love it.
Thanks a lot. Peter
