### ISSUE TITLE
Wikipedia labels on the map shown on few languages

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#11423]
### How to reproduce
Turn on Wikipedia POI in Configure Map, select one language for shown articles, turn on "POI labels". Labels for Wikipedia points on the map will be shown in different languages but is correct in the context menu and in the article itself. 

Wikipedia labels should be shown on selected languages (Wikipedia – Language).

<img src="https://user-images.githubusercontent.com/9365308/114688482-663fc600-9d1d-11eb-9596-b4484e1aff3e.png"  width="300" height="auto"/>

**Comment by nazar-kutz** [comment]
PR: https://github.com/osmandapp/OsmAnd/pull/11502/
