### ISSUE TITLE
difference betwen map in osmand and map in osm.org

### ISSUE THREAD

**Issue by call5** [osmandapp/Osmand#1142]
there is a difference rendered maps on the application and the website osm.org
for example : 
- https://lut.im/KG2x2LeP/df8xK9NS  screenshot in osmand
- https://lut.im/UmqmVrqB/odbRPITn  screenshot in osm.org

on the first pedestrian crossing is below the road and overlooks the bridges on the site yet osm.org everything is done

**Comment by Zahnstocher** [comment]
OSM data is wrong.

layer=5:
https://www.openstreetmap.org/way/101335628

layer=2:
https://www.openstreetmap.org/way/171738085

OsmAnd draws layer=5 over layer=2, I think this is correct.

**Comment by xmd5a2** [comment]
Yes, OsmAnd renders bridges according to layers.

**Comment by call5** [comment]
@xmd5a2 @Zahnstocher do you have any idea how to solve this on OpenStreetMap? I could open a bug report on OpenStreetMap (I already did but it was closed, as it appeared that the problem was Osmand).

**Comment by xmd5a2** [comment]
Somebody fixed it is OSM and now OsmAnd renders it correctly
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshot%20-%20051315%20-%2019%3A56%3A36.png
