### ISSUE TITLE
Whole telephone locks up (bricks) when adding favourite

### ISSUE THREAD

**Issue by tradavyvy** [osmandapp/OsmAnd#11435]
### Description
When I add a new favourite to a favourite group (in my case the self defined group 'roadside atractions')
I long-press the location on the Map
I choose the star icon for Add Location
I pick or leave active "roadside atraction"
I enter the favourite's name
I press Save

Now the whole phone stops working
After a while (sometimes loger sometimes quicker a window appears:

---------
Osmand+ does not react
X close app
    wait
    send feedback
---------

'Close App' usualy works and gets me back to the homescreen
'Wait' does not help
'Send feedback' gives me a pop-up telling me there is no connection 
This loss of connection seems to be a byproduct of this problem because just beforethe problem  the connection works and as soon as osmand closes it works again

### How to reproduce?
see above

### Your Environment   
OsmAnd Version:      3.9.10   2021-03-01
Android/iOS version: Android 11?
Device model:  Samsung A40

**Maps used (online or offline):**   Offline
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by tradavyvy** [comment]
I forgot to mention that the favourite has been stored by osmand when I open osmand again after the crash

**Comment by vshcherb** [comment]
Investigating it, it is probably hardware specific issue, we hope it will be fixed with 4.0 release

**Comment by tradavyvy** [comment]
The problem seems to have disapeared with version 4.2.5.
Thanks.
