### ISSUE TITLE
Several options for filtering the GPS altitude data recorded in GPX files

### ISSUE THREAD

**Issue by DR-Savard1** [osmandapp/OsmAnd#11439]
# 🚀 feature request

### Describe the solution you'd like

 If you have a solution in mind, please describe it.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by scaidermern** [comment]
@DR-Savard1 Any suggestions?

**Comment by vshcherb** [comment]
I think most of the options are present, if you have something in mind how to change default values, please feel free to suggest for each profile.
