### ISSUE TITLE
Reduce space in UI in editing POI, tab "Advanced"

### ISSUE THREAD

**Issue by laralem** [osmandapp/OsmAnd#11445]
# 🚀 feature request

### Description
Reduce space in user interface on screen "Advanced" shown editing or creating a POI and better division/layout of cells for long tags and specially values.

i think there is no need so much space between labels. Also, except in a empty/new tag added, there is no need to show "Tag" and "Value" text in existing tags and values already filled. See screenshots bellow. 

### Describe the solution you'd like
Example mock-up (actual>possible solution):
![Screenshot_20210415-142927_5](https://user-images.githubusercontent.com/80917261/115115207-a05dd180-9f82-11eb-88f1-cc1ea34a1c8d.png)

### Describe alternatives you've considered
Could be more simple, with few changes to developers I think, like the screenshot bellow. The space is reduced but is not addressing the other problem of long tags/values  (actual>another possible solution): 
![Screenshot_20210415-142927_7](https://user-images.githubusercontent.com/80917261/115115359-af914f00-9f83-11eb-82ef-c92c2efea898.png)

P.S. as recommended I've searched if someone made a previous similar proposal but didn't get results.

**Comment by dmpr0** [comment]
Proposed changes: use default android text field style but without label to reduce height to 48dp.
<table style="width:100%">
  <tr>
    <th>Light</th>
    <th>Dark</th>
  </tr>
  <tr>
    <th><img src="https://user-images.githubusercontent.com/9365308/145594513-df1db353-e23d-47be-9031-fbd38c5f4467.png"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/9365308/145594520-ff9b6b61-059d-42f5-ba57-7354bfc2938e.png"  width="300" height="auto"/></th>
  </tr>
</table>
