### ISSUE TITLE
routing Information ramp and bicycle:ramp don't work anymore

### ISSUE THREAD

**Issue by quax2712** [osmandapp/OsmAnd#11443]
The Informations "ramp:bicycle" and  "ramp"
`<select value="1" t="ramp:bicycle" v="yes"/>`
and
`<select value="1" t="ramp" v="yes"/> `
				
do not work anymore in routing.xml.
I used them in combination with highway=steps.
Are this informations maped to others?

Greetings
Rainer

**Comment by vshcherb** [comment]
I don't see them part of the map creation. They need to be part of this section during map creation https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml#L5896 (you can create custom maps btw)
