### ISSUE TITLE
Can't find post offices and post boxes

### ISSUE THREAD

**Issue by alexandrz** [osmandapp/Osmand#1144]
I can see post offices and post boxes on the map, but I can't find them using POI search. It's possible to find it by name, but not by POI filter.

**Comment by xmd5a2** [comment]
Can't reproduce. Please try to update maps.

**Comment by alexandrz** [comment]
It only happened in OsmAnd 1.9 with newer maps and also it still happens in 2.0 with filters presets created using older versions of the app. I think the ticket can be closed.
