### ISSUE TITLE
Samsung Critical Issue

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#1145]
http://stackoverflow.com/questions/24809580/noclassdeffounderror-android-support-v7-internal-view-menu-menubuilder

**Comment by Zahnstocher** [comment]
Wiko Rainbow (Android 4.2.2) is also affected:
https://groups.google.com/forum/#!topic/osmand/8ObVnD7a4kA

**Comment by vshcherb** [comment]
Forgot to mark it, it is fixed, but there are different issues with checkboxes
