### ISSUE TITLE
Wikipedia poi doesn`t show the name in English with disabled transliteration.

### ISSUE THREAD

**Issue by Chumva** [osmandapp/OsmAnd#11462]
### Description
Wikipedia poi doesn`t show the name in English with disabled transliteration.

### How to reproduce?
Select map locale to English and disable transliteration. Open any Wikipedia poi.

### Your Environment
OsmAnd Version: 4.0.0
Android/iOS version: 29 api
Device model: Pixel 4
![Screenshot_1618748840](https://user-images.githubusercontent.com/19220417/115145522-95767000-a05a-11eb-99c2-4e61443748ab.png)

**Comment by vshcherb** [comment]
Fixed with https://github.com/osmandapp/OsmAnd/commit/aa846ab405ffcc72953a83a2a942e147ff171982
