### ISSUE TITLE
The City of Durham Wikipedia marker is in the wrong place.

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#11464]
### Description
The article quotes Coordinates: 54°46′34″N 1°34′24″W
In Osmand Durham mapped it in nearby sewage works instead at 54.78334° N, 1.56667° W
![Screenshot_20210417-085536_OsmAnd+](https://user-images.githubusercontent.com/80623554/115210531-5d793680-a107-11eb-9d02-5506b79137cd.jpg)

### Your Environment
OsmAnd Version:
Android/iOS version:
Device model:

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by xmd5a2** [comment]
I can confirm that coordinates for this particular article are shifted by some reason
![Screenshot_2021-04-23-17-08-23-076_net osmand plus](https://user-images.githubusercontent.com/5829014/115883900-fa650800-a456-11eb-92ea-fe6c39e48218.jpg)
![Screenshot_2021-04-23_17-10-33](https://user-images.githubusercontent.com/5829014/115883835-e7eace80-a456-11eb-85f5-cb6ae43402f7.png)

http://www.enetplanet.com/geo_wiki/?lat=54.77678150085042&lng=-1.5774393081665041&zm=15&lang=en&ds=wiki&rd=4000

**Comment by xmd5a2** [comment]
https://www.wikidata.org/wiki/Q179815
https://www.openstreetmap.org/?mlat=54.783333&mlon=-1.566667&zoom=11#map=11/54.7833/-1.5667
