### ISSUE TITLE
Multiple values not appearing in search

### ISSUE THREAD

**Issue by Hedaja** [osmandapp/OsmAnd#11460]
Hi
There currently seems to be an issue with multiple semicolon-seperated values not appearing in the search.
If I click the POI itself it shows the different craft values separate but search doesn't find them. 

![IMG_20210418_134336](https://user-images.githubusercontent.com/693781/115144286-2eea5580-a04c-11eb-8f7a-7bc897880ac2.png)
![IMG_20210418_134357](https://user-images.githubusercontent.com/693781/115144285-2e51bf00-a04c-11eb-8a24-c5f75497260e.png)

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/pull/11787

**Comment by Hedaja** [comment]
> #11787

Thanks a lot 😊
