### ISSUE TITLE
Custom shortcuts button in map

### ISSUE THREAD

**Issue by Yajo** [osmandapp/Osmand#1147]
I like the new design, it's something that has been needed for a long time now.

In my case, I'd like to have at hand buttons for:
- Turn on/off sound (I use the phone also for music in the car, and when I know where I'm driving I don't like to listen the GPS).
- Turn on/off tolls (sometimes I want them, sometimes not).
- Search for nearby point of interest. In my case:
  - Search for nearby gas station.
  - Search for nearby parking spot.

For my personal needs, those should be 1 or 2 clicks away to enable, since either I have to press them while driving or I have to tell the person next to me to press them, and maybe he/she does not know OsmAnd controls.

But OsmAnd has so many features that event the smartest design ends up hiding some of them or confusing the user to find them, and I suppose not all users use OsmAnd like me, so my proposal is: Add a button with "Custom shortcuts" to the map view, and let the user choose which shortcuts he wants. Or display those shortcuts as buttons directly on the map, to aviod 1 extra click.

**Comment by sonora** [comment]
Well, I suppose you are aware that in our new UI toggling some of the features you ask for has come into much closer reach (3 taps each, I think) than we ever had it before, namely
- Toggle sound during navigation: Tap map screen, on the navigation toolbar tap the settings icon, tap sound
- Search nearby POI: At any time, tap the menu button, tap "Search POI", tap you desired category. (The search origin should automatically be preset to "current map center", although I have some reports this may not yet work reliably in al cases, which would be a bug).

Yes, saving one more tap may be an objective, but this kind of 'simplification' usually also causes more clutter and hence more obscurity or complications for many users. :-)

**Comment by vshcherb** [comment]
Actually we are thinking about it for quite a while, if we take a close look some widgets could be replaced with quick action buttons. So in practice they are not even widgets, let's see which UI we will approach

**Comment by Yajo** [comment]
Well my point is that while driving, 3 taps instead of 1 make a real difference, and users vary in their use of the platform, so it would be nice to let them choose which 1-tap shortcuts they want.

It could be fixed by having 3 circles of "quick action". One press: do it; long press: change it.

To avoid cluttering, other option could be a draggable edge with a custom menu there. But I prefer 1-tap, honestly.

**Comment by jkufner** [comment]
I would rather have this settings in "screen settings", just like all
other things on display.

**Comment by homersimpsons** [comment]
Or maybe implement a left side menu to drag it and access some shortcut set by the user (drive me home, gas station near here, switch off sound etc...)

**Comment by sonora** [comment]
Quick action feature is implemented by now, closing this.
