### ISSUE TITLE
Index and update offline maps as soon as they are available

### ISSUE THREAD

**Issue by Evpok** [osmandapp/Osmand#1148]
As of now, downloading a bunch of offline maps starts by downloading all of them, then indexing and updating (thus removing the old versions). It means that to update many offline maps you need a lot of free space: I have 18Gio of offline maps, so I would need at least a 36Gio card. The obvious workaround is to download one update at a time but it grows old quite fast.

Would it be possible to index and apply the updates as soon as they are downloaded (ie while the other updates are still downloading)?

**Comment by vshcherb** [comment]
Not really maps are downloaded 1 by 1, just indexing is done after all downloads (though I think we changed in 2.0). So you don't need 36 Gb, you need around 20-22 Gb max.
