### ISSUE TITLE
The track is not completely drawn

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#11494]
When the color of the track depending on the speed/height/slope does not draw the last fragment to the finish point.
При окраске трека в зависимости от скорости/высоты/уклона  не рисуется последний фрагмент до финишной точки.

![image](https://user-images.githubusercontent.com/12549744/115598279-e9938580-a2e2-11eb-8275-255d818235db.png)

OsmAnd Version: 4.0.0#31880m
Android/iOS version: 7.0
Device model: Xiaomi Redmi Note 4

**Comment by cepprice** [comment]
Was already fixed
