### ISSUE TITLE
Online search for offline maps has gone with v2.x

### ISSUE THREAD

**Issue by freilichthirn** [osmandapp/Osmand#1149]
With the update to Material Design I lost the ability to search for addresses online. This was possible in the 1.x versions by clicking on ">" at the bottom-right corner of the screen.
![v1x buttons](https://cloud.githubusercontent.com/assets/3681341/7428492/b2de3e86-eff1-11e4-8bdf-cda9a132cdfa.png)

The 2.x version only shows four buttons at the app's buttom:
![_20150501_110906](https://cloud.githubusercontent.com/assets/3681341/7428548/93246524-eff2-11e4-9873-7516b2a6f902.JPG)

Please re-enable the online search for offline maps in upcoming updates.

**Comment by vshcherb** [comment]
That feature is available on POI Search and we are working to provide one line search
