### ISSUE TITLE
ETA miscalculated for plane travel

### ISSUE THREAD

**Issue by jorgk3** [osmandapp/OsmAnd#11493]
For some reason https://github.com/osmandapp/OsmAnd/issues/9960 got closed as not an issue, so here we go again.

### Description
ETA miscalculated for plane travel

### How to reproduce?
Use OsmAnd on a plane, preferably sitting close to a window. Chose plane mode and capture the location of the destination airport. Result, the time to the destination is calculate incorrectly, see image:
![Freiburg-FRA](https://user-images.githubusercontent.com/8466558/115585512-f789dc00-a2cb-11eb-9901-bc512289c389.png)
Remaining distance: ~200km, plane speed: ~900km/h, displayed remaining travel time: 1h22m. It's quite clear that at 900km/h a plane will fly 200km in under 15 minutes.

![FRA-BER](https://user-images.githubusercontent.com/8466558/115586148-957da680-a2cc-11eb-968e-01d458521d54.png)
Remaining distance: ~400km, plane speed: ~900km/h, displayed remaining travel time: 2h46m. It's quite clear that at 900km/h a plane will fly 400km in under 30 minutes.

### Your Environment
OsmAnd Version: 3.4.6, a little old, but I don't think this has been fixed recently.
Android/iOS version: 10
Device model: Samsung Galaxy XCover 4s

**Maps used (online or offline):**   
Offline map of Germany in this case.

**Comment by vshcherb** [comment]
If you check profile default speed it's not 900 kmh, I updated it from 150kmh -> 720 kmh https://github.com/osmandapp/OsmAnd/commit/72ca4055fca9f1b5bb5b3af45e605ba4f7acd3bc, but you can change it as well in the app

**Comment by jorgk3** [comment]
Thanks. What units are those? 40f, 200f? In any case, 5 times 150km/h is now 750km/h?
