### ISSUE TITLE
Route line settings in dark theme

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#11495]
In the line thickness selection, the color of the lines does not match the selected color of the route line. In the light theme, everything works correctly.
Also in the description, under the line thickness selection, it says color, and it should say line thickness

В выборе толщины линии цвет линий не соответствует выбранному цвету линии маршрута. В светлой теме все работает правильно.
Также в описании под выбором толщины линии идет речь про цвет, а должно быть про толщину линии.

![image](https://user-images.githubusercontent.com/12549744/115600384-5019a300-a2e5-11eb-8888-9c4b0a912ffb.png)
![image](https://user-images.githubusercontent.com/12549744/115600311-3f692d00-a2e5-11eb-842b-38eaded57c07.png)

OsmAnd Version: 4.0.0#31880m
Android/iOS version: 7.0
Device model: Xiaomi Redmi Note 4

**Comment by vshcherb** [comment]
Map mode and Application Theme are different settings, as it's visible on screenshot map mode is running day mode now.

**Comment by Nine-Tailed** [comment]
Perhaps I failed to explain, here are two screenshots, in the light theme, the color lines, which shows their thickness are correct - red, in the dark theme - yellow, although the color selected red.
Возможно я не удачно объяснил, вот два скриншота, в светлой теме цвета линий, где показывается их толщина правильные, в темной - желтые, хотя цвет выбран красный.
![Screenshot_2021-04-22-15-25-19-164_net osmand plus](https://user-images.githubusercontent.com/12549744/115715516-e222b980-a380-11eb-8612-168cbe8dd19a.jpg)
![Screenshot_2021-04-22-15-25-55-313_net osmand plus](https://user-images.githubusercontent.com/12549744/115715519-e2bb5000-a380-11eb-9493-cb222a3b2f28.jpg)

**Comment by Nine-Tailed** [comment]
Victor, I understand that for the dark theme, the line color in the thickness selection is shown only for the night mode, I suggest that the buttons "day" and "night" always show, and depending on which of them is selected to change the line color.
Виктор, я так понял что для темной темы цвет линии в выборе толщины показывается только для ночного режима, предлагаю кнопки "день" и "ночь" показывать всегда, и уже в зависимости от того какая из них выбрана менять цвет линии.

And still about the tip under the choice of line thickness, I think it should say about the thickness of the because on the weblate you have a phrase with the substitution of the word. I understand for the substitution of the word "color" and "thickness".
И еще все таки по поводу подсказки под выбором толщины линии, я думаю что там должно говориться про толщину потому что на weblate у вас фраза с подстановкой слова. Я так понял для подстановки слова "цвет" или "толщина".

![image](https://user-images.githubusercontent.com/12549744/115762791-7eae8100-a3ac-11eb-9d11-2500e99ec31e.png)

**Comment by vshcherb** [comment]
Тема приложения это не тема карты, только что проверил, если поменять тему карты все правильно показывается
