### ISSUE TITLE
Different interfaces for applying settings

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#11496]
When applying the settings, there are two different interfaces, it may be worth leaving some one for unification.
При применении настроек есть два разных интерфейса, возможно стоит оставить какой-нибудь один для унификации.

![image](https://user-images.githubusercontent.com/12549744/115603091-670dc480-a2e8-11eb-9289-4e8b95fd1e3d.png)
![image](https://user-images.githubusercontent.com/12549744/115603126-7260f000-a2e8-11eb-84d3-1c2046694254.png)

OsmAnd Version: 4.0.0#31880m
Android/iOS version: 7.0
Device model: Xiaomi Redmi Note 4

**Comment by vshcherb** [comment]
Они специально сделаны для разных настроек (модальный и немодальный диалог).
