### ISSUE TITLE
Flooding: Kherson region

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#11508]
### Description
46.25153° N, 33.87489° E
![image](https://user-images.githubusercontent.com/80623554/115867675-0d221180-a444-11eb-9929-1f34e62f5702.png)

**Comment by xmd5a2** [comment]
User VARVAR8 added natural=coastline tag to "Сиваш" bay: https://www.openstreetmap.org/changeset/102012932
These coastlines were incorrectly oriented and were not connected to world ocean. Fixed in OSM data.
