### ISSUE TITLE
historic=memorial does not show up when next to an entry/exit

### ISSUE THREAD

**Issue by NotSoImportant** [osmandapp/OsmAnd#11515]
### Description
https://www.openstreetmap.org/node/2486736161
zoom 15: hidden
zoom 16: hidden
zoom 17: hidden
zoom 18: hidden
zoom 19: hidden
zoom 20: hidden
zoom 21: hidden
**zoom 22: visible**

### Your Environment

**Maps used (online or offline):**   
Germany, Baden-Württemberg

**Comment by scaidermern** [comment]
This is a typical behavior if POI icons overlap each other.

**Comment by NotSoImportant** [comment]
True, but in this case it makes the memorial nearly invisible, while the entry/exit stays visible all the time. I think memorial should have higher dominance, or entry/exit can be rendered independently - that icon anyhow differs from normal round poi icons and is much smaller.

**Comment by vshcherb** [comment]
That's usually not good when icon disappears on the other hand other icons should not be visible on earlier zooms and they start to overlap later.

**Comment by NotSoImportant** [comment]
validated in OsmAnd Nightly 4.0.0#3192m. thank you @xmd5a2 👍
