### ISSUE TITLE
Bug: hide polygons is not persisted

### ISSUE THREAD

**Issue by NotSoImportant** [osmandapp/OsmAnd#11516]
`Configure map -> hide -> polygons` gets applied on the map, but
- when reopening `configure map` it is not anymore selected (though polygons are still hidden) 
- moving to another profile and back brings polygons back also for the first profile

**Comment by cepprice** [comment]
This bug is not reprocuced. Polygons don't unselect after reopening configure map.

**Comment by NotSoImportant** [comment]
Ok, also cannot reproduce it today. Maybe there is another condition to trigger this behavior.
