### ISSUE TITLE
Packages are still marked as out of date

### ISSUE THREAD

**Issue by a903user** [osmandapp/Osmand#1152]
Some downloaded packages are still marked as out of date. After update they are still in the updates list with status "for update". For example English and Czech TTS files.

Fresh installation of Osmand 2.0.1 @ Android 4.4.4.

Thanks

**Comment by vshcherb** [comment]
After upgrade TTS files need to be updated

**Comment by a903user** [comment]
Sorry, but I do not understand your conclusion.

I installed new instance of Osmand 2.0.1 without upgrade from version 1.9.5. Next I downloaded maps, voices, contour lines etc. Everything is OK, but TTS voices after download still have status "out of date". When I mark them and update it then nothing happens. Still have status "obsolete". This bug was in version 1.9.5.

https://code.google.com/p/osmand/issues/detail?id=2473&can=1&sort=-modified&colspec=ID%20Type%20Status%20Priority%20Summary%20Opened%20Modified%20Milestone

**Comment by vshcherb** [comment]
Do you see the same with altitude correction?

**Comment by a903user** [comment]
No, World Altitude Correction is OK. Only TTS packages.

**Comment by vshcherb** [comment]
Please attach screenshots if possible

**Comment by crypto-rsa** [comment]
I have the same problem. On the screenshot you can see I have voice data for Czech language and English (both from 1. 5. 2015).
![osmand](https://cloud.githubusercontent.com/assets/11479798/7443951/197572cc-f16e-11e4-84dd-b38b8183f11d.png)

 However, OsmAnd says they are "1 days behind" and offers me to update to very old versions of them.

![osmand updates](https://cloud.githubusercontent.com/assets/11479798/7443953/1d653eb2-f16e-11e4-8767-1fb9895f12c3.png)

**Comment by a903user** [comment]
Screenshots of May 3, 2015.

![screenshot_2015-05-03-10-24-38](https://cloud.githubusercontent.com/assets/12199873/7444419/8cc4f406-f181-11e4-9628-96b61e7e861f.png)

![screenshot_2015-05-03-10-24-51](https://cloud.githubusercontent.com/assets/12199873/7444421/92e74780-f181-11e4-9e51-aede8b25ec96.png)

**Comment by vshcherb** [comment]
Fixed

**Comment by a903user** [comment]
Can I ask in which version it has been fixed? In version 2.0.4 is still this bug.

**Comment by a903user** [comment]
?
