### ISSUE TITLE
Quick Action: Wikipedia articles display on languages that you do not choose

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#11530]
### Description
When selecting only one language for Wikipedia articles, but it is displayed on the map articles on the different languages.

### How to reproduce?
1. Go to Configure screen
2. Quick action (...)
3. Add +
4. Show/hide POI
5. ADD A CATEGORY
6. Select Wikipedia

Every time you turn on POI by tapping Show POI in the Quick action menu, you will get English AND Cebuano Wikipedia articles

<table style="width:100%">
  <tr>
    <th><img src="https://user-images.githubusercontent.com/80623554/116102543-78bfe500-a6b7-11eb-966b-e7b39e121ef4.png"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/80623554/116102609-870e0100-a6b7-11eb-9ec8-eda2b062ffc1.png"  width="300" height="auto"/> </th>
  </tr>
</table> 
<table style="width:100%">
  <tr>
    <th><img src="https://user-images.githubusercontent.com/80623554/116102693-97be7700-a6b7-11eb-8126-72c3a2817e4a.png"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/80623554/116102862-bd4b8080-a6b7-11eb-8093-fc305c672080.png"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/80623554/116102914-cc323300-a6b7-11eb-84bb-523050922f97.png"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/80623554/116102962-d94f2200-a6b7-11eb-8dd6-cd2309a73216.png"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/80623554/116103052-e704a780-a6b7-11eb-8047-106367d77b21.png"  width="300" height="auto"/> </th>
  </tr>
</table> 

### Your Environment
OsmAnd Version:3.9.10
Android/iOS version: Android 9
Device model:

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by anastasiia936** [comment]
https://drive.google.com/file/d/1T7Pcx9hC4jdi7x6ggqwYAHjBqg6SqYMI/view

**Comment by dmpr0** [comment]
It seems fixed. In the current nightly builds.
