### ISSUE TITLE
Display heart rate of imported GPX tracks

### ISSUE THREAD

**Issue by holgis** [osmandapp/OsmAnd#11537]
# 🚀 feature request

### Description

It would be nice to have OsmAnd  displaying heart rate of imported GPX tracks

### Describe the solution you'd like

 After importing a track OsmAnd offers displaying 'overview', 'height' and 'speed'. Tracks i.e. from GadgetBridge are also containing heart rate (`hr`) in this form:
      <trkpt lat="XX.XXXXXX" lon="XX.XXXXXX">
        <ele>XXX</ele>
        <time>2021-04-27T09:45:00Z</time>
        <extensions>
          <hr>90</hr>
        </extensions>
      </trkpt>
Offering another tab 'heart rate' and displaying the values as a graph would make OsmAnd more interesting to everyone doing sports. In addition it could also be displayed on 'overview' tab and the `hr` value can be shown when selecting a way point on the map.

**Comment by snooppr** [comment]
I support the proposal.  

Rationale: 
OsmAnd is a combine and can do many things that athletes need, including unique ones, for example, visually break the track into segments of any length and watch the passage ...
You can pick up users of the [Fito Track](https://codeberg.org/jannis/FitoTrack)  applications and the terrible [OpenTracks[(https://github.com/OpenTracksApp/OpenTracks) , which is declared as a sports tracker, but in fact, the height does not work, the pulse does not work, there are no heart rate zones.

Please note that not only heart rate (min, max, average) is interesting for an athlete, but also 5 zones.  I believe that OsmAnd will become a worthy alternative to sports trackers.

**Comment by vshcherb** [comment]
We already have that feature implemented in 4.5 so it's possible to see the graph if track is recorded by OsmAnd

**Comment by holgis** [comment]
But this feature is specific about  imported GPX tracks.

Please reopen.

**Comment by dmpr0** [comment]
Starting 4.7 OsmAnd can write and read data from `<gpxtpx:hr>` tag
