### ISSUE TITLE
Bug: Some items with wikidata do not show the image

### ISSUE THREAD

**Issue by NotSoImportant** [osmandapp/OsmAnd#11534]
### Description
For many around I can see the image beeing taken, but for https://www.openstreetmap.org/node/1700291835
(and some little number of others) it is not showing up. Why?
https://overpass-turbo.eu/s/16Ej

### How to reproduce?
click the POI at geo:48.50186,9.04985 and check the images. Only mapillary images are shown, though https://www.wikidata.org/wiki/Q316773 actually has "image (P18)" set and for most other POIs the image then shows up.

### Your Environment
OsmAnd Version: 3.9.10.
Android/iOS version:
Device model:

**Maps used (online or offline):**   
Germany, Baden-Württemberg -- Example is from Tübingen

**Comment by NotSoImportant** [comment]
related issue #11414

**Comment by dmpr0** [comment]
Wikidata image is shown in the latest nightly builds 4.1.10 and on the iOS version too.

<img src="https://user-images.githubusercontent.com/9365308/145602887-52eb0a79-9b3f-44f9-be3b-04496fd7cf01.jpeg"  width="300" height="auto"/>

**Comment by vshcherb** [comment]
Fixed
