### ISSUE TITLE
tracks multi switch-on possibility

### ISSUE THREAD

**Issue by mariush444** [osmandapp/OsmAnd#11538]
# 🚀 feature request - ergonomy

### 
There is tracks list (favorites/places). 
If some tracks are visible then I have possibility to use multi selection to switch them off at one time (once).
If I would like to switch-on (make visible) some tracks then I have to do it one by one.
I click the track then osmand shows me the track on the map
then again I have to go to favorite/track then click next track then again osmand shows me the track on srceen
and so on, so on.

 

### I need multi switchers for not yet shown tracks, the same like there are multi switchers for already visible tracks.

 
![Screenshot_20210427-133821](https://user-images.githubusercontent.com/66887280/116239160-9d24cb80-a762-11eb-9f3c-7ceefffddc94.png)
![Screenshot_20210427-133811](https://user-images.githubusercontent.com/66887280/116239176-a2821600-a762-11eb-944d-7d1326282244.png)

**Comment by pebogufi** [comment]
This is already possible since a long time. 
Just explore the buttons (icons) at the second screen, bottom line.

**Comment by mariush444** [comment]
You are right.
Thank you for help.
