### ISSUE TITLE
Incomprehensible sentence

### ISSUE THREAD

**Issue by yarons** [osmandapp/OsmAnd#11547]
https://github.com/osmandapp/OsmAnd/blob/3db15d5f21cfa079d7819cb48c4dfabee6d757f0/OsmAnd/res/values/strings.xml#L59

Can you please explain or rephrase? I can't figure it out.

**Comment by vshcherb** [comment]
Fixed https://github.com/osmandapp/OsmAnd/commit/6137253b46f01c7898f02380a8c2b77d1c6e93c1#diff-0fdc438434df96f219514a0078b6d16ee6359083df99326aa3c8cef671cb1ea2
