### ISSUE TITLE
Opening Hours Parse error

### ISSUE THREAD

**Issue by midnightcomm** [osmandapp/Osmand#1154]
POI Seems to have correct format for opening_hours, however, OSMAND is not parsing the tag as expected. Showing the place as closed when it is actually open.

Might have something to do with use of commas/semi-colon.

Mo-Th 09:00-21:00, Fr-Sa 09:00-17:00, Su off

[Screenshot](https://imgur.com/3kJwxO0)
[POI Example](https://www.openstreetmap.org/way/189795777)
[Validation Result](http://ypid.de/~osm/evaluation_tool/?EXP=Mo-Th%2009%3A00-21%3A00%2C%20Fr-Sa%2009%3A00-17%3A00%2C%20Su%20off&DATE=1430508420000&lat=41.1457707&lon=-95.9753071&mode=0)

[Related Issue](https://github.com/osmandapp/Osmand/issues/473)

**Comment by ypid** [comment]
Actually, the use of [\<additional_rule_separator\>](https://wiki.openstreetmap.org/w/index.php?title=Key:opening_hours/specification#additional_rule_separator), which is not supported by OSMand, is not recommended for this value. Rewrite as "Mo-Th 09:00-21:00; Fr-Sa 09:00-17:00; Su off".
Parsing the \<additional_rule_separator\> is difficult …

That said, the I would also like to see issue #473 closed.

**Comment by vshcherb** [comment]
I don't expect any time soon to use javascript library especially we used this function in a critical way for search. 
I expect 
"Mo-Th 09:00-03:00, Fr-Sa 09:00-04:00; Su,PH off", 
that this will fail with PH detecting but won't fail with other values

**Comment by ypid** [comment]
Wrong. The value "Tu-Th 07:00-2:00, Fr 17:00-4:00, Sa 18:00-05:00; Su,Mo off" throws an exception:
Exception in thread "main" java.lang.NullPointerException
        at OpeningHoursParser.testOpened(OpeningHoursParser.java:700)
        at OpeningHoursParser.main(OpeningHoursParser.java:800)

I intend to bundle the javascript library into a Java library (.jar) in the future. Would you consider using it then?

**Comment by midnightcomm** [comment]
Made a note on OSM Wiki for future editors/users.

https://wiki.openstreetmap.org/wiki/Key:opening_hours#OsmAnd

**Comment by vshcherb** [comment]
To avoid sort of confusion.
This syntax is supported: "Mo-We, Fr 08:30-14:40,15:00-19:00", "Mo-Sa 08:30-14:40; Tu 08:00 - 14:00"
But this won't work: "Mo-Sa 08:30-14:40, Tu 08:00 - 14:00" (not sure though it is correct version at all)

**Comment by ypid** [comment]
It is not incorrect, but not intended/recommended/needed. The default rule separator should always be `;`. Please read [the explanation of the syntax](https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#explain:additional_rule_separator) and [the comments of this issue](https://github.com/ypid/opening_hours.js/issues/53)

So, in this case, there is no reason to use `,`. Just write it as `Mo-Sa 08:30-14:40; Tu 08:00-14:00`.
