### ISSUE TITLE
What is the "Gap" profile?

### ISSUE THREAD

**Issue by yarons** [osmandapp/OsmAnd#11548]
https://github.com/osmandapp/OsmAnd/blob/3db15d5f21cfa079d7819cb48c4dfabee6d757f0/OsmAnd/res/values/strings.xml#L270

Can you please explain or rephrase? I can't figure it out.

I tried asking on Weblate several months ago, no response.

**Comment by vshcherb** [comment]
I don't think it's used ApplicationMode and for sure it shouldn't be translateable
