### ISSUE TITLE
Github: Use more labels to categorize issues

### ISSUE THREAD

**Issue by NotSoImportant** [osmandapp/OsmAnd#11556]
Like this people can get a better overview about related issues inside of the current 1.9k issues.
I can offer my help to categorize some of them.

Incomplete list of suggestions, please add/refine:
- navigation
- downloads/live
- ux
- favorites
- my places
- configure map/screen
- profiles
- style
- osm entities
- wiki* (wikipedia, wikimedia, wikidata, wikivoyage)
- plugin: online maps
- plugin: ...
- type: bug
- type: feature
- type: routing

**Comment by vshcherb** [comment]
Used to do it in the past, but don't see much sense actually. Probably it helps to find duplicates or related issues but I feel general search works anyway better. Anyway it's worth a discussion and not an issue. I think most of the issues beyond 1-2 release plan should be converted to dicussions
