### ISSUE TITLE
restrictions not working for the paths or tracks

### ISSUE THREAD

**Issue by cricri-du-lauragais** [osmandapp/OsmAnd#11551]
OsmAnd 3.9.10

OsmAnd internal routing engine

offline maps with liveupdate

car profile (used with my motorbike onto tracks)

when you "**prefer unpaved roads**"
on the "**highway=track**"

only private restriction work

access=no
motor_vehicle=no
motorcar=no
vehicle=no 
or destination and other similar tag do not produce results, the route follows the forbidden path.

you can test it in France near Florac into national park with track are "motor_vehicle=no" tag into openstreetmap.
latitude 44.3157135
longitude 3.57787445

thank you for your great work ;)

**Comment by xmd5a2** [comment]
Can't reproduce. Please provide start/end points and a screenshot.

**Comment by cricri-du-lauragais** [comment]
hello,
I'm sorry, I made a mistake.
my map was too old (february 2021) prior to the many changes in openstreemap
i updated it and everything is working fine.

sorry again for the inconvenience and a big thank you for your great job.
