### ISSUE TITLE
App sudenly not see maps

### ISSUE THREAD

**Issue by miramikes** [osmandapp/OsmAnd#11555]
Hello,
my both apps beta and nightly not seeing maps (using same maps for both). They both asking for downloading new map.
I checked if my maps files disappeared, but not ... they are there. I tried changed location for them ... they has been moved to new location, but after restart of app still not visible for app.
Not idea what happened.
Any help please?
mira

**Comment by miramikes** [comment]
![Screenshot_storage](https://user-images.githubusercontent.com/623412/116582611-d5b8d680-a915-11eb-87d3-d3393612a333.jpg)
![Screenshot_storage2](https://user-images.githubusercontent.com/623412/116582628-d94c5d80-a915-11eb-893c-1fe8158579ae.jpg)

**Comment by pebogufi** [comment]
Do you see in ToralCmd any files with extension obf at current dir ?
Why do you think "they are there" ?

**Comment by pebogufi** [comment]
Just download one single map file, and look where it is.

**Comment by miramikes** [comment]
I don't understand how maps disappeared :( ... But it seems to be that I just download my maps again.
Sorry for panic and thank you for help.

**Comment by vshcherb** [comment]
Probalby you upgraded the system and they moved to another location.
