### ISSUE TITLE
Trip recording - show only 1 dialog to start recording (as before)

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#11550]
I never understood why we now display two successive dialogs when a user starts trip recording:

The first one seems sensible in many use cases, as it offers to set the recording interval. But then immediately afterwards we display a second one offering to pause or stop the navigation again, which surely does not match the use case at this point . It is mostly a nag screen here which you will dismiss, until later you really want to take such action.

It seems that in order to complicate this we have now introduced **yet another setting,** 'Show start screen',  but what it does is facilitate skipping the more useful first dialog, not the mostly out of place second one??

In general, we lately have a huge inflation of our strings file resulting from lengthy explanations about new customization options. I strongly believe users will appreciate if a utility app like OsmAnd will work out of the box with as few dialogs and precise options as needed, rather than offering additional screens which in turn you can disable in settings.

All users who like a simple app will also not appreciate having to go through settings to simplify app use, they rather turn to another app. In many cases we offer alternative or even successive screens and dialogs which can be combined, rather than being omittable via settings.

**Comment by pebogufi** [comment]
FULLY AGREE !!!
This second dialog is absolutely useless at THIS position. 
At least it should be possible to switch it off, like with first screen. (Show start screen)

**Comment by vshcherb** [comment]
- [ ] I think, we should get back to original concept
1. If checkbox is selected, both dialogs are shown to indicate how to stop / start for new users
2. If checkbox is not selected both dialogs should not be shown at Start
Another issue noticed during tests:
- [ ] Empty tracks should not be saved after finish (Clear recorded data)

**Comment by sonora** [comment]
So I understand the intent of showing the second dialog is "_to indicate how to stop / start for new users_"?

But showing that dialog does not fulfil that purpose?! What we need to bring across is that stopping a recording is via tapping the widget :Maybe the recording dot should simply blink red? 

Just showing the dialog serves no purpose unless someone leaves it displayed the whole time, which hardly anybody will do. And once the dialog is gone, users are back at square zero, having learned nothing?

**Comment by vshcherb** [comment]
In new release it has a lot of purpose actually ( I believe), it has functionality of almost whole app with widgets / graph. And in case user doesn't need the map it could stay as a Trip Computer screen (it's almost full screen)

**Comment by sonora** [comment]
Yes, I see. Suggestion: We have an Android system notification while recording a track. We could e.g. use tapping that to pull up OsmAnd with this trip recording control dialog visible?

**Comment by sonora** [comment]
PS: A other example of unnecessary complication is the expandable logging interval section on dialog 1. In the same space which now just shows the set interval, but necessitates to expand the section if you wanted to change the interval, we may as well immediately display the slider and indicate the current value on it at the same time. A fold-out section is obsolete, as is the lengthy but vain explanation of what the logging interval actually is.

**Comment by Chumva** [comment]
This should be fixed here - https://github.com/osmandapp/OsmAnd/pull/11661 but it needs some testing.

**Comment by dmpr0** [comment]
- [ ]  Should be profile independent.

**Comment by vshcherb** [comment]
All settings for trip recording are profile dependent, it will be very confusing if one of all from the list will be profile independent.

**Comment by pebogufi** [comment]
@vshcherb 
But Trip recording is one of the plugins. For me it looks like that it NOT profile dependent - am I wrong ?
Tested with OsmAnd~  4.0.0#32038m.apk 2021-05-22
