### ISSUE TITLE
Feature request: let users create a custom POI filter which finds all synagogues

### ISSUE THREAD

**Issue by unforgettableid** [osmandapp/Osmand#1156]
I am using OsmAnd~ 2.0.0#10871M.  This is a OsmAnd-nightly.apk build which I downloaded today from your [/latest-night-build](http://download.osmand.net/latest-night-build/) directory.

Wherever I go, I would like to be able to quickly find all synagogues near me, but so far I have been unable to do so using OsmAnd.

### Steps to reproduce ###

-  I pressed "Menu".
-  I tapped "Search for POI".
-  I tapped the three vertical dots next to the search field.
-  I tapped "Custom filter".
-  I tried to create a custom filter which will find synagogues and exclude churches, but could not find a way to create such a thing.

### The problem ###

I tried to create a custom filter which will find synagogues and exclude churches, but could not find a way to create such a thing.  As far as I can tell, neither OsmAnd~ 1.x nor OsmAnd~ 2 can do such a thing.

Finding _all_ places of worship wouldn't be as helpful.  I am Jewish, so I don't want to visit a church; and there are a _lot_ of churches in my city.

### My feature request ###

Ideally, it would be wonderful if you could please offer a way for me to find all POIs which are tagged with both `religion=jewish` and `amenity=place_of_worship` at the same time.

If this would be a hassle, it still would be good if you could offer a way for me to find all POIs which are tagged with `religion=jewish`, no matter whether they are synagogues or shops.  This indeed might also find Jewish religious supply shops (`shop=religion`), which I wasn't looking for, but that is okay.

### Important side notes ###

1. https://github.com/osmandapp/Osmand/blob/5d8f82df569ab7aa5e5afe21a5ab3006848a05cb/OsmAnd/res/values/phrases.xml#L507 does mention Jewish places of worship.  But I don't think that line of that file actually does anything:  I doubt that it's connected with any of OsmAnd's actual Java code.

2. When I tap "Custom filter" then "Tourism", I do see an option labeled "Place of worship".  But I don't see any option labeled "Place of worship: Jewish".

3. And anyway, even though I live in a big city, choosing "Place of worship" doesn't find even one single place of worship within 500 km of me.  Not a synagogue, not a church, not anything.  Strange.

### Postscript ###

Thank you very much for writing and maintaining OsmAnd.  It's a really useful tool &mdash; and the fact that it's open source makes it even better.

**Comment by vshcherb** [comment]
Now it is possible to enter Christian or any other religion in a search box of poi types and it will filter all other types

**Comment by unforgettableid** [comment]
Thank you very much!
