### ISSUE TITLE
Incorrect plan route in public transport profile

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#11562]
### Description
This route gives proper directions (5 minute bus ride on the 100 going West), but the map for the route shows that I should catch the 100 bus going East until the end of the route, turn around, and come all the way back +5 blocks. This could be because at Marine Drive Station, the "100 22nd Street Station" (East) and "100 Marpole" (West) both stop at the same stop.
![image](https://user-images.githubusercontent.com/80623554/116659236-f460b100-a999-11eb-8e01-a0912abe64d4.png)
![image](https://user-images.githubusercontent.com/80623554/116659266-02aecd00-a99a-11eb-8a90-1d7b895f249c.png)

**Comment by xmd5a2** [comment]
Relation is mapped incorrect (without stop_position members). However looks like all stops are correctly packed to transport section of obf map:
```
  100 bus 100 Marpole Loop: [22nd Street Station Bay 8, Marine Dr (WB) at 7th Ave, Marine Dr (WB) at 10 Ave, Marine Dr (WB) at 14 Ave, Byrnepark Dr (NB) at Marine Dr, Southridge Dr (WB) at Byrnepark Dr, Marine Dr (WB) at Gilley Ave, Marine Dr (WB) at Royal Oak Ave, Marine Drive (WB) at Nelson Avenue, Marine Drive (WB) at Sussex Avenue, Marine Drive (WB) at Patterson Avenue, Marine Dr (WB) at Greenall Ave, Southeast Marine Drive (WB) at City Edge Place, Southeast Marine Drive (WB) at Matheson Crescent, Southeast Marine Drive (WB) at Fieldstone Avenue, Southeast Marine Dr (WB) at Kerr St, Southeast Marine Drive (WB) at Jellicoe Street, Southeast Marine Dr (WB) at Elliot St, Southeast Marine Drive (WB) at Victoria Drive, Southeast Marine Dr (WB) at Argyle St, Southeast Marine Dr (WB) at Knight St, Southeast Marine Dr (WB) at Inverness St, Southeast Marine Dr (WB) at Ross St, Southeast Marine Drive (WB) at Fraser Street, Southeast Marine Dr (WB) at Prince Edward St, SE Marine Dr (WB) at Main St, SW Marine Dr (WB) at Ontario St, SW Marine Dr (WB) at Manitoba St, Marine Drive Station Bay 2, Southwest Marine Dr (WB) at Ash St, SW Marine Drive (WB) at Logan St, SW Marine Drive (WB) at Oak St, Marpole Loop Bay 4, Southwest Marine Drive (WB) at Montcalm Street, SW Marine Dr (WB) at Granville St, 52118, 52119, Hudson St (SB) at West 72 Ave, Marpole Loop Bay 1]
```
https://www.openstreetmap.org/relation/1148599
It is not clear why OsmAnd do not use Marine Drive Station Bay 2 platform (https://www.openstreetmap.org/node/6357086667). If route start and finish are near 100 Marpole Loop relation then route is calculated correctly.

**Comment by ivanPyrohivskyi** [comment]
Fixed 
https://www.openstreetmap.org/relation/9581622
https://www.openstreetmap.org/relation/1148599
