### ISSUE TITLE
Drop down menu unreadable (white on white)

### ISSUE THREAD

**Issue by Zahnstocher** [osmandapp/Osmand#1157]
Online maps -> Tile map source -> Define/Edit... -> Choose existing...
The drop down menu is unreadable, it seems that font and background are white.

**Comment by vshcherb** [comment]
For me it looks like first entry is empty all other items are readable, please attach screenshot

**Comment by Zahnstocher** [comment]
Android 4.4.2:
![screenshot_white](https://cloud.githubusercontent.com/assets/1073398/7443332/f8e2d188-f142-11e4-9175-bf3677d06d30.png)

**Comment by alexey-pelykh** [comment]
Fixed in f1ddccb7c3dea8bcf62d725ef931fffd2864d301
