### ISSUE TITLE
Restaurant shows up late in car profile

### ISSUE THREAD

**Issue by NotSoImportant** [osmandapp/OsmAnd#11576]
### Description
https://www.openstreetmap.org/node/275324142
In car profiles shows up with min-zoom 18
In all other profiles with min-zoom 16

### Your Environment
OsmAnd Version: 3.9.10 
Android version: 7

**Maps used (online or offline):**   
Germany - Baden-Württemberg - Reutlingen

**Comment by sonora** [comment]
By design, I think, the car profile is optimized to show street/traffic related item in a de-cluttered fasion, not necessarily restaurants.

**Comment by NotSoImportant** [comment]
Yes that would of course sound legit, however there are other pois I consider less important for car navigation that are shown in zoom 18 for car profiles, e.g.
- leasure=pitch
- sport=equestrian

It definitively makes sense for
- parking
- speed cam
- car repair
- car charger
- car wash

Also helpful
- supermarket - I see restaurant in the same category of POIs
- fire brigade
- castle
- museum (interestingly castle wins for cars, but for others museum wins: https://osmand.net/go?lat=48.53280&lon=9.14896&z=16) 
- theater
- community center
- amenity=kindergarten
- amenity=shool

**Comment by NotSoImportant** [comment]
Let's put it like this: I don't want to discuss usefulness of all these, but I think restaurants are same important than supermarkets - (and they are. So please don't hide supermarkets as the fix ;-)
