### ISSUE TITLE
Add support for Car Inspection services in car* shops

### ISSUE THREAD

**Issue by frasty** [osmandapp/OsmAnd#11578]
Osmand doesn't support car shops with tag service:vehicle:inspection=yes.
According to taginfo the counter for service:vehicle:inspection=yes has reached 1661, so it seems enough to be added to the "Car service" filter alongside service:vehicle:* tags that are already there.
Furthermore when selecting "Inspection" in the "Car service" filter list, Osmand should also add amenity=car_inspection POIs to the results, as they do offer the same service.

*The other way around when selecting "Inspection Center" in the filter list, Osmand should also list car* shops that offer inspection services, although I aknowledge that It may be debatable as one might deliberatly search for an inspection center and not a car_repair shop that also offer inspection services.

**Comment by xmd5a2** [comment]
Currently we don't support such combinations. You can create custom filter.

**Comment by frasty** [comment]
I understand that Osmand doesn't support such combinations, but how can I create a custom filter if Osmand doesn't support service:vehicle:inspection in the first place? Maybe you are missing this point.
IMHO Osmand could display an "Inspection" service for shops with a service:vehicle:inspection tag, like it does with already supported service:vehicle:* tags (also service:vehicle:rental tags are missing)

**Comment by xmd5a2** [comment]
I've added `service:vehicle:inspection` in last commit
