### ISSUE TITLE
Profile Customizaton: Inconsistent look

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#11572]
For a long time I thought this is still WiP, but maybe not: Why are the color buttons reasonably small here (about finger tip size), but the position icon buttons about 10 times bigger?

![20210501_084403](https://user-images.githubusercontent.com/845735/116774037-ea9e8280-aa59-11eb-95ee-78c46cf129e0.jpg)

Also: Why is the selected color button not framed, this is inconsistent UI?

**Comment by scaidermern** [comment]
For me the selected colour has a small round frame and a checkmark inside it. OsmAnd 3.9.10.

**Comment by dmpr0** [comment]
We need to:
- [ ]  Color selection frame should use selected color (similar to icon selection)
