### ISSUE TITLE
Fix messy UI in POIs short description

### ISSUE THREAD

**Issue by laralem** [osmandapp/OsmAnd#11587]
### Description
Recently something changed on short POI's descriptions. It was added a new string/description field. The name of POIs is shown twice, and if the POI has no name, is shown the value of some tag of that POI, even opening hours sometimes. I've checked and found this was introduced in "default" build 4.0.0#31918m released in 2021-04-27, the previous "defaul" build in 2021-04-26 doesn't have this problem.

### How to reproduce?
The best place to see this is in Search button > Categories > Nearest POIs and take a look at the results. The next screenshots are in Portuguese but this happens in English too:

<img src="https://user-images.githubusercontent.com/80917261/116831904-af0ed000-aba1-11eb-96c2-d0c77c07fbfb.png" width="250"/> <img src="https://user-images.githubusercontent.com/80917261/116833003-b8e70200-aba6-11eb-8529-e752ea2c5e88.png" width="250"/>

In the next screens is the POIs has no name (public telephone), so the "yes" string seems is coming from another label (payment:telephone_cards ?):
<img src="https://user-images.githubusercontent.com/80917261/116831887-9999a600-aba1-11eb-82ec-ff8be6dbf168.png" width="250"/> <img src="https://user-images.githubusercontent.com/80917261/116830847-9e5b5b80-ab9b-11eb-87c6-2b922a6784cf.png" width="250"/>

### Your Environment
OsmAnd Version: 4.0.0#31940m (released in 2021-05-02)
Android/iOS version: 7.1.1
Device model: Sony Xperia Z5 Compact - Model E5823

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/pull/11625
