### ISSUE TITLE
Big margin in custom filter list

### ISSUE THREAD

**Issue by Zahnstocher** [osmandapp/Osmand#1158]
POI -> Custom filter -> Man made (for example)
There is a big margin between the scroll list and the "Close" / "Select all" buttons.

**Comment by Zahnstocher** [comment]
Android 4.4.2:
![screenshot_margin](https://cloud.githubusercontent.com/assets/1073398/7443335/1e368e84-f143-11e4-8520-78f7d9cb22d6.png)

**Comment by vshcherb** [comment]
Fixed
