### ISSUE TITLE
A few strings untranslatable

### ISSUE THREAD

**Issue by laralem** [osmandapp/OsmAnd#11586]
### Description
A few strings I found untranslatable (all strings in Weblate are translated, before checking these and I'm using nighty build).

### How to reproduce?
(1) "Routes" not translated in Menu > Configure map > activate "POI overlay...":
<img src="https://user-images.githubusercontent.com/80917261/116818972-8c5ac800-ab5d-11eb-8a8b-3b246407f7f6.png" alt="Screenshot_20210502-113543" width="250"/>

(2) "Avoid low emission zones" not translated in Create a route > Options > Avoid roads...:
<img src="https://user-images.githubusercontent.com/80917261/116819327-35ee8900-ab5f-11eb-86ec-5d984e2b3584.png" alt="Screenshot_20210501-165523" width="250"/>

(3) "Desert, LightRS, Mapnik, Offroad, Snowmobile, Topo, UniRS" not translated in Menu > Configure map > Map style as seen in next screenshot. Maybe we should not translate "LightRS, Mapnik and UniRS" but someone could translate "Mapnik" with "Mapnik (used in OSM)". Anyway is needed in translations like Japanese, Arabic...
<img src="https://user-images.githubusercontent.com/80917261/116819471-be6d2980-ab5f-11eb-872a-a14b875636f6.png" alt="Screenshot_20210501-164956" width="250"/>

(4) "Test backup", "Register and backup/restore tracks and favorites" in Menu > Plugins > OsmAnd development (activate) > Settings:
<img src="https://user-images.githubusercontent.com/80917261/116819815-46076800-ab61-11eb-96b6-171165735dde.png" alt="Screenshot_20210501-164839" width="250"/>

(5) Also everything untranslated in the next screen (same path to test backup):
<img src="https://user-images.githubusercontent.com/80917261/116819947-0e4cf000-ab62-11eb-8bca-211e340186ce.png" alt="Screenshot_20210501-162006" width="250"/>

(6) "sec" shown while creating a route (directions button/menu). The [string on Weblate](https://hosted.weblate.org/translate/osmand/main/en/?checksum=bbdf08be7a292dfb) is mostly translatable:
```
Route: distance %1$s, router time %2$s
Calculation: %3$.1f sec, %4$d roads, %5$d tiles)
```
As seen in that string "Calculation: %3$.1f sec" have "sec" but "router time %2$s" doesn't have because it's hard coded, so is not translatable. By the way, that string has ")" orphan at the end, should be removed.
<img src="https://user-images.githubusercontent.com/80917261/116820052-90d5af80-ab62-11eb-9374-b8e6732f7ac7.png" alt="Screenshot_20210502-115046" width="250"/>

(7) "Default" in Menu > Configure profile > Audio/video notes > Audio output format (also in Audio bitrate):
<img src="https://user-images.githubusercontent.com/80917261/116821173-55d67a80-ab68-11eb-903a-8343b25dffb1.png" alt="Screenshot_20210501-162804" width="250"/> <img src="https://user-images.githubusercontent.com/80917261/116821271-bcf42f00-ab68-11eb-9023-d2696fef3213.png" alt="Screenshot_20210501-162734" width="250"/>

(8) "Contents" in Menu > Plugins > OpenStreetMap editing (activate) ---> choose any Wikipedia POI (it seems the Wikipedia article must have >= 4 sections, if it has 3 or less this section is not shown) > Read article button > "Contents" section is the only thing in English, it seems this string is inserted by OsmAnd (Wikipedia calls it Table of contents"), it's not in Wikipedia article, or at least the Wikipedia article has it translated to Portuguese, of course.
<img src="https://user-images.githubusercontent.com/80917261/116828887-1d976200-ab91-11eb-9c74-1b1837155273.png" alt="Screenshot_20210502-224159" width="250"/>

(9) "Searching, Rendering, text, points, points inside,objects visible" in  Menu > Plugins > OsmAnd development (activate) > Plugin options > Settings > Rendering debug info (activate) > move the map to show message:
<img src="https://user-images.githubusercontent.com/80917261/116833918-547a7180-abab-11eb-9ce7-3daba19d3223.png" alt="Screenshot_20210501-164825" width="250"/>

### Your Environment
OsmAnd Version: 4.0.0#31940m (released today 2021-05-02)
Android/iOS version: 7.1.1
Device model: Sony Xperia Z5 Compact - Model E5823

**Comment by vshcherb** [comment]
Most of the referred items are for unfinished (development) functionality or should be hidden for the rest I've created a spin-off issue to have it fixed

**Comment by laralem** [comment]
@vshcherb thank you. Didn't know that. Anyway is not bad finding 4 real issues in a total of 9.
