### ISSUE TITLE
Osmand mistakes normal junction as roundabout

### ISSUE THREAD

**Issue by kreuzschnabel** [osmandapp/OsmAnd#11598]
Approaching the junction at https://osm.org/go/0DfCW3xNc--?m= on the B 417 from the north-west, and giving instruction to turn left for the L 325, Osmand wrongfully refers to the junction as a roundabout: 

![Screenshot_20210503-193642_OsmAnd+](https://user-images.githubusercontent.com/22165960/116911797-9a851300-ac47-11eb-811b-5199dc79bd81.png)

The junction is correctly tagged, there is no junction=roundabout to be found. Maybe this is caused by https://osm.org/way/683253248 being a closed loop AND oneway=yes.

--ks

### Your Environment
OsmAnd Version: OsmAnd+ 3.9.10
Android/iOS version: LineageOS 18.1 / Android 11
Device model: Oneplus 5T

**Maps used (online or offline):**  offline, live maps enabled for navigation

**Comment by vshcherb** [comment]
You correctly pointed out... I think it's better to split the way on OSM - https://www.openstreetmap.org/way/683253248. 

In most of cases we correct another mapping issue (when roundabout is not mapped correctly), so I think it's better to change geometry here though it's not a mistake to map like that but there are many actual roundabout mapping mistakes.
