### ISSUE TITLE
Speed when walking (nice to have)

### ISSUE THREAD

**Issue by curlydawg** [osmandapp/Osmand#1159]
It would be nice if a feature were added that when the app is place in walking mode, the "Speedometer" could have an option to report "x minute mile"  (ie 8.9 minute mile) rather than miles per hours (and the equivalent for the metric system).

This would make Osmand a great tool to measure your running progress.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/issues/1180 Moved to
