### ISSUE TITLE
Save button in the editor got lost in the last update

### ISSUE THREAD

**Issue by bitnapper** [osmandapp/Osmand#1160]
Hi

very great what you have done with the new version. I really like it!

Sadly with the last update the save button in the editor has been removed. I really miss that functionality. If you could add it again that would be great. It would also be nice if one could set a custom path for the export (as a stored setting, and to set another storage path for the images would also be nice).

Again, great work!

Regards.
btn

**Comment by vshcherb** [comment]
Hi,

Which editor is missing save button?

**Comment by bitnapper** [comment]
The OSM Editor Plugin.

**Comment by vshcherb** [comment]
The save button is now by default saves to internal memory, and from the card or from My Places / Edits you will need to upload separately
