### ISSUE TITLE
Font problem with place names in OsmAnd 2.0.1	

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#1161]
English and non english characters are not displayed together.

**Comment by vshcherb** [comment]
This is known issue and it will take time to fix it, we estimate to fix it in 2.1

**Comment by aelmahmoudy** [comment]
I have a problem with some arabic names not displayed in OsmAnd, please see the screenshot:

![osmand-enc](https://cloud.githubusercontent.com/assets/96682/7755239/044b4f00-fff3-11e4-9d05-f8e291934a1f.png)

The 6 rectangles (which I've highlighted with a red ellipse) should actually read: الكيلو

I wonder if this issue is related to what I am experiencing.

**Comment by zuradv** [comment]
I have sam problems inglish font

**Comment by recursive-madman** [comment]
I'm experiencing the same problem.

@vshcherb you say this is a known issue. Do you have any more information on what's going on? Maybe a hint as to how one would go about fixing it?
I would take a shot at it then, if that helps.

**Comment by vardana** [comment]
Same here. Two symbols should be read as 11.
![screenshot_2015-08-03-14-28-56](https://cloud.githubusercontent.com/assets/11329973/9035800/47378d78-39ec-11e5-8a2e-e5ca7250c83d.png)

**Comment by EugenyN** [comment]
same issue in last osmand+ 2.1

**Comment by atsuidesu** [comment]
I ran into the issue under lollipop with Hong Kong map where both English and Chinese characters are used in place names under local lang display setting with any version 2.x. Many characters, and mostly numbers become boxes as if character font not found. I have to reinstall 1.9.x version to see the map properly. Though 2.x works OK with no issue with font under KitKat on my other device.

**Comment by rubin110** [comment]
I'm also seeing this issue in Osmand+ 2.2.4 on a stock Nexus 6 running 6.0.1, while looking at Hong Kong and mainland China.

**Comment by nicolas-raoul** [comment]
Quoting vshcherb from https://github.com/osmandapp/Osmand/issues/1541#issuecomment-143888849 :

> The issue that Skia doesn't support 2 fonts in 1 text view, so that's why it appears.

Then how about using a pan-unicode font like [Noto](https://en.wikipedia.org/wiki/Noto_fonts) which is designed to cover all possible glyphs?  
Or how about using [Antisquare](https://github.com/nicolas-raoul/Antisquare) (disclaimer: developed by me) to automatically find out what font to use in order to avoid missing glyphs?

**Comment by vshcherb** [comment]
- Or how about using Antisquare (disclaimer: developed by me)
If you could help us integrate Antisquare that would be really great. The main concerns are we didn't want to include many fonts because they will increase the size of the application which is already 50MB and the fonts https://github.com/osmandapp/OsmAnd-resources/tree/master/rendering_styles/fonts are about 15 MB. 
We tried to solve that issue with Harfbuzz but that was not easy, we were thinking to take the code from Android, which does basically the same, but stopped in the middle. 

Completely different approach, we consider to move text rendering to the Java side and in that case Android will be responsible for all these issues which might be a better solution.

**Comment by nicolas-raoul** [comment]
I see you include Noto, that's great! Noto does include glyphs for both hiragana and kanji, for instance. So if you use Noto as the font in a Skia text view (is it the case currently?), it should render properly if the problem is really "*Skia doesn't support 2 fonts in 1 text view*".

**Comment by pa-ta** [comment]
I still have this problem in Osmand 2.2.4 with russian maps on my Nokia X2 Dual Sim with stock android 4.3
![screenshot_2016-04-24-18-12-07](https://cloud.githubusercontent.com/assets/6490626/14768352/01cc0f76-0a51-11e6-9924-ba2e256f7bcb.png)

**Comment by yuanchao** [comment]
I think the issue is that "Droid Sans Fallback" or "Droid Sans Japanese" doesn't not include English and number glyphs which are available in "Droid Sans". For modern Linux environment, a fallback mechanism will be available by font-config. But this is not available in Android? A possible solution would be using "WQY Micro Hei" which is a derived font from "Droid" family that contains both en/numbers and CJK glyphs? Also Noto Sans would be a good choice if storage space allows. Just my two cents.

**Comment by Piskvor** [comment]
Apparently also an issue with Iranian place names: https://help.openstreetmap.org/questions/49579/carte-iran-noms-illisible-sur-android
I
This is the first place I have found - south of the Caspian sea, bottom right of image.
![screenshot_2016-05-05-16-46-02](https://cloud.githubusercontent.com/assets/917239/15046640/25aefbe0-12e1-11e6-970b-8c184b28cc13.png)

**Comment by mxa** [comment]
I have this issue with Korean.

**Comment by lasdfdv** [comment]
Running Osmand 2.3.5 on Android M, same with Japanese

**Comment by cl-yu** [comment]
Workaround : enable safe mode to see the fonts, but rendering will be slower.

**Comment by JasonHK** [comment]
There also a problem when Chinese and English (or even with other languages) appear together. It only shows Chinese correctly. Although I found an option to disable other languages, numbers still do not work correctly. Not everyone knows how to disable other languages, for example @mxa. Also, can you try to use only ONE font on the map? I think it may work!
![Imgur](http://i.imgur.com/BZL9894.png)

**Comment by mxa** [comment]
@jasonHK Switching the display language in OSMAnd doesn't help in Korea because most place names still follow the old naming scheme which has the Korean and English/romanized names in the name field. Like `name:대전 (Daejon)`

**Comment by mxa** [comment]
@cl-ju safe mode gets disabled on every start of OSMAnd. Quite inconvenient "workaround"

**Comment by vshcherb** [comment]
Related issue #3220 provides some positive results as workaround but still not good for end user cause requires to update system fonts.

**Comment by vshcherb** [comment]
I think the issue is not fully fixed though I will close it to get more attention to it and we could collect more feedback.

For people experiencing that issue please download from "Other maps" - "Open Sans fonts". It is fixing most of the issues but not all.

If the issue is not fixed, you could help us by testing a proper font. 
Proper fonts could be picked up from here https://github.com/osmandapp/OsmAnd-resources/tree/master/rendering_styles/fonts and put to folder "fonts" on device.

**Comment by mxa** [comment]
"Other maps" - "Open Sans fonts" isn't fixing it for me in OsmAnd~ 2.4.7

**Comment by mxa** [comment]
AFAIK you need to be root to be able to put files in the fonts folder on Android.

**Comment by vshcherb** [comment]
@mxa you should put into osmand/fonts folder (that's not root), some fonts are already there.

**Comment by vshcherb** [comment]
If I can see correctly file NotoSansCJKkr-Regular.ttf  (renamed from NotoSansCJKkr-Regular.otf) fixes all issues in Seoul.

**Comment by mxa** [comment]
I have downloaded and moved the NotoSansCJKkr font family, re-booted the phone and restarted OsmAnd~  2.4.7. The issie is still there. Sorry.

**Comment by vshcherb** [comment]
Rebooting is not needed, only app restart. https://goo.gl/photos/UfWEUNPEawoLF2aa6

**Comment by mxa** [comment]
My screen of the same area looks vastly different.
![screenshot from 2016-11-26 00-06-20](https://cloud.githubusercontent.com/assets/1220707/21031764/7d0d5a16-bda5-11e6-96e0-441b6adc2660.png)

**Comment by vshcherb** [comment]
Please try again, I think you've  send wrong screenshot? I'm sharing screenshots with font enabled and without https://goo.gl/photos/ZADooCNxkH2dSHkw5

**Comment by vshcherb** [comment]
In case you need NotoSansCJKkr-Regular.ttf 16,457,008 bytes (from https://www.google.com/get/noto/#sans-kore), I can share it

**Comment by mxa** [comment]
my fonts:
![screenshot_20161209-003551](https://cloud.githubusercontent.com/assets/1220707/21032124/a2116f94-bda7-11e6-8770-cd1010620240.png)

**Comment by vshcherb** [comment]
That strange will check on another devices, please note that I have only 6 fonts that are visible though it should not matter much cause they should not be used cause they have no korean symbols.

**Comment by mxa** [comment]
just deleted all the fonts except the six you have, but the issue is still persisting.

**Comment by emuzychenko** [comment]
I run OsmAnd+ 2.5.4 on Xiaomi Redmi Note 3 Pro (kenzo) with MIUI 8.0.6.0 (Android 5.1).

Have downloaded all 15 fonts from /rendering_styles/fonts, copied them to "fonts" subdir of /sdcard/osmand, restarted OsmAnd+, moved/resized the map, but still no English (Pinyin) local names.

Placing markers to the map, I see proper English/Pinyin transliterations (for example, the "Yu Ya Lu" in Sanya, China, on the screenshot).

Maybe there is a reason to add a font selection option to the app?

![screenshot_2017-03-14-17-02-27-436_net osmand plus](https://cloud.githubusercontent.com/assets/9041267/23893203/8fede398-08d8-11e7-8fa9-f55f28e3a37e.png)

**Comment by emuzychenko** [comment]
Hmmmm. After rebooting the phone, I noticed that object names became as expected (Chinese+Pinyin). But why? Does OsmAnd+ register/cache its private fonts at a system level?

**Comment by vshcherb** [comment]
Unfortunately the new fonts download require to restart the app. In Android sometimes it is quite hard to properly restart the app.

**Comment by vshcherb** [comment]
The main issue is fixed in 2.6, you can download latest build, the beta build will be next week.
Important, for korean, japanese, chinese - fonts needs to be downloaded in the download sections.
