### ISSUE TITLE
Need Voice Announcement When Off Route - Navigating Imported GPX	

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#1162]

**Comment by vshcherb** [comment]
What steps will reproduce the problem?
1. When I am navigating an imported GPX track and I miss a turn/go off track (cycling off road)there is no voice announcement. As I result I could go on for miles in the wrong direction.


What is the expected output? What do you see instead?
1. I would like to hear an announcement that I went off track.
2. I would like to program to recalculate to get me back to the nearest point of the imported track.
3. I would like to hear the new navigation direction: "make a u turn"

What version of the product are you using? On what operating system?
Android version 1.9


Please provide any additional information below.
This would be most helpful when following by voice prompts alone: cycling without looking at the phone.

**Comment by pajakgdynia** [comment]
Great idea!
I think it could be merged with "off map" navigation: if the distance to (.gpx) route increases, then such notification is made.

**Comment by vshcherb** [comment]
Was under impression that is implemented but I might be mistaken.

**Comment by sonora** [comment]
**Ad (1): "Off the route" prompt**
We definitely have a prompt "You have been off the route for x meters", and this works as desired if you follow a "normal" OsmAnd offline route, miss a turn, and the route has for some reason not been re-calculated by the time you travelled >X meters (think X may be some 350 or so).

I will have to test if this does not work when using a GPX route, I guess this is what this issue claims.

**Ad (2): Routing back onto the GPX**
Regarding the navigation back to the GPX route: We have options to calculate the first/last route segments (I think this means "starting point to GPX", and "GPX to destination point"), and also have a check box whether the entire GPX route must be traversed or not.

I would assume that a combination of these 2 settings (check first, uncheck second) should work, but have not much testing experience with this. Will check as I have time, but please do the same for your use cases.

**Ad (3): U-Turns**
This is probably deprecated, we have replaced the u-turn as much as possible where better alternatives can be found by re-routing.

**Comment by sonora** [comment]
Let's merge what remains of this into #2591.

Looks like from what is reported there, the prompt (1) works, and the routing back (2) remains to be tested with the settings I specified.
