### ISSUE TITLE
Make google plus-codes usable in 'placename-version'

### ISSUE THREAD

**Issue by tradavyvy** [osmandapp/OsmAnd#11628]
# 🚀 feature request

Not terribly important but usefull.
In osmand it is already posible to search a place with 8+2 plus-codes (a geo location system from google). But google maps usualy gives the 4+2+placename version. This version is also used in other places.
It would be nice if osmand could also understand this 4+2+placename version.

### Describe the solution you'd like
I am afraid this would need a huge database of placenames and numbers. But i am no programmer so maybe some of you have a better idea

### Describe alternatives you've considered

Use coordinates, use an external converter, look in googlemaps first and remember the place then go to osmand. All not real good alternatives.

**Comment by vshcherb** [comment]
4+2 are supported but only if you are located in same place.

**Comment by tradavyvy** [comment]
Because of a comment in #12809 asking to close this feature request.
Please keep it open. It would still be nice if +codes worked 'world-wide'.
The following example shows the problem:

Pluscode (from google) in noth Laos:
6GQQ+2FG Ban Tieng, Laos

Takes you to Sudan (while I am currently in Cambodia)

Screenshots:
![Screenshot_20230429-224426_Maps](https://user-images.githubusercontent.com/71978409/235311660-1ffd431d-c221-49d6-954c-2f22db3d1c28.jpg)

![Screenshot_20230429-224243_OsmAnd+](https://user-images.githubusercontent.com/71978409/235311677-fc366182-68a2-470a-bc78-781ee84d00c0.jpg)

![Screenshot_20230429-224357_OsmAnd+](https://user-images.githubusercontent.com/71978409/235311692-db3d7c8d-4ebe-4d79-a3dc-7360ee7f9e3a.jpg)

**Comment by tradavyvy** [comment]
While fidling around with this I found a not optimal workaround. Apparently GoogleMaps gives the full +code when it is not connected to the internet. So finding the spot om gmaps and then disconnecting the internet and then looking at the info-page of that spot gives the full +code and not the shortened one with place and country names. And the full +code works fine in OsmAnd.
As said not optimal but workable in a pinch.

**Comment by Friptick** [comment]
Useful tip! :+1:

**Comment by vshcherb** [comment]
> Takes you to Sudan (while I am currently in Cambodia)


That's weird it should take you close to your current location, needs to be tested. Obviously we don't support country yet I guess but main cities are supported

**Comment by Zirochkabila** [comment]
@tradavyvy Try to update OsmAnd- everything seems to be working.
Also, I tested with `CFFR+V5V Kyiv` and `6GQQ+2FG, Ban Tieng, Laos` - the result corresponds to Google maps


https://github.com/osmandapp/OsmAnd/assets/104760013/4db678b9-72f3-45a6-91a5-91b3724142f3

**Comment by tradavyvy** [comment]
For me it does not work.
My version 4.4.7.
6GQQ+2FG, Ban Tieng, Laos
Takes me here:

![Screenshot_20230524-134654_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/71978409/884b41d4-5955-4611-85a5-27a321352f36)

4+3 does work as long as you are close enough.

Do not spend to much develloper time on this as i see this as a minor issue.

Keep up the good work.

**Comment by Friptick** [comment]
For info, I have a Python script which translates Google's town names to whatever Nominatim can find. This must be what Osmand is doing. Well, the script also has trouble with obscure place names. So it's likely just Nominatim's database that is not complete. Not much that Osmand developers can do about that.

It does usually work, even for obscure places!

Thanks for your work.
