### ISSUE TITLE
[Bug] Tags in POIs sometimes aren't shown/disappear

### ISSUE THREAD

**Issue by laralem** [osmandapp/OsmAnd#11627]
### Description
Sometimes, some tags disappear while editing a POI.

### How to reproduce?
As we can see in the following screenshots, "townhall:type=city" is not shown in OsmAnd but is shown in OSM website. It could be because I don't have the latest OSM data (my map was updated in 2021-05-01). But this tag was added in 2017 as we can seen in last image. So, can't be that. 

POI's URL https://www.openstreetmap.org/node/1799603180

<img src="https://user-images.githubusercontent.com/80917261/117533042-0239b600-afda-11eb-9afc-361fc9e709e3.png" width="530"/> <img src="https://user-images.githubusercontent.com/80917261/117533050-0ebe0e80-afda-11eb-89d8-6eb7ce6ca26a.png" width="250"/>

<img src="https://user-images.githubusercontent.com/80917261/117533047-0960c400-afda-11eb-8ecd-0d2ff4e2dacf.png" width="650"/>

This same issue happened to me yesterday, and I was reporting the issue (in 13 tags, OsmAnd only showed 7 of them in another POI - was also amenity=townhall) but before submitting the issue here I've updated OSM map data and OsmAnd (I'm using OsmAnd last/development builds). And then I checked if still happened but the issue disappeared, OsmAnd was showing all 13 tags now. So it seems this happens only sometimes. Don't know if it easy to reproduce by someone else. One of the tags missing in that other POI was also "townhall:type=city". I've also checked if there is another POI/or area building with the same data but just found 1 POI (by the way OsmAnd could show somewhere POI ID for these situations).

Found now another example: https://www.openstreetmap.org/node/8044979539 has 6 tags but in OsmAnd I only see 2 of them "name=União de Freguesias de Carlão e Amieiro" and "amenity=townhall".

### Your Environment
OsmAnd Version: 4.0.0#31957m (released in 2021-05-07)
Android/iOS version: 7.1.1
Device model: Sony Xperia Z5 Compact - Model E5823

**Maps used (online or offline):**   
Default OSM offline vector map. Downloaded in OsmAnd: Menu > Download maps > Available > Europe > Portugal > Default map (map updated in 2021-05-01)

**Comment by vshcherb** [comment]
It's not a bug, offline not all tags are present and updated though they won't be deleted once you upload new tags or delete one of present in offline maps

**Comment by laralem** [comment]
> It's not a bug, offline not all tags are present and updated though they won't be deleted once you upload new tags or delete one of present in offline maps

So I have to be connected to Internet to show all tags? I thought offline maps had all tags, but seems I was wrong. At least that can explain the erratic behavior. Is there any option to have all tags in the default map? It's annoying being in the field without Internet and adding tags that probably OpenStreetMap have.

Probably there should be a warning in that screen explaining that, at least.

Anyway, sorry by reporting this issue, never thought it was because of that.
