### ISSUE TITLE
icon for post office

### ISSUE THREAD

**Issue by mariush444** [osmandapp/OsmAnd#11626]
# 🚀 feature request - icon - post office

icon for post offce needed

I can't find icon of post office in favorites.
Can you add icon for post office in favorites/places?

example
![image](https://user-images.githubusercontent.com/66887280/117507868-f1f8eb00-af87-11eb-8f5d-dc62838214b9.png)

 If you have a solution in mind, please describe it.
 Have you considered any alternative solutions or workarounds?

**Comment by dmpr0** [comment]
Two icons were added, they already available in the nightly builds and will be available in the next release.
![Снимок экрана 2021-05-25 в 16 58 37](https://user-images.githubusercontent.com/9365308/119510757-74502000-bd7a-11eb-80ac-f1ca72dd6977.png)
