### ISSUE TITLE
Crash on map updates

### ISSUE THREAD

**Issue by marsianer** [osmandapp/OsmAnd#11632]
When I start OsmAnd, my installed maps are no longer visible. However, these maps are available on the smartphone. If I now press the update button under Maps / Local, a crash occurs immediately. 

OsmAnd Version: 3.9.10
Android/iOS version: 11
Device model: OnePlus 3T

**Comment by pebogufi** [comment]
There are problems with Android 11,  read the reports, ex.
https://github.com/osmandapp/OsmAnd/issues/10453

**Comment by scaidermern** [comment]
Sounds like #11633
