### ISSUE TITLE
OsmAnd is corrupted after vector maps update + live update

### ISSUE THREAD

**Issue by bege10** [osmandapp/OsmAnd#11633]
### Description
I ran a full update of all vector maps and afterwards a live update.
Back to the map screen no vector map could be displayed any more. Each time I came to the map screen a toast popped up "multiple points" (not sure about "points" but something similar). With offline maps only the wold map worked. Online maps still worked.
The favorites where gone also.
In the app folder (on external SD) all these files where still there.
Back to the updates screen I saw that in the tab for all maps the list of continents was gone also.

### How to reproduce?
Don't know whether this is reproducible. I was lucky that I had backed up all settings before (thank you very much for that feature). So I cleared all data, restored the settings and downloaded the maps again.

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: 10 (/e/OS 0.16-q)
Device model: Fairphone 3

**Maps used (online or offline):**   
Austria_salzburg_europe.obf May 1
Germany_bayern_europe.obf April 1
and other maps from Germany and Austria.

**Comment by scaidermern** [comment]
Another user in https://t.me/deosmand reported the same issue. The app crashes on or after map update (seems to happen when trying to index the maps). Android 10. The only change was switching from last month to this month maps.

**Comment by marsianer** [comment]
Same issue: #11632 

Is there any workaround available?

**Comment by tiffchros** [comment]
I have the same issue:

Device : dreamlte
Brand : samsung
Model : SM-G950F
Product : dreamltexx
Build : PPR1.180610.011.G950FXXUCDUD1
Version : 9
App Version : OsmAnd~
Apk Version : 3.9.10 400

[exception.log](https://github.com/osmandapp/OsmAnd/files/6462150/exception.log)

@marsianer: for me it worked

- Goto Menü / OsmAnd Live / Live-Aktualisierungen [deactivate]
- Menü / Kartenverwaltung / Tab LOKAL / Find "Germany niedersachsen europe" (three dots) / Deaktivieren
- You have do download a map to have your search index back. Search for addresses results in empty suggestions, if not.

**Comment by marsianer** [comment]
This workaround works fine. Thank You.

**Comment by andrashann** [comment]
> This workaround works fine. Thank You.

It worked for me as well, but after restarting the app, it's broken again. I did not re-enable Live-updates, but I did re-enable some maps.

**Comment by bege10** [comment]
@vshcherb 
Did you close this issue and #11632 as duplicates of #11649 ?
Are all mentioned issues just related to Live Update of Niedersachsen map?

**Comment by vshcherb** [comment]
They are all interrelated and should be fixed now
