### ISSUE TITLE
Map not rendering in the public transport profile Nuremberg

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#11647]
### Description
In the navigation profile in Nuremberg city, the map does not render.
![image](https://user-images.githubusercontent.com/80623554/117775182-ebe26300-b242-11eb-9805-d10a5c6c4e68.png)
![image](https://user-images.githubusercontent.com/80623554/117775217-f6046180-b242-11eb-869a-e9d9a1c42134.png)

### How to reproduce?
Plan route in the public transport profile in Nuremberg.

49.42580° N, 11.07756° E
49.40591° N, 11.04958° E

### Your Environment
OsmAnd Version:3.9.10
Android/iOS version: Android 9
Device model: Experience XZ1

**Maps used (online or offline):**   offline
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by vshcherb** [comment]
It is location dependent issue! So it must be related with internal crash for certain maps, so it needs to be checked and traced.
