### ISSUE TITLE
Various regions in Germany missing from map download list

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#11642]
The map download list for Germany is incomplete since this month. The missing regions are:

* Berlin
* Bremen
* Hamburg 
* Saarland
*
They can still be found via the search function, though.

**Comment by vshcherb** [comment]
Probably there was a delay with May updates cause they are present in the list as I see them.

**Comment by scaidermern** [comment]
Nope, the bug is still present. However not always.

First image is the map list for Germany right after starting OsmAnd, second image is the map list after hitting the refresh button:
![IMG_20210519_185228](https://user-images.githubusercontent.com/1040784/118853015-9c033c00-b8d3-11eb-861d-97eb677ba6e5.jpg)
![IMG_20210519_185257](https://user-images.githubusercontent.com/1040784/118853033-a02f5980-b8d3-11eb-8f10-94d0bc6d1371.jpg)

The second list is shorter, some regions are missing. After restarting OsmAnd the first list is shown again. Until tapping on refresh...

Please reopen.

**Comment by vshcherb** [comment]
Well still couldn't reproduce it . Let's see if we've got more feedback
