### ISSUE TITLE
Crash Ukraine / Upper Bavaria: Public transport routing

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#11656]
### Description
Crash during plan route Public transport profile. In Ukraine whenever I'm trying to find route for public transport OsmAnd crashes. Finding route for walking/cycling/car works fine.

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: Android 9
Device model: SM-A530F Samsung 

**Maps used (online or offline):**   offline
https://photos.google.com/share/AF1QipNs7xqhaozFiLFVWR32yB9TiK0bpbDNV-JiyBeTXhel96SHHMkF-NZSmSmcZqYyxg/photo/AF1QipNGjdnMU_WyN1PsitNVRg6tSKKTpmMswL95q8XC?key=VEZCQkJJTFVKODVaekV1UzZFY2NVYmFrWkNqSUVR

**Comment by vshcherb** [comment]
Crash also in Upper Bavaria

**Comment by vshcherb** [comment]
Probably related to https://github.com/osmandapp/OsmAnd/issues/11647

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-core-legacy/pull/9

**Comment by fastovezz** [comment]
Hi! Can you please take a look: https://github.com/osmandapp/OsmAnd-core-legacy/pull/9#discussion_r637522573

**Comment by vshcherb** [comment]
Took a look, thinking whether it's technically possible

**Comment by fastovezz** [comment]
HI!
The issue is still present on my device:
Android/iOS version: Android 9
Device model: SM-A530F Samsung
OsmAnd Version: 3.9.10
