### ISSUE TITLE
The flooding in the coastline in Wales

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#11658]
### Description
At some zoom levels, the coastline seems to disappear!
52.12426° N, 4.67755° W
![image](https://user-images.githubusercontent.com/80623554/117986387-3c8cb580-b342-11eb-807a-e9567ce5ae3a.png)
![image](https://user-images.githubusercontent.com/80623554/117986026-eb7cc180-b341-11eb-9269-b110b55562ef.png)
![image](https://user-images.githubusercontent.com/80623554/117986412-457d8700-b342-11eb-9a1d-467a5c4e3263.png)
![image](https://user-images.githubusercontent.com/80623554/117986169-0a7b5380-b342-11eb-9d35-5381b20b884a.png)
![image](https://user-images.githubusercontent.com/80623554/117986451-4f06ef00-b342-11eb-818e-3bbffddeb9e0.png)

**Comment by vshcherb** [comment]
Unfortunately not reproducible on latest maps
