### ISSUE TITLE
Search "Gießaufgasse" in Vienna doesn't show anything.

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#11665]
### Description
Search for "Gießaufgasse" in Vienna doesn't show anything, but using Search > Address > Select city "Vienna" shows the needed street.
<img src="https://user-images.githubusercontent.com/9365308/118109365-c2177080-b3e9-11eb-8082-8b2cea7c1e8f.png"  width="600" height="auto"/> 

### Your Environment
OsmAnd Version: current nightly and 3.9.10
Android/iOS version: 10

**Maps used (online or offline):**   
Lower Austria

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd/pull/11728

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-resources/pull/687

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/1227

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/commit/ebfdf6438b84aa90f3d39b93a53de601cf948aa7

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-core/pull/226
https://github.com/osmandapp/OsmAnd-iOS/pull/1241
