### ISSUE TITLE
Existing bicycle path doesn't show, and routing ignores it

### ISSUE THREAD

**Issue by ralphm** [osmandapp/OsmAnd#11660]
### Description

The way https://www.openstreetmap.org/way/6855969 is somehow not recognized by OsmAnd, causing it not to be rendered and ignored for (offline) routing.

### How to reproduce?

I filed a (Dutch language) note https://www.openstreetmap.org/note/2665835 that describes the problem, as I initially assumed the problem was in the data. The stone paved part of the bicycle path north of the node is missing in the app, where it is clearly present in the data, and hasn't changed for a few years. I don't see anything particularly off on the way's tags.

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: Android
Device model: OnePlus Nord

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

Netherlands Gelderland, 2021-05-01 (with daily live updates on OsmAnd+).

**Comment by Famlam** [comment]
It asks to download German maps. Guess OsmAnd needs a slight refinement of the borders it uses?

**Comment by ralphm** [comment]
The German border is just south of this, so I'm not surprised about that. Do you think it causes this issue, though? I have the NRW map available as well in any case.

**Comment by ivanPyrohivskyi** [comment]
Need to fix [gelderland.poly](https://github.com/osmandapp/OsmAnd-misc/blob/master/osm-planet/polygons/europe/west-europe/netherlands/gelderland.poly)
