### ISSUE TITLE
"e" get's expanded to East and "s" to South when it shouldn't

### ISSUE THREAD

**Issue by alex9099** [osmandapp/OsmAnd#11666]
### Description
When searching for a way it shows the result with "e" or "s" expanded to "east" or "south" when it shouldn't ("e" means "and" in portuguese and "s" in that case is suposed to mean "são"/"saint")

I have the phone settings (and osmand) in english, but i've got reports that this also happens if osmand is set to portuguese

### How to reproduce?
Get portugal map and search for "Rua de São Tomé e Principe" 

### Your Environment
OsmAnd Version: 3.9.10
Android version: 10
Device model: davinci (xiaomi mi 9t)

**Maps used (online or offline):**   
This happens with Portugal map, be it from osmand servers or generated with osmandmapcreator

**Comment by alisa911** [comment]
- [ ] map
- [ ] search

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-tools/pull/402

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-tools/pull/403

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/pull/11752
https://github.com/osmandapp/OsmAnd-resources/pull/688

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-tools/pull/405

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/pull/11756

**Comment by vshcherb** [comment]
Fixed

**Comment by vshcherb** [comment]
**New maps will be in June that will not change E -> East in countries that doesn't have English as native language **

**Comment by alex9099** [comment]
So this was a bug on the map generator and not on osmand itself?

**Comment by vshcherb** [comment]
Actually both let's see new maps
