### ISSUE TITLE
Problem to find addres via address-book

### ISSUE THREAD

**Issue by osmvermesser** [osmandapp/OsmAnd#11673]
hi!

i try to open addres on andorid form address-book.

example public address:

Malmöstraße 22
23560 Lübeck

https://www.openstreetmap.org/?mlat=53.83822&mlon=10.66723#map=18/53.83822/10.66723

osmand will not found the address. 

if you extend search radius several times the address will be found. that is not good for the users.

i have the same problem on other address.

then there only less adress will be listed.

![2021-05-14 11_24_51-Fotos](https://user-images.githubusercontent.com/6803899/118250706-087ed500-b4a7-11eb-8059-55440c69df79.png)

![2021-05-14 11_23_05-OpenStreetMap](https://user-images.githubusercontent.com/6803899/118250589-eedd8d80-b4a6-11eb-8578-a225e7fb7986.png)

Black .... Target / red default listed

when i extend search radius the postbox (Postkasten) will other cities will listed and the search address.

in my opinion the address had to found direct.

regards Jan

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-resources/pull/689
https://github.com/osmandapp/OsmAnd/pull/11760

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/1239

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-core/pull/226
https://github.com/osmandapp/OsmAnd-iOS/pull/1241
