### ISSUE TITLE
Update UI for UTM Coordinates search

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#11676]
**UTM:**
Change text field order: Zone, easting, northing.

Allow to type UTM artificial letters like 32 A, 32 B ... to detect N / S - semisphere.

**Comment by cepprice** [comment]
https://github.com/osmandapp/OsmAnd/pull/12499

**Comment by MovingWiki** [comment]
As of version 4.8.5, this issue is still (or again) present.
UTM dialog asks for Zone, Northing, Easting which does not make sense in the usage of UTM which always uses Zone, Easting, Northing when stating coordinates.
