### ISSUE TITLE
Links broken to http://osmandapp.github.io

### ISSUE THREAD

**Issue by andrew-wharton** [osmandapp/Osmand#1168]
On the OsmAnd wiki page at http://wiki.openstreetmap.org/wiki/OsmAnd 2 links that point to a GitHub hosted site are broken.

1. Technical Articles (http://osmandapp.github.io/online-knowledge-base/TechnicalArticles.html) gives a 404.
2. FAQ (http://osmandapp.github.io/faq.html) gives a 404.

I'd fix these links in the wiki, but I'm not sure where they are meant to point to...

**Comment by krt16s** [comment]
I faced the same problem updating metadata in F-Droid. Have a look at

http://osmand.net/help/
http://osmand.net/help/TechnicalArticles.html
http://osmand.net/help/faq.html

However, id would still be nice to have the old links working or at least having a splash page on them...

**Comment by vshcherb** [comment]
the old links are just repository links and it was hard to maintain them. Repository is there https://github.com/osmandapp/osmandapp.github.io

**Comment by sonora** [comment]
I have cleaned it up some in http://wiki.openstreetmap.org/wiki/OsmAnd. Thx!
