### ISSUE TITLE
Crash: while navigation with voice prompts

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#11689]
It seems that the crash occurs only in "Simulate navigation" is enabled.

Device : CAP_sprout
Brand : Nokia
Model : Nokia 5.3
Product : CaptainAmerica_00WW
Build : 00WW_1_290_SP05
Version : 10
App Version : OsmAnd~
Apk Version : 4.0.0#31996m 400
[exception (29) (1).log](https://github.com/osmandapp/OsmAnd/files/6492558/exception.29.1.log)

**Comment by Chumva** [comment]
This should be fixed here - https://github.com/osmandapp/OsmAnd-resources/pull/694
