### ISSUE TITLE
Please render all forests similarly

### ISSUE THREAD

**Issue by UgnilJoZ** [osmandapp/OsmAnd#11680]
Currently, the default map theme renders many forests like natural=scrub. It would be better to render all forests in a similar way.

The following picture, only containing landuse=forest and natural=wood, should illustrate my issue:
![Screenshot_20210514-160450~2](https://user-images.githubusercontent.com/7910828/118282878-0b8dbb80-b4cf-11eb-9368-3ad7e2a2c96b.png)
The rendering suggests a change in landscape, which is not there. The whole picture consists of a forest.

I am not sure why the forests are rendered differently. Maybe the leaf_type and leaf_cycle tags are relevant.

**Comment by xmd5a2** [comment]
`leaf_type` tag is rendered according to value. Scrubs are rendered completely different from `wood` and `forest`

**Comment by UgnilJoZ** [comment]
> `leaf_type` tag is rendered according to value.

But only if present. There are no "default trees" to indicate a forest.

> Scrubs are rendered completely different from `wood` and `forest`

Here is a comparison between default OSM and default OsmAnd rendering of scrubs and `natural=wood`:
![wood-scrub](https://user-images.githubusercontent.com/7910828/118862021-754a0300-b8dd-11eb-9396-3867460da36e.jpg)
I am not able to see any difference. Am I doing something wrong?

**Comment by xmd5a2** [comment]
Forest is indicated by colour. Sorry about scrubs, I forgot that by default they are rendered like wood. I mentioned that with "More detailed" rendering style option they are rendered differently.

**Comment by UgnilJoZ** [comment]
> with "More detailed" rendering style option they are rendered differently.
True, thanks!

Yet the default still irritates me. If there is a difference between different forest types, there should be a noticable difference between scrubs and any forest too.
