### ISSUE TITLE
osmand live problem

### ISSUE THREAD

**Issue by Hades1503** [osmandapp/OsmAnd#11684]
### Description

Hello, there is a problem updating maps with osmand live on the french department ariège (09). 

I made corrections and additions but on osmand it does not appear. I have osmand + on iphone

### Your Environment
OsmAnd Version: OsmAnd + (3.9.7)
Android/iOS version: 14.5.1
Device model: iPhone 11 pro

**Maps used (online or offline):**   
Offline maps

Modification : 14/05/2021
https://osm.org/go/xVJcdXmmY?way=942929254

OsmAnd : 15/05/2021

![image](https://user-images.githubusercontent.com/79785663/118352050-93bba180-b55f-11eb-9513-2414ef6283aa.png)

OSM: 15/05/2021

![image](https://user-images.githubusercontent.com/79785663/118352061-a3d38100-b55f-11eb-9dc9-cc752ca62f35.png)

**Comment by ivanPyrohivskyi** [comment]
Bug is not reproduce. Checked on Android and iPhone.
Seems the bug related to delaying of live updates few days ago.
