### ISSUE TITLE
Do not announce in voice navigation each smooth turn 

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#11690]
It would be good to do not get a voice alert on each smooth turn especially in the winding terrain.

**Comment by bellera** [comment]
I agree. To much alerts when hiking.

**Comment by vshcherb** [comment]
It is probably related to GPX navigation, in that case Approximate route should be used.

**Comment by bellera** [comment]
I'm sorry! I don't understand **Approximate route.** Where is this option, if it exists?

**Comment by dmpr0** [comment]
Hello, @bellera!
You can find it in Menu - Directions - Follow Track, "Approximate Route" will try to find nearby roads for your track to give you the correct navigation instructions.

**Comment by bellera** [comment]
Thanks for your answer. I'm not capable to find this option. I switched to **Offline vector maps** because I thought I have to user a vectorial map. But not success.
![Screenshot_20210526-130453](https://user-images.githubusercontent.com/8041180/119649857-6dc9b300-be23-11eb-9996-22778b4017a0.jpg)

**Comment by vshcherb** [comment]
Sorry, another name in UI - Attach to the roads

**Comment by bellera** [comment]
I tried **Attach to the roads** but I don't understand what exactly does. It seems to do same kind of recalculation, not following the track. I'm doing hiking with non-vectorial map. The only possibility I have it's to follow the track when navigation. And receive warnings if I go too far of the track.

**Comment by scaidermern** [comment]
Attach to the roads needs a vector map.

With just a GPX track OsmAnd doesn't know which part of the track is just a simple curve and which belongs to a real turn at an intersection. Looking at the angle isn't always enough.

**Comment by bellera** [comment]
> Attach to the roads needs a vector map.

It’s what I thought. Thanks!
