### ISSUE TITLE
Follow track: different time depends on how the file was saved

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#11692]
Create route in "Plan a route" save it, open in navigation > follow the track, ETA is shown. Re-save the same tracks as simplified, navigation will show a different ETA.

![Group 103](https://user-images.githubusercontent.com/9365308/118475547-10dc4780-b715-11eb-9fd8-15b11b8a048b.png)

[tracks.zip](https://github.com/osmandapp/OsmAnd/files/6493178/tracks.zip)

**Comment by vshcherb** [comment]
Different time is expected cause in one case the routing time is calculated using only Default Speed (simplified) and another takes road limitations similar to OsmAnd Routing
