### ISSUE TITLE
Add the possibility to display localization of all my contacts

### ISSUE THREAD

**Issue by promeneur** [osmandapp/OsmAnd#11691]
# 🚀 feature request

### Description

Add the possibility to display localization of all my contacts.
Why?
In my contacts I have many favorites restaurants in my town or other towns. Then, when I need to eat, by just looking at the map around my position I would be able easily to choose one restaurant.

**Comment by pebogufi** [comment]
See also https://github.com/osmandapp/OsmAnd/issues/5699

**Comment by promeneur** [comment]
sorry i forgot my other report.

i close this one
