### ISSUE TITLE
iOS: The layer "Show node network cycle routes" displayed partially

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#11703]
In the cycling profile with active 'Show node network cycle routes' in the city center of Dortmund nodes 60 + 61 are displayed fully on Android and partly on the iOS version. The settings are the same on both the mobile phone and the iPad. Screenshots of both devices are added.
The place is located in Dortmund coordinates 51.51557° N, 7.45608° E

![image1](https://user-images.githubusercontent.com/80623554/118648133-c5946880-b7ea-11eb-99c0-94346e3f3cc1.png)
![image0](https://user-images.githubusercontent.com/80623554/118648145-caf1b300-b7ea-11eb-9658-a0419a516968.jpeg)

**Comment by xmd5a2** [comment]
Can't reproduce.
Do you use latest OsmAnd version?
(this is debug version and no icons are displayed, but node numbers are shown correctly)
![Screenshot_2021-07-14_21-06-18](https://user-images.githubusercontent.com/5829014/125671167-2c42ec27-dc95-4f84-8b80-a72457fed31f.png)
