### ISSUE TITLE
Add the ability to scan the route saved as a QR code

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#11718]
Add the ability to scan the route saved as a QR code.

**Comment by vshcherb** [comment]
Unfortunately it's not possible cause it will require online version of OsmAnd with routes etc... You can share the route using GPX as of today.

**Comment by jsjsjsjs** [comment]
> Unfortunately it's not possible cause it will require online version of OsmAnd with routes etc... You can share the route using GPX as of today.


Maybe the initial request was somewhat misleading. 
It's not about a QR code to a geolocation, but a download link to a complete route using GPX. 

[brouter](https://brouter.m11n.de/) has such a feature.
Example QR has information of the type:
[QR Code](https://brouter.m11n.de/brouter-engine/brouter?lonlats=7.598262,52.043805|7.499716,52.076858|7.462506,52.075882|7.534132,52.063747&profile=fastbike-lowtraffic&alternativeidx=0&format=gpx)

To be fair, it's a convenience feature. You still can download on your smartphone and import manually. Scanning the QR code directly would just save some taps.
