### ISSUE TITLE
Wrong lane suggested

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/OsmAnd#11716]
![изображение](https://user-images.githubusercontent.com/5829014/118817109-8a159f00-b8bb-11eb-8832-75d99a81739f.png)
https://www.openstreetmap.org/node/1624464253#map=16/50.1471/19.4312

**Comment by pl71** [comment]
I suppose `slight_right` and `slight_left` are not correctly handled.
Subject [road ](https://www.openstreetmap.org/way/229349124#map=18/50.14569/19.43700&layers=D)has turn:lanes=through|through|slight_right.

Similar [case ](https://www.openstreetmap.org/way/538086282)with slight_left:
![Turn_lanes_Slight_left](https://user-images.githubusercontent.com/4776779/118991688-9ddd0600-b98c-11eb-8b50-f82b5fe1f5b3.jpg)

**Comment by xmd5a2** [comment]
Not reproducible anymore
