### ISSUE TITLE
Error while updating to Osmand 2.0 from Google Play

### ISSUE THREAD

**Issue by janvlug** [osmandapp/Osmand#1172]
When I try to update Osmand from Google Play, Osmand is correctly downloaded.
The installation process starts, but stop with this error:

Couldn't install on USB storage or SD card.

I tried moving Osmand to and from SD card, but the error kept occurring.

My phone details:
bq Aquaris 3.5
Android version 4.2.2

(OK, I just note that there is a remark about this in 'What's new' for Osmand on Google Play.
I leave this issue open as a reference for others who encounter this issue.

**Comment by vshcherb** [comment]
yes we are investigating what could be the reason for this

**Comment by vshcherb** [comment]
One of the option is to try to install via browser or restart the phone before restart. Some recipes provided here http://www.pocketables.com/2014/06/fix-couldnt-install-usb-storage-sd-card.html

**Comment by crypto-rsa** [comment]
I experienced this error, too, when upgrading from 1.9.5 to 2.0 through the Google Play application. After a few unsuccessful attempts I uninstalled the old version and did a fresh install of 2.0 - this went smoothly.

**Comment by vshcherb** [comment]
Information is on the website http://osmand.net. And 2.0.4 is released
