### ISSUE TITLE
Add datetime stamp to favorites

### ISSUE THREAD

**Issue by e-pirate** [osmandapp/OsmAnd#11726]
Please, add date/time stamp to favorites.
One of my common OsmAnd use scenarios is for navigation during mushroom hunting. When I find a "family" of mushrooms, I set a marker so I can return there in the feature. But there is no date stamp, so there is no way to figure out what date mushrooms were found to approximate revisit date during next seasons.
The .gpx file mast store date stamps also.
The comfortable scenario looks like tapping on the screen -> Add -> date is present and saved by default.

**Comment by pebogufi** [comment]
Yes, look in tab "Details"

**Comment by e-pirate** [comment]
I'm using version 3.9.10 from Google Play Market - no such option available. Any estimates on releasing build on Play Market soon?

**Comment by vshcherb** [comment]
1-1.5 months

**Comment by e-pirate** [comment]
Perfect. Thanks!
