### ISSUE TITLE
Average speed screen indicator missing

### ISSUE THREAD

**Issue by paolobenve** [osmandapp/OsmAnd#11721]
# 🚀 feature request

### Average speed screen indicator

I can put the speed indicator on the screen (right side), but I cannot find any average speed indicator for the screen.

I would be very useful, expecially when having to respect a speed limit measured by the tutor system on highways.

**Comment by paolobenve** [comment]
I'd think on something very simple: an average of the speed value on all the time the app is open/on the recording time

**Comment by frasty** [comment]
Why would I want average speed just to avoid speeding between cameras? Sorry but this is a pointless assumption. Doesn't Osmand also allow for bicycle or pedestrian navigation/tracking? I mostly use Osmand with bicycle profile and displaying average speed would be a nice addition, just for the sake to display average speed.

**Comment by paolobenve** [comment]
I use osmand when going by bycicle, me too would be happy seeing my instaneous average speed

**Comment by vshcherb** [comment]
Preparation
![telegram-cloud-photo-size-2-5469657769788422666-x](https://user-images.githubusercontent.com/1042025/169052295-21d4ab7c-7751-462f-879a-986420aa4468.jpg)

**Comment by vshcherb** [comment]
Docs: https://osmand.net/docs/user/widgets/info-widgets#average-speed-widget
