### ISSUE TITLE
weblate complains about macrolanguage ku

### ISSUE THREAD

**Issue by matkoniecz** [osmandapp/OsmAnd#11738]
### Description
 
>  The component translation files are using ambiguous language code.
>  These language codes indicate a macrolanguage and it is usually better to use code of individual language instead.
> The following occurrences were found:

> Language code | Suggested individual language codes
> -- | --
> ku | ckb, kmr, sdh

### How to reproduce?

Follow translation link from readme, see warning, click on it to get https://hosted.weblate.org/projects/osmand/main/#alerts

### Your Environment
irrelevant

**Comment by vshcherb** [comment]
Dismissed
