### ISSUE TITLE
update to new global Digital Elevation Model 

### ISSUE THREAD

**Issue by abdullahO2** [osmandapp/OsmAnd#11737]
# 🚀 feature request

Is it possible to update Hillshade/Slope layers and Contour lines to be from "Copernicus DEM":
https://portal.opentopography.org/datasetMetadata?otCollectionID=OT.032021.4326.1

**Comment by ivanPyrohivskyi** [comment]
Unfortunatelly the data that suggested are worse that present in OsmAnd.
