### ISSUE TITLE
Glitches in position marker since OsmAnd 2.0.1

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#1173]
Please have a look at the attached screen shot. OsmAnd 2.0.1 has introduced regressions in position marker:

1.
The "X" is overlapping the text label. (This is a regression introduced in OsmAnd 2.0.1.)

2.
The map is centered to the position of the position label because I had clicked the favorite item within the GUI. The screen shot also shows the center circle which is displayed while zooming and some seconds after.
You can see that the arrow from the position label does not point exactly to the middle of this circle. (I'm not sure if this is also a regression or an old bug
![osmand201](https://cloud.githubusercontent.com/assets/6921696/7445541/ebb3fd54-f1b8-11e4-87c4-598c9da947b4.png)
.)

**Comment by Norbert80** [comment]
Please exactly watch the position marker's arrow while tapping on it. You will see that it jumps to the left while the finger is on the marker. This maybe the correct position.

**Comment by Norbert80** [comment]
@vshcherb could we fall back to the old 1.9 position markers to resolve this regression? Shouldn't be too much work.

**Comment by vshcherb** [comment]
1.The "X" is overlapping the text label. (This is a regression introduced in OsmAnd 2.0.1.)
This is not a regression it was always overlapping.
2. Can't reproduce. Is it shifted on click as well? May be it is a different screen resolution needed to test. As I see the context menu perfectly positioned next to favorite icon, favorite icon itself positioned at the center as well

**Comment by Norbert80** [comment]
@vshcherb

1.
Thanks for clarification.

2.
It is shifted to the right while not tapping on it.
If I hold the finger on it it jumps left (only the arrow, not the bubble) which seems to be the correct position. (The old marker had not this problem.)

**Comment by vshcherb** [comment]
Was it tested on nighlies? What is the screen resolution?

**Comment by Norbert80** [comment]
@vshcherb

Yes, nightly #7403D.

Resolution see screen shot attached above. (Galaxy S3 native screen resolution. I am on smartphone currently... so it is easier for you to look up exact resolution. :-)

**Comment by Norbert80** [comment]
@vshcherb 367 x 653 pixels

Please let me know if you still cannot reproduce it.

**Comment by Norbert80** [comment]
@vshcherb do you need two screen shots tapping and untapped?

**Comment by vshcherb** [comment]
Nope

**Comment by Norbert80** [comment]
Hi Victor (@vshcherb),

I managed to take a screen shot now also while pressed.

- Please copy the two screen shots attached below to a common folder on your local hard disk drive.
- Open one of these two screen shots with a picture viewer
- Toggle between the two pictures using up and down keys while watching the little arrow at the bottom of the position marker. You can see it shifting.

**Comment by Norbert80** [comment]
![screenshot_2015-05-30-21-45-13 2](https://cloud.githubusercontent.com/assets/6921696/8092708/ed8ef09a-0fbb-11e5-8594-014fecf75631.png)

**Comment by Norbert80** [comment]
@vshcherb:
According to this new screen shot my phone has a resolution of 720px × 1.280px. Can you reproduce the bug with this resolution? (The screen shot in my initial comment with 367px × 653px may be scaled.)

**Comment by vshcherb** [comment]
The margin on click was fixed.

**Comment by Norbert80** [comment]
@vshcherb:
On-click IS the correct position! Unclicked is false position.

**Comment by Norbert80** [comment]
Can confirmed correctly fixed in today's nightly build OsmAndF~2.1.0#7731D.

**Comment by Norbert80** [comment]
@vshcherb thanks for fixing problem 2. I have filed the separate issue #1344 for the remaining problem 1.
