### ISSUE TITLE
Navigation along gpx route created with the Osmand-Route-Planner: Incorrect information about arrival time. 

### ISSUE THREAD

**Issue by Artur-debug** [osmandapp/OsmAnd#11730]
### Description

After creating a gpx route with the osmand route planner, I noticed that the arrival time is displayed incorrectly.
It seems to me that the navigation system calculates the arrival time with the **Walking Speed**? 

Good Example | Bad Example
------------ | -------------
This is a standard route that I ride a lot. 330 km in about 3 hours driving time. Here without GPX navigation. A normal car profile navigation. | Here I have created a GPX route (same route as Good Example) and navigate along the GPX route. It is immediately noticeable that the driving time of 74.5 hours is not correct. 
<img src="https://user-images.githubusercontent.com/84518891/119042275-e5c55280-b9b7-11eb-9fcc-e18aa16951da.jpg" alt="drawing" width="200"/> | <img src="https://user-images.githubusercontent.com/84518891/119042302-f07fe780-b9b7-11eb-9568-ae8c7cea46df.jpg" alt="drawing" width="200"/>

#### More detailed description 
I want to show that the faulty arrival time is created only with GPX routes when the Osmand route planner is used. 
GPX routes created with OSRM and imported in Osmand show no false arrival times. 

**GPX-route created with OSRM and imported into Osmand:** 
Three different profiles, correct travel times are displayed. 

<img src="https://user-images.githubusercontent.com/84518891/119167621-4dcf7380-ba60-11eb-935e-52595fa12003.jpg" alt="drawing" width="200"/> | <img src="https://user-images.githubusercontent.com/84518891/119167641-5162fa80-ba60-11eb-88a6-27175423855d.jpg" alt="drawing" width="200"/> | <img src="https://user-images.githubusercontent.com/84518891/119167649-558f1800-ba60-11eb-98ac-4f6f5b57e2df.jpg" alt="drawing" width="200"/>

**GPX-route created with Osmand-Route-Planner:**
Three different profiles, always the same travel times  (always bicycle times).

<img src="https://user-images.githubusercontent.com/84518891/119168352-190fec00-ba61-11eb-9ad9-bef21de0dd7c.jpg" alt="drawing" width="200"/> | <img src="https://user-images.githubusercontent.com/84518891/119168366-1ca37300-ba61-11eb-8858-33796d02750e.jpg" alt="drawing" width="200"/> | <img src="https://user-images.githubusercontent.com/84518891/119168379-1f9e6380-ba61-11eb-96bd-eb57e68eb79b.jpg" alt="drawing" width="200"/>

### How to reproduce?

1. Create a route with the Osmands Route-Planner (a normal car profile). Please do not use any imported GPX routes. The bug is located in the route planner of Osmand (left picture). The start point of the GPX route should be near your GPS position.
2. Simulate navigation along gpx-route with Osmand (right picture). 

Route-Planner | Simulate Navigation
------------ | -------------
<img src="https://user-images.githubusercontent.com/84518891/119154095-22de2300-ba52-11eb-8229-6def63e58684.jpg" alt="drawing" width="200"/>      |     <img src="https://user-images.githubusercontent.com/84518891/119155040-0b536a00-ba53-11eb-93c4-b4d8486483fd.jpg" alt="drawing" width="200"/>

### Your Environment
OsmAnd Version: 3.9.10
Android version: 10
Device model: ZTE Blade V10

**Maps used (online or offline):**   
Osmand Offline-Vector

**Comment by vshcherb** [comment]
I think it's already 3rd issue related that Navigation profile doesn't change time that stored in GPX. It's planned to be fixed in 4.0
