### ISSUE TITLE
Navigation along gpx route created with the Osmand-Route-Planner: Navigation profile is not changed automatically 

### ISSUE THREAD

**Issue by Artur-debug** [osmandapp/OsmAnd#11743]
### Description

![screen-2021-05-22-19-06-31](https://user-images.githubusercontent.com/84518891/119267065-7b95f300-bbed-11eb-98fa-fdcaca16271c.png)

The picture above shows you a GPX file was created with Osmand. You can see the route was created with or for a bicycle profile. 

It would be nice Osmand would automatically change the navigation profile to "bicycle" while navigating along this GPX route.

I have already created the route with the profile bicycle (Fri-21-May-2021.gpx). I always have to explicitly change that to "Bicycle" one more time because my preferred navigation profile is "car". 

!<img src="https://user-images.githubusercontent.com/84518891/119267122-a6804700-bbed-11eb-9ced-17fdd83ce57d.jpg" alt="drawing" width="400"/> 

### Your Environment
OsmAnd Version: 3.9.10
Android version: 10
Device model: ZTE Blade V10

**Comment by vshcherb** [comment]
Duplicate https://github.com/osmandapp/OsmAnd/issues/11318

**Comment by Artur-debug** [comment]
Duplicate?  #11318 Is not the same issue.
