### ISSUE TITLE
mtb:scale=0 ... color tweak

### ISSUE THREAD

**Issue by miramikes** [osmandapp/OsmAnd#11740]
Hello,
MTB trails of easy difficulty ... mtb:scale=0 are almost identical as boundary of natural reserve only difference is that they are slightly wider.
I am suggesting to use darker color for mtb:scale=0 It would also improve visibility on green background.
These situations are quite common as mtb trails are quite often in same area as naturel reserves.
BTW ... vertical line is boundary of natural reserve and horizontal is mtb:scale=0
 
![Screenshot_mtb_easy](https://user-images.githubusercontent.com/623412/119233290-a1a58f80-bb28-11eb-9f23-bd217a6fa5d1.jpg)

best regards
mira

**Comment by miramikes** [comment]
Maybe same color which is used for piste:type=nordic/skitour piste:difficulty=easy can be used ... then there will same color code across profiles.
That could be nice.
mira

**Comment by xmd5a2** [comment]
Colour of nature reserve was changed recently and now it looks like this. Closing.
![Screenshot_2021-06-15_17-19-15](https://user-images.githubusercontent.com/5829014/122069443-df32cb00-cdfd-11eb-9c6f-699030794db9.png)

**Comment by miramikes** [comment]
Color of natural reserve is still the same here with new night build app ...  I guess I need to wait for maps to be rebuild? 
Thank you for fixing this !
mira

**Comment by xmd5a2** [comment]
@miramikes this can be another boundary or something. Can you provide exact coordinates or link to this object?

**Comment by miramikes** [comment]
> @miramikes this can be another boundary or something. Can you provide exact coordinates or link to this object?
It is this relation
https://www.openstreetmap.org/relation/2332750#map=15/49.9753/14.4148
It happens in biking profile ... Thank you
mira

**Comment by xmd5a2** [comment]
This is how this place looks in latest version
![Screenshot_2021-06-18_10-37-03](https://user-images.githubusercontent.com/5829014/122524759-31a00180-d021-11eb-886d-f5425aa8719a.png)

**Comment by miramikes** [comment]
I don't know what is wrong with my phone, but with latest version of night build my map looks still same :(
I deleted night build totally first and install new one then again ...
![Screenshot_mtb2](https://user-images.githubusercontent.com/623412/122687088-e8b09e80-d214-11eb-8b4e-2da91f3e5130.jpg)

**Comment by vshcherb** [comment]
Probably you need to update the map
