### ISSUE TITLE
Sometimes If I start a new route and I'm beside a Highway it route me strait on the highway

### ISSUE THREAD

**Issue by Mannshoch** [osmandapp/OsmAnd#11747]
### Description
Sometimes If I start a new route and I'm beside a Highway it route me strait on the highway

### How to reproduce?
I started a route 120m away from the Highway in Switzerland. It point me offroad strait ono the highway but that's never possible - at least in switzerland.

**Maps used (online or offline):**   
Offline map 1.5.2021
Osmand 3.9.10

**Comment by vshcherb** [comment]
In case you're not currently on any known road which is mapped on OSM, the routing engine will put you straight to the closest, which could be incorrect in your case. The only solution would be to improve the maps itself.

**Comment by Mannshoch** [comment]
Is there a way to map a Street as not allowed to enter except from another street?

**Comment by vshcherb** [comment]
Hm... not that's not possible. Think about different example - GPS initilal error is about 10-20 m. So device sometimes doesn't detect correctly that you are on the road  
If you're driving offroad there could be different solutions to say not drive to motorway first but to another residential road or something like that.

**Comment by Mannshoch** [comment]
As an Idea. If I start a new route, don't start on a Highway but If you are moving more than e.g 20km/h or have some Meter moved act like normal. So If you are on a Highway and you search for a new route, it's still possible.
