### ISSUE TITLE
Incorrect navigation path for cycling profile in Ravensburg

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#11751]
OsmAnd creates navigation using the wrong way path.
Navigation from Karmeliterstraße 35 to Gartenstraße 107.

47.78422° N, 9.58215° E
47.79400° N, 9.62260° E

The red line shows the path that OsmAnd use for navigation, the blue line displays the way how it should be.
![UTF-8''2021 05 23_Radroute Meersburger Straße](https://user-images.githubusercontent.com/80623554/119350158-a8a6dc00-bca7-11eb-8777-d0bcb28fdb5f.JPG)
![image](https://user-images.githubusercontent.com/80623554/119350773-65993880-bca8-11eb-82ce-b384eb00f443.png)

**Comment by Discostu36** [comment]
If the cycleway in the north can't be used this way then it should have a oneway-Tag.
