### ISSUE TITLE
Missing line with updates summary

### ISSUE THREAD

**Issue by a903user** [osmandapp/Osmand#1175]
When I go to the tab "Updates" immediately after a start of Osmand, then here is missing the line "Updates - #". See screenshots.

Osmand 2.0.1 @ Android 4.4.4 (CyanogenMod)

![screenshot_2015-05-04-10-08-03](https://cloud.githubusercontent.com/assets/12199873/7450620/46d8b18c-f247-11e4-9656-5b9c86bf160e.png)

![screenshot_2015-05-04-10-08-25](https://cloud.githubusercontent.com/assets/12199873/7450621/4b0135a4-f247-11e4-94cb-a2935561d5c4.png)

**Comment by sonora** [comment]
Outdated
