### ISSUE TITLE
Telegram channel and group link

### ISSUE THREAD

**Issue by Aiurek** [osmandapp/OsmAnd#11761]
Since I'm not using Facebook nor Twitter I'd really love to see an Osmand Telegram Channel to be kept up to date about stuff happening in the Osmand galaxy :)
Furthermore, it'd be really helpful for new users if u'd put a link to the Osmand Groups in the Help section of Osmand, like illustrated below. This would help new users to get connected to the community a lot faster and provides the easiest and fastest way of support

![TelOsm2](https://user-images.githubusercontent.com/27865200/119523209-dd389780-bd7c-11eb-9ef8-b456b03be4fe.jpg)

**Comment by dmpr0** [comment]
### We need to:
• Add "GitHub Discussion"
• Add a list of all "OsmAnd Telegram" chats
• By default show top 3, another hide below "View all" button.
• Remove "Vkontakte" item.
![Снимок экрана 2021-06-18 в 18 58 32](https://user-images.githubusercontent.com/9365308/122587974-3091c300-d067-11eb-922c-d31da4b19f99.png)

**Comment by franco999** [comment]
Spanish: https://t.me/osmand_es 
Portuguese (Brazil): https://t.me/brosmand
