### ISSUE TITLE
Catalan TTS voice (ca-tts) doesn't appear as downloadable

### ISSUE THREAD

**Issue by bellera** [osmandapp/OsmAnd#11764]
### Catalan TTS voice (ca-tts) doesn't appear as downloadable

I created a subfolder ca-tts in *Android/data/net.osmand/files/voice* folder and downloaded [https://raw.githubusercontent.com/osmandapp/OsmAnd-resources/master/voice/ca/ca_tts.js](https://raw.githubusercontent.com/osmandapp/OsmAnd-resources/master/voice/ca/ca_tts.js) to it.
But I couldn’t activate it at **Navigation Settings | Voice prompts | Language | TTS** because it doesn't appear on the list.
Going to **Test voice prompts** at **Development plugin** permits to select and test ca-tts.
After this my navigation has ca-tts !!!

**Comment by dmpr0** [comment]
# Review 
- [ ]  "Ca" visible in Developer plugin but doesn't visible in TTT list but it added to Recorded voice
<img src="https://user-images.githubusercontent.com/9365308/121348437-09cde100-c931-11eb-8cab-b84e14896f76.png"  width="300" height="auto"/>

**Comment by vshcherb** [comment]
Task details:
- [ ] This dialog Doesn't support custom files
- [ ] Catalan should be included in TTS by default
