### ISSUE TITLE
Revisit installation defaults for plugins

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#11776]
I just notice that for a fresh install we seem to activate these plugins by default
- Nautical map view
- Ski map view
- Parking position
- OpenPlaceReviews
- Mapillary

which I think is quite a strange selection?

Shouldn't we either enable some more main stream plugins like maybe 'Trip recording', Or maybe enable no plugins at all to cater for the more casual user, trusting that expert users will enable what they need anyway?

**Comment by scaidermern** [comment]
Activating a plugin by default for a service that is offered by Facebook (a company known as one of the biggest threats to user privacy, involved in various political manipulations and much more), is a really bad decision and should really get fixed.

**Comment by sonora** [comment]
Weird, I have done 3 different installations of our nightly this week, each on a factory-reset device, and they consistently had exactly the 5 plugins enabled I state above. Maybe someone else can test again. Possibly this is branch-specific, but it should not be?

**Comment by vshcherb** [comment]
ok will test and fix that's issue
