### ISSUE TITLE
Navigation routed far out of the way

### ISSUE THREAD

**Issue by lunkhub** [osmandapp/OsmAnd#11771]
# 🐞 routing report

### Routing engine

- OsmAnd's in-app offline routing

### Routing Profile

Car, fastest

### Start and end points

Start: 5 to 10 miles east of Greensboro, NC USA on I-85 (aka I-40 part of way) heading to west. See coordinates at top of screenshots.
End: Semi-random place in Asheboro, NC USA, which is 20+/- miles south of Greensboro, down I-73.

### Actual and expected routes

Original OsmAnd route was I-40 west (aka I-85 business) to I-73, then southward. This is OK, but preferred route was I-85 "beltway" route west to I-73, then southward. The difference between the two routes should be small. I-40 may be slightly slower with lower speed limits. I-85 may be slightly longer with higher speed limits.

Issue: After going onto I-85 beltway, OsmAnd recalculated route to a significantly longer route, returning to the original by going out of the way on Highway 421 (Screenshots 1 and 2). After ignoring this route and passing Hwy 421, OsmAnd finally recalculated correctly (Screenshot 3).
![Screenshot_202105_1-OsmAnd~](https://user-images.githubusercontent.com/66975721/119684957-770f4b80-be34-11eb-8ffb-5bf519b3e50d.png)

![Screenshot_202105_2-OsmAnd~](https://user-images.githubusercontent.com/66975721/119685116-9ad29180-be34-11eb-9fc1-fd3b736022f9.png)

![Screenshot_202105_3-OsmAnd~](https://user-images.githubusercontent.com/66975721/119685165-a6be5380-be34-11eb-8305-83b65cf7981c.png)

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

Yes, but exact timing is not known, and offline maps were also recently updated to latest.

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

3.9.10 (3/16/21 from F-Droid)
</code></pre>

**Device and Android/iOS version:**
Nexus 6, Android 11, non-Google, LineageOS fork (without microG)

**Anything else relevant?**

**Comment by lunkhub** [comment]
FYI, Less than a week later, it routed as expected. Still Apr 30 2021 Offline maps. No major changes, AFAIK. Odd.

![Screenshot_202105-4-OsmAnd~](https://user-images.githubusercontent.com/66975721/121077157-cf483500-c7c6-11eb-93b6-9f28d151e82a.png)

**Comment by vshcherb** [comment]
weird... we will double check

**Comment by alisa911** [comment]
The bug isn't reproduced.
