### ISSUE TITLE
Navigation wrong Route Osterwall-Ismaning Bavaria

### ISSUE THREAD

**Issue by Artur-debug** [osmandapp/OsmAnd#11770]
# 🐞 routing report

### Routing engine

- OsmAnd's in-app offline routing

### Start and end points
Start: Lohweg 10, Osterwaal (https://www.openstreetmap.org/node/1797818728)
Stop: Schloßstraße 2, 85737 Ismaning (https://www.openstreetmap.org/way/10046598)

### Actual and expected routes

**Settings:** 
1. avoid highway/motorway
2. not fuel efficient route 

Wrong Route (**high distance, long time**)
<img src="https://user-images.githubusercontent.com/84518891/119667503-a626bc80-be36-11eb-9588-54fda9de15ca.jpg" alt="drawing" width="300"/> | <img src="https://user-images.githubusercontent.com/84518891/119667533-aaeb7080-be36-11eb-9f4a-4c2342825662.jpg" alt="drawing" width="300"/> 

Should be:
<img src="https://user-images.githubusercontent.com/84518891/119667553-ae7ef780-be36-11eb-95f4-10532ff82c19.jpg" alt="drawing" width="300"/> | <img src="https://user-images.githubusercontent.com/84518891/119667561-b2127e80-be36-11eb-8453-829ab61d51a4.jpg" alt="drawing" width="300"/> 

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

 3.9.10

</code></pre>

**Device and Android version:** ZTE Blade V10, Android 10

**Maps used (online or offline):**

- Offline maps offered within the OsmAnd app for download.
**Anything else relevant?** 

A fuel-efficient route would not be a solution, because federal roads (de. Bundesstraßen) are left if the main through-road (de. Ortsdurchfahrt) is less than 500m.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/9436

**Comment by vshcherb** [comment]
Same as https://github.com/osmandapp/OsmAnd/issues/14924

**Comment by alisa911** [comment]
Base routing creates the wrong route. Need to fix (add?) base points where new normal roads were added for connection with new roads.
Map for test:
obf - https://drive.google.com/file/d/1-kX3qCnc7FxaRTn_Pia-Psj1XYkdwJUt/view?usp=sharing
osm - https://drive.google.com/file/d/1ZmwDqOtNRRzYuzYaU8zf5vy_BgpfycQO/view?usp=sharing
class - ImproveRoadConnectivity

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-tools/pull/529
<img width="363" alt="Screenshot 2022-10-24 at 17 20 22" src="https://user-images.githubusercontent.com/38911173/197550921-8616b673-baf0-459a-a0cd-e0151ca62a7e.png">

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-tools/pull/531

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-Issues/issues/1741
