### ISSUE TITLE
GPX slope range and color space seems a little odd?

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#11775]
I am wondering about the scale and color range we offer to display GPX files:

![Untitled](https://user-images.githubusercontent.com/845735/119715025-d6388480-be63-11eb-97ba-e2d236cfe955.png)
- Why would we chose an asymmetric range from -25% to + 100%? Shouldn't the range be strictly symmetric, i.e. from -x% to +x%?

- And the corresponding color range should likewise be symmetric, with one color fading (here red) indicating ascent, the opposite scale (green) indicating decline, and a more neutral color range in the middle (here I faded blue/gray between -5% and +5%) indicating the more leveled stretches?

![Untitled2](https://user-images.githubusercontent.com/845735/119715736-9aea8580-be64-11eb-8d92-be2b527ef6c5.png)

**Comment by vshcherb** [comment]
This is not correct image and yes it's not symmetric. 
.... -> -25% white
0% - green
8% - yellow
25% red
100% -> ... violet

**Comment by Hades1503** [comment]
Hello,
can the slope color already be used in the application?
![image](https://user-images.githubusercontent.com/79785663/120489672-1cd43480-c3b8-11eb-974a-cfd5cabdf88c.jpeg)

**Comment by sonora** [comment]
Problem with that color scheme is that it does not distinguish between ascent and descent (going up or down), which for e.g. bikers is essential.

**Comment by Nine-Tailed** [comment]
See also this issue https://github.com/osmandapp/OsmAnd/issues/11829

**Comment by Hades1503** [comment]
Hi,

for hiking, having the color of the slope is good to apreander the dificult of the ascent but the descent is just as important. therefore, a rise in purple + 60% is trying (and may be impossible) as a descent to + 60%. That is why my proposal refers to the slope color already presented in the application.

the graph in the analysis of a trace would therefore be more readable rather than the current graph with the% of ascent and descent. of course on the graph will keep the slope curves but would be filled with color (that of the slope curves)

seems irrelevant to you?

sorry for my english = gg translation

**Comment by dmpr0** [comment]
• Resource file with: **legend img_legend_route_slope**
• Add new string below legend "Grey color is used when slope is undefined."
• This UI part should be the same for calculated route appearance and track appearance.
![Снимок экрана 2021-06-03 в 18 39 45](https://user-images.githubusercontent.com/9365308/120672545-15398c00-c49b-11eb-9991-dbcbe47caccb.png)

**Comment by sonora** [comment]
@vshcherb This new proposal is a lot better than what we have now. But it still does not cater e.g. skiers (both dowhill and cross country) nearly as well as a symmetric pattern. For skiers downhill slopes exceeding 25% are very coomon, but off this proposed scale.

**Comment by sonora** [comment]
PS: In addition to my point stated above, the 'green' color range we now use is rather symmetric around the zero mark, meaning we don't change base color for the zero transition.

The effect is that there is very little (almost no) distinction between slight ascents and slight descents, e.g. +3% or -3% ( but this mean a huge difference to e.g. joggers).

**Comment by vshcherb** [comment]
@sonora true its a problem...

**Comment by vshcherb** [comment]
Thinking to swap colors Green and White

**Comment by sonora** [comment]
I guess the proper way to do it is really how I propose in my first post above
- in the fashion that **at the zero transition** the base color we fade to needs to change (in my example green is downhill and red is uphill)
- the **range around zero** (blue in my example) needs to be sufficiently narrow to spot small deviations (probably narrower than I picked it above)
- the **percentage range covered needs to be symmetric**, e.g. -100% to +100%.

The drawback is that if we only blend 3 colors it is harder to estimate the actual percentage numerical value, you need to closer compare to the legend.  We could move to 5 or even 7 (different) colors, to fix this. But maybe also simply stay with blending 3 as I propose, and simply display the exact numeric value when someone (long-)taps on a trackpoint on the map.

**Comment by vshcherb** [comment]
There are 2 main colors that could be zero that's black or white, only in that case it's possible to distinguish between + and -.  We're going to update to this colors
![telegram-cloud-photo-size-2-5330434175800554219-x](https://user-images.githubusercontent.com/1042025/121035555-491ff480-c7ae-11eb-85fb-1ee644231c21.jpg)

**Comment by scaidermern** [comment]
I think there is still room for improvement.

An incline of 10% is already quite noticeable for hikers and cyclists. However with the currently used color range a 10% incline is hardly noticeable on the map. The colors do get more visible at 25% but such an incline won't be found on almost any road, except at very steep mountains. Yet, even in steep mountains, inclines larger than 40% are rare and only present on short stretches. Inclines larger than 50% do hardly exist. As a consequence, the differentiation between 50% and 100% will probably never appear

I'm wondering if we can make the color space even more useful for typical use cases (cycling, hiking), e.g. by moving the red region from 25% to maybe 15%.

Another issue is the color range below 0%. While a steep descents are quite nice for bicycles they can get very demanding for hikers. Descends larger than 25% aren't visible with the current color space. This is bad and needs to be improved, too.

**Comment by scaidermern** [comment]
> I think there is still room for improvement.
> 
> An incline of 10% is already quite noticeable for hikers and cyclists. However with the currently used color range a 10% incline is hardly noticeable on the map. The colors do get more visible at 25% but such an incline won't be found on almost any road, except at very steep mountains. Yet, even in steep mountains, inclines larger than 40% are rare and only present on short stretches. Inclines larger than 50% do hardly exist. As a consequence, the differentiation between 50% and 100% will probably never appear on the map.
> 
> I'm wondering if we can make the color space even more useful for typical use cases (cycling, hiking), e.g. by moving the red region from 25% to maybe 15%.
> 
> Another issue is the color range below 0%. While steep descents are quite nice for cyclists they can get very demanding for hikers. Descends larger than 25% aren't visible with the current color space although being important while hiking. This is bad and needs to be improved, too.
> 
> I'm not really sure if the color space needs to be symmetric since this makes it more harder to distinguish different incline/decline values. However there are valid reasons for showing declines the same way as inclines.

Maybe something like this?

![gradient](https://user-images.githubusercontent.com/1040784/126763793-41143d49-2790-4dbc-8eab-5fdac37fc340.png)
Left half is descent, right half is ascent.

- The range between 0% and 15% has large color variations because this is the important range for most use cases.
- The range between 50% and 100% has only slight color variations because these ascent/descent values typically don't occur. 
- The range between 15% and 50% is a bit underrepresented, though.
- The color space is symmetric, showing both ascent and descent up to 100%.

**Comment by scaidermern** [comment]
Komoot seems to use orange for inclines between 5-10% and red for inclines between 10-15% (approximately). This is from the height profile, though. They don't support coloring tracks by slope.

**Comment by scaidermern** [comment]
@vshcherb What do you think about the above suggestion?

**Comment by vshcherb** [comment]
Using green -> blue for slopes downhill  schema to make it symmetric, well that's not bad though I'm not sure why it should be perfectly symmetrical

**Comment by scaidermern** [comment]
> Using green -> blue for slopes downhill schema to make it symmetric, well that's not bad though I'm not sure why it should be perfectly symmetrical

Because descent matters for hiking. It doesn't has to be perfectly symmetrical I guess but at least it seems to be possible to do it.

**Comment by vshcherb** [comment]
this issue is already closed for 4.0, please feel free to create  new one

**Comment by shurasmiling** [comment]
https://docs.osmand.net/docs/user/map/tracks-on-map#track-appearance
https://docs.osmand.net/docs/user/navigation/guidance/map-during-navigation#route-line-appearance
