### ISSUE TITLE
Exporting profile bug

### ISSUE THREAD

**Issue by letkan** [osmandapp/OsmAnd#11789]
**This is on Android 11 with recent nightly OsmAnd**
When choosing to export a profile I'm given the option to select data and clicking on _Continue_ doesn't ask me to choose where to export the data (internal or external storage) but gives me options to _Share_. Exporting is most commonly understood as saving to storage not sharing. Also the apps choices for sharing go from web browsers to music app or image editing app so something is definitely wrong.

**Comment by vshcherb** [comment]
In my case Share app are Messengers, Emails and Google Drive for example. File system becomes more & more obsolete with newer Android versions

**Comment by letkan** [comment]
My main point was that _Export_ is misleading for what it actually does and I was looking for an option to save a configuration data.

**Comment by EssBee59** [comment]
Hello Letkan,

If you install a file manager on your Android smatphone (I am using as example the "FX" file manager), then the "FX"+ "save as.."  will appear in the list of the app´s that can "share" the configuration.
Choosing this app,  you can save the config-file locally....
regards

**Comment by letkan** [comment]
> Hello Letkan,
> 
> If you install a file manager on your Android smatphone (I am using as example the "FX" file manager), then the "FX"+ "save as.." will appear in the list of the app´s that can "share" the configuration.
> Choosing this app, you can save the config-file locally....
> regards

Thanks for suggestion, the file manager I'm using doesn't show up in the list of apps but I found [SaveTo](https://f-droid.org/en/packages/xyz.myachin.saveto/) which did the trick.

**Comment by dmpr0** [comment]
Moved to https://github.com/osmandapp/OsmAnd/issues/12264
