### ISSUE TITLE
Should index every tourism=* object

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#1178]
It seems that some `tourism=*` objects are missing from the `Tourism` category in the POI search.
Every `tourism=*`, including `tourism=yes`, should be indexed.

**Comment by xmd5a2** [comment]
It potentially can cause some sort of unpredictable behavior. Better way to add more tags is to add them explicitly. This takes care of translations and icons. Added some tourism tags https://github.com/osmandapp/OsmAnd-resources/commit/af166ebc3deb97d42292fbc76d2aa85a2b8b4e4a

**Comment by naoliv** [comment]
Good! `<type tag="tourism" value="yes" minzoom="15" poi_prefix="general_tourist_attraction_"/>` should catch most of them.
