### ISSUE TITLE
Packages are not marked as downloaded

### ISSUE THREAD

**Issue by a903user** [osmandapp/Osmand#1179]
Downloaded hillshade and contour lines packages are not marked as downloaded. See screenshots (packages for Czech Republic).

Osmand 2.0.1 @ Android 4.4.4 (CyanogenMod)

![screenshot_2015-05-05-14-24-07](https://cloud.githubusercontent.com/assets/12199873/7472556/02980372-f334-11e4-83e5-1df5495292ab.png)

![screenshot_2015-05-05-14-24-36](https://cloud.githubusercontent.com/assets/12199873/7472559/09121076-f334-11e4-9387-73eace8a3a87.png)

![screenshot_2015-05-05-14-42-41](https://cloud.githubusercontent.com/assets/12199873/7472689/6b2333d4-f335-11e4-845d-aeee593ac124.png)

**Comment by vshcherb** [comment]
Fixed
