### ISSUE TITLE
Bicycle routing: cycleway gets avoided

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#11803]
In the following example the cycleway gets avoided. OsmAnd routes from the cycleway back to the road:

![photo_2021-06-01_08-18-21](https://user-images.githubusercontent.com/1040784/120275650-f2984f00-c2b1-11eb-9f82-ab49527084a4.jpg)

From 51.0037098,13.6650395 to 51.0033384,13.6656618

At first I thought this could be caused by the [`barrier=kerb` node](https://www.openstreetmap.org/node/4861479040), which isn't a real barrier.

However there is a similar example nearby without any `barrier=kerb` node:

![photo_2021-06-01_08-33-32](https://user-images.githubusercontent.com/1040784/120277221-10ff4a00-c2b4-11eb-86ba-235b5d75015d.jpg)

From 51.0030211,13.6659622 to 51.0026295,13.6665845

The cycleway is [way 588431403](https://www.openstreetmap.org/way/588431403) tagged with highway=path, bicycle=designated, foot=designated, footway=sidewalk. Could this be caused by the footway=sidewalk tag?

**Comment by vshcherb** [comment]
Well it's probably not bad for pedestrian navigation. (you didn't mention it's pedestrian actually or it is cycling?)

**Comment by scaidermern** [comment]
> Well it's probably not bad for pedestrian navigation. (you didn't mention it's pedestrian actually or it is cycling?)

Oh, sorry. It is cycling!

**Comment by scaidermern** [comment]
Works, thanks!
