### ISSUE TITLE
Incorrect location determination through google map link

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#11809]
### Description
When I want to search the location using Google map link OsmAnd determinate it in the wrong place.

### How to reproduce?
Check the link below in Google Map and OsmAnd.
http://maps.google.com/maps?q=47.09292481347881%2C15.411024038922198%28GOLF+MEX-N4100BT+19.+Mai+2021%2C+21%3A37+acc%3D4%2C9%29

![image](https://user-images.githubusercontent.com/80623554/120347561-12a52e00-c305-11eb-88e3-7b1303e422fd.png)
![image](https://user-images.githubusercontent.com/80623554/120347628-20f34a00-c305-11eb-8b8a-cb312fe71374.png)

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: Android 9
Device model: Experience XZ1

**Comment by cwerner1** [comment]
In my OsmAnd the marker is placed 450km away. 
The Point should be ~100 Meters away from current positon



![grafik](https://user-images.githubusercontent.com/1199614/120350877-a83dbf00-c2ff-11eb-995f-7250cf71f886.png)


OsmAnd Version 3.9.10
Android/iOs version: EMUI 10.1.0.316 - Android 10
Device model: Huawei P40 lite

**Comment by alisa911** [comment]
It has been fixed in https://github.com/osmandapp/OsmAnd/issues/12521
@ cwerner1 please describe your bug in more detail

**Comment by cwerner1** [comment]
@alisa911
I originally contacted support - and anastasiia936 was kind enough to attach the ticket to her reply. So I added an additional screenshot for the Problem.

I am already looking forward to v4.1
