### ISSUE TITLE
GPX file not saved immediately

### ISSUE THREAD

**Issue by HubMiner** [osmandapp/OsmAnd#11810]
### Description
After pressing "Save and stop recording", GPX file is often not saved (often, not always).
This may be related to issue 11765 - after pressing Save and Stop, the apps still shows track length on the red Record button.

### How to reproduce?

1. Driving as default mode.
2. Start walking.
3. Switch to walking/hiking mode.
4. Start recording.
5. After some track is recorded, press Red record button.
6. Press: Stop.
7. Press: Save and stop recording.
8. Track saved screen, press: Close
9. Open a file browser, go to folder with saved tracks (matches what's configured in OsmAnd setting).

Usually, after a long recording (over 30 minutes), tracks are not present.
After a phone is rebooted, and something else happens, the tracks show up.

This behavior started a few months ago.

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: Android 11
Device model: Samsung S10

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

Offline maps.

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/11765
