### ISSUE TITLE
Checkboxes of downloaded maps are not checked -> will be downloaded twice

### ISSUE THREAD

**Issue by MPW1412** [osmandapp/Osmand#1181]
Hello,

downloaded maps are not checked in the list of downloadable content. If I check them even they're already downloaded, they'll be downloaded again, which is a waste of time and traffic volume.

This issue may be related to the fact, that I set the storage point to external space 2 (sd card).

Galaxy S4 with Android 5.0.1 official rom. OsmAnd version 2.0.1.

Thanks for reading.

Greetings
MPW

**Comment by vshcherb** [comment]
This is expected, in downloaded list you see 2 labels Local Version and Server version, so that's how you can distinguish already downloaded maps

**Comment by MPW1412** [comment]
I see your point, but still a behavior like in maps.me would be nicer....
