### ISSUE TITLE
Return amenity=toilets POI preset

### ISSUE THREAD

**Issue by alexandrz** [osmandapp/Osmand#1182]
I used to add toilets often, but now I can only add user_defined_other=toilets

**Comment by vshcherb** [comment]
What language do you type and what language program ui is using

**Comment by alexandrz** [comment]
English

**Comment by mikeshenson** [comment]
amenity=toilets shows up when you start typing "bathroom" when creating a POI.

**Comment by mikeshenson** [comment]
Could you also add back the "clothes" option when creating a POI? It took me a while to find "apparel" now is the shop=clothes.

**Comment by vshcherb** [comment]
Fixed
