### ISSUE TITLE
NPE while displaying split interval tracks

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#11826]
Not sure how to reproduce:
[exception.log.txt](https://github.com/osmandapp/OsmAnd/files/6589282/exception.log.txt)

**Comment by sonora** [comment]
Related, but not the same, not sure if it was fixed by the same remedy:
[exception.log.txt](https://github.com/osmandapp/OsmAnd/files/6636420/exception.log.txt)

**Comment by vshcherb** [comment]
Fixed (related to rotation)
