### ISSUE TITLE
Render hiking routes in the right colour

### ISSUE THREAD

**Issue by ahgera** [osmandapp/OsmAnd#11833]
A lot of [walking and hiking routes](https://wiki.openstreetmap.org/wiki/Walking_Routes) in OpenStreetMap have an associated [colour](https://wiki.openstreetmap.org/wiki/Key:colour) value. This isn't just to make it pretty, it makes it much easier to know you're on the right path, since these routes often have signs along the route with the color.
![image](https://user-images.githubusercontent.com/34133296/120640524-dee81680-c472-11eb-98a1-be843f852c54.png)
Take [this route](https://www.openstreetmap.org/relation/7306554) for instance, it has a colour value of #d8212b. The [whole area](https://www.openstreetmap.org/#map=16/58.7173/14.5922) has several trails, each with it's own color assigned on signs and along the trails:
![image](https://user-images.githubusercontent.com/34133296/120641217-a3018100-c473-11eb-9d96-1331cfc05751.png)
This is what it looks like in OsmAnd standard map style:
![image](https://user-images.githubusercontent.com/34133296/120641433-df34e180-c473-11eb-99e8-0a83c55fffe9.png)
and OsmAnd topo style:
![image](https://user-images.githubusercontent.com/34133296/120641480-efe55780-c473-11eb-8358-27c2a2810e56.png)
Compare that to [mapy.cz outdoor style](https://en.mapy.cz/turisticka?x=14.5951272&y=58.7201045&z=15&l=0):
![image](https://user-images.githubusercontent.com/34133296/120641578-0db2bc80-c474-11eb-80d2-20c51eda8acd.png)
and [Locus map](https://play.google.com/store/apps/details?id=menion.android.locus):
![image](https://user-images.githubusercontent.com/34133296/120642133-ca0c8280-c474-11eb-9718-5c6e1496d0c7.png)

OsmAnd can render bike routes in a separate color (as visible in the screenshots), I think it makes sense to not only render walking routes as well, but also use the colour value in the OSM data.

**Comment by vshcherb** [comment]
This is currently not possible, only 1 color per track is now rendered.

**Comment by ahgera** [comment]
Each route only needs one color, but I guess there are some ways which belong to multiple routes which would be a problem. How are you handling the biking routes today, they're similar relations as the walking routes, right? Maybe you can render each walking route relation separately with 50% opacity, so it's visible if multiple routes intersect.

Or maybe do similarly to what you do with the biking routes, put the names along the route, but use the route color for each name. On this way there are three bike routes:
![image](https://user-images.githubusercontent.com/34133296/120675235-30a19880-c495-11eb-8d19-4d646683951a.png)

Opencyclemap handles this ok I think, even if mapy.cz is nicer.
![image](https://user-images.githubusercontent.com/34133296/120675791-aefe3a80-c495-11eb-84b2-727bdfd54236.png)

**Comment by ahgera** [comment]
I just found out that you already support exactly this feature, but using a different tag. If you go to "Configure Map", "Routes", and then in "Hiking symbol overlay" you select "Color by OSMC hiking symbol", you get this:
![image](https://user-images.githubusercontent.com/34133296/120687329-3356ba80-c4a2-11eb-8e25-98313bc6ba07.png)

That works great, but it only works when the [osmc:symbol](https://wiki.openstreetmap.org/wiki/Key:osmc:symbol) is set to some color. If you could extend this to also work with the [colour](https://wiki.openstreetmap.org/wiki/Key:colour) key for walking and biking routes that would be great.

**Comment by Zirochkabila** [comment]
Try to make it this way: Configure map > Hiking routes > Colouring according to OSMC 

58.718200, 14.607200
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/189347552-0facf593-cb42-4387-aad3-059ffe02c36d.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>
