### ISSUE TITLE
80% Screen Black in Daylight to Save Battery

### ISSUE THREAD

**Issue by Dollarius** [osmandapp/OsmAnd#11836]
I use OsmAnd for cycling and I think it's a really awesome map/navigation tool.
As I'm often in bright daylight conditions, my phone increases the luminosity of its big screen to 100% and this consumes a lot of battery.

I thus have a proposal: would it be possible to have a dedicated function that makes most of the screen (80%?) black while keeping just a small portion of the screen with a bright map/navigation view?
Nowadays several phones use oLED displays, thus using only a portion of the screen would significantly reduce battery consumption.
Also, phone screens are so big that a small portion would be enough for navigation.

Thank you for your possible consideration of this new functionality.
Giordano

**Comment by vshcherb** [comment]
This functionality is pure system functionality and should be controlled by Android system.

**Comment by Dollarius** [comment]
Thanks for your feedback vshcherb.
I probably did not explain myself well, as the app should definitely be able to draw two black rectangles over the map [100% width and 40% height] in order to make the top and bottom portions of the screen black.
I don't know how difficult would be to implement it though.
Best,
Giordano
