### ISSUE TITLE
Islands don't render as land

### ISSUE THREAD

**Issue by blackboxlogic** [osmandapp/OsmAnd#11837]
### Description
Islands off the coast of Maine USA don't render as land, and have a blue fill (like the water around them).

### How to reproduce?
Browse around the coastal Maine area on the map. Observe island background color is the same as the water.

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: Android 11
Device model: Pixel 3

**Maps used (online or offline):**
Offline Map: "United States Maine" from 4/30/2021
![Screenshot_20210603-212004.png](https://user-images.githubusercontent.com/31355456/120732440-5047b980-c4b3-11eb-861f-276683b05637.png)

**Comment by xmd5a2** [comment]
Not reproducible, but there is a similar issue nearby
![Screenshot_2021-06-09_10-39-05](https://user-images.githubusercontent.com/5829014/121313419-07f32600-c90f-11eb-9c79-c486907f784d.png)
http://www.openstreetmap.org/#map=13/43.75383/-69.83815

**Comment by blackboxlogic** [comment]
Regarding "not reproducible":
You went to this location in OsmAnd and islands rendered correctly? If that's the case, what's your best guess fire my experience? Bad setting? Clear cache? Fresh install?

The related ticket you made was a osm data fix. This island's tags look right to me, can you look at it? https://www.openstreetmap.org/way/219705220

**Comment by blackboxlogic** [comment]
In case anyone finds this later, I had `Configure Map -> Map rendering -> Hide -> Polygons` selected. Fixed by un-selecting that.
