### ISSUE TITLE
`slight_right` and `slight_left` are not correctly handled

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/OsmAnd#11830]
I suppose `slight_right` and `slight_left` are not correctly handled.
Subject [road ](https://www.openstreetmap.org/way/229349124#map=18/50.14569/19.43700&layers=D)has turn:lanes=through|through|slight_right.

Similar [case ](https://www.openstreetmap.org/way/538086282)with slight_left:
![Turn_lanes_Slight_left](https://user-images.githubusercontent.com/4776779/118991688-9ddd0600-b98c-11eb-8b50-f82b5fe1f5b3.jpg)

_Originally posted by @pl71 in https://github.com/osmandapp/OsmAnd/issues/11716#issuecomment-845150643_

**Comment by xmd5a2** [comment]
Test added

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/pull/11918
