### ISSUE TITLE
Navigation: weird 30km+ detour

### ISSUE THREAD

**Issue by pihug12** [osmandapp/OsmAnd#11849]
### Description

OsmAnd 3.9.10 wants to make a weird and long detour for a *Saint-Paul-et-Valmalle* -> *Gare de Montpellier Sud de France (building)* drive.

![Screenshot_20210529-223219](https://user-images.githubusercontent.com/678038/120887943-ff8ca980-c5f5-11eb-8c7f-74d661f74739.png)

### How to reproduce?

**Map:** Europe > France > Occitanie > Hérault
**Start:** Saint-Paul-et-Valmalle
**Finish:** Gare de Montpellier Sud de France (building)

Start a navigation with a car.

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: Android
Device model: Samsung Galaxy Note 10.1 Wi-Fi (2014)

**Comment by pebogufi** [comment]
Source. 43.62620° N, 3.67542° E
destination. 43.59521° N, 3.92439° E

I don't think that your destination (with car) is the "Gare de Montpellier Sud de France" itself, but the next parking site near to it. 
Select such a parking site, the results of navigation by car will be much better !
This is a typical problem for calculation problems, when the destination is a area with a center which can **NOT** be reached **directly by car**. In such a situation select a position which can be reached by car, like a parking site, street or something else near your planned destination.
Hope this can help.
Regards Peter

**Comment by xmd5a2** [comment]
As @pebogufi mentioned above, changing end point to parking solves issue. When end point is near A 9 motorway it tries to go south-west and make U turn to get destination. Looks like this is the shortest way to get to A9 in north-east direction
