### ISSUE TITLE
unneccessary "continue straight" turn instructions following an "attached to road" gpx track

### ISSUE THREAD

**Issue by frozn** [osmandapp/OsmAnd#11850]
during following an "attached to road" gpx track i noticed some unneccessary "continue straight" turn instructions.

example ([Test-Track.zip](https://github.com/osmandapp/OsmAnd/files/6602912/Test-Track.zip), track created with Garmin BaseCamp, car profile):

![image](https://user-images.githubusercontent.com/5655881/120900613-fcb1a900-c635-11eb-94f6-faab11e96168.png)

if i didn't use the gpx track and start a new navigation (car profile) in osmand und set manually the same start and end location, the unneccessary "continue straight" turn instructions are gone:

![image](https://user-images.githubusercontent.com/5655881/120899969-a0995580-c632-11eb-9024-d6309a039d29.png)

**Comment by vshcherb** [comment]
This is extra information which is valuable for navigation i.e. turn lanes are displayed. Note that these arrows have no impact on voice navigation cause  they are mute.

**Comment by frozn** [comment]
but why is this extra information not displayed if navigation was started "the normal way" with start and end location?

**Comment by vshcherb** [comment]
> but why is this extra information not displayed if navigation was started "the normal way" with start and end location? this seems not consistent...

It is displayed as we tested it.
