### ISSUE TITLE
Don't show motorway names, e.g. in Denmark

### ISSUE THREAD

**Issue by Neuwessi11** [osmandapp/OsmAnd#11852]
Hi @ all,

when driving through Denmark I got problems especially when changing motorways, because in Denmark the motorways seem to have names. These names in OsmAnd are shown first, and later the destinations. But because of the long motorway names there is no space left for showing the destinations.
See picture here:
![Screenshot_20210606-153243 1](https://user-images.githubusercontent.com/70072237/120926681-3211d180-c6de-11eb-9f7b-e012a9a46798.png)

The problem is the more annoying because in Denmark these motorway names are never signed in real life.
Can you add a line never to show motorway names?
By the way: Same thing on urban motorways or trunk roads. I personally have no advantage of getting told that I have to change to Berliner Straße (e.g.), when it is not shown on a sign. And in my experience the road names are never shown on any motorways or trunk roads, even in urban ones.

**Comment by pebogufi** [comment]
See also
https://github.com/osmandapp/OsmAnd/issues/11778

**Comment by vshcherb** [comment]
Yes duplicate to #11778

**Comment by Neuwessi11** [comment]
Sorry, but this is not at all duplicate to #11778!

This issue is NOT about the names of motorway_junctions, but of the motorways itself!

**Comment by vshcherb** [comment]
Summarized here https://github.com/osmandapp/OsmAnd/issues/11778#issuecomment-856933600
