### ISSUE TITLE
Dutch TTS file does not work correctly.

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#11857]
Spoken instruction in Dutch does not work with nl_tts.js. It does work with spoken Dutch with nl (several *.ogg files). Checked on both devices: Android version 5.1 and on tablet Android version 7.0.  English and German instructions work correctly, but with Dutch instruction you only hear a sound ("pling") after which nothing more.

**Comment by sonora** [comment]
Is your device set up correctly to support Text-to-speech in Dutch? Got to your **_Android_** (not OsmAnd) **_settings_**, usually under "_Language and input_". Then find the "_Text-to-speech_" settings for the TTS engine you are using.. Find "_Install voice data_", or similar, and download Dutch, male or female as you please.

There is usually a "_Listen to an example_" button, and if all is set up, you should hear a phrase in Dutch.

Then go back to OsmAnd, and it should work.

**Comment by vshcherb** [comment]
Confirming that on S10 - Dutch TTS works correctly
