### ISSUE TITLE
lost mapstyle when underlay is used

### ISSUE THREAD

**Issue by mariush444** [osmandapp/OsmAnd#11866]
### Description

While the underlay map is used the map style is switch off

This is offline map while the underlay map is NOT used.
![image](https://user-images.githubusercontent.com/66887280/121192948-b3e43500-c86d-11eb-86df-1809b15b5764.png)

This is offline map while the underlay map is used
![image](https://user-images.githubusercontent.com/66887280/121193131-dc6c2f00-c86d-11eb-8f46-336945fca91a.png)

There is no problem like this while the overlay map is in use.

### Your Environment
OsmAnd Version:3.9.10
Android/iOS version:8
Device model:g3212

**Comment by vshcherb** [comment]
There is a special setting to hide polygons or not with underlay source. Check it in the settings.
