### ISSUE TITLE
Incorrect handling of opening_hours:signed

### ISSUE THREAD

**Issue by Lee-Carre** [osmandapp/OsmAnd#11862]
### Description
An element which has both

    opening_hours=PH,Mo-Su 07:00-22:00
    opening_hours:signed=no

ends up being handled (within OsmAnd, according to the PoI details UI) as

    PH, Mo-Su 07:00-22:00 || no "Signed"

and (consistently, via various places in the UI (element details, search results, history)) advises the user (circa noon) that the place is currently closed but will be open tomorrow at 07:00.

This is incorrect in multiple ways.

### How to reproduce?
Example: [Park Stores](http://www.openstreetmap.org/node/1780382765).

For those unfamiliar with [opening_hours:signed](http://wiki.openstreetmap.org/wiki/Key:opening_hours:signed), it's commonly used by StreetComplete.

In this instance, during survey, I decided to enter and ask staff for their opening hours. However, since there was still no sign giving the hours, I included both keys for the benefit of other surveyors in future, so that it might be clearer how I acquired the opening hours, during survey, despite there being no sign.

I suggest that developers also consider & account for the possibility of

    opening_hours:signed=yes

since I'm adding that tag when places do have a sign.

### Your Environment
OsmAnd Version: OsmAnd+ v3.9.10 from F-Droid repository
Android version: Android v10 [stock distribution from Samsung]
Device model: SM-A405FN

**Maps used (online or offline):**   
Offline map; other than the included basemap mini, I have Gb_england_channel-islands_europe of 2021-06-01.
I also have OsmAnd Live enabled for the same region.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-tools/commit/01b73dda105969127cc5af45f0c3d5bd7548d95d
