### ISSUE TITLE
Can't upload traces

### ISSUE THREAD

**Issue by stemy2** [osmandapp/OsmAnd#11875]
### Description
I can't upload my gox traces to osm. At every attempt, i have the message "0 of 1 element uploaded".

### How to reproduce?
Create a gpx track.
Try to opload it to osm.

### Your Environment
OsmAnd Version:3.9.10
Android/iOS version:8.1
Device model:samsung galaxy s7

**Maps used (online or offline):**   
Offline
OSM default map

**Comment by vshcherb** [comment]
Please share any trace you can't upload, so we can test it ourselves. You could also see / share the error messages in Development Settings -> Logcat buffer (what exactly error happened).

**Comment by ddaemon82** [comment]
I had the same issue.
I was using off-road tracks in GPX format reularly. Recently the opened tracks show up with zero size.

Uninstalling Osmand completely and reinstalling it solved the issue.
