### ISSUE TITLE
Element tags; opening_hours; mishandling of “closed” modifier for 24/7 case

### ISSUE THREAD

**Issue by Lee-Carre** [osmandapp/OsmAnd#11888]
### Description
An element which has

    opening_hours = 24/7 closed "Temporarily, for major repairs"

is treated (by OsmAnd) as being perma-open rather than indefinitely closed.

Having checked the tag value in question with evaluation and/or validation tools, they report that the syntax is correct and yields the desired meaning. So, OsmAnd's interpretation seems incorrect.

### How to reproduce?
Examples:
* [Green Street Toilets](http://www.openstreetmap.org/node/1844057712)
* [Victoria Park Toilets](http://www.openstreetmap.org/way/168120773)

### Your Environment
OsmAnd Version: OsmAnd+ v3.9.10 from F-Droid repository
Android version: Android v10 [stock distribution from Samsung]
Device model: SM-A405FN

**Maps used (online or offline):**
Offline map; other than the included basemap mini, I have Gb_england_channel-islands_europe of 2021-06-01.
I also have OsmAnd Live enabled for the same region.

**Comment by vshcherb** [comment]
We need to fix C++ as well.

**Comment by Dima-1** [comment]
Fix C++ https://github.com/osmandapp/OsmAnd-core-legacy/pull/33
