### ISSUE TITLE
Videosurveillance POI not displayed or not in the map data

### ISSUE THREAD

**Issue by Pantoofle** [osmandapp/OsmAnd#11883]
### Description
In big cities, when checking the "Video-surveillance" Point of Interest in the map settings, only nodes in isolated, remote areas are displayed. It's impossible to display the cameras of big cities. Even in the research bar, when looking for "Video-surveillance", no nodes are found in big cities.

### How to reproduce?
Map Parameters > POI overlay > Search for Video-surveillance > Display the nodes on the map
Go to a big city (tested with Lyon, France). No nodes are displayed, even if in the web version the nodes do exist.

### Your Environment
OsmAnd Version: OsmAnd~ 3.9.10
Android/iOS version: Android 9
Device model:

**Maps used (online or offline):**   
For the Lyon example: France_auvergne-rhone-alpes_lyon_europe

**Comment by scaidermern** [comment]
I guess this is still #3155? Only named cameras are searchable? It would be nice to have them all searchable.
