### ISSUE TITLE
Edit Vazir Persian/Arabic font

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#11898]
Exist Persian font is incorrect, the problem is in Half-space.
![IMG_20210609_210259](https://user-images.githubusercontent.com/80623554/121684328-3582cf80-cac7-11eb-8676-3ffb826688ec.jpg)

Persian fonts that can be added.
https://drive.google.com/drive/folders/1a47Kzq9_3MoVn_mQI0hCrBT4qA9YBFQY?usp=sharing

**Comment by ivanPyrohivskyi** [comment]
Before:
![Screenshot 2021-09-15 at 18 08 35](https://user-images.githubusercontent.com/1040293/133459851-8dfaa5ee-7aba-40bc-8e9f-8627f7839f71.png)
After:
![Screenshot 2021-09-15 at 18 08 48](https://user-images.githubusercontent.com/1040293/133459855-108dd503-864b-473b-b925-072074f399f7.png)

Pull-request:
https://github.com/osmandapp/OsmAnd-core-legacy/pull/35
