### ISSUE TITLE
additional included waypoints not shown and no voice prompts triggered following an "attached to road" gpx track

### ISSUE THREAD

**Issue by frozn** [osmandapp/OsmAnd#11904]
during following an "attached to road" gpx track i noticed that additional included waypoints (e.g. for breaks) in this track are not shown and no voice prompts are triggered (if enabled in "Navigation settings->Voice prompts->Track waypoints").

example ([Test-Track with WP.zip](https://github.com/osmandapp/OsmAnd/files/6642721/Test-Track.with.WP.zip), track with additional waypoint created with Garmin BaseCamp, car profile):

![waypoint_in_attached_to_road_gpx_track_missing](https://user-images.githubusercontent.com/5655881/121785987-6e04d500-cbbd-11eb-8b40-62ce50830615.jpg)

if i didn't use the "attached to road" feature additional included waypoints are shown and voice prompts are triggered:

![waypoint_in_gpx_track_showing](https://user-images.githubusercontent.com/5655881/121786077-f1262b00-cbbd-11eb-8cac-8ab773019b88.jpg)

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/pull/11993
