### ISSUE TITLE
audio video notices - link syntax in gpx files

### ISSUE THREAD

**Issue by hatzfeld** [osmandapp/Osmand#1191]
Using gps tracking and audio video notices in Osmand 2.0.1, I experienced this syntax error in the exported gpx file (which made it unable to be opened by JOSM):

Links to the media files are represented in this mode:
\<link link="$photo.jpg" />

This is how it should look like:
\<link href="$photo.jpg">\<text>$description</text>\<type>image/jpeg</type></link>
or at least:
\<link href="$photo.jpg" />

**Comment by vshcherb** [comment]
Fixed
