### ISSUE TITLE
Render solar panels below other POIs

### ISSUE THREAD

**Issue by rivermont** [osmandapp/OsmAnd#11911]
Currently, solar panels close to other POIs (for example on the roof of the building) are rendered on top of the other POI, which is not ideal. Rooftop solar panels are not a destination or place of interest at all generally, and should not be prioritized like this.

[Example area](https://www.openstreetmap.org/#map=19/38.96751/-95.26135)

OSM Carto of course does not render solar panels at all:
![image](https://user-images.githubusercontent.com/25139386/121819931-defbc980-cc5d-11eb-9ddd-ce0815bb8399.png)

In OSMAnd, the 'Merc Coop' POI does not display until a very high zoom as shown in these screenshots:
![Screenshot_20210607-100944](https://user-images.githubusercontent.com/25139386/121819957-ffc41f00-cc5d-11eb-8616-2176ac469a86.jpg)

![Screenshot_20210607-100951](https://user-images.githubusercontent.com/25139386/121819958-00f54c00-cc5e-11eb-9550-41c7b9505df0.jpg)

**Comment by thompehw** [comment]
Agree that rendering order could be better, but note that Configure_Map>Hide>Overground_objects hides rooftop solar panels. As a user where they are densely mapped, this was a great discovery!

**Comment by xmd5a2** [comment]
Fixed by https://github.com/osmandapp/OsmAnd-resources/commit/e77d0230d7eec69484e069f97ab32a680ea5604c
