### ISSUE TITLE
Route jumps between nodes on different layers at exact same coordinates

### ISSUE THREAD

**Issue by mattmccutchen** [osmandapp/OsmAnd#11912]
# 🐞 routing report

The route jumps from a secondary road (layer 0 by default) onto a motorway bridge above it (tagged as layer 1).  Unfortunately, my car can't fly in order to complete this maneuver.  The two ways contain different nodes at the exact same coordinates, in this case because the ways were previously mapped incorrectly with a shared node, and the node was later split into two nodes without moving either of the new nodes ([changeset](https://www.openstreetmap.org/changeset/103915962)).

To help isolate the problem, I downloaded the osm file for a small surrounding region with JOSM, converted it to obf with OsmAndMapCreator, and loaded the obf file on my phone, and the problem still occurred.  Then I repeated the process but moved one of the two coincident nodes without significantly changing the shape of the way, and the problem went away.  Here is [a zip file of my test files](https://github.com/osmandapp/OsmAnd/files/6644638/osmand-nodes-jump-test-files.zip).  I could actually move that node on OSM, but my understanding is that I should avoid editing OSM to work around bugs in specific applications.

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, OpenRouteService, OSRM, etc.)

### Routing Profile

Car

### Start and end points

Approximately [this](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=39.43834%2C-76.63299%3B39.43771%2C-76.63397).

### Actual and expected routes

**Actual:**
<img src="https://user-images.githubusercontent.com/8885753/121821509-816c7a80-cc67-11eb-85d2-7f269144d448.png" width="270" height="555"/>
**Expected:**
<img src="https://user-images.githubusercontent.com/8885753/121821607-03f53a00-cc68-11eb-8c02-a9ded0f48421.png" width="270" height="555"/>

### Is this a regression?

I didn't test any previous version.

## 🌍 Your Environment

**OsmAnd Version:** Same problem in both:

<pre><code>F-Droid OsmAnd 3.9.10
OsmAnd Nightly 4.0.0#32163m (clean installation just to test this issue)
</code></pre>

**Device and Android/iOS version:** Google Pixel 3a, LineageOS 17.1-20210309-NIGHTLY-sargo

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download: Us_maryland_northamerica.obf dated 2021-05-31.  Same problem with small obf files I generated myself (see above).

- [ ] Online (tile / raster) maps 

**Anything else relevant?**

**Comment by scaidermern** [comment]
Is this a bug in the map generator? These ways aren't connected. But both have a node at the crossing point on top of each other:

- https://www.openstreetmap.org/node/7755166277
- https://www.openstreetmap.org/node/8684437483

**Comment by vshcherb** [comment]
Last 4 years there was an agreement those issue will be fixed on the map, so the node doesn't belong to 2 separate ways. Background: there are many other OSM apps that also rely on this buggy logic. 
There is no plan to fix it in OsmAnd cause it's seems very complicated but of course it's a bug in routing behavior. Workaround: change geometry on the map.

**Comment by mattmccutchen** [comment]
> Last 4 years there was an agreement those issue will be fixed on the map

Can you give me the link to this agreement so I can cite it when editing the map?  I couldn't find anything relevant in a few web searches.  Thanks.

> so the node doesn't belong to 2 separate ways

I wanted to confirm that the above was just a mistake in writing, not a misunderstanding.  In my example, there are 2 nodes at the same location, not one node on 2 separate ways.

**Comment by vshcherb** [comment]
You can find probably 1-2 OsmAnd issues but it might not be easy :-) 

2 nodes at exactly same location that's actually a big issue with OSM itself. It's not recommended to have overlapping nodes.

**Comment by scaidermern** [comment]
That might be true (I'm not exactly sure about this, maybe there are a few exceptions to this rule). However that doesn't explain why OsmAnd merges nodes belonging to different ways.

**Comment by vshcherb** [comment]
It doesn't merge nodes! It doesn't store which nodes connected to what and doesn't store node ids (it would make maps 2x bigger), so roads that consists of same coordinate points are considered to have intersection

**Comment by thompehw** [comment]
It's very common to have multiple nodes in the same place (KeepRight can flag them) and opinions seem to differ as to whether it's an "error". But I agree it's confusing to have them on ways that cross but do not join.

I wanted to check how common it is for highways to cross with duplicate nodes, and came up with [this](https://overpass-turbo.eu/s/18Dy)  overpass turbo query. E.g. for the case here:
![image_2021-06-22_021625](https://user-images.githubusercontent.com/39751382/122847576-dfe8c700-d2ff-11eb-9511-50f7935f6be3.png)

Unfortunately this query runs *very* slowly so you can only check small areas (eg. like a small town).  I checked a few places I know in the UK and have yet to find another case. Since this issue has been added to a milestone, it may be helpful to leave this example in OSM to be used for testing.

**Comment by LarfAndAHarf** [comment]
I've observed this kind of routing error between disconnected ways, even without exactly overlapping nodes—say, merely one node, or sometimes nodes quite close but not touching. Same issue?

e.g. either of the overpasses at [Interstate 80 crossing CR 626](https://www.openstreetmap.org/directions?engine=graphhopper_car&route=40.8769%2C-74.3276%3B40.8774%2C-74.3260#map=17/40.87798/-74.32696).

![josm screenshot showing ways crossing, with a single nearby-but-not-touching node](https://user-images.githubusercontent.com/991556/233157498-04944f97-8f08-4be6-9f39-bacbba853139.png)

![OsmAnd screenshot showing routing car off side of a bridge](https://user-images.githubusercontent.com/991556/233157784-1bef5de5-346a-4b1e-b705-3e7978bc4f5b.png)

**Comment by scaidermern** [comment]
@LarfAndAHarf Looking at the history of the involved roads there was an actual mapping error. This changeset with the title "changed way geometry as it was glued to bridge": https://www.openstreetmap.org/changeset/134166500. So it looks like this time it is not OsmAnd's fault.
