### ISSUE TITLE
show-hide button for showing tracks DELETES file

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#11935]
### Description
On the two screenshots is a button ("eye" symbol) to show / hide the track.
In both situations (screenshots) the hide function DELETES the file (without conformation dialog), but only after closing the window, not immediate
Eye-button = "Auf Karte zeigen" = "show on map"

![Show-hide button (eye) DELETES file-1](https://user-images.githubusercontent.com/18628183/122280651-b687ff80-cee9-11eb-824b-158b3ba5708e.jpg)

![Show-hide button (eye) DELETES file-2](https://user-images.githubusercontent.com/18628183/122280284-54c79580-cee9-11eb-9c83-22e1f0c39b18.jpg)

### Your Environment
OsmAnd Version:  OsmAnd~  4.0.0#32189m.apk 2021-06-16 (also since at least 2021-06-07)

Android version: 10
Device model: Samsung Galaxy Tab S5e SM-T720, Samsung Galaxy S7 SM-G930F

**Maps used (online or offline):**   
not relevant

**Comment by vshcherb** [comment]
That's a bug will be fixed soon!
