### ISSUE TITLE
Persian voice guidance does not work

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#11948]
### Description
When you configure Persian voice and start navigation, the application announces all information on the previously selected language (English or any other language).

### How to reproduce?
Select any profile->Configure Persian voice guidance->Start navigation

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: Android 9
Device model: Experience XZ 1

**Maps used (online or offline):**   offline
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by vshcherb** [comment]
Persian is not supported by Google TTS

**Comment by sonora** [comment]
You havo to go to your Android (not OsmAnd) device settings, find the TTS section (usually under Language and input), and see if you can set Persian there. Once you do, selecting Persian will also work in OsmAnd.

If the TTS engines which come with your device do all not support Persian, you can research on the Play store and install one which does.
