### ISSUE TITLE
Delete spaces in tags

### ISSUE THREAD

**Issue by gtrus21** [osmandapp/OsmAnd#11949]
Please implement the removal of spaces at the beginning and end of the input tags when creating and editing POI.  For example, I would enter __amenity_=cafe____, and when submitting it would be replaced with amenity=cafe

**Comment by gtrus21** [comment]
UPD: Here I ask you to replace all capital letters in the keys with lowercase ones.

Amenity -> amenity. 

Values not change

**Comment by scaidermern** [comment]
Related to #11662?

**Comment by gtrus21** [comment]
No. There are ideas about the missing tags.  I'm talking about clearing hand-written tags from extra spaces.

**Comment by vshcherb** [comment]
Yes, exactly of #11662 that's what we're going to do
