### ISSUE TITLE
Weblate in rare ocasions not using the last translation

### ISSUE THREAD

**Issue by laralem** [osmandapp/OsmAnd#11940]
It's the second time I see this, so it's a bit rare. The last translation it's not used in weblate. See for example the following translation:
https://hosted.weblate.org/translate/osmand/main/pt_BR/?checksum=fda9d0a0dcf91948
Please don't edit that translation so anyone can see what happened. I will fix it later.
The last translation by eduardoaddad 7 month ago is ignored like never existed and weblate shows the translation made by the same user 2 years ago.

It's a weblate issue or I'm missing something? Should be reported there?

**Comment by vshcherb** [comment]
You can see when its merged here - https://github.com/osmandapp/OsmAnd/commits/master. If it's not merged you can let us know as a comment on this issue and we will double check
