### ISSUE TITLE
Better support for premade routes through GPX files in route planner/plan a route features.

### ISSUE THREAD

**Issue by adegans** [osmandapp/OsmAnd#11945]
# 🚀 feature request

### Description

When making a route in osmand (iOS) i select where to go and it makes a route in between and that's mostly fine. But is super tedious when the route is longer or has many waypoints, especially if the route is several hundred KM long and has 8+ waypoints.

To make that easier I make routes on my computer with an app "Road Trip Planner" (macOS) which creates GPX files with waypoints, track segments and has an option for POI.

### Describe the solution you'd like

Osmand has a "Plan route" option which can load and save to GPX files, but NO WAY to load existing GPX waypoints as navigation waypoints. Making loading a premade route very very very very tedious and frustrating and basically it doesn't work in it's current state.

The easiest way (I think) is to add an option to the "follow track" option, that if Osmand detects waypoints (Not POI) it'll ask (or have a switch) to use those for a proper route, use the track for the calculated route (somehow) and then use that with the plan a route feature. That would give everyone decent turn-by-turn navigation.
I think Osmand is smart enough to test tracks or segments for a viable route and skip half the calculations (making it fast too).

The actions for the user then could be as easy as; Press Navigation button -> Options -> Follow track -> select GPX file -> Enable switch to use waypoints and track for turn-by-turn navigation (where it shows "pass along whole route") -> press done -> press start. And off the user goes.

### Describe alternatives you've considered

Currently I'm simply following the track, (using the "Follow track" option) but then I don't get turn-by-turn navigation, just osmand dumbly following the thick ugly red line on screen. Which as a basic feature works fine. But turn instructions and road names are not available - Which is what I want solved with this request.

Alternatively I tried importing a GPX with JUST the waypoints and have osmand calculate the in-between routes. But that doesn't work. A 293km route gets 400+km because it keeps looping me around roundabouts and go up and down sidestreets on pretty much every turn while I should be going straight. Or it messes up the waypoint order and sends me all over the place on crossings for no reason. Plus it takes 15+ minutes to calculate... So that's useless in it's current form. However, fixing the routing issue on that end would fix the above request as well, but in a different way...

To test compatibility I've converted the GPX I make/get from the desktop app to a bunch of different formats (no track, convert waypoints to route points, add a track AND route points and a few more combinations) to try and match a route made on osmand. But nothing seems to work as expected. It all comes crashing down when the GPX is ready to go and Osmand doesn't load the waypoints for the route planner and has no easy way to load all waypoints, let alone has a clear understanding of route pins/waypoints and POI pins. Or I have to add waypoints myself over and over again (sometimes they show up as mapmarkers (?) too) or the route calculation goes in illogical and useless ways.

If it matters, I'm using iOS Osmand with the whole country downloaded and I'm currently in Mexico.

Thanks for your consideration!

**Comment by vshcherb** [comment]
If I understood correctly, you have GPX file with waypoints but you want to navigate between them. Indeed the easiest way is to run Plan Route with existing GPX displayed and put points one by one in order you want to visit them.

Actually <rte> - points to navigate through and <wpt> points to be displayed on the map (GPX) and there is no way to easy switch between them.

**Comment by adegans** [comment]
Right, on my laptop I make a route - Bunch of waypoints and POI and generate a track for that.
What I'd like to be able to do is use the file a bit more smart/advanced and have Osmand calculate the route based on the supplied track/waypoints.

Importing works fine, but then planning the route is tedious in Osmand. An "add all waypoints to route" button at the very least would improve this alot.
But... Once the waypoints are in, the route calculation between them is wonky for some reason - Sending me over crossings and sidestreets repeatedly sometimes tripling the route distance (300km turns into 900+km) which makes the calculated route useless. If I see it again I'll try to make a screenshot of it.
Having Osmand interpret the track of the GPX as a proper route would be even better - That takes (mostly) away the calculations - It just has to figure out the track and turn it into a route and because it then is a real route we get correct turn by turn navigation with street names and everything.

I think Osmand is smart enough to interpret tracks as routes like this, somehow, but it's just lacking the function/code.

Currently, as you know, importing a GPX with track has Osmand dumbly follow the line and isn't aware of what street you're in. So no street names show up with the direction arrows. While this works fine, it's a bit basic.

I think adding the above features/functions would give Osmand an important edge to compete with Garmin and Tomtom and more importantly make navigation infinitely more easy/better than other mobile apps.

**Comment by vshcherb** [comment]
Hm... OsmAnd is smart enough to interpret tracks with  <rtept> and build routes between these points, you can modify this track using Plan route feature. If you have track with <wpt> they are considered to display only points to pass by.
```
<route>
<rtept>...
<rtept>
</route>
```
