### ISSUE TITLE
Different routes depending on start coordinates

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#1195]
https://code.google.com/p/osmand/issues/detail?id=2580

Please have a look at the attached screen shots. Target is always Lat 47.9840319, Long 7.8041098. With some starting points, OsmAnd is routing through service roads. (See the bottom-left parts of the routes in the attached screen shots.)

http://www.openstreetmap.org/way/178721831
http://www.openstreetmap.org/way/178721843

Map is
Germany_baden-wuerttemberg_europe.obf

Same issue with OsmAnd 1.9.5 and nightly build 200#5975D.

Other users seem to experience similar problems:
https://groups.google.com/forum/#!topic/osmand/eyOks-Fmzs0

**Comment by xmd5a2** [comment]
Not reproducible anymore
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot%20from%202016-04-29%2021%3A25%3A26.png

**Comment by Norbert80** [comment]
A regression in recent OsmAnd builds cause OsmAnd to always calculate thje bad route now. This is filed in #3334.
