### ISSUE TITLE
OpenPlaceReviews Login doesn't transfer to app

### ISSUE THREAD

**Issue by SlidingHorn** [osmandapp/OsmAnd#11951]
### Description
I'm currently using OsmAnd~ 3.9.10, and after enabling the "OpenPlaceReviews" plugin and going to its settings to log in, it opens (what appears to be an in-app version of) Firefox to a login page giving me the options of registering via Google, OSM, GitHub, etc - however, I'm already logged in on that page. Once I select OSM and "Authorize access to [my] account" it goes back to the plugin settings where it appears as though I'm still not logged in (the only "setting" listed is "Login to OpenPlaceReviews")

There does not appear to be anything under "actions" for POIs for me to leave a review, etc.

### How to reproduce?
Described above, but if more information is needed, let me know.

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: Pie (Android 9)
Device model: Samsung Galaxy S8

**Maps used (online or offline):**   
This issue doesn't seem to change whether I use online or offline maps.

**Comment by SlidingHorn** [comment]
Just as an update, I tried again today, and it actually took the login, but after further researching OPR, it looks like it's just in Beta and is little more than a "link to TripAdvisor" at this point.

I'm going to close this, as apparently the login not transfering over was probably just a lag in the OPR account creation.

**Comment by vshcherb** [comment]
We had a fix meanwhile in Android app

**Comment by EvanCarroll** [comment]
I'm still having this issue.
