### ISSUE TITLE
Add Default Profile - Last used

### ISSUE THREAD

**Issue by GuentherGredy** [osmandapp/OsmAnd#11968]
# 🚀 feature request

### Description

You've selected profile "hiking", start hiking the first route or track of a multi route or track tour and you reach the target. The profile falls back to "car". This is not convenient for subsequent route or track handling.

### Describe the solution you'd like

From my point of view a profile should change only on user action.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by vshcherb** [comment]
It's not clear why it defaults to 'car', I think it should fallback to 'browse map' once navigation finished. Please share the track and more detailed instruction.

**Comment by GuentherGredy** [comment]
Well, please follow the use cases:
1. Start OsmAnd, it defaults to profile car (button with car in upper left corner), press the button (Picture_01)
2. Select profile hike by pressing marked button (Picture_02)
3. Result is profile hike (Picture_03)
3. Press button navigation (Picture_03)
4. Navigation dialog invoked with profile hike (Picture_04)
4. Terminate navigation dialog with button Abbrechen (Picture_04)
5. Result (Picture_01)

This is the easiest scenario where it happens, there are others. I do not know whether leaving the dialog for navigation is significant.
![Picture_01](https://user-images.githubusercontent.com/85982948/123433932-40138d80-d5cc-11eb-9895-133341b0060d.png)
![Picture_02](https://user-images.githubusercontent.com/85982948/123433946-430e7e00-d5cc-11eb-8769-808d33ca5139.png)
![Picture_03](https://user-images.githubusercontent.com/85982948/123433953-46096e80-d5cc-11eb-87bc-a60474436c60.png)
![Picture_04](https://user-images.githubusercontent.com/85982948/123433971-4b66b900-d5cc-11eb-8d53-ce5247fd4909.png)

**Comment by vshcherb** [comment]
Yes, it is a known behavior. We don't have the option yet "last used" for default profile. So it will always revert to the "default" profile (which is selected in Global settings)

**Comment by vshcherb** [comment]
Last Used works now as expected
