### ISSUE TITLE
[FR] Make slopes display ( and legend ) modifiable

### ISSUE THREAD

**Issue by letypequividelespoubelles** [osmandapp/OsmAnd#11975]
# 🚀 feature request

### Description

Slopes overlay is very important while preparing winter outdoor activities, especially touring ski. It can help to avoid avalanche risk, and therefore OSMAnd helps to save life. The slopes overlay should be a little bit more usefull if it could focus on the slope between 30 and 50.

### Describe the solution you'd like

What would be perfect is to be able to change the min and max of the displayed slider ( I think the best would be two sliders on the legend of the slopes layer, one for the min, one for the max). Before the min slider, it should be totally white on the map (and therefore legend), and after the max slider, totally purple (the color of the max slopes) both on map and legend. I give hereafter bad paint attempt to illustrate. So all the color panel instead being from 0° to 60° would be from min-slider to max-slider, and therefore have a much better vision of the slopes on the wanted slope's range.

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/54240434/122908861-e3f30400-d354-11eb-9b14-086270403153.jpg"  width="300" height="auto"/> </td>
  </tr>
</table>

### Describe alternatives you've considered

It has already been discussed on #10989 and #6636, but I guess the solution I propose will be enough to close these two other issues.

**Comment by vascotenner** [comment]
This is related to: https://github.com/osmandapp/OsmAnd/issues/9283. Although the solution proposed in this topic will improve the situation, it will not suffice: the different slope classes are not suffcient distinctable.

**Comment by letypequividelespoubelles** [comment]
>different slope classes are not suffcient distinctable

I think that if you put the slider at 30) and 45°, you will have enough precision. 
And to have numeric data, it might be good to add 
- a slope widget that display the slope of the center of the map (as the elevation widget)
- a slope widget that display the slope of the current position
- add an option that enables, when tapping on a position on the map, to display its ele and slope (add information in distance by tap) ?

**Comment by vascotenner** [comment]
My use case is that I use this in the field, also on sunny days where the screen of my phone is hardly visible. In that case, the information should be visually very easy to process, and contain only the information that I need (like with normal maps).

**Comment by XandrexOSM** [comment]
the slider is a very good idea. I use OsmAnd for commute cycling and would like to put the bracket between 2% and 15% because I live in an urban area.

**Comment by miramikes** [comment]
> My use case is that I use this in the field, also on sunny days where the screen of my phone is hardly visible. In that case, the information should be visually very easy to process, and contain only the information that I need (like with normal maps).

For me would be best to switch on such "avalanche layer" by now introduced "quick action button" than I can quickly switch between normal map and checking dangerous slopes around me.

**Comment by letypequividelespoubelles** [comment]
smtg similar seems implemented in the PR linked to this issue : #6636

**Comment by vshcherb** [comment]
Yes work in progress.
