### ISSUE TITLE
Different routing times

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#1197]
https://code.google.com/p/osmand/issues/detail?id=2514
From email:
For me it would make sense if the algorithm would choose to direct me from the secondary road to the tertiary road all the way around and not take the shortcut. But, have a look at the two new screen shots. I did choose v1.9 routing and fastest in the settings. In picture 1 Osmand tells me to use the red trunk road which is the best option, I think. In the second picture I moved the destination a bit further on, into the living area but still I placed it next the yellow tertiary road. The result is very different in a way that does not make sense for me. I think that I should get the 'same' result no matter where I place the destination inside this living area, because I will always need to pass this point http://www.openstreetmap.org/?mlat=53.05034&mlon=8.84878#map=18/53.05034/8.84878. Even if the 'fastest' option would choose not to take the shortcut it should still use the trunk road. 

Observation:
incosistent routing time with 
planRoadDirection=-1 
<test regions="" description="" best_percent="" vehicle="car" 
    start_lat="53.05263443515128" start_lon="8.804678678512602" target_lat="53.05043369160768" target_lon="8.852818965911894" loadedTiles = "704" visitedSegments = "1639" complete_distance = "3619.8352" complete_time = "656.73785" routing_time = "443.19177"  >
</test>

planRoadDirection=1
<test regions="" description="" best_percent="" vehicle="car" 
    start_lat="53.05263443515128" start_lon="8.804678678512602" target_lat="53.05043369160768" target_lon="8.852818965911894" loadedTiles = "713" visitedSegments = "967" complete_distance = "3619.8352" complete_time = "656.73785" routing_time = "543.19183"  >
</test>

Roads are exactly the same but routing time is different

**Comment by xmd5a2** [comment]
Cant' figure out what's wrong
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot%20from%202016-04-29%2021%3A49%3A25.png

**Comment by vshcherb** [comment]
planRouteDirection=1, bicycle. 2 different routes depends on small change of the target point (2nd route is incorrect based on routing_time is much bigger)
    start_lat="53.04848920489773" start_lon="8.819661498069792" target_lat="53.050307931439164" target_lon="8.827815413475065" loadedTiles = "44" visitedSegments = "210" complete_distance = "1038.6176" complete_time = "283.97592" routing_time = "195.53773"  >

        start_lat="53.04848920489773" start_lon="8.819661498069792" target_lat="53.050340177671195" target_lon="8.827649116516142" loadedTiles = "43" visitedSegments = "159" complete_distance = "800.8934" complete_time = "273.08875" routing_time = "131.04558"  >

**Comment by vshcherb** [comment]
Bug is related to heuristicCoefficient="1.5". With heuristicCoefficient="1.5" algorithm could not work 100% correct, without it gives different result
