### ISSUE TITLE
Option to display surveillance cameras on the map

### ISSUE THREAD

**Issue by raearispa** [osmandapp/OsmAnd#11976]
# 🚀 feature request

### Description

I noticed OsmAnd doesn't currently give people the option to display surveillance camera info on the map. As public perception around biometric surveillance in public spaces (and surveillance in general) is finally starting to change, I think it would make a lot of sense for you to make this information (which the data from OSM already includes) available inside the app.

**Comment by xmd5a2** [comment]
Already fixed https://github.com/osmandapp/OsmAnd/issues/11883

**Comment by raearispa** [comment]
> 
> 
> Already fixed #11883

I can't seem to find the option. Is this not available on the OsmAnd app for iOS?
If it's indeed not yet available, do you have a time-frame as to when it will?
