### ISSUE TITLE
Dialog "Karte konfigurieren" | "Tracks"

### ISSUE THREAD

**Issue by GuentherGredy** [osmandapp/OsmAnd#11974]
# 🚀 feature request

### Description

If there are many entries in the list, the operating elements "ABBRECHEN" and "WEITERE HINZUFÜGEN" disappear and can only be reached by scrolling the lower part of the dialog. This is not obvious to a user.

### Describe the solution you'd like

 If you have a solution in mind, please describe it.

Why not arranging the operating elements horizontally and keeping the lower part of the dialog fixed?

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by vshcherb** [comment]
![telegram-cloud-photo-size-2-5382317698563814554-y](https://user-images.githubusercontent.com/1042025/123423052-57984980-d5bf-11eb-92d0-1edbf0239696.jpg)

**Comment by sonora** [comment]
Overlaps with this plan: https://github.com/osmandapp/OsmAnd/issues/10704

**Comment by akkana** [comment]
Could I make a request? I really like the "My places" view for the way it can expand and collapse folders, but I like the checkboxes in "Configure map / Tracks" (or for the currently visible tracks at the top of "My places") for the multiple checkboxes, where you can select multiple tracks to be visible on the map. It would be wonderful if there were a view that offered both an expandable folder hierarchy and checkboxes that let you choose multiple folders at once. Thanks for considering this request!

**Comment by GuentherGredy** [comment]
I fully agree to akkana's comment above. This combination would be very convenient. Thanks.

**Comment by vshcherb** [comment]
New design is in nightly.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14208mqta, Released: 2023-02-28
Design in the new version solves this issue

**Comment by GuentherGredy** [comment]
Dear OSMAND developers, I just installed the 4.4.7 version and I'm happy to see the new tracks-dialog. It opens up perfect overview and flexibility to the user. A great implementation! Thank you very much! BR Guenther
