### ISSUE TITLE
Menu "Karte konfigurieren" | "Tracks"- Hierarchical view on folders and files

### ISSUE THREAD

**Issue by GuentherGredy** [osmandapp/OsmAnd#11983]
# 🚀 feature request

### Description

If you want to import a bunch of GPS data (way points, tracks routes) for a longer tour, it is helpful to structure them as in WINDOWS explorer as a tree of folders and files. I do this as shown in picture "Windows_Structure.png". Connecting my handy to USB port, I just copy this structure to the OSMAND folder "import".

Invoking menu "Karte konfigurieren | "Tracks" I can see a flat list of GPX files together with their folders (pls. refer to picture "OsmAnd_Tracks").

### Describe the solution you'd like

In order to select and display single elements while hiking the tour it would be convenient to have an hierarchical folder and file structure too.

![Windows_Structure](https://user-images.githubusercontent.com/85982948/123073353-9fc83800-d416-11eb-890b-fa301e4aea82.PNG)

![OsmAnd_Tracks](https://user-images.githubusercontent.com/85982948/123073386-a787dc80-d416-11eb-8d5c-00aa6e17fc29.png)

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by GuentherGredy** [comment]
I understand "nice to have", but there is another issue in this context, which can be easily solved as I think. The character "_" (underscore) is missing. Would be great to see it.

**Comment by sonora** [comment]
See #8685 ? Could be related to the fact that we still maintain 2 different tracks screens and many users only find the less powerful one without folder management?

**Comment by GuentherGredy** [comment]
I fully agree to this comment. From my experience OsmAnd anyway has a relatively flat learning curve caused by this incredibly high and welcome feature richness, and it would be very helpful for the user to focus on what is presented under "My Places | Tracks" while retiring the 2nd dialog. From my experience as a software developer and project manager (now retired) you will get rid of many support and maintenance issues on one side, and on the other side you could spend the released resources to enhance the one remaining dialog (re-design, true tree visualization, alpha sorting, date sorting ...). With this in mind I personally would appreciate changing the issue label "nice to have" and assign it a concrete version. Thank you very much for your attention.

**Comment by sonora** [comment]
Well stated.

It's a general theme that in several cases we develop, support, maintain, research issues, and finally bug-fix too many different screens and menu options leading to ultimately similar (or even the same) functionality.

Reducing that by throwing out overlap and redundancy could free up resources and thus facilitate achieving the same functionality but in a better, leaner,and more maintainable fashion: via de-diversifying the UX (fewer ways to do something make support easier), improving the UI (steeper learning curve for users), and less code (easier to maintain).

**Comment by vshcherb** [comment]
It's planned for 4.1 though it will require a lot of work, I would say it's less time to maintain 2 dialogs for 3-4 years, then finish 2 dialogs consolidations. Selecting tracks is a complex task, 2nd after creating Track menu itself.

Merged to https://github.com/osmandapp/OsmAnd/issues/10704

**Comment by sonora** [comment]
Yeah, I know, Victor, I've looked at the code ....

I guess the lessons learned here could be we try to avoid  such duplicate code trees from the beginning or catch things as early as possible, but that's easier said then done.

It seems that these kind of developments always creep up when we do widespread new UI development, like lately all the functionality around the different ways to graphically analyze tracks/routes may contain similar occurrences ("Analyze on map", etc.)

**Comment by vshcherb** [comment]
- graphically analyze tracks/routes
it was always on track screen which is now finally deleted. Also this track menu is getting combined now with travel. so in the end last 2 years number of screens slowly decreasing (except setting screen but that's totally another story.... ) - we even deprecated dashboard but can't delete it now

**Comment by sonora** [comment]
Yes, I guess we're about on the right track.

Regarding Settings we have #9047 with some suggestions from me how to consolidate, once we turn to that.

**Comment by Vanooname** [comment]
Hello! Will the tree-like (Hierarchical) structure of the tracks be? I have more than 150 tracks, one level of folders is not enough for easy navigation between them.

**Comment by sonora** [comment]
As I said: It's already implemented, just use screen Menu/MyPlaces/Tracks.

Put your tracks in different sub-folders under the osmand track folder, and you will see that structure reflected on that screen.

What is still outstanding is the consolidation of that screen with our other Tracks screen under Menu/Configure map/Tracks, plus streamlining the folder view a bit, that epic is still in a future milestone.

**Comment by GuentherGredy** [comment]
Hello Hardy,

thanks for commenting the issue.

I tested the functionality and for me it is o.k. One can see folders and subfolders. Perhaps Vanooname expected a true WINDOWS Explorer type of view.

Yet there is one true disadvantage when deleting items. Only the GPX files are deleted, but the folders are kept, yet not visible in OsmAnd any more. One thinks everything is deleted, but ... So one has to connect the handy to a Personal Computer and delete
the folders separately. This is very inconvenient.

Another issue concerning this dialogue I already posted a long time ago concerns the buttons at the bottom of the dialogue. This part of the dialogue is scrollable and very inconvenient to handle.

What about three horizontally arranged buttons "OK", "Cancel", "Add more..." and no scrolling.

Thanks for your attention.

BR

Guenther

**Comment by sonora** [comment]
@GuentherGredy Just very briefly:
- The folder view is part of the new epic, I expect that handling will become a lot easier by e.g. opening folders on new screens or similar, as file manager apps in Android handle it.
- You can delete track folders in OsmAnd already in the current setup by on the `Menu/MyPlaces/Tracks` screen tapping the trashcan icon at the bottom of the screen, which will produce checkboxes. Selecting the checkbox **to the left the folder name name** (vs. to the left of a track name) will select the folder itself (plus all contained files, if any) You can then execute by hitting the confirmation button (top right), which will also delete the folder itself.
(Again also here, I think the functionality should improve in the new epic towards what is more standard, e.g. producing the selection boxes by long-tapping on an item.)

**Comment by GuentherGredy** [comment]
Thanks, Hardy, for the explanation!

Will be really great having a functionality as in file manager apps.

Concerning track folder deletion it does not work at my setup.
I followed the steps you documented and as a result the folder
disappeared in OsmAnd dialogue but not in a file manager used
under Android. To give you a clearer picture, if you want, I could
document the procedure.

Anyway I am very excited to see the result of your effort in one of
the next OsmAnd versions!

Thanks a lot.

BR

Guenther



Dipl. Ing. Guenther Gredy | Eggbergstr. 46 | 79618 Rheinfelden
Tel.: +49 (0)7623 47353 | Mobile: +49 (0)1523 2754248
Email: ***@***.***




Gesendet mit der Telekom Mail App



--- Original-Nachricht ---
Von: Hardy
Betreff: Re: [osmandapp/OsmAnd] Menu "Karte konfigurieren" | "Tracks"- 
Hierarchical view on folders and files (#11983)
Datum: 17. November 2022, 13:53
An: osmandapp/OsmAnd
Cc: GuentherGredy, Mention


@GuentherGredy Just very briefly:

The folder view is part of the new epic, I expect that handling will 
become a lot easier by e.g. opening folders on new screens or similar, 
as file manager apps in Android handle it.

You can delete track folders in OsmAnd already in the current setup by 
on the Menu/MyPlaces/Tracks screen tapping the trashcan icon at the 
bottom of the screen, which will produce checkboxes. Selecting the 
checkbox to the left the folder name name (vs. to the left of a track 
name) will select the folder itself (plus all contained files, if any) 
You can then execute by hitting the confirmation button (top right), 
which will also delete the folder itself.
(Again also here, I think the functionality should improve in the new 
epic towards what is more standard, e.g. producing the selection boxes 
by long-tapping on an item.)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.￼Message ID: 
***@***.***>

[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", 
"potentialAction": { ***@***.***": "ViewAction", "target": 
"https://github.com/osmandapp/OsmAnd/issues/11983#issuecomment-1318593161", 
"url": 
"https://github.com/osmandapp/OsmAnd/issues/11983#issuecomment-1318593161", 
"name": "View Issue" }, "description": "View this Issue on GitHub", 
"publisher": { ***@***.***": "Organization", "name": "GitHub", "url": 
"https://github.com" } } ]

**Comment by sonora** [comment]
Strange, I used the Samsung MyFiles app to manually create a subfolder of (osmand)/tracks, then successfully deleted it again in OsmAnd as outlined above. Chances are if you copied your track-subfolder from a PC, maybe it contains other files as well (like perhaps a _Readme.pdf_ or even a hidden _.nomedia_ file), and then the Android call to delete the folder fails silently because it is not empty. Or the folder is has an inherited 'write-protected' flag...   Maybe if you experiment you find a way... ;)

**Comment by Vanooname** [comment]
> As I said: It's already implemented, just use screen Menu/MyPlaces/Tracks.
> 
> Put your tracks in different sub-folders under the osmand track folder, and you will see that structure reflected on that screen.
> 
> What is still outstanding is the consolidation of that screen with our other Tracks screen under Menu/Configure map/Tracks, plus streamlining the folder view a bit, that epic is still in a future milestone.

I'm talking about something else. A full-fledged hierarchy is interesting. For example, tabs (nesting) of the second or third level.

**Comment by sonora** [comment]
See https://github.com/osmandapp/OsmAnd-Issues/issues/910.
