### ISSUE TITLE
Suggestion: Re-introduce Nature Areas marked with characters

### ISSUE THREAD

**Issue by tradavyvy** [osmandapp/OsmAnd#11982]
# 🚀 feature request

When opting to show environmental zones on the map, there is a (green) boundary shown around the zone (BEZ - boundary environmental zones).
It would be clearer if the area inside this zone would be shaded in a translucent (green?) color.
Specialy when planning a route/trip you might not zoom in on every detail and a shaded area would stand out better.

See above

 If you have a solution in mind, please describe it.

See above

 Have you considered any alternative solutions or workarounds?

The current boundary only solution will do.
But clearer maps are always better.

Keep up the good work.
And see our comments just as an effort to give this -almost but not quite entirely perfect- app just one more litlle nudge.
Thanks

**Comment by sonora** [comment]
Yes, but on the other hand these zones can be extensive. If we shade big areas (env zones, National Forests, National Parks, etc.), moving inside these areas means that you always see an overlay tint on the map all the time, which in practice can be quite irritating, really ...

**Comment by tradavyvy** [comment]
I see your point.
But the boundry line (BEZ) is optional in the show on map menu / details. So I assumed the shading would be (if need be seperately) optional too.

Your comment about national parks / national forrests etc.. made me think that OPTIONALY shading them would make me happy.

If that is not feasable for instance because there are to manny (overlapping) kinds of possible interesting areas there could be a 'button' to press that lists all the areas the current possition is inside of. A possible use I see for shading/button is when traveling in the usa dispersed camping is allowed in national forrests but not in national parks.

**Comment by snouup** [comment]
Check the rendering of environmental zones on osm dot org webclient. It's green stripes. Similar to restricted zones rendering in osmand.
Personally i'm okay with either shade or stripes or some other way to render area. Showing boundaries only is not sufficient. It's unreadable when zone boundaries touch each other, or when the boundaries overlap with hiking routes. Besides, in a large zone it's hard to tell which side of the boundary you're on.

**Comment by snouup** [comment]
> If we shade big areas (env zones, National Forests, National Parks, etc.), moving inside these areas means that you always see an overlay tint on the map all the time, which in practice can be quite irritating, really ...

Well, irritating or not - you're supposed to be _aware_ of being inside a protected area with special rules to adhere to. Local signage isn't always conclusive. The map should make it obvious without a second look.

Good news is protected areas are mostly devoid of POIs and human made features. The map style won't be obscuring much.

**Comment by sonora** [comment]
Let md please prove you wrong with this example: https://www.openstreetmap.org/relation/3274482

Hundreds of square miles with thousands of people living in its boundaries. Man made features include entire towns. Surely you would not want areas like that to be entirely tinted or striped.

**Comment by tradavyvy** [comment]
This is a no win discussion. There will always be competition between the info that wants to be on a map. For me it is clear that I would not like osmand to be 'poluted' with shaded areas of high yearly rainfall. But I would like it to be visible when I am within an environmental zone (high fines in europe for me) or in a national forest (free dispersed camping in usa). On average I think the osmand team does a great job desiding, this is just to tell you the request of some of your happy users. And when in doubt, make it optional.
Davy

**Comment by sonora** [comment]
Yes Dave, I agree, well stated. Things like this are candidates for user configuration.

The drawback is we overwhelm our users already with configuration options, and while that pleases some traget audience, it turns off others. 

But if there is a strong feeling here this item should be yet another configuration option, I would not object.

**Comment by tradavyvy** [comment]
I might slightly disagree with sonora about overwhelming with options. Afterall options are 'optional' You can choose to go with the verry workable defaults the programers recommend. Or you invest some time to customise the programme completely to your liking. If nessesary there could be a 'menu' for basic settings and a (deeper) settings page for those who are not easily overwhelmed. Because in the end 'It is the information that makes the map!'
Davy

**Comment by snouup** [comment]
> Let me please prove you wrong with this example: https://www.openstreetmap.org/relation/3274482

> Hundreds of square miles with thousands of people living in its boundaries. Man made features include entire towns. Surely you would not want areas like that to be entirely tinted or striped.

That's crazy! Colour me surprised !

It seems there are different types of protected areas with varying levels of strictness.

https://wiki.openstreetmap.org/wiki/Key:protect%20class?uselang=en

Anything below class 5 would likely start to have usage restrictions (like dispersed camping laws mentioned by OP) applied to it. So the example area you point out would not need to be striped / shaded, besides level 5 is meant to be larger area (landscape).

I'm trying to find the map I saw with stripes, unfortunately I can't find it anymore. Maybe osm made a change or maybe I saw someone's 3rd party theme back then. I can't remember.

**Comment by snouup** [comment]
In any case, in osm vs osmand there is a stark difference in the drawing of names of protected areas.

Osm shows a large title spanning almost the entire area. Osmand shows only a small title that takes a lot of effort to find. Sometimes the title won't appear at all unless you zoom to a specific level on a very specific spot. Without the titles, it is more difficult to make sense of the outlines being drawn.

For mountain ranges, osmand _does_ show large titles. So the capability is there.

**Comment by snouup** [comment]
And another difference, osm.org theme lets you see which side the boundary is facing  - the inner side is drawn wider, outer side is drawn thin and bold. Clear and easy.

**Comment by snouup** [comment]
I may just be stating the obvious here - but there may be another way to satisfy OP's request without cluttering the app with more options at all.

1. Render areas which are selected (tapped on) or highlighted (from poi overlay) with a tint - less controversial I suppose?
2. Allow protection classes to be distinguished in the search - partly possibly already. Natural reserve is there as a distinct poi type, others seem missing. Difficulty comes from local classification in each country. May be easier to use an integer filter instead of distinct poi types with hard to translate and possibly very long names.
3. User may create a custom filter and poi overlay for protection classes of their choosing. Same approach may be applied to any other area tag osm may support like fishing forbidden, etc

**Comment by sonora** [comment]
Regarding (1): That's already implemented, I use exactly that to find dispersed camping, see below. But I think we may have to work on the zoom level where tapping such areas is active, I think you have to zoom fairly far out...
![Screenshot_20210724-233313_OsmAnd~](https://user-images.githubusercontent.com/845735/126881589-14024743-75eb-4dff-8ea7-dbb5195d2dc6.jpg)

**Comment by tradavyvy** [comment]
Going back to my original motivation, avoiding fines in environmental zones, perhaps slightly beside the discussion here.
But as an alternative or extra option, would it be possible to get a warning when osmand is preparing a route that crosses an environmental zone, and/or optionaly avoid these zones all together. Like with the avoid private roads or avoid ferries options.

**Comment by pawelostr** [comment]
I'd argue that just making the displayed green line a bit wider would help a lot, here's OSMAnd and Mapy.cz (also known as Windy Maps) of roughly the same area (national park and inside it a strict reserve) side by side ![image](https://user-images.githubusercontent.com/26488603/129443980-81266251-eb2b-4703-94bb-aa40f4ef44e9.png)

![image](https://user-images.githubusercontent.com/26488603/129443988-8bf5d4df-7255-4507-a312-4388c1fb47d2.png)

**Comment by tradavyvy** [comment]
I would say they have visualy solved the enviromental  zones quite wel now.
Now only a warning when navigating to or through an enviromental zone.
Thanks so far
![Uploading Screenshot_20210814-140712_OsmAnd+.jpg…]()

**Comment by tradavyvy** [comment]
![Screenshot_20210814-140712_OsmAnd+](https://user-images.githubusercontent.com/71978409/131488442-24548906-f94b-49c6-97fc-551a51037994.jpg)

**Comment by tradavyvy** [comment]
Enviromentalzone striping in Lille (France)

**Comment by Hades1503** [comment]
Hello,

a member of the German OSM forum gave the code lines to display an opaque layer and the initials NR for the nature reserve. the opaque layer can be deactivated in "detail"

https://forum.openstreetmap.org/viewtopic.php?pid=831545#p831545

for my part I was inspired by his work and I added what was missing in the topo rendering of osmand for me. the paths are bigger, the visibility of the path is taken into account and the coloring of the difficulty of the path (as on Mapnik).
this rendering is added to the others, if it does not suit you, use the style of card that you prefer.

https://github.com/osmandapp/OsmAnd-iOS/issues/1381#issuecomment-912989897

**Comment by sonora** [comment]
As I said, I am never fond of any overall color (green) tinting because it alters and obscures the appearance of all other colors present in the map and identifying their meaning, last not least in this case e.g. all vegatation shaders.

I just notice I had done all this ressarch some 10 years ago, see here https://github.com/osmandapp/OsmAnd/search?q=nr&type=commits, and it result simply using a **transparent** NR shader which sparsely displayed these two letters in an unobtrusive transparent green, enough to reliably identify you are in such an area, but without altering the overall map experience of color features you may be used to in your renderer elsewhere.

I notice that somewhere along the way we seem to have removed using that 'NR'  feature from our default renderer which also had the same effect in Touring view and other dependent renderers. And I now realize this is likely the root cause of users opening this issue.

@xmd5a2 Leonid, would you know off hand when we dropped using tbe NR shader and what was behind that decision? Would re-introducing it be an option, even perhaps just as a 'Detail' option?

**Comment by Hades1503** [comment]
I made a mistake, it is not in "detail" but in "hide".

when we hide the nature reserve on my rendering, the green color disappears, only the NR mentions remain.

moreover the mention NR is too small and dense in this case. if you ever put the NRs back in the renderings provided by osmand, you can enlarge these two letters and space them more apart?

![image](https://user-images.githubusercontent.com/79785663/132125682-e8626404-0d37-47c9-a7c8-85ae8cb8c569.png)

![image](https://user-images.githubusercontent.com/79785663/132125714-f5d319d8-eb2d-4fec-9389-5a2e8f622cf9.png)

**Comment by tradavyvy** [comment]
The letter option looks perfect, it even gives the posibillity to specify the kind of area
NR nature reserve
NP national park
NF national forrest
PL public lands (blm-land in usa)
RZ restricted zone (non military) etc...
This would of course only work if this info is available in osm.

I think the letters could easily be further appart than in the screenshot.

The renderer Hades talks about is not standard in OsmAnd I take it?

By the way, it is maybe a good idea to change the name of this toppic now the environmental zone problem is solved.

**Comment by xmd5a2** [comment]
> @xmd5a2 Leonid, would you know off hand when we dropped using tbe NR shader and what was behind that decision? Would re-introducing it be an option, even perhaps just as a 'Detail' option?

I don't remember exactly but someone asked to remove it because it was very obtrusive

**Comment by tradavyvy** [comment]
I think the bulk of this 'problem' is now nicely solved in the current interface. 
Natural areas and environmental zones are now (optionaly) rendered.
So o sugest someone on the development team closes it.

Thanks for thinking with me and solving yet another small imperfection in this great app.
