### ISSUE TITLE
Chukotka Slopes

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#11999]
Chukotka Slopes is more than 2 Gb.
Need to delete it, because OsmAnd crash during downloading this slopes file.

**Comment by anastasiia936** [comment]
Russia/Siberia/Kraï Krasnoïarsk/Evenkiysky Rayon - Slopes 
Canada/Nunavut/Nunavut - Slopes are also bigger than 2 Gb and the app could not download them.

**Comment by anastasiia936** [comment]
Canada Quebec Slope file is also larger than 2 GB and also could not be downloaded.
