### ISSUE TITLE
Long-tap on a track does no longer produce the point context card

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#11990]
I think this is a regression, not quite sure when we lost this: We used to be able to long-tap on the map, and if the point tapped was on (near) a displayed GPX track, we used to see the track-related data of that particular track (`<trk>`) point. (Use case is to e.g. find out when you were at what point of your recorded track.)

Now, long-tapping on/near a displayed GPX track seems to just open the track menu. I see no option to display the data for recorded track (`<trk>`) points (**not** talking about `<wpt>` waypoints here.). Or am I missing anything?

**Comment by vshcherb** [comment]
It's first of all changed to short tap (open object menu).
- Long tap opens always open menu without snapping to the object i.e. precise points
- Short tap menu was deleted to open consistently track menu to compensate that functionality i.e. details of the point. Small feature was introduced: now all pinpoint is attached to the location on the graph - so you could see distance / altitude / speed at that location

**Comment by sonora** [comment]
Ok, I understand how we handle long taps now, and I think that's ok for the sake of simplicity.

What do you mean to say about the 'Small feature' introduced for compensation? When I short tap on/near a track, I receive an orange pointer for a particular track point. But the corresponding card which opens contains solely the data for the track, with the single exception of the 'distance to the current position' shown as a blue number. Is there any way to view more data for that marked point?

Use case is that user tracked the gpx on a boat trip, and later wants to find out at what clock time exactly they were where. Other data like altitude etc. is of less concern to them.

**Comment by vshcherb** [comment]
Yes,  time I think is missing feature now. We could create a separate issue and think how to display combine. Simple solution (not that simple) to allow change graph axis Distance <-> Time. Also we can remember tab of track you opened before.
