### ISSUE TITLE
New NPE in GpxSelectionHelper

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#11995]
Latest nightly,, not sure how to reproduce:  [exception.log.txt](https://github.com/osmandapp/OsmAnd/files/6710912/exception.log.txt)

**Comment by sonora** [comment]
Here''s another one, just re-use the okd issue : [exception.log.txt](https://github.com/osmandapp/OsmAnd/files/6758728/exception.log.txt)

**Comment by cepprice** [comment]
@sonora Did this NPE happened on new (not not necessarily latest) nightly? You got the [same NPE ](https://github.com/osmandapp/OsmAnd/issues/11826)month ago, and I think it was fixed

**Comment by sonora** [comment]
@cepprice My build date was 03.07.2021 6:36:13, built from a copy of our master branch. I believe that the previously reported NPE was claimed to be fixed earlier than that (in https://github.com/osmandapp/OsmAnd/pull/12024 ?), that's why reported it here again.

**Comment by sonora** [comment]
Similar, but again different: 
[exception.log.txt](https://github.com/osmandapp/OsmAnd/files/6795182/exception.log.txt)
