### ISSUE TITLE
Help for Export

### ISSUE THREAD

**Issue by Bergkraxler** [osmandapp/OsmAnd#12009]
The page https://osmand.net/help-online does not have anything on the new function of "export". When I use export, it does not even tell me what file I have to use if I want to import (on a new smartphone or after reset of my phone) what I had exported.

I have also not found it on the google group.

Thanks if that can be added to the help page, and appreciation for what you are doing with Osmand.

**Comment by vshcherb** [comment]
Documentation is incomplete still and it will be added here - https://docs.osmand.net/en/main@latest/osmand/personal/import-export
