### ISSUE TITLE
Disable mapillary plugin by default

### ISSUE THREAD

**Issue by MPeti1** [osmandapp/OsmAnd#12008]
# 🚀 feature request

### Description

After mapillary's acquisition by facebook, I don't think it's good to support their service in this way.
I think it's ok to keep it as a plugin, but by having it enabled by default you encourage people to use and contribute to their service (because people will happily update outdated information in their area, even if they don't want to support facebook and it's subsidiaries but they don't know about the acquisition).

From reading #9402 I'm aware that there's few known alternatives to it, and I would like to clarify that even if there would be one, I don't think it would be necessary to completely remove support for mapillary, in case someone wants to use it, as it is already a big database

### Describe the solution you'd like

As a first step, I think it would be better if the mapillary plugin would be disabled by default, and later I think it would be even better if it would be moved out into it's own plugin-app, like how the parking position works now.
I think I have seen that a few years earlier it worked this way, but can't find the PR now.

### Additional suggestions

I write this here because I can see this to be controversial, as in is this really a good idea?
But I think it also would be good to somehow hint that mapillary is now a facebook subsidiary. I was thinking about either in the plugin's description, or as a popup when the user activates the mapillary plugin.
I think this is controversial because anti-facebook people would appreciate being warned, but some others might find themselves offended by it. At the same time, F-droid does a similar thing (warning about antifeatures in the app's description), and AFAIK they haven't had problems from it

**Comment by sonora** [comment]
Looks like https://github.com/osmandapp/OsmAnd/issues/11776 is still not implemented?

**Comment by vshcherb** [comment]
@sonora Nope, the task was completed but we didn't plan to implement plugin suggestions. So we decided to keep mapillary on for now until we have default street level imagery or plugin suggestions.

**Comment by MPeti1** [comment]
Thanks @cepprice and @Chumva!

**Comment by MPeti1** [comment]
I just reinstalled OsmAnd and it seems Mapillary is again enabled by default.
Deleted the app's data and checked again just to make sure, but after downloading the map on the onboarding menus, the Mapillary plugin is active in the Plugins menu.

Could you please reopen this issue, and take a look into it?

It seems the plugin's isEnabledByDefault() method hasn't been changed since commit baa1e83, so the problem should be somewhere other place. (or it was not a good idea from me to only check it on the master branch)

**Comment by Chumva** [comment]
Strange, it should be disabled by default. I checked on two different devices and Mapillary is disabled. Try to clear all app data (not only cache for deleting saved preferences) or reinstall.

**Comment by MPeti1** [comment]
I deleted the app data for OsmAnd in the system settings, reinstalling does not help either.
Just to be sure, I'm installing this app from F-droid: https://f-droid.org/packages/net.osmand.plus/

I'll make a screen recording to upload here

**Comment by MPeti1** [comment]
Here I uninstall and reinstall the app from F-droid:
https://user-images.githubusercontent.com/9215491/142947082-e20369e3-9154-47c1-b5b5-948576c30a3f.mp4

The cursor is there because I operated my phone with strcpy.

**Comment by sonora** [comment]
Sound's like it could simply be a build issue, f-droid currently builds based on version code 4.0x, while @Chumva is likely talking about our nightlies based on 4.1.

**Comment by MPeti1** [comment]
Oh, it makes sense. 4.0.9 was based on edd0676 according to the [build log](https://builder.osmand.net:8080/view/OsmAnd%20Builds/job/Osmand-release/1003/console) (found [here](https://gitlab.com/f-droid-mirrors/OsmAnd-submodules/-/merge_requests/57)), and baa1e83 happened after that.

sorry! your release system is a bit hard to see through 😅

**Comment by julianfairfax** [comment]
This appears to be working right now. At least, there's a plugin that's disabled that I can then enable.

But the online photos section still shows in the details if it's disabled, but just doesn't show any images.

The section shouldn't show at all if the feature is turned off. Especially since a user might not understand that they have to enable the plugin, and will just think that there are no online photos available for what they're viewing.

**Comment by artlog** [comment]
Mapillary is well deactivated, what lacks now is an information in Online photos 'Add Photo' part of application that it requires additional plugins. See my verbose comment in https://github.com/osmandapp/OsmAnd/issues/9402.
