### ISSUE TITLE
Not prefering a bicycle route which is in the majority of the path, but not shortest.

### ISSUE THREAD

**Issue by pitastrudl** [osmandapp/OsmAnd#12018]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, OpenRouteService, OSRM, etc.)

### Routing Profile

Bicycle profile

### Start and end points

from: 44.4487,-1.2528
to: 44.4055,-1.1623 

https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=44.44884%2C-1.25291%3B44.40579%2C-1.16239#map=14/44.4273/-1.2068

### Actual and expected routes

![image](https://user-images.githubusercontent.com/2771072/123849475-20a49980-d919-11eb-83dd-82ca7711e080.png)
Red line is expected routing, blue line is on the normal paved road. This is using balanced driving style. 

If you try to avoid the road, it puts you on another road:
![image](https://user-images.githubusercontent.com/2771072/123849644-534e9200-d919-11eb-8143-05fa54920dba.png)

If you add points, it helps:
![image](https://user-images.githubusercontent.com/2771072/123849603-4762d000-d919-11eb-8ac4-5dcd2a287897.png)

### Is this a regression?

Not sure 

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

3.9.10 - Fdroid version
</code></pre>

**Device and Android/iOS version:**
Android 8.0
**Maps used (online or offline):**
Offline map directly from OsmAnd

- [ x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**
A suggestion to add for Bicycle driving style option, would be a "prefer bicycle routes, which would then try to prefer the majority of the bicycle routes. It makes sense in this case it will try the shortest route but it's mostly on the road. This new option could prefer the bicycle routes but not sure how to choose weigh the preference.

**Comment by scaidermern** [comment]
+1 for a setting that gives high priority to cycleways. Currently cycleways in OsmAnd don't have a high priority and are often avoided, for strange reasons (#12023, #10191).

**Comment by alisa911** [comment]
Hi! In the last version of OsmAnd (4.0.6), when the road is avoided, this route is being built.
<img width="474" alt="Screenshot 2021-11-01 at 13 54 06" src="https://user-images.githubusercontent.com/38911173/139670133-b6995a28-196e-43c6-a909-d0cf08553861.png">
