### ISSUE TITLE
impossible river crossing

### ISSUE THREAD

**Issue by Loki-Afro** [osmandapp/OsmAnd#12012]
# 🐞 routing report

### Routing engine

- [ x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, OpenRouteService, OSRM, etc.)

### Routing Profile
bike profile
### Start and end points

from HWN 066 to HWN 069
https://www.openstreetmap.org/search?query=HWN%20066#map=19/51.72310/10.96611
https://www.openstreetmap.org/search?query=HWN%20069#map=19/51.72210/10.97009

### Actual and expected routes

things get tricky from here
1. the direct route to HWN 069 is not allowed by bike (its tagged like that on osm - 27.06.2021) 
2. in the screenshot you see osmand is routing me directly through the river Bode, although i did this as a child, this is not appropriate with a bike and with a little cliff on one end :D - there is no furt nor bridge or similar.

expected:
OsmAnd would have routed me to this place https://www.openstreetmap.org/node/1953289547 to get on the other side of the river and on that trail that is marked as not allowed for bikes. This seems pretty far of but its the closest you can get to the destination since destination is not reachable by bike at all.

![signal-2021-06-28-125258](https://user-images.githubusercontent.com/4738445/123625214-d388d080-d80f-11eb-9778-4e6280cdc1c0.jpeg)

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

3.9.10
</code></pre>

**Device and Android/iOS version:**
Android 10

**Maps used (online or offline):**

- [ x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**

**Comment by scaidermern** [comment]
I guess this is due to this bridge: https://www.openstreetmap.org/way/25912067
It is tagged with `bicycle=no`. This leads to a routing island for bicycles. A bicycle router is not able to reach the rest of the world from your starting point. So OsmAnd falls back to a straight line until reaching something that is connected to the road network.

Is `bicycle=no` for the bridge correct? Maybe `bicycle=dismount` is appropriate instead?

**Comment by Loki-Afro** [comment]
@scaidermern i thought so .. but can't answer that question, just was there yesterday and was slightly confused since i didn't spot any signs for "bikes not allowed bla bla" .. i changed at least that way on osm, but not the bridge yet :/ anyway - wouldn't the closest point be just before the bridge? I know this is kinda corner case, but since this line is so thick one might think there is actually a bridge underneath :D

**Comment by scaidermern** [comment]
> wouldn't the closest point be just before the bridge? I know this is kinda corner case, but since this line is so thick one might think there is actually a bridge underneath :D

I guess OsmAnd takes the shortest distance to the next routeable road segment. Which is right across the river, unfortunately. But this is caused by an error in the map data (unless cycling is really forbidden).

**Comment by Loki-Afro** [comment]
yes, really unlucky circumstances, fixed it on osm, can recommend that area though ;)
