### ISSUE TITLE
Offline Routing: Routing names are not using Map Preferred Language (nor TTS nor route info)	

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#1201]
https://code.google.com/p/osmand/issues/detail?id=2467

I'm using latest OSMAnd+ and maps for Russia. To be exact mostly Russia_moscow_asia_2.obf.zip and Vocalizer with English voice. But when OSMAnd have to say street name, or road name is just skip it.
For example, "After 600 meters keep left on". If I switch to Russian TTS it say same thing, but with road name "After 600 meters keep left on kutuzovsky prospekt" (in russian).
I've tried to use setting "use English names on map", but it affects only display and search, but doesn't affect TTS.
Android version is 2.3.7

>> 
We have english names everywhere using transliteration, the issue in the multilang offline data and its support

**Comment by mchapliuk** [comment]
Similar problem:

I am using osmand in Ukraine. The map language is set to Russian, but when navigation is enabled, names of current streets are shown in Ukrainian, and voice tries to pronounce Ukrainian names in Russian.

Expected result: if I choose preferred map language, navigation language should be the same.

**Comment by vshcherb** [comment]
Fixed

**Comment by vshcherb** [comment]
New maps need to be downloaded after 15th June

**Comment by vshcherb** [comment]
Preferred Map Language settings is respected
