### ISSUE TITLE
Add explanatory text when creating an error message

### ISSUE THREAD

**Issue by gtrus21** [osmandapp/OsmAnd#12013]
Add explanatory text when creating an error message (like maps.me)

For example:
_2021-06-28 13:57:13 UTC User:_
"Closed"
_The place has gone or never existed. This is an auto-generated note from OMaps application: a user reports a POI that is visible on a map (which can be outdated), but cannot be found on the ground.
POI name: SuperShop
POI types: shop-alcohol
OSM data version: 2021-05-29T07:59:45Z_

**Comment by scaidermern** [comment]
Where should this text come from?

Such a predefined text only makes sense if the user is answering predefined questions. This is not how the OSM notes implementation in OsmAnd works.

**Comment by gtrus21** [comment]
The name of the POI that I am currently viewing should be inserted.  Those.  h chose POI xxx, clicked create a note, and this note will contain the name xxx

**Comment by vshcherb** [comment]
Auto-generated text is bad. It gives 0 new information and only bloats & distracts from useful people messages.

**Comment by gtrus21** [comment]
It shows which object this note belongs to.
