### ISSUE TITLE
Bicycle routing: cycleway gets avoided

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#12023]
In bicycle routing, OsmAnd tries to avoid a way tagged with `cycleway:right=track`, at least with driving style "balanced".

Driving style balanced:
![balanced](https://user-images.githubusercontent.com/1040784/123914874-2c777680-d980-11eb-9762-b6ddb9e0a638.jpg)

Driving style shortest route:
![shortest](https://user-images.githubusercontent.com/1040784/123914899-3305ee00-d980-11eb-9909-886f6a2e6f7e.jpg)

From: 51.0431343,13.7233615
To: 51.0366918,13.7154651

OsmAnd nightly.

I would expect that a "balanced" driving style prefers official cycleways.

Could be related to #10191.

**Comment by xmd5a2** [comment]
OsmAnd tries to avoid this road because of traffic signals.
`<select value="2.3" t="cycleway" v="track"/>` fixes issue but looks like it is too much and can cause unexpected detours in other places.

**Comment by scaidermern** [comment]
I see.

What about a new mode? "Prefer cycleways". This will also fix #12018. 

A fourth mode makes the UI even more complicated. But the current bicycle routing of OsmAnd isn't really usable in larger cities. Too often OsmAnd ignores existing bicycle infrastructure. We need something that gives a high priority to bicycle infrastructure, even if this leads to slightly longer routes. Bicycle infrastructure is often fast and secure, the detours OsmAnd currently choses are sometimes neither fast nor secure.

**Comment by xmd5a2** [comment]
I've increased some coefficients. This should solve this particular issue but there is a lot of things to improve.

**Comment by scaidermern** [comment]
Thanks!
