### ISSUE TITLE
Bug for Roundabout with Motorway exit with and without Avoid Motorway option

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#1202]
https://code.google.com/p/osmand/issues/detail?id=2291

Hi

I have noticed the problem with the Routing for the Roundabout with the "Avoid Motorway" option enabled.

Without that option Routing is correctly counting the exits so you can follow your directions:

http://osm.org/go/0EQGXPdgV-  if follow direction from A1309 to A10.

With the Avoid Motorway option enabled Routing excludes the motorways from calculation which is good but it is excluding the exits too!!!!
And actually if it says take 1'st exit and you dont follow the signs you will end up in motorway !!!!

Also if "Avoid Motorway" is enabled it will be nice to have the icon shows that you should not take that exit and take the correct one.

**Comment by hakuchi** [comment]
this issue was reported 2014 the first time, and not fixed yet.
the easiest way to fix this, I think, is to add only highway=motorway to the option avoid motorways.
the motorway_link normally ends on the motorway and so the problem with roundabout and link is fixed

**Comment by vrtareg** [comment]
Hi

I remember this one. 

Looks like I have reported it on old bug tracking system. 

Regards, 
Areg

**Comment by aceman444** [comment]
I don't think this fix is correct. You (or user) can disable routing over various types of roads in different scenarions/navigation modes (e.g. trunks or tracks). But the roads are physically there and the user will see them in real life, so the engine must take them into account when navigating/displaying the exits or voice commands.

This can't be fixed by removing only motorway_link from routing.xml. It is an incorrect solution. The internal engine must be fixed.

**Comment by hakuchi** [comment]
tested with latest nightly and for me this fix looks correct.
this is the simplest fix and after this, nothing is broken in the app.

**Comment by aceman444** [comment]
Yes, it surely works for your specific scenario. But try a roundabout where a highway=trunk ends and disable trunks in rounting.xml. I assume you get the bug again.

**Comment by hakuchi** [comment]
in Osmand is no option to avoid highway=trunk.

You brought me on this, that the error can happen at toll roads what ending on a roundabout, when set in Osmand avoid toll.
I don't know how many toll roads ending on a roundabout.

**Comment by aceman444** [comment]
> hakuchi commented 22 hours ago
> in Osmand is no option to avoid highway=trunk.

No, it is not built in yet, but the user can add it in a customized routing.xml file.

> You brought me on this, that the error can happen at toll roads what ending on a roundabout, 
> when set in Osmand avoid toll. I don't know how many toll roads ending on a roundabout.

Yes, that seems to be a possible case where the error may happen again. Maybe toll roads are not that common, but there is an option to avoid "unpaved roads". Those surely can end at a roundabout.
