### ISSUE TITLE
Startup map position

### ISSUE THREAD

**Issue by szatmariors** [osmandapp/OsmAnd#12021]
# 🚀 feature request

### Description

When starting OsmAnd, the map always jumps to the current location. But it would be useful to choose whether to jump to the current location or to stay at the last used map position. Many times people want to continue browsing the map at the last map position. For example, if you find something interesting on the map and you want to google it in a browser, so you leave the OsmAnd app for one or two minutes, and then you want to continue browsing, but the map jumps to the current location... This is very annoying.

(For example, Google Earth android app always stays at the last used map position, and it causes no problem, beacause you can jump to your current position whenever you want by pushing the target cross. OsmAnd also uses this target cross, when you don't leave the app, you can use it.)

### Describe the solution you'd like

I recommend that OsmAnd always use the last map position like Google Earth app. If you want to jump to your current location, just push the target. 

### Describe alternatives you've considered

An alternative solution would be to choose in the app options whether to stay at the last used map position or to jump to the current position by default when starting the app.

**Comment by vshcherb** [comment]
Actually it should be 1h check, so within 1h after restart OsmAnd shouldn't change the locaiton (except map location was in sync with current location).

**Comment by szatmariors** [comment]
Thanks a lot!
