### ISSUE TITLE
 Distance measuring to nautical mile not persistent

### ISSUE THREAD

**Issue by fatuuse** [osmandapp/OsmAnd#12022]
### Description
When changing measuring distance to nautical mile in boat mode for profile, it's not persistent after restart of the app.

### How to reproduce?
Change measuring to nautical mile, choose apply, just this profile. Exit Osmand, distance measuring is back to default. 

### Your Environment
OsmAnd Version: Osmand+ 3.9.10
Android/iOS version: android 11
Device model:

**Maps used (online or offline):**   
Both

**Comment by vshcherb** [comment]
Indeed, For plan route - Selected profile should be selected by default.

**Comment by vshcherb** [comment]
Your issue should be fixed in 4.0 already
