### ISSUE TITLE
Destination too far from next street

### ISSUE THREAD

**Issue by MPW1412** [osmandapp/Osmand#1203]
Hello,

OsmAnd often reports that the destination is too far away from the next street. The calculation abborts.

As most houses or addresses contain a street name, the algorithm should find that street and calculate the closest point on the street to the destination. (Mathematical problem: minimum distance line <-> point.)

Workaround: Set a point on the map near the destination, which is closer to the next street.

Thanks for reading.

Regards,
MPW

**Comment by vshcherb** [comment]
It would be good to see an example on the map, in order to reproduce the issue.

**Comment by jfburke3** [comment]
Victor, someone else started another github entry on this problem too, and another person in that thread speculated that it might happen when multiple map files are used. 

A quick test route I created seems to support that. A real trip I just made from Atlanta, Georgia to Tampa, Florida (475 miles) was plagued by this problem, even though I used waypoints. I just tried a test route from Miami, Florida to Tallahassee, Florida (480 miles with no waypoints) and did not encounter any errors.

**Comment by vshcherb** [comment]
There is a critical issue https://github.com/osmandapp/Osmand/issues/1226, this might be related

**Comment by jfburke3** [comment]
Victor, yes, that is the other topic I was referring to. I agree that they are probably the same thing from the descriptions.

**Comment by MPW1412** [comment]
Hello,

you're right, the problem is related to the multi destination feature. If you just set one destination, it didn't occure yet.

But the problem is also related saved destinations. I had it several times, that when I enter some waypoints, osmand correctly calculates the route. When I close the app then and reopen it next morning, it fails to calculate the route again and shows the error description.

And the problem seems to be related to very long routes (600+ km). It didn't occur with short routes yet.

Greetings
MPW

**Comment by sonora** [comment]
I think this was fixed in #1226.

**Comment by jfburke3** [comment]
I can't say I've seen this in a long time, so closing it is probably right.
