### ISSUE TITLE
Odd rendering in NW England map near Warrington

### ISSUE THREAD

**Issue by sjorford** [osmandapp/OsmAnd#12049]
### Description
At high zoom levels there is an odd rendering artefact near the River Mersey south west of Warrington:
![image](https://user-images.githubusercontent.com/10633357/124347666-bc662c00-dbdd-11eb-8ab1-87fd5a271cfb.png)

It looks like a stretch of the river is being reproduced in a zig-zag shape. There are no nodes at the points of the zig zag as far as I can see:
https://www.openstreetmap.org/search?whereami=1&query=53.38%2C-2.61

I don't think this is a new issue, as I remember first seeing it a couple of years ago

### How to reproduce?
1. Download England North West England map
2. Do a coordinate search for Lat 53.38, Lon -2.61
3. Zoom in to about level 10

### Your Environment
OsmAnd Version: OsmAnd+ 3.9.10
Android/iOS version: Android 9
Device model: Samsung SM-G950F

**Maps used (online or offline):**   
Gb_england_north-west-england_europe_2 (1 Jun 2021)

**Comment by xmd5a2** [comment]
Will be fixed in next basemap generation

**Comment by sjorford** [comment]
I'mn still seeing this in the 1 Aug 2021 map?
