### ISSUE TITLE
osmand takes the very long route despite having a far more suiteable way nearby

### ISSUE THREAD

**Issue by Loki-Afro** [osmandapp/OsmAnd#12042]
# 🐞 routing report

### Routing engine

- [ x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, OpenRouteService, OSRM, etc.)

### Routing Profile

bike
### Start and end points

https://www.openstreetmap.org/query?lat=51.72447&lon=11.06548#map=18/51.72579/11.07138

### Actual and expected routes

![actual](https://user-images.githubusercontent.com/4738445/124285889-abbaa500-db4e-11eb-93a7-53dffccd3d93.jpg)

![expected](https://user-images.githubusercontent.com/4738445/124285795-96de1180-db4e-11eb-8fc3-2855aa105e39.png)

### Is this a regression?

dunno

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

3.9.10
</code></pre>

**Device and Android/iOS version:**
10
**Maps used (online or offline):**

- [ x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**
i have looked at the ways on osm at they all seem to allow bicycles although i'm not an expert - this dosen't seem only to happen with osmand, openrouteservice is also affected so i think there is a mapping issue but i can't spot it.

see here https://classic-maps.openrouteservice.org/directions?n1=51.726151&n2=11.071483&n3=16&a=51.725124,11.067604,51.726852,11.073993&b=1a&c=0&k1=en-US&k2=km

**Comment by xmd5a2** [comment]
Can't reproduce issue with bicycle routing profile
![Screenshot_2021-07-06_13-21-18](https://user-images.githubusercontent.com/5829014/124584668-2fc9a100-de5d-11eb-87cb-cef41efd7ad6.png)

**Comment by Loki-Afro** [comment]
Can't reproduce it either after updating the map for Saxony Anhalt today - update way available today but map data is still from 1.6.2021 :/
