### ISSUE TITLE
OSRM and OpenRouteService are not working

### ISSUE THREAD

**Issue by Zahnstocher** [osmandapp/Osmand#1204]
OSRM and OpenRouteService are not working, but YOURS is working.
No problem with 1.9.5, but 2.0 does not work.

https://code.google.com/p/osmand/issues/detail?id=2637

**Comment by vshcherb** [comment]
As I see in the log https://router.project-osrm.org/ (is not valid https certificate somehow)

**Comment by vshcherb** [comment]
https certificate doesn't seem to be accepted on Android.
So we switched to http rest

**Comment by ghandmann** [comment]
At least for me, OsmAnd+ 2.0.4 is still not able to calculate routes with OpenRouteService and OSRM. It only reports "Error: Calculated route is empty".

Online routing is only working with YOURS.

**Comment by manolollr** [comment]
It works in version 2.1

**Comment by mathsen** [comment]
Doesn't work for me in Osmand 2.2.4 and Android 6.0.1 (Nexus 5).
All I get is
"Error: Calculated route is empty"
