### ISSUE TITLE
web page links

### ISSUE THREAD

**Issue by mariush444** [osmandapp/OsmAnd#12047]
Web page
https://osmand.net/build_it

paragraph _OsmAnd Sample_

**links that don't work (404)**
```
https://download.osmand.net/latest-night-build/OsmAndCore-sample-armv7.apk
https://github.com/osmandapp/Osmand/tree/master/OsmAndCore-sample
```

**Comment by vshcherb** [comment]
Fixed https://github.com/osmandapp/osmandapp.github.io/commit/70c7728b8640f483a555bab1786219575f9049b0
