### ISSUE TITLE
Colors (night mode) 'Track saved' dialog

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#12051]
The following is quite inconvenient at times: After finishing a track recording via the widget, a dialog named 'Track saved' pops up which offers that you can immediately rename the track from its default name.

Most users want to keep the default name but add something to its end, like maybe a place or trip name.

If you put the text input cursor somewhere in the middle of the displayed track name, things work ok. But it is customary that if you tap to the right of the track name,the text input cursor should be placed to the end of the existing text string.

But our dialog in that case deletes the existing file name (with no real way to get it back). I strongly suggest we should not delete the displayed text (which is the file's defailt name) if a user tries to rename and taps to the right of it. (Deleteing that string can easily be achieved via the keyborad's backspace if desired.)

**Comment by sonora** [comment]
This is not fixed in today's nightly ...

**Comment by vshcherb** [comment]
Sorry didn't put comment to clarify what's going to be fixed.

> The issue teported is that the default filename gets erased in the text box if you tap anywhere to the RIGHT of the displayed default text name string.

It was not reproduced. You probably hit the button "clear" but it should be very narrow phone, so on normal phone, it is not erased and put in the end.

So this issue was fixed in sense that keyboard wasn't open correctly.

**Comment by sonora** [comment]
I think you are right, here is the screenshot: In dark mode the 'clear' button is hardly visible, but it turns out it covers about half the space between 'Sun' and the end of the textbox on some devices. Both effects likely invite the described accidental behavior.

I guess we could at least make the button a bit more visible? Maybe finally look at #9125 ?
![20210718_230802](https://user-images.githubusercontent.com/845735/126082297-85ba5031-8405-466c-8057-d32fb0418e43.jpg)
