### ISSUE TITLE
Link "show on map" from wikivoyage article doesn't work.

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#12055]
### Description

Link "show on map" from wikivoyage article doesn't work.

### How to reproduce?
<table style="width:100%">
  <tr>
    <th><img src="https://user-images.githubusercontent.com/44466116/124435006-3680e700-dd7d-11eb-8c69-40d47c45c445.png"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/44466116/124435040-3ed92200-dd7d-11eb-9269-0c6aefe1da43.png"  width="300" height="auto"/> 
</th>
  </tr>
</table>

### Your Environment
OsmAnd Version: 4.0.0#32295m , released 2021-07-02
Android/iOS version: Android 11
Device model: S10e

**Comment by dmpr0** [comment]
The issue happens with travel gpx description, we need to:
• Open travel article if the needed file is dowlnoaded 
• We should add support to all links: "Open on the map", "tel", 
• All web links should be opened in "chrome tabs".
