### ISSUE TITLE
Bicycle routing: Can't route across intersection

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#12063]
In bicycle mode OsmAnd can't route across the following intersection:

![photo_2021-07-06_12-33-20](https://user-images.githubusercontent.com/1040784/124586150-65b75700-de56-11eb-97a7-0c89d54cde70.jpg)

From: 51.0588152, 13.7261724
To: 51.0585184, 13.725872
[route.gpx](https://github.com/osmandapp/OsmAnd/files/6769329/route.gpx.txt)

Map data looks fine to me.

Routing is fine with GraphHopper: https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=51.05902%2C13.72641%3B51.05845%2C13.72583
Routing is fine with OSRM: https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=51.05902%2C13.72641%3B51.05845%2C13.72583

Maybe there is a misinterpretation of `cycleway:left:oneway=yes` (https://www.openstreetmap.org/way/759408334) and/or `cycleway:right:oneway=yes` (https://www.openstreetmap.org/way/210135540)?

**Comment by scaidermern** [comment]
Still broken in OsmAnd 4.0.2

**Comment by scaidermern** [comment]
Still broken in OsmAnd 4.0.7

Any idea what could be wrong here? If I let avoid all alternative paths then routing across this intersection succeeds:

![photo_2021-09-16_19-07-48](https://user-images.githubusercontent.com/1040784/133655495-f8cb2930-2b4b-4fbc-9841-d0d1a8bd5ddc.jpg)

So routing is possible, but it looks like there is a high penalty somewhere at this intersection.

**Comment by vshcherb** [comment]
@scaidermern can you try to modify routing.xml ? Probably it would be more convenient to give you more power with OsmAndMapCreator so you can test and see what's exactly broken... it could be one of those obstacles... https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#L1547

**Comment by scaidermern** [comment]
> @scaidermern can you try to modify routing.xml ? Probably it would be more convenient to give you more power with OsmAndMapCreator so you can test and see what's exactly broken... it could be one of those obstacles... https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#L1547

Setting all these obstacles to 0 doesn't resolve the problem. The large detour stays.

**Comment by ivanPyrohivskyi** [comment]
[Dresden.obf.zip](https://github.com/osmandapp/OsmAnd/files/10813093/Dresden.obf.zip)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14198mqta, Released: 2023-02-24
24.02

<details><summary>Done</summary>
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/221228918-b18b41f9-69e0-4619-8fc1-843cde4a1831.png">
<img width="360" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/221228973-127d7e1b-6f05-494d-9914-074644bea46e.jpeg">
</details>
