### ISSUE TITLE
Car routing: long deviation for motorway exit

### ISSUE THREAD

**Issue by bikepunk** [osmandapp/OsmAnd#12066]
# 🐞 routing report

### Routing engine

- OsmAnd's in-app offline routing

### Routing Profile
car

### Start and end points

expected routing 
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=45.47905%2C4.34794%3B45.48164%2C4.34193

### Actual and expected routes

![Screenshot_20210706-191303_OsmAnd~](https://user-images.githubusercontent.com/14958221/124642550-42a99900-de90-11eb-84fb-34201a5fd512.png)

The routing shall turn right on the motorway link (as OSRM does) instead of this weird U turn on the primary road.
Since this is not exactly a U turn, I cannot forbid U turn in OSM database

### Is this a regression?

 nope

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

OsmAnd~3.9.10
</code></pre>

**Device and Android/iOS version:**

LineageOS 16.0

**Maps used (online or offline):**

-  Offline maps offered within the OsmAnd app for download.
**Anything else relevant?**

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/9436

**Comment by vshcherb** [comment]
Plus we need to add tests from https://github.com/osmandapp/OsmAnd/issues/9436
