### ISSUE TITLE
"OsmAnd does assume any liability if you violate the law"

### ISSUE THREAD

**Issue by dbolton** [osmandapp/Osmand#1206]
How to get there: 
1. Settings -> Navigation Settings -> Car -> Announce
2. Add a check mark next to "Announce speed cameras"
3. Press "OK"

Presumably OsmAnd intends to "not assume any liability" however their warning does the exact opposite.

> "In many countries (Germany, France, Italy, and others) the use of speed camera warnings is not permitted by law. OsmAnd does assume any liability if you violate the law. Please click yes only if you are eligible to use this feature."

OsmAnd 2.0.3

**Comment by vshcherb** [comment]
Yep, the word any without not sounds weird. So it should be  "does not assume"

**Comment by sonora** [comment]
Yes, of course, the word "not" was missing ... :-)

Looks like someone already fixed it.
