### ISSUE TITLE
Bicycle routing : do not route on trunk roads explicitly not allowed access for bicycle.

### ISSUE THREAD

**Issue by bikepunk** [osmandapp/OsmAnd#12065]
trunk roads shall be avoided for bicycle routing 
When using "shorter routes" offline bicycle routing, Osmand routes on the trunk road from Nantes to Brest 
![Screenshot_20210706-183443_OsmAnd~](https://user-images.githubusercontent.com/14958221/124636795-3a019480-de89-11eb-8826-bed6c1910f04.png)

this trunk road is explicitly not allowed access for bicycle and pedestrians in OSM database.

OsmAnd~3.9.10 on LineageOS 16.0

**Comment by scaidermern** [comment]
The default access tag for trunk roads for bicycle is yes, according to https://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Access_restrictions 

Country-specific defaults are different, of course.

**Comment by bikepunk** [comment]
this very trunk road is tagged as "no" for bicycle and pedestrians. Does offline Osmand bicyle routing consider this tag ?

anyway, IMHO bicycle routing shall avoid trunk roads when possible (at least for western europe reality)

**Comment by scaidermern** [comment]
> this very trunk road is tagged as "no" for bicycle and pedestrians. Does offline Osmand bicyle routing consider this tag ?

Oh, sorry I missed that. Yes, it should recognise this tag.

**Comment by bikepunk** [comment]
> Country-specific defaults are different, of course.

and in France, the default value is "no"

**Comment by xmd5a2** [comment]
![Screenshot_2021-07-15_23-20-36](https://user-images.githubusercontent.com/5829014/125852351-61f700da-704b-47cf-b813-33fbcc15ded3.png)
`bicycle=no` tag was added recently. Not reproducible with up to date OSM data. @bikepunk please try to update offline map.
