### ISSUE TITLE
Maps should be update-able incrementally 

### ISSUE THREAD

**Issue by morray** [osmandapp/Osmand#1207]
Updating map data takes quite some time as some countries/regions of the world have a lot of data. It would be beneficial if this could be solved by providing just the diffs.

**Comment by vshcherb** [comment]
That's a duplicate one

**Comment by Tchiller** [comment]
@vshcherb Could you pls link to the dupe? I can't find it here. Is there work in progress? 
Thanks, I appreciate your work!

**Comment by sonora** [comment]
Yes, there is work in progress here. We do have incremental map updates working now (not released yet), but there are some issues and not all map/routing functionality works correctly with incrementally updated maps.
