### ISSUE TITLE
GPX routes and official map synchronisation

### ISSUE THREAD

**Issue by Paraklius** [osmandapp/OsmAnd#12073]
Hi all,

I tested some other GPX guide apps, and , if possible, I propose you here, something not easy (I think) but that can be a major advantage  for Osmand.

When you try to follow a GPX route (visually  or vocally) osmand ignore his real map, and rely only on the GPX datas to indicates directions (turn left, right etc..., witjout any map detail).

I lately tested the Komoot app. This one propose befor to start the navigation too synchronise the GPX route to the real  map. Of course, some unofficial paths are then be modified to be compatible with  the official map. But the Komoot app is then capable to follow the GPX route using the normal map indications (streets name, crossings etc...), "turn left in Backer Street avenue"...

If this would be possible in Osmand, it would be definitly great! 😊😊 but I think it is quite hard to build^^

Thank you all 😊

**Comment by dmpr0** [comment]
Hello! Thank you for the feedback.
You can do it in OsmAnd too, in Menu – Directions – Options – Follow track, select "Attach to the roads", a new screen will be opened where you can select the needed profile and set threshold distance.

**Comment by Paraklius** [comment]
Hi Dmpr0, thanks for your respond.

I'm so sorry ! you're right...  This is so perfect ! thank you 👍 

Have a nice day !

**Comment by Paraklius** [comment]
Hi Dmpr0, sorry, but there is still a little problem

By attaching the way to the routes, osmand annonces street directions, that's cool, but it then ignore completly  the gpx points (POI), that are not announced anymore (even if it is selected in the navigation options).

Would it be possible to have both (attach to routes => streets directions + GPX POI announcements).

Here is my  GPX file with POI, if you want to try: bit.ly/OSMANDTRIAL.

Thank you for your help 😊.

Raphael 

Have a nice day !

**Comment by vshcherb** [comment]
That moment is already fixed and will be available in 4.0 release

**Comment by vshcherb** [comment]
You can try nightly version by the way
