### ISSUE TITLE
OsmAnd links to the outdated Mapillary app

### ISSUE THREAD

**Issue by adelobosko** [osmandapp/OsmAnd#12084]
### Description
OsmAnd links to the wrong Mapillary app (this app is outdated https://play.google.com/store/apps/details?id=app.mapillary)

The new app: https://play.google.com/store/apps/details?id=com.mapillary.app

### How to reproduce?
Try to add a photo to any place.

### Your Environment
OsmAnd Version: 3.9.10
Android: 8

**Comment by vshcherb** [comment]
Fixed in nighlty already
