### ISSUE TITLE
What is the current status of the slow map rendering?

### ISSUE THREAD

**Issue by tegutistgut** [osmandapp/OsmAnd#12090]
Hi devs and community,

We all know that OsmAnd renders Maps very slow. This has nothing to do with bad, slow or old hardware. This is a OsmAnd specific issue, because other apps that use OpenStreetMap (I.e OrganicMaps) are very fast in comparison.

The rendering is so slow that the app is literally unusable. Even maps in my browser (metager maps, qwant maps, etc.)  are thousand times faster than OsmAnd.

And its really sad that its so slow because otherwise its a really, really good app

I was following this thread: _Improve map rendering speed (expected sub-second) #8370_ and the devs now closed this thread, for whatever reason.

I now want to know what the current status of this issue is. Is a fix in development?
Why did the devs closed the thread?

Thanks

**Comment by vshcherb** [comment]
Some steps are planned for Q3 2021.
