### ISSUE TITLE
Handle female, male and unisex tags for toilets

### ISSUE THREAD

**Issue by jazzzz** [osmandapp/Osmand#1209]
It would be very useful to see if toilets are female-only, male-only or unisex.

**Comment by gorn** [comment]
I have not seen any example of singlesex toilette (without the other one really close) **except** in indoor routing, but there osmand still has much more important glitches.

**Comment by jazzzz** [comment]
> I have not seen any example of singlesex toilette (without the other one really close) except in indoor routing, but there osmand still has much more important glitches.

All external urinals are male-only, with no close female toilets (see the urinals near Soho Square in London).

**Comment by gorn** [comment]
Than this is needed :)

**Comment by sonora** [comment]
Closed for now for lack of relevance.

**Comment by jazzzz** [comment]
In fact it has been fixed since: now the info is visible is the POI details.
