### ISSUE TITLE
change:lanes not support

### ISSUE THREAD

**Issue by Almorca** [osmandapp/OsmAnd#12096]
### Routing engine

- [X] OsmAnd's in-app offline routing

### Routing Profile

Car with "España Canarias" map

### Start and end points

This route https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=27.86364%2C-15.41866%3B27.86810%2C-15.42047#map=17/27.86589/-15.41973 is wrong.

Way 469667109 wad mapped as change:lanes=yes|yes|no but osmand ignore this tag.

### Is this a regression?

No

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>
Osmand+ 3.9.10
</code></pre>

**Device and Android/iOS version:**
Android

**Maps used (online or offline):**
- [X] Offline maps offered within the OsmAnd app for download.

**Comment by vshcherb** [comment]
We don't plan to support it for now cause it's very complicated feature to implement & it has not approve status on OSM Wiki (https://wiki.openstreetmap.org/wiki/Proposed_features/change)
