### ISSUE TITLE
merge gpx files functionality

### ISSUE THREAD

**Issue by soredake** [osmandapp/OsmAnd#12098]
Would be nice to have this functionality in osmand.

like https://joewein.net/bike/gpxmerge/

**Comment by hockeymikey** [comment]
Which is?

**Comment by tradavyvy** [comment]
If this also would work for merging my favourites from my tablet osmand my phone and my wifes phone that would be great. We use the same 'groups' and colors on all devices, but they tend to diverge in content over time. Importing one in the other leads to losing this information.

**Comment by vshcherb** [comment]
You can do it via "Plan Route" -> "Edit Track" -> "Save ... " -> Add to another track

**Comment by soredake** [comment]
> 
> 
> You can do it via "Plan Route" -> "Edit Track" -> "Save ... " -> Add to another track

Would be nice to have checkbox to remove original file after merge.

**Comment by soredake** [comment]
And merging 2 or more files is not possible with this.

**Comment by vshcherb** [comment]
> And merging 2 or more files is not possible with this.
I'm afraid is one by one. Indeed it's not super-nice and easy to find functionality cause it was done for another purpose. But it is a legitimate workaround.
