### ISSUE TITLE
Visualization of contour lines

### ISSUE THREAD

**Issue by GuentherGredy** [osmandapp/OsmAnd#12102]
# 🚀 feature request

### Would it be possible to show the contour lines in a more obvious color? It is clear to me that this is not easy because of the contrast to other more important elements (e.g. pathes) of the map.

 If you have a solution in mind, please describe it.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by pebogufi** [comment]
Goto contour setting which you will find in in each profile. There you can change color, thickness and more of contour lines.
