### ISSUE TITLE
parsing of Covid19 opening hours is broken (adds 24/7?)

### ISSUE THREAD

**Issue by mnalis** [osmandapp/OsmAnd#12109]
### Description
When displaying `opening_hours:covid19`, it seems that `24/7` is erroneously added. 

There is somewhat related https://github.com/osmandapp/OsmAnd/issues/8962 but it talks only about special COVID-19 values, not this failure to parse standard `opening_hours`. 

### How to reproduce?
- Open this location in OsmAnd: https://osmand.net/go?lat=45.80911&lon=15.92983&z=16
- click on `pharmacy` with name `Ljekarne Vidmar` 
- click `details` to show opening hours
- it shows among other correct data this `24/7 - Covid19` which is not (and [never has been](https://www.openstreetmap.org/node/1377491383/history)) in OSM.  
  Compare `details output` with what `modify POI` in OsmAnd shows:

![s_Screenshot_20210706_083212_net osmand plus](https://user-images.githubusercontent.com/156656/125681896-20bea42e-bf46-486a-9bab-92f9e6f306e0.jpg) ![s_Screenshot_20210706_083236_net osmand plus](https://user-images.githubusercontent.com/156656/125681916-4ddffb4e-f2c4-4e35-bd0a-5b8584fe4163.jpg)

  
### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: Android 10 (EMUI 11.0.0)
Device model: Huawei P30 Pro

**Maps used (online or offline):**   
Standard maps (vector): Croatia (Jul 1, 2021)

**Comment by Dima-1** [comment]
According to specification of opening hours, hours list should not have separator ";" at the end. Issue will be fixed in the new version of maps
