### ISSUE TITLE
POI editing: Autocompletion offers "color" tag instead of "colour"

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#12106]
When editing a POI, the autocompletion feature in the advanced tap offers the tag "color". However the correct spelling of this tag is "[colour](https://wiki.openstreetmap.org/wiki/Key:colour)". "colour" isn't offered at all.

**Comment by vshcherb** [comment]
We should migrate slowly data from "color" storage to "colour"

https://github.com/osmandapp/OsmAnd-resources/blob/master/poi/poi_types.xml#L27
https://github.com/osmandapp/OsmAnd-tools/blob/3d2358848d2e9dcae871f368f0587a5462c5ecfe/java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/OsmGpxWriteContext.java#L217
https://github.com/osmandapp/OsmAnd-tools/blob/3d2358848d2e9dcae871f368f0587a5462c5ecfe/java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexRouteRelationCreator.java#L111

**Comment by xmd5a2** [comment]
https://github.com/osmandapp/OsmAnd-resources/commit/64aaeec055a36fdf759838e0344cf6eed1223337
