### ISSUE TITLE
Setting "Route parameters" -> "OsmAnd Live data" only available for car profile

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#12105]
Only the car profile offers the setting "Navigation settings" -> "Route parameters" -> "OsmAnd Live data", the profiles walking and bicycle don't. However changing this setting in the car profile and tapping on "apply to all profiles" also changes it for the walking and bicycle profile.

This also applies to the "Use 2-phase A* routing algorithm" setting.

OsmAnd 3.9.10 and OsmAnd nightly.

**Comment by vshcherb** [comment]
- [ ] "Navigation settings" -> "Route parameters" -> "OsmAnd Live data"
Should be available in all OsmAnd profiles even Public transport
- [x] This also applies to the "Use 2-phase A* routing algorithm" setting. It's correct only for Car routing profiles

**Comment by mnalis** [comment]
@vshcherb I agree that it should, but it also doesn't show for me in OsmAnd `3.9.10` bicycle profile, while it shows in car profile:

![s_Screenshot_20210715_162214_net osmand plus](https://user-images.githubusercontent.com/156656/125804363-fc6ade38-771a-40c1-aa5f-3cae0e73181f.jpg) ![s_Screenshot_20210715_162115_net osmand plus](https://user-images.githubusercontent.com/156656/125804372-6ad030e7-71c7-4aab-ac68-772ca53f3f77.jpg)

**Comment by scaidermern** [comment]
Thanks!

**Comment by dmpr0** [comment]
## Review
- [ ]  "OsmAnd Live data" icon in settings should use profile color if enabled, currently it doesn't change from the default.

**Comment by nazar-kutz** [comment]
PR: https://github.com/osmandapp/OsmAnd/pull/12347
