### ISSUE TITLE
Car mode: speed limit, arrival time icons

### ISSUE THREAD

**Issue by mchapliuk** [osmandapp/Osmand#1210]
On the Car nav screen:

1. The "speed limit" icon is the same as the "current speed" icon. I think it is more intuitive if "speed limit" icon has standard sign and its value inside (red circle with white body and black "speed limit" value)

2. "Arrival time" icon is the same as the "current time" icon. Maybe add "finish" (like chess desk) flag to the "arrival time" icon?

Thanks.

OsmAnd+ 2.0.x
Android 5.1

**Comment by vshcherb** [comment]
1. in 2.0.4 fixed
2. in our plans for 2.1

**Comment by mchapliuk** [comment]
Cool, thanks!
