### ISSUE TITLE
Annoying Notification on slower devices: "Error ocurred while rendering selected area"

### ISSUE THREAD

**Issue by mark-orion** [osmandapp/Osmand#1211]
Omand 2.0.3 is spamming the user with "Error ocurred while rendering selected area" notification popups on slower devices (in this case Samsung Galaxy S3 mini). This happens whenever the map moves or changes. I have used (and I am using) Osmand on the S3 mini for a long time and nothing is wrong with the rendering, but this is a plain pain.
Please find a way to disable this annoying popup.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/issues/1205

**Comment by vshcherb** [comment]
Related issues
