### ISSUE TITLE
Using search works on short part of the name, but fails with longer part of the name

### ISSUE THREAD

**Issue by mnalis** [osmandapp/OsmAnd#12110]
### Description
I'm trying to find `square` with name `Trg Stjepana Radića` at `Martinovka, Zagreb` (this one: https://www.openstreetmap.org/way/618038850).

While starting typing incrementally OsmAnd finds it, but continuing to type it is lost and never shown again.
I would expect

### How to reproduce?
- click `Search` (looking glass icon)
- start typing `trg stjep` and `trg stjepana`: location at `Martinovka, Zagreb` is **found normally**
  ![s_Screenshot_20210704_134953_net osmand plus](https://user-images.githubusercontent.com/156656/125684093-2ba519a1-c54b-481a-bf3d-63543b328c0b.jpg)

- continue typing `trg stjepana ra` and `trg stjepana radića`: location at `Martinovka, Zagreb` disappears from search. 
  **It should not disappear**. 
  ![s_Screenshot_20210704_135006_net osmand plus](https://user-images.githubusercontent.com/156656/125684086-24f33af9-dd2d-4d27-a3c9-2511e1af2169.jpg) ![s_Screenshot_20210704_135020_net osmand plus](https://user-images.githubusercontent.com/156656/125684091-17f901c2-afc4-4574-958d-734e0553d127.jpg)
- even when matching the upper/lowercase as in `Trg Stjepana Radića` it doesn't work (location at `Martinovka, Zagreb`  is not found).  

![s_Screenshot_20210704_135048_net osmand plus](https://user-images.githubusercontent.com/156656/125684056-ed56d05f-1c3b-4d34-bfcd-c0e8660afdbf.jpg)

maybe related: https://github.com/osmandapp/OsmAnd/issues/11467

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: Android 10 (EMUI 11.0.0)
Device model: Huawei P30 Pro

**Maps used (online or offline):**   
Standard maps (vector): Croatia (Jul 1, 2021)

**Comment by alisa911** [comment]
Unable to reproduce the bug. Update to the latest version OsmAnd
<img width="412" alt="Screenshot 2021-08-20 at 15 02 00" src="https://user-images.githubusercontent.com/38911173/130230415-2353c4b2-4a69-4166-9743-73b43d84c13e.png">

**Comment by mnalis** [comment]
@alisa911 That is interesting; what version are you running? Mine is latest version of OsmAnd as available from f-droid.org (3.9.10), on Android 10 phone. I've now also updated to latest Croatia map (Aug 1,2021) but the problem remains the same. 

I also have access to OsmAnd 3.9.7 (f-droid.org version) on other phone (with Android 6.0.1); which does not have that matching favourites; and it exhibits has same problem. I've also tried deleting and installing Croatia map again, with no changes.

**Comment by mnalis** [comment]
**Update** I looked deeper, and it seems that the entry does not disappear, but instead **gets sorted way down in the list** when one starts typing 3rd word `radica`. 

So it is displayed normally at the top (after favourites) as list is sorted by distance from my current map position while I'm typing 1st and 2nd words (`trg stjepana`) but as soon as start typing 3rd word (`radica`) the `Martinovka` location loses its position and gets sorted way down ?? 

Notice in pictures how it correctly displays for `trg stjepana` (`Martinovka, Zagreb, 747m away`) as first building address (after 3 favorites) but when `trg stjepana radica` is typed, it  shows dozen other building addresses (up to `Virje, 83.4km away`) and only then shows our closest building `Martinovka, Zagreb, 747m away`:

![Screenshot_20210823_002148_net osmand plus_s](https://user-images.githubusercontent.com/156656/130372101-1a97e709-5445-4087-9418-a3b225d9b99f.jpg)  ![Screenshot_20210823_002236_net osmand plus_s](https://user-images.githubusercontent.com/156656/130372107-60602412-43dc-478a-99a3-14ef9b949c0b.jpg)

Also other entries (`tunnel`, `square`) seem to start sorting from scratch after buildings, but they have different icon so that might be by design?)

But I see no reason why that building address would be sorted differently than other building addresses (on two of phones I tested, so data corruption is not likely). I also do not understand why it does not happen to you too @alisa911. But it looks like sometimes something is very strange with `sort results by distance from user` logic?

**Comment by alisa911** [comment]
Update OsmAnd to 4.0.6

**Comment by mnalis** [comment]
Thanks for the info @alisa911! 

4.x is not yet available on f-droid (although they seem to [work on it](https://gitlab.com/fdroid/fdroiddata/-/issues/2454)). I don't have google play, so I'll check it out as soon as it becomes available on f-droid.org
