### ISSUE TITLE
No Shields on US motorways - Basemap

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#12117]
No Shields on US motorways - Basemap

Though they are visible on detailed maps
![telegram-cloud-photo-size-4-6016887971107681147-y](https://user-images.githubusercontent.com/1042025/125789909-3a639ebd-f57d-404a-a858-58e6f8011ad3.jpg)

**Comment by xmd5a2** [comment]
Fixed in new basemap
