### ISSUE TITLE
Not searchable via address search: Herne Ottostr. 35

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#12118]
https://www.openstreetmap.org/way/350500589

The address couldn't be found as 1 line search but also couldn't be found via Address search.

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/pull/12544

**Comment by vshcherb** [comment]
Проблемы с ранжированием нет. Все отображается ок. Проблема с показом адресов если зайти внутрь адресного поиска Herne Ottostrasse

NOT OK:
![telegram-cloud-photo-size-4-5888496735611893171-y](https://user-images.githubusercontent.com/1042025/132357866-677f91ab-8feb-4f08-9df3-c8a2324fd500.jpg)

OK:
![telegram-cloud-photo-size-4-5888496735611893173-y](https://user-images.githubusercontent.com/1042025/132357813-8da91b04-19da-4533-b7a1-152212af600b.jpg)
![telegram-cloud-photo-size-4-5888496735611893175-y](https://user-images.githubusercontent.com/1042025/132357829-9e4d8314-ed7f-4973-9a69-70a2c8baf00d.jpg)

**Comment by xmd5a2** [comment]
This is not related to region polygons
![Screenshot_2022-03-16_17-54-48](https://user-images.githubusercontent.com/5829014/160607856-fd3da043-0d8c-40ca-8ec3-ba5d403d8402.png)

**Comment by ivanPyrohivskyi** [comment]
https://www.openstreetmap.org/way/221457835
