### ISSUE TITLE
Incorrect search option for names with number

### ISSUE THREAD

**Issue by Michael21011** [osmandapp/OsmAnd#12123]
### Description
There is special option in search dialog "Show on map"(Показывать на карте in Russian). It allows to see all found POIs on the map.
If search string is started from number (ex. 7 карат) then search dialog proposes another option Extended search by coordinates (Расширенный поиск по координатам in Russian). And there is not a way to show all found POI on map in such case.

### How to reproduce?
Open search doalog.
Enter string for search with leading number, not letter. For example "33 пингвина" w/o quotes. You will see as button Show on map will appear for short period of time and then it will replaced by Advanced search by coordinates.
![Screenshot_2021-07-16-00-54-48-536_net osmand plus](https://user-images.githubusercontent.com/9266780/125862944-79b92cc9-416d-4e9b-bd5b-7bd9789bcac8.jpg)

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: android 11
Device model: M2007J3SG
 
**Maps used (online or offline):**   
It is not related to map

**Comment by Dima-1** [comment]
Should be fixed here:
https://github.com/osmandapp/OsmAnd-resources/pull/744
https://github.com/osmandapp/OsmAnd/pull/13096
