### ISSUE TITLE
change color of current track

### ISSUE THREAD

**Issue by it4workflow** [osmandapp/Osmand#1212]
i upload and display a gpx track i wanted to wander and also record the track. both tracks have the same color. please change the color of the current/record track so that you can see the difference.

**Comment by PalatinateTom** [comment]
Actually Ich miss the same feature as well.

**Comment by vshcherb** [comment]
It is possible to do via custom rendering style

**Comment by PalatinateTom** [comment]
I checked for the custom rendering style, but either I missed something fundamental or
this feature will change the colors for all gpx tracks.
But the point here is - there should be one color for a shown gpx track (which I like to follow) and a different color for the track which is currently recorded.

Greetings, Thomas -> in general a really great app, I use it since years for biking and hiking every week.

**Comment by vshcherb** [comment]
I hope @xmd5a2  (map style developer) could point you how to do it.  I found this one https://github.com/osmandapp/OsmAnd-resources/blob/master/rendering_styles/default.render.xml#L128

**Comment by xmd5a2** [comment]
This can be done this way: "My places" - "My tracks" - track - button at top right (map) - select color

**Comment by PalatinateTom** [comment]
Yes,  thanks a lot, this worked!  However this is really on a almost hidden place. 
Of course there are so many users with different ways of using the app. 
So my 'normal' flow would be to have the map open, tab configure map, gpx,  and in there check the gpx track(s) I would like to see. Maybe the color selection can be added there too? 
Or make the Color selection persistent in the favorites menu? 
Anyway thanks a lot for the quick help!!

**Comment by littlehelper** [comment]
From my point of view this issue can be closed as changing the color of tracks is possible in the way @xmd5a2 explained.

As selecting the width for the currently recorded track is possible (refer to #1410) I would suggest to enable selecting independent track widths for active/visible tracks too.
Should I submit a separate issue for that feature request?

**Comment by ThomasD17** [comment]
The way xmd5a2 explains is not working on iPhone. The select colour option is missing.

**Comment by vshcherb** [comment]
Ios : https://osmand.net/docs/user/navigation/route-line-appearance/
