### ISSUE TITLE
Allow for custom magnification level

### ISSUE THREAD

**Issue by mwerle** [osmandapp/OsmAnd#12125]
# 🚀 feature request

### Description

It would be nice to have an option to magnify the map.  Please note that this is different to ZOOM.

Zooming allows changing the scale of the map, but keeps all screen elements the same size.

Magnification would increase the size of the items rendered on the map. Obviously this would decrease the detail level as less can be displayed at the same time.

The issue being that, especially on smaller screens, it is difficult to read the screen for people who are longsighted.

### Describe the solution you'd like

A setting specifying the magnification. This setting would be a mutliplier applied to all rendered items on the screen (text, map icons,  as well as geographical or navigational items) - the actual interface should not be magnified (or, perhaps, have a separate setting to specify the interface magnification).

### Describe alternatives you've considered

Using a magnifying glass :-P or a larger device (assuming that the larger device shows things larger instead of just showing more)

**Comment by Zero3** [comment]
@mwerle there is already a "magnificiation" setting under `<profile settings> -> Configure map -> Map magnification` (menu names might be slightly different - I'm not using English menus). This setting seems to "magnify" most stuff, like you describe. Is this what you are looking for? Or could you perhaps describe what it is lacking? :)

**Comment by mwerle** [comment]
I'm sorry, I guess I missed it because it's not under "Settings"...  thank you, this is exactly what I was looking for, especially since text magnification can be set independantly from the map magnification.
