### ISSUE TITLE
Wrong text for transit stops with ``shelter`` tag

### ISSUE THREAD

**Issue by Dimitar5555** [osmandapp/OsmAnd#12127]
### Description
Public transit stops which have any value for the ``shelter`` tag show up as "Covered" in OsmAnd.

### How to reproduce?
Select any transit stop that has ``shelter``tag. For example https://www.osm.org/node/676275893
Here is a screenshot from OsmAnd for this stop: https://imgur.com/a/uznZvX8

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: Android 10.0.0
Device model: Honor 20 Lite

**Comment by double-a** [comment]
That is how I would interpret shelter... something with a roof where you are protected from the weather.
What should be shown instead? Especially if shelter is yes and no key covered is available.

**Comment by Dimitar5555** [comment]
It would be better to say "Shelter" and possibly add such icon if there is one. Covered (imo) means that the whole stop is covered which is not the case. There is a separate tag for covered things.

**Comment by sonora** [comment]
I tend to agree that 'covered' is different from 'shelter', I think we should make that distinction.
