### ISSUE TITLE
The icon for "descent" is incorrect

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/OsmAnd#12128]
### Description
The icon for "descent" shows a vehicle that is trying to climb a steep slope, but is rolling backward.
(It does not depict a vehicle that is going down a slope in the forward direction.)

### How to reproduce?
After setting the route, look at the **Details** screen.
While the "Ascend" icon shows the correct movement,
![image](https://user-images.githubusercontent.com/9047168/125957771-b66319fe-219c-43a0-9d34-a3208989b8c8.png)
The "Descend" icon shows a vehicle that is trying to climb a steep slope but is rolling back!
![image](https://user-images.githubusercontent.com/9047168/125957860-93ecf338-30d6-43f0-841b-95bb20bb5452.png)

It should be shown like this:
![image](https://user-images.githubusercontent.com/9047168/125959902-5cedad8e-d516-424e-be63-695a1cabee52.png)

### Your Environment
OsmAnd Version: OsmAnd~4.0.0#32368m (released on 2021-07-16) 

Android/iOS version:
Device model: Asus Zenfone 5z

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by dmpr0** [comment]
Fixed https://github.com/osmandapp/OsmAnd/commit/23f3b5f4acdc790cf6919dca23904605d9eef0d5
