### ISSUE TITLE
Add language string

### ISSUE THREAD

**Issue by franco999** [osmandapp/Osmand#1213]
Let me add a chain of language, a variant of Spanish.

< string name="lang_es-rAR">Español (Argentina)< /string >

**Comment by franco999** [comment]
< string name="lang_es-rAR">Español (Argentina)</string >

**Comment by vshcherb** [comment]
I'm not sure how it is different from Spanish, but dialects are covered by System, you can set Language & Region in Android settings.

**Comment by franco999** [comment]
To know that there is variation in Argentina Spanish language, you need to show in the list of languages.

In Argentina as in the rest of Latin America, there are specific regionalisms for each country.

The "Spanish" section would be used for a general and "Spanish (Argentina)" for the specific Spanish slang of Argentina.
