### ISSUE TITLE
crash after start with new nightly

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#12135]
### Description
crash after install of new nightly (OsmAnd~  4.0.0#32371m.apk 2021-07-17 ) after each restart.
Each restart with remove of regions.ocbf,  ind.cache, itinerary.gpx

Edit: after reinstall of older version OsmAnd~  4.0.0#32346m.apk no more crash.

### Your Environment
OsmAnd Version: OsmAnd~  4.0.0#32371m.apk
Android version:  8.0
Device model: Samsung Galaxy S7 SM-G930F 

[exception.log.zip](https://github.com/osmandapp/OsmAnd/files/6834648/exception.log.zip)

**Comment by MAlfare** [comment]
OsmAnd Version: OsmAnd~ 4.0.0#32370m.apk,  OsmAnd~ 4.0.0#32371m.apk
Android version: 8.0, 4.4, 4.3
Three different devices

OsmAnd~ 4.0.0#32368m.apk is O.K.

So the Problem is introduced in #32369 or #32370

exception log sent via OsmAnd

**Comment by franco999** [comment]
The same thing happens to me with the latest versions.

**Comment by pebogufi** [comment]
Very fast fix. Thanks a lot.
