### ISSUE TITLE
Misleading key shared_string_tones

### ISSUE THREAD

**Issue by Mbodin** [osmandapp/OsmAnd#12149]
### Description
The string key `shared_string_tones` should probably be named something like `unit_metric_tons` given how it is used.

### How to reproduce?
Go to the parameters of the car navigation, and go to the vehicle parameters, then select the weight of the vehicle.
Here is a screenshot:
![Screenshot_2021-07-19-11-21-17-292_net osmand plus](https://user-images.githubusercontent.com/1829786/126136801-d9be9140-6f60-4cf8-b861-71297ebc7e9c.jpg)
In French, the key `shared_string_tones` has been translated by `sonneries` (in the entry box below in the screenshot). In French, “sonneries” means “ringing tones” and not “metric tons”, and I think that the key `shared_string_tones` tricked the translators into this wrong translation.

### Your Environment
OsmAnd Version: OsmAnd~ 3.9.10
Android/iOS version: Android 7.1.2 N2G47H
Device model: Mi Redmi 4X

**Comment by vshcherb** [comment]
Fixed https://github.com/osmandapp/OsmAnd/commit/7aae2770956e547e6162f5916bcd8f297ff46d78
