### ISSUE TITLE
Routing broken when following a pre-made GPX track after update to 4.0.5 iOS

### ISSUE THREAD

**Issue by adegans** [osmandapp/OsmAnd#12140]
### Description
Routing is broken/not working correctly after update 4.0.5 iOS.
Ignores the route and goes in the wrong direction sending me on a stupid route.

Screenshot: https://disk.stor.fit/index.php/s/9XxtqXms5t9Yimo
GPX file: https://disk.stor.fit/index.php/s/ETe6myJDpern8tQ

### How to reproduce?
Display a track, using routing/navigation start to follow it - Review the blue route over the red track line. See it broken...

Same files as before, now they do not work. Did used to work on previous versions.

### Your Environment
OsmAnd Version: 4.0.5
Android/iOS version: iOS 14.newest
Device model: iPhone 7 Plus

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd-iOS/issues/1370

**Comment by adegans** [comment]
You merged this, but it's a separate issue from #1370.

**Comment by vshcherb** [comment]
Same functionality, so it's better to have as 1 issue for now, until it's fixed

**Comment by adegans** [comment]
This now also happens on Osmand 4 on Android.

**Comment by adegans** [comment]
I finally figured it out...
The wacky routing is because of track segments.
Every start and end of segments is added to the route calculation causing me to be sent all over town in straight lines.
First the route seems to nagivate find, then at the end a 'straight-line' route is tacked on between all start and end points from all segments. 

When I edit the GPX and combine all segments in one long segment this does not happen.
In my test I also have to convert Lines to tracks and merge those into the main/primary track as well.

Then everything works perfectly fine.

This behavior happens on both iOS and Android versions of Osmand.
Please someone have a look for a near future fix.
