### ISSUE TITLE
Track name doesn't updates after renaming

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#12153]
## Review 2
- [x]  Track > Options > Rename > open keyboard when bottom sheet opens.

## Review
- [x]  Renaming allows to add spaces before the name `"      name.gpx" `

## ToDo
I have created the new track in Plan a Route, save it with the default "date" name, select it from the map > rename > enter a new name, new track name shows up only after menu reopening.

**Comment by cepprice** [comment]
https://github.com/osmandapp/OsmAnd/pull/12429
