### ISSUE TITLE
Online photos got lost when screen is rotated

### ISSUE THREAD

**Issue by MakiWolf** [osmandapp/OsmAnd#12154]
### Description
online photos got lost when screen is rotated

### How to reproduce?
Open a poi with wikimedia commons photos and rotate screen
The online photos are lost
Workaround: When you close the poi and open it again the photos are here

For example I used this poi [https://www.openstreetmap.org/node/2459904780](https://www.openstreetmap.org/node/2459904780)

![issue](https://user-images.githubusercontent.com/73300633/126192035-46bf4c6b-feab-49ee-b515-423a8c79e708.gif)

### Your Environment
OsmAnd Version: 3.9.10 and latest build from source (19.07.21)
Android/iOS version: 9
Device model: Galaxy Note 8 and Android Studio Emulator (Device Nexus 10 API 30)

**Comment by scaidermern** [comment]
Same problem for OpenPlaceReviews photos.

**Comment by dmpr0** [comment]
In Landscape orientation, if "Online photos" were previously expanded, they will be cropped at the bottom.

https://user-images.githubusercontent.com/9365308/129567961-56c460f6-532b-4cf9-bf8b-7f165f4ce029.mp4
