### ISSUE TITLE
Blocked by google play protect message during install

### ISSUE THREAD

**Issue by monterrr** [osmandapp/OsmAnd#12160]
### Description

The app is being blocked during installation from f-droid by google play protect, there is an option to still continue with the installation or the OK to abort. 

### How to reproduce?
Install OsmAnd app from f-droid.
Play protect message error shows up during the installation.

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: Android 11
Device model: Poco X3 Pro

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by vshcherb** [comment]
You've installed version without google play services and google starts "protection" for any app that doesn't use google play services to request location
