### ISSUE TITLE
Incorrect address displaying in the Wenham, MA, USA

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#12167]
### Description
OsmAnd displays some addresses incorrectly in Wenham, MA, USA.

### How to reproduce?
Check this address: 42.60256° N, 70.87598° W

https://www.openstreetmap.org/way/217072136#map=19/42.60252/-70.87603&layers=C
![image](https://user-images.githubusercontent.com/80623554/126324299-e2799479-0f22-4669-8851-cc65cc11fcaa.png)
![image](https://user-images.githubusercontent.com/80623554/126325221-ecb5cbe3-eb4b-4a60-8462-b6a4fa706252.png)
![image](https://user-images.githubusercontent.com/80623554/126324346-a82a6ed8-fa9f-4d58-b0b7-586814817f25.png)

**Comment by alisa911** [comment]
Need to fix map, add point town for Wenham
