### ISSUE TITLE
[Voice instructions] don't say ref attribute if the road is not very important

### ISSUE THREAD

**Issue by qwerty287** [osmandapp/OsmAnd#12171]
### Description 
OsmAnd's voice instructions always speaks the [ref attribute](https://wiki.openstreetmap.org/wiki/Key:ref) for roads if it's available. If the road is a highway or another important street ([`highway=motorway`](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dmotorway), [`highway=trunk`](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtrunk) or  [`highway=primary`](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dprimary) as OSM tag), this is very useful. But if it's something else, you probably can't use these numbers, because they are actually not shown in reality (at least in Germany). As an example: https://www.openstreetmap.org/way/221808444 - OsmAnd would say "K 6422 Eggersdorfer Strasse", which is very long and annoying. So it would be nice if OsmAnd wouldn't say them if the road is not very important (but show it with the street name in the top bar). Maybe, as an exception, it could be used if the road doesn't have another name. As I don't know how this is in other countries, there could be an option to change it (with values like "always", "only important roads" and "never").

Thank you!

**Comment by quax2712** [comment]
This is a very good idea, the ref attribute for tertiary and residential streets is not shown on signs in Germany. If possible, it should be set using new setup options.

**Comment by sonora** [comment]
This is a country by country decision, in e.g. the US the use of highway numbers is very predominant down to the county road level (which is equivalent to the level you report here should be suppressed for Germany).

I am a strong believer in delivering software usefully configurd out of thd box. This means that for such a fundamental functionality we should not simply suppress something esential, and burden the user to find a setting and change it.

Hence I suggest the only fix can be we introduce a cut-off level above which refs are conventionally used, and then intrinsically set it per country. Until ee have that, or a similar algorithm,I am afraid we should leave things as they are?
