### ISSUE TITLE
Disappearing track from the map

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#12178]
When I set a track for navigation, it disappearing from the map. See video from telegram for details.
https://t.me/ruosmand/75163

OsmAnd Version: 4.0.0#32392
Android: 11
Device model: poco x3 pro

**Comment by scaidermern** [comment]
Sound similar to #12242.

**Comment by vshcherb** [comment]
- During navigation it should be possible to see **both** Track of navigation and Navigation line 
- After navigation Track of navigation (if it's switched on as display on map) should be visible on Map (fixed)
- If User has Route preparation menu open it is fine that Track of navigation is not displayed and only Navigation line is displayed
