### ISSUE TITLE
Reconsider new subscription model and prices

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#12181]
It looks like there are new subscription models with a huge price increase, especially for (hourly) live updates:

![photo_2021-07-21_07-38-42](https://user-images.githubusercontent.com/1040784/126436948-6c5a0b64-9efa-4c64-b98f-2d0c0e78ce95.jpg)

I guess you have valid reasons for this price increase since infrastructure and labor won't come for free. However please consider that many mappers "need" the OsmAnd live feature. It allows them to efficiently contribute to OpenStreetMap by having up-to-date map data. This avoids creating duplicated POIs and enables mappers to instantly differentiate between current and outdated information.

While most mappers "need" OsmAnd live, many of them won't need the OsmAnd cloud feature. The OsmAnd cloud feature is probably the one which contributed to this price increase I guess.

Please take into account that active mappers are the one big reason why OpenStreetMap and OsmAnd are a big success. Without them, OsmAnd wouldn't exist and won't survive. Give mappers a chance to use your live feature without having to pay a huge amount of money. Otherwise there is the possibility that map edits and map quality will decrease, thus making OsmAnd less useful.

There are several options to solve this conflict:

- Move the hourly map update feature from the pro version to the plus version
- Alternatively, reduce the price for the pro version
- Alternatively, offer a third subscription model including the plus features and the live update feature
- Alternatively, offer a discount or free live update feature for active mappers (mappers with a certain number of edits per year or a certain number of active mapping days per year)

**Comment by DP24PH** [comment]
As a mapper myself and Civil Engineering student, I would like to reconsider the option to offer either discounted or free live update feature since it would be only the way to validate the edit in a timely manner. Likewise, it would rather incentivize the active mappers' contribution as well to maintain the quality of the OSM-based database.
