### ISSUE TITLE
Voice routing: announce next street / ref

### ISSUE THREAD

**Issue by quax2712** [osmandapp/OsmAnd#12180]
The nightly version has a problem with street name and ref attribute.
If turning into a street thas has no ref attribute or no name as it is a highway=track, the voice tells the street name and ref from the treet driving on, it is very confusing. It would be a very helpfull information if the voice could tell the highway type ... turn on cycleway , or turn on track.

greetings
Rainer

**Comment by vshcherb** [comment]
Please share an example (coordinates) to double check and understand details

**Comment by quax2712** [comment]
Here is my example, this is a ref problem.
![ref problem](https://user-images.githubusercontent.com/42236280/126517136-90cf4ecb-b12b-401b-9ea0-c91f55e9314d.jpg)

https://www.openstreetmap.org/#map=17/49.38725/8.63341

**Comment by issteve** [comment]
Same problem here with OSMand+ 4.0.5 in German, especially annoying at streets splitting up. E.g. try this one in the app: https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=48.0527%2C7.8628%3B48.0622%2C7.8703#map=16/48.0575/7.8670 
or 
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=48.11696%2C7.87185%3B48.11459%2C7.87311 (Coming already on K5101, instead of "turning right on Parkweg" it says "turning right on K5101 Parkweg".

**Comment by franco999** [comment]
Same problem here. It's annoying and very confusing. 
If the destination street to turn on is not labeled "ref", it should not say "turn on {ref} {name}", because the "ref" referred to in that case is to the road you are driving on and not the road on which the turn is to be made. 
I don't know if this is understood.

**Comment by ivanPyrohivskyi** [comment]
Recheck tests https://github.com/osmandapp/OsmAnd/issues/11778#issuecomment-872246162

# #3181
http://www.openstreetmap.org/way/191799180
<details><summary>From 47.80970, 12.12140 to 47.80840, 12.11240</summary>
<img src="https://user-images.githubusercontent.com/1040293/131990782-37884aa7-0646-4fdc-b39d-8aea63451de7.png" width="300"/>
<img src="https://user-images.githubusercontent.com/1040293/131991057-8a186c54-7966-465a-9ff4-2fe3fc476049.png" width="300"/>
<img src="https://user-images.githubusercontent.com/1040293/131991122-ff625fd2-3a45-436f-9f40-0cba32f95c73.png" width="300"/>
</details>

TTS:
The trip is about 1 kilometer time is  3 minutes. 
in 200 meters, turn left **onto B 15** toward München, Innsbruck , then  keep left
turn left **onto B 15** Rosenheimer Strasse , then  in 40 meters, turn left
turn left toward München, Innsbruck
Continue for 500 meters on A 8 and arrive at your destination 
You have reached your destination Ring 8, Bad Feilnbach

In the old TTS:
turn left onto Rosenheimer Strasse **toward B 15**, München, Innsbruck, then in 40 meters, turn left
But "B 15" is a ref of Rosenheimer Strasse! So part of old TTS was wrong.

https://www.openstreetmap.org/way/24711338
<details><summary>From 47.80180, 12.16250 to 47.80509, 12.15064</summary>
<img src="https://user-images.githubusercontent.com/1040293/131993155-e5282d54-f4d7-4882-8524-fce090f45889.png" width="300" />
<img src="https://user-images.githubusercontent.com/1040293/131993234-3f26f456-5c16-47df-b7d6-0042e68cc710.png" width="300" />
</details>

TTS:
The trip is about 1 kilometer time is  one minute. 
take the second exit onto St 2359 toward München, Rosenheim, Thansau
**turn left toward München**
Continue for 800 meters on A 8 and arrive at your destination 
You have reached your destination Ring 8, Bad Feilnbach

In the old TTS:
turn left **on St 2359** toward München
But we already was on "St 2359"! So part of old TTS was wrong.

**Comment by ivanPyrohivskyi** [comment]
Test Parkweg

https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=48.11696%2C7.87185%3B48.11459%2C7.87311#map=18/48.11580/7.87290
<details><summary>from 48.1170, 7.8718 to 48.11451, 7.87273</summary>
<img src="https://user-images.githubusercontent.com/1040293/131994501-7027739f-3187-4068-a472-9f687de6fdcc.png" width="300" />
<img src="https://user-images.githubusercontent.com/1040293/131994942-c9df13c2-38a3-4c63-9927-60a0b870cd80.png" width="300" />
</details>

TTS:
The trip is 400 meters time is less than a minute. 
in 300 meters, turn right onto  Parkweg
turn right onto  Parkweg then 
Continue for 100 meters and arrive at your destination 
You have reached your destination Parkweg (Windenreute), Emmendingen

**Comment by ivanPyrohivskyi** [comment]
Test B3, B294

https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=48.0527%2C7.8628%3B48.0622%2C7.8703#map=16/48.0575/7.8670

<details><summary>From 48.0527, 7.8628 to 48.0622, 7.8703</summary>
<img src="https://user-images.githubusercontent.com/1040293/131996969-252f04cf-048e-48ca-86ca-c2c5b746a5ce.png" width="300" />
<img src="https://user-images.githubusercontent.com/1040293/131996988-9dd2b8fe-38f5-42bb-843f-4840d47972cc.png" width="300" />
</details>

TTS:
The trip is about 1 kilometer time is  one minute. 
in 600 meters, turn slightly left on B 3, B 294 
turn slightly left on B 3, B 294 
Continue for 350 meters on B 3 and arrive at your destination 
You have reached your destination B 3

**Comment by ivanPyrohivskyi** [comment]
Additionally fixed shield icon in top navigation panel
<img src="https://user-images.githubusercontent.com/1040293/132004391-9937cd22-3e5a-48b7-a80c-68eae90959da.png" width="300" />

<img src="https://user-images.githubusercontent.com/1040293/132004393-42aaaf83-703a-47e1-8e42-b0d5f1fd6191.png" width="300" />
<img src="https://user-images.githubusercontent.com/1040293/132004395-600df122-f7b0-4dc7-849a-863731db4f77.png" width="300" />

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd/pull/12667

**Comment by vshcherb** [comment]
1 more issue to check https://github.com/osmandapp/OsmAnd/issues/12670

**Comment by issteve** [comment]
Thank you for all your efforts! The Test Parkweg example looks perfect. 
Just...

> Test B3, B294
> 
> https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=48.0527%2C7.8628%3B48.0622%2C7.8703#map=16/48.0575/7.8670
> From 48.0527, 7.8628 to 48.0622, 7.8703
> 
> TTS:
> The trip is about 1 kilometer time is one minute.
> in 600 meters, turn slightly left on B 3, B 294
> turn slightly left on B 3, B 294
> Continue for 350 meters on B 3 and arrive at your destination
> You have reached your destination B 3

... is still confusing. It's a street with two names for a while which splits up again in two separate ones. For going in the right direction it shouldn't announce the wrong one together with the right one. So it should only say:
" ... 
in 600 meters, turn slightly left on B 3.
turn slightly left on B 3.
..."

I did check: https://www.openstreetmap.org/way/29441246 for the correct label (only "B3" instead of "B3,B294") and yes it is correctly labeled only "B3" for over a year now. So I have no idea why your test says "turn slightly left on B 3, B 294" instead of "turn slightly left on B 3."

Thank you very much for investigating and fixing this!

**Comment by ivanPyrohivskyi** [comment]
> So could it be related to this node https://www.openstreetmap.org/node/264616481 which connects the streets?

Yes, are right and gave me right direction. Thanks.

New test B3, B294
<details><summary>From 48.0527, 7.8628 to 48.0622, 7.8703</summary>
<img src="https://user-images.githubusercontent.com/1040293/132187580-3f0ce7b8-8f39-424a-965c-ea37304fe074.png" width="300" />
<img src="https://user-images.githubusercontent.com/1040293/132187666-07e27b89-14c2-4d32-844e-c055e740e1df.png" width="300" />
</details>
The trip is about 1 kilometer time is  one minute. 
in 600 meters, turn slightly left onto B 3 
turn slightly left onto B 3 
Continue for 350 meters on B 3 and arrive at your destination 
You have reached your destination B 3

Recheck tests with exit points
#11778 - is OK
#3289 - is OK

**Comment by ivanPyrohivskyi** [comment]
> 1 more issue to check #12670

Test Shankland Road
<details><summary>From 41.61831° N, 81.42414° W to 41.62506° N, 81.41933° W</summary>
<img src="https://user-images.githubusercontent.com/1040293/132192425-454718a5-505b-462e-b243-45966b160020.png" width="300" />
<img src="https://user-images.githubusercontent.com/1040293/132192519-29959914-9e38-4023-852d-86f3b5d64888.png" width="300" />
<img src="https://user-images.githubusercontent.com/1040293/132192579-36421242-c70d-468c-917f-2151bc0c750e.png" width="300" />
</details>

TTS:
The trip is 900 meters time is  2 minutes. 
in 4 tenths of a mile, turn left onto  Shankland Road
turn left onto  Shankland Road
Continue for 2 tenths of a mile on  Shankland Road and arrive at your destination 
You have reached your destination Shankland Road, Willoughby

**Comment by vshcherb** [comment]
Looks like widget of the next street turn is broken now https://docs.osmand.net/en/main@latest/osmand/widgets/nav-widgets#street-name
