### ISSUE TITLE
Osman crashes in Route- Options

### ISSUE THREAD

**Issue by MAlfare** [osmandapp/OsmAnd#12192]
Three different devices,
Android 4.3, 4.4, 78.1

At least since OsmAnd~ 4.0.0#32368m
At least until OsmAnd~ 4.0.0#32392m

Create a route, tap on "Options", tap on "Display along the route" (in German: Entlag der Route anzeigen",-> Osmand~ was terminated.

file:///home/alf/TEMP/exception.log

**Comment by sonora** [comment]
Confirmed, it's an NPE, here is the log: 
[exception.log.txt](https://github.com/osmandapp/OsmAnd/files/6858205/exception.log.txt)
