### ISSUE TITLE
Irritating Behaviour on tapping Track Waypoints

### ISSUE THREAD

**Issue by kreuzschnabel** [osmandapp/OsmAnd#12205]
In previous versions, I could always tap a previously set waypoint on the current tracking to re-edit or even delete it. The editor window just opened again.

In the latest version, when I tap the red dot, I just get a pop-up message (German version) "Modul für Bedienungshilfen: Ziel ist nicht festgelegt". 

Would be nice to be able to re-edit waypoints again. I often add additional information on path properties this way.

OsmAnd Version: still OsmAnd+ 3.9.10
Android/iOS version: Android 11 (Lineage 18.1)
Device model: OnePlus 5T
Latest offline maps, OsmAnd Live maps enabled

--ks

**Comment by scaidermern** [comment]
> In the latest version, when I tap the red dot, I just get a pop-up message (German version) "Modul für Bedienungshilfen: Ziel ist nicht festgelegt".

Sounds like you have the accessibility plugin (German: Bedienungshilfen) activated. Try to disable it.

**Comment by sonora** [comment]
Exactly, see e.g. #10030 and #10920.

**Comment by kreuzschnabel** [comment]
Thanks, solved. However, I don’t remember activating the accessibility plugin :-/

--ks

**Comment by scaidermern** [comment]
> Thanks, solved. However, I don’t remember activating the accessibility plugin :-/

You are not alone. This problem comes up regularly, both here on GitHub and on the Telegram channel.

I already suggested to improve the toast message, making it more obvious that this behaviour is related to the accessibility plugin. But no change so far.

**Comment by sonora** [comment]
Yes, since we have a number of issues about this very behavior, quite possible that we had or have some erratic activation of this plugin. Need to observe that. Hard to act as long as we cannot reproduce.
