### ISSUE TITLE
cycling voice prompt arrival annoucement (final warning before a turn) comes either after the turn or during it

### ISSUE THREAD

**Issue by gazzawazza** [osmandapp/OsmAnd#12207]
Hi

Hope you can help on this.

### Description
the final voice turn instruction/warning comes far too late when cycling.

It either comes AFTER i've turned or literally during the turn.

### How to reproduce?
phone is in flightmode (to conserve battery), with location active (improve accuracy is NOT active + google location accuracy was seemingly on - i normally actually have this turned off to again conserve power).

Power mode is optimised (to allow background GPS checks).

**screen is OFF** (I've no phone mounting on my bike)

I've imported a GPX track and am navigating to follow this track.

I've tried changing both the "arrival announcement" to "early" (from normal) and i've tinkered with the default cycle speeds (i've reduced them to be more realistic for my cycle speed). **No changes have made any difference - the final navigation instruction comes too late.**

I was cycling at night, so was in night mode (think it changed automatically)

I don't understand why the arrival announcement adjustment didn't seem to make any difference. This surely is the configuration setting i needed. The explanation for the announcement time says it depends on the prompt, current speed and default speeds. I would have thought i would have seen some movement in announcement time by changing it.

tbh i didn't rigorously check the impact of my changes. I 'think' the early warnings of a turn 'might' have come earlier but maybe i was just 'hearing' the change i'd made. I'm confident though that the final turn instruction was just as late.

I expect i'm going something wrong but would be grateful for this to be reviewed.

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: android 9
Device model: samsung S8

**Maps used (online or offline):**   
offline

i'm not sure which map i'm using in this exact instance. It says Mapillary top right though.

The maps i picked for my installation are 4 vector maps
- england east of england (1 feb 2021)
- england greater london (1 feb 2021)
- england south east (1 feb 2021)
- world basemap mini (10 Jun 2020)

then i have 3 "online and cached tile maps"
- hike bike map
- hike bike map (hills underlay)
- osmand (online tiles)

i'm assuming i've been using the vector maps in offline mode. I would have been using the england greater london map last night.

regards,

Gary

**Comment by vshcherb** [comment]
With 4.0 release you should be able to see at what time announcement should happen and you should definitely see how each of the changes will affect the distance
