### ISSUE TITLE
Native rendering unable to render "road only" maps

### ISSUE THREAD

**Issue by aaSSfxxx** [osmandapp/Osmand#1220]
Hello,

When using native map rendering, "road only" downloaded maps don't render at all (full maps are rendering as excepted), whereas java (slow!) rendering render them properly.

Unfortunately I didn't find anything interesting in the logcat so I can't investigate further.

I'm using OsmAnd~ 2.0.4 from F-Droid, build 207 (build which fixed native rendering not working at all)

**Comment by vshcherb** [comment]
The issue confirmed and it was broken for more than 3 months

**Comment by vshcherb** [comment]
Fixed
