### ISSUE TITLE
Opening osm.org links

### ISSUE THREAD

**Issue by beatnickgr** [osmandapp/OsmAnd#12202]
Clicking on links such as 
https://www.openstreetmap.org/way/?????????
https://osm.org/way/?????????
are expected to open in osmand~ (currently opening in browser) and search if the ID is already downloaded.

1) If the ID is downloaded, then display the object.
2) If the ID is not downloaded then retrieve the ID.
      a) If the ID is an already downloaded map, then offer to **live update** the map or show in browser.
      b) Else, offer to **download** the respective map or show in browser.

**Comment by vshcherb** [comment]
Unfortunately not supported for now. And probably could be supported only with Internet connection only.

**Comment by beatnickgr** [comment]
When offline, on any POI, i tap details and it shows the link including the ID. I therefore assume this feature could work without internet in case 1 (most of the cases).

For case 2 it will need internet indeed, but if we're offline it can simply show "Downloads not found, please check your connection to the Internet". This is the message which already appears when trying to download maps when offline.

**Comment by beatnickgr** [comment]
It's been more than 2 years that I'm waiting, am I the only one seeing this as a useful feature?
My friends are sending me goo.gl links and I cannot reply them that links to osm.org can also works.
I'm an osm cartographer and people cannot get directions to what I've mapped!

**Comment by vshcherb** [comment]
We can't support this feature with offline maps cause we don't have index by ID, so it's easier to open this url online and copy url to OsmAnd search...

**Comment by beatnickgr** [comment]
OK I see the problem is elsewhere, pasting that URL in the OsmAnd~ search works for you but not for me. I'm opening a ticket for the specific issue. #18386

**Comment by vshcherb** [comment]
Instead of 
https://www.openstreetmap.org/way/5013364
You can use this 
https://www.openstreetmap.org/way/5013364#map=18/48.85852/2.29490

We can't support this feature as our goal offline maps
