### ISSUE TITLE
Favoriten Backup

### ISSUE THREAD

**Issue by anten1222** [osmandapp/OsmAnd#12203]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please do not file questions or support requests on the GitHub issues tracker.

In case you aren't sure whether to open an issue or not, please send your request to support@osmand.net.

You can get your questions answered using the [Google group](https://groups.google.com/forum/#!forum/osmand) or chat in real-time via our Telegram instances: [English](https://t.me/OsmAndMaps), [German](https://t.me/deosmand), [French](https://t.me/frosmand), [Ukrainian](https://t.me/uaosmand), [Italian](https://t.me/itosmand), [Russian](https://t.me/ruosmand).

Osmand creates a backup for the favorites.  Now I wanted to restore the data.  Unfortunately it was not possible for me because I couldn't find a program on the smartphone or in the playstore that can decompose bz2

**Comment by scaidermern** [comment]
Maybe OsmAnd should offer to open these bz2 files directly.
Or favourite backups should get stored uncompressed since they aren't very large (compared to offline maps etc.).
Or OsmAnd should have an internal mechanism to restore favourites from one of the backups.
