### ISSUE TITLE
[BUG] custom POI search returns no results until Find More is pressed

### ISSUE THREAD

**Issue by stephan75** [osmandapp/Osmand#1221]
Transferred from: https://groups.google.com/d/topic/osmand/JkysH9njqTs/discussion

Have any offline vector map in Osmand.

Long press on the map where you know that POIs like restaurants are located, and tap the popup.

Choose "Search near here", go to POI search select the 3 dots for custom filter search.

Select any categories that you know are nearby, for example "Food" that includes restaurants etc. and select at least restaurants etc.

Press close, press the checkmark at upper right corner.

The results list is blank, and the search radius is 31.1 miles or 50 km.

Press "Find More".  The search radius expands to 62 miles (100 km) and results appear, including the ones only a few dozen feet away.

While in normal POI search from pre-defined categories given by Osmand, search starts from 1 km radius, and all POIs are present in the listing, including opening hours etc.

Also when defining an own custom filter and save that filter with the star symbol and give it an own name, POI search is done i´with 1 km radius, and all POIs nearby are fine.

Confirmed bug in Osmand nightly 2.1.0 #11097M from 13-05-2015.

PS:
Also when having defined a custom filter and saved via the star symbol, and then selecting the three dots for custom search, scroll down in categories there to "User defined" ... no content there!!

**Comment by aceman444** [comment]
Confirming in 2.0.4.

**Comment by vshcherb** [comment]
Fixed
