### ISSUE TITLE
Track coloring by slope only partially working

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#12213]
For some tracks, coloring by slope doesn't work at all. For others, only parts of the track get colored.

Left screen: The left part is not colored, only the right part.
Right screen: No coloring at all.
![track_slopes](https://user-images.githubusercontent.com/1040784/126748889-e0b08797-489e-49bd-836a-a14c2f63aeb5.jpg)

Left track: [B Starnberg Pilsensee.gpx](https://github.com/osmandapp/OsmAnd/files/6867112/B.Starnberg.Pilsensee.gpx.txt)
Right track: [B Wörthsee Starnberg.gpx](https://github.com/osmandapp/OsmAnd/files/6867114/B.Worthsee.Starnberg.gpx.txt)

Both tracks have been created by OsmAnd (with match to road). However I have also third-party tracks for which the coloring either works or doesn't work.

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd/pull/12287

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd/pull/12288 for r4.0

**Comment by dmpr0** [comment]
- [ ]  Use the same grey color (that we use for undefined slope parts) for other types of colorization if data about road type or surface is unavailable.

**Comment by cepprice** [comment]
https://github.com/osmandapp/OsmAnd/pull/12446
