### ISSUE TITLE
online routing OSRM Graphhopper - two points only are used

### ISSUE THREAD

**Issue by mariush444** [osmandapp/OsmAnd#12210]
# 🐞 routing report

### Routing engine

- [ ] OsmAnd's in-app offline routing
- [x] Any online routing provider (YOURS, OpenRouteService, OSRM, etc.)

### Routing Profile

car

### Start and end points

Only start and end point is used to calculate route, any additional point in the middle of the route is ignored.
Osmand doesn't send the points to online engine.

example for OSRM
`http://router.project-osrm.org/route/v1/car/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219?overview=true`

example for GraphHopper
`https://graphhopper.com/api/1/route?point=13.388,52.517&point=13.397,52.529&point=13.428,52.523&vehicle=car`

## 🌍 Your Environment

**OsmAnd Version:**

3.9.10

**Device and Android/iOS version:**
Android 8.0
**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**
![image](https://user-images.githubusercontent.com/66887280/126715373-80e0c8d8-e130-483a-8f06-efa5a290c862.png)

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/pull/12385

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/pull/12385
