### ISSUE TITLE
Azimut on screen

### ISSUE THREAD

**Issue by miramikes** [osmandapp/OsmAnd#12219]
Hello,
I like a lot "Radius ruler" on screen when I move a map I immediately see distance to the new place I've moved map.
That's great !!! I would like to also see Azimut ( angle to this new place ) It would be incredible useful for me especially on seakayak, but definitely elsewhere too.
It could be implemented as "Radius ruler" improvement or as separated widget. 
best regards
mira

**Comment by vshcherb** [comment]
It's already implemented as blue triangle - https://docs.osmand.net/en/main@latest/osmand/widgets/radius-ruler#compass-ruler-for-radius-ruler-widget

**Comment by miramikes** [comment]
This is not working on my device probably due to missing compass sensor on my Xiaomi Redmi 9 :(
Is it really necessary to have compass sensor present to get this feature working?

**Comment by vshcherb** [comment]
Good question, no it's not needed but then it's part of another widget not a radius ruler
