### ISSUE TITLE
Crash in Plan route when you try to change the navigation type of the route

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#12221]
### Description
The application crashes when you try to change the navigation type and recalculate the route.

### How to reproduce?
Show track on the map->press Edit->press navigation type icon to recalculate the route for another type and application is crashes
[exception (3).log](https://github.com/osmandapp/OsmAnd/files/6868881/exception.3.log)
.

### Your Environment
OsmAnd Version: 4.0.1
Android/iOS version: Android 9
Device model: Experience XZ I

**Maps used (online or offline):**   offline
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/12215
