### ISSUE TITLE
Route recalculated while riding makes no sense

### ISSUE THREAD

**Issue by Siron777** [osmandapp/OsmAnd#12225]
Hi,

Sometime when the route is recalculated while I am riding (mode bike), because I don't follow always the route OsmAnd is planning for me, the new recomputed route is a mess. It is making me some kind of multiple useless round trips between points I am supposed to pass not far away. It did happen during my last trip (see pictures) and the trip before. Those two trips were with multiple way-points. Due to that bug, when it occurs, I just ignore the proposed route and use OsmAnd only like a indication of the direction to follow. At some point, after multiple recomputation of the route I am not following, the bug will disappear and the proposed route will make sense.

![wrong path 1](https://user-images.githubusercontent.com/15027951/126834151-8d1f6a1a-36ec-49c8-a293-c0aecfe3e875.jpg)
![wrong path 2](https://user-images.githubusercontent.com/15027951/126834156-975e0978-58a8-4644-8f17-1a64adf02f15.jpg)

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: Android 11
Device model: Samsung Galaxy A51

**Maps used (online or offline):**   
Belgium map, Jun 1, 2020

**Comment by vshcherb** [comment]
Is it standard OsmAnd navigation between intermediate points or GPX navigation. Definitely looks weird

**Comment by Siron777** [comment]
It is standard OsmAnd navigation. Its always during a route recalculation while riding. I don't remember having seen that when planing the trip. I did use OsmAnd in France 3 months ago, with also waypoints, I do not remember seeing that bug.

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/pull/12361

**Comment by vshcherb** [comment]
Please test release 4.0

**Comment by Siron777** [comment]
I did a ride today with the 4,0,4, and I got again the issue one time. I did go off  the path (about 5 meters) for 2 minutes, to do a break, then a route was recomputed, and it wanted me to go back to the way-point 1, way-point I already passed.
![wrong path 3](https://user-images.githubusercontent.com/15027951/129264041-be3dc3a8-922c-4183-8703-0badefdeeb05.jpg)

To get rid of the wrong route, I had to remove the way-point 1 from my destination list.

**Comment by vshcherb** [comment]
That's a different issue looks like. This is about some "service interruption" cause it should automatically delete points once you pass them but if it didn't delete then point will be "forever stuck".
So looks like first issue is fixed but there another one.
