### ISSUE TITLE
Trip details "spectrograph" details are unreadable with dark theme

### ISSUE THREAD

**Issue by jsawesome1** [osmandapp/OsmAnd#12228]
### Description
When preparing to start a trip, if you expand the "Details" area and expand any of the three "spectrographs" (Road type, Surface, or Steepness) the name of what each color represents are almost the same color as the background, and can't be read.

![Screenshot_20210723-235821_OsmAnd~](https://user-images.githubusercontent.com/26128926/126857086-b648a5cd-cfdf-49b3-afa1-fb848007c7c3.jpg)
![Screenshot_20210723-235807_OsmAnd~](https://user-images.githubusercontent.com/26128926/126857089-47ddbca9-2e16-403b-992e-37f66b02fc8b.jpg)

### How to reproduce?
Set the Map mode in whichever profile to sunrise/sunset.
Set the App Theme to Dark.
Input a starting point and destination into the trip menu.
View the trip details.
Expand the legend for any of the three "spectrographs" (Road type, Surface, or Steepness)

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: Android 10
Device model: SM-G960U

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
I don't think this is the issue, but for completeness sake: Us_new-york_northamerica, June 30, 2021

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/11269
