### ISSUE TITLE
Confusing duplicate items in POI overlay chooser

### ISSUE THREAD

**Issue by snouup** [osmandapp/OsmAnd#12229]
### Description

There are a few ways to get a POI type listed in the POI overlay chooser:

1. Inspecting a POI on the map temporarily adds it's POI type to the list, only until you restart osmand
2. Adding POI type to list of search categories (via Search -> Save filter as) adds it permanently
3. Sometimes, just doing a search will add one temporarily I think. Not quiet sure how/when

Often after adding a new poi type to categories, I see a duplicate entry in the poi chooser, which at first glance looks like a bug, especially when the duplicate disappears on a restart.

Possible improvements
- hide duplicate
- differentiate implicitly added poi types somehow, communicate what's going on - maybe a separate section titled "recent" containing the X most recent items?
- or don't implicitly add pois at all? (Did anyone ask for it? I personally could do without...)

### How to reproduce?

Inspect some poi
Search for its type, save filter
Check duplicate in poi overlay list

### Your Environment
OsmAnd Version: OsmAnd~ 3.9.10

**Comment by sonora** [comment]
Side note: Also here, just like for tracks, we have the issue that the POI Overlay dialog overlaps in functionality with our search screen, thus duplicating the set of possible bugs and behavioural issues.

Before fixing either one, maybe it is worth to try to unify to just one dialog, throw the other one out, then start fixing issues?

**Comment by snouup** [comment]
Oof, I don't know. The Search is already one of the most complex dialogs in osmand, do we want to make it more complicated?
As for me, I'm grateful for the quick and clean access to poi overlay from profile settings. Sometimes I'll switch some poi on/off on the fly, much quicker than maintaining yet another profile.

**Comment by sonora** [comment]
The Search screen could simply sport an additional tab of things currently displayed, or perhaps we can even put that on the existing Categories tab.

Even today, from the POI Overlay's screen we already link to the Search's Category tab, which shows how closely related this is.

There may be little logical justification to keep the POI Overlay as a separate screen. Plus, we are a little inconsistent, as you note in this issue, showcasing in one place which items and serach results a user currently picked to be displayed, and without duplicates.

**Comment by snouup** [comment]
I'm warming up to it. Allow me some counterpoints still:

- Profile quick section mainly affects the display of map (map style, shown details, etc.) Poi overlay fits into this as a substantial part of display (assuming you show enough poi's). For me that section is all about changing what I _see_
- Search screen can be more of a customisation tool that is used beforehand (before a trip), making custom filters for later use, or search for specific poi to bookmark it. I think of that screen as allowing me to change my _toolbox_ that I will later use. Yes, there are a few operations breaking this model, but overall it fits.

I kind of like that two step approach, separating preparation from day-to-day use.

Besides, if you have a huge number of poi overlays, you may want to turn some off sometimes for lower density. It's nice to be able to do so with the map side-by-side, seeing the changes instantly.

Last question, to what extent do we associate categories and overlays with a specific profile? I personally have overlays tied to profiles and my categories are the same for all profiles. I'm not sure if I ended up with this setup for any logical reason or if the current UX simply nudged me towards it. Time will tell.
