### ISSUE TITLE
Tracks recorded are ending too soon when displayed on the map

### ISSUE THREAD

**Issue by Siron777** [osmandapp/OsmAnd#12226]
Hi,

I am recording my track while riding (mode bicycle). Sometime, when I know the current region, I stop the current routing of OSMAnd, but keep the recording. Once at home, I stop the recording and save it. I got two times the issue where the recording displayed on the map was ending too soon, I evaluate it to stop like 4 km before I stop the routing (which should not be related, but the two times I got the bug is seems to be related somehow to that). Here is the icon which is displayed when it end on the map: 
![wrong track display](https://user-images.githubusercontent.com/15027951/126836234-b0f8305c-9e79-4f85-99d3-c9dd6304d6ca.PNG)

But the track recorded is complete. On the "My Places / Tracks" menu, If I hide the track of the map, the correct distance for the track is displayed, but If I display it, the cropped distance is displayed. After a while (or several manipulation ?), the bug does not appear anymore and the full path is displayed on the map. 

As far as I remember, when stopping the recording, the recorded track was displayed correctly (up to the current position) on the map, it is only after, when I want to review what I did, that I have the issue. 

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: Android 11
Device model: Samsung Galaxy A51

**Maps used (online or offline):**   
Belgium map, Jun 1, 2020

**Comment by sonora** [comment]
Seeing that you use Android 11, have you deployed the fix I describe here #12046 for the storsge location? 

I believe I may have seen a sinilar phenomenon prior to changing my storage folder as described. Not sure, but it could  be due to the sluggish performance of writing to subfolders of Android/data under Android 11.

**Comment by oluc** [comment]
the issue seems to be gone in 4.1.11 (to be confirmed)
