### ISSUE TITLE
Labels - Point Text Overlay blinking

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#12233]
Labels - Point Text Overlay blinking.

Labels blinking as you move. Possibly algorithm has rounding issues i.e. float vs double or some randomness order. It is better to fix so they don't blink as you move the map.

**Comment by dmpr0** [comment]
# Review
- [ ]  Multiline point labels are jiggling while moving on the HDPI device. Video link
[20210804_174003.mp4.zip](https://github.com/osmandapp/OsmAnd/files/6932097/20210804_174003.mp4.zip)

**Comment by vshcherb** [comment]
Original issue is fixed, jiggling should be another issue
