### ISSUE TITLE
Arabic problems with calligraphy

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#12232]
Arabic problems with calligraphy.
Incorrect images:
![telegram-cloud-photo-size-4-6044274636797097836-y](https://user-images.githubusercontent.com/1042025/126896412-a3cf0cd1-1e36-4502-ac08-03f612a02312.jpg)

![telegram-cloud-photo-size-4-6044274636797097837-y](https://user-images.githubusercontent.com/1042025/126896408-9bc3d757-6e92-4081-8dcf-7eeb0a52477e.jpg)

Сorrect image:
![telegram-cloud-photo-size-4-6044274636797097838-y](https://user-images.githubusercontent.com/1042025/126896402-41355ea5-1140-4d7e-90af-bd979cf235e1.jpg)

Possibly problem could be fixed with font:
[NotoSans-Arabic.ttf.zip](https://github.com/osmandapp/OsmAnd/files/6873728/NotoSans-Arabic.ttf.zip)

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-core-legacy/pull/26
