### ISSUE TITLE
Openplacereviews login fails

### ISSUE THREAD

**Issue by ElucGeek** [osmandapp/OsmAnd#12230]
### Description
I try to login to Openplacereviews (OPR) after creating an account by linking my OSM account. From OSMand I open the plugin settings, click login, the page open in Firefox mobile, I select login with OSM, click grant access, then I'm back to OSMand OPR plugins settings but nothing changed, I'm still not logged.

### How to reproduce?
See above.

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: Android 11 (LineageOS 18.1)
Device model: Xiaomi MiMix2 chiron

**Comment by vshcherb** [comment]
Did you signup first before login? Can you try to login on https://openplacereviews.org/

**Comment by ElucGeek** [comment]
Yes I signed up, choose an email (that is not be the same as used for OSM as I use aliases for each services) and I can login on the website.

**Comment by scaidermern** [comment]
Try the following: Go to your user settings at https://www.openstreetmap.org. Go to OAuth 1 settings. Remove the authorization for OpenPlaceReviews (there might be multiple entries). Try again.

**Comment by ElucGeek** [comment]
Thanks, it works now.

**Comment by dead10ck** [comment]
I am currently running into this issue. No matter how many times I revoke the OAuth permission and try again, OSMAnd does nothing after I log in successfully.

**Comment by EvanCarroll** [comment]
Still an issue for me too.

**Comment by EvanCarroll** [comment]
@dead10ck may want to follow https://github.com/osmandapp/OsmAnd/issues/15108
