### ISSUE TITLE
Car mode tries to navigate through a cycleway

### ISSUE THREAD

**Issue by Athoss9** [osmandapp/OsmAnd#12239]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, OpenRouteService, OSRM, etc.)

### Routing Profile

car

### Start and end points

Start: N 61.1105, E 10.4593
End: N 61.1107, E 10.4669

### Actual and expected routes

The navigation tries to direct me through this cycleway: https://www.openstreetmap.org/way/68172947
The road does have a tag "motor_vehicle=destination" but my destination is not in that street.

![Screenshot_20210725-223813](https://user-images.githubusercontent.com/28255870/126913260-32ccac8f-9e52-4bc8-87ac-db05733a3b3e.png)

## 🌍 Your Environment

**OsmAnd Version:**

OsmAnd+ 4.0.1.

**Device and Android/iOS version:**

Android 9

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.
- [ ] Online (tile / raster) maps 

**Anything else relevant?**

**Comment by xmd5a2** [comment]
Looks like to me this is `highway=service` + `bicycle=disignated' not 'highway=cycleway'. I think this should be fixed in OSM data.
![Screenshot_2021-08-06_20-45-34](https://user-images.githubusercontent.com/5829014/128551409-c6ffda16-f5af-438d-aaf2-af758dc5f0e8.png)

**Comment by Athoss9** [comment]
This road is a shared pedestrian and cycleway, the sign below it says "Driving to the properties is allowed", so I think the tagging is correct.
But regardless of this specific road, I don't think OsmAnd should navigate on cycleways at all.

**Comment by vshcherb** [comment]
It should be tagged as motorcar=no, otherwise you can drive highway=service.

**Comment by scaidermern** [comment]
> It should be tagged as motorcar=no, otherwise you can drive highway=service.

It isn't a `highway=service` but a `highway=cycleway`, see https://www.openstreetmap.org/way/68172947. And it is tagged with `motor_vehicle=destination`, but the route destination in the above screenshot is not located on this way.

So it looks like OsmAnd handles `motor_vehicle=destination` incorrectly.

**Comment by Athoss9** [comment]
> 
> 
> It should be tagged as motorcar=no, otherwise you can drive highway=service.

As scaidermern wrote, it is tagged as a highway=cycleway. I think this road actually being a cycleway or not is not relevant to the issue. The issue is that according to the OSM database it is a cycleway and OsmAnd tries to navigate through it. If it has a motor_vehicle=destination tag, OsmAnd should only direct there if the destination is actually on that road.
