### ISSUE TITLE
Another slightly odd route

### ISSUE THREAD

**Issue by lunkhub** [osmandapp/OsmAnd#12238]
# 🐞 routing report

- OsmAnd's in-app offline routing
### Routing Profile

Same result with "fuel efficient" or not.

### Start and end points

Approximate start location:
N 35.25753, W 80.78753

Approximate destination:
N 35.31789, W 80.73752

https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=35.258%2C-80.788%3B35.318%2C-80.738#map=13/35.2879/-80.7626

### Actual and expected routes

Actual, screenshot: 
![Screenshot_20210725-OsmAnd~x](https://user-images.githubusercontent.com/66975721/126908483-21dd8b42-8b5c-4e75-aebd-840245bda8a5.png)

Expected, see above openstreetmap route (link), or screenshot, after "blocking" turns: 

![Screenshot_20210725-OsmAnd~y](https://user-images.githubusercontent.com/66975721/126908524-bbbcff38-7a1c-49ce-8d55-a21a4ead1dcb.png)

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

Unknown.

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

3.9.10 from F-Droid, added 3/16/2021
</code></pre>

**Device and Android/iOS version:**

Nexus 6, Android 11, de-googled

**Anything else relevant?**

Updated to latest maps today. Same results.
Shortest distance route does have more traffic lights, and estimated route times are probably significantly higher than actual, but relatively correct - Shorter distance may be longer time. In any case, "fuel efficient" should choose shorter distance route, but did not.

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/pull/12884/files
https://github.com/osmandapp/OsmAnd-resources/pull/722

**Comment by vshcherb** [comment]
Internal dev comment:
- [ ] routing-cleanup branch - https://github.com/osmandapp/osmand/tree/routing-cleanup fix TODO 10
- [ ] Investigate **precalculatedRouteDirection** is correct (TODO)
- [ ] Branch C++ routing-cleanup
