### ISSUE TITLE
Track Appearance dialog uses wrong color pallette

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#12243]
I had earlier noted that our new track appearance menu does not facilitate resetting track appearance to their renderer-specified defaults (#11542), and this is still not really fixed, see this demonstration:

![Screenshot_20210726-085649_OsmAnd~](https://user-images.githubusercontent.com/845735/126947192-3808868e-f0d4-466c-887b-002501e4c50e.jpg)

The left (lighter blue) track is displayed in the renderer's default color (Touring view in this case), i.e. no 'Appearance' change was ever applied for this track. The right, slightly darker blue is a track where the color was changed using the bight blue button of displayed color menu. You can see that the track color is rather different. There is no way to restore the original track color other than delete this track in OsmAnd (so the database gets reset), the restore it from a backup?

Also please note that in dark theme, like in the screenshot, it is still rather invisible to see which color in the color dialog has been selected, I think we should circle the selected color by a lighter shade of gray. (This also bleeds into #9125.)

**Comment by vshcherb** [comment]
I don't see any issue cause it's all defined in the style.
Style has 16 different colors and uses default different than 15 colors from pallette. So if you change it, you will get color from palette.
```
<case color="#B400FFFF"/>
```



P.S. I've created another issue to add a button "Reset to default" https://github.com/osmandapp/OsmAnd/issues/12247.

**Comment by sonora** [comment]
PS:Please note that the color of the right, darker blue track is exactly that of the color button in the selector, the one which is so barely vibily circled. (If you think otherwise:It's an optical deception.)

This means the bug is not that we assigm the weong color, it is that the cilor selector is missing a burton for the default xolor as specified in the current renderer's gpx default color attfibute.

Maybe rather than adding a missing color dynamically, the best fix would be to create an overall button to restore the track appearance to the currently used rendert's default attributes (color and width).

**Comment by sonora** [comment]
@vshcherb Ah, I see, we just ovevlapped each other with the same idea! ;)

**Comment by vshcherb** [comment]
> This means the bug is not that we assign the wrong color, it is that the color selector is missing a burton for the default color as specified in the current renderer's gpx default color attfibute.

It is a bug in rendering style, that default color is not in possibleValues of GPX track!

**Comment by sonora** [comment]
Like that, you mean? https://github.com/osmandapp/OsmAnd-resources/commit/ba774a7526986f33d49ab4de6f414558727c0bdd

Thanks for spotting! I guess in our old dialog that was never an isssue.

**Comment by vshcherb** [comment]
I actually don't know cause we don't use descriptions any more except IOS version.
