### ISSUE TITLE
Be able to reset Track appearance

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#12247]
Reset 'Track appearance' should reset / remove all changes accumulated in GPX Database (mostly appearance setting), so original GPX is displayed.

## ToDo
- [x] Track appearance menu: add "Actions" group with single action "Reset appearance to initial state"
- [x] Reseted settings should by apply on "Apply" button, and reverted by taping main "Cancel" button

# UI
![Снимок экрана 2021-07-26 в 12 44 47](https://user-images.githubusercontent.com/9365308/126969019-3ae6557d-c02e-425a-b4ee-922995319c21.png)

**Comment by sonora** [comment]
I guess it's best done by **emptying** the color and width attributes in the GPX-db, not by setting them to the default.

**Comment by vshcherb** [comment]
@sonora exactly!

**Comment by sonora** [comment]
Has a reset button been added? Where is it?
