### ISSUE TITLE
Multiply phone number is missing on Live updates

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#12246]
### Description
I was edit point https://www.openstreetmap.org/node/4262627790 and add two phone numbers `phone = +380442279432; +38(093)7198825`, but they missed in the map after the update.

### iOS, doesn't show the phone's in the context menu nor in the edit osm object menu.
<table style="width:100%">
  <tr>
    <th><img src="https://user-images.githubusercontent.com/9365308/126964499-4a243589-976d-4648-a8fb-15339b63ccd5.PNG"  width="300" height="auto"/></th>
    <th><img src="https://user-images.githubusercontent.com/9365308/126964907-b0d0d43a-3764-40fd-ba91-ead510e28015.PNG"  width="300" height="auto"/> </th>
  </tr>
</table> 

### Android doesn't show phone numbers in the context menu but shows it edit menu
<table style="width:100%">
  <tr>
    <th><img src="https://user-images.githubusercontent.com/9365308/126964710-bf3b25d3-b9cf-40c9-8c07-7c5cf822b2d8.png"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/9365308/126964718-820f7fbe-824e-453d-941a-a6ead5dae461.png"  width="300" height="auto"/></th>
  </tr>
</table> 

### Your Environment
Reproduce both on Android and iOS.

**Maps used (online or offline):**   
Kyiv.

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-resources/commit/b03047d600af7fe38989a8fe7471fb65926d592f

**Comment by scaidermern** [comment]
Could be caused by #12209.

**Comment by vshcherb** [comment]
Exactly the same issue.
