### ISSUE TITLE
Arabic font 

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#12244]
### Description

Need to change Arabic Font to official Arabic Font.

It's not prefer:
<table style="width:100%">
  <tr>
    <th><img src="https://user-images.githubusercontent.com/44466116/126959621-a73fa82d-65fe-4acd-9778-e60cda2ddde8.png"  width="400" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/44466116/126959731-bd920ef4-8968-4788-b99c-52b751b476e7.png"  width="400" height="auto"/></th>
  </tr>
</table> 
![image]()

[NotoSans-Arabic.zip](https://github.com/osmandapp/OsmAnd/files/6876810/NotoSans-Arabic.zip)

### Your Environment
OsmAnd Version: 4.0
Android/iOS version: Android 11
Device model: S10e

**Comment by vshcherb** [comment]
Closed https://github.com/osmandapp/OsmAnd/issues/12232
