### ISSUE TITLE
Wrong Drawing Order

### ISSUE THREAD

**Issue by mipri25** [osmandapp/OsmAnd#12249]
### Description

OSMAnd is using a wrong drawing order for objects without an explicit 'level' tag.

In the following example there are two garages on street level. Like the surrounding houses (except 119 and 121) and the street itself, they do not have an explicit level tag. This is according to the OpenStreetMap guidelines (see [here](https://wiki.openstreetmap.org/wiki/Key:layer)) stating that 'level=0' should not be set explicitly.

Now there are two houses (Number 119 and 121) built a bit up the hill, on top of the garages, but overlapping them partially. These houses have 'level=1' and must be drawn on top of the garages.

OpenStreetMap does it right:
![openstreetmap](https://user-images.githubusercontent.com/78664491/126992519-c1b83cd2-ad50-4540-95f0-b85e0537d918.png)

OSMAnd is drawing the garages on top of the houses:
![osmand](https://user-images.githubusercontent.com/78664491/126992818-211b3891-d669-44c2-9513-bb36bd379543.png)

### How to reproduce?

Open this [Permalink](https://www.openstreetmap.org/#map=19/48.67724/10.13379) and compare the displayed map with OSMAnd.

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: Android
Device model: LD Stylus 2

**Maps used (online or offline):**   Offline
 Deutschland Baden-Württemberg 01.07.2021

**Comment by xmd5a2** [comment]
Global support for `layer` tag is not implemented yet. Issue if fixed only for buildings and highways.

**Comment by mipri25** [comment]
Is this fix not yet included in OSMAnd 4.0.5? Just asking because Android version 4.0.5 with maps of 1.8.2021 still drawing the garages on top of the houses.
