### ISSUE TITLE
Action buttons not available when tapping on a track

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#12257]
Tapping on the map opens a widget with several buttons (Add (Favorite), Marker, Share, Actions, Direction etc.).

This widget isn't accessible when tapping on a track. Instead the track gets opened immediately. This makes it impossible to perform any actions at positions that are also part of the track. Especially adding a favorite, adding a marker or adding a track waypoint are typical actions that a user might want to perform. They aren't possible at the moment, though.

Tapping on a track should present a choice to the user whether to open the track or the regular "tap on map" widget.

**Comment by pebogufi** [comment]
YES this is very annoying.
I have to zoom to a very high level, then try to hit a position very close to that what i want but avoid to hit the track itself.

**Comment by scaidermern** [comment]
Indeed.

It is possible to create favorites, markers, waypoints etc. next to the track. Then select them again and move them on top of the track. But this is tedious and time-consuming.

**Comment by snouup** [comment]
This is a new feature I think. Tracks used to not be selectable on the map in older versions of osmand. I have not personally needed for it, and would appreciate if it was less intrusive. Apart from the issue described in here, it now takes an extra tap to select any POI's along a track.

I suggest a certain zoom level to activate the selection of tracks. I.e. you have to zoom out first.

**Comment by vshcherb** [comment]
Yes, I think it's duplicate issue though it should be fixed today with 4.0.

**Comment by vshcherb** [comment]
Now you will need to use Long Tap to get Points menu with Actions

**Comment by scaidermern** [comment]
> Yes, I think it's duplicate issue though it should be fixed today with 4.0.

> Now you will need to use Long Tap to get Points menu with Actions

Are you referring to a future 4.0 version? The above report is for version 4.0.1 where this problem still exists. Long tap doesn't help.

**Comment by vshcherb** [comment]
4.0.2 beta will be released today (master should have this fix as well).
