### ISSUE TITLE
Coastline shifts at different zoom levels

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#12258]
### Description
At zoom level 8 and below, the water overlaps the coastline and all objects marked on dry land displays on the water.

### How to reproduce?
51.16991° N, 4.20960° W
![Screenshot_20210724-205105](https://user-images.githubusercontent.com/80623554/127111841-8c590a6a-b16f-495d-a590-23ff278029ee.png)
![Screenshot_20210724-205058](https://user-images.githubusercontent.com/80623554/127111845-1c3752bd-40ae-4b5b-bfb1-ff4e7321ce6d.png)
![image](https://user-images.githubusercontent.com/80623554/127112192-be671c4e-9f9a-46c2-b33c-13927d608b01.png)
![image](https://user-images.githubusercontent.com/80623554/127112227-eb255957-8bd9-48ed-bcda-d0529f71e5bc.png)

**Comment by vshcherb** [comment]
New basemap should include updated beach area
