### ISSUE TITLE
Data Storage Folder Issue

### ISSUE THREAD

**Issue by bmwbiker62** [osmandapp/Osmand#1227]
Since update to 2.04 Osmand seems it doesn't detect existing maps. Neither in default folder nor in choosen extSdCard folder.
So - download all maps again ?  I tried one. Although I chose extSdCard the downlaod goes to default (internal) folder.
For test I moved World Base Map to extSdCard after download. Did a restart of Osmand and funny - this seems to work ! ?

Additionally there is similar issue with the favourites. My eisting old favourites file doesn't work in extSdCard folder.
Ok, copied it to the default folder. Neither doesn't work.
Created a new favourite. Gues where it will bewritten to - yes, it goes to my existing old favourite file. The new one will be added to my old ones. But Osmand only will continue showing the new created favourite.... ! ?

Fix that helped for me:
I restarted not only Osmand but booted my Samsung.
After that - Osmand will now accept the data folder setting.
Osmand now properly downloads new maps to that folder and also shows them properly in the map selection.
It also now shows my old maps in the local maps section.
Only - some of them it yet doesn't show in downloaded maps section and doesn't want to open (e.g. an Italy map).
Did they become incompatible ?

The favourites issue also is gone after phone reboot.
Osmand now shows all my favourites - also the old ones.

So after mobile phone boot Osmand works almost fine for me.

**Comment by sonora** [comment]
Please check out my comment elsewhere in a related issue about the extra "/osmand" folder at the end you your data storage path: If it looks something like (sdcard)/Android/data/net.osmand.plus/files/osmand, then moving the complete structure up by one level (move all files and folders up to the to the "files" level), and removing the empty "osmand" folder may solve your issue for good. This was a problem for versions 2.0.0-3, thought it was solved ok in 2.0.4.

**Comment by mikeshenson** [comment]
I had the same problem, I found that disabling the world map then re-enabling it fixed the issue. Once it could find the world map, all other maps were found.

**Comment by chanvre** [comment]
same here... osmand does not find any downloaded offline maps. no matter were they  are stored (sd or internal). tried to change folders, deactivate maps, activate again, reboot, uninstall and reinstall, everything failed. when I open the app I can see the world map and the country map. the downloaded country map is green colored as well, but as soon as I try to search for an address in it and I choose "country" osmand says "no offline maps found". frustrating :( maybe someone has a solution and like to share it - thanks

**Comment by chanvre** [comment]
i solved my issue now: problem was I just downloaded the "street map" from my country, and not the complete "regular map". When I downloaded the regular map as well, everything is ok and osmand works like a charm. the offline maps are now found and can be loaded from the sd card. thanks to all the developers and people working on this amazing app.
