### ISSUE TITLE
Fehlende Kontakt Daten

### ISSUE THREAD

**Issue by APneunzehn74** [osmandapp/OsmAnd#12276]
Häufig werden mir keine Kontaktdaten wie E-Mail und Telefon Nummer bei den POIs angezeigt obwohl diese bei OSM richtig hinterlegt.

### Your Environment
OsmAnd Version: 3.9.10 
Android/iOS version:
Device model:

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by pebogufi** [comment]
Please post examples !
As your post is very global nobody can help.
This is an english forum, please respect that.

**Comment by scaidermern** [comment]
Duplicate of #12209.
