### ISSUE TITLE
highway=path not displayed in map view

### ISSUE THREAD

**Issue by hlinden** [osmandapp/Osmand#1228]
I'm running OsmAnd+ 2.0.4 on Android 4.4. 

[This way](http://www.openstreetmap.org/way/102453114#map=18/51.52187/8.51268) for example is not displayed in OsmAnd:

![screenshot_2015-05-14-18-36-18](https://cloud.githubusercontent.com/assets/4718458/7636702/21402b4c-fa69-11e4-8bbb-220694f26c84.png)

Same goes for all the other paths in the area. Map data has been updated together with OsmAnd 2.0, these ways are older and therefore they should exist in the map data.

**Comment by xmd5a2** [comment]
This is by design of car profile (car cant drive those paths and it makes map more clearer to improve orienteering). Try switching to another. However highway=path's bridges are displayed because there are usually notable landmarks.

**Comment by hlinden** [comment]
That was it. Paths are displayed in normal map mode, as well as bicycle and walking mode.

I assume that my map was in car mode because I had used OsmAND for navigation a few days before. Maybe it would make sense to make the map mode more obvious?

**Comment by xmd5a2** [comment]
You can see it on your screenshot. Look at bottom left corner.

**Comment by hlinden** [comment]
Oh. Err. Right. -_- Well, let's close this bug then.
