### ISSUE TITLE
Navigation broken

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#12291]
@vshcherb Please double-check the latest builds if you plan to publish as release 4.02: I just built from the latest master and it seems route calculation is broken, it fails immediately with no route result. Last night's were still ok.

Have not tried the r4.0 branch, but wotth double-checking.

**Comment by sonora** [comment]
Affected seems all navigation to a point destination, while navigation via GPX is fine. The dev version shows toast:

![Screenshot_20210728-173119_OsmAnd~](https://user-images.githubusercontent.com/845735/127351629-4aa4c0c6-ad4a-4bd5-9acf-ab87f520e6ba.jpg)

**Comment by alex-osm** [comment]
Do you still have the issue? There was introduced suggested maps feature https://github.com/osmandapp/OsmAnd/issues/9144. However there was one fix after that.

**Comment by vshcherb** [comment]
4.0.2 is published but it will not be public release. We plan to release 4.0.3 on Friday as first public release.

**Comment by vshcherb** [comment]
As we checked 4.0.2 it's not affected

**Comment by sonora** [comment]
I can confirm that route calculation works again with new builds.

**Comment by hamer13** [comment]
I have built fresh branch "r4.0" (commit 5725e52988) and route calculation does not work. Also it does not work in branch "master".

**Comment by hamer13** [comment]
Also "official" build OsmAnd-master-nb-2021-07-29.apk does not work.

**Comment by vshcherb** [comment]
Another issue is identified and fixed in master / 4.0. Please test

**Comment by hamer13** [comment]
Yes, fixed. Tested in r4.0 branch.

**Comment by sonora** [comment]
Route calculation is faster now, particularly the 'dead period', i.e. the initial hang during each first long route claculation after each app start seems to have been cut in half. :)
