### ISSUE TITLE
Overlay map is disabling after profile switch.

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#12298]
### Description
Browse map profile > open Configure Map > Overlay > Turn on. Back to map, selected overlay and transparency slider is visible on the map. Switch to another profile and switch back to Browse the map, now "Overlay" is disabling. 
The same with "Underlay map".

### Your Environment
OsmAnd Version: 4.0.2 beta
Android/iOS version: 10
Device model: Nokia 5.3

**Maps used (online or offline):**   
OsmAnd Online tiles.

**Comment by pebogufi** [comment]
@vshcherb 
I have a similar problem with version
OsmAnd~  4.0.0#32472m.apk 2021-07-29
but i had the **POI-Overlay** affected.

**Comment by pebogufi** [comment]
Below the text "POI-Overlay ..." the text "* Verkehr/Mautstelle" is wrong, it is from a different POI-Overlay / or a different profile after switching profile.

![Screenshot_20210731-094919_OsmAnd~~01](https://user-images.githubusercontent.com/18628183/127733104-75ae8a9b-a1e2-40d7-99d9-9580376f4731.jpg)
