### ISSUE TITLE
Update links for maps Top Yandex RU and Yandex Traffic RU

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#12290]
Please update links to the following maps:

Yandex Traffic RU
https://core-jams-rdr-cache.maps.yandex.net/1.1/tiles?trf&l=trf,trfe&x={1}&y={2}&z={0}

Top Yandex RU
https://core-renderer-tiles.maps.yandex.net/tiles?l=skl&x={1}&y={2}&z={0}

### Your Environment
OsmAnd Version: OsmAnd~ 4.0.0#32461m, дата выпуска: 2021-07-27

**Comment by Nine-Tailed** [comment]
Also update link Yandex RU
https://core-renderer-tiles.maps.yandex.net/tiles?l=map&x={1}&y={2}&z={0}

**Comment by xmd5a2** [comment]
Link to Yandex traffic tiles gives error 400
For example:
`https://core-jams-rdr-cache.maps.yandex.net/1.1/tiles?trf&l=trf,trfe&x=5015&y=2545&z=13`

**Comment by Nine-Tailed** [comment]
я не знаю что за координаты x и y вы используете, но вот прямая ссылка на конкретный тайл пробок яндекса, ну и хотел бы отметить что сейчас у меня пробки настроены используя ссылку выше и все отлично работает
https://core-jams-rdr-cache.maps.yandex.net/1.1/tiles?trf&l=trf,trfe&x=9573&y=4767&z=14
Ссылки получены непосредственно с сайта яндекс карт
![image](https://user-images.githubusercontent.com/12549744/135630422-f4c69afe-1cdb-4e76-b13a-27bbee3017f5.png)

**Comment by ivanPyrohivskyi** [comment]
Updated online map tiles source list https://github.com/osmandapp/OsmAnd/commit/d8c36c36ba27c25e4f88cb7be663493fdca9b5fb

<img src="https://user-images.githubusercontent.com/1040293/135856148-67c6dc3b-aa10-49f8-bd98-ade196ccdc2b.png" width="400" />

**Comment by Nine-Tailed** [comment]
Thanks, it works.  Checked on a clean install 4.0.8.
