### ISSUE TITLE
Add strings without translations.

### ISSUE THREAD

**Issue by franco999** [osmandapp/Osmand#1230]
There are strings that can not find translate and I wonder if you could add.

Line 44 (SettingsDevelopmentActivity.java) -> "Smart route recalculation"
![recalculo inteligente](https://cloud.githubusercontent.com/assets/12088580/7638914/a4d4c91a-fa4e-11e4-818f-e8417d725242.png)

(list_item_height) -> "Height"
![limite de altura](https://cloud.githubusercontent.com/assets/12088580/7639011/610de29c-fa4f-11e4-83e8-4244e463c15f.png)

"Avoid border crossing"
![evitar fronteras](https://cloud.githubusercontent.com/assets/12088580/7639061/b929a61e-fa4f-11e4-81e9-f4592a4dc0db.png)

**Comment by alexey-pelykh** [comment]
Moved to localization strings in 5e7a4f3. Should be localized soon.

**Comment by franco999** [comment]
Thanks! Could you also add the string "mill pond"?
