### ISSUE TITLE
Display distance recorded in the recording widget's line 1

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#12305]
Is there any objection to displaying the _total distance_ recorded in the headline of our trip recording widget, next to where we show the _trip time recorded_, as indicated here (taken from the lock screen view)?

![Screenshot 2021-07-29 141112](https://user-images.githubusercontent.com/845735/127489877-20df8d5a-e5ba-4f71-bfcf-91223dec6fd4.jpg)

Time recorded and distance recorded are of about equal significance and should be equally displayed. The use cases are numerous, if e.g. running a marathon you would like to see both numbers on the lock screen without having to spend any more taps or swipes because you see one but not the other.

**Comment by scaidermern** [comment]
That would be really nice.

**Comment by vshcherb** [comment]
I think it's a good idea to have it after dot. Though it needs to be checked if there is no conflict with navigation
