### ISSUE TITLE
Maps deleted during update

### ISSUE THREAD

**Issue by miramikes** [osmandapp/OsmAnd#12309]
### Description
Hello,
It happened to me already 3 times that when OsmAnd has been updated my maps disappeared.
Interestingly contour files hillshades and slope files are still there. Also World basemap mini is still present.
mira

### How to reproduce?
Update beta version of OsmAnd

### Your Environment
OsmAnd Version: 4.0.2 beta
Android/iOS version: Android 10
Device model: Xiaomi Redmi 9C

**Comment by pebogufi** [comment]
This also happened to me with touring map with version
OsmAnd~  4.0.0#32467m .apk. 2021-07-28.
With newer version
OsmAnd~  4.0.0#32472m.apk 2031-07-29 i can **not** reproduce.
Device samsung tab s5e, android 10

**Comment by miramikes** [comment]
Interestingly it happened only when I'm updating beta version ... It never happened when I updated "nightly build" version.
Don't know if this matters but I share same directory for maps between "beta" and "nightly" version
m.

**Comment by vshcherb** [comment]
Beta & nightly version have different signature. Beta is controlled by Google Ply that might be part of the answer.
- World basemap mini  comes with application.

**Comment by miramikes** [comment]
Since this issue was reported my maps has been deleted 2 times during app update. Last time this morning ... I am just heading to paddling trip and sitting in car no wifi soon no data as well ... Not easy to download many GB of my maps again. There is really no way how to fix this issue? It is really annoying :/

**Comment by sonora** [comment]
Are you changing between version strains? From what and to what version does this actually occurr?

And what is your data folder? Are you quite certain the folder OsmAnd uses is the very same one before and after the update?

**Comment by miramikes** [comment]
My folder is storage/emulated/0/Android/obb/net.osmand.plus
My folder is always same.
I share maps in this folder between beta and night builds app.
This happened a least in four last updates i guess.

**Comment by miramikes** [comment]
BTW ... during today's update ... my maps again deleted :/

**Comment by sonora** [comment]
I think sharing between 2 different apps with 2 diferent signatures causes this issue under Android 10.

As a workaround it should work if immediately before upgrading you rename the foldrr in a file manager app, to e.g. ".../net.osmand.plus0". The after the update delete the newly created folder and rename the old one back.

Once you are under Android 11 I recommend to use path "(xxxx-xxxx)/ osmand", where xxxx-xxxx  is the id for your SD card. That folder should stay untouched by any updates.

**Comment by miramikes** [comment]
Hello,
thank you for trying help with this issue.
I just got new phone with Android 11.
I am trying create folder on sdcard as you recommended. It seems that total commander don't see sdcard :(
As I already realize there is new way how storage is handled on Android 11 :(
Can you advice me how to create "(xxxx-xxxx)/ osmand" directory pls?
Thank you
mira

**Comment by sonora** [comment]
See #12046: No need to use a file explorer. OsmAnd will create the folder for you, also move all the files. Just use 'Manually specified' with the right spath.
