### ISSUE TITLE
Find intersections

### ISSUE THREAD

**Issue by gtrus21** [osmandapp/OsmAnd#12316]
Need to be able to find intersections by searching.  For example, by request "intersection of Lenin street, Stalin street"

ru: Нужна возможность находить поиском перекрестки. Например по запросу "перекресток улица Ленина, улица Сталина"

**Comment by InsertUser** [comment]
Isn't this close to  how the address search already works. Search for a road, select it and then search/select intersecting street?

**Comment by gtrus21** [comment]
I did not notice that there is a crossroads on the list, I thought only at home
