### ISSUE TITLE
Ask to dl maps inaccurately while opening link

### ISSUE THREAD

**Issue by letypequividelespoubelles** [osmandapp/OsmAnd#12322]
### Description
When I open link from [Acastus Photon](https://github.com/gjedeer/Acastus/issues) in Osmand, it sometimes ask me to dl submap of map I already have. 

### How to reproduce?
I have the last "Rhone Alpes Auvergne" maps.
If I try for the road "route Grand Veymont, Gresse en vercors" in Acastus Photon and open it with OSMAnd, it will ask me to dl the "Isère" which is a sub-map of the "Rhone Alpes Auvergne" maps.
On the contrary, If I ask for the city "Gresse en vercors", OSMAnd won't ask to dl the sub-map 'Isère"

### Your Environment
OsmAnd Version: 3.9.10 from F-droid
Android/iOS version: Android 9
Device model:

**Comment by vshcherb** [comment]
Please test next week with 4.0.3 this algorithm has improved dramatically.
