### ISSUE TITLE
Search function: gas station not found

### ISSUE THREAD

**Issue by Neuwessi11** [osmandapp/OsmAnd#12339]
### Description
When going to "Kategorien/Tankstellen" and then adding "Jönköping", there is first shown nothing. After getting the search radius to 500 km (in my case, because I am now in Middle Sweden) there are shown some gas stations in Jönköping, but not the one I was looking for: Kem och Gas AB, Barnhemsgatan.
And it is tagged with "amenity=fuel". I know that because I did it myself.

### How to reproduce?
Just search for it.

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: Android 9
Device model: Cat S61

**Maps used (online or offline):**   
Live Maps.

**Comment by vshcherb** [comment]
Merged as an example to https://github.com/osmandapp/OsmAnd/issues/11467
