### ISSUE TITLE
Water rendering errors, central north island, NZ

### ISSUE THREAD

**Issue by robinpaulson** [osmandapp/OsmAnd#12331]
![](https://i.imgur.com/wgXUGTg.png)

See attached image, location is
38.42288° S, 175.87885° E 

It's probably related to the Waikato river which flows through the centre of the map, a very wide river. Or one of many lakes.

**Comment by xmd5a2** [comment]
There was `natural=coastline' tag on Hikurangi island https://www.openstreetmap.org/way/836077485
This is a mapping error. Fixed in OSM data.
