### ISSUE TITLE
Make GPX slope color space symmetric

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#12336]
This is the spillover of #11775, where this has already been requested, most recentlyby @scaidermern  with a good pallette in https://github.com/osmandapp/OsmAnd/issues/11775#issuecomment-885520101: 
![126763793-41143d49-2790-4dbc-8eab-5fdac37fc340](https://user-images.githubusercontent.com/845735/127762294-5474ba57-b248-4fc3-ab05-5039c7bdb40e.png)

Reasoning is that in plenty of use cases like hiking, biking, trail running, skiing, descents are of equal significance than ascents, there is no reason to compress the color space of one vs. the other.

**Comment by anastasiia936** [comment]
We got a request in the support chat to change slope range for the bicycle profile from -20% to +20%, so that for instance 2-5%, 6-9%, 10-13% and so on all get another colour. Because currently Slopes up to 10% all show up in yellow color, while there is a big difference between 3% and 9%.

**Comment by scaidermern** [comment]
Isn't that already covered by the above suggestion?

**Comment by Nine-Tailed** [comment]
You can make the maximum slope adjustable in the range of 10-100%. This would then cover the needs of a wide range of users.

**Comment by Nine-Tailed** [comment]
There is also a problem with the direction arrows, when the thickness of the track line above 9, they are drawn inside the line and if there is no slope, then they are not visible (white on white). Perhaps you should add a border for the arrows or use a black color, for example.

**Comment by YoBii** [comment]
> You can make the maximum slope adjustable in the range of 10-100%. This would then cover the needs of a wide range of users.

I second this. Adding to the discussion the only user group (Profile) where slopes exceeding 50% are even remotely relevant is hiking (Correct me if I (non-hiker) am wrong.
Whether it's cyclists or motorists roads above 30%-ish gradient are rare but they exist. The steepest official road has 37%. Everything above 40% though.. hardly exists,
Even when we consider mountainbike trails everything near 50% is extremely steep to a point where it doesn't make any difference for routing or navigating as it is simply **extremely** steep. 

So referring to the spillover above simply cutting the range limits in half while keeping the color palette exactly the same would make this feature much more useful already.

Additionally having a profile dependent customizable range limit is possibly the best solution as every possible use case should be satisfied.

**Comment by vshcherb** [comment]
It looks like https://github.com/osmandapp/OsmAnd/issues/12954 will be solved

**Comment by XandrexOSM** [comment]
> It looks like #12954 will be solved

hi, it does not seem to be solved. Do you have info on new priority for that feature, please?

**Comment by XandrexOSM** [comment]
> It looks like #12954 will be solved

hi, it does not seem to be solved, @vshcherb . Do you have info on new priority for that feature, please?

**Comment by vshcherb** [comment]
Yes it has a strategic goal for us but not in sense of chaning colors again though to provide the way to configure colors for GPX and for Slopes to have "own palette", so it takes time unfortunately to implement it and for now I don't see easy quick solution

**Comment by sonora** [comment]
We could quick and dirty adopt my above symmetric scheme, then take all the tine we need to work on the final, elaborate solution? 😉

**Comment by scaidermern** [comment]
> We could quick and dirty adopt my above symmetric scheme, then take all the tine we need to work on the final, elaborate solution? 😉

Yes, please. This is better than postponing this again and again. This is a nice feature with a big problem that existed right from the start. Let's make this feature as useful as it was supposed to be. It's only a tiny, easy step to make it finally happen. Don't make things too complicated.

**Comment by mnalis** [comment]
- I really do agree with @vshcherb that https://github.com/osmandapp/OsmAnd/issues/12954 is the only way to go that would solve the issue. But it is taking more than 2 years already, and it does not seem much closer to fruition then at the beginning. I understand that it is nontrivial to do and that there are many other things to do, but still I'd love if it would get implemented, it has been my favorite pet peeve for quite some time now.

For example, the proposed scheme here is totally useless to my touring bike (which is my primary, but not only, use of OsmAnd). All the colors between `0%` and `8%` are the same (or slight shade variations of yellow), yet I'm interesting only in grading between 0-6% -- 8% being as impassable to my loaded bike as is 15%, or 45%, or 99%, so they might as well all be the same color.

That being said, the current default is even more useless (unless you use 4WD motor all-terrain vehicle?) so I see no harm in quick PR to change to default until such time as #12954 materializes. (unless accepting such PR would delay #12954 even further. Then I vehemently object to anything that might delay it :smile: )

**Comment by sonora** [comment]
I agree with @mnalis that my above proposal may expose too little differentiation in the 0-8% regime (which matters most to most users). That can be easily fixed by compressing the scale a bit into the closer-to-zero values (and by that losing a bit of differentiation in the higher values), e.g. by transforming my above linear spectrum with a quadratic or exponrntial function.

**Comment by vshcherb** [comment]
@sonora ok create pull request, you need to update code, image and route line appearance preview.

**Comment by sonora** [comment]
Sure!  I'll collect things here https://github.com/osmandapp/OsmAnd/compare/master...hardy_symmetric-color-space. First version of coding is present. Fine-tuning and pictures will follow as I find time.

Fine-tuning: We can spread or condense further, as we see fit, needs some testing. Currently I am cutting over to the next color at 7.5% slope (current release has 12.5%), i.e. we would apply more spread to differentiate the small slopes, and more collapse the big ones.

**Comment by michaelblyons** [comment]
@sonora Thanks for starting a branch! I would encourage you to look at Jon's comment on #12954, wherein he argued that white is hard to see as the neutral 0%.

**Comment by sonora** [comment]
We can of course 'invent' yet another center color, it should be kinda "neutral", though with the "_yellow>red_" meaning uphill and the "_green>cyan_" meaning downhill.

Rather than inventing yet another color, perhaps this is best solved by making the center color range rather narrow, so that you always have a slight tint of yellow or green. (I have that in my tests of the above, but live in a hilly area. We could intensify a little.)

Could also experiment with increasing _transparency_ towards the 0% value. But remember, this was meant to be my quick and dirty approach, not a full-blown scientific study ... :wink:

**Comment by mnalis** [comment]
> Fine-tuning: We can spread or condense further, as we see fit, needs some testing. Currently I am cutting over to the next color at 10% slope, then again at 20% (current release has 12.5% / 25%, i.e. we would apply a little more spread to differentiate the smaller slopes while a bit more collapsing the big ones). 

I think it needs **even more spread at lower values**. 
E.g. I'd have (_at least_) 0-5% be white-to-full-yellow, 5-10% be full-yellow-to-start-of-red, 10-20% be red-to-redish-purple, and 20%+ going from redish-purple-to-full-purple at the end of the spectrum. 
(and even that is a heavy compromise; if I had fully customizable setup in https://github.com/osmandapp/OsmAnd/issues/12954; in my cycling profile I'd have 10% and anything above it at absolute top of full-purple, and use the most of the spectrum white-yelloy-orange-red-redishpurple for more detailed 0-8% slopes)

> From first tests this looks ok for my purposes.

It would be useful to state what your purposes are, though? (mine are different modes of amateur cycling, and amateur hiking)

> We can of course 'invent' yet another center color, it should be kinda "neutral" though (light-gray?)

light-grey might look ok, I think? (although green might make more sense, but then we really lack the colors for marking downhill -- which is less important IMHO, but not completely irrelevant)

**Comment by sonora** [comment]
My purposes are mountain hiking, trail running, and off-highway driving.

Trouble is that judging from the color scale legend is actually quite deceiving, I was surprised how much more differentiation a track offered even with just the 10%/20% scheme (initially had tried 7.5%/15%, and that was almost overdoing it in places).

It would be best to use a test build and try yourself. But if anybody cares to give a test track here, I can offer to produce some screenshots for some parametrizations, then we can pick.

**Comment by sonora** [comment]
@vshcherb The route preview is adjusted. Is there an easy way to re-generate _img_legend_route_slope.xml_?

**Comment by sonora** [comment]
I've tested it for 2 weeks and think it's perfect. Merged now, so more people can try.

**Comment by shurasmiling** [comment]
https://docs.osmand.net/docs/user/map/tracks-on-map#track-appearance
https://docs.osmand.net/docs/user/navigation/guidance/map-during-navigation#route-line-appearance

**Comment by EugeneZmeuk** [comment]
**16-04-2024 Review**
