### ISSUE TITLE
Send supported tags to taginfo

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#1235]
Maybe OsmAnd would be interested in plugging into taginfo.openstreetmap.org so send which tags it does support. See http://blog.jochentopf.com/2014-09-19-taginfo-integrates-more-data-sources.html . I think this would merely need to process the file https://github.com/osmandapp/OsmAnd-resources/blob/master/poi/poi_types.xml into the taginfo required format and also link in the icons used in OsmAnd for those POIs.

**Comment by vshcherb** [comment]
Not sure where it will be better to do this and how to do this to not distract development much. All supported tags are present in rendering style, so they could be extracted as grep or any text search function

**Comment by sonora** [comment]
No action planned here, I guess.

**Comment by aceman444** [comment]
@vshcherb this does not look like something to distract development. It would need to write a script once to process the poi_types.xml and rendering_types.xml to extract all tags found there into the taginfo required format. You can then change the file freely and the script would just run from time to time automatically.

**Comment by vshcherb** [comment]
That's true, it is in my list once I'll have some free time.

**Comment by vshcherb** [comment]
Work in progress https://github.com/taginfo/taginfo-projects/pull/45.

**Comment by vshcherb** [comment]
Fixed

**Comment by vshcherb** [comment]
http://builder.osmand.net:8080/view/WebSite/job/OsmAndTagInfo/ws/taginfo.json
Script is here
https://github.com/osmandapp/OsmAnd-tools/blob/master/obf-generation/taginfo.groovy
