### ISSUE TITLE
Public Transport support for Navigation

### ISSUE THREAD

**Issue by Nutomic** [osmandapp/Osmand#1236]
This is the only thing I'm missing in the app.

Also, thanks for all your effort. v2 looks really good :)

**Comment by Airon90** [comment]
I suggest Osmand developers to use [Navitia.io](http://navitia.io) APIs in order to add support to public transport to the app. You could also contact [Transportr](https://transportr.grobox.de) developers as they are building an open source app just for public transport.

**Comment by dkniffin** [comment]
I would like support for [transloc](https://www.mashape.com/transloc/openapi-1-2#!documentation).

**Comment by kompowiec** [comment]
Could be done hastily plugin which Transportr required?

**Comment by KOLANICH** [comment]
For Moscow buses/trolleybuses/trams you can get live info about their position by reversing ru.yandex.yandexbus API (they have aggreement with Moscow government to get such kind of info from gps/glonass trackers on transport) or by using their public api.

**Comment by paskalito** [comment]
Transpotr also had once plans / ideas to implement these publictransport infos offline, which would also be very cool to have

**Comment by OpenSourceForEver** [comment]
What about it? It would be very nice option

**Comment by ADepic** [comment]
Project Dead?

I think first you should implement transportr, then get an API to work with bus / train routes in OSM.

**Comment by EmmanuelMess** [comment]
> I think first you should implement transportr

How would that work?

**Comment by prototype99** [comment]
might be worth mentioning, transportr for the most part uses navitia, so really the important task seems to be getting navitia support built in. thus we can't really implement transportr (being a whole app) but we can implement navitia, which is the main data source they use (they seem to suggest you can contibute data sources to navitia as needed too). they also detail a bit about the process to get transport service logos, which may be desirable. here is the link anyway, to read: https://transportr.app/contribute/

**Comment by airon90** [comment]
Another source of data than Navitia is https://transit.land. I noticed that this one is more community-based than Navitia, which often doesn't add data you found

**Comment by EmmanuelMess** [comment]
I don't think we need data sources, the app already has enough information from Open Streets Map. The code for the actual public transport navigation is what should be added (IMO).

**Comment by prototype99** [comment]
i'm pretty sure that's what we need the data sources for. one of the most important things to have, is the timetable. does openstreetmap support the addition of timetables? if we wanted to use it like that wouldn't we need to help create a standard for adding in timetables? even if we had that, there are lots of buses now, that broadcast their location and any delays, i don't think osm supports live data like that... it would be good, but i don't think it does as far as i know it has to all be static data.

**Comment by jmaris** [comment]
Has this advanced at all?

**Comment by romusprime** [comment]
unsubscribe me

**Comment by utack** [comment]
Maybe this could be done together with https://github.com/grote/Transportr or https://gitlab.com/oeffi/oeffi  
Either of those apps could implement an api (brouter style) and send results to Osmand?
@schildbach also already seems to have a project to easily implement public transport routing into any app
https://github.com/schildbach/public-transport-enabler

**Comment by romusprime** [comment]
unsubscribe me

**Comment by scaidermern** [comment]
> unsubscribe me

Use the _Unsubscribe_ button on the right.

**Comment by contrapunctus-1** [comment]
It's amazing to see this get some activity! 😃 Could anyone involved please tell us if it will use OSM PT data like MAPS.ME does, or other sources, like Transportr does?

**Comment by vshcherb** [comment]
The data is already available for last years in Public Transport, it is coming only from OpenStreetMap, so navigation will use the current data which you can see by clicking on the transport lines

**Comment by ADepic** [comment]
Maybe supporting external data sources in the future? 
OSM's public transport isn't always reliable, and even if it is, it doesn't support bus times or live bus times (if the bus is early or late.)

**Comment by schildbach** [comment]
Nowadays most of Europe is covered by Hafas, which is very well supported by https://github.com/schildbach/public-transport-enabler/

**Comment by OpenSourceForEver** [comment]
Before including this in Osmand (very nice function) maybe it should be solved problems like https://github.com/osmandapp/Osmand/issues/6176

**Comment by aliceinwire** [comment]
Would be nice to have also Japan transports.

**Comment by franco999** [comment]
I add a screenshot about the new function they are implementing in this regard.
![as](https://user-images.githubusercontent.com/12088580/53695756-531c4700-3d9e-11e9-96e5-f11294eeff86.jpg)

**Comment by prototype99** [comment]
looks promising. i hope documentation is released on what tags osmand looks for, that would probably be a great help. does it only use offline data or does it use something else to add live feed support where available?

**Comment by ADepic** [comment]
Only offline data which is a bit annoying

**Comment by prototype99** [comment]
progress all the same. obviously there are already implementations of live routing for both osm and other services, however there's not really any example of offline routing floating around so i guess naturally offline would be a priority to firstly fill a gap and secondly because osmand already has strong offline routing

**Comment by vshcherb** [comment]
Basic implementation is done and Public Transport now in Beta. From this point this issue will split into many other issues some of them will be must have some of them nice to have.
For this release, we are planning:
1. To write a detailed article how it works and how to correct map data and validate it. In our tests we've found that 90% of the issues were related to the map data.
2. Fix small UI glitches and some not-functionling buttons.

**Comment by prototype99** [comment]
I'll move this to the related issue if/when one is made but for now without looking at the code (because I'm unfamiliar with it) this is what I seem to gather by locating and studying the example shown earlier:

- routing is based off of public transport v2

- routing requires stop positions to be present (which kinda makes sense, it makes the line it draws much smoother)

- if the route relation already exists you must edit it in JOSM because ID has no way to reorder relation members as required

- JOSM has tools that can generate the correct ordering for public transport relations as well as filling in some of the tags, although the auto-generated names seem to be slightly non-compliant

- JOSM also to some degree helps with generating stop position nodes using an appropriate plug-in

- routing currently treats public transport as taking 0 minutes, however one can assume that this will be fixed in a later release

**Comment by OpenSourceForEver** [comment]
I think routing don’t require stop positions to be present

**Comment by prototype99** [comment]
where i live the route relation has no stop positions and it says route is empty. the working example seen above is in an area with stop positions, so it's a guess until i've updated the local route and seen if it makes a difference

**Comment by OpenSourceForEver** [comment]
Osmand works fine with relations without stop positions. Logically, if there are no stop positions there must be platforms

**Comment by prototype99** [comment]
well, i added in the stop positions and it still doesn't route, it's mystifying... it's a full v2 relation with stops and stop positions. i'll have to compare again to see what's missing. now with the stop positions rather than saying route is empty it just stalls.

**Comment by ADepic** [comment]
I feel that osmands stalling is unlikely to be a map issue. It just stalls (routing never completes) and slows down your phone.

BTW, does routing use "duration" ,"interval" and "opening_hours" tags on public transport relations ? Those tags are critical for good public transport.

**Comment by prototype99** [comment]
well, the example place still works on the same app/map version and device... i wasn't aware opening_hours was used on the relations, but it makes sense. as i have no experience of how osmand is coded i couldn't give an exact answer. it LOOKS like 3.3.6 has gained some ability to process public transport duration though, but keep in mind they could just be using a profile designed to emulate a bus' speed and such. someone else may know for sure, you could also see if you get lucky searching commit history, it doesn't look like any commit detailed how the implementation works though.

**Comment by LaoshuBaby** [comment]
> BTW, does routing use "duration" ,"interval" and "opening_hours" tags on public transport relations ? Those tags are critical for good public transport.

Now it is 2023, the public transportation navigation is much easier to use, but they still don't support opening_hours, so recommending night buses during the day or holiday buses during weekdays is still happening, as introduced in #6700

(And this kind of problem is still [being reported](https://t.me/osmchina/1/96359), but I don't know how to modify the [routing.xml](https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml) file to solve this problem, I want to know how I can get guidance to add this feature)

**Comment by firefoxlover** [comment]
In Germany it does not work at all.

https://gitlab.com/oeffi/public-transport-enabler

Oeffi, a very well working public transport app for all transports in all of Germany, has this library that could be used for routing in Germany
