### ISSUE TITLE
Crash if uploading notes or Pois while there is no connection

### ISSUE THREAD

**Issue by AnyFile** [osmandapp/OsmAnd#12369]
### Description
If you upload a note or a modified Poi (with the OpenStreetMap editing plugin turned on) and there is no internet connection the app crash

### How to reproduce?
Turn on the OpenStreetMap editing plugin
Create a note or modify a Poi.
Turn off your internet connection (to be sure, as an experiement turn off both Wi-Fi and Mobile data, but this can also happens accidentally if the connection is lost or if you enter in a zone with no data coverage).
Upload the note or the edited poi

Remember to turn back on Wi-fi and/or Mobile data if you have turned them off

### Your Environment
OsmAnd Version: Osmand+ 3.9.10
Android/iOS version: Android 11 (but I have also experienced the same issue with previous versions of Android)
Device model: Samsung Galxy A50

**Maps used (online or offline):** 
Offline vector map

**Comment by nazar-kutz** [comment]
Can't reproduce in 4.0
