### ISSUE TITLE
Keys for map scrolling left/right/up/down

### ISSUE THREAD

**Issue by Emile31** [osmandapp/OsmAnd#12364]
### Description

I'm trying to develop a handlebar tool (motorbike, bike...) for remote control of Osmand on tablet/smartphone.
The basic functions includes :
- Recenter
- Zoom+/-
- Move up/down/left/right
From what I've seen in the code, there is nothing for the moving of the map.

### Describe the solution you'd like

Maybe we can add the arrow keys for this function ?

**Comment by Emile31** [comment]
Small remark for the move : I think no need for a joystick input with progressive response.

**Comment by vshcherb** [comment]
Yes we need to add arrow keys and probably 'awsd' standard keys

**Comment by Emile31** [comment]
yes good idea

**Comment by nazar-kutz** [comment]
@Emile31 Map scrolling and all needed arrow keys already realized in ScrollHelper class:
https://github.com/osmandapp/Osmand/blob/74fcdc7ce1080562630b502988f7798f3f39f2dc/OsmAnd/src/net/osmand/plus/helpers/ScrollHelper.java#L26

**Comment by nazar-kutz** [comment]
@vshcherb keycode 'D' is already uses for another purpose:
https://github.com/osmandapp/Osmand/blob/690198a740ce870fe6a434df974bb7b7d0f97fcc/OsmAnd/src/net/osmand/plus/activities/MapActivityKeyListener.java#L95

**Comment by nazar-kutz** [comment]
Keycode 'D' is using for switch map direction
![image](https://user-images.githubusercontent.com/30292035/131314985-38572e44-d0c5-4fb2-922d-7d659f29a393.png)

**Comment by Emile31** [comment]
Ok great ! so already available in beta version I guess ? i will try

**Comment by nazar-kutz** [comment]
@Emile31 Arrow keys should works from OsmAnd version ~3.6-3.7

**Comment by Emile31** [comment]
I've just tested with a standard bluetooth keyboard and it works fine.
Just looking for the key to recenter

**Comment by Emile31** [comment]
okay it's key C, thanks !

**Comment by vshcherb** [comment]
Probably we could reuse than i,j,k,l for movements to support keyboard that don't have direction buttons. Though we would need another request for that
