### ISSUE TITLE
Do not change custom icons for waypoints when importing track from external source.

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#12372]
When you plan a route and create a track in a third-party source, then when importing into Osmand, all waypoints are displayed with the same default icons (star in the circle). It would be great if OsmAnd could identify and support icons from an external source. For example, track created in Garmin and imported to OsmAnd: 

![image](https://user-images.githubusercontent.com/80623554/128195685-d95fc2db-2891-43e1-9261-cf5505fd5634.png)
![image](https://user-images.githubusercontent.com/80623554/128195727-7e8b21c9-7e51-49c3-8599-eaa0b3be2f13.png)

**Comment by mariush444** [comment]
Osmand can use only icons that are embedded in it.
Simillar issue exists with gmaps tracks/waypoints.
Then probably workaround can be implemented as is for https://github.com/osmandapp/OsmAnd/issues/11210

**Comment by mariush444** [comment]
@anastasiia936 
This is script in python that translates google icons (stored in kmz) to icons known by osmand.
I think it can be easily adopted for conversion from garmin to osmand.
 https://github.com/mariush444/gmapIcons2osmand
