### ISSUE TITLE
Incorrect display of the "Overlay POI" switch

### ISSUE THREAD

**Issue by gtrus21** [osmandapp/OsmAnd#12378]
POI Overlay switch is not displayed correctly when switching a profile

ru: При переключения профиля неправильно отображается переключатель "Наложение POI"

OsmAnd~ 4.0.0#32493m, дата выпуска: 2021-08-02
Android 11

https://user-images.githubusercontent.com/69676792/128311422-4944adba-bcad-4491-8134-c57583983bde.mp4

**Comment by gtrus21** [comment]
OsmAnd~ 4.0.0#32493m, дата выпуска: 2021-08-02

**Comment by pebogufi** [comment]
For me it is fixed with OsmAnd~  4.0.0#32506m.apk at 2021-08-04.
see https://github.com/osmandapp/OsmAnd/issues/12298

**Comment by gtrus21** [comment]
Да, в OsmAnd~ 4.0.0#32510m, дата выпуска: 2021-08-05 исправлено
