### ISSUE TITLE
Please add permanent_camping to tourism=camp_site

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#12371]
# 🚀 feature request

### Description
Please add tag permanent_camping=yes/no/only
https://wiki.openstreetmap.org/wiki/Key:permanent_camping

to tourism=camp_site
- as optional tag when create/edit tag tourism=camp_site 
- when show details
Please consider to create a different icon for permanent_camping=**only**.

Background:
When i am traveling and searching for a campsite to stay overnight or for some days, a camp_site with permanent_camping=only is UNusable.
If i drive to it, i will be disappointed, because it is not usable for "normal" tourists, so it should be easy be differentiated from normal camp_sites.

Example:
https://www.openstreetmap.org/way/299835457

**Comment by pebogufi** [comment]
@xmd5a2 Should it work with latest nightly 
OsmAnd~  4.0.0#32548m.apk from 2021-08-12
(I don't see something in Details)
or do we need to wait for map update ?

**Comment by vshcherb** [comment]
Map update is needed
