### ISSUE TITLE
Navigation issue in OsmAnd 4.0.3

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#12383]
When you try to calculate route appears message: "Additional offline maps are required to calculate the route". But all maps have already been downloaded. 
For example with downloaded standard map  "Baden Württemberg" (Germany) asks for downloading region map "Regierungsbezirk Karlsruhe". 

Present in the 4.0.2 and 4.0.3 versions.

**Comment by alex-osm** [comment]
Should be fixed in 4.0.4
