### ISSUE TITLE
Update Polish voice ogg files

### ISSUE THREAD

**Issue by steelman** [osmandapp/Osmand#1238]
There have been some significant improvements for Polish voice  [commited](https://github.com/osmandapp/OsmAnd-resources/commit/7bb8db3790b574136afe4fc57501af1f5dcf148e) that still aren't available as "rendered" ogg files, neither in the repository nor on the [download page](http://download.osmand.net/list.php).

**Comment by vshcherb** [comment]
We don't expect to happen it any time soon, cause we've lost a program access to generate files

**Comment by steelman** [comment]
Could you tell more? Is the software required for the task available? Is it a problem, because it needs to be put together in some sophisticated way?

**Comment by vshcherb** [comment]
Well, we commit recorded files to the repository. The only issue to change/add 1 word the same speaker should be used, it used to be 1 system (forgot which one), but they were unreliable
