### ISSUE TITLE
Routing anomaly - Christchurch NZ. Normal car route is bad. Fuel-efficient is ok.

### ISSUE THREAD

**Issue by eliotb** [osmandapp/OsmAnd#12384]
# 🐞 routing report

### Routing engine
- OsmAnd's in-app offline routing

### Routing Profile

Routing profile Car, normal vs fuel-efficient

### Start and end points

Christchurch, New Zealand.

[Route](https://www.openstreetmap.org/directions?engine=graphhopper_car&route=-43.5701%2C172.6841%3B-43.6028%2C172.7183#map=14/-43.5865/172.7013&layers=C)

### Actual and expected routes

Actual route with fuel-efficient route OFF = bad, adds about 3.6km useless side loop.
![Screenshot_20210805-190938_OsmAnd+](https://user-images.githubusercontent.com/421383/128336575-adc9056a-5213-41f4-9ecb-c527b4908972.png)

Fuel efficient route is the expected route:
![Screenshot_20210805-191007_OsmAnd+](https://user-images.githubusercontent.com/421383/128336579-889a53d3-6702-4349-b07c-f3b7a261fad5.png)

### Is this a regression?

Sorry, I don't know

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>
3.9
</code></pre>

**Device and Android/iOS version:**

Samsung s9+
Android 10
/e/ OS 20210529

**Comment by vshcherb** [comment]
Map is fixed, should be in September update
