### ISSUE TITLE
Help find OSM edit now causing OsmAnd "flooding"

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/OsmAnd#12399]
### Discussed in https://github.com/osmandapp/OsmAnd/discussions/12345

<div type='discussions-op-text'>

<sup>Originally posted by **thompehw** August  2, 2021</sup>
I noticed a case of "flooding" at some zoom levels in OsmAnd around geo:51.07450,1.16528

![Screenshot_20210802-041535_OsmAnd+](https://user-images.githubusercontent.com/39751382/127800665-27ac17db-17d0-4f60-bf99-09c23f17f043.jpg)

It doesn't appear with the England South East map of 1st July, only when I have live updates. So I assume that something was edited in OSM since 1st July that is causing a problem. I had a look at the OSM changes using achavi but I haven't found the cause yet. Can anyone help? Thanks!</div>

**Comment by ivanPyrohivskyi** [comment]
Is not reproducible on the new map from 01.09.2021
