### ISSUE TITLE
Android 11: Add GPS permission "Allow all the time"

### ISSUE THREAD

**Issue by hcsihp** [osmandapp/OsmAnd#12397]
**Description**

In Android 11 the permissions for GPS access have changed. 
[https://medium.com/swlh/request-location-permission-correctly-in-android-11-61afe95a11ad](https://medium.com/swlh/request-location-permission-correctly-in-android-11-61afe95a11ad)
[https://developer.android.com/training/location/permissions](https://developer.android.com/training/location/permissions)

Therefore, I can't give alltime access, when opening the app for the first time or when I try to reassign permissions. The "highest" permission for GPS access actually is "While using the app".
That's a problem, when I have OsmAnd in background or use several apps with GPS access. When OsmAnd is in foreground again, it takes up to 30 seconds to find the GPS position.

**How to reproduce?**

Your device uses Android 11.
If you grant GPS permissions for the app, you can't choose "Allow all the time".
When you foreground the running OsmAndApp, it can take time to find the GPS position.

**Your Environment**

OsmAnd Version: OsmAnd~ 3.9.10 (FDroid)
Android/iOS version: Lineage 18.1
Device model: Sony XA2 (pioneer/H3113)

**Comment by sonora** [comment]
Essentially it is a best practice contribution to power saving, while at the same time no disadvantage for many users, because a GPS fix (where GPS is available) averages more like 3 sevonds, not 30, on most devices with manufacturer support for Android 11. (Lineage OS could be the issue here.?)

But in OsmAnd you can easily use the workaround of either turning on trip recorfing, or turning on navigation. Both use a foreground service (even while the app is not showing full screen), thus the app receives the location continuously, just like you want.

You can then also check out the noticeable effect on battery consumption, which we should not risk users to see continuously day in and dax out  by accidentslly having grantied the permanent permission.

**Comment by hcsihp** [comment]
That's right, when track recording is on, the track is recorded continuously.

I understand the point. But my practice of OsmAnd is rather to use it for getting my location than for navigation. I use other apps (e.g Streetcomplete) with the same issue - when I open the app it takes time to find and/or display my location. That behaviour differs from another Routingapp (e.g. Magic Earth), which has this GPS permission and works perfect. So I thought it could be the missing permission. But you're right, it also could be Linage together with my device.  :( 

Any other suggestions?

**Comment by sonora** [comment]
Tapping the MyPosition button while it is still gray will download (if your device is online at the time) the public A-GPS data which should speed things up noticeably.

**Comment by sonora** [comment]
@vshcherb On a more programmatic note: Reviewing the best practice guidelines at https://developer.android.com/training/location/permissions, I am not convinced OsmAnd should include a request to grant background location access. There seems no justified OsmAnd use case for us to do so, and it may even cause future problems e.g. when we start targeting Android 11.

In all cases where OsmAnd holds location access, we explicitly make this transparent, and the user aware, by either the app itself being directly visible, or a foreground service is active in the device notification area. I would not know how to justify additional cases?

**Comment by vshcherb** [comment]
It really depends how Android will proceed with further phones, over time the way main brands handle these permission is going to settle i.e. Samsung, Google, Xiaomi, Huawei. So, it will be clear whether we need to request this permission or not, also changes in Android 12 could again start turbulence.

**Comment by Sepero** [comment]
![Screenshot_20211030-221639__01](https://user-images.githubusercontent.com/1575546/139539319-cb81ab9b-03e1-4390-9520-3d82ce4f2d9c.jpg)

I would also like to request Background Location Access.

My use case is that I use OsmAnd for navigation while riding my motorcycle. I plug headphones in my ears, put my phone in my pocket, and listen to navigation. It's not safe for me to be looking at the screen while driving.

But if the turns off in my pocket, then I no longer get audible navigation (consequently I end up going wrong directions, and late for appointments)

Android 10
Osmand 4.0.7

**Comment by Sepero** [comment]
Please let me know if there is any way to force enable Background Location Access with adb

**Comment by sonora** [comment]
@Sepero  Chances are you are not seeing a permissions issue, but rather a power savings issue. Unfortunately these are quite  device manufacturer dependent.

Please go to https://docs.osmand.net/en/main@latest/osmand/troubleshooting/track-recording-issues#the-system-may-kill-background-apps-to-save-power and try to adjust your configuration, especially as I describe in section "Tested Settings for Android 9 and 10", I think that may resolve the issue.

**Comment by grrosminet** [comment]
sonora said :
> But in OsmAnd you can easily use the workaround of either turning on trip recorfing, or turning on navigation. Both use a foreground service (even while the app is not showing full screen), thus the app receives the location continuously, just like you want.

It's not true : it works a few seconds and after there is no more location update. If the app is not effectively displayed, it will not work. It's true for waze on MagicEarth too.

**Comment by Sepero** [comment]
> @Sepero Chances are you are not seeing a permissions issue, but rather a power savings issue. Unfortunately these are quite device manufacturer dependent.
> 
> Please go to https://docs.osmand.net/en/main@latest/osmand/troubleshooting/track-recording-issues#the-system-may-kill-background-apps-to-save-power and try to adjust your configuration, especially as I describe in section "Tested Settings for Android 9 and 10", I think that may resolve the issue.

This is a very reasonable assumption to make, and may be the case for many people, though I don't suspect it in my case. I have already gone through and disabled all battery saving options on OSMand. Also, as @grrosminet noted, I only lose signal once my screen goes off.

As soon as my screen comes back on, OSMand is still open, and it begins to find my GPS location again, and begins speaking directions to me again

**Comment by sonora** [comment]
I see exactly this behavior on many newer Samsung devices with Android 10 and 11, but so far have managed to reliably fix this with **precisely** the power settings I dicumented.

Unfortunately these power settings tend to be manufacturer-dependent to some degree. In any case, just disabling a single power saving or white-listing OsmAnd did not fix it for me, so maybe try to follow as precisely as you can on your device. BTW Adverse impact on battery life is negligible as per my observations... )

**Comment by Sepero** [comment]
I'm not sure if an apology is in order for me, but I need to issue a correction. I must admit my reports on this issue are from my experiences some months ago, and due to the problems I was having, I had discontinued use of OSMAND for navigation.

I wanted to confirm my statements above, for myself and report back here, so today I used OSMAND for navigation for some hours (screen off, audio navigation). To my surprise, I didn't experience any issues as I had on previous occasions. I received audio directions, and calculated updates throughout my entire route.

As a result, I must retract all my previous remarks. I can no longer reproduce any problem with screen off audio navigation. It is possible that @sonora was correct, and at an earlier time I failed to turn off battery optimizations. I have sincere gratitude to all of you developing this app. Your work is greatly appreciated

**Comment by sonora** [comment]
@Sepero Thanks for reporting back! Clarity like this greatly helps identifying the true root causes for issues!

Sadly, in my experience, providing consistently reliable Android apps has become increasingly difficult as a result of
 - more and more convoluted power saving behaviors and policies,
 - increasing fragmentation betwen versions and even device vendors, with no reliable way to opt out, 
 - and perpetual other OS policy adjustments regarding use of the location service and storage policy,
 - mixing in the bahavior or even mandate to use google services,
 - and enforcing via the Play store (effectively penalizing updated vs. legacy apps there)

It seems outrageous what percentage of developer capacity these days needs to be invested in maintaining software with respec to merely keeping up with this (and debugging related issues), with no per se app-related functionaliy innovation is yet provided. As a result: Progress in software innovation is globally and across the board significantly impacted by this mandate of re-adjusting to OS and vendor compliance, and we can only hope that the 'benefit' that creates is worth this global mandated invest.

**Comment by Sepero** [comment]
While we are on a tangent, I may throw in my remarks. As an end user, I too am disgusted with Google's more and more restricted policy practices and mandate for services.

I currently have a rooted device on Android 10, and I have no plans to upgrade to Android 11/12, nor purchase another Android device. Gnu/Linux phones will likely never be as popular as Android, but they are getting better and better every year, and they will be my first choice upon time to purchase again

**Comment by Lee-Carre** [comment]
@hcsihp

> That's a problem, when I have OsmAnd in background or use several apps with GPS access. When OsmAnd is in foreground again, it takes up to 30 seconds to find the GPS position.

So use something like [My Location](/mirfatif/MyLocation) (available via F-Droid) to keep the GNSS receiver enabled.

**Comment by sonora** [comment]
Since this is still open, I have researched  this again: The "Allow all the time" option will be shown by Android 11 only when an app applies for background location access. There is no use in OsmAnd for this: OsmAnd uses foreground location access when needed (while the map is displayed, during navigation, or trip recording), because it then needs frequent location updates.

Background location access is severely limited by the system in frequency (a few times per hour). There is no use case when OssmAnd needs it.

**Comment by hcsihp** [comment]
Thank you for the discussion. For me as an enduser there are some suggestions helping me to get a faster GPS fix when using OsmAnd or other apps - everything else seems to be a problem of my device in combination with Lineage. I will close this issue.

**Comment by vshcherb** [comment]
Tickets reported: 43589, 43669 allow to run location in background permission.
