### ISSUE TITLE
Update map screen automatically after downloading map using "Download Map" dialog

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#12398]
Additional: It doesn't updates if the map marker toolbar is visible on the screen.
Currently, if you browse the map above area without detailed maps and choose to download it using the "Download Map" dialog that appears above the area, the map screen will not updates automatically to show the downloaded map, it will show the map after zoom change. It works like need if you download a detailed map using the context menu.
• Update map screen, after downloading map using "Download Map" dialog.

- We need to check: https://github.com/osmandapp/OsmAnd/blob/39ecdc4bfe65b876cc285232aa5fcd681ca0d525/OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java#L827

**Comment by cepprice** [comment]
Doesn't reproduce any more
