### ISSUE TITLE
Add direction and destination tags for guidepost pois in details page

### ISSUE THREAD

**Issue by MakiWolf** [osmandapp/OsmAnd#12391]
# 🚀 feature request

### Description

It would be great when osmand support direction and destination tags for guidepost pois in details

For example this poi has this tags (operator tag and the description tag are already supported):
![grafik](https://user-images.githubusercontent.com/73300633/128367954-43227709-b4f8-499d-9781-01a1275a2105.png)
[https://www.openstreetmap.org/node/5111439048#map=19/47.22545/15.42208](https://www.openstreetmap.org/node/5111439048#map=19/47.22545/15.42208)

and some have destination tags like this poi for example:

[https://www.openstreetmap.org/node/4512703670](https://www.openstreetmap.org/node/4512703670)

### Describe the solution you'd like

Just add this tags to osmand resources repository

**See also:**

[https://wiki.openstreetmap.org/wiki/Key:direction_north](https://wiki.openstreetmap.org/wiki/Key:direction_north)

and

[https://wiki.openstreetmap.org/wiki/Key:destination?uselang=en](https://wiki.openstreetmap.org/wiki/Key:destination?uselang=en)

**Comment by letypequividelespoubelles** [comment]
Is there also a tag to indicate the time to destination written on the guidepost ? If yes, it should be added too.
