### ISSUE TITLE
Where is in app purchase product id?

### ISSUE THREAD

**Issue by alizahedi94** [osmandapp/OsmAnd#12405]
Where in the project can I change the in app purchase product ID?

**Comment by comradekingu** [comment]
You can restore purchases in the 4.0 beta (if that is what you are trying to do).

**Comment by vshcherb** [comment]
quite a tricky question, sounds like you are going to redistribute the app with different inapp purchases :-) anyway this question is quite deep in the code and probably could be searched by API name methods
