### ISSUE TITLE
Search: Street with '-' is not listed in results

### ISSUE THREAD

**Issue by totoetco** [osmandapp/OsmAnd#12415]
### Description
A particular street name yields no results in the city of Avignon, France

### How to reproduce?
There is a street in Avignon, France called "Rue du Vieux Sextier". If you look for "Sextier", there are no search results. If you look for "Bonneterie" for "Rue de la Bonneterie", it works fine. It also works fine for online osm.org search. 

screenshot : [<p><img src="https://filesender.breniere.eu/f.php?h=1mOoLa4l&amp;p=1" alt="" width="300" /></p>](url)

Any ideas ?

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: Android 10
Device model: Nokia 6.1 TA-1043

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
Offline maps, Europe France Provence-Alpes-Côte d'Azur 2021-08-08 07:25

**Comment by vshcherb** [comment]
Dash came from https://www.openstreetmap.org/node/3029499038.
