### ISSUE TITLE
Impossible routing spot in Helsinki, Finland

### ISSUE THREAD

**Issue by Aketzu** [osmandapp/OsmAnd#12418]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, OpenRouteService, OSRM, etc.)

### Routing Profile

Car, default options

### Start and end points

![Screenshot_20210808-193929](https://user-images.githubusercontent.com/942914/128639296-7bfbd873-2c18-4ba3-89f2-c0d8f5cd9023.jpg)

https://www.openstreetmap.org/#map=19/60.20841/24.89428

### Error message

Fast route calculation failed (Attempt to invoke virtual method 'java.lang.String net.osmand.binary.BinaryMapRouteReaderAdapter$RouteTypeRule.getTag()' on a null boject reference), fallback to slow calculation

### Is this a regression?

Not tested with other versions

## 🌍 Your Environment

**OsmAnd Version:**
<pre><code>OsmAnd 4.0.4, released: 2021-08-05, Google Play store version</code></pre>

**Device and Android/iOS version:** Oneplus 8 Pro, Android 11, OxygenOS 11.0.7.7.IN11BA

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**

First time testing OsmAnd and immediately found a bug :)

**Comment by vshcherb** [comment]
This issue was there with 4.0.3 but we can't reproduce with latest version and 4.0.4 (updated to latest maps), we plan to release 4.0.5 later this week.

**Comment by vshcherb** [comment]
Reproduced

**Comment by Dima-1** [comment]
osmandapp/OsmAnd-core-legacy#29

**Comment by vshcherb** [comment]
Fixed
