### ISSUE TITLE
2.0.4 crashes when I try to enter an address and select "Choose building" button

### ISSUE THREAD

**Issue by gena01** [osmandapp/Osmand#1241]
I am searching for a house in NY and after i enter all the fields up to the house number it's fine. Once i press "Choose Building" button the app crashes. I think it used to say that there's no buildings available before?

**Comment by xmd5a2** [comment]
Can't reproduce. Please be more verbose. What address you enter?

**Comment by gena01** [comment]
![screenshot_2015-05-18-07-54-50](https://cloud.githubusercontent.com/assets/312125/7680347/98a54e8e-fd33-11e4-9d56-adfef1db4ade.png)

**Comment by xmd5a2** [comment]
Still can't reproduce.. It shows a message "Buildings not found" but not crashes.

**Comment by xmd5a2** [comment]
Can you send us system log using tool something like logcat?

**Comment by gena01** [comment]
05-18 08:27:08.128 E/AndroidRuntime(32524): FATAL EXCEPTION: AsyncTask #5
05-18 08:27:08.128 E/AndroidRuntime(32524): java.lang.RuntimeException: An error occured while executing doInBackground()
05-18 08:27:08.128 E/AndroidRuntime(32524): 	at android.os.AsyncTask$3.done(AsyncTask.java:299)
05-18 08:27:08.128 E/AndroidRuntime(32524): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
05-18 08:27:08.128 E/AndroidRuntime(32524): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
05-18 08:27:08.128 E/AndroidRuntime(32524): 	at java.util.concurrent.FutureTask.run(FutureTask.java:239)
05-18 08:27:08.128 E/AndroidRuntime(32524): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
05-18 08:27:08.128 E/AndroidRuntime(32524): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
05-18 08:27:08.128 E/AndroidRuntime(32524): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
05-18 08:27:08.128 E/AndroidRuntime(32524): 	at java.lang.Thread.run(Thread.java:841)
05-18 08:27:08.128 E/AndroidRuntime(32524): Caused by: java.lang.NullPointerException
05-18 08:27:08.128 E/AndroidRuntime(32524): 	at net.osmand.plus.resources.RegionAddressRepositoryBinary.preloadStreets(RegionAddressRepositoryBinary.java:138)
05-18 08:27:08.128 E/AndroidRuntime(32524): 	at net.osmand.plus.resources.RegionAddressRepositoryBinary.getStreetByName(RegionAddressRepositoryBinary.java:324)
05-18 08:27:08.128 E/AndroidRuntime(32524): 	at net.osmand.plus.activities.search.SearchBuildingByNameActivity$2.doInBackground(SearchBuildingByNameActivity.java:72)
05-18 08:27:08.128 E/AndroidRuntime(32524): 	at net.osmand.plus.activities.search.SearchBuildingByNameActivity$2.doInBackground(SearchBuildingByNameActivity.java:49)
05-18 08:27:08.128 E/AndroidRuntime(32524): 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
05-18 08:27:08.128 E/AndroidRuntime(32524): 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
05-18 08:27:08.128 E/AndroidRuntime(32524): 	... 4 more
05-18 08:27:08.128 I/ActivityManager(673): Notify an ApplicationCrash

There's actually more weird stuff unrelated to the crash. Should I paste it all here?

**Comment by vshcherb** [comment]
It used to be a problem with map data, so I guess the map needs to be redownloaded, it is better to search that street just in New York then the buildings will show up.
