### ISSUE TITLE
Crash on opening Traveling (Beta)

### ISSUE THREAD

**Issue by d4f5409d** [osmandapp/OsmAnd#12426]
Device : OnePlus8
Brand : OnePlus
Model : -
Product : OnePlus8
Build : -
Version : 11
App Version : OsmAnd~
Apk Version : 3.9.10 400

Log:
`Version OsmAnd~ 3.9.10 30.07.2021 5:30:59 Apk Version : 3.9.10 400 Exception occured in thread Thread[AsyncTask #1,5,main] : java.lang.RuntimeException: An error occurred while executing doInBackground() 	at android.os.AsyncTask$4.done(AsyncTask.java:415) 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383) 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252) 	at java.util.concurrent.FutureTask.run(FutureTask.java:271) 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 	at java.lang.Thread.run(Thread.java:923) Caused by: java.lang.OutOfMemoryError: Failed to allocate a 56712 byte allocation with 15872 free bytes and 15KB until OOM, target footprint 536870912, growth limit 536870912 	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:125) 	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:65) 	at com.google.protobuf.CodedInputStream.readString(CodedInputStream.java:233) 	at net.osmand.binary.BinaryMapPoiReaderAdapter.readPoiPoint(BinaryMapPoiReaderAdapter.java:797) 	at net.osmand.binary.BinaryMapPoiReaderAdapter.readPoiData(BinaryMapPoiReaderAdapter.java:660) 	at net.osmand.binary.BinaryMapPoiReaderAdapter.searchPoiIndex(BinaryMapPoiReaderAdapter.java:551) 	at net.osmand.binary.BinaryMapIndexReader.searchPoi(BinaryMapIndexReader.java:1382) 	at net.osmand.plus.wikivoyage.data.TravelObfHelper.searchAmenity(TravelObfHelper.java:171) 	at net.osmand.plus.wikivoyage.data.TravelObfHelper.loadPopularArticles(TravelObfHelper.java:127) 	at net.osmand.plus.wikivoyage.data.TravelObfHelper.initializeDataToDisplay(TravelObfHelper.java:113) 	at net.osmand.plus.wikivoyage.explore.WikivoyageExploreActivity$LoadWikivoyageData.doInBackground(WikivoyageExploreActivity.java:393) 	at net.osmand.plus.wikivoyage.explore.WikivoyageExploreActivity$LoadWikivoyageData.doInBackground(WikivoyageExploreActivity.java:379) 	at android.os.AsyncTask$3.call(AsyncTask.java:394) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	... 4 more Version OsmAnd~ 3.9.10 30.07.2021 5:31:27 Apk Version : 3.9.10 400 Exception occured in thread Thread[AsyncTask #1,5,main] : java.lang.RuntimeException: An error occurred while executing doInBackground() 	at android.os.AsyncTask$4.done(AsyncTask.java:415) 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383) 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252) 	at java.util.concurrent.FutureTask.run(FutureTask.java:271) 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 	at java.lang.Thread.run(Thread.java:923) Caused by: java.lang.OutOfMemoryError: Failed to allocate a 14320 byte allocation with 2216 free bytes and 2216B until OOM, target footprint 536870912, growth limit 536870912 	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:225) 	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:65) 	at com.google.protobuf.CodedInputStream.readString(CodedInputStream.java:233) 	at net.osmand.binary.BinaryMapPoiReaderAdapter.readPoiPoint(BinaryMapPoiReaderAdapter.java:797) 	at net.osmand.binary.BinaryMapPoiReaderAdapter.readPoiData(BinaryMapPoiReaderAdapter.java:660) 	at net.osmand.binary.BinaryMapPoiReaderAdapter.searchPoiIndex(BinaryMapPoiReaderAdapter.java:551) 	at net.osmand.binary.BinaryMapIndexReader.searchPoi(BinaryMapIndexReader.java:1382) 	at net.osmand.plus.wikivoyage.data.TravelObfHelper.searchAmenity(TravelObfHelper.java:171) 	at net.osmand.plus.wikivoyage.data.TravelObfHelper.loadPopularArticles(TravelObfHelper.java:127) 	at net.osmand.plus.wikivoyage.data.TravelObfHelper.initializeDataToDisplay(TravelObfHelper.java:113) 	at net.osmand.plus.wikivoyage.explore.WikivoyageExploreActivity$LoadWikivoyageData.doInBackground(WikivoyageExploreActivity.java:393) 	at net.osmand.plus.wikivoyage.explore.WikivoyageExploreActivity$LoadWikivoyageData.doInBackground(WikivoyageExploreActivity.java:379) 	at android.os.AsyncTask$3.call(AsyncTask.java:394) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	... 4 more Version OsmAnd~ 3.9.10 09.08.2021 7:09:22 Apk Version : 3.9.10 400 Exception occured in thread Thread[AsyncTask #11,5,main] : java.lang.RuntimeException: An error occurred while executing doInBackground() 	at android.os.AsyncTask$4.done(AsyncTask.java:415) 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383) 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252) 	at java.util.concurrent.FutureTask.run(FutureTask.java:271) 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 	at java.lang.Thread.run(Thread.java:923) Caused by: java.lang.OutOfMemoryError: Failed to allocate a 183096 byte allocation with 160888 free bytes and 157KB until OOM, target footprint 536870912, growth limit 536870912 	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:125) 	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:65) 	at com.google.protobuf.CodedInputStream.readString(CodedInputStream.java:233) 	at net.osmand.binary.BinaryMapPoiReaderAdapter.readPoiPoint(BinaryMapPoiReaderAdapter.java:797) 	at net.osmand.binary.BinaryMapPoiReaderAdapter.readPoiData(BinaryMapPoiReaderAdapter.java:660) 	at net.osmand.binary.BinaryMapPoiReaderAdapter.searchPoiIndex(BinaryMapPoiReaderAdapter.java:551) 	at net.osmand.binary.BinaryMapIndexReader.searchPoi(BinaryMapIndexReader.java:1382) 	at net.osmand.plus.wikivoyage.data.TravelObfHelper.searchAmenity(TravelObfHelper.java:171) 	at net.osmand.plus.wikivoyage.data.TravelObfHelper.loadPopularArticles(TravelObfHelper.java:127) 	at net.osmand.plus.wikivoyage.data.TravelObfHelper.initializeDataToDisplay(TravelObfHelper.java:113) 	at net.osmand.plus.wikivoyage.explore.WikivoyageExploreActivity$LoadWikivoyageData.doInBackground(WikivoyageExploreActivity.java:393) 	at net.osmand.plus.wikivoyage.explore.WikivoyageExploreActivity$LoadWikivoyageData.doInBackground(WikivoyageExploreActivity.java:379) 	at android.os.AsyncTask$3.call(AsyncTask.java:394) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	... 4 more Version OsmAnd~ 3.9.10 09.08.2021 7:10:04 Apk Version : 3.9.10 400 Exception occured in thread Thread[AsyncTask #3,5,main] : java.lang.RuntimeException: An error occurred while executing doInBackground() 	at android.os.AsyncTask$4.done(AsyncTask.java:415) 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383) 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252) 	at java.util.concurrent.FutureTask.run(FutureTask.java:271) 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 	at java.lang.Thread.run(Thread.java:923) Caused by: java.lang.OutOfMemoryError: Failed to allocate a 12688 byte allocation with 904 free bytes and 904B until OOM, target footprint 536870912, growth limit 536870912 	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:225) 	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:65) 	at com.google.protobuf.CodedInputStream.readString(CodedInputStream.java:233) 	at net.osmand.binary.BinaryMapPoiReaderAdapter.readPoiPoint(BinaryMapPoiReaderAdapter.java:797) 	at net.osmand.binary.BinaryMapPoiReaderAdapter.readPoiData(BinaryMapPoiReaderAdapter.java:660) 	at net.osmand.binary.BinaryMapPoiReaderAdapter.searchPoiIndex(BinaryMapPoiReaderAdapter.java:551) 	at net.osmand.binary.BinaryMapIndexReader.searchPoi(BinaryMapIndexReader.java:1382) 	at net.osmand.plus.wikivoyage.data.TravelObfHelper.searchAmenity(TravelObfHelper.java:171) 	at net.osmand.plus.wikivoyage.data.TravelObfHelper.loadPopularArticles(TravelObfHelper.java:127) 	at net.osmand.plus.wikivoyage.data.TravelObfHelper.initializeDataToDisplay(TravelObfHelper.java:113) 	at net.osmand.plus.wikivoyage.explore.WikivoyageExploreActivity$LoadWikivoyageData.doInBackground(WikivoyageExploreActivity.java:393) 	at net.osmand.plus.wikivoyage.explore.WikivoyageExploreActivity$LoadWikivoyageData.doInBackground(WikivoyageExploreActivity.java:379) 	at android.os.AsyncTask$3.call(AsyncTask.java:394) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	... 4 more`

**Comment by vshcherb** [comment]
This issue should be fixed with 4.0 release
