### ISSUE TITLE
2.0.4 reboots a phone on launch

### ISSUE THREAD

**Issue by theirix** [osmandapp/Osmand#1242]
I used OsmAnd+ from Google Play on my Android phone (Nexus One, rooted, CM 7.1, Link2SD) and recently upgraded it to 2.0.1 and 2.0.4 from pre-2.0. When I launched osmand the phone hangs for ten seconds and then reboots (just after bootloader).

I did not delete a directory with maps and tracks (/sdcard/osmand). I gathered two logs for different installation types:
1. https://gist.github.com/theirix/61106f0d9fae4f94eec5. OsmAnd installed with Link2SD (app linked with a symlink from external sd card to the /app directory). It crashed.
2. https://gist.github.com/theirix/61eadf2ce83898010634. I wiped OsmAnd data and cache, uninstalled and installed to standard internal location. It crashed again.

**Comment by alexey-pelykh** [comment]
Seems like your GPS driver crashes (/system/lib/hw/gps.mahimahi.so) in both cases what causes system to reboot. Unfortunately, we can not do anything about that.

**Comment by theirix** [comment]
The cause of crash was frozen (disabled in terms of TitaniumBackup) GPSStatus app. OsmAnd started to work again after I had unfrozen GPSStatus. Thank you for the idea.
