### ISSUE TITLE
Error in determining the length of the track

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#12437]
If the track is off, then its length is displayed incorrectly.

![Screenshot_2021-08-10-21-26-23-787_net.osmand.plus.jpg](https://user-images.githubusercontent.com/12549744/128914707-d37a36a7-93e4-48ca-8633-64cdd2e392a1.jpg)

![Screenshot_2021-08-10-21-26-33-799_net.osmand.plus.jpg](https://user-images.githubusercontent.com/12549744/128914752-5f76b949-f3ee-419b-b4b7-07c223d6eb26.jpg)

Link to the track.
https://www.dropbox.com/s/4jsm6uv9l5qq0yv/2021-08-06_23-44_fri.gpx?dl=0

### Your Environment
OsmAnd~ 4.0.0#32540m, дата выпуска: 2021-08-10

**Comment by Nine-Tailed** [comment]
hmm, I don't see this bug again.
OsmAnd~ 4.0.0#32544m, дата выпуска: 2021-08-11

**Comment by vshcherb** [comment]
hm... let's see if it comes back
