### ISSUE TITLE
Add Lighthouse sign to the 'topo' map style

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#12448]
<table style="width:100%">
  <tr>
    <th>Topo</th>
    <th>OsmAnd</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/80623554/129028793-237bbca0-a7bc-4d03-93f5-95e641a17a6e.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/80623554/129028801-c923353e-4fcf-4772-b1cb-038b0d92531f.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by xmd5a2** [comment]
![Screenshot_2022-12-08_10-45-05](https://user-images.githubusercontent.com/5829014/206388617-ec368870-f875-47cf-a7dc-2e2a1d5e5b44.png)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14012mqta, released: 2022-12-09
Done
[Map](https://drive.google.com/file/d/1QJ0PQO2SaWFKgPUw_L_jssy8w2OCjtvL/view?usp=sharing)

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/206712777-380ed2c2-25d6-492e-b439-29b2504d4367.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by dmpr0** [comment]
- [ ]  Don't visible on iOS, tested on TestFlight 4.4.3.1
<table style="width:100%">
  <tr>
    <th colspan=2>iOS</th>
  </tr>
  <tr>
    <th>OsmAnd</th>
    <th>Topo</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/209945110-ba51540b-685e-45d8-9f6b-3f7cb8813ec1.jpeg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/209945112-895522fd-f2ad-4d0c-b2ff-c633e45b780a.jpeg"  width="300" height="auto"/> </td>
  </tr>
</table>   


<table style="width:100%">
  <tr>
    <th colspan=2>Android</th>
  </tr>
  <tr>
    <th>OsmAnd</th>
    <th>Topo</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/209945489-7c0fb279-3f90-4c1e-bf1b-38b6e782e2c2.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/209945494-64175969-42e0-43d4-b4d1-9bd44d2a58dc.png"  width="300" height="auto"/> </td>
  </tr>
</table>   

![Screenshot_20221229-132833]()
![Screenshot_20221229-132900]()

**Comment by xmd5a2** [comment]
Commit is merged to r4.3 branch

**Comment by Zirochkabila** [comment]
4.4.4.1
Done

`46.49653° N, 30.76004° E`

https://user-images.githubusercontent.com/104760013/212661086-93e78bcd-56e5-4338-aaaa-b1895b5dc22f.mp4
