### ISSUE TITLE
Replace tag office=estate_agent abandoned

### ISSUE THREAD

**Issue by franco999** [osmandapp/Osmand#1244]
According to the OSM wiki, the tag "office = estate_agent" is abandoned and should be replaced by "shop = estate_agent".

https://wiki.openstreetmap.org/wiki/Tag:shop%3Destate_agent

![estate_agent](https://cloud.githubusercontent.com/assets/12088580/7671744/571744a4-fcb1-11e4-9256-b6170adbf6e2.png)

**Comment by xmd5a2** [comment]
Fixed

**Comment by franco999** [comment]
Thanks!
