### ISSUE TITLE
Cycling routes is not disappear after disabling

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#12449]
### How to reproduce?
Enable and disable the Cycling route.

![image](https://user-images.githubusercontent.com/80623554/129032547-169bdf97-6804-40de-a14c-bd43885a84a4.png)
![image](https://user-images.githubusercontent.com/80623554/129032827-c13e8999-7fa0-4b60-9fef-de4d49cbcf4b.png)
![image](https://user-images.githubusercontent.com/80623554/129032848-495d1fcf-0878-4e77-a4f5-8247ba9a2775.png)

**Comment by scaidermern** [comment]
Can confirm. The bicycle routes stay visible after disabling them (the color changes a little after moving/zooming the map). However it looks like this only happens when the bicycle route type is set to node network.

**Comment by vshcherb** [comment]
Well yes, it is done on purpose for bicycle mode. It was introduced much earlier than all options appeared. And it is a good question now should we disable it or not. Will transform it into discussion cause it's not clear now.
