### ISSUE TITLE
Crash during Backup

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#12447]
### Description
When I press backup application freezes and crashes. All the time I have 'Conflicts' notification.

### How to reproduce?
Press backup and when file 14 % of the file loaded the application freezes and crashes
<table style="width:100%">
  <tr>
    <th><img src="https://user-images.githubusercontent.com/80623554/129026069-d4905874-86aa-4d72-b271-6165b5e37b54.png"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/80623554/129026259-8aceda82-f6ea-43d4-8245-7fb6f8948436.png"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/80623554/129026799-e10c6fae-08d7-4a74-a20b-b55f380ba469.png"  width="300" height="auto"/> </th>
  </tr>
</table>

[exception (10).log](https://github.com/osmandapp/OsmAnd/files/6968284/exception.10.log)

### Your Environment
OsmAnd Version: OsmAnd 4.0.4
Android/iOS version: Android 9
Device model: Experience XZ1

**Comment by vshcherb** [comment]
java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 11899104 free bytes and 11MB until OOM, max allowed footprint 536870912, growth limit 536870912; failed due to fragmentation (largest possible contiguous allocation 0 bytes)
	at java.util.ArrayList.iterator(ArrayList.java:834)
	at net.osmand.plus.resources.AsyncLoadingThread.updateBitmapTilesCache(AsyncLoadingThread.java:103)
	at net.osmand.plus.resources.AsyncLoadingThread.run(AsyncLoadingThread.java:42)

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/commit/69f4ffc28dadc77cd682cef4ed6730d298db7080

**Comment by dmpr0** [comment]
Still reproducible.
Trying to back up the full Norway map.
[exception (26).log](https://github.com/osmandapp/OsmAnd/files/6993207/exception.26.log)
Device : CAP_sprout
Brand : Nokia
Model : Nokia 5.3
Product : CaptainAmerica_00WW
Build : 00WW_2_210
Version : 11
App Version : OsmAnd+
Apk Version : 4.1.0#32575m 410
