### ISSUE TITLE
[Icon request] More "Maps" icon

### ISSUE THREAD

**Issue by julianfairfax** [osmandapp/OsmAnd#12445]
# 🚀 Icon request

### Description

The current app icon isn't easily identifiable as being "Maps".

### Describe the solution you'd like

An app icon in the style of the OpenStreetMap icon but respecting Android's app guidelines would make it more obvious that this is a maps app and that it's a maps app for OpenStreetMap.

### Describe alternatives you've considered

I could ignore it, but I'm very particular about small details.

**Comment by julianfairfax** [comment]
It would also be nice to have a unified accent colour as both orange and blue seem to be present.

**Comment by julianfairfax** [comment]
OpenStreetMap and GNOME Maps icons for inspiration:
![image](https://user-images.githubusercontent.com/43753131/130283618-91b3761d-66e4-4624-b7fb-835578891af5.png)
![image](https://user-images.githubusercontent.com/43753131/130283563-5d68bded-86f7-42df-bbaf-7bc563186ab3.png)

**Comment by julianfairfax** [comment]
Sorry for closing and opening this again, would you still be up for making this change? Thanks for your wonderful app!

**Comment by vshcherb** [comment]
There is no plan to change it as I know

**Comment by julianfairfax** [comment]
Out of interest, would you happen to know why this accent colour was chosen? Its not exactly the first colour I'd think of using for a maps app

**Comment by vshcherb** [comment]
Historically done like that, probably you can google old icon
![image](https://user-images.githubusercontent.com/1042025/132220637-3cc29e2d-af54-44d7-aff1-afdfe7a542be.png)

**Comment by julianfairfax** [comment]
I know it was historically done like that, but my question is why that colour was chosen?

**Comment by vshcherb** [comment]
no idea
