### ISSUE TITLE
Weird walking navigation

### ISSUE THREAD

**Issue by letypequividelespoubelles** [osmandapp/OsmAnd#12451]
### Description
Trying to go from one side to the other side of this [main road](https://www.openstreetmap.org/node/3290203208), the pedestrian navigation makes a long deviation to cross the sreet (see image) whereas there is pedestrian cross in the OSM data. 

### How to reproduce?
Try to go for exemple from [there](https://www.openstreetmap.org/node/3290203208) to [there](https://www.openstreetmap.org/node/1051453456)

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version:
Device model:

**Maps used (online or offline):**   
Last offline + osmand live update, but same happens without live update
![photo_2021-08-11_21-23-12](https://user-images.githubusercontent.com/54240434/129091113-39699037-b6ec-408d-b046-e055860e12f3.jpg)

**Comment by scaidermern** [comment]
> here is pedestrian cross in the OSM data

Where? I can't see it in the data.

**Comment by letypequividelespoubelles** [comment]
@scaidermern Ok, my bad, I thought that two highway=crossing very close were enough in the data. 

I will add the connection between the other highway=crossing of this road. 

Many thanks !

**Comment by scaidermern** [comment]
> @scaidermern Ok, my bad, I thought that two highway=crossing very close were enough in the data.

No, it always requires a connecting way between them. The router can't assume that you can walk from one to the other if there is no connection. There could be some obstacle between them, or they could be located on different levels (bridges, tunnels etc.)

> I will add the connection between the other highway=crossing of this road.

I already did for a few more locations. Maybe you can spot a few more :) I can imagine that the same problem exists in other parts of this city.
