### ISSUE TITLE
Map language: choose between different Chinese types

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#12464]
Configure Map > Map language menu currently contains only on "Chinese" item, we need to add rename in and add both:
• Chinese (Traditional)
• Chinese (Simplified)
• Also we can offer "pinyin" instead of transliteration.
https://wiki.openstreetmap.org/w/index.php?title=Multilingual_names&uselang=uk#China

User requests:
https://github.com/osmandapp/OsmAnd/issues/9683
https://github.com/osmandapp/OsmAnd/issues/9682
https://github.com/osmandapp/OsmAnd/issues/8265
https://github.com/osmandapp/OsmAnd/issues/5616

**Comment by vshcherb** [comment]
https://chinese.stackexchange.com/questions/21035/api-for-transliterating-a-traditional-character-writing-the-pinyin
https://www.mdbg.net/chinese/dictionary?page=cc-cedict

**Comment by vshcherb** [comment]
997 261 | name:zh
85 086 | name:zh-Hant
80 555 | name:zh_pinyin
59 421 | name:zh-Hans

name:zh_pinyin - should be used if name:en is not present

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-tools/pull/472
