### ISSUE TITLE
Missing icons for custom POI filter in POI overlay and quick action

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#12467]
Some/many POIs that have been created via a custom filter only show a generic icon in the POI overlay settings and the quick action panel.

Example:
Search widget with two custom POI filters "Bench" and "Camp site", both with their correct icons.
![photo_2021-08-13_13-56-55](https://user-images.githubusercontent.com/1040784/129353950-527a5262-e3b0-4dad-ba4a-70e0c9d810ce.jpg)

POI overlay dialog only showing the correct icon for "Bench" but not for "Camp site":
![photo_2021-08-13_13-56-50](https://user-images.githubusercontent.com/1040784/129354002-69169c65-bcce-4af0-be3c-f8799aa7692e.jpg)

Quick action panel with the same problem, showing the correct icon for "Bench" but not for "Camp site":
![photo_2021-08-13_13-56-59](https://user-images.githubusercontent.com/1040784/129354071-01134135-e387-4d83-ba0d-f76f0a48f4bb.jpg)

This happens for various other POIs, too. For example for a parking POI filter.

**Comment by dmpr0** [comment]
# Review
- [ ] `Restrooms` doesn't show icon in `Configure Map > POI Overlay`
- [ ] Restroom show two items in `POI Overlay`
- [ ] After creating `Bench` it was duplicated in `POI Overlay` too.
