### ISSUE TITLE
OsmAnd does not announce names of state or interstate highways

### ISSUE THREAD

**Issue by dbolton** [osmandapp/Osmand#1246]
Steps to reproduce bug:
1. Follow directions onto a US state or interstate highway

Expected behavior: OsmAnd should announce clear directions about which highway to turn onto (e.g. "Turn left onto I-70" (or "Turn left onto Interstate 70")

Actual behavior: OsmAnd just says "Turn left"

Discussion: OsmAnd gives clear directions for named roads (such as "Turn left on Northwest Valley View Road." However it never announces the name of major highways. I haven't looked at the code, but I wonder if OsmAnd has trouble determining that a left onto an on-ramp should be announced as a left onto I-70. 

OsmAnd 2.0.4 using offline map of Missouri, USA.

**Comment by fred702** [comment]
OsmAnd supports the tags destination and destination:ref. Check to see if those tags are present in your area. If not, this isn't a bug just a lack of data (for the moment).

Here's a guide on how to tag: https://www.openstreetmap.org/user/mvexel/diary/22419

In your example it would probably be appropriate to tag the highway=motorway_link way leading to I 70 with "destination:ref=I 70"

**Comment by jfburke3** [comment]
I will confirm what @fred702 says.  For the exits that I use where the _link road is tagged with destination= information, it does tell you where to go.  "Keep right to I 20 <pause> Atlanta".  Although a lot of us would prefer it say "Exit right" when hitting a freeway exit node.

**Comment by sonora** [comment]
Regarding "Keep" vs. "Exit": I totally agree. I authored the voice file, but for now, from what I see, we have no good way to discern in our code (and likely not in the map data either?) what situation truly is an actual exit vs. what looks more like a fork. As soon as we implement something to tell, I will certainly make the distinction. - Best, Hardy

**Comment by fred702** [comment]
>no good way to discern what situation truly is an actual exit vs. what looks more like a fork

Have you considered supporting the [junction:ref](https://wiki.openstreetmap.org/wiki/Key:junction:ref) tag?

**Comment by sonora** [comment]
deprecated, many improvements have happened since.
