### ISSUE TITLE
Track appearance for the current record is not saved

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#12462]
### Description
When you change track appearance during track recording after stop recording the color reset to the default (That selected in the Configure map menu). For example, you select blue color for the current track recording and when you stop and save track it changes color to red (because it was selected in the Configure map menu).
![image](https://user-images.githubusercontent.com/80623554/129321597-a0bc5577-dbb5-449d-8b05-b782aaa3215d.png)
![image](https://user-images.githubusercontent.com/80623554/129321613-cf35076a-9e92-41ca-9382-3d701b1a3856.png)
![image](https://user-images.githubusercontent.com/80623554/129321632-bb335944-681d-4deb-b42d-54b80886a775.png)
![image](https://user-images.githubusercontent.com/80623554/129321648-1f3303b4-6c67-4656-94b4-97b7aa18e0d4.png)

### How to reproduce?
Start track recording->change color for the track ->press save

### Your Environment
OsmAnd Version: 4.0.4
Android/iOS version: Android 9
Device model: Experience XZ1

**Maps used (online or offline):**   does not relate to the map
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by vshcherb** [comment]
I think it should not be saved cause it's a good way to distinguish recording track vs recorded track. So in that case it's a feature. In future we should be able to change default track appearance, so that will be customizable separately
