### ISSUE TITLE
offroad rendering does not take into consideration surface tag (paved/unpaved)

### ISSUE THREAD

**Issue by cmoffroad** [osmandapp/OsmAnd#12479]
### Discussed in https://github.com/osmandapp/OsmAnd/discussions/12476

<div type='discussions-op-text'>

<sup>Originally posted by **cmoffroad** August 14, 2021</sup>
As an active OSM contributor and off-road enthusiast, I love OSMAnd and the live maps updates feature which allows me to do some quick updates before a ground survey.

One major pain I have with the offroad rendering is that surface is not taken into account.
e.g. a paved track will be shown like an unpaved track, an unpaved tertiary road will look like a paved one...

I am currently improving the minor road network in northern Thailand, and one part is to update existing highway classifications and add a surface tag when missing. Because of rendering limitations, there has been a bad habit of tagging unpaved roads as track without a surface, even if these roads are in fact tertiary, unclassified, residential, service...

My proposal would be to either:
- improve existing offroad renderer to incorporate surface tag information (e.g. using dashed or straight casing/stroke lines)
- create a new separate style to achieve this.

I already found a few resources online:
- code related to each rendering style e.g. offroad is here https://github.com/osmandapp/OsmAnd-resources/blob/master/rendering_styles/offroad.render.xml
- documentation https://docs.osmand.net/ru/main@latest/development/osmand-file-formats/osmand-rendering-style

What I am not finding is instructions on how to test rendering on my local machine.

PS: my goal is not to build my own Android application, but to have an improved or separate offroad style in the official APP so that other users can use it.

Any pointers would be much appreciated. Thanks!</div>

**Comment by vshcherb** [comment]
Talked to Offroad contributor he doesn't see a visual possibility to add surface information to not make it less colourful as I see for now the agreement is to start with new rendering style based on Topo (similar to Offroad)
