### ISSUE TITLE
2.0.4 with the latest map for USA- New York i am seeing wrong information

### ISSUE THREAD

**Issue by gena01** [osmandapp/Osmand#1247]
So I am trying to figure this strange thing out. I live in "Brooklyn, NY". But when i browse my neighborhood osmand shows "Long Island" which is wrong and off by quite a few miles. I am not sure that's happening since the osm website shows "Brooklyn" just fine. I am not sure if it's a data/map error I can edit/fix or a bug in osmand.

**Comment by fred702** [comment]
The "Long Island" that appears is not a neighborhood, but a geographical feature. See the OSM feature: https://www.openstreetmap.org/relation/3955977

OsmAnd renders the name of an island at least once on the screen if it is tagged as a way or relation, no matter how far you zoom in.

**Comment by gena01** [comment]
I guess I am a newbie here. Never knew that Brooklyn was part of "Long Island" even after living here for >25 years.. Anyway to show "Brooklyn" instead, just like other maps/tools?

**Comment by xmd5a2** [comment]
Don't see any trouble
![_2015-08-04_14-49-49](https://cloud.githubusercontent.com/assets/5829014/9060016/385e7452-3ab8-11e5-8e76-85b1c6c284ad.png)

**Comment by vshcherb** [comment]
I think we fixed it.
