### ISSUE TITLE
Remove Mapillary

### ISSUE THREAD

**Issue by d4f5409d** [osmandapp/OsmAnd#12480]
Mapillary got discontinued, so it's useless at this point. It would be better to remove it, and instead, make a better support for OpenPlaceReviews.

**Comment by Dani3I** [comment]
As far as I know mapillary has not been discontinued. But maybe I am wrong, where do you get this information?

**Comment by d4f5409d** [comment]
Weird. Last time I wanted to use Mapillary, on the Play Store page, it was stated, that's it's discontinued. It didn't even let me in. Now it isn't there that it's discontinued, and it did let me in. I don't kbow what's going on.

**Comment by vshcherb** [comment]
We have a separate issue related to  Mapillary -> OpenStreetCam so there is no need in this issue.
