### ISSUE TITLE
Turn lanes are shown as through lanes in lane overview

### ISSUE THREAD

**Issue by Zero3** [osmandapp/OsmAnd#12481]
### Description

OsmAnd does not always show the correct lanes in the lane overview.

In the example shown below, when driving on the road from north west to south east, the road is splitting into two left turn lanes and two through lanes before the junction at the bottom of the picture:

![image](https://user-images.githubusercontent.com/82504/129462870-14dfa48b-1897-427a-927e-586fbfbe81fb.png)

(OSM link: https://www.openstreetmap.org/edit?editor=id#map=18/55.37221/10.44506)

The two left lanes are mapped as a single way in OSM with `lanes=2` and `turn=left`. The two through lanes are mapped as a single way with `lanes=2`. This looks correct to me, but as seen below, OsmAnd shows 4 through lanes instead:

![Screenshot_20210814-163456](https://user-images.githubusercontent.com/82504/129462852-c78b8b8e-6e82-46a5-a5fb-d0ecb5c8de2a.png)

On a side note, the "turn slightly right" instruction (see top-left corner of the screen) seems wrong as well, given that I was to drive straight ahead.

### Your Environment
OsmAnd Version: 4.0.5
Android/iOS version: 10

**Maps used (online or offline):** Online

**Comment by vshcherb** [comment]
I think the lanes are displayed correctly i.e. 4 lanes 2 + 2. Of course it is possible to improve how it's rendered with turn:lanes tag but even without it, it looks ok.

This particular junction has a problem that https://www.openstreetmap.org/way/25356914 (cause it's a link) should not be part of any announcement and that's what could be improved potentially.

**Comment by vshcherb** [comment]
The issue was here https://github.com/osmandapp/OsmAnd/commit/99f8f384be36c12cdc80a60d1f4375d9afea21a4

**Comment by Zero3** [comment]
@vshcherb thanks for getting back :)

> I think the lanes are displayed correctly i.e. 4 lanes 2 + 2. Of course it is possible to improve how it's rendered with turn:lanes tag but even without it, it looks ok.

I agree that 4 lanes is a correct number to show. The issue is that they all show as "go straight", even though the two to the left should be shown as "turn left". I have seen OsmAnd show turn lanes correctly, so it seems like a bug that it does not do so in this case?

> This particular junction has a problem that https://www.openstreetmap.org/way/25356914 (cause it's a link) should not be part of any announcement and that's what could be improved potentially.

Just to understand correctly: When you say "announcement", do you mean the instruction at the top-left of the screen? I.e. the "turn slightly right" arrow? If so, I agree :).

(I do not recall if there was a voice announcement at this point or not.)

**Comment by vshcherb** [comment]
Yes, in most of situations these alerts should not appear if you go straight, though they could appear if the roads are the same priority. Here it's not the case (secondary_link vs secondary), so the fix is easy but it needs to be double checked and aligned with other issues.

**Comment by Zero3** [comment]
@sonora let me know if I can assist you with any data or testing or something. I can also drive to the place mentioned and test any fix you might have.

**Comment by Zero3** [comment]
Besides the "secondary_link vs secondary" announcement bug that @vshcherb mentions above, i have a suspicion about the cause of the original issue. Given my example above:

* When tagged as `turn:lanes=left|left`, OsmAnd seems to show the turn lanes correctly.
* When tagged as `turn=left`, OsmAnd seems to ignore the tag and treat the lanes as `through`.

Both variations are documented on https://wiki.openstreetmap.org/wiki/Key:turn#Current_usage

**Comment by Zero3** [comment]
@Dima-1 @vshcherb It seems like you guys fixed the announcement bug, but what about the original issue? Which seems to be that the `turn` tag is ignored and only the `turn:lanes` tag is working (see above: https://github.com/osmandapp/OsmAnd/issues/12481#issuecomment-909367472)

**Comment by vshcherb** [comment]
Nothing to fix, "turn:lanes" is a supported mechanism to clarify turn lanes on the road

**Comment by Zero3** [comment]
@vshcherb Do you mean that you only intend to support the `turn:lanes` tag, and not the `turn` tag? These are both used in the OSM data, and are documented accordingly at https://wiki.openstreetmap.org/wiki/Key:turn#Current_usage:

**When turns apply similarly to all lanes in the same direction (or when there's a single lane per direction)**:

* `turn=*`
* `turn:forward=*`
* `turn:backward=*`
* `turn:both_ways=*`

**To specify different turn indications for each lane when there are multiple lanes in the same direction (see below)**:

* `turn:lanes=*`
* `turn:lanes:forward=*`
* `turn:lanes:backward=*`
* `turn:lanes:both_ways=*`

**Comment by vshcherb** [comment]
```turn=* ``` is not supported

**Comment by Zero3** [comment]
@vshcherb Thanks for the response. What I am trying to understand is whether it is intentional that OsmAnd does not support `turn=*`. If not, and it is just something that has not been implemented yet, I could create a feature request for it. But I do not want to do that if there is some kind of good reason not to support the tag.

**Comment by vshcherb** [comment]
Well, it's simple we have limited capacity and priorities.
Usually tags with less than 10 000 capacity not considered to be implemented at all only some exceptions. And another thing that the tail of features is always truncated that we can complete prioritized tasks for a next half-year and a year.

So there is nothing wrong to create a feature request and if it get's closed you could remind in a year or 2. I think the development capacity is the biggest factor here. So I would say today you should probably not create request for turn support comparing to already created issues.

**Comment by Zero3** [comment]
@vshcherb thanks for the explanation :+1:. Makes sense. I will not create a feature request now then, but adapt my mapping habbits to always use `turn:lanes`, even where a `turn` tag would have been sufficient.

I updated the mentioned OSM wiki page with this information ([diff](https://wiki.openstreetmap.org/w/index.php?title=Key:turn&diff=prev&oldid=2200352)), so that other mappers can be aware of this as well.
