### ISSUE TITLE
Plan route update has broken route between points transport method selection

### ISSUE THREAD

**Issue by k4vej** [osmandapp/OsmAnd#12486]
### Description

Just tried to plan a new route, first time since app update to v4.0.4

I can see from the release notes there is some plan route updates - so update is most likely the cause, as prior to this update I have recently successfully planned several routes.

When trying to plan route, changing from default "straight line" mode to snap to grid using any transport method, driving|cycling|walking - it fails to update the track on the UI and does not calculate the new total distance - like its not even registered the user change in selection.

### How to reproduce?

Plan route > add some points > change from straight line mode to snap to any transport method - it no updatey.

### Your Environment
OsmAnd Version: 4.0.4
Android/iOS version: 10
Device model: Motorola G7 Power

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by vshcherb** [comment]
Weird can't reproduce it. Some screenshots?
