### ISSUE TITLE
Help to improve 2 french translation strings ("Démarrer" should be "Départ")

### ISSUE THREAD

**Issue by ldmpub** [osmandapp/OsmAnd#12488]
In english "Start" can be used as a verb or as a noun meaning "beginning" or "start point" and these 2 meanings can not be translated by the same word in french 😱.

Can someone please direct me to the 2 translation strings (in https://hosted.weblate.org/projects/osmand/ at least for Android) to correct strings displayed in the below contexts:

![NEW - Départ 2  OsmAnd Nightly](https://user-images.githubusercontent.com/1452146/129478182-d0af4c8e-d347-41d3-9308-cf5b7ada8f6c.jpg)

![NEW - Départ 1  OsmAnd - How to translate](https://user-images.githubusercontent.com/1452146/129478175-94633d9d-0ae4-4c5f-8389-8862515569a8.jpg)

both words should be set to "Départ" in french (instead of the current "Démarrer").

Thanks for your help,

**Comment by ldmpub** [comment]
Note: I guess this issue is not particular to french language and maybe adding some comments / help in weblate on these strings should help translators to perform better translation for all languages.

**Comment by xarich** [comment]
Hi,

Thanks to all of you dev for this fix 👍.

It was far from being just a french translation issue but requires an app code improvement which is now done => I'm eager to use the app with these label improvements 😉.

**Comment by ldmpub** [comment]
Hi,

Thanks to all of you dev for this fix 👍.

It was far from being just a french translation issue but requires an app code improvement which is now done => I'm eager to use the app with these label improvements 😉.
