### ISSUE TITLE
Pre-recorded voice bug

### ISSUE THREAD

**Issue by d4f5409d** [osmandapp/OsmAnd#12485]
### Description

The pre-recorded voice fails to say 1km or 1,(anything) km forward or turn in Hungarian language. Please look into this, and fix it because I only can use pre-recorded voices. (No TTS support)

### How to reproduce?

Install Hungarian pre-recorded voice
Navigate and you'll experiment it only says "múlva fordulj ..." and it should say either "1km múlva fordulj ..." or "1,(whatever number)km múlva fordulj ..."

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: Android 11, OxygenOS
Device model: IN2010

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
Online, and offline, both. Hungary map. Last edition date. (osmand+), everywhere occurs.

**Comment by vshcherb** [comment]
Same issue with russian recorded with message you are about to begin navigation.

**Comment by d4f5409d** [comment]
I debugged, there is already a problem with the pre-recorded audio files. 
Audio files to get fixed: 
- 5.1 After 1250m enter a roundabout (1km is missing from input)
- 9.9 Attention: Tunnel (Tunnel [Alagút] from "Figyelem, Alagút" missing)
- 9.1 You are exceeding the speed limit (Replace "Sebességhatár" with "Túllépted a sebességhatárt" or "Átlépted a sebességhatárt")
- 10.4 You are back on the route (Fix the text to "Visszatért az útvonalra"

**Comment by sonora** [comment]
@vshcherb: It seems to me the recorded voices users can download all still work with PROLOG config files? Downloading both hu and en resulted in having  `_config.p` configuration files in their folders on my device...

Assuming we fix this, and make the recorded voices properly dependent on our `.js` config files:

**9.9:**
Most recorded voices miss a recording for "_tunnel_". (Support for tunnel was added to OsmAnd only later.)  **Someone needs to supply missing recordings, or best provide a consistent new set of all recorded expressions as contained in the `xx_tts.js` config file, after we clean that up.** Or we use one of the TTS to ogg converters.

**10.4:**
- hu_tts uses "_Újra a tervezett útvonalon vagy_"
- hu-formal_tts uses "_Újra a tervezett útvonalon van_"

I can adjust both wordings to your liking in the config file, which would fix the TTS case.
Again also here: For the recorded voice then a new recorded file is needed with the desired wording.

**9.1:**
Telling me "this or this" is no good: Please let me know which wording exactly you would like, both for the regular and formal Hungarian TTS voice. Subsequently, someone needs to provide the corresponding recording files.

**5.1:**
This should be fixed once using the maintained `xx_tts.js` config file.

Side note: Both the hu and hu-formal Hungarian config files contain strings `1_5_kilometer_nom/acc` but these are not used at all. I suggest to remove and instead adjust the strings `1_kilometr_nom/acc` to say "_**about** 1 kilometer_", which is what the implemented logic in all languages requires. (And which is already correct for Hungarian for the case of miles via "`around_1_mile_nom/acc`".)

**Comment by vshcherb** [comment]
@sonora we probably didn't clean up _config.p, originally we didn't introduce new version so we wanted old devices to work as well with same downloads but now it's probably too late and we can clean up from _config.P download. Please correct me if I'm wrong we deleted all these files already from repos.

**Comment by sonora** [comment]
From what I see we'd be better off switching all voices to the js config files, that's the only way forward to fix missing features as those reported here.

I think the repo is clean, now it's a matter of syncing to the download server.

**Comment by sonora** [comment]
A lot of this should be fixed already if you simply replace the file `xx_tts.js` in the recorded voice folder on your device with the latest maintained version. If not, we can take it from there. See also #12685.
