### ISSUE TITLE
Ski slopes can't be disabled if the map style is different from "Winter and Ski".

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#12490]
### Discussed in https://github.com/osmandapp/OsmAnd/discussions/12454

<div type='discussions-op-text'>

<sup>Originally posted by **anastasiia936** August 11, 2021</sup>
### How to reproduce?
Enable and disable the Cycling route.

![image](https://user-images.githubusercontent.com/80623554/129032547-169bdf97-6804-40de-a14c-bd43885a84a4.png)
![image](https://user-images.githubusercontent.com/80623554/129032827-c13e8999-7fa0-4b60-9fef-de4d49cbcf4b.png)
![image](https://user-images.githubusercontent.com/80623554/129032848-495d1fcf-0878-4e77-a4f5-8247ba9a2775.png)

</div>

**Comment by xmd5a2** [comment]
Is "Show node network cycle routes" option enabled? It shows cycle routes too.

**Comment by dmpr0** [comment]
# Review 
- [ ]  "Ski slopes" can't be disabled if the map style is different from "Winter and Ski".
