### ISSUE TITLE
4.0.4 doesn't route with Poland roads only map

### ISSUE THREAD

**Issue by emesik** [osmandapp/OsmAnd#12494]
### Description

After upgrading to 4.0.4 osmand doesn't route with Poland roads only map. It asks to download multiple regional maps. They do work but the number of maps exceeds the free version limit.

### How to reproduce?

1. Install osmand 4.0.4
2. Download Poland roads only map
3. Select origin and destination points
4. A message appears that "additional offline maps are required to calculate the route" and Start button is disabled

### Your Environment
OsmAnd Version: 4.0.4
Android/iOS version: Android 9
Device model: Huawei VTR-L29

**Maps used (online or offline):**   

Poland roads only, 2021-08-01

![Screenshot_20210815_205313_net osmand](https://user-images.githubusercontent.com/407107/129489367-312e31a6-bbc2-4e35-bd80-2a2202111e4b.jpg)

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/12554
