### ISSUE TITLE
Don't render emergency=fire_hydrant by default [idea]

### ISSUE THREAD

**Issue by ghost** [osmandapp/Osmand#1249]
They are usually only authorized for use by emergency personnel and typically too small to be used as a landmark for navigation. To reduce map clutter, I propose they be moved to the details setting page, similar to street lighting.

**Comment by xmd5a2** [comment]
Do you have any idea how to name it? May be this option will grow in functionality and it is important to name it correctly because renaming disturbs users.
"Show fire hydrants"?

**Comment by johnwhelan** [comment]
In North America fire hydrants are quite large and can be used for
navigation.

Cheerio John

**Comment by azeae** [comment]
maybe a geographic toggle would be ok

**Comment by sonora** [comment]
Dormant issue, I think we should close for now.
