### ISSUE TITLE
OSMAnd does not request position data from system.

### ISSUE THREAD

**Issue by ErikSchneidereit** [osmandapp/OsmAnd#12498]
### Description
OSMAnd says it does not know my position but downloaded GPS data a moment ago. SatStat and Google Maps are happy about the location data they receive. Screenshots included.
In androids settings SatStat and Google Maps are listed among the apps that recently requested location Data. OsmAnd is not. It has the permission to do so. It appears that the location request OSMAnd tries to send never reaches the system?

### How to reproduce?
Turning on location services on the phone and starting OSMAnd (same effect in perturbed order).
Tap on the location icon to get a message like "Position not yet known. A-GPS data downloaded 2021-8-16 08:00" even when other Apps like SatStat indicate nice GPS accuracy at the same time.

![Screenshot_20210816-085448_Settings](https://user-images.githubusercontent.com/19346939/129523754-23144d06-0cb5-4c4f-b545-e91d2da2499e.png)
![Screenshot_20210816-085501_SatStat](https://user-images.githubusercontent.com/19346939/129523757-d2b663da-59de-4cb5-8059-b1e0b31f3a81.png)
![Screenshot_20210816-085513_OsmAnd](https://user-images.githubusercontent.com/19346939/129523760-fe29da49-0c54-45cb-b217-d7e67e0ce37f.png)

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: Lineage OS 18.1 from July 10th 2021
Device model: Google Pixel 3

**Maps used (online or offline): In Germany, Northrine-Westphalia and all other maps I ever checked.
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by scaidermern** [comment]
Do you have Google Play services running? If so, do they have permissions to request the location?

If not, you need to use the F-Droid version instead. It doesn't need Google Play services for location updates.

**Comment by vshcherb** [comment]
This problem was discussed already: Google Play requires an app to use Google Play Services, so there are 2 versions of OsmAnd you could use whatever you like
