### ISSUE TITLE
Object rendering for hiking

### ISSUE THREAD

**Issue by Hades1503** [osmandapp/OsmAnd#12503]
Hello,

Can you add to renderings of maps or make them bigger and visible:

the rungs: https://wiki.openstreetmap.org/wiki/Key:rungs

The ladder: 
https://wiki.openstreetmap.org/wiki/Key:ladder

Security or help cables:
https://wiki.openstreetmap.org/wiki/Key:safety_rope

Trailblazed:
https://wiki.openstreetmap.org/wiki/Key:trailblazed 
cairns, symbols (osmc: symbol), posts

Trailblazed:visibility:
https://wiki.openstreetmap.org/wiki/Key:trailblazed:visibility

This information is invaluable for trekking in the high mountains. If it is displayed, it will avoid problems or too busy passage during the hike

**Comment by rivermont** [comment]
Do these still render? I can't seem to see them on any map profile I have.
