### ISSUE TITLE
A SQLiteConnection object for database '+data+data+net_osmand_plus+databases+osmbugs' was leaked

### ISSUE THREAD

**Issue by gena01** [osmandapp/Osmand#1251]
05-18 08:27:01.411 W/SQLiteConnectionPool(32524): A SQLiteConnection object for database '+data+data+net_osmand_plus+databases+osmbugs' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
05-18 08:27:01.441 E/StrictMode(32524): A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
05-18 08:27:01.441 E/StrictMode(32524): java.lang.Throwable: Explicit termination method 'close' not called
05-18 08:27:01.441 E/StrictMode(32524): 	at dalvik.system.CloseGuard.open(CloseGuard.java:184)
05-18 08:27:01.441 E/StrictMode(32524): 	at android.database.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:210)
05-18 08:27:01.441 E/StrictMode(32524): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:233)
05-18 08:27:01.441 E/StrictMode(32524): 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:515)
05-18 08:27:01.441 E/StrictMode(32524): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:207)
05-18 08:27:01.441 E/StrictMode(32524): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:178)
05-18 08:27:01.441 E/StrictMode(32524): 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:891)
05-18 08:27:01.441 E/StrictMode(32524): 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:859)
05-18 08:27:01.441 E/StrictMode(32524): 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:696)
05-18 08:27:01.441 E/StrictMode(32524): 	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1234)
05-18 08:27:01.441 E/StrictMode(32524): 	at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:242)
05-18 08:27:01.441 E/StrictMode(32524): 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:224)
05-18 08:27:01.441 E/StrictMode(32524): 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
05-18 08:27:01.441 E/StrictMode(32524): 	at net.osmand.plus.osmedit.OsmBugsDbHelper.checkOsmbugsPoints(OsmBugsDbHelper.java:70)
05-18 08:27:01.441 E/StrictMode(32524): 	at net.osmand.plus.osmedit.OsmBugsDbHelper.getOsmbugsPoints(OsmBugsDbHelper.java:41)
05-18 08:27:01.441 E/StrictMode(32524): 	at net.osmand.plus.osmedit.DashOsmEditsFragment.getOsmPoints(DashOsmEditsFragment.java:148)
05-18 08:27:01.441 E/StrictMode(32524): 	at net.osmand.plus.osmedit.DashOsmEditsFragment.setupEditings(DashOsmEditsFragment.java:73)
05-18 08:27:01.441 E/StrictMode(32524): 	at net.osmand.plus.osmedit.DashOsmEditsFragment.onOpenDash(DashOsmEditsFragment.java:62)
05-18 08:27:01.441 E/StrictMode(32524): 	at net.osmand.plus.dashboard.DashBaseFragment.onResume(DashBaseFragment.java:51)
05-18 08:27:01.441 E/StrictMode(32524): 	at android.support.v4.app.Fragment.performResume(Fragment.java:1832)
05-18 08:27:01.441 E/StrictMode(32524): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:995)
05-18 08:27:01.441 E/StrictMode(32524): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
05-18 08:27:01.441 E/StrictMode(32524): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1120)
05-18 08:27:01.441 E/StrictMode(32524): 	at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:1939)
05-18 08:27:01.441 E/StrictMode(32524): 	at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:447)
05-18 08:27:01.441 E/StrictMode(32524): 	at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:436)
05-18 08:27:01.441 E/StrictMode(32524): 	at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:137)
05-18 08:27:01.441 E/StrictMode(32524): 	at android.app.Activity.performResume(Activity.java:5463)
05-18 08:27:01.441 E/StrictMode(32524): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2919)
05-18 08:27:01.441 E/StrictMode(32524): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2958)
05-18 08:27:01.441 E/StrictMode(32524): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2364)
05-18 08:27:01.441 E/StrictMode(32524): 	at android.app.ActivityThread.access$700(ActivityThread.java:165)
05-18 08:27:01.441 E/StrictMode(32524): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1326)
05-18 08:27:01.441 E/StrictMode(32524): 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-18 08:27:01.441 E/StrictMode(32524): 	at android.os.Looper.loop(Looper.java:137)
05-18 08:27:01.441 E/StrictMode(32524): 	at android.app.ActivityThread.main(ActivityThread.java:5455)
05-18 08:27:01.441 E/StrictMode(32524): 	at java.lang.reflect.Method.invokeNative(Native Method)
05-18 08:27:01.441 E/StrictMode(32524): 	at java.lang.reflect.Method.invoke(Method.java:525)
05-18 08:27:01.441 E/StrictMode(32524): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1187)
05-18 08:27:01.441 E/StrictMode(32524): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
05-18 08:27:01.441 E/StrictMode(32524): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
05-18 08:27:01.441 E/StrictMode(32524): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by vshcherb** [comment]
Fixed
