### ISSUE TITLE
Incomplete map package for germany

### ISSUE THREAD

**Issue by gituser789** [osmandapp/OsmAnd#12516]
### Description
When downloading all regions for germany, they are not complete.
Hamburg and Saarland are missing.
In the download-menu, it says that Berlin is also missing, but it is there (see screenshot), also in very detailed at zoom. May it is also part of another package?

### How to reproduce?
Fresh OsmAnd installation.
Navigate to ... Europe -> Germany. Download all regions (12)
After downloading all regions, it can be seen that Hamburg, Berlin and Saarland are missing. 
This can be verified in the map (see screenshot), but Berlin is there, also in very detail at high zoom level.

### Your Environment
OsmAnd Version: 3.9.10 (2021-03-17) F-Droid-Version

![image](https://user-images.githubusercontent.com/62549000/129683821-f91dac35-8946-458c-ace1-c0c3af672946.png)

**Comment by scaidermern** [comment]
There have been similar reports at #11642 and #11854.

**Comment by vshcherb** [comment]
Berlin is not missing it's downloaded with map Brandenburg + Berlin

**Comment by nazar-kutz** [comment]
It already shoud be fixed with: https://github.com/osmandapp/OsmAnd/pull/12465
![Screenshot_1629387216](https://user-images.githubusercontent.com/30292035/130097881-690d5df3-bb5c-41b4-bf57-27f89523ac99.png)

**Comment by TheSnoozer** [comment]
Hello,
I still can reproduce the issue with `4.1.11` when downloading the streemaps for germany and swiss. Can we reopen this, or should I create a new issue?
