### ISSUE TITLE
Osmand is routing through the air

### ISSUE THREAD

**Issue by Discostu36** [osmandapp/OsmAnd#12518]
### Description
Osmand wants my car to fly through the air. Route goes from one road to the other. They are not connected. 
![Screenshot_20210817_124606_net.osmand.jpg](https://user-images.githubusercontent.com/30999326/129713006-0770b2f8-495b-40ea-b6c0-9480c6b2ab7d.jpg)

### How to reproduce?
Route from 54.32584° N, 10.12419° E to 54.32517° N, 10.12376° E in car profile 

### Your Environment
OsmAnd Version: 4.0.4
Android/iOS version: 10
Device model: Huawei P30

**Maps used (online or offline):**   
Germany_schleswig-holstein_europe.obf 
Germany_schleswig-holstein_europe_21_08_17.obf (11:55 CEST)

**Comment by Dima-1** [comment]
There is not route from start point 54.32584° N, 10.12419° E because has restriction https://www.openstreetmap.org/node/2491373885. After 2021 Oct 1 route will be find as expected.
![photo](https://user-images.githubusercontent.com/31807095/133395738-59f82a3c-86a0-4ec0-8279-95dc11a2f859.jpg)

**Comment by Discostu36** [comment]
You are right that there is no correct route possible at the moment, I didn't think about that. But shouldn't Osmand then give a warning that there is no routing possible instead of giving me an impossible route?
