### ISSUE TITLE
Parsing Google URl link is not precise

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#12521]
### Description
When you copy URL and enter it in the search line OsmAnd displays location in the wrong place.

### How to reproduce?
Check location in the Google Play and OsmAnd 
https://www.google.com/maps/place/31%C2%B058'02.2%22N+34%C2%B047'04.0%22E/@31.9672766,34.7852048,18z/data=!3m1!4b1!4m14!1m7!3m6!1s0x1502b4129c326d41:0x1dfdcf9df0123065!2z15LXldec15PXlCDXnteQ15nXqCAxLCDXqNeQ16nXldefINec16bXmdeV158!3b1!8m2!3d31.967552!4d34.7852707!3m5!1s0x0:0x0!7e2!8m2!3d31.9672753!4d34.7844313

![image](https://user-images.githubusercontent.com/80623554/129738444-99fa5a23-efe0-47a5-addd-15ee331ea5d3.png)
![telegram-cloud-photo-size-2-5251433268912437203-y](https://user-images.githubusercontent.com/80623554/129738740-dca3096c-9869-4cce-9df5-1f93c577984c.jpg)

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/pull/12591

**Comment by Chumva** [comment]
There were some errors with tests in OsmAndMapCreator, this changes should be checked
