### ISSUE TITLE
geojson import error "Unexpected token"

### ISSUE THREAD

**Issue by opk12** [osmandapp/OsmAnd#12526]
### Description
OsmAnd errors out when importing this geojson export file.
```
Unexpected token (position:TEXT {
 "type": "Feat...@16:1 in java.io.InputStreamReader@e4170c4)
```

### How to reproduce?
Paste this in `export.geojson`, open the file with OsmAnd.
```
{
	"type": "FeatureCollection",
	"features": [
		{
			"type": "Feature",
			"geometry": {
				"type": "Point",
				"coordinates": [
					2.351053,
					48.848531
				]
			}
		}
	]
}
```

### Your Environment
OsmAnd 3.9.10 on Android 7

**Comment by vshcherb** [comment]
Geojson is not supported file now for OsmAnd
