### ISSUE TITLE
Create POI highway=street_lamp (nice to have)

### ISSUE THREAD

**Issue by mikeshenson** [osmandapp/Osmand#1252]
When creating a new POI, could you add "street_lamp" to the options list? I use OSMAND to navigate and add any missing POIs while I am out and about. I like to map street_lamps and I am always using the advanced options to add street_lamps. 

http://wiki.openstreetmap.org/wiki/Tag:highway%3Dstreet_lamp

OR please point me to the page that needs to change so I can add the code.

**Comment by vshcherb** [comment]
Unfortunately simple way of tag editing is not good in OsmAnd, we don't let people editing the POI which we don't index. There are 2 possibilities for now (before we make something better), Advanced POI Editing (quite difficult to use), OSM Notes Offline usage -> Export OSMC -> JOSM (and create/publish on PC).
