### ISSUE TITLE
OsmAnd doesn't get the entrance of schoolyard and drops me on the back side

### ISSUE THREAD

**Issue by DamageIncorporated** [osmandapp/OsmAnd#12532]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing

### Routing Profile
- car, fastest

### Start and end points

- Start: Beckum, Vorhelmer Straße
- Destination: Oelde, Hans-Böckler-Straße 14 ( https://www.openstreetmap.org/#map=17/51.84100/8.15749 )

Note: I did not specify "Erich-Kästner-Schule" as Destination but the actual address "Hand-Böckler-Straße 14".

### Actual and expected routes

Overall the route was okay, but right before the destination, OSMAnd messed up ;-)

The school area is rather large and there are several residential roads around. 
OSMAnd dropped me near "Ludgerusstraße 25" and said that I've reached my destination. That's not totally wrong as I am now on the back of the fenced schoolyard. The entrance gate is on the opposite site, on the correct address "Hans-Böckler-Straße 14".
Note that I did not specify "Erich-Kästner-Schule" as Destination but the actual address "Hand-Böckler-Straße 14".

To drive to the front of the school with a car in this particular case , you have to take a rather long detour (South on "Ludgerusstraße", South on "Zum Sundern" sharp turn north on "Fritz-Reuter-Straße" and finally north on Hans-Boeckler-Straße. 
To be routed correctly, I replaced the destination with "Hans-Böckler-Straße 13" a small building on the opposite side of the road

### Is this a regression?
I didn't test that

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

OsmAnd~ 3.9.10 (f-droid)
</code></pre>

**Device and Android/iOS version:**
Galaxy S5 (SM-G900F), Android 9
**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.

Standard Map (Vector) Europe -> Deutschland -> Nordrhein Westfalen 01.07.2021

**Anything else relevant?**
I _think_ OsmAnd tries to use the central point of the whole area as a destination and then looks for the closest road to get there, which is wrong in this case. Maybe it should rely on the actual road I set as destination or, if I had specified the school area/building as destination, use the `addr:street` tag on the building/area?

**Comment by DamageIncorporated** [comment]
I think this is related to #7520 which I didn't find before writing this report yesterday ...

**Comment by DamageIncorporated** [comment]
Hit the wrong button, sorry!

**Comment by sonora** [comment]
In deed related to #7520.  Using number 12 works fine, but as-the-crow-flies number 14 is closer to the back road than to the front, and OsmAnd's current algorithm stays on roadways to as close as it can get to (offroad) destination places.

The "address" in this case is in OsmAnd routing merely reflected by an "offroad" location point, i.e. we have no logic that when you specified a street address you expect to go via the very street name you specifed. This leads to occasional issues like this one or even #1633.

**Comment by vshcherb** [comment]
We're going to fix it with  - https://github.com/osmandapp/OsmAnd/issues/5395
