### ISSUE TITLE
Add favorites: Display Group with recently used icons

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#12539]
As a user I would like to see when adding new Favorite
- Last used color
- Recently used icon group: with 10-20 last used icons

**Comment by tradavyvy** [comment]
I think this has a connection with item #10850.

**Comment by tradavyvy** [comment]
Also a choice for the favourite groups in the most recently used order, not just alfabetical like now.
I am constantly scroling left to right to find my most used groups.
