### ISSUE TITLE
Feature request: add support for "building" object for "Choose Building" in address lookup.

### ISSUE THREAD

**Issue by gena01** [osmandapp/Osmand#1253]
When messing with the current osmand map for NYC. I am able to find the following address/tag:
http://www.openstreetmap.org/node/2679311665

Which is just a single node with address attached. However most of the buildings also have addresses, but I am unable to locate any of them through the app.

Here is one example: http://www.openstreetmap.org/way/248144124

Is it possible to add support to index and use those tags to be able to locate addresses? Otherwise I keep getting "no buildings" found.

**Comment by vshcherb** [comment]
OsmAnd supports it, it just doesn't find correlation between '6th ave' and '6th avenue' which is road on the street.
