### ISSUE TITLE
Linking the Matrix chat on the website

### ISSUE THREAD

**Issue by opk12** [osmandapp/OsmAnd#12534]
Telegram chats require me to install a closed-source version from Google Play, or an open source version from F-droid, which always lags behind for the security fixes. This is not Open or convenient.

Matrix is a decentralized chat network with many free software third-party clients. Matrix clients reach most of the OpenStreetMap community, because they can also access the chats on OFTC and Discord natively.

Would you link [the OsmAnd international Matrix chat](https://matrix.to/#/#osmand:hacklab.fi) on the homepage? (Edit: link to the new room, from vranki's comment below)

Or alternatively, bridge the chats to the respective Telegram chats, with a well-tested, widely used bot that copy-pastes messages (I can provide contacts of OSM staff that is knowledgeable in this Matrix bridging)?

Edit: fixed link (see below)

**Comment by vranki** [comment]
Agreed, it makes no sense to promote Telegram in a FOSS project. 

The correct link to the room is  https://matrix.to/#/!LcnGejdmNwqFQRRjAG:matrix.org?via=matrix.org&via=hacklab.fi&via=nordgedanken.dev - not the one in link above (it just links to outdated web client instance).

If there are active telegram channels, they can be bridged to Matrix easily. I can help with that if needed.

**Comment by opk12** [comment]
Thank you, corrected. The shortest correct form is https://matrix.to/#/!LcnGejdmNwqFQRRjAG:matrix.org

**Comment by vranki** [comment]
Nope, that link won't work except from servers that already know that room. It has only room ID which is not enough to join a room. Keep the other parameters.

**Comment by vranki** [comment]
Also the room has a slight problem - the only admin (with any management power) seems to be inactive. We might need to create another room with proper moderation unless we can reach the admin user.

**Comment by vranki** [comment]
We decided to start a new room with @opk12 - invite link is: https://matrix.to/#/#osmand:hacklab.fi

If the admin of old room wakes up one day, we can merge them together.

**Comment by vranki** [comment]
I am willing to give admin rights to someone who is actually a OsmAnd developer and can prove it. I'm just a random user.

If you want a Telegram room to be bridged, please follow the Telegram side instructions provided here and let me know the ID number: https://t2bot.io/telegram/

**Comment by opk12** [comment]
@vshcherb Is there any update on this? Organic Maps just got Telegram bridged to Matrix.

**Comment by mahdi1234** [comment]
Actually there's #OsmAndMaps:tchncs.de which is bridged with https://t.me/OsmAndMaps for some months/year now - https://archive.matrix.org/r/OsmAndMaps:tchncs.de would be nice to add to official rooms roster. @vshcherb  @EugeneZmeuk

**Comment by vranki** [comment]
All known OSM related rooms, including those mentioned are in OSM space https://matrix.to/#/#osm-space:matrix.org

I think that should be the main entry point to OSM chats and be linked on website.

**Comment by EugeneZmeuk** [comment]
> Actually there's #OsmAndMaps:tchncs.de / https://matrix.to/#/#OsmAndMaps:tchncs.de which is bridged with https://t.me/OsmAndMaps for some months/year now - https://archive.matrix.org/r/OsmAndMaps:tchncs.de would be nice to add to official rooms roster. @vshcherb @EugeneZmeuk

Done. (will be added for the general website after compilation)

**Comment by opk12** [comment]
@EugeneZmeuk Thank you. The link should also be added to the Help screen, next to the Telegram chats.
