### ISSUE TITLE
Option to use 12-hour clock (AM/PM) to display opening hours

### ISSUE THREAD

**Issue by parcelcat** [osmandapp/OsmAnd#12536]
# 🚀 feature request

### Option to use 12-hour clock (AM/PM) to display opening hours

The 12-hour clock format (e.g. `4:00 pm`) is used more commonly in some parts of the world than the 24-hour clock format (e.g. `16:00`). OsmAnd exclusively uses the 24-hour clock format to display opening times, which is how OpenStreetMap stores the data in the `opening_hours` key.

However, the fact that OsmAnd lacks the option to display these times in the 12-hour clock format makes the app less accessible to users in [regions where the 12-hour clock format is much more popular than the 24-hour clock format](https://en.wikipedia.org/wiki/Date_and_time_representation_by_country#Differences) (such as the United States).

### Describe the solution you'd like

OsmAnd should add an option to switch between the default 24-hour clock format and the 12-hour clock format for displaying opening hours. The ideal location for this setting is the "Units & formats" section of the "General settings" part of the profile settings.

### Describe alternatives you've considered

[Organic Maps](organicmaps/organicmaps) is able to show the 12-hour clock format, but does not have a setting to change the format.

**Comment by sonora** [comment]
I think that OsmAnd should simply follow the selected system locale /  setting (like we do elsewhere).

I can reproduce that for the case of opening hours we seem to ignore the system's display preference.

**Comment by dmpr0** [comment]
# ToDo
@sonora is right, OsmAnd ignores the system time format for opening hours, all other places where OsmAnd shows timestamps work as a system.
- [ ]  Use system time format for displaying opening hours.

<img src="https://user-images.githubusercontent.com/9365308/143881429-b48e0f90-5526-4db2-9f46-25a6e8200be8.png"  width="300" height="auto">
