### ISSUE TITLE
Routing information is not translated (Notification)

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#12542]
Some information is written in German and other English (left), it would be much better to have it fixed all to German

![image](https://user-images.githubusercontent.com/1042025/130103325-41fa4cc8-4c1b-44bb-aee4-3a2c77fa943b.png)

**Comment by nazar-kutz** [comment]
Can't reproduce
![image](https://user-images.githubusercontent.com/30292035/130402155-6a7c62e0-fd76-4459-95bb-f06f2beb428d.png)
![image](https://user-images.githubusercontent.com/30292035/130402423-d4e61dbc-1b57-46ed-bb8f-3879248dfaa4.png)

**Comment by vshcherb** [comment]
unfortunately not reproducible
