### ISSUE TITLE
Minor design errors.

### ISSUE THREAD

**Issue by franco999** [osmandapp/Osmand#1254]
He had already reported this in issue #1184, with an old version. Now I have the latest version and find this.

List with white background.
![1](https://cloud.githubusercontent.com/assets/12088580/7735049/f1301cf8-ff10-11e4-819c-639d74c54c5a.png)
--
Error in the text of distance. Remove the space does go down. E.g. "Distancia total 6,53 km, [...]"

Differences between the text in English and Spanish.
![2](https://cloud.githubusercontent.com/assets/12088580/7735176/ec731e58-ff11-11e4-9e4b-03980d062cd0.png) ![3](https://cloud.githubusercontent.com/assets/12088580/7735161/cbdcecfa-ff11-11e4-93ac-25e3cc42241a.png)

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/issues/1157

**Comment by vshcherb** [comment]
Duplicate

**Comment by franco999** [comment]
I do not want to continue duplicating issues, but here I found a similar problem.
![01](https://cloud.githubusercontent.com/assets/12088580/7781948/4c8ac3ea-00d4-11e5-8472-2f4f62c913a6.png)

**Comment by franco999** [comment]
Others bugs

 shared_string_remember_my_choice
![gpx](https://cloud.githubusercontent.com/assets/12088580/7786098/adea9220-018b-11e5-8f99-3807694b129d.png)

 osmand_parking_add_event
![parking](https://cloud.githubusercontent.com/assets/12088580/7786097/addb2326-018b-11e5-87e3-c4d3eab1e5aa.png)

**Comment by alexey-pelykh** [comment]
These are not duplicate issues, and basically are unrelated to this issue. While we'll take a look into that, please create new issues for these
