### ISSUE TITLE
Reset to original doesn't work after Changing Color Configure Map

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#12540]
'Reset to original' button doesn't work if you change color in Configure Map -> Tracks .
IMPORTANT: Changing color through Configure Map -> Tracks -> Color damages the track! (attached)

Note: it works correctly if you change the color through Track context menu appearance.

[Blue.gpx.zip](https://github.com/osmandapp/OsmAnd/files/7015779/Blue.gpx.zip)

[4_5834713050141166211.gpx.zip](https://github.com/osmandapp/OsmAnd/files/7015776/4_5834713050141166211.gpx.zip)

**Comment by dmpr0** [comment]
# Review
- [ ]  Width is not reset to original. After the track was imported is width was thin, change it to bold, taping "Reset to original" width is not reset.
