### ISSUE TITLE
[Feature Request] Split Detail > OSM Mapper assistant into 3 options

### ISSUE THREAD

**Issue by cmoffroad** [osmandapp/OsmAnd#12549]
# 🚀 feature request

### Description

Currently, enabling Detail > OSM Mapper Assistant highlights and shows the content of all objects with a note and fixme tag. While both options are extremely useful, they quickly make the map hard to read in areas where many objects have both tags. Tags have different levels of attention required (fixme being the highest) and it would be great to allow users to choose which one to show on the map.

Description tags, on the other hand, are surprisingly not made available, yet they would be very useful to prevent mappers to use the wrong tag e.g. name to show a short description on the map (happens often for mtb/enduro)

### Describe the solution you'd like

My proposal would be to replace OSM Mapper assistant option with 3 configuration toggle options:
- description assistant
- note assistant
- fixme assistant

And either replace existing options in Detail screen OR have they moved into their own OSM Mapper Assistant section one at the same level as Detail.

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/9d8c68261051e41105d3679a2d982877342ff827
