### ISSUE TITLE
Routing error on junction with a lot of turn restrictions

### ISSUE THREAD

**Issue by Dimitar5555** [osmandapp/OsmAnd#12559]
### Routing engine

OsmAnd's in-app offline routing

### Routing Profile

Car

### Start and end points
Start: 42.69531, 23.29537
End: 42.69307, 23.29486

https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=42.69531%2C23.29537%3B42.69307%2C23.29486

### Actual and expected routes
It should recommend going straight on as it can be seen on the above link.
![image](https://user-images.githubusercontent.com/19364673/130333871-98d68647-cb40-488b-a6cd-e2d4af24c696.png)

### Is this a regression?

 I don't know.

## 🌍 Your Environment

**OsmAnd Version:** 3.9.10

**Device and Android/iOS version:** EMUI (Android) 10

**Anything else relevant?**

The junction has a lot of turn restrictions but other routers are handling it fine.

**Comment by vshcherb** [comment]
@scaidermern indeed it's possible to overwrite and replace on the fly with 2 restrictions, if it works in all cases we're going to fix it altogether
Merged to #12537
