### ISSUE TITLE
Quick action: make map overlay/underlay toggle

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#12562]
Adding a map overlay as quick action just turns the overlay on. Pressing it again does nothing. 

Many other actions (show/hide POI, favorites, tracks etc) toggle the current state. I think it would be nice to have the same behavior for map overlays and underlays. Pressing the button should hide the overlay/underlay if it is already activated.

**Comment by vshcherb** [comment]
I think it's already possible, just click "Add Overlay" -> "No overlay" and it will work as toggle.

**Comment by scaidermern** [comment]
> I think it's already possible, just click "Add Overlay" -> "No overlay" and it will work as toggle.

Yes, but this requires _two_ actions. This is not really a toggle. Various other visual elements can be toggled via a single action.

**Comment by vshcherb** [comment]
If you have 2 maps selected "No overlay" + "Another overlay" - it works as a toggle.

**Comment by scaidermern** [comment]
Oh, right! That works. Thanks for the hint. Not very intuitive, though :)

**Comment by vshcherb** [comment]
Well, yes, but that could be more explanatory in UI later...
