### ISSUE TITLE
No icon for grit bin

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#12587]
Highlighting grit bins on the map is broken. Some grit bins appear as tiny orange circles without an icon, others don't appear at all. This varies when changing the zoom level.

![photo_2021-08-25_11-49-58](https://user-images.githubusercontent.com/1040784/130769363-fd705c18-4844-41d0-8e61-7a0e95f68423.jpg)

**Comment by scaidermern** [comment]
There are more POIs that are recoginized by OsmAnd but don't have an icon:

- office=association
- office=diplomatic
- healthcare=physiotherapist
- healthcare=speech_therapist
- healthcare=podiatrist
- healthcare=counselling
- craft=carpet_layer
- craft=computer
- craft=sculptor
- club=game
- leisure=fitness_station
- leisure=pitch + sport=table_soccer

And probably others.

**Comment by vshcherb** [comment]
Plese note @scaidermern that we support only > 10K object types and sometimes with exeception > 1K. 
So podiatrist is only 2K. 
craft =computer is only 250, so for sure there is no icon planned for it.

**Comment by scaidermern** [comment]
@vshcherb That's completely understandable. I didn't look at the tag usage count, just on POIs nearby which are missing an icon. 

18k: https://taginfo.openstreetmap.org/tags/office=association
14k: https://taginfo.openstreetmap.org/tags/office=diplomatic
11k: https://taginfo.openstreetmap.org/tags/healthcare=physiotherapist

The other tags I mentioned are well below 10k.

**Comment by vshcherb** [comment]
@scaidermern in that sense these 3 definitely should have an icon and others could be considered by specific user request and needs.

**Comment by xmd5a2** [comment]
`office=association` and `office=diplomatic` already have icons

**Comment by scaidermern** [comment]
> `office=association` and `office=diplomatic` already have icons

Nope. In the current nightly `office=association` has the same POI overlay problem as the grit bin did.

**Comment by scaidermern** [comment]
> > `office=association` and `office=diplomatic` already have icons
> 
> Nope. In the current nightly `office=association` has the same POI overlay problem as the grit bin did.

The same for `office=diplomatic`.
