### ISSUE TITLE
Display PT routes

### ISSUE THREAD

**Issue by gtrus21** [osmandapp/OsmAnd#12588]
Please add the ability to find and show the public transport route by searching.  For example, find the name "bus 15" and show its route.  Take the string for search either from name or from ref=* + route=*

Прошу добавить возможность найти и показать маршрут общественного транспорта поиском. Например найти по названию "автобус 15" и показать его маршрут. Строку для поиска брать либо из name, либо из ref=* + route=*

![Screenshot_20210825-142643](https://user-images.githubusercontent.com/69676792/130783297-a656dc35-b846-4f90-a961-f4deb1215f50.png)
![Screenshot_20210825-142552](https://user-images.githubusercontent.com/69676792/130783305-43d8a5a5-d0cb-452f-8cc4-674406fe28a6.png)

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/5924
