### ISSUE TITLE
The presence of a barrier is not taken into account when building navigation.

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#12586]
### How to reproduce:
Create navigation between points: 
51.41072° N, 6.84905° E
51.41072° N, 6.84905° E
https://www.openstreetmap.org/node/2624539300#map=19/51.40960/6.84717&layers=N
![image](https://user-images.githubusercontent.com/80623554/130768685-5d093a82-cfcd-4e8d-a47b-b06ae30ee509.png)
![image](https://user-images.githubusercontent.com/80623554/130768489-94dc04f8-7663-4f5c-9cc6-03b8a55f622b.png)

**Comment by scaidermern** [comment]
See the last screen shot. The barrier is not part of the footway https://www.openstreetmap.org/way/256822515. Instead it is only part of the forest multipolygon. It must be part of the footway to be recognized by routers. So this is an error in the map data.

**Comment by vshcherb** [comment]
Map was edited
