### ISSUE TITLE
Downloaded tts is not available offline

### ISSUE THREAD

**Issue by mpele** [osmandapp/OsmAnd#12589]
Downloaded tts is not available offline.

It is not possible to change tts language when you are offline.

**Comment by sonora** [comment]
This is not fixed. The dialog is available now, but when changing to a voice already present on your device, you will get an error.

Workaround for all affected: Using our old selector embedded in rhe Development plugin's Test voice prompt process works and lets you change the voice for the profile previously selected.

**Comment by sonora** [comment]
PS: Our old dialog in that place used to list all voices already present on the device, plus offer an "Install more..." option. The new dialog now just seems to list all voices available for download, and showing no distinction, I think that's a flaw which needs to be fixed also....

**Comment by dmpr0** [comment]
## Review
Don't show the "Downloading" notification if possible.
