### ISSUE TITLE
map layer, chart style selection doesn't update

### ISSUE THREAD

**Issue by noci2012** [osmandapp/Osmand#1258]
While changing the map style in dutch "Kaartstijl"  on menu "Kaart Instellen"
it isn't update when it is chosen for a different map style (OsmAnd, Touring, UniRS...), and a different map is style is selected then it doesn't show on the main menu. It does change the style as is seen after the map show again.

reentering the "Kaart Instellen" menu does show the updated selection.
So the menu is updated when goin down into the menu, but not on the way up.

**Comment by vshcherb** [comment]
Fixed
