### ISSUE TITLE
OpenStreetMap editing plugin fails to count and review contributions (email login)

### ISSUE THREAD

**Issue by mdykierek** [osmandapp/OsmAnd#12584]
### How to reproduce?
In the Plugin, go to Settings -> Map updates for Mappers -> Refresh
Everything reads 0 from top to bottom.
Tap Contributions.
File not Found error on openstreetmap.org shows up.

### Your Environment
OsmAnd Version: 4.0.5
Android/iOS version: 10
Device model: Mi 9T Pro

**Comment by scaidermern** [comment]
What is the URL for the File not Found error message?

Are you logged in in the OSM editing plugin?

**Comment by mdykierek** [comment]
Yes, I am logged in as mariusz_dykierek (at) o2 (dot) pl.
The URL is: https://www.openstreetmap.org/user/<here is unmasked e-mail address from above>/history
The error reads:
File not found
Couldn't find a file/directory/API operation by that name on the OpenStreetMap server (HTTP 404)
Feel free to contact the OpenStreetMap community if you have found a broken link / bug. Make a note of the exact URL of your request.

**Comment by scaidermern** [comment]
Looks like your OSM user name is missing in the URL.

**Comment by mdykierek** [comment]
The e-mail is my OSM user name and it is in the URL (don't want more spam than I already get that is why I put it in angle brackets.
