### ISSUE TITLE
Vector map rendering experience unusable

### ISSUE THREAD

**Issue by NohWayJose** [osmandapp/OsmAnd#12580]
### Description
Using vector map as source takes from several seconds to several minutes to render completely and then any change to zoom, pan or rotation usually causes a refresh and the whole wait starts again. It does seem to render the hill shading overlay and present position quickly but not the vector map. Occasionally, it will render some roads but then hang/take ages for the rest. The zoom level seems not to matter, as I anticipated it would only render the screen area and perhaps buffer/cache render nearby. Setting source to _OsmAnd (online tiles)_ renders much faster. Am I right in thinking the bitmap tiles used to be available offline?

If vectors are the way ahead, then they've got to be better than this! 
I can't believe it's my phone's CPU/memory but I guess it could be my config? (I don't want Google Play activated though)

### How to reproduce?
Set map source to _offline vector maps_.

### Environment
OsmAnd Version: 3.9.10
Android/iOS version: 11 (update 2021-06-01)
Build: Oxygen 11.0.2.1.HD01BA
Kernel: 4.14.190-perf+
(Google Play disabled. Source FDroid)
Device model: OnePlus 7 Pro (Snapdragon  855+ 8G RAM 256G ROM)

**Maps used (online or offline):**   
I have most UK regions downloaded. Live update used to be enabled (until 01-08-21) but I turned it off to see if that helped rendering - it didn't. Maps where this is experienced most are: (Europe UK)

- East Midlands 01-08-21
- South East 01-08-21

**Comment by scaidermern** [comment]
Since you are using Android 11 this could be caused by the data storage problem described in #12046.

**Comment by vshcherb** [comment]
Thanks for your feedback, there are many discussion threads about it where we will notify once it gets faster. There is no short-term solution possible with this issue.
