### ISSUE TITLE
Incorrect navigation to the Brindisi Airport

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#12583]
### Description
When you plan a route to the Brindisi Airport it creates navigation to the military airport that is actually in the private area. 

### How to reproduce?
Create navigation from any point to the Brindisi Airport. 
40.65657° N, 17.94631° E
https://www.openstreetmap.org/relation/12857931

![image](https://user-images.githubusercontent.com/80623554/130750068-bf1a17cf-45d9-42da-a4ea-0f1b04e43592.png)
![image](https://user-images.githubusercontent.com/80623554/130750179-5bf05a71-2c81-40e3-b232-65ee363a8c09.png)
![image](https://user-images.githubusercontent.com/80623554/130750197-beeaffc2-9afa-4e3d-988a-2f7d1e6c4c42.png)

**Comment by vshcherb** [comment]
It was fixed on the map already? https://nominatim.openstreetmap.org/ui/search.html?q=brindisi+airport&exclude_place_ids=321861787 
don't see anything wrong
