### ISSUE TITLE
The track module re-enables track viewing on map every time a track is recorded

### ISSUE THREAD

**Issue by Zero3** [osmandapp/OsmAnd#12597]
I use the "Record tracks automatically during navigation" feature of the track module. I do not have track viewing enabled on the map though, as I find the display of old tracks quite confusing while driving.

However, every time a new track has been recorded, the track module re-enables track viewing on the map. This is quite frustrating, as I then have to manually go through the settings menus to disable it again. Every single time.

Suggested solution: Do not change the setting automatically after every track recording. If the user disabled it, there was probably a good reason for it.

**Comment by Zero3** [comment]
After some more testing, I believe this happens because of the pre-selected "Show on map" checkbox when stopping the recording of a track. So I guess this might not be an issue after all, since the user can just disable that checkbox, but I found the default behaviour quite annoying nevertheless. Here are some suggestions for improving the usability:

* Do not enable the "Show on map" checkbox by default (at least not when tracks are disabled on the map)
* Make it easier to remove shown tracks on the map. It currently requires some searching in the settings menu to disable.
* Display tracks in a less invasive way on the map. They are currently shown as thick, bright red lines that cover pretty much everything else (including roads, street names, POI icons, ...).

**Comment by dmpr0** [comment]
It seems that the "Track saved" dialog that appears after taping "Finish" by default has "Show on map" options enabled, even if it was disabled on the previous steps. We need to fix this, all "Trip recording" related dialogs, should use/show the same values for the settings.

We can add condition if any track is visible, "show on map" is on, if all disabled, "show on map" is off, but it should work that way until the user first time changes it.

Regarding track appearance, you can set default track appearance in Menu – Configure Map – Tracks, it will be applied to the imported, recorded, or created tracks.
