### ISSUE TITLE
could not draw chosen area

### ISSUE THREAD

**Issue by MakiWolf** [osmandapp/OsmAnd#12599]
### Description
could not draw chosen area appears and map does not load in some zoom levels

### How to reproduce?
Open osmand map in Topo style and zoom in and out. Sometimes I got the error "could not draw chosen area".
![issue](https://user-images.githubusercontent.com/73300633/130859879-41ae1d9c-4f47-49cf-a67a-19b24e2367b3.gif)

### Your Environment
OsmAnd Version: latest build from source code (25.8.21) androidFullLegacyFatDebug as build variant
Android/iOS version: 11
Device model: Pixel 4 API 30 from Android Studio Emulator

**Comment by vshcherb** [comment]
https://www.openstreetmap.org/relation/49970#map=15/47.5271/14.9780

**Comment by MakiWolf** [comment]
I have set up a completly new device from Android studio emulator and the issues happens when switching to skiing profile.
![issue](https://user-images.githubusercontent.com/73300633/132245621-34020a7f-a420-47a5-a82b-678d60c0d630.gif)

**Comment by vshcherb** [comment]
We don't plan to fix it cause it's deprecated java rendering, you need to compile OsmAnd with NDK, so you get ful lOsmAnd. You can also put extract native libraries and put them inside your libs folder apk
