### ISSUE TITLE
Bug: POI Editor transforms amenity=parking to transportation=parking!

### ISSUE THREAD

**Issue by it4workflow** [osmandapp/Osmand#1260]
OsmAnd 2.0.4: As you can the see in following screenshots, i want to update an amenity=parking. But the poi editor transform it into transportation=parking, although you can see amenity=parking in extended tags!
I do not know if it's relevant, but poi layer selection "parking" and "personal transport" shows the same things?
And as you can see in the information popup, the node has got an homepage and telephone, but the editor doesn't show it, bug or feature?
![screenshot_2015-05-22-10-42-37](https://cloud.githubusercontent.com/assets/8296940/7770643/1489e19e-0091-11e5-8dce-480e754ece94.png)
![screenshot_2015-05-22-10-43-07](https://cloud.githubusercontent.com/assets/8296940/7770645/1b0fb110-0091-11e5-8e8d-e0b8d5550799.png)
![screenshot_2015-05-22-10-43-30](https://cloud.githubusercontent.com/assets/8296940/7770646/1cf58ff4-0091-11e5-93b3-678eb35e990b.png)

**Comment by it4workflow** [comment]
OsmAnd 2.0.4

**Comment by vshcherb** [comment]
It was fixed in nightly already, soon will be in release
