### ISSUE TITLE
Village Zoutelande not found

### ISSUE THREAD

**Issue by sebastianschauenburg** [osmandapp/OsmAnd#12616]
### Description

OsmAnd is amazing and I want to help out. I found that sometimes OsmAnd can not seem to find the city (town actually) where I want to navigate to. This also means I can not find a street in that city, which makes navigating sub-optimal, since I can only use GPS coordinates now (or select the destination by scrolling the map in the application). I've downloaded all standard maps of the Netherlands entirely.

Seem to remember something about an issue (years ago) in which cities could not be found if they didn't have city center. So I double checked and they seem to have a city center defined in OpenStreetMap.

### How to reproduce?

- Open OsmAnd
- Try to set the destination to town of "[Zoutelande](https://www.openstreetmap.org/relation/1733973)" (specific example)
- Only find the "Zoutelandestraat" (street) in "Tilburg" (town / city), but expected to find the city/town "[Zoutelande](https://www.openstreetmap.org/relation/1733973)" in Zeeland.

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: 8.0.0
Device model: Samsung Galaxy S 7

**Maps used (online or offline):**   
Offline maps of the Netherlands dated August 1st 2021

**Comment by vshcherb** [comment]
Boundary (https://www.openstreetmap.org/relation/1733973) should have been connected to place village (https://www.openstreetmap.org/node/3130166299)

**Comment by alisa911** [comment]
Has been fixed in OSM
<img width="689" alt="Screenshot 2021-09-23 at 13 21 32" src="https://user-images.githubusercontent.com/38911173/134491788-bc1ff0a7-40f8-4562-8679-92e49febb099.png">

**Comment by sebastianschauenburg** [comment]
> Boundary (https://www.openstreetmap.org/relation/1733973) should have been connected to place village (https://www.openstreetmap.org/node/3130166299)

Thank you so much for that information, I didn't know that. I fixed it upstream (in OSM). Consider it closed :)
