### ISSUE TITLE
Don't show destinations the whole OSM-track

### ISSUE THREAD

**Issue by Neuwessi11** [osmandapp/OsmAnd#12619]
At the moment OsmAnd shows the tagged destinations somewhat prior to a turn, and after the turn for the whole length of the OSM-track. This is annoying on the one hand and can lead to misunderstandings on the other hand.

Better would be: OsmAnd shows the destinations prior to the turn just like now, and (let's say) 100 m after the turn it stops showing.

Quite often it doesn't matter, because the OSM-tracks are not so long. But there are tracks with a length of several km, and there are regions with a lot of such tracks. And if you are driving some km, shown the last destinations, it can really happen that you will miss the changing of the destination some hundred meters prior to the next turn.

**Comment by vshcherb** [comment]
I think it was recently fixed with 4.0. Please provide track & screenshot if it's still not ok, we will take a look what could be done better.

**Comment by Neuwessi11** [comment]
You can navigate from 60.46075, 14.84387 to 60.42172, 14.85199.

When I simulated it just now, after the first turn OsmAnd was not quite sure what to show. The display changed between "Salån" and "Höglinda". I think this is because of the changing speed (it varied between 40 and 350 km/h).

**Comment by Neuwessi11** [comment]
The same with today's update to 4.0.7.

**Comment by Neuwessi11** [comment]
Is this issue already implemented in OsmAnd version 4.2.7?
I ask because in my 4.2.7 the problem still exists.

**Comment by vshcherb** [comment]
Please keep in mind that now there are 3 diff modes for simulation

**Comment by Neuwessi11** [comment]
> Please keep in mind that now there are 3 diff modes for simulation

What does this mean?

**Comment by vshcherb** [comment]
Fast preview, Real simulation, Fixed speed - Simulation

**Comment by Neuwessi11** [comment]
Ah, ok, but this doesn't matter, because it happens in real navigation, too.
I will open a new issue.
