### ISSUE TITLE
Exit lanes are shown as through lanes

### ISSUE THREAD

**Issue by Neuwessi11** [osmandapp/OsmAnd#12618]
### Description
Mostly on highway=trunk, but sometimes on highway=motorway, when continuing driving straight, OsmAnd shows in the lane assist the exit lane as a lane going through, that means it tells me there are three lanes (instead of two) and I should leave the right lane.

### How to reproduce?
Route e.g. from 59.33744, 15.23626 to 59.32214, 15.230356 
But this is only an example. It happens all the time.

### Your Environment
OsmAnd Version: 4.0.5 (OsmAnd Plus +Live)
Android/iOS version: Android 9
Device model: Cat S61

**Maps used (online or offline):** I have no idea. How can I find out?

![Screenshot_20210828-130905-1](https://user-images.githubusercontent.com/70072237/131216457-7790bbf0-688e-4283-8dfc-3b3bea92e573.png)

**Comment by vshcherb** [comment]
This could be corrected only with [turn:lanes](https://wiki.openstreetmap.org/wiki/Lanes) tagging. Without extra information on most of the roads this approach is more informative.

**Comment by Neuwessi11** [comment]
Sorry to contradict you, but I think you mix up turn:lanes with trunk_link.
If there is a street classified as highway=trunk_link I would say you don't need to tag turn:lanes because highway=trunk_link implies a turn:lanes=slight_right or turn:lanes=right.

Please make a difference between that, because there is a difference in reality!

Please reopen!
Thank you!

**Comment by vshcherb** [comment]
There is no difference only turn:lanes tag depicts the reality how lanes merges & splits. If you have only lanes tag than trunk / trunk_link/ motorway / motorway_link don't depict realy junction configuration

**Comment by Neuwessi11** [comment]
Then I have to ask you if there are really situations in which a street marked as trunk_link or motorway_link (maybe even primary_link or others) are NOT a junction or exit lane.
At least on ALL motorways a *_link is always to be combined either with turn:lanes=slight_right or turn:lanes=right by a routing algorithm.  It doesn't matter if tagged or not, because there is no other possibility.
And I presume, it is the same at least with highway=trunk, possibly the others, too.

Don't forget that on OSM is mostly only tagged what is to be seen, so if there is no marked arrow on the road, there is no turn:lanes-tagging.
That's why I would suggest to build a logic into OsmAnd, that at least motorway_link and trunk_link is implicating turn:lanes=slight_right or turn:lanes=right.

The actual situation is unsatisfying and confusing. And yes - a little dangerous, too.

**Comment by vshcherb** [comment]
I would disagree. In most situations trunk / motorway is mapped with exactly number of lanes it has i.e. lanes=2 means on the long segment there are 2 lanes and in most of the countries (but not always) there are special lanes create before junction.
```  Straight | Straight ``` -> ``` Straight | Straight  | Turn Right ``` (just before the turn), so in that case indication is exactly correct that for a short period of time there is an extra lane to make a right turn. Cause there is no ```turn:lanes``` we don't show it as turn right and show it as ```Straight``` icon which anyway gives correct information about extra lane.

**Comment by Neuwessi11** [comment]
> 
> 
> Cause there is no `turn:lanes` we don't show it as turn right and show it as `Straight` icon which anyway gives correct information about extra lane.

No, for my Swedish example this is not true, because the trunk_link is no extra lane. 
You are right, e.g. on German motorways prior to every exit there is an extra lane, tagged as `turn right`. But the trunk_link in my example has no extra lane prior to the exit. The trunk_link simply leaves the trunk, so the information OsmAnd gives is simply false information, because OsmAnd's information shows me three lanes going through, what is incorrect.
Your logic seems to handle the trunk_link as part of the main road, but this is a false logic.

**Comment by Neuwessi11** [comment]
I think it is really sad that you do not reply to the advise that your app gives false information.

And I think it is very sad that you are satisfied with your app giving false information that really irritate drivers!

Please re-open this issue!

**Comment by Neuwessi11** [comment]
By the way, it is not only a problem with highway=trunk_link.
In the following example it happens with highway=residential as well:
Navigate from 51.16240, 6.43402 to 51.16117, 6.42619 and you will see:

![Screenshot_20210913-183353-1](https://user-images.githubusercontent.com/70072237/134074557-7428ccb0-8de5-4c09-bdf6-c94283353b5d.png)

Weird enough, navigating just the opposite direction it works fine.
