### ISSUE TITLE
Flooding near Norden

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#12637]
The problem exists in the area between Norden and Upgant-Schott when scaling up or down to 2 km. Moving the map at a scale of 2 km from the area without error causes no problem. Just a change of scale.
53.59420° N, 7.20674° E
![Screenshot_20210827-092024_OsmAnd+](https://user-images.githubusercontent.com/80623554/131368024-4bcd7a81-0ab2-4a64-b883-779db4b217b6.jpg)

OsmAnd 4.0.5
Map update form 01.08.21

**Comment by xmd5a2** [comment]
Can't reproduce
