### ISSUE TITLE
Mapillary plugin not working, because of API change, old servers are not available anymore

### ISSUE THREAD

**Issue by Zahnstocher** [osmandapp/OsmAnd#12631]
Old API was shut down, the servers are not available anymore:
https://d25uarhxywzl1j.cloudfront.net
https://d6a1v2w10ny40.cloudfront.net
https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd-java/src/main/java/net/osmand/map/TileSourceManager.java

Mapillary switched to new v4 API:
https://blog.mapillary.com/update/2021/06/23/getting-started-with-the-new-mapillary-api-v4.html
https://www.mapillary.com/developer/api-documentation

**Comment by vshcherb** [comment]
We need to start rendering 14th zoom.

**Comment by Zahnstocher** [comment]
> We need to start rendering 14th zoom.

MAPILLARY_VECTOR_SOURCE -> minZoom = 14 causes the green Mapillary lines to blink, 16 is working on my device, but if I set the magnifier <= 50% the lines also start to blink.
https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd-java/src/main/java/net/osmand/map/TileSourceManager.java

**Comment by vshcherb** [comment]
We need to use different tile source and take upscale the data from 13th zoom up to 14-16
