### ISSUE TITLE
Different ETAs

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#1264]
Please have a look at the attached screen shot. This scree shot has bee taken directly after the route has been calculated.

It displays two different ETAs:
- On the top-right: "0:20" (20 minutes)
- On the bottom pop-up: "26:51" (27 minutes)

Found with OsmAnd 2.0.4.

**Comment by Norbert80** [comment]
![screenshot_2015-05-11-11-01-26](https://cloud.githubusercontent.com/assets/6921696/7785424/a87732fe-018f-11e5-980a-7fa4618ce500.png)

**Comment by stephan75** [comment]
Maybe 20 Minuten is time to first waypoint, and not to the last final destination?
Try to do that routing without waypoint or Zwischenziel ... Success?

**Comment by Norbert80** [comment]
No waypoint (Zwischenziel) was set. I also tried it again with nearly the similar starting point.  No success.

**Comment by Norbert80** [comment]
Similar bug report from OsmAnd Group:

**Comment by vshcherb** [comment]
That's not really bug that just quite unused feature and misleading information. Toast shows the time calculated by routing engine, widget proper eta

**Comment by Norbert80** [comment]
@vshcherb from a users point of view it is really misleading so I think it should be considered as a bug. Any chance to set a target milestone? IMHO the "Toast" is not needed and should be removed. Alternatively it could display the identical value as the widget.

**Comment by vshcherb** [comment]
It was fixed
