### ISSUE TITLE
Wrong POI icons for one zoom level

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#1265]
Please have a look at the attached screen shots. You can see that for one zoom level, wrong POI icons are displayed.

Position is:
http://www.openstreetmap.org/search?query=27.7837%2C%20-15.5068#map=16/27.7837/-15.5068

Found in OsmAnd 2.0.4 and OsmAndF~ 2.1.0#7374D.
![screenshot_2015-05-12-09-20-32](https://cloud.githubusercontent.com/assets/6921696/7785462/3e1178aa-0191-11e5-8815-1f13d6ec581e.png)
![screenshot_2015-05-12-09-20-44](https://cloud.githubusercontent.com/assets/6921696/7785463/41cb2a36-0191-11e5-8af1-1043b4b9edc1.png)

**Comment by xmd5a2** [comment]
it's by design. These objects have tags: leisure=sports_centre and sport=* . At first screenshot (lower zoom) only leisure=sports_centre icon is displayed. At second - only sport=* icon.
