### ISSUE TITLE
Sames names of layers in Quick action button in Osmand 4.0.7

### ISSUE THREAD

**Issue by capta** [osmandapp/OsmAnd#12668]
### Description
I have preconfigured multiple layers in Quick action button to fast change layers. After update to Osmand 4.0.7 (it worked great in 4.0.5 layers keep their own name) all layers have the same name (but the changing of layer is ok). 

![Screenshot_20210903-163425](https://user-images.githubusercontent.com/10539115/132022892-e740b95c-c81b-4eaa-90b3-c61f5b8939bc.png)

### How to reproduce?
Update to Osmand 4.0.7 and add many different layers in Quick action button they have all the same name. If you select a layer it applies correctly and all names are replaced by selected layer (true real name) in Quick action button

### Your Environment
OsmAnd Version:4.0.7
Android/iOS version:9
Device model:Blackview BV9600

**Comment by Jasskurn** [comment]
I'm experiencing the same issue. But it appears to be only affection "buttons" for Map Source

OsmAnd Version:4.0.7
Android/iOS version:10
Device model: Huawei P30 Pro


![OsmAnd screenshot - same options](https://user-images.githubusercontent.com/69077639/132108794-4011cfef-14d0-43c5-961d-b09e314480b1.jpg)
