### ISSUE TITLE
Change email for OsmAnd Cloud

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#12666]
Please add the option to cancel registration for one OsmAnd Cloud account and register another.

**Comment by yuriiurshuliak** [comment]
+1

**Comment by alisa911** [comment]
web - https://github.com/osmandapp/web/pull/90
backend - https://github.com/osmandapp/OsmAnd-tools/pull/624

**Comment by alisa911** [comment]
https://github.com/osmandapp/web/pull/93
https://github.com/osmandapp/OsmAnd-tools/pull/627

**Comment by alisa911** [comment]
web https://github.com/osmandapp/web/pull/94
backend https://github.com/osmandapp/OsmAnd-tools/pull/629

**Comment by dmpr0** [comment]
# Review
Change email
Please enter verification code which was sent to your old email
- [ ]  Please enter verification code which was sent to your **current** email

**Comment by vshcherb** [comment]
**Review**
- /loginForm

**Comment by Zirochkabila** [comment]
- [ ] After changing the account - it is still possible to make changes to the cloud on the device and use the cloud using the old account - can we create a check that will verify the account and if the old account is used, a notification will be displayed that "Account address has been changed. Please enter new data" or something similar

- [ ] Message with the confirmation code, when changing account, shown "Delete". Can we change to "Change" - yellow arrow (first message)

- [ ] Message with the confirmation code when confirming a new account also shows "Delete". Can we change to "Confirm" or "Login" - green arrow (second message)


<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/f9697f30-ecf5-4ca2-8559-a115f597b66b"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/1bf77cf8-f34d-4993-b71e-9fe5d0ccbb1d"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
1.  After changing the account - it's ok. Change email doesn't change account
4. Enter button doesn't need to be supported by default
To Do
1. Add Cancel button (close icon is not enough and not accessible item)
2. Messages need to be fixed

**Comment by Zirochkabila** [comment]
Awaiting review

![photo_2023-06-22 13 13 27](https://github.com/osmandapp/OsmAnd/assets/104760013/d18e1258-60a9-4aaf-bb67-da675cbbfc4d)

**Comment by EugeneZmeuk** [comment]
https://github.com/osmandapp/OsmAnd-Issues/issues/1990#issuecomment-1623709208
