### ISSUE TITLE
The route calculation for distance ~100 km takes ages (cycling and walking profile)

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#12669]
### Description
For the cycling profile calculates a distance less than 100 km around 7 minutes and creates a route. For the walking profile the same route could not be calculated for more than 10 minutes (the progress line does not even move).
![image](https://user-images.githubusercontent.com/80623554/132020572-fa1c61fa-282c-4827-918d-33e021ac1510.png)
![image](https://user-images.githubusercontent.com/80623554/132024865-d22ed4f7-410a-4bce-9b29-60e3df8728ef.png)

### How to reproduce?
Calculation of a route for driving profile takes less than a minute.
Calculation of a route for cycling profile will take around 7 minutes.
Calculating a route for the walking profile takes forever (more than 10 minutes)
The distance between Alkmaar city and Rotterdam city
52.63126° N, 4.75037° E
51.92290° N, 4.46317° E

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date. Offline map, last update from 01.08.21

**Comment by vshcherb** [comment]
7 minutes  - not ages and yes it's quite long but the cycling graph is too big in NL
