### ISSUE TITLE
Avoid Roads broken in OsmAnd 2.0.4 and OsmAndF~ 2.1.0#7403D

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#1267]
- Make sure you are in an active care routing (Go button has to be hit)
- Scroll the map and try to define a road section to be avoided (which is not in the near of the actual position)

Note that OsmAnd always jumps back to the current position so that it is impossible to select a road section which is not in the actual screen. (This behavior is independent of the setting to auto move the map to actual position.)

**Comment by sonora** [comment]
I believe what kicks in here is our Auto-zoom feature. And unlike our Auto-center feature, Auto-zoom kicks in immediately and does not obey the configurable wait time interval for Auto-center.

So I can imagine (without having tested it) that a workaround would be to pan the map a little before trying to make the "Avoid" selection on the map, in this fashion the wait-time for Auto-center should become active and be honored (and that can be configured in the Navigation settings).

For a final solution to in our code, we could make Auto-zoom (during an ongoing navigation only) also obey the Auto-center wait time, as I had already suggested elsewhere for the similar issue where you manually zoom out (via the zoom button) to check out the surroundings during ay navigation. In this case also, auto-zoom kicks in immediately and voids your manual intervention, unless you panned the map a little beforehand.

**Comment by Norbert80** [comment]
@vshcherb could you please assign this confirmed issue?

**Comment by vshcherb** [comment]
It is not broken, after the screen switched to my location, you can still drag and select point. This is a small glitch, that you can scroll before the dialog will be closed. Once it closed it will position to my location.
