### ISSUE TITLE
map is missing roads

### ISSUE THREAD

**Issue by emdete** [osmandapp/OsmAnd#12674]
(i am not sure if this is the right place to put this issue, just tell me if i'm wrong and where to put it)

this is the area in question on osm.org:

![scheid](https://user-images.githubusercontent.com/3251523/131484745-2c415328-0cce-485c-b268-c2488858dafd.jpg)

and this is the display of the same area in OsmAnd:

![Screenshot_20210830-072745_OsmAnd_](https://user-images.githubusercontent.com/3251523/131485103-c67a167f-165d-4df1-bdf0-b1e2b89e5a09.png)

it seems the roads where not included in the map file. the location is

[50.3585/6.4240](https://www.openstreetmap.org/#map=15/50.3585/6.4240)

i downloaded a new file 2021-08-30.

**Comment by pebogufi** [comment]
This point is VERY close to the boundary between Rheinland-Pfalz and Nordrheinwestfalen, less than 2 km within Rheinland-Pfalz. There is a "corner" with a complicated structure.

![Screenshot_20211009-114039_OsmAnd~~01](https://user-images.githubusercontent.com/18628183/136653071-4c211848-c195-46cd-9c8b-5833dd3fa97e.jpg)

**Comment by vshcherb** [comment]
@ivanPyrohivskyi screenshots?

**Comment by ivanPyrohivskyi** [comment]
Downloaded map Rhineland-Palatinate (Germany_rheinland-pfalz_europe_2.obf):
<img src="https://user-images.githubusercontent.com/1040293/137100800-0edea0a9-f149-44a2-98fe-8c7367da7e57.png" width ="400"/> <img src="https://user-images.githubusercontent.com/1040293/137100786-66a24255-5d52-4021-b5af-f6306416c968.png" width ="400"/>

Downloaded maps Belgium Wallonia (Belgium_wallonia_europe_2.obf) && North Rhine-Westphalia Cologne Goverment Region (Germany_nordrhein_westfalen_cologne-government-region_europe_2.obf):
<img src="https://user-images.githubusercontent.com/1040293/137101433-733c56b9-4d43-4f62-8626-2bdf1166c471.png" width="400"/>

Please download actual map for this location. Other maps are too close by border and provide such misunderstood.
