### ISSUE TITLE
Search: full match POI is below city results

### ISSUE THREAD

**Issue by tommycrock** [osmandapp/OsmAnd#12688]
### Description

Located next to The Terrace cafe in Saltaire https://www.openstreetmap.org/node/497392253 I searched for "the terrace" and it was not listed though other results are. 
![Screenshot_20210905-111510_OsmAnd+](https://user-images.githubusercontent.com/5749884/132123391-37706462-c093-4916-98ea-93d69dddacd8.jpg)
![Screenshot_20210905-111521_OsmAnd+](https://user-images.githubusercontent.com/5749884/132123395-176a4721-0f0a-4279-9b54-1dd74073392b.jpg)

I had tried searching for it earlier to navigate to it from a few hundred metres away.

### How to reproduce?

As above

### Your Environment
OsmAnd Version: 4.0.7
Android/iOS version: 11
Device model: Samsung s10e

**Maps used (online or offline):**   
Offline Yorkshire and Humber August 2021 with live updates - but node was last edited 3 years ago

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/pull/13898
https://github.com/osmandapp/OsmAnd-resources/pull/789/files

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-resources/pull/813/files
https://github.com/osmandapp/OsmAnd/pull/13898/files
