### ISSUE TITLE
Technical Debt: delete tuProlog lib, avoid reading any _config.p, _ttsconfig.p

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#12685]
@vshcherb As a spillover from #12485, and to detail the associated milestone task, it looks like we should do the following:
1. I have downloaded a number of our recorded voices and it seems that when ending up in the device's respective "voice" subfolder they contain both a `_config.p` and an `xx_tts.js` config file.
**-> While in my tests the `xx_tts.js` file seemed to take precedence, I guess we should delete the _config.p (respectively suppress its creation?)**

2. I have noticed that the contained **xx_tts.js** files contained in the recorded voices are not the latest version as maintained under https://github.com/osmandapp/OsmAnd-resources/tree/master/voice.
**-> What needs to regenerate the recorded packages with the latest `xx_tts.js`, or can we even sync them automatically?**

**Comment by vshcherb** [comment]
I double checked and it's a bit more messy than I've thought. Though it looks like priority is given to xx_tts.js but it's not enough in some code.

The ultimate solution is pretty simple - prolog files are a Technical debt, so we need to delete or rename MediaCommandPlayerImpl, AbstractPrologCommandPlayer. And we need to delete tuprolog from dependency.

Unfortunately now all is interconnected and it's not an easy switch to delete tuprolog like interface method
```public List<String> execute(List<Struct> listStruct);```

Though it might be a big task but hopefully will be resolved with 4.1

**Comment by vshcherb** [comment]
@sonora after voice package downloads, file xx_tts.js within downloaded package should be replaced with newer file from APK. We could double check it with an easy experiment. Also file should be updated every time with new build / release

**Comment by sonora** [comment]
From what I see we update xx_tts.js from new builds only in the tts folders, not in the recorded voice folders. See https://github.com/osmandapp/OsmAnd/blob/4ea75487ed6b2580bbd7b2a2d18b273bbbd5131a/OsmAnd/assets/bundled_assets.xml.

The other question is if we cannot not always update the download packages with the latest xx_tts.js from the repository, so we save the step of having to update on the device immediately after downloading?

**Comment by vshcherb** [comment]
we can update of course but it would require another continuous and automated process (for sure not manual). That's also possible though problem is that would be limitation of version. If we couple tts with application we can be sure that TTS always  synced with Application API which could helpful to develop  new methods not breaking backward compatibility.

Anyway it's a minor issue and yes we could create a job and repackage all voice tts - it's just another effort. And it doesn't avoid this task :-)

**Comment by sonora** [comment]
You're right. Maybe we should even package the recorded voices entirely without config files, in this fashion entirely rely on the app to provide that.

(But similarly: How will the ogg files in the download package get updated if someone updates in the repo?)

**Comment by vshcherb** [comment]
It was always done manually with scripts package...

**Comment by sonora** [comment]
Regarding cleanup: All classes containing 'CommandPlayer' in their name are a candidate for review. I guess we will keep the **bolded** ones, removing the _italic_:

- **CommandBuilder.java**
- **CommandPlayerException.java**
- _AbstractPrologCommandPlayer.java_ -> rename to maybe **CommandPlayerImpl.java**
- **JSMediaCommandPlayerImpl.java**
  - _MediaCommandPlayerImpl.java_ -> port into mostly into JSMediaCommandPlayerImpl.java
- **JSTTSCommandPlayerImpl.java**
  - _TTSCommandPlayerImpl.java_ -> merge into JSTTSCommandPlayerImpl.java
- **JSCommandBuilder.java**
