### ISSUE TITLE
Measuring and notes tools share the same text

### ISSUE THREAD

**Issue by stefanb** [osmandapp/Osmand#1268]
...which makes it hard to translate nicely, at least in Slovenian.

Also english would be better of with:
* "Measure" for distance calculator and 
* "Note" (or "AV note" or "Take note") for taking audio/video notes

"Start" can mean anything, and is only cluttering the screen (all action buttons normally _start_ something)

Instances:
https://github.com/osmandapp/Osmand/search?l=java&q=shared_string_control_start&utf8=%E2%9C%93

**Comment by vshcherb** [comment]
The main accent here is on the icon, we think to redesign to quick access button without start text. For now we don't plan to create a new string cause it will take time to translate to other languages and might not be used
