### ISSUE TITLE
Current version not available in F-Droid

### ISSUE THREAD

**Issue by Krawei** [osmandapp/OsmAnd#12693]
Dear team,

when I take a look on google play store the current version is 4.0.7, in the F-Droid store the current version is 3.9.10.

What's the reason for this gap? Is there a bug in the build process?

Please fix this.

**Comment by vshcherb** [comment]
Not related to OsmAnd team cause we're not part of the build process for F-Droid

**Comment by MakiWolf** [comment]
Version 4.0.7 is now avilable in F-Droid.
See also [https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/net.osmand.plus.yml](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/net.osmand.plus.yml)
