### ISSUE TITLE
Downgrading nightly builds seems to fail

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#1269]
I have reports from several of our pilot users that downgrading (manually installed) nightly apks to earlier apks (of the same branch) seems to fail. In deed I seem to be able to reproduce that downgrading e.g. a master-nb apk to an earlier version simply results in an "App no installed" message on the Android install screen.

**Comment by vshcherb** [comment]
There is additional validation on some Android devices that you can't downgrade apk version, which was certainly changed since 2.0 release

**Comment by sonora** [comment]
Yes, but I could verify trying to downgrade from nightly 05-25 to nightly
05-22, which should certainly be the same apk version, right?

**Comment by vshcherb** [comment]
Yes same.
