### ISSUE TITLE
Display not turning off while routing

### ISSUE THREAD

**Issue by thg57** [osmandapp/OsmAnd#12692]
### Description
While routing is active, the display does not turn off after routing directions.

### How to reproduce?
When Osmand is active with a pedestrian or cycle profile, the display turns of as expected after the time set in the display settings. Then:
1. Start routing to a destination
2. Turn display off by on/off button
3. Display is turned on by routing directions
4. display never turns off anymore

### Your Environment
OsmAnd Version: Osmand+ 4.0.7
Android/iOS version: Android 11
Device model:Samsung S10+, SM-G975F/DS

**Comment by vshcherb** [comment]
You can disable it in General Settings -> Screen On -> Voice instructions.

Turning off screen after turning it on doesn't work correctly on some devices and it's a known issue of Android. It depends whether screen has a lock screen or you touched the screen shortly thus it will also prevent to turning it off automatically.

**Comment by vshcherb** [comment]
I remember testing it on S10+ and it works in certain combination. So If you want to turn it of automatically:
Global Settings -> Screen control -> Use system screen timeout - ON.

**Comment by thg57** [comment]
Thanks for the answer. By testing and configuring around I found out, that I was using an old "Hiking" Profile which was migrated from an older Osmand version. When I created a new profile from a built-in profile it worked as expected.
