### ISSUE TITLE
Support maxheight:forward + maxheight:backward

### ISSUE THREAD

**Issue by cicku** [osmandapp/OsmAnd#12702]
Please consider supporting maxheight with direction.

**Comment by alisa911** [comment]
java https://github.com/osmandapp/OsmAnd/pull/15621
tests https://github.com/osmandapp/OsmAnd-resources/pull/863
<img width="674" alt="Screenshot 2022-11-02 at 17 26 05" src="https://user-images.githubusercontent.com/38911173/199530610-32182a2b-b58f-488b-b187-ba9fec5663bc.png">
<img width="641" alt="Screenshot 2022-11-02 at 17 26 15" src="https://user-images.githubusercontent.com/38911173/199530621-66c940e4-f3a2-460d-92e8-f04b46ea17ba.png">

**Comment by alisa911** [comment]
c++ https://github.com/osmandapp/OsmAnd-core-legacy/pull/108
