### ISSUE TITLE
New Audio/Video Notes are recorded with wrong GPS coordinates

### ISSUE THREAD

**Issue by caigner** [osmandapp/Osmand#1270]
In Osmand+ v2.0.4 new Audio/Video Notes are recorded with wrong GPS coordinates.

**Comment by vshcherb** [comment]
Can't reproduce

**Comment by caigner** [comment]
What infos do you need? I could also send you a picture I took within Osmand+, so you can see how far off it is.

**Comment by vshcherb** [comment]
Yes, screenshot is welcome and procedure how did you take picture

**Comment by caigner** [comment]
My hard and software:
Samsung Galaxy S3
CyanogenMod v11-20150517-nightly-i9300
Android 4.4.4

The procedure:
In Osmand+ I click the A/V-note Start button, which is on the upper right side of the screen. It starts the camera app and I take a picture. I use this later for OpenStreetMap-mapping.

I also record audio notes by selecting "Use Location - Take an audio note" from the menu.

Before the upgrade to version 2.0 the A/V notes feature worked fine and I used it alot, so I am quite familiar with this feature. I expected the image (or audio note) to show up on the map. Old notes are displayed, but new ones are not (so I thought at first). Now I found out, that they are actually displayed, but thousands of kilometers away.

**Comment by caigner** [comment]
Hier is a screenshot from the the location where I took the A/V-note (N48.11897 E16.13603)
![screenshot_2015-05-25-19-37-52](https://cloud.githubusercontent.com/assets/886281/7800473/2199b0e4-0316-11e5-8e1b-f637fff026e7.png)

And here is the screenshot from the location where the image ended up:
![screenshot_2015-05-25-19-40-34](https://cloud.githubusercontent.com/assets/886281/7800499/82d3d6f0-0316-11e5-9032-383bafac6e0c.png)
