### ISSUE TITLE
Backport fixes from 4.1 to 4.0 release (Last Android 4.4)

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#12705]
Is there an easy answer to the question what needs to be changed in the code and where (or do we have a branch) in order to build a new nightly which has our recent issue-fixes on board?

Reason is that the last nightlies (and I guess release) we built with Android 4.x support in late August unfortunately suffered from a number of rather basic bugs, like the inability to change the TTS language offline, or the "false ref" issue in navigation, which have only been worked on in recent days, with maybe no prospect of making it back into an Android 4.x-capable build? There may be some built-in devices out there used for navigation which only run And4.4.

Not talking about continuing And 4.4 support, just talking about a final build ending on a better status than what we have. 

**List  of issues to backport**:
- [x] https://github.com/osmandapp/OsmAnd/issues/12827
- [x] https://github.com/osmandapp/OsmAnd/issues/12589
- [x] #12672
- [x] https://github.com/osmandapp/OsmAnd-Issues/issues/742
- [x] https://github.com/osmandapp/OsmAnd/issues/12495
- [x] https://github.com/osmandapp/OsmAnd/issues/12668
- [x] https://github.com/osmandapp/OsmAnd-Issues/issues/761
- [x] https://github.com/osmandapp/OsmAnd-Issues/issues/679
- [x] https://github.com/osmandapp/OsmAnd/issues/12494
- [x] https://github.com/osmandapp/OsmAnd/issues/12631
- [x] https://github.com/osmandapp/OsmAnd/issues/12540
- [x] https://github.com/osmandapp/OsmAnd/issues/12727
- [x] https://github.com/osmandapp/OsmAnd-Issues/issues/766
- [x] #12180
- [x] https://github.com/osmandapp/OsmAnd/issues/12748
- [x] https://github.com/osmandapp/OsmAnd/issues/12533
- [x] https://github.com/osmandapp/OsmAnd/issues/12153
- [x] https://github.com/osmandapp/OsmAnd/issues/12779

**Comment by vshcherb** [comment]
Yes, we plan to move fixes to 4.0. Here you could mention bugs which were fixed in 4.1, so could be backported to 4.0

**Comment by sonora** [comment]
I guess we could also consider:
- [ ] #12180
- [ ] #12672
- [ ] https://github.com/osmandapp/OsmAnd-Issues/issues/764

**Comment by sonora** [comment]
See https://github.com/osmandapp/OsmAnd/pull/12855

**Comment by Chumva** [comment]
Added fix to 4.0 for https://github.com/osmandapp/OsmAnd/issues/13113
