### ISSUE TITLE
Map screen flashes upon OsmAnd resuming

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#12718]
I've noticed this for at least a few weeks now and it's no big deal, but should maybe be looked at:

In our nightlies, have the OsmAnd map screer visible, then tap the device's home button. Now return to OsmAnd, e.g. by tapping its icon on the home scteen: The map screen will come back up and then briefly flash dark, like some weird refresh is happening or something.

Seems hardware dependent, I observe this on mid and higher end devices, slow devices may perhaps have too slow frame rates to display it.

**Comment by vshcherb** [comment]
Confirm it, especially after app was quite some time in background.

**Comment by sonora** [comment]
Looks like this has been aggravated noticeably in our recent AA capable builds.

**Comment by sonora** [comment]
It looks to me like the "aggravated" issue I had added later to this issue is fixed again, but the original issue I had reported is not yet .

**Comment by vshcherb** [comment]
I think it is not an original issue any more cause it's reproducible under very rare circumstances now. It's probably related to a start app or a deep sleep. So I think it now works as before and the issue need to be fixed.

**Comment by sonora** [comment]
It's not a system issue as it happens for no other app I have. It seems to be something we are doing with the map screen onResume. If for instance you tap the device Home button while you had OsmAnd's search screen displayed, then re-tap the OsmAnd app, it will resume in the search screen, but you will briefly see the maps screen flashing through...

**Comment by sonora** [comment]
Have we ever found out why OsmAnd exhibits this strange flashing in the first place, i.e. which portion of our code may cause that?

What I can say is

- that this is an OsmAnd oddity, I see this for no other app.
- And it is not limited to the map screen, it happens also if you e.g. have OsmAnd display the "Configure profile" screen or the "Plugins" screen before you put OsmAnd in the background and then to the foreground again.

So programmatically it looks like some overarching issue in an `onResume()` method...
