### ISSUE TITLE
Plan route: use current selected profile for planning route / measure distance

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#12710]
Idea from
https://github.com/osmandapp/OsmAnd/issues/12022

Immediately as we start Plan Route - new route start with selected profile for Route between points, in most of the cases it's default and it's quite easy to switch to straight line anywa.

**Comment by dmpr0** [comment]
### Review
- [ ]  Public transport profiles should be skipped, use a straight line instead of it.
