### ISSUE TITLE
OSMAnd+ locks itself out while navigating

### ISSUE THREAD

**Issue by speleoluc** [osmandapp/OsmAnd#12716]
Navigating my bicycle to destination with OSMAnd+ 4.0.7 under Android 8, the screen was showing the map until the app suddenly locked itself out and the cellphone display went back to the Android locked screen, while remaining on.

**Comment by vshcherb** [comment]
Similar issue with these settings - https://github.com/osmandapp/OsmAnd/issues/12692
Please try different settings:
General Settings -> Screen control -> Use system screen timeout - ON.

**Comment by speleoluc** [comment]
In OsmAnd Settings I find Default Profile, Display Language, etc. but no
Screen Control.


-- 
Luc Le Blanc
speleo.qc.ca/Auriga

**Comment by vshcherb** [comment]
Check Configure Profile itself  -> General Settings

**Comment by vshcherb** [comment]
https://docs.osmand.net/en/main@latest/osmand/personal/profiles

**Comment by speleoluc** [comment]
I had Use system screen timeout Enabled.


-- 
Luc Le Blanc
speleo.qc.ca/Auriga

**Comment by vshcherb** [comment]
Yes, it's works as expected (as the setting stays). OsmAnd can now work with locked screen i.e. if click power button once and again you will see OsmAnd but the screen is locked (you can't go to any other app) but you can continue using OsmAnd  map by pressing power button.
