### ISSUE TITLE
Highway text frequently expands beyond the label background

### ISSUE THREAD

**Issue by dbolton** [osmandapp/Osmand#1271]
Highway text frequently expands beyond the label background making it difficult to read. (In the usa highways frequently share multiple names as highways merge for a distance and then diverge later.)

**Comment by dbolton** [comment]
![screenshot_2015-05-25-10-25-29](https://cloud.githubusercontent.com/assets/712270/7799472/0a33de56-02cc-11e5-8eaf-a8f8044feea2.png)

**Comment by xmd5a2** [comment]
Fixed
