### ISSUE TITLE
Request access to storage when importing a plugin

### ISSUE THREAD

**Issue by cmoffroad** [osmandapp/OsmAnd#12717]
# 🚀 feature request

### Description

Getting a permission denied error when I tried to install any OsmAnd plugin on a new Android Device.
Manually enabling access storage in Settings > Apps > OsmAnd solves the issue, however, this is not convenient for new users, especially those new users interested in switching to OsmAnd because of a plugin they are interested in.

### Describe the solution you'd like

When a user tries to install a plugin, 
and if permissions for storage have not been yet enabled, 
a dialog popup "This app requires access to storage" opens and asks for user confirmation. 
If the user select OK, then continue to the plugin installation.

**Comment by vshcherb** [comment]
Can you please share a plugin so we can test it.

**Comment by cmoffroad** [comment]
Here is the link to the current version of my work in progress plugin: 
https://github.com/cmoffroad/osmand-plugin-enduro/raw/master/build/osmand-plugin-enduro.osf

**Comment by EugeneZmeuk** [comment]
Did you know this project? https://osmtopo.blogspot.com/2021/02/style-pour-osmand.html#more

**Comment by cmoffroad** [comment]
> Did you know this project? https://osmtopo.blogspot.com/2021/02/style-pour-osmand.html#more

Thanks @EugeneZmeuk for the link! I didn't know about this project.

It looks great and is very detailed. Though I do not see it a good fit for my local community (Thailand) where: 
- we have very limited amount of tags available and limited mapping resources.
- we have very little coverage of ground survey confirmation of road geometries
- we discourage the use of tags like tracktype, smoothness due to the ever changing conditions of roads due to weather.
- offroad conditions are not only found for track and path, but for all types of minor road classifications (from tertiary to footway)

The initial focus is giving an incentive to local offroad mappers to survey roads on the ground and fill in missing basic tags like highway, surface, and highway.

**Comment by dmpr0** [comment]
Hi, @cmoffroad!
By default, OsmAnd does not need permission to access the storage because it uses the internal application memory. Imported files are copied to the application folder without any issues. 

I could not reproduce the permission issue, even when importing a file from shared storage, which requires permission to access it.
