### ISSUE TITLE
Street shows up in search results multiple times

### ISSUE THREAD

**Issue by letorbi** [osmandapp/OsmAnd#12723]
### Description

When searching for the street Tingodden near Hvide Sande, Denmark the street showes up three times. When I select one of the results, each result offers me a different subset of house numbers to choose from. The subsets do not seem to share house numbers.

Expected behaviour: There should only be one result for "Tingodden", which includes all house numbers. 

### How to reproduce?

1. Move map to Hvide Sande, Denmark
2. Search for "Tingodden"
3. Three results will appear
4. Click on a result
5. Try to find house number 260 in the following list
6. Repeat from 4. for the other results

Only one result will have 260 in its list of house numbers.

### Your Environment
OsmAnd Version: OsmAnd 3.9.10
Android/iOS version:10
Device model: Samsung A5 (2017)

**Maps used (online or offline):**   
Denmark standard map (offline, 1 Aug 2021)

**Comment by vshcherb** [comment]
Should be fixed in new maps
