### ISSUE TITLE
Disappering road

### ISSUE THREAD

**Issue by tradavyvy** [osmandapp/OsmAnd#12722]
### Description
'Wiekslag' road disappears at certain zoom levels.

![Screenshot_20210908-133122_OsmAnd+](https://user-images.githubusercontent.com/71978409/132503494-177f7e95-98d3-4a77-83b0-df4e7eaf9aab.jpg)

![Screenshot_20210908-111035_OsmAnd+](https://user-images.githubusercontent.com/71978409/132503514-d7881c28-e2e0-45ea-bc4e-56a1e398a5a1.jpg)

### How to reproduce?
Look up  52.16801° N, 5.40486° E
And play with zoom

### Your Environment
OsmAnd Version:4.0
Android/iOS version:10
Device model:samsung
Osmand mapstyle
Latest utrecht, netherlands map

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by xmd5a2** [comment]
Can't reproduce. May be this is related to OsmAnd Live?

**Comment by tradavyvy** [comment]
Hi xmd5a2,

I do not know what happened, but since this morning the street is back on all my zoom levvels.
(And so are my millitary areas from my other issue)
I do not use nightly versions or osmand live, and did not knowingly update maps or osmand.
But you never know what android desides to do in the background.
Maybe my renderer went on the blink and is now restarted?
Annyway of it is up to me you can close this item.
Davy
