### ISSUE TITLE
Flooding area in Cork Island.

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#12733]
Sometimes areas of land are shown in the sea like Cobh island in Cork Island. Zooming in it renders it ok.

![image](https://user-images.githubusercontent.com/44466116/132823106-49f8a9b4-4c10-445f-91d8-e1c8b0695b2a.png)

**Comment by ivanPyrohivskyi** [comment]
Is not reproducible on the new map from 01.09.2021

**Comment by kgrabe** [comment]
"Is not reproducible on the new map from 01.09.2021"
I still have the issue, where can I find out the map version?
(I reported the bug origianally via email)

**Comment by EugeneZmeuk** [comment]
menu - download maps - local

**Comment by kgrabe** [comment]
> 
> 
> "Is not reproducible on the new map from 01.09.2021"
> I still have the issue, where can I find out the map version?
> (I reported the bug origianally via email)

thanks for that. downloaded the map Europe | Ireland, Standard map dated 1 Sept 2021.
Zooming 2km and over still shows the issue though
