### ISSUE TITLE
Map orientation is reseting after app brought back to foreground

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#12735]
### Description
- Rotate the map (manually) 
- Go to home screen
- Go back to the app

**Observed:**
- Map orientation is back to north

**Expected:** 
- [x] Map orientation stays rotated
- [x] Also taping on the "My location" button is resetting map orientation too.
- [x] Opening navigation menu should't reset map rotation
- [x] Don't reset on zoom out for basemap (Take into account if map orientation bearing / compass - basemap should be north up zoom <= 8-9 ?)

### Your Environment
OsmAnd Version: 4.0.7

**Comment by vshcherb** [comment]
This is ok, it would be not ok if it's reset when app was not killed and brought back to foreground.

**Comment by dmpr0** [comment]
Also taping on the "My location" button is resetting map orientation too.
