### ISSUE TITLE
Going track detail and exit changes perspective/zoom

### ISSUE THREAD

**Issue by mahdi1234** [osmandapp/OsmAnd#12742]
Osmand 4.0.7.

- having imported gpx track and zoom e.g. to "200m scale"

![scale_1](https://user-images.githubusercontent.com/1097047/132961605-73c8db36-1043-46d3-8d9c-49b8774db7c7.jpg)

-  click anywhere on the track on the map to display the details

![scale_2](https://user-images.githubusercontent.com/1097047/132961610-eae045b7-c4f8-49d5-887c-4ddaa8d86522.jpg)

- select "Track" next to "Overview" in bottom part

![scale_3](https://user-images.githubusercontent.com/1097047/132961616-b8351e72-558e-4013-a9d4-68810e723b2b.jpg)

- click "back button"

![scale_4](https://user-images.githubusercontent.com/1097047/132961618-59b5b2a3-988f-4e16-a205-252b7a7d7315.jpg)

Expected:

Still on the same scale

Observed:

See completely different map scale (guess the whole track?).

This is regression to 3.9 it worked imo correctly and returned to original scale/place.

**Comment by vshcherb** [comment]
Not reproducible with 4.1 builds already, I guess it's fixed.
