### ISSUE TITLE
incorect description for tag shelter

### ISSUE THREAD

**Issue by Michael21011** [osmandapp/OsmAnd#12740]
### Description
Shelter=yes is shown as shelter_yes YES
Should be Навес Есть
![Screenshot_2021-09-11-12-48-09-236_net osmand plus](https://user-images.githubusercontent.com/9266780/132957451-db607784-86b6-4d1a-82f8-9c838e9bd01b.jpg)
![Screenshot_2021-09-11-12-47-44-389_com android chrome](https://user-images.githubusercontent.com/9266780/132957457-2a568467-4da2-412d-9799-fb4ef3ebb777.jpg)

### How to reproduce?
Open POI details in Osmand

geo:54.83366,26.93862?z=19
https://osmand.net/go?lat=54.83366&lon=26.93862&z=19

### Your Environment
OsmAnd Version: Osmand+ 4.0.7
Android/iOS version: android 11
Device model: xiaomi mi 10

**Maps used (online or offline):**

**Comment by xmd5a2** [comment]
Not reproducible with latest nightly
![Screenshot_2021-09-24-10-39-05-244_net osmand plus](https://user-images.githubusercontent.com/5829014/134637066-88442a0c-0834-4703-b4c0-bd5b1204bb6f.jpg)
