### ISSUE TITLE
Moving around over track profile does nothing

### ISSUE THREAD

**Issue by mahdi1234** [osmandapp/OsmAnd#12741]
Osmand 4.0.7.

- having imported gpx track, click anywhere on the track on the map to display it
- select "Track" next to "Overview" in bottom part
- freely swipe around with finger over route profile

Expected:

Profile moves

Observed:

Nothing happens.

To be able do so one has to touch exactly "565m" (height denominator) and then can move around. This is regression compared to 3.9 where it worked directly.

![Screenshot_20210911-224134678 (1)](https://user-images.githubusercontent.com/1097047/132961234-34a77a5c-ea8b-480a-9547-09bd13e7431f.jpg)

**Comment by vshcherb** [comment]
Can't reproduce it. And this part didn't change since 3.9 as I know. Probably installation was corrupted
