### ISSUE TITLE
OsmAnd Development plugin's "Test voice prompts", 6.4 "When possible, make a U-turn" is wired to the wrong sample

### ISSUE THREAD

**Issue by mikehgentry** [osmandapp/OsmAnd#12746]
It seems to play the same thing as 6.3, "Make a U-turn", but there is a separate make_uturn_wp.ogg and no apparent way to play it

OsmAnd 4.0.7

**Comment by sonora** [comment]
Well hidden bug in our JS command builder. Thx!
