### ISSUE TITLE
Navigation UI announces every slight road curve

### ISSUE THREAD

**Issue by speleoluc** [osmandapp/OsmAnd#12758]
Running the latest OSMAnd+ (4.0.7) on Android, when I follow a road bike GPX I created in BikeMap.net that sticks to a road, the UI keeps warning me of every slight road curve. Those pesky voice announcements are annoying because they interfere with the actual distance to ride on a given road: instead of giving me the overall distance to next road, the UI reports the distance to the next road curve. I suspect this happens with OSMAnd's own navigation to destination too. Those constant "slight left/right turn" add confusion to real road changes. Can these be turned off, or is it a bug that needs fixing?

**Comment by scaidermern** [comment]
This is not a bug. If you follow a GPX track then OsmAnd can't know whether a turn belongs to an actual intersection or is just a curve.

Try to match your GPX track to the actual road data: Navigation / Track / options / follow track / snap to road / continue / choose navigation profile / apply.

Thisis a rather inconvenient step, though. Would be nice if this was easier and more obvious.

**Comment by pebogufi** [comment]
See also
https://github.com/osmandapp/OsmAnd/issues/8329

**Comment by speleoluc** [comment]
> This is not a bug. If you follow a GPX track then OsmAnd can't know whether a turn belongs to an actual intersection or is just a curve.

It also happens with a (non GPX) route. Yesterday, for a while, at every second, I would be told to keep left on a straight street. So much that I crossed the street to ride in the opposite shoulder, to no avail (it kept telling me).

> Try to match your GPX track to the actual road data: Navigation / Track / options / follow track / snap to road / continue / choose navigation profile / apply.

Is there a way to make this the default behavior for a given profile?

**Comment by scaidermern** [comment]
> > Try to match your GPX track to the actual road data: Navigation / Track / options / follow track / snap to road / continue / choose navigation profile / apply.
> 
> Is there a way to make this the default behavior for a given profile?

I don't think so. But you can match your track to the road beforehand. Open plan a route, open existing track, select track, options, route between points, [...], options, save as new track.

**Comment by vshcherb** [comment]
If you have this issue after "Attach to roads" or with OsmAnd Offline Navigation please provide a link to OSM junction where it should be skipped. We'll investigate this case thorougly.
