### ISSUE TITLE
Adding special setting for National Park rendering

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#12760]
National parks (nature reserve) rendering has only green borders. Sometimes it's unusable.
I propose to add special settings for rendering of such polygons as national parks. Something similar OsmAnd has with Green zones in cities (https://docs.osmand.net/en/main@latest/osmand/map/vector-maps#details   Show Low Emission Zones )

**Comment by tradavyvy** [comment]
See item #11982.
There is an extensive discussion about this subject.
