### ISSUE TITLE
Missing voice alert when you divert the route (route  recalculation is disabled)

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#12761]
The support team had a request:
If I use the navigation functionality for example in the walking profile
with route recalculation switched off and when I divert from the route I do not get a visual or audio message that I diverted from the route calculated consequently it happened often that I continued without
realizing that I was no longer on the route.

Make, please a visual and audio message when you diverted from the route when recalculation mode is switched off.

**Comment by vshcherb** [comment]
1 alert should be always pronounced

**Comment by Robgru2** [comment]
a visual indication on the screen would also be helpful required in my view

**Comment by vshcherb** [comment]
There is a visual indication already, it's a special dashed straight line with distance
