### ISSUE TITLE
Keyboard missing in 'Track saved' dialog

### ISSUE THREAD

**Issue by Kembolowski** [osmandapp/OsmAnd#12779]
### Description
The keyboard is not appearing when taping to the textbox 'GPX filename' in the 'Track saved' dialog. Only the cursor is visible. When taping a second time only then the keyboard gets visible.

### How to reproduce?
Record a track and stop it after some time. A dialog appears which offers the possibility to rename the filename. Tap into the textbox. The cursor will appear but the keyboard won't pop up.

### Your Environment
OsmAnd Version: 3.9.10
Android version: 11 (GrapheneOS)
Device model: Pixel 4a

**Comment by vshcherb** [comment]
Needs to be double checked if it's device specific

**Comment by Kembolowski** [comment]
The bug can be reproduced as well on a Samsung Galaxy S20 FE with default Android (version 11).

**Comment by cepprice** [comment]
Can't reproduce on Pixel 2 (Android 10), Pixel 4a (Android 11) emulators and Poco x3 Pro (physical device)

**Comment by vshcherb** [comment]
I just noticed 3.9.10, it was fixed probably in 4.0

**Comment by Kembolowski** [comment]
I can confirm. The issue doesn't exist anymore in version 4.0.7
