### ISSUE TITLE
Position marker lagging severely when using external GPS receiver

### ISSUE THREAD

**Issue by kreuzschnabel** [osmandapp/OsmAnd#12777]
Hi, I love to use external GPS receivers for their higher precision. These receivers are connected to my phone via Bluetooth and the app "Bluetooth GPS" which gets them into Android as a mock position source.

This worked well with my old GT-750. However, when I switched to a new receiver, Garmin GLO-2, the position marker is lagging severely behind when going by car, up to a few hundred meters. This is awkward a) because waypoints as AV notes taken by the way will be stored in a wrong position, and b) the entire screen frame lags behind position when giving directions so the junction I’m approaching might not even be visible.

See images on https://imgur.com/a/8aHY9HF

This might be caused by the Garmin’s high measurement rate of 10 data sets per second which might be too much data for OsmAnd to process. Other navigation aids, e.g. Magic Earth, have no such problems with the external device, they keep their position markers precisely up to date.

Funnily enough, this applies to the position marker only (+ the alignment of the moving map). OsmAnd’s track recording plugin as well as the route indicator (back end of the purple overlay) do keep the correct position, the latter being on my real position far ahead of the you-are-here car icon.

### How to reproduce?
- Connect a Garmin GLO-2 via Bluetooth GPS as Android’s GPS source (mock position)
- Observe OsmAnd’s position marker while moving fast (i.e. more than walking speed)

### Your Environment
OsmAnd Version: OsmAnd+ 4.0.7
Android/iOS version: Android 11 / Lineage 18.1, rooted device
Bluetooth GPS version: 1.3.7
Device model: OnePlus 5T

**Maps used (online or offline):**   offline, with Live maps enabled

--ks

**Comment by vshcherb** [comment]
You can disable "animation" in navigation settings, though it means that location is provided not frequently enough. It's expected to have GPS once a second on average and that probably doesn't happen here.

**Comment by kreuzschnabel** [comment]
"Not frequently enough" does not exactly hit it. The location is provided up to 10 times per second by the Garmin device, confirmed by the trackings recorded which show perfectly rounded curves. And, as I said, it’s just the marker that lags behind so badly. Even within OsmAnd, the track recording as well as the route directions follow the actual location perfectly, so it’s by no means a question of "not frequently enough".

I will try if disabling the animation helps.

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/134001831-c562766f-ef4b-4b00-8c54-2ce2247185a5.png)

![image](https://user-images.githubusercontent.com/1042025/134001810-5c3d988b-45e8-4189-917d-c2e3c9366c7a.png)

**Comment by kreuzschnabel** [comment]
That’s it. The actual position I was at when the screenshots were taken are the "ends" of the purple overlay of the navigation. So they follow the location provided exactly. In the 2nd image, i was actually 74m ahead of the junction. However, the blue car icon (and the reference point of the moving map) lags a few hundred metres behind. 

--ks

**Comment by kreuzschnabel** [comment]
Disabling "animation" in navigation settings solved the issue, the position marker is up-to-date now. I still think my GPS data to be rather "too good" for Osmand than "too poor" :)

--ks

**Comment by pebogufi** [comment]
I never understood what this animation is really good for.
This is not the first bug report which ends with the recommandation "switch off animation".

**Comment by sonora** [comment]
True statement. One of the worse ones is that it is suspected to cause inaporpriately high power consumtion on some hardwares.Have not checked if this is on by default, but if yes we should likely change that. I personally always have it disabled.
