### ISSUE TITLE
Change the language for the Voice prompt does not work correctly

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#12775]
### Description
When you select the Portuguese language as Voice prompt the voice guidance announces information on the previously selected language but not Portuguese.

### How to reproduce?
Select English language create navigation->finish navigation->then select Portuguese->start navigation (information will be announced in English)->finish navigation->Selec any other language (for example Russian) and when you start navigation information will be announced in Portuguese.

The only way to have selected Portuguese in Voice prompt and have voice guidance in Portuguese is to select this language for the navigation then close and open the app.

### Your Environment
OsmAnd Version: 4.0.7
Android/iOS version: Android
Device model: Xperience XZ1

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by vshcherb** [comment]
Duplicate - https://github.com/osmandapp/OsmAnd/issues/12747
