### ISSUE TITLE
[Search results] Show and clear search results on the map consistently

### ISSUE THREAD

**Issue by pelderson** [osmandapp/OsmAnd#12786]
1. After a search for a name you get a result list, ordered by distance, and a button to show all the results on the map. This temporary result layer remains there until I restart the app. I can see no other way to lose the search results. 
2. After a search for a category, you get a result list, ordered by distance, and a button to show all the results on the map. This toggles a POI layer, which remains when I restart the app. Only switching the layer off in the Configure map menu removes these search results. 

Although I think I understand what happens, to the user this is inconsistent behaviour. 

In both cases the user would want to be able to show the result set on the visible map temporarily, then later discard the search results including the map display. "Clear current search" could be explicit user action, or implicit e.g. when starting a new search or starting routing for one of the results.  It should not require a restart of the app or going into the layer config. 

The option to make a search "sticky" for the map display is not at all bad, if it is presented as such, and comes with an intuitive "clear sticky search" option.

I hope this makes sense, if not, shoot!

**Comment by pebogufi** [comment]
Did you try to use in the top line of search result the "x" or "<-"

**Comment by pelderson** [comment]
Thanks, I needed that! I'll pass this on and let the user test it.

**Comment by pelderson** [comment]
Got the results back. There still is a bit of a problem.

1. Search > Category > Cafe and Restaurant > Show on map
The search bar is present and X clears the search and the display of the category

2. Search > Category > Cafe an Restaurant > Show on Map 
Tap back arrow and you are back in the search. 
Tap back arrow and you are back on the map, but the Cafe an Restaurant display is still on, and there is no X.
Hard stopping OsmAnd during a category search also cancels the search but not the display of a category.

3. With a name search, the same happens, except after a forced restart the displayed results are cleared.

**Comment by pebogufi** [comment]
ref. 2. What you describe is not a bug, but a feature.
 
Like that you can define different search results for different profiles. 
For example you can display 
petrol stations and parking for profile car, 
viewpoints, guideposts and wayside crosses for profile hiking,
mountain passes for profile bike.
When you switch between profiles you see the interesting details you preselected before, for each profile what you like.
That is a very powerful feature which i really love when traveling or making holidays.

In Configure map of each profile in 2nd line "POI-Overlay" you can easily select or deselect theese search results.
Of course you can create your own search patterns, have a look on "user defined search", which is even more powerful !
Different user defined search in different profiles are really great.

**Comment by pelderson** [comment]
That is the layer config per profile. Great, but you don't expect to do that in a search. Most map apps show a layers icon for the layers. But that's another issue.  Thanks for clearing this up!
