### ISSUE TITLE
Add note:destination tags for guidepost pois in details page

### ISSUE THREAD

**Issue by MakiWolf** [osmandapp/OsmAnd#12784]
# 🚀 feature request

### Description

I have reported before in [https://github.com/osmandapp/OsmAnd/issues/12391](https://github.com/osmandapp/OsmAnd/issues/12391) to support destination and direction tags. But I have seen that some pois are also tagged with note:destination. It would be great when also this tag is supported like here in [https://www.openstreetmap.org/node/6644558016](https://www.openstreetmap.org/node/6644558016)

### Describe the solution you'd like

Also add note:destination to osmand resources repository

**Comment by scaidermern** [comment]
The [note](https://wiki.openstreetmap.org/wiki/Key:note) tag is meant for other mappers and not for end-users. So I think this is wrong tagging. `note:destination` should be replaced with `destination` if this information is meant to be visible to end-users.

**Comment by MakiWolf** [comment]
@scaidermern  
I agree with you that this should be fixed in OSM Data.
