### ISSUE TITLE
Incorrect navigation instruction by following the track

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#12781]
### Description
The voice and screen instructions (turn arrows) tell incorrect information. For example, when you need to turn right it says that you should turn left. Some turns are not announced at all.

![Screenshot_2021-09-14-11-39-27-457_net osmand](https://user-images.githubusercontent.com/80623554/133572093-ff54cc1e-4fd0-41e8-8958-8e8ee637b15a.jpg)
![image](https://user-images.githubusercontent.com/80623554/133572161-10929c25-3967-4737-9cf7-e756018586bc.png)

### Your Environment
OsmAnd Version: 4.0.7
Android/iOS version: Android 
Device model: Nokia 2.4

**Maps used (online or offline):**   offline
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by Zirochkabila** [comment]
The case was checked on version 4.1.11 of OsmAnd - voice prompts work properly.
Route construction was checked near Studenchiskaya street, Belgorod region - the route is built correctly.

**Comment by Zirochkabila** [comment]
The case was checked one more time on version 4.1.11 of OsmAnd - voice prompts don' work properly.
Route construction was checked near Studenchiskaya street, Belgorod region - changing the route when starting the GPX track navigation (BUG)

> ### Description
> The voice and screen instructions (turn arrows) tell incorrect information. For example, when you need to turn right it says that you should turn left. Some turns are not announced at all.
> 
> ![Screenshot_2021-09-14-11-39-27-457_net osmand](https://user-images.githubusercontent.com/80623554/133572093-ff54cc1e-4fd0-41e8-8958-8e8ee637b15a.jpg) ![image](https://user-images.githubusercontent.com/80623554/133572161-10929c25-3967-4737-9cf7-e756018586bc.png)
> 
> ### Your Environment
> OsmAnd Version: 4.0.7 Android/iOS version: Android Device model: Nokia 2.4
> 
> **Maps used (online or offline):** offline If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by Gbernardy** [comment]
This is the same problem reported in # 13752 as fixed in 4.2 🤔
