### ISSUE TITLE
Simple waypoint notification during navigation

### ISSUE THREAD

**Issue by adegans** [osmandapp/OsmAnd#12780]
# 🚀 feature request

### Description

I know Osmand has a turn by turn voice thing.
But I, like many others, don't like to use that. 
The voice sounds weird and forced, which makes me focus on the instruction and miss my turn.
Likewise, some names of turns take so long to pronounce that when it finally announced the thing I missed the turn.
And for non-english names it takes seconds ot interpret them (for me as a non-native speaker anyway) which defeats the point of using voice at all.

This is of-course in part an issue on my side for not being used to this kind of navigation.
On the other hand it's the poor TTS engines available to Osmand to make this work more intuitive.
Either way, there are people who like an alternative method of notification

### Describe the solution you'd like

A good and simple alternative is a sound alarm when a waypoint comes up in the route.

For example; 500M (configurable) before a waypoint is coming up Osmand could sound a little alarm. Similar to a SMS ringtone. "ding ding" or "beep beep" or whatever sound the user chooses.

That way the driver knows to pay attention to the screen and surroundings as something important is coming up.

Likewise there could be a little alarm like this for when you go off-route by N meters.

This of-course should work for planned routes in Osmand, but also (and more important to me) for GPX imported routes.

### Describe alternatives you've considered

TTS, but it kinds sucks for non english and the speaking takes too long causing distractions for interpreting the instruction which is dangerous if the instruction is about navigating a highway exit or city crossing.

Thanks for your consideration.

**Comment by 0709wiwiwi** [comment]
Hi Sir Adegans.
Here we already meet again ;-)

What you expect is not a rattling TTS lady but a single compact tone indication shortly before a turn or info Via announcement.
So something like in next example show in the video. 
https://youtu.be/eUyRNRf0fXk
Normally the screen turns on at the prompt and then off after the turn.
For the demo I did not use as otherwise you notice more black screen than active. 
So simulate all the screen on/off action by blinking your eyes ;-)
Tone code used see the video description pse.

Loud and clear mode so very usefull in traffic conditions 
And yes,  you get used to this turn alert mode very quickly.

**Comment by adegans** [comment]
The screen is always on when I'm driving. I'm on a motorcycle.
But yes, a beep or sound prompt, similar to what you indicate. Your indicator warns for a turn, and a simplistic beep would probably suffice until you enter a twisting road.

My idea is for actual waypoints though. That way the creator of the route can sort of decide where a warning is needed simply by adding a waypoint to the route. Of-course, and most important to me, Osmand should handle GPX waypoints as well as the route planner waypoints.

For example, last week, when entering Mexico City for the first time I added extra waypoints with a name as warning before important intersections. The waypoint would be named "KEEP LEFT AND TURN LEFT ON CROSSING" or "ENTERING CITY CENTER" which kinda works, but the names are long and get lost in the mishmash of the city. 

Likewise, when I'm driving and enjoying myself in the countryside I sometimes don't pay attention to Osmand and miss a turn. 

Here's an example file - https://disk.stor.fit/index.php/s/JTS8LBXSpcQigE2
All waypoints in CAPITALS (in dutch) are extra as an extra warning.

Hence a sound signal, so I know to look down to the screen and see the turn coming up. Perhaps I don't need the extra waypoints anymore in big cities/intersections. Or use them with the sound indicator and be super prepared to turn (probably).

I think, since there already are triggers in osmand for the TTS prompt, it's not too difficult to detect when the indicator should sound (same trigger) and even shared settings are probably possible. Just 2 extra settings are then needed, Voice or sound, and then which sound (which can be the SMS ringtones of the device).

Thinking about it now, the signal It could also be a spoken thingy like "turn coming up" or "attention" or something concise.
Perhaps a 3rd setting for that, but personally I think a simple sound would suffice for most people.

Thanks @vshcherb for adding the label, does that mean it's on a to-do list? 🙃

**Comment by 0709wiwiwi** [comment]
@adegans

[NL] Net nog even gemakkelijker ;-)

Aha aan de hand van je file voorbeelden denk ik nu begrijpt wat je wenst.
Ik ken alleen momenteel de Kurviger app die momenteel dit zo mooi kan.
https://youtu.be/bOthQwHT9YU
Mogelijks verwacht je dus zo iets zoals te zien in de volgende video. Correct ? 
Even horen of wat de Kurviger app hier uitvoert dit is wat je dus verwacht ? 

Om hierin te slagen aan de hand van je waypoints heb ik je file wel eerst aangepast! 
[14 Cuernavaca - CDMX_cleaned.zip](https://github.com/osmandapp/OsmAnd/files/7191712/14.Cuernavaca.-.CDMX_cleaned.zip)
Goed routeren met instructies =  Planner punten plaats je met discipline, HEEL VEEL discipline!

A. De waypoints in je file zijn nu wel in de geheel correcte stricte punt volgorde geplaatst 
    Waypoints steeds iets wat weg van wegkruisingen bespaart je bovendien heel wat problemen. 
    Soms kan het meevallen, maar als het wpt op de verkeerde (zij)straat valt is het gegarandeerd VEEL ellende.
B. Verwarrende (voor de routerings engine en app) groepjes gewone geisoleerde poi wpt zijn hier dan ook verwijderd. 
Vind de aanpassingen in het gpx attachment. (Gebruik best het pc gpx editor programma voor goed overzicht)

Besef: 
Een router met een zijn eigen optimale routeringsprofiel zal steeds het eigen 'beste' traject genereren en dat kan afwijken van het origineel.
Zodra een routeringmachinge, voor wel doel dan ook, er zich gaat mee bemoeien wees dan op je hoede voor onverwachte trajectwijzigingen.
Je moet een (re)routering, en indien mogelijk volgens het routeringsprofiel, soms met extra shaping of Via Points bijsturen om te rijden daar waar je het wenst. 
Ik heb in de video dit opzettelijk niet gedaan, er zijn dus kleine (rare) afwijkingen met het originele traject. Daarmee ben je steeds geconfronteerd bij (re)routing.

Dit alles was dan ook mijn grootste motivatie om toch ook even in dit osmand forum die eenvoudige Locus gpx track mode te tonen.

[EN] 
As this single Locus gpx track smartly combines both the advantages of a (trk)track inclusive the directional turn by turn commands and a (rte)route flexibility.
And additionally freely positioned poi (wpt) waypoints can easily be attached into that same file. Waypoints can be announced by the omnidirectional Locus poi alert module. @ adegans.  I expect this is the  most simple uncritical alerting wpt mode as you probably insist for to suse this by a simple tone alert of TTS name expression (free  xx distance alert setting) 

Thereby keeps 100% traject fidelity, but still is flexible able to reroute a traject or smaller segments by the Planner Shaping_Via points when explicitely asked for by the navigator.

**Comment by adegans** [comment]
Maar ik gebruik Osmand, geen Kurviger.
Mijn bestanden werken veelal prima.
Het enige wat ik vraag is een geluid signaaltje als je in de buurt komt van een waypoint, meer niet.

**Comment by 0709wiwiwi** [comment]
Understood, a simple waypoint approach alarm is enough for you.
https://youtu.be/ahJtOqbDVto
That OMSAND doesn't even offer this 'by default' surprises me.

**Comment by vshcherb** [comment]
Well we have configurable TTS / Voice engines, so you could try to create your own voice package by reusing existing https://github.com/osmandapp/OsmAnd-resources/blob/master/voice/nl/nl_tts.js.

I have a plan to write documentation how to create simple tts-beep package and clean up old packages to have less confusion, but I would be honest it's not in the first priority list.

**Comment by mikehgentry** [comment]
There are plenty of beeps available here:

https://github.com/mikehgentry/OsmAnd-resources/tree/master/voice

I'm still working on the profiles, and will put a new zip in this bug every so often:

https://github.com/osmandapp/OsmAnd/issues/10501

**Comment by adegans** [comment]
Hi @mikehgentry how do I install that?
I've put beep-complex in 'voice' on my phone, but it's not showing up in settings.

**Comment by mikehgentry** [comment]
Hi @adegans

You need to download a voice pack from within OsmAnd (I use Arabic for this example, because it's at the top of the list and I don't speak Arabic, but it really doesn't matter).

Navigation -> Settings -> Sound settings -> Language -> Recorded -> Arabic

Then connect the phone to a computer (or find some other way of accessing the filesystem - this may be more complicated from the phone itself on Android 11). Go to

<Phone>/Android/Data/<OsmAnd directory>/files/voice/ar

Install the .ogg files and beep.js file you want to test. Delete (or rename) the original ar_tts.js file, and rename the beep.js file to ar_tts.js

You may have to end navigation and start it again (or quit OsmAnd entirely and rerun it). Now if you select Arabic recorded voice, it should use the beeps.

If you delete the voice pack from inside 'Downloaded maps', it gets rid of the entire directory, so not much that can go wrong.

Thanks for testing, suggestions are appreciated.

**Comment by vshcherb** [comment]
@mikehgentry you can create a backup of voice package and attach it here, that would be more convenient to install & distribute. And we could rename it to beep.js in osf file

**Comment by mikehgentry** [comment]
@vshcherb There are four versions here. For a bike I'd definitely recommend the louder one. I could imagine it being pretty unpleasant in a car though.

[beep-loud-simple.zip](https://github.com/osmandapp/OsmAnd/files/7204536/beep-loud-simple.zip)
[beep-simple.zip](https://github.com/osmandapp/OsmAnd/files/7204537/beep-simple.zip)
[beep-complex.zip](https://github.com/osmandapp/OsmAnd/files/7204538/beep-complex.zip)
[beep-loud-complex.zip](https://github.com/osmandapp/OsmAnd/files/7204540/beep-loud-complex.zip)

I'm afraid I don't understand if I need to change anything to make it easier to install, but let me know. Cheers.

**Comment by adegans** [comment]
Hah I see.
That worked, I've overwritten the English pack though as a test haha.
I made a basic voice profile with the few instructions I think I need for POI and Highway exits.
I also reworded the TTS so that it's more casual and short.

In a simulated route that seems to work fine.

Perhaps I should pick a language I don't speak, like arabic, so I can switch should the need arise.

I'll try it out in a few days when I go for my next ride.

@mikehgentry It would be easier if Osmand could recognize 'custom' TTS profiles without having to overwrite an existing language. For example, just list all folders in voice so I could make a my custom version available as 'en-modded' or whatever and that would show up in Osmand as a language option to choose.

@vshcherb Yep, I made a backup. If it works I'll share my modded version. Others may find it useful.

**Comment by adegans** [comment]
Are the voice things overwritten with updates or other actions when Osmand does something on its own?

**Comment by adegans** [comment]
Using arabic for spoken English is rubbish it turns out ;) 
The accent Android throws in is terrible. So I'm replacing the default en-us tts bit.

Anyway, I did some further testing, does Osmand's TTS stuff not now know about POI pins in a GPX?
I created a simple route with 4 Waypoints (route pins) and 2 POI (POI pin) and it calls the POI as waypoints too, while in the en-tts.js file there is a provision for POI. Are those only for OSM locations (POI overlay)? 

Any way to make that distinction for GPX POI pins? (minor detail).

I'm going to do a real test tomorrow when I actually drive a route.

**Comment by 0709wiwiwi** [comment]
[quote]I created a simple route with 4 Waypoints (route pins) and 2 POI (POI pin) [/quote] Example file available ? 
[quote] Any way to make that distinction for GPX POI pins? (minor detail) [/quote]  Minor ?

**Comment by vshcherb** [comment]
Packaged as Plugin (before importing delete zip in the end)
[beep.osf.zip](https://github.com/osmandapp/OsmAnd/files/7225030/beep.osf.zip)

**Comment by adegans** [comment]
> Packaged as Plugin (before importing delete zip in the end)
> [beep.osf.zip](https://github.com/osmandapp/OsmAnd/files/7225030/beep.osf.zip)

How does that work? Is there a UI for installing plugins?

**Comment by vshcherb** [comment]
Yes, we make extra fix to support .osf.zip but for now .osf works.

**Comment by adegans** [comment]
> Yes, we make extra fix to support .osf.zip but for now .osf works.

I don’t know what that means…

Anyway, yesterday i tested my waypoint navigation tts.
Seems to work fine, other than osmand losing track and not speaking waypoints for a larger chunk of the way.
I think because i took a break and didn't stop the route/navigation during it… not sure.
But when osmand was on point the waypoint and poi notifications came in fine.

I’ll try a few more routes and fine tune the tts js in the coming days.

**Comment by vshcherb** [comment]
beep voices have been fixed with plugin.osf in nightly build already.
There is a spinoff to support osf.zip - https://github.com/osmandapp/OsmAnd/issues/12863

**Comment by adegans** [comment]
Sometimes I feel there is a true disconnect with what I'm writing and what you guys reply or do here.
But sure... close it, I'll see if I can figure this out on my own with my custom TTS profile.

**Comment by vshcherb** [comment]
Obviously it's disconnected, though it was first marked as require investigation and later a workaround with custom beep navigation is found. 

So for now it's not possible to use TTS + beep sounds and that could be implemented later.
