### ISSUE TITLE
Always use my current location when I enter a different one in the "from : " field

### ISSUE THREAD

**Issue by zwykx** [osmandapp/OsmAnd#12785]
### Description
I sometimes want to calculate the length/time between 2 points on the map.
So I enter these 2 points in the fields "De :" (in french) i.e From, and "A :"  (in french) i.e  To, and touch "Continuer" (Continue ?).
Then OsmAnd start to calculate the route and finally displays the route between MY current location and the entered destination (A/To).

### How to reproduce?
Type a start address different from your current location identified by the satellites and see the result.

### Your Environment
OsmAnd Version: 3.3.8
Android/iOS version: android 8.0.0
Device model: ASUS_Z01KDA

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by dmpr0** [comment]
Hello!
It happens because you tap "Start". This button starts the navigation, and navigation always uses your location. You can set the "From-To" points route will be calculated without taping the "Start" button.
Also, you can use "Plan a route" for this.
