### ISSUE TITLE
Invalid GPX generated by Trip Recording plugin

### ISSUE THREAD

**Issue by daniel-molina** [osmandapp/OsmAnd#12789]
### Description

Output GPX by Trip Recording plugin is invalid (e.g., according to xmlvalidation.com). I attach one example (extension manually changed by me from gpx to txt jut to correctly upload the file to github)

### How to reproduce?

Just using the Trip Recording plugin in a normal way.

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version: Lineage 9
Device model: FP3 (Fairphone)

**Maps used (online or offline):**   
Not sure now, most probably not related. I may check it if needed.

[BusGranadaZubia.txt](https://github.com/osmandapp/OsmAnd/files/7180975/BusGranadaZubia.txt)

**Comment by daniel-molina** [comment]
I can say that a [slightly similar FitoTrack issue](https://codeberg.org/jannis/FitoTrack/issues/321) was reported (but what is reported there does not seem to be the case here)

I though it has an error because viking increases the number of errors when exporting the modified track, so I deduced that the original error was being propagated, but maybe it is exclusively viking fault. I'll report it in [a viking similar issue](https://github.com/viking-gps/viking/issues/137).

**Comment by vshcherb** [comment]
We have a correct version set to '1.1' https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd-java/src/main/java/net/osmand/GPXUtilities.java#L1905.

Actually for now it's hard to understand what needs to be fixed and for which program, so it's tricky then to fix it with unclear goal.
