### ISSUE TITLE
CRASH in nightly when selection POI Overlay

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#12790]
### Description
Selecting a profile, then POI Overlay, 3-dots menu, then CRASH

### Your Environment
OsmAnd Version:  4.1.0#32727m 410, 4.1.0#32731m 410
Android/iOS version: 10
Device model: Samsung Tab S5e

[exception.log.zip](https://github.com/osmandapp/OsmAnd/files/7183077/exception.log.zip)

After installing **older version**, OsmAnd~  4.1.0#**32706**m.apk, **no problem**.

**Comment by alex-osm** [comment]
Fixed by https://github.com/osmandapp/OsmAnd/commit/0ae8e376ec7c31009c0aecc043629dc20ac1103e
