### ISSUE TITLE
Support abbreviation of US State names in TTS

### ISSUE THREAD

**Issue by ghost** [osmandapp/Osmand#1279]
OsmAnd already supports country names. Ex. "ref=US 1" is read as "United States one"
https://www.openstreetmap.org/way/11514036

Please add support for State abbreviations. Ex "ref=ME 9B" is read as "M-E Nine-B" instead of "Maine Nine-B"
https://www.openstreetmap.org/way/11522354

A full list is available here as documented on the OSM wiki: https://wiki.openstreetmap.org/wiki/United_States_roads_tagging#State_Highways

ALABAMA                         AL
ALASKA                          AK
AMERICAN SAMOA                  AS
ARIZONA                         AZ
ARKANSAS                        AR
CALIFORNIA                      CA
COLORADO                        CO
CONNECTICUT                     CT
DELAWARE                        DE
DISTRICT OF COLUMBIA            DC
FEDERATED STATES OF MICRONESIA  FM
FLORIDA                         FL
GEORGIA                         GA
GUAM                            GU
HAWAII                          HI
IDAHO                           ID
ILLINOIS                        IL
INDIANA                         IN
IOWA                            IA
KANSAS                          KS
KENTUCKY                        KY
LOUISIANA                       LA
MAINE                           ME
MARSHALL ISLANDS                MH
MARYLAND                        MD
MASSACHUSETTS                   MA
MICHIGAN                        MI
MINNESOTA                       MN
MISSISSIPPI                     MS
MISSOURI                        MO
MONTANA                         MT
NEBRASKA                        NE
NEVADA                          NV
NEW HAMPSHIRE                   NH
NEW JERSEY                      NJ
NEW MEXICO                      NM
NEW YORK                        NY
NORTH CAROLINA                  NC
NORTH DAKOTA                    ND
NORTHERN MARIANA ISLANDS        MP
OHIO                            OH
OKLAHOMA                        OK
OREGON                          OR
PALAU                           PW
PENNSYLVANIA                    PA
PUERTO RICO                     PR
RHODE ISLAND                    RI
SOUTH CAROLINA                  SC
SOUTH DAKOTA                    SD
TENNESSEE                       TN
TEXAS                           TX
UTAH                            UT
VERMONT                         VT
VIRGIN ISLANDS                  VI
VIRGINIA                        VA
WASHINGTON                      WA
WEST VIRGINIA                   WV
WISCONSIN                       WI
WYOMING                         WY

If this is as simple as editing a text file, I would be happy to complete it just direct me to the proper place.

**Comment by sonora** [comment]
Fred, unless I am very mistaken, we do not actually actively support any country abbreviations either in our code, but solely rely on the Android respectively the phones's TTS engine capabilities (which do actually vary between Android versions and, device brands, and also additional TTS packages installed, if any). 

I only added very few (literally less than 5 or so) manual corrections, e.g. in order to avoid "State Route 50", often abbreviated "SR 50", being pronounced as "Senior 50", I added a manual exception there. But I think a larger number of exceptions, particularly country-specific exceptions will be hard to maintain, and I think the strategy must be to wait and benefit from any development the TTS engines will make independent of OsmAnd.

Best, Hardy

**Comment by fred702** [comment]
Hardy, 
Thanks for your response and clarification. As a user of the AOSP TTS engine, I don't expect much improvement any time soon. But as you stated this challenge goes beyond any individual situation. 

I would like to help create a more consistent experience in this regard, especially for users who may not be able to upgrade to new software or a new device regularly.

Country-specific exceptions may be hard to maintain, but at least in the case of US states and territories they change very infrequently. There is also the benefit of already having wide adoption of tagging in OSM. It may be best to limit these exceptions to the ref=* tag and only within countries they should appear.

**Comment by sonora** [comment]
Yes, "maintain" was the wrong expression for me to use, I essentially meant 2 things:
- If we do this for the US, we may ultimately need to do it for most countries (Canada, Mexico, etc.), which will all have similar issues. And globally, this is a daunting outlook. (Needless to say, there will be collisionsm the acronyms are not unique).
- For now I am not aware we could limit this to a certain region, nor may it very be feasible to limit this to certain languages. And as far as I can see now, we may introduce more issues than benefits here: Imagine we code that MT is always pronounced as "Montana". But there are countless circumstances when even in English you would expect "Mount", and in Italian maybe "Monte" (unless we talk an Italian tourist travelling in Montana ... :-) ). 

So essentially what I am saying is: I have no good universal concept, and feel it is simply something which is beyond the scope of OsmAnd, it must be solved by language-specific and environment-aware code which belongs in the TTS engines not in our app. I will think about this some more, but for now this is my gut feeling ... 

Even for the small fixes I have made, I had run into unexpected issues: While most TTS engines want to pronounce "SR" as "Senior", I originally wanted it to pronounce "State Route" (not just S-R), but in Italian it is mostly "Strada Regionale" (regional road). And then I limited it to English, and on one of my test trips I heard OsmAnd say: "State Route Gonzales Road". Well, this was in New Mexico, and should actually have been "Senor Gonzales Road"  :-). So you see, all sorts of pitfalls here ... :-)

**Comment by jfburke3** [comment]
Just idly thinking out loud here.....

* Perhaps limit it to only ref tags.  Senor Gonzales Road should be in a name tag, so it would be unaffected.  I would expect the same for Mount.

* Perhaps a loadable module that is different depending in where you are.  E.g., when your current location is in Montana, load a small module that pronounces MT in a ref tag as Montana but not other two-letter things.

Again, just idly speculating.  The implementation of something like this is beyond my mental capability.

--jack

PS - Fred, at least you don't have to hear it say "Gah 3" instead of G A 3 (for Georgia highway 3).

**Comment by sonora** [comment]
I like the Gah 3 vs. G A 3 example ...  :-)

Wondering if we should maybe catch if something is all uppercase and make
it pronounce letters one by one in this case. I would have thought most tts
engines behave like that anyway, but it appears most Android-built-in
engines don't ...

**Comment by sonora** [comment]
No good concept here and not much progress either, let me close this for now to have more focus on higher prio topics.
