### ISSUE TITLE
Excess notifications on map updates for every download percent change

### ISSUE THREAD

**Issue by gauravjuvekar** [osmandapp/OsmAnd#12803]
### Description
During map updates, a notification sound / vibration is played every time the "percent downloaded" updates. This is excessive. 

### How to reproduce?
Already have some offline maps downloaded. 
When updates are available, "Download maps > Updates > Update All > Update"
The download progress bar shows in the app and a Android notification showing the download progress bar also shows.
Every time the percentage is updated, the default notification sound / vibration plays. 

### Your Environment
OsmAnd Version: 4.0.7 from Fdroid
Android/iOS version: 10 - LineageOS 17.1 2020-11-26
Device model: OnePlus 6t

**Maps used (online or offline):**   
Offline, any map file.

**Comment by vshcherb** [comment]
It's probably should be reported on Lineage OS as well cause it's not reproducible on Android devices and I don't think there is another API how to update notification except replacing it but we're going to recheck it.

**Comment by gauravjuvekar** [comment]
AFAIK, there should be some way to update an existing notification on android. Other apps such as google photos upload / whatsapp message backup / vlc "scanning media" show a single notification that updates it's percent completion.
