### ISSUE TITLE
Restore of all favourites does not delete all existing favourites

### ISSUE THREAD

**Issue by frobijn** [osmandapp/OsmAnd#12800]
# 🚀 feature request

### Description
I was investigating the use of backup/restore to get closer to [automated synchronisation](https://github.com/osmandapp/OsmAnd/issues/2750) of favourites where an external application manages the collection of favourites. It can also occur if you have several sets of favourites (e.g., one set per holiday and one or more sets for activities when at home) and you want to swap out one set for another. I'm not sure whether this is an issue or feature request because I may expect something different from "backup"/"restore" than what it was intended for.

In these scenarios I would like to replace all favourites by restoring a previous backup. The restore option of OsmAnd 4.0.7 reads the backup (*.osf) file and asks what to backup. I select "favourites". If the app detects that there are favourites present, the app offers the option to replace the existing waypoints or to add them to the current favourites. I select "replace". After the restore, the list of favourites is as I expect it to be: all favourites are from the backup set.

Well, most of the times. What the app does is make a list of waypoint types present in the backup. The option to replace or add favourites only applies to those types. If there are favourites present that have a different type, they will still be present even if the user has selected the replace option. This is very confusing for a user (like me) until (s)he understands that OsmAnd is not doing a full restore but a restore-by-type (which is a neat feature btw).

### Describe the solution you'd like

If a user has selected to restore all favourites and is apparently trying to do a full restore, the app should ask for potentially three options:
* add the waypoints instead of replacing existing ones (if there are waypoints already present in the app with the same types)
* replace the waypoints for each selected type (if there are waypoints already present in the app with the same types)
* replace all waypoints (if there are any waypoints in the app)

### Describe alternatives you've considered

In OsmAnd 4.0.7 the workaround to do a full restore is:
* Go to My Places / Favourites
* Tap on the trashcan
* Select each of the existing waypoint types
* Tap on the trashcan
* Go to backup/restore and restore a previous set

This is quite cumbersome and is only required if in the app there are waypoint types that are not in the backup set. But there is no easy way to find out.

**Comment by vshcherb** [comment]
Yes it's part of discussion here or could be for following questions - https://github.com/osmandapp/OsmAnd/discussions/12807?converting=1.

It's done on purpose to avoid deleting accidentally important data such as favorites i.e. if you replace "external file" with 1 favorites, it will be modified or added but other points wont be deleted. 

Even though obviously it's possible to delete but we don't have local backup / restore mechanism for favorites and that's why it's probably not a good idea to implement like that.
