### ISSUE TITLE
Geocoding of locality-specific "plus codes" is broken when they contain a suffix

### ISSUE THREAD

**Issue by Friptick** [osmandapp/OsmAnd#12809]
### Description

When Open Location Codes (AKA "short codes", "plus codes") are **abbreviated to be locality-specific with a text suffix**, that text suffix breaks Osmand's geocoding. This format is an allowed part of the specification and very commonly found in business addresses on the web. 

`AB1C+A2` > WORKS when you are nearby! :)

`AB1C+A2, Salzburg, Austria`> DOES NOT WORK, **even when you are nearby**. :( But this is how they are often output.

The extra location data ("Salzburg, Austria") is needed only if current location is outside that region. Ideally Osmand would decode the string. In #5735 @vshcherb says it this is a "known issue". Okay, no problem.

**QUICK FIX: since Osmand cannot geocode the suffix, it should just ignore it.**  At present, this text string breaks the geocoding completely. You need to manually delete the text string, then the code will work for any local address. This is laborious, and most users who paste the code for a nearby business will not know about the trick. 

Open Location Codes are an Apache-license open standard. Some state authorities now accept them as official. It would be very helpful if Osmand could understand them wherever possible.

### Your Environment
OsmAnd Version: latest
Android 8

**Comment by tradavyvy** [comment]
See also #11628

**Comment by nnngrach** [comment]
> ### Description
> When Open Location Codes (AKA "short codes", "plus codes") are **abbreviated to be locality-specific with a text suffix**, that text suffix breaks Osmand's geocoding. This format is an allowed part of the specification and very commonly found in business addresses on the web.
> 
> `AB1C+A2` > WORKS when you are nearby! :)
> 
> `AB1C+A2, Salzburg, Austria`> DOES NOT WORK, **even when you are nearby**. :( But this is how they are often output.
> 
> The extra location data ("Salzburg, Austria") is needed only if current location is outside that region. Ideally Osmand would decode the string. In #5735 @vshcherb says it this is a "known issue". Okay, no problem.
> 
> **QUICK FIX: since Osmand cannot geocode the suffix, it should just ignore it.** At present, this text string breaks the geocoding completely. You need to manually delete the text string, then the code will work for any local address. This is laborious, and most users who paste the code for a nearby business will not know about the trick.
> 
> Open Location Codes are an Apache-license open standard. Some state authorities now accept them as official. It would be very helpful if Osmand could understand them wherever possible.
> 
> ### Your Environment
> OsmAnd Version: latest Android 8

Hello. Can you tell me where you found this code?  AB1C+A2 ? It does not look like a correct OLC-code.

As far as I know GoogleOLC does not allow the use of letters “A” and “B” at all.  Only letters from [this list](https://github.com/google/open-location-code/blob/main/docs/specification.md):
23456789CFGHJMPQRVWX

GoogleMap also does not find anything when searching for this code.
https://www.google.com/maps/search/AB1C%2BA2/@30.1798348,4.5050524,4z

Is this exactly the correct code of the real place, which should  be found through search? Or are these just made-up letters for an example of the non-working code?

**Comment by Friptick** [comment]
Hi @nnngrach, thanks for taking the time.

Yes, the code is made up, I thought it would be obvious but apparently not!

It was to illustrate the schema, but it seems I got that a bit wrong too. Here's a quick search for Salzburg Opera House:
>R23V+52 Salzburg, Austria

This is the issue. Google Maps spits out these codes in format "XXXX+XX Town, Country". But the text bit (for example, "Salzburg, Austria") breaks Osmand's decoding.

Without any text, _and if your device is already geolocated in the town_, Osmand interprets the code fine.

So, as I said, the proper solution is to geodecode the text string. Then the code will work for anywhere in the world. But a quick fix would be to assume the device is nearby. Then at least it will work there.

Let me know if anything needs clarifying.

**Comment by tradavyvy** [comment]
I would much prefer osmand to understand the code includong suffix even when I am not near the location. Because I would like to use them to plan ahead for places that are interesting to visit on my travels.
See also #11628

**Comment by Friptick** [comment]
> I would much prefer osmand to understand the code includong suffix

Agree completely, this is the proper solution.

Specs for short codes [here](https://github.com/google/open-location-code/blob/main/docs/specification.md). It says:
>Short codes are used relative to a reference location. They allow the code part to be shorter, easier to use and easier to remember.

So the "Salzburg, Austria" string seems to be known as the "reference location".

Understanding it is not one of the _obligatory_ "library implementation requirements". But it is one of the optional ("can provide") requirements:
> a method to recover a full Open Location Code from a short code and a reference location.

It would be so SO useful, given the ubiquity of these Google-generated codes, particularly for business locations.

Thanks for your work.

**Comment by tradavyvy** [comment]
This: 

https://github.com/google/open-location-code/wiki/Supporting-plus-codes-in-your-app

Talks about coding and reverse coding of short +codes with place names in it.
It apperantly requiers an online converting service, so not ideal for 'off-line-hero' osmand, but maybe better then not being able to read these codes at all.

**Comment by nnngrach** [comment]
> Yes, the code is made up

Thank you for answer. That's just what I thought, but I had to check.

> R23V+52 Salzburg, Austria

This task has already been done for ios. The search finds this address. I hope it will work on android soon.

**Comment by ivanPyrohivskyi** [comment]
Related to https://github.com/osmandapp/OsmAnd-Issues/issues/89

**Comment by Friptick** [comment]
> Related to https://github.com/osmandapp/OsmAnd-Issues/issues/89

404

**Comment by alisa911** [comment]
ios https://github.com/osmandapp/OsmAnd-iOS/pull/1956

**Comment by alisa911** [comment]
tests https://github.com/osmandapp/OsmAnd-resources/pull/857

**Comment by Friptick** [comment]
Lots of movement on this, so exciting! :smile: Thanks for your work :heart:

**Comment by alisa911** [comment]
java https://github.com/osmandapp/OsmAnd/pull/15740
test https://github.com/osmandapp/OsmAnd-resources/pull/904
<img width="378" alt="Screenshot 2022-11-16 at 11 49 42" src="https://user-images.githubusercontent.com/38911173/202163499-fecdacf3-7f8a-452c-96b5-c06e9490acce.png">
<img width="382" alt="Screenshot 2022-11-16 at 11 50 12" src="https://user-images.githubusercontent.com/38911173/202163502-6519df59-b2b2-4f31-9834-c39b8e633374.png">
<img width="369" alt="Screenshot 2022-11-16 at 12 55 03" src="https://user-images.githubusercontent.com/38911173/202163508-5e90f8bc-04ee-4b90-9efd-14344e703c54.png">
<img width="356" alt="Screenshot 2022-11-16 at 12 55 23" src="https://user-images.githubusercontent.com/38911173/202163511-ebc2d8ec-5cfa-41bc-8d69-0220fb185328.png">

**Comment by Friptick** [comment]
:partying_face: Looks great, can't wait for it to come to F-Droid. Great work. :+1:

**Comment by Friptick** [comment]
Confirming that this works great! Thanks! Don't forget to close #11628

**Comment by Friptick** [comment]
Confirming that this works great! Thanks! Don't forget to close #11628

**Comment by tradavyvy** [comment]
Please do not close #11628
I wil put a message there to show it still does not work (flawlessly)

**Comment by Friptick** [comment]
@tradavyvy The problem you raise is not going to be fixed by Osmand developers. All they did was plug in a geocoding library, probably Nominatim or whatever OSM uses. So if there are places lacking, that's for others to fix.

As you can see, OSM does not know about Ban Tieng:

https://www.openstreetmap.org/search?query=ban%20tieng

Googling it comes up with nothing, and Wikipedia needs the spelling "Ban Thieng" to find a tiny stub article. To be fair, that is about the hardest imaginable short code, being an obscure village in a poorly mapped country, with transliteration involved too.

The fix they have implemented is alas the best we are going to get and (as the screenshots above show) it's mostly good enough.
