### ISSUE TITLE
Rendering poor in relation of Rio de la Plata.

### ISSUE THREAD

**Issue by franco999** [osmandapp/Osmand#1280]
-- Google Translate --
I could not find a report about it here, so ...
In various zoom levels, while the Rio de la Plata is in the map view, Buenos Aires, Uruguay Area are like Venice. Sometimes not showing the water. This error is having other people in the area.

Although the maps of Argentina and Uruguay they are downloaded, to have the complete relation of the Rio de la Plata, follows the same error.

![1](https://cloud.githubusercontent.com/assets/12088580/7861707/26072c74-0528-11e5-84d4-266e9d1cd28c.png) ![2](https://cloud.githubusercontent.com/assets/12088580/7861708/261b957e-0528-11e5-886e-257aa243d458.png)
![3](https://cloud.githubusercontent.com/assets/12088580/7861711/26ab4fde-0528-11e5-82ab-7281c2885e70.png) ![4](https://cloud.githubusercontent.com/assets/12088580/7861710/268e61bc-0528-11e5-8729-553db2f51a94.png)
![5](https://cloud.githubusercontent.com/assets/12088580/7861709/2634cefe-0528-11e5-9422-464a7c7a7d0b.png)

**Comment by Norbert80** [comment]
@vshcherb this is a duplicate of Google code issue 2497. It looks like you have forgotten to move it to github.

Please move issue 2497 to github and set this one as duplicate.

**Comment by vshcherb** [comment]
There are lots of issues with coastlines, we now focused only on major ones. This issue looks special cause the whole city is under water. We need to investigate the reason. The issue might be related that  city has 'water' not 'coastline' next to it, so there might be something related to this.

**Comment by vshcherb** [comment]
This file looks like need to be regenerated https://github.com/osmandapp/OsmAnd-tools/blob/master/OsmAndMapCreator/src/net/osmand/data/preparation/oceantiles_12.dat.bz2

It contains ocean/land tiles of 12 zoom and it is not synchronized with changed coastline (which doesn't come to Buenos Aeros) any more.

**Comment by franco999** [comment]
I think that is already fixed in the latest update of the base map world. Thanks!
