### ISSUE TITLE
Add option to display or hide turns arrow in the Route line settings

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#12811]
<img src="https://user-images.githubusercontent.com/80623554/133991508-5330e8b9-8049-4f38-b312-a285908955b6.png"  width="300" height="auto"/>

**Comment by dmpr0** [comment]
# ToDo
- [ ]  Add "Turn arrows" group to control arrows visibility on the route line.

**Comment by mmh-dev** [comment]
https://github.com/osmandapp/OsmAnd/pull/13306

**Comment by mmh-dev** [comment]
https://github.com/osmandapp/OsmAnd/pull/13350
