### ISSUE TITLE
slightTurn and sharpTurn penalties are switched around

### ISSUE THREAD

**Issue by Zero3** [osmandapp/OsmAnd#12816]
### Description

I am currently working on a custom `routing.xml`, and noticed that the `slightTurn` and `sharpTurn` penalties are switched around. *Sharp* turns (including u-turns) use the `slightTurn` penalty, while *slight* turns use the `sharpTurn` penalty.

This causes the routing algorithm to prefer routes with sharper turns, despite the penalty settings intended to prioritize the opposite. In some complex intersections modelled using multiple OSM ways, it will even replace a standard slight right turn with an illegal and dangerous mid-intersection right u-turn, unless there are turn restrictions to prevent this.

### How to reproduce?

Set `slightTurn` to a very high value (for example 100 seconds) and `sharpTurn` to a very low value (for example 10 seconds) in `routing.xml`, and test various routes that contains just a single turn. The toast message that shows the calculated route time (might require the developer plugin to be enabled?) will reveal the problem.

### Your Environment
OsmAnd Version: 4.0.7

**Comment by vshcherb** [comment]
hm... interesting, needs to be double checked.

**Comment by alisa911** [comment]
@Zero3 Hello. I couldn't reproduces the bug. Please share real example with this case.
My example
<img width="725" alt="Screenshot 2021-09-26 at 17 58 45" src="https://user-images.githubusercontent.com/38911173/134818171-7d0fdf0b-b242-4bb8-8932-c8308508b452.png">
This turn has right penalty, when i change values in routing.xml

**Comment by Zero3** [comment]
@alisa911 Hmm. I cannot reproduce it in the latest version of OsmAnd either. Maybe it was fixed, or maybe I made a mistake. I will close this issue for now, and let you know if I see it again. Thanks for checking it out.
