### ISSUE TITLE
Disappearing widgeds for plugins Trip Recording and Parking Position

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#12828]
### Description
Suddenly Trip recording plugin in the upper right corner disappeared and
also the option for configuring in Configure Screen.

This includes
I can't start or stop recording
i don't see recorded distance.

Same problem (plugin in the upper right corner disappeared ) with Parking Pluging.

### How to reproduce?
I can reactivate (better "revisualize") plugins with 
opening plugins, DEactivate Trip recording plugin, then activate plugin again, then go back to map screen. Now the plugin is visible again.
If i switch to a different app and back, and observe the Trip Tecording plugin, i see directly after osmand is back in front that Trip recoeding is disappearing.
Same with Parking Pos.

Problem is since a few days, but NOT with OsmAnd~ 4.1.0#32706m,  2021-09-12

### Your Environment
OsmAnd Version: 4.1.0#32752m 2021-09-21 
Android: 8.0
Device model: Samsung S7

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/commit/e0531a1cef59c70119064911df4bae37bc1bb592

**Comment by chrisaww** [comment]
I also have seen this bug on my Galaxy following the last update. BUT the work around does not work for me!!!!
