### ISSUE TITLE
POI search does not lookup building names

### ISSUE THREAD

**Issue by chtfn** [osmandapp/Osmand#1282]
It would be great to be able to search for building names too when searching for a POI. Often, apartment buildings have a building name, which could be used instead of looking for an address (especially for areas that don't have proper address data yet).
Another case is for institutions/businesses/organisations/entities... that give their name to a building but don't have a specific key+value defined for their activities.

**Comment by vshcherb** [comment]
This is not going to be fixed soon, but we are working on new search combining POI and address search. We want to keep POI name index as small as possible so it will be quick to search well-known amenities.
