### ISSUE TITLE
topo_bare_rock2 shader problem

### ISSUE THREAD

**Issue by Hades1503** [osmandapp/OsmAnd#12820]
### Description

Hello,

I am creating a render for hiking and I am having problems with the shader topo_bare_rock2 and topo_bare_rocknight.

on iphone the rendering is correct but on android the shader is ignored and is not rendered.

the concerned shader is topo_bare_rock2 and topo_bare_rocknight

iOS 
![image](https://user-images.githubusercontent.com/79785663/134141084-d5505f50-2399-4dde-9335-5ea701b1b00a.jpeg)
Androïd 
![image](https://user-images.githubusercontent.com/79785663/134140192-d85979fd-2a90-450e-bd72-4c6eff6b8919.jpeg)![image](https://user-images.githubusercontent.com/79785663/134140206-69f47659-0509-4141-9393-3d6f551c5a3c.jpeg)
why does it not work on android?

### Your Environment
OsmAnd Version: 4.0.6
iOS version: 14.7.1
Device model:iPhone 11pro

**Maps used (offline):**

**Comment by Hades1503** [comment]
This shader

https://github.com/osmandapp/OsmAnd-resources/commit/e9cadf4171867415042cd2c5a400a1cfd7208b68?short_path=74c39d7#diff-74c39d7d44e7a1f1f695d9e323000703b23c23bfb884f0944d2bdefb896cc91b

**Comment by xmd5a2** [comment]
Please provide a portion of your rendering style. These shaders are working without any issue in topo style.

**Comment by Hades1503** [comment]
F-droid OsmAnd 3.9.10
![image](https://user-images.githubusercontent.com/79785663/134650269-09ce06e5-0bec-4ad0-a1f3-bf19ef4baf2c.png)

Playstore OsmAnd 4.0.7
![image](https://user-images.githubusercontent.com/79785663/134650406-e52708af-7637-4f6e-a616-333da1e71e67.png)

this rendering is not finished, I am still working on it

https://www.dropbox.com/s/5m3eq3y4ord046d/Epsilon.render.xml?dl=0

**Comment by Hades1503** [comment]
> Please provide a portion of your rendering style. These shaders are working without any issue in topo style.

F-droid OsmAnd 3.9.10
![image](https://user-images.githubusercontent.com/79785663/134650269-09ce06e5-0bec-4ad0-a1f3-bf19ef4baf2c.png)

Playstore OsmAnd 4.0.7
![image](https://user-images.githubusercontent.com/79785663/134650406-e52708af-7637-4f6e-a616-333da1e71e67.png)

this rendering is not finished, I am still working on it

https://www.dropbox.com/s/5m3eq3y4ord046d/Epsilon.render.xml?dl=0

**Comment by xmd5a2** [comment]
I can't reproduce issue using your style
![Screenshot_2021-09-27_09-56-58](https://user-images.githubusercontent.com/5829014/134859327-fb5b99be-1250-4974-b9e8-fec26670bb15.png)

**Comment by Hades1503** [comment]
the topo_bare_rock2 shader works on android? How did you do ?

until the people who use osmand (playstore and F-droid) give me the info that the shader is not working.

on iphone it works very well.

**Comment by xmd5a2** [comment]
Now this is fixed for sure. Issue was in shader size. 72 px works normally in OsmAndMapCreator but not on Android. I've reduced size to 64 px and now it works. Issue affected topo and offroad styles too.
