### ISSUE TITLE
Next turn indicator does not change colour in osmand v2

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#1283]
https://groups.google.com/forum/#!topic/osmand/K2UcaQpyHJU

Confirmed regression with 2.1.0 nightly of today.

**Comment by sonora** [comment]
Victor, from what I see it is not just the secondary arrows, also the primary arrow color does not always seem to update. When driving on motorways, I frequently seem to see the gray color remaining even when approaching the indicated exit.  Not sure yet how to 100% re-produce, it seems a bit sporadic, but frequent. - Best, Hardy

**Comment by vshcherb** [comment]
Fixed, but requires testing.

**Comment by sonora** [comment]
Confirmed working, thanks, Victor!
