### ISSUE TITLE
Track recording pauses and resumes by itself while screen is off and cellphone left alone

### ISSUE THREAD

**Issue by speleoluc** [osmandapp/OsmAnd#12830]
Running Osmand 4.0.7 on my Android 8 cellphone, I recorded today's paddle, leaving my phone in a waterproof pouch on deck, face down, screen off and untouched all the time. Battery is still at 40% and power save is disabled. I caught most of the ride, except for a few km in between two sections, whereby Osmand+ restarted recording. See annotated screenshot and GPX file (txt extension added for upload...)
.
[2021-09-21_09-59_Tue.gpx.txt](https://github.com/osmandapp/OsmAnd/files/7206235/2021-09-21_09-59_Tue.gpx.txt)

![Screenshot_20210921-165152_OsmAnd+](https://user-images.githubusercontent.com/57163823/134247213-703297f2-11ff-4148-a6a7-29e7556e92bc.jpg)

**Comment by vshcherb** [comment]
I think it's duplicate to https://github.com/osmandapp/OsmAnd-Issues/issues/766. Should be fixed in 4.0.8

**Comment by speleoluc** [comment]
Le mer. 22 sept. 2021 à 05:19, Hardy ***@***.***> a écrit :
>
> @speleoluc I had been asking because we have reports of tracks not immediately becoming fully visible.
>
> Looking at your track and how it contains different segments, it seems likely that @vshcherb is right, because the missing portion seems to co-incide start at a turning point on your trip where maybe you used the pausing?

I never touched my phone during the paddle. I only stopped the
recording once aground.

> Other things to check include:
>
> Double-check power saving, unfortunately these are very hardware dependent and ther is no sinle best way to configure. Please read ***@***.***/osmand/troubleshooting/track-recording-issues#check-your-configuration

I have already checked that long ago after experiencing and reporting
such pausing problems.

> Check the settings of your trip recording plugin and make sure no filters are selected like minimum accuracy etc.

These are the default values, i.e. no minimal displacement and a 50m precision.

Regarding issue 766, this is what I find (nothing in milestones)

https://github.com/osmandapp/OsmAnd/issues/766


-- 
Luc Le Blanc

**Comment by martinstingl** [comment]
> I think it's duplicate to https://github.com/osmandapp/OsmAnd-Issues/issues/766. Should be fixed in 4.0.8
The link does not work.
