### ISSUE TITLE
Collecting traffic data - in a proper way as opposed to Google :)

### ISSUE THREAD

**Issue by KlavsKlavsen** [osmandapp/OsmAnd#12843]
# 🚀 feature request

### Description

Google maps has ONE big benefit over osmand - which is that it forcefully steals every Android/maps users location data - and misuses for commercials - while also enabling to know where there's traffic jams, slowing speed.

I believe this could be reached by an Open Source solution - which hopefully could then be adapted by ANY routing application (and hopefully EU etc. would consider disallowing the current Google approach - which AFAIK actually IS a breach of the GDPR).

While hoping for the law to catch up to the situation, I would really like if a proper solution was put in place to show it SHOULD be done.

I'm thinking osmand should time "a segment" of travel (between signals or turns f.ex.) - and compare to its "calculated cost" - this can be done offline.. and then it could simply report something identifying the route-segment (the route-segments should be split in such a way so all users travelling same stretch of road will calculate same segment) - and the time it actually took and a percentage of how much "off" from expected time, it was (or only the percentage).

This WOULD require some service running to store it - and I'm hoping openstreetmaps would see the use for such a service - as that would enable ANY client to pull data from openstreetmap about "expected variation" - which could simply conclude that from the "timed route-segments" it got - for each segment.. So client would submit a list of "route-segments" in the route its calculating - and get back the "expected variations in percent - if any".
These variations could be stored as simple files - so the clients could simply "figure out the path to GET" (which would mean timerange is part of path) - and thus data could be served as simple files (cheapest performance wise).

This would also help detect anomalies in osmand route calculations and could possibly be used to detect other anomalies - without compromising anonymity.

WDYT ?

**Comment by scaidermern** [comment]
#6878 already has a few ideas for collecting traffic information. Maybe we should continue to collect ideas in this other issue instead of starting a new discussion.

**Comment by KlavsKlavsen** [comment]
Moved my ideas/thoughts to #6878
