### ISSUE TITLE
My position shows in the middle of the screen instead of at the bottom

### ISSUE THREAD

**Issue by joostbijl** [osmandapp/OsmAnd#12848]
When navigating, my position shows in the middle of the screen rather than on the bottom. I'm using the osmand map layout, offline maps, and the direction of the map is set to the movement direction. I'm using osmand v4.0.8. On a previous 4.0 version of osmand, my position was shown at the bottom as I expected.

I think it's a bug. But of course I'm willing to clarify or to take additional steps. 
![Uploading IMG-20210924-WA0001.jpeg…]()

**Comment by vshcherb** [comment]
Please attach the cscreenshot again and please double check the setting Configure Map - Display Position in Center

**Comment by joostbijl** [comment]
I could not find the setting "Display position in center". I did however reset the 'driving' profile to defaults and now my position is at the bottom again. No steps to reproduce, so case closed for now.
