### ISSUE TITLE
Routing ignores motor_vehicle:forward tag

### ISSUE THREAD

**Issue by call-me-matt** [osmandapp/OsmAnd#12857]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

car

### Actual and expected routes

from: 53.55584, 10.02556
to: 53.55640, 10.02854

The following route is for firetrucks only and tagged with `motor_vehicle:forward=no`:
https://www.openstreetmap.org/way/15090712

When navigating, this should be considered and circumnavigated like Graphhopper does.

![osmand](https://user-images.githubusercontent.com/34400929/134785079-db7c30b9-7935-4a2e-b6ee-711545e4ba1d.png)

![graphhopper](https://user-images.githubusercontent.com/34400929/134785083-17263776-ea7f-415a-80ea-9024fc30ed42.png)

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
no

## 🌍 Your Environment

**OsmAnd Version:**
4.0.7

<pre><code>

</code></pre>

**Device and Android/iOS version:**

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**

**Comment by xmd5a2** [comment]
Fixed by https://github.com/osmandapp/OsmAnd-resources/commit/27b094a05ee7289800ae0b0b5daa032b0d36b04a
