### ISSUE TITLE
no speed limit

### ISSUE THREAD

**Issue by toas-koas** [osmandapp/OsmAnd#12851]
In FDroid version 3.9.10, I no longer see a speed limit during navigation.

**Comment by vshcherb** [comment]
We have already 4.0 release, please double check it and double check that you have widgets enabled.

**Comment by vshcherb** [comment]
sounds strange, is it related to the road you travel?

**Comment by toas-koas** [comment]
I drive in Germany in Bavaria. The problem still occurs with me and a friend. Maybe you can just simulate a navigation in Bavaria to be able to recreate this. Currently I use version 4.0.9

**Comment by pebogufi** [comment]
Currently tested within city of Memmingen, (Schwaben) with simulation. 
OsmAnd~ 4.1.0#33282m, veröffentlicht: 2021-12-23
device Samsung tablet S5e, Android 10.
Everything works ok, as expected. 
Speed limit is shown, also with visual and vocal warning if exceeded.

**Comment by toas-koas** [comment]
I have now completely reset the app and downloaded the map again. Now the speed limit display also works.

**Comment by toas-koas** [comment]
Now I have compared everything again and found that this is due to the online route planner. If this is active, then the speed limit is no longer displayed. With the offline route planner, the speed limit works.

**Comment by scaidermern** [comment]
I think this is expected behavior. Only the native routing engine has access to this data.

@victorosm However, maybe there should be an option to attach the route from online route planers to the road? This way OsmAnd should be able to give speed limit and lane information.

**Comment by vshcherb** [comment]
Yes we have options for online route planners, we've just introduced it for online GPX router at least. If you can create an issue we could add it to other profiles as well
