### ISSUE TITLE
GPX Route through mapless area

### ISSUE THREAD

**Issue by mdewilde** [osmandapp/Osmand#1286]
This is better qualified as a feature request and/or suggestion.
I loaded a GPX with a bicycle track. The route included some parts in Belgium and France, but I had only downloaded the map for Belgium.
Navigating through the French parts of the route was tricky, as there was no backing map to instruct the turn-by-turn navigation.
I was thinking it might be a good idea to include a warning or prompt with a notice that a map is missing in this case.
Anyway, thanks for the app, it is truly wonderful.

**Comment by sonora** [comment]
I would say if you live in or travel to an area in the vicinity of borders, we have plenty of ways now for you to check in OsmAnd that you have all the maps of the area, hence I am suggesting we close this.
