### ISSUE TITLE
Support osf.zip, obf.zip, gpx.zip

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#12863]
Allow to import osf.zip, obf.zip, gpx.zip, please double check that we don't catch all zip files.

**Comment by Chumva** [comment]
This should be added here https://github.com/osmandapp/OsmAnd/pull/12930

**Comment by dmpr0** [comment]
Tested file managers:
Google File Manager, works only using "Open With" and if access "Download" folder thru Internal memory > Downloads.
