### ISSUE TITLE
Flooding in Saint Ignace

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#12879]
### How to reproduce?
45.86862° N, 84.72783° W
![image](https://user-images.githubusercontent.com/80623554/135067906-5f4ba1ba-1f29-40bd-b06c-cca84092d0e0.png)
Appear from the zoom level 8

### Your Environment
OsmAnd Version: OsmAnd 4.0.8
Map update: from 01.09

**Comment by ivanPyrohivskyi** [comment]
Will be fix in the new map (October 2021)
Fixed in this changes https://www.openstreetmap.org/way/953118901
![Screenshot_1633094674](https://user-images.githubusercontent.com/1040293/135627790-713149fc-b9ec-4c0a-8787-cedf9313c2ad.png)
