### ISSUE TITLE
Crossings of bridges

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/Osmand#1287]
crossings of bridges in OsmAnd+ looks strange.
OSM online render this crossing much more better.
Highways have gray lines on left and right and on crossing they not cutting the way.

on bridges the thicker black lines cut the way and this look bad:

![screenshot_2015-05-31-11-09-20](https://cloud.githubusercontent.com/assets/9936160/7901670/31553c7e-0794-11e5-8e70-eadebe341f29.png)

**Comment by vshcherb** [comment]
This is a known issue and have no possible solution for now
