### ISSUE TITLE
Translation Navigation dutch version

### ISSUE THREAD

**Issue by PMURAV** [osmandapp/OsmAnd#12889]
# 🚀 feature request

### Description
Translation to dutch is not allways correct.
For example, were it reads "enigzins rechts aanhouden" it should read "rechts aanhouden"

### Describe the solution you'd like

I can help out regarding translating if needed.

### Describe alternatives you've considered

Nope

**Comment by vshcherb** [comment]
Do you mean TTS voice for navigation?

**Comment by PMURAV** [comment]
Nope, I mean the visual routing informatie ie which turn next etcetera.

Op wo 29 sep. 2021 om 17:21 schreef vshcherb ***@***.***>

**Comment by PMURAV** [comment]
See this screen, it happens when you take an exit.
![afbeelding](https://user-images.githubusercontent.com/91596555/140043132-0a2d46d2-6c81-4489-8012-1f1d2abc289a.png)

**Comment by vshcherb** [comment]
Investigating doesn't look like standard OsmAnd
