### ISSUE TITLE
Highways can be preferred and avoided at the same time

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#1288]
In OsmAnd 2 there are check boxes to avoid and prefer highways. Both can be checked at the same time.

That's irritating.

Solution: Checking one of these check boxes forces uncheck of the other one.
Better alternative: Tri-State selection for highways in one gui element: use - prefer - avoid.

**Comment by vshcherb** [comment]
Fixed (prefer_motorway removed)
