### ISSUE TITLE
Use smarter route recalculation strategy

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#1289]
OsmAnd offline routing: Our current strategy of re-calculating only the first 20 km of a route in case you leave a calculated route (miss a turn etc.) has a major pitfall, imagine this:

There is a big lake, swamp, or mountain range. Your destination is pretty much right behind it,  so you have only either the left road around it, or the right road around the obstacle.

Say OsmAnd routes the left road around it, but for some reason (accidentally or on purpose) you take the right road. OsmAnd would continuously route you back onto the left road (which could eventually be a huge detour of 100km), even if you are almost at your destination having taken the right road.

Looks like we need some sort of periodic "sanity check" where the overall route is _completely_ re-calculated from scratch. I guess the best is we trigger this if a route had to _repeatedly_ be recalculated (in the case described there would be pretty much continuous re-calculation). Alternative strategies could be we limit the number of partial re-calculations not absolutely but  per time interval.

**Comment by Inyaheyukan** [comment]
Is this the cause for the following massive routing error?
I was driving from Berlin to C25 Naturcampingplatz am Mössensee (http://www.openstreetmap.org/way/35981763) on 20.5.2015.
I chose a different route than osmand from Wittstock. My route: Wittstock - Babitz - Schweinrich - Alt Lutterow - Flecken Zechlin - Luhme - Diemitz -Fleether Mühle - Fleeth - C25 Naturcampingplatz am Mössensee

The route was recalculated often but always returns to the highway A19. Even when I was standing right next to the target.

My settings in osmand are: fastest route, offline routing, offline maps.
My smartphone: Archos titanium 40 Android 4.2.2
![screenshot_2015-05-20-18-14-12](https://cloud.githubusercontent.com/assets/4369755/8022159/6b956752-0cc0-11e5-95a4-3cfff3c63e13.png)
![screenshot_2015-05-20-18-28-06](https://cloud.githubusercontent.com/assets/4369755/8022160/6bb9cb4c-0cc0-11e5-9469-a1390be912b7.png)
![screenshot_2015-05-20-18-31-10](https://cloud.githubusercontent.com/assets/4369755/8022161/6bd6920e-0cc0-11e5-9313-c554d00ae0a6.png)
![screenshot_2015-05-20-18-31-29](https://cloud.githubusercontent.com/assets/4369755/8022163/6bd915b0-0cc0-11e5-94ea-272f665f8b80.png)
![screenshot_2015-05-20-18-33-42](https://cloud.githubusercontent.com/assets/4369755/8022169/6c184410-0cc0-11e5-8aee-3fa0dfcd7c5c.png)
![screenshot_2015-05-20-18-34-04](https://cloud.githubusercontent.com/assets/4369755/8022162/6bd68976-0cc0-11e5-8d0a-bf256fda3689.png)
![screenshot_2015-05-20-18-35-57](https://cloud.githubusercontent.com/assets/4369755/8022164/6bdf944e-0cc0-11e5-9419-954a5dbff017.png)
The routes are crossing!
![screenshot_2015-05-20-18-36-20](https://cloud.githubusercontent.com/assets/4369755/8022165/6bdff0f6-0cc0-11e5-899a-b932d05ba289.png)
![screenshot_2015-05-20-18-40-15](https://cloud.githubusercontent.com/assets/4369755/8022167/6beb711a-0cc0-11e5-8dfb-fea2d2a024ac.png)
![screenshot_2015-05-20-18-40-45](https://cloud.githubusercontent.com/assets/4369755/8022168/6bec1bf6-0cc0-11e5-8095-cf04250f4a51.png)
![screenshot_2015-05-20-18-48-35](https://cloud.githubusercontent.com/assets/4369755/8022166/6be9e9b2-0cc0-11e5-895c-35d913378bf5.png)
101km to the target!

**Comment by sonora** [comment]
More findings: This issue occurs much more commonly than I first thought: Example is leaving a big city for a long-distance destination. The city has a big motorway ring around it, some 20km out. OsmAnd will initially plot a route from the city center to one point on the motorway ring. If you leave the city in a different direction, OsmAnd will continue to point you back to that initial point on the motorway ring, even if it is totally off your long-distance direction.

I think we urgently need to introduce a counter, not allowing more than say 3 partial route-recalculations before a full new route is plotted.

**Comment by vshcherb** [comment]
Please test it for now there are 2 constants : 3 times and in 2 minutes interval

**Comment by sonora** [comment]
Ok, from my tests I think I can confirm that this works now, good job!
