### ISSUE TITLE
OpenGL: Rendering long Persian names

### ISSUE THREAD

**Issue by Mesgary** [osmandapp/OsmAnd#12892]
Rendering long Persian names which is longer than a line, divided to two line incorrectly. For example the "مرکز تربیت معلم نسیبه" should be split to "مرکز تربیت معلم" (first 3 words) and "نسیبه" (last word), while as you see in attached screenshot, it is split in "تربیت معلم نسیبه" (last 3 words) in first line and "مرکز" (first word) in second line.
You can find it under English name "Nasibeh Training Teacher University" with ID=25624946.
Just as a reminder, in RTL languages like Persian, words read and count from the Right to the Left ;)
![photo_2015-12-12_22-21-19](https://cloud.githubusercontent.com/assets/15173479/11785038/e3c872e0-a294-11e5-9e51-5cccaec86369.jpg)

**Comment by nnngrach** [comment]
It looks like this problem has already been fixed on ios.

![2022-04-18 11 10 36](https://user-images.githubusercontent.com/35684515/163778966-97c16ec3-9866-40c8-9d19-37230127e16d.jpg)

![2022-04-18 11 10 30](https://user-images.githubusercontent.com/35684515/163778982-e6cd2ad3-3f17-4e9a-b6ec-02f874c7d2a8.jpg)
