### ISSUE TITLE
Car navigation instructions (iOS) wrong keep left 

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#12893]
## Description:
1. Application show turns in the incorrect places. 
2. The name of the street display in Ukrainian, English languages (in the Configure map menu selected English). 
3. Absent information in the speed limit widget [Not reproducible].
4. In some places display extra route lines [Map issue] .

![image](https://user-images.githubusercontent.com/80623554/135275533-1e8dd8b7-2e1f-4d27-9857-4bf2725c95b7.png)
![image](https://user-images.githubusercontent.com/80623554/135275602-5869470e-3efc-4967-acd6-5b8a1c902891.png)

## How to reproduce:
Create route between points: 
50.40780 30.55166
50.44313 30.43851

**Comment by Wizit38** [comment]
![no need turn slightly left command](https://user-images.githubusercontent.com/92155388/136657980-7435ac93-449a-4f12-a378-cc3628a4a08a.jpg)


Instead of turn slightly left, it would be clearer to say "follow the road(path)

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-core-legacy/pull/49
