### ISSUE TITLE
"ast" locale has duplicated folders in OsmAnd/res

### ISSUE THREAD

**Issue by enolp** [osmandapp/OsmAnd#12913]
### Description
"ast" (Asturian) locale has "values-b+ast" and "values-ast" in "OsmAnd/res", both folders point to the same region and locale, and it is recommended to have a unique "values-ast" folder. However, both folders have different sync dates from Weblate and makes difficult the translation job. Which folder is picked up by the app to show the translations?

"values-b+XXX" format folder was an old way to include ISO 639-2 locales starting Android 5.0, now is not necessary anymore

### How to reproduce?
Seeing the code

### Your Environment
OsmAnd Version: 4.0.7
Android/iOS version: Android 11

**Comment by vshcherb** [comment]
Fixed https://github.com/osmandapp/OsmAnd/commit/3e0c267f2879ffc21a6105d615a3b047f3995242
