### ISSUE TITLE
OSM Plugin Notes / Already closed notes "can not be closed again"

### ISSUE THREAD

**Issue by flohoff** [osmandapp/Osmand#1291]
If a note in the offline storage is getting closed in the OSM DB you cant upload that notes change. It will "silently" fail without a message. 

I worked around by noting the notes ID - reopening the note from the website and then pushing my notes close from the phone.

**Comment by vshcherb** [comment]
You mean if you comment offline an open note, you can't upload if it is already closed

**Comment by flohoff** [comment]
Exactly - I close the note in OSMAnd and before i upload the Note somebody closes the Note on the website. Afterwards i cant upload those notes. It fails without an error and they stay in the to be uploaded osm notes queue.

**Comment by GaidamakUA** [comment]
Good day to you. Can you please explain, how to reproduce this bug step step. Assuming OSM editing plugin is allready enabled.

**Comment by flohoff** [comment]
1. Close a note in OSMAnd 
2. Close the same note via the Openstreetmap.org web frontend
3. Try to upload the closed note via osmand

The upload will silently fail as the note is already closed at the time of the upload.

Flo

**Comment by vshcherb** [comment]
Fixed
