### ISSUE TITLE
Date format in the update list broken

### ISSUE THREAD

**Issue by flohoff** [osmandapp/Osmand#1292]
I have installed

"Germany North Rhine-Westphalia" 794.2 MB 05.02.2015

On "Aktualisierungen" i get offereed

"Germany North Rhine-Westphalia" 472.3 MB 05.23.2015

22 Tage alt.

So Date format is completely broken - it should be 02.05.2015
and 23.05.2015 or better switch to the language/locale agnostic
iso date 2015-05-02 which is always clear.

Flo

**Comment by flohoff** [comment]
Ah - German language HTC One m8 - CM 12.1 - OSMAnd 2.0.4

**Comment by aceman444** [comment]
Sidenote, is the file size really decreased that much or is there a typo?

**Comment by vshcherb** [comment]
Just checked and OsmAnd uses default Android settings to display, please go to Android - Settings - Date & Time and validate your settings.
