### ISSUE TITLE
English TTS voice wants to update every time

### ISSUE THREAD

**Issue by dbolton** [osmandapp/Osmand#1293]
How to get there: 
1. Go to the hamburger Menu > Manage map files
2. Press "Updates"

Expected behavior: Only new files should be listed. 

Actual behavior: "English: TTS voice  07/06/2014  1.0 MB  1 days behind" appears in the update list every time (even though it is a year old). If you select and download it, "English: TTS voice" still appears in the update list. 

![screenshot_2015-05-29-13-37-12](https://cloud.githubusercontent.com/assets/712270/7928421/38f19992-08b5-11e5-881b-34f4ae4fb32f.png)

**Comment by mircozorzo** [comment]
The same for italian.

**Comment by OpenSourceForEver** [comment]
In spanish voice it does not happen. You can update the voice everyday.

Is english tts voice in the list inmediately after you update the voice?

**Comment by dbolton** [comment]
@OpenSourceForEver Yes, if you select and download it, "English: TTS voice" still appears in the update list. Did you mean that in Spanish it *does* happen too (the voice shows as an update everyday even though it hasn't been updated for a long time).

**Comment by OpenSourceForEver** [comment]
Yes, I did. But if I update spanish voice today it doesn't show in updates until tomorrow

**Comment by vshcherb** [comment]
Is it for nightly builds? Could you update it and the tts will be gone from updates?

**Comment by Norbert80** [comment]
Same for german tts with OsmAnd+ 2.1 Play Store release. This is an old bug.

**Comment by OpenSourceForEver** [comment]
I have updated ttsconfigp for spanish voice ten days ago. I use google play release, I have updated tts spanish voice everyday but changes do not appear in ttsconfigp in my device. Is there any problem with tts voice updates? Do I need to install another osmand release?

**Comment by vshcherb** [comment]
Fixed, please test it.

**Comment by dbolton** [comment]
Fix works for me on the nightly build.

**Comment by OpenSourceForEver** [comment]
In google play release I have updated tts spanish voice two hours ago but changes don't appear. I have updated ttsconfig.p in osmandapp/OsmAnd-resources/voice/es 13 days ago. Is it enough?

**Comment by OpenSourceForEver** [comment]
It is ok. I have updated the app on google play. The problem is fixed.
Thank you very much
