### ISSUE TITLE
Notifications of navigation

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#12932]
### Description

Duplicate navigation notifications in the Silent Notifications menu when we click on the Pause button.
(Note: you need to have two apps of OsmAnd. For me: OsmAnd Free and OsmAnd Nightly)

### How to reproduce?

1. Start Navigation for OsmAnd~. 
2. Collapse OsmAnd~. 
3. Look at to Silent notifications menu:
![image](https://user-images.githubusercontent.com/44466116/136026836-f30c5cad-22af-48bb-9120-f1f901b1e087.png)
4. Click on "Pause" button and we see that "OsmAnd free" notifications have appeared too:
![image](https://user-images.githubusercontent.com/44466116/136027382-0327d0e0-1e0d-4f83-abef-47b79a4e55ec.png)
5. Click on "Resume" button for OsmAnd~". We see that Navigation for OsmAnd~ is continued. BUT "OsmAnd Free" starts the calculation process of navigation :)
![image](https://user-images.githubusercontent.com/44466116/136027519-ae851928-1356-489d-98c5-068843418175.png)
6. we finish navigation for OsmAnd~.  We open "OsmAnd free" and receive log file about crash.

### Your Environment

OsmAnd Version: OsmAnd free 4.1.0 and OsmAnd~  4.1.0#32820m, 2021-10-05
Android/iOS version: 11
Device model: s10e

**Comment by vshcherb** [comment]
Probably related to https://github.com/osmandapp/OsmAnd/issues/14406 Excessive notifications are fixed https://github.com/osmandapp/OsmAnd/commit/57ce7f4ee6d2fe6c3e24f92f759561c6e73d0db7
