### ISSUE TITLE
Mapview: Incorrect rendering of texts in Bengali

### ISSUE THREAD

**Issue by frogtile** [osmandapp/OsmAnd#12941]
### Description
In the map view text in Bengali are being rendered incorrectly

### How to reproduce?

Look at a few location, for example,

Location: geo:23.73260,90.38490?z=18
https://osmand.net/go?lat=23.73260&lon=90.38490&z=18

![Screenshot_20211006-205624](https://user-images.githubusercontent.com/87414805/136231348-647ec2c1-ed91-4a16-b562-f4cec2465443.png)

### Your Environment
OsmAnd Version: 4.0.8
Android/iOS version: 10 Go

**Comment by vshcherb** [comment]
Merged to #3096
