### ISSUE TITLE
Setting for rendering the territory of national parks, reserves, etc.

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#12949]
It's necessary to add a parameter for the rendering of national parks, reserves, etc. like it done for "Show low emission zones" 
https://docs.osmand.net/en/main@latest/osmand/map/vector-maps#details

![image](https://user-images.githubusercontent.com/44466116/136401192-0bcf3cf0-73d8-4d68-92e3-cb8098e6a17b.png)

**Comment by tradavyvy** [comment]
I agree.
See #11982
There is an extensive discussion about this subject.
