### ISSUE TITLE
Poi details are not shown when type is multipolygon

### ISSUE THREAD

**Issue by MakiWolf** [osmandapp/OsmAnd#12956]
### Description
Don't show poi details when type is multipolygon, when dirctly open it from map.

### How to reproduce?
Click on an poi when type is multipolygon and open it directly from the map. But when I search for parking and open the same poi from search, details are displayed correctly.

![issue](https://user-images.githubusercontent.com/73300633/136530390-5c091f79-04da-48e6-b327-eb454441c49d.gif)

I used [https://www.openstreetmap.org/relation/8328360](https://www.openstreetmap.org/relation/8328360) for testing

### Your Environment
OsmAnd Version: latest nigthly build from [https://download.osmand.net/latest-night-build/](https://download.osmand.net/latest-night-build/) from 20-Jan-2021 12:56 and version 4.0.7 from fdroid
Android/iOS version: 9
Device model: Note 8

**Comment by Dima-1** [comment]
OsmAnd~ 4.3.0 everything works as expected
<details>
    <summary>Screenshot</summary>
<table style="width:100%">
<tr>
  <td><img src="https://user-images.githubusercontent.com/31807095/196445935-ff143e1f-19aa-40ed-bdcc-9267291d28e0.png" width="350" height="auto"/> </td>
</tr>
</table>
</details>

**Comment by dmpr0** [comment]
Works on Android. 
Didn't work on iOS.
<table style="width:100%">
  <tr>
    <th>POI selected on the map</th>
    <th>POI from the Search</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/197133085-f4802b3d-26fb-4f9e-8927-987322bf6ed7.jpeg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/197133088-b01597dc-2f24-497e-9b89-90d12b763bee.jpeg"  width="300" height="auto"/> </td>
  </tr>
</table>
