### ISSUE TITLE
Track type dotted lines are not the same as OSM Mapnik, confusing

### ISSUE THREAD

**Issue by martenjj** [osmandapp/OsmAnd#12953]
### Description

In the "OsmAnd" style and anything inheriting from it (Desert, Mapnik, Touring view, UniRS) and the "Topo" style, highway=track shows different line styles for each possible track type (grade1 through grade5 and 'undefined').  However, these line styles are not the same as used on openstreetmap.org Mapnik, and are confusing for those who use both maps regularly.

The fundamental difference is that the line styles for grade4 and 'undefined' are interchanged.  On OSM Mapnik the grade4 line is dashed, with smaller dashes than grade3 but larger than grade5;  this gives a steady decrease in line density which parallels the decrease in grade.  Undefined track types are shown with a dash-dot pattern which stands out as unusual.

In OsmAnd this is reversed, with grade4 shown as dash-dot and undefined as a normal dashed line (somewhere between grade2 and grade3):

![osmand-old-Screenshot_20211007-195050_OsmAnd+](https://user-images.githubusercontent.com/10631760/136448341-2f1505dd-313f-4a94-bbe8-7114fb080c01.png)

Suggest that the track type line patterns are made the same - in the Mapnik style at least - for consistency.

### How to reproduce?

A view which shows all track types in one place is centered on 46.88881N 8.39624E as in the screenshot above.  The "." shows the actual position of the track with that grade.

### Your Environment
OsmAnd Version:  4.0.8
Android/iOS version:  Android 11
Device model:  Samsung S10

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
Offline map:  Switzerland Central 1 Sep 2021

**Comment by vshcherb** [comment]
cc @xmd5a2

**Comment by sonora** [comment]
I still think it's a good idea and increases discernability. I have implemented in Touring view https://github.com/osmandapp/OsmAnd-resources/commit/615b7a49384568c87816c4a306497eaf5615f761, and recommend considering to do alike for other renderers.

**Comment by sonora** [comment]
Here are my suggestions to also align:
- default: https://github.com/osmandapp/OsmAnd-resources/pull/745
- topo: https://github.com/osmandapp/OsmAnd-resources/pull/746
