### ISSUE TITLE
No cycleway rendering for "cycleway:left=shared_lane" + "cycleway:right=shared_lane"

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#12950]
The tag combination `cycleway:left=lane` + `cycleway:right=lane` _does_ get rendered (left part of the image, https://www.openstreetmap.org/way/759425300).
The tag combination `cycleway:left=shared_lane` + `cycleway:right=shared_lane` _doesn't_ get rendered (right part of the image, https://www.openstreetmap.org/way/419006566).

![photo_2021-10-07_16-05-13](https://user-images.githubusercontent.com/1040784/136400983-bcfd6d8c-0bf9-4479-a496-90b1913b5857.jpg)

Location: 51.05476/13.73752

**Comment by scaidermern** [comment]
> Currently not possible cause we can't render on one or another side of the road

Well, good to know. However see my example above.  `cycleway:left=lane` + `cycleway:right=lane` does already get rendered, so somehow this is already possible. Especially if left and right have the same value you don't need support for rendering individual sides of the road. So the above case is fixable with the current rendering engine.

**Comment by vshcherb** [comment]
Yes it does
