### ISSUE TITLE
Customise Limits of "Colour By Slope"

### ISSUE THREAD

**Issue by Dollarius** [osmandapp/OsmAnd#12954]
I find the new "colour by slope" feature for routes to be very useful!
However, the colourscale is fixed (by default) to the range -25% and +100%.
While this choice works (reasonably) well for hiking, I find it very limiting for road cycling.
When cycling on the road, I would like to fix the range to something like -10% -> +20%, as paved roads above 20% gradient are very rare.
Also, a gradient of even 2-3% is rather important and it would be nice to see it on the map.

Would it be possible to allow to manually set the range of the colourscale for each route?
Thank you very much for the help!
Giordano

**Comment by tradavyvy** [comment]
I think the same goes for car routes. At least for my (35 year old) motorhome, wich is severely speed-limited on gradients over +10% and simply stalls at +20%.
Davy

**Comment by YoBii** [comment]
I was very happy about this addition but for cycling and driving it is really not that useful in its current state. I don't know about hiking. 
The steepest road in the world has a gradient of 37% so having the color scale go to 100% or even 50% really doesn't make sense. At least in the driving and cycling profile.
IMO a quick fix as in changing the hardcoded values to achieve proper usability of this feature is the preferable solution before thinking about adding new features that require several changes at multiple locations.

**Comment by scaidermern** [comment]
There is a new coloring scheme suggested in #11775 / #12336. It makes slope changes in the lower range more clear. Maybe there is additional room for improvement.

**Comment by letypequividelespoubelles** [comment]
Suggested in #11975 too, but for the whole slope overlay (very usefull for planning ski trip to avoid avalanche). Maybe both could be done at the same time?

**Comment by michaelblyons** [comment]
I think there's a good case for customizations per routing profile. There may be trouble making a useful UI for it on a phone screen, though. 😉 To bring together some of the use cases mentioned:

- Car
- Vehicle with towing/caravan
- Skiing
- Road cycling
- Mountain bike
- Hiking
- Walking 

And different people will have different thresholds for each activity.

**Comment by letypequividelespoubelles** [comment]
>There may be trouble making a useful UI for it on a phone screen, though.

What about UI proposed in #11975 ? I think it's very easy to customize the slope display for each profile with it !

**Comment by michaelblyons** [comment]
> What about UI proposed in https://github.com/osmandapp/OsmAnd/issues/11975 ?

Good question. I don't think it's sufficient. The slope underlay/overlay limits are 0% to 60% (or something like that), where routes with directionality could be -100% to +100% or pretty close.

- You'd need the extra color spectrum to cover more space. For routing, it's currently -25% 🟢 ⚪ 🟡 🟠 🔴 🟣 100%.
- I'm not sure how much color variation you need for negative slopes, but 🟢 to ⚪ seems insufficient. Presumably at least some level of steep downhill needs a "warning" color. Outdoor sports and towing probably all need this. Maybe walking, too.
- The midpoint might also need to be adjustable. This is a skiing thing that I'm less sure about. Does a skier want ⚪ to be 0% or some other baseline like -3%?
- Some activities might like more color compression at the extremes versus a straight expansion of the color spectrum onto 0%-X%. (This is like in your mockup, there is the same distance between 0% and 3% as 3% to 10%.)
- With these considerations, is the small axis of a phone screen enough room to drag the color bars from -100 to +100? Maybe instead text entry for Minimum, (optionally) Midpoint, and Maximum slope would be better, with a preview underneath.

**Comment by Aambro** [comment]
Is there a temporary solution to override default values in xml file?

**Comment by vshcherb** [comment]
@Aambro Unfortunately no :-( It's hardcoded https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd-java/src/main/java/net/osmand/router/RouteColorize.java#L47. Probably it could be free customized or some different styles to select  generated. Not sure if rendering style is a good place for that. GPX itself might be better

**Comment by michaelblyons** [comment]
Jon's point is well-taken. May I suggest this spectrum without white:

- ⚫ 🟣 🔵 🟢 🟡 🟠 🔴 ⚫

Assuming that black is "too steep to use" on both ends, you can still have a symmetrical color spectrum.

**Comment by ferpg81** [comment]
Hi. I came to github to propose a feature like that for a gpx trace on the map, when selecting color by slope. @Jon-Murray explained it perfectly, when you ride a bike on the road, normal values for slopes are < 5%, and when climbing, maybe a 10-20%, that are very hard to do. You will never (or rarely) ride more than that. The effect is that during all your ride, you always see a white colour or maybe a slight yellow... It would be much appreciated if we could adjust colours limiting max and min values, like the screenshots on #11975, and/or having a default values for each profile (hiking, riding, etc.), and the possibility to select different palettes, as @michaelblyons said. Thanks a lot.

**Comment by anastasiia936** [comment]
Please add the ability to make the gradient line transparent so that you can see the street name on the map.

**Comment by michaelblyons** [comment]
In case you are only subscribed to this issue and not #12336, Victor [has indicated](https://github.com/osmandapp/OsmAnd/issues/12336#issuecomment-1500347990) that they're working on this! 🥳

**Comment by vshcherb** [comment]
Probably instead of special UI (which would take quite some time & efforts)  we could use colorization plugin similar to approach here https://github.com/osmandapp/OsmAnd/issues/6636

**Comment by vshcherb** [comment]
Today we've introduced color palette for user defined (https://github.com/osmandapp/OsmAnd-resources/tree/master/color-palette). Task is not complete yet but should be ready to try.
Files from color palette will be available in user folder (for export / import and editing).
For example:
1. slope_default.txt is responsible for colors for Slope Terrain
2. slope_avalanche.txt is responsible for colors for Terrain Avalanche (new item will be added to the list)
3. route_slope_default.txt is responsible for colors for route in slope
4. height_altitude_0_200.txt is a new file which will color Terrain with colors of absolute altitude (so it should be a range of files that could be applicable for different regions) - dynamic scale is not planned yet.

We plan to improve selection for user palettes in settings and create plugins with some predefined palettes. Though we don't plan for now to create editor for the palette itself, probably later

**Comment by vshcherb** [comment]
Now it's possible to update existing palettes using import / export palette (and manually editing txt files). We're going to introduce inline palette editor later in the app
