### ISSUE TITLE
Osmand~ crash with an icon pack installed

### ISSUE THREAD

**Issue by xphnx** [osmandapp/Osmand#1295]
Hi, I'm the manteiner of a Theme for Cyanogenmod. An user [reports an issue](https://gitlab.com/xphnx/onze_cm11_theme/issues/4): "When starting a navigation on OsmAnd, and having Onze CM 11 installed, OsmAnd will crash with the following Java backtrace. This does not happen when Onze is not installed."
<code>Version  OsmAnd~ 2.0.4
30.05.2015 4:12:40
Apk Version : 2.0.4 207
Exception occured in thread Thread[main,5,main] : 
android.app.RemoteServiceException: Bad notification posted from package net.osmand.plus: Couldn't create icon: StatusBarIcon(pkg=net.osmand.plususer=0 id=0x7f0202a4 level=0 visible=true num=0 )</code>

I think this is a common problem with themed icons, when the app is trying to show an icon that is missing(?).

For reference: https://github.com/syncthing/syncthing-android/pull/332

**Comment by vshcherb** [comment]
To check if bgs_icon has a proper size to NotificationCompat smallIcon.

**Comment by xphnx** [comment]
Maybe this could help:
"[Daniel Jäger @DJaeger](https://gitlab.com/xphnx/onze_cm11_theme/issues/4#note_1354913):
OsmAnd~ crashes only when starting navigation, as it then creates a notification.
This only happens, if Icons of Onze/TwelF are applied and not directly on installing.
So it is the same issue than the much others.

I have looked a little bit more on these issues.

It seems to be only required, that the small icon have to be white.
I have seen an working example at Mirakel.

So only is needed to change in the most common situation/for example
```
.setSmallIcon(R.drawable.ic_launcher)
```
to
```
.setSmallIcon(R.drawable.ic_notify)
.setLargeIcon(Helpers.getBitmap(R.drawable.ic_launcher, getBaseContext()))
```
and add a simplified white icon as "ic_notify.png".

Then the simplified white icon is shown in top bar and a full colored icon (same as on launcher and also themed by TwelF/Onze) is shown in opened notification list.

You can see this here:
https://github.com/MirakelX/mirakel-android/blob/master/model/src/de/azapps/mirakel/services/NotificationService.java#L130"
