### ISSUE TITLE
Address search suggestions

### ISSUE THREAD

**Issue by mchapliuk** [osmandapp/Osmand#1296]
1. I really like OsmAnd, but search engine is too simple. I can search address only in the language of the map. For example, I live in Ukraine, and language of the map is Ukrainian, but about 50% citizens speak Russian, and when I want to search city or street, I cannot type some of characters (specified for Ukrainian). It would be great if you upgrade your search engine to search in all names of objects (when I type name of the street in English (for Ukrainian city) - I get results (if target street has additional name in English (name:en=*) ).
Last example: I have been to Israel, and I could not find anything in English, because map gets only Hebrew language.

2. When you seek a city it would be great show additional info in found results (if there are more than one city with that name in your country):
[Rokitne           ][ Search ]
Rokitne (Kievska oblast)
Rokitne (Lvivska oblast)
Rokitne (Rivnenska oblast)

It is just an example

Thank you,
OsmAnd+, 2.0.4
Android 5.1.1

**Comment by vshcherb** [comment]
We have already one option in Configure Map -> Language (for now only name:en is fully supported, but in address search is not supported yet.

**Comment by sonora** [comment]
I guess this is deprecated with the new search interface.
