### ISSUE TITLE
Seamarks Not Displaying Correctly in Boat Profile

### ISSUE THREAD

**Issue by markongh** [osmandapp/OsmAnd#12968]
There are some Seamarks that do not display properly in the OsmAnd Boat Profile.  This problem seems to be with Seamarks that are drawn in OSM as ways (buildings) and not as nodes.  Seamarks in OSM as nodes will display at a much higher zoom level while seamarks stored in OSM as ways will only display when zoomed far in right on top of them.  This can be an issue when trying to navigate using lighthouses or other seamarks and they are not displaying on the map.

I compared the display of the Boat Profile in OsmAnd with the display from [OpenSeaMap](http://map.openseamap.org/) and also compared the data using Overpass with the overpass query below.  Two examples of this issue can be seen with the lighthouses located [here](https://www.openstreetmap.org/#map=19/40.77816/14.08926) and [here](https://www.openstreetmap.org/#map=19/40.77040/14.01690).

`/*
This has been generated by the overpass-turbo wizard.
The original search was:
“seamark:type=light_major or seamark:type=light_minor”
*/
[out:json][timeout:25];
// gather results
(
  // query part for: “"seamark:type"=light_major”
  node["seamark:type"="light_major"]({{bbox}});
  way["seamark:type"="light_major"]({{bbox}});
  relation["seamark:type"="light_major"]({{bbox}});
  // query part for: “"seamark:type"=light_minor”
  node["seamark:type"="light_minor"]({{bbox}});
  way["seamark:type"="light_minor"]({{bbox}});
  relation["seamark:type"="light_minor"]({{bbox}});
);
// print results
out body;
>;
out skel qt;`

### Your Environment
OsmAnd Version: OsmAnd 4.0.8
Android/iOS version: 11
Device model: Samsung A20e

**Maps used (online or offline):**   
Currently using OsmAnd Live updating daily.

**Comment by Dima-1** [comment]
https://github.com/osmandapp/OsmAnd-core-legacy/pull/84
https://github.com/osmandapp/OsmAnd-resources/pull/818
