### ISSUE TITLE
Haptic feedback stops working when application is put to background

### ISSUE THREAD

**Issue by vojtapolasek** [osmandapp/OsmAnd#12969]
### Description

There is a very nice feature which gives you haptic feedback while navigating and you turn away from the route. I use it a lot since I am blind. However, if you leave the application (press home) and then reopen the navigation again, the haptic feedback is not working and I have to cancel the navigation and start it again to get it working. The same happens when you turn the screen off and on again.

### How to reproduce?

- Make sure that the haptic feedback is turned on: settings -> accessibility -> haptic directions
- Start some navigation
- turn around and notice the vibration
- press Home
- open the app again, continue navigation
- turn around and notice that the vibration is not working

### Your Environment
OsmAnd Version: 4.0.8
Android/iOS version: Android 10
Device model: Unihertz titan

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

This happens no matter what maps I use.

**Comment by Zirochkabila** [comment]
> * and notice the vibration

Your case was checked with OsmAnd 4.1.11 and  the vibration notice works both when exiting the application and when turning off/on the screen.
Try updating to a newer version and check your phone settings.
Start the navigation and then turn on the Accessibility plugin.
