### ISSUE TITLE
Add option to change color of the turns arrow in the Route line settings

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#12978]
In some map modes default color become invisible:
![Screenshot_2021-09-30-17-13-57-31](https://user-images.githubusercontent.com/80623554/136793218-f037c915-d168-4742-90d4-9b830bf1bcb1.jpg)

**Comment by Nine-Tailed** [comment]
In my opinion it is better to add a contour line at the turns arrows.

**Comment by dmpr0** [comment]
<img src="https://github.com/osmandapp/OsmAnd/assets/9365308/f017b6d6-9f26-4eb0-bffb-8403df2e8054"  width="300" height="auto"/> 
!table

**Comment by vshcherb** [comment]
There should be a formula to check contrast ration - https://stackoverflow.com/questions/22031644/formula-for-contrast-ratio-threshold-in-cielab-space - alternate color could be just opposite by hsv.

**Comment by vshcherb** [comment]
Bugs mentionned on demo

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#710m, released: 2023-09-01
- there is no option to change color of the turns arrows in the Route line settings (Navigation > Navigation settings > Customise route line). Their color is changed automatically. 
- turn arrows are good seen when their width is set to *medium* or *bold* in day and night modes and styles

<table style="width:100%">
  <tr>
    <th>day mode</th>
    <th>night mode</th>
    <th>styles</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/116079541/be2bda66-5122-42d6-ac61-163f7e3e1202"  width="200" height="auto"/></td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/116079541/65ce226d-7a7f-459a-b480-7d5762350ab7"  width="200" height="auto"/></td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/116079541/e8909e36-8008-4232-bbb6-63612ea6ee2e"  width="200" height="auto"/></td>
  </tr>
