### ISSUE TITLE
Routing symbol for navigating roundabouts is messed up on left-hand drive roads.

### ISSUE THREAD

**Issue by jhol** [osmandapp/Osmand#1297]
On a UK roads when I approach a roundabout it shows the direction of travel around the roundabout being anti-clockwise; it should be clockwise.

If this is the 4th exit say, then I would enter the roundabout at the 6-o-clock position, and exit at the 3-o-clock position going right. Not only does the arc go the wrong way i.e. subtending a 90-degree angle, rather than a 270-degree angle, it also tries to cram the stubs for exits 1-3 into that 90-degree angle, rather than spreading them round the 270-degree angle.

**Comment by vshcherb** [comment]
There is a setting Driving Region (for left hand navigation), please select UK
