### ISSUE TITLE
Rename in the Download map list Mexico city map to State of Mexico

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#12976]
There are two state maps named "Mexico City". Only one of them (the one containing the point 19.43242° N, 99.13311° W) should be named that.
The other one should be named "State of Mexico". It would also be correct to just label it "Mexico", but that could be more confusing for people not familiar with the country's states.
![Screenshot_20211008-200140](https://user-images.githubusercontent.com/80623554/136779589-2033cb25-efa3-4d32-a8d4-64dcd783fa25.png)

**Comment by xmd5a2** [comment]
We use country/state names from OSM. It is not possible to rename state in automatic mode without losing all future edits/fixes from OSM.
