### ISSUE TITLE
Signal entering the proximity circle (Waypoint extension proximity)

### ISSUE THREAD

**Issue by GuentherGredy** [osmandapp/OsmAnd#12973]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Dear Osmand support team,

does Osmand evaluate the waypoint extension "Proximity" in a gpx file as attached?
If yes, does Osmand signal, if one is entering the proximity circle of the waypoint?

Until now I could not find a means to get this out of Osmand (maybe related to my learning curve).

The use case behind:
Sometimes you are in front of a junction where it is not obvious whether to go left or right (e.g. if the two tracks behind the junction have a very acute angle and run a rather long time very close together; in addition, you have selected a low resolution and are not staring all the time at your handy). In the planning phase of the hike it would be a nice idea to plan a waypoint before this junction called e.g. "attention" with explaining text related to the topic above. While hiking it would be convenient, if Osmand could give an acoustic signal when entering the proximity circle.

Thank you very much for your attention.

BR

Guenther

[DR_Route.txt](https://github.com/osmandapp/OsmAnd/files/7320956/DR_Route.txt)

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by vshcherb** [comment]
Nope, OsmAnd doesn't support proximity circles.

**Comment by GuentherGredy** [comment]
Thank you, vshcherb, for your answer. Isn't it an interesting use case, worth to be supported by Osmand? Would appreciate a more promising label than "nice to have" :=). I think, if the feature would be available, the ideas for additional use cases would increase. Thanks anyway. BR Guenther

**Comment by GuentherGredy** [comment]
Thank you for your comment. Yet, as a hiker or biker I don't want to feed data into resp. watch more than one App. I agree concerning battery power, but I'm also used to have a power bank with me so that I can rely on my mobile and OsmAnd. Escuse me for my insistency :=).

**Comment by tmusolf** [comment]
Proximity sensing for waypoints is something I have wanted for years.  Garmin BaseCamp supports setting a proximity radius for individual waypoints.

Ideally, OSMAnd would support this proximity field with a global on/off switch.  An additional option for each gpx track would enable proximity alerts for each waypoint in the track file with a common, default proximity radius.

I would use this feature when hiking, biking, rafting, driving when I don't want to constantly be checking my phone/OSMAnd.  It lets me be more present in the moment and have OSMAnd alert me when I'm getting close to a place of interest.  In extended backcountry trips it also saves phone battery, but not having to constantly check the phone.

**Comment by GuentherGredy** [comment]
I fully agree! Thanks for your vote.
I'm developing hiking and biking tours using Garmin's BaseCamp together with OSM maps; this is my data base for all my outdoor activities. In preparation of a tour I export different gpx-files and use them on my mobile with OsmAnd. A very convenient workflow.
Before I have used a Garmin navi (GPSmap64) which provides the feature under discussion. Using OsmAnd yet has a lot of obvious advantages.
So it is an uncomfortable break using OsmAnd in comparison to GPSmap64.

**Comment by sonora** [comment]
I think we have the basic code in place to be able to do it. And possibly even a bit more, have you played with this setting: Go to your navigation profile, there `Configure map > Navigation settings > Voice prompts > Announce`, where we support announcing e.g. track waypoints or favorites.

I have not tested, but may possibly even work outside the navigation case after you activated the voice module by e.g. briefly starting/ stopping a voice navigation. (Announcement radii are hardcoded for now for the different point types. )

**Comment by tmusolf** [comment]
I was aware of that setting and had tried in briefly awhile ago, but should probably investigate it more.  

Ideally having a user selectable radii, either for individual waypoints, GPX file or globally makes the feature much more usable.  For example, if you are driving you'd want a much larger radii, say 1/2km, because you are traveling faster.  If you're hiking you may want the radii to be 50 metes.

**Comment by GuentherGredy** [comment]
Thank you, sonora for your comment. I've tried the voice prompts before many OsmAnd versions while hiking and found that there is a signal not only at real crossings or junctions, but at almost every bend in the path; when hiking, this is not necessary resp. rather annoying, and that is why I have not used the voice announcements since then.
It would be nice if OsmAnd **in the menu of a profile** under navigation settings next to "voice prompts" had its own menu item, e.g. "Proximity Circles for Waypoints" or similar, where I can turn the feature on or off; it would also be great to be able to select one of the system sounds there. If this sounds, the hiker can look at the details of the waypoint if necessary, in particular textual instructions that belong to this waypoint. This would allow optimal use of the corresponding feature of Garmin's BaseCamp. The textual hint of a waypoint created in Garmin's BaseCamp is already available in OsmAnd; I've tested that before. The implementation would give the great advantage described by tmusolf ("...it lets me be more present in the moment and have OSMAnd alert me when I'm getting close to a place of interest..."). Thank you very much for your interest! BR Guenther

**Comment by sonora** [comment]
Yes, all I'm saying is we have the basic code in place to perform similar functionality. Whether ee expand the UI to cater for more use cases like you explain rests with product management.

**Comment by vshcherb** [comment]
Main issue that geofence functionality usually works with background and we could implement only if you have navigation / gpx recording or you run application in foreground which is not that useful may be

**Comment by sonora** [comment]
Yes,I think it may even work today if (1) you start/stop a brief voice navigation (to have the voice modile active), then (2) activate track recording to keep the foreground service active even while the phone is in your pocket. Have not tested, though.
