### ISSUE TITLE
Contour line numbers often unreadable

### ISSUE THREAD

**Issue by Pizzacutter-at-tty3** [osmandapp/OsmAnd#12998]
![Screenshot_2021-09-30-15-33-28-840_net osmand(1)](https://user-images.githubusercontent.com/30387161/137265662-77745bdb-d1ea-4276-9cca-49fdc0bd1e15.jpg)

### Description
When using map styles like Default or Mapnik (in this case) the numbers describing m.a.s.l. near detailed contour lines are absolutely unreadable, as shown in the picture. It also applies to things like stream names or something that's very detailed and squiggly. Please change the way text flows around the lines.

### Your Environment
OsmAnd Version: 4.0.8
Android/iOS version: Android 11, MIUI 12.1
Device model: Xiaomi Mi 9T

**Comment by vshcherb** [comment]
Will be fixed in 4.1 (tomorrow beta build will be available)
