### ISSUE TITLE
Street only found over sub-urb name, not city name (Ringheim)

### ISSUE THREAD

**Issue by golden-spiral** [osmandapp/OsmAnd#12999]
# 🐞 routing report

### Routing engine

- [X] OsmAnd's in-app offline routing

### Routing Profile

Car

### Start and end points

Startpoint: "Current location" (does not matter)
For example: https://www.openstreetmap.org/way/140961619 
It applies to any street in that suburb.

### Actual and expected routes

When searching for the address "Großostheim Hasselstraße" no results are found, but "Ringheim Hasselstraße" yields the desired result.  Ringheim is a part of the administrative entity Großostheim.  Adresses in other parts like "Wenigumstadt" or "Pflaumheim" can be found when using "Großostheim", the relation https://www.openstreetmap.org/relation/534355 contains all four parts. 

So I do not know if this is a data error or a routing error in OSMand.  However, the OSM routing and OpenRouteService correctly find Ringheim as part of Großostheim.

### Is this a regression?
Unknown.

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>
4.0.7
</code></pre>

**Device and Android/iOS version:**
Fairphone 3, Android 10

**Maps used (online or offline):**
- [X] Offline maps offered within the OsmAnd app for download.

**Comment by Dima-1** [comment]
Fix request https://github.com/osmandapp/OsmAnd-tools/pull/440
