### ISSUE TITLE
Position of favourites/icons is not rotated with the map while navigation and the map is not "north up"

### ISSUE THREAD

**Issue by Zahnstocher** [osmandapp/Osmand#1300]
The position of favourites/icons is not rotated with the map while navigation and the map is not "north up".
Thus the favourites/icons are floating around/rotated out of the map view/shown on the wrong position.
https://groups.google.com/forum/#!topic/osmand/mrGzSTTY3DQ

**Comment by vshcherb** [comment]
Fixed
