### ISSUE TITLE
Weird circular routing with intermediate points

### ISSUE THREAD

**Issue by xeruf** [osmandapp/OsmAnd#13008]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Any (test on Bike & Car)

### Issue

Almost always when I add a waypoint/intermediary on a long route, OsmAnd starts some weird circular routing where it returns from the intermediary back to the starting point and then calculates the way back to the intermediary. If left unadultered, something like in the first screenshot can happen, driving the journey time and length ad absurdum.

![Screenshot_20210815-125721_OsmAnd~](https://user-images.githubusercontent.com/13354331/137617629-a6b3f790-69a7-44ae-a960-d956e8b17e7c.jpg)
ular calculations once it is done calculating the actual route
![Screenshot_20210815-122216_OsmAnd~](https://user-images.githubusercontent.com/13354331/137617622-f0629635-43d5-4d89-8f53-bd525b805248.jpg)
![Screenshot_20210730-204640_OsmAnd~](https://user-images.githubusercontent.com/13354331/137617615-df531b18-86b5-4dee-a1f9-01229a262a70.jpg)

### Is this a regression?

Seems so, but not sure.

## 🌍 Your Environment

**OsmAnd Version:**

3.9.10

**Device and Android/iOS version:**

Samsung Galaxy S7 Edge running Android 8.0

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps

**Comment by vshcherb** [comment]
There was issue  fixed with 4.0 release
