### ISSUE TITLE
Does not appear dialog "Track saved" (to rename and show the track on the map)

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#13003]
### How to reproduce?
Go to the Menu->Plugins->Trip recording->Settings->Track storage folder->select Store recorded track in monthly folder. When you finish trip recording the dialog "Track saved" (like on the picture below) that allows you to rename and show track on the map does not appear.
![image](https://user-images.githubusercontent.com/80623554/137491111-63a29c0f-6450-4818-8e95-f70f4c0707a1.png)

### Your Environment
OsmAnd Version: 4.0.8 
Android/iOS version: Android
Device model: Sony Experience XZ1

**Maps used (online or offline):**   offline
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by supsm** [comment]
This still occurs to me. I have not changed the save location (it uses Tracks), but the dialog does not appear.

Osmand 4.5.10 F-droid, Google Pixel 7, Android 14

**Comment by DmitryAlexei** [comment]
Please try 4.6 from Google play and see if it works for you.
