### ISSUE TITLE
Updating map files floods the sdcard memory

### ISSUE THREAD

**Issue by Lutwick** [osmandapp/Osmand#1303]
This is for OsmAnd+ 2.0.4 on Android.

When I update the map files, the available space on my sdcard decreases as the new files are downloaded. After the updates are finished, I still have as little space avaliable on the sdcard as if the files were downloaded additionally instead of replacing the old ones.

Only after a restart of my Android, I find the LOST.DIR on my sdcard full of files named 809382, 813599, 855703, etc. The sizes of those files look exactly like the downloaded map files.

**Comment by vshcherb** [comment]
Can't reproduce. Something specific to Android OS.

**Comment by Lutwick** [comment]
The problem still persists... Just checked again.
