### ISSUE TITLE
bike shop with bike rental POI missing in search results

### ISSUE THREAD

**Issue by bege10** [osmandapp/OsmAnd#13034]
### Description
E.g. search for bike rental in category search: You will not find a bike shop with bike rental, you will find it only if you search for bike shop.
https://www.openstreetmap.org/node/279569377
shop=bicycle
bicycle:service:rental=yes

### How to reproduce?
Search > Categories > "Fahrradverleih" (in German locale for bike rental): the linked POI is missing
Search > Categories > "Fahrradgeschäft" (in German locale for bike shop): the linked POI is displayed

### Your Environment
OsmAnd Version: 4.0.7
Android/iOS version: 10
Device model: Fairphone 3

**Maps used (online or offline):**   
Offline, here Germany_niedersachsen_europe.obf

**Comment by xmd5a2** [comment]
Search doesn't work for additional categories (https://github.com/osmandapp/OsmAnd-resources/blob/master/poi/poi_types.xml#L1423)
If I type "прокат" no search results are displayed. But if I create custom filter then bicycle rentals are found correctly. This should be fixed by android team.

**Comment by vshcherb** [comment]
We can allow to search and create custom poi filter if poi additional category  is not global (like payment, etc). It should be implemented as part of the search structure with test, so it's backend task

**Comment by alisa911** [comment]
Need to add translations for additional categories.

**Comment by vshcherb** [comment]
This will be continued in https://github.com/osmandapp/OsmAnd/issues/13450
