### ISSUE TITLE
Japanese district names are inconsistently formatted in English

### ISSUE THREAD

**Issue by famichiki** [osmandapp/OsmAnd#13044]
### Description

Japanese district names ("chome") and/or related transit stops are sometimes formatted inconsistently when the map language is set to English (Transliterate if English name is missing = OFF).

The main issues are:

- [x] - District numbers are not converted to digits and still show as kanji characters (一, 二, 三, 四 etc)
- [x] - Long vowel sounds are indicated by the non-standard use of hyphens or the insertion of the letter "u".

Ideally districts would be standardized to this format:
\<District name> \<district number>-chome
Example: Nanotsu 4-chome 

Improperly formatted examples include:
Nagazumi 1 cho-me
Midoricho- 三 Cho-me
Chiyo 5 Cho-me
Murasakibaru 7 choume
Kotakecho-nichome

Which should become:
Nagazumi 1-chome
Midoricho 3-chome
Chiyo 5-chome
Murasakibaru 7-chome
Kotakecho 2-chome

The conversion of kanji numbers to digits is of particular importance as without knowledge of Japanese these addresses are unreadable.

Long vowel sounds ("ou") in Japanese (おう) are typically transliterated either with a macron such as "ō", or where standard English characters are preferred the "u" is dropped to simply become "o".

For example, the word chome (or chōme) is transliterated from the hiragana ちょうめ (丁目 in kanji) which consists of the syllables cho-u-me (the hyphens here are only for illustration). In the above examples, the district names incorrectly transliterated are Midoricho (Midoricho-) and Kotakecho (Kotakecho-).

However, numbers and long vowel sounds are also incorrectly represented in many different labels (such as building names) not just districts.

Further references:
https://en.wikipedia.org/wiki/Japanese_addressing_system
https://en.wikipedia.org/wiki/Romanization_of_Japanese

### How to reproduce?

1. Change map language to English (transliterate off)
2. Zoom into any city neighbourhood in Japan that contains numbered districts

### Your Environment

OsmAnd Version: 4.0.8
Android/iOS version: 9
Device model: LG-H870DS

**Maps used (online or offline):**   
Offline
Japan Kyushu Region - 1 Oct 2021
Kanto Gunma Prefecture  - 1 Oct 2021 
Kanto Tokyo  - 1 Oct 2021 
(the issue applies to other Japan maps too)

![chome1](https://user-images.githubusercontent.com/59628839/138540714-489fd9f5-d57b-4c89-bd4d-9f53421efcea.png)
![chome2](https://user-images.githubusercontent.com/59628839/138540718-b95c0c88-2c3f-48ac-bf1f-3083151e356e.png)

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-tools/pull/482
