### ISSUE TITLE
Edit POI Filters, sync POI Filters between devices, export/import POI Filters

### ISSUE THREAD

**Issue by ColinLeath** [osmandapp/Osmand#1305]
This is related to https://groups.google.com/d/msg/osmand/P1ojIEyRY8Y/Uz8PhP2H7NsJ (Import /Export POI Filter request)

I now must rebuild a new poi filter from scratch if I just want to change one item in the filter. At least I can't currently find any way of editing an existing POI filter.

That is very time consuming.

If I want to have the same view of a map on my tablet and phone or share that view with others (with the custom poi filter) there is no way that I know of to do that--

**Comment by mircozorzo** [comment]
I agree, nice to have.

**Comment by vshcherb** [comment]
This is truly could be annoying, however backing up 1 file will help, for most people it is not necessary, so this issue is not number 1 priority. Though it is very valuable.

**Comment by homersimpsons** [comment]
In the menu with POI "Custom Filter" you could add a second/third option:
- import/export with a new activity to export (by mail, to sdcard, to cloud) or import (from sdcard, from cloud)
OR
- Import
- Export
In my mind the first option is more intuitive

**Comment by pebogufi** [comment]
-- however backing up 1 file will help

Could you please tell us, which file, which directory ?
Thanks a lot, Peter

**Comment by Boothy99** [comment]
@ColinLeath 
This is exactly what I'm trying to do now,. Having a number of android devices myself, (with OsmAnd+ installed) I would love to be able to export / transfer my custom POI (pubs, waterfalls, "interesting" (to me) places, etc). 
Is there any way of digging out a file from android storage using time explorers? I'm hunting for anything in there right now.

**Comment by majkaz** [comment]
@Boothy99 It is possible, either with rooted phone, or using either Helium (google play) or oandbackup app (Fdroid). Both apps use the same method.
See [this thread](https://groups.google.com/forum/#!searchin/osmand/backup|sort:date/osmand/zBYm999unOw/UTfyvSOZAQAJ)

**Comment by majkaz** [comment]
@Boothy99 - thread named "Transfer (export/import) POI Filter ("custom filter") to another divice"

In principle use either of the named programs, on one device to backup Osmand, on another to restore.

If not rooted, you will need to allow adb on both devices and allow backup when connected to PC using adb. 
[Helium](https://play.google.com/store/apps/details?id=com.koushikdutta.backup&hl=cs&showAllReviews=true) is easier if not rooted, if rooted, I find [oandbackup](https://f-droid.org/en/packages/dk.jens.backup/) slightly better. But if you are rooted, you can simply transfer the data/data/xxxosmandxxx/databases folder from one device to another.

Without root, it will get the needed data from the restricted part of android to the accessible SDcard, and you can then copy this folder to another device and restore it from there.

**Comment by Boothy99** [comment]
@majkaz - Again, thank you enormously for the link and further details. I found the thread and am reading through it now. I'm (currently) un-rooted, but might change that just for the sake of transferring the data if needed.
Cheers!!!

**Comment by halalilalo** [comment]
I have the same requirement like Boothy99:
>"This is exactly what I'm trying to do now,. Having a number of android devices myself, (with >OsmAnd+ installed) 

Every year I look for the solution for an unrouted Android
Is there a newer solution to solve this problem?
Or ist it for normalos impossible?

**Comment by vshcherb** [comment]
This is actually planned for 3.6, all settings will be linked to profiles and make exportable

**Comment by mircozorzo** [comment]
Wonderful

Il mar 29 ott 2019, 10:38 vshcherb <notifications@github.com> ha scritto:

**Comment by halalilalo** [comment]
Thank you very much :-)
I expect 3.6 in one year

**Comment by Boothy99** [comment]
I look forward to the arrival of version 3.6 !! 
Thanks for planning adding this to OsmAnd.

**Comment by vshcherb** [comment]
We expect end of this year or most likely January 2020

**Comment by halalilalo** [comment]
Ohh very fast
Many thanks again for the implementation
Meanwhile I use Osmand+ as Campervannavi and the personal POI filterfields
are extrem helpful für traveling overland

**Comment by vshcherb** [comment]
This feature is already in nightlies and will be in beta this week

**Comment by Boothy99** [comment]
Many thanks vshcherb 👌👍

**Comment by halalilalo** [comment]
Thank you very much
