### ISSUE TITLE
Favorite address field

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#13056]
When a new favorite point changes its name (old favorite as well). Name equals address when the point has been added, but when the point name changes - the address field became blank. 

### Your Environment
OsmAnd Version: 4.1.0#32937m
Android/iOS version: 11
Device model: Samsung 10e

**Comment by dmpr0** [comment]
### ToDo
- [ ]  Don't remove address after favorite/waypoint name changing.
