### ISSUE TITLE
Basemap: Incorrect road reference

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#13058]
### Description
In zoom level 11 OsmAnd display incorrect road numbering.

### How to reproduce?
<table style="width:100%">
  <tr>
    <th>(M74) 55.32979° N, 3.47508° W</th>
    <th>(M6) 52.73776° N, 2.08192° W</th>
    <th>(A1) 55.96991° N, 2.46489° W</th>
    <th>55.91506° N, 3.29326° W</th>
 </tr>
  <tr>
<th><img src="https://user-images.githubusercontent.com/80623554/138722647-7769bb3d-e7bf-436e-a48c-935e1aa630d8.png"  width="150" height="auto"/> </th>
<th><img src="https://user-images.githubusercontent.com/80623554/138723561-e27b8352-39f0-4a75-b35d-7f1cf33c809a.png"  width="150" height="auto"/> </th>
<th><img src="https://user-images.githubusercontent.com/80623554/138724090-9a7468e9-296c-4378-91e2-887ef63f6c7c.png"  width="150" height="auto"/> </th>
<th><img src="https://user-images.githubusercontent.com/80623554/138724674-bf2d4863-d568-4e16-a161-cd05f5ebf55a.png"  width="150" height="auto"/> </th>

The map update from the 1 Oct 2021

**Comment by anastasiia936** [comment]
48.17620° N, 15.63391° E
![image](https://user-images.githubusercontent.com/80623554/140047532-5a482c47-7e4b-48f7-9765-1bb63cc8b470.png)
![image](https://user-images.githubusercontent.com/80623554/140047551-27232da8-43dc-42c2-8a2c-9a52235d16d7.png)

**Comment by ivanPyrohivskyi** [comment]
Wait until new basemap will be generated

**Comment by xmd5a2** [comment]
New basemap doesn't solves issue

**Comment by phmarek** [comment]
Map update doesn't help

**Comment by ivanPyrohivskyi** [comment]
<img src="https://user-images.githubusercontent.com/1040293/148837153-71b0b215-b98b-4f04-b409-4444384e62c6.png" width="400" /> <img src="https://user-images.githubusercontent.com/1040293/148837041-bc377dd3-5426-4d43-9272-c471830a1c00.png" width="400" />

<img src="https://user-images.githubusercontent.com/1040293/148837475-655233c2-c244-4b06-bedf-3a1f0c7e49ad.png" width="400" /> <img src="https://user-images.githubusercontent.com/1040293/148837485-21410fd6-2400-4e01-a054-dc8179a30de6.png" width="400" />

<img src="https://user-images.githubusercontent.com/1040293/148837777-a8aaec67-9686-473d-8ec0-c5db80b28300.png" width="400" />  <img src="https://user-images.githubusercontent.com/1040293/148837796-59d762fa-34ea-4a42-8f1c-189680b66c53.png" width="400" />

<img src="https://user-images.githubusercontent.com/1040293/148837996-5a53daeb-7760-4a79-b34a-3616f6821351.png" width="400" />  <img src="https://user-images.githubusercontent.com/1040293/148838010-49b48016-5734-4566-8775-c73e1a900a00.png" width="400" />

<img src="https://user-images.githubusercontent.com/1040293/148838173-e569c683-8084-4a9c-9344-81a81724f8ad.png" width="400" />  <img src="https://user-images.githubusercontent.com/1040293/148838184-be2eda3d-6a36-43eb-ad58-78e6e8b46bbc.png" width="400" />

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-tools/pull/458

**Comment by ivanPyrohivskyi** [comment]
<img width="400" src="https://user-images.githubusercontent.com/1040293/150641034-bc28d6f2-b97c-4c92-beb2-473c1dffbb7e.png" /> <img width="400" src="https://user-images.githubusercontent.com/1040293/150641040-d94d6622-5f54-456d-b76d-1107f33378dc.png" />
<img width="400" src="https://user-images.githubusercontent.com/1040293/150641047-62b2e99b-6a3c-4cbe-99ef-af55d1e4d9b1.png" /> <img width="400" src="https://user-images.githubusercontent.com/1040293/150641050-581feebc-599e-45ec-8c2e-d9229358f78e.png" />
<img width="700" src="https://user-images.githubusercontent.com/1040293/150641051-3ceaadb1-fe6d-4240-930f-9c4186ff6ffb.png" />

**Comment by vshcherb** [comment]
Maps not published yet.

**Comment by vshcherb** [comment]
https://builder.osmand.net/basemap/release/ - no mini / std release

Size difference not clear yet: mini basemap 40 MB -> 47 MB?  (Detailed 361 MB -> 375 MB)

**Comment by ivanPyrohivskyi** [comment]
Result https://builder.osmand.net/basemap/release/2022-01/

Size difference 
Name, date/bytes, diff:

World_basemap_2.obf.zip 
2021-12 - 264583151
2022-01 - 271655573
diff +6.74 Mb

World_basemap_mini_2.obf.zip
2020-06 - 24608604
2022-01 - 28700851
diff +3.9 Mb
