### ISSUE TITLE
Keep getting prompted to download local map

### ISSUE THREAD

**Issue by Nick-Payne** [osmandapp/Osmand#1306]
Running OSMAND+ 2.0.4 on Android 5.1.1. I'm in Australia, and I download maps on my PC from http://download.osmand.net/rawindexes/ and copy them to the phone because that's several times faster than letting the app download the maps itself.

Every time I start OSMAND it displays a tappable button saying "Download Australia and Oceania", though I already have the local map from rawindexes downloaded - when I go to manage map files it appears in the list of local offline maps as "Australia-oceania 2".

**Comment by vshcherb** [comment]
It needs to be renamed without 2, if you download from website
