### ISSUE TITLE
`public_transport=platform` should be considered as routable

### ISSUE THREAD

**Issue by stragu** [osmandapp/OsmAnd#13070]
A way tagged as `highway=bus_stop` seems to already be considered as a routable segment. Ways tagged as `public_transport=platform` should logically also be considered as routable, as they would form part of the route to follow in order to board public transport, and sometimes also to cross from one side to another of a large station (e.g. footways connecting each other via sections of public transport platforms).

OsmAnd already routes along the edges of pedestrian areas, so platforms tagged as areas could follow the same model.

For a thorough testing of different tagging cases, see this comment: https://github.com/openstreetmap/iD/issues/8760#issuecomment-948196855

**Comment by xmd5a2** [comment]
Can't reproduce. OsmAnd correctly routes via `public_transport=platform` in pedestrian profile. Can you provide exact way/area that is not routable?

**Comment by stragu** [comment]
Hi @xmd5a2 
It looks like it might only be the case for ways tagged with `public_transport=platform` without other tags like `highway=bus_stop` or `railway=platform`.

For example: https://www.openstreetmap.org/way/480017426
