### ISSUE TITLE
Critical Error: Favorites with null name

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#1307]
Here is how to reproduce:
Either rename one of your favorites by just deleting the name (setting it to nothing), or have your favorites.gpx file contain a favorite which has an empty name tag of the fashion <name></name>. Or probably also: Just create a new favorite with empty name.
OsmAnd will, after the next app start, not display any vector maps any more, but just a 'gray' map (raster map overlays or online maps will still be displayed, this issue affects all vector maps only). Upon app start, a toast with text "null" will appear.

The issue is critical because the situation is very hard to remediate. Rebooting the device will not help at all. From what I can see the only way out is to re-name (or edit) your 'bad' favorites.gpx file, then completely uninstall and re-install the app to get the null favorite out of the db again.

I have not checked if similar issues exist with maybe empty favorite Category names (upon creation our default now seems to be empty, while I think it used to be "Other"), empty media notes names, or other conditions which may occur while parsing any xml file (cached OSM edits?), etc.

**Comment by sonora** [comment]
I now encountered 2 users with this issue. Both seem to have one null-named favorite in their favourites.gpx, as well as some favorites which contain special national (non-ASCI) characters, so I cannot rule out that maybe also a UTF-8 issue is causing this. Will try to get my hands at one file which causes this issue. But it looks like users can produce these "bad" files in OsmAnd itself, or we have some sort of bug where OsmAnd creates these files by itself.

**Comment by sonora** [comment]
I am being told that the error came up when people tried to edit a favorite: Looks like in some fashion their favourites.gpx got messed up, they said they were presented with edit screens apparently mixing up several of their favorites on one screen. Leaving the screen caused the issue: After the next start of OsmAnd the map never showed up again (until a complete re-installation). From what I see now, they ended up with null-named favorites, but there must be an additional underlying issue in our fav-edit module causing this (and maybe even further corrupting their favourites.gpx).

**Comment by vshcherb** [comment]
I just checked and the issue is not reproducible with nightly builds. I remember small cleaning in that area, so it might helped empty favorites. Though they are deleted, but they are not causing any other troubles as I see.

**Comment by vshcherb** [comment]
Additionally backup of favorite files was introduced (compressed with bz2 to save more space) up to 20 modifications

**Comment by vshcherb** [comment]
The issue has found and fixed
