### ISSUE TITLE
Add filter "bicycle=yes" for the Charging station POI

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#13076]
It would be useful to be able to filter POI Charging station and select to display stations that are suitable for car or for bicycle only.

**Comment by xmd5a2** [comment]
Already done
![Screenshot_2021-11-03-11-07-25-615_net osmand plus](https://user-images.githubusercontent.com/5829014/140027489-8182381b-8b9c-4225-8a88-69f493390824.jpg)
