### ISSUE TITLE
Map problem on the tunnel

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#13071]
![telegram-cloud-photo-size-4-6034837206373349641-y](https://user-images.githubusercontent.com/1042025/138908036-203d9661-24d8-4387-8754-b2c63ea0c6cf.jpg)

**Comment by ivanPyrohivskyi** [comment]
Cause of problem in rendering styles and value "order" for layer="-1"
[<apply_if layer="-1" order="62"/>](https://github.com/osmandapp/OsmAnd-resources/blob/6eb74b8356a6f2302139f95356f2df8721f0d197/rendering_styles/default.render.xml#L3418)

I suggest add <apply_if layer="-1" tunnel="yes" order="76"/> no less than "pedestrian" order
And <apply_if layer="-2" tunnel="yes" order="71"/> no less than "motorway_link order"
Similar rules add to "trunk" and "primary" highways

https://github.com/osmandapp/OsmAnd-resources/pull/747/files

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-core-legacy/pull/50

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-core-legacy/pull/51
https://github.com/osmandapp/OsmAnd/pull/13210
https://github.com/osmandapp/OsmAnd-resources/pull/751

**Comment by ivanPyrohivskyi** [comment]
Animated changes 11 zoom:
![11](https://user-images.githubusercontent.com/1040293/142665708-62900b4e-1f5e-48d8-9805-6adefb23c29b.gif)

Animated changes 12 zoom:
![13](https://user-images.githubusercontent.com/1040293/142665717-84fc7469-24be-4d2a-85e1-97662db187b8.gif)

Animated changes 13 zoom:
![12](https://user-images.githubusercontent.com/1040293/142665725-356d6a5c-1a67-4905-8759-4728f8fc3890.gif)

**Comment by ivanPyrohivskyi** [comment]
Before changes:
Zoom:9 Main:1240 Low-level:777
Zoom:10 Main:1274 Low-level:980
Zoom:11 Main:1419 Low-level:13341
Zoom:12 Main:1044 Low-level:11853
Zoom:13 Main:1260 Low-level:10905
Zoom:14 Main:644 Low-level:6844
Zoom:15 Main:126 Low-level:3040


After changes:
Zoom:9 Main:1403 Low-level:625
Zoom:10 Main:1325 Low-level:932
Zoom:11 Main:2963 Low-level:11807
Zoom:12 Main:1445 Low-level:11415
Zoom:13 Main:1564 Low-level:10608
Zoom:14 Main:663 Low-level:6833
Zoom:15 Main:126 Low-level:3040

**Comment by ivanPyrohivskyi** [comment]
<img src="https://user-images.githubusercontent.com/1040293/142887968-18b92713-6b74-4c78-8124-55677c2cb4b6.png" width="400" />  <img src="https://user-images.githubusercontent.com/1040293/142887985-e80edaf8-49e4-47b1-a69a-6a85b809396b.png" width="400" />

<img src="https://user-images.githubusercontent.com/1040293/142888634-4cf4a33b-19ba-4ace-8c7a-93a46494e2f4.png" width="400" />  <img src="https://user-images.githubusercontent.com/1040293/142888784-c841daaf-e528-4e1f-b353-0da997777a3b.png" width="400" />

<img src="https://user-images.githubusercontent.com/1040293/142889166-e9e421f2-cf11-4e8d-856b-d8d29f29d00d.png" width="400" />  <img src="https://user-images.githubusercontent.com/1040293/142889156-e417af03-d03c-4bbe-84e4-57e07ef785a5.png" width="400" />

<img src="https://user-images.githubusercontent.com/1040293/142889487-938020c0-faa7-4acc-80f5-f3fb46c848bf.png" width="400" />  <img src="https://user-images.githubusercontent.com/1040293/142889502-f4a5a34b-a33f-4407-ac56-2ac8ad5668bf.png" width="400" />

<img src="https://user-images.githubusercontent.com/1040293/142889837-b68804d9-6418-4290-be48-d623c9cbb110.png" width="400" />  <img src="https://user-images.githubusercontent.com/1040293/142889857-5cfca00c-23a2-4cb9-bf75-74b3591b4904.png" width="400" />

<img src="https://user-images.githubusercontent.com/1040293/142890478-a13dd9ed-2ece-4bf1-89a5-6bb56449c4fd.png" width="400" />  <img src="https://user-images.githubusercontent.com/1040293/142890042-9e9e8449-f7c0-465e-8c46-c47d073ca4fb.png" width="400" />

**Comment by ivanPyrohivskyi** [comment]
Compare last changes in default.render.xml

<img src="https://user-images.githubusercontent.com/1040293/143022870-db570d38-e725-4aa8-b269-501721fd4031.png" width="400" />  <img src="https://user-images.githubusercontent.com/1040293/143022878-6e78f517-080c-43a9-b2d7-71a45156d31e.png" width="400" />


<img src="https://user-images.githubusercontent.com/1040293/143023083-5b112901-3d0d-4e16-a8ca-b0fe4cbb085b.png" width="400" />  <img src="https://user-images.githubusercontent.com/1040293/143023092-103575c2-9fcf-4d6e-9731-75d641643f34.png" width="400" />

<img src="https://user-images.githubusercontent.com/1040293/143023317-d4706e85-6e60-4d56-bc3d-838770f0c8c7.png" width="400" />  <img src="https://user-images.githubusercontent.com/1040293/143023324-dc80c48c-5015-46c9-8578-0b1327d9eff8.png" width="400" />

<img src="https://user-images.githubusercontent.com/1040293/143023578-cad3d67a-a1a1-40a6-b524-8648fb36d8e3.png" width="400" />  <img src="https://user-images.githubusercontent.com/1040293/143023595-d0996815-e274-4e13-93aa-aa9a62d869e6.png" width="400" />

**Comment by ivanPyrohivskyi** [comment]
Test on real device Samsung Galaxy M21.
Before/after

<img width="300" src="https://user-images.githubusercontent.com/1040293/143216365-17583383-98b8-40e5-ab7b-abfd7e6e1568.jpg" />  <img width="300" src="https://user-images.githubusercontent.com/1040293/143216385-d348cb89-3e17-4717-8a51-3bf93a9806b6.jpg" />

<img width="300" src="https://user-images.githubusercontent.com/1040293/143216831-f137b41e-02fc-45eb-82fb-a48b44341532.jpg"/>  <img width="300" src="https://user-images.githubusercontent.com/1040293/143216862-b899690b-99db-4bb1-bd45-20052cc1d349.jpg" />

<img width="300" src="https://user-images.githubusercontent.com/1040293/143217352-9a11ea2a-37e2-4263-85fa-83986448a5eb.jpg" />  <img width="300" src="https://user-images.githubusercontent.com/1040293/143217381-eebed785-91a2-4a45-88fb-021591589264.jpg" />

<img width="300" src="https://user-images.githubusercontent.com/1040293/143217551-a0034b9e-4653-4fdf-b8d8-ad852d02abdc.jpg" />  <img width="300" src="https://user-images.githubusercontent.com/1040293/143217573-af131bd9-99eb-4d62-9bf2-9b3be323ee0e.jpg" />

<img width="300" src="https://user-images.githubusercontent.com/1040293/143217763-e59b26ce-514d-47a8-bef1-55e38dfe9801.jpg" />  <img width="300" src="https://user-images.githubusercontent.com/1040293/143217808-eb58db6a-7edd-40b4-9c73-567ae3210ceb.jpg" />

**Comment by ivanPyrohivskyi** [comment]
Test on real device Samsung Galaxy M21.
Before/after

<img width="300" src="https://user-images.githubusercontent.com/1040293/143219986-8cbd316b-9975-4cff-9a49-67b2f6c7bb58.jpg" /> <img width="300" src="https://user-images.githubusercontent.com/1040293/143220013-c8503a73-d6c4-41c4-b90e-818fc5b09895.jpg" />

<img width="300" src="https://user-images.githubusercontent.com/1040293/143220031-d7adcf8d-0b89-4d7d-98dc-3580c4cb83fc.jpg" />  <img width="300" src="https://user-images.githubusercontent.com/1040293/143220045-7e192618-faac-48b2-90aa-77b1a9b72342.jpg" />

<img width="300" src="https://user-images.githubusercontent.com/1040293/143220061-c7f1c706-487a-4660-8dc7-cd12fc0bf16b.jpg" /> <img width="300" src="https://user-images.githubusercontent.com/1040293/143220078-0df61414-da78-4cb7-8800-b58830a5d4b6.jpg" />


<img width="300" src="https://user-images.githubusercontent.com/1040293/143220085-ad9eb598-ac9a-4cfd-9b7d-77451e4fb9e1.jpg" />  <img width="300" src="https://user-images.githubusercontent.com/1040293/143220096-cab65e0f-b312-4932-b5a1-f79104b25667.jpg" />


<img width="300" src="https://user-images.githubusercontent.com/1040293/143220109-418c80c9-a0e2-4b54-ac53-8d63083937c6.jpg" />  <img width="300" src="https://user-images.githubusercontent.com/1040293/143220122-8df318e1-9903-4ffa-b488-d907457ab370.jpg" />

**Comment by ivanPyrohivskyi** [comment]
Test on real device Samsung Galaxy M21.
Before/after

<img width="300" src="https://user-images.githubusercontent.com/1040293/143221962-a62fd722-a457-40e2-82d7-c7b1c50e3ba3.jpg" />  <img width="300" src="https://user-images.githubusercontent.com/1040293/143221987-4aff6551-e599-47b7-8060-f87c0bcdf9a3.jpg" />

<img width="300" src="https://user-images.githubusercontent.com/1040293/143221994-92b6d608-1274-4343-9bcb-3a8ab40b6888.jpg" />  <img width="300" src="https://user-images.githubusercontent.com/1040293/143221998-0651641a-4c60-4fe7-a9e3-25e9f3acde17.jpg" />  

<img width="300" src="https://user-images.githubusercontent.com/1040293/143222004-ee46bd45-8884-4394-a22b-6d4d057512d3.jpg" />  <img width="300" src="https://user-images.githubusercontent.com/1040293/143222011-e6ce88ec-662c-417a-9de8-c737ea043acd.jpg" />  

<img width="300" src="https://user-images.githubusercontent.com/1040293/143222019-d5e6e168-49dc-46e7-83ee-4a20e2b4d3f5.jpg" />  <img width="300" src="https://user-images.githubusercontent.com/1040293/143222022-734339db-f32a-4813-b676-48c990e68ab7.jpg" />  

<img width="300" src="https://user-images.githubusercontent.com/1040293/143222026-7bda9a97-ed30-4de5-8419-2d20cb2f9bb4.jpg" />  <img width="300" src="https://user-images.githubusercontent.com/1040293/143222034-1202e783-c0f4-4b9b-bdcb-48ceb4335d5d.jpg" />  

<img width="300" src="https://user-images.githubusercontent.com/1040293/143222039-6dacf9e0-d712-4440-8b22-d6ccf7848db5.jpg" />  <img width="300" src="https://user-images.githubusercontent.com/1040293/143222041-cab5b66f-a7cf-45ed-b4c7-092967fa7b6f.jpg" />

**Comment by vshcherb** [comment]
There is a problem probably it need to be fixed in the map generation 
<img width="300" src="https://user-images.githubusercontent.com/1042025/143240918-a60eeb27-80ab-407a-9e1c-50a8bc547e0b.jpg" />

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-tools/pull/447

Generated maps (Map index only)
[Netherlands_zuid-holland_europe.obf.zip](https://drive.google.com/file/d/1shOCzTEdwjsna_LWUHe1Ee4Tz7vUBtJ4/view?usp=sharing)
[Netherlands_noord-holland_europe.obf.zip](https://drive.google.com/file/d/1Cu5UdhMmOl2Uhr7WgX_fD9RdvfLTGSML/view?usp=sharing)

**Comment by ivanPyrohivskyi** [comment]
Temporary rollback changes to old rendering
https://github.com/osmandapp/OsmAnd-core-legacy/pull/55
https://github.com/osmandapp/OsmAnd-resources/pull/752

**Comment by ivanPyrohivskyi** [comment]
New glue objects in maps generating
https://github.com/osmandapp/OsmAnd-tools/pull/450

**Comment by alisa911** [comment]
Osaka
https://www.openstreetmap.org/way/224825697
<img width="187" alt="Screenshot 2021-12-13 at 16 41 00" src="https://user-images.githubusercontent.com/38911173/145832368-b953d4a8-3a3a-43cb-a9b3-8bc5af2b54ad.png">
<img width="98" alt="Screenshot 2021-12-13 at 16 41 10" src="https://user-images.githubusercontent.com/38911173/145832374-f3faad7f-4982-45c9-8539-68dfc630f447.png">
https://www.openstreetmap.org/way/271047922 wrong ref
<img width="158" alt="Screenshot 2021-12-13 at 16 49 47" src="https://user-images.githubusercontent.com/38911173/145833899-50da7bc3-c1fd-4a16-8fa8-1d613c56fd97.png">
<img width="144" alt="Screenshot 2021-12-13 at 16 49 51" src="https://user-images.githubusercontent.com/38911173/145833904-e66ee4a5-8cf8-4df7-a961-c3f0dc115317.png">
https://www.openstreetmap.org/way/134901993
<img width="251" alt="Screenshot 2021-12-13 at 16 55 21" src="https://user-images.githubusercontent.com/38911173/145834892-5f54ffff-d3ea-4baa-abdf-b8ddc43729c7.png">
<img width="213" alt="Screenshot 2021-12-13 at 16 55 30" src="https://user-images.githubusercontent.com/38911173/145834898-ee3dba93-d48d-4cb1-ba0f-bfd99db3ba3d.png">

**Comment by alisa911** [comment]
Sidney
https://www.openstreetmap.org/way/173223772#map=14/-33.8144/151.1673
<img width="254" alt="Screenshot 2021-12-13 at 17 11 12" src="https://user-images.githubusercontent.com/38911173/145837437-21b92fc4-50a4-4384-843c-2583eb2d564a.png">
<img width="292" alt="Screenshot 2021-12-13 at 17 11 18" src="https://user-images.githubusercontent.com/38911173/145837448-00ee9009-b657-40c8-86b3-b8b9492dbd0b.png">
https://www.openstreetmap.org/way/225882687
https://www.openstreetmap.org/way/154825083
<img width="191" alt="Screenshot 2021-12-13 at 17 21 36" src="https://user-images.githubusercontent.com/38911173/145839186-e7983203-d3db-431f-97a2-19f38fbb41bd.png">

**Comment by alisa911** [comment]
Vancouver
http://www.openstreetmap.org/#map=9/49.33611/-122.847046
<img width="500" alt="Screenshot 2021-12-13 at 17 38 41" src="https://user-images.githubusercontent.com/38911173/145841930-6d240ebf-d3a9-4f26-873d-83edcdf31351.png">
<img width="351" alt="Screenshot 2021-12-13 at 17 38 45" src="https://user-images.githubusercontent.com/38911173/145841940-8bb5fbb9-1996-401d-9275-118f5aaadc36.png">

**Comment by alisa911** [comment]
Brasilia
https://www.openstreetmap.org/way/51316565
<img width="242" alt="Screenshot 2021-12-13 at 17 54 10" src="https://user-images.githubusercontent.com/38911173/145844607-46c80b90-0a05-4b3a-9fcc-084601ca5800.png">

**Comment by alisa911** [comment]
core-legacy https://github.com/osmandapp/OsmAnd-core-legacy/tree/issue_13071_generate_maps

**Comment by ivanPyrohivskyi** [comment]
Resources https://github.com/osmandapp/OsmAnd-resources/pull/772
Core-legacy https://github.com/osmandapp/OsmAnd-core-legacy/pull/72
Android https://github.com/osmandapp/OsmAnd/pull/13678

Tools https://github.com/osmandapp/OsmAnd-tools/pull/465
