### ISSUE TITLE
Address search issue in Lutsk

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#13083]
### Description
OsmAnd cannot find street "Черчицька" in Lutsk city.

https://www.openstreetmap.org/way/115447600
![Screenshot_20211027-163704](https://user-images.githubusercontent.com/80623554/139215239-5b09af79-1df4-4648-aea0-2b3a36df5bda.png)

### How to reproduce?
Try to find via search "Черчицька" street in Lutsk city.

**Maps used (online or offline):**   offline, map updated from 1 Oct 2021
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-tools/pull/444

This way https://www.openstreetmap.org/way/115447600 (Черчицька) was merge to way https://www.openstreetmap.org/way/115447600 (Чернишевського) by "old_name:-1992-09-15" tags.
Now these are two different streets.

**Comment by ivanPyrohivskyi** [comment]
Will fix new map (December 2021)
