### ISSUE TITLE
Any statement after the <fallback_rule_separator> in opening_hours leads to "open 24/7" in OsmAnd

### ISSUE THREAD

**Issue by bege10** [osmandapp/OsmAnd#13087]
### Description

Any statement after the <fallback_rule_separator> in opening_hours e.g. `|| "season may vary"` leads to "open 24/7" in OsmAnd.

### How to reproduce?

This water_park https://www.openstreetmap.org/way/51821465 has general opening hours May 15-Aug 31: Mo-Su 10:00-20:00 but depending on the weather the opening season may vary. Thus `May 15-Aug 31: Mo-Su 10:00-20:00 || "Season may vary"` is a valid tag but OsmAnd displays "24/7".

Is it possible to just display the plain value instead of "24/7" whenever a value is invalid or too complex to display?
(As a workaround I put the addition into a description tag for now.)

### Your Environment
OsmAnd Version: 4.0.7
Android/iOS version: 9, 10
Device model: Samsung Galaxy S5 Plus (SM-G901F), Fairphone 3

**Maps used (online or offline):**   
Offline: Germany_niedersachsen_europe.obf 2021-10-01

**Comment by ivanPyrohivskyi** [comment]
No need show 24/7 only text "Season may vary"
![Screenshot 2021-11-16 at 15 34 57](https://user-images.githubusercontent.com/1040293/141995188-8b271449-a62e-4690-b24e-0f014d584b02.png)

**Comment by bege10** [comment]
> 
> 
> No need show 24/7 only text "Season may vary" when time frame not covered by previous rules ![Screenshot 2021-11-16 at 15 34 57](https://user-images.githubusercontent.com/1040293/141995188-8b271449-a62e-4690-b24e-0f014d584b02.png)
> 
> Create map for test

When "24/7" is removed, does the opening hour turn red? I think this would be best in this case: Show closed if not within the standard season, but "Season may vary".
