### ISSUE TITLE
Change focus when "ADD TAG" selected in advanced OSM Editing.

### ISSUE THREAD

**Issue by InsertUser** [osmandapp/OsmAnd#13092]
# 🚀 feature request

### Description

The "ADD TAG" button in advanced editing should move the text input to the newly created key field. 

### Describe the solution you'd like

When creating or editing a POI more experienced mappers can add additional details not shown on the basic tab of the screen through the advanced tab with the ability to add a tag manually. Unfortunately while tags can be added the text input does not move to the new tag fields. 

When no text input is underway there is no keyboard shown and little risk of confusion, but when there is a keyboard because another field has just been edited the input stays in the old field and does not move to the fields created by the most recent (add tag) input in the UI. 

I would like the text input to move to the area for the newly created tag.

### Describe alternatives you've considered

An alternative would be for the add tag button to stop any existing text input and dismiss the keyboard, but in most cases I think users will probably want to continue adding the tag they have requested fields for. 

This request would also be made redundant by an overhaul to the advanced editing area to eliminate the basic fields at the top entirely and replace them as for the tags created by the fields in the basic tab. This would also make it easy to add a lifestyle prefix to a closed amenity or preserve an existing name tag as an `old_name`  as the existing name and top level POI tag table would be replaced like the fields below the basic/advanced switch and easy to modify in their entirety.

**Comment by dmpr0** [comment]
#ToDo
Fix "Add tag" button behavior
- [ ] Taping "Add tag" should open the keyboard and move the input to the new tag field
- [ ] If the keyboard is already open, just move input focus into the new tag field.
