### ISSUE TITLE
"Loading data exception" /route calculation + search broken

### ISSUE THREAD

**Issue by Cqui** [osmandapp/OsmAnd#13093]
### Description
Two errors have happen at the same time, since the last map update,

Search doesn't find any location, 

Asking for a route brings an error "Loading data exception" and a route is calculated but completly wrong like a 4km route with normal car profil is announced as an 3 hours trip or the walking profile gives direct as the crow fly

### How to reproduce?
Make any adresse search
Try any route

### Your Environment
OsmAnd Version: 4.0.8 /2021-09-22
Android/iOS version: 9.1.0
Device model: HAUWEI P20 Lite 

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
Offline map France_auvergne-rhone-alpes_europe 1/10/2021

**Comment by vshcherb** [comment]
Let's see if we or somebody can reproduce it.

**Comment by Cqui** [comment]
I got the map update this weekend, right after it worked, I could find small villages I wanted to visit and get the route calculation fine

But now it is down again, same behavior, I can't search for the very big city nearby (Lyon France) and route calculation is very limited again,

**Comment by deerwood** [comment]
Since some versions I also have the issue, that no search is possible at all. In the middle of Hamburg a search far "Hamburg" finds nothing, neither adding street names nor a bigger radius  do help, Current Version is 4.1.9. Offline Maps are all current (Germany. Hamburg and surrounding regions).

**Comment by Cqui** [comment]
I removed the app from the phone then installed it again and it seems to be working fine,
Only problem now is that maps seems to take a lot more space, or the old date has not been removed, I had all Europe on my phone with full map and wikipedia date with space to spare, now with 3 countries, I have errors of storage full on the camera...
Well that's another problem...

**Comment by PJuniszewski** [comment]
Bumped into the same problem - mentioned in https://github.com/osmandapp/OsmAnd/issues/15261

None of the mentioned solutions work for me tho.
