### ISSUE TITLE
Plugins menu: Nothing happens when clicking on settings for a plugin that is not activated 

### ISSUE THREAD

**Issue by nyqvist** [osmandapp/Osmand#1310]
1. Go to settings menu
2. Click on the "three dots" to the right on a plugin that is not activated.
3. In the pop-up menu click on settings
4. Nothing happens

Maybe settings here should not be visible unless it is activated
![screenshot_2015-06-04-21-20-04](https://cloud.githubusercontent.com/assets/1544300/7992575/9bf75ffc-0b00-11e5-8242-213da32de721.png)

**Comment by vshcherb** [comment]
Fixed
