### ISSUE TITLE
In case screen OFF during navigation turn it ON in N meters before next turn.

### ISSUE THREAD

**Issue by EvgenyZaretskiy** [osmandapp/OsmAnd#13110]
Hello!

Problem: driving a bike can't use a voice assistant for navigation and if I want to have a screen OFF to keep the battery it is difficult to understand when to turn. Now I'm just checking distance in km to next turn, and then control using odometer the distance to next turn, then going to turn on the screen for navigation.

Working scenario: driving the bike, screen OFF, in N meters before next turn screen going ON bringing my attention to turn soon.

**Comment by sonora** [comment]
Menu button / Configure profile / Global serrings / Screen control: Activate Option 'Navigation instructions'.

**Comment by scaidermern** [comment]
And in case you are following a GPX track, make sure to snap it to the road. Otherwise you will get lots of unnecessary instructions and thus screen wakeups.

**Comment by EvgenyZaretskiy** [comment]
> Menu button / Configure profile / Global settings / Screen control: Activate Option 'Navigation instructions'.

Aha, did find, will try.
