### ISSUE TITLE
Public transport routs on the map of Ukraine are drawn as streight lines connecting departure and destination points

### ISSUE THREAD

**Issue by fastovezz** [osmandapp/OsmAnd#13114]
### Description

Public transport routs on the map of Ukraine are drawn as streight lines connecting departure and destination points and do not consider points of stops in between the route and ignore roads. 

![Screenshot_20211104-024201_OsmAnd](https://user-images.githubusercontent.com/11711866/140239729-ab92ee37-73cd-4d6e-aa32-f0114a51b3ee.jpg)

![Screenshot_20211104-024131_OsmAnd](https://user-images.githubusercontent.com/11711866/140239809-3d6a9855-ece9-4739-85a8-41b3b91bd003.jpg)

![Screenshot_20211104-024045_OsmAnd](https://user-images.githubusercontent.com/11711866/140239825-374c512f-ba9a-46d1-a235-ee525e909d36.jpg)

### How to reproduce?
I reproduced it trying to build public transport routs between different departure and destination addresses in Kharkiv city

### Your Environment
OsmAnd Version: 4.0.8
Android version: 9
Device model: Samsund Galaxy A8 (2018) SM-A530F

**Maps used (online or offline):**   
Ofline map Ukraine_europe_2.obf.zip dated 01.10.2021 (https://download.osmand.net/download?standard=yes&file=Ukraine_europe_2.obf.zip)

**Comment by xmd5a2** [comment]
Relations
https://www.openstreetmap.org/relation/2734580
https://www.openstreetmap.org/relation/3417786
are mapped incorrectly. There are too few members with role "platform". OsmAnd uses them to build a route.

**Comment by fastovezz** [comment]
Hi @xmd5a2 
I downloaded after your comment the ofline map Ukraine_europe_2.obf.zip dated 01.11.2021 (https://download.osmand.net/download?standard=yes&file=Ukraine_europe_2.obf.zip) but still the behaviour is just the same. public transport routs are simple straihgt lines in some cases. 

I am not an experet and do not really understand your comment. But does it mean that behaviour stais the same? To me such a behaviour is obviously buggy, ain't it?
