### ISSUE TITLE
Add statistics summary about group of recorded tracks

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#13129]
It would be very useful to be able to see the recorded track statistic. E.g.: total distance, total ascent, etc., grouped by months/year/etc.
![image](https://user-images.githubusercontent.com/80623554/140706198-b2eaf192-3aa5-4c40-a100-9e11b530ff5c.png)

**Comment by dmpr0** [comment]
Duplicate if https://github.com/osmandapp/OsmAnd/issues/10381
