### ISSUE TITLE
Frequent failures to find POIs by name

### ISSUE THREAD

**Issue by kevinp2** [osmandapp/OsmAnd#13128]
### Description
OSMAnd frequently fails to find POIs by name, but this is intermittent and it's hard to pinpoint when or why it happens

### How to reproduce?
Today, I tried to find Manuel's, a restaurant in Austin, Texas, USA.  I could not find it even though I was standing right next to it, and it is on the displayed map.

![image](https://user-images.githubusercontent.com/609677/140631460-e3389683-a502-43f3-9b90-1c687ae387c3.png)

![image](https://user-images.githubusercontent.com/609677/140631464-780ab224-07e3-48b8-b3fa-e140ca12faee.png)

This is the restaurant on OSM: https://www.openstreetmap.org/way/72378709

### Your Environment
OsmAnd Version: 4.0.6
Android/iOS version: iOS 14
Device model:

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by Zero3** [comment]
@kevinp2 I noticed that you are using a different kind of quote in your search string than the one displayed in your screenshot. Did you try searching for `Manuel's` instead of `Manuel´s`?

Unfortunately, as far as I know, OsmAnd only finds stuff that matches the *exact* spelling, unlike many other search engines that do "fuzzy searching" to account for minor spelling differences etc.

**Comment by kevinp2** [comment]
> @kevinp2 I noticed that you are using a different kind of quote in your search string than the one displayed in your screenshot. Did you try searching for `Manuel's` instead of `Manuel´s`?
> 

@Zero3 , this is a good catch.  It turns out that the iOS default keyboard presents the character **´** by default, and you have to press down on it to select the character **'**

I have assigned alt_name tags to this restaurant and will see if it helps.

**Comment by kevinp2** [comment]
Update: I added the following tag to the OSM entry for the restaurant:

`alt_name=Manuel;Manuels;Manuel’s`

This seemed to work.  After the map update, OSMAnd finds it using the default iOS quote character **´**

However, I don't think this can be a general solution.  I am an iOS power user and was unaware that the iOS default keyboard presents the quote character **´** while the vast majority of OSM uses the quote character **'**

Perhaps I should submit a ticket for OSMAnd to look for the quote character **´** in the user-entered search string, and if found, also search for the same word but with the quote character **'** ?

**Comment by Zero3** [comment]
@kevinp2

> Perhaps I should submit a ticket for OSMAnd to look for the quote character ´ in the user-entered search string, and if found, also search for the same word but with the quote character ' ?

I think the right solution would be to switch to so-called "fuzzy searching", which can help with many different kinds of misspellings. That seems like a better idea than implementing a workaround for a particular single character. There are *many* ways to misspell stuff :(

**Comment by n9br** [comment]
In my case this feels like a bigger issue. For 6+ months now I can't find and/or display 'shelter' anymore (which is often useful when hiking, especially in less friendly weather ;) ). Shelter in the sense of weather shelter / small huts, which are obviously still present in the map, and are also named/classified correctly. 

I tried using different other terms like 'hut', but to no avail. 
Displaying via categories works well; but there seems to be no pre-defined category in this case.   

when it was still working, when I searched in a wooden area, most of them showed up. Now, on the contrary, only very rarely things like 'animal shelter' are being displayed. 

I'm on Android 9, with Osmand+ 4.0.8 . can attach images when on my phone if needed.  

will be very happy about investigation/tips/workarounds. also willing to join beta testing :)

cheers

**Comment by scaidermern** [comment]
> In my case this feels like a bigger issue. For 6+ months now I can't find and/or display 'shelter' anymore (which is often useful when hiking, especially in less friendly weather ;) ). Shelter in the sense of weather shelter / small huts, which are obviously still present in the map, and are also named/classified correctly.

You need to search for shelter, then choose "Shelter (service)". This should show `amenity=shelter` objects.

I agree that searching for shelters looks broken. There are dozens of different categories and it isn't obvious which one to choose when looking for a simple weather shelter while hiking.

**Comment by n9br** [comment]
works ! :) so no need to file a bug report ? should keep working, I guess.

**Comment by scaidermern** [comment]
> works ! :) so no need to file a bug report ?

No idea. The search results and the non-obvious categories still look strange to me.

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/1733
https://github.com/osmandapp/OsmAnd/pull/13534
