### ISSUE TITLE
Offline routing uses hgv=no roads even when in truck profile

### ISSUE THREAD

**Issue by morganwahl** [osmandapp/OsmAnd#13126]
All of Memorial Drive in Cambridge, Massachusetts has `hgv=no`. (There are no-trucks signs at every intersection.) However, even when using "truck" profile, the offline navigation still routes onto that road.

Yes, I did encounter this while driving a rented moving truck :-{.

I can give you any more details you need.

**Comment by dmpr0** [comment]
Should be fixed in 4.2 release.
