### ISSUE TITLE
Occasional incorrect lane guidance problems

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/OsmAnd#13141]
### Description

When using OsmAnd to navigate, I occasionally encounter a situation where it gives incorrect lane guidance, usually in the form of an incorrect turn (left or right), both verbal and in the on-screen arrows.

I have to add one specific remark:  I've been encountering this for several months now, but until recently, it was always at distant locations where it wasn't easy (or was too time consuming) to revisit to reproduce the problem.  Just a few weeks ago, I discovered that I could reproduce it on some streets local to my area.  Please don't hate me for not reporting it sooner--the other locations were always highway driving a long distance, and I couldn't really remember the exact places to be able to try to reproduce it before now.

### How to reproduce?

Begin in this parking lot:  https://osm.org/go/ZQqt_lL4a?layers=NG&m=   (could probably pick any store or other POI in this shopping center, really).

Navigate to this restaurant as your destination:  https://osm.org/go/ZQq7LxS~B?layers=NG&m=&way=319637083  or  https://www.openstreetmap.org/way/319637083  (could probably pick any nearby POI, too)

As you pass through this intersection in front of the schools you'll see the lane guidance shift to the left lane only (2m10s into the recording):  https://osm.org/go/ZQq6BDOO_--?layers=NG&m=

At about 2m21s into the screen recording, voice guidance prepares you to turn "slightly left" (even though the hard-left arrow is shown later).

As you approach this road segment, lane guidance changes to indicate you should turn into the park (incorrect!):  https://osm.org/go/ZQq6EGHq9?layers=NG&m=   (2m35s into the recording.  The turn:lanes values here are left|none|none|none.  After you've had a chance to review the problem, I intend to change the "none" values to "through" and add additional guidance for the _link road.  There are other places where OsmAnd gives correct guidance, and "none" is used in turn:lanes, though.

### Your Environment
OsmAnd Version:  you'll hate me for this, but whatever the Play store version _before_ the current 4.1.6 released 2021-10-28 one is what I used to produce the linked screen recording.  Also observed in earlier versions (see comment above about encountering this in distant locations).  I'll try to make some time to reproduce it in the current 4.1.6 version soon, too.
Android/iOS version:  Android 11
Device model:  Samsung Galaxy S20 FE (but also observed on Galaxy S9+)

**Maps used (online or offline):**   

Offline maps.  US Georgia map from September 2021 (but also observed in previous Georgia maps).  I have also encountered this on highways in Georgia over a hundred miles away from this area, and in a few places in Florida.

Due to the size of the screen recording, I can't attach it to this Issue.  Here's a link to it online instead:  
https://drive.google.com/file/d/1-5t-NsvsWrzm8_tEfvuV5b0s75efeMR7/view?usp=drivesdk 

Note:  this might or might not be the same issue raised in #12015 Issues with lane/turn guidance?

**Comment by jfburke3** [comment]
I also note that the on-screen arrows are incorrect when you are about here in the recording, indicating that you should take the left through lane only:  https://www.openstreetmap.org/?mlat=33.98269&mlon=-84.42839#map=19/33.98269/-84.42839&layers=NG  (about 11m35s) (as  you get closer to the intersection, it _does_ show that you should be in the right through lane, which makes sense).

Both locations are where you approach a road curving to the right (for the first, a _link road, for the second, a service road) for which lane guidance is not specified.  It may be a bug related to that.  I don't think I encountered this problem early in the year, and most of these road sections haven't been edited in well over a year.

I'm going to revisit that entire route and add/update lane guidance later, after you have had time to look at the problem.

**Comment by jfburke3** [comment]
Oh, I should note that the phone i was using does NOT have live updates enabled. It only uses the regular monthly map, and only versions of OsmAnd published in the Play store (usually the beta version, I'm signed up for that).

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.3.0#13873mqta, released: 2022-10-17
Navigation and voice prompts work correctly.
**Except for the case shown in the video.**

[13141.gpx.zip](https://github.com/osmandapp/OsmAnd/files/9799853/13141.gpx.zip)



https://user-images.githubusercontent.com/104760013/196162824-a62a99a5-9259-4d5f-8fdd-a4b1e6c4e122.mp4

**Comment by Zirochkabila** [comment]
[Mistake in the data](https://osmand.net/map/?start=33.917210%2C-84.467780&end=33.979485%2C-84.423111&mode=car#18/33.93140/-84.45988)

<img width="536" alt="Screenshot 2022-10-24 at 18 00 01" src="https://user-images.githubusercontent.com/104760013/197558868-d941dc1a-55ec-4c2e-aca2-ae4171ada1ce.png">
