### ISSUE TITLE
RE: Highway codes in Peru are not displayed correctly

### ISSUE THREAD

**Issue by BikeRoad** [osmandapp/OsmAnd#13140]
Hello. Some time ago I created a thread (https://github.com/osmandapp/OsmAnd/issues/8286) about this problem, that the codes of the roads (which is specified in the Ref tag) in Peru are not shown completely
as shown in figure 2.

Both the OBF file that you provide and the OBF file that I get by downloading from geofabrik and using the OsmAndMapCreator tool both have this problem.

The strange thing is that when I use the OSM file (JOSM editor save file) and convert it to OBF with OsmAndMapCreator the codes are fully displayed even though they look different as seen in image 1
It should be said that the OSM file is only a limited area of the map.

![COD](https://user-images.githubusercontent.com/19896035/141007166-66314530-a2d7-4a18-b505-d189b7881669.jpg)
I leave the link of the area in mention, although it is the same in all the roads of the country:
https://www.openstreetmap.org/#map=16/-12.3025/-76.8443

**Comment by vshcherb** [comment]
This is expected behavior. We want to display them as on 2 screenshot with shield and shorter name. You can always make it look as 2nd if you have the map name start with ```peru_```
