### ISSUE TITLE
Offline map not rendering.

### ISSUE THREAD

**Issue by moonandroid** [osmandapp/Osmand#1314]
When i'm going to display offline map after download map as per religion.
Every i'm i got error "Error occurred while rendering selected area".
the same issue also taken place in source code also.
Please reply here,it's too urgent work for me.

Thanks in advance.

**Comment by vshcherb** [comment]
Duplicate issue to map not displaying.

**Comment by moonandroid** [comment]
not getting your comment.

**Comment by moonandroid** [comment]
can you please tell me,where is duplicate map ?

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/issues/124

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/issues/1245

**Comment by moonandroid** [comment]
I'm getting toast alert "Error occurred while rendering selected area". getting runtime exception when load map. And native library also could not be loaded.

**Comment by Pandiyanmk** [comment]
did you solved that problem moonandroid . i am also getting the same error.

**Comment by Pandiyanmk** [comment]
I'm getting toast alert "Error occurred while rendering selected area". getting runtime exception when load map. And native library also could not be loaded.

**Comment by Pandiyanmk** [comment]
MapRenderRepositories Runtime memory exception
                                                        java.lang.NullPointerException: Attempt to get length of null array
                                                            at net.osmand.binary.BinaryMapDataObject.getSimpleLayer(BinaryMapDataObject.java:163)
                                                            at net.osmand.plus.render.OsmandRenderer.sortObjectsByProperOrder(OsmandRenderer.java:466)
                                                            at net.osmand.plus.render.OsmandRenderer.generateNewBitmap(OsmandRenderer.java:265)
                                                            at net.osmand.plus.render.MapRenderRepositories.loadMap(MapRenderRepositories.java:792)


the issue i am facing on map zoom out more then 1 km

**Comment by franciskim** [comment]
I have the same issue as @Pandiyanmk

**Comment by Grunsven** [comment]
For me this problem has also started recently (Moto G4).
It makes OSMAnd nearly unusable As I often don't get a map.
