### ISSUE TITLE
Rendering problem - loaded route dissapear from map view

### ISSUE THREAD

**Issue by razor74** [osmandapp/Osmand#1315]
Used the last Osmand + version 2.0.4 .After i loaded a navigation route, the line of the route which is drawed over the road line dissapear from map view  and reapear from time to time. This is annoing because it distract me. I think the navigation is not working in that time... If i have to go trough a roundabout, and i hear navigating instruction but the route not shows it is difficult to understand on which roundabout exit to take. If i completelly stop the car and map is not moving, the route apears again on the map. This is happened from the 2.0.3 and 2.04 versions.

**Comment by vshcherb** [comment]
It will be good to test it on the nightly builds, unfortunately I can't reproduce it in the latest versions.

**Comment by GabrielSebastianMoise** [comment]
I have the same issue. It happened to me while driving from Romania to Greece. Sometime the route line, or all the streets dissapears with no reason from time to time. 
Sometime after, or while it recalculates the route, or sometime when I switch from OsmAnd+ to Camera app to take some pictures, and the navigation remains on background. After switching back to the OsmAnd+, the roads or only the route dissapears, and sometimes don't.
This happened only with the latest version. And with the one before that had a issue with the recalculation of the route.

Samsung Galaxy Note 3 LTE  Android 4.4.2 official ROM. 

Thanks !

**Comment by razor74** [comment]
I will try a nightly builds probably in the next weekend and i'l keep you informed...

**Comment by vshcherb** [comment]
For now issue is not reproducible so there is no action with it, please leave your feedback once you have it. May be you can notice the dependency of zoom in level and route disappear.

**Comment by razor74** [comment]
Tested yesterday with almost the same results on OsmandF~2.1.0.#7740D. The current route dissapear much rare , but dissapear... And this happened after ~ 35-40 Km of driving on the motorway. I disabled auto zoom if this is important...

**Comment by sonora** [comment]
I can confirm that this happens occasionally, using our standard settings (auto zoom ON, etc.) At first I attributed this to the route being recalculated, but maybe it is not... Route always re-appears within a few seconds. So it is almost like a rendering issue.
Not an enormous issue, but a bit puzzling if the route immediately in front of you disappears while you are following it correctly... and yes, bad if you are in a roundabout and more than usual depend on seeing the route.
