### ISSUE TITLE
“Position not yet known. A-GPS data downloaded.” Pixel 4a - LineageOS 18.1 - No Location Services

### ISSUE THREAD

**Issue by l-ucky** [osmandapp/OsmAnd#13157]
### Description
I have been using OSMand on my LineageOS (18.1) Pixel 4a for a long time with minimal issues. Other than general mapping issues (telling me to turn off the highway when there is no ramp) I'm having issues plainly connecting now. When clicking the target icon to get my location, I get the following error: “Position not yet known. A-GPS data downloaded.” I drove around for 5 hours today doing some work and I can't get OSMand to connect to any satellites. I used SatStat and GPSTest which are showing that there are satellites, and I am connecting to them. Likewise, I've dived into hours of reading to see what the problem is. At one website an OSMand user said they had this problem and after doing a factory reset their OSMand location services worked. I tried this as a solution, and it did not work for me. I also tried doing updates on my phone, downloading OSMand directly from their website, from F-droid, and from aurora store. I don't have Google services enabled on my phone. My girlfriend has the same set-up as mine (Pixel 4a, LineageOS, etc) and she doesn't have any issues, we actually used her phone today for mapping. We both have the same OSMand, and lineage versions, just to make things clear. A final detail, OSMand has location details and I have my location turned on while using.

### How to reproduce?
Bugs on launch.

### Your Environment
OsmAnd Version: 4.0.8
Android/iOS version: LineageOS 18.1 / Android 11
Device model: Google Pixel 4a

**Maps used (online or offline):**   
I had the map tell me to turn off the highway today where there was no ramp. However, unrelated because the maps are unusable since I can't locate myself.

**Comment by sonora** [comment]
I can think of 2 things off hand: Firstly, since you do not have google services installed, you should make sure you are using a version of OsmAnd not relying on them. But it sounds like you tried that by e.g. testing the F-Droid version.  Secondly, have you checked that OsmAnd has been granted Location permissiob? (Double-check under Android-Settings/Apps).

**Comment by l-ucky** [comment]
Hey thanks for your quick reply @sonora. Yes, I have the location app permissions set to allow OMSAnd

**Comment by sonora** [comment]
Are you using the exact same **build** (not just version number as in 4.0.8) which works on your girlfriend's phone?

We have a number of issue reports for location issues under Lineage OS, but so far it was my impression those users used a Play Store build (which per google policy depends on google services for their location service) while their phone does not run google services.

There was even one report saying a GPS fix could only be obtained while being connected to WiFi. I could never reproduce and believed it was exactly this "wrong build" issue.

- While you are displaying OsmAnd's map screen, do you see the GPS indicator in the top Android notification bar?
- When in OsmAnd you tap the menu button and activate the "Configure screen/GOS info" widget, it displays the number of visible vs. used satellites on the map  Does it always report 0/0 ?

**Comment by l-ucky** [comment]
Q: While you are displaying OsmAnd's map screen, do you see the GPS indicator in the top Android notification bar?
A: Yes, I have the GPS indicator and it shows 0/0 GPS connections.

Q: When in OsmAnd you tap the menu button and activate the "Configure screen/GOS info" widget, it displays the number of visible vs. used satellites on the map Does it always report 0/0 ?
A: Yes, it always reports 0/0. Sometimes a black bar will appear at the top of the phone screen reading  "searching for connections: 0/0" or something similar.

I looked around the "About" section in the side-bar menu and couldn't find anything relating to a build number. Can you tell me where it is and I'll get it to you? I'm also looking up where it is, if I find it I'll post it.

**Comment by sonora** [comment]
I have fpund these issue reports which are quite similar: https://github.com/osmandapp/OsmAnd/issues/10903, https://github.com/osmandapp/OsmAnd/issues/10637, https://github.com/osmandapp/OsmAnd/issues/11388, https://github.com/osmandapp/OsmAnd/issues/12585.

It seems to me that users reporting issues with the old OsmAnd 3.9 mostly used an OsmAnd build requiring google play services, and were able to resolve this when switching to the 3.9 F-Droid build F-Droid builds their own version using our code).

The last link above contains a comment which may suggest that F-Droid's 4.08 build may contain an issue in connection with LineageOS and Location fixes. If that is true it may be tested if you use our default nightly build from our website, link is in one of the threads I list above. Please note that when switching the build it is likely signed differently, so if it doese not install you need to backup any OsmAnd data  you continue to need (favorites, tracks, etc.), then uninstall your previous OsmAnd version first.

We are currently publishing OsmAnd 4.1.x, maybe as soon as F-Droid updates they also fix the issue, should it be on their side.

**Comment by l-ucky** [comment]
Hey Sonora, thanks for the links I read through them. The nightly build was a little hard to find on the website, but I got it, it was located in the drop-down menu on the downloads page. The Nightly OsmAnd package on my phone worked, and I instantly was able to connect to GPS. I'll keep my eyes out for 4.1.x.

Have a good day!

**Comment by LinuxOnTheDesktop** [comment]
I have an Asus Zenfone 8, nor rooted, and running Android 12. Just now I installed OsmAnd, via F-droid.

I have the problem with the app not detecting my location.

Oher apps can determine my location. I granted OsmAnd permission to use my location. (More precisely, I gave the app permission to access my location whilst the app is running.) OsmAnd says - in the same pop-up that says location data is not yet available - that GPS data was downloaded.

**Comment by scaidermern** [comment]
> EDIT: ah; [this page](https://boringphone.com/knowledge-base/osmandnavigation-position-not-yet-known/) says that OsmAnd may be unable to find location whilst one is inside a building . .

Correct. OsmAnd only uses GPS for determining the location. Various other apps also use mobile networks as additional source and are thus able to determine the location better if the GPS signal is weak.

**Comment by LinuxOnTheDesktop** [comment]
I went outside and pressed the button and no joy there either. At the least, the error message should be more illuminating.

**Comment by scaidermern** [comment]
You may have to wait a few minutes outside. Also please make sure that your GPS reception works with other apps such as GPSTest or SatStat.

**Comment by LinuxOnTheDesktop** [comment]
The 'GPS Fix' app takes a minute or so to get a GPS fix but then does establish one (even though I am inside). OsmAnd seemed never to establish a fix. More, but as I wrote before: OsmAnd's error message should be more illuminating (as indeed should the seeming success message - the message that says that  GPS data was downloaded).

**Comment by s1nistr4** [comment]
Why even make an open source maps apps if it relies on a trojan google backdoor into your os for it to work?

**Comment by scaidermern** [comment]
> Why even make an open source maps apps if it relies on a trojan google backdoor into your os for it to work?

It doesn't. Set the location source to Android API and it will work with GPS only, no Google service required.
