### ISSUE TITLE
Live update (Relation problem) Wrong turn in Kharkiv Ukraine

### ISSUE THREAD

**Issue by ivanPyrohivskyi** [osmandapp/OsmAnd#13152]
<img src="https://user-images.githubusercontent.com/1040293/141285664-9daf7097-815d-4ff7-aecc-f7b68f7ff548.jpg" width="400"/>

Location https://www.openstreetmap.org/way/991626010
Problem detected in live update 05.11.2021
[Ukraine_kharkiv_europe_2.obf.zip from 01.11.2021](https://drive.google.com/file/d/1IfcM_tpq5svRB5Been9ogCsCdamGKyL5/view?usp=sharing)
[Ukraine_kharkiv_europe_19_25.obf.gz from 05.11.2021](https://github.com/osmandapp/OsmAnd/files/7519824/Ukraine_kharkiv_europe_19_25.obf.gz)

**Comment by ivanPyrohivskyi** [comment]
Old problem of relation
Relation was changed https://www.openstreetmap.org/relation/13409909
Member of this relation https://www.openstreetmap.org/way/991626010
Missed relation https://www.openstreetmap.org/relation/13372986

**Comment by jfburke3** [comment]
Perhaps this one should be left alone until after the Russians have been kicked out....

**Comment by ivanPyrohivskyi** [comment]
Map for test:
[Ukraine_kharkiv_europe_2.obf.zip from 01.11.2021](https://drive.google.com/file/d/1IfcM_tpq5svRB5Been9ogCsCdamGKyL5/view?usp=sharing)

Diffs for test:
[Ukraine_kharkiv_europe_21_11_05.obf.zip](https://github.com/osmandapp/OsmAnd/files/10931837/Ukraine_kharkiv_europe_21_11_05.obf.zip)
[Ukraine_kharkiv_europe_fixed_21_11_05.obf.zip](https://github.com/osmandapp/OsmAnd/files/10931838/Ukraine_kharkiv_europe_fixed_21_11_05.obf.zip) (remove "_fixed" before test)

**Comment by ivanPyrohivskyi** [comment]
Problem fixed until April 19 2023.
Live updates will consist of nodes and ways if one of relation that taken these nodes and/or ways was added, modified or deleted.
