### ISSUE TITLE
allow changing the url config of (overlay) tiles in the app

### ISSUE THREAD

**Issue by HolgerJeromin** [osmandapp/Osmand#1317]
It would be nice, if i would be able to view and change (correct for #1316 ) the urls from an online tile service.
Right now i am only able to rename and delete ist.

**Comment by vshcherb** [comment]
Map Source ... -> Define/Edit

**Comment by HolgerJeromin** [comment]
Oh, thank you!
There is no hint visible on my phone that i can click on the empty space next to the small text:
![screenshot_2015-06-09-09-10-13](https://cloud.githubusercontent.com/assets/2410353/8052931/5dd23726-0e8c-11e5-99c3-729e4298b485.png)
