### ISSUE TITLE
No gps location

### ISSUE THREAD

**Issue by unnamed777** [osmandapp/OsmAnd#13170]
### Description
I have a bike computer, which is based on Android 8.1.0, and I use OsmAnd on it. Recently I've updated the app to 4.0.8 (the latest on ApkPure) and it stops showing my location. When I tap on "my position" button, it always shows a toast "Position not yet known. A-GPS data downloaded: ...current date...". I cleaned cache and data, reinstalled it, no changes. First time after installation the app asks a permission to use location services, but I don't see location icon in the statusbar (in other works, location isn't used). I've tried different versions of the app from ApkPure and found out, that the last version of the app, where "my position" is working, is 3.8.3. On 3.9.4 and newer versions I have the same issue.

I'm not sure if it helps, but I record adb logcat output (openning the app and several taps on "my position" button) -
[log.log](https://github.com/osmandapp/OsmAnd/files/7533777/log.log)

### Your Environment
OsmAnd Version: 4.0.8 (ApkPure)
Android version: 8.1.0
Java VM: 2.1.0
Kernel: 3.18.71-perf-gf487319
Device model: Hammerhead Karoo 2

**Comment by scaidermern** [comment]
Is this a device with Google PlayServices? If not, you need the OsmAnd version from the F-Droid store. Newer OsmAnd versions require Google PlaySevices to obtain location information.

**Comment by sonora** [comment]
Sounds similar to https://github.com/osmandapp/OsmAnd/issues/13157.

**Comment by unnamed777** [comment]
Thanks, version from F-Droid solved the issue.

**Comment by morph027** [comment]
Sorry for bumping this old issue, but i'm encountering the same. Installed via F-Droid and only gets the `Position not yet known. A-GPS data downloaded: ... ` toast

**Comment by morph027** [comment]
> Have you verified that under "Android / Settings / Apps / OsmAnd / Permissions" the location permission is granted to the app?

Yes, the permission is granted.

> And in "OsmAnd / OsmAnd settings / Location source" tried both the Android API and Google API option?

There is no such setting on this device :shrug: I can find it on my mobile phone, but not on the Karoo.

**Comment by scaidermern** [comment]
> > And in "OsmAnd / OsmAnd settings / Location source" tried both the Android API and Google API option?
> 
> There is no such setting on this device 🤷 I can find it on my mobile phone, but not on the Karoo.

This setting is only present in the playstore version. The F-Droid version doesn't have this setting and always uses "Android API" as location source.

**Comment by sonora** [comment]
When you display OsmAnd's GPS widget on the map screen, does it show satellites being used?

**Comment by morph027** [comment]
Hm, weird, now it works. Only thing I did was starting the built-in map app before which git a fix then. Will have a closer look.
