### ISSUE TITLE
Map above keyboard when adding or editing POIs

### ISSUE THREAD

**Issue by mmh-dev** [osmandapp/OsmAnd#13186]
### Description
when adding new POI to favorites or editing it, a map appears above keyboard.

### How to reproduce?
Choose a Location - > add to favorites

### Your Environment
OsmAnd Version:
Android/iOS version:
Device model:

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by alex-osm** [comment]
Where is PR link?

**Comment by vshcherb** [comment]
4.1.8 will be present
