### ISSUE TITLE
Search for "Closest POI" now seems to be gone (version 2.0.4)

### ISSUE THREAD

**Issue by martenjj** [osmandapp/Osmand#1319]
Some versions ago - possibly before the big rewrite for 2.0 - it was possible to select a point (e.g. press on map -> click on popup -> Search near here) and in the POI search there was an option for "Closest POI".  This was useful in two cases:  (a) finding out what a map symbol indicated if the user was not sure what the symbol represented;  (b) if the POI type was not in the default list.

Now this function seems to have disappeared.  The nearest option to it seems to be "Search by name", but that will not accept a null string to search on everything and will never find an unnamed POI.

If this function could be restored then it would be much appreciated!

**Comment by vshcherb** [comment]
Duplicate issue. Short answer: create a custom filter for that.

**Comment by martenjj** [comment]
Thanks for the pointer, setting a custom filter seems to do exactly as before.  Apolgies for the duplication...
