### ISSUE TITLE
wish: show road information even when not navigating

### ISSUE THREAD

**Issue by martenjj** [osmandapp/Osmand#1320]
Most car satnavs, even when no navigation is in progress, display the current road name and its speed limit, continuously updated.  It would be nice if OsmAnd+ had such a feature too.

Obviously this would drain battery power and hence turning this tracking on should be optional.

**Comment by vshcherb** [comment]
If you change app mode, you will see it there. It is not so good as navigation, because road approximation is worse and prediction of the next turn is not technically not possible.

**Comment by martenjj** [comment]
Thanks for the pointer... had looked for a setting under "Map layers" and "Configure screen", but didn't realise that additional settings would appear when changing the map mode.
