### ISSUE TITLE
mistakes in travel guide docs

### ISSUE THREAD

**Issue by mariush444** [osmandapp/OsmAnd#13205]
web page:
https://osmand.net/features/travel

there is `Run ./utilites.sh travel-guide-creator`
should be `Run ./utilities.sh travel-guide-creator`   missing **`i`**

There is:
`We do not recommend locating your files in the 'TravelGuideCreator' folder itself. Kindly see the 'Read me' file for step-by-step commands.`
Where is `Read me` ?

There is:
`Your file should be created in seconds. By default, it will be named 'travel_guide.sqlite', but`
but currently OsmAnd MapCreator 3.0 creates `.obf` file (NAME.travel.obf)

Some more 
![image](https://user-images.githubusercontent.com/66887280/142497812-be2b4db0-91a2-42db-8a6d-7be231a71f97.png)

**Comment by vshcherb** [comment]
This is deprecated documentation, planning 1 January 2022 switch to https://docs.osmand.net/en. Indeed obf is new format for travel guides
