### ISSUE TITLE
wrong rendering of raster maps for map magnifier > 100%

### ISSUE THREAD

**Issue by mariush444** [osmandapp/OsmAnd#13204]
When the underlay/overlay map is used (raster maps)
at the same time with obf (vector maps) then there is problem with rendering.

This is view when map magnifier is set to 100% (view is OK)

![Screenshot-mm75](https://user-images.githubusercontent.com/66887280/142462852-6efaf887-d6ee-4368-a0ce-aca309784a4e.png)

This is the view when map magnifier is set over the 100% (e.g. 300%) 
Then we can see that rendering is not good. (less details is not problem but rendering)

![Screenshot-mm300](https://user-images.githubusercontent.com/66887280/142463180-15169afd-225c-4a1c-8f29-fc928895e331.png)

I think that for magnifier > 100% when the underlay/overlay is used
the raster maps should be rendered as for magnifier = 100%

### Your Environment
OsmAnd Version:3.9.10, 4.0.9
Android/iOS version: 8.0.1, 11

**Comment by vshcherb** [comment]
This is definitely confusing area. I know people use magnifier for raster online maps or special paper maps, with underlay / overlay we need to have separate magnifier otherwise it's very confusing.

**Comment by mariush444** [comment]
@vshcherb  - just idea
I'm not programmer and I don't know source code but
maybe you don't need 2 separate magnifiers.

If the layers are dynamically rendered then let's say we have magnifier_zoom (defined in menu)
so ...
layer_zoom_vector=magnifier_zoom (no changes in current code)
layer_zoom_raster=if(magnifier_zoom>100%) then 100 else magnifier_zoom

**Comment by vshcherb** [comment]
Then it's not consistent and you can't use overlay / underlay. If it's only 1 layer than map magnifier should be setup as it seems to be the best fit text ration vs screen resolution and after that zoom in & zoom out should be used.

I would say this topic belongs to discussion and nothing to be fixed here: only docs should be improved
