### ISSUE TITLE
Links to the OSM and phone numbers do not work

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#13215]
In the description of the object OSM no longer works links to it and the dialer.
What's interesting, the link to the organization's website works.
In Osmand version 4.0.8 everything works fine.

https://user-images.githubusercontent.com/12549744/142729292-27019ac5-025c-4bff-ad82-2a6b8faa4579.mp4

OsmAnd Version: OsmAnd~ 4.1.0#33095m, дата выпуска: 2021-11-19
Android: 11
Device model: poco x3 pro

**Comment by vshcherb** [comment]
![telegram-cloud-photo-size-2-5237738692674697350-y](https://user-images.githubusercontent.com/1042025/142889127-e8e555b1-82aa-41b4-b264-eeebd838f929.jpg)
