### ISSUE TITLE
waypoint colour not saved/loaded correctly in favourites.gpx

### ISSUE THREAD

**Issue by martenjj** [osmandapp/Osmand#1321]
It is possible to set a waypoint colour in the favourites.gpx file, although the app's GUI only supports setting a colour for folders and there only certain preset colours.  However, if certain RGB colour values are set in the GPX file they are not saved and reloaded correctly between runs of OsmAnd+.

Delete all of OsmAnd+'s "My Favorites" and their containing folders, so starting with an empty list.  Then exit the app and save the following file as /sdcard/osmand/favourites.gpx:

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<gpx xmlns="http://www.topografix.com/GPX/1/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <wpt lat="48.229336" lon="7.406588">
    <name>Test Waypoint</name>
    <type>Transport</type>
    <extensions>
      <color>#0000ee</color>
    </extensions>
  </wpt>
</gpx>

Then start OsmAnd+ again.  The waypoint will appear in the list and on the map with a blue colour, as expected.

Exit OsmAnd+ and run it again, note that the waypoint and folder colours have changed back to the standard '#eecc22'.  The favourites.gpx file on the device will have changed to:

<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<gpx version="1.1" creator="OsmAnd+" xmlns="http://www.topografix.com/GPX/1/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
  <wpt lat="48.229336" lon="7.406588">
    <name>Test Waypoint</name>
    <type>Transport</type>
    <extensions>
      <color>#ee</color>
    </extensions>
  </wpt>
</gpx>

Note that the <color> value is truncated.

If this test is repeated with a colour value that will fill up 6 hex digits, for example '#ee0000', it will display correctly (with the expected red colour) within OsmAnd+ and persist properly between runs of the app.

Suspect that the GPX parsing only recognises a full 6 hex digit colour specification, in which case it needs to be written out in a compatible format.

**Comment by martenjj** [comment]
Looks like github has mangled the < and >s in the example files, so here they are again with the offending characters replaced by the corresponding [] brackets.

File that causes the problem:

[?xml version="1.0" encoding="UTF-8" standalone="no"?]
[gpx xmlns="http://www.topografix.com/GPX/1/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"]
  [wpt lat="48.229336" lon="7.406588"]
    [name]Test Waypoint[/name]
    [sym]Restroom[/sym]
    [type]Transport[/type]
    [extensions]
      [color]#0000ee[/color]
    [/extensions]
  [/wpt]
[/gpx]

File that works correctly:

[?xml version="1.0" encoding="UTF-8" standalone="no"?]
[gpx xmlns="http://www.topografix.com/GPX/1/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"]
  [wpt lat="48.229336" lon="7.406588"]
    [name]Test Waypoint[/name]
    [sym]Restroom[/sym]
    [type]Transport[/type]
    [extensions]
      [color]#ee0000[/color]
    [/extensions]
  [/wpt]
[/gpx]

**Comment by vshcherb** [comment]
OsmAnd supports only 1 color per favorite group that's why it tries to select 1 color per group. You can create separate group per color.

**Comment by martenjj** [comment]
I know that only one colour per group is supported, but this issue is not about that.  The problem is that even if only one waypoint is present (therefore by implication only in one group), the colour setting is not saved and loaded correctly between restarts of the app for certain RGB values.

**Comment by vshcherb** [comment]
Need to review it. Does it work when you change on UI?

**Comment by martenjj** [comment]
Changing colours using the GUI works as expected.  But the colours available there (from the 'pallette' array in OsmAnd/OsmAnd/src/net/osmand/plus/helpers/ColorDialogs.java) may not trigger the bug - all of them have a full 6 digit RGB value and so will be written out without truncation.

**Comment by vshcherb** [comment]
Please test it, it was related bug fix

**Comment by martenjj** [comment]
Tested on nightly 2.1.0#11590M.  Appears to be fixed - many thanks!
