### ISSUE TITLE
Concave polygon not being rendered

### ISSUE THREAD

**Issue by adrian5** [osmandapp/OsmAnd#13229]
### Description

OsmAnd does not render the concave shape (blue) of a `mist` type fountain. This may be intentional (treating fountains as point objects), but I thought I'd mention it.

Below a screenshot from the OpenStreetMap.org editor (the map view doesn't render the fountain either):

![convex-fountain](https://user-images.githubusercontent.com/5426924/142886039-bdcc7d8e-dea5-440b-aba2-7d3584ad92e6.jpg)

Two other map apps I tried ([Organic Maps Offline](https://organicmaps.app/), [HERE WeGo Maps & Navigation](https://play.google.com/store/apps/details?id=com.here.app.maps)) render the shape convincingly.

### Environment

OsmAnd~ 4.0.9
Android 11

**Comment by vshcherb** [comment]
Please share OSM location where it happens.

**Comment by adrian5** [comment]
The feature is located at `51.59752, 6.68116`
