### ISSUE TITLE
A few suggestions :)

### ISSUE THREAD

**Issue by aaronstar** [osmandapp/Osmand#1322]
Hi all,

I have a few suggestions/issues from my use of Osmand
(sorry I don't know how to code them or I would've tried)

1.) Cancel a destination after a period of time has elaspsed or the application has been closed for a certain amount of time or the application has been closed. (Alot of the time I don't actually navigate to the desitination but just use it to get an idea of directions, or for mapping issues etc., therefore the route is not cancelled, and there are quite a few clicks required to cancel the route) Other times I may not reach the destination but park nearby or likewise... still have to cancel the route 

Note: People may be travelling a longer route or something with multiple waypoints etc. and as such the app may be closed for a period of time. Maybe leave it in navigation mode or similar until such a time as the user cancels? I'm not too sure

2.) "You have exceeded the speed limit" Should become say: "Speed limit [maxspeed] [units as a word]" E.g.: "Speed limit eighty kilometres per hour". It may be accompanied by a repeating short-ding or similar and repeating "speed limit XXX" Current wording is a bit too agressive or offputting. Further there may be an option to adjust when the speed limit warning occurs.

3.) Destination (address) announcement had  the street number (determined by a building in OSM) announced after the street name  it said you have reached you destination (or somthing like that) George Street 4 (instead of you  have reached your destination [pause] 4 George Street (Further announce the localitiy if possible?)

There also may be pedestrian crossing issue:
 - re highway=crossing, crossing=unmarked
being announced when it shouldn't be

I'll investigate once a map edit makes it way through and get back to you

Regards,
aaron

**Comment by aaronstar** [comment]
Hi there, in regards to point 2.) I found in the menus the option to change this alert, it was not however intuitive - anyway thanks!

**Comment by sonora** [comment]
Ad 1) I feel implementing this will not be very obvious, and overall obscure how the app behaves.
Ad 2) Deprecated
Ad 3) Different regions have different conventions here, so this may be very hard to improve
Ad 4) Deprecated, I think
