### ISSUE TITLE
Some Remarks on Elevation Change and Sampling Theory

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#13224]
Looks like in https://github.com/osmandapp/OsmAnd/commit/ae36090a90b7dfc3cb71a7e08071c383992cf1ef we are experimenting with changing how we approximate elevation change. Here some basic aspects of sampling theory and size effects which should be understood before changing the algorithm:

I enclose below the elevation profile of a mountaineering trip recorded during an actual hike and climb.

- The first screenshot shows the elevation profiled as recorded. There is an ascent, over boulders and gullies, from about 2500m to the summit at about 3500m, then descent to the base camp at about 1400m.
- Not that the recording exhibits an (a priori unknown) mixture of 'true' undulations and noise.
- The next (dark) screenshot shows the uphill/downhill values as calculated with my old, 5m-threshold trend channel algorithm, i.e.  ignoring each undulation of 5m and less. This is the method we have in place up to OsmAnd release 4.0.x). It approximates ascent as experienced by the hiker at **1673m** and descent at **2717m**.
- The bright screenshot shows the result of commit https://github.com/osmandapp/OsmAnd/commit/ae36090a90b7dfc3cb71a7e08071c383992cf1ef, and exposes an alleged **5075m** up / **6136m** down.

![1](https://user-images.githubusercontent.com/845735/142764086-e5576dcc-3c59-473b-8cb5-0ffc5ff69112.png)
![2](https://user-images.githubusercontent.com/845735/142764090-f72d0ee2-de5d-481c-957e-d3a476d06cc6.png)
![image](https://user-images.githubusercontent.com/845735/142764235-d66672c1-0e6b-4cbd-82fa-569de7ab56b8.png)

**When you re-visit the algorithm, I advise to study two things up front:**

**(1) Sampling rate effects**: An algorithm should not introduce a big positive correlation between sampling rate and estimated elevation change to the effect that e.g. how many and how close points are being taken into account affects the outcome more than the actual terrain.

**(2) Sizing and noise effects:** The elevation gain felt by a hiker is vastly different from e.g. that by an ant taking the same trip, because an ant will have to climb every pebble which a hiker will simply step over. Meaning you need to apply a low-cutoff for all undulations. The value to select for the cutoff depends on both the typical undulation of the effect you are trying to observe (size effect: ant vs. hiker), and also on overall measurement accuracy of your signal vs. noise (which depends on many factors, but limited by typical GPS reception).

**Comment by pebogufi** [comment]
There is a static method called moving average to reduce such unwanted noise, example like the ants hiking experience against to a human hiker.

**Comment by vshcherb** [comment]
It's pretty hard in theory but in practice turns to be pretty simple according to GPX I've got and tested.

In practice you always would like to remove "Noise" and try to find out "what's not needed". We're going to solve this *manually*, 

For example, I've got pretty noisy GPX, where outliers happened every 100m and they are off by +-20m up or down and to be honest simple averaging algorithm solves it pretty accurately and the result is adequate. By varying smooth-window:
Window | Uphill
----------------
0 | 16103.2
10 | 3131.24

15-40m the result doesn't change dramatically but

**Comment by sonora** [comment]
Well, in that spreadsheet things look nice, but it addresses a really high sampling rate of 1 point per 5 horizontal meters. This is the same order of magnitude as typical GPS hdop, hence must be considered oversampled in the horizontal dimension (for the distance calculation)  unless post-processed by Douglas-Peucker or similar.

In many use cases you will be facing much smaller sampling rates, like one per 50 -100 horizontal meters. Then you have much less data to play with, and sliding averages over several points could then quickly mean averaging rather long distances of half a kilometer or more. That's why I once resorted to trend-channel in the vertical dimension, rather than sliding average in the horizontal dimension.

When you look at it: The only weakness  in the trend channel approach is outlier control. So if we wanted to improve, I would advise to somply look at e.g. Douglas-Peucker or something similar as pre-processing, then still use trend channel. Chances are that would produce best-in-class GPS elevation change approximation, putting as well ahead of the many amateurish apps and approaches out there... 😉

**Comment by vshcherb** [comment]
@sonora please share the track somehow, so we could test it.

 Douglas-Peucker is bad approach cause it's designed to simplify geometry and not filter out height-specific outliers, the best approach so far actually to not use altitude only from GPX and use it from DEM-data where for we have "given resolution" of 1-5m per pixel, this data is smoothen enough and this would allow to remove outliers easily. 

Even though I think we will implement this algorithm online (or somehow offline with tons of downloaded data), I would like to have something simple. As usual we can talk about same algorithms and their combinations, though I'm always looking to find 1st algorithm that gives the highest precision and only after that make ensemble of other approaches. So far I'm optimistic about 20-m window approach but anyway I would like to create a collection where it doesn't work, so algorithm improvement process will look more systematic.

**Comment by vshcherb** [comment]
P.S. I'm not sure that OsmAnd has right implementation of algorithm yet, that needs to be tested ;-)

**Comment by sonora** [comment]
I PM'ed some test tracks. I propose that as a sanity check essentially the user expectation is:
- (1) When you walk the waterline of a lake, reported elevation gain must be zero.
- (2) When you hike up a mountain starting at 1000m elevation and peaking at 1500m, and the trail keeps sloping uphill with no noticeable dips, elevatiom gain must be reported at 500m.
- (3) As a result, there is a 'noticeability' or 'significance threshold' for any 'dips' to be added to that value. Adding up thousands of small undulations of 20cm each up and down certainly defies the purpose, same as adding up GPS measurement noise.
- (4) That must be reported without the user having to prameterize anything.

Slope is an even trickier animal, because it is the ratio of 2 such fuzzy (uncertain) values, hence it will always be risky to base decisions (like: "Can my truck make it?") on that.

**Comment by vshcherb** [comment]
Slope vs uphill is actually the same. Same techniques should be applied uphill = integral over slope. With noise 1st derivative doesn't exist and though uphill exists is completely irrelevant, because we assume that Earth has 1st smooth derivative unless a free fall.

Agree:
(2) - that's focus of all requests we're getting on support 
(3) - algorithm behind the scenes using 20-m window, not 20-cm. So it shouldn't be a problem
(4) - agree, cause we can't explain what's the parameter mean anyway

Don't fully agree
(1) - You can't walk on the lake cause it has wave / interference. Even with flat Netherlands I see a lot flatenning done in most of Satellite imagery but in reality nothing is flat. I would say it's a matter of how exactly you measure: 10m uphill/downhill for 10 km is fine for most flat areas. Please keep in mind it's also a matter of GPS-altitude GEOID-model. 

Slightly other direction:
- Before I have tried algorithms and I've think that what you've implemented as well, algorithms similar to Kalman-filter, like you have the signal and you predict where it goes and skip the point. To be honest I don't like them anymore, they remove too much noise or too few noise. With aggressive settings they've almost always produce totally flat for my tracks, essentially they can't produce fractional uphill 0.1 - 0.5 m but the noise of GPS-signal could be used to get this information actually.
 

Attaching noisy tracks (2nd use case):
[2018-07-08_07-50_Sun.gpx.zip](https://github.com/osmandapp/OsmAnd/files/7577326/2018-07-08_07-50_Sun.gpx.zip)
[2021-09-22_08-13_Wed.gpx.zip](https://github.com/osmandapp/OsmAnd/files/7577327/2021-09-22_08-13_Wed.gpx.zip)

**Comment by vshcherb** [comment]
P.S. to measure slope properly and catch it properly for 10-20m, you just need a lot of points even if they are good almost every 2m, but I don't think we have that goal here.

**Comment by vshcherb** [comment]
Original track data:
100m window: <img width="403" alt="Screen Shot 2021-11-22 at 10 18 35" src="https://user-images.githubusercontent.com/1042025/142835173-4b52ddaf-4de7-4f06-9519-a17be4516e1c.png">


Window | Uphill | Downhill
--  | -- | --
25 | 5074.65 | -6137.15
30 | 4728.27 | -5799.77
50 | 3230.45 | -4281.45
75 | 2179.10 | -3224.94
100 | 1672 | -2717.88

**Comment by sonora** [comment]
See how sensitive it is to what you call "Window". That's what I called "positive correlation" in my first post above. The mistake is to introduce a horizontal "window" here at all, it's irrelevant.

All you need to do is **look at the vertical dimension**, and define which undulations you are willing to count vs. which you are willing to neglect. My current algorithm sets that cut-off to 5 (vertical!) meters, in other words: "All variations of less then overall 5m before a trend reversal are considered irrelevant or noise." (There is no need to distinguish between "irrelevant" and "noise" ).

**Comment by vshcherb** [comment]
@sonora we introduced algorithm how to correctly determine window size by points in GPX file, so it finds good window for tracks we have.

**Comment by sonora** [comment]
@vshcherb Victor, quick question: I re-ran some tests with the latest build and have to say I am impressed, the elevation gain/loss results come out a lot more plausible now.

I have, however, encountered an oddity in connection with e.g. the very track of my two screenshots in the original post above: The latest version of the app seems to somehow use a simplified or modified version of the track data not just for elevation gain or loss, but also for other stats. E.g. the track distance, which came out as 24.0km in both the v4.0x and v4.1.x screenshots above now with the latest nightly build comes out as 21.9 km. Other data like average speed, time span etc. is also affected. Possibly a bug? Or on purpose?

![Screenshot_20211212-192337_OsmAnd~](https://user-images.githubusercontent.com/845735/145724690-e7a90164-d190-48b6-9746-b089124f81a3.jpg)

**Comment by vshcherb** [comment]
GPS filter applies to the **points** (exclude points by filter). So it affects everything basically.

Since I've managed to have anonymized data, I would post some screenshots here.
**Packraft.**
<table>
<tr>
<td colspan="2">Raw uphill +793m<img width="800" alt="Raw - +793" src="https://user-images.githubusercontent.com/1042025/146042559-efb23f70-a475-476f-bbf3-2b0096cd8283.png">

<tr>
<td colspan="2">Window 50m - uphill +363m <img width="800" alt="Window 50 - +363" src="https://user-images.githubusercontent.com/1042025/146042574-7bc528ab-e8cf-474b-a782-f2161677a0a9.png">
<tr>
<td>Window 200m - uphill +130m<img width="500" alt="Window 200 - +130" src="https://user-images.githubusercontent.com/1042025/146042576-5120bde9-ef9d-4cad-8391-b01bea59b60f.png">
<td>Window 400m - uphill +52m<img width="500" alt="Window 400 - +52" src="https://user-images.githubusercontent.com/1042025/146042578-84db4cf0-a7af-43de-b30e-296846a449a1.png">
<tr>
<td colspan="2">Segment (1.5km) Raw - +98m: <img width="800" alt="Segment Raw - +98" src="https://user-images.githubusercontent.com/1042025/146042565-7cd51994-b7f9-428d-b06b-25aba0e9c2a8.png">
<tr>
<td>Segment (1.5km) Window 50m - +37m: <img width="500" alt="Segment Window 50 - +37" src="https://user-images.githubusercontent.com/1042025/146042566-0d70e831-18bd-463e-b587-fe48e5088728.png">
<td>Segment (1.5km) Window 200m - +8m:<img width="500" alt="Segment Window 200 - +8" src="https://user-images.githubusercontent.com/1042025/146042569-29cbe00d-09be-4a76-91ac-9cf724a9aeae.png">

</table>

**Comment by sonora** [comment]
Hi Victor, I think this is the entire "Packraft" track, right? Maybe we should repeat the analysis with a "watertable only" section so we know the relief variation will be almost  negligible and we can assume all recorded variations are noise and GPS drift?

**Comment by sonora** [comment]
Regarding pur separate exchange: Yes, you are right Victor!  We are looking for a primarily simple solution. I had only mentioned (discrete) Fourier transform because our issue at hand here is precisely in the frequency domain: Fast variations are likely noise or artifacts, slow variations more likely relief-related.

Overall,  we are currently re-iterating the entire train of thoughts I had 10 years ago (or whenever I had implemented version 1 of our algorithm), the key points being 
- that we have limited data to play with
- which is very inconsistent due to user logging habits and also device-specific weaknesses and flaws
- we need an  algorithm which is offline and simple (users looking for something very specific should turn to expert post-procesing elsewhere)
- and the algorithm should be intelligible, i.e. it should be easy to explain to users what exactly we do why they see a particular result (maybe in the presence of certain artefacts)

That's how I had once arrived at saying **"I simply add up elevation trends, and neglect any trend which does not sum up to at least 5m before a turnaround)"**.

I would guess that if we stay with the version 2 algorithm, we should now likely work on that last bullet and find an user-intelligible statement (equivalent o the one for version 1 in bold) explaining what we do now, just so it does not appear as 'arbitrariness'?

All in all, with the communicated weakneses, I could live with version 2, but like several users UIwould like to understand what it does so I can judge where and how it may fail.

I am currently particularly concerned with us recently applying some track simplification by default which does not only cater for a better interpretation of elevation gain (GPS elevation gain is per design less reliable), but we now also apply it to distance and speed data, where I am less convinced it makes sense or even constitutes a valid improvement?

**Comment by vshcherb** [comment]
1. Yes, but Fourier analysis is perfect when we have as a result "periodic" functions such as sound or other waves (even JPEG is good cause it's a light). 
2. Indeed we're reiterating ```10 years``` experience of algorithm full of tweaks and testing. And main reason cause it's not self-explanatory and it has a cost (every issue with right / wrong altitude hard to explain what's the simple situation)
3. > I simply add up elevation trends, and neglect any trend which does not sum up to at least 5m before a turnaround)". 
Sounds good and simple! But completely doesn't take into account scale (main concern), so algorith doesn't distinguish 1m per GPS point or 100m per GPS point. I don't see how it could be improved with scale cause we can miss steady but very slow uphill (typical ground situation).
4. > with us recently applying some track simplification
That's not an issue with rich by data point tracks. On average (we know it by SRTM data) 5m data points are good enough to estimate "expected uphill / downhill", 1m precision is good but can produce quite a lot of noise so we're careful with such DEM data. I think "simplification" to certain degree not a problem. Though without enough data points it's not a silver bullet of course.

For tracks 50m per point we still struggle with 2 main issues: relief could vary a lot / still could be a lot of noise there. 


P.S.: I do like idea of pure trend approach (control point **minimum step** - calculate uphill by steps of 5m), problems:
- scale as not part of formula
- noise ? if noise exceeds 5m, how to skip this points cause it will form noise trends?
