### ISSUE TITLE
Android Auto internal crash issue

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#13236]
Device OnePlus 6T (Android 11).
Issue description:

 I enabled the app to appear in the Android auto launcher, and once I plugged the phone into my Citroën Berlingo Puretech 2021 it appeared on the screen.
I was able to set my destination based on an address that I had searched for earlier (before connecting to the car) and to start the drive.
Voice commands did not came up immediately, it took a few moments before the voice was activated.
During the drive (about 25 mins from home) the navigation instructions "died" and Osmand returned to showing the current position on the map but with no directions on how to get to my destination. I had to click on the search and reselect the destination from the previous history and start the navigation again. This cycle happened 3 times in 25min.

**Comment by vshcherb** [comment]
We're investigating it with 4.1.9 crashes and hope to provide fix with 4.1.10.
