### ISSUE TITLE
"Magnetic bearing" is unclear

### ISSUE THREAD

**Issue by grothesque** [osmandapp/OsmAnd#13239]
I am unable to find out what "magnetic bearing" really means in osmand.  I tried searching the documentation, the web, and this issue tracker.

Conventionally, "magnetic bearing" means bearing that is relative to magnetic north.  If this is indeed what it means in osmand, the application must have an idea of the local magnetic declination which can be quite sizeable (for example in North America).

If, on the other hand, "magnetic bearing" is just a term that is used to differentiate from "relative bearing", I would suggest renaming it to "absolute bearing", which is the proper English term.

It would be still useful to have proper magnetic bearing available for people who would like to use a compass along osmand.  It would be also nice to have bearing relative to a grid (like the UTM grid), because this is what is found on maps.  This would allow to take a bearing with the app (perhaps to some remote destination), and then take it over to a local paper map.

**Comment by grothesque** [comment]
I cannot imagine how osmand's "magnetic bearing" could be relative to what the device's magnetic sensors measure.  For example, I am now sitting in a room.  With osmand set to "straight line" navigation, I choose some destination.  Osmand indicates a magnetic bearing of 34 degrees.  My phone indeed has magnetic sensors, but unless the device is moving, it has no way to know how the local magnetic field relates to geographic directions.

There seems to be an [android API for declination](https://developer.android.com/reference/android/hardware/GeomagneticField).  Perhaps osmand is using it?  Then I think that mentioning somewhere briefly that "magnetic bearing" indeed takes local declination into account, would be useful.  Because otherwise it is surprising that the app can show relative and magnetic bearing, but not absolute bearing.  Or, even better, if absolute bearing could be added as an option along relative and magnetic, there would be no doubt in the first place.

**Comment by sonora** [comment]
@grothesque _Local magnetic north, relative to the device orientation, is derived by a 3D evaluation of the local magnetic field as measured in 3 perpendicular dimensions, you can read this up elsewhere._

Regarding the issue at hand: These are the bearing types in play:

1. **"True bearing"**: The horizontal angle between the direction to a target point and true north as the a reference direction.
2. **"Magnetic bearing**": This is the direction you would have to follow to this target **when using a magnetic compass**. It is a rather similar number in most places on earth, if e.g. TB is 45 degrees, MB could be 47 degrees.

I think that (1) and (2) is what our Bearing widget means to display. _[While there is also (3) **"Relative bearing"** (measured vs. your own direction of motion), and (4) "your own direction of motion (vs. true or magnetic north)", as is requested in e.g. #7282.]_

The local deviation between true north and magnetic north is called Declination, and OsmAnd obtains it, see here https://github.com/osmandapp/OsmAnd/blob/2b0269b48877746f045117293f92b356a396c650/OsmAnd/src/net/osmand/plus/OsmAndLocationProvider.java#L551

- **(A)** It seems to me our "Bearing" widget in mode "**Relative bearing**" may actually display (1). (The values look ok, but need to double-check if this is not the magnetic value, though.)
- **(B)** I think our "Bearing" widget in mode "**Magnetic bearing**" means to report (2), but it does not: It instead reports where the device points relative to the target, to the effect that if (by magnetic orientation) the device seems to point towards the target, the displayed value is zero degrees. 

(B) should not be too complicated to fix, it is simply a shift in reference system. (And it would solve #10220.)

**Comment by grothesque** [comment]
> @grothesque _Local magnetic north, relative to the device orientation, is derived by a 3D evaluation of the local magnetic field as measured in 3 perpendicular dimensions, you can read this up elsewhere.

I understand that magnetic north, relative to the device orientation, can be obtained from the local magnetic field as measured by the sensors.  However, this is of no importance here.  At least on my device, the value that osmand displays for "magnetic bearing" does not depend on device orientation.

>     2. **"Magnetic bearing**": This is the direction you would have to follow to this target **when using a magnetic compass**. It is a rather similar number in most places on earth, if e.g. TB is 45 degrees, MB could be 47 degrees.

The declination varies quite a lot across the globe. see [this map](https://en.wikipedia.org/wiki/File:World_Magnetic_Declination_2015.pdf) for a visualization.  For example, on the US west coast it's more like 10 degrees.  In eastern South America it's more like 20, just like in South Africa.

>     * **(A)** It seems to me our "Bearing" widget in mode "**Relative bearing**" may actually display (1). (The values look ok, but need to double-check if this is not the magnetic value, though.)

On my device, "relative bearing" clearly depends on the direction of the arrow that represents the device.  With a target towards geographic north it can display all kinds of values.  It clearly does not correspond to "true bearing".

>     * **(B)** I think our "Bearing" widget in mode "**Magnetic bearing**" means to report (2), but it does not: It instead reports where the device points relative to the target, to the effect that if (by magnetic orientation) the device seems to point towards the target, the displayed value is zero degrees.

I did a test.  Where I live declination is currently 2.38°.  The true bearing from my current location to a well-known point that is about 20 km off is 37.92° (I measured this using https://geoportail.gouv.fr/).  As such, the magnetic bearing is 35.54°.  Osmand displays 35°.

-------

I suggest adding adding a "true bearing" option in addition to "relative bearing" and "magnetic bearing" in order to make it the different variants self-explaining.

**Comment by sonora** [comment]
We're totally on the same page except I made a mistake in my 2 posts above and somehow managed to reverse the 2 behaviors of our bearing widget. Apologies! I do not think there is a bug, likely I simply touched it and then it toggles between "magnetic bearing" and "relative bearing".

Here is the corrected version:

**(A)** Our bearing widget in mode **"Magnetic bearing"** displays bearing to target vs. magnetic north, and indicates this by showing e.g. "**267° M**". This is the absolute bearing, i.e. independent of device orientation or device direction of motion.

**(B)** Our bearing widget in mode "**Relative bearing**", at least with the device at rest, reports the orientation of the device's primary axis vs. the target, e.g. pointing to the target means "zero". Hence this is actually "relative magnetic bearing".
**(B1)** It seems to me from the code that when your device is in motion, this relative bearing actually becomes based on GPS, and hence would then be "true relative bearing". To test: If this is true, the value in motion would actually become independent of device orientation (have not tested yet).

If things are how I describe them here, I would say there is no need for action, it seems fine to me?

**Comment by grothesque** [comment]
I also made a mistake in my first post where I used the term "absolute bearing" when I actually meant "true bearing".

So indeed, everything seems correct in osmand in that both "magnetic bearing" and "relative bearing" are what they should be.

Still, I found it very surprising that magnetic bearing is present when there's no way to indicate the (arguably more important) true bearing.  This is what gave me the idea that "magnetic bearing" might be used as a label for true bearing.

I suggest the following:

- Correcting the documentation.  Currently [it says](https://docs.osmand.net/en/main@latest/osmand/widgets/nav-widgets#bearing) "Magnetic bearing is the clockwise angle between north and a target point observed from your location." which, as we have seen, is not true.  It should be stated clearly that magnetic bearing is the angle between *magnetic* north and the target, and that declination is corrected for according to World Magnetic Model. (This is what `GeomagneticField` uses.)

- Add a third option to the bearing widget named "true bearing".  This would immediately disperse any doubts with regard to the meaning of "magnetic bearing" and it's also something that is more fundamental than magnetic bearing.  It's strange to have the latter without the former.  (Personally, I would also love to see "bearing relative to the UTM grid" because this is the grid that is present on paper maps, but OK, using a paper map with osmand is probably a niche application.)

**Comment by sonora** [comment]
- [x] I have updated the documentation, please feel free to double-check: https://docs.osmand.net/en/main@latest/osmand/widgets/nav-widgets#bearing
- [ ] I also support the idea to introduce a third mode to the bearing widget called "True bearing". Not sure if we can convince @vshcherb.

**Comment by grothesque** [comment]
The updated documentation is very clear now, thanks.

My argument for adding a "true bearing" option is that it is highly unusual (to the point of being confusing) to only have "magnetic bearing" without "true bearing".  It is also generally more useful to know the true bearing, since the magnetic one is only valuable to people who happen to use a compass together with osmand.

Many map web sites and GPS receivers allow to work with bearings and it's always the true one that is the default, and often the only possible, choice.

**Comment by vshcherb** [comment]
@sonora I think you can create an issue for that. It sounds it makes sense to have "True bearing", I just didn't use anything except magnetic and relative.
