### ISSUE TITLE
Web Links not opening for Help / "Discussion" or "Follow us"

### ISSUE THREAD

**Issue by Boothy99** [osmandapp/OsmAnd#13244]
Description -
When opening the Help section in OsmAnd+ and attempting to open any web link within the "Discussion" or "Follow us" sections, a popup with "Install an app that can perform this action" appears (screenshot provided).

This issue occurs on my mobile phone with android 11. 

The issue is not reproducible on my Tablet with android 10 - here, links open immediately with my default web browser. 

Environment -
LINKS NOT WORKING ....
OsmAnd+ 4.1.7, released: 2021-11-16
Android 11
Xiaomi Mi 9T with MIUI 12.1.1.0

LINKS WORKING ....
OsmAnd+ 4.1.7, released: 2021-11-16
Android 10
Samsung Galaxy Tab S4 (SM T830) with One UI Version 2.1

![Screenshot_2021-11-24-08-21-06-321_net osmand plus](https://user-images.githubusercontent.com/13983995/143205029-7211befc-857c-4492-8da8-f8c7c8ace521.jpg)

**Comment by vshcherb** [comment]
Will be fixed in 4.1.8, already fixed in nightly build

**Comment by Boothy99** [comment]
Thanks for the update, @vshcherb
