### ISSUE TITLE
Screen timeout - proximity sensor stopped working (probably 4.1)

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#13242]
Even though it's not reproducible on many devices with Android 11 and OsmAnd 4.1, 
but it's definitely reproducible on Samsung S21 Android 11 OsmAnd 4.1.

Screen timeout - wake up based on proximity sensor doesn't work in any possible combination (tried 6-8 combinations).

**Comment by alex-osm** [comment]
Looks like Samsung issue - https://stackoverflow.com/questions/66827891/how-to-detect-type-of-proximity-sensor-infrared-or-not

**Comment by anastasiia936** [comment]
The proximity sensor doe not work correctly on Nokia 5.4
