### ISSUE TITLE
Data in Overview Screen

### ISSUE THREAD

**Issue by GuentherGredy** [osmandapp/OsmAnd#13240]
### Description
After update to new OsmAnd version the overview page looks like in screenshot "Screen_01.png"; the two objects "import/RW_Erzkastenrundweg/*" have been used weeks ago but are no longer in folder "Import".

<img src="https://user-images.githubusercontent.com/85982948/143061880-ace86b42-3aa3-4140-a495-b2e56a73f01b.png"  width="300" height="auto"/> 

They both point to a location I've never been there before ("Screen_02.png").
<img src="https://user-images.githubusercontent.com/85982948/143061923-d1428550-9351-45f2-b5d1-f80d3840ef65.png"  width="300" height="auto"/> 

Both objects only appear in overview screen. Deleting content of import folder does not remove the objects.

I have added the object "Werderstraße 5" under the new OsmAnd version (added marker and moved it to history).

History only shows the object "Werderstraße 5" ("Screen_03.png").
<img src="https://user-images.githubusercontent.com/85982948/143061965-3c2e07c6-bc16-435c-be0e-188d0d59ad54.png"  width="300" height="auto"/> 

So I can delete this object but I cannot delete the other two objects.

Any idea how to get rid of the two objects?

### Your Environment
OsmAnd Version: 4.0.9
Android/iOS version: 9
Device model: LG G6

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by GuentherGredy** [comment]
Recently I have used three other GPX-files while hiking, they have been added to history, yet are also not available when pressing "ALLE ANZEIGEN" (Screen_04.png). They also point to the same strange location.
![Screen_04](https://user-images.githubusercontent.com/85982948/143436156-db161fb0-a972-4d60-9aac-1dc53f1e1c06.png)

**Comment by GuentherGredy** [comment]
These days I had another experience with this topic. I recorded and saved two tracks, on Friday and Saturday. They are available in the overview page. Both tracks are located in the Atlantic Ocean!?
![1_Overview](https://user-images.githubusercontent.com/85982948/150841148-69f64adc-7e0c-438d-8c9d-21ed3776010c.png)
If I pressed "ALLE ANZEIGEN" I got a strange history page where only the Saturday track is shown.
![2_History](https://user-images.githubusercontent.com/85982948/150841336-94a4ab49-dea7-4408-9557-8430e20d48ee.png)
Klicking on the track shows the correct track on correct map section.
![3_CorrectTrack](https://user-images.githubusercontent.com/85982948/150848314-4f453b7d-32a8-40dc-bffe-3e553e6fae8d.png)

**Comment by GuentherGredy** [comment]
Hi everyone, it's been a long time since I posted this bug. I even found it in the latest Osmand version 4.2.6. The error is really annoying. The way it looks to me, the bug isn't even assigned yet. Do you have any idea what could be the cause of this error or how to fix it? Thank you for your commitment. Greetings Guenther

**Comment by vshcherb** [comment]
Overview page is deprecated and it's still ongoing debate whether we find resources to fix it or make it out of support. We need to fix the issue of course.

**Comment by sonora** [comment]
From my experience supporting users, not a single one seems to use what we call "Overview page" above, so I guess it is worth considering to remove that one.

**Comment by franco999** [comment]
@sonora Sorry for the intrusion but, if I have not misunderstood, I have read that you are planning to eliminate the "overview page". 

If by "**overview page**" they mean the "**dashboard**" screen, I have to disagree as this panel is critical to me. I have been using it for years as it is more convenient for me than the side panel. I would be very sad to see that I can no longer use this panel.

It's a quick and easy way to see favorites, GPX traces, OSM edits/records and add-ons all in one place.

**Comment by sonora** [comment]
Sure, it depends on what you got used to working with, no hard feelings at all.

What I am saying is I would rather see dev capacities directed to functionality, quality, and ergonomics, rather than maintaining two separate ways to access all functionality.

It is a self-inflicted quagmire, because we have allowed (even facilitated, with hard work) different users to devlop different habits here.  😉 I suppose the way out is to merge both mechanisms again keeping the best of both, but avoiding the double maintenance.

**Comment by GuentherGredy** [comment]
Unfortunately I still found the above described behavior in the newest version 4.2.7.
It's really annoying and I would appreciate it very much to get rid of this bug.
Thank you very much.

**Comment by alex-osm** [comment]
Should be fixed by https://github.com/osmandapp/OsmAnd/pull/16793
