### ISSUE TITLE
Textual error

### ISSUE THREAD

**Issue by oliveiranathan** [osmandapp/Osmand#1325]
On the announce settings, on selecting to announce speed cameras, the warning text is wrong in telling that Osmand will assume any liability for the use of the feature. 
![screenshot_2015-06-07-03-52-32](https://cloud.githubusercontent.com/assets/1960057/8022959/6db487d0-0cc9-11e5-8264-69d0c68e4bd4.png)

**Comment by vshcherb** [comment]
Fixed
