### ISSUE TITLE
OsmAnd creates invalid GPX v1.1 files

### ISSUE THREAD

**Issue by kwirk** [osmandapp/OsmAnd#1326]
GPX v1.1 files generated by Osmand are invalid due to _speed_ (in _trkpt/extensions_) belonging to the default/gpx namespace. GPX v1.1 schema requires that [extensions belong to a "other" namespace](http://www.topografix.com/gpx/1/1/#type_extensionsType).

**Comment by gurkerlbaron** [comment]
This is a very old issue, the solution to fix the code can be found here: https://code.google.com/p/osmand/issues/detail?id=431

It's becaus of the wrong namespace of the speed element. Currently the generated GPX export does not validate against the GPXV1.1 schema and is formal incorrect. Any software validating the gpx file cannot succesfully parse the xml and import data.

**Comment by j764439** [comment]
This issue prevents Garmin basemap software to read the saved gpx track.
A solution is already proposed in https://code.google.com/p/osmand/issues/detail?id=431#c12
Another solution would be a further option allowing the user to switch between full and almost gpx1.1 compliant files.

**Comment by jensMF** [comment]
As the mentioned solutions are not easily available anymore I used the "waybackmachine" to find it:
[https://web.archive.org/web/20160819021250/https://code.google.com/p/osmand/issues/detail?id=431](url)


![OsmAnd_Issue_431](https://user-images.githubusercontent.com/1620034/87231836-bd91be00-c3ba-11ea-8457-3db626fba039.png)

I hope it helps.

**Comment by jensMF** [comment]
I would suggest to either use the garmin GPX extensions like that:
```
<gpx version="1.1" creator="sample"
 xmlns="http://www.topografix.com/GPX/1/1"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd http://www.garmin.com/xmlschemas/GpxExtensions/v3 https://www8.garmin.com/xmlschemas/GpxExtensionsv3.xsd http://www.garmin.com/xmlschemas/TrackPointExtension/v2 https://www8.garmin.com/xmlschemas/TrackPointExtensionv2.xsd http://www.garmin.com/xmlschemas/PowerExtension/v1 https://www8.garmin.com/xmlschemas/PowerExtensionv1.xsd https://www.vecturagames.com/xmlschemas/GpxWaypointExtension/v1 https://www.vecturagames.com/xmlschemas/GpxWaypointExtensionv1.xsd"
 xmlns:gpxx="http://www.garmin.com/xmlschemas/GpxExtensions/v3"
 xmlns:gpxtpx="http://www.garmin.com/xmlschemas/TrackPointExtension/v2"
 xmlns:gpxpx="http://www.garmin.com/xmlschemas/PowerExtension/v1"
 xmlns:gpxwpx="https://www.vecturagames.com/xmlschemas/GpxWaypointExtension/v1">
...
<trkpt lat="52.4893718" lon="13.4398769">
    <ele>15.23</ele>
    <time>2020-07-15T00:11:16Z</time>
    <hdop>18.224</hdop>
    <extensions>
        <gpxtpx:TrackPointExtension>
            <gpxtpx:speed>1.200000</gpxtpx:speed>
        </gpxtpx:TrackPointExtension>
    </extensions>
</trkpt>
```
or at least this:
```
<gpx version="1.1" creator="sample"
 xmlns="http://www.topografix.com/GPX/1/1"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd http://www.garmin.com/xmlschemas/TrackPointExtension/v2 https://www8.garmin.com/xmlschemas/TrackPointExtensionv2.xsd"
 xmlns:gpxtpx="http://www.garmin.com/xmlschemas/TrackPointExtension/v2">
...
<trkpt lat="52.4893718" lon="13.4398769">
    <ele>15.23</ele>
    <time>2020-07-15T00:11:16Z</time>
    <hdop>18.224</hdop>
    <extensions>
        <gpxtpx:TrackPointExtension>
            <gpxtpx:speed>1.200000</gpxtpx:speed>
        </gpxtpx:TrackPointExtension>
    </extensions>
</trkpt>
```

or adding an osmand namespace as suggested in the mentioned solution and prefixing all extensions written by OSMAnd with it.
It would i.e. look like this:
```
<gpx version="1.1" creator="OsmAnd~ 3.7.4"
xmlns="http://www.topografix.com/GPX/1/1"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd" xmlns:osmand="https://osmand.net">
...
<trkpt lat="52.4893718" lon="13.4398769">
     <ele>15.23</ele>
     <time>2020-07-15T00:11:16Z</time>
     <hdop>18.224</hdop>
     <extensions>
          <osmand:speed>1.2</osmand:speed>
     </extensions>
</trkpt>
```

If there is a decision made I would start working on a pull request for this.

**Comment by vshcherb** [comment]
It is not clear what will be backward compatible with OsmAnd and what will be supported by Garmin and others, so far we didn't find working possibility with Garmin

**Comment by jensMF** [comment]
What do you mean with backward compatible with OsmAnd? How could I test that?
Do you know how to test Garmin compatibility without owning a Garmin device?

**Comment by vshcherb** [comment]
We've tried to modify GPX manually as mentionned above with extra namespaces and uploaded to Garmin Basecamp and it wasn't working anyway!  
So I don't consider this issue important for now. Cause we don't know exactly which Garmin devices are broken, how to fix them correctly, how many people and how it will make happier. Almost all modern software read tags correctly inside extensions or ignores them without requiring extra namespaces which just takes extra space.

PS: Backward compatibility with OsmAnd that track will be read correctly with 3.0+ version. For us it is much more important that tracks are shareable between latest OsmAnd versions than Garmin.

**Comment by jensMF** [comment]
I don't really care for the Garmin stuff but I think it is important to follow the documentation of a standard that one uses. Otherwise standards are getting useless. As @kwirk mentioned in his first comment:

> GPX v1.1 schema requires that [extensions belong to another namespace](http://www.topografix.com/gpx/1/1/#type_extensionsType).

where he refers to the Schema Documentation that can be found here:
[https://www.topografix.com/gpx/1/1/](url)

and I am validating the gpx files like mentioned here:
[https://www.topografix.com/gpx_validation.asp](url)
(In short: Install Xerxes and use this command to validate:
```
SAXCount -v=always -n -s -f 2020-07-15_02-11_Wed_test.gpx
```
Replace the filename with that of the file you want to validate)

I added an osmand namespace and prefixed the speed extension in an experimental branch of mine. Here is the resulting file: [2020-07-15_02-11_Wed_test.txt](https://github.com/osmandapp/Osmand/files/4949946/2020-07-15_02-11_Wed_test.txt)
That file validates without any problem with the method mentioned above.

Could you attach an example of your files, that were not working with Garmin?
