### ISSUE TITLE
Fairphone 4 / Android 11: Can't open files or weblinks

### ISSUE THREAD

**Issue by Discostu36** [osmandapp/OsmAnd#13268]
### Description
When I try to import a file backup, the app tells me to install an application. So I guess it doesn't recognise the files app of my smartphone. 

Edit: The same problem exists when trying to open a weblink. 

### How to reproduce?
Go to settings and try to restore from file

### Your Environment
OsmAnd Version: 4.1.7
Android/iOS version: Android 11
Device model: Fairphone 4

**Comment by Discostu36** [comment]
![Screenshot_20211129-104342~2.png](https://user-images.githubusercontent.com/30999326/143844615-333759d1-4ca8-4947-9c8b-bb28b263425e.png)

**Comment by Discostu36** [comment]
Ok, Browser does also not open... ![Screenshot_20211130-111938.png](https://user-images.githubusercontent.com/30999326/144029346-08d4628e-013e-4b5a-b2e7-2b5932198af0.png)

**Comment by vshcherb** [comment]
Fixed with 4.1.9
