### ISSUE TITLE
The routes use slower and wrong roads 

### ISSUE THREAD

**Issue by borisp71** [osmandapp/OsmAnd#13262]
# 🐞 routing report

### Routing engine

- [X ] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Car
### Start and end points

Arilje to Belgrade ( Serbia)
### Actual and expected routes

The normal route goes from Arilje using road 21 to Pozega because that is the main road, straight and fastest, then in Pozega connects to the road E763 and continue to the Cacak. In Preljina the usually navigation should go by highway to the Beograd
### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

OsmAnd 4.0.8, released: 2021-09-22
</code></pre>

**Device and Android/iOS version:**
Android 11,Xiaomi Poco X3 Pro, Miui 12.5.3
**Maps used (online or offline):**
Offline
![Screenshot_2021-11-26-23-12-51-043_net osmand](https://user-images.githubusercontent.com/6475839/143658380-bf6c19c2-787a-4749-8a79-99dbe03f28da.jpg)

- [x ] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**

**Comment by vshcherb** [comment]
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=43.7355%2C20.1106%3B44.8149%2C20.4787

**Comment by borisp71** [comment]
Hi, you can see that route you provide avoiding highway, main road. The route goes over the mountains and the route is maybe shorter but surly not faster or time-consuming best

**Comment by Zirochkabila** [comment]
**Not reproduced**
