### ISSUE TITLE
Display Route  correctly 2.5D

### ISSUE THREAD

**Issue by LeLuyen** [osmandapp/OsmAnd#13264]
Hi all,

After re-calculator routing and drawing, it's wrong in mode 2.5D.

![image](https://user-images.githubusercontent.com/2620445/143727417-4c0ab1d4-807b-455e-8b56-d483b4699923.png)
(2D Image)

![image](https://user-images.githubusercontent.com/2620445/143727438-020bdeeb-02f5-41fb-bf40-b97bb681ff61.png)
(2.5D Image)

How to fix?

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-iOS/blob/master/Sources/Controllers/Map/Layers/OARouteLayer.mm

https://github.com/osmandapp/OsmAnd-iOS/tree/master/Sources/Controllers/Map/Layers
https://github.com/osmandapp/OsmAnd-iOS/blob/master/Sources/Controllers/Map/Layers/OAContextMenuLayer.mm#L360
https://github.com/osmandapp/osmand-api-demo/blob/38b54f8912088c7f34852b0e6780e5e99a414061/OsmAnd-qt-core-sample/app/src/net/osmand/core/samples/android/sample1/MainActivity.java#L343

**Comment by ivanPyrohivskyi** [comment]
[ ] - core/openGL environment for Android
[ ] - SWIG
[ ] - create provider

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd/pull/13948
https://github.com/osmandapp/OsmAnd-core/pull/302
<img width="450" src="https://user-images.githubusercontent.com/1040293/158988418-fb3505b8-e64b-41be-b538-60242edc9e95.png" />

**Comment by lbdroid** [comment]
Running today's (april 14, 2022) opengl-arm64 nightly, I have observed another location where some layer is not following the map surface on tilt; the green overlay that indicates which map sections have been downloaded. See the following screenshots:

The first is a reference for no-tilt, the second one shows approximately the same view, but tilted at maximum.

![Screenshot_20220414-105709](https://user-images.githubusercontent.com/3372230/163418423-60919206-778a-4b2e-832c-6596f6abd98a.png)
![Screenshot_20220414-105719](https://user-images.githubusercontent.com/3372230/163418427-671b6d96-3405-44f5-88f4-1194e707ba2c.png)

**Comment by LeLuyen** [comment]
Hi Alll,

1) App crash when using opengl with map elevation between 35 ~ 89.

Version  OsmAnd~ 4.2.0
28.04.2022 9:09:44
Apk Version : 4.2.0 421
Exception occured in thread Thread[Thread-1210228,5,main] : 
java.lang.NullPointerException: null upcall object in OsmAnd::interface_MapTiledCollectionProvider::getCaptionTopSpace 
Version  OsmAnd~ 4.2.0
28.04.2022 9:09:44
Apk Version : 4.2.0 421
Exception occured in thread Thread[Thread-1210229,5,main] : 
java.lang.NullPointerException: null upcall object in OsmAnd::interface_MapTiledCollectionProvider::getScale 

2) the animation of navigation icon isn't smooth in 2.5d

**Comment by LeLuyen** [comment]
Hi All,

The downloaded regions layer doesn't fixed.

![image](https://user-images.githubusercontent.com/2620445/165669242-65b586e2-3c3c-4d0c-b99f-728ba3aec2e9.png)
