### ISSUE TITLE
Extra u-turn when turning from tertiary to a trunk road

### ISSUE THREAD

**Issue by HubMiner** [osmandapp/OsmAnd#13260]
**### Routing engine**

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

**### Routing Profile**

car, fastest

**### Start and end points**

START
https://www.openstreetmap.org/node/6018501798
Cucina Bella
42.1656885, -88.2939304
Algonquin, Illinois

END
https://www.openstreetmap.org/node/3676686025
Algonquin Mexican Restaurant
42.1630173, -88.2962399
Algonquin, Illinois

### Actual and expected routes

Expected route 1:
https://graphhopper.com/maps/?point=42.16563%2C-88.293879&point=42.158516%2C-88.296953&locale=en-US&elevation=true&profile=car&use_miles=false&selected_detail=Elevation&layer=Omniscale

Expected route 2
http://map.project-osrm.org/?z=17&center=42.161427%2C-88.294839&loc=42.165702%2C-88.293943&loc=42.158584%2C-88.296797&hl=en&alt=0&srv=0

Actual route:
(see attached file)

### Is this a regression?

No.

## 🌍 Your Environment

**OsmAnd Version:**
<pre><code>
4.0.8
</code></pre>

**Device and Android/iOS version:**
Samsung S10
Android 11

**Maps used (online or offline):**
offline

- [X] Offline maps offered within the OsmAnd app for download.
United States Illinois Oct 31, 2021

- [ ] Online (tile / raster) maps 

**Anything else relevant?**
![OsmAnd](https://user-images.githubusercontent.com/15963507/143619827-7092b30b-7941-4d6c-90f1-14c9070a1841.jpg)

**Comment by hplewis** [comment]
I have a similar issue navigating

https://www.openstreetmap.org/node/4341382484 ---> https://www.openstreetmap.org/node/415538039

![Screenshot_20211206-114024](https://user-images.githubusercontent.com/8607347/144912427-82fe1f36-ae06-4dc6-8166-38e1b8100801.jpg)

In practice, this is a simple left turn, but the app tells me to turn right, then left, which is incorrect.

![Screenshot_20211206-114957](https://user-images.githubusercontent.com/8607347/144912779-4911415e-7c6f-42f0-a595-992da272df3f.jpg)

**Comment by alisa911** [comment]
Hello! This bug is not reproducible. Please update app and map.

**Comment by HubMiner** [comment]
![Screenshot_20220402-131903_OsmAnd+](https://user-images.githubusercontent.com/15963507/161396214-fbc2fb32-cf1f-4485-b659-8a73811a52c0.jpg)

Tested, the new instructions are correct, thanks for investigating this. Routing engine must have changed.
