### ISSUE TITLE
Audio/Video plugin starts putting photo notes at the wrong location

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#1327]
I added some Photo notes using the Audio/Video plugin. Always selecting a location on the map, then clicking Add Photo. I used to add a lot of notes this way. For some reason suddenly the notes are not put at the chosen location, but I find them somewhere in the ocean near Australia, while the correct location should be in Europe. Also, the label of these stored notes is no longer "Photo", but it became 0LAd (or OLAd). Only hint could be that before this happened, I mistakenly recorded an Audio note. But when I did that, I just stopped the recording and then tried to add a Photo as usual. Since than all the photo locations are bad. The image itself is correct as taken by the camera.

**Comment by vshcherb** [comment]
There was an issue fixed recently so it is not in 2.0.4. Please confirm that this is not reproducible in nightlies.

**Comment by aceman444** [comment]
It only happens randomly so it is hard to say if it stopped happening already or not. I am now on v2.1 and observing it. I will report back if it appears again.

**Comment by vshcherb** [comment]
2.1 that bug should be fixed, we will need special location where it happens to reproduce it.

**Comment by aceman444** [comment]
With "observing it" I mean I watch whether the bug happens again. I did not want to say I have observed the bug happening yet in v2.1.
