### ISSUE TITLE
Cannot edit name of favourite

### ISSUE THREAD

**Issue by chau-intl** [osmandapp/OsmAnd#13270]
### Description
When I try to edit a favourite and click on the name in the name field, the keyboard shows briefly and disappears again. I cannot get the keyboard to remain visible so that I can enter text.

This used to work, so I think it is a regression and I couldn't see any recent issue on this (sorry if I missed an existing issue).

### How to reproduce?
* Click on a favourite in the map.
* Click the `Edit favourite` button.
* Click on the text in the `Name` field in the top of the window.
* Observe that the keyboard briefly becomes visible for only to disappear again.

### Your Environment
OsmAnd Version: 4.1.7 released 2021-11-16
Android/iOS version: 11
Device model: Xiaomi Mi 9T Pro

**Comment by vshcherb** [comment]
Trying to reproduce, not clear yet if it's Xiaomi related.

**Comment by Pizzacutter-at-tty3** [comment]
I'm a Xiaomi user and I experience the same problem

**Comment by chau-intl** [comment]
I have now received version 4.1.9 released 2021-11-27, and I no longer experience the issue. The keyboard shows and works just as expected.

@Pizzacutter-at-tty3, can you confirm that it is working with the newer version?

**Comment by Pizzacutter-at-tty3** [comment]
I have waited a few days, but have not yet received an update to 4.1.9
I don't know if being in the beta program of google play chabges anything, but I would expect to receive it early

**Comment by chau-intl** [comment]
> I have waited a few days, but have not yet received an update to 4.1.9 I don't know if being in the osmand beta program in google play changes anything, but I would expect to receive it early

I am part of the OsmAnd+ beta program and I guess that's why I have received the new release.

@vshcherb, should I close this issue since it works for me or wait until @Pizzacutter-at-tty3 can confirm it works on 4.1.9?

**Comment by vshcherb** [comment]
Well we could wait for a release, It's blocked for external reasons for now but we hope this week to resolve it. OsmAnd+ is available 4.1.9. You also can test on nightly builds

**Comment by Pizzacutter-at-tty3** [comment]
I have just received an update to 4.1.10 and I can confirm that it works now.
