### ISSUE TITLE
IOS  vs Android: Incorrect address displaying in Canary Ilands

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#13287]
**IOS code is not in sync with Android**

Select any geographic point on the Calle Miguel Calcerrada (which is right, as you can see on the map), but in the Context menu shows the name of the street next to it (Calle Nicolás Pérez Escobar).
28.01425, -16.67008

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/80623554/144084131-35c0613a-f002-43df-a4bb-a8f51422f4e4.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

Checked in OsmAnd 4.1 (Testflight), the last map update from 01.11.21.
P.S. Doe not reproduced in the Android version of OsmAnd.

**Comment by Zirochkabila** [comment]
[Map here](https://drive.google.com/drive/folders/1GriE1HL7i3yzSzsgx3rJxE8tqC3UBTEc?usp=sharing)

**Expected**  OsmAnd~ 4.3.0#13873mqta, released: 2022-10-17
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/196142824-cd95f06c-eb74-458d-ac17-fa6ca50c36d6.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

**Actual** 4.3.0.17
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/196143027-56ad09c2-a668-4879-90a5-7288adc4096c.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
Reproduced expected result is 2nd:
https://osmand.net/map#17/28.01430/-16.66848. 

![Screen Shot 2022-10-17 at 13 29 30](https://user-images.githubusercontent.com/1042025/196166122-da8414b5-36ce-43a0-a749-b4a9034d03a9.png)

It's not wrong cause Arona is around https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=345076&class=boundary

**Comment by vshcherb** [comment]
It's a map issue cause Arona doesn't have smaller boundary but it has the big one https://www.openstreetmap.org/node/313358351

**Comment by Zirochkabila** [comment]
https://www.openstreetmap.org/way/25555766#map=17/28.01424/-16.67005

<img width="1213" alt="Screenshot 2022-10-17 at 17 53 46" src="https://user-images.githubusercontent.com/104760013/196210424-27a2c356-eaff-4e9b-ad66-e5ac6de4eccd.png">


https://osmand.net/map/?end=33.978962%2C-84.424042&mode=truck#18/28.01388/-16.67011

<img width="1125" alt="Screenshot 2022-10-17 at 17 52 56" src="https://user-images.githubusercontent.com/104760013/196210543-49cd8b56-bf51-4589-a315-c439ec44b065.png">

<img width="1213" alt="Screenshot 2022-10-17 at 17 55 10" src="https://user-images.githubusercontent.com/104760013/196210707-e459b02a-3a03-4970-bb80-5b090086428f.png">

**Comment by Zirochkabila** [comment]
Same
[927 lincoln ave map](https://drive.google.com/drive/folders/1GriE1HL7i3yzSzsgx3rJxE8tqC3UBTEc?usp=sharing)

Actual 
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/197338922-8f13bace-f441-4497-ab51-f7aca92ac05d.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

Expected 
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/197338978-74dc5211-be8c-4c18-96fc-f39cfee1dc37.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

[OSM link](https://www.openstreetmap.org/#map=17/39.92629/-85.37431)
[OsmAnd link](https://osmand.net/map/?end=48.884489%2C30.682089&mode=car#18/39.92657/-85.37370)

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/197339067-22744efd-5d56-4f8d-966d-4e190f1ab25e.png"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/197339069-bc4372b2-a072-4ebf-ab0e-0c6b073375df.png"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd/pull/15799
