### ISSUE TITLE
destination=* tag not announced when destination:ref=* is also present

### ISSUE THREAD

**Issue by fred702** [osmandapp/Osmand#1328]
As of 2.0.4, when a motorway_link is tagged with destination=* and destination:ref=* only the destination:ref=* is announced. Both are displayed on screen however.

If both tags are present, destination:ref=* should be announced followed by destination=* to match the on screen display.

Example:https://www.openstreetmap.org/way/6100735

**Comment by vshcherb** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/7ec0ef76d59d25bef024793f21c97f49e14f1bc4

**Comment by fred702** [comment]
Thanks! Now that I think about it more, the decision could be more of a design choice than a bug. Some tags with multiple destinations can be quite lengthy. I'll test it out and hope to get more input on it from other users.
