### ISSUE TITLE
Poor formatting of long_press>Actions in landscape mode

### ISSUE THREAD

**Issue by thompehw** [osmandapp/OsmAnd#13283]
### Description
<table style="width:100%">
  <tr>
    <th>The options are readable in portrait mode:</th>
    <th> but cut short in landscape mode:</th>
  </tr>
  <tr>
    <th><img src="https://user-images.githubusercontent.com/39751382/144170888-51a2a816-8b0c-4493-a656-aea02e716f2e.jpg"  width="300" height="auto"/> </th>
    <th valign=top><img src="https://user-images.githubusercontent.com/39751382/144170967-b432df51-d3ed-4c3d-91d4-fe816789eb96.jpg"  width="600" height="auto"/> </th>
  </tr>
</table> 

### Your Environment
OsmAnd Version: Osmand+ 4.1.9
Android/iOS version: Android 10
Device model: Samsung Galaxy Tab A SM-T510

**Comment by dmpr0** [comment]
# ToDo
- [ ]  Landscape mode: actions menu width should be 50% of screen width.

**Comment by Chumva** [comment]
https://github.com/osmandapp/OsmAnd/pull/13401
