### ISSUE TITLE
The text in the search in the Download map menu is not readable

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#13286]
### Description
In the day app mode, the text for search Cities or regions writes white, but it is readable, in the dark mode it writes black which is not readable.

<table style="width:100%">
  <tr>
    <th>Dark</th>
    <th>Light</th>
  </tr>
  <tr>
    <th><img src="https://user-images.githubusercontent.com/80623554/144222168-ac3850b7-84bb-4262-abaf-7290e9db404d.png"  width="300" height="auto"/> </th>
    <th valign=top><img src="https://user-images.githubusercontent.com/80623554/144222238-9ca8c8db-40c4-4c01-9801-a30194dd86b1.png"  width="300" height="auto"/> </th>
  </tr>
</table> 

### How to reproduce?
Update OsmAnd to 4.1.9 and search City in the Download map menu.

### Your Environment
OsmAnd Version: 4.1.9
Android/iOS version: Android

**Comment by dmpr0** [comment]
# ToDo
- [ ] Light theme text color = active_buttons_and_links_text_light
- [ ] Dark theme text color = active_buttons_and_links_text_dark

**Comment by mmh-dev** [comment]
https://github.com/osmandapp/OsmAnd/pull/13324
