### ISSUE TITLE
Edit track from the selected point

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#13285]
It would be very useful to be able to edit track from the selected point. For example, you overview track and would like to edit some point in the middle of the track you press Edit track and enter to the plan route menu. Currently, it offers you to edit track from the last track point. It would be much better if it enter the Edit Menu from the last overviewed point.

**Comment by dmpr0** [comment]
# ToDo
Edit track UI should be opened centered on the previously selected centering and zoom level.
- [ ]  If "Edit track" was launched from the context menu, show the same map center and zoom level
- [ ] If "Edit track" was launched from My places, use default view, when the whole track is visible on the map screen.

<table style="width:100%">
  <tr>
    <th>Context menu</th>
    <th>Current zooming and centring</th>
    <th>Proposed</th>
  </tr>
  <tr>
    <th><img src="https://user-images.githubusercontent.com/9365308/144842044-71a18906-d8c9-429d-984f-2b0dba72e058.png"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/9365308/144842036-e1451da3-80a7-4aa5-a1cd-7a23442aa511.png"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/9365308/144842043-fa7e714c-7bbe-466d-9ee5-e2a2d16417ed.png"  width="300" height="auto"/> </th>
  </tr>
</table>
