### ISSUE TITLE
Announcement Time - Off Route

### ISSUE THREAD

**Issue by duiveldoder** [osmandapp/OsmAnd#13298]
### Description
When going to any navigation profile
Then "configure profile"
then "navigation settings"
then "voice prompts"
then scroll down to where it says "Announcement time"
expand the information panel below the slider

it all makes sense - early, normal, late you get early notifications "xxx" meters before passing
or normal notications "xx" meters before passing
or late "x" meters before passing

EXCEPT the "off router warnings"
under early I get these for my profile "walking" at 80-85 meters
under normal I get these 55-60m
under late I get these 25-30m

but the thing is - this is OFF ROUTE meaning you get these AFTER and not BEFORE you pass anything..

it means AFTER you get away from the track x, xx, xxx meters you get the warning.

So the values here should actually be increasing and not decreasing as you move the slider from left to right.

### How to reproduce?
just try and see

### Your Environment
OsmAnd Version: latest
Android/iOS version: 10
Device model: Mate 20 pro

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

Always latest up to date.

**Comment by vshcherb** [comment]
Late means that you've closer to the "Action time", so if you have very precise GPS and slow speed you need to use "Late" but if you experience lots of errors of position detection then it's better to use "Early"

**Comment by duiveldoder** [comment]
I think you haven't read what I wrote..

OFF ROUTE - LATE - means I get them within a shorter deviation from the real route..

That's opposite of what to be expected when selecting LATE
