### ISSUE TITLE
The pop up dialog for Download map does not appear 

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#13297]
### Description
Sometimes the dialog appear from zoom level 9 for example for Canada, England, Spain.
Sometimes it does not appear for example for Ireland

The issue is always reproduce in the landscape mode. 
![image](https://user-images.githubusercontent.com/80623554/144625691-66ef33df-e907-48da-a1d1-94b50d1e4a9d.png)
![image](https://user-images.githubusercontent.com/80623554/144625712-3d6a4665-856d-461c-8971-fd1ab12ccf8a.png)
![image](https://user-images.githubusercontent.com/80623554/144625736-a81c519c-8b2a-466d-b2cc-d3c75700b822.png)
![image](https://user-images.githubusercontent.com/80623554/144625755-f77c4843-c59c-4f4d-9d7b-d2836a9b0121.png)

### How to reproduce?
Browse over Ireland.

### Your Environment
OsmAnd Version: 4.0.8
Android/iOS version: Android 9
Device model: Sony Experience XZ1

**Comment by Rowin63** [comment]
It is an east-west-issue.
West of zero meridian the download dialog appears, east of it it does not

Try it following this line. Zoom in to 20km and move the map left and right. 
Dialog appears and disappears, depending on where you are at the map...

Robert 


![Screenshot_20211204-064848_OsmAnd+](https://user-images.githubusercontent.com/95540936/144717697-f31bb7e5-f970-40f8-a5c2-ed927e4f56cb.jpg)
.

**Comment by Rowin63** [comment]
It does not work on my Tablet at all, if used in landscape mode!
In portrait mode, it works at least like mentioned above (east/west-issue)!

**Comment by cepprice** [comment]
@Rowin63, can you please share profile which you were using on your tablet, when Download map dialog doesn't appear at all on landscape?

**Comment by Rowin63** [comment]
Hello!

"unfortunately" all my three devices are already updated to 4.1.10 and as I can see now, this issue does not exist anymore!
(was in 4.0.8)
(only the east/west-issue is still evident)

Perhaps I can find a 4.0.8 somewhere, then I´ll try it again. 

Robert

**Comment by vshcherb** [comment]
@cepprice it still doesn't work on my device as I saw. 
Something strange is going on...
