### ISSUE TITLE
maxspeed:conditional not working with date ranges

### ISSUE THREAD

**Issue by juhanjuku** [osmandapp/Osmand#1329]
maxspeed:conditional is not recognized with date range values.
It is only working with time values, example  50 @ (08:00-17:00)
In Nordic countries we have different speed limits for winter and summer time.
I have tried many combinations from http://wiki.openstreetmap.org/wiki/Key:opening_hours, 
for example (Apr 26-Oct 31), (Apr-Oct), (week 17-39), (Mo-Fr)
Non of them is working with Osmand.

**Comment by vshcherb** [comment]
True, links to real osm objects with such problem will be nice.

**Comment by juhanjuku** [comment]
Here is link:
http://www.openstreetmap.org/#map=18/59.34522/24.89510

**Comment by juhanjuku** [comment]
Why "Nice to Have"? It's bug. Routing estimates totally wrong times and overspeeding warnings are meaninless with this bug.

**Comment by vshcherb** [comment]
We are welcome for patches and any contribution, that could make it possible.

**Comment by fred702** [comment]
access:conditional should also be supported as there are roads with seasonal restrictions that are closed for large portions of the year

https://www.openstreetmap.org/way/339393215

**Comment by vshcherb** [comment]
conditional now is properly supported for navigation, lanes, maxspeed, access though "winter" is not supported, so it is better to put restriction in months, I think. Anyway that feature will require quite some UI to specify what is winter time

**Comment by vshcherb** [comment]
I think all specified cases are supported now
