### ISSUE TITLE
Offline rendering: no way to get rid of direction arrows on waterways

### ISSUE THREAD

**Issue by micechal** [osmandapp/Osmand#1330]
I wanted to make a clear rendering profile that would be free of any clutter for myself, which included removing the arrows drawn on rivers indicating the water flow which I don't need.
When looking through the default renderer I found this block:
`<renderingConstant name="waterwayDirectionIcon" value="arrow_blue_big_night"/>`
From what I was able to see, this variable was used in every waterway object, so I thought I'd change it to something different. 
The first try was making it just an empty string but that didn't change anything at all. Next one was changing the icon to one of a volcano (picked a random icon name found in the file) but the result was the same as earlier - I could still see the arrows instead of volcano icons.
When I tried changing the path icon spacing, nothing changed as well.

All this leads me to the conclusion that these arrows have to be somehow hardcoded, as I whatever I tried would result in the rivers staying the same or disappearing completely. Is it indeed hardcoded or am I doing something wrong here?

**Comment by aceman444** [comment]
I like the arrows feature for mapping. But yes, it should be configurable in the style for advanced users. Is it also possible to remove arrows on oneway roads?

**Comment by cepesko** [comment]
I support the idea of reducing the waterway arrows maybe to the two profiles for pedestrians and bikers plus reduce the color saturation.

**Comment by xmd5a2** [comment]
```xml
<renderingConstant name="waterwayDirectionIcon" value="arrow_blue_big_night"/>
```
This is for OpenGL engine only. Currently there is no way to remove these arrows in old engine. There is an rendering attribute,
```xml
	<renderingAttribute name="waterwayArrows" attrIntValue="0"/>
```
but it does not works: always equal to 1. So I vote to solve this bug because for example in Amsterdam at zoom 14 they are really unnecessary and adds more clutter to map.

**Comment by xmd5a2** [comment]
![_2015-08-26_12-38-45](https://cloud.githubusercontent.com/assets/5829014/9490263/6d86b6ba-4bef-11e5-879b-2c743c4facc4.png)

**Comment by xmd5a2** [comment]
Fixed
```xml
	<renderingAttribute name="waterwayArrows">
		<case attrIntValue="0"/>
	</renderingAttribute>
```

**Comment by Barrocas** [comment]
Sorry, but that was not good, since the waterways direccion arrows were
just removed.

I know some users and a lot of mappers need that info, so it should be
available, or else we are regressing in the developments already made.

If some users prefer not to have the waterways direccion arrows, that
option could be available in the 'configure map' - 'hide' options, like for
example: 'hide waterway direccion arrows'.

>

-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by xmd5a2** [comment]
Ok. Waterway arrows are back but with less disturbing color.

**Comment by aceman444** [comment]
Yes, please leave the possibility to have the arrows, but make it configurable in the map settings.

**Comment by Barrocas** [comment]
Waterway direction arrows are rendered again, thanks.
but is it my impression, or did the arrows also get a little bit thicker?
I also noticed that the highways 'oneway' direction arrows now fail to render (reported in #2203), is this related?

**Comment by xmd5a2** [comment]
Yes, I made them thicker because old arrows were poorly visible in most conditions. You can now change their color:
```xml
	<renderingAttribute name="mainHighwayOnewayArrowsColor">
		<case roadStyle="highContrastRoads" attrColorValue="#000000"/>
		<case roadStyle="orange" attrColorValue="#000000"/>
		<case attrColorValue="#3a3e9c">
			<apply_if nightMode="true" attrColorValue="#000000"/>
		</case>
	</renderingAttribute>
           <case ......>
		<apply onewayArrowsColor="$mainHighwayOnewayArrowsColor"/>
           </case>
```

**Comment by Barrocas** [comment]
Thanks, they are ok, I have no problem with it's color.

-- 
Cumprimentos,
D.er Hugo Barrocas
