### ISSUE TITLE
Enhancements for elevation trip widget

### ISSUE THREAD

**Issue by CJam25** [osmandapp/OsmAnd#13305]
### Description

1. The text is cut off on my device.
2. With inclination disabled the green chart lines are still visible what is somewhat confusing.

![afbeelding](https://user-images.githubusercontent.com/76212814/144756394-ad0ec960-cc21-44eb-b4b5-981a5147bd74.png)

### How to reproduce?
Enable the widget.

### Your Environment
OsmAnd Version: 4.1.9
Android version: 11
Device model: Samsung Xcover 5 Enterprise

**Comment by dmpr0** [comment]
# Review
- [ ]  If text size is big, it doesn't fit too
<img src="https://user-images.githubusercontent.com/9365308/146918472-fb0afdf2-2e79-4e8f-85cf-de6b42d21940.jpg"  width="300" height="auto"/>
