### ISSUE TITLE
Flemish voice commands

### ISSUE THREAD

**Issue by CJam25** [osmandapp/OsmAnd#13304]
# 🚀 feature request

### Description

Some time ago Google introduced a new TtS engine to have a more familiar feeling for the dutch speaking Belgians. This would make voice navigation more enjoyable for Flemish people.

### Describe the solution you'd like

Would it be possible to add this TtS engine in OsmAnd as nl-BE? The text used for the voice commands could be the same as the current nl-NL.

**Comment by vshcherb** [comment]
Yes, we could check the region and provide NL-BE or NL-NL to TTS instead of simple NL

**Comment by cepprice** [comment]
[Resources](https://github.com/osmandapp/OsmAnd-resources/pull/761)
[Android](https://github.com/osmandapp/OsmAnd/pull/13420)

**Comment by cepprice** [comment]
Attention: nl-BE can be unavailable on device. If so, nl-NL will be used.

**Comment by vshcherb** [comment]
Linked to https://github.com/osmandapp/OsmAnd/issues/13737
