### ISSUE TITLE
Search issues - some amenities cannot be found

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#1331]
In release version 2.04 (paid, using your 5/24 maps of U.S. states Georgia & Florida), as well as nightly builds 2.1.0 #7605D and 2.1.0 #7648D.

For example, if you select this place http://osm.org/go/ZQq4SIcs5?way=295295206 and then Search Near Here, the Humane Society of Cobb County cannot be found by any means, whether by name, partial name, or custom filter and selecting all categories.  The same holds true for the Humane Society of the Treasure Coast http://osm.org/go/ZDzpdlxN0--?way=350411473 (although you *can* find the HSTC Thrift Store a few miles away by doing a name search for both "Humane Society" and "Humane Society of the Treasure Coast".  Oddly enough, *this* animal shelter http://osm.org/go/ZQq85BP~M?way=265430471 does show up, but I'm going to assume that it's because of one of the other tags.  It is listed in search results as "Yes Georgia House Rabbit Society" -- see the next paragraph for why I think that's the case.

Also, at least some POIs that are "shop=yes" show up in search results as "Yes <name of place>".  They should probably be listed as "Shop <name of place>" instead, although I think "shop" should be a lower priority tag if something else exists (such as amenity=animal_shelter), but that's open for debate.

Also also, some POIs show up when using the prelisted search categories, but NOT when a custom filter is used, even when a custom filter is selected.  See this thread for info:  https://groups.google.com/forum/#!topic/osmand/Z2wLZ79oB4E

**Comment by jfburke3** [comment]
Sorry, that last bit should have been, "even when all custom filters are selected."

**Comment by jfburke3** [comment]
This may be partially fixed now.

I hadn't tried it for a couple of weeks, but just downloaded nightly build 2.2.0 #8198D.  When I select the custom filter Tourism and all subcategories under it, it is now finding public restrooms near my search point.  Parks are also showing up now.

I still can't find animal shelters when I search by name (unless I use the 'search online with Nominatim' function), but at least the other POIs show up now when using the custom filter method described in the groups thread.

--jack

**Comment by xmd5a2** [comment]
Added animal_shelter to POI
https://github.com/osmandapp/OsmAnd-resources/commit/e09fe4e38063c0c7335787b189e3affde5105962

**Comment by jfburke3** [comment]
Thankx, xmd, but I guess this does confuse me slightly.  I guess what you did means that a place is not searchable by name if its category is not included in the OSMand xml?  That would omit an awful lot of places that y'all just haven't gotten around to including in the xml files, not to mention when new POI types get created.

**Comment by xmd5a2** [comment]
POI (ideally) need icons and translations. If we add everything present in OSM automatically that will not be consistent with other POIs.

**Comment by rriemann** [comment]
I have again the problem in the current osmand version from google play with updated maps that I cannot search for toilets in Lyon (France). Results are empty. However, the POI are on the map.
