### ISSUE TITLE
Use large font for "Distance by Tap"

### ISSUE THREAD

**Issue by speleoluc** [osmandapp/OsmAnd#13315]
The "Distance by Tap" transient widget should use the same large font as the persistent widgets like Time or Speed. It would add legibility for a number that's often displayed at an angle.

**Comment by dmpr0** [comment]
## ToDo

<table style="width:100%">
  <tr>
    <th>Off</th>
    <th>On</th>
    <th>Text size</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/184642822-d6092df9-e9aa-4cc5-8bd3-c50eb6763c6a.png"  width="260" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/184642825-555390bf-fe99-4d5b-a75e-ec4a84eb5918.png"  width="260" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/184642815-e3ecd17c-f250-4867-9877-53c7054ea597.png"  width="260" height="auto"/> </td>
  </tr>
</table>

**Comment by speleoluc** [comment]
Can the display delay be augmented or configurable? It's very quick right now.
