### ISSUE TITLE
Issue with the backup to OsmAnd Cloud

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#13327]
I cannot do a backup on your server, after arrive around a 50% it stops with a message "broken pipe" or something like that.
Device : gts3llte
Brand : samsung
Model : SM-T825
Product : gts3lltexx
Build : PPR1.180610.011.T825XXU3CTD1
Version : 9
App Version : OsmAnd+
Apk Version : 4.1.9 419

[logcat (4).log](https://github.com/osmandapp/OsmAnd/files/7676232/logcat.4.log)
12-07 02:30:31.393  1332  1905 E net.osmand: AndroidNetworkUtils Write error: ssl=0x7b0c095a08: I/O error during system call, Broken pipe
12-07 02:30:31.393  1332  1905 E net.osmand: javax.net.ssl.SSLException: Write error: ssl=0x7b0c095a08: I/O error during system call, Broken pipe
12-07 02:30:31.393  1332  1905 E net.osmand:   at com.android.org.conscrypt.NativeCrypto.SSL_write(Native Method)
12-07 02:30:31.393  1332  1905 E net.osmand:   at com.android.org.conscrypt.NativeSsl.write(NativeSsl.java:422)
12-07 02:30:31.393  1332  1905 E net.osmand:   at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLOutputStream.write(ConscryptFileDescriptorSocket.java:656)
12-07 02:30:31.393  1332  1905 E net.osmand:   at com.android.okhttp.okio.Okio$1.write(Okio.java:81)
12-07 02:30:31.393  1332  1905 E net.osmand:   at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
12-07 02:30:31.393  1332  1905 E net.osmand:   at com.android.okhttp.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:176)
12-07 02:30:31.393  1332  1905 E net.osmand:   at com.android.okhttp.okio.RealBufferedSink.write(RealBufferedSink.java:46)
12-07 02:30:31.393  1332  1905 E net.osmand:   at com.android.okhttp.internal.http.Http1xStream$ChunkedSink.write(Http1xStream.java:534)
12-07 02:30:31.393  1332  1905 E net.osmand:   at com.android.okhttp.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:176)
12-07 02:30:31.393  1332  1905 E net.osmand:   at com.android.okhttp.okio.RealBufferedSink$1.write(RealBufferedSink.java:198)
12-07 02:30:31.393  1332  1905 E net.osmand:   at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:255)
12-07 02:30:31.393  1332  1905 E net.osmand:   at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:212)
12-07 02:30:31.393  1332  1905 E net.osmand:   at java.util.zip.GZIPOutputStream.write(GZIPOutputStream.java:145)
12-07 02:30:31.393  1332  1905 E net.osmand:   at net.osmand.plus.settings.backend.backup.StreamSettingsItemWriter.streamCopy(StreamSettingsItemWriter.java:61)
12-07 02:30:31.393  1332  1905 E net.osmand:   at net.osmand.plus.settings.backend.backup.StreamSettingsItemWriter.writeToStream(StreamSettingsItemWriter.java:37)
12-07 02:30:31.393  1332  1905 E net.osmand:   at net.osmand.plus.backup.-$$Lambda$a62kKZbcCJAmqUn5YjLiDpemSeE.write(Unknown Source:2)
12-07 02:30:31.393  1332  1905 E net.osmand:   at net.osmand.AndroidNetworkUtils.uploadFile(AndroidNetworkUtils.java:656)
12-07 02:30:31.393  1332  1905 E net.osmand:   at net.osmand.plus.backup.BackupHelper.uploadFile(BackupHelper.java:479)
12-07 02:30:31.393  1332  1905 E net.osmand:   at net.osmand.plus.backup.NetworkWriter.uploadItemFile(NetworkWriter.java:111)
12-07 02:30:31.393  1332  1905 E net.osmand:   at net.osmand.plus.backup.NetworkWriter.uploadDirWithFiles(NetworkWriter.java:130)

**Comment by vshcherb** [comment]
The reason is quite unclear, probably it's possible to detect which file causes that error so we can investigate further. Probably it's too big.

Unfortunately for now without details we can't do much
