### ISSUE TITLE
Incorrect road number

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#13329]
Displaying incorrect road number. Mixes the numbers from the current road and closest road. 
Appear from the zoom level 15. 
52.26706° N, 4.96128° E
![image](https://user-images.githubusercontent.com/80623554/145232570-afbfe945-dc3a-445d-a90e-0799dd81222d.png)

OsmAnd 4.1#33201, released 2021-12-08
Map updated 1 Dec 2021

**Comment by vshcherb** [comment]
They are both A2 and E35
https://www.openstreetmap.org/way/79276795#map=18/52.26766/4.96115
https://www.openstreetmap.org/way/7052391#map=16/52.2719/4.9578
