### ISSUE TITLE
Crash when zooming in Finistère (Brittany)

### ISSUE THREAD

**Issue by hamlet** [osmandapp/OsmAnd#13325]
Hi.

For several months I've had troubles with OsmAnd+ crashing when zooming really close in the western part of Brittany.
I couldn't really find the exact extant of the problem, but it definitely happens in Quimper and the surrounding countryside, and not around Rennes for example.
The problem happens every time when I zoom more than 20m (when the scale starts displaying 10m, it freeze a little and then crash).
In other area it might be really slow, but it display down to 2m eventually.
It might be the same kind of problem than in this issue : https://github.com/osmandapp/Osmand/issues/6173

Map data and app up to date.

Best regards.

**Comment by xmd5a2** [comment]
I can confirm that rendering is really slow in Quimper
![Screenshot_2021-12-10-11-17-36-871_net osmand plus](https://user-images.githubusercontent.com/5829014/145540793-1a10a9e4-e39c-464b-a7e5-b6a693b33d49.jpg)

http://www.openstreetmap.org/?lat=47.9959176792315&lon=-4.1024244718801&mlat=47.9959176792315&mlon=-4.1024244718801&zoom=19

**Comment by hamlet** [comment]
Hi.
as said, it crashes even in the countryside, where mapping is simpler, below some screenshot just before the zoom level that crashes.
My phone is a Moto G4, with (only) 2GB of RAM, if it's useful to know.
Also I have quite a lot of layers activated (shading, contour lines, Notes, and others depending on the profile).
Please tell me if I should test with some or all options disabled.
Best regards.

![Screenshot_OsmAnd_20211210-094429](https://user-images.githubusercontent.com/22633/145557832-752086ea-27f5-481f-b46c-49eb39d43519.png)
![Screenshot_OsmAnd_20211210-094510](https://user-images.githubusercontent.com/22633/145557845-053368ff-1f0a-4464-827d-caef1504fdbc.png)

**Comment by ivanPyrohivskyi** [comment]
@hamlet I could not reproduce the crash. I was turning on the different layers and was profiling the using of memory.
Yes rendering was slow to 3 seconds depends from zoom.

Can you describe what layers you was turning on? Can you try to turn off all additional layers and test again. Perhaps it is specific layer problem.
According to you comment you had classical memory leak with crash.

For memory profiling you can use Android Studio or any app from Google Play (I like Simple System Monitor).

My test phone:
Redmi 4A
Android 7.1.2
RAM 2Gb
Maximal RAM using by OsmAnd app 175Mb
Map installed on internal storage

**Comment by ivanPyrohivskyi** [comment]
<img src="https://user-images.githubusercontent.com/1040293/147366623-f6a88d1b-36ed-40d5-aa7c-f3874e25b639.png" width="300"/> <img src="https://user-images.githubusercontent.com/1040293/147366627-0aafe139-8ce0-4f7f-af28-7d1a45ec021e.png" width="300"/>

<img src="https://user-images.githubusercontent.com/1040293/147366678-2c8f177a-24ef-494a-aabf-5d9cc58655d8.png" width="300"/> <img src="https://user-images.githubusercontent.com/1040293/147366680-c1252697-43e9-4551-ab7e-a70a94cebcd6.png" width="300"/>

 <img src="https://user-images.githubusercontent.com/1040293/147366753-c43c07de-3ab7-44d6-abd7-723fb6be565e.png" width="300"/> <img src="https://user-images.githubusercontent.com/1040293/147366711-88004512-a5f2-4b00-bb08-9d146fa808e6.png" width="300"/>
 
 
 <img src="https://user-images.githubusercontent.com/1040293/147366777-e69e4a0b-3185-4865-ad98-8d1a81371def.png" width="300"/> <img src="https://user-images.githubusercontent.com/1040293/147366780-e4b046d0-47ec-45dc-9121-8da03656808d.png" width="300"/>

**Comment by hamlet** [comment]
Hello,

I did try with all plugins and layers disabled. I even created a new profile (but as it's based on existing ones, I'm not sure it helps).

Anyway, same crash happens.
I also get crashes in Morbihan (around Hennebont) now.

I tried with  Simple System Monitor, memory climbs slowly to 70%, and then drops to 55% when OsmAnd crashes. Out of 1.8Go of RAM, it probably means up to 270Mo of memory usage. But the memory usage is kind of the same when I zoom in Rennes, and it doesn't crash.

My phone is Moto G4, with ArrowOS 9.0. Maps are on the SDcard.

Please tell me if I can run some more tests, or how to get a detailed crash log.

Oh, and browsing the settings of the development plugin, I've enabled "Safe mode", it doesn't crash anymore, even with all layers activated ! It even feel faster... What are the drawbacks of this safe mode ?

Best regards.

**Comment by vshcherb** [comment]
Safe mode shouldn't look faster, if it looks faster please use it in this mode cause it's supposed to work slower :-)

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-core-legacy/pull/66

<img src="https://user-images.githubusercontent.com/1040293/147366623-f6a88d1b-36ed-40d5-aa7c-f3874e25b639.png" width="300"/> <img src="https://user-images.githubusercontent.com/1040293/150783607-998860c2-6b0b-42fc-ad37-421eb2397b41.png" width="300"/>

<img src="https://user-images.githubusercontent.com/1040293/147366678-2c8f177a-24ef-494a-aabf-5d9cc58655d8.png" width="300"/> <img src="https://user-images.githubusercontent.com/1040293/150782451-245c1296-7448-4cce-b77e-de69b9bb185e.png" width="300"/>

 <img src="https://user-images.githubusercontent.com/1040293/147366753-c43c07de-3ab7-44d6-abd7-723fb6be565e.png" width="300"/> <img src="https://user-images.githubusercontent.com/1040293/150782318-a23ae39c-347c-4be3-8b1e-e18760667931.png" width="300"/>
 
<img src="https://user-images.githubusercontent.com/1040293/147366777-e69e4a0b-3185-4865-ad98-8d1a81371def.png" width="300"/> <img src="https://user-images.githubusercontent.com/1040293/150782217-9280d44b-841e-48ab-b56d-bde10fac5186.png" width="300"/>

 <img src="https://user-images.githubusercontent.com/1040293/147366934-dc16b138-bc0f-40d6-87d8-6f1a16b600cc.png" width="300"/> <img src="https://user-images.githubusercontent.com/1040293/150782116-2de97fed-ec01-4b25-8a71-261b51d73a29.png" width="300"/>
