### ISSUE TITLE
Status bar not show on 825_X Pro android 10

### ISSUE THREAD

**Issue by LeLuyen** [osmandapp/OsmAnd#13334]
Hi @vshcherb & All,

I tested on device 825_X

But not show status bar

How to fix?

https://forum.xda-developers.com/t/mtk-ac8257-nevegetor-full-825x-pro-info.4305281/

![image](https://user-images.githubusercontent.com/2620445/145435628-2d7117e8-e4b3-4c69-9128-9992a8b85910.png)

**Comment by vshcherb** [comment]
You can probably disable "Full screen mode" or check Developer Settings -> VM Overscan setting

**Comment by LeLuyen** [comment]
Hi vshcherb,

Thank you for your reply.

I used activity.getWindow().addFlags(WindowManager.LayoutParams.FLAG_FORCE_NOT_FULLSCREEN);

it can resolve.
