### ISSUE TITLE
Issue with the track displaying in the landscape mode

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#13337]
### Description
1. Selecting a track from “my places” does not center the map to that track. 
2. The marked button “(back to) tracks” has no function (does not react at all) and does not bring me back to my tracks.
![image004](https://user-images.githubusercontent.com/80623554/145561531-29abb2cb-4ad7-4115-ba04-8aba1ea0369f.jpg)

### How to reproduce?
In the landscape mode select any track from the My places menu.

**Comment by dmpr0** [comment]
# Review
- [ ]  "Show on map" button is placed lower than "Tracks" button.
<img src="https://user-images.githubusercontent.com/9365308/148256036-0312bf44-2ff7-480a-8e48-b82fc284dd4c.png"  width="auto" height="auto"/>

**Comment by nazar-kutz** [comment]
Fix "Show on map" button is placed lower than "Tracks" button: https://github.com/osmandapp/OsmAnd/pull/13600
