### ISSUE TITLE
Automatic alignment in the direction of motion does not work.

### ISSUE THREAD

**Issue by RUMO-Barsoom** [osmandapp/OsmAnd#13331]
### Description
Automatic alignment in the direction of motion does not work.

### When
Always

### How to reproduce?
By every Ride.

ment
OsmAnd Version: 4.0.9
Android/iOS version: 10
Device model: SHIFT6mq

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by vshcherb** [comment]
Please double check that you've set 3rd position on the compass icon (blue arrow) - https://docs.osmand.net/en/main@latest/osmand/map/interact-with-map#map-orientation--compass

![telegram-cloud-photo-size-4-5877632486987643949-y](https://user-images.githubusercontent.com/1042025/145387837-07009676-e639-405b-83cb-b45c67385a7e.jpg)

And the map should rotate to the movement direction.
