### ISSUE TITLE
OsmAnd+ does not render national parks (but does render nature reserves)

### ISSUE THREAD

**Issue by VorpalBlade** [osmandapp/OsmAnd#13335]
### Description

It seems that OsmAnd+ does not properly render national parks, while nature reserves are correctly rendered. See the following screenshot and compare to the website: https://osmand.net/go.html?lat=59.27865&lon=14.88315&z=13

![Screenshot_NationalPark](https://user-images.githubusercontent.com/3315306/145463064-609b786c-7824-490c-901d-c40fe2771399.jpg)

Compare this with a nature reserve (https://osmand.net/go.html?lat=59.08707&lon=14.83464&z=15):
![Screenshot_NatureReserve](https://user-images.githubusercontent.com/3315306/145463418-2779e32d-9df1-42ac-8133-e9a6458376de.jpg)

I have also checked a couple of other national parks in Sweden and they all have the same issue of display in the app. It also does not appear to be an issue of zoom levels.

I would expect national parks to be rendered in a similar manner to nature reserves (perhaps with "NP" instead of "NR" over the background?) At the very least they should be rendered in some way.

### How to reproduce?

Download Swedish maps and look at nature reserves (clear borders as well as a background of "NR" overlaid on the area) and national parks (nothing). One example of each is provided above in the description section.

### Your Environment
OsmAnd Version: OsmAnd+ 4.1.9
Android: Android 11 (OxygenOS 11.1.1.1) 
Device model: OnePlus 6

**Maps used (online or offline):**
I use the vector map for Sweden downloaded via the app. This issue has been around for a while (a few months at least).
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by xmd5a2** [comment]
Nature reserves and national parks can be hidden by option "Configure map - Detail - Nature reserve". Please check it.

**Comment by VorpalBlade** [comment]
> Nature reserves and national parks can be hidden by option "Configure map - Detail - Nature reserve". Please check it.

Well, the problem is that national parks don't show up but nature reserves do, so I wouldn't think that is it. Also I can't find that option, and checking "more details" in that menu changed nothing:

![details-menu](https://user-images.githubusercontent.com/3315306/145803291-4fd48cb2-e63c-4950-bc07-c6f6abd74117.jpeg)
 
Changing map styles (e.g. car, walk, bus, ...) had no effect either.

**Comment by VorpalBlade** [comment]
After some further experimentation, the option does show up in the "Details" sub-menu if I switch "Map style" from the default "OsmAnd" to "Touring View". Then "Nature reserve" toggles both nature reserves and national parks being displayed.

With that new knowledge I guess this bug pertains specifically to the default "OsmAnd" map style not displaying national parks but displaying nature reserves. I would prefer to see both in this style (possibly with an option to turn it off, not that I would ever use that). But at least it should be consistent. I personally prefer the "OsmAnd" style to the "Touring View"

**Comment by xmd5a2** [comment]
I don't understand what are you talking about. `leisure=nature_reserve` and `boundary=national_park' are displayed correctly in OsmAnd style.
![Screenshot_2021-12-13_14-53-06](https://user-images.githubusercontent.com/5829014/145808112-72f53282-5e72-4a77-a594-82317876dfce.png)
![Screenshot_2021-12-13_14-55-23](https://user-images.githubusercontent.com/5829014/145808108-bc78ce36-c7cf-4e15-972e-1fdb1f620a02.png)

**Comment by VorpalBlade** [comment]
That is really strange. It doesn't look like that on my phone (see the two screenshots in the initial post of this bug). I could try installing OsmAnd clean on my old phone again (I really don't want to have to redo all settings and redownload the maps on my current phone if I don't have to) to see if it is some weird bug that goes away with a reset?

**Comment by VorpalBlade** [comment]
This is really strange: On my old phone (with the clean install) the "Nature Reserve" option is there in the details menu when using the "OsmAnd" style. On my new phone (that I have been using for a few years) that is not the case. Any idea why that might be?

**Comment by VorpalBlade** [comment]
Not sure if this is relevant, but, there are some other option visibility that are different as well:
* "Settings -> Browse Map (or any other profile) -> General Settings" is missing the option "Use magnetic sensor" on the old phone, but it is there on the new (and turned off, which is good since the gyro and compass are broken on my newer phone).
* The "Hide" menu when the "OsmAnd" map style is selected is missing the "Hide water" option on the new phone.
* The "Details" menu is missing more than just "Nature reserve", also "Show Low Emission Zones" is missing.
* One menu level up it says "Details  0/7" on the new phone (count is correct) but it says "Details 0/10" on the old phone. However there are only 9 items under that menu!
* If I select "Street lighting" under details on the old phone I get options for "Always" and "Night map" (maybe this is the missing 10th option?). That doesn't happen on the new phone.

Is it possible I somehow have an older version of the OsmAnd mapstyle? And if so, why wasn't it updated together with the app itself. And how do I fix it?

**Comment by xmd5a2** [comment]
What is you OsmAnd version? Look at "Help - About"

**Comment by VorpalBlade** [comment]
As stated in the initial post of this bug report, it was 4.1.9. Since that point it has been updated to 4.1.10 (which still exhibit this behaviour). See screenshot below.

![Screenshot_20211214-114927](https://user-images.githubusercontent.com/3315306/145984305-0733378a-2c4b-4e80-97d8-0c734db253c7.jpg)

**Comment by tradavyvy** [comment]
As a side-note, i would strongly support the different letter for different things aproach.
NR - nature reserve
NP - national park
And if the underlying data supports it more sorts
NM - national monument
NF - national forrest
And so on...

All of caurse within reason so as not to polute the map with things as CR for Cow raising area and FWDMRFOW - Forrest where dogs may run free on wednesdays ...

**Comment by VorpalBlade** [comment]
The issue seems to have resolved itself recently. I don't know if it was when updating to 4.1.11. But the first time I opened the app after that update (on new years eve), the missing menu option were there. Without the need for a clean reinstall. All functionality seems to work as expected.
