### ISSUE TITLE
Navigation is ending on an expressway

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#13344]
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=-27.4757%2C153.0160%3B-27.4751%2C153.0258#map=18/-27.47513/153.02675
<table style="width:100%">
  <tr>
    <th>OSRM</th>
    <th>OsmAnd, destination selected by address search</th>
    <th>OsmAnd, destination selected manually</th>
  </tr>
  <tr>
    <th valign=top><img src="https://user-images.githubusercontent.com/9365308/145554791-74fbe78f-2d36-458c-8ae0-23a8d002ab13.jpeg"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/9365308/145554684-d9431cc8-b1d5-4312-80a5-0c85887ebde8.jpeg"  width="200" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/9365308/145554854-b0298843-a7c1-46c6-8f31-cd8a99831bf8.jpeg"  width="200" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
4.3.0.13 **Not reproduced**
