### ISSUE TITLE
Mark/download all maps of a region

### ISSUE THREAD

**Issue by meteficha** [osmandapp/Osmand#1334]
Right now one has to manually click on every map of a region. It would be great if there was some way of marking all packages of a region for download with a single tap or long tap.

**Comment by sonora** [comment]
I think this would be subject to an overall change in how we present the hierarchy of maps for a region, as we have many different types like "regular maps", road-only maps, srtm, hillshades, etc.

Let me close this for now unless we want to re-visit how we present that interface.
