### ISSUE TITLE
Cannot directly launch GPS Status & Toolbox app by tapping the 'GPS status' button in the Main screen

### ISSUE THREAD

**Issue by Max1234-Ita** [osmandapp/OsmAnd#13346]
### Description
I have installed GPS Status & toolbox v. 11.0.307 on my  smartphone; The app is properly working if I launch it from the Home.

In OsmAnd, if I tap the _GPS status_ button in the right panel of the main screen (the one with the "satellite" icon), I get a pop-up message asking what GPS helper app i wish to run ( GPS Connected, GPS Status & Toolbox, GPS Test, etc.).

If I select _"GPS Status & Toolbox"_, a message pops up, saying the app is not installed, and asking for permission to search it in the market;  as I said before, the app is actually installed from Google Play store. Anyway, I tap "Yes" and  Google Play store opens: obviously, I see no "Install" button, but "Open", instead.

And if I tap the Open button, _GPS S&T_ starts up.

### How to reproduce?
1. Have _GPS Status & Toolbox_  app (by MobiWIA Kft.) installed in the device under test;
2. Open OsmAnd and wait for the map screen to be displayed;
3. In the map screen, tap the "satellite" icon in the right panel: A list of GPS helper apps is shown;
4. From that list, select "GPS Status & Toolbox".
 
As expected behaviour, the mentioned app should start, a pop-up messsage is displayed instead, with message _"App stato GPS non installata. Cercarla in Market?"_ (English translation: _"App GPS Status not installed. Search it in the market?"_)

![image](https://user-images.githubusercontent.com/15315381/145644318-8117000e-8850-4fd4-97ba-458b14d6af7f.png)

5. Tap "Yes", and Google Play Store opens;
6. If the "Open" ("Apri", in the attached picture) button is selected, the app starts and works normally.

### Your Environment
OsmAnd Version: 4.1.9, released 2021-11-27
Android/iOS version: Android  v. 11
Device model: Samsung Galaxy A50 (SM-A505FN/DS)

**Maps used (online or offline):**   Offline, properly working.

**Comment by Axel-Be** [comment]
Exactly the same here on a Samsung Note 20 Ultra 5G (SM-N986B/DS), running Android 11 (One UI 3.1) and OsmAnd+ 4.1.9.
I even uninstalled GPS-Status & Toolbox, tried again, followed the prompt to Google Play, installed GPS Status & Toolbox again. It showed the same behaviour afterwards.

It works on my old Samsung Note 8 (SM-N950F) running Android 9 (One UI 1.0), same OsmAnd+ version.

**Comment by pebogufi** [comment]
See discussion in
https://groups.google.com/g/osmand/c/AN_XkBCuSgc
No problem with Android 10.

**Comment by vshcherb** [comment]
4.1.10  should open external apps better than 4.1.9

**Comment by Max1234-Ita** [comment]
It doesn't look so...

I just tried OSmAnd v.4.1.10 (updated today); I also installed the following apps into my smartphone:

- GPS Connected (by Diego Ferreira)
- GPS Status & Toolbox (by MobiWIA kft.)
- GPS Test (by Chartcross Limited)
- GPSTest (by barbeauDev)
- SatStat (F-Droid)
- GpsTest (F-Droid)

The wrong behaviour is present for each and every one of them (app installed -> not found -> search on market)
And BTW, if I choose to search on Market for SatStat (F-Droid) and GPSTest (F-Droid) I am routed to Google Play instead (I have F-Droid too, in my device).

Please reopen the ticket.

Kind regards,
Max

**Comment by Chumva** [comment]
Similar issue https://github.com/osmandapp/OsmAnd/issues/13369

**Comment by Chumva** [comment]
This should be fixed here https://github.com/osmandapp/OsmAnd/pull/13380 fix will be in 4.1.11

**Comment by Max1234-Ita** [comment]
Thank you very much.
I'll check after v.4.1.11 is released.

Kind regards,
Max

**Comment by Max1234-Ita** [comment]
I've just updated to v.4.1.11; Tried all the esternal applications I mentioned above and they are launched properly from within OsmAnd.

Thanks for your work!
Massimo

**Comment by Axel-Be** [comment]
It works for me too with v4.1.11. 

Thank you very much for the quick solution!
Axel
