### ISSUE TITLE
Seacrhing doesn't work in Latin if names are in Cyrillic

### ISSUE THREAD

**Issue by knjigor** [osmandapp/Osmand#1335]
Hi, I have recently discovered Osmand and I rely love it but I have found some issues that I think should be fixed:
I live in Vojvodina Serbia and national language is Serbian Cyrillic, but as we are multi-cultural region there is a lot of people that use only Serbian Latin (I'm one of them) and doesn't want to use Cyrillic letter. Problem related to this is that 90% of map items are in Cyrillic and have they translation to English (very poor) and they transliteration to Latin (sr-Latn), but when you try to search for address (if map language is set to Serbian) in Latin, you don't get any results (in similar applications as Navigator there is automatic search transliteration).
I think that this could be solved by translating Osmand to Serbian Latin (I have done that already) and add it as new language, or with automatic transliteration in search.

**Comment by knjigor** [comment]
Translation to Serbian Latin https://github.com/knjigor/Osmand/commit/51fd3b0247f5e0f3b119e664e67a292c47b7b101

**Comment by sonora** [comment]
Is this still open?

**Comment by knjigor** [comment]
As far as I can see, nothing hase changed.

**Comment by sonora** [comment]
How about your Latin translation, would it solve the issue if we implemented that in OsmAnd?

**Comment by knjigor** [comment]
I can translate it again (I can't remember where I have put translation), but it wont solve an search problem because it should be done in app core, either there should be an transliteration utility that would search Cyrillic names trough Latin script, or translators and mappers should transliterate names on map levels. 

I don't have time this days to do translation, but I will done ti in next few weeks (2-3).

**Comment by knjigor** [comment]
I have just tested app and it seems that this problem i solved, all names that are on Cyrillic can be searched even if you use Latin.

Translation to Serbian Latin is here:
https://github.com/knjigor/Osmand/tree/master/OsmAnd/res/values-sr-rLATN

**Comment by sonora** [comment]
Ok, thanks. Regarding the Latin sr Locale: I am having trouble compiling that, receive
`values-sr-rLATN: Error: Invalid resource directory name`

Found this link http://stackoverflow.com/questions/15518597/how-to-include-2-variants-of-serbian-language-with-latin-letters-and-with-Cyril, we may need a bit more work if we want to merge your translation.

**Comment by sonora** [comment]
I think I got it to work by changing the region to a 2-letter "LA". It is now merged and can be maintained in Weblate.
