### ISSUE TITLE
OsmAnd is not choosing the optimal route

### ISSUE THREAD

**Issue by gerhard-tinned** [osmandapp/OsmAnd#13356]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Selected profile: Driving (Car)

### Start and end points

Navigation from here: 
48.21240° N, 16.52247° E
https://osmand.net/go?lat=48.212398624011136&lon=16.52247190475464&z=17
https://www.openstreetmap.org/way/819935919

To this destination:
48.25740° N, 16.44389° E
https://osmand.net/go?lat=48.25739669799805&lon=16.443893432617188&z=13
https://www.openstreetmap.org/way/563954846#map=19/48.25739/16.44391

### Actual and expected routes

The original route is shown in the Screenshot ![OamAnd_route_better](https://user-images.githubusercontent.com/1536065/145711584-df2c8eb7-a614-432d-ad13-68f768562f3a.png). As soon as I went a slightly better route (shorter and faster) the estimated arrival time reduced by about 6 minutes. 

The Red line added is the route I went - which is short and faster (even OsmAnd calculates a shorter driving time) while the blue one is the calculated longer one. 

On the route back it is similar (slightly different whey out of the oneway streets but then again the longer way is calculated and when I took a turn on the better route, the time change to 5-6 minutes less. See Screenshot![OamAnd_route_back_better](https://user-images.githubusercontent.com/1536065/145711577-8ceef7b2-b023-4fa1-a20a-038d928fabff.png)

I am not sure why this is happening, but I noticed this behavior in the past with even bigger difference. As I was in an area I did not know so well, I was not sure about it. But this is a nice example. 

I could not figure out if the reason is something in the map or if it is in the routing. Maybe you can help with this. I also tried to attached the logs but github could not upload it.

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

As stated I have seen similar behalviour in the past. I have also tried to toggle on / off the "Fuel-efficient way" option but enabling it made it even worse in most cases. 

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

Device : OnePlus8
Brand : OnePlus
Model : IN2013
Product : OnePlus8_EEA
Build : IN2013_15_211009
Version : 11
App Version : OsmAnd
Apk Version : 4.1.10 420

OsmAnd 4.1.10, released:2021-12-08
</code></pre>

**Device and Android/iOS version:**

<pre><code>
Device : OnePlus8
Brand : OnePlus
Model : IN2013
Product : OnePlus8_EEA
Build : IN2013_15_211009
Version : 11
App Version : OsmAnd
Apk Version : 4.1.10 420

Android 11 based Oxygen OS 11.0.9.9.IN21BA
</code></pre>

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**

I noticed similar inefficient routing in the past as well. Sadly I did not collect any details for them.

**Comment by vshcherb** [comment]
You probably could use "Driving - Economy Fuel profile". I could confirm that this routing is done on purpose to not overcut major roads, even though this shortcut is faster but the routing prefer to stay on the same road rather than switch and go back to the same major road.

**Comment by gerhard-tinned** [comment]
Where do i find this profile??? I have only a "Driving" profile. In case you refer to the "Fuel efficient way" option, it doe not xhange anything for tha route. But I had even worse experience with that option as described already.

**Comment by vshcherb** [comment]
The difference between 2 routes is almost negligible:
- https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=48.2475%2C16.4435%3B48.2151%2C16.4922 (6.6 km, 0:11)
- https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=48.2487%2C16.4456%3B48.2151%2C16.4922 (6.5 km, 0:11)
2nd option:
- https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=48.2498%2C16.4380%3B48.2151%2C16.4922 (7.1 km, 0:12)
- https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=48.2493%2C16.4379%3B48.2151%2C16.4922 (6.7 km, 0:11)


The routes are almost the same in terms of optimal

**Comment by gerhard-tinned** [comment]
All of those 4 routes are equally bad, I agree. None of them follows the optimal route shown in the screenshots above. Which saves approximately 5 - 7 minuted based on what I have seen when I diverted to that route.

**Comment by Lee-Carre** [comment]
While I'm all for refining software for better results, do keep in mind that these are *suggested* routes.

It's unlikely that any routing algorithm will ever be perfect in all situations. Though, I do wonder if a variable to have the driving profile router choose the *shortest* route might help in some cases.

Make use of the described feature; deviate from the suggested route when you see fit, and OsmAnd will recalculate.

**Comment by gerhard-tinned** [comment]
> While I'm all for refining software for better results, do keep in mind that these are _suggested_ routes.
> 
> It's unlikely that any routing algorithm will ever be perfect in all situations. Though, I do wonder if a variable to have the driving profile router choose the _shortest_ route might help in some cases.
> 
> Make use of the described feature; deviate from the suggested route when you see fit, and OsmAnd will recalculate.

As this comment is due to a different ticket, I would like to add the related screenshots as well for reference. This route has also a different issue but that other issue is discussed in the other ticket #13740.

![Osmand_BAD_route](https://user-images.githubusercontent.com/1536065/153818255-9b7fd389-0bd7-4c8e-8bca-b11241db7e9d.jpeg)

The better route (and possible one suggested by me and also a different OSM offline routing app is this one. 
![Correct routes](https://user-images.githubusercontent.com/1536065/153818559-4b8e98ba-e175-498a-bd58-50020580dc45.jpeg)

The detour calculated by Osmand is much longer in distance and in time.

**Comment by gerhard-tinned** [comment]
Maybe this ticket can be reopened? I do not see how I could reopen it. Thanks.

**Comment by gerhard-tinned** [comment]
> While I'm all for refining software for better results, do keep in mind that these are _suggested_ routes.
> 
> It's unlikely that any routing algorithm will ever be perfect in all situations. Though, I do wonder if a variable to have the driving profile router choose the _shortest_ route might help in some cases.

Such a setting for "shortest" or "fastest" route would be awesome.

> 
> Make use of the described feature; deviate from the suggested route when you see fit, and OsmAnd will recalculate.

I stated in this ticket exactly that. I found a 6 minutes faster route just by diverting from the route. As explained in the other ticket in detail, that is only possible if you already know a better way to the destination which makes using a navigation app kind of pointless.
