### ISSUE TITLE
Switching between Map Orientations does not restore North Up correctly

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#13368]
### Description
When you configure orientation mode for “Browse map”  - “north always upward” and “Driving”  profiles - “to moving direction”, if you rotate the map in Driving profile and then switch to Browse map profile the map will be turned to "moving direction”. You need to press on the compass widget to rotate the map for the “north always upward” position.

### How to reproduce?
1. Configure map orientation for the “Browse map” profile - “north always upward”
2. Configure map orientation for “Driving” profile  - "moving direction”,
3. In the Driving profile rotate the map

![image](https://user-images.githubusercontent.com/80623554/145980347-816dcac2-f680-4f4a-8afd-99e90f0ffc1a.png)

### Your Environment
OsmAnd Version: 4.1.10
 Tab S6, S20+, LG7 / Android 10, Android 11

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by Rowin63** [comment]
Switching back to the "browse map profile" does correctly switch to "north always upward", as you can see, marked in my screenshot. But the map remains upside down or however it was displayed before. until you touch the orientation button again.

**Comment by vshcherb** [comment]
We need to link / retest bug with manual saving map orientation...

**Comment by mmh-dev** [comment]
https://github.com/osmandapp/OsmAnd/pull/13613
