### ISSUE TITLE
Osmand ignores no toll option

### ISSUE THREAD

**Issue by MPW1412** [osmandapp/Osmand#1336]
Hello,

the no-toll-option has some bugs. Here's an example, I want to travel from Basel to direction France and don't pay toll, because I don't have a Vignette (swisse toll system).

![screenshot_2015-06-11-15-05-47](https://cloud.githubusercontent.com/assets/1448950/8108383/4c23d56e-1050-11e5-93bd-64836013ddd8.png)

As you can see on the screenshot, osmand sends me via the highway, although there is that orange and yellow street to cross the boarder. On the french side there is no toll on that part of the highway. Both, Swiss and French, highways are tagged correctly.

So this is an routing issues.

Thanks for reading
MPW

**Comment by Zahnstocher** [comment]
I can't find toll=yes on the route shown at your screenshot:
https://www.openstreetmap.org/way/296091820
https://www.openstreetmap.org/way/296269704
https://www.openstreetmap.org/way/25307428
https://www.openstreetmap.org/way/25307518
https://www.openstreetmap.org/way/25791877
https://www.openstreetmap.org/way/318951206
https://www.openstreetmap.org/way/30847399

**Comment by MPW1412** [comment]
You're right, I checked the highway itself, but there's no toll on the feeder street. Strange, I'm a little unsure right now, weather you need to pay to pass over to France. So I didn't correct it.

Closed.
