### ISSUE TITLE
Bicycle routing: OsmAnd jumps between road and sidewalk

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#13361]
In bicycle routing OsmAnd jumps from the road to the sidewalk and back:

![photo_2021-12-13_13-54-23](https://user-images.githubusercontent.com/1040784/145816418-f6b0bff6-7887-40f4-887d-8025be963037.jpg)

From: 51.0503987,13.7752891
To: 51.0420752,13.7670922
Export: 
[route.gpx.txt](https://github.com/osmandapp/OsmAnd/files/7703972/route.gpx.txt)

This can be fixed with the help of via points:
![photo_2021-12-13_13-54-17](https://user-images.githubusercontent.com/1040784/145816618-b15c646b-19e1-4fe8-8d3d-1953b557a0f9.jpg)

However, this depends on the position of the via points. Some solutions won't work:
![photo_2021-12-13_13-54-20](https://user-images.githubusercontent.com/1040784/145816701-d1b84621-58e3-4c1f-a4cc-7cdc97a35688.jpg)
(This is probably a separate bug).

I guess the cause of this strange routing decision is the infamous traffic signal penalty.

**Comment by Zirochkabila** [comment]
**Reproduced** 

When using Driving style **Balance**
the route is built as follows https://osmand.net/map/?start=51.048581%2C13.773476&end=51.042129%2C13.767049&mode=bicycle#16/51.0454/13.7713 time 5 minutes, cost 153
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/193285590-bcd1cfb1-3e8f-4c81-acbb-3254a6a1f9df.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  


When using Driving style **Speed**
https://osmand.net/map/?start=51.048581%2C13.773476&end=51.042129%2C13.767049&mode=bicycle#16/51.0455/13.7717 time 6 minutes, cost 159
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/193285719-f5d66342-13b0-484f-acd9-783610a7a5f2.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

Changepoint
https://osmand.net/map/?start=51.046762%2C13.771711&end=51.042129%2C13.767049&mode=bicycle#16/51.0445/13.7730 time 6 minutes, cost 115

Bicycle OSRM looks like Balance style
https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=51.0475%2C13.7725%3B51.0418%2C13.7668#map=16/51.0448/13.7710

Bicycle GraphHopper looks like Speed style
https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=51.0475%2C13.7725%3B51.0418%2C13.7668#map=16/51.0449/13.7704

**Comment by dmpr0** [comment]
# Review
<table style="width:100%">
  <tr>
    <th>iOS</th>
    <th>Android</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/203056418-ce2a386e-9c4d-4ec4-b2fd-51fb940cc75d.PNG"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/203056709-cf053665-b4a3-4bf4-bf13-acffdb60ee1f.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
4.3.0.34
Driving style: Balanced
Germany - Saxony 01.11.2022, 02:00

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/203077923-d25fa70c-1d31-411a-85ba-6903d9b25bb6.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>
