### ISSUE TITLE
In OsmAnd Contour lines plugin does not work (after 4.1 release)

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#13369]
After the OsmAnd update to 4.1.10 the Contour lines plugin does not work anymore. Contour lines do not display on the map and disappear from the Download maps list.

The Contour lines plugin that was purchased as a separate application does not work.

**Comment by Chumva** [comment]
This should be fixed here - https://github.com/osmandapp/OsmAnd/pull/13380
