### ISSUE TITLE
custom folder problem from 4.1.9 to 4.1.10

### ISSUE THREAD

**Issue by tommycrock** [osmandapp/OsmAnd#13389]
### Description
Osman's 4.1.10 can't see the files that I'd just imported to 4.1.9 in a new custom folder under download

### How to reproduce?
On the changes introduced in 4.1.9 I setup a custom osmand folder in storage/emulated/0/download/net.osmand.plus/ so I could access tracks and avnotes created in osmand. When osmand updated to 4.1.10 it loads the 'Get started' page. It says my storage location is the same folder but doesn't seem to recognise any map files in it (tracks and favourites seem to still be displayed). 

I tried using the migrate folder option and pointed osmand to the folder. It says it can't find any osmand data in the selected folder. When I use a file manager I see many maps still in that folder.

### Your Environment
OsmAnd Version:4.1.10
Android/iOS version:11
Device model: Samsung s10e

**Maps used (online or offline):**   
All offline

**Comment by sonora** [comment]
See my comment in #13352.

**Comment by sonora** [comment]
Giving good advice is tricky here, it depends on what you want to achieve:
- I personally depend on OsmAnd for traveling, expeditions, and professional use. I simply stay with version 4.0.x for now.

If you need to or want to upgrade to 4.1.x: 
- If your non-removable external storage is big enough (you can park not needed maps elsewhere), and if you want to avoid the performance issues some devices experience with removable SD cards now, and if you need easier access to files from outside OsmAnd (some hints here https://github.com/osmandapp/OsmAnd/issues/13254#issuecomment-984661388), you could use the default External Storage 1.
- If you are pressed for space, and don't need file manager access to the data, you can try Ext Storage 2 and check out the performance.
- In any case if you are paranoid maybe simply remove your SD card before doing anything and create a backup of the old OsmAnd folder using a card reader.
- Last not least you could compile your own version of OsmAnd using targetSDK=29, that also circumvents all issues for now from what I see...

**Comment by tommycrock** [comment]
Thanks for the advice. I am already on 4.1.10 and don't know how I would downgrade. I don't know how to compile my own version of osmand either. I have sufficient space on my non-removable storage, that's where I'm keeping my files currently, but I would like access to them from other specific apps (not just a particular file manager). I can switch to using Vespucci for tracks and photos. 

I'm not sure of the steps to reinstate my osmand files in a working order since the migration option doesn't work.

**Comment by sonora** [comment]
In v4.1.x, migration **to** any "not allowed" folder should fail with an error because under Android 11+ OsmAnd 4.1.10 cannot write to these folders any more.

Migratition **from** an arbitrary  folder should still work if that folder was in use in OsmAnd prior to updating OsmAnd, so OsmAnd 'knows' from where to copy existing files.

If for some reason your OsmAnd data files are in a folder where OsmAnd cannot currently see them (looks like this may be your issue here?), I would say set OsmAnd to use the standard Ext Storage 1 path (which will default to something like /storage/emulated/0/Android/data/net.osmand(.plus) ). Then, after that folder has been initialized by OsmAnd, i.e when OsmAnd suggests to download maps as it has none in there, close OsmAnd and use a file manager or better a USB connection to manually transfer all old OsmAnd data folders and files there.

Other than the hints in my post above, I currently know of no viable way to co-use OsmAnd data with other apps. 😢

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/13254

**Comment by tommycrock** [comment]
An update: osmand automatically updated to 4.1.11 and my maps are working again... 

(Sorry, not sure about the etiquette of posting here after it's been merged but it's not going to make sense over there)

**Comment by tommycrock** [comment]
@sonora thanks again. Given this has resolved itself I haven't tried these suggestions. I was reluctant to because I thought if osmand didn't write the files they wouldn't be recognised, but maybe that's only true in the download folder. The migration process appeared to be asking me where the files already were, so I was pointing the file picker at the download folder that it already knew was the location of my maps (/storage/emulated/0/download/net.osmand.plus). The error message then suggested it could see that folder in principle but didn't recognise the files (or maybe couldn't see them) - 'can't find any osmand data in the selected folder' or similar. As I said above, for some reason they are recognised again in 4.1.11 🤞 it stays like that!

**Comment by Pastim** [comment]
It was running OK (using /storage/2614-1710/Android/data/net.osmand.plus), but I then recently found 'shared' route gpxs were being truncated when sent by email or attempting to copy to shareable storage (this was working up and until only a few days ago).   So I tried  /storage/2614-1710/Download/Osmand, and in 4.1.11 it now works as it used to, all files accessible externally.  Good!
