### ISSUE TITLE
Apply appearance to more than one track 

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#13388]
# 🚀 feature request

### Description

Osmand has no possibility to edit more than one track in one go (colour, width, show arrows, etc).
It is very laborious, to edit a bunch of tracks one by one by one…

### Describe the solution you'd like

Possibility to select more than one track from the "my places"-menu and edit them in one go.
Or:  set colour etc to a group/folder in the my places menu (like tracks, import, rec, routes, ...), and each imported track gets his settings from the folder it´s in

### Describe alternatives you've considered

doing it one by one by one...

**Comment by vshcherb** [comment]
It's actually possible! Go to Configure Map -> Tracks and you could modify for all selected tracks

**Comment by Rowin63** [comment]
aaaah, I see - thanks. 
But, this functionality is very unexpected hidden where it is to find (editing tracks not from the "track menu", but from the "map menu"...). 
I tried it this way - but this is a rather inconvenient possibility, especially if there are already various different styles of tracks displayed in the map.  In this menu I have to deselect about 2/3 of my already displayed tracks to edit the rest. After that, all the tracks I set before to be shown in the map are not displayed anymore, only these edited ones. Then I have to start over from the beginning, displaying all the various tracks I want to see (it is not possible to check them again from here, from this menu, where I´m in right now, because then they will be edited too). I have to go back to the track section in the my places menu to display all  the different tracks again...).

Yes, it´spossible this way.
But no, thats too much "work" around, and especially a very inconvenient way.

**Comment by Rowin63** [comment]
It would be sufficient to set the appearance by folders from the "my places"-menu. 
And, when adding/importing a track to a certain folder, to apply it´s settings automaticially ;-)

**Comment by Rowin63** [comment]
Thank you 👍

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14192mqta, Released: 2023-02-21
Done

**Comment by Rowin63** [comment]
Looks good, but I have to find out how it works in detail, to use it properly.
Comment: the swich down left I suppose should be "deselect" and not "hide" ("alle ausblenden" german translation)?
Seems to become a great tool!

Thanks!

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14201mqta, Released: 2023-02-25
Done
