### ISSUE TITLE
POI context menu: phone/website/... shortcut missing for "contact:"-scheme

### ISSUE THREAD

**Issue by Marmo** [osmandapp/Osmand#1339]
In the POI context menu there is a shortcut to call the phone number which is in the POI's "phone"-tag (also shortcut to website etc.). These shortcuts are missing, if the POI uses the "contact:" scheme for phone, website, mail, ...

**Comment by OpenSourceForEver** [comment]
Follow this steps:
1. Long press in PDI when it is showed with the orange circle.
2. Short press in info black box.
3. Select the option you want.

**Comment by Marmo** [comment]
Ok, following your 3 steps yields the following results:
1. Long pressing the orange POI circle for way 290142392 (centraHotel in Schwedt/Oder, Brandenburg, Germany) opens a black info box with the following info:
[Name of the POI]
Website: [POI website]
Addr:housenumber: [POI house number]
Contact:phone: [POI phone]

2. Short pressing that box opens the POI context menu with the following options (among others):
Show POI description
...
Show POI website
...

3. The options I want are missing (show POI phone, show POI e-mail)

The way 290142392 has these tags:
contact:website=...
contact:phone=...
contact:email=...
and still some more but irrelevant tags.

The missing options in 3. are present as expected when the POI uses the "classic" scheme (phone=..., email=...) instead of the "contact:"-scheme (contact:phone=..., contact:email=...).

Note: I use Osmand with german locale and tried to retranslate the settings from the UI, but they still might be different in the original english version.

**Comment by OpenSourceForEver** [comment]
Sorry. I can't help you, I was thinking in Tag: Phone, Tag: website...

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/3e1dd736c7a0e3e70bf8941e7be9e149a5235b40
