### ISSUE TITLE
Honor direction-dependent access restrictions

### ISSUE THREAD

**Issue by fbausch** [osmandapp/OsmAnd#13399]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Car

### Start and end points

Start: Southern end of this way: https://www.openstreetmap.org/way/400539716#map=19/49.38170/8.67543 in Hardtstraße, Heidelberg, Germany
End: Nothern end of this way: https://www.openstreetmap.org/way/400539716#map=19/49.38170/8.67543 in Hardtstraße, Heidelberg, Germany

### Actual and expected routes

Actual route: OsmAnd suggests driving directly along the way from the Southern to the Nothern end.

Expected result: OsmAnd routes via Bogenstraße, Langgarten, Im Franzosengewann to Hardtstraße because https://www.openstreetmap.org/way/400539716#map=19/49.38170/8.67543 and https://www.openstreetmap.org/way/946557603#map=18/49.38270/8.67712 contain direction-dependent access restrictions (`motor_vehicle:backward = no`, `motor_vehicle:forward = destination`). Both streets, Hardtstraße and Albert-Fritz-Straße are not oneway streets. Instead, they have signs limiting access from one side.

### Is this a regression?

So far, this never worked.

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>
OsmAnd~ 4.0.9
</code></pre>

**Device and Android/iOS version:**

Google Pixel 4a 5G, Android 12

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-resources/pull/759

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-resources/pull/771

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-resources/pull/773
