### ISSUE TITLE
Backup option: list of maps

### ISSUE THREAD

**Issue by H-Sachse** [osmandapp/OsmAnd#13397]
# 🚀 feature request

### Description

In the backup option, there's the option to backup the actual maps, which can be quite large.

### Describe the solution you'd like

I propose the option to backup the list of installed maps only, so when restoring a backup, the maps can automatically be reloaded from the server, but do not take up space in the backup.
This should also include the settings for live updates.

### Describe alternatives you've considered

The alternative as I see it at the moment is to write down the list of installed maps.

**Comment by vshcherb** [comment]
It's now implemented and we check if the existing map is OsmAnd generated we don't backup it
