### ISSUE TITLE
Hebrew wikipedia - no images

### ISSUE THREAD

**Issue by Yaniv125** [osmandapp/OsmAnd#13391]
An easy way to explain this, is with an example

Open OsmAnd
Go to Nahl Alexander
https://en.wikipedia.org/wiki/Nahal_Alexander
https://he.wikipedia.org/wiki/%D7%A0%D7%97%D7%9C_%D7%90%D7%9C%D7%9B%D7%A1%D7%A0%D7%93%D7%A8

As you can see (in OsmAnd app) there are no images on the Hebrew version, only on the English one, 

P,S 
1. In the web browser there are images on the English and Hebrew version
2. Download images is on

Tested on Android
OsmAnd 4.1

**Comment by Dima-1** [comment]
https://github.com/osmandapp/OsmAnd-tools/pull/454

**Comment by vshcherb** [comment]
https://uk.wikipedia.org/w/api.php?action=query&prop=imageinfo&iiprop=url&generator=images&iiurlwidth=320&gimlimit=50&format=json&titles=%D0%A7%D0%B5%D1%80%D0%BD%D1%96%D0%B2%D1%86%D1%96&gimcontinue=733%7CNorth.svg

https://uk.wikipedia.org/wiki/%D0%A7%D0%B5%D1%80%D0%BD%D1%96%D0%B2%D1%86%D1%96?action=raw

('Готель_Черемош_(Чернівці).JPG',584598,944,709,'a:1:{s:22:\"MEDIAWIKI_EXIF_VERSION\";i:2;}',8,'BITMAP','image','jpeg',4370202,486,'20110508133310','1q4lwfhue9hzzgdzk9b71jidtcs0wl7'),

https://dumps.wikimedia.org/ukwiki/20220101/ukwiki-20220101-image.sql.gz

[Файл:Gramota Chernivtsi.jpg|міні|ліворуч|250пкс|Копія грамоти з першою письмовою згадкою про Чернівці]

Memo_board_theater_Chernivtsi.jpg'

https://dumps.wikimedia.org/commonswiki/20220101/commonswiki-20220101-image.sql.gz

**Comment by Dima-1** [comment]
https://github.com/osmandapp/OsmAnd-tools/pull/459
