### ISSUE TITLE
GPX search conflicts by priorities with Address search

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#13408]
![telegram-cloud-photo-size-4-5911254530362816376-y](https://user-images.githubusercontent.com/1042025/146812696-a93b3404-181e-4d75-8568-52f95fc3d88c.jpg)

**Comment by vshcherb** [comment]
iOS / Android:
"15 rue..." should not match "2021-03-15"
"15 rue..." should not match "2021-03-12 15-40"
"15 " should not match "2021-03-15"
"15" should  match "2021-03-12 15-40"
"15" should  match "2021-03-15"

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/pull/15765

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/pull/15784

**Comment by alisa911** [comment]
java (add for wpt favorite) https://github.com/osmandapp/OsmAnd/pull/15800
ios (need to add ui for gpx) https://github.com/osmandapp/OsmAnd-iOS/pull/2323
<img width="442" alt="Screenshot 2022-11-22 at 12 32 30" src="https://user-images.githubusercontent.com/38911173/203318281-3921fd56-dba5-48bb-a7ba-aa32da8421df.png">
<img width="356" alt="Screenshot 2022-11-22 at 12 32 47" src="https://user-images.githubusercontent.com/38911173/203318286-dcc4ff95-dbd0-48ed-a32d-88a44b7edccf.png">
