### ISSUE TITLE
Massive harmonization of UI list screens

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#1340]
From talking to many users and discussing what they think needs improving the following issue arises:
OsmAnd is often perceived as extremely complex and awkward to use. One part of it is our feature-rich functionality, let's put that aside for now. But the other part is: We make the optical appearance and the choice of actions too diverse, make things look different which could be the same, and make users guess too often what which icon/ action would cause!  As a result, the learning curve of using OsmAnd is enormously flattened...

Plus: The problem with just having various scattered action icons is that users are unaware or confused by which icons in our UI (mostly on the dashboard, but also on other configuration screens) are clickable or not, and every new or occasional user is clueless about their meaning or what action they trigger.

What aggravates the situation is that we use different ways of presenting icons and actions on completely analogue screens. The following is a partial list, we may find still more measures to rectify the situation:

(1) On the dashboard "list" cards History, My Favorites, and My Tracks, the appearance of the list entries is optically different than in the corresponding "full" lists (the ones obtained by tapping on "Show all". Also the action triggered when tapping the textual list entry, or when tapping the icon to the right of each list entry is different from doing that in the corresponding full list.  I suggest the layout, and the actions triggered must be fully identical, hence
(1a)  On the dashboard card, replace the icons to the right by the "3 dots" More icon (just like we have in the full list)
(1b) When tapping either the textual list entry or the 3 dots icon (on any list), we always must produce the textual popup context menu (the one we have on the full lists now). It is fully comprehensive and in textual form, it removes all guessing for first time users or occasional users, and it offers all possible actions a user would expect like Navigate to, Show on map, etc.

(2) Another example: On the Dashboard's Plugin card, tapping on the icon to the left of each entry just brings up that Plugin's title card. But On the "Plugin / Show all" total list of Plugins, tapping on the icon to the left of each Plugin entry activates or deactivates the Plugin. Again here: The list entries on both the Dashboard Plugin card and the full Plugin list screen, must look identical, and tapping on an entry should always produce the textual context menu to avoid guesswork and surprises.  Also here I suggest we use the "3 dots" appearance on both lists, which brings things in line with what I suggest in (1).

(3) On our Search screen, tab "History", we use the "3 dots" icon to the right of each list entry to indicate that several actions can be triggered by tapping the icon (or the entry, it is the same, which is fine). But on other search tabs like Favorites or POI the 3 dots icon is missing, should be added, too, for consistency.

(4) On the "My tracks" full list, let us create the identical behavior we would now have on all list screens: Tapping an entry will produce the textual popup menu (which so far on that screen you only get when tapping the "3 dots" icon for each entry). As it is now, tapping a track entry itself puts you on the "Track segment" screen, and I have yet to find a single users who immediately comprehended what happened, and what it can be used for (see (5) below). Instead, the option of getting to that screen should be added as one action on the popup menu entry called "Track analysis" or similar.

(5) On the "Track segments" screen, which I suggest you get to only via "Popup/Track analysis",  let us add the actions currently hidden behind the two icons on the top right corner, "Share track" and what we there call "Show on map", into the popup menu for the list entries of that screen. The latter action (now falsely hidden behind the top-right Show on map icon) must be renamed to something like "Split interval", because "Show on map" is already in that menu with its correct action.

**Comment by DonpK** [comment]
As a new *OsmAnd+* user, your observations about the UI certainly resonate with me. I'm thinking of writing myself a tutorial with screenshots, but at this point I don't even know where to start. 

I've always thought that the user interfaces of many, if not most, software applications are often difficult for new users to navigate because they are generally beta tested by people already familiar with the product. These testers take for granted things that new users might not find at all obvious. There may be practical reasons for this, but it often leads to a less than satisfactory user experience.

**Comment by vshcherb** [comment]
Actually we want to make consistent dashboard and other screens but other way around, so it will be no 3 dots and context menu. I think all of these items make sense but the strategy is different that suggested. 

Dashboard is an example how it stays, but we will update other screens to make it consistent, which is now not possible, because we can't fit all the actions on the map now.

I close the issue to not mislead
