### ISSUE TITLE
Routing without toll roads fails on some cases

### ISSUE THREAD

**Issue by alex9099** [osmandapp/OsmAnd#13406]
### Description
Trying to make a route with toll roads disabled fails with Fast route calculation failed and then Could not calculate route

This may be a regression because it routed fine on 4.0.8

### How to reproduce?
Choose two points with toll roads disabled and get the errors.

For example 37.5117, -8.0601 (almodovar) to 37.01617, -7.93496 (faro)

### Your Environment
OsmAnd Version: Nightly 4.1.0 #33267m (happens with the play store version 4.1.11)
Android/iOS version: Android 11  (pixel experience plus)
Device model: davinci (xiaomi mi 9t)

**Maps used (online or offline):**   
Portugal, tried both map from the download server and generated locally with osmand map creator

**Comment by Dima-1** [comment]
Test for this issue https://github.com/osmandapp/OsmAnd-resources/pull/762

**Comment by ivanPyrohivskyi** [comment]
Rollback changes of fix for this issue https://github.com/osmandapp/OsmAnd/issues/12933
