### ISSUE TITLE
Display the current style if you display a dialog?

### ISSUE THREAD

**Issue by ravenfeld** [osmandapp/OsmAnd#13415]
### Description
Hello, I noticed that the name indicated was not very logical for me, if we do not activate the bottomSheetStyle there is no problem but otherwise we display a name that is the following while the user asks to display a dialog. I was more expecting to know the actual name. I found how to correct but when I made a new fetch to update myself I have nothing compiled. I put my solution here.

### Your Environment
OsmAnd Version: 4.0.9
Android/iOS version: Android
Device model: One Plus 7

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

### Solution
In file SwitchableAction

    @Override
    public String getActionText(OsmandApplication app) {
        boolean showBottomSheetStyles = Boolean.parseBoolean(getParams().get(KEY_DIALOG));
        String arrowDirection = isLayoutRtl(app) ? "\u25c0" : "\u25b6";
        String disabledItem = getDisabledItem(app);
        String nextItem = getNextSelectedItem(app);
        String item = getSelectedItem(app);
        if(showBottomSheetStyles){
            return getTranslatedItemName(app, item);
        }else if( Algorithms.stringsEqual(nextItem, disabledItem)) {
            return getTranslatedItemName(app, item) + arrowDirection + "\u2026";
        } else {
            return getTranslatedItemName(app, nextItem) + arrowDirection + "\u2026";
        }
    }

![Screenshot_20211221-174255](https://user-images.githubusercontent.com/3765114/146967192-4aa10887-a500-435f-ad88-64fef87a32f8.jpg)
![Screenshot_20211221-174300](https://user-images.githubusercontent.com/3765114/146967215-6fac3f1d-37c6-425c-85a7-e1aa64689a13.jpg)

**Comment by vshcherb** [comment]
The issue has been fixed please try new build https://github.com/osmandapp/OsmAnd/issues/13964
