### ISSUE TITLE
Offline POI articles missing or not visible for some Wikipedia POIs

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#1341]
This needs some more research, just to not lose it:

We have some wiki places in our new Wikipedia downloads which can be "Shown on the map", "Navigated to", etc., but the context menu associated with them (like when tapping their location bubble, or tapping on them in the POI hit list) is missing the entry to "Show POI description", so the associated wiki article cannot be read (maybe it is not even contained in our download).

One of many examples of this seems to be http://no.wikipedia.org/wiki/Wessels_plass_holdeplass in Oslo, Norway, which can be found in our POI search, but without the option to show its description.

**Comment by vshcherb** [comment]
Unfortunately norway is not indexed by our maps. I will put key files (so in future it could be also used as a reference), all files where we need to add translations in case.
1. Processing:
https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml (name:*) 

https://github.com/osmandapp/OsmAnd-tools/blob/master/OsmAndMapCreator/src/net/osmand/osm/MapRenderingTypesEncoder.java#L33

Wikipedia processing https://github.com/osmandapp/OsmAnd-tools/blob/master/WikipediaConverter/prepare.sh#L41

2. Application
https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/dialogs/ConfigureMapMenu.java#L400 (BOTH mapNamesIds & getMapNamesValues should match with the order)
https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/activities/SettingsGeneralActivity.java#L158 (BOTH entries & values should match with the order)


So I guess if we want we could evolve our language supported list

**Comment by sonora** [comment]
This issue changed behavior today, likely due to the fix for the 1343. I can not  currently find any Wiki places which do not offer the action "Show POI description" and more (the issue did also exist for German, Spanish, Italian or US wiki POIs, but only very few).  Now the behavior seems that "Show POI description" is always offered, ok but sometimes (and I only find this in the Norwegian wiki so far) tapping it produces an empty article (language selector shows EN then). Will investigate other wikis to see if there are examples, too.

**Comment by sonora** [comment]
PS: My above example near Oslo, POI Wessels plass holdeplass, now works ok with the latest nightly and latest download of the Wikipedia POIs.
