### ISSUE TITLE
Non-sensical routing avoids short trunk link if start/end are far enough away and intermediate waypoint

### ISSUE THREAD

**Issue by amalon** [osmandapp/OsmAnd#13428]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

car

### Start and end points

Starting A40 northbound, 51.76970N 2.83138W
Via A4137 51.86541N 2.64856W
Destination A4137 51.89278N 2.65587W

### Actual and expected routes

This is the route suggested:

![Screenshot_20211224-113424_OsmAnd~](https://user-images.githubusercontent.com/210303/147350036-a06132e1-5bb1-4dc1-8850-73aa4030bfb8.png)

Note how it goes straight past the obvious A40-A4137 junction. I've checked the openstreetmap nodes and can't see anything obvious restricting the routing.
The junction is here: https://www.openstreetmap.org/#map=17/51.86203/-2.64517

Here's the zoomed in route:

![Screenshot_20211224-113447_OsmAnd~](https://user-images.githubusercontent.com/210303/147350041-201659fe-1162-40d8-b713-a5fe596f8581.png)

I've attempted to make the route as short as possible to reproduce. If a much shorter route is selected it often does the right thing (or avoids the junction entirely.

### Is this a regression?

Not that I'm aware of. Its been present for a while, I've checked the osm data multiple times in the past, and been bitten a few times

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>
fdroid osmand+ 4.0.9
</code></pre>

**Device and Android/iOS version:**

Oneplus One, MicroG LineageOS 2021-12-16
android 11

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**

**Comment by xmd5a2** [comment]
Not reproducible anymore
![Screenshot_2022-02-19_08-38-08](https://user-images.githubusercontent.com/5829014/154787979-83b5b802-372d-47ec-a8d2-492fad215d55.png)
