### ISSUE TITLE
Routing error on all profiles except driving 

### ISSUE THREAD

**Issue by Wizit38** [osmandapp/OsmAnd#13427]
After recent updates on version 4.1.0, an error message is given

Could not calculate route length=1 index=1

This occurs whether you are using brouter profile, cycling or pedestrian. Only driving profile is able to find a route. This error continued even after updating to 4.1.0 u 33257

This problem has been repeated by Hike&Map_Philippines of the English telegram group.

Route is 596 Ang Mo Kio Street 52 to near 33 Mount sinai rise in Singapore

**Comment by alex9099** [comment]
Might be related with #13406
