### ISSUE TITLE
Add a "start from here" option to the address search/favorites/history screens

### ISSUE THREAD

**Issue by breversa** [osmandapp/Osmand#1342]
Hi,

I often use OsmAnd to calculate navigation from point A to point B, which are different from my current position (e.g. when I only need the last kilometer of a road trip, or simply planning my next treck).

In order to achieve this, I currently need to :
1- search for point B (in search, favorites, history, etc.)
2- set point B as destination
3- search for point A
4- show point A on the map
5- tap point A and select "Start navigation from here" (or whatever it's called in english)

Not only are step 4/5 one tap too much ("fewer taps is better"), but it's rather counter-intuitive to select your destination THEN your starting point.

Both these issues could be corrected with the following :
1-  Add the "Start navigation from here" on the search screen, along with the current "Go to destination" or "Show destination on map". (That might need a new "Starting point" icon on the map though).
2- Once selected, select another address and tap "Go to destination".

I believe this simple modification could do wonder to improve the intuitiveness of OsmAnd. :-)

Even better : add a "current position" button on the address search that would, well, set the current position (as determined by GPS/cell tower/wifi) as either source (effectively meaning "Start from here") or destination (meaning "Get me back to here (where I parked my car/pitched my tent/buried a body/whatever)").

**Comment by sonora** [comment]
Hello breversa, Well, I am personally a bit hesitant to make big modifications or even add more menu options. This further complicates the navigation UI (OsmAnd is rather complex already) even further for the probably 98% of use cases where people simply need directions from where they currently are ("the standard navigation use case"), for something which would only be used in a very small number of cases.

Are you actually aware of this procedure:
- Have _no_ destination selected
- On the map screen, hit the navigation button (near the bottom left corner, between the Menu button and the map ruler)
- If no destination had been selected (your use case, as I understand), the route configuration dialogue will automatically open, and in it you can select start and destination point in any order you chose.
- As pre-configured options we currently support: "Current (real life) position", "Select on map" (probably the best choice for your use case, if you map is centered on where you want to start from anyway, just tap it), and Favorites or address search.

I think this may already be rather close to what you are asking for?
Best, Hardy

**Comment by breversa** [comment]
Thanks sonora for your very quick reply ! :-)

Indeed, I did not know about this procedure, which is indeed rather close to what I ask for. So thanks again !
(I just played a bit with that navigation button, and it seems very handy indeed ! Just why isn't it more obvious ?)

However, I believe we're still for from the impressive simplicity of (sorry) Google Maps, for instance, where you :
1- select a start address
2- select a destination address
3- click "Navigate"

Three steps, no hassle.

**Comment by breversa** [comment]
Addendum :
Though I understand your hesitation to add clutter, I believe that a "Start from here button" to the address screen would nonetheless be a good idea because :
1- The feature already exists, thus only making it more accessible
2- There are four buttons on the address screen. Adding a fifth would only be problematic with the smallest-screened devices (I use a 4,5" one)
3- It is (to me anyway) the most logical place to look for it
4- If screen real-estate is the issue, why not make the bottom "action bar" be scrollable, with the fifth and subsequent buttons being initially "hidden" to the right ? Or in a 3-dots menu ?

**Comment by sonora** [comment]
Ok, thanks for your thoughts, let's now see how other project members feel about it.

I completely share your thoughts about "Why aren't some things more obvious?". From my analysis and work with many a user one part of the answer is that we, even on our startup screen, confront the user with a wealth of not commonly recognized buttons and icons, and the user has little chance to figure things out other than trial and error. This is frustrating for many new and occasional users, because the learning curve is very flat. Just yesterday I happened to open Issue #1340 (https://github.com/osmandapp/Osmand/issues/1340) about it, because general user feedback is that consistent and textual action buttons are much more transparent than un-common icons. From my experience with other apps, the only ones which get away with presenting just icons are media players, because the buttons for "Play", "Stop", "Pause", "Record", "Fast forward / backward" are reasonably common knowledge. All other icons or buttons need explanation, and this is what Issue 1340 is about.

Best, Hardy

**Comment by vshcherb** [comment]
From my perspective it is much less usable function comparing to other 3. We don't really have place for another action. The typical scenario is your start point your location. I see that issue overlaps with future initiatives of new context menu (very similar what iphone version has now) and planning plugin. These 2 features are in the short list of future changes, so I wouldn't expect this feature will be developed before these 2 major things.

**Comment by breversa** [comment]
Thanks for your thoughts, people.

If a planning plugin is on its way, I can wait for it. I'll give feedback then and reopen that issue if need arises again.
