### ISSUE TITLE
Track recording: Visibility always reset to false 

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#13438]
When recording a new track the visibility is always set to false. The visibility can be set to true under My Places but this setting is not stored by OsmAnd. When recording a new track later the visibility is set to false again.

Is this a regression from #12597?

**Comment by pebogufi** [comment]
I confirm this, it is annoying to switch on manually on every recording since some weeks.

**Comment by dmpr0** [comment]
Unfortunately, we could not reproduce the behavior where visibility is always reset to false, we found that the visibility of the "Current Recorded Track" in My Places does not affect the UI of the recording dialog, but it does affect the visibility of the track on the map. 
In addition, the parameter "Show on map" in the dialog of recording trip and in the next dialog "Saving track" is the same and is saved in the settings, so next time the visibility of the recorded track will depend on it.

**Comment by scaidermern** [comment]
I see. I guess this is a misunderstanding due to a changed behavior.

Now the visibility of the track has to be set in the track recording dialog. This setting is new and wasn't present in previous OsmAnd versions. In fact, so far I missed it completely. That's why I changed the track visibility under "My Places" - which doesn't get saved during app restarts.

So I guess I have to adapt to the changed track recording dialog. The visibility setting in this dialog gets restored after app restart. This means this ticket can be closed.

**Comment by dmpr0** [comment]
# ToDo
- [ ]  Fix switch state of "Currently recording track" in My Places
