### ISSUE TITLE
Language selector for POIs' wiki articles always contains "EN"

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#1343]
There is a problem with the language selector for the wiki articles in POIMapLayer.java: I think we always add "EN" by default, even if the wiki article in question does not exist in English.

**Comment by sonora** [comment]
Looking at the code, the issue is as follows: If an article does not exist in the selected map locale language, we always add English to the selection menu as the fallback (even when English may be a language the article does not come I, which produces the issue).

The best solution would be, if the article comes neither in the OmAnd map locale language nor in English, we then select the language in which the article is the longest, (which usually is the one with the most content), and in most cases we would then select the one in the POI's regional default language.

**Comment by sonora** [comment]
I just see we overlapped each other investigating this.
- The  bogus "English" entry in the selector menu comes from us calling getNames("en")
- I am not sure where the "EN" comes from in the menu _header_ upon first opening an article which has default non-en (happens always if the OsmAnd loacle is set to "system language", even if above issue is fixed).
- I wish we had a way of finding our what language the wiki article is in for the default "name"? Knowing this we could fix everything, even the correct wiki-URL (using en.wikipedia.org will get you to a generic "not found" page if the article in question is not an en-article).

Best - Hardy)

**Comment by vshcherb** [comment]
wish we had a way of finding our what language the wiki article is in for the default "name"
- it is always name:en and it is guaranteed by generation

**Comment by sonora** [comment]
Ah, ok, that may simplify the fix!

But I am still not sure I fully understand:  If an article exists e.g. _only_ in Italian, can we assume that it is reliably tagged name:it ? So what would a.getName() return in this case, null?

**Comment by vshcherb** [comment]
There were some internal sets for name and enName, I worked around name and rely on tag "content"

**Comment by sonora** [comment]
Great! With the following glitch still: English seems now totally suppressed as a choice in the language selector (if the article exists in English, of course)?  Even if an article exist ONLY in English, article itself is displayed ok, and EN is correctly displayed in the topbar, but tapping on it will not display the Language selector to visualize there are no other choices but English.

**Comment by vshcherb** [comment]
Fixed EN lang

**Comment by sonora** [comment]
Yes, EN works now, thanks.
When I get a chance I will have to double-check our priority selection, though, because it looks like now of the different language versions available we always default-display the article the language of which comes first in the alphabet  :-)

So for a place in the US where only a an English or a (very short) Danish article exists, I get the small Danish one by default ... :-)  (My phone and OsmAnd  is NOT set to Danish :-) )

I think we should have the priorities as follows:
- (1) If an article exists in OsmAnd's locale, display this first by default
- (2) If not, display English as first fallback
- (3) Only the 3rd priority should be any other language, this could be the first one in the alphabet, or (but this is harder to code) the longest article available

**Comment by vshcherb** [comment]
The rules are exactly the same, please let me know if they are nto there.

**Comment by sonora** [comment]
With latest nightly, somehow none of (1)-(3) seem to be observed. For articles existing in multiple languages it seem a random language is displayed first...

**Comment by vshcherb** [comment]
Please check latest build

**Comment by sonora** [comment]
Getting there, but not quite ... :-)

From what I see, it is now as follow:
- Rules 2 and 3 seem observed ok. English is the second choice, and the "best" article the third, BUT
- the first choice is ignored: If the article exists in the OsmAnd locale, is does not seem to be displayed as the first choice (English used instead, if it exists, if not, rule 3 is honored)
- While rule (3) seems observed, whenever an article is shown in this "best language", the top bar's language selector button (wrongfully) shows "EN" as the displayed language. Correspondingly, when you hit the button "Display full article", the generated URL will start with en.wikipedia.org, which will not yield the desired result. This is best verified by picking an article which exists in language XX only, while XX is not set to be your OsmAnd locale: The article will display in language XX all right, but the top bar will wrongfully indicate "EN", and the full article URL will not resolve to xx.wikipedia.org, but to en.wikipedia.org (producing no result).

**Comment by vshcherb** [comment]
>> the first choice is ignored: If the article exists in the OsmAnd locale, is does not seem to be displayed as the first choice (English used instead, if it exists, if not, rule 3 is honored)

Configure Map -> Map Language. Everything displayed on the map should be displayed using that locale, not UI locale. May be that's a misunderstanding.

(3) True again that weird behavior with name, switch to content tag. Please check it.

**Comment by sonora** [comment]
Victor, Regarding rule (1): I think we should use the OsmAnd locale here as
first choice, not the map preferred locale. Our default for the map locale
is use local names, and that's mostly fine so that map names co-incide with
what you e.g. read on street signposts. But I think when it comes to
reading a Wikipedia article, most users would expect as first choice to see
the language they have also chosen as OsmAnd display language, most likely
the language they speak (in fact our default is the device language there).

But I think I had implemented to use PREFERRED_LOCALE anway, not
MAP_PREFERRED_LOCALE, did you change it back?

Plus: Even testing with map locale, there is still a glitch: Set mep locale
to our default "local names": For e.g. an article on the Germany map which
exists only in Dutch and in German, I get the Dutch article (Settings all
default: Phone set to English, OsmAnd set to "system language", Map locale
to "local names")

Regarding (3) Yes, I think it works now!! will run a more thorough test
tomorrow!

Best, Hardy

**Comment by sonora** [comment]
PS: Here
https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/views/POIMapLayer.java#L342
is where I think we should revert to PREFERRED_LOCALE, not
MAP_PREFERRED_LOCALE, as I say in my comment immediately above it. This
would affect the wiki article first selection only, and I think it is what
users would expect.

**Comment by sonora** [comment]
PS2: The remaining bug comes from the fact that MAP_PREFERRED_LOCALE="",
.i.e. <empty> for our default "use local names". While I think
PREFERRED_LOCALE is never empty, even when set to "system locale". So the
change I suggest in "PS:" above (previous message) would fix it, I think.

**Comment by vshcherb** [comment]
Yes, I've though I did a mistake using UI language, now I see. True the last glitch is conceptual and can't be fixed, because wikipedia doesn't provide "local names". On the other hand I don't see why map preferred language is not configured by default to system settings (unless it is english).

The reason of having it as map_language settings is very strong, everything related to the map: search, routing, poi - they could be displayed/searched on the map should follow that preference. Basically everything that depends on your location. The situation with Wikipedia is rather tricky by 2 things
1. Wikipedia doesn't provide local language name
2. Preferred reading language for long text could be different than geographical names language

Anyway with 2nd issue you would search it differently, there were other requests to filter out Wikipedia poi by language, that doesn't mean we are going to change downloaded files, but it might be additional poi filter in wikipedia.

**Comment by sonora** [comment]
I sill suggest we rectify the situation by using PREFERRED_LOCALE in line
342 of POIMapLayer (setting it there ONLY affects the wiki articles,
nothing else). It fixes our bug, and is likely what the user wants: Exactly
how you say it: The language preferred to read long articles is your system
locale, and may/will be different from how you want to see map labels.

The reason why MAP_PREFFERRED_LOCALE is "" when you select "local names" is
evident: It is unspecified, we just take all the default (name) tags people
use in OSM who do not enter other language versions (the vast majority of
all objects are tagged like this). So it is ok we set this to "". Plus: The
locally correct locale depends on what map you are looking at, but your
preferred system locale does of course not. PREFFERRED_LOCAL, on the other
hand, is never empty.

I had tried it: Using just PREFERRED_LOCALE in line 342 fixes our selection
rule (1) for all device configurations.

**Comment by vshcherb** [comment]
I followed semi original approach and implemented the primary language of the article to user locale settings, however if the map language is different than local names it will be chosen to preferable. So I think from that point we need to try it out and collect more information about user experience.

**Comment by sonora** [comment]
Ok, that is a valid approach also, I think. Testing again, I find that the rule set
(1) Prefer OsmAnd locale, or map locale if specifically set
(2) Take EN as the first fallback
now work as desired, so I would call that a good job!

The remaining awkward issue If find is not very frequent, but could be solved if we implemented what I suggest as rule 3
(3) If article exists neither in OsmAnd, nor in the selected map locale (if any), nor in EN, display the LONGEST article by default.

The odd examples If find where this would help are these:
- POI in Southern Germany, article exists only in German (long article) and Dutch (short snippet). Phone is set to English (not uncommon in Germany), map locale is our default (local names). The awkward result is the article is first displayed in Dutch!
- POI in Spain, long article exists in Spanish, shorter one in Catalan, very short one in Serbian. Same settings as above. Article is displayed in Serbian!

Rule (3) would fix all these.

**Comment by sonora** [comment]
I have to revise my latest update above on this bug report: I have refreshed some of my Wikipedia obfs and for now cannot find any cases any more where we would need to have rule 3 above. (Could it be that we now simply take the Wikipedia-region's language as the 3rd priority? Then evaluation of article lengths would of course be unnecessary.)

**Comment by vshcherb** [comment]
Leonid is planning to add lang per country (https://github.com/osmandapp/OsmAnd-resources/blob/master/countries-info/regions.xml) and other fields, so we can embed it, in order to find Local language per country and other useful features like road signs, max speed, ... 

Please let us know if you want to contribute, so we can share the possible schema.

**Comment by sonora** [comment]
Sure, let's do that! But just displaying the longest article where all other rules fail may be the easier thing to implement, and also be more objective for countries with several official languages.

**Comment by vshcherb** [comment]
Will put in a backlog a note about longest article

**Comment by vshcherb** [comment]
About (https://github.com/osmandapp/OsmAnd-resources/blob/master/countries-info/regions.xml) if you have ability  please put info in such format. (If country has a common attribute, then it is not needed to put  to copy it to any region.
I suggest following attributes:
driving - 'left' or 'right, default 'right'.
lang - local languages 2 digit code separated by ','
signs - 'american', 'european'. Default 'european'
shields - ... . Default what we have now.
highway_speed - '130', '80 m/h', ... Default value '120' - translates to 120 km/h, format of speed is OSM.
city_speed - Default is '50'.
road_speed - '90'.

You can just put them like this and we adopt data later, if something is needed.

**Comment by sonora** [comment]
The most elegant and promising solution would be we somehow crowd-source this: Put a small applet on our home page "Please take 1 minute to help us improve OsmAnd for your country", and produce all the things we need as pulldow or text entry boxes next to a brief explanation each. We would preset with the current content of our regions.xml. This is a little programming invest up front, but ultimatively the only way to get global coverage soon...?

**Comment by vshcherb** [comment]
Actually there is no need to make it soon, let's enter some values and see how it goes. Later we could ask some help once we fill in for 10-20 countries at least

**Comment by arty-name** [comment]
Hi. This bug seems a couple of months old, but I still see somewhat related issue in the latest version of OsmAnd+ 2.1.1. I have English and German Wikipedia POIs downloaded. A certain POI (Amtsgericht Wedding) is most definitely coming from the German Wikipedia set. However EN is shown for it as a language indicator, and the button opens a link to the English Wikipedia where the page doesn't exist.

**Comment by sonora** [comment]
I am almost certain we have already fixed this, I cannot reproduce with latest nightly. I think we only did not release a new version since the fix.
