### ISSUE TITLE
Purchase menu in OsmAnd+

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#13436]
Do not display Continue with Maps+ in OsmAnd+. It is confused because you already have purchased the same product as Maps+.

**Comment by dmpr0** [comment]
# ToDo
Disable the "Maps+" button if the user has purchased the "Maps+" in-app or OsmAnd+ application.
- [ ] Disable button, taping open "Purchase" screen.
- [ ] Change text:
• First line: `Purchased`, second line `purchasing date`.
<img src="https://user-images.githubusercontent.com/9365308/153007337-eac90e65-c898-447c-9c18-2375e723c91b.png"  width="300" height="auto"/>

**Comment by mmh-dev** [comment]
https://github.com/osmandapp/OsmAnd/pull/13873
