### ISSUE TITLE
Glitch in position marker (closing X overlapping label)

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#1344]
The "X" is overlapping the text label.

![osmand201](https://cloud.githubusercontent.com/assets/6921696/7445541/ebb3fd54-f1b8-11e4-87c4-598c9da947b4.png)

**Comment by vshcherb** [comment]
Will be fixed with new context menu

**Comment by homersimpsons** [comment]
Is it fixed?

**Comment by Norbert80** [comment]
It is obsolet because these text labels are no more present in actual builds.
