### ISSUE TITLE
Poorly optimized on android 

### ISSUE THREAD

**Issue by Pauler221** [osmandapp/OsmAnd#13448]
It'd be great if osmand would work on Android as fluently as on iOS. Its really laggy. Offline vector maps especially is really laggy while OsmAnd online tiles are not as much laggy but still not user friendly. 

Optimizing OsmAnd more for android would be really awesome.

**Comment by vshcherb** [comment]
Work in progress

**Comment by Budgiee** [comment]
This might also be affected by the speed of your SD card, if you have maps stored on it.

**Comment by watashibeme** [comment]
I've been doing a lot of looking around and researching, if anyone can debug a logcat or understand, i did one over here, pleass have a look at my other comment:
(Logcat is free of personal stuff)
https://github.com/osmandapp/OsmAnd/issues/13489#issuecomment-1133844950

**Comment by vshcherb** [comment]
This issue is available in 4.2 beta  in Development Plugin -> Settings -> OpenGL rendering
