### ISSUE TITLE
Contour line elevation SRTM text disappears

### ISSUE THREAD

**Issue by seahorse41** [osmandapp/OsmAnd#13441]
### Description
Just upgraded from 4.0.9 to 4.1.9
Now the elevation text, the SRTM data, is not visible. Before it was visible, but sometimes have to pan around to find a label.
Now I can only briefly see it when I zoom out, where out on the edge half is being drawn, then it disappears. With the underlay off, I can see more of the labels, but they disappear as I pan toward them. Also the color of the labels seems to favor grey for the minor lines, which is hard to see even on the default background, and impossible on the aerial background.
For this bug, I am focusing on the labels disappearing, not the color choice for the label.

### How to reproduce?
Have contour lines on, My settings are: Display starting at zoom level 12, Color Yellow or dark brown, line width Medium, density Default.
also I have aerial imagery for underlay map, although changing all those does not solve the issue.
upgrade to 4.1.9, see difference. fewer labels or none at all. 
If I see any labels at all, it is the hundreds on a major line.

### Your Environment
OsmAnd Version: 4.1.9
Android/iOS version:7.1.2
Device model: LG H932

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
Us_washington_northamerica.srtm.obf 2020-01-11 08:38 472Mb

**Comment by xmd5a2** [comment]
Please provide some screenshots and exact coordinates? I can't reproduce this

**Comment by seahorse41** [comment]
Sure,
1. (http://seahorsecorral.org/videos/tests/20211229_060029_L_Osmand_a_c4t16.mp4)
shows why my contour lines start out in the color green, and elevation number labels are hard to read when grey.
Also being inside, the gps can't lock, so the "Searching GPS 0/0" at the top is not providing my location. 2 separate additional issues, I guess.

2. So, removing the underlay to show what you want to see:
(http://seahorsecorral.org/videos/tests/20211229_063645_G_Osmand_n_c35t68.mp4)
Starting at zoom 500ft, 48.75851 -118.57703  At the time stamps (sec):
0:03 pan toward and label disappears, 0:04 another label disappears, 0:09 disappears, 0:17 zoom out ok, 0:20 zoom in in, 0:24-39 pan no numbers at all, finally see some, disappears, 0:45 zoom in on number, disappears. pan, nothing, 0:54 zoom out, pan, 0:58 disappears, 1:03 another repeat. End at 48.72776 -118.58304
The majority of my issue happens at zoom of 200 ft down close to the ground. Less so at 500ft, and above that the contour lines get close together and harder to follow a line to the nearest label, usually out on the edge of the screen.

3. (http://seahorsecorral.org/videos/tests/20211229_061259_L_Osmand_n_c0t98.mp4)
Start at 48.75176 -118.58537 ok. 0:05 zoom in, did not draw any numbers. I give commentary about what I'm seeking, then chase the labels only for them to disappear. Examples at 0:37 , 1:11 , 1:32 

4. At some point I discovered a new bug, must have happened when I ended a recording, when I returned to Osmand, there is no menu button to fix it, the Action button acts like it has been activated, but shows the wrong icon for the lack of action menu at the top. Tapping it has no effect. In the center is a floating pin. The only solution was to force close the program and restart it.
(http://seahorsecorral.org/videos/tests/20211229_060516_L_Osmand_a2-stuck.mp4)

**Comment by seahorse41** [comment]
Works much better in 4.1.11. 
Thank you.

**Comment by seahorse41** [comment]
Strange it worked better yesterday, but today on different device, after updating version, problem is still 90% missing labels .

**Comment by ivanPyrohivskyi** [comment]
Style https://github.com/osmandapp/OsmAnd-resources/blob/master/rendering_styles/default.render.xml#L5227
Need check rendering

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-core-legacy/pull/63
Fixed show text on elevation line.
![Screenshot 2022-01-18 at 10 49 29](https://user-images.githubusercontent.com/1040293/149902659-98ca0417-9b49-4dfd-ba8f-8ee10236ef78.png)


Also made long text more straight.
Before / after
![Screenshot 2022-01-18 at 10 28 28](https://user-images.githubusercontent.com/1040293/149901568-3374b03a-43f9-4c33-aafe-4c8b1ff77964.png)  ![Screenshot 2022-01-18 at 10 28 21](https://user-images.githubusercontent.com/1040293/149901578-380a2245-2d4f-4d83-bada-7849c4262599.png)

![Screenshot 2022-01-18 at 10 24 07](https://user-images.githubusercontent.com/1040293/149902128-b52f7d81-d436-44dd-8e4f-f70be07c9f2d.png)  ![Screenshot 2022-01-18 at 10 24 01](https://user-images.githubusercontent.com/1040293/149902150-424d7b5b-f462-4ac5-856e-89ed1904a8c4.png)


![Screenshot 2022-01-17 at 22 29 10](https://user-images.githubusercontent.com/1040293/149902319-44055561-e73a-4661-a1bd-fb57d35cf230.png)  ![Screenshot 2022-01-17 at 22 29 25](https://user-images.githubusercontent.com/1040293/149902339-164b3d3b-fa43-4f78-a8d5-c587b56534a8.png)
