### ISSUE TITLE
[Feature Request] 12 Hour Format

### ISSUE THREAD

**Issue by DicePenguin** [osmandapp/OsmAnd#13459]
# 🚀 [Feature Request] 12 Hour Format

### Describe the solution you'd like
I would like to see opening hour schedules, collection times, and other time data in a 12 hour format. This is so that it is easier to read when a place is open or closing, etc.

### Describe alternatives you've considered
This could be switch in the settings that allows this display option. In my opinion, 12 hour format should be the default.

**Comment by miklcct** [comment]
12-hour clock should never be set as default because it's confusing and dangerous, unless the device preference is already in 12-hour clock.

**Comment by njohnston** [comment]
From discussion on #12536 it looks like OsmAnd shows dates and times in the system format. This previously did not work for opening hours, but has been fixed in c5c703c. I don't think that has been released yet.

**Comment by vshcherb** [comment]
Indeed with latest build the issue could be closed - https://github.com/osmandapp/OsmAnd/commit/c5c703ca21c52a68e709883aa142d9ba55127507
