### ISSUE TITLE
Some icons are too smal to be noticed

### ISSUE THREAD

**Issue by tradavyvy** [osmandapp/OsmAnd#13455]
# 🚀 feature request

Some 'icons' on the map are verry verry small, and stay small even if you zoom in. It is almost impossible to see if and what is pictured there. See screenshot. There is also no info if you try to tap on the icon.
In this case it is a (long term) rockslide that blocks this road (for a few years already).

My oversight in this case made it nessesary to make a biggg detour after we visited a nice swimspot and then found out we could not drive on to the campsite 10 miles down the blocked road.

![Screenshot_20211211-095319_OsmAnd+](https://user-images.githubusercontent.com/71978409/147808162-a093a279-2e2d-4cf9-aded-4a552ca3b20b.jpg)

### Description

See above

### Describe the solution you'd like

Bigger icons, specialy when zooming in.
Text info when tapping on an icon

### Describe alternatives you've considered

Bring a magnifying glas ;)
In this case the osmand routing software would have seem the problem. But we were visualy freewheeling from spot to spot.

 (i chequed google maps routes you straight through the rockslide)

**Comment by xmd5a2** [comment]
Text info is already displayed when clicking on barriers
