### ISSUE TITLE
"Map mode" widgets changed by the screen rotation

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#13451]
### Description

Widgets changed from night to day mode during rotation the device screen

### How to reproduce?

1. setting Map mode -> night
2. rotate the device screen

![image](https://user-images.githubusercontent.com/44466116/147765688-d5668ce2-8bc7-41be-aa00-d0a713408ee3.png)

after rotating

![image](https://user-images.githubusercontent.com/44466116/147765659-1e49fda7-2e82-4afd-8a24-b74dc3747f9e.png)

### Your Environment
OsmAnd Version: 4.1..
Android/iOS version: 12
Device model: Samsing 10e

**Comment by mmh-dev** [comment]
https://github.com/osmandapp/OsmAnd/pull/13517

**Comment by vshcherb** [comment]
There are some issues with PR
