### ISSUE TITLE
In search lowercase N/W/E/S are not supported

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#13456]
If you type in search ```0 n, 78 w``` or ```n 0 w 78``` you will be redirected to ```0 N, 78 E``` which is incorrect.

Note: ```0 N, 78 W```, ```N 0 W 78``` works correctly

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/pull/13535

**Comment by vshcherb** [comment]
We need to add test

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/pull/13535
