### ISSUE TITLE
Driveways should be rendered with less width

### ISSUE THREAD

**Issue by NotSoImportant** [osmandapp/OsmAnd#13452]
Driveways are displayed too prominent. They should be rendered even smaller / dimmed.
See examples attached:

![IMG_20211231_004559](https://user-images.githubusercontent.com/35758921/147794885-f1e73db8-2388-4360-8b36-7c35fe4addfc.jpg)
![Screenshot_20211231-004151](https://user-images.githubusercontent.com/35758921/147794887-ea736181-eec5-4ea6-994d-af2c0ad7b92a.png)
![Screenshot_20211231-004121](https://user-images.githubusercontent.com/35758921/147794888-0b1d56b2-bb18-467f-9de7-5327fb11d4e8.png)

**Comment by xmd5a2** [comment]
They are dimmed when "More detailed" rendering style option is enabled
![Screenshot_2022-01-01_17-48-08](https://user-images.githubusercontent.com/5829014/147853217-2baa8af2-ea5b-4408-91e1-2063dc410aa8.png)

**Comment by NotSoImportant** [comment]
Thanks :-)
