### ISSUE TITLE
Cursor bug

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#13458]
Periodically occurs in such a bug with a cursor (see video).  There is a suspicion that it is associated with quick action.
The only way to get rid of it is to kill the osmand process.
Maybe switching to another application and then switching to osmand is to blame. But it doesn't happen 100% of the time.

https://user-images.githubusercontent.com/12549744/147857733-540dfdae-4f8d-4776-bc99-925703028566.mp4

OsmAnd Version: OsmAnd~ 4.1.0#33327m, дата выпуска: 2021-12-31
Android version: 11 
Device model: poco x3 pro

**Comment by vshcherb** [comment]
It's probably related to the setting display position always in the center or something like that. Quick action marker seems to be too high. It might be a feature ! On Map Hold - https://docs.osmand.net/en/main@latest/osmand/widgets/markers#panel-widgets-markers
