### ISSUE TITLE
Moving Markers to History

### ISSUE THREAD

**Issue by GuentherGredy** [osmandapp/OsmAnd#13465]
### Description
Map Markers set while hiking and moved afterwards to History are not available any more.

### How to reproduce?
Set a marker, move it to history, invoke history, not available any longer.

### Your Environment
OsmAnd Version: 4.0.9
Android/iOS version: 9
Device model: LG G6

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by GuentherGredy** [comment]
Hello Dmitriy, thanks for your test. Have installed now the latest 4.1.11 version. My overview screen still looks like in attached picture "Overview". When pressing "ALLE ANZEIGEN" I get an empty history screen like in attached picture "History"; it is empty and therefore I cannot delete anything. This overview screen looks the same with all profiles.

Possible solutions:
1. Is there any file in the software configuration containing the data shown in history on overview screen? Could I delete either complete file or partial content of the file?
2. If not, is it an option to de-install OsmAnd and re-install it? In this case I would appreciate an information about a file in the software configuration containing the application settings which I could save and after re-installing the application copy back to the same location. I got it from F-Droid - problem?

Your help is really appreciated because all these data in overview screen are extremely annoying.
Thank you very much in advance.
Best regards
Guenther
![Overview](https://user-images.githubusercontent.com/85982948/148254667-f811b823-c4f4-438e-a49a-92a28cfcc9fe.png)![History](https://user-images.githubusercontent.com/85982948/148254659-25ea6dd4-3ca6-495c-8487-b3e8a9662843.png)

**Comment by scaidermern** [comment]
These aren't markers. These are recently created/imported tracks.

However, I can confirm that this will even list tracks that have already been deleted again. When I tap on "Alle Anzeigen" they are also listed in the history where I can remove them via long tap. Strange that your history is completely empty.

**Comment by vshcherb** [comment]
Indeed it's strange, can't reproduce. First screen related to Dashboard but that's not a history... probably it's worth to make a video to understand the pattern.
