### ISSUE TITLE
Interface inconsistend when choosing color of favorite group

### ISSUE THREAD

**Issue by tradavyvy** [osmandapp/OsmAnd#13461]
### Description

When adding a new favorite in a new category of favourites it is now posible to change the default color of that new category to a free pallette color
(Many thanks for that)
But when i go to 'my places' there is no longer a posibility to freely change te color. Just a limited subset of colors.
I think the interface/choice pannel there is still the old (pre 3.9) version. Could you please update the 'my places' interface.

![Screenshot_20220102-061920_OsmAnd+](https://user-images.githubusercontent.com/71978409/147867282-6c6752ea-9b33-4cad-8bcc-192ad624da2d.jpg)
![Screenshot_20220102-062202_OsmAnd+](https://user-images.githubusercontent.com/71978409/147867283-7fa335ab-194c-4fd4-9f80-836d90f29d5b.jpg)

### How to reproduce?
See above

### Your Environment
OsmAnd Version:
Android/iOS version:
Device model:

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by dmpr0** [comment]
Done, available in the latest nightly builds.
