### ISSUE TITLE
[Feature Request] Android Auto - Display next road name

### ISSUE THREAD

**Issue by lukie80** [osmandapp/OsmAnd#13472]
Display the name of the next road in OsmAnd for Android Auto. Just like in regular OsmAnd Navigation on the top side of the screen. 

Hereby the written (incomplete) phrase describing the next navigation step could be removed and replaced by the road name. The phrase is not necessary as the arrows already indicate the next turn.

(This feature is important if many or complex consecutive exits occur. Then the name of the exit must be known to navigate correctly because the distance information alone is not adequate. Also some people prefer optical navigation instead of listening to lengthy acoustical navigation.)

**Comment by landswellsong** [comment]
Question to devs: is anyone actively working on this or is it ok for outsider to try to pick?

**Comment by vshcherb** [comment]
I think it's actuall yimplemented in 4.2. We've added it to Android Auto but it requires specific support from the car so it's not visible on all cars as I understand.

**Comment by polarbearing** [comment]
@vshcherb - I was testing  OsmAnd-master-nb-2022-07-02 aka 4.3.0#34317 and miss the target road and/or destination on the AA screen, too. 
Which 'specific support from the car' is needed to show the name?
What is the purpose of the phrase "... and go" at the end of each navigation instruction?
