### ISSUE TITLE
Silly routing at mini-roundabout -- over-elaborate data on OSM?

### ISSUE THREAD

**Issue by StarsoftAnalysis** [osmandapp/OsmAnd#13471]
# Routing Report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Car, fuel-efficient

### Start and end points

In West Byfleet, UK, from Sheerwater Road, turning left at the mini-roundabout onto Old Woking Road -- see https://www.openstreetmap.org/#map=18/51.33458/-0.51056

### Actual and expected routes

It should just turn left at the roundabout.  Sometimes it turns right at the roundabout and then does a U-turn where the lanes meet (which would be a dangerous manoeuvre if attempted).  See this screenshot:

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/842101/147943643-69728685-d199-421c-a937-99c7c5344327.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Is this a regression?

I don't know.

## Your Environment

**OsmAnd Version:**

<pre><code>
OsmAnd+ 4.0.8, released 2021-09-22
</code></pre>

**Device and Android/iOS version:**

Android 5.1 on Motorola Moto G 4G

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.
- [ ] Online (tile / raster) maps

**Anything else relevant?**

It may be that the OSM mark-up for this mini-roundabout is over engineered -- it's just a mini-roundabout, albeit with pedestrian refuges and turning-right lanes.  Perhaps it should be marked up as a full roundabout?  Or else be simplified?

I'm happy to change it on OSM, but I thought that I'd ask about it here first in case it really is an OsmAnd problem.

**Comment by luziferius** [comment]
> I'm happy to change it on OSM, but I thought that I'd ask about it here first in case it really is an OsmAnd problem.

I’ve looked at the OSM data. Normally, there is a turning restriction applied to the lane merging point. In this case, each merge should have a “no right turn” restriction added to prevent routing algorithms from performing these kinds of U-turns around pedestrian refuges. Here, no restrictions are present, thus allowing OsmAnd to route around the pedestrian refuges.

But in it’s current form,it also has very steep angles, which probably cause the issue, because the routing algorithm probably tries to avoid very steep angles:
![Screenshot_20220104_142618](https://user-images.githubusercontent.com/2143820/148065846-db04b1db-cfed-48ad-beb7-82ad1a2c3086.png)

 > Perhaps it should be marked up as a full roundabout?
The definition of these is rather strict: https://wiki.openstreetmap.org/wiki/Tag:highway%3Dmini_roundabout. If it has a traversable center, it both has to be mapped as a mini_roundabout and also has to be a node. In which case, these angles can’t really be avoided.

**Comment by scaidermern** [comment]
If such an angle penalty exists then it should get dropped if the junction node is tagged as `highway=mini_roundabout`. However, the same situation could still occur for similar junctions without a mini roundabout.

**Comment by luziferius** [comment]
> If such an angle penalty exists then it should get dropped if the junction node is tagged as `highway=mini_roundabout`. However, the same situation could still occur for similar junctions without a mini roundabout.

I’m unsure about that (and have no code knowledge). But at least there’s something, because OsmAnd distinguishes between regular, slight and sharp turns. And in a similar case (i.e. without a mini roundabout) it might suggest to do a sharp left turn, which does not reflect the on-the-ground turn angle

**Comment by DicePenguin** [comment]
For mini roundabouts in Open Street Map, there is an option to add direction of clockwise or counter-clockwise on the node. Perhaps this could be of use?

**Comment by StarsoftAnalysis** [comment]
@DicePenguin's suggestion about direction=clockwise might be relevant, because the wiki page about mini-roundabouts says 
>"In case the traffic flow is clockwise, the tag direction=clockwise should be added as the default rendering of major renderers is anti-clockwise."
(even though you'd expect the default to be clockwise for a drive-on-the-left country).

**Comment by StarsoftAnalysis** [comment]
Is there a way of searching OSM for similar road layouts?

**Comment by scaidermern** [comment]
> Is there a way of searching OSM for similar road layouts?

I guess it would be possible to construct a Overpass API query to search for mini_roundabouts with > 4 connected ways. However I'm not familiar enough with Overpass API to construct such a query.

**Comment by StarsoftAnalysis** [comment]
I've added no-right-turn restrictions where the lanes merge for this mini-roundabout.

**Comment by scaidermern** [comment]
There is no solid white line so a u-turn should be allowed and the restriction should be removed 
Depends on the country though. I heard there are countries where u-turns are forbidden unless explicitly signed otherwise.

**Comment by StarsoftAnalysis** [comment]
> > I've added no-right-turn restrictions where the lanes merge for this mini-roundabout.
> 
> Pardon my ignorance, but is that the right thing to do? I imagine you _can_ turn right at the intersection. Just in this case OP wanted to turn left. Maybe better is to remove the lane split and add a point for `traffic_calming` on each approach to the intersection?

I haven't blocked right turns at the roundabout, just at the point where lanes split, as suggested by @luziferius above.

But I agree with the suggestion to remove the lane splits completely -- I don't think they add anything useful.

**Comment by michaelblyons** [comment]
> I haven't blocked right turns at the roundabout, just at the point where lanes split,

Ah, I see. Thank you for the clarification.

**Comment by StarsoftAnalysis** [comment]
> There is no solid white line so a u-turn should be allowed and the restriction should be removed.
> 
> Depends on the country though. I heard there are countries where u-turns are forbidden unless explicitly signed otherwise.

In the UK, u-turns are permitted where it is safe to do so (and not specifically prohibited).  I don't think it would be safe so close to a mini-roundabout, but then it's not my opinion that matters.  On the other hand, because OSM is used for sat-navs (among other things), prohibiting u-turns in OSM at this sort of lane-merging point is important: a driver following the sat-nav's guidance wouldn't expect to make a u-turn immediately on exiting a roundabout, and could be prompted to make a mistake.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.3.0#13873mqta, released: 2022-10-17 Not Reproduced

**Comment by vshcherb** [comment]
Not reproduced - looks ok  with new maps https://osmand.net/map?start=51.334768%2C-0.509051&end=51.334738%2C-0.511052&mode=car#18/51.33424/-0.51142
