### ISSUE TITLE
Public Transportation ignores "Hail and Ride"

### ISSUE THREAD

**Issue by duiveldoder** [osmandapp/OsmAnd#13481]
In Asia "Hail and Ride" is common. 

All parts of a route that are "Hail and Ride" you don't need to walk to a designated waiting/loading/unloading area.

Anywhere along the route where you are - you just waive the arm and the Public Transportation will stop for you.

Common in Asia.

Right now - OSMAnd ignores this and forces you to walk as far as 15minutes to get to an "waiting area" where all you gotta do is just "don't move at all - stay and wait - and hail and ride when the bus comes"

**Comment by vshcherb** [comment]
Merged to  #6696
