### ISSUE TITLE
When you create POI in French OsmAnd assign incorrect amenity key

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#13485]
### Description
Request from support.
When I create a new POI, on the dropdown list I want to add "Auto-école"
if I go to the extended menu I can see a wrong key
amenity = driver_training
the correct key is : amenity=driving_school
![image (5)](https://user-images.githubusercontent.com/80623554/148215890-a01de425-8237-4816-93be-88ae645b899e.png)

the second, it is also the same issue if I select "bar" in french language he put me
amenity = pub

<table style="width:100%">
  <tr>
    <th>the correct key is amenity=bar</th>
    <th>If you select "bar" in English it assigns correct key:
</th>
  </tr>
  <tr>
    <th><img src="https://user-images.githubusercontent.com/80623554/148216256-2e4990e1-f78c-4fbc-b8bf-e899b534b2a5.png"  width="400" height="auto"/> </th>
    <th valign=top><img src="https://user-images.githubusercontent.com/80623554/148216357-25d329ec-aebc-4603-a303-407705f9bce4.png"  width="400" height="auto"/></th>
  </tr>
</table> 

### How to reproduce?
Change application language in French. Add POI->select POI type "bar" or "Auto-école"

### Your Environment
OsmAnd Version: 4.1.11
Android/iOS version: Android 9
Device model: Experience XZ1

**Comment by dmpr0** [comment]
There is no issue with key assigning, the problem could be in the translation of the POI types:
```
<string name="poi_driver_training">Auto-école</string>
<string name="poi_driving_school">École de conduite</string>
```
https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/res/values-fr/phrases.xml#L130

Also, POI type field allows typing POI type name in English.

**Comment by AmaaniL** [comment]
Can you confirm this is still an issue?
