### ISSUE TITLE
unexplained com.android.vending.BILLING permission

### ISSUE THREAD

**Issue by jcflack** [osmandapp/Osmand#1348]
On November 4, 2014, in the r1.9 branch apparently, an addition to AndroidManifest.xml was made in commit 275ea7728c, which adds a requirement for `com.android.vending.BILLING`. There was no other code included in the commit that would explain for what the permission is wanted, and the commit message itself says nothing but "Add billing permission."

There is a "Why does OsmAnd require permission X?" FAQ here:
http://osmand.net/help/faq.html#permission
and it does not give any information as to why the `com.android.vending.BILLING` permission has been added.

In March 2015 an [inquiry](https://github.com/osmandapp/Osmand/commit/275ea7728cac21815c633af4722d0066f0fc273b#commitcomment-9974951) was made as a github line comment in the commit, and [answered](https://github.com/osmandapp/Osmand/commit/275ea7728cac21815c633af4722d0066f0fc273b#commitcomment-10039994) that the permission is not used now, but some update is needed.

In the current OsmAnd available via f-droid, 2.0.4 as of June 2015, the `BILLING` permission is still requested, and there is still no mention of it in the "Why does OsmAnd require permission X" FAQ.

None of this seems as transparent as it could be....

**Comment by vshcherb** [comment]
Explanation is put to faq.html, this is in app is just for GPlay, FDRoid distribution could delete it for example.
