### ISSUE TITLE
Map scrolling is slow under Android 12

### ISSUE THREAD

**Issue by apidya** [osmandapp/OsmAnd#13489]
I'm using the One UI 4.0 with Android 12 on the Samsung Galaxy S21 Ultra and Samsung Galaxy Tab S7+. Ever since the update scrolling the map and zooming is extremely sluggish.

**Comment by marcinsmialek** [comment]
Same here.
I had bad scrolling performance and noticeable wait time for dragged terrain to load and appear, including older Samsung Exynos devices.
However on old Nexus 5X it was butter smooth.

**Comment by AndyGHenderson** [comment]
Seeing the same on a Motorola G30
Andy

**Comment by 0xSteeW** [comment]
I also see this issue in 12L AOSP ROM.
Redmi Note 9.
Previous stock ROM in android 11 rendered without issues.

**Comment by AndyGHenderson** [comment]
I'm a plus subscriber and reinstalling fixed the problem for me. I'd tried turning off shading and contour lines to no effect. Turning on OpenGL rendering via the OsmAnd Developement plugin helped a bit, but was still very slow.

I was also seeing OsmAnd simply stopping at random times. I saw it mostly while trying to navigate a GPX route - but that's mainly how I use it. I also saw it stop while navigating menus. Reinstalling seems to have fixed that issue too. Although OsmAnd offered to restart navigation when restarting, it didn't offer to submit a crash report,

Reinstalling is a pain - especially as none of the OsmAnd backup options worked for me, If you want to test the effect of a reinstall you can install OsmAnd alongside OsmAnd plus.

Andy

**Comment by watashibeme** [comment]
Observed on poco f3, android 12, lineageos
Very laggy and sluggish map rendering, hiding details or enabling opengl rendering dont help.

Throwing a lot of disk write violation,by strictmode process( android.os.strictmode.diskwriteviolation and diskreadviolation)opengl rendering timestamps and a weird buffer queue producer, implying mapactivity got disconnected possible due to switch to another window?)

Narrowed the possible logcat and here's a link to file,doesn't contain personal info so no worries :)

[logcat](https://filebin.net/fafivjylruwa5o5w)

**Comment by watashibeme** [comment]
If possible, get the below logcat to a dev or someone who can understand and or can debug logcat

**Comment by scaidermern** [comment]
Is this related to #12046?

Does enabling OpenGL rendering help? This setting is located in the OsmAnd development plugin and needs an app restart.

**Comment by watashibeme** [comment]
> Is this related to #12046?
> 
> Does enabling OpenGL rendering help? This setting is located in the OsmAnd development plugin and needs an app restart.

Apparently for me, it wasn't related to that

**Comment by julianfairfax** [comment]
> Is this related to #12046?
> 
> Does enabling OpenGL rendering help? This setting is located in the OsmAnd development plugin and needs an app restart.

It doesn't seem to help that much. Here's a video from the latest F-Droid build without it (doesn't support it, not sure why) and one from the latest Play Store build with it. The difference is negligible, at least to me, at least on my device.

https://send.vis.ee/download/0871ea4b8ceba06f/#7lyz8Y_2TSPZXv_DXp5epA (too big for GitHub)

**Comment by michaelblyons** [comment]
> the latest F-Droid build without [OpenGL] (doesn't support it, not sure why)

Really curious about the reason for this, independent of the rendering speed.

**Comment by julianfairfax** [comment]
> > the latest F-Droid build without [OpenGL] (doesn't support it, not sure why)
> 
> Really curious about the reason for this, independent of the rendering speed.
> 
> 

Then you should subscribe to https://gitlab.com/fdroid/fdroiddata/-/issues/2711

**Comment by steewbsd** [comment]
I can confirm the opengl-arm64-nightly build fixed it completely for me.

**Comment by marcinsmialek** [comment]
Enabling OpenGL in the dev plugin of the Google Play version 4.2.7 makes it super-smooth on Exynos Samsung S21U.
I tested it with the older version 4.1.1 and it didn't do a thing.

**Comment by apidya** [comment]
Indeed, that solves my issue. Would you consider I close this, or is further development necessary?

**Comment by vshcherb** [comment]
We have other issues reported, so we don't need to keep as original request has solved
