### ISSUE TITLE
Route calculated throught motor_vehicle=permissive

### ISSUE THREAD

**Issue by thuryn** [osmandapp/OsmAnd#13480]
### Description
Route calculated throught motor_vehicle=permissive on car profile (example of the route https://www.openstreetmap.org/#map=17/50.17729/14.50822,  I`m going to put screenshots but I`m not sure if this is possible.

### How to reproduce?
Set start before route with permissive and put destination behind this route.

### Your Environment
OsmAnd Version: the latest
Android/iOS version: A11
Device model: Xiaomi Mi 9

**Maps used (online or offline):**   
Offline

**Comment by thuryn** [comment]
![Uploading Screenshot_2022-01-04-19-46-12-000_net.osmand.plus.jpg…]()

**Comment by thuryn** [comment]
![Screenshot_2022-01-04-19-46-49-193_de blau android](https://user-images.githubusercontent.com/11028346/148109882-62422f5a-77b8-4daa-a487-ec0ebbabf304.jpg)

**Comment by scaidermern** [comment]
What's wrong with that? permissive is routable. There should probably be a penalty to choose an alternative route if available. But if there isn't or the alternative route is way longer than I don't think this behaviour is wrong.

**Comment by thuryn** [comment]
> What's wrong with that? permissive is routable. There should probably be a penalty to choose an alternative route if available. But if there isn't or if the alternative route is way longer than I don't think this behaviour is wrong.

is it? I tought permissive means that just some people are permitted to pass this way. We all are not - so it seams to me that for most of the people is not routable. Imagine - you select some path and then you end by traffic sign telling you that you are not allowed to pass. This is something I expect that navi cares of it.

**Comment by scaidermern** [comment]
> is it? I tought permissive means that just some people are permitted to pass this way.

No, that would be private instead of permissive. 

https://wiki.openstreetmap.org/wiki/Key:access defines permissive as "Open to general traffic until such time as the owner revokes the permission which they are legally allowed to do at any time in the future." 

So anybody is allowed to use this road. 

If this doesn't match reality than permissive is wrong and needs to be changed to private.

**Comment by thuryn** [comment]
OK, so correct value is "no" then
