### ISSUE TITLE
OsmAnd ignores successful OAuth

### ISSUE THREAD

**Issue by quazgar** [osmandapp/OsmAnd#13502]
OsmAnd seems not to understand when OAuth access was successfully granted.

When trying to upload my OSM notes, OsmAnd offers to use OAuth, which opens a browser frame to enter my OSM credentials and subsequently confirm that OsmAnd should be granted access. But when I grant the access, OsmAnd just returns to the previous normal map view instead of uploading the notes. When I try to upload the notes again, I am asked again to choose an authentication method.  In fact, when I select to upload the notes, the procedure starts anew.

In my OSM user profile I can see that there are multiple authorizations for OsmAnd now, see the screenshot below:

![image](https://user-images.githubusercontent.com/302587/148677210-20f098a9-1683-4d6a-b8f9-bd52937cfc76.png)

**Comment by quazgar** [comment]
Note that this may be related to #9707, but I am not certain.

**Comment by vshcherb** [comment]
We need to double check, also you can help us testing by enabling Test openstreetmap account with Development plugin on

**Comment by quazgar** [comment]
Same behavior with dev plugin enabled.

**Comment by vshcherb** [comment]
Could not reproduce now

**Comment by dfandrich** [comment]
I'm guessing this is now obsolete with the removal of oauth1 support at OSM.
