### ISSUE TITLE
access=destination costs in offline routing.

### ISSUE THREAD

**Issue by flohoff** [osmandapp/Osmand#1350]
Hi,

when going through stretches of access=destination osmand tries very hard to get you off those streets as soon as possible at a very high cost. It seems access=destination ( and possibly other access restrictions ) simply increase the cost-per-meter on those roads. This is wrong as access=destination allows you to leave or enter that area but not to transit it. Even assigning a cost to enter or exiting it would be wrong. A very high cost for transiting the subgraph of access=destination streets would probably be okay as that would then allow a route of last resort if there is no way around a access=destination subgraph.

Flo

**Comment by vshcherb** [comment]
There seems to be no other solution for a short term and we need to deal with coefficients and penalties so far.

**Comment by sonora** [comment]
No action planned, I guess.
