### ISSUE TITLE
Routing: no left turn possible

### ISSUE THREAD

**Issue by quazgar** [osmandapp/OsmAnd#13503]
At this location, OsmAnd does not recognize that turning left is possible:
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=54.51116%2C13.60207%3B54.51331%2C13.60315#map=18/54.51232/13.60367&layers=N

On-site, turning left is possible, and the OSM data also looks good.

Screenshot in OsmAnd:
![Screenshot_20220109-111815](https://user-images.githubusercontent.com/302587/148678206-a48bbdc5-1eba-429b-b231-29be3f6823f2.png)

Screenshot on openstreetmap.org:
![image](https://user-images.githubusercontent.com/302587/148678254-4beb4b51-17ac-44c8-9a27-a3d9c7e24f6e.png)

**Comment by rivermont** [comment]
It might be that the penalty for the light is enough to send the route through all the slipways.
Can you try routing to Gewerbepark just before the slipway, just northwest of the light? If it still goes all the way around, try marking the slipways as avoided to try and force it through the light.

In any case, I added turn restrictions to prevent routing from slipway to slipway, which doesn't look legal anyway.

**Comment by quazgar** [comment]
Yes, your guess seems to be right: 
![image](https://user-images.githubusercontent.com/302587/150687844-a62969bc-238f-4336-8738-2b5ecc0c499b.png)

**Comment by alisa911** [comment]
Hello! The problem was in OsmAnd map. Usually the routing takes into account such sharp turns, but only for different roads. The turns on one road aren't taken into. And in OsmAnd map the different ways Mukraner Straße on this crossroads were merged into one. 
Pleas wait for update maps with correct roads.

**Comment by quazgar** [comment]
Thank you! I want to let you know that I am happy to pay for this app :heart_eyes:
