### ISSUE TITLE
Toast notification showing driving time in seconds

### ISSUE THREAD

**Issue by jase88** [osmandapp/OsmAnd#13501]
### Description
After route calculation was successfull, a toast message is shown with details about the route and calculation. It shows the driving time in seconds, which is a technical representation.
For users it needs to be represented in their (locale depending) duration format. For example: 1h 30mins 15secs (although seconds are probably not relevant at all) 

![Screenshot_20211221-180104~3.png](https://user-images.githubusercontent.com/804836/148675475-cc6f2531-47c0-4dd9-a864-f8ba51bed429.png)

### How to reproduce?
- define a start and end point for a route
- start navigation 
- view upcoming toast message

### Your Environment
OsmAnd Version: OsmAnd+ 4.1.11
Android/iOS version: Android 10
Device model: Nokia 8

**Maps used (offline):**   
Germany_schleswig-holstein_europe
01.01.2021

**Comment by mattmccutchen** [comment]
Peanut gallery comment: That toast is a feature of the "OsmAnd development" plugin, so making it user-friendly probably isn't a priority.  The travel time is shown in user-friendly format in several other places in the UI.

**Comment by vshcherb** [comment]
Well it's a dev plugin feature and it's more useful to capture like that , please disable the plugin and use once it's needed cause it's distracting ;-(
