### ISSUE TITLE
In motorways, say exit number/destination voice command.

### ISSUE THREAD

**Issue by albertodiazsaez** [osmandapp/OsmAnd#13516]
# 🚀 feature request

### Description

When in a motorway, the TTS only says "Continue for about [distance] on [motorway name]", but the screen shows the exit number/destination (alternating exit/destination with name of current road).

### Describe the solution you'd like

I think the TTS should tell you the number/destination of your exit, something like "Continue for about [distance] on [motorway name] until exit [number/destination]". Right now it only says it when you are 1 Km away from the exit. 

The routing example I have is this one (but It happens in a lot of roads, this is my most recent example):

From 39.5153 -0.4304 To: 39.5637 -0.5026

I also think is related to this issue: https://github.com/osmandapp/OsmAnd/issues/11778 but I'm not really sure...

**Comment by vshcherb** [comment]
Yes it's probably related needs to be tested

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-resources/pull/815
Result (bold highlighted what appeared):

- The trip is 12 kilometers time is  9 minutes. 
- after about 1 kilometer enter a roundabout **until the fifth exit on CV 31** 
- in 250 meters enter the roundabout, and take the fifth exit on CV 31 
- take the fifth exit on CV 31 
- after about 1 kilometer, turn slightly right toward Llíria 
- in 250 meters, turn slightly right toward Llíria , then  keep right 
- turn slightly right  , then  in 50 meters, turn slightly right 
- turn slightly right toward Llíria 
- Continue for about 8 kilometers to CV 35 
- after about 1 kilometer, turn slightly right on CV 35 toward Bétera, San Antonio de Benagéber, Riba roja de Túria 
- in 200 meters, keep left toward CV 336, San Antonio de Benagéber, Riba roja del Túria
- keep left 
- in 250 meters enter the roundabout, and take the first exit onto CV 336 toward CV 336, CV 336, CV 35 
- take the first exit onto CV 336 toward CV 336, CV 336, CV 35
- in 200 meters, keep left on CV 336 Carretera Bétera   Riba Roja
- keep left on CV 336 Carretera Bétera   Riba Roja , then  in 100 meters enter the roundabout, and take the first exit 
- take the first exit onto Calle San Vicente Ferrer toward San Vicente , then  in 200 meters enter the roundabout, and take the first exit
- take the first exit onto  Calle del Sequer , then  in 90 meters, keep right 
- and arrive at your destination

**Comment by alisa911** [comment]
from 39.49652 -0.40339 to 39.51071 -0.42667
https://github.com/osmandapp/OsmAnd/pull/14007
Results (bold highlighted what appeared):

- Continue for about 2 kilometers on CV 35 ,  **then  turn slightly right onto exit 4 AB ,  toward CV 365, Paterna, Feria de Valencia**
- after about 1 kilometer, turn slightly right on CV 35 toward CV 365, Paterna, Feria de Valencia 
- in 250 meters, turn slightly right onto exit 4 AB ,  toward CV 365, Paterna, Feria de Valencia 
- turn slightly right onto exit 4 AB ,  toward CV 365, Paterna, Feria de Valencia
- in 250 meters, keep left onto exit 4 B ,  toward CV 365, Paterna, Feria Valencia foro oeste 
- keep left onto exit 4 B ,  toward CV 365, Paterna, Feria Valencia foro oeste 
- Continue for 250 meters to CV 365 Acceso Noroeste de Paterna

**Comment by vshcherb** [comment]
[Some requests were prepared but it requires full refactoring](https://github.com/osmandapp/OsmAnd/pull/14007)

**Comment by sonora** [comment]
Some users complain about some voice prompts being too cchatty, that's why we had suppressed giving such details  many miles away. So let's test now and collect opinions, I guess.

**Comment by vshcherb** [comment]
Indeed, let's see I also have doubts but personally it doesn't sound a bad idea

**Comment by albertodiazsaez** [comment]
When I'm driving in a exit numbered motorway, for me it's more comforting if since the beginning I know the exit number I have to take, I can look at the exits I pass and calculate easily how much time I have to take the exit, it's less stressing for me. 

If feedback is negative tho, can it at least be an option in the settings somewhere?
