### ISSUE TITLE
The map in Occitan does not display in OsmAnd

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#13513]
### Description
The translation is available in Occitan for Marseille, but translation does not display in OsmAnd
https://www.openstreetmap.org/node/26761400

![IMG_2466](https://user-images.githubusercontent.com/80623554/148949588-fe00d370-bccb-49b9-9c6c-c59cc49400e1.PNG)
![IMG_2468](https://user-images.githubusercontent.com/80623554/148949473-eda07a4f-4b15-4ebf-8d82-2e39fc426a93.PNG)

**Comment by xmd5a2** [comment]
OSM data is ok
https://www.openstreetmap.org/node/26761400
