### ISSUE TITLE
Move down the transparency slider on a horizontal screen

### ISSUE THREAD

**Issue by Lans-K** [osmandapp/OsmAnd#13523]
When this slider was corrected on a vertical screen, it just became great to use.
But on a horizontal screen, the slider is very close to the active points of the map's movement and makes it very difficult to work with the map in a horizontal position, which is very much in demand by cyclists.

It may be possible to move this slider down; closer to the buttons and the scale, and make it longer, as in the picture.
It would be very convenient.
Thank you.

![Screenshot_20220105-194318](https://user-images.githubusercontent.com/65672441/148926279-6301d30e-07f0-4613-9f46-7774e4142f66.png)
![Screenshot_20220105-194318-1](https://user-images.githubusercontent.com/65672441/148926311-200fc9c8-079b-4938-a7ff-f6c78429415d.png)

**Comment by Rowin63** [comment]
Seems very similar to my wish #13359 😄

**Comment by Lans-K** [comment]
But you asked for an additional function, with the possibility of moving it.
And in my opinion, it is enough just to move it down and lengthen it a little, in proportion to the free space below.
It seems to me that this is enough. It will be so comfortable and functional. And in all any other places on the screen, it will also interfere.
I think that moving down is a sufficient solution to the problem, without complicating and creating new functionality.
In my opinion, this is the difference.

**Comment by Lans-K** [comment]
Maybe this simple, but important question to use can be moved to milestone 4.2?
It would be wonderful.
Thank you.
_______
Может возможно этот несложный, но важный в использовании вопрос перенести в веху 4.2?
Было бы чудесно.
Спасибо.
