### ISSUE TITLE
Adding second  for track point

### ISSUE THREAD

**Issue by 12TarasoFF21** [osmandapp/OsmAnd#13533]
in the Context menu, where the time is
it is necessary to display the full time, up to seconds

<img src="https://user-images.githubusercontent.com/97671409/149319325-c2c2ff3b-1d64-4d60-856b-f8b0d5f2a7ca.jpg"  width="300" height="auto"/>

**Comment by dmpr0** [comment]
# ToDo
Follow https://github.com/osmandapp/OsmAnd/issues/13524, where we make second visible on graph axis, we need to do similar here.
- [ ]  Show seconds in track point context menu `11.01.2022 15:17:11` (long tap on track line to open). Recheck in 12-hour format.

**Comment by mmh-dev** [comment]
https://github.com/osmandapp/OsmAnd/pull/13801
