### ISSUE TITLE
Forest background missing

### ISSUE THREAD

**Issue by miramikes** [osmandapp/OsmAnd#13549]
Hello,
Forest background is missing on one place ... 
m.![Screenshot_2022-01-15-07-16-08-656_net.osmand.plus.jpg](https://user-images.githubusercontent.com/623412/149611630-73546d66-b910-4b59-8364-8c1771edf303.jpg)

### Your Environment
OsmAnd Version:
Android 10p

**Comment by miramikes** [comment]
Problem also could be in osm date but I am not sure about it.
In some zoom level forest polygon is rendered corectly.
![Screenshot_2022-01-16-22-29-05-430_net osmand plus](https://user-images.githubusercontent.com/623412/149680561-61c7047a-6ea7-4323-9d39-710657179e9c.jpg)
![Screenshot_2022-01-16-22-29-42-905_net osmand plus](https://user-images.githubusercontent.com/623412/149680562-d9c97ded-91fd-46dc-af1c-199bed9e90eb.jpg)

**Comment by xmd5a2** [comment]
Cause of issue is in OSM data. 18.01 it was fixed. February maps should be ok
![Screenshot_2022-01-20_11-27-33](https://user-images.githubusercontent.com/5829014/150301512-4a6313fd-3d65-4e52-a30d-8013311e5dc2.png)
.

**Comment by miramikes** [comment]
Great work 👍
Thank you!
m.
