### ISSUE TITLE
GPX navigation "Pass along entire track" missing

### ISSUE THREAD

**Issue by theraser** [osmandapp/OsmAnd#13547]
### Description
In recent OsmAnd versions I'm unable to find the "Pass along entire track" option. I used it quite often in older OsmAnd versions, but now I'm unable to find it anymore.

OsmAnd itself promoted this feature [here](https://twitter.com/osmandapp/status/965624564603609088] and it is mentioned at the [official FAQ](https://osmand.net/help/faq.html#gpx_routing_params)

I can only find these options when using the internal OsmAnd routing engine:
![Screenshot_20220114-112305_OsmAnd~](https://user-images.githubusercontent.com/7988080/149500496-e3c74214-4303-498c-8a96-23504c51e811.png)
![Screenshot_20220114-112250_OsmAnd~](https://user-images.githubusercontent.com/7988080/149500497-3106693f-2aa7-4b22-b2bc-5edc1641008a.png)

### How to reproduce?
Create a GPX track using any online service starting at your current position, going somewhere else and ends near your starting point. Import it to OsmAnd and try to let it follow the whole track using nagivation.

### Your Environment
OsmAnd Version: 4.0.9 (F-Droid)
Android/iOS version: LineageOS 18
Device model: Fairphone 3

**Maps used (online or offline):**   
Offline maps

**Comment by dmpr0** [comment]
Hi!
We made a lot of changes in Follow GPX UI since the tweet :). Currently, if you want to pass/ride along entire tracks, you need to select `Point of the track to navigate = Start of the track`, in this case, OsmAnd will calculate a route to the track start point, not the nearest point that can be somewhere in the middle or closer to the track end.

**Comment by theraser** [comment]
Interesting, I just tested this option without success before opening the issue - but now it is working as you said. But I think in older versions there were two options: one for navigating to the start point and one for "Pass along entire track" which are two completely different things in my opinion. This may explain my confusion at this point :-)

When I start the navigation somewhere in the middle I cannot navigate the remaining track, since OsmAnd would send me to the start point or use the shortest way to the destination - regardless of the GPX track. Am I right with my assumption? Using older versions this was no problem since there was an extra option "Pass along entire track" (which I think was renamed somewhere in between).

**Comment by dmpr0** [comment]
@theraser 
If you start the navigation somewhere in the middle, you need to select "Point of the track to navigate = Nearest point" in this case, OsmAnd should calculate the route or draw a straight line (depends on Navigation type) from your location to the nearest track point.
