### ISSUE TITLE
.metainfo max_zoom is not supported

### ISSUE THREAD

**Issue by mariush444** [osmandapp/OsmAnd#13552]
.metainfo file is

```
[url_template]
https://apps.fs.usda.gov/arcx/rest/services/EDW/EDW_FSTopo_01/MapServer/WMTS/tile/1.0.0/EDW_EDW_FSTopo_01/default/GoogleMapsCompatible/{$z}/{$y}/{$x}.png
[ext]
.png
[min_zoom]
13
[max_zoom]
14
[tile_size]
256
[img_density]
16
[avg_img_size]
18000
```
but osmand downloads more level zooms from server. In this case zoom levels **10, 11, 12**, 13, 14.
min_zoom is supported, max_zoom is NOT supported

Tested for location 44.03991 -72.90766

### Your Environment
OsmAnd Version: 4.1.11
Android/iOS version: Android 8.0/11.0

Discussed in https://github.com/osmandapp/OsmAnd/discussions/11864

**Comment by ivanPyrohivskyi** [comment]
Bug is not reproduce.
In tiles cache save from minimal to maximal zooms.
In rendering overscaling to -2 and +2 zooms.
