### ISSUE TITLE
Poor formatting of OSM login in landscape mode

### ISSUE THREAD

**Issue by thompehw** [osmandapp/OsmAnd#13567]
Similar to #13283 (fixed).

![Screenshot_20220118-021607_OsmAnd Nightly](https://user-images.githubusercontent.com/39751382/149861165-c35a8610-515a-4fe2-bfd5-2edda4d7360d.jpg)

![Screenshot_20220118-021627_OsmAnd Nightly](https://user-images.githubusercontent.com/39751382/149861222-78f2d2ef-cd81-43a7-950d-9be830317363.jpg)

Latest nightly
Android 10
Samsung Galaxy Tab A SM-T510

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14226mqta, Released: 2023-03-09
Done
<img width="764" alt="Screenshot 2023-03-09 at 10 49 13" src="https://user-images.githubusercontent.com/104760013/223969275-95c95b5b-2605-4ce2-a874-9904b5921367.png">
