### ISSUE TITLE
Lane Guidance Arrows Don't Match Route

### ISSUE THREAD

**Issue by pnoll1** [osmandapp/OsmAnd#13560]
### Description
Lane guidance arrows on screen don't match route. In the screenshot, you'll see the route takes the slight_right option while guidance shows the "right" option.
![image](https://user-images.githubusercontent.com/8444617/149682241-17a90795-9f7f-42b4-80c9-80454a3a571a.png)
### How to reproduce?
Create Route from S Spokane St to  I5 South

### Your Environment
OsmAnd Version: Fdroid 4.0.9
Android/iOS version:11 (Lineage 18)
Device model:Moto Z3 Play

**Maps used (online or offline):**   
Offline, custom build, found at https://github.com/pnoll1/osmand_map_creation/releases/download/0.84/Us_wa.obf
Nothing involved with routing has been modified.

**Comment by avataranedotas** [comment]
I have the same problem in Portugal and the Voice Guidance also does not match the route shown on screen.

**How to reproduce?**
Create Route from 37.101368, -7.678949 to 37.099458, -7.683851

**Your Environment**
OsmAnd Version: Google Playstore version 4.1.11
Android/iOS version: Android 11 or Android 9
Device model:Any Android Smarthphone, even tried with Android PC x86

**Maps used (online or offline):**
Offline official download inside OSMAND
Nothing involved with routing has been modified.

**Comment by pnoll1** [comment]
![Screenshot_20220222-190451_OsmAnd~](https://user-images.githubusercontent.com/8444617/155258880-5380c5ac-3d52-4641-8447-4febbfffc980.png
I can't reproduce issue with fdroid 4.1.11 release. I just drove the route again and received correct guidance pictured above.

**Comment by hklene** [comment]
OSM tells me to go straight with a green arrow (sound was off, so no idea, if there was anything on the audio), but the route shall go left with two dedicated left lanes (arriving from north-west to this crossing - exiting north-east):
https://www.openstreetmap.org/node/3814642407

Even though there is a green circle in the middle, it is not a traditional circle. The lanes of the circle are interrupted with their own traffic lights. If you want to do the full circle you'd have to pass 4 traffic lights with 4 left turns.

![Screenshot_20220612-132811](https://user-images.githubusercontent.com/7427503/175086013-704a3014-9f93-4aad-bea1-b562329605b7.jpg)

**Comment by vshcherb** [comment]
As I see with new map data and program it should be fixed (click on orange boxes) https://osmand.net/map?start=52.270496%2C10.499515&end=52.270519%2C10.501543&mode=car#19/52.27030/10.50033
