### ISSUE TITLE
The import net.osmand.plus.R cannot be resolved

### ISSUE THREAD

**Issue by moosaviamir** [osmandapp/Osmand#1356]
Hi 
I just downloaded the source code and imported to eclipse ADT. I get the following error. 
I wonder if someone could tell me what did i wrong?
I'm not new to android and programming but this project gives me error!
please tell me what to do
regards

**Comment by vshcherb** [comment]
Not an application issue. Please check forum for help

**Comment by moosaviamir** [comment]
thank you
