### ISSUE TITLE
Force app restart after modifying storage path

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#1357]
Hi.

OsmAnd does not auto initialize maps after changing the storage path (for example to external SD card). Please do either re-inizialize all stored data or do a re-start of the app to achieve the same. Currently the user has to force close OsmAnd since the Exit menu item has been removed in release 2.1.

**Comment by vshcherb** [comment]
There is a task which reloads all indexes, please create a use case. Cause it was tested for several cases and it worked.
