### ISSUE TITLE
Osmand preffers primary_link over primary

### ISSUE THREAD

**Issue by lucumon** [osmandapp/OsmAnd#13587]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Car

### Start and end points
Start: https://osmand.net/go?lat=42.88098358424414&lon=-8.533045298199426&z=19
End: https://osmand.net/go?lat=42.882137298583984&lon=-8.533178329467773&z=19

### Actual and expected routes
Osmand tells to drive through a primary link that conects the primary road with a service road, instead of going straight on the primary.

![Screenshot_20220120-120144_OsmAnd.jpg](https://user-images.githubusercontent.com/24960275/150327960-cb162d37-4969-4406-a238-8254fec8d6c3.jpg)

### Is this a regression?
I don't know

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

4.1.11
</code></pre>

**Device and Android/iOS version:**
Pocophone F1, Android 10 Evolution OS
**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**

**Comment by scaidermern** [comment]
Strange. The link road has no maxspeed set. However it is really short, involves two road changes, has cobblestone (probably doesn't matter).
