### ISSUE TITLE
No Option To Remove POI?

### ISSUE THREAD

**Issue by seniorm0ment** [osmandapp/OsmAnd#13583]
Unless I'm missing it, I see no way to remove a POI from the map. I can modify, but not just completely remove.
This is useful for buildings that no longer exist, or closed down.

**Comment by scaidermern** [comment]
Edit a POI, then select remove and upload it.

Similar to editing, this will only work for POIs and not for other things like buildings or roads.

**Comment by seniorm0ment** [comment]
My point is I do not see that delete button.
I click on a place on the map, click actions, click modify POI, and see no option to just delete it.

**Comment by scaidermern** [comment]
This button is located in the lower left corner. But only for POIs that have been mapped as a node. If the POI is a way then this button is not available since often deleting the way is wrong and instead the POI tags have to be removed from the way.

Use a different editor (e.g. Vespucci for Android or JOSM/iD if you are on a computer) for these cases.

**Comment by seniorm0ment** [comment]
>If the POI is a way

So would this issue still not be valid, and should be reopened?
It's kinda stupid to have to rely on an external editor to remove a POI when you can edit it already.

Also is there a way to determine if a POI is mapped as a node?

**Comment by scaidermern** [comment]
> So would this issue still not be valid, and should be reopened? It's kinda stupid to have to rely on an external editor to remove a POI when you can edit it already.

You can also edit the POI, switch to the advanced tab and remove all relevant tags.

> Also is there a way to determine if a POI is mapped as a node? (besides a missing deletion button)

Tap on the POI. In the details there is a link to the POI at https://openstreetmap.org. You can see at the URL if it is a node, way or relation.
