### ISSUE TITLE
App crashes on startup while initializing with OutOfMemoryError (FP4 /e/OS)

### ISSUE THREAD

**Issue by patterchon** [osmandapp/OsmAnd#13581]
App is freshly installed on Fairphone 4 with Android 11 (/e/OS) via f-droid. 
Every time when starting the app, an Osmand welcome image appears and the app crashes.
At the next start an exception log can be saved - see [exception.log](https://github.com/osmandapp/OsmAnd/files/7895443/exception.log).

I already tried without success:
- Delete app cache, delete app data, uninstall / reinstall app
- Previous version from f-droid store

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/13598
