### ISSUE TITLE
OsmAnd 2.1 release does not display zoom level (regression)

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#1358]
Former builds have displayed zoom level by replacing the earth/car/bike/pedestrian icon for a short time during zoom with the number of the zoom level.

**Comment by vshcherb** [comment]
May be a false alarm, don't remember any related change. Wouldn't call it regression if it doesn't show it just a bug.

**Comment by Norbert80** [comment]
@vshcherb zoom level numbers have been displayed with the last nightly I had installed. I think this was OsmAndF~2.1.0#7792D.

**Comment by vshcherb** [comment]
Most likely the dev plugin was not enabled in release

**Comment by Norbert80** [comment]
@vshcherb Confirmed. Thanks for the info.

**Comment by sonora** [comment]
No, cannot confirm here: True that with dev plugin enabled, upon zooming the profile icon briefly vanishes, then re-appears, but (at least on most devices) I cannot see the zoom level display in this brief time slot there. Not sure whether we are missing an additional redraw of that area, or the display time is so short that faster devices turn back to the profile icon before the digits become visible. So I suggest let's define a time like 1sec for which the display needs to be visible... the we can check if this works on all devices.
