### ISSUE TITLE
wrong time reported for next live update check

### ISSUE THREAD

**Issue by tommycrock** [osmandapp/OsmAnd#13595]
### Description
The live updates dialogue says it will update again an hour after the map data time instead of an hour after it last checked (which is when it should and does check).

e.g. here the update was done at 22:54 on 20 Jan getting a map from 22:10, 19 Jan. The next check will be at 23:54 but osmand says 23:10 yesterday (!).
<img src="https://user-images.githubusercontent.com/5749884/150439497-9a0f9224-01bd-4def-9605-393991967085.jpg"  width="300" height="auto"/> 

### How to reproduce?
Turn on hourly live updates

### Your Environment
OsmAnd Version:4.1.11 ( but have seen it for at least all of v4.x)
Android/iOS version: Android 12 (but saw it with 10 and 11)
Device model: Samsung s10e

**Comment by scaidermern** [comment]
Is this the same as #13924?

**Comment by tommycrock** [comment]
> Is this the same as #13924?

I think so, yes. I have seen other, similar problems with live updates genuinely seeming to stop updating but #13924 does seem to be the product of the wrong field being displayed against next time

**Comment by tommycrock** [comment]
> Suggestions to rename fields:
> 
>     1. Map available to download from OpenStreetMap (on OsmAnd servers processed OSM data) or 'Map data processed and available from OSM' - Timestamp A
> 
>     2. Map update was checked 5 min ago / 1 day ago at 15:23...
> 
>     3. Latest map update (it should be a timestamp A from last successful update)

Is 1. from the overall live updates screen? I like the current text "Latest OpenStreetMap update available".
Could 3. be "OpenStreetMap data from:" / "Current installed OpenStreetMap data from:"? I think they would provide more clarity, although what you show in the screenshot also seems fine. The problem is the text after that, the time/date for Next update using the wrong field in 4.1.11 (looks right in your screenshot)

**Comment by cepprice** [comment]
https://github.com/osmandapp/OsmAnd/pull/14548
