### ISSUE TITLE
wrong zoom for dowload tiles

### ISSUE THREAD

**Issue by mariush444** [osmandapp/OsmAnd#13591]
### Description
according to https://docs.osmand.net/en/main@latest/osmand/map/raster-maps#download--update-tiles
there is possibility to download tiles from defined WMS/WMST by user.

but downloading screen doesn't respect definition of the source.

Example 1
defined zoom = 14 - 17
but downloading screen shows 10 - 17
![a1](https://user-images.githubusercontent.com/66887280/150385236-31fb2acc-64de-4929-b262-e8827c5ea518.png)
it seems that there are all possible layers but ...

Example 2
defined zoom = 13 - 14
but downloading screen shows 14 - 14
![b1](https://user-images.githubusercontent.com/66887280/150385455-d8ebcad6-969e-484b-b1a5-436999bf9125.png)
all possible layers are 10-17

### How to reproduce?
Example 1
source
https://mapserver.bdl.lasy.gov.pl/arcgis/rest/services/WMTS_BDL_kat_wlasnosci/MapServer/WMTS/tile/1.0.0/WMTS_BDL_kat_wlasnosci/default/GoogleMapsCompatible/{0}/{2}/{1}.png
can be tested at any place in Poland.

Example 2
https://apps.fs.usda.gov/arcx/rest/services/EDW/EDW_FSTopo_01/MapServer/WMTS/tile/1.0.0/EDW_EDW_FSTopo_01/default/GoogleMapsCompatible/{0}/{2}/{1}.png
can be tested at 43.313844, -72.933849

### Your Environment
OsmAnd Version: 4.1.11
Android/iOS version: 8.0/13.0

**Comment by vshcherb** [comment]
Now you can pinch to zoom on map preview
