### ISSUE TITLE
Crash on Fairphone 4 with /e/ OS

### ISSUE THREAD

**Issue by ciropom** [osmandapp/OsmAnd#13598]
### Description
I bought a murena fairphone 4 from /e/ foundation.
Installed osmand from f-droid but it doesn't even start.

### How to reproduce?
Open the app, click "start" from the very first introductory screen. Crash.
Here is the adb logcat [osmand-exception.txt](https://github.com/osmandapp/OsmAnd/files/7911625/osmand-exception.txt)

### Your Environment
OsmAnd Version: 4.1.11
Android/iOS version: Android 11 with /e/ OS
Device model: FP4

**Comment by vshcherb** [comment]
The only visible crash is 
```
java.lang.OutOfMemoryError: Failed to allocate a 2208 byte allocation with 408 free bytes and 408B until OOM, target footprint 37748736, growth limit 37748736
```

**Comment by ciropom** [comment]
I see, but I checked and I have plenty of memory. Any clue on why this happens?

**Comment by vshcherb** [comment]
It's java memory - it's limited to 40 MB somehow. You can see in Plugin - Development - Settings .

**Comment by ciropom** [comment]
No, as I was sayin before, it doesn't even start, I can't go to the preferences.

**Comment by ciropom** [comment]
[exception.log](https://github.com/osmandapp/OsmAnd/files/7914048/exception.log)

**Comment by ciropom** [comment]
probably an /e/ issue

https://gitlab.e.foundation/e/backlog/-/issues/4649

**Comment by fhvyhjriur** [comment]
0.21-r-20220123158735-stable-FP4 firmware for the Fairphone 4 is been rolled out today that include the fix. https://gitlab.e.foundation/e/backlog/-/issues/4649#note_156062
This issue can be closed.
