### ISSUE TITLE
Belgium / Translation 2 regions: Flanders + Brussels and  Wallonia

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#13599]
- Brussels Flanders
- Berlin Brandenburg

Belgium is divided into three federal regions with equal status: Flanders, Wallonia, and Brussels. Brussels is entirely surrounded by Flanders. In OsmAnd the map area "Flanders" includes not only the region of Flanders but also Brussels, so the Belgium map should be divided into 3 regional maps.

https://builder.osmand.net:8080/view/Generate%20Maps/job/Maps_GenerateCountriesOcbf/

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-misc/pull/132
https://github.com/osmandapp/OsmAnd-resources/pull/776

**Comment by xmd5a2** [comment]
Fixed
![Screenshot_2022-02-14-14-47-35-936_net osmand plus](https://user-images.githubusercontent.com/5829014/153860001-03a6b73e-b0ae-488c-9d81-36150f8f4e32.jpg)
