### ISSUE TITLE
Map loading bug

### ISSUE THREAD

**Issue by d4f5409d** [osmandapp/OsmAnd#13593]
### How to reproduce?

Zoom out / Zoom in the app

### Your Environment
OsmAnd Version: 4.1.11
Android/iOS version: Android 11
Device model: OnePlus 8

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
Both

As you see on the footage, the topo-map loads correctly while zooming, but the base map layer doesn't. It would be cool, if you could fix this issue to make it load properly. https://user-images.githubusercontent.com/76624594/150418816-dbd01409-4b23-4d76-bd84-e295a73a051c.mp4

**Comment by vshcherb** [comment]
To be honest from the footage  it's not clear what's expected behavior.

**Comment by d4f5409d** [comment]
To get the basemap (OSM vector map) load WHILE zooming too, like Topo map (see it loads while zooming, not only after I did let my fingers go from the screen)

**Comment by d4f5409d** [comment]
This bug doesn't exist in the new OpenGL version.
