### ISSUE TITLE
Different preset between the 4.1.11 from FDroid and from Gplay

### ISSUE THREAD

**Issue by letypequividelespoubelles** [osmandapp/OsmAnd#13605]
### Description
It seems that #5958 has been solved only for android version coming from gplay, not for the one coming from FDroid. In the 4.1.11 version (from Gplay), a new preset "guidepost" has the right tagging scheme (tourism=information + information=guidepost), and the old preset "information guidepost" (which tags only information=guidepost) is still there. In the Fdroid 4.1.11 version, only the old preset is there, and we don't have the new preset.

Imha, the old preset needs to be deleted, and the new preset available for the FDroid version. 

Thanks a lot !

**Comment by mariush444** [comment]
osmand~ is maintained by other team.
Probably you should post somewhere there https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9678
to Licaon_Kter

But it would be surprise that the source is different.
Generally it's degooled osmand+ version AFAIK

**Comment by letypequividelespoubelles** [comment]
Put an issue [on the FDroid Git.](https://gitlab.com/fdroid/fdroiddata/-/issues/2587)

@vshcherb Wouldn't it better to delete the old preset that misses a tag ? 

Thanks

**Comment by vshcherb** [comment]
Which preset?

**Comment by letypequividelespoubelles** [comment]
the preset named "information guidepost" which is just "information=guidepost".

The new preset "guidepost" is "tourism=information & information=guidepost" which is the right tagging scheme.
