### ISSUE TITLE
Routing Issue - Elbbrücke Dömitz (Germany) - Weird turn without an actual street

### ISSUE THREAD

**Issue by jfastnacht** [osmandapp/OsmAnd#13617]
# 🐞 routing report

### Routing engine

- [X] OsmAnd's in-app offline routing
- [X] OSM / GraphHopper

### Routing Profile

* Car (ferries deactivated)

### Start and end points

Routing: https://www.openstreetmap.org/directions?engine=graphhopper_car&route=53.15185%2C11.23624%3B53.12879%2C11.23509#map=14/53.1406/11.2297

Problematic way: https://www.openstreetmap.org/way/34248466

### Actual and expected routes

OsmAnd Route (actual):

![Screenshot_20220124-125245](https://user-images.githubusercontent.com/6183607/150785422-2ba2a399-3b7b-4b98-8b48-2c02971fcbc7.png)

OSM / GraphHopper Route (expected):

![doemitz_elbbruecke](https://user-images.githubusercontent.com/6183607/150785448-46f8cacc-484b-4c6e-ba1f-20beb93d6b73.png)

### Is this a regression?

I don't know.

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>4.1.11</code></pre>

**Device and Android version: **

<pre><code>Nokia 8</code></pre>
<pre><code>Android 9</code></pre>

**Maps used (online or offline): offline**

- [x] Offline maps offered within the OsmAnd app for download.
- [ ] Online (tile / raster) maps

**Anything else relevant?**

**Comment by hakuchi** [comment]
do you have latest map updates?
maybe it get fixed if you delete the maps and download again

**Comment by jfastnacht** [comment]
Yes, thanks! I removed all maps and downloaded them again, navigation is fixed now.
