### ISSUE TITLE
Turn lanes: Incorrect traffic lane

### ISSUE THREAD

**Issue by pl71** [osmandapp/OsmAnd#13621]
Not sure if this is for here (routing issue), we have a wrong turn lane issue.

Turn lanes shown in the picture below are for the first intersection (also marked with red circle).
Turn lanes for this way https://osm.org/go/x1DHlH3Ug?m=&way=769446293 are left;through|right|right
At first intersection (red circle) we should go straight (through lane) and after that we should turn right (where we still have no turn lane tag).

![Untitled](https://user-images.githubusercontent.com/4776779/150944983-7a412bf4-61dc-463a-aff7-55287a47b790.jpg)

# 🐞 routing report

### Routing engine

- [X] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

 CAR

### Start and end points
Start 42.69002, 23.33703
End 42.69032, 23.33956

![Screenshot 2022-01-25 110353](https://user-images.githubusercontent.com/4776779/150945879-cbd0fd5e-5dcc-43f0-a8a1-b6aeb95d5a4d.png)

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

4.1.11

</code></pre>

**Device and Android/iOS version:**
Galaxy S8
Android 9
**Maps used (online or offline):**

- [X] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**

**Comment by alisa911** [comment]
Hello! It will be fix in new version of the OsmAnd. And please update this map.
