### ISSUE TITLE
Map legend offline or more info about objects in app

### ISSUE THREAD

**Issue by DFyson** [osmandapp/Osmand#1362]
Would be great to be able to pull up a map legend for the current style of map, while offline. Currently the only way I know is to go to the website to get a legend but only for the default map style.
Alternatively have an interactive map legend where one can select an object from he current screen to understand what the symbol represents. Similar feature request to #838.

**Comment by DFyson** [comment]
Why was this closed?

**Comment by vshcherb** [comment]
Cause it is the same as 838.
