### ISSUE TITLE
Inaccurate track display

### ISSUE THREAD

**Issue by blaueente** [osmandapp/OsmAnd#13636]
### How to reproduce?
* Record a track (multiple hours, not sure if it is the same with shorter ones, possibly)
* Show track details 
* "analyze track on map" (only have the localized names, this might sound slightly different in the english version)
* graph by "Time of day"
* Zoom into height/speed graph
* In x axis description, some minutes are missing, others are duplicate.

![xaxis](https://user-images.githubusercontent.com/10434139/151244089-88c95cb3-6a15-4872-9fbc-c6d65ae71881.jpg)

Expectation: 
* x-axis displaying correct seconds hh:mm:ss if zoomed in sufficiently.

### Your Environment
OsmAnd Version: OsmAnd~ 4.1.11
Android/iOS version: Android 12
Device model: Pixel 6 Pro

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by vshcherb** [comment]
Duplicate https://github.com/osmandapp/OsmAnd/issues/13533  https://github.com/osmandapp/OsmAnd/issues/10373
