### ISSUE TITLE
Scale Bar

### ISSUE THREAD

**Issue by DFyson** [osmandapp/Osmand#1363]
Would be nice t

**Comment by DFyson** [comment]
Would be nice to have option to show a scale bar on the screen.

**Comment by stephan75** [comment]
On my latest nightly build from Osmand, I have a map scale displayed on the bottom of the screen, even in main map browse mode and in car mode, same in bicycle and foor profile.

Formerly there was even an option to turn that scale off and on again, but cannot find that switch any more.

So please add a screenshot here where that scale is missing.

**Comment by DFyson** [comment]
Sorry I checked again and its there. Must have been from an older version or something.

**Comment by DFyson** [comment]
Sorry I checked again and its there. Must have been from an older version or something.
