### ISSUE TITLE
Major motorway vanishes from map

### ISSUE THREAD

**Issue by 32Vache** [osmandapp/OsmAnd#13649]
- [x] Generate basemap 15.04.2022

### Description

A major motorway in France vanishes from map at low zooms since latest world basemap update.
More exactly the A1 in Northern France
See [this recording](https://mega.nz/file/TqxRhS7D#ISPfVtlF4OUdu3MqkH--Rx7p4HIp3_GDAe_KWx7W0Cw)

### How to reproduce?
- Install latest world basemap update from 22 Jan. 2022
- Zooms 8 to 6 do not display the motorway

### Your Environment
OsmAnd Version: 4.1.11
Android/iOS version: 11 [MIUI 12.5.4.0]
Device model: Xiaomi POCO X3 Pro

**Maps used (online or offline):**   
World_basemap (22-01-2022)

**Comment by ivanPyrohivskyi** [comment]
Fix glue in base map (basemap generation Java):
![IMAGE 2022-02-22 15:39:00](https://user-images.githubusercontent.com/1040293/155143613-aecfb1de-6a2a-4de0-b3eb-8a31def5de08.jpg) ![IMAGE 2022-02-22 15:39:04](https://user-images.githubusercontent.com/1040293/155143623-4f97aac7-ad4a-4b88-af5c-9fefdf198e10.jpg)

Fix distance in rendering (C++ rendering):
![IMAGE 2022-02-22 15:38:52](https://user-images.githubusercontent.com/1040293/155143592-1f690718-344e-40f6-9caa-60c461bf18c8.jpg)

**Comment by ivanPyrohivskyi** [comment]
Previous changes in basemap:
https://github.com/osmandapp/OsmAnd-tools/pull/458/files

**Comment by alisa911** [comment]
- [ ] fix missing road https://github.com/osmandapp/OsmAnd-tools/pull/473
- [ ] Fix glue in base map

**Comment by ivanPyrohivskyi** [comment]
Generate basemap April 15 2022
