### ISSUE TITLE
OSM Editing: suggest `service:bicycle` and similar when `bicycle`  or `bic` is typed.

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#13660]
# ToDo
Suggest `service:bicycle` and similar tags when `bicycle`  or `bic` is typed. Search for matches only between :

<table style="width:100%">
<tr>
  <th colspan=2>Android</th>
  <tr>
    <th><img src="https://user-images.githubusercontent.com/9365308/151386163-680d88fb-13a9-4cc4-bf95-463c636311c5.jpeg"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/9365308/151386168-6775d19d-c192-4511-9d81-10e11208f59d.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table> 

<table style="width:100%">
<tr>
  <th colspan=2>iOS</th>
  <tr>
    <th><img src="https://user-images.githubusercontent.com/9365308/200598738-ce273115-c478-44de-b727-1a42406db372.PNG"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/9365308/200598760-deb065e1-93de-4695-9de7-b6088e6778bf.PNG"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2340

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd/pull/15876

**Comment by EugeneZmeuk** [comment]
https://osmand.net/docs/user/plugins/osm-editing#create--modify-poi
