### ISSUE TITLE
Add filter "fee=yes/no" for the charging station POI

### ISSUE THREAD

**Issue by fhvyhjriur** [osmandapp/OsmAnd#13667]
The functionality to filter for different types of chargers and other things are already there: https://github.com/osmandapp/OsmAnd/issues/13076#issuecomment-958731825

But i cant filter for fee=yes/no in the filter options.
It would be great if you could add this.

**Comment by scaidermern** [comment]
Should this be a tri-state switch? Since there can be either `fee=yes`, `fee=no` or no `fee` tag at all.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/13450 Duplicate ?
