### ISSUE TITLE
Direction overlay arrows join at certain zoom levels during navigation

### ISSUE THREAD

**Issue by jeenuv** [osmandapp/Osmand#1366]
I like the new yellow overlay arrows that show direction during navigation. I noticed that, at certain zoom levels, some of these are displayed as joined together, which is rather unseemly. I've a screen shot here: https://goo.gl/photos/wy1ZDux5kthgCsKt8

To reproduce, I think you ought to navigate through rather windy roads, and try zooming in/out, until this effect is visible. The coordinates I used is also visible in the screen shot, so someone could use the exect route.

**Comment by Norbert80** [comment]
Duplicate of #1337. I have attached jeenuv's screen shot directly to GitHGub.

@jeenuv what device type are you using?

![screenshot_2015-06-18-12-12-30](https://cloud.githubusercontent.com/assets/6921696/8238948/1f8f3c4c-15f9-11e5-94d6-a0c475322553.png)

**Comment by jeenuv** [comment]
I'm on Moto E 2nd Gen 4G

**Comment by vshcherb** [comment]
Duplicate
