### ISSUE TITLE
TTS Does not work with RHVoice

### ISSUE THREAD

**Issue by pierre-quelin** [osmandapp/OsmAnd#13672]
### Description
Seems to be very similar to this ticket https://github.com/osmandapp/OsmAnd/issues/11373
I'm using CalyxOS which does not include a TTS engine. I should be able to use my TTS engine of choice, RHVoice.
I'm French but I select "anglais (États-Unis)" as default language for RHvoice and "English" for OsmAnd, However it does not work. When I start the routing, I get the message "Cannot start text-to-speech engine".
I tried the workaround indicated in the previous ticket.
I enabled the Development plugin, then in its settings I tried to used the button 'Test voice prompts'. I select "en-tts" but Message "Cannot start text-to-speech engine" appeared again.

### How to reproduce?

Used the official CalyxOS ROM without Google's TTS engine, install RHVoice, and download the voices you need. Make sure it is set as the default TTS engine (which it was, since it was the only one I had installed).
Then start Osmand and start navigating.

### Your Environment
OsmAnd Version: 4.0 08/2021
Android/iOS version: CalyxOS - Android 12
Device model: Pixel 4a

I don't have any workaround.

**Comment by dane-stevens** [comment]
I just got it working on GrapheneOS. Looks like you have to go to System > Languages and input > Text-to-speech output. Where you see RHVoice, click on it and it will ask if you want to enable it. (even though it is pre-selected as the only engine, it does not actually enable by default.)

**Comment by dane-stevens** [comment]
I checked it a whole bunch of times too, did you actually click on the radio button that says RHVoice? Mine was showing that RHVoice was set as the default, but it wasn't till I specifically clicked it again, that the prompt to enable it popped up.

**Comment by pierre-quelin** [comment]
I don't know if it is an operating system issue, RHVoice issue or osmand issue but click the button again solve this.

**Comment by Lee-Carre** [comment]
> I don't know if it is an operating system issue, RHVoice issue or osmand issue

Seems to be an OS issue. See #9637.
