### ISSUE TITLE
Removing intermediate routing destinations leads to strange behavior.

### ISSUE THREAD

**Issue by phillegroom** [osmandapp/OsmAnd#13671]
### Description
When removing interim routing destinations subsequently calculated routes make no sense.
My workaround is to never do that. Instead, start anew.

### How to reproduce?
Remove an interim routing destination and routes will become unusable until routing is terminated and restarted.

### Your Environment
OsmAnd Version: OsmAnd~ 4.0.9 (via F-Droid)
Android/iOS version:
Device model: Both my Samsung Devices (Tablet and Phone)

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

It is on offline maps. However, all versions have been affected by this bug so far, so it is not related to map data.

**Comment by vshcherb** [comment]
Please try with 4.1 or 4.2 nightly build. I think that issue was fixed in 4.1 release
