### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by gouravpal1991** [osmandapp/Osmand#1368]
Osmand-master/OsmAnd/src/net/osmand/plus/helpers/WaypointHelper.java
Error:(687, 56) error: cannot find symbol variable mx_highway_speed_camera
Error:(689, 56) error: cannot find symbol variable mx_barrier_border_control
Error:(703, 56) error: cannot find symbol variable mx_toll_booth

Osmand-master/OsmAnd/src/net/osmand/plus/activities/MapActivityLayers.java
Error:(295, 22) error: cannot find symbol variable mx_user_defined
Error:(157, 90) error: cannot find symbol variable h_arrow

Osmand-master/OsmAnd/src/net/osmand/plus/activities/search/SearchPoiFilterFragment.java
Error:(261, 38) error: cannot find symbol variable mx_name_finder
Error:(263, 38) error: cannot find symbol variable mx_user_defined

**Comment by vshcherb** [comment]
Better put this question on forum or search in google
