### ISSUE TITLE
Routing penalties cannot be applied to amenity=ferry_terminal nodes in routing.xml

### ISSUE THREAD

**Issue by Zero3** [osmandapp/OsmAnd#13684]
You are supposed to be able to apply routing penalties to `amenity=ferry_terminal` nodes in `routing.xml` since OsmAnd 4.1.10. See https://github.com/osmandapp/OsmAnd/issues/12854 for more info.

However, I am unable to make this work. Quote from https://github.com/osmandapp/OsmAnd/issues/12854#issuecomment-994848285 in the original issue:

> I tested this issue again on version 4.1.10, and it still does not work. No time is added to the estimated travel time for a route passing through multiple `amenity=ferry_terminal` nodes, even with a huge penalty like this one:
> 
> ````
> <osmand_routing_config ...>
> 	...
> 	<routingProfile ...>
> 		...
> 		<point attribute="obstacle_time">
> 			...
> 			<select value="1800" t="amenity" v="ferry_terminal"/>
> 			...
> 		</point>
> 		...
> 	</routingProfile>
> 	...
> </osmand_routing_config>
> ````

Please let me know if I can assist in testing/debugging. I am quite familiar with how `routing.xml` works by now :).

**Comment by xmd5a2** [comment]
You should add this line to `<obstacle>` section, not `<obstacle_time>`. Please read https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#L71

**Comment by Zero3** [comment]
@xmd5a2 I am aware of the difference, and already read the documentation you are linking to. In my example above I used `obstacle_time` to make it easier to debug (since it affects estimated travel time, unlike `obstacle` which only affects routing).

That being said, I re-tested on the latest bugfix release, 4.1.11, and now it seems to partially work :smiley:. My `ferry_terminal` penalty is applied, but only *once* per ferry route, even though there is a `ferry_terminal` node on each end of the ferry route. Is there some kind of special handling of ferry routes that causes end node penalties to only be added once instead of for both ends?

**Comment by Zero3** [comment]
Actually, I think this is still pretty broken. I did some more testing, and have come to the conclusion that `amenity=ferry_terminal` penalties are applied very inconsistently. I tested with different penalties in both `obstacle` and `obstacle_time`, and here are some test cases that show the broken behaviour:

Test case A: https://www.openstreetmap.org/way/28007758

* `obstacle_time` penalty is applied **only once**
* `obstacle` penalty is **not applied**

Test case B: https://www.openstreetmap.org/way/29254532

* `obstacle_time` penalty is **not applied**
* `obstacle` penalty is **not applied**

Test case C: https://www.openstreetmap.org/way/32820722

* `obstacle_time` penalty is applied **twice** (once for each `amenity=ferry_terminal` as expected)
* `obstacle` penalty may or may not be applied (I'm not sure how to test, as this route is to an island without alternative road access)

@vshcherb could you reopen please? Thanks!

**Comment by xmd5a2** [comment]
Tested with `<select value="100" t="amenity" v="ferry_terminal"/>` in `<obstacle>` and `<obstacle_time>` sections
**Test case A:**
_Default:_
Route <route>: **routing_time=403,0**, vehicle=car, base=false, start_lat=56,70911, start_lon=9,17424, target_lat=56,70028, target_lon=9,19172, complete_distance=1607,8, **complete_time=282,8**, native=true
_With penalties:_
Route <route>: **routing_time=603,0**, vehicle=car, base=false, start_lat=56,70911, start_lon=9,17424, target_lat=56,70028, target_lon=9,19172, complete_distance=1607,8, **complete_time=482,8**, native=true

**Test case B:**
_Default:_
Route <route>: **routing_time=310,1**, vehicle=car, base=false, start_lat=56,74017, start_lon=8,48665, target_lat=56,73857, target_lon=8,50429, complete_distance=1087,0, **complete_time=189,8**, native=true
_With penalties:_
Route <route>: **routing_time=510,1**, vehicle=car, base=false, start_lat=56,74017, start_lon=8,48665, target_lat=56,73857, target_lon=8,50429, complete_distance=1087,0, **complete_time=389,8**, native=true

**Test case C:**
_Default:_
Route <route>: **routing_time=171,2**, vehicle=car, base=false, start_lat=56,80396, start_lon=9,02131, target_lat=56,80021, target_lon=9,02578, complete_distance=529,1, **complete_time=91,4**, native=true

_With penalties:_
Route <route>: **routing_time=371,2**, vehicle=car, base=false, start_lat=56,80396, start_lon=9,02131, target_lat=56,80021, target_lon=9,02578, complete_distance=529,1, **complete_time=291,4**, native=true

**Comment by Zero3** [comment]
@xmd5a2 I am having a difficult time figuring out why you are closing this issue. Did you fix it? If so, great. But I have a feeling that your comment above is a way of saying that you are not able to reproduce the issue on your end. If so, I would appreciate if you did not just close the issue, since it gives the wrong impression that the problem was solved.

I just tested again again again, and I still see this issue. Here are two fresh screenshots of test case A to document it:

![osmand-issue-16384](https://user-images.githubusercontent.com/82504/156054282-52b92bd4-9378-4802-9592-800ce576e675.png)

**Comment by Zero3** [comment]
@vshcherb could you reopen again please? Unfortunately this issue keeps getting closed without a solution. Thanks!

**Comment by Zero3** [comment]
@vshcherb I double checked everything. I am using the latest OsmAnd 4.1.11 from Google Play and the latest `routing.xml` from https://raw.githubusercontent.com/osmandapp/OsmAnd-resources/935d1486f91802c70b12a3c952554a68346a6de5/routing/routing.xml with only the modification described above.

I did however test on another Android device that has not had OsmAnd installed before, and the issue does *not* happen on that device. Even if I use the same `routing.xml`, the same navigation settings, ... I even tried transferring the whole profile from the "broken" device to the "working" device, and the "working" device keeps working. So it seems like OsmAnd has gotten itself stuck in a bad configuration of some kind on the "broken" device. What can I do to track down the cause?

**Comment by Zero3** [comment]
@vshcherb I did some more testing with the two devices, and I believe I found the problem!

The "broken" device had live map updates enabled. But the date of the "standard" map was from before https://github.com/osmandapp/OsmAnd/issues/12854 was completed. I tried manually updating the "standard" map, and now the penalties seem to work!

So apparently the change made in https://github.com/osmandapp/OsmAnd/issues/12854 requries everyone with live updates to manually update their "standard" maps? I asked about this previously in https://github.com/osmandapp/OsmAnd/issues/12854#issuecomment-994848285, and from what I understood, users should not need to do anything manually. So this seems like a bug.

**Comment by vshcherb** [comment]
Yes it requires, good that problem is found now

**Comment by Zero3** [comment]
@vshcherb so do you want to reopen this issue, or create a new one about fixing the behaviour of live updates?

**Comment by vshcherb** [comment]
It's not a problem of live updates because they couldn't update it retrospectively. So new maps won't have this problem after you updated everything all basemaps to 1st of March at least
