### ISSUE TITLE
Incorrect link to the osm object

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#13686]
### Description
Incorrect link to the osm object, in this case it is a multipolygon (relation), and the link leads to a node.
Correct link https://www.openstreetmap.org/relation/9436211

![Screenshot_2022-02-04-01-40-19-991_net.osmand.plus.jpg](https://user-images.githubusercontent.com/12549744/152441451-3816d829-6f3c-4d9c-b746-a1136b8c7642.jpg)

### Your Environment
OsmAnd Version: OsmAnd~ 4.1.0#33517m, дата выпуска: 2022-02-03
Android version:11 
Device model: poco x3 pro

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-tools/blob/master/java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/IndexVectorMapCreator.java#L142
