### ISSUE TITLE
Info box increasing/decreasing over/below 100 km/h

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#1369]
Hi Victor (@vshcherb),

- Please copy the two screen shots attached below to a common folder on your local hard disk drive.
- Open one of these two screen shots with a picture viewer.
- Toggle between the two pictures using up and down keys while watching the info box* at the top right. You can see it increasing/decreasing.

The reason is that the default width is too small for 3 digits + km/h.

Found with release 2.1.1.

*With info box I mean the labels that display information like remaining kilometers, ETA, ...
![screenshot_2015-06-19-20-55-29](https://cloud.githubusercontent.com/assets/6921696/8266688/aa914094-173c-11e5-870b-0ed0cbdc6e12.png)
![screenshot_2015-06-19-21-00-21](https://cloud.githubusercontent.com/assets/6921696/8266689/aa94c17e-173c-11e5-8ba4-99b06e6f0059.png)

**Comment by vshcherb** [comment]
I don't really think that's an issue.

**Comment by Norbert80** [comment]
@vshcherb That's a nice2have. ;-)

**Comment by vshcherb** [comment]
To be honest, it is not nice to have, I would better close the issue to avoid confusion. In previous issue tracker we used to have label 'we don't plan to do any action'.

**Comment by Norbert80** [comment]
@vshcherb in my opinion the boxes should be increased a little bit, so that they don't expand over 100 km/h. Speeds over 100 km/h are a normal use case of OsmAnd...
