### ISSUE TITLE
track list, erroneous distance/time (when not visible)

### ISSUE THREAD

**Issue by oluc** [osmandapp/OsmAnd#13696]
### Description
Some tracks have erroeous distance/time in the track list.
This happens only when the track is not visible. 
When the track is visible, the data is right.

- distance is set to 0 (zero)
- elapsed time is set to random number
(looks like uninitialised variable ?)

See screenshots

this happens to a few tracks, not all

after editing a track (ex: edit the description + save), then the issue disappears (the distance/time is right)

### How to reproduce?
this happens to a few tracks, not all.

### Your Environment
OsmAnd Version: 4.1.11
Android/iOS version: 8
Device model:

**Comment by oluc** [comment]
3 tracks visible, all data is correct
![Screenshot_20220205-160752_OsmAnd~](https://user-images.githubusercontent.com/439264/152680145-5f475480-0f69-4e6e-8fd8-554c28da5471.jpg)

when set unvisible,
1. first one has null/zero values
2. second has garbage time (but correct distance)
3. third one is correct
![Screenshot_20220205-160806_OsmAnd~](https://user-images.githubusercontent.com/439264/152680147-2b43a340-c6f3-411d-bd13-0a20ce3a398f.jpg)

**Comment by Zirochkabila** [comment]
Doesn't reproduce the bug with local tracks.
Please send us the tracks with which you were able to reproduce the bug.
