### ISSUE TITLE
Viewport Does Not Pan to Selected GPS Track when in Lanscape Mode

### ISSUE THREAD

**Issue by osmgit** [osmandapp/OsmAnd#13692]
### Description
When my phone is in landscape mode the viewport does not pan to the location of the selected track.

### How to reproduce?
Hamburger Menu > My Places > Tracks > Click on any recorded track (when phone is in landscape mode)

View port stays at the current location rather than panning to the selected track.

### Your Environment
OsmAnd Version: 4.1.11
Android/iOS version: Android 11
Device model: Samsung Galaxy S5

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by vshcherb** [comment]
Not repdocible any more
