### ISSUE TITLE
Pedestrian navigation calculate routes using station crossings with a destination on the platform

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#13704]
### Description
Pedestrian navigation calculate routes using station crossings with a destination on the platform

### How to reproduce?
Route: 

<table style="width:100%">
  <tr>
    <th>50.44548, 30.51507 > 50.44390, 30.51234</th>
    <th>50.45206, 30.50861 > 50.44390, 30.51234</th>
  </tr>
  <tr>
    <th><img src="https://user-images.githubusercontent.com/9365308/152794313-f6c5dae3-0834-46da-b1aa-818bed4f1a14.jpg"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/9365308/152794508-c5664f90-4989-4925-9ece-97bf294b7ffe.png"  width="300" height="auto"/> </th>
  </tr>
</table> 

### Your Environment
OsmAnd Version: 4.1
Android: 11, iOS 15.3
Device model: Nokia 5.3, iPhone XS Max

**Maps used (online or offline):**   
Kyiv, Ukraine

**Comment by vshcherb** [comment]
Point depends where navigation will be built, so unfortunately it doesn't detect it correctly sometimes but not clear how it could be fixed.  Please change the point close to the final road

![Screen Shot 2022-02-07 at 19 41 30](https://user-images.githubusercontent.com/1042025/152851315-333af0ef-3707-41dd-9716-83423bfea265.png)
![Screen Shot 2022-02-07 at 19 42 25](https://user-images.githubusercontent.com/1042025/152851318-5a22af89-8482-4bd5-a565-0efd41fba1a8.png)
