### ISSUE TITLE
Route ignores middle destinations when using ORS Routing

### ISSUE THREAD

**Issue by albertodiazsaez** [osmandapp/OsmAnd#13705]
### Description

When using ORS (I tried Car and Bike vehicles), the route goes from the begining pont to the destination, ignoring any middle point that is marked on the way.

### How to reproduce?

Use ORS as a Online Router, mark a Start point, and End point and any number of middle points (even with 1). The route will go to the destination without passing through the middle points.

### Your Environment
OsmAnd Version: 4.1.11
Android/iOS version: Android 11 (Lineage OS)
Device model: Xiaomi MI A2
<table style="width:100%">
  <tr>
    <th>With ORS</th>
    <th>With ORSM</th>
    <th>Offline Routing</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/40151953/152823720-b841d512-ba3d-4ee1-9676-5f07824e6aeb.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/40151953/152823820-65f3ca80-dc0d-4a1d-8ea4-0dd5b6dda84a.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/40151953/152823858-2d314e93-f165-463f-8565-058fad378dd7.png"  width="300" height="auto"/> </td>
  </tr>
</table>   

(I also realized taking the screenshots that in ORSM, the middle point ETA and distance is not showing, I don't know if this functionality only works in offline (and would do for a new feature) or if it's a bug and should be reported as one).

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/pull/12573/files
[joker234](https://github.com/joker234) in case you know what's the issue please help

**Comment by nazar-kutz** [comment]
Can't reproduce described problem. If you can still reproduce it, please, let us know.
Fixed another problem with ORS navigation: https://github.com/osmandapp/OsmAnd/pull/17888
