### ISSUE TITLE
Loss of waypoints when adding a track to another track

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#13700]
When you add track 2 with waypoints to another track 1 with waypoints, track 1 will have its waypoints removed and only track 2's waypoints will appear.

### How to reproduce?
1. Create track 1 with waypoint named 1, also create track 2 with waypoint 2.
2. Select track 2 and tap the edit button.
3. Then tap options and select add to a track
4. Select track 1 from the list.

Track 1 will then be automatically saved, causing the original waypoint 1 to disappear and track 1 to contain only waypoint 2.

Video in telegram chat: https://t.me/ruosmand/88007

OsmAnd Version: OsmAnd~ 4.1.0#33529m, дата выпуска: 2022-02-06
Android version: 11
Device model: poco x3 pro

**Comment by vshcherb** [comment]
Probably fixed needs to be tested

**Comment by Nine-Tailed** [comment]
The bug is still not fixed.
OsmAnd~ 4.2.0#34108m, Дата выпуска: 2022-05-30
