### ISSUE TITLE
With enabled Avoid unpaved roads builds a detour route

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#13706]
### Description
![image](https://user-images.githubusercontent.com/80623554/152829918-fb367b55-8be5-4b4c-b190-30cbb8f8344e.png)
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=49.4454%2C11.8362%3B49.4437%2C11.8661

### How to reproduce?
 In the Navigation settings enable No unpaved roads.
Start point:
49.44717° N, 11.83141° E
Finish point:

### Your Environment
OsmAnd Version: 4.1.11
Android/iOS version: Android 9
Device model: Sony Experience XZ 1

**Maps used (online or offline):**   offline, updated 1 Jan 2022
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by xmd5a2** [comment]
OsmAnd tried to avoid this way with `surface=fine_gravel` https://www.openstreetmap.org/way/315532332
In reality this is asphalt https://www.mapillary.com/app/?lat=49.442862&lng=11.852544&z=17&pKey=1144634752666380&focus=photo&x=0.48671426773942117&y=0.6518593512168402&zoom=0

![Screenshot_2022-02-09_10-48-41](https://user-images.githubusercontent.com/5829014/153145186-5c76e8ce-48b0-4d6a-8429-6b5e034f6a5c.png)
I just fixed this in OSM
