### ISSUE TITLE
Exit button

### ISSUE THREAD

**Issue by razor74** [osmandapp/Osmand#1371]
Hi.
Where is exit buton from last version 2.1.1? I dont want to leave the app( or any other unecessary app) in memory/cache. It was already reported as a power intensive app (by a power management utility from my phone) in the background after i close ( aparently) the app with back button from the phone...
I

**Comment by jkufner** [comment]
If it does something it should not, you should file a bug report. Exit
button is workaround, not a solution.

**Comment by vshcherb** [comment]
It was deleted as it did not follow guidelines and did not work properly, I think the discussion somewhere captured in one of the commit.

**Comment by asd-and-Rizzo** [comment]
I liked exit. Downgraded to 1.9.x where Exit is not so deep in menu.

**Comment by asd-and-Rizzo** [comment]
I bought official app on gplay pre 2 era. Will donate few more if 2.x will become stable on my samsung galaxy s5 and be ensured that really do not need exit button.

**Comment by vshcherb** [comment]
We explained in many places, main points:
- Exit doesn't follow guidelines
- From Android 4.0 it is very easy to kill application with swipe
- We figured out all resources and unexpected service leaks when application is killed with swipe
- GPX notification for example was improved to support some scenarios
