### ISSUE TITLE
Routing map made with OsmandMapCreator routes on Android, but not on IOS

### ISSUE THREAD

**Issue by rickryen** [osmandapp/OsmAnd#13716]
### Description
Custom routing map made with OsmandMapCreator routes on Android, but not on IOS. Tried this on two different iPhones and version 12 and 13 of IOS, running the latest version of Osmand 4.1.11.

Maps created with OsmAndMapCreator V3.0 work fine on Android phones, calculating a route as expected and following a simulated route. The same .obf files fail to calculate a route on IOS, and it just sits there doing nothing when a starting point and destination are entered. A downloaded highway map routes as expected on IOS, just not the custom maps created with OsmandMapCreator.

### How to reproduce?

Try calculating a route on IOS using a map created with OsmandMapCreator. I've provided a simplified test case .obj below.

### Your Environment
OsmAnd Version: 4.1.11 
Android/iOS version: Android 8.0 (not a problem)  / iPhone 12.5.5 and 13
Device model: Android (LGV20)   (works find as do most others)  . iPhone 5S  and another newer model (both fail to calculate routes)
OsmMapCreator V3.0 (build map index, Build Routing index, build POI index, checked)

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

No route is calculated on IOS using this simplified test case file...
  [IOS_route_testcase.obf ](https://www.dropbox.com/s/sdd3f6gp28e1zux/Ios_route_testcase.obf?dl=0)

...which was created using OsmandMapCreator V3.0 from this JOSM created osm source...
 [ Ios_Route_testcase.osm](https://www.dropbox.com/s/crq7irhvgh1he2s/IOS_Route_Testcase.osm?dl=0)

**Comment by rickryen** [comment]
Reproducing...

 Search for Wonton's Chinese Restaurant poi, and you can "directions from" at this spot, and then set destination on map to one of the ATV trails nearby. It is in State of New Hampshire, USA. 43.6132421, -71.039207

**Comment by rickryen** [comment]
I didn,t the button label and closed by mistake. Its still an open issue.

**Comment by vshcherb** [comment]
Duplicate https://github.com/osmandapp/OsmAnd-iOS/issues/1766
