### ISSUE TITLE
Displaying different tracktype in OSMAnd

### ISSUE THREAD

**Issue by mutipg** [osmandapp/OsmAnd#13711]
### Description
In the past, OSMAnd showed tracks with different track types in different ways. Recently, regardless of tracktype, all tracks are displayed in the same way. In the attachments a view of the same area in OSMAnd and osmcarto.

### How to reproduce?
Open the map in OSMAnd with visible tracks by 'OsmAnd' or tourist style. 

### Your Environment
OsmAnd Version: OsmAnd+ 4.1.11, date 2021-12-15
Android: 11
Device model: realme 8 Pro

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
Offline maps dated on 2022-02-01 + live update on 2022-02-07

![tracktype_grade_OSMAnd](https://user-images.githubusercontent.com/10333015/152857679-51030a68-9d19-4d44-9f24-6ae976b00dd3.jpg)
![tracktype_grade_osmcarto](https://user-images.githubusercontent.com/10333015/152857682-6f9c3dc2-51f6-4041-a741-57bd588ff672.png)

**Comment by xmd5a2** [comment]
Map generation was broken and is fixed now. New maps will be ok.

**Comment by CRCulver** [comment]
Will the February 1, 2022 maps generated with errors this month be regenerated correctly, or will we have to wait for the March 1, 2022 maps for correct rendering?

**Comment by vshcherb** [comment]
We will regenerate all maps and as of 12 February you will be able download all maps again.
