### ISSUE TITLE
tap back button  on quick action menue locks screen menues

### ISSUE THREAD

**Issue by C6competition** [osmandapp/OsmAnd#13717]
Opening the quick action menue with the screen button, brings the menue on the screen as well as 
the ocher map marker icon. 
If now the back button of the phone gets tapped, the app (OsMand) goes into the background. 
Reopening the app again, with tap on it's icon, the ocher map marker is still on the screen and not to delete. 
All screen menues are not more available! 
The only way to get out of this situation is to kill the app and restart it again. 

### Your Environment
OsmAnd Version: 4.1.11
Android version: 10
Device model: Blackview 9900E

**Comment by pl71** [comment]
Same here.
Pressing the Back button in Android and re-opening OsmAnd bring no Quick Menu, but only a position marker. 
Quick Menu as well as the main menu are not available.

OsmAnd Version: 4.1.11
Device and Android/iOS version:
Galaxy S8
Android 9

**Comment by Nine-Tailed** [comment]
This bug has already been fixed [here](https://github.com/osmandapp/OsmAnd/issues/13584).
But there is a similar [bug ](https://github.com/osmandapp/OsmAnd/issues/13697)that has not yet been fixed.
