### ISSUE TITLE
no merge_to_left lane nor icon?

### ISSUE THREAD

**Issue by it4workflow** [osmandapp/Osmand#1373]
I use OsmAnd in car mode for QA reasons. It has struck me that turn:lanes:[merge_to_left](http://www.openstreetmap.org/way/326694067) is displayed as straight:
![screenshot_2015-06-20-13-42-26](https://cloud.githubusercontent.com/assets/8296940/8271265/6554f7fa-180e-11e5-8740-cbd40208b593.png)

Was this a conscious decision? Is it a bug? Or is this issue just not implemented yet?

**Comment by jf-simon** [comment]
Looks like https://github.com/osmandapp/Osmand/issues/1198

**Comment by vshcherb** [comment]
Yes, we have pull-request also about it. It is in a backlog and it was implemented keeping in mind that is a first version.

The issue is mentioned  in #1198 .
