### ISSUE TITLE
"Hiking symbol overlay" with "Color by OSMC hiking symbol" shows no route color

### ISSUE THREAD

**Issue by econo202** [osmandapp/OsmAnd#13730]
### Description

When choosing "Hiking symbol overlay" and selecting "Color by OSMC hiking symbol" the route displayed on the map has a generic blue color, not the route color.

Might be somehow related to #11833.

### How to reproduce?

1. Open OsmAnd
2. Choose "Hiking symbol overlay" and select "Color by OSMC hiking symbol"
3. The routes are rendered in generic blue color

### Your Environment
OsmAnd Version: nightly OsmAnd-master-nb-2022-02-08
Android/iOS version: Android 10

**Maps used (online or offline):**   

- offine maps of Poland

**Comment by dmpr0** [comment]
Hi, @econo202!
We have an issue with February maps, some tags are missed in files. Currently, we replaced broken maps from the January backup and starts the new generation process, updated February maps will be available after 15 February. 
Currently please delete and redownload Poland maps.

**Comment by vshcherb** [comment]
Should be soon updated
