### ISSUE TITLE
Render `highway=construction` roads diffrently

### ISSUE THREAD

**Issue by Dimitar5555** [osmandapp/OsmAnd#13733]
### Description
Currently roads tagged with `highway=construction + construction=something` are rendered as `highway=something`, which can be confusing. The motorway and the roundabout in the picture below are under construction and should be rendered diffrently.
![image](https://user-images.githubusercontent.com/19364673/153377010-be816d05-65d4-4993-bc40-517343e1bb37.png)

### How to reproduce?
1. Go to https://www.openstreetmap.org/#map=16/42.7823/23.2431 in OsmAnd

### Your Environment
OsmAnd Version: 4.0.9
Android/iOS version: Android 10

**Comment by pebogufi** [comment]
Can not confirm, see example 
Isfahanallee
https://www.openstreetmap.org/?mlat=48.0134561&mlon=7.8529738#map=19/48.01346/7.85297

https://www.openstreetmap.org/way/246718707/history
Which is tagged as red/white

highway construction
construction primary

**Comment by Dimitar5555** [comment]
Indeed, your example renders fine on my phone. Can you open the location that I linked and confirm whether you see it the same way that it's shown on the screenshot?

**Comment by Lee-Carre** [comment]
Another example (though it's due to be completed and open this month (2022-02)), which is rendered distinctly: [Moneypenny Lane](//www.openstreetmap.org/way/912950093).

**Comment by pebogufi** [comment]
currently downloaded:
![Screenshot_20220210-164854_OsmAnd~~01](https://user-images.githubusercontent.com/18628183/153444276-95c7d958-f789-4a42-ab7d-3fd59744a415.jpg)

**Comment by Dimitar5555** [comment]
The issue fixed itself after redownloading the map for Bulgaria.
