### ISSUE TITLE
Language (dialect) misdetection (UI, TTS voice)

### ISSUE THREAD

**Issue by Lee-Carre** [osmandapp/OsmAnd#13737]
### Description
I'm a fan of automagic, but that requires correct detection of conditions.

Language auto-selection seems to misdetect en-gb as en-us.

This seems rooted in the auto-detection for UI language, which cascades to TTS language.

My configured (ordered-)list of language preferences are
1. English (Jersey)
2. English (United Kingdom)
3. English (United States)

The hint text supplied when configuring system language preference states:

    […] The language at the top of the list will be used by default.
    If an app doesn't support that language, the next language in the list will be used instead.

### How to reproduce?
0. Ensure that OsmAnd's global configuration for language is set to `System (Device language)`
1. Ensure that a TTS engine is installed & configured, which includes English voices for each of American & British dialects
2. Ensure that, within OsmAnd, voice prompts are enabled for navigation, using TTS with language set to `Use system language`
3. Set Android's system (preferred, default) language to `English (United Kingdom)`
4. Launch OsmAnd
5. Simulate navigation with voice prompts enabled
6. Notice that the voice used is en-us (not en-gb)
7. Notice, too, that anywhere that language auto-selection is configured (UI language, TTS language), it indicates that en(-us) will be used (not en-gb)

### Your Environment
OsmAnd Version: v4.0.9 (though has affected v3 through v4)
Android/iOS version: Android v10
Device model: SM-A405FN

**Maps used (online or offline):**   
Problem isn't map-related. However, I use offline vector maps (kept updated).

**Comment by vshcherb** [comment]
Probably fixed same as https://github.com/osmandapp/OsmAnd/issues/13304. You need to configure dialect in TTS and choose French, so voice will be selected how it was configured.

**Comment by Lee-Carre** [comment]
> Probably fixed same as #13304.

Having read that ticket, it seems unrelated. All relevant languages are installed.

> You need to configure dialect in TTS

While that is indeed a workaround, it merely avoids this bug, instead of addressing it.

Manual selection of language does override auto-detection. The point of this thicket is that auto-detection isn't selecting the right language by itself (despite having everything needed to do so).

> choose French

Why would I select French when I want (British) English?

> voice will be selected how it was configured.

But that's the point; it's *not* being selected based on my configuration.

---

I'm wondering if the solution might be some simple mismatching of strings. Such as `en-uk` versus `en-gb`. Or what is actually `en-us` being treated as `en` (generic).

I did try searching the code, but it's beyond me.

**Comment by vshcherb** [comment]
The dialect is not specified by OsmAnd, it's specified by TTS engine. So if I understand correctly if the written language the same, it needs to be changed in TTS engine similar how you change the Male vs Female, Tone, Speed etc...

**Comment by Lee-Carre** [comment]
> The dialect is not specified by OsmAnd, it's specified by TTS engine.

That doesn't match any of my observations.

* The TTS engine is set to use whatever language it's told to by apps. If none is specified then it'll use use system language.
* it's possible to change language / dialect from within OsmAnd, which causes the voice to change without any alteration to TTS
* In the development plugin, different voices can be selected without changing any TTS config
* I can manually override the auto-selection in OA, which forces a particular voice
* if I were purely a TTS concern, then why are there multiple dialects for the same language, within OA, for driving TTS? Especially when, as far as I can determine, they speak the same sentences, all that changes is dialect / accent / pronunciation, by triggering a different TTS voice
* if language were hard-configured in TTS, then tickets asking for multi-lingual sentences (i.e. voice switching) from OA make no sense because that would be impossible, yet the responses in said tickets indicate otherwise (I'll find the ticket ID shortly)

I suggest doing some testing.

Besides, regardless of TTS, UI language selection does us being en-us, even though it's told to use the system language, which is set to British. Hence my suspicion that this is then cascading down into TTS dialect mis-selection.

**Comment by Lee-Carre** [comment]
Having done a little testing of my own, apparently UI language and TTS voice selection are independent.

**Comment by vshcherb** [comment]
I've just tested myself on 'nl-tts' (Dutch - Belgium / Dutch voice). Important you need to completely restart application cause it caches previous voice.
- Tested with selected voice Text to Speech in System settings - works as expected!
- Tested with "System-language" doesn't work as expected and doesn't respect region of System language.

I can't be sure but it looks system issue cause system language / region is not respected correctly by TTS-engine where only  the language code is specified so specifics should be handled by TTS-engine

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/src/net/osmand/plus/voice/LocaleBuilder.java#L76 Probably I found the issue. This looks overcomplication and hard code for pt / nl disrespecting general logic which could as is:
**Developer note**
1. If user manually selected file like pt-br, Language-Region - TTS should be always initialed as Language-Region if available, if not then as language
2. Always take fully specified default locale from System settings, i.e. nl-nl or nl-be depends what's specified in System settings
3. If user manually selected only language code and it's different than default locale in System Settings and not present, don't initialize region at all for TTS
Extra comments: Don't use user location cause it's not important

**Comment by Lee-Carre** [comment]
Thankyou for researching.

If *some* misbehaviours are due to the TTS engine itself (or the OS), then fair enough; clearly those aspects are problems further up the software hierarchy, and I **wouldn't** expect OA to compensate for them.

However, given the observed & described (sometimes inconsistent & contradictory) results when using OA, ensuring that OA is doing the correct thing (detecting system language, instructing TTS engine) is a necessary first step (lest bug reports to the TTS engine be dismissed as ‘*your app* is misbehaving’).

I also now recall experiencing the same with different TTS engines (using the same config of OA as described above, and each engine having all the necessary languages & dialects). So, either it's OA or the OS. Seems unlikely that exactly the same bug is present in a wide variety of engines (including popular proprietary ones I tried: Google & Samsung).

An interesting test would be to remove (from the TTS engine) the en-us dialect. However, that (annoyingly) wasn't permitted when I tried it in some.

I'll see if I can do some testing with other TTS-driving software (e.g. Organic Maps), for comparison.

> [\[…\]/voice/LocaleBuilder.java § line #76](/osmandapp/OsmAnd/blob/master/OsmAnd/src/net/osmand/plus/voice/LocaleBuilder.java#L76) Probably I found the issue. This looks overcomplication and hard code for pt / nl disrespecting general logic

I'm no programmer, but that does indeed look like a mess of hackey kludges. Special-cases instead of robust general-case handling.

> Don't use user location cause it's not important

Absolutely. The two are distinct. Location doesn't imply language. The habit of websites using flags to represent / indicate language is a bad habit.

The obvious case is when travelling to foreign lands. If I, as a Brit, take my car to the Nurburgring, I'll still want OA to use English, not German. Though, English spoken with a German accent might be amusing.

There are enough ambiguous cases for natives, too
* in Québec, should it default to fr-ca or en-ca?
* in USA, a significant number of users will prefer Spanish or even Mexican
* at borders, accurately detecting which side the user is on, becomes important
* near borders, many people are often multi-lingual anyway (and only they each know their preferred language)
* several nations have multiple official languages
* nations can, over time, change which language is commonly used

Keeping language orthogonal from location keeps everything simpler. Adhering to configured user preferences keeps things simpler.

**Comment by vshcherb** [comment]
Using System Settings
- Text To Speech (Use system language)
- Main Locale (NL - Belgium)

- Observed: OsmAnd Selected TTS - nl-nl 
- Expected:OsmAnd Selected TTS - nl-be
-------------------
<img src="https://user-images.githubusercontent.com/1042025/158382666-3188f673-669c-45c0-951f-625f61908b64.jpg" width="20%" />
