### ISSUE TITLE
Bug when changing waypoint position

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#13742]
### Description
When attempting to reposition a waypoint, it will either be incorrectly positioned or disappear from the screen altogether.

### How to reproduce?
1. Create a new waypoint
2. Turn on the orientation of the map in the direction of travel or by compass (the bug is in these two modes)
3. It is desirable that you move and the map changes as you move.
4. Select the previously created waypoint and from the context menu select "Change marker position"

after that, the waypoint either moves unpredictably ([video 1](https://t.me/ruosmand/87990)) or disappears from the screen ([video 2](https://t.me/ruosmand/88369))

### Your Environment
OsmAnd Version: OsmAnd~ 4.1.0#33572m, дата выпуска: 2022-02-10
Android version: 11
Device model: poco x3 pro

**Comment by Zirochkabila** [comment]
In the release (4.1.11) version and regular nightly (4.2.0#34091m) everything works. 
In the OpenGL version (4.2.0#13524mqta) does not work, but if you restart the application the point is displayed moved

**Comment by ivanPyrohivskyi** [comment]
Fixed in r4.2 https://github.com/osmandapp/OsmAnd/commit/8ae7a6c9102db075f7bce7ff32f1b1c32f60aa85
Will merge to master in next week.
