### ISSUE TITLE
missing timestamp on map marker gpx export

### ISSUE THREAD

**Issue by flo-schn** [osmandapp/OsmAnd#13751]
### Description

When exporting Map Markers to an gpx file via 'Save as track file', there are not timestamps. time stamps would be however, very useful. thanks for the good work and pls let me know if i can provide anything further to help fixing the bug asap :)

### Your Environment
OsmAnd Version: 4.1.11
Android/iOS version: Android 12
Device model: Google Pixel 3XL

**Comment by vmicho** [comment]
I dunno if timestamp is saved with a marker internally, but I confirm that it would be a big improvement if there is also a timestamp associated with each marker. This helps to locate some events in time, like putting map notes and photos together.

**Comment by 098714** [comment]
![Screenshot_20220706-202527](https://user-images.githubusercontent.com/79014934/177618199-844065a9-19cf-49a5-af4e-ff57a028db48.png)

When in the osmand app, in map markers a timestamp is visible, see attached screenshot. However when exporting the markers to a gpx file, the info simply isn't included and like you say, it would be very helpful to have that info. let me know if I can provide any further info and help in any way!

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14201mqta, Released: 2023-02-25

<details><summary>Done</summary>
<img width="800" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/221358868-39ebf530-06b9-4d45-8b13-1216e1749464.png">
</details>
