### ISSUE TITLE
Still heavy fast route recalculation problems (loops) with release 2.1.1

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#1375]
Using OsmAnd 2.1.1 second release I noticed the following bug:

Parameters to reproduce

- Make sure maps "Germany_baden-wuerttemberg_europe.obf" and "Germany_bayern_europe_.obf" are installed

- Start point approximately: 47.682812, 9.759014

- Destination: 47.55081, 9.72054

- Start navigation in car mode

- Against automated directions turn left (not right) at:  47.683419, 9.757061

Note: This is a good alternative "economic" route. Other navigation systems - also if in "fastest" - mode - recalculate without problem to accept these alternative route after turning left.

Result with OsmAnd:
OsmAnd was heavily busy with recalculating many times. For the half way it wanted to route me back to the motorway. Below you see a screen shot with the "crazy loop" OsmAnd wanted me to drive. You can see that OsmAnd suggests to drive 30 km although the correct remaining route at that location would be ~14 km!

(Later - but much too late - OsmAnd has recalculated correctly.)

It is not acceptable to suggest a route with more than twice the length. Since these problems have been introduced with "fast recalculation" algorithm I call it a regression.

![screenshot_2015-06-21-15-58-13](https://cloud.githubusercontent.com/assets/6921696/8273231/eb29790a-1863-11e5-9724-be9126a6c449.png)

**Comment by Norbert80** [comment]
@vshcherb I just want to remember about this issue. It should be handled with high priority.

**Comment by vshcherb** [comment]
Once release is out the priority is not on the bugs. I will check that route, the feature we've made should help in your case and act exactly as before 2.0 (after 3 unsuccessful recalculations, full recalculation is scheduled)

**Comment by Norbert80** [comment]
I don't remember how many times it has tried to recalculate "fast". But in South Germany OsmAnd is in general extremely slow calculating.

So also 3 times could be enough to nearly reach the target until OsmAnd has calculated properly.

So what we see here is that "tricks" like this are introducing (new) problems, not solving problems.

IMHO the solution is CH graphs embedded in the map files. This allows correct "full" recalculations in short times. How does the road map look like at this point?

**Comment by Norbert80** [comment]
@vshcherb I don't remember how many times it has tried to recalculate "fast". But in South Germany OsmAnd is in general extremely slow calculating.

So also 3 times could be enough to nearly reach the target until OsmAnd has calculated properly.

So what we see here is that "tricks" like this are introducing (new) problems, not solving problems.

IMHO the solution is CH graphs embedded in the map files. This allows correct "full" recalculations in short times. How does the road map look like at this point?

**Comment by vshcherb** [comment]
>> How does the road map look like at this point?
Are you asking for curiosity or you are going to write code?

**Comment by Norbert80** [comment]
> Are you asking for curiosity or you are going to write code?

I just have fished. :-))
https://github.com/graphhopper/graphhopper/tree/master/android

If you have questions... :-))
https://github.com/graphhopper/graphhopper/blob/master/docs/android/index.md

Feel free to adopt it. ;-)

> How does the road map look like at this point?

What exactly do you mean?

**Comment by vshcherb** [comment]
I just answered a part of your question. Adoption is beyond 15 minutes investigation, but it doesn't really matter for now. I think I will dedicate some time later, but it is 1 month term, which I can't do right now.
For now I feel I need to stop doing lots activities on Github issues, because the productivity goes really down. I'm planning to do Github reviews 2 times a week and respond to emails. Definitely it will not be enough for live conversations, but we are not in release mode and there is no critical outstanding issue as I see (of course, if there is no critical issues, then major issue become critical), so that means no need to do a hotfix release (instead of normal).

**Comment by Norbert80** [comment]
@vshcherb you don't consider fixing issues as "productive"? I don't know what to say...

Regarding GraphHopper... it still seems to have major limitations:

> - for car - it is not simply possible to ignore highways
> - generally it is not possible to route over more data files at once

This is from:
forum.locusmap.eu/index.php?topic=4036.75

It is available for Locus.

**Comment by sonora** [comment]
No recent reports, I think this is deprecated.

**Comment by Norbert80** [comment]
@sonora I can confirm that this problem is resolved in OsmAnd+ 2.4.7.
