### ISSUE TITLE
Navigation by track is broken after attach to roads

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#13759]
[Sentieri Montà e Baldissero d'Alba.gpx.zip](https://github.com/osmandapp/OsmAnd/files/8073232/Sentieri.Monta.e.Baldissero.d.Alba.gpx.zip)

1. User experience quite a lot of unnecessary turns because track is not Attached to roads:
<img width="30%" height="30%" src="https://user-images.githubusercontent.com/1042025/154116509-ecb84cea-1a2e-428b-80e1-e327e4a23866.jpg" />

2. Attach to roads works nearly good
<img width="30%" height="30%" src="https://user-images.githubusercontent.com/1042025/154116336-4bd2da6c-24fe-4721-87cb-e95d5434bec7.jpg" />

3. Broken result after track is select for navigation  - route is completely different than track
<img width="30%" height="30%" src="https://user-images.githubusercontent.com/1042025/154116222-29cac2bf-947d-4e30-922d-c0998b809b28.jpg" />
<img width="30%" height="30%" src="https://user-images.githubusercontent.com/1042025/154116249-99003b19-c59b-4724-a5b0-b3778c57ce61.jpg" />

**Comment by Davidlymn** [comment]
I think this is caused when the track does not go "under" the road. It appears that on some tiles the track is drawn on a layer and the road is on another layer above. In this case the route you draw will cross the road as you expect. If the track is on the same layer as the road then when you try to draw the route , the tool sees a break and so diverts along the road until it finds a "crossing and then comes back to the point you placed. There is no simple solution. Open the options menu, select next segment and straight line, go back to map and draw a line across the road, go back to options and reverse. An onscreen options menu that automatically allows segment change will help.

**Comment by Samuele75** [comment]
hello, when I create a path I draw points and automatically the program connects them by creating segments that do not need to be modified. Until you use the program as a navigator you have no indication of all those unnecessary turns. Is it possible in this case not to have vocal support only on this occasion?

**Comment by dmpr0** [comment]
# Review
- [ ]  After "Attach to the Roads" using [Sentieri Montà e Baldissero d'Alba.gpx](https://github.com/osmandapp/OsmAnd/files/8073232/Sentieri.Monta.e.Baldissero.d.Alba.gpx.zip), show error "Calculated route is empty".
