### ISSUE TITLE
Incorrect navigation instructions in navigation by track

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#13752]
### Description
Make track via the Plan route tool and start navigation by track. As result navigation instructions were incorrect.

Normal navigation 
<table style="width:100%">
  <tr>
    <th><img src="https://user-images.githubusercontent.com/80623554/153871838-71c7e4ee-8d8a-4eaa-b5f3-566f9e914f5f.png"  width="auto" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/80623554/153871902-9f06c412-944b-4f09-a1af-469bf2cad6f5.png"  width="auto" height="auto"/> </th>
  </tr>
</table> 

Navigation by track
<table style="width:100%">
  <tr>
    <th><img src="https://user-images.githubusercontent.com/80623554/153872890-18014b79-918e-420d-ac79-7c59f7ca7e6a.png"  width="auto" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/80623554/153872057-d1b76e0c-6b49-4129-86bb-66acccc1b613.png"  width="auto" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/80623554/153872154-efc7d8bb-30f7-4289-9567-1a9247ce1ffc.png"  width="auto" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/80623554/153872250-7664f378-f5b2-4e08-a656-309495942864.png"  width="auto" height="auto"/> </th>
  </tr>
</table> 
[Mon 14 Feb 2022.zip](https://github.com/osmandapp/OsmAnd/files/8061042/Mon.14.Feb.2022.zip)

### How to reproduce?
1. Create a route via Plan route
2. Start navigation by track

### Your Environment
OsmAnd Version: 4.1.11
Android/iOS version: Android 9
Device model: Sony Experia XZ 1

**Maps used (online or offline):**   offline
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

Developer notes:
- Activate button Attach to Roads to such tracks (Navigation + Plan Route)
- To remove points: 1-st approach. If following mode the same for intermediate points, RouteSegmentResult should be combined together and  RouteResultPreparation.prepareTurnResults should be call again to remove "intermediate point" instructions. 2nd approach: remove last point instruction and RouteResultPreparation.recalculateTimeDistance, RouteResultPreparation.calculateTimeSpeed

**Comment by vshcherb** [comment]
The issue is related to intermediate route points and turns. Route result preparation should be called for the whole track, so turns should be combined together before the track is saved with incorrect turn instructions.

**Comment by Gbernardy** [comment]
> The issue is related to intermediate route points and turns. Route result preparation should be called for the whole track, so turns should be combined together before the track is saved with incorrect turn instructions.

Question ...

but once the new 4.2 release is installed, how can the tracks already drawn with the previous versions (<4.2) be "repaired ..."

**Comment by vshcherb** [comment]
They can be "repaired" by attaching tracks to the roads again, actually it could be done with new maps anyway if they improve the situation

**Comment by Gbernardy** [comment]
> They can be "repaired" by attaching tracks to the roads again, actually it could be done with new maps anyway if they improve the situation

but  ...

if I change, with new release, the track already drawn with the previous versions (<4.2) , 
which of the following changes will "fix" the track: 

1 - I move a point on the track
2 - I add a segment 
3 - other ...

**Comment by vshcherb** [comment]
Similar issue - https://github.com/osmandapp/OsmAnd/issues/13031

**Comment by Gbernardy** [comment]
> Similar issue - #13031

Redrawing the tracks ... nooo 😩

To facilitate the repair of tracks already made with Osmand, a track recalculation feature would be needed.  

This functionality already exists in OsmAnd (see attachment). It might work ?

This feature now has the limit of not being able to calculate the track with the types of segments (navigation ...) used to create the path of the track .

![Screenshot_2022-02-21-17-05-58-29_99c04817c0de5652397fc8b56c3b3817](https://user-images.githubusercontent.com/99968793/154990886-d43a6bf2-d7c4-4689-83ce-4f29ae298d40.jpg)

**Comment by scaidermern** [comment]
Track recalculation is a good thing anyways because map data can change.

**Comment by Gbernardy** [comment]
> They can be "repaired" by attaching tracks to the roads again, actually it could be done with new maps anyway if they improve the situation

Could the "reverse route" command work to repair the traces?  

If yes ... then in OsmAnd there is already a feature to recalculate the tracks ... 

it would only be a question of adding it to the attached menu ... to get the recalculation with just one click and not two.

![IMG_20220225_091800](https://user-images.githubusercontent.com/99968793/155681334-5020b454-f8cc-4cf3-8b33-4408ba7a82d1.jpg)
