### ISSUE TITLE
Import track from the Plan route menu does not work

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#13758]
### Description
When I select import track via Plan route the track does not import.

### How to reproduce?
Menu->Plan route->Import track-> Select file with .gpx extension
[video_2022-02-15_18-48-10.zip](https://github.com/osmandapp/OsmAnd/files/8072970/video_2022-02-15_18-48-10.zip)

### Your Environment
OsmAnd Version: OsmAnd+ 4.1.11
Android/iOS version: Android 9
Device model: sony Experia XZ 1

**Comment by vshcherb** [comment]
You can always import track by Open Track with ... OsmAnd via any other application

**Comment by Gbernardy** [comment]
> You can always import track by Open Track with ... OsmAnd via any other application

Yes, I have already succeeded ...

but for many users it is not that easy to obtain ...

**Comment by dmpr0** [comment]
Fixed https://github.com/osmandapp/OsmAnd/issues/14286
Couldn't reproduce it in the latest nightly build.
