### ISSUE TITLE
OsmAnd Online GPS Tracker missing from the PlayStore

### ISSUE THREAD

**Issue by albertodiazsaez** [osmandapp/OsmAnd#13768]
The application has disappeared from the Play Store: https://play.google.com/store/apps/details?id=net.osmand.telegram (Link obtained from the  [OsmAnd page](https://osmand.net/features/tracker), it does not appear on search results either).

It also doesn't show in the [OsmAnd Applications](https://play.google.com/store/apps/dev?id=8483587772816822023) section in the PlayStore.

**Comment by dmpr0** [comment]
Hello!
Google Play review team temporarily removed OsmAnd Online GPS from Google Play. We have already completed the necessary steps and are waiting for the application to return to Google Play after review.

**Comment by vshcherb** [comment]
It should be live again
