### ISSUE TITLE
Navigation screen orientation, add a 4th option

### ISSUE THREAD

**Issue by antivirtel** [osmandapp/Osmand#1376]
I'm often using OsmAnd's navigation function. Unfortunately, it is usually painful, because the orientation of the screen is not followed correctly. I'd like to use the "To the movement" option, but it will look like this, if the destination is in south:
![Navigation screenshot](http://i.imgur.com/6q8lI9O.png)
The "To the compass" type is not fully what I need, and if I just rotate around 180° it will loose the destination from sight.

In most Navigation applications, I can achieve a mixed solution: to the direction of the movement AND keep the destination in the front of me. Like iGo's, or Google Maps' navigation functions.

Can you add this 4th type of orientation? I don't think 3D is needed, but it is kind of 3D, like in other apps.

**Comment by vshcherb** [comment]
There is a special option to keep my location in center. I would be pleased to know how it is configurable in Google Maps, iGO in details, cause didn't see that.

**Comment by vshcherb** [comment]
To be honest your screenshot looks wrong, the route should be positioned to the top of the screen, I presume this is because my location is not found. Once it found it should be ok.
