### ISSUE TITLE
The distance of the track is different in the track overview and edit track

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#13764]
### Description
If create track via Plan route with part of the track making with Bicycle navigation type and part of the track with  Direct - to - point or Straight line the distance of the track in the track overview and in the edit mode will be different.

### How to reproduce?
Make a  new route: part of it with Direct - to - point or Straight line and part with Bicycle navigation type

<table style="width:100%">
  <tr>
    <th><img src="https://user-images.githubusercontent.com/80623554/154268088-e9de23cc-9a85-4104-8e09-04e81f015a68.png"  width="auto" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/80623554/154268208-b1c1cd88-2f3f-4223-9ea3-c4f72a04a137.png"  width="auto" height="auto"/> </th>
  </tr>
</table> 

### Your Environment
OsmAnd Version: OsmAnd+ 4.1.11
Android/iOS version: Android 9
Device model: Sony Experia XZ 1

**Comment by vshcherb** [comment]
Difference is too small could be a rounding error
