### ISSUE TITLE
Display name of item when asking for confirmation to delete

### ISSUE THREAD

**Issue by Gbernardy** [osmandapp/OsmAnd#13769]
# 🚀 feature request

When you ask to delete a track,

the confirmation request message does not specify the name of the track 🤔. 

if I confirm what do I delete? 🤔 Track 1 or 2 or 3 or  ... 
![IMG_20220218_134800](https://user-images.githubusercontent.com/99968793/154686362-d8d8b047-8a48-4e36-b45a-40b810c60ff5.jpg)

Write the name of the track to be deleted in the confirmation message

**Comment by Lee-Carre** [comment]
Suggested title (rename): “Display name of item when asking for confirmation to delete”

[“Delete Track” reads like a request for a feature which already exists. [Microcontent: how to write headlines, page titles, and subject lines \[also file-names\]](//www.nngroup.com/articles/microcontent-how-to-write-headlines-page-titles-and-subject-lines/).]

---

This suggestion makes for good UI/UX design. It would help to avoid users mistakenly deleting the wrong track.

**Comment by Gbernardy** [comment]
> Titolo suggerito (rinominare): "Visualizza il nome dell'elemento quando chiedi conferma per l'eliminazione"
> 
> ["Elimina traccia" si legge come una richiesta per una funzione che esiste già. [Microcontenuto: come scrivere titoli, titoli di pagina e righe dell'oggetto [anche nomi di file]](//www.nngroup.com/articles/microcontent-how-to-write-headlines-page-titles-and-subject-lines/) .]
> 
> Questo suggerimento consente una buona progettazione dell'interfaccia utente/UX. Aiuterebbe a evitare che gli utenti eliminino erroneamente la traccia sbagliata.

👍

**Comment by Gbernardy** [comment]
👍

**Comment by EugeneZmeuk** [comment]
https://osmand.net/docs/user/personal/tracks#actions
