### ISSUE TITLE
Hide POI type for POI with official_name

### ISSUE THREAD

**Issue by gtrus21** [osmandapp/OsmAnd#13767]
Предлагаю в результатах поиска скрывать тип POI (в данном случае "ресторан"), если в тегах POI имеется official_name, т.к. данное поле всегда включает в себя тип организации ("Ресторан "Нацкэ") и дублирует тип
![IMG_20220217_111503](https://user-images.githubusercontent.com/69676792/154621454-6ff255f1-f9c4-429a-bf7b-27cd6f6a0b8a.jpg)

**Comment by scaidermern** [comment]
I think it is rather uncommon that "official_name" includes the POI type. I've never seen this. So please always keep showing the POI type even if "official_name" is present.

**Comment by Nine-Tailed** [comment]
Не согласен, утверждение, что официальное имя всегда включает тип организации не имеет обоснования, в вики на этот счет ничего не сказано и даже имеющийся там пример в англоязычной версии не содержит тип poi. Тег изначально был придуман для названия стран, и в примере приведена Андорра, а официальное название Княжество Андорра. По вашей логике  тогда полное название `страна Княжество Андорра`. Официальное название это именно название, а не тип ПОИ + оф. название.
