### ISSUE TITLE
POIs with the same tags are displayed differently in OsmAnd

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#13765]
### Description

On the OpenStreetMap POIs have the same tegs, but in OsmAnd they are displayed differently. 

<table style="width:100%">
  <tr>
    <th><img src="https://user-images.githubusercontent.com/80623554/154450238-daa0b111-9f4a-4011-919e-ac2c7d466717.png"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/80623554/154450193-38bb707e-1a52-4f1a-a3bf-c3a834a33c5e.png"  width="300" height="auto"/> </th>
  </tr>
</table> 

https://www.openstreetmap.org/node/768713167
https://www.openstreetmap.org/node/787531807

<table style="width:100%">
  <tr>
    <th><img src="https://user-images.githubusercontent.com/80623554/154448692-e91bdbfc-f2d9-4ac6-ac4e-37bea7e58ace.jpg"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/80623554/154448711-0320b4c4-cdce-42aa-b2f2-695144eda2ac.jpg"  width="300" height="auto"/> </th>
  </tr>
</table> 
Also, one icon does not display in the zoom 19
<table style="width:100%">
  <tr>
    <th><img src="https://user-images.githubusercontent.com/80623554/154451085-6cfc0dcd-bbf4-4046-9045-19db8b05d432.png"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/80623554/154451165-956721c5-94be-4e02-b2d4-676d5509ff90.png"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by scaidermern** [comment]
I have seen such behavior caused by OsmAnd live. With OsmAnd live, a recently edited object can appear differently than older objects with the same tags.

**Comment by ivanPyrohivskyi** [comment]
Map data, POI section:
sport: pitch  Lat 51.20041 Lon 6.601088 osmid=768713167 
sport: table_tennis  Lat 51.20041 Lon 6.601088 osmid=768713167 
sport: pitch  Lat 51.20037 Lon 6.601705 osmid=787531807 
sport: table_tennis  Lat 51.20037 Lon 6.601705 osmid=787531807 

Place where select only one amenity:
https://github.com/osmandapp/OsmAnd/blob/ad2c27899a1d8fd2de73e7109889b69d3521d381/OsmAnd/src/net/osmand/plus/views/layers/MapSelectionHelper.java#L619

Here you can collect amenities for create list for user's select:
![Screenshot 2023-02-20 at 14 28 32](https://user-images.githubusercontent.com/1040293/220108037-9a629e9a-3e26-4cac-8da9-feaf1150e52f.png)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14192mqta, Released: 2023-02-21
Done
