### ISSUE TITLE
Typo in Google Play Store description for Osmand+

### ISSUE THREAD

**Issue by neutric** [osmandapp/OsmAnd#13762]
https://play.google.com/store/apps/details?id=net.osmand.plus&hl=en&gl=US says "OsmAnd+ privilegies" where it should say "OsmAnd+ privileges".

**Comment by MarioSwitch** [comment]
Should be closed
![Capture d’écran 2022-12-23 233223](https://user-images.githubusercontent.com/58565980/209410701-005945cf-30ba-4517-9129-6a8dbc19d398.png)
