### ISSUE TITLE
Road surface not rendering correctly

### ISSUE THREAD

**Issue by bbo2adwuff** [osmandapp/OsmAnd#13761]
Road surface does not render correctly anymore with `4.1.11` (see [screenshots](Screenshots) below).
Before it was just working as expected.

# Screenshots

## Enabled `Show road surface`
![signal-2022-02-15-220114_001](https://user-images.githubusercontent.com/34131023/154150598-2592b457-0006-4e14-bb4a-20812c3d5552.png)

## Most roads do not show road surface
![signal-2022-02-15-220114_002](https://user-images.githubusercontent.com/34131023/154150601-19721153-db57-4b29-82d6-dff3c9ec6971.png)

## But in this area all roads have `surface` information
![Screenshot 2022-02-15 at 22-06-04 OpenStreetMap](https://user-images.githubusercontent.com/34131023/154150603-29309094-9a95-4040-becd-134907bf82e2.png)

**Comment by xmd5a2** [comment]
Map generation was broken
https://github.com/osmandapp/OsmAnd/issues/13711
