### ISSUE TITLE
Wrong lane guidance

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#13775]
I'm experiencing several wrong lane guidance issues. Probably since February maps but not sure. With and without OsmAnd live.

Example:
![IMG_20220219_081837](https://user-images.githubusercontent.com/1040784/154791187-102ecfec-4925-4eb4-b564-11bcac9e2f87.jpg)

From: 51.10048,13.73578
To: :51.12508,13.74773
Way: https://www.openstreetmap.org/way/251360269

I have to turn right into the motorway link but the lane guidance tells me otherwise.

This happened at other locations, too.

**Comment by vshcherb** [comment]
I think already fixed https://osmand.net/map?start=51.104324%2C13.735277&end=51.108839%2C13.737364&mode=car

![Screen Shot 2022-02-21 at 14 09 29](https://user-images.githubusercontent.com/1042025/154961612-b8bb1e39-733a-4bb6-8b55-e102d811230d.png)

**Comment by scaidermern** [comment]
Still looks wrong in the latest nightly downloaded today:

![photo_2022-02-24_13-07-16](https://user-images.githubusercontent.com/1040784/155521329-07612df2-8903-4b89-98c9-ced3845fa19c.jpg)

Only right before the turn the lane guidance is correct. All the way before it is incorrect.

Does the fix need new maps?

**Comment by vshcherb** [comment]
https://osmand.net/map?start=51.104324%2C13.735277&end=51.108839%2C13.737364&mode=car#17/51.10485/13.73806

**Comment by vshcherb** [comment]
![Screen Shot 2022-02-24 at 15 54 30](https://user-images.githubusercontent.com/1042025/155548323-f3ea32b2-2c2d-4c10-bc83-08e3ed24add1.png)
Indeed I checked on the other turn

**Comment by vshcherb** [comment]
I actually think the problem can't be fixed actually https://www.openstreetmap.org/way/233786234. Turn right could be this road first, so probably it works even better in this situation, I mean less confusing for the driver who won't turn right here.

Anyway there are missing OSM details how to identify this situation cause it could be interpreted both ways.

**Comment by scaidermern** [comment]
I see, the information is indeed not very clear :(
