### ISSUE TITLE
Rename tracks subfolder

### ISSUE THREAD

**Issue by Gbernardy** [osmandapp/OsmAnd#13770]
# 🚀 feature request

### Describe the solution you'd like

With click short tap on folder ... open the folder (now it works like this)

With long tap on folder (new additional function) open the new panel for folder handling (rename or delete command).

**Comment by Lee-Carre** [comment]
What ‘folder’ (directory?), where, related to which feature or area of the UI?

You can rename directories via your OS, though that may cause disruption depending on what & where.

[Why](//xyproblem.info/) do you want to rename arbitrary directories?

**Comment by Gbernardy** [comment]
I would like to rename the user folders containing the my tracks. 

It's true ... i could use OS ... but not all users know how to do it.
