### ISSUE TITLE
Italian Language translate error

### ISSUE THREAD

**Issue by Gbernardy** [osmandapp/OsmAnd#13776]
### Description

In the Italian language "aggiungi ad una traccia" is equivalent to the operation of appending the track in edit to a second track.  It must be corrected with "aggiungi una traccia" which is equivalent to appending a second track to the track being edited.

![IMG_20220219_135817](https://user-images.githubusercontent.com/99968793/154802572-a9a53f09-99f8-4197-be47-91bc7054a1fc.jpg)
![IMG_20220219_141658](https://user-images.githubusercontent.com/99968793/154803182-a71723ec-16a4-4322-8c37-09b0e203b27c.jpg)

### Your Environment
OsmAnd Version:
Android/iOS version:
Device model:

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by vshcherb** [comment]
Please feel free to edit the typos https://hosted.weblate.org/projects/osmand/. It would be very nice if you could help.

**Comment by dmpr0** [comment]
Should be reverted.
"Add to a track" is different from "Add a track", add a track could mean that selected track will be added to currently edit, but it won't.

**Comment by Gbernardy** [comment]
In #13839 I proposed a UI overhaul of the tracks update functionality to remove other bugs and to simplify it.

I remain of this opinion.  

In any case I'm not the only one ... see #14119

With any file editor ... when queuing, this affects the file being edited and not the queued one ... Only on osmand the opposite happens ... That's all.

**Comment by vshcherb** [comment]
@Gbernardy we're going to create new issue or you can create to "import track into current", so with name action will do what you say. It will import existing track into editing track

**Comment by Gbernardy** [comment]
Don't worry ...,
Third user will take care of it ... 
I have no doubts about it.

**Comment by Gbernardy** [comment]
> Should be reverted. "Add to a track" is different from "Add a track", add a track could mean that the selected track will be added to current edit, but it won't.

"add to a track" mean ...

Tracks union = 
Track selection dialogue +
Track current edit 

and not 

Tracks union = 
Track current edit +
Track selection dialogue

as now ...
