### ISSUE TITLE
OSM-like rendering style

### ISSUE THREAD

**Issue by 32Vache** [osmandapp/OsmAnd#13778]
# 🚀 feature request

I have been working on a rendering style that looks like the default OSM tiles, inspired by the old Mapnik rendering style.
Could it be added as one of the rendering styles included by default with OsmAnd?
Here is the [xml file](https://raw.githubusercontent.com/32Vache/RoadRepo/main/osm.render.xml). It works as a depedent of the default style.

Screenshots for comparaison:
<img src="https://user-images.githubusercontent.com/42336759/154807891-ee322068-c352-448b-b737-13f5283fe648.jpg" alt="osmand 1" width="350"/> <img src="https://user-images.githubusercontent.com/42336759/154808003-15b105c0-3745-424a-af9e-d5275280c808.png" alt="osm 1" width="350"/>
<img src="https://user-images.githubusercontent.com/42336759/154807895-1428ef58-c725-4bb9-a849-056dc1105d0a.jpg" alt="osmand 2" width="350"/> <img src="https://user-images.githubusercontent.com/42336759/154808004-6681879d-e799-4f6d-9f7c-f23f3fb52eb9.png" alt="osm 2" width="350"/>

**Comment by vshcherb** [comment]
I think we need to merge it somehow with Mapnik. General idea of Mapnik to be default look like OSM

**Comment by 32Vache** [comment]
> I think we need to merge it somehow with Mapnik. General idea of Mapnik to be default look like OSM

So like replace Mapnik? I used Mapnik as a template to create this style, by replacing colors and changing other things, only got rid of the high contrast roads substyle.

**Comment by ivanPyrohivskyi** [comment]
OSM-carto

**Comment by Dima-1** [comment]
Remove mapnik from renderer registry https://github.com/osmandapp/OsmAnd/pull/13966

**Comment by Hades1503** [comment]
> > I think we need to merge it somehow with Mapnik. General idea of Mapnik to be default look like OSM
> 
> 
> 
> So like replace Mapnik? I used Mapnik as a template to create this style, by replacing colors and changing other things, only got rid of the high contrast roads substyle.

Salut, je viens de tomber sur ta publication qui m'intéresse beaucoup!

Nous sommes plusieurs à travailler actuellement sur un rendu vélo pour Osmand. Tes connaissances nous aiderait pour régler quelques petits détails 😃

Notre projet est ici: https://github.com/Hades1503/OsmAnd_Cycling_Map

Ton aide nous serait précieuse! 

Je n'ai aucun moyen de te contacter, je te laisse mon mail.

Hades_Si@protonmail.com
