### ISSUE TITLE
World altitude correction map always shown as update

### ISSUE THREAD

**Issue by kirchwitz** [osmandapp/Osmand#1377]
After updating OsmAnd+ 2.0.4 (totally fresh install) to 2.1.1 (all from Google Play store), OsmAnd always says there's an update for the "World altitude correction" map (dated 2005/07/08). No matter if I download the map, force-kill the app, reboot the phone (in any order possible), OsmAnd insists on updating this specific map. This bug didn't occur in 2.0.4.

If I remember correctly this was already an issue with OsmAnd 1.x series and also sporadically happened after an update.

Device is a Samsung Galaxy S3 running official Android 4.4.4 by Samsung.

**Comment by GabrielSebastianMoise** [comment]
Cofirm that. This issue was also in some previous versions, along tts voice and other files

**Comment by a903user** [comment]
Yes, I can confirm this. By the way, this bug has repeated regularly since 1.x versions...

**Comment by vshcherb** [comment]
Fixed
