### ISSUE TITLE
Add to a track without asking for  confirmation

### ISSUE THREAD

**Issue by Gbernardy** [osmandapp/OsmAnd#13777]
### Description

Edit track

When a second track is added to the track being edited, the result is saved on the second track without asking for confirmation.
<img src="https://user-images.githubusercontent.com/99968793/154802453-2cee9f4f-80e2-43c8-bf93-3faad76551cd.jpg"  width="300" height="auto"/> 

### Your Environment
OsmAnd Version:
Android/iOS version:
Device model:

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by Gbernardy** [comment]
> Yes it is an expected behavior. As I see wording is ok.

but the user should be advised that the union of the two tracks is saved on top of the second track

**Comment by oluc** [comment]
(@Gbernardy that's not useful, please.)

**Comment by oluc** [comment]
@vshcherb could you review my comments, when you have time? thanks

**Comment by vshcherb** [comment]
`

**Comment by vshcherb** [comment]
Right now we're investigating 2 alternatives:
1. Change action to "Add track/segment to current" which is nice cause you could probably add individual segments 
2. Change editing action and allow preview of merged track, so it will be saved after confirmation.

**Comment by Gbernardy** [comment]
personally I would be more for the first hypothesis.  If you then create the addition of points in the track being edited, you would also get the preview ....  Then it is up to the user whether to save on the track in edit or on a new track.
