### ISSUE TITLE
Theme change not working without restart

### ISSUE THREAD

**Issue by kirchwitz** [osmandapp/Osmand#1378]
After updating from OsmAnd+ 2.0.4 (fresh install) to 2.1.1 (all from Google Play store), my standard "Dark" theme had mysteriously changed to "Light" theme. Hopefully that will not happen for every update now.

Not a problem, so I changed the theme back to "Dark", but it only got applied for the "General settings" menu, not for "Settings" menu and also not for the overlay on the main map screen. I was wondering if I had changed it properly and was going to verify my selection, and now the "Settings" menu was "Dark" as well. But from this point on, no matter what I did, the overlay on the main map screen stayed "Light".

Only when I leave the app (no need to force-kill it but that would do the job as well) and re-enter again, then also the overlay on the main map screen finally gets "Dark".

Maybe not a big issue but a little confusing with the mixed "Light" and "Dark" screens until you leave the app. As a simple work-around there could be a small note on the General settings screen that recommends to restart the app to have the change take effect (a lot of apps do it this way, and I'm totally fine with this).

Also I'm wondering why the theme had changed during the update (2.0.4 -> 2.1.1) and if other settings might have changed as well.

**Comment by GabrielSebastianMoise** [comment]
Confirm the same issue, along other settings (checked the high contrast road,but in reality reverted to default.you have to check again the option to switch from default to high contrast roads )

**Comment by vshcherb** [comment]
True we need to give clear confirmation that restart is required.

**Comment by vshcherb** [comment]
This is not the only option, I've noticed for couple of plugins restart is required. It will be good to create a list of things.

**Comment by sonora** [comment]
My short list, so far:
Restart required after theme change, change of display language, and de-activation of obf files (like seamap or wikis), or else you may still get POIs displayed from deactivated maps under certain circumstances.

We should also test again if after first download of hillshade files a restart is required, I think I have the impression hillshading may not be displayed before that, but not sure.

**Comment by vshcherb** [comment]
To Sonora : 
I Fixed all plugins activation/deactivation and now it should be consistent. Once you deactivate plugin all widgets and layers are removed, once you activate they come back. Tested on all plugins. Please check consistency again.

Deactivation obf files might a separate issue.

For language and theme a dialog was added.
