### ISSUE TITLE
Support custom keyboard actions i.e. store waypoint on currently recorded track

### ISSUE THREAD

**Issue by joostbijl** [osmandapp/OsmAnd#13786]
# 🚀 feature request

### Description

When i'm recording a track, i'd like to store a location by pressing a button on my external keyboard.

I control Osmand using buttons on my handlebar (see https://jaxeadv.com/gear-gadgets/navigation-setup/handlebar-buttons/). These buttons simply send a keystroke via a bluethooth keyboard profile from an arduino device. 

When i'm driving, i sometimes like to store a location because of the view, the conditions, or something interesting happened there. When i'm not driving, i can go back to the gpx track, and match the waypoints i created with photo's, or look at the map of that location.

It would be very helpful if i can store a waypoint on the recorded track for this, simply by sending a keystroke.

### Describe the solution you'd like

Extend MapActivityKeyListener.java to also listen for 'X'. Once this button is pressed, store the location as a waypoint on the currently recorded track.

### Describe alternatives you've considered

The alternative is stopping, taking your gloves off, longpress on my current location, add favorite. This doesn't exactly do what i want because it saves a favorite, not a waypoint along the currently recorded gpx track.

**Comment by vshcherb** [comment]
I think it comes with generic feature map keyboard keys to quick actions, we have planned it but that needs to be implemented somehow

**Comment by joostbijl** [comment]
Thanks @vshcherb ! Looking forward to the generic key mapping. That makes Osmand even more powerful!

**Comment by webmonkey** [comment]
+1 one for this feature - either implemented via a specific key-binding or via a generic key/feature map.

I also ride a motorbike and have a set of handlebar mounted buttons emulating a BLE keyboard.

**Comment by lubaldi** [comment]
i also Riding with Bluetooth Keyboard (see ([https://7solid.myshopify.com/products/joymap])) and adding a Waypoint simply pushing a button could be very usefull.

Please implement it !!!

**Comment by vshcherb** [comment]
Now we have custom keyboard actions but the list is limited now for default actions, we're going to integrate it with quick actions list

**Comment by vshcherb** [comment]
I think it could be merged to more generic planned for 4.7 https://github.com/osmandapp/OsmAnd/issues/18821

**Comment by fcg42** [comment]
When can we expect this feature to roll out?

**Comment by dmpr0** [comment]
> When can we expect this feature to roll out?

Available in 4.8 release.
