### ISSUE TITLE
"Search POI" incorrectly registers current map center

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1379]
1)Search some POI, expand search radius to 100km.
2)Select POI which is far away from current location
3)Select "Show on map".
4)Do not touch screen and call "search POI" dialog again from dashboard.
5)All POIs are searched around previous map center not current.

**Comment by sonora** [comment]
I can confirm this, but it does not always happen, only sometimes. (When it happens, leaving the POI search and briefly going to the map screen, then re-entering the POI search fixes the issue.)

So we somehow need an additional check to reliably update the map center _always_ upon entering the POI search.
