### ISSUE TITLE
Search too many partial Address matches hide Precise POI match (Rossio in Lisbon)

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#13797]
### Description
The app cannot find the Rossio is a railway or bus station in Lisbon. The name is on the map but the search does not return any result. Even if I center the map on rossio and zoom in, the search function does not find it.

https://user-images.githubusercontent.com/80623554/155178157-80694ee9-2230-4dd4-a5d7-2e0c1c10d14c.mp4

### How to reproduce?
Try to find the Rossio bus or railway station. 
One of the bus station Rossio is located here: 38.71387° N, 9.13983° W

### Your Environment
OsmAnd Version: OsmAnd 4.1.11
Android/iOS version: Android 9
Device model: sony Experience XZ 1

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by vshcherb** [comment]
Obviously transport stop is present but it is on 232-240 position which is too low. 'Rossio' has a lot of partial word for streets  i.e.
'6. Rua Terreiro de Rossio Amadora [8.67 km, 1, STREET, 30.00]'
'232. Rossio public_transport_platform [0.25 km, 1, POI, 10.00]'

**Comment by vshcherb** [comment]
![telegram-cloud-photo-size-2-5350485380945788726-y](https://user-images.githubusercontent.com/1042025/195541737-0d9d2e73-2468-4e6b-a274-dd644a93409e.jpg)

**Comment by nnngrach** [comment]
If village name is fully equal with search pahrase and if village is near with map center then show it in top of search results list.

**Comment by Zirochkabila** [comment]
[Hawkinsville](https://github.com/osmandapp/OsmAnd/issues/14570#issuecomment-1287829819)

**Comment by alisa911** [comment]
java https://github.com/osmandapp/OsmAnd/pull/15547
tests https://github.com/osmandapp/OsmAnd-resources/pull/856
<img width="648" alt="Screenshot 2022-10-23 at 16 43 50" src="https://user-images.githubusercontent.com/38911173/197471257-b03b68ce-aecc-42ba-b348-8817f46f7784.png">
<img width="618" alt="Screenshot 2022-10-23 at 16 44 46" src="https://user-images.githubusercontent.com/38911173/197471312-f4d53c32-d6fd-4e59-b727-b9b92476b9cb.png">
<img width="721" alt="Screenshot 2022-10-23 at 16 50 35" src="https://user-images.githubusercontent.com/38911173/197471331-7e58ed7a-160f-431d-933a-7baf3c60c967.png">
<img width="579" alt="Screenshot 2022-10-23 at 16 51 23" src="https://user-images.githubusercontent.com/38911173/197471367-9515c423-e705-4bb2-ab90-0b0645e9636f.png">

**Comment by alisa911** [comment]
ios https://github.com/osmandapp/OsmAnd-iOS/pull/2259
