### ISSUE TITLE
Why does OsmAnd connect to scontent-frx5-1.xx.fbcdn.net?

### ISSUE THREAD

**Issue by bege10** [osmandapp/OsmAnd#13792]
When I search for an address OsmAnd connects to scontent-frx5-1.xx.fbcdn.net. That is a Facebook URL.
Why does OsmAnd connect to Facebook? What data is sent there for what purpose?

**Comment by vshcherb** [comment]
This is mapillary, please disable that plugin if you don't feel fine with it. https://blog.mapillary.com/news/2020/06/18/Mapillary-joins-Facebook.html

**Comment by bege10** [comment]
Thank you for your answer and the link.
It is a pity that again and again good ideas go the path of money and disrespecting privacy and sell it as a progress for users.
It is a long time ago that I installed the Mapillary plugin. Has there been a privacy warning in OsmAnd when Mapillary started connecting to Facebook?
