### ISSUE TITLE
Some weird sentences in French voice (voice recorded, not TTS)

### ISSUE THREAD

**Issue by jpggithub** [osmandapp/OsmAnd#13798]
### First weird sentence
 When I have a roundabout during a trip, osmand announce (in french) something like:

"Dans 1km, préparez-vous à entrer dans le rond point **dans**" (In 1km, prepare yourself to enter the roundabout **in**)

As is, this sentence is weird. 

It must be:
"Dans 1km, préparez-vous à entrer dans le rond point" (In 1km, prepare yourself to enter the roundabout")
or
"Préparez-vous à entrer dans le rond point dans 1km" (Prepare yourself to enter the roundabout in 1km")

Perhaps there is a link with https://github.com/osmandapp/OsmAnd/issues/3663#issuecomment-296369079.

### Second weird sentence
When I arrive near the roundabout, osmand announce (in french) something like:

"Dans 400m, entrez dans le round point et prenez la, **prenez la** première sortie" (In 400m, enter the roundabout and take the, **take the** first exit"). Note the repeated "prenez la" (take the). 

Only a single "prenez la" (take the) is necessary.

OsmAnd Version: 4.1.11 Fdroid
Android version: 10 lineage
Device model: Lenovo P2

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/13799 - the task is to update french version
