### ISSUE TITLE
Trace with points > 100 editable only with high high zoom

### ISSUE THREAD

**Issue by Gbernardy** [osmandapp/OsmAnd#13809]
### Description

When the points of the track are > than 100, in edit track, the points are displayed on the track only with zoom> of 16, 17, making the track almost unchangeable on a smartphone screen ...

### How to reproduce?

Drawing track with more than 100 points
### Your Environment

Profile OsmAnd: Bicycle

Device : OP4B83L1
Brand : OPPO
Model : CPH1907
Product : CPH1907EEA
Build : CPH1907_11_F.59
Version : 11
App Version : OsmAnd
Apk Version : 4.1.11 421

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by vshcherb** [comment]
This is expected and please test with 4.2 nightly version where we have already some fixes for editing max zoom

**Comment by vshcherb** [comment]
Now there is no 100 points constant and it's flexible and depends on the points density

**Comment by Gbernardy** [comment]
With previous versions this bug was not there

**Comment by Gbernardy** [comment]
> Now there is no 100 points constant and it's flexible and depends on the points density

The density of the points also depends on the profile, the density for walk and bicycle profiles is very different from that for cars and ...

**Comment by Gbernardy** [comment]
> Now there is no 100 points constant and it's flexible and depends on the points density

The density of the points also depends on the profile, the density for walk and bicycle profiles is very different from that for cars and ...
