### ISSUE TITLE
Clicks on the track points located in the track name area do not work

### ISSUE THREAD

**Issue by Gbernardy** [osmandapp/OsmAnd#13804]
Clicks/Taps on the track points located in the track name area (above the red line in the attached screenshot) do not work.

![IMG_20220223_153237](https://user-images.githubusercontent.com/99968793/155340017-7d9541db-9a0a-44d6-af24-e872eff00e62.jpg)

**Comment by vshcherb** [comment]
Unfortunately that's expected, please shorten the name or we will try to shorten it by cutting the end with '...'

**Comment by vshcherb** [comment]
Merged with https://github.com/osmandapp/OsmAnd/issues/13803
