### ISSUE TITLE
wish: export/share AV notes with locations as GPX

### ISSUE THREAD

**Issue by martenjj** [osmandapp/Osmand#1380]
The AV notes plugin is most useful for collecting OSM mapping information.  If a note (of any sort) is taken while a GPX track is being recorded, it is added to the track as a GPX waypoint;  the position of the note can then be imported into other mapping software, or uploaded to OpenStreetMap, and used as a location.

If an AV note is taken while no GPX track is being recorded - maybe the user is not recording for a map, but just spots an interesting feature - then the note is recorded as before but there seems to be no way to export its position as GPX or in any other format, or even to show its lat/lon position.  It is of course possible to share/export the notes from the My Places - Notes screen, but this only exports the media files themselves and not their position or any other information about them.

Suggest that on that screen there should be two sharing options:  either the selected media files themselves, as now, or alternatively their positions as a GPX file.

**Comment by vshcherb** [comment]
Now on Notes screen in My Places there is an item called share Locations which creates a special gpx file.
