### ISSUE TITLE
Some oneway streets aren't showing arrows on OsmAnd Live

### ISSUE THREAD

**Issue by zekooooo** [osmandapp/OsmAnd#13800]
This seems to be affecting recently edited streets. For example, if I stop and delete live updates, "Ulica Ferde Rusana" in Zagreb, Croatia is correctly shown as one-way. But when I enable and download the latest live update for Croatia, there are no arrows anymore on this street in map view. However, routing still understands that the street is one-way. 

Using OsmAnd~ 4.1.11 (F-Droid) on Android 7.0. I upgraded recently from an older version, maybe 3.9.10 or 4.0.x which didn't have this problem.

**Comment by vshcherb** [comment]
Probably already fixed
