### ISSUE TITLE
Plan a Route: show one line for track name

### ISSUE THREAD

**Issue by Gbernardy** [osmandapp/OsmAnd#13803]
In track edit mode, the "done" button would have to be moved up to avoid improper clicks

<img src="https://user-images.githubusercontent.com/99968793/155337621-d22341f5-7896-4efa-b7c7-c1fbb6906b3a.jpg"  width="300" height="auto"/>

**Comment by Gbernardy** [comment]
Ditto for managing the transparency of the map overlay

![Screenshot_2022-02-23-15-43-00-36_99c04817c0de5652397fc8b56c3b3817](https://user-images.githubusercontent.com/99968793/155342997-200683c7-3730-4f7d-b0bc-9eaa95ca5630.jpg)
tto for managing the transparency of the map overlay

**Comment by mmh-dev** [comment]
https://github.com/osmandapp/OsmAnd/pull/13877
