### ISSUE TITLE
Map download menu, Açores (Azores) not under proper sub menu

### ISSUE THREAD

**Issue by megamster** [osmandapp/OsmAnd#13817]
In the map download menu Açores (Azores) shows under Europe and not the sub menu of Portugal, as Madeira does. It should be moved there.

![IMG_20220227_123616](https://user-images.githubusercontent.com/100518991/155882595-8e60a865-bc02-485a-aa5d-b587cfcbd2b6.jpg)
![IMG_20220227_123632](https://user-images.githubusercontent.com/100518991/155882599-79b25cc9-ee6d-4c1e-81a2-9035e5e6140d.jpg)

**Comment by vshcherb** [comment]
Azores also included separately and as part of Portugal

**Comment by megamster** [comment]
Why would it be there separately, making it the only region of a country thats not simply inside the menu for the respective coumtry?

**Comment by megamster** [comment]
Im not able to replicate that. Just uninstalled all maps and then proceeded to download the Azores standard map. It simply downloaded the map without displaying any message.

I then deleted that map and went to download the Portugal one. It also downloaded without any reference to Azores being included and the download of maps from the separare entry veing redundant
