### ISSUE TITLE
Plan Route - edit: track recalculation function

### ISSUE THREAD

**Issue by Gbernardy** [osmandapp/OsmAnd#13815]
# 🚀 feature request

### Description

Track recalculation is very useful because the map data can change.

Furthermore this function could be very useful to repair the tracks already drawn with OsmAnd with the current version and earlier (now the navigation instructions generated with the track are not correct).

### Describe the solution you'd like

In OsmAnd there is already a feature that recalculates the track, and it is the one that reverses the path ("reverse route").

The new functionality should only recalculate the track without reversing the route.

![IMG_20220225_091800](https://user-images.githubusercontent.com/99968793/155718535-aca404a5-1754-4d68-b976-71520149dcf3.jpg)

**Comment by Gbernardy** [comment]
This new feature, together with the resolution of the bug #13752 already foreseen in the 4.2 version, would allow the almost immediate reuse of the tracks created with the versions before 4.2 .. 

Can't you just insert it in 4.2?  

Thank you

**Comment by vshcherb** [comment]
Merged with another issue

**Comment by Gbernardy** [comment]
> Merged with another issue

What issue number ?

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/13031
