### ISSUE TITLE
Graphic management of folder icons

### ISSUE THREAD

**Issue by Gbernardy** [osmandapp/OsmAnd#13816]
# 🚀 feature request

### Description

With previous versions, when opening a track recorded in a folder, I remember that the source folder remained open.

In this mode it was easy to trace the track's source folder (one of the open folders).

### Describe the solution you'd like

When opening a track (track visible), the icon of the source folder should be colored yellow/orange like the icon of the track itself.

![IMG_20220226_084217](https://user-images.githubusercontent.com/99968793/155835292-90569246-7e96-4a00-ae0e-28794b7a598f.jpg)

![IMG_20220226_085015](https://user-images.githubusercontent.com/99968793/155835300-48413599-462d-4f6c-a657-396ef037f108.jpg)

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/14037
