### ISSUE TITLE
No speed data

### ISSUE THREAD

**Issue by sevareva** [osmandapp/Osmand#1381]
Hello. I'm using OsmAnd 2.1.1 (Android 4.4.2). If I'm using it with my GPS module u-blox NEO-6M I cannot get any data about my speed and the map doesn't rotate in the direction of my movement. I was thinking it maybe a problem in my GPS module because some other GPS navigation apps doesn't provide speed data too (e.g. Navmii). However one of the apps works well - it is Yandex.Maps (Яндекс.Карты). So I can make a conclusion that the input data is correct (I have attached NMEA data). Could you to revise the processing algorithms of the input data?

PS: for comparison, I have attached data that I got when using Nokia E52 (ExtGPS app) + Bluetooth GPS Android app. OsmAnd works well with this input data.

u-blox NEO-6M GPS data:
![ublox_neo6m_gps](https://cloud.githubusercontent.com/assets/13016339/8305448/fa5d3cf4-19b7-11e5-83f4-c1bd36edef47.png)
Nokia E52 GPS data:
![nokiae52_gps](https://cloud.githubusercontent.com/assets/13016339/8305468/22c712f0-19b8-11e5-8f38-1f3fcfb17fc2.png)

**Comment by sevareva** [comment]
Any advices?

**Comment by vshcherb** [comment]
Sorry for late comment,
http://www.gpsinformation.org/dale/nmea.htm looks like GPVTG is empty, though I see 31.8K in the end which means 32 kilometers per hour. OsmAnd uses standard android api and doesn't parse NMEA, so may be there are other apps which could fix the issue. Usually to connect external device, you can install a special app which will simulate local position.
