### ISSUE TITLE
Import more then "desc" from GPX

### ISSUE THREAD

**Issue by ThomasMeister123** [osmandapp/OsmAnd#13811]
### Discussed in https://github.com/osmandapp/OsmAnd/discussions/13782

<div type='discussions-op-text'>

<sup>Originally posted by **ThomasMeister123** February 20, 2022</sup>
Hello!

I have GPX-Files with detailled informations in different tags: name, desc, cmt, link.

OSMAnd only shows the "desc"-tag. Is it possible, to import/display all tags?

GPX:
![grafik](https://user-images.githubusercontent.com/62500258/154845402-213d1ec8-3d8d-4c56-8ada-deee35365272.png)

OSMAnd:
![grafik](https://user-images.githubusercontent.com/62500258/154845370-2addc720-7f94-4163-a6c5-a586fadda3c8.png)

same example in LocusMaps:
![grafik](https://user-images.githubusercontent.com/62500258/154845386-c37cb6a9-56a5-426d-a84a-3e2e63349851.png)

</div>

**Comment by vshcherb** [comment]
Implemented in latest build
