### ISSUE TITLE
Plan route: Key management "go back" in edit  track

### ISSUE THREAD

**Issue by Gbernardy** [osmandapp/OsmAnd#13825]
# 🚀 feature request

### Description

If you have updated a track and click on "go back android" without saving, OsmAnd does not immediately show the "exit without saving" panel but the "my places" screen.

![IMG_20220227_154421](https://user-images.githubusercontent.com/99968793/156035438-901d8761-cda3-45a5-98a7-cffde91353b2.jpg)

![Screenshot_2022-02-27-15-57-27-17_54166e5c6f8ad9491c65e2397c495c92](https://user-images.githubusercontent.com/99968793/156035469-e6396dff-2d4b-44d6-8d70-167d2248cecc.jpg)

### Describe the solution you'd like

If you have updated a track and click on "go back android" without saving, OsmAnd must immediately display the "exit without saving" panel and not the "my places" screen.

**Comment by Gbernardy** [comment]
can be mergeed with issue #13839

**Comment by vshcherb** [comment]
Merged #13839
