### ISSUE TITLE
Change lanes indication so it's visible lanes split on single lane road

### ISSUE THREAD

**Issue by mdykierek** [osmandapp/OsmAnd#13829]
### Description
I have 3 situations with surprising guidance hints.
1. An intersection (https://www.openstreetmap.org/#map=19/50.26335/18.90335) with a single lane, one way going straight south where hints show and tell - keep left.
![1646130808951](https://user-images.githubusercontent.com/27214784/156153212-869ad8de-bbbb-4672-b86b-aa85648eb790.jpg)
2. An intersection with two way road with single lane in each direction where hints tell to take left lane (https://www.openstreetmap.org/#map=19/50.25410/18.89678)
![IMG_20220301_113754](https://user-images.githubusercontent.com/27214784/156154207-02568a2a-f1cf-4255-9aef-f58a3c9f1931.jpg)
3. An intersection with two way road with single lane in each direction where hints tell to keep right -well, this at least doesn't cause confusion (https://www.openstreetmap.org/#map=19/50.26335/18.90335)
![1646131464019](https://user-images.githubusercontent.com/27214784/156154931-7abf871b-ec47-4023-982c-18989682b363.jpg)

Tried to edit the intersections in osm.org but without success.

### Your Environment
OsmAnd Version: 4.1.11
Android/iOS version: Android 11
Device model: Mi 9T Pro

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by scaidermern** [comment]
I had a similar problem about two weeks ago. Deleting and redownloading live data fixed it for me. So I suspect this is a bug related to OsmAnd live. Not reproducible so far for me.

Are you using OsmAnd live?

**Comment by mdykierek** [comment]
I am using OsmAnd live as an active OSM editor.
I have disabled live updates and deleted data - same misbehavior.
Enabled again and downloaded latest updates - same misbehavior.
Since all coordinates are known, you can try on these 3 intersections for yourself with a simulated navigation.

**Comment by vshcherb** [comment]
it's partially correct behavior prior we have implemented lanes count support. In the end we would like to show that you need to keep left and displayed with 2 lanes though we could generate another Traffic sign with 1 lane and 2 directions i.e. "keep left | keep right".

**Comment by mdykierek** [comment]
Please note that in case of 2-way single lane each direction case, showing keep left (case no.2 / Wyzwolenia and opposite to case no. 3 Polna) it can be dangerous - left lane is opposite direction. I was surprised as I have not seen guidance like that in my past experience with directions. Will try driving with Sygic and Google more to check.
Isn't it a bit exaggerated? Does it make sense to take left or right side of a single lane?

**Comment by scaidermern** [comment]
> Does it make sense to take left or right side of a single lane?

Definitely not. If there is just a single lane (for the current direction) then there is absolutely no reason to display more than one in the lane guidance.

**Comment by vshcherb** [comment]
It should be an icon with road split

**Comment by Zero3** [comment]
Might be related to this issue: https://github.com/osmandapp/OsmAnd/issues/13383

**Comment by OpenSourceForEver** [comment]
Keep in mind that an icon implies having to look at the device screen, which is dangerous. The voice instructions should be changed so that there are no mistakes if you do not look at the device screen.

**Comment by vshcherb** [comment]
We also need to fix this issue https://github.com/osmandapp/OsmAnd/issues/15075

**Comment by mdykierek** [comment]
This is most annoying in e.g. Finland.All highway parkings cause fake left/right lane guidance and in fact distract and when there is a real manouver to make,one can easily miss.On Aug 15, 2022 14:06, vshcherb ***@***.***> wrote:
We also need to fix this issue #15075

**Comment by vshcherb** [comment]
We would like to have split sign instead of 2 lanes configuration (confusing)

![Screenshot 2023-02-20 at 12 57 07](https://user-images.githubusercontent.com/1042025/220086320-a09bcf7e-595b-423c-8897-9214ddc9736f.png)

**Comment by Prusaker** [comment]
When leaving a road (without turn:lanes tag) where there is no braking lane, the program shows an additional non-existent lane:

![Screenshot_2024-02-04-14-43-40-668](https://github.com/osmandapp/OsmAnd/assets/32092837/e96b05ab-6d51-44f5-ab4b-d3b73e5e3ca4)
[https://www.openstreetmap.org/way/629093198#map=17/53.84003/27.49388](https://www.openstreetmap.org/way/629093198#map=17/53.84003/27.49388)

[Yandex panoram](https://yandex.by/maps/157/minsk/?l=stv%2Csta&ll=27.492887%2C53.840287&panorama%5Bdirection%5D=90.245049%2C-4.491562&panorama%5Bfull%5D=true&panorama%5Bpoint%5D=27.492297%2C53.839792&panorama%5Bspan%5D=107.582652%2C60.000000&z=18)

The road have 3 lanes, however OsmAnd shows 4 lanes.

**Comment by DmitryAlexei** [comment]
@Prusaker Have you tried the release version or the latest nightly build?
Cannot reproduce with Nightly and fresh (from February) maps. 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/b5bee960-5203-48e1-87b0-58d47971cd36"  width="300" height="auto"/> </td>
  </tr>
</table>
