### ISSUE TITLE
Crash on restore from file

### ISSUE THREAD

**Issue by iexos** [osmandapp/OsmAnd#13821]
### Description
The restore function crashes, when restoring map markers. I can send restore file on request (its big and contains sensitive information).

### How to reproduce?
- go to Settings > Backup & Restore > Back up as file
- select everything and execute backup
- uninstall osmand
- reinstall osmand
- go to Settings > Backup & Restore > Restore from file
- select everything and attempt restore (selecting all but map markers works)

### Your Environment
OsmAnd Version: 4.1.11 421 (f-droid)
Android/iOS version: LOS 18.1
Device model: Fairphone 3

Log: [exception.log](https://github.com/osmandapp/OsmAnd/files/8153224/exception.log)

**Comment by cepprice** [comment]
@iexos Can you please backup only Itinerary (Settings -> Backup & Restore -> Backup as file -> select only Itinerary in My Places) and share resulting file?

**Comment by iexos** [comment]
I removed the app after making the full backup (900MB), so I cannot do this in the original state. I imagine its no use to do it now with my new install (with importing everything but map markers), or do you think otherwise?

**Comment by cepprice** [comment]
@iexos In that case I suggest you to open backup file (.osf) as archive (7-Zip, WinRAR), extract file `itinerary.gpx` and share it

**Comment by iexos** [comment]
I have extracted it and decided that the file is too sensitive to share. I also tried reproducing the error on my own. Here is what I found:

The import of the full marker history crashes every time. However, the point at which it stops importing seems arbitrary, there is no single point which breaks the import. I suspect that it is just the amount of imported markers: My itinerary has 655 points (1 active and 654 history markers).

I wanted to reproduce this by creating a similar backup file with non-sensitive data, though i judge it too tedious to do by hand.

**Comment by cepprice** [comment]
@iexos Most likely import crashes because there are at least two (and probably just two) markers with same value of tag `<osmand:itinerary_id>` (IDs should be unique). It seems that you didn't get crash after editing .gpx because you deleted marker with duplicate id. So, all we need is this non-unique id.

To find it quickly without sharing your file, you can paste contents of your original `itinerary.gpx` [here](https://www.somacon.com/p568.php), select `Duplicates only` and press `Display\Update Counts`. You probably will be presented with line `<osmand:itinerary_id>some_kind_of_id</osmand:itinerary_id>`. That's what we are looking for

**Comment by iexos** [comment]
@cepprice actually, no. All 655 IDs are unique.

What I observe: The restore starts adding the markers from newest to oldest. At some point it crashes, and at which point it crashes is random. The longer it takes to crash, the more points are imported. I tested with deleting app data before every time.

**Comment by black-square** [comment]
I have the same problem but when I restore "Map Markers"

See attached files for the details.
[exception.log](https://github.com/osmandapp/OsmAnd/files/8366976/exception.log)
[Export.zip](https://github.com/osmandapp/OsmAnd/files/8366975/Export.zip)

Pixel 6
Version  OsmAnd+ 4.1.11
Android 12
