### ISSUE TITLE
Incorrectly detected POI type (?) and address

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/OsmAnd#13827]
Osmand Nightly Build (25 february)
Offline OsmAnd Maps.

Some addresses that are bordering more than one street display their address incorrectly. Maybe OsmAnd should show the address that appears in OSM instead of calculating it automatically.

Some examples:
https://www.openstreetmap.org/way/198954688#map=19/40.72902/-4.01551
https://www.openstreetmap.org/way/198954720#map=19/40.72902/-4.01551
https://www.openstreetmap.org/way/317240485#map=19/40.72909/-4.01480
https://www.openstreetmap.org/way/199081617#map=19/40.73017/-4.01076
https://www.openstreetmap.org/way/200489319#map=19/40.73174/-4.00881
https://www.openstreetmap.org/way/200489294#map=19/40.73228/-4.00849

**Comment by vshcherb** [comment]
Not sure, if I understand what's the issue. We plan to continue calculate addresses on device but I didn't find any problem on these addresses with our tools. Probably you can explain where it happens

![Screen Shot 2022-03-02 at 17 38 54](https://user-images.githubusercontent.com/1042025/156406680-540a8b8b-69c3-4f59-9826-cabb70985fe4.png)

**Comment by vshcherb** [comment]
You can play with this tool around https://osmand.net/map#20/40.72873/-4.01571 (context menu - where am I).

**Comment by OpenSourceForEver** [comment]
https://www.openstreetmap.org/way/198954688#map=19/40.72902/-4.01551
Correct address: Paseo de los españoles,12 
Showed address: Avenida de Madrid, 7
![Screenshot_2022-03-06-19-15-33-052_net osmand dev](https://user-images.githubusercontent.com/12786225/156937171-928ad7ab-50e9-42e5-9164-3856ddb80294.jpg)


https://www.openstreetmap.org/way/317240485#map=19/40.72909/-4.01480
Correct address: Plaza del Doctor Gereda, 9
Showed address: Calle del Mayo (without house number)
![Screenshot_2022-03-06-19-16-47-218_net osmand dev](https://user-images.githubusercontent.com/12786225/156937188-3979434c-7509-425a-9785-7822d83fd7e2.jpg)


https://www.openstreetmap.org/way/199081617#map=19/40.73017/-4.01076
Correct address: Plaza del Gargantón, 1
Showed address: Calle del Nogal (without house number)
![Screenshot_2022-03-06-19-17-23-631_net osmand dev](https://user-images.githubusercontent.com/12786225/156937203-9664b18c-7177-4968-aa26-a642299eae7d.jpg)


https://www.openstreetmap.org/way/200489319#map=19/40.73174/-4.00881
Correct address: Calle del Sotillo, 5
Showed address: Calle de las Eras, 4
![Screenshot_2022-03-06-19-18-27-274_net osmand dev](https://user-images.githubusercontent.com/12786225/156937208-9fa81969-7754-40d1-8213-d9347460162e.jpg)


https://www.openstreetmap.org/way/200489294#map=19/40.73228/-4.00849
Correct address: Calle de las Eras, 21
Showed address: Travesía del Sotillo, 6
![Screenshot_2022-03-06-19-19-15-025_net osmand dev](https://user-images.githubusercontent.com/12786225/156937213-03a77e82-2be5-404a-81db-7afe8eebfbae.jpg)

**Comment by vshcherb** [comment]
Side note: Please use small screenshots using html tags - <img src="https://user-images.githubusercontent.com/12786225/156937171-928ad7ab-50e9-42e5-9164-3856ddb80294.jpg" width="25%" height="25%" />

**Comment by vshcherb** [comment]
Was related to https://github.com/osmandapp/OsmAnd/issues/12970

**Comment by Chumva** [comment]
Some fixes were done here - https://github.com/osmandapp/OsmAnd/pull/13880 https://github.com/osmandapp/OsmAnd/pull/13881
