### ISSUE TITLE
The issue with routing in Ski profile

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#13831]
### Description
Reverse the route in the Ski navigation profile does not work. 

### How to reproduce?
Create a route between points (start 46.90015° N, 11.04022° E, finish 46.85393° N, 11.02491° E) and press reverse the route.
<p>
<img src="https://user-images.githubusercontent.com/80623554/156194881-aa33032e-9823-4c57-a917-345dd770fe8b.png" width="25%" height="25%" />
<img src="https://user-images.githubusercontent.com/80623554/156194911-c5a3f205-70bd-4e63-b506-4bedfbd0642b.png" width="25%" height="25%" />
</p>

### Your Environment
OsmAnd Version: 4.1.11
Android/iOS version: Android 9
Device model: Sony Experience XZ 1

**Maps used (online or offline):**   1.02.2022
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by xmd5a2** [comment]
1.Incorrect entity_convert
2.Incorrect tagging (`oneway=no` instead of `piste:oneway=no`)
Should be fixed in march maps
