### ISSUE TITLE
reverse order sorting of notes/tracks would be more useful

### ISSUE THREAD

**Issue by martenjj** [osmandapp/Osmand#1383]
At the moment the "My Tracks" and "Notes" lists (under "My Places") appear to be sorted in date order, with the oldest notes/tracks always appearing at the top.

I'd suggest that a more useful sorting order (if it could not be made user configurable) would be to have the newest information at the top, as this is likely to be most relevant to a trip or survey being performed at the time.

**Comment by sonora** [comment]
The situation is more complex: You can have sub-folders also in your tracks folder, and alphanumeric names, so it is not just a "sort by date" question.

As long as we have no sorting customization, we have both the following:
- Under "Dashboard /My Tracks/Show all", the order in which tracks are displayed is alphabetically, which (when only our ISO date format standard track names are in use) results in newest being at the bottom. But this is useful if you look for e.g. tracks from tour books, which have alphanumeric titles and you would look for them alphabetically.
- Under Map screen / Configure map (top left icon) / GPX Tracks, the sorting is anti-alphabetically, which is exactly how you suggest you want it.  :-)

**Comment by martenjj** [comment]
Thanks for the clarification regarding the track names.  I was aware that there could be subfolders, so the sorting is really "alphabetical (or reverse) within subfolders".

Notes, though, seem to be sorted in date order (or maybe they are not sorted and appear in filesystem order) - and there is no user control over the names - so reversing the order here would be useful.

**Comment by vshcherb** [comment]
No action is planned, seems to be small issue and difficult to change regarding all consequences.
