### ISSUE TITLE
Azores also included separately and as part of Portugal

### ISSUE THREAD

**Issue by megamster** [osmandapp/OsmAnd#13837]
Azores also included separately and as part of Portugal

_Originally posted by @vshcherb in https://github.com/osmandapp/OsmAnd/issues/13817#issuecomment-1056959898_

Theres no indication that the map for Portugal already includes Azores, since it also shows up separately (user would think they need to download both to have the Azores), Azores also being the only region of a country that appears in the sub menu level where the countries appear.

For sanity/consistency's sake, Azores should be removed from the Portugal map itself and added as a region within Portugal, as Madeira currently is, obviously removing it from the country sub level.

**Comment by vshcherb** [comment]
There is indication if you Tap on Azores, it will be suggested to download only Azores or Portugal.

**Comment by vshcherb** [comment]
Merge back to https://github.com/osmandapp/OsmAnd/issues/13817#issuecomment-1056959898
