### ISSUE TITLE
Always recalculation route when set minimal distance to recalculate route is 20m

### ISSUE THREAD

**Issue by LeLuyen** [osmandapp/OsmAnd#13838]
Hi All,

When i'm setting minimal distance to recalculate route is 20m, the route always recalculate and ProgressBar always show.

Note: My devices don't move.

**Comment by vshcherb** [comment]
It's possible that your device produces GPS position with 20m error, so it causes constant recalculation. Please find what's the best configuration for you

**Comment by LeLuyen** [comment]
Hi @vshcherb 

Thank you your reply.

This reason of problem is "Identify wrong movement direction", I'm showing log info.
