### ISSUE TITLE
How can I restrict OsmAnd updates?

### ISSUE THREAD

**Issue by thilokab** [osmandapp/OsmAnd#13847]
Hi Team,
I'm using OsmAnd version 4.1.11 within a mobile application as an offline navigator in Android devices.

Is there a way I  can restrict OsmAnd application updates to avoid mobile data consumption?

I have tried switching off **Allow background data usage** in  `Settings -> Apps -> OsmAnd -> Mobile data`. But my understanding is this will not restrict any of the prompts for OsmAnd application updates.

Your prompt response is highly appreciated.

**Comment by scaidermern** [comment]
App updates are done by the PlayStore, not by the app itself.

Open the PlayStore. Go to the OsmAnd app. Click on More option on the top right corner. Uncheck ‘Auto-update‘.

**Comment by Gbernardy** [comment]
If you have activated the "Online Maps" plugin while navigation, the device will use mobile data to update the satellite maps.  This could be one of the causes of mobile data consumption.

![IMG_20220304_121713](https://user-images.githubusercontent.com/99968793/156754015-422f7e0c-3687-4212-a687-85f94e16fc54.jpg)

**Comment by Lee-Carre** [comment]
Depends what the OP meant, exactly, by updates.

Another feature to consider is Live Updates. Disable it, or set it to Wi-Fi-only, to reduce mobile data usage.

**Comment by thilokab** [comment]
Thanks team for all the supportive comments. 

In these Android devices, I have been using the OsmAnd application by downloading the APK from your website. Not via the PlayStroe. Is there any other way we can restrict the updates? Thanks!

**Comment by stephan75** [comment]
What updates do you mean exactly? ... This is still not clear to us.

**Comment by thilokab** [comment]
Apologies. I am keen on restricting OsmAnd updates

**Comment by Lee-Carre** [comment]
@thilokab

What stephan75 meant is; what do you mean (exactly) by ‘OsmAnd updates’?

It's somewhat ambiguous, especially given your responses to previous suggestions.

Repetition doesn't add clarity.
