### ISSUE TITLE
plan route snapping the track to my profile  (follow up)

### ISSUE THREAD

**Issue by fixifoxy** [osmandapp/OsmAnd#13840]
I have 2 different  behaviors.
1. plan route, open existing track, route between points, apply button black, klicking apply button
the mentioned colored bar appears, nearly not remarkable, done appears in the upper part of the screen. Yes plan a route with the selected profile is  done and I save it the a new file name. 
I think when "done" appears the icon of the profile should be changed to the new used one.

But this do not happen. The icon of the former application profile stays  unchanged.

The next time when I use this new track visible on the map  starting with the default application profile selected, means that the icon for the default application is shown, on loading the track,
the icon didn' t change into the icon of the profile used when planning the route. 
I had a look in the file created with the plan route tool  and find that the new used application
 profile is mentioned in every track statement. So the information is there to be used and the icon of  right application profile could be shown.
2.       With another track file (a longer track), nothing happens.
plan route, open existing track, route between points, select the profile, the apply button change to black after a moment, the thin bar colored  only for 1 cm not changing in length. And the computation seems not come to an end. Even when waiting for half  hour.
 

### How to reproduce?
Let me know what I can do for further investigation. I do not know how to download 4.2
  

### Your Environment
OsmAnd Version:4.1.11
Android/iOS version:12
Device model:

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by fixifoxy** [comment]
Ok, I found 4.2 by downloading nightly osmand. **vshcherb**, you are right,  processing runs much faster! Perhaps too fast!? Because I couldnt observe any tiny progress bar.

**Comment by vshcherb** [comment]
You can test here (select any start point and click select track) https://maptile.osmand.net/map?start=45.478866%2C10.733435&end=45.478970%2C10.733267&mode=bicycle#17/45.47237/10.79922.

As you see light blue doesn't identically match with blue line, so it does something useful attaching segments to OSM roads but it approximate the route pretty close

![Screen Shot 2022-03-25 at 17 13 03](https://user-images.githubusercontent.com/1042025/160159198-c871e334-bc77-4caa-8ff3-ea073a039c88.png)

**Comment by fixifoxy** [comment]
Can´t enter a new start point . On entering a gpx track I´ve got the  error message"502 Bad Gateway ..... center ng1nx 1.18.0....."
Is  there anywhere an updated release to download? Where?

**Comment by fixifoxy** [comment]
Downloaded OSMAND nightly 4.2.0. # 33785
Tested "plan route with existing track snapping to my profile."
VSHCHERB........Let me say: a wonderful result. And the tiny blue progress bar is running, observable.
Thanks.

**Comment by fixifoxy** [comment]
now as betatester I use Osmand 4.2.0 2022-05-10. I tested this function once again with this release I tried again.  Once again the tiny color line appears at the beginning but didn´t progress and I didn´t get any finished result. What can I do to bring this to an end.

**Comment by vshcherb** [comment]
Please attach the track here as well if it's public

**Comment by fixifoxy** [comment]
It is my combining of two different tracks. 
File type GPX an XML not supported. I zipped it.
           
[RömerbisAttersee.zip](https://github.com/osmandapp/OsmAnd/files/8837165/RomerbisAttersee.zip)
I join the used routing file as well:
[izenduro.render.zip](https://github.com/osmandapp/OsmAnd/files/8837167/izenduro.render.zip)
Will execute your instructions of the second email later on.
Thanks.

**Comment by vshcherb** [comment]
As I tested it has weird progress bar but default profile works. So as you summarized the issue is with custom profile you've mentionned.

**Comment by fixifoxy** [comment]
1. RömerbisAttersee.zip is the Zip-file of the gpx-Track for my tests.
2. gros_trail.zip is the routing file mentioned in my summerize 6 days ago.
".........I am using the solutions offered under
https://osmtopo.blogspot.com/2021/02/style-pour-osmand.html
So in release 4.2 I´ve under routing the file
[gros_trail.zip](https://github.com/osmandapp/OsmAnd/files/8873201/gros_trail.zip)
and the profile named gros trail.  "
So the gros-trail.xml was imported in the routing folder.
And  gros-trail.xml is my default profile and as such the gpx-Track RömerbisAttersee.gpx is opened with gros-trail...
Let tell you my proceeding:
1. plan route
 2. open existing track
 3. click RömerbisAttersee.gpx
 4. the file is shown in the map
 5. let bottom the rounded question marks appears and I click on it
 6. route between points
 7. click  Continue
 8.  select profile gros
 9. nothing else happens. With other profiles  "apply" darkens, click on it and the tiny progress bar is progressing.
 I hope my request is specified.
All files i used were already submitted. Please repeat my test. So we can find out or assure,   that the strange behavior is caused by the custom routing file of the french osmander who published this routing file. 
Or not.  
I would appreciate to continue using the published files of "cricri"  the french osmander.

**Comment by Zirochkabila** [comment]
> https://osmtopo.blogspot.com/2021/02/style-pour-osmand.html

[Create for test.xml.zip](https://github.com/osmandapp/OsmAnd/files/8918054/Create.for.test.xml.zip)


Your case was checked with another custom profile - the profile is added to the GPX track that you sent.
Most likely the problem is in your gras_trail profile

**Comment by fixifoxy** [comment]
I didn´t change anything. But now even with several different tracks the apply button changed to  sensitive.
Ok whatever thanks. I´ll now try the webversion as proposed.
