### ISSUE TITLE
Rotating the device aborts capture of audio/video note

### ISSUE THREAD

**Issue by martenjj** [osmandapp/Osmand#1384]
If the device is rotated during capture of an AV note, it appears to abort the capture and no note icon appears on the map.  To reproduce, start an audio or video note capture (the icon changes to say "Stop") and then rotate the device from portrait to landscape or vice versa, being careful not to touch the screen.  The icon will change back to "Start", no note symbol will appear on the map and nothing will appear in the "My Places" - "Notes" list.

Strangely, though, if after doing this I use "Take a photo" (using the system camera app) and then immediately press the back button (no need to actually take a photo), the map icon and the entry in the notes list appears.

OsmAnd map orientation is set to "Don't rotate (north up)" and screen orientation is set to "Same as device".  Using OsmAnd capture (not system app) for video.  HTC Sensation, Android 4.0.3

**Comment by vshcherb** [comment]
Merged into #1682
