### ISSUE TITLE
Public transport distance is wrong

### ISSUE THREAD

**Issue by miklcct** [osmandapp/OsmAnd#13860]
### Description
Distance shown in public transport navigation is wrong

### How to reproduce?
Plan a journey from Clapham Junction to West Brompton

The distance of the Overground leg should be about 3.72 km but it shows 2.97 km.![Screenshot_20220305-191358_OsmAnd.png](https://user-images.githubusercontent.com/2827264/156897292-2d1814f1-dd81-478f-a855-f3c0ad226fd9.png)

### Your Environment
OsmAnd Version: 4.1.11
Android version: 12
Device model: Samsung Galaxy A42 5G

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
Greater London

**Comment by OpenSourceForEver** [comment]
https://github.com/osmandapp/OsmAnd/issues/10805

**Comment by vshcherb** [comment]
Merge #10805
