### ISSUE TITLE
The historical place is highlighted as a military zone

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#13862]
### How to reproduce?

The area has a tag as historical place, but in OsmAnd it is highlighted as a military zone. 
https://www.openstreetmap.org/way/948955387#map=17/51.83298/8.95362

<img width="820" alt="PNG-Bild" src="https://user-images.githubusercontent.com/80623554/156919122-c296a91a-bf7c-4b3c-a082-7f8f475b4974.png">

**Comment by Lee-Carre** [comment]
@anastasiia936

> The [area has a tag a\[s\] historical place](//www.openstreetmap.org/way/948955387), but in OsmAnd it is highlighted as a military zone.

Interesting discovery. 👍

The mismatch is likely due to it being tagged as *formerly* of military use:

    historic=military
    abandoned:landuse=military

**Comment by xmd5a2** [comment]
Fixed. It is important to render abandoned military landuse differently than other abandoned areas because it can be more dangerous
![Screenshot_2022-03-09_18-21-00](https://user-images.githubusercontent.com/5829014/157472507-cb753d6d-3e51-4bf4-9131-5c653411131b.png)
