### ISSUE TITLE
route=fitness_trail

### ISSUE THREAD

**Issue by axelos** [osmandapp/OsmAnd#13870]
# 🚀 feature request

Hello !

### Description

Add the display of the fitness trail (the track).

### Describe the solution you'd like

In the interface, add an option in the menu:
- Configure map
- Route
- **Fitness trail**

The option displays the relations with these tags:
```
type=route
route=fitness_trail
```

### Describe alternatives you've considered

Thanks, Axel.

**Comment by xmd5a2** [comment]
https://wiki.openstreetmap.org/wiki/Tag:route%3Dfitness_trail
