### ISSUE TITLE
Default icon choice for favorites changed

### ISSUE THREAD

**Issue by stevenroose** [osmandapp/OsmAnd#13887]
### Description
Not sure this is a bug or just a feature change, but I'm annoyed by it. I have some folders with saves places and I categorize them by color. Before, by default adding a place to the category would give it a star icon with the given color (occasionally it would glitch and pick a wrong color, but well). However, now it seems the default behavior is to keep the icon of the type of place (restaurant, bar, store, ...) and just add the color. No longer showing them as stars.

I can manually pick the star icon for them, but I have to do it every time.

What was the reasoning behind this change? Is there a way to pick a "default icon" for a places category, not just a color? That'd be great.

### Your Environment
OsmAnd Version: 4.1.11
Android/iOS version: 9
Device model: 

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by tradavyvy** [comment]
This is closely related to #10850 from a year ago.
And I still strongly support default collor, icon and shape per group of favourites.

**Comment by dmpr0** [comment]
Hello! 
Yes, we change behavior for icon selection. We are working on[ #10850](https://github.com/osmandapp/OsmAnd/issues/10850) to add the ability to set default icon, shape, color for a group of favorites, I think it will also fix reporter behavior.

**Comment by tradavyvy** [comment]
Sounds good dmpr0 
I can hardly wait to see the results.
Thanks in advance.
