### ISSUE TITLE
Disabling Overlay

### ISSUE THREAD

**Issue by matmai** [osmandapp/Osmand#1388]
In v2.1.0 it is not possible to disable all overlays.

Public transport has a check box and could be disabled:
![screenshot_2015-06-24-09-24-37](https://cloud.githubusercontent.com/assets/8249305/8325081/c6674d0a-1a56-11e5-94b0-22b275dfef18.png)

But hiking and road style has radio buttons and no option to diable the overlay.
![screenshot_2015-06-24-09-24-47](https://cloud.githubusercontent.com/assets/8249305/8325090/d263c35e-1a56-11e5-8485-70259850a5ae.png)
![screenshot_2015-06-24-09-24-53](https://cloud.githubusercontent.com/assets/8249305/8325088/ce86f5a8-1a56-11e5-83bd-d1b92b237675.png)

Would be great to have an option to disable an active hoking or road overlay.

**Comment by sonora** [comment]
I cannot reproduce with version 2.1.1, so it may already be fixed. Please check again after upgrading.

**Comment by Norbert80** [comment]
@sonora have you tried also "my" resolution? (I can't download youre images on my mobil phone at the moment.)
Could there be any related file in my osmand folder in an old version that I should try to delete?

**Comment by matmai** [comment]
@sonora Yes your are right. I also could not reproduce this issue with 2.1.1 (free version):
![screenshot_2015-06-24-17-25-45](https://cloud.githubusercontent.com/assets/8249305/8349541/203f472a-1b1e-11e5-9f48-512521f6d796.png)
![screenshot_2015-06-24-17-25-50](https://cloud.githubusercontent.com/assets/8249305/8349543/21fbf176-1b1e-11e5-84ec-2b6a9913c739.png)
