### ISSUE TITLE
OsmAnd displays extra lanes

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#13899]
### Description
OsmAnd displays 14 lanes instead of 3.

https://osmand.net/map?start=35.704659%2C-105.945108&end=35.715485%2C-105.936437&mode=car#16/35.7086/-105.9413
https://www.google.com/maps/place/35%C2%B042'13.7%22N+105%C2%B056'46.4%22W/@35.7038224,-105.9464045,44m/data=!3m1!1e3!4m5!3m4!1s0x0:0x46c8d8a7454f07ce!8m2!3d35.703803!4d-105.946228

![image](https://user-images.githubusercontent.com/80623554/158185900-bdef61ba-0beb-4dea-83cd-2b6b331e0a50.png)

### How to reproduce?
Create navigation for the car profile between points:
35.70287 -105.94730
35.71303 -105.93794

### Your Environment
OsmAnd Version: 4.1.11
Android/iOS version: Android 9
Device model: Sony Experia XZ 1

**Maps used (online or offline):**   offline, maps updated from 1 Mar 2022
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by Woazboat** [comment]
Data issue, this way was tagged as having 11 lanes for some reason https://www.openstreetmap.org/way/45077059
