### ISSUE TITLE
[Hillshade issue] blinking display due to numerous refreshes

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#13895]
### Description
In nightly build the display is refreshing repeatedly like blinking, looks like a stack of refreshes is build and then work to finish, that means after some (may be ~5 , maybe more) it stops.
**No blinking with 33679**

### How to reproduce?
move the map or change zoom

### Your Environment
OsmAnd Version: OsmAnd~ 4.2.0#33715m, veröffentlicht: 2022-03-12
Android version: 8 and 10 
Device model: Samsung S7, Tab S5e

**Maps used (online or offline):**   
Mapnik, Offroad, OsmAnd, ...

**Comment by ArjanOnwezen** [comment]
Same here.
OsmAnd~ 4.2.0#33715m
Xiaomi 11 Lite 5G NE

**Comment by Nine-Tailed** [comment]
I confirm, the problem starts from March 5-7.  It is related to the hillshade setting, if you turn it off, the blinking disappears.
https://t.me/ruosmand/89394

**Comment by pebogufi** [comment]
It looks like the hillshade TRYS to show, but without success.
