### ISSUE TITLE
Motorbike optimizations - improvements request

### ISSUE THREAD

**Issue by thuryn** [osmandapp/Osmand#1389]
I would like to see new profile in osmand for motorbikes. This profile is convenient, because I need:
- possibility to specify max speed (my motorbike can go max 75 km/h) - routing should count time with regard of this max speed
- posibility to avoid 2 lines ways (not only highway, but some trunks too with more than one line (maybe navigate me by smaller ways, because of speed limit of motorbike)
- calculate time to destination regards of speed limit of motorbike
- posibility to specify amount of fuel, that could be possible to fill in (motorbike has tank for just about 4 liter of fuel) or to specify number of km to fill in fuel
- add posibility to navigate to gas station regard previous point - when I need to go 200km and motorbike need fuel every 80km, navigation engine will navigate me to gas station on the way automatically

**Comment by martenjj** [comment]
While it may not yet offer, or be able to be configured with, all of your wishes, there already appears to be a motorbike-specific profile available (version 2.1 at least):

Settings - Plugins - OsmAnd development (may need to be enabled) - Application Profiles - then select the visible ones there.

**Comment by thuryn** [comment]
I've tried motorbike profile and it looks good, thanks for hint.
