### ISSUE TITLE
Coastline artifacts around Port-Vendres (France)

### ISSUE THREAD

**Issue by Guibrou** [osmandapp/OsmAnd#13896]
### Description
the coastline in drawn with artifacts around Port-Vendres in France https://osmand.net/map#14/42.5119/3.1138

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/43842946/158053714-e844038b-19cb-4604-a2ad-ce93122f88e1.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

The issue dissapear when the world map is disabled.
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/43842946/158053727-a7a262e7-813a-4207-915b-4edb1f6b4bdd.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

### How to reproduce?

go to https://osmand.net/map#14/42.5119/3.1138 with any map profile.

### Your Environment
OsmAnd Version: 4.1.11
Android version: 11
Device model: Samsung Galaxy XCover Pro

**Maps used (online or offline):**   
France Occitanie 01/02/2022

**Comment by pebogufi** [comment]
Confirm on zoom <15 with
Samsung Tab S5e, Android 10, 
OsmAnd~ 4.2.0#33715m, veröffentlicht: 2022-03-12
