### ISSUE TITLE
Hill shading broken?

### ISSUE THREAD

**Issue by guillaumedc** [osmandapp/OsmAnd#13921]
### Description
I'm using nightly build, and for maybe a week hill shading is not working anymore.

### How to reproduce?
Download area map, altitude curves and hill shading.
Activate hill shading plugin. Map displayed includes altitude curves, but not hill shading.

### Your Environment
OsmAnd Version: 03/15 07h29 android-full build
Android/iOS version: Android 11
Device model: Poco F2 Pro

**Maps used (online or offline):**   
It seams related to rendering since it does not work neither for France, neither for Switzerland.

**Comment by pebogufi** [comment]
Yes, currently hillshade is "down", see
https://github.com/osmandapp/OsmAnd/issues/13895

**Comment by guillaumedc** [comment]
Closed because of duplication.
See [#13895](https://github.com/osmandapp/OsmAnd/issues/13895)
