### ISSUE TITLE
Dynamic shield size for concurrent routes

### ISSUE THREAD

**Issue by fred702** [osmandapp/Osmand#1392]
Often routes are signed with the ref=* tag of multiple routes, leading to a value that is too big to display. 

[example location](https://www.openstreetmap.org/#map=17/42.76699/-73.92805)

![osmand](https://cloud.githubusercontent.com/assets/12385766/8334989/ec871652-1a68-11e5-9e2b-b656713608bb.png)

Here's how it's [handled](https://github.com/gravitystorm/openstreetmap-carto/pull/694) on the main OSM style sheet.
![mapnik](https://cloud.githubusercontent.com/assets/12385766/8334998/f4dacbaa-1a68-11e5-94a8-1f87a2ee2477.png)

https://gist.github.com/Zverik/cf3c7a55c89430c930c0

**Comment by xmd5a2** [comment]
This issue already fixed in nightlies but not such way as in Mapnik

**Comment by sonora** [comment]
Leonid, I think increasing roadsDensityLimitPerTile to something like 50 or 100 would fix it? It works ok in Touring view?   But then this would increase rendering effort, battery use, etc.

**Comment by fred702** [comment]
:+1:
