### ISSUE TITLE
Show Wikimedia Commons photos that depict the Wikidata object (P180)

### ISSUE THREAD

**Issue by jluttine** [osmandapp/OsmAnd#13926]
# 🚀 feature request

### Description

Currently, OsmAnd shows photos that are explicitly listed in Wikidata. However, Wikimedia Commons contains a lot of photos that aren't explicitly listed on Wikidata side but rather marked as depicting Wikidata objects.

Here is one object (Siilinkari winter cafe) that I happened to work on today:

https://osmand.net/go?lat=61.51757&lon=23.75392&z=18

It has one image explicitly marked on Wikidata side, and that is shown by OsmAnd.

https://www.wikidata.org/wiki/Q62619389

Here is a query to Wikimedia Commons which lists all photos that are marked as depicting this particular Wikidata object:

https://w.wiki/4xDA

In this case, it lists two photos, that is, just one photo more. But there are many examples for which there might be zero or just one photo on Wikidata side although there can be many photos on Wikimedia Commons side marked depicting that object.

Note that Wikidata object key is all that is needed. The query on Wikimedia Commons side is based on that.

Also, on Wikimedia Commons side, it is extremely convenient to use this "Depicts" tag to list objects shown in the photo. So, the workflow on both sides is extremely convenient.

### Describe the solution you'd like

Query Wikimedia Commons for photos that are tagged as depicting the Wikidata object and show those photos in OsmAnd.

Wikimedia Commons has a property called "Prominent" which tells whether the tagged object is prominent in the photo. It seems that the query example I gave, shows only the "prominent" photos, not others. It might be nice if all photos were shown, but just sorted so that the "prominent" photos were shown first.

One benefit of this solution is that compared to, for instance, using Wikimedia Commons Categories, there's significantly less manual inputting of structural data on Wikimedia Commons side. It's very easy to just list all objects that are clearly visible in a photo, but figuring out what categories there exist or should exist and putting the photos to those categories (and creating new categories and managing their hierarchy) and then figuring out on OsmAnd side what Category/Categories should be searched for, it's a much bigger mess, with inferior result. Just find the photos that show the particular object, that's it.

**Comment by vshcherb** [comment]
Query:
```
SELECT ?file ?image WHERE {
  ?file wdt:P180 wd:Q62619389.
  ?file schema:url ?image.
}
```
Result:
```
[
{
 "file":"https://commons.wikimedia.org/entity/M980796",
 "image":"http://commons.wikimedia.org/wiki/Special:FilePath/Siilinkari.jpg"
},
{ 
 "file":"https://commons.wikimedia.org/entity/M115537432",
 "image":"http://commons.wikimedia.org/wiki/Special:FilePath/Siilinkari%20Tampere.jpg"
}]
```

**Comment by vshcherb** [comment]
This could be related to  https://github.com/osmandapp/OsmAnd/issues/12303 if 

- https://commons.wikimedia.org/wiki/File:Siilinkari.jpg, https://commons.wikimedia.org/wiki/File:Siilinkari_Tampere.jpg will be united to Wikimedia Commons category 
- And category link will be put in wikidata entity

**Comment by vshcherb** [comment]
To do: 
- General task: prepare data on the server side to easy retrieve data on client side and embed it in the maps
- Run query or parse (???) to get P180 data

**Comment by vshcherb** [comment]
- [ ] Update https://creator.osmand.net:8080/view/Wiki/job/Wiki_GenerateWikipediaMaps/ , https://creator.osmand.net:8080/view/Wiki/job/Wiki_GenerateWikivoyage/ to use /home/wiki/wikidata/commonswiki.sqlite
- [ ] Prepare timing and put in parameters description ```~h``` https://creator.osmand.net:8080/view/Wiki/job/Wiki_PrepareWikidata/build?delay=0sec
- [ ] Before Copy file (delete it) so server will hold temporary reference and check it works ? Restart prod server (by schedule ? ) or rename before it.
- [ ] Configure monthly schedule 
----------------------------------------
- [ ] Download / process delta dumps from wikidata

**Comment by vshcherb** [comment]
To developers on regular update:
- [ ] Jenkins Parameters (put ~h to understand timing in description): 
        - Wikidata: Update, Redownload, Do nothing -  Default Update
        - Download & Update OSM: true / false - Default true
        - Download & Reindex Commons wiki: true / false - Default true
        - Publish (Publish db to osmand.net) : true/ false- Default true
- [ ] Final file is sqlite: wikidata_commons_osm.sqlitedb. Schema
     - Table osm_entity (osm_id, osm_type, wikidata, wikipedia, wikimedia_commons, other-tags-json)
     - Table wiki_coords(id long, originalId text, lat double, lon double);
     - Commons images: common_depict(id long, depict_qid long, depict_type text);, .. .common_content(id long, name text, ns int);

**Comment by dpriskorn** [comment]
Hooray 🎉
I can't wait to test this out 🤩

**Comment by jluttine** [comment]
Big thanks!! :tada: I suppose this is now in OsmAnd 4.6.14? It seems like that, but at least one node isn't showing the photos for me in OsmAnd..

The node: https://www.openstreetmap.org/node/9578634049

The wikidata page: https://www.wikidata.org/wiki/Q111243500

The three photos: https://commons-query.wikimedia.org/#%23cache-control%3Ano-cache%0A%23defaultView%3AImageGrid%0ASELECT%20%3Ffile%20%3Fimage%20WHERE%20%7B%0A%20%20%3Ffile%20wdt%3AP180%20wd%3AQ111243500.%0A%20%20%3Ffile%20schema%3Aurl%20%3Fimage.%0A%7D

There are three photos but OsmAnd doesn't show any of those to me. Any ideas why?
