### ISSUE TITLE
Multitouch Zooming is jerky, when ending zoom (map moves although, when lifting one finger)

### ISSUE THREAD

**Issue by dennisguse** [osmandapp/Osmand#1393]
Zooming via Multitouch (two fingers) works quite well while in zoom mode.
However, getting out of the zoom mode (lifting one finger), the map quite frequently "jumps":
- either changing zoom level or
- shifting the map.

This also happens, when trying to lift both fingers simultanously - most probably one finger is slower...

I started investigating this issue and tracked it down to 
MultiTouchSupport:onTouchEvent() and OsmandMapTileView:onZoomEnded().

Issue #1126 might be related.

Device: Nexus 5, Android 5.1.1
OSMAnd+: 2.1.1 2015-05-20

**Comment by sedrubal** [comment]
I don't want to criticise you and you can estimate this better than me, but for UX this is quite important and not only `Nice to Have`... :wink:

**Comment by sonora** [comment]
Is this deprecated, I cannot seem to reproduce?

**Comment by dennisguse** [comment]
Still not fixed in 2.4.5 (todays version from Google Play store)

**Comment by vshcherb** [comment]
This issue is about continuous zoom i.e. have fractional zooms during zoom in/out. I guess it is not about animation to change zoom in animated way once you stop pinch/zoom gesture but it is about have the map at exactly zoom (fractional basically) as it the gestured was stopped

**Comment by polarbearing** [comment]
With2-finger-zooming, the map snaps to the next zoom level, but it does not move. Even if I lift one finger, it only snaps but does not move. 

When I double-tag somewhere on the screen, the map first centers this position, then zooms in one level. 

+/- buttons also work as expected. 

(BQ Aquaris X5 Plus, Android 6.0.1, current nightly Dec03)

**Comment by sonora** [comment]
Think this is finally investigated in #3319.
