### ISSUE TITLE
Track recording: Invalid duration, invalid start date

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#13945]
Many recorded tracks are shown with an invalid duration and an invalid start time:

![photo_2022-03-17_14-02-57](https://user-images.githubusercontent.com/1040784/158814464-fd2d3082-bd27-4f8b-ba65-d089b5f6ef4a.jpg)
![photo_2022-03-17_14-03-23](https://user-images.githubusercontent.com/1040784/158814466-37be26bb-3696-4212-8f3a-7b613fdcb490.jpg)

It looks like some of the `<time>` entries in the GPX file are invalid. For example:

```
      <trkpt lat="50.8693718" lon="14.296992">
        <ele>288.6</ele>
        <time>2022-03-13T09:33:23Z</time>
        <hdop>4.7</hdop>
        <extensions>
          <osmand:speed>1</osmand:speed>
        </extensions>
      </trkpt>
      <trkpt lat="50.8693764" lon="14.2970017">
        <ele>288.6</ele>
        <time>0000-03-13T09:11:26Z</time>
        <hdop>4.7</hdop>
        <extensions>
          <osmand:speed>1</osmand:speed>
        </extensions>
      </trkpt>
      <trkpt lat="50.8693807" lon="14.2970096">
        <ele>288.6</ele>
        <time>2022-03-13T09:11:27Z</time>
        <hdop>4.6</hdop>
        <extensions>
          <osmand:speed>1</osmand:speed>
        </extensions>
      </trkpt>
```

The second track point has an invalid time set, the year is zero. The same thing happened to multiple other track points.

OsmAnd 4.1.11 on Samsung Galaxy S9 with LineageOS 17.1 / Android 10.

**Comment by vshcherb** [comment]
Did you try to reimport track? Delete and import again?

**Comment by vshcherb** [comment]
There are no tracks attached, so it's not clear whether we can reproduce it or not.

**Comment by scaidermern** [comment]
This is one of the tracks: [2022-03-13_10-07_Sun.gpx.txt](https://github.com/osmandapp/OsmAnd/files/8308057/2022-03-13_10-07_Sun.gpx.txt)

This track was recorded by OsmAnd. So reimporting is not possible / won't fix the invalid time attributes.

**Comment by scaidermern** [comment]
The same happened again: 
[2022-05-07_17-11_Sat.gpx.txt](https://github.com/osmandapp/OsmAnd/files/8650750/2022-05-07_17-11_Sat.gpx.txt)

Most timestamps are correct (`2022-05-07T16:01:15Z` etc.). Some contain random errors, for example:
* `0000-05-07T15:39:25Z` (wrong year)
* `2022-01-07T15:42:22Z` (wrong month)
* `2022-05-00T15:34:27Z` (wrong day)
* `2022-05-07T00:41:01Z` (wrong hour)
* `2022-05-07T00:00:00Z` (wrong hour, minute and probably second)

**Comment by Chumva** [comment]
@scaidermern Please try to check new nightly build, this issue should be fixed

**Comment by scaidermern** [comment]
Thanks, I will. Unfortunately I have no idea how to reproduce this. This doesn't happen to all recorded tracks. But I will keep an eye on it :)
