### ISSUE TITLE
OSMAnd tries to route through a barrier

### ISSUE THREAD

**Issue by MTRNord** [osmandapp/OsmAnd#13941]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

car

### Start and end points

Start location (slightly modified for privacy reasons, but results in the same routing issues): https://www.openstreetmap.org/search?whereami=1&query=54.65469%2C9.40932#map=19/54.65469/9.40932
Target location: https://www.openstreetmap.org/search?whereami=1&query=54.76167%2C9.43046#map=18/54.76167/9.43046

#### Actual
![image](https://user-images.githubusercontent.com/1374914/158615078-3c6c45e8-932a-45d1-8ef1-f45a4fef26ef.png)

#### Expected

Use the way next to the area instead of trying to route through trees

### Is this a regression?

Not aware of it working

 Yes, the previous version in which this bug was not present was: ....

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

OsmAnd~ 4.1.11
</code></pre>

**Device and Android/iOS version:** One Plus 7 Pro, Android 10, Fdroid

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.
Deutschland Schleswig-Holstein (1.3.22) with recent hourly updates.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**

The right turn from the B200 is impossible as a) it is a motorway style road and b) it is a ridge and c) there are trees.

Correct would be to use the road there. It is marked as private because it is behind a big supermarket center, but it still should be routable I believe. Especially if that is the only way.

**Comment by vshcherb** [comment]
Target location is not located on the driving road, so OsmAnd stops routing in the middle of highway. I'm afraid this issue can't be fixed

**Comment by thompehw** [comment]
> Target location is not located on the driving road, so OsmAnd stops routing in the middle of highway. I'm afraid this issue can't be fixed

But for an average user who has placed the destination away from a road, if they are driving in an unknown area then the final *instruction* to e.g. turn right (with direction arrow shown) onto a road that does not exist can be very confusing.

Would it be possible to change how the final directions are announced so that the user knows when to stop the car? Before I understood OsmAnd's behaviour, I was in this situation myself and spent a stressful few minutes driving up and down looking for the imaginary turning!

**Comment by scaidermern** [comment]
I can even imagine a clear hint (e.g. via popup) that no road to the destination could be found and that the user needs to double-check the destination and the final navigation instructions. This could also help in various issues from #7520. Maybe show a hint when the destination is too far away from the nearest road (10m? 25m? 50m? I don't know).

**Comment by Lee-Carre** [comment]
The solution, here, is to tell OsmAnd that the (nearby) carpark is the destination.
