### ISSUE TITLE
Add routing option to avoid bridges

### ISSUE THREAD

**Issue by Atalanttore** [osmandapp/Osmand#1395]
Hi,

I would like a routing option to avoid bridges on windy and icy days.

Best Regards,
Ettore Atalan

**Comment by vshcherb** [comment]
It is possible to customize routing.xml yourself (https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml) and put it on sdcard.

**Comment by Atalanttore** [comment]
Thanks for the advice.

I've made the following insertions to routing.xml:
`<parameter id="avoid_bridges" name="Avoid bridges" description="Avoid bridges" type="boolean"/>`
`…`
`<select value="-1" t="bridge" v="yes">`
`			<if param="avoid_bridges"/>`

But: Should there be a minimum length limit for small bridges over ditches and drains?

Best Regards,
Ettore Atalan

**Comment by sonora** [comment]
No further action planed for now.
