### ISSUE TITLE
[routing] Router asks to leave main road and enter it just after 

### ISSUE THREAD

**Issue by letypequividelespoubelles** [osmandapp/OsmAnd#13955]
<# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Car profile.

### Start and end points

[Start and End point](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=45.8927%2C6.1111%3B45.8985%2C6.1070#map=16/45.8956/6.1093)

### Actual and expected routes
OSMAnd takes the same (wrong) route as OSRM, but it is expected to take [this bridge](https://www.openstreetmap.org/way/97414625). It's not a data issue, because Graphhoper has the right expected routing. 

## 🌍 Your Environment

**OsmAnd Version:**

4.1.11 from F-Droid

**Maps used (online or offline):**

Same issue with Osmand Live update and with last offline map.

**Comment by letypequividelespoubelles** [comment]
[OSMR issue](https://github.com/Project-OSRM/osrm-backend/issues/6221)

**Comment by scaidermern** [comment]
Maybe because https://www.openstreetmap.org/way/601521830 and https://www.openstreetmap.org/way/8407641 have no maxspeed set? Depending on the implicit maxspeed of the routing engine this route could appear faster than staying on the main road. On the other hand, driving through a roundabout is typically pretty slow...

**Comment by letypequividelespoubelles** [comment]
Hum, yes, maybe. I'll add speed limit next time I'll go there. But anyway, event without speed limit, it can't be faster to leave a highway to take a primary road, a roundabout, and then go back to the same highway after...

**Comment by letypequividelespoubelles** [comment]
mapping issue (no speed limit, and wrong tag : trunk instead of trunk_link).
