### ISSUE TITLE
Render fish pass

### ISSUE THREAD

**Issue by letypequividelespoubelles** [osmandapp/OsmAnd#13957]
# 🚀 feature request

### Description
Actually the [waterway=fish_pass](https://wiki.openstreetmap.org/wiki/Tag:waterway%3Dfish_pass) is render, only in the OSMAnd style, as a little blue line (smaller than waterway=stream, and without flow arrow). It's not render at all, neither in topo, nor in nautic map. 

### Describe the solution you'd like

Render fish pass as a stream with [this icon](https://en.wikipedia.org/wiki/Fish_ladder#/media/File:Ferc-fish_ladder.svg) for exemple. It's usefull, at least for topo, nautic, and OsmAnd style.

### Describe alternatives you've considered

None.

Thanks a lot for your amazing app.

**Comment by xmd5a2** [comment]
Icon on path added but only for OpenGL

**Comment by letypequividelespoubelles** [comment]
Wow, so fast. Thanks @xmd5a2
