### ISSUE TITLE
The button Without Underlay takes name of others underlays in Quick action button in Osmand 4.1.11

### ISSUE THREAD

**Issue by capta** [osmandapp/OsmAnd#13964]
### Description
In Osmand 4.1.11 I have preconfigured multiple underlayers in Quick action button to fast change underlayers and one "Without Underlayer".
When I select a layer the button Without Underlayer ("Sans sous-couche" in french in the screenshot) takes the same name than the selected underlayer.
![Screenshot_20220322-001017](https://user-images.githubusercontent.com/10539115/159379395-8a41415b-1808-4a3c-bcd6-f3188853a070.png)
![Screenshot_20220322-001048](https://user-images.githubusercontent.com/10539115/159379428-b1e7be9e-d265-44bd-afc0-64e2b13b71be.png)

### How to reproduce?
Install Osmand 4.1.11 and add multiple underlayers in Quick Action button and a button "Without underlayer". Then select an underlayer in Quick action button and the button "Without underlayer" will have the same name than the previously selected underlayer.

### Your Environment
OsmAnd Version:4.1.11
Android version:9
Device model:Blackview BV9600

**Comment by vshcherb** [comment]
It's probably correct or not? Actions work in a independent manner, once you've already selctted no underlay map, it displays name of the next map. Actually it should be '> Microsoft maps' displayed indicating it's not current map

**Comment by capta** [comment]
It seems that the "No underlay" action (on the screenshot "Sans sous-couche") works differently than all others underlays changing actions (I think it's not ok). In this example there is 3 buttons and only one underlay configured per button.
![Screenshot_20220325-084717](https://user-images.githubusercontent.com/10539115/160077541-2cde5a9e-1be2-4f0d-8b04-416376572ea5.png)
![Screenshot_20220325-082318](https://user-images.githubusercontent.com/10539115/160077809-6401c905-632a-4190-bcb7-91e9a512f139.png)
In the first screenshot if I choose for example OpenTopoMap the name of the button "No undelay"(sans sous-couche) changes to OpenTopoMap. I think it's not correct. The button No overlay may always stay the same and don't change name (and may function as all others underlays). 
![Screenshot_20220325-084738](https://user-images.githubusercontent.com/10539115/160078630-b6ffa093-fd75-4f49-b545-d8028ab587e7.png)

**Comment by capta** [comment]
Let's take an other example. Here the are 2 underlays configured :
No underlay
Microsoft Earth
![Screenshot_20220325-090530](https://user-images.githubusercontent.com/10539115/160080606-2bdbc75f-8266-4f12-9eda-95a7589dfddf.png)

If I use this button the underlay map change (it works) but the name of the action stays always Microsoft Earth. The name "No underlay" never appears. It is replaced by the name Microsoft Earth. I think it's not normal.

![Screenshot_20220325-090855](https://user-images.githubusercontent.com/10539115/160081472-f4054156-c7af-405a-99cb-558f18c0ad76.png)
![Screenshot_20220325-090924](https://user-images.githubusercontent.com/10539115/160081520-1ffadcd4-df7a-4c12-b729-ee3d5977ad10.png)

**Comment by vshcherb** [comment]
Fixed in nightly build

**Comment by miguelpeniche** [comment]
Hey @capta is there a way I can send you an email? Would really appreciate it. Cheers!
