### ISSUE TITLE
Android Auto: Crash during navigation by track

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#13971]
### Description

User case:
The problem arises only when using android auto and when I am trying to navigate along an imported track. Shortly after starting off I get an "encountered unexpected error" message requiring me to close the app. Sometimes I also get the message "native library not supported on this device". The app has no problem following the track if it is operating standalone, only in android auto. 

Device : oriole
Brand : google
Model : Pixel 6
Product : oriole
Build : SQ1D.220205.004
Version : 12
App Version : OsmAnd
Apk Version : 4.1.11 421

[exception (6).log](https://github.com/osmandapp/OsmAnd/files/8325649/exception.6.log)

**Comment by sprreddy1** [comment]
Glad to see the issue being addressed. Just wondering when will it be available for an update?

**Comment by Chumva** [comment]
@sprreddy1 Fix will be available in the next release and nightly builds.

**Comment by vshcherb** [comment]
Android Auto only available in Betas yes should be testable
