### ISSUE TITLE
Incorrect rejoining of GPX track

### ISSUE THREAD

**Issue by Goodingn** [osmandapp/Osmand#1397]
When using a GPX track to navigate, if I leave the track, then rejoin it later, the directions send me the wrong direction on the track, briefly, before continuing correctly.

It's like the navigation is selecting a node too far back round the GPX to continue upon (i.e. back up the GPX), which sends the turn 180 degrees to the wrong direction.
![screenshot_2015-06-24-17-43-22](https://cloud.githubusercontent.com/assets/13037960/8353389/3bb2639a-1b35-11e5-817e-47f2e22ffd17.png)

**Comment by vshcherb** [comment]
We would need more information how to reproduce that issue

**Comment by Goodingn** [comment]
I've constructed a Route and recorded a Ride.  The Route can be followed with Navigation, the Ride can be simulated with the Developer Tools.

The problem isn't as I originally expected and this short artificial route and ride are probably amplifying the issue.

When starting this Test Ride (hopefully a similar action to driving off route) the navigation briefly draws a straight line from the start of the Ride, to the nearest point on the Route.  The navigation then navigates along the road to the junction with the route, then navigates left, back up the route, to that nearest point, then turns 180 and goes forward along the route, past the junction and continues.

When the navigation simulation gets to the junction, the left turn, the navigation back and forth to the junction immediately disappears and continues to the right.

I'd expect the routing to notice that the generated navigation is entering the GPX route and take up the navigation from there - a right turn - instead of doggedly going back to that 'fixed' nearest point on the route.

[Test ride.gpx.txt](https://github.com/osmandapp/Osmand/files/37766/Test.ride.gpx.txt)
[Test route.gpx.txt](https://github.com/osmandapp/Osmand/files/37767/Test.route.gpx.txt)

**Comment by vshcherb** [comment]
This is considered to be a minor issue based on the rejoining issue. There are multiple reasons it could happen and mainly it is related that OSM geometry (OsmAnd maps) is not exact track geometry and it is very hard problem to solve. We hope to fix more severe cases in future and reference this one.

**Comment by sonora** [comment]
I had never read this issue here, but this is identical to my **observation (5)** in #2591, and the reason why this happens I documented in my comment https://github.com/osmandapp/Osmand/issues/2591#issuecomment-239330589 there: It is intrinsic to our mechanism of how we determine where to re-join the track (we determine the closest point, which is the one you are then first routed to, even if it is "in the wrong direction"). Hard to find an equally simple better strategy.
