### ISSUE TITLE
Sunrise and sunset on widgets

### ISSUE THREAD

**Issue by davidesouza** [osmandapp/OsmAnd#13982]
Hello!
<img src="https://user-images.githubusercontent.com/102357171/160101644-b0d54c51-9631-4c96-bcfa-3f218afd5ebf.jpg"  width="300" height="auto"/> 

I'm very satisfied with OsmAnd's functionality, however one would like it to display sunrise and sunset times in the side widgets; so I wouldn't need to switch it with other guidance apps as often.

**Comment by rschmidm** [comment]
I suggest to include two data points in the widget: 
- relative: "time until sunset / sunrise" (from my point of view more important)
- absolute: "next sunset/sunrise"
Locus Maps has a good implementation of this:
(sunset icon) "8:22 (21:02)"

Especially the relative setting is very useful on bike trips: E.g. when you know you only have 45 minutes to sunset and still so much distance to go. 

This also addresses the concern to show static data in the widget, as mentioned in #14496.

**Comment by dmpr0** [comment]
<table style="width:100%">
  <tr>
    <th>Widget group</th>
    <th>Widget info</th>
    <th>Widget info</th>
    <th>Left panel</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/197992273-c9d0000b-19f3-422b-8f44-bb934904e5f2.png"  width="170" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/197992186-5ae98b73-7ef8-45d8-8c57-6dc8bf8c57ab.png"  width="170" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/197992185-45d7131e-d1e4-45d9-8f44-368c8c2450ab.png"  width="170" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/197992099-2495a71f-059e-4b4b-8e4c-bdcc1b467cc5.png"  width="170" height="auto"/> </td>
  </tr>
</table>   

<table style="width:100%">
  <tr>
    <th colspan=2>Sunrise – Settings</th>
    <th colspan=2>Sunset – Settings</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/197993120-b28be37d-38aa-44b1-a7d1-f97dc6ac9005.png"  width="170" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/197993116-902ac9a1-97f9-4a5c-b943-2340fed4248f.png"  width="170" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/197993342-59f47058-00ac-40d7-bd7b-73f2895396a2.png"  width="170" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/197993339-834f4cd7-063c-441f-88dc-e9880ca1b954.png"  width="170" height="auto"/> </td>
  </tr>
</table>

**Comment by nazar-kutz** [comment]
**Pull Request**
https://github.com/osmandapp/OsmAnd/pull/15661

**Comment by vshcherb** [comment]
# Review

- [ ] Sunset / sunrise should show from map screen center

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.3.0#13964mqta, released: 2022-11-22
Information on widgets is updated after reopening the application

- [ ]  It is expected that the sunrise data will be updated in real-time as it happens in the weather widgets


https://user-images.githubusercontent.com/104760013/203282227-ff7fc7f5-2cb1-4b09-98e0-0697b35888ad.mp4

**Comment by EugeneZmeuk** [comment]
https://osmand.net/docs/user/widgets/info-widgets

**Comment by DmitryAlexei** [comment]
https://docs.osmand.net/docs/user/widgets/info-widgets#-weather-widgets
