### ISSUE TITLE
[Feature Request] OpenStreetMap editing source

### ISSUE THREAD

**Issue by Sorunome** [osmandapp/OsmAnd#13980]
# 🚀 feature request

### Description

Allow specifying the source of changesets to upload and supply the `imagery_used` tag if you use online maps such as the bing areal imagery to more precisely specify where exactly a new POI is.

### Describe the solution you'd like

Perhaps on the upload screen add checkboxes for sources like survey or arial imagery?

**Comment by scaidermern** [comment]
Specifying a source has already been requested by #5852.
