### ISSUE TITLE
Range values of "Color by slope" don't make sense

### ISSUE THREAD

**Issue by YoBii** [osmandapp/OsmAnd#13985]
### Description
This is not a bug but more of a design mistake, I guess..?
Having the scale go from -25 to 100% is illogical. The steepest road in the world has a gradient of 37%. So anything above 40% does not occur in the real world. For hiking it might be more but I'd doubt you commonly come across paths with more than 50% gradient. Correct me if I'm wrong but at that point it's more actual climbing than hiking, is it not?

In it's current state if you're not in overly hilly areas the track will be painted mostly white with the slightest touches of green and yellow here and there. For cycling there is basically no benefit to this feature as you won't be able to make out such slight changes of color on your display when outside. 
Especially when cycling something like 5-10% would already be considered steep but the app will display a light yellow. Everything above 20-25% would be extremely steep (like deep purple steep). For cars everything above 30% would also be deep purple steep.

Just moving the range limits to e.g. -15% to 30% would make this features actually usable as the colors would be more intense and you could see the gradients on the map. 

IMO a quick fix as in changing the hardcoded values to achieve proper usability of this feature is the preferable solution before thinking about adding new features that require several changes at multiple locations like making the color scale limits customizable. Although that would be very nice and appropriate for any use case one can think of.

### How to reproduce?
Default behavior. Apply a slope color type to a track in the design/theming section of the track bottom menu e.g. "My places" -> select a track -> select color palette -> slope

### Your Environment
OsmAnd Version: 4.1.11
Android/iOS version: Android 10
Device model: irrelevant

**Comment by YoBii** [comment]
This could be considered a duplicate of #12954 but that issue has already been added to a milestone and there someone explicitly asked for a new feature of having the limits customizable.

**Comment by scaidermern** [comment]
There is a new coloring scheme suggested in #11775 / #12336. It makes slope changes in the lower range more clear. Maybe there is additional room for improvement.

**Comment by YoBii** [comment]
I'll go ahead and close this as it's a duplicate of the tickets mentioned above. Thanks @scaidermern
