### ISSUE TITLE
Auto screen on doesn't work if voice navigation is muted

### ISSUE THREAD

**Issue by Goodingn** [osmandapp/Osmand#1398]
I'd like the auto screen on feature to work with or without the voice navigation.  I tend to not have the voice turned on, but would like the screen to come on when approaching a navigation point.

**Comment by breversa** [comment]
So THAT'S why I thought that feature was broken ! Thanks for that info, Goodingn. I henceforth support your suggestion, as I don't use voice navigation myself either (or only seldom).

**Comment by gunterloos** [comment]
Is this (no auto screen on when no voice navigation) confirmed behaviour? I'll check that out later on - seems incredible. Anyone?

**Comment by breversa** [comment]
I confirm it doesn't work with voice off.

I'll give another try with voice on to confirm.

**Comment by vshcherb** [comment]
Fixed
