### ISSUE TITLE
[Routing] Failed to calculate a route

### ISSUE THREAD

**Issue by lluni** [osmandapp/OsmAnd#13984]
# 🐞 Routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Car, default settings

### Start and end points

Starting point: [`137, Engersche Straße, Schildesche, Bielefeld`](https://www.openstreetmap.org/way/207950632)
End point: [`SchücoArena, 31a, Melanchthonstraße, Mitte, Bielefeld`](https://www.openstreetmap.org/relation/572530)
Route: [Link](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=52.0591%2C8.5543%3B52.0320%2C8.5158#map=14/52.0444/8.5343)

### Actual and expected routes

Expected: Calculating a route successfully.

Actual: Two error toast messages after each other with a failed route calculation.
First toast: `Fast route calculation failed (length=1; index=1), fallback to slow calculation.`.
Second toast: `Could not calculate route.: length=1; index=1`.

### Is this a regression?

 I have not tried other (previous) versions.

## 🌍 Your Environment

**OsmAnd Version:**
<pre><code>4.1.11 (F-Droid)</code></pre>

**Device and Android/iOS version:**
<pre><code>OnePlus 7 Pro, Android 10</code></pre>

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.
Germany, North Rhine-Westphalia (Standard map), 01.03.2022

- [ ] Online (tile / raster) maps 

**Anything else relevant?**

This bug seems to occur for every starting point on L557 with the house number 137 and above / until the road ends. For every starting point with house number 135 and below it seems to calculate a route successfully.

**Comment by vshcherb** [comment]
Should be fixed with 4.2  (available in the nightly already)
![Screen Shot 2022-03-28 at 17 39 58](https://user-images.githubusercontent.com/1042025/160435511-52be8ba8-1b78-4a1c-bc89-4804c6ee8750.png)
