### ISSUE TITLE
Potential bot accounts in OSM BTC

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#13995]
From request to OsmAnd support team:

I have noticed strange activity from some mappers that are part in your programme. They are creating lots of very short ways and then they delete them. Their goal is to get more changes so that they can get more BTC from your fund. It's easy to identify them because they have almost 50/50 ratio on created and deleted elements in HDYC.

Can you please take some action and create an internal tool that checks mapper's HDYC and sends the account for manual review if the deleted vs created elements is around 50/50 before a payout is
made?

Please check these accounts: 
cyhasucu
cuzibelu
rovegoje
lekkituspe
wikyna
kupyhajy
suwajy
firuxubo
virejagy
qoqeda
nefeziwi
pimogyqo
behekyru
vajihuho
cojami
borakure
kuloge
wutukesy
dynydimi
zyludyje
nasuqa
puzomusy
viwunyry
bacyxazi
keveni
seraqi
zanumedo
vufegelu
xydefo
ferusena
calepu
morkigur
vilmibulto
lofyin
likneja
rorkitus
kudrev
begniz
bidray
viknak
hortoj
jiklorti
gaugaut
wilfangir
kirmyl
jamaica5
wilsam
paper1992
c1o2m3b4a

**Comment by tradavyvy** [comment]
If this turns out to be the case
My compliments for great detective work anastasiia936!

**Comment by jfburke3** [comment]
Shouldn't this be reported to the OSM DWG, too?  If they are bot accounts, the the DWG will be able to disable them.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-tools/blob/master/db/sql_changeset_schema#L48

**Comment by alisa911** [comment]
https://github.com/osmandapp/osmandapp.github.io/pull/198
https://github.com/osmandapp/OsmAnd-tools/pull/474/files

**Comment by Dimitar5555** [comment]
> Shouldn't this be reported to the OSM DWG, too? If they are bot accounts, the the DWG will be able to disable them.

I've reported them to the DWG at the same time that I reported them to the OsmAnd team. As far as I know the DWG hasn't blocked anyone since they are not active currently and blocking them would be counter productive since the creation of new accounts is too easy.

**Comment by Dimitar5555** [comment]
These account most likely share a common script for creating changesets. They can be easily found by searching for changesets with `comment=modify road` and with a flag `mass deletion`. See [OsmCha](https://osmcha.org/?filters=%7B%22date__gte%22%3A%5B%7B%22label%22%3A%222022-04-01%22%2C%22value%22%3A%222022-04-01%22%7D%5D%2C%22reasons%22%3A%5B%7B%22label%22%3A%22mass%20deletion%22%2C%22value%22%3A3%7D%5D%2C%22comment%22%3A%5B%7B%22label%22%3A%22modify%20road%22%2C%22value%22%3A%22modify%20road%22%7D%5D%7D).

**Comment by alisa911** [comment]
All accounts that were mentioned in this task have been deleted.
