### ISSUE TITLE
online photos don't show up if mapillary is disabled even though the images aren't from mapillary

### ISSUE THREAD

**Issue by basings** [osmandapp/OsmAnd#13996]
### Description

Online photos don't show up if mapillary is disabled even though the images aren't from mapillary.

### How to reproduce?

Disable mapillary, go to a POI with a known image that isn't cached locally and click on it.

### Your Environment
OsmAnd Version: 4.1.11

**Comment by nazar-kutz** [comment]
Hello @basings, can you report whether this bug still reproduceable and provide links or coordinates of the points with which the problem occurs.

Also, please write from which source the photos should be displayed. For example, Wikipedia or Wikipedia Commons or something else.

I tried to reproduce this bug with disabled mapillary and a point that includes Wikipedia image, but image was downloaded and displayed fine.

**Comment by basings** [comment]
Hi @nazar-kutz,

It is still reproducible. 

Bourbaki-Denkmal Bernrain
Bernrainstrasse (Bernegg) 69, Kreuzlingen
Location: geo:47.63745,9.15643?z=20
https://osmand.net/go?lat=47.63745&lon=9.15643&z=20

This is a random website "memorialgenweb.org".
Images from wikimedia are shown. The same problem occurs with an image from imgur.com.

**Comment by vshcherb** [comment]
Online photos should be displayed if Mapillary is disabled. These features are not connected to each other
