### ISSUE TITLE
Screen power profile

### ISSUE THREAD

**Issue by Goodingn** [osmandapp/Osmand#1399]
Since there's a auto screen on feature, should there not be an accompanying screen 'off' feature?  Power saving between navigation points.

Choice of screen on full, screen on with dimming and default Android screen timeout with screen unlock?

Otherwise you have to keep turning the screen off all the time.

**Comment by breversa** [comment]
I was about to suggest a screen dimming option in additiont to constant screen-on, and screen-on at new direction. Glad I'm not the only one to think of it. :-)

**Comment by vshcherb** [comment]
Dimming is not technically possible but that's doable manually dim before you start navgiation.

**Comment by breversa** [comment]
Well, the idea is to light up the screen when approaching a navigation point, then dim it down afterwards (of course, if it's impossible, that's too bad.).
Dimming the screen before would defeat that.

Or did I understand you wrong ?

**Comment by Goodingn** [comment]
I'm not talking about dimming the screen as per the auto brightness apps, I'm talking about a screen power profile.  Dim Wake Lock rings a bell, from other apps?

I've any number of outdoor GPS recording apps that have the option to a) keep screen on (default position for OSMAND that I'd like the option to change from), b) allow the screen to go off/lock after a timeout as per default Android usage, c) allow the screen to go off (still after default Android timeout) but not lock, d) allow the screen to dim after Android timeout, but not turn screen off, or lock- this dimming is still a system thing that happens after the timeout (you usually see it on your phone just before the screen goes off to lock after the timeout), not something you have to technically 'do'.  I'd like as many of these options available to me as possible in OSMAnd.

For the timeouts to work correctly, I'd expect (as per other apps) when there's something happening, like a navigation point, for the app to reset the screen timeout, so if my screen is set to lock after 2 mins for example, the screen would only go off if 2 mins had passed since the last navigation point.

Without this option for the screen to go off, what's the point of the screen coming back on option that is already in OSMAnd?  This would seem the obvious thing to do to accompany the screen on option, to power save the screen between navigation points?

Cheers,

**Comment by breversa** [comment]
@Goodingn :
Have you tried the auto-screen on yet (for the moment, it only works when voice guidance is on) ?

It works like this :
- Set your phone to turn off screen after a while.
- In OsmAnd settings, activate the auto-screen on (in later Android versions, an extra system authorization step is required to allow OsmAnd to control the screen).
- Set a navigation route.
- Set your device on your dashboard.
- Start driving.
- After the first navigation point, your screen should turn off and/or lock according to your system settings, unless you met another navigation point before.
- When you approach a navigation point, your screen should turn on, then off after the point.

If you try to manually turn on your screen and switch to another app/home screen, you may have to unlock your device, as (someone please correct me if I'm wrong) OsmAnd simply "paints" over the lockscreen. It does not prevent the screen to lock.

**Comment by breversa** [comment]
So basically, your options A and B already exist.
Option C exists if you disable screen lock (but I'm pretty sure you don't want that).

**Comment by Goodingn** [comment]
What you're describing is what I'm after.  I logged an Issue, now reportedly fixed, about the disabled voice navigation not turning the screen on.

Given your experiences I'll try turning voice on and see if the screen does go off ok and see what happens to the lock when it comes back on.

Option C in other apps tends to work in an app specific way.  You can turn the screen on and off at will without the lock screen coming up, but as soon as you attempt to switch to another app, the lock appears.  Option C is therefore ideal.

I think you'd like the weird painting issue to go, and work like Option C, but with the option to have Option D?  It is a very very dark dim though.  Or, the hitherto described technically infeasible, Option E where OSMAnd reduces the screen brightness?  I've seen auto brightness apps to this and I think Google Maps' Navigation does this too.

**Comment by breversa** [comment]
> Option C in other apps tends to work in an app specific way. You can turn the screen on and off at will without the lock screen coming up, but as soon as you attempt to switch to another app, the lock appears. 

My bad, I think I did not undertand what you meant. That's precisely what happens in OsmAnd if you set up the "turn screen on" option. :-)

> I think you'd like the weird painting issue to go, and work like Option C, but with the option to have Option D? It is a very very dark dim though. Or, the hitherto described technically infeasible, Option E where OSMAnd reduces the screen brightness? I've seen auto brightness apps to this and I think Google Maps' Navigation does this too.

I may have been misunderstood here : when I talk about "painting", I mean that OsmAnd is display over/in place of the lockscreen. Pretty much like a fullscreen lockscreen widget. It's perfectly fine to me.

My *only* feature request/suggestion is to have the screen dim instead of completely turning off between navigation points. That's all.

**Comment by Goodingn** [comment]
OK, I've logged this as two new issues.

One is that the screen turning off isn't working, due to losing Device Administrator access: https://github.com/osmandapp/Osmand/issues/1860

And I've logged one for using standard Android screen powersaving, including dimming: https://github.com/osmandapp/Osmand/issues/1861
