### ISSUE TITLE
Mock GPS provider no longer working

### ISSUE THREAD

**Issue by machello** [osmandapp/OsmAnd#14001]
### Description
I use my mobile with Osmand+ in combination with an external BT gps device (Qstarz 1000XT and the Bluetooth GPS app. Done this for years now, with several devices. Worked perfectly, but all of sudden this no longer works. Not sure with which version of Osmand+ the problem started.
BTW, if I check the same setup with Google Maps it works fine.

### How to reproduce?
Enable Mock GPS provider. Install Bluetooth GPS or the like. Connect Bluetooth GPS with external GPS device. Tap location button in Osmand.

### Your Environment
OsmAnd Version: 4.1.11 (Osmand+)
Android/iOS version: tested with Android 6 and 9
Device model:

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by machello** [comment]
Thanks! Just tried that nightly build, changed location source to Android API and it works again!

Any idea when this will be available for the paid version?

**Comment by admash** [comment]
The Location Source setting appears to no longer be available on the nightly builds.
