### ISSUE TITLE
Wikipedia article not showing up

### ISSUE THREAD

**Issue by hamlet** [osmandapp/OsmAnd#14016]
Hi.

I've noticed that some wikipedia articles are not showing up in OsmAnd. Either through "Wikipedia articles nearby" or through search.

For example this [one](https://fr.wikipedia.org/w/index.php?title=Dolmens_de_Kerroyal). It was created on 2021/10/16, my downloaded wikipedia file in OsmAnd is marked as 2022/01/22.

The german version is showing up though, but it's much older.

Is there anything wrong with the coordinates on this article, or is the update delay much longer than I expect ?

Best regards.

**Comment by vshcherb** [comment]
Indeed french article is missing by unknown reason but german article is present - https://www.wikidata.org/wiki/Q51070901

**Comment by hamlet** [comment]
Thanks, I recall that it's not first time I found a similar problem, I will try to record more examples.

**Comment by Dima-1** [comment]
Issue not reproduced now
