### ISSUE TITLE
Incorrect route time displayed.

### ISSUE THREAD

**Issue by Goodingn** [osmandapp/Osmand#1401]
When a route is calculated, the little message that tells you so has the correct miles, but the time it gives is way over.  The standard information on the screen is correct of course.

**Comment by sonora** [comment]
This may be a misunderstanding. The message specifies the travel time forcast, not the arrival time.

Please note that on the map screen widget (top right corner) tapping on the travel time widget toggles between the travel and the arrival time, but the text message upon route (re-) calculation to my knowledge is always the travel time needed.

**Comment by Goodingn** [comment]
No- no misunderstanding, it doesn't tally with the trip forecast time.

I did notice that it did once show, in mm:ss format, the same as the forecast time (the forecast time is in hh:mm format) and I thought that the formatting was the discrepancy, but as that trip progressed and as I diverted from the route and the route recalculated, it was then different to the forecast time.

I've just tried a couple of things now.  I got it to calculate a route, and it showed the correct time, I added a waypoint, then the route recalculated and then showed an incorrect time.
![screenshot_2015-06-25-13-30-04](https://cloud.githubusercontent.com/assets/13037960/8354303/faa32736-1b3e-11e5-9f87-d1898ad97251.png)

**Comment by sonora** [comment]
I haven't taken the time to check the code, but it sounds like our widget simply displays the time to the next waypoint (and to destination only if no more interim waypoints are specified)?

**Comment by Goodingn** [comment]
If it were true that the toast message showed time to next waypoint, the time would be less than the total trip time from the top dashboard- the screenshot clearly shows this not to be true.  Also, the waypoint was just to test/demo the issue, it happens all the time when deviating from the route.

**Comment by vshcherb** [comment]
If development plugin is enabled then this time is "internal time" we use for debugging purposes. Since 2.1 we fixed and without plugin, it shows the same time. Please let me know if it is not a case.
