### ISSUE TITLE
Profiles: color of the icons are often not correct, all have the same color (IOS)

### ISSUE THREAD

**Issue by clwacker** [osmandapp/OsmAnd#14019]
The colors of the profile icons are not always represented correctly on IOS. By clicking on an icon to change profiles the colors are very often changed and all profiles have the same color.
I attach 2 screenshots, one with the correct colors and the second when the colors are not correct

OsmAnd Version: 4.1.1
iOS version: 15.4.1
Device model: iPhone 13 Pro
![OsmAnd-profile_colors](https://user-images.githubusercontent.com/97670456/161435636-9f2dcda1-b8cc-4975-a2d9-abd2cfa03008.jpg)

**Comment by dmpr0** [comment]
Hello! Thank you for the feedback. 
The issue is fixed, you can test it, by installing the TestFlight version https://testflight.apple.com/join/7poGNCKy.
