### ISSUE TITLE
Searching for an address when launched from another app

### ISSUE THREAD

**Issue by Goodingn** [osmandapp/Osmand#1402]
When I hit Navigate from any app that passes on the address details (not the Long/Lat), Osmand just sits there searching, eating up memory (140MB and beyond), other apps get closed and eventually Osmand itself closes.  Never once got a result out of thise.

**Comment by breversa** [comment]
Same here.
It appears that OsmAnd expects the address to follow the US (?) format, i.e. :
[Street number] [Street name] [City] [City code] [State code] [Country]

… and anything else that does not match that scheme returns no result.

**Comment by 9662** [comment]
Ah, I've been intending to report this bug for ages. Neither versions 1.x nor version 2.1.0 give any result other than what @Goodingn describes.

**Comment by vshcherb** [comment]
As it is described that functionality should be better removed completely to not raise false expectation. It was merged into a product by mistake and now pretends it is working. The biggest problem of that function, that search now is working contextually and inlined in the map itself, if you have 20 maps it works 20 times more, which is completely unacceptable. So we need to find another solution.

For now that search is disabled and will output nothing.
