### ISSUE TITLE
Possibility to hide military area

### ISSUE THREAD

**Issue by miramikes** [osmandapp/OsmAnd#14022]
Hello,
It would be great to have possibility to hide military area.
In case I met there is military area which is open to public for most of the year, but red diagonal lines makes almost impossible read the map
Thank you
mira![military.png](https://user-images.githubusercontent.com/623412/161479373-45c3f86d-dc17-4ae8-8fba-c981a57f191c.png)

**Comment by Powersource** [comment]
How do I do this?

**Comment by Powersource** [comment]
Ah at the bottom on Configure map there's a Hide option.
