### ISSUE TITLE
Internal library is not supported on Samsung s21

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#14038]
### Description
From the support request: I regularly get the message "internal library is not supported", even if I don't use OsmAnd at all. Reinstalling doesn't help.
Device : t2s
Brand : samsung
Model : SM-G996B
Product : t2sxeea
Build : SP1A.210812.016.G996BXXU4CVC4
Version : 12
App Version : OsmAnd
Apk Version : 4.1.11 421

[logcat (10).log](https://github.com/osmandapp/OsmAnd/files/8440462/logcat.10.log).

**Comment by vshcherb** [comment]
The bug is not reproducible on S21 Ultra with Android 12, probably reinstall could help. Installation from old releases could also show if it stopped working for all releases or only for latest .
https://download.osmand.net/releases/
