### ISSUE TITLE
Allow the creation of subfolders for storing tracks

### ISSUE THREAD

**Issue by Gbernardy** [osmandapp/OsmAnd#14037]
# 🚀 feature request

### Description
Allow the creation of subfolders for storing tracks

User Folder
____User SubFolder
________User SubFolder
User Folder
User Folder
____User SubFolder
User Folder
____User SubFolder
_________User SubFolder
User Folder
____User SubFolder
....
....
....

**Comment by mariush444** [comment]
easiest method is to create folders/subfolders via file manager.
So probably your expectations is about osmand UI.
It is possible in UI but is not so easy.
When you import you can scoose where to import and then it is option "add new folder".
For the  already existing tracks you have to choose "save as new track" and then "add new folder".

**Comment by Gbernardy** [comment]
> easiest method is to create folders/subfolders via file manager. So probably your expectations is about osmand UI. It is possible in UI but is not so easy. When you import you can scoose where to import and then it is option "add new folder". For the already existing tracks you have to choose "save as new track" and then "add new folder".

Even if I create them with the file manager ... then with OsmAnd I don't see them ... and therefore they cannot be used to archive the tracks.

This function (subfolder management) is very useful for cycling and running profiles that use OsmAnd mainly with gpx tracks specially designed to follow a predefined path.

**Comment by Gbernardy** [comment]
can be merged with issue #13770

**Comment by mariush444** [comment]
![tracks](https://user-images.githubusercontent.com/66887280/162453253-55fbd9e7-adca-40f7-af91-595e97bebffd.jpg)

**Comment by mariush444** [comment]
![tracks2](https://user-images.githubusercontent.com/66887280/162454000-9bb945a3-9fbe-44db-8b70-298e8e53a483.jpg)

**Comment by Gbernardy** [comment]
View user folder with  file manager

![IMG_20220408_162225](https://user-images.githubusercontent.com/99968793/162456751-4f28d547-3047-46f5-90cf-4f0a1cb6b3da.jpg)

![IMG_20220408_162310](https://user-images.githubusercontent.com/99968793/162456878-061c5fe8-1b22-4b4e-a520-64ec6b1bf3d1.jpg)

View user folder with OsmAnd.
Item folder "SubAsolo" NOT not displayed

![IMG_20220408_162712](https://user-images.githubusercontent.com/99968793/162457010-f695e874-b466-4346-bdce-4863bd6bc0e6.jpg)

**Comment by mariush444** [comment]
hmmm... I have Android 11 and osmand 4.1.11
what is your?
As you see I have folder 4x4 and 3 subfolders inside the 4x4.
Every folder\subfolder has own separated gpx tracks.

**Comment by Gbernardy** [comment]
Android 11 and osmand 4.1.11 ...

In osmand I didn't see any parameters for the subfolders 🤔 ...

**Comment by mariush444** [comment]
some noticed...
1. subfolder shouldn't be empty. It will be not shown in this case.
2. Are you sure that folder that you use (via file manager) is the same folder that is used by osmand?
Can you verify osmand "Settings -> osmand settings -> Data storage folder" ?
3. If you want to create subfolder using UI then you have to use a trick.
When you use "Add new folder" or "change folder" in osmand during editing/adding track then specify
Asolo/SubAsolo

**Comment by Gbernardy** [comment]
> alcuni se ne sono accorti...
> 
> 1. la sottocartella non dovrebbe essere vuota. Non verrà mostrato in questo caso.
> 2. Sei sicuro che la cartella che usi (tramite file manager) sia la stessa cartella utilizzata da osmand? 
>    Puoi verificare osmand "Impostazioni -> Impostazioni osmand -> Cartella di archiviazione dati"?
> 3. Se vuoi creare una sottocartella usando l'interfaccia utente, devi usare un trucco. 
>    Quando usi "Aggiungi nuova cartella" o "cambia cartella" in osmand durante la modifica/l'aggiunta di una traccia, specifica 
>    Asolo/SubAsolo

**Comment by Gbernardy** [comment]
The subfolder was empty ... tried with the "move" function, in this case the subfolder is displayed even if empty and I can move the tracks to the subfolder.

![IMG_20220409_151121](https://user-images.githubusercontent.com/99968793/162575571-a12e6cd0-b2ae-43bc-9b16-ffadd76a1379.jpg)

But this is like having additional folders, that is, I see the subfolders and manage them as if they were folders ... anyway thanks for your valuable suggestions.

**Comment by Gbernardy** [comment]
issue #13816 can be merged with this issue

**Comment by XandrexOSM** [comment]
> Even if I create them with the file manager ... then with OsmAnd I don't see them ... and therefore they cannot be used to archive the tracks.

Hello, using your file manager, you should be able to tell it to open the file in OSMand directly, this workaround should provide you with the basic functionnality.

**Comment by vshcherb** [comment]
You create subfolder by Select Track -> 'Move to Folder' -> Create folder -> give a name like 'Folder/Subfolder'.

**Comment by Gbernardy** [comment]
But this is like having additional folders, that is, I see the subfolders and manage them as if they were folders ... instead I should see the subfolders only when I open the corresponding folder ...

**Comment by Gbernardy** [comment]
But the issues #13770 and  #13816 closed those too?
