### ISSUE TITLE
Online/Raster/Tiles Maps shown with too low resolution

### ISSUE THREAD

**Issue by trapicki** [osmandapp/OsmAnd#14035]
### Description
Since upgrading to OsmAnd 4.1 (Android) [online (raster, tiles) maps](https://docs.osmand.net/en/main@latest/osmand/map/raster-maps) look bad. They look like they are from one or two zoom levels less: coarse, grainy, with artefacts, and too low details, the display resolution is not nearly used reasonably. I compared them to the web views of the same maps, and the difference is baffling - see attached examples.

I did not notice the problem for sure in 3.7, but I'm not sure if I had a version in between.

### How to reproduce?

- Use OsmAnd Android. 
- Enable the Extension "Online Maps (Tiles or Raster Maps)"
- Set a online map in the map configuration as main map or as background map
- Compare with your browser display of the same source.

### Your Environment
OsmAnd Version: OsmAnd~ 4.1.11 via F-Droid
Android/iOS version: 11 2021-06-01
Device model: Samsung Galaxy M12

**Maps used (online or offline):**   

- Microsoft Earth
- basemap.at (AT)

![Screenshot_20220406-140532_OsmAnd~](https://user-images.githubusercontent.com/1251121/161995932-9c082f71-b61c-41e2-a142-066569dfe50f.jpg)
Vienna Burgring 7 with OsmAnd using _basemap.at (AT)_

![Screenshot_20220406-140537_Firefox](https://user-images.githubusercontent.com/1251121/161997252-f5701022-1233-4130-8a84-93f65fe0c2fc.jpg)
Vienna Burgring 7 on _basemap.at_ using the official web viewer [geoland.at]
(https://www.geoland.at/webgisviewer/geoland/map/Geoland_Viewer/Geoland?marker={x:1821244,y:6140958,srs:3857}&basemap=basemap)

![Screenshot_20220406-160501_OsmAnd~](https://user-images.githubusercontent.com/1251121/162002603-e9013823-0abe-4256-88ab-2e7318ae185e.jpg)
Vienna Burgring 7 with OsmAnd using _Microsoft Earth_

![Screenshot_20220406-160445_Firefox](https://user-images.githubusercontent.com/1251121/161998262-8fe8e300-1128-4579-9430-c801fae033d1.jpg)Vienna Burgring 7 with Firefox (Desktop mode!) [Bing Maps using _Microsoft Earth_](https://www.bing.com/maps?v=2&cp=48.204582~16.360513&style=h&lvl=15&sp=Point.48.204582_16.360513)

**Comment by mariush444** [comment]
Can you verify profile settings -> configure map -> text size ?

I have similar problems when text size is over 100% but my issue was closed.
Maybe this is the same problem.

**Comment by vshcherb** [comment]
![telegram-cloud-photo-size-4-5947391315744503637-y](https://user-images.githubusercontent.com/1042025/162572501-3d178f53-52a1-4e27-ab72-b2ce338292c7.jpg)
Probably you need to reinstall online maps i.e. delete from Maps -> Local and setup again

**Comment by trapicki** [comment]
@mariush444:  Looking at the the settings, I noticed the setting **Map magnifier** that I had set to 300%, which explains everything fine; works now (I'm a little embarrassed of course). Thanks for looking into this!

@vshcherb: Thank you for your suggestion, tried to clear the cache before, obviously this was not the problem. If it was a problem, it would of couse be a bug. 

With you stating "_Probly you need to..._" I find it irritating that you close the bug before you even had my answer and weighted it in to find out if it was really a bug. Not encouraging for reporters... 
Please mark it as a non-bug/problem between screen and chair.
