### ISSUE TITLE
Tool to convert contacts' addresses to favorites

### ISSUE THREAD

**Issue by breversa** [osmandapp/Osmand#1404]
Is there any way, tool or plugin to batch convert/import contacts' addresses into favorites in OsmAnd ?

I could see many use for it :
- display all your contacts on map
- easily plot a route between several contacts (like pickup up coworkers when carpooling, or delivering regular clients…)
- finding which friend lives closest to all your others friends :-P
- … and probably many more !

A handy option to that tool : create a favorite category for each contacts group (so that contact in the "Friends" group end up in the "Friends" favorites category, "Clients" in "Clients", etc.). I'm not quite sure what to do with contacts that are in several groups, though.

NB :
I know that you can display a contact's address in OsmAnd by clicking on it in your addressbook, but :
- for many people, it doesn't work. See #1402 :-(
- even if it did, the keyword here is _batch_ import all (or a subset) of your contacts. :-)

**Comment by breversa** [comment]
Since address search is now apparently disabled (see #1402), may I bump this idea ?

Importing contacts' addresses as POI would be (IMO) an acceptable workaround to trying to navigate from the contacts app.

**Comment by sonora** [comment]
Possible solution #3026.
