### ISSUE TITLE
Add Persian/Arabic fonts in Map fonts

### ISSUE THREAD

**Issue by Ahmadhosseinbor** [osmandapp/OsmAnd#14042]
The default OsmAnd Arabic font is not good for maps
Please add some good **Persian/Arabic** fonts in the map fonts section
These free fonts are a good option:
**[Estedad](https://github.com/aminabedi68/Estedad)**
**[Vazirmatn](https://github.com/rastikerdar/vazirmatn)**

<img src="https://user-images.githubusercontent.com/44550501/162241157-f4c2916b-5e9b-4a61-9895-f7125cf45fba.jpg"  width="300" height="auto"/>

**Comment by dmpr0** [comment]
Hi, @Ahmadhosseinbor !
As we know fonts that are included in OsmAnd, should work fine with Arabic and Persian language, if you found an issue with displaying, please give us coordinates.

**Comment by Ahmadhosseinbor** [comment]
> Hi, @Ahmadhosseinbor !
> As we know fonts that are included in OsmAnd, should work fine with Arabic and Persian language, if you found an issue with displaying, please give us coordinates. 

Yes, they work, but they do not look good. If you look closely, you will notice that the Persian/Arabic font of the OpenStreetMap map is Vazirmatn font. For better readability of Persian/Arabic texts, It is better to use Vazirmatn or Estedad fonts.

**Comment by xmd5a2** [comment]
New fonts:
![Screenshot_2022-05-04-13-35-02-810_net osmand plus](https://user-images.githubusercontent.com/5829014/166666589-4e98b8e6-6b3f-4800-8ae2-aac828ac3b49.jpg)

Old fonts:
![Screenshot_2022-05-04-13-26-47-366_net osmand plus](https://user-images.githubusercontent.com/5829014/166666607-f1e1244a-9361-49ee-8a4d-ef270ace525c.jpg)

**Comment by Ahmadhosseinbor** [comment]
> New fonts:
> ![Screenshot_2022-05-04-13-35-02-810_net osmand plus](https://user-images.githubusercontent.com/5829014/166666589-4e98b8e6-6b3f-4800-8ae2-aac828ac3b49.jpg)
> 
> Old fonts:
> ![Screenshot_2022-05-04-13-26-47-366_net osmand plus](https://user-images.githubusercontent.com/5829014/166666607-f1e1244a-9361-49ee-8a4d-ef270ace525c.jpg)
> 
> 

In OsmAnd version 4.2 I do not see Estedad Persian font in Map Fonts section!

![Screenshot_20220609-100137_OsmAnd+.png](https://user-images.githubusercontent.com/44550501/172772192-ac50013d-d2ab-4a30-a06e-b310300bd3a2.png)
