### ISSUE TITLE
Do not populate name from ref when opening POI editing while offline

### ISSUE THREAD

**Issue by OsmMUC** [osmandapp/OsmAnd#14051]
When opening the edit dialogue for POIs that typically don't have a name but a "ref" tag while the device is offline, the name field gets populated from the ref field. This requires manual intervention to remove the name again before uploading, or if missed during editing results in objects that are usually not named (fire hydrants, street cabinets, ...) getting a name that duplicates the ref value.

### How to reproduce?
Open the edit dialogue for a POI that has no name in OSM but a ref value while the device is offline. The name field, empty/not populated in the database, will be populated in the edit dialogue with the value taken from the ref field.

### Your Environment
OsmAnd Version: OsmAnd+ 4.1.11 / OsmAnd 4.0.8 / OsmAnd 4.1.1 ( iOS)
Android/iOS version: 7.0 and 9 / 5.1.1 / iOS 15.4.1
Device model: Sony Xperia L1 and Samsung Galaxy Tab S2 / Samsung Galaxy Note 10.1 2014 / iPhone 7

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by vshcherb** [comment]
Could you please give a link to that point? I'm afraid in some situations that will be difficult to implement OFFLINE and it requires to check what's stored inside OBF whether the ref was migrated during map creation process or later

**Comment by OsmMUC** [comment]
Here a fire hydrant, a power substation, a public telephone, and an aerialway pylon, respectively:

https://www.openstreetmap.org/node/1819896437
https://www.openstreetmap.org/node/8149703975
https://www.openstreetmap.org/node/809213540
https://www.openstreetmap.org/node/278226649

Note that the behavior is as expected while the device is online. I.e. when opening the edit dialog while online, the name field remains empty.

**Comment by vshcherb** [comment]
@scaidermern it's not strange this is how it's stored in OBF, the issue to make rendering consistent, so the rendering style is not overcomplicated mostly due to mapping inconsistencies some people put data in the 'name' or 'ref' tags. Though we will investigate whether it could be changed in future.

**Comment by scaidermern** [comment]
> @scaidermern it's not strange this is how it's stored in OBF, the issue to make rendering consistent, so the rendering style is not overcomplicated mostly due to mapping inconsistencies some people put data in the 'name' or 'ref' tags.

I see. Thanks for the clarification!

**Comment by xmd5a2** [comment]
@vshcherb I can't confirm that this is OBF file issue
https://www.openstreetmap.org/node/1819896437
```
emergency_infrastructure: fire_hydrant 2068 Lat 48.140465 Lon 11.525613 osmid=1819896437  fire_hydrant_position_sidewalk='sidewalk' fire_hydrant_type_underground='underground' ref='2068' fire_hydrant_diameter='400'
```

**Comment by dmpr0** [comment]
Ways with `ref` in name, have the same issue? https://www.openstreetmap.org/way/4603579
<table style="width:100%">
  <tr>
    <th>Context menu</th>
    <th>Internet: On</th>
    <th>Internet: Off</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/198230795-07fb97b1-ac67-4ddc-b1fe-26b351806fbd.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/198230805-24068697-4717-4042-92d6-a7826741f9ed.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/198230803-f201ac1c-592d-4d91-8c08-324637f44023.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
Looks like we also need to ignore this https://github.com/osmandapp/OsmAnd-resources/blob/master/poi/poi_types.xml#L2304

**Comment by vshcherb** [comment]
rwn_ref, icn_ref need to be fixed. Template as XXX_ref

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14139mqta, released: 2023-01-31
Done
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/215739845-5752220e-4820-4a84-94a5-60ae748d940d.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>
