### ISSUE TITLE
Sharing address of favorites does not copy to clipboard

### ISSUE THREAD

**Issue by duemoselund** [osmandapp/OsmAnd#14065]
Clicking 'Copy Address' in the 'Share location' does not copy the address to the clipboard if the location is also saved as a 'Favorite'.

**Comment by duemoselund** [comment]
Clicking 'Copy Address' in the 'Share location' does not copy the address to the clipboard if the location is also saved as a 'Favorite'.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.3.0#13872mqta, released: 2022-10-16 


https://user-images.githubusercontent.com/104760013/196025786-b2a2056c-49af-4909-887e-35b224fb6bb3.mp4

**Comment by vshcherb** [comment]
Not reproduced
