### ISSUE TITLE
Portugal, Sintra - issue with search by address

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#14079]
### Description
Even with the map centered on the desired city, the application cannot find the desired city and street.
<table style="width:100%">
  <tr>
    <th><img src="https://user-images.githubusercontent.com/80623554/163596078-28776b6c-7c8b-4f0e-a0ef-8a8bd092947a.png"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/80623554/163596101-ca571847-5856-47d5-b161-fedff0f0bc70.png"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/80623554/163596582-1f73902b-8fda-4b73-a235-8e751e7cbbb0.png"  width="300" height="auto"/> </th>
  </tr>
</table> 

### How to reproduce?
Try to find this address in OsmAnd: Rua Marquês Viana, 2 , 2710-516, Portugal

### Your Environment
OsmAnd Version: 4.1.11
Android/iOS version: Android 9
Device model: Sony Experia XZ 1

**Maps used (online or offline):**   offline, updated from 1.04.2022
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by alisa911** [comment]
It has been fixed
<img width="421" alt="Screenshot 2022-11-17 at 10 52 50" src="https://user-images.githubusercontent.com/38911173/202405889-102ee511-b65a-45d2-aff7-baa79ff1b0d2.png">
