### ISSUE TITLE
Subscribing to 3 free extra maps does not work

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#14072]
### Description
iOS: When you subscribe to additional maps, the email is registered in the marketing mailing system, but the ability to download maps does not appear.

Android: When you try to register email for extra maps, appears a message: Please enter a valid email address
Tested with a few email addresses, all the time the same issue.
![image](https://user-images.githubusercontent.com/80623554/163389597-465c0ba9-9462-4540-bb9e-a3b838cdd4c3.png)

### How to reproduce?
Try to register for the free extra map downloads.

### Your Environment 
**Android**
OsmAnd Version: OsmAnd 4.1
Android version: Android 9
Device model: Sony experience XZ 1

**iOS**
OsmAnd Version: OsmAnd 4.1.1 
 Device model: iPhone 13 Pro.

**Comment by nnngrach** [comment]
Could not reproduce

IOS Device (master)
<img src="https://user-images.githubusercontent.com/35684515/164505192-199f0fb8-46b0-479a-b5ac-caad2548823b.jpeg"  width="100" height="auto"/> <img src="https://user-images.githubusercontent.com/35684515/164505212-9e4bf8cb-4ab7-4add-ba04-b3b35faae020.jpeg"  width="100" height="auto"/> <img src="https://user-images.githubusercontent.com/35684515/164505225-4f91bda7-4b5a-42ab-9196-5166304a1c28.jpeg"  width="100" height="auto"/> <img src="https://user-images.githubusercontent.com/35684515/164505248-7be07f61-9ec0-4132-b411-512090857e08.jpeg"  width="100" height="auto"/>

Android Emulator (gplayFreeLegacyFatDebug)
<img src="https://user-images.githubusercontent.com/35684515/164507014-7eb5981b-67dc-44f2-b8eb-ea638b5eba17.jpeg"  width="100" height="auto"/> <img src="https://user-images.githubusercontent.com/35684515/164507019-4f864071-35ed-4bfd-a6cc-8f21eecae10b.jpeg"  width="100" height="auto"/> <img src="https://user-images.githubusercontent.com/35684515/164507030-3091e5cd-1612-4dd9-82a9-df2ce005afee.jpeg"  width="100" height="auto"/> <img src="https://user-images.githubusercontent.com/35684515/164507033-77ef03de-5d40-4161-adf1-4ffec90f2e85.jpeg"  width="100" height="auto"/>

Android Device (nightly)
<img src="https://user-images.githubusercontent.com/35684515/164506548-8bf97771-b11e-46df-9c54-147e7dc8fb4f.jpeg"  width="100" height="auto"/> <img src="https://user-images.githubusercontent.com/35684515/164506556-a28ce60b-d236-41cc-8d41-dda5c4a3af93.jpeg"  width="100" height="auto"/> <img src="https://user-images.githubusercontent.com/35684515/164506579-6c62a20b-7151-45f6-9054-4aba9dcdeea2.jpeg"  width="100" height="auto"/> <img src="https://user-images.githubusercontent.com/35684515/164507340-a64c37a3-65b4-416f-a63b-ae82b1c83f1d.jpeg"  width="100" height="auto"/>

**Comment by naoliv** [comment]
Maybe there is a space at the end of the e-mail address? (and, if yes, a simple `strip()` should fix this)

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd/pull/14107
