### ISSUE TITLE
Incorrect KML import

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#1407]
[quote]

<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:gx="http://www.google.com/kml/ext/2.2" xmlns:kml="http://www.opengis.net/kml/2.2">
<Document>
<description><![CDATA[Generated by AlpineQuest©<br /><a href="http://www.alpinequest.net" alt="http://www.alpinequest.net">http://www.alpinequest.net</a>]]></description>
<visibility>1</visibility>
<open>1</open>
<Placemark>
<visibility>1</visibility>

<Style>
<LineStyle>
<width>3</width>
</LineStyle>
</Style>

<LinearRing>
<tessellate>1</tessellate>
<altitudeMode>clampToGround</altitudeMode>
<coordinates>
25.3016031,54.6868605 25.3014995,54.6867951 25.301423,54.6867182 25.3013952,54.6866288 25.3012551,54.6866198 25.301137,54.6866842 25.3009624,54.6866976 25.3008314,54.6866393 25.3006493,54.6866246 25.300533,54.6866944 25.3004564,54.6868218 25.3004591,54.6869233 25.3004765,54.6870108 25.3005133,54.6871026 25.3005298,54.6871934 25.3005779,54.6872878 25.3006173,54.6873823 25.3007045,54.6874496 25.3008107,54.6875033 25.300951,54.6875427 25.3011106,54.6875505 25.3012623,54.6875621 25.3014192,54.687566 25.3015553,54.687566 25.3016823,54.6875396 25.3018091,54.687504 25.3019182,54.6874536 25.3019853,54.6873714 25.3019853,54.6872938 25.3019786,54.6872101 25.301945,54.6871329 25.3018579,54.6870624 25.3018243,54.6869852 25.3017271,54.6869245 25.3016031,54.6868605
</coordinates>
</LinearRing>
</Placemark>
</Document>
</kml>
[/quote]

**Comment by sonora** [comment]
Cross ref #3161.
