### ISSUE TITLE
Missing strings to translate


### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#14086]
There are no strings for translation with data on the difficulty of ski routes.
![Screenshot_2022-04-16-01-59-45-131_net.osmand.plus.jpg](https://user-images.githubusercontent.com/12549744/163721304-8828b2e2-5b75-40e1-b605-6bfeb9f2a28e.jpg)
![Screenshot_2022-04-16-01-59-38-129_net.osmand.plus.jpg](https://user-images.githubusercontent.com/12549744/163721316-7ce6d48e-a948-4280-bdf8-d7108a20bc29.jpg)

### Your Environment
OsmAnd Version: OsmAnd~ 4.2.0#33867m, дата выпуска: 2022-04-16
Android version: 12
Device model: poco x3 pro

**Comment by Chumva** [comment]
https://github.com/osmandapp/OsmAnd/commit/073c4945a2adf460448a44a8c990100afb15c271

**Comment by Nine-Tailed** [comment]
String "intermediate" is still missing.
