### ISSUE TITLE
Address information guessed instead of used from POI

### ISSUE THREAD

**Issue by jtotht** [osmandapp/OsmAnd#14084]
### Description
OsmAnd tries to guess a POI’s address even though the correct address is set on OSM (and it guesses wrong).

### How to reproduce?
1. Download the Hungary offline map.
2. Open the map at 47.62275°N, 19.04620°E.
3. Open the POI indicated on the screenshot and look at its address.

### Actual result
4. The shown address is _Pomázi út (Taván) 2/D, Budakalász_, which belongs to a street at the other side of the railway line.

### Expected result
4. The shown address is _Szentendrei út 1-3, Budakalász_, just like on [openstreetmap.org](https://www.openstreetmap.org/way/360735611).

### Your Environment
OsmAnd Version: OsmAnd~ 4.1.11 (from F-Droid)
Android version: screenshot from 6.0.1, also reproduced on another device with Android 11
Device model: Samsung Galaxy A3 (Android 6.0.1), Samsung Galaxy A41 (Android 11)

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
- `Hungary_europe`? I’m not sure what map file name you ask, but hopefully you’ll be able to identify it. It’s just the default normal map for this region.

### Screenshot
![Screenshot_2022-04-16-15-17-18](https://user-images.githubusercontent.com/41370836/163676840-3fc732d3-73b8-409a-897d-6d9ef9f0d80b.png)

**Comment by vshcherb** [comment]
New version 4.2: shows as expected ```1-3 str. Szentendrei út (Klenity) city Budakalász```.

So please wait for new release
