### ISSUE TITLE
OLC search does not work correctly with Villages

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#14081]
### Description
When searching by the OLC coordinates OsmAnd identifies place incorrectly.

### How to reproduce?
Try to find by this coordinates: QJRC+67 Sintra, Portugal
<table style="width:100%">
  <tr>
    <th><img src="https://user-images.githubusercontent.com/80623554/163598274-fba0a3da-9f3a-4ef2-830a-293c8c3fee9b.png"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/80623554/163597798-0060949c-ad4f-45ab-a977-a0afafc3b414.png"  width="600" height="auto"/> </th>
  </tr>
</table> 

### Your Environment
OsmAnd Version: 4.1.11
Android/iOS version: Android 9
Device model: Sony Experience XZ 1

**Maps used (online or offline):**   offline, updated 1.04.2022
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by vshcherb** [comment]
This issue is related to https://github.com/osmandapp/OsmAnd/issues/14079, cause Sintra is not recognized correctly as Town/City

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/1956

**Comment by alisa911** [comment]
Fixed in https://github.com/osmandapp/OsmAnd/issues/12809
