### ISSUE TITLE
Pedestrian distance over-estimates

### ISSUE THREAD

**Issue by PinkDuck** [osmandapp/Osmand#1409]
Pedestrian distance estimates in metric units seem to use imperial coefficients, e.g. turn left in 50 m seems to be always less than 50 foot in reality. Presumably check conversion before speech?

**Comment by PinkDuck** [comment]
I suspect it may be that road distance rounding to the nearest 50 m is active for pedestrian routing too, so consider switching that to the nearest metre instead. It's rather helpful to have precise distances when walking through densely mapped urban areas.

**Comment by vshcherb** [comment]
It is slightly less because of the voice speech but the trigger is checked every second. We do round when it speaks, the exact number is always displayed on the widget! https://github.com/osmandapp/OsmAnd-resources/blob/master/voice/en/ttsconfig.p#L328 (here we do round to +-5m).

**Comment by vshcherb** [comment]
The point that notification happens based on the time left (!) and not on the distance, widget display exact meters, voice speaks rounded distance. I think we will consider rounding it at least to 5 meters

**Comment by sonora** [comment]
Rounding to 5 meters is useless in car routing, and also usually too close
to the GPS fix accuracy itself, so if we do this at all I suggest to
strictly do this in ped mode (and then I am not sure it is worth it ...)

**Comment by PinkDuck** [comment]
Often using pedestrian navigation myself I can tell you it is worth it to have closer distance estimates that "after 50 m" when the next left/right is 3 m away.

**Comment by sonora** [comment]
I think I had fixed this some time ago.
