### ISSUE TITLE
Crash during the update notification of the maps loading

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#14091]
Device : marlin
Brand : google
Model : Pixel XL
Product : marlin
Build : lineage_marlin-userdebug 9 PQ3A.190801.002 eng.root.20200403.054525 dev-keys
Version : 9
App Version : OsmAnd~
Apk Version : 4.1.11 421
exception.log

[exception (9).log](https://github.com/osmandapp/OsmAnd/files/8511064/exception.9.log)

**Comment by Chumva** [comment]
[DeadSystemException ](https://developer.android.com/reference/android/os/DeadSystemException)- The core Android system has died and is going through a runtime restart. All running apps will be promptly killed.

It looks like android system crashed (LineageOS) and OsmAnd cannot fix this crash
