### ISSUE TITLE
GPX tracks style not updated when switching map profile

### ISSUE THREAD

**Issue by toadjaune** [osmandapp/OsmAnd#14105]
### Description

The style of GPX tracks displayed on the map can be configured per profile, however, this setting is not honored when switching map profiles.

### How to reproduce?

* get a gpx track (either record it, download it, use the "Plan route" tool, doesn't matter)
* on the main screen, go to the "Browse map" (default) profile configuration, open the sub-menu "Tracks"
* change the color to blue
* select your gpx track to be displayed
* go back to the map view
* your track is displayed, in blue
* switch your map to car profile
* the track is still blue, despite being configured to red (default) on the car profile
* open the "Tracks" sub-menu for the car profile, change the color to pink
* the track color is now updated

Please note :
* I took specific examples of profiles and colors, but as far as I can tell, the problem seems present : 
  * regardless of source/target profile
  * also for other parameter changes (line thickness / start/end icons)
* I could reproduce the issue with a fresh osmand install
* opening the Appearance configuration window and re-clicking on the current style refreshes as well

### Your Environment
OsmAnd Version: `4.1.11`
Android/iOS version: Android 12 (build `SP1A.210812.016.C1`)
Device model: Google Pixel 3

**Maps used (online or offline):**   
I could reproduce the issue without even downloading a map (besides the default "world basemap mini")

**Comment by vshcherb** [comment]
I think it's fixed in 4.2 cause GPX track color is not profile dependent and should not be.
