### ISSUE TITLE
Add display of golf courses as on OSM

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#14109]
https://www.openstreetmap.org/node/7986377287#map=19/33.50176/-82.02035

<<table style="width:100%">
  <tr>
    <th><img src="https://user-images.githubusercontent.com/80623554/164684536-1a26fc0f-a277-49b9-a0e7-dd0fd70342f5.png"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/80623554/164684207-779fe268-02e3-4856-886d-46adeb1076cc.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by xmd5a2** [comment]
![Screenshot_2022-04-26_09-59-10](https://user-images.githubusercontent.com/5829014/165241717-8f78db7c-1f8b-4e71-8f48-76c10c20d4b9.png)
