### ISSUE TITLE
GPX track drawing suggestion

### ISSUE THREAD

**Issue by PinkDuck** [osmandapp/Osmand#1410]
The GPS Track route highlight would work much better as a thin, magenta line for improved display contrast on mobile devices and to better understand on site how the track overlaps.

**Comment by sonora** [comment]
IFrankly,  have played a lot with this over the years. The route needs to be clearly and quickly  visible for the driver under sub-optimum conditions, like in e.g direct sunlight (for convertables or on motorcycles) or under heavy vibration(jeeps, trucks, bicycles). I have always found that thin lines are inferior to thicker, marker pen like highlightings here.

**Comment by PinkDuck** [comment]
I find the current thick line with translucent cyan rather hard to see on my mobile devices under direct sunlight for GPX created from OsmAnd. An option to set default width and colour for tracks might be better than changing the default.

**Comment by 9662** [comment]
For the record and from experience, the thicker line as mentioned by @sonora  is the lesser evil.

**Comment by PinkDuck** [comment]
Thicker probably so for vehicular movement. I mostly tend to use the GPS visualisation when using OsmAnd to log where I've been during OSM surveying, in which case I'm largely on foot and wanting to know if I've already surveyed a stretch of woodland path or similar.

**Comment by vshcherb** [comment]
It is already like that in UniRS style, I think @xmd5a2  will provide more information about latest changes for GPX rendering style

**Comment by xmd5a2** [comment]
There are options in Touring view, UniRS and LighRS styles: GPX color, GPX width. 
![screenshot_2015-08-04-11-32-35](https://cloud.githubusercontent.com/assets/5829014/9056598/df09e91a-3a9c-11e5-884f-878bf268c5ab.png)

**Comment by meder1** [comment]
Can this be reopened? The controls will alter the recorded track not the proposed route. Can the proposed route have color (+ magenta please) and thickness controls? Looking to use Osmand for dual sport, need blatantly obvious nav lines.
Thanks.

**Comment by meder1** [comment]
Trying to replace Garmin Montana with Osmand.
