### ISSUE TITLE
[bug] meaning of menu is opposite to its processing

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#14119]
### Description
track | options | edit track | options

In track option it is possible to append an other track.
The german translation of menu text is opposite, of what is processed.
Please change
"zu einem Track hinzufügen"
to
"einen Track hinzufügen"
see screenshot menu 5

![Screenshot_track option menu](https://user-images.githubusercontent.com/18628183/164968397-0d1a7a05-82cb-44a3-9178-f4e44dd87cb3.jpg)

### Your Environment
OsmAnd Version: OsmAnd~ 4.2.0#33869m, veröffentlicht: 2022-04-17
Android version: 10

**Comment by letypequividelespoubelles** [comment]
Language translation is done [here, on weblate](https://hosted.weblate.org/projects/osmand/#languages)

**Comment by pebogufi** [comment]
The english version is
"Add to a track"
which is also wrong in my understanding.
I would name it "Add a track" (without the "to").

The action / processing of the function is "add (append) a track (which is to be selected) to current track".

**Comment by vshcherb** [comment]
This is not true, just tested it with creating new track. It saves all new data to the track selected in dialog, so the modified track or new track stays untouched

**Comment by Gbernardy** [comment]
It's a bit strange ... 

one is being edited on a track,

a second track is appended to it, which is not declared in edit, 

and the latter is updated ... congratulations !!!

**Comment by dmpr0** [comment]
> It's a bit strange ...
> 
> one is being edited on a track,
> 
> a second track is appended to it, which is not declared in edit,
> 
> and the latter is updated ... congratulations !!!

"Add to a track" allow to combine two tracks. Add to a track mean, that route that editing or created, will be added to a selected track, it also indicated by the description in the track selection dialogue. 

"Add to a track" option was added directly to do, what it doing now. If you need other options, you can create a request.
