### ISSUE TITLE
[crash] starting on highway=service as pedestrian

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#14113]
### Description

- crash without writing logfile
profile pedestrian
from 43.97204° N, 0.18632° W (highway=service)
to 43.99937° N, 0.16954° W

- NO crash starting nearby on secondary
from 43.97209° N, 0.18584° W
same profile, same destination (to)

version OsmAnd~ 4.2.0#33869m, veröffentlicht: 2022-04-17
current map with live 
crash on two different devices, Samsung S7, android 8, samsung tab S5e android 10

* maybe because the serviceway is something like loop ?

**Comment by Nine-Tailed** [comment]
I also have an osmand crash when navigating on foot on a map with a live update.  The error is not written to the log, but in safe mode I received the following message:
![Screenshot_2022-04-25-14-18-11-609_net.osmand.plus.jpg](https://user-images.githubusercontent.com/12549744/165079407-6c2e6b85-cb09-40d1-9820-295ec2127953.jpg)
