### ISSUE TITLE
characters/icons for closing and opening legends reversed ?

### ISSUE THREAD

**Issue by Gbernardy** [osmandapp/OsmAnd#14111]
But are the characters/icons for closing and opening legends correct?

![IMG_20220422_133307](https://user-images.githubusercontent.com/99968793/164706848-2da09fcd-40cc-481a-8b1c-1daf2290b79e.jpg)

![IMG_20220422_132943](https://user-images.githubusercontent.com/99968793/164706884-93ee5441-7255-417f-89a0-2afca55260b1.jpg)

Comparing them to those used on MyPlaces/Tracks are reversed ...

![IMG_20220422_132133](https://user-images.githubusercontent.com/99968793/164705104-9a6a9ab1-666a-422a-8a8a-799fe5fc1677.jpg)

**Comment by vshcherb** [comment]
what so important about them, couldn't spot an issue

**Comment by Gbernardy** [comment]
No, it is not a issue ...

I used this mode ... 

![Screenshot_2022-04-22-17-14-53-46_99c04817c0de5652397fc8b56c3b3817](https://user-images.githubusercontent.com/99968793/164744330-05ae7110-4279-406a-bd85-4ef3434f61a2.jpg)

then if it's not okay I close it
