### ISSUE TITLE
Purchased Contour Lines plugin leads to subscription page

### ISSUE THREAD

**Issue by mryellow** [osmandapp/OsmAnd#14116]
### Description

The Contour Lines plugin which should result in the ability to download the contour maps, instead results in a "Get" button which leads to a subscription page asking for $3.99/month.

### How to reproduce?

* Purchase Contour Lines plugin
* Use it for years
* Come back and discover it's been taken away from you and this freely available DEM data is now seemingly either bugged or intentionally paywalled

**Comment by dmpr0** [comment]
Hello! Thank you for the feedback. 
You need to contact us at support@osmand.net with the transaction number of the purchase or Google account email address.

**Comment by mryellow** [comment]
I believe this is a bug.

Support simply tell you to install this plugin but installing this plugin does not remove the "GET" buttons which lead to a subscription page and does not provide "Download" buttons where the previously purchased map can actually be downloaded.

**Comment by mryellow** [comment]
This page here suggests that "Topo data (Contour lines and Terrain)" doesn't work in OSMAnd as it once did.

So I have been bait and switched? In other words scammed or in other words stolen from?

https://test.osmand.net/docs/user/purchases/android/

**Comment by mryellow** [comment]
Meanwhile this page...

>F or using this feature you should buy [Contour lines plugin](https://play.google.com/store/apps/details?id=net.osmand.srtmPlugin.paid&hl=en) or subscribe [OsmAnd live](https://osmand.net/features/subscription).

Clearly states that to access can be gained either buying the plugin **OR** subscribing to "OsmAnd Live".

> To see the contours of a specific area, just go to Download maps menu, find your country or region, choose Contour lines, Hillshades, Slopes or all and download the files

If this is the case then there is a bug where when running OSMAnd with the plugin results in a "GET" button instead of a "Download" button.

This page does not look like this with OsmAnd + Plugin installed:

https://osmand.net/images/features/ter6.jpg

https://osmand.net/features/contour-lines-plugin

So either it's a bug, or you've intentionally disabled this feature for all users who have previously paid for it. I'm struggling to figure out which and L1 support aren't very helpful...

**Comment by mryellow** [comment]
Meanwhile...

> Legacy subscriptions (prior 4.0)
> New subscriptions became active from OsmAnd 4.0 (August 2021). All earlier subscriptions are legacy and techncically equal to "Maps subscription", though **legacy subscriptions are entitled for Hourly Map updates**. Users can't buy legacy subscriptions but old subscriptions are automatically renewed until the user unsubscribes (the price for them might change in the future).

https://test.osmand.net/docs/user/purchases/android/#legacy-subscriptions-prior-40

**Comment by dmpr0** [comment]
You need to install both OsmAnd and Contour lines plugin from Google Play, it works, I have checked it. You can try to reboot your device. Also, a similar issue could happen if you have more than one Google account, and the one from which purchased was made not the main.

**Comment by mryellow** [comment]
> You need to install both OsmAnd and Contour lines plugin from Google Play, 

I have.

>  it works, I have checked it.

If that is meant to work. Then I am reporting a bug and you're confirming that it's a bug.

> You can try to reboot your device.

I have. I've also reinstalled the app.

>  Also, a similar issue could happen if you have more than one Google account, and the one from which purchased was made not the main.

The plugin was purchased under the account I am authenticated against.

**Comment by mryellow** [comment]
> I have checked it.

Have you also checked purchasing before version 4 and subscription features were introduced, then installing on one phone, only to subsequently move to another phone?

**Comment by dmpr0** [comment]
> > I have checked it.
> 
> Have you also checked purchasing before version 4 and subscription features were introduced, then installing on one phone, only to subsequently move to another phone?

Contour lines plugin also was part of old "OsmAnd Live" subscription before new subscriptions were introduced.

**Comment by mryellow** [comment]
> Contour lines plugin also was part of old "OsmAnd Live" subscription before new subscriptions were introduced.

I am describing the sequence of events you may have to attempt in order to create a situation which duplicates the bug. Simply installing a fresh copy of the app on a fresh mock purchase may not be sufficient. 

I am experiencing "GET" buttons which should be "Download" buttons on OsmAnd with Contour plugin installed. I have previously purchased and ran Contour lines + Hillshading on OsmAnd without a subscription. Thus I believe this to be a bug.

Are you saying now that it shouldn't work? That I should be locked out from download and that this is intended? That it only works with "OsmAnd Live"?

Very confused. Your documentation clearly states that either "Contour lines plugin" **OR** a subscription to "OsmAnd Live" is required. Which suggests nothing has changed and my setup should still work.

> For using this feature you should buy [Contour lines plugin](https://play.google.com/store/apps/details?id=net.osmand.srtmPlugin.paid&hl=en) or subscribe [OsmAnd live](https://osmand.net/features/subscription).

Then we have the fact that we're talking about free data here. Data you pay nothing for as a company. Data which I download once and keep forever.

Please re-open this ticket and begin to take it seriously. So far you have make a lacklustre effort at duplication and pushed everything back on support when this is not a support issue.

I own the software. I install the software. The software is not working as it should.

**Either you're acting in a fraudulent manner or it's a bug. One or the other.**

**Comment by dmpr0** [comment]
Either you're acting in a fraudulent manner or it's a bug. One or the other.

**Comment by mryellow** [comment]
@Gbernardy Do you have someone more senior than @dmpr0 who can investigate this bug.

**Comment by dmpr0** [comment]
@mryellow Unfortunately, @Gbernardy not part of OsmAnd team.
