### ISSUE TITLE
Can't create a route using rtept

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#14126]
- Nearest point -> Route between points Driving
- Nearest point should take first point with min distance with threshold 10 m 

From https://github.com/osmandapp/OsmAnd/discussions/14122

Can't select Bicycle or Car profile
[1.gpx.zip](https://github.com/osmandapp/OsmAnd/files/8555292/1.gpx.zip)

**Comment by Chumva** [comment]
It should load route with this track - 
<table style="width:100%">
    <th><img src="https://user-images.githubusercontent.com/19220417/166440361-ce111376-078c-4838-abf0-c81d47a4420f.png"  width="300" height="auto"/> </th>
</table>
