### ISSUE TITLE
Many broken links on https://osmand.net/features/osmand_purchases

### ISSUE THREAD

**Issue by mikehgentry** [osmandapp/OsmAnd#14120]
"The full version of an article about OsmAnd purchases you can read [here](https://docs.osmand.net/en/main@latest/osmand/purchases/ios)."

"The full information about OsmAnd subscriptions you can read [here](https://docs.osmand.net/en/main@latest/osmand/purchases/android)."

"OsmAnd has two active subscription plans and legacy subscriptions:

 [OsmAnd Pro](https://docs.osmand.net/en/main@latest/osmand/purchases/android#free-and-paid-features)
 [OsmAnd Maps+ (for OsmAnd Free version)](https://docs.osmand.net/en/main@latest/osmand/purchases/android#free-and-paid-features)
 [Legacy subscriptions](https://docs.osmand.net/en/main@latest/osmand/purchases/android#legacy-subscriptions-prior-40)"

(and possibly others, I didn't check them all)

**Comment by mikehgentry** [comment]
This probably should have been posted here: https://github.com/osmandapp/web

Sorry about that - let me know if you want me to close it and open it there.

**Comment by vshcherb** [comment]
Yes we need to update to https://docs.osmand.net/docs/user/purchases/android

**Comment by mikehgentry** [comment]
OK, will close as you're aware. Cheers.
