### ISSUE TITLE
CyclOSM tiles not loaded, empty map

### ISSUE THREAD

**Issue by ednl** [osmandapp/OsmAnd#14137]
### Description
I use OsmAnd on iOS and iPadOS. I recently saw that the cycling profile with online tiles "doesn't work" anymore. The map is empty, no tiles are loaded. This is not an internet connection issue, it happens on both working wifi and mobile. I tried changing the map source URL of the online CyclOSM profile (Maps & resources  > Installed > Online > CyclOSM > Edit), because I saw that the standard URL is different from the one mentioned on https://github.com/cyclosm/cyclosm-cartocss-style . After entering the URL from GitHub, the updated URL on the profile was automatically changed, I guess, or perhaps the "c." version came from somewhere else? I can't find that anymore now, sorry. Anyway, it is now:

Default URL: `https://dev.a.tile.openstreetmap.fr/cyclosm/{0}/{1}/{2}.png`
GitHub URL: `https://{s}.tile-cyclosm.openstreetmap.fr/cyclosm/{z}/{x}/{y}.png`
Updated URL: `https://c.tile-cyclosm.openstreetmap.fr/cyclosm/{0}/{1}/{2}.png`

It still didn't work. I randomly tried enabling Overlay and/or Underlay for the cycling map (just the standard CyclOSM version), and then it did work! Strangely it keeps working after disabling the Over-/Underlay. Perhaps flipping the Over-/Underlay triggered some sort of download-online-cycling-tiles flag?

### How to reproduce?
On latest iOS and iPadOS, use latest OsmAnd 4.1.1. Switch to Cycling profile: no map tiles are shown. Edit tile server URL as above, tiles are still not loaded. Enable CyclOSM Overlay, online tiles ARE loaded. Disable Overlay, tiles are still loaded.

### Your Environment
OsmAnd Version: 4.1.1
Android/iOS version: iOS
Device model: iPhone 13 Pro, iPad Pro v2

**Maps used (online or offline):** online

**Comment by ednl** [comment]
Well, they asked me to file this issue after I mentioned it on Twitter. Also they provide the CyclOSM profile to be selected in their app, I didn't manually add it.

**Comment by vshcherb** [comment]
Please try this url and it works
```
https://c.tile-cyclosm.openstreetmap.fr/cyclosm/{$z}/{$x}/{$y}.pngx
```

**Comment by vshcherb** [comment]
Actually tested on iOS and couldn't reproduce the default URL works
![telegram-cloud-photo-size-2-5425143375817981181-y](https://user-images.githubusercontent.com/1042025/165477369-f38fbea6-3b76-4856-ba65-b31b6c92f4cf.jpg)

**Comment by vshcherb** [comment]
Please try to clean up and start again

**Comment by ednl** [comment]
Apparently reading my post was too much effort. As I wrote, I already used that URL and the issue is fixed now, for me. *But not before I also enabled/disabled an Overlay on the CycleOSM view!*

Try to clean up?? I never changed anything, and then it stopped working.

This exchange does not give me much confidence in the OsmAnd app organisation :(

**Comment by dmpr0** [comment]
> How to reproduce?
> On latest iOS and iPadOS, use latest OsmAnd 4.1.1. Switch to Cycling profile: no map tiles are shown. Edit tile server URL as above, tiles are still not loaded. Enable CyclOSM Overlay, online tiles ARE loaded. Disable Overlay, tiles are still loaded.
> 

Hi!
Could you please tell, me which option to view the online tile maps are you using? 
If you disable "Overlay" layer, you will be seen only map selected in "Map type" menu, by default it is "Offline vector maps", that need to be downloaded, if not, map  will be empty.

You need enable on of the listed options: "Overlay", "Underlay" or "Map type" with "CycleOSM" as a source to view this map.

I have tried to enable "CycleOSM" as Overlay on my device, it works, on release 4.1 and beta testflight buid 4.2.

<img src="https://user-images.githubusercontent.com/9365308/165541546-1a9d902b-ca8d-4ec0-9d59-2bc5e0326b61.jpg"  width="300" height="auto"/>

**Comment by vshcherb** [comment]
@ednl did you update OsmAnd? How did it stop working then? Unfortunately we've tried the url you've mentionned and it works, so we couldn't reproduce the issue. Probably we will get more evidences and spotlights in the future
