### ISSUE TITLE
Android Auto Search Result (POI / GPX) is not displayed

### ISSUE THREAD

**Issue by ThibaudTC** [osmandapp/OsmAnd#14138]
### Description

I downloaded a gpx route on my android phone and connected to android auto. On android auto I can select this gpx route. But then I get the loading icon (rotating arrow). However it will never load, it keeps on loading. Something wrong? 
Loading the gpx route and using it on my phone is no problem. 
How to get this done on android auto? 

### Your Environment
OsmAnd Version: 4.1.11
Android/iOS version: 12
Device model: Nokia xr20 / Andoid auto

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by rvervaek** [comment]
I'm having the same issue over here.

OsmAnd Version: latest
Android version: 9

**Comment by Zirochkabila** [comment]
@ThibaudTC Did you try to do as @vshcherb wrote?

**Comment by Zirochkabila** [comment]
@ThibaudTC The behavior can be reproduced, but if you perform the actions that @vshcherb wrote about - navigation starts with the selected track.

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd/pull/15858
