### ISSUE TITLE
Contour Lines Plugin fails to enable downloads buttons on OsmAnd

### ISSUE THREAD

**Issue by mryellow** [osmandapp/OsmAnd#14133]
### Description

> For using this feature you should buy [Contour lines plugin](https://play.google.com/store/apps/details?id=net.osmand.srtmPlugin.paid&hl=en) o

https://osmand.net/features/contour-lines-plugin

This image shows that the buttons should become download buttons. However they remain green "GET" buttons which link to the subscription page and demand more money.

https://osmand.net/images/features/ter6.jpg

### How to reproduce?

* Purchase Contour lines plugin
* Use Contour lines plugin for years
* Attempt to install on new phone
* No longer be able to download maps

**Comment by mryellow** [comment]
p.s. This is a bug not a support issue. The buttons should be enabled for anyone using OsmAnd with Contour Lines Plugin installed. As advertised, as documented, as purchased.

**Comment by Gbernardy** [comment]
Have you tried with backup on the old smartphone and then restore on the new smartphone ?

![Screenshot_2022-04-26-09-55-00-16_54166e5c6f8ad9491c65e2397c495c92](https://user-images.githubusercontent.com/99968793/165250517-2e16b678-e930-4fb0-8d24-23f4ab5316b4.jpg)

**Comment by mryellow** [comment]
> Have you tried with backup on the old smartphone a

The old phone is not backed up.

**Comment by dmpr0** [comment]
Duplicate https://github.com/osmandapp/OsmAnd/issues/14116

**Comment by dmpr0** [comment]
> Then reopen the ticket about the bug. I'm very close to starting a fraud report if you insist on closing tickets.
I can't reproduce the bug. As I see you try to make coverage, not try to solve the issue. 
You can send a fraud report or contact Google Play if you want.

**Comment by vshcherb** [comment]
@mryellow please stop creating issue or you will be banned
