### ISSUE TITLE
Exit doesn't

### ISSUE THREAD

**Issue by 9662** [osmandapp/Osmand#1415]
I went and set a "display all" custom filter (as per #1224) which, to my great satisfaction, showed every point in the map. After that I tapped on the **Exit** menu item, but it did not exit, it just went back to the previous menu. I then hit the **Back** button a number of times until I was out of the application.

On the good news front, when I went back in, I could see the "Osm Edits" tab under "My Places" and upload my notes, which I'd just complained about in #1414.

**Comment by vshcherb** [comment]
There is no exit button any more

**Comment by 9662** [comment]
![tmp_screenshot_2015-06-29-04-37-07-929680650](https://cloud.githubusercontent.com/assets/13080040/8400066/ed9d2758-1e18-11e5-8b1f-946df2b96e48.png)

OsmAnd~ v2.1.0
