### ISSUE TITLE
France maps missing.

### ISSUE THREAD

**Issue by bigfoot38** [osmandapp/OsmAnd#14167]
### Discussed in https://github.com/osmandapp/OsmAnd/discussions/14073

<div type='discussions-op-text'>

<sup>Originally posted by **bigfoot38** April 14, 2022</sup>
Hello,

I recently re-installed Osmand but I could not download all the maps from France.
In the download menu, I navigate to Europe->France and only found 4 maps. When I click on a region of France on the map, the region is highlighted but Osmand does not propose to download a map, while it does if I click on another country.

I think that it is a bug, but do you have another explanation?

Regards</div>

**Comment by vshcherb** [comment]
Bug is not clear cause we can't reproduce, could be further discussed https://github.com/osmandapp/OsmAnd/discussions/14073
