### ISSUE TITLE
Feature request: Profile mountainbiking icon

### ISSUE THREAD

**Issue by mjeeloo** [osmandapp/OsmAnd#14169]
# 🚀 feature request

### Description

A icon for mountain-/off-road biking for profiles

### Describe the solution you'd like

Being able to use the icon that's already available for favorites (the uphill biker with the backpack) for profiles

### Describe alternatives you've considered

Using the normal cycling icon (but it's confusing)

**Comment by dmpr0** [comment]
Added fe7920b02c. Will be available in the nightly versions soon.
