### ISSUE TITLE
Route cannot be calculated at specific point on map

### ISSUE THREAD

**Issue by Isolator70** [osmandapp/OsmAnd#14162]
### Description
Plan a route through a specific point on OSM is not possible. OsmAnd shows following error message (German): 
"Route konnte nicht berechnet werden.:
lenght=1; index=1"

### How to reproduce?
1. Goto position 50.51848°N, 8.40801°E
2. On L 3283 (direction north - south) plan a route bypassing the crossing of the two street "Attenbach" and "Oberndorfer Hütte"
3. Result: Route cannot be calculated, see attached screenshot.

### Your Environment
OsmAnd Version: 4.1.11
![Screenshot_20220429_130315_net osmand plus](https://user-images.githubusercontent.com/35434137/165936164-fae85a21-c49b-48ed-9bf7-e4563469e986.jpg)
![Screenshot_20220429_130401_net osmand plus](https://user-images.githubusercontent.com/35434137/165936173-b34569e8-acdc-4e68-8cba-0b71fb878ff5.jpg)

Android/iOS version: Android 9
Device model: Huawei P10, VTR-L29
![Screenshot_20220429_125852_net osmand plus](https://user-images.githubusercontent.com/35434137/165936158-aa1eb525-6e4d-4ab7-9891-c963c683df4b.jpg)

**Maps used (online or offline):**   

Offline map used, affected is "Hessen", subset from "Deutschland", subset from "Europa".
Version from 01.04.2022 is used, error also occurred on the version before (March version?)

**Comment by vshcherb** [comment]
As I see the issue will be fixed with new release 4.2
