### ISSUE TITLE
Editing POI tags moves POI slightly

### ISSUE THREAD

**Issue by Self-Perfection** [osmandapp/Osmand#1416]
Examples:
http://www.openstreetmap.org/changeset/32159594
http://www.openstreetmap.org/changeset/31876397
http://www.openstreetmap.org/changeset/31867818

Seems to be a regression of 2.* version, 1.9.4 did not move POI upon edit:
http://www.openstreetmap.org/changeset/31108632

**Comment by vshcherb** [comment]
Nope that's not a regression because it moves only some POI's, we have a rounding grid in obf maps and it uses that lat/lon from obf, which it should not of course.

**Comment by vshcherb** [comment]
Fixed
