### ISSUE TITLE
No longer able to access external storage device, size or files

### ISSUE THREAD

**Issue by rktcc** [osmandapp/OsmAnd#14165]
### Description
After a recent Android update, OSMAnd can no longer access any files on an external storage SD Card. When attempting to migrate, or when attempting to setup for the first time, external storage or multiuser storage options don't have any size of available space listed, and manually selecting a folder on the SD Card doesn't work, even if it's outside protected folders like Android/data.

I have attempted switching to a brand new in package SD Card, formatting as portable storage, and using that, but it did not work. Using an SD Card as an Android only card is not an option for me.

### How to reproduce?
1. Upgrade to latest Android 11 build for specific device
2. Open OSMAnd
3. Go through migration or setup process. You can only select internal storage.

### Your Environment
OsmAnd Version: 4.1.11 F-Droid build
Device model: Moto G7 Power
Android/iOS version: Android 11, lineageos-18.1-20220423-NIGHTLY-ocean, (April 5 2022 security patch, kernel 4.9.206-perf+)

**Maps used (online or offline):**   
World basemap, but it's not strictly related to any used maps. Even with a blank setup, no downloaded maps or overworld map, this issue is present.

![Screenshot](https://user-images.githubusercontent.com/104650597/166062398-dd383903-16d9-4303-9594-9e77a4457e71.png) 

Screenshot above. [logcat.txt](https://github.com/osmandapp/OsmAnd/files/8594476/logcat.txt) here

I think [this commit](https://review.lineageos.org/c/LineageOS/android_packages_providers_MediaProvider/+/328228/) may be the culprit. I'm not an Android dev so I don't understand the specifics of this.

Should be noted there were no issues with permissions or external storage access with builds before this commit, so the April 2nd or 9th builds work fine.

Thanks!

**Comment by RomBuch** [comment]
I am seeing the same issue. This is quite critical because I have hardly space on internal storage and need to use the SD Card storage. Is there some way to fix it?

**Comment by vshcherb** [comment]
Solution is not clear for now

**Comment by RomBuch** [comment]
Hi, a workaround was reported here: https://github.com/osmandapp/OsmAnd/discussions/13538#discussioncomment-2670607

When I use the manual path 
SD_card/Android/media/net.osmand.plus
it was working for me again. Hope this helps you, too.

Am 2. Mai 2022 13:09:44 MESZ schrieb vshcherb ***@***.***>:

**Comment by klic** [comment]
Well, maybe for importing tracks, but it does not work as the default directory for osmand if you do not want to reside on the internal storage.
At least I can't use anything on sdcard for osmand right now.

**Comment by xgorex** [comment]
I do confirm, same issue on MotoG7 Play, SD set as stand alone stirage, Osmand 4.1.11.

@RomBuch workaround works for me.

**Comment by paolo-caroni** [comment]
Same problem for me on lineageos 18.1...

**Comment by vanMacG** [comment]
Same here since I updated LineageOS 18.1...
When I use the file manager from TWRP I can see everything in android/data on the sd card, even all Osmand-files (maps, etc.) are still there. When I use the file manager in Lineage, the folder is empty.

Curious note: when "external storage 2" is selected, and I try to download a map, the error message says: "storage is not enough". This is a bit misleading...

**Comment by paolo-caroni** [comment]
> Hi, a workaround was reported here: [#13538 (reply in thread)](https://github.com/osmandapp/OsmAnd/discussions/13538#discussioncomment-2670607) When I use the manual path SD_card/Android/media/net.osmand.plus it was working for me again. Hope this helps you, too. Am 2. Mai 2022 13:09:44 MESZ schrieb vshcherb ***@***.***>:
> […](#)
> Solution is not clear for now -- Reply to this email directly or view it on GitHub: [#14165 (comment)](https://github.com/osmandapp/OsmAnd/issues/14165#issuecomment-1114730768) You are receiving this because you commented. Message ID: ***@***.***>
This solution work for me!! I can't move old map but I have downloaded all my maps and resolved the issue... probably the sd card have two identical maps on different folder, but i will remove the sd from the phone and use a pc to delete old folder.

**Comment by new-on-github** [comment]
Same problem here. Thanks for the workaround. This works for me, too. But I had to download all files again.

Btw: Thanks for this amazing app!

**Comment by Betterbird** [comment]
> When I use the manual path SD_card/Android/media/net.osmand.plus it was working for me again. Hope this helps you, too.

The path depends on the device, I have /storage/3934-3962/Android/media/net.osmand.plus/files. No need to re-download, just move the folder from data/net.osmand.plus to media/net.osmand.plus on a "real" computer with the SD card inserted.

**Comment by anastasiia936** [comment]
Reproduced on the Samsung XCover with Android 11

**Comment by premier-lifeboat** [comment]
same problem found on FairPhone4 with Android 12
I'd like to move to some other internal folder rather than adding a SD card
trying to move to "manual specified" folder fails with permission error EPERM
and "migration to common storage"fails with "can't find osm data in that folder"

**Comment by Borph** [comment]
I have to report the issue got resolved for me with Android 12! The size of the volume gets shown correctly, too, what wasn't the case before, and migration is offered and successful. Samsung S10 with lineage OS, updated from 18 to 19.
