### ISSUE TITLE
Osmand open a GPX file without some tracks

### ISSUE THREAD

**Issue by XR-01** [osmandapp/OsmAnd#14189]
### Description
When I try to open the GPX file attached, Osmand open it but whitout some tracks.
The file is created with QMapShack, I tried to open it with www.gpsvisualizer.com without problem. 

I upgrade this file with more tracks some times in a month, ad I still using the same GPX (upgradeted) alwais crated with QMapShack from some years, and Osmand open it without problem in the past.

QMapShack can save the GPX "1.1 without extension" and with this method Osmand open correctly the GPX (but I never had to use this type of GPX saving before).

### How to reproduce?
You can find attached the GPX file that Osmand don't open correctly, and the GPX saved in "1.1 without extension" that Osmand open correctly.

[Osmand_bug.zip](https://github.com/osmandapp/OsmAnd/files/8608698/Osmand_bug.zip)

### Your Environment
OsmAnd Version: 4.1.11
Android/iOS version: Android 11
Device model: Motorola Defy 2021

also reported the same bug with:

OsmAnd Version: 4.1.11
Android/iOS version: Android 10
Device model: BlackView BV6300Pro

**Comment by dmpr0** [comment]
History_Toscana.gpx error while import
<img src="https://user-images.githubusercontent.com/9365308/166638764-4cef70e7-8fb6-4a6c-996e-b1cd5d1131fe.png"  width="300" height="auto"/>

**Comment by vshcherb** [comment]
You need to add to topline of History_Toskana.gpx -  xmlns:osmand="https://osmand.net"
```
<gpx xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd http://www.garmin.com/xmlschemas/GpxExtensions/v3 http://www.garmin.com/xmlschemas/GpxExtensionsv3.xsd http://www.garmin.com/xmlschemas/TrackPointExtension/v1 http://www.garmin.com/xmlschemas/TrackPointExtensionv1.xsd http://www.garmin.com/xmlschemas/WaypointExtension/v1 http://www.garmin.com/xmlschemas/WaypointExtensionv1.xsd http://www.qlandkarte.org/xmlschemas/v1.1 http://www.qlandkarte.org/xmlschemas/v1.1/ql-extensions.xsd http://www.cluetrust.com/XML/GPXDATA/1/0 http://www.cluetrust.com/Schemas/gpxdata10.xsd" xmlns:gpxtpx="http://www.garmin.com/xmlschemas/TrackPointExtension/v1" version="1.1" xmlns="http://www.topografix.com/GPX/1/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:gpxx="http://www.garmin.com/xmlschemas/GpxExtensions/v3" xmlns:wptx1="http://www.garmin.com/xmlschemas/WaypointExtension/v1" xmlns:ql="http://www.qlandkarte.org/xmlschemas/v1.1" xmlns:gpxdata="http://www.cluetrust.com/XML/GPXDATA/1/0" xmlns:rmc="urn:net:trekbuddy:1.0:nmea:rmc" creator="QMapShack 1.16.1 http://www.qlandkarte.org/" xmlns:tp1="http://www.garmin.com/xmlschemas/TrackPointExtension/v1" xmlns:osmand="https://osmand.net">
```

**Comment by XR-01** [comment]
Hi, thank you for the reply. Note that if I add the GPX directly in the \tracks folder, Osmand open it without any error, but some tracks is missing.

So the problem is caused by an update of QmapShack (in the export process of the GPX) or in a newer version of Osmand? I have always used QmapShack and Osmand and I never see this error!

Thank you for your time!

**Comment by vshcherb** [comment]
Good question actually, the track is created by many programs so it's hard to say which program skipped this xmlns:... Obviously if the track couldn't be parsed then it creates internal errors and results are ignored on the screen
