### ISSUE TITLE
Navegación

### ISSUE THREAD

**Issue by Jiuvel** [osmandapp/OsmAnd#14184]
# 🚀 feature request

### Describe alternatives you've considered

Saludos a todo el equipo de Osmand, espero que se encuentren bien:

Mi nombre es Jiuvel, soy fiel admirador y usuario de la aplicación. Les escribo esta vez como otras para hacer una sugerencia con la intención de contribuir a que Osmand sea cada día mejor.
La misma es que se debe implementar la opción de que en la línea de ruta al navegar se muestren los semáforos y señales de Pare presentes en la ruta y que esto sea acompañado de indicaciones por voz.  Algo así fue implementado por Google Maps recientemente.

Eso ayudaría a los conductores si se distrajeran en la conducción, evitando así accidentes.

Sin más por ahora, y siempre con el animo de contribuir con el perfeccionamiento de Osmand, han creado una muy buena aplicación, los exhorto a que continúen trabajando así en aras de su creciente desarrollo.

Jiuvel

**Comment by tradavyvy** [comment]
Dear Juvel,
I think what you want is already implemented.
Try navigation settings - car - spoken instructions - traffic warnings.

**Comment by tradavyvy** [comment]
Dear Juvel,
Try to give your questions in english so more people can try to help thinking about solutions.
Thanks.

**Comment by Jiuvel** [comment]
Hello, I know that they were implemented on screen alerts and voice 
indications of traffic incidents but does not indicate when there is a 
traffic light or when there are signs of stop, that possibility should be 
added.

**Comment by vshcherb** [comment]
There is already recently opened another issue about traffic signs actually
