### ISSUE TITLE
Orientación de mapa

### ISSUE THREAD

**Issue by Jiuvel** [osmandapp/OsmAnd#14188]
### Your Environment
OsmAnd Version:
Android/iOS version:
Device model:

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

Hola
Se debería mejorar la estabilidad cuando la orientación del mapa esta seleccionada en: dirección al movimiento. En muchas ocasiones estando estático, el mapa gira de un lado a otro como si estuvieras en movimiento. Saludos.

**Comment by scaidermern** [comment]
Try to adapt the following setting:
Settings -> Profile -> Navigation settings -> Map during navigation -> Map orientation threshold.

The default is set to 0 km/h. Maybe you want to try a higher setting, e.g. 5 km/h or 7 km/h.

**Comment by vshcherb** [comment]
I think @scaidermern answer should be enough

**Comment by Jiuvel** [comment]
Hello, the orientation threshold is implemented when you are in navigation 
mode, but it should also be implemented by when you are in view map.

**Comment by vshcherb** [comment]
You can probably use Kalman Filter when you're in view map to minimize map rotation distortion
