### ISSUE TITLE
Invisible text

### ISSUE THREAD

**Issue by kritik** [osmandapp/Osmand#1419]
Phone Nexus 5 Latest android, Latest paid osmand.

on search and maps download letters in white color with white background. When you type and hold then background becomes grey and you can read

**Comment by dmpr0** [comment]
I have Nexus 5 with latest Android and OsmAnd version, but i can't reproduce this bug.
What version of android do you have?

**Comment by kritik** [comment]
5.1.1 Do I need to make screenshot?

By the way, I found that at least one more user has the same problem https://play.google.com/store/apps/details?id=net.osmand.plus&reviewId=Z3A6QU9xcFRPRkpWLUZReE5qUUludEtkWEpTV0tncDBvRHRTbWtjSkIwMzdINC1lTDlobmdrb1E4UVg4cjF1ZFY3N2pUYy1nc3RPWlVHOVNndm1mRGRRQUdv&hl=en

**Comment by vshcherb** [comment]
Yes screenshot would be good

**Comment by kritik** [comment]
You're welcome

https://www.dropbox.com/s/67cwaaxkmu59rd3/2015-06-30%2008.26.09.png?dl=0
https://www.dropbox.com/s/802he6sa0wtsnbt/2015-06-30%2008.24.46.png?dl=0
https://www.dropbox.com/s/emtacjoxtalcd4f/2015-06-30%2008.24.37.png?dl=0

**Comment by vshcherb** [comment]
And does another theme works fine?

**Comment by kritik** [comment]
Yes, when I have chosen Day mode - everything works. Thanks!

May be day mode should be selected by default?

**Comment by vshcherb** [comment]
Yes day mode is default since OsmAnd 2.1, but we will investigate that issue anyway.

**Comment by kritik** [comment]
I think it is because I use osm and from very old-old version and never have changed this setting. I use it before current phone. Can it be an issue?

**Comment by GaidamakUA** [comment]
Good day to you. Can you help us investigate please. If you change your theme back, does the issue remains?

**Comment by kritik** [comment]
Hi, I cannot. Before it was unselected. Currently is selected (1 of 2). How can I unselect?

**Comment by unhammer** [comment]
I had the same issue.

I solved it by clicking the lower-left square, then the upper left hamburger, then Settings (or whatever it's called in English), then General settings, then Theme, then just selecting one of the themes. Either theme seems to work fine, now that I've selected at least one.

Ideally, Osmand would notice when neither theme is selected and pick one.

**Comment by kritik** [comment]
It would be better to have default value ;)
