### ISSUE TITLE
Track is visible after back from My Places

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#14192]
# Review
- [ ] Back to My Places closes all groups and loses focus state - change activity state 
- [x] Tap on the map should keep track visible (not hide it)
* Regression: If the track was hidden, and user opened it from My Places > Track, taping on map close context menu and should enable track visibility on the map (it's how it works in 4.1)
- [x] If track is hidden, trying to open **Split interval**, leads to crash. [exception (14).log](https://github.com/osmandapp/OsmAnd/files/8843843/exception.14.log)
- [x] Show/hide icon, should represent action (not state).
• If track is visible, icon _ic_action_hide_
• If track is hidden, show _ic_action_show_

----------------

Track is visible after back from My Places.
Important: The switch was not enabled to show on map, though after back it stays enabled
Question: can we keep scroll & groups at same place My Places

**Comment by dmpr0** [comment]
# Review
- [ ]  If track is hidden, trying to open **Split interval**, leads to crash. [exception (14).log](https://github.com/osmandapp/OsmAnd/files/8843843/exception.14.log)

- [ ] Show/hide icon, should represent action (not state).
• If track is visible, icon _ic_action_hide_
• If track is hidden, show _ic_action_show_

Device and build info.
Device : CAP_sprout
Brand : Nokia
Model : Nokia 5.3
Product : CaptainAmerica_00WW
Build : 00WW_2_210_SP07
Version : 11
App Version : OsmAnd~
Apk Version : 4.3.0#34152m 4300

**Comment by cepprice** [comment]
https://github.com/osmandapp/OsmAnd/pull/14596
