### ISSUE TITLE
Missing strings to translate

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#14190]
In the following screenshots, I highlighted in red the strings that were not included in the translation.

![Screenshot_2022-04-29-13-03-51-854_net.osmand.plus~2.jpg](https://user-images.githubusercontent.com/12549744/166434748-444ac0a8-4c62-4008-b7a8-a47c1db1d444.jpg)

Note that there is still a problem with text formatting.
![Screenshot_2022-04-29-02-50-08-048_net.osmand.plus~2.jpg](https://user-images.githubusercontent.com/12549744/166434768-2de13aa5-a3cb-4454-b79d-3bbd33b84662.jpg)

![Screenshot_2022-04-28-01-51-40-687_net.osmand.plus~2.jpg](https://user-images.githubusercontent.com/12549744/166434780-0c332dae-500e-485b-8cc6-1906e2cba6b9.jpg)

### Your Environment
OsmAnd Version: OsmAnd~ 4.2.0#33957m, дата выпуска: 2022-05-03
Android version: 12
Device model: poco x3 pro

**Comment by Nine-Tailed** [comment]
![Screenshot_2022-05-03-13-02-14-120_net.osmand.plus~2.jpg](https://user-images.githubusercontent.com/12549744/166435595-1ae7b8ab-fa5f-4a20-a7ed-afc203182dcb.jpg)

**Comment by dmpr0** [comment]
# Review
- [ ]  We don't need strings about temperature isolines
