### ISSUE TITLE
recycling container / POI info text

### ISSUE THREAD

**Issue by flohoff** [osmandapp/Osmand#1420]
Hi,

it would be very nice if the recycling container POI info text could list which types of meterials this container takes. Glass/Paper/Cloths etc. 

Container might also contain "opening_hours" which are the times when usage is allowed.

Flo

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/5ad95e9c14a59f3f4eeb7c1a6888e160e102ee58
https://github.com/osmandapp/Osmand/commit/7e1e0d54b601a97d68f9ef7042c275730da8236c
