### ISSUE TITLE
Hike/Trek/Walk: improve time estimation (use DIN 33466)

### ISSUE THREAD

**Issue by tenzap** [osmandapp/OsmAnd#14200]
# 🚀 feature request

### Description

When navigation with type "walk" improve estimation of hike/walk/trek duration by supporting DIN 33466 standard.

### Describe the solution you'd like

I don't know how exactly hike duration is estimated, but it may not always be accurate, especially when there is a high elevation gain.

Briefly from what I read on various sites DIN 33466 permits to estimate a walk duration.
You can find the computing method [here](https://www.wanderndeluxe.de/en/wanderzeit-berechnen-strecke-hoehenmeter/). I copy it below in case the site disappears in future:

**Calculation rules for the hiking time**

In order to estimate the walking time for a planned hiking route, the height difference and the horizontal distance are first considered separately and the respective time requirement is calculated separately. Different speeds are assumed according to the DIN standard:

-    4 kilometers per hour in the horizontal direction
-    300 vertical meters in the ascent per hour
-    500 meters of descent per hour

However, the time required for the horizontal and vertical must not simply be added up. Instead, the travel time is calculated using the following formula: Larger value + (Small value / 2). Or in other words:

Travel time = Max (time required for horizontal distance, time required for altitude) + Min (time required for horizontal distance, time required for altitude) / 2

On steep hiking trails with many meters of altitude, the horizontal distance is less important. Conversely, if you have a long, flat route, you can manage a few meters in altitude.

Our example from above is calculated as follows:

- For the distance of 8 km, 2:00 a.m. are estimated (4 km / h).
- For the ascent and descent, 3:12 hours are calculated (ascent: 600m through 300m / h = 2:00 hours, descent: 600m through 500m / h = 1,2h = 1: 12h).
- Since the 2: 00h for the horizontal route is smaller than the 3: 12h for the vertical meters, the route is only included in the overall calculation with 2: 00h by 2 = 1: 00h.
- The net travel time is 1: 00h + 3: 12h = 4: 12h

**Optionally**
Website also mentions:

> As a rule, a buffer of 20% should be included in the net travel time for short breather and drinking breaks. Who plans to take a long lunch break or something along the way? must also take this into account. 

Maybe this can be an option to enable for duration estimation

**Additional idea**

Maybe there exist other norms, or other calculation methods used by some hiking organization depending on the mountain massif, so there could also be in future
- an option to choose which norm, computing method to use, 
- a way to parametrize the 4km/h 300m/h 500m/h (some hikers are more/less performant than that)

### Describe alternatives you've considered

Maybe this already exists in the app, but I can't find where.

### Additional reference:
https://de.wikipedia.org/wiki/Marschzeitberechnung [[EN](https://de-wikipedia-org.translate.goog/wiki/Marschzeitberechnung?_x_tr_sl=auto&_x_tr_tl=en)]

**Comment by sonora** [comment]
Currently we use Naismith's rule, I think I implemented this in OsmAnd around 2017. Naismith is a little more ambitious than DIN 33466, and I have to say I have quite reasonable experience with it. But then I am somewhat of a' professional hiker' ;) and things largely depends on your hiking habits and fitness.

**Comment by tenzap** [comment]
Interesting. I thought it was simply 4km/h (as this is the value that can be set for default speed in the "vehicle characteristics" for 'walk' profile)

Now let's take a route of:
9.73km (~6 miles) & 423m (1387ft) ascent & 425m descent. OSMAnd reports 3h17 duration

But I can't find this with [naismtih](https://en.wikipedia.org/wiki/Naismith%27s_rule) rule `1 h / 3 mi (5 km) + 1 h / 2000 ft (600 m)` : 6/3 + 1387/2000 = 2+0.69 = 2h41

Maybe the rule in OSM is a little bit more complex and add some corrections.

BTW, I just discovered this interesting tool here: https://trailsnh.com/tools/hiking-time-calculator.php (it doesn't mean this has to be implemented)

**Comment by sonora** [comment]
Make sure you activate the option "Use elevation data", on the navigation dialog, and you have downloaded the elevation data for the region.

Naismith simply adds an hour hiking time for every 2000ft (600m) ascent to your horizontal hiking time, which we calculate via the set default speed, if I remember correctly.

**Comment by tenzap** [comment]
What is the name of the 'elevation data' when downloading the data? I haven't found anything of that name to download.

**Comment by sonora** [comment]
It's the "Contour lines" download. Must have OsmAnd's Contour lines plugin installed for this to work, I think.

**Comment by paulatz** [comment]
I think it can be confusing that even when the option to use elevation data is enabled, the "speed" diagram in the "analyse on map" screen always shows a constant "15min/km" speed. Offtopic: the choice to have "Time" instead of distance on the horizontal axis would be greate.

![Screenshot_20220804-171654_OsmAnd+](https://user-images.githubusercontent.com/1267620/182883946-d2280fdf-a181-4f9c-8c53-a17690f8fca4.jpg)
![Screenshot_20220804-171658_OsmAnd+](https://user-images.githubusercontent.com/1267620/182883952-732275fc-3bbb-4308-bfe2-09fb3fdd247c.jpg)
![Screenshot_20220804-171707_OsmAnd+](https://user-images.githubusercontent.com/1267620/182883958-92c628f2-c38c-46a9-8811-ddec4328ecfe.jpg)

**Comment by sonora** [comment]
DIN 33466 is what the German Alpine Club has adopted. OsmAnd's code currently uses what the Swiiss Alpine Club takes, both are documented here https://de.m.wikipedia.org/wiki/Marschzeitberechnung (in Gerrman). The differences are not enormous,with the Swiss method being slightly more ambitious.

Hence I think you could expect an "improvement" only in the case you find OsmAnd's current estimates slightly too optimistic. On the scale to which personal fitness enters the 'true' situation, the difference between the two methods may actually be found negligible.

**Comment by paulatz** [comment]
I've used Osmand this week to plan a two hour walk divided in two segments, and the estimated time was within 10% of the elapsed one. The uphill part was slightly overestimated, the downhill underestimated, but the path quality is very different. (I was walking with a 9-year-old, but no weight and relatively fast). I think what ever algorithm is used it is decent enough.
![Screenshot_20220805-182541_OsmAnd+](https://user-images.githubusercontent.com/1267620/183123368-0d417a81-4615-4956-9cfd-0521cb609ff3.jpg)
![Screenshot_20220805-182429_OsmAnd+](https://user-images.githubusercontent.com/1267620/183123372-7031dcbb-6726-4b84-9243-56e9465e6376.jpg)

**Comment by sonora** [comment]
Thanks for the feedback! My experienxe exactly in recent years.

The slight adjustment I introduced today would primarily  create the  possibilty to adjust things also for trail runners. If no adjustment to the profile's default speed is made, like likely how the majority of users would handle it, there a no decisive changes except shifting a little towards the cautious side, avoiding underestimating travel times, probably a prudent thing to have.

**Comment by sonora** [comment]
@paulatz
- I have fixed the speed display for the pedestrian"Analyze on map" graph, now showing the slope-dependent projected speed for the "Use elevation data" case. 
- Time selection for the x-axis on the graph has been available for some time now.
- There seems an old (and unrelated) glitch which needs investigating, have opened it here: #15022.

**Comment by hiketimecalculator-oss** [comment]
Hi! I created an an app to calculate the hiking time by using the DIN formula you mentioned and considering ascent and decent: https://hiketime.lovable.app/
I'd love to hear if you find it useful and if there is a feature you are missing. ;-)
