### ISSUE TITLE
highlighted route often obscures street name

### ISSUE THREAD

**Issue by MarkG-108** [osmandapp/OsmAnd#14213]
### Description
When I'm cycling, I'll sometimes use OsmAnd. It's helpful. But, when I try to follow a route that it has suggested, via its navigation, I find that I can't see the street names under the yellow arrow highlighting. Not knowing the street name gives me no clue what to be on the lookout for. Because I'm cycling, I often can't hear the prompts (my phone is in a fanny pack -- I pull it out occasionally to try and check my progress -- but again, due to not being able to see the street names on the route, it's difficult).

### How to reproduce?
Use the navigation feature.

### Your Environment
OsmAnd Version:  4.1.11
Android/iOS version:  LineageOS 14.1 (Android 7.1.2)
Device model:  Nexus 5

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
Toronto Standard map.

**Comment by michaelblyons** [comment]
Related suggestion: #6444

**Comment by vshcherb** [comment]
Actually this issue is fixed with OpenGL rendering.
