### ISSUE TITLE
Index=1, length =1 error 

### ISSUE THREAD

**Issue by Wizit38** [osmandapp/OsmAnd#14215]
### Description
My previous ticket was closed but this error is still occurring in version 4.1.11

### How to reproduce?
In cycling profile, 
End point 1.32607 103.66086
Start point 1.37269 103.85139

(ps: brouter has no problem finding a route) 

### Your Environment
OsmAnd Version: 4.1.11
Android/iOS version: 11.0
Device model: huawei mate 20 pro 

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
Offline map. Singapore 1 Apr 2022

**Comment by vshcherb** [comment]
Please try https://download.osmand.net/latest-night-build/OsmAnd-default.apk nightly version or wait beta release coming next week. There are manu changes so far.

**Comment by varac** [comment]
Please release a new version on F-Droid, this is a pretty severe regression which breaks offline navigation completely for me.

**Comment by varac** [comment]
Similar: #13984

**Comment by varac** [comment]
> Please try https://download.osmand.net/latest-night-build/OsmAnd-default.apk nightly version or wait beta release coming next week. There are manu changes so far.

I installed the nightly and it doesn't find my favorites / downloaded maps anymore. Is there any documentation how to recover my old data ?

**Comment by Terramoto** [comment]
Hello,

I'm experiencing the same issue, is this a non-gapps version of Osmand? I can't get a lock with this OsmAnd-default.apk.
