### ISSUE TITLE
Update link to Генштаб Marshruty.ru

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#14212]
New link:
https://maps.marshruty.ru/ml.ashx?x={1}&y={2}&z={0}&i=1&al=1
![image](https://user-images.githubusercontent.com/12549744/166942709-bc81ecfb-4fe4-4b27-9fce-f5a37454c1a1.png)

**Comment by vshcherb** [comment]
Делайте pull request https://github.com/osmandapp/web/blob/main/main/static/tile_sources.xml#L121
