### ISSUE TITLE
aerialway=goods is not rendered

### ISSUE THREAD

**Issue by martenjj** [osmandapp/Osmand#1421]
These types of aerialway (German: Materialbahn) are currently not rendered at all.  They are not useful for routing, of course, but they are large features which may be present in otherwise sparse areas and so would be useful for orientation.

I've prototyped a rendering using the same line pattern and visibility as passenger aerialways, but in a similar brown colour to tracks (by association).  Not sure whether this should be always be visible in the default renderer, though, or maybe it should appear only in a specialised view such as hiking.  Comments welcome.

Screenshot - the goods aerialway is on the right:

![aerialway-goods](https://cloud.githubusercontent.com/assets/10631760/8409492/2add493e-1e70-11e5-9d5e-b386d9fe36a1.png)

**Comment by xmd5a2** [comment]
Fixed
