### ISSUE TITLE
"Could not parse geo intent"

### ISSUE THREAD

**Issue by 9662** [osmandapp/Osmand#1422]
**OsmAnd~ v2.1.1**

In your phone's address book enter the following address (for example):
```
Spiegelgasse 4
Wien 1010
```

Now tap on it (should launch OsmAnd, assuming that you do not have any Google cruft installed)

**What I expect:** A map will be shown displaying the address above (I do have Austria vector maps).

**What happens:** A message appears saying "Could not parse geo intent" (see screenshot).

![screenshot_2015-06-29-17-43-23](https://cloud.githubusercontent.com/assets/13080040/8412156/404db94e-1e88-11e5-9361-4822f19a5a34.png)

**Comment by vshcherb** [comment]
Duplicated for geo intent searches from address book, this feature is not properly working
