### ISSUE TITLE
OpenGL: text labels sometimes cropped at the bottom

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#14243]
With enabled OpenGL rendering the text of some labels is cropped at the bottom:

![03](https://user-images.githubusercontent.com/1040784/167597527-cc552b34-3508-42c1-80eb-b398479603f3.jpg)

In this example the second line "Tor" is cropped. This is especially visible for the letter "o" which is missing the bottom part.

**Comment by Dima-1** [comment]
Request
[Core](https://github.com/osmandapp/OsmAnd-core/pull/341)

**Comment by Zirochkabila** [comment]
https://osmand.net/map?end=33.051092%2C-117.262176&mode=car#17/50.27221/18.99225

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/189129527-97d5c806-d081-4d54-8186-a1b03b7e66f2.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  


as well as the direction arrows, at a zoom of 17 2.7 or 16 4.1
https://osmand.net/map?end=33.051092%2C-117.262176&mode=car#17/50.24892/18.88855
https://osmand.net/map?end=33.051092%2C-117.262176&mode=car#17/50.26836/18.99023
https://osmand.net/map?end=33.051092%2C-117.262176&mode=car#17/50.26320/18.98804
https://osmand.net/map?end=33.051092%2C-117.262176&mode=car#17/50.25606/18.96286

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/189130321-b28ed0b4-aaf4-4e79-a0c9-262cd63943c6.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>
