### ISSUE TITLE
All previous downloaded maps are gone after update

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#14240]
### Description
Again, after performing the update to 4.2.0 all previous downloaded/installed maps (multiuser 1) are deleted.

### Your Environment
OsmAnd Version: update to 4.2.0
Android/iOS version: 12
Device model: Samsung Galaxy S20+

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by vshcherb** [comment]
Possibly related to https://github.com/osmandapp/OsmAnd/issues/4299

**Comment by Rowin63** [comment]
And to here #13404 too...

**Comment by Rowin63** [comment]
Happens also on my Samsung Tab S6 / Android 12. 
Update from 4.1.x to 4.2.0, all maps are gone (data folder is multiuser 1).

I was expecting this issue to be solved in 4.2. ...?

**Comment by vshcherb** [comment]
Indeed it's duplicate, and the issue is not resolved. The problem is not clear
