### ISSUE TITLE
"Configure screen / Reset to default" does not seem to reset the "Remaining Elements"

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#1424]
Subject line  almost says it all:

Go to "Configure screen", pick any app mode, then hit "Reset to default". It appears that the settings listed under "Remaining elements" in that menu are not reset correctly. Almost looks like they are untouched, or the menu screen refresh fails, even after re-opening that menu.

The code points are MapWidgetRegistry.java / resetDefaultAppearance, and OsmandSettings.java / getDefaultValue.

**Comment by vshcherb** [comment]
It was fixed 3 days ago (menu refresh problem). Please test it

**Comment by sonora** [comment]
Victor, I saw your fix correcting the menu refresh, and it works for the "Configure map" menu (where we had an issue for the menu refresh).  But the actual issue I report here for the "Configure screen" settings is still unchanged (June 30 nightly). I think this may not actually be an issue about menu (display) refresh, but it looks like the settings are actually not reset to default, in other words it rather looks like 
		settings.SHOW_DESTINATION_ARROW.resetToDefault();
		settings.TRANSPARENT_MAP_THEME.resetToDefault();
		settings.CENTER_POSITION_ON_MAP.resetToDefault();
does not have the desired effect.

**Comment by vshcherb** [comment]
Fixed
