### ISSUE TITLE
Opengl: names upside down.

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#14248]
Names of routes and roads upside down.
![IMG_20220510_180724.jpg](https://user-images.githubusercontent.com/12549744/167661653-7750c3cd-c1ea-405c-9160-cc1918f5e51d.jpg)
![Screenshot_2022-05-10-18-06-18-746_net.osmand.jpg](https://user-images.githubusercontent.com/12549744/167662171-aff6119d-57dc-4118-8937-ef6586fcbdf6.jpg)

### Your Environment
OsmAnd Version: OsmAnd~ 4.2.0#13480mqta, дата выпуска: 2022-05-10
Android version: 12
Device model: poco x3 pro

**Comment by ivanPyrohivskyi** [comment]
Core:
const auto shouldInvert =

Core-legacy:
textdraw.cpp inverse

**Comment by Dima-1** [comment]
Request:
[Core](https://github.com/osmandapp/OsmAnd-core/pull/333)
