### ISSUE TITLE
Crash on OsmAndMapCreator.bat

### ISSUE THREAD

**Issue by marthinet** [osmandapp/OsmAnd#14253]
It worked on the first time but now crash and seems to be looking for files that no longer exist.

I converted OSM files to OBF files.

Now, it creates a log file in the directory I previously declared as output (and recreate the dir if deleted)

I uninstalled and reinstalled with no success.
(delete directory, clean registry (ccleaner), looked and deleted "osmand" files)

Something seems to be memorized somewhere, but where ?

Log :
mai 11, 2022 9:28:03 AM net.osmand.osm.MapRenderingTypes initFromInputStream
INFO: Time to init poi types 42
mai 11, 2022 9:28:03 AM net.osmand.binary.BinaryMapIndexReader searchMapIndex
INFO: Search is done. Visit 2516 objects. Read 2516 objects.
mai 11, 2022 9:28:03 AM net.osmand.binary.BinaryMapIndexReader searchMapIndex
INFO: Read 66 subtrees. Go through 129 subtrees.
mai 11, 2022 9:28:03 AM net.osmand.map.OsmandRegions structureWorldRegions
WARNING: Found orphaned regions: 1
mai 11, 2022 9:28:03 AM net.osmand.map.OsmandRegions structureWorldRegions
WARNING: FullName = World_seamarks parent=null
mai 11, 2022 9:28:03 AM net.osmand.swing.ExceptionHandler handle
SEVERE: Error in thread main
java.lang.NullPointerException
	at net.osmand.swing.DataExtractionSettings.getObfReaders(DataExtractionSettings.java:62)
	at net.osmand.swing.OsmExtractionUI.createUI(OsmExtractionUI.java:204)
	at net.osmand.swing.OsmExtractionUI.<init>(OsmExtractionUI.java:164)
	at net.osmand.swing.OsmExtractionUI.main(OsmExtractionUI.java:126)

### Your Environment
Windows 11

**Comment by vshcherb** [comment]
Please specify maps folder for OBF files, it crashes cause it can't access folder with maps

**Comment by marthinet** [comment]
Thank you for our answer

I have modified my batch.xml file to point to my folder F:/Python_Sources/osm/OBF  and set false everywhere :

<?xml version="1.0" encoding="utf-8"?>
<batch_process>
	<process_attributes mapZooms="" renderingTypesFile="" zoomWaySmoothness=""
		osmDbDialect="sqlite" mapDbDialect="sqlite"/>
	<process directory_for_osm_files="F:/Python_Sources/osm/OBF" directory_for_index_files="F:/Python_Sources/osm/OBF" directory_for_generation="F:/Python_Sources/osm/OBF"
		skipExistingIndexesAt="F:/Python_Sources/osm/OBF" directory_for_srtm_files="F:/Python_Sources/osm/OBF" indexPOI="false" indexRouting="false" indexMap="false" indexTransport="false" indexAddress="false">
	</process>
</batch_process>

My F:\Python_Sources\osm\OBF folder contains:
- the log updated with the crash
- monaco.osm
- monaco.pbf


Same crash it seems :
mai 11, 2022 12:51:53 PM net.osmand.osm.MapRenderingTypes initFromInputStream
INFO: Time to init poi types 44
mai 11, 2022 12:51:53 PM net.osmand.binary.BinaryMapIndexReader searchMapIndex
INFO: Search is done. Visit 2516 objects. Read 2516 objects.
mai 11, 2022 12:51:53 PM net.osmand.binary.BinaryMapIndexReader searchMapIndex
INFO: Read 66 subtrees. Go through 129 subtrees.
mai 11, 2022 12:51:53 PM net.osmand.map.OsmandRegions structureWorldRegions
WARNING: Found orphaned regions: 1
mai 11, 2022 12:51:53 PM net.osmand.map.OsmandRegions structureWorldRegions
WARNING: FullName = World_seamarks parent=null
mai 11, 2022 12:51:53 PM net.osmand.swing.ExceptionHandler handle
SEVERE: Error in thread main
java.lang.NullPointerException
	at net.osmand.swing.DataExtractionSettings.getObfReaders(DataExtractionSettings.java:62)
	at net.osmand.swing.OsmExtractionUI.createUI(OsmExtractionUI.java:204)
	at net.osmand.swing.OsmExtractionUI.<init>(OsmExtractionUI.java:164)
	at net.osmand.swing.OsmExtractionUI.main(OsmExtractionUI.java:126)

**Comment by marthinet** [comment]
<process directory_for_osm_files="F:/Python_Sources/osm/OBF" directory_for_index_files="F:/Python_Sources/osm/OBF" directory_for_generation="F:/Python_Sources/osm/OBF"
		skipExistingIndexesAt="F:/Python_Sources/osm/OBF" directory_for_srtm_files="F:/Python_Sources/osm/OBF" indexPOI="false" indexRouting="false" indexMap="false"
		indexTransport="false" indexAddress="false">

**Comment by marthinet** [comment]
Edit 👍 <?xml version="1.0" encoding="utf-8"?>
<batch_process>
<process_attributes mapZooms="" renderingTypesFile="" zoomWaySmoothness=""
osmDbDialect="sqlite" mapDbDialect="sqlite"/>
<process directory_for_osm_files="F:/Python_Sources/osm/OBF" directory_for_index_files="F:/Python_Sources/osm/OBF" directory_for_generation="F:/Python_Sources/osm/OBF"
skipExistingIndexesAt="F:/Python_Sources/osm/OBF" directory_for_srtm_files="F:/Python_Sources/osm/OBF" indexPOI="false" indexRouting="false" indexMap="false"
indexTransport="false" indexAddress="false">
</process>
</batch_process>

**Comment by marthinet** [comment]
Edit:
<process directory_for_osm_files="F:/Python_Sources/osm/OBF" directory_for_index_files="F:/Python_Sources/osm/OBF" directory_for_generation="F:/Python_Sources/osm/OBF"
skipExistingIndexesAt="F:/Python_Sources/osm/OBF" directory_for_srtm_files="F:/Python_Sources/osm/OBF" indexPOI="false" indexRouting="false" indexMap="false"
indexTransport="false" indexAddress="false">

**Comment by vshcherb** [comment]
Probably you can use newer utlities.sh and script generation 1 by 1 file, cause this batch.xml is outdated to be honest, not sure it still used by us.
