### ISSUE TITLE
V4.2.0 Arrival time is always 01:00

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#14257]
### Description
Sice the last update the arrival time is always 1:00 and never changes.
And also it is not possible anymore to switch between arrival/remaining time. It has to be two widgets now. I dont need both informations at the same time, switching was nice.

### How to reproduce?
Try it ;-)

### Your Environment
OsmAnd Version: 4.2.0
Android/iOS version: 12
Device model: S20+, S20FE

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
![arrival time](https://user-images.githubusercontent.com/95540936/167836497-72022cf1-2419-4dd7-9fe4-ce44d65de614.JPG)

**Comment by vshcherb** [comment]
Interesting
