### ISSUE TITLE
OpenGL: Touching of hiking routes not possible

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#14252]
With enabled OpenGL rendering it is not possible to tap on hiking routes to obtain more information about them.

**Comment by ivanPyrohivskyi** [comment]
MapSelectionHelper

**Comment by Dima-1** [comment]
Requests:
[Core](https://github.com/osmandapp/OsmAnd-core/pull/327)
[Android](https://github.com/osmandapp/OsmAnd/pull/14389)
