### ISSUE TITLE
Add  a support of Santali (sat) language

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#14269]
Currently, Santali is translated for 16 % https://hosted.weblate.org/projects/osmand/main/sat/, but users have already added a lot of addresses translated to OSM.

**Comment by Cloud-Prakash** [comment]
Still unable to change OsmAnd App  interface and Map Interface into Santali (Ol Chiki). Previously team said that it was added in system (Device language) but it does not work as Santali (sat) is not available as system language in Android. Could it be added in the list of display language & map language.

**Comment by vshcherb** [comment]
Will be added soon

**Comment by Cloud-Prakash** [comment]
Thanks will test out
