### ISSUE TITLE
No clickable time widget, during navigation

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#14271]
### Description
Time widget does not work when navigation starts (cannot be pressed)

### How to reproduce?
Open navigation, select start point, select finish point, start navigation (click Start), click on time widget
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/168074785-5a5e65e2-d14b-4748-bf0c-da71e132c427.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table> 

### Your Environment
OsmAnd Version: 4.2.0#13484mqta
Android/iOS version: MIUI GLOBAL 12.5.5 Android 11
Device model: POCO X3

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by vshcherb** [comment]
Probably we can change it back to make configurable widget

**Comment by scaidermern** [comment]
Maybe three different widgets? Arrival time, duration, arrival time & duration (toggle button).

**Comment by pebogufi** [comment]
With nightly 34074 2022-05-23 toggle widget works perfectly like older versions
