### ISSUE TITLE
Does not work what's new

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#14273]
The page with the description of what's new does not load.
![Screenshot_2022-05-12-20-01-41-238_com.vivaldi.browser.jpg](https://user-images.githubusercontent.com/12549744/168130220-67c52941-4c67-464b-9c67-4569b7f5dadb.jpg)

### Your Environment
OsmAnd Version: OsmAnd~ 4.2.0#34019m, дата выпуска: 2022-05-12
Android version: 12
Device model: poco x3 pro

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/commit/635d042fe98149c1ac063a2d16554b1e23554e0f
