### ISSUE TITLE
Arabic title rendering in OpenGL

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#14278]
### Description

We noticed the problem of the Arabic language with the English language, when the POI  name is Arabic and English, the Arabic appears as a segment as in the picture

![image](https://user-images.githubusercontent.com/44466116/168241855-5add98d1-408e-4180-98a2-855bd8ffe6c9.png)

![image](https://user-images.githubusercontent.com/44466116/168241900-e6b64224-d99e-4d7a-b69b-3b6c32a731a8.png)

### Your Environment
OsmAnd Version: 4.2
Android/iOS version: Android 11

**Comment by ivanPyrohivskyi** [comment]
bool OsmAnd::TextRasterizer_P::drawText(SkCanvas& canvas, const TextPaint& textPaint) const
{
    const auto text = ICU::convertToVisualOrder(textPaint.text.toString());

**Comment by ivanPyrohivskyi** [comment]
https://www.fileformat.info/info/unicode/char/200e/index.htm
