### ISSUE TITLE
offline map

### ISSUE THREAD

**Issue by katpatuka** [osmandapp/Osmand#1427]
After having activated online maps something seems to have changed in rendering with lower zoomlevels. More detailed map renders fine but zooming out gives me a message: 
Offline vector map present for location
But under 'Map Sources...' there is only online map which I could reactivate.

**Comment by vshcherb** [comment]
It suggests you to use World basemap offline, you can configure it in Online Map Plugin -> Settings -> Zoom to switch to offlline maps

**Comment by katpatuka** [comment]
Ok - you are right: that worked. I could set the 'Min. vector zoomlevel' to 9 and the "missing" zoomlevels showed up. And that means that it's still a bug: if 'Online map' is being deactivated the "standard" min. zoomlevel should apply again.
