### ISSUE TITLE
Current state of revision of Configure Screen

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#14279]
In the new revised version of Configure Screen I am missing two features, compared to the old version (of about early march).

- as @Rowin63  has pointed out in 
https://github.com/osmandapp/OsmAnd/issues/14257
"And also it is not possible anymore to switch between arrival/remaining time. It has to be two widgets now. I dont need both informations at the same time, switching was nice."

This point was not fixed, but the topic was closed. Two widgets need more space on the small smartphone screen.

- for the most of options it was possible to collapse them (or not). So it was possible to have to sets of options for each profile, a compact one, with less widgets, with better overview, for example when driving and a extended one with all information for special purpose.
And with only one single tap I can change between them, great !

Both features did work well !!
And I loved it and used it. 
For driving I went back to a nightly version of early march where the features are present.

**My question**: will theese two really great features be added in some days or are they lost for ever ?

**Comment by dmpr0** [comment]
We will join back "Arrival time/Time to go" for Destination and Intermediate.

Collapse functionality can be replaced with pages. So you can create a few pages, first from map viewing, second for navigation only with navigational widgets.

**Comment by pebogufi** [comment]
What do you mean with pages ? 
Profiles ?
ok, with more profiles it will work.
thanks a lot.

**Comment by vshcherb** [comment]
Collapse functionality is replaced with Widget Pages, you can create 2-3 pages of widgets and slide left / right instead of collapse widgets list

**Comment by pebogufi** [comment]
Got it, thanks.
