### ISSUE TITLE
Track import not working in route planning

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#14286]
### How to reproduce?
1. Open the menu and click on plan route
2. Click import track and select the desired file.
The file will not be imported.

### Your Environment
OsmAnd Version: OsmAnd~ 4.2.0#34026m, дата выпуска: 2022-05-13
Android version: 12
Device model: poco x3 pro

**Comment by Gbernardy** [comment]
... #13758 can be merged with this issue ...

**Comment by Zirochkabila** [comment]
#13758 

### Description
Try to do as shown in the video

### Steps to reproduce

1. Menu
2. Plan route
3. Import track
4. Select (Click in the top right corner of the track)


https://user-images.githubusercontent.com/104760013/168841940-edd0d2d9-2679-4b0d-8ff5-aa24eb072297.mp4

**Comment by Zirochkabila** [comment]
Please attach the file in question

**Comment by Zirochkabila** [comment]
That’s right, thank you.
When selecting a file via the "Plane route", it does not import, but when you add it through "My places" everything works
