### ISSUE TITLE
Updated POI shows "old" data (Modify POI shows "updated" data)

### ISSUE THREAD

**Issue by M4xTheMan** [osmandapp/OsmAnd#14285]
### Description
I've updated a POI using OsmAnd and uploaded it. Today I've checked the (updated) POI and only got the "old" version. Interestingly, the updated version is shown when I chose "Modify POI". From my point of view, it's the same behaviour described in this closed issue: https://github.com/osmandapp/Osmand/issues/6052

### How to reproduce?
- Modify a POI using OsmAnd
- Upload changes
- Open POI in OsmAnd

### Your Environment
OsmAnd Version: 4.1.11
Android version: 11 (LineageOS 18.1)
Device model: Samsung Galaxy S7 (SM-G930F)

**Maps used (online or offline):**   
Germany Schleswig-Holstein

**Comment by scaidermern** [comment]
Did you enable OsmAnd live for this area? Otherwise the updated POI information will only be visible after the next monthly update.

**Comment by M4xTheMan** [comment]
Yes, OsmAnd live is enabled.

**Comment by scaidermern** [comment]
Can you provide more details? Which POI did you edit? What is the date & time your map was last updated by OsmAnd (check download maps / updates / live updates / <your map>)?

**Comment by M4xTheMan** [comment]
Thank you very much for your fast reply. I think I've a problem regarding the live update on one device. It's working fine on a second mobile. I've removed the "problem map" from the first mobile, added it again, run the live update manually and now the map is up to date.

I'm observing the behaviour of this device. If there's still a problem regarding the live update, I'm going to open another issue (with a more appropriate title).

Thank you very much!
