### ISSUE TITLE
V4.2.0 importing tracks 

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#14281]
I am aware of that TET is not your business, but:
TET tracks consist of several sections (up to>30). Before it was possible to import each TET country-track as"one" track.
Now at the "import" all single sections are displayed but without possibility to import them as "one track". So this fills up "my places" with hundreds of single tracks
Unfortunately I can´t find a possibility, to import those racks again as "one track" each country.

<table style="width:100%">
  <tr>
    <td><img src="https://user-images.githubusercontent.com/95540936/168282369-a05b7764-e72e-4251-8a74-1c05b330b9e3.JPG"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/95540936/168282408-5c7d8b26-2fdd-428a-9834-d97d6a649329.JPG"  width="300" height="auto"/> </td>
  </tr>
</table> 
.

**Comment by vshcherb** [comment]
You can click import all or copy the files itself into folder.

**Comment by Rowin63** [comment]
Yes, copying the files directly into the folder is a solution. But until 4.1.11 l could do it this way: downloading any county-TET with the TET app. Selecting Osmand in the "open with'-menu. Then I had ONE country track in Osmand and not up to more then 30 (depending on the country) section-tracks. 

So Osmands behaviour is different now in v4.2.0

Greetings, Robert 


Sent from Nine

________________________________
Von: vshcherb ***@***.***>
Gesendet: Freitag, 13. Mai 2022 15:19
An: osmandapp/OsmAnd
Cc: Rowin63; Author
Betreff: Re: [osmandapp/OsmAnd] V4.2.0 importing tracks (Issue #14281) 

You can click import all or copy the files itself into folder.

**Comment by Rowin63** [comment]
I had a consultation with one of the TET admins.
There was no change in the way the TET-files were provided.

So this behaviour is Osmand-made.

**Comment by dmpr0** [comment]
## ToDo
We need to add a button, that would allow users to import file with multiply tracks as one track.
- [ ]  Add button **Import as one track**

<img src="https://user-images.githubusercontent.com/9365308/171000960-2a7050f9-93f6-480c-8d6c-a280e781412f.png"  width="300" height="auto"/>
