### ISSUE TITLE
Improve hillshade resolution

### ISSUE THREAD

**Issue by tzugen** [osmandapp/OsmAnd#14288]
The hill shading is too low resolution to be very useful in some mountain regions. Additionally the lightning source comes from North always which is controintuitive for place on the Northhalf of the globe. I would like to look at the code and make a PR. Where is it being generated?

**Comment by milanovitch44** [comment]
When you would eluminate the South side of the mountains you would get the impression of mountains caving in and rivers being higher. That's why the North side is eluminated while this won't actually happen on the Northern Hemisphere. When you flip the map with South up, the world gets turn upside down so could we inverse the hillshade when the users turns his map to South up?

**Comment by tzugen** [comment]
> When you would illuminate the South side of the mountains you would get the impression of mountains caving in and rivers being higher. That's why the North side is illuminated while this won't actually happen on the Northern Hemisphere. When you flip the map with South up, the world gets turn upside down so could we inverse the hillshade when the users turns his map to South up? Adding a West sided hillshade could make every rotation look good, but this doubles the file size. I wouldn't add more resolution to the hillshade files as they're quite big already, but we could maybe change the rendering so that it doesn't look as blocky.

I agree with the North/South part, I was earlier mistaken..

Regarding resolution, for hiking or mountaineering higher resolution would be really useful. But maybe the regions for high-res could be smaller cut? If you go mountaineering you don't need the hill shade of the whole country, only of that region..

**Comment by milanovitch44** [comment]
You can always use OsmAndMapCreator to generate .sqlitedb files from xyz tile urls.
(for zoom levels up to 12: https://osmscout.karry.cz/hillshade/tile.php?z={$z}&x={$x}&y={$y})

**Comment by timokoesters** [comment]
Would it be possible to use the contour lines to calculate shadows? I'd like to take a look at the code if you can point me to the relevant part.

**Comment by milanovitch44** [comment]
Using contour lines will likely be harder dan using raw height data (EU-DEM for example). I don't think that the shading is generated by code in this repository.

**Comment by sonora** [comment]
- The human brain is used to things being illuminated from the top, or from the side at most. Illuminating from the bottom creates a horror movie, or a camp fire effect at best ... :wink::wink::wink:
- Regarding locally-produced shading: Yes, it's of course possible to create from the contour line data, but would foreseeably be both laggy and battery-intensive...

**Comment by timokoesters** [comment]
To clarify, contour lines should only be used when zoomed in closely ( zoom level >= 16 ) and otherwise the normal hillshading should be used.
But maybe it's sufficient to apply some image processing (smoothing, sharpness) to the tiles and use that on all zoom levels

**Comment by dmpr0** [comment]
Implemented with new Height maps.
