### ISSUE TITLE
Add amenity=shower

### ISSUE THREAD

**Issue by Taxilof** [osmandapp/Osmand#1429]
Hi,
as far as i can tell, OsmAnd currently does not show public showers?!
The tag for this is "amenity=shower" as seen here:
http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dshower

Thanks

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/5db5d2a2f02d6291c87becd8b8e710f464539deb
