### ISSUE TITLE
Hard crash loading large route

### ISSUE THREAD

**Issue by duiveldoder** [osmandapp/OsmAnd#14295]
This is a severe issue, as it totally crashes the app and closes it.

The biggest issue I see here - is that the exception isn't catched and the user doesn't get any information.

Replication: 
-1) Loading the "Cordillera Great Traverse" aka "CGT" on OSMAnd.
-2) the app is "loading" for a long time locking up the phone, nothing you can do.
-3) the app crashes and OSMAnd is closed - a crash report is generated.

I'll add a small obf file with just the route and neighboring 1000m area so OSMAnd devs can easy test it themselves.

I also add the error log about the failed memory allocation, evidently the crash report claims Java or OSMAnd can't allocate anything over 16kB of memory. This sounds very weird to me, on 21st century  technology. 

If JAVA indeed can't handle anything beyond 16kB - then at least don't crash but catch the error and tell the user: 
"OSMAnd or Java can't handly anything beyond 16kB, please select a shorter route"

[exception.log.gz](https://github.com/osmandapp/OsmAnd/files/8696303/exception.log.gz)

Ah, I can't upload here an obf file - so I'll zip it.
[Josm_gct.obf.gz](https://github.com/osmandapp/OsmAnd/files/8696302/Josm_gct.obf.gz)

This is the OSM relation:
https://www.openstreetmap.org/relation/5416994

**Comment by vshcherb** [comment]
We probably would need to investigate native version for algorithm.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/pull/14889

**Comment by Dima-1** [comment]
https://github.com/osmandapp/OsmAnd/pull/14906
