### ISSUE TITLE
Automatic adding "Vehicle" parameter and not saving custom parameters in online routing URL

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#14300]
### Description
Automatic addition of parameter "Vehicle" in the URL string preview adding a engine for online routing

### Precondition

- Installed OsmAnd+
- User selected Driving profile
- Opened profile configuration
- Navigation settings
- Navigation type
- Online
- Pressed Add online routing engine

### Steps to reproduce
Select:

1. Type: Graphhopper
2. Vehicle: Custom (&profile=car&locale=de)
3. API key: 
4. Example: Amsterdam
5. URL preview: https://graphhopper.com/api/1/route?point=52.379189,4.899431&point=52.308056,4.764167&profile=car&locale=de&key=...............&details=lanes
6. Pressed Test route calculation button (OK status)
7. Clicked Save button
8. Navigation type
9. Settings (Graphhopper - &rofile=car&locale=de)

### Actual result
URL preview - "Vehicle" automatic addition of parameter

### Expected
URL preview - Display of saved parameters (https://graphhopper.com/api/1/route?point=52.379189,4.899431&point=52.308056,4.764167&profile=car&locale=de&key=.........&details=lanes)

### Your Environment
OsmAnd Version: 4.2.0#13500mqta
Android/iOS version: Android 11
Device model: POCO X3

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by nazar-kutz** [comment]
**Fix**
https://github.com/osmandapp/OsmAnd/pull/14390

**Comment by vshcherb** [comment]
1. Preview is not editable cause it leads to confusion for saving
2. Now in Custom Vehicle you can specify additional HTML parameters i.e.
2.1 'car&locale=de' - will specify in url 'vehicle=car' and extra parameter 'locale=de'
2.2 'car' - url 'vehicle=car' 
2.3 'profile=car&locale=de' - url will not have 'vehicle' but will have '&profile=car&locale=de'
