### ISSUE TITLE
RE: Support more values for club=* POIs

### ISSUE THREAD

**Issue by BikeRoad** [osmandapp/OsmAnd#14303]
Hi

Many values of the [club](https://wiki.openstreetmap.org/wiki/Key:club) key are not rendered nor do they have an icon assigned to represent them even though they are included in the rendering_type.xml file

This topic has already been discussed but only 5 values were worked on: freemasonry, sport, social, scout and music
[Support more values for club=* POIs](https://github.com/osmandapp/OsmAnd/issues/9190)
[Add support for club key on the map](https://github.com/osmandapp/OsmAnd/issues/10486)

POI example not rendering:
[Base Astronómica Santa Eulalia](https://www.openstreetmap.org/node/9744072436)

Please add more values

**Comment by scaidermern** [comment]
There was a comment from @vshcherb in #10486:
> I guess we would support only with more > 100 appearances

How about a generic icon for not yet supported club values? This will make every club POI visible (and searchable) on the map.
