### ISSUE TITLE
Change to vector maps only possible when the 'Online maps plugin is enabled

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#1431]
Small issue with our plugin handling: If you had Online maps enabled, and some online or raster tile source enabled, then later disable the plugin, you will on the map screen receive notifications that vector maps are available, and how to configure using them via "Map source...". But the issue is that this menu item now seems only available when the Online maps plugin is enabled?

I think we somehow need to make sure that changing back to vector maps is always possible. (or alternatively maybe is done automatically when the raster map plugin is disabled).

Also: I think while the online maps plugin is enabled its setting "Min vector zoom level" seems to be ignored, or have no effect? Does this setting still have any purpose at all, I think it may be a legacy thing to avoid former performance issues?

**Comment by vshcherb** [comment]
Fixed, the setting was active, but it is very confusing, so I decided to deprecate it.
