### ISSUE TITLE
Lower-resolution map tiles disappear when higher-resolution tiles are loading

### ISSUE THREAD

**Issue by Dollarius** [osmandapp/OsmAnd#14319]
I find Overlay Map Tiles extremely useful, and I always pre-cache a Strava heatmap layer so that I can use it offline during my rides/hikes (blue layer in the attached image).
With numbers referring to the attachment:
1. More/less detailed image tiles are used at larger/smaller zoom levels. Upon zooming in, OsmAnd downloads the more detailed map tiles.
2. However, during the time in which the more-detailed tiles are downloaded, the less-detailed tiles disappear, effectively leaving no tile shown on screen. This is often a problem when internet signal is poor (i.e., while hiking), because new tiles cannot be loaded.
3. The issue can be partially solved by putting the phone in Offline mode, so that OSMand does not attempt to load new tiles.

Since having a grainy tile is usually better than having no tile at all,
**Would it be possible to keep the lower-resolution tiles visible while higher-resolution tiles are downloaded?**

![OsmAnd_DisappearingTiles](https://user-images.githubusercontent.com/56419637/168974594-679d87cb-9dba-41f6-9810-f2b146214867.png)

### How to reproduce?
Enable online tiles of any kind (here using SQLiteDB format from AnyGis)

### Your Environment
OsmAnd Version: 4.2.0#33997m
Android/iOS version: 12
Device model: Samsung Galaxy S20 FE 5G (SM-G7810)

**Comment by vshcherb** [comment]
I think in OpenGL rendering it's solved

**Comment by Zirochkabila** [comment]
@Dollarius  Not reproduced
Try updating the application and using OpenGL rendering: Menu > Plugins > OsmAnd development > Use OpenGL rendering

**Comment by Dollarius** [comment]
@vshcherb and @Zirochkabila thank you for your input.
I really appreciate your help in solving this issue.

I just installed the latest nightly (OsmAnd-master-gnb-2022-09-30.pkg) and tried this out: it is still not solved.
Without an internet connection, tiles disappear beyond a certain zoom level (instead of using the lower-resolution pixelated tile, which would be more helpful).
I did not see any difference between OpenGL On/Off (I restarted the app after switching).

At the present moment, it is difficult to test this no-internet issue thoroughly in builds newer than 2022-07-15 because of this other (new) bug that forces tiles to be re-downloaded at all times.
https://github.com/osmandapp/OsmAnd/issues/15204

**Comment by vshcherb** [comment]
Same issue https://github.com/osmandapp/OsmAnd/issues/15174

**Comment by Dollarius** [comment]
@alex-osm @vshcherb still not solved: could you please re-open?
I re-run the same test today on the latest nightly:
1. with 3G network on, OsmAnd wants to load the higher-resolution tile and nothing is shown.
2. as soon as I switch to Flight mode, the lower-resolution tile is shown.
This behaviour forces the user to turn to Flight Mode when the Internet signal is low to load the cached tiles.
Thank you again for your help!

![image](https://user-images.githubusercontent.com/56419637/201532288-953d8c3a-1cc4-4249-a706-77851cc914ca.png)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.3.0#13945mqta, released: 2022-11-14
**Not Reproduced** - with 3G mode enabled and in flight mode, the result is the same.

Testing without OpenGL

1. 3G mode is enabled - rendering takes place up to 500m (cache), and then the download starts 
2. Flight mode is enabled - the same result


https://user-images.githubusercontent.com/104760013/201643639-16460ce6-70fc-43b2-8348-38b8560cf67a.mp4


https://user-images.githubusercontent.com/104760013/201643688-d8dda119-4cc4-4369-ae70-f94092a3a6a9.mp4


Testing with OpenGL

1. 3G mode is enabled - rendering takes up to 50m, and then the download starts 
2. Flight mode is enabled - the same result



https://user-images.githubusercontent.com/104760013/201644950-f66879d1-3239-417b-8800-c92fcd537271.mp4


https://user-images.githubusercontent.com/104760013/201644654-b60cf685-26db-4d14-b8ff-da853f87b62f.mp4

**Comment by Dollarius** [comment]
@Zirochkabila thank you very much for your deep testing!
I am sorry that you cannot reproduce the problem, let me illustrate it more properly with a video:
1. With internet ON, the cached maps disappear beyond a certain zoom level
2. With internet OFF (flight mode), OsmAnd overscales the cached tiles
3. Turning internet ON, the tiles disappear again.

I hope the attached video will make the problem easy to reproduce.
Thank you for the help!

https://user-images.githubusercontent.com/56419637/201688037-8d857a90-d00c-49e5-a096-eb067a3c8b27.mp4

**Comment by Dollarius** [comment]
As of today (nightly 2023-01-01) this is still NOT fixed.
@dmpr0 @Zirochkabila : could you please reopen? (or shall I make a new issue report?)
Reproduced as in the following video (Engine v1, Android 12):

https://user-images.githubusercontent.com/56419637/210203113-cb156b0f-7445-42dc-841e-cd69a294bebb.mp4

**Comment by vshcherb** [comment]
@Dollarius you are using rendering engine v1, it works as before and going to stay as it is.

**Comment by Dollarius** [comment]
@vshcherb what do you mean?
The exact same behaviour happens with engine V2 (openGL).

**Comment by vshcherb** [comment]
The issue is closed cause now we support it in Flight mode (wasn't before) & on all test devices we couldn't reproduce your issue, it probably exist for v1 / v2 rendering but it's worth to open a new issue and be specific what's left, this issue is 4.3 and 4.3 is already out, we don't plan to make attempt to fix it in 4.3

**Comment by Dollarius** [comment]
@vshcherb according to my testing, the behaviour has always been the same from 2022/05/18 (when I first reported the issue) up to 2023/01/04 (today).
I understand that you could not reproduce the issue, perhaps because the download of new tiles happened too fast for you (not a condition of "poor network connection", as when outdoors).

I just opened a new issue with clear steps to reproduce the issue: https://github.com/osmandapp/OsmAnd/issues/16140
I hope this will help to get it solved, thank you!
