### ISSUE TITLE
Housenumbers are missing from app

### ISSUE THREAD

**Issue by efi99** [osmandapp/OsmAnd#14325]
### Description
Some house numbers are missing in the application, although they are listed in the database and on the OSM website

### How to reproduce?
See attached picture.

### Your Environment
OsmAnd Version: 4.1
Android/iOS version: Android 12
Device model: Samsung A52 5G

**Maps used (online or offline):**   
Offline map in the app (but newest for mappers), online in website
![osm_num](https://user-images.githubusercontent.com/62113872/169322502-69d339ea-befd-464f-8849-1661d0cbb200.jpg)

**Comment by vshcherb** [comment]
Maps for May are not ready yet, in following maps everything will be searchable. OsmAnd Live doesn't support address changes
