### ISSUE TITLE
Croped a street name in the context menu and search results

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#14326]
### Description
When a user searches for a street named "Ferdinand-Alzer-Straße" in the municipality of Lennestadt, Germany (this street exists on the map in its usual form with this name), he entered it this way, but got "Ferdinand Alzer Straße" in the search results and the context menu

### Steps to reproduce

1. typed "Ferdinand-Alzer-Straße" in search line

### Actual result

"Ferdinand Alzer Straße" is displayed in the search results and in the context menu

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/169324845-8de78836-c96b-41a5-a265-f92e3dbdfcff.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/169324855-9d49a9ad-bca3-4d90-915c-3e8c875f2b8a.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table> 

### Expected result

"Ferdinand-Alzer-Straße" is displayed in the search results and in the context menu

### Your Environment
OsmAnd Version: 4.2.0#13507mqta
Android/iOS version: 11
Device model: POCO X3 NFC

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by vshcherb** [comment]
We do name preprocessing to match both name searches.
