### ISSUE TITLE
Use OpenTraffic traffic speed data for car routing

### ISSUE THREAD

**Issue by Hooloovoo** [osmandapp/Osmand#1432]
I just came across OpenTraffic (free, global traffic speed data set linked to OpenStreetMap built with open source software):
http://opentraffic.io/
http://conveyal.com/blog/2015/06/08/launching-opentraffic/
and think it would be really powerful if this functionality could be implemented in OSMAnd. Traffic information is the reason that my wife prefers Waze over OSMAnd.

**Comment by vshcherb** [comment]
How open is it, is there any limitation that Mapbox will stop giving out the data or will start asking money for it? It could be just a FreeTraffic data, but that could be a temporary service from them.

Pure open traffic idea should explain how to setup your own server and maintain it, of course it could have privacy issues.

**Comment by Hooloovoo** [comment]
Their site says that they are forming as a nonprofit organisation, with founding partners the World Bank, Conveyal and Mapzen in addition to Mapbox. I can't easily see information on the licences for submitted data or whether they will guarantee that the full data set is downloadable etc, but looking at the blog post it is all quite new. The site suggests people email them with any questions, so maybe it is worth an OSMAnd developer dropping them a line?

**Comment by DaimonPl** [comment]
Well this could be "win-win" setup. Simply if OsmAnd user wants to use traffic data for routing he must at the same time allow to send his data to opentraffic (of course if he's got local network internet connection).

I'm using other application (country-targeted) which uses its own servers for such routing - it works great

**Comment by Hedaja** [comment]
I wrote them an email about the license now. Waiting for reply.
I think this would be a great benefit for OsmAnd. I believe a lot of people expect to have live traffic data if they are using their smartphone for navigation.

**Comment by vshcherb** [comment]
We are also trying to reach them, to get more information about API

**Comment by Hedaja** [comment]
The Graphhopper project already made a collection of other free traffic data sources. https://github.com/graphhopper/open-traffic-collection
Don't know if this might be helpful or if you already have seen this.

**Comment by thessy** [comment]
OpenTraffic in OsmAnd would be awesome. Are there any news about it?

**Comment by GaidamakUA** [comment]
We've tried contacting them, but get no response. It is seems like they are not reliable. Shame but this is unlikely to be implemented any time soon.

**Comment by liotier** [comment]
France offers free access to traffic events data in Datex format ([page in French](http://diffusion-numerique.info-routiere.gouv.fr/acces-aux-donnees-evenementielles-datex-2-a19.html))

[A number of local governments in Europe seem to offer such data](http://www.datex2.eu/datex-node) but access to that seems administratively very fragmented - there is definitely room for an aggregator...

**Comment by bonanza123** [comment]
Maps.me now offers traffic layer, see also https://github.com/mapsme/omim/issues/736. Maybe its possible that osmand uses the data from the same source?

**Comment by doronbehar** [comment]
Regarding the license, what is the purpose of these files found in their repositories?
 - https://github.com/opentraffic/api/blob/dev/LICENSE.txt
 - https://github.com/opentraffic/osmlr/blob/master/COPYING
Be enough?

**Comment by erdmark** [comment]
There is a project at trafficpixel.tk providing a traffic overlay for osmand and the possibility to add speed points directly with Osmand.

**Comment by ignaciolep** [comment]
Some news about OpenTraffic:
1) Open Traffic technical preview #1: OSMLR segments: https://mapzen.com/blog/open-traffic-osmlr-technical-preview/
2) OSMLR traffic segments for the entire planet: https://mapzen.com/blog/osmlr-2nd-technical-preview/

**Comment by gloschtla** [comment]
[Here](http://gfist.com/index.php/en-us/blog/37-osmand-google-traffic) you find a tutorial, how to manually overlay OsmAnd's car map with Google Maps that includes live traffic color codes. But unfortunately for this solution you need to download Google's map image files, while having (expensive) mobile internet connection. Furthermore (in my case) the overlaying Google map was moved about 30 km northwards relative to the offline map. 
![Screenshot](https://user-images.githubusercontent.com/21010195/33996231-e16efabe-e0e0-11e7-8fe0-f4b2feee31d4.jpg)

**Comment by bam80** [comment]
Any progress? News?

**Comment by ignaciolep** [comment]
> Any progress? News?
About Open Traffic, Mapzen released the platform and handed it to World Bank for operation. Code for all of the platform’s components is on [GitHub](https://github.com/opentraffic), available under the LGPL license. https://mapzen.com/blog/open-traffic-release/

BTW, Mapzen will cease operations at the end of January 2018. https://mapzen.com/blog/shutdown/

**Comment by bam80** [comment]
@ignaciolep I meant progress in Osmand indeed.
BTW, MAPS.ME uses https://traffic.maps.me/ for traffic:
https://github.com/mapsme/omim/issues/736#issuecomment-355181634
Can we use it too?

**Comment by ADepic** [comment]
I'm not sure if traffic.maps.me is allowed for us. Try asking on maps.me github page and read through their terms and conditions

**Comment by ADepic** [comment]
Seems like this idea is dead.

Okay

**Comment by ADepic** [comment]
Close issue? open traffic seems dead, I tried contacting as well.
