### ISSUE TITLE
Public Transport

### ISSUE THREAD

**Issue by Jiuvel** [osmandapp/OsmAnd#14329]
# 🚀 feature request

### Description

Hello, to all the OsmAnd team.  I think that when activating the public transport view, the possibility of filtering a certain bus, metro, train, etc. route should be incorporated.  This would be very useful if you want to see the itinerary of a specific route on the map, something very difficult to appreciate if they are all shown together.  This possibility would be very helpful.  Best regards.  Thank you very much.

![Screenshot_2022-05-19-18-15-50-761_net osmand plus~3](https://user-images.githubusercontent.com/83715100/169414717-1cf48543-baa1-43d6-bbdf-dc75a4de2ec5.jpg)

**Comment by scaidermern** [comment]
You can tap on a public transport stop / station,l and select the route you want to see. This will highlight this route on the map.

**Comment by Jiuvel** [comment]
Hello, thank you very much for your comment. I had not noticed that 
function of OsmAnd. Greetings.
