### ISSUE TITLE
Voice instructions and direction indicator give incorrect directions when overlaying the route

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#14331]
### Review 
- Update documentation
- [ ] Fix iOS
- [x] Introduce attribute (start_trkpt_idx="2"), so later we can safely use it instead of length or together with length

### Description
User was used the "Plan Route" function to create a short cycle route with just 16 points. Then he select the track, activate navigation, and start cycling. The arrow on the map is always correct as I travel. However after the first 2 turns the voice instruction and onscreen turn indicator start to misbehave, although they are in agreement with each other
https://github.com/osmandapp/OsmAnd/discussions/13546

### Steps to reproduce

1. Plane route
2. Create new route
3. Create new route with a route overlay
4. Run the ride simulation (bicycle profile)

OR select this GPX 
Drum.loop.gpx .zip https://github.com/osmandapp/OsmAnd/files/8738666/Drum.loop.gpx.zip

### Actual result
The user observes errors in the playback of voice prompts and driving directions

https://user-images.githubusercontent.com/104760013/169494157-d083f59f-9526-4aa4-82b9-bf45feca1c1f.mp4

### Expected result
Voice navigation and widget of driving direction must correctly work

### Your Environment
OsmAnd Version: 4.2.0#13507mqta
Android/iOS version: 11
Device model: POCO X3 NFC

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by Gbernardy** [comment]
But hasn't this malfunction already been solved in #13031, which reports Android 4.2 as a milestone?

**Comment by vshcherb** [comment]
This issue is specific when route created by plan route has overlap, all other cases taken from discussion #13546 are fixed.

**Comment by vshcherb** [comment]
![telegram-cloud-photo-size-4-6024095450216381083-y](https://user-images.githubusercontent.com/1042025/201907914-f67e70ef-4300-472a-b425-7fecfbf9658e.jpg)

**Comment by vshcherb** [comment]
NEWLY CREATED TRACK 

Problem with Sum Length = 172 of segments however points only 132. We need to make sure that for all tracks sum of lengths = number of points. So we need to revert this fix and properly fix create track

[Tue 29 Nov 2022.gpx.zip](https://github.com/osmandapp/OsmAnd/files/10112761/Tue.29.Nov.2022.gpx.zip)

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2348/files
https://github.com/osmandapp/OsmAnd-core-legacy/pull/113 
https://github.com/osmandapp/OsmAnd-core-legacy/pull/114

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2348

**Comment by PaulStets** [comment]
https://github.com/osmandapp/OsmAnd-core-legacy/pull/116
https://github.com/osmandapp/OsmAnd-core/pull/437
https://github.com/osmandapp/OsmAnd-iOS/pull/2391

**Comment by ivanPyrohivskyi** [comment]
To QA:
- [ ] Compare Plan Route in Android and iOS. Take attention on < osmand:extension > in GPX file
- [ ] Compare navigation by track using same GPX file (created in Plan Route with < osmand:extension >)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14032mqta, released: 2022-12-19
4.4.1.5
Done
