### ISSUE TITLE
Regression: Number of valid digits displayed for analysis values (e.g.speed values)

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#14338]
For tacks recorded while walking or jogging, it seems we have reduced the display of the average speed (on the speed or split interval screens) to now show only integer km/h values (8, 9, or 10 km/h)?

Scientifically, the accuracy we present should be consistent between distance, time, and derived values like speed.

But as a simplification I advise we return to the accuracy thresholds we had up to OsmAnd version 4.0. I have tracks showing speed values like 11.4 km/h or 14.1 km/h, so I believe we used one digit behind the decimal point probably up to <20km/h?

**Comment by dmpr0** [comment]
# Review
- [ ]  Show one digit behind the decimal point, for **Average speed**, if the **Average speed** is less than 20 km/h. In the current implementation, the decimal point for Average speed is shown, only if the Max speed is less than 20 km/h.
I have applied GPS filter for my test track, and filtered out all points with speed more than 20 km/h

<table style="width:100%">
  <tr>
    <th>Before GPS filer</th>
    <th>After GPS filter was applied</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/170680199-f3d00559-6ccc-485e-8389-27155ead4418.png"  width="360" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/170680149-7af3555f-7a16-48f1-a02c-3f2585acea69.png"  width="360" height="auto"/> </td>
  </tr>
</table>

**Comment by cepprice** [comment]
@dmpr0 
Formatting of average speed doesn't depend on maximum speed.

It's probably not about GPS filter, but about profile being used. If profile's default speed > 36 km/h, then speed won't have fractional part, even if speed value < 20 (such logic was since 2015).

So, in **before gps filter** was used profile like car, in **after gps filer** was used browse map / bicycle / walking

**Comment by vshcherb** [comment]
As of today we don't have good solution and that's issue is rather a discussion for now.
**How it works**
Speed formatting is global across the profile. Each profile determines how the speed is formatted i.e. 
**pedestrian** formats speed as ##.# 
**car** formats speed as ##

It's pretty simple but could give unexpected results. We definitely need to document it.

**Other solutions**
In all other cases we will need to implement non-global speed formatting. It's pretty weird in the Current Speed of the car see something like 7.4 kmh or 5.3 mph. So in that case we would need to have widget-speed-formatting and track-context-menu-speed-formatting and it could make situation even less understandable.

**Comment by sonora** [comment]
@vshcherb Maybe we shouldn't bother and still make it one global speed formatting, though? Such low speeds are not very common in e.g. cars and other motorized vehicle, and if you have them, it does not really hurt to see that extra digit?

**Comment by vshcherb** [comment]
They are pretty common, if you slow down you will see in the widget 7.4 kmh which is not what we wanted in the first place. I support idea to have global speed formatting across profile i.e. widget / tracks / etc... Though I think global speed formatting across the app is rather bad idea cause these numbers will be visible in many places

**Comment by sonora** [comment]
True, but those are transient situations. But you are right, formatting per base profile may be the way to go.
