### ISSUE TITLE
Opengl: live updates do not work

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#14339]
Live updates do not work in opengl version.
At the same time, there is new information in the properties of the point of interest, but the geometry has not been updated at all.
![Screenshot_2022-05-20-23-39-52-889_net.osmand.plus.jpg](https://user-images.githubusercontent.com/12549744/169608144-5ffc4032-e121-440d-b1fc-6363481ebd0e.jpg)

### Your Environment
OsmAnd Version: OsmAnd~ 4.2.0#13511mqta, дата выпуска: 2022-05-20
Android version: 12
Device model: poco x3 pro

**Comment by scaidermern** [comment]
Strange, I can't reproduce this behavior.

Yesterday I did a live update and my map changes didn't appear until I restarted OsmAnd. Now they appear immediately.

**Comment by Nine-Tailed** [comment]
It happens that live updates are not displayed or are not superimposed correctly and then you have to restart Osmand 1-3 times after which the problem disappears.  I use nightly builds and this problem is most often observed after updating to a new version.

**Comment by vshcherb** [comment]
We also noticed this restart issue mostly 1 restart helps but indeed it's very strange still
