### ISSUE TITLE
Opengl: incorrect information about poi such as doors, trees, and multipolygons

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#14348]
### Description
video about incorrect multipolygon information https://t.me/ruosmand/95630

![Screenshot_2022-05-22-22-06-56-881_net.osmand.plus.jpg](https://user-images.githubusercontent.com/12549744/169712120-3bde752d-1463-4e4c-b7f8-842b84a5bdc1.jpg)
![Screenshot_2022-05-22-22-06-32-289_net.osmand.plus.jpg](https://user-images.githubusercontent.com/12549744/169712132-c3988444-45ce-48f8-a0ca-f9dd12ac1296.jpg)

### Your Environment
OsmAnd Version: OsmAnd~ 4.2.0#13514mqta, дата выпуска: 2022-05-22 
Android version: 12
Device model: poco x3 pro

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/14531
