### ISSUE TITLE
Opengl: POIs and names over the overlay map - optional

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#14347]
POIs and names are displayed on top of the overlay map.
<img src="https://user-images.githubusercontent.com/12549744/169710542-7b9b0362-dfea-4140-97cd-c05d8dd9a22b.jpg" width="50%" height="50%" />

### Your Environment
OsmAnd Version: OsmAnd~ 4.2.0#13514mqta, дата выпуска: 2022-05-22
Android version: 12
Device model: poco x3 pro

**Comment by vshcherb** [comment]
That's expected behavior for new setup. Names could be switched off.

**Comment by Nine-Tailed** [comment]
With opengl disabled, the overlay map completely hides the vector map, along with text and POI, the same behavior was expected with opengl enabled.

**Comment by vshcherb** [comment]
Nope, it changed. We would like to see exactly like in OpenGL, before it wasn't possible

**Comment by Nine-Tailed** [comment]
Maybe then it's worth adding options to show poi and names.
![Screenshot_2022-05-23-14-40-45-986_net.osmand.plus~2.jpg](https://user-images.githubusercontent.com/12549744/169812786-dfc2e772-4998-4de4-9c5f-487ffb4c9653.jpg)

**Comment by Nine-Tailed** [comment]
Another argument in favor of the possibility of turning off poi and names, this is the imposition of names on top of each other.
![Screenshot_2022-05-24-00-45-19-548_net.osmand.plus.jpg](https://user-images.githubusercontent.com/12549744/169910785-85d01b6b-3d9c-436a-878b-7903f13b43aa.jpg)
![Screenshot_2022-05-24-00-34-25-678_net.osmand.plus.jpg](https://user-images.githubusercontent.com/12549744/169910824-f411d66e-3594-408e-837d-d87bc4c1f48f.jpg)

**Comment by mic140** [comment]
I would like to be able to turn off names and POIs in the overlay layer

**Comment by vshcherb** [comment]
TODO: We need to increase transparency of text / symbols if opacity of overlay is increased.

**Comment by anastasiia936** [comment]
When enabled OpenGL rendering and select any satellite map as overlay layer, objects from the vector layer are displayed over the Raster map. It would be convenient if there was a setting to enable or disable the display of information from the vector layer.
Tested in OsmAnd 4.2.7, with selected Microsoft Earth as an overlay layer.
-34.20923 151.00842.
![image](https://user-images.githubusercontent.com/80623554/188891103-d10bca24-6652-49f8-b2bf-f16dda6075d1.png)

**Comment by vshcherb** [comment]
To make it controllable new issue is open https://github.com/osmandapp/OsmAnd/issues/15411

**Comment by ivanPyrohivskyi** [comment]
To @nnngrach need to move commit https://github.com/osmandapp/OsmAnd/commit/65c3e7e05cfe6175e489bc357836837f732c6efd on iOS
