### ISSUE TITLE
Simplify handling of Custom POI filter

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#1434]
Currently a user has to go through 6 steps (as follows) to set and save Custom POI filters, many steps can be made more obvious or "discoverable", as I suggest in line below:
1. From the map screen, tap the dashboard button (lower left corner)
2. On it tap search POI.
3. On the search POI screen tap the 3 dots icon next to the text filter box, and select "Custom filter". 
   --> I suggest here that we delete the 3-dots "more" button, it only contains 1 action anyway, let us return to a textually explicit "Custom filter" list entry in the POI category list.
4. On the resulting selection screen, tap any combination of categories or sub-categories.
5. When done, hit the "Tick" icon in the upper right corner of the screen.
   --> Often users are not aware of this tick icon, instead wrongfully default to using the device's back button, etc. Let us put an explicit "OK" button somewhere.
6. To save your selection as a custom filter, hit the "Start" icon (again upper right corner), and select a name for your filter.
   --> Same here: Often users are not aware of this icon and what it does (even that it does anything), so why not put an explicit "Save as" button on the screen.

**Comment by vshcherb** [comment]
Currently it is not clear why would we want to simplify such difficult functionality. For now we are targeting to have more available search options and allow POI multiselect on screen, bookmark of poi search is already available, other features like recent search may be will be welcome in future.

**Comment by enomat** [comment]
I support everything that sonora had mentioned here about the Custom POI menu. (Because the current menu is confusing and buggy.)

I also wanted to open a new issue to report all these necessary changes that sonora had mentioned about the POI menu.

**Comment by jensb** [comment]
Just IMHO: in general, there should not be a thousand search options, but just one single "search" input field and "Go" button that tries hard to find what the user currently needs. Think Google search, not static database search forms that are easy to convert to SQL but terrible to use.

**Comment by homersimpsons** [comment]
Furthermore, if possible, can you add an option to select an icon for the filter instead of getting always the qame for each filter...

**Comment by sonora** [comment]
Deprecated.
