### ISSUE TITLE
backup and restore

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#14345]
### Description
Auto-translate: 
The function "backup and restore" seems to me to be a single bug.
) although I deleted all backup data and also "old versions" at the beginning (because I've tried it several times), "Last backup xx hours xx minutes ago" is persistently displayed despite repeated app and cell phone restarts.
) The selection of what should be backed up can be found under Settings / Back up data / Used memory (?)
) here I click on "Settings", "My Places" or "Sources". Although EVERYTHING is selected, "none" is displayed for each individual item
) I canceled the backup started here after 10% / 10 minutes / 500Mb
) I now deselect the "Maps" under "Sources" so that GB of map data are not backed up unnecessarily, I can trigger the backup again.
) with the subsequent "Restore" only an empty window opens under "Choose what to restore".
) After restarting the app, a selection is possible here, but all the expected tracks and favorites and other data can only be found under "Settings: All, 1" and under "My places: Itinerary, All, 1"

Now my 2nd device comes into play:

) Without having started a backup on this beforehand, I am informed of "conflicts" because "blabla... newer data is available... blabla...).
) I could restore a backup right away (which strangely enough, with its size of 500Mb, corresponds to the backup previously canceled on the other device...)

As the "Backup and Restore" function is currently presented, I hope I will NEVER be in the embarrassment of having to use it and only use the "Local backup, save as file" option.

A reliably working backup AND the possibility of synchronizing the favorites from several devices are the "biggest construction sites" I miss in Osmand. I had bought "Osmand Pro" because the mail support told me that with it (the backup and restore function) I can synchronize the data of two devices. Which is pretty much nonsense. I'm willing to pay the price of a "pro version" for it. But it has to work reliably. The possibility of displaying a few "colored lines" is a bit too little for a "pro version" for me.

<details>
<summary> Original</summary>

Die Funktion "backup and restore" scheint mir ein einziger bug zu sein.
) obwohl ich zu Beginn (weil ich es schon öfters versucht habe) alle Backup-Daten und auch "Alte Versionen" gelöscht habe, wird trotz wiederholten App- und Handy-Neustart hartnäckig ein "Letztes Backup vor xx h xx min" angezeigt.
) Die Auswahl, was denn gesichert werden soll, findet sich unter Einstellungen / Daten sichern / **belegter Speicher** (?) 
) hier klicke ich auf "Einstellungen", "Meine Orte" oder "Quellen". Obwohl ALLES angewählt ist, steht bei jedem einzelnen Punkt **"keine"** 
) das hier gestartete Backup habe ich nach 10% / 10Minuten / 500Mb abgebrochen
) wähle ich nun unter "Quellen" die "Karten" ab, damit nicht unnötigerweise GB an Kartendaten gesichert werden, kann ich das Backup erneut auslösen.
) beim darauffolgenden "Wiederherstellen" öffnet sich unter "wählen Sie aus, was wiederhergestellt werden soll" bloß ein leeres Fenster
) Nach App-Neustart ist hier eine Auswahl möglich, aber von all den erwarteten Tracks und Favoriten und sonstigen Daten findet sich bloß unter "Einstellungen: Alle, 1" und unter "Meine Orte: Reiseplan, Alle, 1"

Nun kommt mein 2. Gerät mit ins Spiel:

) Ohne auf diesem zuvor ein Backup gestartet zu haben, werde ich auf "Konflikte" hingewiesen, weil "blabla... neuere Daten vorhanden... blabla...) sind
) könnte ich gleich ein backup wiederherstellen (welches eigenartigerweise mit seiner Größe von 500Mb dem zuvor auf dem anderen Gerät abgebrochenen Backup entspricht...)  

So wie sich die "Backup und Restore" - Funktion gerade darstellt, komme ich hoffentlich NIE in die Verlegenheit, sie nutzen zu müssen und verwende ausschließlich die Möglichkeit "Lokales Backup, als Datei sichern".

Ein verlässlich funktionierendes Backup UND die Möglichkeit der Synchronisierung der Favoriten von mehreren Geräten sind die "größten Baustellen" die ich in Osmand vermisse. Ich hatte "Osmand Pro" gekauft, weil mir der Mail-Support mitteilte, dass ich damit (der Backup und Restore-Funktion) die Daten zweier Geräte abgleichen kann. Was ziemlicher Nonsens ist. Ich bin gerne bereit, dafür auch den Preis einer "Pro-Versuion" zu bezahlen. Aber es muss verlässlich funktionieren. Die Möglichkeit der Dartsellung von ein paar "farbigen Linien" sind mir für eine "Pro-Version" ein bisschen arg zu wenig.

</details>

### Your Environment
OsmAnd Version: 4.2.0 (aber auch zuvor)
Android/iOS version: 12
Device model: S20+, S20FE, TAB S6

**Comment by vshcherb** [comment]
Some observations:
- You can reset and try again.
-  If you interrupt backup, it is still uploaded and stored on Cloud
- Conflicts with new device is annoying but unavoidable now cause you start application with predefined settings and they're set, so it's not possible to detect whether app is fresh or is fine. So we need to introduce question to user in that case - app fresh, so exact restore is possible

For now: 
- Pro version allows to store information and that's what's being paid for. More feature comes, but you need to subscribe once you feel it fits your need not earlier.

Thanks for feedback, though it doesn't form a well described bug, so it will be fixed as separate issues.
