### ISSUE TITLE
Regression: Quick action add track waypoint: Not possible anymore to set waypoint name

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#14352]
I have a "add track waypoint" button in my quick actions. 

Previously this opened a menu where the waypoint name could be set before this waypoint was created.

Now with OsmAnd 4.2.0 this button immediately creates a new waypoint without a dialog in between. In order to to change the name I now have to open the waypoint again, tap on actions, edit,..., save.

This is really cumbersome.

**Comment by dmpr0** [comment]
Hi, @scaidermern!
You need to select **Waypoint appearance** > **Always ask**. Before 4.2, dialog in between will ask to choose the track file and then for track name and other details. Current UI allows to choose the needed file, but shows a waypoint adding UI for entering name and other details.

**Comment by scaidermern** [comment]
> Hi, @scaidermern! You need to select **Waypoint appearance** > **Always ask**. Before 4.2, dialog in between will ask to choose the track file and then for track name and other details. Current UI allows to choose the needed file, but shows a waypoint adding UI for entering name and other details.

Thanks, that works! I guess I wouldn't have found that setting (it is hidden in the settings of this particular quick action).
