### ISSUE TITLE
OSMAnd 4.2 on iOS crashes when creating a driving route with a long distance 

### ISSUE THREAD

**Issue by kevinp2** [osmandapp/OsmAnd#14366]
### Description
Although the exact number is not known, if the route is longer than about 1,000 miles (1,600 km), OSMAnd tried to calculate the route for a long time and then the app closes silently after about 2 minutes

### How to reproduce?

- Create a route from Austin, Texas, USA to Salt Lake City, Utah, USA.  (You will need to download maps for Texas, New Mexico, Colorado and Utah).
- The app will display the growing orange bar for a while and then the app will silently close.

I was able to reproduce this on an iPhone and an iPad.  The routing worked successfully on the earlier version 4.1

### Your Environment
OsmAnd Version: 4.2
Android/iOS version: 15.5
Device model: iPhone XR and iPad Pro

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by vshcherb** [comment]
We're about to release an update of 4.2.1 where longer routes should be calculated faster, especially comparing to 4.1

**Comment by dmpr0** [comment]
Hi! You can install 4.2.1 from AppStore manually or wait for an automatic update.

**Comment by Zirochkabila** [comment]
The bug is confirmed on OsmAnd version 4.2.1, on iPad mini 4, iOs version 15.2

**Comment by Zirochkabila** [comment]
On a device with Android 11, OsmAnd version 4.1.11 everything works fine

**Comment by Zirochkabila** [comment]
> 

Crash is caused by the lack of sufficient RAM on the device

**Comment by vshcherb** [comment]
Can we double check it on IOs devices? 
Original:
> Device model: iPhone XR and iPad Pro
Developer present:
> IPhone X, IPhone XS, iPad mini, ...
