### ISSUE TITLE
Name of road is displayed upside down

### ISSUE THREAD

**Issue by sanketgarade** [osmandapp/OsmAnd#14364]
### Description

The name of a road I was observing got inverted as I zoomed in and out of the map.

Location-

geo:18.58862,73.78053?z=18

![img](https://user-images.githubusercontent.com/74632379/169854741-df166e65-c85c-4a83-b39b-87c44e77e1b7.jpeg)

### How to reproduce?

See the attached video.

https://user-images.githubusercontent.com/74632379/169854890-9e01a175-9c13-4ca9-87cd-7e0625019fe0.MOV

### Your Environment
OsmAnd Version: 4.2.0
Android/iOS version: ios 15.4.1
Device model: iPhone mini

**Maps used (online or offline):**   

Offline map used. India > Maharashtra. Created on 1 May 2022.

**Comment by jfburke3** [comment]
I've encountered this a few times, too.  US Georgia map.
