### ISSUE TITLE
Plan rout, Create new route. Bicycle route not drawn correctly

### ISSUE THREAD

**Issue by Gbernardy** [osmandapp/OsmAnd#14361]
### Description

Bicycle profile.  Plan rout, Create new route.
It does not allow you to join the points of the track.  the starting point is the following
https://osmand.net/go?lat=45.55342&lon=12.16152&z=17

Points entered
![Screenshot_2022-05-23-12-53-58-07_54166e5c6f8ad9491c65e2397c495c92](https://user-images.githubusercontent.com/99968793/169807715-281a5ee3-326f-4e30-9157-70b664d4856f.jpg)

Result
![Screenshot_2022-05-23-13-05-02-11_54166e5c6f8ad9491c65e2397c495c92](https://user-images.githubusercontent.com/99968793/169807761-c6b7ab1b-dc54-4e06-8800-d4c396f41ece.jpg)

### Your Environment
OsmAnd Version:
Android/iOS version:
Device model:

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by vshcherb** [comment]
It's a private track - https://www.openstreetmap.org/way/888000347#map=18/45.55437/12.16050 you are not allowed to use it

**Comment by Gbernardy** [comment]
Ok. 

How do you understand in OsmAnd, when drawing a track, if a road is private ... without enabling "Allow private access" parameter ?

**Comment by scaidermern** [comment]
You can enable Configure map / Details / Show access restrictions and toll.
