### ISSUE TITLE
Navigation: arrival time always 01:00

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#14373]
When planning a route with OsmAnd and then following the resulting GPX track the arrival time always stays the same. It never gets updated.

**Comment by scaidermern** [comment]
Even if I start the navigation hours later the arrival time is still the same. Maybe it is the arrival time from the time the route was planned?

**Comment by Zirochkabila** [comment]
> Even if I start the navigation hours later the arrival time is still the same. Maybe it is the arrival time from the time the route was planned?

Please clarify:
1. The device you use
2. Application version and date of map update
3. Route
4. The presence of traffic restrictions
5. A short video and screenshots where we could see the error

**Comment by scaidermern** [comment]
That's a lot of questions of which most don't really matter. 

OsmAnd 4.2.0, latest map update.

I just tried to plan a route again (I'm talking about the plan a route feature, not about regular navigation). The arrival time is _always_ 01:00.

![IMG_20220524_182129](https://user-images.githubusercontent.com/1040784/170085218-d02741f5-6248-4c90-a50a-6168dfcd8e9d.jpg)

**Comment by scaidermern** [comment]
Doesn't happen in the latest nightly. So I guess this is a bug in OsmAnd 4.2.0?

**Comment by scaidermern** [comment]
Just got the update for 4.2.1, the bug is gone.
