### ISSUE TITLE
All routes ETA are exactly and always 1:00 am on the screen widget

### ISSUE THREAD

**Issue by brunofin** [osmandapp/OsmAnd#14376]
### Description

Any route I navigate to will show ETA screen widget as 1:00 am. It doesn't affect the route planning view neither the Android auto screen widget, only the phone widget. 

![Screenshot_2022-05-24-17-52-13-589_net osmand](https://user-images.githubusercontent.com/8077237/170081814-ed562318-7999-432e-9a88-ddc0533d9feb.jpg)

### How to reproduce?

Search for an address, navigate, see screen widget. 

### Your Environment
OsmAnd Version: OsmAnd 4.2.0, released: 2022-05-10
Android/iOS version: Android 11 RKQ1.200826.002
Device model: Xiaomi Mi 9 Lite, MIUI Global 12.5.2

**Maps used (online or offline):**   offline
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by scaidermern** [comment]
I just opened the same ticket: #14373

Looks like this has been fixed in OsmAnd 4.2.1. Check if you can update your version.

**Comment by pebogufi** [comment]
Already fixed in nightly, and now ok, please close.

**Comment by brunofin** [comment]
Thank you

**Comment by brunofin** [comment]
Sorry, how do I get OsmAnd 4.2.1? I am a beta tester on Google Play and I am still on 4.2.0

**Comment by vshcherb** [comment]
4.2.1 didn't pass on OsmAnd, only on OsmAnd+. 4.2.2 is going to be uploaded today

**Comment by brunofin** [comment]
That makes sense. Thank you for clarifying. Is the information about builds publicly available somewhere?
