### ISSUE TITLE
Shortcut to Position (Favorite) on HomeScreen

### ISSUE THREAD

**Issue by poidi** [osmandapp/Osmand#1438]
Hi there,

currently i use "Desktop VisualiseR" to create a HomeScreen Button that starts OsmAnd with the coordinates of an Favorite (using the http://osmand.net/.... url)

I use it mainly to prepare a trip beforehand, when i have several places to go. Or when i'm in a new area (i.e. vacation) and want to navigate to several places again and again.

This works just fine, except that i have to press another 2 times till i start the navigation (press on the map-point and then on "navigate to")

So it would be great to:
 - Create HomeScreen Shortcut in OsmAnd naitivly
 - Choose wether the Coordinates should be shown only (to search for POIs next to it, or used for navigation)

thanks
poidi

**Comment by vshcherb** [comment]
OsmAnd supports geo intent (https://developer.android.com/guide/components/intents-common.html) which position it faster on the map. The other intent supported is osmand Share (osmand.net/go?lat=5&lon=4&z=19), so it might be possible to use them
