### ISSUE TITLE
OsmAnd doesn't handle oneway:bicycle=no correctly

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#14383]
Either OsmAnd (4.2.1) ignores `oneway:bicycle=no` or there is a very strong penalty applied.

Example 01 at 51.7636795, 14.3390608:
Instead of just turning right into OsmAnd takes a strange detour:
![photo_2022-05-25_14-48-29](https://user-images.githubusercontent.com/1040784/170265883-bd2f4866-576c-4a93-93ec-91ceb48907e9.jpg)

[route.gpx.txt](https://github.com/osmandapp/OsmAnd/files/8771236/route.gpx.txt)

Example 02 at 51.0540657, 13.7867069:
Even with via points OsmAnd tries to avoid even a tiny stretch of `oneway:bicycle=no`:
![photo_2022-05-25_14-54-44](https://user-images.githubusercontent.com/1040784/170267011-09e822ea-6a95-4341-b9cf-b4b3f9d48fc5.jpg) ![photo_2022-05-25_14-56-02](https://user-images.githubusercontent.com/1040784/170267037-91f3ce2b-54b7-4c9e-ad3f-529e6db49b83.jpg)

[route02.gpx.txt](https://github.com/osmandapp/OsmAnd/files/8771286/route02.gpx.txt)

**Comment by vshcherb** [comment]
2nd case.
It goes either way -https://osmand.net/map?start=51.053913%2C13.787029&end=51.054315%2C13.785702&mode=bicycle. Cost is 42 vs 43, so it's negligible, I don't see why 1st route is better than 2nd and other way around. So it's negligible

**Comment by vshcherb** [comment]
1st case it's not a routing issue https://osmand.net/map?start=51.763625%2C14.338481&end=51.764047%2C14.339331&mode=bicycle.

It's an end point detection issue cause we're going to refactor it, I'm going to close it for now. Most likely start/end point road attraction will be changed completely

**Comment by scaidermern** [comment]
I see. I found other cases where it works correctly. The above examples are still strange, though.
