### ISSUE TITLE
 Incorrect construction of the sea route when working with Plan route

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#14399]
### Description

 Incorrect construction of the sea route when working with Plan route (OpenGl version and iOS too)

### Steps to reproduce

1. Boat profile
2. Create new route
3. Select points

### Actual result
Incorrect construction of the sea route
54.60561° N, 13.35571° E

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/170666770-f9605ddf-68df-4f04-b8fb-a172394f23ef.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/170666780-a102b11b-1770-440d-bbf4-09af7f70f47e.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table> 

### Expected result

Correct construction of the sea route

### Your Environment
OsmAnd Version: 4.2.0#13524mqta
Android/iOS version: Android 11
Device model: POCO X3 NFC

**Comment by vshcherb** [comment]
Not supported feature, you can only draw straight lines with open sea navigation

**Comment by vshcherb** [comment]
It's probably a duplicate about open sea routing is not supported
