### ISSUE TITLE
4.2.1 - changing data folder - iterruption causes non working osmand and error

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#14407]
### Description
Because still on every update all previous downloaded maps are deleted, I wanted to change the data folder from "multiuser 1" to "multiuser 2" and see, if this makes any difference.

Phone was in a stand and files were moved to its new location. 
After about one hour (still moving "tiles") I wanted to connect the phone to power, for this I turned it from "portrait" to "landscape". With this turning the moving was interrupted and the message "app has to be restarted" appeared. So I did. But all what happened was a non working Osmand, No maps, no data - but the welcome screen like at a new install (select a map", ...).

It took me lots of time to find and move all data back again to the previous storage place and get Osmand working again.

What now is left is this error message "sending purchase info..."  (see screenshot)
Even though I can´t find anymore files outside the specified Data Folder "multiuser 1", there still must be some already moved data not back in its proper location?

But anyway, the beginning of it all was the interruption of the data moving process just by turning my device 90°. 

[edit] this "sending purchase...." error does not appear anymore, very interesting. 

### Your Environment
OsmAnd Version: 4.2.1
Android/iOS version: 12
Device model: Galaxy S20

![sending purchase info](https://user-images.githubusercontent.com/95540936/170815260-a101bc3b-f8e0-4b0a-bcb4-6b53f8fa001f.JPG)
+

**Comment by vshcherb** [comment]
That was an issue on server on Friday which is fixed now
