### ISSUE TITLE
Altitud

### ISSUE THREAD

**Issue by Jiuvel** [osmandapp/OsmAnd#14409]
# 🚀 feature request

### Description
Hello, currently the altitude widget shows the information based on the height established by the satellites but sometimes it is not entirely accurate.  I think that the option to choose the source of the altitude data between the satellites and the information contained in the map or in the contour layer should be implemented to improve accuracy.  So if we are in a plane we can choose to show the reading of the satellites and if we are at ground level the information of the map.  I also think that when touching a point on the map along with the information that appears on the screen, the altitude of the indicated place should appear.  Greetings.

**Comment by tradavyvy** [comment]
Altitude info when long touching a point would be most welcome. When traveling in our motorhome in the southwest usa in summer, finding a high spot to spend the night means cooler nights and better sleep.
Others might find other uses for this information.

**Comment by vshcherb** [comment]
Duplicate to https://github.com/osmandapp/OsmAnd/issues/11265
