### ISSUE TITLE
The top and the bottom bars waste too much space from the screen.

### ISSUE THREAD

**Issue by enomat** [osmandapp/Osmand#1440]
The top and the bottom bars waste too much space from the screen. The scrollable area is unusable and barely visible. (The scrollable area starts from the "Offline maps (vector)" label, so that small area.)
All menus are affected by this problem more or less.
I have Galaxy S2.

![screenshot_2015-07-05-15-30-33](https://cloud.githubusercontent.com/assets/12612250/8511935/b18e2230-232c-11e5-9d2f-564d6ffa1c87.png)

**Comment by vshcherb** [comment]
We have new design for that screen without bottom bar download and toolbar will be scrollable.

**Comment by enomat** [comment]
@vshcherb 
Unfortunately, this bug is still not fixed. The toolbars still waste too much space. (This problem is more pronounced on devices with small resolution, like Galaxy S2.)

![screenshot_2015-12-13-15-38-15](https://cloud.githubusercontent.com/assets/12612250/11767844/c83ccce4-a1bb-11e5-989e-930149999bd3.png)

.
The problem is bigger on Osmand free version:
![screenshot_2015-12-13-14-49-50](https://cloud.githubusercontent.com/assets/12612250/11767846/cfb9f726-a1bb-11e5-9c82-ac41683c08da.png)

Screenshots were taken from latest nightly versions.
