### ISSUE TITLE
POI search input field is multiline but does not look like one

### ISSUE THREAD

**Issue by jensb** [osmandapp/Osmand#1441]
When using the current POI input field with a different keyboard (e.g. Swiftkey), it is easy to input a line break into this field, which makes previously entered lines invisible (and thus all searches fail). 
The search field should start search when hitting a return key, and not allow multiline text - or actually grow with the number of lines entered.

**Comment by vshcherb** [comment]
Fixed

**Comment by jensb** [comment]
Wow. That was fast. I'm amazed. Thank you! :+1:
