### ISSUE TITLE
Trigger OsmAnd routing from another Android App

### ISSUE THREAD

**Issue by ascomycota** [osmandapp/OsmAnd#14427]
Hello,

I am currently developing a "navigation plugin" in my Android app written with Qt 
framework. Therefore I just call Qt.openUrlExternally("https://navigtaion-website...") and android manages the rest. 
Currently I can trigger GoogleMaps and HERE with such a link like the following:

https://maps.google.com/maps?
travelmode=driving&dir_action=navigate&saddr=Current+Location&daddr=Munich,Hauptstraße+12

and

https://wego.here.com/directions/mix/MyLocation/Munich,Hauptstraße+12

It would be nice to also have such an URL on which OsmAnd is listening to. So I can call an URL like:

https://osm.org/navigation?to=Munich,Hauptstraße+12
or
https://osmand.org/navigation?to=Munich,Hauptstraße+12

and Android opens OsmAnd with destination already set. Optional "from" parameter could be set or defaulting to "current location".
 
Should be an easy but mighty feature - IMHO :) What do you think?

Thanks
Andreas

**Comment by vshcherb** [comment]
We support some Google URL's for search but not for navigation, so that would be a next step to be honest, once these once are supported

**Comment by Chumva** [comment]
We already have the "navigate_search" command via intent API, there is an example of api-demo project with this command - 
https://github.com/osmandapp/osmand-api-demo/blob/15a8c9945fcdba043e90f56d4dd627ce51e758ee/OsmAnd-api-sample/app/src/main/java/net/osmand/osmandapidemo/OsmAndHelper.java#L452

OsmAnd parses and executes it here - 
https://github.com/osmandapp/Osmand/blob/a517184a3608d90766eda462497149d93433a3ca/OsmAnd/src/net/osmand/plus/helpers/ExternalApiHelper.java#L383
