### ISSUE TITLE
Can't switch on Overlay / Underlay on Configure Map

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#14429]
## Review
- [x]  Polygons don't auto enables after switching **Underlay map**.

Underlay map behavior:
1. Tap on switch > Select map > Map is visible under Offline maps. Tap on the switch again > **Underlay** will be turned off. You will see a map with disabled polygons, but in **Hide** > **Polygons** it now selected.
2. Tap on **Underlay** map item > in open windows, select map > Map is visible under Offline maps. Disable map from this screen, **Underlay** will be disabled, and polygons will be visible.

## ToDo
Can't switch on Overlay / Underlay on Configure Map (on top screen)

**Comment by Chumva** [comment]
Switch update should be fixed here - https://github.com/osmandapp/OsmAnd/commit/9a8a3e3d5fb50ca7a179e2216e6c37f5482ad3fb

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/commit/eeff55b9b13641c2fa78070ae0154b49228ea007
