### ISSUE TITLE
Missing OSMC icons

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1442]
Here http://www.openstreetmap.org/#map=14/49.801052/15.231849
or here http://www.openstreetmap.org/#map=14/49.306835/15.080615
http://www.openstreetmap.org/#map=14/50.168495/17.206924
I don't see any reason why OSMC icons are missing at these places, but shown for example here at 12 (!) zoom http://www.openstreetmap.org/#map=12/49.15556/14.761067

**Comment by vshcherb** [comment]
Fixed
