### ISSUE TITLE
Online service with fuel prices

### ISSUE THREAD

**Issue by patranger** [osmandapp/OsmAnd#14423]
# 🚀 feature request

### Description

It would be useful to integrate into OsmAnd some online service that allows you to display fuel prices at each gas station and to set the route to the nearest gas station with the lowest fuel price. And that any user could send a price update.

**Comment by scaidermern** [comment]
Duplicate of #13039.

**Comment by patranger** [comment]
Sorry, I did not notice that this is a duplicate of the thread, although it means that there is a lot of interest in the topic and with rising fuel prices it is a necessary function.
