### ISSUE TITLE
History on Dashboard

### ISSUE THREAD

**Issue by duiveldoder** [osmandapp/OsmAnd#14422]
### Description

I disabled history.
What I expect then in the Dashboard to get get of the "history" 
Reason: my mapping profile for contributing to OSM - when I click dashboard I want to see instantly:
-1 tracks
-2 photos/notes
nothing else

So while history is disabled - a user shouldn't see "any history" and have  look what it shows me!
It shows me old gpx which don't even exist on my phone anymore. When I click "show all" it shows me nothing, just that I disabled history. That's weird showing me a list of gpx - which I don't even want to see and don't even have on my phone anymore - and then click on the "select all" I see nothing. 

### How to reproduce?
Well it's just the dashboard - and disabling history.. that's it.

### Your Environment
OsmAnd Version: 4.2.0#34062m, released 2022-05-13 (the nightly of that day)
Android/iOS version: 10
Device model: Huawei Mate 20 Pro

<table style="width:100%">
  <tr>
    <th>As you can see - history is turned off aka empty nothing</th>
    <th> here you see the bogus gpx it's showing</th>
    <th>here you see there are no GPX tracks on the phone - for mapping purposes I wipe clean everything after it's uploaded/processed to OSM</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/15773876/171063163-3e36d50a-fdc2-4b6c-9795-3ec152ff64f6.jpg"  width="250" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/15773876/171063154-d4531608-308e-48e7-bdce-a78d364f1acf.jpg"  width="250" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/15773876/171063170-015a20b3-f821-41a4-9b51-e14b394998e2.jpg"  width="250" height="auto"/> </td>
  </tr>
</table>   

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by Jiuvel** [comment]
Hello, I reviewed the topic and exactly the same thing described in the comment happens to me.  It is evident then that there is some problem in the functioning of the history.  Greetings, thank you very much.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14214mqta, Released: 2023-03-03
Done

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/16709

**Comment by vshcherb** [comment]
FIX IS REVERTED (leads to user data loss)

NO DELETE IN BACKGROUND.

Please DELETE User Data only on action and with confirmation!

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#14270mqta, Released: 2023-03-25
Done
