### ISSUE TITLE
Bicycle profile. Wrong route recalculation.

### ISSUE THREAD

**Issue by Gbernardy** [osmandapp/OsmAnd#14436]
Wrong route recalculation.  I deviated from the gpx route (deviation in red).  Osmand near point B gave me vocal information to return to point A instead of making me continue along the path.

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/99968793/171357543-50d0b89a-831f-4eb0-adb3-af7e436b8982.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

Route recalculation

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/99968793/171358162-05577df6-cb73-4abe-a70f-881bed22fbb2.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

Point A
https://osmand.net/go?lat=45.61195&lon=12.04988&z=19

Point B
https://osmand.net/go?lat=45.61528&lon=12.04553&z=19

Other cases of wrong recalculation are described in issue #14174

Device : OP4B83L1
Brand : OPPO
Model : CPH1907
Product : CPH1907EEA
Build : CPH1907_11_F.59
Version Android : 11
App Version : OsmAnd
Apk Version : 4.1.11 421

**Comment by Gbernardy** [comment]
Also yesterday I went out on a bicycle ... and more than once I deviated from the track (for my distraction) and the directions to resume the route were not correct.

Avoid this ... I close the navigation and restart it, so I get the right information.

**Comment by Zirochkabila** [comment]
> 

Your case was checked with version 4.3.0#13555mqta, released: 2022-06-07 of the OsmAnd application - the case could not be reproduced.

You can wait for an update where this will be corrected or you can download the current version of the application
https://play.google.com/apps/testing/net.osmand

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/172411967-50a61808-9230-46b0-b575-2c40b4be6c87.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>
