### ISSUE TITLE
Names are showing up in English in map tiles but the Info Card section displaying names in Santali Ol Chiki

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#14433]
### Description
Names are showing up in English in map tiles but the Info Card section displaying names in Santali Ol Chiki

### Steps to reproduce
Go to this location 23°21'18.0"N 85°19'33.7"E -> chose Santali (incomplete) in Display language -> tap on the "Gossner College" -> compare information in the map and in the context menu

### Actual result
Information on the map and in the context menu is different

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/171206516-90e0a179-ccba-431a-a51e-aaf3dbe0e4ba.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

### Expected result

Information on the map and in the context menu is a same

### Your Environment
OsmAnd Version: 4.2.0#13535mqta, released: 2022-05-31
Android/iOS version: Android 11
Device model: POCO X3 NFC

**Comment by Cloud-Prakash** [comment]
![Screenshot_2022-06-11-11-45-59-957_net osmand dev](https://user-images.githubusercontent.com/102574696/173176055-474e9ef3-a082-463b-a3c8-923e989e359b.jpg)
Please close this issue as it is working Ok.
