### ISSUE TITLE
Document OsmAnd Live - free for OSM mappers

### ISSUE THREAD

**Issue by Max1234-Ita** [osmandapp/OsmAnd#14439]
Docs link

- https://osmand.net/docs/user/personal/maps/#osmand-live
- https://osmand.net/docs/user/plugins/osm-editing

### Description

The OsmAnd Live documentation page is visible from any browser @ URL [https://osmand.net/docs/user/personal/maps#osmand-live](https://osmand.net/docs/user/personal/maps#osmand-live) : the text is well written and it very understandable, however it does not mention at all the criteria to be met for a mapper to get Live Maps service enabled for free upon OpenStreetMap contribution.

The only information a user can get, is from OpenStreetMap editing plugin seetting menu, where he/her can see the message "you have provided enough OpenStreetMap contributions and can now enjoy unlimited OsmAnd map updates".

Unfortunately, the available documentation does not mention this feature and it's not clear what kind of activity is considered  "enough contribution":
  - Individual changes are counted, or changesets?
  - How many of them are required? e.g. is that 10, 100, 1000? 
 
Please explain that more in detail.

### How to reproduce?
1. Launch OsmAnd, tap the hamburger menu button then go to Plugins -> OpenStreetMap editing -> Settings -> Map updates for mappers.
2. Note that the message there just communicates that the service is enabled/disabled and shows the total amount of changes done in the past months; no clue about what is the minimum amount required to enable the service.

### Your Environment
OsmAnd Version:    4.1.11
Android/iOS version:  Android 11
Device model:  Samsung Galaxy A50

**Maps used (online or offline):**   
Offline maps of Italy; using Live update for Italy-Lombardy region (that's where I'm living and mapping)

_
![Screenshot_20220601-124557_OsmAnd+ 1](https://user-images.githubusercontent.com/15315381/171388143-b0e98694-314c-46ca-97b8-799213fb497f.jpg)

**Comment by vshcherb** [comment]
We should add here https://docs.osmand.net/docs/user/personal/maps#osmand-live
