### ISSUE TITLE
`fixme` and `note` tags are not updated when using OsmAnd Live

### ISSUE THREAD

**Issue by Dimitar5555** [osmandapp/OsmAnd#14443]
### Description

I've removed a few `fixme` and `note` tags but they haven't updated after 2 weeks of waiting.

### How to reproduce?

1. Download full map for Bulgaria
2. Perform manual live update
3. Enable the OSM mapper assistant from the Details menu in the map configurator
4. Go to 42.66543, 23.26172

### Your Environment
OsmAnd Version: 4.1.11
Android/iOS version: 10
Device model: Honor 20 Lite

**Comment by scaidermern** [comment]
Related to #12960.

**Comment by vshcherb** [comment]
Fixed with 4.2
