### ISSUE TITLE
Fix screen rotation while navigating 

### ISSUE THREAD

**Issue by habitoti** [osmandapp/OsmAnd#14442]
# 🚀 feature request

With the new SmartphoneGrip from Bosch, a lot of bicycle users will be forced to using OSMAND in landscape mode while navigating or following a predefined track. Being fixed almost horizontally, the phone's sensors don't detect any specific orientation now. If you quickly checked another app and return to OSMAND, you usually end up again in portrait mode. So you have to unmount the device, lift it up and rotate it to force it to landscape again.

### Describe the solution you'd like

A profile setting should allow for forcing a certain rotation setting while navigating. So I can set it to "Landscape" and have it always rotate into landscape orientation, no matter what the position sensors think (or actually just don't know...).

### Describe alternatives you've considered

At least for iOS the standard system device orientation lock can't be used, as it forces the device to portrait mode only. You can't lock a phone in landscape (works only for iPads).
I read something about a screen orientation feature for Android, however I couldn't find anything similar for iOS.

**Comment by XandrexOSM** [comment]
see this other ticket : 

https://github.com/osmandapp/OsmAnd/issues/15093

**Comment by scaidermern** [comment]
> A profile setting should allow for forcing a certain rotation setting while navigating. So I can set it to "Landscape" and have it always rotate into landscape orientation, no matter what the position sensors think (or actually just don't know...).

This is already possible. You can lock the rotation and set it to a fixed mode for individual profiles: Settings / Profile / General settings / Screen orientation

**Comment by scaidermern** [comment]
> > This is already possible. You can lock the rotation and set it to a fixed mode for individual profiles: Settings / Profile / General settings / Screen orientation
> 
> Not for iOS...

Oh, I don't know about iOS. However, this is the repository for the Android version. For iOS there is https://github.com/osmandapp/OsmAnd-iOS instead.

**Comment by habitoti** [comment]
Ok, thanks (didn't know, and also not obvious from naming, though...). Will close this one and reopen over there.
