### ISSUE TITLE
Configure screen: add 'revert to defaults'

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#14459]
We keep spending a significant anount of development to facilitate customization. I have discussed elsewhere if this is reaaly appreciated by many enough users to be worth the effort, the esulting app complexity, and support cases and bugs to deal with.

Here I would like to note that on the new config screens for Configure screen/widgets we are missing any buttons to go back to installlation defaults.

I write this issue with the philosophy that the default setup of the app and its initial configuration should be good enough for 80%+ of all users, and even users who have spent some time with customizing something may get lost after a while (#14458) and decide they may just be better of reverting to what the app developers think makes sense in most cases?

**Comment by dmpr0** [comment]
Widget panel in edit mode, has **Reset to default** actions. 

## ToDo

- [ ] **Configure screen**: 
- - [ ] Add actions icon to AppBar
- - [ ] Add **Actions** card with **Reset** to default and **Copy from another profile** to

- [ ]  Widget panel screen in view mode
- - [ ] Add actions icon to AppBar
- - [ ] Add **Actions** card with **Reset** to default and **Copy from another profile** to

<table style="width:100%">
  <tr>
    <th>Configure Screen</th>
    <th>Widget panel</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/172402169-9346312a-8051-4153-a0a8-0ec81e7a292c.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/172402165-5277a23d-b3a7-4155-be46-da82091e760a.png"  width="300" height="auto"/> </td>
  </tr>
</table>
