### ISSUE TITLE
Revert to calling the shortest route the shortest route. do not call it user specific turly or falsely a fuel-efficient route.

### ISSUE THREAD

**Issue by MparkG** [osmandapp/OsmAnd#14454]
Revert to calling the shortest route the shortest route. do not call it user specific turly or falsely a fuel-efficient route.

A car might be (is really) more fuel efficient when travelling on a autobahn in highest gear, rather than driving in lowest gears through traffic lights, cities and shortest zig zag route.

Stick to the factual characterization of the route, the shortest,... 

thanks

**Comment by naoliv** [comment]
If I am not wrong, it's not the _shortest_ route, but only a kind of _shorter_ route.

**Comment by vshcherb** [comment]
Its not the shortest route, the shortest would be pedestrian without any penalties. 
Technically this is a fastest route for a vehicle with maximum speed of 50-70 kmh, so it leads to a fuel-efficient route

**Comment by scaidermern** [comment]
> If I am not wrong, it's not the _shortest_ route, but only a kind of _shorter_ route.

What about calling it "shorter route" then? Yes, that will sound strange. But fuel-efficient is really misleading if not even wrong for most cars.

Can we at least try to find a better term for it?

**Comment by vshcherb** [comment]
It's indeed how fuel-efficient is defined, we probably can do a better job in documentation first. And it actually it mostly produces "human-defined" shortest route.

**Comment by MparkG** [comment]
thanks for responding so quickly.
I see, its not actually the shortest route, but imo it remains not to be called a fuel efficient route...
I would neither call it shorter route, i believe to understand it is a route based on travel time for the given speed and not shortest distance.

fuel efficient really meaning slow speed..
 then we can call it slow in the first place...

(that would be correct although not as intuitive to understand the meaning. but that is how you technically described it)

**Comment by pebogufi** [comment]
What abour using a therm which will never be missleading in interpretation:
"alternative route"
