### ISSUE TITLE
Icon to small for hazard=curve

### ISSUE THREAD

**Issue by GabrielSebastianMoise** [osmandapp/Osmand#1446]
The icon rendered near the road are too small for hazard=curve

It would be nice to have bigger icons. For the moment, the icons are barely visible and only if the speed is under 45 km/h !

Could you increase the icon size , shown near the road ?!?!? And to be shown also if the speed you are going is much higher. In this way you'll see that in your way , will be a portion of the road that need more attention !

Thanks !

**Comment by xmd5a2** [comment]
It is not possible because of technical reason (these icons are overlays over regular icons). Maybe it will be better to show notification over map while routing like pedestrian crossings, etc?

**Comment by vshcherb** [comment]
We are going to make a warning for it, actually already in the master, lets test it.

**Comment by GabrielSebastianMoise** [comment]
ok, can I translate it for Romanian Language if there is english vocal
sentence to translate the line  ?

I can't find here the lines..... for pedestrian crossing, hazard=curve,
etc......

https://github.com/osmandapp/OsmAnd-resources/blob/master/voice/ro/ttsconfig.p

2015-08-04 12:23 GMT+03:00 vshcherb <notifications@github.com>:

> We are going to make a warning for it, actually already in the master,
> lets test it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osmandapp/Osmand/issues/1446#issuecomment-127539559>.
>



-- 
Toate cele bune !
*------------------------*
Gabriel Sebastian  Moise
Administrator Local - Departament Tehnic
*------------------------------------------------------*
NextGen Communications S.R.L. - Campina

Mobil NextGen  : 076 111 65 59
Mobil Personal : 0726 311 957

Adresa Postala: Strada Grivitei, Nr.63, Campina, Romania !
*------------------------------------------------------*
