### ISSUE TITLE
Add separate map for Warsaw

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#14468]
Currently, the map for Warsaw is available only as part of the Masovia region (237MB).
Maybe we could do the same for other European capitals that are available only in region maps over 200 MB.

**Comment by vshcherb** [comment]
Division of Masovia is quite complicated [40 subregions], so it will be quite complicated solution
![image](https://user-images.githubusercontent.com/1042025/172151723-9d18483d-4d32-4f14-bdb5-d26e7fa72b63.png)
