### ISSUE TITLE
Voice prompts do not work correctly when the navigation is on

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#14469]
### Description
Voice prompts and motion widgets do not work correctly when the navigation is on (openGL)
https://osmand.net/map/?start=50.324256%2C20.274643&end=50.327502%2C20.323474&mode=car#15/50.3249/20.2996

### Steps to reproduce
Chose Motorcycle configure profile -> Select point of departure 50.32434° N, 20.27468° E -> Set destination 50.32776° N, 20.32352° E -> start navigation

### Actual result
Voice prompts and motion widgets do not work correctly when the navigation is on

https://user-images.githubusercontent.com/104760013/172128536-ae1cfd3e-2766-42fb-979a-3e6b87ed39cd.mp4

### Expected result
Voice prompts and motion widgets is work correctly when the navigation is on

### Your Environment
OsmAnd Version: 4.3.0#13552mqta, released: 2022-06-06
Android/iOS version: Android 11
Device model: POCO X3 NFC

**Comment by vshcherb** [comment]
Please reopen once it's reproduced on dev device.
