### ISSUE TITLE
[Question / feature request] How to easily display POI info? (opening hours, etc.)

### ISSUE THREAD

**Issue by klawdhfzasjhaa** [osmandapp/Osmand#1447]
Right now, I only found this very long way to show the POI data:
- long press near the POI on map
- "search nearby"
- choose POI type
- long press on POI
- choose "show POI data"

Is this intended or did I miss something? On standard maps sites like http://openrouteservice.org/ it's the same behaviour (no action at click on POI).

I'm using:
- Nexus 4
- Cyanogenmod 12.1 (20150630 NIGHTLY), Android 5.1.1
- OSMAnd~ 2.1.1
- all rights granted in CM Privacy Guard

**Comment by sonora** [comment]
A little easier, but not much, is this:
- On the map screen, tap the dashboard button in the lower left corner of the map
- Tap "Search POI", select your category (or type a name), hit "Search"
- When the search is finished, all POIs (for the filter you selected) will be shown sorted by distance (from the search origin you selected, by default the currently viewed map center), closest first.  Opening times will be displayed immediately in the list, with a color coding for green=open, yellow=closing<30min, red=closed. If you need more details, tap any POI entry, and select e.g. "Show POI description".

**Comment by klawdhfzasjhaa** [comment]
Thanks for the tip. As you said, it's also not that user friendly.
Is there maybe a technical / design reason, why this cannot be implemented more user friendly?

**Comment by sonora** [comment]
I personally think a lot about usability issues, and welcome every suggestion how things can be improved!  :-)

**Comment by klawdhfzasjhaa** [comment]
One more thing, that I noticed. When I tried to long press a POI to show the description, the icon shrunk back to normal (tiny) size within one second. It would be cool if the icon would get bigger when you do a long press near it, to make access to the details easier. Both features would be yet to be implemented.

**Comment by utack** [comment]
This one of the big features I'd like to have.
Is this especially hard to integrate?
For example the "notes" plugin can already suggest all nearby notes takes when long pressing on a location, maybe the code is easy to copy and apply to regular POI?

**Comment by ShamblerBishop** [comment]
+1 on this.

This is actually a critical/badly-needed feature, as it's a very basic/fundamental UI requirement, to be able to directly select POI icons like this.

The lack of this ability, just makes the UI seem unfinished/incomplete - and will frustrate users looking to find more info about a POI, yet not finding an immediately obvious/workable way of doing so.

**Comment by sonora** [comment]
I kind of lost track of this a little. Could anyone please describe the idea how this is supposed to work?

Please note that you can make all POIs trappable if you display the POI layer on the map: `Via Search / POI` and the "Display all on map" button, or via `Configure map / POI`,  you can display the POI categories you want (or all!). The orange disks which will appear on the map are tappable, and all their information is accessible via the popup context menu when tapping them.

It has some impact on performance, and also taps on the map may accidentally bring up the context menu (which I guess could be a usability issue if this was always enabled). Is this the functionality you ask t be enabled by default?

**Comment by raindropsfromsky** [comment]
Imagine that the orange icons are on a different layer. Both **search nearby** and **Search POI** commands first list all those icons, and then allow you to pick one.

Instead, can we simply "punch through" the current (map) layer and reach the POI layer by simply long-pressing?

In other words, if I long-press on a POI that is visible on the map, OsmAnd should not look up address. Rather, it should pick that POI and present it. If the user long-presses a little away from the POI, let OsmAnd look up the address.

This applies to points only, not to areas (land uses or buildings).

**Comment by sonora** [comment]
That's exactly what I was asking with my suggestion above: If you really want this kind of "fully interactive map" all the time.  It is implemented, just test it. The only remaining action would be we make the orange disks transparent :)

**Comment by raindropsfromsky** [comment]
Fantastic! I am downloading the master-nb file with 17:29 timestamp. Hopefully it has this change(?)
Will revert with the feedback.

**Comment by raindropsfromsky** [comment]
I installed the file (OsmAnd~2.4.0#M17653M), and tried to long-press on a POI that was displayed on the map (not the orange circle). But OsmAnd tried to look up the address as usual.

**Comment by sonora** [comment]
There was no change. The "tappable" layer is the one with the orange circles. I was only talking hypothetically that we could make the circles transparent instead of orange, if that is what was requested. But the functionality has always been there, just chose to display the overlay for all or just the POIs you are interested in.

**Comment by raindropsfromsky** [comment]
Oh I see!

Yes, by default the circles should be transparent, and the POI layer should be always active, so that they are always tappable. The user does not need to know which layer actually brings that functionality!

**Comment by raindropsfromsky** [comment]
Just thought of a possible problem: At low map levels, OsmAnd map layer hides many POIs. As we zoom in, these hidden POIs start appearing. But when any POI appears, its symbol is always of a standard size.

In contrast, the POI layer (orange circles) appear as tiny dots at low levels, and as we zoom in, they become larger in size. That means that our tappable target area also changes with zoom.

For our purpose, the size of the orange circle (i.e., the tappable target area in the POI layer) MUST always match the size of the POI symbol in the map layer, as we zoom in/out.

Only then shall we get WSYISYT (What-you-see-is-what-you-can-tap) behavior.

Otherwise people may complain that some blank areas behave like POIs, and some POIs do not respond when tapped.

**Comment by sonora** [comment]
Again: What I suggest is to please test impact on performance and usability.

**Comment by raindropsfromsky** [comment]
OK how about turning off all POIs on map layer? That will show the map somewhat like Google map (roads only, and possibly all shapes).

So the only POIs that appear are from the POI layer. No conflict! And they are all tappable!

**Comment by sonora** [comment]
Please re-read the thread: I never talked about any conflicts ... I asked about performance and usability :-)
