### ISSUE TITLE
Add support for `motorcycle = yes/no` for Motorcycle navigation type

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#14474]
• Example of `motorcycle = yes` https://www.openstreetmap.org/node/322765686
• Example of `motorcycle = no` https://www.openstreetmap.org/way/154236531 from  https://github.com/osmandapp/OsmAnd/issues/14074#issuecomment-1148266600
<table style="width:100%">
  <tr>
    <th>Car</th>
    <th>Cycle</th>
    <th>Motorcycle</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/172200961-d1eb80ab-accf-4356-b20c-893d4aac56ba.jpeg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/172200968-be45ac1a-e8e9-4a14-8286-7f2de2879d66.jpeg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/172200974-17eab958-9471-4808-b554-fb61e56d81ed.jpeg"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Dima-1** [comment]
Request 
[Android](https://github.com/osmandapp/OsmAnd/pull/14553)

**Comment by nnngrach** [comment]
Request
[IOS](https://github.com/osmandapp/OsmAnd-iOS/pull/2040)
[Core-legacy](https://github.com/osmandapp/OsmAnd-core-legacy/pull/97)

**Comment by aceman444** [comment]
Does this actually work for anyone?
@dmpr0 have you tested the fix?

**Comment by aceman444** [comment]
The example bollard may actually work, because it does not contain any 'vehicle' or 'access' tags. But it does not work on other cases. I will provide a fix.
