### ISSUE TITLE
Destination street is being mixed up with other street while correct on nodes

### ISSUE THREAD

**Issue by Electrenator** [osmandapp/OsmAnd#14479]
# 🐞 routing report

### Routing engine
- [x] OsmAnd's in-app offline routing
- [X] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile
Seen this hapen with the bike routing on balanced.

### Start and end points
The start point doesn't really seem to matter but I noticed it at least from Hoorn station. Seen it again from this trash can (https://www.openstreetmap.org/node/6618880474). 

The destination I want to go is the street "Vijzelmolen" (For example number 11 which I didn't need to go too but tested it there; https://www.openstreetmap.org/node/2782097412) but I'm being routed to the same address over at "Weidemolen" (https://www.openstreetmap.org/node/2782097425).

### Actual and expected routes
I would expect to be routed to the "Vijzelmolen" when searchin for an adress there and to be routed to the "Weidemolen" when I search for an adress there. And when I click on one that looks like the other I expect the UI to show the names correctly.

### Is this a regression?
I don't know if this was a thing that happend in previous versions. Just started using routing via OsmAnd

## 🌍 Your Environment

**OsmAnd Version:** 

<pre><code>
4.0 08/2021
</code></pre>

**Device and Android/iOS version:** Android 11

**Maps used (online or offline):**

- [X] Offline maps offered within the OsmAnd app for download.
    - Within `Nederlands`->`Noord-Holland`->`Standard map`
- [ ] Online (tile / raster) maps 

**Anything else relevant?**
Do want to add that there are two "Vijzermolen [house number]" results in my destination search. Clicking on any of those will result in one of the routing paths to the locations given in `Start and end points` while both saying Vijzermolen within the UI.

**Comment by Zirochkabila** [comment]
Your case was tested with OsmAnd app version 4.2.2 - it could not be reproduced
Try to update the application
Please check the date of the map update and try to reset the profile to default settings.

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/175304475-54e4b559-6f2f-4b5d-93ec-fb568ea494ff.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>
