### ISSUE TITLE
Opengl: map rendering frozen

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#14483]
See video.
https://t.me/ruosmand/99116

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13554mqta, дата выпуска: 2022-06-06
Android version: 12
Device model: poco x3 pro

**Comment by Nine-Tailed** [comment]
Overlay map.
https://t.me/ruosmand/98958

**Comment by Nine-Tailed** [comment]
If you increase the scale of the map to 20 zoom, and then sharply reduce it, the map disappears.
![IMG_20220607_134529.jpg](https://user-images.githubusercontent.com/12549744/172361979-4231f76a-e875-4669-9875-8aa4cf18e871.jpg)
https://user-images.githubusercontent.com/12549744/172361994-133019a0-980d-4a38-9e23-1a5fef9eb2b7.mp4

**Comment by vshcherb** [comment]
Fixed

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/commit/a7460ee00409384f0b0366abd47713d9a8c27ff0

**Comment by Nine-Tailed** [comment]
It seems that this bug has not been fully fixed, at the moment the raster overlay map is turned on, some tiles are not drawn until the scale is changed or the map is significantly shifted.
![image](https://user-images.githubusercontent.com/12549744/173770194-4dab7dd1-3be2-49bd-a4bb-4922837a5526.png)

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/commit/3168755867fefe6fb4369f66790af28fb256d08b

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/commit/44513c061c0902ca82f169221497cf7b610a102e

**Comment by vshcherb** [comment]
The bug is repetitive on iOS as well.

**Comment by Zirochkabila** [comment]
OSMAnd version: 4.2.2
Map type: OSMAnd
No over/underlay enabled. If overlay POI, parking places is enabled, some issue occurs.
In the Dalfsen area (Overijssel map, near Zwolle, in the Netherlands) user is observe these mistakes.

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/177311562-1364eb7a-a868-45dd-8b09-c8239b3ccceb.PNG"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/177311581-51f3dedf-e534-4c28-a85e-b78ee24b9568.PNG"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/177311584-cbbd83da-da2a-465f-9c20-d9d137e4e47e.PNG"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by alex-osm** [comment]
Temp fix
