### ISSUE TITLE
Issue with current search address function after selected street is cleared

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#1448]
Not sure if we still want to improve our current "Search address" function, but here is a bug with it which has confused some users:

(1) On the dashboard, go to "Search address"
(2) Specify an address via region / city / street
(3a) After having specified the street, either hit the device's back button, then delete the street via the (X) button next to it
(3b) or select "Display on map", then enter the search address function again, and from the previous address selection which will still be displayed, just delete the street (via the X button to the right of it).
(4) Now hit the "Show on map" icon: You will receive a toast saying "Select city or street first", which is bogus, because if you do the search from scratch, after just specifying the city/town/village without selection of a street ,OsmAnd will of course readily display just the city/town/village selected after hitting "Show on map" then.

The issue is in
	public void select(int mode) {
		if (searchPoint == null) {

**Comment by vshcherb** [comment]
Deprecated
