### ISSUE TITLE
The app crashes when zooming (open GL)

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#14493]
### Description
The app was crashes when zooming (Couldn't reproduce it on the release version)
OsmAnd Live is off
https://osmand.net/map/?start=45.817313%2C8.826687&mode=car#15/45.8300/8.5548
[logcat (1).log](https://github.com/osmandapp/OsmAnd/files/8860471/logcat.1.log)

### Steps to reproduce
Download Italy Piemont map -> zooming 45°49'48.9"N 8°33'03.7"E

### Actual result
The app crashes

https://user-images.githubusercontent.com/104760013/172587893-3d8a2d34-8f7a-41ad-afe1-ebd23368fabd.mp4

### Expected result
The app displays the map and does not crash

### Your Environment
OsmAnd Version: 4.3.0#13557mqta, released: 2022-06-08
Android/iOS version: Android 11
Device model: POCO X3 NFC

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-core/commit/c5bb64ca92dfd2759211ecc1ea08584406a2be81
