### ISSUE TITLE
Incorrect estimated download size

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#14491]
### Description
If the tile size is 512 pixels, then the map size is calculated incorrectly. In this case, the estimated size of the map is equal to the number of tiles, which is not true.

![Screenshot_2022-06-08-09-37-02-598_net.osmand.plus~2.jpg](https://user-images.githubusercontent.com/12549744/172549716-6882472e-9364-4178-94f9-26431bf0657e.jpg)
![IMG_20220608_093808.jpg](https://user-images.githubusercontent.com/12549744/172549757-31b24b84-4c7d-4bdb-a25e-98a86005fb15.jpg)

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13557mqta, released: 2022-06-08
Android version: 12
Device model: poco x3

**Comment by vshcherb** [comment]
Not clear what is the tilsize should be used for rerence - 1 MB for 256, 4 MB for 512?

**Comment by Nine-Tailed** [comment]
> Not clear what is the tilsize should be used for rerence - 1 MB for 256, 4 MB for 512?

These are very large numbers for such small drawings as tiles.
for tilesize 256 - 10-15 kB
for tilesize 512 - 30-70 kB

Initially, I was confused by the equality of the number of tiles and the estimated download size.
I created 4 versions of google maps and for some reason the sizes for the databases are much larger than the sizes for the files.
tiles 256, storage in the database - number of tiles 4545, size 1136 Mb;
tiles 256, storage in files - number of tiles 4599, size 63 Mb;
tiles 512, storage in the database - number of tiles 4562, size 4562 Mb;
tiles 512, storage in files - number of tiles 4538, size 262 Mb.
Is there an error in the calculation of the occupied space for the database?
I also uploaded a map with 256px tiles to the database and the estimated size of 1136 Mb actually turned out to be 64 Mb.
![image](https://user-images.githubusercontent.com/12549744/173232678-9008df53-9bdd-4d74-92f6-719be2193551.png)

sqlitedb:
![image](https://user-images.githubusercontent.com/12549744/173232369-46984468-ea54-46ee-ab97-ade60c30613a.png)
files:
![image](https://user-images.githubusercontent.com/12549744/173232359-3ce85067-67ff-4a62-9563-de9ddb136fa6.png)
sqlitedb:
![image](https://user-images.githubusercontent.com/12549744/173232386-f5cd49e1-85d3-478a-bb0c-c5ad5b6de5e8.png)
files:
![image](https://user-images.githubusercontent.com/12549744/173232401-2b299335-51b5-48c7-b7f6-7cf13eb2703c.png)

**Comment by vshcherb** [comment]
Looks like it's a bug, thanks for documenting. 
Summary:
Tilesize 256 - 10-15 kB = 15 KB
Tilesize 512 - 30-70 kB = 50 KB

DB and sqlite should be the same size in the end!
