### ISSUE TITLE
OpenGL: Enabling/disabling of hiking routes requires app restart

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#14494]
With enabled OpenGL, enabling or disabling of hiking routes (via Configure map / Routes) has no effect. This change gets applied only after restarting OsmAnd.

This bug probably applies to all other routes (cycling etc.) as well.

OsmAnd 4.2.2.

Could be related to #14495.

**Comment by vshcherb** [comment]
It doens't require restart, it requires only refresh i.e. scrolling the map

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/commit/6e0d58b981f4a33a5a21cd7b87c754b95f627a60
