### ISSUE TITLE
Incorrect pedestrian route

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#14499]
1) https://maptile.osmand.net/map?start=56.144468%2C47.211181&end=56.144214%2C47.211519&mode=pedestrian#18/56.14429/47.21376
![image](https://user-images.githubusercontent.com/12549744/172723098-ac5a61ff-42ff-44ea-8057-9cfdc457a8aa.png)

2)https://maptile.osmand.net/map?start=60.055968%2C30.417173&end=60.055186%2C30.420628&mode=pedestrian#18/60.05561/30.42089
![image](https://user-images.githubusercontent.com/12549744/172723228-3f5c5f9c-0468-491b-aa92-e539ccb5f730.png)

**Comment by scaidermern** [comment]
I've noticed a similar wrong routing here. There is a strange and unnecessary loop in the calculated route:
https://maptile.osmand.net/map?start=51.043792%2C13.724896&end=51.043595%2C13.724905&mode=pedestrian#19/51.04377/13.72550
![foo01](https://user-images.githubusercontent.com/1040784/172777535-124882da-c3e0-4d96-b1aa-cd741d2ac06b.png)

The resulting route is correct when choosing a different start point:
https://maptile.osmand.net/map?start=51.044183%2C13.724644&end=51.043595%2C13.724905&mode=pedestrian
![foo02](https://user-images.githubusercontent.com/1040784/172777579-8f896714-380a-4b9a-94bd-9bf1d6ff388e.png)

Maybe these two issues are related.

**Comment by vshcherb** [comment]
**Main issue**: https://maptile.osmand.net/map?start=56.144469%2C47.211170&end=56.144341%2C47.210981&mode=pedestrian#19/56.14430/47.21163 (Java routing is OK, C++ routing is not OK)
Here is the same
https://maptile.osmand.net/map?start=60.055968%2C30.417173&end=60.055186%2C30.420628&mode=pedestrian#18/60.05577/30.41873 (Java - OK, C++ not ok).
Please don't add similar issues any more until this fixed ;-)

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-core-legacy/pull/96

**Comment by vshcherb** [comment]
Probably another issue in java - routing https://maptile.osmand.net/map?start=60.055995%2C30.417253&end=60.055194%2C30.420440&mode=pedestrian#19/60.05595/30.41836

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-tools/pull/487

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-tools/pull/491

**Comment by vshcherb** [comment]
Merged on website
