### ISSUE TITLE
String context missing

### ISSUE THREAD

**Issue by yarons** [osmandapp/OsmAnd#14497]
### Description
I'm trying to translate a string and I'm not sure what it means

https://github.com/osmandapp/OsmAnd-resources/blob/6d5dc3b7f36e29ae8fe5c311761148421e805702/rendering_styles/nautical.render.xml#L20

It reads:

    Additional text info on seabed surface_qualification, combined surface types, category and taxon of weed or seagrass

Thanks.

**Comment by vshcherb** [comment]
It's about Sea Bed https://github.com/osmandapp/OsmAnd-resources/pull/827

**Comment by josail** [comment]
Surface_qualification is like an adjective further describing the surface type

Two different types can be combined

Taxon refers to a plant genus and specie description (taxonomy)

The information is notmally condensed to single letters displayed on nautical charts. 
The concept is explained here:
https://wiki.openstreetmap.org/wiki/Seamarks/INT-1_Section_J

However 100% transfer of this concept was not possible in OSMAND (at least I did not achieve it) and as second best option, all information can be displayed as text as option for "all" "seabedDetail"

**Comment by yarons** [comment]
So it's really bulky but I translated it in parenthesis while keeping the original term, I'm not sure I like it but it seems as if it's a pretty descent solution in case the user will run into the English term somewhere.

Thanks.
