### ISSUE TITLE
Second (red) arrow on maps (for destination direction)

### ISSUE THREAD

**Issue by klawdhfzasjhaa** [osmandapp/Osmand#1449]
I have a permanent (in map and navigation mode) second red arrow on the screen. Is this normal?

I'm using:
- Nexus 4
- Cyanogenmod 12.1 (20150630 NIGHTLY), Android 5.1.1
- OSMAnd~ 2.1.1
- all rights granted in CM Privacy Guard
![screenshot](https://cloud.githubusercontent.com/assets/2808094/8614882/7543fd70-26ee-11e5-81da-bd430602caac.png)

**Comment by GabrielSebastianMoise** [comment]
That's the direction to the Destination Point, or to the latest Destination Point.  you can disable it in settings !

**Comment by klawdhfzasjhaa** [comment]
Thanks Gabriel!
Settings are often in context aware submenus..This is confusing sometimes...
If someone searches the setting: It hides here:
- bottom left icon (four little squares in one bigger square)
- icon in screenshot below
- Configure screen
- (scroll down to the end) disable "Show destination direction"


![clipboard](https://cloud.githubusercontent.com/assets/2808094/8616464/c7a44f86-26fb-11e5-99f0-b6b108288e2f.jpg)
