### ISSUE TITLE
Free version should allow updating of maps or reword error message

### ISSUE THREAD

**Issue by jensb** [osmandapp/Osmand#1450]
The free app from Google Play does not allow updating of map material if you have downloaded 10 maps already. It claims that the user has already downloaded the maximum number of maps for the free version. IMHO this should be possible.

**Comment by sonora** [comment]
Well, that's our limitation, should be enough for testing it? We would appreciate if you spend the few bucks and support our hosting and bandwidth expense  :-)  If you rally cannot afford it you can also go through the hassle and download more maps via the web.

**Comment by jensb** [comment]
I already have. This is just inconsistent behaviour for me, not a limitation in the free version that would be unacceptable for me. If you like, rename this bug to "Free version should display a different error message when updating maps", otherwise free users might be confused and think OSMand is buggy: updating maps is not the same as downloading new maps.

**Comment by sonora** [comment]
I see, thanks for clarifying! I will wait for Victor to explain if the limitation should be 10 downloads (where updates count as downloads) or 10 (concurrent) maps, (I guess this is the issue here?), and then we can certainly adjust the wording of the message to say this less ambiguously. Thx - Hardy

**Comment by jensb** [comment]
Yup. This is what I meant. Thanks!

**Comment by vshcherb** [comment]
Yes, we are planning that change for OsmAnd 2.2, but we are not planning the hotfix for 2.1
