### ISSUE TITLE
Description of the climbing POI doesn't show all relevant information

### ISSUE THREAD

**Issue by letypequividelespoubelles** [osmandapp/OsmAnd#14502]
# 🚀 feature request

### Description

OsmAnd just doesn't show all information : just the min climbing rate, min and max length of the climbing spot. Exemple with [this POI](https://www.openstreetmap.org/node/3500792528)
![photo_2022-06-09_11-57-04](https://user-images.githubusercontent.com/54240434/172820616-0ca998ca-bc8d-43ce-b1e2-ae76aa8aeb55.jpg)

### Describe the solution you'd like

1) Give min, mean, max climbing rate, the number of route (climbing:route=<number>), the number of needed bolts, orientation, etc ... as described in [the wiki](https://wiki.openstreetmap.org/wiki/Climbing)
2) Be able to filter depending on those information while searching POI

Thanks a lot !

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.3.0#13943mqta, released: 2022-11-12

I see the possibility to filter depending on POI information (2nd point)
But, I don't see the information specified in paragraph 1

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/201492063-828f4623-a853-4113-ba62-1964100afc77.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
@Zirochkabila Try to create Custom filter with extra parameters.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.3.0#13945mqta, released: 2022-11-14
The parameters mentioned in paragraph 1 are stilln't displayed


https://user-images.githubusercontent.com/104760013/201675624-24136905-787d-419b-aad7-5384438bb6fd.mp4

**Comment by Zirochkabila** [comment]
Done
50.45671° N, 30.53427° E

https://user-images.githubusercontent.com/104760013/201683238-03b5a562-9279-4e26-8d78-522fc3c5cf08.mp4
