### ISSUE TITLE
Favourite groups as seperate gpx files

### ISSUE THREAD

**Issue by tradavyvy** [osmandapp/OsmAnd#14514]
In #14287 @vshcherb wrote:
" We need to redesign Configure Map -> Favorites similar to new Tracks list, so User could treat each Favorite List is similar to a separate GPX. "

I often thought that it would be nice if groups of favourites would be seperate gpx files. That way it would also be possible to treat 'internal' and 'external' gpx files the same way.

Assign collors icons and shapes, add delete and eddit points etc. Some of this is already possible (deleting points) but some is not (adding points).
This way it would be easier to share 'hpme made' gpx files and or use external gpx files. And last but not least do specific 'synchronisation/sharing'
 
--example: i would like to share my fishingspot favourites with my fishing buddy, my client location file with my collegue, the potential roadtrip highlights with my wife (but not my favourite bars 😉) --

And until the time osmand can do the synchronising itself it can be done by external apps.

**Comment by vshcherb** [comment]
![telegram-cloud-photo-size-4-5846039575141660691-y](https://user-images.githubusercontent.com/1042025/173186380-1c158192-7eec-4fe5-b7d6-1832f16e3c5d.jpg)
In some way it's possible you can share only the Favorites Group. May be it's not clear cause it gives a name of "favorites.gpx" and not a "<group>.gpx"

**Comment by tradavyvy** [comment]
Thanks,
I know of this option and it is nice for some uses.
I just think that splitting favourites would be more versatile. 

And more in line with how osmand treats tracks. There is not just one file that contains all recorded tracks and seperate files for the tracks that come from 'outside'.

As long as all favourite information originates from and stays within osmand it is not a big deal.
But when you start collecting, sharing and synchronising favorites seperate files are just easier.

(This all is not to say that i do'nt hugely apreciate the already enormous quality and versatility of the current favourite system, it is realy great already. But perfection is always one step away😉)

**Comment by vshcherb** [comment]
Actually this is already implemented.
