### ISSUE TITLE
Announcement for highway=motorway/trunk

### ISSUE THREAD

**Issue by 1358** [osmandapp/Osmand#1451]
It would be really nice if there were some special announcements for highway=motorway (_link, _junction) and highway=trunk.

something like "in 100 meters turn on the motorway ...." or "in 3 km leave the motorway ...", special icons and so on

**Comment by sonora** [comment]
Just a comment from my testing experience: For motorways this sounds feasible, but trunks really look VERY different in different parts of the world: While some are really buildt like motorways, others are not different at all from primary or even smaller highways (depending on country and region), hence on some occasions a special voice prompt to leave them may be more confusing than just saying "turn left/right" ... :-)

**Comment by 1358** [comment]
@sonora: good point.
What do you think about using trunk_link as an indicator which kind of announcements to use? Or maybe a special map region attribute?

**Comment by sonora** [comment]
My personal feeling is that maintaining regional exceptions in OsmAnd is beyond what we can and should do (I am even not very optimistic that regional exception would do the trick, it may even depend on more local areas), but using trunk_link sounds like a good idea to investigate!

**Comment by sonora** [comment]
Deprecated, I think. We have made many improvements to announcing road refs (which often indicate road types) etc., more words will unacceptably crowd the voice prompts.

**Comment by wehkah** [comment]
> Just a comment from my testing experience: For motorways this sounds feasible, but trunks really look VERY different in different parts of the world: While some are really buildt like motorways, others are not different at all from primary or even smaller highways (depending on country and region), hence on some occasions a special voice prompt to leave them may be more confusing than just saying "turn left/right" ... :-)

What about announcements like "Take the next exit and follow the signs towards X" or similar? 

That way you don't have to worry about different regional exceptions and you also don't have to worry about diversions because of construction sites, crashes or other disturbances that lead to closed roads, because there will be signs or traffic wardens telling drivers where to go.
