### ISSUE TITLE
Wrong guide line direction to marker

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#14529]
If you move the map in such a way that the marker approaches the border of the screen or widgets, then the line leading from the current position to the marker is under the place where you clicked on the map.

See video in telegram
https://t.me/ruosmand/99906

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#34190m, дата выпуска: 2022-06-13
Android version: 12
Device model: poco x3 pro

**Comment by vshcherb** [comment]
Это фича вообще-то
