### ISSUE TITLE
The color of the track does not change after the recording is finished

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#14530]
### Description
The color of the track does not change after the recording is finished
https://osmand.net/map?start=50.434462%2C30.542298&end=50.435088%2C30.542765&pin=50.436561%2C30.505503&mode=car#18/50.43458/30.54323

### Steps to reproduce
Select start position 50.43446, 30.54230 -> Set destination 50.43509, 30.54276 -> REC -> Chose track color -> Apply -> Start -> Start navigation -> Stop navigation -> Finish trip recording

### Actual result
The color of the track does not change
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/173383274-0bc19ec5-6661-4944-bf0d-10a0ed75898c.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/173383283-07ac735d-dbf0-4a0b-8676-0ee852d7527b.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
The color of the track must be change

### Your Environment
OsmAnd Version: 4.3.0#13570mqta, released: 2022-06-13
Android/iOS version: Android 11
Device model: POCO X3 NFC

**Comment by vshcherb** [comment]
Now it works as expected, so current recording track is always different from already recorded track. 
Probably we need to change the behavior and setup default color for all tracks (to be discussed).

**Comment by dmpr0** [comment]
> Now it works as expected, so current recording track is always different from already recorded track. Probably we need to change the behavior and setup default color for all tracks (to be discussed).

Expected is when changes you applied are saved. If the user chooses a blue color for track and saves it, the user will search for the blue track on the map. iOS works that way.
