### ISSUE TITLE
No defaults set for maximum weight and maximum height

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#1453]
No defaults are set for maximum weight and maximum height (see attached screen shots).

![screenshot_2015-07-10-12-43-50](https://cloud.githubusercontent.com/assets/6921696/8634168/67dbf510-27ee-11e5-83f3-772f74e3efef.png)
![screenshot_2015-07-10-12-44-04](https://cloud.githubusercontent.com/assets/6921696/8634169/67dd2318-27ee-11e5-84c1-415ab7d72e08.png)

Found with OsmAnd+ 2.1.1.

**Comment by sonora** [comment]
Norbert, true, our default for both settings is "empty", and it correctly functions as "no limitation". Only the selection menus do not pick this up correctly. Not a functional issue, more a small UI glitch... we may have more of these, I think I saw this on some other menus, too, after a fresh app install when a setting has not yet been initialized.  - Best, Hardy
