### ISSUE TITLE
Incorrect routing web

### ISSUE THREAD

**Issue by alisa911** [osmandapp/OsmAnd#14539]
https://maptile.osmand.net/map?start=60.056046%2C30.417487&end=60.055194%2C30.420440&mode=pedestrian#19/60.05580/30.41782
![2022-06-14 14 41 19](https://user-images.githubusercontent.com/38911173/173569051-2749b87c-c49c-41da-b96a-a12a864f7ea5.jpg)

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-tools/pull/487

**Comment by vshcherb** [comment]
Merged - https://github.com/osmandapp/OsmAnd/issues/14499
