### ISSUE TITLE
What does the Grade in the elevation widget actually display and can it be enhanced

### ISSUE THREAD

**Issue by Loki-Afro** [osmandapp/OsmAnd#14543]
### Description
Currently the elevation widget display Uphill, Downhill and Grade. Uphill and Downhill are understandable but Grade is really not.

Based on the code i would think it is supposed to display the max gradient, but things on my phone look different (screenshot attached)

### How to reproduce?
Enable elevation widget and navigate using a gpx track in a mountainous area

### Your Environment
OsmAnd Version: 4.1.11
Android/iOS version: Android 11
Device model: Fairphone

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
Sachsen-Anhalt, Germany up to date, no live updates enabled

![Screenshot_20220612-112317](https://user-images.githubusercontent.com/4738445/173689544-5028f59c-157d-4ad5-9ff9-cebdf04505fd.png)

Suggestion: just display the average of the current grade back and force from the current position? to smooth things out? 
What is the benefit of having over the next 10 km (per default) the average grade(seems like it behaves like that?)

I can also provide the gpx track if necessary

**Comment by tradavyvy** [comment]
Possibly linked to #14441

**Comment by vshcherb** [comment]
It's not average, it's maximum (https://docs.osmand.net/docs/user/widgets/nav-widgets#whats-in) as it is mentioned in docs
