### ISSUE TITLE
Bus stop rendered name is random value from [name, operator, line]

### ISSUE THREAD

**Issue by IIVQ** [osmandapp/OsmAnd#14540]
### Description
Bus stops (public_transport=platform, both way and node) in the Public Transport view (or any view with bus routes enabled) display either
- The bus line's operator (for one of the lines stopping at that stop)
- The bus line number (for one of the lines stopping at that stop)
- The bus stop name
- The stop_area name

### How to reproduce?
Osmand, world view, with configure maps -> transport -> "Bus, Trolleybus, Shuttle routes" enabled
Go to a bus stop/bus station, e.g. [Amsterdam Bijlmer ArenA](https://www.openstreetmap.org/search?query=Bijlmer%20ArenA#map=19/52.31112/4.94706), pan and zoom. 

### Your Environment
OsmAnd Version: OsmAnd+ 4.1.11 released 2021-12-15
Android/iOS version: Android 12, ColorOS V12.1
Device model: Oppo A74 5G

**Maps used (online or offline):**   
Offline maps, in this case Netherlands North Holland 1 jun 2022, but recurring problem for a few months (or longer)

The examples below are from the "[Amsterdam Bijlmer ArenA](https://www.openstreetmap.org/search?query=Bijlmer%20ArenA#map=19/52.31112/4.94706)" bus and train station. All public_transport=platform _nodes_ have the name "Station Bijlmer ArenA", all _ways_ have the name "Amsterdam Bijlmer ArenA" (I need to fix that discrepancy, but whatever). They are all member of a stop_area name "Amsterdam Bijlmer ArenA". Everything is tagged according to PTv2.

![Screenshot_2022-06-13-20-13-34-69_014aeb6b5e04ee7837dcdaecc5244511](https://user-images.githubusercontent.com/14251459/173576390-87790b33-89b5-4361-8561-400c622bf574.jpg)
The platform nodes, from top to bottom show 
- operator (Connexxion)
- node name (Station Bijlmer ArenA)
- line number (356)
- nothing (even though multiple lines stop here)
- line number (N85)
- operator (Connexxion)
- node name (Station Bijlmer ArenA)
- line number (49)
- nothing (even though multiple lines stop here, two of which are shown on the platform _way_
- operator (Syntus)

![Screenshot_2022-06-13-20-14-00-23_014aeb6b5e04ee7837dcdaecc5244511](https://user-images.githubusercontent.com/14251459/173576398-376f6374-c7f7-4b44-8d6b-c8cf640cbf5e.jpg)
The same view, but zoomed in a bit. More platform ways show a name of either the stop or the operator ("Keolis Nederland"), and the platform nodes show different data from the previous view

These are views from a "side station" of Bijlmer ArenA, with a different name ("Hoogoorddreef/Atlas").
The northern platform _way_ and both platform _nodes_ have the name "Hoogoorddreef/Atlas", the southern _way_ has no name. 
All four are member of the stop_area with name "Hoogoorddreef / Atlas"), only the platform _ways_ are member of the larger 
"Amsterdam Bijlmer ArenA" stop area.

![Screenshot_2022-06-14-14-14-37-19_014aeb6b5e04ee7837dcdaecc5244511](https://user-images.githubusercontent.com/14251459/173576411-56996b16-6825-4bf5-be66-a955676952cb.jpg)
The northern node and way take their name.
The southern way takes it's name from both the stop areas. The southern node name is not rendered

![Screenshot_2022-06-14-14-15-22-71_014aeb6b5e04ee7837dcdaecc5244511](https://user-images.githubusercontent.com/14251459/173576418-468f8620-428a-4baa-bc62-88ba61da8dbc.jpg)
The same view, a little shift to the east:
Now the southern platform _way_ takes the name of the lines stopping there

### Expected result
Platform nodes and ways should show their name, not the line numbers and certainly not the operators of the lines stopping there (in the Netherlands, bus stops are usually not maintained by bus line operators but by the road operator)

Alternatively, individual bus stops in a larger station should display their ref or loc_ref platform letter/number, or both (for example, with the platform number in parentheses)

**Comment by Nine-Tailed** [comment]
Perhaps the [problems](https://github.com/osmandapp/OsmAnd/issues/12292) are related.

**Comment by IIVQ** [comment]
As a sidenote: bus stops that do only have a platform _way_, no node, have their name not rendered in zooms where the way is shorter than the name.

**Comment by xmd5a2** [comment]
Not reproducible in nightly build
![изображение](https://user-images.githubusercontent.com/5829014/174732768-74e62980-5133-42f5-9f16-08310f0ad6ff.png)
