### ISSUE TITLE
Adding the place of departure of public transport to the total number of stops of public transport (OpenGL) and iOS too

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#14544]
### Description
Adding the place of departure of public transport to the total number of stops of public transport
https://osmand.net/map/?start=50.438136%2C30.420274&end=50.441460%2C30.433255&pin=50.436561%2C30.505503&mode=car#16/50.4396/30.4278

### Steps to reproduce
Select point of departure 50.43814, 30.42027 -> Set destination -> 50.44146, 30.43326 -> Select Public transport profile -> Press Detail button

### Actual result
Adding the place of departure of public transport
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/173788304-bcfbd9ae-1cdc-4a90-9d19-525309b9153f.jpeg "  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
The number of stops of public transport is counted without boarding stops

### Your Environment
OsmAnd Version:  4.3.0#13577mqta, released: 2022-06-15
Android/iOS version: Android 11
Device model:  POCO X3 NFC

**Comment by Skalii** [comment]
[Fix Public Transport - number of stops](https://github.com/osmandapp/OsmAnd-iOS/pull/2035)

**Comment by nazar-kutz** [comment]
**Fix in Android**
https://github.com/osmandapp/OsmAnd/pull/14601
