### ISSUE TITLE
Research institute polygon has no color.

### ISSUE THREAD

**Issue by BikeRoad** [osmandapp/OsmAnd#14556]
Hi.
![Screenshot_2022-06-16](https://user-images.githubusercontent.com/19896035/174073397-39a35165-4e00-4bfa-8cae-9621ae32334b.jpg)
I suggest using the same color as the keytag amenity=university

I also suggest closing the thread I opened about keytag research_institute
[Add support for leisure=research_institute](https://github.com/osmandapp/OsmAnd/issues/9136)

Thank you.

**Comment by xmd5a2** [comment]
![Screenshot_2022-06-20_09-48-09](https://user-images.githubusercontent.com/5829014/174541642-abf3ba4b-2148-43d6-ae81-3b8cd56bba55.png)
