### ISSUE TITLE
IMBA MTB trail difficulty rating colours in OsmAnd don't match those defined by IMBA

### ISSUE THREAD

**Issue by tomeckip** [osmandapp/OsmAnd#14552]
### Discussed in https://github.com/osmandapp/OsmAnd/discussions/12404

<div type='discussions-op-text'>

<sup>Originally posted by **c0nsumer** August  6, 2021</sup>
I do a great deal of mapping of mountain bike trails in OSM and OsmAnd is outstanding for mobile, offline navigation when in remote areas. When the _Show mountain bike trails_ option in _Routes_ is toggled, I can see that MTB routes are getting highlighted, but I'm having a hard time understanding the rules by which these are colored and seem to have relations highlighted.

Can someone either explain this, or point me to where in the code this is defined? I've tried searching through the code myself, but I'm having a hard time finding this.

My goals here are to both ensure that the trails I've been mapping are tagged appropriately, and perhaps work on OsmAnd to get the MTB route highlighting as useful as that in CyclOSM, mtb.waymarkedtrails.org, etc.

As an example, the routes that are part of [superroute 12425503](https://www.openstreetmap.org/relation/12425503) are colored in OsmAnd a way that doesn't quite make sense. A specific example, [way 610004303](https://www.openstreetmap.org/way/610004303#map=18/46.49664/-87.64433) has no difficulty designation ([mtb:scale:imba](https://wiki.openstreetmap.org/wiki/Key:mtb:scale:imba)) but it's part of [relation 8468010](https://www.openstreetmap.org/relation/8468010#map=16/46.4987/-87.6452) which is designated mtb:scale:imba=2 or blue square. In OsmAnd this is currently shown as a red line on the map which would _normally_ designate a Double-Black-Diamond trail.

Thanks for any pointers you can give, I'd really like to contribute to this however I can, but am lost finding where this is defined in the code. Thanks!</div>

**Comment by xmd5a2** [comment]
Will work with august maps and later
![изображение](https://user-images.githubusercontent.com/5829014/177730329-31818e8b-f1da-406e-aac5-3b86d71f9931.png)

**Comment by michaelblyons** [comment]
Any interest in adding a 1.5 with the 🟢 superimposed on the 🟦?
