### ISSUE TITLE
[Feature] Dark Menus with Light Map

### ISSUE THREAD

**Issue by seniorm0ment** [osmandapp/OsmAnd#14550]
Requesting the ability to set menus as dark theme, but the map itself as light

**Comment by seniorm0ment** [comment]
Looking back, it looks like this might be a bug. The app requires a restart for it to apply to the menus.

**Comment by vshcherb** [comment]
It should be possible with Dark Theme and Map Mode - day. These are 2 independent settings.

**Comment by firefoxlover** [comment]
This is default behavior on OSMAnd? I think it should be optional though, as not many want a light map but dark menu I suppose. So opt-in for seperate color schemes, otherwise follow OSMand color scheme (which itself follows the system)

#15902

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/3384
