### ISSUE TITLE
A pink line appears on the map when you activate Terrain Slope (OpenGL) and iOS too

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#14558]
### Description
A pink line appears on the map when you activate Terrain Slope (Germany (Slopes) maps)
from 53.42619° N, 10.00044° E  to  53.68116° N, 10.00004° E

### Steps to reproduce
Configure map -> Terrain -> Slope -> turn on -> Transparency = 100%

### Actual result
A pink line appears on the map
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/174082289-8ca3c7bf-c2f4-465c-9aa0-667bdb58d23d.jpeg "width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
The map is displayed without the pink line

### Your Environment
OsmAnd Version: 4.3.0#13579mqta, released: 2022-06-16
Android/iOS version: Android 11
Device model: POCO X3 NFC

**Comment by xmd5a2** [comment]
Dev note:
```
/home/xmd5a/utilites/OsmAndMapCreator-main/utilities.sh split-hillshade-into-regions \
/mnt/wd_2tb/hillshade_script/slopes.sqlitedb /mnt/wd_2tb/hillshade_script/slopes_regions \
 --prefix=Slope_ --maxzoom=12 --filter=germany

xmd5a@xmd5a-desktop /mnt/wd_2tb/hillshade_script $ ./split_hillshade.sh 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at net.osmand.util.SplitHillshadeIntoRegions.main(SplitHillshadeIntoRegions.java:41)
	at net.osmand.MainUtilities.main(MainUtilities.java:172)
./split_hillshade.sh: строка 4: /mnt/wd_2tb/hillshade_script/slopes.sqlitedb: Отказано в доступе
```
Unable to split slopes

**Comment by xmd5a2** [comment]
Fixed
Old tile:
![old](https://user-images.githubusercontent.com/5829014/181694000-22f2850e-2a1e-42b5-afac-e75bfc6c9900.png)

New tile:
![new](https://user-images.githubusercontent.com/5829014/181694006-ec1294a4-8164-4aad-9bd9-58bf831fb592.png)
