### ISSUE TITLE
OsmAnd renders mtba:scale:imba colour only if mtb:scale tag is also present. 

### ISSUE THREAD

**Issue by tomeckip** [osmandapp/OsmAnd#14554]
### Description

Routes are not colour coded by mtb:imba:scale if a mtb:scale tag is not present. In certain areas the imba scale is used more commonly and mtb:scale tags are not defined. These trails are not getting colour coded on the maps.

Looking around in topo.render.xml, it looks like maybe the trails with only the mtb:scale:imba tag, but no mtb:scale tag are not getting indexed as "route_mtb", so they get missed by the renderer. 

### How to reproduce?

Almost all the MTB trails in North Vancouver and Squamish have mtb:imba:scale tags assigned in OSM, but only a few show up colour coded on the maps. The ones that do show up also have the mtb:scale tag defined. 

### Your Environment
OsmAnd Version: 4.1.11
Android/iOS version: Android 12
Device model: Pixel 6 pro

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
Offline maps - Canada - British Columbia - Metro Vancouver Regional District

**Comment by xmd5a2** [comment]
@tomeckip Can you provide some links to such routes?

**Comment by tomeckip** [comment]
Sure, here are a few MTB trails located in the same are in Squamish:

Routes that get colour coded in OsmAnd according to mtb:imba:scale (also have mtb:scale tags): 
https://www.openstreetmap.org/way/297468385
https://www.openstreetmap.org/way/74660826
https://www.openstreetmap.org/way/366858010
https://www.openstreetmap.org/way/366858012
https://www.openstreetmap.org/way/108800273
https://www.openstreetmap.org/way/504649763
https://www.openstreetmap.org/way/297468122

Routes that don't get colour coded - only have mtb:imba:scale tags:
https://www.openstreetmap.org/way/109262293
https://www.openstreetmap.org/way/802042081
https://www.openstreetmap.org/way/109263733
https://www.openstreetmap.org/way/366874293
https://www.openstreetmap.org/way/109263735
