### ISSUE TITLE
Route engine bug (car, fastest)

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#1455]
Please compare the screen shots of MapQuest and OsmAnd+ 2.1.1. You can see that OsmAnd calculates an  unnecessary loop (2.2 km instead of 590m).

(You can see the start and destination coordinates in the MapQuest screen shot to reproduce the bug in OsmAnd.)

![mapquest](https://cloud.githubusercontent.com/assets/6921696/8635155/e494b628-2816-11e5-91ca-c38361bdd62a.png)
![osmand 211](https://cloud.githubusercontent.com/assets/6921696/8635154/e4915f46-2816-11e5-8bdb-808839c164f6.png)

**Comment by Norbert80** [comment]
Strange is that MapFactor Navigator Free calculates the same loop as OsmAnd while MapQuest OSRM and GraphHopper* calculate correctly.
* https://graphhopper.com/maps/?point=43.84671%2C10.49589&point=43.84703%2C10.49513&locale=de&layer=Lyrk

![screenshot_2015-07-12-20-16-14](https://cloud.githubusercontent.com/assets/6921696/8639227/95764daa-28d3-11e5-939b-5d01b965272c.png)

**Comment by Norbert80** [comment]
Note that the bug only occurs with car, fastest. Car, shortest works. Please also note that the "loop" needs more time than the shortest route. That's why this behaviour has to be considered a bug.

**Comment by aceman444** [comment]
It's probably due to the penalties when switching from a high class road (e.g. primary) to lower class road (like residential). With the penalty, the longer route but keeping on the primary road is determined "faster" (=less penalties) by OsmAnd. This is another case where the penalties cause problems. I think it was already proposed in the forums to ignore this type of penalties for short routes as it produces pathological routes.

**Comment by Goodingn** [comment]
Is this related?
https://github.com/osmandapp/Osmand/issues/1468

**Comment by aceman444** [comment]
Maybe, you can try editing the routing.xml file and remove the section <way attribute="penalty_transition"> ... </way> . Restart OsmAnd fully and try the routes again.

**Comment by vshcherb** [comment]
This is not a routing engine bug, but a configuration issue:
The long route generates:
complete_distance = "2446.8499" complete_time = "341.8831" routing_time = "286.02844"  >
The short route generates (with transit point):
 complete_distance = "750.79114" complete_time = "103.83869" routing_time = "109.0685"  > (+penalty transition +200)
So technically it is correct 286 < 309

https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#L205  (transition is configurable, but we don't want to change it cause it can break other cases). I will keep this case as reference for unit tests. Unfortunately I don't see a fix now, unless somebody will change the road in between to tertiary or change primary -> secondary (that will also eliminates the issue).

**Comment by aceman444** [comment]
Victor, why can't the transition penalty only be applied to longer routes, e.g. above 10km? That was already proposed in the forum and it seems it could make both camps happy.

**Comment by Norbert80** [comment]
This would not fix the situation. The route was longer than 10 km as I found the problem. Only for demonstration and reproduction I have set a start near to the end.

**Comment by vshcherb** [comment]
To be honest if we would be all in same country, I think that check would not be needed. As a traveller, as I mostly use it, I found out that in some countries it is much safer (!) and faster to drive primary / secondary ... roads and not deviate to living street or residential, that was fixed for some logical issue even!

Of course we have tags for smoothness, but they are not tagged often. Knowing the OSM in different places, I would say that a reasonable route just looking on the map. For people who know better area this might be not acceptable. The routing time penalty is only 100 seconds, so the optimal route is not 100 seconds faster. 

I will open it to recap on it in couple of weeks, may be will find a solution. I also think that solving another issue could affect this one in a better way

**Comment by vshcherb** [comment]
Technically routing is correct
cause long route produces routing_time = "408.5157" and short route  routing_time = "418.62598".

To workaround that issue I would recommend to downgrade priority of http://www.openstreetmap.org/way/162698836 to secondary or even tertiary it doesn't seem so important road from the map and this would fix weird routing.

OsmAnd in contrast of other routing systems relies on primary/secondary network a lot and this could be changed in https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#L197 but that will make other routes much slower.

**Comment by aceman444** [comment]
Victor, as already proposed multiple times, could those transition penalties be considered only for longer routes (e.g. above 10km)? Then everybody would be happy.

**Comment by vshcherb** [comment]
That's possible but again it requires testing what will be the difference. Testing could be done without any changes to the code. My biggest concern that we will get inconsistent routes by just moving starting point around threshold. This is quite bad experience. On the other hand we could see how many issues like this we have, if we don't have them many, then I wouldn't go for a change in the core.

**Comment by Norbert80** [comment]
I also think that it would be a very bad experience to have different common route parts by variation of the start point.

That's why I am against such distance depending tricks. There are also already bug reports cause users experience different common route parts on slight modifications of the starting point. ("Bidirectional meeting bug".)

**Comment by aceman444** [comment]
I can understand Victor, that the penalties are necessary for long routes and to keep on main roads due to incompletely mapped roads. If all lower grade roads in cities (like, residential, service) were properly mapped with speed calming bumps, traffix signals, give way signs and maxspeeds, these penalties would probably not be needed as the other road attributes would keep the car on the main roads.

But the penalties are too high for such short routes as in the report and produce unexpectedly longer and slower routes. So either they need to be ignored or, there could be an option "prefer main roads" as there is "prefer motorways" now. Only with that option the penalties would be used.

Norbert so what do you propose as a solution?

**Comment by Norbert80** [comment]
@aceman444

Let's wait some weeks... @vshcherb announced that there are chances that he will find a solution:
"I will open it to recap on it in couple of weeks, may be will find a solution. I also think that solving another issue could affect this one in a better way"

In general distance depending variation in routing algorithm that lead to different results should be avoided.

If the bug fix announed by victor will not solve this issue my idea is as follows:

- Implement an alternative routing method - let's call it "OsmAnd 3 routing" for example
- This method does not apply "transition penalties"
- This method is default turned off and can be set active by devloper plugin

So the beta testers can test it over months. Depending on the results victor could decide to implement it default for a future version 3 release (perhaps with option fall back to "OsmAnd 2 routing" over developer plugin" for the 3.1.x period.

Maybe chances are that quility of OSM data increases and there is decreasing need for "transition penalties".

(It is interesting that MapFactor has the same routing result. Maybe they have no better solution, too.)
