### ISSUE TITLE
disabling interrupt music broken

### ISSUE THREAD

**Issue by ggrseat** [osmandapp/Osmand#1456]
If checked or unchecked interrupt music always interrupts music with bluetooth connection (v2.1.1).
This used to work pre v2.

Thanks

**Comment by sonora** [comment]
I have never seen this work, (at least I never see the music continuing to play with lower volume). Maybe this is Adroid-system, i.e. device specific?

**Comment by sonora** [comment]
Looks device-specific, I think our OsmAnd code is correct according to Android specification.
