### ISSUE TITLE
No GPS in nighlty

### ISSUE THREAD

**Issue by thackel** [osmandapp/OsmAnd#14561]
The latest nightly does not allow to use GPS.
Permissions are OK, other Apps on the device have no problem to obtain GPS position.
GPS status shows perfect amount of satellites and has a fix.
The nightly before (i guess 2-3.months ago) worked perfect on the device.
No OS upgrade since then.

### Your Environment
OsmAnd Version: nightly 2022-06-16 and 15
Android/iOS version: ArrowOS Android 11 with PlayServices
Device model: Poco X3

**Comment by pebogufi** [comment]
No problem with #34212 2022-06-15 Android 8.0, Samsung S7

**Comment by vshcherb** [comment]
Probably installation is corrupted and reinstall is needed

**Comment by thackel** [comment]
You are always very quick closing issues...

The removal of the application and keeping of the app data does not solve the problem.

Using the backup functionality does not work because it after the phase of preparation and a long time of of no visual update the share dialog opens. This dialog does not show any local file option (only drive etc). So its not possible to save the data and maps in a local backup.

I am adding a screenshot of the dialog when there is no progress on export before the share dialog opens.
![Screenshot_20220616-195530.png](https://user-images.githubusercontent.com/1008148/174140158-d061dd72-02a1-42c6-9099-2713df0a6ac4.png)

**Comment by thackel** [comment]
The installation of an older OSM nightly is also not possible (i still have about 15 older nightly apks). 
So downgrading to an older version is not an option...

**Comment by thackel** [comment]
I reinstalled the nightly and removed all the data.

Still no GPS.

There is just a toastlike message, see the attached screenshot.

![Screenshot_20220617-090024.png](https://user-images.githubusercontent.com/1008148/174243755-08234a58-2b6f-4610-87c7-da0ae0396978.png)

Please consider reopening this issue and provide information how to debug this problem.

For now I will try to install the latest F-Droid version...

**Comment by thackel** [comment]
The F-Droid version 4.1.11 has no problem to get the GPS position.
So I think it is a problem with the nightly...

**Comment by vshcherb** [comment]
Closing issue determines the status but it doesn't mean that it wouldn't be reopen once we figure out what's the problem. But so far could not reproduce

**Comment by twitwi** [comment]
I found this issue while searching so I'm cross referencing a solution
https://github.com/osmandapp/OsmAnd/issues/13157#issuecomment-2119004493
summary: there is an option to select the location source (with google service or not)

**Comment by thackel** [comment]
I can not reproduce it anymore when using 4.8.4 from F-Droid
