### ISSUE TITLE
"crosswalk" sounds like "crosswick"

### ISSUE THREAD

**Issue by ggrseat** [osmandapp/Osmand#1457]
"crosswalk" sounds like "crosswick" in spoken english "pedestrian crosswalk" warning.
In non US countries would probably be called a "pedestrian crossing".

**Comment by sonora** [comment]
I agree with your comment about US and other versions of English. As long as we do not have the time and resources to maintain various versions of English (this affects our strings as well as our voice prompts), I have tried to mostly keep it consistent in US English. I am aware this does not suit all, but it would later be easier to split into different versions of English than if we worked with a mixed "middle of the road approach" here ...  :-)

Regarding "how things sound": This entirely depends on the TTS engine you use, i.e. on the Android version and often also device manufacturer if you use built-in TTS. You may want to try to update your google tts engine (if you use that), or try some of the add-on TTS engines out there (check google Play for both), some users report they produce much better results.

I think issues like this should not be fiddled with in OsmAnd, the effects any specific pronunciation fix in OsmAnd would have on the different TTS versions are unpredictable.

**Comment by GabrielSebastianMoise** [comment]
Where can I translate the string for Romanian ?!?!  Do you have announcements for other tags like railway=crossing  , hazard=curve ?!?!?!

**Comment by sonora** [comment]
In this file:
https://github.com/osmandapp/OsmAnd-resources/blob/master/voice/ro/ttsconfig.p
Please compare with other "neighboring" files of different languages like
en or de, it is not trivial to work with the files, please test thoroughly
before committing anything. You can always create a folder like "ro2-tts"
in your OsmAnd/voice data structure on your device, rename your modified
ttsconfig.p to _ttsconfig.p, Put it in there and select it in OsmAnd to
test it.

**Comment by GabrielSebastianMoise** [comment]
Ok, I'll do that ! Thanks !

2015-07-13 21:29 GMT+03:00 Hardy <notifications@github.com>:

> In this file:
>
> https://github.com/osmandapp/OsmAnd-resources/blob/master/voice/ro/ttsconfig.p
> Please compare with other "neighboring" files of different languages like
> en or de, it is not trivial to work with the files, please test thoroughly
> before committing anything. You can always create a folder like "ro2-tts"
> in your OsmAnd/voice data structure on your device, rename your modified
> ttsconfig.p to _ttsconfig.p, Put it in there and select it in OsmAnd to
> test it.
>
> On Sun, Jul 12, 2015 at 10:32 AM, GabrielSebastianMoise <
> notifications@github.com> wrote:
>
> > Where can I translate the string for Romanian ?!?! Do you have
> > announcements for other tags like railway=crossing , hazard=curve ?!?!?!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/osmandapp/Osmand/issues/1457#issuecomment-120701180
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osmandapp/Osmand/issues/1457#issuecomment-121016192>.
>



-- 
Toate cele bune !
*------------------------*
Gabriel Sebastian  Moise
Administrator Local - Departament Tehnic
*------------------------------------------------------*
NextGen Communications S.R.L. - Campina

Mobil NextGen  : 076 111 65 59
Mobil Personal : 0726 311 957

Adresa Postala: Strada Grivitei, Nr.63, Campina, Romania !
*------------------------------------------------------*

**Comment by sonora** [comment]
I see no action here until we finally muster enough resources to maintain en-US and en-GB separately.

**Comment by sonora** [comment]
I had recently implemented region support in our Locales, and I di now provide an "English (United Kingdom)" version of our
- Display language
- TTS voice

2 notes:
- For the display language strings.xml and phrases.xml files: Please note that they must only contain strings where British spelling or wording is different! All others are taken from the default (American) en files
- For the tts-voice: It uses British wording, but a British accent does of course have to be set in the device's TTS-engine  :-)

Best,
Hardy
