### ISSUE TITLE
Opengl: osmand doesn't hide waypoints

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#14578]
### Description
After pressing the hide waypoints button, they are still displayed on the screen. Bug only in opengl.
![Screenshot_2022-06-19-02-31-40-700_net.osmand.plus.jpg](https://user-images.githubusercontent.com/12549744/174460692-9a8bd216-016e-4ff8-a279-e6ab8143c3f4.jpg)

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#34227m, Дата выпуска: 2022-06-18
Android version: 12
Device model: poco f3

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd/pull/14625

**Comment by Nine-Tailed** [comment]
https://github.com/osmandapp/OsmAnd/issues/14628

**Comment by Nine-Tailed** [comment]
The problem has not been resolved.
OsmAnd~ 4.3.0#13619mqta, Дата выпуска: 2022-07-01

https://user-images.githubusercontent.com/12549744/176866372-6fd4e713-adc6-4671-9c8b-282416a7fc58.mp4

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/commit/972a3273a7f4367078a5ce6d71ee021e95b68d13
