### ISSUE TITLE
The village of Saint-Lys does not appear in the search (address -> city/town) (Open GL)

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#14570]
### Description
The village of Saint-Lys does not appear in the search (address -> city/town), in the search (history) you can find the village, but it is displayed in the middle of the list, even if the center of the map is opposite the village

https://osmand.net/map/?pin=50.436561%2C30.505503#14/43.5149/1.1920

### Steps to reproduce
Search -> Address -> First specify.. -> type Saint-Lys

### Actual result
The village of Saint-Lys does not appear in the search

### Expected result
The village of Saint-Lys is displayed in the search

### Your Environment
OsmAnd Version: 4.3.0#13581 mqta, released: 2022-06-17
Android/iOS version: Android 11
Device model: POCO X3 NFC

**Comment by vshcherb** [comment]
It appears in the search but only 38 and only as POI not as address entity.

<img width="727" alt="Screen Shot 2022-06-18 at 12 24 13" src="https://user-images.githubusercontent.com/1042025/174433647-a3f1b48d-1947-475e-a61b-a39a7602542c.png">

**Comment by vshcherb** [comment]
The whole list is undervalue saint-lys pois by unknown reason even it's a perfect match

**Comment by dmpr0** [comment]
Seems the same for https://www.openstreetmap.org/node/301015385#map=14/38.4850/22.4487

**Comment by Zirochkabila** [comment]
### Description
The city of Hawkinsville does not show up in searches

### Steps to reproduce
Search > Hawkinsville

### Actual result
The city doesn't display in the search 
[RPReplay_Final1657184447.MP4.zip](https://github.com/osmandapp/OsmAnd/files/9062042/RPReplay_Final1657184447.MP4.zip)


### Expected result
The city is displayed in the search 

### Your Environment
OsmAnd Version: 4.2.2
Android/iOS version: iOS 15.5
Device model: iPad mini 4

**Comment by nnngrach** [comment]
PR 1

**Comment by nnngrach** [comment]
PR 2 / 2

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-tools/pull/527/files

**Comment by alisa911** [comment]
tests https://github.com/osmandapp/OsmAnd-resources/pull/854
generation https://github.com/osmandapp/OsmAnd-tools/pull/527/files
search java https://github.com/osmandapp/OsmAnd/pull/15530

**Comment by alisa911** [comment]
ios https://github.com/osmandapp/OsmAnd-iOS/pull/2253

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.3.0#13892mqta, released: 2022-10-22
[Hawkinsville](https://www.openstreetmap.org/relation/119681#map=17/32.28389/-83.47178) is displayed in the middle of the search list


https://user-images.githubusercontent.com/104760013/197348023-de4a1d6f-637c-477c-9f5b-bfc17a20c421.mp4

**Comment by alisa911** [comment]
@Zirochkabila Current fix didn't fix result order. It fixed adding the necessary phrases to the result. You can open tests and see it. Order of phrases in the search result will be fixed in https://github.com/osmandapp/OsmAnd/issues/13797
You can add the example to this task and i will check it after the future fix.

**Comment by dmpr0** [comment]
TestFlight 4.3.0.22
<table style="width:100%">
  <tr>
    <th>"saint-lys"</th>
    <th>"saint"</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/197525512-5b2ca39c-80bc-4511-ac0b-612dac832508.jpeg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/197525516-c1646d8b-e7cc-4660-8aa9-cd29f64fb38b.jpeg"  width="300" height="auto"/> </td>
  </tr>
</table>
