### ISSUE TITLE
My position icon is not animated

### ISSUE THREAD

**Issue by efi99** [osmandapp/OsmAnd#14582]
### Description
Although "Animate own position" is enabled, moving the "My position" icon is not continuous, but only jumps every second.
However, rendering and moving the map appears to be continuous.

### How to reproduce?
Enable "Animate own position" and navigate.

### Your Environment
OsmAnd Version: 4.2.4
Android/iOS version:  Android 12
Device model: Samsung A52 5G

**Maps used (online or offline):**  offline (Hungary, OSMAnd Live) 
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by dead10ck** [comment]
I am having this issue as well on a OnePlus 9 Pro, Android 12

**Comment by vshcherb** [comment]
Fixed
