### ISSUE TITLE
Very frequent crashes when zooming in after update to 4.2.4

### ISSUE THREAD

**Issue by Famlam** [osmandapp/OsmAnd#14586]
### Description
Very frequently, when I double tab the screen (or press the `+` button) to zoom in, OsmAnd closes (i.e. the app crashes).
Unfortunately, nothing is written in the crash report... This is new since the update to 4.2.4 (yesterday)

### How to reproduce?
1. Double tab the screen (or press `+`) to zoom in on the map. At the end of the usual rendering period (after half a second or so) the app suddenly closes
(If relevant, the last crash occurred when I tried to zoom in on Nijmegen, The Netherlands, from zoom level 13 to 14)

### Your Environment
OsmAnd Version: 4.2.4
Android/iOS version: Android 11
Device model: LG K61

**Maps used (online or offline):**   
- Offline map of Gelderland, The Netherlands (live updates)
- Offline map of Noord Brabant, The Netherlands (live updates)

**Comment by Famlam** [comment]
@vshcherb thank you for your reply! I must say that I unfortunately ended up on a location (in Nijmegen) such that it crashes on startup, so I'm unable to do any debugging at the moment. Please see the video. However, by memory I have enabled road maps of: Vlaanderen (Belgium), Zuid-Holland, Utrecht, Groningen and Drenthe

https://user-images.githubusercontent.com/1315520/174884034-07aaca76-9a24-40c1-9c96-4b25dc7344c4.mp4

Any suggestions on how I might be able to provide any information on what happens during this time?

**Comment by vshcherb** [comment]
Sorry to hear that. We hope to provide a build with this fix this week (we're working on testing all scenarios to find it), you could meanwhile use nightly or free version if you don't to reinstall the app and save the data in the app.

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-core-legacy/commit/f5a2ca1033e72f0882aefba4671f86cc0ff78beb
