### ISSUE TITLE
Incorrect route construction

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#14587]
### Description
Incorrect route construction
https://osmand.net/map/?start=44.815317%2C6.736314&end=44.819016%2C6.734726&pin=50.436561%2C30.505503&mode=car#close

https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=44.81533%2C6.73651%3B44.81962%2C6.73496

### Steps to reproduce
Select point of departure 44.81532, 6.73631 -> Set destination 44.81902, 6.73473 -> Start

### Actual result
Incorrect route construction

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/174625604-6b29a58f-1fd7-422a-8732-cad44268e935.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
The route is built on the road

<img width="564" alt="Screenshot 2022-06-20 at 17 38 01" src="https://user-images.githubusercontent.com/104760013/174626285-73dd2f90-6bcf-4795-8637-a6b868c7a5dc.png">

### Your Environment
OsmAnd Version: 4.2.4, released: 2022-06-15
Android/iOS version: Android 11
Device model: POCO X3 NFC

**Comment by Nine-Tailed** [comment]
access:conditional=no @ (Oct-Jun) - need to check in 10 days ;)
Graphhopper doesn't route either, and OSRM doesn't seem to take access:conditional into account.
It would be good if osmand would let the user know that the route is not possible.
