### ISSUE TITLE
Voice prompts are in Ukrainian, although English is selected

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#14585]
### Description
Voice prompts are in Ukrainian when the user turns onto Volodymyrska street, although English is selected
https://osmand.net/map/?start=50.446205%2C30.512080&end=50.448460%2C30.517273&pin=50.436561%2C30.505503&mode=car#16/50.4457/30.5132

### Steps to reproduce
Select point of departure 50.44620, 30.51208 ->  Set destination 50.44846, 30.51727 -> Voice prompts -> English -> Start

### Actual result
Voice prompts are in Ukrainian

https://user-images.githubusercontent.com/104760013/174619426-568b8f7a-012f-4ecb-9bcf-37c5d5a73b01.mp4

### Expected result
Voice prompts are in English language

### Your Environment
OsmAnd Version: 4.2.4, released: 2022-06-15
Android/iOS version: Android 11
Device model: POCO X3 NFC

**Comment by vshcherb** [comment]
No bug works as expected

**Comment by vshcherb** [comment]
Voice prompts in english as I hear "Turn left..."

**Comment by Zirochkabila** [comment]
It's pronounced "Володимирська вулиця", not "Volodymyrska street".

**Comment by vshcherb** [comment]
That's expected you need to change Map Language then to have other street names

**Comment by Zirochkabila** [comment]
Yes, you're right
