### ISSUE TITLE
USA: Incorrect route due to turn restrictions

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#14589]
### Description
Incorrect construction of the route because of the incorrectly formed relationship between the roads

route https://osmand.net/map/?start=43.667154%2C-79.587343&end=43.665501%2C-79.588115&pin=50.436561%2C30.505503&mode=car#18/43.66650/-79.58773

first relation https://www.openstreetmap.org/relation/9960346 and incorrect rout https://osmand.net/map/?start=43.667154%2C-79.587343&end=43.665501%2C-79.588115&pin=50.436561%2C30.505503&mode=car#18/43.66650/-79.58773 

second incorrect relation https://www.openstreetmap.org/relation/6629382 (incorrect because in restriction specified only straight on) and incorrect rout https://osmand.net/map/?start=43.666801%2C-79.587434&end=43.665501%2C-79.588115&pin=50.436561%2C30.505503&mode=car#19/43.66640/-79.58745
### Steps to reproduce
Select start point 43.66715, -79.58734 -> Set destination 43.66550, -79.58812 -> Start

### Actual result
Incorrect route construction
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/174637649-7852dc55-1834-4365-9a2d-0a8215ec5fda.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
The route is straight
<img width="1435" alt="Screenshot 2022-06-20 at 18 24 16" src="https://user-images.githubusercontent.com/104760013/174638277-3095fc35-8388-4fcb-9a5a-bb482d1e09d8.png">
<img width="1435" alt="Screenshot 2022-06-20 at 18 27 35" src="https://user-images.githubusercontent.com/104760013/174638313-d1890f22-287e-456d-9c05-ad60978908e8.png">

In the red circles, the direction arrows go straight ahead

### Your Environment
OsmAnd Version: 4.2.4, released: 2022-06-15
Android/iOS version: Android 11
Device model: POCO X3 NFC

**Comment by alisa911** [comment]
Hi! We can only handle restrictions if "from" and "to" belong to the same intersection. This is due to the algorithm doesn't currently support via node, and we do not know for which intersection this restriction is.

**Comment by alisa911** [comment]
The map was fixed.
