### ISSUE TITLE
Spoken road references in UK

### ISSUE THREAD

**Issue by PinkDuck** [osmandapp/Osmand#1459]
In virtually all cases, only A and B class road references are signed in the UK. OsmAnd text-to-speech currently reads out C-road references (possibly U-road references too) set in highway ref tags before the road name, which is unhelpful extra information when driving. Could an exception rule be written to not speak the road references for UK roads where the ref tag begins "C", "D", or "U" please?

**Comment by fred702** [comment]
Improving OSM data is always preferable to making exceptions in software applications. [This](https://wiki.openstreetmap.org/wiki/United_Kingdom_Tagging_Guidelines#Tagging_Road_Numbers) seems to be the common practice.

**Comment by PinkDuck** [comment]
Perhaps a better global modification would be to not state the reference by voice when a signed:ref=no or ref:signed=no tag is present? I'm quite happy to add that to the ways with ref that aren't physically signed, which will preserve the render presentation and search capability too.

Similarly perhaps a modification for when unsigned=yes, or name:signed=no or signed:name=no is set?

I note in the US there are a lot of unsigned_ref too. At present Nominatim does not index any of the keys admin_ref, official_ref, unsigned_ref. In my case there is no other reference for the roads, so official_ref wouldn't be right. I have created an issue with Nominatim to try to get them to support these additional keys for location look-up.

**Comment by fred702** [comment]
>the ways with ref that aren't physically signed

I'm not in the UK, but my reading of the [wiki](https://wiki.openstreetmap.org/wiki/United_Kingdom_Tagging_Guidelines#Tagging_Road_Numbers) is that the ref=* tag is only used for ways that are physically signed. If OSM data has a ref tag for the roads you mentioned and they aren't signposted, they probably shouldn't have a ref tag. Before making changes though it's best to do a survey yourself if possible and/or consult the local mapping community or contact the editor who added the tag in the first place.

**Comment by PinkDuck** [comment]
Wiki aside, I think if the road has an official reference (and no other) with suitable licence that it's still a valid reference and for informational terms having it stored is a good thing. I think the core of this issue is about OsmAnd currently speaking road references that aren't seen by the user. I added the tags originally and know that all are physically unsigned.

**Comment by sonora** [comment]
I am afraid this is more an issue of ref usage in different countries and mapping habits in different countries, I see no overall way to improve things much in OsmAnd without worsening things elsewhere.

**Comment by PinkDuck** [comment]
This became less of an issue for me after I rename the official and unsigned tertiary tags from reg=* to official_ref=*

**Comment by sonora** [comment]
Yes, I think this exactly is the way to go here.
