### ISSUE TITLE
Map rendering is cluttered by natural=hot_spring display.

### ISSUE THREAD

**Issue by laurentriffard** [osmandapp/OsmAnd#14594]
### Description
At certain levels of zoow, map rendering is cluttered by natural=hot_spring display.

### How to reproduce?

For example, go to Casablanca, Morocco.
Example of hot spring node on OSM : https://www.openstreetmap.org/node/9773426158 

With a strong enough zoom, hot springs are displayed like other POIs. This behaviour is OK.

![image](https://user-images.githubusercontent.com/25233732/174742068-4745f548-00a6-419f-9913-3bcb5a7ae368.png)

But when you zoom out, most of the POIs disappear, and the sources remain. This is unexpected, the hot sources should also disappear.

![image](https://user-images.githubusercontent.com/25233732/174742226-e5c8521b-9f61-42c8-9894-bbb578afab66.png)

### Your Environment
OsmAnd Version: OsmAnd~ 4.1.11 from F-Droid
Android/iOS version: Android 11 (Miui Global 12.0.2)
Device model: Redmi Note 8T

**Maps used (online or offline):**   

Offline map : Morocco

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/306ed41627c25de98d29bf05134b2cba2fe6cfbe
