### ISSUE TITLE
Avoid toll roads only in certain countries

### ISSUE THREAD

**Issue by DaimonPl** [osmandapp/Osmand#1460]
Currently there's option to avoid toll roads in true/false switch. It would be nice to have default option + custom option for each country.

Use cases (when routing):
- disabling toll roads for all countries except those for which we've already payed (some countries have country-wide single payment which is valid for longer amount of time)
- enabling toll roads for all countries except those which we don't explicitely want (for example there's no point to pay 1 week toll fee if our route only uses 40km in certain country - real world example is route from Poland to Croatia through Slovenia)

**Comment by Hedaja** [comment]
This would be a nice feature.

**Comment by aceman444** [comment]
Sure, this would be great. There are many options that would benefit from a per-country setting (e.g. maxspeed on some road types). But there is no such infrastructure in OsmAnd yet.

**Comment by sonora** [comment]
No action planned here, I guess.
