### ISSUE TITLE
The names of public transport stops are placed too close

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#14602]
### Description
The strings of names of public transport stops are placed close to each other 
48.79937° N, 9.17166° E

https://osmand.net/map/?pin=48.799474%2C9.171427#19/48.79950/9.17179

### Steps to reproduce
Configure map > Public transport

### Actual result
The strings of names of public transport stops are placed close to each other
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/174829222-7dcb925f-cef7-4bb7-8835-d37258a42305.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
The strings of the names of public transport stops are indented

### Your Environment
OsmAnd Version: 4.2.4, released: 2022-06-15
Android/iOS version: Android 11
Device model: POCO X3 NFC

**Comment by Dima-1** [comment]
Fix with https://github.com/osmandapp/OsmAnd/issues/14243#issuecomment-1185249644
