### ISSUE TITLE
Some text appearance messed up in latest nightly

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#14607]
See here, comparison of 2022-06-09 vs. 2022-06-21:
![Screenshot_20220621-192530_OsmAnd~](https://user-images.githubusercontent.com/845735/174861759-855bd340-f264-47bf-b39f-e724684d1c4d.jpg)

![Screenshot_20220621-193211_OsmAnd~](https://user-images.githubusercontent.com/845735/174862017-a978e129-5324-4d68-96cd-d2bb69d782f9.jpg)

**Comment by vshcherb** [comment]
Also I think we need to trim seconds cause it gives illusion of non-updateable time.

**Comment by dmpr0** [comment]
Could you please provide more details about the issue?

**Comment by dmpr0** [comment]
> Also I think we need to trim seconds cause it gives illusion of non-updateable time.

Without seconds it will be updated?

**Comment by sonora** [comment]
Doesn't the mix of light and dark gray still look weird??

![Screenshot_20220623-012531_OsmAnd~](https://user-images.githubusercontent.com/845735/175174693-9224bb0d-7a6f-44d3-8527-77a6f1731156.jpg)
