### ISSUE TITLE
display increments of time or distance in the Track for better planning possibilitys

### ISSUE THREAD

**Issue by peterelli** [osmandapp/OsmAnd#14612]
Feature Request

When i am navigating with a loaded Track from a GPX File i would like the possibility to display increments of time or distance in the Track. This way you can estimate the time for the next break or the km for the next fuel stop.

And the same Idea can be applied to the Navigation line  which is calculatet in OSMand.

Maybe this was a feature in the past, but actually i cant find no more.

Kind regards
Peter

**Comment by dmpr0** [comment]
Hi!
If I understand you correctly. You can try to use **Split interval** for tracks, open the track context menu – appearance – split interval.

**Comment by peterelli** [comment]
When you aktivate a Track via "Configure Map" then there is no possibility to configure the split interval in the appearance menue.  Why?
Thank You
