### ISSUE TITLE
Regression in routing takes straight line at random? points directly to the destination

### ISSUE THREAD

**Issue by mdykierek** [osmandapp/OsmAnd#14613]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Car. Default settings

### Start and end points

Multiple (probably any) starting points to multiple (any) destination.
It seems that the route has to be re-calculated during navigation for the issue to appear. It is quite common (e.g. setting navigation at a car park and taking wrong starting direction)

### Actual and expected routes

Follow routable roads. Taking straight line severely affects time estimation.

### Is this a regression?

It is a regression. It worked fine in 4.1.11

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>
Device : raphael
Brand : Xiaomi
Model : Mi 9T Pro
Product : raphael_eea
Build : RKQ1.200826.002 test-keys
Version : 11
App Version : OsmAnd
Apk Version : 4.2.4

</code></pre>

**Device and Android/iOS version:**

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.
I am using Poland Silesia area maps with Live updates (hourly) for OSM Editors. Will check if latest "stock" monthly maps have the same issue.
- [ ] Online (tile / raster) maps 

**Anything else relevant?**
Following are screenshots of 2 different variants of shortcuts taken from Katowice to Ruda Śląska ul. Solidarności 15 during the same ride to make the route re-calculation
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/27214784/174971142-44c60fbf-6950-44eb-8bfe-b0e3cb509681.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/27214784/174971194-3bd1f622-0467-4623-866a-342ed27ab836.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/27214784/174971380-058bb503-e250-411c-8413-2af6db71874a.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/27214784/174971415-768088e5-702b-4b91-990f-a3d448475413.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/27214784/174971465-a3272749-ee94-4adf-b172-d4cc25670830.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  
.

**Comment by mdykierek** [comment]
I have confirmed. It occurs for offline monthly maps too.
The easiest way to reproduce is to:
- Disable GPS
- Make a starting point nearby
- Enable GPS it will force route re-calculation and make error appear.

**Comment by mdykierek** [comment]
Just to give an example how bad it can affect time/distance estimates I am attaching another example. Note the time/distance difference between wrong and right route.
Another DANGEROUS thing is that the guidance sticks to the unfortunate shortcut route and the voice prompt tells to take a nonexistent road.
My guess is that it can also lead to taking a suboptimal route since it has to start another re-calculation when the driver responds to the fake route.
![right](https://user-images.githubusercontent.com/27214784/175135866-8e17243b-d911-4d93-8189-ae5a197c3a79.jpg)
![wrong](https://user-images.githubusercontent.com/27214784/175135921-ed03fb6f-a2ba-41d8-bf1d-5f1fffd08f53.jpg)

**Comment by Zirochkabila** [comment]
Your case was tested with OsmAnd app version 4.2.4 - it could not be reproduced (as seen in the video)
Try reinstalling the app, but before doing so, backup your data: Menu > Settings > Backup & Restore
If the error repeats - send us a short video where we can see how you play the case.


https://user-images.githubusercontent.com/104760013/175319260-79fddb34-a2fa-4dab-8298-58f8a4a8f762.mp4

**Comment by mdykierek** [comment]
The scenario is not what I described. 
1. The navigation is CAR. 
2. The route has to be re-calculated "automatically" e.g. by taking wrong direction or enabling the GPS location after route is computed.
3. The route gets fixed by reversing the direction twice or any other manual route re-calculation (does not occur with simulation).
4. Since I don't know how to make a video, I put a few images with description below.
5. I will re-install, since my colleague did not reproduce the error.
a) Compute route with GPS disabled and starting point a bit off your current location:
![route_calculated_ok](https://user-images.githubusercontent.com/27214784/175323459-627d2b65-3e42-4e4c-b49d-433b94688cfe.jpg)
b) This results in a correct route:
![correct_route](https://user-images.githubusercontent.com/27214784/175323541-716edfb2-9c6f-467f-939d-5f1ac53bbb77.jpg)
c) Enable GPS, so that the route has to be re-calculated:
![recalculated_due_to_GPS](https://user-images.githubusercontent.com/27214784/175323739-a2b9ab5a-57cf-483f-8144-5d240b095063.j
![off_highway](https://user-images.githubusercontent.com/27214784/175326225-74664b4b-d928-4838-8cd9-c076bd6e9ea3.jpg)
pg)

**Comment by mdykierek** [comment]
I dropped my settings. Installed OsmAnd from scratch (took 4.2.5 available now in the Play Store), downloaded Silesia maps again and the issue persists - no change whatsoever. I checked Bicycle profile and it does not seem to be affected (or not that easy to reproduce).

**Comment by mdykierek** [comment]
I have a video and another example of troubled routing (takes the opposite direction despite a quite simple, obvious and previously 4.1.11 route).

https://user-images.githubusercontent.com/27214784/175366659-eec78ab5-514b-41db-b4cb-df1423175f37.mp4

And when I was on the way the following proposal showed up instead of taking Bracka directly to A4:
![wrong_way](https://user-images.githubusercontent.com/27214784/175367286-67d2d983-89e8-4bed-8d5f-373bd29e53c9.jpg)

**Comment by Zirochkabila** [comment]
I was able to reproduce it in the following way: Select point of departure 53.45290, 9.98039 > Set destination 53.07340, 8.81790 > Option > Simulate navigation > Fast preview mode > Start

https://osmand.net/map/?start=53.452896%2C9.980392&end=53.073402%2C8.817902&pin=48.799474%2C9.171427&mode=car#10/53.2262/9.3878

In a minute the route will be rerouted and a direct line to the destination will appear

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/175502244-60fd990e-ee86-4be0-b74a-4f59f27b8a01.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
Fixed

**Comment by alisa911** [comment]
c++ https://github.com/osmandapp/OsmAnd-core-legacy/pull/98

**Comment by mdykierek** [comment]
I still have same symptoms with 4.2.7. Will this be reopen or shoul I file a new report?
![Screenshot_2022-08-08-12-27-29-873_net osmand](https://user-images.githubusercontent.com/27214784/184312743-34d18e2f-053b-46b8-be8c-6b493d24cd83.jpg)
![Screenshot_2022-08-08-13-49-21-473_net osmand](https://user-images.githubusercontent.com/27214784/184312751-3dcd9465-ac56-4446-bf62-342fa9f0b746.jpg)
![Screenshot_2022-08-12-10-17-24-747_net osmand](https://user-images.githubusercontent.com/27214784/184312756-aa5ac11c-bf3a-4d5f-bcee-7059a373a7ae.jpg)

**Comment by Zirochkabila** [comment]
As you can see in the added video - reproduction is failed.

Please clarify:
1. The device you use, OS version
2. Application version
3. Route, start and finish coordinates 
4. The presence of traffic restrictions
5. Logcat file: Menu > Help > Send logcat log

https://user-images.githubusercontent.com/104760013/184328909-ab22d5b4-d274-49e4-9b6d-71f2f0755c35.mp4

**Comment by mdykierek** [comment]
Anatoli,   I am trying to provide as much and as exact QA data I can. I do know how developers hate irreproducible stuff. I am in the software business for over 20 years - from quality assurance, through support, technical marketing to product management.  Please review the entire thread for the report. It is not trivial and though it is less frequent, I am getting the straight line shortcuts quite consistently now (doing some 6000 km in Scandinavia).  It is not a single start-end case. It is not as bad as it was (the shortcuts are shorter, but still odd). Had another one just today.  The environment has not changed, same phone, same Android 11, only OsmAnd updated to 4.2.7.  I am going to report 2 more bugs. One for odd routing, the other for wrong ETA.   
            
          
     
      
       
        Dnia 12 sierpnia 2022 11:43 Anatolii ***@***.***&gt; napisał(a):
       
    
       
         
 As you can see in the added video - reproduction is failed. 
 Please clarify: 
 
 The device you use, OS version 
 Application version 
 Route, start and finish coordinates 
 The presence of traffic restrictions 
 Logcat file: Menu &gt; Help &gt; Send logcat log 
 
 user-images.githubusercontent.com https://user-images.githubusercontent.com/104760013/184328909-ab22d5b4-d274-49e4-9b6d-71f2f0755c35.mp4

**Comment by vshcherb** [comment]
This issue was closed in 4.2 and couldn't be reopen due to dev process, so please create a new issue (actually I saw something similar already in 4.3) and put a link to this issue.
