### ISSUE TITLE
No sound initialization on app start ( osmand + latest oficial version)

### ISSUE THREAD

**Issue by razor74** [osmandapp/Osmand#1461]
I have problems with sound. When i start the app, and load a route- when start navigation , i hear no voice announcements.
But if i force close the app and reopen, go to settings - general settings - voice guidance and select the voice , a message with voice initialising apear and after that if a load again the route , the voice works until i close the app again... When start again the app - load a new route again - no voice...
I must do those steps ( anoing) every time when i want to use the app...

I use Ivona.

**Comment by sonora** [comment]
I am just guessing, but maybe check all your TTS (IVONA) settings, to see if everything is correctly configured and initialized. To better localize the issue, it may also be worth to temporarily fall back to your device's default tts engine (google, Samsung, whatever) to see if this has an impact on the issue?

**Comment by razor74** [comment]
Ivona works perfect. Works on other apps. The problem apeared from 2.0 version. Like i said - if i force close the osmand and restart, reload the voice from settings and after that load again the route, the voice works again.
I will try with pico tts to...

**Comment by GabrielSebastianMoise** [comment]
I never had that issue from 2.0 !  It's weird.... Maybe it's a problem on
some Android versions ?  Output channel  that has been changed from 4.0,
4.1, 4.2, 4.3, 4.4.x and 5.x ?  Maybe another app that is accessing the
same resources for sound output like  OsmAnd does, or another app that
check for power consumption or memory usage and take action if some values
are met  ?

In recovery , Hard reset , after Android config. install only the OsmAnd
and Ivonna Text-to-Speech ?!?!

2015-07-13 23:45 GMT+03:00 razor74 <notifications@github.com>:

> Ivona works perfect. Works on other apps. The problem apeared from 2.0
> version. Like i said - if i force close the osmand and restart, reload the
> voice from settings and after that load again the route, the voice works
> again.
> I will try with pico tts to...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osmandapp/Osmand/issues/1461#issuecomment-121052444>.
>



-- 
Toate cele bune !
*------------------------*
Gabriel Sebastian  Moise
Administrator Local - Departament Tehnic
*------------------------------------------------------*
NextGen Communications S.R.L. - Campina

Mobil NextGen  : 076 111 65 59
Mobil Personal : 0726 311 957

Adresa Postala: Strada Grivitei, Nr.63, Campina, Romania !
*------------------------------------------------------*

**Comment by sonora** [comment]
I have tested many of our builds on most of these Android versions, and never saw the issue. Like other people and me suggested, please revert to the basics first to try localize the issue: Remove all Bluetooth audio devices, put up all volume levels, revert to some more standard tts engines, and check if the issue still appears, then take it from there. It will be rather hard to debug this unless we can pinpoint the conditions under which this is reproducible.

**Comment by razor74** [comment]
Yes, you have right. It was from the ivona - probably the last update from google play. I uninstalled, deleted data and cache and reinstalled. Now the sound it is initialised correctly every time when start navigating with osmand. You can close the topic.
