### ISSUE TITLE
Can't hide Favorite Group

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#14628]
### Description
in favourites group the 3-point-menu does not work any more

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#34266m, veröffentlicht: 2022-06-22
Android version: 8
Device model: Samsung S7

**Comment by pebogufi** [comment]
After install of older nightly, then for trying how to reproduce again the 34266, no more problem...
Sorry for inconvenience ...

**Comment by pebogufi** [comment]
No more reproducable

**Comment by pebogufi** [comment]
.

**Comment by pebogufi** [comment]
.

**Comment by Nine-Tailed** [comment]
> Couldn't reproduce actually. Any screenshot or what does it mean "does not work" menu

Виктор, есть другая проблема - выключенные группы избранных точек после перезапуска османд отображаются как включенные, иконка группы перестает быть серой и порядок отображения в списке тоже нарушается, выключенные группы ранее шли в самом низу списка.
Обратите в видео внимание на группу Алтай 2020 которую я выключил, она посерела и опустилась вниз списка. После перезапуска османд она снова на первом месте в списке, что интересно избранные точки внутри группы выключены и имеют серый цвет. А выключатель группы включён.
Видео в телеграмм:
https://t.me/ruosmand/101633

**Comment by vshcherb** [comment]
Probably related https://github.com/osmandapp/OsmAnd/pull/14625

**Comment by vshcherb** [comment]
No it's not related
