### ISSUE TITLE
It is possible to "backup" the World base map

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#1463]
If you go into the map files manager, it is possible to "backup" the World base map so that it becomes inactive. This causes OsmAnd to display black map, even for areas where a country specific map was downloaded. So if the World base map is crucial to operation (like OsmAnd tries to say by forcing it to be downloaded and updated when needed), maybe the option to back it up should not be available for this particular file? Or are there use cases where that is needed?

**Comment by sonora** [comment]
At least for testing it is nice to have the deactivate functionality, to debug overlaps we have between base and detail maps, etc. I do not think many users have an issue with it, if you accidentally de-activate it, you will be prompted to re-download it anyway ...

**Comment by vshcherb** [comment]
>> This causes OsmAnd to display black map, even for areas where a country specific map was downloaded. 

This is an interesting comment. Is it real black, does it happen after restart? Please provide more info or screenshot

**Comment by aceman444** [comment]
Sorry, I wanted to say "blank (empty) map". But I can't reproduce it now. The map does render in the countries where I have a specific map downloaded. It may have been a temporary fluke. OsmAnd sometimes takes some seconds to just draw something so I may have thought it will no longer draw anything and I prematurely went back to map management. So I take that claim back for now. Sorry.

As there are potential uses for disabling the base map as sonora says, I am fine with closing this issue.

**Comment by vshcherb** [comment]
Well we have quite many issues that go after restart, and quite a lot of issues that hard to reproduce. I hope we will catch them all, for now I think we can keep it for history.
