### ISSUE TITLE
The application loads a bicycle or pedestrian route too long

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#14634]
### Description
The application hangs when selecting a bicycle or pedestrian profile
[OsmAnd bug (1).zip](https://github.com/osmandapp/OsmAnd/files/8968209/OsmAnd.bug.1.zip)

### Steps to reproduce
Select pedestrian profile

### Actual result
The application hangs

### Expected result
The application still working

### Your Environment
OsmAnd Version: 4.2.4

**Comment by vshcherb** [comment]
We need to introduce cancel mechanism to cancel loading

**Comment by nicbou** [comment]
@Chumva , just to be clear, does this fix the following issue? The original ticket is not very clear.

1. Click on a node or bicycle route.
2. The route menu open (in case there are multiple routes).
3. Click on a route.
4. The loading popup shows, but nothing happens. The back button does not work, so the app must be killed.

**Comment by vshcherb** [comment]
it's going to be fixed in another way tomorrow

**Comment by vshcherb** [comment]
We've introduced cancel dialog on popup, so now it's possible to cancel if loading goes too long.

**Comment by vshcherb** [comment]
Please let us know which route did you try, so we can try and see if it's a bug or not

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/pull/14654
