### ISSUE TITLE
[Feature] Search tracks by words

### ISSUE THREAD

**Issue by pmontrasio** [osmandapp/OsmAnd#14640]
### Description

Search tracks by typing words that match against the name of the track.

### Describe the solution you'd like

After a few years of use I have more than 130 gpx files on my phone and it's becoming difficult to find a given track.
The only way to do it now is to scroll through the list of all tracks but it's easy to miss the one I'm looking for.
A search filter on the top of the dialog would be best, much like Search in the POI dialog.
Any word typed in should match the name of the track. I believe than an OR search would be better than an AND one because sometimes I don't remember if I named a track with the start, finish or an intermediate location.

### Describe alternatives you've considered

Currently I try to remember if the track I'm looking for is in the rec or import folder on the phone. That helps a little.
I could use some naming convention but there is no way AFAIK to rename a track from inside the app. I just checked that I can still do it from the Android file manager (unrooted Android 11) though I believed that the app folder became inaccessible months ago after the update from Android 10 to 11. The files are inside Android/data/net.osmand.app/
Anyway, renaming in a consistent way helps a little but search would be best.

**Comment by scaidermern** [comment]
> However taking myself as a data point and all the years it took me to discover this (basic?) functionality, the UX is not very good. I expected seach for tracks to belong to the tracks dialog, as search for POI type belongs to the POI dialog.

There is a search icon in the top right corner at My places / Tracks.

**Comment by pmontrasio** [comment]
I never noticed that. Actually I seldom opened My Places. There are really many menus in OSMAnd and few of them seemed to be relevant to my use case (download maps, place markers, record tracks, share tracks to my other devices).
