### ISSUE TITLE
4.2.4 Delete all maps on sw update is back

### ISSUE THREAD

**Issue by wefranke** [osmandapp/OsmAnd#14643]
### Description
After updating OsmAnd to the new version 4.2.4, all maps were deleted again.
This problem already exist in a older version, but updating to the previous version, the problem was solved. Now it's back.
I use as storage location: Multiuser-store 1
/storage/emulated/0/Android/obb/net.osmand.plus

On my tablet (Galaxy Tab Active 3, Android 12) I had not seen this behavior.
Storage manually specified:
/storage/emulated/0/Android/media/net.osmand.plus

### Your Environment
OsmAnd Version: update to 4.2.4
Android/iOS version: 12
Device model: Samsung Galaxy M31

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by scaidermern** [comment]
This is a known problem when multiuser storage is selected. See #13404.
