### ISSUE TITLE
Back into POI changes list returns to start of the list

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#1464]
When you go into the "View all" of your stored POI changes, then scroll down and choose a change to "show on map". That works fine. However when I click the back button of the phone, I am properly put back into the list of POI changes, but not at the position I started from (at the chosen POI). But it is always at the start of the list. That is uncomfortable when managing and checking POI changes.

**Comment by vshcherb** [comment]
Updated, Please test it.

**Comment by aceman444** [comment]
Seems to work in nightly. Thanks.
