### ISSUE TITLE
Probably we need always to display compass if map is rotated

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#14649]
Probably we need always to display compass if map is rotated. Since now it's possible to disable compass on/off we can end up with situation map is rotated and compass is not visible which is bad for geo orientation.

One of the possible outcome is to hide Compass from settings and get back to previous behavior.

## Review
- [x]  **Compass** word is missing at **Configure Screen** > **Buttons** card.
- [x] Bottom sheet should be closed after one of the option is selected
- [x] Compass state is not saved after back to application or app restart (also it should be preserved with app profile change?)

**Comment by vshcherb** [comment]
Make 3 options:
- Always On
- Hide when North is up [default]
- Always Hide

**Comment by sonora** [comment]
Related: When you now tap the compass to cycle through the 4 states, there are now two called "No rotation (north always upwards)", but that's only true for one of them. The other one is a manuallly rotated one, if applicable.
