### ISSUE TITLE
Rendering missing for some objects

### ISSUE THREAD

**Issue by demonbox73** [osmandapp/OsmAnd#14657]
Hi, excuse me, I would only report to you these tags that actually are not rendered:

building=roof (polygon)
building=tent / marquee (polygon)
building=static_roulotte (polygon / node)
military=bunker (polygon / node)
pipeline=marker (node)
advertising=billboard (node)

Would it kindly be possible to render all of theme with any related icon of your choice?
Thanks very  very much!
--enrico

**Comment by vshcherb** [comment]
Roof is rendered for the objects as normal building, yes there is no planning to change it. You can always create your own rendering style, it is may be a better option

**Comment by demonbox73** [comment]
Hi **vshcherb** at least the tags with a higher numerical consistency is not a future inclusion in the rendering really planned?

https://taginfo.openstreetmap.org/tags/building=roof
1 526 459 numerical consistency

https://taginfo.openstreetmap.org/tags/building=static_caravan
303 961 numerical consistency

https://taginfo.openstreetmap.org/tags/military=bunker
67 929 numerical consistency

https://taginfo.openstreetmap.org/tags/pipeline=marker
32 972 numerical consistency

https://taginfo.openstreetmap.org/tags/advertising=billboard
62 426 numerical consistency

THANKS 

--enrico

**Comment by vshcherb** [comment]
I've tested building=roof is rendered, so why should we add it ?

**Comment by demonbox73** [comment]
...these tags

military=bunker
pipeline=marker
advertising=billboard
building=static_caravan

actually are not rendered at all... In my opinion are important informations that at the moment remain transparent ghosts...

What do you thing?

THANKS AGAIN

--enrico

**Comment by xmd5a2** [comment]
Added some of tags you mentioned. Half of them was already rendered.
`pipeline=marker` is deprecated
`advertising=billboard` will not be added for now. May be someday.
