### ISSUE TITLE
All hiking route names displayed on map

### ISSUE THREAD

**Issue by vmicho** [osmandapp/OsmAnd#14658]
### Description
Since last upgrade, there are some places on map that shown text of all hiking routes (cycling routes seem to be OK, found similar places but no error), centered on roundabouts:

![Screenshot_20220625-114604_OsmAnd+](https://user-images.githubusercontent.com/66125746/175773291-ed7cc6dc-0280-4118-912b-011e1b35e137.png)

![Screenshot_20220625-114726_OsmAnd+](https://user-images.githubusercontent.com/66125746/175773293-71dcdff2-d125-49cb-9a58-e95ffff7aab1.png)

Does not matter if Hiking Routes are shown on map, those labels are always visible.
I've checked in OSM, this happen when the hiking (not cycle, not bus ...) route includes a roundabout (maybe works also on any closed path). All routes are separated by commas in the label.
I did not check if this happen when the circle is split into multiple segments.

here are the coords of the two above screenshots:

geo:46.78594,7.14908
https://www.openstreetmap.org/?mlat=46.78594&mlon=7.14908#map=19/46.78594/7.14908

geo:46.79180,7.16047
https://www.openstreetmap.org/?mlat=46.79180&mlon=7.16047#map=19/46.79180/7.16047

### How to reproduce?
Always visible on certain zoom levels / map position

### Your Environment
OsmAnd Version: osmand+ 4.2.4 2022-06-15
Android/iOS version: 11
Device model: mi8

**Maps used (online or offline):**   
offline + live update for this region

**Comment by vmicho** [comment]
Hi. Nope. Map is up to date and I also removed live updates. Still same.

**Comment by vmicho** [comment]
Found another roundabout with one hiking route over it:
https://www.openstreetmap.org/?mlat=52.16361&mlon=9.79581#map=19/52.16361/9.79581

checking osmand, and does the same :
![Screenshot_20220701-002656_OsmAnd+](https://user-images.githubusercontent.com/66125746/176789087-9c5a1531-4121-4577-97f8-3797373324d0.png)

**Comment by vmicho** [comment]
Why is this closed already?
Still happend in lastest 4.2.7 from 2022-07-13

**Comment by vshcherb** [comment]
Please check 4.3 https://download.osmand.net/latest-night-build/OsmAnd-default.apk, this commit might went to 4.3 build.

**Comment by vmicho** [comment]
oh, will have to wait till an update appears, still not in play store :D

**Comment by vmicho** [comment]
OK
4.3.5 works fine, no more labels.
