### ISSUE TITLE
Critical: Map screen does not display when GPS is turned off

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#1465]
I had reported this already here https://github.com/osmandapp/Osmand/commit/5fc6cd7610877e404689f94cd0eca82a7014d00c, and now have more details:

Starting with our nightlies of July 7 and later, on any device, in Android settings disable GPS (Location). The map screen (offline vector maps) will not fully render anymore by itself, after app startup, a zoom operation, etc.. It may partly render, then freeze. If you wait long enough (a few seconds, so the map can get rendered in the background), then touch the map and pan it a little, the map will immediately get fully displayed. So somehow we are missing a final map refresh in newer builds (after the memory leak fix, I guess). Builds of July 6 and earlier did not have this issue. If GPS is enabled, the issue will also not show up. (This is independent of a fix, GPS just has to be enabled.)

**Comment by stephan75** [comment]
I can fully confirm with nightly.apk from 17.07.2015!

especially when dragging the map with one finger. And indeed it depends on whether you have GPS set onn or off in your device: it only happens when turned off!!!

**Comment by sonora** [comment]
PS: It looks like this is partially dependent on which device you use (maybe on the device's available RAM), it seems it reliably happens on all devices for a map area which contains many details (like viewing a "crowded" area at an intermediate zoom like 12-14), while on other devices (particularly large-screen devices) it happens all the time, on all zoom levels, In any case, it only started happening with July 7 and after builds.

**Comment by vshcherb** [comment]
Fixed

**Comment by sonora** [comment]
Yes, confirmed working, thanks, Victor!
