### ISSUE TITLE
When a map is disabled, it's POIs won't disappear. +screenshot +workaround

### ISSUE THREAD

**Issue by enomat** [osmandapp/Osmand#1466]
If I disable a map, it's POIs won't disappear.

Steps to reproduce:

1. Use a map
2. Enable some POIs (in my example food POI)
3. Disable the map

Now you will see that the POIs of that map didn't disappear.

4 . Enable another map that has POIs
5 . Disable (untick) POIs
6 . Enable the same POIs again (in my example food POI)

Now you will see that the POIs of the same objets are duplicated.

![screenshot_2015-06-28-11-46-10](https://cloud.githubusercontent.com/assets/12612250/8395953/a30fd656-1d8f-11e5-81e4-4bdc2cf20555.JPG)

It's annoying because I use multiple different maps of my country, and when I disable a map and enable another, the POIs from the previous map will still be there.

Workaround:
-quit and restart Osmand

**Comment by vshcherb** [comment]
Fixed, disabling map - means step of taking backup in Manage Map Files
