### ISSUE TITLE
Polygons are hidden every time the app is launched

### ISSUE THREAD

**Issue by Lans-K** [osmandapp/OsmAnd#14662]
When the application is restarted, the "show polygons" setting is lost and they are hidden.
Appeared since version 4.2.5
In 4.2.4 there was no such problem.

In the background map setting, the "Show polygons" slider is also turned off at each launch.
The error appears when any background map is enabled.
If there is no background map involved, the bug does not appear.

OsmAnd Version: 4.2.5
Android 6
Samsung

**Comment by Lans-K** [comment]
When you change the screen orientation to landscape mode, the polygons are also turned off each time.

**Comment by Zirochkabila** [comment]
> When 

Your case was tested on version 4.2.5 OsmAnd, POCO X3 NFC Android 11 device - failed to reproduce, polygons do not disappear every time you run the application.

Please describe your actions in more detail and add a short video where we can see the bug

**Comment by Zirochkabila** [comment]
I will check issue #14703 and in the comments to that issue I will give an answer to that case

**Comment by vshcherb** [comment]
Merged to more generic issue https://github.com/osmandapp/OsmAnd/issues/14703

**Comment by Zirochkabila** [comment]
Issue #14703 has been reproduced.
If your case is the same as the one described in the link, please put a "+" in the comments (in the comments of issue #14703)

> OsmAnd Version: 4.2.5 Android 6 Samsung
