### ISSUE TITLE
addr:housenumber displays instead of name

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#1467]
For objects that have a name tag but also address tags (addr:*) in OsmAnd v2.1.1 and the current maps, only the addr:housenumber is displayed below the POI icon. In the past the name of the object was shown. Ideally both would be displayed in some way. But if only one can be shown, was this change intentional?

**Comment by xmd5a2** [comment]
I have not checked this in 2.1.1 but in current nighties building names are rendered as "name housenumber" (space is still a divider. Maybe Victor can fix this?) This feature was not changed after it was introduced. So please check places where this issue happened for you with current nightly.
In theory this can happen when addr:housename is used with for example amenity=college, but IMHO this is bad tagging scheme. Please attach screenshots and give coordinates.

**Comment by aceman444** [comment]
Please do not mix housename and housenumber. Anyway, I have seen it with e.g. shops on nodes or even buildings with "name" and "addr:housenumber". Only the housenumber was used.
Try e.g. way 17506823.
Strangely I can't see the problem on nodes anymore with the new map from 2015-07-14. The report was with a map of 2015-06-26. On nodes the housenumber is shown when zoomed out, when zooming in so that space is available, the name is displayed properly.

**Comment by xmd5a2** [comment]
Way 17506823 doesn't have addr:housenumber tag.

**Comment by aceman444** [comment]
Yeah, it no longer has it as it was wrong. But if you check map of Slovakia from 2015-07-14 that is available in OsmAnd, it still has the housenumber. Or you can try way 38530570 .

**Comment by aceman444** [comment]
I would try a nightly. I looked into http://download.osmand.net/latest-night-build/ . I downloaded the OsmAnd-nightly.apk but it wants to upgrade my existing OsmAnd (release version 2.1.1). So I did not allow that. Which file should I download to test the nightly alongside the stable release?

As to "name housenumber" being displayed in some cases: yes I have seen that with recent maps on some buildings. I like both information to be shown, but please use a better separator than space. E.g. brackets or something.

**Comment by vshcherb** [comment]
If you use OsmAnd+, then install free nightly http://download.osmand.net/latest-night-build/OsmAnd-default.apk

**Comment by aceman444** [comment]
Yes, that seems to be the OsmAnd free version. In that nightly the problem does not appear. The names on the mentioned objects are rendered together with housenumber where available.
