### ISSUE TITLE
Maps loading very slowly

### ISSUE THREAD

**Issue by Ahmadhosseinbor** [osmandapp/OsmAnd#14678]
https://user-images.githubusercontent.com/44550501/175930275-1ff322b2-5761-4c16-a774-fd8b564f7227.mp4

**Your Environment**
OsmAnd Version: 4.2.4
Android/iOS version: 12 (One UI 4.1)
Device model: Galaxy A32

**Maps used (online or offline):**   
Offline

**Comment by vshcherb** [comment]
Please switch to OpenGL (Developer Plugin - Settings)

**Comment by vshcherb** [comment]
You need to restart the app and it should be different i.e. you should see the grid and it's loaded by tiles
