### ISSUE TITLE
The map orientation threshold function doesn't work

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#14681]
### Description
The map orientation threshold function doesn't work

### Steps to reproduce
Select Walking profile 
Menu > Configure profile > Navigation settings > Map during navigation > Map orientation threshold > 7 km/h
Select point of departure > Set destination > walk or options > Simulate navigation > Fixed speed 5 km/h

### Actual result
The map is rotating

### Expected result
The map does not rotate

### Your Environment
OsmAnd Version: 4.2.5
Android/iOS version: Android 11
Device model: POCO X3 NFC

**Comment by vshcherb** [comment]
map orientation threshold is for Compass and not bearing, so simulation is a bad example.

**Comment by Zirochkabila** [comment]
> map orientation threshold is for Compass and not bearing, so simulation is a bad example.

I tried to recreate the situation when walking the route using the aforementioned restrictions - the map still rotates

**Comment by rthrbooks** [comment]
I'm having the same issue in version 4.2.6.The map spins out of control when I come to a stop while navigating.

OS: Android 12
Device: Pixel 6

**Comment by vshcherb** [comment]
Serious Issue: "The map orientation threshold " should affect filtering locating by bearing and shouldn't switch direciton by compass (test with any track and animation simulation).

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/commit/e56417a5215fd0a451211a76e32b6335e81bc0c0

**Comment by vshcherb** [comment]
My comment was wrong: this threshold is needed for Bearing

**Comment by vshcherb** [comment]
This setting affects when "we switch from Bearing rotation to Compass rotation" in Bearing mode. Probably it's not correct cause we're missing important setting "don't rotate for speed < X kmh" important for Bearing mode.

**Comment by vshcherb** [comment]
```
<string name="map_orientation_change_in_accordance_with_speed">Map orientation threshold</string>
<string name="map_orientation_change_in_accordance_with_speed_descr">Select speed of switching orientation from \'Movement direction\' to \'Compass direction\' below.</string>
```

**Comment by Chumva** [comment]
https://github.com/osmandapp/OsmAnd/pull/14824

**Comment by vshcherb** [comment]
UI Location
- Rotate bearing: always use real data bearing or don't rotate if it it's not present
- Location icon: if bearing doesn't exist but snap to road (use previous value). If speed is small small display heading.
- Remove MAP_ORIENTATION_THRESHOLD and settings
