### ISSUE TITLE
Unstable offline routing

### ISSUE THREAD

**Issue by eregwizard** [osmandapp/OsmAnd#14687]
After recent update, when navigating, OSMand starts by calculating an displaying a valid routing. However, at some moment, sometimes in seconds, somtimes while driving, it switches to an invalid routing, where the start and en of the routing a still valid, but a large connecting part is replaced by a straight line. Also, the duration calculation changes to adjust to the thereby reduced distance. Also, calculation takes longer than in previous versions, even freezing while calculating.
When, while driving, reaching the point where routing leaves the valid path part, OSMand corrects and restores to a valid routing and duration.
![Screenshot_20220626-122058](https://user-images.githubusercontent.com/10741961/176024628-e0cd1273-108e-47f7-81a1-0c01bca96004.png)
.

**Comment by pebogufi** [comment]
Same as https://github.com/osmandapp/OsmAnd/issues/14613#event-6873472102 ?

**Comment by vshcherb** [comment]
Indeed looks the same https://github.com/osmandapp/OsmAnd/issues/14613 so please wait for next update.
