### ISSUE TITLE
importing GPX with multiple tracks corrupts app data cache if Currently Recording Track is visible

### ISSUE THREAD

**Issue by heathhome** [osmandapp/OsmAnd#14688]
If you import a GPX file with multiple tracks it causes the "Current recording track in the visibile tracks to disappear and stop working.

When this happens it stops the track being dispalyed while its recording and it cant be turned on.

### How to reproduce?
Goto My Places/Tracks and press "+" to import a GPX file. Select a GPX file that has multiple track files in it and do the import as normal.

Now if in the Visible area in Place/Tracks is showing "Current recording track" it will be replaced by one of the imported tracks. This will make "Show on map" in trip recording to turn off even after its turned on. So you can never see the track recording on the map even knowing its doing it.

### Work Around
To stop the visible current track recording not getting corrupt when importing just make the "Currently recording track" not visible before selecting import.

### Fix 
If you have imported and it stuffed up the  "Currently recording track" visibility, clear the OsmAnd APP cache data and run App again.

### Your Environment
OsmAnd Version: 4.2.6 release 2022-06-22
Android/iOS version: Android 12
Device model: Samsung Galaxy A72

Before Import
![Before Import](https://user-images.githubusercontent.com/108309698/176063841-35518b28-c22f-4b8b-bac4-c006f19dab44.jpg)

After Import
![After Import](https://user-images.githubusercontent.com/108309698/176063836-4ec9c363-ae09-417b-8180-93aa445a7d40.jpg)

**Comment by Zirochkabila** [comment]
Not reproduced
Try updating the application and checking again.
If the situation repeats - please send a short video with all your steps as well as a GPX file
