### ISSUE TITLE
import custom routing xml

### ISSUE THREAD

**Issue by fixifoxy** [osmandapp/OsmAnd#14691]
### Discussed in https://github.com/osmandapp/OsmAnd/discussions/14679

<div type='discussions-op-text'>

<sup>Originally posted by **fixifoxy** June 26, 2022</sup>
I´ve got 3 custom routing profiles in file format .xml.
In the past I  created a new profile based on, 
let say walking profile,  
find the profile folder in Osmands routing folder,
 renamed it  
and copied the custom routing-xml into the folder of the new profile.
Now no  file/folder is shown in the routing folder, even when I create a new profile.
How can I import my custom routing files to use it in profile?

When following the offered Osmand procedure and selecting the xml file under "settings" "import profile" the xml-Format is not accepted. It is asked for OSF-format.

### Your Environment
OsmAnd Version:4.2.5
Android/iOS version:12
Device model:Samsung S21

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
</div>

**Comment by fixifoxy** [comment]
what is the situation:
a general bug handling routing or profile?
a bug in the menue?
low quality in the menu description
or me the user with low knowledge of OSMAND.
But as described w´ve got a situation nice to handle routing.xml.
I think this not a discussion and not nice to have. I need a solution.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/discussions/14679
