### ISSUE TITLE
Opengl: problem with drawing the path in route planning in markers

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#14694]
### Description

The path has flown away
![Screenshot_2022-06-28-14-07-24-386_net.osmand.plus.jpg](https://user-images.githubusercontent.com/12549744/176164669-ef3c10dc-54e5-419a-938e-54572e0fb3bb.jpg)

And video:
https://user-images.githubusercontent.com/12549744/176164744-aecce041-2780-4531-a3a7-9e43c108940b.mp4

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13610mqta, Дата выпуска: 2022-06-28
Android version: 12
Device model: poco f3

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd/pull/14887

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd/pull/14988
