### ISSUE TITLE
Bug: online maps are down with v 2.1.1

### ISSUE THREAD

**Issue by severinmenard** [osmandapp/Osmand#1469]
The online maps are not available in v2.1.1 as the settings almost vanished (only two items remain). See the screenshot below:

![screenshot_2015-07-15-08-15-36](https://cloud.githubusercontent.com/assets/1291055/8693971/c2dfb102-2aca-11e5-891f-e101cc46185e.png)

**Comment by vshcherb** [comment]
We moved these settings to a more convenient place "Configure Map" which is on the screen.
