### ISSUE TITLE
Selecting long hiking route crashes the app

### ISSUE THREAD

**Issue by ERYpTION** [osmandapp/OsmAnd#14698]
### Description
Tapping a long route on the map brings up to 'Loading data...' popup but this does not go away and the app becomes unresponsive and sometimes eventually closes on its own (crashes).

### How to reproduce?
Tapping a very long route. For example The North Sea hiking trail (4500 km), crashes the app every time with a OutOfMemoryError in the log: https://hiking.waymarkedtrails.org/#route?id=1956134&type=relation&map=5.0/55.8501/6.3867

### Your Environment
OsmAnd Version: OsmAnd+ 4.2.4
Android/iOS version: Android 10
Device model: Motorola One Zoom

**Maps used (online or offline):**   
Offroad but happens with other maps as well.

**Comment by sonora** [comment]
Not sure if this should be a separate issue: In addition, there are also "medium long" hiking routes, where, when I tap on them, I receive a brief "Loading data..." pop-up which disappears again after a few seconds, then nothing happens (no crash, but also no context card).

Examples of these are https://www.openstreetmap.org/relation/158952 (175km) or https://www.openstreetmap.org/relation/3762491 (22km).

Not sure if this is really related to the length, maybe we catch some other error when pulling up their cards and then dismiss the operation?

**Comment by scaidermern** [comment]
The crash from the first post could be caused by the same issue as #14295.

**Comment by Dima-1** [comment]
Request [Android](https://github.com/osmandapp/OsmAnd/pull/14906)

**Comment by sonora** [comment]
Recent improvements fixed many issues. The first of my previously failing examples above now works, the second is still broken: https://www.openstreetmap.org/relation/3762491. It's name contains special characters like ":" and "/", potentially an issue with those?

**Comment by Dima-1** [comment]
https://github.com/osmandapp/OsmAnd/commit/18d2455f1e9eed2171d75b84258d1fc74c94bf70

**Comment by Dima-1** [comment]
Here are screenshots for https://www.openstreetmap.org/relation/7323772 and https://www.openstreetmap.org/relation/3762491
<div>
<img width=400px src="https://user-images.githubusercontent.com/31807095/180841222-c31886f1-8b3b-45d0-8f13-b7b15ae1010c.png"> 
<img width=400px src="https://user-images.githubusercontent.com/31807095/180841582-f0890476-2a56-45b5-b650-5d4730779540.png">
</div>

**Comment by sonora** [comment]
Interesting... Maybe it depends on where you tap the route? For both your screenshots it seems like you tapped right on the end point?

Your second screenshot shows we at least have an issue with slashes in the OSM name, the name OsmAnd displays in your second screenshot is truncated up to the occurrence of the "/".

In general I receive user feedback that tapping a route seems unreliable. Do you have to hit one of the route symbols? Taaping just anywhere on  the line (as it works for selecting a track) semms to fail most of the time?

Or is it a timing issue, and you need to wait for something indexing in the background after panning?

**Comment by vshcherb** [comment]
As application shouldn't crash now the original issue considered to be fixed, probably we should continue in other issues to fix completeness of selection.

**Comment by sonora** [comment]
Yes, good idea, see #14936.
