### ISSUE TITLE
The Radius ruler widget does not work

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#14692]
### Description
The Radius ruler widget does not work with the following combination: add to the right widget panel - add to the left panel - delete from the right panel. And vice versa

### Steps to reproduce
Menu > Configure screen > Right panel > Edit > add Radius ruler > Apply > Left panel > Edit > add Radius ruler > Apply > Right panel > Edit > delete Radius ruler > Apply > check Radius ruler widget 

And vice versa

### Actual result
The Radius ruler widget does not work

https://user-images.githubusercontent.com/104760013/176141141-b5f358d5-2262-47ac-af11-45212fc86408.mp4

### Expected result
The Radius ruler widget are working

### Your Environment
OsmAnd Version: 4.2.5
Android/iOS version: Android 11
Device model: POCO X3 NFC

**Comment by nazar-kutz** [comment]
**Pull Request**
https://github.com/osmandapp/OsmAnd/pull/14730

**Comment by nazar-kutz** [comment]
https://github.com/osmandapp/OsmAnd/pull/14755
