### ISSUE TITLE
Opengl: analysis on the map does not show a point on the track

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#14706]
![Screenshot_2022-06-29-13-35-55-076_net.osmand.plus.jpg](https://user-images.githubusercontent.com/12549744/176416695-db8dae7f-caf4-491a-b2ff-36660f06cf36.jpg)

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13612mqta, Дата выпуска: 2022-06-28
Android version: 12
Device model: poco f3

**Comment by alex-osm** [comment]
@Nine-Tailed Could you please provide gpx track? We can't reproduce the issue.
