### ISSUE TITLE
When using Open GL rendering and activating polygons, the map is displayed in black

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#14707]
### Description
When using Open GL rendering and activating polygons, the map is displayed in black

### Steps to reproduce
Menu > Plugins > OsmAnd development > Settings > Use Open GL rendering > Restart the application > Configure map > Hide > Polygons > OK

### Actual result
The map is displayed in black

https://user-images.githubusercontent.com/104760013/176446144-166c005c-dcb9-41ce-99fb-2ccda263dda4.mp4

### Expected result
The map is displayed in the default color

### Your Environment
OsmAnd Version: 4.2.5, released: 2022-06-22
Android/iOS version: Android 11
Device model: POCO X3 NFC

**Comment by Andrewschenko** [comment]
Fixed:
[https://github.com/osmandapp/OsmAnd-core/pull/362](url)

**Comment by Andrewschenko** [comment]
Fixed

**Comment by vshcherb** [comment]
We need to also retrieve proper color from Style (day / night)
