### ISSUE TITLE
Adding all categories of POIs is not possible with OSMAnd 2

### ISSUE THREAD

**Issue by severinmenard** [osmandapp/Osmand#1470]
this possibility was very useful when creating new POIs, to be sure they do not already exist in OSM.
Many categories are also missing, in comparison with v 1.9

**Comment by vshcherb** [comment]
We are adding them continuously, but now with translations. In 1.9 we used a different raw source, without translations.

**Comment by severinmenard** [comment]
is the good location to help with translations? 
https://www.transifex.com/projects/p/osmand/translate

**Comment by vshcherb** [comment]
translate.osmand.net is right one

**Comment by cepesko** [comment]
When I activate the POI layer and select the top option, in English sth. like "POIs around me" or "POIs in my vincinity" all POIs are displayed, just like opting for all POIs in the 1.9 version.
Of course, it will be better once you can select your favourite POIs again and save these preferences.

**Comment by sonora** [comment]
Deprecated.
