### ISSUE TITLE
Elevation widget getting out of sync?

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#14700]
I noticed a strange behavior of the elevation widget. After some time it displays my current location at a wrong position. Consequently also the remaining uphill/downhill elevation is wrong. This can be fixed by stopping and restarting the navigation.

Example one:
<img src="https://user-images.githubusercontent.com/1040784/176231442-46dd1bc2-1a7b-4ca5-9561-ca76c7a85936.png" width="33%" /> <img src="https://user-images.githubusercontent.com/1040784/176231449-8db65cd1-bb07-4e59-9c4c-4236d227c290.png" width="33%" />

Example two:
<img src="https://user-images.githubusercontent.com/1040784/176231508-1ad95c11-1637-433c-b1d1-6685a3894076.png" width="33%" /> <img src="https://user-images.githubusercontent.com/1040784/176231513-3864b758-6cbd-4425-9a8f-52279e9b6227.png" width="33%" />

In the first screenshot for each example the current location in the elevation profile is wrong. The current elevation from the elevation profile widget is clearly out of sync with the elevation displayed in the widget in the top right corner.

The second screenshot for each example is after stopping & restarting the navigation. Now everything looks fine again, especially the remaining uphill/downhill numbers.

Somehow my position in this widget is moving faster than I'm actually moving. Is this a bug or am I doing something wrong?

Also the gradient number is missing.

In case it is relevant: I'm following a track I've previously planned with OsmAnd.

**Comment by vshcherb** [comment]
If you have recorded track you could send to our support or attach it here. Otherwise please record video, from screenshots it's hard to understand what's exactly get lost and when.

Workraound: move the map / scale of the graph slightly and press my location to "resynchronize" graph & my location

**Comment by scaidermern** [comment]
I've uploaded a video: https://www.veed.io/view/7e348f8f-77fa-4390-acf7-2adcb0881da3
(btw. it would be nice if you could provide a place for uploaded videos because github doesn't allow more than 10MB)

In the first part of the video you can see that the elevation profile widget displays my current position at an elevation of 1074m at a distance of roughly 5km. The remaining uphill / downhill distances are supposed to be 345m / 358m. All these numbers are wrong. The elevation widget in the top right instead displays an elevation of 1172m  and a remaining distance of 13km. These numbers are correct.

You can see that moving the map and pressing the my location button in the lower right doesn't synchronize the graph. Also moving the graph around doesn't synchronize it either.

In the second part of the video I've stopped the navigation and restarted it. Now the numbers in the graph are correct.

**Comment by Zirochkabila** [comment]
1. The restriction on video uploads is imposed by GitHub.

2. Your case was tested on version 4.2.5 - it could not be reproduced. All indicators correspond to the actual before the pause navigation and after the continuation (as seen in the video)
If you use a custom profile - send it for checking.
Do you activate Use elevation data?
Also please specify everything that was mentioned above - it will speed up the testing process.

3. Enable Grade indicators can be activated as follows: Menu > Configure screen > Bottom panel > Settings Elevation profile > Show slope > Apply


https://user-images.githubusercontent.com/104760013/176903652-e58b5975-d36e-42f1-a1d4-c272c6b7826a.mp4

**Comment by scaidermern** [comment]
> 1. The restriction on video uploads is imposed by GitHub.

Yes, I know. That's why it would be nice if you could provide a place for video uploads. 

>     2. Your case was tested on version 4.2.5 - it could not be reproduced.

I'm on 4.2.5.

> All indicators correspond to the actual before the pause navigation and after the continuation (as seen in the video)

I have no idea what this is supposed to mean. The numbers in the graph before stopping the navigation are totally different from the numbers after restarting the navigation. So it is not possible that both numbers are correct. The numbers in the graph before stopping the navigation don't match the numbers in the top right widgets, as I already explained several times. 

>        If you use a custom profile - send it for checking.

[Export_01-07-22.osf.txt](https://github.com/osmandapp/OsmAnd/files/9029797/Export_01-07-22.osf.txt)
(looks like .osf extension is not allowed so I had to rename it) 

>        Do you activate Use elevation data?

No, it is currently disabled. 

>        Also please specify everything that was mentioned above - it will speed up the testing process.

Will dot, see next comment. 

>     3. Enable Grade indicators can be activated as follows: Menu > Configure screen > Bottom panel > Settings Elevation profile > Show slope > Apply

Thanks!

**Comment by scaidermern** [comment]
> Please clarify:
> 
>     1. The device you are using / OS version

Samsung Galaxy S9, Android 10, LineageOS 17.1

>     2. Application version and map update date

OsmAnd 4.2.5, latest maps from June. 

>        З. Route - start and finish coordinates/ GPX track

[Meraner Höhenweg 05 Matatz Muthöfe OsmAnd.gpx.txt](https://github.com/osmandapp/OsmAnd/files/9029853/Meraner.Hohenweg.05.Matatz.Muthofe.OsmAnd.gpx.txt)

>     3. Presence of traffic restrictions

Not present. 

>     4. Profile you use (export profile)

See previous comment. 

>     5. What map are you using in Map source?

OsmAnd vector map.

**Comment by scaidermern** [comment]
> telegram-cloud-document-2-5330521204266638078.mp4

Yes, this looks correct. However your example is way too short. In my case it also does look correct right after starting the navigation. However it becomes incorrect after some time of hiking (30 minutes, 60 minutes, I can't really tell).

**Comment by Zirochkabila** [comment]
1. I advise you to use Google Drive to download files, at least we do so.
2. The case was checked with the default profile and your GPX - it couldn't reproduce, the readings in the lower widget correspond to the readings in the upper widget.
3. With the profile settings that you sent and GPX track - playback also failed.

Maybe it's in the geolocation settings on your device

Only on this route is there an error in the display of data on the widgets?

**Comment by scaidermern** [comment]
> 1. I advise you to use Google Drive to download files, at least we do so.

I try to avoid Google but I guess in this case this is fine.

>     2. The case was checked with the default profile and your GPX - it couldn't reproduce, the readings in the lower widget correspond to the readings in the upper widget.
> 
>     3. With the profile settings that you sent and GPX track - playback also failed.

What does "playback also failed" mean exactly?

> Maybe it's in the geolocation settings on your device

I don't think so. As you can see in the screenshots and the video, OsmAnd is able to receive correct information. This can be seen in the widgets in the upper right corner. Recorded GPX tracks also look fine. It is really just the elevation widget which has wrong information. So this must be caused by the OsmAnd software.

Also check #14728. This even happens during simulation.

> Only on this route is there an error in the display of data on the widgets?

No, all routes. I also tried regular navigation (i.e. not following a GPX track). With regular navigation the same bug happens.

**Comment by scaidermern** [comment]
I think I just found a reliable way to reproduce this inconsistency.

Start a navigation (or a simulation). The data in the elevation widget should be correct. Switch of the display and switch it on again. Now the data (especially the height) is incorrect.

This seems to match the observed behavior in #14728. Here the display stays on but a reconfiguration of the elevation widget happens. It seems like this bug is also triggered by this reconfiguration.

**Comment by scaidermern** [comment]
It would be nice to have this fixed in version 4.3. Overall this is a feature users pay extra money for. Moving it to 4.4 feels wrong.
