### ISSUE TITLE
Live Maps - Old maps still showing

### ISSUE THREAD

**Issue by Fizzie41** [osmandapp/OsmAnd#14714]
### Description

Hi. Have spotted an issue a number of times now that 2 paths will show side by side on OSMand, or a road will have multiple lines showing up for it, but OSM only has 1 mapped. In at least some of these places, I have updated the OSM map to correct the path / road in question when newer imagery has become available, so it would appear that the old map traces are still showing in addition to the current map?  

### How to reproduce?

![Fleays OSMand](https://user-images.githubusercontent.com/35707521/176593142-05d359e4-5d4c-44f4-ba8b-785482715ee2.png)
Double paths shown through the Amphitheatre & up to Nalu Theatre, & also overlapping roads between Maintenance & Admin

[https://www.openstreetmap.org/#map=19/-28.10805/153.44496](url)

[https://www.openstreetmap.org/edit#map=20/-28.10805/153.44496](url)

OSM shows single paths & only one road. I last edited these paths ~7 months ago, but the "extras" are still showing on the updated 1 June maps that I have downloaded this morning.

I can provide further examples of the same thing occurring with other both foot-& cycle- paths.

### Your Environment
OsmAnd Version: OSMAnd+ 4.2.4
Android/iOS version: Android 9
Device model: realme C2

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by hakuchi** [comment]
Can you delet the maps from your phone and redownload them!?
This happend to me and so it fixed for me.

**Comment by vshcherb** [comment]
That could still happen but the chance is small, usually redownload live cache

**Comment by Fizzie41** [comment]
Thanks! Just deleted & reinstalled maps & problem now fixed :-) (Except that it also deleted all my favourites & saved locations :-() Interestingly though, after doing so, my phone is still showing the same amount of memory being used by OSMAnd as previously, so I guess the old images were just cached somewhere despite the actual maps having been over-written?

**Comment by Discostu36** [comment]
I have the same problem but only with OpenGL rendering. Re-downloading the map doesn't fix.

![Screenshot_20230630-105505_1.png](https://github.com/osmandapp/OsmAnd/assets/30999326/904de2ce-1c24-4cfa-8f0d-4a4b19163063)

**Comment by scaidermern** [comment]
For OpenGL there is a separate ticket about this: #14920
However, it is supposed to be already fixed. Unfortunately the developers never tell for which version the fix applies. I guess for 4.5.x but not sure.

**Comment by sanatsathaye** [comment]
> For OpenGL there is a separate ticket about this: #14920 However, it is supposed to be already fixed. Unfortunately the developers never tell for which version the fix applies. I guess for 4.5.x but not sure.

It's tagged with milestone 4.5-backend.

**Comment by scaidermern** [comment]
Same problem for me.

50.99589,6.57693
![17575](https://github.com/osmandapp/OsmAnd/assets/1040784/55c00141-baae-4ed2-b72d-13dc19d529c6)

50.99697,6.57895
![17574](https://github.com/osmandapp/OsmAnd/assets/1040784/1b4214e4-7bf9-4254-8d3f-7fc760de446a)

Clearing and re-downloading live data didn't help. 

Problem disappears with rendering engine v1. 

OsmAnd 4.5.10. 

Other users report the same bug (e.g. at https://community.openstreetmap.org/t/poi-loschen-geschaft/7248/40).

**Comment by vshcherb** [comment]
Some issues with duplicate data are fixed  and the roads duplicate issue is merged to https://github.com/osmandapp/OsmAnd/issues/18153

**Comment by ivanPyrohivskyi** [comment]
@scaidermern what map are you downloaded?
Full North Rhine-Phestphalia or just some part (Cologne Goverment Region)?

**Comment by scaidermern** [comment]
> @scaidermern what map are you downloaded? Full North Rhine-Phestphalia or just some part (Cologne Goverment Region)?

The full map of NRW.

**Comment by vshcherb** [comment]
Important issue is fixed in https://github.com/osmandapp/OsmAnd-core/pull/663 - 4.6 release will have the fix

**Comment by vshcherb** [comment]
Done: fixed issue with Live maps (whole region like Bavaria) and standard maps (small part like Bavaria subregion)
