### ISSUE TITLE
When using the 2.5D view, the "Distance by tap" ruler is displayed in an inconsistent way.

### ISSUE THREAD

**Issue by Max1234-Ita** [osmandapp/OsmAnd#14713]
### Description
When OsmAnd is set to use 2.5D visualization, the "Distance by tap" ruler does not work in a proper way: the numeric value corresponding to the measured distance is correct, but the ruler is drawn in a wrong way, not considering the distortion introduced by the "false-perspective view".
Issue occurs in both Osmand Free and OsmAnd+ version.

### How to reproduce?

1. Enable the _Distance by tap_ from the Configure screen menu

2. Activate the 2.5D visualization mode, by enabling the OpenGL rendering in _Plugins -> Osmand Development -> Settings_;

3. Exit the setting menu and go to the map screen; Drag the map upwards with 2 fingers in order to show it in 2.5D;

4. Place 2 fingers anywhere on the screen and observe the _Distance by tap_ ruler being drawn;

### Your Environment
OsmAnd Version:  Osmand+ 4.2.5
Android/iOS version: Android 11
Device model:  Samsung Galaxy A50 (SM-A505FN/DS)

**Maps used (online or offline):**   
Issue observed with Offline vector maps.

**Comment by Max1234-Ita** [comment]
Please also check this video, explaining the symptoms:  https://www.youtube.com/shorts/xe84ughvYBg

**Comment by vshcherb** [comment]
Video is private, please upload short versoin just to Github

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd/pull/14785
