### ISSUE TITLE
Hyperlinks & formatting issue for My Favourites POI descriptions / notes in Osm 4.2.5

### ISSUE THREAD

**Issue by Boothy99** [osmandapp/OsmAnd#14710]
Hyperlinks are only viewable, blue & work when the preview of "Description" of POI is in view. On opening "READ FULL" the hyperlink becomes plain text and not openable. All previous formatting inside the note is lost (paragraph spacing etc).

To reproduce? -
Click on a Favourite POI on the map with text & hyperlink in the description note. Opening READ FULL shows formatting is lost and hyperlinks are non functional. 

Environment -
OsmAnd+ 4.2.5
Android 11
Xiaomi Mi 9T mobile.

Maps used - 
OsmAnd offline.
All UK England / Scotland / Wales for 1st June 2022 (any offline map has same issue).

PREVIEW SHOWS WORKING LINKS
<img src="https://user-images.githubusercontent.com/13983995/176519964-267b7c90-4c71-43d7-a42a-7ffe805f177c.jpg"  width="200" height="auto"/> 

FULL VIEW SHOWS LOST FORMATTING (there were spaces between paragraphs) & NON FUNCTIONING LINKS
<img src="https://user-images.githubusercontent.com/13983995/176520200-fa45454e-4f14-436b-8f3d-bdefb1089704.jpg"  width="200" height="auto"/>

**Comment by vshcherb** [comment]
Read full supports plain html, so it's a bit different feature to be honest. Here we would need to detect whether text is html or not to open in another viewer

**Comment by Boothy99** [comment]
Hi @vshcherb,
Before the update, I know the formatting was kept - i.e. I'd inserted paragraph spaces which were kept intact previously. Unfortunately these seem to have been lost, resulting in the text appearing as a joined up mass without the previously inserted spaces.

Regarding the functioning weblinks - I've just checked on my Samsung Galaxy Tab S4 which is currently still running OsmAnd+ 4.2.4. Opening the "Read Full" shows intact weblinks (in blue) as well as my original formatting. There's definitely something changed between 4.2.4 & 4.2.5.

I'll post a screenshot from my tablet shortly.

**Comment by Boothy99** [comment]
Screenshot showing Read Full view of the same POI as above from Samsung Galaxy Tab S4 running OsmAnd+ 4.2.4.
Formatting & weblinks (showing blue) are how they should be.


![Screenshot_20220630-212131_OsmAnd+](https://user-images.githubusercontent.com/13983995/176771861-5a91e29b-d47c-44fd-8d45-36c027d4ef9a.jpg)

**Comment by Boothy99** [comment]
As a side observation, I clicked on the (new) "Edit" option in Full view. Instantly, the formatting was displayed correctly. The text is nolonger joined-up.
Clicking "Save" however, does not keep the spacing /formatting. 

Here's another screenshot whilst in "edit" mode for the same POI (on 4.2.5 on my Xiaomi Mi 9T).

![Screenshot_2022-06-30-21-31-32-925_net osmand plus](https://user-images.githubusercontent.com/13983995/176773507-9f16a54b-1eeb-42e2-9c00-969901294d9e.jpg)

**Comment by Boothy99** [comment]
Hyperlinks are no-longer "clickable" / "openable" in 4.2.5 as they are /were in 4.2.4.

**Comment by Boothy99** [comment]
> Read full supports plain html, so it's a bit different feature to be honest. Here we would need to detect whether text is html or not to open in another viewer

Hi @vshcherb
Could I ask whether the "Read Full" text viewer has changed in 4.2.5 since the last version of OsmAnd+, as the formatting and ability to display working web / map links all worked well previously as shown in the screenshots above from version 4.2.4.
It's difficult to read the text in the full view now that everything has become joined-up without spacing. The formatting is at least still there - when viewed in Edit mode, so it's not gone.

**Comment by vshcherb** [comment]
We will check if we can make conditional on tags

**Comment by Boothy99** [comment]
Many thanks for adding this for review in 4.2-android, @vshcherb 
Much appreciated !!

Could I ask that the correct formatting of the Full View be looked at too, to revert it to how it's appeared before (and how it appears in Edit mode), please?

Thanks again.

**Comment by Boothy99** [comment]
@nazar-kutz Thank you very much for updating me and for the examples. I'm a VERY happy chap indeed, cheers !!!
I look forward to the update 👍
Thanks again for sorting this out so quickly. You're a genius 😁

Dave.
