### ISSUE TITLE
Feature Request: Waypoint <extension> type...<phone>

### ISSUE THREAD

**Issue by drtbyk** [osmandapp/OsmAnd#14717]
It would be most helpful to add a GPX <extension> type of <phone>+1 (425) 413-4110</phone> and to display Phone numbers in the Waypoint attributes in My Places so that clicking-on or tapping the phone number would make the call.

Cheers,
Dan T.

**Comment by vshcherb** [comment]
1. We need to display all extensions for waypoints in GPX waypoint context menu
2. We need to save some (all?) POI information into GPX Waypoint extension and Favorite if it's created from POI

**Comment by vshcherb** [comment]
```
<wpt lat="52" lon="5">
<extension>
<phone>My phone number</phone>
<website>https://test.website</website>
<comment>Comment</comment>
<extension>
</wpt>
```

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd/pull/14935

**Comment by nnngrach** [comment]
IOS
https://github.com/osmandapp/OsmAnd-iOS/pull/2086
https://github.com/osmandapp/OsmAnd-core/pull/346

**Comment by dmpr0** [comment]
## Review
This tags doesn't displayed
```
<wpt lat="52" lon="5">
<extension>
<phone>My phone number</phone>
<website>https://test.website</website>
<comment>Comment</comment>
<extension>
</wpt>

```
