### ISSUE TITLE
The data about the current altitude in the Elevation profile widget is different from the data in Altitude of current location

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#14728]
### Description
The data about the current altitude in the Elevation profile widget in the lower part of the screen is different from the data in Altitude of current location when Show slope in Elevation profile is activated

### Steps to reproduce
Select start position 48.61150° N, 22.98857° E > Set destination 48.61107° N, 22.98203° E > Select Pedestrian profile > Start > Menu > Configure screen > Bottom panel > Settings Elevation profile > Show slope > Apply 

### Actual result
The data about the current altitude in the Elevation profile widget is different from the data in Altitude of current location

https://user-images.githubusercontent.com/104760013/176906994-fe8c1150-a01f-42fd-a4cf-1f5d304e8569.mp4

### Expected result
The data about the current altitude in the Elevation profile widget is same as the data in Altitude of current location

### Your Environment
OsmAnd Version: 4.2.5
Android/iOS version: Android 11
Device model: POCO X3 NFC

**Comment by vshcherb** [comment]
Duplicate issue?

**Comment by scaidermern** [comment]
Yes, sounds like #14700.
