### ISSUE TITLE
POI creation: suggestion of UI improvement

### ISSUE THREAD

**Issue by severinmenard** [osmandapp/Osmand#1473]
The preset is long and generally exceeds the size of small/medium size smartphones, despite many rows are rarely filled. Therefore you need to shut down the virtual keyboard to get access to the Save button. IMHO Open, Street, House number, Phone and Website should be minimized and accessible from a + to be clicked.

**Comment by Barrocas** [comment]
It used to be an issue on previous versions, but with the mods applied on current night builds, on the 'Create/edit POI' module, it's no longer a problem.
The 'Send' (and 'Cancel') button is visible and accesible on the bottom of the screen, and also on the virtual keyboard bottom right corner.
