### ISSUE TITLE
Issue with hiding a My Favourites (My Places) group.

### ISSUE THREAD

**Issue by Boothy99** [osmandapp/OsmAnd#14739]
### Issue
If you hide a My Favourites (My Places) group, the group icon does not stay greyed out and does not remain at the bottom of the list after closing down OsmAnd+.

### How to reproduce?
Open My Places / My Favourites.
Open options menu for a group and de-select the switch to hide the group (de-select "Show on Map").

Initially this appears to work correctly -
- The icons become hidden on the map.
- Group name moves to bottom of the list and becomes greyed-out.

However, after closing down OsmAnd+ and re-opening, the My Places group reappears back in it's original alphabetical position in the list. 
It is no-longer greyed out and has moved from the bottom of the list.

On opening the options for the group that is supposed to be greyed out, the selection button is in the "Show on Map" = Yes / On. However, the icons are NOT showing on the map.

To make the POI's viewable on the map, one has to deselect the switch to "Hidden" then re-select the switch to "Show on Map".

### Environment
OsmAnd+ 4.2.5
Android 11
Xiaomi Mi 9T mobile.

### Maps used
OsmAnd offline.
All UK England / Scotland / Wales for 1st June 2022 (any offline map has same issue).

**Comment by pebogufi** [comment]
I know this problem, but it looks like fixed in latest nightly. Please dnl and test again with latest.

**Comment by Boothy99** [comment]
Thanks for the information @pebogufi
I'll await the release version ASAP when it's available I get WiFi.
Cheers

**Comment by Boothy99** [comment]
@pebogufi 
Downloaded over a pint on pub WiFi last night, and see it's fixed. Thanks for the heads-up 😁
