### ISSUE TITLE
Move the elevation and percentage of elevation overrun to the left corner of the graphic

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#14744]
### Description
Move the elevation and percentage of elevation overrun to the left corner of the graphic
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/177054174-03c558d8-accf-4763-b0f2-e0e962e32d67.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by dmpr0** [comment]
![Screenshot 2022-10-21 at 09 47 24](https://user-images.githubusercontent.com/9365308/197130894-a9f694d5-1575-43ba-b7f2-434df1588e6a.png)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.3.0#13902mqta, released: 2022-10-26
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/198050292-506a7431-a2e0-4011-92ed-80873edd6bb9.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by EugeneZmeuk** [comment]
Change screenshots:
https://osmand.net/docs/user/plugins/trip-recording#overview-recorded-information
