### ISSUE TITLE
Change default folder when importing multi-segment track

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#14741]
### Description
When importing tracks, there are two different default folders:

If the track consists of one part only, default is "import"
It it consists of more than one part, default is "tracks"

Shouldn´t it be in both cases "import"?

And a suggestion please:
The importing switch is on top of the importing-tracks-page, but the folder selecting is at the bottom of this page.
Could you move both to the same position - no matter, if top or bottom? Thanks! 

### How to reproduce?
Just import different tracks

### Your Environment
OsmAnd Version: latest, but it was also before
Android/iOS version: 12
Device model: S20+

**Comment by Rowin63** [comment]
I don´t "choose" that folder, it is the default and I have to change it on every import.
"Tracks" is the main folder that contains all the others, like "import" ect.
You can see it by the blue frame, it is selected by default.

(importing like: choosing Osmand at the "open with" menu from another app)


![importing tracks to tracks folder](https://user-images.githubusercontent.com/95540936/177207417-97ed5960-328d-4d1c-8c3f-2322dc2901a1.JPG)

**Comment by vshcherb** [comment]
Here we can change default

**Comment by Rowin63** [comment]
be aware of, it only happens when importing a "multi-segement"-track!
Importing a single track does go to "import" by default!

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14082mqta, released: 2023-01-09
Done

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/211279303-d0cbe667-94fe-45a9-9dd0-43c31f105d17.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>
