### ISSUE TITLE
POI creation: rename Advanced mode by Add tag

### ISSUE THREAD

**Issue by severinmenard** [osmandapp/Osmand#1474]
I do not see the benefit to have an extra step with clicking on Advanced mode to get access only to Add tag. Having directly the Add tag button would be great

**Comment by Barrocas** [comment]
That was the way it used to be on previous versions, and I liked it too, there were less tabs to confuse the user.

But on previous versions, you could also read the OSM tag applied and the translation on the same screen, while now we only see the translation, and the OSM tag is hidden in the Advanced tab.

**Comment by sonora** [comment]
No action planned, I guess.
