### ISSUE TITLE
Strange Bike Route (Bug ?)

### ISSUE THREAD

**Issue by wefranke** [osmandapp/OsmAnd#14748]
### Description
I have activated the bike profile in Osmand and planned a route. In the route, Osmand did not want to use a path marked as a bike route in the map and also did not want to use an unmarked path elsewhere.
Is this a bug in Osmand or in the map ?
I added the resulting GPX-File (strange bike trail.zip)
When I change the "Roure between two points" from bicycle to pedestrian, Osmand uses the path (Picture: Route between two points).

Attachments:
Screenshot_bicycle_route: I have marked the two places. At 'Holnstein' the solid line between house 11 and the small lakes should be used.
Bicycle_route_detail_1: The resulting route although the blue line should have been used.
Bicycle_route_detail_2: The blue marked bike-trail goes from 1 to 2 to 3 and continue to 4. It's only marked when bike-routes are activated.

### How to reproduce?
When create an bike route on that (and maybe other) locations.

### Your Environment
OsmAnd Version:  4.2.5 and 4.2.4
Android/iOS version: 12
Device model: Samsung Galaxy TabActive3, Galaxy M31

**Maps used (online or offline):**   
Offline Maps from https://download.osmand.net/list.php,
Name changed (e.g.) from "Germany_bayern_lower-bavaria_europe_2.obf" to "Germany_bayern_lower-bavaria_europe.obf"
Date of the maps: 01.06.2022

[strange bike trail.zip](https://github.com/osmandapp/OsmAnd/files/9038792/strange.bike.trail.zip)
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/96303564/177140868-fe3398e8-be58-42cb-a543-a9c78b1cabd9.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/96303564/177141512-a0129621-cf62-48fb-aa42-159e1530ca5d.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/96303564/177142039-aaf1ac0b-bcb4-4c4b-9c66-b3032613d8c1.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/96303564/177142545-bd6fe0ac-92ed-4c2f-aee3-289eae0ab8d5.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
Looks very weird the issue is likely in GPX file which could be broken and I don't see you attached it to the issue.

**Comment by Zirochkabila** [comment]
>

1. On the first road there are traffic restrictions. That's why OsmAnd doesn't use it when building a route 
https://www.openstreetmap.org/way/338043598#map=17/49.10640/11.51053

3. The second route is marked as "private" accordingly the passage is also prohibited by the tag on the map
https://www.openstreetmap.org/way/745732273#map=17/49.04149/11.47529

**Comment by wefranke** [comment]
1. OK.
2. That actually makes no sense at this point, because the path is marked as a bike path. In this respect, the property "bike path" could override the property "private", because when you create a bike route, you don't expect it. But now I know that something like this can happen and I can pay attention to it. OK.
Much Thanks
