### ISSUE TITLE
OpenGL 2.5D -- more tilt

### ISSUE THREAD

**Issue by lbdroid** [osmandapp/OsmAnd#14752]
### Description

In OpenGL view, the maximum tilt angle is very small, resulting in a very little difference from just leaving the map flat.

### Describe the solution you'd like

Allow a greater range of tilt in order to simulate a "moving forward" type of view that resembles what the driver might theoretically see through the windshield. Ideally even showing a horizon (black or blue depending on night or day) when at extreme tilt.

I presume that this is limited in order to restrict the amount of map that has to be rendered. With a viewport 4 feet above ground level, the distance to the horizon is approximately 2.5 miles, which may be used as an upper bound on the size of map that needs to be rendered.

Its probably fine to ignore earth curvature and simply cut off the map at the horizon.

- [x] дописать в документацию углы

**Comment by sonora** [comment]
Be aware that higher tilt will also make things less realistic from some poiint on, increasingly exposing the fact that there is no 3D data, and that things like hillshades or building shapes are really just 2D color patterns on a flat map.

**Comment by lbdroid** [comment]
> Be aware that higher tilt will also make things less realistic from some poiint on, increasingly exposing the fact that there is no 3D data, and that things like hillshades or building shapes are really just 2D color patterns on a flat map.

No doubt, however realistic or not, it would make things a lot nicer for navigation, and also provide an incentive to eventually start adding some of those 3D elements.

**Comment by lbdroid** [comment]
I like it. Good amount of tilt now!
