### ISSUE TITLE
Offline Rendering: do not display duplicate names when they are close enough

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1475]
(can't attach image for some reason)
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshot%20-%20071515%20-%2022%3A06%3A07.png

**Comment by vshcherb** [comment]
The issue is not fixed, though the situation is already much better. I think we could live with it in legacy engine and for opengl engine could start preparing use cases to fix.

**Comment by vshcherb** [comment]
minDistance field could be used to make it nicer.

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-core/commit/3591622f8820649393448d1a3c6562efce92220f
