### ISSUE TITLE
Plugin content not updated when installation new file

### ISSUE THREAD

**Issue by cmoffroad** [osmandapp/OsmAnd#14766]
### Description

I have created my own OsmAnd plugin which includes for now a renderer.
First-time installation works great and the plugin is automatically enabled.

New, installation with updated content does not work without deleting the plugin first and closing the application.
I have tried to bump the items.json and renderer XML version number but it does not help.

### How to reproduce?

- install https://github.com/cmoffroad/osm-tools/raw/master/osmand-outdoor-explorer-plugin-preview/build/osmand-outdoor-explorer-plugin.osf
- app says the plugin was successfully installed
- in the profile of your choice, select map type "outdoor-explorer", the forest background color should show as green
- install https://github.com/cmoffroad/osm-tools/raw/master/osmand-outdoor-explorer-plugin-preview/build/osmand-outdoor-explorer-plugin-test.osf
- app stays plugin was successfully installed
- forest should have a red background color (only for testing purposes)

### Your Environment
OsmAnd Version: 4.2.6
Android/iOS version: Android  8.0.0
Device model: Samsung Galaxy S7

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

### Expected Behavior

The updated plugin installation should:
- replace the old content with the new content
- inform users that "plugin was successfully updated"

**Comment by Zirochkabila** [comment]
> 
After installing the first plugin, the "outdoor-explorer" map does not appear in the Map source

**Comment by cmoffroad** [comment]
Thanks for the update!

So it looks like a bug for Android. Do you have any workaround or ideas on how to prevent the issue?

**Comment by vshcherb** [comment]
Linked https://github.com/osmandapp/OsmAnd-iOS/issues/2069
