### ISSUE TITLE
Instantaneous navigation override

### ISSUE THREAD

**Issue by guglovich** [osmandapp/OsmAnd#14760]
### Description
Automatically terminates GPX track navigation when start and finish points are close by.

### How to reproduce?
Run a GPX track where the start and finish points are near or in the same place. Start the start of navigation.

### Your Environment
OsmAnd Version: 4.1.11
Android/iOS version: Android 12.1
Device model: Xiaomi Redmi Note 8T

https://user-images.githubusercontent.com/54148165/177457042-f4cd14bf-d6df-4ba1-9626-10b1cd7e1ba2.mp4

**Comment by Zirochkabila** [comment]
Try to select your start position in the start GPX position

Select GPX > Navigation > From > Chose on the GPX start position

**Comment by guglovich** [comment]
> Try to select your start position in the start GPX position
> 
> Select GPX > Navigation > From > Chose on the GPX start position

I do, it's just that the video doesn't show the touches on the screen. I use the navigation once a week on a regular basis.

**Comment by vshcherb** [comment]
I think if GPX is long enough > 100m and select start GPX (not my location), you will have this correclty working once you hit Start.
If still doesn't work in 4.2.6, please share GPX and we will try to reproduce.

**Comment by guglovich** [comment]
The problem sometimes recurs, for example, today.  I am attaching the file I am using.

[ShuvalovskijPuisto_15k.gpx.zip](https://github.com/osmandapp/OsmAnd/files/11584204/ShuvalovskijPuisto_15k.gpx.zip)
