### ISSUE TITLE
Many buildings lost the link to the OSM object

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#14761]
Osmand doesn't always show a link to a building.

https://www.openstreetmap.org/way/437765393

![Screenshot_2022-07-06-10-26-42-218_net.osmand.plus.jpg](https://user-images.githubusercontent.com/12549744/177493891-9bfa17b9-5863-4764-a6d4-c9d88d592892.jpg)

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13629mqta, Дата выпуска: 2022-07-06
Android version: 12
Device model: poco f3

**Comment by Chumva** [comment]
https://github.com/osmandapp/OsmAnd/pull/14823
