### ISSUE TITLE
When turned off, the track does not turn gray

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#14765]
If the track was colored depending on the speed or height, then the track does not turn gray when turned off.
![Screenshot_2022-07-06-10-58-26-775_net.osmand.plus.jpg](https://user-images.githubusercontent.com/12549744/177500357-26048909-f970-4ad9-9c0e-e9b622231501.jpg)

If solid color
![Screenshot_2022-07-06-11-00-12-427_net.osmand.plus.jpg](https://user-images.githubusercontent.com/12549744/177500621-937649b0-30bd-4177-91c3-a511e78ae313.jpg)

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13629mqta, Дата выпуска: 2022-07-06
Android version: 12
Device model: poco f3

**Comment by dmpr0** [comment]
Duplicate https://github.com/osmandapp/OsmAnd/issues/14599
