### ISSUE TITLE
Cliff on the relief map

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#14764]
### Description

In the Leningrad region on the relief map there is an object resembling a wall separating it from wild Karelians;)

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/12549744/177499061-bbec5a6a-4063-499f-a928-217baad30f3e.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

https://user-images.githubusercontent.com/12549744/177499375-1fcae6e5-551f-4641-9c4b-8dac5e06ac8b.mp4

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13629mqta, Дата выпуска: 2022-07-06
Android version: 12
Device model: poco f3

**Comment by Zirochkabila** [comment]
### Description
A black line is displayed that separates the mountains

https://www.openstreetmap.org/search?query=60.947636%2C%2029.174977#map=11/61.0101/29.2154

### Steps to reproduce
Search > 60.947636, 29.174977 > Download map > Configure map > Terrain > Download Hillshade > turn on 

### Actual result
A black line is displayed that separates the mountains

### Expected result
The map is displayed without a black line

### Your Environment
OsmAnd Version: 4.3.0#13634mqta, released: 2022-07-08
Android/iOS version: Android 11
Device model: POCO X3 NFC

**Comment by xmd5a2** [comment]
Fixed. Hillshade updated.
