### ISSUE TITLE
What is the meaning of the fan shaped area behind my current position in those gps applications

### ISSUE THREAD

**Issue by QiangF** [osmandapp/Osmand#1476]
In osmand, my current position is shown as a spot with a certain radius, the radius shows the accuracy of my position, sometimes there is a fan shaped area in that spot, what does that mean?
Thank you for your help!

**Comment by fred702** [comment]
I believe it is the estimated direction you are facing using your device's compass measurements.

**Comment by sonora** [comment]
Yes, it is your viewing direction, i.e. the direction the top or your device is facing.
