### ISSUE TITLE
v4.2.4 Hide track broken function

### ISSUE THREAD

**Issue by snooppr** [osmandapp/OsmAnd#14763]
Android 9.
OsmAnd v4.2.4

https://user-images.githubusercontent.com/61022210/177499200-cf6ab35f-8422-41b8-8db8-5894ba491c0d.gif

**Comment by dmpr0** [comment]
Duplicate https://github.com/osmandapp/OsmAnd/issues/14599

**Comment by snooppr** [comment]
Ok, This issue was not present in v4.1.9.
