### ISSUE TITLE
Strange metamorphosis display island

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#14762]
https://www.openstreetmap.org/way/27337692

Video:
https://user-images.githubusercontent.com/12549744/177497516-a8bf99fa-ec15-4fa1-aa90-d000814db9ba.mp4

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13629mqta, Дата выпуска: 2022-07-06
Android version: 12
Device model: poco f3

**Comment by Nine-Tailed** [comment]
The bug is still reproducible with opengl enabled.
OsmAnd~ 4.3.0#13645mqta, Дата выпуска: 2022-07-13
![Screenshot_2022-07-14-01-45-39-000_net.osmand.plus.jpg](https://user-images.githubusercontent.com/12549744/178849894-fb04c45c-abc5-4179-8566-b49f958cacc4.jpg)

**Comment by vshcherb** [comment]
It's merged to another issue not closed
