### ISSUE TITLE
man_made=surveillance without names or descriptions not listed

### ISSUE THREAD

**Issue by fred702** [osmandapp/Osmand#1477]
When using the POI search function, most surveillance results are not displayed.
Edit: A few appear, but only those that have a name or description tag.  

see https://github.com/osmandapp/OsmAnd-resources/blob/b90933f30e094f2e6665328b07e3916668f593f4/poi/poi_types.xml#L348

**Comment by vshcherb** [comment]
I think this should be a map feature, not a POI.

**Comment by fred702** [comment]
Sorry, I don't know the functional difference between a map feature and a POI as used by OsmAnd. All_ man_made=surveillance objects should be listed and displays when a user makes that search.

Since most surveillance objects do not have a name, they are not displayed.
