### ISSUE TITLE
Android Auto turn instruction for roundabout has syntax error: Take 2 exit

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/OsmAnd#14778]
### Description
On the Android Auto widget, the turn instruction for roundabout is syntactically irritating:
"***Take 2 exit*** and go".

It should either read "Take 2nd exit" or "Take exit 2". The "and go" appears to be meaningless.

### Your Environment
OsmAnd Version: master-nb-2022-07-02 aka 4.3.0#34317
Android version: 7.1.1

**Comment by vshcherb** [comment]
I think message has changed and added to translation and could be changed here 
https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/res/values/strings.xml#L91
