### ISSUE TITLE
Announce/Alert when near Favorite POI while NOT navigating

### ISSUE THREAD

**Issue by JasonRaveling** [osmandapp/OsmAnd#14775]
# 🚀 feature request
Right now you can have Favorites announced but only while navigation on a route. 

It would be great to have the option to enable alerts at all times. For example, if I am out exploring a place I don't know well, hiking, offroading, or even just around town. I would like some of these points to be announced to give me some baring. Much of my area and places I am at are rural and not well mapped. But even while out in town, it would be nice to enable some Favorites (kind of like [the open request for specific favorites](https://github.com/osmandapp/OsmAnd/issues/6927)) to have announced.

**Comment by dmpr0** [comment]
Duplicate https://github.com/osmandapp/OsmAnd/issues/12973
