### ISSUE TITLE
Turn instruction missing at angled junction / Berlin, Alexanderstr ->Karl-Liebknecht-Str

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/OsmAnd#14777]
### Description
On the left turn in [Berlin, Alexanderstr ->Karl-Liebknecht-Str](https://www.openstreetmap.org/?mlat=52.52403&mlon=13.41246#map=19/52.52403/13.41246), the instruction is missing. 

The junction is a bit difficult, from Alexanderstr the 'straight' is already slightly left into Memhardstr, and further left is Karl-Liebknecht-Str.

The turn lanes are shown correctly.

Probably making a turn event since the road name changes would help, see also #6336.
### Your Environment
OsmAnd Version: master-nb-2022-07-02 aka 4.3.0#34317
Android version: 7.1.1

**Maps used (online or offline):**   offline, Germany_brandenburg_europe_2.obf 01 June 2022

Simulation:
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/8266355/177648654-65fcdb72-7731-45fb-b7e7-8b709591f31e.png"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/8266355/177648661-ea8424dc-be91-442e-85d9-45d6858c9c8c.png"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/8266355/177648663-3c2572ea-a6a2-407f-8571-66c2246527af.png"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
### Description
The left turn is not displayed in the widget and is not voiced in the voice prompts

https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=52.52345%2C13.41377%3B52.52344%2C13.41104#map=18/52.52375/13.41241
https://osmand.net/map/?start=52.523539%2C13.413609&end=52.523360%2C13.410986&pin=48.799474%2C9.171427&mode=car#18/52.52362/13.41345

### Steps to reproduce
Select start of departure 52.52345, 13.41377 > Set destination 52.52344, 13.41104 > Options > Simulate navigation > Start

### Actual result
The left turn is not displayed in the widget and is not voiced in the voice prompts

### Expected result
The left turn is displayed in the widget and is voiced in the voice prompts

### Your Environment
OsmAnd Version: 4.3.0#13634mqta, released: 2022-07-08
Android/iOS version: Android 11
Device model: POCO X3 NFC

**Comment by vshcherb** [comment]
@Zirochkabila it's displayed as Turn Lanes! But mute, so we need to understand why actually.

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/pull/15633

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-core-legacy/pull/109

**Comment by alisa911** [comment]
- [ ] add speak to tests
- [ ] test [pull](https://github.com/osmandapp/OsmAnd/pull/15633)

**Comment by alisa911** [comment]
tests https://github.com/osmandapp/OsmAnd-resources/pull/864
java https://github.com/osmandapp/OsmAnd/pull/15692/files

**53. add mute keep left**

<img width="780" alt="Screenshot 2022-11-10 at 12 05 39" src="https://user-images.githubusercontent.com/38911173/201062100-ea30d35b-95b1-4d6c-92cd-0ba914b93494.png">

**52. add mute keep right**

<img width="755" alt="Screenshot 2022-11-10 at 12 07 01" src="https://user-images.githubusercontent.com/38911173/201062333-80bb5e86-5a81-4468-99df-9188e4f89427.png">

**Other cases with MUTE, which weren't affected by the fix**

2.3
<img width="1208" alt="Screenshot 2022-11-10 at 12 19 48" src="https://user-images.githubusercontent.com/38911173/201065263-cfeb2e43-aa6d-496c-87a5-0ec51e4a0bed.png">
32
<img width="721" alt="Screenshot 2022-11-10 at 12 21 26" src="https://user-images.githubusercontent.com/38911173/201065598-48263667-b7e9-4bf4-b158-c4a07bb57919.png">
49
<img width="713" alt="Screenshot 2022-11-10 at 12 22 34" src="https://user-images.githubusercontent.com/38911173/201065851-e53a85fe-fb35-45df-affb-95c31d4b2a4d.png">
54
<img width="1166" alt="Screenshot 2022-11-10 at 12 23 55" src="https://user-images.githubusercontent.com/38911173/201066181-6f2e421a-2fb7-41fa-b50e-ef99a436ac7c.png">
56
<img width="1079" alt="Screenshot 2022-11-10 at 12 25 01" src="https://user-images.githubusercontent.com/38911173/201066410-5c510b59-d521-4746-a738-84b091a07815.png">

**Comment by alisa911** [comment]
java https://github.com/osmandapp/OsmAnd/pull/15695
tests https://github.com/osmandapp/OsmAnd-resources/pull/903
c++ https://github.com/osmandapp/OsmAnd-core-legacy/pull/110

**51**

<img width="1051" alt="Screenshot 2022-11-11 at 09 30 41" src="https://user-images.githubusercontent.com/38911173/201289170-701e881d-de46-4897-8112-60b0eb36ff28.png">

**52**

<img width="899" alt="Screenshot 2022-11-11 at 09 31 24" src="https://user-images.githubusercontent.com/38911173/201289261-48c8aad5-a331-4246-a92d-fc94d5612127.png">

**53**

<img width="788" alt="Screenshot 2022-11-11 at 09 32 03" src="https://user-images.githubusercontent.com/38911173/201289350-488b6b31-9b39-45b6-bd4d-25e09be02679.png">

**new 59**

<img width="1004" alt="Screenshot 2022-11-11 at 09 32 46" src="https://user-images.githubusercontent.com/38911173/201289429-6764a830-e081-41a2-baa6-cf1e6dd6f0b1.png">
