### ISSUE TITLE
Opengl: osmand not showing text for note and fixme tags

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#14784]
### Description
When opengl is enabled, osmand does not show or very rarely shows text for note and fixme tags.

### with opengl
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/12549744/177776211-6ac897a3-3aed-43e4-a640-558785603f89.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

### without opengl
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/12549744/177776341-3e71b296-6a93-4762-8748-37427952bdb5.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Your Environment
OsmAnd Version:  OsmAnd~ 4.3.0#13632mqta, Дата выпуска: 2022-07-07
Android version:12
Device model: poco f3

**Comment by Zirochkabila** [comment]
4.3.0#13634mqta, released: 2022-07-08
Reproduced

**Comment by ivanPyrohivskyi** [comment]
Add to syntetic test rendering

**Comment by xmd5a2** [comment]
Legacy:
![Screenshot_2022-07-27_10-21-16](https://user-images.githubusercontent.com/5829014/181186977-1c6eb118-f0a2-4432-8860-62bc41d1e419.png)

OpenGL:
![Screenshot_2022-07-27_10-21-31](https://user-images.githubusercontent.com/5829014/181187032-5e874a7f-41b2-492e-9ad3-9337c1dda1d8.png)

**Comment by ivanPyrohivskyi** [comment]
Technical comment
Need add filtering by textOrder (RasterizedSymbol order) and intersection by intersectionBBox.
https://github.com/osmandapp/OsmAnd-core/pull/354
In this draft crash in QuadTree inserting, crash in 
https://github.com/osmandapp/OsmAnd-core/blob/4e1dbfa6ddb6a5c46461f2c968516787582fdb0a/include/OsmAndCore/SharedResourcesContainer.h#L379

Better to realize such filtering in AtlasMapRendererSymbolsStage

**Comment by ivanPyrohivskyi** [comment]
resources/rendering_styles/osmassistant.addon.render.xml
OSMMapperAssistant...="true"

**Comment by dmpr0** [comment]
<table style="width:100%">
  <tr>
    <th>Android</th>
    <th>iOS</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/5bbf4e58-631f-4ab9-a8d6-5c5a379da03b"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/8ec9b4d0-39ca-43c7-b248-3d749d9cf262"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
Moved to another issue
