### ISSUE TITLE
Issue with updating online tiles

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#14787]
### Description
I suspect that clicking download tiles loads the maps that were previously loaded, and does not update.

### How to reproduce?
1. Select OsmAnd online tiles as the Main map source.
2. Change any information in the OSM
3. Click download map. 
4. The tiles should be updated and new information appears, but it does not appear

Workaround from the support request:
To get tiles map (OSM, CYCLEOSM, etc etc) refreshed the only alternative way is to clear the tiles manually, so, then by browsing the map you can get new tiles, but this is a too long way specially because you loose all the tiles....

### Your Environment
OsmAnd Version: 4.2.6
Android/iOS version: OsmAnd+
Device model: Sony Experience XZ 1

**Maps used (online or offline):**   online
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by Zirochkabila** [comment]
Was able to reproduce on version 4.2.7 - the Download map function didn't update the map

**Comment by dmpr0** [comment]
<table style="width:100%">
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/177962221-704c2489-f866-4561-85f3-2215367c0185.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/177962186-664c26dd-3f78-48c4-807e-a7fa2d522866.png"  width="300" height="auto"/> </td>
  </tr>
</table>
