### ISSUE TITLE
The name of the apartment complex is cut off when OpenGL is activated

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#14797]
### Description
The name of the apartment complex is cut off when OpenGL is activated
https://osmand.net/map/?pin=48.799474%2C9.171427#18/60.06061/30.44444

### Steps to reproduce
Search > 60.06065° N, 30.44382° E

### Actual result
The name of the apartment complex is cut off
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/177999387-286c43fa-75bf-43ac-8cf5-c264bd6a853e.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
The name of the apartment complex is displayed fully (OpenGL rendering off)
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/177999809-8d22ed7a-44bd-4404-bf13-cffba0f9a304.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Your Environment
OsmAnd Version: 4.3.0#13634mqta, released: 2022-07-08
Android/iOS version: Android 11
Device model: POCO X3 NFC

**Comment by Nine-Tailed** [comment]
[duplicate](https://github.com/osmandapp/OsmAnd/issues/14243)
