### ISSUE TITLE
Don't use rcn_ref for motor vehicle navigation

### ISSUE THREAD

**Issue by fred702** [osmandapp/Osmand#1479]
Currently cycle route ref values are added to the ref=* during navigation.

For example when turning onto [this](https://www.openstreetmap.org/way/20641917) way it displays and speaks "US 4 9".  Expected output is "US 4". For motorists this can be confusing as cycle routes are not relevant to them.

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/fb4a3872442383371702cde483a1930fbfeca9ec

**Comment by fred702** [comment]
Great, thanks!
