### ISSUE TITLE
Part of the route is not displayed when navigating the GPX

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#14801]
### Description
The part of the route is not displayed when navigating on the GPX, and after a while, straight line on the route appear and disappear
[Archive.zip](https://github.com/osmandapp/OsmAnd-iOS/files/9070883/Archive.zip)

### Steps to reproduce
Download GPX > Select Walking profile > Start navigation

### Actual result
The part of the route is not displayed when navigating on the GPX, and after a while, straight line on the route appear and disappear
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/177965712-a5299d35-8252-4184-9bd0-4ba9eb213df0.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/177965716-0d3bf20d-8504-448a-9dbe-d10ea23a8100.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
Navigating through GPX without crashing the route

### Your Environment
OsmAnd Version: 4.2.3
Android/iOS version: iOS 15.5
Device model: iPad mini 4

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2108
