### ISSUE TITLE
address search fails to find streets that are on the map

### ISSUE THREAD

**Issue by johndh** [osmandapp/OsmAnd#14804]
### Description
The search function fails to return results for streets that exist on the map, even if they are very nearby.
This seems to happen most often to residential streets that I've recently added to the database in Vespucci. Peace Road in Columbia Tennessee is an example.

### How to reproduce?
Search, address, Peace Road
https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=1014025901&class=highway

### Your Environment
OsmAnd Version: 4.1.11
Android/iOS version: 11
Device model: Motorola One 5G Ace

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
United States, Tennessee, in the local tab it says May 31 but the live tab says July 8
<img src="https://user-images.githubusercontent.com/692397/178061580-f95e573b-4df0-4f82-8ae8-ebe1360e7e3e.png"
 width="25%" /> <img src="https://user-images.githubusercontent.com/692397/178061582-d4857eaf-7b50-4fc3-b7f3-242757508b10.png" width="25%" />

**Comment by vshcherb** [comment]
This issue is probably irrelevant cause new maps are not generated that should contain changes - https://www.openstreetmap.org/way/1014025901. live doesn't support address  changes
