### ISSUE TITLE
Moving direction uses compass direction instead?

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#14802]
### Description
If I navigate with car, the map just turns (rotates)  heavy left and right.
It looks like instead of moving direction compass direction is used (with a compass with very bad or poor input).
Can anybody please check this ?

Edit:
With moving direction and when not navigating the map  just turns (rotates)  heavy left and right in the same way like in compass direction.
Edit-2:
With moving direction: If I rotate the DEVICE then map stays with the ground, like it does when compass is selected.
So I think setting moving directing uses setting compass.

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#34346m, veröffentlicht: 2022-07-08
Android version: 8 + 10
Device model: Samsung tab S5e, S7

**Comment by vshcherb** [comment]
Not aware of this, there was recently bug discovered that map orientation threshold didn't work, so iit's fixed and you might have a setting setup to very high value and you experience filter of that setting.

**Comment by pebogufi** [comment]
No improvement with OsmAnd~ 4.3.0#34352m, veröffentlicht: 2022-07-10.
Can you give me a hint where i can change the value of that thershold, i did not find any setting in the app. Or - can i change a value when export settings to osf, rename to zip, ...
The problem started after OsmAnd~  4.3.0#34327m.apk 05/07/22.
Uninstall, clear cache, ..., new install is no option, i am travelling and use osmand every day for hiking, cycling and car navigation.

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/14681 (Original issue)

**Comment by Zirochkabila** [comment]
### Description
The case was reproducible
When you select Movement direction, the map rotates as if the Compass direction was selected

### Steps to reproduce
Show geolocation > Chose Browse map profile > Menu > Configure profile > General settings > Map orientation > Movement direction > Apply

### Actual result
The map is rotating

### Expected result
The map rotates only in the direction of movement

### Your Environment
OsmAnd Version: 4.3.0#13642mqta, released: 2022-07-11
Android/iOS version: Android 11
Device model: POCO X3 NFC
