### ISSUE TITLE
cycling osmc symbol and REF not working properly

### ISSUE THREAD

**Issue by Louis-LJ** [osmandapp/OsmAnd#14807]
hello, 

for cycling

- the osmc symbols for cycling are not displayed at the same zoom as for the osmc hiking.

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/79785663/178121724-5c6ae9ab-0a93-4ca0-9856-c6dd19b5c4b7.png"  width="350" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/79785663/178121731-20b6e7ce-4804-451f-9d43-1779d36ed6a6.png"  width="350" height="auto"/> </td>
  </tr>
</table>  

-the REF of the routes are not rendered with a panel like cyclOSM . It would be much more readable if it was displayed as sue cyclOSM or waymarkedtrails.

seeing the long-distance bycicle routes on the map from zoom 6 would be great! if not, what lines of code should be changed to make it appear on a custom rendering?

**Comment by Dima-1** [comment]
https://www.openstreetmap.org/relation/12548505

[Request](https://github.com/osmandapp/OsmAnd-tools/pull/496)
