### ISSUE TITLE
Map stop rendering (gray screen) after often device rotation

### ISSUE THREAD

**Issue by tbicr** [osmandapp/Osmand#1480]
When direction on after often rotations map stop rendering (show gray screen) until restart up: https://youtu.be/Ndl5lWgUygk.

OsmAnd_ 2.1.1
Android version 5.0.2
Sony Xperia Z3 Compact D5833 Build 23.2.A.1.62

**Comment by vshcherb** [comment]
Yes, that's a known issue for 2.1. We fixed it already in nightlies and now testing. There is a memory leak of screens while rotating it.
