### ISSUE TITLE
Osmand 4.3 Nightlies Crash

### ISSUE THREAD

**Issue by MAlfare** [osmandapp/OsmAnd#14809]
### Description
Since five days all nightly builds of android_full crash immediately after start.
Last, maybe second last,  working  version: 4.3.0#34331

### How to reproduce?
Update via  "Builds", run

### Your Environment
OsmAnd Version:  4.3.0#34331 (last working)
Android/iOS version: 8.10
Device model: Moto G4 Plus (XT1642)

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by alex-osm** [comment]
Please attach crash log

**Comment by MAlfare** [comment]
Would like to, but there is none :-(
All I can find is an ancient  Logcat Buffer from
07-10 14:15:33

**Comment by MAlfare** [comment]
After installing a new nightly, immediately after start, I get
`OsmAnd~ wurde beendet`
Next try to start:
`OsmAnd~ wird wiederholt beendet
x App schließen`
OsmAnd folder doesn't contain any helpful information (logs).
Wish I could give more information.

**Comment by MAlfare** [comment]
OsmAnd-master-nb-2022-07-05.apk (which I cannot find any more on https://download.osmand.net/night-builds/)
is the latest, I can use. It installs: 4.3.0#34331m.
All newer has the problem also mentioned in #14861

**Comment by MAlfare** [comment]
One day, a long time ago, the app worked again, and I updated daily, more or less.
Until today 2022-11-24
4.3.0#349992m  crashes again, so does its successor.
I downloaded:
[OsmAnd-master-gnb-2022-11-23.apk]
which installed 
4.3.0.#349991 and this is working.

**Comment by stephan75** [comment]
Similar Problems here on a Moto G6 XT1925-5 device with stock android 9:

Last nightly that works here with OpenGL support is file Osmand-master-opengl-nb-2022-07-04 with 165MBytes filesize.
It installs successfully as Osmand~4.3.0#13625mqta ... OpenGL rendering works fine within.

All other nightlies from later do **not** work any more, either they crashed immediately after starting the app, or the last five weeks, they even fail while installing the apk file manually: "Die App wurde nicht installiert" or "The app has not been installed" (freely translated)

So I even don't have any chance to produce an Osmand's log file ... 

**How can I inspect this failure while installing?** 

Please provide step-by-step instructions. 
(I know that there is anything like debugging via adb ... but never did this on my own. Please help.)

**Comment by sonora** [comment]
Have you tried completely uninstalling and reinstalling? Make sure you save your data by first renaming the osmand data folder (make sure it is the right one withh all your maps and personally created data, there can be several on your device!). Does OsmAnd then start ok?

**Comment by stephan75** [comment]
@sonora 
I did the steps you mentioned exactly like that, especially reinstalling and renaming the folder net.osmand.plus ... I experienced the startup screens of Osmand where it asks you to download a very first map file ... but the app terminated one or two seconds after that screen, even without any user interaction.

Any further hints?

**Comment by sonora** [comment]
Ok, assuming you installed a new release or nightly, that essentially rules out my first guess that it's related to a data or cache file.

The similar issue linked above is on a rather special processor model, but your's seems not. Still may be an issue with some library - can't say more for the time being.

**Comment by hvdwolf** [comment]
> while having installed the file `OsmAnd-opengl-arm-nightly.apk` from 09. Dez. 2020 with filesize 177.738.983 Bytes ...

I assume you mean 09 December **2022**? If not, drop the 2020 version and get the latest.

Do you use special selfmade renderings or profiles? OsmAnd using OpenGl seems to crash on rendering some "strokewidth" statements (as of line 150). If so, remove all your self-created "stuff" and restart with a clean OsmAnd.

**Comment by sonora** [comment]
Exactly. That's why I first suspected an issue in the data folder. Once a clean installation of a current OsmAnd build runs, you can go back to your old dara folder and identify the defunct file, could e.g. be a map or a custom render file.

**Comment by stephan75** [comment]
Finally I succeded in a clean fresh install in the following way (of course with that apk file from 2022, not 2020):

1. Use Osmand's in-app feature to create a backup or map markers, favourites, tracks, settings
2. Instead of including the large offline map files you have in use into that backup, copy those files manually to a secure place on your device or sd-card. Thus you have a small handsome backup osf file.
3. Remove some apps from your device to have more free space in RAM ans on device memory,
4. If you have an old Osmand folder on your device or sd-card in android/data/net.osmand.plus ... rename it like mentioned above
5. I even turned on flight mode on my android device,
6. and the I even had to try starting that fresh Osmand installation several times to get it without app termination.
7. Restore settings, favourites etc. with in-app retsore feature,
8. copy back large map files manually in the freshly created Osmand folder on device or SD card.

@MAlfare ... maybe you can try anew like that?

**Comment by MAlfare** [comment]
I will not, because Osmand is working at the moment.
As earlier written, it started working some day and stopped some time later again.
At the moment, I am on:
Osmand~ 4.4.0#35119m from yesterday.
I did not change anything, beside my strategy:
After each  successful build upgrade, I save the osmandToInstall,apk, so I can install this when an upgrade goes wrong.
And I try new builds, until one works.
