### ISSUE TITLE
Opengl: Maps do not render correctly

### ISSUE THREAD

**Issue by bytes101** [osmandapp/OsmAnd#14818]
### How to reproduce?
[Loading](url) Stored save map only a few tiles are displayed they load in non opengl setup and on other mapping nav, apps

### Your Environment
OsmAnd Version:4.2 

Android/iOS version:12,10
Device model:
Xcover5 Doggee s59pro
**Maps used (online or offline):**   offline(my own maps )
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition [date.](url)
![Screenshot_20220711-093510_OsmAnd](https://user-images.githubusercontent.com/95884760/178223488-f05d4986-69ff-45bc-bf6c-cedc9966ea66.jpg)

**Comment by vshcherb** [comment]
It looks like your issue related to already fixed https://github.com/osmandapp/OsmAnd/issues/14483. It's coming in new 4.2 version

**Comment by bytes101** [comment]
this bug is on the lastest bata release
