### ISSUE TITLE
Bug selecting POI categories

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#1481]
Please have a look at the attached screen shots. Clicking the first check box does not set all check marks but only Wikipedia.
Another problem is that trying to select all subitems of some categories unselectes other categories.

Found with OsmAnd+ 2.1.1.

![screenshot_2015-07-17-15-55-02](https://cloud.githubusercontent.com/assets/6921696/8765457/0a72822a-2e0d-11e5-8dfc-b305e44e8635.png)

**Comment by sonora** [comment]
Yes, thanks, this is already corrected and will be available in the next release. - Hardy

**Comment by vshcherb** [comment]
I think that bug is the most critical that we need to release. We can't release soon, we need to fix more open issues beforehand.
