### ISSUE TITLE
Road is missing 

### ISSUE THREAD

**Issue by Louis-LJ** [osmandapp/OsmAnd#14811]
### Description
<img src="https://user-images.githubusercontent.com/79785663/178142878-a4de2054-f5c0-4d26-8010-431b4b0d014c.jpeg" width="25%"/> <img src="https://user-images.githubusercontent.com/79785663/178142890-3ac4c5a5-099a-4435-ac96-7a5212970e60.jpeg" width="25%"/> <img src="https://user-images.githubusercontent.com/79785663/178142896-108dd110-1430-46f6-a6e7-0752dc4ed568.jpeg" width="25%"/>

### Your Environment
OsmAnd Version: 4.2.3
iOS version: 15.5
Device model: iPhone 11 Pro 

**Maps used (offline):**   
Any style map.

**Comment by Zirochkabila** [comment]
Only when OpenGL is enabled
43.281481, 3.107158
OsmAnd~ 4.3.0#13872mqta, released: 2022-10-16


https://user-images.githubusercontent.com/104760013/196026268-845f859e-c8f7-42a3-914b-55c2f21971dc.mp4

**Comment by vshcherb** [comment]
New basemap should be available this week.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14151mqta, released: 2023-02-03
Done in maps for February 1 - 2023


https://user-images.githubusercontent.com/104760013/216644802-eea6b87b-e8b0-4390-8f01-943b2864aa92.mp4

**Comment by dmpr0** [comment]
Coordinates to test:
Location: geo:43.28270,3.09837?z=12
https://osmand.net/map?pin=43.282702,3.098374#12/43.2827/3.0984

**Comment by vshcherb** [comment]
OpenGL rendering doesn't work Android / iOS (no basemap, only Occitania region maps, Legacy rendering works.

**Comment by Zirochkabila** [comment]
4.4.6.7
Occitania region with overview map and without - Done
