### ISSUE TITLE
La Rochelle - ground on the sea

### ISSUE THREAD

**Issue by Louis-LJ** [osmandapp/OsmAnd#14810]
https://www.openstreetmap.org/#map=11/45.5557/-0.9908

### Description

<img src="https://user-images.githubusercontent.com/79785663/178142635-9dbcd88c-51cf-482f-a599-168e3b367a35.png" width="25%"> <img src="https://user-images.githubusercontent.com/79785663/178142643-207a6b0d-94b6-416b-90ba-8614b1bf0416.png" width="25%"> <img src="https://user-images.githubusercontent.com/79785663/178142651-e24ef7b5-1a81-4c24-adb4-1e7eeeadde8d.png" width="25%">

### Your Environment
OsmAnd Version:4.2.3
iOS version: 15.5
Device model: iPhone 11 Pro 

**Maps used (offline):**   
Any style map.

**Comment by xmd5a2** [comment]
Fixed with new basemap
![Screenshot_2022-08-08_10-00-04](https://user-images.githubusercontent.com/5829014/183358526-a3103808-6181-430c-bfb7-61e1f7c71834.png)
