### ISSUE TITLE
Low FPS

### ISSUE THREAD

**Issue by Ahmadhosseinbor** [osmandapp/OsmAnd#14813]
Description
The FPS on my phone is very low, I tested the FPS on several phones and there was no problem

![Screenshot_20220710-172809_OsmAnd+.jpg](https://user-images.githubusercontent.com/44550501/178146111-1568c5b9-8222-4a10-889c-e77431260b39.jpg)

Your Environment
OsmAnd Version: 4.2.6
Android/iOS version: 12
Device model: A32 4G

**Maps used (online or offline):**   
offline

**Comment by vshcherb** [comment]
Please try to enable OpenGL rendering in Development settings and restart the app

**Comment by Ahmadhosseinbor** [comment]
> Please try to enable OpenGL rendering in Development settings and restart the app

OpenGL is enabled

**Comment by vshcherb** [comment]
It's probably not supported then Search / Rendering is only for non-opengl version.
