### ISSUE TITLE
Lost route Cycling

### ISSUE THREAD

**Issue by Louis-LJ** [osmandapp/OsmAnd#14812]
### Description
<img src="https://user-images.githubusercontent.com/79785663/178142929-e580ea1f-261a-474c-8660-6d9fee0aab54.jpeg" width="25%"/> <img src="https://user-images.githubusercontent.com/79785663/178142934-b46e49ac-c052-4284-a2c8-4822d7dbd9ee.jpeg" width="25%"/> 

### Your Environment
OsmAnd Version: 4.2.3
iOS version: 15.5
Device model: iPhone 11 Pro 

**Maps used (offline):**   
Any style map

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/14811

**Comment by xmd5a2** [comment]
Roads dynamically disappears to increase performance and to improve map readability. You can use "More details" rendering style option.
