### ISSUE TITLE
Rendering of maps was slowed down and the shade of Favorites changed

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#14828]
### Description
After transferring data over the wire from one device to another, map rendering slowed down and the shade of Favorites changed

[Archive 2.zip](https://github.com/osmandapp/OsmAnd/files/9091560/Archive.2.zip)

### Steps to reproduce
Copy application data to a computer using a memory card > Transfer data via cable to a new device > Open files using OsmAnd > Save data in application memory 

### Actual result
Rendering of maps was slowed down and the shade of Favorites changed

### Expected result
The cards are displayed for a few seconds, and the shade of the Favourite remains the same

### Your Environment
OsmAnd Version: OsmAnd+ 4.2.6 
Android/iOS version: Android 12
Device model: Samsung S22Ultra

**Comment by mp13mp13** [comment]
Hi everyone
 It is my problem.
 What I did?
 On July 30, 2020, the Samsung Galaxy S9 + fell into very cold water when the air temperature was around 38 °.
 The display touch and charging stopped working on the phone.
 I decided to recover the data from it in the future, when this model is already cheap, to purchase another as a part donor.
 In May 2022 I purchased the same phone with a broken display, but efficient battery charging.
 I went to the phone service, where after translating a few parts, I managed to copy a 1: 1 copy of the phone to the SD card.
 I took both phones home and found that my old one still had about 70% of the battery, so I decided to copy the data to my PC using a MicroSD card.  I recovered all the data I was interested in, including the gpx route files in the Import and Rec folders and the favorites file.
 I sent this data via a cable to my new S22Ultra phone, opened it in OsmAnd, and then saved it to the application memory.
 After that, the loading of maps slowed down a lot.
 The old favorites points have different shades of icon colors than the current ones.
 I have a new phone from June 1, before uploading the recovered data, the operation of the application and loading maps was satisfactory.
M1roN

**Comment by vshcherb** [comment]
Looks like the app is using too much memory, so it runs GC too often and probably creates problem. Please try to use less overlays or features and let us know if it works smoothly after phone reboot.
```
07-08 17:06:29.786 11038 11046 I net.osmand.plu: Background concurrent copying GC freed 1381(411MB) AllocSpace objects, 0(0B) LOS objects, 19% free, 100MB/124MB, paused 1.151ms,14us total 130.746ms
```

The issue will be closed cause for now we don't have any information what to fix.
