### ISSUE TITLE
Common appearance for POIs in My Places

### ISSUE THREAD

**Issue by candlewithhare** [osmandapp/OsmAnd#14833]
### Description
When an existing POI is added to a folder in My Places, the appearance is no longer changed to the category default. This used to be the case until several weeks ago, it changed with one of the latest updates.

### How to reproduce?
Create a folder/category in My Places / Favorites and define a default appearance (logo and color). 
Define a new MyPlace with a different appearance. Now add this POI to the above category: the appearance of the POI stays the same, but should be changed to the category default.

### Your Environment
OsmAnd Version: 4.2.6
Android/iOS version: 8.1.0 (Android)
Device model: SM-G930F (Samsung Galaxy S7)

**Maps used (online or offline):**  offline
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by tradavyvy** [comment]
This is linked to the (closed) issue
#14245

**Comment by vshcherb** [comment]
I think it's already fixed with 4.2.7 (tested with change default appearance for category).
