### ISSUE TITLE
Add showing "ref" value of "highway"="motorway_junction" for exits (turns)

### ISSUE THREAD

**Issue by tbicr** [osmandapp/Osmand#1483]
In USA on roads use exits numbers: https://en.wikipedia.org/wiki/Exit_numbers_in_the_United_States and https://en.wikipedia.org/wiki/Exit_number. They are useful enough (google maps show it on their routing for example), but not shown on osmand direction. On OSM it marked as http://wiki.openstreetmap.org/wiki/Tag:highway%3Dmotorway_junction on node where main highway and link start branching. It will be great to add this info for turn info.

**Comment by vshcherb** [comment]
Duplicate https://github.com/osmandapp/Osmand/issues/1347
