### ISSUE TITLE
The app freeze when you click on the address search icon (magnifying glass). Android Auto

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#14834]
### Description
When using OsmAnd in Android Auto but when you press the address search button (magnifying glass), the app freeze.
The only way to start the navigation is to select a favorite place.

### Steps to reproduce
Start Android Auto > Press the address search button 

### Actual result
The app freeze

### Expected result
The search bar is open at

**Comment by Danieleser** [comment]
Below my environment where I have had the bug:

Osmand version: OsmAnd+ 4.2.6 (release 2022-06-29)
Android version: 10
Smartphone: Samsung Galaxy Note 9 (SM-N960F) with One UI 2.5

I use the phone in Andorid Auto with the cable connected (not wireless).

This is a short video that reproduce the bug:

https://user-images.githubusercontent.com/80455559/179172117-0386c462-e444-4e9e-8d82-04a9bebfb9c6.mp4

**Comment by vshcherb** [comment]
Not reproduced so far
