### ISSUE TITLE
Configure map: boat and OSM settings 

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#14848]
### Description
For some reason, the boat profile is missing some of the settings for OSM.

![Screenshot_2022-07-13-20-05-29-074_net.osmand.plus.jpg](https://user-images.githubusercontent.com/12549744/178793155-287488aa-0763-42ad-860f-8c6929a0d8fc.jpg)

and for example the profile of a pedestrian
![IMG_20220713_200606.jpg](https://user-images.githubusercontent.com/12549744/178793284-257641c4-e166-4b75-85b1-4a5b637ef788.jpg)

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13645mqta, released: 2022-07-13
Android version:
Device model: poco f3

**Comment by vshcherb** [comment]
it's not supported by map style - OSM settings depend on map style

**Comment by Nine-Tailed** [comment]
Maybe then it is worth adding it to the map style?
I have enabled all profiles and only the boat is missing these settings. Therefore, I thought it was a bug.

**Comment by vshcherb** [comment]
Each style author has own settings to be added, I think it's very low priorities for sailors but if they request we will consider
