### ISSUE TITLE
new aviation mode?

### ISSUE THREAD

**Issue by casiosmu** [osmandapp/OsmAnd#14845]
### Description

See images. After a car route is calulated and started, some time later (seconds to minutes) the route changes and shortcuts from somewhere directly to the destination.

After stopping and restarting the routing all went well again.

### How to reproduce?

It occured twice in the last month on completely different areas of germany (Airport Düsseldorf to Siegen and Airport Ballenstedt to Siegen). Cannot see how to reproduce.

### Your Environment
OsmAnd Version: 4.2.6  (2022-06-29)
Android version: 11
Device model: OnePlus Nord 2

**Maps used (online or offline):**   

offline.

![Screenshot_2022-07-10-09-28-20-92_014aeb6b5e04ee7837dcdaecc5244511](https://user-images.githubusercontent.com/5816476/178784604-51d27bc1-eb94-42ad-89ea-d256597b2476.jpg)
![Screenshot_2022-07-10-09-28-01-82](https://user-images.githubusercontent.com/5816476/178784973-45f28de0-05a0-42bd-8760-d3dfc11c1ee8.jpg)

**Comment by scaidermern** [comment]
Looks a little bit like #14613?

**Comment by vshcherb** [comment]
4.2.7 released
