### ISSUE TITLE
Mass changing appearance of tracks with one click

### ISSUE THREAD

**Issue by eksplorator** [osmandapp/OsmAnd#14846]
Hello Good People!

Menu-> My Places-> Tracks -> Let's say I have 300 tracks in 3 catalogues: 100 is hiking, 100 is biking and 100 is kayaking. 

Now I want to change appearance of the tracks (e.g. thickness, colour or start/finish icons) with one click in each of the catalogues.  For example I would like to mark hiking in green, biking in brown and kayaking in blue.

Menu-> Configure map -> Tracks -> And now there is 300 tracks without catalogues therefore it is impossible to change appearance with one click and it is necessary to change appearance each of 300 tracks.

Thank you in advance and regards!

**Comment by vshcherb** [comment]
You can now change it Configure Map -> Change width / thickness. Though you need to make them visible on the map first.
