### ISSUE TITLE
Coast rendering broken on Isoa di San Pietro, Italy

### ISSUE THREAD

**Issue by dafadllyn** [osmandapp/OsmAnd#14857]
### Description

Rendering of water (sea) and land is broken on [Isola di San Pietro, Italy](https://www.openstreetmap.org/?mlat=39.1403&mlon=8.2741#map=12/39.1403/8.2741): depending on the zoom level, land is displayed on part of the sea, water is not rendered or water is rendered on part of the land. Some examples:

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/79018751/178987071-98e7eca5-fa6e-4d07-866e-a94467677ee3.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

[Former salt works and harbour of Carloforte](https://www.openstreetmap.org/#map=15/39.1399/8.3095): half of the harbour is rendered as land. Besides, there's a fine grey line on land that shouldn't be there.

----

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/79018751/178987159-9ef8108c-0102-45b7-8a7e-64b7da134a46.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

Same place, but zooming out by one level: the former salt works disappears. Again a grey line.

----

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/79018751/178987173-6ff835ab-3fc0-4710-9250-3e3154110435.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

Zooming out by another level: the harbour appears, but the former salt works is still not rendered.

----

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/79018751/178987182-a30260e6-5f25-4823-ba5a-923b90f4814b.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

[Capo Sandalo](https://www.openstreetmap.org/#map=16/39.1450/8.2268) under water.

----

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/79018751/179006261-95bad0c6-aab9-4f73-8489-22670f01fa33.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

Same place, zooming out by one level: the cape is still under water, but scrub appears.

----
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/79018751/178987199-e2cbde6b-0f41-4525-883a-85c621a51b53.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

Zooming out by another level: now the cape is correctly rendered as land, but in return some bays are rendered as land. There's again a thin grey line.

----

### How to reproduce?

See location links above.

### Your Environment
OsmAnd Version: 4.2.6
Android/iOS version: Android 10
Device model: Nokia 6.1

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

* Europe > Italy > Sardinia > Standard map, 1 July 2022

The problem also occurs with live updates.

[OsmAnd bug.log](https://github.com/osmandapp/OsmAnd/files/9112720/OsmAnd.bug.log)

**Comment by Zirochkabila** [comment]
Your case was tested with device version 4.3.0#13647mqta, released: 2022-07-15 - managed to reproduce, the rendering bug is present.

https://osmand.net/map/?pin=48.799474%2C9.171427#12/39.1416/8.2748

**Comment by vshcherb** [comment]
This issue is reproduced with legacy & opengl rendering it looks like there is a broken coastline cause it's easily reproducible. I suspect that there is a "hidden coastline" inside island actually cause this algorithm was pretty good tested.

**Comment by vshcherb** [comment]
Opengl: The bug is reproducible ..9 - up to 13 (including) zoom
Legacy: bug reproducible on all zooms

**Comment by xmd5a2** [comment]
Part 2 of issue is not reproducible with new OSM data anymore
