### ISSUE TITLE
Constantly Taking Sideroads

### ISSUE THREAD

**Issue by seniorm0ment** [osmandapp/OsmAnd#14854]
# Description

Everytime I nav, OSMAnd always wants to throw me down neighborhood roads, side roads, and when I choose not to take that route, and I take a highway it will sometimes try to take me off the highway and back onto roads instead of just continuing on the highway. Eventually if I sit on the highway for a little longer it always seems to start working properly and take me to my intended exit.
This is insanely frustrating, even if the side roads might be slightly shorter, I want to just hop on the main roads and highways.

The other day I went to an unknown area, and I was trying to leave to go home. I took me through stop and go city. Instead all I had to do was go right, follow the way I came and jump right back on the highway. Extremely frustrating.

This happens pretty much most of the time I am navigating and I don't know why.

# How to reproduce?

Load app, start navigating, let it run.

# Your Environment

OsmAnd FDroid, 4.2.6
Android version: 12, Graphene OS
Device model: Google Pixel 6 Pro

# Maps used (online or offline):

Online, although same issue present with offline.

**Comment by TheSnoozer** [comment]
Just a thought: Have you disabled highways in your profile? Besides that I feelthat would be hard to troubleshoot without start/end points where such behaviour can be reproduced.

**Comment by vshcherb** [comment]
Not clear what route & what situation are we talking about?

**Comment by seniorm0ment** [comment]
I do not see any avoid motorway option?
I see a prefer fuel efficient way which was selected, however the highway would've been the more fuel efficient way in all my scenarios.

Also I didn't post routes out of privacy concerns.

**Comment by TheSnoozer** [comment]
Depending on the road type the highway could actually be more inefficient.
For a quick example (sorry for the screenshot in german (with liters and km)):
![image](https://user-images.githubusercontent.com/6849390/179010006-3846b5b5-34f6-4e9d-92d5-1df135fbbd5d.png)
But essentially Autobahn = Highway = consumption 5,5 L per 100km (1.2 gallons per 62 miles, or rougthty 2 gallons per 100 miles). On a Landstraße = country raod the consumption is less with 4,6L per 100km.

Without a road (star end point) we are only left guessing if your assumptions are correct, but maybe unselect the "fuel efficient way" option when you actually want to use the highway...

**Comment by seniorm0ment** [comment]
It's not taking into account traffic I presume either which in city with lights it's stop and go, where the highway is straight route and not as packed. 

But either way this could be easily resolved with an alternative route option, but I literally have no way of choosing. I have to have some idea of where I am, and then follow my own way until it magically reroutes to where I need it too.

**Comment by unforgettableid** [comment]
@TheSnoozer:

### Efficiency

When considering L per 100 km, lower numbers are better. Fewer liters equals more efficiency.

When considering miles per gallon, higher numbers are better. More miles equals more efficiency.

So, the second set of screenshots you posted, regarding Toyota and Ford cars, suggests that highway driving is more efficient than city driving.

### Motorways and interstate highways are much safer than country roads

Maybe German country roads are more efficient than German highways.  Still, both [in Europe](https://www.brake.org.uk/get-involved/take-action/mybrake/knowledge-centre/road-design/rural-roads) and [in the US](https://www.npr.org/2009/11/29/120716625/the-deadliest-roads-are-rural), motorways and interstate highways are both much safer than rural roads. Safety is more important than efficiency.

**Comment by unforgettableid** [comment]
@seniorm0ment:

In OsmAnd 4.x, please tap Menu > Settings > Driving > Navigation settings > Route parameters > Avoid roads.

A.) Is "No motorways" enabled?

B.) Is any other road-avoidance option enabled?

Now, please tap Menu > Settings > Driving > Navigation settings > Route parameters > Prefer...

C.) Is "Prefer unpaved roads" enabled?

**Comment by seniorm0ment** [comment]
Yeah I found it the other day. No motorways is disabled, and Prefer unpaved is disabled.
