### ISSUE TITLE
Roundabout navigation preview highlight needs invertion

### ISSUE THREAD

**Issue by jeenuv** [osmandapp/Osmand#1485]
I drive in UK (that's to say on the left) and I notice that the navigation preview at the top-left corner of the screen for roundabouts displayed inverted - i.e. the yellow highlight is not the part you drive on, but where you don't!

![screenshot_2015-07-20-08-43-09](https://cloud.githubusercontent.com/assets/92313/8771681/535594e6-2ebc-11e5-8dc1-80b705d33407.png)

In the screen shot above, it's directed to take a first exit, but the highlighted preview is as if I'm driving on the right and were to take the second exit! The correct display would be highlight the bottom-left part in yellow that's not at present so: i.e the masked-off part of the round about is the one that needs to be highlighted.

The location coordinates are visible on the screen shot, but I think I've always noticed it so everywhere.

**Comment by vshcherb** [comment]
For now you should change your Driving Region manually in the settings, we plan to do it automatically.
