### ISSUE TITLE
Add filter "parking:fee=yes/no" for the charging station POI

### ISSUE THREAD

**Issue by tiptoptom** [osmandapp/OsmAnd#14860]
# 🚀 feature request

### Description
It would be convenient if you could filter not only by fee=* but also by parking:fee=*, since not only the power delivery can be with and without fee but also the parking.

**Comment by sgjf4g4** [comment]
This already exist in the all 4.2 releases since https://github.com/osmandapp/OsmAnd/issues/13450 is been fixed in version 4.2. Its not related to parking. You can filter anything. Also the different plugs.

**Comment by sgjf4g4** [comment]
Thanks
