### ISSUE TITLE
Plan route. Track editing. Moving segment end point.

### ISSUE THREAD

**Issue by Velomeloman** [osmandapp/OsmAnd#14865]
### Description
Moving the end point of segment cause deleting of this point. 

### How to reproduce?
https://user-images.githubusercontent.com/109347561/179210520-94374da3-8779-4f4d-9d2e-ece7b2308a76.mp4

### Your Environment
Device : HWELE
Brand : HUAWEI
Model : ELE-L29
Product : ELE-L29RU
Build : ELE-L29 10.1.0.152(C10E7R5P1)
Version : 10
App Version : OsmAnd~
Apk Version : 4.3.0#13647mqta 4300

**Comment by Zirochkabila** [comment]
Your case was tested with device version 4.3.0#13647mqta, released: 2022-07-15 - as you can see in the video, it could not be reproduced. The point is saved.


https://user-images.githubusercontent.com/104760013/179233421-cdd81753-8698-4659-b2af-e483f2011990.mp4

**Comment by Velomeloman** [comment]
Track must have segments. Try it with not last segment.

**Comment by Zirochkabila** [comment]
Trying with the last segment - failed to reproduce.
Try to reinstall the application, but before doing so make a backup: Menu > Settings > Backup & Restore

https://user-images.githubusercontent.com/104760013/179505492-b8e73beb-6042-4647-aac6-3e8a54e0fbec.mp4

**Comment by mic140** [comment]
> 

The fact of the matter is that you need to move the last point not of the last segment, but of any other

**Comment by Nine-Tailed** [comment]
You misunderstood the problem description.
Used nightly build dated July 18th.

Steps to play.

Create two segments with 3 points each and save the track.
Select a track to edit and in the first segment move the last point of the segment and save the track.
As you can see, part of the first segment has disappeared, and the finish icon is generally sagging in the air.
After turning the track off and on, you can see that the first segment remained shorter, but the finish icon took its place.

Video in telegram channel:
https://t.me/ruosmand/104796

**Comment by Zirochkabila** [comment]
Your case was checked on the night version of the application 4.3.0#13654mqta, released: 2022-07-19 - I was able to reproduce it (the instructions are in the attached video in the commentary above).

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.3.0#13901mqta, released: 2022-10-25
When **OpenGL is activated**, the start and finish icons of the route are not displayed immediately

[Vidoe](https://github.com/osmandapp/OsmAnd/files/9858901/telegram-cloud-document-2-5384453619703619308.mp4.zip)
[logcat (16).log](https://github.com/osmandapp/OsmAnd/files/9858903/logcat.16.log)

**Comment by Velomeloman** [comment]
> OsmAnd~ 4.3.0#13901mqta, released: 2022-10-25
> When **OpenGL is activated**, the start and finish icons of the route are not displayed immediately
> 
> [Vidoe](https://github.com/osmandapp/OsmAnd/files/9858901/telegram-cloud-document-2-5384453619703619308.mp4.zip)
> [logcat (16).log](https://github.com/osmandapp/OsmAnd/files/9858903/logcat.16.log)
> 

It's described in #14866. Unfortunately closed.
