### ISSUE TITLE
Plan route. Track editing. Start&end symbols. 

### ISSUE THREAD

**Issue by Velomeloman** [osmandapp/OsmAnd#14866]
### Description
After moving start or end point need to refresh position of start/end symbol.

### How to reproduce?
https://user-images.githubusercontent.com/109347561/179213469-f3979348-f982-4852-88df-394ebfa95b44.mp4

### Your Environment
Device : HWELE
Brand : HUAWEI
Model : ELE-L29
Product : ELE-L29RU
Build : ELE-L29 10.1.0.152(C10E7R5P1)
Version : 10
App Version : OsmAnd~
Apk Version : 4.3.0#13647mqta 4300

**Comment by Nine-Tailed** [comment]
You misunderstood the problem description.
 Used nightly build dated July 18th.

 Steps to play.
 1. Create two segments with 3 points each and save the track.
 2. Select a track to edit and in the first segment move the last point of the segment and save the track.

 As you can see, part of the first segment has disappeared, and the finish icon is generally sagging in the air.
 After turning the track off and on, you can see that the first segment remained shorter, but the finish icon took its place.

 Video in telegram channel:
https://t.me/ruosmand/104796
