### ISSUE TITLE
OsmAnd+ opening incorrect Google Maps coordinates

### ISSUE THREAD

**Issue by Jurkis** [osmandapp/Osmand#1486]
There is Google Maps link https://maps.google.com/?ll=55.80637,25.374949&q=55.80637,25.374949 from G+ (https://plus.google.com/+LinasRupeika/posts/2LHc1NEDW4Q).
If i try to open Maps link from OsmAnd+ - ir opens 55.80637,0.0. NOT CORRECT
Iš i try to open Maps link from Maps.me - it opens 55.80637,25.374949. CORRECT.

**Comment by vshcherb** [comment]
Fixed
