### ISSUE TITLE
OsmAnd shows road shield twice

### ISSUE THREAD

**Issue by MetehanOzyurek** [osmandapp/OsmAnd#14863]
OsmAnd shows road shield twice. It shows street name with road shield. But there is no road shield at the beginning of the street name on OpenStreetMap.

Look at the screenshot
![image](https://user-images.githubusercontent.com/80093621/179186282-5bf89095-1517-4f87-b55e-d38f3322cb95.jpeg)

Version: OsmAnd for Android

https://www.openstreetmap.org/way/40441884#map=13/40.7278/27.3216&layers=T

**Comment by Zirochkabila** [comment]
Fixed on Android.
But, it is reproduced on iOS 4.3.0.31

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/201491375-13a802e1-7841-4f85-971d-41375007f5c5.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/201491378-ed2f008e-a0e6-4b6f-90e4-bd0802ba677a.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2313
