### ISSUE TITLE
Cannot import a map style provided as a *.render.xml file

### ISSUE THREAD

**Issue by maxspicer** [osmandapp/OsmAnd#14869]
https://osmand.net/docs/user/map/vector-maps#custom-map-style-own-map-style says "Copy *.render.xml file on devices & Open with OsmAnd". I cannot find a way to open such files in OsmAnd.

For example, https://www.openfietsmap.nl/downloads/android/osmand provides OpenFietsMap.render.xml. If open this in Android using "open with", OsmAnd is not listed as one of the apps to choose from.

I can not find any import feature in the app that will allow me to open this file from within OsmAnd.
I do not have access to the default storage folders so cannot move the file there.

OsmAnd should provide a way to import such files.

This is on a Pixel 6 running Android 12 and OsmAnd+ 4.2.6.

**Comment by dmpr0** [comment]
Hi! You can try to download a file to the device, open the **Files** app > **Internal storage** > **Downloads** > tap on file. It works on my device, when I try to open `*.render.xml `directly from **Downloads** it doesn't show OsmAnd.

<table style="width:100%">
  <tr>
    <th>Download as asection</th>
    <th>Download folder</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/179226670-96770e42-97a2-4a94-8c82-ce19c52f477e.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/179226676-2cf5f3dc-417f-453d-a26a-a4ecb48ed568.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by maxspicer** [comment]
Yes, I get exactly the same. Works from Internal storage > Download, does not work from "Downloads". I hadn't appreciated there would be a difference between these.

Note, "Downloads" does offer Garmin Connect and AlpineQuest as "open with" options but not OsmAnd.

**Comment by maxspicer** [comment]
The above work around does not seem to work an a Samsung Galaxy S9 running Android 10.
