### ISSUE TITLE
osmand bicycle does not avoid unpaved roads, even when option is selected

### ISSUE THREAD

**Issue by wolfcra** [osmandapp/OsmAnd#14877]
In my area here in France, the bicycle option in osmand insists on suggesting extremely steep and narrow paths that are even dangerous with hikers on foot, tagged in OSM simply as "path". This makes the use of the app in our mountains completely impossible.

Is there a way to solve this?

**Comment by wolfcra** [comment]
I think it's a confusion of double negation "avoid" "no unpaved" - maybe this can be just made a little more clear....

**Comment by michaelblyons** [comment]
Alternative might be "prefer _______"
