### ISSUE TITLE
Map markers are not displayed

### ISSUE THREAD

**Issue by rubasov** [osmandapp/OsmAnd#14874]
### Description

Since the last upgrade of OsmAnd I started to notice that sometimes map markers are not displayed.

When OsmAnd is started first, all markers are displayed as they should be, but after some use of the map (and switching back and forth between other apps), some of them disappear (only from the display, not from the list of markers). For example please see the following screenshots:

https://imgur.com/a/CuNfSmG

In the 1st screenshot all four markers are displayed correctly, but when I pan the map to the south, the 3 northernmost markers disapper (2nd screenshot). If I do this really slowly, then I can see that they disappear one by one (starting with the northernmost), as if crossing a line north of which the markers are not displayed. But if I pan the map again to the north, they reappear just like in the 1st screenshot (speculating: as if OsmAnd had the wrong idea of where are the boundaries of the current map view and would not render the markers when OsmAnd believes they are out of view). As I use the map (and other apps), the markers are displayed in a progressively smaller part of screen, eventually not at all.

If I restart OsmAnd, everything starts correctly again, but soon the same cycle begins.

### How to reproduce?

Unfortunately I don't have a reliable method to reproduce this bug yet. If I find one, I will add it to this ticket of course. The problem usually starts happening in the first few minutes of using the map. I believe this problem is present only since the last OsmAnd upgrade.

### Your Environment
OsmAnd Version: OsmAnd+ 4.2.6, release date: 2022-06-29
Android/iOS version: Android 10
Device model: Xiaomi Mi A2

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by Zirochkabila** [comment]
Your case was checked on the night version of the application 4.3.0#13654mqta, released: 2022-07-19 - failed to reproduce (as seen in the video). Most likely this bug was fixed and it will not be in the next update. 
But if you have more information on playback - please write.


https://user-images.githubusercontent.com/104760013/179725528-2a2be35c-30d5-4bc0-8f13-75e5760d13e5.mp4

**Comment by rubasov** [comment]
Just wanted to leave some feedback: Since receiving the next update after my bug report I have not seen this bug again. So I agree, that this bug was likely aready fixed. Thanks for the quick reaction and for the great map app!
