### ISSUE TITLE
Problem with copying widgets from other profiles

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#14873]
### Description
When copying by clicking on the buttons marked in red, a non-identical list of widgets is obtained.
<img src="https://user-images.githubusercontent.com/12549744/179354340-a2d3aa81-36ab-4fe5-835c-12faa0b58423.jpg"  width="300" height="auto"/> 

<img src="https://user-images.githubusercontent.com/12549744/179354344-4cea1f05-f7a0-45b0-9df4-ae98a66a2946.jpg"  width="300" height="auto"/> 

Video in telegram:
https://t.me/ruosmand/104398

Only copying to the button marked in green gives the correct result.
<img src="https://user-images.githubusercontent.com/12549744/179354445-b2dc25bf-4640-4c21-96dd-66801811cd1e.jpg"  width="300" height="auto"/> 

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13647mqta, Дата выпуска: 2022-07-15
Android version: 12
Device model: poco f3

**Comment by dmpr0** [comment]
# Review
<table style="width:100%">
  <tr>
    <th>Profile-A</th>
    <th>Profile-B-Before-Copy</th>
    <th>Profile-B-After-Copy</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/183418959-ec29743b-8923-4371-9a9e-c7ccaec79530.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/183418966-b0b669ae-794e-4763-bfdf-f596ea9bc46e.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/183418967-2479752c-873e-4c39-9e96-081c535b8e65.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by nazar-kutz** [comment]
**Fix of the second bug detected after UI Review**
https://github.com/osmandapp/OsmAnd/pull/15112
