### ISSUE TITLE
Request for a Per-Profile Disable of 2.5D

### ISSUE THREAD

**Issue by H--W** [osmandapp/OsmAnd#14872]
Background: I haven't been able to find a way to disable 2.5D rendering. (I do have an old phone.) I'm assuming there isn't one yet.

There are many uses for OSMAND where the 2.5D view is a problem. Sometimes; (marine navigation, aviation, route planning, especially in extreme terrain, and many others;) you need a consistent scale across the map provided by an appropriate map projection. There are expensive commercial programs and hardware for this, but in many ways OSMAND is much better.

The Ask: I would like to see a per profile control to disable the 2.5D projection.

Summary: The 2.5D projection provides a nice heads-up feature for driving. However it is inappropriate, (to the point of being dangerous,) for some other uses. Also it is (I think) pointless for scales 500m and up, at least for how I use OSMAND.

Best Rgds, -H-

**Comment by breversa** [comment]
Slightly off-topic: is 2.5D view unavailable in `OsmAnd~` (from F-Droid) 4.2.6?
