### ISSUE TITLE
hard to find where to file bugs

### ISSUE THREAD

**Issue by malenki** [osmandapp/Osmand#1488]
I had some difficulties finding a place where I could report OSMAnd bugs to. Neither on the homepage nor in the app I could finde a useful hint. This repo I only found incidentally when translating some OSMAnd-Strings.

**Comment by vshcherb** [comment]
There is contact us and support email in google play. This is a "developer" version.

**Comment by malenki** [comment]
Not everybody uses Google Play or anything else in the Googleverse.

vshcherb schrieb
am Tue, 21 Jul 2015 08:05:04 -0700:
