### ISSUE TITLE
Polygons setting in underlay's settings, is not saved when switching underlay via "quick action" button"

### ISSUE THREAD

**Issue by OsmandUser2022** [osmandapp/OsmAnd#14881]
### Description
Yes, in current osmand release former bug when polygons setting in underlay's settings was not saved after osmand restart, and after some other actions - now it saves
But...
When using "quick action" button to switch underlays: if I enable "polygons" setting in my favorite underlay, and then I switch underlay by that "quick action" button to "no underlay", and then I switch underlay back to my favorite (by that button) - then, "polygons" setting in that my favorite underlay is off.
I also suspect that "transparency" setting in settings of underlay, is not saved too when switching underlays with "quick action" button

### How to reproduce?
Make "quick action" button for underlay (let's call it "button A"), with the following settings:
Intermediate dialog: off
Add underlay: any underlay (from online map sources) - let's call it "underlay B"
Add underlay: no underlay
After "button A" is done:
Enable "underlay B"
Go to "map settings" - underlay, there enable polygons
Exit "map settings" (to the main map screen)
Use "button A" to switch underlay to "no underlay"
Use "button A" to switch underlay to "underlay B"
Go to "map settings" - underlay, there look at "polygons" setting
Enable "polygons" setting there
Exit "map settings" (to the main map screen) - and then repeat switching underlay (by "button A") to "no underlay", and then to "underlay B"
Go to "map settings" - underlay, there look at "polygons" setting

### Your Environment
OsmAnd Version: 4.2.7
Android/iOS version: 10
Device model: Honor 9A

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
Map source: offline vector maps
Underlay: online map
Overlay: online map

**Comment by Zirochkabila** [comment]
Your case was checked with version 4.3.0#13654mqta, released: 2022-07-19, and application version 4.2.7, released: 2022-07-06 - the case was reproduced successfully. 
Polygons setting in underlay's settings are not saved when switching underlay via the "quick action" button"
