### ISSUE TITLE
Add widgets Current Speed, Speed Limit, Average Speed, etc. in Android Auto

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#14885]
Add widgets Current Speed, Speed
Limit, Average Speed, etc. in Android Auto

**Comment by mdykierek** [comment]
Already reported #13413.
Speed limit is displayed when the limit is exceeded by the amount set in OsmAnd Settings.
Note that cars show current speed on the dashboard (redundant on AA)
Finally, for safety it is bad to have too much on car's display as takes more time to analyze.
