### ISSUE TITLE
Bus/railway platforms should be treated same as footpath/sidewalk for routing

### ISSUE THREAD

**Issue by mdykierek** [osmandapp/OsmAnd#14886]
### Discussed in https://github.com/osmandapp/OsmAnd/discussions/14856

<div type='discussions-op-text'>

<sup>Originally posted by **mdykierek** July 14, 2022</sup>
Consider the following route:
https://www.openstreetmap.org/directions?engine=fossgis_osrm_foot&route=50.26634%2C19.01919%3B50.26589%2C19.01888#map=18/50.26624/19.01932
It is similar to what I get in OsmAnd 4.2.6.
Yet, Graphhoper does it better (IMHO):
https://www.openstreetmap.org/directions?engine=graphhopper_foot&route=50.26634%2C19.01919%3B50.26589%2C19.01888#map=19/50.26621/19.01918

Should OsmAnd walking router consider platforms routable or mappers should consider platforms not routable and put a footpath/sidewalk next to the platform (since platform is for people to get on transportation, it definitely is possible to use it on foot).
I think Graphhoper is more reasonable. Mapping extra paths aside platforms will make the maps cluttered.

Just to let you know, I have reported exact same thing to OSRM. Here is another route to try in Berlin:
https://map.project-osrm.org/?z=17&center=52.518940%2C13.291161&loc=52.518695%2C13.287138&loc=52.519045%2C13.292073&hl=en&alt=0&srv=2

After reviewing some platforms in my area (Silesia and Poland) and giving it a second thought, I find this quite important. I also found a question 11 years old at openstreetmap.org: https://help.openstreetmap.org/questions/4450/mapping-platforms-with-regard-to-routing
Moving around cities involves passing platforms on sidewalks. Currently any platform within a footpath breaks the route badly as if there was a barrier.</div>

**Comment by mdykierek** [comment]
Sorry for not finding it before. Definitely important to all city walkers. There are tons of sidewalk platforms.

**Comment by scaidermern** [comment]
I think the penalty for platforms should be _slightly_ higher than for regular footways. Because platforms can be quite crowded with waiting passengers. So it might be better to route around them, but only if there is a _short_ detour available.

**Comment by mdykierek** [comment]
We found that the platforms are in fact routable during mentioned discussion but the cost is sky high.
The routing algorithm on the on-line map is different (luckily) than in the app (app is better) - compare this route (https://osmand.net/map?start=50.266711%2C19.018593&end=50.266345%2C19.018776&mode=pedestrian#19/50.26642/19.01944).
I'd say penalty for train platforms should probably be higher than for public transport (safety and crowd aspects).
As a human (not algorithm) I would take any bus platform (even crowded) on a sidewalk rather than crossing or walking along roadside. After giving it a second thought it has to be "more expensive" so that routing takes a footpath next to the platform rather the platform itself.
Glad to see it scheduled. Is it possible to improve it now with XML or not?

**Comment by Dima-1** [comment]
Fixed in the new map

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-resources/pull/851
