### ISSUE TITLE
Profile selection reset when relaunching app or lost when configuring map or screen

### ISSUE THREAD

**Issue by speleoluc** [osmandapp/OsmAnd#14895]
### Description

The last selected profile is not restored when relaunching OSMAnd+. This profile selection often reverts to the base profile after opening various dialogs.

### How to reproduce?

Stop and relaunch OSMAnd+. Visit various dialogs (screen or map settings, etc.) and see the selected profile change.

### Your Environment
OsmAnd Version: 4.2.6
Android/iOS version: 11
Device model: Samsung s5e tablet

**Comment by vshcherb** [comment]
This is done on purpose, you can change default profile in Global Settings.

**Comment by speleoluc** [comment]
Wouldn't it make more sense to open the app with the last used profile?

**Comment by vshcherb** [comment]
There is a setting for "last used profile", so we think restart should also get back to "normal" default state

**Comment by speleoluc** [comment]
Great! I had never noticed this extra option at the top.
