### ISSUE TITLE
Cannot choose map orientation mode if compass is set to be shown "only when map is rotated"

### ISSUE THREAD

**Issue by Max1234-Ita** [osmandapp/OsmAnd#14901]
### Description
I use to change the map orientation mode by tapping the "Compass" icon in the top-left corner of the display, so I can easily choose between "Fixed - North above", "Movement direction" an "Compass" being the latter the orientation read from device's integrated compass (if any).

Unfortunately, if I set the OsmAnd compass to be shown "only when map is rotated", I'm not able to select a different map orientation anymore, since the icon is visible -as stated by the option name- only when the map is rotated, and if I rotate the map and tap the compass icon, it switches back to "Fixed - North above" and the icon immediately disappears.

Please provide an  alternative option to select map orientation.

### How to reproduce?

1. Open menu -> Configure screen -> Compass
2. Select "_Always visible_" option
3. Go to the main screen
4. Tap several times the compass icon in the top-left corner of the screen; observe that the map orientation changes according to the selected mode (fixed -> movement direction -> Device compass -> Fixed, etc.

5. Reopen menu -> Configure screen -> Compass
6. This time, select "_Visible if map is rotated_" option
7. Go to the main screen; observe that the map is set to "Fixed" orientation and compass icon is not visible (correct)
8. Manually rotate the map by sliding 2 fingers on the display: the compass icon is now visible (correct)
9. Tap once the Compass icon; Observe that map is set back to have North above and the icon immediately disappears
10. repeat step 8 and 9, but this time try tapping the Compass icon more than once; observe that the icon disappears as soon as the first tap occurs and map orientation mode cannot be changed anymore by tapping it. 
The only way to do that is gettingh back to the -> Configure screen -> Compass menu and setting the compass to be "always visible"

### Your Environment
OsmAnd Version: 4.2.7
Android/iOS version: Android 11
Device model: Samsung Galaxy A50 (SM-A505FN/DS)

**Maps used (online or offline):**   
Offline vector map, plus raster overlay with hill shades

**Comment by pebogufi** [comment]
As soon as this freaure was provided, I selected "always visible". FOR ME everything else is not usable or helpful.

**Comment by Max1234-Ita** [comment]
The same did I, but if a feature is present, let's make it working properly :)

**Comment by mikehgentry** [comment]
It appears if you go to configure map irrespective of the setting (easiest way is to tap the profile icon).

**Comment by vshcherb** [comment]
Delay needs to be added, so it's possible to hit again
