### ISSUE TITLE
Downloads not found, please check your Internet connection

### ISSUE THREAD

**Issue by osmand511** [osmandapp/Osmand#1490]
I installed OsmAnd 2.1.1 on a Nexus 5 running Android 4.4.4, a Nexus 4 running Android 5.0.1, and another Nexus 4 running Android 5.1.1, all connected to the same Wi-Fi network. The first two work as expected, but the last one cannot see any available map downloads. The message it produces is "Downloads not found, please check your Internet connection". Occasionally during app startup it shows the "Native library is not supported on this device" error message and switches the app to safe mode. Toggling safe mode does not help. Toggling OpenGL rendering does not help.  Reinstalling the app does not help. Clearing the app's data and cache does not help. There is nothing wrong with the device's Internet connection as all other apps have no problem with Internet access. It appears that I can manually install a map and have the app use it, but Internet connectivity seems completely broken. Is there a bug causing incompatibility with Android 5.1.1?

**Comment by vshcherb** [comment]
Fixed

**Comment by osmand511** [comment]
May we please have more details about the fix? Terse information-devoid responses are not a good way to encourage end users to report bugs.

Was it a fix on the server side or a fix in the OsmAnd app? If the latter, in which version should it appear and when do we see it in Google Play for the free version of OsmAnd? How about the paid version? In the mean time, is there a workaround to enable the Internet-related functionality?

As I am brand new to GitHub and you have not provided a direct reference to a patch, I have yet to figure out how I can get more information than a claim of "Fixed".

For the sake of other folks experiencing similar problems and/or similar error messages now and in the future, what were the necessary conditions to trigger this bug? Does it pertain specifically to using Android 5.1.1? Does the device need to be a Nexus 4?

Seriously, if you don't tell us anything, then you should expect in future that someone will want to reopen this bug for a totally different problem that just happens to share similar symptoms.

**Comment by vshcherb** [comment]
I'm afraid this may not be a good way to communicate here and it might be go via support. The issue about downloads is fixed, it doesn't mean that's the only issue you experience.

"Native library is not supported on this device" definitely wrong, you better try to reinstall it, otherwise we consider that app is not functioning on your devices. In 95% cases, complete reinstall does help.

It is not clear wil we maintain issue management in a future or we will switch to mailing group approach.
