### ISSUE TITLE
Arrows for next turn disappear

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#14900]
![Screenshot_20220720-225351_Gallery](https://user-images.githubusercontent.com/95540936/180081718-66d5187e-aa49-4c9a-8f3d-11e8690893ff.jpg)
### Description
The arrows for the next turns disappear, as soon as a route is recalculated 

### How to reproduce?
Leave a calculated route. 

### Your Environment
OsmAnd Version: 4.2.6 but as I remember it was also in an earlier version 
Android/iOS version: 12
Device model: S20+

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by Rowin63** [comment]
New Experience in this case: disappeared arrows reappear again, when turning phone from portrait to landscape 👍 Until the next recalculation. Turn the phone again, arrows are back again... 😉

**Comment by Rowin63** [comment]
See the video.
Shortly before the arrows disappeared. When turning from portrait to landscape they appear again.

https://user-images.githubusercontent.com/95540936/190849773-9401dfb0-1a53-4128-a0e2-c98c0bc43d02.mp4

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/15074
