### ISSUE TITLE
Czech republic and Hungary country file are empty on local index list

### ISSUE THREAD

**Issue by Olffh** [osmandapp/Osmand#1491]
The country .obp files for Czech republic and Hungary are missing on the local indexes list
To be specific, the link to 
http://download.osmand.net/download.php?standard=yes&file=Czech-republic_europe_2.obf.zip
points to an empty .htm file instead of to a zip file. Same for the Hungary country file

**Comment by vshcherb** [comment]
In progress fixing it, will be in 10-20 hours available

**Comment by vshcherb** [comment]
Fixed
