### ISSUE TITLE
"Keep right" instead of "Turn right"

### ISSUE THREAD

**Issue by ReinerMeyer** [osmandapp/OsmAnd#14911]
Hi,
heute ist mir aufgefallen, dass statt "rechts abbiegen" die akkustische Anweisung "rechts halten" beim Routing gesprochen wurde.
Anbei ist eine Abbildung anhand welcher die Situation grafisch dargestellt ist (Neudörfl im Bezirk Mattersburg, aber direkt bei Wr. Neustadt). Es geht um eine Abbiegung nach rechts aus der Kurve heraus.

Für das Routing habe ich das Profile "Auto" verwendet, wobei die Navigationsart auf "extern BRouter (offline)" eingestellt war.

Ob die Art der Abbiegeanweisung auch vom Brouter beeinfllußt wird, kann ich nicht sagen. Daher überlasse ich erst euch einmal zu entscheiden, an welches Team mein Anliegen vermittelt gehört.

English translation:
Hi,
today I noticed that instead of "turn right", the acoustic instruction "keep right" was spoken during routing.
Attached is an illustration showing the situation graphically (Neudörfl in the district of Mattersburg, but directly near Wr. Neustadt). It is about a turn to the right out of the curve.

For the routing I used the profile "Auto", with the navigation type set to "external BRouter (offline)".

I cannot say whether the type of turn instruction is also influenced by the brouter. Therefore, I will leave it to you to decide to which team my request belongs.

Translated with www.DeepL.com/Translator (free version)

![Neudörfl bei Wr  Neustadt](https://user-images.githubusercontent.com/94683660/180434637-a3d6d314-9684-47e2-bbd5-cbf495d1394c.jpg)

**Comment by vodie** [comment]
Hallo,
die Abbiegeanweisungen werden vom BRouter generiert.
Die Abbiegeanweisung kannst du wahrscheinlich mit "assign turnInstructionCatchingRange 20" im globalen Bereich im BRouter-Profil ändern. Der Standardwert ist (wenn er nicht angegeben) mit 40 meiner Meinung nach zu groß. Eventuell muss der Wert auch weiter reduziert werden.

**Comment by ReinerMeyer** [comment]
Hallo vodie,
danke für deine Antwort.
Dein Vorschlag machte mich erst einmal ratlos, da ich nichts mit "assign turnInstructionCatchingRange" anzufangen wußte. Eine Internet Recherche brachte mich dann darauf, in einer brf-Datei diese Anweisung zu suchen. Auf meinem Handy sind etliche davon im brouter-Verzeichnis. Leider ist diese Anweisung kein Bestandteil innerhalb der Datei "car-fast.brf", wie ich sie beim Autofahren einsetze. Diese spezifische Anweisung konnte ich aber z.B. in dieser Datei finden: "fastbike.brf", also immer, wenn es um Fahrradfahren geht.
Der Hilfetext hinter der Anweisung "Within this distance (in m) several turning instructions are combined into one and the turning angles are better approximated to the general direction" gibt aber keinen Aufschluß darüber, warum "keep right" statt "turn right" verwendet wird, wie es meiner Meinung nach - s.o. - eigentlich heißen müßte.
Daher nochmals meine Frage: Welche Kriterien bestimmen die Anweisung "keep right" und welche Kriterien bestimmen die Anweisung "turn right"?
Lg Reiner

**Comment by vodie** [comment]
Hallo Reiner,
wenn "assign turnInstructionCatchingRange" nicht vorhanden ist kannst du es selbst einfügen. Das ist ein globaler Parameter und kann direkt nach ---context:global eingefügt werden.

Abgesehen vom direkten Kreuzungsbereich ist die Richtung ja eher gerade aus. Deshalb die Anweisung sich rechts zu halten. Wenn ein kleinerer Bereich betrachtet wird hat die generelle Richtung weniger Einfluss und es wird mehr die Richtung im Kreuzungsbereich ausgegeben.

**Comment by ReinerMeyer** [comment]
Hallo vodie,

erst heute habe ich die Anpassung des scripts für "car-fast.brf" ausprobieren können.
Diese Parameter habe ich angepaßt:
assign turnInstructionMode          = 3      # 3 entspricht osmand-style
assign turnInstructionCatchingRange = 40

Leider hat dies nicht geholfen an der selben Stelle, die ich oben aufgezeichnet habe. Ein Grund könnte sein, dass ca. 5 Meter vorher, also an der Stelle, wo die Kurve beginnt, geradeaus eine Service Straße abgeht, bevor die eingentliche Verkehrsstraße nach weiteren  5-10 m rechts abbiegt. Diese Servicestraße geht ein bißchen später auf diese Verkehrsstraße ab. Man würde sich ein paar Meter sparen. Hat das mit Gleichrangigkeit von highway=service und highway=tertiary zu tun?

Etwas anderes hat mich viel mehr gestört und würde einen unbedarften Benutzer von OSMAND in Verbindung mit Brouter, der sich in der Gegend nicht auskennt, sicher frustrieren. Die geplante Route war von Leobersdorf - Knoten Wr. Neustadt - S4 Richtung Mattersburg - Abfahrt Neudörfl. Beim Knoten Wr. Neustadt zweigt die S4 nach Mattersburg ab. Es gab keine Anweisung, beim Knoten nach rechts auf die S4 abzubiegen (Dieses Verhalten ist zumindest 2x passiert). Am Anfang hat die S4 eine langgezogene Rechtskurve. Mitten in der Kurve kam die Anweisung dem Straßenverlauf für 8 km zu folgen. Die S4 macht kurz nach der Ausfahrt Katzelsdorf eine Rechtskurve. Dafür muß man von der Geradeausspur über eine durchgezogene Linie sich rechts halten und dann der Kurve folgen. Jemand, der sich nur auf die Anweisungen verlassen kann, weil er die Gegend nicht kennt, erwartet hier die Anweisung sich rechts zu halten und nicht geradeaus weiterzufahren. An dieser Stelle geradeaus weiterfahren ist naheliegender als abzubiegen, weil die gestrichelte Linie rechts nicht gut zusammenpaßt mit der Anweisung "dem Straßenverlauf folgen". Auch wenn die S4 eben an dieser Stelle ein rechts halten bzw. rechts abbiegen nötig macht. Von Rechts wegen müßte man sogar entsprechend den Blinker setzen.
Ist es möglich Brouter beizubringen, mehr hilfreiche Anweisungen zu verpassen?

Lg Reiner

**Comment by sonora** [comment]
Let me close this here: This seems entirely brouter-related, hence in the wrong issue tracker.
