### ISSUE TITLE
Cannot set custom data storage folder.

### ISSUE THREAD

**Issue by Pratched** [osmandapp/OsmAnd#14916]
### Description
When changing the "Data storage folder" to a custom part like /storage/emulated/0/OsmAnd it says "Moving failed" and 
_I/O error: /storage/emulated/0/Android/net.osmand.plus/itinerary.gpx: open failed: EPERM (Operation not permitted)_ 
And nothing has changed.

### How to reproduce?
See above. (Trying this to enable cloud sync access for my tracks. Cannot access the other possible storage options due to Android 11)

### Your Environment
OsmAnd Version:4.1.11
Android/iOS version: Android 11 as LOS 18.1
Device model: Fairphone 3 with microG

**Comment by sonora** [comment]
Google policy. ä

I explained in a related Issue somewhere that under Android 11 and above there are two possible workarounds.One of them does, and the second one might inhibit hosting the app in the Play store any more.

Could only consider a 'special' compilation hosted elsewhere, which of course raises multiple issues. ;(

**Comment by Pratched** [comment]
I see, cheers for the answer :)
I managed to move it to Android/media/ which I am able to access with my nextcloud app. Dont know if I either got this from the issues here or reddit or something. (In case someone stumbles upon this problem too).

**Comment by sonora** [comment]
There are reports that using the media folder comes with a performance hit, but it seems to not affect every system...

**Comment by Pratched** [comment]
Yeah, I can confirm that. Im still on the edge on moving back to data and backup manually.
Just as an idea for a feature: Maybe there is a way to include some external backup options like nextcloud etc...
