### ISSUE TITLE
Wrong German translation for POI tourism=information

### ISSUE THREAD

**Issue by cepesko** [osmandapp/Osmand#1492]
On the map of Osmand V2.x.x any POI with tourism=information has the translation "Fremdenverkehrsamt" + name, suggesting an official office for local tourism, where in fact in most cases there is just a map, an information board or a guidepost. This sounds especially funny when the POI is in the middle of a forest or at another not inhabited place. Please remove the word completely where the tagging is not in combination with a building or an address. Or use the word "Touristeninformation" instead, which could be an office as well as some board, map or guidepost.
Or even better: create an own symbol for guideposts ("Wegweiser" in German) and for maps use the prefix map or "Karte" in German.
PS: I hope here is the right place to submit this kind of information. If not I do apologize.
Cepesko

**Comment by sonora** [comment]
Cepesko, thanks for posting this! The DE osm wiki http://wiki.openstreetmap.org/wiki/DE:Tag:tourism%3Dinformation specifies "Information für Touristen", so I will replace it by this. Thx - Hardy
