### ISSUE TITLE
OpenGL + live: Duplicated data rendered

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#14920]
With enabled OpenGL rendering and OsmAnd live duplicated data is rendered (probably old + new data).

Example:
geo:51.56373,13.00119?z=19
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/1040784/180620893-35612845-aa28-4571-8ef5-6ef6b02bc7f4.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

Both the upper and the lower path are rendered twice.

Same problem here:
geo:51.55929,12.99431?z=18
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/1040784/180621053-2980c9b1-c530-43b4-8cbd-d05f7d46d30d.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

Deleting and redownloading live data or restarting OsmAnd doesn't fix the problem.

Disabling OpenGL _or_ disabling OsmAnd live does fix the problem.

OsmAnd 4.2.7.

**Comment by scaidermern** [comment]
This also happens to other way types, to buildings etc:

geo:51.34647,12.38865?z=20
![photo_2022-07-26_13-18-48](https://user-images.githubusercontent.com/1040784/180993944-caf232ac-567f-4b67-a8ea-1572be65fdcf.jpg)

This doesn't always happen. If it doesn't happen then restarting OsmAnd immediately leads to this behavior.

**Comment by Zirochkabila** [comment]
reproduce on 4.3.0#13675mqta, released: 2022-07-28 and 4.2.7, released: 2022-07-13 versions. But just when used Live Updates

**Comment by Zirochkabila** [comment]
https://drive.google.com/file/d/1FA4_mXAUAFxbUihBtG_xzBAKDF10LcLd/view?usp=sharing

Live map

**Comment by franco999** [comment]
The same thing happens to me. It happens that live updates are not displayed or are not superimposed correctly and then you have to restart Osmand 1-3 times after which the problem disappears temporary. I use nightly build OsmAnd~ 4.3.0#13751mqta, (2022-09-03) and OpenGL on.

**Comment by 32Vache** [comment]
Still happens on 4.4.0#14151mqta

https://user-images.githubusercontent.com/42336759/216836633-0e3d50d0-1ad1-4b76-9bad-1add26867b67.mp4

**Comment by Nine-Tailed** [comment]
Another video demonstrating the problem of duplication and incorrect rendering of objects that got into the live update.
Video from ruosmand chat in telegram 
https://t.me/ruosmand/122530

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#35830m, Released: 2023-04-23
In the latest nightly version and with the latest maps updates, it was not possible to reproduce user requests - the data is displayed similarly to that on OSM, without duplication

**Comment by Nine-Tailed** [comment]
> OsmAnd~ 4.5.0#35830m, Released: 2023-04-23
> In the latest nightly version and with the latest maps updates, it was not possible to reproduce user requests - the data is displayed similarly to that on OSM, without duplication

Objects are still duplicated, but restarting helps.  Pay attention after the restart, the duplication seems to be gone, but strange bugs are observed when scaling.
OsmAnd~ 4.5.0#35835m, Дата выпуска: 2023-04-24
https://t.me/ruosmand/122930

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#35830m, Released: 2023-04-23
Can only be reproduced with Live Updates

Data on the map **before** and **after the reopening** differ
`55.70107° N, 37.36068° E`
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/234093654-d3b27ac2-13d2-4d8e-a553-335d4597f189.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/234093661-0526dd28-b93b-42e3-b479-879c6ce0f52b.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  


Entrance changes its location
`55.70084° N, 37.35867° E`

https://user-images.githubusercontent.com/104760013/234094097-f9c05da4-4b96-42ab-8c6a-790fa86418b0.mp4

**Comment by Nine-Tailed** [comment]
Good news, will have to check.

**Comment by Nine-Tailed** [comment]
The problem seems to be unresolved (OsmAnd~ 4.5.0#35904m, Дата выпуска: 2023-05-07).
Link to one of the houses with rendering issue: https://www.openstreetmap.org/way/404783647
https://user-images.githubusercontent.com/12549744/236701288-0c2bec7e-c357-44de-b1fe-cbb4a14c736f.mp4

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#35905m, Released: 2023-05-08
4.4.8.5

`55.68777, 37.33968`

When using Live updates and V2, a road chat and a house chat appear
 V1 - works normally


<table style="width:100%">
  <tr>
    <th>Without Live</th>
    <th>Live</th>
    <th>iOS</th>
  </tr>
  <tr>
    <td><video source src="https://user-images.githubusercontent.com/104760013/236854737-24536560-a3c3-46fb-a2aa-64484f697d4a.mp4"  width="300" height="auto"/></td>
    <td><video source src="https://user-images.githubusercontent.com/104760013/236854751-f9bb8055-4fc1-427c-9f78-379174d8144d.mp4"  width="300" height="auto"/> </td>
    <td><video source src="https://user-images.githubusercontent.com/104760013/236856107-63a65a3b-9f54-441c-893b-7cc36486bc35.mp4"  width="500" height="auto"/></td>
  </tr>
</table>

**Comment by ivanPyrohivskyi** [comment]
Need to expand bbox during reading obf. From 15 zoom.

**Comment by Nine-Tailed** [comment]
Found another bug:
https://osmand.net/map?pin=55.68753,37.34513#20/55.68753/37.34513
https://github.com/osmandapp/OsmAnd/assets/12549744/b6c172b7-0d78-440f-8325-621725df59ed

**Comment by Nine-Tailed** [comment]
One more place:
https://osmand.net/map?pin=55.64136,37.57937#17/55.64136/37.57937
See video:
https://t.me/ruosmand/124409

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#56m, Released: 2023-05-20
Best seen with **Topo** map styles
**Ask me map**

`55.64172° N, 37.57949° E`



https://github.com/osmandapp/OsmAnd/assets/104760013/014755d9-fcde-4bde-8ca1-16eb755ff69c

**Comment by Nine-Tailed** [comment]
Has this bug been fixed?  I still continue to watch him in the night build of OsmAnd~ 4.5.0#91m, release: 2023-05-25.

**Comment by vshcherb** [comment]
Original bug is fixed, I don't see any duplicate roads on the same screen. Anyway it could be unrelated issue to this one

**Comment by ivanPyrohivskyi** [comment]
> OsmAnd~ 4.5.0#56m, Released: 2023-05-20 Best seen with **Topo** map styles **Ask me map**
> 
> `55.64172° N, 37.57949° E`
> telegram-cloud-document-2-5427298177634019475.mp4

Moved to https://github.com/osmandapp/OsmAnd/issues/17282
