### ISSUE TITLE
Primary highway portions not rendered at zoom 12

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#14921]
This highway https://www.openstreetmap.org/way/197988587 and the segment south of it is missing on the map screen at zoom 12, while shown ok at 11 and 13. Latest California map.

![Screenshot_20220724-081515_OsmAnd~](https://user-images.githubusercontent.com/845735/180635117-2348ac8a-dd17-436c-b2d1-2b3cbcf69ecc.jpg)

**Comment by scaidermern** [comment]
Sounds like #14451 but more serious.

**Comment by vshcherb** [comment]
I didn't manage to reproduce on default map with Lancaster and Arizona map. First segment disappeared on 9th zoom.

**Comment by sonora** [comment]
Both segments are entirely in California.  It looks to me like the Califoornia map is faulty, i.e. may not contain the entire primary highway at zoom 12.

I tried the following:
- Deactivate the Arizona map: No change, this is expected.
- Then I deactivated the California map: I still see that incomplete highway at zoom 12, so it looks like it comes from the basemap?! (I have the April 25 version.)

**Comment by Zirochkabila** [comment]
reproduce on 4.3.0#13675mqta, released: 2022-07-28 and 4.2.7, released: 2022-07-13 versions.

OpenGL - upper part of the road is not displayed in 10 2.7 zooms, and the bottom part of the road is not displayed in 12 2.7 zooms
Without OpenGL - the same


https://user-images.githubusercontent.com/104760013/181450734-b2c70e20-bcb9-4fcc-b6be-818cf26c62d9.mp4

**Comment by xmd5a2** [comment]
Not reproducible on latest OsmAndMapCreator (legacy and OpenGL) with latest basemap anymore on any zoom
![Screenshot_2022-10-05_10-29-12](https://user-images.githubusercontent.com/5829014/194004779-8618f190-f643-4193-94fb-d8141b11896f.png)

**Comment by Zirochkabila** [comment]
https://github.com/osmandapp/OsmAnd/issues/14811
