### ISSUE TITLE
Routing to Samsø Rederi in Hou (access=yes node)

### ISSUE THREAD

**Issue by G4rdener** [osmandapp/OsmAnd#14924]
# 🐞 routing report

### Routing engine

- [X] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

 car (default)

### Start and end points

 Start: Hamburg, Flensburg, Kolding, Skanderborg, Horsens, Aarhus or Haldrup
End: Samsø Rederi in Hou (https://www.openstreetmap.org/node/3041302832)

### Actual and expected routes

Expected routing: Routing on E45 until Horsens V (56a) or Skanderborg V (52) then following the 451 or 445 to Hou

### Is this a regression?

Didn't try before
 Yes, the previous version in which this bug was not present was: ....

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

4.2.7

</code></pre>

**Device and Android/iOS version:**
Nokia 7.2
Android 11
**Maps used (online or offline):**

- [X] Offline maps offered within the OsmAnd app for download.
Denmark (01.07.2022) (Phone is connected to Wifi)
- [ ] Online (tile / raster) maps 

**Anything else relevant?**
Routing on OSM.org is working fine, and in OSMAnd it is working from e.g. Odder or Søvin

<details>
    <summary>Graphhopper</summary>

![osm_graphopper](https://user-images.githubusercontent.com/49069311/180663976-35b9e4c8-62df-4182-8936-920a3af8c8e6.jpg)

![osm_graphopper_hou](https://user-images.githubusercontent.com/49069311/180663977-1bd4fef2-015e-4290-9e1d-68de00dfe589.jpg)

</details>

<details>
    <summary>OsmAnd</summary>

![Screenshot_20220724-212248](https://user-images.githubusercontent.com/49069311/180663989-f1fa9b38-5a4a-43bf-aac5-3018218a149d.png)
![Screenshot_20220724-214113](https://user-images.githubusercontent.com/49069311/180663993-612c386f-f7d6-4d4a-9258-b332bd57869f.png)
![Screenshot_20220724-214137](https://user-images.githubusercontent.com/49069311/180663994-838ede25-bf79-4ca9-aa4f-2a81645a07a8.png)
![Screenshot_20220724-214204](https://user-images.githubusercontent.com/49069311/180663995-76759d80-81cd-42e6-9798-2e37214ff26a.png)
![Screenshot_20220724-214614](https://user-images.githubusercontent.com/49069311/180663996-a664c9e2-25b1-4179-9b34-e688cc07f3be.png)
![Screenshot_20220724-203001](https://user-images.githubusercontent.com/49069311/180663997-53816c44-ef88-4798-bfb9-2f51ffb78435.png)

</details>

**Comment by scaidermern** [comment]
The reason could be this [gate](https://www.openstreetmap.org/node/2207108788) which has no access tags set.

**Comment by G4rdener** [comment]
Actually this was my first thought too. But why is the routing working from Odder?

**Comment by vshcherb** [comment]
The route from Hamburg is OK, so the problem is in the last segment (https://osmand.net/map?start=55.794333%2C9.661102&end=55.912501%2C10.255158&mode=car#10/55.6218/9.7462)

And I think @scaidermern points correctly to the gate (https://www.openstreetmap.org/node/2207108788)
https://osmand.net/map?start=55.794333%2C9.661102&end=55.912447%2C10.258752&mode=car#10/55.7642/9.7572

**Comment by G4rdener** [comment]
Yeah that's correct but when you Route from Odder it won't Route over the two ferry connections but Route like exspected

**Comment by xmd5a2** [comment]
Routing time (cost) is 18445:
https://osmand.net/map?start=55.890090%2C9.972732&end=55.912513%2C10.259116&mode=car#10/55.6385/10.4548
But if you move start point 30 m east then routing time is 1512:
https://osmand.net/map?start=55.890063%2C9.973542&end=55.912513%2C10.259116&mode=car#18/55.89006/9.97501
There is no something special at this place in OSM data.
Routing engine bug?

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-core-legacy/pull/103

**Comment by alisa911** [comment]
**test files:**
osm - [newTestv3.osm.zip](https://github.com/osmandapp/OsmAnd/files/9764137/newTestv3.osm.zip)
obf - [Newtestv3.obf.zip](https://github.com/osmandapp/OsmAnd/files/9764138/Newtestv3.obf.zip)
osm of result - [res.osm.zip](https://github.com/osmandapp/OsmAnd/files/9764154/res.osm.zip)
inspector result for 14 zoom - [res.txt.zip](https://github.com/osmandapp/OsmAnd/files/9764162/res.txt.zip)
**pull request:**
https://github.com/osmandapp/OsmAnd-tools/pull/524
**before:**
<img width="768" alt="Screenshot 2022-10-12 at 13 53 26" src="https://user-images.githubusercontent.com/38911173/195325965-54f0ebb2-878c-4169-a14c-3eff054901df.png">
**after:**
<img width="523" alt="Screenshot 2022-10-12 at 12 55 20" src="https://user-images.githubusercontent.com/38911173/195326067-410b3a6a-da27-4f5a-b90a-5e77de635d9a.png">
**map on 14 zoom:**
<img width="372" alt="Screenshot 2022-10-12 at 12 57 33" src="https://user-images.githubusercontent.com/38911173/195326146-c3959b73-079c-4722-8383-d03560ce3aad.png">

**Comment by alisa911** [comment]
https://osmand.net/map?start=55.897141%2C9.810405&end=55.912513%2C10.259116&mode=car#11/55.9421/9.9890
было 2603 стало 2586

https://osmand.net/map?start=55.897141%2C9.810405&end=55.912513%2C10.259116&mode=car#11/55.9421/9.9890
с 2825 до 2554
<img width="762" alt="Screenshot 2022-10-13 at 10 28 56" src="https://user-images.githubusercontent.com/38911173/195530650-85746303-75d6-4a20-94f7-820b4424277c.png">
<img width="1150" alt="Screenshot 2022-10-13 at 10 33 31" src="https://user-images.githubusercontent.com/38911173/195531602-5c7b17d0-9310-4ed1-8e28-cc4dce95a66c.png">

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/14924 - probably related

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/15384

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/11770

**Comment by RZR-UA** [comment]
I've re-tested Issue with new OsmAnd HH-routing.

Finish point set exactly to Node: Samsø - Hou (3041302832)

Results:

### New routing (HH) - OK - 53 km, 0:45 time, 3508 cost

https://test.osmand.net/map/?start=55.794333,9.661102&finish=55.912459,10.259108&type=osmand&profile=car#11/55.8589/9.8335

![1](https://github.com/osmandapp/OsmAnd/assets/90444451/fcdd1292-520d-445b-aa84-98511d23de85)

### Old routing (BRP Java) - OK - 48 km, 0:47 time, 3575 cost

https://test.osmand.net/map/?start=55.794333,9.661102&finish=55.912459,10.259108&type=osmand&profile=car&params=car,hhoff#11/55.8589/9.8335

![2](https://github.com/osmandapp/OsmAnd/assets/90444451/c8346a5a-4cba-4294-9585-c50b75669170)

### Old routing (BRP C++ native) - OK - the same as Java

**Comment by RZR-UA** [comment]
Additinal tests are successful:

Test from Hamburg:

https://test.osmand.net/map/?start=53.558003,9.998245&finish=55.912459,10.259108&type=osmand&profile=car#8/54.669/10.085

https://test.osmand.net/map/?start=53.557977,9.997902&finish=55.912459,10.259108&type=osmand&profile=car&params=car,hhoff#7/53.778/9.558

Test to Hamburg with swapped start/finish

https://test.osmand.net/map/?finish=53.558003,9.998245&start=55.912459,10.259108&type=osmand&profile=car#8/54.669/10.085

https://test.osmand.net/map/?finish=53.557977,9.997902&start=55.912459,10.259108&type=osmand&profile=car&params=car,hhoff#7/53.778/9.558

**Comment by vshcherb** [comment]
Issue is finally fixed with new Special Routing
