### ISSUE TITLE
When you activate Hide Buildings house names are still displayed

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#14926]
### Description
When you activate Hide Buildings house names are still displayed

### Steps to reproduce
Configure map > Hide > Buildings > OK

### Actual result
The building names are still displayed
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/180794417-f1698c54-3ca2-452a-afd8-516e79264b87.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
When you activate Hide Buildings house names don't still display

### Your Environment
OsmAnd Version: 4.3.0#13666mqta, released: 2022-07-25
Android/iOS version: Android 11
Device model: POCO X3 NFC

**Comment by xmd5a2** [comment]
![Screenshot_2022-08-04_10-02-26](https://user-images.githubusercontent.com/5829014/182784495-8fac187b-a382-40fa-a147-eb3567c59af8.png)
