### ISSUE TITLE
Show relation ID when tapping on a route

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#14938]
Tapping on POIs shows the corresponding node/way/relation OSM ID in the POI information section.

Tapping on a route doesn't display the relation ID in the information section. It would be nice to have this information, e.g. for mapping and/or debugging.

**Comment by bobeeeze** [comment]
I have now the 4.5.10 version and the relation ID still does not appear in the information section.
Thanks for your work

**Comment by vshcherb** [comment]
Relation ID is not part of the data we need to investigate how much map will increase if data will be stored

**Comment by ivanPyrohivskyi** [comment]
> Relation ID is not part of the data we need to investigate how much map will increase if data will be stored

Do not understand where to better store relations ids

**Comment by Dima-1** [comment]
[Now it looks like this](https://github.com/osmandapp/OsmAnd-Issues/issues/2375#issuecomment-2039470492)

**Comment by pebogufi** [comment]
> [Now it looks like this](https://github.com/osmandapp/OsmAnd-Issues/issues/2375#issuecomment-2039470492)

Link is not valid

**Comment by dmpr0** [comment]
## Review 
- [ ] Replace ID with full OSM link: `51855` > `https://www.openstreetmap.org/relation/51855`
- [ ] Add `Relation_id` to strings as `Relation ID` or `Openstreetmap link`
- [ ] Show only if OSM Plugin is on

**Comment by shurasmiling** [comment]
https://github.com/osmandapp/OsmAnd-iOS/issues/3586
