### ISSUE TITLE
Remaining issues with tapping routes

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#14936]
Carry over from #14698:

1. It still seems unclear where exactly you have to tap on a route to get it selected. It seems that maybe you have to hit a displayed route shield, or an actual route point? Or is there a timing issue, that maybe some indexing takes place after panning during which tapping a route is flaky or may have no effect?
2. There are issues with some routes still not showing, but this seems perhaps only under certain circumstances or devices. The effect is that tapping them briefly shows the "Loading data..." toast, but this aborts with no subsequent context menu shown. Examples are https://www.openstreetmap.org/relation/3762491("Relation: Goldsteig 4: Neuhaus - Letzau/Oberhöll") and https://www.openstreetmap.org/relation/7323772 ("Relation: Trausnitz - ?? 1"). 
3. Possibly related to (2.): Special characters in the OSM relation name may be the root cause of (2), see above. In any case, even on devices where (2) is not an issue, Relation "Goldsteig 4: Neuhaus - Letzau/Oberhöll"is in OsmAnd displayed truncated to just "Oberhöll". (see screenshot at https://github.com/osmandapp/OsmAnd/issues/14698#issuecomment-1194425825)

**Comment by scaidermern** [comment]
I already reported 1) in #14241. Tapping on route shields also doesn't work reliably (even after the alleged fix).

There is also a 4th issue: If multiple routes overlap then only one of them will get selected (the one that gets rendered, I guess). It is not possible to select the other routes.

**Comment by vshcherb** [comment]
Looks more like 3 independent issue or a discussion then
1. You need to hit on road shields
2-3. Strange, attaching screenshots cause it works in my case

<details>
    <summary>Screenshots</summary>

![telegram-cloud-photo-size-4-5980796128263781044-y](https://user-images.githubusercontent.com/1042025/181010376-dfabbedd-61d2-43b3-90be-1e4293a1dd39.jpg)

![telegram-cloud-photo-size-4-5980796128263781045-y](https://user-images.githubusercontent.com/1042025/181010391-c4422ec7-3b5e-4191-ac99-f5f73d325676.jpg)


</details>

4. All routes on the same way should be suggested in the list. I've tested on (https://www.openstreetmap.org/relation/7323772#map=16/49.5175/12.2728, https://www.openstreetmap.org/relation/3762491#map=13/49.7371/12.2458) works ok.

**Comment by scaidermern** [comment]
>     4. All routes on the same way should be suggested in the list. I've tested on (https://www.openstreetmap.org/relation/7323772#map=16/49.5175/12.2728, https://www.openstreetmap.org/relation/3762491#map=13/49.7371/12.2458) works ok.

At some places more than one route shield is visible when routes overlap. Tapping on these individual route shields opens individual routes.

At other places only one route shield is visible when routes overlap. Here, only one route can be opened via tapping. One example for this is 51.54561,12.96754 where [Jakobsweg Frankfurt/Oder - Leipzig](https://www.openstreetmap.org/relation/2254652) and [Torgau-Taura-Jägereiche](https://www.openstreetmap.org/relation/301680) overlap. Only the first one is visible and can be tapped.

**Comment by scaidermern** [comment]
>        2-3. Strange, attaching screenshots cause it works in my case

No, it doesn't. The name of the relation of your first screenshot is "Goldsteig 4: Neuhaus - Letzau/Oberhöll" but it displays only "Oberhöll".

The same applies to the route [Jakobsweg Frankfurt/Oder - Leipzig](https://www.openstreetmap.org/relation/2254652) from my previous comment where OsmAnd shortens the name to "Oder - Leipzig".

**Comment by sonora** [comment]
Possible issue (4) I cannot reproduce on recent builds, I seem to normally get the proper interim selection dialog ok when I tap (and after the tap is accepted) on a way which belongs to several route relations. But have not systematically verified if the list is complete, possibly there is an issue related to (1) that not all underlying routes are reliably captured by every tap? I suggest let's fix (1) first, then re-evaluate. 

Regarding the "'/" truncate issue, looks like you have reproduced it in your screenshot.

What bugs me is that you can produce the context menu of the two route relations 3762491 and 7323772 of my report, they do not open for ne...

**Comment by vshcherb** [comment]
I've created separate issue that we've reproduced and going to fix - https://github.com/osmandapp/OsmAnd/issues/14953. Probably it will affect others.

**Comment by sonora** [comment]
Regarding sub-Issue (2):  Could it matter if you use openGL or legacy-core (I use the latter)?

**Comment by vshcherb** [comment]
It could matter of course.

**Comment by sonora** [comment]
In the field I have a hard time testing both. Is there a way to compile an apk which would use legacy-core or openGL at runtime based on the setting we have in the dev plugin? So far my impression is we have only apks where the decision is made already at compilation time?

**Comment by vshcherb** [comment]
Nope - https://download.osmand.net/latest-night-build/OsmAnd-opengl-arm64-nightly.apk has both!

**Comment by vshcherb** [comment]
Released version 3.2.7 - also has both

**Comment by sonora** [comment]
Right, thanks. I have verified that the issues reported above slso occur using OpenGL.

And I just notice I misspoke above: My question is that I use both armv7 and armv8 devices, and I was wondering if we have "Fat" builds for OpenGL? So far for testing I always use armv7 compilations regardless of hardware (not that I think that is a big performance hit on armv8).

**Comment by vshcherb** [comment]
assembleAndroidFullOpenglFatDebug - 300 MB - correct
so we build opengl only for arm to have size up to 170MB

**Comment by mdykierek** [comment]
See my latest findings in #15131 - I think it is related to possible loops on the route or even route being a loop.

**Comment by sonora** [comment]
With #14953 essentially addressing sub-issue (1), I think here we should now focus on (2), i.e. why tapping some routes briefly produces the "Loading data..." toast but then nothing happens. (Still not fixed in 2022-08-23 nightly.)

Here is another one of these: https://www.openstreetmap.org/relation/7323851. While its title also contains a question mark, that may actually not be the underlying root cause.

**Comment by vshcherb** [comment]
Issue 2. Can't confirm.
<details>
    <summary>Details</summary>

![telegram-cloud-photo-size-4-5780858331118811143-y](https://user-images.githubusercontent.com/1042025/186444849-97144cb1-13fb-43d1-be3e-147f6cc48f09.jpg)

</details>

**Comment by vshcherb** [comment]
As I see for now this issue is not addresable yet cause the cased are not reproducible for now

**Comment by sonora** [comment]
Interesting why this would be configuration-specific... I have this on all my devices, it seems.

Here a few more examples:
https://www.openstreetmap.org/relation/7933
https://www.openstreetmap.org/relation/2746884

And they both have a ":" in their name, which brings up back to my special character theory... 😉

**Comment by sonora** [comment]
EDIT: After testing more occurrences, it most definitely looks like the occurrence of special characters like colons (:), double quot marks (") and question marks seem to cause the issue...

So if things are device specific, could it depend on the sysrem character set or region settings?

**Comment by sonora** [comment]
@vshcherb Here is a respective logcat, when tapping on https://www.openstreetmap.org/relation/7323851:

```
08-27 07:55:06.804 3052 17104 E net.osmand: GPXUtilities Error saving gpx
08-27 07:55:06.804 3052 17104 E net.osmand: java.io.FileNotFoundException: /storage/9C33-6BBD/osmand/temp/Trausnitztalsperre (Rundweg?).gpx: open failed: EPERM (Operation not permitted)
08-27 07:55:06.804 3052 17104 E net.osmand: 	at libcore.io.IoBridge.open(IoBridge.java:492) 08-27 07:55:06.804 3052 17104 E net.osmand: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)

```
So OsmAnd is trying to save the tapped hiking route as a temporary gpx file in a temp folder, and that fails due to the '?' in the attempted file name, right?

**Comment by scaidermern** [comment]
Java has `replaceAll()`, allowing to replace all invalid characters withing a single function call.

**Comment by sonora** [comment]
This fixes (2) and (3): https://github.com/osmandapp/OsmAnd/pull/15167

**Comment by vshcherb** [comment]
Tapping doesn't work yet if you tap in the middle of very long way segment, going to be fixed separately.

**Comment by sonora** [comment]
Yes, exactly. That seems what  was described here as (1) and then also at   #14953.

**Comment by vshcherb** [comment]
WIP - https://github.com/osmandapp/OsmAnd/pull/15205

**Comment by sonora** [comment]
After updating all respective maps it appears as if (a) may have become much less of an issue.
