### ISSUE TITLE
Part of the historical route is not displayed on the map

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#14945]
### Description
Part of the historical route https://www.openstreetmap.org/way/399047914#map=10/53.6088/15.9151 is not displayed on the map from https://www.openstreetmap.org/search?query=53.78961%C2%B0%20N%2C%2016.56743%C2%B0%20E#map=15/53.7896/16.5775 to https://www.openstreetmap.org/search?query=53.68644%C2%B0%20N%2C%2016.26970%C2%B0%20E#map=15/53.6809/16.2730

### Steps to reproduce
Configure map > Map style > Topo > Apply > Details > OSM mapper assistant > Find this place 53.78961° N, 16.56743° E

### Actual result
Part of the route is not displayed on the map
from 53.78961° N, 16.56743° E
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/181255750-ecb0ce53-6f53-4e26-a5d9-3c061d44f05f.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

to 53.68644° N, 16.26970° E
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/181255894-1c626353-f981-44cf-86e9-5f7d9f520df6.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
The historical route is displayed from [53.43152, 15.28523](https://www.openstreetmap.org/#map=18/53.43152/15.28523) to [53.95881, 16.99765](https://www.openstreetmap.org/#map=17/53.95881/16.99765)

### Your Environment
OsmAnd Version: 4.3.0#13673mqta, released: 2022-07-27
Android/iOS version: Android 11
Device model: POCO X3 NFC

**Comment by xmd5a2** [comment]
Looks like this is historical route that never existed but only planned. We don't plan to add such routes in near future to map because their importance to regular user is debatable. Maybe we'll add some historical layer in future. If this route exists (marked/visible) in reality please use corresponding tags in OSM (embankment, path, track etc.)
