### ISSUE TITLE
2.5D mode tilt angle is hard to change

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#14942]
Entering/leaving 2.5D mode or trying to change the tilt angle is really hard. Most of the time OsmAnd moves the map or starts to zoom instead of changing the tilt angle. I've noticed this on several devices (Samsung S7 and Samsung S9).

Is it just me? Is there a certain trick?

This has also been mentioned here by a different user: https://github.com/osmandapp/OsmAnd/issues/1972#issuecomment-1173133591

**Comment by scaidermern** [comment]
As a comparison: tilting in Google maps is much more reliable.

OsmAnd should stop zooming/paning as soon as two fingers are detected and start to tilt instead.

**Comment by RalfJung** [comment]
This seems to have some overlap with https://github.com/osmandapp/OsmAnd/issues/14973 -- except there people are having the issue that tilting happens *accidentally* when users want to zoom/pan. The fact that it starts tilting looks like a bug.

How do you even use two fingers to tilt or change the tilt angle? Usually using two fingers I would expect to zoom/pan.

**Comment by mikehgentry** [comment]
If you have the prerequisites for it working, you put two fingers on the map then move them up or down. 
It does seem to work more reliably if I place my fingers on the screen, with a considerable gap between them, wait a second, *then* start the swipe.

**Comment by RalfJung** [comment]
I see. I often put two fingers on the screen to pan and zoom, so that explains why it keeps tilting the screen when I don't want it to do that.

**Comment by vshcherb** [comment]
Was fixed here https://github.com/osmandapp/OsmAnd/issues/15931 - so there is no tilt while zooming

**Comment by scaidermern** [comment]
With version 4.5.0 two-finger tilt has become even harder to activate. It is almost impossible. Or is it just me?

**Comment by Zirochkabila** [comment]
@scaidermern this is mentioned here https://github.com/osmandapp/OsmAnd/discussions/16836#discussioncomment-5764948

**Comment by scaidermern** [comment]
> @scaidermern this is mentioned here [#16836 (comment)](https://github.com/osmandapp/OsmAnd/discussions/16836#discussioncomment-5764948)

I see. But only inside a discussion. Wouldn't it be better to open a ticket for this bug?

**Comment by vshcherb** [comment]
Now there is a special button so this bug is less a priority comparing to the discussion of rotating and zooming the map

**Comment by AnotherNeko** [comment]
> Now there is a special button so this bug is less a priority comparing to the discussion of rotating and zooming the map

where is this special button? my map is tilted to the maximum such that I can't see where to go, and I can't figure out how to untilt it. 

This thread is the first result on Google.

**Comment by AnotherNeko** [comment]
turns out you need to EXIT NAVIGATION MODE then tap the "my location" button in the bottom right corner.

**Comment by sjvudp** [comment]
I wanted to suggest to make the angle for 2.5D settable, but as it seems it is already. Probably it's non-obvious how to change it, and the setting is most likely quite hidden. Also it seems I can only activate 2.5D mode *after* the current location is known (because the button does not appear otherwise).
