### ISSUE TITLE
Unable to attach the track to the road

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#14946]
### Description
Unable to attach the track to the road

### Steps to reproduce
Select GPX track > Edit track > Options > Attach to the roads > The message "You can attach to the roads only a recorded track" is displayed 
Record the track > Select GPX track > Edit track > Options > Attach to the roads > The message "You can attach to the roads only a recorded track" is displayed 

### Actual result
Unable to attach the track to the road with recorded tracks in OsmAnd as well as imported tracks 
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/181262570-81f0039f-ed4e-4730-bc15-f0d500af8e1c.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
The track is attached to the road

### Your Environment
OsmAnd Version: 4.3.0#13673mqta, released: 2022-07-27 /  4.2.7, released: 2022-07-13
Android/iOS version: Android 11
Device model: POCO X3 NFC

**Comment by LancashireLad** [comment]
You get the same issue if you Plan Route - open existing track - option- attach to roads

Quite by chance I seem to have found a work around...

My Places - tracks (select imported GPX) - track - altitude -calculate altitude - attach to roads - continue - choose profile - apply (when it eventually becomes available - takes a while) - Done (top right)   Bingo!
