### ISSUE TITLE
The information in the note tag is displayed in the place name

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#14950]
### Description
The information in the note tag is displayed in the place name
https://www.openstreetmap.org/node/1614321191#map=19/51.10302/13.65642
https://www.openstreetmap.org/way/887135294#map=18/50.96047/13.94569

### Steps to reproduce
Search > 51.103091, 13.656049
Search > 50.960593, 13.945497

### Actual result
The information in the note tag is displayed in the place name

51.103091, 13.656049
[Map.obf.zip](https://github.com/osmandapp/OsmAnd/files/9220389/Map.obf.zip)

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/181281155-a9ebecf0-6f8d-4bff-bd28-719a6990179b.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

50.960593, 13.945497
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/181281351-1eae274c-838b-447c-a9b2-a4f6994f7a69.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
The information about these place names is displayed like this
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/181282139-7c79c333-d034-462b-99f9-929dbf9d32db.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/181282149-1dd6b178-b093-40ed-89e9-ddd94cce668e.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Your Environment
OsmAnd Version: 4.3.0
Android/iOS version: iOS 15.5
Device model: iPad mini 4

**Comment by vshcherb** [comment]
- Did you backup maps ?
- Is it reproducible Android opengl?

**Comment by Zirochkabila** [comment]
1. No, I don't do maps backup
2. Yes it's reproducible Android OpenGL

>

**Comment by scaidermern** [comment]
I can confirm this issue, happens only with enabled OpenGL. Here is another example:

https://www.openstreetmap.org/node/2720676482
![photo_2022-07-28_09-35-50](https://user-images.githubusercontent.com/1040784/181448286-f1686ef3-ce65-414a-b816-c96c0fdba397.jpg)

Also occurs for https://www.openstreetmap.org/node/3765427071.

Maybe this only happens for `public_transport=halt` and `public_transport=station`. So far I haven't seen this behavior at other places.

**Comment by Zirochkabila** [comment]
It's happened for park names too

**Comment by Choreuomai** [comment]
I encounter this issue even without OpenGL enabled. Android 10, Osmand+ 4.2.7.
Example: https://www.openstreetmap.org/way/675971880

**Comment by Zirochkabila** [comment]
Maps

https://drive.google.com/drive/folders/1a-GFrWsW50Iob82xU1nuvzd3p5aj_J05?usp=sharing

**Comment by cricri-du-lauragais** [comment]
the same for me in my personal style, I solved the problem by changing
nameTag="name"
to 
nameTag=""
and strangely it works

**Comment by nyanmeister** [comment]
I duplicated this issue because I didn't see yours, it also applied to the `fixme` and `operator` tags, as well as `gnis:state_id` which was weird.
