### ISSUE TITLE
Semi-transparent widget

### ISSUE THREAD

**Issue by arncor** [osmandapp/OsmAnd#14957]
# 🚀 feature request

### Description
Widgets with white background cover a good chunk of the screen and are opaque.
We can already choose a transparent background but they become difficult to read.

### Describe the solution you'd like
I wish we could have them look like when night mode is activated (semi transparent dark), but for daymode.

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/16017#issuecomment-1807604736
