### ISSUE TITLE
Route Select doesn't work reliably

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#14953]
When tap on shield nothing happens, selected wrong [way]( https://www.openstreetmap.org/way/106221940) with max distance > 50m from tap
https://www.openstreetmap.org/way/302034108#map=16/57.2370/9.5799
https://www.openstreetmap.org/relation/13278799#map=18/57.23318/9.5754
![2022-07-26_16-39](https://user-images.githubusercontent.com/31807095/181034534-59230f22-4f27-4402-a426-faa43a4e6fba.png)

**Comment by sonora** [comment]
Why do we rely to tap on shields at all? To select recorded tracks you simply have to tap somewhere on the way, and that works reliably. In fact so well, that tapping where a recorded track and an OSM route relation or shield overlap, often the track is displayed right away without interim selection dialog.

**Comment by vshcherb** [comment]
That's the fastest method, we need to detect if that's an empty space or not. So it's correct though we should be able to display list of Routes during planning for example.

**Comment by sonora** [comment]
Different issue around the same code: #14966.

**Comment by vshcherb** [comment]
Technical comment:
- This method looks unnecessary and not used in OsmAndMapCreator (https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd-java/src/main/java/net/osmand/router/network/NetworkRouteSelector.java#L115)

- [ ] We should leave & use only 2 public methods (and delete  getFirstSegments?)
- public Map<RouteKey, GPXFile> getRoutes(QuadRect bBox, boolean loadRoutes, RouteKey selected) throws IOException
- https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd-java/src/main/java/net/osmand/router/network/NetworkRouteSelector.java#L96

- [ ] OsmAndMapCreator and OsmAnd should work exactly the same & produce same results

**Comment by Dima-1** [comment]
- Request
https://github.com/osmandapp/OsmAnd/pull/15094

**Comment by sonora** [comment]
Disadvantage: From what I see there are bicycle routes without shields which are ot selectable.

**Comment by sonora** [comment]
Somehow, after this is claimed fixed, the experience is still mixed:

Sometimes it seems like I have to tap a route shield multiple times before it reacts. In some other cases it seems that tapping one route shield works reliably, while tapping a neighboring shield produces zero reaction at all.

Then, at times, the behavior/non-responsivenes of tapping these two neighboring route shields seems reversed.

Overall I am not certain we can call this fixed?

**Comment by sonora** [comment]
I have a feeling much of this is also a timing issue: If you scroll to a new map area then tap a route (even repeatedly), you may get zero response. Waiting for say 30secs, then things work ok...

**Comment by sonora** [comment]
Here is something weird: If you tap near 49.35492° N, 11.26223° E in the cycle profile, this is very near routes FA 15 (https://www.openstreetmap.org/relation/2759182) and FA 16 (https://www.openstreetmap.org/relation/2746914). But instead OsmAnd only offers FA 17 in its selection dialog, which is https://www.openstreetmap.org/relation/2746884, and about 500m away?!

**Comment by vshcherb** [comment]
It's probably depends on zoom cause the search radius is different on each zoom.

**Comment by sonora** [comment]
Done some more testing now. It seems to solely depend on the route, and the specific section of a route you are trying to tap shields on. Most routes work flawlessly, but specific ones seem to have a systematic issue by reacting sluggsishly or in places not at all, and that then seems the same at all zoom levels.

**Comment by vshcherb** [comment]
We have a new open issue for that... will comment here once it's fixed.
