### ISSUE TITLE
Route-related IllegalStateException after tapping the map

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#14966]
See log attached, code base was latest nightly (with legacy core). Profile was 'Browse map' (no hiking routes, bike routes etc. displayed).

I think I happened to tap on the road shield of a tertiary road when this crash occured. Could not reproduce after app restart: After tapping the same or neighboring road shields the corresponding tertiary highway was highlighted ok, hence seems a spurious situation.

[exception.log.txt](https://github.com/osmandapp/OsmAnd/files/9225451/exception.log.txt)

**Comment by vshcherb** [comment]
Issue that it's accessed in UI thread! And geocoding is possibly competing and concurrent, so it needs to be the same as geocoding and using same files. So it's tricky to reproduce but it's possible

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/15708
