### ISSUE TITLE
Offroad map style (Opengl) - crash

### ISSUE THREAD

**Issue by mikehgentry** [osmandapp/OsmAnd#14962]
### Description

Crash

### How to reproduce?

1) Enable opengl.

2) Enable offline vector maps, offroad style.

3) With this profile selected, fully close OsmAnd.

4) Open it again. It shows the loading screen, then crashes back to the OS.

5) Open it again. It prints "Native OpenGL library is not supported. Please try again after exit" in a popup, then runs as usual, but using legacy rendering.

If instead you open it with another profile selected, then switch to this profile, everything works OK.

### Your Environment
OsmAnd Version: +4.2.7
Android/iOS version: Android 11
Device model: Xcover 4s

**Comment by jfburke3** [comment]
I have the same problem, except it happens with the OsmAnd style selected. I'll run with OpenGL turned off for a day or so and see if that helps. 

Samsung Galaxy S20FE, Android 12, OsmAnd play store beta version OsmAnd+ 4.2.7, released: 2022-07-13

Interestingly, I do not seem to have this problem on my S9+ with OpenGL and OsmAnd map style. I will try to make time to test with Offroad map style.

**Comment by cridemichel** [comment]
Hi all, 
same behavior for osmand pro on my POCO F3 with up-to-date global miui (13.0.7),
best Cristiano

**Comment by vshcherb** [comment]
Bug : 
- Android initialized Offroad earlier than Topo 
- Callback is called before styles / core is initialized

**Comment by Dima-1** [comment]
- https://github.com/osmandapp/OsmAnd/pull/15239

**Comment by arncor** [comment]
Hello, 
Just came to say I got the same bug here : 

Crash on launch of Osmand with offroad map and OpenGL activated, and then on the next launch "Native OpenGL library is not supported".

It's ok though if I start with Osmand map and then switch to offroad.

Osmand+ 4.2.7 from PlayStore and Ulefone Armor 6E running Android9.

PS : when can I sign up for beta testing osmand ? I can't find the link on Osmand page on the PlayStore ? Thanks.
