### ISSUE TITLE
render natural=cliff point

### ISSUE THREAD

**Issue by miramikes** [osmandapp/OsmAnd#14976]
Hello,
I believe there is no symbol for node natural=cliff
I started maping some climbing areas and adopt some habits from other mapers ...
to map rock towers as natural=peaks and larger roks and walls as natural=cliff
But it looks like cliffs are not displayed by OsmAnd hiking profile
On screenshot below should be natural=cliff name=Babinec close to the left from natural=peal name=Zeppelin 
best regards
MIra

![Cliff](https://user-images.githubusercontent.com/623412/182046313-2abcf998-87ce-4b7b-84b4-e419d52e6c7d.png)

**Comment by vshcherb** [comment]
![telegram-cloud-photo-size-4-6003851379564722641-y](https://user-images.githubusercontent.com/1042025/182435196-9fd9d968-2430-4f10-ac71-49ba25186595.jpg)
https://www.openstreetmap.org/way/818874506#map=19/41.97722/3.21133

**Comment by vshcherb** [comment]
Supported in OpenGL map

**Comment by miramikes** [comment]
No ... I didn't meant line ... natural=cliff but point(node) natural=cliff
https://www.openstreetmap.org/edit#map=19/50.61901/16.12922
best regards
Mira

**Comment by sonora** [comment]
In deed natural=cliff is occasionally mapped as a node, just like natural=rock. Looks like we render no symbol for it on the map, though at least I have seen the name of natural=rock displayed in places.

Maybe adding a small symbol would be good.. But Let's please not use the peak icon, as some of these rock formations are near peaks and dupilcating that icon would obscure the true peak location.

**Comment by miramikes** [comment]
I started mapining some climbing areas ... advice from Czech OSM forum was:
natural=rock ... smaller rocks ... usually boldering
natural=peak ... rock towers ... for sport or trad climbing
natural=cliff ... larger rock walls ... usually trad climbing
usually combined tags of names and numbers of sport or trad routes ...
Yes I believe 3 different symbols would be great for rock peak and cliff
Mira

**Comment by miramikes** [comment]
Maybe a black trapezoid would be good idea for natural=cliff point as we have black pyramid for natural=peak ...
Just suggestion ...
m.
