### ISSUE TITLE
Make possible to move many favorites into category

### ISSUE THREAD

**Issue by Silverspur** [osmandapp/Osmand#1497]
To my opinion, it would be a great addition to have the following options:
* Renaming a category: for now this seems to be impossible, one needs to parse all favorites of the category, and change the category name for each.
* Allowing custom colors for categories, or at least offering more choices.
* Providing a hierarchy mechanism to classify categories: a character could be used as a separator to build a directory structure, for instance we could have the following categories : 'NYC', 'NYC/Restaurants' (belongs to NYC category), 'NYC/Restaurants/Brunchs' (belongs to NYC/Restaurants category) and 'NYC/Museums' (belongs to NYC category). This would allow for a user-friendlier interface, wihout having to change the way the Favorites are stored in the file. Of course, it would be even greater to deal with this hierarchy at the XML level in the file, if GPX format allows it.

**Comment by vshcherb** [comment]
* No, rename is not possible. We are going to implement "Move .."  functionality, when you move favorites to a group
* Custom colors available if you prepare favorites.gpx manually.
* You brought a good example of what we should think, though I believe hierarchy is too much. I personally use text NYC - Restaurants, NYC - Hotels - so in UI it looks sorted and reasonable and also searchable.

**Comment by vshcherb** [comment]
Implemented

**Comment by littlehelper** [comment]
I am looking for an opportunity to move several favourites or gpx waypoints from one category into an other but I cannot find "Move..." as mentioned above. Is there a possibility to select/mark several waypoints and move them into a category (like is is possible to delete multiple waypoints) at once?

**Comment by vshcherb** [comment]
No, it is possible to move only whole group into another. Using rename group feature.
