### ISSUE TITLE
Nautical map - submerged stone and similar ...

### ISSUE THREAD

**Issue by miramikes** [osmandapp/OsmAnd#14975]
Hello,
I believe to make symbol for submerged stone smaller (at least at some zoom leves) would make nautical map better looking and easer readable. If agreed then same should goes for oher similar features.
Also I believe that make these symbols more or totally transparent would enhence possibility to read shape of shore better
best regards
Mira

![Stones](https://user-images.githubusercontent.com/623412/182045363-d7759ca8-bea5-4ac5-9b81-1d11bfb6b4f7.png)

**Comment by vshcherb** [comment]
It looks like map magnifier is used and it produces a problem

**Comment by miramikes** [comment]
You are right ... Magnifier was used ... I didn't know it.
But even with magnifier in default I believe icons for submerged stones (and similar) could be somewhat smaller that icons for ports and navigation icons like beacons.
best regards
Mira


![Stone-2](https://user-images.githubusercontent.com/623412/182439753-df776388-f94a-4242-8188-04d536ee0f00.png)
