### ISSUE TITLE
Dog access tag standard incorrect.

### ISSUE THREAD

**Issue by nyanmeister** [osmandapp/OsmAnd#14971]
### Description
OSMAnd uses the wrong key to populate info in a PoI/Area for dog access.
The correct key is "[dog](https://wiki.openstreetmap.org/wiki/Key:dog)", not "[dogs](https://wiki.openstreetmap.org/wiki/Key:dogs)".

### How to reproduce?
Tag an item (or look for objects) with `dogs:<value>` (`yes`,`no`,`leashed`,`unleashed`,`designated`) and it will show this in the info card for an item, and not do this for `dog:<value>` which is the correct tag according to the wiki and popular use.

### Your Environment
OsmAnd Version: 4.2.6 Plus
Android/iOS version: 11
Device model: N/A

**Maps used (online or offline):** N/A

If this gets addressed, also be sure that all major values for the `dog` tag will populate in the info card.

**Comment by xmd5a2** [comment]
I don't know where you found "dogs" in OsmAnd. However I've made a poi filter and added some new values.
