### ISSUE TITLE
Track recording lost if device turns itself off for low battery

### ISSUE THREAD

**Issue by speleoluc** [osmandapp/OsmAnd#14981]
Doesn't Android send a notification to running apps before turning itself off due to low battery? OSMAnd could use it to save the track currently being recorded. With the current setup, everything gets lost when this happens.

**Comment by sonora** [comment]
Have you completely restarted the app later to take a look? I think the track should show up then.

**Comment by speleoluc** [comment]
After charging and restarting the phone, I opened OSMAnd+ and there was no available track.
