### ISSUE TITLE
Updating all offline maps using 'select all' box fails silently

### ISSUE THREAD

**Issue by mrvanes** [osmandapp/Osmand#1498]
I've noticed a couple of times that when I have multiple map updates in queue and select them all by using the "multi select" box on top, the downloads fail (silenty!). The downloads start, decrement downloads left until everything is done, but nothing has changed. I'm left with all maps "updatable" when I refresh.
Only when I select all maps one-by-one and select download, all maps get downloaded en updated correctly.

Version: Android, OsmAnd+ 2.1.1, maps on external SD Card.

**Comment by vshcherb** [comment]
Can't reproduce it for now, the issue might be that updates are refreshed after all maps are downloaded, but they are still updated.
