### ISSUE TITLE
Track recording stops and resumes randomly

### ISSUE THREAD

**Issue by speleoluc** [osmandapp/OsmAnd#14985]
### Description

When paddling, I often start track recording, but for some unknown reason, this recording stops and (sometimes) resumes seemingly randomly, leaving large gaps in the final track. This is despite closing all other apps and turning off power save. This happens on both my phone and tablet, as well as a friend's phone.

I suspected a phone overheat, but this occurs even on cool days, with the phone washed by water (in a waterproof soft case), face down. On the attached screenshot

![Screenshot_20220730-145033_OsmAnd+](https://user-images.githubusercontent.com/57163823/182159266-a7f79a73-6b6c-409d-ab90-74bc7720d282.jpg)

and 30s-interval GPX file renamed as TXT (time for GitHub to support GPX...)

[2022-07-30_11-12_Sat.txt](https://github.com/osmandapp/OsmAnd/files/9237520/2022-07-30_11-12_Sat.txt)

the end position was at track start, so the phone did have a GPS reading at that time.

If the phone momentarily loses GPS data (unlikely on the water with an open sky), shouldn't OSMAnd+ say it (vocally, I mean)?

Is there a debug option I can turn on to trace those stops and report why they happen?

### How to reproduce?

Start recording, leave phone idle, go paddling, turn screen on once in a while and check track at end of the day. 50% chance of gaps.

### Your Environment
OsmAnd Version: 4.2.7
Android/iOS version: Android 8.0.0
Device model: Samsung A5 (2017) phone

Also occurs on Samsung S5e tablet and others.

**Comment by scaidermern** [comment]
Did you disable battery optimization for OsmAnd in your system settings? If not, please try it.

**Comment by sonora** [comment]
When you say it "sometimes" resumes, is this ecactly at places where you happened to turn on the screen  to look at the map? (Only) then is it likely related to the device's power management. Maybe you want to test what I write here https://osmand.net/docs/user/troubleshooting/track-recording-issues#the-system-may-kill-background-apps-to-save-power in section Tested **Settings for Android 9 and 10 (Hardy, 2020-08-25)**, works for me like a charm also with current Android 11 firmwares.

**Comment by speleoluc** [comment]
I say "sometimes resumes" because sometimes I get gaps in the track while at other times, like shown here, once recording stops, it never resumes. Yes, the times recording resumes do seem to correspond to moments I checked the screen, although in the case shown, I was landed on a rock, I checked the recorded distance so far, but the track wasn't recorded any further. Did turning the screen on have the opposite effect? 

I never touched the Trip recording settings, and I see the "Auto-split recordings after gap" and "Prevent standalone logging" options are set.

As for Android settings, Power Saving is off and OSMAnd+ is among the two Unmanaged apps on my phone.

Should I decrease recording period to < 30s ?

**Comment by sonora** [comment]
The recording period has no effect on things any more ever since a few releases ago.

Looks like your issue is that you have the "Prevent standslone logging" option set? The default is to have this option off. Turning it on exactly inhibits OsmAnd to log when the screen is off, I think. (Mostly used for car systems where users want to log trips only while their ignition is on, i.e. their screen is on.)

**Comment by speleoluc** [comment]
Thanks for explaining it. I didn't see the implication of "standalone" since I never close the app, just turn off the screen. I applied the change to all profiles.

**Comment by sonora** [comment]
I am not 10% sure sp please zest if this solves your issue.
