### ISSUE TITLE
Unbrauchbare Routing Anweisung bei Benutzung eines tracks

### ISSUE THREAD

**Issue by ReinerMeyer** [osmandapp/OsmAnd#14980]
Heute bin ich eine Strecke zwischen Leobersdorf und Ofenbach gefahren, wo an 2 Stellen unbrauchbare Routing Anweisungen vorkammen und einmal verwirrende Anweisungen. Für das Routing habe ich einen track verwendet (Auerspergstraße-Ofenbach, s. angehängte gpx-Datei).

1. unbrauchbare Anweisung bei einem Kreisverkehr(Knoten 31 - 38 der angehängten gpx-Datei): Leicht links abbiegen
An dieser Stelle hätte diese Anweisung gegeben werden sollen: Einfahren in den Kreisverkehr, dann die 2. Ausfahrt nehmen

2. unbrauchbarre Anweisung bei einem Kreisverkehr (Knoten 439 - 446 der angehängten gpx-Datei): rechts abbiegen, dann scharf rechts abbiegen
An dieser Stelle hätte diese Anweisung gegeben werden sollen: Einfahren in den Kreisverkehr, dann die 3. Ausfahrt nehmen

Die verwirrende Anweisung war direkt nach der Abzweigung der S4 von der A2 (Knoten 250 - 268 der angehängten gpx-Datei. Gleich zu Beginn des Kurvenverlaufs kam mindestens 3x die Anweisung "Leicht rechts abbiegen".

Alle 3 aufgezählten fragwürdigen Anweisungen passieren nicht, wenn OSMAND die Route selbst erstellt, statt einem track zu folgen.

Einen track als Routinggrundlage zu verwenden ist in OSMAND wohl möglich, aber stellenweise unbrauchbar.

Gibt es da Verbesserungsmöglichkeiten?

Verwendetes Handy zum Navigieren: Samsung Galaxy XCover 5, Android Version 12
[Auerspergstrasse-Ofenbach.zip](https://github.com/osmandapp/OsmAnd/files/9233616/Auerspergstrasse-Ofenbach.zip)

**Comment by scaidermern** [comment]
Wenn du einfach nur einen Track zur Navigation verwendest dann verwendet OsmAnd keinerlei Informationen über die zugrundeliegende Infrastruktur, denn der Track beinhaltet diese Informationen nicht. Dadurch sind Routinganweisungen weniger hilfreich, da OsmAnd nicht wissen kann, ob eine scharfe Kurve ein Kreisverkehr oder etwas anderes ist.

Du kannst den Track jedoch auf die Straße einrasten lassen, dann gibt es Routinganweisungen in üblicher Qualität. Das geht beispielsweise folgendermaßen: Navigation / Optionen / Track folgen / Auf Straße einrasten lassen / Fortfahren / Profil wählen / warten bis der kleine blaue Fortschrittsbalken durchgelaufen ist / Anwenden. Alternativ ist das auch erreichbar über: Meine Orte / Tracks / Track wählen / Optionen / Track editieren / Auf Straße einrasten / usw. Dort kannst du den Track anschließend auch speichern. Dann speichert OsmAnd die Routinganweisungen im Track und du musst diese Berechnung später nicht erneut durchführen (außer, die Infrastruktur ändert sich).

**Comment by ReinerMeyer** [comment]
Danke für den Tip. Habe es heute ausporbiert und es funktioniert.
Das mit dem Auf Straße einrasten hatte ich schon mal vor einiger Zeit gestartet, aber nach gefühlter zu langer Zeit der Berechnung wieder abgebrochen. Braucht OSMAND länger zum Berechnen der Route, wenn es statt des eingegebenen Ziels einen track als Vorlage verwendet? Anschlußfrage: Ist es möglich die Berechnungszeit für eine Route in OSMAND zu beschleunigen? Denn für das Autorouting werden in der Regel längere Strecken eingegeben als für Rad oder zu Fuß. Die lange Berechnungszeit ist schon ein Schwachpunkt von OSMAND gegenüber anderen Routern.

**Comment by scaidermern** [comment]
Ich befürchte, da lässt sich derzeit nichts machen. Ja, die Routen-Berechnung in OsmAnd ist recht langsam.

Meinen Erfahrungen nach dauert es nicht länger den Track auf die Straße einrasten zu lassen als eine reguläre Route zum Ziel zu berechnen. Außer, es ist irgendein Sonderfall und OsmAnd hat Probleme damit, die zum Track zugehörigen Straßen zu finden.

**Comment by vshcherb** [comment]
If something needs to be fixed in the app, please create an issue in English later on.

**Comment by sonora** [comment]
@ReinerMeyer  Newer versions of OsmAnd will show the option "Attach to road" directly on the navigation dialog, see screenshot here.https://github.com/osmandapp/OsmAnd/issues/14855.


The issue that the calculation seems to often take overly long is already posted, you can follow it here https://github.com/osmandapp/OsmAnd/issues/15025.
