### ISSUE TITLE
Card oriantation button disaddears

### ISSUE THREAD

**Issue by NiepelH** [osmandapp/OsmAnd#14987]
Hello friends,
i have observed this in OSMand-version 4.2.7 (2022-07-13) on different Samsung smartphones with different versions of android: 
A separate profile is used. In the profile the map orientation is set to direction of motion. The switch for the map orientation is visible.
If i temporarily choose a different map orientation, the switch disappears. It no longer becomes visible. To return to the original orientation, I must to operate the menu.
Is this a bug?

Thanks
Hagen

**Comment by mikehgentry** [comment]
In 'Configure screen' you can set whether the compass icon remains visible. It's always visible in 'Configure map', which you can access by hitting the profile icon, whatever setting you use.

**Comment by NiepelH** [comment]
Hello mikehgentry,
this eliminates my problem!
Thanks a lot!
Hagen
