### ISSUE TITLE
Search issue for Stresa town (iOS)

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#14983]
While searching in the list of result the Stresa town does not display on the top of the list, even if the map is centralized in the town.
While search by address ->Select city->The Stresa is found, but the Show on the map button is not available, so you cannot check if the correct city found.
<table style="width:100%">
      <tr>
<th><img src="https://user-images.githubusercontent.com/80623554/182113049-079aed9c-8700-4cd6-a858-a4a30fbf5610.jpeg"  width="auto" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/80623554/182113015-85f04e15-f2d6-43e2-b705-bce46c26f44f.jpeg"  width="auto" height="auto"/> </th>
  </tr>
</table>

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2217
