### ISSUE TITLE
OsmAnd doesn't support URI type geo:// 

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#1499]
![screenshot_2015-07-17-22-16-53](https://cloud.githubusercontent.com/assets/12711814/8877056/21b6db34-322c-11e5-9cf2-66dc8088f5d0.png)
![screenshot_2015-07-17-22-15-36](https://cloud.githubusercontent.com/assets/12711814/8877057/21ba2ff0-322c-11e5-8194-b2dd106f9845.png)

**Comment by vshcherb** [comment]
Application Photo uses wrong format
