### ISSUE TITLE
Custom POI display disappears automatically when screen turns off (or switching apps)

### ISSUE THREAD

**Issue by mnalis** [osmandapp/OsmAnd#14993]
### Description
If I have custom POI display enabled, when display turns off (or I switch to another app and back to OsmAnd), custom POI overlay is **_turned off automatically_**. I would expect the custom POIs to remain being shown, just like regular built-in POI overplay remains being shown. 
It is _very_ annoying and makes custom POIs practically unusable :cry: 

### How to reproduce?
- Create a custom POI search (i.e. `Search` / `Categories` / `Custom search`)
- Enable showing that custom POI in `Configure map` / `POI overlay`
- notice POIs are correctly displayed in orange circles
- wait for screen to turn off (or switch to another app and back to OsmAnd)
- when back in OsmAnd, notice that all orange circles have disappeared!

Video:

https://user-images.githubusercontent.com/156656/182373614-a077a24f-93b0-44f6-874c-a29687aa35d9.mp4

 
### Your Environment
OsmAnd Version: OsmAnd~ 4.2.6 (F-droid latest)
Android/iOS version: Android 10
Device model: Huawei P30 Pro

**Comment by scaidermern** [comment]
Strange. Can't reproduce this with OsmAnd 4.2.7 from Playstore. Neither with nor without enabled OpenGL.

**Comment by mnalis** [comment]
It was with disabled OpenGL (default). I've now tried enabling it and restrarting app, but I can see no difference (in this bug happening or otherwise). I've also tried enabling `Safe mode` in app, and it also does not change the situation.

**Comment by vshcherb** [comment]
Also didn't manage to reproduce yet.

**Comment by scaidermern** [comment]
> Here it is attached (I've just renamed it from `.osf` to `.osf.zip` to get it to upload). Can you reproduce it with that, @scaidermern and @vshcherb ?
> 
> [Export_09-08-22.osf.zip](https://github.com/osmandapp/OsmAnd/files/9288341/Export_09-08-22.osf.zip)

Yes, I can reproduce it with your POI filter. Turning the screen off and on again or switching between apps makes these POIs disappear.
