### ISSUE TITLE
Intermediate zoom and OpenGL pinch zoom behavior

### ISSUE THREAD

**Issue by Icelk** [osmandapp/OsmAnd#15009]
# 🚀 feature request

### Description

It would be nice to be able to zoom less then the zoom layers. When you zoom, the zoom level snapps to the closest layer. Keeping the zoom level where the user left it gives a more responsive feel

### Describe the solution you'd like

Keep the zoom level from the zoom animation without snapping it to the nearest zoom layer.

### Describe alternatives you've considered

None

Thank you for the great app!

**Comment by arncor** [comment]
I don't see how it would be easily feasible. Rendering is done differently for different zoom levels, how would it interpret non-integer zoom level?

**Comment by scaidermern** [comment]
> I don't see how it would be easily feasible. Rendering is done differently for different zoom levels, how would it interpret non-integer zoom level?

Via `=>` and `<` instead of `==`. This should be easy to solve.

**Comment by scaidermern** [comment]
> > I don't see how it would be easily feasible. Rendering is done differently for different zoom levels, how would it interpret non-integer zoom level?
> 
> Via `=>` and `<` instead of `==`. This should be easy to solve. There might be other problems, though.

**Comment by Icelk** [comment]
I think the rendering part is already solved, as when doing the pinch gesture, the zoom is in intermediate levels.

**Comment by arncor** [comment]
> I think the rendering part is already solved, as when doing the pinch gesture, the zoom is in intermediate levels.

When pinching, it doesn't seem to render anything. It seems that it rather magnifies the image like it would with a bitmap image.

**Comment by scaidermern** [comment]
> > I think the rendering part is already solved, as when doing the pinch gesture, the zoom is in intermediate levels.
> 
> When pinching, it doesn't seem to render anything. It seems that it rather magnifies the image like it would with a bitmap image.

Without OpenGL your observation is correct. With OpenGL the map gets constantly rerendered (although without any POI icons or labels).

**Comment by arncor** [comment]
> > > I think the rendering part is already solved, as when doing the pinch gesture, the zoom is in intermediate levels.
> > 
> > When pinching, it doesn't seem to render anything. It seems that it rather magnifies the image like it would with a bitmap image.
> 
> Without OpenGL your observation is correct. With OpenGL the map gets constantly rerendered (although without any POI icons or labels).

Ah! I didn't know that, I'm using the Fdroid version. Well the openGL Playstore version really seem to be vastly superior!

**Comment by sonora** [comment]
Carry-over from #15034:

The "on-the-fly magnification" by pinch-zooming the map to better read small text (as featured in the Version 1 engine) also works perfectly for the "normal" map layer in OpenGL (roads, buildings, etc.), issue is simply that here all text labels immediately disappear when starting to pinch-zoom. Any solution or workaround feasible? It's real nuisance about the Version 2 engine...

**Comment by vshcherb** [comment]
Yes, during animation we should really limit of how many labels / icons disappear probably we should keep map zoom "frozen" until fingerpoints are released. Also it wouldn't be bad to keep increasing / decreasing text size during such animation

**Comment by sonora** [comment]
@vshcherb Any chance of putting "**_we should keep map zoom 'frozen' until fingerpoints are released_**" in a near-future sprint, mainly because #15034 "**OpenGL: Pinch zoom to magnify text fails**" is a big showstopper for some users and use cases switching to OpenGL?

**Comment by vshcherb** [comment]
It definitely not planned for 4.3 cause it's already sealed it's about intermediate zoom. I don't think we will keep map zoom 'frozen' cause with intermediate zoom the switch to higher zoom will be around 50%. 

> "OpenGL: Pinch zoom to magnify text fails"

So in reality it's not planned for now as we suggest to increase Text Scale. I don't see that feature in other app so I doubt if we get it back it will be by default

**Comment by sonora** [comment]
I kinda liked the behavior we have had for years to trigger the re-render _after_ and not during the pinch-zoom gesture. What's the harm in keeping this feature?

**Comment by vshcherb** [comment]
I don't think we deleted on purpose it's new rendering engine it does things differently. We still need to collect feedback

**Comment by sonora** [comment]
Sure  My feedback is that it's not solely about text (as already described in #15034), but about the entire map bitmap, i.e. all map details. I e.g. use it in steep terrain if I need to see the local countour line structure more clearly, whereas otherwise I have my countour lines displayed rather thinly and unobstrusively.

Losing this feature us currently my biggest showstopper why I do not use v2 rendering on my tours.

I am not at all against intermediate zooms etc. All I am saying is it has significant advantages if **for the use case of someone using 2 finger pinch zoom** we go back to the v1 behavior that
 - re-rendering the map only starts when you take your fingers off the screen,
 - and before that we simply scale (stretch/shrink)  the **existing bitmap** accordingly.

**Comment by scaidermern** [comment]
I fully support the suggested improvements by @sonora. No re-rendering while zooming via two finger pinch (as with the v1 rendering engine) allows to increase the readability of the map and also reduces ressource usage regarding slower devices and battery consumption

**Comment by erik55** [comment]
Yes please. This will make the usage feel fast again as opposed to the feeling of slow rendering as described and shown in videos in #15977. Also please stop this unnecessary waiting of showing the favorites. 

Why is this implemented by the way, that there is a break of some seconds until the favorites are displayed? I like it much more like it was in rendering v1.

**Comment by Icelk** [comment]
Can we consider adding a setting to change between the two behaviours? Not rendering while zooming can cause unwanted pixelation.

Either way, I don't think this is relevant to this issue, maybe another should be opened? My feature request is merely about storing fractional zoom levels, and how to show text and POIs in that case.

**Comment by sonora** [comment]
I know. I only bring it up here because the original issue https://github.com/osmandapp/OsmAnd/issues/15034 about this was closed-merged into here, likely because in terms of implementation there is a close relationship between the two.

(Regarding a setting: That's not even under consideration yet, because the question is first if we cannot re-create under v2 the behavior we have used forever (and still do) in the v1 engine where nobody had an issue with.)

**Comment by vshcherb** [comment]
No rerendering is not an option at all, in opengl we render all frames especially with fingers interaction. There is a small camera movement as +- 0.5 zoom but I don't think it's possible compensate, so in the end it's a big refactoring with no clue what value it brings at all.

This issue is primarily about saving intermediate zoom but we're going investigate along with it what's possible to do with pixelation interaction

**Comment by erik55** [comment]
Maybe we don’t need intermediate zoom, but just remove the annoying gray areas (not rendered yet): https://user-images.githubusercontent.com/1608326/208079606-f0ede1df-23da-4646-afa6-1767cb29a911.mp4



As opposed to this, where the details (names, numbers etc) also appear later (softly faded in!!), but nothing is gray: https://user-images.githubusercontent.com/1608326/208079625-1b1d2afe-e835-471b-a39a-cf5226e41b42.mp4

**Comment by sonora** [comment]
Isn't it true that OpenGL renders into a buffer, so easentially what it takes to recreate the effect of immediate zooning is to keep the old content displayed (stretched as pinch-zoomed, but that seems implicit functionality anyway) until the user takes their fingers off the screen, then simply swap the new and already rendered buffer to become visible instantaneously?

**Comment by vshcherb** [comment]
Well it's not a big deal to implement, I hope... but not much in  details so far.

**Comment by vshcherb** [comment]
Linked https://github.com/osmandapp/OsmAnd/issues/3928

**Comment by Icelk** [comment]
Great! Thanks

**Comment by erik55** [comment]
I don't know what exactly you did but the GL-rendering is much better now. Thank you for your work!!
