### ISSUE TITLE
Opengl: public transport route not showing

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#15005]
### Description
 When you click on a public transport stop and select a specific type of public transport, its route and stops are not displayed on the map.
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/12549744/182747723-0c2e8050-fe7d-4fe2-ae4d-4884c4c33167.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13688mqta, Дата выпуска: 2022-08-03
Android version: 12
Device model: poco f3

**Comment by Zirochkabila** [comment]
Tested with version (OpenGL) 4.3.0#13697mqta, released:2022-08-08 - failed to reproduce. Transport stops are displayed on the map.

Try to apply the settings that are shown in the video.


https://user-images.githubusercontent.com/104760013/183425540-eb9d9a4a-600b-4613-9472-f0f2501c4934.mp4

**Comment by Nine-Tailed** [comment]
@Zirochkabila, вы включили показ остановок, так работает, но при выключенном опенгл, работает и без этой опции, даже если вообще транспорт выключен, то нажатие на остановку и выбор маршрута, отобразят его на карте с его пунктами остановки. 
А в опенгл оплачивается скрин без маршрута и остановок, но при этом внизу есть кнопки перехода к следующей остановке.

**Comment by Zirochkabila** [comment]
Yes, you're right, thank you!
It's a bug.
