### ISSUE TITLE
OpenGL: Position icon while navigating or moving

### ISSUE THREAD

**Issue by LeLuyen** [osmandapp/OsmAnd#15006]
Hi All,

When enabled OpenGL rendering, the position icon while navigating or moving is not smooth.

When disabled OpenGL rendering, the position icon while navigating or moving is smooth.

### How to reproduce?

https://user-images.githubusercontent.com/2620445/182765512-5d35ebe3-4110-43bd-8b30-e436bf465fd2.mp4

https://user-images.githubusercontent.com/2620445/182765738-5008c600-ba8a-4bdb-acd5-456f8890a6f4.mp4

### Your Environment
OsmAnd Version: 4.2.7
Android/iOS version: Android 10
Device model: Samsung Galaxy Note N960FXXS9FVD2

**Maps used (online or offline): offline

**Comment by vshcherb** [comment]
We fixed in nightly already but we don't want to re-relelease 4.2 cause OpenGL is in Development still
