### ISSUE TITLE
Bicycle routing: Strange detour with enabled elevation data

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#15012]
OsmAnd 4.2.7 calculates a long and unnecessary detour in bicycle mode when elevation data is enabled.

Left: elevation data off, right: elevation data on.

![foo](https://user-images.githubusercontent.com/1040784/183065036-2be5634e-af48-4aa0-a3cd-9806c2a9808b.jpg)

Bicycle routing is set to balanced.

From: 51.05419, 13.75852
To: 51.05384, 13.75720

[route.gpx.txt](https://github.com/osmandapp/OsmAnd/files/9268014/route.gpx.txt)

There is no elevation difference at this location in reality.

**Comment by Zirochkabila** [comment]
version 4.2.7 - reproduce

route without using elevation data - cost 57
https://osmand.net/map/?start=51.054304%2C13.758670&end=51.053913%2C13.757190&mode=bicycle#18/51.05392/13.75843

route using elevation data - cost 181
https://osmand.net/map/?start=51.054304%2C13.758670&end=51.053913%2C13.757190&mode=bicycle#18/51.05412/13.75841

OSM
https://www.openstreetmap.org/way/723249769#map=19/51.05408/13.75789

**Comment by vshcherb** [comment]
Not clear what's going in relief data. So it doesn't look like a bug with routing engine but not clear issue with coefficients or with our SRTM data

**Comment by Zirochkabila** [comment]
This is most likely a problem with our SRTM data - since the route https://osmand.net/map/?start=51.054304%2C13.758670&end=51.053913%2C13.757190&mode=bicycle#18/51.05392/13.75843 passes on a straight road (no hills or descents), in fact, this is clearly shown in the first photo of the user

**Comment by xmd5a2** [comment]
Looks like a routing engine bug
**Straight route:**
![Screenshot_2022-09-06_10-22-44](https://user-images.githubusercontent.com/5829014/188572332-505dae9e-b88d-44c9-bb2c-f9688e9336e0.png)
`routing_time=228,5`
1 m climbing

**Detour:**
![Screenshot_2022-09-06_10-27-23](https://user-images.githubusercontent.com/5829014/188573142-dcf0a14f-020a-4ce1-8902-4296af73fc30.png)
`routing_time=203,8`
6 m climbing

**Comment by Isolator70** [comment]
I have the very same issue here with OsamAnd+ v. 4.2.7 @Huawei P10 (Android 9):
If the elevation is taken into consideration by OsmAnd, the planned route becomes very weird and OK again if no elevation data is used.
Position A: 50.54640° N, 8.48160° E
Position B: 50.54633° N, 8.48170° E

![photo_2022-09-17_12-10-04](https://user-images.githubusercontent.com/35434137/190851744-7cf5c8d8-51c2-4571-a910-30952bde0b92.jpg)
![photo_2022-09-17_12-10-08](https://user-images.githubusercontent.com/35434137/190851749-45dd6f2d-c276-424c-9322-b411a207309a.jpg)
![photo_2022-09-17_12-10-13](https://user-images.githubusercontent.com/35434137/190851756-64899878-713f-40f8-a5e7-e3d48ee2aba7.jpg)
![photo_2022-09-17_12-10-16](https://user-images.githubusercontent.com/35434137/190851764-8c1ea114-ca01-405c-9c0c-ddfd920b8f0c.jpg)

**Comment by vshcherb** [comment]
@Isolator70 confirmed, it's also related to the height data - cost is very high 360 sec (ele) vs 12 sec (flat)

**Comment by dmpr0** [comment]
@vshcherb Is there any description how **Use elevation data** works?

**Comment by vshcherb** [comment]
@dmpr0 Use elevation data on should choose route that will have less total uphill and avoid sharp climbs in compromise of a longer route (more time). Clearly in that case there was a bug.

Formula how much time is added for each 1m uphill could be taken from routing.xml

**Comment by vshcherb** [comment]
Each meter up takes extra Time (sec) based on Incline:
- < 3% - 2 s per meter up
- 3-7% - 8 s per meter up
- 7-13% - 16 s per meter up
- 13-25% - 32 s per meter up
- > 25% - 48 s per meter up
