### ISSUE TITLE
Inaccuracy in 'Analyze on map' number display

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#15019]
Possibly we use integer cutoff instead of proper rounding:

Have your Pedestrian profile default speed set to 4 km/h (which is our default), calculate a route with "Use elevation data"=off, and investigate it using 'Analyze on map': The speed marker on the graph shows "14min/km", but it should of course be 15. Probably the same mistake for elevation etc. markers, only less significant there.

![Screenshot_20220806-145141_OsmAnd~](https://user-images.githubusercontent.com/845735/183249735-6900bf9a-7b0a-48fb-9bfd-e5028325dbc6.jpg)

**Comment by sonora** [comment]
Proper rounding here does fix it:
https://github.com/osmandapp/OsmAnd/blob/b33dbc19cd83c49dc4905fc2badd97620e64eda7/OsmAnd/src/net/osmand/plus/helpers/GpxUiHelper.java#L1515-L1518
but I guess rounding should happen when extracting the values, not when creating them. Also: this is integer-divison, should it be `/ 60.0f`?

**Comment by sonora** [comment]
@vshcherb I think this is a valid fix: https://github.com/osmandapp/OsmAnd/commit/a0d14c7d64137ffe4599647e0bab7803cbc66fa5, maybe someone wants to review before closing.

**Comment by vshcherb** [comment]
I think if it's tested, the fix is correct. The logic of the code looks good but validation of corner cases is hard to get from the code reading.

**Comment by dmpr0** [comment]
> I think if it's tested, the fix is correct. The logic of the code looks good but validation of corner cases is hard to get from the code reading.

how to test?
