### ISSUE TITLE
Show/hide layer of the downloaded maps

### ISSUE THREAD

**Issue by ubikitty** [osmandapp/OsmAnd#15011]
Some people including me find the green overlay quite disturbing when viewing maps from afar.

It would be nice to have a menu entry like the one found under the [configure map] / [contour lines - terrain], where we can activate deactivate the option and use the widget to choose the zoom level where it is active.

Thanks

**Comment by FilippoGuenzi** [comment]
I would like that too

**Comment by dmpr0** [comment]
Proposed name `Show borders of downloaded maps`
![Screenshot 2022-10-06 at 17 20 20](https://user-images.githubusercontent.com/9365308/194337716-19bdc3c3-ab97-4641-860b-5ab667a712b0.png)

**Comment by EugeneZmeuk** [comment]
https://osmand.net/docs/user/map/vector-maps

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/map/vector-maps#show-borders
https://osmand.net/docs/user/map/configure-map-menu#map-layers
