### ISSUE TITLE
'position not yet known' on GrapheneOS

### ISSUE THREAD

**Issue by KiaraGrouwstra** [osmandapp/OsmAnd#15015]
### Description

I've yet to be able to get my location on this app.
GPS data downloaded date does appear to be current. additionally, other apps like satstat seem to get my location just fine.
issue persists with or without play services enabled.

also see #7517

### How to reproduce?

- try to use osmand
- grant location permissions
- try to go to my location
- always get 'position not yet known'

### Your Environment

OsmAnd Version: 4.2.6
Android/iOS version: GrapheneOS 12 July 2022
Device model: Pixel 5

**Comment by scaidermern** [comment]
Is your OsmAnd from F-Droid or from the PlayStore?

**Comment by KiaraGrouwstra** [comment]
@scaidermern it is from F-Droid.

**Comment by sonora** [comment]
Have you tried both options in `Settings / OsmAnd settings / Location source`?

**Comment by KiaraGrouwstra** [comment]
thank you, that did it for me!
