### ISSUE TITLE
OpenGL: Map empty after base map update until app restart

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#15029]
With enabled OpenGL a base map update leads to an empty map. The new map won't get rendered. After restarting OsmAnd everything is fine again. I could reproduce this behavior several times.

OsmAnd 4.2.7, Android 10, Galaxy S9

(yay, my 250th issue :tada:)

**Comment by scaidermern** [comment]
@vshcherb The opengl label is missing for this ticket.

**Comment by vshcherb** [comment]
We have 1 label per ticket, this is a duplicate actually

**Comment by scaidermern** [comment]
A duplicate of what? The other ticket which came half a year later? 🤔

**Comment by vshcherb** [comment]
Original issue was not reproduced and it was kept open cause it was related to OsmAnd Live. Anyway it's always better to have new issue as main cause it doesn't has long history to read and usually has a clear path to reproduce
