### ISSUE TITLE
Add nested groups to manage favorites

### ISSUE THREAD

**Issue by TheSnoozer** [osmandapp/OsmAnd#15028]
# 🚀 feature request
Thanks for the great app. haven't found a similar ticket. I really like the ability to add your favorites into a group, but for me it's getting messy already. So perhaps as feature request: Would there be the ability to add a group to manage favorites? Effectively allowing to create a tree of favorites with sub-x-groups?

**Comment by scaidermern** [comment]
Duplicate of #9967.

**Comment by TheSnoozer** [comment]
thanks didn't found it while searching!
