### ISSUE TITLE
The pointer line is too thin

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#15026]
See this screnshot,it is hard to spot to what exact point on the graph the poiinter data ("446m ...," etc).applies, because the vertical pointer line is just too thin.

Should probably have the same thickness as the frame around the pointer numbers.

![Screenshot_20220806-235345_OsmAnd~](https://user-images.githubusercontent.com/845735/183267365-5f831540-c61b-401a-b279-ced9870ed9fc.jpg)

**Comment by arncor** [comment]
I did notice that too
