### ISSUE TITLE
feature request: road width selection in truck profile navigation

### ISSUE THREAD

**Issue by wurst0r** [osmandapp/OsmAnd#15020]
Hi, 
i was wondering if it would be possible to implement an option for the truck profile in the navigation where you can select the min. size/width of the roads to be used. Right now navigation sometimes sends you down ridicilously small roads when navigating through the truck-profile. At least the truck parameters are considered when plotting the course... 

it would though be very usefull to be able to limit navigation to refrain from using small roads, and only go for motorways/interstate roads and the like :)

thanks in advance for all the effort xoxoxo

**Comment by vshcherb** [comment]
You can already specify Navigation Settings -> Vehicle parameters -> Width limit.

**Comment by scaidermern** [comment]
> You can already specify Navigation Settings -> Vehicle parameters -> Width limit.

This uses the `maxwidth` tag, doesn't it? If I understood correctly the `width` tag should be used instead or additionally.

**Comment by vshcherb** [comment]
Hm... is it correct then?

**Comment by scaidermern** [comment]
From a legal point of view the maxwidth tag is relevant. However there could be situations where no legal restriction is present but only a physical one (width tag).

This could happen in very rural areas, maybe.
