### ISSUE TITLE
'Analyze on map' speed vs. time graph has gaps

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#15022]
This bug has been around for some time:

When you calculate a pedestrian route, then investigate it using Details/'Analyze on map', the 'speed' curve looks ok when plotted vs. distance, but has gaps where it drops to zero when plotted vs. time. This is independent of whether "Use elevation data" is selected or not, but seems to occur only for pedestrian routing.

**Ok vs. distance:**
![Screenshot_20220806-161338_OsmAnd~](https://user-images.githubusercontent.com/845735/183252675-17da2422-7f39-495f-a3e4-b2ed688b52a5.jpg) ![Screenshot_20220806-162800_OsmAnd~](https://user-images.githubusercontent.com/845735/183253169-c4790625-65ad-4ecc-9d46-18b716961a29.jpg)

**Gaps vs. time:**
![Screenshot_20220806-161746_OsmAnd~](https://user-images.githubusercontent.com/845735/183252791-43030e41-6053-4513-9fdc-6ce3ea35a3da.jpg) ![Screenshot_20220806-161121_OsmAnd~](https://user-images.githubusercontent.com/845735/183252539-bd2a5156-50fa-475e-add8-63dd584fc7ec.jpg)

**Comment by tenzap** [comment]
Left pictures is **without** "use elevation data" and right ones **with**?

Whether I use elevation data or not, the speed always looks like your left pictures.

Contours lines are downloaded (for both the region and the country relevant to the track) and the "contour lines" plugin is enabled too.

What am I missing?

**Comment by tenzap** [comment]
![Imagepipe_13](https://user-images.githubusercontent.com/46226844/183295412-4fca684f-8e61-44a7-871e-bda02653bb5a.jpg)

**Comment by sonora** [comment]
@tenzap That is a separate issue I fixed only yesterday, so you have to use our nightly development  build or wait for a new release to see it fixed.

**Comment by sonora** [comment]
PS: I think there is also an issue with the time plot for other profiles, look at the distance and time plot forthis short (car) driving route going steadily straight up a hill, and how  a discontinuity in the elevation data is suddenly displayed in the time domain.

![Screenshot_20220808-080143_OsmAnd~](https://user-images.githubusercontent.com/845735/183350455-146ef4e6-7bc2-477d-b746-d59449c36902.jpg) 
![Screenshot_20220808-080152_OsmAnd~](https://user-images.githubusercontent.com/845735/183350500-3b448324-01df-4097-a442-69e09ad25747.jpg)


It is further unclear why we always miss displaying speed and slope data for the first (and sometimes also the last) routing section, and why the Altitude/Slope curves do not allow being plotted vs. time, but this may deserve separate issues.

**Comment by vshcherb** [comment]
Is it already fixed or not? I'm Confused with last screenshots

**Comment by sonora** [comment]
No, it's not fixed. The last 2 screenshots are for a **car** navigation profile, where I never see gaps (gaps seem to appear only for pedestrian routes).

It is almost like for the pedestrian routes sometimes the segments are deemed **too short**, so that plotting them vs. Time  yields gaps between them, while in the case shown for the car profile the first segment seems to be stretched **too long**, so that then plotting the segment overlaps its end and creates the jump in the blue elevation curve.

Somehow I believe we miscalculate the exact length of each segment when we plot them vs. time.

**Comment by sonora** [comment]
PS: Instructions see first post. The gaps can be reproduced using essentially **every** OsmAnd-calculated pedestrian route.

**Comment by sonora** [comment]
Looks like the "gaps" are always the same map segments,  regardless of which pedestrian route you calculate traversing them, or the direction you traverse them. Also, they seem to be always straight stretches on the map.

**Comment by sonora** [comment]
Candidates:
https://github.com/osmandapp/OsmAnd/blob/4fbe7055ca38d1be74a9204d3e3e472ebc4325b7/OsmAnd-java/src/main/java/net/osmand/router/RouteResultPreparation.java#L234-L237

**Comment by sonora** [comment]
Not sure it's related, but here is an interesting snippet of a **car** route around a corner at 49.65724° N, 12.19951° E.

Look at how the graph indicates it takes 57 seconds for the last few meters on the primary before the turn, that seems wrong?

![Screenshot_20220826-095332_OsmAnd~](https://user-images.githubusercontent.com/845735/186853482-c2bb8dd6-e04a-485e-8856-8063aaed21e3.jpg)
![Screenshot_20220826-095342_OsmAnd~](https://user-images.githubusercontent.com/845735/186853520-0cfe21a6-63ac-4813-9435-899efd79b5f9.jpg)

**Comment by sonora** [comment]
I have found out (by sweeping a finger across the graph in 'Analyze on map' mode) that the pedestrian routing introduces _additional routepoints_, immediately before all such "gap" segments. Those extra route points are not visible in equivalent bike or car routes traversing the same stretches.

In the cases I have checked, these "extra points" were inserted always 1 (pedestrian) second after an existing route point.

Here is an illustration:
- The point in the first screenshot (for this ped route at time 2:24) is present in ALL routes turning at this corner (car, bike, ped).
- The point shown in the second screenshot (or this ped route at time 2:25, at the beginning of a gap) is ONLY present in the pedestrian routing. The straight routing stretch behind it (here to the left) is a "gap" in the speed vs. time graph.

![Screenshot_20220906-203111_OsmAnd~](https://user-images.githubusercontent.com/845735/188715376-34548ea5-ff1f-430e-8cdd-9ea296997d4b.jpg) ![Screenshot_20220906-203124_OsmAnd~](https://user-images.githubusercontent.com/845735/188715372-12a16609-1206-4c3a-84e6-c81989e3c963.jpg)

**Comment by vshcherb** [comment]
Should fix https://github.com/osmandapp/OsmAnd/issues/15284 as well

**Comment by cepprice** [comment]
@sonora

1) Can you please give an example of route start/end points, when **altitude** graph differs according to x-axis (distance vs time) like [here](https://github.com/osmandapp/OsmAnd/issues/15022#issuecomment-1207706964)?

2) Not drawing slope at start and end of the graph is correct. To calculate slope of point, you need at least one previous and one next point.

**Comment by sonora** [comment]
@ceppice: I went back to my notes and unfortunately find no note where I took those screenshots, so I looked for a new location: This is another short stretch of highway also going rather steadily uphill for clarity. You need the United States/Nevada map, I have the Sept. 1, 2022 edition: Start is at 35.18616°N, 114.61642°W, destination is at 35.20099°N, 114.66977°W (car route). Looks like there are even 3 occurrences on this short stretch with a small elevation discontinuity shown in the time view. Hope this helps!

![Screenshot_20221111-174022_OsmAnd~](https://user-images.githubusercontent.com/845735/201388791-7bdfc7ac-c520-4d9d-bf21-ec7345c51d22.jpg)
![Screenshot_20221111-174030_OsmAnd~](https://user-images.githubusercontent.com/845735/201388798-c7de3016-4596-4b96-b18c-0ec0ae891965.jpg)

**Comment by sonora** [comment]
@cepprice Good work, thanks! ;)
