### ISSUE TITLE
Inconsistent icon for track visibility button

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#15031]
The track visibility button (the eye symbol) is used inconsistently. The track menu displays a different icon than the track options menu.

Track menu. Left: track visible -> eye crossed out, right: track invisible -> eye normal
![track](https://user-images.githubusercontent.com/1040784/183355226-06ea716f-9135-4907-a3a7-285f24d6fad4.jpg)

Track options. Left: track visible -> eye normal, right: track invisible: eye crossed out
![options](https://user-images.githubusercontent.com/1040784/183355027-41654045-a9ab-4eab-b44a-42e4e830550b.jpg)

Personally I prefer the second version. track visible == eye normal, track invisible == eye crossed out. The other version is confusing and feels wrong. I already mentioned this in #14599 but unfortunately there was no reaction from the developers.

**Comment by vshcherb** [comment]
No, it's rather a UI/UX discussion. In which I agree with following statement:
 Button always symbolizes an action and toggle represents a current state. 
 
Actually now I think it's not confusing but anyway color of the line indicates the state itself
