### ISSUE TITLE
Missing speed and slope displays at the beginning and end of routes

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#15030]
Reminder to investigate if there is a systematic issue with calculation or just display: 

This is the Altitude/Slope plot for the short, steadily uphill route of   https://github.com/osmandapp/OsmAnd/issues/15022#issuecomment-1207706964, where the corresponding Altitude/Speed plots are. Note how a slope display(green curve)  is missing for the beginning and end of the route.

The same is true for the speed curve, but it is missing for a shorter section only.

![Screenshot_20220808-081422_OsmAnd~](https://user-images.githubusercontent.com/845735/183353458-b8b15bb5-e93f-4655-bfcf-c763902518fa.jpg)
![Screenshot_20220808-080143_OsmAnd~](https://user-images.githubusercontent.com/845735/183353479-ef670908-6a1e-4c91-9401-a0f9efe98517.jpg)

It is unclear why we miss assigning (or just displaying) slope and speed data for the first and last route sections.

Also, possibly related: The Altitude, Slope, and Altitude/Slope curves are only offered to be plotted vs. Distance, not vs. Time. There seems no obvious reason why not?

**Comment by vshcherb** [comment]
Nope it's done according algorithm, probably it should be documented somehow.

Slope graphs are drawn based on average altitude around point. Slope is calculated by formula (x_(n+1) - x_n) / D. Where x_n is an average altitude of D meters around the point. D is hard coded to 30 meters.  So for first 60 meters it couldn't be calculated.

Even though it's possible to calculate theoretically but practically it won't be average altitude any more, so the slope will be much less consistent and could produce large errors, so it's easier to trim

**Comment by sonora** [comment]
Right. So it's not a fundamental mistake, but we rather have a small display error to the effect that in the beginning and end we really have "**slope=NaN**", while our marker there falsely displays "**slope=0%**", as seen in screenshot 1.

But regarding speed? We explicitly assign speed values to to all routing segments (and thy are valid for the entire segment) like e.g. here ,

			if (usePedestrianHeight && (distOnRoadToPass != 0)) {
				rr.setSegmentSpeed((float) (distance / distOnRoadToPass));
			} else {
				rr.setSegmentSpeed((float) speed);
			}
Or have speed values for all points of a recorded track. So why would there be gaps in the speed plot at the beginning and in the end? If it's only the way we plot, it is a mere technicality, but it could be connected to #15022?

**Comment by vshcherb** [comment]
Speed probably a UI error cause it looks like trimmed similar to slope where it should n't be trimmed at all.

**Comment by Chumva** [comment]
Looks like it was fixed [here](https://github.com/osmandapp/OsmAnd/pull/15717)
