### ISSUE TITLE
Context menu Map Download - Unit of contour line files not visible

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#15047]
Same problem as in https://github.com/osmandapp/OsmAnd-iOS/issues/2096.

Two contour line maps for download, no information which one is in meters and which in feet:

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/1040784/183664344-35c045f8-83bb-4143-aea0-dd4ef8e7da32.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

The map details also don't contain this information:
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/1040784/183664890-b69e3a7c-5c1d-4d06-9404-4fa991fc0c7e.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
4.3.0#13700mqta, released: 2022-08-10 - reproduce

Perhaps a brief description of the differences between the cards should be added
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/183867627-9c430e91-3043-4d1d-ad18-d60a4a5e384a.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/183867633-95d9ab62-ef0c-4062-bf48-17b568037247.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
Option A. display only 1 which according to currently selected units. Option B. provide more description
