### ISSUE TITLE
Removing all tracks doesn't remove folder

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#15046]
At the moment is not possible to remove track folder.
If you delete all tracks the folder will disappear, but if you try to move track to another folder deleted folder will be displayed in the list of folders, so you can put tracks for it. As a result, is not possible to remove track folder forever. 
Look at the screenshots below, I tried to delete Test folder. 
<table style="width:100%">
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/80623554/183661695-5ea3ff77-4af3-422c-b62d-d469dfb45966.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/80623554/183661966-7a8bb712-4cbe-4493-ad8a-432b5b17b3d2.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
You have bulk delete in My Places

**Comment by anastasiia936** [comment]
I deleted by bulk delete, tracks deleting, but the folder still exists in the list.

**Comment by dmpr0** [comment]
It will be implemented after the My Places > Tracks redesign.

**Comment by 0xRe1nk0** [comment]
**Pull Request**
https://github.com/osmandapp/OsmAnd/pull/15103
