### ISSUE TITLE
Extremely Poor Performance/Framerate

### ISSUE THREAD

**Issue by seniorm0ment** [osmandapp/OsmAnd#15055]
Noticing extremely poor performance on my device. Full battery, good signal.
I have tried offline and online maps.
Around 10-20fps. 14 average.

It makes doing anything with the map feel extremely slow and aggravating.
I'm not even displaying POIs, just a few favorites show and that's all.

Zooming out, half of the map takes a while to load in. Lots of white empty tiles.
Zooming in, text takes a while to load in.

I have not encountered performance issues with Snapchat's map, nor Waze but I would prefer to just use OSM. This is a major issue for me.

Device: Pixel 6 Pro
OS: GrapheneOS
Version: F-Droid 4.2.6

Also encountered the same issues on a stock OS LG-V40.

**Comment by vshcherb** [comment]
Please try OpenGL Engine in Develpment Plugin -> Settings

**Comment by seniorm0ment** [comment]
Has been enabled, it's broken on the F-Droid build though. However this issue is present when disabled too.
Relevant #14769
https://gitlab.com/fdroid/fdroiddata/-/issues/2711

I guess I will report back when I get an update and let you know if it solves it.
Curiously, what other improvements does the OpenGL engine bring to OSM? Or just faster rendering?
