### ISSUE TITLE
OpenGL: map text ignores transparency slider

### ISSUE THREAD

**Issue by mikehgentry** [osmandapp/OsmAnd#15056]
### Description

Make a layer with text on it transparent, and you can still see the text. This is not the case with legacy rendering, and I'm assuming it's a bug.

### Your Environment
OsmAnd Version: + 4.2.7
Android/iOS version: 11
Device model: XCover 4s

**Maps used (online or offline):**   
Offline vector, doesn't seem to matter which style.

**Comment by vshcherb** [comment]
Duplicate https://github.com/osmandapp/OsmAnd/issues/14347
