### ISSUE TITLE
Wrong ETA for route with a single intermediate point

### ISSUE THREAD

**Issue by mdykierek** [osmandapp/OsmAnd#15062]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Car

### Start and end points

From: https://www.openstreetmap.org/way/538280945
Through: https://www.openstreetmap.org/way/1083142021
To: https://www.openstreetmap.org/way/632506299

### Actual and expected routes
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/27214784/184414989-c690fc9e-7870-44de-8846-e39492fcfa33.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  
2.15 km will definitely not take 40 minutes and it is not legal in Finland to do 56 km in 17 minutes (~200km/h).
Considering that the last 6km are gravel, it must have been for Juha Kankkunen.

### Is this a regression?

Don't know

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>4.2.7
</code></pre>

**Device and Android/iOS version:**
Xiaomi Mi 9T Pro, Android 11

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.
Finland, August 2022
- [ ] Online (tile / raster) maps 

**Anything else relevant?**

**Comment by Zirochkabila** [comment]
The first screenshot shows the time from start to intermediate point, 2.15 km for 17 minutes
The second screenshot shows the route without the intermediate point - 55 minutes

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/184667420-8a8daaa4-8980-4aab-947a-82ced399e012.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/184667429-2c9ba673-e445-45e3-abbc-001ef514bd1d.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>
