### ISSUE TITLE
The screen turns white when you rotate the device

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15065]
### Description
The screen becomes white when the device is rotated to the horizontal position
[logcat (4).log](https://github.com/osmandapp/OsmAnd/files/9331178/logcat.4.log)

### Steps to reproduce
Rotate the device to the horizontal position

### Actual result
The screen turns white

https://user-images.githubusercontent.com/104760013/184477991-8f31fa16-692a-47cd-bd8c-89c4d5066915.mp4

### Expected result
The map is displayed horizontally

### Your Environment
OsmAnd Version: 4.3.0#13706mqta, released: 2022-08-12
Android/iOS version: Android 11
Device model: POCO X3 NFC

**Comment by pebogufi** [comment]
I can reproduce with version #34485. (withour opengl)
For me it lools like same problem as
https://github.com/osmandapp/OsmAnd/issues/14947, 
https://github.com/osmandapp/OsmAnd/issues/15045

**Comment by vshcherb** [comment]
It doesn't look as https://github.com/osmandapp/OsmAnd/issues/14947 but it has the similar outcome. Please not that is not release issue (so it's not in 4.2) but other issues are reproducible in 4.2

**Comment by vshcherb** [comment]
it should be fixed with https://github.com/osmandapp/OsmAnd/commit/dadbd6e6fad5a01e49efe07c296d7fd06698dc53
