### ISSUE TITLE
Ridiculous routing to a restricted military area on an island

### ISSUE THREAD

**Issue by mdykierek** [osmandapp/OsmAnd#15064]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Car

### Start and end points

The final point is somewhat random. I used first thing that appears when I entered Helsinki in Search. Unfortunately it is a torpedo test station (https://www.likealocalguide.com/helsinki/torpedokoeasema-isosaarella).
The route is not useful, but the routing issue must show either a problem in routing algorithm or maps because moving the starting point a littl changes the route dramatically.

End: https://www.openstreetmap.org/way/731171929
Start of an "odd" route: https://www.openstreetmap.org/way/1007571849#map=18/62.52428/27.66942
Start of a "normal" route: https://www.openstreetmap.org/way/538354042#map=19/62.50386/27.72201

### Actual and expected routes
Ferries and about two days:
![Screenshot_2022-08-12-22-23-02-770_net osmand](https://user-images.githubusercontent.com/27214784/184429401-88b15d86-9626-44d4-9787-c53f1117cf08.jpg)
Land route 4h long:
![Screenshot_2022-08-12-22-20-17-336_net osmand](https://user-images.githubusercontent.com/27214784/184429453-f8fada5e-0230-4e54-8cfb-8352d1b70a38.jpg)

### Is this a regression?
Don't know.

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>4.2.7
</code></pre>

**Device and Android/iOS version:**
Xiaomi Mi 9T Pro, Android 11

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.
 Finland, August 2022
- [ ] Online (tile / raster) maps 

**Anything else relevant?**

**Comment by vshcherb** [comment]
The problem that area is restricted so it tries to find any other possible route cause it simple doesn't make sense to support this case cause navigation is restricted, so I would say that issue would remain closed and not fixed for now.

**Comment by mdykierek** [comment]
Well,from a point few hyndred meters away,it takes 3x shrorter land route...IMHO there is something ugly in there.On Aug 15, 2022 17:22, vshcherb ***@***.***> wrote:
The problem that area is restricted so it tries to find any other possible route cause it simple doesn't make sense to support this case cause navigation is restricted, so I would say that issue would remain closed and not fixed for now.
