### ISSUE TITLE
OpenGL: route line sometimes not updated during navigation

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#15069]
### Description

With OpenGL enabled the route line doesn't get updated often enough. Normally the route line is only displayed in front of your own position but never behind. Having the route line in front of you and behind is irritating. It looks like driving into the wrong direction. 

Examples:
![IMG_20220813_154556](https://user-images.githubusercontent.com/1040784/184497082-f273e8bb-4e31-452d-b837-22b7e2970513.jpg)
![IMG_20220813_154543](https://user-images.githubusercontent.com/1040784/184497083-243ecf44-8c7b-4c24-9b72-3317f8ac72ce.jpg)

I've moved the map a little bit so that it becomes more clear. The screenshots have been produced while standing but the same thing also happens while driving. 

### How to reproduce?

- Enable OpenGL
- Navigate

### Your Environment
OsmAnd Version: 4.2.7
Android/iOS version: multiple 
Device model: multiple

**Comment by alex-osm** [comment]
Should be fixed already

**Comment by scaidermern** [comment]
Could be, I haven't checked it again.
