### ISSUE TITLE
Parking icon blinks

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15068]
### Description
The parking icon blinks during navigation
https://www.openstreetmap.org/way/164761978#map=18/50.44125/30.44505

### Steps to reproduce
Navigation > Select point of departure 50.44049, 30.44443 > Set destination 50.44243, 30.44307 > Start
https://osmand.net/map/?start=50.440493%2C30.444435&end=50.442433%2C30.443072&mode=car#17/50.44132/30.44582

### Actual result
Parking icon blinks

https://user-images.githubusercontent.com/104760013/184494546-3ef9500d-4241-4f8e-8087-c741fae6ceb4.mp4

### Expected result
The parking icon is displayed during navigation

### Your Environment
OsmAnd Version: 4.3.0#13706mqta, released: 2022-08-12
Android/iOS version: Android 11
Device model: POCO X3 NFC

**Comment by vshcherb** [comment]
Fixed

**Comment by vshcherb** [comment]
Needs to be double check
