### ISSUE TITLE
OsmAnd shows the lanes where they are absent.

### ISSUE THREAD

**Issue by Prusaker** [osmandapp/OsmAnd#15075]
The program shows the lanes where they are absent. 

There are no lanes on the map in this place (https://www.openstreetmap.org/#map=19/53.83654/27.47686).
However, the program claims that there are two lanes.
![Screenshot_20220814-233251](https://user-images.githubusercontent.com/32092837/184554222-55fe3484-274e-498d-b279-eb3a967b1a29.png)

This bug is reproduced at intersections, where one of the roads smoothly turns to the side.
This bug is misleading when moving along the route, as it shows the lanes that non -existent on the map :(

OsmAnd Version: 4.2.7
Android/iOS version: 6
Device model: Lenovo Tab 2 A10-70F

**Comment by vshcherb** [comment]
It should be merged with this https://github.com/osmandapp/OsmAnd/issues/13829
