### ISSUE TITLE
Don't show destinations the whole OSM-track

### ISSUE THREAD

**Issue by Neuwessi11** [osmandapp/OsmAnd#15071]
### Description
issue #12619 should be solved, but it is still not solved.

### How to reproduce?
E.g. navigate from 60.46023, 14.84255 to 60.42168, 14.85214
Prior to the first junction is shown "Salån", which is correct. This should disappear after the junction, but it doesn't. Instead it shows up the whole OSM-track.
Then for some metres is shown nothing, until prior to the next junction is shown "Höglinda", which is correct again. This should disappear after the junction, too, but it also does not. Instead it is shown until the end of navigation, because the navigation stops before the end of the OSM-track.

### Your Environment
OsmAnd Version: 4.2.7
Android/iOS version: 9
Device model: Cat S61

**Maps used (online or offline):**   offline, Sweden_dalarna_europe.obf (01.08.2022) + Sweden_dalarna_europe_22_08_09.obf

**Comment by Zirochkabila** [comment]
> 
Please explain what you think the expected result should be.
And also, add a couple of screenshots of the problem, to better understand your request

**Comment by Zirochkabila** [comment]
Note how the tagged roads on which the route is built and that OsmAnd displays data from the OSM (screenshots) in accordance with the designations
https://www.openstreetmap.org/way/970492345#map=14/60.4628/14.8484
https://www.openstreetmap.org/way/967647139#map=14/60.4487/14.8434
https://www.openstreetmap.org/way/394794770#map=14/60.4337/14.8484
https://www.openstreetmap.org/way/394794772#map=15/60.4195/14.8485
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/185578650-3c600958-6c8c-4eae-809b-3309f87924fb.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/185578660-e63a7290-ad67-4e88-8b4b-f44d92670a90.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Neuwessi11** [comment]
Sorry for asking, but did you repair anything?

**Comment by Zirochkabila** [comment]
What exactly do you mean?

**Comment by Neuwessi11** [comment]
Did you change something in the software before closing the issue?

**Comment by Zirochkabila** [comment]
No, because it could not be reproduced.

**Comment by Neuwessi11** [comment]
That means, in your simulation disappears "Salån" and "Höglinda" immediately after the junction?

**Comment by Zirochkabila** [comment]
This means that the name of the road is displayed as indicated in the OSM (links to the names of road segments are added in the second comment) - as shown in the screenshots.

**Comment by Zirochkabila** [comment]
The name does not change after the crossroads, because the road section is known as "Salån" (second link) - the name is the same as on the first road section, to the crossroads (first link)

**Comment by sonora** [comment]
So I guess what should change though, is the **icons** in the title line before the street name:

- The yellow arrow indicates the turn coming up pretty soon,
- and the ">>" indicates the destination, i.e. that the name behind it is the one _you will be on after the turn_.

I would expect that if the name of the road does not change, and you are not yet close to a successive turn, after the turn there will be no turn arrow and no ">>" indicating destination displayed for a while, i.e the line is just telling you which road you are supposed to follow for a while.

**Comment by vshcherb** [comment]
That's a good question is it important current road name or not, I would say it simply should be 2nd widget than it's possible always to see current name and next street name

**Comment by Neuwessi11** [comment]
@Zirochkabila 
> This means that the name of the road is displayed as indicated in the OSM (links to the names of road segments are added in the second comment) - as shown in the screenshots.

I am sorry, but this is not true. Both road segments have NO name. They are only tagged with a destination sign. If the roads had names I could understand why the names don't disappear, but there are no names.

**Comment by sonora** [comment]
In my opinion the current mechanism is quite ok and saves screen real estate. It is just that the user has to become aware of the meaning of the "Prefix icons" to understand when the widget displays information about the next turn (only when approaching) vs.  when the current stretch. Bur Ihink once understood it should be quite clear?

**Comment by Neuwessi11** [comment]
> So I guess what should change though, is the **icons** in the title line before the street name:

The actual first point is: destination=* is a complete other thing than name=*, so it should be handled otherwise.

destination=* indicates a destination sign before a crossroad, you can only see it before passing the crossroad, so showing it after a crossroad is useless, annoying and confusing.

**Comment by Neuwessi11** [comment]
@sonora 
> In my opinion the current mechanism is quite ok and saves screen real estate. 

If that were the case, I would not have opened this issue for the second time.

> to understand when the widget displays information about the next turn (only when approaching)

Exactly that is my point. The widget shows the information about the next turn not only before the turn, but also long after the turn.

**Comment by sonora** [comment]
True. If the destination display does not appear after the turn, it's a bug. 

But I cannot reproduce. For me it shows the name of the current road I have to follow until close to the turn, when things change to display the turn arrow and the destination info.

Or perhaps see something related to  #15171?

**Comment by Neuwessi11** [comment]
No, I don't think it is related to 15171.

But I have the impression, that I didn't make my point absolutely clear.
My point is NOT the behaviour of the app before the junction (because for me it is fine). My point is the behaviour of the app AFTER the junction, which is not ok. Because in my example the ">>Salån" is displayed some hundred meters before the junction (which is ok). But this ">>Salån" should disappear after the junction, because there is no next turn in the direction of Salån ahead!

**Comment by sonora** [comment]
I just checked the OSM data and think OsmAnd is totally fine here:

All related highways are **unnamed**, and both "Salån" and "Höglinda" are **destination:** tags, which are valid before and after the turn, so in the absence of any other name data to display and OdmAnd correctl using the destination prefix ">>" I find no bug here.

**Comment by Neuwessi11** [comment]
From the OSM-wiki: "In the road system, the key destination=* describes the content of signposts or ground writing indicating the names of the locations that the tagged way is heading to. Thus navigation systems can refer to road signs that the driver actually sees."

After the junction there is normally no road sign to be seen.
And on the road signs are very often destination showed, that you reach in some hundred kilometers and after a lot of other turns, so displaying the tagged destination is normally useless, except before upcoming turns.

**Comment by sonora** [comment]
Still I see no reason to hide a valid destination display after a turn, and replace it by 'nothing at all': Depending on the region, in ground truth destinations may be displayed periodically on mile markers, road shields, highway distance information signs, and at junctions you pass but where you do not turn.

Please note that in the case of e.g. a labeled highway this same mechanism shows you to follow e.g "^A10 >> ToTown", indicating both the current highway number and until where you must stay on it. In the case you observe here the display is shortened to just the destination because the highway is both unnamed and unlabeled.
