### ISSUE TITLE
Frustration With A Recent Route

### ISSUE THREAD

**Issue by seniorm0ment** [osmandapp/OsmAnd#15073]
I recently used OSMAnd to route to a popular mall in the state I visited.
It was an absolute nightmare. Once I got mid way into the city-area highway, I encountered numerous issues.

- The screen kept turning sideways instead of being angled in the direction I'm traveling like it was before, and like it is set to. Basically it was facing one way, and I can see the car driving horizontally on the road across the screen. It wasn't turning with me.

- Was having trouble sometimes determining my orientation.

- At one point, I was heading the wrong direction (thanks to poor recalculation) and it would not no matter what recalculate. It's idea was for me to turn around and go backwards. I had to take a right, then another right to get it to recalculate. But it should have told me to do that. Not just spin around on the road when I'm driving the wrong direction.

- It wss extremely hard to determine which exit to take. At the top it would show to get off, but the line said to keep going straight. This happened multiple times.

- The navigation itself in general was just absolutely horrendous.

The last two were THE BIGGEST ISSUES. I had gotten off the highway, and back on MULTIPLE times because of this. Heading in all different directions.
In the end I had to figure out my way using only signs, and knowing one of the street names. It was an absolute nightmare and waste of gas.
 

I can provide the route details, what is needed?
Just the start and end points? (obviously this won't show all the other issues I had when going in wrong directions and stuff but it should give an idea)

**Comment by pebogufi** [comment]
**Frustration about the poor information you provide about the situation when your problems accur**

When opening a bug report, you are asked to give some information, see below.
Why you don't fill them ?
And please provide start / end point, type of orientation of map, and everything else which could help to reproduce your problems.
If the developers can't reproduce your problem, how should they fix it ?????
- - - - -
### Description


### How to reproduce?


### Your Environment
OsmAnd Version:
Android/iOS version:
Device model:

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by vshcherb** [comment]
These issues have 1 common problem that all navigation programs act differently and once you switch between them you need to understand how program works. I don't mean that 1 program works better than other but I fell it's the same when I try other programs I constantly missing turns, don't understand when and how should I turn etc... So this problem of getting used & understand the program itself.

So what would be usable is to understand what expectations vs reality from your report it's really hard to understand, did the program miss a turn or just announced it in a "wrong time". Mostly what we see that **announcement timing** differ and that confuses lots of drivers of different programs. 

Of course the nicest outcome would be to have a video and then with timeslots say (Expectation vs Reality). It's probably not necessary to record the full video and possible to record the track itself and then it would be possible to simulat.

As for now I see no possible action for 5 times except 1st. 

1. Please double check what you have as Map orientation for Driving profile (it should be pointing to Direction) if it's misconfigured then it would be interesting to understand how did it happen.

**Comment by seniorm0ment** [comment]
Ok, the missing turn thing is understandable. But there was multiple times where it 100% seemed to be showing way too early.

 However that was the least of the issues. When I got in the city highways, it was constantly trying to take me on exits that didn't exist and clearly never did.
It seemed almost like it was unable to differentiate between whether I was above or below, you know how highways in cities are layered? Because it'd like try to make me take a right offramp, where there looked to be maybe one under me, but not one on my road.
This happened on multiple occasions on different roads and was not an isolated incident. 

Secondly, the orientation thing as I said it was set properly. I also tried clicking the button to see if it would reset itself if it just bugged out. It would not. I even stopped navigation, then restarted it and it did not fix it. It only did this on a few roads, I'm not sure why.

The weird thing was, I think I navigated to a place not long ago, not too far from my intended destination a few months back and it did not encounter a lot of these issues. It was mostly the same route all the way up to the city point, but I don't remember having nearly as much trouble as this time. This was just a disaster.

I would appreciate reopening this issue and making a further attempt to look at this. Again I can provide route info or whatever the best i can. I am unable to provide video if it happening, as it would be unsafe and it's not exactly close by, but I will be in that area on and off.
I genuinely always get nervous using OSMAnd in places that I do not know, because I feel stuff like this will happen. I don't have high confidence in it's routing because a lot of the time I do encounter issues compared to other solutions such as Google Maps or Waze. Unfortunately I do heavily prefer OSMAnd from a functionality and privacy aspect of it over the other two. But it is a bit meaningless if it can't get me to point A to B safely and nicely. I shouldn't have to be messing with it while driving, or looking hard at it. Even the color scheme was insanely difficult when I got in the city because everything blended together. I've tried others but they're all tough to read that is the easiest I found:

**Comment by vshcherb** [comment]
I would definitely reopen once we understand what needs to be fixed. Closed issue doesn't mean it won't be reopend or fixed, it only means it's not actionable for now. 
Here is a table how it should be pronounced - https://docs.osmand.net/docs/technical/algorithms/voice-prompt-triggering/. I will try to test myself today to see if I'm missing something obvious

**Comment by seniorm0ment** [comment]
I was not using voice prompts at all, I was referring to the turn directions at the top of the screen in comparison to the road path when you are driving
