### ISSUE TITLE
Swimming POI: Add more filter options for search function

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#15070]
For the sport=swimming POI there are almost no filter options available when searching for it.

Useful filters are:
- fee (to exclude POIs with a fee)
- access (to exclude private swimming pools)

The swimming pool POI also lacks the second option. There are private swimming pools in OSM, it would be nice to be able to exclude them from searches.

**Comment by tradavyvy** [comment]
I would even say to exclude private swimming pools as default.
Most users would use the search to find a place where they can swim.

**Comment by vshcherb** [comment]
I think private are excluded completely. There was an issue 5 years ago...

**Comment by scaidermern** [comment]
> I think private are excluded completely. There was an issue 5 years ago...

I'm not sure about access=private (I can't really check for it right now) but access=no is still included in the search results.

**Comment by scaidermern** [comment]
Further investigation:
- currently excluded:
  - `leisure=swimming_pool` with `access=private`
- currently not excluded:
  - `leisure=swimming_pool` with `access=no`
  - `sport=swimming` with `access=private`
  - `sport=swimming` with `access=no`
