### ISSUE TITLE
sac_scale should also render for highway=footway

### ISSUE THREAD

**Issue by tommycrock** [osmandapp/OsmAnd#15088]
Currently sac_scale tagging renders for highway=path but not highway=footway. Both should be treated the same: https://wiki.openstreetmap.org/wiki/Key:sac_scale

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14043mqta, released: 2022-12-23
Done 
`46.21413, 10.12533`
[Map](https://drive.google.com/file/d/1dYFWVMTQ1FpKF8dlK5DgngleiYNWBgN9/view?usp=sharing)
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/209334829-43d73c20-c9f0-4101-89ee-f252724e1f62.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>
