### ISSUE TITLE
Crash on slip road navigation TTS guidance in Finnish (possibly other non-English languages as well)

### ISSUE THREAD

**Issue by logarrhythmic** [osmandapp/OsmAnd#15086]
(I initially posted this on [Google Groups](https://groups.google.com/g/osmand/c/5ILcOmD7O30) and was advised to post here.)

### Description
The app crashes almost every time when I'm using navigation and a slip road I'm supposed to take comes up.
[Here's the exception log.](https://github.com/osmandapp/OsmAnd/files/9338653/exception.1.log)
I see the crash is TTS-related and occurs when it tries and fails to say the word "metrin", which is the conjugation of the Finnish word for metre used for "X metrin päästä" (in X metres). I think the TTS voice used to say "undefined" sometimes instead of "[...]metrin päästä", and this seems like a try-catch has been removed somewhere, making the problem present more severely.
Also see [Kevin's message](https://groups.google.com/g/osmand/c/5ILcOmD7O30/m/0AFpolRoBgAJ) under the Google Groups post for some possible relevant speculation about CLDR.

Notably, setting the voice guidance to English TTS avoids this crash. This is not a satisfactory solution even for fluent English speakers, as non-English language road names and sign directions are pronounced using English phonetic rules, which is hard to decipher while driving and looking at road signs. Having to turn off road names in the TTS options is a loss of functionality.

### How to reproduce?
1. Set the navigation voice guidance to Finnish TTS. 
2. Plan a route that includes taking an off-ramp to exit a motorway and start navigation.
3. The app will crash when approaching any of around half of all road sections like this I've seen in Finland. If a specific off-ramp causes a crash, it's usually consistent.

### Your Environment
OsmAnd Version: 4.2.7; also occurs on several daily builds from the builds button available through developer options
Android/iOS version: Android 12 and Android 13
Device model: Oneplus 10 Pro

**Maps used (online or offline):**   
Offline; this happens in similar motorway sections all over Finland so it's unlikely to be a map issue. I can, however, dig up an example intersection if it ends up being necessary, as I do remember a specific one.

**Comment by Zirochkabila** [comment]
As you can see in the added video - reproduction failed.
Please send me the start and finish coordinates so that I can reproduce your situation.
Also, please add a short video

[telegram-cloud-document-2-5474438269796096451.mp4.zip](https://github.com/osmandapp/OsmAnd/files/9380739/telegram-cloud-document-2-5474438269796096451.mp4.zip)

**Comment by logarrhythmic** [comment]
It's specific to motorway exits, so the route in that video wouldn't trigger it. Navigating from 60.25297 N 24.94870 E to 60.24218 N 24.93963 E is an example of the kind of thing that will crash the TTS.

**Comment by logarrhythmic** [comment]
Here's the video.
https://user-images.githubusercontent.com/1952758/185645373-f635896b-9c27-4379-bbef-e0b2e52755f8.mp4

**Comment by sonora** [comment]
Was introduced here https://github.com/osmandapp/OsmAnd-resources/commit/f34524812ad8fef28cf2f3074c84546c6543b0c7, fixed here https://github.com/osmandapp/OsmAnd-resources/commit/487099cc9dbbfbeab0c5f40577fbe09ee3a60a12.

@vshcherb Not quite sure how to push this to the download-server so users could update it?

**Comment by Zirochkabila** [comment]
> from 60.25297 N 24.94870 E to 60.24218 N 24.93963 E 

Thanks for the clarification - I was able to reproduce
The application crashes while navigating through the vicinity of the specified coordinates

[exception (9).log](https://github.com/osmandapp/OsmAnd/files/9403131/exception.9.log)

**Comment by sonora** [comment]
@Zirochkabila Please note I have fixed this in our code, see above. Please move this to our download server so users can update their language config files even before the next releaae of OsmAnd.

**Comment by logarrhythmic** [comment]
I managed to install a nightly build that had this fixed, I have no idea how your deployment stuff works but it didn't crash with Osmand~ 4.3.0#13726mqta. The TTS there had another, smaller, issue though: instead of "X metrin päästä" (in X metres) it omits the postposition "päästä" and says "X metrin" (X metres but with incorrect grammar).

**Comment by sonora** [comment]
Yes, nightlies would work immediately.

@logarrhythmic Can I plrase ask you to temporarily activate the Development plugin in OsmAnd, then go to its settings and use the "Test voice orompts" section. Can you please open a new issue, and there state the button numbers of all buttons which are wrong, explaining how each sounds and howit should sound correctly.

**Comment by vshcherb** [comment]
@sonora I'm afraid TTS are not distributed through downloads, so it will be available in new release only

**Comment by sonora** [comment]
Really? But we have  2 "Voice prompts" sections "Download maps", one of them is for TTS?

**Comment by vshcherb** [comment]
@sonora Unfortunately it's confusing I agree and we have separate issue to delete them. These download means that you can "download" from application binary to intermediate folder "Local".

> Currently, in the Download maps menu you can see the Voice prompts files. Also, there is available to delete or rename the files, but when you restart the app, all your changes (delete or rename) do not save. It probably might be better to hide the Voice prompts menu for users and display only when the Development plugin is on.

We still didn't refactor and fixed that annoying issue.
