### ISSUE TITLE
Correct Swedish county names 

### ISSUE THREAD

**Issue by MrRinkana** [osmandapp/OsmAnd#15085]
# 🚀 Region/country names in the "download maps" section should be shown in the same language as the app is set to.

### Description
Currently when browsing maps to download you are greeted with the ```name:en``` (from Osm) or possibly the ```int_name```. The name should prefer to use the ```name:X``` where ```X``` is the language the app is currently using.
**This is referring to the "download maps" section.**

### Example:
OsmAnd is set to Swedish.
Names given to the maps/map regions should follow the following priority:
1. ```name:sv```
2. ```int_name```
3. ```name:en```
4. ```name```

Or something along those lines, the important part is that ```name:sv``` is the first priority. It seems that there is inconsistency/confusion around the ```int_name```, so the order after the first should maybe be different. 

This would make the names match the language used, and prevent confusion.

**Comment by MrRinkana** [comment]
Actually, I just looked at this again, and it might actually work as proposed, and its just that entries in osm are inconsistent if they specify the name:X (there X is the local language) property (for example swedish counties are most often specified only by the "name" property in swedish).

I have now fixed so that all the swedish counties have the tag "name:sv", and will wait to see if the app will show the swedish names. I will leave issue open just in case they will not be updated, and maybe there is another issue of the county names not being updated after the current osm..

**Comment by vshcherb** [comment]
Yes we will update, please let us know which regions are not correctly translated - we automate it using https://github.com/osmandapp/OsmAnd-misc/tree/master/osm-planet/osm-data

**Comment by MrRinkana** [comment]
### Regarding the Swedish counties:

I updated my maps that where released on the 1 of jan 2023 (if it matters), and the only two counties that are shown correctly are "Norrbottens län" (Norrbotten county) and "Västernorrlands län" (Västernorrland County), all other 19 counties seem to show the name:en. These two counties where the ones that had an name:sv entries before I created this issue. I looked at the link and it seems the files were updated (script ran) just before I fixed the Swedish counties approx two months ago.


### In general:

Is the "update-osm-all.sh" script run automatically? Or does it need to be triggered manually? If its not run automatically it probably should, as there are a lot of countries missing both their own "name:X" (only specifying "name:"), and translations into other countries. Maybe this is not worked on by osm contributors, but there is much to do there so potentially such changes can come quite often.

Might I ask what the current priority order is? I have not managed to find the combinations of places that have or lack different entries to reverse-figure this out.

**Comment by vshcherb** [comment]
We will update manually and release with new app version.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14163mqta, Released: 2023-02-09
07.02.23 master
Done

<details><summary>Android Swedish</summary>
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/217776832-5671c5c0-331a-491e-b446-92f3cec751bc.jpeg">
</details>

<details><summary>iOS Swedish</summary>
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/217777105-739a3e19-25a2-4802-9228-0250ba7ee3da.png">
</details>
