### ISSUE TITLE
"Travel" guide's breadcrumbs navigation doesn't work

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#15080]
Taping on Europe or Italy should show the bottom sheet with a list of regions or countries.

<img src="https://user-images.githubusercontent.com/9365308/184657967-ae0a99ab-baf8-4e87-bdf0-c357815213af.png"  width="260" height="auto"/>

**Comment by Dima-1** [comment]
- https://github.com/osmandapp/OsmAnd/pull/15100
