### ISSUE TITLE
announcement time and repetition of off route warnings

### ISSUE THREAD

**Issue by cridemichel** [osmandapp/OsmAnd#15090]
# 🚀 feature request
Hi,
I very happily use osmand for trekking (which I found irreplaceable!) and when I am off route I would like to be warned 
as soon as possible (considering gps uncerainity, say 5 m off?). I know that I can play with announcement time,
but this setting change all annoucement timings (i.e. turn, arrive at destination, etc). Moreover, if I understood correctly,
I have to set it to "in the last meters" to receive off-route warnings as early as possible (it should be "early" in my opinion),
which is rather counterintuitive.

### Describe the solution you'd like

It would be nice to have a specific announcement time for off route events, or better
to have have the possibility to set announcement times indipendently for all events 
(i.e. turn, arrive at destination, etc.). Moreover, if you are off route, it would be nice to keep 
receiving warnings, which also inform you on current distance from track. To have this,
a specific setting about repeating off-route event could be added as well. More generally, I think
that the way osmand handles navigation along a track could be improved a bit and I would appreciate
to know your impressions on this,

best Cristiano

**Comment by vshcherb** [comment]
Please check how it's built https://osmand.net/docs/technical/algorithms/voice-prompt-triggering. You can name suggestions of the naming of course but we need to keep it separate from functional suggestions and situations when it doesn't work as expected. Of course it requires some experiments cause we see some device specific behavior

**Comment by cridemichel** [comment]
> Please check how it's built https://osmand.net/docs/technical/algorithms/voice-prompt-triggering. You can name suggestions of the naming of course but we need to keep it separate from functional suggestions and situations when it doesn't work as expected. Of course it requires some experiments cause we see some device specific behavior

thank you for the reply but I have already read the link you posted, my point is that I would like to reduce trigger time
for off-route events without necessarily change all the other ones. Moreover, according to the algorithm described at the link which you posted, it seems that, in order to have off-route announcements as early as possible, one has to set annoncement time to "in the last meter", which is the opposite that one can expect for this event, am I wrong?

**Comment by vshcherb** [comment]
You can do it with changing default speed as you could see in the formulas.

**Comment by cridemichel** [comment]
default speed actually is rather reasonable for me,
hence if I change it, estimated arrival times will be inaccurate…
that is not a solution at all and I do not want to set it to
different values...


Cristiano De Michele
***@***.***
