### ISSUE TITLE
Display track names as they are

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#15091]
It is a nuisance that on sevaral screens, inluding both of our track lists (under MyTracks and Configure map) and the track card title, we manipulate characters in the GPX tracks' file names before displaying them, such as replacing any underscore by a blank.

Can we finally remove that confusing and obsolete behavior?

**Comment by vshcherb** [comment]
This is a temporary fix to let https://download.osmand.net/uploads/gpsies-cycling.travel.obf.

Though the problem we still need to display better names than File names cause File names could have some illegal characters.

**Comment by vshcherb** [comment]
I think we can of course use the trick to create name and see if file is created and if it's not created put better name in description or name tag?

**Comment by sonora** [comment]
I don't understand the problem: If a file name is 'legal' in the file system, why would OsmAnd manipulate it before displaying it? That's all I am asking.

Use case: Many commercial hiking guides etc. use the file names as the primary descriptive data field, not any GPX/xml-internal tags.

**Comment by vshcherb** [comment]
Cause we have collections of GPX files stored in OBF, it's not validated if these names are valid file names or not, so we think  to save it inside and use it primarily. 

The source of GPX tracks is here -
https://www.openstreetmap.org/user/GPSies_com/traces
 https://www.openstreetmap.org/traces/tag/enduro/page/1 or other tags 

As you see we want to use better descriptive names instead of cryptic but we are not sure if they could be used as File Names, in most of the cases yes but in some we probably need to simplify it.

**Comment by sonora** [comment]
@Chumva Looks like this should also be aligned
 - here
https://github.com/osmandapp/OsmAnd/blob/f9a3548357d88dba742be7163a928dfee24f657c/OsmAnd/src/net/osmand/plus/myplaces/ui/AvailableGPXFragment.java#L1725
 - and here for the folder names?
https://github.com/osmandapp/OsmAnd/blob/6abc4d61e48c16a8ff97b5ab241601b746e10e72/OsmAnd/src/net/osmand/plus/helpers/GpxUiHelper.java#L350-L351

**Comment by Zirochkabila** [comment]
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/186202431-86d4cb93-3fa1-4055-9d55-f03e71fbc9d5.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/186202444-ae7dfa03-0a4f-493c-9308-74b3b60e0f0d.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/186202452-b4b0c87d-2dbc-41bc-9a78-2af2695db36f.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>
