### ISSUE TITLE
Translate common labels POI information popup

### ISSUE THREAD

**Issue by franco999** [osmandapp/Osmand#1510]
I am a collaborator in the Spanish translation of OsmAnd and have translated several chains in Weblate (poi_brand, poi_operator, poi_fuel_diesel, poi_fuel_octane_x, poi_phone, etc), but to give details of the PDI only appear a few translated labels (eg poi_opening_hours). It would be good to see the other common labels in my language, since all can not be translated.

![contact](https://cloud.githubusercontent.com/assets/12088580/8988653/cb445902-36bd-11e5-92ea-34aa9fc5b036.png) ![fuel](https://cloud.githubusercontent.com/assets/12088580/8988654/cb76ea20-36bd-11e5-801e-5a79a15df30d.png)

**Comment by vshcherb** [comment]
Please update https://github.com/osmandapp/Osmand/blob/master/OsmAnd/res/values/phrases.xml now it should be working. With  new maps the list of the tags is shorten and it is listed here https://github.com/osmandapp/OsmAnd-resources/blob/master/poi/poi_types.xml#L5

@xmd5a2 please add russian translations to operator.

**Comment by franco999** [comment]
Thanks, but the "contact:phone", "addr:housenumber" and "note" labels and the value "yes" are not translated.
It would be nice to have those labels and values translated too.
