### ISSUE TITLE
How use gradient colorization for route

### ISSUE THREAD

**Issue by LeLuyen** [osmandapp/OsmAnd#15101]
Hi all,

How use gradient colorization for route?

Can you help me?

**Comment by scaidermern** [comment]
See the different color options at Settings / Profile / Navigation settings / Customize route line.

**Comment by LeLuyen** [comment]
Hi @scaidermern,

Your way, I know, but i want to use the gradient color example below:

1. Define drawable resource

<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle" >
    <gradient 
        android:startColor="#6586F0"
        android:centerColor="#D6D6D6"
        android:endColor="#4B6CD6"
        android:angle="90"/>
    <corners 
        android:radius="0dp"/>
</shape>

3. Use drawable resource for setting pallette
    
    public static int[] pallette = new int[] {
			R.drawable.gradient_color

Can I do?

**Comment by LeLuyen** [comment]
Hi all, 
When change gradient color by settings, it doesn't work.
![Screenshot_20220818-150819_OsmAnd~](https://user-images.githubusercontent.com/2620445/185346036-735fc674-9795-41d8-89d3-8df3a82f0561.jpg)
![Screenshot_20220818-150813_OsmAnd~](https://user-images.githubusercontent.com/2620445/185346064-c08d6a53-c1aa-47b3-a260-a9dab7d3ab8a.jpg)

**Comment by dmpr0** [comment]
@LeLuyen Hi! You can change gradient colors here https://github.com/osmandapp/Osmand/blob/6353c3fb15b9ff7499a6144c676d13f97ee6c252/OsmAnd-java/src/main/java/net/osmand/router/RouteColorize.java#L31-L43

**Comment by LeLuyen** [comment]
Hi @dmpr0 ,

But when touch 'Apply' button, it doesn't work.

You can see the different of current route line and preview route line

https://user-images.githubusercontent.com/2620445/185346064-c08d6a53-c1aa-47b3-a260-a9dab7d3ab8a.jpg

**Comment by scaidermern** [comment]
@LeLuyen Do you have slope maps installed? Otherwise this will not work I guess.

**Comment by LeLuyen** [comment]
Hi @scaidermern

If i don't have install slope maps, how to work with gradient colorization for route?

**Comment by LeLuyen** [comment]
Hi All,

I try code below but it's work not perfect :)

```
int[] colors = new int[] {
					0xff2117c9,
					0xff00d4ff,
					0xff1919c9,
			};
			float[] positions = new float[] {
					0.0f,
					0.5f,
					1.0f
			};
			LinearGradient gradient = new LinearGradient(0f, 0f, 0f, customWidth, colors, positions, Shader.TileMode.MIRROR);
customColorPaint.setShader(gradient);
canvas.drawPath(path, customColorPaint);
```
