### ISSUE TITLE
Белый экран после смены ориентации

### ISSUE THREAD

**Issue by gtrus21** [osmandapp/OsmAnd#15104]
OsmAnd~ 4.3.0#13716mqta, дата выпуска: 2022-08-17
Включен OpenGL

При повороте телефона набок (при включенном автоповороте экрана) карта исчезает и на ее месте белое поле

![Screenshot_2022-08-17-16-20-38-886_net osmand plus](https://user-images.githubusercontent.com/69676792/185144751-9e67d9f7-0b65-4f2e-b0d2-ee538158161f.jpg)
![Screenshot_2022-08-17-16-20-44-168_net osmand plus](https://user-images.githubusercontent.com/69676792/185144768-ec585b2a-c732-4f81-ad44-589bad63b10e.jpg)

**Comment by vshcherb** [comment]
Duplicate issue
