### ISSUE TITLE
OpenPlaceReviews does not login with OpenStreetMaps Oauth

### ISSUE THREAD

**Issue by EvanCarroll** [osmandapp/OsmAnd#15108]
### Description

 I can not log into OpenPlaceReviews with OSMAnd

### How to reproduce?

1. Clear out all entries in Oauth1 for "OpenPlaceReviews" here https://www.openstreetmap.org/user/Evan%20Carroll/oauth_clients
2. In android OSMAnd
   1. Click Hamburger (bottom left)
   2. Click "Configure Profile" at the top
   3. Click "OpenPlaceReviews" under Plugin Settings
   4. Click "Login to OpenPlaceReviews"
   5. Click "I already have an account"
3. This launches my browser Duck Duck Go with a Login Screen
4. Click  "OpenStreeMap" under "Select registration method:"
5. Click Grant Access, leave "read your user preferences" checked.
6. Click "Open" when it asks to "Open in another app"

**At this point nothing has changed, your only option is again "Login to OpenPlaceReviews"**

Side note: I'm using OAuth to login to OpenStreetMaps too. It works find there.

### Your Environment
OsmAnd Version: OsmAnd 4.1.11 / F-Droid Build
Android/iOS version: Android 11, LineageOS w/ Micro G
Device model:

**Comment by lucchinelli** [comment]
Exactly the same Problem as described from @EvanCarroll . OmaAnd~ 4.2.7 from FDroid on LineageOS 18.1 build 2022-09-05 (Android 11). 
I'm logged in at OpenPlacesReviews (I can see it if I visit the website directly) but in every cases I want to load up a picture from osmand I come to the login page from OpenPlacesReviews.

**Comment by zilti** [comment]
This is still not working, the error reads "User was not signed up in Blockchain".

**Comment by Eheran1** [comment]
Same issue, without Oath, using Firefox.

**Comment by pokulo** [comment]
> This is still not working, the error reads "User was not signed up in Blockchain".

I can't create an account using OpenStreetMap OAuth, seeing the same blockchain problem. I am using firefox on android, but also tested with firefox on a desktop linux. 

Is there any way of debugging this?

**Comment by barbara-sturbo** [comment]
Can confirm issue persists on:
OsmAnd Version: OsmAnd 4.3.8 (current Suggested version) (added on 2023-01-26)/ F-Droid Build 
Android/iOS version: Android 12, LineageOS 19.1 w/ Micro G

Issue is NO longer present on:
OsmAnd Version: OsmAnd 4.3.12 (Added on 2023-03-05 ) / F-Droid Build

**Comment by zilti** [comment]
Cannot confirm the findings of @barbara-sturbo . This ultimately has nothing to do with OsmAnd at all; OpenPlaceReviews is just broken (but hey, at least it's broken on a blockchain, I am sure that got it bonus points somewhere!). I can't sign up (let alone log in) via a browser either.

**Comment by saikimecky** [comment]
Problem still exists in Osmand version 4.4.7.
Stock Android 13 on a realme GT neo 2 5G. 

Tried to delete all oauth tokens and got a new one. In preferences I can see it works. When clicking on a POI and want to add a photo i'm landing again on the registration page. Login via Browser on openplacereviews works.

**Comment by dmpr0** [comment]
OpenPlacesReview is closed.
