### ISSUE TITLE
Please render playground=*

### ISSUE THREAD

**Issue by bkil** [osmandapp/OsmAnd#15111]
# 🚀 feature request

### Description

https://wiki.openstreetmap.org/wiki/Key:playground

### Describe the solution you'd like

Please render and support in search.

**Comment by vshcherb** [comment]
I think they used to display on the map as icon. On iOS the icon is random and very very small and it is hidden behind the tree!

Also I think POI subtypes for search.

**Comment by bkil** [comment]
I leave it to you whether each of them would have a unique icon. For our use case, it would also be sufficient as an MVP if all of them had the same icon (even the existing playground icon) and the subtype was written under it as a caption.

With time, we plan to resurvey individual playground equipment on every playground. For this, it is crucial that we see on the ground within OsmAnd what is already mapped and what is not and whether they appear at the appropriate GPS coordinates.

**Comment by vshcherb** [comment]
As I understand playground is a multiple values so we can't display it altogether. But icons and POI will be possible to display as POI Layer - Custom filter

**Comment by bkil** [comment]
You have two options to map it:
* On the same node or way that represents the whole playground (`leisure=playground`), list all equipment available in `playground=` via a semicolon delimited list - this is not recommended
* Draw the playground as a closed way (`leisure=playground`) and insert each individual equipment within its boundaries as individual nodes (or ways) with its respective `playground=*` tag

With this issue, I asked for the second. For the first, it would be sufficient to see the list if I scrolled down to the advanced info (although we don't map playgrounds like that).

**Comment by ivanPyrohivskyi** [comment]
Start drawing icons in Figma
