### ISSUE TITLE
Regression in routing takes straight line shortcut random points

### ISSUE THREAD

**Issue by mdykierek** [osmandapp/OsmAnd#15118]
Look at #14613
Now it does not go directly to the destination though it still slightly affects all the route parameters (time, distance etc.).
Another thing is that the issue seems to be triggered by automatic re-routing and in fact it causes the automatic re-routing to be triggered.
It seems that in the polar areas GPS does not work as good (maybe caused by fjords) but it appeared more often there.
It also seems to be more likely to happen for longer routes. Got anohter one just today in Poland :)
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/27214784/185712509-322358be-d192-4808-b71e-c5dc34ccd884.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by martenjj** [comment]
Also observed in Germany (OsmAnd+ 4.2.7, Android 12, Samsung Galaxy S10, offline maps 1 Oct 2021):

![Screenshot_20220727-190711_OsmAnd+](https://user-images.githubusercontent.com/10631760/189482695-827714d0-4419-40fa-a39f-30a131428887.png)

![Screenshot_20220727-190805_OsmAnd+](https://user-images.githubusercontent.com/10631760/189482699-4a394acd-218a-47c4-bf51-06d6c874f631.png)

**Comment by Zirochkabila** [comment]
It was not possible to reproduce the scenario described above.
But it seems that https://github.com/osmandapp/OsmAnd/issues/15013 describes a similar bug.

**Comment by mdykierek** [comment]
Can you describe how these two bugs are related? It is not obvious to me.

**Comment by Zirochkabila** [comment]
### Description
[log&gpx.zip](https://github.com/osmandapp/OsmAnd/files/9646267/log.gpx.zip)

### Steps to reproduce
Navigation > Select point of departure `47.101561, 51.925657` > Set destination `51.228633, 51.414281` > Options > Simulate navigation > Realistic simulation > Menu > Plugins > OsmAnd development > Settings > Simulate your position > Chose 41259 (GPX) > Go to the map
### Actual result

https://user-images.githubusercontent.com/104760013/192280302-0359ff8f-bada-49cc-aa7e-836b5df6ed5d.mp4

### Your Environment
OsmAnd Version: OsmAnd 4.2.7, released: 2022-07-13 and OsmAnd~ 4.3.0#13815mqta, released: 2022-09-26 too
Android/iOS version: Android 12
Device model: POCO X3 NFC

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/pull/15506

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-core-legacy/pull/104
