### ISSUE TITLE
`access:conditional` on `route=ferry` ignored

### ISSUE THREAD

**Issue by Discostu36** [osmandapp/OsmAnd#15110]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Car

### Start and end points

From: https://www.openstreetmap.org/way/143418870
To: https://www.openstreetmap.org/way/25037454

### Actual and expected routes

The route goes over the ferry route. But as that one is tagged with `access:conditional = no @ (2022 Aug 15-2022 Oct 31)`, it should use another way instead.

### Is this a regression?

 I don't know

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

 4.2.7

</code></pre>

**Device and Android/iOS version:**
Fairphone 4, Android 11

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.

* Germany_schleswig-holstein_europe.obf from Aug 1st 2022
* Germany_schleswig-holstein_europe_22_08_18.obf from 14:25 CEST
- [ ] Online (tile / raster) maps 

**Anything else relevant?**

**Comment by Zirochkabila** [comment]
Reproduced on version 4.2.7, map update date 25.08.2022 (Germany_schleswig-holstein_europe_22_08_25.obf from 15:40 CEST)
The route (54.522790, 9.717750 > 54.524571, 9.714606 ) is via the ferry, although it is tagged - no @ (2022 Aug 15-2022 Oct 31)

map https://drive.google.com/drive/folders/13ZkkEtOGEcO4BgFlx8FWXCfascbN6Aag?usp=sharing

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/186672110-26ccff54-a9e5-478d-a11e-deb656860007.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by ivanPyrohivskyi** [comment]
Will fix in the new maps May 2023

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#35870m, Released: 2023-05-02
4.4.8.3
May map - Still present

[OSM](https://www.openstreetmap.org/way/1080968970#map=16/39.9862/-0.1458)

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/235684487-fdef4a46-741b-4a6b-bdb0-1fac17a74745.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/235684495-9ed52870-957d-4c83-816a-c3784c8f7a97.jpeg"  width="500" height="auto"/> </th>
  </tr>
</table>
