### ISSUE TITLE
`surface=gravel` & bends cost

### ISSUE THREAD

**Issue by toyotaekefar** [osmandapp/OsmAnd#15116]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Car

### Start and end points

https://osmand.net/map?start=49.083107%2C33.424256&end=49.087102%2C33.431590&mode=car#16/49.0843/33.4297

### Actual and expected routes

**Actual**: Europe Street (Європейска вулиця) > https://www.openstreetmap.org/way/300715840 > https://www.openstreetmap.org/way/305086830 > Heroes of Mariupol Lane (Героїв Маріуполя провулок) > highway=service to apartment building
![photo_2022-08-18_22-07-09](https://user-images.githubusercontent.com/72326579/185667716-6ea00c5e-0eb4-44e1-a089-1993075e969e.jpg)

At https://www.openstreetmap.org/way/300715840 **surface=gravel** from 13 Jan 2019 https://www.openstreetmap.org/changeset/66272542

**Expected**: Europe Street (Європейска вулиця) > Freedom Avenue (Свободи проспект) > Heroes of Mariupol Lane (Героїв Маріуполя провулок) > highway=service to apartment building

![photo_2022-08-18_22-06-32](https://user-images.githubusercontent.com/72326579/185667710-bea60ec3-b53a-43bb-8c02-7540d0bbf21d.jpg)

### Is this a regression?

 Don't know

## 🌍 Your Environment

**OsmAnd Version:** 

<pre><code>4.2.7
</code></pre>

**Device and Android/iOS version:** All

**Maps used (online or offline):** 

- [x] Offline maps offered within the OsmAnd app for download.

- [x] Online (tile / raster) maps  https://osmand.net/map

**Anything else relevant?**

After the detection of the routing problem, **smoothness=bad + lanes=1** at https://www.openstreetmap.org/way/300715840, **lanes=3 + surface=asphalt** at https://www.openstreetmap.org/way/846193383, https://www.openstreetmap.org/way/175941297, **lanes=2 + surface=asphalt** at https://www.openstreetmap.org/way/177963088 were added

**Comment by xmd5a2** [comment]
Route through trunk:
`routing_time=383,5`
Route through gravel:
`routing_time=299,8`
Routing time via trunk is so high because there are 2 traffic signals. It is debatable that route through gravel is less preferable.

**Comment by xmd5a2** [comment]
Added penalty to gravel. Now it doesn't build route through it.
![Screenshot_2022-09-01_11-00-46](https://user-images.githubusercontent.com/5829014/187863642-594fc658-8897-4568-87dc-cf3396e9410a.png)

**Comment by xmd5a2** [comment]
Route with "Avoid unpaved" option:
![Screenshot_2022-09-01_11-03-43](https://user-images.githubusercontent.com/5829014/187864022-bf6be315-92e5-473e-a9c7-0f79e46efe38.png)

**Comment by vshcherb** [comment]
This is also gravel - https://www.openstreetmap.org/way/678718969. 
I think it's pretty bad... https://wiki.openstreetmap.org/wiki/Tag:surface%3Dgravel
If it's like this - https://wiki.openstreetmap.org/wiki/Tag:surface%3Dgravel. Probably we can lower speed and also introduce penalty_transition for them?

**Comment by toyotaekefar** [comment]
> Routing time via trunk is so high because there are 2 traffic signals. It is debatable that route through gravel is less preferable.

1 traffic signal at Freedom Ave & Heroes of Mariupol Lane

**Comment by toyotaekefar** [comment]
> Routing time via trunk is so high because there are 2 traffic signals. It is debatable that route through gravel is less preferable.

The duplicate of the traffic light was removed after your message. However, I believe that even 2 traffic lights would be preferable than surface=gravel & such bends at the highways/roads
