### ISSUE TITLE
Latest nightly defaults to use 'Display position'=bottom

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#15126]
I have installed on several new devices: The latest nightly seems to use` 'Display position'=bottom ` per default for all profiles, I always had to adjust manually?

**Comment by vshcherb** [comment]
Will be fixed soon, yes very annoying.

**Comment by nazar-kutz** [comment]
**Pull Request**
https://github.com/osmandapp/OsmAnd/pull/15148

**Comment by vshcherb** [comment]
Radius ruler doesn't use correctly setting of display position bottom
