### ISSUE TITLE
Is the roundabout navigation graphic meant to reasonably reflect the angle the exit is from the start?

### ISSUE THREAD

**Issue by Goodingn** [osmandapp/Osmand#1512]
Because it doesn't:
![screenshot_2015-07-27-10-33-59](https://cloud.githubusercontent.com/assets/13037960/9007219/3a644e72-3787-11e5-872f-bd419e0af1e4.png)
![screenshot_2015-07-27-10-33-10](https://cloud.githubusercontent.com/assets/13037960/9007220/3d9319fc-3787-11e5-919e-be9e12b82e21.png)
![screenshot_2015-07-27-10-14-46](https://cloud.githubusercontent.com/assets/13037960/9007224/42a8c9e6-3787-11e5-9596-4a0246ef72bf.png)
![screenshot_2015-07-27-10-13-47](https://cloud.githubusercontent.com/assets/13037960/9007227/47e6313c-3787-11e5-92a1-84bc1adec5f7.png)

**Comment by Goodingn** [comment]
![screenshot_2015-06-28-13-10-02](https://cloud.githubusercontent.com/assets/13037960/9007244/6af79422-3787-11e5-8599-9472e63f061d.png)

**Comment by vshcherb** [comment]
We are going to change these icons anyway, because of turn:lanes arrows.

**Comment by polarbearing** [comment]
I think that has been fixed with the recent roundabout re-design?
