### ISSUE TITLE
Improve speed limit display on Android Auto

### ISSUE THREAD

**Issue by mdykierek** [osmandapp/OsmAnd#15121]
In the app it shows the limit. In Android Auto only when exceeded.
Many navigation apps show (Sygic, Automapa)  the limit inactive (gray) when there is a limit that is obeyed (e.g. going 50 where 60 is enforced) and red with a message when exceeded.
IMHO that would be both doable and desirable.

**Comment by sonora** [comment]
There's a speed limit widget you can configure to be shown all the time, under _Menu/Configure screen_.

**Comment by mdykierek** [comment]
This is for the phone app.
My suggestion concerns Android Auto. The Configure Screen does not seem to affect that.

**Comment by dmpr0** [comment]
Duplicate https://github.com/osmandapp/OsmAnd/issues/13413
