### ISSUE TITLE
Search > Address screen is take 5 second to load

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#15130]
https://user-images.githubusercontent.com/9365308/185894603-1338c846-8f80-47bd-9006-c68713e96db2.mp4

**Comment by sonora** [comment]
See #15607: 
I believe the delay is caused by OsmAnd compiling the list of "Nearest cities". And while this happens, there is no access to the 4 buttons
  - "Search street in (last used town)",
  - "Search city/town/locality",
   -"Search postcode" , and
   -"Search cordinates",

although none of them should depend on the compiled list of Nearrest cities being ready.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14031mqta, released: 2022-12-18
Not reproduced


https://user-images.githubusercontent.com/104760013/208300756-fab67f43-138e-48cf-864d-aa084b139f19.mp4

**Comment by sonora** [comment]
@Zirochkabila, @dmpr0  Be aware that that screen is cached in a way, so to reproduce best restart the app.

And I have been testing my fix  https://github.com/osmandapp/OsmAnd/commit/853c594ff7b5dd527add998554f2ba009adb332d fo ra week now, it really makes the search experience **a lot** snappier.

**Comment by Zirochkabila** [comment]
After clearing the cache, and "arriving" in a new city - the speed of loading the search doesn't change


https://user-images.githubusercontent.com/104760013/208302387-9921fa52-9299-47dc-9dbe-8a6cc4b7ff91.mp4

**Comment by sonora** [comment]
Yes, as researched here https://github.com/osmandapp/OsmAnd/issues/15607 , it also scales with the number of maps active on the device, takes e.g. 7 seconds for me on a mid-range device with lots of maps. In any case, the delay results from originally holding back the search buttons until the nearest cities list is ready, although they do not depend on that. My fix solves that by showing the static buttons immediately.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14057mqta, released: 2022-12-28
Done
