### ISSUE TITLE
Add options to navigate selected and non-saved track

### ISSUE THREAD

**Issue by mdykierek** [osmandapp/OsmAnd#15132]
It would be nice to be able to follow the track of a hiking/biking route directly from either the overview, track, or options view.
The easier the access the better.

**Comment by arncor** [comment]
it's already possible. when selecting a track that is already displayed on the map, the last button of the overview tabs allows that.

**Comment by mdykierek** [comment]
I thought that this button is for downloading, so I didn't use it. It is not obvious, that clicking a "button" shows other buttons.
Somewhat hidden, but it can be closed.

**Comment by dmpr0** [comment]
Yes, @arncor is right, taping on last button will launch **Follow track** mode in navigation, all 4 actions from **Overview** tab is shown with the names on **Options** tab.

<table style="width:100%">
  <tr>
    <th>Overview</th>
    <th>Options</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/186093450-c897ac9b-298d-446f-9330-646454c6ad6b.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/186093456-4a3b53ef-e74f-4830-b435-0a11ee36256d.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by mdykierek** [comment]
Well, I don't have it. I have just moved to OsmAnd+ and these options are NOT VISIBLE BY DEFAULT. You have to "download" the track first. This is not obvious. If the options were shown and taking action downloaded the track, it would be clearer what can be done with it. In the Options tab, they are not visible before I download them either, so they are in fact HIDDEN behind this button.
![Screenshot_2022-08-23-11-22-19-898_net osmand plus](https://user-images.githubusercontent.com/27214784/186122406-20b96cc3-922f-45ac-8789-6b28b2aa0d99.jpg)

**Comment by arncor** [comment]
Well, yes you have to download the track first in order to use it for navigation. navigation being offline...

I was talking about tracks that I made myself in Osmand or that I saved from gps recording.

**Comment by mdykierek** [comment]
The title reads however "follow a trail directly".
For me it is now clear. Not sure if for an "average" user it is too for the reasons I wrote in my previous comment.

**Comment by vshcherb** [comment]
Optionally: we also could suggest to extract longest segment cause navigation is only possible by 1 segment

**Comment by mdykierek** [comment]
> Optionally: we also could suggest to extract longest segment cause navigation is only possible by 1 segment

Or if the location is know, the nearest? I often go to a place, select the trail / bike route and want to follow it. The longest may actually not be the nearest. This may not be true for most users of course.

**Comment by dmpr0** [comment]
## Review
- [ ]  Hide "Navigation" button. We should show all buttons as for normal tracks, or don't show anything.

**Comment by vshcherb** [comment]
We probably need to redesign - Options as well and make user clear that he needs to Save track for later navigation. So this could be done as a separate task
