### ISSUE TITLE
City search > different order on iOS vs Android

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#15138]
On both devices map was centred over Milano, on 2 km zoom, open **Search** > **Address** > **Select city** > type "Milan".
On iOS needed result (and the nearest judging from the screenshot) is on 6 place.

<table style="width:100%">
  <tr>
    <th>iOS</th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/185893376-5e652960-1268-4e05-afa5-da1171d5916a.jpg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/185893521-a14f525d-cab9-4529-8a3d-283e15f965b4.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2202

https://github.com/osmandapp/OsmAnd-core/pull/387
