### ISSUE TITLE
Part of the text is not displayed

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15143]
### Description
Part of the text in the map update data is not displayed
[logcat (6).log](https://github.com/osmandapp/OsmAnd/files/9401831/logcat.6.log)

### Steps to reproduce
Download "Germany North Rhine-Westphalia Regierungsbezirk Detmold" map > Updates > Live updates > Update that map

### Actual result
Part of the text is not displayed
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/186140428-33411ea1-9371-4bcc-ba0f-b27d21d2b978.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
The text is displayed in its entirety, as in Kyiv, Ukraine

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13729mqta, released: 2022-08-23
Android/iOS version: Android 11
Device model: POCO X3 NFC

**Comment by dmpr0** [comment]
Related to https://github.com/osmandapp/OsmAnd-Issues/issues/1508

**Comment by scaidermern** [comment]
This is the correct issue: #15052

**Comment by Zirochkabila** [comment]
> This 

This bug should be fixed by now
