### ISSUE TITLE
The route line remains after navigation (Open GL)

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15141]
### Description
When navigating, after changing the location, the line of the route is displayed on the track
[logcat (5).log](https://github.com/osmandapp/OsmAnd/files/9401783/logcat.5.log)

### Steps to reproduce
Navigation > Select point of departure > Set destination > Options > Simulate navigation > Settings > Realistic simulation > Start

### Actual result
The route line remains after navigation
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/186138138-22a9d9ae-f196-4bbf-911e-a5e844a922a3.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
The route line disappears after passing the position

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13729mqta, released: 2022-08-23
Android/iOS version: Andriod 11
Device model: POCO X3 NFC

**Comment by vshcherb** [comment]
Merged to internal issue.
