### ISSUE TITLE
Flooding Gilan province

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15150]
### Description
When using OpenGL on the map of the city displays water. 
12.2.7 and 13.2.7 zoom.
[logcat (7).log](https://github.com/osmandapp/OsmAnd/files/9415414/logcat.7.log)

### Steps to reproduce
Search > 37.46791866684242, 49.49304459307722 > zoom

### Actual result
The map shows the water

https://user-images.githubusercontent.com/104760013/186401889-b12ee89f-3852-436d-b443-a72653e929c2.mp4

### Expected result
The map is displayed without water

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13731mqta, released: 2022-08-24
Android/iOS version: Android 11
Device model: POCO X3 NFC

**Comment by ivanPyrohivskyi** [comment]
> 

Will fix in this issue https://github.com/osmandapp/OsmAnd-Issues/issues/1074

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.3.0#13743mqta, released: 2022-08-31 
17 2.7 zoom
44.40930° N, 8.93019° E

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.3.0#13869mqta, released: 2022-10-14 (OpenGL)
Blue artifacts appear on the map **Denmark_central-region_europe.road** at zoom 12 2.7 and more


https://user-images.githubusercontent.com/104760013/195985357-f3877239-eaea-4f56-aef3-ef321928dc66.mp4
