### ISSUE TITLE
Opens tomorrow is incorrect with specific year / month exception

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15155]
Tag value is ```Mo-Fr 11:00-22:00; Sa,Su,PH 12:00-22:00; 2022 jul 31-2022 Aug 31 off "Betriebsferien"```

<br class="Apple-interchange-newline">
### Description
The place is displayed open (Opens tomorrow at 11:00, When using hourly map updates), but the information says that it is closed from July 31 to August 31 https://www.openstreetmap.org/node/9858456718#map=19/50.45886/7.72272

### Steps to reproduce
Search > 50.458881812358875, 7.722552934398069 

### Actual result
The place is displayed Opens tomorrow at 11:00
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/186695053-ec504e8a-eae4-487a-bffd-1bac27dddd4f.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
The pizzeria is closed according to the specified time at the link

### Your Environment
OsmAnd Version: 4.2.7
Android/iOS version: Android 11
Device model: POCO X3 NFC

**Comment by Dima-1** [comment]
Added [test](https://github.com/osmandapp/OsmAnd/commit/33f8e0189ff0f6b17e3d4c2f62d417578c124ffb), issue isn't reproduced
