### ISSUE TITLE
Map artefact

### ISSUE THREAD

**Issue by 9662** [osmandapp/Osmand#1515]
This screenshot shows a straight road segment that does not exist in reality. It is most likely a problem with the underlying OSM data, but I am unable to check at the moment. It is not visible here: http://www.openstreetmap.org/#map=12/41.7670/2.9203

Perhaps a kind soul can double check and confirm? The location should be deducible from the toponyms shown and from the OSM URL.

![tmp_screenshot_2015-08-02-03-22-13742911125](https://cloud.githubusercontent.com/assets/13080040/9024290/c98d522e-38c7-11e5-93a0-1460bcff1ce0.png)

**Comment by 9662** [comment]
The offending segment starts near the bottom "GI-681" label and goes NNW for about 10 km.

**Comment by vshcherb** [comment]
Fixed in new maps (some already generated, expected this week)
