### ISSUE TITLE
Add track waypoint menu disappears

### ISSUE THREAD

**Issue by martinstingl** [osmandapp/OsmAnd#15169]
### Description
When I do "Add track waypoint", (enter some text) and accidentally touch on the white surface around the "Save" button, the "Add track waypoint" menu is closed (and the text gets lost).

### How to reproduce?
Select a point on the map
Actions -> Add track waypoint
Enter name
Touch on the white space around Cancel and Save
Add track waypoint menu closes without asking

### Your Environment
OsmAnd Version: 4.2.6

**Comment by scaidermern** [comment]
I can reproduce this with OsmAnd 4.2.7.
