### ISSUE TITLE
"Height Correction" downloadable map always outdated

### ISSUE THREAD

**Issue by RalfJung** [osmandapp/Osmand#1516]
The "Height Correction" (free translation back to English) downloadable map says that its latest version is from July 2005. But after downloading, the app OSMAnd~ thinks that it has a version from August 2015 (the date I downloaded the map), and shows this date in orange. The map is listed in "Updates".

I don't know if the shown date is correct, but in any case the app should not consider a just-downloaded map as needing update. It's impossible to get rid of this entry in "Updates", except for uninstalling the map.

This is with the latest version from F-Droid.

**Comment by vshcherb** [comment]
Fixed in nightlies.
