### ISSUE TITLE
The location is designated as a military facility

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15161]
### Description
Preußische Velmerstot is marked as a military facility, although it is now a decorative observation tower
https://www.openstreetmap.org/way/948955387#map=16/51.8329/8.9553

abandoned: landuse military
abandoned: name HAWK-Flugabwehrstellung Velmerstot
[area](https://wiki.openstreetmap.org/wiki/Uk:Key:area?uselang=uk)	yes
[description](https://wiki.openstreetmap.org/wiki/Uk:Key:description?uselang=uk)	ehemalige Hawk-Flugabwehr-Raketenbasis Velmerstot, die von der niederländischen Garnison in Blomberg betrieben wurde.
[historic](https://wiki.openstreetmap.org/wiki/Uk:Key:historic?uselang=uk)	military
[note](https://wiki.openstreetmap.org/wiki/Uk:Key:note?uselang=uk)	Flächenumriss nur ungefährt eingezeichnet, weil hier im Unterschied zu den benachbarten ehemaligen Flugabwehrraketenstellungen Zäune, Straßen etc. entfernt, die Fläche rekultiviert wurde. Nur noch der teilweise offenliegende Bauschutt und einige Böschunge

### Steps to reproduce
Search > 51.832314, 8.955221

### Actual result
The location is designated as a military facility
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/186924233-878af387-b592-4e7c-990e-ead8ff55255c.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
The location is displayed as a civilian object

### Your Environment
OsmAnd Version:  OsmAnd~ 4.3.0#13735mqta, released: 2022-08-26
Android/iOS version: Android 11
Device model: POCO X3 NFC

**Comment by xmd5a2** [comment]
Fixed
![Screenshot_2022-11-15_10-34-04](https://user-images.githubusercontent.com/5829014/201857716-11d34f8e-010d-4ab4-8b26-26323d9b06e0.png)
