### ISSUE TITLE
[bug] German translation bug "car sharing"

### ISSUE THREAD

**Issue by dktzde** [osmandapp/Osmand#1517]
Hi, "car sharing" is in the German version translated as "Fahrgemeinschaft" but it should be "Carsharing". Because in osm car sharing means a station where I can "borrow" a car from a car sharing company (see https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcar_sharing). And the German expression Fahrgemeinschaft means "to share a car to work". There is a wrong Translation in the POI search of osmand. I would help to do the translation but a cannot find it.

**Comment by vshcherb** [comment]
I guess it here, please make pull request https://github.com/osmandapp/OsmAnd-resources/blob/master/poi/phrases/de/phrases.xml

**Comment by stephan75** [comment]
@dktzde : also have a look at the weblate.org translation section for osmand: https://hosted.weblate.org/projects/osmand/

there you can translate also the "phrases" ... log in there with github account if you want.

**Comment by dktzde** [comment]
@stephan75: thanx a lot, before a couldn't fine the right place on weblate (missing the "phrases" link in the beginning)
