### ISSUE TITLE
Encode URLs with spaces in wikipedia tag

### ISSUE THREAD

**Issue by Crashillo** [osmandapp/OsmAnd#15176]
### Description
When the wikipedia article contains spaces in the tag, let's say `wikipedia=en:Some Place`, the generated url does not encode properly the space(s), creating an url link like _https://en.wikipedia.org/wiki/Some Place_, missing those words after the space

### How to reproduce?
- Open [this node](https://www.openstreetmap.org/node/1692315493) with OsmAnd
- Click on the wikipedia article
- Your mobile browser does not handle the link, opening the search engine instead of the article itself, because it misses all the way from the space on

**Comment by Dima-1** [comment]
https://user-images.githubusercontent.com/31807095/187618738-2fcc51f9-ec28-40a6-937c-e89d014ce448.mp4

**Comment by Crashillo** [comment]
@Dima-1 it works as expected because the browser you're using is able to parse the urls properly, but the exported url still contains blank spaces
