### ISSUE TITLE
Cached Overlay Maps Not Loading

### ISSUE THREAD

**Issue by Dollarius** [osmandapp/OsmAnd#15174]
I use (and love) OsmAnd for riding and hiking in the wild.
Hence, offline maps are a must for me as I'm often without phone signal.
Particularly, I use the Strava heatmaps as Overlay Maps (Expiry time=Never, SQLiteDB file) over the standard OSM offline vector map.
I am used to caching the overlay maps when I have wi-fi, and then use them in flight mode when I am on the trails.
This worked perfectly until a few weeks ago.

In the recent OsmAnd versions, in fact, the app does not load the cached maps when in flight mode.
If I turn on the 3g connection, even if there is zero Internet signal, the maps instantly appear (because they are all cached on the phone, as I can see by the space they are occupying under Download Maps/Local Maps).
Am I doing something wrong?
I would greatly appreciate it if you could solve this bug.
Thank you very much!
Giordano

OsmAnd: 4.3.0#34512m
Android version: 12
Samsung Galaxy S20 FE

**Comment by Zirochkabila** [comment]
>

When using the overlay map [strava.sqlitedb.zip](https://github.com/osmandapp/OsmAnd/files/9453514/strava.sqlitedb.zip) - the map displayed in the mode of use, as well as when there is a connection to the Internet is no different.

Please describe in detail the steps of playback (the way you do it) and send us the map Strava (maybe the problem is in it)

**Comment by Dollarius** [comment]
I am using the SQLiteDB maps from Anygis (https://anygis.ru/Web/Html/Osmand_en).
I was able to cache the Google maps, the Strava heatmap, and basically any other overlay map, and then view them offline.

To put the problem in simple form: now OsmAnd does not load the cached maps at all. It is as is the maps are all with expiry time "immediate", i.e. they need to be redownloaded each time (while I set them to expiry=never).

These are the steps to illustrate the problem:
1. Open OsmAnd with wi-fi. Browse maps -> they get cached
2. Switch to flight mode. All cached maps are visible (can move around, zoom in, etc)
3. Close and reopen OsmAnd: no cached map is visible.

Up to a few weeks ago, on step 3 I could still see all the cached maps.
I know that they are saved on the phone because they take storage space.

What can I do to solve this issue?
Thank you very much for your input!

**Comment by Dollarius** [comment]
Misclicked the "closing issue", sorry. Problem not solved as further described above.

**Comment by Zirochkabila** [comment]
> 
The test was conducted with the map 
[=Aviation=Esri_Navigation_Charts.sqlitedb.zip](https://github.com/osmandapp/OsmAnd/files/9477433/Aviation.Esri_Navigation_Charts.sqlitedb.zip)


1. With OpenGL activated, OsmAnd release version 4.2.7, released: 2022-07-13 - reproduced failed
[1.log.zip](https://github.com/osmandapp/OsmAnd/files/9477426/1.log.zip)


2. With OpenGL deactivated, release version OsmAnd 4.2.7, released: 2022-07-13 - reproduced failed
[2.log.zip](https://github.com/osmandapp/OsmAnd/files/9477427/2.log.zip)

3. With OpenGL activated, OsmAnd night version ~ 4.3.0#13749mqta, released: 2022-09-02 - failed to reproduce
[3.log.zip](https://github.com/osmandapp/OsmAnd/files/9477430/3.log.zip)


4. With OpenGL deactivated, night version OsmAnd~ 4.3.0#13749mqta, released: 2022-09-02 - **reproduced DONE.**
[4.log.zip](https://github.com/osmandapp/OsmAnd/files/9477431/4.log.zip)


Accordingly, if you use the night version of the app - try to activate OpenGL rendering: Menu > Plugins > OsmAnd development > Settings > Use OpenGL rendering > Restart OsmAnd

**Comment by Dollarius** [comment]
Thanks for your comment, but for me the raster maps do not load from cache even if OpenGL is enabled (I downloaded the latest 2022/09/02 android_full nightly, and restarted OsmAnd+phone).

I think the bug is related to the update of July 12th, as I explained here:
https://github.com/osmandapp/OsmAnd/issues/15204

Please let me know if I can give any help to identify the issue.
