### ISSUE TITLE
Next turn instruction is way off

### ISSUE THREAD

**Issue by DamianoPantani** [osmandapp/OsmAnd#15171]
### Description

Unsure if related:
https://github.com/osmandapp/OsmAnd/issues/12636

Next turn instruction is shown too early. Example below, I had about 200 m to a right-turn, but the app "thinks" I am already 1 km ahead, and warns me about the next left-turn:

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/16529024/187080683-bd8bc129-8cee-41f6-9034-38fb3e23af4c.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

And the longer on the wheels you are, the effect is more visible, on average 1 km off per each navigation hour, so e.g. after 2 hours ride, app "thinks" you are 2 km ahead, and wants you to "turn right" while there are no intersections nearby. And it's regardless you're on a bicycle or a motorcycle (3 x speed). Stoping and restarting navigation solves the problem (at least for the next few minutes):

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/16529024/187080701-cb21b4ca-57d6-49fc-9102-ff62025158e9.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### How to reproduce?

Nav profile doesn't matter. Works every time, but you can download exact GPX from above screenshots [here](https://drive.google.com/file/d/1tOOLHmmTjyqkEYDQBSEZEJgG2wwXCHYC/view?usp=sharing), and [here](https://www.openstreetmap.org/#map=15/50.9057/20.4907) is the exact location - heading E. Changing speed settings makes no difference

### Your Environment
OsmAnd Version: 4.2.7 (newest as of now)
Android version: 12
Device model: Samsung Galaxy S10

**Comment by scaidermern** [comment]
Is this a regular navigation or did you follow a GPX track? If this is a GPX track did you create it in OsmAnd with the "plan a route" tool?

**Comment by DamianoPantani** [comment]
^ I followed a GPX track created via "plan a route" indeed. And the bug is here since I started using the app (over a year now)

**Comment by scaidermern** [comment]
There have been several similar reports with tracks from the "plan a route" tool. Here is another ticket #14331. It also contains links to even more tickets with similar reports.

**Comment by DamianoPantani** [comment]
Yeah seems the same as #14331 and e.g. #13031 (but it's closed down). Up to you if you want to close this ticket as duplicate, but please re-escalate the issue if needed

**Comment by scaidermern** [comment]
I can't do any of that, I'm just a regular user and not an OsmAnd developer :)

**Comment by DamianoPantani** [comment]
Ah sorry :) The `Contributor` label confused me then 😃

**Comment by Zirochkabila** [comment]
4.2.7 - can be reproduced when simulating navigation on the GPX.
But when simulating navigation without using GPX - voice prompts work correctly.

**Comment by DamianoPantani** [comment]
@Zirochkabila Since the new season I couldn't reproduce, regardless on the profile / settings / speed etc... Are we OK to close this one down?

**Comment by vshcherb** [comment]
Good news, I hope  changes done last year resolved the situation

**Comment by K-Krs** [comment]
I am unsure why this ticket has been closed. The issue is still there #17090.
