### ISSUE TITLE
The routing line is above the address name.

### ISSUE THREAD

**Issue by LeLuyen** [osmandapp/OsmAnd#15179]
Hi all,

Now, the routing line is above the address name, when i'm driving i can't see the address name.

How can order the address name before the routing line?

![z3681373800810_c82e5152273aa97923fb0cbd7b4a1085](https://user-images.githubusercontent.com/2620445/187197958-e2044d5b-ec09-4e76-800f-b9f4ada7acd2.jpg)
![z3681331722511_29316cb01b758eb47b61b96af1f2f324](https://user-images.githubusercontent.com/2620445/187197970-5e645bfe-a41d-4844-bd92-a29e775fb12f.jpg)

Thanks you!

**Comment by vshcherb** [comment]
With opengl routing it will be below (you can already test with 4.3 build)

**Comment by LeLuyen** [comment]
Hi @vshcherb ,

I tested on opengl-arm64-nightly build on 30/08/2022 but It's not resolve.

Thanks you.

**Comment by scaidermern** [comment]
With OsmAnd 4.2.7 and enabled OpenGL the street name _is_ on top. However it is hard to read (black on blue/gray).

**Comment by LeLuyen** [comment]
Hi @scaidermern 

I don't think so, i think the address name is below the routing line.

You have ever the stress name is on the routing line because the color of routing line is setting by alpha.

**Comment by scaidermern** [comment]
This is with OsmAnd 4.2.7 and enabled OpenGL:

![photo_2022-08-30_09-27-11](https://user-images.githubusercontent.com/1040784/187376221-e034f4b7-bc1f-4fe6-9c81-611e849eb0ab.jpg)

**Comment by LeLuyen** [comment]
Hi @scaidermern 

In image 1 post by you, the color of routing line is setting by alpha color then you can see street name by through.

In image 2 post by you, the color of routing line is not setting by alpha color then you can't se it.

If the street name is on top then the "Fahrschule Bernert" will be on.

**Comment by scaidermern** [comment]
@LeLuyen I see but this is the default routing line style. I didn't change it.

Also it looks like the problem is not only the routing line but also the turn arrows. In day mode the routing line is transparent but not the arrows. So even in day mode street names can be hidden if they are below the turn arrows. Maybe this is made deliberately. In night mode the whole routing line is opaque, hiding everything below it.

**Comment by LeLuyen** [comment]
Hi @scaidermern 

Yes, how ever do you think it's bug or feature? :)

**Comment by LeLuyen** [comment]
Hi @vshcherb 

Can you re-open this issue?
