### ISSUE TITLE
Make enforcement POI overlay icons more intuitive

### ISSUE THREAD

**Issue by chereskata** [osmandapp/OsmAnd#15182]
As of today, every enforcement relation, be it enforcement=traffic_lights or enforcement=maxspeed is displayed in the POI overlay as a car icon with "taxi" written below it. Therefore it is not intuitively deducable (for me at least), what the shown POI on the map actually is. It looks like this for a double relation with enforcement=maxspeed and enforcement=traffic_signals:

![1](https://user-images.githubusercontent.com/87526889/187245338-d207576f-3c58-4a39-92e7-dd9ac1db6739.png)

Maybe it would be wiser to mark each (enforcement=) value with a distinct icon. For enforcement=maxspeed the icon of highway=speed_camera can be used for the device node and for enforcement=traffic_signals the device node can be marked with some kind of traffic signal icon (like here: https://www.google.com/search?q=red+light+radar+icon).

Thank you for your time.

P.S. If someone could point me at the right parts of the code, i could create a push request. As of now i am not familiar with the codebase (yet)

**Comment by hakuchi** [comment]
@kozboko if I found the correct enforcement relation in Dortmund, how do you get them into OsmAnd, because this relation was added 1-2 days ago?
I can not reproduce this error on latest nightly version with latest maps.

What is your version? App and map?

**Comment by kozboko** [comment]
@hakuchi i use OSMAnd 4.2.4 on iOS with the latest NRW Map + live updates

**Comment by ivanPyrohivskyi** [comment]
TODO: POI speedcamera
