### ISSUE TITLE
Конец маршрута на мосту

### ISSUE THREAD

**Issue by gtrus21** [osmandapp/OsmAnd#15183]
1) нельзя заканчивать маршрут на мосту. На мосту остановка запрещена ПДД. Надо закончить маршрут перед мостом или после моста
2) нельзя делать выход с моста (уровень 1) на землю (уровень 0). Это прыжок с моста.
56.13448° N, 47.46758° E

![Screenshot_2022-08-30-10-01-55-096_net osmand plus_1](https://user-images.githubusercontent.com/69676792/187371988-49916e1a-1931-40b1-9998-f5de6d42f7b5.jpg)

**Comment by scaidermern** [comment]
Duplicate of #1578 and similar tickets (the error for a bridge the same as for a tunnel).
