### ISSUE TITLE
Bicycle routing: Routing along vehicle=agricultural and vehicle=forestry although forbidden

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#15194]
In bicycle routing OsmAnd seems to respect `vehicle=private` and `vehicle=no`. However, other combinations such as `vehicle=agricultural` and `vehicle=forestry` (and probably also `vehicle=agricultural;forestry`, `vehicle=forestry;agricultural`and similar combinations) are not respected. OsmAnd calculates bicycle routes along these ways although cycling is forbidden there.

**Comment by vshcherb** [comment]
Why cycling is forbidden along vehicle=forestry? Not sure if it's local specific or not
https://discuss.graphhopper.com/t/bicycle-allowed-on-vehicle-delivery-or-vehicle-forestry/6983/2
```
restrictedValues.add("agricultural");
        restrictedValues.add("forestry");
```

**Comment by scaidermern** [comment]
> Why cycling is forbidden along vehicle=forestry? Not sure if it's local specific or not

I don't know if this is country specific 
However, https://wiki.openstreetmap.org/wiki/Key:access is rather clear about this. agricultural means that this way is only open for agricultural traffic (which cycling clearly isn't). forestry means that this way is only open for forestry traffic (which cycling clearly isn't either). 

> https://discuss.graphhopper.com/t/bicycle-allowed-on-vehicle-delivery-or-vehicle-forestry/6983/2
> 
> ```
> restrictedValues.add("agricultural");
>         restrictedValues.add("forestry");
> ```

Interesting. So graphhopper did have the same bug but it has been fixed I suppose.

**Comment by Phoenix616** [comment]
In my country (Germany) such road restrictions always only refer to motorized traffic, which bycicles are clearlt not (they can basically drive anywhere that isn't a pedestrian way or closed-off private property)

Disabling routing like that would potentially remove tons of otherwise suitable ways.
