### ISSUE TITLE
Edit created POIs

### ISSUE THREAD

**Issue by james2432** [osmandapp/Osmand#1519]
When you still have the POI in your local changeset and have not uploaded it, there does not seem to be a way to edit the information other than deleting the POI and recreating it. Editing is useful incase of a typo or you want to add additional tags to your POI(after a survey)

**Comment by Barrocas** [comment]
I also feel the need to have this option, it would be  very usefull.

**Comment by vshcherb** [comment]
Yes it is on the roadmap
