### ISSUE TITLE
The Create POI may lose your data

### ISSUE THREAD

**Issue by zander** [osmandapp/OsmAnd#15199]
### Description

The 'Create POI' workflow ends with "Upload" "Delete" as options, but you can bypass this and lose your data.

### How to reproduce?

* Ensure you have the plugin enabled.
* long-press anywhere on the map.
* Press "Actions" in the popup.
* Select "Create POI" in the next popup.
* Enter data and press "Save".
* You now have a dialog with "Upload" and "Delete". Notice how the latter nicely shows a warning.  
   Here we press neither button but instead we long press elsewhere on the map to start a new POI.
* You just lost all data you entered, without any warning.

### Your Environment
OsmAnd Version: 4.2.6
Android/iOS version: Android 11
Device model: Terracube 2e

As an aside; the goal why I didn't press "Upload" was due to the wish to add several POIs in a single changeset. I expected the phone to remember the new details until I reach the point of pressing upload. I probably didn't understand how OSMAnd enables that workflow, but I write it here to clarify the thinking.

Minor issue; on creation of a POI the dialog that opens has "Cancel" / "Save" as buttons at the bottom. This is likely due to being reused from the edit-poi feature. Maybe for creating one "Ok" would be better than "Save" due to the fact that the next screen shows an "Upload" button.

**Comment by scaidermern** [comment]
> You just lost all data you entered, without any warning.

You didn't loose your modifications. They are still reachable via My Places / OSM Edits. Maybe this is not obvious right away. Also there should be a green icon placed on the map with an "i" in it which represents your POI edit. Only if enabled under Configure map / OSM Edits.
