### ISSUE TITLE
Path routed through barrier=retaining_wall in Warsaw old town

### ISSUE THREAD

**Issue by etam** [osmandapp/OsmAnd#15193]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

bike and pedestrian

### Start and end points

https://osmand.net/map?start=52.246866%2C21.014131&end=52.246791%2C21.013954&mode=pedestrian#20/52.24686/21.01400

### Actual and expected routes

Actual result: ![Screenshot_20220831_085426](https://user-images.githubusercontent.com/220752/187612967-feae5032-c1d4-45cd-965f-d371a8434e3f.png)

Expected result:
- green line: expected path
- red line is impossible to go through

![map](https://user-images.githubusercontent.com/220752/187613399-bd46c051-81a9-4c11-9e7a-a47393024645.png)

### Is this a regression?

I don't know.

## 🌍 Your Environment

**OsmAnd Version:** 4.1.11

**Device and Android/iOS version:** Sony Xperia L1, Android, LineageOS 14.1

**Maps used (online or offline):** offline

- [x] Offline maps offered within the OsmAnd app for download.
- [ ] Online (tile / raster) maps 

**Anything else relevant?**

Also reproducible with https://osmand.net/map

This is how it looks like: https://commons.wikimedia.org/wiki/File:Konstal_116N_3002,_tram_line_46,_Warsaw,_2010.jpg . The stairs are mandatory ;)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.3.0#13776mqta, released: 2022-09-14 - **reproduce**

Location coordinates 52.24687, 21.01413

Expected route
https://www.google.com.ua/maps/dir/52.2468032,21.013943/52.24685,21.0142971/@52.246957,21.0138273,19.83z/data=!4m2!4m1!3e2?hl=uk
<img width="1105" alt="Screenshot 2022-09-14 at 12 11 45" src="https://user-images.githubusercontent.com/104760013/190113068-5c1f25ea-0413-4a7b-9219-5f0dcc70a885.png">


OSM route  https://www.openstreetmap.org/directions?engine=fossgis_osrm_foot&route=52.24679%2C21.01390%3B52.24691%2C21.01435#map=19/52.24699/21.01401
OSM wall https://www.openstreetmap.org/way/1028615023#map=19/52.24688/21.01402

route change point https://osmand.net/map?start=52.246986%2C21.013927&end=52.246899%2C21.014244&mode=pedestrian#19/52.24693/21.01425  cost 57 (**correct plan route**)
<img width="1438" alt="Screenshot 2022-09-14 at 12 08 53" src="https://user-images.githubusercontent.com/104760013/190112267-3b851172-9ea8-428a-97f9-9a1b1a9e3d14.png">


route change point  https://osmand.net/map?start=52.246981%2C21.013927&end=52.246899%2C21.014244&mode=pedestrian#19/52.24693/21.01431 cost 57 (**incorrect plan route**)
<img width="1438" alt="Screenshot 2022-09-14 at 12 08 42" src="https://user-images.githubusercontent.com/104760013/190112333-b4f88c5d-dc2d-46b9-81d1-6e67b91637a6.png">

**Comment by vshcherb** [comment]
Unclear why routing uses https://www.openstreetmap.org/way/1028615023 to navigate to footway. This route should be forbidden or not permissive

**Comment by xmd5a2** [comment]
> maybe it's using this https://www.openstreetmap.org/way/198503051 not noticing there's a barrier in the way.

I think this is a mapping issue but it is not clear how to map this place correctly. There is a pedestrian area on top and footway on layer=-1
![Screenshot_2022-09-19_10-23-41](https://user-images.githubusercontent.com/5829014/190968185-046481ce-d2a1-4151-8a03-5515994ccb5e.png)
Pedestrian area and footway has a shared node. Looks like that them should not share it or they should be on different layers.

**Comment by Zirochkabila** [comment]
**New one**

### Description
The route is built without using roads
https://osmand.net/map?start=51.127957%2C1.324325&end=51.125472%2C1.319668&mode=car#16/51.1269/1.3234 **incorrect**
https://www.openstreetmap.org/directions?engine=fossgis_osrm_foot&route=51.1279%2C1.3243%3B51.1255%2C1.3197#map=16/51.1269/1.3209 **correct**

https://drive.google.com/drive/folders/1I0rS2r7hmhxDuMH-eXzxn7rUuIWMEMi7?usp=sharing **map here**

### Steps to reproduce
Set point of departure `51.12794° N, 1.32458° E` > Set destination `51.12540° N, 1.32187° E`

### Actual result
Route is built without using roads

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/190981505-3fbdeb6d-3cc0-4917-ac4a-ec0c2342438a.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  


### Expected result
Like in OSM

### Your Environment
OsmAnd Version: 4.2.7
Android/iOS version: Android 12
Device model: POCO X3 NFC

**Comment by xmd5a2** [comment]
@Zirochkabila please don't mix different issues and create separate issue

**Comment by vshcherb** [comment]
@xmd5a2 we have a common rule that non-connected roads from different layers shouldn't have same node. Unfortunately in OsmAnd we don't store nodeids inside roads, so even if nodes are different they still should be slightly shifted against each other so they don't overlap

**Comment by xmd5a2** [comment]
Fixed https://www.openstreetmap.org/changeset/126640010
