### ISSUE TITLE
Tag mtb:name does not render.

### ISSUE THREAD

**Issue by Velomeloman** [osmandapp/OsmAnd#15197]
### Description
Paths with tag mtb:name unnamed on map when setting "Mountain bike routes" is enabled.

### How to reproduce?
For example
![Screenshot_20220831_150354.jpg](https://user-images.githubusercontent.com/109347561/187674250-c780cfc6-f9ed-432d-928b-969262e5a3d0.jpg) https://www.openstreetmap.org/way/203791062#map=16/55.6277/37.5719

### Your Environment
OsmAnd Version:
Osmand~ 4.3.0

**Comment by scaidermern** [comment]
Should they be rendered additionally to the `name` tag? I think we should not loose the main name.

**Comment by Velomeloman** [comment]
I think if setting "Mountain bike routes" is enabled, mtb:name should have high priority. If user want see MTB trails, it should have mtb:name.
For example tag name contents piste name. https://www.openstreetmap.org/way/372090203#map=15/55.6010/37.5690
MTB trail usually is just a path in woods or mountains with no well-known name.

**Comment by xmd5a2** [comment]
Will be available with may maps and new OsmAnd release

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#35870m, Released: 2023-05-02
4.4.8.3

The title of the track is present, but:
1. Android - the name is displayed from the 16th noise level, iOS - from the 14th
2. Android - when switching from the 14th to the 15th and from the 15th to the 16th zoom level, the track name blinks
**Android - OpenGL version** legacy - same as iOS



<table style="width:100%">
  <tr>
    <td><video source src="https://user-images.githubusercontent.com/104760013/235648691-184baa66-6ba8-4c78-8d29-bc389b3a3488.mp4"  width="300" height="auto"/></td>
    <td><video source src="https://user-images.githubusercontent.com/104760013/235648717-07b3a220-dcab-4445-9756-2bd4e6cdaea0.mp4"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Velomeloman** [comment]
Titles of some (not all) mtb trails not signed then 3D maps is anabled.

![Screenshot_20230512_150103_net.osmand.plus.jpg](https://github.com/osmandapp/OsmAnd/assets/109347561/0ded93fa-7f36-4a5e-87a0-bb0e3333fdfd)
3D maps disabled

![Screenshot_20230512_150131_net.osmand.plus.jpg](https://github.com/osmandapp/OsmAnd/assets/109347561/b91e6fbf-ad21-490e-bee3-71a407b8f57a)
3D maps anabled 

https://osmand.net/map?pin=55.64164,37.56202#17/55.64164/37.56202

**Comment by vshcherb** [comment]
With 3D we don't render non-flat labels yet cause it's not supported.
