### ISSUE TITLE
POI editing: Remove immediate keyboard focus from input fields

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#15206]
Is it possible to remove the immediate keyboard focus from input fields? When editing a POI the keyboard focuses immediately in the name tag. When switching to the advanced tag the keyboard focuses immediately on the last tag key. This can lead to accidental editing of these fields. It would be better if there was no immediate keyboard focus.

**Comment by vshcherb** [comment]
Mostly focus is important to speed up editing, so it will be end to end discussion to add and to remove. From my experience developers don't add focus by default, so it was requested most likely by somebody.

**Comment by scaidermern** [comment]
I can't imagine that someone requested that the focus is on the last tag (which seems completely random). Also, how often does somebody change the name of a POI when editing? Doesn't sound very convincing to me.
