### ISSUE TITLE
Combine MTB Routes into one screen – Configure Map

### ISSUE THREAD

**Issue by ArjanOnwezen** [osmandapp/OsmAnd#15208]
### Description

Missing icon in Configure Map - Show MTB trails

### Your Environment
OsmAnd Version: latest
Android/iOS version: N/A
Device model: N/A

<img src="https://user-images.githubusercontent.com/44684169/188014106-b3a6bb45-d8fd-490f-bd91-da02343c19ef.jpg"  width="300" height="auto"/>

**Comment by dmpr0** [comment]
We need to combine the current two options for the MTB route in one screen.
<table style="width:100%">
  <tr>
    <th>Routes</th>
    <th>Mountain bike</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/192237335-d661694f-5acd-40a9-b3f1-546541812433.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/192237325-a48201a8-8b69-4201-9044-2c00c9d38ebc.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
IMBA Trails -> "Indicate imba trail scale" or "Indicate mtb trail scale"

**Comment by xmd5a2** [comment]
This should also be done for "topo" rendering style

**Comment by dmpr0** [comment]
Location: geo:47.46892,11.31046?z=15
https://osmand.net/map?pin=47.46892,11.31046#15/47.46892/11.31046

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/203502243-85a9e73d-c6e5-4dad-8799-7d4ab3495a51.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/203502233-13b6ef91-a63e-4399-a40a-facf24f063c2.png"  width="300" height="auto"/> </td>
  </tr>
</table>
