### ISSUE TITLE
OsmAnd/NB crashes when setting a marker

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/OsmAnd#15202]
### How to reproduce?
* Tap on the map, 
* see location pin. 
* Address is being looked up. 
* Tap on "Marker", 
* OsmAnd crashes ("OsmaAnd~ has stopped")

Side observation: 
* When starting, OsmAnd show a toast message "null", and route calculation fails #15203.

### Your Environment
OsmAnd Version: 
* OsmAnd-master-nb-2022-09-01.apk, 
* <strike>already observed since OsmAnd-master-nb-2022-08-23.apk</strike> 
* *last working* was OsmAnd-master-nb-2022-07-11.apk 4.3.0#34358m

Android/iOS version: Android 7.1.1 Kernel 3.10.84
Device model: BQ, Aquaris X5 Plus

**Maps used (online or offline):**   
Recent Germany/Brandenburg and Germany/Bavaria

screenshots follows, will try to go backwards to working NB
![Screenshot_20220901-103752](https://user-images.githubusercontent.com/8266355/187883432-94c3932e-dca4-47ec-b462-853a7877f2d6.png)
![Screenshot_20220901-103800](https://user-images.githubusercontent.com/8266355/187883441-5b65d802-b18f-4a34-aba3-8d442af80efe.png)

**Comment by polarbearing** [comment]
Narrowing down:
OsmAnd-master-nb-2022-07-04.apk:
no "null" toast, shows me all previous marker attempts in the same colour. Can set new marker. Routing works.

**Comment by vshcherb** [comment]
Can you attach log file?

**Comment by polarbearing** [comment]
re log, found 'exception.log' among the osmand files, it contains an 
```UnsupportedOperationException```
at
```CopyOnWriteArrayList```

Thus the PR sounds promising.

**Comment by polarbearing** [comment]
Fix confirmed for NB OsmAnd-default-nb-2022-09-05.apk / 16:49 / 34557m
