### ISSUE TITLE
[Bug] Raster Maps Always Re-downloaded, not Cached (Since 2022-07-15)

### ISSUE THREAD

**Issue by Dollarius** [osmandapp/OsmAnd#15204]
In the newer versions of OsmAnd, raster maps are always **re-downloaded** from the internet instead of being loaded from the phone cache.
This is for me an important issue, as I like to browse cached raster maps while offline (i.e., in the mountains).

I went back in time to identify when this happened, as I explain below.
1. I installed an old OsmAnd version on my Android phone. Cached the raster Strava heatmaps in SQLiteDb form (blue lines in the screenshot below).
2. Put my phone in flight mode, and kept it in flight mode for the rest of this test: the cached maps can be zoomed in/panned etc.
3. Closing/re-opening OsmAnd, the cached maps are still there.
4. Updated OsmAnd with nightly versions (downloaded from PC at https://download.osmand.net/night-builds/?C=M;O=D ) and the behaviour is as expected up to the nightly 2022-07-11
5. Updated OsmAnd with nightly 2022-07-15 (and following), and the cached maps are not anymore visible when offline (see screenshots below). This is because the app wants to re-download the tiles from the internet (they will appear if internet connection is provided).
6. Rolled back to 2022-07-11, and the cached maps are again all visible while offline.

![OsmAnd_TilesNotLoadedFromCache_Bug](https://user-images.githubusercontent.com/56419637/187874733-607f7b34-3c16-48ea-b977-531a1fe9f2c0.jpg)

I tried digging in the code, and this bug may be related to this pull request of 2022-07-12
[https://github.com/osmandapp/OsmAnd/pull/14814]
Possibly, a change (around line 201?) of the following file is causing this bug
`OsmAnd/src/net/osmand/plus/plugins/rastermaps/DownloadTilesHelper.java`

Is it possible to fix this bug?
I would like to be able to browse cached raster maps while being offline.
Thank you so much for your help and for your contributions to this great app.

**Comment by Chumva** [comment]
https://github.com/osmandapp/OsmAnd/pull/15413

**Comment by Dollarius** [comment]
Thank you very much for promptly solving this bug!
I really appreciate your work.

Sadly, a new bug concerning overlay map tiles appeared, as I described here
https://github.com/osmandapp/OsmAnd/issues/15457
