### ISSUE TITLE
OpenGL Map rendering lags with tracks enabled

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#15211]
OpenGL Map rendering lags with tracks enabled

OpenGL App: Apk Version : 4.3.0#13749mqta 4300 
Log: [logcat (1).log](https://github.com/osmandapp/OsmAnd/files/9477217/logcat.1.log)

<table style="width:100%">
  <tr>
    <th>OpenGL</th>
    <th>Regular</th>
  </tr>
  <tr>
    <td><video source src="https://user-images.githubusercontent.com/9365308/188122955-7e6abc3d-cfc6-4200-a79c-27bce6a740dd.mp4"  width="300" height="auto"/>  </td>
    <td><video source src="https://user-images.githubusercontent.com/9365308/188123002-c9575d18-9964-4835-ab99-c01fc4fc0744.mp4"  width="300" height="auto"/>  </td>
  </tr>
</table>

**Comment by scaidermern** [comment]
Is this the same as #14715?
