### ISSUE TITLE
Bicycle and hiking routes displayed at lower zoom

### ISSUE THREAD

**Issue by bobeeeze** [osmandapp/OsmAnd#15213]
Hi,
Whatever the rendering style, bicycle routes are only displayed from zoom 11 and hiking routes from zoom 12, but it would be interesting to see some of these routes (national and international), e.g. the Santiago de Compostela routes, long-distance hiking trails, EuroBike routes, at lower zoom levels. Would it be possible to show these routes at least from zoom 8?

**Comment by sonora** [comment]
There are so many that you would see a total mess.

But what you can do is single out a specific one by using our new 'tap on a route' feature in the latest releases, then zoom out, and the selected route will renain visible all the way to zoom level 2.

Make sure you use a visible enough color to display routes, such as the cyan the 'Toring view,' map style uses by default. Ifyou want to display several routes, save them as gpx to your device using the feature's download button.

**Comment by vshcherb** [comment]
You can lower zoom by setting map magnifier to simulate how it could look

**Comment by sonora** [comment]
True. ;)
