### ISSUE TITLE
Search for specific bus route (without knowing any of the bus stop on that route).

### ISSUE THREAD

**Issue by vi** [osmandapp/OsmAnd#15218]
# 🚀 feature request

### Description

I can view public transport routes in OsmAnd by tapping at some bus stop, then at the route number available at that stop.

I want to be able to go directly to the route (e.g. "bus 153") by its number, without guessing some bus stop on that route first.

### Describe the solution you'd like

Search -> Categories -> Public transport -> type the route number.

Currently public transport category search only searches for points (e.g. bus stops), not for curves (bus routes).

It would be nice if OsmAnd also recognized special query like "bus 501" or "tram 15", to avoid doing "Categories -> Public transport" first.

Internally I expect OsmAnd to search for all public transport stops with matching routes, for each route select one stop that represents it (e.g. nearest) and display it in search results as if it were a route, not just a stop (maybe duplicating it if necessary). Selecting that entry should select the route with the representating stop being selected by default.

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/5924
