### ISSUE TITLE
maps don't render in default mode

### ISSUE THREAD

**Issue by gerardborst** [osmandapp/OsmAnd#15217]
### Description
Maps don't render in default mode, (java??). They do using OpenGL.

![image](https://user-images.githubusercontent.com/56296132/188268970-51d1ed90-b670-4562-aaf4-54e4c3042024.png)

### How to reproduce?
Pixel 6 Android 13. Just try to render the map of Utrecht.

### Your Environment
OsmAnd Version: 4.2.7
Android/iOS version: Android 13
Device model: Pixel 6

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
Offline map, at least all Netherland maps.

**Comment by scaidermern** [comment]
Duplicate of #14947?

**Comment by gerardborst** [comment]
Yes indeed it looks that way.

With OpenGL it does work, rotation also. The only problem is, especially for normal users, that it doesn't work in default mode.

Is it solved in a new release?

**Comment by gerardborst** [comment]
It looks more like https://github.com/osmandapp/OsmAnd/issues/15045

**Comment by gerardborst** [comment]
Close because of duplicate of https://github.com/osmandapp/OsmAnd/issues/15045
