### ISSUE TITLE
Portions of articles using Wikivoyage template:go not showing up

### ISSUE THREAD

**Issue by wbillan** [osmandapp/OsmAnd#15223]
### Description
Wikivoyage supports rendering templates for Listing, See, Do, Eat, Buy, Drink, and Sleep, but is not rendering templates Go at all.  Except for the colour of the geo marker (which is red in the case of Go), the rendering of Go is identical to Listing, See, Do, Eat, Drink, and Sleep.  Go is for transportation-related listings, e.g. airports, train stations, bus stations, etc.

### How to reproduce?
As an example, if looking at the article for North Sydney (Nova Scotia) in OsmAnd versus Wikivoyage's website (https://en.wikivoyage.org/wiki/North_Sydney_(Nova_Scotia), if you look under "By boat" within the "Get in" section, that all references to Maritime Atlantic and its terminal are missing in OsmAnd.  The Maritime Atlantic information is filled in within a Go template.

### Your Environment
OsmAnd Version: 4.2.7
Android/iOS version: Android 12
Device model: Samsung A51

**Maps used (online or offline):**   
Offline Wikivoyage North America, dated August 29, 2022

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/15224
