### ISSUE TITLE
style of battery icon when charging / not charging

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#15227]
On a motorbike, wearning a helmet, osmands battery icon is (nearly) impossible to see if charging or not. 
I think this may be on Android only, because a few days ago I had seen in another post a green icon when charging - perhaps the Apple view? 

![icon_battery](https://user-images.githubusercontent.com/95540936/188310568-593d7d27-bb91-432f-8ce4-06e1fe6c2c54.JPG)

Please change the colour of the battery icon when charging (to green?), thanks.

**Comment by kozboko** [comment]
I am on iOS, can confirm it is now the same as yours
![IMG_5296 PNG](https://user-images.githubusercontent.com/87526889/188310725-872db4c5-da66-4a6e-8934-82b4948853eb.png)

**Comment by chereskata** [comment]
After installing OSMAnd 4.3 beta it changed to a green icon while charging

**Comment by dmpr0** [comment]
We have changed it in nightly/TestFlight builds.
![telegram-cloud-photo-size-2-5206198424242865424-m](https://user-images.githubusercontent.com/9365308/188380932-1e664a46-e998-41ca-8b5f-9c7cfa3daf7d.jpg)
