### ISSUE TITLE
Osmand not rendering region items fields specified in Regionlist template

### ISSUE THREAD

**Issue by wbillan** [osmandapp/OsmAnd#15225]
### Description
Regionlist template displays several fields, but does not display the region items fields (i.e. region1items, region2items, etc), which are intended to list sub regions of a listed region.

### How to reproduce?
Compare OsmAnd Wikivoyage article for Canada vs https://en.wikivoyage.org/wiki/Canada.  Notice in OsmAnd under "Regions" that under "Atlantic Canada" and "Canadian Prairie" that the list of Canadian provinces do not show up (e.g. "Atlantic Canada" does not include a list of four provinces, including "New Brunswick."

### Your Environment
OsmAnd Version: 4.2.7
Android/iOS version: Android 12
Device model: Samsung A51

**Maps used (online or offline):**   
North America Wikivoyage, dated August 29, 2022

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/15224
