### ISSUE TITLE
Google geo intents: full address text search is not supported

### ISSUE THREAD

**Issue by cordawyn** [osmandapp/Osmand#1523]
When a contact/phone app launches OsmAnd and passes it the address in Cyrillic letters, OsmAnd says: ”Could not parse geo intent: 'geo:0,0?q=%D0%9D%D0.......'" (The text is URL-safe encoded, apparently). It must be a parser bug.

OsmAnd+: 2.1.1
Android: 5.1.1 (Nexus 5)

**Comment by exploide** [comment]
Got the same problem and thought it's due to the occurrence of German umlauts (ä, ö, ü, ß) but apparently it is not even working with very simple queries w/o umlauts or whitespace.

For example
> Could not parse geo intent: 'geo:0,0?q=Darmstadt'

**Comment by GaidamakUA** [comment]
That's true. Search isn't working for now. We know about this problem.

**Comment by vshcherb** [comment]
The search was disabled and we are planning to reimplement it.

**Comment by Tchiller** [comment]
Why is OSMand linked to the label sign in google contacts? When I saw that at first I thought "cool... and default it is". The next thing I could see was a bright blue rectangle with "Kein Treffer" (no result) in the lower part of the screen. Next thing to do was to try several other contacts and finally, to google on how to disconnect OSMand from my google contacts. 
Nothing which would stop me from using OSMand of course. But for some new users this could be annoying or irritating. I do not know, how Android selects the "recommended applications" but if possible, OSMand should only appear for features it is able to handle. 
Thank you!

**Comment by sonora** [comment]
No further action planned, it seems.
