### ISSUE TITLE
Attach to roads: track creates wrong segment

### ISSUE THREAD

**Issue by MagielBruntink** [osmandapp/OsmAnd#15244]
When following a track (attached to roads or not) cycling navigation is often giving really weird prompts, like turning right/left on an obvious straight road without intersections. It also misses prompts on obvious turning points.

It’s hard to say for sure, but it may be that the navigation prompts are given in the wrong order (ie the prompts don’t match the points on the navigated route?) 

It appears that the issue is worse if “attached to roads” has been turned on, but it’s hard to confirm.

**Comment by vshcherb** [comment]
Taken from https://github.com/osmandapp/OsmAnd-iOS/issues/2137
