### ISSUE TITLE
Feature request: Show ground height at arbitrary point

### ISSUE THREAD

**Issue by mikehgentry** [osmandapp/OsmAnd#15242]
At the moment the only way I can find to show the height of an arbitrary point on the map is to route past it, which is a roundabout way of doing it.

A widget that shows approximate ground height where the cursor is would be appreciated. Or if that isn't practical, could the location details type screen you get when you long press on a point display it?

OsmAnd+ 4.2.7

**Comment by littlehelper** [comment]
I would love to see such a solution, or a similar one: #2487

**Comment by mikehgentry** [comment]
Sorry, I evidently did a poor job of searching. Will close as a duplicate.
