### ISSUE TITLE
CRASH on upload new POI

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#15245]
When trying to upload a new poi i always get a crash, easy to reproduce.
osmand OsmAnd~ 4.3.0#34561m, veröffentlicht: 2022-09-06
Samsung S7. Android 8

[exception.log.zip](https://github.com/osmandapp/OsmAnd/files/9507509/exception.log.zip)

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/15043
