### ISSUE TITLE
map rotating on every stop

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#15246]
### Description
Everytime I stop, the map rotates at a certain angle. Drivin again, map is properly aligned again.
Keeping the same main direction, the difference is always about the same angle, like always ~90° right or ~45° left, as long as I keep the same main direction. 

Cant find remedy via settings, dont know what causes this effect.

### How to reproduce?
see the attaches video (unfortunately it is too large)
tried a few screenshots, its always one driving and one on a stop

### Your Environment
OsmAnd Version: 4.2.7 bit its nothing new, was already in earlier versions
Android/iOS version: 12
Device model: S20+

**Comment by pebogufi** [comment]
Open
Configure Profile | Navigation Settings | Map during navigation | Map orientation threshold
set value to 0 (kmh or miles)

**Comment by Rowin63** [comment]
I think, I was already in this setting, without any result.
But I´ll try it again, thanks!

**Comment by Rowin63** [comment]
Yes, that´s it...
I really thought, I was in these settings. But probably I got something wrong...
My fault, sorry for opening this issue.

**Comment by Rowin63** [comment]
>Configure Profile | Navigation Settings | Map during navigation | Map orientation threshold set value to 0 (kmh or miles)

Let me add one question here: I don´t find this menu item (anymore)? I knew it was there, but does it not exist anymore or was it moved to somewhere else? I can´t find this setting... Thanks!

**Comment by pebogufi** [comment]
I confirm, that I don't find it anymore, that it irritating.

**Comment by Zirochkabila** [comment]
Now the bearing from the locations is being pulled up and the map rotation is being calculated based on it
https://github.com/osmandapp/OsmAnd/issues/14681#issuecomment-1278801568

**Comment by Zirochkabila** [comment]
@aikitori Try to disable this function https://osmand.net/docs/user/navigation/guidance/map-during-navigation#animate-my-location

**Comment by raleik-pl** [comment]
Same issue here, I have my phone laying on a table, I'm not even touching it, and the map spins like crazy. And disabling "Animate my location" doesn't help.
