### ISSUE TITLE
Opengl: incorrect display of lines in the mapillary layer

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#15248]
Incorrect display of lines in the mapillary layer.  Strange breaks, as well as the mismatch of lines with shooting points.
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/12549744/188990008-9c606d74-8b2b-45e2-b1bf-e1571062975a.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13760mqta, Дата выпуска: 2022-09-07
Android version: 12
Device model: poco f3

**Comment by Zirochkabila** [comment]
Bug is present with OpenGL rendering (59.95987° N, 30.38980° E)

Try to deactivate OpenGL and restart the application: Menu > Plugins > OsmAnd development > Settings > Use OpenGL rendering > Restart app
