### ISSUE TITLE
Hide polygons (noPolygons style option) when underlay and vector maps are used together

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1525]
I propose to do this automatically because it is not obvious. Underlay and vector maps together are less useful without this option and noPolygons option is hard to find. And it will be nice if noPolygons will be turned off when underlay deactivated.

**Comment by vshcherb** [comment]
It could be confusing as well, if we do it automatically. However I'm not 100% sure

**Comment by sonora** [comment]
In fact, the use case to have an underlay is rather rare, mostly people would use overlay. And if you use underlay, yes, it is in many areas quite useless without having the no polygons option set.

But making intrinsic adjustments here can in fact be very confusing, maybe more confusing than beneficial? I would say for now that only power users knowing what they do will use underlay, and those will likely also play with he no polygons option automatically.... 

Maybe all we should do is pop a toast when someone activates an underlay suggesting that the no-polygons option may be worth activating in this case?

**Comment by xmd5a2** [comment]
Yes, I think a text popup will be enough.

**Comment by vshcherb** [comment]
Fixed
