### ISSUE TITLE
Save current recording color within recorded track

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#15252]
- As a user I expect to change current recording color to Yellow and later when I enable that track I would like to see track as Yellow (not as default color Red).
- Yellow could stay as a color for next current recording track.

**Comment by EugeneZmeuk** [comment]
https://osmand.net/docs/user/plugins/trip-recording#start-dialog

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/plugins/trip-recording/#start-a-dialog
