### ISSUE TITLE
Search filter for access=yes for parking

### ISSUE THREAD

**Issue by tommycrock** [osmandapp/OsmAnd#15259]
It should be possible to filter for access=yes for parking. We can filter _for_ various restrictions but cannot either filter them out (not cumstomers, not private, etc) or for the case where we explicitly can park. It seems maybe osmand doesn't even include this information (maybe assumes default is access=yes?) looking at the info presented when clicking on a parking node with access=yes versus access=customers.

See https://github.com/osmandapp/OsmAnd/discussions/14876

**Comment by vshcherb** [comment]
Indeed we could add to poi types but I don't think it will show unspecified access as well.
```
<poi_additional name="access_yes" tag="access" value="yes"/>
```

For now filters don't support Unspecified values which could be another issue

**Comment by aceman444** [comment]
Yes access=yes is missing in https://github.com/osmandapp/OsmAnd-resources/blob/master/poi/poi_types.xml in access_general category. It is commonly used on parkings or toilets marking that access for everyone is allowed (it is not private or for customers). The access=yes value is displayed in OsmAnd UI in the POI details when such a parking is tapped, but it is displayed as access_yes and untranslated. It is used a lot in the OSM database (https://taginfo.openstreetmap.org/tags/access=yes). Please add it to POIs to fix the display and also allow to search for it.

**Comment by aceman444** [comment]
The value was now added in https://github.com/osmandapp/OsmAnd-resources/commit/77dc5c14d8ab2e0fe39a25a2e4d0cdaca1cbd8e0 . Is this report solved?
