### ISSUE TITLE
Improve rendering speed on Android

### ISSUE THREAD

**Issue by Redsandro** [osmandapp/OsmAnd#15269]
# 🚀 feature request

### Description

Compared to other map apps, OsmAnd is rendering a bit slow. I've been using OsmAnd for a long time (bought OsmAnd+ in 2014) and I've used many versions across many handsets. Its feature set is unparalleled, but it has always been a bit slow to render. Even when the hardware went from dual core to octa core and the chips went from 65 nm to 11 nm, I have not observed a considerable render speed improvement between versions or handsets, when at the same time more map apps emerged, and I am amazed by how smooth they can be.

Here is a comparison between Organic Maps and OsmAnd:

https://user-images.githubusercontent.com/1702193/189488381-3ab3f78f-3364-4083-89be-391776c01ae9.mp4

Is there anything we can do to improve this? Is there any inspiring rendering code in open source apps like [Organic Maps](https://github.com/organicmaps)?

### Describe the solution you'd like

I've identified the following points that make the rendering 'feel' slow in comparison to other apps:

1. Frame rate is roughly a quarter of the refresh rate;
2. When moving around, the sides of the map are often empty, even if they were drawn moments ago;
3. The phone waits with drawing until the moving stops;
4. Pinch zooming in/out sometimes snaps back a considerable amount;
5. It takes a couple of seconds for the final drawing to 'finalize', where Organic smoothly transitions from low detail to high detail including 3d buildings.

I'd like to see a higher frame rate, a wider (invisible) area drawn in the background, more previously drawn areas cached, drawing updates while moving in stead of when the movement is stopped, and a general feeling of multiple cores being used to do different things at the same time.

If those limitations are done on purpose, for example to minimize cpu usage, perhaps a performance versus power saving option/toggle can be considered?

### Describe alternatives you've considered

I've waited to open this issue for years, figuring hardware would get better or it would bother a developer at some point. Now I'm curious to learn why it is not an issue or why proves to be difficult.

**Comment by mikehgentry** [comment]
I don't think you have OpenGL enabled? Try that - it's in the development plugin.

It has definitely made things better, but it's relatively new so will presumably still be optimised further.

**Comment by chereskata** [comment]
Is opengl available on ios?

**Comment by benoitsauvard** [comment]
Hello, is the opengl improved rendering for you @Redsandro ?
I use Osmand on a Samsung active tab2 with same rendering issue but I have an error message when using opengl
![Screenshot_20220913-111049_OsmAnd+](https://user-images.githubusercontent.com/94927596/189881258-0a5c1144-1c50-4158-ac37-efe203fb5111.jpg)

**Comment by mikehgentry** [comment]
@chereskata I don't think so, the iOS version had 2.5 D for a while before Android, so I assume it's a completely different rendering system?

@benoitsauvard Might be #14962 ?

**Comment by benoitsauvard** [comment]
@mikehgentry Thank you! Offroad map was my default profil and it was the problem. And now I'm also able to use the 2.5d. It run a little faster (not smooth as google map...).
Thanks again

**Comment by Redsandro** [comment]
> Hello, is the opengl improved rendering for you @Redsandro ?

@benoitsauvard @mikehgentry kind of. I found the option and it was disabled. I enabled it, restarted the phone (to be sure) and perceived considerable improvement in point 5:

> 5. It takes a couple of seconds for the final drawing to 'finalize'

It now takes about a second in stead of a couple of seconds to draw missing parts of the map. This is still quite a long shot from Organic Maps where there is no visible procedural drawing at all. And I don't see any improvements for points 1 through 4.

My hypothesis would be that this is OsmAnd's [dialectics of lead](https://en.wikipedia.org/wiki/Law_of_the_handicap_of_a_head_start) and the render engine relies on legacy code where vectors are drawn to tiles and tiles are drawn to screen in single threaded fashion, where in Organic Maps the vectors are drawn directly to screen.

**Comment by vshcherb** [comment]
> I don't think you have OpenGL enabled? Try that - it's in the development plugin.

This is the answer to original request. In last build you could see FPS, on our test devices OpenGL reaches 120 FPS, so it should be enough.

The only valid request left is (4) we have actually separate issue for that.

**Comment by Redsandro** [comment]
I didn't understand why I wasn't seeing the improvements you claim @vshcherb, until I saw the F-Droid version is at 4.2.6 and the Google Play version is at 4.2.7. The latter is an order of magnitude better indeed.

That said, point 2 and 3 are still relevant. The grey areas, flashes and grids that show while the map movement eases out after a swipe are uniquely OsmAnd and have an inhibited feel. Just a hint. I won't open a new issue.

**Comment by Redsandro** [comment]
For the record, the difference in render speed, snappiness, tile caching etc is still considerable compared with Organic Maps with the OpenGL rendering enabled. 120 FPS scroll speed is one metric but not very helpful when tiles aren't cached, showing an empty grid after every move, slow to render (not draw) etc. I think these are legit issues. There appears to be room for improvement. This is on a Xiaomi Mi 9T Pro. If I've tried an unlucky set of devices and it really works beautifully for others, I'm curious to see a recording of that, and we'll know it's a hardware issue.
