### ISSUE TITLE
A/V notes "Take a Photo":  Retry/OK buttons need more contrast against image

### ISSUE THREAD

**Issue by martenjj** [osmandapp/OsmAnd#15266]
### Description

On the photo confirmation screen, the "Retry" and "OK" buttons are overlaid on the image in white text.  Taking a photo with a lot of white where they woulkd appear makes them very difficult to see.  See screen shot - the top part of the photo is pixellated so as to hide my exact location, but the button area is as displayed.

![Screenshot_20220910-142325_Camera](https://user-images.githubusercontent.com/10631760/189483664-c52e71ba-8234-4ed8-8d3a-1864a75859c5.png)

Suggest that the buttons could be shown with the standard blue background block.

### Your Environment
OsmAnd Version:  2.4.7
Android/iOS version:  12
Device model:  Samsung Galaxy S10

**Comment by vshcherb** [comment]
I think it's system dependent UI
