### ISSUE TITLE
Adapt time-related live-update-related strings to factual type of time indication (times are absolute, but phrasing is relative)

### ISSUE THREAD

**Issue by OsmMUC** [osmandapp/OsmAnd#15279]
# 🚀 feature request

### Description

In OsmAnd+ 4.2.7, time-related phrasing in live-update-related strings is geared towards relative time indications ("a.b. _in_ xz" hours from now). However, it seems the time actually given is in absolute terms, i.e. "_on_ a.b. _at_ xz".

### Describe the solution you'd like

Assuming that going forward, times given will remain in absolute terms, adapt the strings to reflect that. Proposal as per diff file attached.

Notes: 
- The diff also includes one typo correction "dayly" -> "daily", and some other proposals for (arguably) more polished wording (e.g. reflect more that it is not a map update that is being checked, but the _availability_ of a map update that is being checked for).
- The diff only covers languages I am sufficiently familiar with to make concrete proposals. Other languages likely might need to be updated analogously. 
### Describe alternatives you've considered

Code could be updated so that times given are actually relative (to match the current strings). But that seems to be more coding effort than just updating some strings. And at least to me, times given in absolute terms are more useful than in relative terms. (For hourly updates, one could argue that maybe relative time indications might be better, as the next update is likely to be very "near". However, not sure whether it makes sense to spend the effort for such a differentiation.)

[live-update-related-string-updated.diff.txt](https://github.com/osmandapp/OsmAnd/files/9547036/live-update-related-string-updated.diff.txt)

**Comment by vshcherb** [comment]
Please edit in the file and create PR (https://github.com/osmandapp/OsmAnd/find/master -> Edit -> PR), so we could have inline conversation and it will be easier to merge.
