### ISSUE TITLE
Make Nominatim search feature independent from Online Maps Plugin

### ISSUE THREAD

**Issue by stephan75** [osmandapp/Osmand#1527]
See https://groups.google.com/d/topic/osmand/OAYGWTqUo6E/discussion

The question about the "missing" Nominatim search has come up often in the past weeks/month.

So please make that feature available at any time.

**Comment by vshcherb** [comment]
It is now documented here http://osmand.net/features?id=online-maps-plugin. And it belongs to online features we don't want to confuse people with mixture of Online and Offline capabilities in same place
