### ISSUE TITLE
Split Bourgogne-Franche-Comté

### ISSUE THREAD

**Issue by le-jun** [osmandapp/OsmAnd#15288]
I’m wondering how the proposed areas to be downloaded are defined. The french Grand-Est region is subdivided into departements whereas Bourgogne-Franche-Comté must be downloaded entirely. Is there a reason for that?

My device is quite old and lacks space so I tend to download only the area I know I may go to, and I fear that in the near future I won’t be able to make updates anymore.

**Comment by MarioSwitch** [comment]
It's related to file sizes. I've noticed that a file sizing 1 GB or more can't be downloaded entirely, and you must download all regions. So, I think, is the same thing: if the region is sizing more than a defined size, separated maps will be proposed.

**Comment by vshcherb** [comment]
Yes, we try to split regions once their subregions have reasonable size of 100-150 MB. Probably we can split this one too.
