### ISSUE TITLE
Weblate translation is locked

### ISSUE THREAD

**Issue by tbertels** [osmandapp/OsmAnd#15280]
> Auto-merging OsmAnd/res/values-de/strings.xml
CONFLICT (content): Merge conflict in OsmAnd/res/values-de/strings.xml
Automatic merge failed; fix conflicts and then commit the result.
 (1)

See https://hosted.weblate.org/projects/osmand/phrases/

It seems linked to this commit: https://github.com/osmandapp/OsmAnd/commit/48cdaf13cac19572387258fb965260bd8d8c4580

**Comment by franco999** [comment]
Locked again.

**Comment by tbertels** [comment]
New error message:

> To github.com:/osmandapp/Osmand.git
 ! [rejected]              master -> master (fetch first)
error: failed to push some refs to 'github.com:/osmandapp/Osmand.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
 (1)
