### ISSUE TITLE
'Analyze on map' graph mismatches track

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#15284]
This may have the same root cause as #15022:

Take the track posted in #15087 and go to the "Analyze on map" mode: The track has a 19 minute (~2km) recording gap beginning at timestamp 2022-08-13T16:20:06Z (roughly at 4.5 km). On the map, the gap is between the Stop/Start icons in the middle of the track near the y-junction (although there is a line between them but that reflects the return trip).

When you swipe your finger on the "Analyze in map" graph to trace the track, as your finger traverses the gap the blue dot on the map correctly disappears at the Stop icon, but once your finger crossed the gap on the graph, the dot on the map does not reappear at the Start icon, but much later (actually at the turning point of the track). So there is some mismatch here between track data and graph data.

When you do the same experiment using the  the "Track" graph, the jump on the map is reflected correctly, i.e. the issue is limited to our "Analyze on map" graph. (Did not use "Join segments" so that the Stop/Start icons framing the gap remain visible on the map. But hence the gap near 4.5km  is not visible on the graph.)

![Untitled_1](https://user-images.githubusercontent.com/845735/189712976-c5e78b83-cdfe-45c2-aa83-d1fa6a56c04e.jpg)   ![Untitled_2](https://user-images.githubusercontent.com/845735/189712979-e8b9fe11-dbdb-45b8-894c-6403051c8bbf.jpg)

**Comment by sonora** [comment]
Perhaps related: #14700.

**Comment by sonora** [comment]
Upon re-visiting this to debug: Could anybody reproduce this? I currently cannot.

The puzzle to solve here is how did I get to screenshot 1, where in the 'Analyze on map' view I did not select 'Join segments' (as explicitly mentioned, and the surplus Stop/Start icons framing the gap prove this), but **still you can see a gap in the Distance graph**, ending at 5.62km.

When revisiting this now with the same settings, that gap is not visible in the plot (as it should be: Without 'Join segments' the different segments are placed in the plot next to each other gaplessly at 4.28km,  and swiping your finger across the graph produces the expected result.

So it seems somehow the data got misrepresemted but unless we can reproduce systematically we cannot debug.

**Comment by Zirochkabila** [comment]
4.2.7 and OsmAnd~ 4.3.0#13799mqta, released: 2022-09-20 - **reproduced**
[2022-08-13_11-20_Sat.gpx.zip](https://github.com/osmandapp/OsmAnd/files/9607843/2022-08-13_11-20_Sat.gpx.zip)

**Comment by vshcherb** [comment]
@Zirochkabila is it related to https://github.com/osmandapp/OsmAnd/issues/15022 ?

**Comment by Zirochkabila** [comment]
@vshcherb yes it's related
