### ISSUE TITLE
Display Route type in route section dialog

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#15281]
Here's a feature request regarding our new "_Tap routes on the map_" feature: If on the map you tap on e.g. a OSMC hiking symbol, and there are several routes in the vicinity, we display a selection dialog offering all routes traversing in the area, which is great.

It appears that regardless of whether the current app profile has selected hiking, bicycle, or both types of route as visible, in this selection dialog we always offer both types of routes, which is also a cool feature.

But would it be possible to denote the type of route (e.g. "Route: Hiking" or "Route: Bicycle") already immediately in the selection dialog, in the place where now we only show "Route", so that you do not have to tap on each one and go to its details to find out?

![Screenshot_20220912-142532_OsmAnd~_](https://user-images.githubusercontent.com/845735/189653937-085910d7-d65e-4ed3-bef1-7d34d9968231.jpg)

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/16661
