### ISSUE TITLE
Wrong values on CEE red 63A - someone have set it to a non existing 64A value

### ISSUE THREAD

**Issue by sgjf4g4** [osmandapp/OsmAnd#15287]
### Description
This is a funny issue. It makes sense to me that software developer did this error because 64 is part of the 2^ series. But there is no 64A CEE connector. The correct values are 16,32,63 and 125. You can read more about this (or just ctrl+f for '64' and then for '63') here https://en.wikipedia.org/wiki/IEC_60309#Common_plugs

### How to reproduce?

https://github.com/osmandapp/OsmAnd/search?q=poi_socket_cee_red_64a

### Your Environment
OsmAnd Version: all recent
Android/iOS version: any
Device model: any

**Maps used (online or offline):**   
no relation

How to fix: Just change all the numbers (and the translations) from 64 to 63 so that the github link above dont have any result any more.

**Comment by sgjf4g4** [comment]
Could you please backport the fix into the current 4.2 releases? Its not a new feature or anything like that.

**Comment by vshcherb** [comment]
it's not possible cause 4.2 releases are out, 4.3 should be coming this/next month.

**Comment by sonora** [comment]
I've taken the liberty to fix this in (I hope) all our appropriate repositories:
- Phrases: https://github.com/osmandapp/OsmAnd/commit/443d6d9013bf3376a616e27345a4ace2aaa7541a
- Phrases: https://github.com/osmandapp/OsmAnd-resources/commit/c9dcba7030c2913564286ab941cceac9965962dd
- rendering-types: https://github.com/osmandapp/OsmAnd-resources/commit/14fc75376521290651174409980bdfa2879274b7
- obf-creation: https://github.com/osmandapp/OsmAnd-resources/commit/bbc8e29d6b2d0dee6ded67f7614507e79be9149f

Curiously: While https://wiki.openstreetmap.org/wiki/Proposed_features/Charging_station contains this correctly, there is spurious documentation out there which actually gets this wrong, e.g. https://wiki.openstreetmap.org/wiki/FR:Tag:amenity%3Dcharging_station  ;)

**Comment by sgjf4g4** [comment]
"there is spurious documentation out there which actually gets this wrong, e.g. https://wiki.openstreetmap.org/wiki/FR:Tag:amenity%3Dcharging_station"

Thanks for reporting this. Its fixed now.
