### ISSUE TITLE
Regression: Browse Map - Map rotation is always changed

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#15283]
Setup North up - no map rotation in Browse map.

After couple navigation and simulations with different profiles, Browse Map Map rotation is affected it doesn't points map top to the north any more.

**Comment by sonora** [comment]
Yes, seems like there is at least one place where we do not update to the correct profile setting after a profile change (which is recently induced by nearly every start/dismissal of a route calculation).

**Comment by sonora** [comment]
@Dima-1 While investigating this one, #15308 may have a related root cause.
