### ISSUE TITLE
OSMAnd shows a Speed Bump Ahead warning instead of a Crosswalk

### ISSUE THREAD

**Issue by kevinp2** [osmandapp/OsmAnd#15296]

**Comment by kevinp2** [comment]
![C28B4AEE-59D2-40A7-B976-93033A818D6E](https://user-images.githubusercontent.com/609677/189984049-d94a3850-a398-4abe-b1bf-af1186322821.jpeg)

I added the crosswalk to OSM just a day ago:

https://www.openstreetmap.org/node/10019230345

This is OSMAnd 4.2.4 on iOS

**Comment by Zirochkabila** [comment]
**Reproduced** 
And with the use of live updates also managed to reproduce
**map** https://drive.google.com/drive/folders/15D6aZIUVMfO40P4SMp0gkEy6vaR6BWvc?usp=sharing

https://user-images.githubusercontent.com/104760013/190188836-dae5dba2-e9b0-473e-8c8a-949ddc4950f6.mp4

**Comment by kevinp2** [comment]
Interestingly, the OSMAnd map correctly shows a crosswalk icon.  It is the route warning that shows a speed bump.

**Comment by danieldegroot2** [comment]
This issue is likely being caused by (a non-standard value of) the `traffic_calming` key being used (here: `traffic_calming=no`).
The warning module should ignore these values (or at least `yes`/`no`).

**Comment by TS-R** [comment]
I can reproduce this issue with version 4.7.9, too.

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.8.0#2153m, released: 2024-04-222024-04-23 
- Osmand warns about pedestrian crosswalk and then about speed bump, but on the map only crosswalk is mapped.
- On the screen there is a warning about Speed Bump Ahead. 
https://www.openstreetmap.org/node/10019230345 is tagged with traffic_calming=no. According to [taginfo](https://taginfo.openstreetmap.org/tags/traffic_calming=no#overview) there are about 4000 objects with this tag.

https://github.com/osmandapp/OsmAnd/assets/116079541/2b222c47-4abb-4e0a-b507-0ca4250ee637

**Comment by vshcherb** [comment]
Wrong tag interpretation ``` traffic_calming=no```

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-resources/commit/34e9e6684547667e94bce90ed1f78f97b7199f3f

**Comment by dmpr0** [comment]
<table style="width:100%">
  <tr>
    <th>Android</th>
    <th>iOS</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/c6546510-984c-4a57-a6f7-33a551757ce0"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/93d7b358-aeba-4623-b450-ff1fcd8259b4"  width="300" height="auto"/> </td>
  </tr>
</table>   

Tested here https://www.openstreetmap.org/node/10049132027

**Comment by ivanPyrohivskyi** [comment]
Will be available in new August 2024 maps
