### ISSUE TITLE
track has additional point at north pole

### ISSUE THREAD

**Issue by FransM** [osmandapp/OsmAnd#15303]
### Description
I created a track with osmand and wanted to follow that. The track looks ok when editing, but when going to navigation mode there seems to be a point after my last point that brings me to the north pole or so.

Screen shot from track editor:
![Screenshot_20220914-162618](https://user-images.githubusercontent.com/1893299/190183264-e498b6f1-2fe9-47c9-9a12-7dc2fbc7f8f3.png)

Screenshot from navigation
![Screenshot_20220914-162719](https://user-images.githubusercontent.com/1893299/190183279-05d9fca5-385a-4386-9fb3-b3f799f89fa7.png)

What probably happened is that I created the track but by accident added an additional point after my final destination.
I undid that addition and saved the file.
It seems the track editor opens the file quite nicely. However navigation seems to read an additional point (or reads beyond end of file)

### How to reproduce?

Open the attached gpx file and go to navigation
[Wed 31 Aug 2022.gpx.gz](https://github.com/osmandapp/OsmAnd/files/9567315/Wed.31.Aug.2022.gpx.gz)

### Your Environment
OsmAnd Version: 4.2.7 (from play store)
Android/iOS version: 11
Device model: Moto G pro

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by vshcherb** [comment]
The issue that track is broken it has only 1894 trkpt points but segments expect to have 2196 points (so 302 points are lost) due to unknown operation. Obviously it shouldn't be broken and display north pole but it will have other features broken.

Please specify how did you create it so we can reproduce and fix it.

**Comment by FransM** [comment]
I created the route using osmand, plan route, I added points but by accident I added more points after place where I wanted to finish. I suspect I saved before I noticed that I added some rogue points at the end of my trip. and I deleted them using the back arrow. as I was fumbling a bit on my phone it may well be that I did this a few times. It might also be that I deleted some points by going to the points menu and

I suspect that when undoing things the # of points in the segment has not been decreased properly at some point in time.
I just tried to reproduce the issue, but unti now without success.

**Comment by FransM** [comment]
I've been thinking about this issue and would like to suggest the following changes:

Apparently the track editor and navigation use different code to read or process the track points. Maybe this should be factored out.

And if the root case of the faulty track cannot be identified, I would suggest adding some defensive code when opening a gpx file to check if the number of points is what is expected and if not issue an error or warning and perhaps ask the user if the usable part of the file should be used (and saved if desired).

ALso I have been peeking into the gpx file. I do not understand the comment that a gpx segment consists of 2196 points. I could not find this number in the gpx file and also not in the Osmand source code, or in the information that I have on the gpx file format.

And I have been examining the file in gpx.studio: https://gpx.studio/
That gave me the following image. The odd thing is that the whole route seems to be there twice (maybe this is the recorded route versus the planned route)
![image](https://user-images.githubusercontent.com/1893299/190895572-8e970969-9a2f-4418-8fb9-22504b57cf56.png)
We did cycle the route once and if I look in gpx studio I see an oddity at about 49 km. I get to the point at the bottom just a bit of the airport symbol and then it seems I loose the track only to reappear around 53.9 km near start/finish.
