### ISSUE TITLE
[Feature Request] Elevation Graph: use slope to color graph

### ISSUE THREAD

**Issue by rubenvandeven** [osmandapp/OsmAnd#15300]
# 🚀 feature request

### Description

The current graphs in the Elevation Profile Widget and Routing details can show two lines: elevation profile and slope. Some GPX tools (e.g. [1](https://tsportsride.in/wahoo-provides-new-gradient-coloring-with-wahoo-summit-characteristic/) [2](https://i.imgur.com/2irTYO6.png) [3](https://forums.garmin.com/sports-fitness/cycling/f/edge-1030/192167/where-does-climbpro-get-it-s-gradients-from) ) use the slope to shade the elevation profile. Making it a single graph might be easier to read, in particular when on the move.

### Describe the solution you'd like

OsmAnd already has a shaded routing line. It would be great if the same color scheme can be used to shade the graph. This would then also incorporate the current discussions on how the scheme should be defined, such as #12954 and #11975.

I had a quick look at the code and from what I understand the MPAndroidChart library is used to draw the graph. In their issue tracker a similar [question is raised](https://github.com/PhilJay/MPAndroidChart/issues/3977), but seemingly remains unanswered, so to me it is unclear if the library is capable of doing so.

The issue there suggests a custom gradient can be used like so

```java
dataSet.fillDrawable = ContextCompat.getDrawable(context, R.drawable.gradient)
dataSet.setDrawFilled(true)
```

However, not being an experienced Android dev, it is unclear to me if `R.drawable.gradient` is something that could be calculated on the fly (i.e. using the slope data).

### Describe alternatives you've considered

Keep things as they are. Thanks for all the great work!

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/12954. 
Yes it can be calculated on the fly it's not difficult thing to do, we still need to implement UI for that feature.
