### ISSUE TITLE
Small scale areas are mis-rendered, nodes seem to be dropped, resulting in overlapping or not touching areas which share the same edge, and weird ways and buildings.

### ISSUE THREAD

**Issue by dreirund** [osmandapp/OsmAnd#15317]
### Description

Small scale areas render wrongly in OsmAnd. It seems like random nodes are dropped, resulting in weird looking shapes, sometimes completely wrong, or gaps between or overlaps of areas which share the exactly same edge.

The following OsmAnd screenshots are from [&rarr;&hairsp;this area](https://www.openstreetmap.org/#map=19/51.10295/13.76972).

Here, the correct osm.org rendering:

![OSM-Webrendering](https://user-images.githubusercontent.com/1590519/190400397-373fa514-5ea3-4afe-9b1f-9860e0e11dde.png "OSM-Webrendering")

Here, from OsmAnd, a screenshot showing a deformed building and highway areas, which share the same edge, rendered as overlapping or with a gap:

![deformed building and miss-aligned highway areas](https://user-images.githubusercontent.com/1590519/190398691-801ddca6-cb54-4b15-8a48-a8b6f9e9eacd.jpg "deformed building and miss-aligned highway areas")

Here, from OsmAnd, a screenshot showing some path's which leads to a street cabinet rendered wrongly:

![misreandered way](https://user-images.githubusercontent.com/1590519/190398720-8d9cb03f-9c38-4d43-bf38-0933418d92d1.jpg "misreandered way")

### How to reproduce?

Use the offline map as described below and go to 51.10295°N, 13.76972°E and zoom in

### Your Environment
* OsmAnd Version: [OsmAnd~ 4.2.7 (4207) (f-droid)](https://f-droid.org/repo/net.osmand.plus_4207.apk)
* Android/iOS version: Android 11 ([cdDroid](https://crdroid.net/) "[crDroidAndroid-11.0-20210522-markw-v7.6](https://github.com/ShihabZzz/Releases/releases/tag/135.0)")
* Device model: [markw](https://github.com/SonicBSV/android_device_xiaomi_markw)

#### Maps used (online or offline):

* Offline vector maps
* Map: Europe &rarr; Germany &rarr; Saxony
  - Map from 2022-09-01
* Map style: Topo (but also appears in other styles)
  - No option in the map "Details" settings selected (also not "Fewer details", so I expect the highest rendering detail takes place)
  - No option in the map "Hide" settings selected  
  ![map settings](https://user-images.githubusercontent.com/1590519/190398768-8e0cec03-c6be-42a1-9824-a6ae86451a9a.jpg "map settings")

**Comment by vshcherb** [comment]
Duplicate https://github.com/osmandapp/OsmAnd/issues/9821
