### ISSUE TITLE
Feature request: prevent screen control from switching the display off during screen interactions

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#15313]
If the screen gets activated by screen control, for example due to navigation instructions, the user is able to interact with the map and with menus. With the current behavior the screen will suddenly switch off again, even if the user is interacting with the map by panning or typing something into the search function. Any user interaction should stop or better reset the screen timeout so that the screen stays on while the user is performing actions.

**Comment by mariush444** [comment]
--- up ---

I use screen control as:
Use system screen timeout - off
Timeout after wake-up - 45sek
Proximity sensor - on
Navigation instructions - on

When the screen is wake-up and I wanto to verify something on the screen (map) then screen is off during my action.

In my opinion Timeout (45sek) should be **after last touch** and not after wake-up

```
The same behavior should be with the option
Map during navigation -> Auto-center map view.

auto-center should be activated after the last touch.
```

**Comment by vshcherb** [comment]
- and not after wake-up

Makes sense. I think it's only possible to implement for user defined interval which doesn't work everywhere (not for system timeout)

https://github.com/osmandapp/Osmand/blob/dc79e5e12c1ccba384fbb84619c2f403fc24175a/OsmAnd/src/net/osmand/plus/helpers/LockHelper.java#L165

So if it's easy to implement to add just timestamp and run timedUnlock(long millis) {}  again to reschedule event, so probably we should do it quickly.

**Comment by Zirochkabila** [comment]
# Testing 1
`OsmAnd~ 5.0.0#3947m, Released: 2024-12-17` - Fixed
