### ISSUE TITLE
Crash when assigning a name to a recorded track (if the name is already in the track list)

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#15314]
### Description
Crash when I try to save track with the name that already exists in the list.
https://user-images.githubusercontent.com/80623554/190352005-745ba964-54c1-4820-8310-de0e5c7072ae.mp4

### How to reproduce?
1. Record a track
2. Click finish track and when will display the name of the track change it to another one (assign the name that is already exist in the track list) and click Save. You will receive a message "A file with this name already exists "->Click Save.
3. Crash
[exception (42).log](https://github.com/osmandapp/OsmAnd/files/9573236/exception.42.log)

### Your Environment
OsmAnd Version: OsmAnd 4.2.7
Android/iOS version: Android 9
Device model: SoneExperience XZ1

**Maps used (online or offline):**   offline
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by Zirochkabila** [comment]
**Reproduced** 4.2.7
From the third time
[log & video.zip](https://github.com/osmandapp/OsmAnd/files/9582238/log.video.zip)

**Comment by sonora** [comment]
Ah, interesting, yes, I can reproduce it now: This happens only if you have an ongoing navigation. If you try things without a navigation going on in parallel, OsmAnd handles this without crashing in the manner I outlined.

**Comment by anastasiia936** [comment]
From the user request. The user had a long track recorded, around 50-100 miles and when he assign the name that is already exist the track was not save at all. It seems like an app clear the recorded track instead of save it.
User had an issue on the Samsung Galaxy Z Flip 4.Osmand+ version 4.2.7.

**Comment by sonora** [comment]
Yes, please advise the user they should look for the track under the default name, I cannot reproduce how that track would be lost.
