### ISSUE TITLE
Deleted languages reappear after restart of app

### ISSUE THREAD

**Issue by google85** [osmandapp/OsmAnd#15323]
### Description
After deleting any / all vocal indications (TTS) languages and restarting the OsmAnd app, they are automatically redownloaded and marked as active in the app.

### How to reproduce?
All downloads->Others->Vocal indications (TTS) , click on Chinese -> ... menu -> Delete -> Yes
Repeat with other non interesting languages
After closing and reopening app they are automatically redownloaded and marked as active.

### Your Environment
OsmAnd Version:
Android version: 10
Device model: Samsung Galaxy S9 (SM-G960F)

**Maps used (online or offline):**   
Not applicable

**Comment by vshcherb** [comment]
Duplicate https://github.com/osmandapp/OsmAnd/issues/5994
