### ISSUE TITLE
Osmand+ vocal guide through BT stops working

### ISSUE THREAD

**Issue by macro182** [osmandapp/OsmAnd#15327]
### Description
Every time I use vocal guide through bluetooth, the vocal guide stops working after a while. Tipically, when I pause the navigation and then restart it. This happens with all the 3 different audio outputs, but it seems not to happen if the navigation is simulated.
Tried different BT headset, it happens with all of them. In the meanting other apps like Spotify or CamSam keep working. The issue happens even if I don't use other apps connected through BT.

### How to reproduce?
- start a real navigation from point A to point B with a car/motorcycle profile and connect a BT headset to listen to vocal prompts;
- let Osmand guide you through some turns;
- pause navigation;
- restart navigation (if the issue does not happen, try other times the last 2 steps and/or let Osmand navigates some further corner).

### Your Environment
OsmAnd Version: Osmand+ 4.2.7
Android/iOS version: 9
Device model: Huawei P20 light

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
Offline maps, Italy and near countries (all the updates in the last months, maybe years).

**Comment by vshcherb** [comment]
Probably you need to allow OsmAnd work in background - https://dontkillmyapp.com/huawei

**Comment by macro182** [comment]
You made my day...it seems working!

Ciao! 



19 set 2022, 16:06 da ***@***.***:
