### ISSUE TITLE
[OpenGL] Zoom bug

### ISSUE THREAD

**Issue by franco999** [osmandapp/OsmAnd#15328]
### Description
When marking a POI or any location, being on the map and zooming in with the buttons, it moves randomly to any part until it breaks and stops zooming in the desired location. To clarify that zooming without being marked a POI and in the version without OpenGL, works perfectly. It only happens to me in the previous case.

I've been observing this problem for several nightly versions, but I was hoping that someone else had this problem to publish this issue, but as far as I see no one else has this problem.

<details>
<summary>Video</summary>

https://user-images.githubusercontent.com/12088580/190854509-2a7699a2-4310-4c9c-ab37-260d167ef911.mp4

</details>

### How to reproduce?
1. Enable OpenGL.
2. While on the map, mark a POI or location.
3. Zoom in/out with the buttons on the app.

### Your Environment
**OsmAnd Version:** OsmAnd~ 4.3.0#13787mqta, (2022-09-15). I don't remember well, but I've been watching him for at least 2 weeks.
**Android/iOS version:** ArrowOS 12.1 (Android 12.1)
**Device model:** Xiaomi Mi A2 Lite (daisy)

**Maps used (online or offline):**   

This problem was observed in both offline and online maps. In offline maps I used Argentina and the general world map.

**Comment by vshcherb** [comment]
With latest night build can't reproduce it. Probably it was fixed today?

**Comment by franco999** [comment]
I have tried version "OsmAnd~ 4.3.0#13793mqta, (2022-09-18)" and it seems to have been corrected. Thanks.
