### ISSUE TITLE
Transport stops is not disable in the Boat profile

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#15322]
### Review
- [x] "Transport" & " Transport stops" should not be hidden. They available in all Maps / Styles. 
- [x] Routes should be hidden if Map is not Vector and Style doesn't support these features

### Description
If you once enable the Public transport stops layer, you cannot disable it
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/80623554/190644387-bb32cd74-eb61-4510-844d-159a704bc517.png"  width="300" height="auto"/> </th>
  </tr>
</table>  
### How to reproduce?
1. Select Boat profile.
2. Enable Public transport
3. Disable it and the stops will be still display on the map

### Your Environment
OsmAnd Version: 4.2.7
Android/iOS version: Android 9
Device model: Sony Experience XZ!

**Maps used (online or offline):**   offline
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by nazar-kutz** [comment]
**Pull Requests**
* https://github.com/osmandapp/OsmAnd/pull/15427
* https://github.com/osmandapp/OsmAnd/pull/15472
