### ISSUE TITLE
OSMAnd is not drawing downhill ski routes even in Ski profile

### ISSUE THREAD

**Issue by kevinp2** [osmandapp/OsmAnd#15336]
### Description
At the Powder Mountain, Utah ski resort, many ski runs are marked in OSM as **piste:type=downhill** which I believe is the correct tag.

These routes do not appear in the OSMAnd map, even when Ski profile is selected.  Ski lifts are correctly drawn, but no ski runs.

### How to reproduce?

OSM Map:  See the route named **Ojeebus** and the ski lift named **Sunrise**:

https://www.openstreetmap.org/way/771502671#map=18/41.36955/-111.75165

https://www.openstreetmap.org/edit#map=18/41.36989/-111.75209

<img width="777" alt="image" src="https://user-images.githubusercontent.com/609677/190945659-a3d4a3d2-8ed3-4b1d-8d0a-e2258cf12035.png">

Both ski run and ski lift are correctly drawn in the site OpenSnowMap:

https://www.opensnowmap.org/#map=17/-111.752/41.37&b=snowmap&m=false&h=false

<img width="608" alt="image" src="https://user-images.githubusercontent.com/609677/190945763-8ae0f128-0acc-4576-af51-6ba7318f24ba.png">

But OSMAnd shows only the ski lift Sunrise:

![image](https://user-images.githubusercontent.com/609677/190945886-04b93d75-ea8d-412a-b046-68d8f92a1ca4.png)

### Your Environment
OsmAnd Version: 4.2.4
Android/iOS version: iOS 15.6.1
Device model: iPhone XR

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

I have an hourly update for the US > Utah map.

**Comment by xmd5a2** [comment]
It is not skimap rendering style on your screenshot but default style. Please select it from "Configure map" menu
![Screenshot_2022-09-19_16-58-26](https://user-images.githubusercontent.com/5829014/191035014-8c02c3f8-ee58-439c-9097-908f8b861518.png)

**Comment by kevinp2** [comment]
Which map style should I use?  I tried all of the styles below and none of them showed the ski runs:



Kevin

**Comment by sonora** [comment]
Go to (Menu Button) / Plugins, and enable the "Ski map view" plugin. After that you will find a new app profile for selection, with a little skier-icon. When you select that, it should automatically select Map style "Winter and ski".

It somehow looks like you may not have the Plugin activated, hence that Map style is not offered on your screenshot?

**Comment by kevinp2** [comment]
> Go to (Menu Button) / Plugins, and enable the "Ski map view" plugin. After that you will find a new app profile for selection, with a little skier-icon. When you select that, it should automatically select Map style "Winter and ski".
> 
> It somehow looks like you may not have the Plugin activated, hence that Map style is not offered on your screenshot?

That solved it, thank you!  I did not know about or have the Ski Map View plugin.  After I installed it, I was able to select the **Winter and ski** style.
