### ISSUE TITLE
add seccond route calculation to route calculation menu ( propose) - faststest and shortest

### ISSUE THREAD

**Issue by razor74** [osmandapp/Osmand#1533]
Hello. 
Why not add a button where user can activate a seccond route calculation after osmand calculate the default route ( with what is set from navigation menu). Practically if i set for fastest route calculation, and osmand calculate the route, i want to have a option directly from navigation screen to calculate the shortest route ( optional - if i want). So, in this case the user will have at hand both option for route calculation and everyone will be pleased to choose one of them, without need to go into settings, navigation menu to change the type of route calculation. Practically you can somehow move the option from navigation menu to navigation screen. (like here maps or other navigation software).
In this case , no need to calculate both routes. Only one, and user can choose if he want to calculate the seccond with other algorithm.

**Comment by sonora** [comment]
Merge to #1294.
