### ISSUE TITLE
after update all favourites deleted 

### ISSUE THREAD

**Issue by lakik** [osmandapp/OsmAnd#15333]
Hi 
after I have updated my osmand installation on my android samsung all my favourites were deleted. 
The only files I found was favourites_bak... 20 pieces. But I have not figured out how to restore those. 
Or is there any other way to restore my favourites?
Would be great if someone could help me wth that.
Thanks
L

**Comment by sonora** [comment]
Each is simply a normal GPX file, each containing (as waypoints) the snapshot of your favorites at that time.
- They are compressed, so use any zip utility to extract the GPX file contained, which can then simply be imported by OsmAnd.
- I am not currently sure if OsmAnd can directly import from the bz2 format, but probably.

Out of curiosity: Did you lose the favorites by accidentally deleting or uninstalling, or are you saying there is an issue with the app update?

**Comment by lakik** [comment]
Thank you for your answer.
unfortunately it is not working. or the files are empty. 
it was an issue after updating i did not deleted anything. After opening the updated version they were gone. 
That is really bad. 
If you have another idea let me know. 
Thank you!

**Comment by sonora** [comment]
- What file size are your _favourites_bak_XX.gpx.bz2_ files?
- And what creation dates do they have? You need to look for one dated when you know you had favorites.
- In what file path do you find the _favourites_bak_XX.gpx.bz2_? 
- Have you tried copying them to a PC and unzipping there, e.g. with 7-Zip?
- Please provide the version of your OsmAnd app, it would also be interesting what your previous version was, or at least how long ago the previous update was.

**Comment by lakik** [comment]
42kb it seems that they were created while updating. But maybe after the first opening of the new version. 
the path is 'data/net.osmand.plus/files/backup'
Yes i tried it with 7-zip but nothing inside 
the new is 4.2.6 the old one was 3.7.2

**Comment by lakik** [comment]
update 
I tried to open the extracted files online and there it works. But unfortunately it was just one list which I have added from my old backups after I havent found anything. So the backup just saved the added one. 
Any ideas?

**Comment by pebogufi** [comment]
In the directory backup should be the last 20 files with backed up favoutites. Check whether one of them has usable "good" data.

**Comment by lakik** [comment]
20 files and each of them contains the same data, which are not the most current. It is unfortunately only the list decribed above.

**Comment by sonora** [comment]
Exactly, try all favorite-backup files you find, they are from different times. And i f I remember correctly, older versions of OsmAnd may actually not have zipped the backup files, so there may also just be files with .bak or similar extension, which just require renaming to .gpx.

**Comment by lakik** [comment]
I searched in all the places and checked all the files I found nothing. The backup I have was not fresh enough. :(

**Comment by sonora** [comment]
That sounds strange... So you have
- Many old backups, supposedly from your 3.7.2 version, but need favorites you added later.
- When did you add these? Still under 3.7.2, in one go, and then immediately you updated to 4.2.6??

Have you tried checking your search history? If you added points from that screen, they may still be reflected under History?

**Comment by lakik** [comment]
The backup files in the folder backup were all from the same date and time (today around my update of the app). 
As I saw that all my favorites are gone I tried to import one of my old manually made backup files from some month ago. It worked.
As I found (after your description) the automated backup files I only found the imported list in all 20 files. 

I'm missing the points I saved ( all in version 3.7.2) between my last manually backup (few month ago) and the update of the app today.

It seems that the update procedere deleted or overwrites the favourites.gpx in the data folder including all the current points.

The history was a nice hint but most of the points I just save from the map.

**Comment by sonora** [comment]
That sounds like you may have done a lot of testing, and it eventually overwrote all 20 backup versions. :(

What Android version are you on? Android has changed their storage policies. Do you remember that when updating OsmAnd you received some dialogs about a mandatory data folder migration? If yes, it is possible that the older fav backups are still in another folder on your device or on your SD-Card. (Possible on the **external** SD card under _data/net.osmand.plus/files/_).

Other than that you may be out of luck. Though I still do not understand why all favorites would have disappeared, even though the update from 3.7.2 to 4.2.6 jumps several major version updates. But the mechanism that you have a copy of all your current favorites in a file call _favourites.gpx_ in OsmmAnd's data folder, and that file is synced to OsmAnd, has bee the same for 10 years. We may need someone from QA to find out what was perhaps going on here.

**Comment by lakik** [comment]
Unfortunately no dialog occured. 
It was as I said immediatly after the update the favorites are gone without any further action. 
The only thing I did was importing the old one after I did not found my points. The failure was not to look for the files before doing this or even make a backup of the favourites.gpx before updating. But I have not expected the loss due to an update :(

**Comment by tradavyvy** [comment]
As vshcherb added an observed label to this problem I take it this is not a one off occurrence.
Please put a high priority on solving this. For me, and manny others i presume it would be a big problem to loose all favourites. As they represent years of information gathering.
(Yes I do make regular backups outside osmand, but still ......)

**Comment by vshcherb** [comment]
Loosing favorites is really a big issue, we hope to provide UI to access to any internal file but it's not secure from Google point of view. So we need to build custom solutions, we probably build a menu to see local favorites backup so it's possible to restore what is in backup. If it's completely lost than it's also possible on some devices to retrieve from Google backups but it's not guaranteed.
 Unfortunately if there is no file, there would be no way to get it back.

**Comment by tradavyvy** [comment]
What about a automatic, once a week/day/month email of the favorites file to an email adress of choice?
Just to be extra sure.
I do that now manualy (but sometimes I am sloppy)

**Comment by vshcherb** [comment]
well we still didn't have time to implement autobackup to OsmAnd Cloud for us it will be a higher priority for now.

**Comment by vshcherb** [comment]
With development plugin you can now at least get these files i.e. export osf -> rename to zip file, unpack and you will have access to favorites backups

![image](https://user-images.githubusercontent.com/1042025/193399873-a2b6b340-8e70-44cf-93ef-cb83ade9afae.png)
![image](https://user-images.githubusercontent.com/1042025/193399877-f8375d38-9f15-4c84-bfcc-f24ca12e599b.png)

**Comment by daald-docker** [comment]
Same problem here, somewhat.
Yesterday, I updated osmand using F-Droid from ? (a very old version to 4.2.6.
First, I didn't see anything. I then first updated all the maps, but still the same. Then I realized, that the map focus has change to a location somewhere in the south of the southpole (where there is nothing). after moving back to the area of my maps, I saw everything again but no favourites. that was the moment when I googled this page. Then I went sleeping, not touching anything again.

Today, I connected my phone to the pc and realized 1. there are 20 good-looking backups.
but there is also the file Android/data/net.osmand.plus/files/favourites.gpx which also seems ok. Opened the application again and all favs were back here without any extra action from my side

So, maybe there is some conversion process in the background or whatever, but it needs some time for the favs to show up again. maybe (or for sure) this makes people nervous, and they do some kind of actions (instead of waiting) which are not really good for the data?

**Comment by sonora** [comment]
Just guessing, but I believe at some point many versions ago an internal database was introduced to go from the pure file-based favourites.gpx way of handling things to a quicker way using an additional internal database, which also supported to store meta data like time stamps or appearance. Chances are that the import of existing favorites (and perhaps also tracks) can take considerable time but happens unnoticed in the background...

**Comment by vshcherb** [comment]
@sonora other way around we now have 2 favorites.gpx (internal & external), and it's going to change slightly again as internal we will have multiple favorites.gpx per each group. Probably external as well but backups should be present as 1 file

**Comment by sonora** [comment]
@vshcherb I like the idea of having one gpx file per favorite group. Have always handled it like that for my personal data backups anyway, because it simply makes sense.

I think that in general we could think about treating favorites and tracks more alike: Keep those favorite-gpx files in the track folder, and in a backup offe4 to bundle **all** gpx files. In the UI, I am not convinced that in the long run we need two seperate screens, one to display gpx as favorites and one to display gpx as track, because it's actually the same thing. We maybe just need some tagging mechanism where you can mark certain gpx files you use often and then see them displayed for quicker access also in a special group at the top of one unified folder list.

**Comment by tradavyvy** [comment]
There is an issue about seperate gpx files for favourites #14514
