### ISSUE TITLE
Route is built without using roads

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15338]
### Description
The route is built without using roads
https://osmand.net/map?start=51.127957%2C1.324325&end=51.125472%2C1.319668&mode=car#16/51.1269/1.3234 **incorrect**
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=51.1279%2C1.3243%3B51.1255%2C1.3197#map=16/51.1262/1.3200 **correct**

https://drive.google.com/drive/folders/1I0rS2r7hmhxDuMH-eXzxn7rUuIWMEMi7?usp=sharing **map here**

### Steps to reproduce
Set point of departure `51.12794° N, 1.32458° E` > Set destination `51.12540° N, 1.32187° E`

### Actual result
Route is built without using roads

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/190981505-3fbdeb6d-3cc0-4917-ac4a-ec0c2342438a.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
Like in OSM

### Your Environment
OsmAnd Version: 4.2.7
Android/iOS version: Android 12
Device model: POCO X3 NFC

**Comment by Antheii** [comment]
Note the OSM version actually is also wrong: from the starting position, it first goes West to a footpath (but this might be incorrectly defined in OSM data though).

Official route to depart the castle grounds from this parking should be like the red line - so starting at the 'road' I'm already on
![afbeelding](https://user-images.githubusercontent.com/63048026/190992638-555d95bc-2aef-4d8b-b212-8573410c9619.png)

**Comment by Zirochkabila** [comment]
@Antheii The link in the commentary has been changed
Check it, please.

**Comment by Antheii** [comment]
@Zirochkabila - that seems correct now!

**Comment by vshcherb** [comment]
You need to set to use private road access. These roads are not accessible.

**Comment by Zirochkabila** [comment]
Even when using private roads, the actual result (photo) is different from that in OSM.
But, building a route without using private roads should show a notification about it, but never a straight line route.

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/190997747-d5f9fe2e-798e-4f4d-9ab8-9efe0178e24c.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
We need more information what barrier is not supported  and where.

**Comment by Antheii** [comment]
@vshcherb  - in the original proposed route, those were in sequence (at least physically, not sure which are classified as such in OSM data);

1. a small barrier, followed by a small decent of approx 2.5 meters
2. another car park, full with other cars
3. a rather large 3-story building, surrounded by a deep ditch on all sides
4. a grass field (OK, could have done that one!), followed by another steep decent of approx. 3 to 4 meter, though with a bit of luck, I might have used the stairs there.
5. crossing the road (Queen Elizabeth Road) which we officially should have followed.
6. up and down a wall of again 3 to 4 meter high
7. barely missing a World War 1 bunker
8. and the grand finale, all the way down the White Cliffs of Dover ! (which are somewhere between 80 and 110 meters high at that point I guess?), making us crash into the backpacker hotel before we reach this E Cliff road, which is recommended by OsmAnd

![afbeelding](https://user-images.githubusercontent.com/63048026/191042587-8ee4ac31-6ada-441a-a5f8-e06cf60273ae.png)

Hope this helps!

Regards, Hans

**Comment by Zirochkabila** [comment]
@Antheii Try to activate **"Allow private access"** (Navigation > Settings) - the route will be different from what is shown on OSM or Google maps, but the passage will be allowed and the route is shown.
