### ISSUE TITLE
Misleading street in Location for a selected building

### ISSUE THREAD

**Issue by mdykierek** [osmandapp/OsmAnd#15349]
### How to reproduce?
1. Find Kopalniana 20 in Ruda Śląska, Poland.
2. Select the building with the number 20. It will read (20 Location, Sztygarska, Bykowina).
3. In Actions | Modify POI the data shows Kopalniana 20.

Same thing for Kopalniana 10a (or even worse) - shows Kombajnistów 3c.
I figure, it shows where the navigation will take me, but confusion still present. Maybe street next to the number could help.
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/27214784/191340581-adc6bf9e-e39b-4710-a28e-690cb0daceec.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Your Environment
OsmAnd Version: OsmAnd+ 4.2.7
Android/iOS version: Android 11
Device model: Mi 9T Pro

**Maps used (online or offline):**   
September 2022 offline maps for Silesia.

**Comment by Zirochkabila** [comment]
**Not reproduced**
Try to reinstall OsmAnd (but before: Menu > Settings > Backup & Restore - will safe your data) or try to update the map


https://user-images.githubusercontent.com/104760013/191795464-47194564-cd8e-41f1-83f4-007251293c1c.mp4

**Comment by mdykierek** [comment]
> **Not reproduced**
> Try to reinstall OsmAnd (but before: Menu > Settings > Backup & Restore - will safe your data) or try to update the map

Enable Live updates to reproduce.
Re-installation doesn't help.

**Comment by Zirochkabila** [comment]
**Reproduced**  When activating live updates, house 10a displays a misleading street name

https://user-images.githubusercontent.com/104760013/191976734-be6b640a-4ce9-4b6b-9b9c-c593cc972e6f.mp4

**Comment by vshcherb** [comment]
Address is not supported in Live data. Please reproduce on regenerated map or on new maps

**Comment by Zirochkabila** [comment]
Failed to reproduce on the generated map
[Map here](https://drive.google.com/drive/folders/1360laBM4AGzxHEnR1OrLxXrsJ364sd7y?usp=sharing)
