### ISSUE TITLE
Default Theme

### ISSUE THREAD

**Issue by xmha97** [osmandapp/OsmAnd#15340]
Please use the "system default" theme by default

<img src="https://user-images.githubusercontent.com/23485114/191042668-02d1f1e5-3c44-42bf-a513-f20b80271214.jpg"  width="300" height="auto"/>

**Comment by dmpr0** [comment]
## ToDo
- [ ]  Set **App theme** option to **System default** as default choose for all new users. (For supported Android versions only)

**Comment by xmha97** [comment]
Thanks 🌹

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14192mqta, Released: 2023-02-21
Done

**Comment by shurasmiling** [comment]
- https://osmand.net/docs/user/map/vector-maps#map-mode
- https://osmand.net/docs/user/map/configure-map-menu#map-style-parameters
- https://osmand.net/docs/user/plugins/ski-maps#night-and-lighting
