### ISSUE TITLE
Seamark POIs are broken

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1534]
Next lines (when in poi_types.xml) does nothing:
```<poi_type name="seamark_category" tag="seamark:category"/>
<poi_type name="seamark_character" tag="seamark:character" type="text"/>```
Tested on synthetic_test_rendering. POI index does not contains any seamarks.

**Comment by xmd5a2** [comment]
Fixed, but there is another problem with additional seamark characteristics like
```<poi_additional name="seamark_colour" tag="seamark:colour"/>```
Besides, I don't see point for using some of these simplified additional characteristics. Lets consider this object:
seamark:beacon_lateral:colour=green;white;green;white
seamark:beacon_lateral:shape=tower
seamark:name=Beacon lateral green;white;green;white tower - black sphere
seamark:topmark:colour=black
seamark:topmark:shape=sphere
seamark:type=beacon_lateral
Here colour applied to TWO subobjects but our simplification to seamark:colour can reflect only one value.

**Comment by vshcherb** [comment]
I think something is misconfigured in poi_types.xml. That's not simplification, but split into 2 objects.
seamark=beacon_lateral
seamark:colour=green;white;green;white
seamark:shape=tower

seamark=topmark
seamark:shape=sphere
seamark:colour=black
seamark:attached=beacon_lateral
