### ISSUE TITLE
Two overlapping repositories for our documentation?

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#15357]
I am a bit confused which repositoty is to be maintained to keep our documentation up to date, is it osmandapp/docs or osmandapp/web? There seem areas (sub-trees) with different maintenance dates but largely overlapping content, e.g. https://github.com/osmandapp/docs/tree/main/content/osmand and https://github.com/osmandapp/web/tree/main/main/docs/user ?

**Comment by vshcherb** [comment]
https://github.com/osmandapp/docs/blob/main/README.md
