### ISSUE TITLE
GPX track configurations are not saved after backup

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15354]
### Description
After a backup of files from **OsmAnd Cloud** - GPX track configurations are not saved (display on the map, track width, color)
After a **local** backup of files - track display on the map is not saved but width and color are saved.

### Steps to reproduce
Menu > Settings > Backup & Restore > Backup now
Restore data

Menu > Settings > Backup & Restore > Back up as file > Select Favourites > Continue
Select osf file > OsmAnd

### Actual result
Track configurations are not saved

### Expected result
Track configurations are saved

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13802mqta, released: 2022-09-21
Android/iOS version: Android 12
Device model: POCO X3 NFC

**Comment by vshcherb** [comment]
That's expected. Display on the map is part of Settings

**Comment by Zirochkabila** [comment]
@vshcherb Then why are the results of a local backup different from a backup to the cloud?

**Comment by vshcherb** [comment]
Shouldn't be different but backup should be complete
