### ISSUE TITLE
Impossible lane assist - left and straight simultaneously

### ISSUE THREAD

**Issue by mdykierek** [osmandapp/OsmAnd#15350]
### Description
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/27214784/191343540-1519024f-c36a-4bcb-a345-c2fe664e7a62.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### How to reproduce?
Simulate Car route from bus stop Chorzów ZUS to Teatr Rozrywki in Chorzów, Poland.
Lane assist will show left and through lanes simultaneously.
I do not see any obvious errors in OpenStreetMap data.

### Your Environment
OsmAnd Version: OsmAnd+ 4.2.7
Android/iOS version: Android 11
Device model: Mi 9T Pro

**Maps used (online or offline):**   
September 2022, Silesia, Poland

**Comment by Zirochkabila** [comment]
**Not reproduce**
Try to reinstall app (before: Menu > Settings > Backup & Restore - will safe your data) or update the map

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/191793460-64929641-c2b2-4198-a417-795b55f2bfc9.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/191793471-419e22e1-ab63-4493-828b-ca3518244f5c.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by mdykierek** [comment]
Enable live updates. The intersection Dąbrowskiego - Kopernika - Zjednoczenia has now correct turn lanes (matching real world) since September 5th.

**Comment by mdykierek** [comment]
Has it been fixed or I will have to file it again in November when it gets to the monthly maps?

**Comment by Zirochkabila** [comment]
**Reproduced** When you activate the live update, the lane direction widget displays left-turn and straight ahead at the same time
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/191980186-968580ed-953a-4dde-a099-f13fab5c8533.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/191980190-12923dd4-cf40-45eb-b065-1b83a4b05114.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by mdykierek** [comment]
Please note that this probably is not directly related to Live updates. I have mapped the intersection with lane markings matching the road signs and only by chance I had to go through this intersection again. It was unlikely that I notice that. Pure chance.

**Comment by vshcherb** [comment]
Is it related only to OsmAnd Live or will be reproduced on new maps?

**Comment by mdykierek** [comment]
I will check as soon as October maps will be available.

**Comment by vshcherb** [comment]
@Zirochkabila it's possible to generate current  map with map creator

**Comment by Zirochkabila** [comment]
@vshcherb  Result was repeated when a new card was used
[Map](https://drive.google.com/drive/folders/15QiQGWHSYFNgHC0FGztj7e7ZZz0RJw2v?usp=sharing)

**Comment by vshcherb** [comment]
Todo:
1. Tests
2. C++
3. Revert https://github.com/osmandapp/OsmAnd-resources/pull/984/commits/67448d51f9393a597a6f00d775d7ecb3171fb49e

**Comment by dmpr0** [comment]
Add
* ToDo
* Add what have been Done
