### ISSUE TITLE
Half-Empty MapRouteInfoMenu displayed in MenuState.FULL_SCREEN

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#15352]
Is it intended behavior that during route calculation the MapRouteInfoMenu remains in status `MenuSate.FULL_SCREEN`, i.e. does not collapse to `HALF_SCREEN`  for the potentially frequent cases where the lower portion of the sheet does not contain anything?

The occurrences can be reproduced in different ways, e.g. as follows: Make sure no route calculation is active and no destination is selected, then:
- On the map scren, tap the Navigation arrow button,
- then on the MapRouteInfoMenu tap 'Set destination',
- then select a destination e.g. via tapping the 'Favorites' button.

Now you will get this half'emty full screen, and potentially for a long time during the entire route claculation:

![20220921_083136](https://user-images.githubusercontent.com/845735/191431561-68ddc7ce-bb53-4bc3-bc28-c51984f44201.jpg)

There are common others ways also producing  this view, while in some situations the bottom may actually contain somethig, like if you picked a favorite too far away, itiwould show the hint about long routes and suggesting to add an intermediate.

I suggest we could check if anything is being displayed below the progress indicator and if not collapse the menu to `HALF_SCREEN`?

**Comment by sonora** [comment]
PS: In contrast, we already handle things like I suggest above, if you follow these steps:

On the map, select any point e.g. by long-tapping, then tap the bottom sheet's Navigation button. You will now receive this menu state (rest of the screen displays the map), which is perfect:

![20220921_092049](https://user-images.githubusercontent.com/845735/191440715-9a6f9b36-6aed-4d3e-8c01-21aa538ec56c.jpg)

**Comment by vshcherb** [comment]
To save you can click after route is calculated to the preferred state and click start. Later that state will be used for calculation.

**Comment by sonora** [comment]
Hm, but most users are not even aware the dialog can pushed down at all...

**Comment by vshcherb** [comment]
Exactly by design it's full screen probably we add more widgets inside current there is a widget there that some maps are missing
