### ISSUE TITLE
Option To Search Without Specifying Category

### ISSUE THREAD

**Issue by seniorm0ment** [osmandapp/OsmAnd#15364]
Requesting the ability to search all categories, so you do not have to type Restaurants and then type Applebees.
You can simply type Applebees.

Then if you want to nail it down you can just click Filter and pick which category.

It's just added steps for no major reason, also it makes it hard to find stuff you don't know which POI type it is listed under ("Is it considered fast food? Restaraunt? Etc)

**Comment by tradavyvy** [comment]
I think that already works. I am in Delhi right now and when I search (from the map magnifying glass) for domino's I get a list of  these pizza restaurants and when I choose show on map they all get orrange markers (including Domino's Tailors)

**Comment by sonora** [comment]
The categories are optional filters if you want to narrow the seaech.You can certainly search without first picking one.

**Comment by seniorm0ment** [comment]
Is this a setting I need to change? It seems to maybe work sometimes idk?
Like if I type Applebees it does not bring up Applebees restaraunts or anythingbnear me, but omly 2 places multiple states away.
If I filter by restaraunt it shows Applebees near me.

Also it would be nice if we can filter post search. So search Applebees, then try to filter by restaraunt. Instead of needing to delete the query and retry it. A simple filter icon that you can click, choose the type, and have it insert would resolve this. 
It can function as a block separate from your query, so you can change between different categories.

**Comment by sonora** [comment]
Have you waited long enough? Depending on how many maps you have and where you are, unfiltered search can take considerably longer. If you want to share your approximate location, we could try to reproduce and check if there is a bug.
