### ISSUE TITLE
Icon - copy from POI to Favourite

### ISSUE THREAD

**Issue by gubrist** [osmandapp/OsmAnd#15366]
### Description

I use OsmAnd+ 4.2.7.

I display POI's at the location where I am staying at the moment:

![Screenshot_20220924-131929_OsmAnd+](https://user-images.githubusercontent.com/22197180/192106159-82980746-5171-4f71-a9b5-9b17a13d2f38.jpg)

I mark a POI and create a Favorite.

Sometimes, the Icon of the POI is not copied into the Favorite:

![Screenshot_20220924-131955_OsmAnd+](https://user-images.githubusercontent.com/22197180/192106301-68927834-97fe-43c4-88b3-e37e442d1bbf.jpg)

### Describe the solution you'd like

I want that the Icon of the POI **always** is copied to the Favorite.

### Describe alternatives you've considered

Spend time to:
- search and find and 
- replace 
the icon in the Favorite selection.

But:
I cannot find all icons of POI's in the Favorite selection.

**Comment by tradavyvy** [comment]
Altough I would like all available poi icons to be accessable for use in favourites. I myself would prefer that when I mark anny place as a favourite the icon (and colour and shape) follows the chosen default for the group that favourite will be part of. That is in my eyes the purpose of setting a default for a group, if I want something different I will set that manualy.

**Comment by pebogufi** [comment]
@gubrist
use a current nightly build or wait for next release, there it works.

**Comment by vshcherb** [comment]
Yes fixed in coming 4.3
