### ISSUE TITLE
City names should be shown according to population size

### ISSUE THREAD

**Issue by AxelBoldt** [osmandapp/Osmand#1536]
Using osmand 2.0.4 with map Germany_bayern_europe_2.obf.zip from 23.07.2015.

On the first screenshot you see the German cities Nürnberg (Nuremberg) and Fürth. Note that Nürnberg is five times as large as Fürth based on population, and the population sizes are properly recorded in the OSM database. The second screenshot shows the same area, but zoomed out. The label "Fürth" is shown, but "Nürnberg" is missing. 

Presumably there's not enough space on the map for both names, so osmand drops one of them. Clearly, in situations like this, the smaller city's name label should be dropped.

The standard openstreetmap.org map layer has the same problem, but the Humanitarian style does it correctly.

![screenshot_2015-08-05-19-49-32](https://cloud.githubusercontent.com/assets/8941698/9093497/be4d68da-3bac-11e5-812c-2a1e5fca8608.png)
![screenshot_2015-08-05-19-49-53](https://cloud.githubusercontent.com/assets/8941698/9093498/be5254a8-3bac-11e5-88f4-62500ae0598e.png)

**Comment by sonora** [comment]
Yes, we had worked on place labeling lately, and made some big improvements (will be visible in the next release). We now have the OSM hierarchy correct, about like this (in order of falling priority):
   city -town - village/suburb - hamlet
So the remaining issue is the one you discover: Both Nuremberg and Fuerth in OSM are cities, and there is no good mechanism to discover Nuremberg is 5 times bigger (like any manual editor for a paper map would consider).

You will see similar issues where 2 village labels would overlap, and the name of the smaller village may be displayed while the lager one may not. We also put villages and suburbs on the same priority level, se they will how similar effects.

There is no easy fix, I am afraid, unless anybody has a good idea here?  Thx - Hardy

**Comment by fred702** [comment]
[key:population](https://wiki.openstreetmap.org/wiki/Key:population)?

**Comment by HolgerJeromin** [comment]
area size of the Relation:boundary. At least in germany this would work.

**Comment by AxelBoldt** [comment]
I think the population key is the way to go here, because population size correlates better with importance than does area size. It appears that the openstreetmap Humanitarian style also uses the population key to decide these matters.

**Comment by Gizmot** [comment]
key:population would be a great start compared to the current map mess of random cities.

Also, need some sort of mechanism to artificially boost lowly populated area with major tourist attractions.
Exemple: try finding Jasper (BC, Canada on a map)

**Comment by vshcherb** [comment]
I think nightly builds already covers simple scenarios.

**Comment by paule89** [comment]
If there is any chance, the political status of a city could also have an impact on the rating for showing it, as some cities are capitals of states (e.g. sacramento), but not the biggest cities in these states.

But so far, I would also consider the population as the key metric for the importance.

**Comment by xmd5a2** [comment]
Already added support for population, but new basemap will be published closer to release. But if you wish you can test it with new nightly http://builder.osmand.net/basemap/World_basemap_2.obf
Country names, city-hamlet are sorted by population. places with capital=yes have even more priority.

**Comment by fred702** [comment]
As an alternative to captial=yes, the [admin level number](https://wiki.openstreetmap.org/wiki/Proposed_features/capital) is also a [widely used](https://taginfo.openstreetmap.org/keys/capital#values) value.

**Comment by vshcherb** [comment]
Cause we usually close issue once it is available in nightlies, this one also will be closed, however new basemap file is needed.
