### ISSUE TITLE
POI selection profile template

### ISSUE THREAD

**Issue by gubrist** [osmandapp/OsmAnd#15367]
### Description

I use OsmAnd+ 4.2.7.

and POI's.

Depending on where and how I am travelling, I basically use a hand full of standard selections:

Example Selection A:

![Screenshot_20220924-145000_OsmAnd+](https://user-images.githubusercontent.com/22197180/192106741-5b3b58d2-bc3b-4c41-b408-6d9ba2d051b3.jpg)

Example  Selection B:

![Screenshot_20220924-145017_OsmAnd+](https://user-images.githubusercontent.com/22197180/192106750-723fe0c3-888c-4b97-bf6f-5efca776da35.jpg)

### Describe the solution you'd like

I want to to store these selections as profile / template 
to recall them later.

### Describe alternatives you've considered

Manually re-select all the POI's each time, 
which is time-consuming and tedious.

**Comment by sonora** [comment]
- On the Search screen, go to the Categories tab.
- Scroll all the way down and select "Custom search".
- Pick your categories and sub-categories (there is a sub-category screen for each category, access by tapping the category) as you wish. Return from each sub-screen via "Apply".
- You can then name and save the entire selection as a custom filter via the 3 dots top right.
- Repeat for as many custom filters as you need.

**Comment by gubrist** [comment]
Thanks. 

>
>     * Pick your categories ...
> 

If I pick "categories" as per above Example Selection A:

- I can see and check "Tourismus"
- I **cannot** see "Sehenswürdigkeiten"

Why are not all POI main-categories available in the Search-Menu?

**Comment by pebogufi** [comment]
I think there is a wrong menu for 3-dots,
it shows only "Filter speichern"
instead of 
* Kategorien bearbeiten
* Speichern als
* Filter löschen
see screenshot

![Uploading 20220924_200924.jpg…]()

What is needed for creating custom serach categories is "Kategorien bearbeoten"

**Comment by pebogufi** [comment]
@gubrist
Sehenswürdigkeiten is a subselection of tourism and a few other points. 
You can save it as custom search with 3-dots menu "Filter speichern" , then with "Kategorien bearbeiten" you see whats in it.

**Comment by gubrist** [comment]
> @gubrist Sehenswürdigkeiten is a subselection of tourism and a few other points. 

Why are there different levels
between POI Overlay and Categories?

https://user-images.githubusercontent.com/22197180/192106741-5b3b58d2-bc3b-4c41-b408-6d9ba2d051b3.jpg

**Comment by scaidermern** [comment]
> > @gubrist Sehenswürdigkeiten is a subselection of tourism and a few other points.
> 
> Why are there different levels between POI Overlay and Categories?

The POI Overlay and Search>Categories should contain the same list of POIs. These are important POIs that are relevant for most users. This is a flat list, without "levels". The name "Categories" is a little bit misleading, maybe it should be called POIs instead.

The custom search is slightly different. It is hierarchical and allows to select *all* POI types currently known by OsmAnd. Because there are so many different POIs this works only with a hierarchical approach.

**Comment by gubrist** [comment]
> I think we have Quick action for that

What is the "Quick action"?
