### ISSUE TITLE
Map Marker don't work anymore

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#15362]
### Description
- Pressing long on Map Marker should position the map to the appropriate point, currently nothing happens.
- Pressing short on Map Marker shows either a minus sign "-", or a time (hh:mm), but it is very unclear what should it be good for.
The time does change very often, i don't see a difference when changing profile.

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#34621m, veröffentlicht: 2022-09-20
Android version: 10
Device model: Samsung S5e tab

**Comment by vshcherb** [comment]
I think you are talking about this setting

![telegram-cloud-photo-size-2-5289978461500325178-y](https://user-images.githubusercontent.com/1042025/191950782-9d635a55-61cc-4814-b104-3128b2c8d385.jpg)
