### ISSUE TITLE
height length Width

### ISSUE THREAD

**Issue by mxdlinux** [osmandapp/OsmAnd#15370]
hello,
I am trying osmand in a truck, I have set the options height, length, width.  but the proposed routes do not take into account the options and make me take roads with bridge heights and widths that are too small.

**Comment by scaidermern** [comment]
Can you show an example?

Do these bridges in OSM contain the relevant information?

**Comment by mxdlinux** [comment]
journey from rue du grand peuplier, strepy bracquegnies belgium to rue des fabriques , obourg belgium, I was 4.8 meters high and osmand wanted me to take the highway which is prohibited for more than 4.3 meters and take a national with bridges lower than this height

**Comment by scaidermern** [comment]
This is a route with many bridges. Which exact bridge are you talking about?

Does this bridge in OSM contain the relevant information?

**Comment by mxdlinux** [comment]
on the motorway in Belgium the height limit on the motorway is 4.3 meters and on the national from 4.3 meters to 4.5 meters, there are compulsory roads and from 4.5 meters to 4.8 meters other compulsory roads  , the problem bridge is at this location at 50.4710528, 4.0081557

**Comment by scaidermern** [comment]
So it is about [this road](https://www.openstreetmap.org/way/122146411) I suppose?

There is a [`maxheight`](https://wiki.openstreetmap.org/wiki/Key:maxheight) tag present but only maxheight=default. So it looks to be a OSM data problem. If you know the real height restriction then please edit the OSM data accordingly.

**Comment by vshcherb** [comment]
Very tricky.. but we can use default at least US/Europe. Europe should have common default
