### ISSUE TITLE
nearby public transport connections not shown if multiple times present (e. g. bus and tram with same number)

### ISSUE THREAD

**Issue by call-me-matt** [osmandapp/OsmAnd#15374]
### Description

When selecting a public transport station and looking at the nearby connections, OsmAnd does not show lines that have identical names. For example if there is a bus and a tram with the same number, only one of them is shown.

### How to reproduce?

For example here:
Tartu mnt, Tallinn
Standort: geo:59.42747,24.77828?z=17
https://osmand.net/go?lat=59.42747&lon=24.77828&z=17

There is a bus No. 2 and a tram No. 2
If selecting a station nearby, either the tram or the bus are shown, but never both. If it is a stop of the bus No. 2, tram No 2 never is shown and vice versa.

### Your Environment
OsmAnd Version: OsmAnd~ 4.2.7
Android/iOS version: Android 13
Device model: Pixel 4a

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
Estonia_europe from 01.09.2022

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/34400929/192349501-faf5b56e-dd7b-4c69-81ee-27e299b768bb.png"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/34400929/192349509-3ae438d0-f00d-4737-b156-66729dacf6c1.png"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/34400929/192349510-bc319a11-1fc5-4c8d-a529-45d85db9c007.png"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/34400929/192349516-c519a10e-e072-4371-b4e7-73b51b0f46fb.png"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/34400929/192349519-826734d0-75d6-46c3-accb-4a29891e5be4.png"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
Both bus #2 and tram #2 are displayed in the list of routes


https://user-images.githubusercontent.com/104760013/196028587-ad1b0491-8ee5-45c1-bfae-2e034bded1f6.mp4

**Comment by call-me-matt** [comment]
Ok, but why aren't they in the overview?
![Uploading Screenshot_20221016-160037.png…]()

**Comment by call-me-matt** [comment]
Cool, thank you!

**Comment by dmpr0** [comment]
## Review
Tested on TestFlight 4.3.0.31
- [ ]  Should be fixed on iOS too?
- [ ]  iOS: Route order the same as on Android

<table style="width:100%">
  <tr>
    <th colspan=2>iOS</th>
    <th colspan=2>Android</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/201638490-ab00342e-a7e7-40ab-aa31-d5c57d7d6cbc.PNG"  width="200" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/201638494-19693b20-2d9f-41ef-b955-da3fdfc64d3e.PNG"  width="200" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/201638767-44109b7b-79ae-458e-9682-7a080a74b8a4.png"  width="200" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/201638774-0ddf4701-d62a-4444-86c9-e32564711c2f.png"  width="200" height="auto"/> </td>
  </tr>
</table>
