### ISSUE TITLE
Umlauts missing in higher zoom levels

### ISSUE THREAD

**Issue by Isolator70** [osmandapp/OsmAnd#15376]
### Description
Depening on zoom level Umlauts are not shown anymore, eg. Köln becomes Koln.

### How to reproduce?
Change zoom level from low (far away) to higher (closer) with "Köln" in focus. At certain level Köln becomes Koln, see attached screenshots

### Your Environment
OsmAnd Version: 4.2.7
Android/iOS version: 9
Device model: Huawei P10

**Maps used (online or offline):**   
Offline maps from 01.09.2022

Correct Umlauts:

![Screenshot_20220926_202136_net osmand plus](https://user-images.githubusercontent.com/35434137/192352535-b2ad9947-019a-4d05-b4da-e9bfbd1c11a8.jpg)

Umlauts gone:

![Screenshot_20220926_202121_net osmand plus](https://user-images.githubusercontent.com/35434137/192352690-a161dd43-7820-478c-b128-7902ad744832.jpg)

**Comment by vshcherb** [comment]
If you are using language Local names I think it's still displays with umlauts i.e. Köln, Du..sseldorf
