### ISSUE TITLE
Wrong name of location (village) at placing marker on map

### ISSUE THREAD

**Issue by Isolator70** [osmandapp/OsmAnd#15375]
### Description
Placing a marker on map via long touch, here near "Hauptstraße, Schwalbach" (N50.49632, E 8.47122).
Problem: Street name is correct, but village is wrong "Bonbaden" instead of "Schwalbach". Bonbaden is some kilometers away, villages are not linked in any way.

### How to reproduce?
For me it is 100% reproducible, Hesse maps are from 01.09.2022

### Your Environment
OsmAnd Version: 4.2.7
Android/iOS version: Android 9

Device model: Huawei P10

**Maps used (online or offline):**   
Offline map, Hesse from 01.09.22

Screenshot of issue:
![Screenshot_20220926_191307_net osmand plus](https://user-images.githubusercontent.com/35434137/192350109-36911d33-f453-4c04-82aa-c6f792ffb653.jpg)

Village "Bonbaden" is left of "Schwalbach"

![Screenshot_20220926_191322_net osmand plus](https://user-images.githubusercontent.com/35434137/192350315-6e0ab7ec-9ebe-4fff-9ae4-ddcd1fe6828c.jpg)

**Comment by vshcherb** [comment]
![Screen Shot 2022-09-28 at 19 49 11](https://user-images.githubusercontent.com/1042025/192853302-b7cdb1ec-9ecb-4ccb-a9b6-b5125172c0f8.png)
I think it's fixed in 4.3 coming - tested on device as well
