### ISSUE TITLE
Timing/position of navigation commands  are shifting, while following a GPX-track

### ISSUE THREAD

**Issue by C6competition** [osmandapp/OsmAnd#15372]
During navigation on an GPX-track the navigation announcements are shifted by time/distance to the correct location for turning action etc.

As example I used this track, generated with Osmand, of about 110 Km

[Navi Test 22 Sept 22.zip](https://github.com/osmandapp/OsmAnd/files/9646478/Navi.Test.22.Sept.22.zip)

At the beginning of the track, the timing of the navigation announcements (voice) are ok and the distance (shown in the left panel pictogram) to the center of the crossings, where You have to enter another street, seemed to be correct. Although I have to say, the street name in the top panel is not correct! In general I have to say, the position of the vehicle is always shown correct!
But it’s a pity, the recording software is not recording the voice announcements as well!

https://user-images.githubusercontent.com/99248549/192285968-178f5cbe-f612-47ba-976b-1df67486286f.mp4

At the next position at Km 22.6 there is about a difference of 200 m between the actual position of the vehicle and the distance shown in the left panel. 

https://user-images.githubusercontent.com/99248549/192286188-bb423dbe-90d3-4467-bc55-22c1f691b37e.mp4

 At the next point at Km 40 the difference has become smaller, about 50 m

https://user-images.githubusercontent.com/99248549/192286265-ece494df-3a11-4ca2-a181-f73349c18f41.mp4

While at the next point at Km 59 the difference has grown to 200 m

https://user-images.githubusercontent.com/99248549/192286468-4e6fe9b0-c0af-471b-82a2-7762f419f77f.mp4

While at the next point at Km 82.8 the difference has grown to 400 m

https://user-images.githubusercontent.com/99248549/192286590-3a3ab8c7-8266-4b56-8ca8-48600c507b0e.mp4

On the next videos we are driving on a highway waiting for the exit to leave. On the video at Km 97.4 you see the advice for the exit to come, while in the next video at Km 100 You see the exit appearing real. The difference between the announcement and the real appearing of the exit is about 2000 m!
 

https://user-images.githubusercontent.com/99248549/192286710-eb0a0c24-4efb-4614-81e5-08f3073cff54.mp4

https://user-images.githubusercontent.com/99248549/192286736-ad1b419d-7b33-472d-bb37-b7e056f2a121.mp4

Now that we are coming closer to the end of the track (about 110 km)
The behaviour of the software is changing!
At Km 106 a fake roundabout is announced in about 200 m, while the distance to the real roundabout is about 550 m! When the vehicle is reaching the fake roundabout (after about 200 m) the software switches to the real position of the roundabout and shows the correct distance (350 m)!

https://user-images.githubusercontent.com/99248549/192286907-09cd8620-6151-411f-88a6-8d1352b41d89.mp4

https://user-images.githubusercontent.com/99248549/192286928-de747016-4cb2-434a-9626-b0525cc42a54.mp4

At Km 108 nearly the same procedure takes place. It tells there are about 250 m to go to next turn into another street. In real distance it’s about 450 m to go. 
When the correct distance is shown in the last video, the top panel is showing the correct street name and pictogram for the crossing as well! 

https://user-images.githubusercontent.com/99248549/192287031-01e4afed-f671-4a9e-bf1d-7e9a7b0aee42.mp4

https://user-images.githubusercontent.com/99248549/192287057-3f232e08-814d-4ce7-8bb7-f2086c65226a.mp4

At first view it looks like, the timing navigation commands (both, voice and left panel) are getting shifted more and more, the farer the vehicle is following the track. But this is not the case at Km 22.6 and towards the end of the track the behaviour is completely different?

 

OsmAnd Version: 4.2.6
Android/iOS version: 10.0
Device model: BV 9900E

**Comment by scaidermern** [comment]
Could be the same as #15171.

**Comment by Zirochkabila** [comment]
@C6competition If use simulation of navigation on GPX, which you added, it is possible to reproduce wrong street name in "Street name" widget and the fact that after 23 kilometers widget "Next turn" and voice prompts are ahead of the actual location on the map.
But if you start navigation on another [GPX](https://github.com/osmandapp/OsmAnd/files/9683964/paralon.gpx.zip), with the same route, and attach this track to the road - the street name in the "Street name" widget corresponds to the real, as well as after 23 kilometers widget "Next turn" displays the turns correctly, voice prompts also work correctly.
Accordingly, it's all about the GPX file you sent.
@scaidermern  was right - this is similar #15171

**Comment by C6competition** [comment]
@Zirochkabila Thanks for Your respond
Yes, I didn't notice that the issue  #15171 was opened in the meantime, while I was investigating. But may be my records might help You in addition.
Coming back to the GPX file you send, it doesn't realy help me to get rid of the "street name " widget problems and get correct voice prompts. When I attach Your GPX track to the road, I get a lot of nonsence:

![screenshot 1](https://user-images.githubusercontent.com/99248549/193407702-66562703-95a9-4f6c-a09a-1cd8025d0868.jpg)
![screenshot 2](https://user-images.githubusercontent.com/99248549/193407713-1fb365af-79a0-4e14-96e2-7e87490b325a.jpg)
![screenshot 3](https://user-images.githubusercontent.com/99248549/193407729-cf6fcc3b-4a81-4d15-86df-a4602ffe6e3c.jpg)
![scree
![screenshot 4](https://user-images.githubusercontent.com/99248549/193408087-72c7bc81-b9da-42bf-8855-49a98a086555.jpg)
![screenshot 5](https://user-images.githubusercontent.com/99248549/193408097-27092fd3-23f1-4625-99f3-c39bc9a2fbc1.jpg)

But I still have the recorded track of the drive, I generated all the above videos with( that is no simulation! It is real time recorded, while driving with the motorbike on the GPX-route. )

[2022-09-22_12-58_Thu.zip](https://github.com/osmandapp/OsmAnd/files/9690190/2022-09-22_12-58_Thu.zip)

I will attach this track to the road and do some further investigations.
