### ISSUE TITLE
Hiding house numbers

### ISSUE THREAD

**Issue by romavor** [osmandapp/Osmand#1538]
Hello, 

I would really appreciate to have an option for hiding/unhiding house numbers. On phone, there is a too much information on the map in most cases - when I'm using OsmAnd for car navigation house numbers are sometimes disturbing. 
The same thing is when I walking somewhere, I can find the house before a walk and mark it as a finish point so I do not need to see all those house numbers.
It's nice to have an option to hide building (useful for car navigation) but many labels (especially house numbers) are much more disturbing than buildings.

It would be nice to make house number optional.

Thank you,
Roman

**Comment by jkufner** [comment]
I think it should be the same as with contour lines -- Option to set
max. zoom level where numbers are visible. By setting it to more than
usually used zoom level will hide numbers, but you can easily see them
when zooming in.

**Comment by romavor** [comment]
But I'm not sure if this would work properly when using OsmAnd as a car navigation with automatic zooming according to speed.

**Comment by sonora** [comment]
Leonid, I suggest we could maybe link the display of the house number
labels to the "More details" setting being set or not in the Map
configuration settings?
Best, Hardy

**Comment by xmd5a2** [comment]
We can do it but building names will be hidden also.
I tried to do this option some time ago but get stuck with OpenGL engine bug which can't render text from other tag than first in our OBF data. For example it can't render text from building and tourism=museum here:
```Way types [addr:housenumber (222), tourism-museum (1015), building (137)] Names [name(1) - Museum, addr:housenumber(222) - 10] id -13317```
It will use only this code:
```	<case minzoom="16" tag="addr:housenumber" value="" nameTag="" nameTag2="addr:housenumber"/>
	<case minzoom="16" tag="addr:housenumber" value="" nameTag="addr:housenumber"/>```
Well.. this code
```	<case hideHouseNumbers="false" tag="building" value="" nameTag="" nameTag2="addr:housenumber"/>
	<case tag="building" value="" nameTag=""/>
...
	<switch hideHouseNumbers="false">
		<case minzoom="16" tag="addr:housenumber" value="" nameTag="" nameTag2="addr:housenumber"/>
		<case minzoom="16" tag="addr:housenumber" value="" nameTag="addr:housenumber"/>
...```
will work perfect with old engine but in OpenGL engine there will be many missing names.
So it is now impossible to hide ONLY housenumbers but keep building names or tourism=museum name as above in OpenGL engine. His author Alexey Pelykh is inactive for a long time but knows about this bug.

**Comment by aceman444** [comment]
Yes please keep housenumbers, but making the toggleable in "More details" seems reasonable.

**Comment by xmd5a2** [comment]
Fixed but not perfect. When building tag is on the same way/point with address it will be rendered independently of this option.
