### ISSUE TITLE
Loss of ongoing OSM GPX track on battery depletion or crash

### ISSUE THREAD

**Issue by bkil** [osmandapp/OsmAnd#15387]
Could we progressively save it or as an MVP save the current one and open a new one once every x minutes?

**Comment by bkil** [comment]
Sorry, it seems like the track appeared after a reboot. I'll keep an eye on it to see whether anything like this occurs with a potential reproduction in the future

**Comment by scaidermern** [comment]
I also managed to deplete my phone battery during recording today...
The recorded track still exists, though. So looks like everything works as expected.
