### ISSUE TITLE
Customize route line: allow to change direction arrows color

### ISSUE THREAD

**Issue by 32Vache** [osmandapp/OsmAnd#15381]
# 🚀 feature request

### Description

Currently the direction arrows of routing are sometimes not visible when using route line styling, like here with the slope route line style, when there is no slope the line is white, and since the arrows are white too, you cannot see them:
![IMG_20220928_184304.jpg](https://user-images.githubusercontent.com/42336759/192841525-5430f4d9-ac8b-4e2e-938d-ff8ef289e570.jpg)

### Describe the solution you'd like

Be able to change the color of the direction arrows, or make it so they change color if they are the same color as the line (for example when it is white on white like above)

**Comment by Rowin63** [comment]
Some user defined route line colours would be nice at night mode. but not possible to use, because the arrows then are the same colour as the line, like when choosing blue colour. I agree, it would be nice to also customize the arrows.

**Comment by Zirochkabila** [comment]
The color of the directional arrows in V1 and V2 Rendering differs
OsmAnd~ 4.4.0#14117mqta, released: 2023-01-20


https://user-images.githubusercontent.com/104760013/213686564-991fb5dd-2dc9-4555-becd-4c3882e3c6e3.mp4

**Comment by dmpr0** [comment]
Driving profile, all settings are reset to default.
- [ ] Different route line thinkness 
<table style="width:100%">
  <tr>
    <th>Version 1</th>
    <th>Version 2</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/214258655-fc169301-779c-480f-80cb-83f59e1b5817.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/214258650-690e4ba7-d8cd-4995-9494-61c5c80e56fe.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/12978
