### ISSUE TITLE
OsmAnd did not use the ferry crossing for a shorter route

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#15384]
### Description
When building the route, there is a ferry crossing, but OsmAnd does not offer it for the Driving profile and lays the route 500 km longer.
https://www.openstreetmap.org/way/40092029#map=10/47.7873/-69.8470
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/80623554/192964180-a853a466-a71b-4681-8f86-d82f846afc11.png"  width="auto" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/80623554/192961907-5e52f64a-54bd-4eb2-ac76-36065e9d80a4.png"  width="auto" height="auto"/> </td>
  </tr>
</table>  

### How to reproduce?
Start 48.15063, -69.70894
Finish 47.90828, -69.47992

Driving profile (Default).
Downloaded map: Canada Quebec (updated 1 Sep 2022).

### Your Environment
OsmAnd Version: 4.2.7
Android/iOS version: Android 9
Device model: Sony Experience XZ1

**Maps used (online or offline):**   offline
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by TheSnoozer** [comment]
have you disabled the use of a ferry in your navigation profile?

**Comment by anastasiia936** [comment]
@TheSnoozer no. No road restrictions were added

**Comment by Zirochkabila** [comment]
If you download the map **"Canada Quebec Cote-Nord"** and **"Canada Quebec Bas-Saint-Laurent"** - the route will be as follows
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/193601619-df575f14-e542-4a24-93cf-71ae89dc38de.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

If you download the map of "Canada Quebec Cote-Nord", "Canada Quebec Bas-Saint-Laurent" and **"Canada Quebec Capitale-Nationale"** - the route will be as follows
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/193601885-13fc414e-af88-458a-844a-2682d94ae792.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

If you download the map of "Canada Quebec Cote-Nord", "Canada Quebec Bas-Saint-Laurent", "Canada Quebec Capitale-Nationale" and **"Canada Quebec Chaudiere-Appalaches"** - the route will be as follows
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/193602024-01876e94-66e1-470c-8f47-ad4a7039937e.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
Main issue is fixed  - the difference with [Optimal] Routing is not correct
