### ISSUE TITLE
Traffic light penalties sometimes make a confusing detour to avoid the traffic light

### ISSUE THREAD

**Issue by itzikiap** [osmandapp/OsmAnd#15390]
# 🐞 routing report
For some junctions with traffic lights, OSMand routing detour the light by making a right turn, an immediate U-turn and another right turn to the original rode. Not only it's annoying, but it's also very confusing, because way before seeing the junction itself, you get a notification to turn right, which might prompt you to alter your driving speed or style accordingly.

### Routing engine

- [V] OsmAnd's in-app offline routing

### Routing Profile
Using Car routing profile, default settings.

### Start and end points

This phenomenon actually happens a lot, at arbitrary junctions.
For example, here:
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=32.67831%2C35.41172%3B32.68132%2C35.41581#map=17/32.67981/35.41377

### Actual and expected routes

When in a rode, there's
![osmand trafficlight penalty](https://user-images.githubusercontent.com/11741425/193217320-05929775-b4c0-46bc-8d7a-a668e512be7c.jpg)
 a traffic light and the route doesn't need to turn, don't make a needless maneuver.

### Is this a regression?
No, actually, it's an old bug.

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>
OsmAnd~ 4.3.0#13825mqta, Released: 2022-09-28
</code></pre>

**Device and Android/iOS version:**
Android 11

**Maps used (online or offline):**

- [ ] Offline maps offered within the OsmAnd app for download.

**Comment by Henry00572** [comment]
I've added a turn restriction at this particular junction and the routing by https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=32.67831%2C35.41172%3B32.68132%2C35.41581#map=17/32.67981/35.41377 now doesn't make a u-turn anymore. Of course this is only one junction, but as long as the OSM data doesn't have turn restrictions prohibiting OSMAnd from doing a u-turn, it will be difficult to exclude this from routing and in some countries u-turns might be allowed if they are not prohibited explicitly by signs, markings or separated lanes.

**Comment by scaidermern** [comment]
It is hard to believe that taking two link roads, crossing a secondary and making an (almost) u-turn is faster than waiting at the traffic light. At least one penalty and/or assumed speed is wrong.

**Comment by itzikiap** [comment]
Thank you for fixing it!
Even in places where it isn't illegal to u-turn, this kind maneuver is wrong, and even takes longer than just waiting for the light. 
I understand the justification for traffic light penalty,  taken over long routes, this might give a better route with much less traffic lights, but in these cases it's just wrong.

**Comment by vshcherb** [comment]
Difference in cost is small 27 vs 30. https://osmand.net/map?start=32.678107%2C35.411028&end=32.679890%2C35.414048&mode=car#18/32.67878/35.41341 (it's possible to click avoid road on the map). Probably we need to check what's the penalty for sharp left turn (routing can't understand it's a turn and technically it's not even a turn...

**Comment by vshcherb** [comment]
@scaidermern I looked at it and yes it's not mapped as it looks on the imagery, probably precise mapping wouldn't have that issue in first place but we will double check if penalty is enough.

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-resources/pull/862
