### ISSUE TITLE
Crash when simulating GPX navigation

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15391]
### Description
If you turn on the simulation of navigation on the GPX 
[Navi Test 22 Sept 22.gpx.zip](https://github.com/osmandapp/OsmAnd/files/9683458/Navi.Test.22.Sept.22.gpx.zip) - the application crashes. Most likely, the case is that the navigation service did not have time to start.
**Workaround** - is to start navigation by track, and then activate the simulation.
[exception (nightly).log](https://github.com/osmandapp/OsmAnd/files/9683477/exception.nightly.log)
[exception (release).log](https://github.com/osmandapp/OsmAnd/files/9683478/exception.release.log)

### Steps to reproduce
Select GPX > Navigation > Select start point > Options > Simulate navigation > Start

### Actual result
Application crashes
[Video here](https://github.com/osmandapp/OsmAnd/files/9683496/telegram-cloud-document-2-5309953958800795173.mp4.zip)

### Expected result
Track navigation simulation is running

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13829mqta, released: 2022-09-30
Android/iOS version: Android 12
Device model: POCO X3 NFC

**Comment by vshcherb** [comment]
You need to start navigation cause app couldn't work in background without any navigation. So simulation will try to work and crashes
