### ISSUE TITLE
add search category for hiking parking

### ISSUE THREAD

**Issue by tiptoptom** [osmandapp/OsmAnd#15399]
# 🚀 feature request

### Description

I think it would be nice if you could easily search for hiking parking.

### Describe the solution you'd like

When searching for hiking parking you should get all [amenity](https://taginfo.openstreetmap.org/keys/amenity)=parking with [hiking](https://taginfo.openstreetmap.org/keys/hiking)=[yes](https://taginfo.openstreetmap.org/tags/hiking=yes).

### Describe alternatives you've considered

An alternative but not so handy solution would be to add a filter for hiking parking.

**Comment by tradavyvy** [comment]
👍

**Comment by vshcherb** [comment]
There are around 3 599 objects even if we support it's doubtful that people will discover that such poi type exist. It's clearly an additional filter to parking category.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14012mqta, released: 2022-12-09
4.4.1.1
Done

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/206710810-466b767c-863d-473c-8a9e-348489d83061.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/206710818-b52b82bd-9d73-4243-9b27-136174e6db04.jpeg"  width="500" height="auto"/> </th>
  </tr>
</table>

**Comment by dmpr0** [comment]
## Review
- [ ]  Don't visible on iOS Testflight build 4.4.3.1
<table style="width:100%">
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/209964663-ef02afae-fa40-4d39-9fb5-e8584dab05ce.PNG"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14106mqta, released: 2023-01-16
4.4.4.1
Done

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/212651217-494fb8c5-da08-4b16-8899-429d9c4fdca7.jpeg"  width="500" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/212651205-deccec16-972e-4fa9-ae32-5a94437a9c65.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>
