### ISSUE TITLE
osmand always shows data migration dialog but doesn't explain how to find osmand folder

### ISSUE THREAD

**Issue by RalfJung** [osmandapp/OsmAnd#15395]
### Description

Recently, osmand on my Mom's phone with Android 7 started showing the data migration dialog, but I cannot figure out how to complete that. This is with osmand 4.2.6, and it is not triggered by a recent app update -- I don't know what caused this migration dialog to suddenly show up. Given that this is Android 7, I don't think the restricted permissions on more recent Android versions should be relevant?

The dialog tells me to "find the osmand folder". It doesn't explain where to find it, so I really have no clue what I should be selecting in the file dialog. Despite having some Android experience, I don't know what it is asking for. I tried creating a new folder called "osmand" but that didn't make it happy. I also tried the `Android/data/net.osmand.plus` and `Android/data/net.osmand.plus/files` folders on both the SD card and the local storage, no luck. (The app was configured to store maps on the SD card, I think.) Right now it seems like the app is just not usable.

### How to reproduce?

I don't know, it just started happening on startup.

### Your Environment
OsmAnd Version: 4.2.6 (via F-droid)
Android/iOS version: Android 7
Device model: Motorola E4 plus

**Comment by RalfJung** [comment]
I tried updating to osmand 4.2.7 but that did not help.

**Comment by RalfJung** [comment]
Okay I think what actually happens was some kind of other error when accessing the SD-card, which osmand misinterpreted rather badly and showed that dialog. The dialog is gone after a full system reboot, and maps seem to work again. :)

However, something is still very wrong -- when I try to change the data location to a different directory and ask it to move files, that fails saying some files could not be found... but the filename it prints it cannot find is *in the new folder*, of course that file doesn't exist yet! Then it says "1 file moved (2 MB)" but that is clearly wrong, looking at the new location, the new folder has not even been created. Then I can only click "restart app", after which it does *not* restart the app but instead says that the maps could not be created in the new folder.

**Comment by vshcherb** [comment]
Yes, looks like the app  doesn't have permission for  custom location

**Comment by RalfJung** [comment]
It doesn't ask for permission either, though. It just fails with obscure error messages.

Overall this is a pretty bad user experience -- both showing that data migration dialog when something else was wrong (and got fixed by a system reboot), and the behavior when changing to a custom location on the SD card that it somehow cannot access. Your call if you want to track that as a bug :shrug:

**Comment by vshcherb** [comment]
Well yes, but that's out of the planning horizon that bug for now. We plan to disable custom location since Android 11 at all cause there is no standard phone where it works ok.
