### ISSUE TITLE
[offline rendering] highway=footway is only rendered at extrem high zoom

### ISSUE THREAD

**Issue by HolgerJeromin** [osmandapp/Osmand#1539]
Hi,
i am using an osmand-nightly.apk from the homepage and since a few month highway=footways (without bridges) are only rendered at extrem high zooms (20 m ruler is about 2 cm long in Aachen, Germany). Footways on bridges are ok.

Perhaps this is an upgrade problem, but i have it with rendering styles osmand and uniRS, but not with lightRS.

**Comment by xmd5a2** [comment]
I suppose it's because you are using car profile. Try switching to default app profile.

**Comment by HolgerJeromin** [comment]
wow. you are right. Thanks!
The footways on bridges irritated me. But for orientation (leave the street after the second foot bridge ) it seems useful.
