### ISSUE TITLE
Gray screen, does not render any details

### ISSUE THREAD

**Issue by c0ntradicti0n** [osmandapp/OsmAnd#15396]
### Description
I can see nothing, but i can find shops and busstops and locations, but no street to go there, all the country like this. how? Haven't see the change reflected in the matrix so far. Did I miss oud something?

### How to reproduce?
fresh install, download maps, nothing.
![Screenshot_20221001-094507](https://user-images.githubusercontent.com/46457469/193399044-0f7826da-bbe3-45d0-a2a1-29ac8e837124.png)

### Your Environment
OsmAnd Version: 4.2.7
Android/iOS version: 11
Device model: Ulefone Armor x10 pro

**Maps used (online or offline):**   
![Screenshot_20221001-103125](https://user-images.githubusercontent.com/46457469/193400822-44288348-e20f-4ef0-a081-bb08ec13174f.png)
all map files tried so far, multiple times.

**Comment by itzikiap** [comment]
When this happens, sometimes it helps to force quit the app and launch it again.  I think this was fixed in the dev version, not sure,  though.

**Comment by c0ntradicti0n** [comment]
I tried restarting app and phone, with versions from Playstore and a 317.95 MB APK version 4.2.7, downloading maps multiole times If you can point me to a version that works, that would be crazy.

**Comment by hansfn** [comment]
I'm experiencing the same. I just switched phone and suddenly the app stopped working.

OsmAnd Version: 4.2.7
Android/iOS version: 12
Device model: Samsung Galaxy S21

![Screenshot_20221002-171342_OsmAnd+](https://user-images.githubusercontent.com/92755/193461683-ee6bd370-3727-4286-9e5b-a6fceecebf31.jpg)

I have tried restarting the phone. What makes this even more interesting is that if I plan a route, the map is displayed. If I then stop the route and try to zoom, it's stuttering ...

![Screenshot_20221002-172043_OsmAnd+](https://user-images.githubusercontent.com/92755/193461848-6a12911f-ef84-4f47-a86d-cc2155e58351.jpg)

**Comment by vshcherb** [comment]
Please try to switch to opengl rendering in Developmnent Plugin Settings.

It's a known issue similat to Nexus Phone

**Comment by hansfn** [comment]
Thank you, @vshcherb! OpenGL resolved the issue.

**Comment by c0ntradicti0n** [comment]
Thank you too! Works.
