### ISSUE TITLE
Add More details to charging station POI

### ISSUE THREAD

**Issue by sgjf4g4** [osmandapp/OsmAnd#15403]
The tags for the Key:socket have next to "output" and "current" also "voltage". This is been shown here: https://wiki.openstreetmap.org/wiki/Key:socket#Tags

At the moment voltage is missing in the implementation: https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/res/values/phrases.xml#L3624

And that is the reason why voltage is not shown in OsmAnd when you select the POI that have been mapped like in the example here:
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcharging_station#Examples

**Comment by vshcherb** [comment]
You can create pull requests to poi_types.xml and phrases.xml if you see how it could be improved

**Comment by sgjf4g4** [comment]
@vshcherb 
I am not a developer. I just added the information about pharses.xml to hopefully help developers. I dont know if this is the only part that have to be modified. 
And i dont it get why you removed my detailed naming of the report to a useless "Add More details to charging station POI".
The first logical thing when i would read "Add More details to charging station POI" from me would be - why have this person not mentioned in the title WHAT details should be added?

And by telling that https://github.com/osmandapp/OsmAnd/issues/15404 have now also the headline "Add More details to charging station POI" is completely broken. In https://github.com/osmandapp/OsmAnd/issues/15404 at not a single point of the report there is a request to "add" something. But now it have also the headline "**Add** More details to charging station POI".
I have spend much time into being as exact and detailed as possible and in the same time not writing some endless text. You kind of ruined my reporting. Why have you done that this way? Now it does not make any logical sense any more like it did before.

**Comment by vshcherb** [comment]
Yes, links are stored and information is good. We combine issues as they are going to be fixed . Obviously I don't see any sense of spending dev / testing resources picking them 1 by 1. It looks like they are going to be fixed altogether.

**Comment by vshcherb** [comment]
Linked issues:
- https://github.com/osmandapp/OsmAnd/issues/15401
- https://github.com/osmandapp/OsmAnd/issues/15402
- https://github.com/osmandapp/OsmAnd/issues/15404

**Comment by vshcherb** [comment]
Looks like we need to add / edit the classification and filters of charging stations POI, it should be done as 1 effort and not split into 5-6 different issues cause it wouldn't make sense to spend efforts on development / testing.
If one of the merged issue won't be implemented , it will be reopened

**Comment by xmd5a2** [comment]
Done: https://github.com/osmandapp/OsmAnd/issues/15402

**Comment by xmd5a2** [comment]
Done socket:type2_cable : https://github.com/osmandapp/OsmAnd/issues/15401

**Comment by ivanPyrohivskyi** [comment]
@Dima-1 will add *.obf with new map for QA

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14026mqta, released: 2022-12-15
Done
`51.05279° N, 13.71867° E`

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/207860191-2b94a65f-ad37-4eef-bb01-96eac18e2955.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by dmpr0** [comment]
iOS
![telegram-cloud-photo-size-2-5253673652703052201-y](https://user-images.githubusercontent.com/9365308/208134771-550de349-eaf7-41fc-a4d6-289bf5e79347.jpg)
