### ISSUE TITLE
Charging station POI - Type3 - it should be split into two connector types because there is no type3

### ISSUE THREAD

**Issue by sgjf4g4** [osmandapp/OsmAnd#15402]
### Description
At the moment there is one single entry in OsmAnd and that is named type3. But there is no general type3 connector. Its either type3a or type3c. Thats why it should be split into two entries. The one should be named type3a and the other one type3c.

For further information take a look into https://wiki.openstreetmap.org/wiki/Key:socket#List_of_socket_types
And into https://en.wikipedia.org/wiki/Type_3_connector or https://en.wikipedia.org/wiki/IEC_62196#Type_3

### How to reproduce?

https://github.com/osmandapp/OsmAnd/search?q=poi_socket_type3

### Your Environment
OsmAnd Version: all recent
Android/iOS version: any
Device model: any

**Maps used (online or offline):**   
no relation

How to fix:
Link https://github.com/osmandapp/OsmAnd/search?q=poi_socket_type3 show at the moment 37 results in the codebase. It should instead show 37 results with this link https://github.com/osmandapp/OsmAnd/search?q=poi_socket_type3a and also 37 with this link https://github.com/osmandapp/OsmAnd/search?q=poi_socket_type3c

**Comment by vshcherb** [comment]
Merge to https://github.com/osmandapp/OsmAnd/issues/15403
