### ISSUE TITLE
Indonesian language in UI seems like English

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#15409]
### How to reproduce?
Try to switch **Display language** to **Indonesian** in **Menu** – **Settings** – **OsmAnd setting** – **Display language**.

#### Example string `Download maps`, 
* English string https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/res/values/strings.xml/#L2915
* Indonesian – https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/res/values-id/strings.xml/#L3615
* Weblate show 100% of translation https://hosted.weblate.org/projects/osmand/main/id/

<table style="width:100%">
  <tr>
    <th>iOS</th>
    <th>Android</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/193550087-2263a313-3d98-401c-a14d-62e19ecadd63.jpeg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/193549909-2e49edef-a00d-4b3b-bcd7-b95ea8440eab.png"  width="300" height="auto"/> </td>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/193550085-471c8e9f-17fb-48c0-8f2a-ef36261d44df.jpeg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/193549903-6b7cfa09-676a-4517-a0b3-a7b4aa8bb5cf.png"  width="300" height="auto"/> </td>
  </tr>
</table>   

### Your Environment
OsmAnd Version: 4.2.7, 4.3.0
Android/iOS version: 11

**Comment by nazar-kutz** [comment]
**Hebrew Fixes: **
 https://github.com/osmandapp/OsmAnd/commit/9d93b597504a8f203a25e8f8ba8cbaad0c30ce40 and https://github.com/osmandapp/OsmAnd/commit/b52bb674983d7b04a7d4839d9861dcd89b7c05a4
