### ISSUE TITLE
Mark and move more than one Favourtie at one time

### ISSUE THREAD

**Issue by gubrist** [osmandapp/OsmAnd#15405]
### Description

I use OsmAnd+ 4.2.7.

### Describe the solution you'd like

I want to mark (and move) more than one Favourtie at one time:

![44459375pt](https://user-images.githubusercontent.com/22197180/193460079-009ff332-6280-42d5-9d78-c3f8b8ddb967.jpg)

### Describe alternatives you've considered

This feature is already available:  if you want to mark and **delete** more than one Favourtie at one time.

This feature is already available:  if you want to mark and move **all** Favourties of a Favourite group  at one time to another Favourite group by renaming the source Favourite group name.

My request focus is on **some**  Favourties of a Favourite group,

**Comment by tradavyvy** [comment]
Sounds like a nice feature

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/16917
