### ISSUE TITLE
Charging station POI (pharses.xml) is missing a common connector type: socket:type2_cable

### ISSUE THREAD

**Issue by sgjf4g4** [osmandapp/OsmAnd#15401]
There is a common type of charging cable: The type2_cable. This are stations where you dont have to bring your own cable with you like thats the case on socket:type2 . The cable at socket:type2_cable is already attached to the station.
This is even the first example in the OSM-wiki for a charging station:
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcharging_station#Examples

But this type is currently completely missing in OsmAnd:
https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/res/values/phrases.xml

You cant filter for this type of stations 
https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/res/values/phrases.xml#L102
And you also cant even see it when you press a POI that have such a charging-cable attached to the charging station. 
https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/res/values/phrases.xml#L3645

Please add this because its really common on bigger/more expensive public charging stations.

**Comment by vshcherb** [comment]
Merge to https://github.com/osmandapp/OsmAnd/issues/15403
