### ISSUE TITLE
Charging station POI filtering - rise the DC-Charging values for "low","medium" and "high" to modern values

### ISSUE THREAD

**Issue by sgjf4g4** [osmandapp/OsmAnd#15404]
OsmAnd have a nice feature for filtering the speed of charging stations.
The values are named "high" "medium" and "low". They are implemented at the moment for
AC:
type2
type3
cee-blue
schuko

DC:
chademo
type2_combo

The implementation can be partly seen here:
https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/res/values/phrases.xml#L3809

As society we have changed in the last 10 years what we name "high","medium" and "low" in case of DC-charging. I have much contact with many people in the regular charging community and can give information what the people in 2022 are naming the charging speeds.

If you like, i can give some much deeper information about what is been seen how and why.
At the moment the values that people are expecting in general should be changed for DC-charging (in OsmAnd implemented at the moment for chademo and type2_combo) to:
**low: 29 kW and below
medium: 30 kW up to 69 kW
high: 70 kW and above**

This would represent perfectly the newer 70/75kW fast(er) DC-chargers and so on. Like i wrote i can get into detail if you like more details why the values should be set like the above ones.
This also fixes on the lower end in the OSM-data mapped DC-chargers with 22 kW instead of 20 kW. If they have really 22 kW or if this have been mistaken with the AC max charging speed where 22kW is a typical value is a different point. With the current OsmAnd implementation the 22 kW mapped chargers are shown in "medium" instead of "low" and 22kW that is by far not the expectation of the general user for "medium" DC charging speed.

**Comment by vshcherb** [comment]
Merging to https://github.com/osmandapp/OsmAnd/issues/15403

**Comment by sgjf4g4** [comment]
@vshcherb
You changed the name of https://github.com/osmandapp/OsmAnd/issues/15403 to "Add More details to charging station POI". You closed this report here and reason this with "Merging to report named "Add More details to charging station POI" ".

This completely do not make any sense. How can changing the values of "low","medium" and "high" be "more details"? I did not wrote in the report here, that for example a fourth value named "somewhat low" or something like that should be **added**. Because if i argued to add something, than you can say, that this could be named "Add More details to charging station POI". But i have not argued in this report here at any point to add something.
Also the title is now completely broken. It does not make any sense. I spend much time in writing and detecting those things. I have made many thoughts on what could be the possibly best title for the report. You kind of just broke the work i did by removing the title i have chosen, closing the report and adding a title that do not make any sense.
Please explain me why you did this.
