### ISSUE TITLE
Add Level crossing to the POI (Disappears on Zoom)

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#15412]
Level crossings are marked with a red cross on the map, but when searching by name, they are not highlighted. 
![image](https://user-images.githubusercontent.com/80623554/193586070-ec1f0286-2602-4226-a291-1bc4fcb251e1.png)
https://www.openstreetmap.org/node/2647769633#map=19/50.44305/30.46380
It will be nice if Level crossing will be available for highlighting and search like it is implemented for Highway crossings.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.3.0#13873mqta, released: 2022-10-17
POI is displayed in the search.
But, when you increase the zoom level, some of the POI are no longer shown.


https://user-images.githubusercontent.com/104760013/196126800-d02645e2-5a36-4ffb-8142-61e31b7f1011.mp4

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd/pull/15837
