### ISSUE TITLE
Full-width digits (used with Chinese text) rendered as missing glyphs

### ISSUE THREAD

**Issue by GeographicCone** [osmandapp/Osmand#1541]
**Full-width character forms** are used for numbers and punctuation embedded alongside Chinese text. [Wikipedia has the background.](https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms)

With OsmAnd, these are rendered as missing glyphs. Please see the screenshot below for illustration.

As a consequence, lane numbers cannot be read from the map of Taiwan unless the language is switched to English, which severely limits the usability of the map.

What appears to be the likely cause is that some sort of *Roboto* font is used to display the labels, and it doesn't have these glyphs encoded, in which case the application should switch to some fallback font, most likely *Droid Sans Fallback*, whenever a glyph is unavailable. (Mind you this is just a guess that might be wrong.)

Platform: Android 5.1.1 (CM Snapshot 20150806)

**Map of Taiwan in Chinese:**
*(Note the missing glyphs.)*

![screenshot chinese](https://cloud.githubusercontent.com/assets/13693118/9133917/e0473cf0-3cff-11e5-86c9-05793030232c.png)

**Same Map Area in English**
*(Numbers are rendered correctly as in this version they're regularly-sized, or half-width.)*

![screenshot english](https://cloud.githubusercontent.com/assets/13693118/9134192/34fffdf2-3d02-11e5-866f-a93e926bc192.png)

Besides the numbers, this issue also manifests itself with some of the punctuation symbols.

Thank you for looking into it.

**Comment by kcwu** [comment]
Actually, the digits in question are half-width.

With more observation, I found the problem could be summarized as

1. if the first character of the label is half-width (say, digits and punctuation symbols), all Chinese characters will be rendered as half-width (missing glyph) box.
2. if the first character of the label is Chinese, all half-width characters will be rendered as full-width (missing glyph) box.

**Comment by kcwu** [comment]
https://github.com/osmandapp/Osmand/issues/1644 has the same observation and is duped to https://github.com/osmandapp/Osmand/issues/1161

**Comment by GeographicCone** [comment]
Thank you for the follow up, **kcwu**, and for sharing your observations! It seems the issue is indeed unrelated to full-width numerals, so my initial guess was wrong.

After reading the related discussion you referenced, it appears the problem is that characters from more than one Unicode block cannot appear within a single label. Anything from within the block the first character in a label belongs to will be rendered properly, and everything else from outside that block will be shown as missing glyphs. I can't really check this at the moment but this diagnosis sounds plausible.

According to screenshots provided by others, this issue affects Arabic, Thai and Japanese Kana labels as well as the Chinese text, so perhaps, when the issue is addressed, as a test-case scenario it would be a good idea to set up a map with a couple of phony labels with some characters from each of the scripts in different permutations to make sure all of them are rendered correctly.

Someone in the comments mentioned the issue is caused by the inability to switch fonts. If that is indeed the case, perhaps setting the font to *Droid Sans Fallback* (as I suggested earlier) could still solve this issue, as that font should have the coverage of all scripts. In recent Android versions, Google switched the default font from the *Droid* family to *Roboto* so if this bug did not show up before this could be the likely culprit.

The bugs referenced above are indeed related, so please feel free to close and/or merge this issue to keep everything in one place. Thank you.

**Comment by vshcherb** [comment]
Duplicated. The issue that Skia doesn't support 2 fonts in 1 text view, so that's why it appears.

**Comment by nicolas-raoul** [comment]
Duplicate of #1161 please discuss the issue there, thanks!
