### ISSUE TITLE
Map symbols on top of overlay or transparent on OpenGL

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#15411]
Allow to control whether map symbols should be on top of overlay or transparent.

By default  "Show map symbols" - should be off and work as now (so map symbols become transparent as overlay becomes opaque). If Show map symbols is on, it always displays on top of overlay as non-transparent

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/196429082-df7c92c9-fb23-47e8-aec3-5c118a1a605b.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by ivanPyrohivskyi** [comment]
keep_map_labels_visible

**Comment by dmpr0** [comment]
Result

<table style="width:100%">
  <tr>
    <th>4.3</th>
    <th>4.2.7</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/200296950-3cf2abc2-6b5f-4720-b0f2-bed351b12e00.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/200296928-c3c7ac61-e48d-4dbd-b153-7e9182aa6048.png"  width="300" height="auto"/> </td>
  </tr>
</table>
