### ISSUE TITLE
Flooding in China on world overview map

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#15423]
<img src="https://user-images.githubusercontent.com/9365308/193808955-f6282443-b1f6-430c-b965-4dbd91c5c976.png"  width="300" height="auto"/>

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14159mqta, Released: 2023-02-08
V1 and V2
`33.73436° N, 116.74477° W`


https://user-images.githubusercontent.com/104760013/217496454-fce356e3-aa9d-44ea-9984-f61d3304f44d.mp4

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14194mqta, Released: 2023-02-22
Done
