### ISSUE TITLE
Most vegan places don't show. iOS

### ISSUE THREAD

**Issue by beatnickgr** [osmandapp/OsmAnd#15426]
Walking profile, POI overlay, search, "vegan".
=> Only restaurants, cafés and fast food with diet:vegan=yes are showing on the map. Craft, super market, health stores and other places with diet:vegan are missing.

Switch to driving profile, switch back to walking profile
=> apart of cafes, no vegan place is shown.

We expect to see at any time all places with diet:vegan=yes

OsmAnd~ 4.2.7 on LineageOS 18.1

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.3.0#13888mqta, released: 2022-10-21
**Reproduced**


https://user-images.githubusercontent.com/104760013/197229287-b4c73400-a904-478a-b56d-aa6b5f0848af.mp4

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14066mqta, released: 2022-12-31
Done

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14192mqta, Released: 2023-02-21
19.02.23 master

When searching for "Vegan" - the number of places on the map is displayed the same as on Android
When searching for "Vegan" (with a space after the word) - POIs are not displayed, although the number on Android is noticeably larger


https://user-images.githubusercontent.com/104760013/220295726-70e22203-0ad1-4040-9dd6-1b7a6edbe281.mp4


https://user-images.githubusercontent.com/104760013/220296166-59effcc6-ec07-4431-9d50-a6a1449a3581.mov

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14243mqta, Released: 2023-03-16
4.4.6.7

**iOS** - When searching for "Vegan" and "Vegan " (with a space after the word) - POIs are displayed, but the number is much smaller than on Android with the same search queries

<table style="width:100%">
    <td><video source src="https://user-images.githubusercontent.com/104760013/225592145-66d8e304-2400-446d-ab54-3d8385f72752.mp4"  width="200" height="auto"/></td>
<th><img src="https://user-images.githubusercontent.com/104760013/225592396-d72f6ef4-3545-42bd-a6bb-c3062f55e4d3.jpeg"  width="300" height="auto"/> </th>
</table>

**Comment by Zirochkabila** [comment]
4.4.7.1
Same - results in search and, accordingly, on the map are different


<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/230610310-0d486434-83f4-4d06-aa81-893c6fca9d89.jpeg"  width="500" height="auto"/> </th>
<th><img src="https://user-images.githubusercontent.com/104760013/230610319-56076986-0380-489f-b557-19a314d7c3f8.jpeg"  width="300" height="auto"/> </th>
    <td><video source src="  width="300" height="auto"/> </td>
  </tr>
</table> 

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/230610564-9bffb694-319b-4d92-8692-8f332cb90e0a.jpeg"  width="500" height="auto"/> </th>
<th><img src="https://user-images.githubusercontent.com/104760013/230610569-f3eca3d7-57c0-4843-8d6c-f38d6e05494b.jpeg"  width="300" height="auto"/> </th>
    <td><video source src="  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-iOS/commit/c5c64a73bd8efac659a6aa062fd30f892f5d2049
