### ISSUE TITLE
Navigation along track: wrong duration time

### ISSUE THREAD

**Issue by Saturo78** [osmandapp/OsmAnd#15435]
### Description
I started a bicycle navigation along a track today with both Locus and Osmand.
Osmand calculated the travel time for 10 km with 50 minutes longer than Locus.

After I then stopped the navigation and started without track directly to the destination, the time in osmand went back to a value comparable with Locus.

### Your Environment
OsmAnd Version:4.2.7
Android/iOS version:Android 11
Device model: SG S20FE

**Comment by sonora** [comment]
This is possibly the same as #15308.

**Comment by vshcherb** [comment]
Mark as duplicate to https://github.com/osmandapp/OsmAnd/issues/15308
