### ISSUE TITLE
update offline from the map view 

### ISSUE THREAD

**Issue by HolgerJeromin** [osmandapp/Osmand#1543]
If I have an online tile then the context menu has the entry "update map"  (or Karte aktualisieren in German) which reloads the visible tiles. 

It would be nice if I could have the same with the offline map. I often have no idea which data file serves this view. 
Especially in Germany, France and Netherlands there are many files per country.

**Comment by vshcherb** [comment]
Nice proposal, we put it on the plan for new context menu.
