### ISSUE TITLE
Serious bug(?): Navigating to the last waypoint before navigating to the waypoint I need.  

### ISSUE THREAD

**Issue by POTION4** [osmandapp/Osmand#1544]
Yeah, I dunno if this issue has been submitted or not, but now I am going to submit this, as this is a very serious bug(maybe): 

When you navigate, if this is your first time, it works perfectly. 
When you navigate the second time(or third), before navigating you to the waypoint this time, it navigates you to the waypoint LAST time. 
As my English is not that good, if anyone has opened this issue already, please tell me.

**Comment by vshcherb** [comment]
Not actually clear what it means, may be some screenshots could help
