### ISSUE TITLE
Hillshades turned really dark

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#15447]
Not sure if we changed this recently, I am currently traveling in really mountainous terrain and it seems that on all my recently installed devices and for all OsmAnd profiles the default transparency for the Hillshade maps is at 39%.

That produces unusable dark areas on mountain slopes. It seems that the default should be more like perhaps20% - 25%. Cannot currently check our code, maybe someone can find out what our long time default has been.

**Comment by vshcherb** [comment]
You probably use Heightmap which produces own hillshade. I don't have any other explanation related to opengl so far.

**Comment by sonora** [comment]
OsmAnd freshly installed on several devices. The maps are our regular "Hillshades", (not "Slopes"), transferred manually from previous devices. When I go to Configure map / Terrain (Hillshade), the transparency slider is set to 39%, for all app profiles. Reducing thiis to 20% produces something useful.

**Comment by vshcherb** [comment]
I see default values https://github.com/osmandapp/Osmand/commit/c4d76a6cc2f54c27e7df9d47ece0a19df35715b9#diff-16e1d0b805ce49691667b444a6c4b97aadd10c50b442a7c9f35ea0f675c09324R92
```
HILLSHADE_TRANSPARENCY = registerIntPreference("hillshade_transparency", 100).makeProfile();
		SLOPE_TRANSPARENCY = registerIntPreference("slope_transparency", 80).makeProfile();
```
100 - 39%, 80 - 31%. 

You can change it if you see it has measurable better effect https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/src/net/osmand/plus/plugins/srtm/SRTMPlugin.java#L95

**Comment by sonora** [comment]
Ok. I've tested 3 different displays in sunlight and darkness, and feel like 22% seems the limit keeping steep areas light enough to see features, while still accentuating hills in not very mountainous areas enough to make them visible. Have made the change, it feels a lot safer moving in steeper territory now. 😉

I have made the change for both hillshade and Slopes alike.

**Comment by scaidermern** [comment]
Same problem for me after upgrading from 4.2.7 to 4.3.0. Suddenly hill shading was so dark that the map became unreasonable. I had to reduce transparency from 50: to 25%. Before the upgrade everything was fine. Also, before the upgrade OpenGL was already be enabled. So there must have been some other changes causing this.

**Comment by fedcas** [comment]
> You probably use Heightmap which produces own hillshade. I don't have any other explanation related to opengl so far.

Have the same problem after I activated heightmap. How do i get rid of that? disabling hillshade dosn't work: the black shadows are produced by heightmap itself apparently, but how do I hide them?

**Comment by sonora** [comment]
This original issue here had resulted from a temporarily introduced glitch in the scale (percentage vs. hexadecimal) and was fixed again(  https://github.com/osmandapp/OsmAnd/commit/98cf68ab9de5d43dedddd8a0397089f1115d658e). It had nothing to do with the heightmap.

If you encounter an issue connected to the heightmaps, and in the latest releases of OsmAnd, you should probably open a new issue.
