### ISSUE TITLE
Issues with the map orientation button

### ISSUE THREAD

**Issue by chau-intl** [osmandapp/OsmAnd#15448]
### Description
Just below the current-profile icon there used to be a button to change between the different _map orientations_. For me it is gone. I can bring it back by rotating the map.

Another related issue is that I only have the _North up_ option, both the _compass_ and the _movement direction_ options are gone.

If I change the _Map orientation_ in the _current profile_ the _map orientation_ button is still hidden, but when rotating the map I get the option to go through the 3 map orientation modes once and then the button disappears again.

The issue both affects the normal 2D map and 2.5D OpenGL map.

### How to reproduce?
1. Start navigation.
2. Observe that the map orientation button is hidden.
3. Rotate the map.
4. Note that the map orientation button appear.
5. Click the map orientation button twice to switch to no rotation.
6. Observe that the map orientation button is gone.

7. Change the map orientation to movement direction in the current profile.
8. Observe that the map orientation is still hidden.
9. Rotate the map.
10. Note that the map orientation button appear.
11. Click the map orientation button twice to switch to compass direction.
12. Click the map orientation button twice to switch to No rotation.
13. Observe that the switch didn't have any effect.
14. Click the map orientation button twice to switch to No rotation.
15. Observe that the map switches to north up.

### Your Environment
OsmAnd Version: 4.2.7 (2022-07-13)
Android/iOS version: 11
Device model: Xiaomi Mi 9T Pro

_I am participating the the beta program in google play, but I haven't received any updates since July_.

**Comment by mikehgentry** [comment]
Configure screen -> Buttons

Set compass to always visible.

**Comment by chau-intl** [comment]
Hi @mikehgentry, thank you it works really well and sorry I'm a bit late with my reply. 

I have searched for the solution you proposed and I didn't expected `Map orientation` in the profile configuration and `Compass` in the screen configuration to refer to the same button/functionality.

@vshcherb, I'm not sure this is _completed_ since I still think there might be an issue (if `Compass` is NOT set to always visible): 

- Step 5 does not allow me to cycle through the 3 different map orientations, it only goes back to `No rotation`. This might be intentionally though.
- Step 12 doesn't seem to have any effect, while the toast message says _No rotation (North always upwards)_. Step 14 does the actual rotation of the map so that north is upwards. Is this intentionally?

**Comment by mikehgentry** [comment]
You're welcome and no worries :)

For 5, if you tap the compass several times in quick succession you can get to the other modes. It isn't perhaps as obvious as it should be, maybe making it fade out a bit slower would help.

For 12 + 14, the first tap stops the map rotating with the compass. The second reverts to North being up.

So the notification is wrong for the first one - it should be "No rotation", and only the second should be "No rotation - North always upwards." I have a feeling I read that that has been fixed in master, but not sure.

**Comment by chau-intl** [comment]
Hmm you're right about step 5 but I can't reproduce the cycle effect consistently. Wouldn't it make more sense to just be able to cycle them until north up has been reached?

For step 12 + 14 I guess it could make sense to just stop rotation even though it isn't a configurable `Map orientation` option. I will try to remember to check if the notifications has been fixed when the next beta arrives.

Thanks for elaborating!

**Comment by mikehgentry** [comment]
I'm not even 100% sure it's an intended effect, it might just be an 'undocumented feature' as it were. The usual way to change it in that case would be via 'Configure map', I suppose.

I just leave it as always visible and be done with it...
