### ISSUE TITLE
Internet connection required - false error report

### ISSUE THREAD

**Issue by pierre5018** [osmandapp/Osmand#1545]
On the blackberry 10, when attempting to use on-line tile as the map source, app falsely reports that an Internet connection is required. Internet connection works well for other uses such as downloading regional maps. 

Version osmand~ 2.1.1

![img_20150808_092327](https://cloud.githubusercontent.com/assets/5086279/9150594/90de82d0-3daf-11e5-89e9-b1f3711468c9.png)

**Comment by vshcherb** [comment]
This is an issue of Blackberry Rom, not reproducible on Android.

**Comment by sonora** [comment]
No action planned, I guess.
