### ISSUE TITLE
October map update Germany Upper Bavaria missing September changes

### ISSUE THREAD

**Issue by OsmMUC** [osmandapp/OsmAnd#15453]
### Description
It seems the October offline map update for Upper Bavaria, Germany, is missing various changes done in September.

I've noticed various changes missing, e.g. way additions and layout changes, but haven't been able to determine yet whether e.g. only a subset of changes are affected, or whether changes after a specific point in time are missing, or any other pattern.

Could be related to issue #15450, i.e. more general issue somewhere in the process of preparing the October offline map updates.

### How to reproduce?
1. Check that e.g. [way 764665045](https://www.openstreetmap.org/way/764665045) was last updated 2022-09-15T16:45:56Z (thus should be included in the October 2022 update of the offline map), and take note of the latest value of the _website_ tag (https://www.parikita.de/de/kindertagesstaetten/muenchen/lollipop/).
2. Check that the file Germany_bayern_upper-bavaria_europe.obf is dated October 1, 2022, 00:00:00 UTC:
```
[centos@ws001 OsmAndMapCreator]$ ./utilities.sh inspector ../Germany_bayern_upper-bavaria_europe.obf
Oct 09, 2022 7:32:08 PM net.osmand.osm.MapRenderingTypes initFromInputStream
INFO: Time to init poi types 140
Binary index Germany_bayern_upper-bavaria_europe.obf version = 2 edition = Sat Oct 01 02:00:00 CEST 2022
1 Map data Germany_bayern_upper-bavaria_europe - 247960418 bytes
```
[...]

3. Verify that the value of the _website_ tag of way 764665045 in the OBF file does NOT match the one from the 2022-09-15 update in OSM (see step 1 above):
```
[centos@ws001 OsmAndMapCreator]$ ./utilities.sh inspector  -vpoi -vstats -vmap -vbuildings -vaddress ../Germany_bayern_upper-bavaria_europe.obf 2> /dev/null | grep 764665045
education: kindergarten Kindergarten Lollipop Lat 48.08991 Lon 11.5223465 osmid=764665045  website='http://lollipop.paritaet-bayern.de/'
```
4. Find the way in OsmAnd using above version of the OBF file (i.e. October update), and check that, again, the URL shown in OsmAnd does not show the one from the 2022-09-15 update in OSM (see attached screenshot).

![Screenshot_20221009-194418_OsmAnd+](https://user-images.githubusercontent.com/103325443/194771776-9f4cac3a-4fcf-491e-94c5-c814959016e9.jpg)

### Your Environment
OsmAnd Version: OsmAnd+ 4.2.7
Android version: 9
Device model: Samsung Galaxy Tab 9

**Maps used (online or offline):**   
Offline: Germany_bayern_upper-bavaria_europe.obf update dated October 1, 2022, 00:00:00 UTC

**Comment by scaidermern** [comment]
This has already been reported in the Telegram channel https://t.me/OsmAndMaps/32288.

Maps will be regenerated
This will take some time.

**Comment by OsmMUC** [comment]
Yepp, just found that myself and was about to close this issue :-).

I also note that the September versions have been restored on the server, so pulling in OSM changes done since beginning of September via live update should work well enough in the meantime (for those who have access to live updates).
