### ISSUE TITLE
Other / Updated Nautical maps

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#15455]
### Description
After reorganizing **Nautical map** screen and changing map names, they appear in Download Maps > Other list.

<img src="https://user-images.githubusercontent.com/9365308/194839082-9a24c3a5-45c1-43a0-ad09-e1408fb8fd8d.png"  width="300" height="auto"/> 

### Your Environment
OsmAnd Version: 4.3.0#13859

**Comment by ivanPyrohivskyi** [comment]
https://download.osmand.net/indexes.xml

<depth type="depthmap" date="03.08.2017" size="142.1" targetsize="325.3" containerSize="148993591" contentSize="341102677" description="Depth data for Great Lakes contours" name="Great_Lakes_contours_2.depth.obf.zip" timestamp="1501746314000"/>

<inapp type="depth" date="16.03.2017" size="417.6" targetsize="880.8" containerSize="437833350" contentSize="923629910" description="Map, Roads, POI, Transport, Address data for Depth points southern hemisphere osmand ext" name="Depth_points_southern_hemisphere_osmand_ext_2.obf.zip" timestamp="1489666692000"/>

**Comment by vshcherb** [comment]
Other fixed: https://github.com/osmandapp/OsmAnd/commit/587aa2a9999ece0959f563ecacb17fbbd2b4e244
Only Greenland 3 maps left.

**Comment by xmd5a2** [comment]
Greenland fixed
