### ISSUE TITLE
[Bug] Map Tiles No More Transparent (Alpha Channel Flattened from 2022-09-20?)

### ISSUE THREAD

**Issue by Dollarius** [osmandapp/OsmAnd#15457]
I am using Strava's heatmaps as Overlay maps (source https://anygis.ru/Web/Html/Download_en?app=OsmandSqlite)
The maps have an in-built transparent layer so that even with the "Overlay transparency = 100%" set in OsmAnd, it was possible to see the main map underneath:
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/56419637/195055049-3092af2f-46a0-46fd-a297-08be2912e037.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

The in-built transparency was correctly displayed up to OsmAnd nightly of 2022-09-16.
From the nightly of 2022-09-27, the overlay maps are always flattened, so that it is not possible to naturally see the base map underneath (unless the transparency slider is set below 100%, leading to a sub-optimal view of both the base and the overlay map)
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/56419637/195056142-ef9b5563-d484-4095-8bd2-7df032718110.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

There existed sort of a "transition time" between 2022-09-20 and 2022-09-26 in which:
1. the overlay map was non-transparent (i.e., flattened) upon starting the app
2. but if opening the settings and going on any menu (i.e., "Help")
3. then upon going "back" the transparency would be correctly rendered
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/56419637/195057371-5ab4299c-db25-474b-98cc-76cb8c839efa.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

This behaviour is identical both with "OpenGL rendering" enabled or disabled (from plugins/OsmAnd development).
I am using the nightly builds of the kind
OsmAnd-master-gnb-2022-xx-yy.apk
https://download.osmand.net/night-builds/?C=M;O=D
I am running Android 12

I hope this information will help you solve this bug.
Thank you very much for your work!

**Comment by Zirochkabila** [comment]
Reproduced on OsmAnd~ 4.3.0#13869mqta, released: 2022-10-14 **without OpenGL activation**

**Comment by Zirochkabila** [comment]
Reproduced on OsmAnd~ 4.3.0#13869mqta, released: 2022-10-14
Deactivate OpenGL rendering to see the result

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.3.0#13892mqta, released: 2022-10-22
The map is still not transparent
`35.054977, 135.716776`


https://user-images.githubusercontent.com/104760013/197349240-47f6e5ea-a75f-459c-a4ae-4a6fa7638428.mp4

**Comment by ivanPyrohivskyi** [comment]
@vshcherb in OpenGL we make symbols transparent because first is rendering raster layers (even overlay) and symbols layers after.
We implemented setting option "keep_map_labels_visible" for avoid this.

**Comment by vshcherb** [comment]
Check https://github.com/osmandapp/OsmAnd/issues/15457#issuecomment-1280990198 - **Non Opengl** version it's not transparent

**Comment by Zirochkabila** [comment]
**Non OpenGL** 

https://user-images.githubusercontent.com/104760013/197715056-639f09bf-3fb4-4c99-94a9-b1833346070e.mp4

**Comment by ivanPyrohivskyi** [comment]
Need to add parameter keep_map_labels_visible. Issue https://github.com/osmandapp/OsmAnd/issues/15411
