### ISSUE TITLE
map not visibile after first installation on Motorola G22

### ISSUE THREAD

**Issue by adriespo** [osmandapp/OsmAnd#15451]
### Description
 on a brand new Motorola G22 a fresh installation of OSmAnd

### How to reproduce?
Install OsmAnd on a brand new Motorola G22

### Your Environment
OsmAnd Version:  4.2.7 2002-07-13
Android/iOS version: 12 (kernel 4.19.191-g21d6408ea00d #1 Sat Jul 30 22:34:19 CST 2022 build STA32.79-77-28-18)
Device model: Motorola G22 (SKU XT2231-2)

**Maps used (online or offline):**   
Offline Piedmont Italy 2002-09-01
![canc](https://user-images.githubusercontent.com/6150793/194770831-984b9cd5-7c07-49d3-8224-482bd35ac16d.jpg)

**Comment by TheSnoozer** [comment]
Please try to switch to opengl rendering in Developmnent Plugin Settings
https://github.com/osmandapp/OsmAnd/issues/15396#issuecomment-1264679351 / https://github.com/osmandapp/OsmAnd/issues/14947#issuecomment-1219470444?

**Comment by adriespo** [comment]
It worked. Thank you.
