### ISSUE TITLE
Android: October map of France: roads not displayed properly

### ISSUE THREAD

**Issue by dheijl** [osmandapp/OsmAnd#15450]
### Description
The October version of the France maps does not display the roads properly, sections are missing everywhere.

### How to reproduce?
View any sevtion in the France map at a zoom level below 5 km.

### Your Environment
OsmAnd Version: 4.2.7
Android/iOS version: 7.0
Device model: Samsung galaxy tab s2 (sm t810)

**Maps used (online or offline):**   offline
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date. 
France Brittany October 1 2022 and other October 1 2022 France regions.

The September maps (on another Android device) are OK.

**Comment by l33n0x** [comment]
Same problem from me.

Your Environment
OsmAnd Version: 4.2.7
Android/iOS version: 12 + 13
Device model: Samsung galaxy tab Active 3 (SM-T575) + Pixel 4a

Is there a possibility to download map from previous month in the meantime ?


![Screenshot_20221009143146](https://user-images.githubusercontent.com/25307164/194756987-e128eac3-80b8-4382-80f7-ca0fe6e6fdf2.jpg)

**Comment by pebogufi** [comment]
Two examples:
Brittany / Bretagne 
Sept 445 MB
Oct 109 MB

Bourgogne-franche-comte
Sep 480 MB
Oct 72 MB
It looks like that there is more missing than some streets.

**Comment by vshcherb** [comment]
Maps reverted

**Comment by pahervin** [comment]
I had the same issue.
I updated several maps in the same operation, and let the update work in background.

Workaround : I reloaded the maps one by one while the application remained displayed, and the maps were ok.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.3.0#13939mqta, released: 2022-11-10

https://user-images.githubusercontent.com/104760013/201142513-543dabab-8fba-4199-8392-dfb34353886c.mp4
