### ISSUE TITLE
Compass icon can be tapped while disappearing, but only if timed right

### ISSUE THREAD

**Issue by mikehgentry** [osmandapp/OsmAnd#15468]
Set the compass to be invisible when North is upwards, and rotate the map. You can double tap it and get to other rotation modes, but only if you time it right - too fast and it doesn't register. So something is wrong here - either it's not meant to happen at all, or it's too fussy.

Personally I'd be inclined to make it accept quick double taps, and probably make it fade out a bit more slowly.

ref #15448

### Your Environment
OsmAnd Version: + 4.2.7
Android/iOS version: 11
Device model: Xcover 4s

**Comment by vshcherb** [comment]
Duplicate to https://github.com/osmandapp/OsmAnd/issues/15283

**Comment by mikehgentry** [comment]
I'm not sure that's the same bug - this has nothing to do with profile switching.

I'll try to be clearer: set the compass to be invisible when North is up, then rotate the map so it appears, tap it, and it disappears again (and you'll be in North up mode). This is all expected.

If instead you rotate the map then tap it twice *at exactly the right interval* (which is tricky - second tap has to land just before it disappears), it'll still be visible, and you'll be in Movement direction mode.

If this is a feature, it's too hard to do - if you tap it twice too quickly it doesn't work (it registers as one tap, and you'll be in North up with the compass invisible again).

If it's unintended, it probably ought to be fixed at some point, because it'll lead people to think it's a feature if they trigger it by mistake, but it's too hard to do.

**Comment by vshcherb** [comment]
Yes, it has to do with animation, animation is interrupted by some actions and it doesn't end smooth rotation. Obviously one of the fix to not have animation and just changed map orientation quick but that's not good.
