### ISSUE TITLE
Misleading check mark button in address search

### ISSUE THREAD

**Issue by exploide** [osmandapp/Osmand#1546]
When using the address search, one selects Region, City, Street and Building one after another. In the respective "Search xxx incrementally" activities, one can type in the name of a street or the building number for example. To successfully select the address part, one must tap on the appeared proposal after typing a few letters. Even when you completely typed the building number and there is only this proposal left, you have to tap the proposed number below. Using the check mark button in the upper right corner does not lead to a successful selection.

I found this rather counter-intuitive. I would expect that it is fine to accept my self-typed text with the check mark button. If you say this is not reasonably feasible, it would at least replace the check mark button by a X button or something similar which indicates aborting.

**Comment by vshcherb** [comment]
Search is subject of a big change , hope we can make it in next release
