### ISSUE TITLE
Crash when opening a Wiki link from a POI's context menu

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#15467]
[exception.log.txt](https://github.com/osmandapp/OsmAnd/files/9768580/exception.log.txt)

**Comment by nazar-kutz** [comment]
Hi!
If it possible, please, share the coordinates of point that contains the problem.

**Comment by sonora** [comment]
Chances are the problem has to do with formatting or parsing blanks in URLs. Issue can e.g. be observed when tapping the link `http://it.wikipedia.org/wiki/Basilica di Santa Maria in Aracoeli` which we show on this 41.89400° N, 12.48326° E POI's context menu,l atest Italy/Lazio map.

**Comment by nazar-kutz** [comment]
**Pull Request**
https://github.com/osmandapp/OsmAnd/pull/15518

**Comment by nazar-kutz** [comment]
The problem was that the app thought it was interacting with a Wikipedia POI object, but couldn't handle clicking on the link in the usual way for this type of object.

**Comment by sonora** [comment]
Yes, true, well spotted! Thanks!
