### ISSUE TITLE
Zoom on map is reverting to fast due to parameter "map during navigation" in profile settings

### ISSUE THREAD

**Issue by jverlaan** [osmandapp/OsmAnd#15466]
### Description
Have OsmAnd+ integrated with the WunderLinq. When zooming in/out a map via the wonder wheel while navigating/following a track, the zoom is reset to the original (zoom)state within max. 3 seconds. This is to fast to have a decent look at the zoomed map.
This fast going back to the original is caused by the parameter "map during navigation". When the parameter is off then the zoom with the wonder wheel will stay to the set level.
https://osmand.net/docs/user/personal/profiles#navigation-settings
(I guess the wonder wheel has nothing to do with this as it is related to the parameter)

There should be a threshold ideally that a user can set to e.g. 20 seconds that will hold the zoom before the parameter "auto zoom by speed" will act to set the zoom speed level back.

### How to reproduce?
Set the parameter "map during navigation" to ON. While riding zoom in or out on the map. The map will reset to the original state within 3 seconds.

### Your Environment
OsmAnd Version: OsmAnd+ 4.2.7
Android/iOS version: Android 12
Device model: Nokia X20

**Maps used (online or offline):**   
Offline, but guess it will be online too.

**Comment by vshcherb** [comment]
It's 4.5 seconds (https://github.com/osmandapp/OsmAnd/blob/21fb5fb9b96c13aed68972a59fe3dc738dac042a/OsmAnd/src/net/osmand/plus/base/MapViewTrackingUtilities.java#L410).

Now https://github.com/osmandapp/OsmAnd/commit/701edf161ee843e5afa7558d1628fdfbf3e23a0d it should be using auto follow preference by default for car it's 15 seconds after manual zoom action
