### ISSUE TITLE
Cross-platform purchase

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#15463]
- [x] [cross-platform](https://osmand.net/docs/user/purchases/android#difference-between-purchases)
- [x] [How to purchase a subscription](https://osmand.net/docs/user/purchases/android#how-to-buy)
- [x] How to restore subscription on another platform
- [x]  [Storage article](https://osmand.net/docs/user/personal/storage#local-backup)

**Comment by EugeneZmeuk** [comment]
https://osmand.net/docs/user/troubleshooting/setup#cross-platform

**Comment by Zirochkabila** [comment]
[add too ](https://osmand.net/docs/user/personal/storage/#local-backup)
<details><summary>Import from file</summary>
<img width="800" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/220123490-dc6b5631-2592-470f-9f0f-441fa8307c1c.png">
</details>

**Comment by dmpr0** [comment]
> Pro Features are available for Pro subscribes. It means you need to have [OsmAnd Pro subscription](https://osmand.net/docs/user/purchases/android#prices).

Pro Features are available for [OsmAnd Pro subscription](https://osmand.net/docs/user/purchases/android#prices).
