### ISSUE TITLE
Postcodes don't seem to ever find anything, even when marked on OSM

### ISSUE THREAD

**Issue by domdomegg** [osmandapp/Osmand#1547]
On both OSM and FreeThePostcode Buckingham Palace is mapped (SW1A 1AA):
http://www.openstreetmap.org/search?query=SW1A%201AA#map=18/51.50093/-0.14113
Nothing comes up in OsmAnd.

On OSM the cafe down my street is mapped (W2 1TH)
http://www.openstreetmap.org/node/918948842#map=19/51.52459/-0.17693
Search works on OsmAnd, even gives the correct road and the two correct localities, but neither actually come up with anything - 'no buildings found'.

**Comment by rominf** [comment]
Postcode "SW1A 1AA" is not present on OpenStreetMap. The result you see is from external projects FreeThe Postcode which is not integrated into OsmAnd.

As for the second postcode, I don't see the bug. You just need to press at marker button (top right corner) and OsmAnd will show you the building.

Feel free to comment on this bug if you have another questions about postcodes.

**Comment by domdomegg** [comment]
Yep, trying it out today looks like it's fixed. I'm fairly certain the bug was present, but probably fixed now. Although I may just have been insane.

:)

**Comment by rominf** [comment]
Yes, it probably has been fixed, OsmAnd improved a lot since that time.
Speaking of postcode search, it became much faster than before. The improvement will be included in the next night build and following releases.
