### ISSUE TITLE
Hebrew characters are not recognized in an image link

### ISSUE THREAD

**Issue by itzikiap** [osmandapp/OsmAnd#15484]
### Description
When opening the details view of a poi with a link to an online image with Jennette characters, the image is not displayed, and instead the link is shown with the characters replaced by question marks. 

When choosing to edit the poi, the link in the tag is displayed with the correct characters.

### How to reproduce?
Here's a poi for example:

Location: geo:32.64201,35.06815?z=20
https://osmand.net/go?lat=32.64201&lon=35.06815&z=20

(Tap the POI)

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13836mqta, Released: 2022-10-03
Android/iOS version: Android12
Device model: Poco x3 nfc

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

Map is: israel_asia, 1 Oct 2022

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.3.0#13884mqta, released: 2022-10-20
**Reproduced**


https://user-images.githubusercontent.com/104760013/196990162-23f4959b-98ba-42a4-914d-8e6e6ae1e2cb.mp4

**Comment by Chumva** [comment]
There is an issue with the server, it returns "?" instead of Hebrew characters in the URL.

Example link https://osmand.net/api/cm_place?lat=32.642014&lon=35.06815&app=free&lang=en&osm_image=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2F3%2F34%2FIsrael_Hiking_Map_%D7%99%D7%A2%D7%A8_%D7%94%D7%A8%D7%A7%D7%A4%D7%95%D7%AA.jpeg

**Comment by Dima-1** [comment]
<details>
  <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <td><img src="https://user-images.githubusercontent.com/31807095/235848630-da83b7ab-520c-447d-8869-094aaabf98ec.png"  width="300" height="auto"/> </td>
  </tr>
</table>   
</details>

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#35889m, Released: 2023-05-04
4.4.8.4

Data isn't visible in the iOS version

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/236235113-d04c2c2e-f44f-4176-a309-b1e13eee0527.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/236235122-985dd02a-6248-4980-9e30-6039a913784f.jpeg"  width="500" height="auto"/> </th>
  </tr>
</table>

**Comment by dmpr0** [comment]
## Review
- [ ]  Doesn't work on iOS
<table style="width:100%">
  <tr>
    <th>Anroid</th>
    <th>iOS</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/236414683-4280b430-1026-445a-9f5e-65667c1a90b4.jpg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/236414897-c145387b-3532-4ac0-8a6a-8f46412f9774.jpg"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Dima-1** [comment]
Fixed on iOS
<details>
  <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/31807095/0c9b526c-5205-4f76-8cbe-e8d333c11790"  width="300" height="auto"/> </td>
  </tr>
</table>   
</details>
