### ISSUE TITLE
Areas rendered as cemetery

### ISSUE THREAD

**Issue by ermshiperete** [osmandapp/OsmAnd#15485]
### Description

Since the last map update I notice several areas rendered as cemetery. Two of them are former military areas (similar to #12721), but the third is simply alongside a river.

[50.72845, 8.06725](https://www.openstreetmap.org/#map=16/50.72845/8.06725)
![Screenshot_2022-10-15-21-17-02-82_014aeb6b5e04ee7837dcdaecc5244511](https://user-images.githubusercontent.com/181336/196005160-33f96e50-1b9c-41b9-8159-c7c148a22178.jpg)

[50.6881, 8.0383](https://www.openstreetmap.org/#map=14/50.6881/8.0383)
![Screenshot_2022-10-15-21-17-28-32_014aeb6b5e04ee7837dcdaecc5244511](https://user-images.githubusercontent.com/181336/196005161-09aba8b2-1e55-4b62-8b0f-5024596b1651.jpg)

[50.86657, 8.00587](https://www.openstreetmap.org/#map=17/50.86657/8.00587)
![Screenshot_2022-10-15-21-18-17-34_014aeb6b5e04ee7837dcdaecc5244511](https://user-images.githubusercontent.com/181336/196005165-3c64541e-fb97-413e-a22a-89c15dd26a17.jpg)

### Your Environment
OsmAnd Version: OsmAnd+ 4.2.7
Android/iOS version: Android 12 
Device model:Realme X3 SuperZoom (Realme UI v3.0)

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

Germany_nordrhein-westfalen_europe.obf (1.10.2022)

**Comment by tradavyvy** [comment]
Did you try to fully close osmand, close all background apps, clean and clear memmory in android setting, and shut off your phone and restart and then start osmand as first and only app?
Last year I had the same problem (as you mentioned 12721) and it eventualy seemed to disapear without new osmand versions or maps.
-my guess a renderer on the blink-
At this moment my military areas that where affected last year are rendering correct.

**Comment by ermshiperete** [comment]
Strange - yesterday it was suddenly working again without me doing anything.

**Comment by tradavyvy** [comment]
I think it is like a programmers easter egg.
But then more a haloween egg. ;)
