### ISSUE TITLE
Flooding of Horsens city

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15483]
### Description
When using OpenGL on the map of the city displays water.
Blue artifacts appear on the map **Denmark_central-region_europe.road** at zoom 12 2.7 and more

### Steps to reproduce
Search > 55.83479° N, 9.87870° E > zoom

### Actual result
The map shows the water

https://user-images.githubusercontent.com/104760013/195987247-eef0821e-39dd-4ac2-ac2d-dae47d42e801.mp4

### Expected result
The map is displayed without water

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13869mqta, released: 2022-10-14
Android/iOS version: Android 12
Device model: POCO X3 NFC

**Comment by Zirochkabila** [comment]
https://github.com/osmandapp/OsmAnd/issues/15150

**Comment by Zirochkabila** [comment]
Most likely via https://www.openstreetmap.org/relation/11632949#map=19/43.49949/7.05166
It is unlikely that because of this
https://www.openstreetmap.org/way/772326360#map=18/43.50038/7.05118

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/196139505-6ce570be-30be-47e0-b0ca-1355df32a594.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
https://user-images.githubusercontent.com/104760013/196139765-9a4c6f59-dea0-4901-9e86-840d30568e36.mp4

**Comment by ivanPyrohivskyi** [comment]
<img src="https://user-images.githubusercontent.com/1040293/196491604-0ac4ab5e-9d01-4016-891d-9fde49cb27fb.jpg" width="400" /> <img src="https://user-images.githubusercontent.com/1040293/196491617-e8688b10-6809-4ee3-b249-d6ff1b2c6632.jpg" width="400" />

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.3.0#13892mqta, released: 2022-10-22
Still present

`43.518105, 7.043015`

https://user-images.githubusercontent.com/104760013/197341282-c2296545-281d-46f2-a378-978dfe7dc10e.mp4

`38.488604, 14.921237`

https://user-images.githubusercontent.com/104760013/197341311-42071ebe-6e59-4132-9dde-19f810983efe.mp4

**And a new one**
`39.317046, -76.427948`

https://user-images.githubusercontent.com/104760013/197341350-5878b10f-c3f5-4561-a0d8-ba294dfd4612.mp4

**Comment by Zirochkabila** [comment]
https://user-images.githubusercontent.com/104760013/197348519-a38ccac0-9e77-4843-bd01-08daf9c2d2ab.mp4

**Comment by ivanPyrohivskyi** [comment]
Bugs with islands will fix in new November maps

**Comment by ivanPyrohivskyi** [comment]
Last opengl-arm build:
<img src="https://user-images.githubusercontent.com/1040293/197554782-ef349449-73a7-4ab2-a0b4-f5f787712333.jpg" width="400" />
