### ISSUE TITLE
Crash or hang-up when trying to 'Analyze on map' a short track that was created with the 'Plan a route' function

### ISSUE THREAD

**Issue by Max1234-Ita** [osmandapp/OsmAnd#15489]
### Description
I create a short track with the Plan a route function; Later, I go to the My places menu, show the track on the map and, in the track menu option, I select "Analyze on map": In some cases, the program crashes and I'm brought to my device's Home screen; Alternatively, nothing seems to happen, but I'm not able to select and analyse other tracks  anymore, unless I close & restart OsmAnd.
The issue happens 100% of the times with the 2 sample gpx files attached:

- with the first one (_Sat 15 Oc5 2022.gpx_), OsmAnd crashes and closes. The attached exception log is created.
- with the other one (_Sun 16 Oct 2022)_), nothing happens: the Analyse track screen does not show AND, if I try to tap a different displayed track, the _track options_ menu is not displayed as well.

### How to reproduce?
1. Start OsmAnd;
2. From the main menu, select _Plan route_ option;
3. Select _Create new route_;
4. Drag the map to the chosen Start point and click _Add_;
5. Select another point nearby (i.e. within 200 m) and _Add_ it too;
6. In the _Plan Route_ tool, select the _Options_ menu -> _Route between points_; Select a profile, i.e. _Walking_;
7. Add another couple of waypoint nearby, so that the total route length is about 500-700 meters;
8. FInish creating the track by tapping the _Done_ button in the upper-right corner of the display; the new track is saved into the _My Places_ menu;
9. Open the _My places_ menu, locate the just created track and show it on the map;
10. From the track menu, in the bottom of the display, tap _Options_ and select Analyze on map;

### Your Environment
OsmAnd Version:    OsmAnd+ v. 4.2.7
Android/iOS version: Android 11
Device model:  Samsung Galaxy A50 (SM-A505FN/DS)

**Maps used (online or offline):**   Offline Standard maps (the 20 Italian regions, plus Ireland, North of France and Greece)
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

[Sample_GPX_files.zip](https://github.com/osmandapp/OsmAnd/files/9795013/Sample_GPX_files.zip)
[exception.log](https://github.com/osmandapp/OsmAnd/files/9795033/exception.log)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.3.0#13884mqta, released: 2022-10-20
**Reproduced**

[Crash Sat 15 Oct 2022.log](https://github.com/osmandapp/OsmAnd/files/9830971/Crash.Sat.15.Oct.2022.log)
[logcat Sun 16 Oct 2022.log](https://github.com/osmandapp/OsmAnd/files/9830972/logcat.Sun.16.Oct.2022.log)
