### ISSUE TITLE
The name of the city in Persian is not shown on the map

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15482]
### Description
The name of the city (Salmas) in Persian (سلماس) is not shown on the map
https://www.openstreetmap.org/node/180544443#map=13/38.1969/44.7744 **The city is added**
https://osmand.net/map/?end=38.676808%2C15.897388&mode=truck#14/38.2046/44.7756 **The city isnʼt added**

### Steps to reproduce
Search > Salmas > It's shown

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/195983537-f9648c95-57ef-497d-b4ac-317c66499529.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

Search > سلماس > Isn't shown

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/195983580-4420939a-f7a1-4452-b723-ea61dd31ab27.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Actual result
The name of the city in Persian is not shown on the map

### Expected result
The name of the city in Persian is displayed in the same way as in English

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13869mqta, released: 2022-10-14
Android/iOS version: Android 12
Device model: POCO X3 NFC

**Comment by tommyjim** [comment]
The following list includes some of the Iran's cities that are affected by the same issue:

- [Tehran (تهران)](https://www.openstreetmap.org/node/25960293)
_Additional comment: The name of the city is not shown on the top results both in Persian and English._
- [Mashhad (مشهد)](https://www.openstreetmap.org/node/26038568)
- [Tabriz (تبریز)](https://www.openstreetmap.org/node/26038590)
_Additional comment: The name of the city is not shown on the top results both in Persian and English._
- [Mehestan (مهستان)](https://www.openstreetmap.org/node/821096768)
- [Shiraz (شیراز)](https://www.openstreetmap.org/node/26082452)
- [Urmia (ارومیه)](https://www.openstreetmap.org/node/26399215)
_Additional comment: The name of the city is not shown on the top results both in Persian and English._
- [Karaj (کرج)](https://www.openstreetmap.org/node/234526006)
_Additional comment: The name of the city in English is not shown on the map._
- [Isfahan (اصفهان)](https://www.openstreetmap.org/node/26038567)
_Additional comment: The name of the city is not shown on the top results both in Persian and English._
- [Hashtgerd (هشتگرد)](https://www.openstreetmap.org/node/791254167)
- [Kerman (کرمان)](https://www.openstreetmap.org/node/32677945)
- [Varamin (ورامین)](https://www.openstreetmap.org/node/3248971788)
_Additional comment: The name of the city is not shown on the top results both in Persian and English._
- [Abadan (آبادان)](https://www.openstreetmap.org/node/32826329)
- [Abhar (ابهر)](https://www.openstreetmap.org/node/820252479)
- [Eshtehard (اشتهارد)](https://www.openstreetmap.org/node/806942842)
- [Izeh (ایذه)](https://www.openstreetmap.org/node/3067837120)
- [Bandar Abbas (بندرعباس)](https://www.openstreetmap.org/node/4736094012)
- [Birjand (بیرجند)](https://www.openstreetmap.org/node/32677634)
- [Piranshahr (پیرانشهر)](https://www.openstreetmap.org/node/181296509)
- [Takestan (تاکستان)](https://www.openstreetmap.org/node/666772583)

**Comment by vshcherb** [comment]
This screenshot looks weird I guess we don't support proper transliteration for persian now, so I wouldn't use transliteration feature for persian.

![image](https://user-images.githubusercontent.com/1042025/196951088-79776102-e28a-40c2-a938-a4e77e631cbc.png)
