### ISSUE TITLE
place=state names does not appear as expected

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1549]
This code works as expected:
```xml
<switch minzoom="5" textSize="13" textColor="#9d6c9d" textWrapWidth="20">
  <case maxzoom="5" tag="place" value="state">
    <case nameTag="ref" textOrder="3"/>
  </case>
  <apply_if nightMode="false" textHaloRadius="$textHaloRadiusDay" textHaloColor="#88ffffff"/>
</switch>
```
But this not:
```xml
<switch minzoom="5" textSize="13" textColor="#9d6c9d" textWrapWidth="20">
  <case maxzoom="5" tag="place" value="state" nameTag="ref" textOrder="3"/>
  <apply_if nightMode="false" textHaloRadius="$textHaloRadiusDay" textHaloColor="#88ffffff"/>
</switch>
```
This affects zoom 5 (states refs).

**Comment by vshcherb** [comment]
New utilities are added: 
generate-java-style and explain-rendering-style (MainUtility class).

**Comment by vshcherb** [comment]
First generates
place : stateEEE
  test [ maxzoom= 5 minzoom= 5] set [ textWrapWidth= 20.0 textColor= #9d6c9d textSize= 13.0]
    * case  test [ nameTag= "ref"] set [ textOrder= 3]
    * apply  test [ nightMode= 0] set [ textHaloRadius= 0.0 textHaloColor= #88ffffff]


Second generates:
place : stateEEE
  test [ maxzoom= 5 nameTag= "ref" minzoom= 5] set [ textWrapWidth= 20.0 textColor= #9d6c9d textSize= 13.0 textOrder= 3]
       * apply  test [ nightMode= 0] set [ textHaloRadius= 0.0 textHaloColor= #88ffffff]

**Comment by vshcherb** [comment]
This code generates expected output and much simpler
<case minzoom="5" textSize="13" textColor="#9d6c9d" textWrapWidth="20" tag="place" value="stateEEE">
    		<case nameTag="ref" textOrder="3"/>
  			<apply_if nightMode="false" textHaloRadius="$textHaloRadiusDay" textHaloColor="#88ffffff"/>
		</case> 

place : stateEEE
  test [ minzoom= 5] set [ textWrapWidth= 20.0 textSize= 13.0 textColor= #9d6c9d]
 * case  test [ nameTag= "ref"] set [ textOrder= 3]
 * apply  test [ nightMode= 0] set [ textHaloRadius= 0.0 textHaloColor= #88ffffff]

**Comment by vshcherb** [comment]
```xml
<switch minzoom="5" textSize="13" textColor="#9d6c9d" textWrapWidth="20" tag="place" value="stateEEE">
    		<case nameTag="ref" textOrder="3"/>
  			<apply_if nightMode="false" textHaloRadius="$textHaloRadiusDay" textHaloColor="#88ffffff"/>
		</switch>
```

```
place : stateEEE
 switch test [ minzoom= 5] set [ textWrapWidth= 20.0 textSize= 13.0 textColor= #9d6c9d]
 * case  test [ nameTag= "ref"] set [ textOrder= 3]
 * apply  test [ nightMode= 0] set [ textHaloRadius= 0.0 textHaloColor= #88ffffff]
```

**Comment by vshcherb** [comment]
Works as expected, clarification of the issue itself is welcome.
