### ISSUE TITLE
editing actions

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#15490]
# 🚀 feature request

allow sorting the already set actions. a new action is always set to last position and cannot be moved to another place.   
actions can only be set or deleted.

### Describe the solution you'd like

drag and move?

### Describe alternatives you've considered

none

![Screenshot_20221016_174153_OsmAnd+](https://user-images.githubusercontent.com/95540936/196046018-76a39bf7-68b6-43b2-90bd-81b646e7e978.jpg)

**Comment by scaidermern** [comment]
It is already possible to change their order. Go to configure screen / quick action.

**Comment by Rowin63** [comment]
Puh, this functionality is well hidden, where I did not expect it to be. 
I was searching forsomething else and found it coincidentally...
