### ISSUE TITLE
Add filter "Toilets with shower"

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15500]
### Description

Add filter "Toilets with shower"
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtoilets#:~:text=shower%3Dyes%20%E2%80%93%20The%20toilet%20is%20also%20equipped%20with%20a%20shower

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14012mqta, released: 2022-12-09
[Map](https://drive.google.com/file/d/1tXwdEhA6bFeCMq1oOXknkKg-eUpn18R1/view?usp=sharing)

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/206699492-2516df69-543c-4434-b742-c67e3d9a7149.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by dmpr0** [comment]
# Review
Filter screen, both on Android and iOS user icon with shower for filter, but context menu use default "info" icon.
Why item in context menu, don't find/relate to the same icon?

<table style="width:100%">
  <tr>
    <th>Context Menu iOS</th>
    <th>Context Menu Android</th>
    <th>Filter</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/207291180-d53f6c7e-7c35-48a2-9e95-f116e4dee2ae.jpg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/207291340-bc77d76c-3227-4be5-9914-5118e1b86766.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/207291544-70a64273-ade4-470f-9d45-50b660523113.jpg"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
4.4.2.0
OsmAnd~ 4.4.0#14037mqta, released: 2022-12-21
Icon in the context menu is displayed as "info", not as "shower" [Map](https://drive.google.com/file/d/1ObeMj2ftKuoTsGsUzo-36_hsshaQgXNw/view?usp=sharing)


`51.34419° N, 12.38218° E`

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/208876383-56c61ff8-36a2-4192-9f4f-f8ae292283dd.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/208876390-70089246-b41d-4513-bf24-0b6d6c32c64d.jpeg"  width="500" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
4.4.2.1
OsmAnd~ 4.4.0#14043mqta, released: 2022-12-23
`51.34419° N, 12.38218° E`
[Map](https://drive.google.com/file/d/1h49Y0yTR5yTMOx5qdI_KGAecR0RJ-iMn/view?usp=sharing)

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/209337106-5d94442e-74f5-49c8-b77d-74505ca07b60.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/209337113-8cccad51-a7d2-4ed2-855f-9e99145c3f81.jpeg"  width="500" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/pull/16252/files - doesn't look generic and not in generic place.

**Comment by Zirochkabila** [comment]
`51.34419° N, 12.38218° E`
[Map](https://drive.google.com/file/d/1HGBMeTr880OcS_W2Z4a_yqfL2f7eC-vi/view?usp=sharing)

OsmAnd~ 4.4.0#14154mqta, released: 2023-02-05 - **Done**
<details>
  <summary>Android</summary>
<img width="384" alt="Screenshot 2023-02-05 at 15 55 25" src="https://user-images.githubusercontent.com/104760013/216823841-cc202d08-fbcf-406b-9791-c0406f76029f.jpeg">
</details>

iOS master branch - **shower icon isnʼt displayed**
<details>
  <summary>iOS</summary>
<img width="384" alt="Screenshot 2023-02-05 at 15 55 25" src="https://user-images.githubusercontent.com/104760013/216823829-d6cab6f4-9c00-4a18-808c-07e7f87e87ad.png">
</details>

**Comment by dmpr0** [comment]
## Review
Tested on Master branch.

<table style="width:100%">
  <tr>
    <th colspan=2>Shower</th>
  </tr>
  <tr>
    <th>Android</th>
    <th>iOS</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/217208324-f7b08a63-18c3-4388-88f6-2dda78d9671c.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/217208179-e95bbbb9-8eff-4341-ae2c-07fb84ce4c05.PNG"  width="300" height="auto"/> </td>
  </tr>
</table>   

<table style="width:100%">
  <tr>
    <th colspan=2>Drinking water</th>
  </tr>
  <tr>
    <th>Android</th>
    <th>iOS</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/217208349-73299484-48d0-4ee2-a4fd-3930070fadad.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/217208185-7d3887ea-5109-47a1-a9b9-d8668046763b.PNG"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
24.02 master
<details><summary>Done</summary>
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/221221016-dd90d2ce-50f9-4ba7-8492-011a09d8e3b9.png">
</details>
