### ISSUE TITLE
Make alt_name:en searchable

### ISSUE THREAD

**Issue by Breen5** [osmandapp/OsmAnd#15504]
`alt_name` is searchable but `alt_name:en` is not. 

**Example** 
https://www.openstreetmap.org/node/8250113339
* `alt_name:en=Liberty Osaka`
This can not be found. 

* `alt_name:en` should also be displayed when app language is English.
Currently alt_name is displayed.

**Comment by ivanPyrohivskyi** [comment]
Check if tag alt_name:en is present in the map data

**Comment by xmd5a2** [comment]
> Check if tag alt_name:en is present in the map data

alt_name:en isn't present in POI and map data

**Comment by Dima-1** [comment]
Location ```34.6737875, 135.4637888```
[Test map](https://github.com/osmandapp/OsmAnd/files/10967208/Osaka_map.zip)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#35809m, Released: 2023-04-18, 19.04 Master
Search works on a test map

The difference is this:

1. The order of search results is different 
2. The POI icon is not displayed on the map, on the iOS version, after clicking on the search result

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/233022664-cdc24957-df6f-4077-bc32-9fb97369bd7f.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/233022715-ef8c3c69-4ae5-40be-ac3d-068fcbe54f67.png"  width="300" height="auto"/> </th>
  </tr>
</table>  


<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/233022667-37317b2b-c9f8-4a48-8761-1283597edf8d.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/233022722-a7d03b20-f401-4559-bf04-50708c05be4c.png"  width="300" height="auto"/> </th>
  </tr>
</table>
