### ISSUE TITLE
WhatsApp location is interpreted as (0;0)

### ISSUE THREAD

**Issue by GaidamakUA** [osmandapp/Osmand#1550]
If you send location via WhatsApp, it is misinterpreted.

**Comment by vshcherb** [comment]
Can you please specify which URI is used

**Comment by GaidamakUA** [comment]
https://maps.google.com/maps?q=loc:50.453213,30.4878319

**Comment by rodrigorega** [comment]
I get 0,0 too if I open a WhatsApp location message, I am using OsmAnd 2.1.1.

**Comment by mist-01** [comment]
I can confirm the problem with WhatsApp location messages.  It seems happen every time with OsmAnd 2.1.1

**Comment by utack** [comment]
Would be great to have a fix for this in the next stable release

**Comment by vshcherb** [comment]
It will be.

**Comment by naoliv** [comment]
It is not fixed.
I tested right now and I still see the same problem.
The received URL was:

`https://maps.google.com/maps?q=loc:-21.979653,-47.8803802 (LG Brainz)`

Note that `LG Brainz` is the contact name and [testing for "(You)"](https://github.com/osmandapp/Osmand/blob/dd80992edd5d20dd99bf9b8138d76dacb58892e8/OsmAnd-java/src/net/osmand/util/GeoPointParserUtil.java#L393) will always fail.

It should use a more relaxed test (with a regex, maybe), to catch any string after the coordinates.

**Comment by GaidamakUA** [comment]
@naoliv Thank you for your suggestion. New test was added and search for " (You)" was replaced with search for regular expression "\\s\\((\\p{IsAlphabetic}|\\s)*\\)$". Hope it is good enough.

**Comment by naoliv** [comment]
Now it's giving this error:

![Error](http://i.imgur.com/p2FCnlO.png)

**Comment by vshcherb** [comment]
Added failing test https://github.com/osmandapp/Osmand/commit/a705891a81fc94fcb846513fe7c60fc9fc112b43

**Comment by GaidamakUA** [comment]
Sorry about that, the problem was with regexp. For some reason "\p{IsAlphabetic}" is not supported by android but supported by Java, so it was replaced with "\p{L}". Now everything should be working.

**Comment by naoliv** [comment]
Very good! Thank you!
