### ISSUE TITLE
Stop rendering highway=proposed

### ISSUE THREAD

**Issue by cmeeren** [osmandapp/Osmand#1551]
Ways tagged with highway=proposed only add noise in the app and are not useful for any navigation purpose (per definition, these roads do not exist in real life yet as construction has not started).

For further discussion, see https://github.com/gravitystorm/openstreetmap-carto/issues/1654

**Comment by aceman444** [comment]
OsmAnd is not only about navigation. But I would support making proposed features a toggleable option e.g. in the "Hide" submenu.

**Comment by jkufner** [comment]
Objects under construction are very important, if you are about to walk thru the area.

Proposed objects which exist only on paper should be rendered, because construction may start anytime soon (or not) and usually Osmand does not know in which stage the construction is.

**Comment by cmeeren** [comment]
I agree objects under construction are important. But there is absolutely no guarantee proposed ways will be built. Making proposed features toggleable seems like a good option to me.

**Comment by xmd5a2** [comment]
Fixed. Added option to "Hide" category.
