### ISSUE TITLE
After activating/deactivating Heightmap, the widgets on the main screen become transparent

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15524]
### Description
After activating/deactivating Heightmap, the widgets on the main screen become transparent

Workaround: When geolocation is activated, this bug **isnʼt reproduced**

### Steps to reproduce
Menu > Plugins > OsmAnd development > Settings > Heightmap enable/disable > Go to main screen

### Actual result
Widgets on the main screen become transparent

https://user-images.githubusercontent.com/104760013/196997398-11afb5dd-1a20-461f-818f-e165b45b53fd.mp4

### Expected result
Widgets on the home screen keep the same background as before

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13884mqta, released: 2022-10-20
Android/iOS version: Android 12
Device model: POCO X3 NFC

**Comment by vshcherb** [comment]
Minor issue disappearas when movement happens
