### ISSUE TITLE
Vegan pastries

### ISSUE THREAD

**Issue by beatnickgr** [osmandapp/OsmAnd#15522]
Open the search
Type "pastry shop"
Open the filters
We expect to see filters for "vegan=yes" and "vegan=only"
Thank you!!

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14028mqta, released: 2022-12-16
Done

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/208101955-9f439526-8ca0-4758-9d2d-469fdc23cdf1.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>
