### ISSUE TITLE
Depth contour lines aren't displayed when OpenGL rendering is activated

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15529]
### Description
Depth contour lines aren't displayed when OpenGL rendering is activated

### Steps to reproduce
Activate depth contours display (Nautical plugin enabled > Downloaded maps Depth gulf Mexico north-west, Nautical depth contours, Southern hemisphere nautical depth points, Guadeloupe > Boat profile > Nautical depth contours enabled ) > Enable OpenGL > Restart application

### Actual result
Depth contour lines aren't displayed

https://user-images.githubusercontent.com/104760013/197180401-4f99405e-33f5-45a2-8f15-a67f2c81d2b8.mp4

### Expected result
Depth contour lines are displayed on the map when OpenGL enabled

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13888mqta, released: 2022-10-21
Android/iOS version: Android 12
Device model: POCO X3 NFC

**Comment by ivanPyrohivskyi** [comment]
<img src="https://user-images.githubusercontent.com/1040293/198058563-020c4a8c-9901-4841-8f7c-ecfecd1af6ad.png" width="400" />
