### ISSUE TITLE
The line widget is not displayed on the map when navigating the track

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#15539]
### Description
If navigating by track the navigation lines widget does not display on the map. Tested on the Driving profile. 
<table style="width:100%">
  <tr>
    <th>Normal navigation</th>
    <th>Navigation by track</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/80623554/197331101-4c7720ee-9b3f-4db3-b0d2-537c8371a1ff.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/80623554/197331110-7cd83100-d26d-4b3b-92e9-1b6f6a27364e.png"  width="300" height="auto"/> </td>
  </tr>
</table>   

### How to reproduce?
1. Create track for example this [Sat 22 Oct 2022.gpx.zip](https://github.com/osmandapp/OsmAnd/files/9843953/Sat.22.Oct.2022.gpx.zip)
2. Enable the Lanes widget for the Driving profile
3. Select the Driving profile and simulate navigation by track (the track was attached to the road)-> you will see that the lanes widget is not displayed.
4. If you create Navigation by manually selecting Destination point the lanes widget will be displayed.

### Your Environment
OsmAnd Version: 4.2.7
Android/iOS version: Android 9
Device model: Sony Experience XZ 1

**Maps used (online or offline):**   offline 
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by vshcherb** [comment]
Check the track it doesn't have lanes information

**Comment by anastasiia936** [comment]
How to add lines information to the track? Even if the track is snapped to the road the lines do not display. 
[Sat 22 Oct 2022 (2).gpx.zip](https://github.com/osmandapp/OsmAnd/files/9867355/Sat.22.Oct.2022.2.gpx.zip)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.3.0#13902mqta, released: 2022-10-26
**Not reproduced**
It's all about Sat 22 Oct 2022 - doesn't contain turns data.
Like these
<img width="973" alt="Screenshot 2022-10-26 at 18 21 35" src="https://user-images.githubusercontent.com/104760013/198067330-58ee6fff-539b-463f-b8d4-c94cb5a30933.png">
