### ISSUE TITLE
Support retrieving multiple locations via API

### ISSUE THREAD

**Issue by tmerten** [osmandapp/Osmand#1553]
I hope I did not miss that you already implemented this :-/.

Especially in geocaching it is often desirable to hand multiple locations (e.g. destination + waypoints) to a map instead of just one.
However, I don't know if there is a "Standard Android Interface" for this task, since most maps seem to offer a single location on startup, only.

E.g. c:geo seems to support this for locus and maps.me. I would love to see this feature together with OSMand somewhen. An according API could of course be used by many apps... 
See https://github.com/cgeo/cgeo/issues/5024 as a reference. The linked commit shows, how they use the maps.me implementation of such an interface.

**Comment by vshcherb** [comment]
With OsmAnd such integration will be better done via GPX file, so if cgeo could create a special gpx file in osmand/tracks that would solve the issue. Or even generate that file on the flight and open it.

**Comment by tmerten** [comment]
Thank you for the info. I will forward this.
