### ISSUE TITLE
Coordinates widget RTL

### ISSUE THREAD

**Issue by abdullahO2** [osmandapp/OsmAnd#15538]
### Description
There is a problem in Coordinates widget when Arabic is the system language, and it becomes affected by the direction of the text and it is not supposed to be from right to left, so please can you make it unaffected by the language and text direction.

### How to reproduce?
when Arabic is the system language.

### Your Environment
OsmAnd Version: 4.2.7
Android/iOS version: Android 10
Device model: Samsung 10 plus
default:
![Nox_eR8GOA6Pl1](https://user-images.githubusercontent.com/61907628/197330510-fe0352b6-49b6-43e2-ac2b-9c659d2d7aee.png)
when Arabic is the system language:
![Nox_dSMgTh88h9](https://user-images.githubusercontent.com/61907628/197330524-736673a4-1982-48a0-b8cd-741fa75717eb.png)

**Comment by dmpr0** [comment]
Hi!
We show coordinates in the same order in context menu too https://github.com/osmandapp/OsmAnd/issues/11212
