### ISSUE TITLE
Direction arrows aren't displayed on the route

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15544]
### Description
When building a route through the Plan a route, provided that the route is longer than one kilometer, direction arrows aren't displayed on the route

### Steps to reproduce
Menu > Plan a route > Create new route > Add start and finish points > Done > Select GPX > Appearance > Direction arrows 

### Actual result
Direction arrows aren't displayed 

https://user-images.githubusercontent.com/104760013/197396240-7e74706d-9027-4cd4-951c-27bb93c08f73.mp4

### Expected result
Direction arrows are displayed (4.2.7)

https://user-images.githubusercontent.com/104760013/197396323-1311cf44-ebb4-4031-bbbb-f3f0f3e58d0d.mp4

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13893mqta, released: 2022-10-23
Android/iOS version: Android 12
Device model: POCO X3 NFC

**Comment by ivanPyrohivskyi** [comment]
Fixed bugs
"Compression" of arrow icons:
<img src="https://user-images.githubusercontent.com/1040293/198555306-ec79b3db-a917-4de9-a5a9-f076748d52d1.jpg" width="400" />

Size of arrow icons (to issue https://github.com/osmandapp/OsmAnd-Issues/issues/1057):
On OpenGL quality is worse
<img width="400" src="https://user-images.githubusercontent.com/1040293/198556464-49fe8c20-4ecf-4208-8c35-efc9ae10b171.png" /> <img width="400" src="https://user-images.githubusercontent.com/1040293/198556466-c281073b-ac71-45d2-8a5a-086224dbbc71.png" />

**Comment by ivanPyrohivskyi** [comment]
Bug described in this task I can not reproduce.
Possible problem is a different algorithm of offset and counting arrow icons.
On Legacy start from finish, on OpenGL is begin from start. Explain:
<img src="https://user-images.githubusercontent.com/1040293/198558776-076ed1c5-ad61-41a5-a141-aa31de268f16.jpg" width="500" />
