### ISSUE TITLE
Favourites: UX minor improvement

### ISSUE THREAD

**Issue by massic80** [osmandapp/Osmand#1554]
Hi!
Recently they moved the office where I live in another place and I'm used to go there by "testing" OsmAnd. I modified favourites entry for my workplace overwriing it with new location but recently used section of the dashboard still shows me old location with the same name.
I know that it's an history entry and not a favourite, but having them somehow "tied together" or having something like the recently used list updated when a favourite is updated would help someone in a hurry (history is above favourites in the dashboard) to be guided to the wrong place :)

**Comment by vshcherb** [comment]
Yes, it is annoying, the way how it is stored and operated it could be a massive change. We are going to redesign search and recents so it could help to avoid that nuance

**Comment by massic80** [comment]
Thanks!
