### ISSUE TITLE
Show vhf for leisure=marina

### ISSUE THREAD

**Issue by PanderMusubi** [osmandapp/OsmAnd#15556]
# 🚀 feature request

### Description

Show vhf for leisure=marina

### Describe the solution you'd like

Show under the name of a marina where address info etc is shown, the value of key vhf for leisure=marina to easily contact that harbour via marine VHF radio. Note, this not shown on the nap but info of the marina.

See also https://wiki.openstreetmap.org/wiki/Key:vhf

### Describe alternatives you've considered

N/a

**Comment by xmd5a2** [comment]
Already supported and is not reproducible. Please provide exact coordinates of such objects (or OSM link).

**Comment by PanderMusubi** [comment]
By the way, I have added a picture to OSM Wiki regarding this. https://wiki.openstreetmap.org/wiki/Key:vhf

**Comment by xmd5a2** [comment]
I've seen this. I mentioned **a link to OSM object or coordinates** and screenshot illustrating the issue.

**Comment by PanderMusubi** [comment]
This case it isn't a marina but a [lock](https://wiki.openstreetmap.org/wiki/Key:lock). Examples are:
- https://www.openstreetmap.org/way/162762330
- https://www.openstreetmap.org/way/162762328
- https://www.openstreetmap.org/way/99530935

**Comment by xmd5a2** [comment]
Issue is complex:
- [ ] No POI for a **lock**
- [ ] Not possible to select object of geometry type *way* from the map
First issue is solved. POI will be available in June maps. Second is harder to solve but you can enable POI of type **Lock** and tap in on the map.

**Comment by vshcherb** [comment]
@xmd5a2 you can still can have icons on a way (center point), clicking icon on a way should select way similar to polygons (I expect)

**Comment by xmd5a2** [comment]
Icons added using `textShield` but for some reason in OpenGL engine [textDy](https://github.com/osmandapp/OsmAnd-resources/commit/c05440a783545b7c8a8bddea9ea8a2245a2fcf65#diff-0852b71c561b1f6c13dc242f3a4f872e88c3897c0817248d40ecc8d378e01b3bR4803) doesn't work. This results in displaced name in OpenGL. New maps are required.
**V1:**
![Screenshot_2023-05-12_14-02-53](https://github.com/osmandapp/OsmAnd/assets/5829014/890a1d3b-a693-43b2-a000-486c5f1b8d6c)

**OpenGL:**
![Screenshot_2023-05-12_13-55-35](https://github.com/osmandapp/OsmAnd/assets/5829014/786cd122-0c12-464c-ac07-3bf19249693e)
