### ISSUE TITLE
First segment of the route line disappears while zooming/panning in motion

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#15557]
This is observed with non Open-GL: To reproduce, follow a calculated route but do not start the turn-by-turn mode, i.e. simply start driving after the route appears. **While in motion** pinch-zoom out and pan a bit, like to check something on the map. Then tap the My Position button to center the map again. The first segment of the route line will dissappear. (You may still see the turn arrows we superimpose on the route line at crossroads.)

The situation may later recover, possibly when you enter a new route segment.

This is a regression, don't think we had this issue back in e.g. versions 4.0x.

**Comment by Zirochkabila** [comment]
Manage to reproduce **on the fifth attempt**
OsmAnd~ 4.3.0#13902mqta, released: 2022-10-26
**OpenGL is disabled**
[Koyot.gpx.zip](https://github.com/osmandapp/OsmAnd/files/9869956/Koyot.gpx.zip) or create GPX that has two or more segments
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/198040097-086579e4-5359-4886-9602-10b48e9a726f.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/198040103-a6b82359-14f1-4e85-8d78-d2ec93ddfbf6.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by sonora** [comment]
PS: To reproduce you  to follow the calculated route. As soon as you have deviated, the route is recalculated and displayed completely again.
