### ISSUE TITLE
Option to automatically remove destination

### ISSUE THREAD

**Issue by massic80** [osmandapp/Osmand#1555]
Hi all,
it's me not finding it or an option to automatically remove the destination when journey is over is still needed in OsmAnd.
I personally hate having to remove that useless flag from the map anytime I reach the end of a route.

**Comment by romavor** [comment]
I vote for this change.To me, it doesn't make any sense to keep the finish flag "saved" when I reach it.

**Comment by sonora** [comment]
We have popup-options now to overwrite the old destination when a new one is selected. And until hen, having the old dest still is no harm, but can greatly help if you had just prepared this for later use but have not started your trip yet (like e.g. while still sitting at a restaurant before continuing your trip.).
