### ISSUE TITLE
Car navigation : ask to leave main road for few meters

### ISSUE THREAD

**Issue by letypequividelespoubelles** [osmandapp/OsmAnd#15561]
### Description
The OsmAnd offline car router asks to leave maine road and then make a U turn, which is very not optimal. 

### How to reproduce?
From [this point](https://www.openstreetmap.org/node/5241188242) to [this point](https://www.openstreetmap.org/node/7831826268), Osmand asks to do a U-turn [there](https://www.openstreetmap.org/node/30782140) instead of going straight. The maxspeed on the primary and secondary way are the same. 

### Your Environment
OsmAnd Version: 4.2.6 from F-Droid
Android/iOS version:
Device model:

**Maps used (online or offline):**   
Same issue with Offline + live and just offline.

**Comment by Zirochkabila** [comment]
@letypequividelespoubelles Try to update the application as well as the map. If necessary, reset the profile settings to default.

If the behavior repeats please add:
1. A short video and screenshots where we could see the error
2. Logcat file: Menu > Help > Send logcat log

**Comment by letypequividelespoubelles** [comment]
4.2.7 is  not recommanded by F-Droid and is indeed too slow with a lot of map freeze on my phone, I'll wait for 4.4.x and update the issue. Thanks

**Comment by Zirochkabila** [comment]
@letypequividelespoubelles can this issue be considered closed?

**Comment by letypequividelespoubelles** [comment]
Not really, but I'll wait next update of the app and reopen it if needed.

**Comment by Zirochkabila** [comment]
[OsmAnd](https://osmand.net/map/?start=45.856855%2C5.950014&end=45.854594%2C5.951275&mode=car#17/45.85658/5.95098)

<img width="1126" alt="Screenshot 2022-11-02 at 16 27 21" src="https://user-images.githubusercontent.com/104760013/199515647-efec195d-8485-47f1-a1a4-1114a670d5de.png">


OsmAnd~ 4.3.0#13916mqta, released: 2022-11-02

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/199516014-859b6c33-114a-4077-a887-c6c853a14882.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>
