### ISSUE TITLE
Favorities saving mechanizm

### ISSUE THREAD

**Issue by SimonWhite** [osmandapp/Osmand#1556]
Can you tell me why did you chose to files over db? what are yours arguments? Thank you :)

**Comment by GaidamakUA** [comment]
In what part are you interested? AFAIK we are saving photos, videos, notes, maps, user data(favourites etc.). An I believe that's not an issue)

**Comment by stephan75** [comment]
This is an issue tracker here ... a much better place to ask questions like that is the Osmand googlegroup mailinglist.

see https://groups.google.com/forum/#!forum/osmand
