### ISSUE TITLE
Tag `atm=yes` improperly classifies PoIs/Areas.

### ISSUE THREAD

**Issue by nyanmeister** [osmandapp/OsmAnd#15567]
### Description
The tag [atm=yes](https://wiki.openstreetmap.org/wiki/Tag:atm%3Dyes) incorrectly makes an area be classified as an ATM instead of simply indicating the area has an ATM. This classification behavior  would be expected instead from the tag [amenity=atm](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Datm). This behavior is troublesome because the "Nearby POI" feature becomes cluttered with features that have ATMs instead of the actual type of feature. Notably, this incorrect classification does not effect the rendering of what icon appears on the map.

### How to reproduce?
[Look for](https://overpass-turbo.eu/?key=atm&value=yes&template=key-value) (or tag) objects with `atm=yes` and look in the info card in OSMAnd.

### Your Environment
OsmAnd Version: 4.2.7 Plus 
Android/iOS version: 11
Device model: N/A

**Maps used (online or offline):** N/A

**Comment by vshcherb** [comment]
Not sure if I understand the mapping correctly, atm=yes shouldn't be on every enclosing area i.e. it shouldn't be on the mall if it's arleady on the bank inside the mall and it shouldn't be on region/city boundary and so on...

**Comment by nyanmeister** [comment]
> Not sure if I understand the mapping correctly, atm=yes shouldn't be on every enclosing area i.e. it shouldn't be on the mall if it's arleady on the bank inside the mall and it shouldn't be on region/city boundary and so on...

I put `atm=yes` to indicate that a business has an ATM for customers to use, as the wiki article goes into. OSMAnd zealously classifies areas with the tag as an ATM, as in that whole marijuana establishment or convenience store is now an ATM, and that's what shows up in the "Nearby PoI" menu.

**Comment by vshcherb** [comment]
Don't understand what a difference, if you put atm=yes it should display as ATM cause it's accessible

**Comment by nyanmeister** [comment]
The change I propose is that it can be an just an item in the info card (which it currently is), not also the category of the PoI, overwriting the function of the "nearby PoI" feature. I probably want to compare nearby convenience stores and not ATMs when looking at the object. `amenity=atm` is where it would be appropriate to have that be the "nearby PoI" option.

**Comment by nyanmeister** [comment]
This issue seems to have been resolved, looking at previously affected cannabis shops with the tag that was triggering this behavior. The correct behavior for looking for ATMs on the map seems to work with the tag as well, so all's well.
