### ISSUE TITLE
some parks are not rendered

### ISSUE THREAD

**Issue by k-yle** [osmandapp/OsmAnd#15573]
### Description
OsmAnd doesn't render anything if an OSM relation is tagged with `type=boundary` + `boundary=protected_area` + `leisure=park`.

`type=boundary` + `boundary=protected_area` on its own is rendered, and `leisure=park` on its own is rendered, but if you combine all 3 tags then OsmAnd renders nothing. 

### How to reproduce?

Open OsmAnd and browse to one of these locations: [example 1](https://osm.org/relation/12440949), [example 2](https://osm.org/relation/10703494), [example 3](https://osm.org/relation/9852336)

### Your Environment
OsmAnd Version: 4.2.6
Android version: 12 (samsung oneui 4.1)
Device model: Samsung S21+ International Version

**Comment by hakuchi** [comment]
do you have enable boundarys?     
Go to Configure map -> Details -> Nature reserve

**Comment by k-yle** [comment]
thanks @hakuchi , if I enable that option then the park shows up. But since it's doulbe tagged as `leisure=park`, shouldn't it render regardless of that setting?

**Comment by robinpaulson** [comment]
What's the situation here? I'm seeing this apparent bug, my device is too slow to use OGL, which supposedly fixes it.

**Comment by sonora** [comment]
So what is the actual bug? If something is tagged both as park and as nature reserve, should we
- always make it visible because it's a park,
- or make its visibility depend on the nature reserve switch, because it's also that?

I guess the answer is that the green park background must always be rendered, and the NR shader and green boundary line depending on the switch?

**Comment by k-yle** [comment]
> I guess the answer is that the green park background must always be rendered, and the NR shader and green boundary line depending on the switch?

That seems like the most logical option to me, and the least likely to cause confusion

**Comment by robinpaulson** [comment]
This appears fixed, at least for the locations where I saw it, in Aotearoa-New Zealand.

**Comment by vshcherb** [comment]
I think it was fixed with https://github.com/osmandapp/OsmAnd/issues/17241
