### ISSUE TITLE
Plan route shows connection between two unconnected segments when moving point.

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#15576]
## Review, Additional
- [x]  Apply B/W color for point previous position while moving.
![Screenshot 2022-11-16 at 12 12 19](https://user-images.githubusercontent.com/9365308/202152735-6bcb21ff-f672-489d-87d1-3708254e5fc8.png)

## ToDo
• Create a track in Plan a Route with two segment
• Select last point of the first segment
• Choose **Move**
• When Move mode is active, UI draws a line from the last point of first segment to the first point of the second segment
• Click Apply, point will be placed in the new location and will not be connected to second segment. 

Track from video [Thu 27 Oct 2022.gpx.zip](https://github.com/osmandapp/OsmAnd/files/9879412/Thu.27.Oct.2022.gpx.zip)

<table style="width:100%">
  <tr>
    <th>Before move</th>
    <th>Moving</th>
    <th>Video</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/198284935-68c111b4-8914-48db-9f6a-6db49bb4274a.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/198284945-b6632dac-21fb-4ed0-b87a-7a0192ed88cc.png"  width="300" height="auto"/> </td>
    <td><video source src="https://user-images.githubusercontent.com/9365308/198285270-2d531df7-0a91-4e21-8745-119ac8803f3e.mov"  width="300" height="auto"/>  </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.3.0#13906mqta, released: 2022-10-28
[logcat (19).log](https://github.com/osmandapp/OsmAnd/files/9887984/logcat.19.log)
