### ISSUE TITLE
No data on a junction on highways

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15575]
### Description
Offline maps lack data on highway junctions
[Motorway junction, OSM WIKI](https://wiki.openstreetmap.org/wiki/Tag%3Ahighway%3Dmotorway_junction )
[OsmAnd, Default Map Style](https://osmand.net/map/?end=33.979485%2C-84.423111&mode=car#17/29.94747/-95.41580)
[OsmAnd, Mapnik (tiles)](https://osmand.net/map/?end=33.979485%2C-84.423111&mode=car#17/29.94799/-95.41574)
[OSM](https://www.openstreetmap.org/node/316817878#map=18/29.94709/-95.41588)

### Steps to reproduce
Find this place 29.944954, -95.414623

### Actual result
No data on a junction on highways

https://user-images.githubusercontent.com/104760013/198268588-797b5dbb-f490-4503-a098-8cb9c7dd0709.mp4

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/198268432-3a09ba4a-0109-4bcb-9b2c-2747f02a5a4c.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
On offline maps, data on highway junctions are displayed in the same way as on online maps
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/198268867-1e3d114f-da92-44ee-88f5-41f3f2f335e7.jpeg "  width="300" height="auto"/> </th>
  </tr>
</table>   

### Your Environment
OsmAnd Version: 4.3.0.23
Android/iOS version: iOS 15.7
Device model: iPad mini 4

**Comment by vshcherb** [comment]
We have no plan to support it actually on such low level zoom at least.

**Comment by vshcherb** [comment]
This information is available in navigation actually
