### ISSUE TITLE
Wrong icon for railway halt

### ISSUE THREAD

**Issue by Breen5** [osmandapp/OsmAnd#15587]
The icon for railway halt changes from train to bus when zooming in

This concerns places tagged with

railway=halt

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14012mqta, released: 2022-12-09
Done
[Map](https://drive.google.com/file/d/1P7EXIxURSUipk0FnMjG2Pv_xjnODNfRf/view?usp=sharing)

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/206703534-9f58a7aa-f3da-4055-852d-df26229489b7.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>
