### ISSUE TITLE
Improved Route Information (Clickable Routes)

### ISSUE THREAD

**Issue by Hedaja** [osmandapp/OsmAnd#15598]
Hi
I think it would be really useful if you could click on (OSM) routes shown on the map. Similar to for example [Waymarked Trails ](https://mtb.waymarkedtrails.org/#route?id=6632414&map=16.0/38.5397/-105.9852)
For example clicking on a mtb route would zoom out to show the full length of it. The bottom information panel would pop up revealing information about length, difficulty, name, elevation profile, ....
The system in its basics is already implemented in the public transport part of OsmAnd.

Cheers
Christian

**Comment by scaidermern** [comment]
Since version 4.2 it is already possible to tap on hiking and cycling routes (doesn't always work reliable, though). It will show information about the route and also offer to save it as a GPX track.

**Comment by sonora** [comment]
And if you then **tap on the title** in its context menu which has popped up, the map will zoom to show the entire route.

(Similar for POIs etc.) This zooming is a scarcely obvious feature of our context menu, see #2633. Maybe anybody has an idea how to make it more discoverable.

**Comment by vshcherb** [comment]
Indeed, implemented in 4.2

**Comment by Hedaja** [comment]
Thanks. Never realized that it works for hiking and cCling routes.
Unfortunately it doesn't yet work for MTB routes it seems.
