### ISSUE TITLE
org.xmlpull.v1.XmlPullParserException: Attr.value missing f. r

### ISSUE THREAD

**Issue by J2501** [osmandapp/Osmand#1559]
Hello,

When I open OSMand 2.1.1 on my android 4.2 the map is blank and I have this error message  : 
org.xmlpull.v1.XmlPullParserException: Attr.value missing f. r (position:START_TAG \<poi_type name='�0>���������� �0>���^����� ���>������� ��0�>��������� �0�>�������� ��0�>���������� �0�>���^������� �>������� ��0>��������� �0�>�������� ��0>���������� �0�>���������� �.' r='sport'>@476:267 in java.io.InputStreamReader@41ed69f0) 

If I reload the world map ( disable & enable) I can see the map and everything works well until I restart OSMand.

**Comment by vshcherb** [comment]
Please try to install one of the night build.

**Comment by J2501** [comment]
The installation of the night build (in fact it's an update of my OSMand) failed. 
I tried to remove OSMand but I can't (I can't remove OSMand from the administrator list so I can't remove it).
I will find how to make a re-install and I will come back here

**Comment by vshcherb** [comment]
We also have http://osmand.net/help/changes.html releases here of free version. It is very weird issue, which we can't reproduce so far.
