### ISSUE TITLE
Language direction files keep re-appearing

### ISSUE THREAD

**Issue by tradavyvy** [osmandapp/OsmAnd#15606]
I would say only half a bug, but:
Regularly I find a lot of language direction files on my installed maps page. I remove all the languages I do not need. And after a while, I think usualy after an upgrade but I'm not sure, the whole list reappears.
Not a big issue because the files are not big, but not nessesary and illogical. I would expect these files to behave just like map files. Or at most only auto-update the already installed ones.

**Comment by scaidermern** [comment]
Duplicate of #5994?

**Comment by tradavyvy** [comment]
Yep, I think it is. (Sorry)
And vscherb closed that one in september so it will probably be solved in the next release.

**Comment by scaidermern** [comment]
No, unfortunately it is still open. There are just some references to other closed tickets.

**Comment by tradavyvy** [comment]
In that case I reopen the issue because the other one is realy old.

**Comment by scaidermern** [comment]
Well, having a duplicate doesn't really help.

**Comment by vshcherb** [comment]
Issue already fixed
