### ISSUE TITLE
Unexpected car routing

### ISSUE THREAD

**Issue by PinkDuck** [osmandapp/Osmand#1560]
OsmAnd caused some nuisance last night on a return journey from the nearby city by unexpected suggesting a left turn. I have simplified the problem to the following first instance that produces a longer route by distance and time than the second, which was manually created by adding a via point. The YOURS route is correct, the detour via Surrey Street is mystifying. I have tested with current East of England map data and my own generated with OsmAndMapMaker from Norfolk county. Car routing was set to fastest. Shortest gives the expected result.

QUICKEST (longer on distance and time! - 2× traffic light, 1× crossing, 1× left turn, 1× right turn)
```xml
<test regions="" description="" best_percent="" vehicle="car"
	 start_lat="52.62414575157711"  start_lon="1.2948759174346662"
	target_lat="52.62311671022547" target_lon="1.2929125404357649"
	loadedTiles="59" visitedSegments="118"
	complete_distance="726.7104"
	complete_time="144.50327"
	routing_time="105.70777">
```

SHORTEST (shorter on distance and time - 2× traffic light, 1× crossing, 1x right turn)
```xml
<test regions="" description="" best_percent="" vehicle="car"
	 start_lat="52.62414575157711"  start_lon="1.2948759174346662"
	target_lat="52.62311671022547" target_lon="1.2929125404357649"
	loadedTiles="90" visitedSegments="98"
	complete_distance="264.7287"
	complete_time="109.85466"
	routing_time="115.34441">
```

**Comment by PinkDuck** [comment]
I believe this is due to the nature of the junction where the more direct route changes from tertiary to unclassified to primary, causing a 50 second transition penalty for what in reality is under 2 seconds. The longer/further one just changes from tertiary to primary, so no penalty.

Perhaps leave the final value as <select value="150" /> in routing.xml to match with tertiary/tertiary_link. Better yet, consider transition between speed limit and lane count to get a better transition penalty.

**Comment by vshcherb** [comment]
Not reproducible any more
