### ISSUE TITLE
"Driving Style" should be "Riding Style" 

### ISSUE THREAD

**Issue by xenotropic** [osmandapp/OsmAnd#15612]
### Description

All of these instances of "driving style" should say "riding style".

One does not "drive" a bicycle in English, one only "drives" a car. Using the car-centric word for bike nav options makes it seem (even if it isn't true) like this is a feature for cars that got adapted to bicycles. Perhaps a translation error from German in which "fahren" applies to both cars and bikes?

### How to reproduce?

In bicycle navigation, see attached screenshots. 

### Your Environment
OsmAnd Version: 4.2.7
Android/iOS version: 11
Device model: SM-G900V

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
N/A

![Screenshot_20221031-083255_OsmAnd+](https://user-images.githubusercontent.com/4050617/199315255-88664363-b560-42c6-aa96-6ef7d368e5f6.png)
![Screenshot_20221031-083321_OsmAnd+](https://user-images.githubusercontent.com/4050617/199315261-3ea320d5-d38d-4ff5-9b69-06e93ef0c0a8.png)

**Comment by sonora** [comment]
Well spotted - thx! Fixed.
