### ISSUE TITLE
Add route line

### ISSUE THREAD

**Issue by gtrus21** [osmandapp/OsmAnd#15613]
Прошу добавить отображение линии маршрута общественного транспорта при просмотре его маршрута движения. Сейчас при просмотре отображаются только остановки.
![Screenshot_2022-11-02-08-23-20-918_net osmand plus](https://user-images.githubusercontent.com/69676792/199405114-e7b7d12d-6d25-4af6-914f-be4fed925732.jpg)

**Comment by sonora** [comment]
Route lines are displayed if present in the map data.

But note that entering the route line in OSM is not mandatory, is in fact somewhat tedious to enter, and often not exactly known to someone entering the transport stops systematically from time tables only. Hence, route lines are often not contained.

(PS: What's strange about your screenshot is that it does not show the blue bus stop icons served by that selected route.)

**Comment by sonora** [comment]
And I just see the transport stops not showing is a known bug (only in OpenGL rendering): https://github.com/osmandapp/OsmAnd/issues/15005

**Comment by vshcherb** [comment]
Oops I missed that too
