### ISSUE TITLE
Route recalculation should not recalculate the whole route

### ISSUE THREAD

**Issue by pahervin** [osmandapp/OsmAnd#15616]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

car, lorry

### Start and end points

When the driver dont follow the calculated route, a route recalculation happens.
When it happens in town, route recalculation is expected to be quick.

### Actual and expected routes

The whole route is recalculated, including the route beyond the waypoints.
OsmAnd should ends the route recalculation at the first waypoint.
OsmAnd should ends the route recalculation when the new route crosses the former one.

### Is this a regression?

No

## 🌍 Your Environment

**OsmAnd Version:**
<pre><code>
4.2.7
</code></pre>

**Device and Android/iOS version:**
Wiko View3 Lite
Android 9

**Maps used (online or offline):**
- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps

**Comment by lbdroid** [comment]
This is a particularly major problem on extremely long trips. Often you need to get off the highway for fuel and it will want to recalculate the entire route rather than just directing you back to the highway.

**Comment by sonora** [comment]
Maybe check in settings (for the very app profile you use for navigation!) **Navigation settings / Route parameters / Smart route recalculation**.

It should be **on** by default (at least it is for car routing), in which case OsmAnd repeatedly only re-calculates the initial portion of the route. Maybe this was disabled by accident, or was by some mistake not activated if you created a new (lorry?) routing app profile?

**Comment by pahervin** [comment]
> Maybe check in settings (for the very app profile you use for navigation!) **Navigation settings / Route parameters / Smart route recalculation**.
> 
> It should be **on** by default (at least it is for car routing), in which case OsmAnd repeatedly only re-calculates the initial portion of the route. Maybe this was disabled by accident, or was by some mistake not activated if you created a new (lorry?) routing app profile?

Thank's for your quick response.
But there is no more **Smart route recalculation** option wihin the 4.2.7 version.

**Comment by sonora** [comment]
I think you may have to enable the Development plugin to see the option?

**Comment by pahervin** [comment]
> I think you may have to enable the Development plugin to see the option?

Ok, I found it with the development plugin enabled.
Now I am stuck with the maps issue.

**Comment by vetinari** [comment]
> in which case OsmAnd repeatedly only re-calculates the initial portion of the route. Maybe this was disabled by accident

What means "initial portion"? Up to the point where I'm now or from my current position back to the route? 
Not sure if the initial issue applies to me, but on a route with one intermediate destination it happens - after reaching the intermediate destination and then way later going off route to e.g. re-fuel - that the route is recalculated so that the routing tells me to go back to the intermediate destination and continue from there the way I just followed... Maybe this is now fixed with the development plugin enabled (and seeing smart recalculation being enabled)...  Osmand+ here, version from 2023-08-09 on google playstore

**Comment by vshcherb** [comment]
Route recalculation should work now as
1. Without waypoints, Recalculates first 30 km of the route
2. Or with waypoints, it recalculates full route up to first waypoint

You described situation that waypoint wasn't removed once it was passed (was it passed? ) but that's another issue

**Comment by vetinari** [comment]
@vshcherb yes, that first waypoint was reached/passed. Should I open a new issue for that (or did I miss an existing one :))? I can verify if it still happens with the Smart route recalculation option enabled (maybe it was enabled before?) in a few days.

**Comment by vetinari** [comment]
seems not to happen anymore with  the Smart route recalculation.
