### ISSUE TITLE
Some icons need high zoom until they and their text appears

### ISSUE THREAD

**Issue by Thomas12** [osmandapp/Osmand#1561]
Hi,

some icons like the "i" or the symbol for a shelter in a forest often only show up on a relatively high zoom level.

And their textual description almost/often only shows up when you zoom in to an even higher level (~20m). 

Could you please make the zoom-level configurable in the settings window:

-when the icons (like the "i") are shown?
-when the textual description of an icon is shown?

And probably an option like "show/hide an icon's description on tap?"

Thank you very much!

Kind regards,

Thomas

**Comment by romavor** [comment]
It would be great to "show/hide an icon's description on tap" (similar to mapsme) becouse now, it is necessary to zoom in to see the icon label.

**Comment by xmd5a2** [comment]
These zoom levels are defined by rendering style for almost each icons separately.

**Comment by sonora** [comment]
No general action planned. If some icons are definitely and generally displayed too late, please create a separate issue.
