### ISSUE TITLE
Quick action - Pause/Resume navigation

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#15626]
### Discussed in https://github.com/osmandapp/OsmAnd/discussions/15623

<div type='discussions-op-text'>

<sup>Originally posted by **mariush444** November  2, 2022</sup>
There is Start/Stop navigation as quick action

Can you add Pause/Resume navigation ?

I know that there is something like that in Android notification but having this in Osmand is much more useful and make osmand interface much homogeneous.
</div>

**Comment by Chumva** [comment]
This action is already [available](https://github.com/osmandapp/OsmAnd/blob/4bed9475beee2c1355bb182bb56e908c3df02cd6/OsmAnd/src/net/osmand/plus/quickaction/actions/NavResumePauseAction.java#L18) 

![image](https://github.com/osmandapp/OsmAnd/assets/19220417/41ff676c-c26d-4ef5-890f-151625439777)
