### ISSUE TITLE
scree control problem

### ISSUE THREAD

**Issue by mariush444** [osmandapp/OsmAnd#15624]
### Description
I use screen control as:
Use system screen timeout - off
Timeout after wake-up - 45sek
Proximity sensor - on
Navigation instructions - on

When the screen is wake-up and I wanto to verify something on the screen (map) then screen is off during my action.

In my opinion Timeout (45sek) should be **after last touch** and not after wake-up

> The same behavior should be with the option 
> Map during navigation -> Auto-center map view.
> 
> auto-center should be activated after the last touch.

### Your Environment
OsmAnd Version: 11
Android/iOS version: 4.2.7
Device model:

**Comment by mikehgentry** [comment]
Duplicate of #15313

**Comment by mariush444** [comment]
You are right so I closed it.
