### ISSUE TITLE
(wrong)German street name show on romanian map at 500m zoom

### ISSUE THREAD

**Issue by razor74** [osmandapp/Osmand#1562]
![screenshot_2015-08-16-13-06-05](https://cloud.githubusercontent.com/assets/5586993/9292874/49ea4700-4418-11e5-954e-d6d41ff5b2a4.png)
![screenshot_2015-08-16-13-06-37](https://cloud.githubusercontent.com/assets/5586993/9292875/4cea1188-4418-11e5-8102-395bfe084c72.png)
 From lower zoom (50m) until 200m zoom romanian name ( which is put on name tag) show on map. From 500m and up german name which is put on name:de tag show on map.

**Comment by GabrielSebastianMoise** [comment]
I can confirm that.  OsmAnd+ 2.1.1 official from PlayStore . Galaxy Note 5, Stock Rom Android 5.0

![screenshot_2015-08-17-12-09-35](https://cloud.githubusercontent.com/assets/5286676/9301844/3e195200-44da-11e5-98d1-60b1063e7dcb.png)
![screenshot_2015-08-17-12-09-45](https://cloud.githubusercontent.com/assets/5286676/9301845/3e1dbcaa-44da-11e5-999d-10c3b7b4a1b5.png)
![screenshot_2015-08-17-12-09-59](https://cloud.githubusercontent.com/assets/5286676/9301846/3e22dc1c-44da-11e5-86ab-189772a8fdfd.png)

**Comment by razor74** [comment]
The problem still persist in the latest map too. I didnț know if is from the map or from the osmand app...

**Comment by xmd5a2** [comment]
What map language is set in configure map?

**Comment by razor74** [comment]
It is set on Local names.
Phone is on English...

**Comment by vshcherb** [comment]
Unfortunately issue is still not reproducible

**Comment by razor74** [comment]
Sorry but this time i dont believe you...
Please try to load this region
https://www.openstreetmap.org/#map=17/45.30525/24.65146 on osmand and 
try to zoom out  higher then 500 meters.

Phone language set to english ( even the map is romania)...

**Comment by GabrielSebastianMoise** [comment]
Phone set to Romanian, Osmand Set to Romanian, Local Names set, and the
name for DN7C  near Poienari and Corbeni is shown in German !

2015-09-21 22:39 GMT+03:00 razor74 <notifications@github.com>:

> Sorry but this time i dont believe you...
> Please try to load this region
> https://www.openstreetmap.org/#map=17/45.30525/24.65146 on osmand and
> try to zoom out higher then 500 meters.
>
> Phone language set to english ( even the map is romania)...
>
>
> On 21.09.2015 14:09, vshcherb wrote:
> >
> > Unfortunately issue is still not reproducible
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/osmandapp/Osmand/issues/1562#issuecomment-141943836
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osmandapp/Osmand/issues/1562#issuecomment-142087709>.
>



-- 
Toate cele bune !
*------------------------*
Gabriel Sebastian  Moise
Administrator Local - Departament Tehnic
*------------------------------------------------------*
NextGen Communications S.R.L. - Campina

Mobil NextGen  : 076 111 65 59
Mobil Personal : 0726 311 957

Adresa Postala: Strada Grivitei, Nr.63, Campina, Romania !
*------------------------------------------------------*

**Comment by xmd5a2** [comment]
Looks like this issue is related to wrong name order in road-only maps (inspector output):
```
Point types [place-town (351)] Names [name:he(237) - רמת השרון, name(1) - רמת השרון, name:ru(90) - Рамат-ха-Шарон, name:en(84) - Ramat HaSharon] id 278478765
```
Same city from regular maps: 
```
Point types [place-town (351)] Names [name(1) - רמת השרון, name:en(84) - Ramat HaSharon, name:he(237) - רמת השרון, name:ru(90) - Рамат-ха-Шарон] id 278478765
```
This city does not have topic issues, but seems like they are hidden because name:he = name here.
But this city:
```
Point types [place-city (833)] Names [name:ru(90) - Герцлия, name:he(237) - הרצליה, name(1) - הרצליה, name:ar(231) - هرتزيلية, name:en(84) - Herzliya] id 278470198
```
is displayed in russian on some zooms on my device (local names)

**Comment by vshcherb** [comment]
Fixed

**Comment by razor74** [comment]
Thanks.
