### ISSUE TITLE
Map data Schleswig-Holstein is broken

### ISSUE THREAD

**Issue by Discostu36** [osmandapp/OsmAnd#15622]
Germany_schleswig-holstein_europe.obf from Nov 1st is broken. Only Osmand Live data is rendered

![Screenshot_20221102-172604.png](https://user-images.githubusercontent.com/30999326/199547367-d516fe24-6831-48e5-bfae-43ea8656e64e.png)

**Comment by scaidermern** [comment]
Did you try to restart OsmAnd after the map data? If you have OpenGL enabled then this is to be expected after a map update. See #15029. (looks like there are no intentions to fix this bug? 🤷)

**Comment by Discostu36** [comment]
I did deactivate OpenGL to make sure this is not a rendering bug but didn't expect that I need to restart the app. Thanks.

**Comment by scaidermern** [comment]
Remember that you also need to restart the app to disable or enable OpenGL. This setting has no effect otherwise.

**Comment by sonora** [comment]
Latest nightly should change the rendering engine without app restart.
