### ISSUE TITLE
Change offline to online mode

### ISSUE THREAD

**Issue by akbarazimifar** [osmandapp/OsmAnd#15637]
I want it to work online only and the offline mode is disabled. please guide me . Thanks

**Comment by Zirochkabila** [comment]
@akbarazimifar Try to change Map source (on Android) to OsmAnd (online tiles), or Map type (on iOS)
More information can be found at [Online maps](https://osmand.net/docs/user/plugins/online-map)

**Comment by akbarazimifar** [comment]
> @akbarazimifar Try to change Map source (on Android) to OsmAnd (online tiles), or Map type (on iOS) More information can be found at [Online maps](https://osmand.net/docs/user/plugins/online-map)

Hi . Thanks . How to ?
