### ISSUE TITLE
Auto screen on doesn't seem to work on CM12.1 Lollipop

### ISSUE THREAD

**Issue by obifur** [osmandapp/Osmand#1563]
I use the F-droid version.
At least for me it is not working and I have no idea why. Osmand asked for the right the first time I choose the setting and I also checked the permissions afterwards. The voice is talking but display doesn't turn on.

Can anyone confirm this issue? By the way, with Kitkat 4.4.4 everything was fine.

S4 Mini
Cyanogenmod
12.1-20150724-NIGHTLY-serranoltexx 

P.S. Thank's to all guys who work on Osmand - the app is really great!!

**Comment by gunterloos** [comment]
I second the issue. Moto G (XT1033), CM12.1 nightlies, since a few months no auto screen on. 

And indeed: great app!

**Comment by breversa** [comment]
Have you looked at #1398 ? It may be the same issue.

**Comment by obifur** [comment]
I noticed #1398 , but as I wrote, the voice is talking... or do I misunderstand something?

**Comment by breversa** [comment]
My bad, I read your opening post too quickly.

**Comment by obifur** [comment]
Since I updated to CM Version 20150829-NIGHTLY-serranoltexx  the Problem is solved!
