### ISSUE TITLE
Transitloc plugin

### ISSUE THREAD

**Issue by dkniffin** [osmandapp/Osmand#1564]
Transitloc is an API for public transit data. It'd be awesome if there was a plugin for accessing that API through OsmAnd.

https://www.mashape.com/transloc/openapi-1-2#!documentation

**Comment by TheLastProject** [comment]
Another possibility would be [public-transport-enabler](https://github.com/schildbach/public-transport-enabler), which is also used by [Liberario](https://github.com/grote/Liberario).

**Comment by Airon90** [comment]
Duplicate of #1236

**Comment by dkniffin** [comment]
@Airon90 Good call. closing in favor of that issue.
