### ISSUE TITLE
The readings in the weather widgets during the first startup show long values

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15649]
### Description
During the first launch, the indicators in the weather widgets show unrealistic (long) values. Restarting helps. 

### Steps to reproduce
Open OsmAnd with activated plugin and weather widgets

### Actual result
Indicators in widgets are longer

https://user-images.githubusercontent.com/104760013/200116410-ed641625-80a1-49f4-af95-2982b23416f1.mp4

### Expected result
The same indicators are displayed as after the restart

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13926mqta, released: 2022-11-05
Android/iOS version: Android 12
Device model: POCO X3 NFC

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/15653

**Comment by ivanPyrohivskyi** [comment]
Could not reproduce, but fixed possible cause

**Comment by Zirochkabila** [comment]
Still present in OsmAnd~ 4.3.0#13975mqta, released: 2022-11-26
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/204109971-4f3c7679-f69e-4cdb-86d8-3824b89036bb.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  


https://user-images.githubusercontent.com/104760013/204109987-c2e5d4b4-08e5-4bb6-814a-ec377169e3c6.mp4

[logcat (26).log](https://github.com/osmandapp/OsmAnd/files/10097081/logcat.26.log)
