### ISSUE TITLE
Change the name Options in the navigation menu to Settings (at Android and iOS OsmAnd version)

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15645]
## ToDo Android
- [x]  Change **Options** to **Settings** in Menu – Navigation. 

## ToDo iOS
- [x]  Change **Options** to **Settings** in Menu – Navigation 

### Current
<table style="width:100%">
  <tr>
    <th colspan=2>Andoid</th>
    <th colspan=2>iOS</th>
  </tr>
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/199991949-8cd8cc4f-311e-4cbd-ac2f-899d2189f481.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/199991960-212b47f4-3333-4a99-bff4-747bce7b309a.jpeg"  width="300" height="auto"/> </th>
<th><img src="https://user-images.githubusercontent.com/104760013/199993129-c6c6faf0-7713-443b-a31b-e0e344905aa5.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/199993140-f7908da4-fa55-4e91-8383-34041272b761.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
We need to use "Settings" in all cases

**Comment by EugeneZmeuk** [comment]
https://osmand.net/docs/user/navigation/
https://osmand.net/docs/user/navigation/route-navigation#navigation-options
https://osmand.net/docs/user/navigation/route-navigation#simulate-navigation
https://osmand.net/docs/user/navigation/gpx-navigation#how-to-use
https://osmand.net/docs/user/navigation/gpx-navigation#navigation-options
https://osmand.net/docs/user/navigation/boat-navigation#options
