### ISSUE TITLE
Display of transparency of temperature contour lines is delayed

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15651]
### Description
The display of transparency of temperature contour lines is delayed. 
Changing the transparency of the temperature value (located on the curves) occurs instantly.

### Steps to reproduce
Configure map > Weather > Contours > Move transparency slider

### Actual result
Display of transparency of temperature contour lines is delayed

https://user-images.githubusercontent.com/104760013/200117051-e5e2e4f5-7116-4191-a9b1-041256ce4819.mp4

### Expected result
The change of transparency of the temperature contour occurs synchronously with the change of transparency of the value on the contour.

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13926mqta, released: 2022-11-05
Android/iOS version: Android 12
Device model: POCO X3 NFC

**Comment by vshcherb** [comment]
The task didn't pass ui / final review - add it to the task itself
