### ISSUE TITLE
Voice instructions without TTS are very chatty

### ISSUE THREAD

**Issue by starsforeveryone** [osmandapp/OsmAnd#15659]
Hey dear developers!

I've recently discovered OsmAnd~ via F-Droid an like it very much so far!

My only problem is that the voice interface seems to suffer from high precision-syndrome. 😂

Since I'm NOT using Google TTS (text-to-speech), but rely on the internal voice directions, a nice smooth:
"In 253 meters, please turn right."
gets instead narrated as:
"In------TWO----HUNDRED----AND----FIFTY----THREE------meters, please turn right."
with the number spoken slowly and choppy, as if it was synthesized by playing individual voice recordings of the digits after each other.

By the time it takes the voice interface to speak said instructions, my car has already driven like 300 meters. 😅
Therefore, it's not sensible to use such high precision in these conditions where TTS is not used.

I propose that it would be benefitial for usability if the interface would approximate/round the distance to the next big number. This would shorten the voice message to:
"In------THREE----HUNDRED----meters, please turn right."

If you are still doubtful about this, please try using OsmAnd on a Google-free phone (pure LineageOS / Android without Google) and wait for your nervous breakdown ^^

Kind regards & thanks!

**Comment by arncor** [comment]
I've always found a bit ridiculous this 1-meter precision, both from the spoken indications and from the "next turn" widgets.

IMHO, it would be more than enough to never go below 10-meter precision (the GPS signal is barely better than a few meters anyway), and decrease the precision when the distances are bigger.

**Comment by sonora** [comment]
Hmm... sounds like this may still be a leftover of #6023 and #5976, only here now for recorded voices.

Two thoughts up front:
1. Why don't you install any non-google TTS engine, there's several out there... That would also give you the benefit of being able to hear non-recorded voice data, like street names
2. For recorded voices: Your assumption is correct, the announcements are (necessarily) complied of per-recorded chunks, and that#s the reason for this choppiness. But in all voice config files I have just checked we do perform the rounding correct, like to full kilometers above 1.5km, to the nearest 100m above 200m, and to the nearest 10m below that.
 
So I wonder what voice language and version exactly are you using? You are downloading one directly via the OsmAnd app, right?

@vshcherb I think these users are suffering from the fact that our download server seems not up-to-date? I just downloaded the `en` recorded voice via the app, and
- it still contains a __config.p_ file, which should be long obsolete?!
- it's _en_tts.js_ file has file date 2018-08-10, hence is missing both the latest updates I had made to the file in our resources repository about 15 months ago, as well as the old (fall 2018) rounding fixes for the two issues I quoted above.

What needs to be done to refresh the downloadable voice packages with all updated _xx_tts.js_ files? (All changes I ever made to the config files should properly account for the fact that we cannot use new recorded vocabulary without having new recordings, of course).

**Comment by starsforeveryone** [comment]
>     1. Why don't you install any non-google TTS engine, there's several out there... That would also give you the benefit of being able to hear non-recorded voice data, like street names

I tried eSpeak, but frankly, it sound so bad that I cannot use that. It's like a navi from the early 2000's with an extremely robotic voice. I find the included voice samples in OsmAnd to be much more pleasant.

If you know any non-Google replacement that actually sounds pleasant, I'd love to hear more about it!

>     2. For recorded voices: Your assumption is correct, the announcements are (necessarily) complied of pre-recorded chunks, and that's the reason for this choppiness. But in all voice config files I have just checked we do perform the rounding correct, like to full kilometers above 1.5km, to the nearest 100m above 200m, and to the nearest 10m below that.

Like I said, sadly, for me, the rounding seems to only apply for distances larger than 1km.

I repeatedly get voice instructions like the example I posted: "In three hundred and fourty seven meters, turn right." "In two hundred and twenty six meters, turn left."

At least for me, the rounding does not seem to apply.

> So I wonder what voice language and version exactly are you using? One downloaded directly via the OsmAnd app, right?
I downloaded the German voice language directly from the OsmAnd app. The app I downloaded from the F-Droid repository. The version is currently OsmAnd~ 4.2.6.

**Comment by sonora** [comment]
TTS engines: I personally prefer Samsung's, have never researched if it can be installed on non-Samsung devices. Google's does definitely run on all my test devices even where all other Google software and services are deactivated. There used to be several others, I remember SVOX and IVONA, not sure if they can still be found. Here is a German blog post discussing TTS engines in non-google setups. https://www.kuketz-blog.de/android-sprachausgabe-tts-engine-bei-custom-roms-aktivieren/ .

Regarding the rounding issue: I think we have to wait for @vshcherb to update (or teach me how to) the voice config files on the download server. If in your setup you have file access to OsmAnd's data folder, you could manually test this by taking this file [de_tts.zip](https://github.com/osmandapp/OsmAnd/files/9968656/de_tts.zip), unzip it, then backup and replace the existing one in sub-folder `(osmand)/voice/de`.

**Comment by GabrielSebastianMoise** [comment]
Try Voci Vocalizer. For my country it sound excelent.

mie., 9 nov. 2022, 09:52 Hardy ***@***.***> a scris:

**Comment by vshcherb** [comment]
@sonora files are updated automically when app version is updated https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/assets/bundled_assets.xml#L62. 

If you have prepare new zip files they can be updated manually, please create issue with zip files and @xmd5a2 will upload them. Unfortunately there is no automation script yet.

**Comment by vshcherb** [comment]
Updated script https://github.com/osmandapp/OsmAnd-resources/blob/master/voice/gen_voice.sh and added jenkins job to upload generate https://builder.osmand.net:8080/view/Generate%20Maps/job/VoiceRecordedPublisher/ws/voice/work/ 

Though for each language script needs to be added like https://github.com/osmandapp/OsmAnd-resources/blob/master/voice/de/pack_rec_voice_std.sh

**Comment by sonora** [comment]
I cannot guarantee it will work flawlessly, some of the packages are 6 or even 9 years old, but I recommend we update all recorded packages where the xx_tt.js file has a more recent 'last changed" date than the voice subfolder, e.g.

![image](https://user-images.githubusercontent.com/845735/201108837-51fc57f3-60ce-463c-ade6-b7d6ca482b98.png)

This would mean we re-package this positive list:
```
OsmAnd-resources/voice/be/voice/
OsmAnd-resources/voice/bs/voice/
OsmAnd-resources/voice/ca/voice/
OsmAnd-resources/voice/cs/voice/
OsmAnd-resources/voice/da/voice/
OsmAnd-resources/voice/de/voice/
OsmAnd-resources/voice/en/voice/
OsmAnd-resources/voice/en-gb/voice/
OsmAnd-resources/voice/es-ar/voice/
OsmAnd-resources/voice/es/voice/
OsmAnd-resources/voice/fa/voice/
OsmAnd-resources/voice/fi/voice/
OsmAnd-resources/voice/fr/voice/
OsmAnd-resources/voice/hi/voice/
OsmAnd-resources/voice/hu-formal/voice/
OsmAnd-resources/voice/hu/voice/
OsmAnd-resources/voice/it/voice/
OsmAnd-resources/voice/ja/voice/
OsmAnd-resources/voice/ko/voice/
OsmAnd-resources/voice/nl/voice/
OsmAnd-resources/voice/pl/voice/
OsmAnd-resources/voice/pt-br/voice/
OsmAnd-resources/voice/pt/voice/
OsmAnd-resources/voice/ru/voice/
OsmAnd-resources/voice/sc/voice/
OsmAnd-resources/voice/sk/voice/
OsmAnd-resources/voice/sv/voice/
OsmAnd-resources/voice/tr/voice/
OsmAnd-resources/voice/uk/voice/
OsmAnd-resources/voice/zh-hk/voice/
OsmAnd-resources/voice/zh/voice/
```

So you want me to add an [pack_rec_voice_std.sh](https://github.com/osmandapp/OsmAnd-resources/blob/master/voice/de/pack_rec_voice_std.sh) to all of these, right?

**Comment by vshcherb** [comment]
@sonora the issue is to check somehow at least by size that it's not changed much. So it it should be step by step anyway and it's better to start with languages possible to test. Once you do 3-4 languages we can continue ourselves. So it's not just a mechanic task but unfortunately testing task cause voice packages were not automated but hopefully github is in sync with uploaded voices

**Comment by sonora** [comment]
I've checked _de_, _en_, and _ru_: All `.ogg` files on github and on the download server are100% identical, should be safe to re-package these.

But something's wrong, I get on jenkins:
```
/tmp/jenkins14611488336259003731.sh: line 6: ./en/pack_rec_voice_std.sh: Permission denied
work/en_0.voice.zip: No such file or directory
```
Also: Where can I access the files to test if I do not select "Upload"?
