### ISSUE TITLE
When clicking on a link in the weather plugin, a 404 error is displayed

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15654]
### Description
When clicking on a link in the weather plugin, a 404 error is displayed

### Steps to reproduce
Menu > Plugins > Weather > Click on the link

### Actual result
404 error is displayed

https://user-images.githubusercontent.com/104760013/200117722-c6681216-e2cc-4130-af4f-2d1efdc16c6a.mp4

### Expected result
The page with information about the weather (plugin) is displayed.

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13926mqta, released: 2022-11-05
Android/iOS version: Android 12
Device model: POCO X3 NFC

**Comment by vshcherb** [comment]
The task didn't pass ui / final review - add it to the task itself
