### ISSUE TITLE
Add a red circle as the center of the map when viewing the weather

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15657]
### Description
Add a red circle, on the Android OsmAnd version, as a marking of the center of the map, when viewing the weather. How it is implemented on iOS

### Steps to reproduce
Configure map > Weather > Temperature > Enable > Go back to the map and move it

### Actual result
The center of the map isn't displayed and it isn't clear from where the data is displayed in weather widgets

https://user-images.githubusercontent.com/104760013/200118457-a27ab42a-b5bb-4e3e-8370-0b7e3fff42c3.mp4

### Expected result
A red circle is displayed, by which you can understand the data of which place is displayed in the widgets.

https://user-images.githubusercontent.com/104760013/200118563-5668d621-5920-4d16-9bcd-7528c8c7dc13.mp4

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13926mqta, released: 2022-11-05 and 4.3.0.27 iOS (Expected result)  
Android/iOS version: Android 12
Device model: POCO X3 NFC

**Comment by vshcherb** [comment]
Red circle should be only with weather toolbar enabled. Probably android version won't need as we have standard cross icon

**Comment by Zirochkabila** [comment]
@vshcherb Yes, but the standard icon disappears three seconds after zooming, and then it is not visible, which makes it difficult to understand where exactly the data is displayed (you need to use the zoom every time to display the cross icon)


https://user-images.githubusercontent.com/104760013/200279216-0c90e9b2-ea71-437b-badc-d6543b8ae073.mp4

**Comment by vshcherb** [comment]
Then it could be mentionned in Weather Screen which is about to be started to constantly display.
