### ISSUE TITLE
Units of measurement do not change in weather widgets

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15653]
### Description
When changing the units of measurement in Configure map, the units of measurement in weather widgets do not change

### Steps to reproduce
Configure map > Weather > Temperature > Measurement units > Change unit

### Actual result
Units of measurement do not change in weather widgets

https://user-images.githubusercontent.com/104760013/200117500-fb6634e9-d229-4b40-8d4c-25ffe7817455.mp4

### Expected result
Units of measurement change according to the specified value and display at weather widgets

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13926mqta, released: 2022-11-05
Android/iOS version: Android 12
Device model: POCO X3 NFC

**Comment by vshcherb** [comment]
The task didn't pass ui / final review - add it to the task itself
