### ISSUE TITLE
In offline mode, weather widgets will disappear from the home screen

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15656]
### Description
After switching to offline mode and moving the map down or up, the weather widgets disappear. If you go back down or up again, the widgets appear on the map.

### Steps to reproduce
Enable offline mode > Move down/up on the map

### Actual result
Weather widgets will disappear from the screen

https://user-images.githubusercontent.com/104760013/200118165-076c5b37-bafe-44a7-8926-59ce7dee1dfb.mp4

### Expected result
In offline mode, widgets are displayed in the same way as in online

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13926mqta, released: 2022-11-05
Android/iOS version: Android 12
Device model: POCO X3 NFC

**Comment by vshcherb** [comment]
The task didn't pass ui / final review
