### ISSUE TITLE
Display type of contours on the map does not change

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15652]
### Description
When switching between contour types - contours on the map do not change

### Steps to reproduce
Configure map > Weather > Contours > Change type

### Actual result
Display type of contours on the map does not change

https://user-images.githubusercontent.com/104760013/200117284-251d7993-aa29-47a8-99ac-e5ffeacfebdb.mp4

### Expected result
The map displays contours according to the selected type

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13926mqta, released: 2022-11-05
Android/iOS version: Android 12
Device model: POCO X3 NFC

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/15649
