### ISSUE TITLE
Map blinks when weather layer transparency changes

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15650]
### Description
Map blinks when weather layer transparency changes

### Steps to reproduce
Configure map > Weather > Enable > Temperature > Enable > Move transparency slider

### Actual result
Map blinks 

https://user-images.githubusercontent.com/104760013/200116684-0882099c-8857-46bc-9c59-47a69619ebeb.mp4

### Expected result
Animation is smooth as when setting the transparency level for Underlay/Overlay layers

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13926mqta, released: 2022-11-05
Android/iOS version: Android 12
Device model: POCO X3 NFC

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/15653
