### ISSUE TITLE
The "Show full description" button does not show an additional description

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15655]
### Description
The "Show full description" button does not show an additional description

### Steps to reproduce
Menu > Plugins > Weather > Enable > Show full description

### Actual result
The "Show full description" button does not show an additional description

https://user-images.githubusercontent.com/104760013/200117891-bef3edc3-33b7-415f-b543-1c730412ca2c.mp4

### Expected result
An additional description of the plugin should open. If there is no additional description - the button should not be displayed

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13926mqta, released: 2022-11-05
Android/iOS version: Android 12
Device model: POCO X3 NFC

**Comment by vshcherb** [comment]
The task didn't pass ui / final review
