### ISSUE TITLE
Trip duration is reported in seconds after the route calculation ends

### ISSUE THREAD

**Issue by Max1234-Ita** [osmandapp/OsmAnd#15669]
### Description
I've noticed that whenever I do a route calculation, OsmAnd shows a pop-up message with a summary of the calculation result: There, the trip duration is shown in seconds, i.e. "_Route: distance 107 Km, duration 4455 seconds_" (not sure this is the exact English text, translating back from Italian, see attached picture).

I understand this is a message used by the Developer for debug purposes, however it might be useful to the End Users too, if only the travel time would be properly represented, i.e. in (days,) hours and minutes, e.g. :"_Route: distance 107 Km, duration about 1h 14m_" (actually, 4455 seconds build up to 1h, 14m, 15s)

(BTW, I also noticed that the expected travel time is reported in the widget as 1h 24 minuites, I guess OsmAnd is adding some buffer time to make a more realistic estimation)

### How to reproduce?
Calculate a route to a destination that takes more than 60 minutes to be reached

### Your Environment
OsmAnd Version:  4.2.7 released 2022-07-13
Android/iOS version:  Android 11
Device model:  Samsung Galaxy A50 (SM-A505FN/DS)

**Maps used (online or offline):**   
Offline vector maps

![Screenshot_20221106-120958_OsmAnd+](https://user-images.githubusercontent.com/15315381/200325895-9f79a421-8a7a-4061-ad9e-60bd7e26dd7e.jpg)

**Comment by vshcherb** [comment]
Seconds are important to check that we calculate "quickest route" so it's easy to compare in seconds. It might be better of course but it's not a realistic travel time it's internal timer and real time might be much shorter. 

It's probably better in some sense to format it differently but it should be distinguished from real travel time.

**Comment by scaidermern** [comment]
Duplicate of #13501 (just mentioned for completeness)
