### ISSUE TITLE
After connecting to Android Auto, a new value is added to the Map rendering widget

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15668]
### Description
After connecting to Android Auto, a new value is added to the Map rendering widget

### Steps to reproduce
Connect to AA

### Actual result
A new value is added to the Map rendering widget

https://user-images.githubusercontent.com/104760013/200304646-de1bdd6f-727b-4d75-b896-b36539aec515.mp4

### Expected result
After connecting to AA, the value in the Map rendering widget remains the same as before connection

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13932mqta, released: 2022-11-07
Android/iOS version: Android 12
Device model: POCO X3 NFC

**Comment by vshcherb** [comment]
Duplicate
