### ISSUE TITLE
Two finger map rotation: deactivate for North-up (permanent or by settings)

### ISSUE THREAD

**Issue by nounours77** [osmandapp/OsmAnd#15660]
# Prevent map from accidentely rotating by using two finger zoom in "Always North up" mode.

### Description

When the map is used in "Always North up"-mode, the user normally wants to have it "Always North-up", to allow for better orientation. 
Unfortunately, if two finger zoom is used, the north orientation gets lost. I do not see any benefit in turning the map in this mode. On the other hand, if I rotate the map without realizing it, it get totally lost, as the map now looks "wrong". If I do realise it, I have to tap the compass icon - each time after I zoomed. This makes the app basically unuseable for "Map-watching" like on a paper map.

I did not find any hint how this should be possible, nor in the app, nor in the help, nor searching your website and GitHub.

I'm Using OSMand 4.2.4 on iPhone iOS 16.0.2

### Describe the solution you'd like

If the mode "Always North up" is selected, the two-finger-map-rotation should be disabled.

### Describe alternatives you've considered

If somebody sees a need for having the two-finger-map-rotation, then there should be an option to enable/disable this, additional to the existing option "North always up". (Better would be: "North always up", "North up but able to rotate", ...)

Thanks very much for considering, nounours

**Comment by sonora** [comment]
I am a little surprised by your statement "_if two finger zoom is used, the north orientation gets lost_": I just tried it and it appears you have to at tve same time twist (rotate) your fingers beyond a certain threshold, looks like15 or 20 degrees minimum, for that to happen.

Having said that, I have also observed users who have unintedledly rotated their map in that fashion. In order to avoid yet another setting, I guess we could simply inctease the threshoöd to activate the rotation, maybe to 45 degrees or so.

**Comment by nounours77** [comment]
Agreed, you need to twist a bit. But in normal use, this will very often happen.
Yes, increasing the threshold to 45° will help a lot.

Still, why not deactivate completely? Do you see any usecase in rotation when "north always up" is choosen? If I choose north always up, I want North always up, and never rotating it. Or does anybody see a usecase?

**Comment by sonora** [comment]
I was just trying to avoid a larger code and UI change: From what I see in our code,  "Manually rotated" is not a standalone option:
![Screenshot_20221106-212242_OsmAnd~](https://user-images.githubusercontent.com/845735/200193340-bb8ccdfe-26f0-4e9d-862e-96b4e2ecfba3.jpg)

The only way to invoke it in the first place is to use North is up" and then twist the map, i.e. it is essentially a sub-option of "North is up".

**Comment by nounours77** [comment]
I do (still) not get the connection between "Fixed" and "Manually rotated". Either its fixed, or its rotating (by movement, by compass, or manually).
Therefore I would advocate 4 options: 
* Fixed (north is up)
* Movement direction
* Compass direction
* Manually rotating

This seems easier and more logical and having a sub-option.

If you want to go with a suboption, this is also fine by me, it's reaching the same goal.
* Fixed
    ** north is up
    ** manually rotated
* Movement direction
* Compass direction

But again, why not collapse it to one layer?
* Fixed (north is up)
* Fixed (manually set rotation angle)
* Variable (movement direction)
* Variable (Compass direction)

Thanks, Gilbert

**Comment by sonora** [comment]
I have no strong preference here, and don't think it is needed very often anyway. But I think that if a user has this use case on a particular occasion, they may simply may expect that they can twist the map with their fingers if needed, without first having to go though an explicit settings change. Hence I vote for increasing the threshold a little and evaluate it then.

**Comment by nounours77** [comment]
Don't get my wrong - any improvement will be very welcome and is very important!
I just still don't get how some users "... may simply expect that they can twist the map ..." if they are using the setting "Fixed - north is up"?? This is pretty clear to expect that it's fixed when you ask for it. (On the other hand you will disappoint a lot of users if they ask for fixed and it's not ...).
=> But to acknowledge your point, what about the following suggestion: Adding the option "Rotating manually", but make it the DEFAULT. So the unversed user can rotate the map as he/she wishes with two fingers, and the strange old fashioned guys like me can change the option to "fixed", so they are happy as well. Does this help?

**Comment by Dollarius** [comment]
I agree with @nounours77 that this would be a great feature!
I often mistakenly "rotate the North" while zooming in with 2 fingers (i.e., while running), and I find it annoying because I like to have the North fixed North (as the option says).
To obviate this problem, I usually force myself to Zoom in by double-click-drag-up/down (i.e., by using just 1 finger) or by using the +/- buttons.

Thank you for taking this important improvement into consideration!

**Comment by Nine-Tailed** [comment]
I support this request to add an option to disable map rotation when the map is oriented north up.

**Comment by Boothy99** [comment]
Yes, this is driving me bonkers. No matter how careful I am using two-finger zoom, I end up coming out of "North is up (fixed)". Frustrating. I've watched my fingers and I'm not rotating them beyond 5° to10° for this to occur.

**Comment by nounours77** [comment]
@Nine-Tailed  @Boothy99   thank you both for support. I share your frustration. And I really can't figure out a use case when some chooses "North is up (fixed)" that he/she wants the map to spin around like a caroussel! So let's hope this will be changed. Just add a forth setting "Spinning like a caroussel". Make this even the default if somebody feels the need for it. But let the one how use the map as a map having a "North is up (fixed)" which does what it says, well putting "north up". Fixed. Always. Thank you!!!

**Comment by Boothy99** [comment]
> I am a little surprised by your statement "_if two finger zoom is used, the north orientation gets lost_": I just tried it and it appears **you have to at the same time twist (rotate) your fingers beyond a certain threshold, looks like15 or 20 degrees minimum**, for that to happen.
> 
> Having said that, I have also observed users who have unintedledly rotated their map in that fashion. In order to avoid yet another setting, I guess **we could simply increase the threshold to activate the rotation, maybe to 45 degrees or so.**

Hi @sonora,
I'm finding the "North is up (fixed)" changes to the **annoying** "Manually rotated (fixed)" well within an angle of ~ <10°, not 15° to 20°. If I rotate just 5° and let go, I see the view changes to "Manually rotated" 😠 . 
I've tried this on my Google Pixel 6 and Samsung Galaxy Tab S4 (both on OsmAnd+ 4.4.4), and both require only the slightest twist to initiate the change of setting. I agree with you entirely regarding a rotation of 45° threshold 👍

**Comment by nounours77** [comment]
Hi @Sonora, working on iOS, I must say the map rotates well beyond a twist of 15 degrees. Increasing the treshold does help, but it does not cure the problem.
What is a problem with a forth choice in the compass setting? It is very missleading if the setting is saying "North ALWAYS up (fixed), and then it's actually rotating? Rotating the map does not make sense! So this setting should not rotate. If really somebody wants to rotate the map, why not give him the option to set this to "Manually rotating by two finger twist"??

**Comment by Boothy99** [comment]
@nounours77 ....on second thoughts, yes - "North ALWAYS up (fixed)" should stay as it says on the tin, and be always fixed, unless clicking on the icon to allow rotation (i.e. no rotation no-matter what degree two fingers might rotate for "North ALWAYS up (fixed)").

**Comment by sonora** [comment]
Just for cross reference: This had interim been fixed, but is currently broken again, see #16751 and references rhere.

**Comment by ThureHauser** [comment]
I completely agree with previous posts: choosing "north always up" should be respected as is - fixed forever! It is a real navigation problem if map orientation can move with zooming, no matter how many degrees are used as a threshold.

**Comment by zedd137** [comment]
I totally agree with the previous posts. To me it happens many times a day that I accidently rotate the map. It's somewhat annoying, having to tap the compass icon every time I have zoomed in the map. So yes, fixed north schould really be exactly what it says.

**Comment by mnalis** [comment]
- Related: https://github.com/osmandapp/OsmAnd/issues/17086

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/17086
