### ISSUE TITLE
Utterly wrong "On foot" navigation chooses longer and forbidden route (motorroad=yes)

### ISSUE THREAD

**Issue by mdykierek** [osmandapp/OsmAnd#15667]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

On foot

### Start and end points
Start: https://www.openstreetmap.org/node/9439272999
End: https://www.openstreetmap.org/node/300515633

### Actual and expected routes

On foot navigation takes >1.6km using Primary road (forbidden to walk along unless there is a sidewalk - usually does not exist)
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/27214784/200302463-41878f40-a1a7-4903-a7e7-345bfc889bdc.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

For comparison Bicycle is correct and ~570m long
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/27214784/200302591-409c4918-a84a-42ae-a04f-abd01c553d7a.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Is this a regression?

Don't know

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>OsmAnd+ 4.2.7</code></pre>

**Device and Android/iOS version:**
Mi 9T Pro with Android 11

**Maps used (online or offline):**
Poland, Silesia November 2022 + Live updates for the region (results are different, but the essence remains the same).

- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**
I am using live updates so the November 2022 maps will show slightly different results. I attempted to fix the maps and got worse results (due to pedestrian restriction on 902 links - so that on foot is forbidden.)

**Comment by scaidermern** [comment]
> On foot navigation takes >1.6km using Primary road (forbidden to walk along unless there is a sidewalk - usually does not exist)

Well, https://www.openstreetmap.org/way/193121903 has `bicycle=no` set but there is no `foot=no`. I'm not sure if OsmAnd supports any country-specific implicit access tags.

**Comment by mdykierek** [comment]
My attempt was to change access to fix/improve. Now motor_vehicle only 
on the links and that is why it is 1.6km.
IMHO on foot should take better than bicycle (there are plenty of 
footpaths. Why take 3x longer express road vs 600m footpath?
The unfortunate location of bus_stop node is one of the factors.
I would love to move the bus stop (required to be node) off the highway, 
but I am having trouble with relations in ID and platform (area) that is 
already there. It simply does not allow to make proper relations to 
bus_stop node.

Pozdrawiam,
Mariusz Dykierek

**Comment by mdykierek** [comment]
So I changed the 902 to no foot access and the situation improved. This however does not change my opinion on 3x longer route.

**Comment by Zirochkabila** [comment]
[OSM GraphHopper](https://www.openstreetmap.org/directions?engine=graphhopper_foot&route=50.27979%2C18.94332%3B50.28192%2C18.94923#map=17/50.28079/18.94558) 
<img width="1437" alt="Screenshot 2022-11-10 at 16 31 03" src="https://user-images.githubusercontent.com/104760013/201118485-17a05a5e-d394-4e39-b7e4-3c04b3094b19.png">

[OsmAnd](https://osmand.net/map/?start=50.279758%2C18.943332&end=50.281925%2C18.949241&mode=pedestrian#17/50.28049/18.94822)
<img width="1437" alt="Screenshot 2022-11-10 at 16 33 46" src="https://user-images.githubusercontent.com/104760013/201119174-8b10955c-8a9e-4dc1-a2d9-fcc9e45b014d.png">

**Comment by mdykierek** [comment]
> > On foot navigation takes >1.6km using Primary road (forbidden to walk along unless there is a sidewalk - usually does not exist)
> 
> Well, https://www.openstreetmap.org/way/193121903 has `bicycle=no` set but there is no `foot=no`. I'm not sure if OsmAnd supports any country-specific implicit access tags. In many countries it is perfectly fine to walk on a primary highway.

Hey! The road is marked with mottorroad=yes! Thus it should be forbidden both to walk or ride a bicycle there: https://wiki.openstreetmap.org/wiki/Key:motorroad

**Comment by vshcherb** [comment]
Fixed

**Comment by HaoTian22** [comment]
hmm I think that it have not been fixed yet?
I use 4.5.10 on Android 13, it still navigating me to enter a tunnel which was tag as motorroad=yes.
And I found the "Avoid Motorway" is not enabled in the profile of foot by default.
![Screenshot_2023-10-04-23-16-56-363_net osmand](https://github.com/osmandapp/OsmAnd/assets/48882584/8057a289-337e-4b02-a33b-eb43b2f257f0)
Here is the tunnel https://openstreetmap.org/way/153453720
