### ISSUE TITLE
Nov 2022 Base routing: Route calculation much longer

### ISSUE THREAD

**Issue by pahervin** [osmandapp/OsmAnd#15678]
# 🐞 routing report

### Routing engine
- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile
car

### Start and end points
Since november the 1rst maps update, route calculation is much longer.

I am used to to start OsmAnd, even on well known trip. Route calculation was performed quickly for a 300Km trip. 
Since the last maps update (standart ones), the route calculation is much longer, and fails for a long trip (over 200Km). Sometime the application crashes during calculation.
I have tried several route calculations. Fails dont depend on a single (standart) map.
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/6032499/200530883-4fbb73bb-623b-4593-9ae6-642b3e3fb489.png"  width="300" height="auto"/> </th>
  </tr>
</table>   

### Actual and expected routes
If I can get again the formers maps, I'll retry route calculation and check the maps regression (britany, normandy, pays de Loire).

### Is this a regression?
Yes, but about maps (not the application)

## 🌍 Your Environment

**OsmAnd Version:**
<pre><code>
4.2.7
</code></pre>

**Device and Android/iOS version:**
Wiko View3 Lite : I am been using this device with OsmAnd since monthes, several times per week.

**Maps used (online or offline):**
- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**

**Comment by pahervin** [comment]
Same issue with roads-only maps and on another device.

**Comment by vshcherb** [comment]
There is a difference on base routing for November 2022 maps, we're going to revert it now (regenerate November or December) and test it.

**Comment by pahervin** [comment]
> There is a difference on base routing for November 2022 maps, we're going to revert it now (regenerate November or December) and test it.

Thanks for your response.
People who have downloaded November 2022 are stuck in long distance routing.
While you are fixing the issue, may I suggest you to restore September 2022 maps.

**Comment by pebogufi** [comment]
October '22 ?

**Comment by pahervin** [comment]
> October '22 ?

I saw on Twitter that the issue began with the October 2022 maps.
Any recent good maps will be fine.

**Comment by vshcherb** [comment]
Issue with maps October was only about to delay generation + France maps were broken but that was a process issue. Nov 2022 maps slowdown is a result of fixing incorrect routes. So in the end we've fixed issue with incorrect long routes including ferries but it's made overall slower. 

We're going estimate how much slower it is to make a decision to produce new revert generation or not.

October maps are totally fine

**Comment by vshcherb** [comment]
Pre november maps
```
11-13 16:41:59.160 22066 24992 I System.out: Route <route>: routing_time=23467.3, vehicle=car, base=true, start_lat=53.49709, start_lon=9.93312, target_lat=47.92297, target_lon=8.64918, complete_distance=792337.4, complete_time=25770.6, native=true
11-13 16:41:59.160 22066 24992 I System.out: Route <metrics>: tilesPerSec=1731.2, segmentsPerSec=57213.7
11-13 16:41:59.160 22066 24992 I System.out: Route <segments>: visited=1595453, queueDirectSize=302179, queueOppositeSize=201078, visitedDirectPoints=963172, visitedOppositePoints=797562
11-13 16:41:59.160 22066 24992 I System.out: Route <tiles>: loadedTiles=36283, loadedTilesDistinct=18304, loadedTilesMax=18304, loadedTilesPrevUnloaded=14300, unloadedTiles=29961
11-13 16:41:59.160 22066 24992 I System.out: Route <time>: timeToCalculate=48.9, timeToLoad=19.1, timeToLoadHeaders=1.9, timeToFindInitialSegments=0.0, timeExtra=0.0


11-13 16:42:33.258 22066 24992 I System.out: Route <route>: routing_time=23566.0, vehicle=car, base=false, start_lat=53.49709, start_lon=9.93312, target_lat=47.92297, target_lon=8.64918, complete_distance=793570.3, complete_time=26002.6, native=true
11-13 16:42:33.258 22066 24992 I System.out: Route <metrics>: tilesPerSec=1265.2, segmentsPerSec=3455.8
11-13 16:42:33.258 22066 24992 I System.out: Route <segments>: visited=96133, queueDirectSize=80848, queueOppositeSize=-144794, visitedDirectPoints=171994, visitedOppositePoints=1871118
11-13 16:42:33.258 22066 24992 I System.out: Route <tiles>: loadedTiles=8073, loadedTilesDistinct=8073, loadedTilesMax=26377, loadedTilesPrevUnloaded=0, unloadedTiles=29961
11-13 16:42:33.258 22066 24992 I System.out: Route <time>: timeToCalculate=34.2, timeToLoad=6.1, timeToLoadHeaders=0.3, timeToFindInitialSegments=0.1, timeExtra=0.0

```

November maps

**Comment by vshcherb** [comment]
Going to regenerate full europe at least. Should be available all tomorrow - just to redownload maps (date will be the same)

**Comment by vshcherb** [comment]
@pahervin just regenerated today 3 hours ago, redownloaded maps and they started working. Yesterday maps were not fully reverted yet.

**Comment by vshcherb** [comment]
@pahervin just regenerated today 3 hours ago, redownloaded maps and they started working. Yesterday maps were not fully reverted yet.

**Comment by teilzeitutopist** [comment]
I was also very irritated and support the idea of @scaidermern: Only a small portion of people will check here for a solution.

**Comment by pahervin** [comment]
> @pahervin just regenerated today 3 hours ago, redownloaded maps and they started working. Yesterday maps were not fully reverted yet.

@vshcherb I downloaded again the maps.
There is no noticeable change with route calculation.

**Comment by vshcherb** [comment]
@pahervin then it must be a different issue, I can attach october example maps though the process is exactly the same right now for latest maps as for September maps. 

@scaidermern timestamp couldn't be updated cause they are related to OsmAnd Live.
