### ISSUE TITLE
Texts and poi from the vector map offline in "source map"over the "overlay map" with OpenGL enabled 

### ISSUE THREAD

**Issue by bobeeeze** [osmandapp/OsmAnd#15675]
When the opengl mode is activated, if I put the vector map offline in "map source" and an opaque map in "overlay map", all the texts and the poi appear on top when they should be below. This does not happen when OpenGL mode is disabled and I think that should be the normal behavior because if I want to put the text and poi on top, I would put the opaque map in the underlay map.

![opengl disabled](https://user-images.githubusercontent.com/59626956/200415996-251598fd-c2d1-4edc-98ca-2eb0069d4258.jpg)
![opengl enabled](https://user-images.githubusercontent.com/59626956/200416001-d47a8bc9-6947-4503-a2e3-6e6ff871b173.jpg)

My Environment
OsmAnd Version: Osmand+ 4.2.7 released 2022-07-13
Android version: 11
Device model: Xiaomi Mi9T Pro

I use vector map offline in "map source" and any satellite map in "overlay map"

I take this opportunity to tell you that the text is worse in OpenGL mode than in normal mode. The highlighting is cut off in some places.

**Comment by vshcherb** [comment]
You can configure in 4.3 how text labels should be displayed transparent or not
