### ISSUE TITLE
Change URL from https://osmand.net/go to https://osmand.net/map

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15681]
- [x] Change URL from https://osmand.net/go to https://osmand.net/map (Share POI and check code)

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd/pull/15744
https://github.com/osmandapp/OsmAnd-iOS/pull/2316

**Comment by nnngrach** [comment]
Bug founded: 

If you copy this url in OsmAnd search field then it find correct point.
https://osmand.net/go?lat=56.638649&lon=47.911657&z=15

But with new url founded point is incorrect.
https://osmand.net/map?pin=56.638649,47.911657#15/56.638649/47.911657

In Android fixed this in GeoPointParserUtil.java class. It looks like a correct place for this.
https://github.com/osmandapp/OsmAnd/pull/15744/files#diff-60b56077fd935c8b35b85e7a4dd1d3c4008025cd8a789e53d4d71c98ac8fe900R260

But in IOS we don't have GeoPointParserUtil class at all. May be it should be implemented.
https://github.com/osmandapp/OsmAnd-iOS/blob/master/Sources/Search/OASearchCoreFactory.mm#L2036
