### ISSUE TITLE
Map Rendering v1: Broken coastline rendering

### ISSUE THREAD

**Issue by robinpaulson** [osmandapp/OsmAnd#15697]
Near Glendowie, Tamaki Makaurau, Aotearoa

36.85592° S, 174.87900° E

![](https://i.imgur.com/tuRmjxM.png)

**Comment by robinpaulson** [comment]
V4.2.7 from fdroid, on lineage 16

**Comment by Zirochkabila** [comment]
Reproduced only when **OpenGL disabled**
OsmAnd~ 4.3.0#13943mqta, released: 2022-11-12


https://user-images.githubusercontent.com/104760013/201493432-313d76e2-a007-4f4d-8ba8-615e94a08de3.mp4



@robinpaulson Try to enable OpenGL rendering: Menu > Plugins > OsmAnd development > Settings > Use OpenGL rendering > Switch on/off > Restart OsmAnd

**Comment by robinpaulson** [comment]
It was unbearably slow, difficult to test the area properly. I also got a "native library not available on thus device".

**Comment by robinpaulson** [comment]
So long as it's my old, slow device at fault, I suppose the bug can be ignored. Thanks for testing

**Comment by robinpaulson** [comment]
I'll try again when v430 hits the tubes, but I doubt there will be much difference

**Comment by robinpaulson** [comment]
I tried v433, it would not render at all. I'm using a galaxy s5, so no surprise. Thanks for assistance, closing

**Comment by sonora** [comment]
It looks like @Zirochkabila has reproduced this all right so I suggest this should not be closed on the grounds of it being device-specific?

**Comment by vshcherb** [comment]
Nope this ticket likely being closed because we know that Legacy rendering has issues with detailed coastline when basemap coastline (specially on islands) is not precise, as it's very consuming time we're not going to fix it on Legacy rendering (OpenGL works fine).

**Comment by robinpaulson** [comment]
"Legacy rendering has issues with detailed coastline when basemap coastline (specially on islands) is not precise"

How can e rectify this, in the instance above? I.e. what level of precision would not cause problems?

**Comment by vshcherb** [comment]
The issue is closed as not going to be fixed, not "as we can't reproduce" or "it's impossible to fix". It's just an example that v1 rendering will be slowly out of support
