### ISSUE TITLE
regionwide maps doesn't show correclty for the Philippines

### ISSUE THREAD

**Issue by govvin** [osmandapp/OsmAnd#15702]
# 🚀 feature request

### Description

Currently, to downloading the maps for the Philippines, it only shows the standard map that covers the whole country.

Below is comparison of the download section for the Philippines with Japan.
| Philippines | Japan| 
| --- | --- |
| ![image](https://user-images.githubusercontent.com/5821688/201457363-6edf9662-34c0-4e05-a290-067297831769.png) | ![image](https://user-images.githubusercontent.com/5821688/201457499-8ef5e662-50b4-4251-95d4-3abeb19c1494.png) | 

Currently, I've noticed that there are sub-national maps for the Philippines under "Other data". 
| | |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/5821688/201457524-975f3d9c-312e-4502-b0ae-888296ead5b1.png) | ![image](https://user-images.githubusercontent.com/5821688/201457527-bf731550-df88-4430-940e-99f9da74d180.png) 

So perhaps, this is something that can be further improved?

### Describe the solution you'd like

The Philippines has 17 [regions](https://en.wikipedia.org/wiki/Regions_of_the_Philippines), which might be too many, but perhaps it's possible to divide these at least [4 super regions](https://en.wikipedia.org/wiki/Super_regions_of_the_Philippines)?

### Describe alternatives you've considered

There's also the traditional grouping of 4 regions: Luzon, Visayas, Mindano, plus the capital region, Metro Manila. 

---

Is there anything I can do to help? For example, maybe submit the boundaries for the super regions to make this possible soon?

**Comment by vshcherb** [comment]
Issue is already fixed you can find maps in Other maps

**Comment by govvin** [comment]
Like I said, why is it in "other maps" and not the country page?
