### ISSUE TITLE
SpyWare?

### ISSUE THREAD

**Issue by SergeyDjam** [osmandapp/OsmAnd#15703]
Hello, new release blocked play market google as spyware!

**Comment by X-dark** [comment]
Same thing for F-droid version

**Comment by vshcherb** [comment]
Don't see any issue in Google Play console 4300 is available - around 25000 installs happened.

Please provide more information to make it actionable

**Comment by teohhanhui** [comment]
![Screenshot_20221113-234338](https://user-images.githubusercontent.com/548843/201533330-b34553a1-c90e-4a55-bb66-717ab0b9fb70.png)

Steps to reproduce:

1. Try to update to the latest version of the app in F-Droid.

This is on Android 13, though I doubt it makes any difference considering it's Google Play Protect.

**Comment by vshcherb** [comment]
This is a problem of Google Play protect which wants you to install via Google Play the decision needs made by you and not related to OsmAnd I guess

**Comment by SergeyDjam** [comment]
Hmm, https://www.virustotal.com/gui/file/1f963a277788c3a5cedab9c79ebe7a7364d4437234374a89baab55d4f20e302c/detection 
clean
