### ISSUE TITLE
Offline Routing Ignores Barrier=Gate

### ISSUE THREAD

**Issue by Zian** [osmandapp/OsmAnd#15700]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Car

### Start and end points

Start:
- EmbroidMe, Balboa Avenue, San Diego, San Diego County, California, 92133, United States
- https://www.openstreetmap.org/node/2769573238

End:
- Walmart, 4840, Shawline Street, San Diego, San Diego County, California, 92111, United States
- https://www.openstreetmap.org/way/31844637

### Actual and expected routes

Expected  Route:
Something like https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=32.8223%2C-117.1582%3B32.8297%2C-117.1649#map=16/32.8258/-117.1609&layers=N

In other words:
1. Start on unnamed road
2. Sharp left onto unnamed road
3. Turn right onto Balboa Avenue
4. Slight left onto unnamed road
5. Slight left onto Ruffner Street
6. Turn left onto Ronson Road
7. Slight right onto Shawline Street
8. Turn left onto Shawline Court
9. Reach destination

Actual Route (paraphrased to be more meaningful than "Head straight"):
1. West on the parking lot aisle towards C3 Church.
2. Make a stretched out u-turn to head north towards Public Storage Self-Storage.
3. Smash the car through the gate (already marked as barrier=gate, access=customers).
4. Turn slightly left to continue driving northbound.
5. Turn right on Dagget Street.
6. Turn left onto Ruffner Street.
7. Turn left onto Ronson Road.
8. Turn right onto Shawline Street.
9. Turn left into the driveway close to the garden center.
10. Follow the road until you are lined up with the center of the building.
11. Turn right and [drive through the store until you arrive near the jewelry section](https://github.com/osmandapp/OsmAnd/issues/7520).

### Is this a regression?

Not sure.
 Yes, the previous version in which this bug was not present was: ....

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>
OsmAnd+ 4.2.7
</code></pre>

**Device and Android/iOS version:**
Device: ONEPLUS A5000
Android version: 9

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.

Name: Us_california_northamerica
Date: Oct 31, 2022
- [ ] Online (tile / raster) maps 

**Anything else relevant?**
If there is special logic related to access=customer, then perhaps that logic should only apply when the destination matches the building or area that contains the node with the barrier.

**Comment by Zirochkabila** [comment]
Judging by your link to the expected result [Expected](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=32.8223%2C-117.1582%3B32.8297%2C-117.1649#map=16/32.8259/-117.1560&layers=N, ) the actual result is the same as expected [Actual](https://osmand.net/map/?start=32.822368%2C-117.158176&end=32.829558%2C-117.164801&mode=car#17/32.82638/-117.15785)

Voice prompts are generated based on the road data, not on the surrounding objects.

Regarding the Barrier=Gate tag, you can see in the screenshot that OsmAnd builds a route through the gate/barrier
<img width="1133" alt="Screenshot 2022-11-16 at 17 32 03" src="https://user-images.githubusercontent.com/104760013/202223498-29727fd8-cdc3-4bb3-b89e-f62a02d6561e.png">

But, one voice prompt is missing (as the arrow in the widget), although it is in the link to the OSM route. This can be seen in the attached video - @vshcherb what do you think about this?

https://user-images.githubusercontent.com/104760013/202224373-1f9b18c0-eb95-46fe-a910-da80ce68c569.mp4

**Comment by vshcherb** [comment]
Closed

**Comment by Zian** [comment]
> Judging by your link to the expected result [Expected](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=32.8223%2C-117.1582%3B32.8297%2C-117.1649#map=16/32.8259/-117.1560&layers=N,) the actual result is the same as expected [Actual](https://osmand.net/map/?start=32.822368%2C-117.158176&end=32.829558%2C-117.164801&mode=car#17/32.82638/-117.15785)
> 
> Voice prompts are generated based on the road data, not on the surrounding objects.
> 
> Regarding the Barrier=Gate tag, you can see in the screenshot that OsmAnd builds a route through the gate/barrier <img alt="Screenshot 2022-11-16 at 17 32 03" width="1133" src="https://user-images.githubusercontent.com/104760013/202223498-29727fd8-cdc3-4bb3-b89e-f62a02d6561e.png">
> 
> But, one voice prompt is missing (as the arrow in the widget), although it is in the link to the OSM route. This can be seen in the attached video - @vshcherb what do you think about this?
> telegram-cloud-document-2-5452086306504974173.mp4

I don't understand why you think the expected and actual routes match.

I've included a screenshot from OpenStreetMap below.

![Expected Route](https://user-images.githubusercontent.com/1581929/204063555-ede6a29d-0d49-4bf2-be08-c6e3c433dea8.png)

**Comment by vshcherb** [comment]
Both routes are ok - https://www.openstreetmap.org/node/9515255265 it doesn't block access to customers os it means it's passable there is no high cost for gates cause the need to be used sometimes. The penalty is just +20 seconds but speed is very limited on this roads  - https://www.openstreetmap.org/way/128827245 (5 mph) where https://www.openstreetmap.org/way/158308129 it's assumed (10-15 mph). So maxspeed can be changed and it can change the route

**Comment by Zian** [comment]
> Both routes are ok - https://www.openstreetmap.org/node/9515255265 it doesn't block access to customers os it means it's passable there is no high cost for gates cause the need to be used sometimes. The penalty is just +20 seconds but speed is very limited on this roads - https://www.openstreetmap.org/way/128827245 (5 mph) where https://www.openstreetmap.org/way/158308129 it's assumed (10-15 mph). So maxspeed can be changed and it can change the route

You're right; as long as someone is a customer at the self-storage, they can enter a code and the barrier will open.

In this GitHub issue, the destination (https://www.openstreetmap.org/way/31844637) is not the self-storage place. Instead, it is a Wal-Mart that is approximately 0.6 miles away.

OsmAnd should not tell its users to break through a business's gates while driving to an unrelated destination.
