### ISSUE TITLE
Key:note text displayed on map

### ISSUE THREAD

**Issue by poeticus** [osmandapp/OsmAnd#15706]
### Description
I've noticed at least a couple of instances where key:note text is being displayed on maps. 
A search here produced just one similar issue from 2018 (#5596) which was closed as resolved.
Both examples here are in England.
1. Oxford: 51.75494° N, 1.25448° W
Relates to Way 356368085
2. Leeds: 53.79889° N, 1.53975° W
Relates to Node 7275677007

### How to reproduce?
View maps at stated locations.

### Your Environment
OsmAnd Version: 4.2.7
Android/iOS version: Android 11
Device model: Fairphone 3

**Maps used (online or offline):**   
Offline:
United Kingdom England South East England
United Kingdom England Yorkshire and the Humber

**Comment by vshcherb** [comment]
Fixed in 4.3
