### ISSUE TITLE
aboriginal_lands and border_zone are not displayed correctly

### ISSUE THREAD

**Issue by BikeRoad** [osmandapp/OsmAnd#15709]
I have been testing version 4.3.0 of osmand and the areas labeled as aboriginal_lands are not displayed correctly.

I have created test relationships.
Rendering:
The A/C/D figures were created with the tag type=multipolygon and the name is displayed
Figure B/E was created with the type=boundary tag and the name is not displayed.
*Is it correct that the color of the inner line is darker than the outer line of a relationship?
*Why are relationships of type protected_area not rendered in the default_render style?
<img src="https://user-images.githubusercontent.com/19896035/201537075-0fafb8e0-e868-4526-879e-fabe93f17f73.jpg"  width="300" height="auto"/> 
Search:
Both aboriginal_land and border_zone do not appear in the search results, regardless of how the relations have been created (multipoygon or boundary)
<img src="https://user-images.githubusercontent.com/19896035/201537504-625a5bc2-3bd5-485f-b04f-648477b19917.jpg"  width="300" height="auto"/>

Rendering style:
Please give support for aboriginal_lands and border_zone in Topo and Off road map styles, both don't show at all
<img src="https://user-images.githubusercontent.com/19896035/201477398-440421ff-250b-4e3d-9a85-ecc49662b4a8.jpg"  width="300" height="auto"/>

**Comment by vshcherb** [comment]
We don't render boundary only multipolygons please use tag transform if necessary.

**Comment by Zirochkabila** [comment]
Done
https://github.com/osmandapp/OsmAnd/issues/15907#issuecomment-1341175329
