### ISSUE TITLE
Refresh old maps tiles

### ISSUE THREAD

**Issue by gtrus21** [osmandapp/OsmAnd#15713]
В настройках тайлов есть параметр "время устаревания". Прошу добавить рядом с ним переключатель "при устаревании делать следующее" с вариантами: 
1) удалять данные и загружать новые
2) загрузить новые и заменить ими старые

В чем разница: при отсутствии интернета или плохой связи новые тайлы не смогут загрузиться. И тут два случая:
1) одни тайлы, такие как карта, высота и спутник, в случае их устаревания лучше иметь старые, чем не иметь их вообще
2) другие тайлы, такие как слой автомобильных пробок лучше не иметь никаких, чем иметь устаревшие (иначе они будут вводить в заблуждение)

Таким образом этот переключатель выбирает поведение тайлов в случае плохого интернета - ждать пока загрузятся свежие тайлы вместо старых или удалять старые сразу, даже если интернета нет

**Comment by vshcherb** [comment]
Please report issues in English.

**Comment by gtrus21** [comment]
In the tiles settings there is a parameter "expiration time".  Please add next to it a switch "on deprecation do the following" with options:

 1) delete data and upload new ones
 2) download new ones and replace old ones with them
 What is the difference: in the absence of the Internet or poor connection, new tiles will not be able to load.  And there are two cases:

 1) some tiles, such as map, altitude and satellite, in case of their obsolescence, it is better to have old ones than not to have them at all
 2) other tiles, such as the traffic jam layer, it's better to have none than to have outdated ones (otherwise they will be misleading)
 Thus, this switch selects the behavior of tiles in case of bad Internet - wait until fresh tiles are loaded instead of old ones or delete old ones immediately, even if there is no Internet
