### ISSUE TITLE
Input in Filter by name doesn't work

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15723]
### Description
If scroll all filters to the bottom - input in Filter by name stops working

### Steps to reproduce
Search > Climbing > Select Climbing sport > Options > Open all filter categories > Scroll down > Try to input something in Filter by name

### Actual result
Input in Filter by name doesn't work

https://user-images.githubusercontent.com/104760013/201680808-5ea1a66e-1698-4483-8b60-31981299c1fd.mp4

### Expected result
Input in Filter by name is working

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13945mqta, released: 2022-11-14
Android/iOS version: Android 12
Device model: POCO X3 NFC

**Comment by nazar-kutz** [comment]
**Pull Request**
https://github.com/osmandapp/OsmAnd/pull/16019

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14057mqta, released: 2022-12-28
Done
