### ISSUE TITLE
Unit of length and 'Nautical miles/feet', rename 'Nautical miles'

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#15724]
In screenshot 1 the unit of length is "nautical miles" which is indeed what is showing for distances and range rings, however the unit is for altitude meters and not feet.

In screenshot 2 the unit of length is "miles/feet". This allows me to get altitude in feet, however as you can see the distances and range rings are now in miles (1 mile = 1609 meters) and not in nautical miles (1 nautical mile = 1852 meters).

<table style="width:100%">
  <tr>
    <th>1</th>
    <th>2</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/80623554/201682325-ab4a757d-c1a2-4ba7-aae9-01f6e432fcb2.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/80623554/201682416-aa4e6be3-b8ad-4837-98ae-1a197c46ba60.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by dmpr0** [comment]
## ToDO
We need to add to add new **Unit of length** and rename current **Nautical miles**
- [ ]  Rename **Nautical miles** to **Nautical miles/meters**
- [ ] Add **Nautical miles/feet**

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14074mqta, released: 2023-01-05
Done

**Comment by EugeneZmeuk** [comment]
https://osmand.net/docs/user/personal/profiles#units--formats
