### ISSUE TITLE
Application crashes

### ISSUE THREAD

**Issue by GuentherGredy** [osmandapp/OsmAnd#15734]
### Description

The application crashes from time to time. It stays frozen, no user action accepted. Fortunately the termination of the application works and it can be recovered by re-starting it.

### How to reproduce?

There is nothing significant up to now (I'll keep you informed). Yet, a bit more often than in other use cases it crashes zooming into a high map resolution and tipping on the map.

### Your Environment
OsmAnd Version: 4.2.7
Android/iOS version: 9
Device model: LG G6
Map: Deutschland Baden-Württemberg from 01.11.2022

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by scaidermern** [comment]
Do you have OpenGL enabled and visible tracks? Then this could be #14715 and/or #15486

**Comment by vshcherb** [comment]
Without crash information we will treat as a duplicate to other crashes. Many crashes are coming now, so there is a high chance it will be fixed.
