### ISSUE TITLE
OpenGL + live: POI names not updated until app restart

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#15730]
Live updates don't update the name of POIs. The POI details show the new name while the map still shows the old name.

![IMG_20221115_081103](https://user-images.githubusercontent.com/1040784/201854094-c7af76f9-048d-4332-91b4-9314d963bdcd.jpg)

After restarting OsmAnd the new name is also shown on the map.

OsmAnd 4.3.0, OpenGL enabled.

**Comment by vshcherb** [comment]
I think it's a duplicate issue for map OpenGL + OsmAnd Live, so you need to restart the app

**Comment by scaidermern** [comment]
Maybe, but which one is the other ticket?

**Comment by scaidermern** [comment]
For the sake of completeness: An app restart isn't enough. Sometimes the old POI name still reappears.

**Comment by vshcherb** [comment]
At least this https://github.com/osmandapp/OsmAnd/issues/14920 and this https://github.com/osmandapp/OsmAnd/issues/14339
