### ISSUE TITLE
Incorrect interpretation of motorway exit roads

### ISSUE THREAD

**Issue by sdfg2** [osmandapp/OsmAnd#15739]
### Description
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=55.9201%2C-3.3222%3B55.8393%2C-3.9145#map=10/55.8849/-3.6184 

I *think* I see what is happening.  There is an exit from Motorway M8, which later bifurcates.  Osmand is interpreting this as the motorway continuing in four lanes, which is incorrect. I have no idea how to do detailed checks on OSM data, but using the query tool I can see that what Osmand is interpreting as 4 lanes is actually 2 roads with 2 lanes each, and labelled individually - `Motorway M8` and `Motorway Road M8`.  The navigation instructions should only refer to `Motorway Road M8` if it needs to be taken, otherwise it should be ignored.

Not sure if this is an OSM problem or Osmand problem though.

### How to reproduce?
Plot the route as linked.
Look at the navigation instructions.

### Your Environment
OsmAnd Version: 3.9.0#12417mqta
Android/iOS version: 10/13
Device model: joan/sm-t970

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

United Kingdom Scotland 1 Nov 2022

**Comment by vshcherb** [comment]
OsmAnd is already 4.3 version testing on 3.9 is quite outdated.

**Comment by sdfg2** [comment]
How bizarre!  Fdroid hadn't been updating.  I even had to do an uninstall-reinstall to get the latest version working.

Anyway yeah, just tested and it doesn't do it any more.  Sorry for the confusion!
