### ISSUE TITLE
A white widget is displayed on the left side of the screen

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15733]
### Description
After opening the navigation context menu - a white widget is displayed on the left side of the screen

### Steps to reproduce
(Widgets should be added to the left side of the screen) Press at Navigation button > Reduce the size of the context menu

### Actual result
A white widget is displayed on the left side of the screen

https://user-images.githubusercontent.com/104760013/201885601-11355710-5ae4-4ba7-a46c-8c545c5437fd.mp4

### Expected result
The left part of the screen looks similar to the right

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13948mqta, released: 2022-11-15
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by vshcherb** [comment]
Duplicate to widget state
