### ISSUE TITLE
Wikivoyage: search won't find all articles

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#15745]
Some articles are missing from Wikivoyage. For example there is no entry for London/Bloomsbury although there is a Wikivoyage article for it: https://en.m.wikivoyage.org/wiki/London/Bloomsbury. The same for London/Covent Garden: https://en.m.wikivoyage.org/wiki/London/Covent_Garden

Not sure if this is related to any of the other existing issues for Wikivoyage.

**Comment by scaidermern** [comment]
I just noticed that the article for Bloomsbury exists. You can navigate to it from the London article via the paragraph "Districts". However, you can't search for it. The same for the previously mentioned Covent Garden.

**Comment by vshcherb** [comment]
Finally fixed I think

**Comment by vshcherb** [comment]
Ready to test with new files

**Comment by dmpr0** [comment]
Done 

<details>
    <summary>Android</summary>
    <table style="width:100%">
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/0e83b2ce-2cdf-42ca-ba92-ad1d8042588f"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/68dbf111-6fc8-4154-b9a0-93813f95bd5f"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

<details>
    <summary>iOS</summary>
    <table style="width:100%">
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/7dc92941-cab3-44c0-8b6b-7450526a5248"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/ca6ca487-78fd-43a0-95e7-35fdf1afa9f1"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>

**Comment by scaidermern** [comment]
Looks better now I guess.

But the search is still a mystery to me. Searching for "London Bloomsbury" doesn't return any result. Searching for "London/Bloomsbury" does, probably because this is the exact name of the article.

Is this the supposed behavior? Seems odd since the user usually don't know the exact name of the article.

**Comment by vshcherb** [comment]
Bloomsbury or  London finds just fine . I think nobody will search full name in first place if is not familiar with Wikivoyage
