### ISSUE TITLE
Wikivoyage: No POI if coordinates are taken from Wikidata

### ISSUE THREAD

**Issue by muekoeff** [osmandapp/OsmAnd#15742]
### Description
German Wikivoyage increasingly uses Wikidata exclusively for specifying coordinates of [{{vCard}}s/Listings](https://de.wikivoyage.org/wiki/Vorlage:VCard) and [{{Marker}}s](https://de.wikivoyage.org/wiki/Vorlage:Marker) and elides explicitly declaring them in the Wikitext. Although currently less common in English Wikivoyage, for [{{Listing}}](https://en.wikivoyage.org/wiki/Template:Listing) and [{{Marker}}](https://en.wikivoyage.org/wiki/Template:Marker) it is also possible to use coordinates from Wikidata *(“With the current behavior of {{marker}}, this means that explicit lat and long values are unnecessary if such values exist on the associated Wikidata item.”)*.

Due to this, OsmAnd travel guides do not have an „Open on map“-button and POI for affected listings.

### How to reproduce?
* Open German travel guide for [Trier](https://osmand.net/travel?title=Trier&lang=de) in OsmAnd
* Scroll to section „Sehenswürdigkeiten“
* Expand section

| Web | OsmAnd |
| - | - |
| ![Wikivoyage-Trier-Sehenswürdigkeiten](https://user-images.githubusercontent.com/3207399/202175780-c399197b-a95d-4462-9175-d896f2968e16.jpg)<br/>[Permalink](https://de.wikivoyage.org/w/index.php?title=Special:Permalink/1467817) | ![OsmAnd-Trier-Sehenswürdigkeiten](https://user-images.githubusercontent.com/3207399/202176169-1cdba315-0138-44a3-b418-a2c11b747f99.jpg) |

Note, that in the examples above for the first 6 listings no coordinates are declared in the Wikitext. Only for the last listing „Synagogue Trier“ coordinates are explicitly declared. Simplified excerpt from Wikitext for last two listings:
```wikitext
* {{vCard | type = church | name = Benediktinerabtei St. Matthias | wikidata = Q666976 | description = Dort wird die […]
}}
* {{vCard|type=synagogue |name=Synagogue Trier |wikidata=|auto= |lat=49.75074 |long=6.63453 |description=
}}
```

### Your Environment
OsmAnd Version: 4.2.7
Android/iOS version: —
Device model: —

**Maps used (online or offline):**   
Offline map: Deutschland Rheinland-Pfalz / Germany Rhineland-Palatia, 01.11.2022
Offline travel guide: Europa Wikivoyage / Europe Wikivoyage, 29.08.2022

(Excerpts of travel guides taken from German Wikivoyage, [Contributors](https://de.wikivoyage.org/w/index.php?title=Trier&action=history))

**Comment by vshcherb** [comment]
Ready to test with new files

**Comment by dmpr0** [comment]
Done

<table style="width:100%">
      <tr>
        <th>Android</th>
        <th>iOS</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/42303889-cb15-4065-85a0-9fdc24431802"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/8d503ae8-1ffa-4d76-b807-afcde85a2e7a"  width="300" height="auto"/> </td>
      </tr>
</table>
