### ISSUE TITLE
Crash when taping on the map

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#15755]
### How to reproduce?
just tap on the map...

### Your Environment
OsmAnd Version:  OsmAnd~  4.3.0#34948m.apk (android-ful)
Android version: 10
Device model: samsung tab s5e

[exception.log.zip](https://github.com/osmandapp/OsmAnd/files/10029420/exception.log.zip)

**Comment by pebogufi** [comment]
The crash only happens if Heightmap is activated (plugins / OsmAnd development / first option on top of page).

**Comment by vshcherb** [comment]
Android full doesn't have opengl version so Heightmap couldn't be activated same as Altitude version.

**Comment by pebogufi** [comment]
Which nightly version should be used for openGl and 2.5D ?
OsmAnd-opengl-arm64-nightly.apk ? (My samsung is arm64)

**Comment by cepprice** [comment]
@pebogufi Yes
