### ISSUE TITLE
Android 6 not supported Date Format XXX

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15760]
### Description
The track being recorded is displayed without data after opening it in the tracklist.
It seems that the reason is in the time format on the device.
When importing tracks, an error unknown pattern character 'X' occurs, as it became clear, it is related to the date piercing in gpx https://stackoverflow.com/questions/28373610/android-parse-string-to-date-unknown-pattern-character-x
There is a possibility that this happens with rare smartphone models (Android n and Android 6 out of support)

This GPХ loads fine (it has removed the date tags)
![photo_2022-11-17 16 53 24](https://user-images.githubusercontent.com/104760013/202479206-0d05a11e-093f-4b4c-b634-a51f003a6678.jpeg)

And this one (initial, with dates) displays an error
![photo_2022-11-17 16 55 15](https://user-images.githubusercontent.com/104760013/202479734-67b98e27-91e7-4698-8f06-0de8b7e08713.jpeg)

Perhaps it is somehow related to this task [Importing GPX/KML ignores timestamps with timeoffset](https://github.com/osmandapp/OsmAnd/issues/15271) because after fixing this problem, the one described above appeared

**Comment by Vanooname** [comment]
Phone model - Huawei Mediapad X2 GEM-703L
Android version - 6.0

**Comment by Vanooname** [comment]
Thanks! There is no problem on the latest version of the night release.
