### ISSUE TITLE
Translation of words and stuff.

### ISSUE THREAD

**Issue by franco999** [osmandapp/Osmand#1577]
* I found several phrases of words untranslated and are not in Weblate.
![3](https://cloud.githubusercontent.com/assets/12088580/9413896/31a68c66-480b-11e5-8850-13c0677aa229.png) Done!
![2](https://cloud.githubusercontent.com/assets/12088580/9413897/31b22fd0-480b-11e5-87a5-a73954b713f3.png) Done!

* and others that do not appear in the detail section of the PDI as some tags with the prefix "contact" and others like facebook and twitter seen previously, but not anymore. Please correct that.
![1](https://cloud.githubusercontent.com/assets/12088580/9413895/3196694e-480b-11e5-8a8b-ab3d7bfc31d3.png)

* One suggestion I would make them regarding street addresses, would be to show street and number instead of just the number, for more information. For example - Address: San Martin 1234
![4](https://cloud.githubusercontent.com/assets/12088580/9414287/af87d002-480d-11e5-9e03-f9c91c44ca3d.png)

**Comment by xmd5a2** [comment]
Done https://dl.dropboxusercontent.com/u/4624786/osm/Screenshot_2015-08-22-21-17-09.png
Also "mill pond".

**Comment by franco999** [comment]
Perfect! Already the added words were translated. Thank you. 
Later I try to install the version of OsmAnd already translated.

**Comment by xmd5a2** [comment]
I created an issue related to this
https://github.com/osmandapp/Osmand/issues/1584

**Comment by xmd5a2** [comment]
*Missing complete the translation of the first image.
Done

**Comment by franco999** [comment]
@xmd5a2 Why not show me yet labels social networks and the that have the suffix "contact"? Do you see them?

**Comment by xmd5a2** [comment]
1)You need nightly build
2)You need new maps

**Comment by franco999** [comment]
Done, outdated map.
