### ISSUE TITLE
Small UI glitches in voice output settings

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#15773]
Go to Configure profile / Navigation settings / Voice prompts / Voice guidance output.

(1) Change the option, ignore the subsequent popup "Apply to all profiles": While the settings change seems correctly applied in the backend, the menu subtext is not updated and still indicates the previous state. If this irritates you, and you tap on it again, even the radio button dialog opening up will again (falsely) indicate the previous state. (If you change it **again**,  now the display finally gets updated.)

(2) Unless I am mistaken, in this same procedure tapping the option "Apply to all profiles" does not seem to work at all.

**Comment by dmpr0** [comment]
## ToDo
- [ ]  Update value of **Voice guidance output** right after change.

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><video source src="https://user-images.githubusercontent.com/9365308/207341134-d4b9cdde-3dc0-4b93-a480-1a8a2141d511.mp4
"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14066mqta, released: 2022-12-31
Done
