### ISSUE TITLE
Cannot upgrade from version 4.2.6 to 4.2.7

### ISSUE THREAD

**Issue by gszy** [osmandapp/OsmAnd#15778]
OsmAnd version: 4.2.6 ([F-Droid](https://f-droid.org/packages/net.osmand.plus/))  
Android version: 10 (LineageOS)  
Device model: Motorola Moto G (2015)

I cannot upgrade from 4.2.6 to 4.2.7 using F-Droid. After downloading the APK, the installation window appears, there I tap "Install" and it seems to work for some time. When it approaches the end, a failure message appears: "Failed to install due to unknown error".

As a workaround, I can uninstall 4.2.6 and then install 4.2.7 successfully. (Feel free to close this bug if there is no easy solution; I hope at least the workaround will help someone stumbling upon the same issue.)

**Comment by scaidermern** [comment]
I guess this is the wrong ticket tracker since the f-droid build is not maintained by the OsmAnd team.

**Comment by gszy** [comment]
Quite likely, let's try here:
https://gitlab.com/fdroid/fdroidclient/-/issues/2467
