### ISSUE TITLE
Gray out but never hide the OpenGL renderer option

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#15774]
Carry over from #15715:
- [ ] Keep the "_Map rendering engine_" setting  always visible, for all builds and setups.
- [ ] Where not available, gray out but do not hide the line option"_Version 2 (OpenGL)_".

We will follow the convention is that a grayed-out line indicates a menu option we want users to see, or users may anyway expect to see, but the option is not available under the current circumstances. This could be due to
- other conflicting settings being set,
- the device/system/setup not supporting it,
- or the current build not supporting it.

**Comment by vshcherb** [comment]
1st we didn't agree -  Keep the "Map rendering engine" is only visible when build has opengl library support.

**Comment by sonora** [comment]
Apologies if I misinterpreted https://github.com/osmandapp/OsmAnd/issues/15715#issuecomment-1320880437. I still think it"s a good idea. 😉

**Comment by vshcherb** [comment]
Let's keep that open, once we see that people have consistent opengl failures while it's present it will be important to implement.

I believe we shouldn't have Map Rendering engine if it's not part of the build (it could be probably indicated somehow differently). So in the end we probably need 3 states: ok, failed due to lack of code, failed sporadically.

**Comment by sonora** [comment]
I've walked through our code and I think we have the following gap, which may go unnoticed:

If something goes wrong we reset USE_OPENGL_RENDER here
 https://github.com/osmandapp/OsmAnd/blob/ccd9100a08a87380720b25c1974e54e4d86b0f97/OsmAnd/src/net/osmand/plus/AppInitializer.java#L760-L763

but this code is only executed if
https://github.com/osmandapp/OsmAnd/blob/ccd9100a08a87380720b25c1974e54e4d86b0f97/OsmAnd/src/net/osmand/plus/AppInitializer.java#L751

So if for any known or unknown reason, (and it could be swapping builds and/or having set a false renderer in previous builds with the setting available) you end up in a configuration where e.g. `USE_OPENGL_RENDER=true `and `NativeCore.isAvailable()=false`, our code would never rectify that situation?

**Comment by sonora** [comment]
Here's the corresponding PR https://github.com/osmandapp/OsmAnd/pull/15842, maybe could also fix #15841.
