### ISSUE TITLE
Hierarchical organization of tracks

### ISSUE THREAD

**Issue by Vanooname** [osmandapp/OsmAnd#15772]
I suggest adding a hierarchical organization of tracks. Now there is only the possibility of a hierarchy of the first level, this is not enough. For example, I have more than 100 tracks stored for different countries. The hierarchy Country->Region (second level) would help a lot. For some regions (more than 30 tracks), the hierarchy Country->Region->District (third level) would help. In this case, I would have more than ten countries and each of them has more than five regions and several districts in them (some have more than 7 tracks). This functionality would greatly simplify the navigation of tracks, since now even searching through the list of top-level folders takes a lot of time and effort.

**Comment by scaidermern** [comment]
You can already as many subfolders and sub-subfolders as you like.

**Comment by vshcherb** [comment]
I think it's already implemented it's a question of visualization and accessibility of course

**Comment by Vanooname** [comment]
> I think it's already implemented it's a question of visualization and accessibility of course
I agree with you, this is a matter of visualization. In release 4.3.0, subfolders are displayed in the same list with root folders via "/". There is no benefit from such a functional hierarchy. It would be much more convenient for the subfolders to be displayed inside the root folder and it could be opened. Can this be implemented?

**Comment by scaidermern** [comment]
It is indeed quite strange to display a hierarchical directory structure in a completely flat layout.

**Comment by Vanooname** [comment]
In order to be able to change the interface, do I need to create a new ticket?

**Comment by sonora** [comment]
As I stated in https://github.com/osmandapp/OsmAnd/issues/11983#issuecomment-1318995326, I think the proper solution is already suggested in this epic https://github.com/osmandapp/OsmAnd-Issues/issues/910. I think this link may be access-restricted, here are the decisive screenshots:

![189943715-a483eb2b-efff-4779-b2fe-ff4746602be9](https://user-images.githubusercontent.com/845735/203257012-1f7e67f5-f771-4910-ab4e-d0b2019571dd.png) ![189906961-90052690-7f69-4c56-b8c6-5f15222794ce](https://user-images.githubusercontent.com/845735/203256817-53349b45-b416-43c2-9aa0-6942a7630149.png)
