### ISSUE TITLE
Enable or disable the weather plugin

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#15789]
Why do we need a weather confirmation dialog at all?  When you press the turn off button in it, the indication of whether the plugin is enabled starts to work incorrectly.

Also, when the plugin is turned off, the corresponding item does not disappear from the map settings.

https://user-images.githubusercontent.com/12549744/203119876-ac7ab22f-00bf-47f1-a604-d5a1849b30b6.mp4

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13962mqta, Дата выпуска: 2022-11-21
Android version: 12
Device model: poco f3

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.3.0#13973mqta, released: 2022-11-25
[logcat (25).log](https://github.com/osmandapp/OsmAnd/files/10092949/logcat.25.log)


Perhaps the point is this
<img width="853" alt="Screenshot 2022-11-25 at 14 59 10" src="https://user-images.githubusercontent.com/104760013/203991052-1e64b24a-1cd7-4154-9665-1006f26d8bd3.png">

**Comment by vshcherb** [comment]
@Zirochkabila nope this is something else devonly

**Comment by Nine-Tailed** [comment]
A similar problem in the plug-in external sensors.
I did not understand the purpose of the appearance of an additional dialog when these two plugins are enabled.
![Screenshot_2022-11-27-14-31-51-919_net.osmand.plus~2.jpg](https://user-images.githubusercontent.com/12549744/204132994-ddf4b4e5-5eda-4015-af4d-d0af41b3eda6.jpg)

**Comment by vshcherb** [comment]
To do: 
- [ ] For standard plugins confirmation is only needed if plugin adds or suggest to add anything like profile / routing etc (Nautical plugin for example is needed, Weather / External Sensors not needed)
- [ ] Turn off button should disable plugin and update state of the screen but it doesn't now
