### ISSUE TITLE
Add support for photo booths (amenity=photo_booth)

### ISSUE THREAD

**Issue by Codain** [osmandapp/OsmAnd#15782]
# 🚀 feature request

### Description

Add rendering, searching and editing support for amenity=photo_booth.

### Describe the solution you'd like

- Have the objects displayed on the map
- Be able to select type "Photo booth" when editing/creating one
- Be able to search for them

### Describe alternatives you've considered

Not applicable

**Comment by xmd5a2** [comment]
Object to test: https://www.openstreetmap.org/node/11518538279#map=19/49.63468/6.21600
Map: Luxembourg

**Comment by yuriiurshuliak** [comment]
Currently, photo booths are displayed on the map and can be displayed in the search.

OsmAnd~ 4.7.0#1655m, released: 2024-02-23

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/c3e41fcb-9ce5-4f09-b7d5-4ad97de5871e"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/6bb87d9c-f1ec-41ea-ac11-9580a20064d7"  width="300" height="auto"/> </th>
  </tr>
</table>
