### ISSUE TITLE
Inconsistency in menu for Weather

### ISSUE THREAD

**Issue by ArjanOnwezen** [osmandapp/OsmAnd#15783]
### Description

Instead of toggle, text "on/off" is shown for weather plugin.

### How to reproduce?

Check menu

### Your Environment
OsmAnd Version: latest nightly

![IMG_20221120_231904](https://user-images.githubusercontent.com/44684169/202929472-f4fc513f-8957-46f9-a378-f979996e3d35.jpg)

**Comment by dmpr0** [comment]
Hello! Thank you for the feedback. 
You can disable **Weather** plugin in **Menu** - **Plugins**, in **Configure Map** – **Weather**, you can find a list of available weather layer each of it have it own switch.

Using list item with two actions like Terrain in your screenshots is a bad UX for my opinion. Not all users understand that clicking on switch and on left half will lead to different result.

**Comment by Nine-Tailed** [comment]
> Yes, it will be redesigned and if setting have additional option, the switch will be removed.

I noticed that the telegram client has the same menu system.
![Screenshot_2022-11-26-02-08-44-396-edit_org.telegram.messenger.jpg](https://user-images.githubusercontent.com/12549744/204062238-6bbfa7ab-c8a0-4fe6-8aa3-3b383b3512da.jpg)
