### ISSUE TITLE
missing map labels for restricted areas and restricted area marking at various zoom levels

### ISSUE THREAD

**Issue by astromatt42** [osmandapp/OsmAnd#15796]
This is a minor inconvenience that is probably easily resolved:
Restricted areas marked on the offline maps seem to be missing the labels that are present in OSM. Having these can be very useful when venturing off-road in some of these areas.
Case in point, the entire Nevada National Security Site (between Las Vegas and Tonopah in the US) is missing the Area labels and range names, which are all present in OSM. 
A second issue is that for some areas, at low (e.g. NSS above) and/or high zoom levels (e.g. Los Alamos complex), the marking for restricted areas disappears, this should really be present at all zoom levels all the time.

**Comment by Zirochkabila** [comment]
@astromatt42 Please clarify:
1. The device you use, OS version
2. Application version
3. Place coordinates 
4. A short video and screenshots where we could see the error

**Comment by astromatt42** [comment]
> 1. The device you use, OS version

Samsung Galaxy Note 10+ Android 12

> 2. Application version

4.2.7

> 3. Place coordinates

Nevada test site 

Los Alamos 35.86142° N, 106.31338° W

> 4. A short video and screenshots where we could see the error

Zoomed in - restricted area shown without area labels
![screen1-1](https://user-images.githubusercontent.com/52516083/203994914-160f9c62-049e-4e8b-afc4-9072659ee832.jpg)
Zoomed out - area markings not rendered - these should really visible for at least another two to three zoom levels up.
![screen1-2](https://user-images.githubusercontent.com/52516083/203994943-6b5d083e-e575-4231-83a6-86618d59a765.jpg)
Restricted area labels as in OSM, not shown in OsmAnd
![screen1-OSM](https://user-images.githubusercontent.com/52516083/203994954-aafbbc18-a89c-4b75-bd2c-2f243bc23a4d.jpg)
video 1
https://user-images.githubusercontent.com/52516083/203996572-ea685c5a-e2f9-44ae-b067-56cbd40e0bf6.mp4

video 2
https://user-images.githubusercontent.com/52516083/203996538-b5e8fe58-0be3-4fbf-9fbe-95533011f54b.mp4
zoomed out - restricted area marking visible
![screen2-1](https://user-images.githubusercontent.com/52516083/203994961-513b49af-37a1-4aa5-a2d0-6a5c9b8fe4fe.jpg)
zoomed in - restricted are markings gone (n.b. at the first site, the markings are visible down to the highest zoom level, as it should be - so somehow the markings here and in the case above are treated differently)
![screen2-2](https://user-images.githubusercontent.com/52516083/203994965-ffa63dde-3ce6-4ae1-af7b-c43fb61c6566.jpg)

Let me know if you need anything else to troubleshoot these or if the explanation is unclear.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.3.0#13973mqta, released: 2022-11-25

It is possible to reproduce when using Offline vector maps, but when selecting OsmAnd (online tiles) the map is displayed in the same way as on [OSM](https://www.openstreetmap.org/search?query=37.225182%2C%20-116.055749#map=10/37.1242/-116.0211) and [OsmAnd web](https://osmand.net/map/?end=48.326981%2C18.100072&mode=car#11/37.1838/-116.0829)


https://user-images.githubusercontent.com/104760013/204099468-be2d0abe-74ff-4fe3-8e00-7a898808f9a7.mp4

**Comment by astromatt42** [comment]
Yes indeed, with the online maps all areas are marked and visible at all relevant zoom levels. Can this be translated across to the off-line maps? Especially in remote areas without cell coverage, Osmand has been brilliant because it doesn't rely on online map access.

**Comment by Zirochkabila** [comment]
@vshcherb what do you think about it?

**Comment by vshcherb** [comment]
You need to download Full basemap to see areas on zoom < 8

**Comment by astromatt42** [comment]
Which map from the off-line map selection is the "full base"? Seems counter-intuitive that the standard map doesn't contain this. I would expect the roads-only map to be bare bones but the standard map should contain all available mapping data? By default it might make sense for some features to be turned off in the settings to declutter but I should be able to display all available mapping data.

**Comment by vshcherb** [comment]
1. Roads-only don't have all map data - only large areas
2. Also for zooms levels < 10, you need to download Full World overview Basemap which is > 10x of standard packaged in the app
3. This is done to minimize the size of the app

**Comment by astromatt42** [comment]
Thanks for the info! That's useful. I will see if I can create my own map files, using the available tools, that contain a full base map for selected areas.
Cheers

**Comment by sonora** [comment]
@astromatt42 Please note this concept: A state's/country's 'Standard map' contains the most map data, but only for zoom levels 10 and higher. What @vshcherb calls the "full basemap" above is simply what you find in the app under `Download maps > All downloads > World maps > World overview map`. And it's exactly what its name says: a more detailed global map containing _all_ countries but only at overview zoom levels. This is displayed for zooms <10, anywhere. A good one to have present on your devicein any case.

You observe 2 issues here:
 - (1) Our World overview map does not seem to contain the danger zones at all. Reasoning is likely that 99% of them globally are so small that they would not be visible anyway at these zoom levels. Not so in NV and NM .. 😉 @vshcherb I suggest we could include the bigger ones like we do for forests?
 - (2) At detailed zoom levels we do not display the danger area names, see screenshot from my device below with all needed maps present. @xmd5a2 That would require a small change in our default render xml, plus inclusion of the names in our offline standard map if not already there.
![Screenshot_20221206-090426_OsmAnd~](https://user-images.githubusercontent.com/845735/205858801-cf0753e4-2216-41f3-a6fd-eca65da4f4a0.jpg)

**Comment by xmd5a2** [comment]
`landuse=military` labels minzoom increased to 12. If you need labels on zooms 9-11 please use your own rendering style.

**Comment by sonora** [comment]
Thanks @xmd5a2 !

How about Victor stating above in https://github.com/osmandapp/OsmAnd/issues/15796#issuecomment-1339725279: _"In basemap we should include all polygon objects large enough"._  Is that implemented as well?

**Comment by vshcherb** [comment]
> "In basemap we should include all polygon objects large enough".
It's a matter of reviewing all tags, so we need to double check anyway
