### ISSUE TITLE
Bicycle routing missunderstanding

### ISSUE THREAD

**Issue by rkozlo** [osmandapp/OsmAnd#15803]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [x] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

bike, shortest
### Start and end points

https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=54.38223%2C18.47940%3B54.37591%2C18.52601
### Actual and expected routes
I expect to set route on cycleway but it aggressively route on regular road for cars. In this place it is really dangerous. As i talked with other mappers it is because of lack tag bicycle:use_sidepath(or something like that) but imho that tag redundancy is pointless when cycleway is near road. Especially when you are already on cycleway and it routes to leave it.

Will send screenshots later. Github editor seems to be broken. Can't even use graphical markdowns at that moment
### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
Don't know. Probably. Talked with other people on discord server and they know about such behavior and also complain
## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

4.2.7 Fdroid build
</code></pre>

**Device and Android/iOS version:**
Android
**Maps used (online or offline):**
offline

- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**
Hard to say. First report to osmand so sorry for problems but this routing is really annoying and i would not recommend this to any of my friends because it is not working good. In Poland cycling on road when there is near cycleway is forbiden.
Problem is only with osmr on openstreetmap. GraphHooper seems to not be affected

**Comment by rkozlo** [comment]
![Screenshot_20221122_205040](https://user-images.githubusercontent.com/44550015/203410570-c4124003-ecff-41c4-b2f4-921fe1855fe0.png)

**Comment by scaidermern** [comment]
You set the driving style to "shortest". Does this also happen if the driving style is "balanced"?

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.3.0#13973mqta, released: 2022-11-25
Reproduced
[OSM OSRM bicycle](https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=54.38223%2C18.47940%3B54.37591%2C18.52601#map=15/54.3763/18.5013)
[OSM GraphHopper bicycle](https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=54.3822%2C18.4794%3B54.3759%2C18.5260#map=14/54.3791/18.5002)

If activating the driving style **Shorter routers** - the route is built using the road
[OsmAnd Speed](https://osmand.net/map/?start=54.382351%2C18.479143&end=54.375826%2C18.526093&mode=bicycle#15/54.3795/18.5020) **cost 687**

https://user-images.githubusercontent.com/104760013/204000977-80caa075-baa4-4d5b-8862-3780fb619fd2.mp4

If activating the driving style **Balanced** - the route is built using bicycle paths
[OsmAnd Balance](https://osmand.net/map/?start=54.382351%2C18.479143&end=54.375826%2C18.526093&mode=bicycle#15/54.3796/18.5048) **cost 617**


https://user-images.githubusercontent.com/104760013/204002037-018b5eed-41ea-4f9a-aba3-2073e41920fb.mp4

**Comment by rkozlo** [comment]
Thanks for reply. As it routes "shortest" at all cost that means it is not really usable if few meters can cause this. Of course it is only my personal opinion.
I have encountered also a situation on balanced mode when it was avoiding highway=service in some places but right now it seems to be working as expected.
Again thanks for reply and i think i can close this issue  if it is the way it is designed. I'll report to osm.org probably if ti is the only mode i can use there.
By the way bicycle profile has to many voice instructions. Drive to the left side, slight twist. Probably i can tune settings, but with this default one i felt like using navigation for cars.
