### ISSUE TITLE
Refresh old maps tiles

### ISSUE THREAD

**Issue by gtrus21** [osmandapp/OsmAnd#15805]
In the tiles settings there is a parameter "expiration time". Please add next to it a switch "on deprecation do the following" with options:

1) delete data and upload new ones
2) download new ones and replace old ones with them

What is the difference: in the absence of the Internet or poor connection, new tiles will not be able to load. And there are two cases:

1) some tiles, such as map, altitude and satellite, in case of their obsolescence, it is better to have old ones than not to have them at all
2) other tiles, such as the traffic jam layer, it's better to have none than to have outdated ones (otherwise they will be misleading)

Thus, this switch selects the behavior of tiles in case of bad Internet - wait until fresh tiles are loaded instead of old ones or delete old ones immediately, even if there is no Internet

**Comment by vshcherb** [comment]
From https://github.com/osmandapp/OsmAnd/issues/15713#issuecomment-1324782179

**Comment by vshcherb** [comment]
I think it's already present in Download / Update tiles dialog - you can update tiles with check box for a selected region

**Comment by mikehgentry** [comment]
#15187 suggests another way of doing this (specify an 'update after' and 'delete after' time)

**Comment by vshcherb** [comment]
Yes update after will be provide more fine control rather than simple check box redownload existing tiles or not.
