### ISSUE TITLE
Location services not working

### ISSUE THREAD

**Issue by mgw2013** [osmandapp/OsmAnd#15808]
### Description
OsmAnd not detecting location despite all rights granted and location services switched on. Location service works for other apps e. g.  browser and HERE WeGo app Ver. 4.5.000  on same device.

### How to reproduce?
Launch OsmAnd and wait for forever for location to be detected.

### Your Environment
OsmAnd Version:  ~4.2.7~ 4.3.12 installed from F-Droid
Android/iOS version: zLineageOS ~19.1 (Android 12)~ 20 (Android 13)
Device model: mido
**Remark**: **No Google services on device due to no GAPPS installed!**

**Maps used (online or offline):**   
Both

Add'l remark: This is "on and off" some previous versions worked, however the latest version never.

**Comment by sonora** [comment]
Try `Menu / Settings / General settings / Location source`, and set it to "Android API". Does that fix it?

**Comment by scaidermern** [comment]
> Try `Menu / Settings / General settings / Location source`, and set it to "Android API". Does that fix it?

I think this is the only option for f-droid builds and thus already configured / not modifyable.

**Comment by sonora** [comment]
That right? Is this another case of "_the menu is hidden so nobody knows what the setting is set to?_"

**Comment by mgw2013** [comment]
I'm afraid there are no 'general settings' under settings... I do have 'OsmAnd settings' but these have no menu item 'Android API'...


-------- Ursprüngliche Nachricht --------
Von: Hardy ***@***.***>
Gesendet: 23. November 2022 17:08:19 MEZ
An: osmandapp/OsmAnd ***@***.***>
CC: mgw2013 ***@***.***>, Author ***@***.***>
Betreff: Re: [osmandapp/OsmAnd] Location services not working (Issue #15808)

Try `Menu / Settings / General settings / Location source`, and set it to "Android API". Does that fix it?

-- 
Reply to this email directly or view it on GitHub:
https://github.com/osmandapp/OsmAnd/issues/15808#issuecomment-1325314762
You are receiving this because you authored the thread.

Message ID: ***@***.***>

Mit freundlichen Grüßen
Michael Weigelt

**Comment by mgw2013** [comment]
No Android API menu entry available as I just wrote...


-------- Ursprüngliche Nachricht --------
Von: Alexander Heinlein ***@***.***>
Gesendet: 23. November 2022 18:39:47 MEZ
An: osmandapp/OsmAnd ***@***.***>
CC: mgw2013 ***@***.***>, Author ***@***.***>
Betreff: Re: [osmandapp/OsmAnd] Location services not working (Issue #15808)

> Try `Menu / Settings / General settings / Location source`, and set it to "Android API". Does that fix it?

I think this is the only option for f-droid builds and thus already configured / not modifyable. 

-- 
Reply to this email directly or view it on GitHub:
https://github.com/osmandapp/OsmAnd/issues/15808#issuecomment-1325438937
You are receiving this because you authored the thread.

Message ID: ***@***.***>

Mit freundlichen Grüßen
Michael Weigelt

**Comment by mgw2013** [comment]
Might be the case... do I need to install the Android full build or something else?


-------- Ursprüngliche Nachricht --------
Von: Hardy ***@***.***>
Gesendet: 23. November 2022 20:30:03 MEZ
An: osmandapp/OsmAnd ***@***.***>
CC: mgw2013 ***@***.***>, Author ***@***.***>
Betreff: Re: [osmandapp/OsmAnd] Location services not working (Issue #15808)

That right? Is this another case of "_the menu is hidden so nobody knows what the setting is set to?_"

-- 
Reply to this email directly or view it on GitHub:
https://github.com/osmandapp/OsmAnd/issues/15808#issuecomment-1325564005
You are receiving this because you authored the thread.

Message ID: ***@***.***>

Mit freundlichen Grüßen
Michael Weigelt

**Comment by scaidermern** [comment]
Maybe take one step back and check whether your GPS is working at all. You can do this with apps like GPSTest or SatStat.

> Location service works for other apps e. g. browser and HERE WeGo app Ver. 4.5.000 on same device.

I'm not familiar with HERE WeGo, however, keep in mind that there are multiple sources for obtaining a location. These apps may use network services instead of GPS as the location source. OsmAnd doesn't do this but requires a working GPS. So please check if GPS is working at all.

**Comment by mgw2013** [comment]
> Maybe take one step back and check whether your GPS is working at all. You can do this with apps like GPSTest or SatStat.
> 
> > Location service works for other apps e. g. browser and HERE WeGo app Ver. 4.5.000 on same device.
> 
> I'm not familiar with HERE WeGo, however, keep in mind that there are multiple sources for obtaining a location. These apps may use network services instead of GPS as the location source. OsmAnd doesn't do this but requires a working GPS. So please check if GPS is working at all.

As I wrote in the orginal post GPS is definitely working and several other apps do make use of location services! Also, I do not have any Google Apps installed and use of other network services does not happen (and was impossible during the latest test due to being in the thick of a forest).

**Comment by sonora** [comment]
Regarding
> I'm afraid there are no 'general settings' under settings... I do have 'OsmAnd settings' but these have no menu item 'Android API'...

Apologies, I misspoke: I have corrected my wording on the post above https://github.com/osmandapp/OsmAnd/issues/15808#issuecomment-1325314762.

**Comment by mgw2013** [comment]
> Apologies, I misspoke: I have corrected my wording on the post above [#15808 (comment)](https://github.com/osmandapp/OsmAnd/issues/15808#issuecomment-1325314762). And yes, chances are the f-droid build uses the Android API automatically.
>
Might be but can't check due to missing menu item, sorry... 
> * When you go to `Configure screen / Right panel` and display the `GPX info` widget on the map, what does it display? 0/0, or 0/x, or something else?
>
Right now it tells me 0/22 but when I last tried to use OA in the woods I had 7/22 from both GPSTest and SatStat (didn't have GPS in right panel at that time).
> * PS: You mention this, but please verify again under` Android(not OsmAnd) Settings / Apps / Permissions` that OsmAnd **was granted the Location access permission.** I think I have seen situations and OsmAnd builds in the past where that had to be granted manually and was not requested by the app at installation time.
>
Verified - permissions granted are network, sensors and location!

**Comment by mgw2013** [comment]
> Wait a minute will go outside and test for 5'

OK. Here is what I did: went outside; rebooted phone with location and compass switched on - reboot - launched OsmAnd, SatStat and GPSTest - the alter shows 3/23, SatStat has three red dots. OsmAnd tells me postion not yet known with A-GPS data freshly loaded after reboot. Here.com app  immediately found my location.

**Comment by sonora** [comment]
Things like 3/23 actually sounds to me like you have a general GPS issue on that device, and the reason why other apps show your location immediately is they use cell tower  / WiFi / BT based 'approximate'  for the interim .... 

GPS Status could be a good app to display exactly how many satellites are seen and how many are in use. I suspect there may be an issue not directly related to OsmAnd.

**Comment by mgw2013** [comment]
> Things like 3/23 actually sounds to me like you have a general GPS issue on that device, and the reason why other apps show your location immediately is they use cell tower / WiFi / BT based 'approximate' for the interim ....
> 
> GPS Status could be a good app to display exactly how many satellites are seen and how many are in use. I suspect there may be an issue not directly related to OsmAnd.
Well this was after 3 minutes from rebooting the device - if needed I could supply data with >24 h ... regularly this is 7..9/23. I'm well aware that apps might use other data, but this is not permitted in this case, neither WiFi, nor BT (both switched off) as well as mobile data.  Let me know if you need me to produce a specific logfile.

**Comment by sonora** [comment]
In my experience, also 9/23 looks somehow problematic... after rather few seconds of seeing that it should go to something like 20/23. There may  be a few satellites too close to the horizon to be stable, but I would not currently know of any valid reason why your GPS chipset sees 23 satellites and continues to use uses only 9 of them.

Could be a hardware or firmware issue, almost sounds like your device sees satellites from different providers (GPS, Galileo, GLONASS), but only uses one of them...

Do you have a second device to try?

**Comment by mgw2013** [comment]
> In my experience, also 9/23 looks somehow problematic... after rather few seconds of seeing that it should go to something like 20/23. There may be a few satellites too close to the horizon to be stable, but I would not currently know of any valid reason why your GPS chipset sees 23 satellites and continues to use uses only 9 of them.
> 
> Could be a hardware or firmware issue, almost sounds like your device sees satellites from different providers (GPS, Galileo, GLONASS), but only uses one of them...
> 
> Do you have a second device to try?

Hmm. Let me perform some checks. However, firmware is unlikely due to being unchanged since some time. All sensors are good according to Device Info HW app.

**Comment by sonora** [comment]
I have researched this a bit and it seems there are in deed devices which are locked to using just one satellite provider...

In an case, in order to judge if this could potentially be an OsmAnd issue or not, it would be interesting to know if you have any GPS app on your device which confirms using say 20/23 satellites for a position lock while OsmAnd only reports e.g. 9/23. I can currently think of no reason why the OsmAnd GPS widget should show a different number of satellites used for a fix than any other GPS status app you may have in parallel.

**Comment by mgw2013** [comment]
@sonora  can't confirm only single provider. Device shows US, Russia and Chinese satellites.

Back to the issue - any phone based GPS typically needs about 5 mins from a **cold** start. This is not what I'm referring to. The issue is rather with location services being switched on (for a while... usually TTFF is less than 20 sec) and launching the app always reports location not yet known **unless f. i. GPS Test or a similar app is also launched**
