### ISSUE TITLE
Function "Show closed OSM notes" does not work.

### ISSUE THREAD

**Issue by franco999** [osmandapp/OsmAnd#15816]
### Description
When activating the "**OSM notes (online)**" function with the "**Show closed notes**" option deactivated so that it does not show the already resolved notes (in green), it does not seem to work. _See image._

(I apologize for the large image, I don't know how to make it smaller.)
![osm notes osmand](https://user-images.githubusercontent.com/12088580/203786392-e35c8b4e-8b89-455a-a677-d42ad3c9f951.jpg)

### How to reproduce?
Go to "_Configure map_" > "_OSM notes (online)_" > "_Show closed notes_" deactivated.

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13968mqta 
Android/iOS version: Android ROM ArrowOS 12.1
Device model: Xiaomi Mi A2 Lite

**Maps used (online or offline):**   
Map: Argentina-Santa_Fe, World_basemap_mini

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.3.0#13979mqta, released: 2022-11-28
Reproduced

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.3.0#13998mqta, released: 2022-12-05
`48.13319° N, 11.56693° E`


https://user-images.githubusercontent.com/104760013/205625941-d8ffd661-3915-4ad0-8b32-f10c6048ffdb.mp4
