### ISSUE TITLE
Problem after the update to Android 13 / UI 5.0

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#15812]
### Description

After this update I can´t use Osmand+ anymore. It runs from one freeze into the next. Sometimes immediately at the start (just an empty screen), sometimes it happens to start, but freezes when switching in the menue or moving the map. 
It ALWAYS it freezes very soon, after a few very slow seconds. No chance tu use it.

I run Osmand+ 4.3.0 also on two other devices with Android 12 / UI 4.1 and both run fine.

### Your Environment
OsmAnd Version: 4.3.0
Android/iOS version: 13
Device model: S20+ 5G

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/95540936/203708610-9452c055-724e-45d2-ab9c-30c5c9fa08a9.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/95540936/203708647-7a995093-a7ce-46bf-a3f6-041130d5a674.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Rowin63** [comment]
Unfortunately recently I had to change my damaged phone (S20+ to S20+ 5G) and at the same time Android was updated to 13. Since then I had this Problem, Osmand always crashes. So I don´t know, if the phone change or the Android update caused the problem.

Since then I did several new installs, always the same way, always with the same result,ending up in a freezing Osmand:
-) Installing Osmand+ from the play store
-) getting back my data from a local backup (settings/places/sources)
-) restoring all the map data back from a copy folder
I never did it step by step, but always in a row until the end. After this, Osmand always crashed.

Now again I did every step like above, but without the last one, not using the copied maps. Downloaded all the map data again and now Osmand works smooth like always before. Crazy.

**Comment by Zirochkabila** [comment]
Maybe it's a specific build. Try downloading this nightly version and check again [OsmAnd nightly](https://download.osmand.net/latest-night-build/OsmAnd-opengl-arm64-nightly.apk )
If the behavior repeats, please send us a log file if possible: Menu > Help > Send logcat log


If OsmAnd works - can we consider the issue closed?
+ please send us your backup file, which will contain the maps (which, in your opinion, cause the hangs). We will check the file - maybe it is really the maps.

**Comment by Rowin63** [comment]
Yes, we can close this issue. I just wanted towait some days, but Osmand still runs fine without any problems.
Thanks for the great job you all do!
