### ISSUE TITLE
The route calculated does not seem correct

### ISSUE THREAD

**Issue by NikolaTesla369369** [osmandapp/OsmAnd#15813]
Hi, can me someone help? I recently found your great and detailed app- OsmAnd. Now I am using Offline version 4.2.7 on Android 13. I would like use it as my main navigation with purchase but i found these wrong routing calculations. I know this road, driven there for years ... but OsmAnd calculated this road over 5 km longer from 33 km total distance with + 6 minutes. Its too mutch. On road isnt any traffic issue... Btw, sorry for my English for better understanding i post photo u can see this problem. I tried so many settings in navigation but no way to get it work right. There is used 100% same adress / location. Now I tried Online version with diferent providers but no changes... fastes way is calculated wrong.
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/118959776/203713593-e084086e-3f06-4c4d-ae47-e82f7ef083c2.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/118959776/203713637-09d5a731-0786-4702-892b-fddc788a7765.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
The thing is that when building a route, OsmAnd takes into account such factors as the road surface, ascents, and descents - based on this data, the route is formed.
As you can see on the attached screenshots, there is such an indicator as Cost (a kind of fare, taking into account the above parameters) and on the route proposed by OsmAnd, this indicator is lower, although the route is longer.

[OsmAnd 2698](https://osmand.net/map/?start=48.087146%2C18.259985&end=48.326981%2C18.100072&mode=car#11/48.2114/18.2366)

<img width="1388" alt="Screenshot 2022-11-25 at 17 00 42" src="https://user-images.githubusercontent.com/104760013/204013287-d3cb65d2-5819-4c92-8c72-6ed3c06ac21f.png">

[OsmAnd 2764](https://osmand.net/map/?start=48.101743%2C18.236918&end=48.326981%2C18.100072&mode=car#11/48.2224/18.2957)

<img width="1388" alt="Screenshot 2022-11-25 at 16 59 43" src="https://user-images.githubusercontent.com/104760013/204013546-fdebba21-c7cb-4ee4-896f-31aae1f57f4f.png">

**Comment by NikolaTesla369369** [comment]
Thank you for your quick response. Its really interesting fact that so
longer route could be better. Because google maps say that other route is
about 17% fuel cost efficient. It could be verified...

Dňa pi 25. 11. 2022, 16:12 Anatolii ***@***.***> napísal(a):

**Comment by NikolaTesla369369** [comment]
Explained
