### ISSUE TITLE
Islands on wrong map set

### ISSUE THREAD

**Issue by Gizmot** [osmandapp/Osmand#1581]
The islands set at approximatly 47°26'36.5"N 61°45'21.5"W (Îles de la Madeleine) are incorrectly assigned to ''Canada Prince Edward Island'' while this should be assigned to ''Canada Québec''

**Comment by Gizmot** [comment]
details:
https://en.wikipedia.org/wiki/Magdalen_Islands

**Comment by xmd5a2** [comment]
Polygons fixed

**Comment by vshcherb** [comment]
Will be regenerated next month

**Comment by Gizmot** [comment]
Using Canada Quebec 06-09-2015 problem is still present

**Comment by xmd5a2** [comment]
Can't confirm. All borders in obfs are accroding to polys
![_2015-09-09_09-49-52](https://cloud.githubusercontent.com/assets/5829014/9755145/2d208904-56d8-11e5-837a-dbf8d65b9f68.png)

**Comment by Gizmot** [comment]
Still not working

![screenshot_2015-10-10-18-09-47](https://cloud.githubusercontent.com/assets/13919997/10413829/f4f2fc5c-6f86-11e5-83a0-46fbdac29011.png)

![screenshot_2015-10-10-18-09-59](https://cloud.githubusercontent.com/assets/13919997/10413830/f7a212f8-6f86-11e5-8812-31b952407908.png)

**Comment by xmd5a2** [comment]
If you look closely at these island you'll notice that they are included in Canada_quebec_northamerica.obf map. Green fill updates with new OsmAnd version.
