### ISSUE TITLE
Possible bug on crossings with "traffic_calming=no" included.

### ISSUE THREAD

**Issue by franco999** [osmandapp/OsmAnd#15820]
### Description
When following a route with the offline navigation engine and crossing pedestrian crossings with the "**traffic_calming=no**" tag included, the TTS voice announces it as if it were a speed reduction, but it is not. If you have several nodes with the same labelling, it is annoying that it announces every 5 seconds something it is not.

Once you have crossed the section where this node with "traffic_calming=no" was located, then navigation returns to normal.

### How to reproduce?
ROUTE: https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=-32.92814%2C-60.81201%3B-32.93053%2C-60.82012#map=17/-32.92934/-60.81615

FROM: https://osm.org/go/MyGkR4VMh-?m=
TO: https://osm.org/go/MyGkRBQrw-?m=

OVERPASS: https://overpass-turbo.eu/s/1obA
Example node: https://www.openstreetmap.org/node/9993666194

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13968mqta
Android/iOS version: Android ROM ArrowOS 12.1
Device model: Xiaomi Mi A2 Lite

**Maps used (online or offline):**   
Map: Argentina-Santa_Fe, World_basemap_mini

**Comment by franco999** [comment]
duplicate #15296 ?

**Comment by vshcherb** [comment]
Merged to #15296
