### ISSUE TITLE
Map orientation inconsistencies when switching profiles

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#15836]
I guess the following behaviors are bugs?

(1) Have your 'Browse map'  map view profile set to _'Fixed (north is up)'_, and your Pedestrian profile to _'Compass orientation'_. Now from Browese map, use the map screen's top left profile selector to switch to Pedestrian, the map orientation will adjust correctly. But now go back to Browse map, and it seems the map there will now be manually rotated  to the last bearing of the conpass orientation?

(2) A similar but different inconsistency can be observed if a profile change is triggered via the route config dialog. There we currently change the map view profile as soon as that dialog is entered (#15833), but it seems we apply the new profile's (e.g. Pedestrian's) **map orientation** only when and after the user leaves that dialog by tapping the turn-by-turn Start button. I.e. **not** when they enter the dialog, **and not** when they leave the dialog (after the route is calculated) via the back button to just view the route?

EDIT: It looks like both (1) and (2) are reproducible only under unknown pre-conditions, sometimes I see only (1) or (2), sometimes both.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.3.0#13979mqta, released: 2022-11-28
As for the first point - it reproduced. The position of the map is not remembered and automatically returns to what was set in the  'Browse map' profile.


https://user-images.githubusercontent.com/104760013/204331914-e1c5e701-1e2c-4899-b2ab-60f8fa0816b1.mp4



Regarding the second point - @dmpr0 described the explanation in the comment https://github.com/osmandapp/OsmAnd/issues/15833#issuecomment-1327485056
I think this is the case

**Comment by vshcherb** [comment]
(2) sounds correct, otherwise it would be inconsistent with visible profile. What profile is currently visible means that profile settings should be applied

**Comment by sonora** [comment]
Yes, (2) seems fixed, cannot reproduce anymore.

**Comment by Rowin63** [comment]
After finishing a route in the driving profile (orientation "direction"), osmand still switches back to the "show map"-profile (always north). The orientation does switch back to "always north" (see the symbol), but the map itself is not aligned correctly, until tap.

![Map Orientation](https://user-images.githubusercontent.com/95540936/205510770-6d5af3aa-6a89-41fc-8e63-18d406f55b05.JPG)

**Comment by sonora** [comment]
That sounds like (1), only that the profile switch back in your case is invoked by the route finishing ,not manually.

Funny thing is, while earlier I could still reproduce (1) but not (2) anymore, today it is exactly the other way round again for me. So it seems the reproducibility of both (1) and (2) depends on something we still have to establish.

**Comment by vshcherb** [comment]
Rotation angle should be saved per profile (I think) - preferrable
Alternative: it should be switch to North if Map orientation switches from Non-manual rotation to Manual Rotation

**Comment by Rowin63** [comment]
As I can see, this compass setting (shown in my last post) is the "manual" setting. But the "see map"-profile has the compass setting "always north", not "manual". This is why I have to tap the compass once again, after switching back to the "see map"-profile from the "drive"-profile after ending a route. 
This does not happen, when just switching around through different profiles and back to "show map". Then the "show map" is always north. Only after ending a route.

**Comment by vshcherb** [comment]
Issue hard to reproduce only once, we need to test more...

**Comment by sonora** [comment]
It's really weird. You can try this: Have _Browse map_ as your default profile, and set it to _Fixed - North is up_, and _Pedestrian_ to _Compass direction_.

- Start the app, it will show _Browse map_ in correct "North is up" orientation.
- **Now, manually change to the Pedestrian view and back to Browse map. Repeat many times.** Always rotate the device in Pedestrian view a bit, so that you would detect a change when coming back to the Browse map view.

In some cases (maybe 1 out of five tries) _Browse map_ now takes over **the new, actual, degree of rotation** from the Pedestrian compass rotation, i.e behaves as if it had been manually rotated to that map orientation. In the other cases, Browse map will still remember the 'previous' degree of rotation (which may still be the correct initial _North is up_, or the last meanwhile 'inherited' one from the Pedestrian orientation.

It should be concurrency/timing issue, as it reproduces in some cases and in others not, without interim changing the setup or any settings at all.

**Comment by scaidermern** [comment]
I've also noticed several times that there is some inconsistency and north up will sometimes get overwritten. Not sure how to reproduce, unfortunately. Still rather annoying.

**Comment by sonora** [comment]
It essentially resulted from us using setting value `ROTATE_MAP_NONE` for both _Map orientation: Fixed (north is up)_ and _Map orientation: Fixed (manually rotated)_.

Here's the fix: https://github.com/osmandapp/OsmAnd/pull/15943

**Comment by sonora** [comment]
It's tested. Am I supposed to merge it, or someone else?

**Comment by vshcherb** [comment]
Of course peer review is needed here it's less critical and won't be merged to 4.3. 
Also I'm not sure whether it introduces new setting or not:
```
rotateMap.setEntries(new String[] {getString(R.string.rotate_map_none_opt), getString(R.string.rotate_map_bearing_opt), getString(R.string.rotate_map_compass_opt), getString(R.string.rotate_map_none_rotated_opt)});
		rotateMap.setEntryValues(new Integer[] {OsmandSettings.ROTATE_MAP_NONE, OsmandSettings.ROTATE_MAP_BEARING, OsmandSettings.ROTATE_MAP_COMPASS, OsmandSettings.ROTATE_MAP_MANUAL});		rotateMap.setIcon(getRotateMapIcon());
		
```

In that case it will need UI review first.

**Comment by sonora** [comment]
Sure. There's no new setting, just a new entry for an existing setting. And yes, there's one dialog where that extra line will show.

**Comment by sonora** [comment]
Test plan:

 - [x] 1. Verify that tapping the compass icon still pages through modes _Fixed (North is up) -> Movement direction  -> Compass direction  -> Fixed (manually rotated) -> Fixed (North us up)_, in that order.

 - [x] 2. Verify that tapping the compass icon after any manual rotation always reinstates _North is up_.

 - [x] 3. Verify rhe correct function of dialog _Configure profile > General settings > Map orientation_.

 - [x] 4. Verify that previous behavior is unchanged rhat twist-rotate in map state _North is up_ correctly changes to state _Manually rotated_. Twist rotation in state _Compass direction_ is still ignored.

 - [x] 5. Repeatetly  change between a profile using _North is up _and one using _Compass direction_, and check this is consistently reflected correctly (i.e. this very issue us fixed)..

**Comment by sonora** [comment]
PS: Here"s the oneUI dialog which is slighly expanded by my PR:

![Screenshot_20230114-085301_OsmAnd~](https://user-images.githubusercontent.com/845735/212462362-d67e9af3-6680-481d-843e-4ef1156c51cc.jpg)

I have been testing the fix for a month now, it reliably solves the issue.

**Comment by dmpr0** [comment]
<table style="width:100%">
  <tr>
    <th>Map orientation</th>
    <th>Long tap on compass</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/212942005-327658dd-72d3-4299-be9f-f20336ae71b2.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/212942009-ade485b3-4508-46f1-82df-f835718e0690.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by sonora** [comment]
@vshcherb Any chance we merge https://github.com/osmandapp/OsmAnd/pull/16040 any time soon? It's really well tested by now.

**Comment by vshcherb** [comment]
@sonora did you see test plan from @dmpr0. Please mark the checkboxes

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14214mqta, Released: 2023-03-03
Done

**Comment by DmitryAlexei** [comment]
https://docs.osmand.net/docs/user/map/interact-with-map#map-orientation-modes
