### ISSUE TITLE
Bicycle routing: (conditional) access restriction ignored

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#15844]
[Way 28425009](https://www.openstreetmap.org/way/28425009) has `vehicle:conditional=no @ (2022 Nov 17-2022 Dec 31)` set. So the road is currently closed for all vehicles.

When routing from 51.0507562,13.7286615 to 51.0489284,13.745656 OsmAnd correctly recognizes this tag for car routing but _not_ for bicycle routing.

Left: car, right: bicycle
![photo_2022-11-28_12-41-20](https://user-images.githubusercontent.com/1040784/204270113-ce4916bd-c194-4381-bd48-4ab43c13064d.jpg)

There are two possible causes:
* Either `vehicle:conditional` is not used for bicycle routing at all. (`vehicle` is correctly used for bicycle routing if I checked this correctly)
* Or `vehicle:conditional` is correctly used for bicycle routing but `cycleway:right=lane` is overwriting this tag (which it should not, since this is a physical property but not a legal one in my opinion).

OsmAnd 4.3.0

**Comment by vshcherb** [comment]
I think it overrides cause "bicycle-yes" is higher than "vehicle-no". You can add tag like "bicycle:conditional=no..." the same probablyt it won't be too bad

**Comment by vshcherb** [comment]
We can't move vehicle higher cause there are situations where bicycle is present as well but here bicycle-yes is implicit.

**Comment by vshcherb** [comment]
This map needs to be regenerated and checked what's the issue.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.3.0#13984mqta, released: 2022-11-29
Reproduced
[Map here](https://drive.google.com/drive/folders/1n0fImR0yRp46jrHlSqX5M0E0MGNCnm5A?usp=sharing)

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/204546779-fec7d822-1f1a-4748-96b2-d76501cbf0ac.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
From binary inspector
```
Road 1819200637 osmid 28425009 highway='tertiary' lanes='1' lit='yes' maxspeed='20' oneway='yes' smoothness='good' surface='asphalt' vehicle:conditional='no @ (2022 Nov 17-2022 Dec 31)' width='3.25' route_bicycle='' network='lcn' route_bicycle_1='' route_bicycle_1_network='lcn' route_bicycle_2='' route_bicycle_2_operator='Erlebnisregion Dresden' route_bicycle_2_network='lcn' osmand_highway_integrity_brouting='-1' cycleway='lane' sidewalk='no' name="Wilsdruffer Straße" road_name_1="GDD05" route_bicycle_1_name="Radroute Ost-West" route_bicycle_1_ref="O-W" route_bicycle_2_name="Erlebnisregion Dresden Route 6" route_bicycle_2_ref="DD-R6" route_bicycle_2_symbol="Weißer Radfahrer auf dunkelblauem Grund" route_road_1_name="GDD05" pointtypes [[5. highway='traffic_signals' ][6. crossing='traffic_signals' highway='crossing' kerb='lowered' tactile_paving='yes' ][7. bicycle='designated' crossing='unmarked' highway='crossing' kerb='no' segregated='no' tactile_paving='primitive' ][8. crossing='uncontrolled' highway='crossing' tactile_paving='yes' ][10. crossing='traffic_signals' highway='crossing' kerb='lowered' tactile_paving='no' ]]
```

**Comment by vshcherb** [comment]
Author stated that OSM contains multiple of errors regarding 'vehicle=no' for bicycles though he didn't react to that bug, unless we get more feedback with other issues. I would say we need to keep situation as it is right now or do a deep analysis how many OSM errors vs OsmAnd errors we have

**Comment by scaidermern** [comment]
In my opinion the only goal should be to interpret the tags correctly. Otherwise people are forced to add wrong / unneeded tags - like in this case. This can't be our goal.

**Comment by vshcherb** [comment]
Sure though I need 2 things to confirm:
A) Feedback from different people and other issues
B) Deep analysis

Otherwise it's a illusionary goal that we have something and for 5 years nobody complained

**Comment by Posteinwurf** [comment]
Thank you for setting me cc and sorry for my late reply!

The highway=cycleway and route_bicycle override the "vehicle=no" on purpose. It first might seem a contradictory, but it is based on many checks that I did on the ground (I have tested Osmand bicycle routing over thousands of kilometres in Poland, France, Lithuania and Germany). Here is what I found:

There are many cases, where vehicle=no (without any exception mentioned) is indicated on routes that are DESIGNATED for bicycles. In theory, there should be a road sign indicating that bicycles are an exempted from the vehicle=no. And this road sign should then also, theoretically, be found in the OSM data. But in reality, often the exception for bicycles isn't indicated on the ground. In other cases, it is indicated on the ground, but not found in the OSM data. I have made some photos of cycle routes and cycleways where there is a plain "no vehicle access" sign (without exception stated). 

So highway=cycleway and route_bicycle needs to override "vehicle=no", otherwise Osmand would exclude many ways that are intended for bicycles. 

The case above (in Dresden) is special: It is just a temporary closure until end of december. The authorities in Dresden have set up barriers to protect the "Striezelmarkt" (Christmas Market). Therefore, this "vehicle:conditional=no" is set in the OSM data. I haven't checked on the ground (I am in Berlin), but from similar road barriers I would suggest that they block cars and lorries, but not pedestrians and bikes. So you can still descend and push your bike there.

**Comment by scaidermern** [comment]
> There are many cases, where vehicle=no (without any exception mentioned) is indicated on routes that are DESIGNATED for bicycles. In theory, there should be a road sign indicating that bicycles are exempted from the vehicle=no. And this road sign should then also, theoretically, be found in the OSM data. But in reality, often the exception for bicycles isn't indicated on the ground.

I agree that this happens way to often in reality. Nevertheless it is really bad to end up in front of a sign that prohibits cycling whereas the router tells you otherwise. Sometimes these signs are wrong, sometimes they aren't. When standing in front of them you can't tell for sure. So it is better to avoid these ways. It *might* be a different case if this way is also part of a cycle route. But even then the sign might be a temporary one to prohibit cycling for a limited amount of time. 

 
> So highway=cycleway and route_bicycle needs to override "vehicle=no", otherwise Osmand would exclude many ways that are intended for bicycles.

I understand your reasoning but I'm not sure if including ways that are prohibited for cycling is the better alternative. Either way, tags need to get fixed and the signs on the ground need to get fixed to improve the situation. 

> The case above (in Dresden) is special: It is just a temporary closure until end of december. The authorities in Dresden have set up barriers to protect the "Striezelmarkt" (Christmas Market). Therefore, this "vehicle:conditional=no" is set in the OSM data. I haven't checked on the ground (I am in Berlin), but from similar road barriers I would suggest that they block cars and lorries, but not pedestrians and bikes. So you can still descend and push your bike there.

I have checked this case on the ground and the sad reality is that the police is *waiting* for cyclists just to give them a fine.

And yes, of course you can dismount and push your bicycle. This is almost always the case for vehicle=no and bicycle=no.

**Comment by scaidermern** [comment]
Here we go again: https://www.openstreetmap.org/way/1226680710
`vehicle:conditional=*` is respected in car routing but not in bicycle routing, resulting in wrong routing in bicycle mode.

**Comment by vshcherb** [comment]
Need to open new issue this one fixed in previous release

**Comment by scaidermern** [comment]
> Confusing thing that it has nothing to do with conditional cause it's a generic problem, am I right?

That could be correct, I haven't checked. 

> `vehicle:no` prohibits driving for bicycle but according to OSM documentation it shouldn't

I think OsmAnd handles this tag correctly for bicycle mode. According to your previous explanation this bug here is caused by the bicycle route this way belongs to.
