### ISSUE TITLE
Kommune "Hatten" not found

### ISSUE THREAD

**Issue by Spielmops** [osmandapp/OsmAnd#15847]
With Osmand 4.2.7
We have a commune namend "Hatten" nearby: https://www.openstreetmap.org/export#map=12/53.0498/8.3223
Every address ist given as "Schulstraße 8, Hatten". But there is no location named "Hatten" and Osmand does not find "Hatten". If I search for that location with a browser, it is found.

Why not with Osmand?

Spielmops

**Comment by vshcherb** [comment]
OsmAnd only supports city/town/neighboorhood places https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=1185613&class=boundary and it doesn't support custom region names
