### ISSUE TITLE
Additional POI translations bug

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1584]
For example we have additional POI
```xml
	<poi_additional name="vk" tag="vk" type="text"/>
```
And it's translation in phrases.xml (english)
```xml
	<string name="poi_vk">VKontakte</string>
```
And there is no russian translation. When using russian UI language this POI appears as "Vk", but "VKontakte" expected. After switching to english UI this text is displayed correctly - "VKontakte"

**Comment by vshcherb** [comment]
It would be good to have a link or steps how to reproduce it.

**Comment by xmd5a2** [comment]
Can't reproduce anymore. Seems that it is fixed.
