### ISSUE TITLE
OsmAnd does not run after updating

### ISSUE THREAD

**Issue by Ahmadhosseinbor** [osmandapp/OsmAnd#15841]
### Description
After updating to version 4.3.0, the OsmAnd app does not run

### How to reproduce?
-Update to v4.3.0
-Open OsmAnd

### Your Environment
OsmAnd Version: 4.3.0
Android/iOS version: 12
Device model: Galaxy A32

**Maps used (online or offline):**   
offline

https://user-images.githubusercontent.com/44550501/204218757-c74ae39c-ebf7-4275-814d-671a8c4fd9e0.mp4

**Comment by Zirochkabila** [comment]
@Ahmadhosseinbor the same?[Problem after the update to Android 13 / UI 5.0](https://github.com/osmandapp/OsmAnd/issues/15812)

**Comment by Ahmadhosseinbor** [comment]
> @Ahmadhosseinbor the same?[Problem after the update to Android 13 / UI 5.0](https://github.com/osmandapp/OsmAnd/issues/15812)

I don't think they are the same, for me OsmAnd 4.3.0 doesn't run and crashes at the start

**Comment by vshcherb** [comment]
4.3.1 is almost ready, going to update let's see if it's going to fix it.
