### ISSUE TITLE
[Bug] Wrong z-order of map layers: GPX tracks buried

### ISSUE THREAD

**Issue by Dollarius** [osmandapp/OsmAnd#15849]
Up to nightly **2022-11-20**,
imported GPX tracks were drawn on top of all the map layers.
I believe this is the intended behaviour, as an imported gpx track is the most important information to be shown by the app (i.e., the route one wants to follow).
![image](https://user-images.githubusercontent.com/56419637/204464047-ab8a8921-40a1-4d35-9d11-64927a73a55d.png)

From nightly **2022-11-21**,
GPX tracks are drawn underneath both the overlay map and the hillshade layer, thus making the use of gpx tracks impossible.
![image](https://user-images.githubusercontent.com/56419637/204464411-4dcb4d57-2513-425e-ab11-c6811e2c71b3.png)

It would be nice if you could fix this bug and keep the gpx track as top-most layer.
Thank you very much!

**Comment by vshcherb** [comment]
I think you switched from OpenGL rendering to Legacy - please check in OsmAnd Settings

**Comment by Dollarius** [comment]
@vshcherb thank you for your help!
How do I switch OpenGL/Legacy in the latest version?
Few versions ago, there was a switch under Plugins/OsmAnd development (first option), but now it disappeared.
I am assuming OpenGL is now default and cannot be switched anymore?

To be sure that I am now using OpenGL, I installed an old version and checked that the switch is ON: Plugins/OsmAnd development/UseOpenGL rendering
This bug appears only from version 2022-11-21, after OpenGL was made default.
I believe it might be related to the change in zorders that was made in this commit:
https://github.com/osmandapp/OsmAnd/pull/15780#issuecomment-1331698219

Can you please help solve this bug?

**Comment by scaidermern** [comment]
> How do I switch OpenGL/Legacy in the latest version?

This switch is now located here: Settings / OsmAnd settings / Map rendering engine.

**Comment by Dollarius** [comment]
@scaidermern thank you very much for pointing me to the new location of the switch.
It's indeed set on version 1 (NO opengl) and I cannot change it (running android-full nightly 2022-12-01 on Android 12, Galaxy S20FE).
Any ideas why?
![Screenshot_20221201-203507_OsmAnd~](https://user-images.githubusercontent.com/56419637/205043161-3963ab56-44ce-4d77-9585-31f7b75faea7.jpg)

**Comment by Dollarius** [comment]
I managed to enable OpenGL by installing the nightly master-opengl (the switch does not work in the nightly android-full).
The z-order of the GPX track is indeed correct in V2 OpenGL, as @vshcherb pointed out.

**Was the z-order in V1 (NON OpenGL) broken on purpose from 2022-11-21?**
If I understand correctly, V1 (which is stable) will still be the preferred choice for older devices.
Also, I see several bugs on V2 OpenGL (unstable?): I will report them in a separate thread.

**Comment by vshcherb** [comment]
probably by mistake as it was sync https://docs.osmand.net/docs/technical/algorithms/map-rendering-layers#order-of-layers with docs

**Comment by vshcherb** [comment]
@ivanPyrohivskyi is it a mistake in v1?
