### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by d4f5409d** [osmandapp/OsmAnd#15868]
### Description
Random crash

### How to reproduce?
Browse the maps

### Your Environment
Device : OnePlus8
Brand : OnePlus
Model : IN2015
Product : OnePlus8
Version : 13
App Version : OsmAnd~
Apk Version : 4.2.7

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
Offline

Logs: (|||password is vscherb|||)
https://send.vis.ee/download/2a20f0d92d004f0c/#G-8qwYjBDLN7-tfoVh7rVw

**Comment by vshcherb** [comment]
You can create zip file and attach here, please test 4.3.1 it's already in beta

**Comment by d4f5409d** [comment]
> You can create zip file and attach here, please test 4.3.1 it's already in beta

Where can I find the beta release?

**Comment by vshcherb** [comment]
https://osmand.net/docs/versions/future-android/
