### ISSUE TITLE
"Opens at" is incorrect

### ISSUE THREAD

**Issue by nereocystis** [osmandapp/OsmAnd#15865]
### Description
"Opens at" is incorrect for San Francisco Museum of Modern Art

### How to reproduce?
Download California standard map
Search for "San Francisco Museum of Modern Art" on Tuesday, 2:50PM Pacific Time, US/Los Angeles 
Even though museum is currently open Tuesday, 10:00AM-5:00PM, osmand says that museum is open Thursday at 10:00AM.
See screenshot
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/2257107/204665831-d42a94f2-d2f6-4ae9-bfb7-46e9f1986950.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

I clicked on modify POI, and see the following odd time spans. See image below
 There is one blank time span, and one which says Mo-Su, without a time span
But looking at data in JOSM for opening_hours, I see this:
Fr-Tu 10:00-17:00; Th 10:00-21:00; May 27-Sep 4 Sa 10:00-20:00; Dec 25 off; Nov Th[4] off
I suspect that there is a problem with parsing opening_hours
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/2257107/204665829-1d451e81-abbf-4d3b-a392-02f833edff01.png"  width="300" height="auto"/> </th>
  </tr>
</table>  
### Your Environment
OsmAnd Version: 4.2.7
Android/iOS version: LineageOS 18.1, Apri 21, 2022
Device model: OnePlus 6

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
California standard map, Oct 31, 2022

**Comment by Zirochkabila** [comment]
I think the whole point is the tag "24/7 off" - this tag causes conflict behavior
<img width="859" alt="Screenshot 2022-12-06 at 17 00 41" src="https://user-images.githubusercontent.com/104760013/205947988-d088fe7e-ae82-4ee2-be12-b64576fb664f.png">


Using the new [Map](https://drive.google.com/file/d/1bG7rF9_nUIN1_YY15LthO2fSTBHkXUcN/view?usp=sharing) without the "24/7 off" tag - displays the museum open according to the specified hours

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/205948799-d2f16d0c-877c-460a-9179-dd95ec0a3881.jpeg"  width="500" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/205948808-a80e1cda-5726-4a42-b848-256cf072e6cc.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  


Using a new [Map](https://drive.google.com/file/d/1TxfvL3eXdXtSvNUJrhiEXZLbqjGAEpZl/view?usp=sharing) with the "24/7 off" tag - displays the museum is closed twenty-four hours a day

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/205949953-179ca077-dcc9-42a2-8b74-c6041ac4001f.jpeg"  width="500" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/205949308-d8628526-bb3f-47d7-b7dd-f0f77a444e40.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by MarioSwitch** [comment]
Rules separated by semicolons overrides previous rules if having conflicts with. So the "24/7 off" (because specified in the last rule) overrides all other rules, so the POI is considered 24/7 closed.

**Comment by scaidermern** [comment]
Was there any fix in OsmAnd?

The opening_hours value was probably not what the author intended but it was still a syntactically correct value. The interpretation by OsmAnd was wrong. As explained earlier, "24/7 off" should lead to OsmAnd displaying "closed" without specifying any opening date in the future (because there is none).

So this is still a bug in OsmAnd, isn't it?

**Comment by vshcherb** [comment]
I don't think it's a bug of OsmAnd. I don't pretend that OsmAnd algorithm is perfectly correct though opening hours has insanely bad design so we intend only support popular and correct values, here I think the value is not correct and should be fixed
