### ISSUE TITLE
Battery drain: Pixel 7 (40% per hour)

### ISSUE THREAD

**Issue by MarioSwitch** [osmandapp/OsmAnd#15874]
### Description
On my new phone, the app consumes about 40% of battery per hour. Furthermore, my phone overheats after ~5 minutes.
It is very weird (and a bit dangerous) as on my previous phone (a Samsung Galaxy J6 on Android 10), the app had no problems.

### How to reproduce?
Just keep the app opened for 5 minutes.

### Your Environment
OsmAnd Version: 4.2.7 (downloaded from F-Droid)
Android/iOS version: Android 13
Device model: Google Pixel 7

**Maps used (online or offline):**   
Bug not related to maps

**Comment by MarioSwitch** [comment]
Some precisions:

- Battery is consumed at ~40%/h only if in Navigation Mode
- I've launched a simulation to give precision on consumption and will try with Google Maps to compare

Sorry, for my bad English, I am French!

**Comment by sonora** [comment]
PS: Also worth testing: `(OsmAnd) > Menu button > Settings > OsmAnd settings > Location source`, set to `Android API`.

**Comment by MarioSwitch** [comment]
> PS: Also worth testing: `(OsmAnd) > Menu button > Settings > OsmAnd settings > Location source`, set to `Android API`.

This setting doesn't exist in OsmAnd 4.2.7
![Screenshot_20221207-112020.png](https://user-images.githubusercontent.com/58565980/206152996-c5a5a648-1e0c-4ce2-ba8e-f85e2e120414.png)

**Comment by MarioSwitch** [comment]
Fortunately, OsmAnd 4.3.1 from the Google Play Store beta program doesn't have this problem.

**Comment by vshcherb** [comment]
Do you use OpenGL rendering ?

**Comment by MarioSwitch** [comment]
> Do you use OpenGL rendering ?

Both 4.3.4 from Google Play and 4.3.3 from F-Droid doesn't have this problem. So, I think this issue would be closed.
