### ISSUE TITLE
surface and smoothness indication sometimes disappears

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1587]
http://www.openstreetmap.org/#map=16/56.10665/40.397938
At zoom 16 (OpenGL and old engine, also rendering style does not matter (default or UniRS)) in bicycle mode smoothness and surface indication partially disappears.
![screenshot_2015-08-24-07-44-16](https://cloud.githubusercontent.com/assets/5829014/9435894/2912ad82-4a54-11e5-9483-6bc3167bd59c.png)
But with "default" profile all is correct
![screenshot_2015-08-24-07-44-07](https://cloud.githubusercontent.com/assets/5829014/9435903/3f63dafc-4a54-11e5-9984-4af8b627d845.png)
But if we decrease zoom to 15 in bicycle mode all is correct again
![screenshot_2015-08-24-07-44-42](https://cloud.githubusercontent.com/assets/5829014/9435918/62db477c-4a54-11e5-9df2-dbc7611c4521.png)
Can't reproduce this bug in OsmAndMapCreator, only on device (android 4.4.2)

**Comment by vshcherb** [comment]
Can't reproduce
