### ISSUE TITLE
Crash when choosing Approximate location 

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#15883]
### Description
 When choosing Approximate location OsmAnd crashed
[exception (21).log](https://github.com/osmandapp/OsmAnd/files/10140444/exception.21.log)

### Steps to reproduce
My location > Select Approximate > Only this time

### Actual result
OsmAnd crashed

https://user-images.githubusercontent.com/104760013/205276909-896ab77e-b8f7-44e3-9201-3aba5b0f7a7d.mp4

### Expected result
Approximate location displayed on the map

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#13991mqta, released: 2022-12-02
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by vshcherb** [comment]
Merged back https://github.com/osmandapp/OsmAnd/issues/15857
