### ISSUE TITLE
Incorrect highway=tertiary geometry at different zoom levels

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1589]
http://www.openstreetmap.org/#map=13/55.76765/40.9326
Russia_vladimir_asia_2.obf
![_2015-08-24_12-56-52](https://cloud.githubusercontent.com/assets/5829014/9437681/b2aff9ee-4a60-11e5-8e54-048b721bfc98.png)
![_2015-08-24_12-57-32](https://cloud.githubusercontent.com/assets/5829014/9437682/b4b268b2-4a60-11e5-8545-ac9f704eca8c.png)
![_2015-08-24_12-58-17](https://cloud.githubusercontent.com/assets/5829014/9437685/b71c6030-4a60-11e5-995e-a1874af9c31a.png)
![_2015-08-24_13-00-25](https://cloud.githubusercontent.com/assets/5829014/9437689/b9846e30-4a60-11e5-8916-393e9f9f3f6c.png)

**Comment by xmd5a2** [comment]
http://www.openstreetmap.org/#map=14/55.749203/37.562134
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshot_2015-08-26_21-33-40.png
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshot_2015-08-26_21-33-51.png

**Comment by vshcherb** [comment]
Can't reproduce with latest map (possibly it is realted to roads-only map but then it is a known issue and has completely different priority
