### ISSUE TITLE
NPE when trying to "reverse track direction" of a GPX track

### ISSUE THREAD

**Issue by omo42** [osmandapp/OsmAnd#15891]
### Description

Trying to reverse the GPX track direction immediately opens a pop-up saying:

_Attempt to invoke interface method `void java.util.List.clear()` on a null object reference_

### How to reproduce?

- choose a GPX track for navigation
- press the "follow track" input field
- press button "reverse track direction"
- NPE popup displays

### Your Environment
OsmAnd Version: Fails for 4.3.1/4.3.2 Release (worked with the same GPX track for 4.2.7 Release)
Android version: 9
Device model: Samsung Note 8

**Comment by ivanPyrohivskyi** [comment]
Check build 3 weeks ago

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14012mqta, released: 2022-12-09
Done

https://user-images.githubusercontent.com/104760013/206707145-d012093f-d394-494e-affb-04cc51425bdf.mp4
