### ISSUE TITLE
Bicycle lanes not to be displayed at car routing

### ISSUE THREAD

**Issue by cepesko** [osmandapp/Osmand#1590]
When car routing along [here](https://www.openstreetmap.org/way/23428592) tuning westbound, osmand displays 3 yellow left arrows indicating three usable lanes, where in fact only the two left ones are for cars. Lane 3 is designated for bikes (width 1.2) only.

Doing a bike routing instead should - on the other hand - display only one possible left arrow as the two left lanes are reserved for cars (compare bicycle tagging: no|no|designated|right).

**Comment by vshcherb** [comment]
It is not supported yet, but I think it should be tag 
access:lanes:forward (so it will describe the limits) similiar to bicycle:lanes:forward

**Comment by sonora** [comment]
No further action planned, it seems.
