### ISSUE TITLE
Add map rendering  - map mode option "follow system"

### ISSUE THREAD

**Issue by thousandsofthem** [osmandapp/OsmAnd#15902]
# 🚀 feature request

### Description

At this moment it's hard to switch day/night map rendering to the desired state.

### Describe the solution you'd like

* add "Follow System" option, which will turn map rendering mode to match android system (probably iOS as well) dark mode
* Listen to system event for dark mode change - also, currently implemented "app theme - system default" doesn't apply new changes until app restart

### Describe alternatives you've considered

- "light sensor", "sunrise/sunset" were always unpredictable since ancient versions of osmand. They are also do not allow changing day/night rendering with low amount of clicks
- quick action button: this button is sometimes hidden for some unknown reason, which totally defeats its purpose

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/3384
