### ISSUE TITLE
Incorrectly displayed the building number

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#15910]
### Description
Correct building address display only if you click on the middle of the building. 
When you click on the end of the building displays the neighboring 
 address. See the screenshots below.

<table style="width:100%">
  <tr>
    <th>correct address</th>
    <th>incorrect</th>
    <th>incorrect</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/80623554/206185146-328047ad-f6c5-4db3-89b8-9c8f0da13ae7.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/80623554/206186524-60a75239-2973-4571-8cbf-31ca4199c07d.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/80623554/206186672-ca043a36-7fda-47a6-9615-3f617bb01b01.png"  width="300" height="auto"/> </td>
  </tr>
</table>   
https://www.openstreetmap.org/way/953064187#map=19/55.78730/49.25614

Tested Kazan, Azart Abbasov Street 23A
OsmAnd 4.3.1
Downloaded map: Russia Tatarstan
Map updated 1 Dec 2022

### How to reproduce?
Click on the different sides of the building.

**Comment by vshcherb** [comment]
If you don't click on edges it works correctly https://osmand.net/map#18/55.78713/49.25642

**Comment by vshcherb** [comment]
OsmAnd doesn't store polygons of address, so it needs to be later analyzed using the map section, I think it's a duplicate of another existing issue that's planned somewhen in the future.
