### ISSUE TITLE
2.5D not enabled for Android Auto

### ISSUE THREAD

**Issue by aitorpazos** [osmandapp/OsmAnd#15913]
I love the 2.5D feature as it provides really useful details in the short range and good overview for longer distances.
However, I am not able to get that perspective in the Android auto screen.

**Comment by mitohund** [comment]
Ah that's a shame. So there is also no ETA regarding this feature?

**Comment by vshcherb** [comment]
No ETA, but I hope in 2023 will be done

**Comment by dmpr0** [comment]
Beta builds 4.6.6 support 2.5D rendering in Android Auto
https://play.google.com/apps/testing/net.osmand 
https://play.google.com/apps/testing/net.osmand.plus

**Comment by dmpr0** [comment]
## Documentation
* Remove info about 2.5D is not available for Android Auto 
* Add info about new 3D Mode button in Android Auto

**Comment by shurasmiling** [comment]
https://docs.osmand.net/docs/user/navigation/auto-car#map-appearance

**Comment by EugeneZmeuk** [comment]
**16-04-2024 Review**
- added [the section](https://docs.osmand.net/docs/user/navigation/auto-car/#map-appearance-3d)
