### ISSUE TITLE
OsmAnd freezes at startup

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#15926]
### Description
with some tracks (~20) displayed osmand completely freezes at startup. 
The dialogue "close/wait/feedback" appears again and again.
Sometimes it takes 10 minutes, until I can use Osmand again.

In earlier versions (<4.x?) osmand was able to start with 50 or more tracks being displayed, without a noticeable delay. Now it needs 5 minutes or even longer, until I can use osmand. Not even the "give feedback"-button reacts.

I really would like to go back to a pre-4-Version, where can I find the "+ versions for download? 

### How to reproduce?

See the attached log.
I´m not sure, if this perhaps is caused by Android 13.
On myother S20+ I avoid the update 12>13 and this problem does not exist.

### Your Environment
OsmAnd Version: 4.3.2+
Android/iOS version: 13
Device model: Samsung S20+5G

[logcat.log](https://github.com/osmandapp/OsmAnd/files/10196759/logcat.log)

**Comment by Rowin63** [comment]
Deleted and installed Osmand+ again.
At the initial start Osmand had to restart ("app has to use the external memory, for this it needs to restart").
Downloading the first map.
Storage is, as automatically set, multiuser 1.
I closed Osmad and opend again: again I´m at "first steps" and have to select and download a county. Why?
Next step: restoring "my settings" from a local backup. 
Restart.
Next step: restoring "my places" from a local backup.
Next step: restoring "my sources" from a local backup (without maps)
Until here Osmand runs fine.

I will see, when and why this problem occurs again.

**Comment by Rowin63** [comment]
Its not an Android 12/13 issue (happens also on my tablet with Android 12 and Osmand 4.3.0).

But the more tracks are selected, the longer Osmand freezes (and shows repeating this "wait/close/send report"-dialoque) at startup. Witrh about 50 hiking tracks selected/displayed, Osmand needs around two minutes until it is useable. Then its not a problem anymore.

**Comment by Rowin63** [comment]
Good morning.

This is the logfile from the last Osmand start. I could not use it, the pop-up-dialoge "wait/close/report" kept popping um every few seconds (~10s). Had to close Osmand after a few minutes of waiting.

Next osmand start the same. Close it again.
Next osmand start did work.

That really drives me mad.

Logcat.2 is from the last start, without popup dialogue

[logcat.log](https://github.com/osmandapp/OsmAnd/files/10205956/logcat.log)
[logcat (2).log](https://github.com/osmandapp/OsmAnd/files/10206022/logcat.2.log)

**Comment by Rowin63** [comment]
de- and re-installed Osmand.
Importing my local backups ((settings, places, sources).
Osmand runs fine again - starts without delay and is useable within a second. 

If it helps, here´s the actual logfile.

[logcat (3).log](https://github.com/osmandapp/OsmAnd/files/10208050/logcat.3.log)

**Comment by Rowin63** [comment]
Will this be part of 4.3.3? Thank you 👍

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14028mqta, released: 2022-12-16
The issue with the map freezing when displaying tracks has been resolved
But, the map froze after loading the artificial map of [Ireland](https://drive.google.com/file/d/10DMH6ZaXVgMnukAwPzCV_5KsjnmYqvLo/view?usp=sharing) and the standard map of Ireland in OsmAnd (Legacy)


[logcat (32).log](https://github.com/osmandapp/OsmAnd/files/10246291/logcat.32.log)


https://user-images.githubusercontent.com/104760013/208113388-7f90be1b-ccd5-49b1-a797-da687f213cbb.mp4

**Comment by Iris92** [comment]
I have the same problem with version 4.3.3
At startup, the screen freezes on the osmand logo! I uninstalled and reinstalled 3 times without success.
I'm on Android v10 with Samsung S9
I can only use the free version of osmand ;((
![Screenshot_20221221-162823_OsmAnd+](https://user-images.githubusercontent.com/7853744/208943159-86aafd66-b567-41df-b6c6-775505a2f52f.jpg)

**Comment by ivanPyrohivskyi** [comment]
@Iris92 
[Please get log report from you device](https://osmand.net/docs/user/troubleshooting/crash-logs#using-adb). Connect device, open terminal, and run command:
``adb bugreport ./output.zip``
On your device accept permission from computer.
And attach output.zip in the answer. 

After just make full reset of application in phone Settings (clear all data). After this app must run successfully.

**Comment by anastasiia936** [comment]
The app needs 1 minute and 50 seconds to build the map. No matter what rendering. The maps are on the external memory card, but that's where they've always been! Tracks are not installed.
[logcat (17).log](https://github.com/osmandapp/OsmAnd/files/10293856/logcat.17.log)

Device : gauguin
Brand : Xiaomi
Model : M2007J17G
Product : gauguin_eea
Build : SKQ1.211006.001 test-keys
Version : 12
App Version : OsmAnd+
Apk Version : 4.3.3 4303

**Comment by anastasiia936** [comment]
OsmAnd 4.3.3 freezes and won't start on my Samsung S8, since I updated on December 13
[logcat (18).log](https://github.com/osmandapp/OsmAnd/files/10294176/logcat.18.log)

**Comment by anastasiia936** [comment]
Samsung Galaxy S20fe OS version: One UI version 4.1 Android Version 12

**Comment by Rowin63** [comment]
Since #15968 is closed and merged to here: 
Again a freeze happened, exactly like the last I described in the closed issue.
Osmand was very slow in Engine 2 (~40 tracks displayed, not possible to work useful anymore), after switching back to engine 1 the map froze, but the menues do work.

In this state I have to kill and restart Osmand. 
It is now the V +4.3.4

**Comment by ivanPyrohivskyi** [comment]
Freeze during map download. I used SD card for map download.
Steps to reproduce:
1. Start map downloading.
2. Disable internet.
3. Scroll map, but some tiles must do not finish load. Better to use online tiles, in this case freeze occur more often.
4. Stop (swipe) application.
5. Open application again. App is freeze.

Place in the code:
https://github.com/osmandapp/OsmAnd-core/blob/51ce49638faeec470a98f6e6dd2123dfd7f47442/src/Map/MapRendererResourcesManager.cpp#L2064

Stack to the line:
[stack.txt](https://github.com/osmandapp/OsmAnd/files/10308571/stack.txt)

Logcat during freeze:
[logcat.log](https://github.com/osmandapp/OsmAnd/files/10308588/logcat.log)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14057mqta, released: 2022-12-28
No freezes were observed

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14066mqta, released: 2022-12-31
Done
