### ISSUE TITLE
Speech output not working without internet

### ISSUE THREAD

**Issue by seppwabala** [osmandapp/Osmand#1592]
When internet connection (Wifi or mobile) is available, speech output during routing works.
As soon as internet goes off, speech output is not working.

Device: Samsung G7582
Android 4.2.2
Osmand+ 2.1.1

On my Samsung Tablet SM-P600 with Android 4.4.2 Osmand+ 2.1.1 everything is fine.

Thanks for your help and many thanks to all contributers for this great app.
Norbert

**Comment by vrtareg** [comment]
Hi
Which speech engine you are using?
Build in one can possibly require internet connection.
Can you try Ivona one from Google Play?
I never had problem with it.
Regards,
Areg

**Comment by seppwabala** [comment]
Thank you for the hint!
I uses Google TTS in Android Settings as Prefered TTS Engine. When I change to Samsung TTS it works.
