### ISSUE TITLE
'Simulate navigation' option is always offered

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#15929]
I believe we wanted to offer the "Simulate navigation" route settings option only when the Development plugin is enabled, but it seens it is always visible:

![Screenshot_20221210-015537_OsmAnd~](https://user-images.githubusercontent.com/845735/206820603-254eaa17-9863-4d01-9571-4aa6c0a2cbef.jpg)

**Comment by vshcherb** [comment]
Nope last year or more we did it intentionally for everyone,  it's a key feature for all people to see how osmand works in navigation
