### ISSUE TITLE
Blue dot location renders below routing line - analyze on map

### ISSUE THREAD

**Issue by arncor** [osmandapp/OsmAnd#15928]
### Description
When planning a navigation, then before pressing "start", go to details > analyze on map. When moving the blue dot location, I found it hard to see and realized it renders below the routing line.

### How to reproduce?
Plan a navigation, before starting, go to details > analyze on map a'd move the location 

### Your Environment
OsmAnd Version: 4.3.2 (edit : OpenGL rendering)
Android:9
Device model: Armor Ulefone 6E

**Maps used (offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date: off-road map style. <table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/91597340/206811810-71eab78b-4b71-497b-9b84-d983aab51edf.png"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
You can try to use rendering engine version 2 and see if it looks better in OsmAnd Global Settings

**Comment by arncor** [comment]
Oups, I forgot to mention I was already using version 2 (OpenGL). I just checked, the issue is not present with version 1.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14023mqta, released: 2022-12-14

When using OpenGL - the dot is displayed under the route
When using Legacy - above the route


https://user-images.githubusercontent.com/104760013/207536813-3ecbe694-8f56-4462-87c8-9a6c80ebb1cc.mp4

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14028mqta, released: 2022-12-16
Still present at OpenGL

OpenGL

https://user-images.githubusercontent.com/104760013/208104924-6795b9db-56d8-4bc2-97ea-a5627c30e9a5.mp4

Legacy

https://user-images.githubusercontent.com/104760013/208104933-ff8eeaa2-5eb9-4d7b-85ef-bb844b67a53b.mp4

**Comment by ivanPyrohivskyi** [comment]
Will be in nightly 21.12.2022
Merged from r4.3 to master
https://github.com/osmandapp/OsmAnd/commit/779f4b82c67a2754b37f067a2e4e42bb64c670dc

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14037mqta, released: 2022-12-21
OpenGL - the blue dot is displayed above the route

- [ ] but under the turn arrows

- [ ] blue dot skips route segments - jumps from the beginning to the end

- [ ] if change to Legacy rendering and then back to OpenGL - the route disappears from the map and the blue dot is no longer displayed. Only turn lanes are displayed.


https://user-images.githubusercontent.com/104760013/208882323-d5838bed-ef18-48e4-923a-c0676247391f.mp4

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14116mqta, released: 2023-01-19
Done
