### ISSUE TITLE
5-star intersection - identify each turn by suggestion

### ISSUE THREAD

**Issue by Dimitar5555** [osmandapp/OsmAnd#15930]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Car
### Start and end points
Start point: 42.68940, 23.31503
End point 1: 42.68917, 23.31342
End point 2: 42.68982, 23.31349

### Actual and expected routes

For end point 1: the router suggest to go in the U-turn lane.
The expected lane suggestion is slight left.
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/19364673/206840202-cf65658a-78e9-4368-8063-7cd1ee4e0f99.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

For end point 2: the router suggest to go in the U-turn or slight left lanes.
The expected result is slight right
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/19364673/206840231-ea6e85d8-d2aa-48d8-9089-9610d87c92cf.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
I don't know.
## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>4.2.7</code></pre>

**Device and Android/iOS version:**
Honor 20 Lite
Android (EMUI) 10.0.0
**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**

**Comment by letypequividelespoubelles** [comment]
I had the same, and it seemed to me it was the case just when there was lane:forward=* and/or lane:backward=* tags.

**Comment by Dimitar5555** [comment]
I've updated the values for `lanes:forward` and `lanes:backward`. Unfortunately the bug is still present.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14016mqta, released: 2022-12-12
Reproduced
[Map](https://drive.google.com/file/d/1M87qxt40zqT0gVrZC5W9OB77KAMnFJEY/view?usp=sharing)
[OSM](https://www.openstreetmap.org/?query=42.68933%2C23.31540#map=18/42.68976/23.31404)
[OsmAnd](https://osmand.net/map/?end=51.996964%2C4.474783&mode=car#18/42.68942/23.31429)


https://user-images.githubusercontent.com/104760013/207101847-73000c70-b34c-42bb-9e72-9c8d13452d55.mp4


https://user-images.githubusercontent.com/104760013/207101962-77ecdfab-5ab3-439a-a36a-e21e3cfd112f.mp4

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#254m, Released: 2023-06-20 - **Done**
4.4.10.7 - **Still present**

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/752d2809-9418-4ef6-b906-0244117ad201"  width="500" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/eb1f8903-8dd8-4ac6-b1eb-d3cffb19f64e"  width="500" height="auto"/> </th>
  </tr>
</table>
