### ISSUE TITLE
Irish N road shields not coloured correctly

### ISSUE THREAD

**Issue by bmeath** [osmandapp/OsmAnd#15937]
### Description

Signage for Irish national roads show the road number (e.g. N7) in yellow text on a green background,
but the app displays the road number in black text on a white background.

<img src="https://user-images.githubusercontent.com/19391546/206924827-f2f04629-84f7-4025-8f84-cbdfa0c71d57.jpg"  width="300" height="auto"/> 

### How to reproduce?

Open OsmAnd, find a road in Ireland whose "ref" starts with N, and zoom in until the road shield is displayed.

### Your Environment
OsmAnd Version: 4.2.7
Android/iOS version: Android 12
Device model: OnePlus 10T

**Maps used (online or offline):**   
Offline - Ireland_europe - 1 Dec 2022 edition

**Comment by bmeath** [comment]
Out of interest I had a go at fixing this myself, with success!
So I have a code change to the https://github.com/osmandapp/OsmAnd-resources project,
which I would like to contribute as a fix to this bug.

**Comment by vshcherb** [comment]
Sure please create pull request.

**Comment by xmd5a2** [comment]
Fixed in https://github.com/osmandapp/OsmAnd-resources/pull/912

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14028mqta, released: 2022-12-16
Done

**Comment by dmpr0** [comment]
With information in the issues, I didn't see difference. Please provide additional information for testing if it needed.

**Comment by xmd5a2** [comment]
![Screenshot_2022-12-16_16-58-49](https://user-images.githubusercontent.com/5829014/208114285-f9d16201-723f-4546-aab2-d9d4063ced31.png)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14050mqta, released: 2022-12-27
`53.0016, -6.6442`
**It's not possible to check**, the road numbers aren't displayed.
The map was generated according to the instructions:
1. Download the [map](https://drive.google.com/file/d/18kZuB2l-D5FewcUyiNx1Hrt0RrAtms1l/view?usp=sharing) via OSM
2. Change the map name according to the [region name](https://osmand.net/list.php) (Ireland_europe_2)
3. Generate a map using MapCreator


https://user-images.githubusercontent.com/104760013/209653463-628489b1-6191-4d6b-a361-5987663744fc.mp4

**Comment by dmpr0** [comment]
Fixed with new map of Ireland for Jan 1. But we still need to update World Base map to include these changes.

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/210351145-3158e6ef-197f-42c1-81d8-40b45e291697.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/210351151-8c77c3f1-82ee-42ef-ba29-8a5be39f1178.png"  width="300" height="auto"/> </td>
  </tr>
</table>
