### ISSUE TITLE
Rendering engine 1: display tracks  under overlay

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#15934]
### Description
when using the rendering engine 1, overlay map (microsoft earth) and transparency slider all the way right, also tracks are covered by the overlay. Was never before like this, and is not when engine 2 is active. Tracks and favourites are always visible. 

### How to reprodu
acrtivate overlay microsoft earth

### Your Environment
OsmAnd Version: 4.3.2+
Android/iOS version: 12 + 13
Device model: S20+

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14014mqta, released: 2022-12-10
OsmAnd~ 4.4.0#14015mqta, released: 2022-12-11
Overlay map (Microsoft earth)
Map rendering engine (V1)

[logcat (29).log](https://github.com/osmandapp/OsmAnd/files/10202031/logcat.29.log)

https://user-images.githubusercontent.com/104760013/206900918-d78c3f03-1e26-4b76-97bf-963aacaaac3d.mp4

**4.2.7**
Worked correctly

https://user-images.githubusercontent.com/104760013/206901882-a4338b26-9c48-4fd1-b9aa-d480fc454d83.mp4

**Comment by vshcherb** [comment]
Yes, priorities changed to 4.3

**Comment by ivanPyrohivskyi** [comment]
15934

**Comment by ivanPyrohivskyi** [comment]
Need to fix transparency from overlay layer during switching rendering engines.
And need to fix gradient color of track.
<img src="https://user-images.githubusercontent.com/1040293/207546049-ccc5f6d7-ba55-45b3-8f5d-b5be50f9de97.jpg" width="400" />

**Comment by ivanPyrohivskyi** [comment]
Gradient color issue https://github.com/osmandapp/OsmAnd-Issues/issues/1796

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14028mqta, released: 2022-12-16
Done
