### ISSUE TITLE
OpenGL: Pinch zoom sometimes acts a tilt 

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#15931]
I still have the issue that pinch zooming when using the new Version 2 render engine is sometimes interpreted as tilt operation.I think it's accidental, not documented here https://osmand.net/docs/user/map/interact-with-map#gestures.

To reproduce, hold the phone with your right hand and pinch zoom in with thumb and index finger of your left hand, i.e. index finger is essentially "north" of where your thumb touches the map.

Issue for the users is you don't know how to leave that mode again to get to normal zooming, or reverse the tilt angle change.

**Comment by vshcherb** [comment]
Observation: They could leave that mode by double click on my location

**Comment by vshcherb** [comment]
Needs to be tested how sensitive it is.

Other points:
- Mode could be disabled in settings
- To get back user can click on my location
