### ISSUE TITLE
Editing bookmarks screen buttons outside screen

### ISSUE THREAD

**Issue by duemoselund** [osmandapp/OsmAnd#15936]
The bookmark screen for editing and saving bookmarks, displays the two buttons at the bottom partly outside of the screen. 

Samsung Galaxy S21 Fe
Android v. 13 
One UI v. 5.0
OsmAnd+ v. 4.2.7

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/11139391/206902259-ba820133-526d-4061-977f-d9cc0ac9ab44.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14016mqta, released: 2022-12-12
Not reproduced - try to download the night version (beta version - you can become a beta tester on the OsmAnd page in the Play Store). Most likely, this bug has been fixed.


https://user-images.githubusercontent.com/104760013/207093061-cee9fc85-8c44-41c0-89f5-b58b790f60cb.mp4
