### ISSUE TITLE
live update size looks wrong

### ISSUE THREAD

**Issue by 532910** [osmandapp/OsmAnd#15933]
It looks like live update size is shown wrong.

For Georgia, for example, it's huge and sometimes increases every "Update now" press.

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/14617699/206865847-402ed83f-76a7-4992-aa95-fc3d8ad7cbad.png"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/14617699/206865848-b2e73361-ab60-4b80-8299-c38ddd77079e.png"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/14617699/206865849-bbb23056-c2fb-4cb5-8d89-fe1b205b1c2d.png"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/14617699/206865852-9058ebe9-296d-4f8b-af38-68d4918c50e4.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Your Environment
OsmAnd Version: 4.2.7 from f-droid
Android/iOS version: 11 (LineageOS 18.1)
Device model: OnePlus 3t

**Comment by Zirochkabila** [comment]
OsmAnd 4.2.7, released: 2022-07-13
OsmAnd~ 4.4.0#14016mqta, released: 2022-12-12
Behavior can be reproduced on both versions. The file size increases by several megabytes after two or three clicking

4.2.7

https://user-images.githubusercontent.com/104760013/207145396-dc602c9e-350b-417f-8d4f-6557b0762346.mp4

4.4.0

https://user-images.githubusercontent.com/104760013/207145402-69231878-f04c-4cfa-bc17-1b448972d92e.mp4

**Comment by Dima-1** [comment]
Fixed https://github.com/osmandapp/OsmAnd/commit/4d79bafd5ed61dfad2d5ca1023c0825cf2a79c74

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14026mqta, released: 2022-12-15
Done
