### ISSUE TITLE
Moving POIs and changing it's tags doesn't move the POI

### ISSUE THREAD

**Issue by Dimitar5555** [osmandapp/OsmAnd#15940]
### Description
When I change a POI's tags and move it in the same change, the position is not updated.

### How to reproduce?
1. Select a POI
2. Change any of it's tags
3. Zoom to the maximum allowed level to it
4. Hold on the POI until your phone vibrates
5. Move it to a new position
6. Upload the changes

### Your Environment
OsmAnd Version: 4.2.7
Android/iOS version: Android 10.0.0
Device model: Honor 20 Lite

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14031mqta, released: 2022-12-18
Reproduced

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14074mqta, released: 2023-01-05
Done
