### ISSUE TITLE
Rotating screen with certain menus open disables overlays / underlays

### ISSUE THREAD

**Issue by mikehgentry** [osmandapp/OsmAnd#15949]
### Description

Rotating the screen switches overlays and underlays off in certain circumstances.

### How to reproduce?

1. Enable an overlay / underlay (doesn't seem to matter which one).

2. Go to Configure map -> Tracks, but don't select anything.

3. Rotate the phone (with screen orientation set to 'same as device')

You will be dropped back to the map, but with the overlay / underlay switched off.

### Your Environment
OsmAnd Version: 4.3.2
Android/iOS version: 11
Device model: XCover 4s

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14016mqta, released: 2022-12-12
Reproduced

Only with OpenGL - please note that following the same steps, but switching from a horizontal to a vertical orientation, a slight graying on the map remains


https://user-images.githubusercontent.com/104760013/207147593-87d4f200-d7e1-4581-bd2b-382b8a853ad2.mp4

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/pull/15995

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14037mqta, released: 2022-12-21
Done
