### ISSUE TITLE
My Places Favourites Sort Order Incorrect

### ISSUE THREAD

**Issue by mokkies** [osmandapp/Osmand#1594]
Favourites are now showing incorrectly out of sort order, which is a bit of a nuisance when you are looking for a favourite in a long list in My Favourites in My Places.

In version 1.9.5. of OsmAnd+ on Android favourites displayed in a list were listed in a logical alphanumerical order, with favourites listed first with those starting with numbers 0-9, and then characters A-Z after that.

In version 2.1.1. of OsmAnd+ on Android there are a few problems:-

1. Numbers are sorted after letters, and not first.

2. A name with a number anywhere in the title is now sorted as a number, so for example 'Hotel 257  Main St', is now sorted as if it just said '257'.

3. New waypoints may appear near end of the favourites list even after a force close of Osmand.

4. Alphabetical sorting of names is broken as some new waypoints show out of correct alphabetical order. 

(These problems occur even if you test the very same 'favourites.gpx' file from v1.9.5.)

I hope this will be fixed soon.

**Comment by vshcherb** [comment]
Fixed.

Proper order tested now takes into account numbers, here is an example of sorting:
ega 5
egg 1
egg 2
egg 12 
egg 34
egh 4

**Comment by mokkies** [comment]
Hi Vshcherb,

Thank you for the information in your reply.

Could you please clarify your reply of "Fixed" and "Proper order tested now takes into account numbers...". 

1. Were you able to replicate the favourites sorting issue?
2. Does this mean the code of the program has now been changed to fix this sorting issue?

Thanks your assistance.

**Comment by vshcherb** [comment]
1. Yes
2. Yes, now it sorts as I put in comment

**Comment by vshcherb** [comment]
Fixed means you can try a nightly build to double check

**Comment by mokkies** [comment]
Hi Vshcherb. Thank you for the clarification. Many Thanks.
