### ISSUE TITLE
Old rendering engine: textWrapWidth depends on density

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1595]
Density=1:
![_2015-08-25_15-20-10](https://cloud.githubusercontent.com/assets/5829014/9466379/211d7230-4b3d-11e5-93d7-70de97148422.png)
Density=5:
![_2015-08-25_15-20-51](https://cloud.githubusercontent.com/assets/5829014/9466390/316a1206-4b3d-11e5-8974-29a5847d322d.png)
Bug or feature?

**Comment by vshcherb** [comment]
Fixed
