### ISSUE TITLE
Switch to new profile upon creation?

### ISSUE THREAD

**Issue by mikehgentry** [osmandapp/OsmAnd#15950]
### Description

When you create a new profile, I think you have the expectation that you've been switched to it. In a lot of circumstances you're going to be using a profile when you decide to create a new one based upon it, meaning the profile you're in and the one you've just created initially appear identical. When you hit 'save', the menu switches context to the new profile, reinforcing the confusion. This creates the unfortunate situation where you end up modifying the old profile rather than the new one.

### How to reproduce?

Create a new profile, duplicating the profile that you're currently set to. When you hit 'save' the menu's context switches to the new profile. By the time you've exited the menu, you're back in the old profile.

edit - assigning a random new colour when you create a profile, rather than inheriting it from its parent, would help eliminate the confusion - at least then you'd have a visual cue when the switch happens.

### Your Environment
OsmAnd Version: 4.3.2
Android/iOS version: 11
Device model: Xcover 4s

**Comment by dmpr0** [comment]
New profile will have different name **Driving** > **Driving 1**

**Comment by mikehgentry** [comment]
True. The current behaviour isn't wrong as such, but I find it counterintuitive, and at least twice I've duplicated a profile then set about making adjustments, only to realise I'd been modifying what I intended to leave as the original profile, and had to swap their names and reorder them in the list.

I think it's a convention in software that 'Create \<new environment\>' *usually* means 'Create and activate \<new environment\>', and it's better to follow those conventions unless you have a good reason not to.

**Comment by mikehgentry** [comment]
So the way this actually seems to work now (not sure if this was always the case and I just didn't notice) is if you edit the settings while you're creating the profile, you will be in the new profile when you exit the menu. If you don't edit them (just clone a profile, hit save, then hit back till you're out of the menu) the profile is created, but you'll be in the prior profile. That seems extra confusing, and I guess it isn't deliberate.

**Comment by vshcherb** [comment]
You actually on top of the screen have the name of profile you edit, so it's not confusing cause you need to see what you are editing to not edit any profile blindly. 

I tested myself didn't find anything confusing
