### ISSUE TITLE
[BUG] Broken “Search street in city” highlighting

### ISSUE THREAD

**Issue by JakeSmarter** [osmandapp/OsmAnd#15956]
Since version 2.0 the highlighting of the city name in the address search is broken, especially in other locales than `en`. See examples below:
![OsmAnd “Search street in city” en](https://user-images.githubusercontent.com/15823872/207327814-42092f48-c37d-4ad9-802d-4ad20aae36e3.png "OsmAnd+ “Search street in city” en")
![OsmAnd “Search street in city” de](https://user-images.githubusercontent.com/15823872/207327872-d0a76df5-fcaa-40da-90e0-843e68e6a2de.png "OsmAnd+ “Search street in city” de")

This is mainly due to incorrect handling of localizable strings and then trying to mark the city with a span:
https://github.com/osmandapp/OsmAnd/blob/c814f6e81efe98d81d2bb36a7c2776f3ce4dbff3/OsmAnd/src/net/osmand/plus/search/QuickSearchDialogFragment.java#L1080-L1083

**Comment by vshcherb** [comment]
Obviously it should be better to have 1) stringand then 
```
 search_street_in= "Search street in %s" 
String fullText = String.format(R.string.search_street_in, city);
int indStartSpan = fullText.indexOf(city);
int indEndSpan = indStartSpan + city.getLength();
....
```

**Comment by JakeSmarter** [comment]
Thank you for investigating.
> ```java
> search_street_in= "Search street in %s" 
> String fullText = String.format(R.string.search_street_in, city);
> int indStartSpan = fullText.indexOf(city);
> int indEndSpan = indStartSpan + city.getLength();
> ....
> ```
Initially, I had a similar idea. However, the city name can be identical to any word in the localized string or a sub-string, so any fix is not that trivial. One must make sure that only and only the city name gets spanned. I have prepared a PR to fix this issue but I am having a little bit of trouble building OsmAnd+ in order to test it. I am going to post the PR as soon I am confident it works as intended.

**Comment by sonora** [comment]
Could simply use RTL/LTR aware concatenation of strings (may be reusable for use elsewhere), see https://stackoverflow.com/questions/61653698/how-to-concatenate-string-respecting-rtl-ltr. We know the length of the prefix string (in English "Search street in") and then need no `.indexOf(city)` or any searching for the city name in the combined string.

**Comment by JakeSmarter** [comment]
:man_facepalming: I am going to say it again. It is not just about ltr or rtl. The point is that you cannot assume anything about the order or content of the localized string. Just DO NOT construct any messages from localized strings and DO NOT try to analyze localized strings in code. Treat it as an opaque data structure.

**Comment by vshcherb** [comment]
@JakeSmarter 
You are not right. I don't want to say totally but I don't see any issue with the code I mentionned
```
search_street_in= "Search street in %s" 
String fullText = String.format(R.string.search_street_in, city);
int indStartSpan = fullText.indexOf(city);
int indEndSpan = indStartSpan + city.getLength();
highlightString(indStartSpan, indEndSpan);
```

It works RTL / LTR cause symbols RTL are still encoded same way as LTR from 0 to end and if they are in the mixed mode it still problem of rendering text not to calculate which characters needs to be highlighted. 

Any prefix length / suffix length approach indeed wouldn't work cause translation can put words in any place with any combination but it will put the city name somewhere in text once and it could be found

**Comment by JakeSmarter** [comment]
> Any prefix length / suffix length approach indeed wouldn't work cause translation can put words in any place with any combination …

Right, but

> but it will put the city name somewhere in text once and it could be found

you cannot assume this either. Let’s look at an example with English words
```java
String.format("Search street %s arches", "arch");
```
Well, which `arch` do you want to highlight now? The `arch` in `Search`, the substituted `arch`, or the `arch` in `arches` at the end?

**Comment by sonora** [comment]
Our code of how we define and concatenate the strings (`"Show streets"` and `"in %s")` is overcomplicating things.

As output we always have (in English): `"Search street in <CITY>"`,
- with `<CITY>` being the only dynamic portion,
- and always being in the end.
- And I see no need in any language why `<CITY>` would need to be in the middle of that output. That's why it could be simplified and then a simple prefix length approach would work.

**Comment by sonora** [comment]
PS: String `shared_string_in_name` is also the
- **root cause 1** of the issue, because we have the invariable `"in"` in this string rather than in the prefix string.
- **root cause 2** is that the value of the German `<string name="search_street">Straße suchen</string>`  is in uppercase inflated to "STRASSE SUCHEN", which increases the length by 1 character.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14043mqta, released: 2022-12-23
Done

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/209337853-2e0a41f4-ec53-497b-a3ac-8fb85e29e4fa.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>
