### ISSUE TITLE
Last letter chopped off in widgets

### ISSUE THREAD

**Issue by TheSnoozer** [osmandapp/OsmAnd#15957]
### Description
After updating to the latest the last letter in the widgets seems to chopped off. Speed Limit should bei displayed in "km/h" and destination in "km", but the Widget only Shows "km/" and "k". Notice the same problem for the next turn distance visible in the left.

![Screenshot_2022-12-13-11-54-40-49_014aeb6b5e04ee7837dcdaecc5244511](https://user-images.githubusercontent.com/6849390/207351775-1f19f93c-76f3-45cf-9f99-ed3131601203.jpg)

### How to reproduce?
Open the application

### Your Environment
Device : RE513CL1
Brand : realme
Model : RMX3241
Product : RMX3241EEA
Build : RMX3241_11_C.05
Version : 12
App Version : OsmAnd+
Apk Version : 4.3.2 4302

**Maps used (online or offline):**   
Offline Sounds unrelated to the map used

**Comment by mikehgentry** [comment]
Duplicate of #15924

**Comment by TheSnoozer** [comment]
Thanks couldn't find that on the Phone.
