### ISSUE TITLE
Version+ 4.3.3 vehicle under route

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#15969]
### Description
vehicle is covered by the route line (engine 2)

### Your Environment
OsmAnd Version: 4.3.3
Android/iOS version: 13
Device model: S20+

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

![4 3 3 vehicle covered by route](https://user-images.githubusercontent.com/95540936/207615823-d382bc16-f94b-475b-8b26-5d490864e2c5.JPG)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14043mqta, released: 2022-12-23
Done

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/209339389-0d077b7e-496f-4492-ba3b-83fd77628dda.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>
