### ISSUE TITLE
POIs saved as Favorites don't show opening hour after update to 4.3

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#15961]
<table style="width:100%">
  <tr>
    <th colspan=2>Points saved in 4.2.7</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/207559996-2a1f60cb-7266-49ad-860f-e2eabe3a024c.jpg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/207560056-d1d2f608-b28d-4fb2-9f2c-8873850c3c7f.jpg"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14050mqta, released: 2022-12-27
Done
`50.44178° N, 30.43804° E`
[favourites (1).gpx.zip](https://github.com/osmandapp/OsmAnd/files/10307657/favourites.1.gpx.zip)

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/209656435-6185bc48-9bed-4b60-a51b-f0e80aea4674.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>
