### ISSUE TITLE
Bakery get's an info icon on higher zoom levels (map rendering engine V1)

### ISSUE THREAD

**Issue by TheSnoozer** [osmandapp/OsmAnd#15960]
### Description
On higher zoom levels a Bakery has an info icon which feels off.
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/6849390/207421465-d08c606b-cb6e-4793-8832-207173bb642a.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  
Only on zooming in more it turns into a bakery symbol
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/6849390/207421636-d1f5119d-2399-4344-ac9c-0d0ec95b23ab.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### How to reproduce?
https://www.openstreetmap.org/node/1485011637

### Your Environment
Device : RE513CL1
Brand : realme
Model : RMX3241
Product : RMX3241EEA
Build : RMX3241_11_C.05
Version : 12
App Version : OsmAnd+
Apk Version : 4.3.2 4302

**Maps used (online or offline):**   
Offline,  France Provence-Alpes-Côte d'Azur last updated on 01 dec 2022

**Comment by TheSnoozer** [comment]
OsmAnd+ 4.3.3, published on 2022-12-13 also affected

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14031mqta, released: 2022-12-18
Reproduced (Legacy only)


https://user-images.githubusercontent.com/104760013/208303937-c028dc2a-e35f-4fd2-b262-5d5ce06d844c.mp4

**Comment by TheSnoozer** [comment]
Thanks for taking the time to reproduce. Indeed I use map rendering engine V1. With V2 or OpenGL all the map is just gray which feels like my phone is not supporting the OpenGL rendering. I have added that important info to the title of the issue. Thanks again for pointing that out!

**Comment by xmd5a2** [comment]
Will be fixed in january maps

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14057mqta, released: 2022-12-28
Done
`43.36047, 5.31453`
[Map](https://drive.google.com/file/d/1wpMSD3cSr173ywIaRn6JwJfj6S4fii1I/view?usp=sharing)



https://user-images.githubusercontent.com/104760013/209810363-0d03cddf-0fd1-4555-bc20-99ef6bbd21a4.mp4
