### ISSUE TITLE
Split interval gone ?

### ISSUE THREAD

**Issue by bytes101** [osmandapp/OsmAnd#15972]
### Description

Dont see split interval gone used to be in the apperance? 
### Your Environment
OsmAnd Version:
Android/iOS version:
Device model:

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by sonora** [comment]
Things have not changed. You can both display split intervals under `Select a track on the map > tap the Appearance button > Split interval`, as well as analyze under `Options > Analyze by intervals.`

![Screenshot_20221214-232036_OsmAnd~](https://user-images.githubusercontent.com/845735/207728770-4debd4e1-bc50-4519-b97e-a4e896066697.jpg)
![Screenshot_20221214-232048_OsmAnd~](https://user-images.githubusercontent.com/845735/207728788-cd6ec543-12de-48ef-b88c-c5b86082002d.jpg)

**Comment by bytes101** [comment]
![image](https://user-images.githubusercontent.com/95884760/207836510-798c15d2-0690-4958-b464-a38955d7d452.png)

**Comment by bytes101** [comment]
this is what I see start and finish icons and no split intervals

**Comment by bytes101** [comment]
ok split intervals onlys works for tracks and not routes that is xml type <trkpt> and not <rtept>

**Comment by sonora** [comment]
Just to be sure... you _have_ scrolled that dialog all the way up, right? For me, every time I entrer that dialog I end up even further down in the color selection section and have to scroll up accordingly.

**Comment by bytes101** [comment]
yes when I changed the xml type I see it

**Comment by sonora** [comment]
Well, it e.g. won't show up for GPX files which contain only waypoints but no trackpoints... But it looked like your screenshot showed an allright track.

**Comment by bytes101** [comment]
Thanks you can close the issue its just I am have my own web based interface plotting software and I just want to make sure it works with the best mobile apps ;-)
