### ISSUE TITLE
"chakassien" localisation UI Error

### ISSUE THREAD

**Issue by epe** [osmandapp/Osmand#1597]
No matter if I choose german or english as UI language, half the countries in the Europe offline MAP download list are showing up as "Chakassien" 
See a screenshot here: https://twitter.com/ericepe/status/636197279792300032

<blockquote class="twitter-tweet" lang="de"><p lang="en" dir="ltr">What happened to the <a href="https://twitter.com/hashtag/osmand?src=hash">#osmand</a> download section. Doesn&#39;t seem to be a localisation issue, affects en &amp; de interface. <a href="http://t.co/hczO69duCS">pic.twitter.com/hczO69duCS</a></p>&mdash; epe (@ericepe) <a href="https://twitter.com/ericepe/status/636197279792300032">25. August 2015</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by epe** [comment]
If I chose english UI language, it shows Khakassia instead of Chakassien. doeasnt help a bit. How can I find the right country to download?

**Comment by vshcherb** [comment]
Please check that issue it seems that it not reproducible right now. We suspect that it happens occasionally bug goes away indeterministic.

**Comment by epe** [comment]
ok... I managed to solve this somehow: 
rename osmand/ folder to osmand.bak 
restart osmand  and quit.
from the newly created osmand/ folder copy the fresh regions.ocbf file over to osmand.bak folder and rename osmand.bak to osmand (of course delete that new osmand folder first). 
then it works again. probably my regions.ocbf file was still from the old osmand or corrupted.

**Comment by vshcherb** [comment]
We saw that issue once on a test device, however it was solved just by restarting OsmAnd, so we don't really know where the issue exactly. Let's see if we can find more details later, for now this bug is not directly actionable.

**Comment by cfi** [comment]
Same here. Workaround fixed it.

OsmAnd+ 2.1.1 2015-06-20 installed.

Corner case in my case: Profile and cards stored on /mnt/external1 (microsd card) which broke half a year ago: Still readable with all data, but not writable.

Could fix the issue today because of inserting a new card.

I wouldn't waste development effort to fix this, if it keeps being the odd corner case. Just wanted to add some data to this ticket.

**Comment by martinsauter** [comment]
Thanks, your workaround with the fresh regions.ocbf file fixed it for me as well!
