### ISSUE TITLE
Flickering POI icons and street names

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#15983]
Sometimes POI icons and street names disappear and reappear while standing still. In the following example this happens for the fast food icon and for the street name in the upper left corner, see the video

https://user-images.githubusercontent.com/1040784/207884141-4ac2faeb-180b-4b1a-9370-74d0098ea6fc.mp4

![photo_2022-12-15_15-16-33](https://user-images.githubusercontent.com/1040784/207890086-d8ee7cd8-1cc2-472f-b10f-b8e902ef38b3.jpg)

OsmAnd 4.3.3, OpenGL enabled. Not sure if this already happened with 4.2.x and enabled OpenGL. I'm pretty sure it didn't happen before without OpenGL.

Why is there a need to constantly redraw the map, even when there is (almost) no movement? I thought the map is drawn with a buffer around the current view and only needs to be redrawn if there is significant movement or rotation.

**Comment by scaidermern** [comment]
Could be related to #15068?

**Comment by scaidermern** [comment]
Another example from a different user:

https://user-images.githubusercontent.com/1040784/207895710-7779e303-590a-489a-a756-d0743bef50e4.mp4

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14031mqta, released: 2022-12-18
Not reproduced


https://user-images.githubusercontent.com/104760013/208304552-a0e58124-69ab-4217-80fb-d5a15cd7bd4f.mp4

**Comment by vshcherb** [comment]
Let's see if manage to reproduce it and then fix obviously, standing still should be no flickering.

**Comment by pordini** [comment]
Seems very similar so I'll put this here instead of opening a new issue. If a new one is preferred, let me know.

There is flickering of the motorway icons above a certain speed. Also seen it happen with street names but those I did not record.


https://github.com/osmandapp/OsmAnd/assets/12774050/0125d8e9-f743-472c-bf8f-6e1ec0d64f96

**Comment by vshcherb** [comment]
Actually original issue was fixed in 4.3, so it's worth to have separate issue then.
