### ISSUE TITLE
Make tracks 'collapsible'

### ISSUE THREAD

**Issue by tradavyvy** [osmandapp/OsmAnd#15989]
Is it possible to make (active) tracks collapsible, so that all that is visible on te map is an icon marker like the favorites?
Maybe set these collapsed tracks appart bij making the icon shape into an upside down droplet shape.
Put the icon at the start of the track and only render the track when the icon is long pressed, and hide/collapse the track again when te start icon is long pressed.
This might help keep the map unclutterred and still have an overview of available tracks.
This might also help aleviate rendering speed problems like #15968 and others.

**Comment by vshcherb** [comment]
Interesting idea actually

**Comment by dmpr0** [comment]
My Places Tracks has new UI
