### ISSUE TITLE
Sunrise/Sunset widget doesn't use string recourses for hours

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#15985]
it seems that **Sunrise/Sunset** widget doesn't use strings` <string name="int_hour">t</string>` https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/res/values-da/strings.xml/#L1257

<img src="https://user-images.githubusercontent.com/9365308/207895378-004d09ba-e4b4-4934-897d-1adc2b4b0ac5.png"  width="300" height="auto"/>

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14050mqta, released: 2022-12-27
Done - Danish language


https://user-images.githubusercontent.com/104760013/209658631-6b995641-0df0-480e-a93d-3687f4b6926e.mp4
