### ISSUE TITLE
Crashes java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Canvas.rotate...

### ISSUE THREAD

**Issue by mdykierek** [osmandapp/OsmAnd#15987]
I got 4 crashes with 4.3.2 and 4.3.3 when using Android Auto (but I use it most of the time recently) when Granting access to location on car's display.

### How to reproduce?
I had route calculated on the phone. Connected to car's usb (AA) and when Granted access to car's display it remained black. When looked at the phone crash dialog appeared.
Note that the time reported in exception log seems to be missing AM/PM or is off by 12 hours (the last crash was at 17:44 not 5:44)

### Your Environment
OsmAnd Version: OsmAnd+ 4.3.2 and 4.3.3
Android/iOS version: Android 11
Device model: Mi 9T Pro

**Maps used (online or offline):**   
Offline
[exception.log](https://github.com/osmandapp/OsmAnd/files/10239785/exception.log)

**Comment by Zirochkabila** [comment]
@mdykierek Is this related to this issue [15965](https://github.com/osmandapp/OsmAnd/issues/15965)

**Comment by Chumva** [comment]
This should be fixed here https://github.com/osmandapp/OsmAnd/commit/d1182cab2041e3911cc3ee5ea64929f7c65fa27f
