### ISSUE TITLE
Unexpected keep left and then keep back right to same road

### ISSUE THREAD

**Issue by tbicr** [osmandapp/Osmand#1599]
http://osm.org/go/ZeX3jDwOL?m=

![screenshot_2015-08-25-22-23-23](https://cloud.githubusercontent.com/assets/416731/9484383/4caa64bc-4b79-11e5-9a14-503019ad1120.png)

**Comment by vshcherb** [comment]
It doesn't seem to be an issue, it says that you should take 2 left lanes and do not take right lane, may be it is obvious when you drive, but it is not obvious when I look at the map.

**Comment by tbicr** [comment]
http://binged.it/1El2XD1

There are 3 lines - left should turn left, forward, right. When osmand tell to keep left I take to left line.

**Comment by vshcherb** [comment]
Indeed that's an issue, but i would still recommend fixing the map data.
The road should have turn:lanes="left|straight|right" defined in that case OsmAnd will show correctly turns and recommend to stay on the middle lane.
