### ISSUE TITLE
Moutains are flat in 2.5D (Android 9)

### ISSUE THREAD

**Issue by arncor** [osmandapp/OsmAnd#15991]
### Description
Basically the title.
I found the following screenshot on osmand website where the terrain topography gets rendered in 3D when using 2.5D
![Screenshot_20221215-231651_1.png](https://user-images.githubusercontent.com/91597340/207979670-7864ab1b-86b7-48fd-9367-1de2c3d5b6dc.png)

On my phone, moutains are flat:
![Screenshot_20221215-231539.png](https://user-images.githubusercontent.com/91597340/207979739-c0e99025-ef66-4c95-a40d-afe076ff83a5.png)

### Your Environment
OsmAnd Version:4.3.3
Android/iOS version:9
Device model:ulefone armor 6e

**Maps used (online or offline):**   
Offroad, ski

**Comment by scaidermern** [comment]
3D rendering of terrain is only available under the following CONDITIONS as far as I know:
- OsmAnd Pro
- separate height map for your area downloaded (currently they are not available for all countries I think) 
- height map enabled (Plugins / OsmAnd development / settings / height map)

**Comment by arncor** [comment]
I haven't found anything about heightmap in pro features on OsmAnd website, but you're right, in the dev settings, when I try to enable it, it says osmand pro is needed for "pro features" (duh), without further precision.
Thanks for your answer

**Comment by scaidermern** [comment]
> I haven't found anything about heightmap in pro features on OsmAnd website

I guess this is because it is not an official feature yet.

The screenshot is rather unfortunate and suggests that this feature is ready and available. Which isn't really the case.

**Comment by pebogufi** [comment]
Is heightmap useful withOUT 2.5D?
I don't see it.
What about switching heightmap automatically off if 2.5D is switched off and switch it on if (it was on before) when switching 2.5D to on.
...
There are 3 options which are close together:
OpenGl, 2.5D, heightmap.
These options are at very different positions in menus to find.
Please positon them close together.

**Comment by mikehgentry** [comment]
I assume (although I don't know) the heightmap is also used for the altitude widget?

I'm not seeing 3D rendering of terrain either, on Android 11, 4.3.4 Pro/+, with heightmap downloaded and enabled, OpenGL on. Not sure what I'm missing.

**Comment by vshcherb** [comment]
Yes elevation widget only works if heightmap is enabled

**Comment by letypequividelespoubelles** [comment]
To have the 3D view (not available everywhere) : https://github.com/osmandapp/OsmAnd/issues/11204#issuecomment-1368320194

**Comment by mikehgentry** [comment]
Hmm, interestingly I downloaded Normandy and the heightmap for France and it works there, just doesn't seem to work in the UK (well, England, the only UK nation it seems to be built for so far).

Will assume it's a teething issue, see whether it springs to life next time the maps are rebuilt, and if not file a bug.

**Comment by michaelblyons** [comment]
Good news: Height maps can be downloaded for USA now! 🎉
Bad news: All the height maps are 0.00MB. 😅

**Comment by vshcherb** [comment]
Going to generate it with new format, please download the nightly

**Comment by vshcherb** [comment]
Please test latest 4.4 beta where we have all countries download and new format

**Comment by mikehgentry** [comment]
Can confirm this is working (for me at least) on the 4.4 beta.

Thanks!
