### ISSUE TITLE
OpenGL hillshades rendered with false transparency

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#15996]
Our default transparency setting for the hillshade layer is 22%, and that value is also displayed under `Configure map > Terrain > Transparancy` both when using the Version 1 or Version 2 renderer. But Version 2 seems to actually display the layer much more pale, compare these 2 screenshots:

Version 1, correct:
![Screenshot_20221216-082758_OsmAnd~](https://user-images.githubusercontent.com/845735/208047262-e1251c38-aed0-47b2-bad0-3e5414b36e40.jpg)

Version 2, too pale:
![Screenshot_20221216-082742_OsmAnd~](https://user-images.githubusercontent.com/845735/208047379-a603d9e0-a637-460a-bbe3-a07d646a6bd1.jpg)

This is with master build, not sure if fixes were already applied to branch r4.3.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14031mqta, released: 2022-12-18
Reproduced
With the same percentage of transparency, the shades of the hills are lighter with OpenGL


https://user-images.githubusercontent.com/104760013/208304969-bbefb9bc-825e-488a-8c01-b4c7c10ed629.mp4

**Comment by sonora** [comment]
Can I please suggest we keep the de facto degree of shading of the v1 engine, as it is well tested, and adjust the v2 engine's default degree of shading accordingly (and not the other way round).

**Comment by Andrewschenko** [comment]
It looks like Version 2 (not Vesion 1) of renderer shows hillshades correct:
![compare](https://user-images.githubusercontent.com/108512964/212059177-82c379f1-1e50-409f-8d95-91cd3a6a23ae.jpg)

**Comment by sonora** [comment]
I guess the task is
- to align the two behaviors,
- and then set the default such that the optical appearance remains that of today's "Version 1 22% setting", because that's thoroughly tested and has been in place for years without complaints.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14108mqta, released: 2023-01-17
Behavior hasn't changed


https://user-images.githubusercontent.com/104760013/212966141-f4397f82-b6de-4cd2-831e-d2a88bf54678.mp4

**Comment by sonora** [comment]
From what I see, it''s fixed ok, the appearance is identical now in both engines?

**Comment by Zirochkabila** [comment]
No, map is lighter on V1

**Comment by sonora** [comment]
Can you post 2 screenshots of them same area, rather than a video? And ,make sure the value of the transparency slider is the same for both?

**Comment by sonora** [comment]
Here are my screenshots with the new versions, first one using V1, second V2. The hillshade tinting looks identical. (Note that our default transparency setting has now changed to 39%, consistent in both engines, due to the .255 factor glitch correctly discovered in @Andrewschenko 's fix.)

![Screenshot_20230118-095519_OsmAnd~](https://user-images.githubusercontent.com/845735/213127917-da9dd68e-4e88-47bc-960b-9d5d50d933c9.jpg) ![Screenshot_20230118-095544_OsmAnd~](https://user-images.githubusercontent.com/845735/213127958-b76383b7-4942-48b6-8d55-8a0f6c2dc228.jpg)
