### ISSUE TITLE
Add to the settings the choice of the position of the map transparency slider. The misclick problem

### ISSUE THREAD

**Issue by snooppr** [osmandapp/OsmAnd#15994]
First, thanks for the functionality of the slider.

I actively use the slider to instantly view various layers, usually satellite images and local maps.  But the slider has an unfortunate position on the screen. The problem is that it is located in the most intense area of ​​the finger that is always moving the card, and it constantly false positives.  Instead of moving around the map, the slider works.

Please add the ability to select the location of the slider at the discretion of the user.
If it is not possible, then move the slider to the horizontal scale of the ruler, combine.

![osmand](https://user-images.githubusercontent.com/61022210/208034475-789089fb-f6c1-4a89-a5f5-83de63cc393e.jpg)

**Comment by arncor** [comment]
I get that problem too sometimes.

**Comment by Rowin63** [comment]
This is already a "nice to have" #13359
