### ISSUE TITLE
Add self_checkout to custom filters

### ISSUE THREAD

**Issue by The-Nickname** [osmandapp/OsmAnd#16005]
# 🚀 feature request

### Description

Hi there,

It would be cool to have a filter for self_checkout in the custom filters.
https://wiki.openstreetmap.org/wiki/Key:self_checkout
https://taginfo.openstreetmap.org/keys/self_checkout

### Describe alternatives you've considered

In addition it could be nice to have it in the POI overview(if tagged with yes). 
But since the tag seems not to be that wide spread yet and the POI overview might already be "too bloated" this doesnt seem that reasonable.

**Comment by xmd5a2** [comment]
Will be available with upcoming maps

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14217mqta, released: 2023-03-04
04.03 master
Done
Checked place https://www.openstreetmap.org/way/933708931
