### ISSUE TITLE
OpenGL - some texts crippled 

### ISSUE THREAD

**Issue by miramikes** [osmandapp/OsmAnd#16004]
Some contour values are crippled with new openGL engine.
Also some text_on_path are malformed.
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/623412/208193926-0c613387-2e96-4cd6-8199-ecc38ed5d47b.png"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/623412/208193949-d55a6795-628c-41b9-8ff5-0ed9c1b41108.png"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14031mqta, released: 2022-12-18
Not reproduced

@miramikes  Please indicate the coordinates of the location on the screenshots - perhaps the behavior can be reproduced on the screenshot's location


https://user-images.githubusercontent.com/104760013/208306025-23de1438-e40b-4f10-b1c3-e8e1807bd43f.mp4

**Comment by miramikes** [comment]
Previous screenshot were roughly on this location.
47.61961° N, 14.03257° E
Also note that I am usually using text magnified to 125%
Thank you
Mira

**Comment by ivanPyrohivskyi** [comment]
Need to move logic from legacy library:
https://github.com/osmandapp/OsmAnd-core-legacy/blob/a5e5f3b121184451f99cf79c24336988777e16a7/native/src/textdraw.cpp#L1000

Into core library:
https://github.com/osmandapp/OsmAnd-core/blob/100882956378da7bcc74521ce57c1b592bc2fba8/src/Map/AtlasMapRendererSymbolsStage.cpp#L2180

**Comment by Zirochkabila** [comment]
waiting https://github.com/osmandapp/OsmAnd/issues/16409

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14159mqta, Released: 2023-02-08
V2 rendering - Done 
V1 rendering - when zoomed in 14, height digits overlap each other

<details><summary>V1</summary>
<img width="600" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/217486557-a2f591c7-2ec4-4af1-9f70-28469a6a89e7.jpeg">
</details>


https://user-images.githubusercontent.com/104760013/217486779-ddb38597-cdfb-43f6-8e0d-6ee4e4931687.mp4

**Comment by dmpr0** [comment]
### Review
There is some distorsion on zero digit for black text.

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/218442876-0c5fbd32-d294-44b2-b620-1f786a609d96.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/218442880-011b5695-f1f3-4256-9081-e3619fe9a8da.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/218442884-635ee53f-5aa7-48b1-9038-0b9a9c542e59.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14204mqta, Released: 2023-02-26
26.02 master
Done

**Comment by dmpr0** [comment]
## Review 2
I didn't see it previous time, but see now. Text in Version 2 (OpenGL) has some visible distortion on top and bottom of symbols.




<table style="width:100%">
  <tr>
    <th colspan=2>Version 1</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/224335231-42c9b69a-0793-4ec4-803f-d7350244585c.png"  width="720" height="auto"/></td>
  </tr>
  <tr>
    <th colspan=2>Version 2</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/224335221-1b2b811b-9467-4715-9f2d-bd9ff41a184c.png"  width="720" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
Less visible another issue could be opened. OpenGL text is not the same as Canvas it's rendered via 3D and is not flat

**Comment by dmpr0** [comment]
@vshcherb As a user I don't care how text is rendered on canvas or OpenGL, it starts to look crippled and distorted.
