### ISSUE TITLE
Water/seashore line is not rendered correctly at certain zoom-in levels

### ISSUE THREAD

**Issue by orientrun** [osmandapp/OsmAnd#16003]
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/111636669/208167353-c8d4d3f7-878b-49c5-acab-84e620a86e0d.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Description
Water/seashore line is not rendered correctly at certain zoom-in levels.
### How to reproduce?
Open the latest map of Greece, go to Thessaloniki, focus on any place near the seashore and zoom-in.
Might be related to #15124?
### Your Environment
OsmAnd Version: 4.3.2
Android/iOS version: 12
Device model: Pixel 3a
**Maps used (online or offline):**   
Greece (Dec 22)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14031mqta, released: 2022-12-18
Not reproduced


https://user-images.githubusercontent.com/104760013/208305744-e34af66d-02d0-4e09-ad81-d794cf695971.mp4

**Comment by vshcherb** [comment]
Probably maps needs to be updated
