### ISSUE TITLE
OpenGL rendering issues (missing lots of map information)

### ISSUE THREAD

**Issue by traits** [osmandapp/OsmAnd#16008]
### Description

After rolling out the OpenGL engine as default, the following is what I get for the city of Dresden (old engine left, OpenGL right). Zooming in, almost all information is missing: water bodies, buildings, street names and more.

<img src="https://user-images.githubusercontent.com/4024583/208324799-e58439af-b9a4-490d-b75e-8e2f74273b40.jpg" alt="Old Engine" width="300"><img src="https://user-images.githubusercontent.com/4024583/208324805-2814058d-c0d5-4d96-bab6-c5215ac7bd3f.jpg" alt="OpenGL" width="300">

Edit: For my Moto One (same configuration, offline vector maps), the complete map is missing (only an empty grid is shown) if the OpenGL renderer is active.

### How to reproduce?
Switch rendering engines in settings

### Your Environment
OsmAnd Version: 4.3.3
Android version: 12
Device model: Lenovo Yoga Tab 11 YT-J706F

**Maps used (online or offline):**   
Standard Maps Saxony (Vector) + Contour Lines

**Comment by vshcherb** [comment]
Please switch to Rendering Engine v1, it looks like there are serious issues installation or maps issue or some corruption. We will try to reproduce but it looks very strange.

**Comment by traits** [comment]
The update to 4.3.4 solved the problem (but not any reboot before and also no redownload of the map, shown above)
