### ISSUE TITLE
POI icons are below route line during navigation 

### ISSUE THREAD

**Issue by arncor** [osmandapp/OsmAnd#16009]
### Description
Maybe it's has been solved already with #15969

POI icons are below the route line.
(radars icons in my case)
Iny opinion, route line should be above every line and polygon, but below everything else (point, town names, POI icons, road badges, etc)

![Screenshot_20221218-133758.png](https://user-images.githubusercontent.com/91597340/208385262-6ff2736b-2a9d-46df-bc4a-95c67d58d7bc.png)

### Your Environment
OsmAnd Version: 4.3.3
Android/iOS version:9
Device model:armor ulefone 6e

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by Zirochkabila** [comment]
Merge to [15969](https://github.com/osmandapp/OsmAnd/issues/15969)
