### ISSUE TITLE
What is the technical reason why there's no offline legend?

### ISSUE THREAD

**Issue by fabeit** [osmandapp/OsmAnd#16010]
I know already of all the many threads asking for an offline legend. But I haven't seen to this day a serious technical explanation why we cannot store a few megabytes to provide an offline legend. It does not have to be complicated or dynamic so I don't understand why and I would like a technical answer for it. Phones have Gb of storage.

The point of off-line maps is to use them when you have little or no for reception and a few times I had to make routing decisions in remote areas and did not remember the meaning of all features, not being able to completely understand and read a map is also a safety issue.

**Comment by sonora** [comment]
It works for me ... just go to `Menu / Help / Map legend` once while online, after that it's chached and available on your device offline.

**Comment by tradavyvy** [comment]
It would be even better if (in addition to an off line legenda) the legenda info would be displayed when you long-touch a certain area or road or icon.
For instance in the same 'pull up page' that also give you the coordinates (and photo's) of that location.

And while you are at it why not add the elevation info of that spot there to.

**Comment by EugeneZmeuk** [comment]
https://github.com/osmandapp/OsmAnd/discussions/12959
Map legend Plugin

**Comment by fabeit** [comment]
@EugeneZmeuk I have seen that, but I would like a technical answer from the developers as to why such a small image cannot be included?

**Comment by sonora** [comment]
I am not saying I speak for everybody here, but I guess that part of the answer may be:
- **Use case:** The legend is not a mainstream feature, only a (really) small fraction of all OsmAnd users has ever cared about a map legend.
- **Automatic availability:** If you are a "legend user" and have once used the legend while online, it is automatically downloaded and present on your device anyway (similar to the maps: you download only the ones you actually have a use for).
- **Applicability:** We have many different map styles, so eventually a complete feature requires a corresponding number of legends with each applicable only to some users, a blanket download concept sounds like waste.
- **Sustainability:** Last not least, there are regions in the world where bandwidth is really extremely precious. We should avoid using _everybody's_ volume on niche features.

**Comment by fabeit** [comment]
@sonora Thanks for sharing your point of view. I don't necessarily agree with all your points.

- A legend is an integral part of a map, it's like trying to read without knowing the alphabet. OsmAnd users are not your regular users given the steep learning curve and features.
- When you might need a legend it could be when you have no access to a connection, and trying to remember to download it before hand it's not a foolproof design
- At least we could include the default osm style legend, don't need to include all of them
- The size of the osmand app and the offline maps are negligible compared to a couple of Mb. I am just wondering if you have been to any of these regions you are mentioning. Because you might be surprised to know that some of the poorest countries are the biggest data users, some places you can buy a 10 Gb per day subscription. And if you are really in a remote place I doubt you would download osmand.  

Sorry but I still don't see any real technical reason and I would like to hear from the developers.

**Comment by tradavyvy** [comment]
Maybe the data-size problem and the different renderstyles problem would be adressed by giving the information about 'what is this-what is here-what is this road like' after a long touch.
Becourse this info is already in the map data and is not dependent on the rendering style. Even showing only the 'rough' map data labels would be a help. 
Showing a smal example in the current rendering style and a discription would ofcourse be more slick.
But I agree with Fabeit,
A map is only as good as the abillity to read it.
And some form legend is definitely not frige-use even if most people do not use it.
If the use argument was leading manny of Osmand's wonderfull features would be doomed.
Or we could all start using that other app from big G. and I for  one would realy regret that ;))

**Comment by vshcherb** [comment]
Data is an issue and images is an issue, we're preparing new docs / legend -https://docs.osmand.net/docs/user/map-legend/osmand. We're going to make it available to full download docs - around 200-250MB, or possibly download with SVG -  30 -40MB. New legend will be purely svg.

**Comment by fabeit** [comment]
@vshcherb thank you for the response, why are images an issue? I don't understand how an SVG image can be so large when one of the main advantages of SVG is the small file size.

How can data be a problem when people download gigabytes of data each day? We are not using 56k modems...

**Comment by vshcherb** [comment]
Here is the first icons in SVG in the legend https://docs.osmand.net/docs/user/map-legend/osmand/#emergency-health. 

Obviously the most difficult is to provide common technical solution, we need to provide full (almost) automated way to update legend and make it offline and we also want to make documentation generic offline to  deal with other similar issues in a similar way.

**Comment by sonora** [comment]
There may be comparatively little return of invest to implement and maintain a legend for e.g. POI icons: In times where you can tap on such an icon and see its type directly in OsmAnd, few people may bother to go through a "paper style", old school separate legend for this, be it offline or even online.

I suggest we could work on making even more features on the map tappable directly (e.h. areas and ways) and display their context card, that would make a legend instantly and entirely obsolete, for all map styles.
