### ISSUE TITLE
Osmand timeout when searching address/poi from car display on android auto

### ISSUE THREAD

**Issue by mmacura311** [osmandapp/OsmAnd#16014]
### Description
When I try to search for an address or poi on car's display, I always get a timeout error, so it makes impossible to use the app in car's system at all.

### How to reproduce?
Connect to car using android auto. Start osmand. Open search dialog and enter some string. I wanted to go to local Decathlon so I enter "decathlon". Wait for the result to appear - on the display it says there was a problem and I can wait longer or kill the app.

### Your Environment
OsmAnd Version: osmand free 4.3.3 + maps subscription
Android version: 11 (latest available for my model) 
Device model: fairphone 4 8GB

**Maps used (online or offline):**  
Not sure if this is map related (probably not). I was using Czech south-east map file dated 1.12.2022

Additional notes:
the search in app on the phone works without issue, only problem is when I use it from car. Also I can use different app on android auto and it works, so it seems that the SW in my car is OK and problem is on the app side, but obviously there might be bugs.
If needed I can provide some debugging info, logs etc, but need instructions on how to get them.

**Comment by mmacura311** [comment]
I tried also with latest osmand build 4.3.4 and it still throws a timeout.
my android auto version (in the phone) is 8.5.624594-release

Interestingly, the timeout is not caused by the "search" funtcion specifically, but is probably some more general thing. When I try to navigate to on of my "favourites", it finds the point on map immediately, no problem there. But then when I try to search for route, it again ends with the timeout message.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14059mqta, released: 2022-12-29
Waiting for the result took about 18 seconds, but the result was displayed and the route was built


https://user-images.githubusercontent.com/104760013/209929226-684b6b8d-56e8-4783-8e7b-150e02fd1d7c.mov

**Comment by mmacura311** [comment]
I tried again with 4.3.5 (not sure if any fixes for this were included in the build) and it still happens. I will try to record video soon.

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/16158
