### ISSUE TITLE
Problem with names with zero-width non-joiner (ZWNJ) character

### ISSUE THREAD

**Issue by Ahmadhosseinbor** [osmandapp/OsmAnd#16011]
### Description
The zero-width non-joiner (ZWNJ) character is not rendered in OpenGl

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/44550501/208396457-d377caac-af96-4645-844f-ea6db2157a20.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Your Environment
OsmAnd Version: 4.3.3
Android/iOS version: 13
Device model: A32

**Maps used (online or offline):**   
offline

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-core/commits?author=Andrewschenko
