### ISSUE TITLE
OpenGL: Text labeling differences between v1 and v2 rendering engines

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#16013]
Carryover from https://github.com/osmandapp/OsmAnd/issues/15980#issuecomment-1353180971:

Do we have an issue to systematically collect shortfalls or differences between v1 and v2 rendering?

Here is a small comparison which e.g. shows that in v2
- there seems a surplus extra line between a mountain peak icon and its label,
- or there seem contour line labels not visible in v1 in that magnification.

<img width="878" alt="v1" src="https://user-images.githubusercontent.com/845735/207885885-2be79327-d393-4f5b-8ba4-e5c55f4daca3.png">
<img width="827" alt="v2" src="https://user-images.githubusercontent.com/845735/207885928-17fadebb-937b-467e-8aed-94f2b09595cc.png">

**Comment by Zirochkabila** [comment]
Merge to [16004](https://github.com/osmandapp/OsmAnd/issues/16004)
