### ISSUE TITLE
Notification settings from "OsmAnd Contour lines"

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#16016]
### Description

When switching the notification settings to "off", the app itself always immediately switches it back to "on". When I don't use the app I don't want to receive any notifications from it.

![image](https://user-images.githubusercontent.com/44466116/208644301-b94749ca-053f-4afd-9d44-335dcaaf403a.png)

![image](https://user-images.githubusercontent.com/44466116/208644334-3293d57d-f9b2-45ec-b3fb-f4a93f6fbae8.png)

![image](https://user-images.githubusercontent.com/44466116/208644375-b836bfa1-db91-4b62-b28f-b418c462ac90.png)

### Your Environment

Osm-app version 4.3.3, plug-in version 1.0, Android 13.

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by vshcherb** [comment]
this is an old api plugin so it's  a duplicate issue to upgrade plugin
