### ISSUE TITLE
Search for capacity:charging

### ISSUE THREAD

**Issue by ways** [osmandapp/OsmAnd#16018]
Hi

The app allows searching for charging stations or searching for parking. But I can't find any way to search for parking garages that have charging.

In Norway lots of parking garages have free 22 kWh chargers now, so this is kind of a big deal.

A search for any POI with the amenity capacity:charging would solve this. Is there any way to do this already?

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14159mqta, Released: 2023-02-08
Done
[Map](https://drive.google.com/file/d/12VRxDzcRIxRqBBYTkp3rpuKKs_lflIRz/view?usp=sharing)

<details><summary>50kW</summary>
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/217508677-bdac7619-84bd-42b6-a4c6-75f69cd94121.jpeg">
</details>

https://user-images.githubusercontent.com/104760013/217508711-db0efe59-7f06-412b-a7a5-21cffec93763.mp4
