### ISSUE TITLE
2.5D toggle button on map only available with  location on and navigation off

### ISSUE THREAD

**Issue by arncor** [osmandapp/OsmAnd#16026]
# 🚀 feature request

### Description
The 2.5D toggle button is very nice and handy : 
![Screenshot_20221221-155646_1.png](https://user-images.githubusercontent.com/91597340/208938266-c7d01612-3f2f-4e3c-9d36-90ad66f4f3c1.png)
But it's only available when location is on and not during navigation.

### Describe the solution you'd like
Either separate this button from the location button, or make it available during navigation at least.

### Describe alternatives you've considered
Using a 2-finger swipe while driving is unreliable, unpracticle and can be dangerous.

**Comment by mmacura311** [comment]
+1
If I do not switch to 2.5D mode prior navigation and the "car" mode is not switched to 2.5D, then it is navigating in top view and there is no way to change that. I need to stop navigation, change the view, start navigation again.

**Comment by arncor** [comment]
Yes, or you can use the 2-finger swipe, which is pretty difficult while driving (especially on the motorcycle)...

**Comment by dmpr0** [comment]
Slightly similar to https://github.com/osmandapp/OsmAnd/issues/15479. In both cases bottom buttons is hiding while navigation

**Comment by vshcherb** [comment]
Setting would be required cause some other scenarios possible:
1. Show/not show button always on screen
2. 2.5D or 3D enable (so we don't to draw 3D maps in flat mode)

**Comment by dmpr0** [comment]
# ToDo
## Button

<table style="width:100%">
  <tr>
    <th>Configure Screen</th>
    <th>3D Mode – Bottom sheet</th>
    <th>Map – 2D</th>
    <th>Map – 3D</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/233360976-7fa9e67e-fee1-4ee2-98e7-1ddf049cd455.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/233360982-4bf300a4-5b86-4ce8-a702-b7a6441cfd56.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/233360945-9f8fd284-5e59-4674-a0c9-f991dc87f4cb.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/233360965-751378a5-6e0f-4c3a-873c-1b931ca718b3.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by dmpr0** [comment]
# Review
- [ ]  Hide if all related to button if **Map rendering engine** is set to **Version 1**

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#96m, Released: 2023-05-26

- [ ] Button does not respond if the 3D status is displayed (if switched the map to 3D manual mode, 2D is displayed and the button starts working)

https://github.com/osmandapp/OsmAnd/assets/104760013/ebd42103-4215-4827-bf2a-3fd17b3bff43

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/widgets/map-buttons#3d-mode
https://osmand.net/docs/user/personal/global-settings/#map-rendering-engine
