### ISSUE TITLE
Reduce 2.5D tilt angle at low zoom levels

### ISSUE THREAD

**Issue by arncor** [osmandapp/OsmAnd#16027]
### Description
2.5D is finally there, thank you for the hard work. 
In order to make it more usable and mature, I believe this 2.5D gets less and less useful at low zoom levels.

### Describe the solution you'd like
I suggest to gradually reduce tilt angle when zooming out, depending on the zoom level.

This could be in the form of an option in the 2.5D on/off section:
"gradually reduce tilt angle when zooming out
Starting at zoom [10 ; 11 ; 12 ; 13 ; 14 or whatever]"

**Comment by vshcherb** [comment]
We also need to align iOS / Android angles

**Comment by dmpr0** [comment]
Additional request is to remember the angle set by user, especially while navigation, because taping on **My location** button, changes it to default.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/blob/ed843170e8e50f1c102da5ce46cfbdd0fc3fa992/OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java#L1281

**Comment by vshcherb** [comment]
- [ ] Remove code getMinAllowedElevationAngle keep just constant 10
- [ ] We need gradually reduce angle while clicking zoom out -  Zoom 17 - 15 deg, Zoom 15 - 25 deg, Zoom 13 - 35 deg, Zoom 11 - 45 deg, Zoom 9 - 55 deg, ...
- [ ] Zoom should change higher / lower back if you zoom in/out back
- [ ] If user changes angle with fingers it should be kept across all zooms
- [ ] After restart: click 3D should use "default angle" - so user fine-tuned angle with gestures will be kept only in App session

**Comment by vshcherb** [comment]
- [ ] Create task for IOS
- [ ] Create task for smooth OpenGl
