### ISSUE TITLE
Add category "water"

### ISSUE THREAD

**Issue by snooppr** [osmandapp/OsmAnd#16021]
In osmand search, you can search by category, such as "food", "products", but there is no category for "water".
Add to osmand a preset category in the search "water": the category water should include the tags:: (amenity, drinking_water);  (man_made, water_well);  (natural, spring).  Drinking water;  wells and springs.

**Rationale**
1. I and some users know that in osmand you can create any custom category, for example "water" and add any objects to it, not just "drinking water".  But according to my data, most users do not know how to use this and how to create their own filter (it is well known that the osmand interface is overloaded), which means that the user may prefer to use alternative applications, such as organicmaps. 
In the alternative organic maps application, it is enough to write "water" in the search and not only springs, but also water columns and wells will appear on the map.
2. It is well known that osmand in nature (cards outside the city) is unrivaled, that is, very cool, so all activists on hikes, on bicycles, etc.  it is required to search for "water" in the search, but they do not get all the options: what they are looking for is easy to fix: by adding a predefined category to the search that contains the maximum number of sources of drinking water (wells and springs ...).
3. In some single-industry towns and villages, there are no "drinking water" tags on the OSM maps; instead, the "wells" tags are indicated on the maps.  Therefore, an active user, when looking for drinking water, will not find anything where he can get water.  Because he is a user and cannot know all the nuances about OSM maps.

Thus, I believe that in the preset search categories there are extra categories, and the category "water", one of the most important ones, is missing.  Developers simply have to add it in the next versions of the software.

**Comment by tradavyvy** [comment]
Good idea.
I noticed that (in the dutch version) there are 2 almost identical poi cattegories 
-(fast)food (eten)
-cafe en restaurant.
In the food category wells are displayed, but no drinkwater taps as far as I can see
I would not look for drinking water in a fastfood or restaurant category.
So why not make the 2 almost identical categories into one and make a seperate one for all drinkingwater points

![Screenshot_20221223-025702_OsmAnd+](https://user-images.githubusercontent.com/71978409/209256513-8ae89a51-7dcc-49e7-bfac-c4a958743b9a.jpg)

(By the way I have been in one or two places, in India I think, where an enthousiastic mapper mapped all the wells and they drowned out the few mapped restaurants in the area. Great if you are thirsty, less so if you are hungry)

**Comment by snooppr** [comment]
Yes, here is a close-minded example of the problem firsthand

![w](https://user-images.githubusercontent.com/61022210/209292750-99dcea2d-2c2a-41aa-b8e8-f70552638d90.jpeg)
On the left is the search for drinking water, and on the right is the search for wells.

In this locality, all the water on the openstreetmap maps is not correctly tagged, what is tagged with wells is actually "drinking water" [water columns](https://yandex.ru/images/search?text=%D0%92%D0%BE%D0%B4%D0%BE%D1%80%D0%B0%D0%B7%D0%B1%D0%BE%D1%80%D0%BD%D0%B0%D1%8B%D0%B5%20%D0%BA%D0%BE%D0%BB%D0%BE%D0%BD%D0%BA%D0%B8&from=tabbar), painfully known to the founders of the osmand developers.

Actually, the data error from OSM maps is not that important, it's a big problem with the osmand application.
Combining the categories (sources of water) with the tags listed in the first post into a new category "water" solves the problem for newbie users who can't create their custom search filter.

The problem is so obvious and so easy to solve that yes, I have been at a loss for the application for many years ...

**Comment by snooppr** [comment]
> [vshcherb](https://github.com/vshcherb) removed this from the [4.4-backend](https://github.com/osmandapp/OsmAnd/milestone/32) milestone

I've outlined a problem regarding osmand newbie users.  I've outlined the issue as to who is in the top 500 OSM mappers.  I have identified a problem regarding who goes hiking in practice.  But it seems there is something else the boss's unwillingness...

@snooppr  added this to the **[4.4-backend](https://github.com/osmandapp/OsmAnd/milestone/32) milestone**

**Comment by vshcherb** [comment]
You can create a custom filter and share it's as an extension, OsmAnd supports custom POI searches.

**Comment by snooppr** [comment]
> You can create a custom filter and share it's as an extension, OsmAnd supports custom POI searches.

I know this, I even wrote about it in detail in paragraph 1 (at the beginning). I provided redundant evidence in txt and image that "water" with all drinking sources should be pre-assigned as a category.

**Comment by snooppr** [comment]
Я переду на русский язык, так как разработчики его понимают, чтобы исключить неточности перевода.

Ради усиления демонстрации этой проблемы я установил приложение streetcomplete и отредактировал poi "питьевая вода". Смотрите, что предлагает streetcomplete при уточнении какой именно объект питьевой воды здесь присутствует на карте?. Я выбрал "ручная помпа" то есть, известная, как водозаборная, упомянутая выше [колонка](https://yandex.ru/images/touch/search?text=%D1%83%D0%BB%D0%B8%D1%87%D0%BD%D0%B0%D1%8F%20%D0%BA%D0%BE%D0%BB%D0%BE%D0%BD%D0%BA%D0%B0%20%D0%B4%D0%BB%D1%8F%20%D0%B2%D0%BE%D0%B4%D1%8B%20&)  .
После обновления карты данная poi отображается на osmand, как "колодец". 
При поиске "питьевая вода" пользователь никогда не найдет "колодец". Таким образом все, кто обновляет объекты питьевой воды, например, в streetcomplete, не подозревает, что в OsmAnd будут проблемы.

![колонка-кододец](https://user-images.githubusercontent.com/61022210/221391660-f9ff7629-8f9b-4b81-8508-859f66de444e.jpg)

Для проверки используйте, например, эту локацию в радиусе 500 метров: 55.87126 41.76720
используйте в поиске: "питьевая вода", "колодец", "родник" и наблюдайте за печальными результатами поиска. 

Напомню, выше приложил скрин от карт OrganicMaps, этой же местности, этой проблемы в тех картах, тоже osm - нет. Потому что они объединили poi, и при поиске "вода"  отображают "колодцы", "питьевая вода", "родник", т.е. тэги, обозначенные мной в первом посте этой issue. 

Я не понимаю, как руководитель проекта [соглашается](https://github.com/osmandapp/OsmAnd/issues/16442#issuecomment-1436695531)  объединить poi "сотовые вышки" и "антенна", но не понимает ту же смежную проблему с водой. А вода нужна ВСЕМ активистам, кто использует карты за городом. 
Пользователь не знает об особенностях карт osm, он и не должен знать, и тем более настраивать поисковый фильтр на основе этой информации. Все, что ему требуется это в поиске набрать: "питьевая вода" и получить результаты со всеми источниками питьевой воды, а не только водоз.колонок. Если пользователю требуется найти только родники, то в поиске он наберет "родник".

@Zirochkabila можете ли вы проверить предложенную информацию и донести до вашего лидера очевидное улучшение?

**Добавить в предустановленную категорию поиска "Питьевая вода" результат с тэгами: (amenity, drinking_water); (man_made, water_well); (natural, spring).**

**Comment by vshcherb** [comment]
If we add top-level category "water", it could help to combine all water providers

**Comment by xmd5a2** [comment]
Category added but this issue needs to be fixed first: https://github.com/osmandapp/OsmAnd-Issues/issues/1910

**Comment by Glebzilla** [comment]
Hello!
I'd like to notice that i can't find
```
amenity=vending_machine
vending=water
```
when i'm searching "вода"

**Comment by micronull** [comment]
Написал [небольшую статью](https://www.openstreetmap.org/user/SGorskiy/diary/401884) про поиск воды в Organic Maps и OsmAnd.

**Comment by snooppr** [comment]
> Написал [небольшую статью](https://www.openstreetmap.org/user/SGorskiy/diary/401884) про поиск воды в Organic Maps и OsmAnd.

Позвольте внести некоторые замечания по вашей публикации здесь в комментариях.

> Чтоб была возможность множественного выбора, необходимо нажать кнопку с галочками в нижнем-левом углу.

Этот метод не работает, если пользователь до этого не искал по отдельности объекты питьевой воды, т.е. в списках для чекбокса они отсутствуют по дефолту.
Более прагматичный вариант поиска:
нажать поиск (лупу) - категории - настраиваемый поиск (выбрать объекты пит.воды и сохранить)

А в версии OsmAnd 4.4.7 разработчики уже добавили предустановленную категорию "вода"


<details>
<summary>Пруфы</summary>

![скрин](https://github.com/osmandapp/OsmAnd/assets/61022210/fea44d37-9b6e-4c79-ae05-a4daf220e0da)
</details>

**Comment by micronull** [comment]
> And in version OsmAnd 4.4.7, the developers have already added a pre-installed category "water"

Thanks. I added changes to todo.

**Comment by snooppr** [comment]
And so I tested the innovation in real field conditions: I went on a multi-day bike ride and used a preset category to search for water sources.  Everything works well, and perhaps the issue should be closed.  The only note: the non-associable "water" icon in the predefined OsmAnd category is "magnifying glass".  I think it would be more correct to change the magnifying glass icon to, for example, a water droplet icon.

<details>
<summary>spoiler: photo</summary>

![14](https://github.com/osmandapp/OsmAnd/assets/61022210/1603e11b-80dd-4025-8588-71eacbaebf28)
![20](https://github.com/osmandapp/OsmAnd/assets/61022210/970a9fcf-eab9-437e-bf88-9c50e7711dc1)
![17](https://github.com/osmandapp/OsmAnd/assets/61022210/86847f41-5863-436b-b3e1-6c04671e127e)
![23](https://github.com/osmandapp/OsmAnd/assets/61022210/7ba75d17-4c22-450e-b550-a8bf05d501ef)
![25](https://github.com/osmandapp/OsmAnd/assets/61022210/d28cad23-89d7-4dac-8e44-60c9f845cebc)
![15](https://github.com/osmandapp/OsmAnd/assets/61022210/c83431f1-820f-4256-9ab4-52b8fd385f5b)
![2023-09-10-10-11-53-958](https://github.com/osmandapp/OsmAnd/assets/61022210/03da250c-62fc-4fb4-985c-7b383f1ec30f)


</details>

**Comment by DmitryAlexei** [comment]
- Proposed to change the water icon from **magnifying glass** to **water droplet**.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/08c67e06-b53f-4bcb-9138-1947ce3837f8"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by xmd5a2** [comment]
Dev notes: we need to reuse existing icon for water filter but looks like that we don't support `icon` parameter for `poi_filter` in `poi_types.xml`. Icon parameter was added in commit above but issue is not fixed.

**Comment by vshcherb** [comment]
To do: icon is missing

**Comment by dmpr0** [comment]
# Review 

<img src="https://github.com/osmandapp/OsmAnd/assets/9365308/8c35a55d-4586-4e96-8ff0-688dfd42b533"  width="300" height="auto"/> 

- [ ] Yes, Man made. 

- - - 

I propose to remove it at all there is too much categories, this should be implemented as filter in Food or as Custom category.

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/search/search-poi/#categories-poi-search

**Comment by Karsten-stgt** [comment]
Hi - I love the new POI category Water (man-made), great improvement, not only for newbies !

One question - is it possible to add also cemeteries to that category? At least for Germany, most of them (I'd guess 95%) have drinking water from tap, but in OSM this it not shown as POI "drinking water", but only as POI cemetery with no hint for water. 

I have added cemeteries since years to my custom filter for drinking water - and used it heavily on bike rides.

Might be a Germany-only issue. A better solution would probably be to map the drinking water POIs on cemeteries. But how to achieve this?

**Comment by petitminion** [comment]
It's the same in France,
A solution could be to tag cementeries poi with amenity drinking_water ?

**Comment by snooppr** [comment]
Category "water" is missing, was it removed? I reset the category "default" and there is still no category "water"??

v5.1.7 F-droid.

@yuriiurshuliak you can check the information, does the category "water" exist. If yes, delete it, and then reset the category "default" "water" will appear. Perhaps a bug with the disappearance of the category, in any case I do not have it, but I had it.
