### ISSUE TITLE
Routing - Navigation hiccup for cyclists (maybe also cars)

### ISSUE THREAD

**Issue by duiveldoder** [osmandapp/OsmAnd#16028]
See screenshot - this is a left-road-side driving country. When coming from the WNW on the screenshot, down Jalan Kolam, I'm riding the bicycle on the left side of the road. Up ahead is a roundabout, which the cyclist preferably wouldn't enter.

There's a separated road on the left of the roundabout - for traffic that goes straight ahead.

The cyclist - would preferably stay on the left side of the road and just follow his lane - don't switch lanes, and just straight ahead.

OSMAnd navigator - says:"take the roundabout and take the first exit"

Which means - the cyclist is advised to leave his lane, go to the middle of the road to the next lane, enter the roundabout, and take the first exit.

Although this is legally allowed - it's taking additional risks of switching lanes - cars here don't follow the law and rules, at least 95% doesn't follow the rules so it's quite dangerous to advise anyone with a "cycling profile for navigation" to switch lanes without any reasonable reason to do so.

Because this is a safety concern report - I'd deem this more important than any usual bug report I'd make..

here's the link to that specific location on OpenStreetMap:
https://www.openstreetmap.org/#map=19/5.95142/116.10284

<img width="687" alt="javaw_Y88ODq3Lof" src="https://user-images.githubusercontent.com/15773876/209032006-2943f44c-8c10-40c4-8d0a-6b5dced4d515.png">

**Comment by mkotzjan** [comment]
The same happens when using the routing options on osm.org:
https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=5.95218%2C116.10147%3B5.95105%2C116.10489#map=19/5.95156/116.10317

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14059mqta, released: 2022-12-29

That's right, the route goes through a roundabout - the same route is being built on OSM. I am not sure that changing the algorithms of route building just because motorists do not follow the rules of the road will be the right decision.
But, you can set Prefer unpaved roads - Riding style, and then the route will be different (shown on the screenshot).

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/209994654-5744ad36-d48a-45ad-b77b-3778e44bb45b.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
The way they are drawn the produce exactly same length / cost to enter roundabout and not to enter 115 seconds. It looks with a better mapping the problem will be gone.

**Comment by duiveldoder** [comment]
I disagree completely.

Again the main focus for me is on CYCLISTS!

A person riding a bicycle should have a preferred guidance / voice navigation - to stay at the side of the road and not switching lanes to the middle of the road (unless that's really necessary)

**Comment by vshcherb** [comment]
I totally agree with you but situation is not just OsmAnd vs OpenStreetMap, both need to work with cooperation. So without good map data we can't build a good routing, you can only expect from OsmAnd Team to display message every navigation - "This route wasn't tested by our team and could be a reason for legal violation please consult with situation around you and double check how this is area is mapped on OSM.org"

**Comment by duiveldoder** [comment]
The are in question I'm referring to is mapped well enough - even the barrier between the lanes is mapped.

https://www.openstreetmap.org/#map=19/5.95120/116.10274

Although it's not rendered on the default website - open it in JOSM and you see between the lanes even properly mapped barrier that exists on the road.

when the cyclist comes from the WNW and wants to continue to the ESE - he/she/it should just stay left. Left lane, left of the barrier.

you can't put this on properly mapped - unless you tell me what's wrong with it then i'll fix it. But switching lanes in front of a barrier to after the barrier switch lanes again doesn't make any sense in this case.

**Comment by duiveldoder** [comment]
The inner circle is always the shortest I assume that's what you're getting at.

At a roundabout that's not a great argument IMHO, especially not for cyclists, as cyclist you ought to stay, per law in some countries even, as far to the outside of the road as possible.

**Comment by vshcherb** [comment]
Inner circle is shorter if it's drawn correctly here I see it's 2 m longer

**Comment by duiveldoder** [comment]
So if you're saying the inner circle is 2m longer - then why does OSM determine bicycle riders must be told to make a dangerous move to switch lanes to the inner circle...
and then leave the inner circle and go back to the outer circle?

it still doesn't make any sense.

It's like telling someone who needs to drive from Moscow to Kiev:"first drive to London and from there you drive to Kiev"

what's the logic to do that?

**Comment by duiveldoder** [comment]
I wonder - at the point where the road splits..
if I cut it.. and then merge the road coming from the NW to the outer road.. would then the router of OSMAnd prefer to stay left? would it make a difference?

**Comment by mkotzjan** [comment]
@duiveldoder have you ever heard of people driving into lakes because they relied only on their Navigation system? Please use common sense when driving. Also please do not change the road only for the router

**Comment by duiveldoder** [comment]
> 

Have you ever heard - the moment people become rude is the moment I get it.

We're not allowed to have a mature discussion on this board.

Thank you for letting me know.

PS - your comment is totally off-topic! How would a cyclist know that after switching the lanes - he's supposed to go back to the previous lane?

For all I as rider know - it wants me to switch lanes and after that telling me to go right, where in that case switching lanes makes sense, obviously.

but again - don't reply to me anymore - you're rude I don't like rude people. 

I have an honest question, I'm asking for guidance and help and I get a rude reply .. thanks.. nice world with such people!

**Comment by duiveldoder** [comment]
> 
I also cycled a lot in the Netherlands, Germany, Belgium  - there one would not want a penalty on roundabouts.. different as infrastructure in Malaysia and adding such would be a bad idea for the infrastructure as done in Europe.

So solving this per penalties is a no-go I think.

off-topic, but can BRouter be configured to handle such specific cases? in OSMAnd I'm using BRouter as hiking router..

but I use a setting someone else made and works great for me.. if BRouter could do this.. I'll ask on the BRouter groups.. maybe for OSMAnd I can just use BRouter for both hiking/walking and cycling
