### ISSUE TITLE
Moving Osmands data folder to a user specified place - with a fantastic result.

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#16039]
### Description
Because of Android 13 (no access Osmands data in Android/obb/...) I wanted to move all data to a user specified folder.
So I took the already displayed path in the user-defined-menue-option (/storage/emulated/0/Android/obb/net.osmand.plus), just removed the "Android/obb"-part and started the process of moving data to its new destination. 
I did not watch this process entirely, and at the end of the "moving"-process there was a message box like "maps could not be moved" or something similar (text was longer than the windows size), anyway Osmand asked for a restart. Fine.

At the next start Osmand had no maps anymore, so I had to choose and download one. Ok, I will find all my maps again, no big deal.
But the main thing is: ALL my tracks, ALL my favourites, ALL my audio notices, ALL my data is gone!
All the origin data folders do still exist in the old place - but all folders are empty!
NOTHING was copied/moved to the new place, but all deleted!

ALL my data is gone. 
Data folder is still set to the multiuser1.

I dont need to tell you, how I feel right now.

Some minutes later: 
this is a good chance to run a restore from the full online backup, that was created five days ago.
Short story: Osmand let me choose what to restore (settings/places/sources) and then began restoring. 
At the end NOTHING but my Favourites was restored.

Now I remember, I tried a restore from an online backup earlier, a few months ago. Did not work. I thought that time, I´ve done some mistake. But now I know, I did not do anything wrong. It just does not work at all. 

You may check my online backup and then find out, why it is not possible to restore it. Thanks.

### How to reproduce?
Try it?

### Your Environment
OsmAnd Version: +4.3.3
Android/iOS version: 13
Device model: S20+ 5G

**Maps used (online or offline):**   
offline

**Comment by vshcherb** [comment]
You need to select previous folder back. All your data is present at old location. Online backup doesn't work cause the access to this folder is not possible.

We're going to provide online web access so you can download *.osf backup file and import it.

**Comment by Rowin63** [comment]
Your comment why the online backup did not work, this is also A13 related? No access to the obb folder?

**Comment by edwardando** [comment]
I just had this same problem after being prompted to move data, really quite a pity :(
