### ISSUE TITLE
Don't show borders of downloaded map when Weather tab is open (Android)

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd#16030]
### Description
In Android version of OsmAnd when Weather tab is on, borders of downloaded maps are shown. That worsens the quality of perception of weather information.

![photo_2022-12-22_11-33-15](https://user-images.githubusercontent.com/116079541/209092165-b28b7faa-bc17-4c1d-ac40-90787415bc3e.jpg)

### How to reproduce?
Turn Weather tab on.

### Your Environment
OsmAnd Version: 4.4.0#14035mqta
Android/iOS version: 13 Android
Device model: 
**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14050mqta, released: 2022-12-27
Done


https://user-images.githubusercontent.com/104760013/209661311-1c49ecf4-b1cb-4008-a15f-3e501c34b642.mp4
