### ISSUE TITLE
Crash with OpenFietsMap and OpenGL

### ISSUE THREAD

**Issue by eindgebruiker** [osmandapp/OsmAnd#16038]
### Description
In the newest version of OsmAnd OpenGL is the default map rendering engine. Using this rendering engine with the OpenFietsMap render style results in a crash of OsmAnd.

There may be a problem in the OpenFietsMap file, but I think at least OsmAnd shouldn't crash. OpenFietsMap does work with rendering engine version 1.

### How to reproduce?

Select Map style OpenFietsMap (https://www.openfietsmap.nl/downloads/android/osmand) with Map rendering engine Version 2 (OpenGL).

### Your Environment
OsmAnd Version: OsmAnd+ 4.3.3
Android version: 13
Device model: Sony Xperia 1 III (Sony XQ-BC52)

Crash log attached.

[adb-logcat.log](https://github.com/osmandapp/OsmAnd/files/10288904/adb-logcat.log)

**Comment by vshcherb** [comment]
Can you please contact so that people distribute as package osf (simple zip file rename could help to view contents) not as an xml
[OpenFietsMap-style.osf.zip](https://github.com/osmandapp/OsmAnd/files/10303676/OpenFietsMap-style.osf.zip)

```
2022-12-26 15:31:08.783 28922-28978/net.osmand.plus A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8366064690 in tid 28978 (Initializing ap), pid 28922 (net.osmand.plus)

```

**Comment by ivanPyrohivskyi** [comment]
In style [OpenFietsMap.render.xml](https://drive.google.com/file/d/1siUhUQRQHzpqJIpqqeh-kZs7PuLjq-4n/view?usp=drive_web) from 24.06.21 present error from line 218 to line 246.
Code ``<switch minzoom="11" legend="false" textBold="true"> ... </switch>`` is not relate to any style section (text, order, polygon etc.).
In legacy code this code relate to previous ``<text>`` section.
Now this code ignored. Crash fixed by https://github.com/osmandapp/OsmAnd-core/pull/444

**Comment by ivanPyrohivskyi** [comment]
Need to fix style for OpenGL.
Legacy/OpenGL:
<img src="https://user-images.githubusercontent.com/1040293/209799076-800a048c-e820-4036-84be-ada45707ee2b.png" width="400"/> <img src="https://user-images.githubusercontent.com/1040293/209799084-8c9b2c1f-2812-4557-babb-b28c134e9fe2.png" width="400" />

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14066mqta, released: 2022-12-31

[exception (1) (2).log](https://github.com/osmandapp/OsmAnd/files/10327040/exception.1.2.log)

A crash occurs when importing a file. After importing, the work is stable on both OpenGL and Legacy


https://user-images.githubusercontent.com/104760013/210130074-e3fb05db-18a6-4987-b3a4-0807c0224d0f.mp4

**Comment by vshcherb** [comment]
Crash related to dashboard looks like there is another issue for that
