### ISSUE TITLE
Lake names disappear

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#16045]
Names of lakes sometimes disappear with the new OpenGL rendering.

Example at 51.31335,12.52562

Name visible:
![IMG_20221223_090155](https://user-images.githubusercontent.com/1040784/209305528-74cdffd1-8193-4aa5-895f-d6c8e0f10342.jpg)

Name vanished after moving the map to the left:
![IMG_20221223_090117](https://user-images.githubusercontent.com/1040784/209305647-d1342ce0-4bff-4de5-8304-d624adaf10e3.jpg)

This doesn't happen with the old rendering engine. With the new rendering engine lake names are displayed much less often even if there is enough space for the label.

**Comment by vshcherb** [comment]
Not critical as I see on the map, it doesn't blink
