### ISSUE TITLE
Deleted track stays visible until restart

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#16049]
### Description

Deleting a track that is currently visible doesn't make it disappear on the map. 

### How to reproduce?

* Enable a track
* Delete this track
* Track stays visible

### Your Environment
OsmAnd Version: 4.3.3
Android/iOS version: Android 10
OpenGL enabled

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14059mqta, released: 2022-12-29

@scaidermern Please add a video where we can see your playback steps or try one more time at the newest version.


https://user-images.githubusercontent.com/104760013/209996344-5031ad3e-0b3a-4734-a466-5ec997b7437b.mp4

**Comment by scaidermern** [comment]
I can't reproduce it right now. I close this ticket until I find out how to reproduce it. Must be caused by some side condition I guess.
