### ISSUE TITLE
wheelchair : need wheelchair option

### ISSUE THREAD

**Issue by JLZIMMERMANN** [osmandapp/OsmAnd#16055]
# 🚀 feature request

### Description

OSMand gives several profiles : car, bicycle, pedestrian and bus but not wheelchair. We have been asked what application should one wheelchair user try to see easily where to park. We are not able to give any answer for this case because even wheelmap.org doesn't give such option.

### Describe the solution you'd like

In first step a wheelchair profile would be a good way to display relevant POI for people disabled using wheelchair : shops with wheelchair=yes and also display parking_space=disabled

### Describe alternatives you've considered

A first good starting point would be to display an icon for wheelchair on parking space designed.

**Comment by itzikiap** [comment]
You can actually create a new peofile. In the settings menu,  scroll down and select "add profile", there you can choose a color and an icon, than customize it as you please.
I don't know how to search by wheelchair accessiblity, though

**Comment by JLZIMMERMANN** [comment]
The goal is not just to add an icon but get the whole options 🙂

**Comment by scaidermern** [comment]
Already requested in #9415.
