### ISSUE TITLE
Regression: Search History doesn't sort items correctly by access time

### ISSUE THREAD

**Issue by ReinhardPh** [osmandapp/OsmAnd#16052]
In the menu Search/History the last searched objects are no longer displayed.
Instead, route records and selected POI groups are shown there.
Osmand version 4.3.4
Problem since Osmand 4.3

### How to reproduce?
Calling up from the map with magnifying glass symbol/History
Calling up via menu Search/History

### Your Environment
OsmAnd Version: 4.3.4
Android/iOS version: Android 10
Device model: moto G8 power lite

**Maps used (online or offline):**   
Seems not related to maps used.

**Comment by sonora** [comment]
Can reproduce. Neither the very POI you have actually searched and then selected from the hit list seems added to the search history list  nor a specific addtees you have found via the address search tab.

**Comment by ReinhardPh** [comment]
Addition
The search entries are included in the list, but not chronologically. 
With my list of 1,500 entries, the relevant search results are therefore very difficult to find.
Suggestion: The list should be ordered chronologically.

**Comment by sonora** [comment]
Indeed. It seems that tif you had searched a POI via a category, the POI's category is subsequently shown a the top od the Search history list. But the actual POI is displayed several hundred lines further down, somewhere in the middle of the list.Also recent town or address search hits are hidden down there.

Related issue: Most of what's in between is in my case used up by countless track entries I had at some point selected as visible on the map, even thoughbI had done this via the MyPlaces dialog and not via search. These entries should likely not be in the search history at all.

**Comment by sonora** [comment]
In summary: It seems the search history works perfectly all right but since a few weeks it seems "polluted" by also containing
- searched POI categories
- and once-displayed tracks,
and both of these are categorically sorted to the top of the list. If you scroll down below these entries, this is where a search history as you would expect it starts.

**Comment by Zirochkabila** [comment]
Merge to https://github.com/osmandapp/OsmAnd/issues/13874

**Comment by vshcherb** [comment]
**Main issue** - category and tracks are not sorted correctly they pollute the list from top. Everything should be sorted as it was last time accessed (opened).

All specific items don't work 
1. Search POI by name - open it (POI is not in history)
2. Select Category, Select POI - open it (POI is not in history)
3. Select address with hierarchy search - open it (Point is not in history)
4. Select item
....

**Comment by sonora** [comment]
@vshcherb Just to clarify the proper fix: Is it intended behavior that the search history list contains also
- searched **POI caregories**
- and **displayed tracks never searched**?

i.e  should the proper fix be to remove  these items from the history list, or include them in the sorting?

(Especially tracks can be mass-displayed, in such cases easily pollute the history list. Same for **favorite categories**, but interestingly these seem anyway _not_ included in history list after making one visible.)

**Comment by vshcherb** [comment]
> Yes
- searched POI categories
- and displayed tracks never searched?

This a "broad search history" means whatever displayed in context menu.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14074mqta, released: 2023-01-05
Done


https://user-images.githubusercontent.com/104760013/210739608-a43295ba-c0f8-4583-9228-81b4beb18879.mp4
