### ISSUE TITLE
Tourist attraction not found in poi

### ISSUE THREAD

**Issue by tradavyvy** [osmandapp/OsmAnd#16057]
### Description
When setting 'tourist attraction' to be highlighted on map (orange circles)
The ones on the map that have a small (red) star are not highlighted.
(Dutch version)

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/71978409/209464040-a4d920e0-6ce8-4fda-a0c0-9a70d38cb016.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/71978409/209464045-568bd742-1b91-4c1a-89ea-4140bf680acc.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14057mqta, released: 2022-12-28
`10.913869, 104.502469`
@tradavyvy Try to do as shown in the video (language doesn't matter)


https://user-images.githubusercontent.com/104760013/209860857-5681925f-46dc-467e-9abe-ab598894af0c.mp4

**Comment by ceever** [comment]
**Works fine for me in OSMand 4.3.3:**

<img src="https://user-images.githubusercontent.com/40247591/210010046-11e6b599-38b0-4473-b03f-cab4bbda09f7.jpg" width="320"/>

@tradavyvy : Maybe you lost the "Tourist attraction" selection while browsing. I think I had that issue before as well, when continuing browsing after the search, the search gets lost. Maybe it is this issue and not a display issue?

**Comment by tradavyvy** [comment]
Thank you, but that is not the problem.
There are (at least in the dutch version) 2 different categories:
Toerisme (Toursim) and Touristische atractie (Touristic atraction)
The first contains (also) a lot of 'utilitarian' info you do not necesarily interested in when sightseeing, like campsites etc..
The second is more compact and shows the things you might want to go and see, like castles, temples, street art, fountains etc.
Some points marked like (or maybe only those) 'touristic atraction' are not in the first category (where they belong). But they are in the second.

Because these are two realy different sets of info I would sugest having 'tourist attractions' rendered in the Tourist Attactions category.

And also maybe do some pruning in the Tourism category. So one becomes like 'places to see' (castles, fountains, churches...) and the other more like 'places you might need' (campsites, hotels, police stations ...)

This also will prevent the 2 categories from swamping each other. (Atraction rich areas are usualy also hotel and campsite rich areas)

Some screenshots:

![Screenshot_20221230-021804_OsmAnd+](https://user-images.githubusercontent.com/71978409/210026718-c993798e-352c-4936-bcf6-933e52ec2b1a.jpg)

![Screenshot_20221230-021823_OsmAnd+](https://user-images.githubusercontent.com/71978409/210026719-9c7a8d4d-7567-475a-a13c-1bb0068eb413.jpg)

![Screenshot_20221230-022310_OsmAnd+](https://user-images.githubusercontent.com/71978409/210026720-aaa3aa6e-d661-412e-a44a-973761ad33be.jpg)

![Screenshot_20221230-022327_OsmAnd+](https://user-images.githubusercontent.com/71978409/210026721-ee3497e2-7c93-4781-bbdd-d329351cb7d0.jpg)

**Comment by ceever** [comment]
I got it now! @ devs!

@tradavyvy is right, my confusion here stems from the language difference.

The category that is called "Toeristische attractie" in the above demonstration is actually called "Sightseeing" in English. And yes, tourism=attraction nodes are not displayed under "Sightseeing". I just verified that, see graphic in the following:
<p><img src="https://user-images.githubusercontent.com/40247591/210105812-32b71b91-227a-46ee-b786-57aa711965f8.jpg" width="300"/></p>

Sorry for the confusion, but indeed tourism=attraction nodes should really be included in "Sightseeing" ... obviously.

I wouldn't change the "Tourism" category though!! I think, it is a good thing that it is broader than "Sightseeing", basically covering anything. I would rather add an alternative category "Tourism infrastructure" to exclude sights, etc.

Thanks

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14068mqta, released: 2023-01-02
I think that the idea described by the @ceever  will be the most appropriate

https://user-images.githubusercontent.com/104760013/210210540-e5bbe3f6-04b2-4a30-9f5e-9c4ab0936e99.mp4

**Comment by tradavyvy** [comment]
I not sure we disagree, but my recomendation would be te make 2 cattegories with minimal overlap. I think usualy people are either sightseeing or looking for infra structure e.g. hotels etc..
And having them in one category makes it harder to find what you are after. 
See how clutterred the screenshot of Brugge, Belgium is with 'tourism' (the current combined option) turned on.
![Screenshot_20230102-103645_OsmAnd+](https://user-images.githubusercontent.com/71978409/210215190-c20cf8c0-7f51-4ffb-afcd-335c15963400.jpg)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14155mqta, released: 2023-02-06 - Done
Master branch - Done
