### ISSUE TITLE
openGL engine ... Hiking route not visible 

### ISSUE THREAD

**Issue by miramikes** [osmandapp/OsmAnd#16053]
Hello,
with openGL engine is not hiking route visible ...
Same setting just old and new engine.
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/623412/209438842-287b1968-f705-4dd1-88df-7ca04dbafc28.png"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/623412/209438851-4c3f537a-e366-43bd-92ac-387bb9eef700.png"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by scaidermern** [comment]
Same problem for me.

There is a temporary fix: Go to configure maps / hiking routes and select one of the different styling modes. Afterwards the routes are displayed. Until restarting OsmAnd, then they are gone again.

**Comment by ivanPyrohivskyi** [comment]
<img src="https://user-images.githubusercontent.com/1040293/209972521-9a220481-9896-4d7c-ac0d-e354ed02cecf.png" width="400" /> <img src="https://user-images.githubusercontent.com/1040293/209972527-21b602f4-1441-49a9-a5d6-3a9ac8a435be.png" width="400" />

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14068mqta, released: 2023-01-02
Done
