### ISSUE TITLE
Clearing the weather_forecast folder

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#16051]
### Description
I noticed that the weather plugin folder is increasing in size and that the data in it is not cleared automatically.
I think it is necessary to add a mechanism to clear the folder of old weather forecasts.

### Your Environment
OsmAnd Version: 4.4.0#14044mqta
Android version: 12
Device model: poco f3

**Comment by vshcherb** [comment]
Extra UI tasks:
## Review
- [ ]  Decrease padding between zoom buttons and bottom menu with dates.
- [ ] Decrease corner radius on buttons with data
- [ ] Add compass button

**Comment by nazar-kutz** [comment]
**Pull Request (UI Fixes)**
* https://github.com/osmandapp/OsmAnd/pull/16101

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14068mqta, released: 2023-01-02
Done
