### ISSUE TITLE
Ski Routing: oneway=no ignored

### ISSUE THREAD

**Issue by droogmic** [osmandapp/OsmAnd#16061]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Ski

### Start and end points

Near both ends of https://www.openstreetmap.org/way/314117011.
Specifically starting at the south and ending at the north.

### Actual and expected routes

Navigating on https://www.openstreetmap.org/way/314117011 should by symmetric in both directions.

However, navigating from the southern end to the northern end is incorrectly forbidden and causes a massive detour.

I assume oneway=no is ignored, as the way direction is north to south.

### Is this a regression?

Probably not. I didn't notice this last year, but I may have not intentionally routed over this way

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>
4.2.6
</code></pre>

**Device and Android/iOS version:**

Android 11
Oxygen OS 11

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14064mqta, released: 2022-12-30

`46.11376, 7.30497`
[OsmAnd](https://osmand.net/map/?start=46.116563%2C7.306488&end=46.113587%2C7.303934&mode=ski#17/46.11533/7.30607)

https://user-images.githubusercontent.com/104760013/210046687-26ef1c5b-a47a-406b-a2f1-bc7bf5be56fd.mp4

**Comment by xmd5a2** [comment]
Should be fixed in upcoming maps

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14217mqta, released: 2023-03-04
04.03 master
Done
