### ISSUE TITLE
Augmented height on 2.5D view

### ISSUE THREAD

**Issue by CristiG80** [osmandapp/OsmAnd#16060]
Hi. I would like to make a suggestion about 2.5D map rendering. It would be very useful if the height of the terrain would be augmented, multiply by a factor, because now it looks pretty flat.

**Comment by arncor** [comment]
That's because it is flat. #15991

**Comment by CristiG80** [comment]
Is this some kind of sarcasm which I don't understand?

**Comment by CristiG80** [comment]
I've read the issue linked to this and I see now that this is  PRO feature. I was expecting to have it on the "Plus' version, but anyway... Closing

**Comment by CristiG80** [comment]
Duplicate of [#15991](https://github.com/osmandapp/OsmAnd/issues/15991)

**Comment by arncor** [comment]
> I've read the issue linked to this and I see now that this is  PRO feature. I was expecting to have it on the "Plus' version, but anyway... Closing 

Yep, same here. Sorry for the sarcasm ;)
