### ISSUE TITLE
feature req: "remaining trip time" info in right panel

### ISSUE THREAD

**Issue by cptMikky** [osmandapp/Osmand#1606]
As much as I like the Estimated Time **of** Arrirval feature, I'd prefer having the **remaining trip time** information, or Estimated Time **to Arrival**, available. Preferably as a yet another "icon" to the right panel.

cheers!

**Comment by jf-simon** [comment]
Tap on the time to switch between time of arrival and remaining trip time

**Comment by vshcherb** [comment]
Yes, it is available by tapping on it.

**Comment by cptMikky** [comment]
Thanks for info, I had no clue. Perhaps this behaviour should be described in documentation.
