### ISSUE TITLE
pre-calculated traveltime is always displayed in seconds 

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#16065]
### Description
The travel time in the popup is always displayed in seconds (time xxxx sex)

### Your Environment
OsmAnd Version: 4.3.4 but was earlier too
Android/iOS version: 13
Device model: S20+

**Maps used (online or offline):**   
offline

![Screenshot_20221226_102907_OsmAnd+](https://user-images.githubusercontent.com/95540936/209533426-84a11503-6cfe-48f8-8f3a-9b788d6271c4.jpg)

**Comment by dmpr0** [comment]
Hi!
The toast shows up only if **OsmAnd Development** plugin is On, and made for development purpose.

**Comment by sonora** [comment]
Yes, that's not really the "pre-calculated travel time", it's a benchmark figure for debugging. German translation shown in the screenshot may be questionable. Also, with this being reported a second time already (#13501), maybe it's about time we make this an explicit setting in the Dev plugin and not activate it automatically when the user activates the plugin?

**Comment by Rowin63** [comment]
Ah, thank you. Did not realize it is connectet to the plugin.

**Comment by Zirochkabila** [comment]
@Rowin63 can we close this issue?

**Comment by Rowin63** [comment]
Yes of course, thanks

**Comment by sonora** [comment]
@vshcherb So how about https://github.com/osmandapp/OsmAnd/pull/16066?
