### ISSUE TITLE
wrong pos of car (current) in 2.5D view in navigation simulation

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#16067]
### Description
In the mountain (Germany, black forest, Mountain pass = Kandel )
I made a navigation starting from the valley with car profile.
Current pos should be "near bottom".
The problem is, that when i increase the angle of 2.5D view, then the car position moves near to the top of screen.
So the view position is var away from the car /current pos.
Reducing 2.5D angle removes pos to the expected one near bottom.

Use this starting point 48.04020° N, 7.98305° E, dest= dest = 48.06504° N, 8.01623° E 

### How to reproduce
Test with different 2.5D angle and different zoom level.

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14045mqta, veröffentlicht: 2022-12-24
Android version: 10
Device model: samsung tab S5e

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14059mqta, released: 2022-12-29
As you can see in the video - the position remains in the same place at different angles and map scales


https://user-images.githubusercontent.com/104760013/209924804-012fc8c9-6c13-40ce-8a03-003a03b608b6.mp4

**Comment by pebogufi** [comment]
I made more test with OsmAnd~ 4.4.0#14059mqta.
The problem only occurs with heightmap activated and if button "current pos" is pressed.
See also https://github.com/osmandapp/OsmAnd/issues/16086.

**Comment by Zirochkabila** [comment]
Merge to https://github.com/osmandapp/OsmAnd/issues/16086

**Comment by pebogufi** [comment]
https://github.com/osmandapp/OsmAnd/issues/16586
