### ISSUE TITLE
Editing more than one tracks in one go

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#16068]
# 🚀 feature request

### Description

Hello!
I know, it already is a "perhaps future feature", but until then there is only one way to edit some settings of more than one track (configure map - tracks - ...)
But the options are very little, I can't find a possibility to add colors to this menu. There is no green and no yellow at the predefined color list, I would need that. 
Is it possible, as an "in between solution", to add a color picker or something similar please?

Thanks 

### Describe alternatives you've considered

Edit tracks one by one 

![Screenshot_20221226_121747_OsmAnd+](https://user-images.githubusercontent.com/95540936/209544870-907c9afd-babe-427d-9d51-2561f833576f.jpg)

**Comment by vshcherb** [comment]
Yes it's planned

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/11336

**Comment by Rowin63** [comment]
I think we can close thi here, it is continued in #13388
