### ISSUE TITLE
Support for time-condition turn restrictions

### ISSUE THREAD

**Issue by ERnsTL** [osmandapp/Osmand#1607]
Greetings, I had to navigate through city using OsmAnd+ and calculated route. I use It daily and am quite happy, but it calculated horrible route in this case:

![screenshot_2015-04-30-19-55-55](https://cloud.githubusercontent.com/assets/3127919/9501468/c94152c6-4c2b-11e5-8cdf-61ea68d10522.png)

As it seems, OsmAnd+ does not use time condition on turn restriction relations.

The important relation attributes are hour_on and hour_off, see [the relevant page in the official OSM wiki](http://wiki.openstreetmap.org/wiki/Relation:restriction). Please make OsmAnd+ consider these attributes also and cull accordingly.

I have attached screenshots of the symptoms and with example relation in Vienna, Austria:

![only_straight_on time-restricted](https://cloud.githubusercontent.com/assets/3127919/9501467/c93b1898-4c2b-11e5-9e77-9b89bc15890c.png)
![only_straight_on](https://cloud.githubusercontent.com/assets/3127919/9501469/c9428f7e-4c2b-11e5-990b-2420c7101609.png)

I have the screenshot on my device for a few months, wanting to report the issue, sorry for report if this has been fixed in the meantime.

**Comment by hakuchi** [comment]
I think you sold not use hour_on and hour_off on turn_restrictions.
better using access:conditional on the street, and Osmand sold support access:conditional

**Comment by sonora** [comment]
Merge to #1794.
