### ISSUE TITLE
font weight varies sometimes

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#16078]
### Description
See the attaches screenshots, sometimes the font in the widget varies from light to "normal" (I always noticed it in this direction).

It´s neither important nor dramatic, but happens sometimes (I think since 4.3.3., didn´t notice it before)

### Your Environment
OsmAnd Version: +4.3.4
Android/iOS version: 13
Device model: S20+5G

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

![Font light](https://user-images.githubusercontent.com/95540936/209684039-21718bbf-3cf1-4c91-a031-d7785adc499c.JPG)
![Font normal](https://user-images.githubusercontent.com/95540936/209684054-8bce90ea-0032-44fe-a3e6-2a6dab7eef37.JPG)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14064mqta, released: 2022-12-30

@Rowin63  The behavior could not be reproduced.
Please try downloading the latest nightly version (beta version - available on OsmAnd PlayStore page) and check again. If you manage to get the result shown in the screenshots - please send a log file: Menu > Help > Send logcat log

**Comment by Rowin63** [comment]
Have not noticed this anymore. Temporary appearance...?

**Comment by Zirochkabila** [comment]
Maybe

**Comment by Rowin63** [comment]
Can we close this?
It happened a few times (in the mentioned version) but never again since then.

**Comment by Rowin63** [comment]
Still happens every now and then, see the attached screenshot.
This time in +4.3.7 (before was +4.3.4)

Sent a logcat.log (as requested above) to crash@osmand.net referring to this issue´s number.
(it´s not possible to attach a logcat.log here)

![Screenshot_20230201_103813_OsmAnd+](https://user-images.githubusercontent.com/95540936/216042761-9cd2a636-4e6b-4fc6-9b27-493a3335cb54.jpg)

**Comment by Zirochkabila** [comment]
@Rowin63 We still can't reproduce it. But we will be watching and looking into this issue.
Please try to download the public beta version 4.3.10 and send the log file (after reproduction) again to the mail - in the Subject: (in the letter) specify "change font", this will help us to find your letter

**Comment by Rowin63** [comment]
Good morning!

Happened again, sent a mail as requested.

Regards, Robert
