### ISSUE TITLE
The position icon isn't displayed during navigation (Android & iOS)

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16086]
### Description
If downloading Height map the position icon isn't displayed during navigation
[logcat (41).log](https://github.com/osmandapp/OsmAnd/files/10318433/logcat.41.log)

### Steps to reproduce
Load the height map > Start navigation (simulation of navigation, or simulation location by GPX)

### Actual result
Position icon isn't displayed

Simulate navigation

https://user-images.githubusercontent.com/104760013/209926347-958f86e5-d226-43c4-a6a1-fe2d0854a13a.mp4

https://user-images.githubusercontent.com/104760013/209927587-49bf31b1-51d8-467f-9374-bebd1e7471f6.mp4

Simulation location by GPX

https://user-images.githubusercontent.com/104760013/209926397-52d1f9b6-c4ec-49af-b8b1-e78cca14aaa8.mp4

### Expected result
The position icon is displaying

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14059mqta, released: 2022-12-29 / 4.4.3.1 iOS
Android/iOS version: Android 12
Device model:  Poco x3 nfc

**Comment by pebogufi** [comment]
See also https://github.com/osmandapp/OsmAnd/issues/16586

**Comment by vshcherb** [comment]
We need to properly test if My Locaiton animation is still smooth @Zirochkabila that was the main issue 3 months ago cause during navigation map was jumping

**Comment by mikehgentry** [comment]
Long pressing on a point to start navigation will pick the wrong spot at very low angles too. Let me know if you want me to file a separate bug.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14261mqta, Released: 2023-03-23
4.4.6.10
Done
