### ISSUE TITLE
OsmAnd wrongly replaces amenity=shelter with tourism=lean_to when editing

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#16083]
When editing an object tagged as `amenity=shelter` (such as https://www.openstreetmap.org/way/298181596) OsmAnd 4.3.4 automatically replaces this tag with `tourism=lean_to`. This is wrong and should be fixed soon. 

See the related discussion here: https://community.openstreetmap.org/t/editieren-mit-osmand-verworrene-anfangerfragen/7307

Please also check if there are other cases where tags are automatically replaced by OsmAnd. This is always wrong and must never happen.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14064mqta, released: 2022-12-30

@scaidermern A test was conducted with this [POI](https://www.openstreetmap.org/way/1033104476#map=19/50.43183/30.47768)- behawior couldn't be reproduced.
Although, judging by the discussion on the link you sent - the problem exists.
Please provide a video where we can see the steps to playback and the result.

**Comment by scaidermern** [comment]
> Please provide a video where we can see the steps to playback and the result.

I can't reproduce it with OsmAnd 4.3.5. Maybe this was already fixed? I guess you have to ask your developers :)
