### ISSUE TITLE
Sharing a track from the MyPlaces screen crashes

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#16087]
Go to `MyPlaces > Tracks > tap any track's 3-dot menu > Share`:
[exception.log.txt](https://github.com/osmandapp/OsmAnd/files/10318569/exception.log.txt)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14059mqta, released: 2022-12-29
@sonora  Try to update OsmAnd


https://user-images.githubusercontent.com/104760013/209930667-1cb683c3-ff46-4e02-97ad-c5d5fd216bee.mp4

**Comment by sonora** [comment]
Indeed, it seems that Victor's refactoring https://github.com/osmandapp/OsmAnd/commit/b0aeb894714393fa41b800b472d9352246b1b647 last night had fixed this, so my compilation was about 2 hours too old! :wink:

Thanks for the lightning-fast reaction and the good work, @Zirochkabila !
