### ISSUE TITLE
Austria | Tirol map is missing a part of Tirol

### ISSUE THREAD

**Issue by mdykierek** [osmandapp/OsmAnd#16090]
I have downloaded all Austria parts and the area of Lienz, Matrei in Osttirol remains white.
When selecting this part of map, it reads that it is included only in Austria (not a given area like Carinthia, Salzburg, etc.)
The reason might be that Tirol is actually split into 2 separate areas...
![1672311975447](https://user-images.githubusercontent.com/27214784/209942876-f1d944a3-b085-4d21-bbaf-bfaec6519da4.jpg)

**Comment by vshcherb** [comment]
Is the map itself displayed correctly ?

**Comment by mdykierek** [comment]
It looked that the streets etc. were displayed OK. I plan going through Tirol and I cannot afford situation where routing will fail.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14092mqta, released: 2023-01-13
@mdykierek  When using V2 rendering, a part of the map is indeed not displayed in green, although at higher zoom all data on this area is displayed.
If you switch to V1 rendering - the problem disappears and part of the map is displayed in green color as well.


https://user-images.githubusercontent.com/104760013/212301278-0056a0d4-d67a-46d1-b201-11d0e6c26e31.mp4

**Comment by vshcherb** [comment]
Summary: 2 bugs
1. Opengl (not legacy) doesn't show 2 parts of Tyrol
2. Click on 2nd part of Tyrol doesn't suggest to download

**Comment by ivanPyrohivskyi** [comment]
Need also fix for iOS

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#14270mqta, Released: 2023-03-25
Done
4.4.6.11
Still present

**Comment by dmpr0** [comment]
## Review
- [ ]  Green overlay of over downloaded regions are blinking when context menu is opens or closed.
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src=""  width="300" height="auto"/> </td>
    <td><img src=""  width="300" height="auto"/> </td>
  </tr>
</table>   

<video source src="https://user-images.githubusercontent.com/9365308/228535803-eb44e87b-1422-43aa-aae0-0f1f9f5d8dfe.mov"  width="300" height="auto"/>

**Comment by vshcherb** [comment]
Not critical... @dmpr0 separate issue could be open
