### ISSUE TITLE
OpenGL renders sluggish

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#16098]
Sony Experia XZ1 - Android 9

https://user-images.githubusercontent.com/1042025/210060412-3fe19c22-3c6c-44b4-8530-fdd72b7946e5.mov

**Comment by anastasiia936** [comment]
Brand : CUBOT
Model : QUEST
Product : QUEST_EEA
Build : CUBOT_QUEST_V14_20200820
Version : 9
App Version : OsmAnd
Apk Version : 4.3.4 4304

The touch screen does not work with OpenGL rendering. While trying to move the map the app opens the point's Context menu. 
The Legacy rendering works better. 
With version 4.2.2 it worked perfectly.
[logcat (26).log](https://github.com/osmandapp/OsmAnd/files/10332460/logcat.26.log)

**Comment by sonora** [comment]
@anastasiia936 This is what some people call "freeze" in several similar issues: The app seems to still somehow respond, e.g. menus open, but the map is frozen, e.g. insensitive to trying to pan or zoom.

**Comment by anastasiia936** [comment]
Device : dream2lte
Brand : samsung
Model : SM-G955F
Product : dream2ltexx
Build : PPR1.180610.011.G955FXXUCDVI1
Version : 9
App Version : OsmAnd
Apk Version : 4.3.5 4305
[logcat (30).log.zip](https://github.com/osmandapp/OsmAnd/files/10384604/logcat.30.log.zip)
![image](https://user-images.githubusercontent.com/80623554/211603572-11e49336-da5f-4c2a-b4b5-3ffbf3fc1061.png)

**Comment by Zirochkabila** [comment]
### Description
Freezing map with Legacy rendering

### Steps to reproduce
Download Travel guides (Europe - Paris) > Select Paris / 1st arrondissement > Settings > OsmAnd settings > Map rendering engine > V1

### Actual result
Map is freeze


https://user-images.githubusercontent.com/104760013/211835274-b2487c0e-fa11-453c-83a4-266c25191ebd.mp4



### Expected result
Map is displayed as with the renderer V2

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14086mqta, released: 2023-01-11
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by vshcherb** [comment]
Needs to be tested @anastasiia936 with 4.3.6

**Comment by anastasiia936** [comment]
Tested OsmAnd 4.3.6. Seems to work better
https://user-images.githubusercontent.com/80623554/211858169-ef0f0dad-d10b-49be-8de1-39e93a55824f.mp4

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14114mqta, released: 2023-01-18
No cases with crashes or slow rendering were noticed
