### ISSUE TITLE
opening hours are not parsed/displayed correctly

### ISSUE THREAD

**Issue by michaelprager** [osmandapp/OsmAnd#16092]
### Description
I noticed that complex open hours are not parsed correctly. Here is an example:

`Mo-Fr 10:00-18:30; We 10:00-14:00; Sa 10:00-13:00; Dec-Feb Mo-Fr 11:00-17:00; Dec-Feb We off; Dec-Feb Sa 11:00-13:00; Dec 24-Dec 31 off "Inventurarbeiten"; PH off`

For today, (29.12.2022), the app will show "opening tomorrow at 10:00". However the rule `Dec 24-Dec 31 off "Inventurarbeiten"` indicates that it is actually closed tomorrow. Also during Dec-Feb, the opening hour for Mo starts at 11:00 not 10:00.

### How to reproduce?

Open the following POI: https://www.openstreetmap.org/node/3484520472

### Your Environment
OsmAnd Version: 4.3.3
Android/iOS version: 13
Device model: Pixel 7 Pro

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14068mqta, released: 2023-01-02
[Map](https://drive.google.com/file/d/1lo9CZtO6gF0U3uWrAvh4kbWtlM-Y3HsJ/view?usp=sharing)

<img width="1122" alt="Screenshot 2023-01-02 at 14 14 45" src="https://user-images.githubusercontent.com/104760013/210229937-3719aaf6-5e27-4c7b-a45f-272e6f82f07c.png">


https://user-images.githubusercontent.com/104760013/210229963-87682ab8-77ca-4338-9e83-a9763704b948.mp4

**Comment by scaidermern** [comment]
A general question regarding the parsing of `opening_hours` in OsmAnd: The opening_hours syntax of OSM is quite complex. Instead of-reinventing the wheel and wasting a lot of time in fixing such issues - why not simply use [opening_hours.js](https://github.com/opening-hours/opening_hours.js) to parse the value of the `opening_hours` key? This library is licensed under LGPL v3.0. So it should be possible to include it in OsmAnd. Has this ever been considered? Is the library too big or too slow?

**Comment by vshcherb** [comment]
It should be considered now I think, cause it's finally supports all use cases and it's probably easier to switch on other cases we still have faster code (Java / C++) but it doesn't matter if we need to support more & more complicated cases with Public Holidays.

**Comment by vshcherb** [comment]
On the other hand we won't be able to support it in the routing where speed is critical though in most of the cases they don't have complicated syntax.

**Comment by scaidermern** [comment]
> On the other hand we won't be able to support it in the routing where speed is critical though in most of the cases they don't have complicated syntax.

True.

Maybe for routing it is possible to pre-process conditional access tags with opening hours during map creation and to transfer them into an OsmAnd-internal format? For the base maps and also for live updates. Then OsmAnd doesn't have to perform this expensive task during routing.

**Comment by vshcherb** [comment]
Just tested on the website https://openingh.openstreetmap.de/evaluation_tool/
```
Mo-Fr 10:00-18:30; 2023 Jan-Feb Mo-Fr 12:00-17:00;  2023 Feb Mo-Fr 11:00-17:00;  PH off
```  (open from 11:00 in Feb)
vs
```
 2023 Jan-Feb Mo-Fr 12:00-17:00;  2023 Feb Mo-Fr 11:00-17:00;  Mo-Fr 10:00-18:30; PH off
``` (Always open on from 10:00!)

Looks like rules are evaluated from **right to left** which is a contradiction to documentation.

**Comment by scaidermern** [comment]
> Looks like rules are evaluated from **right to left** which is a contradiction to documentation.

I don't know why you got that impression. This website evaluates rules correctly from left to right. If a time span is covered _again_ by a _later_ rule that is separated by a _semicolon_ than the _new_ rule applies. This is what the specification says and this is what this website does.

**Comment by vshcherb** [comment]
@scaidermern time span is not covered, it's shorten on the right side. 
Rules are evaluated from left to right. If a normal rule that specifies open hours **applies to a given day**, then this rule overrides all earlier rules applying to that day. 

Yes I see first rule should be tested without time limits and if it applies then it overrides earlier rules

**Comment by alex-osm** [comment]
I just merged request. Github closed it automatically.

**Comment by ivanPyrohivskyi** [comment]
С++

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14189mqta, Released: 2023-02-20
Done

**Comment by verdulo** [comment]
I want to report almost identical problem, the value `Mo-Sa 06:00-22:00; Jan 26,Apr 13,Apr 27,Jun 29,Aug 31,Dec 07,Dec 14,Dec 21 Su 08:00-19:00; PH off` is not processed today 2025-04-13. OsmAnd (both 4.9.10 and Nightly 5.1.0) marks the shop with that value of opening_hours as closed today.
