### ISSUE TITLE
OpenGL rendering make application slower

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#16093]
Osmand+ V 4.3.4 it takes up to 40 seconds to launch the app.
Before it has been around 3 - 5 seconds.
Sony Xperia XZ1 Compact, Android 9
[logcat rendering V1 (1).log](https://github.com/osmandapp/OsmAnd/files/10320232/logcat.rendering.V1.1.log)
[logcat rendering V2 (1).log](https://github.com/osmandapp/OsmAnd/files/10320233/logcat.rendering.V2.1.log)

**Comment by anastasiia936** [comment]
Since the last update it takes 1.5 minutes for the app to start.

Device : HWEVR
Brand : HUAWEI
Model : EVR-L29
Product : EVR-L29
Build : EVR-L29 10.1.0.247(C432E6R1P7)
Version : 10
App Version : OsmAnd+
Apk Version : 4.3.4 4304
[logcat (2).log](https://github.com/osmandapp/OsmAnd/files/10320243/logcat.2.log)

**Comment by anastasiia936** [comment]
Fairphone3s
after starting osmand+, map background and contours are shown, but all other maps come up after many (10+) minutes, if at all

**Comment by anastasiia936** [comment]
App crash and freeze with OpenGL rendering.

Device : RMX3081L1
Brand : realme
Model : RMX3081
Product : RMX3081EEA
Build : RMX3081_11_C.24
Version : 12
App Version : OsmAnd
Apk Version : 4.3.4 4304

[logcat (23).log](https://github.com/osmandapp/OsmAnd/files/10320255/logcat.23.log)

**Comment by anastasiia936** [comment]
OsmAnd load map very slow and does not display POI, map markers. It is periodically freezes and crashes.
Device : G8342
Brand : Sony
Model : G8342
Product : G8342
Build : 47.2.A.11.228
Version : 9
App Version : OsmAnd+
Apk Version : 4.3.4 4304

[logcat (24).log](https://github.com/osmandapp/OsmAnd/files/10320297/logcat.24.log)
[exception (63).log](https://github.com/osmandapp/OsmAnd/files/10320298/exception.63.log)

**Comment by scaidermern** [comment]
Maybe related to #15926?

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/16093#issuecomment-1367419308 should be fixed
Merged to https://github.com/osmandapp/OsmAnd/issues/15926
Another observation - https://github.com/osmandapp/OsmAnd/issues/15968

**Comment by vshcherb** [comment]
Slow rendering moved to https://github.com/osmandapp/OsmAnd/issues/16098
