### ISSUE TITLE
tourism=attraction still not displayed with proper POI icon

### ISSUE THREAD

**Issue by ceever** [osmandapp/OsmAnd#16096]
### Description
This is a reopening of https://github.com/osmandapp/OsmAnd/issues/15380
Unfortunately, this is still not fixed properly. I have already laid out comprehensively, why it would really make sense to give tourism=attraction a proper POI icon. And since an attempt was made to fix is, I though it is relevant.

However, we still have the situation that it is still not displayed properly with an appropriate POI icon:
<p style="vertical-align:top;white-space:nowrap;">
<img src="https://user-images.githubusercontent.com/40247591/210004479-4683fe1c-e233-4640-b8e7-b1b3647cd8e4.jpg" width="200"/>
<img src="https://user-images.githubusercontent.com/40247591/210004516-cb352cd7-d32c-4eeb-8e89-b797e719e3d2.jpg" width="200"/>
<img src="https://user-images.githubusercontent.com/40247591/210004532-f882fd44-2f8e-42b9-89d0-4d74bd11893d.jpg" width="200"/>
<img src="https://user-images.githubusercontent.com/40247591/210004540-e47e4861-1c4f-4943-94a2-57af757cdaf3.jpg" width="200"/></p>

The example is this node: https://www.openstreetmap.org/node/1741133570

Only when zoomed in very far one will get a weird star, which is a little inconsistent to the rest of OSMand and also probably not very useful due to the high zoom require before it is displayed.

I thinks what would really make sense is something like this (proposal, own edit!):
<img src="https://user-images.githubusercontent.com/40247591/210005651-d8877f18-d297-4dc1-87a4-bf697a7f176d.jpg" width="300"/>
I took other sightseeing POIs as a model here.

Please note, that this is only relevant for tourism=attraction POIs that not already are displayed through a different POI, e.g. stemming from historic=ruins, or something like this. As I have laid out in the last issue already, there is a substantial amount of such standalone POIs relevant for users.

### How to reproduce?
Search "tourist attraction".
Select the generic "Tourist Attraction" category.
Zoom into one of the displayed POIs and turn off "POI overlay ...".

### Your Environment
OsmAnd Version: 4.3..3
Android/iOS version: Android 9
Device model: Samsung S8

**Comment by tradavyvy** [comment]
See also #16057
They are working on it.
Cherb has it as 4.4 back end now

**Comment by ceever** [comment]
No, that is a different issue! @ Devs, please note that.

I am not talking about the orange POI circles, but the regular POI circles that get displayed at certain zoom level. There is no such regular POI circle for standalone tourism=attraction nodes. See regular circles in the following screenshot:
<p>
<img src="https://user-images.githubusercontent.com/40247591/210105217-392b03ea-539a-4210-8f5d-ce3c4d604fde.jpg" width="300"/></p>

**Comment by xmd5a2** [comment]
Fixed
![Screenshot_2023-02-21_09-47-37](https://user-images.githubusercontent.com/5829014/220268684-04726085-9473-4a12-bb19-65703c498d30.png)

**Comment by Zirochkabila** [comment]
`50.44964, 30.54543`

OsmAnd~ 4.4.0#14194mqta, Released: 2023-02-22

<details><summary>Done</summary>
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/220600757-e82b7b48-7c7b-46db-b24d-4fc907b877d1.jpeg">
</details> 

22.02.23 master
<details><summary>Done</summary>
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/220601834-4add5aa8-800f-47d0-b32a-9ff06cfa05a4.png">
</details>

**Comment by ceever** [comment]
🤩
