### ISSUE TITLE
Duplicated information in the Map rendering FPS widget (Legacy)

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16107]
### Description
When navigating, the information in the Map rendering FPS widget is duplicated

### Steps to reproduce
Start navigation or Simulate navigation

### Actual result
Duplicated information in the Map rendering FPS widget

https://user-images.githubusercontent.com/104760013/210102543-5e1f0e82-2e5b-4eab-b035-9c47f7cedcb4.mp4

### Expected result
Information in the Map rendering FPS widget is displayed as when using OpenGL

https://user-images.githubusercontent.com/104760013/210102719-bf863c74-39b9-4b38-a367-b0a066a11733.mp4

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14064mqta, released: 2022-12-30
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by vshcherb** [comment]
As designed - legacy has 2 FPS indicators even if it's buggy it's less important for now
