### ISSUE TITLE
Use a decimal point instead of a decimal comma in GPX files

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd#16106]
# 🚀 feature request

### Description

Parsing the GPX was discovered, that (for German locale) extension osmand:bearing uses a decimal comma (274,1), while other fractional numbers (e.g., osmand:speed) use a decimal point. OsmAnd version 4.3.4 for Android 12.

### Describe the solution you'd like

Use a standardized approach (decimal point or comma – which is preferable) for all languages in GPX files

**Comment by sonora** [comment]
The [GPX 1.1 Schema](https://www.topografix.com/GPX/1/1/gpx.xsd)'s simple types `longitudeType`and `LatitudeType` have parent type `xsd:decimal` which is specified as `(\+|-)?([0-9]+(\.[0-9]*)?|\.[0-9]+)`, i.e. **the decimal separator is a dot**. `xsd:decimal` is also required for tags like `<ele>` or `<hdop>`.

If we use a locale-specific decimal separator, this is a bug.  (And quite possibly a regression.)

**Comment by tradavyvy** [comment]
Seems like a comparable problem to #14082

**Comment by vshcherb** [comment]
It looks like that's a developer request who used the code in locale specific environment, I guess developer could write here or submit pull request to fix it. So it doesn't go via support as a broken phone

**Comment by vshcherb** [comment]
@sonora we have a bug when user has a German locale so we use wrong format for ```osmand:bearing``` needs to be tested but going to submit a patch

**Comment by sonora** [comment]
@vshcherb Indeed, it was a bug, and it looks like it was only with the bearing value. Fixed now  I've just tested it, thank you!

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14074mqta, released: 2023-01-05
Done

<img width="907" alt="Screenshot 2023-01-05 at 11 37 53" src="https://user-images.githubusercontent.com/104760013/210748782-f9402419-5e45-46b5-8f3e-3e1f90b54a9b.png">
