### ISSUE TITLE
Favorites are bunched even on high zoom levels

### ISSUE THREAD

**Issue by DamianoPantani** [osmandapp/OsmAnd#16102]
# 🚀 Feature request

### DESCRIPTION

Hey, I noticed that along with recent major update, 2 things changed around favorites rendering (for performance reasons):
👍 Favs out of viewport are filtered out
👎 Densely packed favs are "grouped" even on high zoom levels, i.e. when diving deeper

### WHY IT MATTERS

It was kinda like that before, but now it's much more aggressive. And because of that, I need to zoom the map in to check if there are more things to visit in a given area, or there is just 1 pin dropped.

![image](https://user-images.githubusercontent.com/16529024/210079277-064ad564-30ad-4456-96d8-844e1e1e47f2.png)

### FEATURE REQUEST

Do we have a slider in the setting so we could customize the grouping "aggressiveness"? Or if not, could we have it anytime soon? I'd like to sacrifice a bit of extra performance, and ensure I never miss a beautiful spot!

Wish next year is your best one,
Damian.

**Comment by ceever** [comment]
I cannot reproduce that. For me it always shows overly many (also personal) POIs, also at widely varying zoom levels. Some are even displayed smaller to indicate the amount. See following screen:

<img src="https://user-images.githubusercontent.com/40247591/210108399-7b185334-de59-497f-8108-effd1390e204.jpg" width="300">


This has always been like it and I did not notice a difference coming to OSMand 4.3.3

🤷

**Comment by Zirochkabila** [comment]
@DamianoPantani The fact that at a lower zoom level fewer POIs are displayed is a predictable behavior. Otherwise, the map would be completely covered with POIs.
But, the idea with the slider for POI is interesting.

**Comment by DamianoPantani** [comment]
OK so when I set OpenGL version back to V1, I can see all my favourites, and all is how I expect it to be 😃 I think this ticket can be closed down, leaving it up to you

![Screenshot_20230408_192738_OsmAnd](https://user-images.githubusercontent.com/16529024/230736582-5b3ce543-7231-4821-b0c0-1234113ec161.jpg)
