### ISSUE TITLE
OsmandMapCreator and WMS as Source of tiles

### ISSUE THREAD

**Issue by mariush444** [osmandapp/OsmAnd#16108]
I downloaded the latest OMC 3.0 but it doesn't support {bbox} {q}? Just only zxy.
I can't define new source. The error msg. is "Please specify all placeholders {$x} {$y} {$z} in URL"
Could you update OMC?

**Comment by vshcherb** [comment]
OsmandMapCreator ? probably it's missing support - https://github.com/osmandapp/OsmAnd-tools/blob/master/java-tools/OsmAndMapCreator/src/main/java/net/osmand/swing/NewTileSourceDialog.java here. 

We provide only latest nightly builds for Map Creator without releases.

**Comment by mariush444** [comment]
I've moved issue to tools
