### ISSUE TITLE
incorrect display turn:lanes routing

### ISSUE THREAD

**Issue by Inyaheyukan** [osmandapp/Osmand#1610]
![screenshot_2015-08-22-16-23-39](https://cloud.githubusercontent.com/assets/4369755/9528994/069af920-4cf8-11e5-8ec9-0e1bbff68fc6.png)

There is a green arrow to the left. But the direction ist strait ahead.

It is in Berlin, Germany, Adlergestell / Rudower Chaussee

Software is OsmAnd+ 2.1.1 offline maps and offline routing.

**Comment by Inyaheyukan** [comment]
Another example
![screenshot_2015-09-06-14-50-44](https://cloud.githubusercontent.com/assets/4369755/9706370/514aa284-54e3-11e5-9335-47f3eaca10d5.png)

There is a green arrow to the right. But the direction ist strait ahead.

It is in Berlin, Germany, Alt-Mahlsdorf / Hultschiner Damm

Software is OsmAnd+ 2.1.1 offline maps and offline routing.

**Comment by klawdhfzasjhaa** [comment]
Hello,

I got a similar issue, even worse: In @Inyaheyukan's example the top left arrows are correct at least. Today I got this:
![screenshot_2015-09-27-08-48-052](https://cloud.githubusercontent.com/assets/2808094/10123683/8149d6fe-6540-11e5-9992-90b4920b75b1.jpg)

Also OsmAnd+ 2.1.1 offline maps and offline routing.

**Comment by utack** [comment]
First situation:
The road you are driving on has 4 lanes.
Two of these lanes go straigt ahead into a oneway
Two of these lanes go to the right into a oneway
Two lanes merge from the left oneway
Osmand error: you cannot turn left into a oneway, but one lane is shown that does

Third situation:
The road you are driving on has 3 lanes
Three lanes go straigt ahead
Two lanes go to the right 
Two lanes merge from the left oneway
Osmand error: Two lanes go straigt ahead, one goes straigt ahead and right, the last one is missing in the display

There must be some internal flaw in the logic that generates the middle lane picture.
@developers: Where is the code for that located?

**Comment by vshcherb** [comment]
1) and 2) http://www.openstreetmap.org/way/40191607 this road has 3 lanes, so OsmAnd is not able to detect whether 3 lanes from source road go straight or 2. The algorithm to detect which lanes go where is very tricky.

3) I think the map is outdated and it is not using turn:lanes at all, it is standard display of 2 lanes.

**Comment by utack** [comment]
Osmand is also technically correct in situation 1.
The "turn left lane" goes to the next road segment, after the one way street has merged, and can be used at the time where the screenshot was taken.

**Comment by hakuchi** [comment]
@Inyaheyukan in your first example it can be a problem with this part of street without turning lanes:
http://www.openstreetmap.org/way/318210359

in the second example I cant see any problem in the OSM data.

@vshcherb need OsmAnd "turnlanes:turns"relations to fix this problem?
https://www.youtube.com/watch?v=uF_ZuIwLruQ

**Comment by Inyaheyukan** [comment]
**Example 1:**
I think that this way *should not be a oneway* http://www.openstreetmap.org/way/40191608 . The wrong green arrrow shows against this oneway. It is possible to use this way in both directions. The one who wants to turn left must use this way. Should I delete oneway=yes?
But for me and osmand who wants in this case to go straigt on, is on this way with turn:lanes=left|through|through|right only the two lanes in the middle correct. It don't need a tricky algorithm. It is not important how many lanes are behind this point. If I wan't to go straight, the lanes with straight have to be green. Others not green.

**Comment by hakuchi** [comment]
I have tested with simulation(OsmAnd+ 2.1.1) some intersections with turn:lanes.
Now I think Osmand **need** [*turnlane:turns*] (http://wiki.openstreetmap.org/wiki/Relations/Proposed/turn_lanes#Plugin) to display correct green arrows.

Here some intersections with *turnlane:turns* on they the arrows from OsmAnd showing correct way and direction in green.
Easy intersection: http://www.openstreetmap.org/node/60405910
Complex intersection: http://www.openstreetmap.org/way/4694378

**Comment by Inyaheyukan** [comment]
![screenshot_2015-12-06-16-45-54](https://cloud.githubusercontent.com/assets/4369755/11614251/2c452896-9c3d-11e5-8a9b-5fba2e473c47.png)

The left arrow should not be green!
Berlin Greifswalder Straße / Ostseestraße,Michelangelostraße  north towards
Osmand+ 2.2.3 offline maps and offline routing.

**Comment by vshcherb** [comment]
Fixed
