### ISSUE TITLE
V4.3.5 no local backup anymore???

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#16109]
### Description

headline says it all.

### Your Environment
OsmAnd Version: +4.3.5
Android/iOS version:
Device model:

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by EugeneZmeuk** [comment]
You can use only  export/import for Profile now.

**Comment by Rowin63** [comment]
and how to backup my data?
my last online backup was a disaster, could not write data back to the obb-folder, was useless!?!

**Comment by scaidermern** [comment]
What about Settings / Export to file (at the bottom)?

**Comment by Rowin63** [comment]
Ok - you moved it to another place. It was at the backup section before.
Did not see this...

Thanks!

**Comment by Rowin63** [comment]
> You can use only export/import for Profile now.

not only for profile, fortunately

**Comment by Rowin63** [comment]
> What about Settings / Export to file (at the bottom)?

Danke, hatte ich nicht gesehen.
