### ISSUE TITLE
Osmand Cloud - Not sync - Jan 2021

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#16110]
### Description
Good morning and a happy new year.

Because of some issues  (like #16081) I wanted to start the new year with a fresh install of my Osmand +Version.
Before that, I did, about one hour ago, a complete online-backup (and deleting all previous online-files before, so all backup data has to be current) to the Osmand Cloud.

First step after the online-backup: uninstalling and reinstalling +V4.3.5
Next expected step: getting all my data back from this new online backup, but that remained a "pious hope".
Even the backup was created recently, the cloud now tells me, that the last sync was at Dec 27th. and with the additional information, that it "failed to fetch the file list from the server". Great.
 
### How to reproduce?
I dont know.

### Your Environment
OsmAnd Version: +4.3.5
Android/iOS version: 13
Device model: S20+ 5G

**Comment by Rowin63** [comment]
Tap on "sync now" does not trigger anything.
Tap on "delete all my data" in the settings does not trigger anything.

Still "last sync 27.Dez 2022" is diplayed and "failed to fetch filelist from the server".

**Comment by Zirochkabila** [comment]
Reproduction failed - all data that was uploaded to the Cloud was returned

**Comment by vshcherb** [comment]
OsmAnd Cloud is now under various of testing cause we suspect some corner case issues but we're not sure we can understand how to reproduce step by step

**Comment by Rowin63** [comment]
After restoring did not work, I wanted to delete all previous data for a new backup.
But I cant either sync nor delete my existing data at the moment.
Online seems no data present, the two blue lines (like the hourglass) are running and running and ...
I dont know how to continue in this situation.

**Comment by Rowin63** [comment]
> Reproduction failed - all data that was uploaded to the Cloud was returned

) I ran the last sync on January 1st., not on December 27th
) Since this last sync there is this error displayed (failed to fetch...)
) "Sync now" does not work, no reaction
) Under "settings" "delete all my data" does not seem to do anything

![Osmand online error](https://user-images.githubusercontent.com/95540936/210397723-ca9c9008-0258-4d22-89f1-af380c98113f.JPG)

**Comment by Rowin63** [comment]
I will leave OsmAnd Cloud aside a while.
After 2 tries disconnecting and logging in again I was able to delete the previous stored data and run a new backup.
But not all data was backed up, only a part of it. And syncing again does not change anything.

Having a working backup and above all a working (and real) SYNC TOOL (syncing devices) is my greatest wish to you.
This would be the functionality that makes me pay for a pro version.

**Comment by vshcherb** [comment]
Let's see in a month while we need to make important fixes and polish I observe quite a lot of smaller issues myself, so it needs to take time.

**Comment by vshcherb** [comment]
> "failed to fetch the file list from the server"

Do you have anything in log files (Logcat)?

**Comment by Rowin63** [comment]
> 

Sorry, no.
Since I did logoff and -on severaltimes, this message does not appear anymore.

Nevertheless thanks for your great work!

**Comment by Zirochkabila** [comment]
@Rowin63 Today, synchronization with Cloud was tested again on the [version](https://download.osmand.net/latest-night-build/OsmAnd-opengl-arm64-nightly.apk) - everything worked
Try to download and check again

**Comment by vshcherb** [comment]
@Rowin63 release 4.3.6 is in beta mode, please let us know if something doesn't work.

**Comment by Rowin63** [comment]
Hi!

In V4.3.6 I ran a sync but no restore yet.
Because the sum of tracks in the cloud seems not correct.
Local is around 1300 tracks, in the cloud "used space/my places"it is only 507 tracks.
I deleted all cloud data and ran a sync again, but it did not change.

**Comment by Zirochkabila** [comment]
@Rowin63 We have finalized some processes today - please check tomorrow night's version

**Comment by Rowin63** [comment]
Unfortunately I can´t install the nightly, I don´t know why.

1) Question: you want to actualize the app?
2) Message: App was not installed, because of a conflict with the existing package

![Nightly_1](https://user-images.githubusercontent.com/95540936/212536844-4355b8d3-996a-4bf0-9313-a46048773d06.JPG)
![Nightly_2](https://user-images.githubusercontent.com/95540936/212536853-0341dac7-90ab-4ef1-a5dc-da9635298cce.JPG)

**Comment by vshcherb** [comment]
You can only install release versions, offlicial nightly version is another one. https://download.osmand.net/latest-night-build/OsmAnd-default.apk
4.3.6 is already out

**Comment by Rowin63** [comment]
So what was it in the link provided 6 posts ago, the one I could not install?
Now I run this last linked nightly parallel to "my" 4.3.6.
It makes no difference, the amount of local tracks differs to the uploaded backup.

My local tracks is about 1300.
My local backup contains 594 tracks at restore.
My cloud backup shows 594 tracks (displayed in the app)
Restoring this backup (created in 4.3.6) to the nightly brings back 594 tracks.
The missing tracks are spread over all the foldes.

www.osmand.net/map/ is again not available right now, but the number of tracks shown there is always less than in the backup (last number I have seen was around 530).

Favourites are selected when creating the local backup, but no favourites are restored (there is no checkbox for restoring favourites). Creating a backup in 4.3.6 incl. favourites and restoring this backup to the last nightly brings back "0" from 1168 favourites. When restoring a "regular" version I dont know, because favorites are also backed up (and automatically restored at a new install) by Google.

I´m confused.

**Comment by Rowin63** [comment]
The last post is getting long. So here a new try:

Deleting all favourites and all tracks from the nightly.
Then ran a "my places"-backup in 4.3.6.
Then restored this backup in the nightly.

The result is (as you can see in the attached screenshots):
1168 favourites in the backup
1298 tracks in the backup
At the import in the nightly are no favourites available
After the import there are 0 favourites and 602 tracks restored.

![Screenshot_20230116_084956_OsmAnd+](https://user-images.githubusercontent.com/95540936/212627680-a015ebdf-e5f6-4db5-977e-d9460186a508.jpg)

![Screenshot_20230116_085106_OsmAnd+](https://user-images.githubusercontent.com/95540936/212627714-f12df7cd-bdb7-4e1b-8e0c-50c731e431c2.jpg)

![Screenshot_20230116_085401_OsmAnd Nightly](https://user-images.githubusercontent.com/95540936/212627787-7c5124bf-88a4-4cb1-ab3a-0142f5ec733d.jpg)

![Screenshot_20230116_085507_OsmAnd Nightly](https://user-images.githubusercontent.com/95540936/212627834-7dfd81c8-5065-451f-97d9-a3fe0087ef5a.jpg)

![Screenshot_20230116_085639_OsmAnd Nightly](https://user-images.githubusercontent.com/95540936/212627860-6f3e0ea9-48a4-48c7-bd16-8e9b9f06c49d.jpg)

**Comment by vshcherb** [comment]
> No restore possible from cloud to nightly (no button, only "sync") but 652 cloud changes and 84 conflicts (736 elements too).

Sync is same as restore if you sync it restores all 736 items .

It's not clear why you have ~1200 tracks but all backups displays only half of them ~600... My local backup 302 tracks is fully the same.

**Comment by Rowin63** [comment]
Ok. So a local backup is always importing and a cloud backup is always syncing.
I ran a sync and all (1168) favourites are back and 594 tracks. 
=> Syncing brings back what´s in a backup. But the backup itself is not complete.
 
As an example, the "rec"-folder never contains all tracks in a backup. It is always significantly less, about 35 out of 150.
But also small folders are not complete, like 8 out of 35 or 15 out of 20 and so on.
Almost no folder in the backup contains all it´s tracks.

Beside all this, the folders online (~40) are not and can´t be sorted in alphabetical order, they´re always completely mixed up (inside a folder there is an option for sorting the tracks, but not the folder list)

**Comment by Rowin63** [comment]
?

![Online Files](https://user-images.githubusercontent.com/95540936/212933809-22d03b5e-1192-4bd3-aa30-eafc5746b687.JPG)

**Comment by vshcherb** [comment]
Total files is not correct 1319 cause it includes info files (on web), so we will need to filter this out actually... So on web it doubles actual files (2nd file is metadata)

**Comment by Rowin63** [comment]
First, now I know why I couldn´t install the version mentioned a few posts before: the linked version is a "+"-version and can not be installed over/parallel to an existing official "+"-version. The second provided link is the "standard"-version, that´s why I could install it.

So I did de-install both versions (nigfhtly regular and my +), making a data backup before.
Then I could install the +nightly without problems.

Next was restoring alldata from the backup: 
NO favourites were restored. Favourites are still empty after restoring the backup. 
How to restore my favorites?

Unfortunately I dont have access to the data-folder (the nightly is installed in). The regular version is installed in the obb-folder, where I have access to.

Why this folder change obb to data?

**Comment by vshcherb** [comment]
It's strange what does it mean favorites were not restored? Have you seen them on https://test.osmand.net/map ? If you have seen that should be identically restored.

**Comment by Rowin63** [comment]
I forgot to mention, I did a local backup, not online. Since that confusing behaviour I don´t use online backup at the moment.
But I created a local backup including favorites. When restoring, no favorites were restored.
I´m not sure, what´s wrong, because this happened also at one of the previous online backups. Favorites were "not selectable" at resore. Are they in the backup alt all? They are selected when creating the backup, but perhaps they are not included though?

**Comment by Rowin63** [comment]
I just gave it a try again.
Creating a backup including only the favourites. (about 1200 favorites, the backup size is 60,7KB - is that possible?)
When restoring from this backup, I see just an empty screen, nothing to select.
That means, favourites are, though selected, not possible to restore from the backup. 
Either they are not backed up or they cant be restored.

**Comment by Rowin63** [comment]
backup.osf is a zipfile. renamed it to *.zip and opened it, it contains all the favourites.
So favourites are not resored at restoring.

**Comment by Rowin63** [comment]
And yes, I can see the favorites on  https://test.osmand.net/map.

**Comment by Rowin63** [comment]
> Why this folder change obb to data?

Sorry, my mistake. "data" is the external memory, "obb" the multi user memory".

**Comment by Rowin63** [comment]
Cloud: Track folders are not sorted (by name?) but mixed up and can not be sorted. Tracks in the folders can be sorted A-Z or Z-A.
Thanks!

**Comment by vshcherb** [comment]
You can click on cloud sorting there are buttons AZ / Time in Group (website)

**Comment by vshcherb** [comment]
Unfortunately as I see lowercase is not mixed with uppercase while sorting

**Comment by vshcherb** [comment]
Actually right there are no sorting for folders probably they are sorted by last added track inside them

**Comment by Rowin63** [comment]
Oh I see.
But would you agree, a sorting option (I use more tan 50 folders...) could be helpful...?

**Comment by Rowin63** [comment]
Ok, thanks ;-)
