### ISSUE TITLE
Coordinate search should retain the last used settings

### ISSUE THREAD

**Issue by Max1234-Ita** [osmandapp/OsmAnd#16114]
### Description
I'm searching for some places by their coordinates: I have a list where they are written in format DDD MM SS.sss.

When I open the Coordinate search panel, I see the default format set is _DD.DDDDD_, so I change it to _DD MM SS.S_ and type in the values for the first point, I confirm and the map is properly centered on the selected location.

When I get back to search for the second location, however, I see the coordinate format has switched back to _DDD.DDDDD_: I would expect to find it set to the format I chose previously, as this would speed up my search.

### How to reproduce?

1. Start OsmAnd and wait for current position to be fixed.
2. Open the menu _Search -> Address -> Coordinates search_
3. Note that Coordinates format field is set to _DD.DDDDD_
4. Set Coordinate format field to _DD MM SS.S_.
5. Type in the coordinates and confirm: the map is centered on the chosen location
6. Get back to menu _Search -> Address -> Coordinates search_
7. Note that Coordinates format field has been reset to _DD.DDDDD_ : DD MM SS.S (the same as the last search) would be expected as this would make it easier for the user to search for another spot. Setting should be retained at least until the app is closed.

### Your Environment
OsmAnd Version: OsmAnd+ v. 4.3.5
Android/iOS version:  Android 11
Device model: Samsung Galaxy A50 (SM-A505FN/DS)

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by Max1234-Ita** [comment]
Thank you so much! :)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14086mqta, released: 2023-01-11
Done
