### ISSUE TITLE
POI custom search edits produce erroneous 'Apply to all profiles' dialogue box

### ISSUE THREAD

**Issue by mikehgentry** [osmandapp/OsmAnd#16117]
### Description

POI custom search edits apply to all profiles. But when you edit one, you are given the 'Apply to all profiles?' dialogue box anyway.

### How to reproduce?

Search -> Categories -> Custom Search

Add some things

Apply -> Show -> Save

Give it a name, then exit the menu, and switch to another profile.

Search -> Categories

Your new category will appear in this list, i.e. they're not profile specific.

Categories -> Rearrange categories

Do something like move the category or delete it. You will be given the "Apply to all profiles?" popup. If you ignore it, the edit is applied to all profiles anyway.

There seems to be something else broken here - the ordering of things when you choose 'Rearrange categories' isn't always the same as the actual displayed ordering.

### Your Environment
OsmAnd Version: 4.3.5
Android/iOS version: 11
Device model: Xcover 4s

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14069mqta, released: 2023-01-03
Reproduced


https://user-images.githubusercontent.com/104760013/210354133-289fc499-b954-45c0-8376-731afd8da9d0.mp4

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14082mqta, released: 2023-01-09
Done
