### ISSUE TITLE
Unable to set Display position to Center

### ISSUE THREAD

**Issue by seahorse41** [osmandapp/OsmAnd#16112]
### Description
After upgrading from 4.2.7 to 4.3.3 the Center is now at the bottom. Researching the new features I find in Configure profile, Browse map, General settings, Display position is already set to center.

After much toggling of settings, changing rendering engine from 1 to 2, and Setting driving to bottom, while leaving browsing and walking set to center,
I finally got it to switch back to center one time by switching profiles.
But on next load, it was back to the bottom, and the earlier trick no longer works.
I also tried setting Center to all profiles, but radius ruler is still at the bottom.

Switching profiles with different Display position does not change that setting on the map/screen.

### How to reproduce?
I'll list the settings, and any differences between the 3 profiles I have turned on:
Browse map: Dark, Fixed north up, 2.5D off, Center, Same as device
Driving profile: 2.5D on, Bottom
Walking profile: Center
Then tap the upper left profile icon to switch profiles. Check if the center changes also.

### Your Environment
OsmAnd Version: 4.3.3
Android/iOS version: 7.1.2
Device model: LG-H932

**Maps used (online or offline):**   Offline
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by seahorse41** [comment]
Also tested with Android version 10.3.12 on OnePlus 6T A6013 and result: The Display position sticks to the screen center, and when changing profile to driving does not move Display position to the bottom.

**Comment by Zirochkabila** [comment]
OsmAnd 4.3.5, released: 2022-12-29
OsmAnd~ 4.4.0#14069mqta, released: 2023-01-03

Not Reproduced
Try to reinstall OsmAnd app (please make a backup before: Menu > Settings > Export to file) and try one more time


https://user-images.githubusercontent.com/104760013/210350013-e87cf3d3-0a4e-4a73-8eee-bde34a7c0f28.mp4

**Comment by seahorse41** [comment]
Fixed in 4.3.5
Thank you.

**Comment by seahorse41** [comment]
Just installed 4.3.5 on a third device, It is stuck at the bottom again. I opened settings for browse, verified it is set to center, selected center again, applied to all.
Then went to driving, and set it to bottom. Back out to the map.
The center rings are at the bottom, I tapped the upper left, just like in your video, selected driving, then back to browse. It is stuck at the bottom (again).

**Comment by vshcherb** [comment]
Watched the video but definetely can't reproduce, please send another video where you set it to center and it's applied. On your video once you open settings and check center and back to browse map on 3rd second it wasn't center! So it looks like center never applied

**Comment by seahorse41** [comment]
> please send another video where you set it to center and it's applied. 

I would IF I could... 
After seeing your request, I came back to it after it has been sleeping 7 hours, The position moved to the center on it's own, and that applied to all 3 profiles somehow. 
In settings it shows a different position that I requested, but all are drawn in the center now.
Now I can't move it from the center. I did make more videos attempting to change the position, but I can not get it to change once.
I'm out of ideas to try.

**Comment by seahorse41** [comment]
I revisited the other 2 devices, that I had working yesterday. Today they are both stuck in the center, and are not moving. I checked and verified version 4.3.5.

**Comment by sonora** [comment]
Cannot reproduce either. I notice you have the out-of-the-box bicycle profile disabled, and on some profiles you have radius ruler on and some kind of over-/underlay, but I cannot currently imagine how that would cause such an issue.

I have, however, while testing noticed that we have something irreversible going on (#16157), so maybe it has to do with in which order you have changed yor settings after the fresh install. I suppose you always immediately worked with setting "Display position" from the start, not with "Map orientation"?

**Comment by seahorse41** [comment]
> I suppose you always immediately worked with setting "Display position" from the start, not with "Map orientation"?

Correct, my map orientation has always been north up. Since the first thing I noticed that changed was the center of the map in browse profile, that was the first thing I hunted around to change.

Only with the new rendering engine with tilt, does it make sense to move the center to the bottom when in motion. For me that is only in driving mode when it is navigating to a destination.

**Comment by sonora** [comment]
@seahorse41 Sounds to me like you are experiencing https://github.com/osmandapp/OsmAnd/issues/16157. If so, it should be fixed, but probably not in release versions 4.3.x.

(To verify: When you go to `Menu > Configure profile > Position placement` (or perhaps:  `... > Display position`), I guess you see a two-option (_Center / Bottom_) and not a 3-option dialog (_Automatic / Center / Bottom_)?

@vshcherb I guess we may have to merge https://github.com/osmandapp/OsmAnd/pull/16267 back to branch r4.3. Related: Probably about time we merge https://github.com/osmandapp/OsmAnd/pull/16329?

**Comment by vshcherb** [comment]
Nope 4.3 is frozen just for critical issues such as Android Auto or serious regressions.

4.4 should be already available in beta this week but since we didn't get approved android auto yet, 4.3 is ongoing. 

Closing as it fixed.

**Comment by seahorse41** [comment]
> (To verify: When you go to `Menu > Configure profile > Position placement` (or perhaps: `... > Display position`), I guess you see a two-option (_Center / Bottom_) and not a 3-option dialog (_Automatic / Center / Bottom_)?

Correct.
Also I can now confirm that on multiple devices, the action to Force kill and restart after upgrade, does fix this reported bug.
