### ISSUE TITLE
penalty loop?

### ISSUE THREAD

**Issue by Inyaheyukan** [osmandapp/Osmand#1611]
![screenshot_2015-08-17-20-01-12](https://cloud.githubusercontent.com/assets/4369755/9530642/62a7fb2e-4d01-11e5-8a1a-1fe838609c7f.png)

What is this for a loop? I have to go straigt on.

It is in Berlin, Germany, Heerstraße / Gatower Straße

Software is OsmAnd+ 2.1.1 offline maps and offline routing.

**Comment by vshcherb** [comment]
The issue is not reproducible
