### ISSUE TITLE
Offline tiles not always loading

### ISSUE THREAD

**Issue by seahorse41** [osmandapp/OsmAnd#16113]
### Description
After upgrading from 4.2.7 to 4.3.3 the tiles at zoom level 19 no longer load.

Also instead of loading lower res maps, some of the tiles load and some don't. The ones that don't show a X in a circle.
Sometimes lower zoom levels also do not load, like when zooming out.

### How to reproduce?
Zoom in, tiles saved in the tiles directory that used to load fine, only load down to zoom level 17 now.

### Your Environment
OsmAnd Version: 4.3.3
Android/iOS version: 10.3.12 and 7.1.2
Device model: OnePlus and LG both

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
Only tested with offline maps.

This shows aerial tiles, top is showing level 17, bottom didn't load any tile. Zoom level is high enough level 19 should load.
![20230101-091055_L_osmand-4 3 3_fresh-start-not-loading-all-tiles](https://user-images.githubusercontent.com/14300304/210179895-a1606b76-81e2-4701-8570-367c279f5a3a.jpg)
I don't have level 18, Saves memory, and the snap lets me know what zoom level I'm at.
I will have to test further.

Here is zoom out.
![20230101-090013_L_osmand-4 3 3_zoom-out-not-loading-tiles](https://user-images.githubusercontent.com/14300304/210179979-475e10ec-212c-4c98-87c8-85ce377c7a9e.jpg)

Next is after zoom in, you can see tiles at level 17 did load, but every time I press Back... this is happening on the LG H932 only:
![20230101-091407_L_osmand-4 3 3_crash-on-exit](https://user-images.githubusercontent.com/14300304/210180009-90b6c006-073e-4294-8607-392e128a100d.jpg)

**Comment by seahorse41** [comment]
I solved the primary problem. There was no ..metainfo file and so the default max_zoom now defaults to 18. That was my bad.

It still fails to load tiles sometimes, and panning finally resets that cache if I pan far enough away.
So I'm editing the title.

Perhaps I can make an assumption, until it happens again, that the upgrade did not completely clean up the various layers being loaded, and that caused the repeatable crashing at exit.
I have not seen any limit on the number of gpx tracks it can show, only a speed slowdown.

Is there any place to see statistics on memory usage?

**Comment by TheSnoozer** [comment]
Maybe related to https://github.com/osmandapp/OsmAnd/issues/16098 ?

What map rendering engine do you currently use? Does the situation change if you switch to map rendering V1 instead of V2 (OpenGL)? This setting can be found in Menu → Settings → OsmAnd settings

**Comment by seahorse41** [comment]
> What map rendering engine do you currently use? Does the situation change if you switch to map rendering V1 instead of V2 (OpenGL)? This setting can be found in Menu → Settings → OsmAnd settings

It was set to V2.
I zoomed in, then out so I could see the empty X in a circle for the tiles not loaded.
Changed to V1
Now the zoom out button does nothing. Is frozen.
Can not drag or pan
I'll force close and restart.
Tiles now load as before.

**Comment by seahorse41** [comment]
> Maybe related to #16098 ?

Yes it has always been sluggish on this particular LG model/device but not on the others. That unsolved problem also affects other apps, and so has not been complained about here.

**Comment by seahorse41** [comment]
The zoom levels showing the failure to load, are when those specific tiles are not available/present. Before rendering engine V2 it would load the zoom level above and scale it to fit, which was acceptable and intentional in leaving some levels without files for offline use.

**Comment by vshcherb** [comment]
We're collecting crasehs for v2 and investigate them, meanwhile you switch back to use rendering v1 in OsmAnd Settings and see how it goes later with next releases
