### ISSUE TITLE
Don't automatically rename custom multi-POI quick action

### ISSUE THREAD

**Issue by mikehgentry** [osmandapp/OsmAnd#16116]
### Description

User added name for custom multi-category POI search in Quick Actions is automatically overwritten whenever a POI category is added / removed - a minor annoyance, but still shouldn't happen I think.

### How to reproduce?

1) Go to Quick Action -> Add action -> Show / hide POI

2) Pick something.

3) Type in a new Action Name.

Doesn't matter whether you close the menu at this point and re-enter it later.

4) Add another POI category.

The action is renamed to "\<first POI category\> +1"

### Your Environment
OsmAnd Version:  4.3.5
Android/iOS version: 11
Device model: XCover 4s

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14069mqta, released: 2023-01-03
Reproduced


https://user-images.githubusercontent.com/104760013/210351536-e3fef4c5-bf65-4306-8f66-25742b0c7f69.mp4

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14082mqta, released: 2023-01-09
Done
