### ISSUE TITLE
Power=generator are badly rendered when in a multipolygon tag

### ISSUE THREAD

**Issue by letypequividelespoubelles** [osmandapp/OsmAnd#16126]
### Description
Power=generator are badly rendered when in a multipolygon tag, and not possible to click on the generator icon.

### Your Environment
OsmAnd Version: FDroid, 4.3.3 , same with engine 1 and OpenGL
Android/iOS version:
Device model:

**Maps used (online or offline):**   
offline

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14164mqta, Released: 2023-02-09
`49.28493, 11.4222`

[Map](https://drive.google.com/file/d/1y6orl3z20fOCtnPGUNqLSLcySuODbzr1/view?usp=sharing)

[OSM](https://www.openstreetmap.org/relation/7614307#map=17/49.28514/11.42380)

<details><summary>Overpass</summary>
<img width="700" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/218263339-63535efb-2e52-4f7e-b54b-016e39b406fe.png">
</details>


https://user-images.githubusercontent.com/104760013/218263447-c4e3d72c-a492-46b0-a91e-b66975bb0bbb.mp4

**Comment by xmd5a2** [comment]
Looks like this is an UI issue. Power generators are rendered correctly.
![Screenshot_2023-03-03-11-33-33-195_net osmand plus](https://user-images.githubusercontent.com/5829014/222674431-84c6d81c-5248-4ff6-ba32-0ccf15172ca0.jpg)

**Comment by vshcherb** [comment]
Bug not selected occurs cause context menu searches POI in a small radius 50 m cause there is 1 POI for relation but we have 3 separate icon (buildings) which are located > 100 m

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-resources/commit/c607a9717bc5e53aa4533221bbcdcd920b655aca https://github.com/osmandapp/OsmAnd/issues/13555

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#14270mqta, Released: 2023-03-25
4.4.6.11
It is possible to select a generator in the polygon
But

- Icon is displayed only with More details enabled
- Generator address is displayed only on Android

**Comment by xmd5a2** [comment]
> [osmandapp/OsmAnd-resources@c607a97](https://github.com/osmandapp/OsmAnd-resources/commit/c607a9717bc5e53aa4533221bbcdcd920b655aca) #13555

@Zirochkabila please read comment from @vshcherb

**Comment by Chumva** [comment]
Duplicate - https://github.com/osmandapp/OsmAnd/issues/16813
