### ISSUE TITLE
Copy point name to clipboard by long tap

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#16129]
We can copy POI name by long tap on it, currently it can be done only by taping on Share > Copy POI name, or by opening Details for some types of POI that show the same info in Details.

## To Do
- [ ]  Taping on point name should copy the text to clipboard.
- - [ ]  Add support for all points type: POI, favorites, waypoints etc.
- - [ ]  Show toast with copied text.

<table style="width:100%">
  <tr>
    <th>Custom point</th>
    <th>POI</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/210365784-1bb377e5-3f09-4ca7-a3fe-86f8df3c5d59.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/210365788-8557ef0e-9cf4-408b-a66f-d1423f00378e.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by ceever** [comment]
Btw. If you already going into that direction, being able to also copy the address this way would be very helpful 👍

**Comment by luigifab** [comment]
yes please! same demand for me, please allow copy by long tap on "Kalverstraat 185, Amsterdam" and "The leather club" and "Shoe store, Kalverstraat 185, Amsterdam" from previous screenshots.

**Comment by dmpr0** [comment]
> yes please! same demand for me, please allow copy by long tap on "Kalverstraat 185, Amsterdam" and "The leather club" and "Shoe store, Kalverstraat 185, Amsterdam" from previous screenshots.

Taping Share button in context menu will open OsmAnd share sheet, for Android 14 and above system share sheet with separate button for copying POI name, address or coordinates.

**Comment by luigifab** [comment]
Android 14? I'm still waiting an update from 11 to 12!
