### ISSUE TITLE
Crash after track sharing

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#16123]
When I share any track from My Places menu by way  "Menu - My places - Tracks - choosing any track and "three dots" button - Share", 
OsmAnd crashes at once.

![photo_2023-01-03_10-05-04](https://user-images.githubusercontent.com/44466116/210327200-8042b4a8-c92b-413e-80a8-36fda94c97fc.jpg)

Device : beyond0
Brand : samsung
Model : SM-G970F
Product : beyond0ltexx
Build : SP1A.210812.016.G970FXXUGHVJ5
Version : 12
App Version : OsmAnd~
Apk Version : 4.4.0#14068mqta 4400

[exception (1) (12).log](https://github.com/osmandapp/OsmAnd/files/10335293/exception.1.12.log)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14069mqta, released: 2023-01-03
Not Reproduce

**Comment by EugeneZmeuk** [comment]
Reproduce for me again

Device : beyond0
Brand : samsung
Model : SM-G970F
Product : beyond0ltexx
Build : SP1A.210812.016.G970FXXUGHVJ5
Version : 12
App Version : OsmAnd~
Apk Version : 4.4.0#14070mqta 4400

[exception (1) (14).log](https://github.com/osmandapp/OsmAnd/files/10338605/exception.1.14.log)
70mqta 4400

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14074mqta, released: 2023-01-05
Done
@EugeneZmeuk can you check it?
