### ISSUE TITLE
Hebrew localisation don't work

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#16124]
* Start **OsmAnd**
* Open **Menu** – **Settings** – **OsmAnd Settings** – **Display language**
* Select **Hebrew**, restart app
* After relaunch, app will use first language from system list
* Trying to put **Hebrew** as first language doesn't make any effect.

<table style="width:100%">
  <tr>
    <th>4.2.5</th>
    <th colspan=2>4.4.0</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/210332743-d84639b6-bcca-4f67-b4fb-1073aa7c7c5f.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/210332873-80093f35-a7f2-4cb3-a047-ace34ab53032.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/210332876-23a9dbaf-4465-4f74-8dbc-06e82a70b333.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/res/values-he/strings.xml

https://github.com/osmandapp/OsmAnd/issues/8042

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14074mqta, released: 2023-01-05
Done

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/210751082-7b46ff57-76ef-482c-a683-d56e1af1b656.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>
