### ISSUE TITLE
Empty coordinates widget if CH1903 or CH1903+ is used

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#16125]
## How to reproduce
* Change coordinates format to **CH1903** or **CH1903+** in **Menu** – **Settings** – **Profile** – **General settings** – **Coordinate format**
* Open **Menu** – **Configure Screen** – **Top panel** – **Available widget** – **Coordinates widget** – Add both
* Go back to map screen, widgets will be empty.

Tested on 4.4.0 nightly builds.
<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/210337340-d6e0743f-1268-4836-9d7a-d51076ec215c.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/210337344-8a1f016e-c055-43a2-8537-917f9eb29ae1.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14086mqta, released: 2023-01-11
Done
