### ISSUE TITLE
OpenGL: Minor rendering errors for roads

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#16135]
With OpenGL enabled there are minor rendering errors for roads, especially for motorway:

51.03705,13.61845
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/1040784/210431099-b3dbe85d-8992-4924-8b9c-aabdf7e56bd4.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

With the touring style they are more prominent:
51.03873,13.61277
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/1040784/210431172-e787d05a-e6cb-4c88-ba88-f57b9f245818.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

Also occurs for other road types:
50.98727,13.71508
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/1040784/210432328-63097f9a-ee2b-496e-b74b-9c6caa90d2b9.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

These errors don't occur with rendering engine v1.

OsmAnd 4.3.5, Android 10.

**Comment by vshcherb** [comment]
Yes it's a known issue with tile rendering

**Comment by d4f5409d** [comment]
Yes I do experience that
