### ISSUE TITLE
[Feature request] Export / Import for settings and favorites

### ISSUE THREAD

**Issue by klawdhfzasjhaa** [osmandapp/Osmand#1613]
This would be nice, if you move from one device to another or to make a backup of the current setup.

**Comment by vshcherb** [comment]
Favorites are exportable just from the screen of Favorites. For settings it is recommended to use Backup programs.

**Comment by klawdhfzasjhaa** [comment]
Thanks for the suggestion. I'll share for anyone who stumbles across:

Backup: adb backup -f osm.ab net.osmand.plus -apk
Restore: adb restore osm.ab

USB Debbugging and ADB drivers are necessary.

For the favorites only part: Problem is, that I cannot see the floppy disk icon:
![screenshot_2015-08-31-22-03-33](https://cloud.githubusercontent.com/assets/2808094/9589142/9f105326-502c-11e5-99d9-67afbb5d3cd6.png)
I followed the instructions on http://osmand.net/help-online?id=HowToArticles ("export the favorites"). When using the share button, "saving to local sd card" or something similar is not available. I'm using version 2.1.1.

**Comment by klawdhfzasjhaa** [comment]
Sorry @vshcherb : Could you please give me a hint? Where can I find the option to save the favs in the above screen?

**Comment by vshcherb** [comment]
Share is saving favorites

**Comment by klawdhfzasjhaa** [comment]
The menu does not contain a "save to file" option (Bluetooth does not work). Even if it would, there is no (easy) way to import back..

**Comment by vshcherb** [comment]
There is a share button click it and send by email, then opening that file on a target device will import favorites.

**Comment by frankgerhardt** [comment]
So, there is no Save icon. The Share button only shows SMS/MMS, Bluetooth, Firefox and a Podcast player. This is a real problem. 

I had to find the the favorites.gpx file somewhere in the file system under Android/data/net.osmand.plus/files and copy it manually to my PC.

**Comment by vshcherb** [comment]
Just send via Email or Dropbox or some File Explorers also support that intent

**Comment by frankgerhardt** [comment]
Again, neither Dropbox nor Email nor file explorers are offered in the share menu.

**Comment by klawdhfzasjhaa** [comment]
On my device (Nexus 4 with CM 12.1 / Android 5.1.1) I do have Dropbox and E-Mail (K-9 Mail) in the share menu, but I would like to save it offline as it contains sensitive data.
Frank's problem is a seperate issue it seems.

**Comment by tomspur** [comment]
Would it be possible to use the Android Backup Service? This way the backup would work automatically, if the Android Backup Service is enabled on the phone.

**Comment by skeeve42** [comment]
It would be nice if this were easier/automated. I know this is my fault for not properly backing them up, but I've lost my favorites twice now.

**Comment by samtuke** [comment]
Sharing the file works for me, but I'm not sure how to import it in the second device. Only file managers are suggested as file handlers for the .gpx file.

**Comment by vshcherb** [comment]
It depends which program do you open from. If you open a file from file manager, OsmAnd will be one of the option.

**Comment by mjg** [comment]
In case anyone else is wondering:

- Astro File manager **does not** offer to open a gpx with OsmAnd+ (but others), nor does the Google Drive app.
- ES File Explorer **does** offer to open a gpx with OsmAnd+ (and others).

I have no idea how an app like OsmAnd+ could be "partially" registered as a consumer for gpx.

**Comment by sonora** [comment]
Some portions deprecated. No more immediate action planned, I guess.

**Comment by grafa** [comment]
Just ran into the same problem. How do I transfer all my places from old phone to the new one?

**Comment by tomspur** [comment]
Is it also possible to back the favorites up with your Google account and use it in the other phone?

**Comment by sonora** [comment]
I guess you could just sync favourites.gpx to any cloud storage, from where it can be re-imported elsewhere...

**Comment by grafa** [comment]
maybe for those non technical guys there could be 2 buttons like "export favourites" and "import favourites"

**Comment by tomspur** [comment]
Sounds like the Android Backup Service might also be a possibility:
https://developer.android.com/guide/topics/data/keyvaluebackup#Files

**Comment by doriangrosch** [comment]
With Android 11, the location of the OsmAnd folder containing favourites.gpx is no longer easily accessible. So a feature to export / import favourites becomes relevant again. Has anything changed since?
