### ISSUE TITLE
Not possible to import OSF file

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#16141]
I can't open (import) this OSF file for Android version of OsmAnd (version 4.2.7 and version  4.4.0#14070mqta 4400)
[Export_21-12-22.zip](https://github.com/osmandapp/OsmAnd/files/10342465/Export_21-12-22.zip)

But for iOS version of OsmAnd, I can import it:

![image](https://user-images.githubusercontent.com/44466116/210513149-84840de8-32be-47fb-bdbe-1290b6780220.png)

Device : beyond0
Brand : samsung
Model : SM-G970F
Product : beyond0ltexx
Build : SP1A.210812.016.G970FXXUGHVJ5
Version : 12
App Version : OsmAnd~
Apk Version : 4.4.0#14070mqta 4400

[Export_21-12-22.zip](https://github.com/osmandapp/OsmAnd/files/10342465/Export_21-12-22.zip)

**Comment by EugeneZmeuk** [comment]
Yes, Sonora is right. looks like a broken file. I checked the tracks folder in the iOS version, but they are not in Mya Places - Tracks folder. They were not imported. 
Also, it is not possible to unzip the file on Windows.

**Comment by vshcherb** [comment]
Yes it could be an option to double check but in most of the cases broken backup is still a valuable backup

**Comment by sonora** [comment]
Certainly true. But also: The fact that a backup is broken must not go unnoticed upon creation...?

**Comment by llahteinen** [comment]
I have a case here, can't import an .osf backup that contains tracks, created using Android osmand v4.8.6 and imported to another Android phone with same version. The Import file picker just disappears and goes back to Settings menu, no error messages, nothing. Importing other settings works when not including tracks on the export.

I tried to reproduce using a third phone with same version, but way less gpx tracks and got the same result.

The export list shows 0 points for all tracks, don't know how it should be.
Also btw the export tracks menu titlebar says "Select items that will be _imported_"

![Screenshot_20240924_010617_OsmAnd+](https://github.com/user-attachments/assets/736445c1-f020-48fb-afb0-78653284c301)
[Osmand_backup.zip](https://github.com/user-attachments/files/17105098/Osmand_backup.zip)

**Comment by alex-osm** [comment]
Fixed - https://github.com/osmandapp/OsmAnd/commit/f643b7ae751de5c6bf603b867440438d902e3e55
