### ISSUE TITLE
Weird anomaly in the Contour lines addon near Pécs, Hungary

### ISSUE THREAD

**Issue by d4f5409d** [osmandapp/OsmAnd#16148]
### Description
There is a grey line across the map, where there shouldn't be on purpose.

### How to reproduce?
Activate Contour lines addon in Hungary and check it yourself.

### Your Environment
OsmAnd Version: 4.3.5
Android/iOS version: Android 12
Device model: 1+ 8

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
Both

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/76624594/210554630-1b99ce07-19bd-4a0f-837a-ef6356573139.jpg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/76624594/210554642-8cea85b4-3c66-46fc-99a8-05d7dbd107ba.jpg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/76624594/210554660-f1fc3df8-c7cd-4164-8c2d-b389acf5bc34.jpg"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by xmd5a2** [comment]
Fixed. Please download maps again.

**Comment by d4f5409d** [comment]
Thank you, very cool!

**Comment by dmpr0** [comment]
## Review
Maps downloaded 6.03.2023
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/223098293-4cbd1c80-d7a0-491d-872a-c9da3b170bf4.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/223098306-efb5b8d9-dbf0-4ba4-96de-db4c3daaceaa.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/223098314-d83abb27-7053-4e37-8558-e18935645fa5.png"  width="300" height="auto"/> </td>
   <td><img src="https://user-images.githubusercontent.com/9365308/223098321-2e9290f1-114d-457d-9ad0-894f8a7cbb91.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by xmd5a2** [comment]
@dmpr0 Place at 4-th screenshot is fixed. Please retest. Place at screenshots on 1-3 is not easy to fix because we use different sources of terrain data. Some of them are good in one place, others in another. However this can be fixed with upcoming "on-the-fly" hillshade.
