### ISSUE TITLE
Lower-resolution Tiles Not Scaled When Online

### ISSUE THREAD

**Issue by Dollarius** [osmandapp/OsmAnd#16140]
Missing tiles disappear ONLY when online as OsmAnd tries to load higher resolution ones.

### Description
Before heading outdoors, I always pre-cache Strava heatmap overlay tiles (https://anygis.ru/Web/Html/Osmand_en) so that I can navigate unmarked trails without phone signal.
It often happens that I pre-cache high-resolution tiles for an area, but NOT some neighbouring tiles.

Referring to the following video:
1. When I am in offline (flight mode), OsmAnd correctly rescales the missing tiles (top right, bottom right, bottom left)
2. When I am online (poor Internet connection), only the high-resolution tile (top left) is shown, while the other 3 are NOT rescaled but disappear. This happens because OsmAnd tries to download the higher-resolution tiles, but it cannot (poor connection). **Rescaled tiles should remain visible while the download is attempted**.
3. Going back to flight mode, all tiles are visible again (the low-resolution tiles are correctly rescaled)

https://user-images.githubusercontent.com/56419637/210502994-b7472394-e250-4870-8bc3-d45b5c5020c5.mp4

### How to reproduce?
I already reported this issue (https://github.com/osmandapp/OsmAnd/issues/14319), but developers were unable to reproduce it, so let me give clear steps:

1. Enable internet connection on the phone
2. Setup overlay tiles of Strava heatmap (https://anygis.ru/Web/Html/Osmand_en) in SQLiteDB format
3. Enable the overlay and zoom in/out onto an area to physically cache the tiles on the phone
4. To simulate a "poor network connection", change the tile sourcing link (so that new tiles cannot be downloaded) under DownloadMaps/Local/=Overlay=Strava/Edit/URL:"http://wrong.link.com"
5. Zoom Out/In and Pan the map to found the edge of the locally cached tiles so that a high-resolution tile borders other low-resolution tiles.
6. Observe the low-resolution tiles disappear upon zooming (as in my video above)
7. Set the phone to Offline mode
8. Observe the low-resolution tile RESCALE correctly (as in my video above)

### Your Environment
OsmAnd Version: Android full nightly 2023/01/04
Android/iOS version: Android 12
Device model: Samsung Galaxy S20FE
Engine: both v1 and v2 (OpenGL)

**Maps used (online or offline):**   
I am using Strava heatmap, but the issue happens with any tiles.

**Comment by sonora** [comment]
I think the issue is in this code:
https://github.com/osmandapp/OsmAnd/blob/073e4c1db1a6bbf495d700f11d971d7cccaa8418/OsmAnd/src/net/osmand/plus/views/layers/MapTileLayer.java#L372-L377

Downloading always takes priority over displaying an upscaled tile, and if a download seems possible, no upscaled tile is displayed (unless it is the maxLevel anyway).

**Comment by vshcherb** [comment]
@sonora you found the code https://github.com/osmandapp/OsmAnd/blob/073e4c1db1a6bbf495d700f11d971d7cccaa8418/OsmAnd/src/net/osmand/plus/views/layers/MapTileLayer.java#L319 that's related to rendering version v1, and that's not our goal to fix cause on the video it's opengl rendering

**Comment by sonora** [comment]
Ah, ok, but the issue is present in both v1 and v2, and very likely any fix would be the same for both.

Question is what strategy to apply here: Always showing an upscaled tile even if a download is ongoig async sounds like waste.We used to have a manual "Do not use Internet" switch in the tile map plugin which inhibited online refreshs, which would solve this. But I guess we have removed it at some point.

**Comment by Hello1024** [comment]
Note that osmand seems to have support for rendering *partially downloaded* tiles.   That means you now have to decide if it is better to render a partially downloaded tile or an upscaled tile, or to try to overlay them somehow.


A partially downloaded tile is usually just the top half of a tile, but I guess in some cases (eg. a progressively encoded jpeg) might actually be a blurry version of the final image.

**Comment by vshcherb** [comment]
This bug looks like already fixed and needs to be retested probably it was fixed together with https://github.com/osmandapp/OsmAnd/issues/14319
