### ISSUE TITLE
Values uphill/downhill doesn't correspond Elevation Widget

### ISSUE THREAD

**Issue by Dollarius** [osmandapp/OsmAnd#16145]
# 🚀 feature request
### Description
I absolutely love the new Elevation Widget, which is a great aid for riding bicycles with OsmAnd.
In the present version, I find the following 3 problems:

1. When the navigation is started, the current position starts from 0% of the x-axis (then gradually moving to 20%). This makes it impossible to read the y-axis labels (covered by the position marker) and to see the first part of the graph (covered by the y-axis labels).
2. The values shown on the y-axis are quite random and not so useful
3. The values of uphill (climbing) and downhill (descending) integrate the altitude data from the gpx route shown in the graph, but are often meaningless because the gpx altitude is rough.

![image](https://user-images.githubusercontent.com/56419637/210536413-715490fd-ddf4-4c66-ac38-d559829e4f82.png)

### Describe the solution you'd like

Referring to the problems above, I suggest the following improvements:

1. Fix the current position at 20% of the x-axis, even when the navigation is started, so that all labels/current-position-graph are always visible. Data before km0 can be white (so that the first 20% of the widget graph would be empty when starting navigation)

2. Show on the y-axis labels for the highest and lowest points of the graph. These are usually the most important points (summit/lowest-point) that one wants to quantify.

3. Solution for this is more tricky.
Ideally, you could use a function for detecting peaks (p0, p1, p2, etc) and valleys (v0, v1, v2, etc.) in the graph, then calculate
- "current uphill" as vertical distance between current elevation and next peak
- "current downhill" as vertical distance between current elevation and next valley
In the most ideal case, you could detect if p0_x < v0_x (currently climbing or descending?) and show
- "current climb" as horizontal distance to the next peak (i.e., 2km remaining)
- "current descent" as horizontal distance to the next valley
Whether to show information for climbing or for descending could be changed according to the current position.

4. Peaks and valleys could be indicated on the graph with a dot, and maybe with a label indicating the peak/valley elevation

5. When navigating with a gpx, the graph x-axis could display the distance of the gpx (i.e., 98.5km in the example above) instead of starting from 0km.

**Comment by Zirochkabila** [comment]
The first point should be corrected, as it really hinders
As for the second and third points, it's quite subjective. However, we can make the display of these indicators functional

**Comment by Dollarius** [comment]
@Zirochkabila I may add that the navigation often restarts from "km 0" when the phone screen is turned off for some time (more than 10min?). So point 1. would be an important improvement for something occurring rather often.

**Comment by daanasma** [comment]
+1 for the first remark, thank you for thoroughly describing it🙏Since the first part of the route is often the part I want to see, it's indeed a shame these overlapping labels don't permit it.

A possible solution could be to change the position of the labels to the end of the graph? Programmatically that might be easier than creating a new blank area left from the y axis.

Many thanks for the great app to all of you contributing

**Comment by vshcherb** [comment]
1st part moved to separate task https://github.com/osmandapp/OsmAnd/issues/18204
Values uphill / donwhill algorithm changed a lot last 3 months so it should be more realistic now https://docs.osmand.net/docs/technical/algorithms/calculate-uphill-slope/
