### ISSUE TITLE
Access restrictions not shown on map

### ISSUE THREAD

**Issue by rene78** [osmandapp/OsmAnd#16150]
### Description
In previous versions of OsmAnd streets with access restrictions (e.g. "private" or "destination") were highlighted in different colors on the map (e.g. red or blue). This is no longer the case in the current version. Possibly related to the switch to opengl?

### How to reproduce?
Configure map --> Details --> Show access restrictions and toll - activate
No change on display of access restricted roads.

### Your Environment
OsmAnd Version: OsmAnd+ 4.3.5
Android/iOS version: Android 8, MIUI
Device model: Redmi Note 5

**Maps used (online or offline):**   
Experienced on offline maps of Germany, Switzerland and Malaysia.

**Comment by scaidermern** [comment]
I can still see access restrictions with OsmAnd 4.3.5 and enabled OpenGL 🤔. Are you sure you enabled "Show access restrictions and toll" for your current profile? Are you sure you are using the offline vector map? OsmAnd can't display this information for other maps.

**Comment by rene78** [comment]
Yes, it is activated and I'm using offline vector maps.

I have just changed back to "Rendering Engine v1" and the color coding for access restricted streets appear again. So it really seems to be related to OpenGL. Interesting that you don't seem to have this problem, @scaidermern

**Comment by scaidermern** [comment]
Could it depend on the chosen map style? If I select the touring style then access restrictions are only visible with rendering engine v1 but not with v2. This sounds exactly like your problem. With the default map style OsmAnd access restrictions are visible with both engines.

**Comment by rene78** [comment]
Unfortunately not for me. No matter which map style I choose the access limitations are not visible. Thanks for helping, by the way!

**Comment by rene78** [comment]
Thanks @Zirochkabila! After playing around with it some more I was able to switch on the highlighting of access restricted roads by changing the map style (Configure map --> Map style) from "Touring view" to "OsmAnd".

My favorite map style has been "Touring view" so far. You think there's a chance to fix this map style so it shows access restricted roads in different colors again? That would be awesome.

**Comment by sonora** [comment]
Would certainly try to fix. But I am still unclear if the issue is
- "_If I select the touring style then access restrictions are only visible with rendering engine v1 but not with v2._", or is it
- "_No matter which map style I choose the access limitations are not visible._"?

**Comment by rene78** [comment]
The first one:
"If I select the touring style then access restrictions are only visible with rendering engine v1 but not with v2."

All other map styles show access restrictions in rendering engine v1 and v2.

**Comment by sonora** [comment]
Can reproduce.

@xmd5a2 Would you have an idea why this is? _Touring-view_ means to completely use _default_render_ for the handling of `showAccess`, I see no overriding code. But Touring view seems the only dependent renderer still having the following code block, is that maybe outdated?  https://github.com/osmandapp/OsmAnd-resources/blob/f8d10c2d1566bc2e11ff3b7f98a854c8ce4260f7/rendering_styles/Touring-view_(more-contrast-and-details).render.xml#L262

**Comment by rene78** [comment]
> Could it depend on the chosen map style? If I select the touring style then access restrictions are only visible with rendering engine v1 but not with v2. This sounds exactly like your problem. With the default map style OsmAnd access restrictions are visible with both engines.

(On a side note:
@scaidermern perfectly pointed to the issue. I misunderstood "map style", thus didn't really respond to his comment. Sorry.)

**Comment by sonora** [comment]
@xmd5a2 , @vshcherb I've tested that putting explicit `showAccess` code in the dependent renderer would make it work also in engine V2. But I think we are looking at an OpenGL-related glitch here, because such workaround is not needed for V1 rendering, there access restrictions inherited from `default.render.xml` show ok.

**Comment by sonora** [comment]
I fixed this in Touring view by duplicating the `showAccess` code for roads from default render into the dependent render file. Leaving this issue open if anybody still comes up with a better idea.

**Comment by sonora** [comment]
Fun fact: In my duplication of default render's `showAccess` code to Touring view I have there commented out e.g. the case `access=permissive`. The effect is that
- when using engine V1, access=peemissive is nevertheless rendered ok (style and color is taken from default render),
- when using V2 it is not rendered...

So again, somehow code from default is propagated to the dependent renderer differently in V1 and V2.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14163mqta, Released: 2023-02-09
Done
Tested using the Touring view style in rendering versions 1 and 2, in night and day mode - access restrictions are shown on map

**Comment by rene78** [comment]
@xmd5a2  Sorry to bother again. Access restrictions are corrected with the updated release, but I don't see one-way-street arrows with Touring View anymore. Would it be possible to fix this one as well? I can open a new issue if you want.

**Comment by scaidermern** [comment]
Indeed, oneway arrows aren't visble with touring style.

**Comment by sonora** [comment]
And again, only with the V2 engine, V1 seems to work fine.

**Comment by Zirochkabila** [comment]
@rene78 Please create a new issue

**Comment by rene78** [comment]
> @rene78 Please create a new issue

Done. https://github.com/osmandapp/OsmAnd/issues/16900
