### ISSUE TITLE
Android Auto search didn't work

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#16158]
I had tested search on Android Auto emulator and didn't works in OsmAnd~ with 14 maps (4.35GB).
Logcat: [logcat (7).log](https://github.com/osmandapp/OsmAnd/files/10351722/logcat.7.log).

Probably not related:
`net.osmand.binary.BinaryMapPoiReaderAdapter.readPoiIndex` [Google Play Console](https://play.google.com/console/u/0/developers/8483587772816822023/app/4972717699233382173/vitals/crashes/daf08e8ccead9e7b8f38c075b4b0e3a4/details?days=28)

<img src="https://user-images.githubusercontent.com/9365308/210770605-91662c91-197b-4d4c-a1b9-a323a571485c.jpg"  width="500" height="auto"/>

**Comment by mmacura311** [comment]
it looks like same problem I have https://github.com/osmandapp/OsmAnd/issues/16014

**Comment by mmacura311** [comment]
tried yesterday with 4.3.6 and still hitting the issue

**Comment by alex-osm** [comment]
- [ ] GPX selection via _Route menu > Select destination > Search > GPX_ does not work

**Comment by mmacura311** [comment]
Tried 4.3.8 yesterday in a car, first ride worked OK search and navigation, second ride the navigation did not work - there was supposedly no GPS signal. However different app showed coordination perfectly. Not sure if this can be related or not.

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/commit/2163d9a19a7b4c4aaa329388c5ca9a49734e8e02
https://github.com/osmandapp/OsmAnd/commit/874c03240a9ad10d1b9082d8529c8f67cf78dcbe

**Comment by mmacura311** [comment]
Hello, what is the status with this fix? will it make into 4.3.x or will only be in 4.4.x ?
I tried 4.3.8 again and it kinda works when selecting a favorite destination, but the search still hits timeout.

**Comment by vshcherb** [comment]
4.3.10 should be a first version with a fix - it's on review

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14157mqta, released: 2023-02-07

[exception (29).log](https://github.com/osmandapp/OsmAnd/files/10673423/exception.29.log)


- [ ] If the track is not displayed on the map - **crash**

If the track is displayed on the map, a route is built
