### ISSUE TITLE
Vehicle parameters didn't respect changed measurement units or region

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#16169]
Feedback from user
>  My car manual gives measurements in inches. These settings are in meters.

### How to reproduce
* Open **Menu** – **Settings** – **Profile** – **General settings**
* Change **Region** to **USA**
* Go back to **Configure Profile**
* Open **Navigation settings** – **Vehicle parameters** – **Width limit**
* Limit is showing in meters

<table style="width:100%">
  <tr>
    <th>General settings</th>
    <th>Vehicle parameters</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/210987776-319a213a-e93a-4442-8716-8bc6480af62c.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/210987758-03cff2a5-d62a-485a-bd67-3a08e66e30ab.png"  width="300" height="auto"/> </td>
  </tr>
</table>   
iOS have the same issues https://github.com/osmandapp/OsmAnd-iOS/issues/2433

**Comment by nazar-kutz** [comment]
**Pull Request**
https://github.com/osmandapp/OsmAnd/pull/16490

**Comment by vshcherb** [comment]
Feet -> Inches for Driving

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14201mqta, Released: 2023-02-25
Done

**Comment by dmpr0** [comment]
## Review 
- [ ]  Use **lbs.** instead of **tons** for Weight parameter if USA region is selected.
For USA, weight units should be changed to **lb*. [Wikipedia](https://en.wikipedia.org/wiki/Ford_F-Series_(thirteenth_generation)) show Ford F-150 weight in lb: `4,069–4,653 lb (1,846–2,111 kg)`. Official Ford site is also show weight in **lbs** https://www.ford.com/trucks/f150/models/f150-limited/

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#14270mqta, Released: 2023-03-25
Done
