### ISSUE TITLE
Cannot add POI's "opening hours" via the time wheel selector

### ISSUE THREAD

**Issue by i7u** [osmandapp/Osmand#1616]
When adding a new POI (e.g. shop), there is a nice time selector GUI which allows us to scroll to the right hour/minute to select opening times. Unfortunately the output of this visual selection process does not appear to be saved. The only method that works is typing in the opening hours.

**Comment by vshcherb** [comment]
We just introduced new UI for POI editing in nightlies feel to try it, it solves the issue you described.
