### ISSUE TITLE
No saving "Show on the map" for Favorites folder

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#16164]
### Description

No saving "Show on the map" for Favorites folder

### How to reproduce?

1. My Places menu - Favorites - Folder - Tree dots button - Show on map
2. Favorites on the map
3. "Force stop" for OsmAnd
4. Favorites Folder is not showing on the map. "Show on the map" is disabled.

P.S.  before all manipulation my Favorites folder was not active on the map.

Device : beyond0
Brand : samsung
Model : SM-G970F
Product : beyond0ltexx
Build : SP1A.210812.016.G970FXXUGHVJ5
Version : 12
App Version : OsmAnd~
Apk Version : 4.4.0#14070mqta 4400

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/commit/88a0689d98a2cd4bfdb1b389be5f41bcba16d94a

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14082mqta, released: 2023-01-09
Done
