### ISSUE TITLE
Enhancement: support mix of local and chosen guidance voices

### ISSUE THREAD

**Issue by ericzolf** [osmandapp/Osmand#1617]
When being in a foreign country, I often would like to have the instructions for guidance handled separately from the name of the places. Basically I generally want to choose the instructions' language but still have the local names be spoken in the local language.
As an example, I was recently in Poland and, even if my Polish is poor, polish street names are completely impossible to understand if spoken with a German voice, whereas it would make some sense in Polish, even though I don't speak it good enough to understand quickly enough the instructions.

**Comment by vshcherb** [comment]
It doesn't look easy, we use standard TTS engine and switching language will take quite a lot of time which we can't allow due to important announcements. Let us investigate it a little bit more to find possible solutions.

**Comment by Gizmot** [comment]
+1, This is a quite good issue for example in Montreal where you get half of your street names in French and the other half  in English.

**Comment by vshcherb** [comment]
Closed in favor of #1690 seems to be natural (without extra options) approach to pronounce street names correctly.

**Comment by sonora** [comment]
I am not aware there is a mechanism to mix 2 languages in TTS announcements, I'm afraid...
