### ISSUE TITLE
Widgets: map markers is disappears when navigation starts

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#16171]
## How to reproduce
* Add one or two markers on the map 
* Open **Configure Screen** – **Widgets** – **Left panel**
* Scroll to **Available widgets** – **Map markers** 
* Add **First marker** and **Second marker** to the panel
* Go back to map, you will see two map marker widgets with distance to them
* Tap on **Navigation**, select destination, tap on **Start**
* When navigation is in progress map marker widgets is disappears

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/211011371-121f39ce-aea8-4758-9f2d-83c61a63103d.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/211011378-749e2daa-8eb4-4b43-a4d9-8fb95e7b3d40.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by marcor** [comment]
I second this, the map marker widget is sorely missed in navigation mode, especially when there are many intermediate points and one needs to keep an eye on their name, and possibly skip them. Opening the navigation list is too cumbersome while driving.
