### ISSUE TITLE
Zoom level for Hillshades

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#16176]
**Regression**

### Description

"Zoom level" parameter works only on the upper bound.

### How to reproduce?

Choose "Zoom level" for Hillshade layer (Configure map > Terrain > Hillshade):  12-15
We can see the Hillshade layer for zoom before 12. (Not ok)
For zoom after 15 the layer is disappeared (Ok).

### Your Environment
Device : beyond0
Brand : samsung
Model : SM-G970F
Product : beyond0ltexx
Build : SP1A.210812.016.G970FXXUGHVJ5
Version : 12
App Version : OsmAnd~
Apk Version : 4.4.0#14078mqta

**Comment by EugeneZmeuk** [comment]
after zoom level 15 the level has not disappeared fully. Only the transparency is greatly reduced. At first glance, this gives the impression that it is correct. The difference can only be seen clearly if you switch off the terrain menu item.

**Comment by vshcherb** [comment]
Probably related to opengl so other layers needs to be tested as well

**Comment by DmitryAlexei** [comment]
Hillshades are visible on the 16-th zoom <table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/116079541/218705022-b25f5581-1a1a-4594-9981-753d6217e110.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/116079541/218705024-6b998142-ada1-4527-a411-cc51eb873e9e.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>

Hillshades are also visible on the 11-th, 10-th, 9-th, 8-th, 7-th, 6-th and 5-th zoom. On the 4-th zoom cannot check, app crashes

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/116079541/218705687-40f208ff-497e-4e8f-be41-b0ad5aa02744.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/116079541/218705721-04dfb1d7-7abd-4844-83a8-fa8c2f753d01.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/116079541/218706364-b3a31d88-bab7-4f3d-adc4-c19af23a89ce.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/116079541/218705768-334bf2be-1218-4c22-9f3c-e95a67a6e409.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/116079541/218705793-84c88e60-c5f8-4524-af2d-3e52fadfdc73.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/116079541/218705829-f1a19ff4-e2fe-4c71-b8c4-94294205f92d.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.4.0#14189mqta, released: 2023-02-20

1. The zoom level at which the Hillshades should be visible set in Configure map > Terrain: min 15 - max 19

Despite the configured range, Hillshades are not visible at 17-19 zooms:

<details><summary>Video Hillshades</summary>
<video src="https://user-images.githubusercontent.com/116079541/220288582-0cd8f47e-64b0-4ce6-a786-f338bfbbc1a3.mp4"></video>
</details>


2. The zoom level at which the Slopes should be visible set in Configure map > Terrain: min 15 - max 19

Despite the configured range, Slopes are visible at 3-14 zooms and not visible at 17-19 zooms:

<details><summary>Video Slopes</summary>
<video src="https://user-images.githubusercontent.com/116079541/220290146-d0bf0569-230c-4022-89ce-7372b155a5e4.mp4"></video>
</details>

[logcat.log](https://github.com/osmandapp/OsmAnd/files/10791297/logcat.log)

As a conclusion. The slider for adjusting the display of hillsides and slopes does not work.

**Comment by vshcherb** [comment]
Hillshade / Slope
1. Doesn't respect lower boundary Min i.e. even if min is 12, hillshade / slope are still visible on 8th zoom for example
2. Default values should be set 3 - 17 (hillshade), 3 - 16 (slope) (it's known issue that hillshade / slope couldn't be displayed after 16/17 but Geotiff support coming 4.4 will support up to 19 th zoom)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14249mqta, Released: 2023-03-17
Still present


https://user-images.githubusercontent.com/104760013/225959166-fcc96a0e-29fe-4479-8148-a32156cae20a.mp4
