### ISSUE TITLE
Navigation calculation freezes when you try to navigate to a destination with maps, but there are no maps around this point.

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd#16177]
### Description
Navigation calculation freezes when you try to navigate to a destination with maps, but there are no maps around this point.

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/116079541/211040223-e26609af-d823-49db-b0fb-4a7d6193cd6d.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/116079541/211040242-b3be6971-2822-4efb-b0ae-28dea481f8e0.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

https://user-images.githubusercontent.com/116079541/211041992-6b743951-6f6a-4932-9069-2faedc7396c1.mp4

Please note that when you change the destination point, the navigation calculation simply stops without a clear explanation of what is happening. See video

https://user-images.githubusercontent.com/116079541/211042527-f4ca9f98-7ced-4392-9556-2e52069f59bc.mp4

It would be great if a notification to load maps along the route would pop up. 
Something like that
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/116079541/211042970-915906f5-6e06-411a-8fbd-d4bebd92ffdb.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### How to reproduce?
Try to navigate to a destination with maps, but there are no maps along your route to this place

### Your Environment
OsmAnd Version: 4.3.5
Android/iOS version: 13
Device model: samsung galaxy note 20 

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

Offline maps of West Pomerania

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14164mqta, Released: 2023-02-09
There are no offers to download maps or messages that there are no necessary maps and the route cannot be calculated


https://user-images.githubusercontent.com/104760013/218270578-191293a5-7f84-4840-a775-e6065b083b55.mp4

**Comment by dmpr0** [comment]
<table style="width:100%">
  <tr>
    <td><video source src="https://user-images.githubusercontent.com/9365308/235593800-00170b7e-176f-482d-bc55-32fe8d5412be.mov"  width="300" height="auto"/>  </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
We need to properly document algorithm when we suggest to download maps and continue to calcuate and we don't calculate route at all.

**Comment by DmitryAlexei** [comment]
https://docs.osmand.net/docs/user/navigation/setup/route-navigation#troubleshouting

Possible bugs, further investigation needed:
- It seems that when loading maps through the navigation menu, the start point and destination are lost.
