### ISSUE TITLE
Animation during navigation

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#16178]
### Description

As long as my move was straight, the map refresh was fine (only a translation) ... but at each significant change of my direction (for example entering a traffic circle) the problem was the following:
* The vehicle avatar was blocked at a fixed position on the map
* The map was rotating (with the vehicle avatar as the center of the rotation) for a few seconds (5 or 6)
* After this delay a long translation of the map was performed to catch up with the distance traveled.

### How to reproduce?

 "Car" mode" and  the map orientation was in the "Movement Direction" 
Issue with releases 4.3.4 and 4.3.5

in 4.3.3 and previous releases, the map is correctly displayed (in position and orientation) but its refresh rate (every second I guess) does not give a smooth impression of movement.

**Comment by TheSnoozer** [comment]
Sounds related to https://github.com/osmandapp/OsmAnd/issues/16081

**Comment by Zirochkabila** [comment]
@EugeneZmeuk is this a duplicate https://github.com/osmandapp/OsmAnd/issues/16081 ?

**Comment by EugeneZmeuk** [comment]
https://github.com/osmandapp/OsmAnd/issues/16041 
https://github.com/osmandapp/OsmAnd/issues/16081

**Comment by vshcherb** [comment]
Needs to be tested with 4.3.6
