### ISSUE TITLE
Spurious (too many) lanes and directions through tunnel near Basel, CH

### ISSUE THREAD

**Issue by martenjj** [osmandapp/OsmAnd#16179]
Routing engine:  OsmAnd's in-app offline routing
Routing Profile:  Car, no restrictions

Start point:  A2/A3 westbound near Muttenz, Basel, CH:  47.52746, 7.67643
End point:  approximately 1.5km to west along same road:  47.53504, 7.65736

Actual and expected routes:  The routing is correct, because there are no junctions or road changes along it.  However, just after entering the tunnel (OSM way 137361920), at the location indicated in the screen shot, a six lane route indication is given with the voice instruction "Keep right on...".  There is no junction or change in the number of lanes here, and the number of lanes is consistently 3 before, through and after the tunnel.  Nowhere nearby does the route have 6 lanes.

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/10631760/211070460-0750bba5-cf16-4bee-98b6-06bd874019a0.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

Is this a regression? - apparently not, have noticed this before with earlier OsmAnd+ app version and maps, but have not been able to capture it.

**OsmAnd Version:**

<pre><code>
4.3.3 (2022-12-13)
</code></pre>

**Device and Android/iOS version:**
Samsung Galaxy S10, Android 12

**Maps used (online or offline):**
Offline, full map, Switzerland Basel 1 Jan 2023

**Anything else relevant?**
This happens both with real time (on the ground) navigation and simulated.
Navigating in the opposite direction along the eastbound tunnel (OSM way 137361922) is correct, there are no spurious lane indications.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14120mqta, released: 2023-01-22

@martenjj  Try updating the maps or downloading the latest version of the app and checking again. Because as you can see in the video, it cannot be reproduced

https://user-images.githubusercontent.com/104760013/213910633-a1d94170-f6ee-41f0-8694-58c2c424bb82.mp4

**Comment by vshcherb** [comment]
- Did you use live updates? 
- Did you use combination of 2 maps ? Full Switzerland map and Basel?

**Comment by vshcherb** [comment]
Can't reproduce any more unfortunately it will be hard to find old maps cause now they are regenerated.

**Comment by martenjj** [comment]
Sorry, can still reproduce with Osmand+ 4.3.11 2023-02-05 (current beta version from Google Play - not sure how to obtain the 4.4 version).  Offline maps only, no online maps or live updates.  Map "Switzerland Basel 1 Feb 2023", have checked device filesystem and there is no old Switzerland map present.  Driving region is explicitly set to Europe (previously it was set to "Automatic", but I have not had any problem with driving direction after recent fixes).

**Comment by martenjj** [comment]
Further: Have tried with a older device (Samsung Galaxy S9), app version (4.3.7 2023-01-17) and map (Switzerland 1 Feb 2020).  The guidance is correct and there are no spurious lane indications.  Upgrading the data file to the latest available (Switzerland 1 Feb 2023) reproduces the problem.  This is the complete Switzerland data file, not the region.

**Comment by Zirochkabila** [comment]
@martenjj Cannot be reproduced
Can you recreate the result artificially, without real navigation?

**Comment by martenjj** [comment]
Can reproduce both on the ground (I'm not in Basel at the moment, but did observe this happening in early January there) and with simulated navigation.

**Comment by vshcherb** [comment]
Please share screenshot @martenjj with installed Local maps to double check all possible artifacts. 
Also please make sure you cleaned OsmAnd Live

**Comment by vshcherb** [comment]
Do you have old road-only maps possibly installed?

**Comment by martenjj** [comment]
Contents of directory /storage/self/primary/Android/data/net.osmand.plus/files:

.nomedia
Andorra_europe.obf
Austria_europe.obf
Belgium_europe.obf
Denmark_europe.obf
France_auvergne-rhone-alpes_europe.obf
France_bourgogne-franche-comte_europe.obf
France_brittany_europe.obf
France_centre-loire-valley_europe.obf
France_corse_europe.obf
France_great-east_europe.obf
France_hauts-de-france_europe.obf
France_ile-de-france_europe.obf
France_new-aquitaine_europe.obf
France_normandy_europe.obf
France_occitania_europe.obf
France_pays-de-la-loire_europe.obf
France_provence-alpes-cote-d-azur_europe.obf
Gb_england_channel-islands_europe.obf
Gb_england_east-midlands_europe.obf
Gb_england_east-of-england_europe.obf
Gb_england_greater-london_europe.obf
Gb_england_north-east-england_europe.obf
Gb_england_north-west-england_europe.obf
Gb_england_south-east-england_europe.obf
Gb_england_south-west-england_europe.obf
Gb_england_west-midlands_europe.obf
Gb_england_yorkshire-and-the-humber_europe.obf
Gb_scotland_europe.obf
Gb_wales_europe.obf
Germany_baden-wuerttemberg_europe.obf
Germany_bayern_europe.obf
Germany_berlin_europe.obf
Germany_brandenburg_europe.obf
Germany_hamburg_europe.obf
Germany_hessen_europe.obf
Germany_mecklenburg-vorpommern_europe.obf
Germany_niedersachsen_europe.obf
Germany_nordrhein-westfalen_europe.obf
Germany_rheinland-pfalz_europe.obf
Germany_saarland_europe.obf
Germany_sachsen-anhalt_europe.obf
Germany_sachsen_europe.obf
Germany_schleswig-holstein_europe.obf
Germany_thueringen_europe.obf
Isle-of-man_europe.obf
Italy_abruzzo_europe.obf
Italy_basilicata_europe.obf
Italy_calabria_europe.obf
Italy_campania_europe.obf
Italy_emilia-romagna_europe.obf
Italy_friuli-venezia-giulia_europe.obf
Italy_lazio_europe.obf
Italy_liguria_europe.obf
Italy_lombardia_europe.obf
Italy_marche_europe.obf
Italy_molise_europe.obf
Italy_piemonte_europe.obf
Italy_puglia_europe.obf
Italy_toscana_europe.obf
Italy_trentino-alto-adige_europe.obf
Italy_umbria_europe.obf
Italy_valle-aosta_europe.obf
Italy_veneto_europe.obf
Liechtenstein_europe.obf
Luxembourg_europe.obf
Monaco_europe.obf
Netherlands_drenthe_europe.obf
Netherlands_flevoland_europe.obf
Netherlands_friesland_europe.obf
Netherlands_gelderland_europe.obf
Netherlands_groningen_europe.obf
Netherlands_limburg_europe.obf
Netherlands_noord-brabant_europe.obf
Netherlands_noord-holland_europe.obf
Netherlands_overijssel_europe.obf
Netherlands_utrecht_europe.obf
Netherlands_zeeland_europe.obf
Netherlands_zuid-holland_europe.obf
San-marino_europe.obf
Switzerland_basel_europe.obf
Switzerland_bern_europe.obf
Switzerland_central_europe.obf
Switzerland_eastern_europe.obf
Switzerland_lake-geneva_europe.obf
Switzerland_ticino_europe.obf
Switzerland_zurich_europe.obf
World_altitude_correction_WW15MGH.extra
World_basemap.obf
World_basemap_mini.obf
avnotes
backup
exception.log
favorites
fonts
ind.cache
ind_core.cache
itinerary.gpx
logcat.log
nautical
osmandcore.log
proj.db
regions.ocbf
rendering
roads
routing
sounds
srtm
tiles
tracks
travel
voice
weather
weather_forecast

OsmAnd Pro is not purchased or enabled.
"Online maps" plugin is disabled.

**Comment by martenjj** [comment]
Have tried completely refreshing the installation by uninstalling the app, checking with ADB that its data directory is empty, then reinstalling the app and re-downloading the map files.  The routing is correct and there are no spurious lane indications.  The map files present are the same as above, except that there is no "roads/ind_core.cache" file.

So there was obviously something left behind, maybe from a long time ago, which was causing the spurious lane indications.  Would be happy for this issue to be closed.

**Comment by xmd5a2** [comment]
Routing log from OsmAndMapCreator:
```
<test  route_routing_time="63,6" route_vehicle="car" route_base="false" route_start_lat="47,52746" route_start_lon="7,67643" route_target_lat="47,53504" route_target_lon="7,65736" route_complete_distance="1769,5" route_complete_time="75,5" route_native="true" metrics_tilesPerSec="6194,2" metrics_segmentsPerSec="1516,9" segments_visited="8" segments_queueDirectSize="16" segments_queueOppositeSize="1" segments_visitedDirectPoints="35" segments_visitedOppositePoints="38" tiles_loadedTiles="61" tiles_loadedTilesDistinct="61" tiles_loadedTilesMax="61" tiles_loadedTilesPrevUnloaded="0" tiles_unloadedTiles="0" time_timeToCalculate="0,0" time_timeToLoad="0,0" time_timeToLoadHeaders="0,0" time_timeToFindInitialSegments="0,0" time_timeExtra="0,0">
	<segment id="821980645" oid="52606761311" start="7" end="13" time = "6.0" rtime = "4.0" name = " (A2;A3) " maxspeed = "100" distance = "175.0" motorway turn = "Go ahead" turn_angle = "0.0" start_bearing = "-90.87246" end_bearing = "-83.659805" height = "[0.0, 280.17343, 7.076425, 280.09796, 32.63408, 279.75, 43.120975, 280.75, 31.33358, 281.0, 22.090143, 281.75, 8.920612, 282.0]" description = "Go ahead and go 1769,51 meters" />
	<point 9 osmand_ele_desc="0.75" osmand_ele_decline_1="1"/>
	<point 10 osmand_ele_asc="1.0"/>
	<point 11 osmand_ele_asc="0.25"/>
	<point 12 osmand_ele_asc="0.75"/>
	<segment id="124582571" oid="7973284583" start="0" end="10" time = "20.0" rtime = "17.0" name = " (A2;A3) " maxspeed = "100" distance = "522.0" motorway start_bearing = "-82.6004" end_bearing = "-66.04473" height = "[0.0, 282.0, 15.6414995, 281.5, 33.28288, 281.75, 34.451103, 282.0, 35.68063, 280.0, 26.92574, 278.25, 24.659359, 276.75, 37.84239, 275.0, 39.8251, 274.27722, 111.697655, 272.25, 162.23425, 273.0]" description = "" />
	<point 1 osmand_ele_desc="0.5" osmand_ele_decline_1="1"/>
	<point 2 osmand_ele_asc="0.25"/>
	<point 3 osmand_ele_asc="0.25"/>
	<point 4 osmand_ele_desc="2.0" osmand_ele_decline_5="1"/>
	<point 5 osmand_ele_desc="1.75" osmand_ele_decline_5="1"/>
	<point 6 osmand_ele_desc="1.5" osmand_ele_decline_5="1"/>
	<point 7 osmand_ele_desc="1.75" osmand_ele_decline_3="1"/>
	<point 9 osmand_ele_desc="2.75" osmand_ele_decline_1="1"/>
	<segment id="137361920" oid="8791162903" start="0" end="13" time = "41.0" rtime = "35.0" name = "Schweizerhalletunnel (A2;A3) " maxspeed = "80" distance = "874.0" motorway start_bearing = "-66.4534" end_bearing = "-42.891903" height = "[]" description = "" />
	<segment id="200676710" oid="12843309487" start="0" end="3" time = "7.0" rtime = "6.0" name = " (A2;A3) " maxspeed = "100" distance = "197.0" motorway start_bearing = "-48.027245" end_bearing = "-52.109585" height = "[0.0, 268.0, 118.66272, 272.0, 62.53651, 273.25, 3.0744793, 273.28818]" description = "" />
	<point 1 osmand_ele_asc="4.0"/>
	<point 2 osmand_ele_asc="1.25"/>
</test>
Route <route>: routing_time=63,6, vehicle=car, base=false, start_lat=47,52746, start_lon=7,67643, target_lat=47,53504, target_lon=7,65736, complete_distance=1769,5, complete_time=75,5, native=true
Route <metrics>: tilesPerSec=6194,2, segmentsPerSec=1516,9
Route <segments>: visited=8, queueDirectSize=16, queueOppositeSize=1, visitedDirectPoints=35, visitedOppositePoints=38
Route <tiles>: loadedTiles=61, loadedTilesDistinct=61, loadedTilesMax=61, loadedTilesPrevUnloaded=0, unloadedTiles=0
Route <time>: timeToCalculate=0,0, timeToLoad=0,0, timeToLoadHeaders=0,0, timeToFindInitialSegments=0,0, timeExtra=0,0
Routing time 0.02756758
!!! Finding self route: 4 32 ms
```

Looks like nothing wrong here

**Comment by martenjj** [comment]
I believe have found the root cause.  The Switzerland Basel map was up to date (1 Mar 2023), but the adjacent Germany Baden-Württemberg was not (I haven't travelled to Germany recently, so due to data limits had not updated the Germany maps since 1 Oct 2021).  This includes short but not continuous segments of the A2/A3 in Switzerland:

![Screenshot_20230323_081411_OsmAnd+](https://user-images.githubusercontent.com/10631760/227145646-fabdfd3a-4420-44f6-814e-edea7d8e4f19.png)

Over that time the road route must have been edited, because at very high zoom levels in Osmand a discrepancy between the DE and CH maps could be seen, with multiple road segments overlaying this route exactly at the place where the spurious directions are given.  Updating the adjacent Germany BW map to the current version (1 Mar 2023) removes the discrepancy and the navigation is totally correct.

So I have learned a lesson: if there are map problems in border areas, make sure that the adjacent countries are also up to date!
