### ISSUE TITLE
Wrong route with car profile

### ISSUE THREAD

**Issue by clementcontet** [osmandapp/OsmAnd#16173]
# 🐞 routing report

### Routing engine
- [X] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile
Car (works fine with pedestrian or bicycle)

### Start and end points
45.77704, 4.82428 to 45.77699, 4.82360

### Actual and expected routes
Actual: 
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/7261426/211017639-27ebc552-9ab4-4196-b729-4d9f68735ddd.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

Expected:
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=45.77704%2C4.82428%3B45.77699%2C4.82360

### Is this a regression?
I don't know

## 🌍 Your Environment

**OsmAnd Version:**
<pre><code>4.3.5</code></pre>

**Device and Android/iOS version:**
Android 

**Maps used (online or offline):**
- [X] Offline maps offered within the OsmAnd app for download (France Auvergne-Rhône-Alples from January 1st 2023)
- [ ] Online (tile / raster) maps

**Comment by vshcherb** [comment]
Looks like there is a bug that road is impassable ? https://www.openstreetmap.org/way/22476166#map=19/45.77695/4.82450

**Comment by clementcontet** [comment]
Indeed there is a barrier in the middle of the road (https://www.openstreetmap.org/node/9417509524) but it shouldn't make the whole road impassable

**Comment by vshcherb** [comment]
https://www.openstreetmap.org/node/9417509524 - yes the issue is that it's 1st node and it misinterprets 1st node that 1st segment is fully impassable so it tries to  route to the east and not west which is correct.
![Screen Shot 2023-01-13 at 17 24 46](https://user-images.githubusercontent.com/1042025/212356208-464c3501-5d44-43d9-90cc-7a574b1ccd74.png)

**Comment by xmd5a2** [comment]
@vshcherb yes, issue is in this bollard. If you remove it, then the route builds normally. Looks like a routing engine bug.

**Comment by sonora** [comment]
Not sure if it's unavoidable,  but by my testing some commit in the last 5 days led to an increase in route calculation time by about 10-20%, could it be?

**Comment by Zirochkabila** [comment]
@sonora What kind of commits are you talking about? 
Calculation time increased on Android or iOS?

**Comment by sonora** [comment]
Anatolii, I am comparing an Android build of 2023-04-07 with an equivalent one of 2023-04-02, calculating the very same car route multiple (say 8) times and taking the average of what our development pluugin displays each time as calculation times.

Typical results are: For a route of
- 120km, start and end points are in built-up areas near motorways: 6.4s vs. 5.5s
- 150km,  start point farther away from a motorway: 10.4s vs. 9.5s
- 110km, start and end points are close to motorway exits: 4.5s vs. 3.9s

Initially itwas just a feeling, but I think it is statistically significant.

**Comment by Zirochkabila** [comment]
@sonora We need to draw @vshcherb  attention to this commit. 
It seems that they really make the calculation time longer

**Comment by goldfndr** [comment]
Would it be an improvement to have the `hdirection` comparison outside the loop instead of inside, and the `direction` and `tdirection` comparisons first instead of last?

**Comment by sonora** [comment]
Upon a closer look: Isn't the commit buggy in the first place? We now filter out exactly the ones where the direction flag applies, rather than where it does not apply?

**Comment by vshcherb** [comment]
@sonora you need to test visited segments compare before / after but that won't change commit itself cause it's systematically (logically) correct, so there was a bug in the code

**Comment by sonora** [comment]
Here''s a before and after:
![Screenshot_20230410-150628_OsmAnd~](https://user-images.githubusercontent.com/845735/230907551-4dbba962-9dfc-474d-9a56-301a820e16d9.jpg)
![Screenshot_20230410-150831_OsmAnd~](https://user-images.githubusercontent.com/845735/230907554-4282829b-6a22-4765-8c56-2d512524967d.jpg)

**Comment by sonora** [comment]
We could optimize our code up front by e.g. sorting our pointTypes. So far we need two loops over the same entity, one to find direction tags, the next one to subsequently find what they apply to.

**Comment by vshcherb** [comment]
It looks very strange +50% time calculation, but visited segments are the same... 

Though I'm not sure we need to open new issue.

**Comment by velle** [comment]
@sonora What did you do to make OsmAnd show such an infobox with details about the routing (distance, router time, calculation time, number of roads, number of tiles)?

**Comment by sonora** [comment]
@velle Enable the Development plugin, then go to its settings - there are two related to showing debug info. But please note that this is _debug_ info, not _route_ info, in particular e.g. the router time is not the travel time.
