### ISSUE TITLE
Enhancement: have a language preference order for POIs (especially Wikipedia)

### ISSUE THREAD

**Issue by ericzolf** [osmandapp/Osmand#1618]
It would be really nice to have a preference order for languages (similar to the language order for content in Firefox) so that one's best language is always offered first when asking for a POI description.

**Comment by ericzolf** [comment]
As an after-thought, it would be also nice to have only the Wikipedia articles in your chosen languages be downloaded, that would spare some bandwidth.

**Comment by pos-ei-don** [comment]
+1 ;-)
It's hard to find the correct wiki-Iconin the correct language. I've even seen Chinese-Icons in germany.

**Comment by Gizmot** [comment]
Extensive testing in Vietnam. +1
Annoying sorting trough articles not written not Vietnamese :)

**Comment by Barrocas** [comment]
+1 
I see russian names, with italian description, in Portugal.
even when map view language is set to PT, and the info is available in Portuguese, some are not displayed correctly.
