### ISSUE TITLE
Category search: include post_partner post offices

### ISSUE THREAD

**Issue by call-me-matt** [osmandapp/OsmAnd#16186]
### Description

If searching for post offices `post_partner` and `post_annex` stores should be included. 
Quote from [wiki.osm.org](https://wiki.openstreetmap.org/wiki/Tag:post_office%3Dpost_partner): In some countries it is possible, that there are POIs like shop, amenity, craft or office, where the operator offers postal services on behalf. That could be a bank, a fuel station, a supermarket, a kiosk and others. These postal partners often do not offer the full range of services. Because this POIs can not be marked as `amenity=post_office` there is an approved tagging scheme.

### How to reproduce?

Go to Hamburg Ottensen. There are is a post [office](https://www.openstreetmap.org/node/9360753504) in a [greengrocer](https://www.openstreetmap.org/node/1083758245) and another one in a books [store](https://www.openstreetmap.org/way/400129402).

If you search for post offices, you will only find the one in the greengrocer which actually is doubled.

Besides these post "partner" offices, there are many more from private post operators like [dpd](https://www.openstreetmap.org/node/9585983393), [ups](https://www.openstreetmap.org/node/355243344), [hermes](https://www.openstreetmap.org/node/4908095521) etc.

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.5
Android/iOS version: 13
Device model: pixel4a

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
Germany > Hamburg

**Comment by pebogufi** [comment]
Of course such shops can be markes as post_office, it is a good idea to add additional information about limited services. I add theese object as separate pois nearby the "main" shop, or whatever it is. So the search for it is as usual.

**Comment by call-me-matt** [comment]
Not fond of this proposal to map for the renderer (or search engine in this case). In my country most post offices are `post_partner` or `post_annex` and it is not feasible to double tag all of them for OsmAnd to show them in a category search.

**Comment by osmonoid** [comment]
> I add theese object as separate pois nearby the "main" shop, or whatever it is

->

> Not fond of this proposal to map for the renderer (or search engine in this case)

It is not only about (not) being fond of something (could be a personal preference) but @pebogufi's suggestion is against the [good practices stated in the OSM wiki](https://wiki.openstreetmap.org/wiki/Good_practice#Don't_map_for_the_renderer):

> Do not enter incorrect data or remove correct data just because it will help a map renderer, a navigation system or some other data consumer which has problems with the correct data.


@pebogufi, please take a look at the OSM wiki regarding the tagging of [amenity=post_office](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpost_office) which clearly states the following:
> Only use this tag for *actual post offices*:
> **Businesses** that only act as a **relay point** to some postal service(s) **should be tagged** with **post_office=post_partner** instead.

**Comment by frasty** [comment]
Please add the possibility to search for POIs like shops, office, craft... with post_office=post_partner tag. This is an established tag with more than 5000 uses.

Actually OsmaAnd is not able to find features offering parcel pickups as a DHL post partner I previously added in osm (with post_office:service_provider=DHL and post_office=post_partner) like [this one](https://www.openstreetmap.org/nodo/4194520931). Adding a Custom Search with Service --> Post Office and then filtering with Type --> post partner didn't produce any results, as expected.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14172mqta, Released: 2023-02-12
`49.63677, 10.99957`
The post_office=post_partner tag of 5792 is not displayed as a POI

[Map](https://drive.google.com/file/d/1LIiQZF2OfVKI0ZUSzWS_Mpjzb1izjKIJ/view?usp=sharing)
[OSM](https://www.openstreetmap.org/way/37215830#map=19/49.63687/10.99959)
[Taginfo](https://taginfo.openstreetmap.org/tags/post_office=post_partner)

<details><summary>Overpassl</summary>
<img width="800" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/218298518-0caac293-7d76-455c-a779-c2a0e7cb63f4.png">
</details>

**Comment by xmd5a2** [comment]
Will be fixed with new maps

**Comment by Zirochkabila** [comment]
4.4.6.7
OsmAnd~ 4.4.0#14243mqta, Released: 2023-03-16
Done
[Post.obf.zip](https://github.com/osmandapp/OsmAnd/files/10990014/Post.obf.zip)

**Comment by dmpr0** [comment]
Re-check with **April** maps.

**Comment by peetCreative** [comment]
I have the same problem, when searching for post office, post partner is not found. The problem seems not to be solved.

OSM link: https://www.openstreetmap.org/node/3900271141

I'm on OsmAnd+ 5.4.4, released: 2026-08-31
