### ISSUE TITLE
 Search filter for access=yes for parking only finding a few car parks with this tagging.

### ISSUE THREAD

**Issue by tommycrock** [osmandapp/OsmAnd#16180]
### Description
Thanks for implementing  #15259 but it doesn't seem to be working well. A search for parking using the filter 'General access: Access is allowed' finds a few car parks (consistently the same ones) with access=yes, but not others also tagged access=yes. Looking at the details of these in osmand the access tag isn't showing at all, yet it does on the ones that are found. 

#### Examples of car parks found:
https://www.openstreetmap.org/way/19196527
https://www.openstreetmap.org/way/4470222
https://www.openstreetmap.org/way/95102382

#### Examples not found:
https://www.openstreetmap.org/way/87970031
https://www.openstreetmap.org/way/492747300
https://www.openstreetmap.org/way/161932210
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/5749884/211141021-7d245750-94a7-4782-8db7-27aec0b7d587.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### How to reproduce?
Search for parking, filter on general access allowed.

### Your Environment
OsmAnd Version: 4.3.5
Android version: 12
Device model: Galaxy s10

Maps used ( offline): UK Yorkshire and Humber. Latest + live

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14120mqta, released: 2023-01-22

Try updating the maps or the app.
As you can see in the screenshots, when you apply the **'General access: Access is allowed'** filter, tags on all parking lots are displayed in the description

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/213924548-e7389cdc-3cce-424f-b975-81c30d3346d6.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/213924549-57e806c8-7035-4716-bf28-74b495a9c76a.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/213924552-3f2ba842-c17f-4e3d-a7ef-c38a3d5b876c.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by tommycrock** [comment]
Redownloading the map has fixed it. Thanks
