### ISSUE TITLE
Cannot select guidepost if part of a hiking route

### ISSUE THREAD

**Issue by vmicho** [osmandapp/OsmAnd#16185]
### Description
Cannot select guidepost if part of a hiking route - the hiking routes are shown instead, not the guidepost object, so I cannot check the destinations or other guidepost contents.

### How to reproduce?
Tap on a guidepost that has route relation(s)
Guidepost causing problem (any other with relation will do):
https://www.openstreetmap.org/node/9533565188
The guidepost just above ( https://www.openstreetmap.org/node/9533565176 ) works fine in all my osmand versions.

2nd phone:
I also have a phone (android 12) with osmand 4.1.11 -> those 2 guideposts work fine
After updating to 4.2.7, the problematic guidepost is not selectable anymore (nothing happens after clicking on it or a nearby element is activated)
(On my original phone I have cycle routes overlay active.)
Activating cycle routes (Configure Map -> Routes -> hiking + alpine + cycling routes ON) - still nothing happens, activating hiking routes - nothing happens (also after reboot)
Reboot (with all routes active) -> same, guidepost not selectable
Update to 4.3.5 -> back to original problem (instead of guidepost, i see all routes listed)

1st phone again:
Activated hiking routes, then deactivated all hiking and cycle routes, reboot - now the behavior is same as 2nd phone, i.e. the problematic guidepost is not selectable.
Activated all cycle and hiking routes - same
Reboot (with all routes activated) -> back to original behavior (selecting guidepost lists all hiking routes, even those not connected with guidepost)
Deactivate hiking routes (keep cycle routes) -> no change
Reboot (still only cycle routes shown) -> same problem, selecting guidepost shows all routes

I'll not try all possible combinations. Obviously guideposts behave badly when part of route.
(might apply to any point that is part of a route relation)

### Your Environment
OsmAnd Version: 4.3.5 + 
Android/iOS version: 11
Device model: sh*tyaomi mi8

**Maps used (online or offline):**   
Austria, CH, Slovakia
Offline, no live updates on that mentioned zone.
Happens same when using live updates.

What happens now:
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/66125746/211161006-a99f17ed-34a3-4c1c-a7a7-ce63c4506584.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

What was it before:
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/66125746/211161013-e365d792-e6ec-455f-bf69-629774096b21.png"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14120mqta, released: 2023-01-22

[OSM](https://www.openstreetmap.org/node/9533565188#map=19/47.56282/13.64990)
<img width="906" alt="Screenshot 2023-01-22 at 17 54 25" src="https://user-images.githubusercontent.com/104760013/213925448-88a4f890-4644-44c1-ae09-2d9b92dfa40f.png">
[OSM](https://www.openstreetmap.org/node/9533565176#map=19/47.56378/13.64999)
<img width="906" alt="Screenshot 2023-01-22 at 17 54 36" src="https://user-images.githubusercontent.com/104760013/213925468-645cbfa8-f782-4884-b19a-eb96b2d5134b.png">


https://user-images.githubusercontent.com/104760013/213925356-db7ab9d3-3390-44ff-be24-094a19a02017.mp4
