### ISSUE TITLE
Non optimal map reindexing mechanism

### ISSUE THREAD

**Issue by brbar** [osmandapp/OsmAnd#16192]
Each map download / update causes reindexing of all maps you have downloaded. If you hit update all maps OSMAnd will reindex all the maps as many times as many maps you have on your device. I believe it is not optimal approach. And it takes noticeable time on devices with slow SD cards.

Is it possible to do a reindex after all downloads / updates in the download queue are done?

**Comment by vshcherb** [comment]
reindexing happens just for one map, but it double checks which map was download. It's quite fast when it's fast access sd card

**Comment by brbar** [comment]
According to what it shows it iterate each time through all of the downloaded maps, if you have a bunch of maps to be updated it takes significant amount of time. What if you will do any of those checks after all maps files are downloaded?

**Comment by vshcherb** [comment]
otherwise map is not visible until all are downloaded
