### ISSUE TITLE
Incorrect lane recommendations

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd#16196]
### Description
Wrong lane recommendations while navigating. The data is entered correctly in OSM. See https://www.openstreetmap.org/way/756086350
[Map](https://drive.google.com/file/d/1nzJUaGRh2zeR1V-nh2nWouDqHX-_amBo/view?usp=sharing)

[Googe Map Satellite](https://www.google.com.ua/maps/place/Aleja+Warszawska,+21-002+Panie%C5%84szczyzna,+Poland/@53.7666765,20.4654355,167m/data=!3m1!1e3!4m5!3m4!1s0x47225c040b87a8b1:0xbbe97bb50c7498eb!8m2!3d51.3030887!4d22.4360431?hl=en)

![IMG_20230107_182420_335](https://user-images.githubusercontent.com/116079541/211339729-0523dd67-2192-4588-98fc-59e3c8ec9c61.jpg)

https://user-images.githubusercontent.com/116079541/211353314-c595e6f4-95a2-4d2e-9c51-45d0c287de23.mp4

![photo_2023-01-09_16-32-12](https://user-images.githubusercontent.com/116079541/211342623-dd058b75-37e6-4b53-a7d0-86bcb345f8eb.jpg)

### How to reproduce?
Navigate from 53.76765° N, 20.46652° E to 53.76535° N, 20.46480° E
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=53.76751%2C20.46634%3B53.76603%2C20.46462#map=17/53.76624/20.46518

### Your Environment
OsmAnd Version: 4.3.5
Android/iOS version: 13
Device model: Samsung

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
offline maps of Warmian-Masurian Voivodeship

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14157mqta, released: 2023-02-07
<details><summary>Done</summary>
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/217208872-7a6e7dd5-b3a0-4cb9-8118-e30e0e062a1b.jpeg">
</details>

07.02.2023 Master branch
<details><summary>Done</summary>
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/217209076-156931c9-418b-4999-a692-0bed9507b940.png">
</details>
