### ISSUE TITLE
OsmAnd sometimes just quits or hangs for a long time

### ISSUE THREAD

**Issue by ericzolf** [osmandapp/Osmand#1619]
Sorry for the very vague description but I haven't find a way yet to properly reproduce and provide more information but since version 2.x and the new GUI (and Lollipop 5.0.2 on Xperia Z1 compact), OsmAnd is less stable and either has hangers from which it sometimes recovers (and sometimes I just quit it forcefully) and sometimes it just quits (no crash report whatsoever).
I would tend to say that it happens when there is an action on my side like start navigation, or locate an address on the map, but without clear pattern.
Let me know what I can do with helping to find the issue, I couldn't find any FAQ article on debugging issues.

**Comment by vshcherb** [comment]
It could be related to UI memory consumption, you could monitor it in Development Settings. If it is growing to the limit that a bad sign.

We fixed some allocations after 2.1 release and they will be in OsmAnd 2.2

If you have more information please provide it.

**Comment by asd-and-Rizzo** [comment]
I has this frequenly on samsung galaxy 5 on latest version on fdroid. Sometimes same time I change horizonal vertical position of phone. Downgraded to 1.9.x where thing are fine.

**Comment by asd-and-Rizzo** [comment]
I bought official app on gplay pre 2 era. Will donate few more if 2.x will become stable on my samsung galaxy s5 and be ensured that really do not need exit button.
