### ISSUE TITLE
World map has inconsistent "local names" with OpenGL vs legacy rendering 

### ISSUE THREAD

**Issue by TheSnoozer** [osmandapp/OsmAnd#16205]
### Description
Country names are not localized to the user language with Map Rendering V2 (OpenGL)

![photo_2023-01-10_17-20-42](https://user-images.githubusercontent.com/6849390/211606012-cb3e1894-9fd5-424d-b657-4eaea7eaf5bc.jpg)

### How to reproduce?
Enable Map Rendering V2 (OpenGL) and take a look on the world map.
Switch to Map Rendering V1 (Legacy), restart OsmAnd and take a look at the same world map.
County names are correctly localized  to the user selected language under Map Rendering V1 (legacy), but not Map Rendering V2 (OpenGL).

### Your Environment
Device : RE513CL1
Brand : realme
Model : RMX3241
Product : RMX3241EEA
Build : RMX3241_11_C.05
Version : 12
App Version : OsmAnd+
Apk Version : 4.3.5 4305

**Maps used (online or offline):**   
Offline

**Comment by scaidermern** [comment]
Can't reproduce here (or am I missing something?).

OsmAnd 4.3.5, OpenGL, map labels set to German, same zoom level as you. Resulting labels are in German:
![IMG_20230110_211741](https://user-images.githubusercontent.com/1040784/211653563-fe88eb2e-d361-4165-8392-3af53f7810be.jpg)

**Comment by TheSnoozer** [comment]
Interesting. I did some more investigation.

Under Settings -> OsmAnd settings -> Display Language I have set "System (device language)".
However there seems yet another language setting under Settings -> Browse Map (profile) -> Configure Map -> Map language (almost at the buttom) which is set to "Local names" on my end.

Now with "Settings -> Profile -> Map language" ==  "Local names" and Rendering V2 (OpenGL) I actually see the "Local names" of the country names (as reported). 

With "Settings -> Profile -> Map language" ==  "Local names" and Rendering V1 (Legacy) I see the country names displayed in the "Settings -> OsmAnd settings -> Display Language" which is "System (device language)". So under rendering V1 the "Map language" under the profile doesn't seem to have an effect.

I have no issue changing my settings around, but that feels a bit inconsistent. Is that behaviour desired? Could you try reproducing? 

If reproducible and not desired I would change the description to "Rendering V1 (Legacy) does not honor the Map language configured on the profile".

**Comment by vshcherb** [comment]
Indeed we need to stick to the previous behavior as it had no issue so far

**Comment by vshcherb** [comment]
Test

**Comment by scaidermern** [comment]
> Could you try reproducing?
> 
> If reproducible and not desired I would change the description to "Rendering V1 (Legacy) does not honor the Map language configured on the profile".

Yes, I can reproduce this. Rendering v1 displays label in the app language (=display language) and not in the map language. Which feels wrong. However, this bug only exists for the world map. Individual country maps are fine.

**Comment by ivanPyrohivskyi** [comment]
Compare with legacy rendering
Base map language
https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/src/net/osmand/plus/render/MapRenderRepositories.java#L750

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14198mqta, Released: 2023-02-24
Done

**Comment by DmitryAlexei** [comment]
https://docs.osmand.net/docs/user/map/vector-maps#map-language
https://docs.osmand.net/docs/user/personal/global-settings#display-language
