### ISSUE TITLE
White text on light grey background

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/Osmand#1620]
on 2.2.0#12699M 29.8.2015 5pm using the dark theme, in the main menu is white text on light grey background. it is hard to read the text. 
![screenshot_white](https://cloud.githubusercontent.com/assets/11144987/9563034/017a02c2-4e7b-11e5-92b5-1e901935ec63.png)

greetings simon

**Comment by franco999** [comment]
Me too.. And..
![2](https://cloud.githubusercontent.com/assets/12088580/9569915/f782962c-4f50-11e5-8f67-7b409bd7f3b6.png) ![1](https://cloud.githubusercontent.com/assets/12088580/9569916/f78e8482-4f50-11e5-848f-4157474cef70.png)

**Comment by jf-simon** [comment]
I can confirm this also

**Comment by sonora** [comment]
Yurii, thanks for fixing! Please see my comment on your commit b074344. Thanks, Hardy
