### ISSUE TITLE
"poi_climbing_bolted_filter" phrase is empty

### ISSUE THREAD

**Issue by MarioSwitch** [osmandapp/OsmAnd#16208]
At line 196 of [phrases.xml file](https://github.com/osmandapp/Osmand/blob/master/OsmAnd/res/values/phrases.xml), the string is empty.

With some translators, we want to translate [this string on Weblate](https://hosted.weblate.org/translate/osmand/phrases/en/?checksum=2b20c73f814bb5f3) and we can't because it's empty.

Thanks!

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/commit/380df91fe48164a9a916e0e5281b2204ea2be868
