### ISSUE TITLE
Routing.xml (master)

### ISSUE THREAD

**Issue by twikedk** [osmandapp/OsmAnd#16213]
### Description
Something looks wrong here, either it is not working or it is a hardcoded function and I guess that is then wrong too.

![Screenshot_2023-01-11_16-44-33](https://user-images.githubusercontent.com/24204069/211852025-ab25d098-908e-443c-a543-eb1c27603411.png)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14125mqta, released: 2023-01-24
Done
[Map](https://drive.google.com/file/d/11_gBlnBIQG_-SSMtQ5rHmmFNRE1aFUWk/view?usp=sharing) here
`50.27907, 11.52421`
<img width="1137" alt="Screenshot 2023-01-24 at 12 01 21" src="https://user-images.githubusercontent.com/104760013/214263000-ff26446c-57ed-455f-8b34-b707945a87c6.png">


https://user-images.githubusercontent.com/104760013/214262828-743ff96d-7876-4a27-93b6-fece15a3778e.mp4
