### ISSUE TITLE
Wikipedia layer can't be activated

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16210]
### Description
Wikipedia layer can't be activated
[logcat (42).log](https://github.com/osmandapp/OsmAnd/files/10393165/logcat.42.log)

### Steps to reproduce
Configure map > Wikipedia

### Actual result
Wikipedia layer can't be activated

https://user-images.githubusercontent.com/104760013/211829839-0a8fb864-fe58-401a-bbc7-216648fa93df.mp4

### Expected result
Wikipedia layer is activated after enabled

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14086mqta, released: 2023-01-11
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by Nine-Tailed** [comment]
working again
OsmAnd~ 4.4.0#14106mqta, Дата выпуска: 2023-01-16

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14117mqta, released: 2023-01-20
Done
