### ISSUE TITLE
speed camaras while routing

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/Osmand#1621]
today a got a warning about a speed cam, but didn't saw it on my way.
later i saw it on the road ahead, witch i left a road before the speed cam.
![screenshot_speedcam](https://cloud.githubusercontent.com/assets/11144987/9563067/968313ae-4e7b-11e5-8b8c-355213985e86.png)

shouldn't osmand only warn of speed cam on the route?
Also the warnings of speedcams an also crossings comes very early.

Greeting simon

**Comment by OpenSourceForEver** [comment]
Maybe You have checked Announce nearby POI in Navigation settings -> Announce...

**Comment by jf-simon** [comment]
in "show alarms" speed cameras are enabled. in "announce" "speed cams" is enabled, "announce nearby poi" is disabled.
i think, when in navigation mode, osmand only should warn of speedcams on the route, in "view mode" warn all speed cams which are nearby on the street on

**Comment by OpenSourceForEver** [comment]
IHave you got this problem in other speed cameras? Could you tell me where is the speed camera you have this problem?

**Comment by jf-simon** [comment]
i only recognised it on this speed cam. not sure for others. i will observe
	
https://www.openstreetmap.org/node/979522800#map=19/48.58866/8.67390

**Comment by OpenSourceForEver** [comment]
Is really the cam in this point? I have moved the cam to the way because it was not on the way but I do not know if it is the problem.

**Comment by jf-simon** [comment]
it doesn't matter where the speed cam is. speedcams can be tagged as notes on the street or as a note of the real possition which Relation:enforcement http://wiki.openstreetmap.org/wiki/Relation:enforcement
i asked for the way when speedcams are shown in osmand.

**Comment by vshcherb** [comment]
OsmAnd supports relation enforcement (camera could be in the other place) and supports speed camera on the way.

OsmAnd doesn't support camera without relation and not on the way

**Comment by vshcherb** [comment]
I think it is related issue to https://github.com/osmandapp/Osmand/issues/1196, so I will merge into it.
