### ISSUE TITLE
avoid roads

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/Osmand#1622]
in my opinion actually it is hard to select the road to avoid.
while in navigation mode i want to select the street to avoid
i tap the display -> select the settings icon -> tap on the "construction icon" -> "select on map"
then osmand brings me back on my current position. than i have to scroll back to the road i want to avoid. wouldn't it better to stay on the current screen position? because when i have to avoid a street, i have to park my car(while driving it is not allowed to use the phone in Germany) , scroll around and look how long the street is, and which to select.
also if i know a street to avoid before starting a trip, it would be good to be able to select to road over the long press menu.
only some thinking of mine

greetings simon

**Comment by vshcherb** [comment]
Thanks for feedback.

**Comment by sonora** [comment]
I think this is deprecated now, because we changed the interface and made Avoid roads sticky.
