### ISSUE TITLE
OpenGL freeze upon resume before app restart

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#16235]
This may not be a use case or issue on its own, but it seems a reliable way to create a 'freeze' scenario:

- Run the app using the Version 2 rendering engine
- Go to `Settings > Map rendering engine` and set to Version 1. The app will immediately correctly change the rendering to Version 1.
- Now tap the device's home screen button to put OsmAnd in the background
- Then retunr to OsmAnd

The app will have fallen back to a gray, empty, Version 2 type map scren which seems frozen (no map being displayed also after trying to pan or zoom), while all lapp menus still react. Only after killing the app and restarting it,  it will come up fully responsive and finally in Version 1 mode for good.

**Comment by vshcherb** [comment]
Probably related - https://github.com/osmandapp/OsmAnd/issues/16235
