### ISSUE TITLE
maxspeed:backward issue

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/Osmand#1623]
on 2.2.0#12699M 29.8.2015 5pm osmand ignores the maxspeed:backward tagging.
https://www.openstreetmap.org/way/330766428#map=17/48.56598/8.58353&layers=D
on the road from south to north, i see the 100km/h speed limit icon, in the 70km/h speed limit area, nothing is shown in the widget. after that, the 100km/h icon is back.

greetings simon

**Comment by vshcherb** [comment]
Fixed, Please test it with nightly.

**Comment by jf-simon** [comment]
Sorry not working with last nightly, now 100km/h is always displayed. Even in the 70 zone. On a other street it seems that osmand displays the speedlimit from speedlimit:forward

**Comment by aceman444** [comment]
Cool, is 2.2 supposed to finally support maxspeed:backward/forward? Thanks!

**Comment by hakuchi** [comment]
in 2.2.4 backward/forward is not supported.
the crossing looks like a maxspeed=none street

**Comment by vshcherb** [comment]
Just tested works fine on the specified segment

**Comment by jf-simon** [comment]
i have tested this issue yesterday and have still problems. means, backward and forward maxspeed isnt't handled right.
Have a look at this location http://osm.org/go/0DkDjC8OR-?layers=N&m=
when driving on "Pfalzgrafenweiler Straße"  at the crossing to "Schwarzwaldstraße" there is maxspeed "70 km/h" from the south to the north. This is backward in the osm data line direction. all works fine.
But coming from north to south. there is always "100 km/h". In the segment where maxspeed:backward=70 AND maxspeed:forward=100 is tagged, osmand ignores the 100 value.
While simulating the route, you can see, that osmand "recognize" the "70 km/h" maxspeed value, be course the "maxspeed widget" is not show on screen.
See this video: 
https://www.dropbox.com/s/dt5ikg3hq71xqsl/Pfalzgrafenweiler%20Stra%C3%9Fe.mp4?dl=0 

If you have a look here. There its similar. http://osm.org/go/0DkMM~lAg-?m=
Through the city on "Neubulacher Straße" from north to south there is a short segment of "40 km/h". When driving from north to south on the "40 km/h" segment, no maxspeed widget is shown.
From the south to north "40 km/h" is shown, what is wrong. The way in osm data is from north to south.
See videos:
https://www.dropbox.com/s/qcr40yx2qo6eep5/Neubulacher%20Stra%C3%9Fe%20SouthNorth.mp4?dl=0
https://www.dropbox.com/s/jlh77j2vephxcbt/Neubulacher%20Stra%C3%9Fe%20NorthSouth.mp4?dl=0

Greetings Simon
Using 2.4.0 #18094M

**Comment by hakuchi** [comment]
"maxspeed:backward issue" is fixed.
maxspeed:backward is 100% supported in OsmAnd 2.4.3

maxspeed:forward is not displaying in 2.4.3 so I think, you should report this as new "maxspeed:forward issue"
