### ISSUE TITLE
Permanent altitude offset (80m) between widget and contour lines

### ISSUE THREAD

**Issue by arncor** [osmandapp/OsmAnd#16242]
### Description
As far as I remember, it was present in 4.2 already. World altitude correction is present (I don't know if it's related).

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/91597340/212492160-a82221ef-2344-49ba-8240-7be65efc6462.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

Edit: 45°11′22.4″ N, 05°37′36.0″ E 

The correct altitude is the one from the contour lines.

### How to reproduce?
Display altitude widget and contour line.

### Your Environment
OsmAnd+ Version: 4.3.6
Android version:9
Device model: Armor Ulefone 6E

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14172mqta, Released: 2023-02-12
As you can see in the video, the heights in the widget and on the contour lines are identical

Try updating the app (or downloading the latest nightly version) and resources and check again.
Maybe it's a custom profile or other settings + please send route coordinates and GPX if you are navigating on a track


https://user-images.githubusercontent.com/104760013/218301444-bdd36b2c-b4b9-4434-8186-8b033597d5e9.mp4

**Comment by sonora** [comment]
@arncor Just as a consistency check: When you tap your (red) MyPosition icon on the map, then pull up its context menu, it reports an elevation value consistent with what the altitude widget says, right?

This really sounds like the 'World altitude correction'  is not present, or somehow not used. Can you try deleting and re-downloading it .(I just notice it seems displayed only on the 'All downlosds' tab, is missing on my 'Local' tab.)

If this does not fix it: What coordinates is your screenshot for? We could see what the nominal altitude correction is there, maybe that provides a hint.

**Comment by arncor** [comment]
Hey, thanks a lot for following up with this issue.

I just installed the lasest nightly (OsmAnd Nightly 4.4.0#35421m, Released: 2023-02-11 ) which shows a +50m altitude difference with osmand+ 4.3.7 (tested just where I live).

When I downloaded world altitude correction on the nightly, I didn't change anything.

On both versions, when tapping on my location I got the same altitude as the widget, with 1m vertical precision.

When using other apps, gps status or satsat, I got a -49m altitude !

**Comment by sonora** [comment]
Could it be that your chipset has something like a built-in altitude correction, have you tried after deleting OsmAnd's World altitude correction? Then restart the device, how does it look then?

**Comment by sonora** [comment]
PS: The geocorrection at your given coordinates as per https://www.dcode.fr/earth-elevation is +67m, so using your screenshot 678 m + 67 m = 745 m would fit?

**Comment by arncor** [comment]
> Could it be that your chipset has something like a built-in altitude correction, have you tried after deleting OsmAnd's World altitude correction? Then restart the device, how does it look then?

My device is equipped with a barometer, and a basic app which shows 88m of altitude, based on the ambient pressure (no correction is available, lol).

On both the nightly and 4.3.7 :
- with altitude correction : same altitude as the dcode website
- without altitude correction (removed + app restart) : 50m above

**Comment by arncor** [comment]
> PS: The geocorrection at your given coordinates as per https://www.dcode.fr/earth-elevation is +67m, so using your screenshot 678 m + 67 m = 745 m would fit? That would mean the correction is somehow not applied.

I don't see any mention of geocorrection, only 745m with these coordinates

**Comment by sonora** [comment]
Apologies, I must have misread the output,  geoid corection is +51m at the given coordinates.

So it sounds like it's working for you now as expected?

**Comment by arncor** [comment]
> Apologies, I must have misread the output, geoid height is +51m at the given coordinates. I.e. a correction of -51m must be applied to the bare GPS reading to arrive what is called 'above mean sea level'.
> 
> So if the corrected value coincides with what the web page (and the contour line) says, it sounds like it's working for you now as expected?

Yep, it sounds like it's working. I'll double check that on my next excursion in the mountains, next week I hope!

**Comment by sonora** [comment]
I knw the area around the Isere has narrow gorges, so it may well be that the GPS altitude reading has some uncertainty.

If in doubt, check the precision displayed on the MyPosition's context menu, and if bad look for a more open spot to take an altitude reading, or trust your contou lines. By GPS design, vertical precision suffers more than hoizontal precision under tricky circumstances.Hope this helps! Have fun!

**Comment by vshcherb** [comment]
Success with testing

**Comment by sonora** [comment]
I m convinced this is hardware-specific.
- Can you provide a screenshot both with OsmAnd's "World Altitude Correction" present and with it being deleted from the system (please kill and restart OsmAnd in between,)
- Also, it would be interesting to have from any GPS Status etc. app on your system a concurrent screenshots at that time ... Thanks!
