### ISSUE TITLE
Coast rendering issue near Sihanoukville

### ISSUE THREAD

**Issue by nils-werner** [osmandapp/OsmAnd#16246]
### Description

At zoom level 12 ocean and land are rendered inverted on the coast off [Sihanoukville](https://osmand.net/map?pin=10.63669,103.49379#12/10.63669/103.49379).

It doesn't happen in zoom levels 11 and 13.

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/88704/212523088-3d341248-139f-4493-87a0-f0594d54e5b2.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/88704/212523090-a50c488e-a63c-4bc3-829b-7e1de2946b47.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/88704/212523092-09493dab-b597-4e29-baa6-0af0f03dfb12.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### How to reproduce?

Go to [Sihanoukville](https://osmand.net/map?pin=10.63669,103.49379#12/10.63669/103.49379) on zoom level 12. Observe the behavior.

### Your Environment
OsmAnd Version: 4.3.5, OpenGL Rendering on
Android/iOS version: Android 10
Device model: OnePlus 5T

**Maps used (online or offline):**   
Offline Cambodia, 1st December 2022

**Comment by Zirochkabila** [comment]
https://user-images.githubusercontent.com/104760013/212989256-6a161dcd-d635-4c15-b8e7-c67b5cb1d02a.mp4

**Comment by Zirochkabila** [comment]
https://user-images.githubusercontent.com/104760013/212989368-daacdd25-720c-4aaf-81ed-05da93852106.mp4

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14194mqta, Released: 2023-02-22
22.02.23 master
Done
