### ISSUE TITLE
Missing translation leaves POI edit tab title blank

### ISSUE THREAD

**Issue by helinko** [osmandapp/OsmAnd#16245]
### Description

I added the Finnish translation on weblate but I assume there are languages where the issue still exists. I could fix it with some ad hoc way, but is there a standard way to do this elsewhere in the codebase?

The line is here: https://github.com/osmandapp/OsmAnd/blob/7e3fc7792f73d2d91f95cf3dd3123c1c91e39f59/OsmAnd/src/net/osmand/plus/plugins/osmedit/dialogs/EditPoiDialogFragment.java#L183

![1](https://user-images.githubusercontent.com/12040063/212497798-2e9da72e-f11f-4d14-b52a-5a16719ee11b.png)

![2](https://user-images.githubusercontent.com/12040063/212497800-9ffadd33-0e8e-4ec2-b29b-e1b4bac20e6e.png)

### Your Environment
OsmAnd Version:
Android/iOS version:
Device model:

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by vshcherb** [comment]
Unfortunately I see somebody added empty lines 
https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/res/values-fi/strings.xml#L1863
```
    <string name="commit_poi"/>
    <string name="osmand_parking_plugin_description"/>

```
Please translate these 2 via weblate
