### ISSUE TITLE
Wrong street name language selection when Map Language is "Local names"

### ISSUE THREAD

**Issue by yrtimiD** [osmandapp/Osmand#1624]
When map language is set to "Local names" some streets names are shown in local language (name tag) and some in English.
Both street types have name and name:he tags for local language, and name:en for English.
When I switch language either to English or Hebrew - all streets are shown in defined language.

example:
Shown in English: http://www.openstreetmap.org/way/103192781
Shown in Hebrew: http://www.openstreetmap.org/way/30795844
![osmand_street_language](https://cloud.githubusercontent.com/assets/816805/9567078/95bde7c2-4f26-11e5-89bf-82af4d8bd97f.jpg)

Version: latest nightly 2.2.0#12695M (but issue exist for at least month)

**Comment by vshcherb** [comment]
Can't reproduce it with fresh maps https://www.dropbox.com/s/m1ux4tuwa7x3430/Screenshot%202015-08-30%2023.34.25.png?dl=0.

May be the issue is in the maps itself.

**Comment by yrtimiD** [comment]
On your screenshot is a main osm site, right?
My screenshot - is from android osmand app  offline rendered map.

**Comment by xmd5a2** [comment]
I already done that. Can't reproduce at all.

**Comment by yrtimiD** [comment]
Fully re-installed app and re-downloaded maps - all work perfect. Probably some internal configs were broken.
Closing.

**Comment by yrtimiD** [comment]
Just another check, please: using "Israel - roads only" map.
Thanks.

**Comment by vshcherb** [comment]
Not reproducible
