### ISSUE TITLE
Sunset/Sunrise Map Mode: Set Only 60s After Startup

### ISSUE THREAD

**Issue by Dollarius** [osmandapp/OsmAnd#16251]
### Description
It takes at least 60s after startup for the map to be set in day/night mode when "map mode = sunset/sunrise".

### How to reproduce?

1. Open OsmAnd after sunset: the map will appear in day mode
2. Only after 60s, the app will start changing something (widget colours)
3. After 10s more, the map will turn to night mode.

![image](https://user-images.githubusercontent.com/56419637/212642417-3941574c-3632-48f7-8b9f-de41e0a8f746.png)

Please note that OsmAnd remembers the last location even without a GPS fix (dot shown on map, sunrise/sunset times correctly shown on widgets).

### Your Environment
OsmAnd Version: OsmAnd 4.4.0#35253, released:2023-01-12
Android/iOS version: 13
Device model: Samsung Galaxy S20 FE

**Maps used (online or offline):**   
Offline vector maps with overlay raster maps.

**Comment by MarioSwitch** [comment]
Also happens to me

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14172mqta, Released: 2023-02-12

Good point - OsmAnd does take about 30 seconds (in my case) to switch the card to night mode, or vice versa.

[logcat (58).log](https://github.com/osmandapp/OsmAnd/files/10715670/logcat.58.log)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14236mqta, Released: 2023-03-14
[logcat (75).log](https://github.com/osmandapp/OsmAnd/files/10970339/logcat.75.log)
Switching to night mode works in 2 seconds
But the transition to day mode does not occur (Enable location > Device settings > Change time > Back to OsmAnd > Nothing)
It's possible that a similar situation occurs when switching to night mode, but I can't check, as OsmAnd reopens - you can see it in the first seconds of the video


https://user-images.githubusercontent.com/104760013/225049438-34a74948-b0f6-4fca-bcb2-c6e234dbedb6.mp4
