### ISSUE TITLE
GPS signal position is blocked and goes to the previous one

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16259]
### Description
While recording a track, the GPS signal is occasionally blocked and the position jumps to an older one. When you manually disconnect and reconnect the GPS, the track restarts, moving from the old to the current position.
`It seems that when there is no GPS, we get a point with the old location from the system`
[2023-01-12_13-56_Thu (1).gpx.zip](https://github.com/osmandapp/OsmAnd/files/10434195/2023-01-12_13-56_Thu.1.gpx.zip)

### Workaround
Install Osmand version 4.2.7 and Android API for location detection

### Your Environment
OsmAnd Version: 4.3.5
Android/iOS version: Android 11.
Device model: Xiaomi redmi note 8

**Comment by vshcherb** [comment]
```
   <trkpt lat="50.6747" lon="4.6481983">
        <ele>160.1</ele>
        <time>2023-01-12T13:08:37Z</time>
        <hdop>1.8</hdop>
        <extensions>
          <osmand:heading>289</osmand:heading>
        </extensions>
      </trkpt>
```

These wrong points could be filter by minimal speed.
