### ISSUE TITLE
The map isn't displayed

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16254]
### Description
If change the rendering V2 > V1 > lock and unlock the screen - map isn't displayed
[logcat (47).log](https://github.com/osmandapp/OsmAnd/files/10427084/logcat.47.log)

[Please check it too ](https://github.com/osmandapp/OsmAnd/issues/16098#issuecomment-1378856087)

### Steps to reproduce
Menu > Settings > OsmAnd settings > Map rendering engine > V1 > Lock screen > Unlock screen 

### Actual result
Map isn't displayed

https://user-images.githubusercontent.com/104760013/212712769-9837e00b-700d-4283-85b3-15de39e98870.mp4

### Expected result
Map is displayed and compass will work

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14106mqta, released: 2023-01-16
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by scaidermern** [comment]
I can reproduce this on Android 10.

**Comment by sonora** [comment]
#16235

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14114mqta, released: 2023-01-18
Done
