### ISSUE TITLE
Cannot Enable Engine v2 (OpenGL) on Galaxy S20 FE

### ISSUE THREAD

**Issue by Dollarius** [osmandapp/OsmAnd#16258]
### Description
If I understand correctly, the v1 rendering engine will be phased out (no more support/bug fixing).
On my 2-year-old phone (Samsung Galaxy S20 FE), which was "almost" a top-of-range phone, I cannot enable the v2 rendering engine.
The option (under Settings/OsmAndSettings/MapRenderingEngine) is available, but cannot be selected (grayed out?)

![image](https://user-images.githubusercontent.com/56419637/212796407-9796308d-f11c-44a6-b2db-826a850f4bc1.png)

### How to reproduce?
Install any OsmAnd-android-full or OsmAnd-default release and try enabling v2.

I can only enable the v2 engine if I install the release OsmAnd-opengl-arm-nightly, but after doing so the app crashes every 30 seconds.
What am I doing wrong?

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#35282m, released: 2023-01-16
Android/iOS version: 13
Device model: Samsung Galaxy S20 FE

**Comment by pebogufi** [comment]
Did you dnl and install
https://download.osmand.net/latest-night-build/OsmAnd-android-full.apk ?
 This is ONLY v1, NOT OpenGl.
Use 
https://download.osmand.net/latest-night-build/OsmAnd-opengl-arm64-nightly.apk
for Samsung and OpenGl (v2).

**Comment by Dollarius** [comment]
Thank you for the clarification: I was mislead by the "default" and "full" nomenclature of the files.

I can enable v2 after installing the opengl-arm64 version.
I will try to report separately why such version with v2 enabled crashes very often on my device.
