### ISSUE TITLE
wrong way of creation a map

### ISSUE THREAD

**Issue by mariush444** [osmandapp/OsmAnd#16264]
### Description

I noticed some wrong routing/navigation in Osmand and this is one example.
![wrong-routing](https://user-images.githubusercontent.com/66887280/213022865-9795230c-395d-4d97-a573-52dc280282b9.jpg)

Data seems to be OK in OSM.
https://www.openstreetmap.org/#map=19/52.27744/21.06734
![osm-org](https://user-images.githubusercontent.com/66887280/213023044-244d84ae-b060-4ca1-9aa8-55f9cff9cc63.png)

but I noticed something strange in Osmand. The street is divided into 2 lines. It can be seen in very high zoom.
If the right line (of north dir.) is chosen then the navigation goes wrong. The navigation goes OK when left line (of north dir.) is chosen.
![doubled-street](https://user-images.githubusercontent.com/66887280/213024016-229d8006-d2aa-4de9-8ed4-35940e40df2b.jpg)

It seems that there is a bag during creation of the obf. Maybe because of line asistence. Just guessing.
Anyway, this is street with 3 lines for north and with 3 lines for south direction.

### Your Environment
OsmAnd Version: 4.2.7
Android/iOS version: 11

**Maps used (online or offline):**   
Poland Mazovia Warsaw

**Comment by vshcherb** [comment]
It's probably an artifact with enabled OsmAnd live, it's likely related to the rendering but not to the routing. Please test with fresh maps / on off (live updates)

**Comment by scaidermern** [comment]
Indeed, the rendering looks like #14920.

**Comment by mariush444** [comment]
@vshcherb 
I do NOT use live updates. This is related to the ROUTING.
When you  click on right line of the route the routing is wrong.
When you click in the left line of the route the routing is OK.
Then it is NOT related to ANY artifact.

When one uses low zoom then user don't know where is problem with routing but now the reason is known.
The question is just when there is a source of the problem.

Just do it, test it, please.

**Comment by scaidermern** [comment]
@mariush444 I've tried to reproduce this but here everything is fine. No duplicated road even when zooming in.

Please check if you have duplicated maps installed for this region.
