### ISSUE TITLE
Map rendering v2 crash log can't be forwarded plus map rendering engine v2 stays set

### ISSUE THREAD

**Issue by TheSnoozer** [osmandapp/OsmAnd#16263]
### Description
Hello, thanks for osmand!

In the past days I have a weird crash when opening osmand after my phone went on hibernate.
Unfortunately I only can randomly reproduce the issue. When it happens I see a dialogue explaining that map rendering engine V2 (opengl) crashed and osmand switched back to map rendering v1 (legacy).

The problem really is that
- the exception.log seems to be an empty file and can not be attached to eMails, saved in the google drive, or forwarded using a messaging app.
- after the crash the map rendering engine V2 is still selected, so while osmand claimed it switched the engine to V1 on the UI one still sees the V2 selected even after restarting the app multiple times

Here is a screenshot of the dialogue
![photo_2023-01-17_21-00-33](https://user-images.githubusercontent.com/6849390/213000152-fda46f9e-305d-429e-9492-ca2d5fb548f4.jpg)

A logcat generated directly after such "crash" doesn't reveal any exception of problem at all. So far I was unable to reproduce with "adb logcat". An "adb bugreport" doesn't contain any (new) tombstone crash log that could reveal any more information.

### How to reproduce?
No idea.

### Your Environment
Device : RE513CL1
Brand : realme
Model : RMX3241
Product : RMX3241EEA
Build : RMX3241_11_C.05
Version : 12
App Version : OsmAnd+
Apk Version : 4.3.6 4306

**Maps used (online or offline):**   
Offline

**Comment by vshcherb** [comment]
Yes it's correct fail safe behavior, so we display this dialog on 3rd crash in a row and let user change to map rendering engine v1 if it doesn't work correctly but we keep v2 set, so user will restart and get v2 rendering engine on.
