### ISSUE TITLE
Set app default to hide proposed objects

### ISSUE THREAD

**Issue by WizoneDE** [osmandapp/OsmAnd#16262]
### Description
At the moment the map shows highway with the tag proposed as a transparent dashed road.

Since these are only ghost roads of maybe later planned roads, which aren’t even in a planning process or building process. (highway=construction) they should not be draw in the map.

https://wiki.openstreetmap.org/wiki/DE:Tag:highway%3Dproposed

### How to reproduce?
Example positions:
https://www.openstreetmap.org/way/697074943
https://www.openstreetmap.org/way/697074616

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/35132439/212973469-80dc6f30-be0c-4939-a063-a4efdaf1069e.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Your Environment
OsmAnd Version: 4.3.3
Android/iOS version: iOS 16.2
Device model: iPhone 14 Pro 

**Maps used (online or offline):**   
Online and offline

**Comment by scaidermern** [comment]
This is a (imho badly chosen) default. You can disable them: Configure map / Hide / Proposed objects.

**Comment by WizoneDE** [comment]
thx. yes should be hide by default

**Comment by xmd5a2** [comment]
@Zirochkabila where are proposed objects on your screenshots?

**Comment by dmpr0** [comment]
Done
<table style="width:100%">
  <tr>
    <th colspan=2>iOS</th>
    <th colspan=2>Android</th>
  </tr>
  <tr>
    <th>Off</th>
    <th>On</th>
    <th>Off</th>
    <th>On</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/226350128-cce7b0c5-9839-468f-be1b-c8c7a1e2af09.PNG"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/226350095-87c38d79-510a-474d-9c84-3c3d01e156b7.PNG"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/226350495-a6a78f7b-b0eb-4c3b-93d1-8adf4cdd7749.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/226350510-a33a4bdb-5bc9-40ab-8b6c-7e82e19bf6bb.png"  width="300" height="auto"/> </td>
  </tr>
</table>
