### ISSUE TITLE
"Native library not supported on this device" while the app is in background (and supposed to be stopped)

### ISSUE THREAD

**Issue by Max1234-Ita** [osmandapp/OsmAnd#16269]
### Description
In my device (Samsung Galaxy A50 with Android 11, non-rooted), I keep getting pop-up messages saying _"Native library not supported on this device"_. Such messages are displayed from time to time, apparently randomly, either while the device is idle or I'm browsing the Internet, reading emails, etc.

The weirdest thing is that when it happens, I have (supposedly) exited OsmAnd! No navigation nor track recording is ongoing, it's just like it'is keeping to run in background even if I have quit it.
Not sure if this is similar to #14947 / #15157 .

Attaching a logcat file, hope it helps.

> Device : a50
> Brand : samsung
> Model : SM-A505FN
> Product : a50eea
> Build : RP1A.200720.012.A505FNXXS9CVJ2
> Version : 11
> App Version : OsmAnd+
> Apk Version : 4.3.6 4306

[logcat.log](https://github.com/osmandapp/OsmAnd/files/10444195/logcat.log)

### How to reproduce?
1. In the device's power options, set OsmAnd as "Never put to sleep"
2. Launch OsmAnd, download a map for current location;
3. Wait for position to be fixed;
4. Set the rendering engine to OpenGL
5. Do some activity, i.e. browse the map around and/or search for an address;
6. Exit OsmAnd (with the "**<**" device button) and go back to the Android Home screen 
7. Do some activity, i.e. launch other apps
8. Lock the device
9. Wait for some time (can be a few minutes or a couple hours)
10. Unlock the device
11. Perform some activity for some time (i.e. read emails or launch a web browser) and check if the "Native library not supported on this device"
12. Open OsmAnd and check if error message appears: "_OsmAnd's map rendering has recently crashed_"
 (see picture below)
![Screenshot_20230115-171225_OsmAnd+](https://user-images.githubusercontent.com/15315381/213135312-4d869ed2-6790-4b5d-bee8-5f097fc7ae57.jpg)
13. At this point, map rendering is set to "native" (at least in my case).

### Your Environment
OsmAnd Version:  4.3.6 from Google Play Store
Android/iOS version: Android 11
Device model: Samsung Galaxy A50 (SM-A505FN)

**Maps used (online or offline):**   
Offline vector maps. I have the maps of entire Italy installed on my device and current position is in Lombardy Region, but I guess it happens with any map.

**Comment by TheSnoozer** [comment]
Sounds related to https://github.com/osmandapp/OsmAnd/issues/16263

Maybe even a duplicate.
Perhaps one question: when the crash happens the application asks If you want to share the crash log. Does that work for you?

**Comment by Max1234-Ita** [comment]
> Sounds related to #16263
> 
> Maybe even a duplicate. Perhaps one question: when the crash happens the application asks If you want to share the crash log. Does that work for you?

Apparently the crash happens while the app is in backgrond: I'm doing a different activity in that moment.
The error is then reported as soon as I reopen OsmAnd (see the picture I attached).

One thing has come to my mind: I've set the power options in my device so that OsmAnd is never put to sleep. Perhaps you are doing the same?

Maybe  many users don't experience this since they are using the normal setting and all the apps in background are put to sleep after some time.

Moreover, I would expect OsmAnd not to be running at all, since no navigation nor track recording is in progress and I've exited the app (it sounds quite strange to me having to "kill" the process by removing it from the Recent Apps list).

**Comment by Max1234-Ita** [comment]
[exception.log](https://github.com/osmandapp/OsmAnd/files/10715806/exception.log)
Exception log collected from OsmAnd+ v. 4.3.6.

Also tried with 4.3.8 (I have OsmAnd Free 4.3.8 on the same device) but in that case every attempt to export the log fails (invalid attachment whatever the selected app).

Perhaps exception logs are also stored in some directory reachable by a non-root user?

**Comment by Zirochkabila** [comment]
This issue is similar to this one https://github.com/osmandapp/OsmAnd/issues/16504
So far, I haven't been able to reproduce it - it looks like it's done

**Comment by Max1234-Ita** [comment]
> This issue is similar to this one #16504 So far, I haven't been able to reproduce it - it looks like it's done

Thanks for your reply.
In what version shall the fix be implemented? I will also check on my device and provide feedback.
