### ISSUE TITLE
Bike route going up a highway=steps

### ISSUE THREAD

**Issue by utack** [osmandapp/Osmand#1626]
Just found out when planning a bike route and there is a 
"highway=steps"
connecting two
"highway=cycleway"
the router goes up the steps with a bike.
Example:
https://www.openstreetmap.org/way/339406348#map=19/48.05517/11.53222
(Ignore the small loop around the steps, I added this after testing the situation described above)
Should be a very quick fix, hopefully

**Comment by utack** [comment]
Just found out the steps in question are part of a bike route:
https://www.openstreetmap.org/relation/2080238
Poor tagging in this case, but it should still be useful to blacklist steps from any bike routing

**Comment by utack** [comment]
Suppose you should not blacklist them entirely but weigh them worse and treat the mas bicycle=dismount, if that is already in place in your router?

**Comment by james2432** [comment]
You should definitly not disable them entirely, in Canada I know of some bike paths that you have no choice in going up staires/downstaires to reach destination

**Comment by aceman444** [comment]
Steps are already penalized for bikes, having a default speed of 1km/h, compared to e.g. 18km/h on a cycleway. So OsmAnd should only take steps if there is no better way around.

**Comment by vshcherb** [comment]
May be I'm using something wrong, but I can't really reproduce it.

**Comment by vshcherb** [comment]
Just generated new piece of map

**Comment by vshcherb** [comment]
The line was edited 10 days ago https://www.openstreetmap.org/way/368307966, may be that's a reason.

**Comment by utack** [comment]
It is indeed the cause for the new route.
It correctly weighs the steps as very slow and now goes the correct path around.
Sorry for reporting that issue in the first place, I could not find anything about this being intentional and correctly calculated, thought it is a bug.
