### ISSUE TITLE
Unexpectedely Straight -> TSLL and TR -> C

### ISSUE THREAD

**Issue by mdykierek** [osmandapp/OsmAnd#16279]
### Description
Consider this intersection: https://www.openstreetmap.org/?query=50.24253%2C18.99567#map=19/50.24254/18.99568
When following Mikołowska South to North the intersection with Parkowa shows 3 slight left lanes and 1 through.
However, in OSM https://www.openstreetmap.org/way/234238770 the lanes count is 3 and turn:lanes are "through|through|through;right"

### How to reproduce?
Navigate Mikołowska S-N direction through mentioned intersection.

### Your Environment
OsmAnd Version: OsmAnd+ 4.3.6
Android/iOS version: Android 11
Device model: Mi 9t Pro

**Maps used (online or offline):**   
January 2023 offline. Checked live updates too (same result).

**Comment by vshcherb** [comment]
- https://www.openstreetmap.org/way/234238770#map=17/50.24178/18.99694
- https://creator.osmand.net/map?start=50.241795%2C18.995994&end=50.247116%2C18.998247&mode=car#18/50.24217/18.99702

Through (Straight) turn indicator is replaced turn slightly left.

**Comment by vshcherb** [comment]
Probably related with #1 from https://github.com/osmandapp/OsmAnd/issues/16752

**Comment by vshcherb** [comment]
# 1 
`44.386406, 26.139163`
[Map](https://drive.google.com/file/d/17elaUq3aawwMQrbViKqNvXBK_GD5T26L/view?usp=sharing)
[OSM](https://www.openstreetmap.org/way/23766846#map=17/44.38592/26.14041)
[OsmAnd](https://osmand.net/map/?start=44.387949%2C26.140938&end=44.383416%2C26.137730&mode=car#17/44.38602/26.13932)


https://user-images.githubusercontent.com/104760013/227515365-42186839-af21-498d-8143-16864930f1fe.mp4

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/16279
