### ISSUE TITLE
Building param overwrites amenity information

### ISSUE THREAD

**Issue by WizoneDE** [osmandapp/OsmAnd#16275]
### Description
If there is a building with Tag building=yes and amenity=* OsmAnd shows building instead of the amenity tag in details 

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/35132439/213217912-76c60c3f-d30b-481d-ab7c-6c2c24d39517.png"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/35132439/213217955-611329fa-e7cc-462b-8957-78571781e2dd.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

### How to reproduce?
example poi as buildling
https://www.openstreetmap.org/way/239869477

### Your Environment
OsmAnd Version: 4.3.3
Android/iOS version: ios16.2
Device model: 14 pro

**Maps used (online or offline):**   
Online and offline map with 1h update

**Comment by vshcherb** [comment]
@Zirochkabila test android as well

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14120mqta, released: 2023-01-22

(Live Updates) When searching for a gas station, the amenity fuel tag works, as it displays Shell Petrol station

https://user-images.githubusercontent.com/104760013/213926543-930d0bbe-d2db-4307-b25a-c0517f1d6321.mp4

**But**, when using a newly generated [map](https://drive.google.com/file/d/1oV2uDY9Cef0xMq45N1xzlNpf983CLPvM/view?usp=sharing), the "amenity" tag is preferred

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/213926844-36cc40e0-b78e-4664-a24c-b3f1588f2f22.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by scaidermern** [comment]
I've seen similar cases caused by live updates. For example after adding the tag `internet_access=wlan` to a restaurant OsmAnd displays "internet access" instead of "restaurant" when tapping on this POI. After the next base map update this problem disappears.

**Comment by vshcherb** [comment]
Minor issue, we're going to fix with other live updates issue.
