### ISSUE TITLE
destination:foward and destination:backward on the streets with both directions on a single way

### ISSUE THREAD

**Issue by razor74** [osmandapp/OsmAnd#16278]
Hi, i observed that Osmand did not read correct some destination tags on the streets with both directions on a single way. This feature is already supported on Id Editor and Josm. In this case Osmand will anounce destination in both ways, no matter if the anounced city is on a specific direction only. 
One example is here on the crossroad between Strada emil Racovita and Strada Turnu Magurele. On two segments from Strada Turnu Magurele there is destination:forward an backward tags.

Thanks

# 🚀 feature request

**Comment by razor74** [comment]
related tags: destination:forward and destination:backward

**Comment by Zirochkabila** [comment]
@razor74 Please add expected and actual result

**Comment by razor74** [comment]
Hi. Fore example if destination:backward is Giurgiu and the route takes me on forward direction ( as destination:forward) which is opposite with Giurgiu, osmand tell me that i drive in direction of Giurgiu, which is wrong. It couldnt make difference of the right direction. I think i explained very well for the first time.

**Comment by Zirochkabila** [comment]
@razor74 If I understood your query correctly - you are moving in the direction of Strada Turnu Magurele and turn right at the intersection to Strada Emil Racovita. OsmAnd displays Strada Emil Racovita as your destination, which is logical given that you are moving in that direction.
<details><summary>Strada Emil Racovita</summary>
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/219864036-fa090896-8f9d-4cfd-a886-850bfb2a6fdf.jpeg">
</details>

**Comment by Zirochkabila** [comment]
@razor74 If you mean that the route from `44.37938, 26.12944` to `44.38047, 26.12653` sounds like 

https://user-images.githubusercontent.com/104760013/219961400-bee6edaa-cac5-482f-bb4c-cdbdc5bccc73.mp4


And, for the route from `44.38047, 26.12653` to `44.37938, 26.12944` it sounds like 


https://user-images.githubusercontent.com/104760013/219961428-2e3ef745-50cb-4f06-8216-42f453ffa59a.mp4


Perhaps this is due to the fact that the changes destination:forward - Oltenița;Constanța are added only here https://www.openstreetmap.org/way/853255596#map=19/44.37934/26.12806 but not here https://www.openstreetmap.org/way/853255595#map=19/44.37923/26.12859

**Comment by razor74** [comment]
Now does not work anymore  in both direction. No city anounce with
destination:forward or backward. The tag is correct because it works on
Magic Earth Navigation& Maps.

dum., 19 feb. 2023, 18:34 Anatolii ***@***.***> a scris:

**Comment by razor74** [comment]
Hello. Today with the last night version worked again . I drive from Strada
Emil Racovita  an turn left on Strada Turnu Magurele. Osmand anounced that
Oltenita and Constannta are in that direction. I will see tonifht when i
come back if it anounce the same towns in the opossite direction.

dum., 19 feb. 2023, 23:36 Razvan ***@***.***> a scris:

**Comment by Zirochkabila** [comment]
@razor74 Since you didn't write, were similar places announced when you returned?

**Comment by razor74** [comment]
Hi. I already responded in that night.

dum., 26 feb. 2023, 11:31 Anatolii ***@***.***> a scris:

**Comment by razor74** [comment]
Not i not working correct. I was only able to test again today. When i come on Strada Turnu Magurele from Soseaua Oltenitei to Bulevardul Constantin Brancoveanu, no audio intruction is gived. There is destination:backward = Giurgiu tag on street segment marked with blue. Audio intruction works only on  segment marked with g
![Screenshot 2023-03-20 202555](https://user-images.githubusercontent.com/5586993/226432874-5df38327-609b-436e-9e77-0e4996881948.png)
![Screenshot_2023-03-20-18-57-41-906_net osmand plus](https://user-images.githubusercontent.com/5586993/226432881-7c50b9e5-7c97-4f37-a240-b15d855e523a.jpg)
reen when destinatio:forwar tag is.
