### ISSUE TITLE
No recalculation on a portion of map which seems to have a compilation bug.

### ISSUE THREAD

**Issue by razor74** [osmandapp/OsmAnd#16277]
![photo_2023-01-17_23-03-06](https://user-images.githubusercontent.co
![photo_2023-01-18_10-57-31](https://user-images.githubuserconten
![photo_2023-01-18_10-57-30](https://user-images.githubusercontent.com/5586993/213256181-ded9060c-dc9c-44f1-8257-8e7fc1a74f37.jpg)
t.com/5586993/213256169-56c4f16d-0472-483f-9422-2de92c6268d2.jpg)
m/5586993/213256155-4609a88f-73a1-46da-a6a9-64f9abf3efbd.jpg)

https://www.openstreetmap.org/#map=19/44.40485/26.18603

Hi. From some time ( almost 3 months) i have a problem with routing recalculation on a street which contains a roundabout. Navigation  route suggest another path on a street from vicinity, but i want on this street because is more convenient for me. After some discussions on Telegram i come here in order to report this problem. I found something which probably has to do with routing problem there. A roundabout keep to be unlinked from streets even if openstreetmap data is correct.  I will attach some images and a link on that roundabout.
Osmand cannot route or recalculate route trough that road between Drumul Lunca Cetatii and Bulevardul Theodor Pallady. I drive almost daily on that street. I came from the left from Drumul Lunca Cetatii and take left trough that roundabout on Drumul Lunca Bisericii and Aleea Mizil until i reach Bulevardul Theodor Pallady and continue until i reach Ikea Pallady. Osmad will anounce one more time to turn around and came back to the initial route and after that no recalculation until i reach this point on Bulevardul Theodor Pallady where Socar Gas Station is. https://www.openstreetmap.org/#map=19/44.40770/26.19195   With or without daily update for the map, the problem persist. It seems to me to be a map compilation problem. possibly from that unlinked roundabout in the map database.

# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [x] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

</code></pre>

**Device and Android/iOS version:**

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.

- [x] Online (tile / raster) maps 

**Anything else relevant?**

**Comment by razor74** [comment]
![photo_2023-01-17_23-03-06](https://user-images.githubusercontent.com/5586993/213258225-aa9b9e6e-77f0-47f0-95ca-e23c17e263bc.jpg)

**Comment by razor74** [comment]
![photo_2023-01-18_10-57-31](https://user-images.githubusercontent.com/5586993/213258268-876cff3e-b654-4c38-9397-eb2a73705c5e.jpg)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14120mqta, released: 2023-01-22

[Expected place of recalculation](https://osmand.net/map/?start=44.398973%2C26.183424&end=44.407957%2C26.206448&mode=car#16/44.4027/26.1969)

<img width="1422" alt="Screenshot 2023-01-22 at 21 32 25" src="https://user-images.githubusercontent.com/104760013/213936932-0eef038c-7e3e-4b5e-b08c-cc848f22ae6b.png">


[Route](https://drive.google.com/file/d/10u-w__5PxP3Nni138GK_U1GhF3ItWSnL/view?usp=sharing) isn't recalculated
[Map](https://drive.google.com/file/d/1U942CEDYWkubkvcAU4gyExZNDUyyomLZ/view?usp=sharing) here 


https://user-images.githubusercontent.com/104760013/213936869-b00ae5b1-85bb-4b33-9b93-a33e8b030378.mp4

**Comment by razor74** [comment]
I come from the left  where i drawed with blue, te last recalculation is where i point with red, just near that roundabout where is the train track and recalculation start again after 1 km on Bulevardul Theodor Pallady where is Socar Gas Station ( i drawed red arrow).

![213936932-0eef038c-7e3e-4b5e-b08c-cc848f22ae6b](https://user-images.githubusercontent.com/5586993/213982383-31ed4f24-1deb-41ac-9a28-cf9b9f01a990.png)

**Comment by razor74** [comment]
Hi. The same situation with the last map. Maybe will help you to know that some of the turn lanes added with two map releases ( in the past) not apeared in this map. There are in the osm database but not work in osmand. It seems some more road data is missing in that zone, or for some reason are not compiled in the map. These turn lanes are near that roundabout from the bottom image, others are in that round intersection near Ikea.

**Comment by Dima-1** [comment]
Also fixes #16475

**Comment by razor74** [comment]
Nothng is fixed. And again this roundabout apears disconnected from other
street links.

lun., 27 feb. 2023, 10:01 Dmitry ***@***.***> a scris:

**Comment by Dima-1** [comment]
> Nothng is fixed. And again this roundabout apears disconnected from other street links. lun., 27 feb. 2023, 10:01 Dmitry ***@***.***> a scris:



Request not accepted yet

**Comment by vshcherb** [comment]
iOS should be fixed as well

**Comment by vshcherb** [comment]
1. Android native routing
2. Constant in the code

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14217mqta, released: 2023-03-04
4.4.6.2
Done

**Comment by razor74** [comment]
Thanks alot.Works perfect now. There is no annoing aditional recalculation
when i turn back on a route.

dum., 5 mar. 2023, 12:56 Anatolii ***@***.***> a scris:

**Comment by sonora** [comment]
@razor74 Thanks for the feedback!

**Comment by razor74** [comment]
Hi. there is a problem with history page after this update. All history 
dissapeared, and nothing registered again. The page history remains 
empty after few destination search and driven routes.
