### ISSUE TITLE
Problem when interpreting maxspeed:conditional date syntax

### ISSUE THREAD

**Issue by Peter0** [osmandapp/OsmAnd#16289]
### Description
Going on highway from 50.72452/7.16195 to 50.71959/7.14463, since turn of the year from 2022 to 2023 Osmand doesn't display the temporary speed limit of 80 km/h anymore. I suppose that the syntax of tag "maxspeed:conditional" isn't interpreted correctly. This tag has "80 @ (2019 Oct-2024 Dec)" as value, meaning the "80" is valid from october 2019 until end of december 2024. I suppose that it will be interpreted as valid only from october until december, disrespecting that the years from 2020 until 2023 (or, in fact, even 2024) are meant completely from january until december.

### How to reproduce?
Use 50.72452/7.16195 resp. 50.71959/7.14463 (in Bonn, Germany) as starting resp. destination point.
Use navigation simulation (or go there in real life).
Tick in order to take temporary constraints into account.
Observe the maximum speed that is displayed by the navigation directions GUI.

### Your Environment
OsmAnd Version: 4.2.6
Android/iOS version: /e/OS corresponding Android 9
Device model: Samsung Galaxy J5 (2015)

**Maps used (online or offline):**   offline
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
Germany_nordrhein_westfalen_cologne-government-region_europe – live updated today 1:20

Ciaoi – Peter

**Comment by ivanPyrohivskyi** [comment]
- [ ] C++

**Comment by Zirochkabila** [comment]
Done

<details><summary>OsmAnd~ 4.4.0#14194mqta, Released: 2023-02-22</summary>
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/220685397-cbbae3bc-0773-4ed9-a176-3b7391f85b54.jpeg">
</details> 


<details><summary>22.02.23 master</summary>
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/220685609-eb268bcc-12e2-4f5c-bf01-aea1fc53731b.png"">
</details>
