### ISSUE TITLE
Routing ignores highway service roads even if public

### ISSUE THREAD

**Issue by WizoneDE** [osmandapp/OsmAnd#16282]
### Description
Endpoint routing oder start routing with a highway=service gets ingored.

was routing to the area WAB but instead of using the highway service to enter it it just follows the main road parallel till the middle of the area  and than drive through the forest right…

Same if you are on a highway service as starting point it gets completely ignored and the routing is just going straight to the main road.

![DC4E51CB-EA79-4B7D-A222-5ED881443A9A](https://user-images.githubusercontent.com/35132439/213438786-024c79e0-5692-4cf6-998c-c74f3ad52ef7.png)
![4D7CD655-C627-49A7-B7C4-4278941AD1F0](https://user-images.githubusercontent.com/35132439/213438808-8df4685a-1090-4b4a-9c4c-a730eb5ef129.png)
![5169888D-60FA-47FC-9B62-45586C545FDB](https://user-images.githubusercontent.com/35132439/213438816-30ce1fc4-23c8-4384-8d54-cbf28f652dca.png)

road has only "highway=service" tagged without access attributes. the gate has only  "bicycle=no foot=no" set

my expectation would be that end and start routing would use highway=service roads and only ignores its for longer dinstance routing
  

### How to reproduce?
example location: 
https://www.openstreetmap.org/way/217525396

### Your Environment
OsmAnd Version: 4.3.3
Android/iOS version: 16.2
Device model: iPhone 14 pro

**Maps used (online or offline):**   
online and Offline with 1h update

**Comment by scaidermern** [comment]
The reason is probably this gate: https://www.openstreetmap.org/node/2268071653
It doesn't have any access tags for vehicles specified. So the default is no.
