### ISSUE TITLE
Missed items when import settings 

### ISSUE THREAD

**Issue by Velomeloman** [osmandapp/OsmAnd#16298]
### Description
Quick action, Favorites, Markers history, Search history, Itinerary, Online routing engines, Map sources doesn't import from OSF files. 

### How to reproduce?
Export all settings or one profile. Check all available boxes. Then import created file. 
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/109347561/213811021-95e8386b-1f04-4fc5-9a91-ffc960ab3f11.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/109347561/213811079-c37ab1f0-e197-4643-9808-857b01bdf25d.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Your Environment
OsmAnd Version:4.4.0#14117

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14173mqta, Released: 2023-02-13
Done
