### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by anten1222** [osmandapp/OsmAnd#16290]
From my point of view, one of the biggest construction sites in Osmand is the navigation.  Longer routes don't work at all without intermediate destinations.  It works with an online service.  The calculation with Brouter on the smartphone as well.  Please fix this limitation
 Greetings Ludwig Anten

**Comment by vshcherb** [comment]
Yes, there are plans for that in 2023. It's likely a duplicate issue, so I will close it
