### ISSUE TITLE
Routing asking to get off highway

### ISSUE THREAD

**Issue by Gizmot** [osmandapp/Osmand#1629]
Problem 1 : Simulated Routing going West on Highway 50 in Quebec, Canada
Eastbound route seems to be going fine. While no expert, data in OSM also looks good.
from 
Lat 45.707, Lon -73.999
to
Lat 45.481, Lon -75.713

2 exemples:

Lat 45.65028
Lon -74.75066
![screenshot_2015-08-31-08-12-18](https://cloud.githubusercontent.com/assets/13919997/9578680/1977a524-4fba-11e5-8548-ce32d5283618.png)

Lat 45.62494
Lon -75.23539
![screenshot_2015-08-31-08-13-09](https://cloud.githubusercontent.com/assets/13919997/9578681/197aa33c-4fba-11e5-919c-f7b1b6e771eb.png)

Problem 2: Routing is asking to "turn slightly right" instead to "take exit".

**Comment by Gizmot** [comment]
found some 1-way highway section in osm...

**Comment by Gizmot** [comment]
Could be an OSM issue or not... data looks clean now

**Comment by stephan75** [comment]
see https://github.com/Project-OSRM/osrm-backend/issues/1632 about the missing update of the OSRM database.

The **only** up-to-date OSM based online router is IMHO Graphhopper ... but the web service **is not able**  to process with turn-restrictions so far :-( ... although there has been much effort by graphhopper developers recently.

**Comment by vshcherb** [comment]
If it is not OsmAnd data issue, then that issue could be closed. New maps are generated for OsmAnd already.
