### ISSUE TITLE
Regional locales not translated in Voice language menu (regression)

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#16297]
In the menu `Navigation settings > Voice prompts > Language` the display of all translations of locales which consist of more than just 2-character codes is broken. For example instead of  `en-gb-tts` the value of string `lang_en_gb` should be displayed, or instead of `hu-formal-tts` the value of string `lang_hu_formal`.

**Comment by sonora** [comment]
I think this broke it: https://github.com/osmandapp/OsmAnd/commit/2b42828ead164b273b57c64af4754baaf7ab98f2

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14119mqta, released: 2023-01-21
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/213864095-0f2734c9-ff48-47ca-8cd6-61646af425a2.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>
