### ISSUE TITLE
MapCreator crash

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1630]
https://dl.dropboxusercontent.com/u/4624786/osm/crash.zip
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f624b658f4b, pid=8562, tid=140060147525376

OsmAndMapCreator 10728MC crashes with this obf with old rendering engine but only in 90% cases. In OpenGL engine all is ok. Removing this obf helps.

**Comment by vshcherb** [comment]
Will be helpful: does it crash same style/obf on device?

**Comment by xmd5a2** [comment]
Can't reproduce with another PC and on android. What was that?

**Comment by xmd5a2** [comment]
But now latest map creator can't live on my primary PC longer that 3-4 times switching on-off offline rendering (without ANY maps in osmand dir!). Also it crashes when zooming out to zoom 2 in old engine. Very inconvenient.

**Comment by vshcherb** [comment]
Yes I confirm it crashes on zoom 2, but I guess it was always a case. So a different a may be less important. And I can't reproduce switch off issue.

You can check my changes https://github.com/osmandapp/OsmAnd-core/commits/legacy_core and I'm afraid it is hard to find the reason for such serious degradation, it could be related to the environment, either compiling or running. I would suggest to try compile it on the target environment, like "all linux program does". So far, I can't detect an issue.

**Comment by vshcherb** [comment]
The crash you send is related to italic issue and it is fixed. Please try it.

**Comment by xmd5a2** [comment]
Yes, now it does not crashes so frequently. Thanks!
