### ISSUE TITLE
Bicycle routing "Avoid footpaths" option avoids designated foot-cycleway when tagged using `highway=path`, `bicycle=yes/designated`, `foot=yes/designated`

### ISSUE THREAD

**Issue by 05storm26** [osmandapp/OsmAnd#16309]
Cycleway according to the wiki can be tagged as highway=path and bicycle=yes/designated. Optionally when it is a shared path foot=yes/designated can be added too.

OsmAnd bicycle route planning avoids these cycleways when the "avoid footpaths" option is turned on. This is incorrect. A highway=path can even be a dedicated cycleway, if there is a bicycle=designated tag on it, and there is no foot=yes/designated on it.

Avoid footpaths turned off:
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/8590289/214093916-e8edf5a1-115b-4d2d-ab59-252ca2aa479d.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

Turning it on ("Gyalogutak elkerülése", the last one):
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/8590289/214094015-85e0ee01-21c4-46f4-ad13-60ff56d471fc.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

Resulting plan after the option is turned on:
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/8590289/214094135-519b81c1-4c10-455b-ae10-dcbb9458f914.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

The location in the pictures is around at: 46.27243° N, 20.14569° E

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14172mqta, Released: 2023-02-12

In fact, everything is a little different - as you can see in the video, the route failure occurs only when the "No unpaved roads" + "Avoid footways" restriction is activated (by the way, this does not work only on the mobile application (the text below will give an example with the web version of OsmAnd), a combination of other modes was tested and only with this combination does the failure occur).

The fact is that errors in the Unpaved roads mode were described here https://github.com/osmandapp/OsmAnd/issues/16369, it seems that this behavior somehow affected those restrictions where No unpaved roads are used.

So, when you combine similar restrictions (in the web version), the route is built according to the expected scenario, i.e. the same as without the No unpaved roads restrictions.

Accordingly, if a route change (which should not happen, according to OSM tags, as well as building a similar route with similar restrictions in the web version) occurs only when "No unpaved roads" + "Avoid footways" is activated, and this does not happen in the web version, it is all about "No unpaved roads", which is confirmed by https://github.com/osmandapp/OsmAnd/issues/16369

[OSM](https://www.openstreetmap.org/way/38620662#map=17/46.27350/20.14305)
<details><summary>Asphalt</summary>
<img width="800" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/218325634-adcb0895-f462-4ef4-9fa1-9abfc4fb2413.png">
</details>

[OSM](https://www.openstreetmap.org/way/111148835#map=19/46.27293/20.14306)
<details><summary>Asphalt too</summary>
<img width="800" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/218325760-fbed568c-de64-495b-a10f-e9138df6e8a7.png">
</details>

[OsmAnd](https://osmand.net/map/?start=46.272407%2C20.145369&end=46.273891%2C20.142446&mode=bicycle#18/46.27316/20.14453)
<details><summary>"No unpaved roads" + "Avoid footways" </summary>
<img width="800" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/218326113-b37805c5-d69f-4418-98ff-de8e7f0ee8f1.png">
</details>

<details><summary>All the restrictions as in the condition</summary>
<img width="800" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/218326208-53e40a72-70e9-440c-9859-160946ee92f9.png">
</details>


https://user-images.githubusercontent.com/104760013/218325527-48421b0a-bbba-4b74-85d0-d2f6a5f4e165.mp4

**Comment by 05storm26** [comment]
Hi @Zirochkabila, awesome work, thanks for triaging this.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#14270mqta, Released: 2023-03-25
4.4.6.11
Done
