### ISSUE TITLE
Clear all history option do not remove info about previous route.

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd#16307]
### Description

Clear all history option do not remove info about previous route.

https://user-images.githubusercontent.com/116079541/214050652-e7173039-590d-4124-9a0a-6420d2a9f688.mp4

### How to reproduce?
Go to Settings > OsmAnd settings > History
Choose "Clear all history"
Check "Navigation history" in the same menu > you will see previous route.
Previous route is also shown in navigation function.

### Your Environment
OsmAnd Version: 4.3.8
Android/iOS version: 13
Device model:

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14163mqta, Released: 2023-02-09
Done
