### ISSUE TITLE
OpenGL: not yet uploaded notes have extra vertical offset

### ISSUE THREAD

**Issue by goldfndr** [osmandapp/OsmAnd#16318]
### Description

When an [OSM note is added](https://osmand.net/docs/user/plugins/osm-editing#create--modify-osm-note), the displayed icon for the note has its pin point at the bottom higher on-screen than it should be when using the Version 2 (OpenGL) engine. No apparent problem with the Version 1 engine or already uploaded notes.

The offset seems nearly the opposite of the text's in issue #14784's initial screenshots.

### How to reproduce?

1. Add an OSM note with arbitrary text. Don't upload yet, don't close the bottom sheet.
2. Make it (add the selected point as) a favorite.
3. Observe how zooming in/out keeps nearly all of the note icon at a constant vertical offset "above" the favorite icon with the OpenGL engine. Switching engines (Settings / OsmAnd Settings / Map rendering engine) shows a difference, no need to restart app.

### Your Environment
OsmAnd Version: 4.4.0#14120mqta, 2023-01-22 (but also at least 2 weeks earlier)
Android/iOS version: Android 13, security patch 2022-12-01, Google Play system 2022-10-01, One UI 5.0
Device model: Samsung Galaxy Z Fold3 5G

**Maps used (online or offline):**   
The issue is independent of the type of map displayed (vector vs raster) and tilt and map magnifier value.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14173mqta, Released: 2023-02-13
When using V1 rendering, the Favorites icon is more obviously displayed above Notes

https://user-images.githubusercontent.com/104760013/218494072-a0c5609e-67bc-44a1-ac6b-4bfc48707bf2.mp4

**Comment by vshcherb** [comment]
@Zirochkabila please double check that corner of triangle exactly in the center of the screen. So please compare with exact center - on video it's not clear whether v1 or v2 is incorrect.

So you need to center map exactly with coordinates of entered point.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14187mqta, Released: 2023-02-18


https://user-images.githubusercontent.com/104760013/219866312-a0a06396-e76b-42f9-a8d0-cd512b617cca.mp4

**Comment by vshcherb** [comment]
Indeed not centered
<img width="180" alt="Screenshot 2023-02-19 at 14 41 52" src="https://user-images.githubusercontent.com/1042025/219948631-fd32def9-4ec7-4a95-86b6-302b2e32437d.png">

**Comment by goldfndr** [comment]
Possibly related:  [OsmEditsLayer.java#L443](https://github.com/osmandapp/OsmAnd/blob/07f28dcbb28799afebcb03eec81bb19e00a9a4bc/OsmAnd/src/net/osmand/plus/plugins/osmedit/OsmEditsLayer.java#L443) uses MapMarker.PinIconVerticalAlignment.Top vs MapMarker.PinIconVerticalAlignment.CenterVertical

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#698m, released: 2023-08-30
Bottom point of the Osm note is almost always in the center of the screen. Very small shift (offset) can be observed only at close or far zoom levels (see video). The shift (offset) is more significant when 3d relief is enabled (I think this is not within the scope of this task). 

https://github.com/osmandapp/OsmAnd/assets/116079541/64882d79-ffb0-49c2-aeb6-5400fdbd95bb



<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/7b24be30-3b56-4c17-9b86-71bf5dc89412"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/9d0a4eb3-7e4b-4c1e-bdab-231641ee0c4b"  width="300" height="auto"/> </td>
  </tr>
</table>
