### ISSUE TITLE
Bus lines not visible at zoom 15 and higher

### ISSUE THREAD

**Issue by arncor** [osmandapp/OsmAnd#16311]
### Description
Using openGL. Bus lines aren't displayed at zoom 15 and higher
Edit : only using the "public transportation" profile

### Your Environment
OsmAnd Version: 4.3.7
Android version: 9
Device model: armor 6e (ulefone)

**Maps used (online or offline):**   
OsmAnd mapstyle

**Comment by scaidermern** [comment]
Can't reproduce. Bus lines are working fine for me from zoom levels 11-22. OsmAnd 4.3.7, Android 10.

**Comment by arncor** [comment]
Update : it doesn't work only when using the "public transportation" profile.
When using the "walking" profile and displaying the bus stops and bus lines there is no problem

**Comment by scaidermern** [comment]
They work in all of my profiles :thinking:

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14172mqta, Released: 2023-02-12
Bus routes are displayed at all zoom levels - as previously mentioned by @scaidermern 
Try updating OsmAnd and check again


https://user-images.githubusercontent.com/104760013/218306712-4cd358d3-89b6-43ce-ae29-9794b354aa28.mp4

**Comment by arncor** [comment]
Hey, thanks for testing.
I still got rhe issue with 4.3.7 but it's fixed in OsmAnd Nightly 4.4.0#35421m, Released: 2023-02-11
(I just downloaded the nightly and imported the settings and profiles from my daily 4.3.7) thanks !

**Comment by Zirochkabila** [comment]
@arncor Can this issue be considered closed?

**Comment by arncor** [comment]
> @arncor Can this issue be considered closed?

Yes, thanks :)
