### ISSUE TITLE
Extend AIDL Intent API to start track navigation at the starting pount of the track

### ISSUE THREAD

**Issue by mfroehler** [osmandapp/OsmAnd#16314]
# 🚀 feature request

### Description

I already had mailing contact with your colleague Eugene and was told to post my issue in a feature request here.

Context:

We (my company) needs navigation for winter service or street service vehicles. Something like this (https://rasco.hr/de/news/eine-weitere-erfolgreiche-transformation-ein-nutzfahrzeug-wurde-in-ein-winterdienstfahrzeug-umgewandelt/) or this ( https://de.dreamstime.com/stockfotos-stra%C3%9Fenreinigungsfahrzeug-3-image5181083 )

Such vehicles usually have a daily track they have to fulfill to keep the streets free from snow or dirt. In the morning the vehicles usually all start at the same point, when the drivers load the track in OSMAND. It would be great the vehicles are now navigated to the start of the track and then along the track.

We plan to develop a intermediate android app that would call OSMAND via intent to start track (gpx) navigation with the track the current vehicle has to fulfill. 

The problem is that a winter service should always start his work on the starting point of the track (In OSMAND Option: “start of the track”) and not at the nearest point on the track. But when we start a gpx navigation with the AIDL intent api the default is the nearest point of the track.

See here https://osmand.net/docs/user/navigation/gpx-navigation/  "Start of the Track" vs. "Nearest Point"

### Describe the solution you'd like

I suppose the "navigateGpx(in NavigateGpxParams params);" in the AIDL API must be extended. The NavigateGpsParams need an additional parameter to select if the track navigation should use "Nearest Point" or "Start of the Track"

### Describe alternatives you've considered

Introduce a parameter in navigation settings to configure this for all track navigations started. But I think the upper solution could be better.

Thanks in advance and hope to hear from you soon.

**Comment by vshcherb** [comment]
Yes we plan to review it quick enough

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14189mqta, Released: 2023-02-20
Done
