### ISSUE TITLE
Unintuitive Visible POI selection.

### ISSUE THREAD

**Issue by GaidamakUA** [osmandapp/Osmand#1632]
Conditions:
- Editing POI plugin is on
- Map preferences
- Show Checkbox
- See list with checkboxes
- Select some
I can't find any way to save selection. There are only cancel button. Seems like the only thing you can do is to click on list item and only that item will be selected. Those checkmarks are misleading.

**Comment by vshcherb** [comment]
It is not a bug and we have a plan for this, to enable multiselect, that's why it is closed
