### ISSUE TITLE
OsmandPreference vs. CommonPreference

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#16323]
In `OsmandSettings.java` we distinguish between `OsmandPreference` and  `CommonPreference`. Which characteristics determine if a setting should be one or the other?

I am trying to assist with harmonizing our settings UI along the guidance @EugeneZmeuk communicates here https://github.com/osmandapp/OsmAnd/issues/16157#issuecomment-1401682405. It turns out that e.g. most of our "General profile settings" are `OsmandPreference`, but a few are `CommonPreference`, the latter not using the same bottom sheet templates, but mostly custom dialog. Is one or the other preferred? And is conversion of one group to the other in scope for the sake of harmonizing the settings UI?

**Comment by Chumva** [comment]
OsmandPreference is an interface for all preferences, and CommonPreference is used for all our preferences except APPLICATION_MODE.
