### ISSUE TITLE
Bad czech translation of standpipe

### ISSUE THREAD

**Issue by michalspondr** [osmandapp/OsmAnd#16326]
This should be "Vodní pumpa". "Požární hydrant" is something else.

https://github.com/osmandapp/OsmAnd/blob/3ad4b2ee85a1f956a97d4462c8e507470b2a1889/OsmAnd/res/values-cs/phrases.xml#L693

**Comment by scaidermern** [comment]
You can fix the translation here: https://hosted.weblate.org/projects/osmand/

**Comment by michalspondr** [comment]
I've translated it.
