### ISSUE TITLE
Issue SQLITE file rendering for OpenGL  

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#16338]
### Description

After some time scrolling OsmAnd map with SQLITE Overlay, OsmAnd rendering slows down. After 3-5 minutes, OsmAnd crashed.

Logs from Android Studio
[Archive 5.zip](https://github.com/osmandapp/OsmAnd/files/10518148/Archive.5.zip)

The device is hot.

### How to reproduce?

OpenGL engine rendering.
SQLITEdb file - 3Gb (Overlay layer)

### Your Environment

Device : beyond0
Brand : samsung
Model : SM-G970F
Product : beyond0ltexx
Build : SP1A.210812.016.G970FXXUGHVJ5
Version : 12
App Version : OsmAnd~
Apk Version : 4.4.0#14131mqta 4400
[exception (1) (20).log](https://github.com/osmandapp/OsmAnd/files/10517971/exception.1.20.log)

Device : surya
Brand : POCO
Model : M2007J20CG
Product : surya_eea
Build : SKQ1.211019.001 test-keys
Version : 12
App Version : OsmAnd~
Apk Version : 4.4.0#14131mqta 4400

[exception (48).log](https://github.com/osmandapp/OsmAnd/files/10517979/exception.48.log)

**Maps used (online or offline):**   
SQlitedb file ~3Gb

**Comment by Zirochkabila** [comment]
May be related to https://github.com/osmandapp/OsmAnd/issues/15968 - application behavior is similar

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14139mqta, released: 2023-01-31
Done
