### ISSUE TITLE
Can't see nor select external SD storage

### ISSUE THREAD

**Issue by monnier** [osmandapp/Osmand#1634]
I just got a Galaxy Tab S running Android 5.0 and can't convince Osmand (2.1.1) to use the maps I have on my SD card (from an older tablet that was still running Android 4.0).

Originally, the files were in /storage/extSdCard/osmand, and based on information I found here and elsewhere on the Internet, I tried to move it to /storage/extSdCard/Android/data/net.osmand.plus/,
/storage/extSdCard/Android/data/net.osmand.plus/osmand, as well as /storage/extSdCard/Android/data/net.osmand.plus/files but none of them seem to be visible to Osmand.

Also in the preferences, when I try to change the storage location, I'm only offered /storage/emulated/0/osmand as option.  How can I convince Osmand to read (and store) maps on the SD card?

**Comment by vshcherb** [comment]
Could you please make a screenshot in OsmAnd Settings -> General -> Change app dir. I just wonder if it is only 1 option available there and what is that option

**Comment by monnier** [comment]
Hmm... well... looks like I was confused.  I didn't notice the little "crayon" icon on the right, which gave me access to a set of options.  So I guess my bug report should be changed into a request to change the UI:  

In my case at least, when I want to change the storage location:

- I go to the "general settings" where it tells me that the location is "/storage/emulated/0/osmand",
- then I click on this entry, and that gives me a confusing dialog box which just repeats this same information and has a little crayon icon.
- After clicking on the crayon icon I get a second dialog box which lets me choose the location I want.

I think you should simply remove the middle step since it seems useless.

**Comment by vshcherb** [comment]
Indeed we planned to change it for next release.
