### ISSUE TITLE
Nautical charts: display color segments

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#16341]
I received a feature request for our nautical charts to consider showing the color signature of beacons also in a colored circle segment fashion like 

![image](https://user-images.githubusercontent.com/845735/215269559-85761efc-1be5-4189-ab64-090fb5050d09.png)

**Comment by vshcherb** [comment]
Yes looks cool but I guess not possible with current rendering engine, only if generate these lines and circles on the server side but then they will be connected to the map data which is probably not what expected...

**Comment by sonora** [comment]
From how I understand it, they can and should actually be connected to the map data, and shown at certain zoom levels. See examples at e.g. https://webapp.navionics.com/?lang=en#boating.

**Comment by vshcherb** [comment]
Nope here in example it has a fixed "pixel sized" and not fixed size of "3 km" and rendering engine doesn't support rendering arcs of a fixed size

**Comment by quantenschaum** [comment]
see https://github.com/osmandapp/OsmAnd/issues/16894#issuecomment-1724202350

**Comment by vshcherb** [comment]
Merge to https://github.com/osmandapp/OsmAnd/issues/16894#issuecomment-1724202350 as we see a prototype there
