### ISSUE TITLE
Engine V2 ... disable tilt per profile

### ISSUE THREAD

**Issue by miramikes** [osmandapp/OsmAnd#16343]
Even tilt is great feature sometimes can be unwanted.
Sometimes tilt can be performed accidentally when rotating map by two fingers and trying to reset tilt you will return on your gps position.
So disabling tilt per profile can be useful I guess.
Cheers Mira

**Comment by scaidermern** [comment]
This is already possible: Settings / Profile / General settings / 2.5 D

**Comment by miramikes** [comment]
Thank you I could not find it.
I am going to close this issue.
Cheers Mira
