### ISSUE TITLE
Export: No progress visible when exporting maps

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#16346]
When exporting maps there is no progress visible. It looks like the app is just stuck. The progress bar displays NaN on the left and 0/0 on the right all the time. Exporting 2.6 GB of maps takes around 4-5 minutes with my device (Samsung S9, Android 10). The progress bar stays at 0 all this time.

OsmAnd 4.3.7.

**Comment by TheSnoozer** [comment]
Maybe related to https://github.com/osmandapp/OsmAnd/issues/16340?

**Comment by scaidermern** [comment]
> Maybe related to #16340?

I saw this other ticket but for me the export is working. Except for the progress bar.

**Comment by sonora** [comment]
The other ticket is for v4.3.6. I think there has been a series if fux-attempts in the last few minor releases, so we should use v4.3.8 as a basis for the current status quo.

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.4.0#14175mqta, released: 2023-02-14
Exporting 3,4 Gb of map data.
The progress bar doesn't move after about 7 min. from the beginning of “preparing” to export. After about 10,5 min. the process has suddenly ended, .osf file is ready for export. 

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/116079541/218722270-89459980-53af-436f-969d-016d01691461.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/116079541/218722285-e1efca43-3af4-4617-aae6-0a93075a88df.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
[logcat1.log](https://github.com/osmandapp/OsmAnd/files/10741627/logcat1.log)

**Comment by prallo** [comment]
Still not solved. Version 4.3.12 Pro version.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14208mqta, Released: 2023-02-28
Done
