### ISSUE TITLE
Routing trunk vs trunk_link

### ISSUE THREAD

**Issue by toas-koas** [osmandapp/OsmAnd#16356]
The APP routes down the street to the right and then back onto it to the left. Straight ahead would be faster. 

From:

Oberbürgermeister-Müller-Ring, B 17;B 300
Standort: geo:48.35828,10.85097?z=19
https://osmand.net/map?pin=48.35828,10.85097#19/48.35828/10.85097

To:
Standort: geo:48.36272,10.85315?z=19
https://osmand.net/map?pin=48.36272,10.85315#19/48.36272/10.85315

**Comment by TheSnoozer** [comment]
You can also plot routes:
https://osmand.net/map/?start=48.358280%2C10.850970&end=48.362720%2C10.853150&mode=car#17/48.36040/10.85462

With the default car profile this indeed seems to use the exit and then navigate you back to the road. The cost of that trip is estimated to be 30.
![Screenshot from 2023-01-30 23-08-20](https://user-images.githubusercontent.com/6849390/215607069-276f98ed-3fff-4f7f-ae20-ec59e596824e.png)

When specifically telling the profile to use the short route (via the settings button next to the profile) the navigation would not use the exit, but the trip is estimated to cost 34 (hence "more expensive")
![Screenshot from 2023-01-30 23-07-53](https://user-images.githubusercontent.com/6849390/215607260-9839df93-5019-4279-bcdc-2ce1c1d83796.png)

**Comment by toas-koas** [comment]
Then the routing algorithm is wrong.
First, I have to go right. Then the speed limit is no longer 60 but 50 km/h. Then I cross a road that I have to keep short because cars could cross my path. Then I'll get back to gas and I'll have to get back to the left.
Each of these points costs time and should be included.

**Comment by scaidermern** [comment]
Yes, looks like a bug. Usually these cases are caused by the link ways not having a maxspeed set or a maxspeed that is higher than the actual road. But this isn't the case here. The link road has a maxspeed that is equal or lower.

**Comment by vshcherb** [comment]
More precise numbers
Trunk 
```
calcTime: 0.086560624, distance: 668.0648, routingTime: 39.222507, time: 40.625565}
```
Trunk link 
```
{calcTime: 0.089737832, distance: 668.4041, routingTime: 37.777603, time: 32.13115}
```

According to distance and speed (60/3.6) ms, routing time should be 668/(60/3.6) = 40.08 but strangely it's smaller. Interesting case and very different, trunk_link has a penalty of 70%
```
<select value="1" t="highway" v="trunk"/>
			<select value="0.7" t="highway" v="trunk_link"/>
```
It should be enough to make it even smaller

**Comment by Zirochkabila** [comment]
If we take into account only the maximum speed limit, then the route should have been built without a right turn + according to driving practice, in such cases, the movement is straight.

However, the web version of OsmAnd shows such a route to be 4 units more expensive. I think this may be due to the fact that:
1. The route goes directly across the bridge, so the fuel costs will be higher
2. OSM GrapHopper and OSRM routing build a similar route (with a right turn), **512m - 0:01**
3. OSM Valhalla routing (with a straight line) - **513m - 0:01**

[OSM](https://www.openstreetmap.org/directions?engine=fossgis_valhalla_car&route=48.35831%2C10.85097%3B48.36271%2C10.85313#map=17/48.35884/10.85475)

**Comment by vshcherb** [comment]
```
<!-- maxspeed doesn't affect on motorway_link and trunk_link -->
			<select value="100" t="highway" v="motorway_link"/>
			<select value="90" t="highway" v="trunk_link"/>
```
To do: We need to introduce another rule which could be a min/max rule
```
<!-- maxspeed doesn't affect on motorway_link and trunk_link -->
			<min value1="100" value2="$maxspeed" t="highway" v="motorway_link"/>
			<min value1="90" value2="$maxspeed" t="highway" v="trunk_link"/>
```

**Comment by vshcherb** [comment]
+ tests preferrably
