### ISSUE TITLE
Add ability to attach to road via aidl 

### ISSUE THREAD

**Issue by christianCasRo** [osmandapp/OsmAnd#16350]
Hi there! 
I ask to add ability to set the option of "Attach to road" by AIDL.
When you have a gpx and want to start the route you need before to do some previous steps, (more than one) and if we  make it more easy with aidl maybe we can get like a predeterminate behaviour.
Thank you in advance

**Comment by nazar-kutz** [comment]
**Pull Requests**
* https://github.com/osmandapp/OsmAnd/pull/16923
* https://github.com/osmandapp/osmand-api-demo/pull/63 (AIDL API)
