### ISSUE TITLE
Directions transport type persistence behaviour

### ISSUE THREAD

**Issue by PinkDuck** [osmandapp/Osmand#1635]
For the following UI behaviour sequence:

Default map view: Browse map
Directions: Defaults to car
Change directions to pedestrian mode
End the directions
Directions again: Defaults to car again

I think that the user-chosen directions Pedestrian mode should be persisted instead of always converting the Browse Map view to Car by default. This would only need an extra variable to save the last used mode to use when starting directions from the Browse Map view.

This is particularly a nuisance when using default Browse Map view and using pedestrian navigation to go from one individual waypoint to the next, as each time the travel mode needs to be changed from Car to Pedestrian.

If I change the view from Browse Map to Pedestrian before directions then pedestrian mode is the initial profile. However, on exiting directions the chosen default Browse Map view is restored then using directions again similarly results in car navigation.

**Comment by vshcherb** [comment]
I agree, please test it in the nightly
