### ISSUE TITLE
map does not rotate following compass

### ISSUE THREAD

**Issue by ericJrdn** [osmandapp/OsmAnd#16352]
In osmand~4.3.8, the map does not rotate correctly following the compass, despite configuration.

![215467104-073588f4-9545-44db-90cc-5345def4a1af](https://user-images.githubusercontent.com/845735/215473599-0d54d663-08b3-4f14-8dd3-1aaeb7e9b4a5.png)

Function was last seen working on 4.3.3

**Comment by sonora** [comment]
Looks to me like it's working as expected: The red end of the arrow in your compass widget depicts magnetic south, hence points north.

In you picture it points form "_Pointe du Chemin de Puteaux_" towards "_Avenue Georges Clemenceau_", and checking 
OSM (https://www.openstreetmap.org/node/2542291592), "_Avenue Georges Clemenceau_" is just north of "_Pointe du Chemin de Puteaux_".

So the compass points right.  Possibly you have set the wrong map orientation? If you expect the map to be aligned with your direction of movement, tap on the compass icon until it displays not the magnetic compass needle but the blue direction of motion icon, or alternatively chose what you need under` Menu > Configure profile > General settings > Map orientation`.

**Comment by ericJrdn** [comment]
got this problem on two different phones. (android 10 and 13)
for a certain amount of time, the map rotates fine and follows the direction i'm pointing to. Then something happens and the software does not seem to see the direction has changed.

**Comment by ericJrdn** [comment]
Here is an example of what can happen
https://user-images.githubusercontent.com/64037055/216672060-109ae74d-f2b2-4ec2-b2a7-2ebc6fa2e859.mp4

[log2.txt](https://github.com/osmandapp/OsmAnd/files/10581499/log2.txt)

This time, it happened just after setting a route.

**Comment by sonora** [comment]
When for the app profile you use for navigation you go to `Menu > Configure profile > General settings`, what's the state of `Use magnetic sensor`? It's a long shot, but your log file is full of Power entries, so maybe you force OsmAnd to use the magnetic sensor for compass data, but there is some other process running on your device thinking it can turn the magnetic sensor of while in motion and GPS is on...

**Comment by ericJrdn** [comment]
It is off. One should remember i had the problem on two different phones with a nearly out of the box osmand configuration.

In the case i recorded, i found (and already knew, sorry) the answer : i set a route but did not press start.

I will continue to investigate with logcat. Thanks

**Comment by sonora** [comment]
Indeed, it seems that compass rotation is suspended if you calculate a route and then just follow it without starting the turn-byturn navigation. I believe the suspension is meant to only last while you set the destination, because it is e.g. close to impossible to use "Select on map" if the map spins. But I believe that the suspension after the route calculation has finished is likely a bug.

**Comment by ericJrdn** [comment]
The problem is in fact that my phone is fixed with a magnet in my car. Basically, the sensors get crazy with the magnet.
It seems to me that with the magnet, the only relevant orientation is the moving direction.
I'm now pretty sure that the problem is physics, not software.

**Comment by sonora** [comment]
Well, when I tried it, I actually found [this](https://github.com/osmandapp/OsmAnd/issues/16352#issuecomment-1416801398) which I think is a small but valid issue in our code.

Regarding magnetic fixation, it depends: Device rotation is deduced by _variations_ of the magnetic field strength as measured by y/y/z magnetic sensors, and using calibration the compass direction is derived. The presence of a strong and, relative to the device, static magnet attached to the back of the device would not normally interfere with the detection of these magnetic variations.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14175mqta, Released: 2023-02-14
[logcat (61).log](https://github.com/osmandapp/OsmAnd/files/10731132/logcat.61.log)

The situation described by the user in https://github.com/osmandapp/OsmAnd/issues/16352#issuecomment-1416213141 is reproduced when you select any profile and any compass mode - **But, after calculating the route, the map corresponds to the compass direction and changes in accordance with the turn.**
The behavior shown in the video is probably a different bug.


https://user-images.githubusercontent.com/104760013/218702252-73dd5b1f-a416-4668-b9e5-dfe1888ad589.mp4

**Comment by ericJrdn** [comment]
i'm very disappointed by your logs. They look similar to mine.

In particular, we have this in common : 
_02-14 11:48:16.017  7556  7556 E ContextImpl: java.lang.IllegalAccessException: Tried to access visual service WindowManager from a non-visual Context:net.osmand.plus.OsmandApplication@e22b28f
02-14 11:48:16.017  7556  7556 E ContextImpl: 	at android.app.ContextImpl.getSystemService(ContextImpl.java:2070)
02-14 11:48:16.017  7556  7556 E ContextImpl: 	at android.content.ContextWrapper.getSystemService(ContextWrapper.java:869)
02-14 11:48:16.017  7556  7556 E ContextImpl: 	at android.content.Context.getSystemService(Context.java:3955)
02-14 11:48:16.017  7556  7556 E ContextImpl: 	at android.widget.ToastPresenter.<init>(ToastPresenter.java:83)
02-14 11:48:16.017  7556  7556 E ContextImpl: 	at android.widget.Toast$TN.<init>(Toast.java:661)
02-14 11:48:16.017  7556  7556 E ContextImpl: 	at android.widget.Toast.<init>(Toast.java:172)
02-14 11:48:16.017  7556  7556 E ContextImpl: 	at android.widget.Toast.makeText(Toast.java:518)
02-14 11:48:16.017  7556  7556 E ContextImpl: 	at android.widget.Toast.makeText(Toast.java:506)
02-14 11:48:16.017  7556  7556 E ContextImpl: 	at net.osmand.plus.OsmandApplication.lambda$showShortToastMessage$1$net-osmand-plus-OsmandApplication(OsmandApplication.java:720)
02-14 11:48:16.017  7556  7556 E ContextImpl: 	at net.osmand.plus.OsmandApplication$$ExternalSyntheticLambda4.run(Unknown Source:4)
02-14 11:48:16.017  7556  7556 E ContextImpl: 	at android.os.Handler.handleCallback(Handler.java:938)
02-14 11:48:16.017  7556  7556 E ContextImpl: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-14 11:48:16.017  7556  7556 E ContextImpl: 	at android.os.Looper.loopOnce(Looper.java:210)
02-14 11:48:16.017  7556  7556 E ContextImpl: 	at android.os.Looper.loop(Looper.java:299)
02-14 11:48:16.017  7556  7556 E ContextImpl: 	at android.app.ActivityThread.main(ActivityThread.java:8319)
02-14 11:48:16.017  7556  7556 E ContextImpl: 	at java.lang.reflect.Method.invoke(Native Method)
02-14 11:48:16.017  7556  7556 E ContextImpl: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
02-14 11:48:16.017  7556  7556 E ContextImpl: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)_


It means a non ui thread tries to modify the ui. It probably does not have a lot of things to do with the problem (it's just the text information that pops at the bottom of the screen, i guess), but it's bad.

@sonora : do you know if it this second problem could be solved?

**Comment by sonora** [comment]
Sounds like a Toast message placed in the wrong method, potentially even just a left-over of some debugging attempt. Cannot currently tell from the log where this occurs, in any case not sure there is a causality with the issue at hand (but could be).

**Comment by vshcherb** [comment]
Confirmed in 4.3 map doesn't rotate if you are in "Route planning mode", it looks like it was done to display route correctly (North up) once it was calculated. 
Suggested fix if you swipe down "Route planning" menu, map should start rotating according to profile settings.

**Comment by dmpr0** [comment]
## How to reproduce
* Start **OsmAnd**
* Tap on **Menu** - **Navigation** – **Set destination**
* Selected any destination
* Wait until route will be calculated
* Don't tap on **Start**, tap on map or swipe down **Navigation** menu
* Long tap on compass button, switch **Map orientation** to **Compass direction**

### Actual result
**Map orientation** doesn't follow compass direction, looks line North is up mode.

### Expected result
Map orientation modes should work as selected.

**Comment by sonora** [comment]
I guess the fact that map rotation by compass is suspended while in route planning mode is on purpose, or else it would be rather confusing, would e.g. be very hard to set a destination via "Select on map".

So probably the glitch is just that the suspension _is not lifted_ as soon as the user swipes down the route config sheet to work with the map plus the calculated route without going into turn-by-turn mode.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14239mqta, Released: 2023-03-15
Done
