### ISSUE TITLE
map roration is not correct in driving direction

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#16366]
### Description
Map rotation is set to follow moving direction, but often there is a difference.
Happens every now and then.

### Your Environment
OsmAnd Version:
Android/iOS version: +4.3.7
Device model: Galaxy S20+

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

![Screenshot_20230201_092115_OsmAnd+](https://user-images.githubusercontent.com/95540936/216041745-4414ce29-32e0-453c-bcd6-954ccfd867b9.jpg)

**Comment by vshcherb** [comment]
it's not a difference bearing is taken from GPS device which should not be aligned what you have on the route we plan to provide an option but this part of code has different issues - https://github.com/osmandapp/OsmAnd/blob/73d92c4b4f4909c7e389c7b15337246a9e430e4d/OsmAnd/src/net/osmand/plus/routing/RoutingHelperUtils.java#L83. 

I think that discussion is tracked somewhere to provide smooth animation during snap of the road or with false bearings of Android Auto
