### ISSUE TITLE
Handling of tile map sources in the UI

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#16361]
We currently seem to have these places where to configure (add) tile maps, but its a little inconsistent:

`Menu > Configure map > Map source...`  offers

- **(1)** an `"Install more..."` option, but that seems restricted to **(a)** _pre-cofigured_ **(b)** _online sources_, neither (a) nor (b) becomes clear in the UI wording,
- **(2)** an`"Add"` option, but that seems **(c)** restricted to _manually specified online sources_ (also not obvious in the UI,wording)
- **(3)** while an option **(d)** to import e.g. _sqlite_ or _.tif_ files which are locally present on the device seems entirely missing?

Using
- **(4)** `Menu > Configure map > Overlay...` or `Underlay...` seems to put you to the same screen as **(1)**, but now without the "Add" option there present as **(2)**.

Side issue:
- **(5)** If you once configured an e.g. locally stored tile map as a map source, and later happened to disable the Online maps plugin, you cannot revert your map source back to "Offline Vector map". Trying to do this will put you on the Plugin overview screen, which is unexpected for most users not knowing what to do there.

**Actionable items:**
- [ ] Create option to "_Install predefined online tile source_"
- [ ] Create option to "_Add manually configured online tile source_"
- [ ] Create option to "_Import locally present tile source from file system_"
- [ ] Offer previous 3 items uniformly regardless if are called via `Map source...`, `Overlay...` or `Underlay...`
- [ ] Allow always being able to reset to Vector map source regardless of plugin state.

**Comment by vshcherb** [comment]
Kind of design though we're very busy with design tasks, I don't think it makes sense to do anything now unless we fully agree with redesign, so for me it's a long future (at least 6 months ahead task)

**Comment by sonora** [comment]
@vshcherb I can suggest 2 immediate fixes:

 - [ ] **(1)** Wording change:
 -- "**_Install more..._**" becomes "**_Activate more..._**", to reflect that this is a mere a selection from a list.
 -- "**_Add_**" becomes "**_Add manually..._**", to reflect that this requires manual configuration of more sources.

 - [ ] **(2)** I guess should produce some sort of toast in this case
https://github.com/osmandapp/OsmAnd/blob/389edeb8a4cfff352644d868abb2c2ad088e1352/OsmAnd/src/net/osmand/plus/configmap/MapLayerMenuListener.java#L96-L98
to not simply produce the Plugins screen, but make the user aware they need to activate the "Online maps" plugin there?

**Comment by vshcherb** [comment]
Sounds ok - (2) could be both redirect + toast

**Comment by sonora** [comment]
I've made a very low-impact change just adding the toast and juggling some strings. Think we can consider this fixed.

Could potentially at some point still think about alphabetically sorting the tile maps in the dialogs.
