### ISSUE TITLE
Directions From location preservation between directions display

### ISSUE THREAD

**Issue by PinkDuck** [osmandapp/Osmand#1637]
Current UI behaviour sequence:

Location services on
Directions from...
Set as destination
End directions
Open directions
Current location used (when location services on) or unset (when location services off)

I would like to see the original Directions from... location preserved instead of defaulting to current location or unset. The destination is preserved fine.

**Comment by vshcherb** [comment]
Here I don't have a strong feeling. The directions is not about showing the route, after you start the navigation it will fall back anyway to your current location and won't use selected from location.

**Comment by vshcherb** [comment]
We even have explicit comment of what we do (reset start point) https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/activities/MapActivityActions.java#L461. It would be good to understand that not resetting won't break any use case

**Comment by PinkDuck** [comment]
The issue is that once a destination is set the option for Directions From... is no longer available in the context menu, so it's just a nuisance to have to go to waypoints, pick favourite for start then search an unordered list to restore what was there previously.

I like the idea that directions mode is active then can be temporarily disabled/hidden then just restored by clicking the directions icon again. Resetting the origin implicitly seems more a nuisance than a help. If I'm looking at routes starting not from here then it's usual because I want to test something. That's often with location services off.

**Comment by vshcherb** [comment]
The context menu is being changed. There is an easy way to cover that request, click on waypoints flag on the route calculation and select the start point as a favourite. It requires an extra click but we will eliminate it. 

Because of major changes in context menu, this request better to put on hold for now.

**Comment by sonora** [comment]
deprecated
