### ISSUE TITLE
The borders of Hebei Province are incorrectly displayed

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16377]
### Description
Borders of Hebei Province are incorrectly displayed
Hebei does not include Beijing and Tianjin. These three places are actually equal relationships in China.

### Steps to reproduce
Select/download Hebei province `38.71558° N, 116.41091° E`

### Actual result
<details><summary>Hebei Province</summary>
<img width="791" alt="photo_2023-02-02 12 23 12" src="https://user-images.githubusercontent.com/104760013/216299256-cb4787e7-1e09-46e3-b8cb-7bd0594bace0.jpeg">
</details>

### Expected result
[OSM](https://www.openstreetmap.org/relation/912998#map=6/39.232/117.861)

<details><summary>Hebei Province</summary>
<img width="627" alt="Screenshot 2023-02-02 at 12 30 05" src="https://user-images.githubusercontent.com/104760013/216300548-53acef0b-05a7-4175-9a3d-f5aa1e6e349b.png">
</details>

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14149mqta, released: 2023-02-02
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by DmitryAlexei** [comment]
Macau and Hong Kong maps also cannot be downloaded _inside_ China map (only as separate states).
With map rendering engine 2 Macau and Hong Kong maps are displayed as downloaded and included in China map (see screenshots) while both maps are missing. 

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/116079541/220294579-bb890e76-a4ac-447a-bc52-d67c76af9996.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/116079541/220294593-2d9c298b-9680-4c29-b0f9-52b76b9ba91b.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/116079541/220296718-7d11ad19-d286-4406-8bde-34924f4b053e.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by xmd5a2** [comment]
> It needs either renamed to Hebei, Beijing, Tianjin or borders should change

No, our poly of Hebei province is ok. This is an UI issue.
![Screenshot_2023-02-28_11-32-54](https://user-images.githubusercontent.com/5829014/221797718-ddebc1ee-c3c8-44ed-be66-bdd63fce926a.png)

**Comment by vshcherb** [comment]
Its a duplicate issue with Tirol not correct boundaries

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14217mqta, released: 2023-03-04
4.4.6.2
Same result
