### ISSUE TITLE
Synchronization with the cloud is interrupted

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16372]
### Description

- [ ] When synchronizing with the cloud, the process is interrupted and the message "Broken pipe" is displayed
- [ ] Also, View conflicts button stops responding

[logcat (51).log](https://github.com/osmandapp/OsmAnd/files/10559427/logcat.51.log)

Perhaps this is due to https://github.com/osmandapp/OsmAnd-iOS/issues/2523

### Steps to reproduce
Menu > Settings > OsmAnd Cloud > Sync now

### Actual result
Synchronization with the cloud is interrupted

https://user-images.githubusercontent.com/104760013/216108940-9424fda0-d120-45d7-8552-15cfbe0bb767.mp4

### Expected result
Data is synchronized, View conflicts button works

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14143mqta, released: 2023-02-01
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by vshcherb** [comment]
Probably server outage

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14189mqta, Released: 2023-02-20
Done
