### ISSUE TITLE
Incorrect, additional, subscription display

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16370]
### Description
An extra, incorrect, subscription is displayed that does not exist
Probably due to verification of subscription through backup https://github.com/osmandapp/Osmand/blob/bf8a52fbfc719617030350d319702f165312f403/OsmAnd/src/net/osmand/plus/settings/purchase/PurchasesFragment.java#L98

[logcat (50).log](https://github.com/osmandapp/OsmAnd/files/10558408/logcat.50.log)

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/216081648-0cb7ab66-af19-4d43-9358-b646c8415cda.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Your Environment
OsmAnd Version: 4.3.7

**Comment by anastasiia936** [comment]
+1

**Comment by nazar-kutz** [comment]
**Pull Request**
* https://github.com/osmandapp/OsmAnd/pull/16514

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14198mqta, Released: 2023-02-24
Looks like done

**Comment by dmpr0** [comment]
# Review
- [ ]  Promo Subscription don't visible on **Purchase** screen with active **OsmAnd Cloud** login. OsmAnd Pro Promo subscription active, expire 2023-07-13 14:29:29.813

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/commit/83d24f6c81e9ad345249bc53316255caa6c039e9

**Comment by Zirochkabila** [comment]
4.4.6.7
Done
