### ISSUE TITLE
"Could not calculate route..." errors

### ISSUE THREAD

**Issue by Busterama452** [osmandapp/OsmAnd#16379]
### Description
Building a route involving multiple points to guide the route to take roads that are unpaved and also some tracks.  As you add routing points, it eventually fails to calculate the entire route.  It will calculate between two of the sequential points next to each other, but not the entire route.  

Checked OSM data, looks good.  

Using the CAR profile and switching various routing options does nothing to resolve this.  It does calculate very quickly using the bicycle profile, but I cannot use bicycle routing.  I've seen this issue before and never reporting a bug.  Using bicycle as a work around doesn't help because I'll be navigating the route using a 4x4 truck and the bicycle routing could put me on highway=path (4x4 motor vehicles are not allowed).

### How to reproduce?
GPX with waypoints included in code at the bottom of this message.

Routing works fine from points 1 to 5.
Routing works fine from points 5 to 7 (which automatically passes point 6).
Routing doesn't work from 5 via 6 to 7 and aborts with "intermediate destination 1 [which is point 6] is too far from the nearest road"
Routing works fine from point 7 to the destination.

So routing basically works between all intermediate points. But it fails if you add them one after the other.

### Your Environment
OsmAnd Version: 4.3.6
Android/iOS version: 13 and 11
Device model: Samsung Galaxy S22+ and Samsung Tab A 8" Tablet

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

`<?xml version="1.0" encoding="utf-8"?>
<gpx version="1.0" creator="QGIS">
<wpt lat="34.003232408087" lon="-112.771733847899">
<name>1 Start</name>
<urlname>Digitized in QGIS</urlname>
<ele>0</ele>
</wpt>
<wpt lat="34.163114240748" lon="-113.007687559553">
<name>2</name>
<urlname>Digitized in QGIS</urlname>
<ele>0</ele>
</wpt>
<wpt lat="34.154161221694" lon="-113.218684919953">
<name>3</name>
<urlname>Digitized in QGIS</urlname>
<ele>0</ele>
</wpt>
<wpt lat="34.243788365407" lon="-113.486248393975">
<name>4</name>
<urlname>Digitized in QGIS</urlname>
<ele>0</ele>
</wpt>
<wpt lat="34.114346797532" lon="-113.546371476926">
<name>5</name>
<urlname>Digitized in QGIS</urlname>
<ele>0</ele>
</wpt>
<wpt lat="34.166604554776" lon="-113.688335152332">
<name>6</name>
<urlname>Digitized in QGIS</urlname>
<ele>0</ele>
</wpt>
<wpt lat="34.219456150170" lon="-113.773605463084">
<name>7</name>
<urlname>Digitized in QGIS</urlname>
<ele>0</ele>
</wpt>
<wpt lat="34.171300723823" lon="-113.834390554381">
<name>Destination</name>
<urlname>Digitized in QGIS</urlname>
<ele>0</ele>
</wpt>
</gpx>
`

**Comment by scaidermern** [comment]
The strange thing is that routing from waypoint 5 to waypoint 7 succeeds:
![photo_2023-02-03_10-22-36](https://user-images.githubusercontent.com/1040784/216561948-5c9ae476-393e-4e5c-9737-79f53cf18362.jpg)

But it fails if you add waypoint 6 as via:
![photo_2023-02-03_10-22-40](https://user-images.githubusercontent.com/1040784/216562030-1fcbb565-c95b-4e64-b3a3-c1dc01701b8c.jpg)

Waypoint 6 is directly located on the road. The same error happens if the via point is somewhere near waypoint 6.

**Comment by vshcherb** [comment]
Intermediate points are not supported in GPX navigation but possibly they're still validated and that causes the issue. So as a workaround you shouldn't use intermediate points.

**Comment by scaidermern** [comment]
In my case while trying to reproduce this issue I didn't use GPX navigation at all, just regular navigation.

Note that the track above only contains GPX waypoints, no GPX track/route.

**Comment by vshcherb** [comment]
That strange there is no road on the map so it is not a problem then, it's just an expected error message.

**Comment by scaidermern** [comment]
No, there is a road. It is just not displayed at this zoom level. After zooming in it becomes visible. Otherwise the route from the first screenshot wouldn't be possible.

**Comment by vshcherb** [comment]
Could you please share the route via osmand web service like https://osmand.net/map?start=34.057211%2C-113.556061&end=34.201865%2C-113.686695&mode=pedestrian#13/34.1174/-113.5798 (it will have coordinates and easy to understand situation usually - the bug could be visible immediately)

**Comment by scaidermern** [comment]
https://osmand.net/map?start=34.114347%2C-113.546371&end=34.219456%2C-113.773605&mode=car#12/34.1134/-113.5593

The web interface doesn't find a route between 34.114346797532,-113.546371476926 (waypoint 5) and 34.219456150170,-113.773605463084 (waypoint 7) in car mode. OsmAnd does. But routing in OsmAnd fails as soon as you add 34.166604554776,-113.688335152332 (waypoint 6) as via point.

**Comment by vshcherb** [comment]
@scaidermern on web interface you can drag any orange point and it will be come intermediate.

**Comment by vshcherb** [comment]
It looks like it works with bicycle ok but with car there are problems probably there are some restrictions?

**Comment by scaidermern** [comment]
> It looks like it works with bicycle ok but with car there are problems probably there are some restrictions?

There aren't any. Again, it works _without_ the via point but fails _with_ the via point. The route is supposed to be the _same_. The via point is _on_ the calculated route. Nevertheless it fails _with_ the via point.

**Comment by Busterama452** [comment]
FYI, I'm also a contributor/editor to openstreetmap  and I was just out there on those roads surveying them and downgraded some of the unclassified roads to track roads.

You should be good using the monthly map build, but live update will show my updates any minute now.

**Comment by scaidermern** [comment]
Maybe this video helps to understand the problem better. 
First, a route is calculated from 5 to 7. Then a via point is added inbetween. 

https://user-images.githubusercontent.com/1040784/217072833-d1717a33-6ec3-43bd-b557-78b36d004522.mp4
