### ISSUE TITLE
Crash in the 4th zoom (OpenGL)

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16376]
### Description
When zoom outing to the 4th level, app crashes
[logcat (52).log](https://github.com/osmandapp/OsmAnd/files/10567349/logcat.52.log)
[exception (27).log](https://github.com/osmandapp/OsmAnd/files/10567350/exception.27.log)

### Steps to reproduce
Set the zoom level to 4 and wait a few seconds

### Actual result
Crash

https://user-images.githubusercontent.com/104760013/216285410-7ea68c13-96ac-4c08-8f01-185f337bbb6b.mp4

### Expected result
V1 rendering

https://user-images.githubusercontent.com/104760013/216285786-5f39b11f-20b0-4071-80c1-7464939e14eb.mp4

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14149mqta, released: 2023-02-02
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by franco999** [comment]
I can confirm this problem. On level 4 it crashes

OsmAnd~ 4.4.0#14154mqta, released: 2023-02-05

**Comment by DmitryAlexei** [comment]
[logcat.log](https://github.com/osmandapp/OsmAnd/files/10709204/logcat.log)
Device : c2s
Brand : samsung
Model : SM-N985F
Product : c2sser
Build : TP1A.220624.014.N985FXXS5GWA7
Version : 13
App Version : OsmAnd~
Apk Version : 4.4.0#14165mqta 4400

Problem persists:
https://user-images.githubusercontent.com/116079541/218138797-122fd6bc-1b1f-4ceb-a11f-89f99c8ca908.mp4

**Comment by DmitryAlexei** [comment]
On my device, the app crashes at any zoom above 4. 
With map rendering Version 1 works fine

**Comment by Zirochkabila** [comment]
The last night's version failed to reproduce the crash.
It seems that it depends on the specific environment - needs to observe and collect additional information

**Comment by franco999** [comment]
Is fixed in OsmAnd~ 4.4.0#14186mqta, Released: 2023-02-17 👍
