### ISSUE TITLE
Share button to openstreetmap.org with marker on map

### ISSUE THREAD

**Issue by thibaultmol** [osmandapp/OsmAnd#16386]
# 🚀 feature request

### Description
Ability to generate an openstreetmap.org link from inside osmand BUT that has the marker enabled on the location you selected

### Describe the solution you'd like
Another button (or an option or something) so that you can share a select coordinate on the map and have a url that has the marker enabled. 

![image](https://user-images.githubusercontent.com/1010226/216665558-497e99be-f1e4-4913-95cf-611225de81d1.png)

example url:
https://www.openstreetmap.org/?mlat=51.0046&mlon=3.3373#map=14/51.0046/3.3373

I use this url often to send to my municipality report the location of a problem. But in osmand I can only get the regular openstreetmap.org url.

**Comment by barka91** [comment]
I will work on this issue

**Comment by vshcherb** [comment]
Thanks for PR we will put it for 4.6 schedule

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#814m, released: 2023-09-28

- added option in map context menu 
- link can be copied by tap and used as a link to that location on OpenStreetMap (when inserted in your browser's address bar)
- tested, shows location with pin (marker) on OpenStreetMap correctly

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/3217a1e8-9da4-4db0-8858-df07e8a76874"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/2e7739aa-26e3-430b-bcdd-c4b3bf6c1748"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
Doc:
- https://osmand.net/docs/user/map/map-context-menu#coordinates

**Comment by dmpr0** [comment]
# Review 

<table style="width:100%">
  <tr>
    <th>Video</th>
    <th>Context menu, zoom level = 17</th>
    <th>Generated link</th>
  </tr>
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/503999cf-d3eb-475d-a060-5adebb5dd546"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/0c4f5893-b962-4c20-9ce8-7464823c1f94"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/182f0a3a-fefb-4c7b-b1ef-4b08f9bb1ed5"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ]  Zoom level is always set to `12`.
`https://www.openstreetmap.org/?mlat=52.37308&mlon=4.89245#map=12/52.37308/4.89245`

**Comment by dmpr0** [comment]
# Review – 2
- [ ]  Tap **Details** lead to changing zoom level to 17, but zoom level in the link stay on previous zoom level.

**Comment by DmitryAlexei** [comment]
Added info to 
https://osmand.net/docs/user/map/map-context-menu#coordinates
and
https://osmand.net/docs/versions/future-android#share-point-coordinates-by-an-osm-link
