### ISSUE TITLE
Some changeset absent in live updates

### ISSUE THREAD

**Issue by letypequividelespoubelles** [osmandapp/OsmAnd#16388]
### Description
[This changeset](https://www.openstreetmap.org/changeset/132009746#map=19/28.52941/77.14909) seems to not be taken in account with live update : I don't see any change in OSMAnd. Some changesets I made after are visible in Osmand. 

### How to reproduce?
Go to this location with february map + live update.

### Your Environment
OsmAnd Version: FDroid 4.3.8 
Android/iOS version: 7.1.2
Device model: Crosscall action X3

**Maps used (online or offline):**   
offline

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14184mqta, Released: 2023-02-17

https://user-images.githubusercontent.com/104760013/219689933-c971fa0f-e24c-4bcb-921d-e24cbec0ce07.mp4

**Comment by letypequividelespoubelles** [comment]
I updated with March map and it appeared (w and wo live update). And it wasn't with February map + live updates, so it's really a live update issue.

**Comment by Dima-1** [comment]
Merging hourly update on the server doesn't equal to merge it locally

**Comment by MichaelHaeckel** [comment]
I observe frequently that modified data is initially correct with the first live update which contains is. However after a day or some days the old version comes back. Then for modified or deleted objects the old version is shown and new objects are shown as well.
It helps to delete all live update data an redownload it. However it appears that this is required daily.

An example is [this changeset](https://www.openstreetmap.org/changeset/136381770).
The deleted road sections are shown together with the new ones.

![Screenshot_20230524_093809_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/13928096/5c6e4207-4611-445b-9045-53b4ef9c786e)
![Screenshot_20230524_093908_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/13928096/a485344b-08db-498c-be5b-b10be398081c)

**Comment by Dima-1** [comment]
Fixed here https://github.com/osmandapp/OsmAnd/commit/5ff92f18ccf40e2062ed40e4d6bcb74854d5be04
