### ISSUE TITLE
natural=dune rendering

### ISSUE THREAD

**Issue by 32Vache** [osmandapp/OsmAnd#16387]
# 🚀 feature request

The tag `natural=dune` is currently not rendered on Osmand, it would be nice if it did.

For example here:
![Screenshot_2023-02-03-21-57-27-032_net.osmand.plus.jpg](https://user-images.githubusercontent.com/42336759/216710101-4577b558-01ac-421f-8c5a-7d51e8b6adac.jpg)
https://www.openstreetmap.org/way/1137653662

Here is the wiki page: https://wiki.openstreetmap.org/wiki/Tag:natural=dune

**Comment by ceever** [comment]
As per wiki: "If the dune occurs in a larger dune field or is surrounded by bare sand areas that are not part of this dune map the whole sand covered area as [natural]=[sand] in addition."

In that sense the area marking is incomplete.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14189mqta, Released: 2023-02-20
Done in a new map
