### ISSUE TITLE
Position on the screen is always late in time

### ISSUE THREAD

**Issue by Stefal** [osmandapp/OsmAnd#16384]
### Description
I noticed since a long time that the position displayed on the Osmand map is always at least one seconde late.
I've already miss a direction because of this.

### How to reproduce?
Enable track record/display. You will see that the recorded position are in front of the symbol position.

![lag_osmand](https://user-images.githubusercontent.com/8255984/216594830-7098e962-5413-4fef-9ec9-e7a859285bf9.png)

### Your Environment
OsmAnd Version: various
Android version: various
Device model: various

**Comment by rouelibre1** [comment]
I have the same issue riding my bicycle. It's a clear painpoint of the app.

**Comment by scaidermern** [comment]
Could this be the same issue as #16081?

Does this problem disappear if you switch to OpenGL? Settings -> OsmAnd Settings -> Map Rendering Engine -> Version 2

Or if you disable Settings -> Profile -> Navigation Settings -> General Settings -> Animate own position?

**Comment by Stefal** [comment]
> Could this be the same issue as #16081?
It's not the same issue 
> Does this problem disappear if you switch to OpenGL? Settings -> OsmAnd Settings -> Map Rendering Engine -> Version 2
No

> Or if you disable Settings -> Profile -> Navigation Settings -> General Settings -> Animate own position?
I will try.

**Comment by vshcherb** [comment]
It's animate own position which causes 1 second delay it's probably written in documentation.

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/personal/profiles#other
https://osmand.net/docs/user/personal/profiles#map-during-navigation

**Comment by vshcherb** [comment]
https://osmand.net/docs/user/navigation/guidance/map-during-navigation#animate-my-location

**Comment by DmitryAlexei** [comment]
Added links and ways, corrected errors
https://osmand.net/docs/user/navigation/guidance/map-during-navigation/#animate-my-location-android-animate-own-position
https://osmand.net/docs/user/personal/profiles/#other
https://osmand.net/docs/user/map/interact-with-map#animate-own-position-ios-animate-own-position
