### ISSUE TITLE
textWrapWidth works differently in map creator and on android (old engine)

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1638]
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshot_2015-08-31-20-24-42.png
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshot_2015-08-31_20-20-05.png
It is default rendering style. Zoom does not matter.
Also note "&quot;". After some screen redraw it disappears and normal quote is displayed (yes, that's strange).

**Comment by vshcherb** [comment]
Please specify if it is reproducible on map creator

**Comment by vshcherb** [comment]
Location is http://www.openstreetmap.org/relation/5259165#map=13/56.1558/40.6910 (Vladimir)

**Comment by vshcherb** [comment]
Nope can't reproduce it in map creator

**Comment by xmd5a2** [comment]
Of course it is reproducible in map creator. Second screen from first post is from it. I mean it looks like map creator uses different textWrapWidth.
![_2015-09-01_10-02-55](https://cloud.githubusercontent.com/assets/5829014/9598094/c9e7032e-5090-11e5-874b-5f62a38a203b.png)

**Comment by vshcherb** [comment]
I see I will test on the phone.

**Comment by vshcherb** [comment]
Fixed
