### ISSUE TITLE
right turn not possible

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#16382]
# 🐞 routing report

This right turn is not possible/allowed and would be pretty dangerous.

### Routing engine

- [ x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

 car 

### Is this a regression?

 No, was already in earlier versions

## 🌍 Your Environment

**OsmAnd Version:  +4.3.7**

<pre><code>

</code></pre>

**Device and Android/iOS version:**
Samsung Galaxy S20+ / A13
**Maps used (online or offline):**
Offline Austria (standard map)

- [x ] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**
![Screenshot_20230202_111334_OsmAnd+](https://user-images.githubusercontent.com/95540936/216536669-2d5bd4b7-60d9-4118-a8fb-3b827cc7426b.jpg)

**Comment by scaidermern** [comment]
The corresponding right turn restriction (https://www.openstreetmap.org/relation/10842160) has to _ways_ as via. I guess OsmAnd can't handle this. These two _ways_ should be removed from the relation and replaced by a single via _node_. This should be enough.

**Comment by Rowin63** [comment]
Ich kann leider nicht beurteilen, ob der Fehler in OpenStreetMap liegt oder in OsmAnd.
Falls das, wie von dir angemerkt, im Basismaterial (OpenStreetMap) liegt (so verstehe ich dich), müsste das jemand beheben, ich kann das nicht. Danke.

**Comment by scaidermern** [comment]
I'll try to fix it. This intersection is rather complex (and maybe mapped too complex in OSM) and I guess someone didn't understood how turn restrictions are supposed to work.

**Comment by scaidermern** [comment]
Should be fixed I hope. Maybe you can check this route again in a few hours (if you have OsmAnd live)?

**Comment by Rowin63** [comment]
I'll check it as soon as possible (today/tomorrow). Thanks a lot!

**Comment by Rowin63** [comment]
Fixed! Thanks, danke 👍

**Comment by Helium314** [comment]
> These two ways should be removed from the relation and replaced by a single via node. This should be enough.

While I actually don't care how the intersection is mapped, I want to state that map data should not be changed just to work around shortcomings in [specific routing engines](https://wiki.openstreetmap.org/wiki/Tagging_for_the_renderer#Generalization).
2 via ways is ok according to https://wiki.openstreetmap.org/w/index.php?title=Relation:restriction#Members and thus should be understood by OsmAnd. Valhalla and OSRM understand this correctly, and so should OsmAnd.

**Comment by scaidermern** [comment]
> > These two ways should be removed from the relation and replaced by a single via node. This should be enough.
> 
> While I actually don't care how the intersection is mapped, I want to state that map data should not be changed just to work around shortcomings in [specific routing engines](https://wiki.openstreetmap.org/wiki/Tagging_for_the_renderer#Generalization). 2 via ways is ok according to https://wiki.openstreetmap.org/w/index.php?title=Relation:restriction#Members and thus should be understood by OsmAnd. Valhalla and OSRM understand this correctly, and so should OsmAnd.

Agreed. It would be nice if OsmAnd could handle this. In this specific case, though, some of the turn restrictions have been mapped overly complicated and could be simplified. In other cases it might be actually necessary to use one or more via ways.

**Comment by vshcherb** [comment]
The cost difference is huge 90 seconds vs 270 seconds (https://osmand.net/map?start=48.249510%2C16.392634&end=48.251589%2C16.390556&mode=car#18/48.25039/16.39309), so it comes back to the point 

With new map it will be fixed but live updates don't handle yet correctly complex restrictions

![Screen Shot 2023-02-06 at 13 54 05](https://user-images.githubusercontent.com/1042025/216976605-52377c77-d98c-4cb9-902a-ccf9a2700fad.png)
