### ISSUE TITLE
Exporting the gpx and adding to Strava does not look successful

### ISSUE THREAD

**Issue by pookdeveloper** [osmandapp/OsmAnd#16389]
### Description
exporting the gpx and adding to Strava does not look successful in garmin shows correctly (in strava add some linear extra points )

### How to reproduce?
Create a route and export Gpx, go to Strava and create a route (import gpx)

### Your Environment
OsmAnd Version:
Android/iOS version: 4.3.8
Device model: One Plus 6
![2023-02-04 10_41_37-Window](https://user-images.githubusercontent.com/3384734/216760396-c960d71a-1457-4b51-8388-d9a9516396cb.png)

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by ceever** [comment]
If it shows correctly in OSMand and in Garmin, then maybe it is related to a problem in Strava 🤷

**Comment by sonora** [comment]
If I interpret the screenshots correctly,  it looks like Strava somehow interconnects the points which do not have a road surface specification. Yes, looks like Strava issue at first sight, I have so far no indication that our gpx files are not in accordance with the gpx specification.

**Comment by vshcherb** [comment]
When saving / exporting GPX you can use "Simplified version" GPX in Plan Route and then it won't have rte points interconnections.

**Comment by pookdeveloper** [comment]
Hi @vshcherb I dont see this option in OsmAnd app (Android) it only have one option to share

**Comment by vshcherb** [comment]
You likely created that track with Plan Route (you can get back to it by click the edit track button) there you have Save As option.

**Comment by pookdeveloper** [comment]
@vshcherb 1it works fine, thanks
