### ISSUE TITLE
Display recorded tracks slows down map, even when not near viewport

### ISSUE THREAD

**Issue by Redsandro** [osmandapp/OsmAnd#16390]
### Description

Displaying recorded tracks slows down moving the map, even when they are located in a different continent.

### How to reproduce?

https://user-images.githubusercontent.com/1702193/216779180-33314922-eb35-47d1-a56d-3a1914bb6b4d.mp4

### Your Environment

**OsmAnd Version:** 4.3.5
**Android version:** LineageOS 19.1 Android 12
**Device model:** Mi 9T Pro
**Maps used (offline):**  A dozen European and American maps downloaded.

As agreed in #11961, this issue is split off from #15269.

**Comment by sonora** [comment]
I guess this duplicates https://github.com/osmandapp/OsmAnd/issues/15968.

**Comment by Redsandro** [comment]
You are correct. In my enthusiasm to split up #15269 related issues, I forgot to search for this one.
