### ISSUE TITLE
Tiles get redrawn all the time, even if they were drawn moments ago.

### ISSUE THREAD

**Issue by Redsandro** [osmandapp/OsmAnd#16391]
### Description

OsmAnd is constantly re-rendering tiles that could or should be cached. This makes OsmAnd feel slow when manually traversing maps.

If this limitation is done with good reason, for example to support extremely low resource hardware, perhaps a performance versus power saving option/toggle can be considered.

### How to reproduce?

Hold a point and repeatedly draw an "O". OsmAnd is constantly re-rendering, or re-queueing tiles to be rendered, causing portions of the map to be repetitively or constantly empty. It feels like OsmAnd is struggling. Do this on any other map app and everything is already rendered and cached. It feels effortless. Here is a comparison between OsmAnd and (open source) [Organic Maps](https://github.com/organicmaps/organicmaps).

Secondly, **sometimes** when your finger is released from the touch screen, OsmAnd triggers a complete redraw of everything that was rendered moments ago, as captured in the below recording.

https://user-images.githubusercontent.com/1702193/216779669-b07b39e3-3e35-4ab6-8a34-a4e8fd87f1d7.mp4

As you can see, OsmAnd seems to be constantly working, while Organic Maps seems like a big pre-rendered image.

### Your Environment

**OsmAnd Version:** 4.3.5
**Android version:** LineageOS 19.1 Android 12
**Device model:** Mi 9T Pro
**Maps used (offline):**  A dozen European and American maps downloaded.

As agreed in #11961, this issue is split off from #15269.

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/16392
