### ISSUE TITLE
Cycling routing with "use elevation data" shouldn't assess penalties elevator ride (high slope)

### ISSUE THREAD

**Issue by lmamane** [osmandapp/OsmAnd#16398]
# 🐞 routing report

### Routing engine

- [X] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Cycling, Riding style balanced

### Start and end points

All in country Luxembourg:

Bereldange (the village, no specific street)
Boulevard Royal (Ville Haute) in city Luxembourg

### Actual and expected routes

When one _disables_ the "Use elevation data" option, the route found is, in broad strokes: staying in the valley along the river, then using the "Lift Pfaffenthal"
https://www.openstreetmap.org/node/4315424505
to climb to city level. It has a very very short localised 8% slope segment, and the second-highest-slope is similarly very very short localised 4% and all the rest is lower slope.

![216845764-b7bd7aec-c705-443b-91a5-a03ebac34d06](https://user-images.githubusercontent.com/7558692/217035880-c24e8c6e-1c0b-4c01-8911-c079e870362f.png)
![216845765-946ac604-24c3-443e-bd10-c49f7317ece9](https://user-images.githubusercontent.com/7558692/217035954-9c64d697-f4fe-4edd-88d4-2807920178bb.png)
![216845766-cb3247ad-a94c-4440-9f75-1034e7883084](https://user-images.githubusercontent.com/7558692/217036022-864a336b-3678-401b-a6b7-a943d4ebae4d.png)

When one _enables_ the "Use elevation data" option, the route found has two long slopes of up to 10% and 8%. That's a significantly worse route when judged on "climb effort", which is what "use elevation data" is supposed to avoid! It has opposite effect that what it should. It is also a worse route in that it uses more busy roads rather than cycle paths and secondary roads.

![216845778-5610eb8a-2a97-438e-85c1-af6a216df3e4](https://user-images.githubusercontent.com/7558692/217036097-bb735f45-2fe5-4172-a1bd-4ce2937de20d.png)
![216845781-67668ad9-945a-4a9c-b7a7-d57e38b34e2d](https://user-images.githubusercontent.com/7558692/217036142-fc3be5cd-c466-43ab-a6e3-312bb357f882.png)

It seems the routing algorithm doesn't understand that using an elevator for an "extremely steep climb" is preferable (let's call it cost zero in terms of climb effort; some cost in time "obviously") to making the same climb through a "steep slope". It seems it sees the elevator as a 67% slope and completely rejects its use on that ground?

### Is this a regression?

Not that I know of.

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>4.3.8</code></pre>

**Device and Android/iOS version:**

OnePlus 9 Pro, LineageOS build lineage_lemonadep-userdebug 13 TQ1A.230105.001.A2 f60dd643e4, version 20-20230124-NIGHTLY-lemonadep, Android version 13.

**Maps used (online or offline):**

- [X] Offline maps offered within the OsmAnd app for download, Luxembourg Standard Map 1 Feb 2023. I also downloaded Contour lines (19 Mar 2021), Hillshades (22 Jul 2021), Slopes (28 Oct 2020) and (but I guess this is not relevant) Wikipedia 18 Jul 2022.
- [ ] Online (tile / raster) maps 

**Anything else relevant?**

Essentially, make using an elevator should be equivalent to a zero-slope step, although the elevation brusquely changes.

**Comment by lmamane** [comment]
Probably for the same reason (but maybe also because the funicular is not marked "bicycle: yes", I'm not sure), the route from Bereldange (same starting point) to "mBox Rout-Bréck - Pafendall"
https://www.openstreetmap.org/node/5276083318
doesn't use the funicular from Pfaffenthal-Kirchberg to Rout Bréck-Pafendall, but makes the same manual climb along the same 8%-10% slope to then use the bridge to arrive, or (use elevation data: off) goes into unpaved / forest paths.

![Screenshot_20230205-211559_OsmAnd~](https://user-images.githubusercontent.com/7558692/216846886-57f28f84-6b33-432a-a455-1eebca3a9bf7.png)
![Screenshot_20230205-211607_OsmAnd~](https://user-images.githubusercontent.com/7558692/216846887-39cce2a8-a53e-4641-896b-8d924cca4160.png)
![Screenshot_20230205-211624_OsmAnd~](https://user-images.githubusercontent.com/7558692/216846888-3c31face-c82c-4d39-a14a-a796d011bd89.png)
![Screenshot_20230205-211628_OsmAnd~](https://user-images.githubusercontent.com/7558692/216846889-3df0269e-c252-4a2b-93c5-fdc70a7c33fe.png)
![Screenshot_20230205-211643_OsmAnd~](https://user-images.githubusercontent.com/7558692/216846890-a6fd1bda-2573-4846-9822-4577122b7d0a.png)


The expected route is to go to https://www.openstreetmap.org/relation/7809498 use the funicular to go to https://www.openstreetmap.org/relation/7752818 which is meters away from the destination. Barely no climb :)

**Comment by xmd5a2** [comment]
@lmamane Please downscale your screenshots. It is very hard to understand issue because of that.

**Comment by lmamane** [comment]
> @lmamane Please downscale your screenshots. It is very hard to understand issue because of that.

OK, I have downscaled them by a linear factor of 4 - area factor 16.

**Comment by Dima-1** [comment]
Now use elevation data switch works as expected.
<details>
    <summary>Screenshots</summary>
<table style="width:100%">
  <tr>
    <th>
      Use elevation data:off
    </th>
    <th>
      Use elevation data:on
    </th>
  </tr>

  <tr>
    <td><img src="https://user-images.githubusercontent.com/31807095/234780972-396e5bd4-ec94-4d1d-8efa-c953ee2b872f.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/31807095/234783047-fd0be369-fd7f-4708-8356-c17cacaebbf8.png"  width="300" height="auto"/> </td>
  </tr>
<tr>
    <td><img src="https://user-images.githubusercontent.com/31807095/234780964-056e6114-4c73-495d-a74d-80de970e158e.png"  width="300" height="auto"/> </td>
<td><img src="https://user-images.githubusercontent.com/31807095/234783043-0bc4eb2b-1883-4aff-a96d-48aa0ec863f8.png"  width="300" height="auto"/> </td>
  </tr>
<tr>
    <td><img src="https://user-images.githubusercontent.com/31807095/234780946-e6d20e56-6b6e-44d6-9aca-2c0dd51f923f.png"  width="300" height="auto"/> </td>
<td><img src="https://user-images.githubusercontent.com/31807095/234783037-369eea11-cb9c-489d-bded-6053fb20329c.png"  width="300" height="auto"/> </td>
  </tr>
</table>   

</details>
