### ISSUE TITLE
Brands – Search results prioritize streets over POI (not sorted by distance overall) - Aldi

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/OsmAnd#16397]
Search results are not properly sorted by distance. If I scroll down the list some near results are displayed below results that are several hundred kilometres away.

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/6921696/216839329-b5661578-4850-429b-8646-18c43ead1e77.png"  width="300" height="auto"/> </td>
  </tr>
</table>

OsmAnd~ 4.3.8

I am not sure if the following report is duplicate:
https://github.com/osmandapp/OsmAnd/issues/8677

**Comment by vshcherb** [comment]
> we need completely restructure the search cause search doesn’t have mechanism to understand what’s the meaning of the words.  So I think you can adjust how you use it and type Supermarket Aldi and save as a filter - so then it’s prioritized
 
You could see that results are sorted 1) Cities / Streets 2) POI - in each group results sorted by distance

**Comment by scaidermern** [comment]
Same issue for me (OsmAnd+ 4.3.7) with similar POIs like Aldi, Netto (supermarkets) and Aral (fuel station):
![foo](https://user-images.githubusercontent.com/1040784/216905389-9832e6a4-c465-4e09-b1f1-dfe224d33c16.jpg)

Looks like it could have something to do with partival vs exact matches?

**Comment by vshcherb** [comment]
Exactly cause it's a deliberate decision to prioritize exact matches over partial matches, unless there is a language or vocubalary understanding behind that issue won't be fixed. 

**Please use**: Supermarket (category) Aldi to achieve necessary result

**Comment by scaidermern** [comment]
> **Please use**: Supermarket (category) Aldi to achieve necessary result

Unfortunately this leads to the exact same behavior or is even worse.

Searching for "Convenience store and supermarket Aldi" (_without_ space at the end) returns exactly the same results.
Searching for "Convenience store and supermarket Aldi " (_with_ space at the end) only returns "ALDI Nord" but not "Aldi".

**Comment by vshcherb** [comment]
Similar issue with Lidl

![telegram-cloud-photo-size-4-5983060546691381751-y](https://user-images.githubusercontent.com/1042025/216977746-e013c266-dec1-4719-a1de-999b0972f1d6.jpg)


If it enables search by category you should see button increase radius 
1. Works correctly
![telegram-cloud-photo-size-4-5983060546691381753-y](https://user-images.githubusercontent.com/1042025/216977466-bf0365ff-4b88-4d9a-bf40-a9cbb9b9f587.jpg)

2.  Searching for "Convenience store and supermarket Aldi " (with space at the end) only returns "ALDI Nord" but not "Aldi".

It's a bug... Need to be fixed

**Comment by vshcherb** [comment]
The underlying reason - https://github.com/osmandapp/OsmAnd/issues/13797  and similar discussion https://github.com/osmandapp/OsmAnd/discussions/16344#discussioncomment-4886324

**Comment by yuriiurshuliak** [comment]
Cafe and restaurant: Humboldt 1a
City: Kassel
![Screenshot_20230402-174554_OsmAnd](https://user-images.githubusercontent.com/127092082/229549808-7fdceb90-5459-4da1-b38a-b5ccf712482d.png)

**Comment by sonora** [comment]
Quite obviously in all related reports there is always the conflict between
-  overall sorting by distance (the output optically appears as one flat list)
- and  structured output where each section is sorted by distance.

I guess the solution could be to output as a  _colapsable list_, like we do when you search for something on  our  MyPlaves>Tracks screen. There it is optically clear that  the search results are from different folders (and from which ones), and we could transfer that scheme to here showing search results headed by the categories like
- Tracks
- Favorites
- Addresses
- POIs

as applicable?

**Comment by mnalis** [comment]
I think it should always be sorted by distance, as that is the only that makes sense (unless OsmAnd happens to guess as first category exactly what you wanted - but that is just pure luck).  

What would be _nice_ is an option to **filter only one category** (e.g. `city/town` name, or `streetname/address`, or `public transport` name, or `amenity/shop/everythingelse` name)

**Comment by sonora** [comment]
@mnalis Essentially, that's the effect of what I suggest above (try it on the Tracks screen): You would get an (initially collapsed) list of all categories which have a fitting search result, and you could then tap on any of these to expand it to see the corresponding results, sorted by distance.

**Comment by Zirochkabila** [comment]
Incorrect order of request display (Android & iOS) https://github.com/osmandapp/OsmAnd/issues/15504#issuecomment-1514372596

**Comment by lcosmin** [comment]
I guess there can't be an "one-size-fits-all" type of solution. 

How about having some controls at the top of the search screen which could be used to decide the sorting order, i.e. to allow sorting by proximity to current location, to prefer exact matches first, etc. ?

**Comment by xmd5a2** [comment]
Brand analysis was done. First I performed an Overpass request like that on Europe/USA:
```
[out:xml][timeout:90][bbox:{{bbox}}];
(
  nwr["name"="Barclays"];
  nwr["brand"="Barclays"];
  nwr["operator"="Barclays"];
);
(._;>;);
out meta;
```
Note that result of these requests contains some data not related to brands (like places with such names) but there is very few of them.
I counted the number of objects with tags like that:
`name="Barclays"`,`brand="Barclays"`,`operator="Barclays"`. 
  | Europe |   |   |   | USA |   |  
-- | -- | -- | -- | -- | -- | -- | --
  | name | brand | operator |   | name | brand | operator
Shop |   |   |   |   |   |   |  
Lidl | 11158 | 10108 | 3991 |   | 130 | 123 | 8
Aldi | 2283 | 1736 | 1264 |   | 364 | 322 | 53
Netto | 1971 | 1662 | 706 |   |   |   |  
Aral | 2286 | 2744 | 1015 |   |   |   |  
Edeka | 1348 | 784 | 694 |   |   |   |  
Penny | 1099 | 859 | 441 |   |   |   |  
Tesco | 3109 | 1665 | 1245 |   |   |   |  
Eurospar | 565 | 442 | 52 |   |   |   |  
Albert Heijn | 1003 | 1042 | 160 |   |   |   |  
7-Eleven | 165 | 226 | 98 |   |   |   |  
Picard | 1011 | 952 | 293 |   |   |   |  
Tesla | 113 | 355 | 394 |   | 139 | 371 | 97
BMW | 1290 | 1175 | 209 |   | 56 | 276 | 16
Audi | 242 | 939 | 161 |   | 52 | 206 | 5
Lego | 124 | 134 | 0 |   |   |   |  
  |   |   |   |   |   |   |  
Food |   |   |   |   |   |   |  
KFC | 2569 | 2568 | 300 |   | 3473 | 3507 | 55
McDonald’s | 7584 | 7955 | 1686 |   | 11 | 15 | 7
Dunkin' | 146 | 150 | 1 |   |   |   |  
Domino's | 2131 | 2144 | 40 |   |   |   |  
Starbucks | 1939 | 1916 | 124 |   | 11167 | 10858 | 153
Subway | 3534 | 3518 | 171 |   | 13406 | 13335 | 146
Burger King | 3431 | 3817 | 558 |   | 6233 | 6221 | 117
  |   |   |   |   |   |   |  
Estate agent |   |   |   |   |   |   |  
Laforêt | 626 | 617 | 10 |   |   |   |  
  |   |   |   |   |   |   |  
Shoes |   |   |   |   |   |   |  
ASICS | 43 | 42 | 0 |   |   |   |  
Adidas | 286 | 272 | 11 |   | 115 | 119 | 1
  |   |   |   |   |   |   |  
Clothes |   |   |   |   |   |   |  
Nike | 252 | 223 | 3 |   | 144 | 146 | 38
Intimissimi | 570 | 519 | 4 |   | 9 | 9 | 0
Chanel | 75 | 50 | 1 |   | 23 | 17 | 0
Gucci | 88 | 70 | 2 |   |   |   |  
Burberry | 70 | 66 | 11 |   |   |   |  
Hugo Boss | 212 | 212 | 1 |   | 71 | 75 | 0
Lacoste | 265 | 264 | 6 |   | 59 | 58 | 0
  |   |   |   |   |   |   |  
Telecommunication |   |   |   |   |   |   |  
Orange | 1948 | 1198 | 34495 |   |   |   |  
Deutsche Telekom | 107 | 2557 | 3233 |   |   |   |  
Vodafone | 3080 | 2642 | 2132 |   |   |   |  
  |   |   |   |   |   |   |  
Cosmetics |   |   |   |   |   |   |  
Yves Rocher | 1041 | 992 | 7 |   |   |   |  
  |   |   |   |   |   |   |  
Computer |   |   |   |   |   |   |  
Apple | 89 | 52 | 39 |   |   |   |  
  |   |   |   |   |   |   |  
Bank |   |   |   |   |   |   |  
Barclays | 923 | 1068 | 393 |   |   |   |  
  |   |   |   |   |   |   |  
Fuel |   |   |   |   |   |   |  
Total | 2689 | 4224 | 2037 |   | 530 | 542 | 29
Shell | 5184 | 6398 | 2560 |   |   |   |  
BP | 3516 | 4800 | 1968 |   | 4152 | 4112 | 375
Esso | 4028 | 5544 | 1439 |   |   |   |  
Circle K | 1525 | 1879 | 747 |   | 4974 | 4723 | 241
  |   |   |   |   |   |   |  
Post |   |   |   |   |   |   |  
Royal Mail | 146 | 19164 | 50755 |   |   |   |  
Deutsche Post | 1432 | 12089 | 50925 |   |   |   |  
La Poste | 2984 | 11751 | 49832 |   |   |   |  
  |   |   |   |   |   |   |

**Comment by vshcherb** [comment]
Brand has : https://taginfo.openstreetmap.org/keys/brand#values 2.5M values and > 2.5K unique
Distribution:

- 350 brands > 1000 places
- 800 brands > 500 places
- 10 000 brands > 10 places
- 13 800 brands > 5 places

**Comment by vshcherb** [comment]
**Technical plan**:
- List of brands could be maintained in OsmAndMapCreator (as top > 100 places)
- OsmAnd search should support dynamic categories (provided from files) - probably it's implemented

**Comment by DmitryAlexei** [comment]
- how many icons (of brands) do we need to show? (100?)

**Comment by vshcherb** [comment]
Icons are secondary part of the task probably - 10-20 or as much as we can reasonably find

**Comment by ivanPyrohivskyi** [comment]
iOS/core drafts:
https://github.com/osmandapp/OsmAnd-iOS/pull/3811
https://github.com/osmandapp/OsmAnd-core/pull/765

**Comment by dmpr0** [comment]
## Review

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/ec9c642a-dddb-42ca-88fb-0498b3269dbe"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [ ] Remove `Top_index_brand` line from POI details, or make it visible if OsmAnd Development plugin is On.

**Comment by vshcherb** [comment]
- [ ] Crash Show on map

**Comment by vshcherb** [comment]
- Fixed Show on map
- Fixed Save Filters
- Fixed duplicates

**Comment by dmpr0** [comment]
# Review



- [ ] Japanese brand doesn't indicate language

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd/pull/20513

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd/pull/20514

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd/pull/20514

**Comment by EugeneZmeuk** [comment]
**Docs**
- [ ] [Searc POI section > Brands](https://osmand.net/docs/user/search/search-poi)
