### ISSUE TITLE
Superposition of monthly updated map and live update

### ISSUE THREAD

**Issue by letypequividelespoubelles** [osmandapp/OsmAnd#16395]
### Description
OSMAnd sometimes renders a superposition of the "core monthly upadte map" with the live update map. As in the screenshot : the building "hall 14" has been slighlty mooved, and you see two buildings in OSMand. It disappeared after few live update. 
I think it's a regression, never seen it in 4.2 version or before.
Maybe related to #16388 
![photo_2023-02-05_05-46-56](https://user-images.githubusercontent.com/54240434/216802255-389cca97-bb2f-4a1c-bc67-f601de322313.jpg)

### Your Environment
OsmAnd Version: Fdroid 4.3.8
Android/iOS version: 7.1.2
Device model: Crosscall action-X3

**Maps used (online or offline):**   
offline

**Comment by scaidermern** [comment]
Duplicate of #14920.

**Comment by letypequividelespoubelles** [comment]
Oh, sorry, did not see it.
