### ISSUE TITLE
The "orientation cone" is too small / difficult to see

### ISSUE THREAD

**Issue by paggps** [osmandapp/Osmand#1639]
The orientation cone, which is based on the compass is extremely useful. Without moving, just by watching at the cone, you know where you have to walk or drive.
However, it is too small, and too "light" in colour, so many times it is very difficult to find it on the screen, or find out where is it pointing.
Please check how the cone looks in OsmAnd, and how looks it in and old software I used to use (Maverick), where the cone is much bigger.
![screenshot_2015-09-01-09-10-11](https://cloud.githubusercontent.com/assets/14073425/9604011/fa9c1ff0-508a-11e5-9e3a-29cd45f0e059.png)
![maverick](https://cloud.githubusercontent.com/assets/14073425/9604051/50cd114a-508b-11e5-8b2d-a107eddc3a80.jpg)

**Comment by Gizmot** [comment]
I agree, especially trying when trying to use outside walking. Impossible to see with the sun shining on the screen

**Comment by sonora** [comment]
Concur. We used to have it larger, and that was more usable.

**Comment by vshcherb** [comment]
I made it 2 times bigger, but still not that big as in different app. To make it that big, it requires some settings which for now we don't want to introduce.

**Comment by paggps** [comment]
Honestly, I think this (closed) issue is still a valid issue.
Many people are asking for it.
The blue orientation cone is SO useful when you are a traveller pedestrian, that it should be improved.
Thanks.
