### ISSUE TITLE
Contour lines item isn't displayed in Configure map

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16409]
The **Contour lines** item isn't displayed in **Configure map**
**Download maps** - displays downloaded maps of Contour lines
In **UI Customization**, the Contour Lines item is also not displayed - although the plugin is enabled

## How to reproduce?
* Open **Menu** – **Configure map**
* **Contour lines** item isn't displayed

### Actual result

<details><summary>OpenGL-arm64-nightly</summary>
<img width="300" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/217193637-9fbe0549-c883-4575-a204-0c2a84e64774.jpeg">
</details>

### Expected result
If **Contour lines** plugin is enabled, **Contour lines** item should be visible in **Configure Map** (if it not hidden in **UI Customization**)
<details><summary>OsmAnd 4.3.10, released: 2023-01-30</summary>
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/217194778-b92c7d61-4b6b-4d02-b839-9da1db27f33b.jpeg">
</details>

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14157mqta, released: 2023-02-07
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/commit/7b12d6dcc94b5264074ad3c018d373331399e66c

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14159mqta, Released: 2023-02-08
Done
