### ISSUE TITLE
Ocean/Land rendering error in v2 OpenGL that is not present in v1

### ISSUE THREAD

**Issue by dangxit** [osmandapp/OsmAnd#16404]
### Description
For some of the costal area the ocean layer is rendered above the land layer of the map, at a certain range of zoom in the V2 OpenGL engine. The zoom range is roughly between 500m:1cm to 50m:1cm. The issue is not present when using the V1 engine.
![Screenshot_2023-02-07-00-21-03-441-edit_net.osmand.plus.jpg](https://user-images.githubusercontent.com/26214417/217026942-518db4c5-6568-46fa-bcad-dfee739bfc06.jpg)
### How to reproduce?
Issues only occur at the specific location of the map when viewing between roughly 500m:1cm and 50m:1cm . The one I found is located in Zhuhai, PRC at 22.28678° N, 113.57270° E the ocean area is rendered above the land area

### Your Environment
OsmAnd Version: OsmAnd+ F-droid 4.3.5
Android/iOS version: Android 12
Device model: Redmi POCO F3 (Redmi K40)

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
Offline Map: China, Guangdong Province 2023/FEB/1

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.4.0#14173mqta, released: 2023-02-13
China, Guangdong Province 2023/FEB/1 map
Not reproduced

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/116079541/218670883-ebbb96a1-5420-4c0a-ad18-bc4eb39c1075.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
@DmitryAlexei please check different zooms probably this is not relevant any more cause maps are updated.

**Comment by DmitryAlexei** [comment]
I checked this place with different zoom levels and with old and new rendering engines. I cannot observe it there.
But near that place can be found other related to rendering (or map source) issues:
1. 21.99641° N, 113.27231° E

https://user-images.githubusercontent.com/116079541/218960426-5f26d3df-c50b-472d-932c-c04ad38f01f0.mp4


https://user-images.githubusercontent.com/116079541/218960474-c04ee1d5-f528-4570-b78c-cd4a1e2ef064.mp4

2. Huge massive of ponds isn't displayed on high zoom levels. 22.08128° N, 112.78424° E


https://user-images.githubusercontent.com/116079541/218962707-711a2a73-2673-46ea-b80f-624d59e7ffa5.mp4



https://user-images.githubusercontent.com/116079541/218962754-dd7b18c9-cd55-46d4-ade7-85a28367603d.mp4

3. Hong-Kong and Macao maps displayed as downloaded (in green color) while they are not. With rendering version 1 works fine. See difference in old (left) and new rendering:

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/116079541/218964500-980d881f-2ba2-46fb-82f8-490f4a8a44c0.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/116079541/218964518-af700f9e-431e-4b36-983a-3752ea970407.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
Also see ponds near ocean at 22.06164° N, 113.01018° E :

https://user-images.githubusercontent.com/116079541/218997828-b81f646c-ae65-4b9a-b15a-9047e1663efe.mp4

This behavior also persists with the old rendering

<details><summary>Video from OSM</summary>
<video src="https://user-images.githubusercontent.com/116079541/218997845-317b70fd-d3d8-4abb-8c70-bd6a10d0ad0a.mp4"></video>
</details>

**Comment by jsoriano** [comment]
@vshcherb has this issue been fixed? I am seeing similar issues with OpenGL rendering that I cannot reproduce with V1 rendering.

I am using 4.3.12 on a Fairphone 3.

Some screenshots:
![Screenshot_20230304-224914](https://user-images.githubusercontent.com/15763/222930398-2bf1965a-2520-43d5-af37-1d498b06426e.png)
![Screenshot_20230304-224729](https://user-images.githubusercontent.com/15763/222930415-8a910142-c8ab-4eda-a10e-3c6b67f2040e.png)
![Screenshot_20230304-225000](https://user-images.githubusercontent.com/15763/222930469-966a3d5f-a98e-4bc3-b641-62276dd2bf36.png)

**Comment by Zirochkabila** [comment]
@jsoriano Please create a new issue with all the data described in your comment
