### ISSUE TITLE
Implement a "Find in Settings" function to easily retrieve the menu options

### ISSUE THREAD

**Issue by Max1234-Ita** [osmandapp/OsmAnd#16408]
We all know that OsmAnd is a complex app, due to the enormous number of functions it has inside.
As a consequence, the menu tree has so many branches that even the most experienced users sometimes struggle to find the option they're looking for.

So i was wondering if it would be possible, in the future, to have a Search function not for addresses or POIs but for... the menu items themselves, like it happens, for instance, with modern web browsers (i.e. Firefox or Chrome) or the Settings menu of some operating system (i.e. Android).

Example: I'm looking for the option that allows me to show the road quality on the map.
I need to remember it's in menu /// -> Configure map -> Details -> Show road quality.

But if I could just type "Road quality" in a "Search in settings" Textbox, pick the option from the matching results and directly jump to the right menu, I would set that option very easily without having to remember where that option exactly is.

I understand the work to implement such a feature would be huge, but in my opinion it would greatly improve the usability  of OsmAnd.

Thanks for you attention!

**Comment by scaidermern** [comment]
@vshcherb You added the "next-android" milestone to this ticket but not to ##13973. Now that this ticket here is closed I think the same milestone should be set for #13973? In my opinion this would be a really helpful feature.

**Comment by vshcherb** [comment]
Yes same milestone and yes next-android indicates roadmap this year but next-android is definitely much bigger than just 1 release which is planned every 1-2 month
