### ISSUE TITLE
The track continues to be visible on the map when exiting the filtering screen

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#16407]
### Description
When you exit the filtering screen by the back buttons, the track continues to be displayed on the screen, but stops responding to pressing and disappears from the list of visible ones.

### How to reproduce?
1. go to my places and select a track.
2. press options and select gps filter.
3. press the back button in the upper left corner several times until this button disappears.

After that, the track is displayed on the map, but does not respond to clicks and is not in the list of visible ones.

See video in telegram:
https://t.me/ruosmand/116608

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14154mqta, Дата выпуска: 2023-02-05
Android version: 12
Device model: poco f3

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14189mqta, Released: 2023-02-20
Done
