### ISSUE TITLE
Public transport directions: "no route suitable"

### ISSUE THREAD

**Issue by cat3na** [osmandapp/OsmAnd#16410]
#### Brief:

When pulling up navigation in the "Public transport" profile, route calculation is not even attempted by the app. Loading walking directions solves this temporarily, and route calculation proceeds normally from there, but changing the map region or closing the app brings the issue back.

#### Full:

As of sometime in the past week (after updating to 4.3.5), I stopped being able to calculate any public transport directions at all. Regardless of the location or simplicity of the route, even in completely different map regions, I was getting this message:

> Unfortunately, OsmAnd could not find a route suitable for your settings.
>
> Try changing the settings.

After testing further, this issue seemed to spontaneously resolve after switching to the "Walking" profile and letting those directions load. When I switched back to "Public transport", the directions loaded as usual, and I was able to enter different routes in the same city with no problems. 

However, when I moved to my testing region to get some screenshots, I ran into the same problem again. This was again fixable by briefly loading the "Walking" profile and switching back.

Switching to the Walking profile does continue to work as a temporary fix, but it seems to break again every time the map changes or the app exits.

#### Other notes

Driving and walking directions seem unaffected. Using "My position" or a static address does not change the result.

Another odd note is that when this issue is occurring, changing to the "Driving" profile and back to "Public transport" retains the overlay of the driving route on the map. This does not happen when the transport directions load properly.

### How to reproduce

Navigation > Public transport profile > enter any route

If public transport directions *do* load, switch to another region's map and try to load directions there. Alternatively, close the app, re-open it, and attempt again.

To clear the problem temporarily, switch to the Walking directions profile (Driving does not appear to do anything) briefly, then switch back to Public Transport. The walking route does not need to finish calculating.

### Expected result

Previously, I was able to access public transport directions without doing anything special, though they did take a while to load (~1-3 min).

### Your Environment
OsmAnd Version: 4.3.5 (F-Droid)
Android/iOS version: Android 12
Device model: Samsung Galaxy A53 (OneUI 4.1)

Navigation settings >
* Type: Public transport
* Route parameters >
    * Avoid transport types: (none selected)
    * Number of changes: 3
    * Consider temporary limitations: On
    * Minimal distance to recalculate route: 394 ft
    * In case of reverse direction: Enabled
* Screen alerts: On
* Voice prompts: Off

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14187mqta, Released: 2023-02-18
[logcat (67).log](https://github.com/osmandapp/OsmAnd/files/10774342/logcat.67.log)


https://user-images.githubusercontent.com/104760013/219868381-aad61ac7-664f-4891-b16a-4711a64ba914.mp4

**Comment by fr33zing** [comment]
I've got the same issue on GrapheneOS, though it did work a few weeks ago. Only difference is that I can't resolve it by switching profiles. Public transit navigation is totally unavailable to me via Osmand. I fully reset the app (wiped my settings and all data) but the issue remains.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14222mqta, Released: 2023-03-07
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/223450232-c7f725ef-8bfc-4b2b-846f-cc03db843da5.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
@Zirochkabila screenshot doesn't explain anything, please follow the pattern: steps, expected, actual. On your screenshot it looks like there is a data missing in OSM ?

**Comment by Zirochkabila** [comment]
This only happens with routes that are marked accordingly in OSM [175э](https://www.openstreetmap.org/relation/8904872), for example [3c](https://www.openstreetmap.org/relation/8954733#map=13/53.8642/27.5894 ) is displayed as expected

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/224490675-c8aff19e-9b68-4f80-a818-51e1525b8fbc.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/224490677-f8b55dfa-ca02-4f4c-851c-fec02f049670.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by nakic** [comment]
I don't get it. How has been closed? Offline public transportation routing has been completely unavailable for me in New York during a recent trip.

**Comment by yuriiurshuliak** [comment]
Please try to increase the number of changes, navigate through the menu as follows: Menu → Navigation → Settings → Navigation settings → Route parameters → Number of changes. Additionally, ensure that you are not utilizing online maps. 
Furthermore, please furnish the coordinates where public transport routing is not functioning correctly for you.
