### ISSUE TITLE
Zooming after I select something from search

### ISSUE THREAD

**Issue by theNizo** [osmandapp/OsmAnd#16414]
**Behavior**

1. I search for something, then select the result.
1. The map shows up, with a predefined zoom, it seems.
1. I zoom in, because it's pretty much always too far out.
1. AFTER I did that, the map then zooms out to that default value again.

This happens to me pretty much everytime.

A workaround by the user would be to wait 3 seconds, which I honestly don't want to do (as weird as it sounds).

**Expected behavior:** Cut the 4th step. It's annoying and repeats something that's already done.

**Comment by sonora** [comment]
Weird, I cannot reproduce that. How do you zoom, using the +/- buttons, double-tapping, tap-swiping, or by pinch-zooming?

Also, maybe as a workaround: Are you aware that a single-tap on the content menu title triggers a close-in zoom?

**Comment by theNizo** [comment]
> Are you aware that a single-tap on the content menu title triggers a close-in zoom?

The closest thing I could find that fits this description is the button labelled "Details" that's on the bottom left of the screen if something on the map is selected. But no I didn't, thanks for that.

> How do you zoom

Pinch, and I haven't thought about other methods yet. With the + button, it works as expected, every other method triggers the 4th step. This would be a suitable workaround for _me_, so I'll leave it up to you if you want to look into it.

---

I should have specified, I select an - object? (eg. anything you can find under search -> categories) - not an address. From what I've found, the app pans to the place with a predefined zoom. In the description of the place it says "looking up address". As soon as it shows the address, it pans and zooms again. This behavior can especially be noticed when holding the phone in landscape, where it pans a bit different the second time.

It seems to have to do something with the address lookup. It pans and zooms as soon as that's finised. If you search for an address, instead of an object, the second pan and zoom doesn't happen and the adress shows up in the description immediately.

The address lookup takes longer in a city, so that might make it easier to reproduce.

**Comment by theNizo** [comment]
And sorry, I somehow got past the issue type selection

### Your Environment
OsmAnd Version: v4.3.5
Android/iOS version: Android 12 (crDroid)
Device model: Oneplus 5

**Comment by vshcherb** [comment]
Screenshots or video is welcome

**Comment by Zirochkabila** [comment]
OsmAnd 4.3.11, Released: 2023-02-05

https://user-images.githubusercontent.com/104760013/219708109-3766ba31-820f-49e1-b4b9-7eee2aa6de6e.mp4

**Comment by vshcherb** [comment]
We have different default zoom based on search object city / street / building - poi. It's configurable but we don't see much issue with current default behavior.

**Comment by theNizo** [comment]
Sorry, I was to slow with answering.

I don't even know what the other person tried to show, or how it was related, but my issue is not the default zoom, it's the second pan and zoom that happens:


https://user-images.githubusercontent.com/38207294/220061567-0f42b5d2-da86-4c5f-99f3-392259765284.mp4

(I zoom in, it then zooms out. Second pan and zoom happens at the same time as it shows me the address.)

This can also be seen in landscape, where there's not even further input needed to see that it does that the second time:


https://user-images.githubusercontent.com/38207294/220061846-480aadc7-de2e-453b-ae98-75de345e7745.mp4

I select something from search that's not an address. The app pans and zooms. I adjust something. The app displays address and pans and zooms again. I don't see the necessity for the second one. Second pan and zoom only doesn't happen if I use the +/- buttons. Double-tap, tap-swing and pinch is all affected.

**Comment by vshcherb** [comment]
Issue at laest: Landscape doesn't have pin in center of right side

**Comment by theNizo** [comment]
So we're just gonna ignore the fact that it zooms twice? (I never zoomed _out_ in these videos, that was the app itself)

**Comment by sonora** [comment]
I finally understand what you mean, it's this:
- Tsp on a POI search result.
- Map centers to the POI in default zoom.
- Quckly pan the map a  bit **while the POI's context menu still indicates it is searching for the POI's address** (this is key here!)
- After the POI address is found, the context menu is updated, **and we center (and default-zoom) the map again**

Quite possibly  this second center+zoom operation is expendable.

**Comment by vshcherb** [comment]
1st video is not clear cause it has some weird interactions and it's not clear whether they were manual or by program but I certainly didn't reproduce it yet

**Comment by sonora** [comment]
@vshcherb Yes, I had the same problems to reproduce. I'd say forget the videos and try my 4 bullet points above. You need to do this with POIs where it takes a few secs to find the address. So the faster your device is, the harder it will be to reproduce.

If we wanted to fix this it's probably quite simple: I currently see no need to re-center/re-zoom a second time after the reverse geo-lookup finishes, so chances are we just need to comment out a single line of code.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14204mqta, Released: 2023-02-26

<details><summary>V1 and V2 too</summary>
<video src="https://user-images.githubusercontent.com/104760013/221421069-74f06cea-cbe2-4ff6-991f-6f29ad9ec8c4.mp4"></video>
</details>

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14239mqta, Released: 2023-03-15
Map is shifted when switching to landscape mode.
Both on V2 and V1 - more noticeable on V1
[logcat (76).log](https://github.com/osmandapp/OsmAnd/files/10978649/logcat.76.log)



<table style="width:100%">
  <tr>
    <th>V1</th>
    <th>V2</th>
  </tr>
  <tr>
    <td><video source src="https://user-images.githubusercontent.com/104760013/225282866-4ed990f0-d06c-4cc3-ae65-0cc506de0802.mp4"  width="300" height="auto"/></td>
    <td><video source src="https://user-images.githubusercontent.com/104760013/225282893-c90b5330-d3a0-4834-b3ae-1b3068f3112d.mp4"  width="300" height="auto"/> </td>
  </tr>
</table>
