### ISSUE TITLE
Do not render text without icon if the icon is to be rendered (old engine)

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1641]
![screenshot_2015-09-01-22-46-13](https://cloud.githubusercontent.com/assets/5829014/9627108/aabbace0-516a-11e5-902e-426e174d221f.png)
http://www.openstreetmap.org/#map=19/56.128586/40.40255

**Comment by vshcherb** [comment]
Fix https://github.com/osmandapp/OsmAnd-core/commit/804de22a3f100fad8a86b0a1ea9072e48176aae5

Fix #1641. Requires a little bit testing, but fixed. Please check potential memory leak or native crash

**Comment by vshcherb** [comment]
@xmd5a2  please check

**Comment by xmd5a2** [comment]
Checked. No noticeable memory leak or crash.
