### ISSUE TITLE
Different categories of POIs in the Kyiv travel guide file are displayed in one color 

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#16418]
### How to reproduce?
1. Open Travel guides
2. Download the Europe file
3. Select Kyiv
4. Display points on the map
5. You will see that all POI categories are displayed in one color
![image](https://user-images.githubusercontent.com/80623554/217488135-af00bdba-ac41-43e0-90f3-8a0c53dece51.png)
[Kyiv.gpx.zip](https://github.com/osmandapp/OsmAnd/files/10683882/Kyiv.gpx.zip)

### Expected result
All categories are displayed in a different colors. For example, cafes are orange,  Shopping centers are purple, etc

https://github.com/osmandapp/OsmAnd-tools/blob/master/java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/travel/WikivoyageLangPreparation.java#L548

### Your Environment

OsmAnd Version: 4.3.7
Android/iOS version: Android 9
Device model: Sony Experience XZ1

**Maps used (online or offline):**   offline
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by ivanPyrohivskyi** [comment]
Need to check on Legacy and OpenGL

**Comment by vshcherb** [comment]
Data obf / osm could be checked itself

**Comment by xmd5a2** [comment]
Wikivoyage Obf data correctly contains different categories of POI
```
routes: route_article_point Vyshhorod Lat 50.583054 Lon 30.486717 osmid=-44285  category_see='see' lang_yes:en='yes' route_name='Kyiv' directions='21km N' gpx_icon='special_photo_camera' route_id='Q1899' description='A summer winter resort. For more see Central Ukraine#Kievska|Central Ukraine
outes: route_article_point Cosa Nostra Lat 50.5831 Lon 30.48662 osmid=-509302  category_eat='eat' lang_yes:ru='yes' route_name='Вышгород' address='просп. Шевченко, 1A' gpx_icon='restaurants' route_id='Q1004257' phone='+ 38 (063) 651 97 97' description='Phone: + 38 (063) 651 97 97'
```

**Comment by vshcherb** [comment]
@xmd5a2 doesn't have color so it's an issue with data however it's generated.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-tools/blob/master/java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/travel/WikivoyageGenOSM.java#L387 - gpx_icon is present but color is not.

**Comment by xmd5a2** [comment]
Issue is in fact that wikivoyage generator use `color` tag but poi_types.xml contains `colour` tag
https://github.com/osmandapp/OsmAnd-resources/blob/master/poi/poi_types.xml#L27
OSM uses `colour` tag. We need to solve this somehow.

**Comment by ivanPyrohivskyi** [comment]
- [ ] color -> colour

**Comment by ivanPyrohivskyi** [comment]
if (color != 0) {
    gpxTrackTags.put("color",
      MapRenderingTypesEncoder.formatColorToPalette(Algorithms.colorToString(color), false));
    gpxTrackTags.put("color_int", Algorithms.colorToString(color));
   }

OsmAnd-tools/OsmGpxWriteContext.java at master · osmandapp/OsmAnd-tools
OsmAnd tools to generate new maps & to test OsmAnd files on PC - OsmAnd-tools/OsmGpxWriteContext.java at master · osmandapp/OsmAnd-tools

https://github.com/osmandapp/OsmAnd-tools/blob/master/java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/OsmGpxWriteContext.java#L240

OsmAnd/Amenity.java at master · osmandapp/OsmAnd
OsmAnd. Contribute to osmandapp/OsmAnd development by creating an account on GitHub.

https://github.com/osmandapp/OsmAnd-tools/blob/master/java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/OsmGpxWriteContext.java#L329

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14201mqta, Released: 2023-02-25
Done



<details><summary>Perhaps it is worthwhile to display the POI in such a way that when you select a certain category (Buy, Do, Eat...), the map displays POIs only of the color of the category selected, and not all of them together.</summary>
<video src="https://user-images.githubusercontent.com/104760013/221365883-73ee7a29-c30e-42e6-a6d4-3785dea068bd.mp4"></video>
</details>
