### ISSUE TITLE
Wrong voice prompts when navigating through the created GPX

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16422]
### Description
When navigating through GPX (created in OsmAnd), errors occur during voice navigation. 
Errors are caused by the number of turns in the track details
After joining the road, the errors in the voice guidance disappear, as well as the incorrect turns in the track details.
It seems that an error occurred while recording track - **4.3.8 OsmAnd version**

[Test voice prompts.gpx.zip](https://github.com/osmandapp/OsmAnd/files/10686997/Test.voice.prompts.gpx.zip)
[logcat (54).log](https://github.com/osmandapp/OsmAnd/files/10687014/logcat.54.log)
From `51.218879896333405, 18.57551594450522` to`51.17547866247871, 18.554243344808793`

### Steps to reproduce
Navigation > Select gpx > Set start point > Start

### Actual result
Wrong voice prompts and turns

https://user-images.githubusercontent.com/104760013/217571893-b35aab35-55ab-4730-a71c-cd3c08bf48eb.mp4

### Expected result
Voice prompts and turn arrows are the same as on the unattached track

https://user-images.githubusercontent.com/104760013/217573586-7cbfccec-fb8e-4b10-b084-d23a191c8635.mp4

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14159mqta, Released: 2023-02-08
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by vshcherb** [comment]
Needs to be tested on the clean track, reattached and generated in a new program [ Probably track is wrong ]

**Comment by Zirochkabila** [comment]
The track is incorrect - the track itself contains incorrect turns
But, the track was created in OsmAnd - for some reason, the application created a broken track - need to understand why and fix it

**Comment by DmitryAlexei** [comment]
1. Each point of _Test voice prompts.gpx_ has tag _<osmand:speed>_. Tracks made using OsmAnd~ 4.4.0 _Plan a route_ tool does't have this tag. 
2. Also _Test voice prompts.gpx_ doesn't have information about used profile.
3. _Test voice prompts.gpx_ has 130 points.

So, highly likely, _Test voice prompts.gpx_ was created using another GPX file in old version of the OsmAnd app in _Browse map_ profile.
P.s. isn't it strange to manually create a short (less than 6 km) track using 130 points? 

<details><summary>Test voice prompts.gpx</summary>
<img width="300" alt="Screenshot_5" src="https://user-images.githubusercontent.com/116079541/220955381-7ed5cd94-c1d5-4240-be80-37efe2f02923.png">
</details>

<details><summary>GPX created by Plan a route for comparison (bicycle profile)</summary>
<img width="300" alt="Screenshot_6" src="https://user-images.githubusercontent.com/116079541/220957195-5f8d4486-5861-4340-aef4-c9e78cf46b94.png">
</details>

Voice prompts, recorded in _Test voice prompts.gpx_ file and the user's speed of movement (13.9, 8.7, 3.4, 5.5 etc) refer to bicycle profile. 
When you try to use a _bicycle_ track in _driving_ profile, OsmAnd shows voice prompts for bike and then (after starting a route) - for a car.
