### ISSUE TITLE
The export file is displayed empty

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16421]
### Description
The export file does not display data on Android but displays data on iOS
[Export_03-02-23 (1).osf.zip](https://github.com/osmandapp/OsmAnd/files/10686392/Export_03-02-23.1.osf.zip)
[logcat (53).log](https://github.com/osmandapp/OsmAnd/files/10686482/logcat.53.log)

### Steps to reproduce
Open osf file on Android devices

### Actual result
File is displayed as empty

https://user-images.githubusercontent.com/104760013/217555624-4dd90812-6ed5-4291-b390-22413a03f559.mp4

### Expected result
File displays data
4.4.5.3

https://user-images.githubusercontent.com/104760013/217556715-e6437bf0-ef93-4b32-b922-40a53d8ee937.mp4

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14159mqta, Released: 2023-02-08
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by Corwin-Kh** [comment]
Not reproduced

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14236mqta, Released: 2023-03-14
Done
