### ISSUE TITLE
UI freezes

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16423]
### Description
UI freezes
[logcat (55).log](https://github.com/osmandapp/OsmAnd/files/10687367/logcat.55.log)
Possibly related to https://github.com/osmandapp/OsmAnd/issues/16360

### Your Environment
OsmAnd Version: 4.3.8 4308
Android/iOS version: Android 10
Device model: POCOPHONE F1

**Comment by vshcherb** [comment]
Merged to #16360
