### ISSUE TITLE
Enhancement POI: Add own POI templates to the "create poi" feature

### ISSUE THREAD

**Issue by pos-ei-don** [osmandapp/Osmand#1642]
Enhancement: Add own POI templates to the "create poi" feature.
It would be nice to see own templates sorted before the build-in templates.

**Comment by vshcherb** [comment]
We plan to do it but in a different screen (same dialog), so called Quick Templates for POI creation

**Comment by pos-ei-don** [comment]
great to hear! Thanx!

**Comment by matthijskooijman** [comment]
This seems to be related to #4689, which talks about adding additional tags to "create POI" quick actions.
