### ISSUE TITLE
Unpair ANT+ device

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#16428]
User case from the support request:

Once a sensor of a type (in my case the HR) is linked with the app its identity stays in the app and the Plugin NEVER again looks for a sensor of that type.

I would urge to check the function the plugin out by using one HR sensor and then attempting to use a different HR sensor - it is not possible to swap sensor.

**Comment by dmpr0** [comment]
Duplicate https://github.com/osmandapp/OsmAnd/issues/15459

**Comment by vshcherb** [comment]
Now it's not possible to unpair ANT+ device cause settings are hidden in ANT+ application, that's why we are moving towards to https://github.com/osmandapp/OsmAnd/issues/15459
