### ISSUE TITLE
Part of the map isn't displayed

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16426]
### Description
Part of the map isn't displayed V1 and V2

### Steps to reproduce
Follow to `33.73436° N, 116.74477° W` > Zoom in

### Actual result

https://user-images.githubusercontent.com/104760013/217635185-d460b393-31ea-442c-97f3-a39052b52c53.mp4

### Expected result
Map is displayed in green

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14159mqta, Released: 2023-02-08
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by hakuchi** [comment]
looks like a error in the OSM map not an OsmAnd issue

check mapped scool in this area: https://www.openstreetmap.org/way/686046391

**Comment by vshcherb** [comment]
Conflicting objects:

https://www.openstreetmap.org/relation/11337437
https://www.openstreetmap.org/way/686046391

School area < Wood area so it's drawn over Wood area.
