### ISSUE TITLE
Fuel-efficient routing tries too hard to avoid gravel/unpaved roads

### ISSUE THREAD

**Issue by bhankerson** [osmandapp/OsmAnd#16433]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Car, Truck

### Start and end points

This is a general report that applies to all gravel roads (`highway=residential` and higher)

### Actual and expected routes

None toggled in "Avoid roads..."
None toggled in "Prefer..."
Fuel-efficient way ON
I don't want to prefer gravel roads, or avoid motorways, but I've noticed in too many cases that OsmAnd tries too hard to avoid unpaved roads, enough so that the route calculated is not nearly the most fuel-efficient way. I suspect this is because the parameters for driving conditions on unpaved roads are too harsh.
I propose a few possible avenues to a solution:
1. Increase the expected speed for gravel roads and similar "unpaved" tags (i.e. separate gravel roads from dirt roads)
2. Add a "Shortest way" option that would only avoid very small or poor-quality roads (below `highway=residential` or whenever `surface=dirt` and similar)
3. Give users the ability to enter their own expected speeds on gravel roads (or unpaved in general)

I have played with the "Default speed" settings, and I can almost make routing do what I want by making the minimum speed at least 60 mph (seems minimum to 50-60 mph is that range where gravel roads start being selected, depending on the length of the gravel section). But even at a minimum speed of 55 mph (the local speed limit), routing chooses 2 miles of asphalt + 1 mile of unknown (3 miles) instead of 1 mile of gravel. A longer route at minimum 55 mph preferred 1.35 miles of gravel + 4 miles of paved (5.35 miles) instead of 2.9 miles of gravel. I had to increase minimum speed to 65 mph(!) before it chose gravel.
Ideally, I would like to utilize gravel roads on short routes (i.e. to almost always take the shortest route), while generally avoiding gravel roads on long routes (unless of course a gravel road can significantly reduce route length). I understand this is a tough ask (what's the cutoff point for short vs. long routes... how much shorter must the gravel route be... not all gravel roads are created equal... how to account for unknown road surfaces...), but that is my wish :) Another thought I just had, possibly adding a "Percent of route allowed to be gravel"? But that wouldn't work on short gravel-only routes... maybe "total miles/km allowed to be gravel"?
Thank you for your time!

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
I don't know

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

4.3.8

</code></pre>

**Device and Android/iOS version:**

Moto G7 Power
Android 10

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps

**Comment by DmitryAlexei** [comment]
Fuel-efficient routing with default speed parameters in some cases calculates more than 2 times more long route, than with customized (increased) minimal and average speeds. With higher default speeds, gravel roads are more likely to be chosen. 

From 54.05916° N, 27.64085° E to 54.09265° N, 27.64924° E
None toggled in "Avoid roads..."
None toggled in "Prefer..."
Fuel-efficient way **ON**

<details><summary>Basic route calculation 10.6 km</summary>
<img width="300" alt="fuel-efficient routing" src="https://user-images.githubusercontent.com/116079541/229705537-8c890c83-cadb-4ec4-9ca7-235d9e2bf49e.jpg">
</details>

<details><summary>Customized road speeds 4.82 km</summary>
<table style="width:100%">
  <tr>
    <th>Default speeds</th>
    <th>Route calculation</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/116079541/229704489-5f73ec8b-f23e-4676-a7cc-5cfa1a4e8bbd.jpg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/116079541/229707950-cb6f0b30-da19-4008-96e1-19d4076a8107.jpg"  width="300" height="auto"/> </td>
  </tr>
</table>
</details>

<details><summary>Prefer unpaved roads 5.94 km</summary>
<img width="300" alt="unpaved roads" src="https://user-images.githubusercontent.com/116079541/229709215-c4e87943-768f-4414-a18b-3e259c9e1635.jpg">
</details>

So in this case the maximum effective factor is given by `maxDefaultSpeed/speed`. See explanation in [routing.xml file](https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#:~:text=The%20maximum%20effective,for%20this%20case).

**Comment by vshcherb** [comment]
Fuel efficient routing works is intended  it doesn't support to use gravel/unpaved roads. Fuel efficient still deprioritize gravel unpaved roads but it limits the maximum vehicle speed to 90 kmh. 
So as stated by @DmitryAlexei these are optimal settings to prefer or use gravel roads more aggressively

**Comment by bhankerson** [comment]
@vshcherb What is the expected speed on a gravel residential road? Is it 45 kmph * 0.2 = 9 kmph (L379 & L974)?
Is "Fuel-efficient way" called `parameter id="short_way"` (L396)?
And when I have "Fuel-efficient way" toggled on, residential roads are given a priority multiplier of 25 (L789)?
This results in a priority of 0.2 * 25 = 5, and a speed of minimum(5 * 45, maxDefaultSpeed) = maxDefaultSpeed?
Can this be changed by setting a speed limit on the gravel residential roads (in OSM)?
Thanks

**Comment by vshcherb** [comment]
Yes we think now actively how to provide more transparency and yes we think to introduce individual speed limits to each road which would solve the situation and let full control without creating own routing profile... we're not sure though how many road types should be present then..
