### ISSUE TITLE
Publicize F-Droid Releases

### ISSUE THREAD

**Issue by qkqsb** [osmandapp/OsmAnd#16439]
# 🚀 feature request

For some reason the fact that the app is released on F-Droid is not made clear by this repository's readme.md, or by the website. Why is it that the homepage of the website greets you with all of the places to obtain the app, and yet F-Droid is excluded? For those who are interested in this app, it is highly likely that they will want to use F-Droid, so why make it confusing? Looking forward to the discussion of this.

**Comment by ferromint** [comment]
- the version on F-Droid is not the free version, but the [paid pro version](https://osmand.net/docs/user/purchases/android/#prices)
- I guess that it is not the OsmAnd developers who maintain the F-Droid build but [someone not part of the OsmAnd team](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/net.osmand.plus.yml).

- take a look at the [OsmAnd versions](https://osmand.net/docs/user/purchases/android/#prices) mentioned above
- think about how promoting this would defeat the idea of offering a more feature-rich pro version (additionally to the free version)
- how it would negatively impact the development of also/mainly the free version via a pro version for the heavy users
- imagine that having less resources means being able to invest less effort into this technologically complex project (working hours, infrastructure, etc.)
- and put one and one together

Please correct me if I'm wrong.

**Comment by vshcherb** [comment]
There is no need to publicize or depublicize, we support open-source and fine that pro-like version is published on F-Droid. So far the main financial support comes from GPlay / Amazon / iOS version, so marketing team makes public what brings more financial support and makes project viable
