### ISSUE TITLE
Sync App Theme and Map Mode

### ISSUE THREAD

**Issue by MarioSwitch** [osmandapp/OsmAnd#16435]
# 🚀 feature request

### Description

Now, there are 2 "Light/Dark" modes: The "App Theme", which change menus and "Map Mode" which change map. It would be great if we can synchronize these 2 options as if you want to have a dark map, you don't want to be surprised because menus are still in light mode.

### Describe the solution you'd like

Add an option "Sync with Map Mode" in the "App Theme".
If the map is in night mode (either if you've set "Night", "Sunrise/sunset" and it is night, or "Light sensor" and the environment is dark), menus are in dark mode.
If the map is in day mode (either if you've set "Day", "Sunrise/sunset" and it is day, or "Light sensor" and the environment is bright), menus are in light mode.
Using this setting, all Day/Night settings are synced and if the map changes from day to night mode, menus changes too.

### Describe alternatives you've considered

Now, we can change these 2 settings independently but it is less convenient and, moreover, there aren't "Sunrise/sunset" nor "Light sensor" options in "App Theme".

**Comment by vshcherb** [comment]
duplicate https://github.com/osmandapp/OsmAnd/issues/3384
