### ISSUE TITLE
Highway shield steals numbers from the route/ref/name

### ISSUE THREAD

**Issue by bhankerson** [osmandapp/OsmAnd#16434]
### Description
Display widget of current street or next turn shows a blue pentagon shield with the CR number. Roads that have multiple ref numbers that share the same digit lose that digit in the widget display. Even the digit from `name` is stolen.

### How to reproduce?
Route from https://www.openstreetmap.org/way/1109712542 to https://www.openstreetmap.org/way/763479015. 

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/33230497/217914850-74272a4f-ec5d-4ec2-aa88-5610dd3a59fe.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

Turning onto CR 3/MN 30

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/33230497/217914879-3a6f3593-1a75-4e83-ad1d-4ec0c1d35ae9.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

Turning onto CR 3/MN 83

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/33230497/217914914-fa39a1ed-6773-42ee-887d-f779dc3919c3.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

Driving on CR 3/State Highway 83

### Your Environment
OsmAnd Version: 4.3.8
Android/iOS version: Android 10
Device model: Moto G7 Power

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14187mqta, Released: 2023-02-18
Simulate navigation from`43.79011, -93.72892` to `43.93331, -93.69738`

[logcat (68).log](https://github.com/osmandapp/OsmAnd/files/10774431/logcat.68.log)

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/219870000-7b366f91-438b-4088-8472-41ec488be3a6.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/219870003-adf54028-504d-45fb-b555-8ab0550ff55f.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by sonora** [comment]
Issue is caused here:

https://github.com/osmandapp/OsmAnd/blob/b2e633f8e65e9d0fa82045669099a05d2666c107/OsmAnd/src/net/osmand/plus/views/mapwidgets/widgets/StreetNameWidget.java#L145-L147

I am not yet sure what the intent of that code snippet is.

**Comment by vshcherb** [comment]
https://www.openstreetmap.org/way/1109742849#map=16/43.8914/-93.7126 - "MN 30;CR 3" -> "MN 0;CR " - only iOS BUG

**Comment by sonora** [comment]
Very likely, the original intent of the code snippet and the corresponding commit https://github.com/osmandapp/OsmAnd/commit/71d6c09de2a6245597cf1a49e3476db89534b46e was just to avoid repeating the road shield text also in the street name field. But it's of course a naive approach... I suggest to just revert the commit?

**Comment by vshcherb** [comment]
@sonora the problem that it replace means replaceAll which is incorrect and replaceFirst or something smarter should be used.

**Comment by vshcherb** [comment]
This fix will be a hotfix but we need more systematic approach how to display refs and replace, I suggest to keep it open cause this example is very good to display 2 shields and cut when shield name is different than ref.
Original issue: https://github.com/osmandapp/OsmAnd/issues/14863

**Comment by Dima-1** [comment]
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/31807095/56346e8e-6fd4-40f4-8a71-15b7074641c2"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/31807095/f98b6bba-8e94-4600-855a-239a5f1152ed"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by yuriiurshuliak** [comment]
Currently, the bug has been fixed. The widget functions properly on both Android and iOS, accurately showcasing turns and numbers.  However, it's worth mentioning that there's a discrepancy in the widget's appearance—iOS displays only one shield while Android shows two.

OsmAnd~ 4.6.0#1163m, released: 2023-12-06
OsmAnd 4.6.2.2

<table style="width:100%">
  </tr>
  <tr>
    <th>Android</th>
    <th>Android</th>
    <th>iOS</th>
    <th>iOS</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/e89a43e2-b0e3-408f-942e-5675d11e2d98"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/e6b5d1d1-93f3-4b7f-b650-95cc0173263d"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/25a43aa2-3f42-40b0-b991-ebfc462215df"  width="300" height="auto"/> </th>
  <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/f70ff882-a7c3-45b9-9a79-30baba14ddd8"  width="300" height="auto"/> </th>
  </tr>
</table>
