### ISSUE TITLE
Japanese kana displayed as boxes when label starts with a kanji

### ISSUE THREAD

**Issue by nicolas-raoul** [osmandapp/Osmand#1644]
Context: Most POI names in Japan are a mix of kanji and kana (2 different alphabets). A single Japanese word often uses the two alphabets, for instance 通り (meaning "road") is a kanji plus a kana.

Whenever the first character is a kanji (and that's very often), then all following kana characters are displayed as boxes.

As a result, ~50% of the POI names in Japan are corrupt:

![screen](https://cloud.githubusercontent.com/assets/99590/9631331/1ad5a9b8-51bb-11e5-9032-57086256ce7d.png)

Examples showing how the bug works:

```
漢字ひらがな　→　漢字□□□□
漢字カタカナ　→　漢字□□□□
ひらがなだけ　→　(same)
カタカナダケ　→　(same)
漢字丈　→　(same)
漢字ひらがな漢字　→　漢字□□□□漢字
漢字カタカナ漢字　→　漢字□□□□漢字
通り　→　通□
```

I suspect OsmAnd uses a Chinese font without kana whenever the first character is a kanji. A first workaround would be to use a font that has kana. Another workaround would be to differentiate Japan/China using [this easy formula](http://gis.stackexchange.com/a/80408/1013):

```
106.38 + longitude - 0.666*latitude = ?  Japanese if positive, Chinese if negative
```

[OsmAnd-nightly-2.3.apk 02-Sep-2015 09:43 41M](http://download.osmand.net/latest-night-build/), Android 5.1.1 on Nexus 5.
Keywords: hiragana, katakana, missing glyphs, replacement glyph, mojibake.

**Comment by vshcherb** [comment]
Related https://github.com/osmandapp/Osmand/issues/1161

**Comment by vshcherb** [comment]
We have issue of rendering one label with 2 fonts

**Comment by kebinchien** [comment]
I have met with the same problem as well and have not figure out a way to correct it.
We got to thank the team for delivering free (trial) software for all to use, but I hope they can do User Acceptance Testing before delivery. 
Not displaying locations correctly for a map App, is a rudimentary bug akin to a car that does not move, or a toaster that does not heat up.

**Comment by kebinchien** [comment]
by the way, this problem did not pop up until an update recently, either to the app itself, or to the Android operating system.

**Comment by nicolas-raoul** [comment]
Duplicate of #1161 please discuss the issue there, thanks!
