### ISSUE TITLE
POI with tags tourism = attraction & historic = spacecraft not showing on map

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#16441]
### Description
The Vostok launch vehicle is not displayed on the map, possibly due to the tag historic=spasecraft.
https://www.openstreetmap.org/way/45757945#map=19/55.83431/37.62310

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14165mqta, Дата выпуска: 2023-02-10
Android version: 12
Device model: poco f3

**Comment by michalgwo** [comment]
This tag is not documented on OSM Wiki, I would start here: https://wiki.openstreetmap.org/wiki/Any_tags_you_like

**Comment by Nine-Tailed** [comment]
> This tag is not documented on OSM Wiki, I would start here: https://wiki.openstreetmap.org/wiki/Any_tags_you_like

but the tourism = attraction tag is documented there, but it is not displayed on the map in any way

**Comment by vshcherb** [comment]
Yes tourism attraction is a star with name should be rendered.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14188mqta, Released: 2023-02-19
`55.8343, 37.62302`

Since the **historical=spacecraft** tag is not present in OSM Wiki, a conflict occurs.
For example, you can download a [map](https://drive.google.com/file/d/1cMLCEdS3obI5MKz7qshwj3xPdj-JjLl-/view?usp=sharing) that will display the POI

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/219941183-4e1e0046-9872-4805-b2c5-f0010fcdd2bd.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by ceever** [comment]
Please, also remember this bug #16096, which would also solve this issue, if we would just introduce a proper tourism=attraction POI circle. 👍

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/16096

**Comment by xmd5a2** [comment]
Will be fixed in upcoming maps
![Screenshot_2023-02-26_13-46-55](https://user-images.githubusercontent.com/5829014/221405822-63f6e966-a5d7-4199-b7b5-89deb7d0aab3.png)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14217mqta, released: 2023-03-04
4.4.6.2
POI icon added to the map
But it is not displayed in search results

<details><summary>Sightseeing Category</summary>
<table style="width:100%">
  <tr>
    <th>Android</th>
    <th>iOS</th>
  </tr>
  <tr>
    <td><video source src="https://user-images.githubusercontent.com/104760013/222952748-2a508963-7f31-404d-a13a-a7107c7d6b3b.mp4"  width="300" height="auto"/></td>
    <td><video source src="https://user-images.githubusercontent.com/104760013/222952758-a5c84b1f-dd9f-457f-9491-74295581b574.mp4"  width="300" height="auto"/> </td>
  </tr>
</table> 
</details>
