### ISSUE TITLE
The radius gauge is broken

### ISSUE THREAD

**Issue by snooppr** [osmandapp/OsmAnd#16440]
![Screen](https://user-images.githubusercontent.com/61022210/218168412-5b513198-faee-455d-aab4-5890ba5bafc2.png)

The focus shifts down either at startup or when determining the location.  Bug in versions 4.3.5 and 4.3.8. OS Android.

**Comment by mikehgentry** [comment]
If you have Configure profile -> General settings -> Display position

set to Bottom, it'll centre there, rather than at the midpoint of the screen. If that's not what you mean, could you elaborate?

**Comment by snooppr** [comment]
I needed to return to the center.

Thanks, that fixed the problem, but it seems I didn't touch these options, they came with the update.  And it is strange that the position at the start of the application was either in the center or at the bottom (although in theory, the position should always be at the bottom with the "position at the bottom" settings).

https://github.com/osmandapp/OsmAnd/issues/16112

**Comment by snooppr** [comment]
https://user-images.githubusercontent.com/61022210/218241046-c45a9cdf-a4ae-4340-96c4-3f05b042dc44.mp4

The radius of the ruler is shifted to the top. 

Steps to reproduce the problem: create any track, options->pitch correction->back key.  

The compass went up randomly.  Application restart required.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14164mqta, Released: 2023-02-09
[logcat (57).log](https://github.com/osmandapp/OsmAnd/files/10714708/logcat.57.log)

Center of the map shifts upwards
Restart helps

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14226mqta, Released: 2023-03-09
Done
