### ISSUE TITLE
Map source has no status display

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#16445]
On most menu items of screen `Menu > Configure map` we show the currently selected value as a subtitle, e.g. for 'Overlay map 'and 'Underlay map', but we fail to do this under point 'Map source'. This has confused some users thinking they have forgotten to configure something there.

**Comment by dmpr0** [comment]
## ToDo
- [ ]  **Map source**, show second line if **Offline vector maps** option is selected.

**Comment by sonora** [comment]
@dmpr0  Dmytro, I guess it should be exactly like we already have in the neighboring `Overlay..`. and in `Underlay...` menu items, right? There we show the selected value (not just limited to "Offline vector maps").

**Comment by dmpr0** [comment]
@sonora Yes of course. Map source is show selected value, it omits it for Offline vector maps only.

**Comment by sonora** [comment]
Ah, yes, you're right! I had overlooked this. That's easy then, this should fix it https://github.com/osmandapp/OsmAnd/pull/16564.

Still have to check if the menu display needs an explicit refresh after the value of "Map source" was changed by the user.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14214mqta, Released: 2023-03-03
Done
