### ISSUE TITLE
Moped profile: icons / translations / routing profile 

### ISSUE THREAD

**Issue by JeroenVanOort** [osmandapp/OsmAnd#16446]
# 🚀 feature request

### Description

I'm working on a new profile for mopeds. Please refer to https://github.com/osmandapp/OsmAnd-resources/pull/935 for details. I would like to have some help adding icons and translations for this new profile.

Could anyone please help me with this? I can do the work, but I just need someone to point me to where things should be added.

**Comment by Chumva** [comment]
We need to create a new ApplicationMode "moped", which will use a "moped" routing profile, have a bicycle as a parent, and be disabled by default.

**Comment by dmpr0** [comment]
## Review
- [ ]  Change **Navigation type** name **moped** to **Moped**
- [ ] Change **Navigation type** icon to `ic_action_motor_scooter`
