### ISSUE TITLE
poi antenna not in the database

### ISSUE THREAD

**Issue by snooppr** [osmandapp/OsmAnd#16442]
I noticed that on the OSM map sometimes communication towers (tower tag) are changed to [antenna](https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dantenna)  tag.  Osmand does not display as poi data tags: antenna.  Reproducing the problem: show all poi on the map, poi data (3 communication towers in one place are not displayed).
* https://www.openstreetmap.org/node/1259407828#map=19/55.67181/38.24458
* https://www.openstreetmap.org/node/1349485332
* https://www.openstreetmap.org/node/3581338107

![antenna](https://user-images.githubusercontent.com/61022210/218242630-14b0b5dd-2d71-4f12-9926-63a3b702f0db.jpg)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14188mqta, Released: 2023-02-19
[Map](https://drive.google.com/file/d/1cTmDlw8EK-v-NePLyB9zcpo94wZrcama/view?usp=sharing)
[Taginfo](https://taginfo.openstreetmap.org/search?q=man_made%3Dantenna) 


https://user-images.githubusercontent.com/104760013/219937443-5f211b7f-5c3c-42e4-ab8f-d8744295fed3.mp4

**Comment by vshcherb** [comment]
Correct tagging - https://taginfo.openstreetmap.org/tags/tower%3Atype=communication looks like - which has 350K usage vs 30K. Probably we could convert to each other to have same POI - https://wiki.openstreetmap.org/wiki/Tag%3Aman_made%3Dantenna

**Comment by xmd5a2** [comment]
POI antenna added. It is not correct to convert `man_made=antenna` to `man_made=tower + tower:type=communication` because they have different meaning in OSM.

**Comment by snooppr** [comment]
I also agree that these are different but adjacent antennas.  The example above in the screenshot with towers/antennas only showed that the mappers themselves get confused and put different tags on the map for the same emitters.  Thanks for the added new category.

**Comment by dmpr0** [comment]
Re-check with march map updates.
