### ISSUE TITLE
contourlines.addon.render.xml causes persistent crash

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#16443]
Some commit on Feb 10 causes OsmAnd to crash persistently upon app start, even after downgrading again to a previous build. 

Turns out the crash is caused by this file [contourlines.addon.render_broken.xml.txt](https://github.com/osmandapp/OsmAnd/files/10712711/contourlines.addon.render_broken.xml.txt) now present in your rendering subfolder, which has persistently replaced this previous version [contourlines.addon.render_good.xml.txt](https://github.com/osmandapp/OsmAnd/files/10712712/contourlines.addon.render_good.xml.txt).

Here is the log  [exception.log.txt](https://github.com/osmandapp/OsmAnd/files/10712722/exception.log.txt), I think the primary issue is about `contourLineDepthColor100m` (there could be more issues present, not sure yet.) Version 4.3.11.5009 of late Feb 10 caused the issue after upgrade, .5008 is of Feb 9 and runs stable before the upgrade, or if downgraded to it again, but then only after manually deleting the problematic render.xml file.

**Comment by franco999** [comment]
I have the same problem since OsmAnd~ 4.4.0#14168mqta 10.02.2023

**Comment by Zirochkabila** [comment]
11.02.23 nightly arm64 OpenGL - version
https://download.osmand.net/latest-night-build/OsmAnd-opengl-arm64-nightly.apk
[OpenCrash from AS.zip](https://github.com/osmandapp/OsmAnd/files/10713113/OpenCrash.from.AS.zip)

https://user-images.githubusercontent.com/104760013/218252142-8cc64117-750a-4af0-9e91-5afe7c56deb6.mp4

**Comment by franco999** [comment]
> I have the same problem since OsmAnd~ 4.4.0#14168mqta 10.02.2023

After downloading a previous version ( https://download.osmand.net/night-builds/OsmAnd-master-gnb-2023-02-08.apk ) and deleting the render file that gives problems, it works fine.

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-resources/commit/279bf28edd4459f68f89f9291eeafb996099e7e8

**Comment by sonora** [comment]
Yes, thanks fir fixing! Good that we caught and fixed this one so swiftly.
