### ISSUE TITLE
Cannot compile project 

### ISSUE THREAD

**Issue by chathura1** [osmandapp/Osmand#1645]
I am trying to compile the project via this instructions for Mac OSX 10.10:
https://code.google.com/p/osmand/wiki/GradleCommandLineBuildEnvironment

With
../gradlew --refesh-dependencies clean assembleFullLegacyFatDebug

I am getting following error message:

FAILURE: build failed with an exception.
*What went wrong:
A problem occurred configuring project ':OsmAnd'.
Could not resolve all dependencies for configuration ':OsmAnd:_freqQtcoredebugArmv7DebugCompile'.
   Count not find net.osmand:OsmAndCore_androidNativeDebug:0.1-SNAPSHOT.
       Searching in the following locations:
       https://repo1.maven.org/maven2/net/osmand/OsmAndCore_androidNativeDebug/0.1-SNAPSHOT/maven-metadata.xml
       https://repo1.maven.org/maven2/net/osmand/OsmAndCore_androidNativeDebug/0.1-SNAPSHOT/OsmAndCore_androidNativeDebug-0.1-SNAPSHOT.pom
      https://repo1.maven.org/maven2/net/osmand/OsmAndCore_androidNativeDebug/0.1-SNAPSHOT/OsmAndCore_androidNativeDebug-0.1-SNAPSHOT.aar

**Comment by vshcherb** [comment]
qtcore is not compiled remotely, please use old legacy
