### ISSUE TITLE
OsmAnd Cloud freezes when uploading hillshades or slopes

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd#16457]
### Description
OsmAnd Cloud freezes when you try to upload hillshades or slopes map to the Cloud

### How to reproduce?

1. Make a Cloud backup
2. Download hillshades or slopes (or both) map (s) in your device memory
3. Try to synchronize with OsmAnd Cloud
4. Receive strange error message

If you try to resolve conflicts manually, e.g. to upload your local hillshades or slopes map to the Cloud, uploading also stops at about 10-25%, you receive error message.

After deleting slopes and hillshades, synchronization goes in a normal way.

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/116079541/218668028-bfefde4b-8b7d-482a-bf0f-7da100c715bf.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/116079541/218667441-d3d6bbf5-d20c-49a7-9ca1-1f30c1764c76.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/116079541/218667443-208e394e-8b1e-4241-9665-dce641f5e043.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14173mqta, released: 2023-02-13
Android/iOS version: 13 
Device model: 

**Maps used (online or offline):**   Reproduced with Andorra and Belgium hillshades and slopes map.
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by Chumva** [comment]
https://github.com/osmandapp/OsmAnd-tools/commit/1c4b28b23ff47cd2d3ab5b2ce8790e57a54bdbea

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14194mqta, Released: 2023-02-22
Done
