### ISSUE TITLE
Stop button doesnʼt work

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16453]
### Description
Stop button does not work when trying to stop synchronization
[logcat (60).log](https://github.com/osmandapp/OsmAnd/files/10723194/logcat.60.log)

### Steps to reproduce
Menu > Settings > OsmAnd Cloud > Sync now > Stop

### Actual result
Stop button doesnʼt work

https://user-images.githubusercontent.com/104760013/218486141-d81331f5-3e7b-4203-8206-1643957670d4.mp4

### Expected result
After clicking the Stop button, the synchronization stops

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14173mqta, Released: 2023-02-13
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14230mqta, Released: 2023-03-11
Still present

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14254mqta, Released: 2023-03-20
Done

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/pull/16521
