### ISSUE TITLE
Android Auto split-screen issues, location don't moves to visible map area

### ISSUE THREAD

**Issue by juanantoniomosquera** [osmandapp/OsmAnd#16456]
### Description
Hello, with the new version of Android Auto, if the screen is split and you are navigating, the image is not centered on the current position, only the left part of the map is visible (the route cannot be followed).

### How to reproduce?
Install new Android Auto version, start navegation and select double screen.

### Your Environment
OsmAnd Version: 4.3.7
Android/iOS version: 9
Device model: Xiaomi Mi6

**Comment by dmpr0** [comment]
<table style="width:100%">
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/218756423-e3f4729e-c11a-4ae4-95f5-f66ff53d8aaf.png"  width="800" height="auto"/> </td>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/218756435-2df03889-eb94-4785-ad46-85c5ff9ec36f.png"  width="800" height="auto"/> </td>
  </tr>
</table>

**Comment by wolfsolver** [comment]
Just update to 4.4.1 seems that still not working.

As workaround, with new AA 9.1.130944-daily is possible to invert split screen area 
![IMG_20230309_081105847_HDR.jpg](https://user-images.githubusercontent.com/3205448/223947340-9898fd25-3125-49e6-9dda-9625ca6cc238.jpg)

**Comment by wolfsolver** [comment]
Hi all, I see that this is already closed, but I'd like to share an important info (and different behaviour from OsmAnd and OsmAnd+)

* OsmAnd v 4.3.12
  - navigation work fine also with app in background using Android API as sourcengps. "OsmAnd android auto is running"  notification is present
  - navigation with Google play service does not work

* OsmAnd+ v 4.4.1
  - navigation in background does not work (both with Google service or Android API)
  - no notification that app running.
  - as soon app goes in background, all thead are stopped

**Comment by dmpr0** [comment]
## Driving mode
![Screenshot 2023-03-14 at 12 21 12](https://user-images.githubusercontent.com/9365308/224970576-17e623b9-bf70-45d5-84ee-b20acc82c22b.png)

## Navigation mode
![Screenshot 2023-03-14 at 12 22 10](https://user-images.githubusercontent.com/9365308/224970858-6276928e-12bb-40f4-b93c-bd2367706a3d.png)

**Comment by wolfsolver** [comment]
Good news on new OSMAnd+ beta

OSMAnd+ 4.4.3, AA 9.1.631024-release

Split screen working, position recentered, route is followed, both on left or right layout!

![IMG_20230316_071449184.jpg](https://user-images.githubusercontent.com/3205448/225531096-37329258-dbfc-4ae3-9c71-7e010d968427.jpg)

![IMG_20230316_071506629.jpg](https://user-images.githubusercontent.com/3205448/225531097-3ec6a529-a132-4ff9-af14-bb9d3194aa0e.jpg)

**Comment by juanantoniomosquera** [comment]
Yes, that problem is solved but the GPS location does not work if the application is not open on the mobile device, if the application is in the background, the GPS location is lost.

**Comment by wolfsolver** [comment]
right @juanantoniomosquera, but for this there is a different discussion #16607 for gps in background.
keep care that in my last image the icon is cutted by ETA. I think is better to move a little bit on top, if screen orientation is follow driving direction.

**Comment by Chumva** [comment]
It should work fine now - 
![image](https://user-images.githubusercontent.com/19220417/227148730-b2c52432-0264-4510-82bf-6e12cfb931f5.png)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#14270mqta, Released: 2023-03-25
Done

**Comment by dmpr0** [comment]
<img src="https://user-images.githubusercontent.com/9365308/227976657-b1395c31-ab3e-4355-9b68-b2e145894ba4.png"  width="300" height="auto"/>
