### ISSUE TITLE
Improve OsmAnd Cloud interaction

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#16462]
When I log in to the OsmAnd application offers me to select **Sync now** and **Choose what to sync**. When I click **Choose what to sync** it redirects to the Settings Menu and it is not clear where to go to select data for backup. 
Will be helpful if when I click Choose what to sync and it opens the Backup data menu (Storage taken) to choose info for backup. 

https://user-images.githubusercontent.com/80623554/218778855-4a6fc65d-8105-4207-ad64-a41dfc190bea.mp4

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/16461
