### ISSUE TITLE
Map download "all submaps" of a country/county/higher folder

### ISSUE THREAD

**Issue by MikeTango** [osmandapp/OsmAnd#16466]
Hi,

i would love to be able to click on "yes entire country please" to just download all the things. At the moment i have to click every subfolder to then download each village submap by hand. It's tedious and unnecessary.
<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/3368005/219004789-b524ba98-6650-4b18-921b-3a4873a95c02.jpeg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/3368005/219004815-bfde06b1-9df3-498c-a9a9-57b4f9c55e75.jpeg"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by scaidermern** [comment]
If you download "Standardkarte" then you already have all data for this country. You don't need to (and should not!) download all regional / city maps additionally to that.

**Comment by MikeTango** [comment]
I noticed that on some countries it does check subfolders by default. So the main map for in this case belgium will also give me all others? Does it work the same for elevation/wiki data?

**Comment by scaidermern** [comment]
> So the main map for in this case belgium will also give me all others? Does it work the same for elevation/wiki data?

Yes. If you download the country-wide map then you don't need the individual region maps. They can even cause problems if installed additionally (#15039).

**Comment by MikeTango** [comment]
ok, i deleted france's departement ones...and when i clicked on France as a whole it just gave me those again as a pre-checked list. This could need some consistency across all country maps. Also, are the elevation etc maps affected by that or do i have to pull each of them seperately?

**Comment by scaidermern** [comment]
> ok, i deleted france's departement ones...and when i clicked on France as a whole it just gave me those again as a pre-checked list.

Some countries are so large / have so much data that there is no single country map available for them (France, Germany, Spain, ...). You can identify them on the download icon on the right. If it is only a single arrow pointing down then it is a single download.  If there are two arrows pointing down then this download consists of multiple smaller ones.

> Also, are the elevation etc maps affected by that or do i have to pull each of them seperately?
Not sure if I understand your question correctly. If there is a single elevation map available for the whole country then you don't need the individual smaller ones.

**Comment by MikeTango** [comment]
Thanks for the prompt reply, so all we need is a line that seperates the main map and the submaps saying

 "If you have these ^^ you don't need those vv"

**Comment by vshcherb** [comment]
Related (duplicate) -> https://github.com/osmandapp/OsmAnd/issues/15039
