### ISSUE TITLE
combine App and map color scheme

### ISSUE THREAD

**Issue by firefoxlover** [osmandapp/OsmAnd#16469]
# 🚀 feature request

### Description
The map has to be set to light/darkmode in a completely different menu, which is unintuitive. There also is no popup "apply the color for all profiles" for map colors 

### Describe the solution you'd like
- Map colors should adapt to OSMAnd interface color.
- There should be a popup allowing to at least apply the map color to all profiles
- map colors should be in the same menu as osmand colors (something like "colors" in general)

### Describe alternatives you've considered

Setting colors manually for each profile. Not user friendly.

**Comment by vshcherb** [comment]
Related https://github.com/osmandapp/OsmAnd/issues/14550 https://github.com/osmandapp/OsmAnd/issues/15902 https://github.com/osmandapp/OsmAnd/issues/16435

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/3384
