### ISSUE TITLE
live updates doesn't include housenumbers for searching

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/Osmand#1646]
i like the live updates.
but i can't search for housenumbers although they are displayed correct in map.
for example, i tagged this area four days ago: https://www.openstreetmap.org/way/234215785#map=19/48.53241/8.72697&layers=D
but i don't find a housenumber in the searching dialog.
maps updated today 2.2.0#12778M
greeting simon.

**Comment by stephan75** [comment]
just my 2cent:
Be careful when using live updates, because some types of turn-restrictions are without effect then!!

See ticket #1601

**Comment by jf-simon** [comment]
Thanks i have seen it

**Comment by vshcherb** [comment]
Yes, we know there are some issues with live updates. I will create a list which *will not be supported* in first version and address search is one of them (!). It requires much more than server side generation, it also requires format change. So first version won't support it, but we are heading to fix all bugs with live updates.

**Comment by jf-simon** [comment]
Ok, Thanks for all

**Comment by jf-simon** [comment]
Where will i find this list?

**Comment by vshcherb** [comment]
Known issues page, which is not created yet.
