### ISSUE TITLE
Incorrect screens in OsmAnd Cloud

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#16461]
# 2 Issues below

### How to reproduce?
1. Log in to OsmAnd Cloud 
2. Click settings->Log out
3. Opens OsmAnd Cloud menu when you see Error message: "Failed to fetch the file list from the server".

https://user-images.githubusercontent.com/80623554/218777131-72543687-ece9-4dce-9a82-2e141eabb751.mp4

### Your Environment
OsmAnd Version: OsmAnd+ 4.3.7
Android/iOS version: Android 9
Device model: Sony Experience XZ 1
[logcat (33).log.zip](https://github.com/osmandapp/OsmAnd/files/10733744/logcat.33.log.zip)

-------------------
When I log in to the OsmAnd application offers me to select **Sync now** and **Choose what to sync**. When I click **Choose what to sync** it redirects to the Settings Menu and it is not clear where to go to select data for backup. 
Will be helpful if when I click Choose what to sync and it opens the Backup data menu (Storage taken) to choose info for backup. 

https://user-images.githubusercontent.com/80623554/218778855-4a6fc65d-8105-4207-ad64-a41dfc190bea.mp4

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14194mqta, Released: 2023-02-22
Done

**Comment by dmpr0** [comment]
## Review
- [ ]  Taping **Choose what to sync** should open **Backup data screen**

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14236mqta, Released: 2023-03-14
Done

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14254mqta, Released: 2023-03-20
Done
