### ISSUE TITLE
Kastelorizo island does not highlited green when the map of Greece is loaded

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#16473]
When I download or select map of Greece Kastelorizo island does not highlited green/ yellow. Visually, there is a feeling that this island is not on the map of Greece
![image](https://user-images.githubusercontent.com/80623554/219042077-cc00fdfb-26e3-41cb-b6d0-8ba7033a254c.png)
![image](https://user-images.githubusercontent.com/80623554/219042133-f8680a61-3e80-4132-bb42-e57c19b70b78.png)

https://www.openstreetmap.org/relation/5321397#map=12/36.1175/29.6288
OsmAnd 4.3.8 Android, 4.3.4 iOS display similar results.
Map updated 1 Feb 2023

**Comment by Zirochkabila** [comment]
Merge to https://github.com/osmandapp/OsmAnd/issues/16090
