### ISSUE TITLE
Iconos con imagenes

### ISSUE THREAD

**Issue by Matrix2033** [osmandapp/OsmAnd#16479]
Buenas tengo varias carpetas en favorito, y en ellas tengo varios poi de peajes, camping, áreas de Servicio etc. Mi pregunta es se puede subir y añadir imágenes y envés de poner los iconos que trai la app ya que para peajes, areas de servicio no hay, y a ver si con estas imágenes se podría subir y así poder las añadir a dichas carpetas, ya que en Google maps si que se puede subir, en el ipotetico caso de que no se pueda hacer, a ver si en próximas actualizaciones lo pudiera incluir gracias

**Comment by hakuchi** [comment]
@Matrix2033 please write in english!

**Comment by scaidermern** [comment]
No need to open a new issue (#16480). You simply could have edited your question. Now please close this one instead.

**Comment by Zirochkabila** [comment]
Merge to https://github.com/osmandapp/OsmAnd/issues/16480
