### ISSUE TITLE
announcement wish: toll or other barriers

### ISSUE THREAD

**Issue by martenjj** [osmandapp/Osmand#1647]
It would be most useful to have the option of announcing these, especially for the car or other vehicle profiles.  These may include motorway toll barriers (péages), border crossings (even if no physical stop is required), or other types of barriers/gates (usually found on country roads).

**Comment by vshcherb** [comment]
We already have announcement of toll_booth. Please make sure you enable it in settings and it mapped on the road. You should also see indication on bottom left. You can check settings in "Navigation Settings"
