### ISSUE TITLE
Straight line when recalculating route

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16475]
### Description
When recalculating the route, a straight line is built
[logcat (64).log](https://github.com/osmandapp/OsmAnd/files/10753992/logcat.64.log)
[Thu 16 Feb 2023.gpx.zip](https://github.com/osmandapp/OsmAnd/files/10753996/Thu.16.Feb.2023.gpx.zip)

### Steps to reproduce
Navigation > Set start `39.9308759, -8.1476236` > Set finish `39.6998083, -8.2672806` > Simulate location by GPX > Select attached GPX

### Actual result

<details><summary>Straight line</summary>
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/219316720-ecdb7be8-8615-459d-a0ef-518f8547e613.jpeg">
</details> 

### Expected result
Recalculation line is built along the way

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14181mqta, Released: 2023-02-16
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by vshcherb** [comment]
Duplicate

**Comment by vshcherb** [comment]
@Zirochkabila please find same open ticket in backlog with straight line recalculation

**Comment by Zirochkabila** [comment]
@vshcherb This issue is similar to https://github.com/osmandapp/OsmAnd/issues/15118
But, it is already closed

**Comment by sonora** [comment]
Bit please note that this report here is for a very recent build: OsmAnd Version: OsmAnd~ 4.4.0#14181mqta, Released: 2023-02-16

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/16277
