### ISSUE TITLE
The Conflicts page is not updated after downloading conflict version from Cloud

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16477]
### Description
The Conflicts page is not updated after downloading conflict version from Cloud - which forces users to download the same conflict again, thinking that it does not work
**Workaround** is to exit the conflicts page and re-enter - the page with conflicts will be updated

[logcat (66).log](https://github.com/osmandapp/OsmAnd/files/10755403/logcat.66.log)

### Steps to reproduce
Menu > Settings > OsmAnd Cloud > Sync > Conflicts > Download cloud version

### Actual result
Conflicts page isn't updated 

https://user-images.githubusercontent.com/104760013/219353829-94d73b9c-182a-459d-a5b9-d64edf39e84b.mp4

### Expected result
Conflicts page is  updated like after "Upload local version"

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14181mqta, Released: 2023-02-16
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by kuiperonline** [comment]
As soon as I open Osmad Cloud menu the status says  checking…

On my iPhone I get FAILED
On my iPad nothing happens

4.4.8.15
