### ISSUE TITLE
Direction on traffic calming doesn't work (iOS)

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#16486]
Traffic calming warning is displayed in 2 directions which is wrong cause it has tag ```direction=backward```

**Comment by Zirochkabila** [comment]
<details><summary>4.4.5.7</summary>
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/219941694-4cb5d705-327e-432d-a0ca-a80ae485977d.jpeg">
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/219941695-4e6785b0-84b0-4d06-9c91-69ac08ccff1e.jpeg">
</details>


<details><summary>OsmAnd~ 4.4.0#14188mqta, Released: 2023-02-19</summary>
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/219941657-56c2d863-3e44-421b-9d19-5e27f47239ad.jpeg">
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/219941659-ae825d54-84f9-4355-9205-9f812e1c43ed.jpeg">
</details>

**Comment by dmpr0** [comment]
## Review
- [ ]  Doesn't work
* * Tested on TestFlight 4.4.8.
* * Settings [Export_01-05-23.osf.zip](https://github.com/osmandapp/OsmAnd/files/11365021/Export_01-05-23.osf.zip)

<table style="width:100%">
  <tr>
    <td><video source src="https://user-images.githubusercontent.com/9365308/235443632-ab505063-003d-40ae-859c-d47821d0937e.mov"  width="300" height="auto"/>   </td>
  </tr>
</table>
