### ISSUE TITLE
Empty map - eastern-cape congo

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#16482]
Map should be either deleted or polygon created https://github.com/osmandapp/OsmAnd-misc/tree/master/osm-planet/polygons/africa/congo-democratic-republic

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14208mqta, Released: 2023-02-28
28.02 master
Done

**Comment by dmpr0** [comment]
It seems Congo has new division into provinces  https://en.wikipedia.org/wiki/Provinces_of_the_Democratic_Republic_of_the_Congo, now it should be 25, OsmAnd shows 11 and old one, for example:
* Bandudu now part of [Kwango](https://en.wikipedia.org/wiki/Kwango) province. OSM has it too https://www.openstreetmap.org/relation/193091#map=8/-6.187/18.045
* Issues with name of currently visible provinces

<table style="width:100%">
  <tr>
    <th>iOS</th>
    <th>Android</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/224357731-03c0e1f8-574a-4561-9521-e00e9a2fa9d4.jpeg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/224357832-d2f66f28-7ae0-4b9c-b7e3-b75bc7b49e2d.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
4.4.6.14
It is not possible to select a separate republic, only Congo as a whole is selected (this is possible in Android)
