### ISSUE TITLE
180° turn arrow the wrong way

### ISSUE THREAD

**Issue by lightonflux** [osmandapp/Osmand#1649]
Used version 2.1.1.

![180° arrow wrong way](https://cloud.githubusercontent.com/assets/1377943/9692706/3fe5ed62-534b-11e5-8b79-d6fd2c8958b8.png)

This is the affected part of the route. [Navigation on osm.org](http://www.openstreetmap.org/directions?engine=osrm_car&route=51.0608%2C7.4757%3B51.0771%2C7.4557#map=15/51.0691/7.4659)

The router in use was osmand offline.

**Comment by sonora** [comment]
Very weird ... take aside the fact that routing should not actually detect this as a turn instruction at all: But even if it is, it should be detected as a sharp right turn, not as a U-turn, unless the user has chosen driving region to reflect "left side driving"? But I assume this in in Germany, and your setting are for continental Europe?

**Comment by sonora** [comment]
I have downloaded the map and ran a simulation with our latest nightly, see attached. OsmAnd actually behaves as expected, no turns are announced at the switchbacks. So it looks like the issue may be outdated?

![screenshot_2015-09-13-10-09-17](https://cloud.githubusercontent.com/assets/845735/9835878/26652f2c-5a00-11e5-8637-b31d0938b6fe.png)

**Comment by lightonflux** [comment]
> So it looks like the issue may be outdated?

Very possible. I think we should push back this issue until the next release. Then retest it and close if it does not appear again.

**Comment by sonora** [comment]
Maybe you can test by manually installing a nightly build if you like.

**Comment by lightonflux** [comment]
Yes i can. Are there apks ready to download of the nightly? And how do i spoof my location?

**Comment by sonora** [comment]
The nightly default apk is linked at the bottom of osmand.net.

For the "spoofing", please
- enable the development plugin in OsmAnd.
- Then select a navigation destination on the map as usual..
- Then select a start point for the navigation, using the context menu's  "Directions from" item. 
- After the route is calculated, go to the OsmAnd Dashboard, on the bottom of which you will find a function "Start simulation"
- After the simulation is started, you may hit the "Go" button on the navigation taskbar

**Comment by lightonflux** [comment]
So i found the time to test it. Installed the nightly from last night and now when i try to click on the popup of the start coordinates osmand closes (crashes). Does not matter if debugging is enabled or not. I sended the crash report.

If i press on a popup of an address it works as expected and does not crash

**Comment by sonora** [comment]
Ye, likely work in progress with the popups, and unrelated t this issue.

**Comment by Barrocas** [comment]
Should Osmand give a warning when aproaching such tight curves? 

In car mode, It could be helpfull to avoid accidents, but that would mean Osmand could be like a rally co-pilot...?
