### ISSUE TITLE
OpenGL: Building parts are rendered with no border

### ISSUE THREAD

**Issue by Max1234-Ita** [osmandapp/OsmAnd#16492]
### Description
If a building is composed by several parts, they are not visible if the OpenGL engine is active. 
Instead, they are visible with the native rendering.

### Steps to reproduce
1. Have OsmAnd installed, with at least one offline vector map;
2. Launch OsmAnd;
3. On the map, locate a building that is composed by several parts (building:part tag in OSM), i. e. this:  [45.46419° N, 9.19150° E](https://osmand.net/map?pin=45.46419,9.19150#18/45.46419/9.19150) 
4. Observe that only the external border of the building is visible, while the internal parts are not. The picture below shows a comparison of the same building from the JOSM editor and OsmAnd with OpenGL:

![image](https://user-images.githubusercontent.com/15315381/219904084-a7a8ba98-6a28-47c0-b5ff-3171d583b8c2.png)

5. Select the Native engine and check the rendering of the same building: the internal parts are now visible (see picture below).

![image](https://user-images.githubusercontent.com/15315381/219904173-d10c7089-0621-4145-9bf9-46a4f74b891f.png)

### Actual result
Only the external border of the building is traced; the parts are not rendered by OpenGL engine; They are, instead, if the Native rendering is used

### Expected result
Map elements which have the _building:part_ tag should be distinguishable from the background color when rendered by OpenGL engine, as well as they are with the native rendering.

### Your Environment
OsmAnd Version: 4.3.8
Android/iOS version: Android 11
Device model: Samsung Galaxy A50 (SM-A505 FN/DS)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14204mqta, Released: 2023-02-26

When you enable **More details** and switch to V1 rendering, the interior of the building is displayed.
With V2 rendering - not displayed
[OSM](https://www.openstreetmap.org/way/520952970#map=18/45.46419/9.19275)


https://user-images.githubusercontent.com/104760013/221404453-a237c9ee-a558-4e92-a23b-ee0cb41798c3.mp4

**Comment by Max1234-Ita** [comment]
Thank you very much

**Comment by dmpr0** [comment]
Re-check with **April** map updated.
