### ISSUE TITLE
Gpx start and finish icons can't be hidden

### ISSUE THREAD

**Issue by Athoss9** [osmandapp/OsmAnd#16499]
### Description

The setting for turning the gpx start and finish icons does not work.

### Steps to reproduce

Configure map -> Tracks -> Appearance -> Start and finish

### Actual result

The checkbox is always unchecked and the icons are always shown.

### Expected result

The state of the checkbox should change and the start/finish icons should be hidden/shown.

### Your Environment
OsmAnd Version: OsmAnd+ 4.3.12
Android/iOS version: Android 9
Device model: Xiaomi Mi A1

**Comment by Rowin63** [comment]
_Configure map -> Tracks -> Appearance -> Start and finish_

I have experienced, that via this menu you have to check first and then uncheck it again, then the icons of _all displayed tracks_ are gone (and as long as you don´t touch any colour while doing so, also different dispayed colours are not changed).
I hope this fact will disappear with the new "track options menu".
You can also switch this symbols on/off one by one in each tracks editing menu.

**Comment by Zirochkabila** [comment]
https://user-images.githubusercontent.com/104760013/220165439-3f2d24d9-323b-41a0-8fd2-c57ca38e1ced.mp4

**Comment by vshcherb** [comment]
New tracks change appearance available now.

**Comment by Zirochkabila** [comment]
@Athoss9  New tracks appearance menu solves this issue
