### ISSUE TITLE
Mapping for quickaction pause/continue navigaton

### ISSUE THREAD

**Issue by mastromberger** [osmandapp/OsmAnd#16496]
### Description
Mapping for quickaction pause/continue navigaton seems to be wrong, after selection quickaction simulation of location with gpx is taken/displayed

### Steps to reproduce
Add quickaction pause/continue navigaton
![image](https://user-images.githubusercontent.com/39034541/219960383-d0656a94-8024-4734-8509-b0251d47022b.png)

### Actual result
Simulation of location with gpx is taken/displayed 
![image](https://user-images.githubusercontent.com/39034541/219960393-0353e889-49b7-4467-8622-5c821027fa98.png)

### Expected result
Quickaction pause/continue navigaton should be taken/displayed 

### Your Environment
OsmAnd Version: 4.3.12
Android/iOS version: Android 13
Device model: Samsung Galaxy S23 (SM-S911B/DS)

**Comment by mariush444** [comment]
https://github.com/osmandapp/OsmAnd/issues/15626

**Comment by Zirochkabila** [comment]
@mastromberger Not reproducing
Try downloading the night version https://osmand.net/docs/versions/nightly_versions

https://user-images.githubusercontent.com/104760013/223452925-45415022-567d-42fb-8c2d-0e2d2ddd19aa.mp4

**Comment by mastromberger** [comment]
Hi, I've checked it once again
01: Removed all quickactions
02: Add new quickactions -> in selection for available quickactions are these entries: Start/stop navigation and Pause/resueme navigation
03: On selection Pause/resume navation the quickaction has the name Simulate location by GPX like in your video

I think my assumtion was wrong - I thougt that after adding Pause/Resume navigation I'll have the possibility to pause and resume the navigation with the quickactions, but after readion the manual there is nothing with pause and resume: https://osmand.net/docs/user/navigation/route-navigation/

Thanks for your time ;) ... I'll close this report because my assumption was wrong

![Screenshot_20230308_201704_OsmAnd](https://user-images.githubusercontent.com/39034541/223826114-08dd0898-2652-4c22-88d1-86ecc88a9a33.jpg)
