### ISSUE TITLE
Wrong version numbers in the Play store?

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#16493]
I am confused with these:
![Screenshot_20230219-090338_Firefox](https://user-images.githubusercontent.com/845735/219936485-ded98235-88b6-4dc8-8c05-e129366b2b08.jpg)
![Screenshot_20230219-090412_Firefox](https://user-images.githubusercontent.com/845735/219936486-6daaa34b-e2e2-43bf-8388-f474a9c21feb.jpg)

**Comment by vshcherb** [comment]
Staged updates

**Comment by sonora** [comment]
Ok. But these screenshots are without google account. Would have thought then you always see not only the latest update date ("Feb 17, 2023"), but also version. Seems not.

**Comment by vshcherb** [comment]
Today should be 4.3.12

**Comment by sonora** [comment]
Yes, confirmed!
