### ISSUE TITLE
Turn-by-turn lanes suggests to exit earlier than it should be 

### ISSUE THREAD

**Issue by gauravjuvekar** [osmandapp/OsmAnd#16498]
### Description

Turn-by-turn description, next turn arrows, announced TTS turns are incorrect and differ from route line.
The route line shows continuing along a highway, while the next turn incorrectly shows taking highway exits.

### Steps to reproduce

Navigate from `37.42450 -121.92369` to `37.41325 -121.97770`.

### Actual result
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/2271906/219986770-0bbf6065-a248-4542-95a3-25be6185592b.png"  width="400" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/2271906/219986783-5d67bdb5-eac2-453f-acec-52a0cda9e88c.png"  width="400" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/2271906/219986807-a1871050-8b11-404d-928c-4d2934c792ca.png"  width="400" height="auto"/> </th>
  </tr>
</table>  

### Expected result

The exit 8 and exit 7 turns are incorrect. The route line should be followed. 

### Your Environment
Version : 11
App Version : OsmAnd~
Apk Version : 4.3.8 4308 (build from Fdroid)

AFAIK, this is a regression since 4.3
4.2 used to work correctly.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14204mqta, Released: 2023-02-26
[OsmAnd](https://osmand.net/map/?start=37.424322%2C-121.923609&end=37.413169%2C-121.977682&mode=car#15/37.4166/-121.9507)
[Map](https://drive.google.com/file/d/1dNGYyRhaNfiojLdv0KuIxhesSx5qdVLV/view?usp=sharing)

<details><summary>Turn errors</summary>
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/221405477-b4266b87-4231-4737-8569-5dd5f3a07c7a.jpeg">
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/221405479-577a76f7-73bc-4748-a7e0-125b83367aca.jpeg">
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/221405480-ba802c54-8b5d-427b-8dd3-5d3c81693058.jpeg">
</details>

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14206mqta, Released: 2023-02-27
`47.79535, -116.89981` to `47.79661, -116.89764`
[OSM](https://www.openstreetmap.org/directions?engine=graphhopper_car&route=47.79547%2C-116.89974%3B47.79661%2C-116.89767#map=17/47.79605/-116.89881)
[OsmAnd](https://osmand.net/map/?start=47.795457%2C-116.899681&end=47.796571%2C-116.897793&mode=car#17/47.79543/-116.89786)
[Map](https://drive.google.com/file/d/1pmGO4ii9wVf9tQ36PTJkLGFmDnBvbHjz/view?usp=sharing)

Turning right is displayed as a roundabout
<details><summary>Roundabout</summary>
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/221553911-b6f16949-e46d-4161-9856-52aeba1de5b2.jpeg">
</details>

**Comment by vshcherb** [comment]
Road that is circle and oneway is treated as roundabout - https://www.openstreetmap.org/way/1123017192#map=18/47.79520/-116.90086
