### ISSUE TITLE
New map rendering engine (V2) does not immediately display favourites

### ISSUE THREAD

**Issue by ceever** [osmandapp/OsmAnd#16497]
### Description
Before with the old rendering engine, favourites were always displayed immediately, even if the map was not yet full rendered. Basically, they were always there, even when zooming and rotating

Now, with the new rendering engine, favourites are only displayed as the very last step in the display, after the map or where the map has fully loaded. This makes navigating through the maps very hard, because sometimes navigation is done based on the favourites even without full map display, since one knows where they are approximately. However, now (with V2) one can do nothing for 5 seconds until one sees the favourites.

### Steps to reproduce
Navigate through the map, once with rendering engine V1 and once with V2.

### Actual result
Favourites are only displayed after the map has been fully rendered.

### Expected result
Favourites are always displayed. Even without any maps yet in display.

### Your Environment
OsmAnd Version: 4.3.5
Android/iOS version: 9
Device model: Galaxy S8

**Comment by vshcherb** [comment]
We find this issue is not critical to fix
