### ISSUE TITLE
Map changes orientation - N after restart activity

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16495]
### Description
After changing the V2 rendering to V1, the map changes its orientation
[logcat (69).log](https://github.com/osmandapp/OsmAnd/files/10776617/logcat.69.log)

### Steps to reproduce
Compass orientation "N" > Settings > Map rendering engine > V1 > Zoom out

### Actual result

https://user-images.githubusercontent.com/104760013/219942336-7e09b68a-13e7-494d-be30-808a05c411be.mp4

### Expected result
Map orientation remains the same

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14188mqta, Released: 2023-02-19
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by sonora** [comment]
I guess something like this code
https://github.com/osmandapp/OsmAnd/blob/8a98bd8cfc636dc9e6163e9de1aea97584f4dc44/OsmAnd/src/net/osmand/plus/base/MapViewTrackingUtilities.java#L247-L249
needs to be executed when the activity is recreated, but it seems it is only traversed if `isMapLinkedToLocation`. (I would guess that after you tap the 'My Position' widget, the map rotation gets finally set as ecpected?)

**Comment by sonora** [comment]
This seems not limited to an V1-> V2 change, but rather to the map activity being recreated _**for whatever reason**_ . It can sometimes be reproduced as follows:
- I use a build without OpenGL libraries, this takes V2->V1 change out of the picture
- Have your default profile set to Browse map, with "Map orientation=North is up". Have your Pedestrian profile set to "Map orientation=Compass direction"
- Fresh start of the app: Switch to the Pedestrian profile. Pan and zoom the map a bit.  Make sure the map i**_s not linked to location_** (i.e. you panned it manually), then close (force-stop) OsmAnd, e.g. by swiping it up in the Android change-app mechanism.
- Now restart OsmAnd: OsmAnd will start and display the map in the Browser map profile. The profile will also always be correctly in "North is up" mode, as can be verify both in its profile settings as well as by the tapping behavior of the compass widget.
- But despite this, in rather rare occurrences, the compass widget's North will not point upward, it (and the displayed map) will remember the last "compass" rotation from the previous Pedestrian profile. It looks like the rotation is not reset to 0 upon activity restart (though the map orientation settings is). Tapping the blue ""Where am I" button will then fix it.

**Comment by vshcherb** [comment]
Not planned to fix
