### ISSUE TITLE
Track appearance not correctly indicated

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#16509]
- [x] Recorded track in default appearance, i.e. appearance has never been customized: Tap on the track, then on its context menu tap the appearance button. You will receive this dialog, where neither the current color button is circled, nor is the current track width marked:

This is for the example of the OsmAnd Map style, but the issue is also present for all other Map styles.

- [x] Note: The new 'Default track appearance' dialog accessible via `Configure map > Tracks` does circle the correct color all right, but also has the issue that the track width in use is not correctly reflected.

![Screenshot_20230220-231353_OsmAnd~](https://user-images.githubusercontent.com/845735/220206523-bd657ef8-8167-4ca1-879d-1d2081a45ada.jpg)

Moved -> https://github.com/osmandapp/OsmAnd/issues/16584

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14222mqta, Released: 2023-03-07
Record a new track > Options > Appearance > Current color and line width are not highlighted
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/223477014-845ec736-f963-4b48-97c5-10fcca221647.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by sonora** [comment]
@Zirochkabila Can I please ask you to verify: I think the color is now correctly indicated, but not he width? If e.g. I use the map style 'Touring view' and its track default  it shows me width "Default" and "1", but that' s certainly not correct?

**Comment by sonora** [comment]
Here's how it looks for me, the color is now right, but "Custom" with "width="1 seems wrong?
![Screenshot_20230320-222427_OsmAnd~](https://user-images.githubusercontent.com/845735/226469704-732ae5ba-d413-4501-b62a-69d6b046e6ea.jpg)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14261mqta, Released: 2023-03-23
When switched to Touring view, the width of the route line changes (V1 and V2)

Configure map > Map style > Touring view

https://user-images.githubusercontent.com/104760013/227168141-8f2416b3-75c8-4c40-b889-fec38e73049b.mp4

**Comment by sonora** [comment]
I could actually fix this via this commit: https://github.com/osmandapp/OsmAnd-resources/pull/949.

I am not sure this is by design, but it seems that _the first of the comma-separated values under the renderingProperties' 'possibleValues' is recognized as default_. (And not the numerical actual value the renderer paints with).

So if this is by design and a valid fix, we could document that here
https://github.com/osmandapp/OsmAnd-resources/blob/6b4008bdf75241e32916634ab384673f39345c8f/rendering_styles/default.render.xml#L69 and close this issue, possibly even without merging https://github.com/osmandapp/OsmAnd/pull/16838?

**Comment by sonora** [comment]
I think we should clean up how we use `renderingProperty`:
- It allows for a `description` tag, I think it may be deprecated.
- We have a `defaultValueDescription` tag but are missing a `defaultValue` tag.
- In many places, e.g. https://github.com/osmandapp/OsmAnd/blob/6020aa521782bff95590a1e2dbcf9716fb9019f8/OsmAnd/src/net/osmand/plus/track/TrackDrawInfo.java#L144 leading to this issue, we use method `property.getPossibleValues()`, which returns a string array of all possible actual values, e.g. [thin,medium,bold], but without indication of the default value.
- In other places, e.g. https://github.com/osmandapp/OsmAnd/blob/6020aa521782bff95590a1e2dbcf9716fb9019f8/OsmAnd/src/net/osmand/plus/configmap/ConfigureMapUtils.java#L90 we shift the returned array results by 1 and place in position [0] the translated string of `defaultValueDescription`. (Not sure if we use this anywhere.)

(1) In any case it would make sense to rethink the system somehow and decide if `renderingProperty` should facilitate an explicit `defaultValue` parameter for the dialogs to use for action "reset to default". `getPossibleValues()[0]` could e.g. consistently return this tag, everywhere. Or instead read it explicitly via `getDefaultValue()`.

(2) For `renderingProperty attr="currentTrackWidth"` we further lack a mechanism to detect the numerical **actually used line width**, which would be needed as the starting value if users select the "Custom" button. Having to parse the renderer to detect this seems like too heavy a method...

**Comment by vshcherb** [comment]
Solution was proposed to do 3 requests thin / thick / medium and for all others don't display as selected. Displaying default is not an option.

Also we plan to keep simplifying rendering style and remove it from rendering style, to simply keep it configurable only in UI. So it might less important issue for now.

More important feature will be to configure track appearance in a bulk mode.

**Comment by sonora** [comment]
Yes, today we are complicating things by having two overlapping approaches:
- We allow the renderer files to specify _verbal_ values like fine/thin/medium/bold as a renderingProperty and then they effectively define their own numerical values for each.
- In  addition, on our UI dialogs we also allow the selection of a separate conflicting or overlapping Custom _numerical_ value.

Approach could be
1. To base everything in the backend uniformly on one _numerical_ "GPX width" parameter only.
2. Remove the _verbal_ values in the renderers, replace with just the "GPX width" parameter, i.e. allow any actual selection only via the UI.
3. If desired, in the UI only create _verbal_ shortcut buttons (or additional labels on a selection slider slider) fine/thin/medium/bold, for things certain numerical values. But these will not propagate to the backend, will iby the UI mmediately be resolved to a numerical value (2/4/8/12).
- But I think it is mandatory we let each renderers specify its default (numerical) value and in the UI we respect it for tracks with no appearance information and for action "Reset to default", because a default track appearance is a specific characteristics of each map style.

**Comment by sonora** [comment]
As a side finding: The (at least width) indication of track appearance in the new dialog is frequently wrong, both for tracks visible an not visible on the map.

See these two screenshots, they indicate different width for different tracks. But  all tracks are displayed on the map wirh the same width (medium=8pt), and that same value is also the renderer's default (i.e. would be used to display the currently invisible tracks). But the dialog shows a mixture, it seems to show "thin" for all not visible tracks?


What is the meaning of an appearance indication for invisible tracks anyway? Apparently it seems _not_ "how it would appear if it was visible"?

![Screenshot_20230423-075307_OsmAnd~](https://user-images.githubusercontent.com/845735/233823183-2817d749-461d-427c-994c-ae18a6b9e79f.jpg)
![Screenshot_20230423-075351_OsmAnd~](https://user-images.githubusercontent.com/845735/233823185-4709c426-83d8-4559-b35a-ca6c617f4055.jpg)

**Comment by vshcherb** [comment]
Probably we need to close that issue as overwhelmed with information and open new one. Where we could simply ignore rendering style settings. 

The only use was to have different width scale  in different rendering styles but now it becomes overconfusing. All styles than should support exactly same "thin", "medium", ".." thickness no custom are allowed. 

So I think we should prepare new issue to remove color / width being propagated from rendering styles.

**Comment by sonora** [comment]
Yes makes sense for the width,
```
<case currentTrackWidth="fine" strokeWidth="2"/>
<case currentTrackWidth="thin" strokeWidth="4"/>
<case currentTrackWidth="medium" strokeWidth="8"/>
<case currentTrackWidth="bold" strokeWidth="12"/> 
```
seems to fit most renderers, with perhaps `fine` not very frequently used in practice in my experience.

For the colors it's trickier, because renderers vary considerably in the degree of color saturation they use, hence a renderer-specific color intensity / palette for tracks seems actually quite crucial. At first sight I would say let's keep the current propagation of colors to the appearance dialog (it works flawlessly now - this issue was only still open about the track width).

**Comment by vshcherb** [comment]
I think we better spend resources on Default Group (Change all) Appearance time cause it will be open for every user and "Default" will be mean same "As group" configured.

**Comment by sonora** [comment]
So effectivley do you have a 2-tier structure in mind like this: On the "Change appearance" dialog 
-  we add a checkbox called 'Set as user default"
-  we have a button "Reset to user default".
- we have a button "Reset user default to system default'?
