### ISSUE TITLE
OpenGL error message

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#16504]
### Description
When OpenGL rendering is disabled, user still receives an error message that OpenGL rendering crashed, please switch the rendering engine to Version 1. 

OsmAnd has reverted to version 1. You can try reverting to the new version 2 in the settings.
Please support improvements by sharing your bug log.
![image](https://user-images.githubusercontent.com/80623554/220163017-9588e73e-d595-49c4-a31f-d0d683cba3c6.png)
[logcat (50).log](https://github.com/osmandapp/OsmAnd/files/10786347/logcat.50.log)

### Steps to reproduce
Open OsmAnd -> receive an error message.

### Your Environment
OsmAnd Version:  Device : HWELE
Brand : HUAWEI
Model : ELE-L29
Product : ELE-L29EEA
Build : ELE-L29 10.1.0.150(C431E22R2P5)
Version : 10
App Version : OsmAnd
Apk Version : 4.3.8 4308

**Comment by Zirochkabila** [comment]
Still present - seems to be related to this issue https://github.com/osmandapp/OsmAnd/issues/16483#issuecomment-1453323831

**Comment by Zirochkabila** [comment]
https://github.com/osmandapp/OsmAnd/issues/16483#issuecomment-1458420848

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14239mqta, Released: 2023-03-15
So far, this error hasn't been encountered

**Comment by anastasiia936** [comment]
Crash massage without crash:

When user opens OsmAnd, he receives and error message that OsmAnd's map rendering has recently crashed. The user said that: "when I open OsmAnd I see an error message popping up saying "OsmAnd's map rendering has recently crashed."

But this is not true! The app always works flawlessly! I never see any errors during use. I always use v2 rendering and I've never had issues.
When I click on 'share crash log' on that popped up message, I can't send or share it anywhere. I tried all kinds of apps and saving it on Google Drive, but somehow there is no file to upload in the first place. So OsmAnd says it's crashed (which is not true) and then suggests I should share a crash log file (which doesn't understand exist)...

I can't send you any log files currently because as I said, the error only occurs usually when I OPEN the app, NOT when I USE it.

OsmAnd 4.3.12, Xiaomi 11 Lite 5G NE with MIUI 14.0.2 and Android 13.
![image](https://user-images.githubusercontent.com/80623554/225621292-e58a43c9-6e1f-4777-a964-d92325317d10.png)
