### ISSUE TITLE
When changing zoom, fade from old rendering to new

### ISSUE THREAD

**Issue by lightonflux** [osmandapp/Osmand#1651]
At the moment (2.1.1) when you only use offline rendering and you zoom it might take some time for different reasons. If the rendering is slow that means that the old tiles disappear before the new tiles are rendered and you see the background colour. 

It would be nicer if osmand would fade from the old tiles to the new ones.

**Comment by sonora** [comment]
I think what you are describing is not the actual behavior (at least not with our classic rendering, no sure about GL): When zooming out, the screen immediately displays the old screen section smaller, you can still see it, and you can see the new rendering (in the new areas around( it building up. When zooming in, the old tile is immediately magnified until the new rendering is ready.

I think this kind of immediate reaction is good feedback for the user showing that the zoom action requested has the desired effect but takes a little wait to complete, we should not change this!
