### ISSUE TITLE
show "track folder" in the list of visible tracks

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#16515]
# 🚀 feature request

### Description
it would be helpful to see also the name of the folder of a track in the "list of the visible tracks" in "my places".
sometimes that would help to identify the correct track.

### Describe the solution you'd like
add the information of the folder where the track is in

### Describe alternatives you've considered
no alternatives, sometimes it´s just scrolling up/down, switching tracks off/on to find the one I want to edit ;-)

Thanks!

**Comment by sonora** [comment]
I think this is my number (6) here  #16508  for the screen I understand is planned to replace this one some time soon.

**Comment by Zirochkabila** [comment]
Merge to https://github.com/osmandapp/OsmAnd/issues/16508

**Comment by Rowin63** [comment]
> I think this is my number (6) here #16508 for the screen I understand is planned to replace this one some time soon.

Not exactly. 
I meant here ("visible tracks" in "my places"):

![Screenshot_20230222_072608_OsmAnd+](https://user-images.githubusercontent.com/95540936/220546039-261cd58f-0c98-43fe-a8a1-be918bad0a27.jpg)

and would be also helpful here (tap on the map):

![Screenshot_20230222_073048_OsmAnd+](https://user-images.githubusercontent.com/95540936/220546062-8f7c954f-2df0-4573-93d1-92f6e98da6ca.jpg)

Thanks!

**Comment by Rowin63** [comment]
I don´t think, that first screen should go away!
It´s a main part of the overall view of all my places!

**Comment by dmpr0** [comment]
We starting to redesign all screens related to Tracks. **Tracks** screen in **My Places** will be changed and will looks more like file manager without collapsable folders. **Visible tracks** will open new Tracks menu in Configure Map on **On Map** tab.

**Comment by sonora** [comment]
Would we all agree that the goal is to maintain just one **Tracks management** screen? It must have the maximum functionality you need around both managing and displaying tracks. And yes, if really necessary it could be asscessible via different user paths like `Configure maps > Tracks` or `Menu > MyPlaces > Tracks`, but you should end up on the same screen maintained by the same code?

In the past we suffered a lot from the fact that there were two semi-functional screens, most users knowing only one of them, never even having discovered the complementary one...

In my mind OsmAnd must become a powerful **GPX management software** and the corresponding capabilities should become a lot more organized and discoverable than today...
