### ISSUE TITLE
Add Communication antennas POI

### ISSUE THREAD

**Issue by Arian03dc** [osmandapp/OsmAnd#16526]
# 🚀 feature request

### Communication POI's

 In my country (Cuba) the cellular coberture coverage is very short, and we create homemade antennas, but is hard to locate the communication antennas for ubicate the homemade antenna,and would be more easy if this POI would be to exist

### Describe alternatives you've considered

Use third-party maps, like CellMapper or others -->

**Comment by Zirochkabila** [comment]
@Arian03dc Duplicate https://github.com/osmandapp/OsmAnd/issues/16442 ?

**Comment by Arian03dc** [comment]
Your issue is for 3G, 4G, 5G and WiFi antennas?

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/16442 this is only relevant information in OSM
