### ISSUE TITLE
Position arrow does not move forward during a curve, it just turns in its place and only changes orientation

### ISSUE THREAD

**Issue by oxxm** [osmandapp/OsmAnd#16527]
### Description
During navigation the blue arrow stops moving forward during a long curve, it just turns left (or right) in its place. When the road ahead is straight again, and the curve is almost over, the blue arrow suddenly jumps forward to the actual GPS position.

### Steps to reproduce
1- start navigation
2- go into a long left or right curve

### Actual result
The blue arrow of the actual position does not move forward, it stands still and changes only the orientation. When the curve is over and a straight line is ahead, the arrow suddenly jumps forward.

### Expected result
Blue arrow should move forward during the curve.

### Your Environment
OsmAnd Version: 4.3.8
Android: LineageOS 17.1
Device model: Samsung S9

### Additional Info
This was not occuring with earlier releases. Not with 4.3.5 at least.

**Comment by Zirochkabila** [comment]
@oxxm Please add a video

**Comment by Rowin63** [comment]
I think, this is the setting: profile configuration>general settings>"animate own position" (i dont know how it is named in english, in german it is "eigene Position animieren)>off. Dont find the issue where this was written, had the same problem and it is gone with this setting "off"

**Comment by Rowin63** [comment]
It´s here #16081 and it is named "animate my location". Switch it off.

**Comment by oxxm** [comment]
This is the exact behaviour described in those screenshots:
https://github.com/osmandapp/OsmAnd/issues/16081#issuecomment-1368066116

Will try it in the next days with animate own position off and close the ticket.

Thank you all!

**Comment by Rowin63** [comment]
Yes, this was my post ;-)
So switching this mentioned setting to "off" is the solution, did not ever happen again!

**Comment by oxxm** [comment]
With switching animate own position to off the issue is resolved. But the refresh rate of the position is not what it used to be, it is much lower now, and is not smooth as it used to be in earlier version. Will closed this issue. Thanks!
