### ISSUE TITLE
non-existent roundabout announced via voice commands

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#1652]
1. download map of Slovakia (date of 7th Aug 2015)
2. look for junction node 700425 (on Senecka cesta near Ivanka pri Dunaji).
3. put a destination somewhere on Senecka cesta (I am not sure how far that needs to be).
4. put starting point on the opposite side of the junction. I used real GPS position, not sure if that is needed to reproduce it.
5. start navigation

Result:
OsmAnd announces to "enter a roundabout in X metres" at that spot (X being only several metres). But that is only in the voice commands. There is no roundabout on the screen and nothing in the "next turn" widget. The next turn is the roundabout in Bernolakovo (junction of Senecka cesta and Dukelska), which is far away. So maybe OsmAnd is somehow confusing the distance to the roundabout. Or there is a bug in the voice commands. I used the Slovak voice. I am not sure now if it needs to be the TTS or pre-recorded voices.

**Comment by sonora** [comment]
Aceman, As a general rule:
- tts voices are always better maintained up to date (because it is easier) than recorded voices
- the English tts voice is one of the reliably ones, many other languages cannot be well tested by most of us developers.  :-)

So I would say:
- Can you please verify how the English tts voice (as a reference) behaves in exactly this situation?
- Also: I am currently fine-tuning lead distances for voice prompts, see issue #1411, so maybe try a new nightly and see if it makes a difference (there were some oddities in our release version)

Thanks, Hardy

**Comment by aceman444** [comment]
Yes, I can try the English TTS.

**Comment by vshcherb** [comment]
Yes would be good to try with different voice, simulation could help.

**Comment by Barrocas** [comment]
If there is a place on map were there are roads in a somewhat closed circuit, it may issue roundabout warning.

I noticed this on a road were the mapper made a combined way of 2 oneway roads, making a way shaped like a stretched hexagon, in a closed circuit, without turn restrictions, so Osmand assumed a roundabout.
I separated the ways and it was corrected.
Check the Osm map, and see if it is the case.

**Comment by vshcherb** [comment]
Could please somebody share link to location via http://openstreetmap.org/

**Comment by aceman444** [comment]
My reported place is at https://www.openstreetmap.org/#map=18/48.19416/17.24314&layers=N (node 700425). Sorry I couldn't yet test it in real life with EN TTS as it requires me to drive to the place which I am not able to do often.

**Comment by vshcherb** [comment]
We can test (I will do it via Map creator).

**Comment by vshcherb** [comment]
So far I don't see any instruction about roundabout https://www.dropbox.com/s/i8d0i0ms5mvo7ua/Screenshot%202015-11-07%2021.21.32.png?dl=0. Please try to reproduce or give more information.
