### ISSUE TITLE
The setting 'Show currently recorded track on map' is counted as a visible track

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#16524]
If the setting 'Show currently recorded track on map' is active, it is counted like a visible track even if no track is currently being recorded. The effect is
- that the number of allegedly visible tracks displayed in the sub-line of menu item `Configure map > Tracks` is too high by 1 (i.e. one higher than the number of actual entries on the new "On map" tab of the new track management screen.
- If no tracks are selected as visible and no recording is ongping, this "On map" tab will appear empty, but the message "No tracks on map" does not show on it, probably because the number of visible tracks is falsely counted as 1.

**Comment by vshcherb** [comment]
Sounds like a bug but probably can be moved to all bugs related to current tracks - so there will be no need to have 15-20 track related issues cause it's harder to manage them - So I would merge it as well

**Comment by sonora** [comment]
Merged to #16508.
