### ISSUE TITLE
leisure=sports_centre rendered in the wrong color

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#16533]
### Description
The default.render.xml specifies the color for educational institutions.

```
<switch>
<case minzoom="13" tag="leisure" value="stadium" color="$stadiumColor" color_2="$stadiumStrokeColor"/>
<case minzoom="13" tag="leisure" value="sports_centre" color="$buildingEducationalColor"/>
<apply strokeWidth_2="1"/>
</switch>
```

### Actual result
![Screenshot_2023-02-23-20-46-45-419_net.osmand.plus.jpg](https://user-images.githubusercontent.com/12549744/220989067-03777fe8-6dc8-43c4-93c8-864183c84b09.jpg)

https://www.openstreetmap.org/way/297521688

![Screenshot_2023-02-23-19-37-39-802_net.osmand.plus.jpg](https://user-images.githubusercontent.com/12549744/220989765-78fdeb08-0894-437d-aeba-adb2bd2c0c4a.jpg)

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14194mqta, Дата выпуска: 2023-02-22
Android version: 12
Device model: poco f3

**Comment by xmd5a2** [comment]
Fixed
![Screenshot_2023-02-28_11-26-46](https://user-images.githubusercontent.com/5829014/221796388-46ba747f-2109-43ef-b8d1-51b970f478ca.png)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14217mqta, released: 2023-03-04
4.4.6.2
Done
