### ISSUE TITLE
Menu structure

### ISSUE THREAD

**Issue by GuentherGredy** [osmandapp/OsmAnd#16546]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Dear OsmAnd Support,

in order to become safer when using OsmAnd and to be able to use all the features, I recently tried to document the menu structure (see attachment).
In the main menu there is an entry "Configure map". The same setting options can be reached via the menu "Configure profile" > "Configure map". I marked that in red.
What is the reason for this apparent double implementation?
Thank you very much.

[1_Osmand-Menu.pdf](https://github.com/osmandapp/OsmAnd/files/10834233/1_Osmand-Menu.pdf)

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by scaidermern** [comment]
There are other similar cases. It really depends on your drawer settings. Take a look at Configure profile / UI Customization / Drawer. There are many items that you can activate or deactivate in order to speed-up access to a certain setting or to simplify your drawer.

**Comment by dmpr0** [comment]
There is no double implementation in case of Configure Map, you can access it thru:
* Button on the map
* Item in Drawer/Left menu
* Configure Profile settings
This is done for quick access.

**Comment by GuentherGredy** [comment]
Good morning, thank you for answering. I've tried the UI Customization menu and it's really a great convenience. Sorry I overlooked that. BR Guenther
