### ISSUE TITLE
Track being recorded is hidden if starting point off current view

### ISSUE THREAD

**Issue by pe-ppe** [osmandapp/OsmAnd#16541]
In 4.3.8 the track currently being recorded is not drawn if its starting point is out of the current view. If the map is scrolled or zoomed out to include the starting point, the track will appear.
Scroll or zoom in to hide the starting point and the currently recording track will again disappear.

**Comment by Zirochkabila** [comment]
@pe-ppe Please update OsmAnd - this has already been fixed.
