### ISSUE TITLE
External Sensor plugin not showing up in F-Droid release

### ISSUE THREAD

**Issue by LnLcFlx** [osmandapp/OsmAnd#16540]
### Description
The external sensors plugin does not show up in the plugins section unlike as described [here](https://www.osmand.net/docs/user/plugins/external-sensors).

| Screenshot 1 | Screenshot 2|
|---|---|
| ![Screenshot 1](https://nextcloud.haagfank.de/s/n7WMPD5n27a85i8/download?path=&files=OsmAnd_1.png) | ![Screenshot 2](https://nextcloud.haagfank.de/s/n7WMPD5n27a85i8/download?path=&files=OsmAnd_2.png) |

### Steps to reproduce
I am using OsmAnd+ from [F-Droid](https://f-droid.org/en/packages/net.osmand.plus/).

### Your Environment
OsmAnd Version: 4.3.8 (latest)
Android/iOS version: Android 13 (LineageOS 20)
Device model: Motorola moto g100 "nio"

**Comment by Zirochkabila** [comment]
@LnLcFlx Please contact the F-Droid developers on this issue.

**Comment by licaon-kter** [comment]
This is about ANT+? If so, no... as the libs are not FOSS, afaik.

**Comment by dmpr0** [comment]
> This is about ANT+? If so, no... as the libs are not FOSS, afaik.
Yes, currently OsmAnd supports only ANT+ sensors, but we have plans to add support for BLE sensors.

**Comment by LnLcFlx** [comment]
Got it thanks. Will BLE likely be supported in the F-Droid release?

**Comment by licaon-kter** [comment]
@LnLcFlx not sure how it's implemented, but F-Droid has other BT apps like GadgetBridge :shrug:
