### ISSUE TITLE
Сan reload a previously downloaded map

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16553]
### Description
Сan download a previously downloaded map again
[Same ](https://github.com/osmandapp/OsmAnd-iOS/issues/2434)

### Steps to reproduce
Menu > Download maps > Select previously downloaded map > Download again

### Actual result
It's possible 

https://user-images.githubusercontent.com/104760013/221577302-a1c0f9cf-81d5-4ae1-93de-aee1dba89803.mp4

### Expected result
Cannot be re-downloaded

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14206mqta, Released: 2023-02-27
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by vshcherb** [comment]
It's a feature not a bug!
