### ISSUE TITLE
Bad side panel display

### ISSUE THREAD

**Issue by franco999** [osmandapp/Osmand#1655]
Google Translator for english -
Since leaving the night version of the new design of the side panel, it shows me around the map, so I can not see properly sidebar options (at least on my phone).
The view is something like (my phone not draw the problem, so here I had to edit):
![12](https://cloud.githubusercontent.com/assets/12088580/9699661/be550194-53c1-11e5-8c12-06662dca51d3.png)

hardware or software ploblem?

**Comment by franco999** [comment]
Update: When active the GPS and the application screen is updated every second, the error is corrected. But while the display is not updated, the error persists.

**Comment by vshcherb** [comment]
Is there any update with latest build?

**Comment by franco999** [comment]
@vshcherb Currently I have version #12886M and is still happening. It is difficult to explain without a picture, but my phone did not photograph the error.
I remember that this had happened before in the nightly version 2.0, but later they corrected. I do not know if it's a hardware problem on my phone or the application itself.

**Comment by franco999** [comment]
I could copy the effect that makes me the phone with a photo editor and something shows me the side menu when the display is not updated. It seems that the menu was a layer on the buttons and widgets, but below the map.
![12](https://cloud.githubusercontent.com/assets/12088580/9769937/80c00a14-5703-11e5-9152-19d3dbe193b9.png)

**Comment by dmpr0** [comment]
Hi, what android version you have?

**Comment by franco999** [comment]
@dmpr0 Sony Xperia ST21a (Tipo) with Android 4.0.4

**Comment by franco999** [comment]
It seems the problem was fixed in version 2.2.0#13172M. In this version no longer it makes me the problem.
