### ISSUE TITLE
network=* tags used for road routes in Australia have undergone changes

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16568]
### Description
network=* tags used for road routes in Australia have undergone changes
This affects the rendering of the shields in OSMAnd
Network tags are now in the format network=AU:(state or territory abbreviation)[:(shield type)]

Details of the network tags now in use:

NATIONAL HIGHWAY (green shield with yellow number) - formerly network=NH
network=AU:NSW:NH
network=AU:NT:NH
network=AU:SA:NH
network=AU:TAS:NH
network=AU:WA:NH

NATIONAL ROUTE (white shield with black number) - formerly network=NR
network=AU:NT:NR
network=AU:QLD:NR
network=AU:WA:NR
network=AU:VIC:ALT_NR (alternative national route)
network=AU:WA:ALT_NR (alternative national route)

STATE ROUTE (blue shield with white number) - formerly network=S
network=AU:NSW:S
network=AU:NT:S
network=AU:QLD:S
network=AU:VIC:S
network=AU:WA:S
network=AU:QLD:ALT_S (alternative state route)
network=AU:WA:ALT_S (alternative state route)

METROAD ROUTE (white hexagonal shield with blue number) - formerly network=MR
network=AU:QLD:MR

TOURIST ROUTE (brown shield with white number) - formerly network=T
network=AU:ACT:T
network=AU:NSW:T
network=AU:QLD:T
network=AU:SA:T
network=AU:VIC:T
network=AU:WA:T

SPECIAL TOURIST ROUTES - Queensland has some tourist routes with the usual tourist shield, but with a picture rather than a route number. The wiki page at https://wiki.openstreetmap.org/wiki/Australian_Tagging_Guidelines/Roads#Routes <https://wiki.openstreetmap.org/wiki/Australian_Tagging_Guidelines/Roads#Routes> has some of these images. These previously did not have
network=AU:QLD:TD:Brisbane_Valley - Brisbane Valley Heritage Trail
network=AU:QLD:TD:Bunya - Great Bunya Tourist Drive
network=AU:QLD:TD:Cobb_Co - Cobb & Co Tourist Drive
network=AU:QLD:TD:MB - Moreton Bay Tourist Drive - ref=Northern/Southern (for the northern and southern sections of this route)
network=AU:QLD:TD:GBR - Great Barrier Reef Tourist Drive
network=AU:QLD:TD:Cane_Cutter - Cane Cutter Way Tourist Drive
network=AU:QLD:TD:Cassowary - Cassowary Tourist Drive
network=AU:QLD:TD:Dinosaur - Dinosaur Way Tourist Drive
network=AU:QLD:TD:Muttaburrasaurus - Muttaburrasaurus Tourist Drive

network=AU:QLD:SSTR - State Strategic Touring Routes in Queensland - these don't have shields - they look similar to alphanumeric route numbers, but with yellow writing on a brown background.

OD ROUTES - Overdimensional - routes for heavy vehicles. I don't know what shields they are in (might have to leave these as shieldless)
network=AU:VIC:OD

OTHER ROUTES (ALPHANUMERIC) (yellow number on a green background) - in the past these did not have network tags.
(N.B. These network tags are also used for some road routes without a ref=* tag.)
network=AU:ACT
network=AU:NSW
network=AU:NT
network=AU:QLD
network=AU:SA
network=AU:TAS
network=AU:VIC
network=AU:WA
network=AU:QLD:ALT (alternative alphanumeric route)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14243mqta, Released: 2023-03-16
4.4.6.7
Done
[OSM](https://www.openstreetmap.org/search?whereami=1&query=-33.16547%2C151.46856#map=18/-33.16547/151.46881) - for example M1

**Comment by dmpr0** [comment]
Will be available for Public use with April map updates.

**Comment by Zirochkabila** [comment]
`-33.16547, 151.46856`

M1

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/229361573-a01cb02b-c187-441b-a207-27f63868f5e0.jpeg"  width="500" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/229361575-799d2780-c43c-4a86-9fbf-10b18e6ee87a.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by xmd5a2** [comment]
@Zirochkabila what's wrong with M1?
https://www.openstreetmap.org/relation/2910577

> OTHER ROUTES (ALPHANUMERIC) (yellow number on a green background) - in the past these did not have network tags.
> (N.B. These network tags are also used for some road routes without a ref=* tag.)
> network=AU:ACT
> network=AU:NSW

**Comment by Zirochkabila** [comment]
@xmd5a2 Everything is fine - @dmpr0 asked to add screenshots (comment above)
