### ISSUE TITLE
renderingAttribute does not works as expected (legacy engine)

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1656]
https://dl.dropboxusercontent.com/u/4624786/osm/default.render.zip
See line 263:
```xml
	<renderingAttribute name="highwayShadowRadius"> <!-- OpenGL engine only for now -->
		<case showAccess="true" additional="motorroad=yes" attrFloatValue="1:1"/>
		<case attrFloatValue="3"/>
	</renderingAttribute>
```
This returns 0 for old engine (except for some highways), but OpenGL engine works correctly.
But if we change renderingAttribute to renderingConstant (uncomment line 267 and comment renderingAttribute):
```xml
<!--	<renderingConstant name="highwayShadowRadius" value="3"/>-->
```
All engines works as expected. Can't figure out how to solve this.

**Comment by vshcherb** [comment]
Did you try attrFloatValue="1" instead of attrFloatValue="1:1". I'm not sure it is supported

**Comment by xmd5a2** [comment]
Problem is with second "case"
