### ISSUE TITLE
Support themed icons (Android 13)

### ISSUE THREAD

**Issue by xmha97** [osmandapp/OsmAnd#16577]
Please add the Android 13 "Themed Icons" feature.

<img src="https://user-images.githubusercontent.com/23485114/222255086-329dbfd1-b1ca-40e1-92a8-44d9b9917034.jpg"  width="300" height="auto"/>

**Comment by dmpr0** [comment]
We support Adaptive icons. We need to add support for themed app icons.
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#user-theming

**Comment by xmha97** [comment]
Thanks. 🙏

**Comment by xmha97** [comment]
> <img width="1119" alt="Screenshot 2023-04-07 at 17 02 36" src="https://user-images.githubusercontent.com/104760013/230621883-c8997c3e-0b9e-48a4-936e-66cb434b36db.png">
> 

Thanks 🙏
Please publish a new version.

**Comment by Zirochkabila** [comment]
@xmha97 Please try to download nightly version https://osmand.net/docs/versions/nightly_versions

**Comment by xmha97** [comment]
> @xmha97 Please try to download nightly version https://osmand.net/docs/versions/nightly_versions

It's nightly version without monochrome icon.
![Screenshot_2023-04-08-17-41-34-893_de.mm20.launcher2.release.jpg](https://user-images.githubusercontent.com/23485114/230725792-87cb56ea-5bc6-45f3-8592-f4d7702d0b20.jpg)

**Comment by Zirochkabila** [comment]
@xmha97 This is information about the application - a standard icon can be used here.
Please add a screenshot where you can see the OsmAnd icon among the list of other applications

**Comment by dmpr0** [comment]
## Review 
- [ ] Themed icon don't applies to Nightly Default build
![Screenshot 2023-04-10 at 15 47 31](https://user-images.githubusercontent.com/9365308/230904109-3e058c8b-3833-4325-b213-0e10994b24db.png)

**Comment by xmha97** [comment]
> ## Review 
> - [ ] Themed icon don't applies to Nightly Default build
> ![Screenshot 2023-04-10 at 15 47 31](https://user-images.githubusercontent.com/9365308/230904109-3e058c8b-3833-4325-b213-0e10994b24db.png)
> 

Ok, thank you for your reply. 🙏

**Comment by xmha97** [comment]
> <img width="894" alt="Screenshot 2023-04-13 at 17 30 58" src="https://user-images.githubusercontent.com/104760013/231792290-07ae7ca6-c77f-417f-b326-a5b3d53a425c.png">
> 

Thanks, now the nightly version supports the monochrome icon.

![IMG_20230413_183500_392.jpg](https://user-images.githubusercontent.com/23485114/231802623-c386f411-be94-4b33-99ee-54b8b5e01d71.jpg)
