### ISSUE TITLE
Angle is not saved in manually rotated (Compass icons misleading)

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#16570]
Yesterday we changed the compass icons:
 - Before that the 2 fixed modes "North is up (fixed)" and "Manually rotated (fixed)" had a similar icon contaiing the letter "N" topped with a red arrow, rotated correctly, while just the "Compass direction" mode aptly had an icon which assimilated a floating compass needle.
- Since yesterday the icon for "Manually rotaded (fixed)" now assimilates a floating compass needle, which  is both misleading and badly distinguishable from the "Compass direction" mode.

**Comment by sonora** [comment]
So why milestone **4.5**, i.e. we let this slip into our upcoming 4.4 release without need?

We only just caused this yesterday. We could easily revert to the previous icon (which was also quite new anyway) until we find a better new one (if we need one at all)?

**Comment by vshcherb** [comment]
@dmpr0 need to investigate what icon fits better so probably 4.4 but depends how much we could do for 1-2 weeks

**Comment by andrzej-gmt** [comment]
I like the feature, where I can change map orientation by pressing compass icon. This has 2 glitches:
* With default settings icon disappears, when orientation changes to "north up". One have to browse menus, to go back.
* Now we get separate "manually rotated" mode, which IMHO is redundant and even misleading at first.

My suggestion is to go back to old 3 modes, when pressing icon and simply allow manual rotation, when mode is "north up". This way users get what they expect, when pressing the icon and know what is happening, when they rotate map themselves. And they will know, why the icon "north up" is rotated.

**Comment by sonora** [comment]
@andrzej-gmt This issue is about zhe icon, really, not the widget.

But to your points
- No need to browse the menus, simply twisting the map with two fingers will do the trick
- True, we do (and always have) by default hidden the North arrow for North-is-up to declutter the screen a bit for the majority of users But you can always go to `Configure map > Compass` and change to `Always visible`.
- We have always had 4 modes, only now a bit more explicit for more clarity.

**Comment by andrzej-gmt** [comment]
Ok, I see. I thought the icon is a result off making 4-th mode explicit.

**Comment by sonora** [comment]
Just to clarify what this issue is about: Below the 4 icons we use before and after:

<table>
 <tr>
  <td></td>
  <td><b>North is up (fixed)</b></td>
  <td><b>Manually rotated (fixed)</b></td>
  <td><b>Movement direction</b></td>
  <td><b>Compass direction</b></td>
 </tr>
 <tr>
  <td><b>Before 2023-03-01</b></td>
  <td><img src="https://user-images.githubusercontent.com/845735/222950295-c021bc78-fbbf-4d27-a4b4-8f2ecc4bac3e.png" width="86" height="86"/> </td>
  <td><img src="https://user-images.githubusercontent.com/845735/222950296-f4869ec4-1a65-4517-8084-20f7e734a16d.png" width="86" height="86"/> </td>
  <td><img src="https://user-images.githubusercontent.com/845735/222950297-8c1cf999-1251-4f1d-9bcf-41d4d1e76e33.png" width="86" height="86"/> </td>
  <td><img src="https://user-images.githubusercontent.com/845735/222950298-5e335fb1-fee1-469f-97c5-c962bd83f371.png" width="86" height="86"/> </td>
 </tr>
 <tr>
  <td><b>After</b></td>
  <td><img src="https://user-images.githubusercontent.com/845735/222950306-e9616150-b83c-400e-b368-59e7efe5ae1f.png" width="86" height="86"/> </td>
  <td><img src="https://user-images.githubusercontent.com/845735/222950309-e7f16d02-f49f-4d2f-9137-210f22a8bfe4.png" width="86" height="86"/> </td>
  <td><img src="https://user-images.githubusercontent.com/845735/222950311-aab089d7-06ab-4eef-9314-a4c464aa19d4.png" width="86" height="86"/> </td>
  <td><img src="https://user-images.githubusercontent.com/845735/222950313-acd7b4ba-3e77-4895-8194-d51f712b804f.png" width="86" height="86"/> </td>
 </tr>
</table> 


I think the **Before** version for "**Manually rotated (fixed)**" with the "**N**" was better, or maybe we should use this pattern: 

![sugg](https://user-images.githubusercontent.com/845735/222950724-6478e71c-34d2-4a33-97b5-a1dfcc458f58.png)

**Comment by vshcherb** [comment]
While taping single time angle is not saved, so I can't have preselected preferred angle.

**Comment by sonora** [comment]
> While taping single time angle is not saved, so I can't have preselected preferred angle.

@vshcherb Do you mean between app sessions, right? Actual rotation is a variable now, so we can either 
- create a dedicated variable remembering the manual rotation between orientation mode switches,
- or put it in OsmandSettings to get it remembered between app sessions.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14239mqta, Released: 2023-03-15
Done
