### ISSUE TITLE
Add turn camera parallel road

### ISSUE THREAD

**Issue by gtrus21** [osmandapp/OsmAnd#16579]
Auto Translation: Please add an alignment mode parallel to the road to which the location point is attached.  When navigating a straight road with heading alignment enabled, the location arrow rotates left and right intermittently.  We need a mode (working only when snap to road is enabled) that would align the camera parallel to the section of the road on which the user is located.  Those.  this section will look straight up

Native language: Прошу добавить режим выравнивания параллельно дороге, к которой привязана точка местоположения. При навигации по прямой дороге с включенным режимом выравнивания по направлению движения стрелку местоположения периодически поворачивает влево и вправо. Нужен режим (работающий только когда включена привязка к дороге), который бы выравнивал камеру параллельно участку дороги, на которой находится пользователь. Т.е. этот участок будет смотреть строго вверх

**Comment by gtrus21** [comment]
![Screenshot_2023-03-02-08-34-32-662_net osmand](https://user-images.githubusercontent.com/69676792/222340904-462edf95-f3d4-46c2-9f55-ededb0fce3cc.jpg)

**Comment by gtrus21** [comment]
Когда пользователь "слетает" с привязки дороги, камера _временно_ должна перейти в режим по направлению движения

**Comment by Zirochkabila** [comment]
@gtrus21 Please change the language in the issue to English.

**Comment by vshcherb** [comment]
You can use experimental setting - Navigation Settings -> Map during navigation -> Approximate bearing.
