### ISSUE TITLE
Reminder to reset 'waitAnnouncedOffRoute'

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#16571]
Carry-over from https://github.com/osmandapp/OsmAnd/issues/16315#issuecomment-1430492885: Reminder to reset `waitAnnouncedOffRoute`.

My current thinking is we need to do it in 3 places:
 - [ ] **(1)** When the user starts a new turn-by-turn navigation.
 - [ ] **(2)** Here: https://github.com/osmandapp/OsmAnd/blob/1c6d058004acba0deba7e1d46eb3165762bb174c/OsmAnd/src/net/osmand/plus/routing/VoiceRouter.java#L240
 - [ ] **(3)** Probably when the users follows a route turn correctly, i.e. somewhere in `updateStatus()`.

**Comment by sonora** [comment]
From what I see, this should be the fix: https://github.com/osmandapp/OsmAnd/pull/16598

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14222mqta, Released: 2023-03-07
4.4.6.4
Done

**Comment by vshcherb** [comment]
Constant wait off the route for pedestrian route

**Comment by sonora** [comment]
Increment only for a non-walking navigation, so for walking you would invariably hear the prompt every 60 seconds, you mean?

**Comment by Nine-Tailed** [comment]
> Increment only for a non-walking navigation, so for walking you would invariably hear the prompt every 60 seconds, you mean?
Today, during pedestrian navigation, I had a bug several times when the notification that I deviated from the route and returned to the route played non-stop.
at the same time, sometimes deviations from the route did not exceed 5 m at all, but the alerts went one after another.
Below are two links to the video, the only notification there is in Russian.
Video in telegram chat ruosmand:
https://t.me/ruosmand/119325
https://t.me/ruosmand/119331

**Comment by sonora** [comment]
I think the issue may be here: https://github.com/osmandapp/OsmAnd/blob/667aa10f6ea8dfb991acd079cae81157cca41a65/OsmAnd/src/net/osmand/plus/routing/data/AnnounceTimeDistances.java#L117-L118

Perhaps my patch above has revealed a threshold of just 20m for a pedestrian use case to be too ambitious. If byv GPS inaccuracy or whatever your posiion is discovered some 20m off the route, that effect may result. Need to think abbout how to mitigate this, could either be to not immediately reset the wait period (before the fix we never reset, which was clearly a bug but had masked this), or increase the OFF_ROUTE_DISTANCE.

**Comment by sonora** [comment]
@vshcherb Do you understand why we call `announceBackOnRoute() `here, is this correct?
https://github.com/osmandapp/OsmAnd/blob/c29e28491add9040000d87a1376d816bb1641a9b/OsmAnd/src/net/osmand/plus/routing/RouteRecalculationHelper.java#L127
There seems no check for any distance to anything, it seems..

And that now resets the wait to announce "off route" to zero, probably creating the loop @Nine-Tailed observes. Of course we could just not reset the off-route-wait in that case, but I do not understand the logic yet of when we intend to announce back-on-route...

**Comment by vshcherb** [comment]
This check is probably related that if calculation being stopped that means you're back to the route but that's weird

**Comment by sonora** [comment]
Yes, exactly, somehow the assumption is that if a route calculation has stopped, you are assumed to be back on the route. Seems the _only_ place where we call `announceBackOnRoute()`.

I think we should find a better condition when to announce "back on the route". My current thinking is it should instead be called from `announceOffRoute(double dist)` like this:

```
	public void announceOffRoute(double dist) {
		if (dist > atd.getOffRouteDistance()) {
			(...)
		} elseif (announceBackOnRoute && (dist < 0.5 * atd.getOffRouteDistance())){
			announceBackOnRoute();
		}
	}
```
If you don't see an obvious flaw with this, I can try to build this and test...

**Comment by sonora** [comment]
Ok, I got it: The loop is caused by `announceOffRoute(distOrth)` and `stopCalculationIfParamsNotChanged()` being called immediately behind each other in `RoutingHelper.java`,and the latter one causing "back on route" without much additional checking.

So this https://github.com/osmandapp/OsmAnd/pull/16693 is a viable fix, and I have just tested by walking around the neighborhood, it seems ok. Could @Nine-Tailed please also test?

**Comment by Nine-Tailed** [comment]
I can test tonight if a build with these fixes is available

**Comment by Nine-Tailed** [comment]
I tested it this morning on my way to work, there was no more looping of voice prompts.  but for some reason, when I reached the finish line, Osmand did not get ahead of it and continued navigating further.
![Screenshot_2023-03-15-07-24-00-943_net.osmand.plus.jpg](https://user-images.githubusercontent.com/12549744/225278375-84e0f5b5-2e91-4b75-ac37-13bbf9b855dd.jpg)

**Comment by Nine-Tailed** [comment]
In the evening, on the way home, the navigation worked fine, even though I deviated to the store for 10 minutes.

**Comment by sonora** [comment]
Yes, I have also tested and concur we have a decent fix, both for the original issue as well as for the subsequently surfacing _offRoute/onRoute_ loop.

 The "backOnRoute" condition could perhaps be finetuned some, particularly for cars, but then it is a rather seldom heard prompt, in many instances the route will have re-calculated before that prompt even plays in practice.

Let me close this and copy @vshcherb and @Zirochkabila because I am unsure about what needs to be done to advance this now to "Testing" or whatever the proper next stage is in our latest operating model.  :wink: I will, in any case, monitor this issue should something still come up.

Regarding @Nine-Tailed 's new observation "_Osmand ... continued navigating further_": I believe that may be #16594, and I currently have no indication it is related to this issue here.

**Comment by Zirochkabila** [comment]
So far, we haven't noticed any cyclic prompts.
But, there is a misunderstanding with the announcement of arrival at the destination - as mentioned above @sonora @Nine-Tailed
