### ISSUE TITLE
Solid color of track does not update

### ISSUE THREAD

**Issue by Velomeloman** [osmandapp/OsmAnd#16584]
### Description
Solid color of track updates only after restart or changing width.

### Steps to reproduce
Track - Appearance - change solid color - Apply. Nothing happens.
Track - Appearance - change solid color - change width or restart OsmAnd. Color updates. 

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14214mqta, released: 2023-03-03

**Comment by Zirochkabila** [comment]
@Velomeloman Duplicate https://github.com/osmandapp/OsmAnd/issues/16509 ?

**Comment by Velomeloman** [comment]
Yes. Badly searched.

**Comment by vshcherb** [comment]
- [ ] Track color can changed only after changing the line thickness, showing/hiding the track on the map, and selecting Altitude
`Select track > Appearance > Chose color`
[logcat (71).log](https://github.com/osmandapp/OsmAnd/files/10823147/logcat.71.log)

https://user-images.githubusercontent.com/104760013/221156279-c775d0f2-4058-483f-8186-e0ee5e04e03a.mp4

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14198mqta, Released: 2023-02-24
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14236mqta, Released: 2023-03-14
Done
