### ISSUE TITLE
GPX tooltip extra field display

### ISSUE THREAD

**Issue by PinkDuck** [osmandapp/Osmand#1658]
It would be good if a GPX wpt XML file could have its cmt element value displayed in the pop-up tooltip in addition to the name when waypoints are shown as a layer in OsmAnd.

It would also be nice if the sym XML element value could be used to set the waypoint icon displayed in OsmAnd, possibly just an inner symbol of the marker from the available set of symbols used on the maps.

For my particular case, I am adding a layer of postbox points to survey. It would be good to be able to mix data sets together into a single layer rather than switch between and rely on context to know the data type of interest.

**Comment by vshcherb** [comment]
I think we can show it similar to description or may be instead of "desc", I guess it could solve original issue.

**Comment by sonora** [comment]
- Regarding  `cmt`: I think I have implemented that some months ago.
- Regarding the symbols: You can create categories for your favorites, and set the icon color per favotite I think it covers your use case sufficiently?

**Comment by fedjo** [comment]
>     * Regarding  `cmt`: I think I have implemented that some months ago.
> 
>     * Regarding the symbols: You can create categories for your favorites, and set the icon color per favorite I think it covers your use case sufficiently?

A problem that arises when not parsing <sym> elements is the compatibility problems?

Eg: What happens if I want to Import points from a GPX exported from another software that uses maps (Garmin) ?

A solution could be to convert the gpx to another gpx. But I still haven't found any useful convertors

**Comment by pebogufi** [comment]
For convertors have a look at 
https://www.gpsbabel.org/
