### ISSUE TITLE
Remove "Add action" from "Quick action"

### ISSUE THREAD

**Issue by andrzej-gmt** [osmandapp/OsmAnd#16593]
# 🚀 feature request

### Description

I would like to remove button "add action" from quick action popup. I don't need this button but it wastes some space on screen.

### Describe the solution you'd like

Could you please treat "add action" as any other action and allow user to add/move/remove it? You can set default configuration with this button already active, if you think it could be helpful for new users.

### Describe alternatives you've considered

Live with it?

**Comment by Zirochkabila** [comment]
@andrzej-gmt This button allows you to add another function - making it faster and easier to use
