### ISSUE TITLE
Wechat location sharing is not working with Osmand

### ISSUE THREAD

**Issue by postadelmaga** [osmandapp/Osmand#1659]
If somebody send me a location on wechat I usually get option to open it with my map application ( gmap and baidu map ) but Osmand is not present in those options.

**Comment by RicoZ-OSM** [comment]
@postadelmaga : Intent Intercept can get you the details like which intent and other parameters should be matched. 

https://f-droid.org/repository/browse/?fdfilter=intent+intercept&fdid=uk.co.ashtonbrsc.android.intentintercept

**Comment by postadelmaga** [comment]
@RicoZ-OSM  Thanks, I have installed Intent Intercept but I'm not sure how to use it:
- I enabled it
- I open the location inside wechat and I get prompted to the application selection as usual ... nothing special happens 

I probably miss someything ... can you give me some hint ?

**Comment by RicoZ-OSM** [comment]
you are on the right track - now IntentIntercept should be one of the choices offered in the application selection. Possibly only offered in a submenu like "more apps" or similar. So select it (just once) and it should display you the full details of the invocation, copy&paste/email them and post here.

**Comment by postadelmaga** [comment]
Unfortunately even if intercept is activated I only have 2 options baidumap/gmap ... 
At this point I suspect  these options are hard coded in wechat, in that scenario there is nothing to do here.

Feel free to close this task if there is nothing more I can try

**Comment by GaidamakUA** [comment]
Intents are hardcoded in app. Nothing we can do.

**Comment by postadelmaga** [comment]
Sorry for posting on a closed bug.

I just notice the last versions of OsmAnd is presented as option in wechat now ...
it looks that wechat try to share the url in the form of maps.google.com url (those urls contains gps coordinates ) it will be nice if OsmAnd could parse the url and extract the coordinates.

**Comment by vshcherb** [comment]
Do you have any idea which URL it sends?

**Comment by postadelmaga** [comment]
This is an example
http://maps.google.com/maps?f=d&saddr=30.597153,104.165665&daddr=32.426788,105.823158&hl=en

**Comment by vshcherb** [comment]
Added a test though could not reproduce it via test

**Comment by vshcherb** [comment]
These links are opening fine on latest OsmAnd, do they cause crash on latest version you have?
2.4 release will be around next week
