### ISSUE TITLE
Icons in "Edit Favourite" not all visible in Portrait view (on Google Pixel 6)

### ISSUE THREAD

**Issue by Boothy99** [osmandapp/OsmAnd#16599]
**Description -**
On editing a Favourite, the full list of icons are not viewable (in a number of lists) on Google Pixel 6.

**Steps to reproduce -**
Select a Favourite icon / choose "Edit Favourite".
In "Select icon", scroll to "Travel" (or any in the affected list, below).
Look for (eg) the Waterfall icon. Waterfall icon is not visible in Portrait view (the last icon is the cave image).
Flip the phone to Landscape and re-select Travel group. The full list of icons can now be seen. 
See Screenshots, below.

**Actual result -** 
This issue is seen on my Google Pixel 6 but not on my older Xiaomi Mi 9T or Samsung Galaxy Tab S4 tablet. The lists do not have to be long ones for the last icons to be omitted ....

Lists of icons affected (incomplete view) are -
Special, Transport, Service, Symbols, Sport, Travel, Nautical, Industrial.

Lists of icons not affected (complete view) are -
Amenity, Emergency, Education

OsmAnd Version: OsmAnd+ 4.4.1, release 2023-03-03 (on all devices).
Android version: 13 (Google Pixel 6) / 11 (Xiaomi Mi 9T) / 10 (Samsung Galaxy Tab S4)
Device model: Google Pixel 6

**TRUNCATED LIST ON GOOGLE PIXEL 6 IN PORTRAIT........**

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/13983995/222956428-00b98310-f975-4607-ae2b-6dedd76db79b.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

**FULL LIST ON GOOGLE PIXEL 6 IN LANDSCAPE.......**

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/13983995/222956429-b5032793-45fb-4e91-8254-c9d81a9c841d.png"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Boothy99** [comment]
In Portrait view, the list is not scrollable.
OsmAnd+ settings have text zoom at 100%
Google Pixel 6 text is set to Medium.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14233mqta, Released: 2023-03-12
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/224557559-f1bcf594-ab20-4f88-9403-f4bc473c6e72.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/224557561-00565609-95b1-4764-ae7c-1f5b8dd9d829.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Boothy99** [comment]
Thanks Zirochkabila
I see I'm not alone then 👍

**Comment by DragNet2** [comment]
I confirm this issue on Galaxy Note 9 (Android 10).
For example I don't see the "X" icon in the portret view, however it does exist in landscape.

**Comment by Boothy99** [comment]
Thanks @DragNet2 for confirmation and @vshcherb for assigning the issue.

**Comment by Boothy99** [comment]
Thanks @Chumva 👍👌

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14254mqta, Released: 2023-03-20
Done
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/226411805-94a640ca-260d-4935-9064-6078f54b2d65.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Boothy99** [comment]
👍👌
Excellent !! No update for mine just yet, but I'll look out ta.

**Comment by Zirochkabila** [comment]
@Boothy99 Try installing the night version https://osmand.net/docs/versions/nightly_versions

**Comment by Boothy99** [comment]
All sorted on OsmAnd+ 4.4.4 👍👌
Thanks
