### ISSUE TITLE
Android Auto:  no GPS signal when using background phone

### ISSUE THREAD

**Issue by mmacura311** [osmandapp/OsmAnd#16607]
### Description
I was happy to see 4.4.1 to appear as 4.3.x was not usable for nagivation in the car (10-15s lags between map updates), but I'm sorry to report that it is even worse then it was.
in 4.4.1 osmand takes ages to get gps fix and when driving it often stays totally out of sync with my current position (over minute refresh delay) and also frequently complains that GPS signal was lost. What is also weird that on my phone the location status icon is not turned on on the tray, but is blinking very fast, like the app have some problem reading the gps or something.
I tried running the "gps lock" app on background to force always-on gps, but this have no effect on the osmand itself.
I think my setup is OK in general (phone, cable) as when I switch to different app on the car display, it works right away and updates the map every second.

### Steps to reproduce
1) connect phone to car via usb
2) run osm and
3) search for addres/poi
4) try to drive

### Actual result
map is not updated with current location, showing symptoms described above

### Expected result
map view is constantly updated and app is providing navigation directions

### Your Environment
OsmAnd Version: 4.4.1
Android/iOS version: 12
Device model: Fairphone 4
android-auto version: 8.8.630424-release

**Comment by wolfsolver** [comment]
Hi all, I have similar issue on 4.3.12, seems working by keep smartphone wake and app open on smartphone. 
With this workaround navigation is ok. But if screen goes off after a while GPS lost.

**Comment by Zirochkabila** [comment]
@wolfsolver @mmacura311 What permissions you have set for using GPS data: While using the app or Only this time?
Which Location source do you use Google Play Services or Android API?
Are you using device/battery optimization?

**Comment by mmacura311** [comment]
HI @Zirochkabila my seeting for osmand are:
Location: while using the app + allow accurate location
battery use: optimization enabled
location source:
  I'm not sure what are you asking here. on my phone under location there are 7 options (vaguely translated):
  History of location in Google : disabled
  Accuracy of google location: enabled
  sharing location google: disabled
  emergency location service: enabled
  earthquake warnings: enabled
  wifi searching: disabled
  bluetooth searching: disabled

I will try to drive today with battery optimization disabled (unlimited) and see if that makes any difference.

**Comment by wolfsolver** [comment]
Hi! OsmAnd is set "While using the app', GPS is connected to Google play service, no battery ottimozation (or better standard android 12)

Today I perform a deep test, here some result:
- with app in foreground and screen off
  - using Google play service as GPS source has the issue (GPS lost/GPS connect many times)
  - using android api has less disconnect/reconnect GPS (but still present)
- with app in background and screen off GPS lost for more time
- no significant change using cable or WiFi connection to car
- seems that using in foreground with screen on different all that use GPS (like bussola) no issue

Hope this can help.

**Comment by mmacura311** [comment]
ok I tried again with the battery optimization disabled(unlimited) and it have no effect, I was driving for some 10 minutes and osmand did not even have initial gps fix.

**Comment by wolfsolver** [comment]
Hi all, a quick update.
In my previous comment I use 4.3.13 and GPS work fine with Android API setting (not with play service) as I wrote before.

In beta version 4.4.1 I had the same issue of @mmacura311 

It not relevant using Android API or play service. GPS not working if app is not in foreground.

**Comment by wolfsolver** [comment]
Hi all, I'd like to share an important info (and different behaviour from OsmAnd and OsmAnd+)

* OsmAnd v 4.3.12

  * navigation work fine also with app in background using Android API as source gps. "OsmAnd android auto is running" notification is present (see picture below)
   * navigation with Google play service does not work


* OsmAnd+ v 4.4.1

  * navigation in background does not work (both with Google service or Android API)
  * no notification that app running.
as soon app goes in background, all thead are stopped


**Image**

![Screenshot_20230313-182837-137.png](https://user-images.githubusercontent.com/3205448/224780898-af3b0739-0c24-4704-bde2-45e775260051.png)

**Comment by mmacura311** [comment]
so I drove for a few hours and confirm above from @wolfsolver . When the osmand app was in foreground on the phone, it worked OKish (sometimes there were some lags, but that is probably different bug). If app moved to background almost immediately the navigation loses position tracking.
I was using 4.4.2

**Comment by wolfsolver** [comment]
Good news!
Now OsmAnd+ has same behaviour and same issue.


OsmAnd v 4.3.12, OSMAnd+ 4.4.3
On AA 9.1.631024-release

* navigation work fine also with app in foreground or background using Android API as source gps. "OsmAnd android auto is running" notification is present
* navigation with play service as GPS source signal lost (and notification is still present)

So we have a solution: using Android API as source gps :)

**Comment by wolfsolver** [comment]
Sorry... I made a mistake:(

In my previous post I have recording track active .. and works in background (osmand on AA follow GPS position) as soon I stop the recording osmand on AA stop following GPS 

So issue is still present, but maybe using same technique for tracking can resolve the issue.

**Comment by mitohund** [comment]
I think this might be the same issue as #16111.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14251mqta, Released: 2023-03-18
AA stops updating the GPS position if the device is locked or OsmAnd is running in the background (Google Play Services, Android API - the result is the same).

- [ ] Also, there was a crash (rare): Connect AA > Grant permission to determine the location > Menu > Settings > Location source > Android API > Close OsmAnd > Open (AA does not respond) > Close OsmAnd > Disconnect AA > Open OsmAnd
[exception (39).log](https://github.com/osmandapp/OsmAnd/files/11008380/exception.39.log)

**Comment by mmacura311** [comment]
ok I only just now realized that using android api or google play services is option in OsmAnd.
I had it on google services the whole time, if that is of any value.

**Comment by PhotoKevin** [comment]
I've noticed that sometimes, when it seems like there's no GPS, it's really just very far behind. I payed close attention this morning on my way to work. 

I leave my house and got 0.25 miles east to a stop sign. At the stop sign, the AA display shows I've went only part of the way.
Then I turn north go another 0.75 miles. As I do this, I see the marker move in fits and starts to the east. All the way to where I turned. Then it starts going north.
I then take a roundabout and get on a freeway to go east.  I keep watching the display as it continues to show me going north. By the time I'm about three miles away, the display shows me getting to the roundabout, taking the partial circle and then the entrance ramp. The entire time it has perfectly shown what I did, it's just getting further and further behind.

I don't know if this is useful information.

**Comment by wolfsolver** [comment]
Just tested on 4.4.4 with GPS source as play service in navigation mode and work fine with app in background and screen off.

I will test later with API as source and without navigation mode.

**Comment by PhotoKevin** [comment]
@mmacura311 Oops. On the one hand, you're right. I'm on the 4.3.12 version. But. It was working perfectly until about 3-4 weeks ago, about the same time as this issue was entered. No lags, all perfect. Now it's unusable. Hence my thinking it was the release the original poster was on. While it often lags now, it also will just be stuck. Either way, if  I open it on my phone and bring it to the foreground it will jump the correct position.

Come to think of it, that's also the same time frame as when the Android Auto in my car updated to the version with split screens and such.

**Comment by wolfsolver** [comment]
Still not close.
Just tested on 4.4.5 with GPS source both as play service and API, both in navigation mode and drive mode.
Better then before, but not the best.

GPS position is updated occasionally. GPS icon "blink"

Here a video, look upper right to gps icon

https://photos.app.goo.gl/L331ZaMuAVMSudSV9

**Comment by Zirochkabila** [comment]
@wolfsolver On the video AA 9.1.631044-release 22.03

**Comment by olifoss** [comment]
Works again with OsmAnd 4.4.5 and Android Auto  9.1.631044 on Android 13 😁.

I'm grateful for your quick fix, I love to navigate with OsmAnd in my car. Deactivated Google Maps.

**Comment by wolfsolver** [comment]
> I'm on AA 9.2.631214-release. on with AA are you?

I just noticed that same issue occurs today using Waze. So maybe is a issue not related to osmand but to beta release of android auto. I will waiting for new AA release and come back to update you

**Comment by wolfsolver** [comment]
OsmAnd 4.4.6
AA 9.2.631214

Navigation in background works. Some lags in car movement occurs sometimes.
