### ISSUE TITLE
README: broken link: donate (403 Forbidden)

### ISSUE THREAD

**Issue by WofWca** [osmandapp/OsmAnd#16600]
### Description

https://github.com/osmandapp/OsmAnd/blob/daf64e7eae90158cc7f7b5491af049ef917f1bd2/README.md?plain=1#L86

**Comment by vshcherb** [comment]
@Zirochkabila here https://github.com/osmandapp/OsmAnd/blob/master/README.md#contribute-to-osmand

**Comment by WofWca** [comment]
The one that's on the 86th line of README. This one: https://osmand.net/help-online#buy_app

**Comment by WofWca** [comment]
(so it's not in the actual app, sorry)

**Comment by DmitryAlexei** [comment]
https://github.com/osmandapp/OsmAnd/blob/master/README.md#contribute-to-osmand

**Comment by sonora** [comment]
@vshcherb Actually, it looks like the link which was broken was about the possibility to make donations, not contributions? Are there no ways anymore to make donations?

**Comment by vshcherb** [comment]
I think no, cause company doesn't support direct payments from people, so it only works through aggregators like Google / Amazon / Apple
