### ISSUE TITLE
Old building geometry shows on top of new one

### ISSUE THREAD

**Issue by lucumon** [osmandapp/OsmAnd#16602]
After updating some buildings in osm, Osmand Live shows new and old geometry superposed.
![Screenshot_2023-03-05-19-48-55-29_54166e5c6f8ad9491c65e2397c495c92](https://user-images.githubusercontent.com/24960275/222979940-c6d82996-3512-4969-b129-1f883b68fb9b.jpg)
![Screenshot_2023-03-05-19-49-03-71_54166e5c6f8ad9491c65e2397c495c92](https://user-images.githubusercontent.com/24960275/222979944-72084f06-37ce-4cb2-b538-e9ea37f3c92a.jpg)
Both captures were taken on "Negreira", 42.90976° N, 8.73609° W.
Osmand Live for Galicia updated hourly, last update 5th march 2023 at 19:40.

**Comment by mikehgentry** [comment]
Duplicate of #14920

**Comment by lucumon** [comment]
Sorry, closing.
