### ISSUE TITLE
Arabic missing strings

### ISSUE THREAD

**Issue by abdullahO2** [osmandapp/OsmAnd#16604]
### Description
There are some Arabic strings on the weblate, but they don't appear correctly on the app:
![image](https://user-images.githubusercontent.com/61907628/223010812-7bdcba4f-9790-436a-a40d-e5c05ca25090.png)

"Import/export"
https://hosted.weblate.org/translate/osmand/main/ar/?q=export&sort_by=-priority%2Cposition&offset=1
"Export to file"
https://hosted.weblate.org/translate/osmand/main/ar/?q=export&sort_by=-priority%2Cposition&offset=2

### Your Environment
OsmAnd Version: Android 4.3.12 
Android/iOS version: 13
Device model: pixel 6

**Comment by vshcherb** [comment]
Weblate was not merging, should be fine tomorrow
