### ISSUE TITLE
Sharing location is not working as expected

### ISSUE THREAD

**Issue by postadelmaga** [osmandapp/Osmand#1660]
If I share a location I expect that this can be open at least with Osmand on another phone with it installed ... at the moment this is not possible.

One solution would be some place where I can past the `geo:Lat,Loni so that it easy to open it. (even better if you can monitor the clipboard and notify the user if a uri if found )

**Comment by breversa** [comment]
Agreed : it is rather weird (and quite unimpressive when presenting OsmAnd to a newcomer) that OsmAnd cannot read back its own location shares… :-S

**Comment by vshcherb** [comment]
Sending a message reads location fine. Second is opening in browser and in application (both android and ios)

Coordinates: geo:52.34167,4.8679733?z=14
http://osmand.net/go?lat=52.34167&lon=4.8679733&z=14

**Comment by vshcherb** [comment]
Please specify more information in case if it is different

**Comment by postadelmaga** [comment]
Sharing Location present 4 options:
- Message
- Clipboard
- geo
- Qr-Code

- Message/Clipboard produces the same output ( like the example @vshcherb shared ):
As you said works it would be better if, at least the option 'message' produce an output that once clicked the user is prompted for the map application to use for read it. ( honestly I'm not sure this is possible )

- Geo -> if I click this option my phone ask me to open it either with osm or other map application ( that would be result expected if a user click on an location I shared with him, see above )
The purpose of this option is not very clear ... anyway it is nice to have because let me easly open the same location in a different app

- Qr-Code: nice to have but It would be nice if osm have the option to scan qr-code
