### ISSUE TITLE
OsmAnd with Android Auto in coolwalk mode

### ISSUE THREAD

**Issue by wolfsolver** [osmandapp/OsmAnd#16612]
### Description
I was surprised to see that OSMAnd is coolwalk compatible in android auto 
Unfortunately the screen is only cuted on left side without re-center (see below)

### Steps to reproduce
Open android auto, select OsmAnd, set destination (optionally), set coolwalk mode

### Actual result
Android auto normal scren
![IMG_20230306_083045439_HDR.jpg](https://user-images.githubusercontent.com/3205448/223181791-b38087e8-5080-4fbb-91e7-ef5f3f914b0f.jpg)

Android auto coolwalk screen
![IMG_20230306_083053596_HDR.jpg](https://user-images.githubusercontent.com/3205448/223181914-8e0439a6-236f-4941-ae59-fc959af89622.jpg)

### Expected result
Espected screen in coolwalk
![IMG_20230306_083105730_HDR.jpg](https://user-images.githubusercontent.com/3205448/223182052-9084e429-ee57-451d-8141-9524c0adb35f.jpg)

Last screen is "sample" (I center maps manually)

### Your Environment
OsmAnd Version: 4.3.12
Android: 12
Device model: moto g100 / volkswagen Tiguan
Android Auto: 9.0.630824

**Comment by Zirochkabila** [comment]
@wolfsolver Duplicate https://github.com/osmandapp/OsmAnd/issues/16456#issuecomment-1429773365 ?

**Comment by wolfsolver** [comment]
You are right! I search for similar issue, but missing it. Thanks.

You can close this as duplicate. I will follow the original one.

By the way: great job! Amazing app!
