### ISSUE TITLE
Regression: Obsolete 'Import' duplication of GPX files

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#16614]
Looks we recreated #9908 again somehow. When (to open aGPX file in OsmAnd) in a system file manager app, either
- I tap on a GPX file in a subfolder of OsmAnd's track folder,
- or on a GPX file elsewhere, of which an exact copy (also with the same name) is already present in a subfolder of OsmAnd's track folder,

OsmAnd creates a new, obsolete copy of the file in folder tracks/import.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14230mqta, Released: 2023-03-11
Files > Open GPX in OsmAnd > Move GPX from Import Folder to Tracks folder > Files > Open the same GPX > The same track is added to the Import folder

**Comment by vshcherb** [comment]
I'm not sure if it's possible to understand if track was imported from the osmand folder or another folder.
@Chumva

**Comment by nazar-kutz** [comment]
**Fix PR**
* https://github.com/osmandapp/OsmAnd/pull/16736

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14254mqta, Released: 2023-03-20
Still present

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/226415284-dfd0e941-d6fc-48c1-b104-270783b4b7b3.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by nazar-kutz** [comment]
The mentioned problem https://github.com/osmandapp/OsmAnd/issues/16614#issuecomment-1476621267 is actual only for one track, the comment will be below.

**Comment by vshcherb** [comment]
We need to display dialog to replace or not replace file

**Comment by dmpr0** [comment]
## Review
Tested on Android 13.
- [ ]  Toast show "null is imported" after Replace is selected.
<img src="https://user-images.githubusercontent.com/9365308/235451007-12daca4a-fc2a-4553-8c33-4bc94b9651d5.png"  width="300" height="auto"/>

**Comment by Zirochkabila** [comment]
Android 12 - it works
@dmpr0 please make retest on Android 13 (AS - can't import track)

**Comment by sonora** [comment]
Perhaps #17212 is related.

**Comment by dmpr0** [comment]
## Review
- [ ]  Don't change number in file name if it was not added by OsmAnd. Example after importing file with name "Day 3.gpx" and taping Keep both, OsmAnd import duplicate with the name "Day 4.gpx", should be something like "Day 3 (2).gpx"
