### ISSUE TITLE
Poor search results for natural gas filling stations/Schlechte Suchergebnisse nach Erdgastankstellen

### ISSUE THREAD

**Issue by icke68746** [osmandapp/OsmAnd#16615]
OSMAND 4.3.4
Android: 9
If you search for natural gas filling stations in the app, only natural gas filling stations far away (> 80km) are found. A search in the map showed that the app probably searches for the word "natural gas filling station" (name=natural gas filling station), and not for "fuel:cng=yes".
ORIGINAL (übersetzt mit deepl.com)
Sucht man in der App nach Erdgastankstellen, werden nur weit (> 80km) entfernte Erdgastankstellen gefunden. Eine Recherche in der Karte ergab, dass die App wohl nach dem Wort "Erdgastankstelle" (name=Erdgastankstelle) sucht, und nicht nach "fuel:cng=yes".

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14233mqta, Released: 2023-03-12
@icke68746 Try to update the app, maps and send your results
[OSM](https://www.openstreetmap.org/way/828126287)

https://user-images.githubusercontent.com/104760013/224559243-1490cf76-8586-48b9-a668-0c6d36cca466.mp4
