### ISSUE TITLE
Wrong font is used in map rendering engine version 2

### ISSUE THREAD

**Issue by yakitama** [osmandapp/OsmAnd#16617]
### Description
The downloaded "Map fonts" are not used when rendering engine version 2.
This problem does not occur when I use version 1 of the rendering engine.

### Steps to reproduce
- Map rendering engine in OsmAnd settings is set to "Version 2 (OpenGL)".
- Download "Map fonts". I'm Japanese, so I download "NotoSans Japanese".
- Download "Standard map" I want to use. For example, Asia -> Japan -> Kinki region.
- Open map.

### Actual result
- Wrong font are used.

### Expected result
- I think "NotoSans Japanese" should be used for the map font.

### Your Environment
OsmAnd Version: 4.3.8 (F-Droid)
Android/~~iOS~~ version: Android 13, 2023-02-05 security patch installed
Device model: Pixel 6 Pro

**Comment by dmpr0** [comment]
Example,  **き**(ki) hiragana character https://fonts.google.com/noto/specimen/Noto+Sans+JP?preview.text=%E3%81%8D&preview.text_type=custom. In NotoSans bottom part of symbol is dettached.


<table style="width:100%">
  <tr>
    <th>Version 1</th>
    <th>Version 2</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/223410181-3ae83b2e-1fef-4d70-bacb-0ddfd5b50ea6.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/223410173-cfaa6a3f-8abc-4ad1-8678-046291c85f06.png"  width="300" height="auto"/> </td>
  </tr>
</table>   



<table style="width:100%">
  <tr>
    <th colspan=2>Version 1</th>
  </tr>
  <tr>
    <th>Default</th>
    <th>NotoSans JP</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/223409551-7903e9a3-5548-4f37-90b7-f94b5c6e68bb.png"  width="400" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/223409537-256537b6-56f4-4f0d-afee-eac4aea2a4d6.png"  width="400" height="auto"/> </td>
  </tr>
</table>   

<table style="width:100%">
  <tr>
    <th colspan=2>Version 2</th>
  </tr>
  <tr>
    <th>Default</th>
    <th>NotoSans JP</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/223409542-e73ab721-9ec3-4326-b327-98496ebbf3a7.png"  width="400" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/223409545-855d8dd2-76d6-4fdf-b0ef-ad73a6ca8996.png"  width="400" height="auto"/> </td>
  </tr>
</table>

**Comment by ivanPyrohivskyi** [comment]
Check first iOS

**Comment by dmpr0** [comment]
<table style="width:100%">
  <tr>
    <th>Default</th>
    <th>NotoSans JP</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/230597475-507f2f31-dd17-46ec-944a-e70646934322.jpeg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/230597478-f0a85061-92bb-4fce-9b46-843526620662.jpeg"  width="300" height="auto"/> </td>
  </tr>
</table>
