### ISSUE TITLE
Fix text color or background for dark theme and strings not yet translated

### ISSUE THREAD

**Issue by franco999** [osmandapp/Osmand#1661]
Fix text color or background for dark theme, because it is not shown or displayed wrong.

![1](https://cloud.githubusercontent.com/assets/12088580/9706823/9f5bb63a-54c9-11e5-8e40-531bc7d25385.png) ![2](https://cloud.githubusercontent.com/assets/12088580/9706824/9f6b7ba6-54c9-11e5-9c77-92b8317379c4.png)
![3](https://cloud.githubusercontent.com/assets/12088580/9706825/9f78b0c8-54c9-11e5-97e8-ff436d89f791.png) ![4](https://cloud.githubusercontent.com/assets/12088580/9706826/9f8706aa-54c9-11e5-8f8a-29a402220c00.png)

And add strings not yet translated for options hide panels.
![5](https://cloud.githubusercontent.com/assets/12088580/9706833/02cd9198-54ca-11e5-8e1d-d35b01b8dcb2.png)

**Comment by GaidamakUA** [comment]
Partially fixed by commit 213807e4153d0524036c119d77606d09eb34e9e4. Context menu is not fixed, because it is work in progress.

**Comment by franco999** [comment]
Thanks!

**Comment by crimean** [comment]
Context menu for dark theme fixed
