### ISSUE TITLE
Unicode problems?

### ISSUE THREAD

**Issue by vrtareg** [osmandapp/Osmand#1662]
![screenshot_2015-09-07-15-19-56](https://cloud.githubusercontent.com/assets/2562730/9715809/93b5cea8-556c-11e5-8482-93701c6a37cb.png)
![screenshot_2015-09-07-15-15-19](https://cloud.githubusercontent.com/assets/2562730/9715810/93bd0952-556c-11e5-9842-ecb8904c7b16.png)

Hi

I have noticed that some other language names are shown as squares. 

Here is the screen shots from OsmAnd and Vespuci (OSM data).

Could it be  OsmMapCreator issues?

Regards, 
Areg

**Comment by vshcherb** [comment]
This is duplicate (can't find it now open) and known issue so far.
