### ISSUE TITLE
Wrong opening hours rule displayed

### ISSUE THREAD

**Issue by utack** [osmandapp/Osmand#1663]
When searching for POI the wrong opening hours rule can be displayed.
Example: (for http://www.openstreetmap.org/node/419292284 )
It is now: Monday, 14:54
The rules for the restaurant are "Mo-Fr 11:30-15:00,17:30-23:00; Sa-Su,PH 11:30-23:00"
The text of the rule in Osmand shows: "Sa,Su 11:30-23:00"
However it is yellow, meaning internally it has analyzed the correct rule for Monday and knows the restaurant is now open and closing soon.

**Comment by vshcherb** [comment]
Fixed issue with Sa/Su.
Added ellipsize and also make sure that in context menu we see full information.
