### ISSUE TITLE
Can't overwrite or delete imported routing.xml?

### ISSUE THREAD

**Issue by david-gpu** [osmandapp/OsmAnd#16645]
### Description

It doesn't look like there is a way to either delete or overwrite the routing methods that were imported through a `routing.xml` file.

### Steps to reproduce

After going through Navigation settings -> Import routing file, a new entry appears in the "navigation type" menu. However, these new entries cannot be deleted or overwritten.

### Actual result

Long press doesn't show a contextual menu to delete the user-imported routing method.  There is no visible "trash" button next to each entry to delete it either.

### Expected result

Having some discoverable way to delete routing methods imported through an XML file, so that the user can tinker with this without creating a never-ending list of routing methods.

### Your Environment
OsmAnd Version:  #4.3.12
Android/iOS version: Android 13
Device model: Samsung A71

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/20329368/224057149-2ddc664c-0fcf-4790-a693-64222b6a7ea9.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
Import should not rename file but instead should override

**Comment by david-gpu** [comment]
Interesting. The behavior I observe is that importing another routing file with the same name causes a new entry to be added, this time with a number next to it. E.g. if the first time it was imported as  "routing.xml", the second time it is imported as "routing 1.xml" even when the file name was still "routing.xml".

**Comment by david-gpu** [comment]
Reopening. Sorry, I did not expect the issue to be closed just because I added a comment t to it :-/

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14228mqta, Released: 2023-03-10
Can't select, delete, or edit the routing method

https://user-images.githubusercontent.com/104760013/224311476-72f9dd07-1584-4211-9fcf-c5bfba09a4da.mp4

**Comment by david-gpu** [comment]
For other people running into these issues, there's a workaround you can try. The imported XML routing files are stored under `/sdcard/Android/data/net.osmand/files/routing/`. You can delete the ones you don't need, restart OsmAnd and they will disappear.

Likewise, you can use `adb push` to overwrite them -- you will also need to restart OsmAnd.

**Comment by dmpr0** [comment]
## Review 
### Select navigation type
- [ ]  Add additional menu button next to custom routing file name
- [ ] Show context menu after tap on additional menu button
- - [ ] Context menu: Action **Delete**
- - [ ] Tap should open alert dialog with confirmation

<table style="width:100%">
  <tr>
    <th>Additional menu button</th>
    <th>Context menu</th>
    <th>Confirmation alert</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/232446545-e644b20a-5c3f-4382-93c8-33411bdd63b9.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/232446555-0ebc5e67-2a41-4d20-810f-4bef96f2141c.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/232446731-3463bbe2-5a4b-4dee-af00-6e19824f8bb8.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#35859m, Released: 2023-04-27
**Import of duplicates** item of Review doesn't implemented


https://user-images.githubusercontent.com/104760013/235131395-1ba9bfbd-278c-477c-b324-968325ce6bf5.mp4
