### ISSUE TITLE
Override default speed limit if maxspeed:advisory is tagged

### ISSUE THREAD

**Issue by fred702** [osmandapp/Osmand#1664]
At least in the USA and Canada, many motorway_link and other *_link ways do not have a posted speed limit, but have advisory speed limits tagged in OSM with the key [maxspeed:advisory](https://wiki.openstreetmap.org/wiki/Key:maxspeed:advisory). Often this value is much more accurate to real world speeds than the default speed assigned to those way classes in OSMand. I think it would help cases like #1629 to treat the maxspeed:advisory value as maxspeed (overriding the default speed) if no maxspeed is tagged. Since often these kinds of ways are not physically signed with a maxspeed, it is not possible to add more information to OpenStreetMap to solve the routing problem.

**Comment by vshcherb** [comment]
The tag will be available in new maps https://github.com/osmandapp/OsmAnd-resources/commit/d25c12da0793997a94b10661eb501e0e887b2b49

**Comment by vshcherb** [comment]
The rule has added to routing.xml https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#L221

**Comment by fred702** [comment]
Many thanks, will test. Hopefully this will encourage tagging of maxspeed:advisory where appropriate.
