### ISSUE TITLE
Overlay shows map symbols irrespective of setting after screen rotate

### ISSUE THREAD

**Issue by mikehgentry** [osmandapp/OsmAnd#16648]
### Description

The map symbols / text appear when you rotate the screen, even if they're set to invisible

### Steps to reproduce

Add an overlay, set map symbols to invisible.

### Actual result

Rotate the screen, and they appear. Adjust the transparency slider around and they disappear again.

### Expected result

Screen rotation has no effect

### Your Environment
OsmAnd Version: +4.4.1 beta
Android/iOS version: 11
Device model: Xcover 4s

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14226mqta, Released: 2023-03-09



https://user-images.githubusercontent.com/104760013/224105537-2b0d1943-f57a-4b82-ac32-15b0305dd4a2.mp4
