### ISSUE TITLE
Google traffic overlay parameters posted on Reddit break overlay, overlay on/off switch, when restarting

### ISSUE THREAD

**Issue by mikehgentry** [osmandapp/OsmAnd#16649]
### Description

Upon full exit and reopening OsmAnd the overlay disappears, and the overlay on/off switch becomes unresponsive

### Steps to reproduce

Follow these instructions

https://www.reddit.com/r/OsmAnd/comments/11lvalm/how_to_add_live_traffic_to_osmand/

Fully close OsmAnd, and open it again. 

### Actual result

The overlay is no longer visible, and the overlay on/off switch is completely broken at this point, but can be fixed by switching to a different overlay.

### Expected result

Even if there's something wrong with those parameters (the tiles load fine until you quit the program AFAICT?), it shouldn't break the button :)

### Your Environment
OsmAnd Version: + 4.4.1 beta
Android/iOS version: 11
Device model: Xcover 4s

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14234mqta, Released: 2023-03-13
Can be reproduced both with an Underlay and an Overlay 
[logcat (74).log](https://github.com/osmandapp/OsmAnd/files/10956322/logcat.74.log)

For example, there is no such behavior on the iOS version - everything works

**Comment by Zirochkabila** [comment]
@mikehgentry Today, I retested it again with the latest nightly version of https://osmand.net/docs/versions/nightly_versions - it could not be reproduced.
Please try again on your device

**Comment by mikehgentry** [comment]
Working fine for me at least as of 4.5.0#35759m

Cheers!
