### ISSUE TITLE
Heightmap washes out (whitens) other layers

### ISSUE THREAD

**Issue by mikehgentry** [osmandapp/OsmAnd#16641]
### Description

Possibly related #16633

Enabling the heightmap / 3D view washes out other layers. This isn't a huge problem with standard vector maps, but with a 'texture' sort of layer (satellite imagery, or in my case a 3rd party hillshade layer) it undoubtedly makes it harder to read.

### Steps to reproduce

Enable a full coverage underlay, and switch on the heightmap

### Actual result

<img src = "https://user-images.githubusercontent.com/1724168/224009811-d1b8203b-06b3-43be-88e2-73c9802a2b91.jpg" width="300"> <img src = "https://user-images.githubusercontent.com/1724168/224009815-ba847219-0422-412f-8667-e5b8a0c06a50.jpg" width = "300">

### Expected result

I understand that some loss of fidelity is unavoidable with the built-in hillshade, but I don't think it should uniformly wash everything out. If that's unavoidable, perhaps it'd be desirable to make the built-in hillshade optional?

### Your Environment
OsmAnd Version: +4.4.1 beta
Android/iOS version: 11
Device model:  Xcover 4s

**Comment by vshcherb** [comment]
This is due to grayish layer that 3D maps create it's even visible without tilt
