### ISSUE TITLE
Aboriginal_land and border_zone relationships do not appear in the search results

### ISSUE THREAD

**Issue by BikeRoad** [osmandapp/OsmAnd#16652]
Aboriginal_land relationships do not appear in the search results.

![Screenshot_2023-03-09-22-01-55-566_net osmand](https://user-images.githubusercontent.com/19896035/224212840-3ce8c5e0-679f-4d02-b967-c6803b25a837.jpg)

Example: https://www.openstreetmap.org/relation/11032268

**Comment by xmd5a2** [comment]
Dev notes:
If you add a line in `poi_types.xml` it will not work:
```xml
<poi_type name="aboriginal_lands" tag="boundary" value="aboriginal_lands" no_edit="true"/>
```

**Comment by BikeRoad** [comment]
The problem that I reported also happens with the relationship boundary=border_zone

**Comment by vshcherb** [comment]
@xmd5a2 
Added line to poi_types.xml - tested on https://www.openstreetmap.org/export#map=11/39.8721/-113.9357
```
<poi_type name="aboriginal_lands" tag="boundary" value="aboriginal_lands" no_edit="true" />
```
Shows in OBF as expected
```
natural: aboriginal_lands Confederated Tribes of the Goshute Reservation / Aipimpaa Newe Lat 39.872288 Lon -113.988785 osmid=2213087278080  alt_name:en='Deep Creek Valley' name:shh='Aipimpaa Newe' name:en='Confederated Tribes of the Goshute Reservation'
```

**Comment by xmd5a2** [comment]
Fixed
```
natural: aboriginal_lands Aboriginal lands Lat 45.73328 Lon 36.49716 osmid=-4587632351537669355 
natural: aboriginal_lands  Lat 45.7372 Lon 36.578957 osmid=-4587632351537669470 
natural: aboriginal_lands Aboriginal lands Lat 45.73726 Lon 36.575123 osmid=-4587632351537669349 
natural: aboriginal_lands Aboriginal_lands_boundary Lat 45.73789 Lon 36.582584 osmid=-6078318031171014656 
natural: aboriginal_lands Aboriginal lands multipoly Lat 45.737774 Lon 36.5796 osmid=-6078318031170996224 
natural: aboriginal_lands  Lat 45.737835 Lon 36.581966 osmid=-4587632351537669469 
natural: aboriginal_lands  Lat 45.737236 Lon 36.583473 osmid=-4587632351537669468 
natural: aboriginal_lands  Lat 45.73859 Lon 36.582317 osmid=-4587632351537669467 
natural: aboriginal_lands Aboriginal lands Lat 45.739326 Lon 36.580357 osmid=-4587632351537669358 
natural: aboriginal_lands  Lat 45.737583 Lon 36.580303 osmid=-4587632351537669351 
natural: aboriginal_lands  Lat 45.73631 Lon 36.578976 osmid=-4587632351537669350 
```
Relation to test: https://www.openstreetmap.org/relation/11032268#map=7/-11.048/-70.676
Map of Peru will be regenerated today

**Comment by yuriiurshuliak** [comment]
This has been fixed. Mashco Piro Indigenous Reserve is currently displayed in the search.

OsmAnd~ 4.7.0#1497m, released: 2024-02-02

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/853ad5da-ba7b-4450-9158-c491ef48530b"  width="300" height="auto"/> </th>
  </tr>
</table>
