### ISSUE TITLE
We are not passing/updating the correct appMode to the Prolog  Command Player

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#1665]
Title says it all. appMode is passed here: https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/voice/AbstractPrologCommandPlayer.java#L126
and is needed in voice announcements to create shorter prompts for car more, which currently does not work.

**Comment by vshcherb** [comment]
Fixed

**Comment by sonora** [comment]
Confirmed working, thanks! Noticeably de-cluttered our voice prompts, too.

I like what we have achieved in Issue 1411 by now, big improvement over where we came from an few weeks ago. But will keep the issue open for a while to see if we get more feedback. Very challenging to get this optimized for all situations, countries, and languages, though.
