### ISSUE TITLE
Text in Version 2 (OpenGL) has some visible distortion 

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#16656]
## Description
Sequel of https://github.com/osmandapp/OsmAnd/issues/16004

I didn't see it previous time, but see now. Text in Version 2 (OpenGL) has some visible distortion on top and bottom of symbols.

<table style="width:100%">
  <tr>
    <th colspan=2>Version 1</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/224335231-42c9b69a-0793-4ec4-803f-d7350244585c.png"  width="720" height="auto"/></td>
  </tr>
  <tr>
    <th colspan=2>Version 2</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/224335221-1b2b811b-9467-4715-9f2d-bd9ff41a184c.png"  width="720" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
Related (Бульвар ...) 50.44316 30.51606
![telegram-cloud-photo-size-4-6014559072336069332-y](https://github.com/osmandapp/OsmAnd/assets/1042025/2e60ede2-7e13-4269-8b68-7d32985256ac)

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/17269
