### ISSUE TITLE
Map tilt gesture stops working after zoom gesture

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#16650]
### Description
Map tilt gesture stops working after zoom gesture. See video:
https://user-images.githubusercontent.com/12549744/224134860-c7fe8327-2b3b-4d67-bd50-e5768c8956cb.mp4

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14226mqta, Дата выпуска: 2023-03-09
Android version: 12
Device model: poco f3

**Comment by albansuser** [comment]
I also observe this issue.

The only way I can reactivate the tilt function is to close the app and restart.

OsmAnd~ 4.4.0#14226mqta, released: 2023-03-09

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/15931
