### ISSUE TITLE
Provides road surface information on imported tracks 

### ISSUE THREAD

**Issue by Wizit38** [osmandapp/OsmAnd#16659]
Osmand currently only provides road surface, gradient, etc information for tracks calculated by its router

It does not provide such information for tracks generated by brouter or imported tracks.

I would like to request this new feature support

**Comment by Zirochkabila** [comment]
@Wizit38 That's right, road surface information can only be displayed along a calculated route (you can calculate a route by track).
A track is a set of points, coordinates, time, etc. - such a data set cannot contain information about the surface or slopes

**Comment by Wizit38** [comment]
@zirochkabila, is it not possible to have this information also made available for inported tracks?

**Comment by Zirochkabila** [comment]
@Wizit38 Only if you attach the track to the road and lay a route along it - without this procedure, the track is a set of coordinate-points

**Comment by Wizit38** [comment]
What do you mean by attach the track to the road. How do I do this say with an imported track or a track generated by brouter?

**Comment by Wizit38** [comment]
@Anatolii
What do you mean by attach the track to the road. How do I do this say with an imported track or a track generated by brouter?

**Comment by Velomeloman** [comment]
@Wizit38, duplicate of #16484?

**Comment by Wizit38** [comment]
@Velomeloman

Similar but not quite the same.
Osmand has a feature to display slope, smoothness, etc information onto your track. However, it only displays this if you are using the osmand inbuilt router.

If you use a track calculated by brouter or import a track from say ridewithgps.com, it will not display this information.

Apparently, it is possible to get this by attaching to a road but I'm not sure what is meant by that

**Comment by vshcherb** [comment]
Yes it's a duplicate https://github.com/osmandapp/OsmAnd/issues/16484 ! We want to have button - attach to the roads to simpllify UX and get this information.

**Workaround** For now user should go to Plan Route -> Open -> Attach To Roads and find this info. This is a quite complicated path

**Comment by Wizit38** [comment]
When i do plan route-open-attach to road
I get an error message that
You can only attach to roads on a recorded track (i did this on a route that i asked osmand to generate and then saved)

**Comment by Velomeloman** [comment]
@Wizit38, in this case use Edit track - Graph - Surface/Road type/etc.

**Comment by Wizit38** [comment]
@Velomeloman
I can't find edit track - graph
This is what I have when I open options

Where do i find the graph that you mentioned. Tqvm

Regards

**Comment by Velomeloman** [comment]
> @Velomeloman
> I can't find edit track - graph
> This is what I have when I open options
> 
> Where do i find the graph that you mentioned. Tqvm

https://user-images.githubusercontent.com/109347561/224932240-6577308f-746d-450d-bfc9-91fb6170c7a2.mp4
