### ISSUE TITLE
Apeldoorn (Netherlands, Gelderland) can't be found via address search

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1666]
Map data contains following:
	Cities/Towns section, 54 group(s):
		'Апелдорн' [216244216], 1721 street(s) size 2193777 bytes:
			''t Sluisje' [50965], 0 building(s), 2 intersections(s)

For some reason Apeldoorn's name is in russian. OSM data is correct - "name=Apeldoorn" on both point and relation.

**Comment by vshcherb** [comment]
It was wrong parameter in Binary inspector.
