### ISSUE TITLE
Display the route type upon tapping

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#16661]
I think we have this somewhere, but I can't find it anymore, (it's probably not in any Milestone yet), and it should be quite easy to implement:

So far when on the map you tap on a route, in the pop-up selection dialog (in case multiple routes exist in the tapped area) in lines 2 of each entry for certain routes we just show "Route". Users should be able to distiguish here e.g. hiking routes from cycling routes. So it would be interesting to show the types of route here instead (the attributes we subsequently show on each track's context menu  in "Overview"under "Network" and "Route type").

**Comment by sonora** [comment]
Just to clarify, I am talking about where it just say "Route" here:
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/845735/09d75b5b-4ef0-49ce-9cfd-e387ad7c5922"  width="300" height="auto"/> </th>
  </tr>
</table> 

Should be easy to achieve, and is more than just "Nice to have"`?

**Comment by goldfndr** [comment]
[Related reddit thread](https://www.reddit.com/r/OsmAnd/comments/13cr0oc/)

**Comment by vshcherb** [comment]
To do.

We need to print Route type per route "Route - $1%s" (Route - Hiking) if present

**Comment by vshcherb** [comment]
Route could be imported as .gpx. This is a separate issue - *.gpx.zip is not supported. Also you won't be able to see route type by importing this track, you need to check as described here https://github.com/osmandapp/OsmAnd/issues/16661#issuecomment-1559005978

**Comment by dmpr0** [comment]
> Route could be imported as .gpx. This is a separate issue - *.gpx.zip is not supported. Also you won't be able to see route type by importing this track, you need to check as described here [#16661 (comment)](https://github.com/osmandapp/OsmAnd/issues/16661#issuecomment-1559005978)

Do you try to import GPX, or upload GPX to to GitHub?
![Screenshot 2023-08-04 at 17 35 30](https://github.com/osmandapp/OsmAnd/assets/9365308/552f3495-a408-4da9-9283-7a63733ea247)

**Comment by sonora** [comment]
I belive we may be mixing issues here now: I was actually talking about tapping routes on tbe map, i.e. displaying their OSM (hiking or cycling)  network affiliation  (which we know about in our obf files)..This issue seems fixed now.

Importing gpx files seems a different use case, likely justified,  but technically different.
