### ISSUE TITLE
'Attach to the roads' seems to be broken

### ISSUE THREAD

**Issue by mikehgentry** [osmandapp/OsmAnd#16669]
### Description

I can get as far as a dialogue box with a 'Threshold distance' slider and a choice between my profiles. The 'Apply' button is greyed out, and no fiddling with these settings seems to change that. I've tried on a couple of different GPXs, both downloaded from the web and generated by BRouter (both on and off the phone).

### Steps to reproduce

Import a GPX generated from outside OsmAnd. My places -> Tracks. Choose the file, hit navigation button and 'Attach to the roads'. Hit 'Continue'. At this point my only option is to cancel, which gets me to the 'Plan a route' screen. Hitting 'Done' gets me back to the main navigation screen, but not apparently attached to the roads (the option to attach is still displayed, and no surface properties etc. are present).

### Your Environment
OsmAnd Version: + 4.4.1 beta
Android/iOS version:  11
Device model: Xcover 4s

**Comment by sonora** [comment]
In my experience, that means there are no close enough roads, i.e. no solution is found. (Not sure if there is a popup saying that much, I guess there should be...). Perhaps put the tolerance slider as far right as possible, then wait a few seconds.

**Comment by mikehgentry** [comment]
Your comment induced me to leave it for longer, and it did eventually get there - I missed the calculation loader bar before (I think the UI didn't used to look like this? Or perhaps I'm just misremembering). I think maybe you could afford to make it a bit more obvious that it's thinking. Maybe replace the greyed out 'Apply' with a thinking spinner or something.

Anyway, thanks, closing as not a bug.
