### ISSUE TITLE
Android Auto: No GPS Signal

### ISSUE THREAD

**Issue by olifoss** [osmandapp/OsmAnd#16675]
I'm using actual beta of OsmAnd (4.4.2.).

When my Smartphone (Android 13) is in reach of my car system it connects automatically to Android Auto wireless (AA Wireles Dongle)..

It worked since last update that OsmAnd starts automatically and shows the actual position on the map, the map moves like while routing.

Now OsmAnd starts but doesn't get a GPS signal, shows the last known position. Searching for GPS position doesn't work. Start a route from Android Auto doesn't work without GPS. When I open OsmAnd on the phone the GPS position is read in less than a second. Guess it's a problem when OsmAnd is in the background. Have no background restriction and no accu optimation for OsmAnd. Location service is Google Play.

Android Auto version: 8.9.630624

It worked perfectly before the Android Auto split-screen route displaying problem (is now fixed).

**Comment by Zirochkabila** [comment]
@olifoss Duplicate https://github.com/osmandapp/OsmAnd/issues/16607 ?

**Comment by vshcherb** [comment]
Yes we're starting getting more issues related to Android Auto GPS however it wasn't the case before....
