### ISSUE TITLE
I have searched

### ISSUE THREAD

**Issue by anten1222** [osmandapp/OsmAnd#16677]
I have searched
Schlegelstr 30
Neustadt
Bremen 28201 
Deutschland

I found
Herderstr./Schlegelstr., [53332](tel:53332) Bornheim
Googel Maps und Here we go 
finds it immediately
 This is just one example. Overall, the address search is subterranean
 do not file questions or support requests on the GitHub issues tracker.

In case you aren't sure whether to open an issue or not, please send your request to support@osmand.net.

You can get your questions answered using the [Google group](https://groups.google.com/forum/#!forum/osmand) or chat in real-time via our Telegram instances: [English](https://t.me/OsmAndMaps), [German](https://t.me/deosmand), [French](https://t.me/frosmand), [Ukrainian](https://t.me/uaosmand), [Italian](https://t.me/itosmand), [Russian](https://t.me/ruosmand).

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by Zirochkabila** [comment]
@anten1222 Try to find the location by using: Search button on the screen > Address
https://osmand.net/docs/user/search/search-address

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14234mqta, Released: 2023-03-13
@anten1222 Try the method mentioned above - it looks like the queries are showing up in the search

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><video source src="https://user-images.githubusercontent.com/104760013/224746921-54a8e06d-1d1a-4c1d-b8a4-2668e8578470.mp4"  width="300" height="auto"/></td>
    <td><video source src="https://user-images.githubusercontent.com/104760013/224746934-449bbcd3-8834-4414-9b86-9d4967eb5a87.mp4"  width="300" height="auto"/> </td>
  </tr>
</table>
