### ISSUE TITLE
Osmand deletes empty track-folders automatical

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#16672]
### Description
If the last track in a track-folder is deleted/moved away (like the "Import" and "Austausch" here in my case) Osmand automatically and without indicating it deletes the now remaining empty folder.
 
### Steps to reproduce
delete the last track from a folder
when deleting the last track also the folder is deleted

### Actual result
empty folder is deleted

### Expected result
leave the empty folder untouched, I want to use it again and have to create it everytime again.

### Your Environment
OsmAnd Version: V+4.4.1
Android/iOS version: 
Device model:

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14234mqta, Released: 2023-03-13
If moved or delete a track, the folder is not left empty, but is automatically deleted.
**The behavior is similar on iOS too**

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><video source src="https://user-images.githubusercontent.com/104760013/224739715-943a8c0b-d889-4a23-a8a2-48049d2eb9cd.mp4"  width="300" height="auto"/></td>
    <td><video source src="https://user-images.githubusercontent.com/104760013/224739702-f86369cb-ba1d-4b04-8a18-b161e2481a72.mp4"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by sonora** [comment]
Confirmed.

@vshcherb As already noted elsewhere, I think we would benefit here a lot, and at low cost, also e.g. with later support,
- if we look at what's habitual look & feel of some very widely used Android File Managers, Samsung's "_My Files_" just to name one as an example due to the abundance of Samsung devices in our user base, 
- and **mimic their UI and behavior as closely as it makes sense**. That should affect, but not stop at, aspects of sorting, folder creation, item context menu, etc.

The key to OsmAnd becoming an accepted GPX File Manager (a true gap and opportunity in the market), is also having a conventional and streamlined UI, something OsmAnd on occasion has had a history of struggling with ... 😉

**Comment by vshcherb** [comment]
We need to delete empty folders otherwise they will say stuck. It's always possible to create new folder for a track but it's impossible to delete unless we create folder with all actions support.

Note: There is no sense to replicate full system File Manager at least to do it in a short term perspective cause it will take a lot of time to implement all nuances. Of course we will get there but we need to be strict how much implementation of all these function takes.

**Comment by sonora** [comment]
Just a reminder that our legacy screen `MyPlaces/Tracks` does have a "Delete folder" functionality (its `Delete` button will create a checkbox also in front of folder entries), which could help mitigate the argument that they get "stuck".

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#34m, Released: 2023-05-17

If delete or move a track, the folder from which the track was deleted or moved disappears from the list of folders in My Places and Android system. But it is displayed in the suggestion when moving a track

After moving a track to a folder that has disappeared, the folder reappears in the My Places list and Android system

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/2963bb1e-44ac-4201-9997-1dbacc7b5388"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/f257f5f5-59b8-44a6-9902-6aed925a8fac"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by sonora** [comment]
@Rowin63 You mean the system file picker does not show up? Can't currently reproduce , works for me from both 'Tracks' screens.Perhaps try reboot your device to see if something unrelated had crashed. Also try another app which uses the system file picker.

If it persists, may be worth another issue, could be untelated to this here (which seems solved, by my testing).

**Comment by sonora** [comment]
PS: Probably unrelated, but on occasions I use the following procedure to reset OsmAnd"s gpx database:
- Force-stop OsmAnd
- Rename the [OsmAnd-data-folder/]tracks to tracks0
- Start OsmAnd and go to a Tracks screen, verify it sees zero tracks.
- Force-close OsmAnd again and rename the tracks folder back (delete the new, empty one)

This may go a long way in cleaning things up and removing artifacts from previous testing.

**Comment by Rowin63** [comment]
> @Rowin63 You mean the system file picker does not show up? Can't currently reproduce , works for me from both 'Tracks' screens.Perhaps try reboot your device to see if something unrelated had crashed. Also try another app which uses the system file picker.
> 
> If it persists, may be worth another issue, could be untelated to this here (which seems solved, by my testing).

The "file picker" opens, then I tap a file and the same moment I´m back to the "my places"-page. Without having the selected track imported. The "import"-folder is still empty. And also a search for the imported track gives no result, so it´s not importzed to somewhere else. But this behaviour is on two different devices...

**Comment by Rowin63** [comment]
> OsmAnd~ 4.5.0#34m, Released: 2023-05-17
> 
> If delete or move a track, the folder from which the track was deleted or moved disappears from the list of folders in My Places and Android system. But it is displayed in the suggestion when moving a track
> 
> After moving a track to a folder that has disappeared, the folder reappears in the My Places list and Android system
> <img alt="" width="300" height="auto" src="https://user-images.githubusercontent.com/104760013/238983934-2963bb1e-44ac-4201-9997-1dbacc7b5388.jpeg"> 	<img alt="" width="300" height="auto" src="https://user-images.githubusercontent.com/104760013/238983931-f257f5f5-59b8-44a6-9902-6aed925a8fac.jpeg">

Yes, you´re right, an empty folder is not anymore deleted, but not displayed anymore in the "my places - tracks".
The empty sub-folder still exists in the tracks-folder.

**Comment by Rowin63** [comment]
Unfortunately I dont have a 4.4.7 anymore, all is updated. But recently it worked - but not anymore in 4.5.0

**Comment by sonora** [comment]
Confirmed. Same experience here,: File picker opens, but after selecting a track it is not imported.

**Comment by dmpr0** [comment]
# Review
- [ ]  Unable to delete folder from Selection mode
<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/9365308/73a0ce97-55ca-4db5-9a65-1eb11b6240dc"  width="300" height="auto"/>   </td>
  </tr>
</table>
