### ISSUE TITLE
New Tracks screen - Better use of screen real estate

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#16676]
Compare old vs.new below.

Although the font size used for the track name seems the same, and the old screen facilitates viewing the complete track name in 3 lines where needed (e.g. track 18), and the old screen already contains the track- individual 3-dots action menu which the new one does not yet, the old screen uses the real estate better:  It fits more tracks in the same area while looking equally structured.

I think the key is to use narrower line spacing within the lines belonging together to one track, and lose spacing only to separate track entries?

![Screenshot_20230312-161240_OsmAnd~](https://user-images.githubusercontent.com/845735/224554267-23dc0c77-f845-431e-b509-d20bd67e69e1.jpg) ![Screenshot_20230312-160939_OsmAnd~](https://user-images.githubusercontent.com/845735/224554264-02bc0300-2b9d-4b72-86cc-3d8a187d7b8b.jpg)

**Comment by Zirochkabila** [comment]
@sonora Your screenshots show two different screens.
The menu on the first screen still has all the functionality you described
The menu on the second screen has become more extensive compared to the previous one
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/224555146-6a19c12b-dc84-4355-93b0-85fc61147d52.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by sonora** [comment]
Yes, I compare the two different screens on purpose to make sure we use the best practice of both screens.

**Comment by sonora** [comment]
PS: Also on the new "Switch folder" dialog the line spacing between wrapped lines belonging to the same folder and between folders is the same, creating a single **structureless** column of text if you have folders with longer names which all wrap to two lines each.

This can easily be given some visual structure by using the additional line spacing only **between** folder entries, but not for the line-wrapped folder entries.

**Comment by Zirochkabila** [comment]
@sonora I think this is a different issue and you can create a separate issue

**Comment by Nine-Tailed** [comment]
I would suggest removing the comma in front of the region, and increasing the indent a bit from the distance shown in blue
![Screenshot_2023-03-13-08-22-42-646-edit_net.osmand.plus.jpg](https://user-images.githubusercontent.com/12549744/224615144-47e87e67-49c4-4907-a190-fb32c0fc3bc4.jpg)

**Comment by dmpr0** [comment]
Hello! Thank you for the feedback. 
As @Zirochkabila mentioned you have compared two different screens. We din't start to implement new UI for Tracks screen in My Places.

**Comment by sonora** [comment]
Dmytro, I'm afraid you misunderstand: I do on pupose compare two different screens here to illustrate **what we do better on the old screen than  on the new one yet**, so we can transfer best practice to the new  screen. And it boils down to e.g. **use narrow line spacing within entries, and a greater line spacing only between entries**.

**Comment by sonora** [comment]
So where do we stand here, still thinking about it? There's a number of suggestions above, but no response in 2 weeks?

**Comment by dmpr0** [comment]
> So where do we stand here, still thinking about it? There's a number of suggestions above, but no response in 2 weeks?

I don't see any suggestions, only comparison of two different screens. Why you don't compare to similar screen?


<table style="width:100%">
  <tr>
    <th>Old</th>
    <th>New</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/228159535-0ba4cc87-de47-4197-97b5-aebc6594fa9b.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/228159635-8a24cb20-132a-415c-89eb-8d404996ebc1.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Nine-Tailed** [comment]
When wrapping a line, separating the unit of measurement from the quantity looks unappealing.
Track characteristics in the form of distance, time, number of waypoints should preferably be given in one block so that they are all in one line.
Add icons for the given track characteristics.
So the user will be more understandable, otherwise I had to think that it comes after the time (number of waypoints).
![IMG_20230328_202718.jpg](https://user-images.githubusercontent.com/12549744/228320929-64a853f0-856c-4bda-aad7-8a4a5a1e574d.jpg)

![IMG_20230328_202850.jpg](https://user-images.githubusercontent.com/12549744/228320950-18f591d1-5ee7-47a0-843b-81269965c2b5.jpg)

**Comment by sonora** [comment]
Well, small devices with big fonts are used on rafting expeditions where you have lots of fog on the screen sometimes. Please note that I do not suggest to remove the padding, but simply _use single line spacing within items_. 1.5 line spacing within items conveys neither any additional information nor does it contribute to more readability of the list structure?

**Comment by vshcherb** [comment]
I don't see big issue as it looks ok for guidelines - https://m2.material.io/components/lists#behavior. There is no evidence that having 6 or 10 fit the screen will make situation better, we still need to scroll / sort or search, so it's most important. We simply can't design for small devices in same way, if we want UI for smartwatches for instance we need to make it different

**Comment by sonora** [comment]
No it's no big issue indeed. I just felt (but may be mistaken) that the line spacing and item sorting in this picture https://lh3.googleusercontent.com/GVS0-Fp9sWI3OHBSH7cEuycjhGZDF-YdABfQHt4FLO3uyF1-coVt-CelgV74MWGjEV2GvCiq2TKlBofuJL-0hXseDz7cHhz6kE5Nyg=w1064-v0 looks more like what I suggest, while it is wider spaced in our new implementation.

But definitely this https://user-images.githubusercontent.com/845735/224562355-1e0a9efe-fff0-4eb3-8daa-1e7eb6a95d73.jpg is not to standard, I think,and needs improvement?
