### ISSUE TITLE
Possibility to rename marker

### ISSUE THREAD

**Issue by miramikes** [osmandapp/OsmAnd#16687]
Sometimes would be very helpful to have chance rename marker. Especially when the marker name is not very meaningful like "No address determined"
![Screenshot_20230313-171533.png](https://user-images.githubusercontent.com/623412/224763266-fb563ed1-849d-4ce5-8bb8-496287794f00.png)

**Comment by vshcherb** [comment]
You can create a favorite first to give a proper name, we still need to digest markers phylosophy to separate the tool to display directions from points which are favorites and markers

**Comment by letypequividelespoubelles** [comment]
It's already possible in OsmAnd~ v.4.3.12 FDroid. Just click on the marker, and then "modify"

![IMG_20230314_122746_385](https://user-images.githubusercontent.com/54240434/224920297-323fe0f5-d725-4a0f-aee1-534d2d818ae6.jpg)

**Comment by letypequividelespoubelles** [comment]
Yes true, not possible to modify it in the marker list, which could be good too

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14236mqta, Released: 2023-03-14
@letypequividelespoubelles This is also possible in the night version of https://osmand.net/docs/versions/nightly_versions
Can we consider issue closed?


https://user-images.githubusercontent.com/104760013/225109609-3bcfe3bc-5acc-45a1-82ef-c03d05fae214.mp4

**Comment by letypequividelespoubelles** [comment]
@miramikes Is it ok for you ? Or you wish marker's name to be editable in marker menu (in that case, maybe a new issue is better) ?

**Comment by miramikes** [comment]
It is ok for me to close this issue.
