### ISSUE TITLE
v4.4.0#14236 all Quick Actions are deleted

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#16689]
### Description
all previous set quick actions are gone after the update

### Your Environment
OsmAnd Version: 
Android/iOS version: 
Device model: 

![Screenshot_20230314_073328_OsmAnd~](https://user-images.githubusercontent.com/95540936/224915756-5a571c6b-7578-4ee8-aac8-e59762e8ac40.jpg)

**Comment by Rowin63** [comment]
No more information, after the update to 4.4.0#14236 (before version was the last release from a day before) all my previous setted Quick Actions are gone, the Qick Action menue is empty. I had set about 6 or 7 qick actions, they are gone after the update. 
No big deal to set them again, I just wanted to mention it / inform you.

**Comment by Zirochkabila** [comment]
@Rowin63  It's strange, but everything has been saved on my device after the update - we'll see how it behaves

**Comment by Rowin63** [comment]
did not happen again going to v14241 and v14249.

**Comment by Rowin63** [comment]
I think, someone can close this. Or do you still want to observe it?
Happened only one time at this certain update and never again.
