### ISSUE TITLE
POI search for "Waterfall" or Dam fails

### ISSUE THREAD

**Issue by RicoZ-OSM** [osmandapp/Osmand#1669]
it seems a specific POI search for waterfalls is implemented but does never return any results.

As far as I can see this is caused by a line in "resources/poi/poi_types.xml" which defines 
``` <poi_type name="waterfall" tag="natural" value="waterfall"/> ```

which should be

```  <poi_type name="waterfall" tag="waterway" value="waterfall"/> ```

Unfortunately when I change that in /sdcard/osmand/poi_types.xml with an editor it still doesn't work.. no idea  why.

Same kind of problem, "Dam" searches for man_made=dam instead of waterway=dam. There are very few man_made=dam and it is not even sure what those are, most are waterway=dam.

**Comment by vshcherb** [comment]
It requires map to be regenerated.

**Comment by xmd5a2** [comment]
1.rendering_types.xml is used to a)describe tags that need to be in maps b)convert tags to be used as POI
See https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml#L2111
2.poi_types.xml is used to describe POI that need to be included in maps as POI. So changing it locally does nothing useful.
3.Error with dam corrected

**Comment by RicoZ-OSM** [comment]
could you please also fix the waterfall? Still see 
``` <poi_type name="waterfall" tag="natural" value="waterfall"/>```
where it should be "waterway" instead of "natural"

natural=waterfall also exists and was proposed to be the "waterfall cliff edge" which is now  mostly drawn as natural=cliff instead.
   http://wiki.openstreetmap.org/wiki/Proposed_features/Waterfall#History_of_the_proposal

However, the current usage of natural=waterfall is 1646 piece from a LINZ import in New Zealand and random single contributions. The LINZ data seems miserable - dots which are sometimes 5 km from the next mapped waterway. On mapbox this appears that those waterways are partially missing but most of the places don't look like significant waterfalls.. not yet sure how to fix that in OSM.

**Comment by xmd5a2** [comment]
@RicoZ-OSM natural=waterfall is converted to waterway=waterfall internally. It is described in rendering_types.xml.

**Comment by RicoZ-OSM** [comment]
But in "resources/poi/poi_types.xml" it still searches for "natural=waterfall". Or why else don't I find any waterfalls in a country where hundreds of waterfall symbols are rendered?

**Comment by xmd5a2** [comment]
Fixed

**Comment by RicoZ-OSM** [comment]
noticed missing "to" in

```<entity_convert pattern="tag_transform" from_tag="natural" from_value="cliff" if_tag1="waterway" if_value1="waterfall"/>```

in resources/obf_creation/rendering_types.xml

- does that rule do anything?

**Comment by xmd5a2** [comment]
This rule removes waterfall if natural=cliff present. It is needed for map only. I'll correct this.
