### ISSUE TITLE
UI: Speed limit Display

### ISSUE THREAD

**Issue by Gizmot** [osmandapp/Osmand#1670]
I find that there is way too much information on the top right screen when navigating (I use GPX, speed, speed limit, time to go, waypoint). As a serious globe trotter, I find it very handy to be able in a quick glance to see the local speed limit. Right now, I need to read all informations to find the right one.

What I would like is to remove the speed limit display from the "right panel" and leave always on the bottom left  "icon" that pops up when you go over the speed limit.
To clearly display and overspeed limit condition, you could quickly flash this max speed icon.

**Comment by vshcherb** [comment]
You need to check Configure Screen menu http://osmand.net/features?id=map-viewing#Viewing_widgets.

**Comment by Gizmot** [comment]
Hum, lot of text for a poor explanation... sorry
What I meant is: use the "you are going above the speed limit" icon as the road max speed label (you leave it always on).

**Comment by vshcherb** [comment]
I see, technically we are going to something similar but not in the next release (in 1 release). We have mockups already that show that widget information differently so it will be visible in a more familiar way.
