### ISSUE TITLE
Building on top of pedestrian area not rendered

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#16707]
There is a building which is not visible. Probably because it is located inside a pedestrian area:

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/1040784/225250343-c3ba8302-be05-4d7d-9bef-7b615ce22ff3.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

https://www.openstreetmap.org/way/48045409

I guess this can be fixed by creating a multipolygon for the pedestrian area so that the building isn't part of it. But is this really necessary or is it a bug?

OsmAnd 4.4.1, both rendering engines.

**Comment by vshcherb** [comment]
It's not visible on OSM as well https://www.openstreetmap.org/way/48045409#map=19/50.74597/13.06919. Likely pedestrian areas are rendered as roads i.e. they are always over all polygons

**Comment by scaidermern** [comment]
Interesting, I didn't check openstreetmap.org.

I'll convert the pedestrian area to a multipolygon (so you will need a different example for testing :))

**Comment by Zirochkabila** [comment]
The new map shows building - most likely, @scaidermern changes worked
[Pedestrian area.obf.zip](https://github.com/osmandapp/OsmAnd/files/11008508/Pedestrian.area.obf.zip)

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/226106127-e71c0403-98ba-41c8-ab99-06b328c5beed.jpeg"  width="500" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/226106131-4339c392-2237-4f1f-9ac6-5ea2ec65db85.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by scaidermern** [comment]
> The new map shows building - most likely, @scaidermern changes worked

Right. The pedestrian area is now a multipolygon. The building is a member of this relation with role inner, meaning it is no longer part of the pedestrian area. 

Not sure if the original case needs fixing. This is for you to decide.

**Comment by xmd5a2** [comment]
This clearly was a mapping issue. If we try to fix this is OsmAnd then such issues will be masked and fixed with a longer delay.
