### ISSUE TITLE
History not working

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#16709]
Since OsmAnd version 4.4.1(?) the search history is broken. The history contains mainly tracks. Recently searched POIs, categories and addresses aren't listed at all.

**Comment by vshcherb** [comment]
Code revierted from https://github.com/osmandapp/OsmAnd/pull/16525/files

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14243mqta, Released: 2023-03-16
Done
