### ISSUE TITLE
Foot navigation on area=yes / highway=pedestrian not functional

### ISSUE THREAD

**Issue by ceever** [osmandapp/OsmAnd#16714]
### Description
Foot navigation on area=yes / highway=pedestrian is not touching pedestrian area for direct route and uses its borders instead.

### Steps to reproduce
Try navigating to a point on this pedestrian area: 28.24030,-16.84534

### Actual result
Does not touch inner area of pedestrian area, nor connects destination. Also, it uses the path the is draw inside the pedestrian area instead.

![Screenshot_20230315-173755_OsmAnd sml](https://user-images.githubusercontent.com/40247591/225397305-d1a94032-a4f9-4c24-b015-246feee3115b.jpg)

![Screenshot_20230315-172535_OsmAnd sml](https://user-images.githubusercontent.com/40247591/225397440-e0cccc98-b20e-4d43-9603-51b36236f36a.jpg)

### Expected result
Uses the shortest straight line on any pedestrian area and actually reaches the chosen destination, without the need for any actual paths inside the pedestrian area.

### Your Environment
OsmAnd Version: 4.3.8
Android/iOS version: 9
Device model: Galaxy S8

**Comment by scaidermern** [comment]
It works, but only at the border of the area. Most routers don't support routing across areas. Therefore for larger areas mappers add artificial ways to OSM to improve routing.

**Comment by Zirochkabila** [comment]
@ceever Duplicate https://github.com/osmandapp/OsmAnd/issues/2586 ?

**Comment by ceever** [comment]
> @ceever Duplicate #2586 ?

Yes, kind of. But I would strongly oppose the view of this being a "Nice to have" thing. Surely, one could always add a path into a pedestrian area, but that's a workaround specifically for navigation with apps like OsmAnd. However, the specification of OSM does not require such a thing. A pedestrian area is clearly defined as walkable everywhere. If OsmAnd does not support this, then the ball is on the side of OsmAnd and not OSM.

Generally speaking, if one would be consequent, most areas not inhibiting a building or similar are pedestrian walkable and thus incompatible with the current OsmAnd functionality. I have already had many cases when foot navigation was super cumbersome, following roads and only available path, whereas it was easily possible to just walk straight across an area not tagged or mapped as anything.

Clearly, the latter is a different discussion, but one should at least start acknowledging the need to extend OsmAnd's navigation into this direction. I don't see it becoming less relevant in the future with people mapping things on OSM more realistically and consistently.

**Comment by vshcherb** [comment]
Yes we don't support direct-line navigation inside a polygon which could be very helpful for marine navigation
