### ISSUE TITLE
Avoid... for bicycle navigation

### ISSUE THREAD

**Issue by vslatten** [osmandapp/Osmand#1671]
For car navigation there are preference settings such as "Avoid toll roads" or "Avoid motorways". I would like similar functionality to be implemented for bicycle navigation, based on e.g. the mtb:scale of a path, so I can get a route from A to B that does not send me down a path where I have to dismount my bike to avoid injuring myself.

I would personally prefer a preference setting that is customizable so that I can select a key, a comparator (=, >, <, >=, etc.) and a string or number value, with the option of adding more than one avoidance rule. The alternative is to add a few premade ones like "Avoid paths" (highway=track is allowed, but not highway:path), "Avoid difficult MTB paths" (scale:mtb >= 2) and so on.

**Comment by vshcherb** [comment]
I think the easiest way to use custom routing.xml https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml and put these rules there, laster you could share your results. It is not difficult format to get simple rules encoded.

**Comment by vslatten** [comment]
Thanks for the tip! I will look into it and see if it can be achieved there.

**Comment by RicoZ-OSM** [comment]
See also https://github.com/osmandapp/Osmand/issues/1693

**Comment by elumbella** [comment]
I'm not sure if I should open a new bug; I think this issue is related: 
I was just routed over stairs (using bicycle routing option). At least that should be avoided by default, right?

**Comment by vshcherb** [comment]
I just added the option to avoid staris

**Comment by sonora** [comment]
No further action planned here for now, I guess.
