### ISSUE TITLE
Route labelled %1$s when navigating it and it has multiple segments

### ISSUE THREAD

**Issue by tommycrock** [osmandapp/OsmAnd#16712]
### Description
Select a hiking route relation shown on the map (one which osmAnd sees as having multiple segments), hit navigate, it brings up the dialogue:

> #### Select segments
> %1$s contains more than one segment, you need to specify the portion for navigation.
![Screenshot_20230314_224405_OsmAnd+](https://user-images.githubusercontent.com/5749884/225380756-00ffa07d-1bc5-4b3b-97f2-4191a4a59143.jpg)

### Expected result
presumably, '%1$s' is supposed to be a variable for the name.

### Your Environment
OsmAnd Version: 4.4.1
Android version: 12
Device model: samsung s10e

**Comment by Chumva** [comment]
This should be fixed here - https://github.com/osmandapp/OsmAnd/commit/32637a4849671448b7667bc842019e
![Screenshot_1679397583](https://user-images.githubusercontent.com/19220417/226591130-085c453b-9cc1-4a60-beab-3faa36868982.png)
99ae09dbd1

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#14270mqta, Released: 2023-03-25
Done
