### ISSUE TITLE
Profile icon for climbing

### ISSUE THREAD

**Issue by endolith** [osmandapp/OsmAnd#16722]
# 🚀 feature request

### Description

Let us choose a climber icon for profiles under "Profile appearance".

### Describe the solution you'd like

The icon in "My Places" → "Change default appearance" → "Sport" is fine.

### Describe alternatives you've considered

Currently using the hiker icon

**Comment by dmpr0** [comment]
Done https://github.com/osmandapp/OsmAnd/commit/fdeb395088615823a7140bb3e5563bb0abf44c40

**Comment by Zirochkabila** [comment]
Done
