### ISSUE TITLE
POI search/rendering for nudism

### ISSUE THREAD

**Issue by RicoZ-OSM** [osmandapp/Osmand#1672]
http://wiki.openstreetmap.org/wiki/Nudism has been approved about a year ago, would be nice to have POI search and if possible rendering.

The combination nudism=no (and invalid values) could be filtered out and nudism={yes,obligatory,designated,customary,permissive} used as "yes".  The tag is being applied to beaches, campgrounds, lakes and coastline stretches.

http://taginfo.openstreetmap.org/keys/?key=nudism

**Comment by xmd5a2** [comment]
I added this tag to POI a couple of days ago. Not sure if it presents in our current maps though. 
Also not sure it's a good idea to render it on map itself. Possible icons for this tag are complex and it will be hard to achieve good readability.

**Comment by RicoZ-OSM** [comment]
It would be nice if you could add nudism=designated, perhaps as alias to nudism=yes. I don't think too many values other than yes/no are useful.

**Comment by xmd5a2** [comment]
Done

**Comment by RicoZ-OSM** [comment]
is there any way to search places tagged with nudism=* within the app?

**Comment by xmd5a2** [comment]
Unfortunately not yet.

**Comment by RicoZ-OSM** [comment]
Created https://github.com/osmandapp/Osmand/issues/2209 as this seems to be a general problem.
