### ISSUE TITLE
Support all osmc symbols in brown

### ISSUE THREAD

**Issue by tommycrock** [osmandapp/OsmAnd#16738]
### Description

Currently, only a few of the osmc symbols are supported in brown (AFAICT). https://github.com/osmandapp/OsmAnd-resources/tree/master/icons/svg Although not all symbols are listed for brown on the wiki page, it mentions the list is outdated and different vendors support different sets. https://wiki.openstreetmap.org/wiki/Key:osmc:symbol waymarkedtrails supports more brown symbols. https://hiking.waymarkedtrails.org/osmc_symbols.html#

### Describe the solution you'd like

Support all the osmc symbols in brown! I don't think any code change is needed to support a full set, just some additional icons.

Thanks!

**Comment by xmd5a2** [comment]
No new maps are needed. Only OsmAnd version.
![Screenshot_2023-04-11_11-25-06](https://user-images.githubusercontent.com/5829014/231101297-618865d0-8688-4092-859d-d7d6df7d43f3.png)

**Comment by xmd5a2** [comment]
https://github.com/osmandapp/OsmAnd-Issues/issues/1993

**Comment by tommycrock** [comment]
> https://github.com/osmandapp/OsmAnd-Issues/issues/1993

Dead link?

**Comment by xmd5a2** [comment]
> > [osmandapp/OsmAnd-Issues#1993](https://github.com/osmandapp/OsmAnd-Issues/issues/1993)
> 
> Dead link?

No, just private repository
