### ISSUE TITLE
Position icon disappears under certain conditions

### ISSUE THREAD

**Issue by dtcg** [osmandapp/OsmAnd#16735]
### Description
From zoom level 19 and below, position icon disappears. See screenshots below (with zoom level value in right panel.) 

This occurs only in these conditions :

### Steps to reproduce

* map rendering engine, version 2
* dev plugin + heightmap activated
* zoom out below level 20

### Actual result

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/20596421/226096240-e233866a-441c-402a-a13e-5858b330cb51.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/20596421/226096264-747a3c44-fef9-432a-a55a-29ef7f86509b.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  
 

### Expected result

Positon icon should be visible at all zoom levels. 

### Your Environment
OsmAnd Version: 4.3.12
Android/iOS version: EMUI 12 (based on android 10, if I believe wikipedia) 
Device model: HUAWEI CLT-L29

**Comment by fedcas** [comment]
I have the same issue on:

OsmAnd Version: Version 4.3.8 (4308)
Android/iOS version: Android 9
Device model: moto x4

**Comment by dtcg** [comment]
I think it could do with the heightmap. I notice a series of other glitches when activated : some mountain areas are black even when hillshade is disabled, POI selection is off like I have to tap next to them in order to select them, etc.

**Comment by vshcherb** [comment]
Fixed please try 4.4.3-4 in Beta. It's related to 3D maps
