### ISSUE TITLE
Lake names are displayed even if lakes themselves are filtered by area

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1673]
![_2015-09-09_14-35-23](https://cloud.githubusercontent.com/assets/5829014/9760737/647d2c4a-5700-11e5-94f7-6923f476ff4f.png)

**Comment by vshcherb** [comment]
This issue will be solved together with issue filtering text by area, I assume it is duplicate issue then.

**Comment by vshcherb** [comment]
Fixed
