### ISSUE TITLE
At higher zoom level recorded track disappears

### ISSUE THREAD

**Issue by sebaFlame** [osmandapp/OsmAnd#16737]
### Description
When recording a track, and you zoom in, the recorded track disappears. I always set it to red/solid/thin, with arrows for the direction. This happens since the update to 4.3.8 .

### Steps to reproduce
Start recording and zoom in to the last 3-5 zoom levels.

### Actual result
The recorded track disappears.

### Expected result
The recorded track stays visible.

### Your Environment
OsmAnd Version:  4.3.8
Android/iOS version:  Android 10
Device model: Samsung Galaxy A6

**Comment by Zirochkabila** [comment]
@sebaFlame Please update or download the nightly version of OsmAnd and try again
https://osmand.net/docs/versions/nightly_versions

**Comment by sebaFlame** [comment]
The nightly seems to work!

**Comment by Zirochkabila** [comment]
@sebaFlame can the issue be considered closed?
