### ISSUE TITLE
Cannot download maps to sdcard, disk space not recognized

### ISSUE THREAD

**Issue by mildred** [osmandapp/OsmAnd#16739]
### Description

Cannot download maps to sdcard. Crash.

When trying to download maps to sdcard, I first select the storage location (either external storage or multi-user storage). There are two of them. Either the actual phone storage recognized as emulated external/multi-user storage and the disk space is correctly computed there. Or the actual sdcard as external/multi-user storage. The available disk space is not recognized for the sdcard storage folders.

When trying to doenload the maps, Osmand will complain about insufficient disk space. it shows a message about a few begabytes of negative disk space and stops.

Reinstalling OsnAnd, and not it crashes between the time it looks for my current location (and best map to doenload) and the moment it primpts me the map to download

### Steps to reproduce

- open OsmAmd
- Click the big blue button "Start together" (o something equivalent, using a French system)
- click on the bottom to choose the disk space
- choose "external storage 2" or "multi user storage 2", one or the other. The available free space is not shown
- go back
- click download to the map (or it may have crashed before this point)
- get a message that it cannot download because of insufficient disk space

The crash only occurs when selecting the storage space where it cannot detect available space.

### Actual result

Ability to download maps, even if free disk space cannot be determined

### Expected result

Failed to download or crash

### Your Environment
OsmAnd Version: 4.3.8
Android/iOS version: /e/ OS. Android 11
Device model: klte (Samsung Galaxy S5)

**Comment by scaidermern** [comment]
Could be #14165. If I understand correctly this is an issue specifically with Android 11.

**Comment by pebogufi** [comment]
Try using
/storage/xxxx-xxxx/Android/**media**/net.osmand.plus
Where xxxx-xxxx is the name of sd card.
Use manually specify.
There are access problem using android 11 and newer, you can read about the problems in a lot of threads.

**Comment by Zirochkabila** [comment]
@mildred Duplicate https://github.com/osmandapp/OsmAnd/issues/14165 ?

**Comment by mildred** [comment]
That's probably the same issue, sorry for the duplicate
