### ISSUE TITLE
App theme doesn't follow system theme

### ISSUE THREAD

**Issue by frasty** [osmandapp/OsmAnd#16740]
### Steps to reproduce
Set app theme to system default and then change the system theme to night theme or light theme

### Actual result
Osmand doesn't change the app theme

### Expected result
Osmand should follow the system theme

### Your Environment
OsmAnd Version: 4.3.12
Android/iOS version: Android 12
Device model: realme 7 Pro

**Comment by Zirochkabila** [comment]
@frasty Please download the night version of OsmAnd and try again https://osmand.net/docs/versions/nightly_versions

**Comment by frasty** [comment]
Ok, thanks. Will try 4.4 nightly

Il mer 22 mar 2023, 16:23 vshcherb ***@***.***> ha scritto:

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#14264mqta, Released: 2023-03-24
Issue described by the user could not be reproduced
But, in Live updates - when changed system theme stripes of a different color are displayed 

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><video source src="https://user-images.githubusercontent.com/104760013/227534217-4da5afd4-16f1-46ac-adb6-ecf746692d68.mp4"  width="300" height="auto"/></td>
    <td><video source src="https://user-images.githubusercontent.com/104760013/227534225-81363e10-5f21-499c-98e6-d0c9159e6b64.mp4"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by franco999** [comment]
It happens to me too. There seem to be parts of the background that reverse the theme from which it is selected.

OsmAnd~ 4.5.0#14277mqta, Release: 2023-03-29

<img src="https://user-images.githubusercontent.com/12088580/228976675-b192634e-ead9-4e7e-84be-70f488342fc3.jpg" width="200"> <img src="https://user-images.githubusercontent.com/12088580/228976685-6071aaea-08bc-4a7d-9e04-c5bf3ae8f1ed.jpg" width="200">

**Comment by vshcherb** [comment]
To do: Bug on Live updates screen - doesn't follow system theme, check Download Tiles

**Comment by Nine-Tailed** [comment]
selecting markers from navigation
![Screenshot_2023-04-05-14-45-01-810_net.osmand.plus.jpg](https://user-images.githubusercontent.com/12549744/230071254-aaf749a9-ce13-4c21-aa2b-8188af9d1f63.jpg)

**Comment by Zirochkabila** [comment]
4.4.7, OsmAnd~ 4.5.0#35740m, Released: 2023-04-10 - OK
A theme in Menu is different from a theme in Navigation

https://user-images.githubusercontent.com/104760013/230915804-241c90d9-9922-41ed-a404-5d15d52733e6.mp4

**Comment by Chumva** [comment]
> 4.4.7, OsmAnd~ 4.5.0#35740m, Released: 2023-04-10 - OK A theme in Menu is different from a theme in Navigation

When you open the navigation menu app profile is changed to the car, it can have another theme selected

**Comment by franco999** [comment]
In "OsmAnd~ 4.5.0#35766m, Released: 2023-04-12" is done! 👍

**Comment by dmpr0** [comment]
## Review 
- [ ]  Wrong Status bar color, should be `status_bar_color_dark/light`
- - [ ] Download Maps – Updates – Live updates
- - [ ] Download Maps – Local – Online tiles - Microsoft Earth – Edit

<table style="width:100%">
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/232442632-ad31dffe-c053-4a77-b9f5-3aaf41d8669d.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/232442639-54c50391-db3d-4acb-92ab-3da27a107946.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by franco999** [comment]
Currently (in OsmAnd~ 4.6.0#670m, 2023-08-27) there is a bug with the "Theme" option when in "system default" and when in dark mode throughout the device, as the context menu of the POIs does not change as it should (see picture).

| With the default system theme. | With the dark theme of the app |
|--------|--------|
| <img width=250 alt="default system theme" src="https://github.com/osmandapp/OsmAnd/assets/12088580/3a8c4731-1a17-4c7f-811e-dd624235de8a" /> | <img width=250 alt="night theme" src="https://github.com/osmandapp/OsmAnd/assets/12088580/0ab3360d-daf4-4a48-802d-5a9183ab5030" /> |
