### ISSUE TITLE
POI Create/Add uploads "user_defined_other" Version 2.2.0#193M (last few nightly)

### ISSUE THREAD

**Issue by mikeshenson** [osmandapp/Osmand#1674]
When I add a POI, I start typing **fas** and the **fast_food** option automatically displays. I click on the **fast_food** option and the the **User defined** gets small. So I checked the advanced menu and everything is OK there. I assume what is in the **Advanced** menu is what should be uploaded to OSM. The POI gets uploaded to OSM with the **user_defined_other** as the tag.

It would be nice to upload what is displayed in the **Advanced** screen. 

I just tried uploading this POI with attached screen shot. 
https://www.openstreetmap.org/node/3736075197

![2015-09-09-08-42-23](https://cloud.githubusercontent.com/assets/7337270/9763615/2e638c2e-56d0-11e5-9831-4d88720ce052.jpg)

**Comment by franco999** [comment]
Me too in #12990M

**Comment by mikeshenson** [comment]
Thank you! @GaidamakUA
