### ISSUE TITLE
how can i get rid of this new button ?

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#16743]
Since a few days there is a new button which you see in center of the screenshot. 
I can move this button, pressing it refreshes the screen, I can move it to the bottom which enables to remove it (for sometime).
Device Samsung S10, Android 12
NO button with Samsung tab S5e Android 10.
Both devices with same version
OsmAnd~ 4.4.0#14251mqta, veröffentlicht: 2023-03-18
Rendering v2 openGl, 2,5D=off

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/18628183/226174500-a319f210-5ede-4a18-89d6-1291012fb9ce.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
@pebogufi Please record a video of how the button appears and how it works/disappears. Also, attach a log file

**Comment by pebogufi** [comment]
[Screenrecording+logcat.zip](https://github.com/osmandapp/OsmAnd/files/11011214/Screenrecording%2Blogcat.zip)
Logcat was created immediately after stop of recording.

**Comment by pebogufi** [comment]
@Zirochkabila 
I am very sorry. I just detected, that this button is "feature" of Android 12 system. I don’t know how to stop it and what it's good for, but found it also in message app.
Closing thread...

**Comment by pebogufi** [comment]
.
