### ISSUE TITLE
Unexpectedly Straight -> TSLL and TR -> C

### ISSUE THREAD

**Issue by razor74** [osmandapp/OsmAnd#16752]
### Description
When i drive in the direction from screenshots below, a wrong turn lane count( arrows) is show on the top of the screen - 5 lanes , but the real lane count is 3. You can see the exact location where i was and in other screenshot the turn lane schematics from JOSM.
### Steps to reproduce
When i drive from Soseaua Vitan Barzesti road to Soseaua Oltenitei road.
### Actual result
5 turn lanes
### Expected result
only 3 turn lanes
### Your Environment
OsmAnd Version: Osmand+ Pro 4.4.3
Android/iOS version: Android 13
Device model: Xiaomi Mi11
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/5586993/226435856-b0f4f65f-5e54-4307-80ad-a8d1382dccfa.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

![incorrect lane count](https://user-images.githubusercontent.com/5586993/226435859-2f281923-a243-46d0-b936-fbad24afb81b.png)

**Comment by Zirochkabila** [comment]
@razor74 What maps of this territory and country do you have downloaded, do you use live updates?

**Comment by razor74** [comment]
I have Romania map from 1 march 2023 and i use live updates.

**Comment by Zirochkabila** [comment]
OsmAnd 4.4.4, released: 2023-03-22

`44.386406, 26.139163`
[Map](https://drive.google.com/file/d/17elaUq3aawwMQrbViKqNvXBK_GD5T26L/view?usp=sharing)
[OSM](https://www.openstreetmap.org/way/23766846#map=17/44.38592/26.14041)
[OsmAnd](https://osmand.net/map/?start=44.387949%2C26.140938&end=44.383416%2C26.137730&mode=car#17/44.38602/26.13932)


https://user-images.githubusercontent.com/104760013/227515365-42186839-af21-498d-8143-16864930f1fe.mp4

_____

Same
`53.884649, 27.619833`
[Map](https://drive.google.com/file/d/1tgtDwUoxkzdQgLm3HOa9lvfWVi0hf5zh/view?usp=sharing)
[OSM](https://www.openstreetmap.org/way/48538459#map=17/53.88182/27.61373)
[Osmand](https://osmand.net/map/?start=53.884593%2C27.619790&end=53.879365%2C27.609960&mode=car#17/53.88299/27.61594)

https://user-images.githubusercontent.com/104760013/227510193-8a5a70e8-8a33-4ce3-aeea-fd7543af0e1a.mp4

____
`53.90069, 27.61206`
[Map](https://drive.google.com/file/d/13HZyH6OrezHCK_xxIHv6UVwehILEp7xO/view?usp=sharing)
[OSM](https://www.openstreetmap.org/way/875428742#map=18/53.90063/27.61197)
[OsmAnd](https://osmand.net/map/?start=53.901436%2C27.614018&end=53.897238%2C27.603257&mode=car#17/53.89976/27.61049)


https://user-images.githubusercontent.com/104760013/227518041-2a5bc378-9262-49a2-9795-6552613f680d.mp4

**Comment by razor74** [comment]
Until the point when wrong lane count begin, now it is corect , but just before this point still show wrong lane count. There is only 3 lanes per direction and osmand shows 5. There is 3 forward and 3 backward on opposite direction, not 5 in one direction.

**Comment by razor74** [comment]
Osmand still shows wrong lane count.   This is the real  turna lane configuration. 
![image](https://user-images.githubusercontent.com/5586993/227578947-9abb43f6-283e-4a89-b03a-da59f5ac5d02.png)

**Comment by SamRuzhowski** [comment]
> OsmAnd 4.4.4, released: 2023-03-22
> 
> `44.386406, 26.139163` [Map](https://drive.google.com/file/d/17elaUq3aawwMQrbViKqNvXBK_GD5T26L/view?usp=sharing) [OSM](https://www.openstreetmap.org/way/23766846#map=17/44.38592/26.14041) [OsmAnd](https://osmand.net/map/?start=44.387949%2C26.140938&end=44.383416%2C26.137730&mode=car#17/44.38602/26.13932)
> 
> Same `53.884649, 27.619833` [Map](https://drive.google.com/file/d/1tgtDwUoxkzdQgLm3HOa9lvfWVi0hf5zh/view?usp=sharing) [OSM](https://www.openstreetmap.org/way/48538459#map=17/53.88182/27.61373) [Osmand](https://osmand.net/map/?start=53.884593%2C27.619790&end=53.879365%2C27.609960&mode=car#17/53.88299/27.61594)
> 
> `53.90069, 27.61206` [Map](https://drive.google.com/file/d/13HZyH6OrezHCK_xxIHv6UVwehILEp7xO/view?usp=sharing) [OSM](https://www.openstreetmap.org/way/875428742#map=18/53.90063/27.61197) [OsmAnd](https://osmand.net/map/?start=53.901436%2C27.614018&end=53.897238%2C27.603257&mode=car#17/53.89976/27.61049)

And Уральская street from 2nd video at the end has turn:lanes:backward=reverse;left|through;left|right. Way 868135783. So lanes need to be like this.
![Screenshot_20230325-112446_1_1](https://user-images.githubusercontent.com/128892083/227706376-db719a96-6d31-4406-ad11-7e1e78b50f05.png)

**Comment by vshcherb** [comment]
To do: No 1 , No 2 - should be fixed. No 3 - not reproduced.

**Comment by razor74** [comment]
Hi. the problem is present on map release from may. The map show now 6 lanes instead of 3.

**Comment by vshcherb** [comment]
# TODO 

# 1 

- https://www.openstreetmap.org/way/234238770#map=17/50.24178/18.99694
- https://creator.osmand.net/map?start=50.241795%2C18.995994&end=50.247116%2C18.998247&mode=car#18/50.24217/18.99702

Through (Straight) turn indicator is replaced turn slightly left.

-----

# 2

`44.386406, 26.139163`
[Map](https://drive.google.com/file/d/17elaUq3aawwMQrbViKqNvXBK_GD5T26L/view?usp=sharing)
[OSM](https://www.openstreetmap.org/way/23766846#map=17/44.38592/26.14041)
[OsmAnd](https://osmand.net/map/?start=44.387949%2C26.140938&end=44.383416%2C26.137730&mode=car#17/44.38602/26.13932)


https://user-images.githubusercontent.com/104760013/227515365-42186839-af21-498d-8143-16864930f1fe.mp4

**Comment by ivanPyrohivskyi** [comment]
PR https://github.com/osmandapp/OsmAnd/pull/17421
Test case before/after, OsmAnd do not show left turn and reverse at same time, but code instruction is consist reverse (TU) 34233649 Go ahead (+TL,TU|+TL,C|TR):
<img width="400" src="https://user-images.githubusercontent.com/128892083/227706376-db719a96-6d31-4406-ad11-7e1e78b50f05.png" /> <img width="400" src="https://github.com/osmandapp/OsmAnd/assets/1040293/aa4dd7d4-52fd-49ba-9634-21009ecd833c" />

**Comment by ivanPyrohivskyi** [comment]
Test case 44.386406, 26.139163 after PR https://github.com/osmandapp/OsmAnd/pull/17421
Before/after
Lanes configuration of intersection are right, but [this way to fuel station](https://www.openstreetmap.org/way/227300986) also counting as possible lane. I suggest to avoid all [service=* road](https://wiki.openstreetmap.org/wiki/Key:service) (but not all highway=service) in lane counting. Will be in separate pull request.
<img width="400" src="https://github.com/osmandapp/OsmAnd/assets/1040293/8a8152ae-3b1c-451c-b734-5c79800f4764" /> <img width="400" src="https://github.com/osmandapp/OsmAnd/assets/1040293/02794d0b-420c-4ecf-9f25-36d56d256c27" />

**Comment by ivanPyrohivskyi** [comment]
Test case 50.24268, 18.9957
Need to fix data. [Way 234238770](https://www.openstreetmap.org/way/234238770) (through|through|through;right) is not connected with [way 128275340](https://www.openstreetmap.org/way/128275340), therefore OsmAnd generate syntetic lanes instruction.
<img width="400" src="https://github.com/osmandapp/OsmAnd/assets/1040293/031d6007-3ace-42fe-b528-8f80526c961f" />

JOSM:
![Screenshot 2023-06-15 at 11 56 54](https://github.com/osmandapp/OsmAnd/assets/1040293/908b8e01-be68-4c11-8b0a-7b53a02d42e9)

**Comment by ivanPyrohivskyi** [comment]
Test case 49.57615, 11.0159
Need to fix data or create virtual syntetic lanes for [way 430007222](https://www.openstreetmap.org/way/430007222) like TL|C or TL|TL|C|C (from way 515591061).
Ways with lanes:
[Way 30405356](https://www.openstreetmap.org/way/) left|left|through|through|right|right that use for instruction.
[Way 515591061](https://www.openstreetmap.org/way/515591061) left|left|through|through

Present [restriction only_straight_on](https://www.openstreetmap.org/relation/1669919)

<img width="400" src="https://github.com/osmandapp/OsmAnd/assets/1040293/72a7e6a4-63c3-486a-973c-1d0476862a7d" />

**Comment by vshcherb** [comment]
Summary Jun 16 2023 
-------------
All mentioned cases are fixed except 3

- [ ] 1. Topic starter https://github.com/osmandapp/OsmAnd/issues/16752#issuecomment-1592594307 - investigating how to fix
- [ ] 2. Data need to be fixed https://github.com/osmandapp/OsmAnd/issues/16752#issuecomment-1592644516 - however we're checking 
- [x] 3.  Data need to be fixed https://github.com/osmandapp/OsmAnd/issues/16752#issuecomment-1592678308 - however we can fix it somehow different (please create new issue)
- [ ] 4. Migrate to C++ 
- [ ] 5. Fix PR comments

**Comment by xmd5a2** [comment]
Test for https://github.com/osmandapp/OsmAnd/issues/16752#issuecomment-1592678308 added
