### ISSUE TITLE
Again Osmand is reported "power intensive app" because missing shut down button

### ISSUE THREAD

**Issue by razor74** [osmandapp/Osmand#1675]
Contionuoussly osmand app remains in memory and consumes all battery because you keeep at this bad idea to eliminate shut down button. And i am not the only one with this big problem for my phone. I cannot remember any time to enter in apps menu and force close Osmand app because he remains in memory. And others too. other maybe even didn't know how to find and enter in apps menu in order to force close this app...

**Comment by sonora** [comment]
Please be aware that apps in memory are part of the Android architecture, this per se has no noticeable implication on power consumption, I have measured this on many different devices. In fact, if you frequently open OsmAnd to look at a map in certain intervals, the app remaining in memory actually uses significantly LESS power than if you always closed (or force-closed) it.

 OsmAnd actually only uses noticeable power under 2 conditions: 
- Screen and GPS usage (while the screen is on and you are watching the map screen),
- or from just GPS usage (if using navigation or trip recording while the device is asleep, in this case a notification icon will be visible in the Android notification bar.)

I have occasionally seen devices where OsmAnd is reported (by the OS) to use power in different situations, but verifying with advanced tools have always shown this to be an artifact of the OS reporting (power consumption by wakelocks triggered by different apps seem not always attributed correctly in all versions of Android.)

**Comment by JeanDom** [comment]
In earlier versions when interrupting a trip, I closed OSMand and disabled GPS (to save power and use the phone for other purposes). Was perfectly OK. 

Now, I cannot close OSMand any more and I only disable GPS.
Now OSMand not only continues in the backgroud, but continues talking to me and even says "no GPS reception". This is not only anoying, but also consumes power, power, power, power.......

**Comment by sonora** [comment]
No further action planed here, no evidence for a general issue,
