### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16755]
### Description
Crash when trying to open the track menu
[exception (41).log](https://github.com/osmandapp/OsmAnd/files/11026443/exception.41.log)

### Steps to reproduce
Menu > My Places > Import (or another folder other than Visible) > Three-point dot button 

### Actual result
Crash

https://user-images.githubusercontent.com/104760013/226557688-b6820656-1a03-44cf-8fab-7bc53ebbbb3c.mp4

### Expected result
Track menu opens

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14256mqta, Released: 2023-03-21
Android/iOS version: Android 12
Device model: Poco x3 nfс

**Comment by nazar-kutz** [comment]
**Pull Request**
* https://github.com/osmandapp/OsmAnd/pull/16756

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#14270mqta, Released: 2023-03-25
Done
