### ISSUE TITLE
Unable to calculate bicycle route

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#16779]
## Description
Start: `19.90690, 99.83350`
Destination: `19.894489, 101.136337`
Route link: https://osmand.net/map?start=19.906887%2C99.833275&end=19.894489%2C101.136337&mode=car#7/17.240149/100.501663

<table style="width:100%">
  <tr>
    <th>Car</th>
    <th>Bicycle</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/227168223-72d552d1-d5ee-402c-ae1e-7fe64dad6197.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/227168204-40300043-ae2f-48fa-afa3-71d7d07995cb.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14261mqta, Released: 2023-03-23
Not reproduced - 15s routing

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/227172342-cc9fadb4-3aa5-4f81-b016-08190f19b42a.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>
