### ISSUE TITLE
osmand:atachment insted a/v notes

### ISSUE THREAD

**Issue by mariush444** [osmandapp/OsmAnd#16770]
My idea is to add osmand's tag `osmand:atachment01` `osmand:atachment02` ... to gpx file.
The UI of POI and A/v notes can be unified and a/v plugin as plugin is not needed anymore.

In case of osmand:atachment any file can be attached: photo, video, voice, txt, docs ....

**Comment by vshcherb** [comment]
Well yes we plan to refactor a/v notes so they will be part of Favorites but that's another issue.
