### ISSUE TITLE
Manual zoom always rotates map

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#16773]
### Description
It is (nearly) impossible to perform a manual (two fingers) zoom without rotating the map. 
"fixed north" always gets set to "manual rotation" only by zooming. 
### Your Environment
OsmAnd Version: 4.4.4
Android/iOS version: 
Device model:

**Comment by scaidermern** [comment]
Same problem here. Two-finger zoom _always_ rotates the map with OsmAnd 4.4.4.

It is rather unsettling to have such obvious bugs again and again. Of course it is a beta, but still one would expect at least some minor testing before releasing it.

**Comment by scaidermern** [comment]
Probably a duplicate of #16751? :thinking:

**Comment by Rowin63** [comment]
Yes, but  #16751 is closed...

**Comment by vshcherb** [comment]
Task is in progress, next week should be moment to test.

**Comment by vshcherb** [comment]
> Yes, but #16751 is closed...

Still better comment in the closed issue as it clear duplciate
