### ISSUE TITLE
Usability - "location" popups

### ISSUE THREAD

**Issue by RicoZ-OSM** [osmandapp/Osmand#1677]
* on Android I would expect that those disappear if any point outside the box is tapped, hitting the little X sign is not quite as easy.. especially if they happen to zoom or scroll out of the view

* it took me a while to figure out that I had to tap the popup once more to get into the menu. Possibly there could be a "..." bellow the text of the popup to indicate that there is more or the menu could be presented immediately (with the location info on top) without the extra step

* is there a way to get "internal object/debugging info" , or list of all attached tag/values etc of the corresponding object?

**Comment by stephan75** [comment]
About the popup:

There is already a different user interface in nightly builds of Osmand ... please try those by manually installing the apk file ... and give feedback.

**Comment by sonora** [comment]
I like the new "popups" a lot!

My feedback as follows:
- The X and other icons are wrong color still (dark gray on black in the dark theme is hardly visible in bright sunlight)
- Many, especially new users have no clue what our icons mean. It may make sense to still use them here in the bottom bar, unless we find a better way, but maybe long-tapping them could produce a popup bubble with a brief explanation ("Directions", "Save as Favorite", "Share", etc.), like we do when long tapping the action bar icons on most search result screens
- The popup menus (after tapping any of the icons) are not consistent with respect to having a headline yet (headline missing on "Directions" and "All actions" menus)

Best, Hardy

**Comment by RicoZ-OSM** [comment]
Just to be sure, should I test http://download.osmand.net/latest-night-build/OsmAnd-default.apk ?

**Comment by sonora** [comment]
Yes, that's the apk to test.

Many things have already been improved now. Three major things which still need fixing are:

(1) The new bubble needs to automatically disappear after some menu actions, like after user selects "Directions to", so it does not obstruct the Navigation toolbar which appears thereafter. 

(2) The new toolbar needs to also appear after a users selects "Show on map" on any search results screen (currently still the old bubble appears for this case.)

(3) In the long run (maybe only after the search screen re-design?) we must make the look and feel of the icon bar on the new location bubble and the icon bar on the search results screen identical. They now still largely differ (e.g. tapping the nav arrow icon on the location bubble produces the "Directions" context sub-menu, but on a search address result screen it directly triggers "Directions to". Things like this must be strictly aligned to simplify the app operation!

**Comment by RicoZ-OSM** [comment]
The new look is pretty cool but I hit a bug:

* tap on route symbol
* select from (from favorites)
* select destination on map
* wait for route to appear
* tap on a place with the intention to add it as waypoint - instead the point is selected as destination, already active one discarded

Quite bizarrely, if the so created destination is close to home an old style location popup will appear somewhere else (but with coordinates matching the selected point). Hope you can reproduce that?

**Comment by vshcherb** [comment]
This is work in progress
