### ISSUE TITLE
Map orientation is too sensitive

### ISSUE THREAD

**Issue by MarioSwitch** [osmandapp/OsmAnd#16785]
### Description
When Map orientation is set to "Fixed: North is up" and I want to zoom in/out, Map orientation automatically sets to "Fixed: Manually rotate" as I rotate a little bit.
This issue appears to be added in 4.4.4 as in 4.4.3, there is no problem: I have to rotate to change Map orientation but if I rotate a bit, orientation doesn't change.

### Steps to reproduce

1. Set Map orientation to "Fixed: North is up"
2. Try to zoom in/out

### Actual result
Map orientation changes to "Fixed: Manually rotate"

### Expected result
Map orientation stands "Fixed: North is up" if the rotation is small

### Your Environment
OsmAnd Version: 4.4.4 (downloaded on Google Play)
Android/iOS version: Android 13
Device model: Google Pixel 7

**Comment by scaidermern** [comment]
Duplicate of #16751 #16773

**Comment by MarioSwitch** [comment]
> Duplicate of #16751 #16773

Oops... Closed!
