### ISSUE TITLE
Coordinate widgets do not disappear when opening a Quick Action

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16788]
### Description
When opening Quick Action, the Coordinate widgets at the top of the screen don't disappear and are covered by the Quick Action menu

### Steps to reproduce
Add Coordinate Widgets to the top of the screen > Open Quick Action

### Actual result

https://user-images.githubusercontent.com/104760013/227274366-cd4c40b1-c78f-45e1-bbaf-ac271da33786.mp4

### Expected result
Widgets disappear like other widgets and, accordingly, don't underlap with the Quick Action menu

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14261mqta, Released: 2023-03-23
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by vshcherb** [comment]
Note: compass icons should also move to the bottom edge of quick actions?
