### ISSUE TITLE
Coordinates displayed incorrectly in CH1903

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16781]
### Description
Incorrect placement of the CH1903 and CH1903+ coordinate system

### Steps to reproduce
Find this place `57.45571° N, 16.26735° W` > Detail

### Actual & Expected result

![image001 (1)](https://user-images.githubusercontent.com/104760013/227174803-0916395a-afbe-4548-aa15-01a35ef64cbf.jpg)

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14261mqta, Released: 2023-03-23
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by barka91** [comment]
I will work on this issue

**Comment by barka91** [comment]
I noticed that the result given by the application is the same that is given by the swisstopo (see this link below ). Can you tell me how you found your results please?

https://www.swisstopo.admin.ch/content/swisstopo-internet/en/topics/survey/reference-systems/switzerland/_jcr_content/contentPar/tabs/items/dokumente_publikatio/tabPar/downloadlist/downloadItems/516_1459343097192.download/ch1903wgs84_e.pdf

**Comment by Zirochkabila** [comment]
@barka91 The results were found by one of our users and, accordingly, an issue was created to investigate this behavior

**Comment by barka91** [comment]
@Zirochkabila I think that it is not a mistake and we can close this issue.
