### ISSUE TITLE
distance of start showing turn lanes

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/Osmand#1678]
last weekend i travelled a lot on German highways. 
while this i noticed that often the turn lanes begins before osmand shows up the turn lanes.
so i had to wait for osmand to know on which lane i have to go.
i would prefer, that osmand shows up the turn lanes, when they start, or at least xx meter before the turn, if the turnlane is short.

using last nightly

greeting simon

**Comment by Gizmot** [comment]
can you pinpoint exactly one of those turn? Could be an OSM issue

**Comment by vshcherb** [comment]
Couldn't observe.

**Comment by jf-simon** [comment]
I will look for it in my next trip
