### ISSUE TITLE
More minor untranslated strings

### ISSUE THREAD

**Issue by franco999** [osmandapp/Osmand#1679]
Show on start > in the panel settings
Live updates > in the list of maps and development settings. (download_live_updates)
Address is unknown yet > in the new popup location (unknown_location)

**Comment by franco999** [comment]
![1](https://cloud.githubusercontent.com/assets/12088580/9922832/a6b18b4c-5cc3-11e5-8e7c-796c8f8982cd.png) ![2](https://cloud.githubusercontent.com/assets/12088580/9922833/a6bb9cea-5cc3-11e5-800b-f433b19705cc.png)
![3](https://cloud.githubusercontent.com/assets/12088580/9922834/a6cc08fa-5cc3-11e5-9efe-7d0c54587200.png) ![4](https://cloud.githubusercontent.com/assets/12088580/9922835/a73cd8fa-5cc3-11e5-836f-1d741aa42517.png)

**Comment by vshcherb** [comment]
1. Going to be fixed
2. This string will be changed by release, so it is better to not translate it yet.
3. Fixed
4. Going to be fixed. (where exactly these dialog)?

**Comment by franco999** [comment]
4. The warning is displayed, after canceling the creation of a POI.

**Comment by GaidamakUA** [comment]
4. Strings extracted as resource and going to be fixed soon.

**Comment by vshcherb** [comment]
Fixed
