### ISSUE TITLE
Whole land tile renders as water at some zooms

### ISSUE THREAD

**Issue by blackboxlogic** [osmandapp/OsmAnd#16798]
### Description
At three different zoom levels, there's a whole map tile that renders blue even though it is land. The tile is in southern Maine USA, and this rendering issue has been happening over the last few map updates.

### Steps to reproduce
Download the Maine USA map, change zoom levels over southern Maine, observe an all-blue tile at 3 zoom levels.
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/31355456/227676008-2ef56fa3-3c9a-4a11-bab7-3330bc6275cc.png "  width="300" height="auto"/> </th>
  </tr>
</table>  

The attached image is after sun-set, so the map is in a dark theme but the issue is also in the light theme map. I have not tried deleting and re downloading the Maine map.

### Actual result
Blue tile 

### Expected result
All land areas should render as land 

### Your Environment
OsmAnd Version: 4.3.8
Android/iOS version: android 12
Device model: pixel 3
The Maine map I have downloaded says February 28, 2023.

**Comment by blackboxlogic** [comment]
Update: I deleted the Maine map and the map rendering issue persists, so it seems the problem is with the "world overview map (mini)"

**Comment by Zirochkabila** [comment]
@blackboxlogic Does the night version also reproduce https://osmand.net/docs/versions/nightly_versions?

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#14272mqta, Released: 2023-03-27
Not reproduced

**Comment by blackboxlogic** [comment]
I'm using fdroid and it's not clear if a nightly build is available there. I've upgraded to 4.3.12, deleted "world overview map (mini)" and downloaded "world overview map".

The blue tiles still appear.

**Comment by Zirochkabila** [comment]
Try to download here https://osmand.net/docs/versions/nightly_versions#google-play-beta-builds

**Comment by blackboxlogic** [comment]
As directed, I installed Osmand nightly, I downloaded the world map and the Maine map. I could not reproduce the problem. I exported my settings from the normal install into the nightly install and could not reproduce the problem.

So I guess I wait until the next version is released, assuming it's been fixed. Thanks.

**Comment by Zirochkabila** [comment]
@blackboxlogic Can we consider this issue closed?

**Comment by blackboxlogic** [comment]
Yes thank you

**Comment by blackboxlogic** [comment]
For the record, upgraded to 4.4.7 release from FDroid and the issue is fixed.

**Comment by blackboxlogic** [comment]
I'm noticing more blue land tiles. I'm going to keep a record on this ticket and reopen the ticket after I have a few, or notice a pattern.

Zoomed in pretty far:
44.20113° N, 69.07389° W

**Comment by yuriiurshuliak** [comment]
I tried to reproduce several times on the last nightly build. And do not reproduce similar behavior. Here are the steps:

- Download the map at these coordinates 44.20113° N, 69.07389° W
- Try moving the zoom several times from the smallest to the largest.
- Try using night mode and day mode

Please provide more precise factors to reproduce this bug if I missed something.

OsmAnd~ 4.7.0#1356m, released: 2024-01-12

<table style="width:100%">
  </tr>
  <tr>
    <th>Night mode</th>
    <th>Day mode</th>
  </tr>
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/5e3c66c7-b0c3-4469-be8e-73a891347963"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/bd140917-3f34-4ebf-95e0-d47e09472c84"  width="300" height="auto"/>   </td>
  </tr>
</table>
