### ISSUE TITLE
Subway line wrong color

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#16792]
### Description
In Moscow, a new metro line has recently been opened - BKL, in which the color # 82C0C0 (turquoise) is indicated in the osm, but the osmand shows gray for this line.
https://www.openstreetmap.org/relation/13525792#map=10/55.7244/37.5904&layers=N
https://www.openstreetmap.org/relation/13525793#map=10/55.7244/37.5904&layers=N

### Actual result
![Screenshot_2023-03-24-00-04-03-832_net.osmand.plus.jpg](https://user-images.githubusercontent.com/12549744/227360715-bfa0a64e-2e4b-409c-b1e6-dab31eb68113.jpg)

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#14262mqta, Дата выпуска: 2023-03-23
Android version: 12
Device model: poco f3

**Comment by letypequividelespoubelles** [comment]
See #12557

**Comment by Zirochkabila** [comment]
@Nine-Tailed Duplicate https://github.com/osmandapp/OsmAnd/issues/12557?

**Comment by Zirochkabila** [comment]
@Nine-Tailed Can we consider this issue closed?

**Comment by Nine-Tailed** [comment]
> @Nine-Tailed Can we consider this issue closed?

Yes
