### ISSUE TITLE
App appeared to still think it was in car mode after changing to bike mode after starting navigation

### ISSUE THREAD

**Issue by LJNielsenDk** [osmandapp/OsmAnd#16796]
### Description
Changing from car mode to bike mode after starting the navigation didn't appear to change the actual navigation suggestions.

### Steps to reproduce
Start navigation in car mode.
Change to bike mode by pressing the mode circle on the map.
Observe mode circle is showing bike mode.

### Actual result
Navigation appears to still be in car mode by what it tells you to do, like go onto roads where bikes are not allowed (have not verified if this is a map error (there is a sign on Selma Lagerløfs vej, Aalborg, Denmark just before going into the roundabout on Universitetsboulevarden, Aalborg, Denmark that says bikes are not allowed) or constantly recalculating the route to ignore bike paths even when you're driving on a bike path.

### Expected result
Navigation should be in the mode it is shown to be in.

### Your Environment
OsmAnd Version: 4.3.8
Android/iOS version: Android 12
Device model: Nokia 8.3 (TA-1243)

**Comment by mikehgentry** [comment]
You can change the profile doing the navigation via the navigation menu, and you can change the display profile via the main menu, or tapping the profile icon to jump to configure map.

These two things don't have to match - you can be using a navigation in one profile that was generated in another. There's definitely utility to that (I have many different profiles for different situations, and often want to have a peek at another profile, without regenerating the route), and once you know it can work like that and isn't a bug you won't do it again. I guess it would be good if there was a way to communicate better that these are separate though.

**Comment by Zirochkabila** [comment]
@LJNielsenDk Please install the nightly version and check again https://osmand.net/docs/versions/nightly_versions
Alternatively, you can install the beta version of OsmAnd 4.4.4 in the Play Store

**Comment by Zirochkabila** [comment]
@LJNielsenDk The route will be recalculated only if you change the profile in the Navigation window (where you calculate the route)
When you change the profile on the map, you change the overview profile, it does not affect the route calculation.

**Comment by LJNielsenDk** [comment]
I guess it's working as intended then, though that is not at all clear from the UI.
