### ISSUE TITLE
Setting the map's sensitivity to rotation when zooming with a gesture

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#16805]
# 🚀 feature request

### Description
Recently the map's sensitivity to the rotation gesture was changed and it began to rotate when zooming.  Then the sensitivity was reduced, but I still get false positives of the map rotation.

### Describe the solution you'd like
Maybe it's worth letting the user adjust the sensitivity to the rotation of the map.  Or add a setting that prohibits the rotation of the map if the orientation of the map is north from above.

Or return the sensitivity to the rotation that it was before.

**Comment by Zirochkabila** [comment]
@Nine-Tailed Duplicate https://github.com/osmandapp/OsmAnd-Issues/issues/1409?

**Comment by Nine-Tailed** [comment]
> @Nine-Tailed Duplicate https://github.com/osmandapp/OsmAnd-Issues/issues/1409?

you have a broken link.
