### ISSUE TITLE
Crashing on attempting to Modify POI (OsmAnd+ 4.4.4)

### ISSUE THREAD

**Issue by Boothy99** [osmandapp/OsmAnd#16806]
**Description**
When attempting to edit any single-point Node POI, OsmAnd+ immediately crashes when I click on "Modify POI".

**Steps to reproduce**
Click on any (single-point Node) POI (such as a pub, or shop etc).
Choose "Action" / "Modify POI"

**Actual result**
As soon as I click on "Modify POI", then OsmAnd+ immediately crashes / closes down. This occurs on two separate devices I have at hand.

**Expected result**
Should obviously be able to edit a POI when signed into OpenStreetMap within Plugins / OpenStreetMap editing. I tried signing out of OpenStreetMap plugin, then back in again with the same results.

**Environment**
OsmAnd Version: OsmAnd+ 4.4.4, released: 2023-03-22 (on both devices).
Android versions: 13 (Google Pixel 6) & 10 (Samsung Galaxy Tab S4)
Device models: Google Pixel 6 & Samsung Galaxy Tab S4

**Comment by Boothy99** [comment]
https://user-images.githubusercontent.com/13983995/227767041-937e3e12-1154-4653-a752-c2d25e16a2ad.mp4

**Comment by pebogufi** [comment]
See also
https://github.com/osmandapp/OsmAnd/issues/16801

**Comment by Boothy99** [comment]
Oops ... thanks @pebogufi 
I did do a search before posting - obviously not a very successful one 🤔
I'll close this now thanks 👍

**Comment by Boothy99** [comment]
Same as -
Crash when trying to edit POI #16772
