### ISSUE TITLE
Bugs in the interface of the live update screen

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#16803]
### Description
The live updates screen has white bars and the notification bar has turned orange.
![Screenshot_2023-03-25-16-48-05-860-edit_net.osmand.plus.jpg](https://user-images.githubusercontent.com/12549744/227721425-8ffa7bc6-9032-4393-a159-0eaeea7831dd.jpg)

![Screenshot_2023-03-25-16-47-31-133-edit_net.osmand.plus.jpg](https://user-images.githubusercontent.com/12549744/227721426-f28fadcf-6307-4800-8e33-6b889c6e39a6.jpg)

### Expected result
version 4.3.12 did not have these errors
![Screenshot_2023-03-25-16-49-57-432_net.osmand.jpg](https://user-images.githubusercontent.com/12549744/227721436-8a835758-5594-4a7d-9f45-95739c927f32.jpg)

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#14270mqta, Дата выпуска: 2023-03-25
Android version: 12
Device model: poco f3

**Comment by Zirochkabila** [comment]
@Nine-Tailed Duplicate https://github.com/osmandapp/OsmAnd/issues/16740#issuecomment-1482801746

**Comment by franco999** [comment]
It happens to me too and it becomes really annoying. There seem to be parts of the background that reverse the theme from which it is selected.

OsmAnd~ 4.5.0#14277mqta, Release: 2023-03-29

<img src="https://user-images.githubusercontent.com/12088580/228976675-b192634e-ead9-4e7e-84be-70f488342fc3.jpg" width="200"> <img src="https://user-images.githubusercontent.com/12088580/228976685-6071aaea-08bc-4a7d-9e04-c5bf3ae8f1ed.jpg" width="200"> <img src="https://user-images.githubusercontent.com/12088580/229319878-1c5378b0-3465-46fa-a166-8fc45aa22205.png" width="200">
