### ISSUE TITLE
install developement enviroment document is out of date?

### ISSUE THREAD

**Issue by moosaviamir** [osmandapp/Osmand#1680]
Hi.
I followd "install developement enviroment" Document but it seems out dated!
I get the following error when i run this command:

repo init -u git://github.com/osmandapp/OsmAnd-manifest.git

fatal: manifest 'default.xml' not available
fatal: manifest default.xml not found

please help me. some people says the documentation is out dated and recommend to do something else but the other commands is not working too.

is there any other document or installation guide?

Regards.

**Comment by moosaviamir** [comment]
Found it!
I should specify xml file in command line.
sudo  repo init -u git://github.com/osmandapp/OsmAnd-manifest.git -m android_build.xml
keeping move forward.
Thank you Anyway.

**Comment by EoANishant** [comment]
Hi ,
Which file should one specify for ios app ? U mentioned the one for android .
