### ISSUE TITLE
Map jumps during zoom from 19 to 20 (Android and iOS)

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16812]
### Description
Map jumps during zoom from 19 to 20 (Android and iOS)
Most likely, it's all about the **Height map**

### Steps to reproduce

- Change the zoom from 19 to 20 and vice versa

### Actual result
Height map
<table style="width:100%">
  <tr>
    <td><video source src="https://user-images.githubusercontent.com/104760013/227795742-af5dc805-1deb-44d9-8bb5-4edfd7f80832.mp4"  width="300" height="auto"/></td>
    <td><video source src="https://user-images.githubusercontent.com/104760013/227795751-ce572047-0397-47b0-9191-228b65e33612.mp4"  width="300" height="auto"/> </td>
  </tr>
</table> 

### Expected result
Without Height map

<table style="width:100%">
  <tr>
    <td><video source src="https://user-images.githubusercontent.com/104760013/227795906-1b870020-53df-4d11-a579-d41d764600d0.mp4"  width="300" height="auto"/></td>
    <td><video source src="https://user-images.githubusercontent.com/104760013/227795908-5c41f121-4320-4053-aa2d-64183f0c8b64.mp4"  width="300" height="auto"/> </td>
  </tr>
</table> 

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#14271mqta, Released: 2023-03-26 / 4.4.6.12
Android/iOS version: Android 12 / iOS 15.7.3
Device model: Poco x3 nfc / iPad mini 4

**Comment by vshcherb** [comment]
Known issue when falling under the ground, will be researched later
