### ISSUE TITLE
3 suggestions for our new menu structure

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#1681]
(1) I think we should  change the wording "Home" in our (drawer) menu to something like "Dashboard" (or maybe anybody has a better wording idea), because "Home" in a nav system normally has a different association (many people would think of "Drive home"), and also the "Home" screen in Android is already taken for something totally different.

(2) On many 4 inch screens, our current drawer has exactly 1 entry more than would fit on the screen without having to scroll (with dev plugin active). I suggest that the "Builds" item does not really need to be on the top menu layer, but we could rather move this to the settings of the development plugin? 

(3) Looks like our "Start simulation" item currently only lives at the bottom of the dashboard (if dev plugin is enabled, of course). In my mind it is not a very obvious place to be at, maybe we should actually move this to the dev plugin settings, near where we have "test voice prompts"?

**Comment by jf-simon** [comment]
I agree with you. 
 And I am a little bit confused of the config icon in dashboard. first i thought it is for osmand setting and not for the dashboard. Maybe changing the icon make it clear. like the “screen settings“ Icon

**Comment by sonora** [comment]
I have fixed issue (1) above and also changed the icon as suggested.
(2) + (3) still open.

PS:
(4) I think the our setting SHOULD_SHOW_DASHBOARD_ON_START is a weird one, because it only controls a one time action which in Android rarely occurs (app start only). I think the setting should be deleted. 
Alternatively we could use it to switch the app behavior between always showing the drawer menu or always showing the dashboard upon a tap on the menu button. But this basically introduces to ways to run the app, Drawer or Dashboard as primary interface, which I am certain will confuse the majority of users.

**Comment by breversa** [comment]
> And I am a little bit confused of the config icon in dashboard. first i thought it is for osmand setting and not for the dashboard. Maybe changing the icon make it clear. like the “screen settings“ Icon

I'm also totally confused by the different "config" buttons : I can never tell which one is for the dashboard and which is for OsmAnd. And which one is for the screen, or for the map…

However, the navigation options button when planning a trip is handy and can't be mistaken. :-)

**Comment by vshcherb** [comment]
(1) definitely, please feel free to proceed with it (just the only thing we need to create new resource to maintain proper translation)
(2) partially agree, because Builds are not visible in release installation. So I argue that's not an issue and we shouldn't do anything (it is only in development plugin)
(3) True, I agree we could duplicate it in development plugin settings, though I'm not sure if it is needed. It is hidden, but it is not widely used.

**Comment by sonora** [comment]
I know  bunch of people (regular power users, not developers) who have the dev plugin activated to get access to our sunrise/unset info (which we have put here in the settings.)  It is mainly these people who are bothered by the other things the dev plugin provides in all different places, and that's why I though it may be a good idea we better consolidate all actions the dev plugin provides in its settings, and not scatter it around in common menus or dashboard.

**Comment by vshcherb** [comment]
(3) I agree let's put it there if it is not difficult.

**Comment by sonora** [comment]
For (3) I'd say let's wait where we go with our Dashboard now. Latest builds look to me like we are going back to a menu (Drawer)-based scheme (fine by me). The Dashboard would only be seen
- upon app start (which is very rare in Android) if the user selected "Show upon app start",
- or if the user explicitly taps on "Menu/Dashboard". These extra taps needed would de facto enormously reduce the usage of the Dashboard for most users, almost to the point of making it obsolete. And then we would definitely need a new home for the "Start simulation" button  :-)
