### ISSUE TITLE
Hide favourites and map markers

### ISSUE THREAD

**Issue by Noitarud** [osmandapp/OsmAnd#16826]
# 🚀 feature request

### Description
Map feels cluttered

### Describe the solution you'd like

favourites and map markers, I want to hide by type since (for example) the ski slopes are not always necessary or I use the maps for other things or expeditions.

If user selects POI when navigating, could show relevant favourites also…?

### Describe alternatives you've considered

Declutter…?

**Comment by Zirochkabila** [comment]
@Noitarud Regarding POI - you can customize the display in each profile separately (if necessary, make a copy of the profile) and when switching, the POI that is activated for this profile will be displayed

Regarding Favourites - you can add the function of displaying (displaying a specific folder of Favourites) Favoruites to the Quick Action and activate them in a few seconds

**Comment by dmpr0** [comment]
Hi!
You can hide Favorites:
* By group in **Menu** – **My Places** - **Favorites**, tap on 3 dot's menu – **Show on map**
* All **Favorites**, in **Menu** – **Configure Map** – **Favorites**

Map markers:
* **Menu** – **Configure Map** - **Map markers**.

**Comment by Noitarud** [comment]
@Zirochkabila my version does not appear to support + adding actions, plus I would have anticipated the showing of favourites by folders to be in the "configure map" page then once the user adds folders to have the ··· options button appear alongside the slider so folders can be disabled, I can only hide all right now. Better placed here. (Okay, POI is separate)

@dmpr0 I anticipate using the app for different purposes so need some up while others not. Cannot do this at all with markers. @Zirochkabila Says I can display groups of favourites (so would, at least, be useful to group markers in the same folders as favourites, or else separate and enablable as described for favourites in paragraph above).

**Comment by scaidermern** [comment]
Do you really need to use markers? Try favorites or GPX tracks with waypoints instead. Both support grouping, both can be hidden individually. Over all, both are way more flexible and customizable than markers.

(I really don't get why anyone is using map markers at all. They just feal really cumbersome to me)

**Comment by sonora** [comment]
Yet another resson to strategically consider https://github.com/osmandapp/OsmAnd/issues/14413#issuecomment-1464957494, I guess. 😉

**Comment by Noitarud** [comment]
@dmpr0 (configure map) Show: Favourites are only On/Off. I would like to enable display by group, and I could need the same behaviour with markers too, if I am on another project I can hide what pertains to this.

**Comment by scaidermern** [comment]
> @dmpr0 (configure map) Show: Favourites are only On/Off. I would like to enable display by group

Disabling individual favorite groups is possible at My places, as described earlier.
