### ISSUE TITLE
http://osmand.net/releases/

### ISSUE THREAD

**Issue by anten1222** [osmandapp/OsmAnd#16829]
/### Your Environment
OsmAnd Version: 4.4.5
When I open Osmand, it says "Install HMS Core".

Android/iOS version: 
Device model:

**Comment by dmpr0** [comment]
It seems you install version for Huawei App Gallery. If you don't use Huawei App Gallery, try to install OsmAnd from different App Store or from https://docs.osmand.net/docs/versions/free-versions

**Comment by dmpr0** [comment]
> I did it as you suggested. The result is the same. Try it yourself

Yes, you are right, we have build Huawei by mistake. Free version will be rebuilded in a 30 minutes.
