### ISSUE TITLE
🚀 Feature request: Allow to move favorites between folders

### ISSUE THREAD

**Issue by zipav** [osmandapp/OsmAnd#16828]
### Description

 Into My places → favorites users have some groups with many favorites within. They want to reorganize them, e.g. move it to another group.
Unfortunately, it is not possible to multi-mark some favorites in order to move them all to another group (like users can do if they want to delete favorites). Instead, as far as known, they have to open every favorite individually to move it.

### Describe the solution you'd like

Possibility to multi-mark some favorites in order to move them all to another group.

**Comment by yuriiurshuliak** [comment]
Req: Move Gpa with 2000 waypoints to one folder.
With the ability to change the color and icon.

Conclusion: import a GPX files with poi and be to have the possibility to assign them at the moment of import to a folder, icon and color.

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/16917
