### ISSUE TITLE
Slopes / hillshade showing contour lines when added via Configure map -> Terrain

### ISSUE THREAD

**Issue by mikehgentry** [osmandapp/OsmAnd#16824]
### Description

When added via Configure map -> Terrain, instead of as an overlay, you get a set of contour lines as well. Hillshade looks a bit more like an aliasing / Moiré type pattern in places, but similar.

I'm not sure it should be there unless explicitly enabled - it's a loss of user control, especially in that you can't specify density / colour etc. as you can when enabling them deliberately.

The higher resolution is great though.

<img alt="" width="300" src="https://user-images.githubusercontent.com/1724168/228036113-0b512a4a-967a-464d-a61c-6b92d8de0914.jpg"> <img alt="" width="300" src="https://user-images.githubusercontent.com/1724168/228036118-3a01b138-d9a4-4097-a97d-5e99c16255ad.jpg">

### Your Environment
OsmAnd Version: + 4.4.4 beta
Android/iOS version:  11
Device model:  Xcover4s

**Comment by Zirochkabila** [comment]
@mikehgentry We have additional settings - try doing it this way: Menu > Plugins > OsmAnd development> Settings > Generate slope raster maps from 3D maps > Disable

**Comment by mikehgentry** [comment]
@Zirochkabila Thanks, I didn't spot those.

If I'm understanding correctly that gets me back to the old method (which I assume is just downloading tiles from an OsmAnd server).

Ideally we'd be able to get the new method, with the higher resolution, but have fine control over the parts of it that look like contour lines (colour, density, thickness and all that).

**Comment by Zirochkabila** [comment]
@mikehgentry Yes, we are thinking about how to implement this
