### ISSUE TITLE
Strange turn arrows displayed at a bended street

### ISSUE THREAD

**Issue by Peter0** [osmandapp/OsmAnd#16832]
When going a route passing this node: https://www.openstreetmap.org/node/1178358087
there will be presented strange arrows in the turn-arrows-window. Rf. submitted image, where "34 m" appears. There are two arrows, just as there were two lanes, one (the "through" lane) exclusively for entering the residential way named Steinweg, and another one for staying on the secondary class street. I can't discover any reason in the OSM data for displaying this kind of (somewhat tangling) arrows (except the shape/geometry of the streets).

Expected behaviour is that there are no turn directions at this node. This is nothing special, compared to all the other junctions where residential ways ending at a bigger ("secondary" in this case) street. Particularly be aware of the first few meters of the other street that comes off at a much greater angle than the remaining part of the street. To me a "through" indicating arrow is an unattractive manner if one should really convinced to turn into this street (other than at the shown route, where this street will not be taken).

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/2462058/228492400-9eda374b-fe7a-4a8f-b306-7c8199636352.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

V 4.3.8 on /e/OS

Regards, Peter

**Comment by vshcherb** [comment]
I think it makes sense and could be helpful during navigation. Probably it's a duplicate issue that there is 1 lane and not 2 and that we need to fix but other than that it's not a big issue.

**Comment by Peter0** [comment]
Provided that one goes in the direction like shown in appended screenshot, when I imagine that it is (as it is in reality) only 1 lane, then in my imagination there will be a "through;right"-arrow. If one stays on the main street, it's not a big issue, as there is no possibilty to turn right at the moment the device told you to do so. But if you really want to turn into Steinweg, the device will told you to drive straight; doing so results in missing the left-turn junction to Steinweg.
