### ISSUE TITLE
Incorrectly built route

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16837]
### Description
Incorrectly built route
The way is laid by a longer route
[OsmAnd](https://osmand.net/map/?start=50.079672%2C35.579953&end=50.083084%2C35.524035&mode=car#15/50.0787/35.5554)
[OsmAnd Broke point](https://osmand.net/map/?start=50.079121%2C35.569868&end=50.083084%2C35.524035&mode=car#15/50.0787/35.5534)
[Map here](https://drive.google.com/file/d/1HhoW_a-a9SvprEgvFHE3wDPWCqW9ZRPT/view?usp=sharing)

### Steps to reproduce

- Navigation 
- Car profile
- From `50.08028, 35.58394` to `50.08308, 35.52403`

### Actual result
[OSM OSRM](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=50.0795%2C35.5809%3B50.0808%2C35.5387#map=14/50.0797/35.5636)

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/228596251-fc7c4687-76d9-41bc-856b-6ca184c69365.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
[OSM GraphHopper](https://www.openstreetmap.org/directions?engine=graphhopper_car&route=50.0795%2C35.5809%3B50.0808%2C35.5387#map=15/50.0799/35.5597)

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#14277mqta, Released: 2023-03-29
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by Dima-1** [comment]
[Way](https://www.openstreetmap.org/way/613652228/history#map=14/50.0736/35.5896) has tag [smoothness = very_horrible]( https://wiki.openstreetmap.org/wiki/Key:smoothness).  May be wrong mapping

**Comment by MarioSwitch** [comment]
> [Way](https://www.openstreetmap.org/way/613652228/history#map=14/50.0736/35.5896) has tag [smoothness = very_horrible](https://wiki.openstreetmap.org/wiki/Key:smoothness). May be wrong mapping

Moreover, last update was 4 years ago...

**Comment by vshcherb** [comment]
So problem should be fixed on the map
