### ISSUE TITLE
Boxes on Korea map

### ISSUE THREAD

**Issue by alxchk** [osmandapp/Osmand#1683]
On my Nexus 4 and Galaxy Tab S i haveproblem with korean names on the osm map. Screenshot is attached.
![screenshot_2015-09-13-01-28-10](https://cloud.githubusercontent.com/assets/329535/9834141/0c8a98d8-59b7-11e5-9f58-660e15c3c494.png)

**Comment by dmpr0** [comment]
we already have same issues
