### ISSUE TITLE
at junctiiuns, small road hides big road

### ISSUE THREAD

**Issue by letypequividelespoubelles** [osmandapp/OsmAnd#16845]
### Description
At junctiun,  small road hides big road, see screenshot. The gighway=primary_link is hidden by highway=residential.
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/54240434/228811609-26606988-c25c-4094-8486-5693a6e57045.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Steps to reproduce
Check this [node](https://www.openstreetmap.org/node/6475259567) for exemple.

### Your Environment
OsmAnd Version: FDroid 4.3.12, rendering engine 2
Android/iOS version: 7.1.2
Device model: crosscall action X-3

**Comment by Zirochkabila** [comment]
@letypequividelespoubelles Most likely, it's the presence of the `highway=primary_link` tag 
https://wiki.openstreetmap.org/wiki/Tag:highway=primary%20link?uselang=uk

**Comment by letypequividelespoubelles** [comment]
@Zirochkabila but why do primary_link should be hidden by residential or tertiary roads ?

**Comment by Zirochkabila** [comment]
@letypequividelespoubelles I think it's all about the tag hierarchy in the OSM

**Comment by vshcherb** [comment]
Nope it should be connected with **service_link** < primary_link < service < primary

**Comment by letypequividelespoubelles** [comment]
@vshcherb I'm not sure that it should be service > primary_link ... primary_link are usualy quite big road, every time bigger than service

**Comment by vshcherb** [comment]
This is how it supposed to work with rendering all links are rendered below all roads
