### ISSUE TITLE
Nearest road penalty loop

### ISSUE THREAD

**Issue by Gizmot** [osmandapp/Osmand#1684]
Stopped at a gas station (not on a road), selecting a store just accros the highway overpass.
Got this somewhat interesting loop:

![screenshot_2015-09-09-11-40-14](https://cloud.githubusercontent.com/assets/13919997/9834682/452000ac-5994-11e5-94fe-5fcb697f1952.png)

Here is a closer shot of what happened:
![screenshot_2015-09-12-21-06-18](https://cloud.githubusercontent.com/assets/13919997/9834681/451de484-5994-11e5-84ae-c92556a3af34.png)
1. First off all, there is a slight bug in OSM, but that does not change the problem.
   That ramp should be starting a bit further south in real life.
   Instead of splitting off, there is multiple lines.
   From my location there, you can go east (like on the offline routing), change lane and go straight over the overpass.
2. Considering the bug in OSM, routing should be asking me to grab Thickson road a bit  North of my location or going North to Consumers Drive instead of telling me to grab that highway ramp (closest road by distance)

In this case, I am not sure how the routing should handle that... Measure the straight line distance (start to finish) and if routing calculations are way different (lets say 100% over), try to recompute with all directly accessible nearby road within 100m?

**Comment by RicoZ-OSM** [comment]
Exiting unmapped ground is always tricky. The rule that would help in this case is that you can never enter a motorway(link) other than by first entering a regular road and taking an allowed turn.

**Comment by Gizmot** [comment]
Did not tough about that. But what about you are stopped on the side of the road (you are lost) on a motorway and ask directions to osmand. Result could be quite hilarious?

**Comment by RicoZ-OSM** [comment]
More generally I see the problem as lack of data - you are in unmapped territory and Osmand can not navigate unmapped territory. 

So while the "don't enter motorways illegally" rule would help in your first example I think the more generally useful way to proceed would be that Osmand asks the user where to start navigation, maybe offering a selection of nearby roads.

Normally you would expect that once the car starts moving or when it enters some other than the precomputed road Osmand would recompute the route, however it probably won't recompute the complete route but only the small piece to the next road so it might still give you completely wrong instructions.
 
This is also an example where the route (probably) won't get recalculated when you enter the road in slightly different  place ..

**Comment by vshcherb** [comment]
It is a really tough problem to solve and it could be related not only to the map data but also to GPS signal which could be inaccurate. To be honest I don't see a solution here, I think the long route could be either correct or either wrong (like in your case), so complicating algorithm doesn't solve the problem and make it even harder to understand how it works. I think the solution in this case would be just to draw some roads and the algorithm will find the closest road.

**Comment by Gizmot** [comment]
Well, I retract my previous comment. RicoZ-OSM solution could solve the problem. My corned case makes no sense since this is for a case where you are not on an existing road anyway

**Comment by sonora** [comment]
No action planed, I am afraid.
