### ISSUE TITLE
OsmAnd does not start with the latest update

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16864]
### Description
Possibly related to https://github.com/osmandapp/OsmAnd/issues/16860

After installing the new update. OsmAnd doesn't start anymore. Rebooting the device doesn't help either.
[gryvnya.zip](https://github.com/osmandapp/OsmAnd/files/11128903/gryvnya.zip)

Redmi S2
Android 9

**Comment by vshcherb** [comment]
What device it was reproduced?

**Comment by Zirochkabila** [comment]
4.4.6 Not reproduced
