### ISSUE TITLE
OsmAnd's map rendering has recently crashed

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16860]
### Description
The error occurs when you open the program, not when you use the program!
Cannot change rendering 1 to 2
The error reappeared with the latest update
[logcat (89).log](https://github.com/osmandapp/OsmAnd/files/11123433/logcat.89.log)
[промах 2.zip](https://github.com/osmandapp/OsmAnd/files/11123467/2.zip)

### Steps to reproduce
Open OsmAnd

### Actual result
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/229164599-8871337d-30b4-4f30-b315-ec2cba737127.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Your Environment
OsmAnd Version: 4.3.12, and nightly 27.03
Android/iOS version: Android 13
Device model: Xiaomi 11 Lite 5G

**Comment by meiersa78** [comment]
This one comes from me via email to support, but you mixed something up here.

This error message appears randomly when opening the app. Support already asked me to go through a lot of tests and updates and checking with nightly builds - nothing works. The error shows up randomly.

But that's it. The app ALWAYS runs smoothly and flawlessly on rendering version 2. Contrary to what the error message says, the settings do never return to version 1 automatically. They always remain on version 2 and it always works.

So this error message is just that - a message. There is never really an error that would impair the functionality of the app.

Also, my device is the Xiaomi 11 Lite 5G NE (correction).

**Comment by vshcherb** [comment]
I think that issue with dialog is fixed in 4.4 please try new release
