### ISSUE TITLE
Toggle on/off zoom buttons

### ISSUE THREAD

**Issue by duiveldoder** [osmandapp/OsmAnd#16866]
I'm requesting this for 2 reason:

- I honestly never ever in all these years used these buttons, the sparse space on phone-displays every unnecessary icon should be able to toggled off.
- OSMAnd is one of my favorite apps, because of the fact the whole screen/windows/drawers/icons can be configured by us, the users. It's totally configurable, so why not complete it by the finishing touch - that we can also configure to toggle on/off these zoom buttons?

Thank you for your consideration

**Comment by mikehgentry** [comment]
Duplicate of #4117

**Comment by duiveldoder** [comment]
Then I'll close it here
