### ISSUE TITLE
No weather layer anymore

### ISSUE THREAD

**Issue by Anthiel** [osmandapp/OsmAnd#16868]
Hello,
I'm using Osmand pro since yesterday and i'm not able to see the different layer of weather on the map (I can see the circle around the zone of rain for example, but not the layer with color).
Regards

### Description
No weather layer on the map

### Steps to reproduce
Weather app, and activate layers

### Actual result
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/44339217/229345632-24e66895-80ad-4ffa-bebf-986c062ed0ad.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/44339217/229345634-bffabcb3-dc8d-4a8f-aa4a-bfbfc2d2709d.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  
You can see the circle of rain area, but no color layer.

### Expected result

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/44339217/229345664-66377e53-c2ad-4605-b1c1-6038795b34f0.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Your Environment
OsmAnd Version: 4.4.6
Android/iOS version: Android
Device model: Samsung tab active3

**Comment by Zirochkabila** [comment]
@Anthiel Tested on version 4.4.6 and nightly version from 02.04 - weather layers are displayed.
 
Please attach the log file
Also, try reinstalling the app. But, make a backup beforehand (just in case).

**Comment by Anthiel** [comment]
Very weird thing here: 
I tried to move the storage folder from my SD card to internal storage, and once the migration of data done, the weather layer appeared on the map!

**Comment by Zirochkabila** [comment]
@Anthiel Perhaps it was because OsmAnd did not have access to the folder on the memory card

**Comment by Anthiel** [comment]
the maps (on the SD card) were well displayed :/

**Comment by plicplocplicploc** [comment]
I'm having the same issue. OsmAnd~ 4.4.7 (f-droid). I tried moving data storage locations (from external storage to internal app memory and back). The weather data is there (displayed in the top right corner) but the layers just won't show.

The log shows PLENTY of such lines:
```
08-06 20:05:03.272 15722 20777 E net.osmand.core:native: Failed rasterize weather tile 64x43x7
08-06 20:05:03.273 15722 20777 E net.osmand.core:native: Failed to create tile image of non rasterized weather tile 64x43x7
```

**Comment by XandrexOSM** [comment]
hello @Anthiel , can you please test with a 4.5.x version, and tell us if the bug remains?

**Comment by Sonwon1** [comment]
This may have a connection to Osmand not being able to use the Shared storage. When I try to give it access it tells me No Osmand data found in the slected folder. Please try again and then it loops.

**Comment by vshcherb** [comment]
Bug was not reproduced on release version, so unfortunately we can't fix.
