### ISSUE TITLE
Missing road sections

### ISSUE THREAD

**Issue by Gizmot** [osmandapp/Osmand#1686]
OSM Data is ok
**Note that this is not a display issue. Roads are gone for navigation**
at low zoom, everything looks good
![screenshot_2015-09-12-21-24-27](https://cloud.githubusercontent.com/assets/13919997/9835528/01ea88f0-59be-11e5-9369-728629bd36c5.png)

at higher zoom level, highway 401, road CR5, and lot of others roads are gone. 
![screenshot_2015-09-12-21-24-47](https://cloud.githubusercontent.com/assets/13919997/9835529/01f36826-59be-11e5-842c-0c7e55cc9c39.png)

**Comment by utack** [comment]
I can confirm this, it happens noticeably often.
Please tell me if you need a example with map+area+zoomlevel to reproduce.

**Comment by sonora** [comment]
We generally have 2 different reasons why this happens:
- Issues at map creation time (world basemap mpstly), likely the cause for all issues observed at overview zoom levels
- Issues at rendering time (usually affects detail screens with "crowded" map sections). For this case, I would be interested if the issue disappears by testing these 2 settings: Use Map style "Touring view", and in addition under "Map configuration" select the "Details / More details" tick box.

**Comment by utack** [comment]
Touring and more detail did not help in my case.

**Comment by bparmentier** [comment]
Same issue here, but not specifically when zooming. At a same zoom level, some roads can (dis-)appear just by moving the map.

With the road:

![screenshot_2015-09-14-15-36-34](https://cloud.githubusercontent.com/assets/2833843/9851289/322ddbee-5af8-11e5-94a9-c586eeea2527.png)

After moving the map a bit on the left, the road disappear:

![screenshot_2015-09-14-15-38-49](https://cloud.githubusercontent.com/assets/2833843/9851288/322c626e-5af8-11e5-82f3-23fe5ff96b95.png)

**Comment by Gizmot** [comment]
changing these settings did nothing. As I said in bold above:
Note that this is not a display issue. Roads are gone for navigation

**Comment by sonora** [comment]
Yes, true, I can confirm this, I have now also found places where missing road segments kept routes from correctly being calculated. Looks like a (new, I think) map creation issue we currently have ...

**Comment by vshcherb** [comment]
I think the issue is related to OSM boundaries we use to create regions, let us check.

**Comment by xmd5a2** [comment]
It was boundary (poly) issue. Map will be regenerated soon.
