### ISSUE TITLE
CH maps from 2023-04-01 - full map outdated, roads-only buggy

### ISSUE THREAD

**Issue by vmicho** [osmandapp/OsmAnd#16872]
### Description
The 1st April maps update from Switzerland are buggy
CH Full map: looks like 1 month old. Together with live updates (that start from 1st April) I cannot see an up-to-date map
CH Roads-only map: visible only at certain (from-to 10-20km scale) zoom level: too close -> blank, too far -> blank

I've removed the world overview just in case - this one is the only I can get working in the region.
For comparison, older map like 'Germany - North Rhine-Westphalia' from 2021 is still working fine, also Thuringia from 2021-10 road-only is fine.

Calculating a navigation route works fine (on roads-only map), but I cannot see the map.
I did not check other maps.

Quick update: updated Thuringia road-only to 2023-04 -> looks fine
updated North Rhine-Westphalia to 2023-04 -> also OK
Looks like issue with CH for now.

### Steps to reproduce
update CH to 2023-04

### Your Environment
OsmAnd Version: 4.3.12
Android/iOS version: android 11
Device model: xi mi8

**Comment by pebogufi** [comment]
I downloaded it at 2023-04-02 after  about 16:00, it looks ok,
Just try again.

**Comment by Zirochkabila** [comment]
@vmicho This could be due to technical work being done on the server today

**Comment by vmicho** [comment]
Hi
Deleted and redownloaded. Still not working.
I do not see 2 weeks old features inside.
I've additionally updated Slovakia map - same, 18 days features are not inside.
The maps 2023-04-01 are supposed to contain everything till 2023-03-31 I suppose?

**Comment by Famlam** [comment]
Same for Netherlands - Gelderland

**Comment by marcor** [comment]
OsmAnd~ 4.3.12 on Android 12L

The latest offline standard map for Italy:Emilia-Romagna is missing some edits I uploaded to OSM in march. For example this one: https://www.openstreetmap.org/way/85625371#map=14/44.6066/9.9976

**Comment by cebderby** [comment]
Same for UK including at least East Midlands, West Midlands, Greater London - known edits during March are not showing as changed in 01Apr23 map update.  Have tried deleting and re-downloading map but no difference.  (And same with vsn 4.3.x/4.4.x app before/after update, as would be expected).

**Comment by scaidermern** [comment]
Milestone 4.5? Does that mean we have to wait for the next major app version before we have up-to-date maps again? 🤔

**Comment by Zirochkabila** [comment]
@scaidermern This will be fixed in the coming days

**Comment by vshcherb** [comment]
No 4.4 (probably final release already) is out so we now we work in 4.5 milestone .
Backend milestones are irrelevant they will be fixed in parallel.

We've started map regeneration, so tomorrow should be maps available. But there is an issue they won't show in updates...

**Comment by verdulo** [comment]
> We've started map regeneration, so tomorrow should be maps available. But there is an issue they won't show in updates...

Why don't you regenerate maps with slightly later date, for example 2023-04-01 00:05?

**Comment by scaidermern** [comment]
> New maps were regenerated with 00:001

Yet there is no map update available 🤔

**Comment by Famlam** [comment]
Removing and redownloading worked for the region I'm in, but indeed, no automatic update

**Comment by vshcherb** [comment]
Looks like there is an issue with comparision in Android - https://download.osmand.net/indexes.xml 
```
<region type="map" date="01.04.2023" size="86.3" targetsize="165.2" containerSize="90504908" contentSize="173222819" description="Map, Roads, POI, Transport, Address data for Germany berlin europe" free="false" name="Germany_berlin_europe_2.obf.zip" timestamp="1680307260000"/>
```
Timestamp has changed from 1680307200000 -> 1680307260000

**Comment by EugeneZmeuk** [comment]
After #16902,  all maps (not only standard maps) have status for updating:

![telegram-cloud-photo-size-2-5294236341753727901-y](https://user-images.githubusercontent.com/44466116/230331791-66c9ba3c-155d-465c-ae39-5c5ed83ebda7.jpg)  
![telegram-cloud-photo-size-2-5294373742052492132-y](https://user-images.githubusercontent.com/44466116/230331816-293866a7-cf3e-4244-9025-c88b228ba3f9.jpg)

**Comment by vshcherb** [comment]
Issue fixed

**Comment by aceman444** [comment]
Redownload map on 6th Apr also solved the problem for me. The map files have changed when though they still show 1st Apr as date.

Thanks
