### ISSUE TITLE
Bicycle navigation: voice instructions come too late

### ISSUE THREAD

**Issue by vmicho** [osmandapp/OsmAnd#16876]
### Description
When in bicycle navigation, the voice instructions come usually too late.
e.g.: 20m before roundabout I get the instruction "in 40m enter a roundabout". When on roundabout, "take the 1st exit" come basically at the exit point. Similarly turning instructions on a regular crossroads come like 1 second before turning.
That's all too late.

Note: did not check with pedestrian navigation, had no issues if I remember correctly (mostly because the speeds are much slower).

### Steps to reproduce
Can be tested in navigation simulation directly in osmand.

E.g.: use this example route through a roundabout at 48.17794N,14.01672E
(https://www.openstreetmap.org/#map=19/48.17776/14.01684)

Example:
![Screenshot_20230402-183539_OsmAnd+](https://user-images.githubusercontent.com/66125746/229366444-aa64da81-b2d3-470c-8d34-0e7e976265d8.png)

### Expected result
Instructions should come sooner.

### Your Environment
OsmAnd Version: 4.3.12
Android/iOS version: android 11
Device model: mi8

**Comment by Zirochkabila** [comment]
@vmicho Try to update OsmAnd and change this settings https://osmand.net/docs/user/navigation/voice-navigation#announcement-time

**Comment by vmicho** [comment]
Well I've found that setting before. But it is at the default Normal and never touched that. At least that one (Normal) should work reasonably out of the box.

**Comment by Zirochkabila** [comment]
@vmicho I checked with the default profile settings - as you can see in the video, the voice prompts are quite timely.
Even more so if you increase Announcement time


https://user-images.githubusercontent.com/104760013/230427090-d0fb9ecb-0154-47b3-bff7-c51f8c8090fa.mp4
