### ISSUE TITLE
Lapland (Finland) map missing on Android

### ISSUE THREAD

**Issue by rhtenhove** [osmandapp/OsmAnd#16883]
### Description

Just bought OsmAnd+ on Android after being happy with it on iOS. When routing through Finland, even with the full (Standard) map downloaded, I noticed details were missing.

It appears (at least) the Lapland part of the map is empty (0.00MB).

On iOS it works perfectly fine, but the map regions are also different. The Lapland region is called Regional State Administrative Agency for Northern Finland instead, which in turn contains Lapland.

Related to #6211

### Steps to reproduce

1. Have Android Phone
2. Install OsmAnd+ from Play Store
3. Get Finland map
4. Go to Lapland area, and notice all details are missing

### Actual result

|  |  |
| - | - |
![Screenshot_2023-04-03-18-48-56-74_014aeb6b5e04ee7837dcdaecc5244511](https://user-images.githubusercontent.com/10206967/229575838-f56b472c-4cd1-4578-bac9-f6e5aa5b3dab.jpg)  |  ![Screenshot_2023-04-03-18-49-03-53_014aeb6b5e04ee7837dcdaecc5244511](https://user-images.githubusercontent.com/10206967/229575844-3745f27a-e0c2-4f44-8bb2-64acc44b2493.jpg) |

### Expected result

Like on iOS:

|  |  |
| - | - |
| ![signal-2023-04-03-184844_002](https://user-images.githubusercontent.com/10206967/229575816-f4682c29-674e-4c64-8f64-f59934231d0b.jpeg) | ![signal-2023-04-03-184824_002](https://user-images.githubusercontent.com/10206967/229575821-3681fc12-6961-4d30-9c7a-8d5a8f4f5144.png) |

### Your Environment
OsmAnd Version Android/iOS: 4.4.6 / 4.3.5
Android/iOS version: 12 / 16.4
Device model: OnePlus 8 Pro / iPhone 12

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#14290mqta, Released: 2023-04-03
4.4.6.15

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/229595234-798c43a5-16b1-4a07-894a-b0147ecada77.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/229595237-c93f4747-dc64-4cb3-bdac-44a451d12b80.jpeg"  width="500" height="auto"/> </th>
  </tr>
</table>

**Comment by rhtenhove** [comment]
The file appears to have been updated april 1st, and is indeed empty: https://builder.osmand.net/osm-extract/finland_lapland_europe/

A workaround for Android is to open the .pbf file in that index in OsmAnd Map Creator (Create .obf file from osm file), and copy the resulting .obf file to `\Android\data\net.osmand.plus\files`. It will appear in the Maps download / Local menu after a refresh, and will work as expected.

**Comment by mnalis** [comment]
> The file appears to have been updated april 1st, and is indeed empty: https://builder.osmand.net/osm-extract/finland_lapland_europe/

it seems to have been regenerated today:

```
[finland_lapland_europe.pbf]                         04-Apr-2023 07:58            42828027
```

**Comment by Zirochkabila** [comment]
@rhtenhove Please check if the following has been restored - looks like restored

**Comment by rhtenhove** [comment]
Lapland is still broken in the full Standard map. It can however now be fixed by downloading the separate region after this regeneration

**Comment by Zirochkabila** [comment]
@rhtenhove What do you mean by broken map?
Today I compared a standard map of Finland and a map of a separate region (Lapland), using the example of the city of Rovaniemi - map looked identical

**Comment by rhtenhove** [comment]
Noticed the size of the standard map had changed (with about the size of the Lapland region), but didn't indicate an update. After removal and redownload, I no longer need the Lapland region to see all its details!

Awesome 👍  all good now. Thanks for whomever did the magic! 😄
