### ISSUE TITLE
Less labels when 3D Enable even in 2D mode

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#16881]
## Description
Contour lines label is missing when **Enable 3D Maps** is On in **OsmAnd Development** plugin.

### How to reproduce
* Download **Standard**, **Contour lines** and **Heightmap** for Georgia 
* Turn on all Heightmap related options in **Menu** – **Plugins** – **OsmAnd Development** – **Settings**.
* Go to `41.5138417, 41.7475876`
<table style="width:100%">
  <tr>
    <th colspan=2>Androd</th>
  </tr>
  <tr>
    <th>3D – Off</th>
    <th>3D – On</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/229489361-c99fdcd8-0399-45ea-a220-c6bb2277e63c.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/229489383-fc3099e5-a15e-4bd5-8f7a-80902fe9a82a.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#35926m, Released: 2023-05-11
4.4.8.7

- [ ] Labels are still displayed in a smaller number
- [ ] Part of the elevation map is missing (iOS)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/e78849fa-6404-4d87-84e6-758fa9298348"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/a640bc79-6bb0-4a70-b240-9eeccc6f4b43"  width="500" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
Todo:
- Short labels elevation (3-4 symbols) should be flat similar to 2D case.

**Comment by Zirochkabila** [comment]
I see no changes - the result is the same as in the previous comment

**Comment by vshcherb** [comment]
@Zirochkabila  please provide 2  examples (android) same place and same phone (!) 3d enabled on / off

**Comment by cepprice** [comment]
@vshcherb Threshold still has to be removed for short texts, @Zirochkabila is right
