### ISSUE TITLE
Truck profile is not considering "delivery" restrictions

### ISSUE THREAD

**Issue by Mannivu** [osmandapp/OsmAnd#16882]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

I was using the "Truck" profile, having set the Vehicle information as such: Weight - 15t; Width - 3m; Length - 9m

### Start and end points

Starting Point: Via Evangelista Torricelli, Brignano Gera d'Adda
Ending Point: Via vecchia fornace, Bariano

### Actual and expected routes

The route suggested by OSMand tells the user to pass in Pagazzano, using the [SP129 ](https://www.openstreetmap.org/way/605867510) road that has a `hgv=delivery` restriction, but this route isn't for a delivery inside that town, so the routing engine should avoid that road.

### Is this a regression?

I don't think this is a regression

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>
OsmAnd+ 4.4.6
</code></pre>

**Device and Android/iOS version:**
Xiaomi Redmi Note 11 Pro; Android 12 SP1A.210812.016; MIUI 13.0.3.0(SGDEUXM)

**Maps used (online or offline):**

- [X] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**
No

**Comment by dmpr0** [comment]
Hello! 
Current release version of OsmAnd doesn't support `hgv=delivery`. It should be working in the latest nightly builds. We are working to add few more truck related tags.
* `maxweight:hgv=`
* [maxweightrating](https://wiki.openstreetmap.org/wiki/Key:maxweightrating) `proposed`
* [maxweightrating:hgv](https://wiki.openstreetmap.org/wiki/Key:maxweightrating:hgv)
* `hgv=delivery`
* [maxspeed:hgv](https://wiki.openstreetmap.org/wiki/Key:maxspeed:hgv)

**Comment by Mannivu** [comment]
Oh, great! I didn't know about the nightly version.

**Comment by Zirochkabila** [comment]
@Mannivu  did you manage to check in the nightly version?
https://osmand.net/docs/versions/nightly_versions

**Comment by Mannivu** [comment]
Hi @Zirochkabila I've just checked the nightly version and the route proposed is what I was expecting. I'll close this issue.
