### ISSUE TITLE
3D gestures: pan, zoom, rotate

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#16887]
Next gestures work incorrectly with 3D relief function:
- tilt (by two fingers gesture) - does not always work correctly.
- moving (by one finger gesture).

### Steps to reproduce

- Enable OsmAnd development plugin (switch on 3D function).
- Download Heightmap
- Try to tilt the map by two fingers

### Your Environment
OsmAnd Version:  4.5.0 #14292
Android/iOS version: Android 12
Device model: Samsung S10e

**Comment by vshcherb** [comment]
# Review
- [ ] Fix bug with sudden zoom
- [ ] Add rotate / zoom gesture with fixed 2 fingers

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0
It is very difficult to change the tilt
Similar behavior has already been discussed https://github.com/osmandapp/OsmAnd/discussions/16836#discussioncomment-5764948




https://user-images.githubusercontent.com/104760013/236261880-ac548c64-76d1-4fc9-8518-34961503f776.mp4
