### ISSUE TITLE
map files of 1.4.2023 do not contain changes from March 2023

### ISSUE THREAD

**Issue by aceman444** [osmandapp/OsmAnd#16884]
The currently generated maps dated 1st April 2023 do not contain changes made in March 2023. The files are not identical to maps of 1st March 2023, but the size increase is very small. Something went wrong here.

**Comment by sanketgarade** [comment]
Observed the same for Maharashtra, India. 

1 April 2023 map update does not contain changes done in March 2023.

**Comment by aceman444** [comment]
Yes, looks like duplicate, thanks.
