### ISSUE TITLE
Flooding map (Android & iOS)

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16898]
### Description
Flooding the map

### Steps to reproduce

- Find this place `61.99255° N, 6.15541° W` and `61.99255° N, 6.15541° W`
- Zooming to 5 and 3 level

### Actual result
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/230085728-bdc28c69-f10d-43da-a668-06b8aeccc006.jpeg"  width="240" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/230085737-f051076f-0b4a-44b9-a66f-332434c0f54e.jpeg"  width="400" height="auto"/> </th>
  </tr>
</table>  

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/230086071-4c25a371-d96d-4709-9244-95976575a5f3.jpeg"  width="240" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/230086074-b4fd5fea-efc5-4d9c-a897-d28de6e7dbd0.jpeg"  width="400" height="auto"/> </th>
  </tr>
</table>  

### Expected result
Without flooding

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#14294mqta, Released: 2023-04-05 & 4.4.6.15
Android/iOS version: Android 12 & iOS 15.7.3
Device model: Poco x3 & iPad mini 4

**Comment by Zirochkabila** [comment]
`44.16755° N, 76.41661° W`


https://user-images.githubusercontent.com/104760013/231510124-695cba9e-f895-4238-a990-0273dbe979fa.mp4

**Comment by Zirochkabila** [comment]
`40.739246, 13.998950`

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><video source src="https://user-images.githubusercontent.com/104760013/235345497-b478db19-0171-410d-8387-27d673ac08b8.mp4"  width="600" height="auto"/></td>
    <td><video source src="https://user-images.githubusercontent.com/104760013/235345491-5aff3c96-b96f-4787-ba0f-56557aee354a.mp4"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by dmpr0** [comment]
https://www.openstreetmap.org/search?query=Procida#map=12/40.7600/14.0414
<table style="width:100%">
  <tr>
    <th>Android</th>
    <th>iOS</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/235859334-bb10018b-d01b-4677-b613-1799b655b8ab.jpg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/235859941-b8b571e2-7759-4747-afaa-0808348b3308.PNG"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
https://www.openstreetmap.org/way/42728613 - problematic clockwise / anticlockwise

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#50m, Released: 2023-05-19
World overview map needs to download

`17.01868° N, 81.08617° E`

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/b1af10ee-6be6-4e1c-b8d4-a135aada5298"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by ivanPyrohivskyi** [comment]
[Polygon for 12 zoom (oversymplified)](https://github.com/osmandapp/OsmAnd/files/11529656/naumov.csv)
![Screenshot 2023-05-22 at 12 53 48](https://github.com/osmandapp/OsmAnd/assets/1040293/50a5a4b9-bed1-43dc-a3dd-fb2c60127238)

[Polygon for 13 zoom (normal)](https://github.com/osmandapp/OsmAnd/files/11529674/naumov2.csv)
![Screenshot 2023-05-22 at 12 54 49](https://github.com/osmandapp/OsmAnd/assets/1040293/2f6215b5-2304-45fd-8324-f1e17fde82d9)

**Comment by dmpr0** [comment]
<table style="width:100%">
  <tr>
    <th colspan=2>61.99255° N, 6.15541° W</th>
  </tr>
  <tr>
    <th>Android</th>
    <th>iOS</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/82b74c28-a339-45f6-b543-6bd2a1714ab1"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/b733925f-61f1-4295-92b7-675a3d069d93"  width="300" height="auto"/> </td>
  </tr>
</table>
