### ISSUE TITLE
Waterway:canal not displayed

### ISSUE THREAD

**Issue by Gizmot** [osmandapp/Osmand#1689]
Middle area is the St-Lawrence seaway. This is water

![screenshot_2015-09-13-13-05-48](https://cloud.githubusercontent.com/assets/13919997/9837782/801fb326-5a18-11e5-8fce-d974f3a7caf9.png)

**Comment by xmd5a2** [comment]
According to wiki waterway=canal should not be used on areas
See https://wiki.openstreetmap.org/wiki/Tag:waterway%3Dcanal

**Comment by RicoZ-OSM** [comment]
indeed, the area should be drawn with natural=water+water=canal or one of the alternatives.
