### ISSUE TITLE
OsmAnd 4.4: Map orientation no longer respects "North is up (fixed)"

### ISSUE THREAD

**Issue by Zyolix** [osmandapp/OsmAnd#16893]
### Description
Even if rotation mode "North is up (fixed)" is selected, OsmAnd 4.4 tries to identify rotation gestures and automatically rotates the display and switches to "Manually rotated (fixed)" if it believes to notice a rotation gesture.

This is bad behavior because the two-finger scaling gesture is easily misinterpreted as a slight rotation gesture and OsmAnd regularly switches to "Manually rotated (fixed)" even if this is not intended and wanted by the user.

As it is now, there is basically no behavior difference between "North is up (fixed)" and "Manually rotated (fixed)". In either mode OsmAnd reacts on perceived rotation gestures and rotates the screen, even if the user intentionally wants to keep the map persistently in north orientation.

### Steps to reproduce
Select rotation mode "North is up (fixed)" and apply a rotation gesture

### Actual result
The map orientation gets rotated and the rotation mode is automatically switched to "Manually rotated (fixed)"

### Expected result
"North is up (fixed)" mode should keep the map strictly in north orientation and ignore rotation gestures until the user intentionally changes the rotation mode to "Manually rotated (fixed)"

### Your Environment
OsmAnd Version: 4.4.6 published 2023-03-31
Android/iOS version: Android 13 (latest patch level)
Device model:  Google Pixel 5

**Comment by Zirochkabila** [comment]
@Zyolix Duplicate https://github.com/osmandapp/OsmAnd/discussions/16836?

**Comment by Zyolix** [comment]
Yes, it is clearly a duplicate of #16836. I haven't looked for older posts on this matter because I personally first noticed it with the 2023-03-31 build and I had not considered that this might have already been noticed and discussed in the beta community. Nevertheless I consider my post a good summary of the situation and user expectation. #16836 is already a little bit cluttered by various discussion branches about history of this feature and changes during the beta-phase.

**Comment by Zyolix** [comment]
Yes, it is clearly a duplicate of #16836. I haven't looked for older posts on this matter because I personally first noticed it with the 2023-03-31 build and I had not considered that this might have already been noticed and discussed in the beta community. Nevertheless I consider my post a good summary of the situation and user expectation. #16836 is already a little bit cluttered by various discussion branches about history of this feature and changes during the beta-phase.

**Comment by GallusMax** [comment]
I dont think its a duplicate of #16836 . In short, its NOT about preventing accidental map rotation, but what is missing since some versions is a true "fixed north" mode as clearly stated above:

Expected result
"North is up (fixed)" mode should keep the map strictly in north orientation and ignore rotation gestures until the user intentionally changes the rotation mode to "Manually rotated (fixed)"

@Zyolix : I pledge for reopening and accepting this as a design issue, in that a previously existing "fixed north" feature is now badly missing.

I currently run 4.5.3, released 2023-06-20, and the map rotation is still slipping from north while zooming or just touching a wet display.

**Comment by GallusMax** [comment]
> Duplicate of #16836

Sorry, #16836 describes the problem without asking for the clear solution of a true fixed north view. So it is _no_ duplicate.

**Comment by mikehgentry** [comment]
Have you actually read it (and yes, that includes the replies)?

It's the same discussion

**Comment by GallusMax** [comment]
> Have you actually read it (and yes, that includes the replies)?
Definitely.
> 
> It's the same discussion

Not quite - because it comes to different solutions. IMHO its no solution to implement a threshold before leaving map north or automagically turn the map. The "north is up" needs to stay fixed, when configured as such.
