### ISSUE TITLE
Search is very slow and results are returned in erratic order

### ISSUE THREAD

**Issue by kevinp2** [osmandapp/OsmAnd#16904]
### Description
Search is very slow in my setup of OsmAnd on iOS with the map of Texas, USA (a large state).  What happens:
a)  It can take up to 2 minutes to find a named place like a store, e.g. Walmart
b)  The results are returned in some random order.  Walmarts will appear that are hundreds of miles away.  The nearest Walmart eventually shows up well after one minute.
c) When the search completes, the results are in the same random order instead of showing the nearest matches first.

### Steps to reproduce
Screen recording video:

https://user-images.githubusercontent.com/609677/230225081-f9ea027c-7e73-4aca-9c4d-14842a2a6b2e.mp4

You will need:
Texas, USA map.
Scroll to or search for the location: 30.20580,-97.85659
Search for **Walmart**

### Actual result
As described above.

### Expected result

1. The nearest Walmart should be displayed in under 10 seconds.
2. Subsequent results should be displayed in increasing order of distance.
3. Walmarts that are closer by should be shown faster than Walmarts that are further away.
4. Walmart is just an example.  The same thing happens for many other stores or locations.

### Your Environment
OsmAnd Version: 4.4.6
iOS version: 16.3.1
Device model: iPhone XR

**Comment by sonora** [comment]
Related:  #16397.  And https://github.com/osmandapp/OsmAnd/issues/16397#issuecomment-1495445487, since also here your search results are obscured by mixing e.g. addres results like "Walmart Drive" in one flat hit list..

**Comment by vshcherb** [comment]
Yes I think it's exactly same issue as Aldi or any other large network chain of POIs - merged to https://github.com/osmandapp/OsmAnd/issues/16397
