### ISSUE TITLE
Elevators as POI overlay not visible

### ISSUE THREAD

**Issue by Strubbl** [osmandapp/OsmAnd#16901]
### Description
I cannot highlight the elevators in the map. 

### Steps to reproduce
Go to Configure Map → POI overlay  → Search  → Type Elevator (in German: Aufzug) → Click the found transport category → Save the filter and activate it for the map

### Actual result
No elevators are highlighted

### Expected result
The POI overlay highlights elevators

### Your Environment
OsmAnd Version: OsmAnd+ 4.4.6
Androidversion: 12
Device model: Motorola Moto G Pro

**Comment by xmd5a2** [comment]
Will be available in may maps
