### ISSUE TITLE
One-way arrows not shown on map with "Touring View" map style

### ISSUE THREAD

**Issue by rene78** [osmandapp/OsmAnd#16900]
### Description
One-way arrows are not visible on the map if _Touring Style_ is selected. This problem is related to https://github.com/osmandapp/OsmAnd/issues/16150
### Steps to reproduce
Configure map --> Map style --> Touring view

### Actual result
No one-way arrows on the map
### Expected result
One-way arrows on the map
### Your Environment
OsmAnd Version: OsmAnd+ 4.4.6
Android/iOS version: Android 13
Device model: Galaxy Z Flip 4

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#14294mqta, Released: 2023-04-05
Arrows are not displayed with V2 rendering

<table style="width:100%">
  <tr>
    <th>V2</th>
    <th>V1</th>
  </tr>
<th><img src="https://user-images.githubusercontent.com/104760013/230136742-7ddc6bb4-8004-4daa-86e7-e911bce63647.jpeg"  width="300" height="auto"/> </th>
<th><img src="https://user-images.githubusercontent.com/104760013/230136760-3225f4d9-e6c3-4c3c-895d-c6a3949e230c.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>
