### ISSUE TITLE
Configure map > Tracks: Add action menu to individual tracks

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#16915]
For a more complete user experience, we should add the 3-dots menu for individual track actions to facilitate: `Show on map,` `Rename`, `Move`, `Share`.

(We have the code to port already under  MyPlaces > Tracks.)

`Show on map` is the most pressing of these, screen does currently not facilitate to find out where any individual track is actually located, a rather common use case.

**Comment by dmpr0** [comment]
Unfortunately we don't have plans to add additional menu for tracks on the screen designed to control track visibility on the map.

**Comment by sonora** [comment]
Thanks for commenting. It's a pity because it could be a cool enhancement, maybe we could at least put it in our backlog?

**Comment by dmpr0** [comment]
> Thanks for commenting. It's a pity because it could be a cool enhancement, maybe we could at least put it in our backlog?

Unfortunately we don't have plans to add additional menu for tracks on the screen designed to control track visibility on the map. But we put in our backlog redesign of Tracks screen in My Places, where all additional menus for Groups, tracks and any item will be present.

**Comment by vshcherb** [comment]
Because we don't plan to overwhelm UI and add any other extra elements, we will add long tap as a hidden feature and check whether it contradicts or not.

To do: on long tap open context menu or actions list.

**Comment by sonora** [comment]
Yes, cool, thanks!

When you think about it: The fact if a track is visible on the map or not is really just one boolean flag per track. So in the long run maybe we can find an uncomplicated way to not need an entire separate screen for just that

**Comment by sonora** [comment]
The one "individual track action" that's still missing seems "Delete", all others are here now!

**Comment by Rowin63** [comment]
I see, but this button "select all" selects really "all" tracks!
About 1500 here. Thant´s not what I need ;-)

Yes, using it in the subfolder tabs would be great!

**Comment by sonora** [comment]
I have just added the count to the "Select" button (https://github.com/osmandapp/OsmAnd/commit/c86d826a9ef4c6071f40725d2dca7da7b2df4d72), I think it's a very useful enhancement.

**Comment by Rowin63** [comment]
Thanks 👍

**Comment by sonora** [comment]
So we could use a "Select Al" button like that on every subfoldrr tab. Or the other way to achieve what we need would be to include a "Select all" titled checkox line, similar to the one I marked here, on every subfolder tab:

![Screenshot_20230515-204754_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/845735/0a709560-1751-4481-b1cb-4c87656f25f1)

**Comment by Rowin63** [comment]
I don't see it in the latest 4.5.0#28m like you show here, but a checkbox (in one line with the sorting option, left of it?) sounds good 😉

**Comment by sonora** [comment]
Here's where we stand currently with functionality on the 2 Tracks screens:

| Feature  |   | Configure map > Tracks  |  MyPlaces > Tracks |
|---|---|---|---|
| 1 |  Make tracks visible (single select) | x | x |
| 2 | Make tracks visible (folder select)  |   | x |
| 3 | Locate a track and display on map  | x | x |
| 4 | Change track appearance  | x |   |
| 5 | Share tracks | x | x |
| 6 | Import tracks | x | x |
| 7 | Rename tracks | x | x |
| 8 | Move tracks | x | x |
| 9 | Create/rename folders |   | x |
| 10 | Delete tracks |   | x |
| 11 | Search tracks | x | x |

**Comment by Rowin63** [comment]
I want to display the tracks of different folders in a different appearance.
But still I can´t find a way, to edit (color, width, direction arrows, ...) all tracks in a folder, having already others on display.

The only possibility I see (beside doing it one by one...) is:
) go to "my places" and set all tracks in a folder on display
) go to "configure map / tracks" and set the appearance of this now displayed tracks
) remove again all the tracks from display
) go back to "my places" and start over with the next folder

And having already different (coloured) tracks from different folders on display, it´s not possible at all, to edit a selection of tracks (without removing all displayed tracks first!). 

This is a very laborious way. Or do I overlook something?

**Comment by Rowin63** [comment]
And something else:

I set the appearance of a selection of tracks (like: no direction arrows, no start- and finish-symbols, red, fat).
Apply/save it.
Immediately go back in the same menu (set appearance) but what I see is not the actual appearance of the selected tracks, but I see start- and finish-symbols activated, and a colour and thickness that does not accord to the selected tracks.

This is very complicating too. 
If now I just want to change ONE of the settings, I HAVE TO REMEMBER ALL the other settings of the displayed tracks and set them AGAIN, ortherwise all other settings will be changed back to something I dont want (the app does´nt recognize the selected track´s settings). Confusing.

**Comment by Rowin63** [comment]
Sorry, I wasn't concrete enough.
It's possible one by one. But no way to select all tracks in a folder (via configure map / tracks) and if you have a selection of tracks already on display, you have to take all of them off display before.

I'm searching an editing option (not one by one, but folderwise), detached from displaying. Maybe I don't see it...

**Comment by vshcherb** [comment]
@Rowin63 you can select all by single tap in selection mode tick

**Comment by vshcherb** [comment]
@sonora this issue is outdated? 
Select all is another task. I didn't find anything critical yet https://github.com/osmandapp/OsmAnd/issues/16913

**Comment by Rowin63** [comment]
> @Rowin63 you can select all by single tap in selection mode tick

There is no "selection mode" in the "configure maps / tracks"-menu...? 
I only see a "hide all / deselect all" button?

**Comment by vshcherb** [comment]
It's only possible in Tracks screen this one is not designed for that

**Comment by Rowin63** [comment]
> It's only possible in Tracks screen this one is not designed for that

Oh, that´s good (wasn´t always like that)!
In this menu "my places / tracks" (now?) it is possible, to edit the appearance of a selection of tracks without (!) affecting all other displayed tracks! That´s great 👍

(please consider a "select all in a folder" - option in "configure map/tracks", thanks...)

**Comment by sonora** [comment]
> @sonora this issue is outdated? Select all is another task. I didn't find anything critical yet #16913

Yes, I think this issue has become solved over time. Thanks!
