### ISSUE TITLE
Routing: Wrong fastest route take a much longer route in the Netherlands.

### ISSUE THREAD

**Issue by AllroadsNL** [osmandapp/Osmand#1691]
This is what was planned. two routepoints
Car fastest.
http://osrm.at/fob
https://graphhopper.com/maps/?point=52.710403%2C5.804043&point=52.693721%2C5.173756&locale=nl-NL&layer=Omniscale

It is about going south on the motorway, Osmand does not take the bridge on the Muntweg Emmeloord just 138 m and goes south, but it goes north and then turn around on the next exit
That is a extra tour of 9 km (-138m), so much time lost, not the fastest solution.

![screenshot_2015-09-13-11-41-26](https://cloud.githubusercontent.com/assets/8817345/9845337/6a98d980-5aca-11e5-8ca8-5597c7b83c55.png)
![screenshot_2015-09-13-11-41-41](https://cloud.githubusercontent.com/assets/8817345/9845336/6a978832-5aca-11e5-811e-7ba011359198.png)

**Comment by vshcherb** [comment]
Can't really reproduce it with latest maps https://www.dropbox.com/s/inu5hizzwfmm27f/Screenshot%202015-09-20%2019.34.58.png?dl=0, may be special configuration is used or the maps are different.
