### ISSUE TITLE
Add information about the date of the map upload

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16910]
### Description
The Android version does not display information about the date of map download

- [x] Display information about downloaded maps (as it is implemented in iOS)

### Steps to reproduce
Menu > Download maps > Local > Select any map

### Actual result

https://user-images.githubusercontent.com/104760013/230425113-32c9d41f-b516-4b08-af95-668dc52acb16.mp4

### Expected result

https://user-images.githubusercontent.com/104760013/230425217-8938a639-4c73-4197-87e3-c23c278fc867.mp4

**Comment by dmpr0** [comment]
## Review 

> Description
> The Android version does not display information about the date of map download
> 
>  Display information about downloaded maps (as it is implemented in iOS)
> 

* I can't find described task in builds.
- [ ]  Time with hours isn't visible
