### ISSUE TITLE
regression/nightlies: eats battery

### ISSUE THREAD

**Issue by RicoZ-OSM** [osmandapp/Osmand#1692]
Hi, downloaded the nightly on Sept 13th 2015 and notice that it keeps using CPU constantly while in bakcground and supposedly not doing anything. 

I did the normal setup without anything fancy and after that -

Steps to reproduce:
* reboot device (just to be sure it is clean)
* start osmand nightly and hit "home" button without any other actions

watching in os-monitor osmand gets 0.2-0.3% CPU every 3-4 seconds. Utime and Stime also keep steadily increasing. The CPU usage may be low but might keep the device woken up all day.

**Comment by sonora** [comment]
Cannot reproduce on my devices. 9/14 build has on one of them been in the background all day, CPU time adds up to 33 sec so far.

Any more details? Does the OsmAnd background service seem running (notification bar)?

**Comment by RicoZ-OSM** [comment]
No notification bar signs. 

Unistalled/reinstalled the 9/13 build and took a stopwatch. It is now much rarer, had hoped to find some particular interval but have seen 25,30, 50,60 seconds.. don't know how to accurately measure it. Will give CPU time estimates in a few hours.

Does it listen to some kind of broadcasts?

**Comment by RicoZ-OSM** [comment]
It did not accumulate much overnight but  clearly there is something which causes the Osmand nightly to run periodically without any apparent reason.

Would adb logcat tell me anything? Does it listen to some broadcasts?

**Comment by vshcherb** [comment]
It could be related to issue Areg reported, if he gets a skype message then OsmAnd starts up. Mostly I do see that I forget to press Home button from Map screen and if it accidentally turns on, it will never go asleep, but this is technical details and not the issue so far (or a known issue).
