### ISSUE TITLE
OpenGL doesn't support vector icons (map icons pixeled)

### ISSUE THREAD

**Issue by DaanLT** [osmandapp/OsmAnd#16920]
### Description
All of the map icons look very pixelerated.
Please look at screenshots at 100% size

### Steps to reproduce
OsmAnd  - Any profile > Configure map > Map rendering > Text size: 200%

### Actual result
CAR screenshot
![car-scr](https://user-images.githubusercontent.com/128729388/230619550-30bda14f-b2e9-4778-a597-b00940b22282.jpg)
crop:
![car-scr-s](https://user-images.githubusercontent.com/128729388/230622769-1083291d-51c1-4be4-9e87-42ef0a3c779f.jpg)

### Expected result
Phone screenshot
![phone-scr](https://user-images.githubusercontent.com/128729388/230619572-83ba2e5b-5af8-493e-b99c-b9b3154d963c.jpg)
crop:
![phone-scr-s](https://user-images.githubusercontent.com/128729388/230622784-d3e2ecab-39d7-4527-8c1a-0ce79e06a242.jpg)

### Your Environment
OsmAnd Version: 
nighty OsmAnd~ 4.5.0#14304mqta, released 2023-04-07
playmarket OsmAnd 4.4.6, released 2023-03-31
Android/iOS version: 10
Device model: 
car head unit, UIS7862 based (ums512), android 10 (API/SDK 29),
https://gadgetversus.com/processor/unisoc-uis7862-specs/

**Comment by DaanLT** [comment]
nighty OsmAnd~ 4.5.0#14304mqta, released 2023-04-07
better quality screenshot:
![Screenshot_2023-04-07_161208](https://user-images.githubusercontent.com/128729388/230620532-b272a306-2051-43be-97d0-d9d3a42c2fc6.jpg)

**Comment by Zirochkabila** [comment]
@DaanLT Most likely, it's because the screen resolution of your device 
1280 x 720 with a large screen size.
As you can see (in the screenshots you've attached), the pixels are more visible in the image from tablet than in the image from your smartphone.

**Comment by DaanLT** [comment]
Most likely not, text and GUI elements look ok. Looks like higher res svg/bitmaps not used?

**Comment by Zirochkabila** [comment]
It looks like it's all about the screen resolution
The text size on both devices is 300%

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/230918617-65edc1a0-cbeb-490a-b84d-45baca289d8b.jpeg"  width="175" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/230918641-b011e2ec-b325-452e-8bb9-1788974a110a.png"  width="600" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
- [ ] Subway icons are not visible

**Comment by goldfndr** [comment]
osmc_brown_diamond_left is missing (mentioned at pull request)
