### ISSUE TITLE
Part of the motorway is missed 

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#16939]
## Description
Part of the motorway is missed.
* OSM Link – https://www.openstreetmap.org/way/135399878
* Geo –  `48.09261, 11.27510`

<table style="width:100%">
  <tr>
    <th>Android</th>
    <th>iOS</th>
    <th>OSM</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/230908952-eeb9835e-15a1-4681-9409-e4c5bf8b1093.jpg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/230908916-78194e16-8613-411a-a0d8-f5704ff13354.jpg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/230909009-37e74ec2-ffea-43b7-b76c-4c7140c2cafd.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
If install only [a map with part of this road](https://drive.google.com/file/d/1BM8Yq1OHhNCLOP7S-DETZrUvhU17Vo2E/view?usp=sharing), the entire road is displayed


https://user-images.githubusercontent.com/104760013/230911777-516a49f3-4ead-40a4-8b5a-cc95702d0416.mp4

**Comment by xmd5a2** [comment]
OSM extract data (germany_bayern_upper-bavaria_europe.pbf):
```xml
	<way id="135399878" version="2" timestamp="2012-09-13T11:16:37Z" changeset="13094510" uid="496959" user="Robotrino">
		<nd ref="267694"/>
		<nd ref="1486961323"/>
		<nd ref="267696"/>
		<tag k="highway" v="motorway"/>
		<tag k="int_ref" v="E 54"/>
		<tag k="lanes" v="2"/>
		<tag k="maxspeed" v="120"/>
		<tag k="note:name" v="Der reg_name, sowie ggf. der loc_name sind dem zugehörigen Wikipediaartikel entnommen."/>
		<tag k="oneway" v="yes"/>
		<tag k="ref" v="A 96"/>
		<tag k="reg_name" v="Ammerseeautobahn"/>
	</way>
```
Version is 2 which is 11 years old

**Comment by scaidermern** [comment]
Sounds like this could be related to #16935.

**Comment by vshcherb** [comment]
@xmd5a2 please check old versions it was working before

**Comment by ThomasMeister123** [comment]
Maybe the same problem(?)
[https://github.com/osmandapp/OsmAnd/discussions/16980](https://github.com/osmandapp/OsmAnd/discussions/16980)

**Comment by xmd5a2** [comment]
@vshcherb Map extract from Overpass at 2016.01.01:
![Screenshot_2016](https://user-images.githubusercontent.com/5829014/232415276-801c6486-9489-4254-afb0-e9b0cd19ab98.png)
2021.01.01:
![Screenshot_2021](https://user-images.githubusercontent.com/5829014/232415307-3078421c-a2a5-4002-a74c-fd82a6f6f92d.png)
2022.01.01:
![Screenshot_2022](https://user-images.githubusercontent.com/5829014/232416493-2c5a375b-96f8-48fa-8ad3-cafa0e82849d.png)
2023.01.01:
![Screenshot_2023](https://user-images.githubusercontent.com/5829014/232416598-e88a01de-397e-465a-b7fa-582b41bea504.png)

**Comment by ivanPyrohivskyi** [comment]
Need to check data in our current planet (updated) and downloaded from https://planet.openstreetmap.org/pbf/
Better to cut Upper Bavaria pbf and compare.

**Comment by ThomasMeister123** [comment]
How long will it take to fix the map-data?

**Comment by xmd5a2** [comment]
Looks like our planet-latest was not correctly updated. This motorway was not there. I downloaded planet again. This should be fixed in may maps.

**Comment by vshcherb** [comment]
With may maps should be ok. I'm closing issue to send to  review
