### ISSUE TITLE
Older versions of some roads are shown

### ISSUE THREAD

**Issue by Dimitar5555** [osmandapp/OsmAnd#16935]
### Description
There are some roads that (probably) have been modified/deleted years ago but they are shown in OsmAnd in some of their older versions.
### Steps to reproduce
1. Download Bulgaria roads only map (version 1 Apr 2023)
2. Go to 43.41173, 23.21128

You can also check out 43.40432, 23.24903 where you can see a similar problem. 

The same bug appears when using the standard map as well.
### Actual result
There are some roads that overlap existing roads and there are missing sections of other roads. The data is fine on OSM.org.
### Expected result
Everything should look the same way as it looks on OSM.org
### Your Environment
OsmAnd Version: 4.3.12
Android/iOS version: EMUI/Android version 10
Device model: HRY-LX1T
### Screenshots

1st place `43.41173, 23.21128`:
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/19364673/230797511-0906e254-4944-49ac-886f-c3ad98bc8796.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

2nd place `43.40432, 23.24903`:
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/19364673/230797512-5cfbbd0a-8ca8-4716-b45e-39d662733b3c.png"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by scaidermern** [comment]
There was a problem with map generation (#16872). Maps have been regenerated since then but unfortunately OsmAnd failed to notify all users about this. Maybe re-downloading solves your problem?

**Comment by Dimitar5555** [comment]
@scaidermern the issue is still present after redownloading the maps.

**Comment by vshcherb** [comment]
Not sure I think its part of https://github.com/osmandapp/OsmAnd/issues/16939
