### ISSUE TITLE
Unable to select English app language (Android 13)

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#16938]
## Description
After introducing [per-app language preferences for Android 13](https://github.com/osmandapp/OsmAnd-Issues/issues/1585) users, if device language is not English, is unable to set English, in the list `en-rGB` is present https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/res/xml/locales_config.xml/#L30

### How to reproduce
* Open **Device settings** - **Languages & input**, change to Ukrainian 
* Open Settings and then **Languages & input** and then **App languages** and then OsmAnd
* Choose a language.

<img src="https://user-images.githubusercontent.com/9365308/230905974-4b409973-dd0c-4094-8caa-a068ac55022a.jpg"  width="300" height="auto"/>

**Comment by Nine-Tailed** [comment]
On a poco f3 phone with miui global 14.0.1 stock firmware, you cannot select a language for an individual application, since there is no such menu item in the system settings.  The language can only be changed for the entire system.
