### ISSUE TITLE
Cursor at wrong pos after lost GPS pos

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#16932]
### Description
During a hiking tour i record the track.
At the end of the hiking tour i enter into a house and loose GPS pos. 

### Actual result
When i activate the screen, the cursor pos (blue triangle) is at the last pos where screen was on minutes before.

### Expected result
The cursor pos should be at last known GPS pos which is end of hiking tour.

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#14304mqta, veröffentlicht: 2023-04-07
Android version: 12
Device model: Samsung S10

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/18628183/230773532-88b69434-92e9-4e18-8364-ef51ca12264c.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
@pebogufi Do you use Android API or Google services?
Which permission do you set: Allow only while.. or Ask every time?

**Comment by pebogufi** [comment]
- Google play
- access only while..

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#35740m, Released: 2023-04-10 & 4.4.7 too
Battery saver doesn’t restrict app’s activity - function doesn’t help

- Start moving with geolocation activated
- Lock the screen
- After 50m, turn off GPS (simulate GPS signal loss)
- Unlock the screen > The last location on the map is displayed when the screen is locked, not when the GPS signal is lost

_Location icon - when the screen is locked
Arrow - loss of GPS signal
Square - turning on the screen_

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/230964562-c504a367-986c-4c37-ae8e-d908043fb33a.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by scaidermern** [comment]
Can confirm. 30 km track recorded, display is the whole time off. At home, without any GPS reception, OsmAnd jumps to km 8 when pressing the location button. Not to the last known position.

I guess this could be due to the track recording happening in a different service than the main app. Still strange that OsmAnd jumpsuits to a seemingly random point on the track.

OsmAnd 4.4.7, position via Android API.

**Comment by sonora** [comment]
Yes, our Android service ensures navigation and trip recording while the app is not in the foreground, and/or while the device screen is off. But it does not update any auxiliary variables of the app like "Last known position", which the app will use when it resurfaces, and until it receives a new position update.

It is not quite predictable when "Last known position" would have received its last update: Definitely when the app had received a position update while it was in the fireground with the screen on. But possibly in @scaidermem's case it had received a few more CPU cycles later, even while already in the background, not sure.

**Comment by Zirochkabila** [comment]
The situation is similar with track recording.
But my recheck showed that only the actual position is not updated. The track is also recorded in the background - that is, the data is actually saved correctly. The only thing is that the position on the map is not displayed (it freezes) - but, on the other hand, it helps to save battery power when working in the background

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/233846291-120da947-3994-4cad-b6d9-26f2f99d98d4.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/233846293-0ab331d1-e07a-46ed-90dd-c668d76a44e2.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by sonora** [comment]
Well, as I said, it does not really"freeze', the app is simply not running, just the service. We would have to modify the service to update the cached location. Frankly, I'm not convinced it's worth it?

**Comment by pebogufi** [comment]
What about only check the real position when activate (switch on) the screen ?
This is the only situation when the wrong pos is visible.

**Comment by sonora** [comment]
That's what happens. It is my understanding the issue really only happens briefly, until the position  is updated. But it will of course persist longer when inside a building with no reception at the time you re-open the app, and with the cached location then being 'older' than the last location known from the track recording. Or do I misundrrstand the issue report?

**Comment by pebogufi** [comment]
No, you got it.
But if it is not easy to fix, it can be closed. 
For me it more a funny behavior than a bug.

**Comment by scaidermern** [comment]
A possible fix could be: When _stopping_ track recording, the recording service could report the last position to OsmAnd. OsmAnd then updates the last known position (if the one from the recording service is newer). This wouldn't require any additional resource while recording.

Not sure if it is worth implementing, though.

**Comment by vshcherb** [comment]
After long discussion we didn't come up with any solution and decided not to fix
