### ISSUE TITLE
Subscription Promo Pro doesn't activate without internet connection 

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16949]
### Description
Original iOS issue - Android same https://github.com/osmandapp/OsmAnd-iOS/issues/2787

### Your Environment
OsmAnd Version: 4.4.7
Android/iOS version: Android 12
Device model: Poco xe nfc

**Comment by vshcherb** [comment]
Not reproduced.

**Comment by vshcherb** [comment]
Weather doesn't work without internet
