### ISSUE TITLE
Map orientation: use colored icons for UI in General settings

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16940]
### Description
Different colored icons for UI
[iOS isuue](https://github.com/osmandapp/OsmAnd-iOS/issues/2534#issuecomment-1494011953)

### Steps to reproduce

- Menu
- Settings
- Select profile
- General settings

### Actual result
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/230908675-4c99e458-fa13-4081-927a-f5f4c45f03bf.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
Сolor of the icon in the General settings should match the color of the icon in the **Map orientation (priority)** context menu

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#35740m, Released: 2023-04-10
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by nazar-kutz** [comment]
**Fix**
* https://github.com/osmandapp/OsmAnd/pull/16994
