### ISSUE TITLE
Currently recording track does not display if start point is not visible

### ISSUE THREAD

**Issue by SherbetS44105** [osmandapp/OsmAnd#16947]
I noticed that when I'm using OsmAnd on my phone, while recording a track and double checking that all relevant visibilty settings are enabled, I cannot see the currently recording track unless the start point is visible on the map.

![image](https://user-images.githubusercontent.com/56209479/231022526-f8a521a7-fc80-4fb8-9a5d-293ba0536287.png)
![image](https://user-images.githubusercontent.com/56209479/231022538-4cc0debb-9374-4636-9a8f-cdba1c179063.png)

I'm using the latest F-Droid build of OsmAnd for LineageOS, and I'm running it on my Google Pixel 7.

Another user on a different forum told me "recently, i have been having a bug in the newest version of osmand from f-droid where the currently recording track disappears when the start position is not visible on the screen."

This is very annoying when taking several mile bike rides for contributing to OSM, because I cannot keep track of where I've already been.

**Comment by sonora** [comment]
That sounds like #16380 and should have been fuxed. What version number do you have, I guess f-droid may just be behind?

**Comment by Zirochkabila** [comment]
@SherbetS44105 Try to check in this versionhttps://osmand.net/docs/versions/nightly_versions
Should be fixed

**Comment by SherbetS44105** [comment]
F-Droid version I'm using is 4.3.8. I can't test today, but thanks for the nightly link.

**Comment by thomas725** [comment]
Is there anyway to estimate / predict when OsmAnd~ will be updated to 4.4.* in F-Droid?
