### ISSUE TITLE
Support the official cartography of France

### ISSUE THREAD

**Issue by Ujilon** [osmandapp/OsmAnd#16956]
# 🚀 feature request

### Description

Be able to use the official cartography of France, provided by the IGN, the National Geographic Institute

### Describe the solution you'd like

This could be done in two ways, one pretty easy for you (but a bit more complicated for the users), and another one quite easy for the users (but, obviously, a bit more technical for you) :

1 - We can already add our own online maps, thanks to the "Add Online Source" form. For example, here is mine, with an URL provided by the IGN (the hidden part is only my API key) 

![Screenshot_20230412-113406~2](https://user-images.githubusercontent.com/1191833/231420152-874ee2f7-b129-4e6d-8b95-e7168577236b.png)

But unfortunately, it triggers an SSL error on Android < V10, because the CA isn't trusted by Android. Here is the Osmand Log about it :

![Screenshot_20230412-101905](https://user-images.githubusercontent.com/1191833/231420440-b594399d-3243-4bc7-b3b8-9c81d5f50319.png)

After talking about it with the IGN support, they pointed me to this help page : 

https://developer.android.com/training/articles/security-config#TrustingAdditionalCas

With this CA to be added :

http://autorite.certigna.fr/certignarootca.der

I assume it would quickly fix the SSL error.

2 - Alternatively, I would LOVE to be able to select this map automatically, in the map sources list, when we want to add more online maps. Of course, the user would have to create an account on the IGN website, get its own API key, and provide it in Osmand when the map is selected, maybe through a pop-up form, or something like that. It would be extremely smooth :)

### Describe alternatives you've considered

As far as I know, there is no other way to use their tiles in Osmand, and there is absolutely nothing as accurate as their content, in france.

Thank you for your work, Osmand is absolutely amazing ❤️

**Comment by scaidermern** [comment]
Duplicate of #11307?

**Comment by Ujilon** [comment]
> Duplicate of #11307?

That's absolutely correct, sorry I missed this one

**Comment by bellera** [comment]
wxs.ign.fr is deprecated. URL for IGN France topo is:

https://data.geopf.fr/private/wmts?apikey=ign_scan_ws&layer=GEOGRAPHICALGRIDSYSTEMS.MAPS&style=normal&tilematrixset=PM&Service=WMTS&Request=GetTile&Version=1.0.0&Format=image/jpeg&TileMatrix={0}&TileCol={1}&TileRow={2}
