### ISSUE TITLE
Plan route: new point is not visible if Display position is bottom

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16965]
### Description
New point in Plan route is not visible on the map, it seems that map center is shifted under bottom toolbar.

### How to reproduce

* Open **Menu** – **Settings** – **Select profile** – **General settings** – **Display position** set to **Bottom** 
* Open Menu – **Plan a route** – **Create new route**
* Try to add point 

#### Actual result
* Map center is shifted below bottom toolbar
<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/232080994-f25a0e83-71a5-4d10-85b9-361e78ec33fd.jpg"  width="300" height="auto"/> </td>
    <td><video source src="https://user-images.githubusercontent.com/104760013/231768082-abf6187c-590f-45ca-9e6a-53d419fcb9ad.mp4"  width="300" height="auto"/>  </td>
  </tr>
</table>   

#### Expected result
* While opening Plan a route, the map is centered in the middle of the screen so that the place where you add a point is displayed

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#35770m, Released: 2023-04-13
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by paullemmens** [comment]
Confirmed. Somehow the crosshairs to enter a next point are totally not visible (anymore).
