### ISSUE TITLE
Export file misses a lot of info

### ISSUE THREAD

**Issue by letypequividelespoubelles** [osmandapp/OsmAnd#16960]
### Description
When trying to export profile from my old phone and import it to my new phone, a lot of data is missing, like
- favorite
- custom search group
- quick action setup

I have just 
- online maps li,ks
- menu parametrisation
- profil list with profil parametrisation

### Your Environment
OsmAnd Version: FDroid 4.3.12 -> FDroid 4.3.12
Android/iOS version: Android 7.1.2 -> Android 12
Device model: Crosscall Action X3 -> Crosscall Z5

**Comment by dmpr0** [comment]
Please provide file to test.

**Comment by letypequividelespoubelles** [comment]
A file with just favorites : [Export_10-04-23.zip](https://github.com/osmandapp/OsmAnd/files/11213490/Export_10-04-23.zip)

A file with all possible exports (except marks, and maps) : 
[Export_28-03-23.zip](https://github.com/osmandapp/OsmAnd/files/11213501/Export_28-03-23.zip)

**Comment by Velomeloman** [comment]
Fixed #16298

**Comment by sonora** [comment]
Yes, that was an issue in OsmAnd's 4.3 versions. Should be fixed in 4.4.x,

**Comment by letypequividelespoubelles** [comment]
OK perfect, didn't find the other issue.
