### ISSUE TITLE
There are no margins around the edges on the screen for turning on the weather forecast.

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#16961]
### Description
Increase the margins around the edges on the screen for turning on the weather forecast.
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/12549744/231554014-901444fb-c21e-4c34-b508-790ce18aa2e8.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#35766m, Дата выпуска: 2023-04-12
Android/iOS version: 13
Device model: poco f3

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#35770m, Released: 2023-04-13
Same result for the next languages:

1. Basque
2. Belarusian
3. Catalan
4. Esperanto
5. French
6. German
7. Hungarian
8. Italian
9. Japanese
10. Polish
11. Portuguese
12. Portuguese (Brazil)
13. Romanian
14. Russian
15. Sardinian
16. Serbian (Cyrillic)
17. Slovak
18. Slovenian
19. Spanish
20. Spanish (American)
21. Spanish (Argentina)
22. Turkish
23. Ukrainian
