### ISSUE TITLE
Radius Ruler Compass exceeds screen limits

### ISSUE THREAD

**Issue by ManDay** [osmandapp/OsmAnd#16967]
The Radius Ruler's compass in most zoom levels exceeds the screen, as can be seen on the following screenshot:

![Screenshot_20230413-172647_OsmAnd~](https://user-images.githubusercontent.com/1059827/231791780-7b23a892-e929-41e8-b7e0-b01a5fa05491.jpg)

**Comment by ManDay** [comment]
@Zirochkabila yes, and? Notice on the screenshot how the compass (the one circle with degree ticks and the blue compass arrow) is **larger** than the screen width - you can't read the marks at the east and west end; and if the blue compass arrow points east or west, you can't see it. At different zoom levels it can be come even worse than that.

**Comment by dmpr0** [comment]
Distance between circles in radius ruler is equal to map scale.

**Comment by sonora** [comment]
But doesn't @ManDay have a valid point that the degree scale should always be on a ring which is fully visible?

**Comment by ManDay** [comment]
> *But* the compass should automatically adjust to the size of the screen.

I still don't fathom what's so controversial about this... You (sometimes) can't see the compass and "needle", isn't that a bug? 4.3.12 on LineageOS 19-20230404-NIGHTLY-sargo (Google Pixel 3a)

**Comment by ManDay** [comment]
Maybe I didn't express this correctly: The radius ruler does work well and matches the scale well, it *does* adjust to the screen, I just think there is some modulo/integer-rounding mistake when it comes to deciding which of the circles gets the compass.

**Comment by Zirochkabila** [comment]
@ManDay I checked the display of Radius-ruler on Google Pixel 3a with version 4.3.12 - it could not be reproduced.

<img width="945" alt="Screenshot 2023-04-14 at 11 41 40" src="https://user-images.githubusercontent.com/104760013/231992316-0415e003-bfad-4991-a7b0-6782b5b4498a.png">


Try reinstalling the app. This may be a system error (make a backup beforehand, just in case). Alternatively, download the nightly version at https://osmand.net/docs/versions/nightly_versions

**Comment by ManDay** [comment]
Did you understand that this happens only at certain zoom-levels? The code of `getCompassCircleIndex` looks rather suspicious in that regard, because it somehow (wrongly?) manages the question symmetrically (using only one `Min` between V and H) whereas the actual question is assymetric in left/right and top/bottom...

**Comment by ManDay** [comment]
Could https://github.com/osmandapp/OsmAnd/blob/5da18c91d0171b0949d6c53a9a74ac9724f1a731/OsmAnd/src/net/osmand/plus/views/layers/RadiusRulerControlLayer.java#L256 be in the wrong order? If the `minFittingRadius` is smaller than the intended radius, it's already a problem. Multiplying it with a factor > 1 will cause it to be accepted in some cases.

**Comment by sonora** [comment]
I can confirm the issue on my Samsung Xcover 4s, stock Android 11, OsmAnd 4.4.7, with screen magnification set at 100%: The issue occurs at e.g. zoom levels 9, 10, 11, as well as 19, 20, and 21, while the levels in between are ok. So it seems like a bug.

**Comment by ManDay** [comment]
I reckon the coefficient was just a quick solution to account for the drawing space outside of the circle for the compass needle, the north mark, and the heading text - without having to exactly determine their sizes?

Yes, multiplied on the left side :stuck_out_tongue_winking_eye:

**Comment by ManDay** [comment]
I still suspect the code is wrong w.r.t. the symmetry l/r t/b, because it does treat the placement as arbitrary (thus distinguishes between t/b and l/r), but fails to carry that assymetry into the calculation. I think it can't possibly be correct with only one occurrence of `Min`, unless it is a-priori centered. I think this is shown if you set the "Display Position" to "Bottom" instead of "Center" - then the compass goes even further outside of the screen.

**Comment by ManDay** [comment]
![Screenshot_20230414-132527_OsmAnd~](https://user-images.githubusercontent.com/1059827/232020292-2f789a36-c12e-4d8a-b49a-722f6751ab73.jpg)

**Comment by vshcherb** [comment]
> But doesn't @ManDay have a valid point that the degree scale should always be on a ring which is fully visible?
@sonora - no it's not a valid point

**Comment by ManDay** [comment]
@vshcherb if the center is aligned at the bottom, I could understand the reasoning that only the "top" part of it can be visible, because that alignment only makes sense with a rotating map (i.e. compass points up). If the compass is centered and the map is north-oriented (i.e. north points up), it doesn't make sense to crop any particular side, because every side is equally important and it will render the compass entirely useless under some headings.

This is my last comment on this thread. I would encourage some of you to not be so dimissive, although I understand that a large project like yours suffers from silly bugreports at time. In this case the experience has strongly discouraged me from further interaction (which is sad, because OsmAnd is truly fantastic, thanks to you).

**Comment by sonora** [comment]
Just to clarify regarding _"fits purpose of having same scale as map scale"_: I did not mean to change the fact that the ring radii are multiples of the map scale (bar) indicator. I merely meant to suggest placing the degree markers reliably _on the first ring which is fully visible_, instead of on one which is partially cut off.

(And I agree with @ManDay that this is a concern only in the isotropic use case, i.e. where the position marker is set to be the screen center, where our compass is currently unusable when moving in certain directions.)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#35850m, Released: 2023-04-26
I confirm @sonora  comment that before the strange behavior of Ruler on **9,10,11,19,20,21** zoom levels


<table style="width:100%">
  <tr>
    <th>11 > 12</th>
    <th>14 > 15</th>
    <th>8 > 9</th>
    <th>17 > 18 > 19</th>
  </tr>
  <tr>
    <td><video source src="https://user-images.githubusercontent.com/104760013/234587788-f253aa09-1919-4813-bd72-bcbd1b8e4c90.mp4"  width="300" height="auto"/></td>
    <td><video source src="https://user-images.githubusercontent.com/104760013/234587797-9e04f119-99af-4d3f-b110-e48903c05029.mp4"  width="300" height="auto"/> </td>
    <td><video source src="https://user-images.githubusercontent.com/104760013/234587801-31e3e411-49d4-4e26-8648-3b7cc22c6a43.mp4"  width="300" height="auto"/></td>
    <td><video source src="https://user-images.githubusercontent.com/104760013/234587809-bd121d99-e42b-4024-af7d-c65fb1b14370.mp4"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
This is not strange, we have "good numbers" - 1, 2, 5. The difference between 2 and 5 is quite big 2.5, so it produces a jump also there is also a limit on the ruler could be. 

So between 8-9 and 18-19 ruler stays the same on number 2

**Comment by sonora** [comment]
But we seem to always have at least one ring which fits on the screen completely (when the map center is the screen center). Why would we not use the biggest completely displayed ring ,and instead fall back to using a 'broken' ring in some cases, what's the advantage?

**Comment by vshcherb** [comment]
cause it's not consistent with the rule that scale = radius-ruler. 

It might seem strange but once that rule stops working there will be issues why circle very tiny. Cause the scale itself follows the "thumb rule".  "Thumb (rounded to 1/2/5) = scale = radius of main circle"

Also it doesn't say anything whether we should break the rule or reconsider the width of the scale itself.

**Comment by sonora** [comment]
Ah  ok, I just notice we seem to **always** use the _second smallest ring_, i.e. the one with `radius = 2x scalebar` to attach the degree scale. So I guess you mean to say you want to consistently use that ring, while the fact whether it is fully displayed on the screen is secondary to you.

I had not made that connection between which ring to use and if it has 1 or 2 scalebars radius, was more concerned to use a fully visible ring (without changing the thumb rule  of course).  But thanks for explaining!

**Comment by ManDay** [comment]
@sonora since you are happy with the explanation, will you please take a minute to pass it on in terms which I can understand? Because I would love to understand how the user being unable to use the compass in a third of all directions is literally not an issue (or has aforementioned advantage).

Also, I suspect the existence of `getCompassCircleIndex` is the real problem then. Someone erroneously wrote that code with the obvious intention of choosing a circle which fits into the screen, because they didn't consult @vshcherb first, who would have told them that the correct solution is to always use the 2nd circle! :+1:

**Comment by sonora** [comment]
@ManDay Well, "happy with the explanation" is a bit far-fetched :wink:, but I now understand from Victor that the current logic seems to be the degree scale is always and consistently attached to the _second ring from the center_. Not that that would have been been my first priority criterion had I done the coding to select the ring, though. If I had a say I would likely have selected _the largest ring fully visible (when centered)_.
