### ISSUE TITLE
opengl: POIs that have been removed or moved continue to be displayed on some map zooms.

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#16962]
### Description
POIs that have been removed or moved continue to be displayed on some map zooms.
On rendering engine v1 there is no such problem.

### Actual result
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/12549744/231567837-9b389073-2f57-46a6-857c-71139f4517f8.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#35766m, Дата выпуска: 2023-04-12
Android version: 13
Device model: poco f3

**Comment by scaidermern** [comment]
Could be #14920?

**Comment by Nine-Tailed** [comment]
> Could be #14920?

Yhere we are talking about duplication of ways, and here we are talking about nodes.  They seem to work independently of each other.

**Comment by Zirochkabila** [comment]
As shown in the video in the commentary, the approach icon and the “Буханка" icon change their position depending on the zoom https://github.com/osmandapp/OsmAnd/issues/14920#issuecomment-1520700038
