### ISSUE TITLE
Add "Follow system theme" for maps mode

### ISSUE THREAD

**Issue by xmha97** [osmandapp/OsmAnd#16963]
Please add "Follow system theme" for maps mode:

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/23485114/231617127-85410f95-29b4-481a-a56e-e155b11dbb3c.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

 Thanks. 🙏

**Comment by Zirochkabila** [comment]
@xmha97 Try to follow this way: Menu > Settings > Select profile > General settings > App theme

**Comment by vshcherb** [comment]
Duplicate https://github.com/osmandapp/OsmAnd/issues/13998
