### ISSUE TITLE
Glide Ratio Widget

### ISSUE THREAD

**Issue by ManDay** [osmandapp/OsmAnd#16968]
# 🚀 feature request

### Description
I'd like to tentatively propose a simple "Glide Ratio" widget (in analogy to speed, etc.) to make OsmAnd a bit more suitable for Aircraft usage. It could have, as alternative displays:

- Current estimated Glide Ratio from the average over a segment with a configurable distance/time (to adapt to different kind of speeds)
- Glide Ratio to target

**Comment by vshcherb** [comment]
> Glide ratio is the horizontal distance divided by change in altitude. I. For example, if my handglider has a glide ration of 7:1 (7 to 1), then for each foot of altitude lost I travel forward 7 feet. 

https://en.wikipedia.org/wiki/Lift-to-drag_ratio#Glide_ratio

To do: We need to add 2 widgets
1. Glide ratio to target 1st marker 
2. Average glide ratio over time (configurable time) - same as average speed.
Glide ratio formatting:
``` #.# : 1 (7.4 : 1)```

**Comment by ManDay** [comment]
> Average should be calculated as sum covered length / (start - end altitude) - the value could be negative

That's a great idea. I always had a end-point minus start-point in mind, but that wouldn't work if the trajectory is curvy, whereas yours does!

I don't know how feasible that is, but I thought an algorithm which takes the average over the latest, longest segment wherein the GR remained **constant within a threshold**, as opposed to a segment of configurable duration could also be meaningful. What do you think?

**Comment by ManDay** [comment]
Here are two ideas for the icon
 - GR to next WP ![gr_target](https://github.com/osmandapp/OsmAnd/assets/1059827/4acddb3a-ea66-41bc-a5ec-4b14877e91ec)
 - GR ![gr_traject](https://github.com/osmandapp/OsmAnd/assets/1059827/0abb3f11-b6c4-4857-9a1e-afcdadf373f7)

I'm not familiar with making drawables for apps, I used the `widget_sunrise_day.xml`, converted it to SVG with [this website](https://vd.floo.app/) and then used it as basis.

**Comment by dmpr0** [comment]
Icons https://github.com/osmandapp/OsmAnd/commit/6d7a9b92da5fa1b10ce68f142a230d32089df5c5

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/e9812fc1-fc4c-4888-b7ac-d9b53e35b862"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/6dee5443-6db4-4609-b197-417691435809"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by ManDay** [comment]
Took the layman's design and turned it pro, cheers!

**Comment by vshcherb** [comment]
**To do**:
- [ ] Don't display values ```abs(value) >= 150``` - display "1 : 0"
- [ ] On click Glide ratio to widget display - target altitude

@dmpr0
- **On click** Both Average speed / average 
- Add similar Group of widgets **Altitude speed**, - same 2 widgets **Average altitude speed**, **Time to descend to destination** (calculated using elevation difference / average speed)

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/widgets/info-widgets#glide-ratio

**Comment by shurasmiling** [comment]
https://osmand.net/blog/osmand-android-4-6-released/#added-glide-ratio-widgets
Glide ratio to the target. изменить описание

**Comment by shurasmiling** [comment]
https://docs.osmand.net/docs/user/widgets/info-widgets#glide-ratio

**Comment by vshcherb** [comment]
We need to do add 2nd option "Average altitude speed" + "Average glide ratio"

**Comment by EugeneZmeuk** [comment]
**12-04-2024**
- add _Target elevation_ (Glide ratio to target) (by clicking on the widget)
