### ISSUE TITLE
Usablility: When selecting Destinations, facilitate "snap to road"

### ISSUE THREAD

**Issue by RicoZ-OSM** [osmandapp/Osmand#1696]
Two ideas:
- when creating waypoints it could search for nearby roads/crossings and ask if it should "snap"  there
- waypoints could have their own history which could appear after calculating a route, with points sorted by approximate distance to the route. Or perhaps previously used waypoints could be displayed in the overview map with an easy way to select them

**Comment by sonora** [comment]
I like the snapping idea for waypoints, in particular! Much needed feature.

About the "separate history": Not sure if 2 histories would not confuse more than benefit most users ..   :-)

If we really need it, maybe  we could simply add support to make all "history" points visible as tappable points on screen, just like favorites, that would do the trick, I guess. Could be a feature request for our future search screen,

**Comment by RicoZ-OSM** [comment]
I think the tappable history points on screen would be pretty cool..  something similar like what already works with POI search results.

The separate history for waypoints idea was because I have some such points to force particular routes which I prefer for example in times of heavy traffic jams. I would not like to add them to favorites and they are useful exactly only as waypoints. So maybe instead of separate history a separate category to store waypoints?

**Comment by vshcherb** [comment]
2 item is exactly what we have in mind for next waypoint implementation, it is not clear will it be made this release.

About snapping waypoints, I don't really like this idea and don't see a value.

**Comment by RicoZ-OSM** [comment]
One thing that is a hassle and intelligent snapping could possibly improve is that for multi lane roads it can be difficult to hit the correct lane.

**Comment by vshcherb** [comment]
Yes that's annoying, it should be an option, please make a route and pass waypoints on the distance 100-500m. It is needed for other features as well.

**Comment by littlehelper** [comment]
Snapping the marker to the closest object like road, POI etc. automatically would be a solution if no other "snappable" object is close. For my part, I would prefer to have an option to precisely move the marker on my own (see #2199).

In addition, I can imagine to long-tap anywhere on the map to set the marker and Osmand will show me a selection menu where I can select the (closes point of the) road, the POI etc. close to the marker (see #1862, #2178) to finally create a waypoint.

**Comment by sonora** [comment]
Let's consider this in (and merge to) #2765.
