### ISSUE TITLE
bridge areas not shown

### ISSUE THREAD

**Issue by vmicho** [osmandapp/OsmAnd#16974]
### Description
Since v4.4.x the bridge area is not shown:

![image](https://user-images.githubusercontent.com/66125746/231880223-6cae42c0-5cfd-49c1-9871-797aa5021e3a.png)

here is same area screen from 4.3.12:
![image](https://user-images.githubusercontent.com/66125746/231880963-666c58c4-3e5a-4767-83e6-51398ce69453.png)

### Steps to reproduce
See any bridge area

### Your Environment
OsmAnd Version: 4.4.6
Android/iOS version: a11
Device model: mi8

**Comment by sonora** [comment]
https://www.openstreetmap.org/way/1008159395.

Can be observed both with Settings > OsmAnd settings > Map renderer engine > V2 and V1.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#35776m, Released: 2023-04-14
Same result for V1 and V2
[Map here](https://drive.google.com/file/d/1CWC3i0sNhFCWp-rM1DnAhQb0Pvy8zhMA/view?usp=sharing)

<table style="width:100%">
  <tr>
    <th>V1</th>
    <th>V2</th>
  </tr>
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/231984788-bca65c69-62ec-4e73-90b8-b45aa39bd55e.jpeg"  width="300" height="auto"/> </th>
<th><img src="https://user-images.githubusercontent.com/104760013/231984793-93b4bf35-d8c1-4e95-8c9a-296422c0046f.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by xmd5a2** [comment]
Issue was introduced by this commit: https://github.com/osmandapp/OsmAnd-resources/commit/f3989ea65bfbac43a138082196dec29da5cac6a2
Order line of man_made=bridge was moved from `cycle="true"` section of `<order>` to `line` section.
Original issue: https://github.com/osmandapp/OsmAnd/issues/16491
Original object: https://www.openstreetmap.org/way/733835734

**Problematic bridge:** https://www.openstreetmap.org/way/1008159395 (note that this is not multipolygon but way)
obf data:
```
Way Lat 48.744053 Lon 19.140516 types [man_made-bridge (24)] add_types [layer-1(20)] id 129044402579 osmid 1008159395
```
**But bridges that are multipolygons are rendered correctly**: https://www.openstreetmap.org/relation/1907260
![изображение](https://user-images.githubusercontent.com/5829014/232768848-30d338ec-59a9-4e8d-8d03-71f129ff063d.png)
obf data:
```
Area Lat 48.744614 Lon 19.1407 types [man_made-bridge (24), note_tag-yes (32)] add_types [layer-1(20)] Names [name(1) - Третьяковский мост] id 8803905159872 osmid 68780509061
```
Note that in first case object type is **way** but in second it is **area**.

Not clear how this can be fixed. I suppose that my commit should be reverted and original object (https://www.openstreetmap.org/way/733835734) should be split into two ways. Not sure that it is correctly tagged.

**Comment by xmd5a2** [comment]
Fixed by reverting https://github.com/osmandapp/OsmAnd-resources/commit/f3989ea65bfbac43a138082196dec29da5cac6a2

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#35861m, Released: 2023-04-28
4.4.8.3



<table style="width:100%">
  <tr>
    <th>V1</th>
    <th>V2</th>
    <th>iOS</th>
  </tr>
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/235198424-9363d2c5-2ec1-4f18-bce2-5a1c2107879c.jpeg"  width="300" height="auto"/> </th>
<th><img src="https://user-images.githubusercontent.com/104760013/235198438-5145b386-5a58-4a0a-884f-afa27d180464.jpeg"  width="300" height="auto"/> </th>
<th><img src="https://user-images.githubusercontent.com/104760013/235198442-c2ec86f5-4427-4237-af13-7cfb090472eb.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by xmd5a2** [comment]
Looks like OpenGL engine always render ways on the top of polygons, independent of `order` in `<order>` rendering style section

**Comment by vshcherb** [comment]
To do: OpenGL engine always render ways on the top of polygons, independent of order in <order> rendering style section

**Comment by zipav** [comment]
OsmAnd Nightly 4.6.0#939m, released: 2023-10-30

<table style="width:100%">
  <tr>
    <th>V1</th>
    <th>V2</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/379f9369-118e-4df6-9552-02d1d1cebc7b"  width="300" height="auto"/> </th>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/f2accf85-bef7-421a-8720-b564ac8fc81d"  width="300" height="auto"/> </th>
  </tr>
</table>
