### ISSUE TITLE
Chipseal surface is not shown in any color

### ISSUE THREAD

**Issue by averza** [osmandapp/OsmAnd#16973]
Currently, surface=chipseal roads are just white. I think it should be shown in "Paved" or even "Asphalt" color based on the description: https://wiki.openstreetmap.org/wiki/Tag:surface%3Dchipseal

https://osmand.net/assets/images/osmand-surface-smoothness-6ee1fd7ac58f3801caeebbe55bb0a314.png

**Comment by sonora** [comment]
I would agree that it is adequate to depict chipseal like paved, rather than ignoring the tag.

**Comment by Zirochkabila** [comment]
@dmpr0 Check on new maps of Swabia - are already available  `48.0136, 10.7272`
