### ISSUE TITLE
Android Auto: After power change route lost

### ISSUE THREAD

**Issue by thijstravel** [osmandapp/OsmAnd#16977]
Im travelling in offline modus. And everytime i switch off the car, my planned route islost and need to insert it again when i start the car. I try press navigation button. But again route gone after a short brake.

# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

</code></pre>

**Device and Android/iOS version:**

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**

**Comment by Zirochkabila** [comment]
@thijstravel If I understand you correctly, you are talking about Android Auto?
What version of OsmAnd are you using?

**Comment by thijstravel** [comment]
I'm using Pro, latest download. Yes with android auto.


Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#35850m, Released: 2023-04-26

It can be reproduced in the following scenario: **Open AA on computer** > **Build navigation** > **Start navigation** > **Close AA on computer** > **Open AA on computer** > Route lost

If doing this way: **Open AA on computer** > **Build navigation** > **Close AA on computer** > **Open AA on computer** > Route is saved 

That is, the route is lost when closing the AA only if the route navigation has been started - press the "Start" button
