### ISSUE TITLE
national parks not rendered with openGL

### ISSUE THREAD

**Issue by cricri-du-lauragais** [osmandapp/OsmAnd#16976]
polygons that are tagged "boundary=national_park" appear as "leisure=nature_reserve" when using the V1 renderer, as they have for a very long time.
when using the openGL renderer, only the "leisure=nature_reserve" polygons are displayed.

Android many
Device model: many

<table style="width:100%">
  <tr>
    <th>Default style engine V1</th>
    <th>Default style OpenGL</th>
    <th>Custom style (more visibility) engine V1</th>
    <th>Custom style OpenGL</th>
  </tr>
  <tr>
<th><img src="https://user-images.githubusercontent.com/83398215/232018820-65ff59e5-cb9a-4cc6-a67c-2b6aa7513ab7.png"  width="300" height="auto"/> </th>
<th><img src="https://user-images.githubusercontent.com/83398215/232019000-af217fe7-77f5-412e-8040-a3cfc54fe772.png"  width="300" height="auto"/> </th>
<th><img src="https://user-images.githubusercontent.com/83398215/232019160-2d3f41c8-621f-49e3-8276-fb88fdecf015.png"  width="300" height="auto"/> </th>
<th><img src="https://user-images.githubusercontent.com/83398215/232019239-ace7154b-1b39-4cbd-87f2-f325741e2763.png"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#35841m, Released: 2023-04-24
Clear park boundaries and NR markers are displayed only with V1 rendering
`42.8462, 0.1028`
[Nationalpark Pyrenäen](https://www.openstreetmap.org/relation/1024513#map=13/42.8523/0.1159)
 

https://user-images.githubusercontent.com/104760013/234333451-6540024d-a67e-465c-956d-b3c34216ac8e.mp4

**Comment by vshcherb** [comment]
```
Area Lat -85.2297 Lon -181.8734 types [leisure-nature_reserve (709), osmand_nature_reserve-line (710), boundary-national_park (843)] Names [name(2) - Parc national des Pyrénées (cœur), name:de(390) - Nationalpark Pyrenäen, name:es(285) - Parque nacional de los Pirineos, name:eu(346) - Pirinioetako parke nazionala] id 8800289430080 osmid 68752261172

lat/lon : 42.79729 / -0.4390937 , 42.798065 / -0.43682456 , ...
```

**Comment by cepprice** [comment]
Another [example](https://www.openstreetmap.org/relation/1024512) of bug
[Example](https://www.openstreetmap.org/relation/6014846) of `boundary=national_park` without bug

**Comment by vshcherb** [comment]
Similar Bug with https://www.openstreetmap.org/relation/13422106#map=14/50.4137/30.5629 ?

**Comment by dmpr0** [comment]
@ivanPyrohivskyi or @vshcherb please provide details about what was fixed and what in need to be tested.

**Comment by cepprice** [comment]
@dmpr0 Parks above cross two maps. It means polygons of these parks are not closed. In V2 unclosed polygons were not drawn. We added exception for polygons that are tagged `boundary=*` to draw them despite they are not closed.

To test: polygons, partially contained by 2 or more maps, are drawn.

**Comment by cricri-du-lauragais** [comment]
it's been working with nightly for about 2 weeks and with beta 4.5.1 ;)
thanks for the work :)

**Comment by vshcherb** [comment]
@dmpr0 fixed parks in the link https://www.openstreetmap.org/relation/1024513#map=13/42.8523/0.1159 and examples from description
