### ISSUE TITLE
Hide the list arrow for default profiles

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16972]
### To Do

- [ ] Need to hide this arrow, as it does not work for default profiles

### Description
The default profiles display an arrow that should open a list with a selection of profiles (this works for profiles other than the default ones)

- Menu
- Settings
- Profile
- Profile appearance

https://user-images.githubusercontent.com/104760013/231811823-33c0852e-6723-4975-a58a-68cd9a4285f1.mp4

**Comment by sonora** [comment]
What's the line "OsmAnd profile" for anyway? Shouldn't its caption rather say something like "Based on profile", or perhaps even more clearly "Means of transportation"?
