### ISSUE TITLE
régler la transparence du fond d'écran situé sous les widgets ajoutés à l'écran

### ISSUE THREAD

**Issue by Goupil30** [osmandapp/OsmAnd#16987]
Bonjour

Je souhaiterai que lors d'une prochaine version il soit possible de
régler la transparence du fond d'écran situé sous les raccourcis ajoutés
à l'écran

Menu / Configurer écran / Widgets transparent
Est ce qu'il pourrait être ajouter un curseur afin de régler la
transparence de fond du l'écran des raccourcis

Merci de votre attention, cordialement

JM Luitaud

I would like that in a future version it is possible to adjust the
transparency of the wallpaper located under the shortcuts added to the
screen

Menu / Configure screen / Transparent widgets
Could a slider be added to adjust the background transparency of the
shortcuts screen?

Thank you for your attention, best regards

**Comment by Zirochkabila** [comment]
@Goupil30 Duplicate https://github.com/osmandapp/OsmAnd/issues/16017?
