### ISSUE TITLE
Usablility: Taps on widgets during navigation

### ISSUE THREAD

**Issue by ska-osm** [osmandapp/Osmand#1698]
If you tap on the target widget during the navigation, the map centers on the target.
If you tap on a the waypoint widget, the list of waypoints is opened.
If you tap on the widget of the next junction, nothing happens.

How about, if you tap on either positional widget, "next intersection", target, waypoint, the map centers on the location of that object?

A long tap on either a waypoint or the target could bring up the list of waypoints.
A long tap on the next junction could bring up the list of junctions - routing information.

**Comment by vshcherb** [comment]
It is a duplicate issue about tapping on "next intersection" there is work in progress there. Once I've finish cleaning the issues list, I will provide a link to that issue (it was reported by Hardy)
