### ISSUE TITLE
Usablility: Buttons of Add POI not visible

### ISSUE THREAD

**Issue by ska-osm** [osmandapp/Osmand#1699]
on my SmartPhone the dialog of "Add POI" and the keyboard overlaps in such way, that the buttons to add a new POI or replace an existing one are not accessable.
So, I have to close the keyboard manually, in order to add the POI.
Maybe you could detect, if the both objects overlap and move the dialog up or move the buttons to the opposite border of the dialog.

**Comment by Gizmot** [comment]
may I suggest a screenshot?

**Comment by vshcherb** [comment]
Decided not to fix now and run some usability tests.
