### ISSUE TITLE
Attach to roads dialog stays on top of other screens

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16999]
### To Do

- [x] When attaching a track to a road, the buttons at the top of the screen should be hidden - **Configure map, Search**

### Description
When attaching a track to a road, it is possible to open Configure map 
Android - it is displayed under the Attached track window

### Steps to reproduce
 Tap on the track > Edit > Question mark button > Attach to the roads > Configure map

### Actual result

https://user-images.githubusercontent.com/104760013/233112992-c9ea1927-9520-4484-a829-6ad03fa39c96.mp4

### Expected result
Configure map and Search buttons must be hidden

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#35809m, Released: 2023-04-18
Android/iOS version: Android 12 
Device model: Poco x3 nfc

**Comment by vshcherb** [comment]
Nobody asks to hide buttons on Plan Route screen

**Comment by dmpr0** [comment]
## Review
- [ ]  Bring back buttons. Hide **Configure Map** and **Search** button only when **Attach to the roads** is used.
