### ISSUE TITLE
Allow to use Emoji in user point names 

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#16993]
## Description
Core team have fixed displaying emoji on the map https://github.com/osmandapp/OsmAnd-Issues/issues/1250, but in the past we was added code that don't allow to use emoji as one or first symbol in the favorites/waypoint name.

* https://github.com/osmandapp/OsmAnd/commit/a64110cf99bfa683ef6a462a40a98fd1642862c7
* https://github.com/osmandapp/OsmAnd/commit/0380aafccd754b028bc3698bdc0cddb581504a5b#diff-6f80d2f178c644f433fe866e1acf27b04ca03d92ae75e82bd5482624387607d4R205

### How to reproduce
* Select any point on the map
* Open **Context menu**, tap **Add favorites**
* Tap on **Name** field, clear proposed name if present
* Enter emoji as first or last symbol in the name

#### Actual result
* OsmAnd will show alert
* OsmAnd will remove all emoji's from the name 

#### Expected result
* OsmAnd allows to use emoji symbol in any place while entering name for favorite/waypoint

## Todo
- [ ] User can use emoji in the favorite/waypoint name

**Comment by Velomeloman** [comment]
Not all combinations of text and emoji correctly displays.

![Screenshot_20230419_094617_net.osmand.plus.jpg](https://user-images.githubusercontent.com/109347561/232990209-32cb3ef8-8b36-4947-ab2d-f890cb2359a2.jpg)

![Screenshot_20230419_094604_net.osmand.plus.jpg](https://user-images.githubusercontent.com/109347561/232990208-7e204e85-7d1c-4a26-8b57-1ea4e0ddb0f8.jpg)

![Screenshot_20230419_094423_net.osmand.plus.jpg](https://user-images.githubusercontent.com/109347561/232990210-182056b3-9795-434a-b22f-56962e6d57c6.jpg)

![Screenshot_20230419_094549_net.osmand.plus.jpg](https://user-images.githubusercontent.com/109347561/232990207-d3a57f4f-677c-4dab-8880-6e8c1d281bab.jpg)

![Screenshot_20230419_094512_net.osmand.plus.jpg](https://user-images.githubusercontent.com/109347561/232990212-6715d459-b1dc-45ce-9c6e-98a0718dd1e6.jpg)

**Comment by Zirochkabila** [comment]
@Velomeloman Please check on the latest nightly version - all the combinations you described work

**Comment by Velomeloman** [comment]
Still have some problems.

![Screenshot_20230421_123926_net.osmand.plus.jpg](https://user-images.githubusercontent.com/109347561/233604809-ca97ea20-b006-4b90-b7c4-84fddcab4378.jpg)
Pair of emoji

![Screenshot_20230421_123628_net.osmand.plus.jpg](https://user-images.githubusercontent.com/109347561/233604995-dd120f7f-7e82-46e1-a1cf-9d78b3240c46.jpg)
Text+pair of emoji

![Screenshot_20230421_124330_net.osmand.plus.jpg](https://user-images.githubusercontent.com/109347561/233605216-067faf25-4de4-4d97-bcc8-ba4c8bf3328f.jpg)
Triple emoji 

![Screenshot_20230421_124518_net.osmand.plus.jpg](https://user-images.githubusercontent.com/109347561/233605438-a3c1cf93-11c5-4b98-b020-3a2842851a06.jpg)
Double emoji + text with no space character between

**Comment by dmpr0** [comment]
## Review 
It seems that only 2 emoji symbol is showing as name on the map

<table style="width:100%">
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/233948832-d0dd36e4-1ac3-4d97-b9cb-01e857d1a245.jpeg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/233948836-79ab94d7-84bb-438d-8679-662dfbf1b7c6.jpeg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/233948840-29136607-314d-4e08-aaec-14fb23edd04a.jpeg"  width="300" height="auto"/> </td>
  </tr>
</table>
