### ISSUE TITLE
Coastline rendering problem, Aotearoa

### ISSUE THREAD

**Issue by robinpaulson** [osmandapp/OsmAnd#17009]
See attached image, which is at Half Moon Bay, Tamaki Makaurau-Auckland, Aotearoa-New Zealand

![](https://i.imgur.com/uGRsxAU.png)

**Comment by robinpaulson** [comment]
36.88183° S, 174.88824° E

**Comment by ManDay** [comment]
And what exactly is the problem? (Link for the lazy https://www.openstreetmap.org/#map=15/-36.8834/174.8871 )

**Comment by robinpaulson** [comment]
I'm not sure what you're asking for.

**Comment by BenBE** [comment]
The part at Farm Cove looks strange (and likely wrong) …

Comparing with the rendering from OpenStreetMap (Default Layer), the rendering of Tahuna Torea east of Lagoon Track is kinda odd (although probably right).

**Comment by Zirochkabila** [comment]
Reproduced - zoom levels 11 through 14. 
Only with V1 rendering

https://user-images.githubusercontent.com/104760013/234021959-c2d290fe-b64e-42ea-a9a5-5fd399967d8d.mp4

**Comment by robinpaulson** [comment]
@BenBE yes, tahuna torea is unusual, lots of wetlands and sand dunes, but it appears correct.

**Comment by robinpaulson** [comment]
As of the latest offline snapshot, this is no longer a problem. Perhaps there was a coastline error? Closing
