### ISSUE TITLE
Usablility: Current position hidden by notification

### ISSUE THREAD

**Issue by ska-osm** [osmandapp/Osmand#1700]
Sometimes some notifications are displayed in at the lower part of the osmand map, e.g. when the "Time until map view synchronizes with current position" kicks in during navigation. However, on my phone the current location is below the notification window and becomes hidden by it. This can disturb the routing, if there is a junction right ahead.
Could you display the notification on the upper side of the screen, if the current location is displayed in the lower 3rd of the screen, in order to keep the current location visible, because it is the interesting spot during a navigation?

**Comment by vshcherb** [comment]
We need to review all notifications displayed during navigation, it seems that they are useless, cause during navigation it is hard to read something on them.
We can't change the position of the toast, but we can review and disable some of them.

Can you provide what kind of messages do you see during navigation ?

**Comment by jf-simon** [comment]
something similar to that issue. 
the new context menu of long press hides the poi.

if i longpress on a poi the menu at the bottom appears. 
press on the name in the menu so the poi becomes centre. in my case not the centre of the screen.
now the poi ist hidden.
![screenshot_2015-09-22-13-41-33](https://cloud.githubusercontent.com/assets/11144987/10018269/b6a798ea-6135-11e5-9fca-04ef69d9588d.png)
![screenshot_2015-09-22-13-41-42](https://cloud.githubusercontent.com/assets/11144987/10018279/c052011e-6135-11e5-9bfc-002b3e3a6b5f.png)

**Comment by jf-simon** [comment]
Thanks for fixing
