### ISSUE TITLE
Abberance in the route calculation.

### ISSUE THREAD

**Issue by Breizhux** [osmandapp/OsmAnd#17001]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

In car routing profile.

### Start and end points

Start address : https://www.openstreetmap.org/#map=17/48.10517/-1.69851
End address : https://www.openstreetmap.org/#map=19/48.11816/-1.67616

### Actual and expected routes
The expected route is the one calculated on the open street map website :
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=48.10520%2C-1.69850%3B48.11820%2C-1.67620#map=16/48.1118/-1.6873

The itineraries are aberrant, adding completely useless detours...
Pictures will speak better than long speeches. These 3 captures are taken on the same route in car profile (I did not check the other profiles, I can do it if you wish):
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/53947821/233165199-e00fd96d-1aaf-430f-a46e-520ed579645d.png"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/53947821/233165206-823a522d-5da9-4bea-a1d3-a5d519df9eef.png"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/53947821/233165208-00bb7fcc-ff57-4399-b771-f004d2849e63.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Is this a regression?
I remember (when I was a kid ^^) a few years ago, I was promoting OSMAnd precisely for the quality of the calculated routes. I thought they were really amazing. But I can't remember which version the change was made to. But one day I discovered that OSMAnd proposed completely aberrant routes. Since then, regularly during some trips, I discover aberrations of this type, which I can obviously avoid sometimes... But this is not normal.

When I started to use OSMAnd, the first times I thought I was seeing aberrations, it was actually the application that had detected that by making me go through secondary roads the way to avoid me long roads with lights for example. It was really incredible.
But now it is not the case anymore, on the contrary. In this case it lengthens the route for nothing!

To be honest, I really like OSMAnd, it's one of my favorite applications. But if it doesn't do its job anymore, even if the interface is made customizable and the navigation made pleasant, if the route is wrong (calculated route or ETA), the application is unusable.

I will try to find an old version of OSMAnd... But it must be 2 years and a half that I encounter this bug...

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>
OsmAnd~ 4.3.8
</code></pre>

**Device and Android/iOS version:**
**Device** : Xiaomi Mi A1
**Android version** : 12

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.
Current example is run on map "France_brittany_europe"...
- [ ] Online (tile / raster) maps 

**Anything else relevant?**

OSMAnd has all the capabilities to be by far the best GPS application. Please make sure it stays that way!!!
Lots of courage, and thanks for a great project!

**Comment by Breizhux** [comment]
I'm not sure I understand your answer. Besides I am not familiar with route calculations... When you talk about "costs" I guess it means fuel costs or time costs (depending on the setting)?

Anyway, in the first two cases, the cost is higher with the OSMAnd route than with the OpenStreetMap route... Only the third case seems to cost less.

But in fact, whatever happens, it is disconnected from reality. If you look closely, on the OSMAnd routes the resulting route is necessarily more fuel or time consuming: the calculated route looks like it follows the widest road, but which is therefore also the busiest; it also contains more traffic lights, more pedestrian crossings, etc.
What I'm saying here is a bit theoretical, but it's mostly verifiable in reality, i.e. I spend much more time braking and accelerating with OSMAnd routes than with the others, where I gain in consumption (less energy consuming), by saving time and distance! The routes calculated by OSMAnd are in every way a loser. I'm not sure how much I want to tell myself that the route proposed by OSMAnd is better from a certain point of view, but there, I don't find it...


On the other hand, after having done the test, the 3 previous captures were made without the fuel economy mode. With the fuel economy mode, the route is better and corresponds to what I would usually expect, but there remains this which is still aberrant:

![Capture du 2023-04-20 12-29-20](https://user-images.githubusercontent.com/53947821/233340762-52cf0b5b-b83b-4dd3-977e-ec1ea81ccad1.png)
_*the red dots correspond to traffic lights, which were not necessarily visible with this zoom level._

**Calculated route** (by car, economy mode or not): 4 traffic lights, 2 direction changes, 2 bus stop zones.
**Desired route** (in both cases): 3 traffic lights, 1 change of direction, 2 bus stop zones.



In short, without the fuel saving mode, **I don't see on what criterion the journey is optimised, as it is longer in time, distance and even consumption...** After all, the aim is perhaps to accentuate the usefulness of the "fuel-saving route" option by adding unnecessary detours 😂️ More seriously, even without the fuel-saving mode, the route has no interest in making us take detours, and even less in making us pass through the big intersections that are regularly jammed in town.

And **in fuel economy mode, the ride is better... But only in town**. On long journeys the route avoids the motorways... Which is not desirable at all considering my fuel consumption.
My car consumes little on the motorway (~4L/100), but the algorithm seems to assume that driving above 90km/h is undesirable. But in this case, it makes me drive on slower roads, but often segmented by regular roundabouts, or even traffic lights. So I spend my journey accelerating/braking at every intersection. And despite a rather regular and smooth driving, I consume much more than going on the motorway to avoid all these roundabouts. I can believe that it depends on the car. In this case, **we should perhaps think about making the vehicle's consumption (in town and on the motorway) parameterisable...**

**Comment by ivanPyrohivskyi** [comment]
Issues in this route:
1. [Rue de l'Hôtel Dieu](https://www.openstreetmap.org/way/9669533) is closed (motor_vehicle=no) _"Route fermée durant les travaux, du 30/05/2023 au 07/07/2023 "._
2. [Rue Legraverend](https://www.openstreetmap.org/way/462556846) has maxspeed=30 and lower highway=secondary than [Boulevard de Chézy](https://www.openstreetmap.org/way/315159180) with maxspeed=50 and highway=primary
3. [Rue Papu](https://www.openstreetmap.org/way/462556846) has highway=residental that has too big [penalty_transition in routing.xml](https://github.com/osmandapp/OsmAnd-resources/blob/d014ae6e44efacdf5f55ea6f25a4972adcc1a7cd/routing/routing.xml#L779C22-L779C22). Minimal value of penalty_transition when OsmAnd routing build route through this way is 113.

**Comment by vshcherb** [comment]
1. the main reason
