### ISSUE TITLE
Center of the map changes its position (OpenGL only)

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#17012]
### To Do

- [ ] Keep the center of the map in the same place as before locking the screen

### Description
When unlocking the screen, the map shifts, and the center of the map changes its position

### Steps to reproduce

- Lock your screen
- Unlock

### Actual result

https://user-images.githubusercontent.com/104760013/233647289-7c673b0b-c88a-4e5c-b94a-88b994c93859.mp4

### Expected result
Мap remains in the same place

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#35825m, Released: 2023-04-21
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by cepprice** [comment]
No longer reproduced
