### ISSUE TITLE
Data is not imported if used the "/" symbol in the name of the Favorites folder

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#17013]
### Description
When exporting all Favorites to a .osf file user used "Export to file" (so as not to lose anything during reinstallation).
When the user re-imported the file, two of its categories were missing (in one
of them he collected more than 200 POIs, which are very important for the user!)
Fortunately, the user found a mistake - these categories had a slash in the name ("mountain peaks/saddles").
When OsmAnd generated the backup structure, instead of creating a file "favorites-mountain peaks/saddles.gpx", the slash resulted in a subfolder. So the user ended up with the following result: "favorites-mountain peaks" folder with the file "saddles.gpx".
And it seems that OsmAnd could not re-import this structure.

### Expected result
Or not allow the user to add straight slashes to favorites or remove them automatically during backup. The first solution is probably more reasonable.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#35864m, Released: 2023-04-29
If you use the "/" symbol in the name of the Favorite folder and create an osf file, the folder containing the name with the "/" symbol will not be imported (Volna/morska is the name of the Favorite folder)
[Export_2023-04-29.osf.zip](https://github.com/osmandapp/OsmAnd/files/11358817/Export_2023-04-29.osf.zip)

![photo_2023-04-29 12 44 32](https://user-images.githubusercontent.com/104760013/235296285-4108f7f1-3c3c-4005-bf73-3902d795f0f2.jpeg)


https://user-images.githubusercontent.com/104760013/235296210-91d727ef-0791-4a68-a22e-76c55c03ce20.mov

### Step to reproduce

- **Menu** > **My Places**
- **Folder menu** > **Edit name** > **Enter a name with "/" symbol** > **Save**
- **Menu** > **Settings** > **Export to file** > **Select Favorites**
- **Import osf file to OsmAnd**

**Comment by patrick-haldi** [comment]
Hello! I'm the guy who originally had this problem. Sorry for my late response! Here is my original backup file: https://e.pcloud.link/publink/show?code=XZD1njZ7GThpDJQAyfdarR5t5eIJkXlzOwX
(it was to big to upload here directly)

I think the favourite categories that caused the problems were named
- Mountain peaks / saddles
- to add / edit OSM

So, of course, the problem was the forward slash in the name, as described above.

General info:
Device: Fairphone 4
Android Version: 12 (FP4.SP25.B.058.20230318)
OsmAnd Version: Tried various versions, at the moment I have 4.4.7

**Comment by sonora** [comment]
A forward slash may be interpreted as a path folder separator, have you checked if the coresponding elements perhaps ended up in a subfolder?

In principle, we should probably  check and mitigate problematic charactets, at the latest when exporting,I guess...

**Comment by patrick-haldi** [comment]
Yes, that's exactly my guess as well. Did you see Zirochkabila's Screen recording? It seems to show that exactly this happens. And in my case, it was exactly the same, I ended up with this dir structure:
- Mountain peaks
  - saddles
- to add
  - edit OSM

Yes, I think it would be best if the user were not even allowed to enter such characters.
Or alternatively setup a clean coding when backing up and a decoding when re-importing. But the first solution might be easier..

**Comment by dmpr0** [comment]
# Review
- [ ]  "file": "favorites-Paris_%_Day 1.gpx" is missed after import
File [Export_2023-06-12.osf.zip](https://github.com/osmandapp/OsmAnd/files/11722346/Export_2023-06-12.osf.zip)
