### ISSUE TITLE
add vending_machine=fuel

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/OsmAnd#17019]
The fuel stations sometimes have a automatic fuel dispenser what can operated after the service is closed or 24/7.

https://wiki.openstreetmap.org/wiki/Tag:vending_machine%3Dfuel

There are over ~13.000~ 7.000 fuel stations with the vending_machine=fuel tagging. 
Please add these to Osmand

**Comment by Zirochkabila** [comment]
[Tag info 7252](https://taginfo.openstreetmap.org/search?q=vending_machine%3Dfuel#tags)

**Comment by hakuchi** [comment]
@xmd5a2 I think this only for a gas pump `amenity=vending_machine` and `vending=fuel`     

my request is for a gas station `amenity=fuel` with `vending_machine=fuel`

https://www.openstreetmap.org/node/367460867
https://www.openstreetmap.org/way/609232309
https://www.openstreetmap.org/node/8948085541

**Comment by xmd5a2** [comment]
New maps and OsmAnd required.

**Comment by Zirochkabila** [comment]
`48.83163/2.35952`
[OSM](https://www.openstreetmap.org/way/221071441#map=19/48.83161/2.35959)
Done - new map
