### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by saeedafshari8** [osmandapp/Osmand#1701]
Dear developers,
Thanks for continues integration.
I cloned the latest version from repository and I saw that there is 5 errors related resource files.
The following resources does not exist:
- R.drawable.mx_name_finder
- R.drawable.mx_user_defined
- R.drawable.mx_toll_booth
- R.drawable.mx_barrier_border_control
- R.drawable.mx_highway_speed_camera

**Comment by moosaviamir** [comment]
Dear saeed
You should clone resources too.
Then search files in the resources and put them into drawable folder and you will be fine.
