### ISSUE TITLE
Maximum speed on roads is outdated

### ISSUE THREAD

**Issue by spaanse** [osmandapp/OsmAnd#17017]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

car

### Start and end points

Zwolle, a road segment on the Oldenallee
https://www.openstreetmap.org/#map=17/52.49263/6.13127

For example:
52.49114 N 6.12749 E to 52.49348 N 6.13482 E

### Actual and expected routes

The given route follows Oldenallee as expected.
However it states that it takes 41 seconds for a route of 565 meter.
Converting that gives a speed of 50 km/h ([calculator on DuckDuckGo](https://duckduckgo.com/?q=565%2F41+m%2Fs+to+km%2Fh&t=ffab&atb=v210-1&ia=answer))
However, the max speed of this road is 70 km/h and has been that way in OSM since 2013.
The maximum speed is also indicated to be 50 km/h when driving on this road

### Is this a regression?

I don't know, seems the speeds are not updated in the new offline maps.

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

OsmAnd 4.4.7
Released: 2023-04-10
</code></pre>

**Device and Android/iOS version:**

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

Relevant map:
Netherlands Overijssel, updated on 1 Apr 2023
Live updates: last updated 21 Apr 00:19 (includes OSM changes made until 2023-04-20, 23:50)

**Anything else relevant?**

**Comment by sonora** [comment]
Sounds like you're taking the trip time from our Development  plugin's debug information, please note that this is not normally equivalent to the actual travel time estimate. But if on this road stretch OsmAnd displays a speed limit of 50 instead of 70, that seems like it needs investigaring.

**Comment by CJTmmr** [comment]
On another location Osmand shows MaxSpeed 80 km/h,  while on OSM it has been 100 km/h always. 
Netherlands South Holland, N11 between Bodegraven en Leiden.
For instance on this locatiion, but futher all along N11. 

https://www.openstreetmap.org/way/129170115#map=17/52.08071/4.73903&layers=D

![Screenshot_20230425_233611_OsmAnd+](https://user-images.githubusercontent.com/15076257/234409771-87b2d14a-12a1-44d9-927a-03046a2b2401.png)

**Comment by Zirochkabila** [comment]
Same result https://github.com/osmandapp/OsmAnd/issues/17065

**Comment by xmd5a2** [comment]
Fixed. `maxspeed` now have more priority than `zone:traffic` and `maxspeed:type` tags. New maps are required.

**Comment by Zirochkabila** [comment]
Needed to update or re-download the map of **South Holland**

`52.07857, 4.74493`
[OSM](https://www.openstreetmap.org/way/129170115#map=17/52.07940/4.74001)

<table style="width:100%">
  <tr>
    <th>OsmAnd Nightly 4.5.0#46m, released: 2023-05-18</th>
    <th>4.4.8.11</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/75d0591f-a721-4ceb-b65c-34f46b60f39b"  width="300" height="auto"/> </th>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/31512e61-1f7e-4e79-aa20-855e445569bd"  width="600" height="auto"/> </th>
  </tr>
</table>
