### ISSUE TITLE
Add a mountain icon for My Places

### ISSUE THREAD

**Issue by endolith** [osmandapp/OsmAnd#17029]
# 🚀 feature request

### Description

Add a mountain icon for items in My Places

### Describe the solution you'd like

Add a mountain icon for items in My Places for labeling peaks/cliffs (and, ideally, any other icons that are provided by other services like Google My Maps). 
![image](https://user-images.githubusercontent.com/58611/233854297-bac25c37-3d42-4b92-95a3-845980cfa786.png)

### Describe alternatives you've considered

The pyramid is the closest looking icon in the current set.

**Comment by dmpr0** [comment]
Done https://github.com/osmandapp/OsmAnd-resources/commit/a8af8780cc42502a8add8cbca

<table style="width:100%">
  <tr>
    <th>iOS</th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/393d1b80-8691-45e6-b285-ce27f713a2be"  width="300" height="auto"/> </td>
    <td><img src=""  width="300" height="auto"/> </td>
  </tr>
</table>
