### ISSUE TITLE
Add alias "AED" for defibrillator POI search

### ISSUE THREAD

**Issue by dreua** [osmandapp/OsmAnd#17025]
# 🚀 feature request

### Description

When I search for "defibrillator" it displays the category, I tap on it, hit "Show defibrillator on map" and can quickly find the nearest one in case of an emergency, perfect :+1:

When I type "AED" however, the search yields only some defibrillators which are far away (those which happen to contain AED in their name).

### Describe the solution you'd like

Implement something like an alias that gives the same results "Defibrillator (Emergency)" category first if someone searches for AED.

Note that this is sufficient for English and German speakers because the words are the same. Ideally it would be internationalized to work in all available languages.

### Describe alternatives you've considered

Use some other App/Map I'm not familiar with and which most likely not have offline maps for the place I'm currently at. - Not ideal. (http://definetz.online/defikataster-hp does have better coverage in some areas however, improving that in OSM data is another project.)

**Comment by dreua** [comment]
Just had another idea to solve this: Could we just rename the "Defibrillator" category to contain both keywords, e.g. "Defibrillator (AED)" or "Defibrillator / AED"? This way both search terms would yield the category as result.

Just tried this with "post" as search term and it yields "Health post", "Post Box", "Trading post" etc. Therefore I'm confident this should work just fine.

**Comment by vshcherb** [comment]
Yes we can add "Defibrillator (AED)" to the translations so it's searchable, renaming category won't be backward compatible with current release.  However we will need to all languages where we think AED is known. 
CC @xmd5a2

**Comment by dreua** [comment]
Sounds good to me! For english and german I can say that it is known and should be included.

**Comment by xmd5a2** [comment]
Fixed
