### ISSUE TITLE
Feature request: easy way to change profile

### ISSUE THREAD

**Issue by mikehgentry** [osmandapp/OsmAnd#17021]
# 🚀 feature request

### Description

There have been a few issues that have come up (e.g. #17020 #16139 ) that could be solved or at least mitigated by having an easier way to change profile - you could have two profiles adjacent to one another, and be able to flip between them, to effectively reconfigure the UI or the map on the fly. 

### Describe the solution you'd like

Three finger swipes could work, assuming you can detect those?

### Describe alternatives you've considered

Quick actions would also be an option, especially with the plan to allow them to be placed on separate buttons. Opening a profile selection widget doesn't get you anything (it's just as quick to do via Configure map, probably), but if the user could add 'Previous profile' and 'Next profile' buttons to the screen using quick actions that'd definitely work.

**Comment by sonora** [comment]
Just to make us all aware: The quickest way currently to change the profile is three taps:
- Tap on the profile widget displayed top left on the map (in the navigation case below any direction arrows)
- Tap on the desired profile (in the top row of the dialog)
- Tap the device's back button (or anywhere in the map). Perhaps we could save this 3rd tap during an ongoing navigation by closing the dialog automatically after tap 2?

Also, be aware that during an ongoing navigation, this method willl _not_ change the transport mode used for the navigation, only the map display mode (while changing the profile on the navigation dialog instead would).

**Comment by mikehgentry** [comment]
Yes, to the extent that you can change that in the render xmls, it can be done via profile (though I don't think you can only show the route you're on and the routes leading off it).

And it would allow you to change a lot of things, including complexity of map and UI (as in the motivation behind #16139 ). More of a Swiss-army suggestion than a specifically directed one. I know I'd make use of it - I have lots of similar profiles suited to different conditions, and at the moment the process of changing between them is pretty cumbersome with my phone in a bag, and not really doable in motion.

**Comment by vshcherb** [comment]
We plan to have a hardware mappin button to change profiles and also rearranged quick action to allow 1 click

**Comment by mikehgentry** [comment]
This works as of 4.8 (or possibly before).

Thanks!

**Comment by NohWayJose** [comment]
I've looked in profiles and **it's not at all obvious how to de-detail the view**. Even if it did, basing the removal of unneeded clutter on just hierarchy means that if your navigation route comes off a motorway on to a B-road (don't know how that translates internationally), then if B-Roads are too measly to render, what happens? What's needed is route aware de-cluttering and it be the default profile for navigation. 

@mikehgentry  This needs to be reopened! classifying the request as quick profile switching is missing the user experience needed.

**Comment by NohWayJose** [comment]
I've dug down into profiles and there's a hokey and rather unrelated means to hide stuff. It doesn't at all fulfil the need to 'only show what's relevant to my current navigation route', which is why closing the request by identifying a tenuously related very partial 'fix' means the legitimate issue will get ignored and I don't think it should be. The proper fix, even if it's a long burn item is to have an algorithm to take the route vector and calculate which map 'road' or 'path' vectors intersect it and draw those (mode: only draw route & intersections) or that plus important places, such as town names or landmarks (mode: route, intersections & important places) or that plus important places + searched item types within a specified distance of the route (in the direction of travel) (mode: route, intersections, important places & search markers (with a _divert-to_ option))

**Comment by NohWayJose** [comment]
In that case, why are YOU closing my issue? (Assuming you did that)

**Comment by mikehgentry** [comment]
This is an issue I opened. You are subscribed to it because you commented (you can opt out of specific issues via the right hand panel of github's web interface, and probably configure that globally if you look in to it)

**Comment by NohWayJose** [comment]
My apologies,

Hectic dipping in and out of various things. Should have spent a bit more time. I thought it was a spin off from an issue I raised.

Peace and love

Greg
