### ISSUE TITLE
Key: note text still being displayed on maps

### ISSUE THREAD

**Issue by poeticus** [osmandapp/OsmAnd#17024]
### Description
I'm still occasionally seeing key: note text displayed on maps. Previously reported examples were fixed in v4.3 (see closed issue #15706). Edit: this only appears to happen when using the OSM carto rendering style.

Screenshot below of Warton Crag just N of Carnforth, Lancashire in NW England relates to node 3773389211 (Warton Upper Crag). 
Map used: United Kingdom England North West England (April 1st 2023).

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/118109677/233833310-81457f1b-16b2-469d-a3d1-5037ab596276.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Steps to reproduce
View map at this location.
Edit : use OSM carto rendering style.

### Actual result
Key: note text displayed for Warton Upper Crag.

### Expected result
Key: note text should not be displayed.

### Your Environment
OsmAnd Version: 4.3.12
Android/iOS version: Android 12
Device model: Fairphone 3+

**Comment by poeticus** [comment]
Looks like this results from my use of a customised rendering style based on an old standard render file. Key: note text does not appear when a current included style is used.

Closing this issue.

**Comment by poeticus** [comment]
Reopening issue as have just realised that the note text is displayed if OSM carto map style is used (but not displayed with other styles).

**Comment by sonora** [comment]
I guess it's by design: OSM carto has been introduced to assimilate the style used on osm.org, see https://github.com/osmandapp/OsmAnd/issues/13778.

**Comment by poeticus** [comment]
I don't believe it's by design. The vast majority of notes are not displayed on the maps when using the OSM carto style / my customised style based on it. Just very occasionally I notice one showing, as in the screenshot. Looking on OpenStreetMap at the tag detail for the node it appears to me to be tagged similarly to others where the note text is not displayed.

**Comment by scaidermern** [comment]
Carto doesn't display note tags. So OsmAnd shouldn't display them either. The [note tag](https://wiki.openstreetmap.org/wiki/Key:note) contains information for other _mappers_, not for regular users.

However, I don't see note tags when switching to OSM-carto style. I haven't checked your location, though.

Also please check that the setting Configure map / Note tags is _off_.

**Comment by poeticus** [comment]
As described above I see this only for the very occasional feature. Generally the text from key:note tags is, correctly, not displayed.

The example shown in the screenshot relates to this node https://www.openstreetmap.org/node/3773389211 and only appears for me in OsmAnd when using the OSM carto style.

**Comment by Zirochkabila** [comment]
@poeticus In the latest update, the text is not displayed.
Please update OsmAnd https://osmand.net/docs/versions/nightly_versions


https://user-images.githubusercontent.com/104760013/234016168-1c92d779-54df-4e44-9009-e5705c28f2f2.mp4

**Comment by poeticus** [comment]
Will check when next updated on F-Droid then. Thanks.

**Comment by Zirochkabila** [comment]
@poeticus I advise you to pay attention to the version from the official app stores.
Can we consider this issue closed?

**Comment by poeticus** [comment]
Happy for you to do whatever's best. However, until the app is updated in F-Droid I'm unable to confirm its resolution here.

**Comment by poeticus** [comment]
Confirmed that the text is not displayed in v4.4.7 from F-Droid so now closing this.
