### ISSUE TITLE
Feature request : keep screen on when near a crossroad

### ISSUE THREAD

**Issue by breversa** [osmandapp/Osmand#1702]
I've started experimenting with the "Wake up screen near a crossroad/direction change" (or whatever it's called in english), and I find it very handy to save up battery, especially during long highway trips.

However, when driving in the city center, I often end up in the following situation : as I approach a crossroad where I need to turn, the screen would turn on to show me the way. However, if there's a red light at the crossroad, the screen would sometimes turn off again (after timeout), and when the red light turns to green, I sometimes can't remember precisely what road to take (imagine a very complicated crossroad in an unknown city during peak traffic, and you'll get the idea).

So here are my suggestions to avoid this situation :
- either keep screen on when _near_/within range (= in distance, not just time) of a crossroad/direction change
- or simply keep screen on when immobile. After all, it's one of the best time to check your map. :-)

Both those changes could also come in handy if there's an unexpected stop/heavy slowing on the way, like a construction area, or an accident. Having the screen on at that moment could allow you to more easily pick an alternative route.

**Comment by sonora** [comment]
No action planned here, it seems.

**Comment by breversa** [comment]
Yeah, apparently nobody noticed my request… :-s

**Comment by sonora** [comment]
Definitely not a matter of noticing! But a matter or resonance. :) And I think we need to apply some product management every once in a while here by focusing on the things which resonate most  :)  No hard feelings.

**Comment by ossilator** [comment]
too bad - it seems like a reasonable request. :slightly_smiling_face:
