### ISSUE TITLE
Waypoint description rendering difference when displaying "read full" 

### ISSUE THREAD

**Issue by tmusolf** [osmandapp/OsmAnd#17023]
### Description ###
Import GPX file with a waypoint description tag that contains \<br\> tags.  This renders property in the main waypoint details screen, but when selecting "read full" the \<br\> tags are visible and there are no newlines in the displayed text.

### Steps to reproduce
  Create a gpx file with the following contents:
```
<?xml version="1.0" encoding="utf-8"?>
<gpx xmlns="http://www.topografix.com/GPX/1/1" version="1.1">
  <wpt lat="41.4642097" lon="-126.5076542">
    <name>Escape Char Test</name>
    <desc>ampersand &amp; char&lt;br&gt;Greater than sign &gt; char&lt;br&gt;Less than sign &lt; char</desc>
    <ele>0</ele>
    <extensions>
      <icon>special_marker</icon>
      <background>circle</background>
      <color>#0288D1</color>
    </extensions>
  </wpt>
</gpx>
```

Import this into OSMAnd My Places and make it visible.  Select this waypoint from the map and choose "details".
Look at the description text on the details screen and it looks correct.  Select "read full" and there are no newlines and the \<br\> tags are visible.

### Actual result
```
ampersand & char<br>Greater than sign > char<br>Less than sign < char\
```

### Expected result

```
ampersand & char
Greater than sign > char
Less than sign < char
```

### Your Environment

OsmAnd Version: 4.4.7 released 2023-04-10
Android/iOS version: Android 13
Device model: Pixel 5a

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#35865m, Released: 2023-04-29
4.4.8.3
[lalalla.gpx.zip](https://github.com/osmandapp/OsmAnd/files/11360836/lalalla.gpx.zip)


**If imported file as a Waypoint** - text in the new line is displayed in the general description, but after clicking on read full text, it is displayed in one line
**If imported file as GPX** - text is displayed in one line, as in the case of read full
**If imported file in iOS** -  text  is displayed  in one line,  but after clicking on a text it displayed in the new line in general description

<table style="width:100%">
  <tr>
    <th>Waypoint</th>
    <th>GPX</th>
    <th>iOS</th>
  </tr>
  <tr>
    <td><video source src="https://user-images.githubusercontent.com/104760013/235342470-5d8132be-a7b1-4e0d-805c-d7727be32c33.mp4"  width="300" height="auto"/></td>
    <td><video source src="https://user-images.githubusercontent.com/104760013/235342471-e5d10b30-0e3b-440d-a77f-a5f4f69093a1.mp4"  width="300" height="auto"/> </td>
    <td><video source src="https://user-images.githubusercontent.com/104760013/235342473-b70db04c-9d3d-44bf-8846-f746afc66ed7.mp4"  width="300" height="auto"/></td>
  </tr>
</table>

**Comment by vshcherb** [comment]
To do: we need to fix
1. full description  Read Full Android - HTML should be supported
(Possibly if we can fix) 2. Android description in GPX Points menu - simple HTML should be displayed (so tags <br> should not be visible)

**Comment by dmpr0** [comment]
<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/e0941b20-40d6-43d1-aecf-d2f1ec57460f"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/0787f782-c9b4-4706-99ed-b52aa86f6f74"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/79f5ca8b-80f3-40f8-ba82-c637ee68a150"  width="300" height="auto"/> </td>
  </tr>
</table>
