### ISSUE TITLE
Green fill is not displayed on the map (5-6 zoom) when poly is composed of several closed ways

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1703]
Problematic poly parts have these tags in regions.xml:
key_name=malaysia
osmand_region=boundary
region_full_name=asia_malaysia
Problem is related to osmand_region=boundary.
![screenshot_2015-09-16-11-50-17](https://cloud.githubusercontent.com/assets/5829014/9901334/a6368af4-5c6f-11e5-92f9-2e62e5ccc974.jpg)
![_2015-09-16_12-39-40](https://cloud.githubusercontent.com/assets/5829014/9901383/1121fc7c-5c70-11e5-8abb-68e8cf690ecb.png)

**Comment by vshcherb** [comment]
Requires ocbf regeneration, but I guess it is fixed now. The testing is needed to check if download button appears on all areas and green is displayed as well
