### ISSUE TITLE
Illegal (wrong) routing with "Moped" routing profile

### ISSUE THREAD

**Issue by Isolator70** [osmandapp/OsmAnd#17034]
# 🐞 routing report

### Routing engine

OsamAnd internal routing engine

- [ X] OsmAnd's in-app offline routing

### Routing Profile

**Moped** profile ~without any changes~ Edit (20230502): **Speed of routing option was set to personal (higher) values** was used

### Start and end points

Starting point: https://www.openstreetmap.org/way/525451599#map=17/50.49651/8.47116
End point: https://www.openstreetmap.org/way/525451599#map=18/50.51830/8.48819

### Actual and expected routes

OsmAnd routes over clearly as "agricultural" tagged ways and therefor excluded for motor vehicles like cars, motorcycles, mopeds and mofas as well.

Additionally the way's smoothness is partly "bad", so a "Moped" rider would not choose if there were legal alternatives because he goes with 45km/h speed and more.

I expect:

1. A legal routing
2. A switch to accept (illegal) routing via agricultural ways AND smoothness "intermediate" and better.

### Is this a regression?

Did not use it so far, so I cannot rate.

## 🌍 Your Environment

OsmAnd: 4.4.7

**Device and Android/iOS version:**

Huawei P10 (VTR-L29), Android 9.0

**Maps used (online or offline):**

- [X] Offline maps offered within the OsmAnd app for download.

**Anything else relevant?**

A "**Moped**" typically has a maximum speed of 45km/h, some are allowed to go even 60 (ex. GDR). Nowadays it's colloquial name is "**Scooter**" with limited speed, in German "Kleinkraftrad": https://de.wikipedia.org/wiki/Kleinkraftrad 
It is not allowed to go on "Bundesstraße" or "Autobahn" (max speed >= 61km/h).
This type of vehicle if very popular in many countries of the world.

It is something different than the "**Mofa**" which only goes 25km/h (and most probably does not need navigation, as the typical traveling distance is much more limited. (https://de.wikipedia.org/wiki/Mofa).
The popularity compared to 45km/h Scooter  class is quite low.

https://user-images.githubusercontent.com/35434137/233939852-4e9f6a9a-8945-4de4-86d8-57ad2b70e2d8.mp4

**Comment by Zirochkabila** [comment]
@Isolator70 Behavior was reproduced in the web version, but not on the device. 
Standard settings of the Moped profile are similar to those of a car
[OsmAnd](https://osmand.net/map/?start=50.499309%2C8.464665&end=50.518462%2C8.488462&mode=moped#15/50.5078/8.4820)

https://user-images.githubusercontent.com/104760013/234011649-05566a5e-ead1-4b16-913c-de6718fce436.mp4

**Comment by Isolator70** [comment]
@Zirochkabila : What router are you using? I'm using the "OsmAnd Offline Moped" Router.
Where can the settings of the "Moped" profile be checked? I can only select if I want to use "Ferries" or not and the speed (which at standard settings are way(!) to slow).

**Comment by Zirochkabila** [comment]
@Isolator70  This is a standard profile with standard settings
[Moped.osf.zip](https://github.com/osmandapp/OsmAnd/files/11311412/Moped.osf.zip)

**Comment by Isolator70** [comment]
@Zirochkabila : How can I export/ generate/ find this file on my device for comparison reasons?

**Comment by Isolator70** [comment]
So the json files are quite different, here is mine (changed extension osf to zip) and please find attached the output of diff on both *.json. The items file in the *.osf are identically (sha256sum checked).
[Moped_Isolator.zip](https://github.com/osmandapp/OsmAnd/files/11312623/Moped_Isolator.zip)
[Diff_output_profile_moped.json.txt](https://github.com/osmandapp/OsmAnd/files/11312631/Diff_output_profile_moped.json.txt)

Now the Master questions:
1. Is there a Moped profile delivered along with OsmAnd?
2. Or did I create mine with no idea what I was doing based on bicycle?
3. If 1. is true: Why is mine and the one of @Zirochkabila (based on car?) totally different?

**Comment by Isolator70** [comment]
> My OsmAnd (4.4.7) comes with a moped profile.

Thanks, could you please export and post it here for comparison?

> Not sure what this means exactly, though.

Looking into @Zirochkabila  profile shows way more routing options which are not available in my profile and other suspicious differences:

```
--
Ziko:  "nrenderer_baseAppMode": "",
Iso:  "nrenderer_baseAppMode": "bicycle",
--
Ziko:  "nrenderer_appMode": "",
Iso:  "nrenderer_appMode": "moped",
--
Ziko:  "prouting_avoid_toll": "false",
Ziko:  "prouting_avoid_unpaved": "false",
Ziko:  "prouting_avoid_borders": "false",
Ziko:  "prouting_avoid_ice_roads_fords": "false",
Ziko:  "prouting_avoid_ferries": "false",
Ziko:  "prouting_avoid_motorway": "false",
Ziko:  "prouting_avoid_low_emission_zone": "false",
Ziko:  "prouting_avoid_shuttle_train": "false",
Ziko:  "prouting_avoid_tunnels": "false",
Ziko:  "prouting_avoid_4wd_only": "false",
Ziko:  "prouting_allow_private": "true"
Iso:
--
```

**Comment by scaidermern** [comment]
> > My OsmAnd (4.4.7) comes with a moped profile.
> 
> Thanks, could you please export and post it here for comparison?

Sure. This is the standard, unmodified moped profile of OsmAnd 4.4.7:
[Moped.osf.txt](https://github.com/osmandapp/OsmAnd/files/11313667/Moped.osf.txt)

**Comment by Zirochkabila** [comment]
@Isolator70 Moped profile is provided with OsmAnd
Try the following - back up all files locally (just in case): Menu > Settings > Export to file. 
After that, install the night version and restore OsmAnd to factory settings (do not export your data yet) https://osmand.net/docs/versions/nightly_versions
After that, try to create a route using the standard moped profile (it should be disabled by default, you will need to activate it).
If everything works, transfer all the data from the export file except for the moped profile.

**Comment by Isolator70** [comment]
**Steps for reproduction found!**

I reset my moped profile and achieved the same result like @Zirochkabila - a legal routing.
BUT: If I **change the "Standard Speed"** in the Navigation setting, vehicle parameters - which is much to slow in the default setting - to realistic/personal values of my scooter, the illegal routing happens.
Max Speed was set to maximum (53 km/h), Average Speed to 40 km/h.
After that, the illegal routing happens.

**Comment by scaidermern** [comment]
Indeed, I can reproduce this. Increasing the standard speed leads to wrong routing.

**Comment by Zirochkabila** [comment]
> Max Speed was set to maximum (53 km/h), Average Speed to 40 km/h. After that, the illegal routing happens.

OsmAnd~ 4.5.0#35877m, Released: 2023-05-02
If used these derivatives, then the route does change.


https://user-images.githubusercontent.com/104760013/235702993-d809adac-4582-4127-a10a-14f4135344a0.mp4

**Comment by Isolator70** [comment]
Talking about the Default speed values in OsmAnd for the Moped profile (they are way to low):

A modern scooter has a (minimum) max Speed of 45 km/h. Most are a little faster (maybe 48 km/h) even without modification, the modified ones (throttle in variator removed) go easily 55-60 km/h. As written in the starting post, the ex. GDR ones are allowed to go 60 km/h legally.

Going on Country roads most scooters are continuously full speed over longer distance.
So following two additional issues of OsmAnd are:

1. **Default speed:**

- Estimated **Default speed** of a legal scooter most probably is around **35km/h**.


2. **Max. speed:**

- Estimated **Max. speed default value** in EU should be **45km/h.**
- **Maximum speed value** range to be set should be **up to 65 km/h** (for tuned scooters or the ex GDR ones))

**Slider properties:**

- Currently the slider also offers float (i.e. 34.7 km/h), which makes reallly, really no sense (but most people mad, as the want to have a "x.0" value to be set. It is precise enough to have 1km/h increment.

**Comment by scaidermern** [comment]
> Talking about the Default speed values in OsmAnd for the Moped profile (they are way to low)

I've already created #17096 for this.

**Comment by xmd5a2** [comment]
@Isolator70 Hi. I've added priority section to moped routing. Now it builds the route like this:
![Screenshot_2023-05-30_10-10-19](https://github.com/osmandapp/OsmAnd/assets/5829014/ca66b8a7-16d2-4c96-8389-310a35cb7869)
This is 100% asphalt route and without any agricultural restrictions.

**Comment by Zirochkabila** [comment]
`50.49651, 8.47116` 
`50.51830, 8.48819`

4.4.10.1
OsmAnd~ 4.5.0#142m, Released: 2023-06-02

Works when the default speed exceeds 25 km
