### ISSUE TITLE
On 5th zoom Country names are more prioritized than capitals (also cities are sorted by population)

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#17038]
### To Do

- [ ] Display the capital at the 5th zoom level. How it was implemented for Japan, India

### Description
In a certain number of countries, such as China, Ukraine, Belarus, Turkey, Spain, the Netherlands, etc., the capital is not displayed at the 5th zoom level, however, other cities and regions are displayed

### Steps to reproduce

- Set the zoom level to 5
- Check out the countries mentioned above

### Actual result
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/233968890-92b975a6-a7a9-4195-bd6b-f16743289309.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/233968891-21546945-fc59-4220-b15c-3dbf595220c1.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/233968892-349984d9-a775-4912-87cb-ee44b6cd0b27.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/233969488-39658d7a-cf1e-4b84-87c2-ebc8e0914634.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/233969490-4edd3080-2d7f-47a9-8679-a7d2a97ae95e.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/233969492-c0483afa-e2de-43b8-a6c1-010deb546edc.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#35830m, Released: 2023-04-23
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by vshcherb** [comment]
On 5th zoom Country names are more prioritized than capitals (also cities are sorted by population) #17038
