### ISSUE TITLE
Turn restriction is ignored (live updates)

### ISSUE THREAD

**Issue by Peter0** [osmandapp/OsmAnd#17047]
# 🐞 routing report

### Routing engine

- [X] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Car

### Start and end points

From 50.73430 7.08827 to 50.73292 7.08749.

### Actual and expected routes

When routing with internal car router, a route via node 2132522412 is ignoring the turn restriction https://www.openstreetmap.org/relation/2727821
### Is this a regression?
OSMand 4.3.12 shows behaviour as well as OSMand 4.3.8. Therefore I think: No.

 Yes, the previous version in which this bug was not present was: ....

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

OSMand 4.3.12
</code></pre>

**Device and Android/iOS version:**
Samsung Galaxy J5. /e/OS equivalent to Android 9
**Maps used (online or offline): offline, one-hour- updates active.**

- [X] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**

**Comment by Peter0** [comment]
Complete map for Europe/Germany/NRW/Reg.-Bz. Köln. Hourly online updates active.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#35841m, Released: 2023-04-24
**Only** with live updates
[OsmAnd](https://osmand.net/map/?start=50.734194%2C7.088338&end=50.732713%2C7.087630&mode=car#17/50.73391/7.08874)
[OSM](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=50.73421%2C7.08819%3B50.73286%2C7.08751#map=17/50.73316/7.08855)


<table style="width:100%">
  <tr>
    <th>Without</th>
    <th>Live</th>
  </tr>
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/234212100-0c86205d-7fae-45ee-a9e2-e811cf270e61.jpeg"  width="300" height="auto"/> </th>
<th><img src="https://user-images.githubusercontent.com/104760013/234212114-edd18ef3-d632-43f1-98fa-bb09f9676987.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
Investigation result: https://www.openstreetmap.org/relation/2727832 (23.05.14 09:10 UTC)

**Comment by ivanPyrohivskyi** [comment]
Problem was with wrong generation of OBF files where present duplitated ID. In this case we can lose 100 000 nodes/ways in resulting OBF file.
Fixed in PR https://github.com/osmandapp/OsmAnd-tools/pull/637
