### ISSUE TITLE
Plan route with snap to roads

### ISSUE THREAD

**Issue by fixifoxy** [osmandapp/OsmAnd#17045]
### Description
I imported 2 gpx-tracks. And proceeded in both trials in the same way:
-plan route
-open existing track (attached herewith)
 n° 1=Pfronten-Vilstal...43km
n° 2=Tannheimertal Jagdhütte....31km
-choose profile  for n°1= gros tail from the french guy who published enduro as well
-                               n°2= osmands cycle profile
With n° 1 Track and profile nothing happened. No thin blue line. Osmand stopped with tne N° 1  Marking on his Osmand icon.
With N° 2 The blue line progressed to the end. No "done " button" appeared. I tried to save and attach the result.,      
  

### Actual result
The icon done do not appear at all. Icon "Save" is shown from the beginning.
a thin advancing blue is shown in the second trial. IN the first mentioned trial not at all.
When the first mentioned trial stops the Icon for the App Osmand in the main menue appears  with a number one figure.
But I do not know what that means.    

### Expected result
Let me start with a suggestion. Plan a route should start with something like a turning cercle so that the user knows the App has started to work and when the cercle stops turning the app had tone his job. The icon "done" appears" , change to "save" and the action is finished.   

### Your Environment
OsmAnd Version: 4.4.7
Android/iOS version: 13
Device model: Samsung S21 5G
[zipfile.zip](https://github.com/osmandapp/OsmAnd/files/11313730/zipfile.zip)

**Comment by fixifoxy** [comment]
Follow up  with more concentrated tests.
Only 1 track, but two different profiles.
Both tests start with track Pfronten-before snapping
1. Profile Osmands cycle
Track copied to folder track. Plan route. Open existing. Chose track Pfronten. Map screen opened showing the track.
To show the button "save" in the roght corner of the screen is without use at this stadium. Clicking at the round button at the left side of the bottom screen. Selecting Osmands cycle profile. The  tiny blue line starts and progressed to the other side. No "done" is shown. But calculation seemed terminated. It may be possible to click ths button "save" but this is to overwrite the track we started with.
So clicking on "option". Save as new track. The result is in the zip-folder under "pfronten-after cycle snapping.."
2. Profile gros_trail.xml
as well joined in zip-folder
Proceeded as in 1. The tiny blue line started as well. But after about cm stopped. And never continiued even when waiting a while. After that while, Osmand finished. And in my menue screen the Osmand Icon somes up with a tiny number one figure.
I hope this more comprehensive the first remark.     
 
[fixifoxy.zip](https://github.com/osmandapp/OsmAnd/files/11330554/fixifoxy.zip)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#35865m, Released: 2023-04-29

Behavior described in https://github.com/osmandapp/OsmAnd/issues/17045#issuecomment-1522971950 is repeated with user tracks.
This issue is most likely related to this https://github.com/osmandapp/OsmAnd/issues/17083

**Comment by vshcherb** [comment]
This profile is broken it's based on   "derived_profile": "default",
which is non navigation profiile. So profile should be created based on bicycle
