### ISSUE TITLE
Offline Routing: Shortest route

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#1704]
Home ->Directions
From: Map: Lat 40,732, Lon-4,009
To: Lat 40,494, Lon -3,869

When Osmand calculates this route with shortest route option:
![screenshot_2015-09-16-01-18-56](https://cloud.githubusercontent.com/assets/12786225/9910031/4f6081e0-5c9b-11e5-9932-2b278d42777c.png)

When Osmand calculates this route with fastest route option:
![screenshot_2015-09-16-01-19-51](https://cloud.githubusercontent.com/assets/12786225/9910050/5effe4c4-5c9b-11e5-811f-1e1189b14bc5.png)

First route is longer than the second one. It is a bug?

**Comment by OpenSourceForEver** [comment]
From: Map: Lat 42,302, Lon -5,894
To: 42,533, Lon -5,878

According to Osmand, fastest route 0 h 36 m, Shortest route 0 h 31 m.

Fastest route:
![screenshot_2015-09-19-17-03-18](https://cloud.githubusercontent.com/assets/12786225/9976844/e1c7c492-5ef0-11e5-865f-e9609bd42b6c.png)

Shortest route:
![screenshot_2015-09-19-16-54-42](https://cloud.githubusercontent.com/assets/12786225/9976845/fa908946-5ef0-11e5-82d8-ce1fe131437a.png)

**Comment by vshcherb** [comment]
The issues are no longer reproducible, might be fixed already
