### ISSUE TITLE
Temporary access restriction ignored

### ISSUE THREAD

**Issue by Peter0** [osmandapp/OsmAnd#17048]
# 🐞 routing report

### Routing engine

- [X] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Car
### Start and end points

From 50.73360 7.08573 to 50.73430 7.08827.
### Actual and expected routes

When routing with internal car router, a route via node https://www.openstreetmap.org/node/10830758587 is ignoring the temporary restriction on this node.
When going from west to east along Endenicher Straße, i.e. against direction of way in OSM data, the router is going through the node.   
### Is this a regression?

 
OSMand 4.3.12 shows behaviour as well as OSMand 4.3.8. Therefore I think: No.
## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

4.3.12
</code></pre>

**Device and Android/iOS version:**
Samsung Galaxy J5. /e/OS equivalent to Android 9
**Maps used (online or offline):**

- [X] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 
Complete map for Europe/Germany/NRW/Reg.-Bz. Köln. Hourly online updates active.
**Anything else relevant?**

**Comment by scaidermern** [comment]
I think this tag belongs to a way, not to a node. If you add it to a node then probably some additional tag like barrier is required. Looks like a mapping error to me.

**Comment by Zirochkabila** [comment]
@Peter0 It looks like a mapping error (you can try to build a route in OSM and all three types of routers will build the route). Please make sure the tag is correct

**Comment by scaidermern** [comment]
Can confirm, doesn't work for me either (newest map + live updates, OsmAnd 4.4.7).
Maybe vehicle:backward:conditional isn't supported by OsmAnd?

**Comment by Peter0** [comment]
Added a oneway tag. Let's see what happens.

**Comment by xmd5a2** [comment]
Tag is present on OsmAnd routing data:
`
Road 74586547197 osmid 1165414799 cycleway:both='lane' cycleway:both:lane='advisory' highway='residential' lanes='2' lit='yes' maxspeed='50' oneway:bicycle:conditional='no @ (2023 Apr 11-2023 May 31)' oneway:conditional='yes @ (2023 Apr 11-2023 May 31)' sidewalk:both:surface='paving_stones' smoothness='intermediate' surface='asphalt' vehicle:backward:conditional='no @ (2023 Apr 11-2023 May 31)' osmand_ele_start='59' osmand_ele_end='58' osmand_highway_integrity_brouting='0' sidewalk='yes' name="Endenicher Straße" name:etymology:wikidata="Q153759" pointtypes [[1. vehicle:backward:conditional='no @ (2023 Apr 11-2023 May 31)' 50.73403 / 7.0877237 ]] lat/lon : 50.73403 / 7.0877237 , 50.73401 / 7.087657 , 
`

**Comment by xmd5a2** [comment]
Now routing is correct is all directions (towards west and towards east). Closing.
![Screenshot_2023-05-26-16-41-17-027_net osmand plus](https://github.com/osmandapp/OsmAnd/assets/5829014/2d003324-ef2b-48cb-95f7-b68a05a09986)
![Screenshot_2023-05-26-16-43-18-980_net osmand plus](https://github.com/osmandapp/OsmAnd/assets/5829014/4c33cc66-4e99-45a1-a9b5-7134c95a85b1)

**Comment by Zirochkabila** [comment]
4.4.10.1
OsmAnd~ 4.5.0#142m, Released: 2023-06-02

<table style="width:100%">
  <tr>
    <th>From West to East</th>
    <th>From East to West</th>
    <th>From West to East</th>
    <th>From East to West</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/b71ba632-b399-445e-8b55-b597ed5267a9"  width="300" height="auto"/> </th>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/83f5c31c-5e12-4d87-bafc-79e3bc637f59"  width="300" height="auto"/> </th>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/0ba5fc23-2435-4a4d-88b9-7e27cd91f2d0"  width="300" height="auto"/> </th>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/de5fcacd-6a48-422a-89a1-bec68adef137"  width="300" height="auto"/> </th>
  </tr>
</table>
