### ISSUE TITLE
Offline tiles cache freeze OsmAnd

### ISSUE THREAD

**Issue by luigifab** [osmandapp/OsmAnd#17057]
### Description

I configured OsmAnd to display _OpenTopoMap_ tiles with the **Online maps** plugin.
There are no problems, the tiles are downloaded, cached and displayed.

On my computer, I created an OpenTopoMap tiles cache. I have now 220,000 files / 5 GB.
So I copied these files into my phone (SD card) into the right directory (_Android/obb/net.osmand/tiles/OpenTopoMap_).

### Actual result

Now when I start the application, the application won't start (I have a gray screen with the logo, and without the bottom text)
Do you have some index processes? why?

Perhaps this is the same problem as #1932.
Solution is to stop it, and to rename the tiles directory.

### Expected result

No problem.

### Your Environment

OsmAnd Version: 4.4.7
Android/iOS version: Android Go 11

**Comment by Zirochkabila** [comment]
@luigifab Try changing the rendering type: Menu > Settings > OsmAnd settings > Map rendering engine
Or move the maps to the internal memory - Android may be blocking the system's access to the folder where the maps are located

**Comment by luigifab** [comment]
I try to change the setting, but same, the application won't start.
I don't understand how to move the maps into the internal memory (my SD card is used as an extension of internal memory).

**Comment by Zirochkabila** [comment]
@luigifab You can change the storage type in the app: 
**Menu** > **Settings** > **OsmAnd settings** > **Data storage folder** > **External storage 1**

Also, try transferring files using the following path: 
**Android** > **data** > **net.osmand** > **files** > **tiles**


<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/235346604-553306f5-5594-4fd7-88f3-c6835110d2f9.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/235346602-6ae61a74-cc85-4448-9fd4-0eb7368cde45.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
There is an index process, OsmAnd requires specific indexes for tables to have. Obviously if they are not created it can take 5-10 or more min for 5GB to start. You can repackage sqlite database with OsmAndMapCreator tool on your computer first.
