### ISSUE TITLE
At creating a new track, the center of map moves to the point where finger touches map

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#17051]
### To Do

- [ ] Display the map center icon in the center, as implemented in 4.4.7

### Description
When creating a GPX track and move the map by touching the screen fingers, map center icon is attached to the place where finger touches the map

### Steps to reproduce
Menu 

- Plan a route 
- Create new route
- Move the map by touching the screen fingers

### Actual result

https://user-images.githubusercontent.com/104760013/234227983-697b8106-799a-4170-9b40-e63aebd50f7a.mp4

### Expected result

https://user-images.githubusercontent.com/104760013/234228022-e81a4b8e-c4f7-47d7-9b70-c92f2d4951ec.mp4

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#35841m, Released: 2023-04-24
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by vshcherb** [comment]
Should be fixed with https://github.com/osmandapp/OsmAnd/pull/17052

**Comment by dmpr0** [comment]
Depends on https://github.com/osmandapp/OsmAnd/issues/16965
