### ISSUE TITLE
Hide Polygons (water)

### ISSUE THREAD

**Issue by Gizmot** [osmandapp/Osmand#1705]
For car driving, where distractions must be kept to a minimum, I like to have a screen as clear as possible. That means turning off buildings, polygons, buildings, etc. My issue arise from the fact that disabling polygons removes not only useless stuff such as grass vs forest, but also water. River and oceans are pretty good landmark... I like to see it.

My idea would be to split hide polygons between "Hide polygons (water only) and Hide polygons (all except water).

**Comment by RicoZ-OSM** [comment]
My guess is this feature was created for efficiency reasons - drawing polygons may be costly.

So if rendering efficiency is not your problem you might  want more options in the Details/Hide/Transport menus instead of this.

**Comment by Gizmot** [comment]
This is exactly what I'm asking: an other option in the Hide menu.

Not trying to derail my own bug report but, I kind of dislike the hide menu. Its like a double negative where checking an option turn off stuff versus all the other menus were checking an option turn stuff on.

**Comment by vshcherb** [comment]
Hide polygons was introduced in order to use with mixing satellite images, for that purpose hiding any polygons is good.

**Comment by xmd5a2** [comment]
Agree with Victor. Two switches can be confusing to users which use satellite images. Maybe introduce this change when our UI can switch all inner options of a group.

**Comment by vshcherb** [comment]
I think original issue is already solved by using "Road only maps" which don't include buildings, but do include large forests and water, please try it.

These new road only maps are working only in nightlies still
