### ISSUE TITLE
Straight road lines after downloading map of Romania

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#17054]
### To Do

- [x] Do not display straight lines of roads

### Description
After downloading the map of Romania, the map displays straight lines of roads connecting Kherson region, Odesa, and Crimea. Although, in fact, there are no such roads

### Steps to reproduce

- Download the map of Romania
- Change the zoom level to 8x

### Actual result

https://user-images.githubusercontent.com/104760013/234313473-4b0f78b8-64f1-4f16-bb3c-f54e5bed0dba.mp4

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#35841m, Released: 2023-04-24
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by vshcherb** [comment]
Need to be retested with May maps
