### ISSUE TITLE
Incorrect direction of stream flow

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#17055]
### To Do

- [ ] Direction of flow of the stream should be similar to the direction of flow of the Mark River

### Description
Direction of flow of the [stream](https://www.openstreetmap.org/way/398262635#map=19/50.74187/3.89628) differs from the direction of flow of the [river](https://www.openstreetmap.org/way/933018874#map=18/50.74176/3.89592) 

### Steps to reproduce

- Find this river `50.74116° N, 3.89400° E`

### Actual result
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/234330992-e1de029e-36f5-4963-a658-f4dc9fbdc913.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
River and stream flow is displayed from east to west

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#35841m, Released: 2023-04-24
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by vshcherb** [comment]
You gave the link to object https://www.openstreetmap.org/way/398262635#map=19/50.74187/3.89628 where it starts https://www.openstreetmap.org/node/1221715697. So it's obviously incorrect data and you didn't state that we should change the data, so it's not a program bug.

**Comment by scaidermern** [comment]
I've added a map note: https://www.openstreetmap.org/note/3660414
