### ISSUE TITLE
Download online tiles: last "Map source"  is used instead of selected as Overlay

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#17062]
## Description
Last used map in **Map source** is download when user try to download online tile map set as **Overlay**, where other source is selected.

## How to reproduce
* Open **OsmAnd** – **Menu** – **Configure Map** – **Map source** 
* Choose **Microsoft Earth** as source, close the menu
* Re-open **Map source**, change it back to **Offline vector maps**
* In **Configure Map** go to **Overlay**
* Set **OpenRailwayMa**p as an **Overlay**, close the menu go back to map
* Open context menu on the map – **Actions** – **Download map**

### Actual result
* Preview will show tiles for Microsoft Earth
* If you start download, it will be download Microsoft Earth

<table style="width:100%">
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/234538653-ee8b20c1-b538-48b2-bac1-cf085390d54e.jpg"  width="300" height="auto"/> </td>
  </tr>
</table>   

### Expected result 
* Source selected as Overlay will be downloaded

**Comment by vshcherb** [comment]
To do: estimated size is wrong by factor of 10, looks like related as well to "Map source" overlay

**Comment by Zirochkabila** [comment]
Unable to check, waiting for a solution https://github.com/osmandapp/OsmAnd/issues/17079

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#35864m, Released: 2023-04-29
Approximate size still differs from the actual size by a factor of 6 or 4 times


<table style="width:100%">
  <tr>
    <th>6</th>
    <th>4</th>
  </tr>
  <tr>
    <td><video source src="https://user-images.githubusercontent.com/104760013/235295450-37255448-99c8-4151-a4ba-48cf067bf77b.mp4"  width="300" height="auto"/></td>
    <td><video source src="https://user-images.githubusercontent.com/104760013/235295452-6c469cfd-d4c9-4e38-a6bc-1a19bc7720ed.mp4"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
- Approximate size still differs from the actual size by a factor of 6 or 4 times
**To do** 
As we have tiles preview downloaded we should use these tile sizes to provide better estimate
