### ISSUE TITLE
Search is very slow

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#17075]
### Description

After tapping the search-button and entering the first three or four letters, it takes about two minutes until a result is shown.
Every following search is quick, results appear letter by letter.
After closing and opening Osmand, the first search again is very slow. 

### Actual result
slow
### Expected result
quick
### Your Environment
OsmAnd Version: +4.4.7.
Android/iOS version: 13
Device model: Samsung S20+

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#35877m, Released: 2023-05-02
@Rowin63  I can't reproduce it - the search responds quickly even with a cold start.
Please attach a video with the results

**Comment by Rowin63** [comment]
Hello!

I have a video (screen recorder) but it is too big and at the moment I dont know how to upload it here....
Its three minutes. The first search takes about 40s , the next search immediately following the first one, takes about 1m40s.

I´ll try...

**Comment by sonora** [comment]
Please note that in my experience the phenomenon seems related to how many maps you have. If you have only a handful, performance is ok, but quickly degrades with increasing number of (active) obf's.

**Comment by Rowin63** [comment]
I thought it may be the amount of favorites (~1500). So I deleted 3/4 of them, but it did not help.
I´ll try disabling some maps ;-)

**Comment by Rowin63** [comment]
Deactivated all maps but one (Austria)
Deleted all Wikipedia files.

Still the same. 
Initial search takes 1-2 minutes, next search is quick (results follow every letter). Seems like some kind of indexing...?

**Comment by Rowin63** [comment]
Yes, thats it.
I always use "multiuser 1" (obb), because there I have access to all data.
Now its "external storage 1" (data).

But why it´s like this? I always used multiuser 1 and the search never was that slow?

**Comment by Rowin63** [comment]
Now after changing the storage folder I did reactivate all my maps (~50) again and search still is quick.

**Comment by sonora** [comment]
Yeah, it's a nuisance. If you want to store the app data on the SD card, with normal performance, and accessible for backup and sync, then https://github.com/osmandapp/OsmAnd/issues/16059 seems the only viable "solution" these days.

I use my own compilation. Chances are the f-Droid version also supports "All files access", not sure.

**Comment by sonora** [comment]
Regarding

> Initial search takes 1-2 minutes, next search is quick (results follow every letter). Seems like some kind of indexing...?

It is really worth investgating if there is no better way to handle this, i.e. what takes 1 minute the first time around, and couldn't that be cached in some fashion.

**Comment by Rowin63** [comment]
It´s not only the search, also the list of "recent places" needs this time to be displayed.

**Comment by sonora** [comment]
I've experienced this a few times, too, now. Looks like it can be fixed by changing data folders back snd forth.

Perhaps the index somehow becomes bad? Perhaps an easy fix is we provide a way  to reset the index?

**Comment by vshcherb** [comment]
There is no index on search I think it's related how sdcard storage optimized by system... whether it provides fast IO and slow IO

**Comment by vshcherb** [comment]
May be it's related to indexes.cache file...

**Comment by Rowin63** [comment]
Just want to say, storage was not SD, but internal memory: before multiuser 1 (search slow), now external 1 (search quick)

**Comment by sonora** [comment]
@vshcherb Yes, I think may be the ind.cache file. It seems faster now, will test deleting it when it becomes slower again.

If it is: Many users will not have access to it, so it may ne worth doing someting about this automatically or via menu..

**Comment by Rowin63** [comment]
It seems, the "slow search problem" (it takes up to three or more minutes until the history is displayed) is also a variant from this "loading large tracks extending memory"-problem. I think, once the "displaying tracks process" is finished, finally the search history appears. Can´t be really sure, because it is not possible to watch both processes side by side. But without any tracks on display the search history appears much earlier (it still takes about 25s but not several minutes).

**Comment by sonora** [comment]
Interesting... v2 engine only, or regardless?

**Comment by Rowin63** [comment]
I think it´s regardless. Searching times are always different.
But, as mentioned before, I really can´t say what´s the cause.
Still I´m trying around so much with the "tracks-OOM-problem". And sometimes the search result is displayed in 10s, some other time it takes up to 3min. I don´t know if the app then still is busy in the background (processing tracks) or not or something else. It´s impossible to me to compare all possibilities, because I never can act in a menu (search, tracks, ...) and at the same time see how busy the app is, working on the previous command.

I performed a few searches now. The result was between 10s and 2:30min. One of the searches caused a crash. The same search takes different times. Search with tracks on display takes longer than without tracks. It seems to make a difference, if the tracks on display are still processed and not finished yet on display. V1 seems quicker than V2, but sometimes vice versa. So confusing.

I really would like to find out and clearly reproduce it, but sorry, I can´t. The app´s behaviour confuses me. Analyzing this is seems to be beyound my limits...

Anyway there is something wrong with the search, as mentioned in the other issue (history is endlessly filled up with my displayed tracks, and the favorites I searched for are not listed in the history thats seen by the magnifying glass).

**Comment by Rowin63** [comment]
To complete my confusion: after moving back the tracks folder into Osmand AND displaying the tracks, the search still is as quick as before. Results appear almost immediately.

I'm done. 
Once again I don't know what to do or not.

**Comment by Rowin63** [comment]
Was only a short "success". At the next use of the app the first initial search was behaving lame like before. Perhaps "slow" is the wrong term, it is delayed, until osmand is not busy anymore.. It took about four minutes for a result. Seems about as long as the attached logfile was processed. Then the search works fine.

[logcat.log](https://github.com/osmandapp/OsmAnd/files/12339284/logcat.log)

**Comment by sonora** [comment]
It's like this: Whenever this happens, kill OsmAnd and restart it: After the initial lag (until the search history appears) the search is fast again. Until you do sonething with tracks. I think this is the same issue as #18077.
