### ISSUE TITLE
After exiting the item in Configure map, the list returns to the beginning

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#17077]
### To Do

- [x] Save current position in list

### Description
If opened any item in Configure map and click "Back" - list is displayed from the beginning, and not in the place where the user opened item

### Steps to reproduce

- Configure map
- Hiking routes
- Back

### Actual result

https://user-images.githubusercontent.com/104760013/235089911-2e9af327-e2ad-4242-92a9-02938965f66c.mp4

### Expected result
Saves the current position in the list so user doesn't need to go back to the desired item again

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#35859m, Released: 2023-04-27
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by vshcherb** [comment]
Lag is separate issue not important for now.
