### ISSUE TITLE
Show "level" of POIs

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#1707]
Show the "level" tag in the POI details (NOT layer). This is useful e.g. in multistorey (-level) malls or public transport stations. The information can't be easily seen on the map as often indoor paths are not mapped or overlaps.

**Comment by xmd5a2** [comment]
Added

**Comment by aceman444** [comment]
Thanks.

**Comment by aceman444** [comment]
I updated to nightly build of 21th Sep and the latest live update of SK map but I do not see the Level shown on any POIs. Is the tag actually in the map files? Is it included in rendering_types.xml? Or is it a bug in live updates?

**Comment by xmd5a2** [comment]
It's ok:
transportation : bus_station  Lat 45.70717 Lon 36.519455 id=-7008953 level=6
Maybe related to live updates.

**Comment by vshcherb** [comment]
Live updates include only changed objects, so if the schema was changed it requires full redownload new map
