### ISSUE TITLE
Turn assist shows slight left at a right turn with Live Updates

### ISSUE THREAD

**Issue by mdykierek** [osmandapp/OsmAnd#17076]
At Złota x Bukowa intersection: https://www.openstreetmap.org/#map=19/50.27881/19.00297
I am supposed to turn right, while navigation shows slight left.

### Steps to reproduce
Navigate from Złota towards east on Bukowa

### Actual result
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/27214784/234964820-0f6199c6-7d41-46cf-b1e0-26de18fd4c9b.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
I'd expect turn right guidance (which is correct when Live Updates are off)

### Your Environment
OsmAnd Version: OsmAnd+ 4.4.7
Android/iOS version: Android 11
Device model: Mi 9T Pro

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#35877m, Released: 2023-05-02
@mdykierek Please update your maps to 01.05 and try again

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/235709315-c4f31ed7-68cb-4035-a0e8-bec9aba50052.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
Let's if it's reproduced later
