### ISSUE TITLE
Bug in Map (Wiesbaden/Germany)

### ISSUE THREAD

**Issue by ThomasMeister123** [osmandapp/OsmAnd#17071]
### Discussed in https://github.com/osmandapp/OsmAnd/discussions/16980

<div type='discussions-op-text'>

<sup>Originally posted by **ThomasMeister123** April 15, 2023</sup>
There is a bug in map at position 50.04238° N, 8.21260° E
The Highway has a "gap" here. I checked the data at OSM: there it is correct. I downloaded newest live-Update some minutes ago... Same gap... 
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/62500258/232242714-337d8621-646f-4283-9304-17220bfd542d.png"  width="300" height="auto"/> </th>
  </tr>
</table>  
</div>

**Comment by Zirochkabila** [comment]
Cannot be reproduced either with or without live updates - please download the nightly version (or an available update) and try again https://osmand.net/docs/versions/nightly_versions


https://user-images.githubusercontent.com/104760013/234966522-f21fc4c8-1a36-4070-8338-7b13128d4d7c.mp4

**Comment by ThomasMeister123** [comment]
I'm using OSMAnd+. But what does that have to do with the program version? If I use the old maps from January everything is OK, with the current maps it is not OK.

**Comment by ThomasMeister123** [comment]
OK, I see... The version 4.3.12 has the releasedate 2023-03-05... That's roughly the date since I've had the error in the map. So it's actually a BUG in the program

**Comment by Zirochkabila** [comment]
@ThomasMeister123  Perhaps it's
You might want to try updating

**Comment by ThomasMeister123** [comment]
> 

Where can I download a nightly(?) OSMAnd+ Version?

**Comment by ThomasMeister123** [comment]
I downgraded the App via ADB back to 4.3.8. Then ist works (with the same map-data). So its a Bug in 4.3.12

**Comment by ThomasMeister123** [comment]
> @ThomasMeister123 You can download nightly version here [#17071 (comment)](https://github.com/osmandapp/OsmAnd/issues/17071#issuecomment-1526199846)

"OsmAnd free" = "OsmAnd+"?

**Comment by hakuchi** [comment]
you can try to make a clean map download.
first delete all your maps and then download again.
Sometimes after years of only updating, some non reproducible bug in mapview can occur on you.

**Comment by ThomasMeister123** [comment]
> you can try to make a clean map download. first delete all your maps and then download again. Sometimes after years of only updating, some non reproducible bug in mapview can occur on you.

I've done that. The problem here is NOT the map-data. Its a bug in der App-version. I downgraded to an older version (without deleting anything) and it fixes the problem (same map-data!)

**Comment by Zirochkabila** [comment]
@ThomasMeister123 Can we consider the issue closed?

**Comment by hakuchi** [comment]
@ThomasMeister123 what is the date of your maps?
this bridge was edited a month ago. do you have tested with maps from 05.2023?
do you have updated all your maps, because with Rheinland-Pfalz this part is also updated/downloaded

**Comment by ThomasMeister123** [comment]
I tested it with the 04.2023 maps. Now I cant test it anymore, because I downgraded to a working version....

**Comment by vshcherb** [comment]
There was a glitch with planet generation May maps should be ok

**Comment by ThomasMeister123** [comment]
Thank you. I still stay at the old app-version. Never change a running system ;)

**Comment by vshcherb** [comment]
i keep using 2 versions - 1 latest and 1 released as a backup system in case of emergency
