### ISSUE TITLE
Long pressing misses target at high elevations with map tilt

### ISSUE THREAD

**Issue by mikehgentry** [osmandapp/OsmAnd#17084]
### Description

[N.B. this might be fixed in nightly, but I don't think I can test it because I don't think nightly has the 3D mode]

Map tilt causes long press to miss its target at high elevations

### Steps to reproduce

Enable 3D view, tilt map significantly, find a big hill.

Tap on a spot (e.g. a town or a POI).

Now long press on the same spot.

### Actual result

The long press selection misses the target significantly (proportionally to how tilted the map is, and the elevation of the target)

### Expected result

Tapping and long pressing select the same spot

### Your Environment
OsmAnd Version: 4.4.7+
Android/iOS version: 11
Device model: Xcover 4s

**Comment by Zirochkabila** [comment]
@mikehgentry The nightly version has a 3D mode https://osmand.net/docs/versions/nightly_versions

**Comment by mikehgentry** [comment]
@Zirochkabila My mistake. Unfortunately it requires Pro features - if I try to enable the heightmap in OsmAnd Development, I am taken to the 'Purchase Pro' screen, and selecting 'Restore purchases' does nothing. I can file a separate bug for that, if it is in fact a bug.

**Comment by mikehgentry** [comment]
@Zirochkabila 

Tested it on a different phone linked to the same Google Play account (where I get the same problem, but where in OsmAnd+ all prior purchases are automatically restored upon installation).

Maybe the problem is that OsmAnd+ is a different application as far as Google Play is concerned...

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#35885m, Released: 2023-05-03
If tilting  map as much as possible, you can't select the same location by tapping and long pressing


https://user-images.githubusercontent.com/104760013/235947105-184141d4-d196-46b3-9f00-d38a1202e379.mp4

@mikehgentry You shouldn't cancel subscriptions - we need to analyze this behavior

**Comment by mikehgentry** [comment]
@Zirochkabila Fair enough - let me know if there's anything I can provide in the way of logs or similar.

**Comment by vshcherb** [comment]
Fixed in latest builds

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/pull/17097
