### ISSUE TITLE
Voice/screen navigation instruction has a delay when following gpx attached to road in profile bicycle

### ISSUE THREAD

**Issue by K-Krs** [osmandapp/OsmAnd#17090]
Since osmand 4.3 or 4.4, the voice and screen navigation is delayed following an imported gpx using the Osmand routing engine. During the trip, the orientation of the current location on the screen is correct. The arrows indicating going left or right and the voice instructions lags after a couple of kilometers and sum ups to a lag of up to 400m behind the actual location. 

Day 1 april 29, i have used a gpx. When starting my cycling trip, I start the navigation and Osmand asks to attach the gpx to the roads. I accept this option. I have the original gpx and the recorded gpx and lot of screen prints in the included zip-file.

Day 2, april 30. I have used the plan route. Plan route along a predefined gpx. Both the original gpx as the newly generated GPX (PR Westerbork) using the navigation engine of Osmand is included in the zipfile. 

After a recalculating route, sometimes the navigation instructions is spot on. After a few kilometers, the lag of the voice/screen navigation increases.

Both days, same result. A delay in the navigation instructions which makes it voice and screen navigation unusable.

During my bicycle trips, to save battery, i have turned off my screen and rely mainly on the voice instructions. To look at the screen, I use the power button to turn the screen on and again off.

Animate my location on or off makes no difference.
Version 2 (OpenGl) rendering

Profile, cycling
Osmand 4.4.7
Android 13
Samsung A52
[04 29.zip](https://github.com/osmandapp/OsmAnd/files/11362243/04.29.zip)
[04 30.zip](https://github.com/osmandapp/OsmAnd/files/11362244/04.30.zip)

**Comment by K-Krs** [comment]
Did today a small cycle trip. In the beginning, navigation instructuctions (voice and screen) were in sync with my locations. Voice instructions were clearly on time. Later on the trip, somewehere the navigations instructions came too late. There was a delay for about 150 meters introduced. So the turn/left instructions came about 150 meters after the moment I took the turn. Note that the arrow indicating my location on my smartphone screen is spot on. This delay keeps the same till the end of my trip.

**Comment by K-Krs** [comment]
Bug seems to be introduced in version 4.3 or 4.4. Never had problems before.

**Comment by Zirochkabila** [comment]
@K-Krs  I was unable to reproduce the result you described.
There is a possibility that the tracks you sent were damaged during creation or import, as the simulated navigation on them works with a long delay or does not work at all - try creating similar tracks along the same route and try again (using Plan a route from OsmAnd as well). 
A similar test of voice guidance on the same route, but with manually created tracks, was carried out - no problems were found.
Also, please note that the track must be connected to the road or created using the profile you need.

**Comment by Lebuin** [comment]
I also encounter this issue as well sine a few weeks, whenever I use Osmand to follow an imported gpx track (using "Attach to roads"). The issue becomes already apparent when starting the navigation: the first few direction arrows are in the correct place (and when you arrive at those places, the spoken directions will also have the correct timing), but after a few km, the direction arrows are drawn after the relevant intersection. See screenshot for an example. 
![Screenshot_20230518-204250](https://github.com/osmandapp/OsmAnd/assets/3847197/99ddcdca-4c58-4a5d-b951-eec4bf695b13)

**Comment by K-Krs** [comment]
Hi,
Thanx fort his response. Today I did another bike trip, and recorded my screen. The delay is obvious in the video's. Unfortunately the voice navigation has not been recorded. Voice and screen navigation are the same.

The original GPX is: do 18 mei hemelvaart 2023 60 km.gpx
The recorded GPX by osmand is: 2023-05-18-12-25_thu.gpx

My way to follow this track in Osmand (video start c)
1)	i Add the original GPX to Osmand via Add places. 
2)	Start navigation
3)	Select the GPX file
4)	Osmand ask to attach to road
5)	I confirm
6)	Select Bike (Fiets in Dutch)
7)	Select the distance
8)	Select Pas Toe (Ok)
9)	Navigation starts
Video start shows my way of working (from #4)

Video 1 is the most interesting where you can see how the navigation instructions has a delay versus the actual position
00:00:03 Navigation tot he right 283 meters, while I have to go to the left (exit #1)
00:00:49 Now the navigation instructions is at the point 183meters before exit #1, Next Exit #2 is 133 meters away. I’m already going tot his exit #2
00:01:25 I am on exit #2, while the nav instructions is at exit #1, exit #3 is another 175meters away. I am going towards exit #3 in real
00:01:51 I am on exit #3, while navigation instructions is just after exit #2
00:02:19 navigation is at exit#3, while my position in real is at least 100-200 meters after exit#3

The GPS on my phone is ok. As Osmand shows my location on the map on the actual position where I'm cycling.

Video 3 shows some other interesting thing. Somehow, Osmand recalculates the navigation at 00:00:15.

Have more video's to share. 

Hope these video’s helps to reproduce the error.

Regards
[18 05c.zip](https://github.com/osmandapp/OsmAnd/files/11510874/18.05c.zip)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#64m, Released: 2023-05-22
The video shows where the voice prompts and widget prompts fail (when simulating a location on GPX x3, this can be seen within 3 minutes) - it seems that the failure is caused by Waypoints. At least after passing them, the voice prompts and turn arrows in the widgets start to differ from what is on the map.


https://github.com/osmandapp/OsmAnd/assets/104760013/b175979c-7cb3-44b4-912a-d7a3de3d1421

**Comment by K-Krs** [comment]
I did recently another tour. I deleted all the waypoints in the gpx file using gpx.studio. The delay is not that worse anymore. The first about 20 kilometers the voice navigation is accurate. After some point, Osmand signals: you have reached your destination.  I cannot find that marker in the attached gpx file. My actual destination is about 50 km ahead.
From that point, the voice navigation instructions is about 200 metres late. The delay isn't increasing and keeps rougly about two hundred meters, 
[NO WP zondag 2 juli appelscha 70km.zip](https://github.com/osmandapp/OsmAnd/files/11951471/NO.WP.zondag.2.juli.appelscha.70km.zip)

**Comment by 9Biker** [comment]
Auch mit Version 4.5.5 treten bei Navigationsanweisungen immer noch Verzögerung auf.
Es wäre Wünschenswert wenn OsmAnd+ das Problem bald in den Griff bekommen würde weil eine 
Motorrad Navigation so nicht möglich ist.

------------------------------------------------------------------------------------------
Even with version 4.5.5 navigation instructions are still delayed.
It would be desirable if OsmAnd+ would soon get the problem under control because a 
motorcycle navigation is not possible.

**Comment by K-Krs** [comment]
Removing the waypoints from an gpx file resolves not the issue. Attached .gpx file does not contain any waypoints and still after approximately 20km, the navigation instructions gets delayed and is about 200 - 500 metres to late with the proper annoucements. The nice feature "snap to road" is in this way unusable.
[warnsborn - wijhe 93km (terug).zip](https://github.com/osmandapp/OsmAnd/files/12072298/warnsborn.-.wijhe.93km.terug.zip)

**Comment by Lebuin** [comment]
My current workaround is as follows:

* Open a gpx route with Osmand to import it
* Follow the normal steps for navigation snapped to roads, but don't start the navigation, i.e. select the route -> Navigation -> Settings -> Follow track -> Attach to the roads -> Continue -> choose navigation profile -> Apply, but do not press "Start".
* Instead press Details -> "Download" button in the top right corner -> choose a new name -> Save.
* Exit the current navigation setup.
* Select the newly created route -> Navigation -> Start.

It's cumbersome, but it works for me.

@Zirochkabila Is there any way that we can help you find the cause of this issue? This is 100% reproducible for me, and while I was able to find a workaround, I can imagine a lot of less experienced users are getting put off by something like this.

**Comment by K-Krs** [comment]
@Lebuin Thank you very much! This was a hidden feature for me. I will use the workaround and give feedback after my next trip. And indeed, for multiday trips, even more usefull!

**Comment by 9Biker** [comment]
Auch mit Version 4.5.6 treten bei Navigationsanweisungen immer noch Verzögerungen auf.
Bei Abbiegen links werden noch 268 m angezeigt.
![268 m](https://github.com/osmandapp/OsmAnd/assets/139489837/2ecfe0f7-b275-4901-8011-1e5e545ee04f)


Wird dieses Seite  https://github.com/osmandapp/OsmAnd/issues/17090 auch von OsmAnd Support gelesen. ?

**Comment by K-Krs** [comment]
the workaroud fixed at least for a small tour of about 45km. Thanx!!  
However, some navigation instructions are now too early. Befrote to exit, Osmand annouce to go right or left, while the exit is about 100m or 200m away. This is not consistent, as in the next turn, the navigation instructions are accurate in time. Don't know if this a known bug or do more people experience a too early instruction.

**Comment by 9Biker** [comment]
In Version 4.5.7 kann man jetzt keinen Track mehr simulieren, OsmAnd stürzt nach „Auf Straße einrasten“ ab.

**Comment by 9Biker** [comment]
In Version 4.5.8 wurde der Fehler von Version 4.5.7 
Track stürzt beim simulieren nach „Auf Straße einrasten“ ab 
wieder behoben. :-)

Zur Simulation ist folgendes zu bemerken.
Zum starten der Track Simulation gibt es 3 Vorgänge:
1. Track starten
2. Simulation Ein
3. Auf Straße einrasten
diese kann man unterschiedlich in Betrieb nehmen.
Je nach starten der 3 Vorgänge gibt es unterschiedliche Abläufe und Zeiten bis der Vorgang berechnet ist.

Das wichtigste ist aber daß es keine Verzögerungen in den Sprach-/Bildschirmnavigationsanweisungen 
soweit ich es in der Simulation getestet habe >250km mehr gibt. :-)  

Hoffentlich bleibt dieser Zustand auch in neueren Aktualisierungen erhalten. :-)

**Comment by 9Biker** [comment]
Heute OsmAnd 4.5.9 auf der Straße mit GPX Track getestet.

Kommt man an eine Abbiegung werden unter „Nächste Abzweigung“
noch ca. 10 > 20 Meter angezeigt. 
Erst unmittelbar nach nach dem Abbiegen geht die Anzeige auf 0 Meter b.z.w. wird die nächste Abbiegung angezeigt.

Nach ca. 150 km ist das Display mit OsmAnd eingefroren.

Auch die Bedienung „Externe Eingabegeräte - Tastatur“ funktioniert bei mir mit verschieben nur verzögert,
mit einer anderen Navi App geht das verschieben problemlos.

**Comment by K-Krs** [comment]
This issue seems to be solved in version 4.5.10. Navigation did works allmost flawless today. Will probably do some more biking trips in the upcoming weeks. If the behaviour of the navigation instructions keeps working as promised, you can close this issue.

**Comment by 9Biker** [comment]
Die Verzögerungen sind in Version 4.5.10 an einer Abzweigung nur noch minimal und aus meiner Sicht akzeptabel.
