### ISSUE TITLE
Folow current position since start

### ISSUE THREAD

**Issue by davidebaldini** [osmandapp/Osmand#1709]
**Wish:** add setting to automatically start the app in "follow position" mode, without the burden to press the relative button at every start.

**Rationale:**
I mounted an android phone in my car in such a way that, when I turn the key, the phone boots and osmand starts, when I turn off the car, osmand closes and the phone goes off. The phone is fixed on my dashboard and is dedicated to the car.

Now, when osmand is started, the first thing it displays is its starting menu with a few large buttons. I have a script installed in the phone which automatically presses the "back" button after x seconds since boot, so that it automatically closes this menu and have osmand show my map.
But when this happens, osmand does not automatically follow my car position as I wander around the town, instead, it statically keeps showing some other area of the map around me and there it remains.

If I manually tap the "follow" button (or however it is named) on the lower right hand of the screen, osmand correctly follows my vehicle as I move. But this is a behavior I'd like to achieve automatically, without having to manually tap my phone whenever I start the engine.

Is it or would it be possible to implement such a setting to automatically follow the current position as soon as osmand is started? After all it's just a simple option, definitely self-explanatory for all users and it would make osmand more flexible for people requiring more flexibility :)

**Comment by vshcherb** [comment]
Implemented by default linking to map location.

**Comment by davidebaldini** [comment]
If it's implemented by default, it doesn't work for me; as Osmand starts, it doesn't follow my car as I move.

**Comment by vshcherb** [comment]
Did you test the nightly build already?

**Comment by sonora** [comment]
Can confirm in nightly, thanks!
Great feature also that in nightly we can also start the app directly to the map screen now, no scripts needed anymore ...:)

**Comment by davidebaldini** [comment]
Excellent.

When will the nightly be available on the playstore? I'm not familiar with manual installation.
