### ISSUE TITLE
Travel guide categories bug

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#17101]
### Description

Categories of Travel guides disappear when we reopen the Track Context menu > Points

### Steps to reproduce

1. Download guide and open the track Contex menu > Points

Here we see all categories: all, buy, do, drink....

2.  Close the Track Context menu

3. Tap on any Guide Point on the map > "Open Track" button

4. The Track Context menu > Points. Now we see only ALL and Sleep Categories on the points list:

But on the map, we see All points from all categories

5.  Next, when we go to the Travel guides menu > the chosen article > Read > Points 

We see all categories again

<table style="width:100%">
  <tr>
    <th>1</th>
    <th>3</th>
    <th>4</th>
    <th>5</th>
  </tr>
  <tr>
<th><img src="https://user-images.githubusercontent.com/44466116/235646806-281a3db9-6c59-4d10-8807-c678b0304513.png"  width="300" height="auto"/> </th>
<th><img src="https://user-images.githubusercontent.com/44466116/235647238-f3eab710-52d9-4ef8-8d25-89176a897269.png"  width="300" height="auto"/> </th>
<th><img src="https://user-images.githubusercontent.com/44466116/235647418-47c15ee9-ebdb-439c-8b97-b3e02d0b34bc.png"  width="300" height="auto"/> </th>
<th><img src="https://user-images.githubusercontent.com/44466116/235648215-1e74f5c5-fd99-4a5a-a62c-4a1173e7d720.png"  width="300" height="auto"/> </th>
  </tr>
</table> 

### Actual result

Points categories disappeared

### Expected result

Points categories will be on the Points list

### Your Environment
OsmAnd Version:  4.5.0 # 35871m  2023-05-02
Android/iOS version: 11
Device model:  Samsung S10e

Travel Guides - Krakow / Kazimierz

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#35926m, Released: 2023-05-11

Perhaps it is worth adding an automatic transition to categories (those in the horizontal list) when scrolling through the vertical list.
Now, the categories in the horizontal list remain on "All" even if the user is at the end of the vertical list.


https://github.com/osmandapp/OsmAnd/assets/104760013/83eceba5-f829-4d79-b134-2fb4ccfee47f
