### ISSUE TITLE
OpenGL engine doesn't process textLength condition in icon style section

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#17104]
### To Do

- [ ] Display tree types on the map, as implemented with V1 rendering

### Description
Tree types are not displayed on the map. 
If using legacy rendering, trees are displayed

### Steps to reproduce

- Go to this place `50.21340° N, 27.09008° E`

### Actual result
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/235759817-29fe93b7-b4d5-4f99-9af7-418926c70dbd.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/235759846-e836c300-e060-4399-8847-6c96c94f87c3.png"  width="440" height="auto"/> </th>
  </tr>
</table>  

### Expected result

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/235760128-078138da-ef33-488c-8d64-b10662f45128.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#35877m, Released: 2023-05-02 / 4.4.8.3
Android/iOS version: Android 11 / iOS 15.7.3
Device model: Poco x3 nfc / iPad mini 4

**Comment by xmd5a2** [comment]
`textLength` doesn't work in OpenGL in `<icon>` style section.
https://github.com/osmandapp/OsmAnd-resources/blob/master/rendering_styles/default.render.xml#L6575
```
		<switch minzoom="12">
			<case tag="natural" value="wood" iconVisibleSize="24"/>
			<case tag="landuse" value="forest"/>
			<apply icon="wood" shield="wood_shield"/>
			<apply_if nightMode="true" shield=""/>
	=>		<apply_if textLength="0" icon=""/>
		</switch>
```
OpenGL engine just skips `textLength="0"` condition and removes all icons independent of `textLength`
