### ISSUE TITLE
The points of the tracks are seen in edit only with high zoom (<= 100mt)

### ISSUE THREAD

**Issue by Gbernardy** [osmandapp/OsmAnd#17107]
Bicycle profile

Track file 54 km, 86 points
[Mestre JESOLO LIDO 2023 via Altino.zip](https://github.com/osmandapp/OsmAnd/files/11370210/Mestre.JESOLO.LIDO.2023.via.Altino.zip)

Premise. 

Tracks with a bicycle profile generally have a length between 50km and 300km and up to 200/300 points can be used to track them.

 To follow a precise route, the routes are traced manually and therefore, depending on the map below, you can have both very close points (50mt, 100mt) and points distant from each other by one or more kilometres.

 Therefore, when these routes are modified, the points should be able to be seen starting from a zoom of at least 5km, otherwise it becomes almost impossible to view the points of the track and the consequent modification

This anomaly is present from version 4.2.6 (issue #14742 and #13809).

Tried again today with version 4.4.7, the track points being edited are visible only when the zoom is set to 100 meters.  With this zoom it becomes impossible to edit the track on a smartphone!!!

In track editing the track points are not displayed up to a zoom of 200 metres.
![IMG_20230501_151556](https://user-images.githubusercontent.com/99968793/235460719-7fc42d4f-5f54-49b1-978f-5a3e5b9c52d5.jpg)

Track editing with zoom 100mt, the point are visible ... but if I move the point on screen ... I can move it up to 200mt ... that is,  the track of 54 km is not modifiable.
![IMG_20230501_152127](https://user-images.githubusercontent.com/99968793/235460959-ce6079cb-defb-4d80-95ef-e2a6aee4046b.jpg)

**Comment by Gbernardy** [comment]
> Duplicate of #14742

To change the tracks that I use with the bicycle profile I have to use a second smartphone with version 4.1.11 installed which displays the points starting from the zoom set at 50km ..but it's not a very convenient solution 🤔.

![IMG_20230504_112930](https://user-images.githubusercontent.com/99968793/236166738-949339de-25ef-4fcd-8366-6dcf345a4ba3.jpg)

![IMG_20230504_113252](https://user-images.githubusercontent.com/99968793/236167122-c6a5f166-eeca-43b8-85aa-346b4141cad5.jpg)

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/14742
