### ISSUE TITLE
Apeldoorn is incorrectly extracted from db for basemap processing

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1710]
OSM data:
http://www.openstreetmap.org/node/216244216
What we get in cities.osm:
```xml
<node version="1" id="216244216" lat="52.2156456674474" lon="5.96394849876654">
	<tag k="place" v="city" />
	<tag k="population" v="155000" />
	<tag k="name:de" v="Appeldorn" />
	<tag k="name:fy" v="Apeldoarn" />
	<tag k="name:nl" v="Apeldoorn" />
	<tag k="name:ru" v="Апелдорн" />
	<tag k="name:sr" v="Апелдорн" />
</node>
```
There is no "name" tag. May be it is the source of name related problems?

**Comment by vshcherb** [comment]
It is very strange and if it is only Apeldoorn issue, I believe the error happened somewhere in the middle of incremental update. It is a big questions should we regenerate whole osm database or try to fix it manually (possible in database), but then we need to be sure we don't need to make twice.
