### ISSUE TITLE
Conflict between Map markers and Plane a route windows after reopening

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#17110]
### To Do

- [ ] After reopening, Map markers widget should not be displayed when working with Plan a route

### Description
When working with Plan a route, Map markers widget appears, after OsmAnd reopening

### Steps to reproduce

- **Menu** > **Configure screen** > **Top panel** > **Add Map marker bar**
- **Menu** > **Plan a route**
- **Reopening OsmAnd**

### Actual result

https://user-images.githubusercontent.com/104760013/235943823-7e6d6188-c33e-4c12-b653-6e31a61d913d.mp4

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#35885m, Released: 2023-05-03
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by Chumva** [comment]
This should be fixed [here](https://github.com/osmandapp/OsmAnd/pull/17114)
