### ISSUE TITLE
My Places > Tracks UI: confusing UI

### ISSUE THREAD

**Issue by plicplocplicploc** [osmandapp/OsmAnd#17116]
Hi, imported maps are visible in My Places > Tracks. I can then select tracks that I want to show on the maps by clicking the 3-dot button and pressing Show on map. When I return to the menu, the selected track will be shown under Visible, with a toggle button. Toggling the track using that toggle will remove the map from the Visible sub-menu (after leaving/returning to the menu), making the toggle button usable just once.

Tracks are also visible in Configure map > Tracks, where the UI feels more intuitive.

Perhaps merging the 2 menus, or having a more convenient way to show/hide tracks in My Places > Tracks, could make the UI better?

Thank you.

**Comment by sonora** [comment]
Looks related to https://github.com/osmandapp/OsmAnd/issues/17103.

**Comment by dmpr0** [comment]
We are working of redesign of My Places – Tracks, it will be available soon in the nightly versions.
