### ISSUE TITLE
How to make offline vector map for a specific place?

### ISSUE THREAD

**Issue by danialbehzadi** [osmandapp/Osmand#1711]
I downloaded the offline map for my country, but it only includes the main streets and not all of them!
I can download bitmap tiles from the openstreetmap, but this method has many disadvantages like low quality and large size.
How can I get the full vector data of my town from openstreetmap and make them available as an offline map with complete details?

**Comment by RicoZ-OSM** [comment]
Are you sure the area you are looking at is decently covered in openstreetmap?

You can get specific areas from http://extract.bbbike.org/ - select Osmand format

**Comment by vshcherb** [comment]
Check OsmAndMapCreator and documentation
