### ISSUE TITLE
TTS for Bikes is extremely faulty at roundabouts and slight corners

### ISSUE THREAD

**Issue by trytomakeyouprivate** [osmandapp/OsmAnd#17124]
I dont know how the TTS engine is made and it is really useful how it is.

But at specific scenarios it is extremely faulty, often giving orders in completely opposite directions. This happens at roundabouts:

1. Turn right
2. Stay left
3. Turn left 
4. Stay right
5. Turn right

Instead of "In the roundabout use the second exit" or "in the roundabout stay ahead".

Also at light turns, where in general you drive straight forward but first you first need to make a small exit to the right for a zebra crossing for example, it is also really confusing. It is comparable with the first example with many explanations instead of just "After a small bend stay straight on."

I will attach images of these scenarios.

In very rare cases it works that roundabouts are detected, but somehow really rarely.

I think in general it would be best to orient on larger direction vectors, so that this very small confusion is just ignored. In the end you drive/ride straightforward and not right-left-right.

This happens in 4.3.8 from F-Droid

**Comment by sonora** [comment]
This sounds like map data issues, can you please specify example coordinates?

**Comment by mikehgentry** [comment]
Also if you're generating your routes outside OsmAnd (or using an alternative router, such as brouter), you will probably get better results using 'attach to the roads'.

**Comment by trytomakeyouprivate** [comment]
This occurs everywhere so I dont think its a map issue really.

![Screenshot_20230421-190702](https://user-images.githubusercontent.com/113100745/236566360-de47a2ef-50d5-43cb-94b6-e6306fa0291b.png)

53.10660 8.27606

Is an example

**Comment by sonora** [comment]
Ok, thanks for the screenshot. Could it be that you forgot to mention that this occurs for bicycle routing only?

Can you please verify that for car routing roundabouts in these cases are correctly discovered and announced?

It seems to me the issue occurs in cases where there are cycle or foot paths, used by your selected navigation mode and next to roadway roundabouts, and (other than the roadway next to them) they are not detected as roundabouts.(Perhaps technically correct, they may not actually be roundabouts...?)

So perhaps this issue may need renaming from talking about "TTS" to something like "roundabout detection for cycle and foot paths:"?

**Comment by trytomakeyouprivate** [comment]
Yes this could be. I have not much experience going by car so cant say.

It can be that the road itself is pretty round and detected as such, but the shared path next to it is farer away so the lines are not as rounded and they are detected as normal turns.

Something changing the vectors is needed I guess.

**Comment by sonora** [comment]
Just try a route where you know it fails for bike by temporarily selecting "car" navigation, so we are not hunting the wrong issue. But I am rather sure that you would then both
- in the "on screen arrow display" would see a roundabout logo indicating the exit number to take
- and the voice announcements would also talk about a roundabout instead of detailed turn instructions.

**Comment by Zirochkabila** [comment]
@trytomakeyouprivate It was tested with the latest nightly version - not reproduced (video attached)

Try again with this version of [OsmAnd](https://osmand.net/docs/versions/nightly_versions/) 


https://user-images.githubusercontent.com/104760013/236687597-0cc933fe-a810-46a9-8f51-d3b9df8453d2.mp4


The issue may be:
1. App version (or the F-Droid version)
2. Date of the map update
3. Profile settings

**Comment by vshcherb** [comment]
In navigation there is a button to attach to the roads but we can make it more explicit and explain or probably run automatically
