### ISSUE TITLE
Map Doesn't Rotate With Map Rendering Engine 2

### ISSUE THREAD

**Issue by mikebela** [osmandapp/OsmAnd#17121]
**### Description**
Map doesn't rotate with map rendering engine version 2 (OpenGL), when map orientation compass direction or map orientation movemenet direction is activated - under **Samsung Galaxy A34** (Android 13 / One UI 5.1).

**### Steps to reproduce**
1) Settings - OsmAnd settings - Map rendering engine **Version 2 (OpenGL)**.
2) Map orientation: Compass direction, or Movement direction.

**### Actual result**
Map doesn't rotate.

**### Expected result**
Map should rotate.

**### Your Environment**
OsmAnd Version: **4.4.7**
Android/iOS version: **Android 13 / One UI 5.1**
Device model: **Samsung Galaxy A34 5G (SM-A346B/DSN)**

**Comment by Zirochkabila** [comment]
@mikebela  We are unable to reproduce the behavior you describe - please attach a video showing the steps to reproduce and the result. Also, please attach a video using V1 renderer for comparison.

You may find this article useful https://osmand.net/docs/user/personal/global-settings#location-source

**Comment by mikebela** [comment]
Hi @Zirochkabila ,  

Here are 3 files attached:
1) **System.png**: Information about the device and operating system.
2) **V1_Engine_Rotating.mp4**: Rotating map with "compass direction" activated (and when I'm rotating the device itself). This is the correct, expected behaviour.
3) **V2_Engine_Not_Rotating.mp4**: The direction-angle is rotating on the map,  when "North is up" is activated. So the compass itself is working. But the map doesn't rotate with "compass direction" activated, no matter I'm rotating the device itself. So the map remains blocked: it makes only very-very small micro-movements.  

It happens on Samsung A34 device (Android 13, One UI 5.1), but it NOT happens e.g. on Pixel 6A device (Android 13).


**System.png:**
https://user-images.githubusercontent.com/40147872/236489603-35ce9b42-ec33-47cb-9d34-ee36a5e84560.png
**V1_Engine_Rotating.mp4:**
https://user-images.githubusercontent.com/40147872/236489636-b7821ef1-6e35-4861-8d61-801271ce67f2.mp4
**V2_Engine_Not_Rotating.mp4:**
https://user-images.githubusercontent.com/40147872/236489666-1493ea20-f916-4683-be64-983ab9a33c72.mp4

**Comment by mikebela** [comment]
(...) Update:  

This is very strange:
Switching "Location source" from "Google Play Services" to "Android API" does activate the map-rotation,  
BUT even in that case the rotation is much more slower with Engine 2 than with Engine 2.  

SO:  
1) Samsung A34:  
          --> 1.1 "**Engine 1**": no issues  
          --> 1.2 "**Engine 2**":  
                    -----> 1.2.1 "Location source: _Google Play Services_": **no map-rotation at all**  
                    -----> 1.2.2 "Location source: _Android API_": rotating map, but **much more slower** than with "Engine 1"  

2) Pixel 6A: no issues.

**Comment by sonora** [comment]
Perhaps uncheck setting "Configure Profile > General settings > Use Kalman filter", it's purpose is to dampen motion and make things less jumpy, but it may at the same time also create your perception of things being "slower".

**Comment by mikebela** [comment]
The same Kalman filter is activated in both cases.
Let's see another video, just to compare and see,
there is a tremendous difference between Engine 1 and Engine 2.
Engine 1 does rotate the map (of course with its well known, uglier, oldish manner);
but Engine 2 is only struggling, Engine 2 it's not working in a reliable way.
Video:
https://user-images.githubusercontent.com/40147872/236536154-cb2c4a1b-03cb-417d-a8de-38ac84f807dc.mp4

**Comment by Zirochkabila** [comment]
@mikebela The only thing I can say is that when using the **Android API (Compass direction, V2)**, the map does not rotate, so you need to check with @vshcherb 
However, there is no such delay as in your videos.

**Comment by spongepaul** [comment]
I have potentially the same issue with my Samsung A51 (Android 13, One UI 5.1).
I have tried turning off the Kalman Filter, turning on the Magnetic Sensor, and different map sources, but V2 is always slow.
Lastly, I noticed clicking the 'configure map' button quickly jumps the rotation.  

Video Breakdown:
- 00:04 - Smooth V1 180 degree rotation 
- 00:17 - Smooth V1 180 degree rotation
- 00:37 - Very Slow V2 180 degree rotation
- 02:08 - V2 180 degree rotation pressing 'configure map' button

https://github.com/osmandapp/OsmAnd/assets/1760807/c256edca-66f9-4930-aeda-dbd6c30f7964

**Comment by vshcherb** [comment]
@Zirochkabila needs to be check on other devices

**Comment by Zirochkabila** [comment]
It has been noticed that on devices running Android 13, the animation on V1 responds faster than on V2 - perhaps this is due to a user request
[logcat.log](https://github.com/osmandapp/OsmAnd/files/11714891/logcat.log)

https://github.com/osmandapp/OsmAnd/assets/104760013/19b5fcba-5016-44ab-82f1-ce71b7114c14

**Comment by yuriiurshuliak** [comment]
The specified error was tested with two versions of the rendering under conditions of device rotation and gesture rotation. Reproducing was not successful, please specify more conditions to reproduce the problem.

Time codes:

Map rendering engine Version 2 (OpenGL). Device rotation:
00:00 - Map orientation: Movement direction.
00:10 - Map orientation: Compass direction

Map rendering engine Version 2 (OpenGL). Gesture rotation:
00:00 - Map orientation: Movement direction.
00:12 - Map orientation: Compass direction

Map rendering engine Version 1. Device rotation:
00:00 - Map orientation: Movement direction.

Map rendering engine Version 1. Gesture rotation:
00:00 - Map orientation: Movement direction.
00:13 - Map orientation: Compass direction





OsmAnd~ 4.5.0#391m, released: 2023-07-13

<table style="width:100%">
  </tr>
  <tr>
    <th>Map rendering engine Version 2 (OpenGL).
Device rotation.</th>
    <th>Map rendering engine Version 2 (OpenGL).
Gesture rotation</th>
    <th>Map rendering engine Version 1.
Device rotation.</th>
    <th>Map rendering engine Version 1.
Gesture rotation</th>
  </tr>
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/f0d16ad6-2976-4ecc-8f18-7b7432b96a9f"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/504b53a8-e7f0-432b-bc87-9b5133135f94"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/fc6e1b0e-3a77-4900-a0f5-3d5a0e72cf1d"  width="600" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/bbb71335-81e2-433b-afa1-aa4601a517d8"  width="600" height="auto"/>   </td>
  </tr>
</table>

**Comment by mikebela** [comment]
"please specify more conditions to reproduce the problem"

Is I'd been mantioned in the first posting:
"**Samsung Galaxy A34 (Android 13 / One UI 5.1)**".
It seems to me, this is maybe a device-specific sympthom:
- using "map rendering engine 1" it rotates flawlessly the map with "compass direction";
- using "map rendering engine 2" it doesn't rotate the map with "compass direction".
This happens even now, today.
[Other softwares like Mapy.cz or Organic Maps are rotating the map too with compass direction.]

**Comment by DmitryAlexei** [comment]
Device : a30s Samsung (Model SM-A307FN)
Android Version 11
App Version 4.4.7 4407 
[logcat.log](https://github.com/osmandapp/OsmAnd/files/12080090/2_5287775516483399689.log)


**Reproduced**
Map doesn't rotate by compass direction with map rendering engine version 2 (OpenGL).



<table style="width:100%">
  <tr>
    <th>Rendering version 1</th>
    <th>OpenGL</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/116079541/7a7fb2b2-3433-4b5e-9364-95b3b4a45426"  width="200" height="auto"/></td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/116079541/a2a48a8b-33c6-47b1-b055-3620dd02057b"  width="200" height="auto"/></td>
  </tr>

**Comment by DmitryAlexei** [comment]
OsmAnd 4.5.10, 2023-08-09
Map rendering 2
https://github.com/osmandapp/OsmAnd/assets/116079541/8e5e8f50-9515-4139-918d-d6b88807fc21
