### ISSUE TITLE
Menu does not respect the language I choose

### ISSUE THREAD

**Issue by miklcct** [osmandapp/OsmAnd#17129]
### Description
The menu doesn't respect the map language I choose, therefore I can't understand it.

### Steps to reproduce
Use English UI on English Android with map language set to Swedish.

Download the map of Helsinki (Helsingfors).

Tap a bus stop with a Swedish name.

### Actual result
The name shown in the menu, and in the stop list is not Swedish.

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/2827264/236638809-8f159a62-7863-46ac-94e4-5774386be4c6.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
The place names are in Swedish.

### Your Environment
OsmAnd Version: 
Android/iOS version: 
Device model:

**Comment by Zirochkabila** [comment]
@miklcct [Map Language](https://osmand.net/docs/user/map/vector-maps#map-language) and [Display language](https://osmand.net/docs/user/personal/global-settings#display-language)  is different settings

Try to make it this way: Menu > Settings > OsmAnd settings > Display language > Swedish

**Comment by vshcherb** [comment]
@Zirochkabila we need to have link to the object, names on the map are related to map language.

**Comment by vshcherb** [comment]
Beta build is out.
