### ISSUE TITLE
Add course over ground to navigation info on "boat" routing profile

### ISSUE THREAD

**Issue by a-0-dev** [osmandapp/OsmAnd#17127]
# 🚀 feature request

### Description

A crucial part of nautical navigation is knowing the course one needs to steer to arrive at the next waypoint. The course is currently not shown in the navigation info box in OsmAnd.

### Describe the solution you'd like

Additionally to the distance to the next waypoint etc. the course over ground (angle to the next waypoint in 360° format, e.g. 180° if the waypoint is directly south of the current location) should be shown as it is the primary info for the user during navigation.

It could even replace the "arrow box" (where turns, crossings etc are shown in normal street navigation) as these arrows do not make any sense on the water anyways.

### Describe alternatives you've considered

I am not aware of any feature in OsmAnd one can currently use to work around this. Of course one could steer until the arrow on the screen points to the next waypoint and then read the ship's compass, but that is highly inaccurate.

**Comment by mikehgentry** [comment]
Doesn't the bearing widget do this?

https://osmand.net/docs/user/widgets/nav-widgets/

**Comment by a-0-dev** [comment]
You are right, I wasn't even aware one could configure these panels (I expected the "left panel"/"right panel" buttons to only be able to toggle their respective visibility :D

Thanks a lot, that solves it!
