### ISSUE TITLE
Rendering is slow when internet is very slow

### ISSUE THREAD

**Issue by duiveldoder** [osmandapp/OsmAnd#17136]
### Description
So I have downloaded the offline maps for the Philippines (keep that in mind)
there's several possible scenarios:

1. I have fast internet (fiber, cable, dsl, anything >1Mbps)
2. I have no internet at all - no reception, airplane mode, etc
3. I have extremely slow internet. This is the one I notice this bug, and with slow I don't mean 50kbps I mean really like 0.1kbps slow!

### Steps to reproduce
You need very slow internet - but there's still some internet! Like 0.1kbps

So scenario one - I can scroll around, zoom-in and out, move over the map - all without any lag at all, at least not noticeable!
scenario two - ditto, I can do whatever I want, I notice no lag!

reason is obvious - I have my maps locally on the phone.. it doesn't need internet!

Scenario 3 - so now it's laggy! When I go right or left or north or south on my screen - I don't see the actual map data! I just see a grey background - and after 3, 4, 5, 10, 60 seconds - it shows me the actual map data I would expect. 

Now I don't know what's going on here of course - I can only suggest. Maybe despite having map data locally there's some online data from wiki or whatever it wants to download before rendering the map - although also that I have offline!

But regardless of such possible case why this is happening - the fact is the actual map data I have offline and it shouldn't lag on me like that!

IF there's something that OSM wants to download in the background - yet obviously omits if there's no internet at all - it should try to download that over very slow internet but at the same time it should show/render me the local stored data instantly nonetheless!

Thank you for your consideration to fix this bug!

### Actual result
Laggy scrolling despite offline data

### Expected result
fast scrolling since having offline data on my phon locally

### Your Environment
OsmAnd Version: 4.5.0#35904m released 2023-05-07 the full OpenGL version
Android/iOS version: 10
Device model: Huawei Mate 20 Pro

Note - my temporary solution right now if I am in an area with very poor internet reception - and OSM takes 30-60 seconds to show me the local stored map data for which it doesn't need internet in the first place - I switch on airplane mode on my phone and then everything is rendered instantly without lag!

But I mean - this is temporarily - obviously it shouldn't be the case a user has to switch on airplane mode to be able to use OSMAnd LOL

**Comment by scaidermern** [comment]
Can you reproduce scenario 3? It could be the same as #15801. Try to disable the display of OSM notes and check if the problem disappears.

I experience this slow rendering regularly when being outside in hilly terrain with bad mobile connectivity (which isn't that uncommon in Germany...).

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#35905m, Released: 2023-05-08

Test was performed at a speed of **0.24 KB/s** - the second video shows a delay of **3** and **8** seconds compared to the first video. It can be assumed that when the speed is 0.1, the delay will be greater. 
Most likely, this delay is caused by the display of other objects (routes, notes, etc.) on the map.

### Step to reproduse

- Set the connection speed to low (2g)
- Activate all items in Configure map (shown in the screenshot)


<table style="width:100%">
  <tr>
    <th>0.24 KB/s</th>
    <th>Fast rendering</th>
    <th>What need to activate</th>
    <th>Slow renderring</th>
  </tr>
  <tr>
    <th><img src="https://user-images.githubusercontent.com/104760013/236798928-422ee09b-58d8-4ff3-a7ea-386426ee8494.jpeg"  width="300" height="auto"/> </th>
    <td><video source src="https://user-images.githubusercontent.com/104760013/236799003-8869252e-261d-4bd6-b185-69756de73882.mp4"  width="300" height="auto"/></td>
    <th><img src="https://user-images.githubusercontent.com/104760013/236798933-57f8dd37-f393-4305-8233-6109cd13759e.jpeg"  width="300" height="auto"/> </th>
    <td><video source src="https://user-images.githubusercontent.com/104760013/236799073-7b3e908e-8e49-4da3-af25-9e4e0168f332.mp4"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by scaidermern** [comment]
Thanks for the fix!

**Comment by duiveldoder** [comment]
awesome - quick resolve of the issue 👍
