### ISSUE TITLE
Error generating final archive: Found duplicate file for APK

### ISSUE THREAD

**Issue by moosaviamir** [osmandapp/Osmand#1713]
I just cloned every thing and compiled jni folder. every thing is fine but when i try to run get this error:
[2015-09-18 05:43:40 - OsmAnd] Error generating final archive: Found duplicate file for APK: main/AndroidManifest.xml
Origin 1: E:\osmWorkspace\android-support-design\bin\android-support-design.jar
Origin 2: E:\osmWorkspace\android-cardview\bin\android-cardview.jar

how can i get rid of this error? i am using eclipse on windows.

regards

**Comment by vshcherb** [comment]
For Eclipse I had to create symlinks to these files, for Android Studio I'm not aware but it should work out of the box. Compilation on main server is successful http://builder.osmand.net:8080/view/OsmAnd%20Builds/
