### ISSUE TITLE
OpenGL issues with screen magnification (was: appearance of the route line (Open GL) )

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#17135]
### Description
Why the route line appears so different between engine 1 and engine 2?
Route line is way too thick with Open GL?

Here in the pics I did change the color, but even if I choose standard settings for the route line, it is as thick as this. 
(did not find any similar issue) 

### Your Environment
OsmAnd Version:  +4.4.7
Android/iOS version: 13 
Device model: S20+

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/95540936/236696068-1e96a98a-c922-4407-ac65-259a49d64193.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/95540936/236696076-b3d9599b-b491-4bfc-be37-af9bf9cf9e86.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
@Rowin63 So far, I can't reproduce the result - as you can see in the video, the route line is the same.
Try restoring the default profile settings or reinstalling OsmAnd.
Also, it seems that in the second screenshot, you have a larger zoom level (although both screenshots show 100m), which can be seen by the different sizes of buildings - perhaps you changed some settings in the map display and it affected it.


https://user-images.githubusercontent.com/104760013/236789826-f0ec45a3-4b71-4880-a1be-e9b30526ebcf.mp4

**Comment by Rowin63** [comment]
Hmmm.
I did reset the car profile and the routing line in Rendering V2 still is the same fat.
There are no changes made in the map settings, I just switch from Rendering V1 to V2. 
So there must be all the same settings, the profile itself remains untouched by changing the rendering engine.

**Comment by sonora** [comment]
Could it be that you use screen magnification? Long-tap Osmand's zoom buttons and check if it is set to 100% in both cases. (Also accessible via `Menu > Configure map > Map magnifier`.)

**Comment by Rowin63** [comment]
No screen magnification, both cases is set to 100%...

**Comment by sonora** [comment]
You're tracking something bigger here: While the 100m scale bar on both of your screenshots has the exact same length (~76 pixels), **all linear dimensions on the 2nd screenshot are about 55% longer than in the 1st one, meaning the scale on one of these 2 screens is blatantly wrong...**

**Comment by Rowin63** [comment]
Sorry, I can´t reproduce it.
Two devices (both S20+) with the same internal display settings. 
The same settings in thed car-profile. 
The other device is correct, and the first is like shown on the pics above. Then I did export the car-profile from device 2 to device 1 and again the line is way too thick. Crazy.
Don´t waste your time on it, perhaps I will find out whats wrong. Last option is a new install of osmand - but I would like to avoid this...
Thanks for helping.

**Comment by sonora** [comment]
Question is how you arrived on the screen with the wrong scale. For the record, this is https://www.openstreetmap.org/way/279248202, and per inspection the scale on your second ('enlarged') screenshot is the wrong one.

**Comment by sonora** [comment]
Ok, hete's how to reproduce:
- Display the map using the driving profile, and using engine V1.
- Have the screen magnification at 150% (this could be the default for the driving profile, not sure).
- Now change the engine to V2.

The map will display about 50% additionally enlarged vs. before, with the scale bar indicationg the original scale. Almost like we **apply the map magnification twice**.

Related or not: While testing tvis, OsmAnd even crashed on me, with this 
[exception.log.txt](https://github.com/osmandapp/OsmAnd/files/11428085/exception.log.txt)

**Comment by Rowin63** [comment]
Thanks for investigating!

About your crash:
My Osmand crashes really often when opening tracks. 

I did not mention this here, because I did not see any connection.
But I frequently sent the crashlogs to the automatic email address (support).

**Comment by Rowin63** [comment]
> Question is how you arrived on the screen with the wrong scale.

Just starting the app

> For the record, this is https://www.openstreetmap.org/way/279248202,

Yes, right, somewhere there

> and per inspection the scale on your second ('enlarged') screenshot is the wrong one.

Yes, correct

**Comment by Zirochkabila** [comment]
@sonora If all the steps were followed correctly (video), I don't see any difference anyway.

Please describe in more detail the steps to reproduce the crash - we may need to create a separate error report


https://user-images.githubusercontent.com/104760013/237058520-f9beb05f-718c-41a1-8ad1-660ae6f58125.mp4

**Comment by sonora** [comment]
@Zirochkabila You are right, it's weird, and seems to depend on something we have not yet understood.

This morning I could perfectly reproduce it with just the 3 bulleted steps above (no route etc. needed). Now I can not reliably, only sometimes. _I believe it is some sort of screen redraw or screen refresh issue (or lack there of)._ See this procedure:
1. Fresh app start: My default profile (Browse map) shows, and it has 100% magnification. I use V1 (visible by the displayed street name, which OpenGL suppresses, see separate bug report of a few weeks ago).
2. Change to Car profile (mine is set to 150%, rendering engine is still V1). In addition: Touring view in car mode uses wider strokewidth fior roads - that seems to be observed ok.
3. Change to V2 engine. Street name disappears Scaling looks still like (2), so probably ok.
4. I swiped OsmAmd off and restarted it. Default profile is now shown again, now using V2. Looks like (1), minus the street name - seems ok.
5. Now again switch to Car mode: **This now looks scaled different from (2) and (3)!** So there's a problem here.
6. Put the app in the background, then back to the foreground: (6) equals (2), so only now it's consistent again!


<table style="width:100%">
  <tr>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/845735/ebdb4087-c18c-43d4-b06e-681b9020fa91"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/845735/15b0a201-dbe8-4582-b80d-78efe4c323f3"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/845735/6b6ad182-4717-456d-8f9c-67f58b405949.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/845735/7ea3bae9-c322-4ad9-a8e6-703271aebfcb.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/845735/ca507102-9031-4d33-ab93-cd9d3daac5d1.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/845735/38baa859-cc29-4d8c-8e16-3b03b2395841"  width="300" height="auto"/> </th>
  </tr>
</table>  

But at least the scale bar seems ok on all of these. But repeating this, I occasionally get this: the left one is like (5) above, but on the right one the scale bar is clearly too short:

<table style="width:100%">
  <tr>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/845735/11a8ca73-8d4e-47c6-936d-f43cc6f25e82"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/845735/574d5927-42d5-42f0-ab24-7b181913f4b6"  width="300" height="auto"/> </th>
  </tr>
</table>  

Feel free to delete all these once you find a good reproduction rule. But they document for now that we have some issues...

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#35935m, Released: 2023-05-12

@sonora I checked three times, according to your points - the result is different, the 5th screenshot is identical to the 2nd and 3rd

Maybe I missed something?

**Comment by sonora** [comment]
Yes, it seems not reliably reproducible, so I also vote for ignoring this for now. If it's a big enough issue so that someone reports or references it, we could come back to it.
