### ISSUE TITLE
My favorite places don't show up the same way at different zoom levels, which confuses me

### ISSUE THREAD

**Issue by tch123** [osmandapp/OsmAnd#17137]
Some can be turned into small dots when zoomed out to x level, and some will always be displayed
I want to know how to unify to a standard rule, for example: when zooming out to N level, let all favorites be displayed as small dots and not display the name of favorites

**Comment by Zirochkabila** [comment]
@tch123 Favorites become visible on the map from the zoom level 6 
Please follow the link for more information https://osmand.net/docs/user/map/point-layers-on-map/#favorites

**Comment by tch123** [comment]
I saw this link and was so confused, because I found that the favorite point is not getting bigger and smaller at the same time when zooming to a certain level,
But I saw another saying that the changes of these adjacent collection points are determined by algorithms
