### ISSUE TITLE
Coastline rendering error

### ISSUE THREAD

**Issue by robinpaulson** [osmandapp/OsmAnd#17131]
![](https://i.imgur.com/rrl4Mxs.png)

The top 2/3 of the screen should be water, specifically the Tamaki estuary, Tamaki Makaurau-Auckland, Aotearoa-New Zealand, near Pakuranga.

**Comment by robinpaulson** [comment]
Location: geo:-36.90678,174.86077?z=19
https://osmand.net/map?pin=-36.90678,174.86077#19/-36.90678/174.86077

**Comment by robinpaulson** [comment]
This is around 1km from a similar bug I reported 2 weeks ago, #17003

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#35904m, Released: 2023-05-07
Can be reproduced only when using **V1 rendering**

`-36.90678, 174.86077`


https://user-images.githubusercontent.com/104760013/236686357-e393c638-3564-484d-877c-4108a9b0a51d.mp4

**Comment by ivanPyrohivskyi** [comment]
Probably related to https://github.com/osmandapp/OsmAnd/issues/17240

**Comment by robinpaulson** [comment]
Fabulous, it appears fixed since the Jun data snapshot yesterday. Cheers
