### ISSUE TITLE
Cycleways and crossings rendering

### ISSUE THREAD

**Issue by michalgwo** [osmandapp/OsmAnd#17141]
# 🚀 feature request

### Description

Currently, OsmAnd renders cycleways only when they are tagged with `highway=cycleway`, but there is another way of tagging cycleways with `highway=path` and `bicycle=designated` which is described on the [wiki](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dpath) (Examples section is the most helpful here). There is a huge difference when you add `bicycle=designated` to a `highway=path`, so I think all paths shouldn't have the same color.

The next thing is the rendering of crossings. Currently, they are rendered only when the way has the tag `footway=crossing`, but there are also tags `path=crossing` and `cycleway=crossing`, all of which are described under [this](https://wiki.openstreetmap.org/wiki/Tag:footway%3Dcrossing) wiki page.

### Describe the solution you'd like
It would be nice to see paths rendered according to their destiny, for example:
* `highway=path` + `bicycle=designated` - the same color as a cycleway
* `highway=path` + `foot=designated` + `bicycle=designated` - some other color to emphasize it's also designated for pedestrians

I think all the crossings can be rendered the same way as `footway=crossing`

**Comment by xmd5a2** [comment]
`highway=path` + `bicycle=designated` is already rendered but only in *bicycle* profile:
![Screenshot_2023-05-15_10-12-50](https://github.com/osmandapp/OsmAnd/assets/5829014/71396ca5-b469-4aea-b7f3-ad69deb72463)

**Comment by Velomeloman** [comment]
Confirm. Also highway = footway + cycleway = lane is already rendered only in a becycle profile.
![Screenshot_20230516_132823_net.osmand.plus.jpg](https://github.com/osmandapp/OsmAnd/assets/109347561/fab33dfc-2612-4a40-80e2-8ebbf4a132c7)

![Screenshot_20230516_132830_net.osmand.plus.jpg](https://github.com/osmandapp/OsmAnd/assets/109347561/eb03d19d-8487-4fc6-b808-8a8bd0ec8079)

**Comment by xmd5a2** [comment]
Fixed. New maps and OsmAnd are required.

**Comment by Zirochkabila** [comment]
Needed to update or re-download the map of **South Holland**

`52.07866, 4.74471`
[OSM](https://www.openstreetmap.org/way/500683191#map=19/52.07866/4.74471)

<table style="width:100%">
  <tr>
    <th>OsmAnd Nightly 4.5.0#46m, released: 2023-05-18</th>
    <th>4.4.8.11</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/aa035dbc-8c14-437f-90af-1521566ee5d3"  width="300" height="auto"/> </th>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/c8672fcb-489d-4e1c-9625-bb4e650f392f"  width="600" height="auto"/> </th>
  </tr>
</table>
