### ISSUE TITLE
Tag:embankment=dyke is not rendering

### ISSUE THREAD

**Issue by APneunzehn74** [osmandapp/OsmAnd#17140]
If a highway is entered as a dyke in OSM, that is highway=path + embankment=dyke the dyke is not rendered in OsmAnd. If only highway=path + embankment=yes (without dyke, which is less precise) it will be rendered correctly as an embankment. 
Please note that. Thank you.
[Wiki](https://wiki.openstreetmap.org/wiki/Tag:embankment=dyke
### Your Environment
OsmAnd Version: 4.4.7
Android/iOS version: androit
Device model: Gigaset GX290 and other models

**Comment by xmd5a2** [comment]
Fixed. New maps are required.
![Screenshot_2023-06-07_10-29-25](https://github.com/osmandapp/OsmAnd/assets/5829014/0da017cf-4db7-4558-827f-2bf01de42788)

**Comment by Zirochkabila** [comment]
Newest map
[OSM](https://www.openstreetmap.org/way/737017602#map=19/48.40008/11.75595)
`48.40008/11.75595`

<table style="width:100%">
  <tr>
    <th>OsmAnd~ 4.5.0#226m, Released: 2023-06-16</th>
    <th>4.4.10.5</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/5c279386-2b0a-4c7f-802e-bbf05c7126f8"  width="300" height="auto"/> </th>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/ae160cdc-3bf6-4894-8ac6-56a174ffc41d"  width="535" height="auto"/> </th>
  </tr>
</table>
