### ISSUE TITLE
Duplication of some names on the map

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#17157]
### Description
I noticed that the names of entrances, kindergartens and substations began to be duplicated. Not all names are duplicated for kindergartens, but only for those that have a description.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/12549744/579ba4be-9669-4256-bbf2-8c1f39ecad3c"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#35923m, Дата выпуска: 2023-05-10
Android version: 13
Device model: poco f3

**Comment by Zirochkabila** [comment]
`60.05366° N, 30.42196° E`

OpenGL only

**Comment by scaidermern** [comment]
Can confirm. OsmAnd 4.5.0.

**Comment by vshcherb** [comment]
To Review Pull Request - tech utilities:
1. Obf -> Osm, OSM -> OBF
2. How it works nameTag
3. debugTextDisplayBBox, ...

**Comment by spaanse** [comment]
I am going to assume this is fixed by the MR.
The same was happening for cycle nodes.
The only exception is when an extra node label would collide with another

**Comment by ivanPyrohivskyi** [comment]
Check textDy from issue https://github.com/osmandapp/OsmAnd/issues/15556#issuecomment-1545572783
