### ISSUE TITLE
Custom map sources disappear

### ISSUE THREAD

**Issue by TwoForty** [osmandapp/OsmAnd#17155]
### Description
Sometimes when adding / modifying map sources after a restart of the app all configured custom map sources disappear.

### Steps to reproduce
Sorry I haven’t figured out a reliable way to reproduce this yet but will update if I figure out the exact trigger. Something along the lines of:
1. Have a number of custom TMS sources configured
2. (Sorry this is vague) add a new map source but modify the config a few times
3. restart the app

### Actual result
All custom map sources are removed.

### Expected result
Only the added map source should be touched and all prior map sources left in tact

### Your Environment
OsmAnd Version: 4.4.7
Android/iOS version: 16.4.1
Device model: iPhone 14

**Comment by Zirochkabila** [comment]
@TwoForty Please transfer your request to the iOS repository https://github.com/osmandapp/OsmAnd-iOS
