### ISSUE TITLE
Navigation by GPX unreliable with poor GPS signal

### ISSUE THREAD

**Issue by orbisvicis** [osmandapp/OsmAnd#17154]
I have cycling route in New York city that crisscrosses itself and for which OsmAnd does a terrible job navigating:

1. OsmAnd sometimes truncates the route at crisscrosses, taking the shortest path to the finish rather than following the entire route.
2. OsmAnd omits roadside information, such as which sidewalk I should use to cross a bridge when one sidewalk leads to a dead end.
3. OsmAnd position can jump laterally by a few blocks when cycling under elevated highways. When the GPS signal is poor it should assume I'm following the navigation.
4. OsmAnd position can lag actual position when cycling between tall buildings. If the lag is more than a block, following turns is almost impossible. If the lag is less than a block it should be possible except that the automatic zoom level usually truncates the map before the next intersection, so the only clue to the turn I have is a distance (ie 745 feet) which is inaccurate and useless. When the GPS signal is poor OsmAnd should show a radius bracketing my estimated position, and have the zoom include the next turn on the map.

OsmAnd+ 4.4.7 / Android 12 / Lineage OS 19.1

**Comment by mikehgentry** [comment]
Personally I've found brouter provides better routing for a bike than OsmAnd's inbuilt router

https://osmand.net/docs/user/navigation/routing/brouter/

And I guess you're going to need to provide a sample GPX or at least coordinates for the routing problems for this bug report to be actionable

**Comment by orbisvicis** [comment]
[GPX file](https://gist.github.com/orbisvicis/f4321f7e3cf9c4264d04ff5c4116ca1f)

**Comment by Zirochkabila** [comment]
@orbisvicis Most likely, it's the GPX you created with BRouter-Web 0.18.1 - the track looks damaged.
Try creating a track with a similar route, but using the built-in Plan a route. Or, activate the track recording plugin and record the route directly
during the ride.
As for the GPS operation, try changing the settings: Menu > Settings > OsmAnd settings > Location source

**Comment by scaidermern** [comment]
> @orbisvicis Most likely, it's the GPX you created with BRouter-Web 0.18.1 - the track looks damaged.

What exactly looks damaged on this GPX track? Some track points don't have an ele field - which should not be a problem. The track looks fine to me.

**Comment by vshcherb** [comment]
As I understand this is navigation by GPX with poor signal. And this is GPX doesn't have attached road information i.e. street names etc. Cause it uses some ferries probably it won't be reliably attached to OsmAnd data but it is worth to try

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#73m, Released: 2023-05-22

If the GPS connection is weak, I get incorrect directions in the turn widget (as well as voice guidance).
I may also experience delayed guidance, as in the second video.
This behavior may be related to another issue https://github.com/osmandapp/OsmAnd/issues/17090


<table style="width:100%">
  <tr>
    <th>GPS weak</th>
    <th>Delayed guidance</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/104760013/ed762a3b-18bf-4754-b9dd-f448b96d19d4"  width="300" height="auto"/></td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/104760013/302031fd-57d5-4160-8fff-493f9745f0a4"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
Inded attaching to the roads might be the best workaround in this case but it might related to https://github.com/osmandapp/OsmAnd/issues/17090
