### ISSUE TITLE
"and arrive at your destination"

### ISSUE THREAD

**Issue by cmeeren** [osmandapp/Osmand#1716]
I'm using the english TTS. Just after the last direction (e.g. turn) before arriving at my destination, the voice says "and arrive at your destination", which is a weird thing to say (and a gramatically bad sentence). Note that the TTS also announces when I have actually arrived at my destination.

I suggest that if the destination is the next thing on the directions list, then IF it's more than x meters away (you decide the limit), announce "arrive at your destination after x meters", and if it's closer, don't announce anything and only announce the arrival when it happens. For example, if the destination is 20 meters after the last turn, you'll have arrived before the voice has finished saying "arrive at your destination after 20 meters" and it would be better if the voice waited until you actually arrived at your destination and announced only that.

**Comment by vshcherb** [comment]
It should say somethign like:
go straight 60 m and arrive at your destination

**Comment by sonora** [comment]
I had also noticed and I thought I had fixed this about 3 weeks ago. Are
you reporting for our latest release, or a new nightly build?

thx - Hardy

**Comment by cmeeren** [comment]
Using version 2.1.1. Seems to be the latest one on Google Play.

**Comment by vshcherb** [comment]
We didn't release it yet, so if you are not able to test it with nightlies let's wait for the first 2.2 release

**Comment by aceman444** [comment]
Actually I have heard this command too as "turn right and arrive at your destination", while the destination was still several km away (straight on), so it shouldn't have said that here. Is that also covered?

**Comment by sonora** [comment]
What I think I have fixed is the _isolated_ "and arrive a your destination"
which we did have under certain circumstances (and which of course is not a
complete sentence). What we still have it is the "Turn xxx and arrive at
your destination", if the arrival is the next step after the next turn (but
I think this is ok?).

**Comment by aceman444** [comment]
I don't think it is ok to say "arrive at your destination" if you are not yet there and you still have several kilometers. If you have the interval of repeating commands set, you should still get the commands "go straight/continue" before the destination comes.

**Comment by sonora** [comment]
Yes, that is true, now I see what you are saying.

I likely never came across an actual situation where the very last turn before reaching a destination was miles before actually reaching it, that's probably why I never noticed, and no one else reported a problem either.

I have tried to suppress the message now if the destination is still a long way after the next turn, but it needs testing. Also: There may be a similar issue for announcing waypoints and/or favorites, but I do not use that functionality a lot. Please test and report!
