### ISSUE TITLE
Hiking routes are not hidden in cycle routes view

### ISSUE THREAD

**Issue by Botrops1** [osmandapp/OsmAnd#17163]
### Description
I enabled Cycle Routes option to search routes in the map by simply clicking on color lines. However, "What's here" tab shows hiking routes together with cycling routes, despite first are disabled. I want to see only cycle routes, otherwise for every route I need to check a type and it is not convenient.
### Steps to reproduce
Activate cycle routes and check that hiking routes are displayed as well
### Actual result
Being disabled hiking routes are shown on the map together with enabled cycle routes.
![20230509_160636](https://github.com/osmandapp/OsmAnd/assets/133165279/3c387083-77ed-42d9-9c5b-094a8054c157)
### Expected result
When cycle routes are enabled and hiking routes disabled on routes tab, than on the map to be visible only enabled routes (in my example on cycle routes).
### Your Environment
OsmAnd Version: 4.4.7+
Android/iOS version: Android 13
Device model: Samsung S22 Ultra

**Comment by vshcherb** [comment]
To do :
- In Context menu (Screen What's here) "Route" should be specified "Route hiking"
- Routes should be sorted by type, 2nd by name. "Route Hiking" should be preferred for "Pedestrian types", "Route cycling"  for "Car" types. List of route types here (https://wiki.openstreetmap.org/wiki/Relation:route#Route_types_(route)) and probably in Enum code.

**Comment by dmpr0** [comment]
Done
<table style="width:100%">
  <tr>
    <th>Hiking</th>
    <th>Bicycle</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/23a2f96e-709b-46a7-a98b-41f3f951fae9"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/b6e650e2-c104-427c-b765-b815ec3e8a1e"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
- Consolidate 3 enum types of Route types into 1: 1) Network selection  2) Sorting 3) Travel (GPX generation) 
- Are there other hard coded route types such as "hiking", "running", "horse",...
- Add to data type missing route types "running", ...

**Comment by yuriiurshuliak** [comment]
Currently, if Cycle routes are enabled, only trails of this type are displayed on the map, if Hiking routes are enabled, only hiking path are displayed on the map.

OsmAnd~ 4.7.0#1416m, released: 2024-01-24

https://github.com/osmandapp/OsmAnd/assets/127092082/c5a693f9-7195-41e7-a967-59fbf94f1083
