### ISSUE TITLE
Stop tracking users

### ISSUE THREAD

**Issue by deavmi** [osmandapp/Osmand#1717]
It would be nice if we didn't have analytics being done on us.

**Comment by vshcherb** [comment]
There is no analytics.

**Comment by deavmi** [comment]
It showed up in F-Droid like that.

**Comment by deavmi** [comment]
Thanks ;)

**Comment by vshcherb** [comment]
F-droid uses previous release, please find corresponding discussion in one of the github issues.

**Comment by Zahnstocher** [comment]
@deavmi 
Removed 6 weeks ago:
https://github.com/osmandapp/Osmand/commit/513024eac7ceca812ddc94056fc0ac0d5d2772ec

**Comment by aceman444** [comment]
Yeah, I have also seen that warning at f-droid. deavmi, can you report the change to f-droid?

**Comment by deavmi** [comment]
@aceman444 Okay, will do.

**Comment by deavmi** [comment]
@aceman444 Just sent the email. :smile:

**Comment by moshpirit** [comment]
OK, F-droid uses the same version as Google (2.1.1) which tracks us. Any idea about the next release date?

**Comment by spookas** [comment]
Yeah I'm curious about this too! The code was removed in August but the last update on both Play and Fdroid is June.

**Comment by rugk** [comment]
Any update on this? [FDroid](https://f-droid.org/repository/browse/?fdfilter=maps&fdid=net.osmand.plus) still shows you would be tracking users.

**Comment by rugk** [comment]
BTW another issue about this: https://github.com/osmandapp/Osmand/issues/1526

**Comment by moshpirit** [comment]
You can use MAPS.ME a new app developed because of this issue (I think)

**Comment by rugk** [comment]
Yes, but there is no need to completely switch to another app just because of this issue, which also seems to be fixed already. Just wanted to get the latest news, because on F-Droid there is still this warning.
