### ISSUE TITLE
Double-tap and zoom out gesture doesn't work (Regression)

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#17180]
### Description
Single finger zoom gesture stopped working.
Double tapping the screen and swiping up or down no longer zooms the map.

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#35942m, Дата выпуска: 2023-05-13
Android version: 13
Device model: poco f3

**Comment by sonora** [comment]
Can confirm. Only for the OpenGL rendering engine, though, V1 works fine.

**Comment by Zirochkabila** [comment]
@Nine-Tailed @sonora I can't confirm it


https://github.com/osmandapp/OsmAnd/assets/104760013/f606e08f-65bc-47ee-bc00-8dd02a2f785e

**Comment by Nine-Tailed** [comment]
> @Nine-Tailed @sonora I can't confirm it
> 

When you press the second time, without lifting your finger from the screen, swipe up or down.

**Comment by Zirochkabila** [comment]
Confirmed - OpenGL only

**Comment by Dollarius** [comment]
Thanks for reporting this.
It **stopped working in the 2023-05-09 version** (it's OK for 2023-05-08 and earlier), only OpenGL.
I hope it can be fixed because it is the only way I can reliably zoom in/out while keeping the North Up (because of this problem https://github.com/osmandapp/OsmAnd/issues/15660).

**Comment by Nine-Tailed** [comment]
Installed a fresh nightly build, the gesture doesn't work.
OsmAnd~ 4.5.0#150m, Дата выпуска: 2023-06-02

**Comment by Dollarius** [comment]
@Andrewschenko unfortunately, it does not work on master-opengl nightly 2023-06-04.

**Comment by Dollarius** [comment]
@Andrewschenko it works now!
Thank you very much for timely fixing this important functionality.

**Comment by yuriiurshuliak** [comment]
OsmAnd~ 4.5.0#209m, released: 2023-06-14
Confirmed, the issue is fixed in the latest nightly version.

https://github.com/osmandapp/OsmAnd/assets/127092082/d70a9467-26bf-49d0-944b-e562900811ad
