### ISSUE TITLE
Turning the phone while calculating a route causes the osmand to be inoperative

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#17183]
### Description
Screen orientation - same as device.
See video in telegram chat ruosmand
https://t.me/ruosmand/123921

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#35942m, Дата выпуска: 2023-05-13
Android version: 13
Device model: poco f3

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#14m, Released: 2023-05-14
Can't reproduce it - please send log files

**Comment by vshcherb** [comment]
Probably it's a duplicate of Crash / ANR that's quite popular in Google Play but not fixed.

**Comment by vshcherb** [comment]
Didn't reproduce let's see if we get more feedbacks
