### ISSUE TITLE
Tile Loading Screen - dark theme is not correctly displayed

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#17181]
### Description
Light theme instead of dark:
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/12549744/f0fe0d5b-19c0-4e61-ae0a-274df2fbb4f8"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#35942m, Дата выпуска: 2023-05-13
Android version: 13
Device model: poco f3

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#14m, Released: 2023-05-14
Confirmed

**Comment by 0xRe1nk0** [comment]
Fixed in this commit https://github.com/osmandapp/OsmAnd/commit/d1f67ec36e6fa19ba7ae5afc5c27e10292682b44
