### ISSUE TITLE
Road is visually segmented and routing not working

### ISSUE THREAD

**Issue by GladYouAsked** [osmandapp/OsmAnd#17187]
### Description
Visually the road is broken up into several segments. 
Car-routing via this road is also not working.
I assume this is a map creation issue, but it is present since at least 2 map updates.

### Steps to reproduce
Open Osmand and go to 48.22455/11.34618

### Actual result
See attached screenshot.
Road Schulstraße is segmented in several parts.

### Expected result
https://www.openstreetmap.org/#map=18/48.22455/11.34618
(Schulstraße is not broken into segments)

### Your Environment
OsmAnd Version: Osmand+ 4.4.7 released 2023-04-10
Android/iOS version: GrapheneOS / 5.10.177-Android13-4-g7ec3b8565b6e
Device model: Pixel 6
![Screenshot_20230514-175635](https://github.com/osmandapp/OsmAnd/assets/133578250/eb3a7749-2760-4ea0-9348-be77af7726b4)

**Comment by TheSnoozer** [comment]
Street looks fine on my end:
![photo_2023-05-14_20-37-26](https://github.com/osmandapp/OsmAnd/assets/6849390/1dcd503e-74d7-4ee8-8b67-4e47aa5caab5)

From what date is your map data? (Settings -> "Kartenverwarltung" -> Lokal -> Deutschland Bayern -> tell us the date noted next to the map)
What rendering for the map are you using? (Settings -> Settings -> OsmAnd Einstellungen -> Karten-Rendering-Engine - what version is listed here)

**Comment by GladYouAsked** [comment]
Issue solved, thanks!
Updated to the last available map data and now it looks fine:
Germany Bavaria
1.44 GB 1 May 2023

(before it was
Germany Bavaria
1.44 GB 1 Apr 2023
Don't know why I did not see the new map update before...)

### What rendering for the map are you using? 
Version 2 (OpenGL)

**Comment by vshcherb** [comment]
There will be june maps soon in 2 days, so it's worth to wait

**Comment by GladYouAsked** [comment]
Reopened this topic as I had the same issue on another device. 
It could be an issue with Live Update or I just do not understand how Live Update works.

Initially this map was installed and showing the described issue
Germany Bavaria
1.44 GB 1 Apr 2023

On this map (Germany Bavaria) I have Live Update enabled and the latest Live Update on "Germany Bavaria" was done on 2023-05-27, 15:40". Nevertheless the issue described still exists with this Live Update.

I had to manually update the map via Download Maps==>Updates to
Germany Bavaria
1.44 GB 1 May 2023
by triggering *manually* the update of the *complete* map (not via Live Update).

==> Obviously the map has not been updated via Live Update and required a manual update. 
If this is the normal behavior (monthly manual update needed) I do not understand Live Update.

**Description:** See initial post

**Your Environment**
OsmAnd Version: Osmand+ 4.4.7 released 2023-04-10
Android/iOS version: Samsung Android 13
Device model: Galaxy Tab Active 3

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#126m, Released: 2023-05-31
Issue seems to be resolved both with and without Live Updates - Upper Bavaria map

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/3e90b095-54b8-4926-9404-21c19c4b7725"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/1704010b-60b7-4ced-a4ed-06d0d93286d7"  width="300" height="auto"/> </th>
  </tr>
</table>
