### ISSUE TITLE
Bicycle Routing: Usage of footways

### ISSUE THREAD

**Issue by a77bright** [osmandapp/OsmAnd#17192]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

bicycle

### Start and end points

Routing engine fails to deliver the shortest route, between {51.26594 7.13877} and {51.26580 7.13877} in this case, while utilising the profil 'bicycle'.

https://osmand.net/map?start=51.26594%2C7.13877&end=51.26580%2C7.13877&mode=bicycle#16/51.26587/7.13877

### Actual and expected routes

It's a footway that connects these two coordinates. Transition is not allowed while pedaling the bicycle, but to dismount and pushing the bicycle through these few meters is both legal and possible, and in fact it's the most rational solution.

The OsmAnd+ routing engine avoids to choose this footway by every means, resulting in a routing solution that consumes several minutes instead of a few seconds.

Up to my opinion OsmAnd+ should propose the direct, just 15 meters long connection.

### Is this a regression?

 Yes, but I am unable to name the version that delivered the route I'm expecting. In the meantime, there might have been relevant changes in the map sources as well.

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

4.4.7
</code></pre>

**Device and Android/iOS version:**
Different Android versions, tested on 10 and 13. Seems to be device independent, too. Online version, as of today, May 15th, 2023, shows the same routing behavior

**Maps used (online or offline):**
offline:
Europe;Germany;North Rhine-Westphalia

- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**
Within the navigation settings, 'avoid roads' -> 'avoid footways' is *not* checked. Implicitly, this states that the bicycle routing profile does allow the use pedestrian ways.

**Comment by a77bright** [comment]
(1) In a way there's some trouble with the tag
'bicycle=no'.

Maybe it's understood in a different ways.

(1.1) 'bicycle=no' means 'you're not allowed to enter this place with a bicycle at all'.

(1.2) 'bicycle=no' means 'you're not allowed to ride a bicycle here, but you're allowed to have a bicycle with you, if you dismount'.

It seem that the routing engine of OsmAnd 4.4.7 interpretes 'bicycle=no' following (1.1). In combination with the statement found at Key:access≫List of possible values≫dismount in the documentation https://wiki.openstreetmap.org/wiki/Key:access which says 'Note that bicycle=no is also commonly used where dismounting and pushing bicycle is legal.' the interpretation referenced at (1.1) seems to be the wrong one, and (1.2) should be used instead.

Following https://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Access_restrictions , 'bicycle=no' triggers the routing engine not to use this path. On the other hand, dismounting is an option, and if trespassing is allowed, e.g.'foot=yes', the path should be considered, adding the right amount of time.

But... how to map areas where bicycles are not allowed at all → (1.1)? 





(2) The example used in this request

https://osmand.net/map?start=51.26594%2C7.13877&end=51.26580%2C7.13877&mode=bicycle#16/51.26587/7.13877

is a footpath regulated with the traffic sign 239. 

It has been mapped using the following tags:

Way: 192429385
Version #11

Specify tracktypes

    Edited 17 days ago by Zuecho
    Changeset #135504374

bicycle=no
de:strassenschluessel_exists=no
emergency=yes
foot=yes
highway=track
horse=no
lit=yes
loc_name=NBT-Zugang Unterer Dorrenberg
sac_scale=hiking
surface=paving_stones
tracktype=grade1
trail_visibility 	excellent
wheelchair=yes
width=4

up to my opinion, and utilising/refering

https://osmtools.de/traffic_signs/?signs=239

the tags used above:

bicycle=no
foot=yes
highway=track

should be exchanged with:

highway=footway
foot=designated
traffic_sign=DE:239

where bicycle=dismount is included implicitly. If someome insists, bicycle=dismount might be declared explicitly.

Most likely the routing issue will be solved this way. 

After all, it will be great to have a routing profile at hand, that recognizes short 'bicycle=no' tracks, and accepts them as viable.

**Comment by scaidermern** [comment]
> (1.1) 'bicycle=no' means 'you're not allowed to enter this place with a bicycle at all'.
> 
> (1.2) 'bicycle=no' means 'you're not allowed to ride a bicycle here, but you're allowed to have a bicycle with you, if you dismount'.

Indeed, these two different meanings exist. However, I don't think we have a tag for (1,1). Also, I don't think there is an actual traffic sign for (1,1), is there?

Most of the `bicycle=no` tags probably mean `bicycle=dismount` instead. Unfortunately I don't see any way to resolve this historical "misusage" (if it even is one, `bicycle=dismount` probably didn't exist from the beginning on).

Therefore I think routers should interpret `bicycle=no` and `bicycle=dismount` as synonyms. The OSM community should come up with a new tag for specifying that pushing a bicycle is actually forbidden (maybe something like `bicycle=forbidden`, but this needs to be discussed first).

**Comment by pebogufi** [comment]
Fully agree to @scaidermern .
In germany it is nearly impossible to forbit pushing a bike, it would be similar to forbid pushing baby buggies or rollator.
So, bicycle=no tags probably means don't **ride** a bike.

**Comment by a77bright** [comment]
Here's my example of (1.1), 'you're not allowed to enter this place with a bicycle at all'.

Botanischer Garten
https://www.openstreetmap.org/way/24658427

In a way it's a fenced private property, where entrance is allowed to the public during opening hours.

A plate at the door regulates several issues using text and pictograms, one of them is related to bicycles. It's a pictogram of a bicycle with a red 'X' on it. White background, black bicycle icon within a black sqarish frame, 45 degree rotated red cross overlaying parts of the bicycle icon. Left and right of it there are several other restrictions displayed in the same manner. I will take and share a picture of it the next days. 

A couple of years ago I've been visiting this place, and I've been kindly asked to leave it immediately, as I had my bicycle with me. So this is my experience and example related to (1.1). 

The related gate got tagged with 'bicycle=no':
https://www.openstreetmap.org/node/465270102

**Comment by Zirochkabila** [comment]
@a77bright One of the options is to create a combined route through Plan a route - that is, you select a walking profile at the desired location, the route is built using the settings of this profile, and then you navigate along the created route.

As for implementing this in the routing, it most likely won't work. Since bicycle routes are different from pedestrian routes and if the `bicycle no` tag is added to them (as in the case you have mentioned), it may cause problems in the routing.

**Comment by scaidermern** [comment]
> @a77bright One of the options is to create a combined route through Plan a route - that is, you select a walking profile at the desired location, the route is built using the settings of this profile, and then you navigate along the created route.

This is possible but not really an option. For this you have to choose for every section which way - cycleway or footway or road - you want to take. Which means you have to plan every tiny section yourself. If you have to plan everything yourself you don't need a router.

**Comment by vshcherb** [comment]
No clear action could be taken with that issue, so it's closed as No Further Action

**Comment by scaidermern** [comment]
> No clear action could be taken with that issue, so it's closed as No Further Action

Could you at least explain why it is not possible to include footway but give them a high penalty? I can't see a reason why this shouldn't be possible.

**Comment by vshcherb** [comment]
Giving high penalty or avoiding is long interesting discussion. 
I think restrictions help to improve the map data and high penalties create issues the could sit forever and produce very weird routing sometimes. And also we need to be specific is it legal?

So legality issue couldn't be solved with any any penality
