### ISSUE TITLE
Road name is not displayed (OpenGL)

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#17193]
### To Do

- [ ] Show road name when using V2 renderer

### Description
While using OpenGL rendering - road name isn't displayed on the map
[OSM](https://www.openstreetmap.org/way/165564286#map=19/43.85524/-79.42195)

Probably related to https://github.com/osmandapp/OsmAnd/issues/16543

### Steps to reproduce

- Enable V2 rendering
- Follow to this place `43.85534° N, 79.42151° W` 

### Actual result

<table style="width:100%">
  <tr>
    <th>OsmAnd~ 4.5.0#20m, Released: 2023-05-15</th>
    <th>4.4.8.9</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/01bd4aca-9cdd-4c65-9860-304347fdc597"  width="300" height="auto"/> </th>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/fd94bb5c-247c-478e-8789-4e0eecf01e23"  width="500" height="auto"/> </th>
  </tr>
</table> 

### Expected result

<table style="width:100%">
  <tr>
    <th>V1</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/4ea00953-45e7-4960-baa7-9fcf71bff854"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by sonora** [comment]
Perhaps related to #16543 ?

**Comment by cyberman54** [comment]
I found out: If i enable an overlay map (OpenRailwayMap in my case), and i set the overlay transparency slider to the right, all kind of text (street names, villages names, etc.) disappear.
