### ISSUE TITLE
Moving map when GPS gets lock

### ISSUE THREAD

**Issue by jkufner** [osmandapp/Osmand#1719]
When user taps button to go to current location (in bottom right corner) when there is no GPS signal, an error message is shown and map view does not move. Then, when GPS position is received, map view is moved to the position. But is user moves map between two events, the map should not be moved automatically.

Steps to reproduce:

1. Open osman indoors (no GPS signal).
2. Click "go to current GPS position" button in bottom right corner.
3. Move map somewhere else.
4. Go outside, wait for GPS signal.
5. The "go to current position" button turns blue and map is moved to current GPS position.

I would expect that number 5 does not happen, because user moved map already in number 3.

It should be like this:

First good scenario:

1. Open osman indoors (no GPS signal).
2. Click "go to current GPS position" button in bottom right corner.
3. Move map somewhere else.
4. Go outside, wait for GPS signal.
5. The "go to current position" button turns blue, but nothing else happens.

Second good scenario:

1. Open osman indoors (no GPS signal).
2. Click "go to current GPS position" button in bottom right corner.
3. Do not touch map.
4. Go outside, wait for GPS signal.
5. The "go to current position" button turns blue and map is moved to current GPS position.

Difference is in number 3 and 5.

**Comment by Gizmot** [comment]
i agree, annoys me a lot.
Usually, I know that there is a delay before getting GPS signal so I take that time to check the surrounding roads. As soon as GPS signal gets a lock, this moves the screen away from where I was looking.
Get in mind that if you start driving, map when recenter itself anyway

**Comment by sonora** [comment]
unless I am mistaken, though, the map only centers if you ever pressed the blue button. So in all scenarios not mentioned above, where you just fire up OsmAnd and start panning, you should not have an issue?

But I agree it may make sense if we just honor the _last_ user action, so if a user first pressed the blue button, and then decides to pan the map, then maybe this panning action should cancel the previous blue button action ...
