### ISSUE TITLE
Osmand crashing when making route.

### ISSUE THREAD

**Issue by Chadlh** [osmandapp/OsmAnd#17190]
Hello all.
  I've been following the same process for making routes for over a year.  I'm using a Samsung S20FE.  Within the last few days Osmand has been crashing, or should I say crashing and restarting automatically in the background.  It never totally dissappears, just closes the visible window.  All my work is lost up to the last save.

Being an adventure motorcyclist, I'm using all the features I can to emphasize gravel roads, atv trails, etc.  I'm also using Google satellite view as an overlay with a transparency slide control.

For creating a route, I switch between dropping points as "motorcycle", "walking", and "straight line".  This allows me to route through sections Osmand feels a motorcycle shouldn't travel.  This has been working perfectly for over a year.

Thanks for any help you can provide 

### Your Environment
OsmAnd Version: 
Android/iOS version: 
Device model:

**Comment by Zirochkabila** [comment]
@Chadlh So far, the latest, nightly version and the release, beta, version have not crashed.
We need more data from you.
Please clarify the following:

1. OsmAnd version
2. Start and finish coordinates
3. Log file/crash log: Menu > Help > Send logcat/crash log
4. Profile and settings you are using: Menu > Settings > Export to file

**Comment by Chadlh** [comment]
I'm using 4.4.7

I've made the route multiple times with different start points and slightly different routing.  It has crashed randomly at different places.  I feel it's maybe not route specific but maybe I'll test that theory some more by changing total location

Please find files attached.

Thanks for your help.

Chad


@Chadlh<https://github.com/Chadlh> So far, the latest, nightly version and the release, beta, version have not crashed.
We need more data from you.
Please clarify the following:

  1.  OsmAnd version
  2.  Start and finish coordinates
  3.  Log file/crash log: Menu > Help > Send logcat/crash log
  4.  Profile and settings you are using: Menu > Settings > Export to file

**Comment by Chadlh** [comment]
I'm using 4.4.7

I've made the route multiple times with different start points and slightly different routing.  It has crashed randomly at different places.  It isn't start point, end point, or route specific. 

Not sure how to share log files on here

**Comment by Zirochkabila** [comment]
@Chadlh You need to create an archive with this file, then it can be uploaded to GitHub
