### ISSUE TITLE
Search result is without addresses

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#17204]
# 🚀 feature request

At some searches (e.g. supermarkets, here "Spar"), the result is a long list with XX or XXX entries with the same name. If I dont want to go to the closest, but to a specific one, the result is not helpful, because it does not display the address and so I never know which one to select. Adding the street name to the search does not help, then the results only refer only to the street. (There is a "Spar" in Porzellangasse. But the result when searching for "Spar Porzellangasse" is a short list of streets with this name, without any relation to "Spar".  

Display the supermarkets address in the search result.

### Describe alternatives you've considered

![Screenshot_20230516_102158_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/95540936/2324f129-b37a-4823-a067-c080346a0097)

**Comment by Zirochkabila** [comment]
@Rowin63 related to https://github.com/osmandapp/OsmAnd/issues/2993 ?

**Comment by Rowin63** [comment]
It's similar, yes. 
This mentioned issue has really lots of branches and is still open since almost seven years...

So ?
