### ISSUE TITLE
Should display numeric keyboard when searching location

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#1720]
When searching for a location we have this:
![Location search](http://i.imgur.com/mmrnBVw.png)

Since we basically only type numbers and dot here, shouldn't the default keyboard type be numeric here?

**Comment by vshcherb** [comment]
We have spaces and : characters in order to be able to input in different coordinate systems, layout specifies limited set of characters, but not all Android version supports it. At 1 point we disabled phone and only numbers keyboard, because we were missing these characters.

**Comment by naoliv** [comment]
Won't `android:inputType="time"` work here?

**Comment by vshcherb** [comment]
time doesn't have '.', but this is what I've found also http://stackoverflow.com/questions/11383697/edittext-inputtype-time-does-not-support-colons

**Comment by lightonflux** [comment]
Maybe you could make it depended on the format that is selected. In the format of the screenshot you only need the . so no need for additional chars.

**Comment by naoliv** [comment]
Indeed it seems that it's not possible to natively use a more specific keyboard for this (unless one is implemented and customized).

**Comment by sonora** [comment]
Deprecated with new search.
