### ISSUE TITLE
Show recorded data from sensors on graph – BLE/ANT+ 

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#17201]
## ToDo
Allow to select 2nd axis on Analyze Map

- [x]  **Heart rate**
- - [x] icon – ic_action_sensor_heart_rate_outlined
- [x] **Speed**
 - - [x] icon – ic_action_sensor_speed_outlined
- [x] **Cadence** 
 - - [x] icon – ic_action_sensor_cadence_outlined
- [x] **Bicycle Power** 
 - - [x] icon – ic_action_sensor_bicycle_power_outlined
- [x] **Temperature**
 - - [x] icon  – ic_action_thermometer
6. Not used: Distance, Battery
---------------------

**Comment by dmpr0** [comment]
# Review
Track – [2023-07-13_18-13_Thu.gpx.zip](https://github.com/osmandapp/OsmAnd/files/12040989/2023-07-13_18-13_Thu.gpx.zip). Position was simulated using GPX file.


<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/311b3c5b-83b1-47dd-a40c-ec134424099d"  width="300" height="auto"/> </td>
  </tr>
</table>   


- - - - -

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/2407339d-23d7-484c-ab71-cdb5d355e1d9"  width="360" height="auto"/> </td>
  </tr>
</table>   
- [ ] Speed data without units

**Comment by shurasmiling** [comment]
All links are in this issue:
[BLE/ANT+ Management Sensors](https://github.com/osmandapp/OsmAnd/issues/15459#top)
#15459
