### ISSUE TITLE
Lake changed to a Volcano

### ISSUE THREAD

**Issue by Legitimater** [osmandapp/OsmAnd#17215]
### Description
Hello, and I'm reporting about what I suspected to be a bug in OsmAnd
Coords: `14.0767, 121.3293`

Fig. 1.1:
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/71918689/b3ed92fb-9e90-4814-907c-edd72ef274c4"  width="400" height="auto"/> </th>
  </tr>
</table>  

This is actually an issue I've seen before, on older versions of OsmAnd, going as back as v4.3 or 4.2, where it shows a volcano, instead of a lake. I previously thought of this as a vandalism editing (into iD via openstreetmap.org) but when I went to the coordinates, and try to edit via iD there, It was a lake (no vandalism). I tried to change the one of the lake's feature types to Volcano, but I can't, (so not only no vandalism has taken place, but vandalizing that way isn't possible at all)

Maybe the database is at fault? Maybe the app? Rendering Engine? Who knows? maybe the devs, I'm just trying to improve the app, that's all.

### Environment
OsmAnd Version: 4.4.7 (Released 4-10-2023 M-DD-YYYY)
Android version: 12 (Android S, API Level 31)
Device model: Realme C25s (see also the Metadata of bug.jpg)

Thanks.

 -L.

**Comment by sonora** [comment]
https://www.openstreetmap.org/relation/1557746

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#40m, Released: 2023-05-17

[Map](https://drive.google.com/file/d/1_SjDHRAjFHpbgcdhUOBpgE4UyvVu6fYW/view?usp=sharing)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/13e01fea-d6a7-489f-81f4-61240f5051ae"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by xmd5a2** [comment]
Fixed. New maps are required.
