### ISSUE TITLE
Importing a track through My Places is broken

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#17212]
Recently, trying to import a track results in the file picker still opening, but after picking a gpx file nothing happens. See https://github.com/osmandapp/OsmAnd/issues/16672#issuecomment-1552057156 and @Rowin63's posts above. May or may not be due to the recent fix for #16672.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#40m, Released: 2023-05-17

### Steps to reproduce

- Menu
- My Places
- Tracks
- Import
- Select GPX

### Workaround

- Files
- Chose GPX
- Select OsmAnd > File has been imported

**Comment by Dollarius** [comment]
I must add that
- NOW when importing a gpx we only get a little notification at the bottom "file has been imported" and the gpx is not displayed.
- BEFORE, the gpx would be loaded and displayed immediately.
I preferred the previous behaviour as I usually want to see/use an imported gpx immediately.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#117m, Released: 2023-05-30

1. When importing a track via **Menu > My Places > Import > Select track > Open** - Open button does not work - the track is not displayed on the map

2. When importing a track through **Files > Chose track > Select OsmAnd > Open** - Open button works, the track is displayed on the map

<table style="width:100%">
  <tr>
    <th>1</th>
    <th>2</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/104760013/909249c8-7e0c-4967-b39d-0a9abf0cb3e2"  width="300" height="auto"/></td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/104760013/565a6614-d002-46f6-8e1d-f08d4523ea2e"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
**Menu > My Places > Import > Select track** - track is immediately displayed on the map
**Files > Chose track > Select OsmAnd** - track is not displayed on the map, but a message with the **Open** button is displayed

<table style="width:100%">
  <tr>
    <th>Displayed on the map</th>
    <th>Message with the **Open** button</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/104760013/80bf83b0-d4f7-42f2-97a2-14d8c2b14257"  width="300" height="auto"/></td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/104760013/dde1d824-4770-4276-a564-474fbea26de0"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
> V+4.5.1 "Displayed on the map": Menu > My Places > Import > Select track - a message appears "track is imported" and an "open" switch. But nothing happens when tapping "open".
> 
> ![Screenshot_20230601_160002_OsmAnd+](https://user-images.githubusercontent.com/95540936/242623258-dba6e882-a387-49d3-a2c3-3063e7acd399.jpg)
> 
> And after a while, when writing this words, Osmand crashed again. Log is sent to your mail.

This behavior was fixed in the latest nightly version
