### ISSUE TITLE
Walking time public transportation always ~1 minute 

### ISSUE THREAD

**Issue by duiveldoder** [osmandapp/OsmAnd#17214]
### Description
No matter the distance to walk: 30 meters, 350 meters, 500 meters, the app always says I can walk that in ~1 minute

Apart from the fact - no I won't do that in 1 minute especially not in urban environment with traffic lights, steps, etc.
it also results that the suggested possible connections are not in the most favorable order to chose.

As it basically chooses the shortest route in total, but of course walking times make a huge difference!

If 1 suggested route is 150m in total to walk and the other is 900m, then the difference is 750 meters.

In Urban environment a homo sapiens being walks 4kmh if no traffic lights, steps, etc. which means 0.75m difference results in 11-12minutes walking, rounding up 12 minutes..

### Steps to reproduce

dunno, look at the screenshot and do the same on your end

### Actual result

False times and most favorable connection isn't on the top.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/15773876/7afe3feb-d272-4d23-9e77-58e341f12de2"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Your Environment
OsmAnd Version: 4.5.0#28m released 2023-05-15
Android/iOS version: Android 10
Device model: Huawei Mate 20 pro

**Comment by duiveldoder** [comment]
Okay, found the issue why this happened - and regardless of the "why" it's an error nonetheless.

Obviously the Public Transportation uses the build-in "walking" profile to determine the walking speed.

So if I select the walking profile and go to the navigation settings and the vehicle parameters and then default speed, it's set at min speed 1kmh,  default speed 2kmh and max speed 5kmh.

So regardless of any other setting - at 5kmh to do 0.5km is already 6minutes and not 1 minute.

But here's the thing, the "Navigation Type" was set to "car"

And that's then the reason why it resulted in ~1min regardless of the distance.

Now even with that type "car" the speed is still set to 1kmh, 2kmh and 5kmh. 

So it shouldn't matter what the "type" is - the app should be bound to the speed settings of the profile "walking" independently of the "type"

but anyway - now you know - if the type is set to car - it ignores the min speed, default speed and max speed of the profile and any distance is covered in 1 min.


My suggestion - then either tell a user:"you can't change the build-in walking profile navigation type to anything other than foot, it's locked to foot"

orrr... use the speed settings of the walking profile - regardless of the chosen type.

The latter would have my preference - since someone walking might chose car as type - to ensure to walk along/on roads and not go over steps, paths through forest, etc (the reason I set it to car was one time it was late and I wanted not to deviate from the asphalted road - later I forgot to set it back to foot) 

and that got me puzzled then when I later used OSMAnd for Public Transport.

Thanks

**Comment by Zirochkabila** [comment]
@duiveldoder It's strange because I don't have this behavior.
Although, the public transit profile is set by default

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/f70c8bf8-a55f-4eda-8e7b-da03b326d4a5"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by duiveldoder** [comment]
> @duiveldoder It's strange because I don't have this behavior. Although, the public transit profile is set by default
> <img alt="" width="300" height="auto" src="https://user-images.githubusercontent.com/104760013/241403049-f70c8bf8-a55f-4eda-8e7b-da03b326d4a5.jpeg">

As said in my "added" comment I get this when switching to car as "navigation type" of transportation profile instead of foot - then it ignores the "min speed, average speed and max speed settings for the public transportation profile"

I changed from "foot" to "car" inside the "Public transport" profile - and then the setting "navigation type"

this to make sure the footways that are chosen between stops - are not over paths or anything but follow properly constructed roads.

when choosing "foot" it sometimes had me walk slippery dirt paths etc.. you don't want that when using public transportation.

Changing to "car" then it plans the bus routes properly and the connection between stops it follows the properly built roads.

but then it ignores the min_speed, average_speed and max_speed settings.

and of course regardless if type is car or foot - it should follow the speed settings regardless - that's the bug I'm facing here

**Comment by vshcherb** [comment]
Well then you have that issue that speed is taken as a car which is not correct... 
I think it's very specific issue to be fixed

**Comment by duiveldoder** [comment]
> 

No it doesn't take the speed of the car - as I set those all 3 to 5kmh..

closing an issue which is real and existing - isn't the way to move forward.

if you claim you just close all my tickets because even with proof and screenshots of issues you simply don't like me - then I'll stop reporting issues.

very arrogant and rude to close issues just like that - assuming something - which is wrongly assumed.

**Comment by vshcherb** [comment]
- I changed from "foot" to "car" inside the "Public transport" profile - and then the setting "navigation type"

The issue closed cause it's not reproduce with default settings. It's reproducible but it's very weird configuration so there is no sense in fixing it. 

If we see more people experience it then it's worth to reopen and fix it.
