### ISSUE TITLE
Quick action setting screen - dark theme is not correctly displayed 

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#17229]
### Description
Go to configure screen - quick action
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/12549744/b5b35752-1ee3-4e32-bf8e-5968a05fe57a"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#56m, Дата выпуска: 2023-05-20
Android version: 13
Device model: poco f3

**Comment by Zirochkabila** [comment]
@Nine-Tailed Changes have been made https://github.com/osmandapp/OsmAnd/issues/17181#issuecomment-1555960324
We need to wait for a new build

**Comment by Nine-Tailed** [comment]
@Zirochkabila, the previous bug is fixed (I checked), so I don't think they are related.
