### ISSUE TITLE
Missing national maxspeeds for trucks in France

### ISSUE THREAD

**Issue by aearil** [osmandapp/OsmAnd#17220]
### Description

In France, trucks over 12t of weight rating are limited to 90km/h on motorways (autoroutes) and 80km/h everywhere else outside of city boundaries. Also, inside city boundaries, even if the speed limit is raised to 70km/h (default 50km/h), trucks stay limited to 50km/h

https://fr.wikipedia.org/wiki/Vitesse_maximale_autoris%C3%A9e_par_type_de_v%C3%A9hicule_en_France#Les_transports_de_marchandises

It seems like OSMAnd is not taking into account those restrictions and as a consequence is underestimating travel times when using non-motorway roads that have a maxspeed > 80km/h

### Steps to reproduce

Setup a truck profile with a maxspeed of 90km/h, and compare the evolution of the predicted ETA while using motorways and non-motorways road (under cruise control)

### Actual result

I can see the ETA slowly creeping up when driving on a non-motorway road with maxspeed > 80km/h (while I'm still doing 80km/h because I'm driving a HGV), while it remains constant while driving on a motorway

### Expected result

ETA stays the same in both cases

### Your Environment
OsmAnd Version: 4.3.12
Android version: 11
Device model: Xiaomi Redmi 10

**Comment by vshcherb** [comment]
It needs to be checked with French OSM community whether these tags needs to be introduced or they should be assumed on the roads, I guess on main motorways they should be part of OSM actually.
