### ISSUE TITLE
Frequent NPE in connection with tracks

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#17221]
I sporadically experience this crash [exception.log.txt](https://github.com/osmandapp/OsmAnd/files/11512201/exception.log.txt), happens randomly, no particular way to reproduce.

**Comment by Chumva** [comment]
This should be fixed [here](https://github.com/osmandapp/OsmAnd/pull/17226/commits/b779fa45c7745d93101ccc13df704d60cc242a28)
