### ISSUE TITLE
Mismatch between current location and center of the map altitude widget

### ISSUE THREAD

**Issue by letypequividelespoubelles** [osmandapp/OsmAnd#17237]
### Description

The altitude given by the two altitude widget aren't consistent. When I'm at the same position (and in a quite flat terrain so I cant come from a GPS fluctuation) I have around 50m difference between the "altitude : current location" and "altitude : center of the map" when the center of the map is set to my position (set with clicking on the GPS icon).

### Steps to reproduce
Enable both altitude widget and put the center of the screen on your location. There is a mismatch everywhere, even if the difference isn't constant.

### Your Environment
OsmAnd Version: D-Droid v 4.4.7 OpenGL engine, with heightmap enable.
Android/iOS version: 12
Device model: CrossCall Z5

**Comment by scaidermern** [comment]
Did you download the "World altitude correction" (located under Download maps)? If not, does it fix the problem? If you already downloaded it, try to delete it instead and check if the problem still exists.

**Comment by letypequividelespoubelles** [comment]
The issue remains with or without the "world altitude correction". It just changes the mismatch (from ~40 m to ~70).

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#77m, Released: 2023-05-23

@letypequividelespoubelles As you can see in the screenshot, the error is minimal.
Try updating the app in the Play Store or download the night version at https://osmand.net/docs/versions/nightly_versions

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/bbe6f168-899c-46c7-a89c-1cfb8157f62f"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by letypequividelespoubelles** [comment]
Thanks @Zirochkabila I'll wait next FDroid version to check. 2m difference is indeed negligeable, but it does mean that there are two different data source for elevation, which is a little bit weird.

**Comment by vshcherb** [comment]
We need specific location in some cases we think the data is not correct because of approximation but we can't confirm it yet. We expect the margin of error 5%-10% of a minimum height in radius 100m - that what we will measure on server side and compare with client

**Comment by letypequividelespoubelles** [comment]
I just tried with the 4.5.8 from Fdroid and the error is still the same - quite huge : 211m vs 178m (15%-20% error ...).
I still don't understand why we need two different source for the height.
