### ISSUE TITLE
Village not appearing when searching for places

### ISSUE THREAD

**Issue by keunes** [osmandapp/Osmand#1723]
Whilst the village is marked as such in OSM, in OsmAnd it can only be found as a POI.
Location: Renesse, The Netherlands.
http://www.openstreetmap.org/note/435665

**Comment by fangly** [comment]
I manage to find the village by address.
When searching by address, the cities appear incrementally, as you type. However, for villages, you need to type the name of the village, and then press on "search more villages/postcode".
Does that help?

**Comment by keunes** [comment]
Actually it does, it just takes very long before it finds the village. Probably it took so long that I changed to POI to try there.
Wouldn't it be possible to automatically apply 'Search more villages/postcode' when no results are returned from the first list? (don't know if that's any clear)

**Comment by vshcherb** [comment]
Known issue and it is planned to be fixed

**Comment by keunes** [comment]
Grand, thanks.
