### ISSUE TITLE
Turn is not indicated (also traffic lanes) at a certain intersection

### ISSUE THREAD

**Issue by Prusaker** [osmandapp/OsmAnd#17238]
### Description
At one of the exits from the highway, where lanes are marked on the Openstreet map, lanes are not displayed on the screen when driving along the route. On other exits from the highway, the lanes are displayed normally on the screen when driving.

### Steps to reproduce
Just build a car route from 53.8383362, 27.5331176 to 53.8364377, 27.5311923. Lanes is not displayed.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/32092837/ed5bfa03-51a6-4480-8ddc-ee285f436655"  width="300" height="auto"/> </th>
  </tr>
</table>  

https://www.openstreetmap.org/way/603584791
On this section of the highway, the lanes have been marked for a very long time.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/32092837/17f65939-e68f-4d91-aae8-7033339fa50c"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Your Environment
OsmAnd Version: 4.4.7
Android/iOS version: 7.1.2
Device model: Google Nexus 7 2012

**Comment by Zirochkabila** [comment]
@Prusaker  I think this is due to the fact that the exit is marked as having one lane
Although, the Mapillary data shows that there are two lanes
[Map](https://drive.google.com/file/d/1csOGtfYqGczMaLiIaDYkaFkEDUv1CZQY/view?usp=sharing)

On the generated map - **line is displayed**
On the downloaded map (also in Live Updates) - **line isn't displayed**

[OSM](https://www.openstreetmap.org/way/610913306#map=19/53.83760/27.53329)
[OsmAnd](https://test.osmand.net/map/?start=53.839285%2C27.533026&end=53.836253%2C27.530558&mode=car#17/53.83800/27.53363)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/a7ac216c-e118-4cbb-a3bd-46a19ba5163c"  width="600" height="auto"/> </th>
  </tr>
</table>  

<table style="width:100%">
  <tr>
    <th>Generated</th>
    <th>Downloaded</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/104760013/f4d9c4c6-7e2e-499c-89a9-ac86780a57d8"  width="300" height="auto"/></td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/104760013/4e9dd8fd-5f48-40c1-88ed-b17710b9ce3d"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Prusaker** [comment]
The exit from the highway starts with one lane, which then turns into 2 lanes through 5-10 meters . But that's not the problem. I checked - if you remove a small piece of the route, which is intended for a U-turn, then the program correctly displays the lanes. This is a bug of the program, not the OSM data.

**Comment by Prusaker** [comment]
I simulated several intersections and found a bug in the display of lanes in two cases.

Example 1 - if there is a reversal lane, the lanes are not displayed at all.

Example 2 - if there is a left turn lane, the lanes are displayed, but with an error - the left turn lane is not displayed at all.

Example 3 - if you can go straight and left from the left lane, all lanes are displayed correctly.

![EXAMPLE1](https://github.com/osmandapp/OsmAnd/assets/32092837/a73ae234-52be-493d-ab6e-3bcb7b38fdd1)
![EXAMPLE2](https://github.com/osmandapp/OsmAnd/assets/32092837/c9560bb7-ec80-4e73-9290-3c2098931e76)
![EXAMPLE3](https://github.com/osmandapp/OsmAnd/assets/32092837/c057b044-e278-486f-9f37-17954d54b25f)

**Comment by Zirochkabila** [comment]
Different result

It seems that the first couple of screenshots show the correct result in the Android
On the second pair - in iOS

OsmAnd~ 4.5.0#254m, Released: 2023-06-20
4.4.10.7

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/a9bf51c6-22dc-4115-bd35-cecc6b2c94dc"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/dd796f71-a8bd-483d-a36f-98499e7423f1"  width="500" height="auto"/> </th>
  </tr>
</table>  

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/2bbd1420-c0b5-4a37-b41a-b3124175e212"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/5517b764-472b-49b4-8f42-f81da32ff435"  width="500" height="auto"/> </th>
  </tr>
</table>
