### ISSUE TITLE
Not all hiking routes can be selected

### ISSUE THREAD

**Issue by avernan** [osmandapp/OsmAnd#17234]
### Description

When browsing the map with "Hiking routes" enabled, some hiking routes are not identified and cannot be selected.

### Steps to reproduce

1. Enable "Hiking routes"
2. Go to the following coordinates: 51.31234, 0.27448
3. Zoom&Pan a bit, and some hiking routes should appear on top of the path called "Pilgrims Way", one of them corresponding to this relation: Relation: North Downs Way (Eastern) (8127)

![image](https://github.com/osmandapp/OsmAnd/assets/9851882/984a96ce-39c0-4a6a-ad33-f8291d771a17)

This happens for all hiking routes in England, but routes in Wales work as intended (at least those I checked).
Checking the routes tags on OSM show very similar properties between the routes that can be selected and those that cannot.

### Actual result

No "shield" for the path appears, and there is no way of selecting this hiking route.

### Expected result

I would expect this to behave the same as other hiking routes in the UK. For example, you can go to the following coordinates:
51.86889, 5.27395 (Relation: Pembrokeshire Coast Path (77964))
![image](https://github.com/osmandapp/OsmAnd/assets/9851882/cbc71975-0381-4430-ba59-25fe67861efe)

### Your Environment
OsmAnd Version: 4.4.7
Android/iOS version: 13
Device model: Pixel 6

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#77m, Released: 2023-05-23
@avernan If we're talking about the route on the screen, then this route can be selected and corresponds to the one on the map

[Waymarkedtrails](https://hiking.waymarkedtrails.org/#route?id=1957071&type=relation&map=15.0/51.3121/0.2818)
[OSM](https://www.openstreetmap.org/way/27720154#map=16/51.3125/0.2785)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/278d4d27-b718-4a24-b80e-c326040881f2"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by sonora** [comment]
We are talking this https://www.openstreetmap.org/way/27720154 and the relations it's part of.

Have you tried tapping the caption? I am not sure it's intended, but sometimes I had a feeling that works for routes with no symbol.

**Comment by avernan** [comment]
Thanks for your replies. The issue was that I could not select the route by tapping the screen.
After seeing the replies, I went to try again and noticed some subtle differences in the ways around there between my app and the screenshot you posted. That finally led me to check and update the offline maps, which solved the issue.

Thank you very much for the replies and the help! In the future, I'll make sure to check map updates before opening a bug!
