### ISSUE TITLE
Polygon for 12 zoom oversymplified

### ISSUE THREAD

**Issue by ivanPyrohivskyi** [osmandapp/OsmAnd#17240]
Original issue https://github.com/osmandapp/OsmAnd/issues/16898#issuecomment-1556914147

[Polygon for 12 zoom (oversymplified)](https://github.com/osmandapp/OsmAnd/files/11529656/naumov.csv)
![Screenshot 2023-05-22 at 12 53 48](https://github.com/osmandapp/OsmAnd/assets/1040293/50a5a4b9-bed1-43dc-a3dd-fb2c60127238)

[Polygon for 13 zoom (normal)](https://github.com/osmandapp/OsmAnd/files/11529674/naumov2.csv)
![Screenshot 2023-05-22 at 12 54 49](https://github.com/osmandapp/OsmAnd/assets/1040293/2f6215b5-2304-45fd-8324-f1e17fde82d9)

_Originally posted by @ivanPyrohivskyi in https://github.com/osmandapp/OsmAnd/issues/16898#issuecomment-1556914147_

**Comment by ivanPyrohivskyi** [comment]
Map for test
[Italy_procida.obf.zip](https://github.com/osmandapp/OsmAnd/files/11554852/Italy_procida.obf.zip)

Problem will fix in June 2023 maps

**Comment by Zirochkabila** [comment]
Fixed on the maps in June (Italy - Campania) - Done

**Comment by dmpr0** [comment]
Provide coordinates for testing.
