### ISSUE TITLE
country names in weird IPA-like language

### ISSUE THREAD

**Issue by m4lvin** [osmandapp/Osmand#1724]
The country names are messed up in a very funny but hard to read way.
Map language is set to en, I am running 2.1.1 from F-Droid, the world overview map is from 2015/08/02. Any other information that could be useful?

![screenshot_2015-08-27-22-13-45](https://cloud.githubusercontent.com/assets/2990728/10001306/66f4e1fc-60a1-11e5-932b-3c16a3082380.png)
![screenshot_2015-09-21-20-31-37](https://cloud.githubusercontent.com/assets/2990728/10001308/66f81c6e-60a1-11e5-9dc8-5a56b39da7e9.png)
![screenshot_2015-09-21-20-32-05](https://cloud.githubusercontent.com/assets/2990728/10001309/66fa3710-60a1-11e5-978a-8aab34265fdc.png)

**Comment by aceman444** [comment]
I also see the same since installing OsmAnd on a new phone som months ago. However, on the same phone with the same map all is fine with the OsmAnd nightly builds. So I am not sure what happens.

**Comment by vshcherb** [comment]
Please try to change the map language in Configure Map -> Map Language.

**Comment by m4lvin** [comment]
@vshcherb This was set to English when I took the screenshots above.

I now also tried "Local Names", giving this funny stuff:
![local-names](https://cloud.githubusercontent.com/assets/2990728/10012940/31893c54-610d-11e5-90d5-dc32623eb332.jpg)

And German, giving this again:
![german](https://cloud.githubusercontent.com/assets/2990728/10012941/3498881e-610d-11e5-8730-9a14a7a66240.jpg)

**Comment by aceman444** [comment]
Setting the language does not work (either has no effect or changes to a completely different language). My map language is set to SK but it still shows mostly name:hu or name:de on objects, even thought 'name' in local (Slovak) exists.

**Comment by vshcherb** [comment]
Does reinstallation helps? Can you please try nightlies?

**Comment by aceman444** [comment]
For me nightly works correctly. I'll wait if updating to v2.2 fixes this on the release build. If not, I can try reinstallation. However as I said, for me the problem started immediatelly upon first installation of OsmAnd to a new phone (thus as if reinstalling). I just copied over the data folder (maps, not settings).

**Comment by vshcherb** [comment]
Can you please try to install exactly the version which didn't work (release I believe). I'm trying to find explanation, but still I couldn't

**Comment by aceman444** [comment]
I have both release (OsmAnd+ v.2.1.1) and nightly (the free version) installed in parallel on the same phone. V2.1.1 is NOT working right, nightly is.

**Comment by sonora** [comment]
Think tis is deprecated

**Comment by aceman444** [comment]
Yes, I haven't seen it since. Not sure about the reporter.

**Comment by m4lvin** [comment]
Yes, with the current version I have not had this problem anymore.
