### ISSUE TITLE
Crash when opening Terrain/Configure map

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#17248]
### Description
When opening the Terrain item in Configure map, the application crashes
[exception (54).log](https://github.com/osmandapp/OsmAnd/files/11542784/exception.54.log)

### Steps to reproduce

- Configure map
- Terrain

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#77m, Released: 2023-05-23
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by sonora** [comment]
I receive an NPE in this case (which is different from your exception.log): [exception.log.txt](https://github.com/osmandapp/OsmAnd/files/11543151/exception.log.txt)

**Comment by Velomeloman** [comment]
[exception.log](https://github.com/osmandapp/OsmAnd/files/11543485/exception.log)

**Comment by sonora** [comment]
Perhaps introduced by this PR: https://github.com/osmandapp/OsmAnd/commit/177091d587b76d6cc1690f4ae3c50e16bab90193

**Comment by Chumva** [comment]
This should be fixed [here](https://github.com/osmandapp/OsmAnd/commit/183a59a86a1d479bb07be788ade0d571b4fca435#diff-ddb3895384efbbc86a631ef0c230e3f6eb78927e7d47d1092d1ff28040c895cfR137)
