### ISSUE TITLE
Gryshko National Botanical Garden area and name doesn't display on the map

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#17241]
### Description
Gryshko National Botanical Garden doesn't display on the map
[OsmAnd](https://osmand.net/map/#15/50.4146/30.5653)
[OSM](https://www.openstreetmap.org/relation/13422106#map=14/50.4137/30.5629)
* Area color is missing
* Name is missing

### Steps to reproduce
Go to this place `50.4137, 30.5629`

### Actual result

<table style="width:100%">
  <tr>
    <th>OsmAnd~ 4.5.0#64m, Released: 2023-05-22</th>
    <th>4.4.8.12</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/bba9a18e-8952-48ff-9cc7-c868d22442b4"  width="300" height="auto"/> </th>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/39741e10-0747-4d92-906a-178338114f75"  width="515" height="auto"/> </th>
  </tr>
</table> 

### Expected result
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/6f1da771-c982-43c7-a54a-d702921da206"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by xmd5a2** [comment]
Fixed. New maps are required.
