### ISSUE TITLE
show reason why loading voice files failed

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#1725]
I experiment now with ttsconfig.p and also use the gen_voice script to generate the pre-recorded voices. I got into a state where the generated voices are no longer accepted by OsmAnd (while they were in the past). Probably some error in the generated _config.p. But OsmAnd only says the "voice files version is unsupported". Can we get a more descriptive message or at least some debug output file to see what went wrong? Is there a prolog interpreter in OsmAnd and did it produce an error message? Can we somehow see it? Thanks.

**Comment by vshcherb** [comment]
It is definitely visible in the logs (use LogCat for example), may bet that exception could be pulled from internals, but it is not clear yet.

**Comment by vshcherb** [comment]
Technical information should not be overloading UI, we better find the way with looking into logs.

**Comment by aceman444** [comment]
So in which log file can I find the information?

**Comment by vshcherb** [comment]
If you start any Log collect file program, you will see there all exceptions and additional information.

**Comment by aceman444** [comment]
I have found out the "voice files version is unsupported" message came due to there being "version(103)" in my _config.p file (instead of version(0)) (the gen_voice.sh script does not replace 103, which somebody already fixes in other PR). So there probably was no exception.
