### ISSUE TITLE
Update downloads never get "green" 

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#17259]
### Description

The Wikipedia updates can be downloaded, but they always remain "orange" and don't get "green" after downloading, in the map management section

### Your Environment
OsmAnd Version:  +4.5.0
Android/iOS version: 13 
Device model: S20+

**Comment by Rowin63** [comment]
I think they don't update at all.

**Comment by scaidermern** [comment]
Duplicate of #17243.

**Comment by Rowin63** [comment]
Sorry I did not see this 😎
