### ISSUE TITLE
new track list (configure map -> tracks) is orders of magnitude slower than old

### ISSUE THREAD

**Issue by khimaros** [osmandapp/OsmAnd#17257]
### Description

loading the list of tracks (~50-100 tracks) takes upwards of 30 seconds to load. on the old system it was nearly instantaneous. N.B. i'm using an "external storage" folder for my OSMAnd storage.

### Your Environment
OsmAnd Version: 4.4.7 (F-Droid)
Android/iOS version: 13 (CalyxOS)
Device model: Pixel 6

**Comment by Zirochkabila** [comment]
@khimaros This behavior has been fixed in 4.5.0 or the nightly (or beta) releases.
Please download OsmAnd from the Play Store and try again

**Comment by khimaros** [comment]
i'm using from F-Droid, since the Play store version does not allow for external storage. i'll keep an eye out for the 4.5.0 release there. thank you for the fix. would you mind linking to the PR or commit that resolved the performance issue?

**Comment by vshcherb** [comment]
Beta version will be out this week
