### ISSUE TITLE
Navigation sometimes does not finish

### ISSUE THREAD

**Issue by martenjj** [osmandapp/OsmAnd#17266]
### Description

Sometimes reaching the end of a navigated route does not display the "Finish Navigation"/"Find Parking" popup and the app appears to remain in navigation mode:

* The profile icon and map style remains as "Car"
* Voice warnings continue to be given

When in this state, tapping the "Navigate" button sets and calculates a very short route from the current position to the original destination.  (Or, in "simulate" mode", recalculates the original route and starts again). When this happens the buttons at the bottom say "Stop" and "Start", instead of "Cancel" and "Start" as would be shown for a new navigation setup.

However - and this is what hints to me that the destination has actually been reached - the voice instruction says "You have reached your destination <name>".

### Steps to reproduce

This simulated route reliably reproduces the problem:
  Start:  Staines Road, Teddington, England 51.44093, -0.35507
  End:  Staines Road, Teddington, England 51.43998, -0.35747
  Profile: Car, no restrictions (but also happens with Cycle or Walk)
  Simulate mode: Realistic simulation
  Offline map: UK England Greater London 01/03/2023

### Actual result

The navigation instructions given (en-GB voice, slightly paraphrased) are:

The route is 200 yards time less than a minute
In 200 yards keep left on A305 Staines Road and arrive at your destination
Keep left on A305 Staines Road and arrive at your destination
You have reached your destination Staines Road Teddington Twickenham

The same happens if voice instructions are switched off.,

### Expected result

As above, but when the destination is reached the "Finish navigation" popup appears and the profile switches back to "Browse map"

### Your Environment

OsmAnd Version: 4.5.0
Android/iOS version: 12
Device model: Samsung Galaxy S10

**Comment by Zirochkabila** [comment]
@martenjj As you can see on the screenshot, it could not be reproduced.
But there is already a similar discussion https://github.com/osmandapp/OsmAnd/issues/16594

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/ac67cfa2-7920-4e60-aac0-14273d3fa9d7"  width="300" height="auto"/> </th>
  </tr>
</table>
