### ISSUE TITLE
Flooding in the India

### ISSUE THREAD

**Issue by ivanPyrohivskyi** [osmandapp/OsmAnd#17264]
OsmAnd~ 4.5.0#50m, Released: 2023-05-19
World overview map needs to download

`17.01868, 81.08617`

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/b1af10ee-6be6-4e1c-b8d4-a135aada5298"  width="300" height="auto"/> </th>
  </tr>
</table>

_Originally posted by @Zirochkabila in https://github.com/osmandapp/OsmAnd/issues/16898#issuecomment-1555071184_

**Comment by Zirochkabila** [comment]
Similar behavior is described in this issue https://github.com/osmandapp/OsmAnd/issues/17356

**Comment by cepprice** [comment]
[This](https://www.openstreetmap.org/way/1174411388#map=14/54.4683/-5.6088) polygon has wrong clockwise direction in map, in OSM it is ok

**Comment by vshcherb** [comment]
Small islands (coastline) could be ignored if they are drawn as 1 way

**Comment by ivanPyrohivskyi** [comment]
Remove tag coastline for island that drawes single closed way

**Comment by xmd5a2** [comment]
Basemap coastline was simplified in this area
![Screenshot_2023-07-12_10-26-48](https://github.com/osmandapp/OsmAnd/assets/5829014/2969fb78-a136-4964-b506-53b81c4df3fa)

**Comment by xmd5a2** [comment]
Fixed. New basemap uploaded to server.
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/7541fb0a-e922-4949-8bd7-94c456d5f2a0)

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#609m, released: 2023-08-13
World overview map downloaded
**No flooding at different zoom levels**

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/174b3841-eb3c-44e3-9064-f230e33831dd"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/a5f326f6-6d0c-487e-bce9-c4c613430d60"  width="300" height="auto"/> </td>
  </tr>
</table>
