### ISSUE TITLE
Include bearing/heading should be present 

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#17268]
Can anybody confirm that at least as of late all our recorded tracks include `<heading>` and ` <bearing>` values even with the Trip recoridng plugin's setting "Include bearing" set to off?

**Comment by vshcherb** [comment]
Heading is always written especially with development plugin on (which was on purpose to replicate strange bugs with navigation). 

In case it's a question I would close that issue as answered, however I didn't go into code itself yet.

**Comment by sonora** [comment]
I see for heading, was not aware. But bearing should not be written, is it a bug?

**Comment by vshcherb** [comment]
@sonora Yes it makes sense

**Comment by vshcherb** [comment]
Todo 2 settings
- Bearing should be off by default (compass)
- Heading should be on by default (direction of movement calculated by GPS)

**Comment by dmpr0** [comment]
# Review

```
      <trkpt lat="50.4382074" lon="30.5072724">
        <ele>164</ele>
        <time>2023-07-26T11:07:27Z</time>
        <hdop>5</hdop>
        <extensions>
          <osmand:speed>13.3</osmand:speed>
          <osmand:heading>0</osmand:heading>
        </extensions>
      </trkpt>
```

- [ ]  <osmand:heading> is present in track data after disabling

**Comment by DmitryAlexei** [comment]
Docs: - added info to https://osmand.net/docs/user/plugins/development#troubleshotting
