### ISSUE TITLE
Navigation widgets still sometimes disappear after route recalculation

### ISSUE THREAD

**Issue by martenjj** [osmandapp/OsmAnd#17265]
### Description

This was apparently fixed by #15074, but unfortunately I am still experiencing the problem with OsmAnd+ 4.5.0.  

The "Next turn" and "Second next turn" navigation widgets sometimes either disappear when the route needs to be recalculated, or do not appear in the first place when navigation starts.  Rotating the device makes them appear again.

### Your Environment
OsmAnd Version:  4.5.0
Android/iOS version: 12
Device model: Samsung Galaxy S10

**Comment by Rowin63** [comment]
Same here, happens again. (+4.5.0 / And13 / S20+)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#100m, Released: 2023-05-28
@martenjj @Rowin63 If you are referring to the same example as shown in the 2nd second of the video, I'm not sure if this is a bug. The widgets appeared after the final recalculation.


https://github.com/osmandapp/OsmAnd/assets/104760013/6052be35-4a74-4ebc-a542-8f89c0ddce24

**Comment by Rowin63** [comment]
I happened to me in one of the last 4.5.0#xx releases. But never again since then.

**Comment by Rowin63** [comment]
Still the widget disappears sometimes (this here happened in one of the previous two or three 4.6.0#83? releases)

I think it happens, when starting a route at moment when osmand is very busy in the background.
Rotating the map did not help (like it often did before), had to start the routing again, then it worked well. 

![Screenshot_20231003_174209_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/95540936/38fefc99-d145-4275-8df3-75469139f68d)
