### ISSUE TITLE
Usability: Display selected city while searching street name

### ISSUE THREAD

**Issue by Gizmot** [osmandapp/Osmand#1726]
When searching for an address, after entering a city name, this is the screen you get:
Note that you get a different screen if a city is already selected and you click on "Street" to select it

instead of "OsmA..." and "Search...", I would like a reminder like : "Select street in XXXX town name".
This is usefull in case you cannot find a street and would like to make sure you are searching in the right city.
![screenshot_2015-09-21-19-42-35](https://cloud.githubusercontent.com/assets/13919997/10010007/b83b08f0-60b2-11e5-9140-a753f3dc1963.png)

**Comment by Gizmot** [comment]
an other use case I remember:
In this screenshot, it is quite evident that you are searching for a street (XXX road, YYY lane, etc).
While in Vietnam, I was always wondering if I was currently looking at the city, street or street intersection...

**Comment by sonora** [comment]
deprecated, as this refers to our old search interface.
