### ISSUE TITLE
OpenGL crashed and return to engine version 1 in launch osmand

### ISSUE THREAD

**Issue by avantdill** [osmandapp/OsmAnd#17260]
### Description
When starting Osmand, a message appears saying that the engine failed to start version 2 and rolls back to version 1
### Steps to reproduce
Just launch newly installed Osmand (f-droid release or nightly version) or random launch old installed osmand nightly and f-droid version

### Your Environment
OsmAnd Version: 4.3.12
Android/iOS version: Android 13
Device model: Samsung A715F/DSM

**Comment by avantdill** [comment]
[exception.log](https://github.com/osmandapp/OsmAnd/files/11561259/exception.log)

**Comment by Zirochkabila** [comment]
@avantdill This bug should have been fixed by now - try updating the app (download the beta) or installing the nightly version https://osmand.net/docs/versions/nightly_versions
