### ISSUE TITLE
Map periodically flickers after re-center.

### ISSUE THREAD

**Issue by spongepaul** [osmandapp/OsmAnd#17276]
### Description
The map flickers/flashes after pressing the re-center button or auto-center is activated.
Note: I am forced to use render engine v1 due to #17121, this does not occur on V2.

### Steps to reproduce
1. Wait for gps lock.
2. Press the bottom-right re-center button.

### Expected result
No Flickering

### Your Environment
OsmAnd Version: 4.4.7
Android/iOS version: 13
Device model: Galaxy A51

https://github.com/osmandapp/OsmAnd/assets/1760807/d8fc1be0-40f5-4524-b07e-ae874dddcb71

**Comment by spongepaul** [comment]
The flickering starts at frame 0:10 (after I click the re-center button) until 0:25.  It is not extremely noticeable, but if you look at the dark blue background you will notice it flickering/flashing a whiter/lighter shade approximately once a second like a heartbeat.

**Comment by vshcherb** [comment]
By the video it's not clear it was sync with my location before or not, we can't reproduce it so far but probably some more evidences will pop up.
