### ISSUE TITLE
MyPlaces > Tracks loses its sorting

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#17278]
After its recent update, between different visits of the MyPlaces > Tracks screen the factual sorting on the screen is broken.

 Reproduce by setting sorting to e.g. "Name A-Z": The tracks will show sorted accordingly. Revisit that same screen later: The sorting indicator will still show "Name "A-Z", but the tracks are not actually sorted accordingly any more.

**Comment by sonora** [comment]
The behavior has changed a bit with today's updates. Now it appears consecutive visits to the MyPlaces screen preserve its selected sorting.

But now I see this: Have MyPlaces > Tracks (where the folders are shown) sort by Name A-Z, and Configure map > Tracks > On map sort by Last modified. After you entered the latter, the former will now also switch to Last modified.

**Comment by sonora** [comment]
Side finding: It seems that by default all sub-folders have sorting by Last modified. It is a nuisance for users with big (often meant to be alphabetically organizedl) gpx libraries over dozens of folders to have to change each of them to A-Z upon first opening. Can we maybe apply the sorting selected on the main screen to all folder contents as well, and change folder sorting individually only where subsequently changed on a folder tab?

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#97m, Released: 2023-05-26
@sonora Unable to reproduce
Please provide the exact steps to reproduce with the result
Or attach a video that shows the steps and the result

**Comment by sonora** [comment]
Since yesterday it's like this (for me 100% reproducible):
- Open the MyPlaces  > Tracks screen: Set sorting to Name A-Z. Leave screen via back button.
- Open Configure map  > Tracks. Set (or already have) sorting  there to Last modified. Leave screen via back button.
- Got to MyPlaces > Tracks again: Sorting there now displays Last modified also.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#100m, Released: 2023-05-28
@sonora Still can't reproduce


https://github.com/osmandapp/OsmAnd/assets/104760013/dd784d66-1fd1-416b-a1d1-1f725f9b02b6

**Comment by Rowin63** [comment]
Sorting A-Z also as Z-A always sorts tracks starting with numbers (date) at the end of the list

**Comment by scaidermern** [comment]
> Can we maybe apply the sorting selected on the main screen to all folder contents as well,

This would be really nice. Currently it is really tedious to change the sorting for each folder individually (especially since OsmAnd is forgetting it again).

**Comment by Zirochkabila** [comment]
Reproduces the behavior in the video above - previous sort order is preserved

**Comment by scaidermern** [comment]
Still not fixed: #17475
