### ISSUE TITLE
Usability: Click on screen to add waypoint or favorite

### ISSUE THREAD

**Issue by Gizmot** [osmandapp/Osmand#1727]
Instead of only getting a GPS coordinate while clicking on a map, I would like to be able to simply able to add this coordinate as a waypoint or favorite.
I'm imagining below the GPS coordinate the usual icons for waypoint and favorite.

**Comment by vshcherb** [comment]
This is work in progress in the nightlies.

**Comment by Barrocas** [comment]
Already available options as suggested, in the nighy builds.
