### ISSUE TITLE
please revert osmandapp / OsmAnd-resources  commit 585e2f9 for sake of completeness of navigational light characteristic display

### ISSUE THREAD

**Issue by josail** [osmandapp/OsmAnd#17273]
May I request to revert commit 

https://github.com/osmandapp/OsmAnd-resources/commit/585e2f91d6f21b0b61507f7d35ae5bd588706c0c#commitcomment-115027886

due to the comment left there. Certainly, the solution with rendering_types.xml line6822 including the dot "." is not perfect, but it is essential (so far) to assure completeness of display of navigational light characteristics and its consistent display in round brackets, in case the name and seamark:name are missing.

Happy to help with further insight on this issue, if needed. I put screenshots illsustrating the difference in the referenced comment.

Thanks, Jo

**Comment by josail** [comment]
See simple solution in pull request https://github.com/osmandapp/OsmAnd-resources/pull/972

If there is further possibility to find an empty character, which still assures completeness of lightDetail with unnamed navigational lights, that would be an additional improvement, which I was not able to figure out.

**Comment by Zirochkabila** [comment]
@josail Can you confirm that your request has been fulfilled?

**Comment by Zirochkabila** [comment]
@josail doesn't answer, so we'll assume that everything is working

**Comment by josail** [comment]
yes, thanks, very fine! I saw the publishing of the APP update today.

only new remark after this: the vertical text location, i.e. textDy tweeking, leads to quite some text offset from the symbol. This is up for further improvement. But all the new content is perfectly there! Thanks a lot to all. Jo

**Comment by Zirochkabila** [comment]
@josail I think you need to create a new issue with this request (the vertical text location, i.e. textDy tweeking, leads to quite some text offset from the symbol)

**Comment by josail** [comment]
Thanks for this hint. I will do so next week when back to my computer. JoAm 09.06.2023 um 18:03 schrieb Anatolii ***@***.***>:﻿
@josail I think you need to create a new issue with this request (the vertical text location, i.e. textDy tweeking, leads to quite some text offset from the symbol)
