### ISSUE TITLE
osmand android don't show leisure=sports_centre names

### ISSUE THREAD

**Issue by summoner001** [osmandapp/OsmAnd#17272]
### Description
Poi with this tags:
leisure=sports_centre
name=Hosszúpályi Sporttelep

Names tag don't show on the osmand offline map.

### Steps to reproduce
https://www.openstreetmap.org/way/1012140076

Go to here in osmand app: 47.38263° N, 21.73407° E

### Actual result
Name don't show on the osmand's offline map

### Expected result
Name showing on map

### Your Environment
OsmAnd Version: OsmAnd~ v4.4.7
Android/iOS version: Android 9
Device model: Cubot Quest
Live update: enabled

**Comment by hakuchi** [comment]
> ### Description
> Poi with this tags:     
**leisure**=sports_centre    
name=Hosszúpályi Sporttelep
**barrier**=fence

barrier and leisure on the same object looks wrong to me...     
OsmAnd is not displaying names of fences

**Comment by xmd5a2** [comment]
![Screenshot_2023-06-02_10-03-06](https://github.com/osmandapp/OsmAnd/assets/5829014/1dfa2056-8664-4e88-91b2-eb4434a62bc5)

**Comment by Zirochkabila** [comment]
Displayed on newly generated maps

<table style="width:100%">
  <tr>
    <th>OsmAnd~ 4.5.0#213m, Released: 2023-06-15</th>
    <th>4.4.10.5</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/e8f0fd13-d919-4cb6-87cb-01e64766859b)"  width="300" height="auto"/> </th>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/391a688c-eed0-4533-a6ea-bf3c47ae989f"  width="530" height="auto"/> </th>
  </tr>
</table>
