### ISSUE TITLE
Screen-off recording broken?

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#17287]
Is anybody aware we changed anything fundamental about how the OsmAnd service or the Trip recording plugin work? 

Ever since a few days ago, potentially since we cut over from builder to creator, I experience sporadic issues with tracks not recording when the screen is off. Not observed on builds before mid May. I am using these device settings which have worked 100% reliably for years https://osmand.net/docs/user/troubleshooting/track-recording-issues/#tested-power-settings-for-android-9-10-and-11-hardy-2020-08-25 on my devicee Samsung Xcover 4s, Android 11 stock. There was a mid May firmware update, but I think limited to security patching. No filtering active, standalone track recording not disabled. Location permission granted.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#97m, Released: 2023-05-26
@sonora I just checked the track recording when the screen is off - the recording works and the track is displayed on the map after the screen is turned on.

**Comment by sonora** [comment]
I'll keep an eye on it. Seems hard to reproduce deliberately. I had zero lost recordinngs in 10 years, and 3 in the last two weeks, strange...

**Comment by sonora** [comment]
I could just reproduce it. Apparently when this happens, the GPS icon consistently turns off about 3 seconds after you put OsmAnd in the background. (No need to turn off the screen). (And note: that without a recording, putting OsmAnd in the background turns of the GPS icon _immediately_). During such a "faulty" recording, the following is 100% reproducible: GPS comes on immediately when I return to OsmAnd, turns off after 3sec when I go to my home screen

Then I stopped the track recording and started a new recording  (did not restart the app!): Now GPS remains always on aa expected, recording with the app in the background works.

It almost feels like maybe the OsmAnd service does sometimes not fully initialize. Could be that it is more reproducible if you start a recording and then_ immediately_ put OsmAnd in the background too fast.

**Comment by sonora** [comment]
Here's how to reproduce the situation: with some likelihood
- Fresh start of the app (Important. I think the situation never develops after previous successful recording)
- Tap the recording widget, tap Start
- Rather quickly afterwards turn the screen off.

If the situation develops, after turning the screen back on, you will see the recording notification on your lock screen and in rhe notification bar, but no GPS icon. The GPS icon will come on while you view the OsmAnd map, but disappear a few seconds after every time you put OsmAnd in the background.

The situation only turns to normal after stopping  the recording and starting a new one.

**Comment by scaidermern** [comment]
Indeed I also experienced this issue with OsmAnd 4.5.0. No lost recordings with the previous versions for years.

During hiking, suddenly a short stretch was missing (the track was straight although the path wasn't). This happened between two interactions with OsmAnd (and probably other apps, not sure). OsmAnd was always in the foreground during screen off.

**Comment by Zirochkabila** [comment]
@sonora This may depend on the Android version or other features (of the device itself).
Because out of 3 attempts, all of them were successful and I could not reproduce

[2023-05-28_14-58_Sun.gpx.zip](https://github.com/osmandapp/OsmAnd/files/11584442/2023-05-28_14-58_Sun.gpx.zip)

https://github.com/osmandapp/OsmAnd/assets/104760013/993712c3-baa1-4ecf-b801-dbbd8e50eea5

**Comment by vshcherb** [comment]
It may depend on flaky Optimization per app enabled. 
I will keep an eye too.

I could only say that I'm not aware of any commits related to Notification / Background...

**Comment by blaueente** [comment]
I am experiencing this as well, since very recently. Pixel 6 Pro with Android 13, August update. Osmand 4.4.7
I now have OSMtracker running in parallel, which is not killed and does record the track. All optimizations are still off, and I remember Osmand working perfectly before.

**Comment by sonora** [comment]
For the time being, I have not observed this any more with recent v4.5's, and these settings: https://osmand.net/docs/user/troubleshooting/track-recording-issues/#tested-power-settings-for-android-9-10-and-11-hardy-2020-08-25. (But Android 11 here, it may well depend on device and OS version...).
