### ISSUE TITLE
Problems in maps with live updates

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#17282]
The video will show how the road breaks when scaling the map.

Geo:
https://osmand.net/map?pin=55.68753,37.34513#20/55.68753/37.34513

_Originally posted by @Nine-Tailed in https://github.com/osmandapp/OsmAnd/issues/14920#issuecomment-1555107703_

<video source src="https://github.com/osmandapp/OsmAnd/assets/12549744/b6c172b7-0d78-440f-8325-621725df59ed"  width="300" height="auto"/>

**Comment by Nine-Tailed** [comment]
One more place:
https://osmand.net/map?pin=55.64136,37.57937#17/55.64136/37.57937
See video:
https://t.me/ruosmand/124409

**Comment by ivanPyrohivskyi** [comment]
OsmAnd~ 4.5.0#56m, Released: 2023-05-20
Best seen with **Topo** map styles
**Ask me map**

`55.64172° N, 37.57949° E`



https://github.com/osmandapp/OsmAnd/assets/104760013/014755d9-fcde-4bde-8ca1-16eb755ff69c
