### ISSUE TITLE
Wrong display at high zoom

### ISSUE THREAD

**Issue by letypequividelespoubelles** [osmandapp/OsmAnd#17288]
### Description
At high zoom I have several problem :
- position icon is way too big
- when I press somewhere  (for distance by tap), the line doesn't go from my position to where I tap. No issues if I tap at two different locations, the line is between the two tapped point.
- it's impossble to open a POI or add note / POI (by long press) as the position where I press or long press isn't the same as where I tap on the screen .

### Steps to reproduce
Zoom a lot and try 

### Your Environment
OsmAnd Version: Fdroid 4.4.7, openGL, 2D.
Android/iOS version: 12
Device model: crossscall  Z5

**Comment by Zirochkabila** [comment]
@letypequividelespoubelles It was tested on the version of OsmAnd from the Play Store, and the behavior you describe cannot be reproduced.
Perhaps the issue is in the Fdroid build. 
Please download OsmAnd from the Play Store and try again.

**Comment by sonora** [comment]
Screenshot may be helpful, particularly for "position icon is way too big".

**Comment by letypequividelespoubelles** [comment]
https://github.com/osmandapp/OsmAnd/assets/54240434/02481b55-afaa-4501-be0d-bae1e320a778


Sorry @sonora , forgot the screenshot last post.

@Zirochkabila I prefer to make donations to Osmand

**Comment by sonora** [comment]
Could it be that you manually changed you position icon from the  small to the big one under Menu button > Configure profile > Profile appearance?

Also: Long tap the plus or minus button and verify your screen magnification is at 100%?

**Comment by letypequividelespoubelles** [comment]
I have the  first (smallest) position icon, and I'm always at 100% zoom (just verified).

**Comment by Zirochkabila** [comment]
@letypequividelespoubelles Please send your profile settings and system settings to OsmAnd.
It seems that you are using karst settings - they could be the reason.
Are you using Microsoft Earth as an Overlay?

**Comment by vshcherb** [comment]
It's a duplicate @Zirochkabila please link to the issue that with Heightmap enabled you can fall under the landscape + Icons change size a lot

**Comment by letypequividelespoubelles** [comment]
Indeeed when I disable heightmap in dev plugin I don't have the issue. 👍

And yes I had Microsoft Earth as underlay, but if I change to an other underlay or no underlay, issue remains. Do you still need my .osf profile ? I need to zip it in order to attach to the GitHub issue, waiting for my laptop

**Comment by Zirochkabila** [comment]
Related to https://github.com/osmandapp/OsmAnd/issues/16559 and https://github.com/osmandapp/OsmAnd/issues/16027
