### ISSUE TITLE
3d mode button working incorrect

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#17289]
### Description
When the map is not tilted, a button with the inscription 3d is displayed and it does not work when pressed.  If you tilt the map with a gesture, the button will display 2d and it will switch the tilt of the map between two tilts.
https://github.com/osmandapp/OsmAnd/assets/12549744/e0544242-84a3-4987-98c7-63c6ffad5dee

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#99m, Дата выпуска: 2023-05-27
Android version: 13
Device model: poco f3

**Comment by Zirochkabila** [comment]
@Nine-Tailed Duplicate https://github.com/osmandapp/OsmAnd/issues/16026#issuecomment-1564554784
