### ISSUE TITLE
Show distance to next alarming object

### ISSUE THREAD

**Issue by eschava** [osmandapp/Osmand#1728]
Now there is only sign shown when you are near the traffic warning object (speed bump or crosswalk)
But it would be good also show distance to that object

**Comment by jf-simon** [comment]
I would like this too. also the warning icon on the point on map would be usefull

**Comment by sonora** [comment]
I have discussed this a lot, most people feel that information overload causes more harm than benefit here, particularly for warnings it should be made clear that something is imminent, then the driver should react, not trying to figure out how far it is.
