### ISSUE TITLE
Map keeps getting listed under updates even after downloading them

### ISSUE THREAD

**Issue by MrHappy** [osmandapp/OsmAnd#17280]
Since recently I had the same issue as in #17243 and that solved almost all, except for one map that keeps getting listed under updates.
In my case (and I know there are others) it is The Netherlands - ZuidHolland that does not update.

OsmAnd 4.5.0 on Lineage 20.0

**Comment by vshcherb** [comment]
Merged back to original issue https://github.com/osmandapp/OsmAnd/issues/17243
