### ISSUE TITLE
destination:lang:XX:forward sometimes fall back to destination:forward

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/OsmAnd#17283]
Osmand fall back to the destination:forward/backward without using lang:XX in some cases.     
I dot know if matter the length of the destination or the present of some symbols in the destination name...

Here some examples:    
https://www.openstreetmap.org/way/1023324996     
Map language set to SV or EN booth works fine

https://www.openstreetmap.org/way/129819481     
https://www.openstreetmap.org/way/129819484
Map language set to IT or DE the first way works fine but he second fall back and show only destination:forward     
[Routing](https://www.openstreetmap.org/directions?engine=graphhopper_car&route=46.81553%2C11.54240%3B46.81737%2C11.53722)

https://www.openstreetmap.org/way/99810133
With language set to EN from [east to south](https://www.openstreetmap.org/directions?engine=graphhopper_car&route=36.7442%2C126.2987%3B36.7428%2C126.2940#map=17/36.74502/126.29578) works fine     
But from [west to north](https://www.openstreetmap.org/directions?engine=graphhopper_car&route=36.74956%2C126.28840%3B36.74872%2C126.29299) fall back to destination:forward and not use english destination

Tested with latest Nightly and maps 05.2023

**Comment by Zirochkabila** [comment]
@hakuchi Please describe the steps to reproduce.
I do not understand what is happening and under what circumstances

**Comment by hakuchi** [comment]
@Zirochkabila go to "Configure map" > "Map language" and set map language to English, Italian or German.

For example 2 use map language Italian    
First way:     
![Pic 1](https://s20.directupload.net/images/user/230531/ewfiwcpe.png)    

Second way have `destination:lang:it:forward` but Osmand use only `destination:forward`:
![Pic 2](https://s20.directupload.net/images/user/230531/4cdph25h.png)    

And for 3th example set map language to English and generate route.    
from east to south `destinalion:lang:en:backward` is used correct:
![Pic 3](https://s20.directupload.net/images/user/230531/ikzmx3ii.png)    

From west to north only using `destination:forward`:
![Pic 4](https://s20.directupload.net/images/user/230531/qwlmru2q.png)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#130m, Released: 2023-05-31
[OSM](https://www.openstreetmap.org/way/129819484#map=19/46.81780/11.53708)
[Map](https://drive.google.com/file/d/1UWpJ45GzZ0ngffb5HqxITzYD9cgap9xS/view?usp=sharing)


### Step to reproduce
Chose Driving profile > Configure map > Map language > Italian
Navigation > From `46.81725° N, 11.53987° E` > To `46.81780° N, 11.53693° E` > Simulate navigation

### Actual result

_Abfalldeponie - discarica di rifiuti_

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/0cb2ff08-6914-4886-a8db-8c7e4e5dc0f6"  width="300" height="auto"/> </th>
  </tr>
</table>  


### Expected
_discarica di rifiuti_

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/77bd2920-9a69-4286-bcce-6ef321f22e8c"  width="600" height="auto"/> </th>
  </tr>
</table>

**Comment by xmd5a2** [comment]
Routing data are OK:
`Road 65492799777 osmid 1023324996 highway='tertiary' lit='yes' maxspeed='40' surface='paved' osmand_ele_start='4' osmand_ele_end='3' osmand_highway_integrity_brouting='1' name="Satamakatu" destination:forward="Satamakonttori;Ravintola Pasaati;Kokkolan venekerho" destination:lang:en:forward="Port office" destination:lang:fi:forward="Satamakonttori;Ravintola Pasaati;Kokkolan venekerho" destination:lang:sv:forward="Hamnkontor;Ravintola Pasaati;Kokkolan venekerho" name:fi="Satamakatu" name:sv="Hamngatan" pointtypes [[3. osmand_ele_asc='0.5' 63.841133 / 23.040607 ][8. osmand_ele_desc='0.25' osmand_ele_decline_1='1' 63.84129 / 23.03851 ][9. osmand_ele_asc='0.25' 63.841187 / 23.03812 ][10. osmand_ele_desc='0.25' osmand_ele_decline_1='1' 63.841118 / 23.037899 ][14. osmand_ele_desc='0.5' osmand_ele_decline_1='1' 63.840973 / 23.036661 ]] lat/lon : 63.840847 / 23.041943 , 63.840878 / 23.041803 , 63.841133 / 23.040607 , 63.841335 / 23.039656 , 63.841377 / 23.039295 , 63.84137 / 23.039017 , 63.84135 / 23.038803 , 63.84129 / 23.03851 , 63.841187 / 23.03812 , 63.841118 / 23.037899 , 63.84105 / 23.037624 , 63.841015 / 23.03745 , 63.84099 / 23.03722 , 63.840973 / 23.036661 , `

**Comment by hakuchi** [comment]
@xmd5a2 yes... the routing on this finish road work fine, 
but the navigation from '**46.81725° N, 11.53987° E**' to '**46.81780° N, 11.53693° E**' is not working correct if I set map language to german.
tested with nightly 4.6.0#859m

**Comment by hakuchi** [comment]
tested today with map from October and some multilingual roads worked. Updated map(to November) and then none of the smaller multilingual roads works around **46.81725° N, 11.53987° E**

looks like a error during map generating

**Comment by yuriiurshuliak** [comment]
It is worth noting that when the map language is set to Italian, it is indicated correctly. However, if local names is selected, the naming problem occurs again.

OsmAnd~ 4.7.0#1537m, released: 2024-02-06

<table style="width:100%">
  </tr>
  <tr>
    <th>Italian</th>
    <th>Local names</th>
  </tr>
  <tr>
    <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/3e7c0fab-f44f-4bfb-b894-57c90c79f494"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/ab3c68b5-3afd-4856-aeb5-110a8add4523"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by dmpr0** [comment]
iOS

<table style="width:100%">
  <tr>
    <th>DE</th>
    <th>IT</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/f344fec2-c844-4122-a86b-ba0964b08db7"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/ee293df8-6f68-4773-822d-759a8416b0a9"  width="300" height="auto"/> </td>
  </tr>
</table>
