### ISSUE TITLE
Bus Routing missing most bus routes

### ISSUE THREAD

**Issue by Arndorferd** [osmandapp/OsmAnd#17295]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Bus routing

### Start and end points

UPMC Mercy, 1400 Locust St, Pittsburgh, PA 15219 
to 
Target, 6231 Penn Ave, Pittsburgh, PA 15206

### Actual and expected routes

This only shows 71B bus routes, should show many routes
 
OsmAnd~
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/41760727/2cf5ba47-fc7f-4c7b-948f-65da653f0a54"  width="300" height="auto"/> </th>
  </tr>
</table>  

Google Maps 
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/41760727/8cce0b4c-bb43-4a13-ae65-dce985579e30"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Is this a regression?

No
 Yes, the previous version in which this bug was not present was: ....

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

4.3.12

</code></pre>

**Device and Android/iOS version:**
Android 12
**Maps used (online or offline):**

- [ x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**

**Comment by scaidermern** [comment]
Do these other bus routes exist in OSM?

**Comment by Zirochkabila** [comment]
@Arndorferd As you can see in the video, many more stops and routes are displayed.
Try updating the app and maps.
Also, pay attention to the data entered in [OSM Public transport](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=40.43600%2C-79.98500%3B40.46100%2C-79.92100#map=15/40.4443/-79.9704&layers=T), they may differ from those on Google maps


https://github.com/osmandapp/OsmAnd/assets/104760013/f2eaf59c-08d8-4c85-a6e0-473fa95d833d

**Comment by vshcherb** [comment]
The mapping data is not present enough + we don't support combination of routes yet.
