### ISSUE TITLE
double text when poi and housename are same

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/Osmand#1729]
with active poi and an housename the names are double. 
See screenshot
![screenshot_2015-09-22-13-42-22](https://cloud.githubusercontent.com/assets/11144987/10018400/bf03cbac-6136-11e5-8353-7d6cfd93d48b.png)

Greetings Simon

**Comment by vshcherb** [comment]
Known issue and not possible to fix now with current rendering engine.

**Comment by jf-simon** [comment]
ok thanks
