### ISSUE TITLE
support tunnel:name:XX and bridge:name:XX

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/OsmAnd#17296]
OsmAnd should support multilingual bridge:name and tunnel:name the same way as it is done with street names

**Comment by Zirochkabila** [comment]
@hakuchi  Please clarify more detail
I tested this place [OSM](https://www.openstreetmap.org/way/244104746#map=16/50.3960/30.5859) and it supported in app

**Comment by vshcherb** [comment]
https://taginfo.openstreetmap.org/keys/bridge%3Aname#overview

**Comment by hakuchi** [comment]
Example:     
https://www.openstreetmap.org/way/452955850
OsmAnd show only "Milos the Great" not "Šarani Tunnel"

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#130m, Released: 2023-05-31
[Map](https://drive.google.com/file/d/1sOM2547jskqYienc-zUaRN8_xRbS-mT2/view?usp=sharing)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/9b1d53c8-c618-4aa2-88ae-a7ca334fe0df"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
@Zirochkabila Shouldn't be issue renamed to support just tunnel:name first ? I don't think we supported it. I'm confused why we talk about translations and don't tag about tunnel name itself

**Comment by hakuchi** [comment]
@vshcherb tunnel:name and bridge:name are supported if you use "local names" in map language. But if you change map language, only the street name is shown.

Bridge https://www.openstreetmap.org/way/149967432     
![Screenshot_20230601-181938](https://github.com/osmandapp/OsmAnd/assets/9936160/b4f3b47d-1730-4314-96ef-94304da0de36)

Tunnel https://www.openstreetmap.org/way/452955850       
![Screenshot_20230601-165247](https://github.com/osmandapp/OsmAnd/assets/9936160/09eb9f84-4216-42e2-a5a3-1fdf8a5ceb58)

**Comment by xmd5a2** [comment]
We are speaking about rendering of tunnel/bridge name instead of street name, right?

**Comment by xmd5a2** [comment]
@vshcherb To solve this issue we need to introduce `lang="true"` parameter to `entity_convert`
https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml#L717
Or we need to overcomplicate rendering style by adding `nameTag="tunnel:name"` to all highways. This will slower rendering a bit.

**Comment by ivanPyrohivskyi** [comment]
Will fix with in new maps (July 2023)
