### ISSUE TITLE
Without turn instructions street name stays the same

### ISSUE THREAD

**Issue by C6competition** [osmandapp/OsmAnd#17305]
Concerning issue #15171 " next turn instruction is way off", it looks like all problems are solved. 

The only thing I noticed is, the top panel doesn't show the name of the street You are driving on, when You are following a track. After there is no more advising instruction necessary at the moment, I expect the top panel to show the name street (leaded by blue arrow) I am driving on. The same way as it happens, if I don't follow a track. Instead of this it shows a street name of a waypoint from the actual track, far away from the momentary position! This repeats every time after advising instructions are finished. In the added video, all instructions are correct proceeded, until you reach the junction "Marienstrasse", where a waypoint is located. When You pass this waypoint the top panel switches to the "Heinrich-Drake-Strasse", which is nearly at the end of the 260 km long track. This name will stay, until the next driving instruction is necessary.

https://github.com/osmandapp/OsmAnd/assets/99248549/d95b2f66-b590-4620-8ed8-da4e0b25b849

Following the track You get to the junction A30, which is correctly advised.
when passing the traffic light, shortly the correct name of the street "A30"
is shown and then the top panel again shows the "Heinrich-Drake-Strasse" until the next advices for following the track are necessary.

https://github.com/osmandapp/OsmAnd/assets/99248549/efdf97ee-12bc-4da9-8438-c113396ce20e

[Emmersee 250 Km.gpx.txt](https://github.com/osmandapp/OsmAnd/files/11600842/Emmersee.250.Km.gpx.txt)

OsmAnd Version: 4.5.0
Android/iOS version: 10.0
Device model: BV 9900E

**Comment by C6competition** [comment]
Today I some more investigations and created a small test track to run in simulation mode.
These small videos only point at the places, where I think something goes wrong.

[Testrunde Bergk Luttern attached.gpx.txt](https://github.com/osmandapp/OsmAnd/files/11614418/Testrunde.Bergk.Luttern.attached.gpx.txt)


Right after the start I would have expected to have the street name with a blue arrow in the top panel, instead of showing the turn right arrow and the street name I am on. In my opinion it is wrong anywhere, because if turn arrow right is shown, it must be the name of the street I am going to (Bergkirchener Str) 

https://github.com/osmandapp/OsmAnd/assets/99248549/6d2f8264-2b91-457c-81d9-5ff0acc7bc0e

The next movie shows the moment (left panel arrow turns green) when I would suggest to show in the top panel the right turn arrow with the name of the street to go to (Bergkirchener Str)

https://github.com/osmandapp/OsmAnd/assets/99248549/65f00d4b-e27e-4498-843f-78dd482a6086

When we pass the exit "Marienstrasse" we also pass a waypoint and the top panel display the correct values: blue arrow with the name of the street we are on.

When we go to a waypoint, the panels are showing a yellow/green arrow. I would suggest to modify it into an arrow with a big dot or ring in its shaft, to notice, it's only a waypoint we traveling to. This would help to recognize, what is going on here. 

https://github.com/osmandapp/OsmAnd/assets/99248549/50b29012-3c1f-43db-ad56-e909416b9f7f


This shows the place, where the top panel again switches much to early to other status

https://github.com/osmandapp/OsmAnd/assets/99248549/aca42b10-70ab-48c0-87f0-74954deec4a3


At this position, when the left panel switches to green, it would have been early enough

https://github.com/osmandapp/OsmAnd/assets/99248549/0340caa7-91be-40e8-bac1-cdb555e93daa

The same happens on and on.



https://github.com/osmandapp/OsmAnd/assets/99248549/1c7903b6-6acc-4a1c-8c6b-415c6634ca57


https://github.com/osmandapp/OsmAnd/assets/99248549/2aeb13b1-b0e8-4c5e-bac1-86f1046b5fc0


After nearly half of the track the top display doesn't show any street name any more until the last street (B65) of the track.    


https://github.com/osmandapp/OsmAnd/assets/99248549/b25d7871-c3c6-469a-870f-60981c3cff35

I hope this helps a little bit to find the reasons for this behavior

**Comment by Zirochkabila** [comment]
@C6competition At first sight, everything seems to work according to the app's algorithms (my testing showed an acceptable result) - Turn in X m = Trigger time (sec) 22 s or Trigger distance (m) Driving: 275 m, Cycling: 61 m, Walking: 24 m (Skipped if less than 15 seconds before turn)

[Street name Widget](https://osmand.net/docs/user/widgets/nav-widgets#street-name) & [Trigger Behavior](https://osmand.net/docs/technical/algorithms/voice-prompt-triggering/#trigger-behavior)

**Comment by vshcherb** [comment]
@Zirochkabila check the street name - it displays only ref but not a street name - so it's strange, looks all roads has a name but almost all videos don't have street name (only refs)

**Comment by C6competition** [comment]
@Zirochkabila 
If You look at the first movie on my last post, you see in the left panel we are about 1.62 km away from the junction, which is declared in the top panel (dispite the street name, which is wrong). If I calculate back with the trigger time of 20 sec, I need a speed of more than 290 Km/h to get this trigger distance ! 
As I don't know how quick simulation speed is, I looked for a similar place on the live recording of the  track out of my first post in this chapter.

[Emmersee 250 Km.gpx.txt](https://github.com/osmandapp/OsmAnd/files/11645183/Emmersee.250.Km.gpx.txt)

There I found this situtation:

https://github.com/osmandapp/OsmAnd/assets/99248549/a133d6f6-095b-405c-a7f8-ae8090a5de9b

Here the top panel switches at a distance 1.92 Km, which returns a speed of more than 330 Km/h to get in 20 seconds to the junction. As You can see I am only driving about 60 Km/h!

To verify my settings I went to the page where to adjust this distances and timings and was surprised:
On the top of the page there is  a slider to adjust this distances/timings. The top values, which are relevant for our problem, don't change their values, when you move the slider from left to right. Is this how it should be?



![Screenshot_20230603-093801](https://github.com/osmandapp/OsmAnd/assets/99248549/886e189e-c45e-49f7-92da-08695f6be47c)
![Screenshot_20230603-093840](https://github.com/osmandapp/OsmAnd/assets/99248549/fb94b4df-f0aa-4d49-a770-0f3f26f67389)
![Screenshot_20230603-093737](https://github.com/osmandapp/OsmAnd/assets/99248549/92914a7f-c8de-4b44-9dde-5a5658617fce)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#188m, Released: 2023-06-11

I could not reproduce the problem with displaying only ref.
However, I was able to reproduce the user's **primary request** - When You pass this waypoint the top panel switches to the "Heinrich-Drake-Strasse", which is almost at the end of the 260 km long track. This name will stay until the next driving instruction is necessary.

### Steps to reproduce

- Build route via user's gpx
- Simulate location via user's gpx
- Start navigation

[Expected](https://www.openstreetmap.org/way/43202793#map=17/52.26642/8.77553)

https://github.com/osmandapp/OsmAnd/assets/104760013/53b298da-c785-469c-9db7-ea35aa5874ae

**Comment by vshcherb** [comment]
It needs to be  confirmed in other type of navigations and it looks like the problem is related to GPX navigation (non attached tracks?)

**Comment by yuriiurshuliak** [comment]
With user track "Emmersee 250 Km.gpx", the street is not indicated correctly, showing "Heinrich-Drake-Strasse" instead of "Bergkirchener Straße".
With no track attached, the street is not displayed at all.
With the track I created, the street is displayed correctly as "Bergkirchener Straße".
With point-to-point navigation, the street is also displayed correctly.

| Attached user track | Unattached track | Track created by me | Point-to-point navigation |
| ----------                 | ------                 | ----------                 | ----------
|<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/66598a9c-2dbd-4493-a2a8-efb18ad69f03"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/5662d992-0132-4504-b6fc-5f867a4adff2"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/da4b9bb9-2d50-4abf-8576-2bee17e3699a"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/f3e77778-0106-4da3-8672-5ab80067725e"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by C6competition** [comment]
Hallo @yuriiurshuliak 

If I am creating the same track as You did, I have no problem as well!
Everything is working, like it's ought to be.

The question is, why is my track not working correctly!



May be it's helpfull, to have the configuration I am using for motorbike 

[Motorrad.osf.txt](https://github.com/osmandapp/OsmAnd/files/11833907/Motorrad.osf.txt)

**Comment by C6competition** [comment]
I found 2 ways to attach a route to the roads:

1. Plan a route/open existing track/select a track/options/attach to the roads
2. Favorites/tracks/select a track/navigation/settings/follow track/attach to the roads/continue

there is a different behavior between these two ways: 

Going the 1. way nothing happens, if You order "attach to the roads", only the prior page comes back with the menue point "options"

Selecting the 2. way initiates a calculation, if You order "continue"
After some while (depends on the length of the track) the menue "apply " comes up and the attach has been done.

I have an additional question: is it possible to save the track as an "attached track", so I don't have to attach it again, when using it for the next time.

**Comment by vshcherb** [comment]
Your track has old data, so it was required to regenerate or reattach again. As we tested if you created again or reattach the issue is gone.

Unfortunately now we don't have an opportunity to automatically reattach once you start track for navigation. However you can Attach to the roads in Plan Route functionality and save it for further usage.
