### ISSUE TITLE
POI search by poi_additional outside poi_category does not works

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1731]
fee=* can't be found
```xml
<poi_additional name="fee_yes" tag="fee" value="yes" />
```

**Comment by vshcherb** [comment]
This is not going to work search is possible only by poi type, outside of poi type or poi category it won't work and it doesn't look reasonable. Possibly we can have additional filter like "open" or "closed", paid or more but it needs to be discussed, cause it doesn't look easy. For now poi additional is primarily for Context Menu.
