### ISSUE TITLE
Configure map / tracks > sorting

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#17315]
### Description
After the update to 4.5.1 the track sorting is set back to "last modified" in all folders/Tabs (had it A-Z) 

Also in the my places / tracks. 
### Your Environment
OsmAnd Version: 4.5.1
Android/iOS version: 13
Device model: S20+

**Comment by sonora** [comment]
Related, or the same: #17278.

**Comment by sonora** [comment]
@Rowin63 Yes, let's pursue the other issue. 2 problems, it seems: One that the sorting seems permanently "forgotten" under certsin circumstsnces. The other thing which may be inproved is that there is no way to set a default sorting, it is tedious to always have to set for each single subfolder.
