### ISSUE TITLE
Buildings with admin_level are incorrectly rendered as a border

### ISSUE THREAD

**Issue by Rilele** [osmandapp/OsmAnd#17310]
### Description
This bug happens with buildings that also have a admin_level key present.
According to [the wiki](https://wiki.openstreetmap.org/wiki/Key:admin%20level):
> It [=admin_level] is also used with other types of objects that are associated with government entities.

Note that boundary=administrative is **not** present.
Links to the two buildings:
https://www.openstreetmap.org/way/185852902#map=18/52.37286/9.74548
https://www.openstreetmap.org/relation/4662941#map=18/52.37266/9.74528

### Steps to reproduce
1. Download Germany -> Lower Saxony -> Hanover -> Standard map
2. Navigate to 52.37311 9.74489 .

### Actual result
The building on the top left (Prinzenstraße 5) has a border around it.
The building on the bottom right (Schiffgraben 10) is only rendered as a border.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/122899461/d9ef0a1e-95c2-4ed5-885f-4c5a65e43dcf"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
No borders are present. The building on the bottom right is rendered correctly,

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.7
Android/iOS version: Android 13
Device model: Android Emulator 13.0 Google Play Intel x86_64 Atom System Image

**Comment by xmd5a2** [comment]
First case is fixed but second requires more efforts. My commit removes `admin_level` if `building` tag is present but this doesn't work if building is mapped as a relation.
https://www.openstreetmap.org/relation/4662941#map=18/52.37266/9.74528
![Screenshot_2023-06-08_09-46-57](https://github.com/osmandapp/OsmAnd/assets/5829014/b3fe653d-f7a7-47c6-b097-76be42a212b1)
