### ISSUE TITLE
Data mismatch in the Distance to target and Camera Elevation widgets if activating Height maps

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#17324]
### To Do

- [ ] Display same data  in **Distance to target** and **Camera Elevation** widgets as before the activation of the **Height maps**

https://github.com/osmandapp/OsmAnd/assets/104760013/c00aca3d-5d67-47f4-9b6b-8968628c63f1

### Description
After activating the **Height maps**, the data in the **Distance to target** and **Camera Elevation** widgets is different
_Data is synchronized after passing the Height map level (20th)_

### Steps to reproduce

- **Menu** > **Download maps** > **Europe** > **Ukraine** > **Download Height maps**
- **Menu** > **Plugins** > **OsmAnd development** > **Settings** > **Test heightmap**
- **Menu** > **Configure screen** > **Right panel** > **Add Distance to target and Camera Elevation widgets**
- **Change zoom level**

### Actual result

https://github.com/osmandapp/OsmAnd/assets/104760013/d74fa067-9016-45b7-ab82-1e952419fe38

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#136m, Released: 2023-06-01
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by vshcherb** [comment]
It's even documented that's correct data.

**Comment by Zirochkabila** [comment]
@vshcherb Please attach a link to the documentation
