### ISSUE TITLE
Offline Raster Map (*.sqlitedb) freezes OsmAnd on iPhone

### ISSUE THREAD

**Issue by skitourenguru** [osmandapp/OsmAnd#17328]
### Description
Since years I am providing beautiful governmental raster maps in the RMaps format (*.sqlitedb) to the comunity. They work perfectly on OsmAnd and GuruMaps:
https://info.skitourenguru.ch/index.php/swisstopo4guru

Since version 4.4.7 (eventually also earlier) these maps don't work anymore on **OsmAnd-iPhone**: **The app freezes as soon as we try to change the new map source**.
On **OsmAnd-Android** the same map continue to work perfectly. Also on other Apps able to handle the RMaps format the maps work.

### Steps to reproduce
1. Download this 4-GByte-Map of Switzerland: https://kdrive.infomaniak.com/2/app/265437/share/e4c54de1-7750-41de-8001-da95db818746/files/212/download
2. Unzipp it and copy the *.sqlitedb to the OsmAnd folder
3. Restart OsmAnd (Stop and Start OsmAnd)
4. Try to change with the OsmAnd-App the "Map Source" to the map: The App freezes for some minutes.

### Actual result
The App freezes for some minutes. Its not possible to switch to the map. From now on OsmAnd doesn't work anymore. Also the former map is not displayed. 

### Expected result
We want to switch to the new map.

### Your Environment
OsmAnd Version:  4.4.7
Android/iOS version: iOS 16.3.1
Device model:  iphone SE (Modellnummer MHGC3LL/A, 2. Generation 2020)

### Remark
It seems that OsmAnd tries to write to the sqlitedb. There is a fresh *.journal in the OsmAnd folder. Why does OsmAnd try to write to the sqlitedb. There is no reason to write to it!

**Comment by vshcherb** [comment]
OsmAnd requires specific indexes to be present in sqlitedb. Most likely it tries to index x/y/z and also calculates bbox.

**Comment by skitourenguru** [comment]
x/y/z is already indexed.
Keep in mind, that the map works on OsmAnd-Android, but not on OsmAnd-iPhone.

![image](https://github.com/osmandapp/OsmAnd/assets/58003532/93e25043-8e03-44ae-a3f0-b734cc8be4c8)

**Comment by skitourenguru** [comment]
The map creation of Skitourenguru is based on GDAL/OGR, the primary output is MBTILES (*.mbtiles). In the second step I convert the map to RMaps (*.sqlitedb). Thats done with the following SQL statements:

DROP INDEX IF EXISTS IND,
ALTER TABLE tiles RENAME COLUMN tile_column TO x,
ALTER TABLE tiles RENAME COLUMN tile_row TO y,
ALTER TABLE tiles RENAME COLUMN zoom_level TO z,
ALTER TABLE tiles RENAME COLUMN tile_data TO image,           
UPDATE tiles SET y=(1<<z)-y-1,
UPDATE tiles SET z=17-z,
ALTER TABLE tiles ADD COLUMN s,
UPDATE tiles SET s=0,
CREATE INDEX IND ON tiles (x,y,z,s),
CREATE TABLE info(minzoom INT,  maxzoom INT),
INSERT INTO info (minzoom,maxzoom) VALUES( 17-(SELECT value FROM metadata WHERE metadata.name='maxzoom'), 17-(SELECT value FROM metadata WHERE metadata.name='minzoom')),
DROP TABLE metadata

**Comment by skitourenguru** [comment]
Could you specify to which table/columns the BBOX is written? The BBOX of which layer? Each layer has a minimally different BBOX.  In which measures? Meters of tile-numbers? If I pre-configure BBOX can I avoid the OsmAnd-iPhone tries to update them?

Android:
On OsmAnd-Android the App definitively doesn't write BBOX to the sqlitedbHowever it seems that also on Android the App writes something to the sqlitedb. Once switched to the new map, the MD5 of the file changes. Hard to say what is written.

iPhone:
I don't know if something is written to the sqlitedb.

**Comment by skitourenguru** [comment]
Okay, it seems on OsmAnd-iPhone (only on iPhone, not on OsmAnd-Android) you create 3 additional indexes:

CREATE INDEX tiles_x_index ON tiles(x)
CREATE INDEX tiles_y_index ON tiles(y)
CREATE INDEX tiles_z_index ON tiles(z)

The question is now, what happens, if I create these indexes. Does OsmAnd delete them and re-create them?

**Comment by skitourenguru** [comment]
It seems indexes are created conditionally:
https://github.com/osmandapp/OsmAnd-core/blob/master/src/TileSqliteDatabase_P.cpp

            if (!execStatement(database, QStringLiteral("CREATE INDEX IF NOT EXISTS tiles_x_index ON tiles(x)")))
            {
                LogPrintf(
                    LogSeverityLevel::Error,
                    "Failed to create index on tiles(x): %s",
                    sqlite3_errmsg(database.get()));

                return false;
            }

**Comment by vshcherb** [comment]
`It looks like a bug ...

**Comment by skitourenguru** [comment]
Here is what happens: OsmAnd checks the number of indexes with:
`PRAGMA index_list(tiles)`
https://github.com/osmandapp/OsmAnd-core/blob/master/src/TileSqliteDatabase_P.cpp

Android:
There are two indexes (IND and sqlite_autoindex_tiles_1). The second one created by sqlite lib. As there are two indexes the additional 3 column indexes are not created.

iPhone:
There is probably only one index detected (IND). Therefore additional 3 column indexes are created. On big files (many GByte) that can take minutes, even hours. iOS eventually doesn't like apps that block the main thread.

**Comment by vshcherb** [comment]
This is doesn't look correct it should be 1 index. We should check that index doesn't tiles table and if it doesn't exist we should create just 1 index

```
CREATE INDEX IND on tiles (x,y,z,s)
```

or

```
CREATE INDEX IND on tiles (x,y,z)
```

**Comment by skitourenguru** [comment]
I suppose you need only one index (IND). What is important to conditionally create indexes:

`CREATE INDEX IF NOT EXISTS on tiles (x,y,z,s)`

Reason: On a 40 GByte file index creation is slow (minutes or hours). So let that do the map providers.

**Comment by skitourenguru** [comment]
On my test file I added now the 3 additional strange indexes. Here is the 4 GByte file:
https://download.skitourenguru.com/temp/CH_SG_TOPO15_MINI4.1_IND.sqlitedb.zip

I let it test a friend (I don't have an iPhone). **It works!** 

Now the question is: What are these 3 dummy indexes good for. Do I have to add them always?

**Comment by vshcherb** [comment]
We will fix it.

**Comment by skitourenguru** [comment]
I would find it better to count indexes (as before) with:
PRAGMA index_list(tiles)

If there is no index, you should create only one index (not three indexes that have no purpose):
CREATE INDEX IND IF NOT EXISTS on tiles (x,y,z,s)
rsp.
CREATE INDEX IND IF NOT EXISTS on tiles (x,y,z)

Tiles are always fetched indicating x,y,z,(s). A performance gain can only be archived, if you create one index that combines x,y,z,(s).

**Comment by Zirochkabila** [comment]
@skitourenguru Can you confirm that the bug has been fixed?

**Comment by skitourenguru** [comment]
I can't test it. I don't have a test environment. I must wait for the next OsmAnd-Version (4.5.8). However according to the code I am sure it is fixed.  Its fine to close the issue.
