### ISSUE TITLE
Routing doesn't support sidewalk key properly

### ISSUE THREAD

**Issue by jluttine** [osmandapp/OsmAnd#17329]
### Description

I'm using OsmAnd routing for walking. A road has a sidewalk tagged with `sidewalk:right=yes` but the routing algorithm doesn't use that but routes a different route which is way too long:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/2195834/3d581c89-b3c9-4f77-b6c3-c06baf056d61"  width="300" height="auto"/> </th>
  </tr>
</table>  

As a comparison, OSM website routing works correctly:

![image](https://github.com/osmandapp/OsmAnd/assets/2195834/e861136e-fb0a-45fe-88af-a381754717bf)

I guess OsmAnd isn't able to make use of the road section that has `sidewalk:right=yes`.

### Steps to reproduce

Link to the OSM website: https://www.openstreetmap.org/directions?engine=graphhopper_foot&route=61.52374%2C23.63629%3B61.52278%2C23.63524

I don't know how to share a routing from OsmAnd. But the route is from Varvunpolku or Varpukuja to Hätiläntie in Lamminpää, Tampere, Finland.

### Actual result

OsmAnd finds a weird long route because it doesn't utilize the sidewalk.

### Expected result

OsmAnd should find the short route similarly as OSM website GraphHogger routing.

### Your Environment
OsmAnd Version: 4.3.12
Android/iOS version: Android 13
Device model: OnePlus 5, LineageOS 20.0

**Comment by scaidermern** [comment]
is this caused by the `foot=use_sidepath` tag?
https://www.openstreetmap.org/way/424580243

**Comment by Zirochkabila** [comment]
@scaidermern Most likely yes

**Comment by vshcherb** [comment]
That's a map data issue
- https://www.openstreetmap.org/way/424580243 this way is forbidden for pedestrian
But there is no connection from 
https://www.openstreetmap.org/way/1026941232
https://www.openstreetmap.org/way/1060129277#map=16/61.5228/23.6386

Once it's fixed everything will be ok

**Comment by jluttine** [comment]
> That's a map data issue
> 
>     * https://www.openstreetmap.org/way/424580243 this way is forbidden for pedestrian

Ok, thanks! Do you mean that having `foot=use_sidepath` makes `sidewalk:right=yes` pointless? So, if `foot=use_sidepath` is used, the sidewalks should be mapped as separate ways, not as `sidewalk:*=yes`? To me this isn't obvious because one valid interpretation could be that a sidewalk must be used and as it's available in `sidewalk:right=yes`, it's ok to use the way (i.e., its sidewalk). But it's not so, is that what you mean? I read OSM wiki but couldn't find an answer there.

**Comment by scaidermern** [comment]
> Ok, thanks! Do you mean that having `foot=use_sidepath` makes `sidewalk:right=yes` pointless?

No, both tags are valid in combination.

> That's a map data issue
> 
>     * https://www.openstreetmap.org/way/424580243 this way is forbidden for pedestrian
>       But there is no connection from
>       https://www.openstreetmap.org/way/1026941232
>       https://www.openstreetmap.org/way/1060129277

It is true that _maybe_ there is a missing connection at this point. Still, the router doesn't handle the sidewalk tag properly!

https://www.openstreetmap.org/way/424580243 is tagged with `sidewalk:right=yes`. This means the road as a sidewalk on the right side (the east side) that is not mapped separately. This means the foot router should use the sidewalk up to this point: https://www.openstreetmap.org/node/32921600. Up from here there is a connection to the separately mapped sidewalk on the other side of the road.

So the ticket title remains valid - the foot router isn't handling sidewalks properly.

In this specific case, the foot router should probably just ignore the `foot=use_sidepath` tag due to the `sidewalk:right=yes` tag. This is a little bit confusing, though.

**Comment by vshcherb** [comment]
Nope 
Footway is connected to https://www.openstreetmap.org/way/424580243#map=17/61.52482/23.63484
tertiary road but tertiary road is not connected to https://www.openstreetmap.org/way/1060129277#map=18/61.52384/23.63619 cycleway.

So router understands instruction not to use tertiary road but it can't jump from tertiary road/footway to cycleway so it gets stuck.

In any case router can only work with connected roads is disconnected. As I see solution is the only feasbile for now to make 
- https://www.openstreetmap.org/way/1026941232 longer up to cycleway

**Comment by jluttine** [comment]
I'm not quite sure what connection is missing. To me it looks like everything is connected as it should. Here's a red line drawn over OSM editor:

![image](https://github.com/osmandapp/OsmAnd/assets/2195834/ad91dcaa-8a0b-43f6-97a0-1490bb9967ba)

And that's the route other OSM walking routers find (e.g., GraphHogger shown above in my original post).

**Comment by scaidermern** [comment]
> So router understands instruction not to use tertiary road

Why doesn't it use the tertiary road? The tertiary road is tagged with `sidewalk:right=yes`. So the router should route along the (implicitly contained) sidewalk, just as shown in the above screenshot by @jluttine.

Yes, the road is tagged with `foot=use_sidepath` but `sidewalk:right=yes` should overwrite this (because then the user doesn't walk on the road but on the (implicitly contained) sidewalk), shouldn't it?

**Comment by vshcherb** [comment]
as I said road ```sidewalk:right=yes``` is forbidden to be used cause sidewalk should be used and without that road there is a gap between roads which couldn't be routed through. 

Picture displays impossible routing

**Comment by scaidermern** [comment]
I don't get it. Why exactly is the sidewalk forbidden?

**Comment by sonora** [comment]
I think Victor means to say the following:
- `foot=use_sidepath` inhibits the pedestrian use of https://www.openstreetmap.org/way/424580243, instead directs all pedestrian use to its (not separately mapped) sidewalk on its east side.
- But that very sidewalk is not connected to any destination on the west side of this road. (The road itself is connected, but it must not be used by pedestrians. Apparently not even _crossed_...).

It is a weird situation, cannot currently say if it is a mapping issue, or if it needs fixing in OsmAnd. Potentially it may not even be an extremely rare mapping case, so probably researching this is justified...

**Comment by scaidermern** [comment]
>     * But that very sidewalk is not connected to any destination on the west side of this road. (The road itself is connected, but it must not be used by pedestrians. Apparently not even _crossed_...).

OK, it is indeed not clear whether the road can be crossed at this point. But I doubt a highway=crossing would help here. Is this really preventing the router from using the sidewalk on the east side?

**Comment by sonora** [comment]
Cannot say. Perhaps @vshcherb can. And maybe not _preventing_ it, but perhaps the corresponding detour is even longer than the other one found?

**Comment by jluttine** [comment]
> EDIT: Could probaly try a destination further south, directly on that tertiary, to verify that the east sidewalk itself is used in that case and hence not per se a problem.

It's not using the east sidewalk at all: https://osmand.net/map/?start=61.523664%2C23.635449&end=61.524322%2C23.635095&mode=pedestrian#18/61.52345/23.63649

![image](https://github.com/osmandapp/OsmAnd/assets/2195834/916e53f5-b51e-4771-9fa1-b54fa47f04bc)

Just to be clear: The correct route in real world is exactly what I drew with the red line in https://github.com/osmandapp/OsmAnd/issues/17329#issuecomment-1575643385 . I still think this is a routing issue as @scaidermern explained in https://github.com/osmandapp/OsmAnd/issues/17329#issuecomment-1576408929 . But if it's a map data issue, could you explain how the map data should be fixed? I see the following two options but neither one is satisfactory in my opinion:

- _Remove `foot=use_sidepath` from tertiary road Ylöjärvenkatu?_ But the tertiary road shouldn't be used for walking, only the sidewalks on east and west side. So, this is correctly tagged.
- _Draw the east sidewalk as a separate way and use `sidewalk:right=yes`?_ But it shouldn't matter whether the sidewalk is drawn separately or not. If it needs to be drawn separately, then why `sidewalk:right=yes` tagging is even a valid tag in the first place? It shouldn't be allowed if it can't be used. (Also, in real world, the east sidewalk is indeed attached to the tertiary road with nothing in between so this is a correct place to use the tag if some place is.)

So, I still think this is a routing issue.

**Comment by vshcherb** [comment]
> Apparently not even crossed.

Exactly the road couldn't be crossed. 

Think about graph edge & vertices. There is no direct edge between footway and sidewalk,  and edges from the road with ```foot=use_sidepath``` can't be used cause "it says that use_sidepath" should be used. 

----------- 
It's impossible to get from the point https://www.openstreetmap.org/node/1608807120  to this point https://www.openstreetmap.org/node/9740137127 which would be **correct routing**. What you saying that walking on https://www.openstreetmap.org/way/424580243#map=17/61.52482/23.63484 is ok if you intentionally reach sideway.

I'm saying it's not ok, you should not use any edge from https://www.openstreetmap.org/way/424580243#map=17/61.52482/23.63484 at all, it's a bad routing. So we can only produce good routing by fixing map and not switching from 1 bad routing to another bad routing.

**Comment by jluttine** [comment]
How should I fix the map so that:

1. It would use the east sidewalk instead of the long route on this example: https://github.com/osmandapp/OsmAnd/issues/17329#issuecomment-1585623338

2. It would use the route drawn with red line on this example: https://github.com/osmandapp/OsmAnd/issues/17329#issuecomment-1575643385

Those are the real-world routes one would use.

**Comment by vshcherb** [comment]
@jluttine please feel free to review it  - https://www.openstreetmap.org/changeset/137518298#map=16/61.5228/23.6386. If its not legal to cross highway than footway needs to be created on the other side of the road

**Comment by jluttine** [comment]
> @jluttine please feel free to review it - https://www.openstreetmap.org/changeset/137518298#map=16/61.5228/23.6386. If its not legal to cross highway than footway needs to be created on the other side of the road

Thanks, but that's not correct. There's no crossing at that point. The correct route is similar to what is shown in this comment: https://github.com/osmandapp/OsmAnd/issues/17329#issuecomment-1575643385

That is, use the east-side sidewalk of Ylöjärventie and then use the crossing near Vuorentaustantie, https://www.openstreetmap.org/way/23883416#map=19/61.52333/23.63541

In addition, the crossing you added wouldn't solve the issue described in this comment: https://github.com/osmandapp/OsmAnd/issues/17329#issuecomment-1585623338

The problem is that the routing isn't using the east sidewalk of Ylöjärventie although it has the tag `sidewalk:right=yes` https://www.openstreetmap.org/way/424580243#map=17/61.52481/23.63484

**Comment by vshcherb** [comment]
I just noticed there are tags 
```
bicycle:backward | use_sidepath
bicycle:forward  | yes
```
And as you said foot also should use the same road
Should not be the same?
```
foot:backward | use_sidepath
foot:forward  | yes
```

I'm afraid I'm still confused so I won't be able to fix something

**Comment by jluttine** [comment]
> ```
> foot:backward | use_sidepath
> foot:forward  | yes
> ```

This wouldn't be correct. For the following reasons:

1. It's not a matter of walking direction (forward/backward) but a matter of side of the road. I mean, one can use the implicit sidewalk (`sidewalk:right=yes`) to walk either direction (forward or backward). Using that kind of direction tagging would mean that one can walk on the road when walking north but not when walking south. That makes no sense in this case.
2. Walking is not permitted on the road but on the implicit sidewalk. Therefore, `foot:*=yes` is incorrect. The correct tagging is what it currently is:
    - `foot=use_sidepath` to say that walking on the road is not allowed
    - `sidewalk:left=separate` to say that the west sidewalk is drawn as a separate way
    - `sidewalk:right=yes` to say that the east sidewalk is implicit and uses the same way as the road itself

So, I still feel this is a routing issue. Especially because of this issue in one of my earlier comments: https://github.com/osmandapp/OsmAnd/issues/17329#issuecomment-1585623338 . In that example, there are no crossings or switching the side of the road, but the routing is still unable to use the implicit east sidewalk of Ylöjärventie.

**Comment by vshcherb** [comment]
Ok,
TODO: allow walking on the road if tags are
```
foot=use_sidepath
sidewalk:*=yes (at least one)
```

But we need to disable if
```
foot=use_sidepath
sidewalk:*=separate (all)
```

**Comment by jluttine** [comment]
Sounds good to me as far as I understand.
