### ISSUE TITLE
Selecting the Germans state for address search

### ISSUE THREAD

**Issue by bitnapper** [osmandapp/Osmand#1732]
To find an address in Germany, one has to select the German state of that address first. But often I am not sure so I have to look it up on Wikipedia first so that I can select the state afterwards. The reason for splitting in several states or whole country seems to be based on file size structural reasons (countrys with huge amount of data are splitted like Germany, others are not).
Maybe you could improve the address search a bit. It would be very nice if one could enter a city and if there are several cities osmand could present them as follows:
- Altenau (Lower Saxony)
- Altenau (Bavaria)

btw: Great work. Love osmand!

**Comment by vshcherb** [comment]
Definitely, it is in our roadmap

**Comment by bitnapper** [comment]
great!

**Comment by utack** [comment]
@bitnapper "Germany adresses nationwide" map is the current workaround.
Takes up a lot of additional space and is a bit outdated, but it works

**Comment by jf-simon** [comment]
Showing the postcode of the town, also would be helpful

**Comment by Paviluf** [comment]
Is it a duplicate https://github.com/osmandapp/Osmand/issues/2539 ?

**Comment by vshcherb** [comment]
Nope it is earlier issue and we are working on a fix for it.

**Comment by sonora** [comment]
Implemented via new search.
