### ISSUE TITLE
Settings card for Paired external sensor screen

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#17323]
## Description
Add **Settings** card to **Sensors screen** for Paired sensors. Main BLE task https://github.com/osmandapp/OsmAnd/issues/15459

## ToDo
* Add Name field
* Add Sensor specific settings, for example **Wheel circumference** for Bicycle speed sensors
* Add button **Forget** sensors

## Card
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/8a868b92-5854-4a0e-983c-8bd2f624af49"  width="360" height="auto"/> </td>
  </tr>
</table>   

- [ ]  **Name**, tap open new screen with edit dialog
- - [ ] first item, always present
- [ ] **Forget sensor**, 
- - [ ] always last item
- - [ ]  icon `ic_action_sensor_remove`

## Name
<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/95cdcf30-cdd2-4fbb-ab88-46c22869c372"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/0fc3f650-7d1b-46c4-8a33-3e850e80d11b"  width="300" height="auto"/> </td>
  </tr>
</table>   

## Sensor specific settings

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/9a3dd533-28af-4492-afde-38983152e5a1"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Lucas-Sichardt** [comment]
Hello and thanks very much for implementing the whole External Sensors Plugin.
Today I tried to start with it but I have no wheel circumference field in the sensor's settings card.
Perhaps this is only shown for known devices? 
By magic there's a speed value shown. But I guess that's more realistically the frequency (cadence or rpm of the wheel? - combined cadence/speed sensor) as without wheel circumference information it should be impossible to guess the speed in km/h.
My device is a CooSpo BK805

**Comment by vshcherb** [comment]
@Lucas-Sichardt did you try beta 4.6 ?

**Comment by Lucas-Sichardt** [comment]
My version is 4.5.10...

-- 

Diese Nachricht wurde gesendet mit Evolution unter Linux Mint Xfce.Am Freitag, den 15.09.2023, 06:06 -0700 schrieb vshcherb:
