### ISSUE TITLE
MyPlaces > Tracks > Search (and locate) issue (OsmAnd+ 4.5.1)

### ISSUE THREAD

**Issue by Boothy99** [osmandapp/OsmAnd#17330]
### Description
Intention = to search for a saved Track and locate / open it on the map.

When entering a search within MyPlaces > Tracks, I can easily find the intended Track. However, I find it difficult to then get to locate it on the map.

### Steps to reproduce
Open MyPlaces > Tracks / select Search then enter part-name of a saved Track (Bracadale used in video).
Item found ? (yes)
Now, I wish to view the track on the map, (which would previously require a "short tap" that opens the map and zooms in to the track start location). 

### Actual result
Currently, (on OsmAnd+ 4.5.1) a "short tap" on the located Track enables the "show on map" checkbox, but doesn't open the map. 
A "long press" on the Track opens a list of my Track Folders with checkboxes ( I'm unsure of what I'd do with this)?? 
No pop-up Options menu opens to locate the Track on the map.

From what I have discovered so far, I need to -
Locate the Track using MyPlaces > Tracks > Search,
Select the checkbox,
Click Apply,
Open "Visible on map" folder (near top of the folders list that is now open)....
Then....

IF I have a number of Tracks already showing on the map - this will have a long list of the "Tracks showing" (on the map), so I again need to locate the track I'm trying to display.
Using the available "Search option" I can again locate the Track I'm after - but a "long press" doesn't display a pop-up option window. A "short-tap" only enables/disables the checkbox.

If I manually scroll through the list and (eventually) find the Track I originally wanted to locate - **THEN** I can long-press that Track, which finally opens a pop-up option menu from where I can "Show on map" (or move / Rename / Share)

### Expected result
Open MyPlaces > Tracks / select Search & enter part-name of a saved Track.
"Long-press" on the located Track to open a pop-up option menu & have OsmAnd open the map and show me the start location (as occurred on previous versions, but with a "short-tap").

### Your Environment
OsmAnd Version: OsmAnd+ 4.5.1 (beta)
Android version: 13
Device model: Google Pixel 6

**Comment by Boothy99** [comment]
https://github.com/osmandapp/OsmAnd/assets/13983995/8c10ddb2-1c25-40a5-bc70-10d62becf89e

**Comment by scaidermern** [comment]
I can confirm this. Showing tracks from the search result (from My Places) on the map doesn't work. OsmAnd 4.5.1.

However, using the regular search window (the one from the top left) to search and show a track on the map works.

**Comment by Boothy99** [comment]
@scaidermern Thanks for confirming and for the tip on using the main map search for Tracks!!
I wasn't aware Tracks could be searched for there, as Tracks isn't part of the headings at the top of the search window 😳 That's an alternative option I/we can use, at least. I've missed seeing that was there before, as I normally go straight to MyPlaces >Tracks and Search / locate from there.
Cheers 👍

**Comment by Boothy99** [comment]
Hi @sonora - Yes, I'd seen your issue #17103 this morning whilst checking to see if this issue had already been mentioned 👍 I agree there's certainly an abundance of menus and sub-items to navigate inside OsmAnd 🥴
I'd also agree that "History" as the default list inside Search is something I never use either. Could be replaced with Tracks??

You mentioned "_when you are on the "_Configure map > Tracks" screen, you can _long-tap a track and then tap "Show on map" in the popup menu___"
Again, using the Search function after opening the Configure map > Tracks screen fails to allow you to open the selected track immediately on it's map location = no pop-up menu "show on map" available 😪

**Comment by sonora** [comment]
@Boothy99 Yes, my first bullet point above only works for the screen you get with "Configure map > Tracks". If from there you move on to perform a search, you are in the regime of my 3rd bullet point.... (and the very situation you opened this issue about...  😉)

**Comment by vshcherb** [comment]
Yes that's not logical and looks like a bug.

**Comment by Boothy99** [comment]
@vshcherb @Chumva thanks

**Comment by Rowin63** [comment]
>     * when you are on the "My Places > Tracks" screen, you can **tap any track's 3-dot menu, then select "Show on map"**,

tapping the 3 dots of a sub folder in "my places - tracks" and choose "display all on map" forwards to that folder in the "new" tracks menu/view, but no track is selected. "display all" should "select all".

**Comment by Rowin63** [comment]
in "my places - tracks": tapping the 3 dots and choosing "set standard look" leads to the track´s color/linestyle options. But nothing is selected (0), so where will this changes/settings be applied to?

**Comment by Rowin63** [comment]
and if I change the settings "direction arrows" to "on" and "start/finish symbols" to "off", next time entering this menu the same settings are selected to arrows "off" and symbols "on" again.

**Comment by Boothy99** [comment]
Thanks @Chumva 👍👌

**Comment by Zirochkabila** [comment]
For an accurate display of the track on the map, https://github.com/osmandapp/OsmAnd/issues/17435 waiting for
The **main task** is completed
