### ISSUE TITLE
Shifted icon - Fixme and Note tags are placed separately. 

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#17338]
## Review
- [ ]  Shifted icon. When Fixme and Note tags are placed separately. 
* * **Fixme** is shifred to the right.
* * **Note** is shifted to the left.

<table style="width:100%">
  <tr>
    <th>Android</th>
    <th>iOS</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/5bbf4e58-631f-4ab9-a8d6-5c5a379da03b"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/e0a4ac1d-1c13-46f4-bd53-4a156e6e0713"  width="300" height="auto"/> </td>
  </tr>
</table>

_Originally posted by @dmpr0 in https://github.com/osmandapp/OsmAnd/issues/14784#issuecomment-1573426589_

**Comment by xmd5a2** [comment]
New maps are not needed.
![Screenshot_2023-06-14_10-06-33](https://github.com/osmandapp/OsmAnd/assets/5829014/706b876c-62ec-45b6-b920-a0b846ca9469)
![Screenshot_2023-06-14_10-05-17](https://github.com/osmandapp/OsmAnd/assets/5829014/144341a0-f4a2-4a4b-8a8a-0ed4898c2905)
