### ISSUE TITLE
Second hand goods yes/no as filter category under clothes shop in order to filter 2nd hand clothes stores

### ISSUE THREAD

**Issue by Erlendur22** [osmandapp/OsmAnd#17336]
# 🚀 Second hand goods yes/no as filter category under clothes shop in order to filter 2nd hand clothes stores

### Description

While strolling through Hamburg I was looking for second hand clothes stores. I had no Internet, therefore I relied on Osmand. Looking for Second Hand stores showed me all second hand stores but I was looking for clothes-only second hand stores. But the ones selling used clothes usually did not show up. This was quite frustrating. 

I then looked into the tagging suggestions and I found out, that clothes-only second hand shops are tagged as clothes shops with the subtag of second hand goods only. But this was not considered in the Osmand search. 
But looking for clothes shops in Osmand I can't filter for second hand stores. Only types like baby clothes, men, women, hats, etc. or organic products yes/no, is possible. 

### Describe the solution you'd like

Solution is an easy filter implementation where the user can filter the clothes stores by second hand yes/no. 

I think this suggestion is really quite handy. I understand that not every subtag can be included in Osmand, but e.g. the Internet Access filter seems unsuitable for clothes stores, bulk purchase is not really necessary and the organic products filter, well, could stay imo. 

Please let me know if my suggestion can be included. 

Greetings Andre

**Comment by Zirochkabila** [comment]
[Taginfo](https://taginfo.openstreetmap.org/search?q=shop%3Dsecond_hand#tags)

**Comment by vshcherb** [comment]
Second hand is a special category - https://taginfo.openstreetmap.org/tags/shop=second_hand#combinations. So it's a separate POI not related to Clothes itself. 

Request https://taginfo.openstreetmap.org/keys/clothes#combinations  - probably it's related to https://taginfo.openstreetmap.org/keys/second_hand#values it's a different story

**Comment by vshcherb** [comment]
@xmd5a2 any suggestions?

**Comment by xmd5a2** [comment]
Fixed. New maps required.

**Comment by Zirochkabila** [comment]
Not displayed on iOS - newest map

<table style="width:100%">
  <tr>
    <th>OsmAnd~ 4.5.0#277m, Released: 2023-06-22</th>
    <th>4.4.10.8</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/1a805347-89e7-4cd8-a312-ca42d886b6c4"  width="300" height="auto"/> </th>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/7316e5d0-cea7-48f8-8fdf-653ba4ae0719"  width="535" height="auto"/> </th>
  </tr>
</table>

**Comment by dmpr0** [comment]
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/14608a8f-5459-4bc8-9b30-eb49baae2579"  width="300" height="auto"/> </td>
  </tr>
</table>
