### ISSUE TITLE
Some kind of new GPS Loggin notification ?

### ISSUE THREAD

**Issue by vrtareg** [osmandapp/Osmand#1733]
Hi

I have noticed that together with the background notification there is a new "GPS Logging" notification which is not dissapearing any whey if the GPS Logging is enabled and OsmAnd is completely closed ...

May be related to #1600 ??

Regards,
Areg

![screenshot_2015-09-23-08-27-25](https://cloud.githubusercontent.com/assets/2562730/10049428/592e2514-620f-11e5-9fac-1980e5d2ee8d.png)
![screenshot_2015-09-23-08-28-04](https://cloud.githubusercontent.com/assets/2562730/10049429/592fdabc-620f-11e5-8bc4-44790b46fe7d.png)
![screenshot_2015-09-23-08-28-11](https://cloud.githubusercontent.com/assets/2562730/10049427/592d7862-620f-11e5-994b-38eea37e508b.png)
![screenshot_2015-09-23-08-28-44](https://cloud.githubusercontent.com/assets/2562730/10049426/592a9eb2-620f-11e5-9501-6792172ebb1e.png)

**Comment by vshcherb** [comment]
Yes it is related to #1600 and we are going to redesign it very soon, to come back to 1 notification.

**Comment by vshcherb** [comment]
Sorry it is not related to 1600, but will be fixed soon anyway.

**Comment by sonora** [comment]
It does need fixing, though, it has some issues:
- It remains shown even after a GPX track recording was stopped and saved
- it remains visible even after OsmAnd was closed (only disappears if you force-close OsmAnd)
- it sometimes shows "Stop" or "Save" buttons (also when no track is recording had been started) which seem to have no function

**Comment by vshcherb** [comment]
I hope to provide fix this week, it is slightly newer, so let's validate after that.
