### ISSUE TITLE
Erratic altitude measurements

### ISSUE THREAD

**Issue by ManDay** [osmandapp/OsmAnd#17334]
I'm using OsmAnd on a Google Pixel 3a with LOS 19.1 and get erratic altitude samples when recording, notably during free flight but not during hiking. I suspect this might be related to barometric samples not being weighted correctly when they are combined with GPS and gyrometric measurements.

The aberration is virtually always upwards and in a manner consistent with encountering thermals, which also cause upwards acceleration. However, the aberration is way beyond anything which should be permitted by the uncertainty of the gyrometer or GPS, which seems to suggest a bug in the algorithm.

[Recorded Track (zipped)](https://github.com/osmandapp/OsmAnd/files/11635677/gpx.zip)

Here is a visualization taken from https://www.sportstracklive.com

![SportsTrackLive.com](https://github.com/osmandapp/OsmAnd/assets/1059827/45b3e963-b56a-42ba-b4fc-ed2d30f2bcb7)

**Comment by vshcherb** [comment]
Did you try to switch Location API - from Google Play Service s to Android API

**Comment by ManDay** [comment]
It's a LineageOS without Google Apps/Play Services.

For what it's worth, there is a System Application `com.android.location.fused` called "Fused Location", just in case that would indicate that the bug was in a component outside of OsmAnd (but I *think* "Fused Location" only combines RF signals with GPS).

**Comment by scaidermern** [comment]
> It's a LineageOS without Google Apps/Play Services, so I assume the answer is No.

Better check anyway. Settings / OsmAnd settings / Location source. If this entry exists (it won't in the frdroid build) then it should be set to Android API.

**Comment by ManDay** [comment]
Ah, I misunderstood. I thought that was an Android setting, because indeed I didn't see it anywhere. I am using the fdroid build and no such entry appears.

**Comment by ManDay** [comment]
I just took a quick look at https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/src/net/osmand/plus/OsmAndLocationProvider.java and it seems like OsmAnd is not considering barometric measurements and uses the location as-is from the Android location provider, is that correct?

Does that imply the problem lies outside of OsmAnd? Should I try a different application (which?) to log to GPX and see whether it exhibits the same irregularities?

**Comment by sonora** [comment]
@ManDay  Yes, that would be my guess also: I have currently no explanation what could go wrong inside OsmAnd to cause this, and would suspect something in your underlying system and/or its (Location related) settings.
-You could try a recording with another app to verify if it looks similar or different.
- Have you looked at your actual recorded GPX file in a text editor, does it really contain these singularities in its `ele` tags? Does it somehow correlate wirh changes in the `speed` and/or `hdop` tags?
- How do recordings look you take while driving or walking, do they have similar artefacts?

**Comment by scaidermern** [comment]
> Should I try a different application (which?) to log to GPX and see whether it exhibits the same irregularities?

OSMTracker is quite nice and small for simple track recordings.

**Comment by ManDay** [comment]
@sonora Yes, the singularities are in the file, they also show in the OsmAnd "Analysis" pane and I can see the jumps in altitude live while they're being recorded, too. There seems to be no correlation with `hdop` or `speed` - both remain within their usual range.

I will do more tests on the ground and also try OSMTracker and report back.

**Comment by ManDay** [comment]
I report two findings:
- The problem could not be reproduced while driving or walking over the course of several weeks.
- Eventually I tried it with a tracking app called [GPS Logger](https://play.google.com/store/apps/details?id=eu.basicairdata.graziano.gpslogger&hl=en&gl=US&pli=1) and it showed the exact same artefacts.

I'm therefore closing the issue. An [upstream bug](https://gitlab.com/LineageOS/issues/android/-/issues/5975) has been filed at LOS.
