### ISSUE TITLE
Blink mode

### ISSUE THREAD

**Issue by zekooooo** [osmandapp/OsmAnd#17341]
Traffic signals that are marked with traffic_signal=blink_mode are displayed in the same manner as those that don't have this tag.

They should instead be ignored by renderer & routing or at least grayed out.

Blink_mode means the signals are permanently blinking yellow and traffic should ignore them and use other signs like yield and stop.

This can be temporary for a few months to get people used to a new traffic light, but I've mapped more than a few intersections in my city that have been on permanent yellow since I was a kid.

Checked with latest OsmAnd~ 4.3.12 on F-Droid, but this has existed since 3.x.x at least.

**Comment by xmd5a2** [comment]
Hi. I've checked [this node](https://www.openstreetmap.org/node/246834665) and it is removed from rendering and routing as long as couple of year. This is how it is rendered in OsmAnd:
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/0b52d3c5-2e71-4ac4-b451-233574421ec0)

**Comment by zekooooo** [comment]
I've checked that one and the ones in my city, they work fine now except for the pedestrian crossing ones, which probably shouldn't be marked like that anyway, since they're simply turned off & not blinking. I think it may have had something to do with the live update feature.

**Comment by dmpr0** [comment]
@ivanPyrohivskyi @xmd5a2 provide feedback about what was done or not.

**Comment by xmd5a2** [comment]
@dmpr0 Issue was not reproducible
