### ISSUE TITLE
Brouter navigation: option "Offline calculation of OsmAnd route segment" is undocumented

### ISSUE THREAD

**Issue by Max1234-Ita** [osmandapp/OsmAnd#17347]
### Description
I'm trying the BRouter navigation in OsmAnd: I installed Brouter app and did all the configurations as described in the dedicated documentation page ([https://osmand.net/docs/user/navigation/routing/brouter]()).

Unfortunately, in the route settings menu I found the option "Offline calculation of OsmAnd route segment": What is it for?
I tried looking into the docs but I wasn't able to find anything. 
I see there's a "This article is incomplete" mark on the BRouter page, so I guess something is actually not added yet; I think adding the missing information would help many users.

### Steps to reproduce

1. Have Brouter app installed and configured as described in the documentation
2. In OsmAnd, select a profile (i.e. "Biking"); 
3. Go to menu _/// -> Configure profile -> Navigation settings -> Navigation type_; Select **BRouter (offline)**
4. Go back to the main screen; search for a destination and start navigating;
5. In the route overview, tep the Settings button; observe that option "Offline calculation of OsmAnd route segment" is present:

![image](https://github.com/osmandapp/OsmAnd/assets/15315381/ace174a2-51d9-450e-8f25-1f4ac560e3ca)

6. Go to the BRouter documentation page ([https://osmand.net/docs/user/navigation/routing/brouter]()) and check the _Route parameters_ section; Observe that such an option is not described there.
7. Go to the Route recalculation page (https://osmand.net/docs/user/navigation/setup/route-navigation#route-recalculation) and check the _Route recalculation_ parameter table;  observe that there is no description either.
 

### Actual result
Option "Offline calculation of OsmAnd route segment" is not documented

### Expected result
Some explanation of the function should be added: 

- what id does;
- how do the switch next to the option is working; what does toggling/untoggling it does.

### Your Environment
OsmAnd Version: OsmAnd+ v. 4.4.7
Android/iOS version: Android 11
Device model: Samsung Galaxy A50 (SM-A505FN/DS)

**Comment by Zirochkabila** [comment]
@Max1234-Ita  Offline calculation of OsmAnd route segment - will be removed for online navigation https://github.com/osmandapp/OsmAnd/issues/17405
As for the BRouter article, it will be written later.
You can join the description by clicking on the **Make a сontribution** button https://osmand.net/docs/user/navigation/routing/brouter/

**Comment by Max1234-Ita** [comment]
@Zirochkabila, thanks for this feedback!

It looks like the devs are discussing this topic: removal has been proposed, not sure yet if the option is going to be taken off or not, anyway I agree with them, if you choose to navigate online you should not go with offline navigation.

**Comment by vshcherb** [comment]
Still could be documented, it will cost 1 h to document and couple of months to properly delete

**Comment by DmitryAlexei** [comment]
https://osmand.net/docs/user/navigation/routing/online-routing#online-routing-setting
