### ISSUE TITLE
Coastline rendering problem

### ISSUE THREAD

**Issue by robinpaulson** [osmandapp/OsmAnd#17346]

**Comment by robinpaulson** [comment]
![](https://i.imgur.com/GkZoBhq.png)

Near Mahurangi east, Tamaki Makaurau-Auckland, Aotearoa-New Zealand

**Comment by robinpaulson** [comment]
36.48932° S, 174.74814° E

**Comment by robinpaulson** [comment]
The lower right third of the scree is showing water, although it is masked by the green of the park and the wood. Rendering engine v1.

**Comment by robinpaulson** [comment]
I'm using v4.4.7, from fdroid

**Comment by Zirochkabila** [comment]
@robinpaulson not reproduced
Try the following: 
1. Refresh the maps
2. Install the version of OsmAnd from the Play Store
3. Install the night version https://osmand.net/docs/versions/nightly_versions
