### ISSUE TITLE
Button to hide Landing screen menu – Android Auto 

### ISSUE THREAD

**Issue by kit4short** [osmandapp/OsmAnd#17353]
# 🚀 feature request

### Description

I am running version 4.5.1 of Android released on the 30th May 2023 and running Android Auto version 9.4.631624.

While using Android Auto, the OSMAnd screen now shows a menu on the left hand side that cannot obviously be cancelled or hidden.. The menu displays favourites etc in a scrollable list.

The scroll bar in the list cannot be scrolled by hand and the down arrow in the pop up menu is hidden behind the icon bar at the bottom of the Android Auto icon bar.

If the user wishes to just display the map and follow the roads, this is no longer possible without selecting a track, favourite, marker etc first to navigate to. Obviously this pop up menu seriously inhibits the screen real estate available for use of the map in the Android Auto display when nothing has been chosen from the pop up

### Describe the solution you'd like

I think the pop up menu is an improvement on the previous display for Android auto, but for some users (like me), I often just want  the map displayed so I can see the route I am taking, so would like to be able to cancel It's display

All that is needed is for some mechanism to close or cancel that pop up menu so that the whole screen can once again display the map

### Describe alternatives you've considered

There is no obvious workaround to this issue unless there is some hidden mechanism to cancel the pop up menu display

**Comment by jf-simon** [comment]
I have the same Problem.
I cant hide the "Menu"
![image](https://github.com/osmandapp/OsmAnd/assets/11144987/0dcf3dd6-20ff-4060-931f-e1342f355c0c)

also it is not possible to center back to current position

thanks for looking at this issue

Greetings Simon

**Comment by jf-simon** [comment]
i other issue with the new menu.
if i'm in an active routing and switch within android auto to an other app and back.
The menu pops up, and i cant hide it. i have to stop and restart the routing.

![image](https://github.com/osmandapp/OsmAnd/assets/11144987/81898a01-dccc-4fde-a90d-c5c102cf8d5f)

**Comment by dmpr0** [comment]
@jf-simon and the route is disappear?

**Comment by jf-simon** [comment]
no the routing is still active an shown

**Comment by Zirochkabila** [comment]
<table style="width:100%">
  <tr>
    <th>While navigation</th>
    <th>Without navigation</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/30a4be1f-5543-483a-bad6-18a28dbc9cdf"  width="300" height="auto"/> </th>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/44ec3a24-402a-4184-916d-0e14e314aff8"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by gena01** [comment]
I have experienced the bug reported above. (We should probably split that into a separate issue?) The bug is context/task switch doesn't stop navigation and I end up with active medication in the background and android auto pop-up on top. I can't cancel navigation or make the pop-up go away.

**Comment by vshcherb** [comment]
For now we've introduced a button to hide and later to open the list should be available today with 4.5.3 beta.

**Comment by jf-simon** [comment]
thanks, looks good and works fine

**Comment by dmpr0** [comment]
## Review
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/71c90037-3c7b-4b2e-b550-70f3823a2133"  width="400" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/435464f1-2042-4b92-9df2-3a9df32f7e23"  width="400" height="auto"/> </td>
  </tr>
</table>   


- [ ]  Rename `Free mode` to `Free ride`
- [ ] Use `ic_action_start_navigation` icon

### Free ride
- [ ]  Use `ic_action_list_flat` icon for menu

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/navigation/auto-car
