### ISSUE TITLE
Customise the POI Overlay menu

### ISSUE THREAD

**Issue by quixoticgeek** [osmandapp/OsmAnd#17352]
### Description

Would be really useful to customise the default "Show POI overlay" list to include POI's that are commonly used by the user, but are not in the default list. 

### Describe the solution you'd like

A setting somewhere obvious that allows the "Show POI Overlay" list to be configured by the end user. 

### Describe alternatives you've considered

Searching every time I want to use a POI that is not in the list. It's getting really annoying after a couple of years of regular use.

**Comment by mikehgentry** [comment]
You can just use search, then select categories, select a few things, then in the top right save that as a custom filter.

You can also assign that custom filter to a quick action, if required.

**Comment by quixoticgeek** [comment]
Adding stuff to the menu is one thing, with the saved custom stuff. But it would be really useful to be able to remove the stuff I don't need. In a landlocked country as a cyclist, I don't need a menu offering me nautical stuff one click away.

**Comment by dmpr0** [comment]
You can customize list of POI categories, in Menu – Search – Rearrange categories. It will apply for POI categories list in Search – Categories and in the dialog Configure Map – Show POI Overlay, because it the same list.

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/86b311eb-0cd9-45c2-aafd-1822b966d43b"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/8e5b4af5-3d6a-4f6b-a719-04990bd6955e"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/ebb9c111-73dc-4080-8409-3b07ed356b89"  width="300" height="auto"/> </td>
  </tr>
</table>
