### ISSUE TITLE
Null/empty tile in specific location

### ISSUE THREAD

**Issue by jsloan-red-button** [osmandapp/OsmAnd#17356]
Location at 
https://www.openstreetmap.org/#map=17/54.46875/-5.62224
fails to render properly ( see attached screenshots )
blank shape appears around the transition from 1mi to 0.5mi zoom
zooming in, it looks like the colours for that particular region have been inverted - the island is in blue on a grey sea.
I tried a fresh reinstall, in case it was a local corruption, but the new install shows the same issue.
I've included a satellite image of the area in question for comparison.
Any more information I can supply ?
### Your Environment
OsmAnd Version: 4.4.7
Android/iOS version: 11
Device model: Cubot Kong Kong Pro 5
![signal-2023-06-05-134550_005](https://github.com/osmandapp/OsmAnd/assets/548516/fc5104fe-9bce-4d7f-bb89-897ac9079ebe)
![signal-2023-06-05-134550_004](https://github.com/osmandapp/OsmAnd/assets/548516/dbf87bc6-2365-4ddf-890f-466f62e7db11)
![signal-2023-06-05-134550_002](https://github.com/osmandapp/OsmAnd/assets/548516/c5819354-261a-4b9b-b58e-162d027e3e2b)
![signal-2023-06-05-134550_003](https://github.com/osmandapp/OsmAnd/assets/548516/81e782ac-f867-4b07-b7eb-2c3029a63bc1)
![Screenshot from 2023-06-05 13-43-01](https://github.com/osmandapp/OsmAnd/assets/548516/ae3de499-e12c-4ea0-89dc-7e936d64fa76)

**Comment by Zirochkabila** [comment]
<table style="width:100%">
  <tr>
    <th>OsmAnd~ 4.5.0#154m, Released: 2023-06-04</th>
    <th>4.4.10.2</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/104760013/2088f493-5fea-4a46-bbce-a8807bddc101"  width="300" height="auto"/></td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/104760013/94590780-2486-4774-86ce-e360daf50e2c"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/17264
