### ISSUE TITLE
POI Overlay does not persist between app starts

### ISSUE THREAD

**Issue by quixoticgeek** [osmandapp/OsmAnd#17350]
### Description

Setting up a POI overlay, say for "Drinking Water" the POI shows up as the orange icon. Switching to another app, then switching back to OSMand, the app loads a fresh without the POI overlay. 

### Steps to reproduce

- enable POI overlay. 
- Switch to another app on the device
- swap back to osmand.

### Actual result

POI overlay not enable.

### Expected result

POI still enabled. 

### Your Environment
OsmAnd Version: 4.4.7 2023-04-10
Android/iOS version: Android 11
Device model: Fairphone 3+

**Comment by Zirochkabila** [comment]
@quixoticgeek  Please update the app and try again.
Can't reproduce - POIs continue to be displayed even after reopening
It will also be useful if you add a log file: Menu > Help > Send logcat log
