### ISSUE TITLE
Bicycle router ignores vehicle:forward=no and vehicle:backward=no

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#17362]
In bicycle routing, the access tags `vehicle:forward=no` and `vehicle:backward=no` are ignored. OsmAnd 4.5.1.

Examples:
* https://www.openstreetmap.org/way/60696575
* https://www.openstreetmap.org/way/28003582

Screenshot for the first example:
![photo_2023-06-06_08-40-22](https://github.com/osmandapp/OsmAnd/assets/1040784/cce6edc2-ffbf-4ff3-b3c8-f46820e0bde0)

GraphHopper handles these access tags correctly:
https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=50.62646%2C12.81440%3B50.62742%2C12.81369

OSRM doesn't:
https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=50.62646%2C12.81440%3B50.62742%2C12.81369

Valhalla doesn't:
https://www.openstreetmap.org/directions?engine=fossgis_valhalla_bicycle&route=50.62646%2C12.81440%3B50.62742%2C12.81369

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#191m, Released: 2023-06-12
`50.62646, 12.81440`
[OsmAnd](https://osmand.net/map/?start=50.626628%2C12.814431&end=50.627418%2C12.813655&mode=bicycle#19/50.62708/12.81458)
[OSM](https://www.openstreetmap.org/way/60696575#map=18/50.62705/12.81491)
[Map here](https://drive.google.com/file/d/1gU5JL6bnr8yVo7blkYUA1OYRy_SMa7ab/view?usp=sharing)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/2f3be558-50df-414a-afbf-10b83899353a"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by xmd5a2** [comment]
Fixed. No new maps required.
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/0c7a7866-479f-4183-b687-a0adb478f027)
Also fixed for `car` and `moped` routing
