### ISSUE TITLE
Contour lines file missing for Acuerdo de Campos de Hielo (Chile/Argentina) region

### ISSUE THREAD

**Issue by phlustik** [osmandapp/Osmand#1736]
Hello,
I cannot find the proper file to download contour lines for a special area on the Chile/Argentina border, called Acuerdo de Campos de Hielo - most likely because it is neither Chile nor Argentina (not included in their borders), see e.g., http://wikimapia.org/9885986/es/Acuerdo-de-Campos-de-Hielo-%C3%81rea-sin-delimitar
The OSM relation is 4112727
Please consider making it a separate region for downloading.
Thanks.

**Comment by xmd5a2** [comment]
Fixed. Expanded Chile_magallanes-and-chilean-antarctica_southamerica_2.srtm.obf.zip and Argentina_santa-cruz_southamerica_2.srtm.obf.zip to cover this region

**Comment by sonora** [comment]
We have more issue like this, it likely deserves a systematic approach. I recently received a complaint that while we have one consolidated download "Carribbean archipel" for regular vector maps, which is good, the hillshade overlay needs to be downloaded for each tiny island separately, which is certainly cumbersome and counter-productive. We probably should completely align the download regions, structure, and naming convention for all our map types.
