### ISSUE TITLE
Don't show hungarian region names when 'Use latin name if missing' is enabled

### ISSUE THREAD

**Issue by summoner001** [osmandapp/OsmAnd#17366]
### Description
Osmand don't show simple name tag in Hungary region when the poi is:
admin_level=5
place=region
Osmand show the name:en tag on the map, and don't use name=* tag (name=* tag is the Hungarian name of the place)
On OSM: https://www.openstreetmap.org/node/775498603 or https://www.openstreetmap.org/node/775498606

### Steps to reproduce
1) Map settings
2) Map Language: Hungarian
3) Use latin name if missing option is enabled

Go here in osmand: 47.94376, 20.32128 or 47.17596, 16.88505

### Actual result
Osmand render use name:en=*
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/11212632/8f9ea750-c4d1-4e0b-b298-d885067cac51"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/11212632/de4a01e0-e0ee-421b-9641-2d9acb52bc8f"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
Osmand render use simple name=* tag in Hungary

### Your Environment
OsmAnd Version: 4.5.1
Android/iOS version: Android 9
Device model: Cubot Quest

**Comment by summoner001** [comment]
Same here: name:en=Beehive Stone (name=Kaptárkő)
![Screenshot_20230606-170503](https://github.com/osmandapp/OsmAnd/assets/11212632/8b77b4ac-ae31-4391-9fae-760392238526)

OSM: https://www.openstreetmap.org/node/3242559801
GPS: 47.41383, 18.93542

**Comment by Zirochkabila** [comment]
### Steps to reproduce

- Go to `47.41383, 18.93542`
- Configure map > Map language > Hungarian (Use Latin name..) > Apply
- Menu > Settings > OsmAnd settings > Map rendering engine > V1


https://github.com/osmandapp/OsmAnd/assets/104760013/27bfd284-ce2f-4b98-9073-517009bdf835

**Comment by summoner001** [comment]
This is not the problem.

1) v2 OpenGL
2) settings > osmand settings > Language (hungarian/magyar) > restart osmand required by settings
3) map settings > map language > hungarian and Latin transcription enabled
4) search menu > type this > Tolvajos tanya 178/A

**Comment by summoner001** [comment]
And try this:

And go here: Go here in osmand: 47.94376, 20.32128 or 47.17596, 16.88505

**Comment by summoner001** [comment]
Multipolygons without name:hu, but now i add the name:hu bacause this issue is closed without solution

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/9413
