### ISSUE TITLE
Dynamic zoom when navigating, depending on the current speed

### ISSUE THREAD

**Issue by sjvudp** [osmandapp/OsmAnd#17377]
# 🚀 feature request

### Description

I couldn't find it, so I guess it's new:
I'd wish for a "dynamic zoom" that depends on the driving speed when navigating or following a route.
"Dynamic zoom" means the map should be scaled down when driving fast, and be scaled up (zoom in) when driving slower.
So when driving slowly in a narrow city the zoom should be much larger than when driving on the Autobahn (for example).
Also when approaching a roundabout or road crossing (junction) the map should zoom in on that.

### Describe the solution you'd like

There should be a switch to turn the feature on and off, maybe allowing for more detailed customization, too.
The feature should work in 2D and 2.5D mode of the map.

### Describe alternatives you've considered

Zooming the map manually while driving is a thing one is not expected to do.

**Comment by sonora** [comment]
Menu button > Settings > Driving profile > Navigation settings > Map during navigation > Auto zoom map

**Comment by vshcherb** [comment]
It should work automatically but we plan to improve situation

**Comment by sjvudp** [comment]
> Menu button > Settings > Driving profile > Navigation settings > Map during navigation > Auto zoom map

I must admit that I overlooked that, probably because not having "auto" on the radar when looking for "dynamic" ;-)
