### ISSUE TITLE
Boat navigation failed unexpectedly (no route found)

### ISSUE THREAD

**Issue by sjvudp** [osmandapp/OsmAnd#17378]
### Description
I have no boat, but for fun I asked OsmAnd for a route between two harbors.
OsmAnd said it could not find a route.

### Steps to reproduce
Here is the basic setup. I made sure that both points are in the water.
![Screenshot_1](https://github.com/osmandapp/OsmAnd/assets/6734808/3a048f0e-6031-42ed-b7b0-52a31603f18e)
![Screenshot_2](https://github.com/osmandapp/OsmAnd/assets/6734808/02390740-facf-4039-b571-4904fd5e22c8)

### Actual result
No route could be found

However when I had moved the starting point a bit by mistake, a route could be found, but the route is partially on land:
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/6734808/17be5278-ea9c-4193-840d-6d5f7b866358"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
A route should be found, preferably one using the official boat route
### Your Environment
OsmAnd Version: 4.4.7
Android/iOS version: 13.1
Device model: Oppo Find X5 Lite

**Comment by DmitryAlexei** [comment]
According to what is written in the OsmAnd documentation, [Boat routing](https://osmand.net/docs/user/navigation/routing/boat-navigation) type is designed for sailing by channels, rivers or fairways. Boat routing is not recommended for open water navigation, it is suggested to use [Direct to point](https://osmand.net/docs/user/navigation/routing/boat-navigation#direct-to-point-routing-for-boat.md) routing type instead.

**Comment by sjvudp** [comment]
> I also had no luck with the provided route in Indonesia, and in most other cases when I tried to make a route across the open sea. With rivers, routing works fine.

Maybe my fault was trying to navigate from harbor to harbor when actually the harbor POI is considered to be _land_, and _not water_.
