### ISSUE TITLE
My Places > Tracks crashes when tapping 'Select' too soon

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#17382]
In addition to the crash reports in #17290 and #17337, here's another way to reproducibly crash this screen after its recent modifications:

Go to 'My Places > Tracks', and while the screen is still collecting all your folders and tracks, tap on 'top right 3 dots menu > Select'. The app will crash immediately.

[exception.log.txt](https://github.com/osmandapp/OsmAnd/files/11682772/exception.log.txt)

**Comment by DmitryAlexei** [comment]
Maybe it depends on how many tracks you have. 
OsmAnd~ 4.5.0#182m, released: 2023-06-08 does not crash for me with 64 tracks (5 folders). It doesn't matter if those tracks are displayed on map or not.

**Comment by sonora** [comment]
@Zirochkabila It's independent of the tracks.  😉  Just use a slower device, or more tracks. Perhaps use a file-manager to duplicate your 200 files 10 times or so. It is 100% reproducible. All you need to do is tap the "Select" menu before the orange (in dark theme) horizontal running bar has stopped/disappeared.

**Comment by Zirochkabila** [comment]
@sonora I will try to check again by increasing the number of tracks
Please attach a video with your result

**Comment by sonora** [comment]
Not much to record... this is the last screen the app will show before the crash, when you tap "Select" here at this stage...

![Screenshot_20230613-182022_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/845735/5c0ba979-085c-4cf9-b607-abf9fa39e5f6)

**Comment by zipav** [comment]
### Steps to reproduce: 
Menu → My Places → Tracks  → ⁝ →  Select 
Number of tracks increased to 1000

OsmAnd Nightly 4.5.0#196m, released: 2023-06-13

https://github.com/osmandapp/OsmAnd/assets/123936521/7233e401-9ddd-4746-9119-ba0ebaee8589

**Comment by sonora** [comment]
You need to tap "Select" while the screen is still collecting the tracks to display, i e. while the **spinner is showing**.

For me this takes about 3-5 seconds. For you it looks a lot faster - likely depends on device and number of tracks.(It's actually unclear why this scales with the number of tracks you have and can take so long - our previous screen showed up instantaneously).

**Comment by zipav** [comment]
OsmAnd Nightly 4.5.0#208m, released: 2023-06-14

[exception (18).log](https://github.com/osmandapp/OsmAnd/files/11748053/exception.18.log)

### Steps to reproduce:

- Menu
- My Places
- Tracks
- ⁝ (3 dots menu)
- Select
Number of tracks increased to 1000


https://github.com/osmandapp/OsmAnd/assets/123936521/8e8c368e-c358-4f70-b647-4d2c7d9c8585
