### ISSUE TITLE
Weird Car Routing

### ISSUE THREAD

**Issue by meyverick** [osmandapp/OsmAnd#17389]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Car Fuel-efficient way.

### Start and end points

- From: [50.40615, 4.39517](https://www.openstreetmap.org/#map=18/50.40615/4.39517)
- To: [50.40875, 4.39522](https://www.openstreetmap.org/#map=18/50.40875/4.39522)

#### Actual:
<table style="width:100%">
  <tr>
<th><img src="https://i.imgur.com/V9Smaih.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>  

#### Expected:
Straight.

### Is this a regression?

I made many changes to this area (more lanes, more precise road, ...) without results.
I had a similar bug that has been possible to fix because it wasn't allowed to make what suggest OsmAnd (we added a relation that prohibit turning left (https://i.imgur.com/yeewjh7.png). But it's not possible to fix for this zone because what OsmAnd suggests is allowed.

## 🌍 Your Environment

**OsmAnd Version:** OsmAnd 4.4.7, released: 2023-04-10

**Device and Android/iOS version:** Android 13

**Maps used (online or offline):** Belgium Wallonia, I think it's offline but I have access to live updates.

- [x] Offline maps offered within the OsmAnd app for download.

- [x] Online (tile / raster) maps 

**Anything else relevant?**

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#191m, Released: 2023-06-12
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/fbc631fd-7f33-41cb-bb39-82ad1a54c121"  width="300" height="auto"/> </th>
  </tr>
</table>  

@meyverick  Try the following:
1. Refresh OsmAnd
2. Refresh the maps
3. Reset profile settings
