### ISSUE TITLE
New My Places > Tracks screen shows the wrong number of selected tracks

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#17381]
Small bug as follows:

- Go to 'My Places > Tracks', tap the 3 dots menu top right on the screen, and tap 'Select' to receive this blue control:
![242511687-bdcd98ac-a539-4831-b52d-da1e9eed747e](https://github.com/osmandapp/OsmAnd/assets/845735/970eecae-0740-4309-acc2-1f06c506498b)
- Now tap on the checkbox in front of one of your track folders.
Instead of the number of tracks the selected folder contains (which are all selected now), the blue control just shows "1", i.e. it does not show the number of selected tracks, but folders.

- Now tap the 'Select all' toggle (I have marked in yellow above): The control now switches to show your correct number of tracks (not folders).

I suggest this behavior is buggy, the number should consistently indicate the number of selected tracks, never folders.

**Comment by dmpr0** [comment]
Hello! Thank you for the feedback. 
This is correct, it shows quantity of selected items, folder is one item. We need to change alert that show up after taping on Delete, to show quantity of tracks that will be deleted.

**Comment by sonora** [comment]
It's not only about deleting, but _any_ subsequent action, where the user should know how many tracks will be affected. Most prominently displaying on the map. Would perhaps be easiest to simply expand the numeric display in tbe control to "_x folders, y tracks_" ?

**Comment by Zirochkabila** [comment]
@sonora I think that the functionality works correctly - that is, it displays the number of selected items (including a folder as one item)
As for the extension of the numeric value, the folder information contains the number of tracks. So, I don't see the need to duplicate this information.


https://github.com/osmandapp/OsmAnd/assets/104760013/52dcc3ce-4526-4c05-bdbc-d12c4a989343

**Comment by vshcherb** [comment]
Same as in File manager it displayed number of selected items not searching all files inside.

**Comment by sonora** [comment]
Yeah, but see the third bullet point in my original post: After togglig the control a second time, we switch to showing the nunber if tracks. So it's inconsistent.

Since showing the number if tracks is the very pupose of the blue widget, showing the trrack number seems the correct thing to do here?

**Comment by Rowin63** [comment]
my places > tracks > 3 dots > select:
The initial count is always "1" though nothing is selected. Selecting some tracks then is always "+1"

After tapping "select all" and "deselect all" the counter goes to "0".  

V+4.5.3

![Screenshot_20230624_111209_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/95540936/cebdf89b-f5d5-428a-ab9b-6187dba6d5df)

**Comment by vshcherb** [comment]
Fixed now it's consistent number of items.

**Comment by sonora** [comment]
> Fixed now it's consistent number of items.

Well, "items" in this case is not very useful - it now shows the number of tickmarks, which is often folders.

But what really counts for the user to know is the number of **tracks** they are about to display?

Why not display that??

**Comment by vshcherb** [comment]
This is consistent with how File manager treats the items / selections.
You need to create another issue anyway cause this one is fixed.

You could probably suggest to display both items and tracks or for certain actions like delete display also number of tracks.
