### ISSUE TITLE
Road rendering glitch near two region border

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#17383]
## Description 
Road rendering glitch near North and South Holland region borders.
* Coordinates `52.281407, 4.697940`
* OSM https://www.openstreetmap.org/search?query=52.281407%2C%204.69794#map=15/52.2725/4.7042

**Maps:**
* North Holland, 01.06.2023
* South Holland, 01.06.2023

**App version:**
* iOS TestFlight: 4.4.10.13
* Android: OsmAnd~ 4.5.0#176m, released: 2023-06-07
<table style="width:100%">
  <tr>
    <th colspan=3>Android</th>
  </tr>
  <tr>
    <th>11</th>
    <th>12</th>
    <th>13</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/b539da1d-9c3a-439d-8aac-d78674bf7363"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/9949e09a-c1df-4117-bd98-4a36d5fe8871"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/91cb89df-969d-46e5-a192-5ae3f80a992f"  width="300" height="auto"/> </td>
  </tr>
</table>   

<table style="width:100%">
  <tr>
    <th colspan=3>iOS</th>
  </tr>
  <tr>
    <th>11</th>
    <th>12</th>
    <th>13</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/c3116275-fe29-4bf5-a9b5-3c7e389a8869"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/f5ba7696-b30f-46a9-bbe9-e7645db382de"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/fbea6a92-bf12-41d8-affb-63f57b145cdb"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by cepprice** [comment]
@vshcherb This happens in V1 too

**Comment by xmd5a2** [comment]
**Zoom 12 engine v1**
Zuid-Holland map only:
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/2e788f09-b6c7-498d-8138-94c6e6f6f715)
Noord-Holland and Zuid-Holland:
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/4300b898-e1b6-43fa-821f-f4da1b68c5cb)
Noord-Holland only:
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/4dcc4f1a-a1c6-496e-9f51-06c2567acf2c)
Zuid/Noord Holland poly boundaries (Zuid Holland selected (red)):
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/68288b86-0a7e-40b2-be7c-b5f4f9000b8e)

**Zoom 12 engine v2**
Noord-Holland and Zuid-Holland:
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/358f77fa-ef9b-4c7e-a3eb-9c7a6b1b8c0f)

Looks like issue is related to road merging
