### ISSUE TITLE
osmand does not use accented characters when displaying addresses

### ISSUE THREAD

**Issue by summoner001** [osmandapp/OsmAnd#17398]
### Description
osmand does not use accented characters when displaying addresses

### Steps to reproduce
search an adress for example Tolvajos tanya 178/A
as result: Tolvajos Tanya 178/A Orgovany (is correctly written as follows: Orgovány)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/11212632/799715ec-d9c9-42d4-aeed-48833485c7b3"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Actual result
accented characters is missing

### Expected result
(is correctly written as follows: Orgovány)

### Your Environment
OsmAnd Version: v4.5.1
Android/iOS version: android 9
Device model: Cubot Quest

**Comment by Zirochkabila** [comment]
I think it's all about the tags [OSM](https://www.openstreetmap.org/way/866654807#map=18/46.73421/19.46786)
How you can pay attention to the location of [OSM shown](https://www.openstreetmap.org/node/7183865273#map=19/46.75065/19.46536) - all characters are displayed


<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/9dc51b94-22b2-4e7d-97f3-db82e3eb489d"  width="300" height="auto"/> </th>
  </tr>
</table>  

Search results also show the required character "á"

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/bb1eab06-04b2-4a95-bfaf-8cfee2a4252e"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by summoner001** [comment]
It does not work for me :(

![Screenshot_20230611-122735](https://github.com/osmandapp/OsmAnd/assets/11212632/89dcdd7b-1bfe-4213-b4f7-61cc6adc6682)

**Comment by summoner001** [comment]
yes, that's fine by me, but in this particular case only addr:place=XX and here in Hungary it's quite common that there is no street name, just the name of the place

**Comment by Zirochkabila** [comment]
@summoner001 I checked again, and I think it's either your profile settings or the application's system settings.
Video shows that the symbol is supported

https://github.com/osmandapp/OsmAnd/assets/104760013/9c05af7b-457d-42f1-8861-a7fa40cdc515

**Comment by summoner001** [comment]
For me:
Map Language: default by device
OsmAnd display language: default by device

I do not know any other settings what I wrongly selected

but it is working for now on my device after kill osmand process and restarted the phone.

hmm interesting.

**Comment by summoner001** [comment]
Ahhw I found the problem. If I select the map language to hungarian and enable the 'use latin name is missing' option. In this case the accented characters is missing.

**Comment by summoner001** [comment]
The problem is the option: Latin name transcription.
When this enabled osmand use english alphabets.
