### ISSUE TITLE
Boat Routing ignores linear obstacles (weir) on rivers

### ISSUE THREAD

**Issue by Isolator70** [osmandapp/OsmAnd#17401]
# 🐞 routing report

### Routing engine

Offline original OsmAnd routing (never changed anything)

- [ X] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Boat routing

### Start and end points

Problem 1 (Tunnel problem):

Start: 50.48515/8.26796
Destination: 50.47748/8.26704

Problem 2 (Lock problem):

Start: 50.4707/8.2418
Destination: 50.46562/8.24025

### Actual and expected routes

Problem 1 (Tunnel problem):

Normally the routing should go through the "Weilburger Schiffstunnel" a tunnel for boats.
Instead OsmAnd routes over the dam/ barrage which is forbidden and impossible.

Problem 2 (Lock problem):

Normally boats has to go through the lock, but OsmAnd ingnores it and routes over the dam /barrage which is forbidden and impossible.

### Is this a regression?

Never needed before, but basically the app does it really as wrong as possible - this is unsuable.

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

</code></pre>

**Device and Android/iOS version:**
Huawei P10, OsmAnd 4.4.7

**Maps used (online or offline):**

- [ X] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/35434137/f8d606c4-fd78-42bc-b58e-3eb6d0b73c2d"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/35434137/e27f52a8-5caa-484e-b485-a449e5579e89"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
@Isolator70 Try to make a change to https://www.openstreetmap.org/way/304237579#map=18/50.48257/8.26603, namely to add the https://wiki.openstreetmap.org/wiki/Tag%3Ausage%3Dtransportation tag - I think this can be a problem

In the second case, you will most likely also need to change the map data

**Comment by Isolator70** [comment]
@Zirochkabila: Okay, I'll check the tunnel attributes first, thanks.

**Comment by Isolator70** [comment]
@Zirochkabila , I've set the transportation attributes, and corrected other issues at this location as well as at the lock before and after the "Schiffstunnel"

**Comment by Zirochkabila** [comment]
@Isolator70 I think you needed to add a tag to this link https://www.openstreetmap.org/relation/412921#map=17/50.48258/8.26695

**Comment by vshcherb** [comment]
We can treat ```waterway=weir``` similar to highway restriction ```no straight on```, so it won't go through. However it looks we need to add something special to process this situation.

**Comment by DmitryAlexei** [comment]
tested on OsmAnd~ 4.6.0#774m, released: 2023-09-18

> **Case 1** If weir line is crossing river line then there should be **waterway=weir** tag on their intersection. It needs to be fixed in OSM. OsmAnd doesn't support linear obstacles if they are just crossing waterway without proper tagging of intersection point. **Dev notes: Looks like this is more OsmAnd issue that OSM data.** But there was another problem with weirs, dams and waterfalls. It was fixed. If OSM data is fixed and OsmAnd version updated then routing work like this:  https://user-images.githubusercontent.com/5829014/258437980-042be063-0092-4a6d-a21a-97019f996bf3.png
>

Unfortunately without changing OSM data still works the same as in the original issue.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/8934e19e-7c78-4446-b049-cfc560e42ca4"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/0de06006-01fa-4848-b90a-630e29abafa6"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by ivanPyrohivskyi** [comment]
Tested on Android device Samsung Galaxy M21, Android 11.
Map [Germany_hessen_giessen_europe](https://download.osmand.net/download?standard=yes&file=Germany_hessen_giessen_europe_2.obf.zip) (regenerated 18.09.2023)

All changes will be available in new October maps.

<img width="400" src="https://github.com/osmandapp/OsmAnd/assets/1040293/fd7cb1cf-e0f8-42bb-9f46-e5cc6b04e2a9" /> <img width="400" src="https://github.com/osmandapp/OsmAnd/assets/1040293/e01c7d5e-1fc1-40d4-af16-7606394ec5da" />
<img width="400" src="https://github.com/osmandapp/OsmAnd/assets/1040293/af46ac36-a2c2-41cf-9f5c-78fd6b90dbe5" /> <img width="400" src="https://github.com/osmandapp/OsmAnd/assets/1040293/6a4324b1-4f0f-46b6-9a2f-289474ca9c74" />
<img width="400" src="https://github.com/osmandapp/OsmAnd/assets/1040293/7bcb050e-ccf4-4872-9f46-e2a1cc2d13c4" />

**Comment by vshcherb** [comment]
@xmd5a2 @yuriiurshuliak double check if the bug is fixed

**Comment by yuriiurshuliak** [comment]
As of now, both cases described in the issue are working correctly. The route is being laid as expected:

- Case 1 (Tunnel Problem): The navigation correctly routes through the "Weilburger Schiffstunnel"
- Case 2 (Lock Problem): The navigation directs boats through the lock, avoiding the dam/barrage as intended.

OsmAnd~ 5.0.0#3767m, released: 2024-11-20

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/7ea5808f-8ce8-48f8-96d7-c050b75408d1"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/e963eb1b-484a-4a3a-b24f-aad3faf93558"  width="300" height="auto"/> </th>
  </tr>
</table>
