### ISSUE TITLE
GPS posion lag when navigating gpx

### ISSUE THREAD

**Issue by TheRealHerisson** [osmandapp/OsmAnd#17407]
### Description
For the last couple of months our 3 phones have all shown a gps lag when navigating various gpx files. As we don't update the app that often I can't say which or if it was a particular release. The lag is always there and shows as a very slow moving position marker which then moves very quickly to catch up to current position then moves very slowly again. The lag lasts anything from about 3 to 10 seconds which is enough to frequently miss turns.

When this started I thought it might be my old 'satnav' phone Blackview BV7000 pro on Android 7 but it's happening our 2 Blackview BV's Android 10 phones too. 

No Osmand settings have been changed on any of the phones. 

### Steps to reproduce
It happens all the time.

### Your Environment
OsmAnd Version: 4.4.6  
Android/iOS version: 7 
Device model: Blackview BV7000 pro
OsmAnd Version: 4.4.7
Android/iOS version: 10
Device model: Blackview BV9900E

**Comment by mikehgentry** [comment]
Could be #16081 

(in short: try disabling 'animate own position', or possibly switching to OpenGL rendering)

**Comment by Zirochkabila** [comment]
Related to https://github.com/osmandapp/OsmAnd/issues/16081
