### ISSUE TITLE
OpenGL cuts off the name of the Római árok valley

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#17406]
### Description
OpenGL cuts off the name of the Római árok valley
[OSM](https://www.openstreetmap.org/way/337086635#map=19/47.41344/18.93531)

### Steps to reproduce

- Find this place `47.41383, 18.93542`

### Actual result
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/4003128a-03a6-4d13-9f1d-502b1ce7c108"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/2c9404c2-d0a6-4b71-9fd6-cd97ec33082d"  width="500" height="auto"/> </th>
  </tr>
</table>  

### Expected result

<table style="width:100%">
  <tr>
    <th>V1</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/83f72b6a-e9d5-4a35-a88c-e14eeca1c3f2"  width="300" height="auto"/> </th>
  </tr>
</table> 

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#191m, Released: 2023-06-12 / 4.4.10.3

**Comment by Zirochkabila** [comment]
I still have the behavior reproduced

**Comment by vshcherb** [comment]
For this situation is not critical
