### ISSUE TITLE
Footpath rendering problem

### ISSUE THREAD

**Issue by robinpaulson** [osmandapp/OsmAnd#17419]
This is wrong

<table style="width:100%">
  <tr>
<th><img src="https://i.imgur.com/ntQKkZK.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

This is correct

<table style="width:100%">
  <tr>
<th><img src="https://i.imgur.com/9LsaBZA.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

The only difference is zoom level 

MacAulay Street (Eden Terrace), Auckland
Location: geo:-36.86370,174.75733?z=18
https://osmand.net/map?pin=-36.86370,174.75733#18/-36.86370/174.75733  

Osmand 4.4.7, rendering engine v1, latest maps. Galaxy s5 mini, lineage 16

**Comment by zipav** [comment]
OsmAnd Nightly 4.5.0#226m, released: 2023-06-16

### Steps to reproduce: 
- Menu
- Settings 
- OsmAnd settings
- Map rendering engine: choose Version 1
- Go to coordinates: `-36.86370,  174.75733`
- Zoom to 50m scale and check result
- Zoom to 10 m scale and check result

![photo_2023-06-16_18-23-23](https://github.com/osmandapp/OsmAnd/assets/123936521/cf6afafb-f60b-41e7-a8f4-216d6cd827e9)
![photo_2023-06-16_18-23-41](https://github.com/osmandapp/OsmAnd/assets/123936521/2f3fd2e2-6260-4e6e-80fb-dc4777d2c3f3)

**Comment by vshcherb** [comment]
It looks like a map issue? Is it reproducing on map rendering engine v2?

**Comment by zipav** [comment]
@vshcherb There is no bug in Version 2, screenshots for comparison:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/626eea6c-ad9f-42ae-948b-e3049d9bf171"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/7983f43f-ae7f-4edc-bb2b-fc54a6811ef5"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
- v1 version is no longer supported.

**Comment by robinpaulson** [comment]
Well, I suppose ignoring bugs is easier than fixing them. I'm sure you could hugely simplify maintenance if you chose to not support other features.

**Comment by vshcherb** [comment]
Main rendering engine (v2) doesn't have that bug, so we need to consolidate in any case. iOS version doesn't have v1 at all. So many v1 bugs won't be fixed

**Comment by robinpaulson** [comment]
I and likely others would find it much easier to accept this sort of decision if you owned it directly rather than attempting to hide behind passive-aggressive language. So, rather than "v1 is not supported" and "many bugs won't be fixed", you could say "We made many mistakes writing v1 rendering engine; rather than fix them, we have decided to drop support for v1 and thus anyone using a phone older than x years."

**Comment by robinpaulson** [comment]
The point about ios is irrelevant in thud context

**Comment by scaidermern** [comment]
> * v1 version is no longer supported.

It would be a good idea to remove it from the settings then. Or show a big warning if v1 is selected. Otherwise this isn't obvious at all to the user.

**Comment by vshcherb** [comment]
>  We made many mistakes writing v1 rendering engine;

Which many mistakes did we make? 

Situation is specific some bugs probably still will be fixed in v1, v1 was main rendering engine for 10 years so if bug was not reported back then it's probably not critical.
