### ISSUE TITLE
Add point slider when editing gpx track

### ISSUE THREAD

**Issue by snooppr** [osmandapp/OsmAnd#17423]
And so OsmAnd can edit a gpx track, delete points, move, excellent.  But.

In practice, this works very limitedly, for example, when the user draws the track himself, he has few points.

Bluetooth gadgets, sports watches, sports social trackers write a track, which usually has several thousand, tens of thousands of points.

An example from the field.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/61022210/c44d5ccb-406f-4d3b-90f9-01f5370ca5b1"  width="300" height="auto"/> </th>
  </tr>
</table>  
`Track selection.gpx on the map - options - edit track - points.`
Sports tracker, from where I uploaded a workout to edit points.  As you can see, I cycled 200km and got 21K points.  Too much, I can't go to the very bottom and remove the endpoints (for example, I forgot to turn off the tracker in the last 10 minutes and would like to remove the endpoints from the end).  But scrolling by 100 points, the fingers will fall off, never rewind 21000 points).  I can't even get to the middle of the track.

It's not even that the bike track (perhaps 200km seems long).  long, no.  I was also on a hike, where the clock wrote the route to over Kilo points.

**Please add a slider to the right of the points, which will easily scroll through the entire track and move to any position, point in an instant, not forever.**

I usually edit the track via PC and this is not a problem, but OsmAnd seems to be the only one who can edit the track directly on Android, please improve this.

**Comment by snooppr** [comment]
Thanks it worked!  I never cease to be surprised by OsmAnd, a lot of workarounds that are not obvious to the user for solving the problem.

**Comment by snooppr** [comment]
https://github.com/osmandapp/OsmAnd/assets/61022210/ecc8cb78-38ef-4d39-afcc-e18723e6235a

**Comment by scaidermern** [comment]
> I selected a point and cut the track, but I don't know, I don't see what part of it disappeared, the point, until I pressed save and saw that it was gone, the finishing part of the track.

I think this is because your track shares the same blue color that is used by OsmAnd to highlight the track during editing. Try to assign a different color to your track. Does it work afterwards?
If so, OsmAnd should probably choose the track color during editing depending on the actual track color. Maybe by using the complementary color?

**Comment by snooppr** [comment]
Yes, I changed the color of the track and it works.  It seems that the blue track is the default track color, and the blue dotted line is what you need to delimit the colors.  Simply put, the user must be a geek at first glance in order to defeat the challenge.  Perhaps the effort expended will cost more than the goal.  It is necessary to simplify the editing of the track, that is, to make editing it obvious a pleasant pastime.  

@scaidermern Thanks for the help!
