### ISSUE TITLE
Can it be integrated into a free Android app and used in an offline environment?

### ISSUE THREAD

**Issue by FrancisFYK** [osmandapp/OsmAnd#17422]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

We will download offline map packages in environments with network access, and we are not sure if it is supported to achieve offline navigation when there is no network available.

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by TheSnoozer** [comment]
https://github.com/osmandapp/OsmAnd#functionality

All map data can be stored on your device's memory card for offline use. 


So yes, you can download all your maps from home, internet cafe or whatever place that offers you internet. Once you have the maps downloaded to your phone you can use them for navigation (=offline). You certainly could try the free version it should give you a good view of what the payed version offers with the limitation that the free version only allows you to download 7 or something maps (updates count as download).
