### ISSUE TITLE
Allow all roads with a speed limit of 30km/h or less to cyclists on both ways unless specified otherwise in France

### ISSUE THREAD

**Issue by foux** [osmandapp/OsmAnd#17426]
# 🚀 feature request

### Description

Contrary to what is said in #10462, in France, all roads with a speed limit of 30km/h or less is allowed to cyclist in both ways, unless specifically stated otherwise.

With the #10462, you checked the `source:maxspeed=FR:zone30`, but that's too restrictive, as we can see in the law ([here](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000045025523/) for those who understand french)
### Describe the solution you'd like

All roads with a 30km/h or less speed limit in France, without the tag `oneway:bicycle=yes` should be allowed on both ways to bicyles.

### Describe alternatives you've considered

Marking all 30km/h or less roads as `oneway:bicycle=no` on OSM, but that doesn't really makes sens

**Comment by le-jun** [comment]
too french; didn't read: Random french people, nitpicking at details.

@foux J'ai pas suivi l'évolution, il y avait une sombre histoire de cafouillage où la vitesse ne suffisait pas et qu'un pannonceau « Sauf vélo » (M9v2) était indispensable pour indiquer le double sens (Source : [Assemblée Nationale](https://www.cc37.org/pour-une-generalisation-du-double-sens-cyclable-en-zone-30-a-tours/)) – À défaut, un sens interdit s'appliquant à tous les modes de transport –, ça a changé depuis ?

**Comment by foux** [comment]
> too french; didn't read: Random french people, nitpicking at details.
> 
> @foux J'ai pas suivi l'évolution, il y avait une sombre histoire de cafouillage où la vitesse ne suffisait pas et qu'un pannonceau « Sauf vélo » (M9v2) était indispensable pour indiquer le double sens (Source : [Assemblée Nationale](https://www.cc37.org/pour-une-generalisation-du-double-sens-cyclable-en-zone-30-a-tours/)) – À défaut, un sens interdit s'appliquant à tous les modes de transport –, ça a changé depuis ?

@le-jun le texte de loi me semble assez clair : 
```
Lorsque la vitesse maximale autorisée est inférieure ou égale à 30 km/ h, les chaussées sont à double sens pour les conducteurs d'engins de déplacement personnel motorisés, de cyclomobiles légers et les cyclistes sauf décision contraire de l'autorité investie du pouvoir de police.
```

Donc c'est le contraire, c'est autorisé sauf si mentionné autrement ([source](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000045025523/))

**Comment by le-jun** [comment]
Je reformule, je vois trois situations en limitation à 30 :

* Panneau sens interdit B1 et sauf vélo M9v2 – Indispensable selon l'Assemblée Nationale : Double-sens cyclable ;
* B1 sans M9v2 mais avec arrêté municipal : Pas de double-sens ;
* B1 sans M9v2 ni arrêté : Situation floue.

À défaut de M9v2, avec ou sans arrêté, je – et l'Assemblée Nationale – considère qu'un tronçon n'est pas utilisable à double-sens de par la signalétique physique. C'est à la municipalité de se mettre en règle via l'ajout des pannonceaux ou d'un arrêté municipal.

**Comment by foux** [comment]
Mais "ce que dit l'assemblée nationale" n'a pas de sens en soit. Ce qui compte c'est le texte de loi. Donc non, le troisième point n'est pas flou, c'est juste autorisé, et la loi est plus que claire la dessus.

**Comment by AdrienJaguenet** [comment]
Bonjour, de ce que j'ai vu, l'obligation du pannonceau M9vx se trouve dans l'IISR, une norme à destination des opérateurs routiers (article 2 dudit), et donc sans effet sur l'interprétation que doivent faire les usagers du CDR et des panneaux. Or, comme le remarque @foux, le CDR est clair est net. Le flou existe quand à l'obligation de signaler l'existence d'un arrêté fermant le DSC.

**Comment by le-jun** [comment]
Ça roule pour moi alors, merci de l'éclairage !

**Comment by vshcherb** [comment]
Didn't understand much, needs to be investigated

**Comment by letypequividelespoubelles** [comment]
> Didn't understand much, needs to be investigated 

To summarize, when I opened [this ticket](https://github.com/osmandapp/OsmAnd/issues/10462), I thought that it was only road with `source:maxspeed=FR:zone30` that are bothway for cyclist, but I was mistaken*, and it's ALL way with speed limit below 30 km/h, unless there is a special signalisation, leading to a tag `oneway:bicycle=no` like the one in the picture : 
![no DSC](https://github.com/osmandapp/OsmAnd/assets/54240434/c7186755-0d17-4703-afe9-dd3fa6537187)


What were talking @foux , @le-jun  and @AdrienJaguenet is "Do we need a signalisation that allow cyclist in both direction", and finally the answer is no : [see french law for reference](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000045025523/).

**To conclude : all way with `maxspeed=30` or below, with `oneway=yes` and not `oneway:bicycle=yes` should be considered as with `oneway:bicycle=no`, and we finally don't care about the `source:maxspeed=FR:zone30` tag which is not relevant for this.**

*There is a law specific for zone30, but a more general law exists for all ways with maxspeed below 30km/h/

**Comment by letypequividelespoubelles** [comment]
Thanks @xmd5a2 but I'm currently not in France, maybe @foux or @AdrienJaguenet or @le-jun can test it ?

**Comment by scaidermern** [comment]
@xmd5a2 I'm not familiar with `rendering_types.xml` but I can't find any reference to France anymore in [your change](https://github.com/osmandapp/OsmAnd-resources/commit/20fe36ef84b569e9dddbfb4509e0001d0b28f735). Does this new rule really apply to France only?

**Comment by xmd5a2** [comment]
@scaidermern Fixed. Thanks for noticing.
