### ISSUE TITLE
Opengl: Way with fixme is not displayed in topo and offroad styles

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#17437]
### Description
Way with fixme is not displayed in topo and offroad styles.
https://www.openstreetmap.org/way/379694694

Maybe related with https://github.com/osmandapp/OsmAnd/issues/14784

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#226m, Дата выпуска: 2023-06-16
Android version: 13
Device model: poco f3

**Comment by xmd5a2** [comment]
Not reproducible.
Topo:
![Screenshot_2023-06-24_13-23-43](https://github.com/osmandapp/OsmAnd/assets/5829014/0fe65997-29f4-4356-84be-0dc8d449862f)

Offroad:
![Screenshot_2023-06-24_13-23-30](https://github.com/osmandapp/OsmAnd/assets/5829014/978da34a-c9b4-4982-96e8-0c8a0d33d463)

May be related to some OSM Live issue.

**Comment by Nine-Tailed** [comment]
Yes, the problem was related to the live update.
