### ISSUE TITLE
Track screen dualism - interconnect both screens

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#17434]
Despite extensive functionality overlap (see https://github.com/osmandapp/OsmAnd/issues/11336#issuecomment-1557348965), it seems we go with 2 separate track screens:
- (1) "My Placed > Tracks", focusing on track management, but also facilitating to display tracks or entire folders of tracks on the map, and configure track appearance.
- (2) "Configure map > Tracks", focusing on configuring track visibility and track appearance, but also offering track management functionality.

Users can get from the "management screen" (1) to the "visibility screen" (2), simply by tapping on "Visible Tracks". But reversely, if you went to the visibility screen (2) via the Configure map menu, we miss a way to advance to the management screen (1).

**Comment by Zirochkabila** [comment]
@sonora We need to agree with @dmpr0  whether we will do it

**Comment by vshcherb** [comment]
- You can click "Back" to get to previous screen. 
- "Show on map" present on both screens and should function the same theoretically, that's need to be changed

**Comment by sonora** [comment]
@vshcherb, @dmpr0 Yes, but regarding your first bullet: Tapping "Back" only does the trick if you already came from the "management screen".

If you came from the "Configure map" menu (like many users do who never discovered the second Tracks screen), there is currently no way to get to the Track management screen from there. (An issue we've always had, see e.g. https://github.com/osmandapp/OsmAnd/issues/11983#issuecomment-869502294. I had hoped we unify both screens to finally solve this, but if not, we should at least create the missing link between the 2 screens?)

**Comment by vshcherb** [comment]
I don't see an immediate issue to do something or to fix. So we can continue as a conversation.

I tested the screens and of course important actions are not ready such as Default Track Folder Apperance or Change Appearance for multiple tracks. Even Change Appearance in Configure Map is not obvious action so far.

But what's clear that these screens couldn't be the same.

Common:
- They represent same structure (folder / filter (in future) / track)
Less common:
- They have search functionality and navigate to single track action
Main purpose totally different:
- Screen with checkboxes - Configure Map
- Screen as File Navigator - My places

I think all screen will be different 1 about selection on the screen and another about management.

**Comment by vshcherb** [comment]
I don't think you should navigate from Configure Tracks Visibility to Track Management... that's weird
