### ISSUE TITLE
Positioning the screen on the track when it is selected

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#17435]
### Description
Sometimes osmand doesn't position the screen correctly when selecting a track.
See video:
https://t.me/ruosmand/126723

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#226m, Дата выпуска: 2023-06-16
Android version: 13
Device model: poco f3

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#226m, Released: 2023-06-16
Confirmed

**Comment by Nine-Tailed** [comment]
Today I met a similar problem with the navigation route. After calculating the route, osmand did not correctly position it on the screen, it turned out to be outside the screen.

**Comment by Zirochkabila** [comment]
@Nine-Tailed This may be related to each other
