### ISSUE TITLE
POI context menu jumps when opening a POI with the address displayed in two lines

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#17438]
### Description
POI context menu jumps when opening a POI with the address displayed in two lines

### Steps to reproduce

- Tap on this `50.43531° N, 30.43951° E` parking POI

### Actual result

https://github.com/osmandapp/OsmAnd/assets/104760013/17ddb3ab-72d8-4606-8777-d32576dc271c

### Expected result
The result is the same as when you click on "АТБ-маркет"

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#226m, Released: 2023-06-16
Android/iOS version: Android 12
Device model: Poco x3

**Comment by vshcherb** [comment]
We're missing smooth animation obviously but then it should be across whole application
