### ISSUE TITLE
Large distance and ambiguous attribution of seamark nameTags of light buoys beacons and towers, tweeking textDy

### ISSUE THREAD

**Issue by josail** [osmandapp/OsmAnd#17432]
### Description
large distance and ambiguous attribution of seamark nameTags of light buoys beacons and towers,
see also: https://github.com/osmandapp/OsmAnd/issues/17273#issuecomment-1577278163

### Steps to reproduce
use current nautical.render.xml
example: Harbours of Island Texel, Netherlands

### Actual result
seamark nameTags of light buoys, beacons and towers are displayed with large distance above the seamark buoys, beacons and tower icon symbols.

Problem 1: The correct attribution of the seamark name (nameTag) and its light characteristics (nameTag2) to the correct icon symbol and location is hardly possible and very confusing in many situations with a lot of seamarks like e.g. Harbours of Island Texel, Netherlands

Problem 2: The exact location of the seamark should be at the bottom of the symbol, but becomes very vague, if the text extend to far above the top of the symbol.

see attached Display 2
Issue nautical render nameTag far away and above seamark light buoys beacons towers.PNG
![Issue nautical render nameTag far away and above seamark light buoys beacons towers ](https://github.com/osmandapp/OsmAnd/assets/93162192/377030cc-29aa-4199-a66c-c5d4bba6970f)

### Expected result
seamark nameTags with light Characteristics closely placed below and thereby attributable to the seamark light buoy/beakon/tower symbol 

see https://github.com/osmandapp/OsmAnd-resources/pull/965
see there Display1 - Texel nautical render of light character details in nameTag2 displayed in brackets

The name and light Characteristics should be placed below the light buoy/beakon/tower symbol, where for buoys and beacons the bottom of the symbol should be placed at the exact location. If the symbol extends to the top, then the text sould better go close (!) and below (!) the symbol bottom, taking the exact location more to the center of symbol and nameTag. (If the nameTag is displayed above the symbol, it is far away from the exact location, and intuitively the exact location is not any longer expected at the bottom of the symbol)  

### Further Analysis
After the most recent update, the display of name tags in nautical.render.xml is quite different from the testing of the same before the update (compare Display1 and Display2).

Also the tweeking of textDy (https://github.com/osmandapp/OsmAnd-resources/commit/861847a32e19b2b22ec82fa6ebbe585236291244) did not solve this sufficiently. 

Even redoing the reverting the commit of the tweeking does not any more lead to the display, as in the testing of https://github.com/osmandapp/OsmAnd-resources/pull/965

I was not able by any stepwise positive or negative value for textDy to reproduce the Display1. 

I noticed, that now (June 2023) values of textDy=-16 and below, e.g. -30 now lead to nameTags above symbols (while before negative values would lead to lower positioning of name tags).

Only values of textDy=-13 and above lead to placing the nameTags below symbols (counter intuitive and different from before, e.g. May 2023). 

Values of textDy=-14 or textDy=-15 lead to nameTags beeing positions sometimes above, sometimes below the symbol, but always with larger distance to the symbol than before in Display1. It seems that there is some outomatic nameTag distance regulation applied. Before it was possible to place text on top of and partially overlapping the icon symbol. This seems impossible after the last update.

Thus, based on this analysis, the vertical text positioning must have changed somehow more generally during the most recent update. 

It could theoretically have to do with rendering engine version. However, my understanding is that my tests on iOS version and iphone8 allways use OpenGL rendering (i.e. not version1).

Strange? The display on the OsmAnd Map website looks ok and still very similar to Display1, but it is lacking all the light characteristics, so the nautical.rendering.xml used on the website is certainly from before the last June update. Likely this is also true for the rendering engine. So this is not the solution, but it highlights the experienced difference between before and after the June update of the OsmAnd App: 
https://osmand.net/map#15/53.0025/4.7728

Display 3: OsmAnd website map with outdated (before June update) rendering style and display
![No issue of nautical render nameTag in current OsmAnd website map display](https://github.com/osmandapp/OsmAnd/assets/93162192/d3d033e5-2f74-4793-8d4f-0ecadaa86713)

### Idea for solution
1. 
My best currently possible solution by stepwise adjusting negative values to textDy=-13 was acceptable, for certainly placing the nameTag below the symbol, but still with much more distance, in comparison to Display1. This would be a first step solution, for which I can offer as a first and certainly not perfect trial https://github.com/josail/OsmAnd-resources/commit/734def8f49a23ef801beeee4661af939f2cf2f78

2. 
It would be far more benifitial, to allow closer attribution and placement of icon symbol and nameTags, and this will require more professional analysis (more than I can do) of what has generally influenced the changed vertical nameTag positioning during the last update. A very close attribution and placement of nameTags below the symbol like initially achieved in Display1 should be the aim.

### Your Environment
OsmAnd Version: 4.4.9
iOS version: 
Device model: iphone8

**Comment by vshcherb** [comment]
Indeed it's a bug. Now we don't support textDy at all, we support 2 slots for text. 1 at the bottom another at the top. We will investigate and fix it or suggest, please let us now if it's custom rendering style or as I see nautical.render.xml

**Comment by josail** [comment]
it is nautical.render.xml,
but I tried modifing nautical.render.xml to solve the issue, still after quite some trying of all stepwidse textDy  values, without success. So all related to nautical.render.xml

let me know, when I can support with any testing of a solution you find, 

Jo

**Comment by vshcherb** [comment]
What I see 
```
<switch OSMMapperAssistantFixme="true" tag="fixme_tag" value="yes" nameTag="fixme" textColor="#ffffff" textHaloColor="#ccf800e0" textWrapWidth="20" textPlacement="top" textOrder="1">
				<case maxzoom="15" textSize="10"/>
				<case minzoom="16" textSize="11"/>
				<apply_if engine_v1="true">
					<case maxzoom="15" textDy="-33"/>
					<case minzoom="16" textDy="-50"/>
				</apply_if>
				<apply_if nightMode="true" textColor="#7f0a7e" textHaloColor="#ffdcff"/>
			</switch>
```
so removing textDy and using textPlacement="top" or textPlacement="bottom" should help

**Comment by josail** [comment]
ok, this command is new, at least to me

**Comment by cepprice** [comment]
1) I don't know, how text placement above seamark icons occured with nautical style from master branch
2) In current OpenGL implementation text placed right below icon. That's why if icon has big bottom padding (empty space), offset will be big too. So, icons should be updated

Red rectangle represents raw icon's bounds
| No padding | Big padding |
|-----|----|
| ![Screenshot_20230619_001107](https://github.com/osmandapp/OsmAnd/assets/31509211/e075eb19-8e1b-4efd-8c00-a142b9ef3480) | ![Screenshot_20230619_001112](https://github.com/osmandapp/OsmAnd/assets/31509211/049383ec-b770-443e-b715-5e70095d49fc) |

**Comment by vshcherb** [comment]
1. Needs to be fixed obviously (cc @xmd5a2 )
2. Probably padding could be reduced or controlled by textDy=-4 with negative values, so it will look closer

**Comment by cepprice** [comment]
@vshcherb textDy is no longer used in OpenGL. Area between red and green rects is added manually from font properties [here](https://github.com/osmandapp/OsmAnd-core/blob/master/src/Map/SymbolRasterizer_P.cpp#L210) and [here](https://github.com/osmandapp/OsmAnd-core/blob/master/src/Map/SymbolRasterizer_P.cpp#L213)

**Comment by xmd5a2** [comment]
Bridges  with `seamark:bridge:clearance_height` are also broken. `textDy` was used to center text on icon.

**Comment by quantenschaum** [comment]
Is it possible that the padding around the icons and the position of the origin of the icons is handled differently by render engines 1 and 2? Is this somehow related to #17413?

**Comment by josail** [comment]
Any news or ideas for solution on this issue on the vertical text positioning?

**Comment by josail** [comment]
This looks like restoring textDy in the OSMAND core has been found as the solution. Many thanks!

I think I can not easily test the result. 

Can someone who can do a test provide a screenshot of bridges with hight restriction and the nameTags at seamarks at the harbour of Texel? 

If these nameTag displays fit again, then the issue could be closed.
