### ISSUE TITLE
My Places > Tracks: Use conventional long-tap behavior

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#17433]
On the My Places > Tracks screen:
- Go to a screen where you have enough folders or tracks to fill more than your device screen (i.e. the list is scrollable).
- Scroll down a fair bit.
- Long-tap an item (can be a folder or a track).

The conventional behavior would be:
- (1) Of the checkboxes which now appear, the one for the long-tapped item becomes selected.
- (2) The selected, long-tapped item remains visible, i.e. the list does not shift.

Instead of (1), the item remains unselected, and regarding (2) even moves outside your screen's viewport, because the list gets repositioned to display its very top again (which serves no use case).

**Comment by Zirochkabila** [comment]
Related to https://github.com/osmandapp/OsmAnd-Issues/issues/125#issuecomment-1592815495

**Comment by vshcherb** [comment]
The feature not complete yet, should be fixed soon

**Comment by sonora** [comment]
Recent testing: It looks like a long-tap now selects the item ok, but still the list is scrolled to the top immediately afterwards.

**Comment by vshcherb** [comment]
Yes, I maid that comment on working PR, so it should be fixed soon
