### ISSUE TITLE
Mini basemap causes Flooding

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#17442]
### Description
In night builds from 17.06 there is flooding of territories when zooming.  Latest version without bug OsmAnd~ 4.5.0#231m, Release date: 2023-06-16
See video:
https://t.me/ruosmand/126837

**Comment by prallo** [comment]
Osmand Pro 4.5.2
Android 13
Samsung S23 Ultra

Same problem !
When I switch to rendering engine 1 it is gone !

**Comment by vshcherb** [comment]
Have same problem - issue is related to World basemap mini. If you delete it, it will be fine until restart

**Comment by vshcherb** [comment]
Most likely the reason https://github.com/osmandapp/OsmAnd-core/pull/576/files

**Comment by vshcherb** [comment]
Reverted so should be tested

**Comment by Nine-Tailed** [comment]
In the night build, removing the world mini map does not help, perhaps these are different bugs, since there were no problems on the previous build, and comparing the map files showed that they are the same.

**Comment by vshcherb** [comment]
Fixed / with latest (Tested) build
