### ISSUE TITLE
Search - Origin selector

### ISSUE THREAD

**Issue by Gizmot** [osmandapp/Osmand#1744]
Allow me to quote a review on Googleplay:

Anton Lodder August 20, 2015
"...Search especially a hot mess; there are many, many categories and if you pick the wrong one you won't find anything. It returns results close to where you are, not close to where you are looking on the map, ..."

I had the same issue when using osmand. The origin selector looks like a title and not a button or option to select. Took me quite a while to realize I could click on it.

1. On top, where Origin... is, I would replace that by "Search"
2. Below some short of crosshair icon with a textbox with white background
3. There is no way to know there is something next after favorite. Could had a small arrow pointing to the right to show there is an extra option

![screenshot_2015-09-24-21-41-28](https://cloud.githubusercontent.com/assets/13919997/10093744/ec89f688-6324-11e5-838b-b078fdf07eb8.png)

**Comment by vshcherb** [comment]
We plan to change the whole search next or one after release.

**Comment by utack** [comment]
@vshcherb sounds great, something more interactive like (sorry for saying it) Gmaps.
In the meantime setting origin to the map center by default should be quick and what most people expect it to be.

**Comment by vshcherb** [comment]
We already have working version in iOS, first draft will be exactly the same and yes in some sense it is google maps
