### ISSUE TITLE
Allow to use Offline Altitude correction based on 3D Geotiffs 

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#17458]
Allow to use Offline Altitude correction based on 3D Geotiffs

**Comment by vshcherb** [comment]
Add task to iOS version

**Comment by Zirochkabila** [comment]
- I suggest adding to the documentation that **Online** works only when **V1 rendering** is active https://docs.osmand.net/docs/technical/algorithms/calculate-uphill-slope/#altitude-srtm-correction

- Should the settings in **Configure map > 3D Relief** affect the display of **Calculate Offline** or **Calculate Online**?

- Should the settings in **Developer plugin > Heightmap** affect the display of **Calculate Offline** or **Calculate Online**?

- Should the absence of downloaded maps in the **Download maps** > **Terrain map** window affect the display of **Calculate Offline** or **Calculate Online**?

>None of the above in points 2-4 has any effect - it's not logical

**Comment by dmpr0** [comment]
* What to test?
* Where?
* How it should works?

**Comment by vshcherb** [comment]
https://docs.osmand.net/docs/user/map/track-context-menu#online-elevation-profile

Currently https://docs.osmand.net/docs/user/map/track-context-menu#online-elevation-profile (Elevation correction from Track context menu) should work offline and use terrain maps

**Comment by DmitryAlexei** [comment]
https://osmand.net/docs/user/map/track-context-menu/#calculate-offline

**Comment by vshcherb** [comment]
- Important feature not described clearly, deserve own item. Why do we combine it under 4th element? Altitude is very important part of the graphs
- Links should be present to this item from Navigation / Elevation widget in case user will start navigation with track without Altitude

**Comment by EugeneZmeuk** [comment]
## To Do

- [ ] competed the section of ["Calculate Elevation"](https://osmand.net/docs/user/map/track-context-menu/#calculate-elevation)
    * while only for Android
    * note: can calculate on our web server (online)
    * describe all steps how to calculate
    * note: read this [issue](https://github.com/osmandapp/OsmAnd/issues/18872)

**Comment by vshcherb** [comment]
- [ ] Too many screenshots and too much text. https://osmand.net/docs/user/map/track-context-menu/#calculate-elevation-offline  - 1-2 sentences is enough to explain 1-2 screenshots. Should be rewritten

**Comment by vshcherb** [comment]
- [ ] Still 4 screenshots in column (requested 2 in row)
- [ ] 3 item points describing same text as in first paragraph

**Comment by shurasmiling** [comment]
http://localhost:3000/docs/user/map/track-context-menu#calculate-elevation-offline
