### ISSUE TITLE
Open Place Reviews just died

### ISSUE THREAD

**Issue by 813gan** [osmandapp/OsmAnd#17451]
According to https://openplacereviews.org/ ([WA mirror](https://web.archive.org/web/20230619215116/https://openplacereviews.org/)) project died.
Probably some alternative should be found.

**Comment by 813gan** [comment]
Issues https://github.com/osmandapp/OsmAnd/issues/14621 https://github.com/osmandapp/OsmAnd/issues/15108 https://github.com/osmandapp/OsmAnd/issues/16091 are obsolete

**Comment by scaidermern** [comment]
Alternatives have already been discussed here: #11111.

**Comment by vshcherb** [comment]
Indeed Mangrove.reviews is most popular and here is an article about MapComplete https://www.openstreetmap.org/user/Pieter%20Vander%20Vennet/diary/400854
Merged to https://github.com/osmandapp/OsmAnd/issues/11111

**Comment by Coehill** [comment]
@vshcherb 
Can we re-open this?  The add photos button is still present on OsmAnd, despite relying on OpenPlaceReviews.
