### ISSUE TITLE
Route is built on the already passed part of the track

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#17456]
### Description
When navigating a track that has a common route to the start and finish - after recalculation, the route is built along the already passed part of the track
Reproduction is faster if setting the location simulation to **GPX x5**
[Невірний перерахунок.gpx.zip](https://github.com/osmandapp/OsmAnd/files/11798775/gpx.zip)
Probably related to https://github.com/osmandapp/OsmAnd/issues/17392 https://github.com/osmandapp/OsmAnd/issues/17305

### Steps to reproduce

- **Select GPX** > **Navigation** > **Point of start GPX**
- **Simulate location** > **Select track** > **Wait for the end of the trip (until the location is at the intersection)**

### Actual result

https://github.com/osmandapp/OsmAnd/assets/104760013/26dfb40e-cd95-40e1-926a-50b7ea40db70

### Expected result
The route is directed to the finish line

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#254m, Released: 2023-06-20
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#785m, released: 2023-09-20
Reproduced as in the video above:
- Select attached GPX for Navigation
- Set simulation speed *Fixed* > 66 km/h (to speed up reproduction)
**No need to *Simulate location by GPX***
- Wait almost until the end of the route

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/d26c7aa2-7303-420f-a058-ee4fa6a8e3b5"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/dbed537b-cda6-48e7-8354-940afb92e4a1"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/b443bbba-0179-4227-a3b2-c2be5d106e8d"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.7.0#1346m, released: 2024-01-10
**The issue was resolved.** 
Now, when navigating a track that has a common route to the start and finish, the route is no longer built along the already passed part of the track.

https://github.com/osmandapp/OsmAnd/assets/116079541/05d8fce2-55c1-48d2-a705-7049d9b63a38

**Comment by dmpr0** [comment]
Don't reproduce on iOS
