### ISSUE TITLE
Cycling route to Billstedter Hauptstraße 60, coming from odd-numbers side, uses one way street in the wrong way.

### ISSUE THREAD

**Issue by 7eggert** [osmandapp/OsmAnd#17454]
# 🐞 routing report

### Routing engine

- [X] OsmAnd's in-app offline routing

### Routing Profile

cycling, balanced, use elevation data, avoid unpaved roads / ferries / stairs

### Start and end points

Neu-Allermöhe
to
Billstedter Hauptstraße 60, Hamburg

(GPX track available)

### Actual and expected routes

Expected: Since I was driving on the road I'd just need to cross the street in front of the building. (There is a not-yet-mapped possibility to cross - IDK how this should be mapped if it's supposed to be done at all)

Actual: I was routed through Geesthang (road next to the main road) and expected to cycle through a one-way service road that's got no "Radfahrer frei" (I'm not allowed to use it in that direction).

### Is this a regression?

Unknown, probably not.

## 🌍 Your Environment

<pre><code>

Osmand~ 4.3.12 F-Droid

Android on Doogee X96Pro

</code></pre>

- [x] Offline maps offered within the OsmAnd app for download.

**Comment by scaidermern** [comment]
Is it this route?
https://osmand.net/map?start=53.538191%2C10.106338&end=53.538891%2C10.103563&mode=bicycle#17/53.53870/10.10432

If so, only the western part (https://www.openstreetmap.org/way/23340211) has a `oneway=yes` tag. The eastern part (https://www.openstreetmap.org/way/23340274) doesn't.

**Comment by 7eggert** [comment]
https://www.openstreetmap.org/way/23340211 is the forbidden way. I was on audio so I didn't see the map till I was in front of the building. Sorry. But to my defense: I was directed to turn right just when I arrived at the forbidden road. 

I'm quite sure now that it's a mapping problem, next time I'm there I might take a better look at how it should be mapped.
