### ISSUE TITLE
Search POI: airport 

### ISSUE THREAD

**Issue by Gizmot** [osmandapp/Osmand#1745]
Call this a professional deviation, but I sort of expect "airport" to be one of the main menu by default available.

Also, took me a while to realize that the search menu in POI is to search for other TYPES of POIs. My brain defaulted on thinking that the "Type to search all" would search stuff in the differents types of POIs on screen (Accommodation, Cafe and Restaurant, etc). My basic conclusion was that there is no Airport POI in osmand.

**Comment by sonora** [comment]
"Search" is work in progress ...  :-). 

For now you may find you get the best results if you just type a few letters for what you are looking for in the "Type to search all" text input field of the POI search screen. As you type, you will see that OsmAnd actually suggests if there are OSM categories matching what you are looking for (such as "Airport"), or you can always hit the "Search by name" option which will turn up all POIs containing what you typed in their names.

If you frequently look for / use categories not listed by default on the POI search screen, you can define a custom filter via the 3-dots menu button next the text input field.

Best, Hardy

**Comment by vshcherb** [comment]
Work in progress (search related)
