### ISSUE TITLE
Colour setting of water depth contour lines not respected

### ISSUE THREAD

**Issue by quantenschaum** [osmandapp/OsmAnd#17464]
### Description

Under map settings, nautical depths one can choose between several colouring schemes for contour lines. No matter what scheme I chose, the lines are always shown white.

It does work with render engine 2 (OpenGL), though.

### Steps to reproduce

- download depth data (preferably for NL)
- switch between styles in the settings mentioned above

### Actual result

Contour line remain white.

### Expected result

Contour line change colour.

### Your Environment
OsmAnd Version: 4.4.7  
Android version: 13  
Device model: Nokia X20

**Comment by yuriiurshuliak** [comment]
On **Version 1** of the rendering, the **colors do not change**, a stable white color of the contour lines is displayed.
On **Version 2 (OpenGl)** rendering, the **colors change** correctly and are displayed.
**OsmAnd~ 4.5.0#270m, released: 2023-06-21**

<table style="width:100%">
  </tr>
  <tr>
    <th>Version 2 (OpenGl)</th>
    <th>Version 1</th>
  </tr>
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/d2544fd0-9c85-4083-8dbc-ed9422ab53cc"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/9ea219e1-c2da-4524-b16c-ea8c4457382c"  width="300" height="auto"/>   </td>
  </tr>
</table>
