### ISSUE TITLE
I/O error: File not found – Live updates

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#17460]
## Description 

Log file: [logcat (3).log](https://github.com/osmandapp/OsmAnd/files/11799235/logcat.3.log)

Device : bluejay
Brand : google
Model : Pixel 6a
Product : bluejay_beta
Build : UPB2.230407.019
Version : 13
App Version : OsmAnd~
Apk Version : 4.5.0#253m 4500

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/169d1d7c-b852-4286-ae55-94fe26c08a90"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-tools/commit/db30e37fcb423e707081a3b1bfd4ae3574b9f071
