### ISSUE TITLE
Hillshading is pixelated instead of smooth

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#17469]
I'm not sure since when this issue persists but with OsmAnd 4.5.3 and rendering engine v2 hillshading isn't smooth anymore but pixelated.

Left: rendering engine v2, right: rendering engine v1
![photo_2023-06-21](https://github.com/osmandapp/OsmAnd/assets/1040784/890c1b04-90d7-4993-ae14-b0f0b7261962)

**Comment by scaidermern** [comment]
If the above screenshot isn't looking horrifying enough then maybe this one is:
![photo_2023-06-21](https://github.com/osmandapp/OsmAnd/assets/1040784/86246250-9bcd-4aa0-b266-b7088a24404e)

**Comment by vshcherb** [comment]
> This new setting is enabled by default. I wonder if this is a mistake. And I wonder why the result isn't smooth.

It's not a mistake cause we want to switch to geotiffs hillshade in order to have 1) smaller files that fits all features 2) all zooms availability without scale artifacts on 17-19 zoom

**Comment by scaidermern** [comment]
Well, currently it looks really awful. Isn't it possible then to get a similar look like before? This can't be the desired result, can it?

**Comment by Andrewschenko** [comment]
Have you tried to re-download the terrain map (heightmap)? Cleaning app's cache after that is needed.

**Comment by scaidermern** [comment]
> > Well, currently it looks really awful. Isn't it possible then to get a similar look like before? This can't be the desired result, can it?
> 
> Have you tried to re-download the terrain map (heightmap)? Cleaning app's cache after that is needed.

Redownloading helped, thanks! No cache cleaning was needed.
