### ISSUE TITLE
Inscription tags are erroneously treated as links

### ISSUE THREAD

**Issue by bdwz-osm** [osmandapp/OsmAnd#17466]
### Description
Adding a properly-formatted [`inscription=*`](https://wiki.openstreetmap.org/wiki/Key:inscription) tag with spaced line breaks (` / `) and paragraph breaks (` // `) causes OSMAnd to highlight the entire text and recognize it as a URL, even without any other elements of a web link present.

Note that the text of an inscription might actually contain a link, so completely disabling links for the value of `inscription` isn't a good solution.
### Steps to reproduce
- Tap on a map feature with an `inscription` tag, such as a [memorial](https://wiki.openstreetmap.org/wiki/Tag:historic%3Dmemorial), that contains line or paragraph breaks
- Observe the orange-highlighted text beneath ":information_source: Inscription"
- Tap it to open in browser and find that it's not a URL at all

### Actual result
Inscription text can be opened in browser as a non-functional URL
### Expected result
Non-URL text to remain unavailable for interaction
### Your Environment
OsmAnd Version: 4.3.12
Android/iOS version: Android v13
Device model: lol

**Comment by DmitryAlexei** [comment]
**Reproduced** OsmAnd~ 4.5.0#382m, released: 2023-07-12

48.7823370, 9.1824859
https://www.openstreetmap.org/node/5504782341
- inscription=* tag with spaced line (/) is recognized by OsmAnd as weblink
- clicking on such text opens a blank page in the browser
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/9c42b24b-c572-4ba4-9199-8768a6fe4ce1"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/b72b20b9-fe7e-4b95-8360-2f232e102517"  width="300" height="auto"/> </th>
  </tr>
</table>

@bdwz-osm Next time, please provide a link to the object and screenshots, this will speed up reproducing

**Comment by vshcherb** [comment]
[inscription](https://wiki.openstreetmap.org/wiki/Key:inscription) and other tags needs to be checked if they start with ``` http://``` or ```https://``
