### ISSUE TITLE
Navigation occasionally displays "1048 km" to next turn

### ISSUE THREAD

**Issue by oliver** [osmandapp/Osmand#1746]
While doing lots of cycle navigation with Osmand in the past weeks, I occasionally saw the navigation advice "1048 km to next turn". In fact the next turn was just a few meters or so away. Here's what was displayed:
![screenshot_2015-09-22-13-58-15](https://cloud.githubusercontent.com/assets/2344/10118194/285b5086-6473-11e5-9f19-ce59855880bf.png)
(this screenshot was made in Dalby, Sweden).

The wrong advice disappeared normally when reaching the turn.

IIRC the voice navigation was still correct in these cases and said something of 100 meters to next turn.

This issue occurred maybe two or three times, in different places. I could not reproduce this issue when playing around with the simulation mode in Osmand.

This happened with OsmAnd~ 2.1.1 from F-Droid under Android 4.4.2, using bike navigation with the offline map of Sweden from 2015-09-03.

**Comment by vrtareg** [comment]
I have noticed that occasionally too even all my settings are set to miles/yards ...

**Comment by vshcherb** [comment]
Fixed
