### ISSUE TITLE
Default motorway speed at Belarus was changed from 110 to 120 km/h

### ISSUE THREAD

**Issue by Prusaker** [osmandapp/OsmAnd#17468]
Dear colleagus.

Since October 2022 default motorway speed at Belarus was changed from 110 to 120 km/h.
(https://pravo.by/document/?guid=12551&p0=P32200145&p1=1)
According to this could you please change rendering_types.xml?
(The tag BY:motorway is present in two places in the file).

Thanks in advance

**Comment by Zirochkabila** [comment]
@xmd5a2  needs an assessment

**Comment by xmd5a2** [comment]
Fixed. New maps required.
