### ISSUE TITLE
10.1 GPS signal lost is wrongly pronounced in hu (non-TTS) voice navigation

### ISSUE THREAD

**Issue by d4f5409d** [osmandapp/OsmAnd#17478]
### Description
The voice is pronouncing "GPeace" where it should be "GPS".

I recommend switching the input to "Dzsí pí esz" instead of "GPS" so it would pronounce it correctly for sure.

### Steps to reproduce
Check it in developer mode or via navigation

### Actual result
GPeace

### Expected result
GPS

### Your Environment
OsmAnd Version: 4.4.7
Android/iOS version: 13.1
Device model: OnePlus 8

**Comment by sonora** [comment]
The explicit text provided in these vocabulary lines is used by TTS. And I have checked that both the TTS voices for `hu` and `hu-formal` use "_dzsípíesz_". So if that works ok, it should not be touched.

Non-TTS simply plays the rigid wave file provided, in this case https://github.com/osmandapp/OsmAnd-resources/blob/master/voice/hu/voice/location_lost.ogg. You can try if https://github.com/osmandapp/OsmAnd-resources/blob/master/voice/hu-formal/voice/location_lost.ogg works better, and if fits in the `hu` voice by pitch and intonation, we could use that.

If not, we would need a new `location_lost.ogg` file, potentially need to record or regenerate the entire voice.  In general I advise against putting too much effort into maintaining recorded voices. their feature set is comparatively limited, and for common languages such as Hungarian I would think you can find a TTS engine which does a much better job.
