### ISSUE TITLE
After selecting one folder in my places>tracks ALL my tracks are going to be displayed! 

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#17473]
### Description
In "my places>tracks" I selected one folder containing around 40 short tracks. After tapping "display on map" Osmand gets very busy.
After having a look into "configure map>tracks" I can see, that ALL of my stored tracks (up to 1500!) are going to be displayed. Leading osmand to crash again and again.

It´s hard to deselect all tracks to get osmand running again... (repeating tracks>hide all>apply as long as...)

### Steps to reproduce
select a folder in "my places >tracks"
tap "display on map"

go to configure map>tracks >3dot menu: 1500 (all my tracks) are going to be displayed!

Tried it three times, happened three times.

### Your Environment
OsmAnd Version: +4.5.3 and 4.5.0#274
Android/iOS version: 13
Device model: S20+

**Comment by sonora** [comment]
Must be a new regression - 4.5.2 still behaves ok from what I see.

**Comment by Rowin63** [comment]
Yes, 4.5.2 did not do this. But both new releases do so...

**Comment by Rowin63** [comment]
I´m hardly waiting on a reliable running version...

**Comment by scaidermern** [comment]
Strange, can't reproduce this one with OsmAnd 4.5.3. But no reason to be sad, I found enough other bugs in the new my tracks screen!

**Comment by scaidermern** [comment]
Oh wait, I can. It is just a little different from what I expected.

Steps:
* Go to My Places / Tracks
* Enter a folder (for example called "A"),  open the three buttons menu on the top right, choose select, select a *subfolder* (for example called "B"), go to the same three buttons menu again, choose select on map
* instead of the tracks from folder A / B, OsmAnd shows all tracks from folder A and all tracks from any subfolder of it

**Comment by scaidermern** [comment]
> I am beginning to wonder what we truly gained other than all these bugs - if we should not simply go back to the old (and fast!) fold-out Tracks screen we had until 4.4... 😉😘😉

Well, apart from the amount of features, isn't it also the amount of bugs that make OsmAnd stand out from similar apps? 😉

**Comment by sonora** [comment]
How boring would my evenings be in the desert or on a mountain without finding 2 or 3 new bugs every night... 😉😉😉
