### ISSUE TITLE
Too many "Beneluxbaan" street names

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#17470]
### Description
Too many "Beneluxbaan" street names
Clear overflow of names is visible at **16x and higher zooms**

### Steps to reproduce
Go to this place `52.298846675464496, 4.868072261138867`

### Actual result

<table style="width:100%">
  <tr>
    <th>OsmAnd~ 4.5.0#269m, Released: 2023-06-21</th>
    <th>4.4.10.7 </th>
    <th>V1</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/9a31195e-7b9c-49cc-9b92-0e592c380376"  width="200" height="auto"/> </th>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/df4f729f-1312-4dc3-af12-3104843e5321"  width="500" height="auto"/> </th>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/2f8bcd7c-09e1-4bf3-87fc-624bd18cef29"  width="300" height="auto"/> </th>
  </tr>
</table> 

### Expected result
Fewer street names should be displayed. For example, as shown in **V1**

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#269m, Released: 2023-06-21 / 4.4.10.7

**Comment by DmitryAlexei** [comment]
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/111066a8-e703-4197-b77a-f09169ad046a"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/09c718d0-3866-47b3-b35f-9c64aba8dcd5"  width="300" height="auto"/> </th>
  </tr>
</table>
