### ISSUE TITLE
My Places > Search > allow to open selection mode for search results

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#17472]
Use cases: I have tracks which belong to a certain region, a certain project, a certain expedition etc. In addition to some of these dimensions  being organized in folders (we need a "Select all" button per folder, see https://github.com/osmandapp/OsmAnd/issues/17103), some of these dimensions are coded into the track names. So we certainly also need a "Select all" button on the Track search screen to be able to display in one go all tracks fitting a search.

This button existed until recently, I had even coded it to display the number of tracks it would affect.

**Comment by Zirochkabila** [comment]
4.5.3 = nightly

<table style="width:100%">
  <tr>
    <th>OsmAnd~ 4.5.0#269m, Released: 2023-06-21</th>
    <th>4.5.2</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/dd96f5d6-3a87-4507-81e8-573e07ededbc"  width="300" height="auto"/> </th>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/4c94a01e-1db1-4992-8df4-23f67c765a0b"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
Search shouldn't have long tap and selection mode - that was not planned

**Comment by vshcherb** [comment]
To do: it should work as in file manager, selection should be working and select filtered elements

**Comment by sonora** [comment]
Yes, I think it must be possible to select several entries, no matter if the entries are **unfiltered**, or **search hits** (i.e. filtered by some criteria). "_it should work as in file manager_" ... everything else would be highly unusual... :wink:

In practice, the search on itemized tabs is nothing but a **filter** - that's why it is a complication to think of "Search" as a separate screen, when it really is just a filter on a (nested) list (see https://github.com/osmandapp/OsmAnd/issues/6702#issuecomment-1612517804#9 ).
