### ISSUE TITLE
My Places > Tracks: Sorting order gets lost

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#17475]
OsmAnd 4.5.3

Steps to reproduce:
* Go to My Places / Tracks
* Set sorting order to Name: A - Z
* Select any track to open it
* Return to My Places / Tracks
* Sorting order got reset to Last Modified

☹️

**Comment by zipav** [comment]
OsmAnd 4.5.3, released: 2023-06-20
OsmAnd Nightly 4.5.0#284m, released: 2023-06-23

### Steps to reproduce
- Menu 
- My Places
- Tracks
- Sort: Name A - Z
- Open on map any track
- Arrow back 
- Check the result

https://github.com/osmandapp/OsmAnd/assets/123936521/f79bf6fa-1b4f-4173-98e2-38eeff985070

https://github.com/osmandapp/OsmAnd/assets/123936521/57448652-b7a3-4617-8e8f-8fe86eb63133

**Comment by scaidermern** [comment]
Another way to reproduce this:
* Go to My Places / Tracks / Visible on the map
* Change something, hit apply
* Sorting order at My Places is reset to Last modified

**Comment by yuriiurshuliak** [comment]
We were unable to reproduce the bug you mentioned, after selecting the sort and opening the track, the sort remains the one we selected.
We tested the two methods you mentioned. Please try the latest nightly version or beta version.

OsmAnd~ 4.5.0#313m, released: 2023-06-29
OsmAnd 4.5.3, released: 2023-06-20



<table style="width:100%">
  </tr>
  <tr>
    <th>Reproducing on Beta</th>
    <th>Reproducing on Nightly</th>
    <th>Reproducing the alternate path of the bug, Nightly version</th>
  </tr>
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/75f684c3-489b-4d06-b52a-e6b77ac7a1e4"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/23525d57-77b0-4129-b491-ab70e9c0dc32"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/d2f7409f-682d-4115-87ad-dd2f1cc1c700"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by scaidermern** [comment]
> Another way to reproduce this:
> 
>     * Go to My Places / Tracks / Visible on map
> 
>     * Change something, hit apply
> 
>     * Sorting order at My Places is reset to Last modified

Still reproducible with the new version 4.5.4.

Please reopen.

**Comment by sonora** [comment]
I think it's a new regression, had meanwhile been fixed. Likely one of the things which would be complete non- issues if we followed this idea: #17538.

**Comment by DmitryAlexei** [comment]
Cannot reproduce with different combinations of tracks and sorting options in both folders (entire tracks folder and visible on map folder)

**Comment by yuriiurshuliak** [comment]
I reproduced this bug in different variations:
- all tracks
- tracks inside the folder "shown on the map"
- tracks inside other folders

Everything was done according to the user's instructions, unfortunately, the reproduction of this bug was unsuccessful.
Please confirm if this issue is reproduced in the latest nightly version? 
It would also help us in further investigation if you could provide your logcat files.

<table style="width:100%">
  </tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/87fa7016-47d1-4bc2-84c2-f83c5d3dde4f"  width="300" height="auto"/>   </td>
    </td>
  </tr>
</table>

OsmAnd~ 4.5.0#351m, released: 2023-07-06

**Comment by scaidermern** [comment]
> Please confirm if this issue is reproduced in the latest nightly version?

I can't reproduce it with nightly 4.5.0#351m. Looks like it has finally been fixed.

**Comment by scaidermern** [comment]
Nope, it hasn't. But maybe I found the difference between your and my tries to reproduce this.

This does *not* reproduce it:
* Sorting order (of the top directory) set to A-Z
* Currently recording track is set to visible
* A track that is located in the top directory (where sorting order is set to A-Z) is made visible (or invisible)
* Sorting order (of the top directory) remains A-Z

This *does* reproduce it:
* Sorting order set to A-Z
* Currently recording track is set to visible
* A track that is located in a sub directory (where sorting order is set to Last modified) is made visible (or invisible)
* Sorting order (of the top directory) gets set to Last modified

So it looks like the sorting order of the directory of the track that is changed is copied to the top level directory?

**Comment by yuriiurshuliak** [comment]
After following your updated instructions on the new nightly version, we made an attempt to replicate the error, but were unsuccessful in reproducing the problem.

OsmAnd~ 4.5.0#367m, released: 2023-07-10

https://github.com/osmandapp/OsmAnd/assets/127092082/ec848670-ffef-49ba-9414-1b6764e40d7a

**Comment by scaidermern** [comment]
@yuriiurshuliak That's not quite what I wrote. What you are missing is the part "A track that is located in a sub directory (where sorting order is set to Last modified) is made visible (or invisible)".

You are opening a track sub directory ("Rec") that is set to Last modified. But you aren't changing the visibility of any of the tracks that are located in this directory.

So please try to change the visibility of one track inside the "Rec" directory. Then check if the sorting order of the top level directory is still set to "A-Z"

**Comment by yuriiurshuliak** [comment]
I tried to reproduce the bug with your comments. Sorting has been enabled as you requested. First, variable actions were performed in the first folder, then in the second folder. No result was achieved. Please, attach a video, of how you reproduce it step by step from your side.

OsmAnd~ 4.5.0#373m, released: 2023-07-11


https://github.com/osmandapp/OsmAnd/assets/127092082/08c0c497-3491-4f64-9640-30a5f8f80a78

**Comment by scaidermern** [comment]
> Please, attach a video, of how you reproduce it step by step from your side.

I already did that here: https://github.com/osmandapp/OsmAnd/issues/17475#issuecomment-1622977126

This works in both version 4.5.3 and the nightly 4.5.0#351m. I have no idea which other conditions have to be met. Maybe a developer should take a closer look at the corresponding code to check which actions can lead to a change of the sorting order. Can't be too hard.

**Comment by Rowin63** [comment]
On every crash sorting is set back to "last edited". And I don't even get and never had all my 50 folders set to "A-Z", because just scrolling the folders and doing this setting one by one crashes Osmand and I'm back to "last edited".

**Comment by Rowin63** [comment]
I just did the update to +4.5.8 and all track folders are set to "last edited" again.

**Comment by scaidermern** [comment]
> I just did the update to +4.5.8 and by this all track folders are set back to "last edited".

Same for me with version 4.5.7. All previous sorting order settings lost, all back to last edited.

But it looks like my original bug is finally resolved. The sorting order is no longer reset when changing the track visibility.

**Comment by scaidermern** [comment]
> So I went (via "configure map / tracks) through 52 folders and set them once again to "A-Z".
> But in the "my places / tracks" the sorting still remains "last edited"...

Can confirm. Looks like both have a separate configuration. Worth a separate ticket I guess.

**Comment by Rowin63** [comment]
Creating new folders, their sorting is "last edited". So this seems to be the standard setting (personal opinion, I would prefere A-Z as standard).
But also editing an existing folder changes it's sorting back to "last edited".
At least, now it's the same in both menus :-)

**Comment by sonora** [comment]
See https://github.com/osmandapp/OsmAnd/issues/17886, I think that would save a lot of headache, and make everyday usage a lot easier (at least for me).

**Comment by scaidermern** [comment]
Implementing #17467 and having a default sorting order would also help a lot.

**Comment by scaidermern** [comment]
From time to time the sorting order still gets reset to last modified. No idea how to reproduce yet. OsmAnd 4.5.10.

**Comment by sonora** [comment]
Same for me. Perhaps this commit https://github.com/osmandapp/OsmAnd/commit/c856ce8e3917da66849da48fbd23d9f61f4945f2 caused it when updating to the corresponding app version. Then it should have been a one-time effect - let's watch.

**Comment by scaidermern** [comment]
It definitely happened after upgrading. But it also happened again afterwards, at least two times. I guess it has something to do with moving of tracks or something similar.

**Comment by Rowin63** [comment]
> 

Also here. Happens everynow and then, back to "last edited". Can't reproduce it.

**Comment by scaidermern** [comment]
Found out how to reproduce it, pretty easy: Change the visibility of the currently recording track (no active recording required):
https://github.com/osmandapp/OsmAnd/assets/1040784/9d692b20-fb7d-4792-bacf-9925f646fb9f

OsmAnd 4.5.10. 

Please reopen.

**Comment by vshcherb** [comment]
Issue needs to be new open - 4.5 is closed

**Comment by scaidermern** [comment]
#17955
