### ISSUE TITLE
Usability: navigation route display obscures road details

### ISSUE THREAD

**Issue by oliver** [osmandapp/Osmand#1747]
When using navigation mode, the pink route completely covers the actual map data, making it very hard to determine the actual road details. Eg. I'd like to see if it's a yellow or a white road that is taken by the navigator, so that I can decide whether to go for a smaller/quieter road instead of the main road.

Would it be possible to use a dashed line for the navigation route instead?

**Comment by xmd5a2** [comment]
Added more opacity to route line. Try latest night build.
![clipboard01](https://cloud.githubusercontent.com/assets/5829014/10131123/a62e899c-65d6-11e5-974c-8e7495eca288.jpg)
