### ISSUE TITLE
Weather / Development plugins don't allow to reset settings to default

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#17471]
Some configurable plugins have a button "Reset plugin settings to default" (track recording plugin, a/v notes plugin, accessibility plugin). Other configurable plugins don't have such an option (weather plugin, OsmAnd development plugin).

Please add such an action to all configurable plugins. Otherwise it is not possible to get back to the default settings without loosing all settings.

**Comment by DmitryAlexei** [comment]
Better here https://docs.osmand.net/docs/user/plugins/#plugin-settings
or here https://docs.osmand.net/docs/user/plugins/development https://docs.osmand.net/docs/user/plugins/weather

**Comment by DmitryAlexei** [comment]
See comment https://github.com/osmandapp/OsmAnd-Issues/issues/2017#issuecomment-1698611888

**Comment by DmitryAlexei** [comment]
Screenshots changed and added description https://docs.osmand.net/docs/user/plugins/#plugin-settings
