### ISSUE TITLE
U-Turn not possible

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#17488]
# 🐞 routing report

### Routing engine

- [ x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Car

### Start and end points

It´s exactly at `48.26640, 16.36455`

### Actual and expected routes

At this point U-turn is not possible

### Is this a regression?

I dont know.
This bug does not happen online at Open Street Maps and not at Osmands online map. 
Both cases give a correct routing to the next possible legal turning point.
## 🌍 Your Environment
Android S20+
**OsmAnd Version:**
+4.5.3
<pre><code>

</code></pre>

**Device and Android/iOS version:**
S20+ Android 13
**Maps used (online or offline):**

- [ x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**
![U-Turn nicht möglich](https://github.com/osmandapp/OsmAnd/assets/95540936/4f1d708f-0d2b-403a-a864-007712a4068c)

**Comment by yuriiurshuliak** [comment]
We couldn't replicate the incorrect turn you mentioned using the provided coordinates. We have verified that the navigation on OpenStreetMap and our app is accurate for that specific road segment. Here's a link to OpenStreetMap with your segment: https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=48.2610%2C16.3682%3B48.2650%2C16.3658#map=16/48.2730/16.3624



OsmAnd~ 4.5.0#382m, released: 2023-07-12

<table style="width:100%">
  </tr>
  <tr>
    <th>OsmAnd</th>
    <th>OpenStreetMap</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/f06dc738-659d-4188-8423-7108161481b1"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/c666db22-19b9-46c8-ba22-1ac94fd82260"  width="700" height="auto"/> </th>
<td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/91e365e5-2b7f-4689-a997-b727fede6f20"  width="500" height="auto"/>   </td>
  </tr>
</table>

**Comment by Rowin63** [comment]
Yes, that's the correct way to go. But you can see on my screenshot, how Osmand did the routing. I don't know 🤔

**Comment by vshcherb** [comment]
Not reproduced right now probalby related to osmand live - let's see further.

**Comment by Rowin63** [comment]
I can't reproduce it either. Seems to be gone 😉
