### ISSUE TITLE
URL field is duplicated in Context Menu

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#17485]
## Description
Object on OSM [Khikhani Fortress](https://www.openstreetmap.org/way/547497894#map=19/41.54140/42.56534)
iOS issue https://github.com/osmandapp/OsmAnd-iOS/issues/2776

### How to reproduce
* Open **OsmAnd** – **Menu** - **Maps & Resources** – **Asia** – **Georgia**
* Download **Standard** map
* Open **Search** - **Address** – **Coordinates search**
* Search `41.54137° N, 42.56541° E`
* Select **Khikhani Fortress** on the map, tap **Details**

## Expected result
* URL field will be shown as one item

## Actual result
* URL field is shown as two items

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/07b7736d-12c3-4792-810f-4dc2a53a2d90"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
Fix looks incorrect it should be reverted and backend fixed

**Comment by Dima-1** [comment]
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/31807095/a700d2d5-e3c6-4160-b8f1-76c6887f4bb9"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#718m, released: 2023-09-02
No more duplicated URL fields. 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/40e25db2-d6f1-4383-ae77-5b3ddb55e61f"  width="300" height="auto"/> </td>
  </tr>
</table>
