### ISSUE TITLE
day/night switch only happens when GPS fix is available

### ISSUE THREAD

**Issue by oliver** [osmandapp/Osmand#1748]
When opening Osmand in the morning (hours after sunrise), it usually still shows the dark "night mode" map which I used in the last night. It does not instantly switch to day mode; rather, I have to enable GPS on the phone and wait for GPS position to be found and then scroll around on the map, until the map switches to the bright "day mode" rendering.

I have configured Osmand to use sunrise/sunset to determine the map display mode.
It would be nice if the map switches to the correct day/night theme as soon as Osmand is started.

This happens with OsmAnd~ 2.1.1 from F-Droid under Android 4.4.2.

**Comment by vshcherb** [comment]
Known limitation and seems to be reasonble.

**Comment by sonora** [comment]
If you are talking about the automatic sunrise/sunset switch: The location information o where you are is of course essential for that first, as it exactly depends on that ... :-)

**Comment by oliver** [comment]
You are right, I hadn't thought of that :-) it just was weird to open Osmand in the morning (when I hadn't really moved during the night - but of course Osmand couldn't know that without GPS) and still seeing the dark map.
I will instead try the brightness sensor now.
