### ISSUE TITLE
Left Panel too short after changing route

### ISSUE THREAD

**Issue by pordini** [osmandapp/OsmAnd#17489]
### Description
The left panel becomes too short to display all the information after changing the route, like adding an intermediate destination.
Minimizing and reopening Osmand will repair the panel, as will starting to drive / walk / etc. 

### Steps to reproduce

- Set a destination
- Add an intermediate destination 
- Start simulation navigation
- Wait for recalculation

### Actual result
The left panel is mangled.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/12774050/de679c87-58f7-4867-944c-4d9684465366"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
Full panel
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/12774050/6a4a2ef9-2660-40af-a6de-a5a6fe44e320"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Your Environment
OsmAnd Version: OsmAnd+ 4.5.3, released: 2023-06-20
Android/iOS version: Android 13, Graphene
Device model: Pixel 5

**Comment by yuriiurshuliak** [comment]
This bug has not been fully reproduced, but there are delays with the widgets on the left side for several seconds. Please try to use the latest beta and nightly versions, and check again the real conditions in the city where the satellites are caught.
OsmAnd~ 4.5.0#313m, released: 2023-06-29
OsmAnd 4.5.3, released: 2023-06-20


<table style="width:100%">
  </tr>
  <tr>
    <th>Beta version</th>
    <th>Nightly version</th>
  </tr>
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/15b9c42b-03ff-436e-9ed0-e5b2a397d93f"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/65cf8fde-e4a7-40fa-b3a4-4c5133207e1c"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by pordini** [comment]
For me, this issue happens everywhere, every time I change an existing route.


https://github.com/osmandapp/OsmAnd/assets/12774050/d7835d54-a7f9-4c86-9540-46929605be51

I will see if I can install a nightly on my backup phone. I don't want to install it on my main navigation device at the moment.

**Comment by pordini** [comment]
It stays like that as long as you do not move. 
When you start driving, the widgets are drawn. But when I stay still, they stay like this.

**Comment by DmitryAlexei** [comment]
@pordini 
Please try the latest nightly build

Later I've got result #1. As of now #2

<table style="width:100%">
  <tr>
    <th>#1</th>
    <th>#2</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/33bb0824-29e6-4b6b-a66c-c85f0b457a1c"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/f24807a2-dc3f-403f-9e82-765048fc4f5d"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by pordini** [comment]
With OsmAnd+ 4.5.4, released: 2023-07-04 the widgets are restored almost instantly.

https://github.com/osmandapp/OsmAnd/assets/12774050/3a0ee4d8-b0c6-4a66-aade-405f8edf8342

I think it's very similar to OsmAnd Nightly 4.5.0#381m, released: 2023-07-12

https://github.com/osmandapp/OsmAnd/assets/12774050/6df0fc15-035d-4317-bbba-c07aefb40de8

**Comment by vshcherb** [comment]
Consider that original issue is fixed
