### ISSUE TITLE
Turn Left instruction when going straight

### ISSUE THREAD

**Issue by pordini** [osmandapp/OsmAnd#17483]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Car

### Start and end points

Grunwaldzka, Przemyśl, Poland. 49.78636 22.76384

### Actual and expected routes
There is no left turn in the route, it should not be showing as such. (Screenshots added for clarity).

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

Unknown

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

OsmAnd+ 4.5.3, released: 2023-06-20
</code></pre>

**Device and Android/iOS version:**
Pixel 5, Android 13, Graphene

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/12774050/71744699-f979-46c2-8b97-def26d14bdc2"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/12774050/a27ffc13-f194-466b-8031-3921fb7b3633"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by zipav** [comment]
OsmAnd 4.5.3, released: 2023-06-20
OsmAnd Nightly 4.5.0#284m, released: 2023-06-23

### Steps to reproduce
- Navigation button
- Choose start and end points: `49.78607  22.76607` and `49.78636  22.76384`
- Details
- Scroll down to Turn-by-turn
- Check instructions
- Start Simulate navigation
- Check the result

On Nightly version:
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/7d88c518-ea79-48a7-bfb4-eda7962d0b25"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/a5d9bef5-f5d5-4a82-8311-a39ea49b2741"  width="300" height="auto"/> </th>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/787599c0-2d81-45e9-9911-c2a84ccb0d8d"  width="300" height="auto"/> </th>

On Beta-version:
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/40b64663-5e18-44f1-b4d8-8229075bb88b"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/3b49edcd-b6f4-435c-8a99-203b98ee9fc3"  width="300" height="auto"/> </th>

**Comment by d4f5409d** [comment]
I experienced something similar on a bycicle route. It told me to turn slightly right but the route was straight.

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.5.0#367m, released: 2023-07-10

Start point 49.786387 22.764331
End point 49.785995 22.761006
This route on the [OsmAnd map](https://osmand.net/map?start=49.786387%2C22.764331&end=49.785995%2C22.761006&mode=car#18/49.78615/22.76354)
Screenshots from the app:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/2e632544-1edf-4444-81ab-9f7af7f0c47a"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/b272fa0e-5f52-4e03-bc74-e62673663416"  width="300" height="auto"/> </th>
  </tr>
</table>
