### ISSUE TITLE
OpenStreetMap fields old_name, alt_name etc. are not considered when looking for cities, while they are when serching for roads

### ISSUE THREAD

**Issue by Max1234-Ita** [osmandapp/OsmAnd#17486]
### Description
I know of some locations in Italy which have either old_name or alt_name keys mapped in OSM.
e.g.:

Voghera (map: Italy-Lombardy):
Piazza Francesco Meardi: https://www.openstreetmap.org/way/910629447
Tags: place=square; name=Piazza Francesco Meardi; **alt_name=Piazza Rossella**; **old_name=Piazza Rossella**

Lungavilla (map: Italy-Lombardy): https://www.openstreetmap.org/node/62515300
Tags: place=village; name=Lungavilla; **old_name=Calcababbio**

Pizzo (map: Italy-Calabria): https://www.openstreetmap.org/node/67276014
Tags: place=village; name=Pizzo; **alt_name=Pizzo Calabro**

I noticed that in OsmAnd, if I search for alt_names/old_names of a street, they appear in the search results, however the search is not successful if the old/alt_name belongs to a city or village, i.e.:

- Search for Voghera, Piazza Rossella: Successful (returned "Piazza Francesco Meardi"; would be better if it was "Piazza Francesco Meardi (Piazza Rossella)", but it's OK)

- Search for "Calcababbio": Unsuccessful. A place named Calcababbio actually exists in the same map, but it's about 12Km away, I would expect to see "Lungavilla" listed among the results.

- Search for ""Pizzo Calabro": Unsuccessful. A lot of results appear, but "Pizzo (village)" is not in the list.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/15315381/670bdf6a-94b1-491c-b031-fad3c99b8275"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/15315381/7a957cf7-c07f-44f6-bdb0-96833fedc07a"  width="300" height="auto"/> </th>
  </tr>
</table>  

![image](https://github.com/osmandapp/OsmAnd/assets/15315381/477d042f-0122-4275-81dc-a800056132ca)

### Steps to reproduce

1. Have at least Italy-Lombardy and Italy-Calabria maps installed in OsmAnd
2. Open the Search tool and enter: "Voghera piazza rossella"; Observe that the result is listed and corresponds to the wanted location (see the OSM URLs in Description)
3. Search for "Calcababbio"; Observe that a match is present but if you show it on the map, it corresponds to a different location (correct behaviour); "Lungavilla (village)" should be present in the list (the wanted place)
4. Search for "Pizzo Calabro";  Observe that many matches are present after expanding the search radius (I have all the Italy maps installed in my device), unfortunately "Pizzo (village)" is not among them

### Actual result
Searching for old_name or alt_name of locations returns a result only if the old/alt_name belongs to a street or square; place=village, place=city etc. seems to be disregarded

### Expected result
Search for old_name or alt_name should return results also for place_city, place=village etc.

### Your Environment
OsmAnd Version: OsmAnd Plus v. 4.5.3 (Beta)
Android/iOS version: Android 11
Device model: Samsung Galaxy A50 (SM-A505 FN)

**Comment by vshcherb** [comment]
As you see 2nd line displays old_name (https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=113138320&class=highway) also old_name  / alt_name should searchable cities
![telegram-cloud-photo-size-4-5834589127906016521-y](https://github.com/osmandapp/OsmAnd/assets/1042025/5d336fb6-01e1-4037-b8c9-764a39837bae)

**Comment by Max1234-Ita** [comment]
> As you see 2nd line displays old_name ([nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=113138320&class=highway](https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=113138320&class=highway)) also old_name / alt_name should searchable and visible for cities ![telegram-cloud-photo-size-4-5834589127906016521-y](https://user-images.githubusercontent.com/1042025/250104621-5d336fb6-01e1-4037-b8c9-764a39837bae.jpg)


I don't read very well Cyrillic alphabet, but I guess this i a search for a street which has _old_name_ set (and actually works).
The issue comes up when a *village* is searched with its old_name: it looks it isn't showing up iun the search results.

**Comment by DmitryAlexei** [comment]
The tag **old_name** for cities is available to search in Cyrillic, but not available to search in Latin languages. 
See Grodno (https://www.openstreetmap.org/relation/130921)
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/14fba5e0-19cb-4ba3-abac-eb94010ef648"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/10289e53-2cbb-4eaf-82fc-916d262da45d"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
To do: support old_name:* in search, probably it's not part of the map and only map update is needed.

**Comment by ivanPyrohivskyi** [comment]
Problem new maps in August 2023.

Use Italy Lombardy map for test.
Test cases:
https://www.openstreetmap.org/node/62515300 Lungavilla / Calcababbio
https://www.openstreetmap.org/node/62515810 Verrua Po / Verrua Siccomario
https://www.openstreetmap.org/node/517735981 Villapia / Tiracoda

**Comment by Max1234-Ita** [comment]
Just tried with OsmAnd v.4.5.5 Beta, it looks it works.
I tried searching just for "Siccomario", however, and in effect several villages with that word in their name/old_name are found ( _Verrua Po - Verrua Siccomario_ is among them). Unfortunately they are at random places in a very long list:

![image](https://github.com/osmandapp/OsmAnd/assets/15315381/ab466ef0-9f76-45b2-ac0b-a562c2795e69)

I think matches coresponding to inhabited locations (cities, towns, villages, etc) should be listed first, before all the other match types (roads, bridges, tunnels and amenities such as bus stops, etc.)... but I guess this is a different issue :-)

Thank you so much!

**Comment by DmitryAlexei** [comment]
> Problem will fix in new maps August 2023.
> 
> Use Italy Lombardy map for test. Test cases: https://www.openstreetmap.org/node/62515300 Lungavilla / Calcababbio https://www.openstreetmap.org/node/62515810 Verrua Po / Verrua Siccomario https://www.openstreetmap.org/node/517735981 Villapia / Tiracoda

1. Test cases almost ok. For Verrua Po village in the second line there is no information about *old_name*

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/935a2b80-2289-450d-a4b5-921b03a0cdb1"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/10c94736-60e8-41e3-a6b2-c0f34ef6c5c0"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/2a7bf1ae-2fa7-4575-9f07-2d2a519caef4"  width="300" height="auto"/> </td>
  </tr>
</table>

2. Search do not support old_name:de 
https://www.openstreetmap.org/relation/130921

<table style="width:100%">
  <tr>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/93e7e8cd-4bbb-413c-b03b-5cd61bcd3371"  width="300" height="auto"/> </td>
  </tr>
</table>

3. Wrong search and map data for diacritic signs
In Poland, Lodz region when you search for Adolfów, which is old_name for Zdziechów-Kolonia (https://www.openstreetmap.org/node/3009772106), you get information about Czaplinek (https://www.openstreetmap.org/node/31880927), that do not have *old_name* tag and  

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/4b6b2277-68e5-4833-8944-718d5c50249e"  width="300" height="auto"/> </th>

**Comment by Neuwessi11** [comment]
I am not completely sure if it is the same thing, but if I search for „Düsseldorf Hotel Nikko“ there is not shown the Hotel Nikko (what is now Clayton Hotel, but I added the old_name tonight) in the search list. It only appears a wikipedia article tagged at the building next door.
But when tapping at the Clayton Hotel you can see in the details of this hotel the old name, so I would guess OsmAnd can read the old names, but OsmAnd cannot reliably search for old names.
Or can be the problem that „Hotel Nikko“ is only in the Live Updates, but not in the normal maps?

**Comment by Max1234-Ita** [comment]
> I am not completely sure if it is the same thing, but if I search for „Düsseldorf Hotel Nikko“ there is not shown the Hotel Nikko (what is now Clayton Hotel, but I added the old_name tonight) in the search list. It only appears a wikipedia article tagged at the building next door. But when tapping at the Clayton Hotel you can see in the details of this hotel the old name, so I would guess OsmAnd can read the old names, but OsmAnd cannot reliably search for old names. Or can be the problem that „Hotel Nikko“ is only in the Live Updates, but not in the normal maps?


The live updates are included included in the cartography and subsequently deleted after the monthly packages have been built, as they are just temporary modifications to the map;

Perhaps the hotel tags have been changed recently?
Try checking the same item after next monthly update: if so, you should find it in the regular map too (otherwise, I guess it's a bug).

**Comment by Neuwessi11** [comment]
Yes, I recently added the old_name-tag. But you said, OsmAnd should work with the live updates, and it does, because when tapping on the hotel, the old name is shown. Only the search function doesn't find the old name.
But I will try again after the next monthly update.
Until then, you can form your own opinion. It is this hotel: https://www.openstreetmap.org/node/3176636861

**Comment by Neuwessi11** [comment]
It's the same with the December maps, so it seems to be a bug.
Maybe this issue should be re-opened?

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#1135m, released: 2023-12-01
@Neuwessi11 cannot confirm
- fresh nightly build
- fresh maps (from December)
- search for Nikko

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/a5227aa6-bc53-4697-aa4e-51055a560bbf"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
OsmAnd TestFlight 4.7.2.11
New functionality successfully added to the iOS version of the app. Old_name=* tag tested on [this](https://www.openstreetmap.org/node/4726658599) POI (see screenshots), alt_name=* tested on [this](https://www.openstreetmap.org/node/10824078498) and [this](https://www.openstreetmap.org/node/1340656195) POI and [this](https://www.openstreetmap.org/relation/130921) city, all worked.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/1d198dbd-78c5-4e24-a4b9-50500cac492d"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/7a6a4223-3cec-4ac2-a911-fb1c7fe7a7d4"  width="300" height="auto"/> </td>
  </tr>
</table>
