### ISSUE TITLE
building:part value isn't rendering

### ISSUE THREAD

**Issue by 5EOTlGWT** [osmandapp/OsmAnd#17495]
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/102209029/4b47b687-eecc-407f-9409-790cc000f366"  width="300" height="auto"/> </th>
  </tr>
</table>  

Building with a single contour
building=yes
And two inner contours
building:part=retail
building:part=apartments

According to the wiki, the designation seems to be correct.
The purpose of the individual parts of these buildings is not visualized.

**Comment by xmd5a2** [comment]
Fixed. New maps and OsmAnd required. "Colored buildings" option is needed.

**Comment by 5EOTlGWT** [comment]
Спасибо ВАМ !!
О Великий !!!

**Comment by 5EOTlGWT** [comment]
Не работает.
В последней ночнушке тоже...

**Comment by DmitryAlexei** [comment]
@5EOTlGWT 
New maps  required, wait till early August
