### ISSUE TITLE
"Customize route line" doesn't show surface detail for navigation on saved track

### ISSUE THREAD

**Issue by bananu7** [osmandapp/OsmAnd#17493]
### Description
The "customize route line" available in Pro plan is very useful for me, especially the surface option showing paved/unpaved terrain. I've noticed, however, that it only shows up for me when doing dynamic routing, and not following an existing track.

It works perfectly fine for Altitude and Slope, but breaks for "Road type", "Surface" (the first one, i.e. road/footpath), Smoothness, "Winter road", and "Surface composition".

### Steps to reproduce
Open navigation with the "follow track" option on e.g. some existing GPX file. Set "customize route line" to "Surface".

### Actual result
The route is displayed in a default color.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/2399997/987db3eb-7e3d-4dfa-8895-ed108f73786c"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
The planned route shows, following the preloaded track, the colour according to the surface. 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/2399997/093704cf-00a6-4ddf-9443-a2ce88354d34"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Your Environment
OsmAnd Version: 4.4.7
Android/iOS version: 12
Device model: OnePlus 7

**Comment by bananu7** [comment]
I've just realized that the Pro version also has the option to customize the appearance of the displayed track. I found that it allows similar settings to the navigation screen, _however_ that screen nicely shows grayed out options, and mentions that "the track is missing the respective data" which is much nicer UX.

I'm assuming that's why it's not showing on the navigation screen. It's a bit confusing to the new user, since I have no idea why it's not up there. Similar issue occurs (arguably worse) when a different map type is chosen - then the options dissapear completely. I think it would be better to show them grayed out with an info as to why they can't be chosen on that particular map.

Incidentally, it feels kinda silly that I can pull up surface data for a _dynamically_ routed track, but not for a fixed one? Is it because that track is based on raw GPS points and OsmAnd isn't smart enough that it actually follows the roads it has in the base?

**Comment by Velomeloman** [comment]
#16484

**Comment by scaidermern** [comment]
> Is it because that track is based on raw GPS points and OsmAnd isn't smart enough that it actually follows the roads it has in the base?

Yes. You need to snap the track to the road first. Otherwise OsmAnd has no data about which roads belong to this track.

**Comment by DmitryAlexei** [comment]
Our guide to using the *Attach to the roads* function:
https://osmand.net/docs/user/navigation/setup/gpx-navigation#attach-to-roads
