### ISSUE TITLE
OSMAnd doesn't recognize is_in:*** tag and it doesn't display corresponding results

### ISSUE THREAD

**Issue by d4f5409d** [osmandapp/OsmAnd#17494]
### Description
Since OSMAnd doesn't care about is_in tags, we can't search for a place which is common in the country like 
ABC-Place, Town1

When we type ABC-Place it throws me all of the results nearby (Town2, Town3 and Town4), but I only need ABC-Place in Town1, which has a ```is_in:town=Town1``` tag.

### Steps to reproduce
Told it already

### Actual result
It gives no results if Town1 is given after the ABC-Place.

### Expected result
ABC-Place, Town1 should give the the correct result or at least via searching in Town1's contents like how the streets appear.

### Your Environment
OsmAnd Version: 4.4.7
Android/iOS version: 13.1
Device model: OnePlus 8

**Comment by scaidermern** [comment]
The `is_in` tag should no longer be used. Use boundary relations instead.

**Comment by goldfndr** [comment]
#6497 is possibly related
