### ISSUE TITLE
Route from Uis to Kamanjab 3.8 times longer than expected, avoids C35.

### ISSUE THREAD

**Issue by HughTaylor** [osmandapp/OsmAnd#17502]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Default routing preference with "Car" or "Motorcycle" (bug is not present when bicycle is selected)

### Start and end points

Start point: Uis, Namibia
End point: Kamanjab, Namibia

https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=-21.2023%2C14.8508%3B-19.6399%2C14.8464

### Actual and expected routes

Expected route: Straight up the C35
![expected](https://github.com/osmandapp/OsmAnd/assets/70054665/eec0bb6b-d5a5-4e4d-b49a-2e6ad1651a4b)

Actual route: Avoids C35
![actual](https://github.com/osmandapp/OsmAnd/assets/70054665/be5f258b-d265-4fb3-8570-eb5fa06d8bb2)

### Is this a regression?

Unknown, behaviour is different to openstreetmap.org

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

4.3.12
</code></pre>

**Device and Android/iOS version:**
ONEPLUS A6003
lineage_enchilada-userdebug 13 TQ2A.230505.002

**Maps used (online or offline):**

- [ x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**

**Comment by zipav** [comment]
OsmAnd Nightly 4.5.0#399m, released: 2023-07-14
### Coordinates: 
Start point `-21.2023, 14.8508` 
Finish point `-19.6399, 14.8464`


In OsmAnd Nightly the route is built in the same way as the user's.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/908b412b-ff73-4f9d-a8cd-bdd2cea3c11e"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/e8f5f2be-d328-410c-93ab-5b754dc46370"  width="300" height="auto"/> </th>
  </tr>
</table>



In OsmAnd Web version results are the same:

1) for bicycle: https://test.osmand.net/map?start=-21.202300,14.850800&end=-19.634830,14.847340&type=osmand&profile=bicycle#9/-20.4463/15.6638

2) for car: https://test.osmand.net/map?start=-21.202300,14.850800&end=-19.634830,14.847340&type=osmand&profile=car#8/-21.302/15.743

**Comment by xmd5a2** [comment]
OsmAnd tries to avoid `surface=gravel`. Whole road from Uis to Kamanjab is mapped in OSM as gravel road. It tries to reach asphalt as fast as possible. It builds a direct route when `Prefer unpaved` option is activated. I don't see any bugs at OsmAnd side.
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/99822557-400b-4fb0-b2df-a2eb3ab5d19f)

**Comment by vshcherb** [comment]
Probably gravel too much deprioritized, so it should be prioritized by a factor of 2-3 but not 6?

**Comment by xmd5a2** [comment]
I don't think that gravel should be less deprioritized because usually gravel looks like this:

![](https://mir-s3-cdn-cf.behance.net/project_modules/1400/619c10123353307.60ece0c21d2df.jpg)

![](https://3.bp.blogspot.com/-ZI9wjFl6u9w/Ub5oHq0JgMI/AAAAAAAAVXo/EcNeDeC8mkk/s1600/3GR+Solo+6-13+019.JPG)

Such roads in practice have speed limit 40-50 km/h. Increasing priority of such surface will most likely lead to unwanted off-road exits in Europe.

**Comment by xmd5a2** [comment]
Priority for gravel was increased
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/57e28345-a8e5-475a-b4d3-3d02c52ad473)

Hope this will not break anything else.

**Comment by scaidermern** [comment]
> I don't think that gravel should be less deprioritized because usually gravel looks like this:
> 
> ![](https://camo.githubusercontent.com/1679c55189c2e501ef4095cf4415c183058c33947a7220c5ea35211cf418403a/68747470733a2f2f6d69722d73332d63646e2d63662e626568616e63652e6e65742f70726f6a6563745f6d6f64756c65732f313430302f3631396331303132333335333330372e363065636530633231643264662e6a7067)
> 
> ![](https://camo.githubusercontent.com/31085f5567f90cffc7e5628480c703f7ca706bb9ad5b016ba5310796dec9305a/68747470733a2f2f332e62702e626c6f6773706f742e636f6d2f2d5a4939776a466c367539772f5562356f4871304a674d492f414141414141414156586f2f45634e65446543386d6b6b2f73313630302f3347522b536f6c6f2b362d31332b3031392e4a5047)
> 

This is compacted or maybe fine_gravel but not gravel.

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#718m, released: 2023-09-02
Car routing improved on the map  (https://test.osmand.net/map/?start=-21.202300,14.850800&end=-19.634830,14.847340&type=osmand&profile=car#8/-21.302/15.743) and in the app
- but we still have noticeable differences with [ORSM routing](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=-21.2023%2C14.8508%3B-19.6399%2C14.8464#map=9/-20.4232/14.9428) (see pictures for comparison):

 <table style="width:100%">
  <tr>
    <th>OsmAnd routing</th>
    <th>Details</th>
    <th>OSRM routing</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/6c38ad2d-4cce-413b-ae39-c44ed0d97d07"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/46a81272-2ba1-4307-85c8-32d89879322d"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/642d8e92-00a3-4235-8009-7168b98a77d4"  
width="300" height="auto"/> </td>
  </tr>
</table>

- OsmAnd routing chooses **highway=secondary with surface=unpaved** (https://www.openstreetmap.org/way/23893365 and https://www.openstreetmap.org/way/23925926) for **53 km** and **highway=primary with surface=asphalt** for **72 km** (https://www.openstreetmap.org/way/668788065) over **highway=primary with surface=gravel** (https://www.openstreetmap.org/way/424569992) for **about 75 km**.

**Comment by vshcherb** [comment]
Still question remains about
https://test.osmand.net/map/?start=-20.165544,15.070496&end=-19.718232,14.839783&type=osmand&profile=car#11/-19.8462/15.0444 - 60km - 1:00
and 

https://test.osmand.net/map/?start=-20.165544,15.070496&end=-19.667160,14.865189&type=osmand&profile=car#11/-19.8462/15.0444 - 130 km - 2:13

Here is the problem it doesn't use primay road which probably is important than surface cause secondary road (https://www.openstreetmap.org/way/23925926.203125#map=13/-20.1120/15.1468) is probably worse. 
Also the time difference doesn't indicate the good routing result it's 100% (1 h difference)

**Comment by xmd5a2** [comment]
If I increase gravel priority to [0.45](https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#L947) then route from this issue is calculated correctly BUT another route breaks:
https://test.osmand.net/map/?start=56.584226%2C41.224727&end=56.589506%2C41.217795&type=osmand&profile=car#16/56.5860/41.2203
**gravel=0.45:**
`Route <route>: routing_time=498,8, vehicle=car, base=false, start_lat=56,58417, start_lon=41,22456, target_lat=56,58943, target_lon=41,21784, complete_distance=1760,9, complete_time=181,1, native=true`
![image](https://github.com/osmandapp/OsmAnd/assets/5829014/b3fb0d17-7f42-467b-936d-02c0ac36294a)

**gravel=0.3:**
`Route <route>: routing_time=606,4, vehicle=car, base=false, start_lat=56,58417, start_lon=41,22456, target_lat=56,58943, target_lon=41,21784, complete_distance=967,4, complete_time=116,9, native=true`![image](https://github.com/osmandapp/OsmAnd/assets/5829014/03d8e336-40ca-4474-9619-2191e5b13b6f)

**Comment by xmd5a2** [comment]
If I decrease `surface=unpaved` priority to **0.35** then final part of route is correct:
![Screenshot_2023-10-03_10-04-05](https://github.com/osmandapp/OsmAnd/assets/5829014/36e7c7dc-c3d2-4e98-be4b-401099b27577)

**unpaved = 0.4:**
![Screenshot_2023-10-03_10-04-22](https://github.com/osmandapp/OsmAnd/assets/5829014/f4a7c430-a588-4189-94c7-ed4b9c09fade)

BUT if I move start point a little bit to south then route is totally wrong:
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/2473b15c-3e45-4d23-afdc-3cd905913af7)

**Comment by Dima-1** [comment]
https://test.osmand.net/map/?start=-20.130081,15.086754&finish=-19.620659,14.843452&type=osmand&profile=car#10/-19.9604/15.1680

  | length (m) | max speed (km/h) | priority | effective speed (m/s) | cost (s) | total(s)
-- | -- | -- | -- | -- | -- | --
primary gravel (c35) | 67942 | 65 | 0.3 | 5.42 | 12543.14 | 12617.02
primary asphalt (c35) | 1334 | 65 | 1 | 18.06 | 73.88 |  
secondary unpaved (D3226) + (D2666) | 53438 | 60 | 0.7 | 11.67 | 4580.40 | 8562.89
primary asphalt (c40) | 71906 | 65 | 1 | 18.06 | 3982.49 |

**Comment by Dima-1** [comment]
For all case maxspeed the same as before, primary = 65 secondary = 60. With priority specified in the table route switches at the corresponding point
 <table style="width:100%">
  <tr>
    <th colspan="2">OSRM routing</th>
    <th>Osmand Priority</th>
  </tr>
  <tr>
    <td valign="top"><img src="https://github.com/osmandapp/OsmAnd/assets/31807095/abb89281-dd9f-4ca2-9754-1096f7d093bb"  width="300" height="auto"/> </td>
    <td valign="top"><img src="https://github.com/osmandapp/OsmAnd/assets/31807095/6047d764-ebe1-4ee4-9ae5-01a89adaba59"  width="400" height="auto"/> </td>
    <td valign="top"> gravel=50
      <br>unpaved=50 </td>
  </tr>
  <tr>
    <th colspan="2">GraphHopper routing</th>
    <th>Osmand Priority</th>
  </tr>
  <tr>
    <td valign="top"><img src="https://github.com/osmandapp//OsmAnd/assets/31807095/b3610724-2521-42d7-9e94-fdef2e1f1880"  width="300" height="auto"/> </td>
    <td valign="top"><img src="https://github.com/osmandapp/OsmAnd/assets/31807095/636d2d44-89f9-43ed-a4d5-44ff0ad924dc"  width="400" height="auto"/> </td>
    <td valign="top"> gravel=50
      <br>unpaved=45 </td>
  </tr>
  <tr>
    <th colspan="2">Valhalla routing</th>
    <th>Osmand Priority</th>
  </tr>
   <tr>
    <td valign="top"><img src="https://github.com/osmandapp/OsmAnd/assets/31807095/7943f2b8-37e7-43c4-9646-942dd9341f13"  width="300" height="auto"/> </td>
    <td valign="top"><img src="https://github.com/osmandapp/OsmAnd/assets/31807095/cad96ab6-5ed0-4231-b36b-aaa26555a74f"  width="400" height="auto"/> </td>
    <td valign="top"> gravel=38
      <br>unpaved=30 </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
gravel=50 ? primary ? 
Example
```
primary gravel = 65 * 0.76 = 50
secondary unpaved = 60 * 0.83 = 50
```

```
primary gravel = 65 * 0.58 = 38
secondary unpaved = 60 * 0.5 = 30
```

**Comment by vshcherb** [comment]
Looks like we can keep gravel=0.5 and unpaved=0.5 (
![image](https://github.com/osmandapp/OsmAnd/assets/1042025/e0800130-30ce-45e1-abfc-0af1c68d228c) )

We can introduce additional penalty_transition to fix https://github.com/osmandapp/OsmAnd/issues/17502#issuecomment-1736862648

**Comment by RZR-UA** [comment]
"Bad" short road:

![direct](https://github.com/osmandapp/OsmAnd/assets/90444451/a6663d63-f090-46bb-b2aa-1660cbe0ba55)

Sattelite image:

![sat](https://github.com/osmandapp/OsmAnd/assets/90444451/ba9018c1-9e22-4e23-b052-a154f9010f42)

There is no problem with Savino (xmd5a2 case).

On the shortest route, there is living_street(s) (**speed 25, much lesser than 35 for residential**) - this is the main reason why route is not the shortest by distance.

Gravel priority is not a case also, because that "shortest" living_street(s) has "ground" surface which is worse than gravel.

Sattelite image confirms that nobody using that "short" road in Savino.

Closed.

**Comment by vshcherb** [comment]
@RZR-UA what about https://github.com/osmandapp/OsmAnd/issues/17502#issuecomment-1764306065 and how this route looks https://user-images.githubusercontent.com/116079541/265284603-6c38ad2d-4cce-413b-ae39-c44ed0d97d07.jpg

**Comment by RZR-UA** [comment]
Original route looks great:

![good](https://github.com/osmandapp/OsmAnd/assets/90444451/c7bba0be-0011-4fb0-860e-fd1f0968d06a)

**Comment by dmpr0** [comment]
## Review 
Not clear ToDo.
