### ISSUE TITLE
Route line is cut off (after turn off screen / rotation / ..)

### ISSUE THREAD

**Issue by pordini** [osmandapp/OsmAnd#17506]
### Description
Route line disappears after a certain point, then reappears a few seconds later.

### Steps to reproduce
Unknown at this time. I haven't been able to determine when exactly it happens, I've just seen it several times in different places and managed to screenshot it once. 
Coordinates: 47.67485° N, 21.50777° E

### Actual result
<table style="width:100%">
  <tr>
    <th>Line is cut off</th>
    <th>Line reappears</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/12774050/fca66ccd-c83c-4429-95b2-d50a964731ed"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/12774050/7b1dde03-3c78-49ac-9cad-49dc1a230a88"  width="300" height="auto"/> </td>
  </tr>
</table>

### Expected result
The route line continues on.

### Your Environment
OsmAnd Version: OsmAnd+ 4.5.3, released: 2023-06-20
Android/iOS version: 13, Graphene
Device model: Pixel 5

**Comment by pordini** [comment]
![Screenshot_20230629-120142](https://github.com/osmandapp/OsmAnd/assets/12774050/bc1f80c3-a023-4e45-821b-6b4cc12b9657)
Happened again in the Budapest area.

**Comment by DmitryAlexei** [comment]
As for me, route line disappears only in front of *My location* icon. 
[logcat (4).log](https://github.com/osmandapp/OsmAnd/files/11984113/logcat.4.log)

- Managed to reproduce this issue while travelling along existing GPX track
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/baa35aeb-720d-4928-9c32-dfc59b13d2e1"  width="300" height="auto"/> </th>
  </tr>
</table>

- and without a track. In that case, it may be related to the (accidental) change of orientation of the device screen during road turns.

 <table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/cfa69407-ac3a-4449-beb1-6a77d608181d"  width="600" height="auto"/> </th>
  </tr>
</table>

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/5c1af40a-94c2-4626-9580-eb5818f32a15"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by cepprice** [comment]
Bug with missing segments in front of My location is fixed
Bug with missing segments in the middle of route wasn't reproduced

**Comment by DmitryAlexei** [comment]
Still can be reproduced after starting navigation along existing GPX track (car profile, default route line appearance). I build regular navigation and part of the route goes along or near visible gpx track


[logcat.log](https://github.com/osmandapp/OsmAnd/files/12686326/logcat.log)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/6faa8dbe-41ab-43a4-89bd-ebb70e95ff19"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/cb4e84fe-ae9b-417b-b422-db6aa8633f15"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
In other use cases, including when screen orientation changes, work fine.
