### ISSUE TITLE
Response to panning with external keyboard is choppy

### ISSUE THREAD

**Issue by joostbijl** [osmandapp/OsmAnd#17509]
### Description
When using an external keyboard (or controller) to pan the map, Osmand sometimes behaves choppy

### Steps to reproduce
* Put the phone in landscape position
* Start osmand
* Simulate a route
* Put the map orientation in 'movement direction'
* Observe that panning works as expected by pressing arrow keys
* Rotate the device to portrait position
* Observe that panning is choppy by pressing arrow keys

### Actual result
Here's a video of the behavior and the steps to reproduce: https://youtu.be/XbKcxKUm8bY

It looks like the calculation of the panning increment breaks when you rotate the device.

### Expected result
Panning is smooth, also when you rotate the device.

### Your Environment
OsmAnd Version:  4.5.3
Android/iOS version: 10
Device model: Blackview BV5100 (720x1440 screen resolution)
Map Rendering engine: Version 2 (OpenGL)
Controller: JaxeADV BarButtons

**Comment by vshcherb** [comment]
This was recently fixed new version is being prepared.

**Comment by NorthmanFPV** [comment]
I have the same problem with Osmand 4.5.10 on my Samsung Galaxy Active Tab 3. It's not fixed.
