### ISSUE TITLE
Wrong turn/lane suggestion

### ISSUE THREAD

**Issue by Wouter-M** [osmandapp/OsmAnd#17508]
### Description
It's about this route (https://osmand.net/map?start=52.500065%2C6.054518&end=52.468305%2C5.986766&mode=car#15/52.4913/6.0375). The route suggests the right lanes (even though the blue navigation line goes to the left lane for straigh-ahead). The suggested right lanes would have you end up going in the wrong direction. 
I looked at the map data in JOSM, and I cannot find anything on the map that seems wrong to me.

### Steps to reproduce
This is the shortest route I can reproduce the issue

1. Plan a route between (52.50006, 6.05452) and (52.46831, 5.98677) for profile car
2. Turn on 'simulate navigation' in the settings
3. Start the route

### Actual result
When nearing the 'Knooppunt Hattemerbroek', the lane suggestion and associated voice prompt suggest a right turn (using the right lane) even though the actual route (and correct lanes) are the two-left most ones.
Screenshot:
![Screenshot_2023-06-26-20-41-15-62_54166e5c6f8ad9491c65e2397c495c92](https://github.com/osmandapp/OsmAnd/assets/6692660/319a71f2-bfcd-41e1-914f-f893340269b3)

The written turn-by-turn also suggest the incorrect right lanes:

![Screenshot_2023-06-26-20-51-23-29_54166e5c6f8ad9491c65e2397c495c92](https://github.com/osmandapp/OsmAnd/assets/6692660/8610de4b-3442-4e89-abdb-bf22324d17b4)
The second instruction about 'Turn slightly right and go ...' is incorrect.

### Expected result
I expect it to use the left two most lanes, especially since the blue line also follows these.

### Your Environment
OsmAnd Version: 4.5.3
Android/iOS version: Android 13
Device model: OnePlus 10 Pro 5G

**Comment by zipav** [comment]
Another similar case from a user:
Launch coordinates: `37.01826 -7.96824`
Finish coordinates: `37.11632 -8.41943`

Voice prompts offer to turn off the road, which you just need to go straight.
Rotation on 12 EN, on 9 IC, and 8 EM is suggested.

App version: OsmAnd+ 4.4.7 (Android)


  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/5da2595c-8b55-4f63-b2be-f12293e5a25d"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/c439f07b-bb71-4aa5-8cb3-7fe46050adf3"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
It could be determined from the data cause https://www.openstreetmap.org/way/6511892#map=18/52.49180/6.03506 - the right
