### ISSUE TITLE
Track loses resolution (seem to have fewer points) when changing profile 

### ISSUE THREAD

**Issue by vsassone** [osmandapp/OsmAnd#17517]
### Description
 I’ve noticed that changing the profile garbles the tracks displayed on  the screen (as if a lot of points were dropped and straight lines connected the remaining ones), you have to unshow and then show them again to fix them.

### Steps to reproduce

I expect this has to do with the underlying map changing, so the displayed track becomes sketchy. Unshowing and showing again fixes it. 

### Your Environment
OsmAnd Version: current beta
Android/iOS version: android 13
Device model: Samsung active tab 3

**Comment by vsassone** [comment]
Apologies this is a rubbish report. I’ll try to update it with more information as soon as I can.

**Comment by vsassone** [comment]
Still planning to come back to this now that I have the device with me, but struggling to reproduce the issue to screenshot it. Pls bear with me.

**Comment by vsassone** [comment]
I m finally able to attach two pairs of screenshots thwt illustrate the issue. The first of each shows a “low resolution” rendering of a track, the second shows the track correctly rendered after cycling the “show on map” button. 

![IMG_7934](https://github.com/osmandapp/OsmAnd/assets/25900396/27085c02-7407-4cce-89bf-7a86820bf131)
![IMG_7939](https://github.com/osmandapp/OsmAnd/assets/25900396/58ccaf1d-18c0-4f31-a165-4aaf15bc68aa)
![IMG_7936](https://github.com/osmandapp/OsmAnd/assets/25900396/6873b888-a63e-42b2-8b36-1b1419c3ff30)
![IMG_7937](https://github.com/osmandapp/OsmAnd/assets/25900396/3f1f0112-a961-4291-8806-167c57db8356)

**Comment by vsassone** [comment]
Didn’t mean to close it, apologies.

**Comment by vshcherb** [comment]
If you can share tracks to our support email, we will try to reproduce it. Also we can't understand if geometry is permanently broken (so restart is required or reimport track is required) or it can be fixed by zoom in out? if you can if you can show on video it would be great.

**Comment by vsassone** [comment]
Definitely will select suitable tracks. Geometry is not permanently broken. No restart is required to fix. Zoom in/out won’t fix it, but hide and then show again the track on the map (through clicking the eye symbol) will. I’ll try to take a video asap.

**Comment by DmitryAlexei** [comment]
may be reopened if additional information is provided

**Comment by vsassone** [comment]
I manage to take a video of this, but still I can’t reproduce it

**Comment by DmitryAlexei** [comment]
Please, provide information of your OsmAnd build, tracks and video, we will try to reproduce this issue.

**Comment by vsassone** [comment]
Hello. I’ve got a new clear video of this. Observe the track is rendered with straight lines rather than follow the road. It is enough to hide and then unhide the track for the rendering to get correct. This is osmand 4.5.10 on android 12. On 15 Oct 2023, at 19:54, DmitryAlexei ***@***.***> wrote:﻿




CAUTION: This e-mail originated outside the University of Southampton.




Please, provide information of your OsmAnd build, tracks and video, we will try to reproduce this issue.
—
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
You are receiving this because you modified the open/close state.Message
 ID: ***@***.***>

**Comment by vsassone** [comment]
Yes, please a link to where you want me to upload it. I can also upload the gpx. On 28 Nov 2023, at 07:37, DmitryAlexei ***@***.***> wrote:﻿




CAUTION: This e-mail originated outside the University of Southampton.




@vsassone I would
 be grateful, if you add your video to that ticket. It seems, that video cannot be uploaded via e-mail.
—
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
You are receiving this because you were mentioned.Message
 ID: ***@***.***>

**Comment by DmitryAlexei** [comment]
@vsassone Please send your tracks to support@osmand.net
