### ISSUE TITLE
During a turn after announcement, map rotation follows movement, while the current position marker only rotates and stays stuck at the beginning of the turn

### ISSUE THREAD

**Issue by Max1234-Ita** [osmandapp/OsmAnd#17518]
### Description
While taking an announced turn, i.e. driving along a roundabout or motorway trunk, I see the map rotates accordingly to my curren theading, and so does the blue indicator of current position; The indicator itself, however, stays "stuck" at the beginning of the turn and no new announcement is made until its position is updated, making it very uncomfortable to follow the correct route (i.e. if another trunk or roundabout is very close to the previous)

### Steps to reproduce

1. Open OsmAnd and calculate a route which includes several motorway junctions or roundabouts; Start navigating with the "car" profile;
2. When a turn approaches, announcement is properly made both on the map and the left panel (i.e. "turn right")
3. While driving along the trunk, check the map for next driving direction; observe that the current position indicator is still at the very beginning of the turn, while map and indicator rotation are updated; 

![image](https://github.com/osmandapp/OsmAnd/assets/15315381/7a0f4511-2c0c-4fc2-8ab6-2744ca8fdee4)
![image](https://github.com/osmandapp/OsmAnd/assets/15315381/5293b28f-d61b-4ecf-b913-6d018634cd95)
![image](https://github.com/osmandapp/OsmAnd/assets/15315381/8b329d12-36fc-4d57-b260-2d9e55d8fa49)
![image](https://github.com/osmandapp/OsmAnd/assets/15315381/92fd35ee-9f7a-4bf6-9737-28f22ff79df4)

### Actual result
This issue is not very helpful and potentially dangerous on road safety side (the driver might be distracted trying to understand what's happening, while he/she should remain concentrated on the road)

### Expected result
Current position indicator should  properly follow the movement, even if the real position does not belong to the calculated route.

### Your Environment
OsmAnd Version: Osmand+ v. 4.5.3
Android/iOS version: Android 11
Device model: Samsung Galaxy A50 (SM-A505 FN)

**Comment by mikehgentry** [comment]
Probably #16081

Disable 'animate own position', or switch to rendering engine v2 (OpenGL).
