### ISSUE TITLE
Current speed widget on device only displays two random speed values when connected to Android Auto

### ISSUE THREAD

**Issue by kit4short** [osmandapp/OsmAnd#17513]
### Description
When I plug my Android device into my vehicles Android Auto system and display the navigation widgets separately on the Android device, the current speed widget seems to get stuck on a pair of values. These values appear random, so instead of displaying the actual speed of the vehicle, the current speed widget displays a pair of alternate values, for example 12 & 14kmh, regardless of the vehicles speed.

### Steps to reproduce
1) Plug the Android device into the vehicles Android Auto interface
2) From the Android device, open or refresh the OSMAnd app
3) Android device tells user that map is displayed in the Android Auto display
4) Widgets as defined in the relevant profile are displayed (current speed, trip etc)
5) This bug occurs regardless of whether the record trip has been activated with or without  navigation to a destination having been chosen.

### Actual result
Current speed displays two random speed values that alternate between each other and have no relationship to the actual speed the vehicle is travelling

### Expected result
The current speed widget displays the actual current speed

### Your Environment
OsmAnd Version: 4.5.3 beta released 2023-06-20
Android/iOS version: 13TP1A.220624.014
Device model: Redmi Note 11 Pro+ (Model# 21091116UG)

**Comment by vshcherb** [comment]
I think it's the same https://github.com/osmandapp/OsmAnd/issues/17505. So workaround might help
