### ISSUE TITLE
AIDL remove GPX does not work

### ISSUE THREAD

**Issue by pab2d** [osmandapp/OsmAnd#17526]
### Description
Using AIDL command removeGpx has no effect. Imported files are not deleted.

### Steps to reproduce
Import a couple of tracks or create them by using navigateGpx command.

Use OsmAndAidlInterface commands (e.g. from OsmAnd-api-sample project).

```java
public List<AGpxFile> getImportedGpxFiles() {
        if (mIOsmAndAidlInterface != null) {
            try {
                List<AGpxFile> res = new ArrayList<>();
                if (mIOsmAndAidlInterface.getImportedGpx(res)) {
                    return res;
                }
            } catch (RemoteException e) {
                MobileLogger.error(e);
            }
        }
        return null;
    }

public boolean removeGpx(String fileName) {
        if (mIOsmAndAidlInterface != null) {
            try {
                return mIOsmAndAidlInterface.removeGpx(new RemoveGpxParams(fileName));
            } catch (RemoteException e) {
                MobileLogger.error(e);
            }
        }
        return false;
    }

public void deleteAllTracks() {
         List<AGpxFile> importedGpxFiles = getImportedGpxFiles();
         for (AGpxFile file : importedGpxFiles) {
             removeGpx(file.getFileName());
         }
}
``` 

### Actual result
After excecuting deleteAllTracks() all files are still inside the tracks/imported directory.

### Expected result
All imported files are deleted.

AddOn:
When using the navigateGpx method, it would be very helpful to be able to specify the file name under which the file is stored in the import directory. Otherwise the only option is to delete everything?!?. If the file name was specified, only this could be deleted.  

### Your Environment
OsmAnd Version: 4.4.7 
Android version: API 31
Device model: Emulator Pixel 3

**Comment by vshcherb** [comment]
If you can provide PR to fix it, please do it, so we can speed up this process

**Comment by pab2d** [comment]
I see two possible solutions, please decide which one do you prefer and use the fix.

Keyfacts:
Tracks (GPX) can be imported via App function or by calling e.g. AIDL navigateGpx method.
**In case of import via App:**
- GPX file is stored in the tracks root directory.
- File data is added to GPXDatabase and is flagged as imported.
**In case of "import" via navigateGpx():**
- File is stored in a subdirectory: import under tracks.
- File data is added to GPXDatabase but is not flagged as imported.
- The itemCache Map in GpxDbHelper contains the wrong path string (key does not contain the import directory)
**All possible track subdirectories:**
`GPX_INDEX_DIR = "tracks/";
GPX_IMPORT_DIR = "tracks/import/";
GPX_RECORDED_INDEX_DIR = "tracks/rec/";
GPX_TRAVEL_DIR = "tracks/travel/";
`

Calling AIDL getImportedGpx function returns only file names without subdirectory names and do not differentiate between imported and unimported flagged files.
 
**Solution 1**
getImportedGpx function returns the filenames with the subdirectory(ies).
removeGpx function do not check for imported flag.
`	
// class: OsmandAidlApi.java
boolean getImportedGpxV2(List<net.osmand.aidlapi.gpx.AGpxFile> files) {
		List<GpxDataItem> gpxDataItems = app.getGpxDbHelper().getItems();
		for (GpxDataItem dataItem : gpxDataItems) {
			File file = dataItem.getFile();
			if (file.exists()) {
				String segments[] = file.getPath().split(IndexConstants.GPX_INDEX_DIR);
				String fileName = segments[segments.length - 1]; // filename with its subdirectory(ies)
				boolean active = app.getSelectedGpxHelper().getSelectedFileByPath(file.getAbsolutePath()) != null;
				long modifiedTime = dataItem.getFileLastModifiedTime();
				long fileSize = file.length();
				int color = dataItem.getColor();
				String colorName = "";
				if (color != 0) {
					colorName = GpxAppearanceAdapter.parseTrackColorName(app.getRendererRegistry().getCurrentSelectedRenderer(), color);
				}
				net.osmand.aidlapi.gpx.AGpxFileDetails details = null;
				GPXTrackAnalysis analysis = dataItem.getAnalysis();
				if (analysis != null) {
					details = createGpxFileDetailsV2(analysis);
				}
				files.add(new net.osmand.aidlapi.gpx.AGpxFile(fileName, modifiedTime, fileSize, active, colorName, details));
			}
		}
		return true;
	}

	boolean getImportedGpx(List<AGpxFile> files) {
		List<GpxDataItem> gpxDataItems = app.getGpxDbHelper().getItems();
		for (GpxDataItem dataItem : gpxDataItems) {
			File file = dataItem.getFile();
			if (file.exists()) {
				String segments[] = file.getPath().split(IndexConstants.GPX_INDEX_DIR);
				String fileName = segments[segments.length - 1]; // filename with its subdirectory(ies)
				boolean active = app.getSelectedGpxHelper().getSelectedFileByPath(file.getAbsolutePath()) != null;
				long modifiedTime = dataItem.getFileLastModifiedTime();
				long fileSize = file.length();
				AGpxFileDetails details = null;
				GPXTrackAnalysis analysis = dataItem.getAnalysis();
				if (analysis != null) {
					details = createGpxFileDetails(analysis);
				}
				files.add(new AGpxFile(fileName, modifiedTime, fileSize, active, details));
			}
		}
		return true;
	}

	boolean removeGpx(String fileName) {
		if (!Algorithms.isEmpty(fileName)) {
			File f = app.getAppPath(IndexConstants.GPX_INDEX_DIR + fileName);
			if (f.exists()) {
				GpxDataItem item = app.getGpxDbHelper().getItem(f);
				if (item != null) { // && item.isApiImported()) { // disable imported check
					Algorithms.removeAllFiles(f);
					return app.getGpxDbHelper().remove(f); // return result directly in case of remove is false!
				}
			}
		}

		return false;
	}`
Based on the workflow of my example (get all imported GPX files, delete them, start a new navigation), the GpxDbHelper - readGpxItem(..) method should be improved too. Otherwise the rendering tries to render a file which is already deleted.

`private void readGpxItem(@NonNull File gpxFile, @Nullable GpxDataItem item, @Nullable GpxDataItemCallback callback) {
		if (gpxFile.exists()) { // GPX file may have already been deleted, before the rendering starts
			readingItemsMap.put(gpxFile, item != null ? item : new GpxDataItem(null, (GPXTrackAnalysis) null));
			if (callback != null) {
				readingItemsCallbacks.put(gpxFile, callback);
			}
			readingItems.add(gpxFile);
			if (readerTask == null) {
				startReading();
			}
		}
	}`

**Solution 2**
If getImportedGpx function should still return only the filenames and hide the internal directory structure:
- The removeGpx method should not check neither if the file exists (works only for files in tracks directory) nor the imported flag.
- The key for the itemCache (GpxDbHelper) should be fixed. Maybe only the filename should be used instead of the complete path. At the moment the key does not contain the information about the subdirectory.

Guess to change the key logic bring up a whole bunch of problems...

I can not provide a PR at the moment, so please use my code of solution 1 for your tests and use the fix if it suits you. 
appreciate that.

**Comment by nazar-kutz** [comment]
Hi @pab2d!
Thank you for your suggestions (https://github.com/osmandapp/OsmAnd/pull/17594) and detailed response and sorry for my late reply.

We are currently working on this tasks and will add a similar fix to what you suggested in #17594 to use a custom file name for navigation. A '**_fileName_**' parameter will be added to the **_NavigateGpxParams_** class.

The file name may change during saving if a file with that name already exists in the directory. The changed file name will replace the corresponding parameter in the **_NavigateGpxParams_** class, so it can be pulled up and used for your purposes.

We will also add the ability to find out the _relative path_ of the _imported files_ relative to the root folder in which all tracks are stored when the **_getImportedGpx_** method is called.

Deleting a track has always been done by its _relative path_, so this will now be explicitly indicated by the **_relativePath_** parameter, which replaces the previous **_fileName_** parameter in the **_RemoveGpxParams_** class.

**Comment by pab2d** [comment]
Hi @nazar-kutz,
thank you for the information. Can you tell approximately when the fix / feature will be implemented?

**Comment by nazar-kutz** [comment]
The PR's already on review: https://github.com/osmandapp/OsmAnd/pull/17650
Maybe there will be additional fixes needed after review before the fix will be available in nightly.

**Comment by christianCasRo** [comment]
Do you have tried and work?
Maybe I'm missing something in the files of the solution, because I have the same problem
