### ISSUE TITLE
deleting all and not only the selected tracks in "my places > tracks > folder_xy" 

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#17522]
### Description

In "my places > tracks" I wanted to delete some tracks from a folder.
This folder contained 45 tracks. 
Tapped the  "top 3 dots" and "selecting".
Selected 22 of 45 tracks.
Tapped at "deleteing".
Osmand told me 45 of 45 tracks succesful deletet.

Very funny. This was my planned next three-weeks-Balkan-trip.
(Yes, I do have a backup and was able to restore my tracks. But all the individual settings/appearance are lost)

And since then osmand crashed already 4 times, without me doing anything (except sending crashlog and restart the app). 

### Your Environment
OsmAnd Version: 13
Android/iOS version: +4.5.3
Device model: S20+

**Comment by yuriiurshuliak** [comment]
20 tracks were deleted in a folder containing 40 tracks, that is exactly the number I selected.
OsmAnd~ 4.5.0#313m, released: 2023-06-29

Please try again and send the corresponding video and log file right after repeating this error.


<table style="width:100%">
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/1691f792-b903-41ae-aa11-c166bd7579df"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by Chumva** [comment]
This should be fixed [here](https://github.com/osmandapp/OsmAnd/commit/a5803300bbe287e88ada00aa0366a8342ec3425b), in nightly and next build 4.5.4
