### ISSUE TITLE
Wrong widgets order and placement after import without restart

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#17527]
## Description
After import OSF file with profile settings, widgets that should be on left panel, visible on the right panel, widget duplicates is missing too, it change back to proper order and quantity after app restart.

> Tested on `OsmAnd~ 4.5.0#306m, released: 2023-06-29`

Logcat after import (without restart) – [logcat (7).log](https://github.com/osmandapp/OsmAnd/files/11904348/logcat.7.log)

## How to reproduce
* **Reset to default** Browser map profile
* **Left panel** in **Configure Screen** should be empty
* Import the file [Export_2023-06-29.osf.zip](https://github.com/osmandapp/OsmAnd/files/11904250/Export_2023-06-29.osf.zip)

## Actual result
* Widgets shows up on wrong panel (right instead of left)
* Duplicates is missing
* Manual app restart fix the issue

<table style="width:100%">
  <tr>
    <th>State before Export (right order and panel)</th>
    <th>State after import (without restart)</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/e9ff0b71-19a9-440a-8585-1ef4397da4da"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/b2543448-c529-4c2d-8abb-76d8bee81226"  width="300" height="auto"/> </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/9365308/c963e023-8d53-45c7-9000-d4cf8ac4f07f"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by yuriiurshuliak** [comment]
After importing the profile settings, the widgets are displayed in the right panel. After restarting the application, the widgets start to appear on the left panel.

OsmAnd~ 4.5.0#313m, released: 2023-06-29


<table style="width:100%">
  <tr>
    <th>State before Export</th>
    <th>State after import (without restart)</th>
    <th>State after import (after restart)</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/bd33f7bf-1188-4119-8934-760093f38570"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/7ae66189-bcf8-4f06-bfa9-9019fc077f1d"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/7f8e3afd-aa18-4b71-8414-8a1e82be0152"  width="300" height="auto"/> </th>
  </tr>
</table>



<table style="width:100%">
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/73b79870-b1d5-422b-9d3e-9b7cbbe4a675"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by dmpr0** [comment]
# Review – 1

```
net.osmand: SettingsHelper Failed to collect items from: Export_2023-06-29.osf
java.lang.IllegalArgumentException: No items
	at net.osmand.plus.settings.backend.backup.SettingsImporter.processItems(SettingsImporter.java:109)
	at net.osmand.plus.settings.backend.backup.SettingsImporter.collectItems(SettingsImporter.java:37)
	at net.osmand.plus.settings.backend.backup.ImportFileTask.doInBackground(ImportFileTask.java:102)
	at net.osmand.plus.settings.backend.backup.ImportFileTask.doInBackground(ImportFileTask.java:23)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

- [ ]  Unable to import file [Export_2023-06-29.osf.zip](https://github.com/osmandapp/OsmAnd/files/11904250/Export_2023-06-29.osf.zip)
