### ISSUE TITLE
"Bar" category didn't proposed in Search

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#17528]
## Description
Search doesn't show **Bar** as search category only show POI with bar in the name

## How to reproduce
**Search**
* Open **Menu** – **Search**
* Type "Bar"

**Custom categories**
* Open **Menu** – **Search** – **Categories**
* Scroll down, tap on **Custom search**
* Type "Bar" in search

## Actual result
* "Bar" category didn't show up in search result
* "Bar" category didn't show up in Add Custom category search result

<table style="width:100%">
  <tr>
    <th>Android</th>
    <th>iOS</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/eea8e396-278a-42ad-aa70-6fadf87295c2"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/37e45c52-9a66-4759-8758-83a986c20397"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Dima-1** [comment]
https://github.com/osmandapp/OsmAnd/commit/dfd5f73c0676347ce8531d9863206c7d1300faa0

**Comment by DmitryAlexei** [comment]
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/2e819f08-3923-4c68-99ed-79c812fbd593"  width="300" height="auto"/> </th>
  </tr>
</table>
