### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by saeedafshari8** [osmandapp/Osmand#1752]
Hi,
According the issue #1701 I cloned and add resource files into drawable directory inside of OsmAnd project. But still I have a build exception as following:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':OsmAnd:preDexFreeLegacyArmv5Debug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_25\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

I couldn't solve the problem.

**Comment by vshcherb** [comment]
Service is running *assembleFreeLegacyFatDebug* task and build is green, please use *repo* utility to correctly clone repository https://github.com/osmandapp/OsmAnd-manifest/blob/master/android_build.xml
