### ISSUE TITLE
Suggestion: Create a "Filter visible" button on My Places >  Tracks

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#17538]
Today we have a "Visible on map" line item under My Places > Tracks. Tapping it takes you to an entirely separate Track management setup with different appearance (folders now tabbed horizontally, ...) and operation (long tap behavior, ...).

Why would we not simply convert this to a "Filter visible" button? And activating it would remain **on the same screen**, but it would be filtered to the visible tracks and folders only?

Side benefit: Configure map >Tracks would point to this screen with this "Visible" filter active. By simply deactivating it the user would be on the full management screen for all tracks.

By eliminating the 2 different track UIs you now perform operations on visible and invisible tracks (or folders) in exactly the same fashion. In addition, the "visible only" filter would provide a much clearer overview which track folders are (fully or partially) selected to be visible, something almost impossible to find out today. (Seeing and changing the visibility status of entire track folders is a valid use case.)

**Comment by vshcherb** [comment]
This is planned to work the same as Filters. So you will be able to create own filters which won't work same as Folders, so I think UI could be different but it will still be row and  a button.

**Comment by sonora** [comment]
@vshcherb , @DmitryAlexei The more I observe users working with the new Tracks setup, the more convinced am I this suggestion here would be a good idea for everyone. So what's the plan now, Victor comments is as "is planned", but Dmitry, you mark it as "not planned"?

Please note that we have continued support cases where usrs have found the _Configure map > Tracks_ screen, but from there is currently no obvious path to get to the full Tracks management screen. If it was simply a filtered version of the full screen, it would be both obvious and easy.

**Comment by DmitryAlexei** [comment]
@sonora We will keep this issue in the *In future* section of *Done/Closed* until Victor adds a milestone to it.

**Comment by vshcherb** [comment]
@sonora Filters in general are planned for 4.6 but it's a complex task. It's definitely in roadmap but it really depends how much time we will have for 4.6. We also have weather redesign to improve too much tasks to handle in 1 release. 

The main message that we want to have separate entity Filters and Folders and for now we don't want to do "small improvement" cause it will take time anyway and they won't be small
