### ISSUE TITLE
Wishlist: adjust sound volume to speed

### ISSUE THREAD

**Issue by RicoZ-OSM** [osmandapp/Osmand#1753]
Presumably at higher speeds the noise is dominated by wind noise which is some factor times square of the speed.

At lower speeds tire noise (assumed linear to speed) and engine RPM  (possible surrogate acceleration) will be more significant than wind noise but I assume the volume adjustment would be most important  for speeds where the wind noise prevails.

Adjustment should be probably disabled if music is playing, it is safer to assume that music volume was manually adjusted.

Also realized that many (most?) devices have a microphone which could be in theory used to estimate noise level. 

Here is some example code which might be usable:
https://code.google.com/p/android-labs/source/browse/trunk/NoiseAlert/src/com/google/android/noisealert/SoundMeter.java?r=2

**Comment by breversa** [comment]
Speed of sound (https://github.com/jpeddicord/speedofsound) is released under GPLv2. Maybe another source of inspiration ?

**Comment by sonora** [comment]
I think this seriously should _not_ be a function in OsmAnd but done by external systems, as volume changes usually need to apply system-wide ("infrastructure-like"), not just for OsmAnd prompts. So the solutions are already existing: A system-wide app for your device, or the adaptive volume setting in your car stereo, or special features present on some headsets. Some of these features work with speed data, others with background noise evaluation and are more situation-specific than OsmAnd could be.

**Comment by vshcherb** [comment]
Yes, it is done by external systems, for example, Ford already has this function for years and it works if you connect via AUX. For Headphones this function also doesn't add much value.

**Comment by RicoZ-OSM** [comment]
It would never come to my mind to use car navigation with headphones. Some cars have sophisticated volume management but not all.

Also don't agree that it a systemwide app is preferable - an OsmAnd solution can do much better:
* it can save battery and CPU power by analysing background noise only shortly before messages need to be spoken
* analysis of background noise is much cheaper/better for an app like OsmAnd which does not continuously play music which would be the assumption for most general purpose volume managing apps
