### ISSUE TITLE
TTS reading only name=... no name:fr, name:it, name:de,

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/Osmand#1754]
In some citys are bilingual names of streets.

OSM Wiki:http://wiki.openstreetmap.org/wiki/Multilingual_names#Sardegna_.28Sardinia.29

Example1: I am Italian and go to Sardegna and navigate around with a car/bicycle/...
So for me the navigation is more easy when OSMand TTS read the name:it=... because I use only Italian on my device. 

OsmAnd is displaying name:it=... but TTS read only name=...
http://www.openstreetmap.org/#map=14/39.9253/8.5820&layers=N

Example2: I am Italian and go to North Italy and navigate around with a car/bicycle/...

There are long bilingual street names:
http://www.openstreetmap.org/way/29899813
http://www.openstreetmap.org/way/40504242
http://www.openstreetmap.org/way/367039099
http://www.openstreetmap.org/way/34178033

If OsmAnd TTS reed only name=..., in this places come out a lot of nonsense during navigating.
My Italian TTS have problems to reed the German part of name=... 
German TTS, I think have the same problems with the Italian part.

Example3: Belgium
In this example I am French and go to Belgium.
http://www.openstreetmap.org/way/22775323
for me is only "name:fr=Rue des Déportés" important, and French TTS have a lot of problems to reed the Dutch part of name:... - Weggevoerdenstraat
The TTS reed correct French part Rue des Déportés and then only nonsense Weg.v...ens.....at

My finally question:
Is it possible to make the TTS configuration to reed the name:<lg>

**Comment by vshcherb** [comment]
In some sense it is duplicate issue to use different TTS engines for Street names and for riding, in another case it is already implemented by changing Configure Map -> Map Language.

**Comment by hakuchi** [comment]
if I set Map Language to German, the map show German names, but for navigating use only Italian names.
If I set to Italian, the map shows Italian names and for navigating use only name=... and if no name:it=.. is present, osmand reed name:de=...
The tested roads have name=.. name:it=... and name:de=... and roads with name=... and name:de=..
I use OsmAnd+ 2.1.1 and latest offline maps
