### ISSUE TITLE
My Places > :Tracks: In selection mode display the number of selected tracks

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#17541]
Carry-over of #17381: The purpose of our My Places > Tracks screen is to manage tracks. In selection mode, i.e. when you see the checkboxes to select tracks and folders for any subsequent action, it is interesting to see the number of tracks actually selected, i.e. if you selected e.g. 3 folders, let's not display "3", but the accumulated number of tracks (which would be affected by any subsequent action like "Show on map").

If we do not want to drop the number of checkmarks selected, we could display both, like "3  folders (248 tracks)".

**Comment by vshcherb** [comment]
To do: show selected UI element and show selected Tracks
- ``` SELECTED_ELEMENTS (SELECTED_TRACKS Tracks) ```. Example "4 (5 Tracks)"
