### ISSUE TITLE
Include emergency=assembly_point 

### ISSUE THREAD

**Issue by mnalis** [osmandapp/OsmAnd#17540]
# 🚀 feature request

### Description

[emergency=assembly_point](https://wiki.openstreetmap.org/wiki/Tag:emergency=assembly_point) is useful tag for mapping designated area in case of an emergency like natural disaster etc. Yet it is not rendered nor can be shown in OsmAnd. Even enabling to show all `Nearby POIs` on the map does not show it, so I guess it is maybe not even included in `.obf` file?

### Describe the solution you'd like

- It would be nice if it was included, so user can search / show it in `POI overlay`
- additionally it should be shown in default OsmAnd offline renderer.

### Describe alternatives you've considered

Writing overpass turbo query and saving that as GPX on the phone regularly to be used by OsmAnd; but that is obviously not practical at all.

**Comment by XandrexOSM** [comment]
I see 13'000 objects (from taginfo), so I guess it would not make the OsmAnd database much heavier.

A few lines of code, not much data, but it can provide a lot of dafety to people who may need the info worldwide.
=> it's a quick win !

**Comment by DmitryAlexei** [comment]
https://github.com/osmandapp/OsmAnd-resources/blob/master/rendering_styles/default.render.xml
https://osmand.net/docs/user/map-legend/osmand#emergency

**Comment by mnalis** [comment]
@DmitryAlexei if I see correctly on those two links, they have other emergency tags, but not `emergency=assembly_point`, right? 
If so, I can make PR that updates those two files. However, is that all that is needed? (as it is not only an issue with default offline renderer because `Nearby POIs` does not show that POI - which seems to me like it is not even present in `.obf` file)

**Comment by DmitryAlexei** [comment]
@mnalis Yes, OsmAnd displays other emergency tags, but not a mentioned one.
We will probably also need a separate icon for *Assembly point*.

**Comment by mnalis** [comment]
@DmitryAlexei I've done PR https://github.com/osmandapp/OsmAnd-resources/pull/985 which attempts to implement it (including separate icon as requested), and also PR https://github.com/osmandapp/web/pull/127 which adds the docs; would you take a look if it looks OK to you?

**Comment by xmd5a2** [comment]
How to test: update **Luxembourg** map and go to https://www.openstreetmap.org/node/10295226425
