### ISSUE TITLE
Map tilt breaks route preview

### ISSUE THREAD

**Issue by mikehgentry** [osmandapp/OsmAnd#17553]
## Description

When you long press on a spot and choose 'Navigation', OsmAnd calculates a route (doesn't seem to matter which algorithm, so choose 'straight line' to speed things up), the menu to start and stop navigation appears, and the viewport (squeezed into the top of the screen) pans and zooms to show the proposed route.

This is at least sometimes broken if the map is tilted. Long journeys and high degrees of tilt seem to exacerbate it. I'm in South West England, and I've ended up with views of Scottish islands and random places in Brittany.

### How to reproduce

Tilt map extremely, long press on the map somewhere fairly far away, choose 'Navigation'. It may take several attempts. Use 'Straight line' algorithm to speed things up.

**Environment**
OsmAnd Version: + 4.5.3
Android/iOS version: 11
Device model: XCover 4s

**Comment by pordini** [comment]
I've seen the same on Pixel 5, Android 13, OsmAnd+ 4.5.3.

Also happens with short routes, just less extreme. Instead of centering the route it just focuses on an unrelated bit of map.

**Comment by zipav** [comment]
OsmAnd Nightly 4.5.0#370m, released: 2023-07-10

### Steps to reproduce:
- Tilt the map as much as you can using a gesture
- Choose profile avia
- Tap the point on the map
- Navigation button
- Choose start\finish points
- Navigation settings
- Navigation type: straight line
- Start

Navigation does not behave correctly

https://github.com/osmandapp/OsmAnd/assets/123936521/36beee1c-5ced-4b96-9cde-cde2c893ac82

**Comment by DmitryAlexei** [comment]
https://github.com/osmandapp/OsmAnd/assets/116079541/5f92ddfd-b1c1-4597-9d6c-e9c98d65a2b7

**Comment by mikehgentry** [comment]
I think this is actually broken sometimes without any map tilt at all, though haven't tested extensively in render engine v1.

**Comment by pordini** [comment]
> I think this is actually broken sometimes without any map tilt at all, though haven't tested extensively in render engine v1.

Yes, I've seen this as well.


https://github.com/osmandapp/OsmAnd/assets/12774050/d7dcbea7-d6a8-47b6-b524-d997aa2abdbb

**Comment by vshcherb** [comment]
Original issue is fixed, it could work better with incline but at least it doesn't flow away

**Comment by DmitryAlexei** [comment]
https://github.com/osmandapp/OsmAnd/assets/116079541/4194000c-a86d-4ef7-8877-159a5363f1f3
