### ISSUE TITLE
Live update size adds today's size even if already summed

### ISSUE THREAD

**Issue by goldfndr** [osmandapp/OsmAnd#17556]
## Description
Sometimes, when editing, I'll download multiple times within a single day, as a spot-check to make sure I haven't overlooked / missed a change. After I've downloaded a live update, under specific conditions, it'll add the new size of today's updated download to the sum of live update downloads instead of first subtracting today's earlier download or doing a complete rescan of the sizes. Exiting and dismissing the app seems to correct the value, but only backing out seems to enable the bug.

Possibly related to #2809 and/or #2800.

### How to reproduce
1. Download a live update using an "Available maps" item's "Update now" button. Note the Update size.
2. Back ×4 to soft-exit, wait some time.
3. Return to the live updates tab [before midnight UTC].
4. Tap the refresh button (update all).
5. Examine the "Available maps" item.

### Actual result
The item's displayed update size has likely grown the full size of today's download. After multiple downloads, it increased to 10.9 MB for US Washington. Resetting (to 5) then performing these steps once shows 6.5 instead of 5, as today's download is ~1.5 MB.

### Expected result
The item's displayed update size should only have increased the *delta* size of today's download; a restart (close, dismiss, launch) brings it down to 5 MB.

**Environment**
OsmAnd Version: 4.5.0#321m, released 2023-07-01 (android-full-arm64 nightly)
Android/iOS version: Android 13 with 2023-06-01 patch, One UI 5.1
Device model: Samsung Galaxy Z Fold3

**Comment by goldfndr** [comment]
Reproduced in OsmAnd~ 4.4.0#35147m, released: 2022-12-19 (on an LG V50 Thinq on Android 10).

**Comment by yuriiurshuliak** [comment]
After uploading the live update of the map, one size of the update is visible. After closing and opening the program several times or systematically pressing the "Update now" button, the size of the update increases.

OsmAnd~ 4.5.0#367m, released: 2023-07-10


<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/2a9669b3-9897-42d6-9ee9-a5fcb434aa8e"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/f845440e-31bb-4573-8757-55a52d339ccb"  width="300" height="auto"/> </th>
  </tr>
</table>

https://github.com/osmandapp/OsmAnd/assets/127092082/90f63e46-013a-40ce-8822-6b13cd7db03e

**Comment by vshcherb** [comment]
Yes all size is displayed even if not used, so you could see how much disc space is used.
