### ISSUE TITLE
Not showing path Suggestion on Pixel 7

### ISSUE THREAD

**Issue by TobiasHoefchen** [osmandapp/OsmAnd#17550]
## Description
OsmAnd+ does not show path suggestion when planning a route on my Pixel 7 device although it works perfectly on my old device (bq aquaris). In general it does not connect the points when planning a route so there is no way to check whether points are connected as desired. The connection appears once the track is stored.

### Actual result
![Screenshot_20230605-103900](https://github.com/osmandapp/OsmAnd/assets/82144255/76830132-1830-4c96-bf24-21e6acb18ab9)

### Expected result
Suggested path ist shown. 
![Screenshot_20230605-103913](https://github.com/osmandapp/OsmAnd/assets/82144255/588006b5-5dd6-4da1-9ec8-803adbf1e9ff)

**Environment**
OsmAnd Version: 4.4.7
Android/iOS version: 13

Device model: Google Pixel 7

**Comment by scaidermern** [comment]
Try switching between rendering engine v2 and v1. If you are using v2, is the height map enabled in the development plugion? If so, disable it, it can have some strange effects.

**Comment by TobiasHoefchen** [comment]
Thank you for your suggestion. I solved the issued by joining the beta and thus updating top 4.5.3.
