### ISSUE TITLE
Display "motorcar=designated" tag in POI Details

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd#17558]
# 🚀 feature request

### Description
OsmMand user encountered a problem, that tag "motorcar=designated" is not shown in POI Details (see screenshot).

Coordinates are 53.56461° N, 9.75574° E. 
https://www.openstreetmap.org/way/1180951662

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/96b49856-205e-4a6e-a052-0920cd7083df"  width="300" height="auto"/> </th>
  </tr>
</table>

The parking lot is mapped with "vehicle=no" and "motorcar=designated". Unfortunately, only the first parameter is shown when accessing the details of this lot as "Vehicles access: no"; the other parameter is not given, which leads to confusion because it seems like the parking lot is not accessible to vehicles at all (which would not make sense). 

### Describe the solution you'd like

**"Motorcar=designated" tag is shown in POI Details.**

**Comment by zipav** [comment]
OsmAnd Nightly 4.5.0#351m, released: 2023-07-06
Coordinates: `53.564610, 9.755740`
### Steps to reproduce:
- Search coordinates
- Tap on the Rissener Ufer/ Wittenbergen object 
- Scroll up to open details
- Check the result

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/ee5ceaa4-edbb-439a-95de-d1543d49b003"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by xmd5a2** [comment]
Fixed. How to test: download **Hamburg** map (not earlier than 2 august) and go to https://www.openstreetmap.org/way/1180951662

**Comment by DmitryAlexei** [comment]
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/250a4229-d432-4590-be7a-02cb31083fa5"  width="300" height="auto"/> </td>
  </tr>
</table>
