### ISSUE TITLE
Tracks > Share doesn't work

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#17567]
## Description
Export of tracks thru My Places > Tracks doesn't work.
> Tested on OsmAnd Nightly 4.5.0#345m, released: 2023-07-06

### How to reproduce
* Open **Menu** – **My Places** – **Tracks**
* Tap on **More** button on AppBar – **Select**
* Select ant folder, tap on **More** button – **Share**
* On **Export** screen, tap on **Continue**

### Actual result
<table style="width:100%">
  <tr>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/9365308/ac731a54-f733-4ef8-889b-adc32ca46f88"  width="300" height="auto"/>   </td>
  </tr>
</table> 

* Share sheet doesn't show up, share/export flow end without sharing

### Expected result
* Share sheet should be shows up

**Comment by zipav** [comment]
OsmAnd Nightly 4.5.0#351m, released: 2023-07-06

The issue is reproduced:

https://github.com/osmandapp/OsmAnd/assets/123936521/8530efab-d194-441d-b938-cdfb2b55f7ad

**Comment by dmpr0** [comment]
## Review
<table style="width:100%">
  <tr>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/9365308/ac9d3381-5714-44e2-b396-0fc3a66837f2"  width="300" height="auto"/>   </td>
  </tr>
</table>   


- [ ]  Lag

**Comment by vshcherb** [comment]
I don't have a lag issues with 40 MB
