### ISSUE TITLE
Bus route not displayed/available when choosing bus stop

### ISSUE THREAD

**Issue by tenzap** [osmandapp/OsmAnd#17568]
## Description

Select a bus stop (for example https://www.openstreetmap.org/node/11030390791) of this route https://www.openstreetmap.org/relation/16062405

Usually, OSMAnd will display the ref of the route with its color and display the route on the map if we click on the tag. But this doesn't happen here (no tag displayed, hence no possibility to display the route).

I couldn't find what could be wrong with the route. Except maybe that it's new, but I refreshed/downloaded the latest data (dated after the modification)

**Environment**
OsmAnd Version: 4.3.12
Android/iOS version: Android 12
Device model:  Xiaomi redmi note 9S

**Comment by DmitryAlexei** [comment]
As I see it, someone is continuing to modify this bus stop in OSM, so maybe in future map updates (early August) will be fine.

**Comment by vshcherb** [comment]
Lets see august maps

**Comment by vshcherb** [comment]
Yes geometry updates are not supported yet, we will add to the roadmap
