### ISSUE TITLE
Distance by tap line

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#17569]
## Description

We have two Profiles (for the first "Distance by tap" - on, for the second - off). 
For the first, we activate the line of Distance by tap, and we switch on the second Profile at this moment.
The line of Distance by tap is on the map always after that manipulation

### Expected result

For the second Profile the line must be not active.

**Environment**
OsmAnd Version: 4.5.0#351m
Android/iOS version: 13
Device model:  Samsung S22

https://github.com/osmandapp/OsmAnd/assets/44466116/305865ee-d824-41af-92c0-8022aa37167d

**Comment by yuriiurshuliak** [comment]
The "Distance by tap" feature was activated for the cycling profile but deactivated for the walking profile. When a distance line was created using the "Distance by tap" feature in the cycling profile and then the user switched to the pedestrian profile, where this function is not available, the line continued to appear on the map.

OsmAnd~ 4.5.0#351m, released: 2023-07-06

<table style="width:100%">
  </tr>
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/5ad76037-4f8e-4256-be48-b350a0460a4b"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by Nine-Tailed** [comment]
Tap to distance fires after zoom followed by map shift
See video in telegram chat:
https://t.me/ruosmand/130721
