### ISSUE TITLE
Driving region changes despite not set to automatic

### ISSUE THREAD

**Issue by Spielmops** [osmandapp/OsmAnd#17564]
## Description
I've been driving around the UK for almost 100 days now. In my settings I have set the driving region to "Europe" and not to "automatic". Nevertheless, the app switched to UK by itself. This usually only happened with the second navigation task right after the first.
### How to reproduce
Drive to UK with a German SIM
### Actual result
Frust
### Expected result
Smile
**Environment**
OsmAnd Version: 4.3.12
Android/iOS version: LineageOS 14
Device model: Cobot Max

Spielmops

**Comment by yuriiurshuliak** [comment]
First selecting the Europe region, then starting to lay a route in Great Britain, the region changes automatically, while it was not selected. Units of measurement are also automatically changed.
OsmAnd~ 4.5.0#351m, released: 2023-07-06

<table style="width:100%">
  </tr>
  <td> <video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/85ddceaf-c095-4561-9bd9-10a731309d3b"  width="300" height="auto"/>   </td>
  </td>
  </tr>
</table>

**Comment by yuriiurshuliak** [comment]
The issue has been fixed. When you choose the Europe region and begin plotting a route in Great Britain, the region doesn't switch automatically. Nevertheless, the widget continues to perform kilometer to mile conversions.

OsmAnd~ 4.6.0#637m, released: 2023-08-18


https://github.com/osmandapp/OsmAnd/assets/127092082/b0c73d8a-953e-4cab-9291-5e099f2f108f

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/d5d28762-83bb-493e-87cf-6c5c76afe24a"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/3db9fc89-ece4-427c-9fab-2e9b96c1341c"  width="300" height="auto"/> </th>
  </tr>
</table>
