### ISSUE TITLE
Map and compass button become blank sometimes

### ISSUE THREAD

**Issue by alex-osm** [osmandapp/OsmAnd#17562]

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/commit/7140650d6daf31baf9274d0a61236c90deffb2d2

**Comment by Velomeloman** [comment]
Issue haven't t fixed yet 
https://github.com/osmandapp/OsmAnd/assets/109347561/cdf0ccc0-125e-41a8-9502-6897887cf7ed

**Comment by DmitryAlexei** [comment]
@Velomeloman 
In the last nightly build?

**Comment by Velomeloman** [comment]
> @Velomeloman 
> In the last nightly build?

#344m after commit

**Comment by Velomeloman** [comment]
[logcat.log](https://github.com/osmandapp/OsmAnd/files/11968127/logcat.log)

**Comment by Nine-Tailed** [comment]
Confirm, OsmAnd~ 4.5.0#351m, дата выпуска: 2023-07-06.

**Comment by Velomeloman** [comment]
[logcat (1).log](https://github.com/osmandapp/OsmAnd/files/11979547/logcat.1.log)

**Comment by alex-osm** [comment]
@Velomeloman @Nine-Tailed Please try last nightly version

**Comment by Velomeloman** [comment]
Can't reproduce blank screen.

But empty areas flooded again.
![Screenshot_20230707_131240_net.osmand.plus.jpg](https://github.com/osmandapp/OsmAnd/assets/109347561/a2525616-5298-49fd-ac7d-a0bb290c2177)

**Comment by alex-osm** [comment]
Flooding was caused by recent changes. [Reverted](https://github.com/osmandapp/OsmAnd-core/commit/b09af0b4d136853ad36f52dd436bd75c992efdc4) today. 
Nightly version will be ready in 10-20 minutes
