### ISSUE TITLE
Deleting the downloaded maps on a fresh install after the automated change of the data folder

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#17576]
## Description

During a fresh install (again I have to do so, because #17290 is driving me really crazy by now) Osmand wants to change the data folder ("...shared memory... bla bla  ...not allowed anymore... ...press continue...")
But I can´t "press continue", because at the same time there is an information popup asking to permit or reject Osmands notifications. After "permitting", this requested "change data folder - dialog" is skipped and gone.

[edit] But also when tapping on "continue" there is no way to select another data folder, Osmand just continues with the "map download".

On the end of this fresh install, after downloading the first maps and the contour lines, Osmand wants to restart, to finally change the data folder ("...writing to external memory..." bla bla "...restart necessary...").

After this restart, the just a few moments before downloaded maps and contour lines are all deleted and have to be downloaded again.

And next, after this install the favorite´s color is set to standard again.
If I want my favorites in "my" certain color, then I´m loosing their symbols again... 
#17344 does not even have a label yet...
 
**Environment**
OsmAnd Version: 4.5.4
Android/iOS version: 13
Device model: Samsung S20+, Tab Act3

**Comment by sonora** [comment]
The overlapping notification dialog in combibatuon with the other dialog then dusappearing definitely sounds like a bug which needs fixing. An interim workaround for you could perhaps be:
- fresh install of the app
- do not open it, instead go to the Android system settings, Apps, OsmAnd, there grant the app all permissions
- Only now open the app and set the data storage, etc.

I would assume this order avoids any interim permision dialogs and their interference with the setup dialogs?

**Comment by Rowin63** [comment]
I dont know. At my last ray, there was no overlapping info-popup, though osmand continued with the map download, without letting me change the data folder.

**Comment by yuriiurshuliak** [comment]
After a new installation of the application, without giving any permission, we tried to reproduce this bug. Unfortunately, we didn't have an overlapping notification dialog in combination with the other dialog with similar messages. 

Try to grant file and media permission to the app immediately after the new installation. Also, after opening the application, you can skip loading the map and immediately change the memory settings to the desired ones. Menu → Settings → OsmAnd settings → Data storage folder

After selecting the correct folder, then try downloading the maps and contour lines again.

If the error cannot be resolved, please provide us with a step-by-step reproduction and video of the screen as the application crashes. Here is a link on how to record a video of the Samsung S20+ screen: https://www.samsung.com/au/support/mobile-devices/using-screen-recorder/

OsmAnd 4.5.4, released: 2023-07-04

https://github.com/osmandapp/OsmAnd/assets/127092082/b946b503-d7ce-45f7-8224-0d7d0692c273

**Comment by Rowin63** [comment]
Thanks for the detailed info. I'll do so at the next time I will HAVE to do a new install. At the moment Osmand keeps me busy with other things 😉👍
