### ISSUE TITLE
Url is not correct on Android Page

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#17572]
when I clicking on the link in OSMAND, the page is not found.

https://osmand.net/docs/user/plugins/osm-editing. (The Dot after "editing." is the problem)
.
https://osmand.net/docs/user/plugins/osm-editing (No Dot after "editing", then it works.)

![image](https://github.com/osmandapp/OsmAnd/assets/1042025/825fdc78-4b4e-475f-9bae-01ad58395889)

**Comment by JasperJJ** [comment]
This problem may also occur with other languages, since I believe they are also modified via Weblate.
When I look at Weblate (https://hosted.weblate.org/translate/osmand/main/en/?checksum=155a8ef11e59b3b1#translations), some of the translations have a space before the period to fix this problem.
