### ISSUE TITLE
Flickering dots of widget pages

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#17570]
## Description

when we move the map, dots of widget pages flick.

Environment
OsmAnd Version: 4.5.0#351m
Android/iOS version: 13
Device model: Samsung S22

https://github.com/osmandapp/OsmAnd/assets/44466116/dfbded57-bc41-4615-a05e-fae44f647ecc

**Comment by zipav** [comment]
OsmAnd~ 4.5.0#357m, released: 2023-07-07
[logcat (6).log](https://github.com/osmandapp/OsmAnd/files/11982868/logcat.6.log)

### Steps to reproduce:
- Configure screen 
- Enable widgets on the Right panel and Left panel
- Disable Transparent widgets
- On main screen move the map by gestures


https://github.com/osmandapp/OsmAnd/assets/123936521/575cff1c-c742-43bd-8b4e-c4fe780ae892
