### ISSUE TITLE
+4.5.4. is missing options in track appearance

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#17577]
## Description
options in "colors" and "track width" are missing
### How to reproduce
happens after a fresh install, but not at an update (all options are available then) (and does not happen in a fresh  4.4.7.)
Tried it two times, happens both times.
### Expected result

**Environment**
OsmAnd Version: +4.5.4
Android/iOS version: 13
Device model: Samsung  Tab Active 3

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/95540936/6522bbb4-6861-4dd0-a544-6eeb3fb8b430"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Rowin63** [comment]
Next try: did not happen when using "multiuser1", all options are available.

**Comment by yuriiurshuliak** [comment]
This case was tested immediately after the nightly and beta update. The problem could not be reproduced. Please try to check on the latest nightly version.

OsmAnd~ 4.5.0#373m, released: 2023-07-11


<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/5df25926-9bee-4a48-ba2a-916a2e3fb4e3"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Rowin63** [comment]
Thank you! 
But it did not happen again at the third try, now it is ok. So I´m not going to try it again ;-)
From my side this topic is closed.
