### ISSUE TITLE
PNG Format Error

### ISSUE THREAD

**Issue by saeedafshari8** [osmandapp/Osmand#1757]
Gradle build process generates the following errors:

AAPT err(1318574994): D:\Workspaces\Osmand\Osmand\res\drawable-large\warnings_speed_camera.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(398090252): D:\Workspaces\Osmand\Osmand\res\drawable-large\warnings_traffic_calming.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(400401267): D:\Workspaces\Osmand\Osmand\res\drawable-hdpi\ic_btn_wocheckbox_selected.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(1978638812): D:\Workspaces\Osmand\Osmand\res\drawable-hdpi\monitoring_rec_big.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(531008317): D:\Workspaces\Osmand\Osmand\res\drawable-mdpi\progress_orange.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(390840232): D:\Workspaces\Osmand\Osmand\res\drawable-mdpi\progress_green.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(1318574994): D:\Workspaces\Osmand\Osmand\res\drawable-hdpi\warnings_speed_bump.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(1318574994): D:\Workspaces\Osmand\Osmand\res\drawable-hdpi\progress_orange.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(2145470175): D:\Workspaces\Osmand\Osmand\res\drawable-hdpi\ic_overflow_menu_light.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(2145470175): D:\Workspaces\Osmand\Osmand\res\drawable-hdpi\pedestrian_small.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(586890467): D:\Workspaces\Osmand\Osmand\res\drawable-hdpi\progress_blue.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(990612815): D:\Workspaces\Osmand\Osmand\res\drawable-hdpi\progress_green.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(1677588771): D:\Workspaces\Osmand\Osmand\res\drawable-hdpi\ic_btn_wocheckbox_notselected.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(400401267): D:\Workspaces\Osmand\Osmand\res\drawable-hdpi\warnings_speed_camera.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(1473622162): D:\Workspaces\Osmand\Osmand\res\drawable-mdpi\progress_blue.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(1621073843): D:\Workspaces\Osmand\Osmand\res\drawable-large\warnings_speed_bump.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(452763849): D:\Workspaces\Osmand\Osmand\res\drawable-hdpi\ic_btn_wocheckbox_pushed.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(1621073843): D:\Workspaces\Osmand\Osmand\res\drawable-hdpi\monitoring_rec_small.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(1473622162): D:\Workspaces\Osmand\Osmand\res\drawable-hdpi\monitoring_rec_inactive.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(400401267): D:\Workspaces\Osmand\Osmand\res\drawable-mdpi\progress_grey.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(1677588771): D:\Workspaces\Osmand\Osmand\res\drawable-hdpi\pedestrian_small_white.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(452763849): D:\Workspaces\Osmand\Osmand\res\drawable-hdpi\progress_grey.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited

**Comment by vshcherb** [comment]
Good question for forum, but it is not reproducible with our builds

**Comment by saeedafshari8** [comment]
I used Android Studio 1.3 and Gradle 2.7. Maybe it helps.
