### ISSUE TITLE
weighbridge tag spelled wrong (as "weightbridge")

### ISSUE THREAD

**Issue by elgaard** [osmandapp/OsmAnd#17581]
## Description
According to the wiki
https://wiki.openstreetmap.org/wiki/Tag%3Aamenity%3Dweighbridge
and existing weighbridge is spelled without a "t".

However 
https://github.com/osmandapp/OsmAnd-resources/blame/9103399a10dac46bc8914258244745155ff3605c/rendering_styles/map-legend/default.legend.xml#L818

has the condition: `value="weightbridge"`

### How to reproduce

In OsmAnd search for "weighbridge"

### Actual result
With English as display language no category match is found. It is not possible to search for weighbridge.

With other display languages a matching category seems to be found. But it is still not possible to search for weighbridges because the translated name is mapped to "weightbridge" which return
no search results or only a few, with a misspelled value.

### Expected result

Getting a match for the category "weighbridge" and a search returning
the closest of the 5461 weighbridges tagged in Openstreetmap for maps installed.

**Environment**
OsmAnd Version:
Android/iOS version:
Device model:

**Comment by elgaard** [comment]
Also note that is was implemented as a result of #10419
Which has the title "Add amenity=weightbridge", but then links to the correct wiki page:
https://wiki.openstreetmap.org/wiki/Tag%3Aamenity%3Dweighbridge

**Comment by elgaard** [comment]
Note that weighbridges are also created with the wrong spelling using OsmAnd. I have corrected some in OSM already.

**Comment by xmd5a2** [comment]
Fixed. 
How to test: https://www.openstreetmap.org/way/776433417
Map: Luxembourg (check 1 hour after posting this post)
