### ISSUE TITLE
Slow rendering of some places

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#1758]
http://www.openstreetmap.org/way/103192781#map=17/32.15629/34.79840 (road only map) - 15 zoom
searching 88 ms
rendering 2500 ms
292 of 1340 visible objects

**Comment by xmd5a2** [comment]
searching 100ms, rendering 300, 1700 of 1200 objects visible

**Comment by vshcherb** [comment]
Strange enough can't reproduce any more
