### ISSUE TITLE
differentiate between shelters and public transport shelters.

### ISSUE THREAD

**Issue by cricri-du-lauragais** [osmandapp/OsmAnd#17584]
Hello, on the map it is not possible to differentiate between generic shelters (amenity=shelter) and road transport shelters (amenity=shelter + shelter_type=public_transport).
this is annoying because many shelters in the wild are just marked "amenity=shelter" and to see them on the map you have to see all the public transport shelters.
Thanks for all your hard work.

**Comment by DmitryAlexei** [comment]
1. amenity=shelter + shelter_type=public_transport [OSM](https://www.openstreetmap.org/way/160596000) 160k objects according to [Taginfo](https://taginfo.openstreetmap.org/tags/shelter_type=public_transport#overview)
2. amenity=shelter [OSM](https://www.openstreetmap.org/node/1672073872) 480k objects according to [Taginfo](https://taginfo.openstreetmap.org/tags/amenity=shelter#overview)


<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/84c014e9-9cb4-464d-b528-5e7cdf6f9cc1"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/76869f89-3618-4506-a5d8-1fbe1599716b"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by xmd5a2** [comment]
Fixed by https://github.com/osmandapp/OsmAnd-resources/commit/0ef8f61379a5b20a018156d0d232a23a79e223cf
but proper fix of https://github.com/osmandapp/OsmAnd/issues/17310 required
