### ISSUE TITLE
Settings incomplete in Dutch system version

### ISSUE THREAD

**Issue by CleanFuels** [osmandapp/OsmAnd#17586]
## Description

The settings menu of a Dutch display language install (4.4.7) does not give option of changing display language.

Unlike settings of UK display language install. 

### How to reproduce

See attached pics
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/35400352/c12de754-46f3-41f3-93e7-1a900fbc28bc"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/35400352/caf2d684-da6a-4d11-9852-ff2466b227eb"  width="300" height="auto"/> </th>
  </tr>
</table>

### Actual result

User cannot set display language from NL to UK, if NL is her starting position.

### Expected result

**Environment**
OsmAnd Version: 4.4.7
Android/iOS version:
Device model:

**Comment by scaidermern** [comment]
Could be #16938 - which is fixed in version 4.5.
Maybe try the 4.5 beta from the playstore.

**Comment by DmitryAlexei** [comment]
Now the application language must be changed in the Android system settings

**Comment by dmpr0** [comment]
Starting Android 13, language selection should be done in System Settings https://support.google.com/android/answer/12395118?hl=en

**Comment by CleanFuels** [comment]
> Could be #16938 - which is fixed in version 4.5. Maybe try the 4.5 beta from the playstore or a nightly.

Indeed, might be the same.

Where are the nightly's? Or 4.5 beta?

**Comment by CleanFuels** [comment]
> Starting Android 13, language selection should be done in System Settings https://support.google.com/android/answer/12395118?hl=en

Super! Great! Thx

**Comment by scaidermern** [comment]
> > Could be #16938 - which is fixed in version 4.5. Maybe try the 4.5 beta from the playstore or a nightly.
> 
> Indeed, might be the same.
> 
> Where are the nightly's? Or 4.5 beta?

See https://osmand.net/docs/versions/nightly_versions/

The latest nightly build is at https://download.osmand.net/latest-night-build/OsmAnd-default.apk

The official beta version can be downloaded from the playstore if you join the beta program (there should be a button to do so):
* https://play.google.com/apps/testing/net.osmand.plus
* https://play.google.com/apps/testing/net.osmand
