### ISSUE TITLE
unwanted left turn instruction 

### ISSUE THREAD

**Issue by pordini** [osmandapp/OsmAnd#17580]
# 🐞 routing report

### Routing engine

- [X] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Car
### Start and end points

From 51.21706° N, 6.80517° E
To 51.22039° N, 6.80841° E
### Actual and expected routes
Actual route contains a left turn and left lane instruction. This is wrong, as you would end up in the Albertstrasse.
![Screenshot_20230708-224053](https://github.com/osmandapp/OsmAnd/assets/12774050/99464aae-52ff-4a64-801f-8012e141a42e)

Expected route has no turn and lane suggestion is going straight. 
### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

OsmAnd+ 4.5.4, released: 2023-07-04
</code></pre>

**Device and Android/iOS version:**
Pixel 5, Android 13
**Maps used (online or offline):**

- [X] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**

**Comment by ivanPyrohivskyi** [comment]
Fixed map data for [OSM way 17580](https://github.com/osmandapp/OsmAnd/issues/17580) .
Changes  are available in Live Update or will be in new August maps.

**Comment by DmitryAlexei** [comment]
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/88bb8d67-a23e-45dc-8127-52aa9905b4ff"  width="300" height="auto"/> </th>
  </tr>
</table>
