### ISSUE TITLE
Water rendering for quarry lake

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#17590]
## Description

Not rendering for Android and iOS version water for quarry lake

### How to reproduce

https://www.openstreetmap.org/relation/7487050#map=16/50.0365/19.9111

<img width="372" alt="image" src="https://github.com/osmandapp/OsmAnd/assets/44466116/01026b3d-052e-44e1-844b-2e7894fd46b2">

<img width="376" alt="image" src="https://github.com/osmandapp/OsmAnd/assets/44466116/b85418ce-3ec9-4ff6-aa18-d30bbf9f80a6">

**Environment**
OsmAnd Version: 4.5.0#351m
Android/iOS version: 13
Device model:  Samsung S23

Map date - 1 July 2023

**Comment by xmd5a2** [comment]
Fixed. New maps required.
