### ISSUE TITLE
crash on raster map download (IllegalStateException)

### ISSUE THREAD

**Issue by quantenschaum** [osmandapp/OsmAnd#17599]
## Description

OsmAnd crashes when trying to download tiles of a raster map.

### How to reproduce

- Add a raster map source with zoom levels limited from 8 to 16 (inclusive)
- set map storage to SQLiteDB
- select this map as map source
- long tap > actions > download map
- :boom: 

### Actual result

OsmAnd crashed with [exception.log](https://github.com/osmandapp/OsmAnd/files/12016429/exception.log)

```
java.lang.IllegalStateException: Slider value(17.0) must be greater or equal to valueFrom(11.0), and lower or equal to valueTo(16.0)
```

### Expected result

It does not crash.

### Workaround

Set max. zoom level of the map source to `>=17`.

**Environment**
OsmAnd Version: 4.5.4 4504
Android: 13
Device model: Nokia X20

**Comment by yuriiurshuliak** [comment]
By enabling the Online Maps plugin, changing the Map Source, Overlay map and Underlay Map, choosing Microsoft Hybrid and changing the zoom levels limited from 8 to 16 (inclusive). And taking the following steps: long tap > actions > download map, the application crash was not noticed.

Please attach a crash video and export of your settings. Also try to see if it will reproduce in the latest nightly version.

OsmAnd 4.5.4, released: 2023-07-04
OsmAnd~ 4.5.0#382m, released: 2023-07-12

<table style="width:100%">
  </tr>
  <tr>
    <th>Nightly version</th>
    <th>Beta version</th>
  </tr>
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/a7212974-2206-4c43-ba4b-25920a505d94"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/8fe8bd5a-2a18-4f47-baaf-dbd5eb29aac2"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by quantenschaum** [comment]
The exception is about the initial value of the zoom range slider AFAIU, so it's not clear to me how this is affected by the storage backend of the map tiles: :shrug: but it seems to trigger the exception.

**Comment by yuriiurshuliak** [comment]
By performing all the previously performed actions and changing the Storage format to SQLiteDB file, the bug was reproduced.
After taking the following steps: long tap > actions > download map, the application crashes.

OsmAnd~ 4.5.0#391m, released: 2023-07-13


https://github.com/osmandapp/OsmAnd/assets/127092082/5231a865-1bcd-4e5f-927c-e54fd81bcc0d
