### ISSUE TITLE
Version info now missing

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#1759]
Somehow we lost the build/release version info on our "About" screen. The About screen is where users would by convention expect this kind of info. For the nighties the Edition date is also essential for debugging user reports, just like we used to have it, see https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/activities/MapActivityActions.java#L721

**Comment by vshcherb** [comment]
There is new design and it is there, but lets keep an eye on it. In new release it will be back.
