### ISSUE TITLE
Show more pressure lines

### ISSUE THREAD

**Issue by spaanse** [osmandapp/OsmAnd#17609]
# 🚀 feature request

### Description

Currently in the weather plugins you can show the isobars, lines of similar pressure. However there are very few of them. This is because the values range typically from 1000 hPa to 1030 hPa, but they are drawn in an interval of 10.
So from low to high pressure you will only see 4 lines.

### Describe the solution you'd like

Decrease the interval from 10 hPa to 1 hPa.
I suspect that the app chooses the intervals proportionally to the size of the values, but that clearly does not work here.

### Describe alternatives you've considered

Selecting other units for pressure has the same spread out bars.

**Comment by xmd5a2** [comment]
Fixed
![Screenshot_2023-07-28-11-16-17-625_net osmand plus](https://github.com/osmandapp/OsmAnd/assets/5829014/58b8aefd-c74b-4a4f-bde5-291413f21888)
![Screenshot_2023-07-28-11-16-32-712_net osmand plus](https://github.com/osmandapp/OsmAnd/assets/5829014/ac52f5db-07ee-406a-9d25-87d36c628bc4)

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#609m, released: 2023-08-13
For mmHg and hPa it's ok, isobars are shown in 2 measurement units. 
**Not ok for inHg** - data are rounded to whole numbers and are not always shown on the map (screenshot 3)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/7b27951d-d1fc-4f9f-9ea1-2b4a06400c12"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/4f43c210-bfde-4307-91de-b65eeab3c953"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/03e76fb8-e7b3-4a8c-b28f-fe4284d711d3"  width="300" height="auto"/> </td>
  </tr>
</table>
