### ISSUE TITLE
Search for specific public transport routes

### ISSUE THREAD

**Issue by Elaborendum** [osmandapp/OsmAnd#17616]
# 🚀 feature request

### Description

Sometimes I just simply need to know where a certain bus stops instead of planning a route. For example, when I'm already on a bus not on OSM with a planned destination and need to know if a registered bus has a stop near my destination.

It mostly happens when I'm going somewhere for the first time or I rarely go to. Most of the main bus routes in my city are on OSM so I mostly just need to find those.

### Describe the solution you'd like

Some way to see a list of all available public transport routes and the ability to search for a specific one. OSMand can already highlight a specific route but I mean this as a way to find them to search for a specific one by name instead of searching it on the map and guessing.

### Describe alternatives you've considered

Maybe the completed Public Transport routing would fix this issue for me or perhaps there is an existing app out there that covers this.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/5924

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/5924
