### ISSUE TITLE
Search for bars too in poi_cafe_and_restaurant

### ISSUE THREAD

**Issue by l2212** [osmandapp/Osmand#1761]
In Italy (but not only there) "bar" and "cafe" are basically  the same thing, so people in OSM used both for the same kind of places. It could be possible to include bars (poi_bar) in the list of POIs you find when clicking on "Cafe and restaurant"? Right now only "poi_cafe" points and restaurants appear.

![2015-10-01-17-11-48](https://cloud.githubusercontent.com/assets/11271324/10226574/257451e2-6860-11e5-81bb-8edb9a9c5d21.jpg)

**Comment by vshcherb** [comment]
In a fact they are different, we suggest to use search bar and type "bar" there

**Comment by l2212** [comment]
Yes but the problem is, in the translations (at leas, in Italian and Sardinian) the word is the same.

Cafe = Bar (it) =Tzilleri (sc)
Bar = Bar (it) = Tzilleri (sc)

So if I use "Bar e Ristoranti" or "Tzilleris e ristorantes" i already expect to find them, while a lot would be missing.
