### ISSUE TITLE
GraphHopper Custom Models

### ISSUE THREAD

**Issue by CesiumCs** [osmandapp/OsmAnd#17617]
# 🚀 feature request

### Description

I live in a suburb in the States where a large portion of routes mapped by normal systems keep me on busy roads where there aren't sidewalks and the shoulder is too narrow to comfortably/safely walk on. I used GraphHopper to make a custom model that goes out of its way to keep me on less busy roads until I can get to a sidewalk, and I'd like to use it in OsmAnd. The current way of using the GraphHopper API makes a GET request to their /route endpoint, which supports most features but the [GraphHopper docs](https://docs.graphhopper.com/#operation/getRoute) explicitly state that you can't use custom models with that type of request.

### Describe the solution you'd like

Changing the GraphHopper API implementation to use POST requests and adding an optional field for supplying a custom model

### Describe alternatives you've considered

Using the GraphHopper web interface to create a GPX trace of my route ahead of time, importing it and following that

**Comment by scaidermern** [comment]
This ticket should go to the [GraphHopper git repository](https://github.com/graphhopper/graphhopper/issues). There is nothing the OsmAnd team can do about this.

**Comment by CesiumCs** [comment]
This isn't a problem on GraphHopper's end - they just have two different ways of requesting the data and OsmAnd just happens to use the one that doesn't support a specific feature. I don't think going to their issues to ask them to change their API just so a single piece of software can support it better without changing its own code would succeed.  I understand not wanting to implement this though as it's a niche feature of a niche feature, so I'll just end up doing it the long way I described. Thanks for your time with this issue.

**Comment by scaidermern** [comment]
Oh, in that case I simply didn't understand your request correctly. If GraphHopper already supports this then I guess this is a valid ticket.

Either way, I'm just a regular user. Not sure what the developers think about this.
