### ISSUE TITLE
Wrong data on precipitation widget

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#17618]
### Expected result

**Environment**
OsmAnd Version:
Android/iOS version:
Device model:

**Comment by vshcherb** [comment]
- [ ] Async data should be synchronized, so until data is received to widget it should show "-", so we don't see deprecated wrong data (margin of error is allowed 30 km - so we don't see "-" while we are moving the map)
- [ ] When weather screen is open it should zoom out map to visible data (13 zoom ? )
