### ISSUE TITLE
New Kazan metro logo

### ISSUE THREAD

**Issue by Glebzilla** [osmandapp/OsmAnd#17623]
Hello.
This week Kazan metro presented its new official logo.
I've received svg file only for Osmand. The use of the file in other locations and projects is currently not allowed.
Please update.
![subway_kazan_2023](https://github.com/osmandapp/OsmAnd/assets/7659970/5903185f-263f-4ef8-8c45-9504d029717b)

**Comment by xmd5a2** [comment]
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/61038a7c-298c-4481-8c10-6ca202f28634)
