### ISSUE TITLE
After enabling Time to destination widget, it isn't appearing on a screen on any nav. profile.

### ISSUE THREAD

**Issue by User1l0** [osmandapp/OsmAnd#17626]
### Expected result

**Environment**
OsmAnd Version: 4.3.12
Android/iOS version: 12
Device model:

**Comment by DmitryAlexei** [comment]
Please, try to update to the latest version of the app (try the beta version from Google play), your problem should be resolved in this issue https://github.com/osmandapp/OsmAnd/issues/17014.
If the bug persists, please add screenshots or short video.

**Comment by mikehgentry** [comment]
Could be the same as #17299 - check that you have a destination, and that your position is known.
