### ISSUE TITLE
Position jumps off during navigation

### ISSUE THREAD

**Issue by MiMoHo** [osmandapp/OsmAnd#17625]
## Description

The blue position arrow suddenly jumps off during car navigation approx. every 10 seconds.

### How to reproduce

Use car mode and navigation while driving on the road. 

### Actual result

The result is the blue arrow on a white screen, but the correct position returns half a second later and after a short map refresh, the navigation continues. I tested this on two independent Android 11 phones. Here's a sample:
https://github.com/osmandapp/OsmAnd/assets/37556964/8659085a-557b-4620-844b-081688215a51

### Expected result

The position must not suddenly switch about 200 meters off its actual position, so that the navigation is not interrupted.

**Environment**
OsmAnd Version: 4.4.7 (Amazon)
Android/iOS version: 11
Device model: Sony Xperia 5

**Comment by scaidermern** [comment]
Position also seems to be very sluggish.
Are you using rendering engine v1? If so, try to turn off Settings / Profile / General settings / Animate own position. Or try again with rendering engine v2.

**Comment by DmitryAlexei** [comment]
You can also try to change location source
https://osmand.net/docs/user/personal/global-settings#location-source
