### ISSUE TITLE
going from “desert” to “off-road” and back disables “road quality”

### ISSUE THREAD

**Issue by vsassone** [osmandapp/OsmAnd#17637]
## Description

going from “desert” to “off-road” and back disables “road quality”

### How to reproduce

set a profile A with map “desert” and option “show road surface” and a profile B with map “off-road” and option “road surface integrity. 

Change profile from A to B and then back to A

### Actual result

the road surface markings are not shown when back to A

### Expected result

They should be

**Environment**
OsmAnd Version: 4.4.7
Android/iOS version: 12
Device model: Samsung active tab 3

**Comment by zipav** [comment]
OsmAnd Nightly 4.5.0#421m, released: 2023-07-18
### Steps to reproduce:
- Configure map
- Select profile Car
- Map style: Desert
- Details: Show road surface
- Configure map
- Select profile Bicycle 
- Map style: Offroad
- Details: Road surface integrity
- Configure map
- Select profile Car
- Select profile Bicycle 
- Select profile Car back

When switching from the Bicycle profile back to the Car profile, the Show road surface setting is not displayed

https://github.com/osmandapp/OsmAnd/assets/123936521/48fc448c-2169-47ac-9dd1-4dae59f4d8ef
