### ISSUE TITLE
Feature request: avoid country / avoid toll roads

### ISSUE THREAD

**Issue by efi99** [osmandapp/OsmAnd#17633]
When planning a route it would be nice to have an option to avoid specified countries, as well as toll roads within _specified_ countries.
Thanks.

**Comment by DmitryAlexei** [comment]
@efi99 
You can deactivate maps, and they won't be used for offline routing:
- go to Download maps > Local > tap unnecessary map > choose deactivate
If this solved your problem, click "close issue"

**Comment by efi99** [comment]
Yes, this is a good way to avoid the country. 
But the toll roads can only be excluded manually one by one, if I don't want to avoid the country anyway.

**Comment by DmitryAlexei** [comment]
You can exclude all toll roads from routing using *avoid road* option in navigation settings (see https://osmand.net/docs/user/navigation/routing/car-based-routing#route-parameters---car)

**Comment by efi99** [comment]
This is true. 
But the situation is this: the driver is visiting several countries, but some of them only for a short distance, so he does not want to pay for example a 10-day motorway sticker for 1 day (or even 10 min!) / 20 km, so wants to avoid this 20 km of motorway only in this country.

**Comment by scaidermern** [comment]
How about telling OsmAnd to avoid a specific road explicitly? This is already possible.

Of course, for this solution the user has to know beforehand which road OsmAnd will take. But isn't this still better than having for each navigation setting a list of countries for which they should apply? This sounds like a horrible UI.

**Comment by efi99** [comment]
Why would the UI be horrible?
I'm planning a road, the route leads through a couple of countries at most, and I will disable toll roads for the given country with a switcher. So the disable would be available at route planning, not in advance. 
This is a fairly common feature in other navigation applications. (see image)
![Screenshot_2023 07 17_11 32 35 988](https://github.com/osmandapp/OsmAnd/assets/62113872/5bb32fd6-b272-4886-b39c-266ba7817793)

**Comment by scaidermern** [comment]
> To avoid country you can delete map or archive so you will route through wanted maps

This doesn't cover the second part of the request: Avoid toll roads in specific countries.

**Comment by vshcherb** [comment]
That's indeed not possible for now but sounds quite sophisticated to be implemented in near future

**Comment by ronnystandtke** [comment]
I would absolutely love this feature! My use case: I am living in Switzerland (and already paid the Swiss motorway vignette) and want to travel to Belgium but want to avoid the toll highway sections in France. Right now this is impossible to plan with the otherwise really great OsmAnd app.

**Comment by dalekirkwoodcerebria** [comment]
I love Osmand but can't use it because of this. I have a Vignette for Slovakia, not for Austria, so I have paid tolls in SK not in Austria. I want to avoid the toll roads only in Austria. I don't want to delete any maps or do it manually.

Sygic does this and so does Waze. Waze has a much nicer approach than Sygic. This is my biggest blocker to not switch from Waze/Sygic to an Osmand subscription

**Comment by DmitryAlexei** [comment]
@dalekirkwoodcerebria have you tried to use avoid specific roads option?
please see
https://osmand.net/docs/user/navigation/routing/osmand-routing#avoid-specific-roads

**Comment by scaidermern** [comment]
> @dalekirkwoodcerebria have you tried to use avoid specific roads option?

This is certainly a workaround. But not a good one. It requires the user to research which roads are toll roads in order to tell OsmAnd to avoid them.
