### ISSUE TITLE
Incorrect turn lanes

### ISSUE THREAD

**Issue by Prusaker** [osmandapp/OsmAnd#17635]
After executing the issue [17238](https://github.com/osmandapp/OsmAnd/issues/17238) turn lanes are now displayed incorrectly in other places on the map. I found two places:

1) [https://www.openstreetmap.org/#map=19/53.83938/27.50270](https://www.openstreetmap.org/#map=19/53.83938/27.50270)
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/32092837/0ed3106f-f035-4928-a355-392ad664fe85"  width="300" height="auto"/> </th>
  </tr>
</table>

2) [https://www.openstreetmap.org/#map=19/53.14254/24.80188](https://www.openstreetmap.org/#map=19/53.14254/24.80188)
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/32092837/6dfc40af-bbaf-4e28-9efc-3d47ed4e9dcc"  width="300" height="auto"/> </th>
  </tr>
</table>

There are no errors in the osm data. In OsmAnd version 4.4.7 and earlier, everything shows correctly.
I think, what this bug appeared after executing the issue [17238](https://github.com/osmandapp/OsmAnd/issues/17238).

**Comment by yuriiurshuliak** [comment]
In the latest version, the turning lanes for these sections of the route are displayed correctly. Try the latest nightly version.

53.14266, 24.80208
53.83941, 27.50262
OsmAnd~ 4.5.0#416m, released: 2023-07-17


<table style="width:100%">
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/911cb77f-2640-464f-9a65-798b3b5aa00a"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/c620bbf4-53dc-4e75-b004-27a7314d583f"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by Prusaker** [comment]
I tried now lates nightly build (4.5.0 #418m released 2023-07-17).
Turnlanes errors remain the same.

**Comment by Prusaker** [comment]
![Screenshot_20230717-173511](https://github.com/osmandapp/OsmAnd/assets/32092837/04a7bac9-7f54-4607-ae0f-1c164d4765e1)
Please try to set destination point similar as my screenshot. And the error will appear.

**Comment by DmitryAlexei** [comment]
@Prusaker OsmAnd~ 4.5.0#418m, released: 2023-07-17

Start point 53.84087° N, 27.50359° E
If the end point 53.83942° N, 27.50094° E - **Lanes instructions are correct**
If the end point 53.83944° N, 27.49749° E - **Lanes instructions are incorrect**

<table style="width:100%">
  <tr>
    <th> 53.83942° N, 27.50094° E </th>
    <th> 53.83944° N, 27.49749° E </th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/a5382aeb-200a-42e5-ac25-827d93e24cd1"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/2bc7355c-b40c-4358-b75a-6f0cabae3adb"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by ivanPyrohivskyi** [comment]
First case - yes, bug detected, will fix.

Second case - need to fix data. Need fix tag _turn:lanes:forward=left|through_ to _turn:lanes=left|through_ for way https://www.openstreetmap.org/way/519964020 . This will set turn lanes instruction for both directions, now is work only for opposite direction.

**Comment by ivanPyrohivskyi** [comment]
Try to fix.

Right, slight right:
<img width="400" src="https://github.com/osmandapp/OsmAnd/assets/1040293/3b9a9e0d-3d57-4100-b0b0-93909fd8295c" /> <img width="400" src="https://github.com/osmandapp/OsmAnd/assets/1040293/8165a0c7-0a82-4a0c-bc5c-f3d2a39c4b3d" />

Right, through:
<img width="400" src="https://github.com/osmandapp/OsmAnd/assets/1040293/108bfadd-6e6d-49be-8ff8-b4d9b1c81b7d" /> <img width="400" src="https://github.com/osmandapp/OsmAnd/assets/1040293/23c8ddf1-73f1-4774-a149-7cd5e5466704" />

**Comment by vshcherb** [comment]
C++ left
