### ISSUE TITLE
Wrong categories shown in all POIs everywhere, when whole building accommodates one POI

### ISSUE THREAD

**Issue by Erlendur22** [osmandapp/OsmAnd#17632]
Hello, 

I recently reported a problem about POI's with the Internet_access tag don't show the correct POI category but rather show Internet_access as category, hence the helpful menü "Nearby POI Internet_access" is shown in the POI menu instead of the correct category of the POI.
I think, someone is already assigned to it and I hope to see some changes. That's the link to the problem: 

https://github.com/osmandapp/OsmAnd/issues/17335

Something similar I want to describe here. Similar, because same behavior BUT it does not affect single POI nodes. It effects buildings which have the POI included in the building tags. 

## Description

Let's take a look at screenshot No. 1
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104724692/1326e347-8641-4e3d-875a-03d3acf43af9"  width="300" height="auto"/> </th>
  </tr>
</table>

Those three stores are located in Gibsons, BC, Canada. I added and updated them. They are located in three different houses of which  all of them are solely retail buildings, hence the tag building=retail was used. The stores don't have an own node, for they use up the whole house.

In screenshot No. 2 
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104724692/3f90026c-53b9-450c-a545-3c04ec2e1777"  width="300" height="auto"/> </th>
  </tr>
</table>
the clothing store at this specific zoom level does not show the category "clothing store" and the symbol is the one of the building category. The two other restaurants at that zoom level show "building" as category too but at least the symbol is the right one  (no photo of that).

One zoom level out the restaurants show at least the right symbol but still "building" as category (No. 3 and No. 4) 
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104724692/341f297c-0c2c-42b4-93df-b9509fe0fd35"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/104724692/8f009278-629b-431d-b1c4-741a1abdc6e2"  width="300" height="auto"/> </th>
  </tr>
</table>

but the clothing store neither shows the right symbol nor the right category (No. 5)
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104724692/af4fef96-7726-4ef5-9b47-df5976baad63"  width="300" height="auto"/> </th>
  </tr>
</table>

The last screenshot is from another zoom level where Osmand asks, what POI I want to select. 
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104724692/e07e0164-5c68-4aa0-b30d-b10c36de5501"  width="300" height="auto"/> </th>
  </tr>
</table>
The one restaurant POI has the category of "building" but the right symbol and a fourth POI (a cafe not described in this example) does not even show a cafe symbol but just the "building" symbol and category. 

This is not correct at all and the information shown on the map is wrong and misleading!

The same problem as I described in the beginning of my post gets produced due to the wrong categorization, 
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104724692/c1754a8f-b802-410f-b8f4-3355d024e5dd"  width="300" height="auto"/> </th>
  </tr>
</table>
the "Nearby POI" feature is "building" rather than restaurant, clothes store or cafe. No one cares about a nearby building but the right category of restaurant or bakery would be helpful. 

The strange thing is, if one uses the Osmand search and look for restaurant, cafe, clothes store, the POI show up correctly in the search 
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104724692/90818762-01a8-437d-8768-99a4b62ee407"  width="300" height="auto"/> </th>
  </tr>
</table>
(see Brassica and The Mad Hen") and clicking on it shows the right category 
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104724692/ed3713e8-8db8-4ca0-bc82-ba3bce11a5ef"  width="300" height="auto"/> </th>
  </tr>
</table>

Is this behavior intentional? If yes, then it is very confusing, for no one cares about a building but rather about the POI which it accommodates. 

### How to reproduce
Pretty much this occurs everywhere where a POI is the building and not a separate node. A store, a shop, a restaurant, anything which is written in the building tag . 

### Actual result
As described, Osmand plots the category "building" for every POI which is the building instead of the correct  POI category. It is logical, that it is a building where the POI is located, so it does not have to be shown as category. 

### Expected result
Right category AND symbol when browsing the map and seeing a POI and clicking on it. The symbol in the map is correct but everything else not. 

**Environment**
OsmAnd Version: 4.3.5
Android/iOS version: 9
Device model: Samsung Galaxy S8 SM-G950F

Any ideas or explanations? Will this be fixed along with the other problem in my other post or is this something different someone has to look  into? 

Greetings Erlendur

**Comment by Erlendur22** [comment]
A short addition to it. It happens to other POIs too. E.g. churches. Look at the world famous Pantheon in Rome. OK, it is a temple rather than a church, but all other churches show the same behavior. 
The Pantheon appears just as a building but it should be a monument. The churches appear as buildings but they should be "Places of Worship".

![Screenshot_20230716-130355_Gallery](https://github.com/osmandapp/OsmAnd/assets/104724692/baaac620-0abc-4796-aa16-deb953bbf2ba)

Browse over a map and click on churches or other places. You will see, they all show building as category rather than "place of worship", "monument", "temple", etc.
Hence the menu of "Nearby POI Building" is not wrong but it is meaningless. 

The Pantheon is shown as a building, rather than a monument, as it appears in the Osmand search. If you look for Pantheon in the Osmand search, it appears as Monument. Clicking on it leads one to the correct Pantheon menu with the correct symbol and category. 

That is for sure a bug and affects widely Osmand as source for information and helpful guide while traveling. :-(

**Comment by DmitryAlexei** [comment]
The problem you describe has probably already been solved as part of the work on your previous issue https://github.com/osmandapp/OsmAnd/issues/17335. 
Please read this https://github.com/osmandapp/OsmAnd/issues/17335#issuecomment-1635709844, and see if everything is ok.
Below this comment there is a map, that you can download and check if the fix works correctly in the beta or nightly versions of the app.

**Comment by vshcherb** [comment]
I think we just fixed it
