### ISSUE TITLE
Wrong priority of text labels in Newquay at some zooms

### ISSUE THREAD

**Issue by mikehgentry** [osmandapp/OsmAnd#17638]
## Description

In Newquay in Cornwall UK a particular point of interest ('The Island') takes precedence over the name of the town at certain zoom levels (11 - 12, though if you zoom in / out from there it's still incorrect until you pan sometimes). 

**Environment**
OsmAnd Version: United Kingdom Southwest 2023/07/01, OsmAnd + 4.5.5
Android/iOS version: 11
Device model: Xcover 4s

**Comment by DmitryAlexei** [comment]
[50.4158506, -5.0830376](https://www.openstreetmap.org/#map=18/50.4158506/-5.0830376)

**Comment by yuriiurshuliak** [comment]
To recreate the bug, increase the zoom level to 11-12 in Newquay, Cornwall, UK, and observe that "The Island," a small rocky outcrop off the town's coast, is given higher priority than the actual town.



OsmAnd~ 4.5.0#416m, released: 2023-07-17


https://github.com/osmandapp/OsmAnd/assets/127092082/6ddfc5c4-3ff8-4208-ad3f-18438f8d70c0

**Comment by xmd5a2** [comment]
Fixed but in some places there can be side effects when island in reality is more important that town name. Ideally text should be additionally filtered by area.
![Screenshot_2023-07-28_10-32-32](https://github.com/osmandapp/OsmAnd/assets/5829014/d8a622a2-ad3c-456a-aa03-bff9b45e55fe)

**Comment by yuriiurshuliak** [comment]
The bug has been rectified in the current version, and now the town of Newquay is correctly given higher priority.

OsmAnd~ 4.6.0#592m, released: 2023-08-09


https://github.com/osmandapp/OsmAnd/assets/127092082/aebdd628-8a22-4cd6-a567-c9b0899d8d87
