### ISSUE TITLE
Differentiate street name from suburb

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#1764]
When looking at the street names we can see the suburb/district in parentheses:

![Street names](http://i.imgur.com/hgLAx4f.png)

Could the suburb/district name have a smaller font size and/or be displayed in italic, so it could be easily distinguished from the street name? (ie, the street name is more important, thus it should standout).

**Comment by vshcherb** [comment]
This is going to be redesigned in new search (not 2.3 release) and it is not clear yet what will it look like.

**Comment by sonora** [comment]
Deprecated.
