### ISSUE TITLE
Incorrect navigation for mini roundabouts

### ISSUE THREAD

**Issue by Yogurt4** [osmandapp/OsmAnd#17647]
## Description

The navigation seems to omit mini roundabouts. Though they may be only painted so that large vehicles can take the turn, the same traffic rules apply as for regular roundabouts, like giving way to the one already in instead of yielding to the right, or making a large turn instead of a short arc to the left.

### How to reproduce

Drive through a crossing with a mini roundabout.

### Actual result

"Keep straight on", or "Haladjon egyenesen" in Hungarian.

### Expected result

"Drive in/through the (mini-)roundabout and leave at the second exit"

**Environment**

OsmAnd Version: 4.4.7
Android/iOS version: 101.191014.001
Device model: Xiaomi Redmi 8

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/3273
