### ISSUE TITLE
Speed shown in nmh despite the fact that settinds are for UK, miles/yards and Naulitical Plugin disabled...

### ISSUE THREAD

**Issue by vrtareg** [osmandapp/Osmand#1765]
Speed shown in nmh despite the fact that settinds are for UK, miles/yards and Naulitical Plugin disabled...

**Comment by vshcherb** [comment]
In boat mode ( and  used to be in aircraft mode as well) nmh is set by default.

**Comment by vrtareg** [comment]
I was in car mode




On Tue, 6 Oct 2015 8:19 am vshcherb <notifications@github.com> wrote:

> In boat mode ( and used to be in aircraft mode as well) nmh is set by
> default.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osmandapp/Osmand/issues/1765#issuecomment-145765980>.
>
-- 


Regards,
Areg

**Comment by jkufner** [comment]
Do you realize that for most people nmh is completely useless unit? It is relevant only to people who actually sail on sea and even then I'm not sure how many of them does not use metric system. Nautical mode is very useful on rivers, where user is in canoe or something like that.
