### ISSUE TITLE
Navigation stops once disconnected from car

### ISSUE THREAD

**Issue by crypto-rsa** [osmandapp/OsmAnd#17666]
## Description
When I am connected to Android Auto with active navigation, as soon as I disconnect from the car, navigation stops.

### How to reproduce
1. Connect to Android Auto
2. Start navigation
3. Disconnect from AA by unplugging the USB cable (this happens to me often by accident)

### Actual result
Navigation stops and I need to enter the origin and destination again.

### Expected result
Route continues to be displayed on the screen even without AA connected.

**Environment**
OsmAnd Version: 4.4.7
Android/iOS version: Android 13
Device model: OnePlus 5T

**Comment by DmitryAlexei** [comment]
You could try using history (https://osmand.net/docs/user/navigation/auto-car#history).
or is your route not saved there either?

**Comment by crypto-rsa** [comment]
Well the destination is saved in the history but that's not the point. Why does the navigation need to be stopped in the first place?

**Comment by vshcherb** [comment]
That's a duplicate known issue https://github.com/osmandapp/OsmAnd/issues/16977

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/13351
