### ISSUE TITLE
show gpx-points with different colors

### ISSUE THREAD

**Issue by osmvermesser** [osmandapp/Osmand#1766]
i Import sometimes poi by gpx and they will Show by red markers.

the problem is, that poi with different kinds all will be red.

it would be nice to have the possibility to set a userdefine Color to the gpx-files.

a friend told me that this this was integrate in an older version - now not.

regards Jan

**Comment by vshcherb** [comment]
In coming UI it is possible, for existing version it is possible to set only in the file itself.
