### ISSUE TITLE
Map rotates around when vehicle stops

### ISSUE THREAD

**Issue by crypto-rsa** [osmandapp/OsmAnd#17667]
## Description
During navigation I have the orientation mode set to "in the direction of travel" which works correctly. However, as soon as the vehicle stops, the map starts to rotate around.

### How to reproduce
1. Start navigation
2. Make sure orientation mode is set to "in the direction of travel"
3. Stop the vehicle

### Actual result
Map rotates around.

### Expected result
Map stays oriented in the latest known direction of travel.

**Environment**
OsmAnd Version: 4.4.7
Android/iOS version: Android 13
Device model: OnePlus 5T

**Comment by mikehgentry** [comment]
Probably a duplicate of #17053

**Comment by crypto-rsa** [comment]
Yes, I think so. Thanks!
