### ISSUE TITLE
When Importing gpx points into favorites - choose which favorites group

### ISSUE THREAD

**Issue by QJKX** [osmandapp/OsmAnd#17661]
# 🚀 feature request

### Description

When importing a gpx file Osmand offers to add it to favorites.

with lots of existing favorites and lots of favorites in the gpx it's hard to remove or replace the imported pois afterwards.

### Describe the solution you'd like

I would like the importer to offer to create a new favorites group for the contents of the gpx file.

It should default to a merge (current behaviour) when the filename is the same osmand uses for exporting the favorites group.
It should default to a merge for a small number of points (less than 5)
otherwise it should default to a new group based on the filename.

Alternatively the wording should be clearer.
Instead of `Import as favorites`, `Merge with favorites` Thid would imply a more irreversible operation.

Another alternative is to make imported gpx points behave more like favorites.

### Describe alternatives you've considered

Import as gpx layer.
Unfortunately the gpx points aren't available to select from when planning a route like favorites are.

The current workaround is to rename my favorites group before importing the gpx into a new, empty, favorites group.

**Comment by tradavyvy** [comment]
This has similarities with #14514 I think.

**Comment by QJKX** [comment]
@tradavyvy, it's the same area of the program.

#14514 is about how what you see in osmand relates to physical files.
On the other hand this feature request does not have an opinion on the disk format of osmand's internal favorites storage.

**Comment by QJKX** [comment]
@tradavyvy although in your proposed implementation the import would basically be copying a gpx file into osmand's favorites directory.

**Comment by tradavyvy** [comment]
Yes, and a favourite group would just be a gpx file. No difference in how OsmAnd treats them.

**Comment by vshcherb** [comment]
You need to import GPX first and then select group and save to favorites.
![telegram-cloud-photo-size-4-5891136860598680602-y](https://github.com/osmandapp/OsmAnd/assets/1042025/b7b3e180-7d10-48bd-9ca3-4c518c0e51c8)
