### ISSUE TITLE
Incorrect right turn lane guidance

### ISSUE THREAD

**Issue by TheSnoozer** [osmandapp/OsmAnd#17671]
# 🐞 routing report

### Routing engine

- [X] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Routing profile car, avoid toll roads

### Start and end points

```
start=48.771592,8.226689
end=48.783166,8.203391
```

https://osmand.net/map/?start=48.771592,8.226689&end=48.783166,8.203391&type=osmand&profile=car#19/48.77212/8.22577

### Actual and expected routes

Navigation in OSMAnd makes the suggestion to use the right lane going into the "Lange Straße" (turn slight right). However that suggestion is incorrect, one should only use the two straight ahead roads to the "Europastraße".

From OsmAnd directly:
![photo_2023-07-20_11-16-27](https://github.com/osmandapp/OsmAnd/assets/6849390/1ddacbef-3c85-4eaf-be3b-8f1ad7c0dce0)

From https://osmand.net/map/?start=48.771592,8.226689&end=48.783166,8.203391&type=osmand&profile=car#19/48.77212/8.22577
![image](https://github.com/osmandapp/OsmAnd/assets/6849390/b7fc2f97-42eb-4d03-a103-321d090d77af)

What also is weird is that the side roads are labeled with "B 500", however only the "Europastraße" should carry that label.
![photo_2023-07-20_11-27-10](https://github.com/osmandapp/OsmAnd/assets/6849390/c02e9a85-81ac-4454-8255-d60c1459fa61)

### Is this a regression?

No idea

## 🌍 Your Environment

**OsmAnd Version:**
Map data last updated 01.07.2023, Map Rendering V1

<pre><code>
Device : RE513CL1
Brand : realme
Model : RMX3241
Product : RMX3241EEA
Build : RMX3241_11_F.06
Version : 13
App Version : OsmAnd+
Apk Version : 4.4.7 4407
</code></pre>

**Device and Android/iOS version:**

**Maps used (online or offline):**

- [X] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**
Let me know.

**Comment by TheSnoozer** [comment]
The weird B 500 that are attached to the side roads might be able to be explained by an incorrect relation attached to them. I have removed that via https://www.openstreetmap.org/changeset/138754815

**Comment by vshcherb** [comment]
Probably this can't be fixed by app and only by the data fix - https://www.openstreetmap.org/node/32198584. So way should be split around this node and lanes proposed [TL;C|C|TSLR]. In that case C will be selected and displayed correctly.

In any other case we have conflicting situations with other junctions where Straight lane actually means Turn left later on.

To summarize: we can't fix with algorithm for now.

**Comment by TheSnoozer** [comment]
Thanks for your input! I see now why osmand would suggest the turn lanes the way it did.

I fixed the map data now via:
https://www.openstreetmap.org/changeset/138770570
and simplified the intersection via https://www.openstreetmap.org/changeset/138770701

That IMHO should be all needed and follows your suggestion.

**Comment by vshcherb** [comment]
Will test on new maps in 10 days.

**Comment by TheSnoozer** [comment]
On the OSMAND-Map it still seems to suggest to Turn slightly right despite (C,TL|C|TSLR)

https://osmand.net/map/?start=48.771592,8.226689&end=48.783166,8.203391&type=osmand&profile=car#19/48.77212/8.22577

![image](https://github.com/osmandapp/OsmAnd/assets/6849390/7f426760-4d78-4657-bdc2-55d3deb3af6a)


Any suggestions?

**Comment by vshcherb** [comment]
Add tests

**Comment by TheSnoozer** [comment]
Thank you!

**Comment by DmitryAlexei** [comment]
Turn lanes are correct now:
- on the map https://osmand.net/map/?start=48.771592,8.226689&end=48.783166,8.203391&type=osmand&profile=car#19/48.77199/8.22506

<img width="446" alt="image" src="https://github.com/osmandapp/OsmAnd/assets/116079541/61891551-285e-4c34-bb0b-47f8f09d033d">

- and on OsmAnd~ 4.6.0#698m, released: 2023-08-30. Coordinates are [48.7718843, 8.2259005](https://www.openstreetmap.org/#map=18/48.7718843/8.2259005)
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/111dff58-f863-4830-a81b-710aa39d3506"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/99e63d77-5498-4936-ace0-790ccad8c3a4"  width="300" height="auto"/> </td>
  </tr>
</table>
