### ISSUE TITLE
"highway=path" into "highway=footway" when "foot=designated" exists

### ISSUE THREAD

**Issue by cricri-du-lauragais** [osmandapp/OsmAnd#17674]
Hello, in the "rendering_types.xml" you convert "highway=path" into "highway=footway" when "foot=designated" exists, I think this is a mistake, in my country (France) a path can be marked pedestrian (foot=desiganted) and be legally authorized to motorized vehicles when it is a cadastral road even if over time it has become narrow, motorcycles for example can circulate legally as long as a prohibition is not indicated by a sign and a bylaw.
I think that a highway=footway is exclusively pedestrian and by definition forbidden to motorized vehicles.
Thank you for your work.

**Comment by xmd5a2** [comment]
Fixed.
How to test: download **France_pays-de-la-loire_europe** map (not earlier than 2 august) and check if [this way](https://www.openstreetmap.org/way/23562936) is rendered as path not footway
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/048e383c-ea8d-4d55-96d1-963a5c259b45)

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#609m, released: 2023-08-13  
https://www.openstreetmap.org/way/23562936
highway=path is rendered as path (see https://osmand.net/docs/user/map-legend/osmand#highways)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/31ef08b4-ef83-4359-b58e-fb28a26eef6d"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/36210e73-7120-46f9-84bc-ea7efd6df3dc"  width="300" height="auto"/> </td>
  </tr>
</table>
