### ISSUE TITLE
missing icon of highway=emergency_access_ponts 

### ISSUE THREAD

**Issue by osmvermesser** [osmandapp/Osmand#1767]
following i send by email to osmand-contact-address.

in the category emergency it is possilbe to Show positions of emergency_access_ponts  by circle markers.

other objects will be Show by Icon - but not emergency_access_ponts 

reagards Jan

**Comment by xmd5a2** [comment]
I have no idea how this icon should look like

**Comment by Zahnstocher** [comment]
@xmd5a2
http://osm-icons.org/wiki/File:17005.svg

**Comment by osmvermesser** [comment]
prefers in green - so my opinion.

**Comment by xmd5a2** [comment]
Added but only for POI layer (and POI search)
