### ISSUE TITLE
plan a route  with map markers. Cannot save the resulting Track

### ISSUE THREAD

**Issue by fixifoxy** [osmandapp/OsmAnd#17688]
How I proceeded:
open Map markers
2 map markers (Start and Destination) are shown.
Click "More"
among the offered options I chose: 
"Plan a route".
Route is shown using the selected profile.
In the upper right corner = options.
Options=
   Navigation
  Make round trip
 Sort by.
No possibility is offered to save the new  calculated track 
for riding the other day or  to test other track alternatives with different map marker lists.
Shouldn´t  save as new track be added?

**Comment by DmitryAlexei** [comment]
On the last step tap **Navigation** and using [route details](https://osmand.net/docs/user/navigation/setup/route-details#share--export-actions) you can save or share your newly created route.
