### ISSUE TITLE
Flickering icons and street names

### ISSUE THREAD

**Issue by pordini** [osmandapp/OsmAnd#17689]
## Description
There is flickering of the motorway icons above a certain speed. Also seen it happen with street names but those I did not record.

(following https://github.com/osmandapp/OsmAnd/issues/15983#issuecomment-1627628935_)

### How to reproduce
Seen on the motorway at around 100 km/h but also seen at lower speeds. No further info at this time.

### Actual result

https://github.com/osmandapp/OsmAnd/assets/12774050/5e39de2c-5483-4624-a197-65a1d16049cf

### Expected result
No flickering 

**Environment**
OsmAnd Version:OsmAnd+ 4.5.4, released: 2023-07-04
Android/iOS version: Android 13
Device model:  Pixel 5

**Comment by scaidermern** [comment]
Another user reported flickering road names (watch the yellow road) : https://t.me/OsmAndMaps/41653
Not sure if these two issues are related.

**Comment by razor74** [comment]
I have the same problems, but for me flikering is on streets names. Aoears and dissapear and for precision circle around gps arrow -is flikering too.

**Comment by vshcherb** [comment]
Flickering icons is an issue of course.

**Comment by vshcherb** [comment]
https://www.openstreetmap.org/way/44849338#map=16/49.3230/10.2070

**Comment by vshcherb** [comment]
We need to wait for fix https://github.com/osmandapp/OsmAnd/issues/17731 (simulation and route line)

**Comment by vshcherb** [comment]
Actually flickering was not reproduced with latest version, so other issues are referenced here https://github.com/osmandapp/OsmAnd/issues/17731#issuecomment-1653630343

**Comment by razor74** [comment]
Flickering with latest version.

vin., 28 iul. 2023, 13:41 vshcherb ***@***.***> a scris:

**Comment by razor74** [comment]
Another screen recording with loaded route in the latest version which i
reveived last night. Screen flickering when i stay withouth move.

vin., 28 iul. 2023, 15:25 Razvan ***@***.***> a scris:

**Comment by vshcherb** [comment]
Is it 4.5 version? It shouldn't flicker and we can't reproduce it yet especially standing still. We keep monitoring user feedback but didn't get similar reviews yet

**Comment by razor74** [comment]
Hello. Maybe will help this. Flickering  is only on thin portion of the
road until that point marked by me on precedent screenshot with red where
road becomes thick. Flickering is only with route loaded and is somehow
timmed at one seccond. What osmand does from seccond to seccond ?

lun., 24 iul. 2023, 15:32 vshcherb ***@***.***> a scris:

**Comment by razor74** [comment]
Hi.
Nothing changed with latest version. But for shure it has to do with GPS
module. It interfere somehow with how Osmand read data from GPS receiver.
Gps is interogated one time per seccond. With GPS activated fllickering
start from seccond to seccond. With gps de-activated, flickering stops.
This problem apear only in 2,5 D. On 2D everything works normally.

lun., 24 iul. 2023, 15:32 vshcherb ***@***.***> a scris:

**Comment by vshcherb** [comment]
This is related to https://github.com/osmandapp/OsmAnd/issues/17731, location gets under the relief looks like and that needs to be fixed

**Comment by razor74** [comment]
Hi. With the latest update flickering problem dissapeared at last.

mie., 2 aug. 2023, 18:40 vshcherb ***@***.***> a scris:
