### ISSUE TITLE
"Topography" vs. "Terrain"

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#17685]
Due to some recent refactoring, we now use the expression "Terrain" for two different meanings: (1) as the overall header for anything around contour lines, hillshades, 3D Relief, etc,. and (2) as a synonym for just the Hillshade maps and layer:
![Screenshot_20230722-184055_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/845735/a2edecbf-3a1c-4e53-980f-dd62bfcb8211)

If you agree, I offer to clean this up by using "Topography" as the overall category header and keep "Terrain" only where Hillshade is meant (as also used in the v1 engine)?

**Comment by vshcherb** [comment]
That I think could have different views, I think Terrain is used in a header as a main feature of the topic.

In my opinion Terrain is associated quite strongly with 3D

**Comment by vshcherb** [comment]
I think "Terrain" meaning is perceived as "Perspective on non-flat round Earth" and "Topography" more as "science/knowledge about Earth non-flat specifics", may be I'm wrong

**Comment by sonora** [comment]
Essentially, topography is more overarching, referring to all sorts of (also manmade) surface features beyond just terrain/relief, while terrain (or relief, in my mind rather synonymous to each other), focuses on the lay of the land, which is the shape of the surface in terms of elevation, slope, etc.

I think we could best solve the issue by now using "Terrain"  as the new overarching new header, and for the different sub-features use as precise as possible terms describing each solution. So the screenshot above could look like this:

- **Terrain**
  -  **Contour lines**
Display from zoomlevel 12
  - **Hillshade / Slope**
None / Hillshade /Slope
  - **3D Relief**
Off / On

In the Configure map menu for engine v1 we would just use the 2 **Countour lines** and **Hillshade / slope** entries directly, as we have no overarching header there.

Would need to go through the strings file and our documentation and make sure we swap out occurrences of the expression "Terrain" where we used it to refer to just Hillshade alone.

**Comment by sonora** [comment]
Right, I will take this on and create the relevant PRs.

**Comment by dmpr0** [comment]
We can't release with those changes, undo all changes, I don't see this task in task in sprint

**Comment by sonora** [comment]
It's a systematic but rather simple string change, consistently implementing this naming pattern through all screens and related strings:

![Screenshot_20230726-140153_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/845735/f85959cc-96a8-4cb9-b3d5-15fe90134937)

Hope you can consider to merge for the release, would create more clarity than the recently introduced multi-use of the term "Terrain" we had introduced 4 days ago:
- "**Terrain**" as the category header for all terrain-related functionalities and maps (this is the one I propose to keep).
- "**Terrain**" was previously also used unnecessarily as synonym for our "**Hillshade/Slope**" maps (I eliminated this).
- On the Download screen we also use "**Terrain map**" synonym for the v2 "**Heightmap**" download. (I had also eliminated this, but it is not as necessary as the bullet above).

**Comment by sonora** [comment]
I have re-submitted it as a PR for your review here: https://github.com/osmandapp/OsmAnd/pull/17728.

**Comment by vshcherb** [comment]
Commented,  it might be not that easy to fix it in the end, so we need to be careful

**Comment by sonora** [comment]
We just need to decide what the target strings for this screenshot are: https://github.com/osmandapp/OsmAnd/issues/17685#issuecomment-1651684812. I can adjust the PR to make things consistent then throughout the app and documentation. (Screenshot shows my current suggestion.)

**Comment by dmpr0** [comment]
All needed string was added before changes.

**Comment by sonora** [comment]
@dmpr0 Sure, but my driver for this issue is to de-duplicate our use of "Terrain", see yellow dots in the screenshot at the very top. 😉

**Comment by vshcherb** [comment]
Yes, @dmpr0 agreed that you can change header to "Topography" but than you need to change it in Plugin name as well. Though my opinion is to keep duplication and that means 3 people / 3 opinions. For consensus 2 votes are needed

**Comment by sonora** [comment]
Hey Victor and Dmytro, I do not want to force any opinion on anybody here , and you surely agree we can save our energy for more functionally pressing improvements. :wink:

So it sounds like all 3 of us can agree to let this rest as is (with the current duplication of "Terrain" in section header and one sub-category)? We can always re-visit later, should we find it worth!

(I will go through the documentation once more and make sure it reflects what we have in 4.5.8.)

**Comment by vshcherb** [comment]
Well, I think your idea was to give name Topography to the section which is also fine (that I've thought as initial proposition), but then please make name of the plugin "Topography Plugin" (not contour lines plugin)

**Comment by sonora** [comment]
right... first impulse is sometimes the best... :wink:

- So we call the plugin "**Topography**" - done here: https://github.com/osmandapp/OsmAnd/pull/17791
- We call the OpenGL download type "**Terrain map (3D)**": https://github.com/osmandapp/OsmAnd/commit/570352db82165f7c96bae031d33be823f410e6f7

Quite like that - thanks! (Will adjust doc also).

**Comment by jojoob** [comment]
It's great to read that the wording will be made consistent! :+1: 

I have one additional request which I don't know if it belongs to the scope of this issue: The [documentation](https://osmand.net/docs/user/plugins/contour-lines/#setup) says in the setup section:

> 2. Download Contour lines, Hillshade, Slope, or Terrain map (3D) maps.

But with the latest android version (4.5.8) there are no slope or hillshade maps anymore in the download maps menu (or is it dependent on the country?) It would be nice if the documentation is clear about the relations: you want contour lines? download contour lines vector map! you want hillshades or slopes? download terrain map/heighmap! or hillshade/slope tile map for older versions.

**Comment by dmpr0** [comment]
> right... first impulse is sometimes the best... 😉
> 
> * So we call the plugin "**Topography**" - done here: [Rename Contour lines plugin to "Topography" #17791](https://github.com/osmandapp/OsmAnd/pull/17791)
> * We call the OpenGL download type "**Terrain map (3D)**": [570352d](https://github.com/osmandapp/OsmAnd/commit/570352db82165f7c96bae031d33be823f410e6f7)
> 
> Quite like that - thanks!
> 
> * EDIT: doc updated [osmandapp/web@f41e629](https://github.com/osmandapp/web/commit/f41e6291210adb4cdbb84f69a9557245de2e2320) , [osmandapp/web@967ddd1](https://github.com/osmandapp/web/commit/967ddd174064481340e91f2629ece674db2f8e21)

OsmAnd doesn't have "**Terrain map (3D)**"

**Comment by sonora** [comment]
@jojoob My current impression here: https://github.com/osmandapp/OsmAnd/issues/17794#issuecomment-1661743193

@dmpr0 Victor had the idea to call the new download type "**Terrain map (3D)**", I think it makes sense to denote its advanced capabilities vs. our conventional **Hillshade**/**Slope** raster downloads. I had a few hours ago given our doc article a revision and also adjusted the relevant screenshots, should show up on https://osmand.net/docs/user/plugins/contour-lines shortly.

**Comment by dmpr0** [comment]
@sonora new Terrain maps completely replace old ones. New Terrain map is used for: HillShade, Slope (Custom slope in the future), Elevation data for any point, 3D relief.

**Comment by sonora** [comment]
@dmpr0 Yes, true, but not for the v1 engine, right?

I like Victor's idea https://github.com/osmandapp/OsmAnd-Issues/issues/2046#issuecomment-1658715117 to mark by adding (3D) to the _download type_ the fact that the new download type also has the capability to provide the "**3D Relief**" feature, and not just our conventional "**Terrain**" features Hillshade/Slope, which we now have combined under our "Terrain" (without 3D) menu item?

**Comment by vshcherb** [comment]
"Terrain (3D) Maps" is fine for new maps

**Comment by sonora** [comment]
Ok, then we should be good now!

I believe I have also reviewed and updated all relevant user documentation on osmand.net, and aligned the screenshots. Maybe someone feels like proof-reading it, I will also go through it one more time, and I think we can close this issue.

There is one remaining observation noted here https://github.com/osmandapp/OsmAnd/issues/17798#issuecomment-1662072764.

**Comment by dmpr0** [comment]
> "Terrain (3D) Maps" is fine for new maps

Or maybe "Terrain (3D) (Currently only mountains Maps.tiff" because, "Terrain" is clearly not understandable.

**Comment by sonora** [comment]
Personally, I would not overexplain it. "Terrain map (3D)" is
- _short_,
- _common language_, and
-  _unique_,

which are 3 good criteria to find good app wording.

Uniqueness then always facilitates to locate and read up any details in the documentation.

**Comment by vshcherb** [comment]
Names and tiff files should stay 
Heightmap_Argentina_jujuy_southamerica.tif and name as Argentina ...  We need to change only 2-nd line description

**Comment by sonora** [comment]
PS: Of course, reason "Terrain" alone is not good enough is that we also use it as header for the conventional Hillshade / Slope raster maps, so it lacks the uniqueness criterion. :😉

**Comment by dmpr0** [comment]
> Names and tiff files should stay Heightmap_Argentina_jujuy_southamerica.tif and name as Argentina ... We need to change only 2-nd line description

Maybe we need to mention what type of glasses user need to view new "Terrain 3D Maps"?

**Comment by sonora** [comment]
@vshcherb Yes, changing the file name prefix would cause huge issues, so I limited all work to the display portion only.

One more consideration is the folder structure: We have the tif files in folder geotiff, but also have an additional folder heightmap with only the 3 parameter files?

**Comment by vshcherb** [comment]
heightmap is the old folder, so it's left over after migration to geotiff

**Comment by sonora** [comment]
My "heightmap" folder was re-created after deletion, as recently as July 29, so potentially we still have a open action here to deprecate it?
