### ISSUE TITLE
Routepoints disappear when editing a track

### ISSUE THREAD

**Issue by bizzco-jpb** [osmandapp/OsmAnd#17691]
## Description
A track is created: startingpoint and endingpoint. 
When a point is inserted after the startingpoint, then the endingpoint is gone.
When a point is inserted before the endingpoint, then the startingpoint is gone.

### How to reproduce
See above
### Actual result
A shorter track

### Expected result
A complete track with the new point in it.

**Environment**
OsmAnd Version: 4.4.7 (April 10 2023)
Device model: Cubot X30 T1, Android 10

**Comment by DmitryAlexei** [comment]
During the creation or editing of a track you can zoom in or out. So when zooming out, your track becomes smaller and for better perception some points become invisible. Only the points being edited and added remain visible.

<table style="width:100%">
  <tr>
    <th>Edit track</th>
    <th>Create track in plan a route tool</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/116079541/dfc3a8a0-d975-4d9a-92d5-8e485c0a6f8f"  width="200" height="auto"/></td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/116079541/8fbdb3a6-ceb3-43fd-99ae-7b2bdbb0b060"  width="200" height="auto"/></td>
  </tr>

Perhaps we need to describe this behavior in the documentation:
https://osmand.net/docs/user/plan-route/create-route#point-context-menu

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/plan-route/create-route/#create-new-route

**Comment by EugeneZmeuk** [comment]
**16-04-2024 Review**
