### ISSUE TITLE
Trip duration on single-lane roads (a.k.a. practical max. speed)

### ISSUE THREAD

**Issue by Yogurt4** [osmandapp/OsmAnd#17698]
# 🐞 routing report

### Routing engine

- [X] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Car

### Start and end points

From: Applecross Car Park, C1087, Milltown, Applecross, Highland, Scotland, IV54 8LR, United Kingdom
To: Applecross Road End, A896, Tornapress, Highland, Scotland, IV54 8XE, United Kingdom

[OSM permalink](https://www.openstreetmap.org/directions?engine=graphhopper_car&route=57.4337%2C-5.8139%3B57.4185%2C-5.6024)

But the same happens all around Isle of Skye, too.

### Actual and expected routes

The route itself is OK (there are no other options, anyway). However, the trip time is totally unrealistic. The planned route is calculated from the 60 mph generic speed limit for rural roads.

1. Both incline and sharp turns are omitted (as anywhere else). Implementing this will remain on the wish list I guess.

2. The most serious issue that it's a single-lane road (and is tagged as such in OSM). There is no way anyone can travel at 60 mph and use passing places at that speed. I was happy to reach 40 mph at some places.

I've tried to find some tagging to help OsmAnd in this respect. `maxspeed:practical` is a rejected proposal though.

To complicate matters, the edges of the asphalt are broken and deep. Unfortunately the `smoothness` tag does not apply to this scenario because the surface is smooth. Using `lanes=0.9` would describe the situation but it would anger a lot of data consumers. The `width` tag is no suitable again because there is enough space.

### Is this a regression?

No.

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>
4.4.7
</code></pre>

**Device and Android/iOS version:**

Xiaomi Redmi 8, Android 10 QKQ1.191014.001

**Maps used (online or offline):**

- [X] Offline maps offered within the OsmAnd app for download. United Kingdom Scotland, 1 June 2023.
- [ ] Online (tile / raster) maps

**Anything else relevant?**

**Comment by scaidermern** [comment]
> I've tried to find some tagging to help OsmAnd in this respect. `maxspeed:practical` is a rejected proposal though.

[`maxspeed:practical`](https://wiki.openstreetmap.org/wiki/Key:maxspeed:practical) is still the preferred option in OSM, I think. This tag is de-facto in use and recognized by several routing engines. It isn't wrong to add tags that haven't been approved, so please use it!

**Comment by DmitryAlexei** [comment]
Try changing the default speed in your navigation profile. The default speed (and also maxspeed) affects the arrival time. 
Also see https://osmand.net/docs/user/navigation/guidance/navigation-settings#default-speed

**Comment by Yogurt4** [comment]
> Try changing the default speed in your navigation profile. The default speed (and also maxspeed) affects the arrival time. Also see https://osmand.net/docs/user/navigation/guidance/navigation-settings#default-speed

It solves the issue only for this prepared part. But a whole trip would include B and A roads (2*1 lanes) as well that really can be travelled at 60 mph.

**Comment by scaidermern** [comment]
@Yogurt4 Do you have a suggestion how two-way single lane roads should be handled if there is no `maxspeed:practical` present? Use something like `maxspeed * 0.5` as the expected speed?

**Comment by Yogurt4** [comment]
@scaidermern That would definitely help.

However, if `highway=passing_place` itself adds some penalty (suggesting you may need to stop, like at a give way sign) - which it doesn't seem to do at the moment, then I'd recommend `maxspeed * 0.7` as the default expected speed for the road.

**Comment by Yogurt4** [comment]
I had another thought for `passing_place`s: The more frequent they are, the more penalty it would mean. However, in practice, having frequent passing places means only slowing down a bit - and avoiding the need for doing reverse, like for distant passing places. And it all depends on the traffic in the opposite direction.
