### ISSUE TITLE
Category search: include leisure=water_park

### ISSUE THREAD

**Issue by call-me-matt** [osmandapp/OsmAnd#17692]
Description

If searching for swimming pools, water parks should be included in search results.

How to reproduce?
Go to Eckernförde, Germany. [There is](https://www.openstreetmap.org/node/338517960) a water park. When searching for swimming pools in the category search, this is not shown.

OsmAnd Version: OsmAnd~ 4.4.7
Android/iOS version: 13
Device model: pixel4a

This issue is similar to https://github.com/osmandapp/OsmAnd/issues/16186

**Comment by DmitryAlexei** [comment]
This particular water park can be used (and is mostly used) as a pool, but in the OSM it's tagged as a water park. 
At the same time there are a lot of water parks, that do not have swimming pools and cannot be used for classical swimming.
So I would rather propose to change info in OSM.
