### ISSUE TITLE
Opening an Osmand link should open the app, not the website

### ISSUE THREAD

**Issue by letypequividelespoubelles** [osmandapp/OsmAnd#17695]
## Description

When you share a POI the link now opens the website OsmAnd instead of the OsmAnd app, even if offline. It wasn't the case beforre. (Few month ago maybe ?).

### Expected result

An OsmAnd link should open Osmand app.

**Environment**
OsmAnd Version: Fdroid 4.4
Android/iOS version:
Device model:

**Comment by DmitryAlexei** [comment]
@letypequividelespoubelles 
POI link opens in OsmAnd from Google Play

**Comment by DmitryAlexei** [comment]
Using search and POI link, you can also find needed object in OsmAnd downloaded from other sources.

**Comment by vshcherb** [comment]
Nightly build is not supported only beta/release Google Play cause of the package names

**Comment by letypequividelespoubelles** [comment]
If finally worked (with FDroid OsmAnd~ v 4.5.8) && Android 12:

- Android Settings
- App settings
- Open by Default : 
- Open compatibles links
- check everything, or at least download.osmand.net && osmand.net

Now, OsmAnd app opens osmand link.
