### ISSUE TITLE
OsmAnd shows wrong POI type when `Internet access: yes`

### ISSUE THREAD

**Issue by sedrubal** [osmandapp/OsmAnd#17704]
## Description

There is [a supermarket](https://www.openstreetmap.org/node/2244983406) which has `Internet access: yes` and which is not shown as supermarket but as "Internet access: yes". Editing this POI results in an empty changeset: https://www.openstreetmap.org/changeset/138947590

The same applies for hotels with Internet access

https://github.com/osmandapp/OsmAnd/assets/5571650/79b0bc9a-5054-4614-a559-f46940d2ae03

### How to reproduce

Inspect this POI in OsmAnd: https://www.openstreetmap.org/node/2244983406

### Actual result

The POI is shown as "Internet access: yes"

### Expected result

The POI should be shown as "Supermarket" and there should be a <kbd>Nearby POI "Supermarket"</kbd> button instead of a <kbd>Nearby POI "Internet access: yes"</kbd> button.

**Environment**
OsmAnd Version: 4.4.7
Android/iOS version: Android 12
Device model: FP4

**Comment by scaidermern** [comment]
Duplicate of #17335

**Comment by sedrubal** [comment]
You're right. I'm sorry.
