### ISSUE TITLE
Trip recording disappears after using Configure map > Tracks 

### ISSUE THREAD

**Issue by pkubowicz** [osmandapp/OsmAnd#17705]
### How to reproduce

1. Use the built-in Trip recording plugin to start recording, enable 'Show on map', make sure you see the red line
2. Open 'Configure map', make sure 'Tracks' is enabled, click '…', do something, click 'apply'

### Actual result

Red line from trip recording disappears from map. You need to go to Trip recording menu, where 'Show on map' is disabled (although you just enabled it), and re-enable it.

Every time you do something in 'Configure map > Tracks', you need to re-enable displaying trip recording.

### Expected result

I can start showing a track without affecting currently recorded trip.

This is a regression. Previously, it was easy to manage which tracks are displayed, and things you did not disable did not disappear out of their own.

**Environment**
OsmAnd Version: OsmAnd+ 4.4.7
Android/iOS version: Android 10
Device model: motorola one XT1941-4

**Comment by zipav** [comment]
OsmAnd Nightly 4.6.0#486m, released: 2023-07-26

### Steps to reproduce:
- Enable Trip recording plugin 
- Enable Trip recording widget
- REC
- Enable "Show on map"
- Start recording 
- Configure map
- Enable Tracks (or check if it's already enabled)
- Three dots button (⁝)
- Change appearance
- Apply

The track did not disappear from the map after doing these actions several times:

https://github.com/osmandapp/OsmAnd/assets/123936521/72109375-3be7-41d8-97ce-9ec6677c50d5

**Comment by pkubowicz** [comment]
Still happens. Here is my recording, showing settings of the plugin.

https://github.com/osmandapp/OsmAnd/assets/13313417/2eaef391-acb8-4304-b410-db031ab54153

**Comment by zipav** [comment]
OsmAnd Nightly 4.6.0#505m, released: 2023-07-28
OsmAnd 4.5.7, released: 2023-07-25
OsmAnd+ 4.4.7, released: 2023-04-10

Issue is not reproduced in OsmAnd Nightly and OsmAnd 4.5.7

Issue is only reproduced in OsmAnd+ 4.4.7


https://github.com/osmandapp/OsmAnd/assets/123936521/f95bf44d-d245-4a4a-9ff5-b7f144c404b5

**Comment by vshcherb** [comment]
Fixed in 4.5

**Comment by pkubowicz** [comment]
I received an update to 4.5 and trip recording works fine now. Thanks.
