### ISSUE TITLE
Support OSM / GMaps directions URL

### ISSUE THREAD

**Issue by bytesnz** [osmandapp/OsmAnd#17708]
## Description

OsmAnd only seems to support the older versions of the directions urls from google and osm. It would be great if it supported the latest versions of the urls

### Old URLs (though still used)
- https://maps.google.com/maps/dir//-41.156615,174.975586

### New URLs
- https://www.google.com/maps/dir/?api=1&destination=-41.156615,174.975586 (https://developers.google.com/maps/documentation/urls/get-started#directions-action)
- https://www.openstreetmap.org/directions?from=&to=37.2888%2C-122.1899 (obtained from going to osm.org, right clicking on point and clicking Directions to here)
- https://www.openstreetmap.org/directions?from=&to=37.2888,-122.1899 (as above, but replaced character code)
- https://osm.org/directions?from=&to=-40.9592,175.2704 (as above, but manually shortened, still valid)
- https://osm.org/directions?from=&to=-40.9592%2C175.2704

### How to reproduce
1. Ensure google maps is disabled and OsmAnd is enabled for handling url domains
1. Go to web site that has URLs
1. Click on links

### Actual result
Link should open in OsmAnd, but instead it just opens in the browser

### Expected result
Old URLs open in OsmAnd, but new URLs do not

**Environment**
OsmAnd Version: OsmAnd~ 4.2.7 & OsmAnd+ 4.2.7
Android/iOS version: 13
Device model: Samsung Galaxy Tablet and Phone

**Comment by DmitryAlexei** [comment]
Related with https://github.com/osmandapp/OsmAnd/issues/17695
@bytesnz Please, try OsmAnd from Google Play

**Comment by bytesnz** [comment]
I have also tried it with the latest version from the play store. I had to manually go through and select the google and osm domains in the supported web addresses setting and disable google maps from handling them to get the old format google url to work, but the new formats don't work.

I think #17695 was my initial problem (having to change the handler settings) but not to do with the new url formats.

**Comment by vshcherb** [comment]
These urls need to be first of all checked in search, I think navigation urls are not supported.

**Comment by bytesnz** [comment]
Yes, I have checked them in search as well.

- The old format (https://maps.google.com/maps/dir//-41.156615,174.975586) works.
- https://www.google.com/maps/dir/?api=1&destination=-41.156615,174.975586 works
- https://www.openstreetmap.org/directions?from=&to=37.2888%2C-122.1899 and https://www.openstreetmap.org/directions?from=&to=37.2888,-122.1899 etc do not (either show 0.0000, 0.0000 or 0.0000, -122.1899)

As OsmAnd seems to support the old urls, it would be great if it supported the new urls as well (hence my issue) as they are very handy to have open in your map app (as the google ones do on google maps).

Thanks

**Comment by zipav** [comment]
OsmAnd Nightly 4.6.0#508m, released: 2023-07-28
OsmAnd+ 4.4.7, released: 2023-04-10
The same results in both of applications

- https://maps.google.com/maps/dir//-41.156615,174.975586 - this link works
- https://www.google.com/maps/dir/?api=1&destination=-41.156615,174.975586 - opens a location in Oceania, not New Zealand
- https://developers.google.com/maps/documentation/urls/get-started#directions-action - nothing
- https://www.openstreetmap.org/directions?from=&to=37.2888%2C-122.1899 - show results 0.00000° S, 0.00000° W
- https://www.openstreetmap.org/directions?from=&to=37.2888,-122.1899 - the same result
- https://osm.org/directions?from=&to=-40.9592,175.2704 - the same result
- https://osm.org/directions?from=&to=-40.9592%2C175.2704 - the same result
- https://maps.google.com/maps/dir//-41.156615,174.975586 -  this link works
- https://www.google.com/maps/dir/?api=1&destination=-41.156615,174.975586 - opens a location in Oceania, not New Zealand
- https://www.openstreetmap.org/directions?from=&to=37.2888%2C-122.1899 - show results 0.00000° S, 0.00000° W
- https://www.openstreetmap.org/directions?from=&to=37.2888,-122.1899 - the same result

**Comment by zipav** [comment]
OsmAnd Nightly 4.6.0#751m, released: 2023-09-12


https://www.google.com/maps/dir/?api=1&destination=-41.156615,174.975586 - opens a location in Oceania, not New Zealand
https://developers.google.com/maps/documentation/urls/get-started#directions-action - no results
https://www.openstreetmap.org/directions?from=&to=37.2888%2C-122.1899 - shows location in SF, CA
https://www.openstreetmap.org/directions?from=&to=37.2888,-122.1899 - the same result
https://osm.org/directions?from=&to=-40.9592,175.2704 - shows location in New Zealand
https://osm.org/directions?from=&to=-40.9592%2C175.2704 - the same result
https://www.google.com/maps/dir/?api=1&destination=-41.156615,174.975586 - shows location in Oceania, not New Zealand
https://www.openstreetmap.org/directions?from=&to=37.2888%2C-122.1899 - shows location in SF, CA
https://www.openstreetmap.org/directions?from=&to=37.2888,-122.1899 - the same result

**Comment by bytesnz** [comment]
Awesome. Thank you
