### ISSUE TITLE
Ajouter à une  trace, lier les segments 

### ISSUE THREAD

**Issue by jol70** [osmandapp/OsmAnd#17718]
## Description
Bonjour, j utilise Osmand depuis plusieurs années en particulier car il me permet de crée des traces sur le terrain... Certes la mise en œuvre est imparfaite, mais me convenait bien..  et l effacement des données obsolètes.
Tout aussi gênant ça a été la gestion / correction assemblage  de l enregistrement des traces réalisées... Avec une quasi impossible impossibilite d ajouter de manière logique les traces entre elles incluant des morceaux recréés après coup. Si  ajouter fonctionnait parfaitement c est la fonction relier les traces qui a été une galère monstrueuse, systématiquement il choisissait de relier les départ d origine au bout de la partie que  j avais ajouter créant des croisements...pour m en sortie j ai due utiliser des logiciels sur ordi et couper de manière astucieuse les pistes puis de recréer le circuit. (plus de 8h00 d ordi). En fait je pense que c est un problème logiciel car même avec une trace propre venant de l ordi, il finissait par revenir au lien que j avais éliminé avec l ordi je ne sais pas d ou il avait en mémoire ces points antérieur car j avais effacé toutes les mémoires connues du téléphone et du logiciel... Il y a donc bien pour moi un big logiciel c est dire qu il faudrait pouvoir désigner avant d utiliser la fonction de relier les points, les points que l on veut lier car sinon il en fait comme il le sent.

Si vous savez comment transmettre aux chers développeurs... Merci

### How to reproduce
often.. Pour des petites traces sans mixité de profil c est OK.mais pour des segments long et multiples c est plus fréquents à très fréquents. Dans des versions antérieurs il est vrai c était systématique même pour des petites traces. Dans mon cas précis... Durant le parcours, j ai enregistré la trace et fait des pauses régulière. Osmand a sauvegardé les diverses segments que j ai ensuite corrigé pour pouvoir les assembler. Hors malgré mes sauvegardes avec des noms nouveaux pour ne pas perdre le segment d origine, lors de l ajout de la trace à une autre trace (OK pas de problème), mais lors de l utilisation de la fonction pour lier les segments Osmand retrouve et utilise les points effacés ou non apparent (effacement d un segment détaché du segment en cours qui fait que le point de départ se déplace sur le segment restant, mais le point de départ d origine devient cache). 
### Actual result
Sachant que l usage des fonction de découpe avant et après ne me permettait pas de reconstruire la partie virtuelle du segments, pour réussir à remettre en forme les liste de points, j ai due utilisr le logiciel routeconverter qui permet par copiage (copier coller) d ajouter directement les points à une trace affichée à l écran. 
### Expected result
1) Que l on désigne le point d arrivée et de départ du lien à réaliser avant action sur le lien 
2) que la mémoire soit purgée après chaque sauvegarde d une trace 
3) que les points actifs aujourd hui qui deviennent caches restent apparent jusqu a suppression. 
**Environment**
OsmAnd Version: Osmand +
Android/iOS version: 10 qkq1 2006.28. 002
Device model: Mi 10T...... MIUI 12.0. 9

En espérant répondre au mieux a vos demandes. Cordialement  jol70

**Comment by vshcherb** [comment]
Sorry please translate to English and if possible attach screenshots or videos to understand the issue

**Comment by jol70** [comment]
Sorry, m'y english is to bad...
Today I make a test.. I open a trace created with Osmand with gps prune and route concerter on a pc.. I think, i found the problème.. When I Import osmand trace to my pc vith gpsprune I have 2 traces one the same screen one with the initial trace before routing (the points i have created) and one with the point that Osmand created when i ask to route and i chosed the profil to route.
Some think similar arrive when I read the Osmand with route concerter on my pc with Linux.. The différence is  route convertir create two trace the original trace with only Some points and à second with all the point when Osmand route the original trace. To reproduce that exolain before  it s easy, but Osmand don t make à mistake on this case.. But if i have a lot of segments on the same trace (when I save the trace during my trip) and that i want to complète the trip then Osmand make à lot of mistake with the begining and the end of each segment (part) and Osmand can t recognize the succession of the segment...now if i can reproduire i make à vidéo, but it s not easy.. Sorry.

**Comment by jol70** [comment]
Please heure you can fond à Osmand trace read by gpsprune on my pc.. You can see the double trace in the same direction... The prouve that Osmand don t erase the old points when i save the new trace..

**Comment by jol70** [comment]
Sorry nothing show to me that i have put un photography. Why, how I can do.? Thanks

**Comment by jol70** [comment]
![Screenshot_2023-07-29-01-09-55-928_com miui gallery](https://github.com/osmandapp/OsmAnd/assets/79138181/84207cc5-2824-4d0a-96ed-e24bf2350e3d)
Here it s with à screen copy
