### ISSUE TITLE
Show on map acts differently in Selection mode and track actions

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#17717]
## Description
Selecting one or more tracks thru Selection mode and applying **Show on map** action, will enable visibility for those tracks on the map. Selecting **Show on map** action in track actions menu, will open track context menu without changing it visibility on the map.

<table style="width:100%">
  <tr>
    <th>Selection mode</th>
    <th>Actions menu</th>
  </tr>
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/cd869b27-aec9-4299-9ff5-159e1a969a26"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/d4a14e3c-7c92-4ca4-b78e-21ace49b7ce9"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
Not clear how it should be different probably action should have just different name "Show on Map" vs "Change visibility on map"

**Comment by sonora** [comment]
@dmpr0 , @vshcherb Does it actually make sense that we offer the 3-dots menu **twice**, one on each single line entry, and then one in selection mode as an overarching menu? And both menus offer partially the same, partially different actions??

In file managers it seems quite customary to offer actions **only in selection mode**. With the only exception being the tap on the item itself, which in a file manager :"opens" the item, on our Track screen the equivalent should likely be to view the item on the map?

In this fashion we could delete the 3-dots menu for individual items. If you want to re-use that space, an indication/button if a track is currently visible or not would be very useful instead.

**Comment by vshcherb** [comment]
I think people won't be ready to 3 dots and long tap selection in osmand, that could cause quite some stress that 3 dots disappeared, so for now with other changes it better to stay
