### ISSUE TITLE
Tap to distance is broken - not displayed during zoom

### ISSUE THREAD

**Issue by Velomeloman** [osmandapp/OsmAnd#17711]
Tap to distance fires after zoom followed by map shift. This behavior should not be.
See video in telegram chat:
https://t.me/ruosmand/130721

_Originally posted by @Nine-Tailed in https://github.com/osmandapp/OsmAnd/issues/17569#issuecomment-1645829096_

**Comment by vshcherb** [comment]
To do: with tap to distance on, line should be displayed while 2 fingers zoom (it displayed now with a delay and not in correct place sometimes)

**Comment by vshcherb** [comment]
Related

**Comment by Nine-Tailed** [comment]
Now again the distance appears when the map is zoomed.
OsmAnd~ 4.6.0#507m, Дата выпуска: 2023-07-28 https://github.com/osmandapp/OsmAnd/assets/12549744/148134e5-8f45-4add-a573-5f7d2f75db55

**Comment by vshcherb** [comment]
@Nine-Tailed yes that's correct we didn't want to hide it. Original bug that ruler was stuck between profile.
