### ISSUE TITLE
OsmAnd identifies ciruclar one way roads as roundabout

### ISSUE THREAD

**Issue by mem76** [osmandapp/OsmAnd#17715]
## Description

When traffic island are drawn as diffrent roads, the road in question sometime may become a circular way with the oneway=yes.

When this happens, OsmAnd treats this road as an intersection, even if does not have a junction=roundabout tag, as a roundabout.

### How to reproduce

With the map Vestland (Norway), navigate from "Mjåtveit" to "Frekhaug terminal"
### Actual result

Navigation :
"Roundabout: Take 2 exit and go Havnevegen"
### Expected result

"Turn right and go Havnevegen"

**Environment**
OsmAnd Version: 4.4.7
Android/iOS version: 12
Device model: Motorola moto g22  

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/16096631/c7ba82e7-d847-489d-a1c7-661a36d8cd3b"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by mem76** [comment]
The  road in the screenshot:
https://www.openstreetmap.org/way/747120753

**Comment by pordini** [comment]
This may be the same issue. The road was edited 10 months ago from roundabout to traffic circle. However, with the most recent maps OsmAnd still treats it as a roundabout.

https://www.openstreetmap.org/edit?changeset=128473626#map=19/52.06910/4.25102

**Comment by mem76** [comment]
> This may be the same issue. The road was edited 10 months ago from roundabout to traffic circle. However, with the most recent maps OsmAnd still treats it as a roundabout.
> 
> https://www.openstreetmap.org/edit?changeset=128473626#map=19/52.06910/4.25102
>

There is a slight difference. The junction at Laan van Meerdervoort is created with two ways and is marked with `junction=circular`.

Possible the same bug, but two different solution as traffic circles and roundabout has the same shape.

A circular oneway routing-path with:

- No juction tag
- `junction=circular`
- `junction=roundabout`

should all be treated differently when navigating.

**Comment by RZR-UA** [comment]
Road/Turn type bug is confirmed:

https://osmand.net/map/?start=60.518789,5.239019&finish=60.518953,5.240178&type=osmand&profile=car#19/60.51898/5.23973

**Comment by RZR-UA** [comment]
How to check Ways that might lead to the bug : https://overpass-turbo.eu/s/1Do9

**Comment by RZR-UA** [comment]
Possible method to find bad roundabout(s):

```
[bbox:{{bbox}}];

way
 ["oneway"="yes"]
 ["junction"!="roundabout"]
 (if:is_closed())
 (if:length()>10)
  
 (if: lrs_in(1, per_vertex( angle() < -60 || angle() > 60 )))

;
out geom;
```

In the other hand, mostly "good" roundabout(s):

```
[bbox:{{bbox}}];

way
 ["oneway"="yes"]
 ["junction"!="roundabout"]
 (if:is_closed())
 (if:length()>10)
  
 (if: ! lrs_in(1, per_vertex( angle() < -60 || angle() > 60 )))

;
out geom;
```

**Comment by vshcherb** [comment]
Based on analysis only 1-5% of missing roundabouts are determined by that method, 5-10% are probably could be dual roundabout and non roundabout and other 80% are not roundabout at all, so we need to delete this check. These 2 lines should be deleted - https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd-java/src/main/java/net/osmand/binary/RouteDataObject.java#L706

**Comment by RZR-UA** [comment]
> This may be the same issue. The road was edited 10 months ago from roundabout to traffic circle. However, with the most recent maps OsmAnd still treats it as a roundabout.
> 
> https://www.openstreetmap.org/edit?changeset=128473626#map=19/52.06910/4.25102

As for Turn Types (Navigation Instructions), OsmAnd treats junction=circular the same as junction=roundabout

So that, this is another case and it's not connected directly to the main subject of the Issue.

**Comment by dmpr0** [comment]
# Review 
* ToDo is missed

**Comment by vshcherb** [comment]
Todo here - https://github.com/osmandapp/OsmAnd/issues/17715#issuecomment-1812474486 (remove 2 lines of code).

Todo Explanation all circular oneway roads should be treated as roundabout (means we display in navigation roundabout sign) only if there is a tag roundabout in OSM.
