### ISSUE TITLE
Hillshading does not work (+SD card unmount)

### ISSUE THREAD

**Issue by mherrmann3** [osmandapp/Osmand#1771]
When I select the hillshading layer, and then pan around, OsmAnd+ shows no map info anymore - only a blank map... and the SD gets unmounted. The problem also occurs when no downloaded hillshade files are present in the tiles directory.

After mounting the SD card again, I cannot start OsmAnd anymore, it crashes. So, to let OsmAnd work for me again, I have to do the following:
 1. Mount SD card again
 2. delete the folder /storage/sdcard1/Android/data/net.osmand.plus/files/tiles (otherwise, OsmAnd will crash the next time I start it)
 3. Start OsmAnd
   * It shows the following message:
   "*/storage/sdcard1/Android/data/net.osmand.plus/files/regions.ocbf: open failed: ENOTCONN Transport endpoint is not connected)*"
   * Now, the SD card got unmounted again
   * UNTICK the hillshade layer

 4. Mount SD card again
 5. (no need to delete the tiles folder this time)
 6. Start OsmAnd, works (without my beloved hillshading) :-(

I did this now around 5 times. It always happens (and can be fixed) after this scheme.

Do you guys think it's an SD-related error? To be on a more safe side, I formatted the SD card on windows (exFAT, 128kb cluster). Still the same behavior.

I have a Sony Xperia Z1 Compact with CM12.1 (Android 5.1.1) and run the most recent OsmAnd+ version 2.1.1.

**Comment by OliverHaag** [comment]
Have the same problem on a Galaxy S2 with CM12.1 and the latest OsmAnd+ release...

**Comment by vshcherb** [comment]
We have issue with Hillshades, there were downloaded with wrong name and thus don't work. We are planning to release nightly build in several weeks, for now known workaround is to rename downloaded map to Hillshade_... (should start with Hillshade_)

**Comment by mherrmann3** [comment]
Still not working in the recent version. Even renaming " " --> "_" doesn't help.

**Comment by nibelungen** [comment]
+1
Removed the files, after the crash something is wrong with the sdcard - space is used but the maps does not appear have to check the files with an sdcard reader to find where they are now stored.

**Comment by NonnEmilia** [comment]
Still not working with my Sony Xperia Z3 Compact.
OsmAnd~ 0.3.4
Android 8.1.0

Renaming is not working, deleting the tile folder let me open OsmAnd again.
Curiously when OsmAnd try to add the hillshading layer seems to corrupt the SD card: the OS tells me "0 byte of 0 free" and every app using SD card stop working. Unmounting and re-mounting the SD card again the OS recognise it right.
