### ISSUE TITLE
Routing is ignoring temporary access-restriction of Way 37909210

### ISSUE THREAD

**Issue by Peter0** [osmandapp/OsmAnd#17710]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

car, save fuel, consider temporary restrictions
### Start and end points

Start: 50.72232 7.06267
Dest.: 50.72128 7.06150

### Actual and expected routes

I expected that Osmand respects the temporary access-restriction of https://www.openstreetmap.org/way/37909210 and will route a detour.
In reality, Osmand 4.4.7 routes straight through Way 37909210.
### Is this a regression?
Reportedly, 4.5.6 is also affected.

 Yes, the previous version in which this bug was not present was: ....

## 🌍 Your Environment

**OsmAnd Version:** 

<pre><code>~4.4.7
</code></pre>

**Device and Android/iOS version:**
Samsung J5, /e/OS, based on Android 9
**Maps used (online or offline):**
Germany, NRW, Reg.-Bz. Köln
Hourly updates active.

- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**

**Comment by vshcherb** [comment]
https://test.osmand.net/map?start=50.722241,7.061870&end=50.720910,7.060567&avoid=2426189467&type=osmand&profile=car#18/50.72151/7.06163
vs
https://test.osmand.net/map?start=50.722241,7.061870&end=50.720910,7.060567&type=osmand&profile=car#18/50.72151/7.06163

**Comment by Peter0** [comment]
Thanks. How do I find out in which version this commits appear? I think, "4 commits into [r4.5]" means one of the 4.5.X versions?

**Comment by vshcherb** [comment]
In help you can see, once it merged you can see by release date
