### ISSUE TITLE
Trial Limit of downloads is visible in Nightly full release ...

### ISSUE THREAD

**Issue by vrtareg** [osmandapp/Osmand#1772]
Hi

Please see screenshots attached.

Some strange notification in Full version about Free version.

Regards,
Areg

![screenshot_2015-10-05-07-25-12](https://cloud.githubusercontent.com/assets/2562730/10279227/b269e99c-6b5b-11e5-87ae-fe6286f45a3f.png)
![screenshot_2015-10-05-07-25-21](https://cloud.githubusercontent.com/assets/2562730/10279228/b26eb2b0-6b5b-11e5-9f14-fca9c5a2b4c9.png)

**Comment by vshcherb** [comment]
Fixed
