### ISSUE TITLE
Speed display in car or truck profile

### ISSUE THREAD

**Issue by jol70** [osmandapp/OsmAnd#17722]
# Auto-translate
# Description
at a double Point: display the speed via a flashing or audible message, as desired, before reaching the GPS speed change point.
# Describe the solution you'd like
1) when changing regulated speed, display a panel in full screen for 2 seconds indicating the new mandatory speed limit
it is advisable to display the speed some 100m before reaching the panel to allow slowing down by engine braking... For this, the prior display (time of prior information, but also the distance) should ideally take into account the speed and the weight of the vehicle. vehicle so that it can slow down.

### Description

 en un double Point : afficher la vitesse par un message clignotant ou et sonore au choix avant l atteinte du point GPS de changement de la vitesse. 

### Describe the solution you'd like

1) lors du changement de vitesse réglementée afficher en plein écran durant 2 seconde un panneau qui indique la nouvelle vitesse limite obligatoire

2) il convient d afficher la vitesse quelques 100m avant l atteinte du panneau pour permettre de ralentir par frein moteur... Pour cela l affichage préalable (temps d information préalable, mais aussi la distance ) doit idéalement tenir compte de la vitesse et du poids du véhicule de manière à pouvoir ralentir.

**Comment by scaidermern** [comment]
Duplicate of #17391?

**Comment by letypequividelespoubelles** [comment]
@scaidermern yes it's a doublon
