### ISSUE TITLE
Add OsmAnd actions to system share sheet

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#17727]
## Descripiton
Starting Android 14, apps can add their custom actions to system share sheet https://developer.android.com/about/versions/14/features#add-custom-actions. We already implemented the same feature in iOS.
<details>
    <summary>Example</summary>
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/51cf8123-03e4-4726-bb58-edb8e7acda36)"  width="300" height="auto"/> </td>
  </tr>
</table>   

</details> 

<table style="width:100%">
  <tr>
    <th>Android</th>
    <th>iOS</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/3785d1b1-22b5-4093-97b6-a8e8f7a06e35"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/431dd93e-7f5b-4d25-946c-c79992251933"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by 0xRe1nk0** [comment]
We should increase SDK to 34 before merging [this PR](https://github.com/osmandapp/OsmAnd/pull/19922)

**Comment by dmpr0** [comment]
## Review
- [ ] Use `ic_action_coordinates_location` for Copy coordinates action

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/map/map-context-menu#share
