### ISSUE TITLE
Heart rate is not visible in tracks with more than one segment

### ISSUE THREAD

**Issue by alienff** [osmandapp/OsmAnd#17720]
## Description
Heart rate is not visible in tracks with more than one segment.

### How to reproduce

1. Start recording a track including heart rate measurements.
2. Wait for data to appear.
3. Click "New segment"
4. Wait for more data.
5. Stop tracking.
6. Save track.
7. Open saved track.
8. Heart rate measurements is not in the list of data to display.

Example tracks: [one segment](https://alienff.com/one_seg.gpx), works fine, [two segments](https://alienff.com/two_seg.gpx), does not work.

**Environment**
OsmAnd Version: OsmAnd+ 4.5.6
Android/iOS version: Android 10
Device model: SM-A520F

**Comment by albansuser** [comment]
Same here. 

OsmAnd~ 4.6.0#481m, released: 2023-07-25

Tracking on with heart rate displayed and recording. Ride following route from A to B. At B create and follow route back to A. Heart rate still displayed.

Recorded track A to B to A only displays HR of segment A to B. All other standard parameters (speed, altitude etc) are correctly displayed for whole trip.

![Screenshot_20230726_203101_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/66352711/b4435fe1-726a-47f7-ba5b-e18ff8812a98)
![Screenshot_20230726_203133_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/66352711/74c439d3-dc82-4e7c-ba92-ad7fa8f5d379)
