### ISSUE TITLE
Configure map > menu category as for v2 engine

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#17726]
While using the v2 engine, the _Configure map_ menu displays a separate category ("Terrain") for the menu items _Contour lines_, _Hillshade / Slope_, _3D Relief_, and _Nautical depth_ (as available):

![image](https://github.com/osmandapp/OsmAnd/assets/845735/86b813d2-e566-4281-aff2-78e0bd64f9f2)

But while using the v1 engine, there is no separate category, the (available) menu items are listed under the "Show" category.

This simplification PR aligns the v1 appearances with that of v2: https://github.com/osmandapp/OsmAnd/pull/17725

**Comment by vshcherb** [comment]
Merged in another issue.
