### ISSUE TITLE
Location/Direction pointer obscured

### ISSUE THREAD

**Issue by albansuser** [osmandapp/OsmAnd#17731]
OsmAnd~ 4.6.0#490m, released: 2023-07-26

The location/direction pointer has become partially obscured by displayed routes and tracks. This has occurred with recent nightly compilations.

The location/direction pointer needs to be displayed in the topmost layer as previously occurred.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/66352711/06af81dd-67eb-47ba-a527-7e4fc7901c1c"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/66352711/85cf426a-b512-4592-8c60-294c433e9c45"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
The problem is reproduced in 3D simulation for https://www.openstreetmap.org/way/44849338#map=16/49.3230/10.2070

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#489m, released: 2023-07-26 
Reproduced after changing *Map rendering engine* **V2-V1-V2** (see video). After this rendering switch, *my location* remains hidden under route line in other simulations as well.

https://github.com/osmandapp/OsmAnd/assets/116079541/925c58e3-8a95-45b5-9629-12c4794a30f5

**Comment by albansuser** [comment]
Thanks
