### ISSUE TITLE
Navigation instruction by vibration pattern

### ISSUE THREAD

**Issue by lightonflux** [osmandapp/Osmand#1773]
For pedestrian and bicycle navigation it is very desirable to get navigation instructions in a non-visual way. At the moment the only other option is audio, but this can be unsafe (bicycle) or rude if you walk and talk with somebody (earphones).

All modern phones can vibrate with different characteristics. So it is possible to have different vibration patters for different instructions (immediate left & right turn, distance left&right turn). 

I would like to read your input and ideas how to make this possible and how design the patterns. At the moment i searching and trying to get some papers on the topic (e.g.: Navigation by vibration: Effects of vibrotactile feedback on a navigation task).

**Comment by sonora** [comment]
No action planned, it seems.
