### ISSUE TITLE
Instructed to take off ramp when route continues on motorway

### ISSUE THREAD

**Issue by johnea** [osmandapp/OsmAnd#17730]
# 🐞 routing report

### Routing engine

- [X] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

car

### Start and end points

from: [32.76323, -117.12201]  Le Stat's Coffeeshop on Adams Ave, San Diego 
to: [34.03446, -118.3808]  Olin St, Culver City / Los Angeles

Route details below...
### Actual and expected routes

Routing will instruct to exit at intermediate off ramps, when the route actually continues along the I-5 freeway.

This issue is consistently reproducible. An example routing is below.

I "shared" the route details from osmand via email, below is the email contents.

LeStats Caffeeshop Adams Ave San Diego to Culver City Route shared via OsmAnd
==============================
Total distance 126 mi, traveling time 2 h 11 min.
1.  Head Adams Avenue (892 ft,  0:25)
2.  Turn left and go 32nd Street (866 ft,  0:41)
3.  Turn sharply right and go toward I 805 North (47.6 mi,  48:06)
4.  Keep right and go I 5 San Diego Freeway (11.3 mi,  11:15)
5.  Turn slightly right and go I 5 San Diego Freeway 78 (7.96 mi,  7:52)
6.  Turn right and go I 5 San Diego Freeway 86 (7.02 mi,  6:58)
7.  Keep right and go I 5 San Diego Freeway (1.08 mi,  1:05)
8.  Keep left and go San Diego Freeway (17.3 mi,  16:55)
9.  Keep right and go I 5 Santa Ana Freeway (18.0 mi,  17:56)
10.  Turn slightly right and go I 5 Santa Ana Freeway 129 (0.95 mi,  0:57)
11.  Turn slightly right and go I 5 Santa Ana Freeway 130B (1.26 mi,  1:15)
12.  Turn right and go I 5 Santa Ana Freeway 131 (0.36 mi,  0:21)
13.  Turn slightly right and go I 5 Santa Ana Freeway 132 (0.63 mi,  0:37)
14.  Turn slightly right and go I 5 Santa Ana Freeway toward Santa Monica 133 (0.36 mi,  0:22)
15.  Turn slightly right and go toward I 10 West, Santa Monica (7.28 mi,  7:14)
16.  Turn slightly right and go I 10 Santa Monica Freeway 9 (2.01 mi,  2:00)
17.  Turn slightly right and go I 10 Santa Monica Freeway 7B (1.38 mi,  1:22)
18.  Turn slightly right and go I 10 toward Robertson Boulevard, Century City, Beverly Hills, Museum of Tolerance 6 (1227 ft,  0:29)
19.  Turn left and go S Robertson Boulevard (0.58 mi,  3:48)
20.  Turn right and go Washington Boulevard (837 ft,  0:36)
21.  Turn right and go Washington Boulevard (427 ft,  1:08)
22.  Turn right and go (210 ft,  0:08)
23.   (0 ft,  0:00)
==============================

In this route, the following steps are incorrect instructions to exit the freeway:
5, 6, 10, 11, 12, 13 and 14

Several others are of dubious correctness:
4, 7, 8, 9 and 21

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 3.0.4

I used 3.0.4 for many years without this issue. On updating to new phone this year I updated osmand and began having this issue immediately.

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

OsmAnd 4.3.12, released: 2023-02-17
</code></pre>

**Device and Android/iOS version:**
teracube 2e
Android version 11
/e/OS 1.8.1-r-20230204257076-stable-emerald

**Maps used (online or offline):**

- [X] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**
I have driven this route several times and always get these incorrect off ramp instructions.

The blue route line on the map indicated a continuation along the I-5 freeway, so I knew the exit instructions were wrong.

Prior to filing this bug report, I reproduced the route with manually entered start and destination locations, and found the errors to be 100% reproducible.

As an experiment, while northbound, I exited at off ramp 130B as instructed. At the end of the off ramp, there was no followup instruction. I continued to drive, and eventually received "You have been off the route for..." message. Then re-routed back to I-5.

On the webmap, one interesting thing about this exit, is that the 130B shows in I-5 prior to the offramp separating from the main freeway:
https://www.openstreetmap.org/node/317623786

When I would ignore the instructions to exit, immediately after passing the off ramp, I would get an announcement "Continue XX miles on I-5 Santa Ana Freeway".
 
This issue is 100% reproducible for me. 
If a starting point is chosen here: [32.76323, -117.12201]
And a destination here: [34.03446, -118.3808]
Then the route should be via I-5 and show the incorrect exits listed above.

**Comment by scaidermern** [comment]
OsmAnd istl outdated. Please update to the current stable version 4.4.7 or try the current beta version 4.5.7.

**Comment by johnea** [comment]
> Your OsmAnd version is outdated. Please update to the current stable version 4.4.7 or try the current beta version 4.5.7.

If you have one of these versions installed, wouldn't it easiest to add the starting point and destination above and see if it produces the same route errors?

This would also confirm/deny if this issue is reproducible.

**Comment by scaidermern** [comment]
Can you add a screenshot first? From your description it is hard to understand where exactly the problem occurs.

**Comment by scaidermern** [comment]
Definitely looks different with OsmAnd 4.5.7:

![IMG_20230727_191035](https://github.com/osmandapp/OsmAnd/assets/1040784/60e655b7-8019-4d86-8b66-8f561bcb7939)

**Comment by johnea** [comment]
That definitely looks different. 

Although I wonder about those 3x exits from I-10 Santa Monica Freeway. Seems like there should only be 1 exit from I-10, for me it was Robertson Ave, number 18 in the shared route above. Also note in the shared route above, numbers 16 and 17 are incorrect off ramp instructions from I-10 Santa Monica freeway. 
Can you look at the route you posted above on the map and see if those exits, exit 12 and Western Ave, show a continuing route along I-10? 
These look like the same erroneous exit instructions to me.

I will install version 4.5.7 from here:
https://osmand.net/releases/net.osmand-4.5.7-4507.apk

I can sideload this, but do you have advice for updating via sideload? I want to make sure I don't wipe out my Markers, and other user added data.

Thanks for your efforts in debugging this issue!

**Comment by DmitryAlexei** [comment]
Please try updating the app to the newest version. You may also need to update the map (OSM data may be outdated).
You can backup all of your data: go to menu > settings > swipe to the bottom of the screen > export to file (note that exporting maps may take a long time



https://test.osmand.net/map?start=32.763230,-117.122010&end=34.034460,-118.380800&type=osmand&profile=car#11/34.1919/-118.1712
