### ISSUE TITLE
Error in loading faviorits db

### ISSUE THREAD

**Issue by saeedafshari8** [osmandapp/Osmand#1775]
Hi,
There is an error on initializing favorites gpx at the FavouritesDbHelper -> method : loadFavorites.

flatGroups.clear();
		favoriteGroups.clear();
		
		File internalFile = getInternalFile();
		if(!internalFile.exists()) {
			File dbPath = context.getDatabasePath(FAVOURITE_DB_NAME);
			if(dbPath.exists()) {
				loadAndCheckDatabasePoints();
				saveCurrentPointsIntoFile();
			}
			//createDefaultCategories();
		}
		Map<String, FavouritePoint> points = new LinkedHashMap<String, FavouritePoint>();
		Map<String, FavouritePoint> extPoints = new LinkedHashMap<String, FavouritePoint>();
		loadGPXFile(internalFile, points);
		loadGPXFile(getExternalFile(), extPoints);
		boolean changed = merge(extPoints, points);
What happens if FAVOURITE_DB_NAME database does not exists?
Yes, the application got an exception at loadGPXFile(internalFile, points);
I recommend to create a default empty database if the mentioned database does not found.

**Comment by vshcherb** [comment]
Fixed with #8cf0d0f

**Comment by saeedafshari8** [comment]
Thanks. How can I contribute?

**Comment by saeedafshari8** [comment]
You fixed it at #989cdae not #8cf0d0f
