### ISSUE TITLE
"Show all tracks on the map" is broken

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#17754]
(I think this is a regression:) Go to My Places > Tracks, then for any of your track folders tap the 3-dots menu, and select "Show all tracks on the map".

Instead of showing the tracks on the map, or even just marking them as "visible", you get routed to the corresponding folder's view of the "Visible tracks" screen. But with none of the tracks even selected, and there also being no "Select all" button (#16913) to select all tracks of the corresponding folder.

**Comment by vshcherb** [comment]
It needs to be fixed with Select All on this screen -https://github.com/osmandapp/OsmAnd/issues/16913, probably name of the action should change to "Show on map".

I don't think this is a regression cause I don't remember this action in 4.4

**Comment by sonora** [comment]
Looks like this was closed but not fixed, that's why I accidentally re-created it in https://github.com/osmandapp/OsmAnd/issues/18490.

@vshcherb I guess it would be nice to not just fix it by forwarding users to the selection screen and expecting them to further buttons there, but use this folder-related menu action "_Show all tracks on the map_" simply for what it says?
