### ISSUE TITLE
Different sorting options (my places and configure map) 

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#17758]
## Description
The sorting set in "configure map / tracks" does not apply to "my places /tracks" 
### Expected result
Should be the same? 

**Environment**
OsmAnd Version: +4.5.8,  4.6.0#508m
Android/iOS version: 13
Device model:

**Comment by sonora** [comment]
Another side effect of not unifying the current dualism between _Configure map > Tracks_ and _My Places > Tracks_. Both screens could be made different views of the same screen, but are coded completely separate (and with different behavior).

**Comment by vshcherb** [comment]
To do:

Sorting options for same folders should be consolidated and use 1 preference
