### ISSUE TITLE
Opening in Wikipedia app fails

### ISSUE THREAD

**Issue by ChildishGiant** [osmandapp/OsmAnd#17753]
## Description
When opening any Wikipedia article "in browser" using the Wikipedia app I get an error saying "CLEARTEXT communication to en.wikipedia.org not permitted by network security policy"

![Screenshot_20230728-173409.png](https://github.com/osmandapp/OsmAnd/assets/13716824/98ca55b0-93ef-46dd-8de6-deaf474b2bca)

### How to reproduce
Open a Wikipedia article with Wikipedia beta. 

**Environment**
OsmAnd Version: 4.5.7
Android version: 11
Device model: Unihertz Titan Slim

**Comment by DmitryAlexei** [comment]
It's not an Osmand issue. Try contacting Wikipedia Beta support with this question.
