### ISSUE TITLE
Ship navigation routes through culvert

### ISSUE THREAD

**Issue by spaanse** [osmandapp/OsmAnd#17752]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Start and end points

Start: 52.96388° N, 5.48629° E
End: 52.96210° N, 5.48833° E

### Actual and expected routes

Routes through the following culvert: https://www.openstreetmap.org/way/948500478

### Is this a regression?

Have not seen it before, but might have existed before

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

OsmAnd 4.5.7, Released: 2023-07-25
</code></pre>

**Device and Android/iOS version:**

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**
Routing profile contains height of 11m

**Comment by DmitryAlexei** [comment]
[OsmAnd map](https://test.osmand.net/map/?start=52.963878,5.486296&end=52.962082,5.488362&type=osmand&profile=boat#18/52.96293/5.48744)
OsmAnd routes through [tunnel:culvert](https://wiki.openstreetmap.org/wiki/Tag%3Atunnel%3Dculvert). [Taginfo](https://taginfo.openstreetmap.org/tags/tunnel=culvert#overview).
OsmAnd~ 4.6.0#489m, released: 2023-07-26
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/35d6bc7e-55f3-4222-a908-79462ba8448a"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#609m, released: 2023-08-13
1. On the web portal, OsmAnd doesn't build route through culvert anymore: 
https://test.osmand.net/map/?start=52.963878,5.486296&end=52.962082,5.488362&type=osmand&profile=boat#18/52.96286/5.48700
2. On Android OsmAnd also does't use culvert, but makes a route over it
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/6bb32471-b980-4159-a0b1-a934685095e6"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
This test should be used to test correctness cause it can't get to this small part anyhow https://test.osmand.net/map/?start=52.963878,5.486296&end=52.950513,5.500503&type=osmand&profile=boat#14/52.9451/5.5180
