### ISSUE TITLE
Map empty at zoom level 19 with 3D relief enabled, map jumps to different position

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#17764]
With Configure map / 3D relief enabled, the map remains empty at zoom level 19. When zooming past level 19, the map sometimes jumps to a different position a few hundred meters away.

Example:
https://github.com/osmandapp/OsmAnd/assets/1040784/2378a666-b0db-498c-80ce-1a0e6456ffc6

Coordinates: 51.04058, 13.75397
(I tried various other locations, same behavior)

OsmAnd 4.5.8

**Comment by sonora** [comment]
Cross-linking to another zoom level 19 issue with 3D Relief active: #17763.

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#514m, released: 2023-07-31
Related with #17763 but not the same
- 3D Relief in Configure map enabled + **Heightmap of tested area downloaded**
- tilt the map
- zoom in using + button
- one or some zoom level may be empty (white map)
- at some zoom level the map jumps to another location

The number and quantity of missed zooms depends on the altitude of the location above sea level (higher it is, earlier empty zooms appear).


<details><summary> video from 47.11714° N, 10.61515° E </summary>
<video src="https://github.com/osmandapp/OsmAnd/assets/116079541/0750739c-00d2-497a-a485-c5ecbb9c1192"></video>
</details>

**Comment by vshcherb** [comment]
These issues should be fixed together so no sense to separate them for now.
