### ISSUE TITLE
Accessing edits via the osm editing plugin screen 

### ISSUE THREAD

**Issue by musshorn** [osmandapp/OsmAnd#17779]
## Description
When you access an edit via Plugins -> OSM Editing -> Settings -> OSM Edits and select an edit, you would expect the screen to swap to the map and display where the edit was, however it just cuts back to the plugin screen but with the map node selection UI visible at the bottom of the screen

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/874740/c65c5b79-02f7-4d26-a457-c086eb3412fb"  width="300" height="auto"/> </td>
  </tr>
</table>

### How to reproduce
Access an edit via Plugins -> OSM Editing -> Settings -> OSM Edits and select an edit

### Actual result
See above screenshot

### Expected result
After selecting an edit you end up on the visible map

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/874740/1f8e5d48-480e-4b86-bb49-9f26a7b05cb9"  width="300" height="auto"/> </td>
  </tr>
</table>

**Environment**
OsmAnd Version: OsmAnd+ 4.5.8, released: 2023-07-28 
Android/iOS version: 12
Device model: OnePlus 7

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#626m, released: 2023-08-17
Steps to reproduce:
- make Osm note
- Open Menu > Plugins > OSMediting plugin > settings > OSM edits > chose your edit

Actual result:
- see screenshot. OsmEdit context menu overlaps OSMediting plugin starting page, you do not see the map with edit sign.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/077a108b-efae-4aaa-96c0-45a8446fd8b9"  width="300" height="auto"/> </td>
  </tr>
</table>
