### ISSUE TITLE
Duplicate street segments

### ISSUE THREAD

**Issue by Citro12** [osmandapp/OsmAnd#17777]
Hello, after changing the parking lot streets, they appear twice.  See the screenshot
https://abload.de/image_mobile.php?img=screenshot_2023-07-28aydh8.jpg

Android 13, Xiaomi Mi 11 lite 5G
OsmAnd 4.5.8

Regards
Hans

**Comment by DmitryAlexei** [comment]
As I understand, you are using Live updates.
Try to restart the OsmAnd app (several) times (swiping out from currently used programs in Android menu).

**Comment by Citro12** [comment]
> As I understand, you are using Live updates. Try to restart the OsmAnd app (several) times (swiping out from currently used programs in Android menu).

yes, they are live updates.  I have now closed the app about 10 times in a row, also removed it from the task manager.  Unfortunately it doesn't help.

**Comment by DmitryAlexei** [comment]
Clearing Live updates cache and re-downloading updates doesn't solve the problem?
Please, provide the coordinates of the parking slot.

**Comment by Citro12** [comment]
> Clearing Live updates cache and re-downloading updates doesn't solve the problem? Please, provide the coordinates of the parking slot.

How can I clear the live update cache?
47.78424° N, 12.33285° E

**Comment by DmitryAlexei** [comment]
Please see documentation https://osmand.net/docs/user/personal/maps#osmand-live
use basket to clear cash

**Comment by DmitryAlexei** [comment]
As I see, your changes are already included in Osmand's main map, so you need to update the main map
https://osmand.net/docs/user/personal/maps#update-maps

**Comment by Citro12** [comment]
> As I see, your changes are already included in Osmand's main map, so you need to update the main map https://osmand.net/docs/user/personal/maps#update-maps

Livecache has been emptied and the new Main Map randomly appeared today.  It worked.  Many thanks
