### ISSUE TITLE
Trip recording has gaps when screen is off (regression in 4.5.8)

### ISSUE THREAD

**Issue by vinc17fr** [osmandapp/OsmAnd#17771]
## Description
After the update from 4.4.7 to 4.5.8, trip recording now has gaps when the screen is off.

### How to reproduce
1. Start trip recording.
2. Switch off the screen.
3. After some time, switch on the screen.

### Actual result
There are gaps in the track, which happened when the screen was off.

### Expected result
There should be no gaps.

Note: in the location permissions, some apps are "allowed all the time", while OsmAnd+ is "allowed only while in use". IIRC, in the past, I changed it to "allowed all the time", but this is not possible with this new version.

**Environment**
OsmAnd Version: 4.5.8
Android/iOS version: Android 13
Device model: Samsung Galaxy S23 Ultra

**Comment by scaidermern** [comment]
Please check if battery optimization for OsmAnd is still _disabled_ in your Android settings.

Also check https://osmand.net/docs/user/troubleshooting/track-recording-issues#recorded-tracks-have-gaps

**Comment by vinc17fr** [comment]
The Battery setting for OsmAnd+ was set to "Optimized". I've now changed it to "Unrestricted". Next time I go out, I'll see if this makes a difference. But I'm wondering why such a change would be needed after an OsmAnd+ update.

**Comment by vinc17fr** [comment]
Changing the Battery setting to "Unrestricted" solved the issue.

If nothing changed about the location or battery optimization on the OsmAnd side, the only thing I can think of about the regression is that "allowed all the time" for the location permission could have still been active with 4.4.7 on my phone due to past settings (since some apps still have it) and got disabled after this upgrade. Note that I used 4.4.7 in the morning before the upgrade and the previous days with trip recording and I hadn't had any issue with this version. The problem appeared only after the update to 4.5.8.

**Comment by scaidermern** [comment]
@vshcherb I suggest to raise the priority of #14958. This is a rather frequent problem with an easy solution.

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/14958

**Comment by sonora** [comment]
Regarding "Allow all the tine" for the location permission: Ever since Android 11 this indicates that an app can receive "background location", something heavily restricted by google.

OsmAnd does not use background location: Following best practice, all OsmAnd location requesting happens in the **foreground** (during navigation or trip recording via a "foreground service", visible in the Android notification bar, even while the app itself may not appear in the foreground).
