### ISSUE TITLE
Expire doesn't seem to work for own online map

### ISSUE THREAD

**Issue by Wikunia** [osmandapp/OsmAnd#17776]
## Description
I've added my own tile server to OsmAnd+ with an expire time of one minute. Though changing the tiles on the tileserver will not get reflected on the app even after five minutes.
I found this issue which should be solved but apparently doesn't seem to have fixed it for me: https://github.com/osmandapp/OsmAnd-iOS/issues/1838

### How to reproduce
Add a new tile server with tileserver-gl and add an expire time of one minute and store as sqlite db, load the tiles, change the images on the tile server and open OsmAnd again.

### Actual result
The tiles of the old version are shown until one clears the cache manually.

### Expected result
The new tiles should be shown after a maximum of one minute

**Environment**
OsmAnd Version: 4.5.8
Android/iOS version: Android 13
Device model: Pixel 6

**Comment by Sonwon1** [comment]
Add me to the list, Rainviewer is not updating the radar maps.
