### ISSUE TITLE
Tracks / Favorites / Map markers and all data not displayed in Android Auto

### ISSUE THREAD

**Issue by KaiRo-at** [osmandapp/OsmAnd#17780]
## Description
Until the upgrade to OsmAnd 4.5.8, the tracks set visible on the map were also shown on the Android Auto screen. Esp. the currently recording track and the POI GPX files from uMap and similar are absolutely crucial to see for me when I'm on one of my road trip vacations, like I am right now.
Yesterday, before the recent update (I guess that was still a 4.4.x version), this worked perfectly. Today, after installing the update to 4.5.8, this broke. (Note that I do not use routes at all, so the new menu isn't much help to me and I also pretty much have to click it away all the time, but that's OK - not seeing tracks any more is enough of a deal breaker that I'd actually be happier switching back to 4.4.x though. Also, if that changes anything, I'm using map rendering engine v1 as v2 was too sluggish on my Fairphone 3.)

### How to reproduce
Set some tracks, recorded and with waypoints, to visible and start recording a track. Make sure, those are actually visible on the phone screen. Then, activate Android Auto.

### Actual result
Map on car screen should display same tracks as phone screen.

### Expected result
No tracks are shown.

**Environment**
OsmAnd Version: 4.5.8
Android/iOS version: Android 13
Device model: Fairphone 3

**Comment by KaiRo-at** [comment]
That kind of reaction time is why I love open source projects! You're doing a great job! Keep up the great work!
Any idea when I can expect the fix(es) in the Play Store (at least the Beta channel)?

**Comment by dmpr0** [comment]
> That kind of reaction time is why I love open source projects! You're doing a great job! Keep up the great work! Any idea when I can expect the fix(es) in the Play Store (at least the Beta channel)?

Hi! Update with fix is already available in beta:
* https://play.google.com/apps/testing/net.osmand
* https://play.google.com/apps/testing/net.osmand.plus 

Release will be available later today or tomorrow, depends on time needed for Google Play team to approve.
