### ISSUE TITLE
navi-problem by "shortes" way

### ISSUE THREAD

**Issue by osmvermesser** [osmandapp/Osmand#1778]
if you define the car-profile by shortes way and you want (example) from http://www.openstreetmap.org/?mlat=53.9342&mlon=10.7202#map=14/53.9342/10.7202 to http://www.openstreetmap.org/?mlat=53.7177&mlon=10.3351#map=14/53.7177/10.3351 then you leave A-1 at https://www.openstreetmap.org/node/21826513 drive by https://www.openstreetmap.org/way/104942850 and remove to A-1 at https://www.openstreetmap.org/node/26726763. this part is not so long but you only use the motorway_link. normal you drive this part only on A-1!!!

**Comment by hakuchi** [comment]
this is because you use shortest route.
if you use the fastest route, Osmand will take the motorway without passing the link.
Cant see anything wrong here.

**Comment by vshcherb** [comment]
Fixed
@xmd5a2 can we have a test for this? (to revert fix please see commit https://github.com/osmandapp/OsmAnd-resources/commit/165e2b61eec1da626bb3185dba98c881aea73bf8)
