### ISSUE TITLE
Unable to access profile settings (Android 6)

### ISSUE THREAD

**Issue by Prusaker** [osmandapp/OsmAnd#17785]
## Unable to access profile settings.
When you select the settings of any of the profiles, the program exits with a message "Unfortunately, OsmAnd Nightly has stopped"

### How to reproduce
Download and install any nightly build (tested at builds throughout the month), tap "Settings" and select any profile.

### Actual result
Error message "Unfortunately, OsmAnd Nightly has stopped" and OsmAnd is crashed.

**Environment**
OsmAnd Version: 4.6.0#525 (however this error appears on earlier builds as well, I have checked builds from the last month)
Android/iOS version: 6.0
Device model: Lenovo TAB 2 A10-70L

The same OsmAnd build on another device, but with Android 7, is works correctly.

Error log is attached:
[exception.log](https://github.com/osmandapp/OsmAnd/files/12226958/exception.log)

**Comment by vshcherb** [comment]
We need to make decision whether we can still support Android 6.
