### ISSUE TITLE
Fix quick actions for Widgets

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#17797]
### How to reproduce
- Hide widget with a quick action
- Remove widget in Configure Screen
- Add widget back in Configure Screen

### Actual result
- Widget not visible 
### Expected result
- Widget should be visible 

Note: once widget is hidden by quick action it should be stored in same settings as widget visibility which should be reset once widget is added back via Configure screen

**Comment by vshcherb** [comment]
To do: remove quick actions show/hide coordinates. We need to have consolidated decision around configure screen quick actions
