### ISSUE TITLE
Bug with Calculate elevation (offline)

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#17792]
## Description

Can't receive data and graph for Edit track function (Straight line profile without elevation data 

### How to reproduce

     - Start to create a track with Straight line profile 
     -  Graph > Calculate elevation > Calculate offline

### Actual result

not calculate elevation and not show the graph

### Expected result

Show Graph with Elevation data (from Terrain map data)

## Description

Can't recalculate track with partial elevation data (one part of a track with elevation data and the second part without data)

### How to reproduce

     - Open a track with elevation data on Edit track tool
     -  Add lines by Straight line profile
     - Graph > Caclulate elevation?

### Actual result

not calculate elevation and  show graph with partial elevation data

### Expected result

Show Graph with all elevation for full track

| 1 Scenario image| 2 Scenario image|
|-----------|-----------|
|![telegram-cloud-photo-size-2-5355096419180072439-y](https://github.com/osmandapp/OsmAnd/assets/44466116/c22b1de8-ff8e-4822-9ba0-16e0f17eaa53)|![telegram-cloud-photo-size-2-5355096419180072438-y](https://github.com/osmandapp/OsmAnd/assets/44466116/5fc8107a-fe23-4254-b31c-2166f7da6193)|

**Environment**
OsmAnd Version: 4.6.0#526m
Android/iOS version: Android 13
Device model: Samsung S22

**Comment by yuriiurshuliak** [comment]
Currently, in the latest nightly version, the bug has been fixed in two scenarios.
OsmAnd~ 4.6.0#723m, released: 2023-09-04

<table style="width:100%">
  </tr>
  <tr>
    <th>Scenario 1</th>
    <th>Scenario 2</th>
  </tr>
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/43737d12-dec4-4a44-af8f-ef07d9e7b8e0"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/56089d7c-09f3-4ded-9440-b2b3722dbe21"  width="300" height="auto"/>   </td>
  </tr>
</table>
