### ISSUE TITLE
Heightmaps categorized as "Online and cached tile maps"

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#17798]
At Download maps / local, the downloaded heightmaps appear in the category "Online and cached tile maps". Neither are the heightmaps online maps, nor are they tile maps. I guess they should get listed in a new category "Heightmaps", similar to "Contour lines".

![photo_2023-08-02_13-02-30](https://github.com/osmandapp/OsmAnd/assets/1040784/6709e8b7-e0f4-4260-b7ec-906f38846b35)

OsmAnd 4.5.9.

**Comment by sonora** [comment]
Plus: It seems, what we call "**Heightmap**" here is really what we call "**Terrain map**"under Downloads?  (Related: this question:https://github.com/osmandapp/OsmAnd/issues/17685#issuecomment-1661810182 )

**Comment by sonora** [comment]
@vshcherb Are we keeping the name "Heightmap" here? Because on the download screen we call it "Terrain map (3D)"?
