### ISSUE TITLE
Don't draw distance line after every two finger action with map

### ISSUE THREAD

**Issue by Velomeloman** [osmandapp/OsmAnd#17804]
It's very annoying to draw distance line after every two finger action with map. There used to be a delay after two finger tap **without moving** to draw the line. Need to bring that delay back.
https://github.com/osmandapp/OsmAnd/assets/109347561/e32fa364-3c02-4903-893e-685354bc32fe

_Originally posted by @Velomeloman in https://github.com/osmandapp/OsmAnd/issues/17569#issuecomment-1625130649_

**Comment by DmitryAlexei** [comment]
what kind of solution do you suggest?
how should it work?

**Comment by Velomeloman** [comment]
Just like Guru maps - hold two fingers for ~1s:
https://t.me/ruosmand/127303

And maybe extra function:
https://t.me/ruosmand/127311

**Comment by vshcherb** [comment]
This option could be disabled, so we won't introduce an option to have or not have a lag

**Comment by Velomeloman** [comment]
This option could be disabled from very deep settings. The switch is located in the Buttons section, but there is no such button on screen. There isn't any fast way to able/disable it (quick action or widget like radius ruler).

In addition, the flickering of the distance line looks like a glitch.

**Comment by vshcherb** [comment]
For flickering there is a separate issue, same as flickering radius ruler, hopefully will be fixed.

Probably quick action to enable needed it. So a separate issue makes sense
