### ISSUE TITLE
Amenity bench + tourism not indexed

### ISSUE THREAD

**Issue by tomhanax** [osmandapp/OsmAnd#17801]
### Discussed in https://github.com/osmandapp/OsmAnd/discussions/17668

I want to see for specific POI, node 9151211710. You can find it at https://www.openstreetmap.org/node/9151211710 and it's not in POI database.

it should be indexed by couple of rules: 1) amenity=bench + name 2) tourism=attraction however it's not in POI

Technical: amenity=bench -> bench=yes, tourism=attraction -> tourism=yes and it becomes non POI

**Comment by DmitryAlexei** [comment]
@xmd5a2, please regenerate Slovakia map, not Slovenia.
