### ISSUE TITLE
List of stops ends unexpectedly (bus route ptv2) at zone border.

### ISSUE THREAD

**Issue by tenzap** [osmandapp/OsmAnd#17809]
When looking at the bus stops of a bus route, it seems that when there is a border of an administrative zone between the stops/platforms then the list of stops in osmand will end at the border although there are stops afterwards. 

In my setup I have installed 'France - grand est' map. This map covers the administrative zone 'Haut rhin' and 'Bad Rhin' (and a few others).

Select stop named 'MARCKOLSHEIM - Joffre' at 48.15964° N, 7.54412° E

Select the first route "COLMAR - Blaise Pascal =>  MARCKOLSHEIM - Joffre". You will notice that the list of starts at ELSENHEIM - Leclerc while it should start at COLMAR - Blaise Pascal and the stop just before should be 'GRUSENHEIM - Pompiers' at 48.14782° N, 7.48888° E. Apparently only the stops in the administrative zone 'Bas-Rhin' are listed.

When selecting bus stop 'GRUSENHEIM - Pompiers' there is the same problem. Only the stops in administrative zone 'Haut-Rhin' are listed (from COLMAR to GRUSENHEIM). The stops from ELSENHEIM to MARCKOLSHEIM are missing.

It is expected that for the bus route there is not this split.

Btw this route has only members having role stop and platform, but no member with an empty role (ie. The itinerary of the route is not set, only platforms and stops are defined).

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/46226844/f395d03d-b97f-4ba5-a39b-b03a3323b231"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/46226844/20257d5e-d138-451e-9b4f-49fa7af7eceb"  width="300" height="auto"/> </td>
  </tr>
</table>

**Environment**
OsmAnd Version: 4.4.7
Android/iOS version: android 12
Device model: Xiaomi redmi note 9s

**Comment by DmitryAlexei** [comment]
Bus route 68R021 MARCKOLSHEIM - r.Maréchal Joffre => COLMAR - Gare SNCF:
https://www.openstreetmap.org/relation/16090520 (edited 20 days ago)
https://www.openstreetmap.org/relation/16089371 (edited 10 days ago)
Route ends on the maps border
Related with https://github.com/osmandapp/OsmAnd/issues/16569
According to comment below it's ok
https://github.com/osmandapp/OsmAnd/issues/16569#issuecomment-1498868354


<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/9b212b56-4d9c-42e2-92fd-ade8e4bdca98"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/9b2814df-904f-4fc6-a8bb-d20c06a560bb"  width="300" height="auto"/> </td>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/cd1897de-fba0-407b-a3c7-bbc0876a3e78"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
@tenzap same result with *France grand est* map

**Comment by DmitryAlexei** [comment]
@tenzap If you haven't got a map, so there is no PT stop

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/16569
