### ISSUE TITLE
Water is disappears on zoom level 15 if Underlay is on

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#17813]
## Description
Water is disappears starting from zoom level 15 if Underlay is On. Affected map styles: OsmAnd and OSM Carto.

### How to reproduce
* Turn on Online map plugin
* Open Menu – Configure Map – Underlay, turn on
* Select Microsoft Earth as underlay
* Disable Show  

### Actual result
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/2ec63717-3e7d-4e9b-83ea-a13bb383f66e"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/8fd297c0-49b4-4c3d-bf60-12649f46c03c"  width="300" height="auto"/> </td>
  </tr>
</table>   

### Expected result

**Environment**
OsmAnd Version:
Android/iOS version:
Device model:

**Comment by dmpr0** [comment]
> This definitely was intentional, not clear whether map or satellite imagery will be more useful depends what's more precise.

Settings could be precise, now needed result could be achieved by turning on "Show polygons" in Configure Map – Underlay map and turning on Hide Polygons in Configure Map - Hide

**Comment by xmd5a2** [comment]
Not reproducible
Zoom 14:
![Screenshot_2023-09-20-09-58-49-214_net osmand plus](https://github.com/osmandapp/OsmAnd/assets/5829014/8ab3966f-a55a-4b5e-8e84-f3905eec3f64)
![Screenshot_2023-09-20-09-58-05-239_net osmand plus](https://github.com/osmandapp/OsmAnd/assets/5829014/b2d421a9-5dd3-4953-81d9-55b97c670d52)
