### ISSUE TITLE
Some characters are not displayed in Hebrew

### ISSUE THREAD

**Issue by ale-xy** [osmandapp/Osmand#1781]
On Israel map, squares are displayed instead of some charactres. Probably when Hebrew characters are in the same word with non-Hebrew (numbers, ', ").

Examples on the screenshot below:
'המלך ג'ורג (King George) street, http://www.openstreetmap.org/way/119290511
רש''י (Rashi) street, http://www.openstreetmap.org/way/33627462
המלך ג'ורג'/רש''י (King George/Rashi) bus stop, http://www.openstreetmap.org/node/1803024981
6א house number POI, http://www.openstreetmap.org/node/2079204804
![scr1](https://cloud.githubusercontent.com/assets/7405393/10314278/a49beae8-6c5c-11e5-8057-e516ebf34687.png)

On POI tooltip the same characters are displayed normally
![scr3](https://cloud.githubusercontent.com/assets/7405393/10314280/a4a079f0-6c5c-11e5-8d5b-9007fcedc831.png)

HTC One M7, Android 5.0.2
OsmAnd+ 2.1.1
Israel map 05/09/2015

**Comment by vshcherb** [comment]
Yep, this is known issue, duplicated

**Comment by nicolas-raoul** [comment]
@vshcherb When you close as duplicate, please state the issue number. For instance, if XYZ is a duplicate of ABC, then say "Closed as duplicate of #ABC".
For instance here, this is a duplicate of what issue?
Cheers! :-)

**Comment by nicolas-raoul** [comment]
I finally found it: I think the root issue is #1161
