### ISSUE TITLE
Direction navigation

### ISSUE THREAD

**Issue by Jeawrong27** [osmandapp/OsmAnd#17815]
### normally the direction on navigation Is upper (come in)

**Environment**
OsmAnd Version: 4.5.9
Android/iOS version: 12 SKQ1.211019.001
Device model: Redmi Note 9 Pro M2003J6B2G

**Comment by mikehgentry** [comment]
I'm not sure I understand the problem, but perhaps try tapping the compass icon?

https://osmand.net/docs/user/map/interact-with-map#map-orientation--compass

If you can't see the compass icon, it can be turned on in 'Configure screen'. And if you're navigating, you have to tap it twice.

If that isn't the problem, maybe a screenshot would help?

**Comment by Jeawrong27** [comment]
With the icon compass (or not) on the screen and ripetute tapping on it the result is the same, the direction of navigation is not in the right direction (the upper orange bar). I add 4 screenshot of this issue.

![Screenshot_2023-08-06-14-18-14-375_net osmand plus](https://github.com/osmandapp/OsmAnd/assets/141437231/8d51b0a2-e161-49af-9e45-68c11e0afc3d)
![Screenshot_2023-08-06-14-20-54-472_net osmand plus](https://github.com/osmandapp/OsmAnd/assets/141437231/164bc8b5-f922-425e-9406-90e2539c00a3)
![Screenshot_2023-08-06-14-17-23-845_net osmand plus](https://github.com/osmandapp/OsmAnd/assets/141437231/95168ed5-fec6-4127-b2e9-28c60f5ca0a8)
![Screenshot_2023-08-06-14-15-53-776_net osmand plus](https://github.com/osmandapp/OsmAnd/assets/141437231/289680d3-87d9-4355-9dbd-c860a861f60c)

**Comment by mikehgentry** [comment]
Have a look in

Menu -> Configure profile -> General settings -> Map orientation

What is it set to?

**Comment by Jeawrong27** [comment]
Is set on (Italian language) "Direzione del movimento",

**Comment by DmitryAlexei** [comment]
@Jeawrong27 how did you manage to use **Browse map** profile for navigation? Or have you only changed driving profile icon?

We recommend resetting your driving profile to default values (menu > settings > your driving profile > browse to the bottom of the screen > reset to default) and using Map orientation: movement direction (https://osmand.net/docs/user/map/interact-with-map#map-orientation-modes)
If this does not help, please attach short video and your driving profile settings (menu > settings > your driving profile > browse to the bottom of the screen > export profile)
