### ISSUE TITLE
Add estimated time of arrival to online tracking trip recording info

### ISSUE THREAD

**Issue by Simounet** [osmandapp/OsmAnd#17825]
Hi there, it would be nice to add the `estimated time of arrival` to the online tracking part of the trip recording extension. Today, we can use:
- lat
- lon
- alt
- acc
- timestamp
- speed
- bearing

For online sharing with other people (like [Phonetrack](https://github.com/julien-nc/phonetrack) for Nextcloud), knowing the time of arrival would be super useful.

Thanks a lot for this amazing app and have a nice day!

**Comment by vshcherb** [comment]
This is for live updates we can some extra parameters and document it:
- eta (unix time - to arrival)
- eda (distance in meters - to arrival or to a marker)
- edfa (distance in meters - to first intermediate point / finish point)
- etfa (unix time - to first intermediate point / finish point)

**Comment by Simounet** [comment]
Thank you so much! Can't wait to make a PR to Phonetrack to implement it! Have a nice day.

**Comment by vshcherb** [comment]
Documentation not accepted
