### ISSUE TITLE
nature of seabed "shells" not rendered

### ISSUE THREAD

**Issue by quantenschaum** [osmandapp/OsmAnd#17827]
## Description

polygons tagged with

- `seamark:type=seabed_area` and
- `seamark:seabed_area:surface=shells`

are not rendered (with nautical map style). Mud (M) and sand (S) are shown as expected.

### How to reproduce

Look at https://map.openseamap.org/?zoom=15.5&lon=6.17412&lat=53.45810 (need to enable live updates due recent changes)

### Actual result

no shells (Sh) on the map

### Expected result

blue italic "Sh" on the map, when tapped showing the outline of the polygon

**Environment**
OsmAnd Version: 4.5.9
Android version: 13
Device model: Nokia X20

**Comment by quantenschaum** [comment]
In `nautical.render.xml` there is

```xml
<!-- <apply_if additional="seamark:seabed_area:surface=shells" shader="seamark_j11_shells"/> omitted-->
```

Why is it "omitted"?

**Comment by xmd5a2** [comment]
Fixed
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/747d434b-ef07-423f-99d8-feb813832800)
Netherland - Friesland map will be regenerated in 1-2 hours

**Comment by quantenschaum** [comment]
Is this really fixed? How are shells rendered when [these lines](https://github.com/osmandapp/OsmAnd-resources/blob/master/rendering_styles/nautical.render.xml#L3292) in `nautical.render.xml` are commented out?

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#698m, released: 2023-08-30
- Downloaded Netherlands Frisia map
- Live updates for this map enabled
- go to 53.45810 6.17412

1. Polygon tagged seamark:seabed_area:surface=mud (https://www.openstreetmap.org/way/1195214471) **is rendered** according to our [Map legend](https://osmand.net/docs/user/map-legend/nautical-map#seabed-area). You can see small transparent ovals of different sizes as an underlay and **M (mud)** inscription. 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/568345cb-4410-4029-af13-f2a04aa303ba"  width="300" height="auto"/> </td>
  </tr>
</table>

2. Polygons tagged seamark:seabed_area:surface=shells (https://www.openstreetmap.org/way/1195214472 and https://www.openstreetmap.org/way/1195263187) **are not rendered** according to [Map legend](https://osmand.net/docs/user/map-legend/nautical-map#seabed-area). There should have been **Sh (shells)** inscription.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/52fb9deb-b9fa-4a54-a229-36377fb5c1b1"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by quantenschaum** [comment]
So, this should be reopened.

How did @xmd5a2 get the shell show up on the map in https://github.com/osmandapp/OsmAnd/issues/17827#issuecomment-1695714620 ?
