### ISSUE TITLE
Add altitude to arbitrary POI

### ISSUE THREAD

**Issue by SergeyP2** [osmandapp/OsmAnd#17826]
Hi!

I asked this may be 10 years ago... probably it's time to request again.

I suggest to add calculated Altitude info into all POIs (except those that have Altitute as a property from openstreetmap). This is rather easy, just take an approximation between two nearby altitude lines, if "Contour lines" files is downloaded for this region. It will be very useful for tracking in hilly / mountainous terrain, to instantly know what the altitude of some point is. Right now, I am forced to scroll in all directions to find out altitude label on some altitude line, and then spend efforts to add / deduct "number of lines * 10 m" between a found line with a label, and my point of interest -- not a very nice to do all this in sunny environment somewhere in the mountains.

**Comment by tradavyvy** [comment]
This is a function I would use a lot also.even better if it would work for any point on the map that you 'long click'. 
My use is for camping in hot or cold seasons.
(Higher is cooler lower is warmer, about1c per 100 mtr.)

**Comment by scaidermern** [comment]
This functionality already exists. Not sure what is needed, probably the height map?

**Comment by SergeyP2** [comment]
Here, on screen-shot. The "tourist attraction" on the top of the hill, but at what height it is?

![Screenshot_20230807-103044_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/22505250/69e4a3f9-6209-44f3-810e-11729c464552)

**Comment by SergeyP2** [comment]
> even better if it would work for any point on the map that you 'long click'

I aggree, this should be added into description of any arbitrary place. Right now it has Coordinates and Online photos items, so there we need 3d item: Altitude, after Coordinates.

**Comment by vshcherb** [comment]
Now that's possible to do but it's low priority cause there is a dedicated widget for altitude in every point

**Comment by SergeyP2** [comment]
> dedicated widget for altitude in every point

What do you mean by "there is a dedicated widget for altitude in every point"? What widget and how can I see him?

**Comment by vshcherb** [comment]
https://docs.osmand.net/docs/user/widgets/info-widgets#-elevation-map-center

**Comment by scaidermern** [comment]
This already exists:
![17500](https://github.com/osmandapp/OsmAnd/assets/1040784/fdeb8b21-93e8-4dd2-9df3-c5672d9b6dff)

Not sure what the requirements are for this information to appear.

**Comment by SergeyP2** [comment]
> https://docs.osmand.net/docs/user/widgets/info-widgets#-elevation-map-center

1. I turned on the "Development plugin", but I can't "switch on heightmap option in the Development plugin settings" - this option is gray.

Also I don't understand why to see altitude for POI I should go to "Development plugin"??? do you think this is at any sense logical for a user? :) Why you need to turn any option at all, instead of just showing this info?

> Not sure what the requirements are for this information to appear.

"Counter lines" data file is loaded for this region, I can't imagine what other requirements can be, because all data for altitude is here.

**Comment by DmitryAlexei** [comment]
- Elevation features that depend on heightmaps are available with Pro subscription (see info about Pro features https://docs.osmand.net/docs/user/purchases/android#pro-features). 
- Before 4.5 that was in development (https://docs.osmand.net/blog/osmand-android-4-5-released#terrain-maps-updates)
- Some elevation data is also included in standard maps (for roads only)

**Comment by DmitryAlexei** [comment]
@scaidermern What map style do you use?

**Comment by SergeyP2** [comment]
I really don't understand what is so difficult in this feature, that it takes years to implement. You have "Counter lines" data, you find what line is the nearest, you get an altitude to show, that's it.

![111](https://github.com/osmandapp/OsmAnd/assets/22505250/eba6880d-8230-4b0b-a15d-5c3af3eab6c1)

**Comment by scaidermern** [comment]
> @scaidermern What map style do you use?

This is the default OsmAnd style. Why are you asking? 🤔

**Comment by DmitryAlexei** [comment]
@scaidermern, tnx!
Elevation info is visible in the *point context menu* when one of the elevation widgets is on.

**Comment by DmitryAlexei** [comment]
Useful info about possibility to display elevation in Point context menu might be added to documentation:
- https://osmand.net/docs/user/map/map-context-menu/#select-any-point-long-tap
- https://osmand.net/docs/user/widgets/info-widgets#-elevation-map-center

**Comment by SergeyP2** [comment]
> Elevation info is visible in the point context menu when one of the elevation widgets is on.

See no "elevation widgets", only "Altitude: current location" (added in Right panel)

**Comment by SergeyP2** [comment]
I little bit amused of the discussion here... 

Does this look logical to OsmAnd team, that to see altitude in _point context menu_ you need to show _elevation widgets_? This is so obvious, that you need to add this to documentation. Really? You expect users to read your documentation carefully, instead of making UI more logical and without a strange quirks? Why not just show altitude without this strange condition?

**Comment by scaidermern** [comment]
Is there a misunderstanding here? For me enabling this widget is not required to show the altitude of an arbitrary POI. Enabling 3D relief is, however.

**Comment by SergeyP2** [comment]
> Is there a misunderstanding here? For me enabling this widget is not required to show the altitude of an arbitrary POI. Enabling 3D relief is, however.

I have "Counter lines" data downloaded for the region AND turned ON in Configure map. Would this count as 3D relief?

**Comment by scaidermern** [comment]
> I have "Counter lines" data downloaded for the region AND turned ON in Configure map. Would this count as 3D relief?

No, contour lines are a different thing.

![17859](https://github.com/osmandapp/OsmAnd/assets/1040784/d691ff4c-cffd-429f-8456-3f1c175e864b)

**Comment by SergeyP2** [comment]
> No, contour lines are a different thing.

Hm... Why I should to download one more HUGE data file, if all the altitude information is already here in "Counter lines" file?

**Comment by scaidermern** [comment]
> > No, contour lines are a different thing.
> 
> Hm... Why I should to download one more HUGE data file, if all the altitude information is already here in "Counter lines" file?

Because it isn't, I guess? Or maybe not in a suitable format.

**Comment by SergeyP2** [comment]
> Because it isn't, I guess? Or maybe not in a suitable format.

OK, if OsmAnd team wants implement app features in an awkward way, and insists that this is OK, I, as a user, cannot force you to do things properly.

**Comment by sonora** [comment]
Things are indeed a bit convoluted here:
- Under map render engine v1, the following relief-related downloads are offered:
  - Contour lines  in a vector format
  - Hillshade files (in raster format, i.e. big in size but comparatively fast to display)
  - Slope files (also as raster)
- Under map rendering engine v2,
  -  there is a new 3D vector download offered, which is used to on the fly produce the hillshade or slope effect as needed. This can hence replace the Hillshade/Slope downloads. If it does is currently a setting in the Dev plugin.
  - The Contour lines downloads are still offered. Without doubt also these could be derived from the 3D file, not sure it's efficient and/or planned.

Now any point's elevation could surely be derived on the fly using interpolation and either the 3D or the Contour lines file. I guess it's up to product management to make a decision here, perhaps also if not 3D files could also be supported in v1 so the situation becomes less fragmented?

**Comment by vshcherb** [comment]
Nope we won't be spending time on working pseudo precise algorithm to determine altitude based on derived data, we are going to use original data.
Unfortunately we also won't be making contour lines on the fly based on 3D geotiff data cause it's very very energy consuming

**Comment by sonora** [comment]
Yea, I thought so. Any chance to in the future alao aupport the 3D filea under v1? And perhaps retire the Hillshade/Slope downloads?

**Comment by SergeyP2** [comment]
> on working pseudo precise algorithm

May be this is your problem, you think that users need some "pseudo precise algorithms", when they actually don't care, will it be 3401 or 3406 m of elevation, as long as it will fit in those 10 m that "Counter lines" file already has.

**Comment by vshcherb** [comment]
> 3D file under v1

No, even not planned, all computation is done on video-chip card, so we are not planning for now to move to CPU. However in theory it's possible
