### ISSUE TITLE
"Avoid low emission zones" does not avoid Low-emission zone

### ISSUE THREAD

**Issue by pordini** [osmandapp/OsmAnd#17833]
# 🐞 routing report

### Routing engine

- [X] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Driving / car
(including vehicle parameters set to "Diesel" fuel)

### Start and end points

Here is the boundary for the LEZ: https://www.openstreetmap.org/directions?from=52.09243%2C4.30970&to=
And here is the boundary on the other side: https://www.openstreetmap.org/directions?from=52.08508%2C4.28360&to=#map=19/52.08507/4.28313

From: 52.09208,4.31094 (outside the LEZ on the eastern side)
To: 52.08358,4.27889 (oustide the LEZ on the western side)

### Actual and expected routes
Actual route: http://test.osmand.net/map?start=52.090944,4.311796&end=52.084321,4.280494&type=osrm&profile=car#16/52.0900/4.2806

Expected route would avoid LEZ, probably like this:
http://test.osmand.net/map?start=52.090944,4.311796&end=52.084321,4.280494&inter=52.096907,4.304109&type=osrm&profile=car#16/52.0873/4.2808
### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

Osmand+ 4.5.9 released: 2023-08-01
</code></pre>

**Device and Android/iOS version:**
Pixel 5, Android 13
**Maps used (online or offline):**

- [X] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**
Here is the outline of the entire LEZ: https://www.arcgis.com/apps/webappviewer/index.html?id=51ef15d83fb84fcfa00aeb2fab947b73&extent=69907.3386%2C448776.3921%2C94291.3873%2C460168.3149%2C28992

**Comment by Dima-1** [comment]
[OSM LEZ boundaries](https://www.openstreetmap.org/way/903704656#map=14/52.0767/4.3086) in the Hague doesn't match LEZ boundaries from the site https://www.milieuzones.nl/locaties-milieuzones

**Comment by scaidermern** [comment]
Would be a good idea to add at least an OSM note next time. Just closing this ticket won't fix the problem. The LEZ remains incomplete in OSM and thus also in OsmAnd.

**Comment by XandrexOSM** [comment]
hello, I just extended the LEZ area to the correct zone in OpenStreetMap, no more issue. 
![image](https://github.com/osmandapp/OsmAnd/assets/92858966/a5550a81-0176-43f5-a9e1-3329367cf1c8)

**Comment by XandrexOSM** [comment]
for the record, here was the previous area in OSM 
![image](https://github.com/osmandapp/OsmAnd/assets/92858966/b102d157-1a87-4a0f-a88e-9b1e2cdfaabc)

**Comment by XandrexOSM** [comment]
> Would be a good idea to add at least an OSM note next time. Just closing this ticket won't fix the problem. The LEZ remains incomplete in OSM and thus also in OsmAnd.

yes, @scaidermern is right.

Alternatively @vshcherb / @Dima-1 next time, just ping me when a edit needs to be done in OpenStreetMap, and I'll do it or gladly liaise with other contributors in OSM to have it done.

**Comment by vshcherb** [comment]
I will send update in the chat. And make a note if nobody will pick up. Thanks

**Comment by pordini** [comment]
Maybe you could make an OSM tag? 
If you apply it to an issue, those editing OSM can easily pick it up or relay it to the relevant place (telegram, for instance) and report back once it is completed. That way you don't have to put energy and time into those issues.

**Comment by scaidermern** [comment]
I don't think we need yet another method. Adding OSM notes should be enough.
