### ISSUE TITLE
objects rendered with wrong z order

### ISSUE THREAD

**Issue by quantenschaum** [osmandapp/OsmAnd#17835]
## Description

Seamarks and maybe other objects are drawn with wrong z order such that certain feature get hidden under other features. In the example below at https://osmand.net/map#16/53.4600/6.1658 some fairways (light green) and cable area (transparent red with dotted outline) are partially hidden below tidal flats (wetlands). The are only (slightly) visible because the wetland area is not fully opaque.

(Also when using an underlay with 'show polygons' disabled I would like the wetland polygons to be hidden.)

![Screenshot_20230807-112053-](https://github.com/osmandapp/OsmAnd/assets/3985599/cab79367-664b-4a61-af70-feb4b669b0d3)
![Screenshot_20230807-112102-](https://github.com/osmandapp/OsmAnd/assets/3985599/0206dca7-b36b-4352-9bf0-d98203d77701)

### How to reproduce

Look at https://osmand.net/map#16/53.4600/6.1658 in the boating profile (nautical map style)

### Actual result

Features hidden below wetland area.

### Expected result

Wetland area should be in the background.

**Environment**
OsmAnd Version: 4.5.9
Android version: 13
Device model: Nokia X20

**Comment by quantenschaum** [comment]
It seems to be more difficult than I thought. The proposed simple change only works for render engine 2. With engine 1 and wetland order=4 or 5 the wetland polygon gets hidden behind the water polygon. :grimacing:

**Comment by quantenschaum** [comment]
## render engine 1

wetland order=6 as it currently is, fairway hidden behind wetland (1) and cable area is hidden behide wetland (2) and seabed polygons are hidden behind wetland (X)
![engine1-wetland6](https://github.com/osmandapp/OsmAnd/assets/3985599/89974943-5191-421e-bc6e-ea4a67fbf769)


wetland order=5, it is better but cable area still behind wetland (3)
![engine1-wetland5](https://github.com/osmandapp/OsmAnd/assets/3985599/c3f0fef4-f967-4678-87ca-57cb4c0d9e49)

and when zoomed in, wetland polygon gets behind water polygon
![engine1-wetland5-zoomed](https://github.com/osmandapp/OsmAnd/assets/3985599/f409caff-d79b-405c-964b-ea80617fd1e0)

wetland order=4, the wetland is not display at all
![engine1-wetland4](https://github.com/osmandapp/OsmAnd/assets/3985599/d5fc4001-e8ac-4607-8826-cc0bed56531c)

## render engine 2
wetland order=4, it works as expected
![engine2-wetland4](https://github.com/osmandapp/OsmAnd/assets/3985599/fb017c8a-7829-4d54-a742-f6a7ebea8dc2)


I use diffrent colors for wetland and fairways, but this does not affect the z ordering issue.

**Comment by vshcherb** [comment]
rendering engine v1 is out of support for such complex issues, so it's relevant to be honest. On iOS version v1 was never supported

**Comment by xmd5a2** [comment]
Fixed
Legacy engine:
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/cc311f34-af7b-4baf-8eda-995e2db32be7)

OpenGL engine:
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/41cdd56c-ec79-4de5-ae19-6763a98a0065)

**Comment by quantenschaum** [comment]
Thanks! But I do not consider this as fixed. 

The no anchor area is still partially behind the wetland.

![zorder](https://github.com/osmandapp/OsmAnd/assets/3985599/95345df8-87f6-4509-b606-c6072b4add1e)

**Comment by quantenschaum** [comment]
Is the render.xml file actually updated when the app get updated via the app store?

**Comment by quantenschaum** [comment]
The `order` attribute was [removed for `sand_waves`](https://github.com/osmandapp/OsmAnd-resources/blob/master/rendering_styles/nautical.render.xml#L491). But what about the other sea bed related keys/values?

**Comment by vshcherb** [comment]
Commit is attached https://github.com/osmandapp/OsmAnd-resources/commit/8cc445ad9ed46bc3d6aa9126c926779ece7cb027

**Comment by quantenschaum** [comment]
I meant, in line https://github.com/osmandapp/OsmAnd-resources/blob/master/rendering_styles/nautical.render.xml#L491 the `order` attribute was removed, but shouldn't it also be removed from the surrounding lines?

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#710m, released: 2023-09-01
Latest Netherlands Frisia map downloaded
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/5d194e53-0ed1-45c0-9f6a-74e0cbb4bd2c"  width="300" height="auto"/> </td>
  </tr>
</table>

- as mentioned in comment above (https://github.com/osmandapp/OsmAnd/issues/17835#issuecomment-1681942640) the **No anchor area** is still partially covered by the wetland (middle left part of the picture attached)

**Comment by xmd5a2** [comment]
This is because of sorting by area. Nothing to do in rendering style.

**Comment by quantenschaum** [comment]
It does have to do with the rendering style, because the order is defined there. Transparent areas like `seamark:type=cable_area` should get a higher `order`. This won't hide anything since they are (semi)transparent and ensures that the auto order algorithm does not put them in the back.

**Comment by quantenschaum** [comment]
Some `seamark:area`s are match with `area=true` others with `cycle=true`, some by both. `cable_area` is only in the `area` section.

**Comment by quantenschaum** [comment]
Adding `<case tag="seamark:type" value="cable_area" order="8"/>` [here](https://github.com/osmandapp/OsmAnd-resources/blob/master/rendering_styles/nautical.render.xml#L550) wloud fix https://github.com/osmandapp/OsmAnd/issues/17835#issuecomment-1702874036

**Comment by xmd5a2** [comment]
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/b7c34fd9-4895-4a58-afa4-c6cbf7a73753)
