### ISSUE TITLE
*wn_ref and *cn_ref conflict

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1783]
*wn_ref - hiking network node, *cn_ref - cycling network node. These tags presents in our poi_types.xml.
(for example)
rwn_ref=70
rcn_ref=67
I want value of these tags to be shown as POI name, not additional text value. So I convert value to name. But if same node contains *wn_ref and *cn_ref problems begin - we have 2 POI with the same name: rwn_ref=70, rcn_ref=70. This is incorrect and confusing. Any suggestions?
http://www.openstreetmap.org/node/3209177274
I propose to introduce something like nameTag in entity_convert.

**Comment by vshcherb** [comment]
I think we need to split these objects via entity_convert, I don't see other solution, actually it will be correct, because name of the poi is always *name* tag. Let me know if split doesn't work

**Comment by xmd5a2** [comment]
I already do splitting
```
transportation : rcn_ref 70 Lat 51.51678 Lon 4.002435 id=3209177274 
transportation : rwn_ref 70 Lat 51.51678 Lon 4.002435 id=3209177274 
```
```xml
		<entity_convert pattern="split" from_tag="icn_ref" to_tag1="icn_ref"/>
		<entity_convert pattern="split" from_tag="ncn_ref" to_tag1="ncn_ref"/>
		<entity_convert pattern="split" from_tag="rcn_ref" to_tag1="rcn_ref"/>
		<entity_convert pattern="split" from_tag="lcn_ref" to_tag1="lcn_ref"/>
```
