### ISSUE TITLE
live updates cause duplicated features

### ISSUE THREAD

**Issue by quantenschaum** [osmandapp/OsmAnd#17834]
## Description

When live updates are enabled and update information is available it _sometimes_ happens that the updated features (moved nodes) are shown twice, in the _old_ and in the _new_ position.

### How to reproduce

Look at https://osmand.net/map#16/53.4600/6.1658 in the boating profile (nautical style). Use OsmAnd for a while until the screen shows something like this. I cannot tell what actually triggers this behaviour, but I do observe it frequently.

![Screenshot_20230807-111858-](https://github.com/osmandapp/OsmAnd/assets/3985599/67a619d5-15d9-48b7-8c35-78b838d23379)
![Screenshot_20230807-111906-](https://github.com/osmandapp/OsmAnd/assets/3985599/0792863f-edab-485a-b449-cb085550d10e)

Workaround: quit and relaunch OsmAnd or manually trigger an update of the live data and it works correctly for a while.

### Actual result

Objects are rendered twice.

### Expected result

Object are shown in new (updated) position only.

**Environment**
OsmAnd Version: 4.5.9
Android version: 13
Device model: Nokia X20

**Comment by vshcherb** [comment]
Probably related https://github.com/osmandapp/OsmAnd/issues/14714

**Comment by vshcherb** [comment]
Related to https://github.com/osmandapp/OsmAnd/issues/17898

**Comment by DmitryAlexei** [comment]
Tested 17/08 and 08/09:
- latest nightly builds
- Netherlands Frisia map with latest Live map updates
- nautical map style enabled

August: 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/f95e9655-0eb0-438a-8183-b181656d0434"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/c8354d7c-55ec-44f1-be63-5278253f9913"  width="300" height="auto"/> </td>
  </tr>
</table>

September:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/98112ec0-5244-4bde-8572-2dc1fa1ae8b0"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/0765f803-59e9-4279-bd90-f31dbf9b9d69"  width="300" height="auto"/> </td>
  </tr>
</table>
