### ISSUE TITLE
Android Auto Navigation widget doesn't visible if navigation was launched from device

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#17844]
## Description
Navigation widgets on OsmAnd Android auto version doesn't visible if navigation was started on device.

### How to reproduce
* Connect device to Android Auto
* Launch OsmAnd on device
* Tap on **Menu** – **Navigation** – **Set destination**, select any point
* In Navigation **Settings**, turn on **Simulate navigation**
* When route is calculated tap on **Start**

### Actual result
* OsmAnd on Android Auto doesn't switch to navigation mode

<table style="width:100%">
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/cbba6ddf-bb2b-423f-8534-13a8fd2fa95a
"  width="300" height="auto"/> </td>
  </tr>
</table>   
<table style="width:100%">
  <tr>
    <th>OsmAnd</th>
    <th>Dashboard</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/8566363f-f3cc-4d5d-9d36-fbc667bae74c"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/30484c5f-5ae3-459e-a0b4-6b79853ee983"  width="300" height="auto"/> </td>
  </tr>
</table>   

### Expected result
* OsmAnd on Android Auto is switch to navigation mode when navigation is started on device
*Tested on previous release version `4.4.7`

<table style="width:100%">
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/4e3a45a3-89a1-4777-99e6-753eca95c195
"  width="300" height="auto"/> </td>
  </tr>
</table>   

**Environment**
OsmAnd Version:
Android/iOS version:
Device model: 

https://github.com/osmandapp/OsmAnd/issues/17353

**Comment by tomwinger** [comment]
The same problem occurs if you start navigation in Android Auto, then switch to another app (like a music player), then switch back to OsmAnd. When you return to OsmAnd the navigation widget disappears and is replaced by the main menu. It is then impossible to get the navigation widget back, and you can't even cancel navigation. See this sequence of screenshots:
![IMG_20230804_140451435_HDR_1500px](https://github.com/osmandapp/OsmAnd/assets/60906373/c8b271a9-e4de-447c-bb00-16e5e4dc95ac)
![IMG_20230804_140505125_1500px](https://github.com/osmandapp/OsmAnd/assets/60906373/c15f4fac-2dfe-49f9-be31-ee3047b414fa)
![IMG_20230804_140538123_1500px](https://github.com/osmandapp/OsmAnd/assets/60906373/ea778d11-4def-4862-b203-e9fabc5cf265)
