### ISSUE TITLE
App crashes during start (openGL rendering)

### ISSUE THREAD

**Issue by zipav** [osmandapp/OsmAnd#17841]
[exception (1) (2).log](https://github.com/osmandapp/OsmAnd/files/12280102/exception.1.2.log)
[exception (1) (1).log](https://github.com/osmandapp/OsmAnd/files/12280104/exception.1.1.log)

## Description
Our customer claimed that app crashes 

**Environment**
OsmAnd Version: OsmAnd 4.5.9

**Comment by vshcherb** [comment]
The app looks to have corrupted installation if the issue is not fixed after full reinstall we can continue investigation.
