### ISSUE TITLE
Hillshading and 3d relief

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#17848]
## Description
If you turn off hillshade in Osmand and turn on 3d relief, the hillshade will still be displayed, although it will have a softer picture.  Test video filmed in the Murmansk region in Khibiny.
https://github.com/osmandapp/OsmAnd/assets/12549744/cae7574b-1783-4531-815e-80fd66e5ed1d

It is not clear whether the display of hillshade when the corresponding option is disabled is a bug.

As you can see in the screenshots, with the hillshade option turned on, the picture with shadows looks more rough and step-like.

<table style="width:100%">
  <tr>
    <th>Hillshade off and relief 3d on: </th>
    <th>Hillshade on: </th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/12549744/1d632b25-ce46-4912-adfa-7450e6deddda"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/12549744/1dfa4367-21a4-42ac-b1b0-8b14f98a6bd9"  width="300" height="auto"/> </td>
  </tr>
</table>

**Environment**
OsmAnd Version: OsmAnd~ 4.6.0#584m, Дата выпуска: 2023-08-07
Android/iOS version: 13
Device model: poco f3

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#571m, released: 2023-08-07

https://github.com/osmandapp/OsmAnd/assets/116079541/953d4819-a1a9-40d6-bd61-0d3d6f1ff2ac

**Comment by vshcherb** [comment]
It's not a bug and probably could be documented, with 3D shadows are always displayed

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/map/raster-maps#hillshade--slope

**Comment by shurasmiling** [comment]
https://docs.osmand.net/docs/user/map/raster-maps#hillshade-and-3d-relief
https://docs.osmand.net/docs/user/plugins/contour-lines#3d-relief
