### ISSUE TITLE
Add support for highway=services

### ISSUE THREAD

**Issue by Ratterkresch** [osmandapp/Osmand#1784]
Hi All,
Actually you can find highway=rest_area , when you are using OsmAnd for navigation on highways.
But this is not sufficcient support for touring on a highway.
    
In Germany, Austria, etc. there is a big difference between "rest area" where you cannot eat and refill fule and a "service area" where you can eat and get fuel too. 
These "service areas" are called "Raststätte" (highway=services) , see https://en.wikipedia.org/wiki/Rest_area#Germany_and_Austria.

I'd like to request to add the "service areas"/ "Raststätte"/"highway=services" to the default list of POIs in Osmand.
So you would be able find the nearest service station for refueling and food when driving on a highway.
It would be nice to have this visible also, when you select POI category 
<string name="poi_personal_transport">Individualverkehr</string>

regards,
Ratterkresch

If needed, I would be able to create a svg graphic for this POI too.

**Comment by xmd5a2** [comment]
Already added as POI (in nightly version) with icon
