### ISSUE TITLE
scale bar not scaled correctly with render engine 2

### ISSUE THREAD

**Issue by quantenschaum** [osmandapp/OsmAnd#17846]
## Description

render engine 2 allows stepless zooming, but the scale bar at the bottom of the screen only changes size in fixed steps, the range rings scale correctly

### How to reproduce

- enable render engine 2
- zoom in and out
- observe scale bar at bottom of screen

### Actual result

scale bar changes size _only in fixed steps_ when zooming

### Expected result

scale bar changes size when zooming

**Environment**
OsmAnd Version: 4.5.9
Android version: 13
Device model: Nokia X20

**Comment by vshcherb** [comment]
We still plan to update once fingers ares released

**Comment by quantenschaum** [comment]
"Plan" means it is not yet implemented but in the pipeline?

Update on release would be sufficient IMHO.

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#656m, released: 2023-08-22
Scales bar scales correctly with stepless zooming

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/86a78227-250c-4428-afbb-79c486d7a89e"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/ea1d428c-c17a-4993-8345-c99f1b140ddb"  width="300" height="auto"/> </td>
  </tr>
</table>

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/deb0813a-a9b0-4fe7-a2da-a371e43cadee"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/94d1cef7-2334-440f-9fab-f77a3086a588"  width="300" height="auto"/> </td>
  </tr>
</table>
