### ISSUE TITLE
entity_convert and Los Angeles subway stations

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1785]
I'm trying to distinguish Los Angeles subway system from San Francisco using operator tag from subway relation.
```xml
		<type tag="subway_region" value="losangeles" additional="true" minzoom="12" />
```
```xml
		<entity_convert pattern="tag_transform" from_tag="railway" from_value="station" if_region_name="california" if_tag1="operator" if_value1="Los Angeles County Metropolitan Transportation Authority" to_tag1="railway" to_value1="station" to_tag2="route" to_value2="subway" to_tag3="station" to_value3="subway" to_tag4="subway_region" to_value4="losangeles"/>
```
Test with relation Metro Red Line (2810818) and railway station Universal City (16298122)
https://dl.dropboxusercontent.com/u/4624786/osm/test_california_subway.zip
Railway station tags:
```
name=Universal City
public_transport=stop_position
railway=station
```
Relation tags:
```colour=red
name=Metro Red Line
network=Metro Rail
operator=Los Angeles County Metropolitan Transportation Authority
public_transport:version=2
ref=802
route=subway
type=route
```
What I get:
```
Point types [railway-station (5), public_transport-stop_position (19)] add_types [route-subway(2), color_red(6), station-subway(24)] Names [name(1) - Universal City] id 16298122
```
I'm expecting subway_region=losangeles tag.

**Comment by vshcherb** [comment]
Implemented verbose feature: adding  verbose="true" to entity_convert shows debug information like
{{{
INFO: Apply entity convert from 'tag=railway val=station' to {name=Universal City, public_transport=stop_position, railway=station} in ROUTING - has failed due to if conditions
}}}

**Comment by vshcherb** [comment]
<type tag="operator" minzoom="15" additional="text" relation="true"/>
adding this line fixes the issue or may be having name_prefix will fix it too

**Comment by xmd5a2** [comment]
This line works, but now I can't exclude "operator" tag from adding to map data
```xml
Point types [railway-station (5), public_transport-stop_position (19)] add_types [route-subway(2), color_red(6), subway_region-losangeles(24), station-subway(25)] Names [name(1) - Universal City, operator(9) - Los Angeles County Metropolitan Transportation Authority] id 16298122
```
```xml
<type tag="operator" minzoom="15" additional="text" relation="true" map="false" poi="false"/>
```
map="false" poi="false" simply has no effect

**Comment by vshcherb** [comment]
operator issue has fixed
