### ISSUE TITLE
Search results are weird (i.e. not sorted by proximity to GPS location)

### ISSUE THREAD

**Issue by lcosmin** [osmandapp/OsmAnd#17850]
## Description

I'm encountering this issue frequently when searching for something in OsmAnd (could be a bug, could be by design).

When I type something in the search box, I expect results to be ordered by proximity to my current location. But often I get results hundreds of km away before the thing I'm looking for (which is next to me). 

### How to reproduce

GPS activated, map centered on my location, search for the name of a hotel or street a little further away. 

### Actual result

For example, being in [this location](https://www.openstreetmap.org/node/582513565) and searching for "Brad" (hoping to find street called "Bulevardul Ion Ionescu de la Brad"), I get [these results](https://imgur.com/ahmfgkx).  Notice that the first results are 200+ km away.

Another example, where the results are even worse. Being on a hiking trail [here](https://www.openstreetmap.org/node/468355980) , searching for "Silva" (wanting to find this [alpine hut](https://www.openstreetmap.org/way/420789403) ), I get [these results](https://imgur.com/eas9mJ3). The hut i'm looking for is close to the end of the results.

### Expected result

Results should be sorted in ascending order, with those closer to my GPS position being first.

 I don't know, maybe i'm doing something wrong, but I feel this should work "out of the box" and the default behavior is not what I'd normally be expecting.

PS: I have the offline vector maps.

**Environment**
OsmAnd Version:  4.5.9 
Android/iOS version:  Android 13
Device model: Samsung S20 FE (SM-G781B/DS)

**Comment by TheSnoozer** [comment]
Thanks for raising this, I think this was raised already in https://github.com/osmandapp/OsmAnd/issues/16397.

**Comment by lcosmin** [comment]
Looks like the same behaviour, indeed. I'll close this, then.
