### ISSUE TITLE
android 12 : writing to sdcard access denied (not /storage/XXXXX/Android/*)

### ISSUE THREAD

**Issue by jlmxyz** [osmandapp/OsmAnd#17852]
## Description
I want to store my osmand data on sdcard on android 12, so I choose manual path, enter the sdcard path, osmand begins the move process and fail because of access rights 
looking into the sdcard shows that osmand did create the folder but can't access it's content

### How to reproduce
go to parameters - osmand parameters - storage folder - then enter a path to a sd card

### Actual result
process begin but fail on access storage rights, the destination folder is created
using the shared multiuser storage on sdcard succeed, but since there is a bug on android the obb folder is not shared across users
PS : would be nice if only some data could be shared like maps when others are kept private like tracks, point of interest...

### Expected result
the data should be stored into the sdcard folder

**Environment**
OsmAnd Version: 4.4.7
Android/iOS version: 12
Device model: samsung/n975f /e/os

**Comment by pebogufi** [comment]
I use a Samsung S10 with Android 12 since about half a year without problems with Internal mem 
/storage/emulated/0/Android/**media**/net.osmand.plus
It also works (tested) with
/storage/xxxx-xxxx/Android/**media**/net.osmand.plus
Repace xxxx-xxxx with your sd card.

Important is **media**, instead of obb

**Comment by jlmxyz** [comment]
seems indeed that using media folder is a workaround, however there still is a problem if I want to use another folder outside the realm of */Android/* folders....

**Comment by sonora** [comment]
It's a google Play Store restriction - arbitrary folders are not allowed anymore, see https://github.com/osmandapp/OsmAnd/issues/16059.

**Comment by pebogufi** [comment]
> seems indeed that using media folder is a workaround, however there still is a problem if I want to use another folder outside the realm of _/Android/_ folders....

Why do you want to use a different folder, if media works ?

**Comment by jlmxyz** [comment]
why do you want to store your clothes in the wardrobe if the storage in the garage works? maybe because I like to arrange my data in a way that is not google's way of thinking? why should i have to follow the way google decided me to store my data? why everyone has to follow google's decisions? most data in */Android/​* folders is just useless data that you don't care about, finding the right useful data in it is just like seeking the trash for your precious document... it's like the way they manage media files, images, photos.... everything out of folders, in a big messy storage space, that you've to search for hours before finding the document you need... yes, google, apple, decided for us that it's better to forget what is a folder, that IA is better and just have to ask some online service to find all the photo matching the word "me".... not my way, my data is organized the way I can search them fast... in a way that is natural for me to find them, not in an obscure net.osmand.plus (and at least, it's one that is not too long or too obscure....)

------- Original Message -------

**Comment by DmitryAlexei** [comment]
Probably related https://github.com/osmandapp/OsmAnd/issues/14165#issuecomment-1557334038

**Comment by foegra** [comment]
> I use a Samsung S10 with Android 12 since about half a year without problems with Internal mem /storage/emulated/0/Android/**media**/net.osmand.plus It also works (tested) with /storage/xxxx-xxxx/Android/**media**/net.osmand.plus Repace xxxx-xxxx with your sd card.
> 
> Important is **media**, instead of obb

Does not work on Android 14

**Comment by sonora** [comment]
See #16059.
