### ISSUE TITLE
Coastline nautical style rendering errors

### ISSUE THREAD

**Issue by quantenschaum** [osmandapp/OsmAnd#17851]
## Description

In certain places like https://osmand.net/map#15/53.5000/6.4172 when zoomed in close enough the map is not rendered correctly. I am using the boating profile/nautical map style here, but this also happens with other map styles.

With render **engine 1** land is displayed instead of water (there is a "hole" in the map and the background color is visible)

wrong (errors marked red)
![Screenshot_20230808-102245](https://github.com/osmandapp/OsmAnd/assets/3985599/8bf872ac-63cd-4911-b294-4dcf71980151)

correct when zoomed out a bit
![Screenshot_20230808-102252](https://github.com/osmandapp/OsmAnd/assets/3985599/5300c76f-1502-4feb-9130-1257a04b5520)

With render **engine 2** this happens already at lower zoom levels
![Screenshot_20230808-102309](https://github.com/osmandapp/OsmAnd/assets/3985599/fb503d24-813e-43a3-b3ec-327ffab3f147)
![Screenshot_20230808-102316](https://github.com/osmandapp/OsmAnd/assets/3985599/bc8d9dc6-2c25-4c52-9d2f-892c24ea467c)

### How to reproduce

zoom in on the location above

### Actual result

see screenshots, there are holes in the map

### Expected result

no holes in the map

**Environment**
OsmAnd Version: 4.5.9
Android version: 13
Device model: Nokia X20

**Comment by cepprice** [comment]
World_basemap_mini contains island that is non-existent in OSM
![image](https://github.com/osmandapp/OsmAnd/assets/31509211/be7be545-cee6-47a4-bc4c-56810f23bdd2)

**Comment by xmd5a2** [comment]
Fixed. Basemap was updated.
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/1ec85530-dac2-46d8-955c-9c1bb23de60d)

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#1003m, released: 2023-11-09
No more strange artifacts with fresh November maps

<table style="width:100%">
  <tr>
    <th>**V2**</th>
    <th>**V1**</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/116079541/2ce11b51-87b6-4941-b211-6bf004852040"  width="200" height="auto"/></td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/116079541/2e9d0236-16d0-443b-8649-2f09d041d22d"  width="200" height="auto"/></td>
  </tr>
