### ISSUE TITLE
"Reset to default" Memory allocated for routing causes crash

### ISSUE THREAD

**Issue by zipav** [osmandapp/OsmAnd#17862]
[exception.log](https://github.com/osmandapp/OsmAnd/files/12291929/exception.log)

[exception1.log](https://github.com/osmandapp/OsmAnd/files/12291928/exception1.log)

## Description
When trying to resetting to default memory allocated for routing crash occurs

### How to reproduce
- Menu 
- Plugins
- OsmAnd Development
- Settings
- Memory allocated for routing
- Reset to default

### Actual result
App crashes

### Expected result
Resetting without crash

**Environment**
OsmAnd Version: OsmAnd Nightly 4.6.0#589m
Android version: 12
Device model: Nokia 5.3

https://github.com/osmandapp/OsmAnd/assets/123936521/1940b310-3224-4300-ac47-12df0000ea31

**Comment by dmpr0** [comment]
# Review
- [ ]  Crash [exception (3).log](https://github.com/osmandapp/OsmAnd/files/12342749/exception.3.log)

> Device : bluejay
> Brand : google
> Model : Pixel 6a
> Product : bluejay_beta
> Build : UPB4.230623.007
> Version : 14
> App Version : OsmAnd~
> Apk Version : 4.6.0#610m 4600
>
