### ISSUE TITLE
Transparent status bar option doesn't make status bar transparent on the map screen

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd#17863]
OsmAnd~ 4.6.0#586m, released: 2023-08-08 and OsmAnd 4.5.9, released: 2023-08-01

For me, there are two issues with **Transparent status bar**
- status bar isn't transparent on the map screen (and transparent in the settings menus)
- after **Transparent status bar** is been disabled, toolbar is cut off (restart of the app helps to make toolbar big again)

Steps to reproduce:
- Menu > plugins > development plugin > toggle Transparent status bar option
No matter if *Fullscreen mode* is on or not (Menu > settings > profiles > general settings > fullscreen mode)

<table style="width:100%">
 <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/8f2bc620-367e-483e-b836-e23fc7de0252"  width="300" height="auto"/> </td>
 </tr>
</table>

https://github.com/osmandapp/OsmAnd/assets/116079541/239d92c2-f597-47e3-9810-966b64d35289

_Originally posted by @DmitryAlexei in https://github.com/osmandapp/OsmAnd/issues/13989#issuecomment-1669580985_

**Comment by zipav** [comment]
OsmAnd Nightly 4.6.0#632m, released: 2023-08-17

Issue is still reproduced.


https://github.com/osmandapp/OsmAnd/assets/123936521/8ddace0f-335b-49f8-95a3-c7f138a1ffeb

**Comment by emonect** [comment]
Same issue here. Really annoying to have that big black status bar on top when in horizontal mode. Removes so much real estate to show the map !!! Please help to fix this, thanks :-)
