### ISSUE TITLE
Hide city blocks as it clutters the map

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd#17868]
# 🚀 feature request

### Description

One of our users wants to have an ability to turn off displaying of quarter names. 
The app favours quarters over street names, it becomes quite annoying to use. 

### Describe the solution you'd like

Add option to hide names of quarters names in **Configure map > Hide**

**Comment by vshcherb** [comment]
Screenshot needed and OSM classification (districts? suburbs?)

**Comment by mickepe** [comment]
This what a default look of Stockholm shows. The quarters are never used by ordinary people, preferably the names of the streets should be shown instead.
![image](https://github.com/osmandapp/OsmAnd/assets/14888723/8fae175b-816b-4f6a-97f4-d5004426c491)

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#634m, released: 2023-08-18

<table style="width:100%">
  <tr>
    <th>Befor</th>
    <th>Now</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/14888723/8fae175b-816b-4f6a-97f4-d5004426c491"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/9a4186f5-2115-49d8-8486-4d5b5021c522"  width="300" height="auto"/> </td>
  </tr>
</table>
