### ISSUE TITLE
Track context menu is shown instead or route calculation

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#17860]
## Description
Track context menu is shown instead or route calculation

### How to reproduce
* Open **Menu** – **Navigation** – **Set destination** - **Search**
* Select any track from Search screen

### Actual result
<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/d1de2380-dd1d-49a2-9b41-3ddf5ad7766b"  width="300" height="auto"/> </td>
  </tr>
</table>   
</details> 

* Track context menu is open above the Route preparation menu

### Expected result
* Follow track screen should be shown to follow default track selection behavior

**Environment**
OsmAnd Version:
Android/iOS version:
Device model:

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#634m, released: 2023-08-18
Now after choosing a track (navigation > *to* (set destination) > search) opens follow track menu
As for me, it is not clear, that to proceed you should tap *Close* button 


https://github.com/osmandapp/OsmAnd/assets/116079541/098695de-7ddf-47db-b189-e68c1a60defb
