### ISSUE TITLE
12 IllegalAccessException at startup

### ISSUE THREAD

**Issue by Codain** [osmandapp/OsmAnd#17879]
## Description
When opening OsmAnd in Android, I got several java.lang.IllegalAccessException.

### How to reproduce

1. Start an adb recording (`./adb logcat -c` then `./adb logcat *:W`)
2. Start OsmAnd

### Actual result
See log attached: [logcat.log](https://github.com/osmandapp/OsmAnd/files/12307064/logcat.log)

- 12x java.lang.IllegalAccessException
- 34w Warnings

### Expected behavior

No Errors or Warnings (only Debug or Information levels).

**Environment**
OsmAnd Version: 4.4.7
Android/iOS version: Android 12
Device model: Fairphone 3+

**Comment by vshcherb** [comment]
Not a good news obviously
