### ISSUE TITLE
Wrong description for Fullscreen mode

### ISSUE THREAD

**Issue by zipav** [osmandapp/OsmAnd#17870]
## Description
The description of the full screen mode does not give an idea of what happens when this option is activated.

### How to reproduce
- Menu 
- Settings
- Configure profile
- General settings
- Fullscreen mode: ON

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/0a9dbc98-8a97-49e8-aacb-9a114d80b074"  width="300" height="auto"/> </td>
  </tr>
</table>

### Actual result
Wrong description: A tap on the map toggles the control buttons and widgets. 

### Expected result
Something like 

A tap **on an empty space** on the map **hides** control buttons and widgets.
or 
A tap **on an empty space** on the map toggles **to hide** the control buttons and widgets.

**Environment**
OsmAnd Version:  OsmAnd Nightly 4.6.0#589m
Android version: 12
Device model:  Nokia 5.3

**Comment by DmitryAlexei** [comment]
The description of this option in the docs should also be updated
https://osmand.net/docs/user/personal/profiles#other

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/personal/profiles#other
and strings description

**Comment by Velomeloman** [comment]
> https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/res/values/strings.xml#L2590
> The description of this option in the docs should also be updated
> https://osmand.net/docs/user/personal/profiles#other

The description has been corrected in the documentation, but remains unchanged in the application
https://github.com/osmandapp/OsmAnd/blob/00b4dbb97fb81c2702a42208364d2847bf6ea48c/OsmAnd/res/values/strings.xml#L3183
