### ISSUE TITLE
New UI for Open Track screen – Tracks

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#17871]
## Description
We need to replace different dialog that share the same function: select a track. 
Places from where tracks can be opened:
* **Plan route** > **Open existing track**
* **Plan route** > **Add to a track**
* **Navigation** > **Follow track** > **Select**
* **Markers** > **Groups** > **Add** > **Track waypoints**
* OsmAnd Development - Settings – Simulate your position – **Select track**
* Quick action > Simulate your position > Select track

<table style="width:100%">
  <tr>
    <th>Current</th>
    <th colspan=2>Proposed</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/058e259e-73d6-4e10-ac17-876e777e5b2c"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/11048fe8-9f06-417a-9cab-bbb5f69466cb"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/b0b9e4e5-fc37-4cbf-9239-c5f1c009f325"  width="300" height="auto"/> </td>
  </tr>
</table>  

## Places to apply new dialog
- [x]  Open existing track
- [x]  Add to a track

## New dialog
<table style="width:100%">
  <tr>
    <th> Visible </th>
    <th>All tracks</th>
    <th> Folders </th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/e06a429b-a5af-44e9-80c0-9c4956700501"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/5ce39715-907e-4cdc-816b-63efabdb0fe2"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/bda0e7e0-7a13-42bb-8652-2707c7b55a13"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x]  Use native AppBar and Tabs
- [x] Show 3 tabs: Visible, All tracks, Folders
- [x] Tap on tracks, should select / open track or continue started flow
- [x] Hide 3 dots (menu) button for tracks and folders
- [x] Hide 3 dots (menu) for Folders AppBar

### Visible, [Figma](https://www.figma.com/file/e2RHNzqCgUhcfAaQafHmQ8/My-places?type=design&node-id=3617%3A211230&mode=dev)
<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <th>Empty state</th>
    <th>Default state</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/3e477f6a-920c-43db-8ec4-a8dd53c05e71"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/6d2b2db0-0f95-4df1-81d6-bd1ec22871d9"  width="300" height="auto"/> </td>
  </tr>
</table>   
</details>  

- [x] Show list of visible tracks
- [x] Show empty state if there is no visible tracks

### All tracks, [Figma](https://www.figma.com/file/e2RHNzqCgUhcfAaQafHmQ8/My-places?type=design&node-id=3843%3A42223&mode=dev)
<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <th>Empty state</th>
    <th>Default state</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/5fc1c200-c046-4ddf-9a6f-47fe3e353ed3"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/ec16a1b6-992e-41a3-a61f-ddd07a1312a3"  width="300" height="auto"/> </td>
  </tr>
</table>   
</details> 

- [x] Show all tracks (similar to Configure Map – Tracks - All)
- [x] Show empty state if there is no tracks

### Folders, [Figma](https://www.figma.com/file/e2RHNzqCgUhcfAaQafHmQ8/My-places?type=design&node-id=3843%3A44225&mode=dev)
<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <th>Empty state</th>
    <th>Default state</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/674c9f6a-2a8a-4964-ae40-9881c235220e"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/82a3bba5-1f9a-4f49-837b-df8a04b09566"  width="300" height="auto"/> </td>
  </tr>
</table>   
</details> 

- [x] Show folder and tracks, the same as in My Places – Tracks
- [x]  Show empty state if there is no tracks

**Comment by dmpr0** [comment]
# Review 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src=""  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [ ] Remove menu button from tracks and folders

- - -


- [ ] Import doesn't work. Trying to import track into empty folder leads to import those track into **Import** folder
- [ ] Import folder tab is appears after track import.

**Comment by sonora** [comment]
Trouble is that by my tests also here we introduce the "time lag" issue #17805. In the case where you say
- "Missed Places": Navigation > Follow track > Select is still use old UI

using that is still **instantsneous**, in the cases already touched by this change I experience the ~10 sec wait, every time.

**Comment by DmitryAlexei** [comment]
- [ ] fix tests

**Comment by Chumva** [comment]
UI fixes for tests were added [here](https://github.com/osmandapp/OsmAnd/commit/7ef8167dd06401d2847737878d05227828d5a219)

**Comment by EugeneZmeuk** [comment]
**29.03.2024 Review**
- [ ] changing of screenshot [Plan a route](https://osmand.net/docs/user/plan-route/create-route#add-to-a-track) article

**Comment by shurasmiling** [comment]
- https://docs.osmand.net/docs/user/personal/tracks#follow-track
- https://docs.osmand.net/docs/user/map/tracks-on-map#tracks-in-configure-map-menu
