### ISSUE TITLE
Night build - 'add favorite' -> 'modify' (to relocate a favorite) no longer available?

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#1787]
In today night build I tried to reposicion an existing favorite. It used to be possible to do the reposicioning by selecting the new location, choose the star icon to add to favorites, and then the option to 'modify', then choose by name or sort by distance.

That option is no longer visible.
Was it relocated or removed?

**Comment by vshcherb** [comment]
Yes, looks like we missing button "Replace" with another favorite.

**Comment by Barrocas** [comment]
Fixed on today night build. Working as expected. Thanks.
