### ISSUE TITLE
@osmandapp Annoying to see that this bug is still present on Android 13. A bit sloppy in my opinion. This is the only app I have seen that suffers from this problem.

### ISSUE THREAD

**Issue by ohoes** [osmandapp/OsmAnd#17889]
@osmandapp Annoying to see that this bug is still present on Android 13. A bit sloppy in my opinion. This is the only app I have seen that suffers from this problem.

As far as I am concerned, it may be resolved by now. This problem has been going on for a long time.
![Screenshot_20230810-133617_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/110535097/522bb6b5-46b3-42b1-9395-931c4c4e48ea)

_Originally posted by @ohoes in https://github.com/osmandapp/OsmAnd/issues/15704#issuecomment-1673074525_

**Comment by scaidermern** [comment]
It is not necessary to open a new ticket. The old one is still open.
