### ISSUE TITLE
Car route is slower when adding no intermediate point, and faster when adding one

### ISSUE THREAD

**Issue by robobobeng** [osmandapp/OsmAnd#17882]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Car profile

### Start and end points

Start point: 44.09462, 6.23368 (city of Digne-les-Bains)
End point: 44.24711, 6.69826 (a parking in the mountains)

### Actual and expected routes
Actual route: A route going north by the city of Barcelonnette, its total time is 2 hours and 9 minutes:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/41967635/a9e49ad0-f867-4517-8ae5-457eb48bd240"  width="300" height="auto"/> </td>
  </tr>
</table>

Expected route: A route going south by the city of Barrême, its total time is 1 hour and 38 minutes. I can force OsmAnd to choose this route by adding an intermediate point (namely 43.95599, 6.42761)
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/41967635/4d34094b-e573-4244-87f3-df7241f33098"  width="300" height="auto"/> </td>
  </tr>
</table>

### Is this a regression?
no 

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

OsmAnd+ 4.5.9, released on 2023-08-01
</code></pre>

**Device and Android/iOS version:**
Google Pixel 7, Android 13

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**
It is very strange to me that by adding an intermediate point, OsmAnd is able to reduce the duration of the total route from 2:09 to 1:38. Then why doesn't it choose the 1:38 route in the first place? This route seems consistent with the one suggested by Google Maps (which is the same and has a duration of 1:35 according to Google Maps). I don't understand why OsmAnd suggests using a slower route when there is no intermediate point. Isn't the travel time the most significant variable in the routing engine? (I am NOT using "fuel-efficient route" parameter)

**Comment by robobobeng** [comment]
Isn't travel duration the most important parameter in the cost calculation? Why does a route that is 30 minutes faster ends up with a higher cost?

**Comment by robobobeng** [comment]
Then if the expected route has a lower cost, why does OsmAnd chooses another route?

**Comment by vshcherb** [comment]
Bug is related to base routing navigation cause there is no enough high class roads so it chooses long route (with slow routing enabled - 2-base in dev settings) there is no such problem.

Merged to https://github.com/osmandapp/OsmAnd/issues/15802

**Comment by vshcherb** [comment]
Issue is fixed
