### ISSUE TITLE
Simplify to have only two track folder sort settings

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#17886]
As a follow-up to https://github.com/osmandapp/OsmAnd/issues/17475#issuecomment-1672649169 and to solve the associated issues mentioned: Is it really necessary to remember the sort setting for the track listing **per each folder**?

There are essentially two types of folders:
- "rec", "import" are system folders used for recordings and imports.
- All other folders are "organizing / archiving" folders the user creates.

So why would we not have _only two sort settings_, one applies for rec / import, the other for all other folders? And as default, I agree with @Rowin63 hat "A-Z" is perfect for the org folders, and "Last Edited" for the rec / import folders?

**Comment by vshcherb** [comment]
Yes, each folder different settings - simple and clear for documentation and usage. Recursive change is a question to be honest.

Users shouldn't have 1000 folders or they shouldn't have 1000 tracks inside folders if they have > 100 tracks. Organizing tracks will be always too much of nightmare users vs developers. We need to focus on Search / Smart folders now
