### ISSUE TITLE
Use Different Sources of data

### ISSUE THREAD

**Issue by C0deBr3ak3r** [osmandapp/OsmAnd#17881]
# 🚀 feature request

### Description

Recently the [Overture Maps Foundation](https://overturemaps.org/) [release it's first version of their Open Map data](https://overturemaps.org/download/overture-july-alpha-release-notes/), it would be nice if we can implement support for its data as a complement to OSM's one. The project still in it's beginning so is to expect some problems with it, however it still is a good idea to keep an eye on it

### Describe the solution you'd like

There is [a reference to implement queries to access the data](https://github.com/OvertureMaps/data) and this might be the only way for now

### Describe alternatives you've considered

As the time passes abstractions layers will be created to interact with the data in a cleaner and more concise way

**Comment by scaidermern** [comment]
Please no. We don't need bad quality POIs from evil cooperations.

See:
 * https://community.openstreetmap.org/t/overturemaps-org-big-businesses-osmf-alternative/6760
 *  https://community.openstreetmap.org/t/overture-maps-first-dataset-release/101702

**Comment by vshcherb** [comment]
Unlikely but you can do it your own by converting data to OSM XML and use it inside OsmAnd

**Comment by C0deBr3ak3r** [comment]
I get it, for now maybe isn't a good idea, as I said the project is in its beginning, but this may be a good thing in the future, my issue was more to initialize a discussion about the viability of it, but if the concerns is about the founding members being big techs with a questionable reputation I get it
