### ISSUE TITLE
Some healthcare specialities are not visible

### ISSUE THREAD

**Issue by axayr25** [osmandapp/OsmAnd#17885]
## Description

I'm adding hospital specialities and some specialities are not visible.

my healthcare speciality list: 
`anaesthetics;neurosurgery;oncology;paediatric_surgery;paediatric_dentistry;paediatrics;dermatology;endodontics;endocrinology;infectious_diseases;physiatry;gastroenterology;surgery;geriatrics;pulmonology;ophthalmology;haematology;internal;allergology;gynaecology;cardiac_surgery;cardiology;otolaryngology;nephrology;neurology;nuclear;orthodontics;orthopaedics;periodontics;plastic_surgery;rheumatology;psychiatry;urology;dental_oral_maxillo_facial_surgery;radiology;`

option 1- add speciality with healthcare:speciality=XXX;XXX;XXX

result: these specialities not visible: 
`allergology;cardiac_surgery;endodontics;geriatrics;haematology;infectious_diseases;internal;paediatric_dentistry;paediatric_surgery;periodontics;rheumatology`

option 2- add speciality with healthcare:speciality:XXX=yes

result: all specialities not visible.

option 3- add speciality with health_specialty:XXX=yes

result: same specialties not visible as option 1

### How to reproduce

add hospital to osm and add specialities

### Actual result

not visible specialities

### Expected result

all specialities should be visible

**Environment**
OsmAnd Version: 4.4.7~ 
Android/iOS version: android 10
Device model: ---

**Comment by DmitryAlexei** [comment]
healthcare:speciality more than 110.000 objects ([taginfo](https://taginfo.openstreetmap.org/keys/healthcare%3Aspeciality#overview))

Tags (allergology; cardiac_surgery; endodontics;geriatrics; haematology; infectious_diseases; internal; paediatric_dentistry; paediatric_surgery; periodontics;rheumatology) **are not visible** when they are single. For example:
- [allergology](https://taginfo.openstreetmap.org/tags/healthcare%3Aspeciality=allergology#overview) = 96 objects https://www.openstreetmap.org/way/417315903
- [cardiac sugery](https://taginfo.openstreetmap.org/tags/healthcare%3Aspeciality=cardiac_surgery#overview) = 5 objects https://www.openstreetmap.org/node/6575626712
- [rheumatology](https://taginfo.openstreetmap.org/tags/healthcare%3Aspeciality=rheumatology#overview) = 98 objects  https://www.openstreetmap.org/#map=18/50.9478633/21.3884969

<table style="width:100%">
  <tr>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/d1785dff-531d-47da-9753-94fd54b78f67"
width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/efee4528-4ba0-468f-a87f-57c8bac3b441"
width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/3339b3c2-1a1c-4145-bb3b-acd3270a5a9e"  width="300" height="auto"/> </td>
  </tr>
</table>

This tags and also some other tags are also invisible, in case they are mixed with other tags:
- https://www.openstreetmap.org/node/6390325698 healthcare:speciality = general;internal;rheumatology **visible only general** (internal - 3 objects according to taginfo, rheumatology - 98)
- https://www.openstreetmap.org/node/9049662617 **gastroenterological_surgery** tag (1 object according to taginfo) is not visible
- https://www.openstreetmap.org/way/679181288 **occupational** (1 object) **paediatric_surgery** (4 objects) **pulmonology** (21 object) are not shown
 - **Items in the drop-down list are sorted not in alphabetical order**
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/7d7f33a0-8cfa-452c-9e01-043a004f8d21"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/3664102e-1681-4480-9c84-2290b3f9c241"  width="300" height="auto"/> </td>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/596430b6-6f85-4b1c-9e0a-126aee2d599d"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
Some values are very rare probably we could add support for values which are described in Wiki ~ 50

**Comment by xmd5a2** [comment]
`healthcare:speciality` values were updated. Added more than 30 new values. Multispecialities should be fixed another way.

**Comment by vshcherb** [comment]
Multispeciality should be fixed same as sport / cuisine  https://github.com/osmandapp/OsmAnd/issues/8483

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#736m, released: 2023-09-08
- Some of previously not visible single tags (tested allergology; cardiac_surgery; rheumatologyl) are visible now. 
<table style="width:100%">
  <tr>
    <th>50.94812 21.37978 </th>
    <th>50.87312 20.60010</th>
    <th>50.94786 21.38850</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/8be8e71f-fe26-4126-99ee-41a61c8d2dc8"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/4cede323-fa7f-4c89-8b50-09d2d2d6b931"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/f3d88137-245d-431b-87b9-06719e07071c"  width="300" height="auto"/> </td>
  </tr>
</table>

- Also displayed previously not visible paediatric_surgery; vascular_surgery (48.45707 8.41015) 
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/64d56002-d118-4826-ac0f-ad45e87f6aa7"  width="300" height="auto"/> </td>
  </tr>
</table>

- Not displayed geriatrics; phoniatrics (https://www.openstreetmap.org/way/670481735 coordinates 52.51534 13.56452) obstetrics; family_medicine; haematology; oncology (https://www.openstreetmap.org/node/9283880392 coordinates 52.51936 13.56686). 
- Probably fresh maps are needed.
