### ISSUE TITLE
Deleted poi are visible in live update

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#17887]
## Description
On the map of the Russia_far-eastern-federal-district_asia.obf , poi are visible removed a few days ago.
Moreover, if you download a map of a smaller area (Russia_sakhalin_asia.obf), then these poi will be deleted there.

https://www.openstreetmap.org/node/8872382317
https://www.openstreetmap.org/node/8872329718

**Environment**
OsmAnd Version: OsmAnd~ 4.6.0#595m, Дата выпуска: 2023-08-09
Android/iOS version: 13
Device model: poco f3

**Comment by vshcherb** [comment]
Tested on map - deleted https://creator.osmand.net/aosmc/russia_sakhalin_asia/Russia_sakhalin_asia_23_08_00.obf.gz
```
Point types [osmand_change-delete (614)] id 1135658203996 osmid 8872329718
Point types [osmand_change-delete (614)] id 1135664936684 osmid 8872382317
```

**Comment by vshcherb** [comment]
On this one same picture https://creator.osmand.net/aosmc/russia_far-eastern-federal-district_asia/Russia_far-eastern-federal-district_asia_23_08_00.obf.gz

So I can't reproduce, try to redownload far - estaern it's probably a bug with cache

**Comment by Nine-Tailed** [comment]
> So I can't reproduce, try to redownload far - estaern it's probably a bug with cache

Yes, clearing the cache helped.

**Comment by vshcherb** [comment]
Problem looks persistent, it would be good to know whether just restart could help

**Comment by scaidermern** [comment]
> Problem looks persistent, it would be good to know whether just restart could help

For me (#17898) restarts don't help.
