### ISSUE TITLE
Create POI in advanced mode w/o required fields

### ISSUE THREAD

**Issue by mikeshenson** [osmandapp/Osmand#1788]
When creating a POI under the <b>advanced option</b>,<br> It would be nice to <b>"commit"</b> a POI with out typing in the <b>"POI Type"</b> <br>
![2015-10-08-09-21-57](https://cloud.githubusercontent.com/assets/7337270/10369828/e7336c3c-6da1-11e5-8b2d-1ce8dbf5ad7b.jpg)

**Comment by vshcherb** [comment]
We will add street_lamp as an option to type , but we also plan to have just tag/value editing without any required fields.

**Comment by xmd5a2** [comment]
Added highway=street_lamp to POI
