### ISSUE TITLE
OsmAnd Cloud First start issues - Not possible to apply / Conflicts

### ISSUE THREAD

**Issue by pordini** [osmandapp/OsmAnd#17883]
# 🚀 feature request

### Description
The wizard on first start to restore from Osmand Cloud seems incomplete when you choose "what to sync". If you use this option you get the screen with three toggles to choose what to sync. However, you cannot "apply" or "save" this selection, there is no other button. If you then go back, you're just dropped into the standard sync screen. 

Additionally, I had 17 sync conflicts on a new install, having to indicate that I want to use the cloud version on every one of them.

### Describe the solution you'd like
Just a more complete out of box experience.
Also it might be good to have the cloud restore feature be a bit more prominent in the first screen, it's now hidden in the menu.
Additionally, I think there should be no conflicts with a completely new install, cloud should be primary and override any defaults that came with the install (but I might obviously be wrong on that).

### Describe alternatives you've considered
I've considered not changing anything and keeping it the way it is.

**Comment by vshcherb** [comment]
Conflicts on new install are normal cause you have already settings / profiles on a new device, so we don't how to distinguish yet if something was changed in settings or settings were changed because of a new version. In that case you should be able to restore and overwrite.

**Comment by vshcherb** [comment]
I think we should treat situation as special that no backup was done before and suggest to restore All from backup (regardless conflicts) or suggest to go to standard menu with conflicts / overwrites tetc.

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#648m, released: 2023-08-19

**Steps to reproduce:**
- Install OsmAnd from Google play
- tap tree dots in the top right corner on the *Welcome screen*
- chose *Restore from OsmAnd Cloud*
- enter email used for Cloud account and confirm email
- tap *Choose what to sync*

**Actual result:**
- see video 
- after tapping on *Choose what to sync* you are redirected to *Back up screen*. On that screen, you cannot choose items for synchronization, that should be available with PRO subscription. The switches are set as if you had an Osmand Cloud Basic. You cannot confirm your choice, only *Back arrow* is available. 
- when you tap *Back arrow*, you are redirected to _OsmAnd cloud last sync_ screen. There are 17 sync conflicts on a fresh  install.

<table style="width:100%">
  <tr>
    <th>video choose what to sync </th>
    <th> screen </th>
  </tr>
  <tr>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/116079541/608c9c64-df7f-4c62-8190-0f57be1ae2de"  width="200" height="auto"/></td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/0c83d89a-d439-4ea5-8e51-250be0fb7481"  width="200" height="auto"/></td>
  </tr>

**Comment by vshcherb** [comment]
**To do** 
There should be no conflicts in simple case scenario: 
- Installing application, downloading 1 suggested map, opening OsmAnd Cloud and login in.
So it means: no general settings, no profies, no map sources, no TTS, no other conflicts.

**Ideas to implement**:
- Treat empty files as non existing (it means ok to synchronize) - should solve Map sources, Itinerary
- Do not backup standard files which are always packaged in the app - English TTS
- Do not save default values in files, so if we say Map zoom 15 by default it should not be saved into files
- Split General settings (same for all Profiles) into 2 files. So everything that's not changed by user won't be synchornized. For example setting of last viewed location, last open tab and other (non-directly controllable by user) will be saved in file that's not backed up in OsmAnd Cloud.

**Comment by vshcherb** [comment]
- [ ] Audio files couldn't download..
- [ ] Still lots of track conflicts (don't know how to fix) - 300 local upload (after fresh installation)
- [ ] Global and General settigns should be consided as non conflicts if it's first sync (downloaded from cloud)
- [ ] Sort Local/Cloud by modified timestampl

**Comment by dmpr0** [comment]
# Review
- [ ] **Browse map** profile conflict after login. * Storage was cleared for OsmAnd.

**Comment by vshcherb** [comment]
**To do**
Properly test on fresh version.

First appeared conflict on "Browse map", once it was downloaded as cloud version conflict appeared on "Global Settings", later conflict on "Quick actions", later on "Moped..." something weird...

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/commit/9e778d5094b48f2fafbf3ae318c2d5023dfa062c
