### ISSUE TITLE
Cannot see and access all POI details in context menu when drop-down menus are open

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd#17894]
## Description

When some drop-down menus inside POI's details are open, it's impossible to see and access the items in the bottom of the list. Issue reproduces with menus in the middle of the details list.

### How to reproduce
1. Choose POI with long details section, that includes drop-down menus
For example go to -25.7485260, 28.1962770 and tap Cure Day Hospitals Medkin or Louis Pasteur Private Hospital.
2. Open POI's details swiping it up
3. Open drop-down menu **Health specialty**, **Operational status**, **Open** inside POI details (you can open them altogether or only some of them). 
4. Try to scroll down POI details to the bottom of the list.

### Actual result
Last items in details are not visible and it is not possible to access them. See video

https://github.com/osmandapp/OsmAnd/assets/116079541/91bc7777-f1d9-4175-8334-aa142963b62d

### Expected result

You can see and access all items in the POI's details section, even if one or more drop-down menus are open.

**Environment**
OsmAnd Version: OsmAnd~ 4.6.0#599m, released: 2023-08-10
Android/iOS version: 13
Device model:

**Comment by zipav** [comment]
OsmAnd Nightly 4.6.0#648m, released: 2023-08-19

The issue is reproduced in the latest version of OsmAnd Nightly.

https://github.com/osmandapp/OsmAnd/assets/123936521/2265dfe7-9a3e-4c0b-aa7e-45bc88708182
