### ISSUE TITLE
access=private not rendered (due to live updates?)

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#17892]
The following setting is enabled: Configure map / Details / Show access restrictions and toll
Nevertheless `access=private` on `highway=path` is not visualized in red for these ways:

* https://www.openstreetmap.org/way/23590521
* https://www.openstreetmap.org/way/953637299

Maybe there is a problem with rendering of access tags that have been added via OsmAnd live?

OsmAnd 4.5.10. Default map style.

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#626m, released: 2023-08-17
Steps to reproduce:
- go to 48.0672518, 7.2542649 
- Download France Grand Est map, enable live updates for this map, download live updates
- enable *show access restrictions and toll* option in *Hide* menu in Configure map settings
- see if this [way](https://www.openstreetmap.org/way/23590521) or this [way](https://www.openstreetmap.org/way/953637299) are rendered according to OsmAnd [map legend](https://osmand.net/docs/user/map-legend/osmand#access)

Actual result:
- restrictions from live updates are not rendered (see screenshot)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/704c2531-bd6d-412c-86a3-6d5b7afde436"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
Issue couldn't be reproduced any more
