### ISSUE TITLE
The street is not correctly assigned to another municipality 

### ISSUE THREAD

**Issue by zipav** [osmandapp/OsmAnd#17906]
## Description
Our user from France has left a complaint that the Rue Kléber at coordinates `48,88869, 2,41212` is marked as belonging to the Commune Noisy-le-Sec, but is actually in the Commune Pantin.
See commune Pantin [OSM](https://www.openstreetmap.org/relation/67685#map=16/48.8882/2.4149)
See Rue Kléber [OSM](https://www.openstreetmap.org/way/435012861)

### How to reproduce
- Search coordinates
- Download the Ile-de-France map
- Tap this point on the map
- Check the result

### Actual result
Point is marked as belonging to Noisy-le-Sec 

### Expected result
Point is marked as as belonging to Pantin

**Environment**
OsmAnd Version: OsmAnd Nightly 4.6.0#606m, released: 2023-08-11
Android version: 12
Device model: Nokia 5.3

<table style="width:100%">
 <td><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/634eb342-b48e-48c7-800b-e65b8872bb49"  width="300" height="auto"/> </td>
 </tr>
</table>

**Comment by DmitryAlexei** [comment]
Rue Kléber in Pantin is mixed with allée Kléber in Noisy-le-Sec [OSM](https://www.openstreetmap.org/way/26559106)

**Comment by vshcherb** [comment]
Data is aligned with Nominatim
![Screenshot 2023-08-18 at 13 35 36](https://github.com/osmandapp/OsmAnd/assets/1042025/3c0dddaa-18d6-49d3-845b-2a54a8d12279) - https://osmand.net/map#16/48.8964/2.4747 where am i

https://nominatim.openstreetmap.org/ui/reverse.html?lat=48.89733&lon=2.47275&zoom=18

**Comment by vshcherb** [comment]
This one is not correct

https://nominatim.openstreetmap.org/ui/reverse.html?lat=48.88681&lon=2.41142&zoom=18
![Screenshot 2023-08-18 at 13 38 28](https://github.com/osmandapp/OsmAnd/assets/1042025/4600039a-c172-4f16-af41-11853aeb21c9)

https://osmand.net/map#18/48.88681/2.41142

**Comment by vshcherb** [comment]
Looks like these streets are incorrectly merged

**Comment by zipav** [comment]
OsmAnd Nightly 4.7.0#1352m, released: 2024-01-11

Now looks like a fix in https://osmand.net/map/#18/48.88681/2.41142 and in the latest version of OsmAnd Nightly

![Screenshot 2023-08-18 at 13 38 28](https://github.com/osmandapp/OsmAnd/assets/123936521/a3077d23-90bb-4fb6-b419-fca794904fa5)


<table style="width:100%">
 <td><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/3e20466f-00fd-4cc1-a216-c5b4921414af"  width="300" height="auto"/> </td>
 </tr>
</table>
