### ISSUE TITLE
Trip Recording: initial form is shown multiple times if the Rec button is pressed more than once

### ISSUE THREAD

**Issue by Max1234-Ita** [osmandapp/OsmAnd#17910]
## Description
I just noticed that if I tap several times the Rec button on the map display, the Trip Recording initial form is displayed the same number of times.

Since I guess only one position log can be recorded at the same time, I think a check should be present to prevent initiation of multiple instances.

### How to reproduce
1. Launch OsmAnd

2. Make sure the Rec button is displayed in the right panel.

3. Quickly tap the Rec button several times (i.e., 3).

4. Notice the recording configuration form is displayed the same number of times.

5. Tap the 'x' (Cancel) button to close the tool.

6. Notice that the Recording form is closed but another instance is present below it.

### Actual result
Multiple instances of the Trip Recording configuration form are started at once.

### Expected result
User should be able to initiate only one instance of the recording tool at a time. 
A check should be present to verify if the recording configuration form is already visible: if so, it should not be displayed again before the user closes it.

**Environment**
OsmAnd Version: Osmand Plus v.4.5.10
Android/iOS version: Android 11
Device model: Samsung Galaxy A50 (SM-A505 FN)

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#611m, released: 2023-08-15
When quickly tapping on the rec button, it is possible sometimes to open two windows of *trip recording initial dialog* (not easy reproducible in everyday conditions).


https://github.com/osmandapp/OsmAnd/assets/116079541/56bcc9a6-8972-4017-81f5-084186ae6d07

**Comment by Max1234-Ita** [comment]
If the user has a non-flagship device, with limited copy resources, it's quite easy to reproduce 🙂
