### ISSUE TITLE
Next turn widget shows incorrect turn in left-hand driving region when navigating by GPX

### ISSUE THREAD

**Issue by wavard** [osmandapp/OsmAnd#17912]
## Description 	
Hi
OSMAND Customer Support recommended that I submit a bug report.

I am using the latest version of OSMAND+ and have a widget display problem. I am based in Australia where we drive on the left hand side of the road and drive in a clockwise direction around roundabouts.

I use the "Plan a route" command. I then save. It is saved as a Track. I then navigate using the saved Track. The navigation route is displayed correctly and the route through the roundabout is correct (ie clockwise).

The problem is that the widget in the top left of the screen shows the route going in a anticlockwise direction.

If I was to create a route using the navigate tool/widget the route through roundabouts is displayed correctly.

Is this problem that I am experiencing a bug or a operator error?

I have attached screen clips & zip file of route that display the problem.

The profile selected is Driving and the Driving Region is Automatic.

Regards

Walter

### How to reproduce
See above
### Actual result
See above & attachments
### Expected result
See above
**Environment**
OsmAnd Version: 4.5.10
Android/iOS version: 13
Attachment(s)
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/99114504/594c2a9b-d5de-4906-bddd-5653905a7661"  width="300" height="auto"/> </td>
  </tr>
</table>   
  <tr>

[Thu 10 Aug 2023_1.zip](https://github.com/osmandapp/OsmAnd/files/12329335/Thu.10.Aug.2023_1.zip)

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#611m, released: 2023-08-15
- downloaded latest Australia South Australia map
- driving region for driving profile is set to *automatic*
- In navigation mode from starting point 33.02687° S, 137.53484° E to end point 33.02526° S, 137.52759° E *[Next turn](https://osmand.net/docs/user/widgets/nav-widgets#next-turns)* widget shows correct data (screenshot 1)
- In GPX navigation mode using previously created gpx file [Tue 15 Aug 2023.gpx.txt](https://github.com/osmandapp/OsmAnd/files/12343360/Tue.15.Aug.2023.gpx.txt) *Next turn widget* shows incorrect turn direction (screenshots 2 and 3)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/1361bcd7-5fc7-444b-8ae0-7494f694e828"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/b1e0267f-536a-4eb3-81db-9f822950ebf8"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/45300a2d-aed9-404c-95e5-e3e5fea559b3"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by ivanPyrohivskyi** [comment]
С++ and iOS needed

**Comment by ivanPyrohivskyi** [comment]
For test on iOS need select Australia region in settings

**Comment by yuriiurshuliak** [comment]
To reproduce this issue, followed these steps:

- First downloaded the latest map for South Australia.
- Tested the "driving profile" option in both "Automatic" and "Australia" modes, and the results were consistent.
- In navigation mode, I set the starting point at 33.02687° S, 137.53484° E, and the endpoint at 33.02526° S, 137.52759° E. During this route, the Next turn widget displayed the correct data for Android and iOS.
- I also tried **GPX navigation** using a previously created gpx file named "[Tue 15 Aug 2023.gpx.txt](https://github.com/osmandapp/OsmAnd/files/12343360/Tue.15.Aug.2023.gpx.txt)" In this mode, the Next turn widget functioned **correctly on Android**. However, **on iOS, it incorrectly** indicated the next turn.

OsmAnd~ 4.6.0#799m, released: 2023-09-22
OsmAnd 4.5.1.11

<table style="width:100%">
  </tr>
  <tr>
    <th>Navigation mode Android</th>
    <th>Navigation mode iOS</th>
    <th>GPX navigation Android</th>
    <th>GPX navigation iOS</th>
  </tr>
  <tr>
  <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/4085a685-491d-435e-b376-17ccbe3bb0e7"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/759cf747-9da1-4f6d-8979-296c29d9d8d9"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/158c6576-fc86-456a-b4cd-5d03805a00e2"  width="300" height="auto"/> </th>
  <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/40e944af-6a7a-4b09-b2a5-dc8c89e7aa94"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
The issue can only be tested with 4.6 build not 4.5 Testflight

**Comment by yuriiurshuliak** [comment]
The bug has been resolved, and at present, the Next Turn widget is displaying accurate data for Android in both navigation mode and GPX navigation.

OsmAnd~ 4.6.0#888m, released: 2023-10-19

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/f348be31-0751-4099-8fc1-48e1a796946b"  width="200" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/158c6576-fc86-456a-b4cd-5d03805a00e2"  width="200" height="auto"/> </th>
  </tr>
</table>
