### ISSUE TITLE
ANT+ Widgets for Gamin Tempe not available

### ISSUE THREAD

**Issue by rnpr4541** [osmandapp/OsmAnd#17921]
## Description
There are no widget to display temperature from garmin tempe ant+ device

### How to reproduce
On the complements menu, choosing external sensores I'm able to connect the temperature sensor from garmin (Garmin Tempe) and I can see the temperature values refreshing , but on configure screen  there are no widget for this sensor. Only for cycle and heart rate.
### Actual result
Not able to use temperature sensor

### Expected result
I was expecting a widget to display temperature on screen

**Environment**
OsmAnd Version: 4.5.10
Android/iOS version: 11
Device model: Galaxy tab S5e

**Comment by DmitryAlexei** [comment]
Yes, there is no temperature sensor widget https://osmand.net/docs/user/widgets/info-widgets#-external-sensors-widgets

Could you please describe possible use cases of such widget? Who would be interested in such a feature?

**Comment by rnpr4541** [comment]
Hello Dmitry

I will describe my use case.
My car as no temperature sensor and i use osmand for offroad.
I will put the sensor outside the vehicle and i would like to see outside
temperature on a widget.
Osmand us receiving the info frok the sensor but it is not aable to use it.
You have opened the app for ant+ and bluetooth connection but if you cant
use the information then the connection is useless.

Regards,
Rui Rodrigues

DmitryAlexei ***@***.***> escreveu em ter., 15/08/2023 às
09:06 :

**Comment by dmpr0** [comment]
## ToDo
- [ ]  Add widget **Temperature** as part of External sensor plugin

**Comment by rnpr4541** [comment]
Waiting for the new widget.
Thanks

**Comment by DmitryAlexei** [comment]
Documentation
https://osmand.net/docs/user/widgets/info-widgets#-external-sensors-widgets
