### ISSUE TITLE
 Сadence indicator in the widget

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#17923]
## Description

| Widget indicator with Float|
|-------|
|![image](https://github.com/osmandapp/OsmAnd/assets/44466116/ea264774-28d3-49a3-9d79-bc909699ec78)|

### Actual result

70.378006

### Expected result

70

**Environment**
OsmAnd Version: 4.5
Android/iOS version: 13

**Comment by johnnychicago** [comment]
Osmand Version 4.5.10, Android 13. The sensor device is a Magene S3+, talking Bluetooth to the phone and ANT+ to my watch. 

Other bit I've been noticing is that the sensor seems to update regularly to 0 - maybe once a second I get a 0 value shown in Osmand, inbetween one or multiple updates of the big float value. Maybe some smoothening is supposed to happen to the data coming from the sensor.

Thanks

**Comment by vshcherb** [comment]
if 0 value means N/A data, we need to accept 0 with some delay

**Comment by vshcherb** [comment]
@sjsbikes try 4.6.1 beta build it's fixed

**Comment by vshcherb** [comment]
To do: 
Would love to get this fixed! (see attached video of speed widget as explained by @johnnychicago )

https://user-images.githubusercontent.com/145097691/268200436-0e851dbe-926d-4710-837f-c88c42fc90cc.mp4

              Osmand Version 4.5.10, Android 13. The sensor device is a Magene S3+, talking Bluetooth to the phone and ANT+ to my watch. 

Other bit I've been noticing is that the sensor seems to update regularly to 0 - maybe once a second I get a 0 value shown in Osmand, inbetween one or multiple updates of the big float value. Maybe some smoothening is supposed to happen to the data coming from the sensor.

Thanks

_Originally posted by @johnnychicago in https://github.com/osmandapp/OsmAnd/issues/17923#issuecomment-1678683769_

**Comment by DmitryAlexei** [comment]
@johnnychicago @sjsbikes could you check in the latest beta version if it works

**Comment by sjsbikes** [comment]
> @johnnychicago @sjsbikes could you check in the latest beta version if it works

Still blinking! [(using 4.6.2)](https://osmand.net/releases/net.osmand-4.6.2.apk)

Perhaps it possible to have it update only once every second, like almost every other app does?

As a work around I use [OpenTracks](https://f-droid.org/en/packages/de.dennisguse.opentracks/) to give me speed info and use it split screen with the map, although it would be great to have one app that does it all. @DmitryAlexei

**Comment by DmitryAlexei** [comment]
@johnnychicago @sjsbikes Does it work the way it should now?

**Comment by sjsbikes** [comment]
Seems to be fixed!

Sent with [Proton Mail](https://proton.me/) secure email.
