### ISSUE TITLE
Recording GPX Dialog / Recorded track - Heart Rate is not visible that it present

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#17937]
## Description
* Allow to select any available data type for graph on Trip recording screen
* Track to test – [2023-11-01_14-40_WedHR.gpx.zip](https://github.com/osmandapp/OsmAnd/files/13228045/2023-11-01_14-40_WedHR.gpx.zip)

# Currently recording track, context menu
- [x] Sensor data is missed. In Analyse on Map for  Current recording track

# Track recording dialog, [Figma](https://www.figma.com/file/Ws2AIfiFsi3i1pmFzjpLrk/Track-recoding?type=design&node-id=1433%3A7527&mode=dev&t=malBSqBJ6WGRPdQ3-1)
We need to change graph toggle to give the ability to select any available options for displaying on the graph.

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Track recording</th>
        <th>Y-Axis</th>
        <th>X-Axis</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/1bff75af-3805-4ace-8f23-c967d436e827"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/f3e41f1d-484f-4eb6-880b-711bd908ddcd"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/e888e05c-8083-4f0d-8fa8-50a1ec000441"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

### Graph selection
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/34edbc04-fa7b-49ef-8d85-88c3e802dff7"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Replace toggle with list item
- [x] Title –  `Graph`
- [x] Right side: show selected options for each axis of the graph.
- - [x] Use slash `/` to divide Axis: `Y-Axis Option 1, Y-Axis Option 2 / X-Axis option`, example: `Altitude, Speed / Distance`
- [x] Tap on item should open **Graph axis bottom sheet**

### Statistic 
Previously we showed different sets of statistics items depending on the selected graph option: Overview / Speed / Altitude. We will change it; now we will show a permanent set of statistical items.
- [x] **Distance**
- [x] **Time span**
- [x] **Uphill**
- [x] **Downhill**
- [x] **Average speed**

# Graph axis bottom sheet, [Figma](https://www.figma.com/file/Ws2AIfiFsi3i1pmFzjpLrk/Track-recoding?type=design&node-id=1448-34207&mode=dev) 
We need to add changes to the bottom sheet 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Y-Axis</th>
        <th>X-Axis</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/2363628b-9929-46a9-b3ad-efc5e158ce96"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/c52788f6-7cbe-493a-a067-a5b3dd52484c"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [x] Add toggle to switch between `Y-Axis | X-Axis`
- [x] Add Cancel and Apply buttons
- - [x] **Cancel** – undo changes 
- - [x] **Apply** – close bottom sheet, apply changes

### Y-Axis
- [x] Use checkboxes instead of radio buttons
- - [x] Allow to select two options for Y-Axis
- [x] Remove compound items: Altitude / Slope, Altitude / Speed, Slope / Speed we will use checkboxes
- [x] Show  divider between sensors option
- [x] Don't show options without data

**Change icons for:**
- [x] **Altitude**, icon `ic_action_altitude`
- [x] **Slope**, icon `ic_action_slope`
- [x] **Speed**, icon `ic_action_speed_outlined`

### X-Axis
- [x] Use radio buttons for available options, only one options can be selected

**Change icons for:**
- [x] **Distance**, icon `ic_action_distance`
- [x] **Time,** icon `ic_action_time_span`
- [x] **Time of day**, icon `ic_action_time_of_day`

**Comment by dmpr0** [comment]
## Review

- [ ] Save the selected graph axis. Reopening the dialogue box now resets the previously selected graph parameters.

**Comment by 0xRe1nk0** [comment]
Need sensor to fix missing sensor data for recording track
