### ISSUE TITLE
Track recorder icon appears twice in map

### ISSUE THREAD

**Issue by speleoluc** [osmandapp/OsmAnd#17931]
On a Samsung A54 (Android 13) running OSMAnd+ v. 4.5.10, the track recorder icon appears twice, but I couldn't find how to remove one.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/57163823/4adc0921-7745-495c-aec2-0b8bde622586"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by dmpr0** [comment]
Hello! 
You can delete duplicated widget in Menu – Configure screen – Right side

**Comment by sonora** [comment]
I wonder why we allow duplicates of identical widgets in the first place, isn't this a bug?

**Comment by dmpr0** [comment]
> I wonder why we allow duplicates of identical widgets in the first place, isn't this a bug?

No

**Comment by sonora** [comment]
So what's the use case to have 2 identical widgets on the same screen?

**Comment by DmitryAlexei** [comment]
@sonora they can show different data (see sunrise/sunset widgets https://osmand.net/docs/user/widgets/info-widgets#sunset-and-sunrise-widgets)

**Comment by sonora** [comment]
True for some, but many cannot show show different information, so a good U should limit those to one iinstance only...?

**Comment by DmitryAlexei** [comment]
Identical widgets can also be added to the different widget pages (some users need that)

**Comment by sonora** [comment]
Yes, but all that is not what this issue is about. When you re-read it, it is entirely avoidable by a small UI improvement?
