### ISSUE TITLE
Automatic select Source of Data (Widget / Trip Recording)

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#17936]
Once Device is connected in External Sensors
- [x] Trip Recording should automatically include recording of this data (if not configured yet)
- [x] If widget is added automatically select source of data that's present
---------------- 
- [ ] To Design: Suggest to add the widget

**Comment by dmpr0** [comment]
# Review

<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/22dd7796-9e2d-4282-9a60-00bc254df327
"  width="300" height="auto"/> </td>
  </tr>
</table>   
</details>  


- [ ] Unable to change **Source of data** for widget.

**Comment by vshcherb** [comment]
To design: we need to add element "Don't record data" - "None" (> None (automatically choose connected device)

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/18217
