### ISSUE TITLE
insufficient checking of one-way streets

### ISSUE THREAD

**Issue by imyxh** [osmandapp/OsmAnd#17932]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

car

### Start and end points

[41.57256,-72.64104] to [41.55678,-72.65677]

### Actual and expected routes

OSRM, Graphhopper, and Valhalla get it right: https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=41.57324%2C-72.63968%3B41.55590%2C-72.65599#map=15/41.5652/-72.6423

However, OsmAnd will attempt to route into Spring Street, *against one-way traffic!* This is very dangerous. See screenshot.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/12703838/af1bd7b4-fe9b-4035-95ae-64119ada5fe3"  width="300" height="auto"/> </td>
  </tr>
</table>

What is happening here is that there is an off-ramp onto Spring Street. Spring Street is interesting in that:

- traffic flow is bidirectional east of Rome Avenue [41.56628,-72.65504]
- traffic flow is eastbound only, west of Rome Avenue [41.56628,-72.65504]
- thus OsmAnd sees that it can *enter* Spring Street from the off-ramp from Main Street at [41.56633,-72.65415]
- but OsmAnd does *not* notice that once it's on Spring Street, it needs to immediately turn on Rome Avenue or else it will be going the wrong way.

### Is this a regression?

no

## 🌍 Your Environment

**OsmAnd Version:**

<pre>4.5.10<code>

</code></pre>

**Device and Android/iOS version:**

Android 11

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**

Not related, but thanks for all the hard work you put in to this app! Seriously, it's been a huge help for me.

**Comment by DmitryAlexei** [comment]
On the [OsmAnd map](https://test.osmand.net/map/?start=41.571943,-72.641540&end=41.556782,-72.656742&type=osmand&profile=car#18/41.57131/-72.64203) the route is the same as in [OSM](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=41.5732%2C-72.6397%3B41.5559%2C-72.6560#map=19/41.56625/-72.65467). The same using the nightly build OsmAnd~ 4.6.0#622m, released: 2023-08-16

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/e2498ba1-921e-4731-b1b4-da45429bd5a9"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/204da043-46ca-4b1a-aa67-4d3a8988474d"  width="300" height="auto"/> </td>
  </tr>
</table>

@imyxh try resetting to default your driving profile (menu > settings > your driving profile > swipe to the bottom of the list > reset to default. Also update the app to the latest version (i.e. beta from google play)

**Comment by imyxh** [comment]
Ah. Yeah, I see. Resetting the profiles didn't do anything, but updating the map did. I was using an old version of the map for Connecticut.

This still slightly worries me, as even on that old version OsmAnd should've seen that the street was one-way (it was), and should not have told me to go down it....
