### ISSUE TITLE
CAI/SAC difficulty classification with topo and offroad map styles

### ISSUE THREAD

**Issue by cridemichel** [osmandapp/OsmAnd#17946]
## Description
CAI/SAC difficulty classification settings do not work with topo and offroad map styles

### How to reproduce

1) set map style to "topo" or "offroad"
2) go to "configure map"
3) tap on "difficulty classification" and enable it

### Actual result

latter steps result in the following screenshot

<img src="https://github.com/osmandapp/OsmAnd/assets/15322138/fd525742-be5a-452d-bd95-6174e57d01b0"  width="300" height="auto"/> 

### Expected result

while one should expect the following one:

<img src="https://github.com/osmandapp/OsmAnd/assets/15322138/4db3cd4b-6816-4523-a7ea-f0040057e596"  width="300" height="auto"/> 

**Environment**
OsmAnd Version: OsmAnd+ PRO 4.5.10  
Android/iOS version: MIUI Global 14.0.9
Device model:  POCO F3

**Comment by sonora** [comment]
Relate:; https://github.com/osmandapp/OsmAnd/issues/17703

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#648m, released: 2023-08-19
46.27548° N, 12.12646° E
path on the left hand is marked highway=path and [sac_scale=mountain_hiking](https://www.openstreetmap.org/way/351831091)
path going from the middle of the map to the right is marked only with [highway=path](https://www.openstreetmap.org/way/629951879#map=18/46.25153/12.11048)

**Steps to reproduce:**
- Tested with and without *Difficulty classification enabled* (Configure map > difficulty classification)

1. OsmAnd default rendering (in difficulty classification chosen SAC scale)
<table style="width:100%">
  <tr>
    <th> difficulty classification off </th>
    <th>difficulty classification on</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/5c17a087-8008-4e4d-9171-164b2da20dcc"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/ecc1e14f-6bc8-4411-87dc-0d4a17e4a809"  width="300" height="auto"/> </td>
  </tr>
</table>

2. Topo rendering (SAC difficulty classification is set by default, you cannot choose SAI)
<table style="width:100%">
  <tr>
    <th> difficulty classification off </th>
    <th>difficulty classification on</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/16b2e54c-b89a-4279-b6ff-76132f067cd2"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/18eca390-13d1-4e4e-a291-21f2116eeb2c"  width="300" height="auto"/> </td>
  </tr>
</table>

2. Offroad rendering (SAC difficulty classification is set by default, you cannot choose SAI)
<table style="width:100%">
  <tr>
    <th> difficulty classification off </th>
    <th>difficulty classification on</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/3ae7b735-9b78-48dc-958b-9b45c0c4f45c"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/eec32ac9-de98-4790-98af-4bcec8098d88"  width="300" height="auto"/> </td>
  </tr>
</table>

**Actual result (see pictures above):**
- Topo and Offroad map styles lack SAI difficult classification setting in Configure map menu
- Topo map style incorrectly displays paths without SAC difficulty classification as if they tagged so

**Comment by xmd5a2** [comment]
Fixed. Now it should be like this
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/c16a6538-9973-46d9-9703-8566a25e3313)

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#813m, released: 2023-09-28
tested in initial conditions

> 46.27548° N, 12.12646° E path on the left hand is marked highway=path and sac_scale=mountain_hiking [OSM](https://www.openstreetmap.org/way/351831091) path going from the middle of the map to the right is marked only with highway=path [OSM](https://www.openstreetmap.org/way/629951879#map=18/46.25153/12.11048)

1. Offroad and topo map style. Now there is a possibility to choose between CAI and SAC difficulty classifications. **At the same time objects tagged only CAI are also displayed when SAC difficulty is chosen.** (Probably related with https://github.com/osmandapp/OsmAnd/issues/17703 ). 

<table style="width:100%">
  <tr>
    <th>  Offroad map style difficulty classification CAI </th>
    <th> Offroad map style difficulty classification SAC</th>
    <th> Topo map style difficulty classification CAI </th>
    <th> Topo map style difficulty classification SAC</th> 
 </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/8aaec1a7-00d9-447e-ae9d-633d123cbc83"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/e998048e-977f-4361-9e6f-05e066ae7a69"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/56bb2c14-5fc9-4aa2-8aea-59bbbea46dc3"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/0d8eb290-7923-4783-be09-0754b3e22f03"  width="300" height="auto"/> </td>
  </tr>
</table>

2. **In default map style, path going from the middle of the map to the right is rendered if it has CAI or SAC tag (it doesn't).**
According to our map legend (https://osmand.net/docs/user/map-legend/osmand#path-difficulty), path on the left tagged **mountain_hiking should be rendered with solid line** (not with dashed line). 

<table style="width:100%">
  <tr>
    <th>  Osmand map style difficulty classification CAI </th>
    <th> Osmand map style difficulty classification SAC</th>
 </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/4d7fc7c3-34a9-406e-a3f6-3e51f6317ccd"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/f94d18ac-2d24-425c-b03e-abb70a16e3ee"  width="300" height="auto"/> </td>
  </tr>
</table>

3. Also tested on iOS 4.5.2.2
- there is **no possibility to choose between CAI and SAC in topo and offroad map styles**.
- in default map style when CAI enabled and in topo map style with difficult classification on, **the path going from the middle of the map to the right is rendered if it has CAI or SAC tag (it doesn't)**.

<table style="width:100%">
  <tr>
    <th> Default map style difficulty classification CAI </th>
    <th> Default map style difficulty classification SAC</th>
    <th> Offroad map style difficulty classification on </th>
    <th> Topo map style difficulty classification on </th> 
 </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/b2ac2cc1-cf2c-4249-a588-44db326fa703"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/d304009b-240b-4826-9efe-d9ffe01f5b6a"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/14f3d8b2-c7d6-42f5-ad47-69ea80b6ce9b"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/e4a92180-f356-4ef7-9299-68d59e5a6037"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by xmd5a2** [comment]
cai/sac_scale tags are propagated from corresponding relations (https://www.openstreetmap.org/relation/8766376#map=15/46.2571/12.1115). There is no error.
