### ISSUE TITLE
Support access:conditional, oneway:conditional, maxspeed:practical:conditional restrictions

### ISSUE THREAD

**Issue by ghost** [osmandapp/Osmand#1794]
[This tag](https://wiki.openstreetmap.org/wiki/Key:access:conditional) is used to show when access changes according to time. 

i.e. 
[A major road that is closed during winter](https://www.openstreetmap.org/way/339393218)
[A park path that closes at night](https://www.openstreetmap.org/way/246086074)

**Comment by majkaz** [comment]
How difficult would it be to implement a fix doing "simple" processing as in case #3462 or #6654 ? 
What I mean is just to look for some cases like access/access:vehicle/access:motor_vehicle @ no (date from - date to). 
I understand that processing the conditional restrictions is a huge undertaking, but perhaps picking what to implement first might be a way how to get at least some part of this functionality and this seems to promise best results for the least amount of work.

**Comment by vshcherb** [comment]
Should be fixed now

**Comment by 532910** [comment]
Awesome, it means it should route considering bridges opening, that I mapped some time ago.

**Comment by vshcherb** [comment]
Yes, that feature released 6 months ago though the issue was not closed by that time
