### ISSUE TITLE
off route warning: inconsistent setting

### ISSUE THREAD

**Issue by cridemichel** [osmandapp/OsmAnd#17948]
## Description
I have the same issue raised by [duiveldoder](https://github.com/duiveldoder) (see #13298)
and for the sake of convenience I report it in the following:
__
When going to any navigation profile
Then "configure profile"
then "navigation settings"
then "voice prompts"
then scroll down to where it says "Announcement time"
expand the information panel below the slider

it all makes sense - early, normal, late you get early notifications "xxx" meters before passing
or normal notications "xx" meters before passing
or late "x" meters before passing

EXCEPT the "off route warnings"
under early I get these for my profile "walking" at 80-85 meters
under normal I get these 55-60m
under late I get these 25-30m

but the thing is - this is OFF ROUTE meaning you get these AFTER and not BEFORE you pass anything..

it means AFTER you get away from the track x, xx, xxx meters you get the warning.

So the values here should actually be increasing and not decreasing as you move the slider from left to right.
__

**Environment**
OsmAnd Version: OsmAnd+ PRO 4.5.10 
Android/iOS version: MIUI Global 14.0.9
Device model:  POCO F3

**Comment by sonora** [comment]
True, I think this is a good fix: https://github.com/osmandapp/OsmAnd/pull/17950

**Comment by cridemichel** [comment]
but does the proposed fix introduce a separate slider? If no, I think that it would break the other warnings, isn't it?

**Comment by sonora** [comment]
No, this quick fix would simply scale the off route lead distance with negative proportionality vs. all other lead distances, but still uses the same slider.

**Comment by cridemichel** [comment]
> No, this quick fix would simply scale the off route lead distance with negative proportionality vs. all other lead distances, but still uses the same slider.

in this case, my opinion is that the proposed fix is not appropriate, since, as I have already observed, it may be necessary to have the off route warning as soon as possible, while having the waypoint warning as late as possible (i.e. only where you are close to)

**Comment by cridemichel** [comment]
why did you close it? It was not completed at all...I do not understand this way of handing issues

**Comment by vshcherb** [comment]
The original issue is fixed that "as late as possible" will trigger "off route immediately". 

> I would suggest tò add a check box forenabling individual sliders for each possible warning.

That would be  a separate issue and way to complicated, we can revise the timing itself cause for the most of the users they will use default setting
