### ISSUE TITLE
Zwischenziel im importierten GPX Track setzen.

### ISSUE THREAD

**Issue by 9Biker** [osmandapp/OsmAnd#17959]
Folge einem importierten GPX Track und möchte auf dieser Route ein neues Zwischenziel setzen.
Finde keine Lösung ?

OsmAnd Version:4.5.10
Android/iOS version:13
Device model: Samsung

**Comment by DmitryAlexei** [comment]
You can add a waypoint to existing track:
- make your track visible on map
- tap on a place on the map where you want to add a waypoint
- in *Context menu* chose Actions > Add track waypoint > Select track to which you want to add a waypoint

**Comment by 9Biker** [comment]
@DmitryAlexei

Danke für die Info, aber einen Wegpunkt hinzufügen fuktioniert bei mir nur mit einem mit OsmAnd erstellten Track.
Die Frage war einen Wegpunkt einem importierten GPX Track hinzufügen und das fuktioniert bei mir nicht.

Gruß

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#645m, released: 2023-08-19
I tried to add waypoints to different imported tracks and it always worked. 
Please note, I speak only about waypoints (https://docs.osmand.net/docs/user/map/track-context-menu#points--waypoints) not about intermediate destinations (https://docs.osmand.net/docs/user/navigation/setup/route-navigation#intermediate-destinations), that cannot be used with GPX navigation.

Please follow the algorithm I mentioned above. If the problem persists, please make short video of your issue, and attach your track.

**Comment by 9Biker** [comment]
Meine Frage war: ein Zwischenziel setzen so daß die Route über das Zwischenziel verläuft.
"""Folge einem importierten GPX Track und möchte auf dieser Route ein neues Zwischenziel setzen."""
