### ISSUE TITLE
elevation graphic missing

### ISSUE THREAD

**Issue by MaxLanar** [osmandapp/Osmand#1795]
Hello,

IMO Osmand lack the ability to provide graph elevation (For a planned route or for a gpx file) . I use it a lot to prepare my (bikes/horses/feet) travels and  this would be a killer-feature to have !

(sorry for my english)

**Comment by shorty66** [comment]
This would need to be calculated using elevation data.
This data is not available in osmand at the moment - hillshades are just raster-images and elevation lines are pre calculated paths from actual elevation data like SRTM.

It should be possible to calculate hillshades and elevation lines from elevation data on the fly. That should reduce file size but increase processing time. It would allow for options like elevation-graphs for gpx files and elevation aware routing, though.

I would very much like that feature.

**Comment by gibbsnich** [comment]
Sorry for being off-topic (and kind of rude because this should probably be a pull request, but I don't have the time to polish my code atm..) but I just wanted to share that I implemented a simple elevation view some time ago for recorded gpx tracks. 
![screenshot_2015-10-16-22-53-41](https://cloud.githubusercontent.com/assets/584660/10553159/197c975a-7459-11e5-9306-e00c53fcc2ad.png)
You can see my changes at https://github.com/osmandapp/Osmand/compare/master...gibbsnich:master

**Comment by shorty66** [comment]
Okay, but i assume this uses GPS altitude - it's not possible to show this graph for a calculated route with the available data.

**Comment by littlehelper** [comment]
+1 for providing an elevation graph for (the remaining part of) a planned route or for a recorded track.

**Comment by andrew-davie** [comment]
I submitted a mod that uses a rainbow-coloured backing to tracks/routes that shows the relative elevation along the whole track.
That is, purple through blue green yellow orange red from lowest to highest. So you can always see along a track the relative elevation.
Not exactly what you ask for, but does the same job. See… https://www.youtube.com/watch?v=L1MXf20mqSw <https://www.youtube.com/watch?v=L1MXf20mqSw>

**Comment by sonora** [comment]
Ok, thanks!

I have taken the time to clean out some bugs, make it bulletproof for all kinds of OsmAnd and non-OsmAnd generated GPX files and adapt to the style sheet. May take some time later to also support showing ft, but that should be secondary.

**Comment by homersimpsons** [comment]
MAPS.ME shows elevation data when you calculate a Bike/foot trip. But it has a lot less functionality.

**Comment by utack** [comment]
Will this be included in the next version?
Also a question: Can it deal with BRouter gpx files? At least the web version of BRouter gives back gpx files with elevation profile, and it would be really neat to have an elevation plot in Osmand for the ones generated by the BRouter Android app

**Comment by sonora** [comment]
Yes, I had tested tracks created from brouter-web without issues, and yes, the feature should be in our 2.6 release (currently scheduled for the cause of February)

**Comment by utack** [comment]
That is nice
Is it a plugin or shown in the route overview, where the list of turns and streets are currently?
BRouter web always returns a gpx with elevation, I was worried the api used on the phone might not

**Comment by sonora** [comment]
When you save a brouter gpx from their web site  to the osmand track folder, it contains the elevation data for all points, and OsmAnd now shows it as a graph when viewing the track data, no plugin required.

**Comment by utack** [comment]
@sonora Do you happen to know if the BRouter offline app you use from Osmand also returns elevation data that can be plotted?  
That would be an awesome feature

**Comment by sonora** [comment]
Create atrack and inspect it using a text editor. See if it contains `<ele>` data.

**Comment by utack** [comment]
It does not  
Will determine if the interface of BRouter and open a separate bug to request it, in case it does
