### ISSUE TITLE
GPS position displayed inaccurate leads to wrong instructions

### ISSUE THREAD

**Issue by andrixnet** [osmandapp/OsmAnd#17956]
## Description
This past week I've been across country and used OsmAnd to guide me (navigate). 

### How to reproduce
My route passed through several mountain passes with successive tight turns. 

### Actual result
OsmAnd apparent position got stuck somewhere before a turn while I went through it, then it jumped from that position as I passed it onto the road ahead, practically skipping part of the road and the route marking remaind from then on as if I didn't follow the route and without recalculating. 

This is where it jumped and kept showing the route as if not driven.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/3382777/8d0e302c-7e21-4459-a8dc-16191bed4be2"  width="300" height="auto"/> </td>
  </tr>
</table>

This is a wider view when I first saw the problem and managed a screenshot overview. 
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/3382777/ad3b43a5-2c59-4e40-b657-2490679791c5"  width="300" height="auto"/> </td>
  </tr>
</table>

This happened multiple times in multiple mountain passes. Once I managed to pause the route, resume it, did something like changing the route starting position to my position (was a waypoint) and route got reset from my position, but later was unable to affect this since it was already my position and refused to recalculate. 

### Expected result
In parallel with OsmAnd I was running another app (Pathaway) that was recording my progress. GPS signal was correct, the shape of the road was consistently recorded correctly as can be seen in this screenshot of the same place and comparing the shape of the road.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/3382777/044a4752-7b91-44de-9247-f9c76a04ab68"  width="300" height="auto"/> </td>
  </tr>
</table>

I would have expected OsmAnd to follow the road and advance the route properly. 

Browsing later through settings I found nothing identifyable that may relate to this sticky behaviour to test different values.

**Environment**
OsmAnd Version: 4.5.10 2023-08-09
Android/iOS version: 9
Device model: SM-G965F

**Comment by mikehgentry** [comment]
Maybe #16081 

Try turning off 'animate own position'

**Comment by andrixnet** [comment]
> Can be related with #17506 Such behavior can occur due to loss of GPS signal

Loss of GPS signal is not a cause in this case, as demonstrated by the track recorded in parallel by another application on the same device. See initial description and third screenshot.

**Comment by andrixnet** [comment]
My problem looks similar on the screen to the video shown in #16081 though the behaviour is not that extreme. 
But in addition to that behaviour, my problem includes route remaining marked as not driven, though my position (following the route) has advanced. 

I still get turn instructions (top-left widget) correctly according to my current position and the route ahead.

**Comment by vshcherb** [comment]
It's only possible to fix such issues with GPX if they are reproduced, but to reproduce especially stuck locations, we need to have track recorded (in continuous mode) by OsmAnd and track that you tried to follow. You can share it here or with support team. 

Also you can  check option Navigate a track - https://docs.osmand.net/docs/user/navigation/setup/gpx-navigation#user-start--finish--points

**Comment by andrixnet** [comment]
Do you mean the route it calculated is used internally as a GPX? 

I was using calculated route via navigation dialogs (selecting destination and several intermediate points), not a pre-existing GPX set to follow. 

------------

Do I understand correctly that I should calculate a route, export it as GPX, then load it as track to follow and simultaneously record trip?

**Comment by DmitryAlexei** [comment]
To reproduce this issue we need:
1. recorded track
2. start, destination and intermediate points of your route. We can create this gpx file ourselves, or you can export that file using details section of navigation menu https://docs.osmand.net/docs/user/navigation/setup/route-details#share--export-actions.

**Comment by sonora** [comment]
From what I see, there may be a misunderstanding and this is **not** a GPX based navigation, but a 'regular' offline navigation.

Would be interesting to know if disabling the "Animate own position" setting eliminates the issue.

**Comment by andrixnet** [comment]
A few days ago, on a winding road and then through a roundabout, I took another screenshot. 
![Screenshot_20230825-120653_OsmAnd](https://github.com/osmandapp/OsmAnd/assets/3382777/80fa0962-2c04-4b4b-a2a7-e16e9a427648)

The position remained stuck there just as I started the left turn and remained there well after clearing the roundabout. 
One can see the track (in red) following the road. 

This was taken before reading the previous 2 comments, so: 
- starting position (set as my position) from Mangalia https://goo.gl/maps/9y8ri1MGoUxkYuxz8
- 1st intermediate https://goo.gl/maps/YpgAiRydLjP5CfiKA
- 2nd intermediate https://goo.gl/maps/ebKup2n56bJJ2kHx9
- 3rd intermediate https://goo.gl/maps/ZByTMzoGjpACiFD58
- destination https://goo.gl/maps/6ooYNYpq8sHgBzPj7

During this trip I had "use Kalman filter" disabled for driving profile. Didn't seem to make any difference. 
I have the recorded track, I just have to identify it in the phone storage, I'll add it later.

**Comment by andrixnet** [comment]
[2023-08-25_12-05_Fri.zip](https://github.com/osmandapp/OsmAnd/files/12455704/2023-08-25_12-05_Fri.zip)
This is the recorded track (by OsmAnd), only the relevant section in relation to this screenshot.

**Comment by DmitryAlexei** [comment]
Unfortunately didn't manage to reproduce this issue using provided coordinates and GPX track. In simulation everything works fine, no errors occurs.
At the same time I experienced some similar issues, when location source is set to Android API. The navigation icon has moved further than the route line. Both times occurs after crossing the intersection. 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/53cc4af2-1841-4a2f-a0df-a9a6d2539a41"  width="600" height="auto"/> </td>
  </tr>
</table>

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/356de519-db57-4f64-8754-627297496b66"  width="600" height="auto"/> </td>
  </tr>
</table>

**Comment by andrixnet** [comment]
Looks similar to what I experienced, minus the stuck position arrow.

**Comment by vshcherb** [comment]
To do: we need to properly reproduce it of course, the line could only be slightly ahead as it moves with GPS position without animation

**Comment by vshcherb** [comment]
Unfortunately we didn't reproduce but we fixed route line segment display. So we need to retest and check if it was fixed

**Comment by andrixnet** [comment]
I'll retest with OsmAnd (release, up-to-date) with every longer trip I will take and return if needed. Thank you.
