### ISSUE TITLE
off route warning: inconsistent setting (reissued since not completed at all)

### ISSUE THREAD

**Issue by cridemichel** [osmandapp/OsmAnd#17958]
## Description

I have the same issue raised by [duiveldoder](https://github.com/duiveldoder) (see https://github.com/osmandapp/OsmAnd/issues/13298)
and for the sake of convenience I report it in the following:
__
When going to any navigation profile
Then "configure profile"
then "navigation settings"
then "voice prompts"
then scroll down to where it says "Announcement time"
expand the information panel below the slider

it all makes sense - early, normal, late you get early notifications "xxx" meters before passing
or normal notications "xx" meters before passing
or late "x" meters before passing

EXCEPT the "off route warnings"
under early I get these for my profile "walking" at 80-85 meters
under normal I get these 55-60m
under late I get these 25-30m

but the thing is - this is OFF ROUTE meaning you get these AFTER and not BEFORE you pass anything..

it means AFTER you get away from the track x, xx, xxx meters you get the warning.

So the values here should actually be increasing and not decreasing as you move the slider from left to right.
__

Environment
OsmAnd Version: OsmAnd+ PRO 4.5.10
Android/iOS version: MIUI Global 14.0.9
Device model: POCO F3

**Comment by vshcherb** [comment]
Fixed with https://github.com/osmandapp/OsmAnd/pull/17950

**Comment by vshcherb** [comment]
It's a duplicate issue as I see

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/17948#issuecomment-1683662718

**Comment by cridemichel** [comment]
that's not a fair fix, as discussed in #17948
