### ISSUE TITLE
My Places > Tracks: Sorting order at My Places gets reset to last modified

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#17955]
#17475 still happens. The track sorting order at My Places gets reset to last modified after certain actions. Change the visibility of the currently recording track (no active recording required, maybe also works for other tracks):
https://github.com/osmandapp/OsmAnd/assets/1040784/9d692b20-fb7d-4792-bacf-9925f646fb9f

OsmAnd 4.5.10.

**Comment by yuriiurshuliak** [comment]
Attempted to replicate the issue using the provided video instructions. Initially, modified the sorting sequence to A-Z. Subsequently, included the Currently recorded track. To verify if the sorting alterations occurred automatically, accessed the Visible on map directory and deselected the visibility of Currently recorded track by selecting Apply. However, upon navigating to My places, the sorting sequence persisted as the initial selection (A-Z).

Kindly verify if this problem is duplicated in the most recent nightly version. Additionally, it would aid our further investigation if you could confirm the sequence displayed in the video and outlined above. It is possible that certain reproduction steps were inadvertently omitted on our end.

OsmAnd~ 4.6.0#649m, released: 2023-08-21


https://github.com/osmandapp/OsmAnd/assets/127092082/bea80b1c-bfd7-4bfa-a734-a31327aad249

**Comment by scaidermern** [comment]
@yuriiurshuliak Thanks. The steps in the video look correct. I can't reproduce this issue in the latest nightly.

However, I'm not sure if this means that the bug has been fixed or if some side-condition isn't fulfilled.

If you have the time, you could try to reproduce it with the current version (4.5.10). If _you_ can reproduce it with the old version then chances are high that it really has been fixed in the nightly version.

**Comment by scaidermern** [comment]
So the bug may still exist in the nightly 😟

**Comment by vshcherb** [comment]
Not reproduce unfortunately, let's see if we get more information over time.

**Comment by Rowin63** [comment]
Also here, sorting is frequently set back to "last modified" (my favorite sorting is A-Z). Couldn't find out yet what's the reason.

**Comment by Rowin63** [comment]
After the update to 4.6.0#826 (but probably also at previous updates) the sorting in "my places / tracks" was set back to "last edited".
Only this sorting, the folder list. 
All tracks sorting inside the folders were not affected and remained as set (A-Z).


![Screenshot_20231002_061300_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/95540936/82dacf2c-9cc2-4a53-8cd1-42c7d4484771)

**Comment by scaidermern** [comment]
Bug still exists in version 4.6.2. Some actions lead to the toplevel sorting order being reset to Last modified.

**Comment by Rowin63** [comment]
Happened again at the update (to 4.6.0#838m).

**Comment by sonora** [comment]
Also for me, this seems to have re-surfaced, in particular with the nightlies of last week or so.

**Comment by dmpr0** [comment]
> Is it correct that in the iOS version there is no sorting option at all? Would be nice to have it.
> 
> <img alt="" width="300" height="auto" src="https://private-user-images.githubusercontent.com/48593176/272297137-b6cdde68-b033-47f6-a87a-2765931925e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0OTM3NjMsIm5iZiI6MTcwMzQ5MzQ2MywicGF0aCI6Ii80ODU5MzE3Ni8yNzIyOTcxMzctYjZjZGRlNjgtYjAzMy00N2Y2LWE4N2EtMjc2NTkzMTkyNWU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDA4Mzc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzY2Y3MzM0ODI5NTRhMDJhNmY5YWQ5YmQwNzk5ZGNkZTMyNDRkZTQ5ZGUxYzE0MmRhNzUyMmEyYWMwNGZjMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0I0bxrH-z-sJc89vakdeuohcaKrp5Ep0Fv6Z9J1FNq4">

Yes, currently there is no sorting option on iOS. We have planned to update the UI for tracks on iOS in the next release.

**Comment by sonora** [comment]
Shall we re-open this issue here, or first wait for more fixes of #17805?

**Comment by sonora** [comment]
Not fixed, or a regression after some fixes to #17805.

**Comment by scaidermern** [comment]
This bug was never really fixed. Some actions lead to the sorting order being reset. I've never managed to reproduce it consistently, maybe it is a race or it requires some rare condition. Happens every now and then.

**Comment by sonora** [comment]
One root cause seems the annoying separation/dualism we still have between screens _My Places > Tracks_ and the sub-screen _Visible on map_. Here is one way I can reproduce 100%:

- Have _My Places > Tracks_ (i.e. the Tracks root folder) sorted A-Z.
- Also have the _rec_ folder sorted A-Z.
- Go to _My Places > Tracks_, tap on _Visible on map_, then go to the (view the) _rec_ folder there.
- I think no sorting action etc. is even required at this point to reproduce, just tap the device's back key. Next time you open _My Places > Tracks_, it sorting has been reverted to "Last modified" for me...

**Comment by scaidermern** [comment]
> One root cause seems the annoying separation/dualism we still have between screens _My Places > Tracks_ and the sub-screen _Visible on map_. Here is one way I can reproduce 100%:
> 
>     * Have _My Places > Tracks_ (i.e. the Tracks root folder) sorted A-Z.
> 
>     * Also have the _rec_ folder sorted A-Z.
> 
>     * Go to _My Places > Tracks_, tap on _Visible on map_, then go to the (view the) _rec_ folder there.
> 
>     * I think no sorting action etc. is even required at this point to reproduce, just tap the device's back key. Next time you open _My Places > Tracks_, it sorting has been reverted to "Last modified" for me...

I can reproduce this with OsmAnd 4.6.11 but only if I _do_ perform a sorting action. Setting the sorting order in _My Places > Tracks_ > _Visible on map_ >  _rec_ to A-Z _again_ (although it is already set to A-Z) and hitting back leads to the root folder being set to "Last modified".

**Comment by zipav** [comment]
OsmAnd Nightly 4.7.0#1402m, released: 2024-01-21

The sorting nominally remains A to Z, but the tracks are placed in Last Modified order.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/bce0b860-59c1-4225-9674-3b6546832f39"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/350e5bd5-7db8-4268-816e-8c118488a3a9"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by dmpr0** [comment]
@sonora Please provide log file. 
I can't reproduce the issue by following the steps from https://github.com/osmandapp/OsmAnd/issues/17955#issuecomment-1873970211

**Comment by sonora** [comment]
@dmpr0 Dmytro, please use @scaidermern 's comment here https://github.com/osmandapp/OsmAnd/issues/17955#issuecomment-1874075513:

I have just tried with v4.6.13 code, and with his addition "perform a sorting action", i.e. in my third bullet point "_My Places > Tracks > Visible on map_", go to the Rec folder _there_ and resort it to "Last modified".

Then  it is definitely reproducible for me: Next time you open _My Places > Tracks_ (without going to _Visible on map_), the root folder sorting there has also been modified from "A-Z" to "Last modified".

**Comment by vshcherb** [comment]
Its' reproducible only 1 time as default value is used. Once you set the value manually in each folder it doesn't change @sonora. So I tried many scenarios but it's only possible on fresh build and 1 time to reproduce

**Comment by scaidermern** [comment]
> Its' reproducible only 1 time as default value is used. Once you set the value manually in each folder it doesn't change @sonora. So I tried many scenarios but it's only possible on fresh build and 1 time to reproduce

No. I can still reproduce it exactly the way described above (when setting the sorting order in the last step).

OsmAnd 4.7.4.

Please reopen.

**Comment by vshcherb** [comment]
Reopening won't have any effect cause neither me nor @dmpr0 couldn't reproduce so it has no effect. I hope if @sonora could reproduce probably he could find underlying reasons.
I'm not excluding the option that we are doing totally different things.

**Comment by scaidermern** [comment]
> I'm not excluding the option that we are doing totally different things.

Let's just avoid that doubt, reproducing it is really easy:

https://github.com/osmandapp/OsmAnd/assets/1040784/58aaa249-16c7-45de-8430-95df89ff760c

At the beginning I'm just showing the current sorting settings. Reproducing the bug begins when entering "Visible on map" (at 00:08).

**Comment by vshcherb** [comment]
@sonora already started a new issue https://github.com/osmandapp/OsmAnd/issues/19333
