### ISSUE TITLE
[🚀 feature request] Add options to efficiently mass-delete selected downloaded maps.

### ISSUE THREAD

**Issue by dreirund** [osmandapp/OsmAnd#17952]
# 🚀 feature request

### Description

I request the possibility to efficiently delete many downloaded maps; individually or all of some type/ region.

### Describe the solution you'd like

I'd like two features:

* In the "Download maps" &rarr; "LOCAL" view, an option to enable checkmarks for the downloaded maps, which allow to check several maps, and then delete (with confirmation) all selected maps,
* in the "Download maps" &rarr; "LOCAL" view, an option to filter maps by search string and category (e.g. allow filtering for "Hillshading" (category), "Germany" (search string), or both), and then an option to select all shown maps, to allow mass deletion.

### Describe alternatives you've considered

Manually deleting maps one by one is not really an option, because one has to scroll & search, and after deleting the view starts at the top again, so the next scroll and search.

### Use case and reference

Use case where it comes up: See [&nearr;&hairsp;this discussion](https://github.com/osmandapp/OsmAnd/discussions/17941):

Recent OsmAnd update now uses single heightmap data for both hillshading and slope display.

But I still have many old, now obsolete, hillshading and slope files downloaded.

When I go to "Download maps" -> "LOCAL", I have to scroll down to find the downloaded hillshading and slope maps (scattered in between online maps). Then I can delete one. Then I start at the top of the screen, having to scroll down a lot again.

That is not a viable solution for many tens, maybe hundred, of such files.

**Comment by DmitryAlexei** [comment]
https://github.com/osmandapp/OsmAnd-Issues/issues/2163

**Comment by dreirund** [comment]
> https://github.com/osmandapp/OsmAnd-Issues/issues/2163

Error 404 Page not found.

**Comment by vshcherb** [comment]
You need to click Delete icon in top Corner and then you can use multiselect

**Comment by dreirund** [comment]
> You need to click Delete icon in top Corner and then you can use
> multiselect

OK, thanks.

This still leaves open the search & filter feature request, so I
request re-opening this issue or also commenting that this won't be
implemented.
