### ISSUE TITLE
Route Restores

### ISSUE THREAD

**Issue by Sonwon1** [osmandapp/OsmAnd#17963]
# 🚀 feature request
Enable saving any navigation route as a turn-by-turn list and then enable restoring that route by rebuilding the route from the turn-by-turn list. From looking at the list it would require adding the way points, beginning, middle and end. This would allow saving any route, OsmAnd, Broute or manual routes to reload without using the Attach to the roads to correct the turn information. The  Attach to the roads function is painfully slow.

**Comment by vshcherb** [comment]
I think could be safely merged to https://github.com/osmandapp/OsmAnd/issues/17964
