### ISSUE TITLE
Left panel shows when in navigation

### ISSUE THREAD

**Issue by Sonwon1** [osmandapp/OsmAnd#17960]
## Description
Left panel shows when in navigation

### How to reproduce
1. Setup left panel to show Sunset and GPS info widget
2. Tap onscreen Navigation button.

### Actual result
Left panel shows on map

### Expected result
Panels should not show while in menus

**Environment**
OsmAnd Version: 4.5.10
Android/iOS version: 13
Device model: Samsung Galaxy Tab Active 3

**Comment by dmpr0** [comment]
Could you please provide screenshot?

**Comment by Sonwon1** [comment]
![IMG_20230818_145113031_HDR](https://github.com/osmandapp/OsmAnd/assets/141348374/fc6af225-d662-48f0-9ae9-5ce0b1a18e3c)

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#648m, released: 2023-08-19

Steps to reproduce:
- select your driving profile > go to OsmAnd menu > Configure screen > left panel 
- (or go to settings > driving profile > configure screen > left panel)
- add informational widgets (https://docs.osmand.net/docs/user/widgets/info-widgets) to the left panel  
- go to landscape mode
- tap navigation button

Actual result:
- informational widgets are shown on left panel (and do not shown on left panel)
- widget is partially covered by navigation menu

![photo_2023-08-21_11-07-23](https://github.com/osmandapp/OsmAnd/assets/116079541/306e3e51-1dff-4690-ae65-a38237614fef)
![photo_2023-08-21_11-11-11](https://github.com/osmandapp/OsmAnd/assets/116079541/701492f5-ab5a-4a36-9b8e-39f71224c4c6)

**Comment by Sonwon1** [comment]
This is related to [Configure Screen #17807](https://github.com/osmandapp/OsmAnd/discussions/17807)

**Comment by DmitryAlexei** [comment]
@Sonwon1  So issues appear in landscape mode?

**Comment by Sonwon1** [comment]
Yes, I only use the tablet in landscape mode. Please see the picture I posted above.

**Comment by dmpr0** [comment]
## ToDo
- [ ]  Hide all widget panels when Navigation screen is open
