### ISSUE TITLE
Add complete England maps

### ISSUE THREAD

**Issue by gogo25171** [osmandapp/OsmAnd#17962]
## Description
Good morning,
Can you add the ability to download full maps of england.
Thank you in advance, truthfully yours.

**Environment**
OsmAnd Version: 4.5.10, released : 2023-08-09
Device model: note 8 samsung
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/31017668/ea3bfd77-1971-4083-bb68-9c3acaab83ca"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by sonora** [comment]
In your screenshot, tap on "England", then on "Standard map": I think that's the one you are asking for.

(The screenshot directly is for the entire "United Kingdom", and ismissing an overarching "Standard map" because its file size would exceed the limit, I suppose.

**Comment by Popke523** [comment]
> In your screenshot, tap on "England", then on "Standard map": I think that's the one you are asking for.
> 
> (The screenshot directly is for the entire "United Kingdom", and is missing an overarching "Standard map" because its file size would exceed the limit, I suppose.)

If it exceeds the limit, it shows the full map but is downloading region by region (e.g. Poland, Germany)

**Comment by sonora** [comment]
Ah, true ,I was not aware...

**Comment by vshcherb** [comment]
I think England is too big. Zip size in total is 1.7 GB so it exceeds the limit of the file of 2 GB as we have today
