### ISSUE TITLE
Online search broken

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#17965]
Online search doesn't seem to work at all currently. Searching for Paris or Madrid doesn't return any results. Did I miss doomsday?

OsmAnd 4.5.10.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/pull/17969/files

**Comment by sonora** [comment]
Doomsday should have been delayed ... :wink: https://github.com/osmandapp/OsmAnd/pull/17969

**Comment by scaidermern** [comment]
Great 🙂

**Comment by sonora** [comment]
@vshcherb Fix is not in the r4.5 branch. If we publish another r4.5.x minor, it may be worth backporting.

**Comment by vshcherb** [comment]
4.5 branch won't be published any more, next week 4.6 beta will start (it requires new target sdk anyway)
