### ISSUE TITLE
Compass mode "North is up (fixed)" doesn't work

### ISSUE THREAD

**Issue by osmandlover** [osmandapp/OsmAnd#17979]
## Description

I was excited to see in the 4.4.7 version: "Map orientation added new fixed mode" as this is a feature I have been hoping for for a really long time. Unfortunately, after testing this it isn't working for me and I signed up a github account to submit a bug report. I am new at this so I hope I am doing this rite. 

The new "North is up (fixed)" mode works exactly the same as the old "Manually rotated" mode for me. If I rotate the map with two fingers the map manually rotates, in both modes. I'm not sure if it is just my device. But at the moment there is no difference between the two modes that I can tell. 

I never want the map to rotate and I expect that most other people don't either. But if manual rotation is the default setting that would be OK, as long as "fixed" mode does truly fix the map so that rotation is not possible. This is highly important for safety as the map rotating unintentionally can easily get you lost and / or cause you to be distracted while operating a vehicle. 

### How to reproduce

1. In Settings > Compass mode, select "North is up (fixed). 
2. Go to the main map. 
3. With two fingers, make a rotation gesture.

### Actual result

Map manually rotates, just the same as if you are in "Manually rotated" mode.

### Expected result

Map does not rotate and north remains fixed to be the top of the screen when in "fixed" mode.

**Environment**
OsmAnd Version: 4.7.7
Android/iOS version: Android 12
Device model: Pixel 4

**Comment by scaidermern** [comment]
See #17086, #17561 and similar tickets.
And update your version. OsmAnd 4.5.x behaves a little bit less weird.

**Comment by osmandlover** [comment]
I get OsmAnd from F-Droid and 4.4.7 is the "suggested" build, I took that to mean that 4.5.x was unstable. Is that's not the case?
![image](https://github.com/osmandapp/OsmAnd/assets/142730423/9b14186a-3c47-482d-9a95-6d91a8aa17a1)

I will read out the tickets that you linked, thanks for the feedback!

**Comment by scaidermern** [comment]
> I get OsmAnd from F-Droid and 4.4.7 is the "suggested" build, I took that to mean that 4.5.x was unstable. Is that's not the case?

I've never understood F-Droid's version philosophy regarding OsmAnd. So I can't answer this question. Try 4.5.x and decide for yourself.

Note that the F-Droid OsmAnd builds arent official. It is up to the F-Droid OsmAnd maintainer to decide which version to build, and when, and how to tag it.

**Comment by osmandlover** [comment]
Ok thanks I assumed that the f-droid maintainer was also an osmand maintainer. anyways after seeing that long conversation without actually landing on the very very obvious fix - to make the "north up" mode mean "north up" - i have compiled osmand myself and I am going to figure out how to do exactly this.

**Comment by osmandlover** [comment]
Submitted PR #17981 which solves this issue for me.

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/17086
