### ISSUE TITLE
Live update 

### ISSUE THREAD

**Issue by bast69** [osmandapp/OsmAnd#17975]
## Description
Hi,
When i want to Update i get an error
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/6906908/d529968a-f54f-4618-9d1a-c0a00898ecb4"  width="300" height="auto"/> </td>
  </tr>
</table>

### How to reproduce
Connect with your osm account, and update maps for contributions and update 
### Actual result
404 error
### Expected result

**Environment**
OsmAnd Version: 4.5.10
Android/iOS version: 12
Device model: POCO X3 NFC

**Comment by DmitryAlexei** [comment]
@bast69 Have you successfully logged in to your OSM account?
Do you have enough changes (30 in the past two months) for live updates to work?

**Comment by bast69** [comment]
Hello @DmitryAlexei ,
All it's ok, you will close the issue.
