### ISSUE TITLE
[Bug] Падение приложения при загрузке карт

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/Osmand#1797]
1. Зашел в загрузки карт на вкладку "загрузки"
2. Выбрал Евразия-Россия -> Северо-Западный федеральный округ -> Ленинградская область -> Карты с затемненным рельефом
3. Началась загрузка карты, во время загрузки поворачиваю экран телефона и приложение падает

Кроме этого если загрузить карту, то почему-то карты с рельефом не отмечаются как загруженные - возле них не появляется даты загрузки зеленого цвета
Osmand~2.2.0#13523M

**Comment by GaidamakUA** [comment]
Application should crash no more in actual nightly. But there are still a lot of work to do.
