### ISSUE TITLE
Timmelsjoch Hochalpenstraße

### ISSUE THREAD

**Issue by Sonwon1** [osmandapp/OsmAnd#17988]
# 🐞 routing report
Routing is not possible on the [Timmelsjoch Hochalpenstraße](https://www.timmelsjoch.com/de/timmelsjoch-hochalpenstrasse/) during closed hours.

[Road route video](https://www.youtube.com/watch?v=XLlith0R7zY)

### Routing engine

- [X] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Motorcycle

### Start and end points

Start at Hochgurgl, 6456, Austria
Ends at Autonomous Province of Bolzano – South Tyrol, Italy (Alto Adige)

[Google Map of route](https://www.google.com/maps/dir/6456+Hochgurgl,+Austria/Alto+Adige,+Italy/@46.7071905,10.8749191,10z/data=!3m1!4b1!4m16!4m15!1m5!1m1!1s0x4782cca709c1c063:0x39e8c607df1d9099!2m2!1d11.051!2d46.90206!1m5!1m1!1s0x4782a738d28c4f11:0x307098715907eb0!2m2!1d11.3547335!2d46.4982901!2m1!1b1!3e0?entry=ttu)

### Actual and expected routes

Expected route as shown above by Google Maps.

### Is this a regression?

No

## 🌍 Your Environment

OsmAnd Version: 4.5.10

Android/iOS version: 13
Device model: Samsung Galaxy Tab Active 3

**Maps used (online or offline):**

- [X] Offline maps offered within the OsmAnd app for download. This is not a map issue.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**

Mapping of this route is only possible during the open hours for this road. This makes it not act as expected when trying to create a route while the road is closed. I would think that setting Consider Temporary Limitations to off would have allowed mapping this route at anytime of the day. Or perhaps we need another switch?

The only workaround I could find was mapping the route during road open hours.

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#654m, released: 2023-08-22
[One of initial parts of Timmelsjoch Hochalpenstraße on OSM](https://www.openstreetmap.org/way/268337599) 
This way is tagged: access:conditional=no @ (Nov-May; 20:00-07:00)

Route was configured on 22/08/2023 at 12:30 according to the following parameters

-Starting point 46.8999275, 11.0514309
-End point 46.4981125, 11.3547801
-motorcycle profile
[OsmAnd Map motorcycle profile](https://test.osmand.net/map/?start=46.899902,11.051418&end=46.498112,11.354780&type=osmand&profile=motorcycle#12/46.7867/11.1897) 
- default motorcycle profile in the OsmAnd app
[Tue 22 Aug 2023.gpx.txt](https://github.com/osmandapp/OsmAnd/files/12407427/Tue.22.Aug.2023.gpx.txt)
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/d5c49e1b-f3c9-4152-a5b8-474b1173728e"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
@Sonwon1
You may probably need to update maps, while https://www.openstreetmap.org/way/268337599#map=14/46.9061/11.1054 has been changed 2 months ago

**Comment by Sonwon1** [comment]
Routing works at 12:30 try routing this route during closed hours. The road is closed at 20:00 to 07:00 so try at 22:00 hours and see if you get the same results. Be aware of the time zones too.

Is it possible it is Android version sensitive? I would not thinks so.

The OsmAnd Map screen says, All files up to date. OsmAnd and all of the maps where loaded less than a month ago.

I can provide a screen shot of the routing where it routes around Timmelsjoch and GPX file later tonight after the road closes if it will help?

**Comment by Sonwon1** [comment]
Maybe setting the system time manually was not a valid test?

Which OsmAnd version are you using?

I will try again tonight and post my results.

> * system time was set to 2:00
> * tried to build a route between 46.8999275, 11.0514309 and 46.4981125, 11.3547801
> 
> Actual result when _Consider temporary limitations_ is **on**:
> 
> * few times I experienced crashes during route calculation. No crash log file or tombstone files were recorded. Screen recording was also interrupted and file not saved.
> * after several attempts route was build avoiding _Timmelsjoch Hochalpenstraße_ (screenshot 1)
> 
> Actual result when _Consider temporary limitations_ is **off**:
> 
> * _Timmelsjoch Hochalpenstraße_ is used for routing (screenshot 2)
> 
> Consider temporary limitations is on	Consider temporary limitations is off
> <img alt="" width="300" height="auto" src="https://user-images.githubusercontent.com/116079541/262625255-3fa50854-628c-442d-b743-b236620bd0d1.jpg">	<img alt="" width="300" height="auto" src="https://user-images.githubusercontent.com/116079541/262627477-52444016-9c39-4f5b-9580-1effac24ffc1.jpg">

**Comment by DmitryAlexei** [comment]
@Sonwon1 I use OsmAnd~ 4.6.0#654m, released: 2023-08-22 (this is nightly build)
Please note, that according to documentation (https://osmand.net/docs/user/navigation/routing/osmand-routing#consider-temporary-limitations), *Consider temporary limitation option*  allows taking into account temporary road restrictions when calculating routes. So this is expected behavior of the app, when this option is turned on.

**Comment by Sonwon1** [comment]
> Consider Temporary Limitations

I am sorry I was not clear. The routing fails for me if I have the _Consider temporary limitation option_ turned on or off. 

The nightly build is not available in the Google Play store so maybe something changed?

I will try again tonight after the road is closed and post the results here.

**Comment by Sonwon1** [comment]
Okay, I give up. I am now unable to duplicate the problem.
