### ISSUE TITLE
update article about 2.5D projection

### ISSUE THREAD

**Issue by beatnickgr** [osmandapp/OsmAnd#17985]
After updating to 4.5.8, the 2.5D view was automatically turned on without my consent.
I tried to turned it off but it's not in the menu https://osmand.net/blog/osmand-android-4-3-released#25d-projection
Please restore the option to turn off the unrequested, annoying, and resource hungry 2.5D.

**Comment by jp8** [comment]
It can be turned off by a gesture:  two finger swipe upwards

**Comment by beatnickgr** [comment]
Thanks!
=> Then the article must be updated.

**Comment by DmitryAlexei** [comment]
https://osmand.net/docs/user/personal/profiles#appearancу
delete info about 2.5D mode for Android

**Comment by DmitryAlexei** [comment]
https://osmand.net/docs/user/personal/profiles#appearancу
