### ISSUE TITLE
Dangerous routing due to `oneway=reversible` not being respected (one-way roads whose direction changes during certain hours)

### ISSUE THREAD

**Issue by reassure-unfasten608** [osmandapp/OsmAnd#17982]
# 🐞 routing report

I live in Seattle. Multiple times, OsmAnd directs me to the [I-5 express lanes](https://wsdot.wa.gov/travel/roads-bridges/express-lanes) when it is closed for that direction, putting me in peril.

That express way has the tag `oneway=reversible` in OpenStreetMap. Closed tickets https://github.com/osmandapp/OsmAnd/issues/6267 and https://github.com/osmandapp/OsmAnd/issues/6271 say that OsmAnd will avoid routes with this tag, but it is not the case. In fact, it confuses them with regular two-way roads. See reproduction for details.

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile
Driving

### Start and end points
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=47.6578%2C-122.3175%3B47.7028%2C-122.3253

### Actual result
The route being picked uses two segments of the reversible oneway routes that never opens in the routed direction simultaneously. It asks the user to do a U-turn onto incoming traffic.
![image](https://github.com/osmandapp/OsmAnd/assets/142747453/bc401b7e-5744-4c79-9acb-70f66eb15446)

### Expected result
Navigation should avoid the reversible oneway routes, since they do not have time information tagged in OpenStreetMap.

### Is this a regression?

It never worked for me.

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

None works:
4.4.7.440703
4.5.8.450803
</code></pre>

**Device and Android/iOS version:**
Android 13, Pixel 6 Pro

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.
- [ ] Online (tile / raster) maps 

**Anything else relevant?**

**Comment by yuriiurshuliak** [comment]
While checking this route, I observed that in both the mobile and web editions of OsmAnd, the route is constructed according to the user's instructions mentioned earlier. However, upon verification using OpenStreetMap, the route is accurately established. The tags for this road indicate "oneway: reversible", but the time intervals are not indicated on the reversible lanes.. It's advisable to avoid these roads altogether.

Link to the route in the Web version: https://test.osmand.net/map?start=47.657791,-122.317393&end=47.702782,-122.324913&type=osmand&profile=car#14/47.6942/-122.3337

Link to the route in the OpenStreetMap:
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=47.6578%2C-122.3175%3B47.7028%2C-122.3253#map=16/47.6589/-122.3176

Route coordinates: 
47.65779, -122.31739
47.70278, -122.32491

OsmAnd~ 4.6.0#658m, released: 2023-08-23

<table style="width:200%">
  </tr>
  <tr>
    <th>Phone version</th>
    <th>Web version</th>
    <th>OpenStreetMap</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/e0bd4bb8-1fe4-4351-837e-bdeeb298c48f"  width="600" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/5bafafa3-2bd4-433d-8e83-dd8cc9b36983"  width="600" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/fe510d21-331a-4d3d-9ced-70dc0fb1c605"  width="600" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
To do: make oneway=reversible non routable for cars.

**Comment by xmd5a2** [comment]
Fixed. Routing should avoid `oneway=reversible` tag
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/2a735940-1920-4a23-8659-f7441fbf4d72)

**Comment by yuriiurshuliak** [comment]
The bug has been fixed. At present, the navigation route is accurately established on both the mobile and web versions of the app, effectively bypassing the tag "oneway=reversible." 
An alternative navigation route is currently being selected for this road.

OsmAnd~ 4.6.0#764m, released: 2023-09-15

<table style="width:200%">
  </tr>
  <tr>
    <th>Phone version</th>
    <th>Web version</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/9475c430-74c6-4193-8844-98376de83345"  width="600" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/3947b0ef-8a03-4a4a-9a5a-69fff9eac07b"  width="1200" height="auto"/> </th>
  </tr>
</table>
