### ISSUE TITLE
Renderer preference for route=* relations over ways tagged ref=*

### ISSUE THREAD

**Issue by BalooUriza** [osmandapp/Osmand#1798]
Rather than blindly trusting ref=* every time, it would be nice if it would modally prefer the appropriate relations rather than the ref=* tag on the highway.  For example, if you're navigating by bicycle, bike routes get announced by name or ref.  When by car or truck, if there's a route relation, then the route=road relations get digested instead of any ref=* on the way.  If no relation exists (which would currently be an error by omission in existing tagging), then use ref=* on the way.

**Comment by naoliv** [comment]
It's more complex:
- what happens when there are more relations (routes) in the same segment?
- what happens when the highway's ref diverges from the route's ref?

While it is good to have a route relation for the highways, it's not mandatory (and thus it's not an error if it isn't available).

**Comment by BalooUriza** [comment]
On Mon, Oct 26, 2015 at 2:48 PM, Nelson A. de Oliveira <
notifications@github.com> wrote:

> It's more complex:
>
>    - what happens when there are more relations (routes) in the same
>    segment?
>
> Render each route applicable.  This is a frequent situation in most of the
US in general (and to a lesser extent, signed E and I roads in Eurasia).

>
>    - what happens when the highway's ref diverges from the route's ref?
>
> This generally only happens at major junctions, so I'd treat it as any
other time two routes currently intersect.

**Comment by BalooUriza** [comment]
On Thu, Oct 29, 2015 at 3:48 AM, Paul Johnson <baloo@ursamundi.org> wrote:

> On Mon, Oct 26, 2015 at 2:48 PM, Nelson A. de Oliveira <
> notifications@github.com> wrote:
>
>> It's more complex:
>>
>>    - what happens when there are more relations (routes) in the same
>>    segment?
>>
>> Render each route applicable.  This is a frequent situation in most of
> the US in general (and to a lesser extent, signed E and I roads in Eurasia).
>

Addendum:  This is cleaner than the way this is currently handled, which is
just dogpiling on the way's ref=*.  Keep in mind it's not unusual in North
America, and to a lesser extent, Europe, to have more than one route on the
same way in the ground truth (particularly with E and I routes), and it's
not unheard of to have 5+ routes on the same way in the US (I believe the
current record is for a segment nearish Indianapolis that has nine that are
mapped; it's conceivable someplace has more routes).

>
>>    - what happens when the highway's ref diverges from the route's ref?
>>
>> This generally only happens at major junctions, so I'd treat it as any
> other time two routes currently intersect.
>

Correction, if it's a system like Oregon where the highway and the route
have different refs, the route takes precedent as it's what's going to be
on shields, trailblazers and guide signs 99% of the time.

**Comment by sonora** [comment]
Unclear how to proceed, if at all. Closed for now.
