### ISSUE TITLE
Online stack is broken

### ISSUE THREAD

**Issue by Max1234-Ita** [osmandapp/OsmAnd#17992]
## Description
Performing an online search from OsmAnd (Search menu -> Categories -> Online search) does not return any result, whatever I search for and the search radius I set.

### How to reproduce
- Launch OsmAnd
- Open the Search menu
- Type anything in the text box, i.e. "Milano Piazzale Lima"

### Actual result
Search results should be displayed after a few seconds.

### Expected result
No result is shown, just the "Nothing found" message.

**Environment**
OsmAnd Version: OsmAnd Plus v.4.5.10; Observed also in v. 4.5.8

Android/iOS version: Android 11

Device model: Samsung Galaxy A50 (SM-A505 FN)

**Comment by mikehgentry** [comment]
This was recently reported as fixed

#17965 

Presumably just hasn't landed in the stable release yet

**Comment by Max1234-Ita** [comment]
OK, thank you so much.
Hope v. 4.6 will be released soon :-)

**Comment by vshcherb** [comment]
Beta should be released this week, 4.6 probably will be long way to go but probably 4.6.1 will be a small release with bug fixes
