### ISSUE TITLE
Problem in scrolling map with external keyboard

### ISSUE THREAD

**Issue by twasilew** [osmandapp/OsmAnd#17994]
### Discussed in https://github.com/osmandapp/OsmAnd/discussions/17993

<div type='discussions-op-text'>

<sup>Originally posted by **twasilew** August 22, 2023</sup>
I use external keyboard (arrows) to scroll map.

To reproduce the issue I followed the steps
1. Connected wireless keyboard
2. Change the orientation of the map to follow my position. 
3. Then use any arrow on keyboard. 

Resoult: Map scrols random directions.

But if i change map orientation to north on top it works ok.
It must be direction of strolling in relation to map orientation.

Any one has similar problem? 

I noticed that after update on around July. 
I use version 4.5.10
On version 4.0.4 it worked fine.
On version 4.5.8 arrows keys didn't worked at all.

</div>

**Comment by dmpr0** [comment]
<table style="width:100%">
  <tr>
    <th colspan=2>Map orientation</th>
  </tr>
  <tr>
    <th>North is Up</th>
    <th>Movement direction</th>
    <th>Compass direction</th>
  </tr>
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/c66d53ec-7729-48de-a6c6-0dc93aaa782f"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/a79a2613-fab6-458b-815c-51e5641e0002"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/86f2011b-a9ea-4cbe-9a82-da0f298c2368"  width="300" height="auto"/> </td>
  </tr>
</table>   

I can reproduce few issues, if Map orientation is
* **North is up:** taping move map left / right, moves map but in the same time every press it shifts down.
* **Movement direction:** taping move map left / right do big jumps
* **Compass direction:** taping move map left / right works in wrong order

> Tested on 4.5.10 release version

**Comment by nazar-kutz** [comment]
@twasilew, Could you please check which device you have selected in preference "External input device":
Settings -> Profile settings ("Browse map", for example) -> General settings -> External input devices.

It can be one of four options:
* None
* Keyboard
* WunderLINQ
* Parrot

This is necessary for a better understanding of the cause of the problem.

Over the past few years, the code involved in moving the map has changed several times. I will try to understand the causes of the bug and fix it.

**Comment by twasilew** [comment]
> @twasilew, Could you please check which device you have selected in preference "External input device": Settings -> Profile settings ("Browse map", for example) -> General settings -> External input devices.
> 
> It can be one of four options:
> 
> * None
> * Keyboard
> * WunderLINQ
> * Parrot
> 
> This is necessary for a better understanding of the cause of the problem.
> 
> Over the past few years, the code involved in moving the map has changed several times. I will try to understand the causes of the bug and fix it.


Hi @nazar-kutz, I had "Keyboard" selected all the time.

**Comment by dmpr0** [comment]
# Review
<table style="width:100%">
  <tr>
    <th>Navigation</th>
    <th>Map viewing</th>
  </tr>
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/efd10455-dbaa-4777-9fcb-2a1889e80eed"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/792923a6-0489-401c-be26-0eda8f40578a"  width="300" height="auto"/> </td>
  </tr>
</table>   






* Slight shift on every tap is still present without navigation

**Comment by twasilew** [comment]
Is there any date on when this bug will be fixed and released? 
Until release it's impossible to use this app :(.

**Comment by DmitryAlexei** [comment]
The fix should already be available in the public beta and nightly builds
https://osmand.net/docs/versions/nightly_versions

**Comment by vshcherb** [comment]
Fix is in beta release you can try it
