### ISSUE TITLE
Text rendering in image-based engine

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1799]
For example we have a point:
```
office=telecommunication
shop=mobile_phone
name=Mobile phone+telecommunication
```
rendering_types.xml :
```xml
		<type tag="shop" value="mobile_phone" minzoom="16" />
		<type tag="office" value="telecommunication" minzoom="15" />
```
Style should render only mobile phone. It does not support office=telecommunication. In this case OsmAnd renders mobile_phone icon but not text.
inspector output:
```
Point types [office-telecommunication (1230), shop-mobile_phone (1110)] Names [name(1) - Mobile phone+telecommunication] id -18857
```
If I change "order" in rendering_types and shop=mobile_phone becomes first in inspector output line (Point types [shop-mobile_phone (1110), office-telecommunication (1230)].) then text renders correctly.

**Comment by vshcherb** [comment]
Discussed, works exactly as designed, if there are other suggestions, please feel free to comment.
