### ISSUE TITLE
Revert tilt gesture

### ISSUE THREAD

**Issue by Velomeloman** [osmandapp/OsmAnd#17998]
The map tilt gesture is now counter-intuitive. In most of map programs, the tilt is carried out by swiping up. This gesture is more logical, as the plane of the map follows the movement of the fingers.

**Comment by Nine-Tailed** [comment]
It's funny that before version 4.4 the map tilt gesture was like in google maps, but then its direction was changed

**Comment by zipav** [comment]
I tested 2D/3D mode on OsmAnd, Maps.Me, GMaps, StreetComplete, Waze.
- Maps.Me does not have map tilt/3D mode
- In Google Maps, the gesture of tilting the map is straight, to tilt in 3D mode you need to put two fingers horizontally, parallel to each other and smoothly swipe upwards;
- In Waze, gesture switching is not included in the functionality, it can only be switched in the application settings;
- In StreetComplete as well as in Google Maps the gesture of tilting the map is straight, to tilt in 3D mode you need to put two fingers horizontally, parallel to each other and smoothly swipe upwards;
- In OsmAnd, to tilt the map in 3D mode, you need to put two fingers horizontally, parallel to each other and gently swipe down, i.e. the gesture is reverted.
