### ISSUE TITLE
OsmAnd~ crashes when trying to navigate any non-trivial route

### ISSUE THREAD

**Issue by rah2501** [osmandapp/OsmAnd#17999]
## Description

When trying to start navigation between one place and another where the route is non-trivial, the application crashes.  This problem appeared recently (within the last few months) but I can't say when or what changed before it appeared.

I have followed some of the instructions in #17901 which seems similar.  Unfortunately there is no exception.log in OsmAnd's data folder, Android/data/net.osmand.plus/files.  There is no option to "Send crash log" in the Help menu.

I have switched the map renderer from v2 to v1 but get the same crash. 

Here is an export of my profile settings: [Browse map.osf.gz](https://github.com/osmandapp/OsmAnd/files/12412954/Browse.map.osf.gz)

### How to reproduce

Navigate from one place to another place where the route is non-trivial, for example a street in one city to a street in another city.

### Actual result

The progress bar goes very close the far right of the screen, the application is still responsive and then after about a minute, the application disappears.  When I start it again, I get asked "Continue following previous unfinished navigation?"  If I select "yes", the same thing happens.

### Expected result

Finds a route and begins navigation.

**Environment**
OsmAnd Version: OsmAnd~ 4.5.8 from F-Droid
Android/iOS version: LineageOS 20230613-NIGHTLY-enchilada
Device model: Oneplus 6

**Comment by DmitryAlexei** [comment]
Probably related https://github.com/osmandapp/OsmAnd/issues/17988#issuecomment-1689636218

**Comment by DmitryAlexei** [comment]
@rah2501 to reproduce this issue we need:
- start and end points of the route
- your navigation profile settings. You can export your profile settings using:  Menu > Settings > Your navigation profile > swipe to the bottom > export profile

**Comment by rah2501** [comment]
> Probably related [#17988 (comment)](https://github.com/osmandapp/OsmAnd/issues/17988#issuecomment-1689636218)

I'd had the same thought and tried disabling "Consider temporary limitations" but it made no difference.

**Comment by rah2501** [comment]
> * your navigation profile settings.

That should be included in the issue description?

**Comment by rah2501** [comment]
> * start and end points of the route

An example route:  53.41963 N 2.95533 W -> 53.49068 N 2.25995 W

**Comment by DmitryAlexei** [comment]
@rah2501 please note, that *Browse map* profile is not supposed to be used for navigation. It doesn't have navigation settings (https://osmand.net/docs/user/personal/profiles#navigation-settings)
Thus, your profile cannot be used to build a route.

Please, provide your driving (or bicycle?) profile


- I managed to create a route from 53.41963 N 2.95533 W to 53.49068 N 2.25995 W using default driving and bicycle profiles with no crash on OsmAnd~ 4.6.0#663m, released: 2023-08-24 and OsmAnd 4.5.10, released: 2023-08-09
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/b280d7d8-c0dd-4120-938a-5940a0ce32cb"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/890139f8-88b6-47dc-90e8-6a55e55852c6"  width="300" height="auto"/> </td>
  </tr>
</table>

- Only walking profile produces crash with this route after about 5-6 minutes of route calculation. No exception.log provided, video recording interrupted and file is not saved. Increasing memory allocated for routing (https://osmand.net/docs/user/plugins/development#memory-settings) up to 2048 Mb does not help, app crashes

**Comment by vshcherb** [comment]
I think this route is routable fine for bicycle
https://test.osmand.net/map/?start=53.419630,-2.955330&end=53.490680,-2.259950&type=osmand&profile=bicycle#10/53.4239/-2.2694
![Screenshot 2023-09-04 at 16 18 25](https://github.com/osmandapp/OsmAnd/assets/1042025/d0ebe314-659a-4615-96b4-c14ddfcd7b34)

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/troubleshooting/navigation#calculation-of-50-km-routes-for-pedestrians
https://osmand.net/docs/user/plugins/development#memory-settings

**Comment by EugeneZmeuk** [comment]
**12-04-2024**
- write about new routing engine.

**Comment by vshcherb** [comment]
Needs to be updated as it's relevant now only for A* routing
