### ISSUE TITLE
Improve "Configure screen" UX

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#18003]
Users visit the "Configure screen" dialog to show or hide widgets.  A logical setup for that screen would be to primarily (i.e. first) show them the list of all iwidgets available, structured by topic, and also indicating the ones already configured as visible.

Then upon tapping / adding  a widget, we can _in a second step_ offer the places where that widget can appear and its configuration options.

Today we do it the other way round: In the dialog we _first_ confront the users with the generic screen locations ("left stack", "right stack", etc.) which is of little interest at this time.

**Comment by dmpr0** [comment]
> Users visit the "Configure screen" dialog to show or hide widgets. A logical setup for that screen would be to primarily (i.e. first) show them the list of all iwidgets available, structured by topic, and also indicating the ones already configured as visible.

Why it would be a "logical setup"?

**Comment by sonora** [comment]
Regarding "Logical setup", here's my thinking:

 - Use case 1: User knows from release notes thatt there are now e.g. sensor widgets, so wants to add one. The first you want to see is which ones there are. It seems pointless to first have to select a screen position?

 - Use case 2: User knows there is e.g. a "Street name" widget. But we offer it as a selection only under "Top panel" or "Buttom panel". We currently force users to first select a panel, so users not realizing that limitation, or simply selecting the first panel listed, will not find it...

 - Use case 3: You want to hide a widget. You can do that by simply removing a checkmark in the "Visible" section of the widget list. Why force usres to select a panel first?

I call it "logical" because I think in all these cases the widget selection catalog takes priority (for the  sake of discoverability and usability) over the panel selection?

**Comment by vshcherb** [comment]
I don't think it's a big problem and now it's better to stick to the current version for a while
