### ISSUE TITLE
Recent OSMAnd~ builds crash

### ISSUE THREAD

**Issue by albansuser** [osmandapp/OsmAnd#18009]
Builds after OsmAnd~ 4.6.0#648m, released: 2023-08-19 initially crash upon displaying track or panning loaded track. Thereafter OSMAnd crashes repeatedly upon starting.

Clearing cache does not help. Nor does complete reinstall to latest version.  Reverting to #648 solves the problem.

This has happened on Samsung Galaxies running Android v13 and v9.

**Comment by DmitryAlexei** [comment]
@albansuser 

- Can you make a short video of your issue or send your track(s) to our support e-mail? (support@osmand.net, please indicate, that this is follow up of this issue)
- Additionally your system settings might be helpful (settings > swipe to the bottom > export > settings)
- How many tracks and favorites do you have displayed on map?

**Comment by albansuser** [comment]
Update on original symptoms. With compilation v4.6 #663 the crash occurs differently. 

The crash can now be caused as follows:
1. With a single track displayed, open menu for changing the track's appearance (artist's pallet icon).
2. Click on either the "speed", "altitude" or "slope" colour change options.
3. OSMAnd spontaneously crashes.

With compilation #663, OSMAnd can be restarted and steps 1, 2 and 3 can be repeated.

**Comment by DmitryAlexei** [comment]
[exception.log](https://github.com/osmandapp/OsmAnd/files/12431088/exception.log)

Steps to reproduce:
1. Open *Track context menu* of the track, visible on the map 
2. Tap on *Appearance* tab
3. Try to change track appearance according to its speed or height 

https://github.com/osmandapp/OsmAnd/assets/116079541/dbad88cc-0966-45fe-af65-a69a2526b20e

**Comment by albansuser** [comment]
Appears to be fixed in OsmAnd~ 4.6.0#667m, released: 2023-08-25.

Thanks

**Comment by Sonwon1** [comment]
Add me to the crash list. When I try to switch profiles from global to a navigation profile OsmAnd is crashing, version 4.5.10. When will 4.6 be released?

**Comment by DmitryAlexei** [comment]
@Sonwon1 can you, please, provide your navigation profile?

**Comment by Sonwon1** [comment]
What is the best way to provide that information? Isn't it in the crash reports I emailed?

**Comment by Sonwon1** [comment]
> @Sonwon1 can you, please, provide your navigation profile?

What is the best way to provide that information? Isn't it in the crash reports I emailed?

**Comment by Sonwon1** [comment]
> @Sonwon1 can you, please, provide your navigation profile?

[Removing Map Marker Widget from Driving Profile Causes OsmAnd to Crash #18021](https://github.com/osmandapp/OsmAnd/issues/18021)

**Comment by vshcherb** [comment]
Yes lots of crashes with tracks were in nightly but not reproducible any more
