### ISSUE TITLE
Osmand HTTP server

### ISSUE THREAD

**Issue by kelson42** [osmandapp/Osmand#1800]
This would be really good to be able to provide offline mapping in local network environments and avoid solutions based on pre-rendered tiles.

**Comment by thinrope** [comment]
That is a bit too vague, but isn't a http proxy (on any tileserver) enough? It can even be transparent.

**Comment by sonora** [comment]
No action planned.

**Comment by nicopace** [comment]
Just to note, this would also be relevant to be able to use cached OSM vector maps in other apps that use raster maps, for example ATAK.
