### ISSUE TITLE
Unable to Build OsmAnd-core: SWIG const mismatch in SingleSkImage?

### ISSUE THREAD

**Issue by yourealwaysbe** [osmandapp/OsmAnd#18012]
When building OsmAnd-core with `gradle build` from `OsmAnd-core/wrappers/android` i get an error in the generated SWIG code. I think this was introduced in [this commit](https://github.com/osmandapp/OsmAnd-core/commit/3cc698bfef8a72f8a0667b9b9957b593356afe6a) but still persists in the current head.

My build environment is Debian Bullseye, clang 11.0.1, gcc 10.2.1, swig 4.0.2 (but i've also tried 3.0.12 as the build instruction specify 3.0.*). Let me know if there are any other packages that might be relevant.

The error is:

    /mnt/volume/OsmAnd-submodules/baked/armeabi-v7a-android-clang-debug.make/core/wrappers/java/gen/cpp/swig.cpp:76859:45: error: no matching constructor for initialization of 'OsmAnd::SingleSkImage'
      *(OsmAnd::SingleSkImage **)&jresult = new OsmAnd::SingleSkImage((const OsmAnd::SingleSkImage &)result); 

of the list of constructors for SingleSkImage, the closest i find is

    /mnt/volume/OsmAnd-submodules/build/../core/include/OsmAndCore/SingleSkImage.h:32:16: note: candidate constructor not viable: 1st argument ('const OsmAnd::SingleSkImage') would lose const qualifier
            inline SingleSkImage(SingleSkImage& that)

which would need `that` to be declared `const`. However, the implementation in `core/include/OsmAndCore` doesn't look like it can provide the const guarantee because of the release.

        inline SingleSkImage(SingleSkImage& that)
        {
            if (that.sp.get())
                this->sp.reset(that.sp.release());
        }

An example of the SWIG code that fails is (from the generated `swig.cpp`)

    result = OsmAnd::SwigUtilities::createSkImageARGB888With(arg1,arg2,(char const *)arg3,SWIG_STD_MOVE(arg4));
    *(OsmAnd::SingleSkImage **)&jresult = new OsmAnd::SingleSkImage(result); 

which looks like it comes from `OsmAnd-core/swig/SwigUtilities.h`

        inline static SingleSkImage createSkImageARGB888With(...)
        {
            ...
            bitmap.setImmutable(); // Don't copy when we create an image.
            return SingleSkImage(bitmap.asImage());
        }

**Comment by yourealwaysbe** [comment]
Looks like [using SWIG 4.1.1](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13591/diffs?commit_id=6f042231136c8857ae25a77e69a88d1f789881c6#23ea5fa3f85bccbc97929c0896d5e515ecb9591b_5539_5674) should work. I guess just the build instructions on the site need updating.

**Comment by vshcherb** [comment]
Please feel free to create pull request to https://github.com/osmandapp/web/blob/main/main/docs/technical/build-osmand/how-to-compile-the-android-version.md
