### ISSUE TITLE
2 Belgian files don't download

### ISSUE THREAD

**Issue by a-pirard** [osmandapp/Osmand#1801]
On 1.9#8094D, my "Manage image files -> updates" shows 2 messages and does this:
Roads only Belgium 2014/02/15 -> 2015/05/25 : a file downloads but the same message remains
Contour lines Belgium 2013/09/25 -> 2015/06/30 : says "File not found".
Other files have updated alright.
Hoping this will help.

**Comment by vshcherb** [comment]
1.9 is not supported currently, may be you can download files by direct link and update them
