### ISSUE TITLE
Redesign "Download Maps" to be more intuitive

### ISSUE THREAD

**Issue by Redsandro** [osmandapp/OsmAnd#18013]
# 🚀 feature request

### Description

Once upon a time, there was a _"Download maps"_ menu. Over time, more and more things got hooked into this menu, and now it is confusing. Can we redesign this to be intuitive?

First, if you want to **remove** a map from the map overview where your downloaded maps are marked green, the first intuition is to touch or long-touch the green map you want to remove. 

![image](https://github.com/osmandapp/OsmAnd/assets/1702193/d742b230-1502-4bff-b0df-af5ff0653db4)

This does not work. You have to _figure out the name of the region_, and look for it in a long list of regions.

Second, if you want to **remove** a map, you first need to go to "**download** maps", even though you don't want to download a map. You locate the map you want to **remove**, but you first need to **update** it before you can remove it. 

![image](https://github.com/osmandapp/OsmAnd/assets/1702193/324196eb-7a1e-462b-9c25-49b9f4bf3ff8)

Turns out you can directly remove them from the "local" tab though. I didn't figure that out until I searched the internet, and I see multiple people asking the same question.

![image](https://github.com/osmandapp/OsmAnd/assets/1702193/0bf1f13b-c61a-417d-ad96-d82482722ffa)

In the "local" tab, touching an item shows a popup menu where you can remove the map. But opening the item kebab menu (`⋮`) on that same item shows the same popup menu on the other side. 

![image](https://github.com/osmandapp/OsmAnd/assets/1702193/58389b29-63fe-47ab-8efe-076fdaf6f4fa)

That's duplicate functionality, so this local tab and the download tab could be merged. Touch the item to update (as in download menu), touch the kebab menu to show options like "deactivate/delete" (as in local menu).

Then you need to do it again for every map. Intuition tells me to long-touch for multi-select, but that does not work.

### Describe the solution you'd like

**No. 1:** Being able to remove maps straight from the green download map overview would be a huge time saver, because you don't have to figure out the name of every map and then look them up in a list. Currently touching the map functions as if you want to do something with this position on the map, but at this zoom level no one really means to indicate that exact coordinate. Bonus for multi-select maps and remove/update them from here.

**No. 2:** The menu item should simply be called _"Maps"_ - not _"Download maps"_. First, you need to go there for things unrelated to downloading as well, and second, the download part is not about just maps, but downloads for voices, guides, fonts etc. as well. Alternatively it could be called _"Maps and downloads"_ to make more intuitive sense.

**No. 3:** Merge "local" map list functionality with "download" map list so the kebab menu shows there too.

**No. 4:** Long-touch for multi-select and apply update/delete/etc to all.

### Describe alternatives you've considered

I considered commenting on #9717 to agree with @dreirund who [commented](https://github.com/osmandapp/OsmAnd/issues/9717#issuecomment-683458715) the following:

> I would still like to offer also the delete functionality in the 'All Downloads' menu for downloaded maps which have updates

And replying my menu suggestion to @sonora who [commented](https://github.com/osmandapp/OsmAnd/issues/9717#issuecomment-683430850) the following:

> I am very open for any better wording which could make this clearer.

But I figured that issue is closed, quite old, and more limited in scope.

**Comment by sonora** [comment]
Essentially this suggestion is similar to what I propose (https://github.com/osmandapp/OsmAnd/issues/17538 and  https://github.com/osmandapp/OsmAnd/issues/17717#issuecomment-1686648083) for the My Places Tracks management screen:
- Place all items on one screen
- Mark the downloaded / visible in some fashion,  e.g. using color
- Assimilate the handling of the screen to that of a File Manager, i.e. provide a default action by tapping a single item, and provide multi-selection via long-tapping an item,  upon which a context menu (or bottom buttons) becomes available showing all possible actions. (Which will depend on whether just one or several and which items are selected).

It's quite some work, but doing this rigorously would create a harmonized and intuitive UX.

**Comment by dmpr0** [comment]
No. 1: It can't be done by long tap because long tap has own actions on the map screen, but we can add Remove action for region or country context menu.
No. 2: **Maps** will be more intuitive? **Maps and Resources** would be, we use it historically on iOS.
No. 3: I don't understand the issues at all. Downloads shows what you can download, Local tab shows what you have already downloaded and stored on the device. We are working on redesigning Local to show all OsmAnd files located on the device.

**Comment by Redsandro** [comment]
> No. 1: It can't be done by long tap [but] we can add Remove action for region or country context menu.

@dmpr0 that would be very helpful! (For people like myself who don't know the names of most regions and have limited phone memory.)

> No. 2: **Maps** will be more intuitive?

Let me put it this way: If you are searching for a specific map action that is _not_ __downloading__ a map, it doesn't make sense to expect it in a menu called _"download maps."_ You are right, **Maps and Resources** would be better!

> No. 3: I don't understand the issues at all. Downloads shows what you can download, Local tab shows what you have already downloaded and stored on the device. 

The issue is the inconsistency. I get that the issue might not be immediately clear from a technical standpoint. However, empirical evidence shows a noticeable level of confusion among users.

Items in the "Downloads" list (that are outdated) have 1 anonymous action: Download. You don't know that you will activate a download until you activated it. This option should be in a popup menu so you can think: "hmm no that's not what I want."

Items in the "Local" list have 2 options, and they are both the same. Take one away (because it is redundant) and add it to the "Downloads" list because it is lacking. Ideally the kebab menu (those 3 vertical dots) should be on both.

---

@sonora it's similar in one aspect, namely that different behavior in similar lists is confusing. But I see those multi-select checkboxes in your example. It'd be nice to have them on the local maps list as well!

**Comment by vshcherb** [comment]
"Downloads" was always referring to 'Files that are already downloaded or being downloaded", "Download maps" is important for new users however it provides "Download / Manage / Update maps" as it has 3 tabs and it's much better to have in 1 place to manage maps but that name is too long

**Comment by diggernet** [comment]
Definitely improvement needed for deleting maps.  Right now I have a couple GB of outdated maps in a large region that I want to delete.  I have only found two options available:
- Update the maps, downloading GB of data, so that I can access the "Delete" menu and discard that data.
- Locate all the many individual files in the "Local" tab and delete them one by one.
Neither is a good experience.

**Comment by goldfndr** [comment]
@diggernet are you unable to access the "Select" option in the overflow menu ( ⋮ )? One can select several Local maps then Delete them.

Probably should change Delete (selections) to Remove (individual) or vice versa for consistency.

**Comment by diggernet** [comment]
@goldfndr Your description doesn't match what I see:
- In "All Downloads" tab, individual items that are up to date have an overflow menu containing "Remove" and "Download".  Items that are outdated just have a download button instead of overflow.
- In "Local" tab, there is an overflow menu at top right containing "Deactivate" and "Activate".  Individual items have an overflow menu with "Deactivate", "Rename", and "Delete", plus "Update" if they are not current.

However, now that I went hunting for menus, I noticed that the "Local" tab has a trash can icon that it turns out enables multi-select.  Not sure what I was expecting it meant (delete all, maybe?), but it's just what I needed.  Thanks.

**Comment by goldfndr** [comment]
Ah, #17952, if your OsmAnd is before [the 4.6 redesign](https://osmand.net/blog/osmand-android-4-6-released/#local-menu-redesign).

**Comment by diggernet** [comment]
Thanks @goldfndr, obviously my ability to find existing tickets before submitting could stand some improvement.

But to avoid me hijacking this ticket by your resolution of my specific complaint, I want to mention that I was commenting in support of the request for usability improvements in this area.  As I do not have 4.6 yet (hello FDroid) I cannot speak about the improvements that have been made and whether they have resolved @Redsandro 's original request.

**Comment by vshcherb** [comment]
The issue becomes pretty vague as we have Local maps redesigned in 4.6, so probably it's not relevant anymore.

**Comment by goldfndr** [comment]
@vshcherb There's still a wording difference as of 4.7.0#1485m:

* Delete (selected, overflow menu at top)
* Remove (individual, overflow menu at right)

But I'm not sure what is preferred, if it is an issue.

**Comment by vshcherb** [comment]
Yes thanks for point out
