### ISSUE TITLE
SPLITVL between public transport route numbers in POI

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1802]
Just grep synthetic_test_rendering inspector's -vmapobjects -vpoi output with "SPLITVL"
```
transportation : public_transport_platform Остановка 3 Lat 45.732784 Lon 36.66921 id=-9640 route_bus_ref=3SPLITVL666route_trolleybus_ref=16c
```
This objects (OSM data) is included in 3 relations:
route=bus with ref=3
route=bus with ref=66
route=trolleybus with ref=666

Expected output should be:
```
route_bus_ref=3,666 route_trolleybus_ref=16c
```

**Comment by vshcherb** [comment]
Fixed
