### ISSUE TITLE
Suggests 2 Fitness Centre spelling  when creating POI

### ISSUE THREAD

**Issue by musshorn** [osmandapp/OsmAnd#18027]
## Description
Seemingly exclusively for Fitness Centre when you go to add it, both the British and American spelling of 'Centre' appear as items. This can probably be reduced to just the British as that would be more consistent with other items. 

### How to reproduce
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/874740/4678759a-56f3-4587-b439-e7adc8744b50"  width="300" height="auto"/> </td>
  </tr>
</table>

### Actual result
See screenshot

### Expected result
Only one of Centre / Center is spelt listed 

**Environment**
OsmAnd Version:  OsmAnd+ 4.5.10, released: 2023-08-09
Android/iOS version: Android 12
Device model: OnePlus 7

**Comment by zipav** [comment]
OsmAnd Nightly 4.6.0#729m, released: 2023-09-05

When attempting to create POI, several options are displayed for the name "Fitness Centre"

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/900360ff-b71a-4bf3-ae1c-384beae184c8"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
[fitness_centre](https://taginfo.openstreetmap.org/tags/leisure=fitness_centre) - is correct OSM name 
But we have american translation by default in res/phrases.xml
```
<string name="poi_fitness_centre">Fitness center</string>
```
