### ISSUE TITLE
Paragliding (Free flying) icon available for profiles

### ISSUE THREAD

**Issue by elgandoz** [osmandapp/OsmAnd#18041]
# 🚀 feature request

### Description
Add the already existing "Free flying (sport)" icon to ones allowed to be selected in profiles.

### Describe the solution you'd like
Some people use OsmAnd for paragliding and other free flying sports, mainly for planning, but it can be also used for analysys and track recording.
Since there are very specific settings for such profile, it would be very nice to also have a dedicated icon.
This should be very easy to implement since the icon is already available within OsmAnd for the POI "Free flying (sport)"

| Available profile icons | Free flying Icon |
|--------|--------|
| ![Screenshot_20230829-132405](https://github.com/osmandapp/OsmAnd/assets/5859926/c0a1378c-5c56-43c9-b4f1-79609f80f5e9) | ![Screenshot_20230829-132426](https://github.com/osmandapp/OsmAnd/assets/5859926/891ca4a5-77d1-49e1-aa5d-4467c5384dcc) | 

### Describe alternatives you've considered
I'm currently using a little airplane icon, but it's not the same 😊.

-----
This is part of a set of feat. requests aimed to make OsmAnd more user friendly for paragliding, generic free-flying and other flying activities: #18035

**Comment by dmpr0** [comment]
Done https://github.com/osmandapp/OsmAnd/commit/b0f1aa23f0b0fd48b1770b2ad00e9f68e9584de8
![Screenshot 2023-09-13 at 14 33 19](https://github.com/osmandapp/OsmAnd/assets/9365308/77571c89-f309-40da-8a71-189476cb02d9)

**Comment by zipav** [comment]
OsmAnd Version: OsmAnd TestFlight 4.5.1.10/OsmAnd Nightly 4.6.0#759m, released: 2023-09-14
Android/iOS version: Android 12/iOS 16.0
Device model: Nokia 5.3/iPhone 12

<table style="width:100%"> 
  <tr>
    <td valign=top><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/d98b75d1-0e88-4e4b-9e8a-d0a613648389"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/b865efeb-cb9b-406d-9649-0b704786e78b"  width="300" height="auto"/> </td>
