### ISSUE TITLE
Multivalued POIs

### ISSUE THREAD

**Issue by mic140** [osmandapp/OsmAnd#18042]
If the object key has several values ​​separated by ";", then all these values ​​are not displayed in the properties of such an object, and the "nearest POI" is shown only for one of the values ​​in the list.  At the same time, the search for all key values ​​​​works properly.  Object example: https://www.openstreetmap.org/node/7020911412

**Environment**
OsmAnd Version: OsmAnd~ 4.6.0#676m
Android version: 13
Device model: Redmi Note 10 Pro

**Comment by mic140** [comment]
![IMG_20230829_163826](https://github.com/osmandapp/OsmAnd/assets/69987154/553690e5-12fc-477d-bc14-c481bf01765c)
![IMG_20230829_163853](https://github.com/osmandapp/OsmAnd/assets/69987154/e1f36856-96fe-4de8-99c1-b751eb0cd0fb)

**Comment by scaidermern** [comment]
The main problem here is that on one hand `shop=beauty;cosmetics;perfumery;hairdresser_supply` isn't considered good tagging - some would even say that this is wrong. On the other hand, OSM doesn't offer an accepted tagging scheme for these kind of multi-purpose shops.

This controversy is explained at https://wiki.openstreetmap.org/wiki/Semi-colon_value_separator.

**Comment by vshcherb** [comment]
We support these kind of issue cuisine, but we don't support for sport, I think this issue should be linked to "sport" https://github.com/osmandapp/OsmAnd/issues/8483
