### ISSUE TITLE
Add baby carriage/stroller/buggy icon to possible profile icons

### ISSUE THREAD

**Issue by mahlzahn** [osmandapp/OsmAnd#18046]
# 🚀 feature request

### Description

I added a profile based on pedestrian with the routing option “no steps”, but there was no suitable icon to choose (I currently use the UFO!). I‘d like to have an icon there.

### Describe the solution you'd like

Add the already existing icon for baby store, but in the other direction as all profile icons go from left to right:

[![svg](https://raw.githubusercontent.com/osmandapp/OsmAnd-resources/master/icons/svg/shopping/baby.svg)](https://github.com/osmandapp/OsmAnd-resources/blob/master/icons/svg/shopping/baby.svg)

### Describe alternatives you've considered

A further step could be also a dedicated profile, could potentially use #9415 as base profile, but this goes here beyond this feature request.

**Comment by dmpr0** [comment]
Done https://github.com/osmandapp/OsmAnd/commit/093f771749661ada0e1f8b168626782a210ff7f6
