### ISSUE TITLE
Weather overlay does not show

### ISSUE THREAD

**Issue by Sonwon1** [osmandapp/OsmAnd#18044]
This was recently closed I am opening this issue with additional information.

## Description

Weather overlay does not show. Weather contour lines do show.

## Additional information

This maybe related to permissions on the storage folder. The contour lines did not show while the Data Storage Folder was assigned to External Storage 2. After Migration to the Internal App Memory the contour lines began to show. I believe there was a change between Android 10 and 13 with how external storage is handled that may have effected OsmAnd. OsmAnd Weather works correctly on a phone running Android 10 External Storage 1. Regardless Weather overlays are not showing.

This is likely related to [No weather layer anymore #16868](https://github.com/osmandapp/OsmAnd/issues/16868). The user with issue 16868 also had a Samsung Galaxy Active Tab 3. This appears to be a pattern.

### How to reproduce

Assuming you have weather setup.

1. main menu
2. Weather
3. Tap overlay button, make sure Precipitation check box is checked
4. Tap contour line button, select Precipitation.

### Actual result

Precipitation lines show overlay does not show.

### Expected result

Expect Precipitation overlay to show.

**Environment**
OsmAnd Version: 4.5.10
Android/iOS version: 13
Device model: Samsung Galaxy Active Tab 3

**Comment by Sonwon1** [comment]
### Additional Information

I am not clear on how familiar the developers are with Samsung Knox security software?

Samsung devices have Samsung Knox software running on them. Samsung Knox is security software written by Samsung for enterprises. Maybe Knox is somehow not playing well with the Weather plugin or vice versus and preventing it from writing to the SD card?

This is a possible idea as to why Weather would work on other devices and not on a Samsung Galaxy Active Tab 3. I would root this device and remove Knox if I could however I need an unrooted device for other software I need to run. Knox tends to cause more problems than it is worth on a non enterprise device in my opinion.

**Comment by Sonwon1** [comment]
###More Additional Information

While reading the news and such I saw this comment.

"[I think this is due to an anti-consumer "feature" of newer versions of Android. Two apps can't use the same folder anymore, only folders they create and "own" can be used.](https://www.reddit.com/r/OsmAnd/comments/160vedw/trouble_moving_data_storage_on_android_with_osman/)"

**Comment by DmitryAlexei** [comment]
OsmAnd 4.5.10, released: 2023-08-09 fresh app installation from Google Play

**Steps to reproduce:**
- log in to Cloud account with Pro subscription 
- Change storage folder in menu > settings > OsmAnd settings > Data storage folder to External storage 2 (you need android device with SD card)
- give permission to access photos, videos, music and audio on your device
- restart OsmAnd
- to to the Weather tab, enable weather layer (layers) and contour lines 

**Actual result:**
- Weather widgets show info, weather contour lines are displayed, **weather layers are not shown**


https://github.com/osmandapp/OsmAnd/assets/116079541/9261fedd-f78c-4943-8a0a-a03bcabbfa8e


Workaround:
- transfer data back to the External storage 1 and then back to the External storage 2 (restart OsmAnd every time)
- sometimes weather layers are displayed after downloading a weather map (weather forcast) for one of the countries

**Comment by Sonwon1** [comment]
FYI, the posted work around above does not work on a Samsung Galaxy Active Tab 3.

**Comment by Sonwon1** [comment]
Just posting the weather overlay is working in version 4.6.x.
