### ISSUE TITLE
3D tracklog

### ISSUE THREAD

**Issue by elgandoz** [osmandapp/OsmAnd#18040]
# 🚀 feature request

### Description

OsmAnd could display a GPX track in 3D, instead of being flattened" on the ground

### Describe the solution you'd like

Any GPS fix is a point in a three-dimensional space. In some contexts, for example in any flight-related activity (like paragliding, hanggliding, general aviation, drone tracklogs, etc...), a 3-dimensional track is what a user would like to display, instead of a track projected to the surface.

Given that OsmAnd can currently display the map in 3D, it would be great to being able to display a track that uses the original GPS elevation data.
For usability and backward compatibility, every track should be "flattened" by default: in the display option of each track there should be a switch for using the elevation data (aka 3D tracklog).
Optionally, there could be a global flag to have the default behaviour for every track in 3D, and allow to be flattened in each track display option.
As a further option, the 3D track should display the  projected line on the ground in a less visible color, like a grey shade, in order to have a visual reference on the ground.

When the a specific point is visualised along the track (for example while moving the cursor on the graph for the "Analyse on the map" function), the dot represented on the 3D track should have a projection connecting it to the ground.

The track should maintain all the display and colouring options as the regular track.

All in all, the visual representation could be similar to this, with specific reference to the "point projection":
<img width="770" alt="Screenshot 2023-08-29 at 13 13 20" src="https://github.com/osmandapp/OsmAnd/assets/5859926/9f40d091-0edf-4e20-bdc7-79986a52ab2e">

|OsmAnd|SportsTrackLive|
|:-:|:-:|
| ![Screenshot_20230829-125738](https://github.com/osmandapp/OsmAnd/assets/5859926/9fd59929-f370-4c9d-bf7d-29b90a359895) | <img width="1728" alt="Screenshot 2023-08-29 at 13 04 29" src="https://github.com/osmandapp/OsmAnd/assets/5859926/0edf6fe7-fd00-45e1-ad93-583fd9dbb0ab"> |

Generic example of a track display by another cloud service (ignore non-described feats.): https://www.sportstracklive.com/en/track/map/elgando/1/angrogna-torre-pellice-piedmont/735524/?mode=3D

### Describe alternatives you've considered
Currently, there are no real alternatives, aside from using other services (like [SportsTrackLive](https://www.sportstracklive.com/)) or apps (like [Google Earth](https://play.google.com/store/apps/details?id=com.google.earth&hl=en&gl=US))

-----
This is part of a set of feat. requests aimed to make OsmAnd more user friendly for paragliding, generic free-flying and other flying activities: #18035

**Comment by vshcherb** [comment]
As a test implementation we can display all GPX that have difference with 3D relief (when 3D enabled) ```> 50m``` as 3D tracks

**Comment by vshcherb** [comment]
We need to prepare UI as backend is ready  today.
