### ISSUE TITLE
Add widget "Available RAM"

### ISSUE THREAD

**Issue by Chumva** [osmandapp/OsmAnd#18058]
### Description

It will be useful to have a widget that shows available memory info, similar to the one at the bottom of the development settings

### Describe the solution you'd like
- [x] Add new widget **Available RAM**
- [x] Icon `widget_developer_ram_day/night`
- [x] Show device available RAM: `6 / 12 GB`
- [x] Visible only if **OsmAnd Development** plugin is On.

Add a development widget that will show available, used, and total app memory

### Describe alternatives you've considered

We can use memory info from development settings or the Android Studio profiler, but it is not always comfortable/possible to use them to determine if there is something heavy is working in the app

**Comment by dmpr0** [comment]
Result

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/2816e7b1-8d04-4b7e-953b-c5126caa0f34"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by nazar-kutz** [comment]
**Fix widget appearance after review**: https://github.com/osmandapp/OsmAnd/pull/18268

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/widgets/info-widgets#available-ram
