### ISSUE TITLE
Add a widget to stop a running navigation

### ISSUE THREAD

**Issue by pramach** [osmandapp/OsmAnd#18059]
# 🚀 feature request

### Description

Add a widget to stop a running navigation

### Describe the solution you'd like

There is a widget I can add onto left or right panel, which stops an ongoing navigation

### Describe alternatives you've considered

The current available solution is to click with gloves till you get the navigation window open, where you can stop an ongoing navigation.

**Comment by mikehgentry** [comment]
Probably a duplicate of #15462, although it's not entirely clear what they're planning to do to solve it

**Comment by pramach** [comment]
Yes & Thanks. Sorry but I did not found it while searching.

**Comment by mikehgentry** [comment]
No problem. You can probably close this issue to save developer brain-power :)

**Comment by pramach** [comment]
OK
