### ISSUE TITLE
shop=bedding unusual (suggested in POI creation)

### ISSUE THREAD

**Issue by Dominik-K** [osmandapp/Osmand#1805]

**Comment by xmd5a2** [comment]
Can you please describe what is the problem?

**Comment by Dominik-K** [comment]
When creating an POI for a shop with bed stuff (mattresses, etc.), "shop=bedding" is suggested ([taginfo lists just 43 objects](https://taginfo.openstreetmap.org/tags/?key=shop&value=bedding)). "shop=bed" is the common keyword used for this kind of shops ([taginfo lists 2309 objects](https://taginfo.openstreetmap.org/tags/?key=shop&value=bed)). See also [OSM wiki article for "shop=bed"](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dbed).

With the German OsmAnd version, "Bettwarengeschäft" directly creates "shop=bedding". It should create "shop=bed" as well as the keywords as listed in the wiki article:

	waterbed=*	If water beds are sold.
	bases=*	If the bases for beds are sold.
	mattress=*	If mattresses are sold.
	furniture=*	If other furniture for the bedroom is sold, eg bed side tables.
	linen=*	If linen and other bed coverings is sold.

Sorry for the late answer. I quickly created this issue as a hint to expand it afterwards.

**Comment by xmd5a2** [comment]
Ok, I'll correct this by removing "bedding" and moving en translation from it to "bed".
