### ISSUE TITLE
Latest entries in the search history can not be deleted 

### ISSUE THREAD

**Issue by oxxm** [osmandapp/OsmAnd#18053]
## Description
As mentioned in the title, the latest entries in the search history list can not be deleted. They don't show up within the selectable list of entries. This started happening with the latest update to 4.5.8.

### How to reproduce
1- Open the search history
2- tap and hold the last entry, in order to start selecting

### Actual result
The last entry in the history list is not visible in the selectable list of entries. Only older ones. I assume those are the search entries done with older versions of Osmand < 4.5.8

### Expected result
all entries in the history list should be visible in the list where the user can select the entries to delete

**Environment**
OsmAnd Version: 4.5.8
Android/iOS version: LineageOS 17
Device model: Samsung S9

**Comment by scaidermern** [comment]
Works fine in 4.5.10 for me, also with recent search terms.

**Comment by oxxm** [comment]
Weird enough, only few search terms are excluded from the selection list!

Will give a feedback with the next update.

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#736m, released: 2023-09-08
- *Navigation search* results are displayed in search tab with other search results. At the same time, this type of entries can be deleted only in *Navigation history* tab, not in *Search history* tab.

**Steps to reproduce:**
- Navigation > set destination > search for some POI
- stop route calculation
- go to *Search* (menu > search or by tapping magnifying glass) 
- long tap on your search 
- you will be redirected to *Search history* tab

**Actual result:** 
Entries from *Navigation Search* aren't shown in *Search history* tab, they can be found (and deleted) in *Navigation history* tab.

<table style="width:100%">
  <tr>
    <th>Search results</th>
    <th>Search history</th>
    <th>Navigation history</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/a61cfecd-5819-4626-8fe9-7055df165a19"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/a8883d98-066f-4c46-907e-807bd2bcd5ff"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/e7604951-0039-4eb8-b195-41b03c59da02"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by oxxm** [comment]
how do you get to the _Navigation History_ tab?

**Comment by DmitryAlexei** [comment]
@oxxm 
go to menu > settings > OsmAnd settings > History and choose *Navigation history*

**Comment by oxxm** [comment]
Is it intentional to have 2 separate lists for the same purpose? Wouldn't it be better to have just one list?

Never i would have guessed that there is a second list hidden somewhere in the settings.


@DmitryAlexei Thank you

**Comment by vshcherb** [comment]
Yes 2 lists are intentional so you can disable them separately

**Comment by vshcherb** [comment]
To do: Selecting a searched point listed via the magnifying glass should lead the user to the section it´s listed in and not to somewhere else.
