### ISSUE TITLE
Navigation from point to point, not from my current location.

### ISSUE THREAD

**Issue by EvgenyZaretskiy** [osmandapp/OsmAnd#18065]
Hello. I've got a track in GPX format in Nepal, now I'm in Thailand, started Navigation using that track to check information about the track (elevation profile, distance and so on). OSMAND is trying to navigate me from my current location. What is the point then use preloaded track for navigation? How can I navigate using the track with starting and finishing points different from my current location?

Thank you

**Comment by EvgenyZaretskiy** [comment]
The idea is to navigate from one point to another point using preloaded track or builtin navigation to check a distance from one point to another point or elevation profile in advance, not being at the start or end points.

**Comment by scaidermern** [comment]
You can set a custom start point in the navigation menu. Just _don't_ press start, because that will replace the start point with your current position.
