### ISSUE TITLE
Both original and modified element was displayed caused by Osmand live update

### ISSUE THREAD

**Issue by LaoshuBaby** [osmandapp/OsmAnd#18069]
## Description

OSM map data was modified yesterday, and I found original and modified data both displayed after I check live update

For example, [this way(988323751)](https://archive.ph/qpCkc) was moved and shrinked, here is the comparison of before and after

Before(OSM-Carto)
<img src="https://github.com/osmandapp/OsmAnd/assets/42690037/02790223-4a2c-4106-9339-baf69c89de48" width=400px/>
After(OSM-Carto)
<img src="https://github.com/osmandapp/OsmAnd/assets/42690037/6756f8f8-d14f-4a93-911c-0296417b7b37" width=400px/>

### How to reproduce

1. Download provincial data of Shandong, China
2. Download its live update
3. move to those buildings in Osmand app.
4. Found 2 overleaped grave yard!

(All time shown are in UTC+8)

<img alt="Screenshot_2023-09-01-17-36-05-786_net osmand plus - 副本" src="https://github.com/osmandapp/OsmAnd/assets/42690037/527822db-6a38-4a06-8973-2a336fba315b" width=250px/> <img alt="Screenshot_2023-09-01-17-36-09-022_net osmand plus" src="https://github.com/osmandapp/OsmAnd/assets/42690037/088a2165-1b65-4626-adfe-3931e8e62af4" width=250px/>

### Actual result

<img alt="Screenshot_2023-09-01-10-57-58-042_net osmand plus" src="https://github.com/osmandapp/OsmAnd/assets/42690037/1c7b7ae3-f74e-4735-b72f-8f146e2b63e3" width=650px/>

### Expected result

Only the latest element been shown.

**Environment**
Device : polaris
Brand : Xiaomi
Model : MIX 2S
Product : polaris
Build : QKQ1.190828.002 test-keys
Version : 10
App Version : OsmAnd~
Apk Version : 4.4.7 440703

This is not the first time this kind of error has happened, but this time it was very noticeable, so I reported it as this issue. I suspect that this grave yard appeared once in the monthly data and live update data at the same time.
I didn't find any relevant issues, but this may also be because I didn't search past issues carefully enough. If you find other related issues, please be sure to list them below, thank you!

**Comment by vshcherb** [comment]
Duplicate https://github.com/osmandapp/OsmAnd/issues/17898
