### ISSUE TITLE
Load a GPX Route as markers, not as track

### ISSUE THREAD

**Issue by pramach** [osmandapp/OsmAnd#18061]
# 🚀 feature request

### Description

Allow to load a GPX Route as a predefined sequence of markers, not as a track

### Describe the solution you'd like

While loading a GPX file, Osmand either handle it as a Track to follow, or give me the possibility to load it into a group of markers. 
When importing as a Track, several functions are missing like easy manipulation of the track, like ignoring one or some POI inside the track or mark a POI as passed.
When load as a group of markers, I have to use them one by one again in the navigation, but could do just 2 of them at once.

### Describe alternatives you've considered

Often, road routes are planned as a sequence of POI's (e.g. mountain pass), sometimes enhanced with some helping points in order to declare the road to be taken. Such routes may contain hundred of POI's to be driven over several days.

While loading a GPX file containing route segments, there should be a possibility to load the Route as a route and not as a track. Means, internally the route might be added as a specific marker group (when needed) but should be used in the defined sequence in a way, that the route POI's can be easily maintained while driving.

### Have you considered any alternative solutions or workarounds?

Print out the route, load the GPX into a marker group, then use the printout to navigate to the first POI.
After arriving, I use the printout to navigate to the next POI.
An so on.

**Comment by DmitryAlexei** [comment]
@pramach This issue may have already been implemented:
- you can import GPX as group of markers (see https://docs.osmand.net/docs/user/navigation/setup/markers-navigation#add-gpx)
- you can sort imported map markers using *Plan a route tool* (see https://docs.osmand.net/docs/user/navigation/setup/markers-navigation#sort-markers-with-plan-a-route-tool) and after that 
- use them for navigation *all-at-once* (as intermediate destinations while creating your route) or one-to-one from map markers list without starting navigation

**Comment by pramach** [comment]
Ok. will try tomorrow on my ride
