### ISSUE TITLE
route line not shown in route planning mode

### ISSUE THREAD

**Issue by quantenschaum** [osmandapp/OsmAnd#18075]
## Description

When I start planning a route by placing waypoints, the line connection these points is *not* displayed when in the boating profile using the nautical map style.

### How to reproduce

- switch to boating profile
- use nautical map style
- main menu > plan a route
- place at least 2 waypoints on the map

### Actual result

no line connection the points visible

![Screenshot_20230901-222545](https://github.com/osmandapp/OsmAnd/assets/3985599/94fd7ff1-2682-45c5-a181-cb18ec6bd4a9)
 
### Expected result

line connection the points is visible

![Screenshot_20230901-222504](https://github.com/osmandapp/OsmAnd/assets/3985599/d75a309e-ba96-41fa-9834-ca999ddd6058)

### Workaround

- switch to another profile, no nautical map style
- start route planning
- place waypoints (line is shown)
- cancel route planning
- switch to boating profile
- start route planning

- or switch profile during route planning

- now the line should be visible

**Environment**
OsmAnd Version: 4.5.10
Android version: 13
Device model: Nokia X20

**Comment by DmitryAlexei** [comment]
Reproduced in OsmAnd 4.6.0, released: 2023-09-01 but doesn't reproduced in OsmAnd~ 4.6.0#710m, released: 2023-09-01
How to reproduce:
- go to 53.39591° N, 5.71474° E
- switch to boating profile
- in plan-a-route tool place more than two point 
Actual result: no route between points (see screenshots) in release version

<table style="width:100%">
  <tr>
    <th>OsmAnd 4.6.0</th>
    <th>OsmAnd~ 4.6.0#710m</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/be34248d-eae3-4649-94ce-70a43d595241"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/644a04b5-83be-4ab8-b0a6-382ac3812d07"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
@DmitryAlexei  Screenshots are not correct Straglht line was used in original request not boat profile.
Managed to reproduce 1 time on release version, but once I switch Profile in Configure Map and switched back, thin line appeared (may be thinner than expected?)

**Comment by quantenschaum** [comment]
Yes, but it is the same even with routing enabled between the points. Once you switch profiles, it is working as expected (workaround), but next time the line is missing again.

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#727m, released: 2023-09-05

**Steps to reproduce:**

- go to 53.39591° N, 5.71474° E
- switch to boating profile
- open plan-a-route tool, choose *Straight line* profile
- place more than two points

 **Actual result:**
- no route between points (see video) in nightly build


https://github.com/osmandapp/OsmAnd/assets/116079541/c0d201d2-7929-4a9b-9880-7122c01b6207
