### ISSUE TITLE
Part of the road cannot be used for routing

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd#18071]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing

Car profile

### Start and end points

- Starting point 40.73629, -4.25995
- End point 40.74202, -4.26553

### Actual and expected routes

**Actual route**
- [OsmAnd map](https://test.osmand.net/map/?start=40.736291,-4.259949&end=40.742022,-4.265528&type=osmand&profile=car#15/40.7378/-4.2671)
- OsmAnd app
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/9be25ba6-18f0-4abc-a1e5-5892c25a3a20"  width="300" height="auto"/> </td>
  </tr>
</table>

- OsmAnd does not use part of the Carretera Madrid a A Coruña road ( https://www.openstreetmap.org/way/409288532 ), that is located under viaduct (https://www.openstreetmap.org/way/450243975)
- This part of the road cannot be used for routing with other profiles

**Expected route**

As on the Openstreetmap https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=40.7380%2C-4.2608%3B40.7400%2C-4.2629#map=17/40.73820/-4.25963

## 🌍 Your Environment

**OsmAnd Version:**

OsmAnd~ 4.6.0#710m, released: 2023-09-01

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.

**Comment by vshcherb** [comment]
Regenerating map doesn't produce an error

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#814m, released: 2023-09-28
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/b681daf9-6a51-4eb3-b8b3-22632e707a94"  width="300" height="auto"/> </td>
  </tr>
</table>
