### ISSUE TITLE
Support importing and removing OBF files when using internal app storage

### ISSUE THREAD

**Issue by jahed** [osmandapp/OsmAnd#18074]
# 🚀 feature request

### Description

I need to add custom OBF files so that I can search UK post codes using https://github.com/hvdwolf/OsmAnd-UKpostcodes

Currently, to add custom OBF files, I need to manually add files to OsmAnd's directory using a file manager. When using "Internal app memory" as OsmAnd's storage folder, only OsmAnd has access to the directory so I can't add custom OBF files.

I'd like an option to import custom OBF files from OsmAnd's UI so that OsmAnd can add and remove files as needed from its internal app directory.

### Describe the solution you'd like

Custom imports can appear on the "Download maps" screen, under the "Local" tab, maybe as a separate "Custom" or "Imported" section.

An option to import files can appear under that section too.

Imported files can also be removed from here similar to the other downloads.

### Describe alternatives you've considered

There are other issues related to this specific "UK postcode" use case (#5497, #9758). The interim solution to those is to not use internal app storage so that files can be manually added to OsmAnd's directory using a file manager. I'd like to avoid doing this.

Internal app storage is useful from a security/privacy perspective as it avoids needing to give OsmAnd additional storage permissions and avoids making OsmAnd's data available to other apps.

Manually modifying OsmAnd's directory also leads to other issues such as OsmAnd not detecting the new files until restart and files not writing properly due to possible permission issues. https://github.com/osmandapp/Osmand/issues/5497#issuecomment-580254433

**Comment by DmitryAlexei** [comment]
@jahed the issue is about postcodes or about *how to import .obf files*?

- you can tap on an .obf file (in your file manager program) and choose *Open in OsmAnd*. The file will be downloaded into the specified memory.

**Comment by jahed** [comment]
The feature request is to support importing OBF files via OsmAnd's app interface.

I tried "Open with" but OsmAnd doesn't show up as an option. I'm using Samsung's default file manager. OsmAnd doesn't appear on the "Share" dialog either.

I installed OsmAnd via F-Droid, but I don't think that makes a difference?

Even if that did work, is there an interface to remove the file if it's no longer needed? If not, since only OsmAnd can access its own app storage, I'll end up with duplicate files and stale data that I can't see or remove.

**Comment by DmitryAlexei** [comment]
<table style="width:100%">
  <tr>
    <th>importing obf</th>
    <th>deleting obf</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/116079541/b2720792-1568-4862-9348-ea1add5c5088"  width="200" height="auto"/></td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/116079541/68d233c4-b2b6-4f3c-9cb8-5b7c8684ffa5"  width="200" height="auto"/></td>
  </tr>

**Comment by jahed** [comment]
Thanks. Good to know this feature is already in place and might just have a bug or limitation.

As I mentioned, OsmAnd doesn't appear in that "Open with" dialogue for me so I can't use it.

@DmitryAlexei Are you using internal app storage? It's possible "Open with" only appears if OsmAnd is given full file access permissions, which I don't want to give as it defeats the point of using internal app storage.

I can open a separate issue for this if that's preferred.

**Comment by DmitryAlexei** [comment]
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/165abab9-95d1-446b-94be-c3e929f2ac86"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/86f850fd-6c51-4e11-bcfa-98a5ea650d4e"  width="300" height="auto"/> </td>
  </tr>
</table>
I've got Android 13 Samsung device.

Maybe there is a way to change file associations on your phone?

**Comment by jahed** [comment]
Oh, I realised, in your screenshot, you're opening an OSF file. Whereas I'm opening an OBF file.

https://osmand.net/docs/technical/osmand-file-formats/osmand-obf

There's no file associations for OSB files in the manifest:

https://github.com/osmandapp/OsmAnd/blob/530d2cfbe99291075e371e71203f68852e845b56/OsmAnd/AndroidManifest.xml#L395

Can they be added?

**Comment by DmitryAlexei** [comment]
@jahed I opened .obf file
<img width="226" alt="Screenshot 2023-09-06 100135" src="https://github.com/osmandapp/OsmAnd/assets/116079541/371b2c42-1792-4b3b-bc2b-4f7f73b23df9">
