### ISSUE TITLE
Pin details only show altitude if 3d relief is on

### ISSUE THREAD

**Issue by ManDay** [osmandapp/OsmAnd#18085]
Not sure whether feature request or bug, but it appears the altitude of a dropped pin is only displayed if 3d relief is turned on. As soon as it's turned off, the altitude no longer shows.

**Comment by DmitryAlexei** [comment]
<table style="width:100%">
  <tr>
    <th>3D on</th>
    <th>3D off</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/22409cef-8c43-484a-a0f6-3d8ae933db9c"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/a20607a5-d8e3-4d9d-a68c-f0c271c82cd9"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by ManDay** [comment]
The "Elevation at map position" widget, too, it seems.

**Comment by creeper82** [comment]
Bump. I was literally about to post the same issue. I dream about the possibility of checking altitude for so long, and it's done very well. However, it should be a standalone setting at least

**Comment by vshcherb** [comment]
To do: all these feature should be working if 3d map is available

**Comment by zipav** [comment]
OsmAnd Nightly 4.7.0#1578m, released: 2024-02-12

<table style="width:100%">
  <tr>
    <th>3D on</th> 
    <th>3D off</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/6fbc340c-bda4-4216-bd36-198d051364bd"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/a162e42a-c658-4bce-ab2f-eab8998044d4"  width="300" height="auto"/> </td>
  </tr>
</table>
