### ISSUE TITLE
Route planner recalculates route too late

### ISSUE THREAD

**Issue by MarkuBu** [osmandapp/OsmAnd#18088]
Every time I deviate from the given route, it takes a very long time for a new route to be calculated. 

I always get a route displayed in the opposite direction until the route I am on is shorter than the original one.

For example, if I have to go around a construction site in a wide arc, it takes a very long time until I get the new route displayed.

I have both "Recalculate route" options enabled and the minimum distance for recalculation set to 20m.

Router zlzk.biz
OsmAnd+ version 4.5.10
Android 13
Pixel 7

**Comment by DmitryAlexei** [comment]
@MarkuBu 
- Have you got *Offline calculation of OsmAnd route segment* option enabled?  https://osmand.net/docs/user/navigation/routing/online-routing#online-routing-setting

- does this issue appear when you use offline routing?

**Comment by DmitryAlexei** [comment]
Mostly, if you deviate from online calculated route, you will be guided to it (similar to GPX routing https://osmand.net/docs/user/navigation/setup/gpx-navigation#guidance)

**Comment by MarkuBu** [comment]
I use zlzk online routing, as mentioned.

Because offline routing is extremely slow. It takes long to calculate longer routes. But I will try the offline routing

**Comment by vshcherb** [comment]
We're going to improve offline routing by the end of the year
