### ISSUE TITLE
3D Relief setting ignored across profile switches

### ISSUE THREAD

**Issue by ManDay** [osmandapp/OsmAnd#18084]
F-Droid 4.5.8, the 3D Relief setting is inconsistently applied when switching profiles. I haven't figured out the pattern by which it is or isn't respected, but it occurs in both directions. When this happens, the 3D (tilted) view shows (no) relief, while the toggle-switch for "3D Relief" is off (on). Toggling the switch induces the correct rendering.

**Comment by vshcherb** [comment]
Can't reproduce, so it might be very tricky. 
I have 2 profiles with 3d relief on and off, switching between them correctly displays hillshades.

**Comment by ManDay** [comment]
Ok, anything I can do to help with reproducibilty? Anyway here is a video to illustrate:

https://github.com/osmandapp/OsmAnd/assets/1059827/a206b25f-8e61-467b-b65c-0371493c4d25

**Comment by scaidermern** [comment]
I can reproduce this with version 4.5.10.

Steps:
* Enable 3D relief for profile 1, disable it for profile 2
* In profile 1 enter 2.5 D by pressing the 3D button: the terrain is rendered in 3D
* Switch to profile 2. The terrain is still rendered in 3D although the 3D relief is disabled for this profile.

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To illustrate, when you select two profiles and activate 3D relief in the first one while deactivating it in the second one, an issue arises. If you then view the map in a profile with 3D relief enabled and switch to a profile with 3D relief disabled, the function doesn't automatically disable itself when changing profiles. Conversely, if you view the map in a profile with 3D relief turned off and switch to a profile with 3D relief turned on, the function doesn't automatically activate itself when changing profiles.

OsmAnd~ 4.6.0#727m, released: 2023-09-05


https://github.com/osmandapp/OsmAnd/assets/127092082/c85a6b7c-b69f-4c61-8381-ad624822693e

**Comment by ManDay** [comment]
To be fair and echo @vshcherb's comment, it isn't 100% reliable, at least for me. When I played around with it, it sometimes spontaneously started working, just to stop working at a later time. Hence my saying I couldn't spot the pattern.

**Comment by yuriiurshuliak** [comment]
The issue has been resolved. Now, if you choose two profiles and enable 3D relief in the first one while disabling it in the second, when you switch between profiles, the 3D relief will behave in accordance with each profile's settings.

OsmAnd~ 4.6.0#806m, released: 2023-09-25



https://github.com/osmandapp/OsmAnd/assets/127092082/d5f09a73-c6fb-47f0-b72a-30f2d3bd506a
