### ISSUE TITLE
3D only for navigation

### ISSUE THREAD

**Issue by gtrus21** [osmandapp/OsmAnd#18080]
Please add an option so that during normal map review (or during pause) the map switches to 2D mode, and when navigating back to 3D

**Comment by vshcherb** [comment]
It's possible to have different profiles configured, so 1 in 3d, 2nd in 2D

**Comment by gtrus21** [comment]
Но для чего создавать 2 профиля? Мне нужно во время навигации возможность поставить на паузу и в удобном 2D режиме осмотреть карту, после чего продолжить маршрут

**Comment by gtrus21** [comment]
Ну или хотя бы добавьте кнопку "3D", у вас ведь есть кнопка 2D

**Comment by scaidermern** [comment]
There is already a button to switch between 2D and 3D.
