### ISSUE TITLE
Offline Rendering: City Label and Island Name by Population

### ISSUE THREAD

**Issue by ax3l** [osmandapp/Osmand#1809]
In offline rendering, the decision for which name label to be shown in an area if not all can be placed should be made by `population` tag.

E.g., in the German cities "Augsburg"/"Ingolstadt"/"Salzburg" should not be preferred over "Munich" in low zoom levels (alternatives in CA, USA: "Richmond" dominates over "San Francisco" in most intermediate zoom levels). This is currently highly confusing for people trying to find cities or districts on the map (without GPS assistance / being there, e.g., for travel planning).

The same applies to naming of islands, on should either prefer larger one's names by population (or alternatively by size if that is possible).

**Comment by xmd5a2** [comment]
Already fixed.

**Comment by ax3l** [comment]
@xmd5a2 thank you for the quick answer, that is great!

Which version fixed it?
I am using `OsmAnd~ 2.1.1` via F-Droid (sry, forgot to mention that in the report).

**Comment by xmd5a2** [comment]
Wait for next release (1-2 months) or use nightly with this basemap https://dl.dropboxusercontent.com/u/4624786/osm/World_basemap.zip

**Comment by ax3l** [comment]
wow cool, so in now release yet and very fresh.

thank you a bunch, that is a great new feature! :sparkles:

**Comment by sonora** [comment]
Leonid, is it also fixed for our standard (region/country) maps? If you
look at e.g. our Italy maps, the label for Naples (a big city) is very hard
to find, mostly hidden by all of its suburbs, it seems. Similar, but not
quite as bad on most zoom levels, is Rome.

Best, Hardy

**Comment by xmd5a2** [comment]
@sonora Just update maps

**Comment by xmd5a2** [comment]
@sonora Naples and Rome are visilble at 6+ zooms, no exceptions

**Comment by sonora** [comment]
Yes, true, thanks! Naples and Rome now visible at 12+ zooms, lower zooms
will need new basemap, I guess. Thx - Hardy
