### ISSUE TITLE
Nautical feature request: Clearance height of bridges

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#18094]
A user complains we do not display the clearance height (of going under bridges) on our nautical map. Not sure such data is available in our maps, but if yes  I guess we should display it?

**Comment by DmitryAlexei** [comment]
Size parameters of your vessel can be set in Navigation settings of boat profile (see https://osmand.net/docs/user/navigation/guidance/navigation-settings#size-parameters) and they will be used for navigation (route calculation).

- According to tag.info there are more than 6,000 objects tagged **seamark:bridge:clearance_height** (https://taginfo.openstreetmap.org/keys/seamark%3Abridge%3Aclearance_height#overview) and more than 5,000 tagged **seamark:bridge:clearance_width** (https://taginfo.openstreetmap.org/keys/seamark%3Abridge%3Aclearance_width#overview)

According to OSM wiki, the tag **seamark:bridge:category** is used for routing purposes. It should be placed on the waterway beneath the bridge (https://wiki.openstreetmap.org/wiki/Key:seamark:bridge:category)

**Comment by sonora** [comment]
Yes, but the navigation is a slightly different use case from when you just explore the map. Perhaps we could somehow try to cover that, too, and if just by displaying the clearance upon tapping a bridge in its context menu?

**Comment by dreua** [comment]
Works for me:
https://www.openstreetmap.org/node/2774989813
![signal-2023-09-19-224950_002-clearance](https://github.com/osmandapp/OsmAnd/assets/15114715/a8a643a1-fa7f-41f1-be8b-aee45fbf8e35)

**Comment by sonora** [comment]
Yes, true. So can we assume that where it's missing, it's missing in the map data? Or is there some other issue why so many bridges in OsmAnd don't show it?

**Comment by dreua** [comment]
I guess it is just missing data, even if the height might he present in some other tag I'd say it would be too risky to display it as clearance height. Its probably also a question of sourcing the data as copying it from nautical charts poses legal risks, but that's just me guessing.

**Comment by dreua** [comment]
I wonder if it would make sense to make an effort to add that data, maybe ask StreetComplete to add such a quest? Might be off their main topic though but maybe we could have it disabled by default so that the nautically inclined can enable it and have it as a reminder whenever they map near bridges...
