### ISSUE TITLE
Not displayed some track folders from OsmAnd Cloud

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#18098]
## Description

Not displayed some track folders from OsmAnd Cloud

### How to reproduce

- Create new track folders with track data on your OsmAnd Cloud by web service  www.osmand.net/map
I created 'EZ-tracks' and 'KR-tracks' folders.

![image](https://github.com/osmandapp/OsmAnd/assets/44466116/4cf31e41-0ab6-4073-b18e-3e14f3ba59fc)

- Sync your Cloud data on your device

### Actual result

Two folders (EZ-tracks and KR-tracks) were not synchronized with OsmAnd Cloud on the APP.

|Web track folders| App track Folders|
|---------|---------|
|![image](https://github.com/osmandapp/OsmAnd/assets/44466116/03bb2806-580c-4d3c-9a51-9d6327b5f07c)|<img width="373" alt="image" src="https://github.com/osmandapp/OsmAnd/assets/44466116/1d0140cc-ac6a-4c4e-8953-287aa90fefb4">|

### Expected result

'EZ-tracks' and 'KR-tracks' folders will be synchronized on the app with OsmAnd Cloud.

**Environment**
Device : r0s
Brand : samsung
Model : SM-S901B
Product : r0sxeea
Build : TP1A.220624.014.S901BXXS6CWGA
Version : 13
App Version : OsmAnd~
Apk Version : 4.6.0#683m 4600

[logcat (2).log.zip](https://github.com/osmandapp/OsmAnd/files/12523894/logcat.2.log.zip)

**Comment by dmpr0** [comment]
# Review 
- [ ]  ToDo is missing, what was done too.

**Comment by vshcherb** [comment]
@EugeneZmeuk is result ok?

**Comment by EugeneZmeuk** [comment]
The result is Ok.
I tested it today again:
- I created two new folders with 3 GPX tracks on the web service, and saved it on my Cloud (web)
- opened the OsmAnd app and synced data from OsmAnd Cloud
- Two new folders with GPX tracks appeared on My Places - Tracks menu
