### ISSUE TITLE
Mirrored dependencies - ICU archive corrupted

### ISSUE THREAD

**Issue by licaon-kter** [osmandapp/OsmAnd#18097]
https://creator.osmand.net/dependencies-mirror/

`icu4c-52-1.tar.gz` is ~25Mb and errors out on extraction

but `bak/icu4c-52-1.tar.gz` is ~47Mb and extracts fine

ref: https://gitlab.com/fdroid/fdroiddata/-/issues/3046#note_1543488691

**Comment by vshcherb** [comment]
Smaller icu needed to make app footprint smaller but it's fine to use full one

**Comment by licaon-kter** [comment]
wat? It's not about size but about gzip erroring out and stopping the build process
```
$ gzip --test icu4c-52-1.tar.gz

gzip: icu4c-52-1.tar.gz: unexpected end of file
```

Can you replace it with a non-broken file, of whatever size you want?

**Comment by licaon-kter** [comment]
The broken file has been fix :+1:
