### ISSUE TITLE
Navigating by track crashes the application

### ISSUE THREAD

**Issue by btbroot** [osmandapp/OsmAnd#18109]
## Description
Navigating by track crashes the application
### How to reproduce
* Import file *FIN.gpx* from https://transeurotrail.org/finland/
* Select track *TET_FIN-05_20230731* on the map and start navigating by the track
### Actual result
The app crashes randomly in few minutes
### Expected result
No crash occurs

**Environment**
Device : r0s
Brand : samsung
Model : SM-S901B
Product : r0sxeea
Build : TP1A.220624.014.S901BXXS6CWGA
Version : 13
App Version : OsmAnd
Apk Version : 4.5.10 4510

[logcat.log](https://github.com/osmandapp/OsmAnd/files/12541725/logcat.log)

**Comment by vshcherb** [comment]
Unfortunately no information in the logcat, probably it's realted to OOM crashes with TET routes which are too big to handle. We currently aim to support GPX tracks with 500K points for viewing and similar but not measured yet for navigation.

**Comment by vshcherb** [comment]
Track contains </wpt> - 336 </trkpt>  - ~ 100K. So it should be handled correctly in new beta build Android (4.6.0)

**Comment by btbroot** [comment]
Excuse me my ignorance in Java, but shouldn't it throw a *java.lang.OutOfMemoryError* exception in such case? Because I couldn't see any exceptions in the *logcat* file

**Comment by zipav** [comment]
OsmAnd Nightly 4.6.0#734m, released: 2023-09-08

Importing .gpx does not crash the app, also if display all tracks at the same time on the map, there is no crash in the latest OsmAnd Nightly

**Comment by btbroot** [comment]
Same behavior on 4.6.0

Device : r0s
Brand : samsung
Model : SM-S901B
Product : r0sxeea
Build : TP1A.220624.014.S901BXXS6CWGA
Version : 13
App Version : OsmAnd
Apk Version : 4.6.0 4600

[logcat (2).log](https://github.com/osmandapp/OsmAnd/files/12565467/logcat.2.log)

**Comment by vshcherb** [comment]
Log doesn't have any information cause it's done before the crash. Please enable Memory widget (form development widgets) and if you see before the crash that memory limit is not increasing then problem is likely due to memory. Please also let us know what's you memory limit you see (should be 512 MB on new devices)

**Comment by btbroot** [comment]
On Galaxy S22 with the default motorcycle profile screen plus the Memory widget, local vector maps and no tracks, I immediately see 90 MB reserved memory. This is a big discrepancy

**Comment by btbroot** [comment]
On Galaxy S22 with the default motorcycle profile screen plus the Memory widget, local vector maps and no tracks, I immediately see 90 MB reserved memory. This is a big discrepancy
