### ISSUE TITLE
Search should return results in other languages, even if "Use latin name if missing" is enabled

### ISSUE THREAD

**Issue by balporig** [osmandapp/OsmAnd#18101]
## Description

If `Use latin name if missing` Map Language option is enabled, and you search for existing POI in a non-latin language for POI with name in non-latin language no results will be returned

Related: #15579

### How to reproduce

POI Name: "Агенция за устойчиво енергийно развитие"
Location:42°42′2″N, 23°19′27″E - 42.7005858, 23.3241546

Make sure you're using the latest OSM data

Enabled `Use latin name if missing` under Configure Map > Map rendering > Map language
Map Language: English

Enter in search: "агенция за устойчиво"

### Actual result

The POI will not be found

### Expected result

The POI should be found. Search only accounts for the transliterated display name.

If you disable `Use latin name if missing` option, the POI shows in search results

Search should take into account:

- transliterated name if `Use latin name if missing` (which is already does)
- all `name` attributes in all languages set on a given node (`name`, `name:en`, `name:es` etc.)

**Environment**
OsmAnd Version:4.5.8
Android/iOS version: Android 10
Device model: Samsung Galaxy S10

**Comment by DmitryAlexei** [comment]
**OsmAnd~** 4.6.0#755m, released: 2023-09-13
POI Name: "Агенция за устойчиво енергийно развитие" https://www.openstreetmap.org/node/211381 (this poi was recently changed - 9 days ago, so I used actual OsmAnd map data), also tested other POI

<table style="width:100%">
  <tr>
    <th>Local names</th>
    <th>English names (Use latin name if missing)</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/ee2da123-18a2-4422-adc8-29c0a66795cf"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/8e2aecd6-cb3d-435f-b84e-77115551e894"  width="300" height="auto"/> </td>
  </tr>
</table>

**Steps to reproduce:**
- in menu > Configure map > Map language enable _English names_ and _Use latin name if missing_  options
- go to 42°42′2″N, 23°19′27″E
- search for "агенцията" 

**Actual result:**
- when _English names_ and _Use latin name if missing_ enabled, search works only with transliterated names, actual names (tag name=*) is not taken into account
- only 1 variant of transliteration is used, so you will not find object when transliteration is slightly different (for example ahientsiiata, aghienciiata, aghientsiata, ahientsiiata etc.).

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/ed53085c-96ce-4f63-97cf-f9fdadc4d3d9"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/0f4cffd5-63ba-4b4e-9c5e-b3c69158175d"  width="300" height="auto"/> </td>
  </tr>
</table>

- important to note, that when "Local names" option enabled, transliterated names are searchable

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/93c97cc0-e75c-43cd-ad17-0452ddfc33ad"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
**To do**
Even with ```English names and Use latin name if missing enabled```, search should be able to find object with native name

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.7.0#1813m, released: 2024-03-12 **This issue is no longer reproducible.** 
- when searching for "Агенция" search returns **the same results** both when _Local names_ or _English names and Use Latin name if missing_ options enabled (menu > configure map > map language)

Important to note, that in Context menu of tested POI https://www.openstreetmap.org/node/211381 not all tags were displayed
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/8309ac4b-c93a-4b5d-86bc-2c102a2c3c86"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/c248cd7f-4734-4a34-bfcc-f80509e39ca9"  width="500" height="auto"/> </td>
  </tr>
</table>
