### ISSUE TITLE
Crosswalk warning too early

### ISSUE THREAD

**Issue by Prusaker** [osmandapp/OsmAnd#18102]
In Car profile typically, a pedestrian crossing warning appears shortly before the crossing.
However, in some cases, the warning sounds long before the pedestrian crossing.
I noticed that this happens if, when approaching a pedestrian crossing, you need to make a turn or exit from the road.

How to reproduce:
Try to build route (Car profile) from 53.8567593, 27.477711 to 53.859509, 27.4790297, turn on "Simulate navigation" and let the OsmAnd follow the route (his bug appears during real movement along the route, but it is also well reproduced when simulating movement).
Along the way, you will need to make one U-turn and turn right.
The warning about the approach to the crossing appears long before the turn and even more so long before the transition itself.

![111](https://github.com/osmandapp/OsmAnd/assets/32092837/0fdc3324-ec0d-4326-9267-5e9e72d60ff2)

It would have been logical to issue a crossing warning just before the crossing, but not a few minutes before I reach the crossing.

This program behavior manifests itself in many places.

**OsmAnd Version:** 4.4.7
**Device and Android/iOS version:** Nexus 6, Android 7.7.1
**Maps used:** offline

**Comment by yuriiurshuliak** [comment]
I tested the latest nightly version and the most recent TestFlight version, and in both instances, I was able to replicate the bug where the "Pedestrian crosswalk" warning was displayed incorrectly. To reproduce the issue, I created a route using user-specified coordinates, enabled voice prompts and navigation simulation, and observed that there were two "Pedestrian crosswalk" warnings along the route despite there being only one pedestrian crossing.

It's worth noting that one of the "Pedestrian crosswalk" warnings occurred after the navigation had ended. Additionally, another "Pedestrian crosswalk" warning was triggered on the following road: https://www.openstreetmap.org/way/28833048.

Here is a link to the pedestrian crossing location on this route: https://www.openstreetmap.org/node/2834305573#map=19/53.85924/27.47922


OsmAnd~ 4.6.0#727m, released: 2023-09-05
OsmAnd 4.5.1.8

<table style="width:100%">
  </tr>
  <tr>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/612ee1e5-0bcb-4f55-97e4-ff8db45b74bc"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/e2cdfa26-7f6e-4cff-a33f-a4f997d61a43"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by Prusaker** [comment]
I confirm - already after the end of the route, the navigator often voices a warning about the crossing. There may also be a "stop sign" warning.

I saw this bug on older versions of the program (since 3.3), and it appears in all versions so far.

**Comment by Dima-1** [comment]
[Test map  45.91949° N, 35.20644° E](https://github.com/osmandapp/OsmAnd/files/13841095/Alarm_test.zip)

**Comment by vshcherb** [comment]
- [ ] Fix Tests https://creator.osmand.net:8080/view/OsmAnd%20Builds/job/OsmAnd-ui-tests/

**Comment by yuriiurshuliak** [comment]
The issue persists. Presently, the pedestrian crossing notification occurs only once, but it's in the incorrect location. The alert is triggered before reaching the pedestrian crossing, specifically at the start of the route, when it should be activated at the route's end.

OsmAnd~ 4.7.0#1485m, released: 2024-01-31
OsmAnd 4.7.1.3
<table style="width:100%">
  </tr>
  <tr>
    <th>iOS</th>
    <th>iOS</th>
  </tr>
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/26164b52-5340-4df3-b56d-82ea582d430b"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/f41d2acd-402b-43a8-b7db-6e51d60d5f18"  width="300" height="auto"/>   </td>
      </tr>
</table>

<table style="width:100%">
  </tr>
  <tr>
    <th>Android</th>
    <th>Android</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/dbe477ba-b556-4742-8ba1-6a239876d56a"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/696aba53-6eb9-434f-88e9-8efb7e952985"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by Dima-1** [comment]
For correct testing alert widgets and voice prompts we need to use fixed speed or realistic simulate navigation mode

**Comment by yuriiurshuliak** [comment]
Using the realistic simulate navigation mode, the "Pedestrian crosswalk" is detected 150 metres before the [specified location.](https://www.openstreetmap.org/node/2834305573#map=19/53.85924/27.47922)


OsmAnd~ 4.7.0#1497m, released: 2024-02-02

https://github.com/osmandapp/OsmAnd/assets/127092082/44610ec8-1156-4ad9-977e-7b6de149c43e

**Comment by dmpr0** [comment]
Works on iOS
