### ISSUE TITLE
Render highway=emergency_bay POIs

### ISSUE THREAD

**Issue by lcosmin** [osmandapp/OsmAnd#18107]
# 🚀 feature request

### Description

Add a POI category to allow displaying [highway=emergency_bay](https://wiki.openstreetmap.org/wiki/Tag:highway%3Demergency_bay) on the map, maybe marked with a "P" as regular parking.

They're very useful for emergency stops along a road, so it's useful to be able to see them while navigating.

**Comment by tradavyvy** [comment]
I would not mark them as a regular parking spot.
Different collor maybe, or a P in a triangle.

**Comment by lcosmin** [comment]
Indeed, it makes sense to have it drawn differently.

**Comment by xmd5a2** [comment]
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/b02ef70e-56a1-4dab-b693-8a07f7e03994)

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#848m, released: 2023-10-09 
tested on object with coordinates 49.5102835, 6.2141472
- [highway=emergency_bay](https://wiki.openstreetmap.org/wiki/Tag:highway%3Demergency_bay) poi is displayed on the map starting from zoom level 18. 
- info about emergency_bay also added to *[Map legend](https://osmand.net/docs/user/map-legend/osmand#emergency)*

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/3b68202f-008c-4c3e-8d00-dcf9fae2f83e"  width="300" height="auto"/> </td>
  </tr>
</table>
