### ISSUE TITLE
"Difficulty classification" setting shows "disabled" after being enabled

### ISSUE THREAD

**Issue by ejain** [osmandapp/OsmAnd#18111]
## Description

The _Difficulty classification_ settings continues to be labelled as _Disabled_ even after being enabled.

### How to reproduce

1. Go to _Configure map_.
2. Scroll to the _Difficulty classification_ setting (under _Routes_).
3. Toggle the setting on.

### Actual result

The toggle control for _Difficulty classification_ appears enabled, and the hiking grades are visualized on the map as expected. But the setting continues to show be labelled as _Disabled_, even after closing the settings or even restarting the app. Other settings change to _Enabled_ when toggled on, as expected.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/1323903/c0719d09-a601-4030-a2e0-d0b9188d2912"  width="300" height="auto"/> </td>
  </tr>
</table>

### Expected result

The label under the _Difficulty classification_ setting should change from _Disabled_ to _Enabled_.

**Environment**

OsmAnd Version: 4.5.10
Android/iOS version: Android 13
Device model: Pixel 6a

**Comment by yuriiurshuliak** [comment]
I was unable to replicate this issue. In my attempt to reproduce it, I navigated to the Menu, selected "Configure map," then went to "Routes" and toggled the switch for "Difficulty classification" to the 'On' position. The switch displayed "On, SAC," and I did not observe any indication of "Disabled." I made further attempts to reproduce the bug using various profiles and settings, but without success.

To assist us in identifying and addressing this bug, please provide more specific conditions and detailed steps for reproduction. Additionally, it would be greatly helpful if you could record a brief video demonstrating the issue.

We also recommend trying our latest nightly build of the app to see if the bug persists: https://download.osmand.net/latest-night-build/OsmAnd-default.apk

OsmAnd~ 4.6.0#736m, released: 2023-09-08

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/cfbbe6c9-a59c-4ef8-b2d2-d42e84c6b281"  width="300" height="auto"/> </th>
</tr>
</table>

**Comment by Terra6x** [comment]
I have the same bug in latest store version and the beta version OsmAnd+ 4.6.1. But if I use a new installation, e
g. the nightly version OsmAnd Nightly 4.6.0#802m the error doesn't occurs.

**Comment by DmitryAlexei** [comment]
Related https://github.com/osmandapp/OsmAnd/issues/17946
