### ISSUE TITLE
Moped Profile: Don't allow routing over bicycle-lanes or forest paths

### ISSUE THREAD

**Issue by Jsn42** [osmandapp/OsmAnd#18115]
Version 4.5.8 from the F-drois Store

I'm located in Germany an I have made a lot Trips with the Vespa and OSM And Pro with the Moded Profile.

Routing Mistake in Germany:

The Moped Profile route me a lot up bicycle lanes or forest-roads. This roads are allowed for bicycles, but not for Mopeds in Germany. The routing by the Moped-Profile make some problems in context with the use from bicycle-lanes.

The avoiding of Trunk roads, in german called: Kraftfahrtstraße, https://de.wikipedia.org/wiki/Kraftfahrstra%C3%9Fe works very well.
Trunk roads are not allowed for mopeds in germany.

Vehicle: Vespa Primavera 50
EU Driving Licence Class: AM
Max Speed: 45 km / h
https://www.vespa.com/de_DE/models/primavera/primavera-50-4t-3v-2020/

A Moped like the Vespa with 50 cc is not a Bicycle.

Is it possible to make the usage of bicycle-lanes and paths are switchable like the usage of ferrys ?
In my opinion this is a good solution.

Kind Regards
Jsn42

**Comment by Jsn42** [comment]
Version 4.5.8 from the F-drois Store

I'm located in Germany an I have made a lot Trips with the Vespa and OSM And Pro with the Moded Profile.

Routing Mistake in Germany:

The Moped Profile route me a lot up bicycle lanes or forest-roads. This roads are allowed for bicycles, but not for Mopeds in Germany. The routing by the Moped-Profile make some problems in context with the use from bicycle-lanes.

The avoiding of Trunk roads, in german called: Kraftfahrtstraße, https://de.wikipedia.org/wiki/Kraftfahrstra%C3%9Fe works very well.
Trunk roads are not allowed for mopeds in germany.

Vehicle: Vespa Primavera 50
EU Driving Licence Class: AM
Max Speed: 45 km / h
https://www.vespa.com/de_DE/models/primavera/primavera-50-4t-3v-2020/

A Moped like the Vespa with 50 cc is not a Bicycle.

Is it possible to make the usage of bicycle-lanes and paths are switchable like the usage of ferrys ?
In my opinion this is a good solution.

Kind Regards
Jsn42

**Comment by mikehgentry** [comment]
@vshcherb I might be misreading, but I think the post states that the motorway behaviour is *correct*. The thing they're struggling with is it's using bicycle lanes / forest paths.

**Comment by Jsn42** [comment]
The Problem is the using bicycle lanes / forest paths. This is in Germany not allowed.

**Comment by scaidermern** [comment]
@Jsn42 You can change the title yourself (edit button right next to it, I think). Please do so. The new title is wrong and will lead into the wrong direction.

**Comment by xmd5a2** [comment]
@Jsn42 OsmAnd current moped routing shouldn't route over cycleways that are exclusively for bicycles. But it routes over ways with various `cycleway:left/right=*',`cycleway:both=*`,`cycleway=lane/track` etc. as additional tag. Is it a problem for you? Can you provide such route?
What do you exactly mean under *forest paths*? Can you provide a link to such path?
