### ISSUE TITLE
Update progress when copying files to a new storage directory

### ISSUE THREAD

**Issue by bsidhom** [osmandapp/Osmand#1811]
When the storage directory is changed, the app gives the user the option to copy files from the old location to the new location. During the copy process, a progress dialog is shown. The name of the current file being copied is shown, but the [progress percentage stays at 0%](https://github.com/osmandapp/Osmand/blob/27ba888bf105396cd140011f05d29ac2a5db3f6b/OsmAnd/src/net/osmand/plus/ProgressImplementation.java#L226).

The progress bar should either be updated as files are copied or the progress indicator should be removed altogether (opting for something like a loading spinner instead).

**Comment by vshcherb** [comment]
Added, please test in nightlies.
