### ISSUE TITLE
Multiple net.osmand.plus folders

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#18117]
I have received complaints from users that upon installation the app creates multiple net.osmand.plus folders on the device, while only one of them is the actual data folder the app uses.

And in deed, inspecting several devices, I find such folders (most of them empty) in various locations like (internal)/Abdroid/data, (internal)/Android/obb, (SD)/Android/obc, etc. I can imagine we perhaps create these upon installation to test which folders are writable for the app, but then fail to delete all but the one finally selected by the user as the actual data folder?

Multiple osmand folders are often a nuisance for support, users view, or place files in, wrong folders when asked to check or test something, etc.

**Comment by vshcherb** [comment]
During installation it shouldn't be acase cause only Internal memory should be used

**Comment by zipav** [comment]
OsmAnd+ 4.5.10, released: 2023-08-09

After installing Osmand+ from Play Store, the folder appears in the directory (internal)/Android/obb, and also (internal)/Android/data.
Unfortunately it is not possible to check whether the net.osmand.plus folder appears on the SD-card.

**Comment by vshcherb** [comment]
**To do**: OsmAnd should create any root folder ```(internal)/Abdroid/data, (internal)/Android/obb, (SD)/Android/obc``` only if it was selected at least once during settings change.

**Comment by Corwin-Kh** [comment]
/Abdroid/data and Android/obb are system folders. They are created by Android on application start. We can't  change that behaviour

**Comment by dmpr0** [comment]
# Review 
- [ ] Only `net.osmand` folder is visible in Android/obb, any other app doesn't show folder here.

**Comment by vshcherb** [comment]
That's ok as it's an empty folder so we know that could suggest Shared Multi user storage which I personally use. So it's a minor issue.
