### ISSUE TITLE
Some characters seem to be missing in the font

### ISSUE THREAD

**Issue by morray** [osmandapp/Osmand#1812]
Looking at http://www.openstreetmap.org/#map=19/25.04733/121.51444 in osmand, one sees that several characters seem to be missing. E.g. the name of the park are just substitutes, on the bus stations there are also misses. See screen shot.

Seen on a Nexus 5 with Android 6

![osmand](https://cloud.githubusercontent.com/assets/1404645/10563498/b6d92dfe-758c-11e5-9206-2fe76949589a.png)

**Comment by vshcherb** [comment]
Thanks, this is a duplicate issue, we are working on it.
