### ISSUE TITLE
"Configure map" screen UI customization gets messed up

### ISSUE THREAD

**Issue by luxcalor** [osmandapp/OsmAnd#18120]
## Description
When dragging around Configure map screen's menu items in customization mode, the whole arrangement gets messed up and menu items start to move randomly around the menu or get freezed.
### How to reproduce
Drag the "map style" menu item near the "map source" item in another category, for example. Or Terrain items to the Map rendering category. The problem seems to be with moving items between categories. 
### Actual result
Menu items start to move around unpredictably between categories, some become unresponsive to interaction altogether. Only reset to default and app reboot help bring things back to order.
### Expected result
Arrange menu items in the order I prefer them to be in regardless of category.
**Environment**
OsmAnd Version: 4.5.10
Android/iOS version: A13
Device model: Xoaomi Redmi Note 10 Pro

**Comment by Velomeloman** [comment]
Related #17839. Already fixed.

**Comment by DmitryAlexei** [comment]
Probably regression after https://github.com/osmandapp/OsmAnd/issues/17839?

**Comment by DmitryAlexei** [comment]
Fix will be available in 4.6 release. You can also try beta or nightly build to see if it works for you (https://osmand.net/docs/versions/nightly_versions)
