### ISSUE TITLE
Points for city names is missing on zoom level 5

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#18137]
<table style="width:100%">
  <tr>
    <th colspan=2>Zoom level: 5</th>
  </tr>
  <tr>
    <th>iOS</th>
    <th>Android</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/e3f54bae-44fb-48cc-a833-fba6925c972d"  width="240" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/074f29aa-a5aa-47d4-a35a-548e832c98b3"  width="240" height="auto"/> </td>
  </tr>
  <tr>
    <th colspan=2>Zoom level: 6</th>
  </tr>
  <tr>
    <th>iOS</th>
    <th>Android</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/00c38c8a-58e5-4dc6-97d0-457c863a2f72"  width="240" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/8d3ee78b-ab5b-4d6a-b6d1-244712a2d295"  width="240" height="auto"/> </td>
  </tr>
</table>

**Comment by xmd5a2** [comment]
Fixed in this commit but only for default style. Topo will be fixed after confirmation of correction in default style.
https://github.com/osmandapp/OsmAnd-resources/commit/805c02dafaa0b64126a2f71bc60ce8bb7c0db500
