### ISSUE TITLE
Android Auto `My Places` not shown properly

### ISSUE THREAD

**Issue by gena01** [osmandapp/OsmAnd#18132]
## Description
There are several display issues with My Places on Android Auto:

1. Hidden favorite folders are still synced and shown in the UI.
2. For some active folders not all places are shown. In one case it shows only 1 favorite instead of 5 saved.
### How to reproduce
Create several folders with favorites. Hide (select not to show on the map) at least one.
Connect to Android Auto.
Wait for favorites to sync.
Click on Favorites. You will see all of the folders including hidden.
Select one of shown folders and check that all favorites are shown.

### Actual result
1. Hidden folders are still shown
2. Some favorites are missing in Android Auto UI
### Expected result

**Environment**
OsmAnd Version:OsmAnd~ 4.6.0#729m, Released: 2023-09-05
Android/iOS version: Android 10
Device model: LG G7

**Comment by dmpr0** [comment]
Hi! 
Hidden status for Favorites folder means, that it wouldn't be visible on the map.

**Comment by DmitryAlexei** [comment]
@gena01 We show only 12 items pro favorite folder (or according to limit set by android auto itself). Recently added entries displayed first.

**Comment by DmitryAlexei** [comment]
Also see https://osmand.net/docs/user/navigation/auto-car/#destination-points

**Comment by dmpr0** [comment]
@gena01 
Hi! Could you please provide screenshots and log file from Menu – Help – Help improve OsmAnd – Send logcat log.
