### ISSUE TITLE
The zoom level from which live updates are displayed

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#18133]
## Description
Regional maps begin to be displayed at zoom level 9.  At the same time, live updates are applied only from zoom level 13.  I would like them to also change from level 9 zoom.  In the video below you can see that the piece of forest that was added to the live update appears from zoom level 13.
Video in telegram:
https://t.me/ruosmand/136448

**Environment**
OsmAnd Version: OsmAnd~ 4.6.0#738m, Дата выпуска: 2023-09-08
Android version: 13
Device model: poco f3

**Comment by vshcherb** [comment]
Tehcnically not possible due to road simplification, we will need to provide full map on daily basis and not a diff
