### ISSUE TITLE
multipolygon rendering problems

### ISSUE THREAD

**Issue by RicoZ-OSM** [osmandapp/Osmand#1814]
recently updated the maps of Bavaria and the mp https://www.openstreetmap.org/relation/1765193 is no longer rendered. 

It was rendered in the map version of Aug 27, not rendered in version of Oct 14th, same app version. Not the first time this mp causes trouble.

Was there any relevant change in OsmAnd map generation? I am also investigating to see what changed with the MP.

One thing that comes in my mind is that it crosses the border many times, possibly something went wrong here?

**Comment by GabrielSebastianMoise** [comment]
Maybe one of the segments in poligon does not have all info, role=outer !

2015-10-18 16:02 GMT+03:00 RicoZ-OSM <notifications@github.com>:

> recently updated the maps of Bavaria and the mp
> https://www.openstreetmap.org/relation/1765193 is no longer rendered.
>
> It was rendered in the map version of Aug 27, not rendered in version of
> Oct 14th, same app version. Not the first time this mp causes trouble.
>
> Was there any relevant change in OsmAnd map generation? I am also
> investigating to see what changed with the MP.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osmandapp/Osmand/issues/1814>.
>



-- 
Toate cele bune !
*------------------------*
Gabriel Sebastian  Moise
Administrator Local - Departament Tehnic
*------------------------------------------------------*
NextGen Communications S.R.L. - Campina

Mobil NextGen  : 076 111 65 59
Mobil Personal : 0726 311 957

Adresa Postala: Strada Grivitei, Nr.63, Campina, Romania !
*------------------------------------------------------*

**Comment by RicoZ-OSM** [comment]
@Gabriel: can't find anything, it also seems to pass all validation tests that I am aware. Possibly a border-cutoff issue?

**Comment by vshcherb** [comment]
Looks weird, OsmAnd skips all incorrect multipolygons, I can't really say now if it is incorrect or it is MapCreator issue.

**Comment by RicoZ-OSM** [comment]
See #2464 for follow up.

**Comment by vshcherb** [comment]
The multipolygon is incomplete (missing inner https://www.openstreetmap.org/way/129837758#map=12/47.5317/11.5538) in source map http://builder.osmand.net/osm-extract/germany_bayern_europe/germany_bayern_europe.pbf

**Comment by vshcherb** [comment]
Fixed, added --complex-ways to osmconvert. Tested locally but full verification is needed, just rescheduled osm-extract job and next one should be obf generated from http://builder.osmand.net/osm-extract/germany_bayern_europe/germany_bayern_europe.pbf
