### ISSUE TITLE
"I/O Error: Old file can't be deleted" on Android 13, Sony Xperia 5 III

### ISSUE THREAD

**Issue by ian727** [osmandapp/OsmAnd#18140]
Hello community,

I recently bumped into this issue - I can't seem to download any maps that I at some point apparently already downloaded. I will get the message "I/O Error: Old file can't be deleted" after the download has finished. I already tried un- and re-installing OSMAnd, but that did not help. I vaguely remember receiving a message about some internal/external storage changes within OSMAnd, and I assume it could be related to that. However I really don't know much about Android as a system and would greatly appreciate any help.

I am running Android 13 on a Sony Xperia 5 III. Please let me know if you need any additional info.

Thanks!

**Comment by scaidermern** [comment]
Is your OsmAnd configured for internal storage or external storage? You can check at Settings / OsmAnd settings / Data storage folder. If you are using external storage, maybe your SD card is broken

**Comment by ian727** [comment]
![Screenshot_20230912-111905](https://github.com/osmandapp/OsmAnd/assets/66421150/dabdc30c-0844-499e-b38a-a92de2825295)

Here's a screenshot of the settings. As you can see, "External memory 2" is selected; that's indeed my SD-Card. However it works fine for music and other stuff, so I highly doubt that it is broken. It is interesting that the phone's internal memory is listed twice here, as "internal memory" and as "external memory 1". Furthermore, there is something called "shared memory" which is not accessible anymore, telling me to "migrate" files. However I have no idea what this exactly means, when I select a folder I just get another error message. Also: While writing this (on my PC), I left my phone in the OSMAnd settings, and now it won't even turn on anymore. It seems like something is significantly wrong with the App, I have never experienced this kind of behaviour with another app. 

Is there a way to completely get rid of the OSMAnd app & all it's folders and files? I'd like to try a completely fresh start.

**Comment by scaidermern** [comment]
> As you can see, "External memory 2" is selected; that's indeed my SD-Card. However it works fine for music and other stuff, so I highly doubt that it is broken.

Maybe it isn't, maybe it is. This is not a good a good indicator. OsmAnd maps are quite large, requiring significantly more SD card operations to read and write. A single bit flip will be sufficient to have negative effects while using OsmAnd. This isn't necessarily true for music files.

Maybe you have a different SD card you can try. For a simple test, a small one will be sufficient. Or test with internal storage instead, just to compare it against your external storage.

> Is there a way to completely get rid of the OSMAnd app & all it's folders and files? I'd like to try a completely fresh start.

Not sure. I think uninstalling OsmAnd will lead to some files remaining in OsmAnd's directory (the one from your screenshot). You may have to use a file manager to remove those. Also, OsmAnd has a auto-backup feature which will restore some files on reinstall. You can disable it at Settings / OsmAnd settings / Auto-backup.

In case you don't want to loose your OsmAnd settings, favorites etc. make a backup first before uninstalling (Settings / Export to file).

**Comment by ian727** [comment]
Long story short: My SD card is out of writing cycles. That means it is working completely fine with regards to the data stored on it, but I can't make any changes to the files & folder structure.
