### ISSUE TITLE
Car routing avoid whole way if ways ends with motocar=no

### ISSUE THREAD

**Issue by TheSnoozer** [osmandapp/OsmAnd#18144]
# 🐞 routing report
Hello OsmAnd, thanks for the great app. Quite some time ago I observed the following misguided route.

### Routing engine

- [X] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

OsmAnd Car, avoid Toll Roads

### Start and end points

https://osmand.net/map/?start=43.200896,6.673017&end=43.201040,6.674000&type=osrm&profile=car#20/43.20105/6.67351

Please also note that any other starting point seems to reproduce the issue

### Actual route
![photo_2023-09-12_20-29-03](https://github.com/osmandapp/OsmAnd/assets/6849390/0656c8c0-ce69-4920-95e8-7d886a8d0dbd)

![photo_2023-09-12_20-29-08](https://github.com/osmandapp/OsmAnd/assets/6849390/5535df28-9ca3-4f79-9f9b-281f3befcb5d)

### Expected route

https://osmand.net/map/?start=43.200896,6.673017&end=43.201040,6.674000&type=osrm&profile=car#20/43.20105/6.67351

![image](https://github.com/osmandapp/OsmAnd/assets/6849390/cb6f5413-0731-4eb5-ad5a-51bdbb46b009)

### Is this a regression?

Not sure

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>
Device : RE513CL1
Brand : realme
Model : RMX3241
Product : RMX3241EEA
Build : RMX3241_11_F.07
Version : 13
App Version : OsmAnd+
Apk Version : 4.5.10 4510
</code></pre>

**Device and Android/iOS version:**

**Maps used (online or offline):**

- [X] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**
Maps last updated on 01 Sep 2023

**Comment by TheSnoozer** [comment]
Maybe (but just maybe) related to https://github.com/osmandapp/OsmAnd/issues/18071, since in this routing the car attempts to use a route that is only accessible to pedestrians.

**Comment by DmitryAlexei** [comment]
- route **OK** https://test.osmand.net/map/?start=43.200921,6.672081&end=43.200941,6.673776&type=osmand&profile=car#18/43.20068/6.67343
- route **not OK** https://test.osmand.net/map/?start=43.200921,6.672081&end=43.200964,6.674039&type=osmand&profile=car#18/43.20068/6.67343
So probably this way, tagged **motocar=no** https://www.openstreetmap.org/way/27109832 is the cause of the issue (it has one common point with main route https://www.openstreetmap.org/way/27109833)

OsmAnd~ 4.6.0#750m, released: 2023-09-12

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/8f003cb1-2ff9-4d80-b773-5f1df887d41b"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/d7fe3981-03ab-486a-8cea-a80c8aaba76d"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by xmd5a2** [comment]
Already fixed 
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/db4ee874-599c-4968-9b85-11279380cb39)

**Comment by zipav** [comment]
OsmAnd Nightly 4.6.0#939m, released: 2023-10-30

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/515d2ee7-aade-45b8-9308-145cf7b24a12"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/2b98bfa8-4597-4df8-8ca0-7428dd522822"  width="300" height="auto"/> </td>
  </tr>
</table>
