### ISSUE TITLE
Create tests for Rendering Text

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#18143]
Create tests for issues closed this year / cases from messages:
- Text on street not visible - 5 cases 
- Long streets consisted of different segments
- Long street (zoom 19-20)
- Too many icons on intermediate zoom 16.5
- Symbol size scaled too much - 3D (possible to test?)

**Comment by vshcherb** [comment]
- [ ] https://github.com/osmandapp/OsmAnd-iOS/issues/2480
- [ ] https://github.com/osmandapp/OsmAnd/issues/16004
- [ ] https://github.com/osmandapp/OsmAnd/issues/16045
- [ ] https://github.com/osmandapp/OsmAnd/issues/16700
- [ ] https://github.com/osmandapp/OsmAnd/issues/16543
- [ ] https://github.com/osmandapp/OsmAnd/issues/17282
- [ ] https://github.com/osmandapp/OsmAnd/issues/17157
- [ ] https://github.com/osmandapp/OsmAnd/issues/14784
- [ ] https://github.com/osmandapp/OsmAnd/issues/17193
- [ ] https://github.com/osmandapp/OsmAnd-Issues/issues/1588
- [ ] https://github.com/osmandapp/OsmAnd/issues/15240
- [ ] https://github.com/osmandapp/OsmAnd/issues/17104
- [ ] https://github.com/osmandapp/OsmAnd/issues/16881
- [ ] https://github.com/osmandapp/OsmAnd/issues/17432
- [ ] https://github.com/osmandapp/OsmAnd/issues/17413
- [ ] https://github.com/osmandapp/OsmAnd/issues/17470
- [ ] https://github.com/osmandapp/OsmAnd-Issues/issues/1574
- [ ] https://github.com/osmandapp/OsmAnd-Issues/issues/2114
- [ ] https://github.com/osmandapp/OsmAnd/issues/17769
- [ ] https://github.com/osmandapp/OsmAnd/issues/17269
- [ ] https://github.com/osmandapp/OsmAnd/issues/16656
- [ ] https://github.com/osmandapp/OsmAnd-Issues/issues/1250
- [ ] https://github.com/osmandapp/OsmAnd/issues/15818
- [ ] https://github.com/osmandapp/OsmAnd/issues/16617

**Comment by xmd5a2** [comment]
Small part of terrain tile for test https://github.com/osmandapp/OsmAnd/issues/16881:
[N41E041-crop.zip](https://github.com/osmandapp/OsmAnd/files/13214418/N41E041-crop.zip)
