### ISSUE TITLE
More or less every way (open AND closed) are poorly drawn/rendered

### ISSUE THREAD

**Issue by NLBRT** [osmandapp/OsmAnd#18150]
## Description
I assume it was previously discussed in Issue #9821. However, it's FAR TERRIBLE in my case.

I'm attaching the screenshots of the actual shapes as seen on iD first, followed by the OsmAnd Renders, in a respective manner.

**iD:**

![image](https://github.com/osmandapp/OsmAnd/assets/93070290/70ae8699-affe-4da0-8e57-68c4de4d618f)
![image](https://github.com/osmandapp/OsmAnd/assets/93070290/b1d5b1a7-27ef-412e-9540-ab7767bed48b)
![image](https://github.com/osmandapp/OsmAnd/assets/93070290/9b439d86-2ff3-4e48-8d8e-31eb6d32292e)

**OsmAnd:**

![image](https://github.com/osmandapp/OsmAnd/assets/93070290/5bd14960-d971-4994-90d0-2e7191cba81f)
![image](https://github.com/osmandapp/OsmAnd/assets/93070290/0b47857b-5fde-4fc4-8d28-deeb2c02b720)
![image](https://github.com/osmandapp/OsmAnd/assets/93070290/d09feffa-7621-49ec-a0e4-48b38d713fd6)

### How to reproduce
Download India/West Bengal and head over to the city of Jalpaiguri, specifically [The Municipality](https://www.openstreetmap.org/way/1203988369), [this building](https://www.openstreetmap.org/way/1188225572), or even the intersections @ [Kadamtala More](https://www.openstreetmap.org/way/1204132598) and [Thana More](https://www.openstreetmap.org/way/1207374550).

### Expected result

**Environment**
OsmAnd Version: 4.5.10
Android/iOS version: 12
Device model: Samsung A21s (SM-A217F/DS)

**Comment by vshcherb** [comment]
This circle is 5 m precision which is too small , we don't support such level of detalisation cause our points are aligned to the grid of +- 1m
![image](https://github.com/osmandapp/OsmAnd/assets/1042025/4816e1d3-d9c6-4633-90a5-d18cdcf4a5ae)
