### ISSUE TITLE
Binding the widget "Average speed" to the track recording for the correct calculation

### ISSUE THREAD

**Issue by snooppr** [osmandapp/OsmAnd#18152]
### Description of the problem

I’ll start right away with the problem: due to the specific calculation of the average speed by the widget, I have to double record the gpx track in another application in order to track the correct average speed in real time.

How the average speed widget works (calculates) is not described in the help.  It shows complete nonsense regardless of its settings (consider the average speed from 15s or 60min).

An example of what average speed is and how a sports tracker (third party alternative applications) calculates it.  You start recording the route and see the average speed; if you pause/autopause, the calculation is suspended and does not underestimate the average speed

An example of using the average speed function for an athlete/tourist.  A man set a goal to cover a route of 100 km in 24 hours.  on foot.  He knows that in order to complete the day, his average speed must be at least v=S/t=4.17 km/h.  Using OsmAnd it is impossible to achieve the goal: the widget will show absolutely anything: jumping numbers, for example 3 km/h, after a while 5 km/h, after another time 0.3 km/h, but not the average speed (due to breaks/rest, I tested  the widget in the field is terrible, that is, planning the average speed in OsmAnd is simply impossible at the moment, which is very important in a sports topic/at competitions).

<img src="https://github.com/osmandapp/OsmAnd/assets/61022210/8c25c29b-0148-403c-bc1e-e46887f29c04"  width="300" height="auto"/> 

Recorded in parallel with Sports Tracker and correctly calculated average and displayed average speed/drop to of 3.7 km/h throughout the entire route, that is, I already knew, based on my average speed, that I would not be able to complete the 100 km route in 24 hours.  And OsmAnd “lied”... (OsmAnd showed jumps).

### A proposal on how to fix the average speed widget, bring it to the standards, as in any other tracker.

Add a checkbox to the “average speed” widget setting: calculate the average speed of the track recording.
<img src="https://github.com/osmandapp/OsmAnd/assets/61022210/1402087d-958e-4743-8125-1d4aad55f728"  width="300" height="auto"/> 

Now the widget will calculate the average speed only if and only if the user has launched the “track recording/Rec widget”.  If the user pauses while recording a track, the average speed should not be updated on the widget.

<img src="https://github.com/osmandapp/OsmAnd/assets/61022210/97fd42e8-ea34-4d49-9126-f613654e0713"  width="300" height="auto"/> 

In other words, add the ability to link an average speed widget to a track recording.  The problem is relevant for athletes and tourists, and at the moment the average speed widget only misleads them.

**Rationale for correction/improvement**: Users of third-party applications (athletes) will be able to refuse sports trackers, for example, Strava/Sports Tracker, etc., where applications correctly calculate and display average speed in real time.  and go to OsmAnd.  Increasing the audience of OsmAnd users.
I myself didn’t open an issue for a long time because I’m happy with recording a track and real average speed monitoring with a third-party application in parallel with OsmAnd, but the overhead costs are on the gadget’s battery.  But if it can be fixed, that would be damn great.

**upd**: Sorry, I was in a hurry, it turns out similar requests already exist https://github.com/osmandapp/OsmAnd/issues/18139

**Comment by scaidermern** [comment]
It should be possible to display a reasonable average speed without any active track recording.

**Comment by snooppr** [comment]
My proposal does not cover the current state of affairs, but only expands: check the box, write the average speed only according to the recording, uncheck the box, everything is as it is (if this is meant by “reasonable”).

**Comment by vshcherb** [comment]
If you want to see average moving speed, you could have it visible in recording track or in dialog of track recording.

This widget is made independent and it's purposely not calculating "average moving speed " (average of all values > 0), it calculates average speed over time, so it's much more reasonable value. Also it calculates average speed as "Sum of distance" / "Sum of time"

**Comment by snooppr** [comment]
>  or in dialog of track recording.

Thank you! It works, in addition, I found an even more convenient way to inform about the average speed when recording: through the widget: “duration” -> review.

**Comment by AndyB69** [comment]
> Thank you! It works, in addition, I found an even more convenient way to inform about the average speed when recording: through the widget: “duration” -> review.

@snooppr Can you give more info on this? I'm not sure what you mean here. Duration is one of the Trip Recording widgets, I have that widget showing. But what do mean by "Review"? Thx

**Comment by AndyB69** [comment]
> If you want to see average moving speed, you could have it visible in recording track or in dialog of track recording.
> 
 @vshcherb I'm not clear what you mean here - are you saying average speed **since the start of the currently recording track** IS possible somehow, or are you saying that could be a future development (i.e. my request in #18139). Thx.

**Comment by DmitryAlexei** [comment]
@AndyB69 
Information you are looking for can be found in Context menu of currently recording track (tap on trip recording widget > track tab > overview or speed screens), for more information see https://osmand.net/docs/user/plugins/trip-recording/#overview-screen

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/c90edbab-c2f5-4cc8-bc94-c5697676848a"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by AndyB69** [comment]
> @AndyB69 Average speed you are looking for can be found in Context menu of currently recording track (tap on trip recording widget > track tab > overview or speed screens)...

Yes, ok, thanks. I do know about that option, but I'm looking for this info as an on-screen widget, so no clicks needed to see it.  Thx.

**Comment by snooppr** [comment]
> > Thank you! It works, in addition, I found an even more convenient way to inform about the average speed when recording: through the widget: “duration” -> review.
> 
> @snooppr Can you give more info on this? I'm not sure what you mean here. Duration is one of the Trip Recording widgets, I have that widget showing. But what do mean by "Review"? Thx

![2023-09-16-](https://github.com/osmandapp/OsmAnd/assets/61022210/0a641ec4-0077-4732-8f95-752830ff1215)
This widget displays the time relative to the track recording.  By clicking on it -> rev, you will get the real average speed.

**Comment by AndyB69** [comment]
Hi. Interesting. For me, when I am recording a track, that same widget
(Trip recording *Duration*) does nothing at all when I click on it.. While
my finger is on actually it, it's background goes a light grey colour, but
no other info is displayed, for long or short tap of it.

Regards,
Andrew
