### ISSUE TITLE
Improper routing in Istanbul, Turkey

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#1815]
The app leads through the whole junction instead of turning right.
![screenshot_2015-08-22-11-07-19](https://cloud.githubusercontent.com/assets/12711814/10580710/7e95db12-7687-11e5-8449-47946d729cb3.png)
![screenshot_2015-08-22-11-07-40](https://cloud.githubusercontent.com/assets/12711814/10580711/7e99341a-7687-11e5-950b-cb6ea354f44e.png)

**Comment by sanderd17** [comment]
It looks to me like you're forcing that route with your waypoint.

It's not possible to take the right turn towards the 34-13, as there's a bridge over the link that leads to your destination. I guess normally the route would take the link going to the primary road directly, but as your waypoint seems to be closer to the motorway, it takes the motorway instead and needs to do a detour around the entire crossing.

In any case, this doesn't looks like an OsmAnd Issue, at most it's an OSM issue, and then you can fix it on the map directly: https://www.openstreetmap.org/#map=17/40.98138/29.09714

**Comment by maraf24** [comment]
OSM data problem. Fixed.

**Comment by vshcherb** [comment]
Thanks
