### ISSUE TITLE
Lane guidance has difficulty suggesting to go straight ahead

### ISSUE THREAD

**Issue by TheSnoozer** [osmandapp/OsmAnd#18158]
## Description

Lane guidance has difficulty suggesting to go straight ahead

### How to reproduce

Start: 48.58836°N, 7.75573°E
End: 48.59019°N, 7.74927°E

https://osmand.net/map/?start=48.588429,7.755468&end=48.590190,7.749270&type=osrm&profile=car#18/48.58895/7.75273

### Actual result
No lane in lane guidance is marked yellow

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/6849390/8c7ef8bc-960a-433e-85ef-22970ab1f514"  width="300" height="auto"/> </td>
  </tr>
</table>

### Expected result
straight ahead should be yellow in lane guidance

**Environment**
```
Device : RE513CL1
Brand : realme
Model : RMX3241
Product : RMX3241EEA
Build : RMX3241_11_F.07
Version : 13
App Version : OsmAnd+
Apk Version : 4.5.10 4510
```
Maps from 01 Sept 2023

**Comment by yuriiurshuliak** [comment]
When inputting the provided coordinates into the simulation and activating the navigation, the "Lanes" widget fails to show the current road's lane and does not illuminate the lane for straight traffic during active navigation.

OsmAnd~ 4.6.0#770m, released: 2023-09-16

https://github.com/osmandapp/OsmAnd/assets/127092082/bfe884b5-4357-4739-942f-845a6a1aae38

**Comment by vshcherb** [comment]
- [MUTE] Go ahead (TL|C|C,TR) onto Avenue des Vosges and go 0.2 km. 
- https://osmand.net/map/?start=48.588429,7.755468&finish=48.590589,7.751155&profile=car#16/48.5890/7.7515 - also this is not correct it's not a TR
- REGRESSION since 2023

**Comment by yuriiurshuliak** [comment]
The bug has been fixed. The "Lanes" widget shows the current lane of the road.

OsmAnd~ 4.7.0#1969m, released: 2024-04-03

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/5b1a2a94-cb86-40dc-a85d-8f3fc3bb8e71"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/a4b735db-2120-4e8b-963d-2f8e32b2660e"  width="300" height="auto"/> </th>
  </tr>
</table>
