### ISSUE TITLE
Osmand Version 4.5.10, Android 13. The sensor device is a Magene S3+, talking Bluetooth to the phone and ANT+ to my watch.

### ISSUE THREAD

**Issue by sjsbikes** [osmandapp/OsmAnd#18161]
Would love to get this fixed! (see attached video of speed widget as explained by @johnnychicago )

https://user-images.githubusercontent.com/145097691/268200436-0e851dbe-926d-4710-837f-c88c42fc90cc.mp4

              Osmand Version 4.5.10, Android 13. The sensor device is a Magene S3+, talking Bluetooth to the phone and ANT+ to my watch. 

Other bit I've been noticing is that the sensor seems to update regularly to 0 - maybe once a second I get a 0 value shown in Osmand, inbetween one or multiple updates of the big float value. Maybe some smoothening is supposed to happen to the data coming from the sensor.

Thanks

_Originally posted by @johnnychicago in https://github.com/osmandapp/OsmAnd/issues/17923#issuecomment-1678683769_

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/17923
