### ISSUE TITLE
sqlitedb satellite images doesn't work anymore

### ISSUE THREAD

**Issue by summoner001** [osmandapp/OsmAnd#18160]
## Description
If I select Fömi Ortofoto 2000 satellite images to underlayer or overlayer it doesnt work anymore.

Until now it has worked.

### How to reproduce
Create new online tiles in sqlitedb file. This satellite only working in Hungary.

name: Fomi Ortofoto 2000
zoom levels 1-17
url: http://e.tile.openstreetmap.hu/ortofoto2000/{0}/{1}/{2}.jpg
expiry time: 1440

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/11212632/0dd3f490-8fda-4683-bfc5-8fd79f173c8e"  width="300" height="auto"/> </td>
  </tr>
</table>

### Actual result
nothing

### Expected result
Load Satellite images to underlayer

**Environment**
OsmAnd Version: v4.6.0
Android/iOS version: Android 9
Device model: Cubot Quest
Rendering Engine: V1-V2

**Comment by zipav** [comment]
No possibility to check if the issue is displayed, as the site that contained the online map picture no longer exists.

**Comment by summoner001** [comment]
Here it is: http://e.tile.openstreetmap.hu/ortofoto2000/

Chrome redirect to https but this is only http and the url is working in JOSM editor

**Comment by DmitryAlexei** [comment]
@summoner001 JOSM uses link  http://e.tile.openstreetmap.hu/ortofoto-2007-2010/{zoom}/{x}/{y}.jpg

**Comment by summoner001** [comment]
Yes I know from the different formatting but the main url don't changed.
In Osmand until now has been worked.
Working in josm.

**Comment by summoner001** [comment]
Ahh my mistake. Sorry.

I change the link

http://e.tile.openstreetmap.hu/ortofoto-2007-2010/{0}/{1}/{2}.jpg

To this link. And working for now with https.

https://e.tile.openstreetmap.hu/ortofoto-2007-2010/{0}/{1}/{2}.jpg
