### ISSUE TITLE
Ski map plugin: option to use different colour schemes for ski trail difficulty ratings

### ISSUE THREAD

**Issue by DFyson** [osmandapp/Osmand#1816]
Ski trail difficulty rating conventions depend on the region (https://en.wikipedia.org/wiki/Piste#Ratings). Currently it only uses the European convention. I would love to see an option to change it. OSM wiki has a colour equivalence chart: http://wiki.openstreetmap.org/wiki/Piste_Maps#Difficulty

**Comment by xmd5a2** [comment]
Fixed. No need to switch anything. All will be rendered according to this table https://wiki.openstreetmap.org/wiki/Piste_Maps#Difficulty (with new maps and new nightlies).
