### ISSUE TITLE
New Quick-Action option: Switch Terrain Colour Scheme

### ISSUE THREAD

**Issue by AndyB69** [osmandapp/OsmAnd#18169]
### Describe the idea (required)

There exists a 'quick actions' icon you can add to the map screen to Show/Hide Terrain, but this simply turns on/off the entire terrain layer, whereas what I want to do is easily simply switch between Hillshade and Slope, _within_ the terrain layer. 

Reason being that I use this functionality when ski touring - by default I have hillshade on but when I'm concerned about avalanche risk I want to switch to slope to check the risk, but then go back to hillshade again. 

Currently you have to do that by going into the Menu > Configure Map > Terrain... menu...  etc twice. A bit of a hassle.

### Tell us about the expected behaviour (required)

- A new quick action button called (perhaps) "Switch terrain scheme", or "Switch terrain hillshade/slope" could be  provided, which can be selected for display in the on-screen quick-actions widget.
- When chosen in the quick-actions on-screen widget, it would toggle the terrain layer between Slope and Hillshade.

### Tell us about alternatives you've considered (required)

The only option I can see is the current long-winded approach of doing the same via the full menu path: 
By default I have map in Hillshade, so to see Slope then go back to Hillshade, I need to do: 
1. Menu > Configure Map > Terrain > Colour Scheme > then choose Slope > back to map.
2. Menu > Configure Map > Terrain > Colour Scheme > then choose Hillshade > back to map.
But this is clearly long-winded.

**Comment by dmpr0** [comment]
Already implemented in 4.8
