### ISSUE TITLE
Gaps up to several minutes during recording with Version 4.5.10

### ISSUE THREAD

**Issue by GuenterD** [osmandapp/OsmAnd#18165]
### Describe the bug (required)

recording tracks with Samsung Galaxy S22 ultra and version 4.5.10 results in a .gpx with lot of gaps up to several minutes. Before, with 4.4.7 it worked fine. After downgrade to 4.4.7 again working fine.

### Describe how the bug can be reproduced (required)

record track with samsung galayx S22 ultra and version 4.5.10.

### Describe the actual result (required)

recording tracks with Samsung Galaxy S22 ultra and version 4.5.10 results in a .gpx with lot of gaps up to several minutes. Gaps occur e.g. with 5 seconds recording interval like in attached example:
[2023-09-15_Test-5sV4.5.10.gpx.txt](https://github.com/osmandapp/OsmAnd/files/12620160/2023-09-15_Test-5sV4.5.10.gpx.txt) first 19 points are good. next point with 39 seconds gap, next point good, next point with 2:39 minutes gap ...  Test with different recording intervalls: Continuous recording, 1 second, 2 seconds... The issue is independent form recording interval. Test with other mobiles Nokia, Xiaomi (not Android 13): version 4.5.10 working fine.
After go back to osmand version 4.4.7. recording with Galaxy S22 ultra again working fine. (Only osmand version changed)
Checked troubelshooting, Track recording points: No Power saving active.

### Describe the expected result (required)

No gaps, recording working like in previous Version 4.4.7.

### Your Environment (required)

```
OsmAnd Version: 4.5.10
Android/iOS version: 13 latest patches installed.
Device model: Galaxy S22 Ultra   SM-S908B/DX
Crash-Logs: ?
```

**Comment by DmitryAlexei** [comment]
@GuenterD Have you tried disabling the *Minimum accuracy* option?
for more information see https://osmand.net/docs/user/plugins/trip-recording#recording-settings

**Comment by GuenterD** [comment]
Now i repeated test with Minimum accuracy option disabled. Issue is same.

**Comment by DmitryAlexei** [comment]
@GuenterD In my case, adding OsmAnd to *Never sleeping apps* (Your Samsung Device settings > Battery and device care > Battery > Background usage limits > Never sleeping apps) makes the situation much better for long trips.

**Comment by GuenterD** [comment]
Add OSMAND to "Never sleeping apps" did  not help. Issue is same.
Also turn off "Put unused apps to sleep" did not help. Issue is same.
Keep screen active helped. No gaps. (But this is not a solution)
In file produced with OSMAND added to "Never sleeping apps" are 5 gaps 
[2023-09-18_Standby-off.gpx.txt](https://github.com/osmandapp/OsmAnd/files/12651472/2023-09-18_Standby-off.gpx.txt)
Does corresponding part of screenshot: Einstellungen -> Sicherheit und Datenschutz -> Datenschutz -> Standort  --> Nutzungsverlauf: 
![Screenshot_20230918_161656_Permission usage](https://github.com/osmandapp/OsmAnd/assets/131299046/e6fa39d4-9497-41b9-b55d-dee0b8267d2d)
help analyses?

**Comment by DmitryAlexei** [comment]
[2023-09-16_19-16_Sat.gpx.txt](https://github.com/osmandapp/OsmAnd/files/12664179/2023-09-16_19-16_Sat.gpx.txt)
- Samsung device (note 20 ultra)
- Trip recording in background (screen is off)
- OsmAnd added to *Never sleeping apps*

In the beginning of the track everything goes ok, points recorded every 5 seconds. At the end (after about 2 hours of recording), 
there are gaps several minutes long (see .gpx attached):
The points below go one after the other:

1. <time>2023-09-16T18:10:29Z</time>
<time>2023-09-16T18:12:33Z</time>

2. <time>2023-09-16T18:07:28Z</time>
<time>2023-09-16T18:09:51Z</time>

3. <time>2023-09-16T18:02:43Z</time>
<time>2023-09-16T18:04:58Z</time>
<time>2023-09-16T18:07:18Z</time>

**Comment by blaueente** [comment]
maybe related to https://github.com/osmandapp/OsmAnd/issues/17287 ?

**Comment by DmitryAlexei** [comment]
@GuenterD as a workaround, try to change location source from Google to Android API (https://osmand.net/docs/user/personal/global-settings#location-source).

I tested recording several long tracks (2-3 hours) in the background with Android API as location source, and it works fine for me (resulting tracks are without gaps)

**Comment by GuenterD** [comment]
Track recording with location source Android API works fine. With location source Android API cannot produce a gap.

**Comment by eksplorator** [comment]
Same issue with track recording interruption after updating to these versions:

- Mi 11 Lite 5G
- MIUI Global 14.0.8 (TKIEUXM)
- Android 13 TKQ1.220829.002

All settings are correct. Changing the location source from Google Play Services to Android API didn't help either.

Is there anything else that can be done?

**Comment by DmitryAlexei** [comment]
First of all, in Android system settings you need to turn off the power saving mode for OsmAnd, so that the system does not automatically put it to sleep

**Comment by eksplorator** [comment]
Thank you for your instant reply.
Yes, this setting is already enabled: Power saving does not limit background app.

Maybe something else can be set?

**Comment by DmitryAlexei** [comment]
@eksplorator as a guess, Your system may also limit gps services in background

**Comment by eksplorator** [comment]
@DmitryAlexei I see, so the only solution seems to be downgrading to a lower system version?

**Comment by dmpr0** [comment]
I have tested track recording using:
* Latest release version 4.6.13.
* Both: Android API and Google Play Services as location source
* App Battery usage was set to default **Optimised** with Allowing background usage
* Google Pixel 6A, Android 14
* Both track without gaps
