### ISSUE TITLE
Slow startup of the nightly comparing to release

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#18168]
I recently noticed that the nightly build of osmand runs very slowly (10-12 second's) compared to version 4.6.0 from google play or version 4.5.10 from fdroid (3 second's). 
I did a reset of the app and then uninstalled and reinstalled it. But the night build still takes a long time to start. I made several rollbacks, the last one to OsmAnd~ 4.5.0#35827m, release date: 2023-04-21, but the result is the same.
I suspect it's related to the phone model, based on a small poll in the telegram chat.
Below is a link to a video where I run the nightly build of the app first, and then the google play version.
https://t.me/ruosmand/136939

```
OsmAnd Version: OsmAnd~ 4.6.0#769m, дата выпуска: 2023-09-15
Android/iOS version: 13
Device model: poco f3 (xiaomi)
Crash-Logs: ?
```

**Comment by zipav** [comment]
OsmAnd Nightly 4.6.0#849m, released: 2023-10-09


https://github.com/osmandapp/OsmAnd/assets/123936521/a2544fda-c9d0-4db3-9ba7-83724780c3b1

**Comment by zipav** [comment]
OsmAnd 4.6.2, released: 2023-09-27

When compared to the release version, launching the release version is almost 5 seconds faster:


https://github.com/osmandapp/OsmAnd/assets/123936521/4e62f702-f602-4a97-85eb-70f91619d3cb

**Comment by vshcherb** [comment]
Not actually reproduced on my device probably it's related to tracks or not. Did you try latest beta release?

**Comment by Nine-Tailed** [comment]
> Not actually reproduced on my device probably it's related to tracks or not. Did you try latest beta release?
> 

I tried a clean installation of the nightly build, the first launch of Osmand without a map took 7 seconds.  Then I downloaded one map and Osmand began to load in about 10-11 seconds.  The version from the google play loads in 4 seconds.
Today I repeated the experiment with a clean install, nothing changed.

**Comment by vshcherb** [comment]
Release version might be precompiled cause they are installed from Google Play. 
However I tested 3 versions: nightly, plus, free and it looks like they start independently fast 5-6 seconds. So I can't confirm it, we need to have comparable log files to identify the issue.

**Comment by Nine-Tailed** [comment]
I can attach logcats after starting applications for nightly builds and free versions from Google Play.
![logcat_gplay.log.txt](https://github.com/osmandapp/OsmAnd/files/13057337/logcat_gplay.log.txt)

![logcat_nightly.log.txt](https://github.com/osmandapp/OsmAnd/files/13057336/logcat_nightly.log.txt)

**Comment by vshcherb** [comment]
Logs are identical (please attach again)
Nightly log - 15 seconds
```
10-20 20:28:06.795 16088 16088 I System.out: Time to start application 1687 ms. Should be less < 800 ms
10-20 20:28:06.919 16088 16088 I System.out: Time to init plugins 124 ms. Should be less < 800 ms
10-20 20:28:11.336 16088 16139 I System.out: Initialized INIT_RENDERERS in 4541 ms
10-20 20:28:12.501 16088 16088 I System.out: Initialized ROUTING_CONFIG_INITIALIZED in 1164 ms
10-20 20:28:14.521 16088 16139 I System.out: Initialized NATIVE_OPEN_GL_INITIALIZED in 2021 ms
10-20 20:28:14.911 16088 16139 I System.out: Initialized POI_TYPES_INITIALIZED in 390 ms
10-20 20:28:14.989 16088 16139 I System.out: Initialized ASSETS_COPIED in 78 ms
10-20 20:28:15.223 16088 16139 I System.out: Initialized MAPS_INITIALIZED in 233 ms
10-20 20:28:16.369 16088 16139 I System.out: Initialized NATIVE_INITIALIZED in 1147 ms
10-20 20:28:17.924 16088 16139 I System.out: Initialized FAVORITES_INITIALIZED in 1555 ms
10-20 20:28:18.487 16088 16139 I System.out: Initialized POI_FILTERS_INITIALIZED in 563 ms
10-20 20:28:20.996 16088 16139 I System.out: Initialized INDEX_REGION_BOUNDARIES in 2509 ms
10-20 20:28:21.340 16088 16139 I System.out: Initialized LOAD_GPX_TRACKS in 344 ms
10-20 20:28:21.343 16088 16139 I System.out: Initialized SAVE_GPX_TRACKS in 3 ms
10-20 20:28:21.343 16088 16139 I System.out: Initialized RESTORE_BACKUPS in 0 ms
```

**Comment by Nine-Tailed** [comment]
![logcat_nightly.log.txt](https://github.com/osmandapp/OsmAnd/files/13063661/logcat_nightly.log.txt)

![logcat_gplay.log.txt](https://github.com/osmandapp/OsmAnd/files/13063662/logcat_gplay.log.txt)

**Comment by vshcherb** [comment]
Google Play - 3 seconds
```
10-22 17:30:29.463  3999  3999 I System.out: Time to start application 953 ms. Should be less < 800 ms
10-22 17:30:29.525  3999  3999 I System.out: Time to init plugins 62 ms. Should be less < 800 ms
10-22 17:30:29.561  3999  4065 I System.out: Initialized INIT_RENDERERS in 98 ms
10-22 17:30:30.196  3999  3999 I System.out: Initialized ROUTING_CONFIG_INITIALIZED in 635 ms
10-22 17:30:31.370  3999  4065 I System.out: Initialized NATIVE_OPEN_GL_INITIALIZED in 1174 ms
10-22 17:30:31.388  3999  4065 I System.out: Initialized POI_TYPES_INITIALIZED in 17 ms
10-22 17:30:31.416  3999  4065 I System.out: Initialized ASSETS_COPIED in 29 ms
10-22 17:30:31.485  3999  4065 I System.out: Initialized MAPS_INITIALIZED in 69 ms
10-22 17:30:32.021  3999  4065 I System.out: Initialized NATIVE_INITIALIZED in 536 ms
10-22 17:30:32.155  3999  4065 I System.out: Initialized FAVORITES_INITIALIZED in 134 ms
10-22 17:30:32.201  3999  4065 I System.out: Initialized POI_FILTERS_INITIALIZED in 46 ms
10-22 17:30:32.920  3999  4065 I System.out: Initialized INDEX_REGION_BOUNDARIES in 719 ms
10-22 17:30:32.920  3999  4065 I System.out: Initialized LOAD_GPX_TRACKS in 0 ms
10-22 17:30:32.923  3999  4065 I System.out: Initialized SAVE_GPX_TRACKS in 3 ms
10-22 17:30:32.923  3999  4065 I System.out: Initialized RESTORE_BACKUPS in 0 ms
```

**Comment by vshcherb** [comment]
Well the answer pretty clear there is no JIT optimization on APK level https://source.android.com/docs/core/runtime/jit-compiler (it is done only once uploaded to google play).
INIT_RENDERERS is 10 times faster same as other parsers.

**Comment by vshcherb** [comment]
So unfortunately I think it will be waste of time to try to optimize "debug" level code when "runtime" works fine

**Comment by Nine-Tailed** [comment]
I'm not familiar with android architecture.  But why then are there no problems with builds from fdroid? And in general it’s strange that nightly builds show different speeds on different phones.

**Comment by vshcherb** [comment]
>  But why then are there no problems with builds from fdroid? And in general it’s strange that nightly builds show different speeds on different phones.
I can't answer the question, more like a question to Android developers

**Comment by vshcherb** [comment]
Slow startup nightly log:
```
10-22 17:29:52.340  3034  3034 I System.out: Time to start application 1732 ms. Should be less < 800 ms
10-22 17:29:52.497  3034  3034 I System.out: Time to init plugins 156 ms. Should be less < 800 ms
10-22 17:29:56.724  3034  3165 I System.out: Initialized INIT_RENDERERS in 4384 ms
10-22 17:29:57.718  3034  3034 I System.out: Initialized ROUTING_CONFIG_INITIALIZED in 994 ms
10-22 17:30:00.538  3034  3165 I System.out: Initialized NATIVE_OPEN_GL_INITIALIZED in 2820 ms
10-22 17:30:00.958  3034  3165 I System.out: Initialized POI_TYPES_INITIALIZED in 420 ms
10-22 17:30:00.995  3034  3165 I System.out: Initialized ASSETS_COPIED in 37 ms
10-22 17:30:01.267  3034  3165 I System.out: Initialized MAPS_INITIALIZED in 272 ms
10-22 17:30:02.592  3034  3165 I System.out: Initialized NATIVE_INITIALIZED in 1325 ms
10-22 17:30:04.706  3034  3165 I System.out: Initialized FAVORITES_INITIALIZED in 2114 ms
10-22 17:30:05.251  3034  3165 I System.out: Initialized POI_FILTERS_INITIALIZED in 545 ms
10-22 17:30:07.970  3034  3165 I System.out: Initialized INDEX_REGION_BOUNDARIES in 2719 ms
10-22 17:30:08.300  3034  3165 I System.out: Initialized LOAD_GPX_TRACKS in 330 ms
10-22 17:30:08.305  3034  3165 I System.out: Initialized SAVE_GPX_TRACKS in 5 ms
10-22 17:30:08.305  3034  3165 I System.out: Initialized RESTORE_BACKUPS in 0 ms
```

**Comment by vshcherb** [comment]
```
10-22 17:30:29.463  3999  3999 I System.out: Time to start application 953 ms. Should be less < 800 ms
10-22 17:30:29.525  3999  3999 I System.out: Time to init plugins 62 ms. Should be less < 800 ms
10-22 17:30:29.561  3999  4065 I System.out: Initialized INIT_RENDERERS in 98 ms
10-22 17:30:30.196  3999  3999 I System.out: Initialized ROUTING_CONFIG_INITIALIZED in 635 ms
10-22 17:30:31.370  3999  4065 I System.out: Initialized NATIVE_OPEN_GL_INITIALIZED in 1174 ms
10-22 17:30:31.388  3999  4065 I System.out: Initialized POI_TYPES_INITIALIZED in 17 ms
10-22 17:30:31.416  3999  4065 I System.out: Initialized ASSETS_COPIED in 29 ms
10-22 17:30:31.485  3999  4065 I System.out: Initialized MAPS_INITIALIZED in 69 ms
10-22 17:30:32.021  3999  4065 I System.out: Initialized NATIVE_INITIALIZED in 536 ms
10-22 17:30:32.155  3999  4065 I System.out: Initialized FAVORITES_INITIALIZED in 134 ms
10-22 17:30:32.201  3999  4065 I System.out: Initialized POI_FILTERS_INITIALIZED in 46 ms
10-22 17:30:32.920  3999  4065 I System.out: Initialized INDEX_REGION_BOUNDARIES in 719 ms
10-22 17:30:32.920  3999  4065 I System.out: Initialized LOAD_GPX_TRACKS in 0 ms
10-22 17:30:32.923  3999  4065 I System.out: Initialized SAVE_GPX_TRACKS in 3 ms
10-22 17:30:32.923  3999  4065 I System.out: Initialized RESTORE_BACKUPS in 0 ms
```

**Comment by vshcherb** [comment]
Nighlty starts 5x times slower on my devices 3s vs 15s and I didn't find any workaround yet :-( https://www.reddit.com/r/android_beta/comments/14yh35l/this_is_how_to_force_optimize_android_beta_or/ - so it becomes very inconvenient to use nighlty probably we will be forced to use public beta more often

**Comment by Nine-Tailed** [comment]
Good news, today's nightly build of Osmand~ 4.7.0#1765m is fast again.

**Comment by sonora** [comment]
@vshcherb Sorry for only just now discovering this thread: In my experience, there is zero performance difference between a release build and a debug build if only in build.gradle you specify this for the debug build (I get like 5  sec startup time with dozens of maps present):

![Screenshot_20240306-220335_Firefox](https://github.com/osmandapp/OsmAnd/assets/845735/fc171b05-579b-419e-90ce-d6b1368b4086)
