### ISSUE TITLE
Ski map plugin: Highlight ski hills when zoomed out.

### ISSUE THREAD

**Issue by DFyson** [osmandapp/Osmand#1817]
When zooming out in ski map mode the ski hills begin to look congested then finally disappear. Would be nice to highlight and label them so they can all be clearly seen when zoomed out to a large region.

**Comment by xmd5a2** [comment]
What do you mean by "ski hills"?

**Comment by jkufner** [comment]
He probably means a hill where a piste is located. (tag piste:type = yes)

**Comment by DFyson** [comment]
Yes, probably just the terminology we use here. More specifically it usually refers to a privately owned ski resort for downhill skiing or snowboarding with chair lifts, collection of runs (usually groomed), snow park, usually some buildings, rentals, etc. Example Whistler Blackcomb, Mont Tremblant Resort.
Looking at OSM wiki, it appears to be areas with landuse:winter_sports (http://wiki.openstreetmap.org/wiki/Piste_Maps#Areas)

**Comment by xmd5a2** [comment]
Added winter_sports to rendering at 11-13 zooms. But not every ski resort is tagged as winter_sport. Also leisure=ski_resort tag exists, and relations with site=piste which includes only pistes themselves and hence is very hard to process. Maybe somebody wants to add landuse=winter_sports to such ski resorts?
