### ISSUE TITLE
[BUG] "North is up" isn't fixed

### ISSUE THREAD

**Issue by SergeyP2** [osmandapp/OsmAnd#18174]
### Describe the bug (required)

I have Map orientation = "North is up". I like it this way all the time, unless I will choose something else. Yet, as soon as I zoom in / out with two fingers, with high chance, the map starts to rotate. I then press Compass icon, to restore direction to the North to the top. Yet this is VERY annoying.

### Describe how the bug can be reproduced (required)

(in description)

### Describe the actual result (required)

Map is rotated.

### Describe the expected result (required)

Map should stay in the mode I've choosen in Settings: North is up.

### Your Environment (required)

Version 4.5.10

**Comment by vshcherb** [comment]
Duplicate

**Comment by SergeyP2** [comment]
Version 4.6.9

I waited for several months for the version that will fix this ANNOYING issue, and it is still here. How this can be???
