### ISSUE TITLE
Weird Zoom bug

### ISSUE THREAD

**Issue by DavidRLTG** [osmandapp/OsmAnd#18175]
### Describe the bug (required)

Basically, I was driving with OsmAnd put on driving mode with a route set, and the zoom was waaaay too close, with the route's arrows looking a bit.. weird
The app said the zoom is set to 100%, but it obviously wasn't
And if I zoomed in more, the map would just flat out disappear.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/87834635/b5fcdaeb-1c81-46c0-a3f2-bd6c31c95e50"  width="300" height="auto"/> </td>
  </tr>
</table>

### Describe how the bug can be reproduced (required)

Simply just set a route, and change to driving mode, and just drive.

### Describe the actual result (required)

Weird looking map, way too zoomed in

### Describe the expected result (required)

The zoom from the old versions of the app that qorked much better and didn't look weird

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.5.10 (From F-Droid)
Android/iOS version: 13
Device model:M2012K11AG (Poco F3)
Crash-Logs: Unavailable
```

**Comment by ManDay** [comment]
Dupe of https://github.com/osmandapp/OsmAnd/issues/17763 and related.

**Comment by DmitryAlexei** [comment]
@DavidRLTG If your issue reproduces only with 3d Relief option (menu > configure map > 3d Relief) enabled, so yes, it's duplicate.

**Comment by DavidRLTG** [comment]
Yes, Disabling 3D Relief has fixed my problem, thank you.
Although, gotta mention, and with no offense to the OsmAnd devs-
Every update fixed a major bug, and added another, for me at least
..I wonder when that cycle will end-
