### ISSUE TITLE
Wrong average speed data in recorded tracks 

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd#18170]
### Describe the bug (required)

[2023-08-23_13-42_Wed.gpx.txt](https://github.com/osmandapp/OsmAnd/files/12640388/2023-08-23_13-42_Wed.gpx.txt)

The track's context menu does not display the average speed correctly (average speed exceeds the maximum speed). This mostly happens with tracks recorded in the walking profile. The probable cause is an incorrect calculation of time in motion.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/d7e399f1-05db-434a-808d-c00aea422b9a"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/80506cf3-e1c6-4864-a634-f9ca41d8ae2c"  width="300" height="auto"/> </td>
  </tr>
</table>

### Describe how the bug can be reproduced (required)

- record a track while walking in the park (menu > trip recording > start) 
- open this track and see if average speed exceeds maximum speed

### Describe the actual result (required)

Average speed exceeds maximum speed, time in motion is too short

### Describe the expected result (required)

average speed is calculated correctly

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd~ 4.6.0#764m, released: 2023-09-15

Android/iOS version: 13
Device model: samsung
Crash-Logs: ?
```

**Comment by cepprice** [comment]
> Will the fix work with new tracks?

I believe so 

> Can we test it on new tracks?

Yes

**Comment by DmitryAlexei** [comment]
Yesterday tested with the latest nightly build. Average speed doesn't exceed maximum speed now.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/61f76429-598f-4ce2-83cb-e40806be7eed"  width="300" height="auto"/> </td>
  </tr>
</table>
