### ISSUE TITLE
Screen lock: GPX route not activating screen/directions

### ISSUE THREAD

**Issue by ekliw** [osmandapp/OsmAnd#18186]
### Describe the bug (required)

I use Screen lock to follow imported GPX routes.
I use the timeout after wakeup of 5 seconds
The screen goes on with route directions

Recently this is not working properly. It works for some time (5 minutes) and then it is not giving directions and the screen keeps off. When I put the screen on again (finger on sensor), the screen goes on and immediately I get a voice/screen direction. When I switch it off again, it works fine, screen goes 5 seconds on with directions, but after some time it stops again. 

Also when I keep the screen on and the phone system turns it off (after 15 seconds as my setting), it has the same issue and stops working until I trigger the screen on again.

I saw there was in august an update, but I only noticed in September as I started using it again for the first time after the update.

So now I am continuously on my bike (35/40 km/h) pushing the button, paying attention to the App and thus taking huge riska in my cycling. 

### Describe how the bug can be reproduced (required)

Not sure. It happens every time when I start a new trip. The GPX routes are generated from different Apps (Komoot, Garmin, FIetsersbond)

### Describe the actual result (required)

No directions given, screen/voice is quiet

### Describe the expected result (required)

Wirking as it used to do

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.5.19
Android/iOS version: Android 12
Device model: Samsung S10e
Crash-Logs: ?
```

**Comment by mikehgentry** [comment]
Have you made sure OsmAnd is exempt from your phone's power saving attempts?

https://osmand.net/docs/user/troubleshooting/track-recording-issues#recorded-tracks-have-gaps

**Comment by DmitryAlexei** [comment]
Similar to https://github.com/osmandapp/OsmAnd/issues/18082

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#855m, released: 2023-10-10
Can be reproduced both with gpx navigation and navigation by route
Steps to reproduce:
- in Android settings set 15 seconds *Screen timeout* 
- In OsmAnd settings set *Turn screen on* by *Navigation instructions* (Menu > Settings > your driving profile > General settings > Screen control > Navigation instructions)
- activate navigation
- wait until screen switches off (or push the power button)
- wait until voice instruction is voiced

Actual result:
- you can hear voice instruction
- display remains dark, map isn't shown (see video, sound on)

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/6b2267d8-b962-4799-be27-f8c9fb619d72"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/osmandapp/OsmAnd/assets/116079541/ef61a7d7-3c4f-44ac-8d17-a241ba3f681b"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by ekliw** [comment]
Sorry for the late reaction; was not able to test/use OSMAND+ until yesterday. The problem is the Apps setting on battery. It used to be **UN**limited on my Android phone. However, with the August update it seems to have changed to limited causing my  problem. I have changed it back to UNlimited (as it was before the update) and now it works fine again.

**Comment by scaidermern** [comment]
One more reason to implement #14958.

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. I tried setting Screen timeout to 15 seconds, enabling Navigation instructions and setting Time after wake up to 5 seconds. When voice prompts are heard, the screen turns on for 5 seconds and then turns off.

OsmAnd~ 4.7.0#1497m, released: 2024-02-02

https://github.com/osmandapp/OsmAnd/assets/127092082/3e9838a3-ace0-4fec-bb9f-90b8e89bc8f3

**Comment by vshcherb** [comment]
Issue could be OS/ device specific
