### ISSUE TITLE
Separate file with nautical depth points for "Great Lakes"

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#18185]
# Description

OsmAnd has a separate file with nautical depth contours for "Great Lakes", but if user also wants to get nautical depth points, he needs to download "Northern Hemisphere points" file, which is  413 MB file and 800 MB after unzipping.
* Provide separate "Nautical points for Great Lakes".

**Comment by xmd5a2** [comment]
Depth points are now separated from contours

**Comment by DmitryAlexei** [comment]
- on Android and iOS devices *Great Lakes points* map can be updated again after it was downloaded (OsmAnd is offering to re-download this map)
https://github.com/osmandapp/OsmAnd/assets/116079541/47560135-0453-45a4-9f0b-a40772c7652c

**Comment by vshcherb** [comment]
Todo
-  [ ] https://github.com/osmandapp/OsmAnd/issues/18536
