### ISSUE TITLE
Gray arrows on the current track

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#18189]
After changing the interface of screens with tracks, it often turns out that the current track is not visible, I probably disable it accidentally, which is annoying.
And against this background I came across a bug that if you start recording the current track when it is not visible, and then after some time to turn on, then after turning on the arrows are gray.
The bug is not always reproduced.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/12549744/97f4f654-6334-43fd-b490-bdb19407c74f"  width="300" height="auto"/> </td>
  </tr>
</table>

```
OsmAnd~ 4.6.0#777m, Дата выпуска: 2023-09-18
```

**Comment by DmitryAlexei** [comment]
@Nine-Tailed Please provide your profile settings (menu > settings > pedestrian profile > export profile)

**Comment by Nine-Tailed** [comment]
@![Osmand.zip](https://github.com/osmandapp/OsmAnd/files/12675156/Osmand.zip)

**Comment by zipav** [comment]
OsmAnd Nightly 4.6.0#804m, released: 2023-09-25

Tested twice, if Trip recording is paused, click Show on map, then Appearance and turn Direction arrows on, arrows are displayed in red.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/5b84d6c1-6043-44cf-b023-f4c190c57cc8"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
I think you need to change current recording track color as it probably somehow assigned transparent color, so it will reset and problem will be solved
