### ISSUE TITLE
Enabled 3D relief produces hillshade although terrain is disabled

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#18184]
### Describe the bug (required)

Terrain off, 3D Relief off | Terrain on, 3D Relief off | Terrain on, 3D Relief on | Terrain on, 3D Relief on
:---:|:---:|:---:|:---:
![01_terrain_off_relief_off](https://github.com/osmandapp/OsmAnd/assets/1040784/d1c6646f-b183-496e-8925-a15ed5672024) |  ![02_terrain_on_relief_off](https://github.com/osmandapp/OsmAnd/assets/1040784/46e05c11-0388-4a77-9a3f-1f3c68cde5f7) | ![03_terrain_off_relief_on](https://github.com/osmandapp/OsmAnd/assets/1040784/9206bf08-6b40-4e6a-bdab-123e15a196ed) | ![04_terrain_on_relief_on](https://github.com/osmandapp/OsmAnd/assets/1040784/deb1a41d-2e8a-49dc-b441-41d3bbb5b0ba)
→ No hillshade | → Light hillshade| → Dark hillshade | → Light hillshade

### Describe how the bug can be reproduced (required)

See above

### Describe the actual result (required)

* Hillshade although Terrain setting is disabled
* Different hillshade intensity depending on combination of Terrain and 3D Relief settings

### Describe the expected result (required)

* No Hillshade when Terrain setting is disabled
* Same hillshade independent of 3D Relief setting

### Your Environment (required)

```
OsmAnd Version: 4.6.1 (same behavior with 4.5.10)
Android: 10
Device model: Samsung S9
```

**Comment by vshcherb** [comment]
Hillshade should be always visible with 3D on (it's possible to switch off in dev settings) - but it must be on to see 3D. the option to avoid darker hillshade is good, it's hard to fix and avoid confusion of changing settings by user. 

So I think we're not going to fix it for now as it doesn't give any value

**Comment by scaidermern** [comment]
This is all very confusing, especially the missing explanation.

**Comment by Nine-Tailed** [comment]
I was wondering the same thing. I think earlier there was a 3d mode without hillshading.
Also on my screens you can see that hiilshades is more rough, with some stripes by compare with 3d relief.
https://github.com/osmandapp/OsmAnd/issues/17848
