### ISSUE TITLE
Buttons without icons

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#18181]
Problem with displaying zoom and quick action buttons on the filter and track appearance customization screen.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/12549744/86017a13-83bf-45f9-a896-6522808c4f15"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/12549744/ca7b0468-a9f3-4a47-9d85-a0e6d6d03b32"  width="300" height="auto"/> </td>
  </tr>
</table>

OsmAnd~ 4.6.0#777m, Дата выпуска: 2023-09-18

**Comment by Nine-Tailed** [comment]
![Screenshot_2023-09-18-22-10-00-659_net.osmand.plus.jpg](https://github.com/osmandapp/OsmAnd/assets/12549744/35b6ad3f-9a69-4b2c-b64d-730d9791777b)

**Comment by scaidermern** [comment]
Same problem for me when opening the track styling menu.

**Comment by vshcherb** [comment]
Todo:
- Buttons should be visible
- Please list all screens in comment to test

**Comment by dmpr0** [comment]
Buttons is back
