### ISSUE TITLE
Crashing on a 300km gpx route

### ISSUE THREAD

**Issue by erlandl4g** [osmandapp/OsmAnd#18191]
### Describe the bug (required)

300 km long gpx track saved from Garmin. When I have loaded it and started navigating along the track - Osmand would hangup and close every 3-5 minutes for the first 30-60 km. Later problem seem to have stopped but I used it very little so cannot confirm if it is just the start of the track a problem.

### Describe how the bug can be reproduced (required)

Load the gpx file attached and simulate navigation (with routing) along the track.

### Describe the actual result (required)

It was closing or sometimes just hanging up the app while navigating along the track (without much deviation)

### Describe the expected result (required)

It should do recalculation just for the part of the track to save some memory if memory is an issue with default app settings (I am using latest app version)

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.5.10
Android/iOS version: Android 13
Device model: Galaxy S22
Crash-Logs: ? Where they are stored???
```

[SuTomu300.zip](https://github.com/osmandapp/OsmAnd/files/12670490/SuTomu300.zip)

**Comment by DmitryAlexei** [comment]
@erlandl4g what profile did you use for navigation? Have you attached the track to roads? (see https://osmand.net/docs/user/navigation/setup/gpx-navigation#attach-to-roads)

Providing crash logs will speed up reproduction of your issue (see https://osmand.net/docs/user/troubleshooting/crash-logs#crash-and-logcat-logs)

**Comment by DmitryAlexei** [comment]
After about 10 minutes in simulation mode, I had no crashes with this track.

**Comment by erlandl4g** [comment]
Where would crash logs be stored on my phone if they were produced? Are they created by default? As I was using it 11 days ago.

Crashing started about 4 - 5 km from start up to 30 km. I was going at 15-20 km/h speed

**Comment by DmitryAlexei** [comment]
@erlandl4g crash logs can be found and send as described in this article https://osmand.net/docs/user/troubleshooting/crash-logs#crash-and-logcat-logs or https://osmand.net/docs/user/troubleshooting/crash-logs/#send-tombstone-files-android-only. They are produced automatically.
It is important to know in which profile you experienced crashes, because some roads may not be accessible for cars or for cycling.
Also specify, have you used *Attach to the roads* option?

**Comment by erlandl4g** [comment]
Hopefully it includes crashes from beginning of September Device : r0sBrand : samsungModel : SM-S901BProduct : r0sxeeaBuild : TP1A.220624.014.S901BXXS6CWH6Version : 13App Version : OsmAndApk Version : 4.5.10 4510

**Comment by erlandl4g** [comment]
Actually I have opened the log file attached above and I see it only has records of today. Does it save older crash logs somewhere else or is it made just to save current log and everything else is overwritten (which would be a bad decision).

**Comment by DmitryAlexei** [comment]
@erlandl4g please see if crash logs files available (menu > help > swipe to the bottom > send crash log)
or use instruction from this article https://osmand.net/docs/user/troubleshooting/crash-logs#send-tombstone-files-android-only

**Comment by DmitryAlexei** [comment]
Please add your gpx file and specify in which profile do you use it for routing

**Comment by erlandl4g** [comment]
> Please add your gpx file and specify in what profile do you use it for routing

I have used default OsmAnd profile - Type: Cycling

GPX file is attached to the [first comment](https://github.com/osmandapp/OsmAnd/issues/18191#issue-1904414058)

**Comment by erlandl4g** [comment]
Created bug report but there is nothing created on September 9 when I was having Osmand turning itself off/hanging up.

<img width="513" alt="image" src="https://github.com/osmandapp/OsmAnd/assets/76598482/07ddbeea-0470-4355-9602-034aa104f02c">

**Comment by zipav** [comment]
OsmAnd Nightly 4.6.0#835m, released: 2023-10-03

Tested twice within a day on Realistic Simulation mode and Fast Preview mode, the app does not crash, only slowly (about 2-3 minutes) loading the navigation route.

**Comment by erlandl4g** [comment]
The map would load quickly and the track tracking with routing would start quickly (within seconds) for me when I was driving there. The black app screen would come up just few minutes later.

Very possible that it was simply going Blank (black screen) at some point after starting (About 2-5 minutes) as it may have been doing routing recalculation.

**Comment by vshcherb** [comment]
We have some gpx fixes related to out of memory, I think it's a main reason here. So with 4.6 situation should be better and hopefully works, let's wait 4.6 beta soon and 4.6 release in a month period
