### ISSUE TITLE
The map freezes when the device screen is turned off – Android Auto

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#18194]
### Describe the bug (required)

When I switch off the screen of my phone. Location for OsmAnd on Android Auto lost.

### Describe how the bug can be reproduced (required)

Start navigation for AA and switch off the telephone screen.

### Describe the actual result (required)

The location was lost at once for AA with a switched-off telephone screen. 

### Describe the expected result (required)

The location must work for AA with a switched-off telephone screen. (as it works for other navigation apps on AA)

### Your Environment (required)

```
Brand : samsung
Model : SM-S901B
Product : r0sxeea
Build : TP1A.220624.014.S901BXXS6CWH6
Version : 13
App Version : OsmAnd
Apk Version : 4.6.1 4601
```
[logcat (3).log.zip](https://github.com/osmandapp/OsmAnd/files/12675770/logcat.3.log.zip)

**Comment by EugeneZmeuk** [comment]
Track recording works without any issues and a track recording line is drawn on the map. Voice prompts of current navigation work fine too (in time). But My location doesn't work (not moving) when the OsmAnd app is collapsed on the telephone or the device screen is switched off.

**Comment by EugeneZmeuk** [comment]
Problem is when use: "Map orientation > Movement direction"

**Comment by juanantoniomosquera** [comment]
Same problem. With map orientation North works fine.
