### ISSUE TITLE
Maps/tiles disappear when navigating

### ISSUE THREAD

**Issue by slackline** [osmandapp/Osmand#1819]
I've encountered this two or three times now when using navigation that after about five minutes the maps showing the route as I travel completely disappear to leave a dark grey screen.  Animations/annotations such as which turn to take next are still shown but there is no display of the surrounding maps/landscape.

This is using OSMAnd+ 2.1.1 under Android 5.1 on a Samsung GT-I9505G (Galaxy S4).

If theres any more information I can provide please let me know.

**Comment by vshcherb** [comment]
Duplicate #1685
