### ISSUE TITLE
Lane guidance has difficulties to suggest the exit lane

### ISSUE THREAD

**Issue by TheSnoozer** [osmandapp/OsmAnd#18196]
### Describe the bug (required)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/6849390/5d9d39c9-3d88-49dd-b5b2-e5aabfb00cee"  width="300" height="auto"/> </td>
  </tr>
</table>

### Describe how the bug can be reproduced (required)

start 43.42265° N, 5.37205° E
end 43.42041° N, 5.36771° E

https://osmand.net/map/?start=43.422650,5.372050&end=43.420410,5.367710&type=osrm&profile=car#17/43.42100/5.36840

### Describe the actual result (required)

All lanes in the lane guidance are grayed out (=Lane guidance has difficulties to suggest the exit lane)

### Describe the expected result (required)

IMHO at least one lane should be highlighted in yellow (=the exit lane)

### Your Environment (required)

```
Device : RE513CL1
Brand : realme
Model : RMX3241
Product : RMX3241EEA
Build : RMX3241_11_F.07
Version : 13
App Version : OsmAnd+
Apk Version : 4.5.10 4510
```

**Comment by DmitryAlexei** [comment]
Probably the same https://github.com/osmandapp/OsmAnd/issues/18158

**Comment by yuriiurshuliak** [comment]
When entering the given coordinates into the simulation and initiating navigation, the "Lanes" widget doesn't display the current lane on the road and doesn't light up the turning lane for active navigation.

You can see the specific road section in question by following this link:
[Link to Map](https://osmand.net/map/?start=43.422650,5.372050&end=43.420410,5.367710&type=osrm&profile=car#17/43.42100/5.36840)

Expected result: The corresponding lane should be highlighted in yellow.

OsmAnd~ 4.6.0#806m, released: 2023-09-25

https://github.com/osmandapp/OsmAnd/assets/127092082/ff7496e0-e936-4a71-93e9-7c512f75fd66

**Comment by kevinp2** [comment]
I find the new exit symbol in 4.5 confusing and misleading.  Here is a picture from this exit:

![image](https://github.com/osmandapp/OsmAnd/assets/609677/fe7796dc-e280-4f41-90ba-ab7bb128166f)

This symbol implies to me that there are three forward lanes on the motorway and the right-most lane forks and exits.

But I can testify and you can examine the exit here:
https://www.openstreetmap.org/node/83461895

There are only two forward lanes, and the exit is a straightforward exit to the right, not a fork and then one lane goes to the right.

In my opinion, the exit lane should be shown as below.

![image](https://github.com/osmandapp/OsmAnd/assets/609677/ce329ef3-ca8c-497d-9fbe-a36615c5a652)

Should I submit a new issue for this, or is this current issue the right place to address this?

**Comment by TheSnoozer** [comment]
Just my 5 cents: My initial complaint was that the lane guidance wasn't suggesting any exit lane. Notice that in my initial screenshot the lane guidance also suggested a similar "forked" exit. As per https://www.openstreetmap.org/node/1921673020 this would be a similar case as yours, however your case at least suggests a exit lane. Hence this "feels" different and thus I would personally create a new issue and link the two. In case they are fixed at the same time it's easy to close them in one go since they are linked together.

**Comment by vshcherb** [comment]
Current version should display Go ahead (TSLL|TSLL|+C,TSLL) and go 0.3 km. 
Needs to be retested

**Comment by yuriiurshuliak** [comment]
Currently, the "Lanes" widget highlights the current lanes and indicates the right turn.

OsmAnd~ 4.7.0#1864m, released: 2024-03-19

https://github.com/osmandapp/OsmAnd/assets/127092082/8be732dd-f3f0-4907-80dc-15938516b78e
