### ISSUE TITLE
maxspeed enforcements not notified (due to live updates?)

### ISSUE THREAD

**Issue by Talkless** [osmandapp/OsmAnd#18216]
### Description

OSMAnd did not produce notification for this speed camera with two `enforcement` relations in both ways:

https://www.openstreetmap.org/node/11125696474#map=18/55.92385/23.30048

It's rather new, so it could be that I do see it on the OsmAnd map only because of Live Updates. Maybe it will start to "work" after I download new Lithuanian map?

### Steps to reproduce

(probably impossible :) ) drive through https://www.openstreetmap.org/node/11125696474#map=18/55.92385/23.30048.

### Actual result

No speed camera notification provided.

### Expected result

OsmAnd should provide notification for speed camera `11125696474`.

### Your Environment (required)

```
OsmAnd Version: 4.5.8
Android/iOS version: Android 11 (Waydroid lineage_waydroid_arm64_userdebug 11).
Device model: Volla Phone X
Crash-Logs: N/A
```

**Comment by vshcherb** [comment]
The change was done https://www.openstreetmap.org/api/0.6/relation/16217644 - we can check the map data of timestamp="2023-08-18T17:25:46Z" (2023-08-18) if we still have it around .

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#871m, released: 2023-10-13 **Not reproduced, works as expected**
Tried to reproduce with following settings:
- Speed camera notification is turned on in Navigation > Settings > Sound settings > Speed cameras
- Created route https://osmand.net/map?start=55.922760%2C23.297434&end=55.924328%2C23.300945&mode=car#17/55.925043/23.299188
- Simulation speed is set to 90 km/h
- Started simulation

Actual result: OsmAnd warns *Speed camera ahead* when driving this route

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#871m, released: 2023-10-13 
I do not have *Live updates* for Lithuania map, all works as expected without it.
I've recorded video with notification (turn sound on). 
You have probably turned on *Announce when exceeded* option?

https://github.com/osmandapp/OsmAnd/assets/116079541/d1c3177d-a48c-44a4-95d2-cc1ea82d0381

**Comment by Talkless** [comment]
> I do not have Live updates for Lithuania map, all works as expected without it.

Yes, it works using "full" update, that's the point.

Let me parathrase:
1. All OLD speed cameras worked.
2. I've added new camera, which was downloaded by OsmAnd via Live Update, because month haven't passed (or whatever map update interval is).
3. Newly downloaded camera via Live Updates was visible, but "inactive" while navigating.
4. Recently downloaded "full" Lithanian man update - it started working.

If you want to reproduce the issue, you have to:
1. Create NEW speed camera in your nearby location, with two `enforcement` relations (in both directions).
2. Download Live Update on the next day
3. Drive through that new camera you've recently created.

**Comment by vshcherb** [comment]
Yes I think it's related to the issue https://github.com/osmandapp/OsmAnd/issues/18153. We have an issue that sometimes restart is required (not update!) and after 1-2 restarts it starts working, still investigating but this issue is present for a year in new opengl rendering

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/18153
