### ISSUE TITLE
Not routing wants closer maps

### ISSUE THREAD

**Issue by Noitarud** [osmandapp/OsmAnd#18228]
### Describe the routing engine used (required)

- [ x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Describe your routing Profile (required)

By Road, avoid toll

### Describe your start and end points (required)

Adelaide to darwin

### Describe the actual route (required)

Fails, wants maps

### Describe the expected route (required)

The destination and roads present on the country but the program wants better maps.
I only wanted a general idea of route (distance, maybe time clue) only not to have to go download more.

### Describe what Maps you used (online or offline) (required)

- [ ] Offline maps offered within the OsmAnd app for download. 
- [ ] Online (tile / raster) maps 

Have detailed Quensland, Northern territory and newsouth Wales. Adelaide in Victoria, mapper has the city and roads going to it but program refuses to use them. Gives message:
v4.4.7 "some offline maps needed for this route are missing"
v3.9.10 "could not calculate route, ending point too far from nearest road"

V4 allows option "directions from" when selecting a place, so chose that for Adelaide, and chose Darwin for destination.

### Your Environment (required)

Device : TB-X505F
Brand : Lenovo
Model : Lenovo TB-X505F
Product : TB-X505F
Build : TB-X505F_S001142_210804_ROW
Version : 10
App Version : OsmAnd~

### Anything else? (optional)
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/98794719/f9ce0d2e-2c6d-4a22-a4fb-9f53dcc34771"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by scaidermern** [comment]
Well, without a map OsmAnd can't calculate a route. Either download the missing region or use an online router. You can also configure an online router in OsmAnd, see https://osmand.net/docs/user/navigation/routing/online-routing/

**Comment by DmitryAlexei** [comment]
@Noitarud As written above Osmand works completely offline unless otherwise specified (online routing). See https://osmand.net/docs/user/navigation/setup/route-navigation#no-maps
