### ISSUE TITLE
Externe Eingabegeräte Tastatur

### ISSUE THREAD

**Issue by Biker729** [osmandapp/OsmAnd#18225]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑
zoomen im Stillstand funktioniert bei jedem kurzen Druck auf die Taste + zoomt die Karten größer
und bei jedem kurzen Druck auf die Taste - zoomt die Karte wieder kleiner.

Aber beim fahren passiert bei einem kurzen Druck auf die + oder - Taste kein zoom.

Bei einem längeren Druck auf auf die + oder - Taste springt der zoom auf kurz auf „zoom max“ oder „zoom min“
und sofort wieder zurück auf Normal.

Das zoomen im Stillstand funktioniert aber bei fahren funktioniert der zoom nicht.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by DmitryAlexei** [comment]
@Biker729 please disable *Auto zoom map* option in *Map during navigation* settings (see https://osmand.net/docs/user/navigation/guidance/map-during-navigation#map-during-navigation) and try again.

**Comment by Biker729** [comment]
Danke für die Info!

Bei keine automatische springt die Anzeige schon mal nicht zurück.

Im Stillstand kann ich zoomen mit kurz drücken auf die Taste + oder -

Sobald schneller als Schrittgeschindigkeit passiert mit kurz kurzem kein
zoomen.

Nur bei einem längeren Druck auf die zoom Taste + oder - verstellt sich de
große der Karte.



Am Di., 26. Sept. 2023 um 12:16 Uhr schrieb DmitryAlexei <
***@***.***>:

**Comment by Biker729** [comment]
Geschlossen #18225 als abgeschlossen.

*?*

Am Di., 26. Sept. 2023 um 14:22 Uhr schrieb DmitryAlexei <
***@***.***>:

**Comment by Biker729** [comment]
Beim Motorradfahren kann ich nicht mal kurz mit zwei Finger auf das Display Tippen.?

**Comment by Biker729** [comment]
Beim Motorradfahren kann ich nicht mal kurz mit zwei Fingern auf das
Display tippen.?
Deshalb benütze ich eine externe Tastatur und da funktioniert das Zoomen
nicht richtig.

Am Di., 26. Sept. 2023 um 14:26 Uhr schrieb Roland Stengel <
***@***.***>:
