### ISSUE TITLE
Crash using waypoints

### ISSUE THREAD

**Issue by Noitarud** [osmandapp/OsmAnd#18227]
### Description

Seems to have forgotten selected track.

### Steps to reproduce

Australia.
Create waypoint (to "currently recording track")
Go to "open track"
Delete waypoints
Add waypoint. This causes it to leave Australia to 0°S 0°W
Press Cancel
Press Options. Crash.

### Actual result

Crash

### Expected result

Able to add, etc.

### Your Environment (required)

OsmAnd Version: 3.9.10
Android/iOS version: 10
Device model: lenovo tb x505f
Crash-Logs: 

Log has:

Device : TB-X505F
Brand : Lenovo
Model : Lenovo TB-X505F
Product : TB-X505F
Build : TB-X505F_S001142_210804_ROW
Version : 10
App Version : OsmAnd~
Apk Version : 3.9.10 400

**Comment by Noitarud** [comment]
Updated.
Did not crash, but knowing problem (it forgot), I added new waypoint. Then I select waypoint, press "open track" and nothing happens.

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#866m, released: 2023-10-12 Cannot reproduce this issue with provided instructions. 
@Noitarud Please update your OsmAnd to the latest version. Best of all try beta from Google play and see if your issue still persist.  If yes, please add short video or screenshots where bug is present.

**Comment by Noitarud** [comment]
Recorded on last stated version (though this time I note fdroid recommends v4.5.8 I updated to 10 today and video still valid)

Video actions:
On selected point add waypoint, through prompts
View selected track, see points
Delete points
Add point is pressed, redirects view away from Australia
Move back to Australia (this version does annoying rotation effect, crash version okay)
Finally press Add, through prompts.
Note no marker shown on map or list, and text "currently recording track" is missing
Clear selected position
Add waypoint, through prompts
Currently selected track, see points.
Last two added are shown.

https://github.com/osmandapp/OsmAnd/assets/98794719/a37931d1-c019-423a-b01e-aab801cf389e

**Comment by zipav** [comment]
OsmAnd Nightly 4.6.0#924m, released: 2023-10-26

I have tried several times with Waypoints on different versions of OsmAnd Nightly, however nothing is causing the crash or bug you have shown.
Tried repeating the steps from your video, perhaps some additional steps are needed? Then please describe one by one. 
Perhaps you can give us the video in a higher resolution, uncompressed? 

https://github.com/osmandapp/OsmAnd/assets/123936521/ce2189cf-1558-4b82-92a1-170b21469726
