### ISSUE TITLE
"Elevation: map center" widget doesn't appear until I minimise the app and get back to it

### ISSUE THREAD

**Issue by plicplocplicploc** [osmandapp/OsmAnd#18232]
### Description

The "Elevation: map center" widget doesn't appear when the app has been freshly opened. For it to actually be displayed, I need to leave OsmAnd then get back to it (by going to the home screen, turning screen off then back on).

### Steps to reproduce

Enable the "Elevation: map center" widget (hamburger > Configure screen > Right panel > add "Elevation: map center").
If I exit the app (by swiping up in the opened app list), the widget won't appear on next app load, until I switch to the home screen momentarily.

### Actual result

The widget is not displayed in some circumstances.

### Expected result

The widget should always be displayed if I have selected it.

### Your Environment (required)

OsmAnd Version: 4.5.10 ~ (f-droid)
Android/iOS version: LOS 20 / Android 13
Device model: Pixel 6a
Crash-Logs: n/a
```

**Comment by nazar-kutz** [comment]
@plicplocplicploc, Please let me know if this bug occurs every time or only from time to time under certain conditions? And if possible, attach a video with the reproduction of this bug.

**Comment by plicplocplicploc** [comment]
Thanks for looking at this!
Here's a video: https://imgur.com/a/iNZvuYT
When the app is freshly opened, the widget doesn't show: not shown on display, not shown in the list of widgets.
When I go back to desktop then switch back to the app, the widget has reappeared on display and in the list of widgets.
I then exit the app by swiping up in the list of opened apps, and demo again: widget not shown when app is freshly opened, widget is shown after I've switched back to desktop and switched back to the app again.

**Comment by nazar-kutz** [comment]
Thanks for the quick reply!
I will try to find the cause of the bug and fix it.

**Comment by DmitryAlexei** [comment]
related https://github.com/osmandapp/OsmAnd/issues/18326

**Comment by dmpr0** [comment]
# Review 

<details>
    <summary>Screenshot</summary>

    <p>Detailed content goes here …</p>

</details>  

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/0a53800d-8d84-487d-8467-53659db02f88
"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/e616d3a8-ba4d-4fcb-ab0e-58ec1e76c3a7"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ]  Widget doesn't appear on Top Panel right after app start.
