### ISSUE TITLE
Zooming with external keyboard works only conditionally by pressing the key longer #18225

### ISSUE THREAD

**Issue by Biker729** [osmandapp/OsmAnd#18231]
**Translated**
The topic was already requested under #18225, but closed.

My system: OsmAnd+ v4.6.1 / Android 12 / External keyboard: BarButtons v3 (Bluetooth).

Zooming and panning the map on the display works fine with fingers.

Zooming works with the external keyboard without movement while stationary.
Each short press of the + button zooms the map larger and larger, and each short press of the - button zooms the map smaller and smaller.

Zooming does not work while moving faster than walking speed.
A short press on the + or - button does not zoom, only a long press on the + or - button zooms the map larger or smaller.

Automatic zoom is set to: "No automatic zoom".

So again briefly:
Without movement while standing still, zooming with OsmAnd works perfectly.
While driving, zooming with external keyboard works only conditionally by pressing the key longer.

<details>
    <summary> Original </summary>

Das Thema wurde schon unter #18225 angefragt, aber geschlossen.

Mein System: OsmAnd+ v4.6.1 / Android 12 / Externe Tastatur: BarButtons v3 (Bluetooth)

Zoomen und Verschieben der Karte auf dem Display funktioniert mit den Fingern gut.

Mit der externen Tastatur ohne Bewegung im Stillstand funktioniert das Zoomen.
Bei jedem kurzen Druck auf die + Taste zoomt die Karte immer größer und bei jedem kurzen Druck auf die - Taste zoomt die Karte immer kleiner.

Während der Fahrt größer als Schrittgeschwindigkeit funktioniert das Zoomen nicht.
Bei einem kurzen Druck auf die + oder - Taste funktioniert kein zoom, nur bei einem langen Druck auf die + oder - Taste wird die Karte größer oder kleiner.

Automatische Vergrößerung ist eingestellt auf: „Keine automatische Vergrößerung“.

Also nochmal kurz:
Ohne Bewegung im Stillstand funktioniert das Zoomen mit OsmAnd perfekt.
Während der Fahrt funktioniert das Zoomen mit externer Tastatur nur bedingt durch längeres drücken der Taste.

</details>

**Comment by DmitryAlexei** [comment]
@Biker729 
- It was not so clear in your first issue, that you use External keyboard for zooming. So, please, translate your issue into English, so everybody can understand it.
- What is your version of the app? Is your issue similar to https://github.com/osmandapp/OsmAnd/issues/17994? If so, it might have been fixed and will be available in 4.6. release.
- You can also try beta version and / or nightly build to see if this bugfix is working for you

**Comment by Biker729** [comment]
This topic was already requested under https://github.com/osmandapp/OsmAnd/issues/18225, but closed.

My system: OsmAnd+ v4.6.1 / Android 12 / External keyboard: BarButtons v3 (Bluetooth).

Zooming and panning the map on the display works well with fingers.

Zooming works with the external keyboard without movement while stationary.
Each short press of the + buttons zooms the map larger and larger, and each short press of the - zooms the map smaller and smaller.

Zooming does not work while moving faster than walking speed.
A short press on the + or - button does not zoom, only a long press on the + or - button zooms the map larger or smaller.

Automatic zoom is set to: "No automatic zoom".

So again short:
Without movement at standstill, zooming with OsmAnd works perfectly.
While driving, zooming with external keyboard works only conditionally by pressing the key longer.

**Comment by DmitryAlexei** [comment]
@Biker729 errors occur in navigation mode? (when navigation is set) or when you try to scroll the map while mooving without navigation?

the issue may be related to https://github.com/osmandapp/OsmAnd/issues/18193

**Comment by dmpr0** [comment]
I can't reproduce the issues 

<table style="width:100%">
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/9922a143-7c7c-4dac-bd85-9b1994ea3174"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Biker729** [comment]
Wurde bei dem Video der Zoom mit der externen Tastatur gemacht?
Wie sind die genauen Einstellungen?
OsmAnd Version, Android ?

Dmytro Prodchenko ***@***.***> schrieb am Mi., 27. Sept.
2023, 11:09:

**Comment by Biker729** [comment]
Habe gerade die Option "auf Straße einrasten" deaktiviert, jetzt
funktioniert es.
Vielen Dank und Gruß
Roland

Roland Stengel ***@***.***> schrieb am Mi., 27. Sept.
2023, 11:29:
