### ISSUE TITLE
Seit Update 4.6 kein "AUFWECKEN" möglich.

### ISSUE THREAD

**Issue by Paul-04** [osmandapp/OsmAnd#18233]
### Description

bei Route abfahren bleibt das Display bei ansagen dunkel. Mir der Version 4.5.10 funktioniert alles normal.
Auch mit Samsung S5 und S10 alles OK

### Steps to reproduce

Route abfahren und warten bis Ansage kommt

### Actual result

bei Ansage bleibt Disolay dunkel

### Expected result

Display sollte bei Ansagen einschalten und den vorgewählte Zeitraum eingeschaltet bleiben

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:4.6.1
Android/iOS version:Android 13
Device model:Samsung "20 Ultra SM-G988B/DS
Crash-Logs: ?
```

**Comment by DmitryAlexei** [comment]
@Paul-04 please,
- translate your issue into English, so every member of our community will be able to understand it
- add your driving profile (where error occurs). go to OsmAnd menu > settings > your driving profile > swipe to the bottom
- if possible, add logcat file recorded just after you encounter this error

**Comment by Paul-04** [comment]
I can't find the log file. But errors occur with all profiles.

**Comment by DmitryAlexei** [comment]
How to find crash logs https://osmand.net/docs/user/troubleshooting/crash-logs#send-logs-from-osmand-app-android
Please add short video or screenshots of your issue

**Comment by scaidermern** [comment]
Just for reference, automatically switching the display on for turn instructions works fine fore me (OsmAnd 4.6.1, Android 10).

**Comment by DmitryAlexei** [comment]
@Paul-04  are we talking about possible screen control issue? Or map screen is dark during navigation?

**Comment by DmitryAlexei** [comment]
It is probably related to https://github.com/osmandapp/OsmAnd/issues/18082
See comment https://github.com/osmandapp/OsmAnd/issues/18082#issuecomment-1737441732

**Comment by Paul-04** [comment]
Hier ist eine logcat.log Datei
[logcat.log](https://github.com/osmandapp/OsmAnd/files/12764639/logcat.log)
