### ISSUE TITLE
Tracker widget cannot be selected like other widgets

### ISSUE THREAD

**Issue by mikehgentry** [osmandapp/OsmAnd#18235]
### Description

1: If you put widgets including the tracker widget on a profile then copy to another profile, the tracker widget will not be copied.

2: In the 'Available widgets' list you can tap on the name of other widgets. With the tracker widget you have to tap on the icon to the right to select it.

### Steps to reproduce

Create a profile, add some widgets including the tracker widget. Note that to add the tracker widget you have to tap the icon to the right in the 'Available widgets' list.

Create another profile, go to configure screen and copy from the first profile.

### Actual result

Widget is unselectable via text. Widget will not copy.

### Expected result

Widget is selectable via text. Widget is copyable.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: +4.6.1
Android/iOS version: 11
Device model: XCover 4s
Crash-Logs: N/A
```

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#834m, released: 2023-10-03
Unable to reproduce
- set the tracker widget in driving profile
- OsmAnd tracker widget was successfully imported with driving profile
- 
https://github.com/osmandapp/OsmAnd/assets/116079541/e5df1ed5-d4e9-4217-88c4-001f5a7cd675

**Comment by mikehgentry** [comment]
I can reproduce it pretty consistently here, but I've noticed bug 1 only triggers if I copy from the 'Configure screen' screen. If I go into the screen for the actual widget panel and copy from there, it doesn't trigger.

Bug 2 only seems to be present when bug 1 is. I will try to reproduce on a clean installation later.

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#834m, released: 2023-10-03
**Reproduced**
*OsmAnd Tracker widget* can be added to a profile from configure screen only by tapping on the right side of it.

Steps to reproduce:
- enable OsmAnd tracker, link it to the OsmAnd app
- go to any profile 
- try to add tracker widget to the right or left panel

Actual result:
- widget menu opens only when you tap on the right side of the widget field (on the *i* button)


https://github.com/osmandapp/OsmAnd/assets/116079541/274e8fcb-dda9-44fa-a799-6f3248f90449

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.7.0#1346m, released: 2024-01-10
Now OsmAnd Tracker widget works like other widgets. Taping on any part of the OsmAnd tracker list item (not only right part of it) opens widget details (see video)

https://github.com/osmandapp/OsmAnd/assets/116079541/e3fa3289-bc0c-4e91-bec4-839732be4a62
