### ISSUE TITLE
Searching for various POI attributes is broken

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#18249]
### Description

Searching for a specific type of waste at a recycling container doesn't work. 

### Steps to reproduce

Tap on a recycling container. Unfold the list of accepted waste. Tap on any of the items. The search returns no results and nothing gets highlighted on the map.

https://github.com/osmandapp/OsmAnd/assets/1040784/a1609383-0745-4554-bacd-02084b210615

### Actual result

No results. 

### Expected result

Results. 

### Your Environment (required)

```
OsmAnd Version: 4.6.2
Android/iOS version: 10
Device model: Samsung S9
Crash-Logs: ?
```

**Comment by scaidermern** [comment]
The same issue exists for various other POIs.

* crossings: type: no results
* crossings: tactile paving yes: no results
* bicycle parking: type: no results
* pharmacy: wheelchair accessibility yes: no results

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced.  When you click on the map and select one of the following categories: Recycling, Pharmacy, or Bicycle parking, and then choose a specific type, the search yields no results, and there is no corresponding highlighting on the map, regardless of the search radius.

To reproduce the issue, follow these steps:

- Download a map of Berlin.
- Search for Recycling, Pharmacy, or Bicycle parking.
- Click on the POI and scroll down to the "Type" option, etc.
- Click on "Type" or a similar option to display the search bar, but nothing is found.

It's worth noting that there is no category named "crossings" at all. Please provide more precise information.

OsmAnd~ 4.6.0#844m, released: 2023-10-06



<table style="width:100%">
  </tr>
  <tr>
    <th>Recycling</th>
    <th>Pharmacy</th>
    <th>Bicycle parking</th>
  </tr>
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/6f963840-9db7-4a3a-94c7-7649a6fd7360"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/c850d6e3-1ab4-4fcf-82c6-e2619a9abb43"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/a58e17bd-639a-499f-b7d1-aa37ee0d52ce"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by dmpr0** [comment]
# Review 
- [ ] Missed ToDo

**Comment by Chumva** [comment]
Search opened from context menu should find items similar to selected one

For example bicycle parking with type shed should find parkings with same type
