### ISSUE TITLE
Cloud sync of multiple devices to same account results in multiple copies of favorites

### ISSUE THREAD

**Issue by Busterama452** [osmandapp/OsmAnd#18241]
### Description

I have two android devices setup to sync to the cloud.  I've synced several times on both devices and now the individual favorites  are showing 4 times in each file.  My favorites files are now exploding in size and bogging down rendering when I enable my favorites to show.

### Steps to reproduce

Setup two android devices with OSMAND Pro and set them to sync to the same account.  Synchronize favorites on device A, then on device B, then back and sync device A...

### Actual result

Here's a screenshot from within the web interface showing the quadruplicated favorites.

<img width="615" alt="image" src="https://github.com/osmandapp/OsmAnd/assets/61025063/771700ab-1d1a-4182-8ab2-50739131af01">

### Expected result

There should not be duplicated favorites.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```
/
/

**Comment by Busterama452** [comment]
Here's a screenshot of the quadruplicated favorites on one of my android devices.
![Screenshot_20230927_111931_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/61025063/1335ac91-42e8-482c-8b01-7e163a3fa194)

**Comment by DmitryAlexei** [comment]
I succeeded to reproduce this issue using 2 mobile phones (one Android 13 OsmAnd~ 4.6.0#825m, released: 2023-10-01 and second Android 7 OsmAnd 4.5.10) and [iOverlander_Peru.zip](https://github.com/osmandapp/OsmAnd/files/12789366/iOverlander_Peru.zip) package of favorites.

Preparations:
- cleared all data from OsmAnd cloud
- switched off *Automatic backup* option in in Settings > OsmAnd settings > Auto-backup on both phones
- In Cloud settings in *Back up data* settings choosed only *Favorites* on both phones
- cleared all favorites and tracks on both phones
After that
- I imported iOverlander_Peru.gpx as Favorites on Android 13 device
- synchronized Favorites via OsmAnd cloud with Android 7 device

Already at this step on the second phone appeared conflicts between favorite points, which could not be resolved
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/788fd6d0-7a51-4755-9257-76ef0626485e"  width="300" height="auto"/> </td>
  </tr>
</table>

After syncing favorites back on the Android 13 device, I received 3 additional copies of each favorite point shown. At the same time, the size of favorites increased in about 8 times (16.8 Mb initial gpx file and 133 Mb resulted favorite export). See 
[favorites.zip](https://github.com/osmandapp/OsmAnd/files/12789977/favorites.zip). The structure of the initial .gpx file has been saved, but the number of lines increased from 300 thousand to 2.4 million. 
For example wpt lat="-13.525519" lon="-71.952136 repeats 3 times in the resulting file (and in initial file only 1 time)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/3fbfa0e6-9c82-4535-a82b-48e5d8622c82"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/96b53eba-7aad-4349-be9c-4e1ec8af9638"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
At the same time I didn't manage to reproduce this issue with favorite points created in OsmAnd.
- created 2 favorite points in 2 folders
- syncing multiple times between 2 devices
- there were conflicts while syncing, but duplicates have been not created

**Comment by DmitryAlexei** [comment]
After this pull request https://github.com/osmandapp/OsmAnd/pull/18510 cannot manage to create duplicates of favorites via cloud sync.

**Comment by Busterama452** [comment]
> After this pull request #18510 cannot manage to create duplicates of favorites via cloud sync. So this issue can no longer be reproduced.

Is this fixed on the cloud/web services or does this require a mobile app update?  If this requires a mobile app update, what release is/will it be in?

**Comment by DmitryAlexei** [comment]
@Busterama452 updating of mobile app required. You can try beta-version from Google play or wait for the next 4.6 release. Hopefully it will be ready by the end of the year.

**Comment by Busterama452** [comment]
> @Busterama452 updating of mobile app required. You can try beta-version from Google play or wait for the next 4.6 release. Hopefully it will be ready by the end of the year.

Awesome, thanks for saving me from turning on sync on two devices and ending up with a mess.  I'll consider beta.
