### ISSUE TITLE
How to avoid error "BRouter service is not available"

### ISSUE THREAD

**Issue by EssBee59** [osmandapp/OsmAnd#18244]
### Describe the idea (required)

Hello,
An old problem (reported for years  in  https://github.com/osmandapp/OsmAnd/issues/10148) occured again after a sw update:
Platform:
Smartphone: Xiaomi MI 12T Pro
Android 13
MIUI 14
Brouter-app 1.7.3
Osmand 4.5.0

Problem:
The routing & navigation with Osmand (using Brouter-app) starts successfully, but after a time between 20 and 50 minutes the error "BRouter service is not available" is reported in Osmand.

Cause:
By starting Osmand open the IPC connection with Brouter-app (this creates a "brouter_service" backgroud process)
The brouter_service should run untill Osmand is closed... but it sems that a Xiaomi "optimization" kills the service after a variable time,

The error "BRouter service is not available" is reported when Osmand tries to call the Brouter-app in that situation.

[Brouter_miui14.txt](https://github.com/abrensch/brouter/files/12712411/Brouter_miui14.txt)

Workarroud:
Underway my workarround was to close Osmand and start it again (a new brouter_service is started ... for 30 minutes or so..)

A running solution:
I could find a running "solution": it consists to deactivate the "MIUI optimization".
Two steps are necessary for that, this page describes how to proceed:
https://www.gizmochina.com/guides/how-to-disable-miui-optimization/

As the solution above is not intuitive and not easy to implement, I liked to have a better (long term) solution like this:

A change in Osmand: try once to reconnect to the Brouter_service in case of error.

I tested this change:
1- In RouteProvider.java
......
		OsmandApplication ctx = params.ctx;
		List<Location> res = new ArrayList<Location>();
		List<RouteDirectionInfo> dir = new ArrayList<>();
		List<Location> segmentEndpoints = new ArrayList<>();

		IBRouterService brouterService = ctx.getBRouterService();

// Change essbee: by need try to reconnect...
		if (brouterService == null) 
     {
           log.info(" brouterService is NULL (A)");
           log.info(" brouterService TRY reconnect to Brouter_service once...");
            
           brouterService = ctx.reconnectToBRouter();

     }
// End Change essbee

2- In OsmandApplication.java
make the "reconnectToBRouter" public and add a delay..

	public IBRouterService reconnectToBRouter() {
          LOG.info(" reconnectToBrouter starts...");

		try {
			bRouterServiceConnection = BRouterServiceConnection.connect(this);
//  a delay is necessary as the service process needs time to start..
                Thread.sleep(800);    

			if (bRouterServiceConnection != null) {
                      LOG.info(" reconnectToBrouter call getBrouterService ...");

				return bRouterServiceConnection.getBrouterService();
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
           LOG.info(" reconnectToBrouter ... return null...");

		return null;
	}

Regards

### Tell us about the expected behaviour (required)

With the change the problem do not occur longer

### Tell us about alternatives you've considered (required)

Deactivate the MIUI optimization...
Not easy, and the problem could occur on further platforms

**Comment by vshcherb** [comment]
sounds like a reasonable approach, please prepare pr if possible

**Comment by EssBee59** [comment]
Thank for your message!
As I am not expert for PR´s afficherdev (from Brouter-team) will create a PR after retests, so it needs some time!

I have a further idea to enhance the use of Osmand+Brouter.
Is it of interest?
[Osmand_PR2.txt](https://github.com/osmandapp/OsmAnd/files/12801005/Osmand_PR2.txt)
