### ISSUE TITLE
Disable autofill for new waypoints 

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#18258]
### Describe the idea (required)

When creating a new waypoint the name is automatically filled with the current address. Most of the time the address is not the desired name of the waypoint. This means the user has to delete the address from the waypoint name. Usually this takes multiple seconds, especially if the address is long and consists of many words.

I use waypoints to make mapping notes in order to improve the map. Emptying the waypoint name field takes a considerable amount of my time while surveying.

Please make this behavior configurable. I never need the address in the waypoint name. I guess this is also true for most other users. 

### Tell us about the expected behaviour (required)

The name is empty when creating a new waypoint. 

### Tell us about alternatives you've considered (required)

Use a different app? 🤔

**Comment by Rowin63** [comment]
Waypoint = Favorite?
When creating a new favorite, for a split second (at "search adress") there is an option "enter name / skip" but its displayed way too short to react (it really appears only for the fraction of a second).
I needed to take a picture out of a screen recording to see that option...

![20231001_081808](https://github.com/osmandapp/OsmAnd/assets/95540936/2cfa7cc2-5036-46c7-b57c-04fdd8bdd701)

**Comment by scaidermern** [comment]
> Waypoint = Favorite?

No, GPX waypoint in my case. But looks like the problem is the same for favorites. 

When creating a new favorite, for a split second (at "search adress") there is an option "enter name / skip" but its displayed way too short to react (it really appears only for the fraction of a second).

Yes, trying to dismiss this dialog is usually not an option.

**Comment by mikehgentry** [comment]
One way some software handles this is to make the autofilled name the selection when the dialogue appears, so you only have to hit backspace to get rid of it, or click outside the entry box (/ tap outside the virtual keyboard, I suppose) to keep it.

Not sure if you can even do that on Android, but if it works it avoids another setting.

**Comment by scaidermern** [comment]
> One way some software handles this is to make the autofilled name the selection when the dialogue appears, so you only have to hit backspace to get rid of it,

Either this. Or a small trash icon to delete the current text in the nam field.

@vshcherb Is this possible? Adding named waypoints has become very cumbersome in OsmAnd 4.6.x. Would be nice to have a solution for this soon.

**Comment by vshcherb** [comment]
I think more important is to
To do: focus field while creating waypoint same as favorites.

Some keyboards provides quick access to select all / delete all in the input field.

To think: offer a setting to not search for address while creating waypoint / favorite

**Comment by scaidermern** [comment]
I just compared the behavior with OsmAnd 4.5.x on a different device. In the older version the text was pre-selected, so hitting delete was enough to clear the input field. OsmAnd 4.6.x doesn't have this anymore. So maybe just restore the old behavior?

**Comment by vshcherb** [comment]
Sounds reasonable, at least I don't any request to disable old behavior.
