### ISSUE TITLE
Android - Add POI - suggestions to improve usability

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#1825]
I'm using Android version, and I do add POI while driving (not advisable, I know), but I'm not the only one doing this ;)

With the current night build, I have to follow these 10 steps:
1 - long press the spot on the map, that opens the 'spot options' (I don't know the correct name, or how to call that menu)
2 - tap the 3dots,
3 - choose 'Add POI'
4 - tap the name value to open the virtual keyboard
5 - write the name
6 - tap 'back' phone button to return to the context menu
7 - tap the 'POI Type' value to open the virtual keyboard
8 - write/choose POI type (i know what I want to write, it's easier than going through the categories list)
9 - tap 'Send' virtual button
10 - tap the map screen to get that 'spot options' menu out of the way, to see the map again

So if the process of inserting a new POI is made easier, it will be better for us all.
Those 10 steps are a nice number, but could be made simpler.
Previous versions were simpler in menus, but we had to scroll some, and that doesn't help either.

So for start:
Suggestion on step 1 - make the 'Add POI' readily available on the 'spot options', right after the long press. 
Please mind that I do realize that not every user is going to need the 'Add POI' function, so to be fair, I understand if this option stays away hidden under the 3dots sub-menu, even though it would really make my life easier (and all other mappers) if it was readily available at step 1, we would skip 2 steps in the process.
More so, because with the 'spot options' sliding from the left side (current night build, using the phone in landscape mode), there is a lot of blank space unused in the menu.

Suggestion on step 4 - when we choose to Add (or Create) a new POI, the POI editing/adding context opens up, with the name=value blinking the cursor, but we still have to tap on it, in order to open the virtual keyboard, so that we can type the name.
Since most of the phones are Touchscreens without real keyboards, could the virtual keyboard be already opened when the 'edit/add POI' context pops-up?
That would have the same use, but we would need one less click to be able to write the 'Name' value, since the virtual keyboard would already be opened and ready for typing.
That would skip another step in the process.

Suggestion on step 6 - Following the 'make things easier' line of thought, and to make the insertion faster (as I sugested in #1439 ), when adding the 'Name' value, with the phone placed in landscape mode, there used to be a virtual button to click 'Next' (and it would go to the POI_Type) that is now replaced by a 'Send', but this is not good, since we first need to insert a 'POI Type' to be able to send a valid OSM POI information.
The 'send' button is great in the 'POI_Type' value, but the 'Name' value should maintain the 'Next' button.
In portrait mode, that 'Next' or 'Send' button is placed at the bottom right corner of the virtual keyboard, very handy to speed things up, but same as landscape mode, only needed to be a 'Next' when writing the Name value, and 'Send' when inserting a POI_type value, and it would just be excellent.
That would skip another 2 steps in the process.

Suggestion on step 10 - after tapping the virtual 'Send' button (step 9), I'd like to return straight at the map view, If i'm navigating, I do like to see the map.
The chosen spot itself can still maintain the orange/brownish circle/teardrop, as if the user needs to use it again, he just has to tap it.
The 'spot options' menu is huge, sure is nice to be able to tap with fat fingers, or even a trembling phone on a rolling car, but since it has been used to 'Add POI', the menu could be out of the way, it doesn't need to stay opened and occupying more than half the screen.
That would skip another step in the process.

So, after all this, the 'Add POI' could be made in just 6 steps:
1 - long press the spot on the map, that opens the 'spot options'
2 - choose 'Add POI', virtual keyboard opens up ready to type
3 - write the name
4 - tap 'Next' virtual button to go to 'POI Type' value,  virtual keyboard stays open, ready to type
5 - write/choose the POI type
6 - tap 'Send' virtual button, and it's done!
with the menu out of the way, we are back at the map view.

Hope I have made some sense, sorry if I didn't use the correct designations for any menu/option, but I think this is understandable.
Most of the suggestion are also appropriate for the 'Modify POI' context, since it's basically the same. 

Cheers and keep up the great work! :)

**Comment by Barrocas** [comment]
Another interesting detail:
In recent versions, when we choose a 'spot' close to a nearby road, that road name is displayed in the 'spot options'.

Could that road name be auto-inserted in the 'street name' field, when adding/editing a POI?

**Comment by GaidamakUA** [comment]
Thank you for your time. That would be separate issue.

**Comment by GaidamakUA** [comment]
@Barrocas Probably we will consider possibility of adding 'Add POI' button to the context menu. Thank you for your suggestions.

**Comment by Barrocas** [comment]
Thanks for making the 'Next' button available again. Already tested it and it is working fine. Makes it a lot easier to use.

Could the other suggested options be considered also?

**Comment by GaidamakUA** [comment]
@Barrocas I believe everything accept 'Add POI' button already implemented. And we are considering possibility to add it.

**Comment by Barrocas** [comment]
Thanks for applying the suggestions.

I can see with today night build v2.3.0#14151M that when creating a new POI, the virtual keyboard instantly pops-up open at the name field, but only if this is done with the phone in portrait mode orientation. If I rotate the phone, it preserves the keyboard opened, waiting for the name insertion. That's fine.

But if I try to add a POI with the phone already in landscape mode orientation, the keyboard stays closed, until the name field is tapped.

Could the landscape mode act like the portrait mode? Keyboard be already opened in field name, when adding a new POI?

**Comment by GaidamakUA** [comment]
Sorry, but when you edit in landscape mode the field is full screen, because there are quite a little space to draw user interface. So by default keyboard is not opened and I don't think it's a good idea to change that.

**Comment by Barrocas** [comment]
I understand, and was also expecting that reason :)

But if I choose to 'Add POI', it's because I intend to type
something... or exit.

1 - (As I sugested), If the keyboard is pop-up opened on the 'name'
field, that is one less tap needed for the mapper.
If I eventually just want to go to the 'POI_type' field (even without
inserting a name), I just have to tap the 'next' button, one time.

2 - (as it is working now), If the keyboard is NOT pop-up opened in
the name field , I have to tap it once on the 'name' field to be able
to write,
and tap it again to go to the 'POI_type' field.
Even if I don't want to insert any name, I still have to tap it once
on the  'POI_type' field to be able to write.

So either way, I would always have to tap once, to be able go write in
the 'POI_type' field.
But making the keyboard pop-up at the 'name' field would simplify
insertion if the 'name' is to be inserted.

Only drawback is that when in fullscreen there is no info (like a
title bar or field denomination) of what is being inserted (name,
POI_type, street, phone, etc), but that is valid for any field value
being edited in landscape mode.

please understand that this is just my humble opinion as a mapper, and
I appreciate all the work done so far, since it's getting much better
and easier to add info to OSM by using Osmand, thus making the
available map info more complete.

Cheers, and great app!

-- 
Cumprimentos,
D.er Hugo Barrocas
