### ISSUE TITLE
Search filter by name not functional in map view

### ISSUE THREAD

**Issue by ceever** [osmandapp/OsmAnd#18256]
### Description

When selection a certain kind of POI and then filter by name, the filter works in the resulting list. But when selection "Show ... on map" the name filter is not applied, but only the original category.

### Steps to reproduce

1. Select the specific hostel in Tirana.
2. Search nearby for category "hostel".
3. Filter by name "Hostel" ... see that the list just keeps the ones with the actual name.
4. Select "Show ... on map" and observe that the hostel where we started is still displayed as an orange POI.
See pictures:
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/40247591/fd66b752-4acc-4794-a23b-52fcfafafc6e"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/40247591/3eeeffcf-350b-4fd7-aa7a-f9cfefb87e45"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/40247591/87b6e4d1-beab-4601-9ef1-ca6a6f822ec4"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/40247591/e3ff3e2a-6edf-4141-b1e9-a25c8762a4f1"  width="300" height="auto"/> </td>
  </tr>
</table>

### Actual result

The orange POI icon does appear in the map.

### Expected result

The orange POI icon should not appear in the map.

### Your Environment (required)

```
OsmAnd Version: 4.5.10
Android/iOS version: 9
Device model: Galaxy S8
Crash-Logs: ?
```

**Comment by DmitryAlexei** [comment]
@ceever please specify, why the “initial” hostel should not be displayed

**Comment by ceever** [comment]
I don't understand the question. It seems like a valid usecase to me, I choose a category and then filter by name. I can think of a dozen other cases like mine. Why shouldn't that work for certain combinations of category and name? They are different POI keys, aren't they?

But I think you are missing the real point here. It's not so much the specific query, it is the fact that the result list is not consistent will the results in map view ... that's the bug.

Cheers

**Comment by vshcherb** [comment]
Yes confirmed results on map is different than in search list Android / iOS - also in IOS you can't get back to exact search filter via top row

**Comment by sonora** [comment]
@vshcherb Also: It seems we should have some spinner type indication on the top bar in the map view, indicationg when the search (or its result display on the map) is still ongoing. In my experirnce there can be considerable time lag until search results are actually shown on the map, and users may prematurely zoom or scroll the map, or even leave the app already, thinking no results are in the vicinity, and not noticing the display is not done yet.

**Comment by vshcherb** [comment]
Well good point though...
