### ISSUE TITLE
Sorting in Maps & Resources – Local

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#18257]
### Description

Downloads are listed by country, then region
Updates (maps and wiki) are listed by country, then region

But everything in "local" (maps, wiki, terrain, ...) is listed by region, then country

### Steps to reproduce

have a look at it

### Actual result

confusing listing

### Expected result

correct listing

### Your Environment (required)

OsmAnd Version: +4.6.2, 4.6.0#823m

**Comment by scaidermern** [comment]
I think @vshcherb already mentioned in a Telegram group that this is a known bug that will be fixed. Still helpful to have a bug ticket for this.

**Comment by vshcherb** [comment]
![telegram-cloud-photo-size-2-5246751239163727737-y](https://github.com/osmandapp/OsmAnd/assets/1042025/0e80386f-803d-467f-a024-4197408f5d06)

Yes it's missing design I don't think now it's worth to keep track as it will be fixed soon.
