### ISSUE TITLE
Maps & Resources / Local: Up-to-date maps and outdated maps have the same color

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#18261]
### Description

In the new overview at Maps & Resources / Local, all maps have the same color. Previously, outdated maps were shown in orange and up-to-date maps were shown in green.

### Steps to reproduce

See above. 

### Actual result

No differentiation between outdated and up-to-date maps. 

### Expected result

Differentiation between outdated and up-to-date maps. 

### Your Environment (required)

```
OsmAnd Version: 4.6.2
```

**Comment by dmpr0** [comment]
Fixed https://github.com/osmandapp/OsmAnd/pull/18251
