### ISSUE TITLE
Add POI display locker room

### ISSUE THREAD

**Issue by snooppr** [osmandapp/OsmAnd#18264]
### Describe the idea (required)

OsmAnd does not display the "dressing room" POI (Tag:amenity=[dressing room](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Ddressing_room) ).  Usually there is a place on the beaches for changing clothes

This tag could also be added to the POI-OsmAnd editor

### Tell us about the expected behaviour (required)

When exploring the beach, it will become obvious to the user whether it is possible to change clothes there privately.

### Tell us about alternatives you've considered (required)

Nein.

**Comment by DmitryAlexei** [comment]
3 697 objects according to [taginfo](https://taginfo.openstreetmap.org/tags/amenity=dressing_room#overview)

**Comment by snooppr** [comment]
Yes, I know, the link attached in the post to the tag tells you the number of objects on the map, are there any difficulties or limitations?

**Comment by xmd5a2** [comment]
Object to test: https://www.openstreetmap.org/way/366356472
Map **France_hauts-de-france** will be regenerated in a couple of hours.

**Comment by xmd5a2** [comment]
> IHMO, the main thing is to add a tag to the POI editor, and then there will be more locker rooms on the map.

It is done in [this commit ](https://github.com/osmandapp/OsmAnd-resources/commit/974859daa185cb9cc61582217669a7091aabac0a)
