### ISSUE TITLE
add possibility to clear tile cache

### ISSUE THREAD

**Issue by HolgerJeromin** [osmandapp/Osmand#1827]
It would be nice if i could clear the downloaded tiles of one tile layer in the "map management" (where i can download maps).
At least this would be the place i would expect such a "clear cache" function.

**Comment by jf-simon** [comment]
![screenshot_2015-10-23-08-55-55](https://cloud.githubusercontent.com/assets/11144987/10686398/04df2708-7964-11e5-84e8-ff9095c8a808.png)

**Comment by HolgerJeromin** [comment]
did you tried it?
After clicking delete (or "löschen" in german) the whole tile layer was not available anymore. 
So it removed the entry.

**Comment by jf-simon** [comment]
You are right, the entry was removed from 'local'. If you add for example 'Microsoft earth' layer via the 'overlay map' you will see the entry again.

**Comment by HolgerJeromin** [comment]
I am even not sure that the cache is cleared on removing. 
So another item in the menu "clear cache" is very useful.

**Comment by HolgerJeromin** [comment]
Thanks!
