### ISSUE TITLE
Configure Map and Search buttons jump when context menu is open

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#18275]
## Description
Buttons in top left corner are jumps when context menu is open or closed.

### How to reproduce
* Open OsmAnd, tap on any POI on the map

### Actual result
<table style="width:100%">
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/c6da8f84-490d-4601-94e7-b07d46125ae3"  width="300" height="auto"/> </td>
  </tr>
</table>   

* Buttons is jumps

### Expected result

**Environment**
OsmAnd Version: OsmAnd 4.6.1, released: 2023-09-15
Android: 14
Device model:

**Comment by dmpr0** [comment]
# Review 

<table style="width:100%">
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/ed31b7a8-8bc8-457e-94af-ca4e1be939b4"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ]  Still reproduced

**Comment by vshcherb** [comment]
- [ ] Fix jumping search buttons
