### ISSUE TITLE
seamark TSS separation line rendered as arrows

### ISSUE THREAD

**Issue by quantenschaum** [osmandapp/OsmAnd#18270]
### Description

The `seamark:type=separation_line` (l**I**ne) is rendered like a `separation_lane` (l**A**ne). 

### Steps to reproduce

Look at a [TSS with a separation line](https://www.openstreetmap.org/way/1212194047).

### Actual result

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/3985599/1ccf9519-c5b4-4e9c-a0de-7561d146f3d2"  width="300" height="auto"/> </td>
  </tr>
</table>

arrow in center line

### Expected result

solid magenta line 

![image](https://github.com/osmandapp/OsmAnd/assets/3985599/36468971-8db2-4a28-a6cc-a5afcafefd70)

see https://wiki.openstreetmap.org/wiki/Tag:seamark:type%3Dseparation_line

### Your Environment (required)

```
OsmAnd Version: 4.5.10
Android/iOS version: 11
Device model: Nokia X20
```

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#825m, released: 2023-10-01
Separation line is rendered according to Map legend (https://osmand.net/docs/user/map-legend/nautical-map#anchorage-and-berth) as solid magenta line

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/e7950899-a356-435f-ac00-ced79579fe5f"  width="300" height="auto"/> </td>
  </tr>
</table>

@quantenschaum probably it was rendering issue due to live updates. As for me with fresh maps works fine

**Comment by quantenschaum** [comment]
Hi! This may be because this line was changed recently. The fat line in the center in a `separation_area` (3), not a line. Please zoom in closer or look at https://www.openstreetmap.org/way/180387151.

The problem is here https://github.com/osmandapp/OsmAnd-resources/blob/master/rendering_styles/nautical.render.xml#L3546

`line` and `lane` are rendered the same.

**Comment by quantenschaum** [comment]
No, you are getting something wrong here. The legend is wrong because it was generated with the code mentioned above which is wrong. Please look at https://wiki.openstreetmap.org/wiki/Tag:seamark:type%3Dseparation_zone.

`separation_zone` and `separation_line` are zones/areas that vessel have to keep clear of, they are shown as solid magenta lines/areas in the map. The `separation_lane` is a one-way road and is displayed with arrows.

Here `line` and `lane` have been treated the same by accident. 

Displaying the `separation_line` like a `separation_lane` is an error. This is a bug.

**Comment by quantenschaum** [comment]
There is also another problem with TSS `separation_lane`s. They are not rendered when they form a closed loop. 

`separation_line`, `lane`, `boundary` should be assigned `objectType=2`.

**Comment by quantenschaum** [comment]
Here an example for testing.

[tss.zip](https://github.com/osmandapp/OsmAnd/files/12790428/tss.zip)

expected
![tss](https://github.com/osmandapp/OsmAnd/assets/3985599/a074fc97-aa42-47ae-be7f-725bfcb81517)

actual
![Screenshot_20231003-104316](https://github.com/osmandapp/OsmAnd/assets/3985599/2e227fcd-177a-4ddf-a0f9-457a0e6ceab8)

**Comment by quantenschaum** [comment]
problems
- `separation_line` rendered as arrows
- `recommended_traffic_lane` just a black line, should be dashed arrows
- `separation_line`, `separation_lane`, `separation_boundary` not shown when closed loop (but `recommended_traffic_lane` is shown)

**Comment by xmd5a2** [comment]
Fixed. No new maps required, just OsmAnd.

**Comment by quantenschaum** [comment]
Thank you! :cake: 

Would be nice, if you also fixed the issue with closed ways. Please assign `objectType=2`, so that lines and lanes are rendered as lines if they form a closed loop. see https://github.com/osmandapp/OsmAnd/issues/18270#issuecomment-1744504145

**Comment by xmd5a2** [comment]
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/1001c0f3-0d54-46a1-ae07-db289764931a)

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#891m, released: 2023-10-19
tested on https://www.openstreetmap.org/way/180387151 coordinates https://www.openstreetmap.org/way/180387151
seamark:type=separation_line is shown as solid magenta line going through the center of the map from bottom to top

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/ee1dc938-e840-409f-ab86-32bcf508ce52"  width="300" height="auto"/> </td>
  </tr>
</table>
