### ISSUE TITLE
Bug in the "Avoid road" feature

### ISSUE THREAD

**Issue by ahmaduxui** [osmandapp/OsmAnd#18273]
### Description

I accidentally put an "Avoid road" point in the sea!  But it is not possible to remove this point!

### Steps to reproduce

- Open the OsmAnd
- Choose a point of the sea
- Select "Avoid road" from the menu
- Now close the OsmAnd app and open it again

### Actual result

It is not possible to remove the "Avoid road" point

### Expected result

These points should have been removed and this feature is not used in the sea and by default the app should not allow this

### Your Environment (required)

```
OsmAnd Version: 4.5.6 and 4.6.0
Android/iOS version: 13
Device model: Realme C35 RMX3511 
Crash-Logs: ?
```
https://github.com/osmandapp/OsmAnd/assets/44550501/6bdf7f00-fbe1-4227-a7c8-b44e83bc9c9e

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#832m, released: 2023-10-02
@ahmaduxui try to reach *Avoided roads* list via navigation settings. Please see https://osmand.net/docs/user/navigation/routing/osmand-routing#avoid-roads-menu
As for me adding avoid road in the sea and removing this sign works correctly (see screenshot), so you may try updation the app to the latest version (4.5.10 or  last beta) and try agin.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/45c78459-eb2e-4685-8774-c8094eb554a2"  width="300" height="auto"/> </td>
  </tr>
</table>
