### ISSUE TITLE
Hide "war zones" does not work properly

### ISSUE THREAD

**Issue by snooppr** [osmandapp/OsmAnd#18287]
### Description

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/61022210/3daac121-bd4f-4d61-adab-d39e7b66cacf"  width="300" height="auto"/> </td>
  </tr>
</table>

In your profile, you can choose which objects to hide and not display on the map.  This works, for example, for buildings, water bodies, but does not work for military zones.  The military zone remains outlined and highlighted in pink on the map, for example, the tourist layer (Or the "boat" profile.), only the shading disappears.  The problem is that a user can post a screenshot of OsmAnd maps on the Internet, and in some countries this may be punishable by reprisals and persecution.  Thus, a flaw in the application puts the user at risk.

### Steps to reproduce

Select the travel layer.
Profile - hide - military zones.

Find any military zone on the map (I can’t attach a screenshot, it’s unsafe) and see it.

### Actual result

The military zone is outlined in pink, only the pink shading inside the area has disappeared.

### Expected result

Hide military zones the same way you hide other objects, such as water.

### Your Environment (required)

```
OsmAnd Version: 4.5.10
Android/iOS version: LOS16
```

**Comment by yuriiurshuliak** [comment]
It has been reproduced. When you choose the Touring view for the map and hide the military areas, and then search for military zones in the search categories, you'll discover it, and it will be outlined in a pink border.

To recreate it, follow these steps:

- Download the Geneva, Switzerland map.
- Choose the "Touring view" map style.
- Enable the "Hide military areas" option.
- Perform a search for military zone using the coordinates 46.22661° N, 7.38324° E. When found, it will be highlighted with a pink border.

You can also see an example of this in the web version at: [Link](https://test.osmand.net/map/?start=46.226610,7.383240&type=osmand&profile=pedestrian#18/46.22668/7.38277)

OsmAnd~ 4.6.0#844m, released: 2023-10-06


https://github.com/osmandapp/OsmAnd/assets/127092082/b627b98d-fca9-41a9-bd6e-91d488191ba7

**Comment by yuriiurshuliak** [comment]
The issue has been resolved. Military areas will no longer appear on the map when using the "Touring view" map style and having the "Hide military areas" option activated.

OsmAnd~ 4.6.0#1007m, released: 2023-11-10

<table style="width:100%">
  </tr>
  <tr>
    <th>"Hide military areas" is enabled</th>
    <th>"Hide military areas" is disabled</th>
  </tr>
  <tr>
  <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/459961d9-01b5-4111-948b-4fe1920d08ac"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/8aecfe67-7f3c-43b5-af87-96c05a04f017"  width="300" height="auto"/> </th>
  </tr>
</table>
