### ISSUE TITLE
Make the area around the zoom buttons inactive.  Prevent accidental clicks.

### ISSUE THREAD

**Issue by snooppr** [osmandapp/OsmAnd#18286]
### Describe the idea (required)

The zoom buttons are the most frequently used, which means the percentage of accidental clicks in the area between the buttons is high.  This is where the problem arises: when your finger gets into the area between the buttons, the focus of the map shifts to the southeast.  Unfortunately this happens all the time.  And instead of zooming in and seeing any place, the focus of the map flies down, a menu of an object pops up, which the user did not select, and this menu is pressed by inertia.

### Tell us about the expected behaviour (required)

Due to accidentally pressing the area between the buttons, the focus of the map is shifted and the user takes time to find the object he wanted to study again, this is not fast in an unfamiliar area.  Thus, the problem of accidentally pressing in the area between the buttons is not only an irritation, but also some damage to the loss of momentum.

https://github-production-user-asset-6210df.s3.amazonaws.com/61022210/272781318-6ce0e29a-3ea0-4c0c-84c1-7960913f8d1d.mp4

[edited] For a better example of reproducing the problem, see:
https://github.com/osmandapp/OsmAnd/issues/18286#issuecomment-1760723601

An example of the problem in the video.  I wanted to study the object in focus, but my finger got into the area between the scale buttons and the focus of the map shifted far, a menu came out and by inertia this very menu was pressed (I planned to change the scale, click speed several times per second), which can sometimes cause different  actions, such as downloading maps.

![2023-10-05-07-18-28-652](https://github.com/osmandapp/OsmAnd/assets/61022210/1baa9847-49af-45f9-998b-350c8e80f1e9)
Make the red shaded area around the buttons inactive.

This will solve the problem of accidental clicking, which happens very, very often.

### Tell us about alternatives you've considered (required)

Nein.

**Comment by zipav** [comment]
OsmAnd Nightly 4.6.0#867m, released: 2023-10-12

Only if pressed for more than one second, the map moves, tested several times in a row, in other cases - with a short random press the app offers to download a map of the area, and this offer can be closed without shifting the selected area of the map.


https://github.com/osmandapp/OsmAnd/assets/123936521/7f7ca573-60e2-4a2c-bb46-e11b7f26c1dd

**Comment by snooppr** [comment]
The displacement of the map depends on the area (terrain in the southeast) and the scale that falls between the buttons, if it is clickable, then the map flies away, this is a very common occurrence.  It is with a short accidental press that the card flies away.  Your example is not the same as the example in my video, your click area between the buttons is slightly different so the map doesn't move as much, but if you target the area between the buttons exactly like I do in the video, your map will also move a lot.

**Comment by vshcherb** [comment]
We wan't to disable the country click cause indeed it's annoying and opens menu however non clickable area is rather radical solution and we will need to implement for all buttons
