### ISSUE TITLE
Improve font color and add translation

### ISSUE THREAD

**Issue by franco999** [osmandapp/Osmand#1828]
In some parts of the dark theme of the application, the font color is very dark and can not see much that is written. Please change to a lighter color.
And the second thing is, adding the translation of the string "will start from OsmAnd map screen".
Thanks!

![screenshot_2015-10-23-10-19-15](https://cloud.githubusercontent.com/assets/12088580/10693814/0ac55c3e-7971-11e5-8456-ac33704d1cff.png) ![screenshot_2015-10-23-09-01-41](https://cloud.githubusercontent.com/assets/12088580/10693813/0ab8fb60-7971-11e5-80d0-75dd5753bc3b.png)

**Comment by vshcherb** [comment]
#1257
