### ISSUE TITLE
New crash in search

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#18295]
Just produced with a build from today's code, happened simply when tapping the Search button, while the screen collected the seach history. Possibly related to #18077.

[exception.log.txt](https://github.com/osmandapp/OsmAnd/files/12821050/exception.log.txt)

**Comment by Rowin63** [comment]
Yes, happens in the 841m

**Comment by sonora** [comment]
Looks related to Smart Folders, so likely not related to the 'slow search' problem.
