### ISSUE TITLE
Route cannot be found if "use elevation data" is enabled

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#18290]
### Describe the routing engine used (required)

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Describe your routing Profile (required)

Bicycle routing with "use elevation data" _enabled_.

### Describe your start and end points (required)

Start: 47.58100, 11.59295
End: 47.56556, 11.58151

https://osmand.net/map/?start=47.581005,11.592955&finish=47.565556,11.581514&type=osrm&profile=bicycle#15/47.5733/11.5933

### Describe the actual route (required)

No route is found if "use elevation data" is _enabled_. A route is found if "use elevation data" is _disabled_.

![photo_2023-10-05_09-45-50](https://github.com/osmandapp/OsmAnd/assets/1040784/6ea045de-42ca-4510-8b5b-a9418e3af68d)

### Describe the expected route (required)

A route is found with both settings.

### Describe what Maps you used (online or offline) (required)

- [x] Offline maps offered within the OsmAnd app for download. 
- [ ] Online (tile / raster) maps 

### Your Environment (required)

```
OsmAnd Version: 4.6.2
Android/iOS version: 10
Device model: Samsung S9
```

### Anything else? (optional)

This problem doesn't exist in general, but for this route it does.

**Comment by DmitryAlexei** [comment]
@scaidermern Please specify what do you have inside *Use elevation data* option
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/84cd5cc1-8e4c-47e4-8849-a52567219f79"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by scaidermern** [comment]
> @scaidermern Please specify what do you have inside _Use elevation data_ option

I had _Less hilly_ selected. With _Flat_ the route can be found. With both _Less hilly_ and _Hilly_ the route calculation fails.

**Comment by vshcherb** [comment]
Issue is reproduced - https://osmand.net/map/?start=47.581005,11.592955&finish=47.563134,11.576028&type=osmand&profile=bicycle#15/47.5708/11.5952 but the routing itself has enormous cost so it should be revised

**Comment by DmitryAlexei** [comment]
Related https://github.com/osmandapp/OsmAnd/issues/18284

**Comment by xmd5a2** [comment]
Issue is not reproduced in OsmAndMapCreator. Elevation gain is around 750 m and distance is 3.5 km. Routing time is 112 m. The calculated time is quite consistent with the real time of the route, and may even be underestimated. This is very difficult route especially on the bike.

`Route <route>: routing_time=6743,0, vehicle=bicycle, base=false, start_lat=47,58097, start_lon=11,59322, target_lat=47,56607, target_lon=11,58208, complete_distance=3568,4, complete_time=675,2, native=true`
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/c901fb54-2f03-4aa2-a94c-8dd0d2de89f0)

**Comment by RZR-UA** [comment]
I've tried this route with MapCreator:

Java-routing mode - almost OK:

1) without "use elevation data" - OK, Cost ~6800
2) with "use elevation data" - OK (wait few minutes), Cost ~115000 (16x)

Native-routing mode - FAILED:

1) without "use elevation data" - OK, cost ~6800
**2) with "use elevation data" - FAILED (no result after 10 minutes)**

Need to re-check height obstacle values and/or native mode.

**Comment by vshcherb** [comment]
To do:
- [ ]  Fix complete_time (10x difference) - complete_time displayed on UI, routing_time used for computation, consult with @xmd5a2 about penalties for UI and routing Time
```
complete_time=675
routing_time=6743
```

- [ ] probably we also need to limit A* search if it's impossible to reach destination within reasonable time for example if you can't travel 8 km route < 8 h (no reason to continue A* search) - check if it's relevant for this case at all or not. Bidirectional

**Comment by RZR-UA** [comment]
https://github.com/osmandapp/OsmAnd/issues/18305

**Comment by RZR-UA** [comment]
https://github.com/osmandapp/OsmAnd/pull/18549
https://github.com/osmandapp/OsmAnd-core-legacy/pull/152

**Comment by vshcherb** [comment]
![telegram-cloud-photo-size-2-5393517543047681571-y](https://github.com/osmandapp/OsmAnd/assets/1042025/43eecb27-f6b2-42f2-9be2-0daee80298ca)

**Comment by yuriiurshuliak** [comment]
According to my check, the bug persists. When the "use elevation data" feature is turned off, route calculation happens immediately. But when this option is activated with the "Less hilly" setting, the route takes a considerable time to calculate, eventually resulting in an error where OsmAnd fails to calculate the road.
However, it's worth noting that this behavior varies based on the chosen riding style. For instance, when opting  "balanced," "shorter routes," and a preference for "prefer byways," it triggers the specific error mentioned. Conversely, when opting for "prefer unpaved roads," , the route gets calculated despite having the "use elevation data" option enabled.

OsmAnd~ 4.7.0#1264m, released: 2023-12-22

<table style="width:100%">
  <tr>
    <th>The "use elevation data" option is enabled.</th>
    <th>The "use elevation data" option is disabled.</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/4173b24e-a636-45e4-a358-94489922c298"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/00c30980-d563-4d90-a1d7-d9c6f96e98aa"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
- [ ] @xmd5a2  Please provide table for documentation 
- [ ] @RZR-UA please double check bicycle

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.7.0#1264m, released: 2023-12-22
Route can be calculated when either _Flat_, _Less hilly_ or _Hilly_ options inside *Use elevation data* enabled. 

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/6c680478-5143-438c-88da-cee62bde8696"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/699bf34a-a924-49b1-85f6-d399714eafd7"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by xmd5a2** [comment]
Table for documentation:
https://docs.google.com/spreadsheets/d/1qRj5XTZJzrHJAccMHi2LcHfmR7ovjvxs0Cpp4H1zLek/edit?usp=sharing

**Comment by EugeneZmeuk** [comment]
- [ ] tables of penalties
  * [bycile](https://osmand.net/docs/user/navigation/routing/bicycle-based-routing/#penalties-of-elevation-data)
  * [pedestrian](https://osmand.net/docs/user/navigation/routing/pedestrian-routing/#penalties-of-elevation-data)

**Comment by vshcherb** [comment]
Penalties still should be clarified not as numbers! It's better to write table not as
as ``` 2 | 5 | 10 | ... ``` but as ``` 1:2 | 1:5 | 1:10 ```

And explaination given as ``` 3% 1 : 2 ``` means that route with **flat 2  km** will be preferred over route with **3% 1 km** though **3%  1km route** will be preferred over  route **flat 2.5  km**

**Comment by EugeneZmeuk** [comment]
**23.05.2024**
- [ ] [Penalties of Elevation data](https://osmand.net/docs/technical/osmand-file-formats/osmand-routing-xml/#penalties-of-elevation-data)
