### ISSUE TITLE
routing though military zones

### ISSUE THREAD

**Issue by Loki-Afro** [osmandapp/OsmAnd#18294]
### Describe the routing engine used (required)

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Describe your routing Profile (required)

walking, on foot, no restrictions, everything default
allow private access: off

although same happens in my highly customized cycling profiles

### Describe your start and end points (required)

start: https://www.openstreetmap.org/node/8074627048
end: https://www.openstreetmap.org/node/702244053

### Describe the actual route (required)

it routes though Standortübungsplatz Ohrdruf

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/4738445/05c2de65-6a06-417e-833c-ac051c7aaec4"  width="300" height="auto"/> </td>
  </tr>
</table>

### Describe the expected route (required)

it should route around Standortübungsplatz Ohrdruf

### Describe what Maps you used (online or offline) (required)

- [ x] Offline maps offered within the OsmAnd app for download. Germany Thuringia from 1. october 2023
- [ ] Online (tile / raster) maps 

### Your Environment (required)

```
OsmAnd Version: 4.5.8
Android/iOS version: android 12/13
Device model: Fairphone 4
```

### Anything else? (optional)

an additional question maybe, in the south east of that Standortübungsplatz, there is a public trail which slightly overlaps with the restricted area, in reality as well as in osm (although many small differences weirdly enough) i think one should still route though that official public trail .. but just my humble opinion

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/4738445/db9d6386-5ceb-4044-b6a6-d8f513199a23"  width="300" height="auto"/> </td>
  </tr>
</table>

same Standortübungsplatz, place i have not been to, its further north, another public trail(??) that goes directly though
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/4738445/9ccb64d7-332a-4542-8be1-c7a33881ae58"  width="300" height="auto"/> </td>
  </tr>
</table>

keep up the good work!!

**Comment by TheSnoozer** [comment]
Route in question:
https://osmand.net/map/?finish=50.867930,10.824740&type=osrm&profile=car#17/50.86793/10.82474

Related Area:
https://www.openstreetmap.org/way/144959632#map=17/50.81343/10.79724

Related ways:
- https://www.openstreetmap.org/way/178641603#map=15/50.8157/10.8029
- https://www.openstreetmap.org/way/178641583#map=16/50.8119/10.8181
- etc


My personal take here would be: If the Area is restricted (e.g to military personal) then this should also be reflected on the paths/ways in the area. Hence for me this almost sounds like a map issue where the restrictions are not properly encoded.

From https://wiki.openstreetmap.org/wiki/Key:access#Road_with_restricted_access
```
There are some roads with restricted access - roads in factory complexes, on military bases or driveways with clear out of bounds signage or barriers. To mark road as as restricted to only private access, add access=[private](https://wiki.openstreetmap.org/wiki/Tag:access%3Dprivate).
```

**Comment by Loki-Afro** [comment]
@TheSnoozer i thought of a mapping problem as well but .. 
https://osmand.net/map/?start=51.371352,10.902214&finish=51.379388,10.985298&type=osrm&profile=pedestrian#13/51.3718/10.9582 has the same issue, different military zone
and another one https://osmand.net/map/?start=49.693175,11.638985&finish=49.665850,11.997070&type=osrm&profile=pedestrian#12/49.6864/11.7530

**Comment by TheSnoozer** [comment]
Are you sure that this is a osmand only issue?
Consider the route from [openrouteservice](https://maps.openrouteservice.org/#/directions/Pfarrgasse,W%C3%B6lfis,TH,Germany/Markt%2013,M%C3%BChlberg,TH,Germany/data/55,130,32,198,15,97,4,224,38,9,96,59,2,24,5,192,166,6,113,0,184,64,70,0,24,3,160,29,128,14,66,6,103,32,26,1,88,76,160,78,115,152,27,136,227,200,9,128,22,102,52,25,48,6,202,89,190,124,33,104,128,128,1,213,60,8,137,176,229,0,12,222,42,0,66,16,2,186,37,138,181,52,61,232,102,103,76,154,24,0,22,184,77,153,150,29,34,12,209,114,128,3,102,151,35,110,132,172,204,50,94,136,0,230,184,92,20,212,228,0,190,50,0,94,80,0,182,145,116,32,62,0,158,232,30,120,152,38,232,232,168,210,224,250,110,208,153,184,32,0,226,57,201,200,136,149,50,114,208,16,154,94,232,85,234,80,168,0,180,0,238,200,94,0,214,72,17,50,242,138,202,170,160,173,6,176,0,250,38,240,114,158,25,174,97,168,246,56,68,132,123,205,16,72,168,170,84,22,133,176,184,132,177,215,177,64,0,0) which navigates right through the military zone:
![image](https://github.com/osmandapp/OsmAnd/assets/6849390/5693954b-3302-4eec-8caf-d0be3ff74fc4)

**Comment by Loki-Afro** [comment]
@TheSnoozer 
ha you are correct with openroute service .. when i planned that route, i usually do it there in classic, using cycling -> mtb, but even there, it routes one though that zone, kinda surprised now.

the problem is with blindly routing there is, that in many map-styles on osm you don't even see those zones ... that might become dangerous quickly :D

**Comment by Nine-Tailed** [comment]
Because the roads must have appropriate tags for access.  And all these zones do not affect anything; not a single router uses them in routing.
All routing data is read only from road ways and nodes.

**Comment by DmitryAlexei** [comment]
- Cannot find anything with tag *militay* in OsmAnd [routing .xml file](https://github.com/orgs/osmandapp/projects/19/views/26). 
- At the same time need to note, that according to OSM wiki only trespassing *[military=exclusion_zone](https://wiki.openstreetmap.org/wiki/Tag:military%3Dexclusion_zone)* is prohibited by default (14 objects on the map).
