### ISSUE TITLE
maxweightrating= tag not used in truck profile

### ISSUE THREAD

**Issue by R39RA** [osmandapp/OsmAnd#18307]
Merged with https://github.com/osmandapp/OsmAnd/issues/18307
### Describe the idea (required)

maxweightrating=
Please add to cargo navigation so that at least this tag is taken into account. It is marked on a large number of roads in Europe, but is not taken into account when planning a route by truck. The tag indicates the permissible maximum weight.

### Tell us about the expected behaviour (required)

This tag indicates the actual weight of the truck and only this is taken into account when constructing the route. It is necessary to add “maxweight=" on the road where “maxweightrating=" is already indicated so that the navigation is built correctly. Which ultimately leads to conflicts with other cartographers on the OSM map.

### Tell us about alternatives you've considered (required)

I wrote above how I’m doing it at the moment

**Comment by DmitryAlexei** [comment]
maxweightrating:hgv is already in the routing. See [Routing.xml](https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml)
Please update your app to the latest version (you can also try beta from Google Play), update your maps to the latest version and try again.
If the issue persists, please describe on which roads it is not taken into account.

**Comment by scaidermern** [comment]
> maxweightrating:hgv is already in the routing. See [Routing.xml](https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml)

Are the current rules correct? Looks like for a truck profile, only `maxweightrating:hgv` is taken into account. Shouldn't also the more general `maxweightrating` be taken into account? If only this one is given, it surely also applies to heavy goods vehicles.

**Comment by DmitryAlexei** [comment]
@scaidermern according to Taginfo there are 1800 objects with tag [maxweightrating](https://taginfo.openstreetmap.org/keys/maxweightrating#overview) and almost 13000 with tag [maxweightrating:hgv](https://taginfo.openstreetmap.org/keys/maxweightrating%3Ahgv#overview).
So *maxweightrating* will probably be added, when there will be more objects of that type on map.

@R39RA do not forget to specify the weight of your car so that tag *maxweightrating:hgv* is taken into account (see  https://osmand.net/docs/user/navigation/guidance/navigation-settings#limits )

**Comment by scaidermern** [comment]
> @scaidermern according to Taginfo there are 1800 objects with tag [maxweightrating](https://taginfo.openstreetmap.org/keys/maxweightrating#overview) and almost 13000 with tag [maxweightrating:hgv](https://taginfo.openstreetmap.org/keys/maxweightrating%3Ahgv#overview).
> So _maxweightrating_ will probably be added, when there will be more objects of that type on map.

It _is already added_ in Routing.xml. Just not for truck profiles - which seems wrong to me.

**Comment by DmitryAlexei** [comment]
I see only **maxweight** (not _maxweightrating_)  tag in routing
	` <ifnot param="profile_truck">
				<select value="-1" t="maxweight">
					<gt value1=":weight" value2="$maxweight" type="weight"/> `

**Comment by vshcherb** [comment]
To do:
- [ ] Fix https://github.com/osmandapp/OsmAnd/issues/18346

**Comment by tommycrock** [comment]
Just for completeness given the title of the current issue, the situation is also the same for maxweight Vs maxweight:hgv. The hgv versions should be considered only as further restrictions on top of maxweight/maxweightrating. Thanks

**Comment by yuriiurshuliak** [comment]
The bug has been fixed. Using the truck profile with the specified vehicle parameters for navigation, the route is built correctly. The route calculation now appropriately considers the "maxweight" tag.

You can also view the route in the web version at this link: https://test.osmand.net/map/?start=47.515433,0.128428&finish=47.499131,0.103802&type=osmand&profile=truck&params=truck,weight:39.99,height:3.99,length:11.99,width:2.49#14/47.5113/0.0954

OsmAnd~ 4.6.0#1007m, released: 2023-11-10

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/35c8b315-9766-4b0b-9443-0fb52c5bb536"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/0b76531d-3d93-402a-83c1-25f5b70c9209"  width="700" height="auto"/> </th>
  </tr>
</table>
