### ISSUE TITLE
ajdust noise cancelling according to position

### ISSUE THREAD

**Issue by spykyvenator** [osmandapp/OsmAnd#18301]
### Describe the idea (required)

I had this Idea of turning off noise-cancelling off when for example near a crossroad or for example when you are close to make a maneuver for using this app when walking/cycling.
You could turn off noise-cancelling/lower volume/enable audio pass trough on nc headphones in these situations, and I think it would be a cool feature that might give an edge over other (proprietary) map apps.

### Tell us about the expected behaviour (required)

When your gps location is in a certain radius of a crossroad or you are close to maneuvering you can now hear traffic around you and are more aware of your surroundings because of it.
This should be configurable, not being able to turn this off could be annoying.

### Tell us about alternatives you've considered (required)

none, I don't think this exists anywhere?

**Comment by fillwithjoy1** [comment]
ngl, this doesn't replace common sense. You should not always rely on an app to do this. Just take your headphones on and cross, it's that simple

**Comment by scaidermern** [comment]
You should never use headphones in such a way that you can't hear your surrounding traffic anymore. What about emergency vehicles and similar cases? Please stop doing stupid and/or dangerous things in traffic.

**Comment by fillwithjoy1** [comment]
> You should never use headphones in such a way that you can't hear your surrounding traffic anymore. What about emergency vehicles and similar cases? Please stop doing stupid and/or dangerous things in traffic.

thank god somebody else here actually realizes the stupidity of this issue :D
