### ISSUE TITLE
Offline Routing: maxheight not supported yet?

### ISSUE THREAD

**Issue by CJTmmr** [osmandapp/Osmand#1830]
Hello,

I am driving a minibus, Height = 2.6 m
In Navigation Settings I can specify a Height Limit. It is set to 3.0 m (to be sure..)
But still OsmAnd Offline Routing uses tunnels/roads with maxheight=2.2 of lower.

Example: [this tunnel](http://www.openstreetmap.org/way/7423385#map=18/52.05556/4.64823) in Waddinxveen Netherlands; tagged with maxheight=2.2

This is a screenshot, made with latest nightly:
![2015-10-24 12 46 27](https://cloud.githubusercontent.com/assets/15076257/10710548/456e6fa8-7a5f-11e5-9cb3-eeeb778623dc.png)
where OsmAnd lets me use this tunnel.

In routing.xml  maxheight and maxweight are used in the "acces"-section:
```javascript
<select value="-1" t="maxweight">
				<gt value1=":weight" value2="$maxweight" type="weight"/>
			</select>
			<select value="-1" t="maxheight">
				<gt value1=":height" value2="$maxheight" type="length"/>
			</select>
```
but this is not yet functional??

The Weight-Limit is not used as well, I think

I would be very usefull though.

Thanks

CJTmmr

**Comment by vshcherb** [comment]
I specified height 2.5 m in settings and I've got a different route.https://www.dropbox.com/s/zo8684g62efesjo/Screenshot%202015-11-08%2000.14.28.png?dl=0

**Comment by vshcherb** [comment]
Issue double checked and indeed it is not working for Native routing.

**Comment by CJTmmr** [comment]
I can confirm this.  In general settings:  Safe mode, uses android code.
Then heigth limit is taken into account,  but route calculation is indeed
much slower. Both on 2.1.1 and nightly

CJ
Op 8 nov. 2015 00:39 schreef "vshcherb" <notifications@github.com>:

**Comment by pl71** [comment]
OsmAnd 2.2.3 offline routing also do not obey `hgv=no` when profile is set to 'Truck'

**Comment by vshcherb** [comment]
>> hgv-no
Good point, thanks.

**Comment by martenjj** [comment]
Confirmed with OsmAnd+ 2.2.4.  Another test case:

![route](https://cloud.githubusercontent.com/assets/10631760/12552442/c17f592e-c369-11e5-9fbb-e6dba659a1e7.png)

Navigation maximum height is set to 3.5m, but the tunnel (OSM way 48804407) has maxheight=2.2

**Comment by martenjj** [comment]
Also confirmed that in "Safe mode" it correctly avoids the tunnel.

**Comment by vshcherb** [comment]
Finally fixed, easy fix. https://github.com/osmandapp/OsmAnd-core/commit/3e40f748893b5f097bf1d9be56097cf0946444f2

**Comment by xmd5a2** [comment]
Test added

**Comment by CJTmmr** [comment]
I looks like all highways tagged with maxheight=default are now impassable
for routing; no matter what height is set in settings

Op 5 aug. 2016 21:40 schreef "xmd5a" <notifications@github.com>:

**Comment by vshcherb** [comment]
@CJTmmr 
Any information? It is impassable to any value of height setting or it is still passable for default "0" ("-").

**Comment by CJTmmr** [comment]
For example this road,  with tag maxheight = default,
http://www.openstreetmap.org/way/37263023#map=18/52.02976/4.68347&layers=D

Even with heigth set to " - "(car profile, navigation settings) no routing
via this road

Op 7 aug. 2016 21:31 schreef "vshcherb" <notifications@github.com>:

@CJTmmr <https://github.com/CJTmmr>
Any information? It is impassable to any value of height setting or it is
still passable for default "0" ("-").

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/osmandapp/Osmand/issues/1830#issuecomment-238103076>,
or mute the thread

**Comment by vshcherb** [comment]
Fixed

**Comment by CJTmmr** [comment]
Latest nightly fixed this. See also #2922 
When I have opportunity I will do more tests - also with max-weight!

Thanks- this is a great improvement!

One small issue left:
After changing the height in navigation settings, the route is not recalculated automatically.
You have to cancel the current route and start navigation again.
