### ISSUE TITLE
latest nightly releases are very slow at app start (15-20 seconds until map is displayed)

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#18311]
### Description

Since a few releases the nightly´s are very slow at start, 

For about 10-15 seconds I see this:
![Screenshot_20231009_144755_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/95540936/5787e03b-b6bd-4e6c-b5a4-0433a8d5873b)
Then for another about 5-10 seconds I see this:
![Screenshot_20231009_144805_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/95540936/a18806f1-e0fd-4a83-8f93-fc26e64405f2)
before finally the map is displayed. 
Then everything seems to run like always.

Did a complete clean install already (switching off Androids backup functionality!), so no data at all was restored and only one map (lower austria) is installed. No tracks, no favorites, nothing.

Here´s the logfile, perhaps it helps?
[logcat.log](https://github.com/osmandapp/OsmAnd/files/12846330/logcat.log)

On the same device I have the free 4.5.10 running, which starts up in about 3 seconds until map.
On my other device I have the +4.6.2 and also the free 4.5.10 running, both start up very quick (3 seconds) with tons of maps, hillshades, favorites and tracks. All installs are in "ext. memory 1" (Android/data/...) Open GL.

This began a few releases ago, don´t know exactly when...

### Steps to reproduce

don´t know...

### Actual result

slow start 

### Expected result

quick start

### Your Environment (required)

OsmAnd Version: 4.6.0#847m
Android/iOS version: 13
Device model: S20+

**Comment by Nine-Tailed** [comment]
similar problem https://github.com/osmandapp/OsmAnd/issues/18168

**Comment by Dollarius** [comment]
I am experiencing the same problem since a few release: it takes about 15s for the app to start.
I just discovered that if navigation is running, the app start is much quicker (2-3s), which is a comparable starting time to the older releases.
Maybe a hint on fixing the unsolved issues https://github.com/osmandapp/OsmAnd/issues/18311 and https://github.com/osmandapp/OsmAnd/issues/18168 ?
This should possibly be reopened?

2023-10-24 OpenGL on Android 13, Samsung Galaxy S23

**Comment by vshcherb** [comment]
> I just discovered that if navigation is running, the app start is much quicker (2-3s),

App is  not starting during navigation, cause it was running in background anyway.

**Comment by Rowin63** [comment]
It became noticeable worse with the last few releases (~4.7.0#1528m). Map is built (slow) as usual, but now it takes almost two minutes until favourites and tracks are displayed in "my places" (it starts with an empty page at the "import" dialoge for some time).

**Comment by Rowin63** [comment]
De-installed the getting slower and slower nightly.
Installed the regular +4.7.0 on that device (had to delete all data too, was not possible to install when keeping the data) and it runs smooth as expected (including the same amount of maps/tracks/favorites/... like before).
 
Installed the nightly on another device, runs smooth too (also including the same data).

The only thing: 
Osmand crashed a few times on importing the exported data from the previous installation (hat split it to three files, sources/places/settings - containing no map data/contour lines/wikis). But still, if the backup file is too large (like my tracks folder), Osmand crashes on importing. Had to import it in several steps, one by one section. Needed a few tries to succeed.

The problem (getting slower and slower) probably just needed a fresh install.

**Comment by yuriiurshuliak** [comment]
In order for us to be able to better investigate this crash issue, please provide us with step-by-step instructions, the file size during the import process, and the associated crash logs.
