### ISSUE TITLE
OsMo plugin no longer working

### ISSUE THREAD

**Issue by 9662** [osmandapp/Osmand#1831]
Using OsmAnd~ 2.1.1 on two phones, it does not appear that one is able to share locations via OsMo.

When entering the other device's tracker ID, a toast message appears, saying: "OsMo Connection Problem: 300 Deprecated".

Regenerating the ID does not help, and I no longer appear to be able to view a tracker's position on the OsMo website, so I've no idea whether it is a sending or receiving problem.

**Comment by GaMsh** [comment]
Hi! Please using the groups instead!

**Comment by 9662** [comment]
Hello! Does this mean that the ability to share positions anonymously and without registration will no longer be available?

**Comment by 9662** [comment]
I actually just saw the OsMo notification that says:

> The subscription system device to device is no longer available. Please use the private group to exchange the coordinates.

@GaMsh, could you please clarify whether that functionality is planned to be reintroduced in the future? Thanks a lot!

**Comment by GaMsh** [comment]
> Hello! Does this mean that the ability to share positions anonymously and without registration will no longer be available?

You can see shared positions via session URL. But in osmand - no, only with groups. To create group you need be register, but to enter group - no.

**Comment by GaMsh** [comment]
> I actually just saw the OsMo notification that says:
>
>>The subscription system device to device is no longer available. Please use the private group to exchange the coordinates.
>@GaMsh, could you please clarify whether that functionality is planned to be reintroduced in the future? Thanks a lot!

No, it won't be.
Please use group - it is much more convenient and powerful tool for sharing location. While registration is required only to the one who created the group, and takes less than a minute.

**Comment by 9662** [comment]
Ok, cheers. :)

**Comment by GaMsh** [comment]
In future we may be enable creating simple little group without registration =)
