### ISSUE TITLE
Checking details of a POI leads to Zoom 17, which is a white map

### ISSUE THREAD

**Issue by Dollarius** [osmandapp/OsmAnd#18328]
### Description

The app automatically zooms "fully in" when checking the details of a POI, leading to an empty map (inexistent data at such zoom level)

### Steps to reproduce

1. Start OsmAnd
2. Click on any POI (i.e., mountain summit, campsite)
3. Click on the POI description to open the extra details
4. Observe the map becoming "white" because going to Zoom 17
5. The same behaviour (Zoom to 17) is achieved when sliding up from the POI description, so to enlarge it to read the additional details

### Actual result

https://github.com/osmandapp/OsmAnd/assets/56419637/01ef96e0-a4d5-4d76-8488-763b8fb551f3

### Expected result

It may be desirable to keep the zoom unchanged upon clicking on the POI details.
Alternatively, the zoom level could be smaller than 17 (i.e., 15, 16?)

On a different regard, is "Zoom 17 = white" a different bug by itself?

### Your Environment (required)

```
OsmAnd Version: 4.6.0#857m, released 2023-10-11
Android/iOS version: Android 13
Device model: Samsung Galaxy S23 SM-S911B/DS
```

**Comment by scaidermern** [comment]
Probably related to various issues around #17763.

**Comment by DmitryAlexei** [comment]
White map when close zooming in mountainous regions when 3d is enabled is a known issue. Work is already underway. See https://github.com/osmandapp/OsmAnd/issues/17763 and https://github.com/osmandapp/OsmAnd/issues/18253

**Comment by vshcherb** [comment]
Needs to be tested on latest version

**Comment by zipav** [comment]
OsmAnd Nightly 4.6.0#881m, released: 2023-10-17


https://github.com/osmandapp/OsmAnd/assets/123936521/2ed7fa84-bdc3-4599-a651-1944716c9b07

**Comment by DmitryAlexei** [comment]
camera don't go underground any more.

**Comment by Dollarius** [comment]
Works in the latest release -> closing the issue.
Thanks for fixing it!
