### ISSUE TITLE
Instructions (voice, visual) mismatch - how best to report these mismatches?

### ISSUE THREAD

**Issue by Simplenuity** [osmandapp/OsmAnd#18333]
Similar to discussion below I'm also coming across these mismatches between voice prompt and visual route on the map from time to time.

What is the most efficient way for the developers to receive these error reports?

* Opening an issue here on GitHub for each instance of mismatch
* Adding a note to the map via web interface
* other method

### Discussed in https://github.com/osmandapp/OsmAnd/discussions/11356

<div type='discussions-op-text'>

<sup>Originally posted by **Tukcedo** April  6, 2021</sup>
Hi All!

I'm a relatively new user, but I noticed something odd during navigation. When I create my own route by adding and dragging waypoints onto the map, there seems to be a mismatch between the voice and visual instructions to the point where the instructions seem totally unrelated (or at the very least, not synchronised) to the actual route shown on the map. I have "car" selected and during the track creation process, the route is properly following the roads after I add a waypoint, resulting in a route map that is (largely, see below) correct. 

- However, while driving I often get the instruction to go right whereas the map (correctly) shows a left or I'm asked to turn into some non-existing road. Not surprisingly, the instructions often use the wrong street name, whereas the map is correct. 
- The time needed to complete the route is way off: for something like 80k (again, for a car) it will start off with something like 40 hours but getting a little closer to something more realistic as we progress along the route
- Often, there seem to be points the navigation wants to go to that are maybe 100m or so off the route, in which case even the map shows these spurious "detours". Most often these occur in intersections like T-junctions. So navigating on the map, they're easy enough to avoid as you can usually see where the correct route goes.

Strangely enough, routes that I download (I've tried primarily those from the web site of the Dutch tourist organisation ANWB) seem to do much better at these things than the routes I create myself.

Am I doing something wrong? Are there any settings I need to change?

Thanks!

Mich.

Tablet: Samsung Tab A (SM-P550), Android v7.1.1, kernel 3.10.49-13808168
OsmAnd: 3.9.10 (free)
</div>

**Comment by DmitryAlexei** [comment]
@Simplenuity Please update OsmAnd to the latest version.
4.5.10 is available in Google Play

Some issues have been fixed in https://github.com/osmandapp/OsmAnd/issues/17376 also see https://github.com/osmandapp/OsmAnd/issues?q=label%3Aturn-lanes+is%3Aclosed

**Comment by DmitryAlexei** [comment]
@Simplenuity In the F-droid app you can find OsmAnd 4.5.10 already. So if you refer to 3.9.10 version, it is very outdated and needs to be upgraded. 
Some issues with roundabouts and live updates have been already resolved, so, please, best of all try beta 4.6 from Google play and see if it is working well for you.

**Comment by DmitryAlexei** [comment]
@Simplenuity Issues like that you can report here, on Github. That's exactly what this platform is for.

As for this error. Tried to reproduce with OsmAnd~ 4.6.0#866m, released: 2023-10-12
- driving region set to Australia
- downloaded fresh map of Western Australia
- starting point -32.4239697, 115.7666074 , end point is set after roundabout

Actual result:
- exit number is displayed # 2 as expected



<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/26bd593b-2526-49ea-8603-8eba7012d694"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
You can also try to update your map
If this not works, you can wait for the next release

**Comment by DmitryAlexei** [comment]
You can check this [roundabout](https://www.openstreetmap.org/way/176052215) on openstreetmap.com, and see, that it is connected only with [Warnbro Sound Avenue](https://www.openstreetmap.org/relation/16400360). [Service road](https://www.openstreetmap.org/way/200278068) is also connected with Warnbro Sound Avenue, but before the roundabout.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/4fe019c3-e279-457d-b784-15b54aa3fce8"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/a7657bc3-b5fa-40d6-8c0b-99281c6e868a"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
OsmAnd uses Openstreetmap data for navigation and when displaying maps. 
As you can see in that service road description, it was created 10 years ago and this info may be outdated. 
The best way is to check this road "on the ground" and change it in Openstreetmap, thus everybody will use correct road.
<img width="591" alt="Screenshot 2023-10-16 133458" src="https://github.com/osmandapp/OsmAnd/assets/116079541/30a16c38-cdd3-46ad-b47d-1349c70fa1c5">

**Comment by DmitryAlexei** [comment]
@Simplenuity you are completely right
