### ISSUE TITLE
Missing time data for created or imported tracks

### ISSUE THREAD

**Issue by Ludovico84** [osmandapp/OsmAnd#18337]
### Description

Good morning, I am writing to you to understand if there is some bug with Osmand or if there is some function to activate.

I found the application splendid and full of all the features necessary to undertake an outdoor activity.

I tried importing some of my gpx tracks and they correctly show elevation gain, slope and route length. However, what seems to be missing in all of them is travel time. The clock icon tells me 00:00 for all the tracks, and it seems strange to me that such an important data is missing.

I tried importing at least 9 tracks and the result is always the same. Trying to create the route directly from the application, setting the "walking" profile, identical problem.

### Steps to reproduce

The bug occurs following these operations:

1) Open the OsmAnd application.

2) Press the three lines at the bottom left and enter the menu.

3) Press Plan a route.

4) Create a route using the walking profile, then press save.

5) Return to the menu and press "my places"

6) Once pressed, you will see a summary of the route and the time will be 00:00

The same procedure is possible by importing the track. To do this instead of creating it, just press plan a route and then import track

### Actual result

The route time will be 00:00

### Expected result

See the estimated time to travel the tracks

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.6.2
Android/iOS version: Android 13
Device model: Samsung S20
Crash-Logs: ?
```

**Comment by DmitryAlexei** [comment]
Information about time in motion can only be provided when track has not only track line but also track points (see https://osmand.net/docs/technical/osmand-file-formats/osmand-gpx#details-of-a-track-point-trkpt). So recorded in OsmAnd tracks have info about time. However, created and some imported tracks haven't got this information because they don't have track points.

<table style="width:100%">
  <tr>
    <th>Recorded tracks</th>
    <th>Imported tracks</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/da98cb82-2409-4710-957d-f1edf9d94745"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/33effbe9-39fe-4b60-b749-16977b23c1b5"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Ludovico84** [comment]
Dear Dmitri, thank you for your reply.

So it's not possible to have a time estimate of the imported track or create without recording through navigation?

With other map applications this is possible, and the data is provided while the route is created.

It seems strange to me that this feature is missing from such a complete and well-made app

**Comment by DmitryAlexei** [comment]
@Ludovico84 OsmAnd provides time estimate for tracks, recorded in other apps.
As tracks can be used with different profiles (e.g. driving, walking etc.) estimated time seems to be not very useful.
However, you can obtain this information in navigation mode (see https://osmand.net/docs/user/navigation/setup/gpx-navigation)

**Comment by Ludovico84** [comment]
Thank You for support Dmitry

**Comment by scaidermern** [comment]
Sounds like a bug to me.

A track created in OsmAnd with the "Plan a route" tool should have a duration time if it was created within a specific profile. When planning a route, the user not only wants to see the distance but also the travel time. This is a really basic feature that should be present.

**Comment by vshcherb** [comment]
Nope the travel time is characteristic only for recorded tracks, in case you want to make a collection of "planned routes" and see stats for "planned travel" it should be said explicitly and don't raise confusion i.e. specify by which routing profile time is measured. So this feature was never implemented

**Comment by scaidermern** [comment]
> don't raise confusion i.e. specify by which routing profile time is measured. So this feature was never implemented

Well, a track planned by OsmAnd is always for a specific routing profile. You can't plan a track in foot mode and then expect it to work in car mode. So why not include a time? If a user plans a route, it is expected to have a distance and an estimated time. Which popular route planning tool omits the time?

**Comment by vshcherb** [comment]
We're about statistics not about that you are not able to see duration. 
My point - that duration for recorded tracks immediately helps to understand how much you've spent time recording these tracks. 
Whether **duration of total planned tracks** doesn't mean any valuable information.

However I read about the issue again and I think it's not about the Total sum and it's about individual tracks. So in that case I think we should display duration, distance and small icon of routing profile but I'm not sure if that fits

**Comment by vshcherb** [comment]
We can potentially display duration if track has following section (segmentTime):
```
   <osmand:route>
          <segment id="839981740" length="4" startTrkptIdx="0" segmentTime="104.29" speed="1.39" turnType="C" types="0,1,2,3" pointTypes=";;;" />
          <segment id="839981740" length="2" startTrkptIdx="3" segmentTime="35.29" speed="1.39" turnType="KL" turnLanes="+C|C" turnAngle="-0.07" types="0,1,2,3" pointTypes="4,5;" />
          <segment id="839981740" length="2" startTrkptIdx="4" segmentTime="3.68" speed="1.39" turnType="TSLR" turnLanes="C|+TSLR" turnAngle="-21.55" types="0,1,2,3" pointTypes=";" />
          <segment id="139526199" length="3" startTrkptIdx="5" segmentTime="48.92" speed="0.38" turnType="TSLR" turnLanes="+TSLR" turnAngle="111.96" types="1,2,6,7" pointTypes="12;8,9,10,11;" />
```

**Comment by dmpr0** [comment]
# Review 
Task is not complete. Time data is displaying only in the track list, why it missed on other screens?
Task should be moved To Design.

**Comment by vshcherb** [comment]
I think we shouldn't display duration / time in Track context menu and other places cause that's not **a recorded track**. Unless we don't have a specific user request I suggest to consider it's done

**Comment by scaidermern** [comment]
> I think we shouldn't display duration / time in Track context menu and other places cause that's not **a recorded track**. Unless we don't have a specific user request I suggest to consider it's done

Isn't exactly this ticket already a user request to display time data for imported tracks? :thinking:

**Comment by vshcherb** [comment]
Yes user requested to display in My places and now it's displayed
