### ISSUE TITLE
gpx track not shown after import unless i change colour

### ISSUE THREAD

**Issue by plicplocplicploc** [osmandapp/OsmAnd#18330]
### Description

When I import a GPX track into OsmAnd, the track wont' be shown initially, until I modify its colour.

### Steps to reproduce

Have a GPX track ready on phone. Open the track with OsmAnd.
Track won't show on the map.
Track will show after I modify its colour.

### Actual result

Track is not shown.

### Expected result

Track should be shown.

### Your Environment (required)

```
OsmAnd Version: 4.5.10 (OsmAnd~ f-droid)
Android/iOS version: LineageOS 20
Device model: Pixel 6a
Crash-Logs: ?
```

**Comment by DmitryAlexei** [comment]
@plicplocplicploc Cannot reproduce. Please attach short video of your issue and your track and profile settings (menu > settings > your profile > export profile)

**Comment by plicplocplicploc** [comment]
Sincere apologies, this actually seems to work as intended. Sorry for the noise.
