### ISSUE TITLE
Keystrokes "c" and "d" ignored landscape

### ISSUE THREAD

**Issue by Brente88** [osmandapp/OsmAnd#18347]
### Description

Hi,
Boundary conditions:
Osmand beta
Ble keyboard connected

Once the app is started with the standard profile with vertical screen orientation, when the profile is switched to a one with landscape orientation, the keystrokes "c" and "d" are ignored.

So it's impossible to orientate the map and centering the map.

If the app starts as preferred profile a "landscape" profile, the keystrokes works properly.

This situation has been reported also on the 9th August update

### Steps to reproduce

Boundary conditions:
* OsmAnd beta
* BLE keyboard connected
* Standard profile with vertical orientation
* Switch to a profile with landscape orientation

### Actual result

Keystrokes `c` and `d` ignored

### Expected result

Keystrokes `c` and `d` should work for all conditions

**Comment by DmitryAlexei** [comment]
Unfortunately, we have to close the investigation of this issue due to lack of information. It was not possible to reproduce it.
