### ISSUE TITLE
Attach to the roads option works improperly with OsmAnd track

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd#18343]
### Description

Previously created in OsmAnd track (was exported via Route details > send as file) shows straight line after attaching it to the roads.

### Steps to reproduce

- import provided GPX file (added .txt extension, simply delete it) into OsmAnd
- in context menu of that track tap on navigation button
- in navigation menu tap "Attach to the roads" 

[track.gpx.txt](https://github.com/osmandapp/OsmAnd/files/12894111/2_5278265728745615672.gpx.txt)

### Actual result

- after being attached, route line becomes straight. See video

https://github.com/osmandapp/OsmAnd/assets/116079541/1ac76423-2f8f-4523-9c22-272fb0859da8

### Expected result

- route line suitable for navigation

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd~ 4.6.0#866m, released: 2023-10-12
Android/iOS version: 13
Device model:
Crash-Logs: ?
```

**Comment by martyatvtti** [comment]
I am seeing the same issue with a few routes I created.

**Comment by martyatvtti** [comment]
I found a workaround for others having the same issue. You convert your gpx file into a kml [here](https://kml2gpx.com/). Take this kml into Google Earth (online version will do) and delete everything except the Track folder from the resulting item in Google Earth. Re-export as kml then covert back to gpx via the same service you converted from gpx. Import this file into OsmAnd as a new route and things should work as expected. I believe this works by creating many more points to route through.

**Comment by vshcherb** [comment]
We need to check if problem is Android or Core (Reproducible in MapCreator)

**Comment by RZR-UA** [comment]
Reproduced in:

**4.6.0 release - PROBLEM
4.6.11 release - PROBLEM
OsmAnd-default-nb-2024-01-16.apk - PROBLEM**

OsmAndMapCreator warns "GPX route correction - Check validity of GPX File".

Used Lithuania Standard Map, Car profile, and GPX attach to roads with default settings

![osmand](https://github.com/osmandapp/OsmAnd/assets/90444451/70a569ad-a87e-4e2f-bab8-44ac66403c3c)

![mapcreator](https://github.com/osmandapp/OsmAnd/assets/90444451/8989eaed-0671-4acf-9978-e3fd174633e0)
