### ISSUE TITLE
Add support for tags: author, cmt, link, keywords, copyright, email

### ISSUE THREAD

**Issue by ceever** [osmandapp/OsmAnd#18342]
### Description

No matter how I import a gpx file into OsmAnd, I am not able to leverage the <url> or <urlname> tags if they are present. As far as I understand, OsmAnd even drops this information when importing the GPX.

But url and urlname are part of the standard specification of gpx, so I think they should really be supported natively. And as the user of #14618 wrote: A link "can allow the user to open the link retrieving more information about this point and maybe adding some custom workflow (for example triggering a web page with more information and logic regarding the reached point)"

### Steps to reproduce

Create a simple gpx file like this:
```
<?xml version='1.0' encoding='UTF-8' standalone='yes' ?><gpx version="1.1" creator="Mundraub2Use Script" xmlns="http://www.topografix.com/GPX/1/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
<name>Rider Houses</name>
<wpt lat="43.94073" lon="141.650913">
<name>Rider House 346</name>
<url>https://www.hatinosu.net/house/archives/346</url>
<urlname>Rider House 346</urlname>
</wpt>
<wpt lat="43.322306" lon="145.632708">
<name>Rider House 349</name>
<url>https://www.hatinosu.net/house/archives/349</url>
<urlname>Rider House 349</urlname>
</wpt>
</gpx>
```

Import it into OsmAnd and see how url is drop, by opening the imported file. Or put the file into the tracks folder of OsmAnd and see how no url information is available when selection the waypoints in the map.

### Actual result

No url anywhere.

### Expected result

Somehow the url should be displayed and also not be deleted from the gpx.

### Your Environment (required)

```
OsmAnd Version: 4.5.10
Android/iOS version: 9
Device model: Sansung S8
```

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#871m, released: 2023-10-13
- try to import [favorites-3.gpx.txt](https://github.com/osmandapp/OsmAnd/files/12916975/favorites-3.gpx.txt) (simply delete .txt extention) as .gpx file
- open this track (it consists of only one waypoint) and see if url is present in context menu of this waypoint (open track > points tab > waypoint)

https://github.com/osmandapp/OsmAnd/assets/116079541/ee291003-3e18-434a-99f7-bdf9e950de47

**Comment by ceever** [comment]
Thanks for the proposal.

However, this is not what #14618 and I are talking about. Your example is an OsmAnd specific solution using <extension>, which is not helpful when working with other apps and geo tools. We are talking about the standard gpx definition: https://www.topografix.com/gpx_manual.asp that natively should support <url> and <urlname>. But OsmAnd actually seems to actively drop these tags, even though they are defined as standard.

**Comment by ceever** [comment]
But, I mean since it is essentially already implemented within \<extension\> (also works if importing as Favourite), it shouldn't be hard to also include \<url\> of \<gpx\> in the option to deliver an url.

Just that weird removal of \<url\> by OsmAnd should be dropped.

**Comment by DmitryAlexei** [comment]
@ceever please add a link(s) to documentation
it is not clear, why are you speaking about `<url>` and not a `<link>` (or whatever else) tag
what is most common implementation of this feature in other apps? (i.e. which tags other apps support?)

**Comment by ceever** [comment]
The link to the mentioned documentation of GPX is in my comment before. They decided for "url" instead of "link", c'est la vie. I mean what does that even matter? Would that impact the impementation in any way, it is just a word?

**Comment by DmitryAlexei** [comment]
@ceever provided link refers to gpx 1.0 schema, and in the beginning of this document it is stated, that this schema is outdated. 
According to OsmAnd technical documentation, it uses gpx 1.1 schema (see https://osmand.net/docs/technical/osmand-file-formats/osmand-gpx)
In gpx 1.1 technical documentation it is proposed to use different tags for urls (see https://www.topografix.com/GPX/1/1/#type_linkType). However, as I know, this solution looks a bit complicated, and it is not commonly used. Custom extensions are used instead.

<img width="549" alt="Screenshot 2023-10-19 141414" src="https://github.com/osmandapp/OsmAnd/assets/116079541/cc4cfabd-8833-4311-859f-8806f73e449d">

**Comment by ceever** [comment]
I don't think it is very complicated, that's just the way it is documented, which is a little cumbersome, I have to admit. But anyhow.

I mean if one implements support for a certain file format (GPX), one covers the standards of the file format first to be compatible with other applications, right? I mean it's great that there are these numerous OsmAnd extensions (osmand:color ... etc). But of what use are they as soon as I move out of the OsmAnd universe? Unless, of course, you intentionally wanted to produce incompatibilities and lock users in. But why bother using GPX then in the first place?

Wouldn't a proper implementation be to use the existing standards and always fall back onto it if possible, and only if it goes beyond the standard, one relies on the extension part?

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#1037m, released: 2023-11-16

**Steps to reproduce**
- based on .gpx file provided above, created a file that seems to meet the requirements of the 1.1 GPX standard. 
[gpx_with_link.gpx.txt](https://github.com/osmandapp/OsmAnd/files/13394878/gpx_with_link.gpx.txt)
- imported this and 8 other variants of that .gpx file into OsmAnd trying to see link in the *Track context menu*

```

<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<gpx version="1.1" creator="Mundraub2Use Script" xmlns="http://www.topografix.com/GPX/1/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
  <metadata>
    <link href="https://www.hatinosu.net/house/archives/346">
      <text>Rider House 346</text>
    </link>
  </metadata>
  <wpt lat="43.94073" lon="141.650913">
    <name>Rider House 346</name>
  </wpt>
  <wpt lat="43.322306" lon="145.632708">
    <name>Rider House 349</name>
  </wpt>
</gpx>

```
**Actual result:**
- lthe link is not displayed in the *Track context menu* (see screenshot)
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/d3577fb7-b667-4ecb-a4db-72001a9741d2"  width="300" height="auto"/> </td>
  </tr>
</table>

**Expected result:**
- the link is displayed in the *Track context menu*, when you tap, you are redirected to the corresponding resource
- probably it is also possible to copy it to the clipboard

**Comment by vshcherb** [comment]
@DmitryAlexei please test original gpx with waypoints extra info this looks as a separate issue

**Comment by ceever** [comment]
> OsmAnd~ 4.6.0#1037m, released: 2023-11-16
> 
> **Steps to reproduce**
> 
> * based on .gpx file provided above, created a file that seems to meet the requirements of the 1.1 GPX standard.
>   [gpx_with_link.gpx.txt](https://github.com/osmandapp/OsmAnd/files/13394878/gpx_with_link.gpx.txt)
> * imported this and 8 other variants of that .gpx file into OsmAnd trying to see link in the _Track context menu_
> 
> ```
> 
> <?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
> <gpx version="1.1" creator="Mundraub2Use Script" xmlns="http://www.topografix.com/GPX/1/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
>   <metadata>
>     <link href="https://www.hatinosu.net/house/archives/346">
>       <text>Rider House 346</text>
>     </link>
>   </metadata>
>   <wpt lat="43.94073" lon="141.650913">
>     <name>Rider House 346</name>
>   </wpt>
>   <wpt lat="43.322306" lon="145.632708">
>     <name>Rider House 349</name>
>   </wpt>
> </gpx>
> ```
> 
> **Actual result:**
> 
> * lthe link is not displayed in the _Track context menu_ (see screenshot)
> 
> <img alt="" width="300" height="auto" src="https://user-images.githubusercontent.com/116079541/283882676-d3577fb7-b667-4ecb-a4db-72001a9741d2.jpg">
> **Expected result:**
> 
> * the link is displayed in the _Track context menu_, when you tap it, you are redirected to the corresponding resource
> * probably it is also possible to copy it to the clipboard

Yes, that's not the issue I am talking about. The link is supposed to be part of the way point ... POIs with websites as addition.

Here the proper example:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<gpx version="1.1" creator="Mundraub2Use Script" xmlns="http://www.topografix.com/GPX/1/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
  <wpt lat="43.94073" lon="141.650913">
    <name>Rider House 346</name>
    <link href="https://www.hatinosu.net/house/archives/346">
      <text>Rider House 346</text>
    </link>
  </wpt>
  <wpt lat="43.322306" lon="145.632708">
    <name>Rider House 349</name>
    <link href="https://www.hatinosu.net/house/archives/3469">
      <text>Rider House 349</text>
    </link>
  </wpt>
</gpx>
</code>
```
Here the gpx:
[gpx_with_POIs_with_link.gpx.txt](https://github.com/osmandapp/OsmAnd/files/13402495/gpx_with_POIs_with_link.gpx.txt)

**Comment by zipav** [comment]
OsmAnd Nightly 4.6.0#1078m, released: 2023-11-22
Nokia 5.3
Android 12


When importing a track using OsmAnd, the import fails, the application freezes. When trying to import using the device file manager, there is no URL in the description.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/008da43c-2336-4350-a57f-1ad5cdc4d199"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by zipav** [comment]
OsmAnd Nightly 4.6.0#1078m, released: 2023-11-22


<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/35b18673-2e88-487c-9f46-3ac8e17cc79f"  width="300" height="auto"/> </td>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/d7c5ee49-e2ed-486c-a77d-cec2299b40c6"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
To do: 
- Links and all other tags should be displayed in Track Context menu
- Links and all other tags should be displayed in Waypoint Track Context menu

**Comment by Chumva** [comment]
Do not show `bounds`

**Comment by vshcherb** [comment]
Display all that inside that file
[gpx_with_link.gpx.zip](https://github.com/osmandapp/OsmAnd/files/13649602/gpx_with_link.gpx.zip)

**Comment by Chumva** [comment]
file with fixed author and copyright tags - [gpx_with_link.zip](https://github.com/osmandapp/OsmAnd/files/14025702/gpx_with_link.zip)

**Comment by dmpr0** [comment]
## Review 
**General**
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/5db800c2-8952-482b-8ae3-0e33653448cf"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] **Created on**, icon – ic_action_date_start
- [ ] **Size**, icon – `ic_sdcard`
- [ ] **Location**, icon – `ic_action_folder`

**Info**

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/7b23229c-9091-4534-98a8-e39a85dd5c02"  width="300" height="auto"/> </td>
  </tr>
</table> 

- [ ] **Activity**, icon = activity icon
- [ ] **Keywords**, icon – `ic_action_label`
- [ ] **Link**
- - [ ] Icon – `ic_action_link`
- - [ ] Color – active
- - [ ] Tap should open link in Chrome tabs

**Comment by dmpr0** [comment]
# Review 2

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/5ec9b8cf-e61b-4e5c-82a7-a910dbe03685"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [ ] License should be work as link

- - -

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/781b9a42-c802-48a9-a355-17d7d47fe9d4"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>  

- [ ] Display first symbol of custom tag name as uppercase.
* * address > Address
* * icon > Icon

**Comment by dmpr0** [comment]
# Review 3
**Copyright**
- [ ] Rename **Name** to **Author** on UI

**Comment by EugeneZmeuk** [comment]
**Review 29.03.2024**
- [ ] re-write this sections of Track Context menu [1](https://osmand.net/docs/user/map/track-context-menu#waypoint-format-description) and [2](https://osmand.net/docs/user/map/track-context-menu#display-custom-gpx-tags)
