### ISSUE TITLE
Offline Address Search: ability to search in all the active maps needed

### ISSUE THREAD

**Issue by Max1234-Ita** [osmandapp/Osmand#1834]
Dear sirs,
recently, I noticed that National map for my country (Italy) is no more available.
I think this is because the package has grown in size so that it cannot be easily  handled anymore, so I'll have download a set of regional maps to cover the territory, instead of one large package .

There is a big limitation in this solution: address searches can be made only on a certain map, which requires one to know exactly in what region is located the searched address. 

Until a few days ago, the problem was solved by using National Address lists, and it worked fine, unfortunately also address files have disappeared from the servers, so that searching for an address can be very difficult now (just an example: try searching for a village named "Valle Superiore" among all the 20 regional maps of Italy... without using Nominatim service, of course; personally, I believe that any user would resign soon)

I think that an alternative solution should be implemented if address files are not used anymore, such as extending offline address search to ALL the maps which are in "active" status in the device, or maybe locally build an address list from the ones included in installed maps.

Best regards,
Max - Italy

-

**Comment by vshcherb** [comment]
Duplicate to #1845
