### ISSUE TITLE
Weather widgets are not added to the top and bottom panels

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#18349]
### Description

Weather widgets are not added to the top and bottom panels

### Steps to reproduce

1. went to the screen settings
2. selected the top panel
3. went to the weather widgets and checked them
4. clicked the add button
but they weren't added

### Actual result

Weather widgets are not added to the top and bottom panels.

### Expected result

Weather widgets should be added to the top and bottom panels.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:OsmAnd~ 4.6.0#871m, Дата выпуска: 2023-10-13
Android/iOS version:13
Device model:поко ф3
Crash-Logs: ?
```

**Comment by dmpr0** [comment]
https://github.com/osmandapp/OsmAnd/pull/18354
