### ISSUE TITLE
Notifications stopped working

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#18350]
### Description

Notifications have stopped working and cannot be turned on.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/12549744/c120c721-995e-4ef8-8dde-ff257ffa28e4"  width="300" height="auto"/> </td>
  </tr>
</table>

### Steps to reproduce

Go to the application properties and try to enable notifications.

### Actual result

Notifications don't work

### Expected result

Notifications work

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:OsmAnd~ 4.6.0#871m, released: 2023-10-13
Android/iOS version:13
Device model:poco f3
Crash-Logs: ?
```

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#871m, released: 2023-10-13 **Reproduced**
- there is no more permission to send notifications in OsmAnd nightly settings
- when trip recording is active, there is no more notification in notification bar

<table style="width:100%">
  <tr>
    <th>OsmAnd from Google play </th>
    <th>OsmAnd Nightly </th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/3bd0bd8d-0e1c-4086-94a8-851c80798435"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/63db82c2-0b30-430c-8bc6-10d1bf4c1bed"  width="300" height="auto"/> </td>
  </tr>
</table>

<table style="width:100%">
  <tr>
    <th>OsmAnd from Google play trip recording notifications active </th>
    <th>OsmAnd Nightly no more notifications</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/f1e54d8c-1574-497b-a9f2-41be0428b8c6"  width="300" height="auto"/> </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/116079541/5c8e5dd2-151f-43af-9193-f77a217a754e"  width="200" height="auto"/></td>
  </tr>
</table>
