### ISSUE TITLE
File permission

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#18352]
### Description

The app has lost permission to access files.  Now you can move Osmand files only to internal memory, but not back.

### Steps to reproduce

Described above.

### Actual result

no permission

### Expected result

have permissions

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:OsmAnd~ 4.6.0#871m, Дата выпуска: 2023-10-13
Android/iOS version:13
Device model:poco f3
Crash-Logs: ?
```

**Comment by dmpr0** [comment]
https://github.com/osmandapp/OsmAnd/pull/18354

**Comment by vshcherb** [comment]
It's probably related to new Android version, so it's somehow expected

**Comment by Nine-Tailed** [comment]
> It's probably related to new Android version, so it's somehow expected

But my Android version has not changed for a long time, and the previous version of Osmand 4.5.10 does not have this problem.  Over the weekend, I discovered that notifications in Osmand had not been working for two months, and then I discovered that permission to access files had disappeared.

**Comment by vshcherb** [comment]
I have Android version 13 + Latest nightly build and I don't see any issue using Multi user storage 1 which I can access through System My files application

**Comment by Nine-Tailed** [comment]
I had Osmand installed in external storage and it worked, after I noticed that Osmand had lost permission to access files, I decided to conduct an experiment and transferred the data to internal storage.  But it doesn’t allow me to transfer it back anymore.

**Comment by Nine-Tailed** [comment]
Two permissions were missing in Osmand, I created an issue for both.  Because it caused notifications to disappear and problems accessing file storage locations.
![IMG_20231016_191553.jpg](https://github.com/osmandapp/OsmAnd/assets/12549744/5d8a7374-f36f-416e-9b3d-7d36a3b2920b)

**Comment by vshcherb** [comment]
Then issue probably needs to be merged together cause the change looks related
