### ISSUE TITLE
OsmAnd Cloud - delete account, wrong passcode will still delete everything (except account)

### ISSUE THREAD

**Issue by qwerfd2** [osmandapp/OsmAnd#18359]
### Description

Expected behavior: App notify user passcode incorrect and halt.

Actual behavior: All stored item is deleted, account deletion failed, user is logged out and can log back in.

Tested platform: Google Play and F-Droid.

### Steps to reproduce

Log in to account.
Setting - delete account.
Enter correct email address.
Enter arbitrary string and continue.

### Actual result

All stored items deleted, user logged out, account not deleted, user can log back in.

### Expected result

User denied account deletion since code does not match.

### Your Environment (required)

OsmAnd Version: 4.5.10
Android/iOS version: 10
Device model: SM-A5160
Crash-Logs: n/a

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce it, follow these steps:

- Navigate to Menu > Settings > OsmAnd Cloud > Gear icon in the upper right corner > Select "Delete account."
- Provide the email address associated with your OsmAnd Cloud account and click the "continue" button.
- In the subsequent field, you must input a one-time password sent to you via email. However, you can enter any four-digit combination and click "continue."
- Confirm the account deletion, and the progress bar will indicate successful completion.
- Then, you will be able to log in to the deleted account again, but please note that all your data will be permanently erased.

OsmAnd~ 4.6.0#892m, released: 2023-10-20

<table style="width:100%">
  </tr>
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/71140949-7914-4c7a-b552-53d29a6dd6e7"  width="300" height="auto"/>   </td>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/bb55f251-82bf-49e1-91d9-fada3db4046b"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by dmpr0** [comment]
# Review 
- [ ]  Previous one-time password can be used, check for the **last!**
