### ISSUE TITLE
3.5.8 crashes after a few second with SIGABRT

### ISSUE THREAD

**Issue by monochromec** [osmandapp/OsmAnd#18364]
### Description

Titles says it all

Crash dump is at https://gist.github.com/monochromec/ccd2a9a9eb8c75ece969b624a28bad25

OS is stock Android 13 running on an FP4, opengl is 2 (last info I got from the settings before the app crashed).

More than happy to provide additional info as required.

Doesn't seem to be related to https://github.com/osmandapp/OsmAnd/issues/16878... 

### Steps to reproduce

1. Open the app
2. Wait a few seconds

### Actual result

App crash

### Expected result

App working

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 3.5.8 
Android/iOS version: 13
Device model: FP4
Crash-Logs: see above
```

**Comment by dmpr0** [comment]
Hi! Did you try to update OsmAnd to the latest version? 3.5 was released almost two years ago.

**Comment by scaidermern** [comment]
Is it maybe 4.5.8 instead? From F-Droid? F-Droid also has 4.5.10 so please try to update.

(No, my crystal ball is not for sale)

**Comment by monochromec** [comment]
Sorry, yes, that was a typo (hence corrected). I updated this version to 4.5.10 from F-Droid and the app now works. Closing this and thanks for the quick reaction.
