### ISSUE TITLE
Auto insert street name in POI Editor dialog

### ISSUE THREAD

**Issue by GaidamakUA** [osmandapp/Osmand#1836]
In recent versions, when we choose a 'spot' close to a nearby road, that road name is displayed in the 'spot options'.

Could that road name be auto-inserted in the 'street name' field, when adding/editing a POI?

Moved from #1825.

**Comment by vshcherb** [comment]
Generally not a good idea, it should be optional because there could be some issues with it.

**Comment by sonora** [comment]
No action planned, it seems.
