### ISSUE TITLE
New 'Local' tab's Other category size is wrong

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#18376]
See here:
![Screenshot_20231018-224601_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/845735/bf31cc0d-ff84-4b00-bde2-5a97ac30015c)

Looks like the 'Other' category is calculated as "the rest of ecereywhere OsmAnd can see" , which may be wrong for certain devices, configurations and Android versions. The value must really be calculated as just "the rest of all data in OsmAnd's data folder".

**Comment by sonora** [comment]
Well, frankly, I use Android 11 and a build which has "All files access," permission, which helps simulate the situation for Android 10 and below, where Google"s storage access rules are still less strict.

But the fact that I can produce what you see in the screenshot proves that in our code the 'total' storage is determined with a wrong method (and consequently ''Other' = 'total' minus 'all defined categories'). Should be easy to fix, 'total' must be determined as 'the size of OsmAnd's data folder', rather than 'the size of everything OsmAnd can see in the specified storage'.

**Comment by Rowin63** [comment]
May I add this here?

I dont see your problem, but something else: why some tracks (only a very few) are listed here in this section?

![Screenshot_20231020_075117_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/95540936/2f7787b4-2179-4f19-bab2-42cc3f45da3c)

**Comment by DmitryAlexei** [comment]
@Rowin63 Could you please provide some of your tracks, that are listed here for testing?

**Comment by Rowin63** [comment]
Yes sure:

[TET_Bulgaria_2017-07-26.TXT](https://github.com/osmandapp/OsmAnd/files/13053349/TET_Bulgaria_2017-07-26.TXT)
[TET_France_2018-03-23.TXT](https://github.com/osmandapp/OsmAnd/files/13053356/TET_France_2018-03-23.TXT)
[TET_Serbia_2017-08-02.TXT](https://github.com/osmandapp/OsmAnd/files/13053364/TET_Serbia_2017-08-02.TXT)

It is noticeable, it happens only with older tracks.

**Comment by Rowin63** [comment]
Interesting note: 3 of this listed tracks don't even exist anymore. At least I can't find them using the search.

**Comment by dmpr0** [comment]
# Review
- [ ]  Todo is missed, what was done? what to test?

**Comment by Chumva** [comment]
> # Review
> * [ ]   Todo is missed, what was done? what to test?

Two checks were added, one for the app folder (which should help with @sonora issue), other check helps properly check file extensions without issues with upper case (for example files with .gpx/.GPX/.Gpx extensions should go to tracks category)

You can test the second part with file extensions

**Comment by vshcherb** [comment]
Let's wait for @sonora  feedback

**Comment by sonora** [comment]
Yes  I can confirm the check works correctly now!

**Comment by Rowin63** [comment]
In my case it really was caused by the extension written in capital letters GPX. Renaming/removing them solved the problem 👍
