### ISSUE TITLE
New 'Local' tab strings/categories

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#18377]
I don't want to change without consent, but here some findings:

(1) There is a new string 'Terrain maps'. It seems this summarizes over the maps our Topography plugin uses, hence it could better be called "Topography maps"? Also, when opening it, neither the icons nor the naming makes a difference to indicate the map types-Hillshade, Contour lines and Terrain(3D)? We should use the same nomenclature and icons as on the Download tab?

(2) There is now a category called "Map source", but that really is a misnomer, I guess it means "Tile maps"?

(3) It is unclear where the 'Roads only' maps fall under, I don't think we consider them our "Standard maps"?

(4) It seems 'Nautical maps' covers only the depth contours not the seamarks files?

(5) Live Updates seems to have an issue: I have none, but the screen shows alleged 127 MB.

(6) Where are the weather maps counted?

**Comment by vshcherb** [comment]
(5) Live Updates seems to have an issue: I have none, but the screen shows alleged 127 MB. - It might be cache, but then files need to be displayed or groupped

**Comment by vshcherb** [comment]
To do:
1. OK, rename to "Topography maps"
4. Seamarks to nautical
5. Live Updates seems to have an issue: I have none, but the screen shows alleged 127 MB. - It might be cache, but then files need to be displayed or groupped

--------------- 
Answers: 
2. Keep as it is. Alternative name "Raster maps" only appears in documentation
3.  They have own category
6. They are either in Weather or in Cache

**Comment by sonora** [comment]
@vshcherb Yes, very good!

But further, in latest builds, regarding point (1) "Topography maps":
- The "Topography maps" category (correctly) contains the **Contour lines** files.
  - But they incorrectly carry the "(empty) mountain" icon of our Terrain (3D) maps, not the contour line icon (as they carry on the Download tab)
  - They just carry the name of the region without any "(Countour lines)" string behind, so it is unclear to the user that these are the Contour lines at all
- But regarding the **Hillshade** files
  - they are not shown under the "Topography maps" category but are under "Map sources"
  - they are shown there using the "layer" icon, not the "(filled) mountain" hillshade icon as used for them on the Download tab for them

**Comment by vshcherb** [comment]
Hillshade maps are deprecated so it's not an important for now

**Comment by sonora** [comment]
Are Hillshades truly deprecated? I believe for the v1 engine there is no alternative yet, or am I wrong?

**Comment by sonora** [comment]
@Chumva I guess we should still do something on the Topography screen to make the Contour lines files distinguishable from the 3D-Terrain maps (they are not, see my screenshot above):
- Use the "Contour lines" icon for Contour line files (like we do on the Downloads screen) 
- Add "(Contour lines)" or "Terrain (3D)" behind each map name? (like we do for Hillshades)?

**Comment by dmpr0** [comment]
# Review 
According to ToDo from https://github.com/osmandapp/OsmAnd/issues/18377#issuecomment-1787063132

- [ ] Seamarks to nautical? Can't find where was changed.
