### ISSUE TITLE
Getting Could Not Get Path Error

### ISSUE THREAD

**Issue by bandishsapphire** [osmandapp/OsmAnd#18372]
### Description

I have used OsmAnd in my application. It is working fine in previous month. But from 2-3 days it giving error could not get path from the URL.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform OsmAnd-java-master-snapshot-android.jar (net.osmand:OsmAnd-java:master-snapshot) to match attributes {artifactType=enumerated-runtime-classes, org.gradle.libraryelements=jar, org.gradle.status=integration, org.gradle.usage=java-runtime}.
      > Could not find OsmAnd-java-master-snapshot-android.jar (net.osmand:OsmAnd-java:master-snapshot).
        Searched in the following locations:
            https://creator.osmand.net/ivy/net.osmand/OsmAnd-java/master-snapshot/OsmAnd-java-master-snapshot.jar

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':OsmAnd:compileDebugKotlin'.
> Error while evaluating property 'filteredArgumentsMap' of task ':OsmAnd:compileDebugKotlin'
   > Could not resolve all files for configuration ':OsmAnd:debugCompileClasspath'.
      > Failed to transform OsmAnd-java-master-snapshot-android.jar (net.osmand:OsmAnd-java:master-snapshot) to match attributes {artifactType=android-classes-jar, org.gradle.libraryelements=jar, org.gradle.status=integration, org.gradle.usage=java-runtime}.
         > Could not find OsmAnd-java-master-snapshot-android.jar (net.osmand:OsmAnd-java:master-snapshot).
           Searched in the following locations:
               https://creator.osmand.net/ivy/net.osmand/OsmAnd-java/master-snapshot/OsmAnd-java-master-snapshot.jar

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform OsmAnd-java-master-snapshot-android.jar (net.osmand:OsmAnd-java:master-snapshot) to match attributes {artifactType=android-jni, org.gradle.libraryelements=jar, org.gradle.status=integration, org.gradle.usage=java-runtime}.
      > Could not find OsmAnd-java-master-snapshot-android.jar (net.osmand:OsmAnd-java:master-snapshot).
        Searched in the following locations:
            https://creator.osmand.net/ivy/net.osmand/OsmAnd-java/master-snapshot/OsmAnd-java-master-snapshot.jar

### Steps to reproduce

Try to build the project.

### Actual result

It should run properly.

### Expected result

Giving error while building the project.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 3.9
Android/iOS version: 13
Device model: Redmi 9
Crash-Logs: ? Could not resolve path
```

**Comment by DmitryAlexei** [comment]
The actual version of the app is 4.5.10, try to update and see if the problem persists.

**Comment by bandishsapphire** [comment]
Thank you for your quick reply. Now I am getting below error. So in the latest version you removed below library?

Could not find net.osmand:OsmAndCore_android:master-snapshot

**Comment by vshcherb** [comment]
Latest version is 
``` url = "https://creator.osmand.net/"```
