### ISSUE TITLE
Unable to upload POI change / creation

### ISSUE THREAD

**Issue by 9662** [osmandapp/Osmand#1837]
With OsmAnd~ 2.1.1, when I try to upload either a newly created or modified POI to OSM, it fails with the following error:

> Action Opening changeset...: I/O error occurred

Or simply, no error but the message:

> 0 POI/Notes were uploaded.

I tried both with "Always use offline editing" on (my default) and off. It made no difference.

**Comment by Barrocas** [comment]
I upload 'offline added POI' everyday (only using night build versions) and
I only get errors if the wifi or internet connection fails.




-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by jf-simon** [comment]
Creating poi is working for me too

**Comment by vshcherb** [comment]
In current version we fully refactored OSM Edits and new version is soon coming out, that issue is not reproducible in the latest builds.

**Comment by 9662** [comment]
I tried this on last night's nightly and it was still refusing to upload, but at least it showed a toast error leading me in the right direction. It turns out that the HTTPS SSL negotiation was failing as it was not able to verify the OSM server's X509 certificate, due to my disabling nearly every certificate that comes with Android (it's not paranoia if they *are* after you, etc., etc. :-) ). Having checked openstreetmap.org's certificate chain and re-enabled various GeoTrust certificates, it now works both on the nightly and on v2.1.1
