### ISSUE TITLE
No display of turn lanes when driving along a route.

### ISSUE THREAD

**Issue by Prusaker** [osmandapp/OsmAnd#18387]
### Description

There is no display of turn lanes when driving along a route (Car profile).

The bug is reproduced only when **actually moving along the route!** If you simply build a route from one point to another (without GPS) and turn on route simulation, then the traffic lanes are shown normally.

!!! OsmAnd Nightly 4.6.0 #636m **works well** (no bug). **There is a bug in OsmAnd nightly versions #847 and newer** (tested also at latest nightly build). !!!

### Steps to reproduce

Try to actually drive (without simulation) on any route where there are turn lanes. They will not be displayed.

### Actual result

There is no display of traffic lanes when driving along a route.

### Expected result

It is necessary for turn lanes to be displayed when driving along a route.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd Nightly 4.6.0 #847m and newest
Android/iOS version: Android 10
Device model: Lenovo TB-8506X
Crash-Logs: no logs.
```

**Comment by Prusaker** [comment]
How to reproduce bug without actually driving along the route:
- turn on GPS
- wait until your location is determined
- build the route from your place so that it includes sections of the road with turn lanes
- turn on the simulation of driving along the route.

During the simulation, the turn lanes will also not be shown, just like during a real trip.

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#1139m, released: 2023-12-04 The issue can be considered resolved.

During two weeks, the lanes' widget was tested:
- in realistic simulation, location simulation using GPX and in real life conditions
- in landscape and in portrait mode

The Lanes' widget is displayed in most cases. Sporadically, the Next turn widget and the Second turn widgets were not displayed (I cannot catch the pattern), but this is not the scope of that issue.

**Comment by DmitryAlexei** [comment]
@Prusaker According to the [OSM](https://www.openstreetmap.org/way/132721580), there are no lanes on proposed road, so in that case Lanes widget is not shown.
At the same time, Lanes widget can be observed on the multilane road.
 
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/fada2ee2-454a-4980-b514-20098885b506"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Prusaker** [comment]
I described how to reproduce the the bug you described with Next turn widget and the Second turn widgets disappearing.
Perhaps this bug should be moved to a separate issue?

**Comment by DmitryAlexei** [comment]
@Prusaker thank you for hint and clarification! But on my device, the next turn and second next turn widgets work with that road.
So, I suppose, the steps to reproduce the issue when this widget disappears are different.
