### ISSUE TITLE
In osmand style, the names of rivers have disappeared

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#18398]
### Description

In the osmand style the names of rivers have disappeared. At the same time, river names are present in the topo style.

### Steps to reproduce

Include appropriate map styles and test.

### Actual result

No river names.

### Expected result

Display river names.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:OsmAnd~ 4.6.0#893m, Дата выпуска: 2023-10-20
Android/iOS version:13
Device model:poco f3
Crash-Logs: ?
```

**Comment by zipav** [comment]
OsmAnd Nightly 4.6.0#950m, released: 2023-11-01

| Topo | OsmAnd |
|-----| ---- |
| ![Screenshot_1691014898](https://github.com/osmandapp/OsmAnd/assets/123936521/30397771-9336-4529-9376-55c4d56e3284) | ![Screenshot_1691014905](https://github.com/osmandapp/OsmAnd/assets/123936521/b67d4438-9cae-4170-9bc5-ac0921ef13ae) |
