### ISSUE TITLE
Widgets in the bottom panel in a dark theme

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#18397]
### Description

Text is hard to see:
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/12549744/03332abb-1291-408c-8bef-7e57203d7fb0"  width="300" height="auto"/> </td>
  </tr>
</table>

In addition, changing the application theme does not affect widgets until you restart the application

### Steps to reproduce

Described above

### Actual result

Not nice.

### Expected result

Improve text readability.  Changing the application theme should immediately change the widgets.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:OsmAnd~ 4.6.0#893m, Дата выпуска: 2023-10-20
Android/iOS version:13
Device model:поко ф3
Crash-Logs: ?
```

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#897m, released: 2023-10-22
Steps to reproduce:
- go to settings > your profile (in my case Browse map profile) > General settings > app theme > set to *Dark*
- map mode set to Day (configure map > map mode > day)
- set some bottom widgets (in my example weather widgets)

Actual result:
- data in widgets is difficult to read (see screenshot)
- with map mode set to Night works fine
- bottom widgets also not transparent, although the corresponding setting is enabled
