### ISSUE TITLE
Actual Speed much bigger for using OSM AND on my bike

### ISSUE THREAD

**Issue by it-open** [osmandapp/OsmAnd#18391]
### Describe the idea (required)

I use my mobile phone on my bike with OSMAnd as route planner. 
i see the speed on the right top side but with the protection it is barely visible. 
I would like to have the speed at least double Size.

### Tell us about the expected behaviour (required)

For some People special things are more interesting than others. 
The direction, ot time till arrival, the Speed, the Position. 
You have done a very good job that you can define what you want to see on the left or right side of the Display.

If you have an option to make one of the Items at least twice as big or very big on the Top middle, everyone can choose what they need. 
If I have the actual Speed, I wouldn't need any extra system on my Bike. 

### Tell us about alternatives you've considered (required)

Floating Overlay on the Screen where you can move it. Even on top of other Apps.

**Comment by mikehgentry** [comment]
This has been discussed, e.g. #11086 #1084

I think I remember vscherb saying that they're intending to add a 'bike computer' view, but I don't know how long-term the plan is.
