### ISSUE TITLE
Strange type in the shelter description

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#18399]
### Description

The description looks unfinished, and is also missing for translation
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/12549744/99ce313b-e3a3-45cf-a23b-6638ebcb2710"  width="300" height="auto"/> </td>
  </tr>
</table>

### Steps to reproduce

Select any amenity = shelter

### Actual result

looks unfinished.

### Expected result

make it more understandable for the user.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:OsmAnd~ 4.6.0#893m, Дата выпуска: 2023-10-20
Android/iOS version:14
Device model:poco f3
Crash-Logs: ?
```

**Comment by xmd5a2** [comment]
**Dev notes:** [phrases are ok](https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/res/values/phrases.xml#L5174) but UI does not even show a phrase in English.

**Comment by ivanPyrohivskyi** [comment]
Todo: check translation

**Comment by zipav** [comment]
OsmAnd Nightly 4.7.0#1226m, released: 2023-12-15

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/efde035f-6bec-451a-87ba-ab4121f98b13"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by dmpr0** [comment]
# Review 
- [ ] Don't work on iOS
- [ ] Description source? https://wiki.openstreetmap.org/wiki/Key:shelter_type

https://www.openstreetmap.org/way/975414176#map=19/52.22153/21.02572

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>iOS</th>
        <th>Android</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/7d50cc6c-2a7a-4ceb-ab6b-bf20e8a777fc"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/ef3202e2-ff91-456a-a660-f30844a1f3e7"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>

**Comment by xmd5a2** [comment]
Related to https://github.com/osmandapp/OsmAnd/issues/17584

**Comment by xmd5a2** [comment]
@dmpr0 It is a search filter actually and may not be suitable for context menu info. But what if we change description to "Shelter type is not public transport"?
Currently there is no way to hide it from context menu while keep it available as search filter.

**Comment by ivanPyrohivskyi** [comment]
In iOS must copy_phrases.sh

**Comment by vshcherb** [comment]
- [ ] ```Shelter (not for public transport)```

**Comment by dmpr0** [comment]
> * [x]  `Shelter (not for public transport)`

How it related to public transport so we need to mention is not related to it?

**Comment by zipav** [comment]
OsmAnd Nightly 4.7.0#1402m, released: 2024-01-21

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/6ba87b33-41dd-4d2f-a3f2-733cdcec64d6"  width="300" height="auto"/> </td>
  </tr>
</table>
