### ISSUE TITLE
Some remaining issues with our Download screens

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#1840]
We have made great progress with our new "Download indexes" UI, for documentation here are some remaining issues I still observe:

(1) On the "Updates" tab, we should, just like we already do it on the "Local" tab, add the country name of any list entry which represents a country's sub region. E.g.: Local tab shows "Italy Lazio", which is good, but the Updates tab only shows "Lazio", which should be improved. 

(2) We somehow lost the ability to Deactivate /Activate hillshade, contour line and Wikipedia files (on the Local tab, of course)

(3) Order of group categories on the Local tab: Proper order should be (consistent with All Downloads tab):
  (a) Standard maps (is ok)
  (b) Standard maps - Deactivated   (TODO: now here we have Contour lines - Deactivated, if you have any)
  (c) Online and cached tile maps (is ok, but hillshades are also shown here, do we want to change this?)
  (d) Contour lines (is ok)
  (e) Wikipedia (is ok)
  (f) Voice prompts (TTS, preferred)
  (g) Voice prompts recorded) (this is now still swapped with f above)

(4) Local tab: On smaller screens longer group category headlines like "Standard maps - Deactivated" are truncated because we only allow one line. We must either allow multiple lines, or we could simply put all deactivated items into one group category called "Deactivated", and distinguish them only by their icon.

(5) The group category headline "Online and cached tile maps", unlike the other groups headlines does not show the total size used (in MB  GB, etc.),  we should add it.

(6) OsmAnd force-closes when the screen is rotated while on any of the tabs.

**Comment by vshcherb** [comment]
(2) I think it was deleted even in previous release, there are possibility to turn off hillshade/contour lines by plugin. Wikipedia files appeared recently as a separate group. Having deactivation function is questionable, the biggest issue used to be only with standard maps.
(4) name deactivated will be fine, cause the header is not designed for columns
(5) it was never showing and it could be a separate feature request, but I doubt will be implemented soon without real necessity. The issue it is not possible to measure "Folder size" in a reasonably short time frame (on load), even on PC it could take minutes to calculate disk space usage for tiles.

**Comment by vshcherb** [comment]
(3) ordering is fixed (order how files are loaded) - 	public List<LocalIndexInfo> getLocalIndexData(LoadLocalIndexTask loadTask){
(6) fixed
(1) fixed
(4) fixed
(2) partially fixed

**Comment by sonora** [comment]
OK, all fine now I think!  Except:

ad (3) I cannot figure out why on he "Local" tab recorded voices are listed before TTS voices (TTS is preferred and should come first, just like an he "All Downloads" tab)

Regarding the "Deactivated" section: Small logical error here still: By the icon we denote the file type (map, wiki, etc.), while by icon color we denote the file status (up2date, outdated, etc.). So deactivated files must not have their own icon, but retain their (getOriginalType() ) category icon, perhaps with a "deactivated" color like gray (R.color.color_unknown).

**Comment by vshcherb** [comment]
The order in this method 
public List getLocalIndexData(LoadLocalIndexTask loadTask){

**Comment by vshcherb** [comment]
I'm not sure which icon it should have archive or original type, I put a type name in description, so Icon is not that important, but may be I agree with you.

**Comment by sonora** [comment]
Order of voice cats: It depended on the alphabetic order of the languages you happened to have downloaded, fixed in this commit: https://github.com/osmandapp/Osmand/commit/ebcd44c2e677a2cc2abe1cf16d72d88d13485e33

"Activate" menu entry was now missing due to new DEACTIVATED category, fixed by this commit: https://github.com/osmandapp/Osmand/commit/d9a1647f1abe651a9de54bfd0849593fedf60720 . I checked it functions ok also for e.g. deactivated SRTM data, if you happen to have any,

Color of deactivated items now neutral, as we do not check their up-to-date status, fixed by this commit: https://github.com/osmandapp/Osmand/commit/c05b7b386951d98e96a1947443669a254202350a

Would probably be more logical if we assigned the original-type icon to deactivated items, kind of like I drafted in this commit: https://github.com/osmandapp/Osmand/commit/df04fe44dfa7502fbef03156c1eb160221df6297, but we need to check how we can reference the items at that point in the code and check their original type?

**Comment by vshcherb** [comment]
I think It is done, there are minor improvements, but they are discussible. Though we have lots of other todo's
