### ISSUE TITLE
Objects on the map are rendered with low resolution/incorrect size when map scale is set to ~20m

### ISSUE THREAD

**Issue by github-test-567** [osmandapp/OsmAnd#18405]
### Description

While zooming map to 20m scale objects on the map are rendered in low resolution and have incorrect size which does not match map scale. When zooming further (to 5-2 m scale) objects become rendered with correct resolution/size.

Looks like, only 2.0 (OpenGL) rendering engine is affected.
Clearing application data does not resolve the problem.

### Steps to reproduce

1. Run app.
2. Download vector map.
3. Zoom map to 20m scale.
4. Zoom map further to 5m scale.

Captured video:
https://github.com/osmandapp/OsmAnd/assets/148674895/f51116ae-34fa-4967-91af-43dbda95db27
https://github.com/osmandapp/OsmAnd/assets/148674895/b129c056-40fe-4670-934a-effed4d338ba

### Actual result

Objects on the map are rendered in low resolution and have incorrect size.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/148674895/fc7ae13a-63f5-4689-ab7f-f6634f5168ee"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/148674895/0c0a43a1-26e2-4909-8c61-2d235c1a69be"  width="300" height="auto"/> </td>
  </tr>
</table>

### Expected result

Objects on the map are rendered in correct resolution and have correct size which matches map scale.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/148674895/71b2a201-a19e-4286-8e6c-37ad274f9b4d"  width="300" height="auto"/> </td>
  </tr>
</table>

### Your Environment (required)

OsmAnd Version: "OsmAnd~ 4.5.10 (451003)"
Android version: 9 PKQ1.190118.001
Device model: Xiaomi Mi6

**Comment by DmitryAlexei** [comment]
@github-test-567 thank you for taking time and leaving a message about the problem
Fix for this issue (https://github.com/osmandapp/OsmAnd/issues/17763) will be available in 4.6 release. 
As a workaround, you can disable 3d relief option in configure map menu
