### ISSUE TITLE
Navigation in a tunnel with lost GPS signal

### ISSUE THREAD

**Issue by oxxm** [osmandapp/OsmAnd#18408]
### Description

Osmand doesn't simulate the position with the last known speed in order to give navigation directions **_in_** the tunnel, in case an exit needs to be taken in the tunnel itself.

After exiting the tunnel and getting the GPS signal back, Osmand recalculates the route, by then it is already too late to announce the exit in the tunnel.

### Steps to reproduce

Example of a route with an exit in a tunnel:
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=48.7553%2C9.1374%3B48.7578%2C9.1593#map=15/48.7567/9.1520

### Actual result

GPS signal is lost, navigation is on hold, which can lead to missing exists in a tunnel.

### Expected result

Osmand should simulate the position in a tunnel based on the last known speed at tunnel entrance, in case navigation is needed **in** the tunnel, like taking an exit as an example.

After exiting the tunnel Osmand overwrites the simulated position with the GPS position and updates the navigation route accordingly.

### Your Environment (required)

OsmAnd Version: 4.5.10
Android: LineageOs 17.1
Device model: Samsung S9

**Comment by vshcherb** [comment]
This issue needs to be reproduced as it's long time implemented feature.

**Comment by Rowin63** [comment]
> This issue needs to be reproduced as it's long time implemented feature.

Then it is an issue, same here.
Until now I thought, that's something I just have to deal with...

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#897m, released: 2023-10-22
Reproduced using track [2023-10-23_12-54_Mon_timestamps off.txt](https://github.com/osmandapp/OsmAnd/files/13072591/2023-10-23_12-54_Mon_timestamps.off.txt) (timestamps of points inside tunnel were deleted)

Steps to reproduce:
- set a route using provided gpx, start navigation in *Flight mode* (when GPS receiver of your device is off)
- set GPS simulation using provided GPX
- wait until the tunnel entrance

Actual result:
- navigation get stuck at the tunnel entrance
- OsmAnd announce: *GPS signal lost* (00:17 on video)


https://github.com/osmandapp/OsmAnd/assets/116079541/049e9e8b-d82c-4b8d-828b-09a2b7bc178c

**Comment by oxxm** [comment]
@vshcherb what is the expected behaviour? Osmand simulates the position after signal loss at tunnel entrance and continue navigation until gps signal is back online?

**Comment by Noitarud** [comment]
Maybe treat as a roundabout, "take 2nd exit" at entry.

Your evisioned solution is best with accelerometers (on mine the limit per axis is 40G: thrust your device with rotation onto your bed to see centrifugal force; can increase limit with device tilt).

**Comment by Rowin63** [comment]
Thew problem still or again exists.

See the attached video. The situation at the end of the clip (rotating 180° back and forward) continues until leaving the tunnel.
No routing (taking the correct exit) possible at all. Problem is not new, it exists already a longer time.

https://github.com/osmandapp/OsmAnd/assets/95540936/2dacc0d2-12d3-40d4-bf7a-f64b33cccc5b

**Comment by Rowin63** [comment]
Still exists in the +4.8.6 but doesn't in the nightlys 🤔
