### ISSUE TITLE
No u turn restriction doesn't allow to cross the street

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#18409]
https://www.openstreetmap.org/relation/6091778
https://www.openstreetmap.org/way/1106646257

![Screenshot 2023-10-22 at 18 04 10](https://github.com/osmandapp/OsmAnd/assets/1042025/c981d9f6-bff3-461b-91c4-9941d50a4f9f)

**Comment by RZR-UA** [comment]
Please clarify the issue.

The "restriction: no_u_turn" problem (pictured above) is not reproduced.

Please check by link:

https://osmand.net/map/?start=50.451773,30.434409&finish=50.449358,30.433540&type=osmand&profile=car#18/50.45037/30.43376

![cross](https://github.com/osmandapp/OsmAnd/assets/90444451/415f6152-a00e-472c-a87e-0714f7e91ab4)

**Comment by RZR-UA** [comment]
Closed.

NOT_A_BUG

Actually it was happened in routingHHBase branch due to wrong configuration.
