### ISSUE TITLE
Current open issues with the new context menu

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#1841]
Open issues, as a reminder or us:

(1) Tapping the Waypoints button (can easily occur accidentally) will  immediately and without further confirmation set a waypoint (which is comparably cumbersome to remove again). All other actions we have correctly require a second tap for confirmation, and this must also be implemented for setting a waypoint. I suggest we re-instate the old interim menu asking for confirmation to replace the destination, or add as first or as last waypoint.

(2) The "..." menu should also contain an item "Show POI description", because currently how to display the e.g. Wikipedia or other POI descriptions is very hidden.

(3) Has "Navigate from" been deleted on purpose? (Another possible candidate for the "..." button)

(4) If possible, it would be nice if (e.g for residential addresses) the city/town/etc. could be shown below the street name, not just the LatLon.

(5) The LatLon values are displayed twice (once below the street name and once below in the details section. Once in the details section is enough).

(6) Tapping near a named road, but with an unnamed e.g. pedestrian or bike trail next to it (between the tap mark and the road) will result in the road name not being displayed. We could think about ignoring unnamed lines and instead displaying the named road name if it is close enough to the tap mark.

(7) It would be nice to not only display the street name, but also see a short list of the say 3 or so closest POIs as a selection list under the details section.

(8) Tapping the Share button currently FCs OsmAnd.

**Comment by Barrocas** [comment]
Nr (8), the 'Share' crash,  is also reported on #1839

**Comment by vshcherb** [comment]
(8) Fixed
(7) Agree, Please report another issue
(6) Agree
(5) We try to reduce number of times it is displayed as a second row (as minimal as possible), but if there is nothing else to display it will duplicate. We want to make the row below clickable later.
(4) Agree, same as 6 + house number could be shown
(3) Yes, deleted in favor to restructure waypoints dialog, so this is an open discussion could be opened once we finish a first prototype.
(2) Yes, this could be an issue, will mark as most important question here
(1) Works as designed, it will be slightly different design and will be easier to delete waypoints.

Waypoints have an idea to not attach them any more to just one trip and may be remove numbering. There is an idea to make it as "extra favorites" list that doesn't require any additional information. There will be 2 use case navigation:
1) Short path navigation from context menu, will start navigation without any intermediate point
2) Long path: navigation from Waypoints list, where you first need to select which waypoints will be part of the trip and there you could select a start point or an end point. That will cover use case of "Directions From"

**Comment by vshcherb** [comment]
I think most of the bugs are closed, regardless navigation, which should be a separate topic. I would split into several groups:
(2) - will be fixed
- Small usability improvements (clicks etc) - most likely next release
- More information about POI and objects - - most likely next release
- Information about object when clicking on map without POI - next release
- More precise geocoding - city, suburb, ... - next release
- Navigation / waypoitns - still this release and still shaking

**Comment by vshcherb** [comment]
(6) Nope, it requires a separate issue and it is not that easy, at least I don't how exactly to fix now, so once the critical bug list is down we will take a look. That's  new functionality it needs to go through couple of iteration. So far we are using algorithm from routing which was not designed for this.
