### ISSUE TITLE
Hide Dashboard after critical messages

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#1842]
Users who have selected SHOULD_SHOW_DASHBOARD_ON_START=false deliberately do not want to be bothered with seeing the Dashboard.

We have at least 2 occasions ("dashboardOnMap.hasCriticalMessages") when the dashboard pops up regardless, for the DashErrorFragment and the rate_us_fragment.

So for (SHOULD_SHOW_DASHBOARD_ON_START=false && dashboardOnMap.hasCriticalMessages=true), after these messages pop up (and unfortunately they come with the Dashboard), we  should automatically hide the Dashboard again after they are dealt with. (Now Dashboard remains visible, user has to actively hide it.)

**Comment by CJTmmr** [comment]
On the other hand....
I really like the Dashboard, and got used to it in PlayStore release 2.1.1.
In the nightly's I get the Dashboard on start-up. (Option Dashboard: **Show on start**).
The Android-menu-button always gives you the OsmAnd-menu, as does the small widget with the three dashes.

To display the dashboard you need to tap at least two times..: Menu - Dashboard.
So... I hardly use the dashboard anymore, although I like it so much.

Maybe with Option Dashboard **Show on start** ; the Dashboard could pop-up always..

Thanks for the great app!

CJTmmr

**Comment by vshcherb** [comment]
It should not be used during next startup, I think we still didn't make final decision which way to go. I guess for these case, it should be a separate screen (not dashboard, so we keep it untouched).

**Comment by sonora** [comment]
Our Dashboard really polarizes our users: Some love it (mostly because of its flexibility and direct-access features), some hate it (mostly because it has small elements hard to select during many activities, and they like a stable and predictably static menu structure).

Our current option to show or not show the Dashboard on app startup is useless, because app startup happens very infrequently.

Unless we decide which way (Dashboard or Menu) to go and dump the other, the only suggestion I have for now is CJTimm's: Let us onvert the current "Show on app start" menu item to a configuration item selecting which of the 2 (Dashboard or Menu) should always be shown first after one tap on the app menu button.

This kind of creates 2 basic ways to operate the app and hence slightly complicates usage and support, but may be the only way to serve both parties.

**Comment by vshcherb** [comment]
That one of the most important decision we need to make it by release at least 4 options:
1. Show dashboard on start or not (configurable)
2. Show dashboard on menu or don't show (not configurable)
a) Used to be: Yes + yes
b) Now is: Yes + no
c) Possible: No + no
d) Doesn't make sense: No + yes.

a) definitely doesn't fit every one, but it is really difficult to switch immediately to c) especially because not everything is solved yet with crash cards (however I think it is latest)
For now we have a setting to switch between b) and c) and missing a).
If we change in release to c) (that will be a big surprise I'm afraid), but in that case we could keep the setting between a) and c). 
But I do think b) option has sense, because it provides a nice menu where to start with (with a recording, with a favorite, with ...), later on I should admit my usage is more comfortable with a static drawer.

**Comment by Barrocas** [comment]
I must admit that I didn't like the dashboard at first, but now I use it
often, mostly to go to the added/edited POI management and uploading.

So I jump between menu and dash, but I do have it set to start straight to
the map.


-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by sonora** [comment]
Looks to me like most people either prefer the Dashboard or the Drawer, few people like to regularly switch between the 2. So we should likely go for an option which allows setting the preference which of the 2 comes up with 1 tap (on the menu button), and for the other you then need a subsequent tap. this means make (2) configurable.

App start  (vs. and Android resume) happens so rarely under most conditions that I think we can delete (1), just always go to the map directly and get the user used to using the menu key. (We need to of course handle all startup messages in popups outside the Dashboard then.)

So my suggestion is:
- Always start the app directly to the map screen (unless there are startup messages or first-run messages)
- Make it configurable if the menu key triggers the Dashboard or the Drawer menu, the other one then always requires a second tap.

**Comment by CJTmmr** [comment]
I agree with Hardy Sonora
Op 30 okt. 2015 12:59 schreef "Hardy" <notifications@github.com>:

**Comment by sonora** [comment]
I think this is actually resolved and we can close it?

**Comment by CJTmmr** [comment]
I think it is very good,  as it is right now
Thanks

CJ

Closed #1842 <https://github.com/osmandapp/Osmand/issues/1842>.

—
Reply to this email directly or view it on GitHub
<https://github.com/osmandapp/Osmand/issues/1842#event-476198278>.
