### ISSUE TITLE
App language stuck in English 

### ISSUE THREAD

**Issue by 32Vache** [osmandapp/OsmAnd#18429]
My OsmAnd app is currently set to English but I'm completely unable to change it. I can't find any setting to change language, and while I thought that was because it followed my system's language instead, it does not. My system language is set to Catalan but even when switching to something else, OsmAnd stays in English. How can I go about setting OsmAnd to Catalan or French?

Using version 4.6.0#897m, on Android 13 - MIUI 14

**Comment by Nine-Tailed** [comment]
Хм, странно, изменение языка системы должно было вам помочь.
Могу предложить в настройках андроида поискать в строке поиска секретную настройку "доступ ко всем файлам" только конечно на языке системы. Там выбрать османд, а потом пункт "язык".
![Screenshot_2023-10-25-00-30-39-854_com.android.settings.jpg](https://github.com/osmandapp/OsmAnd/assets/12549744/82df4ada-6e59-4ef5-ae61-b7cd47d2f405)

**Comment by DmitryAlexei** [comment]
@32Vache It is suggested, in the android settings to find "access to all files" (using the system language). Then, select OsmAnd, and then the "language" option.

On Samsung devices go to Android settings > Apps > OsmAnd > language and choose your variant

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/39040c73-a30b-4e97-9f02-3609e73af68d"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/44b9d27a-d9c6-4adc-a5f5-43dc11897476"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by 32Vache** [comment]
I did this, but clicking Change language crashes the thing...
https://github.com/osmandapp/OsmAnd/assets/42336759/76e824a9-e5f0-47f5-ad45-a5d6ba80a846

**Comment by DmitryAlexei** [comment]
Try to change your system language to French first, then change app language to French and system language back to Catalan.
It seems the issue is with your Android system.

**Comment by 32Vache** [comment]
Indeed, tried changing system language to French but the crash stills happens.

**Comment by vshcherb** [comment]
Which crash happens

**Comment by 32Vache** [comment]
An issue with my system settings, trying to change an app's language through 'Access to all files' crashes the settings app. Because of this I'm unable to change OsmAnd to another language than English (it currently is set in English)

**Comment by Nine-Tailed** [comment]
make a full backup, delete Osmand and try a clean installation first, if changing the language works on it, then try restoring the backup.

**Comment by 32Vache** [comment]
After uninstalling and reinstalling, OsmAnd was now following system language, so it is in Catalan now, which is what I wanted. My system settings are busted though and I'm unable to change the language for any app. But as long as it follows system language which it now does, that's fine by me. Thanks for the help!
