### ISSUE TITLE
Bicycle routing avoiding correct bicycle lane

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#18430]
### Describe the routing engine used (required)

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Describe your routing Profile (required)

Bicycle, live data enabled.

### Describe your start and end points (required)

Start: 51.056755,13.725797
End: 51.057999,13.727563

### Describe the actual route (required)

OsmAnd avoids the road ahead and calulcates a long detour instead of just driving straight.

![photo_2023-10-25_09-19-58](https://github.com/osmandapp/OsmAnd/assets/1040784/676e370f-d5f5-4bf5-920e-95c537a8adf0)

Only happens in bicycle mode. Car mode is fine.
Doesn't happen online: https://osmand.net/map/?start=51.056755,13.725797&finish=51.057999,13.727563&type=osrm&profile=bicycle#17/51.05738/13.72406

### Describe the expected route (required)

OsmAnd drives straight ahead.

### Describe what Maps you used (online or offline) (required)

- [x] Offline maps offered within the OsmAnd app for download. 
- [ ] Online (tile / raster) maps 

### Your Environment (required)

```
OsmAnd Version: 4.6.4
Android/iOS version: 10
Device model: Samsung S9
```

### Anything else? (optional)

Possibly related to #18422 and/or #18327.

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. Below are the instructions to recreate it:

- Download the map of Saxony, Germany.
- Activate navigation and choose the cycling profile.
- Input the following coordinates for the initial point: 51.056755,13.725797, and these coordinates for the destination: 51.057999,13.727563.
- The routing does not follow a direct route; instead, it creates detours toward the endpoint.
- Interestingly, if you swap the starting and ending points, the navigation works correctly.

In the Web version, the route is also built with detours: https://test.osmand.net/map/?start=51.056750,13.725800&finish=51.057980,13.727579&type=osmand&profile=bicycle#17/51.05759/13.72463

OsmAnd~ 4.6.0#915m, released: 2023-10-25

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/11c019ed-25e1-4ba8-a9f7-3f74eac83b26"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/cb54f529-50ae-4eef-9ffb-2fdb4aa9351e"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
By unknown reason - https://www.openstreetmap.org/way/31823323 is not allowed for routing. 
```
<tag k="cycleway:right" v="track"/>
<tag k="cycleway:right:segregated" v="no"/>
<tag k="cycleway:right:surface" v="paving_stones"/>
<tag k="destination:arrow:lanes" v="|through;through"/>
<tag k="destination:colour:lanes" v="white|;white"/>
<tag k="destination:lanes" v="Parkhaus Mitte|Bischofswerda;Semperoper"/>
<tag k="destination:ref:lanes" v="|B 6"/>
<tag k="foot" v="designated"/>
<tag k="highway" v="primary"/>
<tag k="lanes" v="2"/>
<tag k="lit" v="yes"/>
<tag k="maxspeed" v="50"/>
<tag k="name" v="Könneritzstraße"/>
<tag k="name:etymology:wikidata" v="Q994021"/>
<tag k="oneway" v="yes"/>
<tag k="ref" v="B 173"/>
<tag k="shoulder" v="no"/>
<tag k="sidewalk" v="right"/>
<tag k="sidewalk:right:surface" v="sett"/>
<tag k="source:maxspeed" v="DE:urban"/>
<tag k="surface" v="asphalt"/>
<tag k="turn:lanes" v="left|through;right"/>
<tag k="wikidata" v="Q60463568"/>
<tag k="wikipedia" v="de:Könneritzstraße (Dresden)"/>
```

**Comment by scaidermern** [comment]
Maybe because of the same (unknown) reason as #18327 - which has been closed without a fix ☹️

**Comment by xmd5a2** [comment]
This is because of this commit https://github.com/osmandapp/OsmAnd-resources/commit/95ff1b8ccde4683350a958a66bd6165e44794583
which forbids ways with `foot=designated` for bicycles. Is there a mapping error here? Looks like not because of `<tag k="sidewalk" v="right"/>`. Not clear how to fix that. Any ideas?

**Comment by scaidermern** [comment]
> which forbids ways with `foot=designated` for bicycles.

Good find.

Under which conditions is `foot=designated` forbidden for bicycles? The combination of `foot=designated` + `bicycle=designated` is perfectly fine and often used for shared foot/cycleways. But it looks like OsmAnd _doesn't_ forbid those, so there must be more to this.

>  Is there a mapping error here?

In this case it is indeed. Not really an error but rather imprecise tagging. The `foot=designated` is for the sidewalk next to the road that is implicitly mapped as `sidewalk=right` and should also become `sidewalk:right:foot=designated` instead of `foot=designated`. I will correct this.

Still unsure why `foot=designated` is forbidden for bicycle routing. If cycling is not allowed somewhere then `bicycle=no` or `bicycle=dismount` is used. `foot=designated` doesn't tell you anything about bicycle access.

**Comment by xmd5a2** [comment]
Agree. This commit was reverted. [This issue](https://github.com/osmandapp/OsmAnd/issues/17532) needs to be fixed another way.

**Comment by yuriiurshuliak** [comment]
The bug has been fixed. The route is correctly built in a straight line in both directions.

OsmAnd~ 4.6.0#1126m, released: 2023-11-30

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/362ea528-0212-4de3-8728-b02ddc65711c"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/9a9fb3bd-cb81-4cd5-8b3b-f0b5788ab6b5"  width="300" height="auto"/> </th>
  </tr>
</table>
