### ISSUE TITLE
NB: Live Updates => slower map Rendering

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#1843]
![screenshot_2015-10-27-10-38-11](https://cloud.githubusercontent.com/assets/4006691/10755618/b3413e1e-7c96-11e5-901e-05599fc23a03.png)

I'm having some slow rendering while navigating or browsing the map, it appears to have gotten worse these past few days. 
Roads get greyed out and take a while to render properly.
'Peter B' also complained about the same slower rendering when using the Live Updates:
https://groups.google.com/forum/m/#!topic/osmand/S1rGIUPLMrM

I can confirm that when removing the Live Updates folder, the rendering goes back to normal.

I'm using a Bq Aquaris E6 with Android 4.4.2, latest Osmand night build.

**Comment by vshcherb** [comment]
Could you please give more information how update files do you have in the folder (it is possible to check on file system).

**Comment by Barrocas** [comment]
Sure.
I keep daily updates of Portugal and Spain maps.

Now there are 4 files in the 'live' folder:
Portugal_europe_15_10_00.obf
Portugal_europe_15_10_27.obf
Spain_europe_15_10_00.obf
Spain_europe_15_10_27.obf

But 'Peter B' is another user that has different maps (I guess maybe
germany), and he had the same slower rendering issue, so it may not be
related to any map update in specific.

It appears that Osmand has some difficulty to deal with the normal maps and
the updates at the same time.

This is on an 2ghz octacore 6inch phone, and it is fast in any other app,
except in Osmand.


-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by vshcherb** [comment]
Can you please publish debug rendering information (Settings -> Development -> Show rendering time).

I have a feeling it is related to the lines which go across the map (they are not visible)

**Comment by vshcherb** [comment]
Can you please publish debug rendering information (Settings -> Development -> Show rendering time).

I have a feeling it is related to the lines which go across the map (they are not visible)

**Comment by Barrocas** [comment]
![screenshot_2015-10-28-15-01-11](https://cloud.githubusercontent.com/assets/4006691/10792680/9de21a26-7d85-11e5-87f6-4039f6f111e6.png)

Starting navigation, and navigating, with the Live files.
Sometimes it takes 5s or more to render properly, while driving, even at low or moderate speeds.

![screenshot_2015-10-28-15-02-12](https://cloud.githubusercontent.com/assets/4006691/10792704/b45e17b4-7d85-11e5-9686-b1324fa7b362.png)

![screenshot_2015-10-28-15-05-23](https://cloud.githubusercontent.com/assets/4006691/10792709/c1fc8de2-7d85-11e5-8792-875afe49c90f.png)

Near the same place, but without the Live files and after an app force close + restart:

![screenshot_2015-10-28-15-16-38](https://cloud.githubusercontent.com/assets/4006691/10793070/3cd60d30-7d87-11e5-8644-5500cb2a8546.png)

![screenshot_2015-10-28-15-18-59](https://cloud.githubusercontent.com/assets/4006691/10793100/5ab9c71a-7d87-11e5-8c9a-8d5d482266af.png)

**Comment by Barrocas** [comment]
With the latest builds and maps, this issue is no longer noticeable.

**Comment by jf-simon** [comment]
For me slow rendering is back
![screenshot_2015-12-19-22-55-09](https://cloud.githubusercontent.com/assets/11144987/11915364/096b7ac0-a6a4-11e5-8663-89e24e01ec2a.png)
![screenshot_2015-12-19-22-51-29](https://cloud.githubusercontent.com/assets/11144987/11915368/12f42f9c-a6a4-11e5-99ca-63096af6585b.png)

Lat 48.52417 Lon 8.56284

Live updates are enabled for Germany baden-württemberg

Greetings Simon

**Comment by Barrocas** [comment]
I also notived the slower rendering coming back, more in some areas than
others.

It was much better at the beginning of the month.
It gets slower as Live Updates gets more complex?


-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by vshcherb** [comment]
Live updates is not changed... I suspect it is related to the long lines reported issue. We plan to address these issues soon and altogether.

**Comment by jf-simon** [comment]
Ok Thanks

**Comment by joskohorvat** [comment]
Hm, I will wait a little bit. At the end of the year there will be solution for this slow rendering.for sure.
Otherwise Live Updates it is good idea, just now is mixture of Low & Hate

**Comment by vshcherb** [comment]
The solution is on its way, there are already new maps but they are in a deep testing yet. The maps will be slightly incompatible (ids will be different), that's why we want to fix all these issues before we switch to new ones.
