### ISSUE TITLE
sea_areas rendered as shoal

### ISSUE THREAD

**Issue by quantenschaum** [osmandapp/OsmAnd#18438]
### Description

At zoom level 14+ all `seamark:sea_area`s are rendered as shoals (dotted fill pattern and red dashed outline).

reason: typo `assitional` here https://github.com/osmandapp/OsmAnd-resources/blob/master/rendering_styles/nautical.render.xml#L3313

### Steps to reproduce

look at https://www.openstreetmap.org/#map=14/55.3363/11.0464

### Actual result

![image](https://github.com/osmandapp/OsmAnd/assets/3985599/5c1086bc-d7fb-4eaa-a9ed-40caec6ed388)

### Expected result

![image](https://github.com/osmandapp/OsmAnd/assets/3985599/c12d2ba9-412a-425c-b9dd-b5081dea2aa4)

### Your Environment (required)

OsmAnd 4.6.3

**Comment by quantenschaum** [comment]
This is fixed in my [marine style](https://github.com/quantenschaum/mapping/blob/master/marine.render.xml). You might want to merge this and the other changes into the nautical style.

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#1003m, released: 2023-11-09
tested on 55.3363 11.0464
