### ISSUE TITLE
Allow to search `health_specialty` by name

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#18431]
# Description 
* Add ability to search `health_specialty` by name. 
* Allow to search `blood_check`

Previous task https://github.com/osmandapp/OsmAnd/issues/1996

**Comment by xmd5a2** [comment]
Fixed

**Comment by vshcherb** [comment]
Not clear how to test

**Comment by xmd5a2** [comment]
https://www.openstreetmap.org/node/9903524096
Map: Italy_trentino-alto-adige_europe
![Screenshot_2023-11-21-09-54-36-967_net osmand plus](https://github.com/osmandapp/OsmAnd/assets/5829014/8effbcae-8660-4453-8726-f4ca673d4bc6)
![Screenshot_2023-11-21-09-55-09-381_net osmand plus](https://github.com/osmandapp/OsmAnd/assets/5829014/141d4bfe-36b3-4880-8041-2744f5d2bd0c)
There is another UI issue. At search results screen `blood_check` phrase is not used but it is present in [phrases.xml](https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/res/values/phrases.xml#L5201C16-L5201C16)

**Comment by Dima-1** [comment]
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/31807095/fb8ba106-637e-4269-8035-e5a420116890"
width="300" height="auto"/> </td>
  </tr>
</table>
