### ISSUE TITLE
Offline Routing: Destination close to footway but far from highway

### ISSUE THREAD

**Issue by CJTmmr** [osmandapp/Osmand#1844]
Hi,

Using latest Nightly's, map Netherlands (with live updates)
Try to navigate to addresses on [Bodegraven-Vlietkade](http://www.openstreetmap.org/way/177902370#map=18/52.08594/4.73885) (click link)
Vlietkade is a footway, no car could ever acces the small path
The situation is mapped fine on OSM, according to reality

On FOOT/BIKE-mode navigation is perfect:
to [City] Bodegraven, [Street] Vlietkade, [Housenumber] 33: OsmAnd brings you right to the front-door:
![2015-10-27 19 34 46](https://cloud.githubusercontent.com/assets/15076257/10770179/32ba5bdc-7cea-11e5-889c-7ea7b7e4b795.png)

BUT on CAR-mode....OsmAnd takes me to an adjecent industrial area, maybe the most close way with car-acces. But you cannot reach 33 from there, because a canal is running in between..:
![2015-10-27 19 40 57](https://cloud.githubusercontent.com/assets/15076257/10770339/0c865406-7ceb-11e5-8a06-d29a41edf0ff.png)

If you navigate to housenumber 37 the CAR-mode takes you to the trunk-highway N11 - indeed close, but you can't walk from N11 to Vlietkade:
![2015-10-27 19 42 31](https://cloud.githubusercontent.com/assets/15076257/10770433/95febbba-7ceb-11e5-9cc0-89fc3d872c00.png)

Maybe, in future .... on CAR-mode OsmAnd c/should navigate to the crossing of Vlietkade and Overtocht (the "shortest route by feet, from destination to a road with car-acces"), and tell us to "get out of the car" and walk the last 150m.....

In The Netherlands there are many more similar situations.

Good luck,

CJTmmer

**Comment by vshcherb** [comment]
So far, OsmAnd picks up the closest accessible road to the destination, which may be not the best option and it could take into account close roads accessible to the parking, which might be not the closest by distance.

**Comment by vshcherb** [comment]
It is not planned to be fixed in coming releases
