### ISSUE TITLE
Elevation seems to high

### ISSUE THREAD

**Issue by DavidHenryThoreau** [osmandapp/OsmAnd#18446]
### Description

Before latest update elevation seems lower than after the update.

### Steps to reproduce

On a GPX record I'm using 
`Options > Elevation correction > altitude calculation > off line calculation`

Results is empty

 

### Actual result

Before with that I can calcul elevation, now results is too high.

### Expected result

Sum elevation gain and elevation down correctly.

### Your Environment (required)

Latest F-Droid : 4.5.10

**Comment by DmitryAlexei** [comment]
Please provide your .gpx tracks (or screenshots and start/end points of your routes) and describe what are you comparing with what.
Also see technical documentation https://docs.osmand.net/docs/technical/algorithms/calculate-uphill-slope/

**Comment by DavidHenryThoreau** [comment]
https://docs.osmand.net/docs/technical/algorithms/calculate-uphill-slope/#altitude-srtm-correction

I only have offline but not online since update.
Does online disapears or needs to be enabled ?

**Comment by DmitryAlexei** [comment]
@DavidHenryThoreau Calculate Online is available only with map rendering engine Version 1 (menu > settings > OsmAnd settings > map rendering engine)

**Comment by DavidHenryThoreau** [comment]
You've find what I was looking for !
Thanks a lot :+1:
