### ISSUE TITLE
OsmAnd Routing Problem

### ISSUE THREAD

**Issue by Sonwon1** [osmandapp/OsmAnd#18458]
### Describe the routing engine used (required)

- [X] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Describe your routing Profile (required)

Motorcycle profile, same with Car profile
Fastest route: off
Consider temporary limitations: on or off makes no difference

Avoid Roads;
No toll roads: on
No unpaved roads: on
No border crossings: off
Avoid low emissions zones: off
No ice roads or fords: on
No ferries: off
No shuttle train: on
Avoid tunnels: off
Avoid 4WD roads: on
No motorways: on

### Describe your start and end points (required)

Start: 47.415082 10.852254
End: 47.405029 10.869702

### Describe the actual route (required)

OSMAnd routes like this:
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/141348374/d721f03a-12f3-45e6-b758-afe66f38cde7"  width="600" height="auto"/> </td>
  </tr>
</table>

### Describe the expected route (required)

Just changing the router to bRouter gives this correct route.

bRouter and Google maps routes like this:
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/141348374/b80e45d5-a934-45d8-b0c5-26ae22695fb3"  width="600" height="auto"/> </td>
  </tr>
</table>

### Describe what Maps you used (online or offline) (required)

- [X] Offline maps offered within the OsmAnd app for download. 
- [ ] Online (tile / raster) maps 

Austria Oct 1, 2023

### Your Environment (required)

```
OsmAnd Version: OsmAnd 4.5.10
Android/iOS version: Android 13
Device model: Sansung Galaxy Tab Active 3
```

### Anything else? (optional)

I originally discovered this while on a tour when OsmAnd routed me down a bicycle path. After I narrowed the route down to the two points it gave me the route posted above.

**Comment by scaidermern** [comment]
Looks like #18215 again?

**Comment by Sonwon1** [comment]
> Looks like #18215 again?

You are correct, I guess I'll have to wait for 4.6.2 to test again.

**Comment by zipav** [comment]
OsmAnd Nightly 4.6.0#946m, released: 2023-10-31

On the latest version of OsmAnd Nightly does not reproduce with route restriction settings on either Motorcycle profile or Car profile.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/654695eb-a3ec-4b24-9241-724b3c653b27"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/7056c57e-c90f-4d3f-ac44-8f410debd28d"  width="300" height="auto"/> </td>
  </tr>
</table>
