### ISSUE TITLE
Country address maps no longer available

### ISSUE THREAD

**Issue by hvdwolf** [osmandapp/Osmand#1845]
There are a number of mail threads dealing about the missing country address maps. Especially now that big countries are split-up and no longer have a general big country map, it is really a much needed feature.
The new roads maps are not generated either for full countries so also there we miss a full country address map.

Please start generating the address maps again.
Or: If this is part of the new search option which already has been mentioned a couple of times, then please explain in the mail group.

Note: Another app that also works with split country maps, simply scans the (for example) available Germany maps and uses the available addresses, instead of making the user choose a region in advance (which you mostly don't know).

**Comment by Max1234-Ita** [comment]
Thanks Harry, I also posted a very similar proposal a few days ago: https://github.com/osmandapp/Osmand/issues/1834
Hope a solution is available soon.

Best things,
Max - Italy

**Comment by hvdwolf** [comment]
Sorry.
I searched the github issues list for "address" but it did not show up
strange enough.

Harry

2015-10-28 13:40 GMT+01:00 Max1234-Ita <notifications@github.com>:

**Comment by vshcherb** [comment]
Indeed they are not the same but very related issues. We also missing road only maps for big countries like France (this I'm not sure did we give up or not), Germany, Russia and others.

**Comment by jf-simon** [comment]
one more thing. now to download for example whole germany, i have to to tap 16 times every region an select the map i want. the possibility to select one whole country would be very useful if the maps are split.

**Comment by Max1234-Ita** [comment]
I Agree with jf-simon's idea. Just consider that Italy has 20 regions...
Basically, it's OK to have separate regional maps, what is missing is an option to manage them as they were a single, bigger package made of multiple modules.

It would also help updating, i.e. with Live update feature: one has to manually check updates for every single map installed: It's ok for development and testing, but once  rolled out, I think some user would soon complain about that.

**Comment by Paviluf** [comment]
I agree, it's great to have separate regional maps (low memory usage) but we really miss an option to manage them as they were a single package made of multiple modules for a country.

It will be great too to have the possibility to download a full country map (lot of memory available).

Like said here https://github.com/osmandapp/Osmand/issues/2539 "Region" should be replaced by "Country" to make a search.

**Comment by sonora** [comment]
Obsolete with new search.
