### ISSUE TITLE
Sorting favorites

### ISSUE THREAD

**Issue by FXBab** [osmandapp/OsmAnd#18453]
### Describe the idea (required)

Hi!
That would be so useful to sort out favorites places by
. Distanve to current location
. Date of creation

Actually just like tracks

Thanks!
FX

### Tell us about the expected behaviour (required)

Now it s sorted just by alphabetic, so not really useable.
Looking for quick search.

### Tell us about alternatives you've considered (required)

Actually nonr

**Comment by dmpr0** [comment]
https://github.com/osmandapp/OsmAnd/issues/16917
