### ISSUE TITLE
Render roller coaster tracks

### ISSUE THREAD

**Issue by paganella31** [osmandapp/OsmAnd#18467]
### Describe the idea (required)

I would suggest adding support for [`roller_coaster=track`](https://wiki.openstreetmap.org/wiki/Tag%3Aroller_coaster%3Dtrack)

### Tell us about the expected behaviour (required)

Usage of such a tag is [growing steadily](https://taginfo.openstreetmap.org/tags/roller_coaster=track#chronology); having the tracks rendered would allow for a finer level of details in the context of theme parks.

### Tell us about alternatives you've considered (required)

Currently, many tracks are double-tagged with a `railway=*` key, so in those cases they are already shown on map. The proposed implementation could then be a first step to avoid such cases and to encourage the correct use of tags.  

### Context (optional)

Also see the Carto implementation: https://github.com/gravitystorm/openstreetmap-carto/pull/4666 (merged, but not yet released)

**Comment by paganella31** [comment]
Related iD issue: https://github.com/openstreetmap/iD/issues/9839

**Comment by DmitryAlexei** [comment]
6800 roller_coaster=track according to [taginfo](https://taginfo.openstreetmap.org/search?q=roller_coaster%3Dtrack#tags)

**Comment by xmd5a2** [comment]
Fixed. Place to test: [https://www.openstreetmap.org/way/692823433#map=18/51.39633/5.98436](https://www.openstreetmap.org/way/692823433#map=18/51.39633/5.98436)
Map: Netherlands_limburg should be regenerated in a couple of hours.
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/3e165fe2-ab08-4308-b48f-c81fa6ac86af)

**Comment by zipav** [comment]
OsmAnd Nightly 4.6.0#1187m, released: 2023-12-10

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/fbd460c1-d05e-4c7d-9b80-92c97ceb390c"  width="300" height="auto"/> </th>
  </tr>
</table>
