### ISSUE TITLE
Map Scale to augment Zoom Level

### ISSUE THREAD

**Issue by malJohann** [osmandapp/OsmAnd#18464]
### Describe the idea (required)

I use OsmAnd Maps with my Boox Tab Ultra C, which is a colour e-ink Android tablet with an e-pencil.

I want to use offline OsmAnd maps the same way I use paper maps. To do this, I need to be able to zoom to a specific scale, like 1:25,000 or 1:50,000. The reason for this, is that protractors work with measurements to determine distance.

So that if I can set the map to a specific scale, I can set my tablet to Sleep mode with a Transparent Screensaver, so the map still displays, while consuming maybe 1% of battery life every 24 hours.

This way I can carry around countless maps in a 500 gram package that reads well in sunlight, and can go for theoretically 3 months without recharging, while using it like a traditional paper map.

In my opinion, and especially as colour e-ink tablets are getting bigger now, this has great potential for people that don’t want to be stuck with maps on tiny screens when they’re on an expedition.

### Tell us about the expected behaviour (required)

The way this would work, is by detecting the resolution and PPI of a screen, and adjusting the scale according to the PPI and available screen realestate.

Esentially PPI is how the software would know how to determine whether the scale is displayed to the correct proportions on the screen.

e.g. A 300ppi screen has 300 pixels per inch, so there’s your measurement, then just fit the number of miles/kilometres to the selected scale according to the number of pixels required.

So you could long press on the “+” zoom button to open a prompt where you can enter the desired scale.

### Tell us about alternatives you've considered (required)

Just using inbuilt GPS, but that would use too much battery power.

### Context (optional)

To cater for all the map scales out there…
1:1,000,000
1:500,000
1:400,000
1:320,000
1:300,000
1:285,000
1:280,000
1:260,000
1:250,000
1:235,000
1:225,000
1:205,000
1:200,000
1:182,000
1:160,000
1:156,000
1:150,000
1:140,000
1:135,000
1:126,720
1:125,000
1:100,000
1:84,000
1:80,000
1:77,000
1:75,000
1:69,500
1:65,000
1:63,360
1:62,500
1:50,000
1:48,000
1:47,520
1:40,680
1:40,000
1:35,000
1:31,680
1:30,750
1:30,000
1:25,000
1:24,000
1:20,000
1:15,000
1:12,000
1:10,000
1:5,000
..and more!…
..ideally you should just be able to enter the map scale manually e.g. have a field like:
“1:<input_value>”

**Comment by tradavyvy** [comment]
Great idea.
Also, with fixed scale it makes it easier to estimate distances in a glance.

**Comment by JRMalherbe** [comment]
This is a feature I would also use

**Comment by malJohann** [comment]
> Great idea. Also, with fixed scale it makes it easier to estimate distances in a glance.

Thanks, please like my post at the top if you will, I think it helps motivate the change.

**Comment by malJohann** [comment]
I added some more useful information to the context section.

Coincidentally I found out today that I can add a screenshot of my map as the shutdown image for my Boox e-ink tablet, thus displaying the map while consuming 0% power!

**Comment by vshcherb** [comment]
To do: on click zoom level widget change to scale but with 1000 ratio i.e. "1:1000 mm/m" = "1:1 000 000"

**Comment by cepprice** [comment]
- Max 3 digits
- If < 1000, 1 digit after comma, otherwise o digits

**Comment by vshcherb** [comment]
- Scale > 1000
      - Scale '1-10 XXX' 2 digit after comma,
      - Scale '10-100 XXX' 1 digit after comma 
      - Scale '>=100 XXX' 0 digits after comma
      - Trailing zeros after comma should be displayed
- Scale < 1000 - no numbers after comma

**Comment by EugeneZmeuk** [comment]
**20.05.2024**
- [ ] [zoom level](https://docs.osmand.net/docs/user/plugins/development#zoom-level) widget (Android), we need to write about more a map scale.
