### ISSUE TITLE
Add icon for parking_space=disabled

### ISSUE THREAD

**Issue by 32Vache** [osmandapp/OsmAnd#18470]
### Describe the idea (required)

OsmAnd currently renders individual parking spaces mapped as `amenity=parking_space` but does not make any distinction between normal parking spaces and parking spaces tagged with `parking_space=disabled`. It would be nice to be able to tell them apart, with an icon for example.

### Tell us about the expected behaviour (required)

![Screenshot_176](https://github.com/osmandapp/OsmAnd/assets/42336759/7d5d1a81-3cb4-47f0-a84a-bb30e4757c97)

Example here from the French OSM Carto, disabled parking spaces are shown with a special icon.

### Tell us about alternatives you've considered (required)

If not adding an icon, I guess making the outline blue would also be a good improvement.

**Comment by goldfndr** [comment]
Have you configured the map to Hide POI icons? They should be visible at [zoom 20](https://github.com/osmandapp/OsmAnd-resources/blob/master/rendering_styles/default.render.xml#L6789) with the OsmAnd map style.

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#984m, released: 2023-11-06 not reproduced
Tested on https://www.openstreetmap.org/way/1144797407 (coordinates) tagged with amenity=parking_space and parking_space=disabled
Actual result: 
- parking place for disabled is rendered starting from 20 zoom level
- **icon for parking_space=disabled is not listed in Map Legend** (here https://osmand.net/docs/user/map-legend/osmand#parking or here https://osmand.net/docs/user/map-legend/osmand#traffic-transportation )
- see screenshots

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/a916e962-4f81-4154-8b70-ee04884dacbb"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/f47efbd6-d474-4eb3-8033-604284803bd7"  width="300" height="auto"/> </td>
  </tr>
</table>
