### ISSUE TITLE
Map Style Editor

### ISSUE THREAD

**Issue by FabiRich** [osmandapp/OsmAnd#18483]
Good evening,

I just want to know if there is a map style editor for OSMAnd, because creating custom rendering files doesn't suit my needs. I have tried a few modifications.
Is there an editor like [Maputnik Editor](https://maputnik.github.io/editor/#0.43/0/0)?

And where do I set the text rendering option so that the text is only displayed when it can be displayed at the moment and not the other way round, as in this attached image.
![IMG_20231101_175905](https://github.com/osmandapp/OsmAnd/assets/76914324/d7e1c2bc-8ca4-4582-ba65-6a976970cf18)

Best regards

**Comment by DmitryAlexei** [comment]
There is no such option now. So It sounds like a feature request.

**Comment by vshcherb** [comment]
We have OsmAndMapCreator for testing please check documentation

**Comment by mikehgentry** [comment]
The text reproduction is still a little bit buggy in places in rendering engine v2 (OpenGL) - you might find you prefer v1, and the switch is in general settings.

**Comment by FabiRich** [comment]
Thanks for the suggestion, but I was using v1 and v2 actually works better, but not perfectly. Is there a setting in the render xml file that the text is only displayed if it is not wrapped?
Best regards

**Comment by FabiRich** [comment]
@vshcherb I've tried the OsmAndMap Creator, but I don't want to create new map files, just a render.xml file. I could see that I can render it offline with a custom render file, but that's not really helpful in creating a new file. But you could test a custom render file with it of course.
