### ISSUE TITLE
Return department_store in query "Apparel store"

### ISSUE THREAD

**Issue by ghost** [osmandapp/Osmand#1848]
As of 2.1.1 [shop=department_store](https://wiki.openstreetmap.org/wiki/Tag:shop%3Ddepartment_store) does not show up when searching for clothes "Apparel store".

**Comment by xmd5a2** [comment]
It's a very confusing tag because wiki https://en.wikipedia.org/wiki/Department_store says that not only clothes can be sold in this type of shop. I think that a large percent of department stores in osm database also sells not only clothes.

**Comment by twzkxkan** [comment]
In the US department stores sell often sell other goods besides clothing, but I do not know of shops that would be called department stores without a clothing department.

Are there department stores that do not sell clothing? Are they common?

The point of the query would be to find somewhere to buy clothing, which a department store would likely have in countries I know of.
