### ISSUE TITLE
Ski routing: oneway=no on aerialway is ignored

### ISSUE THREAD

**Issue by QuercE** [osmandapp/OsmAnd#18480]
### Describe the routing engine used (required)

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Describe your routing Profile (required)

ski

### Describe your start and end points (required)

Both ends of Borest aerialway=gondola : https://www.openstreetmap.org/way/321146973.
Specifically going eastward: 
- starting at https://www.openstreetmap.org/node/2609297154 (Borest western end station),
- ending at https://www.openstreetmap.org/node/1638308214 (Borest eastern end station).

### Describe the actual route (required)

route according to OsmAnd: 
https://osmand.net/map?start=46.549824%2C11.853970&end=46.548161%2C11.871077&mode=ski#11/46.401928/11.808757 

The ski route goes all the way around the mountain massif, instead of just using the aerialway eastward. 
See following screenshot:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/12443450/3210b7bd-6a32-4d30-8740-dde3d4d95c2e"  width="300" height="auto"/> </td>
  </tr>
</table>

### Describe the expected route (required)

expected route: going eastward only along the Borest aerialway=gondola
(= the exact opposite of this route in following screenshot: )
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/12443450/ddf901f5-84a1-4e6f-8804-e7d275c66460"  width="300" height="auto"/> </td>
  </tr>
</table>

Since the aerialway is tagged with oneway=no, (ski) navigating along https://www.openstreetmap.org/way/321146973 should be possible in both directions.

Routing according to the ‘normal’ (westward) travel direction of the way is possible. However, navigating in opposite (eastward) direction is impossible and results in a (huge) detour, since the gondola is the only direct connection between 2 parts of the ski area, without any adjacent/nearby ski pistes providing a direct ‘skiable’ alternative. 

Moreover, the eastward travel direction along this aerialway is an essential part to be able to complete the [orange=clockwise Sellaronda](https://www.openstreetmap.org/relation/1819421), a very popular marked ski tour in the area. 
 
More general, this issue (probably) occurs at every aerialway marked with oneway=no.
The expected behaviour is that ski routing should be enabled in both directions when explicitly tagged this way. Now it seems oneway=no on aerialways is still ignored in ski routing. 

(Of course the penalty for taking aerialways, especially against their normal direction when allowed, should stay reasonably high, to give preference to actual piste skiing (e.g. along valley descents nearby: the descent via aerialway is then a possible but secondary/discouraged alternative) 

This issue is actually similar / the same as issue #16061 considering oneway=no for routing on ski pistes. That issue has successfully been solved, but only for piste ways, not for aerialways.

### Describe what Maps you used (online or offline) (required)

- [x] Offline maps offered within the OsmAnd app for download. 
(italy_trentino-alto-adige_europe + italy_veneto_europe standard maps, edition 2023-11-01)
- [ ] Online (tile / raster) maps 

### Your Environment (required)

```
OsmAnd Version: OsmAnd~ 4.6.0#949m (2023-11-01)
Android/iOS version: Android 13
Device model: Samsung Galaxy A52s
```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. Follow these steps to observe the issue:

- Enable the ski profile.
- Download the map of Trentino-Alto Adige/Sudtirol, Italy (making sure to enable live updates).
- Input the starting coordinates as 46.54816, 11.87108 and the finishing coordinates as 46.54982, 11.85397. View the result.
- Swap the coordinates and recheck the result.
- As a result of this process, the starting coordinates 46.54816, 11.87108 and the finishing coordinates 46.54982, 11.85397 will display the correct outcome. However, when you switch the starting coordinates to 46.54982, 11.85397 and the finishing coordinates to 46.54816, 11.87108, the route will not be calculated at all.

It's worth noting that in the web version, the one-way route is accurately calculated, but in the opposite direction, the route is computed with a significant detour. You can see the uncorrect route in the web version here: [Link to the web version](https://test.osmand.net/map/?start=46.549820,11.853970&finish=46.548160,11.871080&type=osmand&profile=ski#11/46.5492/11.7602)

Additionally, you can compare this with the route calculated in OpenStreetMap here: [OpenStreetMap Route](https://www.openstreetmap.org/directions?engine=fossgis_osrm_foot&route=46.5482%2C11.8711%3B46.5498%2C11.8540)

OsmAnd~ 4.6.0#962m, released: 2023-11-02

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/12284128-6719-4601-b724-1e3c7f2dae13"  width="250" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/45c9ddea-b903-4220-b86a-c056543fb991"  width="250" height="auto"/> </th>
  </tr>
</table>

<table style="width:200%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/dd91a044-2c6f-4b3f-92aa-dd8cf0a5b26c"  width="700" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/e6d217cf-68a8-4706-969d-8c7b5ddddf98"  width="700" height="auto"/> </th>
  </tr>
</table>

**Comment by xmd5a2** [comment]
Fixed. Italy_trentino-alto-adige_europe map will be regenerated in a couple of hours.

**Comment by yuriiurshuliak** [comment]
The bug has been fixed. Currently, the route is calculated in two directions. 
Everything works correctly in the web version too.
https://test.osmand.net/map/?start=46.549820,11.853970&finish=46.548160,11.871080&type=osmand&profile=ski#15/46.5511/11.8518

OsmAnd~ 4.6.0#1071m, released: 2023-11-22

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/640834f4-19d8-4857-94eb-981001967b03"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/a0ce8ee8-fe18-4f23-a2e3-f33d28c2b712"  width="300" height="auto"/> </th>
  </tr>
</table>
