### ISSUE TITLE
Live data rendered although base map is disabled

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#18487]
### Description

OsmAnd renders live data even if the corresponding base map has been disabled.

This isn't really a problem, but looks very strange and probably has a few performance impacts.

### Steps to reproduce

* Download live data for a region
* Disable the corresponding base map

### Actual result

The base map disappears but live data is still rendered.

| base map enabled | base map disabled |
| --- | --- |
| ![01](https://github.com/osmandapp/OsmAnd/assets/1040784/ea8ac329-4f40-4744-a11b-7b7618db07ce) | ![02](https://github.com/osmandapp/OsmAnd/assets/1040784/e0e7a23c-0aaa-4d35-8250-2b1e8e10321e) |

Location: 50.80869,8.76876
(any other location will work the same, as long as there are recent OSM edits to populate live data)

### Expected result

An empty map.

### Your Environment (required)

```
OsmAnd Version: 4.6.4
Android/iOS version: Android 10
Device model: Samsung S9
```

**Comment by zipav** [comment]
OsmAnd Nightly 4.6.0#983m, released: 2023-11-06

@scaidermern  Please clarify, do you disable Offline Source Map, and leave only Live Updates enabled, or are both Road Map and Source Map and Live Updates downloaded? As i unfortunately don't quite understand the steps for reproducing. 
These screenshots show Offline Source Map + Live Updates, and the second one shows Road Map + Live Updates.

| base map enabled | base map disabled |
| --- | --- |
| ![01](https://github.com/osmandapp/OsmAnd/assets/123936521/6da219b7-6438-45ef-ac11-9c87eecf2c32) | ![02](https://github.com/osmandapp/OsmAnd/assets/123936521/7285476d-2752-4092-89d0-4e9b48adfd13) |

**Comment by scaidermern** [comment]
> @scaidermern Please clarify, do you disable Offline Source Map, and leave only Live Updates enabled, or are both Road Map and Source Map and Live Updates downloaded?

Roads-only map is not involved. I only have the full base map + live updates. After disabling the base map, live updates are still displayed.

If you try to reproduce this now your result will look differently. That's because most of the live data from my second screenshot is now contained in the new base map from November.

**Comment by zipav** [comment]
OsmAnd Nightly 4.6.0#999m, released: 2023-11-08

Live Updates when all offline maps are disabled disappear at 8 zoom or less.

| Offline map of Hessen + Live Updates | only Live Updates enabled|
| --- | --- |
| ![01](https://github.com/osmandapp/OsmAnd/assets/123936521/662c5eaf-6f82-46af-894b-a44bb7a44e66) | ![02](https://github.com/osmandapp/OsmAnd/assets/123936521/2550f546-0003-42fa-a55d-4f8bde5bda81) |

**Comment by DmitryAlexei** [comment]
Related issue https://github.com/osmandapp/OsmAnd/issues/18325

**Comment by zipav** [comment]
OsmAnd Nightly 4.7.0#1402m, released: 2024-01-21

| Offline map of Hessen + Live Updates | Offline map of Hessen disabled|
| --- | --- |
| ![01](https://github.com/osmandapp/OsmAnd/assets/123936521/25b16375-37db-4c76-9756-637968625c17) | ![02](https://github.com/osmandapp/OsmAnd/assets/123936521/5b9056ec-d16d-426e-a31a-84c9634ba9fd) |
