### ISSUE TITLE
POIs with name_only="true" can't be found via POI search

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1850]
These POIs can't be found if for example I type "canal" in POI search. But they can be found if they are part of poi_filter (type "water supply").
```xml
<poi_type name="canal" tag="waterway" value="canal" name_only="true"/>
```
But what if I want to search for just a canal? There are many more examples:
```
square (I think it can be useful to search for a square by name)
industrial
vineyard
orchard
allotments
forest
commercial
construction
retail
residential
```
and so on. Please correct this.

**Comment by vshcherb** [comment]
It could be easily corrected here: 
https://github.com/osmandapp/Osmand/blob/master/OsmAnd-java/src/net/osmand/osm/MapPoiTypes.java#L171
Change 
```if (pt.isReference() || pt.isNameOnly()) {```
to 
```if (pt.isReference()) {```
But I don't have strong feeling it is right thing to do, please try it and revert if you don't like.
