### ISSUE TITLE
A purchase page for OsmAnd~ to use OsmAnd Start

### ISSUE THREAD

**Issue by dylanmorroll** [osmandapp/OsmAnd#18507]
### Describe the idea (required)

As far as I can on OsmAnd~ 4.5.10, there is no purchase page in the settings. However, this means it isn't possible to use the new free OsmAnd Start settings and favourites sync.

### Tell us about the expected behaviour (required)

The purchases page should be available to view on OsmAnd~, with the payment options removed/disabled, so you can setup the OsmAnd Start cloud integration.

### Tell us about alternatives you've considered (required)

As all the payment options require google integration, there is no way to use OsmAnd Cloud with OsmAnd~. The new OsmAnd Start is a great way around this, but it currently there is no way to set it up.

### Context (optional)

Related issue: [OsmAnd Pro subscription without in-app payments (e.g. GitHub Sponsorship) · Issue #17681 · osmandapp/OsmAnd](https://github.com/osmandapp/OsmAnd/issues/17681)

**Comment by scaidermern** [comment]
You are probably referring to the F-Droid version of OsmAnd? This is an unofficial version created by the F-Droid maintainer. I guess you have to get into contact with them by creating a ticket at the F-Droid issue tracker.

**Comment by dylanmorroll** [comment]
Ahh didn't know that, got ya, thanks! Will do :)

**Comment by dylanmorroll** [comment]
For anyone looking btw, this is the relevant issue:
https://gitlab.com/fdroid/fdroiddata/-/issues/3074
