### ISSUE TITLE
Graphhopper change API url support: /vehicle vs /profile

### ISSUE THREAD

**Issue by shaohme** [osmandapp/OsmAnd#18508]
### Describe the idea (required)

I can see the latest Osmand supports online routing using Graphhopper servers. I have tried install a Graphhopper (8.x) instance locally but found that the /route API demands 'profile' param by default ( probably because I have misconfigured something) and does not have 'vehicle' param. Osmand currently produces a URL like so and Grasshopper respond like so:

> 2023-11-05 15:03:49.335 [dw-56 - GET /route?point=<redacted>&point=<redacted>&vehicle=car&details=lanes] INFO  c.g.h.IllegalArgumentExceptionMapper - bad request: profile parameter required
> java.lang.IllegalArgumentException: profile parameter required
>	at com.graphhopper.http.ProfileResolver.resolveProfile(ProfileResolver.java:42)
>	at com.graphhopper.resources.RouteResource.doGet(RouteResource.java:133)

Is the current implementation intended for a different or public version Graphhopper, or just unmaintained with latest API changes, or simply not made to support locally installed Graphhopper instances?

### Tell us about the expected behaviour (required)

Osmand Graphhopper plugin should support latest versions.

### Tell us about alternatives you've considered (required)

I have not considered other implementations.

**Comment by DmitryAlexei** [comment]
Have you entered a valid API key?

**Comment by shaohme** [comment]
> Have you entered a valid API key?

I'm not using the public Graphhopper service, but a locally installed instance without API keys, as far as I can tell

**Comment by scaidermern** [comment]
https://graphhopper.com/maps/ also wants `profile=` instead of `vehicle=`.

This isn't new, according to https://www.graphhopper.com/blog/2021/12/15/new-and-customizable-routing-profiles/

```quote
Deprecation of Parameters for the Routing API

[...] Furthermore you should start using the profile parameter instead of the vehicle parameter.
```

**Comment by shaohme** [comment]
> https://graphhopper.com/maps/ also wants `profile=` instead of `vehicle=`.
> 
> This isn't new, according to https://www.graphhopper.com/blog/2021/12/15/new-and-customizable-routing-profiles/
> 
> ```
> Deprecation of Parameters for the Routing API
> 
> [...] Furthermore you should start using the profile parameter instead of the vehicle parameter.
> ```

Then how come the Graphhopper plugin for Osmand doesn't seem to use it?

**Comment by shaohme** [comment]
@vshcherb @scaidermern 
Could we please re-open this issue? I would like to branch osmand and implement it myself ..

**Comment by scaidermern** [comment]
> @vshcherb @scaidermern Could we please re-open this issue? I would like to branch osmand and implement it myself ..

I can't do that, I'm just a regular user like you. Unfortunately sometimes tickets get closed here without getting fixed properly. 

@vshcherb If the GraphHopper interface hasn't been updated to the latest state then this ticket must be reopened.

**Comment by vshcherb** [comment]
As I remember it was possible to configure differently on own webserver so both configurations are equivalent. Obviously that feature was tested once it was implemented so I'm not sure what is the best correct way

**Comment by scaidermern** [comment]
The official blog suggests to switch from vehicle to profile parameter. Maybe add a switch to choose between both versions? At least for a while until the old vehicle parameter disappeared from typical GraphHopper instances.

**Comment by shaohme** [comment]
> The official blog suggests to switch from vehicle to profile parameter. Maybe add a switch to choose between both versions? At least for a while until the old vehicle parameter disappeared from typical GraphHopper instances.

Would be nice. If we know which version this was officially changed we could add a "Version > X.X" button or similar.

We could also act on the return web response and suggest/hint the user to change/button if the request fails.

**Comment by vshcherb** [comment]
If it's an easy switch and no need to support old, just create a Pull Request.

**Comment by shaohme** [comment]
Just a small update. I have been busy with other work, but I should share a little update.

If anyone having same problem when running more recent Graphhopper, like I described initially, this can be mitigated with a simple URL rewrite. In my setup, a nginx reverse proxy is servicing Graphhopper requests and alters the requests before they reach Graphhopper, like so:

```
    location /osm/route {
        if ($arg_key != "abcd1234") {
            return 401;
        }
        # old osmamd+ GH plugin use 'vehicle' instead of 'profile'
        if ($args ~* "(.*)(vehicle=)(.*)") {
            set $args "$1profile=$3";
        }
        # details=lanes is rejected by GH 8.x
        if ($args ~* "(.*)(\&details=lanes)(.*)") {
            set $args "$1$3";
        }

        proxy_pass http://localhost:8989;
    }

    location /osm/maps/config.js {
        alias /etc/graphhopper/config.js;
    }

    location /osm {
        proxy_pass http://localhost:8989;
    }

    location /osm/admin {
        proxy_pass http://localhost:8990;
    }

```

I plan to work new API into the Osmand plugin and perhaps utilize more feature and currently exists, like avoiding roads, and others...
