### ISSUE TITLE
Android Auto - changing Settings button to Sound button

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#18513]
### Describe the idea (required)

Now, there are two steps on the screen: Settings button ⚙️ > Voice prompts on /off
|Settings button ⚙️| Voice prompts on/off|
|----|----|
|![telegram-cloud-photo-size-2-5352839937852035791-y](https://github.com/osmandapp/OsmAnd/assets/44466116/4fd35aff-c355-451f-8ee1-f3940d7fb5a4)|![telegram-cloud-photo-size-2-5352839937852035792-y](https://github.com/osmandapp/OsmAnd/assets/44466116/e28ba470-4769-424d-b349-fa1669ad1de1)|

My proposition is to make the Sound button 🔇  🔈 except the Settings button ⚙️

<img width="575" alt="image" src="https://github.com/osmandapp/OsmAnd/assets/44466116/4c2b16ce-a141-46f2-a57a-c5c35d389585">

### Tell us about the expected behaviour (required)

🔈 - voice prompts on
🔇 - voice prompts off

### Tell us about alternatives you've considered (required)

no

**Comment by dmpr0** [comment]
Android Auto has limitations on the UI, such as how many buttons or list levels we can use. If we change the Settings button to one specific option, we wouldn't be able to add other options related to setting or route parameters. 
* https://github.com/osmandapp/OsmAnd-Issues/issues/1782
* https://github.com/osmandapp/OsmAnd-Issues/issues/1895
