### ISSUE TITLE
Context menu: Some remaining issues with Favorite operations

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#1851]
Issues found as follows:

(1) When CREATING a new favorite, the "Replace" button is very visible on the top of the dialogue, while the "Save" button is elsewhere, much less visible on the top of the screen. Both need to be moved next to each other (suggest top of the dialog, as top of the screen moves outside the visible area when the keyboard appears, which is also awkward).

(2a) When EDITING a favorite, a slightly different problem exists: The "DELETE" button is on the top of the screen, and not visible any more after the keyboard pops up.

(2b) Also when EDITING, any changes to the text fields (like the name) become immediately effective when tapping the devices back button or even just tapping the map (unlike for all other operations where we usually have a "Save" button). I suggest (2a) and (2b) need to be fixed consistent with (1): Move all operation buttons to one obvious place (like top of the dialog), and make sure it remains visible even when the keyboard is up. 

(3) Side note: Many users miss the confirmation buttons for dialogues on the top of the screen, the Waypoint dialog is another notorious example. The little confirmation tick mark appearing in the top right corner of the screen after e.g. removing some waypoints (via the "Edit" then "X") is often overlooked, so users tap the device's BACK key instead, and silently loose their deletions, and wonder why. Not sure yet how to fix, it seems like an intrinsic weakness of the new UI. Maybe we need a popup confirmation dialog asking whether to apply the savings if a users made edits on any of our new screens screen then leaves without saving them!

**Comment by vshcherb** [comment]
Hope to hear more information soon:
1) did people adopt
2) are there cases when it was not difficult

From original description, it looks like new UI is not that easy to understand, though Google Contacts uses the same concept

**Comment by sonora** [comment]
Victor, yes, most users adopt it and like it, particularly because it has new functionality, and particularly those users who have experience with similar UIs in other apps.

What I keep reporting is the things we still need to change, e.g. optically (important action buttons like "SAVE"not well visible, or related buttons like CREATE / REPLACE separated unnecessarily far), or where we really still have bad beginner's mistakes in the UI, like where you can accidentally create some element or action by one accidental tap with no equally easy "UNDO". The waypoint button which quickly creates a waypoint without confirmation is a prime example, like the other things I report in this issue here.

In principle I'd say let's go with the new UI, although we must be aware we will once again fight all the people saying "We hate you for wasting our time because you are re-inventing everything with every new release" ...  :-)

**Comment by vshcherb** [comment]
I agree, maybe we need to add icon to SAVE button, so it will indicate better.

**Comment by sonora** [comment]
Perhaps and / or add a confirmation dialog if a user backs out of a screen  (usually via the back button) without saving any changes they made.

**Comment by vshcherb** [comment]
If you tap on the screen, the changes will be saved. They won't be saved only if you press button back.

**Comment by sonora** [comment]
I found out. But it is far from obvious  :)

**Comment by sonora** [comment]
Regarding the Waypoint button and behavior, we have made some great progress on Nov 16. I think the following 2 things should still be done.
- On the waypoint list appearing after tapping the context menu's waypoint button, in the list of waypoints let us highlight the newly added entry in orange font for better discoverability of what has happened
- Harmonize the behavior of the waypoint list like we have it for editing: When tapping the device's BACK button, you should end up on the Context menu again, and the waypoint should NOT be added (instead you need to tap the SAVE button to save it).

If we do not do this, we create a discoverability issue for our users: They will try to find out what the buttons on the bottom row of the context menu mean b tapping them one after the other. Then subsequent tapping the device's BACK key should always put them back on the context menu with no changes made. But the waypoint button (and only this)  for now behaves very different, it adds a waypoint and puts you back on the map screen. 
 
Other than that, on the Context menu, I think adding a "Show POI description" item (which pulls up the bubble, for the sake of discoverability) to the 3-dots menu is the remaining showstopper we should implement before a release.

**Comment by vshcherb** [comment]
I'm just reitrating all the issues I didn't reply. 
Your observation are correct but I think they are not that important for users. Waypoint always add to the end (we can highlight or may be even sort differently, so it will be always on top). We try to make sure that everytime you add something it immediately displays on the screen. It is the most easy to feel and to understand pattern, if you added - it shows, if you didn't - it doesn't show. So it is more important to check that if you add a favorite, it always show on the screen. I think, that reaction is natural.

**Comment by stragu** [comment]
I was about to report an issue titled "no way to save a new favourite" because the button is so tricky to see, especially because "replace" is so obvious - I assume that the contrast makes it even less discoverable. Not sure if I am particularly unlucky or unobservant, but it did take me about 8 tries (over two months) and the discovery of this here thread to find the "save" button :)

**Comment by sonora** [comment]
We can call this fixed, I guess.
