### ISSUE TITLE
World overview map - Austria / Germany border issues

### ISSUE THREAD

**Issue by poeticus** [osmandapp/OsmAnd#18531]
### Description

The latest World overview map (30/10/2023) shows no border between Austria and Germany (see screenshot). Also most of the German border is shown lighter than other borders. World overview map (mini) (13/09/2023) renders the borders correctly.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/118109677/d1d84e85-6420-4f08-b905-422558b73fa1"  width="300" height="auto"/> </td>
  </tr>
</table>

### Steps to reproduce

Install latest World overview map (30/10/23). Deactivate World overview map (mini). View Germany / Austria.

### Actual result

No border is shown between Germany and Austria. Most of German border is shown lighter than other borders.

### Expected result

Border between Germany and Austria shown, all national borders rendered the same. This is the case with World overview map deactivated and World overview map (mini) reactivated.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.5.10
Android/iOS version: Android 12
Device model: Fairphone 3+
Crash-Logs: ?
```

**Comment by scaidermern** [comment]
The southern German border looks like the one from 1938 :thinking: :see_no_evil:

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#1003m, released: 2023-11-09
Issue can be observed with latest World overview map or with World overview map (mini) 
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/527ab173-0e9c-4948-8a62-71f28a1c4510"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/d562bbcc-cbf6-4460-a695-cb913c0e5e64"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
Polygons are broken, will be checked with OSM data looks strange

**Comment by xmd5a2** [comment]
New fixed basemap is published
![Screenshot_2023-11-20_10-41-06](https://github.com/osmandapp/OsmAnd/assets/5829014/3a667f58-7f9f-4e36-a970-41ae84ba9df5)

**Comment by dmpr0** [comment]
# Review 

<table style="width:100%">
  <tr>
    <th>Big basemap</th>
    <th>Mini basemap</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/f09c6fd4-932c-4354-81c9-3d0540f8badd"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/174f6ff4-c26b-4ec1-a830-c67b535e857a"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] Update for Mini basemap is not available?

**Comment by vshcherb** [comment]
Mini Maps are only updadated with new app version
