### ISSUE TITLE
osmand crashed on android 14 while starting routing

### ISSUE THREAD

**Issue by icegood** [osmandapp/OsmAnd#18539]
### Description

Hello. I already sent a coulpe of bugreports via email since crash. Error occurence: 10/10 since i moved to google pixel 7a.
Exception is:

11-10 18:36:41.976 22968 22968 E AndroidRuntime: FATAL EXCEPTION: main
11-10 18:36:41.976 22968 22968 E AndroidRuntime: Process: net.osmand, PID: 22968
11-10 18:36:41.976 22968 22968 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at net.osmand.plus.views.layers.base.BaseRouteLayer.getRouteLineWidth(BaseRouteLayer.java:180)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at net.osmand.plus.views.layers.RouteLayer.drawLocations(RouteLayer.java:447)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at net.osmand.plus.views.layers.RouteLayer.drawLocations(RouteLayer.java:218)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at net.osmand.plus.views.layers.RouteLayer.onPrepareBufferImage(RouteLayer.java:185)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at net.osmand.plus.views.OsmandMapTileView.drawOverMap(OsmandMapTileView.java:1096)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at net.osmand.plus.views.OsmAndMapLayersView.onDraw(OsmAndMapLayersView.java:84)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.View.draw(View.java:23889)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22756)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22712)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22712)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22712)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22712)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22712)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22712)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22712)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22712)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22712)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4540)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4513)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22712)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:694)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:700)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:798)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4939)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4643)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3822)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2465)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9305)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1339)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:882)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:958)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8177)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
11-10 18:36:41.976 22968 22968 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

full log for pid=22968 will be attached.

### Steps to reproduce

Choose destination and press 'start'

### Actual result

app crashed

### Expected result

routing starts

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.5.10
Android/iOS version: 14
Device model: Pixel 7a
Crash-Logs: ?
```

**Comment by icegood** [comment]
https://drive.google.com/drive/folders/1GP5-GpMvyyh1AT78t2iZ4LMsVsSZx4Rf?usp=sharing

**Comment by icegood** [comment]
probably was fixed in 
c398285cf906f3ee3c4b4e08dc142e42ea577031.
Release is needed them

**Comment by vshcherb** [comment]
Yes, nightly build should be ready to test, and next week beta will be.

**Comment by DmitryAlexei** [comment]
@icegood can you provide us feedback on this issue?
Does everything work now as expected?
