### ISSUE TITLE
Show remaining "Elevation to destination"

### ISSUE THREAD

**Issue by theraser** [osmandapp/OsmAnd#18533]
### Describe the idea (required)

There are a lot of different panel widgets like "Distance to destination", but I'm missing something like "Elevation to destination".

### Tell us about the expected behaviour (required)

For a lot of sports it would be really interesting to know not only the remaining distance, but also the remaining elevation to climb. A small indicator at the left or right side would be nice, just as it there for "distance to destination".

### Tell us about alternatives you've considered (required)

The information is already there and there are two workarounds: the remaining elevation can be shown using the huge "elevation profile" bottom panel, but for me this is just too big and contains too much information for daily usage. The other workaround is opening the navigation view and sliding up the panel each time you want to know the remaining elevation, but this is too complicated. The data is already there, we "just" need a small widget to show the data :wink:

**Comment by vshcherb** [comment]
There is a widget glide ratio, 2nd state displayes elevation at destination. Glide ratio is opposite to Slope/Elevation but we need  a route to properly calculate that.

We plan to redesign Elevation widget to have separate items as small widgets. I think it's a duplicate issue actually, so I'm closing it...
