### ISSUE TITLE
Unable to download "Great Lakes" depth contours I/O Error file not found

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#18536]
## Description
Main task https://github.com/osmandapp/OsmAnd/issues/18185

### How to reproduce
* Open Menu – Download Maps – Nautical maps
* Scroll to Depth contour – Great Lakes, tap Download icon

### Actual result
<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/0d6590a0-2df5-4e9b-9e38-f2f8f08b8e1a
"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/f2709aa1-1322-4880-b253-853fb305d094"  width="300" height="auto"/> </td>
  </tr>
</table>  
</details>  

* `I/O Error file not found`
* Log  file  [logcat (1).log](https://github.com/osmandapp/OsmAnd/files/13316967/logcat.1.log)

### Expected result
* Downloading the file 

**Environment**
OsmAnd Version: 4.6.0#999m 4600
Android: 14
Device model: Pixel 6a

**Comment by vshcherb** [comment]
Same task duplicate?

**Comment by dmpr0** [comment]
No, depth contours and points different files

**Comment by vshcherb** [comment]
Fixed
