### ISSUE TITLE
Symbol invisible on favourites with white background

### ISSUE THREAD

**Issue by Cwpute** [osmandapp/OsmAnd#18532]
### Description

Favorites which use a white background have a white symbol on it. As is, using white points for favourites makes symbols useless.

### Steps to reproduce

1. Create a new favourite point
2. Choose a white background for the shape
3. Choose any symbol
4. Save that favorite
5. Look at favourite on the map

### Actual result

The symbol is invisible, blended with the white of the shape.

### Expected result

The symbol we choose should always be visible no matter what shape colour we choose.
Either allow users to set their symbol colour manually, or do it automatically, detecting when a shape colour is too bright or too dark for it to use the corresponding symbol colour.

### Your Environment (required)

```
OsmAnd Version: 4.5.8
Android/iOS version: Android 11
Device model: Nokia TA-1157
Crash-Logs: x
```

**Comment by DmitryAlexei** [comment]
As a workaround you can use any other color except white

**Comment by mariush444** [comment]
https://github.com/osmandapp/OsmAnd/issues/13207

**Comment by Cwpute** [comment]
This is indeed somewhat the same request, i'll close my issue as a duplicate and add some information there.
