### ISSUE TITLE
wikipedia files not containing sk language

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#1854]
Well, I do not like the new method of wiki files containing articles in all languages for a given country (I liked the language specific files better). But if you like that that way at least they should contain all the languages. I downloaded Slovak wiki file and there is no article in sk language to be found in it. Most wiki POIs show articles in English and can be toggled to other languages but I could not find anything in Slovak (sk). What is going on?

**Comment by vshcherb** [comment]
Slovak language is missing unfortunately, we will regenerate wikipedia files. https://github.com/osmandapp/OsmAnd-tools/blob/master/WikipediaConverter/prepare.sh#L54 and we will add poi filter specifically for wikipedia.

**Comment by xmd5a2** [comment]
Added sk. Started wiki regeneration.

**Comment by aceman444** [comment]
You added sk at line 99, not 54, but maybe that doesn't matter.
Yeah, it seems you only include whitelisted languages. Maybe you should automatically include all languages that OsmAnd supports (has UI translation).
Thanks for fixing this.

**Comment by xmd5a2** [comment]
It doesn't matter.
