### ISSUE TITLE
More conventional Filter icon

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#18546]
I often encounter users completely unaware of the various Filter capabilities we offer in OsmAnd, e.g. to refine searches.

I attribute this to the not very speaking filter icon we use
![Screenshot_20231112-113633_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/845735/ea52b5b6-2ad5-4000-877c-5f7c5339fd86)
Perhaps using something more like this could help fix the issue?
![proxy-image](https://github.com/osmandapp/OsmAnd/assets/845735/21259ad9-03e4-495b-b30f-3d457cd1a6c1)

**Comment by ceever** [comment]
Also consider the three dots, they are more in line with the the rest of the application and Android itself.

![20231119_204036](https://github.com/osmandapp/OsmAnd/assets/40247591/82b9cf88-c31e-4edf-b6b4-09f1a13ef497)

**Comment by dmpr0** [comment]
Done https://github.com/osmandapp/OsmAnd/commit/e223163bba52b545dd75ca336222a4260481117c

<img src="https://github.com/osmandapp/OsmAnd/assets/9365308/dfc57f67-af12-42e7-b7e6-7b60ab016fec"  width="300" height="auto"/>
