### ISSUE TITLE
Bias street name location toward view

### ISSUE THREAD

**Issue by Noitarud** [osmandapp/OsmAnd#18545]
### Description

Street names should be moved into view (does do it sometimes). Image implies another fault (not shown at all).
![Screenshot_20231108-132448](https://github.com/osmandapp/OsmAnd/assets/98794719/c332ed77-6afe-4147-afd5-8257c058a470)
![Screenshot_20231112-195734](https://github.com/osmandapp/OsmAnd/assets/98794719/b73c8dac-52e8-4f80-9318-1afdbe78dc7f)

### Steps to reproduce

Can move view away to hide.

### Actual result

Not shown, or far

### Expected result

i'd like to see them closer to the focal street

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.5.10
Android/iOS version: 10
Device model:
Crash-Logs: ?
```

**Comment by DmitryAlexei** [comment]
Cannot reproduce this behavior on the latest nightly build. OsmAnd~ 4.6.0#1014m, released: 2023-11-12
Probably the display of street names has been improved. Also check if you are using a magnifying glass, this option can be activated by long press on the + or - buttons (see  https://osmand.net/docs/user/map/vector-maps#map-magnifier). If yes, set it to 100%
![photo_2023-11-13_00-37-00](https://github.com/osmandapp/OsmAnd/assets/116079541/66126905-5ac5-47ff-8fbe-ccdc54cd6dc6)

**Comment by Noitarud** [comment]
The ones I wanted to see the most were the ones connected to the highway, the first image is missing three of these. Bartlett Road is not seen in your image - hence why I said "moved into the view".

The second one does show the name of the by-road but because it is curvy the name is in line with the other road - perhaps should be closer?
I almost added above that names should be upside down to avoid seeing "… Road" (incomplete). But that's up to you.

**Comment by vshcherb** [comment]
@Noitarud please test 4.6 we fixed street name display, so it's a bug and we are working to fix these cases
@DmitryAlexei please test 4.5.10 to confirm

**Comment by DmitryAlexei** [comment]
Compared Osmand 4.5.10 and OsmAnd~ 4.6.0#1060m, released: 2023-11-20
- download Australia Queensland map
- coordinates 19.5678718 147.1366315
- tested in landscape and portrait mode. 
- tested 15th and 14th zoom

**Actual result:** Names of residential roads appears at 15th zoom.
Displaying of streets names are almost the same with 4.5.10 and latest nightly build. 
Below you can find screenshots in portrait mode for a better visual comparison (landscape mode the same).

So @Noitarud to resolve your issue you probably needed to redownload (update) Australia Queensland map and / or disable magnifying glass (set it to 100%)


<table style="width:100%">
  <tr>
    <th>Osmand 4.5.10 </th>
    <th>OsmAnd~ 4.6.0#1060m </th>
  </tr>
  <tr>
     <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/bc6ff45c-2fbb-4685-93f7-de0e759f9e00"  width="300" height="auto"/> </td>
     <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/30223f38-13dc-440c-abb6-1fa06a4fa1f5"  width="300" height="auto"/> </td>
  </tr>
     <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/73ba9c69-9bfa-44ff-8ee5-85d84739d709"  width="300" height="auto"/> </td>
     <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/f8e7c0db-3d5b-412a-8c4b-5349383e8b2b"  width="300" height="auto"/> </td>
  </tr>
