### ISSUE TITLE
My location is covered by the elevation profile widget with display position at bottom

### ISSUE THREAD

**Issue by mikehgentry** [osmandapp/OsmAnd#18547]
### Description

My location is covered by the elevation profile widget during navigation if 'display position' is set to bottom or automatic.

### Steps to reproduce

Be in a profile with the elevation profile widget active and display position set to automatic or bottom.

Start a navigation

### Actual result

Position is covered by elevation widget

### Expected result

Position is visible

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: + 4.6.5
Android/iOS version: 11
Device model: XCover 4s
Crash-Logs: ?
```

**Comment by DmitryAlexei** [comment]
Steps to reproduce:
- enable **bottom** display position (go to menu > settings > driving > general settings > display position > bottom)
- enable **elevation profile** widget in bottom panel (go to menu > configure screen > bottom panel > elevation profile widget > add )
- start navigation simulation

Actual result:
- **Elevation profile widget covers *My location* icon** (see video)

Expected result:
- *My location* even when display position is set to *bottom* and *Elevation profile* widget is enabled


https://github.com/osmandapp/OsmAnd/assets/116079541/ca86d713-2fa4-42f5-89ab-14b2ff4a499b

**Comment by vshcherb** [comment]
To do: bottom / top widget should be taken into calculation of bottom / center

**Comment by yuriiurshuliak** [comment]
This bug has been fixed. When the bottom display position is activated along with the elevation profile widget in the bottom panel, the widget no longer covers the "My Location" icon; instead, the icon is now positioned more centrally without any overlap.

OsmAnd~ 4.7.0#1218m, released: 2023-12-14

https://github.com/osmandapp/OsmAnd/assets/127092082/d6bd1958-e87c-4bac-a7bd-086c18049216
