### ISSUE TITLE
No name of streams in map

### ISSUE THREAD

**Issue by moonraver** [osmandapp/OsmAnd#18548]
Hello,
Osmand map is not showing name of the streams in Slovak republic. I am an OSM mapper and I use Osmand+ 4.6 nightly and I can see in JOSM that there are names for streams like Dobranský potok, Kubrica, Černatina, Teplička, Súčanka but these names are not visible in map.
Thank you.

**Comment by DmitryAlexei** [comment]
Duplicate of https://github.com/osmandapp/OsmAnd/issues/18398
