### ISSUE TITLE
Setting widgets 

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#18541]
### Describe the idea (required)

1.Setting widget opacity separately for each panel.
2.Ability to use a dark theme in widgets, regardless of the day/night settings of the map

### Tell us about the expected behaviour (required)

With the appearance of all widgets in the bottom panel, for ease of use it needs to be set to opacity, and I want to replace the white background color with a dark one.

### Tell us about alternatives you've considered (required)

No.

**Comment by dmpr0** [comment]
Duplicate https://github.com/osmandapp/OsmAnd/issues/16017, https://github.com/osmandapp/OsmAnd/issues/14957
