### ISSUE TITLE
Allow to toggle current position button before location known

### ISSUE THREAD

**Issue by Noitarud** [osmandapp/OsmAnd#18543]
### Describe the idea (required)

I would like the app to register my interest in seeing my position after starting app.

### Tell us about the expected behaviour (required)

Presently pressing the current position button gives "position not yet known".  But I would like app to register my interest and [place a ring around button] to indicate, and going to my position when it gets the position, even if I am toying with the map. If I don't want to be auto-centred I can untoggle the button (or add forewarning).

### Tell us about alternatives you've considered (required)

This is so I don't have to keep checking the colour of the button and so I can get started as soon as it is ready.

**Comment by DmitryAlexei** [comment]
Please enable *Google play services* as a location source (see https://osmand.net/docs/user/personal/global-settings#location-source).  With this option enabled, location information will be available almost immediately after start of the app.

**Comment by Noitarud** [comment]
I didn't want to do that… plus it shouldn't work if I had just turned on the device's GPS…
