### ISSUE TITLE
(Partial) screen touch lock feature requested

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#1855]
I have a user complaining that we dropped our former screen lock feature. Not sure that we did, actually, but I cannot find it anymore myself for now.

What the user actually requests is a feature which ignores all touch operations on the OsmAnd map screen except the zoom buttons, like supposedly some other outdoor apps have it, Apparently this is meant to aide operation with gloves on some devices.

Not sure it is a valid request and does not complicate our app too much. Maybe a screen touch lock could also be performed by some third party app. But we could treat this as a feature request to evaluate.

**Comment by vshcherb** [comment]
The feature was dropped because we redesigned status bar and another reason why it didn't get enough attention because screen touch lock doesn't affect other buttons screen buttons which makes it half usable. Still this is a valid request I think.

**Comment by raindropsfromsky** [comment]
Recently I undertook several trips within the city, with my co-driver looking at OsmAnd screen (the device was not mounted on a phone-holder).

The experience was terrible: My phone has a very thin bezel, which meant that my wife/daughter ended up touching the screen unintentionally. In some cases the display went haywire, but in 2 cases the route itself changed, as a waypoint got added somehow. I had to stop the car to edit the route again (not easy on busy roads).

Moral of the story is, the screen lock is urgently needed.

**Comment by Al-Hun** [comment]
Hi !
Very interested too by the lock screen feature's return...
When running in places that need several upates I usualy keep my smartphone in hand, to limit the time needed to take notes. For the moment I must turn off the screen to avoid unwanted manipulations, so when I turn it on back again I have to unlock the phone...
Recent phones have very often thin edges, and holding it is enough, even just with the palm, to touch the screen.
Thanks.

**Comment by utack** [comment]
I have the problem @Al-Hun is having when dropping the phone in my pocked for a minute, I don't want to enter the pin again just to take a note.

**Comment by ntruchsess** [comment]
OSMAnd did have this feature until some month ago: [see the little lock-symbol in this linked screenshot](https://tiefendeswaldes.files.wordpress.com/2013/07/osm_tour.jpg?w=500&h=312).

I's a nuisance it's no longer available. I used it a lot when cycling in rainy/wet/damp conditions. Without this feature osmand is nearly useless and unusable as soon a few drops hit the screen.

Perfect would be if one could disable the complete touchscreen including the onscreen zoom-buttons and allow to zoom in/out via the volume-buttons.

**Comment by agilob** [comment]
I would like to add to this request, I really liked this feature, it was quite unique for OsmAnd to have it and I found it really useful. Motorcyclist have waterproof cases which still allow to control phone with fingers through the case, sometimes when it's raining or phone jumps on bumps, screen detects it as a tap and changes zoom or shows me notification list, that's just annoying, but can live without it. I would be happy if it went back as a plugin or something.

**Comment by sonora** [comment]
Looks like no action planned here for now(?).

**Comment by kxrob** [comment]
Yet the reapperance of this feature is still urgently needed. Please reopen.
