### ISSUE TITLE
Access is displayed despite the fact that it is disabled

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#18568]
### Description

Access is displayed despite the fact that it is disabled in the map settings
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/12549744/f358765e-0974-4df9-a503-abc3203debb2"  width="300" height="auto"/> </td>
  </tr>
</table>

### Steps to reproduce

Just look at the roads that have access.

### Actual result

Access is always displayed

### Expected result

Access should be displayed depending on the map settings.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd~ 4.6.0#1032m, Дата выпуска: 2023-11-15
Android/iOS version: 13
Device model: poco f3
Crash-Logs: ?
```

**Comment by DmitryAlexei** [comment]
To disable access restrictions, go to menu > configure map > hide > and toggle access restrictions option (at the bottom of the list).
FYI. This behavior was introduced after completing this issue https://github.com/osmandapp/OsmAnd/issues/10983

**Comment by Nine-Tailed** [comment]
@DmitryAlexei, what then is this switch responsible for now?
![Screenshot_2023-11-16-09-59-09-235_net.osmand.plus-edit.jpg](https://github.com/osmandapp/OsmAnd/assets/12549744/d0759ef6-5648-430a-9bc4-8d903ae02b3b)

**Comment by DmitryAlexei** [comment]
@Nine-Tailed Thanks for the comment! It seems, that this switch doesn't affect anything now.

**Comment by dmpr0** [comment]
Work in progress https://github.com/osmandapp/OsmAnd/issues/10983
