### ISSUE TITLE
Landscape mode widget placement

### ISSUE THREAD

**Issue by surajak** [osmandapp/OsmAnd#18562]
### Describe the idea (required)

When osmand used in landscape mode the widgets (both left and right of portrait mode) are at same position even when we device is in landscape mode, So to get a better user experience and use available space properly,these widgets should be at left top and bottom corners and navigation arrow at right centre. For ex. Many other Osm based and non based navigation apps use this design for landscape mode, MagicEarth navigation app, Google Maps, Sygic Navigation Maps.

### Tell us about the expected behaviour (required)

When using osmand in my car with landscape mode , it's difficult to see next turn and road ahead because of it gets hide behind right top widget. And display looks imbalance leaving lots of space at left and right bottom.

### Tell us about alternatives you've considered (required)

No alternate option to turn this landscape mode design in osmand. Either you have to use in portrait mode Or use MagicEarth in landscape mode.

**Comment by DmitryAlexei** [comment]
To better understand the context, please provide screenshot or short video of your issue.
Also, please add info about app version and device you use.

**Comment by vshcherb** [comment]
I think we just added to 4.6 release. So you can use widgets top/bottom and many in a row
