### ISSUE TITLE
OsmAnd won't route from Trunk highway to Driveway

### ISSUE THREAD

**Issue by mbartlett21** [osmandapp/OsmAnd#18561]
### Description

Navigating to a house that has a long driveway (mapped) that comes off a trunk highway doesn't seem to work. It instead navigates to a different driveway off a different street.

### Steps to reproduce

Navigate from the highway to a house with a driveway attached to the highway.

See this link for an example. (Yes, this also appears when doing the same route on the mobile app)
https://osmand.net/map/?start=-27.642808,151.934626&finish=-27.642834,151.935948&type=osrm&profile=car#18/-27.64148/151.93607

### Actual result

OsmAnd routes to a different driveway that can't access the house.

### Expected result

I expected OsmAnd to use the driveway that is mapped.

### Your Environment (required)

```
OsmAnd Version: 4.5.10
Android/iOS version: 13
Device model: Asus Zenfone 9
Crash-Logs: None
```

**Comment by scaidermern** [comment]
Map data looks fine to me.

**Comment by vshcherb** [comment]
The data is very new ... https://www.openstreetmap.org/way/1222460170
5 days only
