### ISSUE TITLE
Not all display languages are available as map languages too

### ISSUE THREAD

**Issue by l2212** [osmandapp/Osmand#1857]
I've seen that there are a lot less languages in the "Map preferred language" option compared to the "Display language" one. Even some ones with complete translations do not appear on the list.

**Comment by sonora** [comment]
Please understand ha the "Display language" refers to how our app displays its menus and operations, and hence basically simply depends on whether our translators have made a language file with sufficient content available to be included in the app. 

The "Map preferred language", on the other hand, depends on whether places in the map are tagged in a specific language in the original openstreetmap.org map data. And there, mostly names for places on maps will be without any language tag (which is the usual case for the name being in "local language"), or some may have secondary (like often English in countries with non-Latin character sets) or secondary/tertiary languages for countries with multiple domestic languages. 

So if you expect to e.g. see Suaheli names for a lot of places in Germany, you will be disappointed anyway.  :-)  And in places where Suaheli is the primary language the names are specified in that language anyway (without it being explicitly tagged), so having a "Map preferred language" for which not many OSM placed are EXPLICITLY tagged with is not needed.

**Comment by l2212** [comment]
I understand, but there are some exceptions to that. For example:
-Sardinia (Sardinian/Italian names)
-South Tyrol (German/Italian)
-Friuli-Venezia Giulia (Italian/Slovenian)
-Basque country (Basque/Spanish)
-Catalonia (Catalan/Spanish)
-Valencian Community (Valencian catalan/Spanish)
and probably others.
In all those cases there are a lot of multilingual names in the "name" tag in a specific area, leaving the single language names separated, but maybe someone (especially when navigating) could prefer to switch to only one language. In this list that would be possible for four out of six, but not for Basque and Sardinian.

**Comment by xmd5a2** [comment]
Added eu, eo, fa, sc, ka, mk, lb, os, fy, af, hy, ml, ta, als, nds, ku, la, ga, nv, bs, bpy, is, sq, br, mr, az, sh, tl, cy, bn, pms.

**Comment by l2212** [comment]
Ok, thank you very much!
