### ISSUE TITLE
Icon at rest shows heading sector even when no heading is available

### ISSUE THREAD

**Issue by RheinSkipper** [osmandapp/OsmAnd#18575]
### Description

Hi!

I am running OsmAnd on a device that has no heading sensors (Carlinkit T-Box Plus).

At rest OsmAnd shows my position on the map as a blue dot but with heading sector always pointing to the north. This is confusing.

Google maps shows this heading sector only on devices where heading information is available. If not there is just the blue dot without heading sector.

Is there a trick to modify the "position at rest dot" to just a blue dot without heading sector?

Thanks

### Steps to reproduce

Try it on a device that has no heading sensors.

### Actual result

Misleading heading sector is shown on the map. Always pointing to 0° north.

### Expected result

No heading sector should be shown with "icon at rest" if no heading data is available.

### Your Environment (required)

Android 13 on Carlinkit T-Box Plus car navigation system.

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#1108m, released: 2023-11-28

**Steps to reproduce:**
- simulate Pixel 3a in Android Studio 
- Open OsmAnd
- Rotate map in different directions

**Actual result:**
- *My location* is displayed on the map as a blue dot with heading sector
- Heading sector always points to north
- see screenshots

**Expected result:**
- Heading sector shouldn't be displayed if the device doesn't have compass. 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/0ec1170b-e6df-4cb8-88ba-7b7ff7125b02"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/18cef1ac-ef3d-4128-9375-abbefa290be0"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by cepprice** [comment]
@RheinSkipper can you share logs?
1. Menu
2. Plugins
3. OsmAnd development
4. Press on
5. Settings
6. Logcat buffer
7. Press button on right top until `*:E` is shown
8. Share

**Comment by RheinSkipper** [comment]
Here is the log.



Von: cepprice
Gesendet: Sonntag, 10. Dezember 2023 14:03
An: osmandapp/OsmAnd
Cc: RheinSkipper; Mention
Betreff: Re: [osmandapp/OsmAnd] Icon at rest shows heading sector even when noheading is available (Issue #18575)

@RheinSkipper can you share logs?
1. Menu
2. Plugins
3. OsmAnd development
4. Press on
5. Settings
6. Logcat buffer
7. Press button on right top until *:E is shown
8. Share

**Comment by RheinSkipper** [comment]
[logcat.log](https://github.com/osmandapp/OsmAnd/files/13628778/logcat.log)
