### ISSUE TITLE
Nightly crashing on starting

### ISSUE THREAD

**Issue by albansuser** [osmandapp/OsmAnd#18573]
### Description

Over the last few days, since OsmAnd~ 4.6.0#1021m, released: 2023-11-13, the more recent nightlies have crashed on startup. This is on a Samsung S22+ running Android 13.

It appears that a relatively large increment in the APK size is associated with the beginning of the problem. New routines or functions added?

The problem has not been resolved by clearing cache nor a complete uninstall, installing and restoring data by importing from a backup. 

Before restoring data the latter nightly loaded as expected. After restoring data the crashes reoccurred.

The crash seems to be associated with Settings, as opposed to My Places or Resources.

Reverting to #1021 resolves the problem.

Interestingly the same recent nightlies have worked normally on an older mobile Samsung S8 running Android 9. OsmAnd settings are essentially the same between both mobiles (custom profiles, opengl, maps etc).

### Steps to reproduce

Update to recent nightly

### Actual result

Osmand fails to start.

### Expected result

Normal starting and operation

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: since OsmAnd~ 4.6.0#1021m
Android/iOS version: 13
Device model: Samsung S22+
Crash-Logs: ?
```

**Comment by albansuser** [comment]
Thanks.

I emailed the exceptions log to crash@osmand.net on the 15th Nov. The email started "Nightly build of 15th Nov at 02:26 NZ date and time crashes at startup."

Regards

**Comment by albansuser** [comment]
I took a look at the most recent exceptions log and saw repeated references to the External Sensors. 

Using the last functional nightly (#1021) I deactivated the External Sensors plugin and then updated to the most recent nightly (which I'd already tried, but had failed) and the update loaded and worked fine.

Within the latest nightly I attempted to enable the External Sensors plugin. 

A crash report was generated and the nightly restarted but the External Sensors plugin remained disabled.

**Comment by albansuser** [comment]
Have found a way to resolve the issue. But, of course, doesn't necessarily explain the original  cause of it.

Using the last functional nightly (build 1021), I deleted the two paired external HR sensors listed in the external sensor plugin (two different HR sensors).

Then updated to latest nightly build and re-paired the sensors. 

Everthing now works fine.

**Comment by alienff** [comment]
It looks like I am facing the same issue on OsmAnd+ 4.6.6. From logcat:

> 11-24 08:45:05.000 20214 20214 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Set java.util.Map.keySet()' on a null object reference
11-24 08:45:05.000 20214 20214 E AndroidRuntime: 	at net.osmand.plus.plugins.externalsensors.DevicesHelper.updateDeviceProperties(DevicesHelper.java:163)
11-24 08:45:05.000 20214 20214 E AndroidRuntime: 	at net.osmand.plus.plugins.externalsensors.DevicesHelper.initDevices(DevicesHelper.java:152)
11-24 08:45:05.000 20214 20214 E AndroidRuntime: 	at net.osmand.plus.plugins.externalsensors.DevicesHelper.setActivity(DevicesHelper.java:111)
11-24 08:45:05.000 20214 20214 E AndroidRuntime: 	at net.osmand.plus.plugins.externalsensors.ExternalSensorsPlugin.mapActivityCreate(ExternalSensorsPlugin.java:213)
11-24 08:45:05.000 20214 20214 E AndroidRuntime: 	at net.osmand.plus.plugins.PluginsHelper.onMapActivityCreate(PluginsHelper.java:535)
11-24 08:45:05.000 20214 20214 E AndroidRuntime: 	at net.osmand.plus.activities.MapActivity.onCreate(MapActivity.java:296)
11-24 08:45:05.000 20214 20214 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7824)
11-24 08:45:05.000 20214 20214 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7813)
11-24 08:45:05.000 20214 20214 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
11-24 08:45:05.000 20214 20214 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
11-24 08:45:05.000 20214 20214 E AndroidRuntime: 	... 11 more

Is there any way to disable a plugin without starting the app?..
