### ISSUE TITLE
Search results and map (displayed search) results not identical

### ISSUE THREAD

**Issue by ceever** [osmandapp/OsmAnd#18583]
### Description

When searching for something like "Cafe and restaurant" with the name of Yen, as a very specific example, I get 4 results in the region of Da Nang within a radius of 50 km. But then switching to map view displays way more than 4 results.

Screenshots:
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/40247591/a7530fa6-84d5-4b8a-b6e7-ba031f33bc9f"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/40247591/bca47e98-97c1-48e0-8417-a29cb61b42e7"  width="300" height="auto"/> </td>
  </tr>
</table>

### Steps to reproduce

1. Go to Da Nang
2. Selected the train station and search nearby
3. Search for "Cafe and restaurant"
4. Add the name "Yen" to the filter
5. Observe the search results
6. Switch to "Show ... on the map" and observe that many more results are available

### Actual result

The search result list has different results than the map from "Show .... on the map".

### Expected result

The search result list has identical results as the map from "Show .... on the map".

### Your Environment (required)

```
OsmAnd Version: 4.5.10
Android/iOS version: 9
Device model: Galaxy S8
Crash-Logs: ?
```

**Comment by vshcherb** [comment]
There was a similar bug probably fixed in 4.6 (definitely remember this one)

**Comment by sonora** [comment]
Ye in deed,, from my testing this has been fixed all right.

**Comment by zipav** [comment]
OsmAnd Nightly 4.6.0#1078m, released: 2023-11-22

Indeed, the latest version of OsmAnd Nightly displays more results than the original search results window, but every cafe displayed contains the particle -yen, or the word Yen, in its name.



<table style="width:100%">
  <tr>
  <th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/a37e0c16-78b1-483e-be58-cec89c37c59f"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/062b34f3-ff7d-456f-8853-a9f6c8e94e4c"  width="300" height="auto"/> </th>
<table style="width:100%">
  <tr>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/00283645-4108-4d54-8208-ce3ff523bcde"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/a670bcc6-51db-4333-975c-dc0079762759"  width="300" height="auto"/> </th>
 </tr>
</table>

**Comment by vshcherb** [comment]
Filter on Map searches "yen" as contains but in Search it displayed as word_starts_with, we need to use the same search strategy as in Search. So filter on map today is not correct
