### ISSUE TITLE
Problems with latest map creator - comments tag are shown on the map

### ISSUE THREAD

**Issue by razor74** [osmandapp/Osmand#1858]
On latest two build of mapcreator , on the rezulted compiled map on all poligons with comments tag - the text from comments are shown on the map. The mapp is filled now with huge texts from place to place... This is encountered from 100m zoom level and low.
![screenshot_2015-11-01-12-30-24](https://cloud.githubusercontent.com/assets/5586993/10868388/e9583a9a-8095-11e5-9368-0dfce37f116e.png)

**Comment by xmd5a2** [comment]
Can't do anything without knowing exact coordinates. We are not mind readers.

**Comment by razor74** [comment]
Thanks

**Comment by razor74** [comment]
It is about a tag which add comments on the map. Those comments must be 
visible only on map editors not on the navigation map.
You can find one of the comments here 
https://www.openstreetmap.org/edit#map=17/44.17136/28.57917 on one of 
the industrial multipoligons, for example - way: 88172506
