### ISSUE TITLE
2.5D map view not shown in Android Auto

### ISSUE THREAD

**Issue by Max1234-Ita** [osmandapp/OsmAnd#18590]
### Description

In my phone, the first profile after "Browse map" is "Car". In it, I'v set the 2D/3D view switch button to be always visible.
If I connect my phone to Android Auto, the map in the Haed Unit will always be 2D, even if the phone has 2.5D view enabled beefore connection to Android Auto.

Also, no 2D/3D button is visible on the car display, and the car view stays 2D if i set 3D by using the switch button on my phone display, so it's impossible to switch between the views.

### Steps to reproduce

1. Launch OsmAnd;
2. Make sure the "Car" profile is the firs profile available after "Browse map";
3. Select the "Car" profile;
4. Set the 2.5D/3D button to be always visible on display;
5. Set the map view to 2.5D;
6. Connect the device to Android Auto;
7. Expand the car display view to full screen (if needed);
8. Notice that the map is shown in 2D, and no 2D/3D button is visible;
9. On the smartphone, tap the 2D/3D button sevearl times; notice that the map view in the car dispaly doesn't change.

### Actual result

The map view in Android Auto Head Unit is always 2D, no 2D/3D button is visible on display, even if it's set to be always visible in the first profile presente in the device.

Current view in the smartphone, before connection:
![image](https://github.com/osmandapp/OsmAnd/assets/15315381/36087d35-5a79-4b66-9cb0-33fc9931811c)

Same view in Android Auto, after connection:
![image](https://github.com/osmandapp/OsmAnd/assets/15315381/fc3301d7-fad5-4f57-8765-7977c771c6e4)

Phone display after connection:
![image](https://github.com/osmandapp/OsmAnd/assets/15315381/f4a08385-626e-4876-9380-d14089a0124b)

### Expected result

The map view should be the same as previously set in the device before connection; 2D/3D button should be visible

### Your Environment (required)

```
OsmAnd Version:  OsmAnd+ v. 4.5.10
Android/iOS version:  Android v. 11
Device model:  Samsung Galaxy A50 (SM-A505 FN)
Crash-Logs: ?  N/A
```

**Comment by dmpr0** [comment]
2.5 D view is available in the current nightly builds and will be available in the next beta and release version.

**Comment by Baldo81** [comment]
The same happens also with Carplay and the latest version of Osmand. 
Previously to change between 2D/3D from carplay you could press the location button, now is not possible anymore.

**Comment by dmpr0** [comment]
> > @Baldo81 You can switch to 3D mode by two finger swipe up or down or by using separate button. You can enable it visibility in Menu – Configure Screen - 3D Mode.
> 
> 3D mode button is enabled but doesn’t appear on CarPlay. 2 fingers don’t work on CarPlay as the input can be only by 1 finger.
> 
> The solution you described works just on the app but not on CarPlay.

Taping 3D Mode button on your device should switch 3D on CarPlay unit.

**Comment by Baldo81** [comment]
> > > @Baldo81 You can switch to 3D mode by two finger swipe up or down or by using separate button. You can enable it visibility in Menu – Configure Screen - 3D Mode.
> > 
> > 
> > 3D mode button is enabled but doesn’t appear on CarPlay. 2 fingers don’t work on CarPlay as the input can be only by 1 finger.
> > The solution you described works just on the app but not on CarPlay.
> 
> Taping 3D Mode button on your device should switch 3D on CarPlay unit. I have add a issue for separate button [osmandapp/OsmAnd-iOS#3231](https://github.com/osmandapp/OsmAnd-iOS/issues/3231)

The problem is that sometimes when iphone is connected to carplay and you open the app the map on carplay disappears, I'm used to keep the mobile locked.
And a button (as was before) that allows you to switch between modes on Carplay is way more useful then actin on mobile, it reduces distractions and in my case as I use it on motorcycle I can select the function on carplay from commands on the steering wheel rather than stopping and take my mobile on hands.
