### ISSUE TITLE
Cannot stop track recording when enabled Auto-record track during navigation 

### ISSUE THREAD

**Issue by deprado63** [osmandapp/OsmAnd#18598]
### Description

Nachdem Die Streckenaufzeichnung gestartet worden ist kann diese nicht mehr gestoppt werden. Die Aufzeichnung startet jedesmal wieder neu wenn auf Stopp gedrückt wird.
Um die Aufzeichnung zu beenden muß ich jedesmal das GPS Signal ausschalten. 

### Steps to reproduce

Aufzeichnung mit REC starten.
Bei Ende auf Beenden. 

### Actual result

Die Aufzeichnung fängt wieder an aufzuzeichnen 

### Expected result

Ich erwarte das die Aufzeichnung beendet wird. 

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by deprado63** [comment]
Version 4.6.6 hat auch keine Abhilfe gebracht
Der Fehler ist nach wie vor vorhanden.

**Comment by scaidermern** [comment]
Maybe you enabled auto-record track during navigation in the trip recording settings? Not sure if this leads to your described behavior.

**Comment by deprado63** [comment]
Das hat damit nichts zu tun. Die Aufzeichnung startet immer neu sobald auf Beenden gedrückt wird.
Gruß

**Comment by DmitryAlexei** [comment]
@deprado63 could you please add short video of your issue?
Your profile settings may also help (go to menu > settings > your profile with issue > export profile.

**Comment by deprado63** [comment]
Es liegt nicht am Profil schließlich funktionierte diese Funktion vor den Updates ohne Tadel

**Comment by DmitryAlexei** [comment]
@deprado63 Without more information (at least short video) of your issue, we cannot reproduce it

**Comment by deprado63** [comment]
Ok ich werde versuchen die nächsten Tage ein Video zu machen Hoffe es hilft

**Comment by deprado63** [comment]
Habe jetzt mal mehrfach probiert. Es liegt wahrscheinlich so wie es Scaidermann gesagt hat an der Automatischen Aufzeichnung bei Navigation. Wenn ich diese Funktion deaktiviere dann kann ich die Aufzeichnung auch stoppen. In vorigen Versionen war das nicht der Fall da konnte ich stoppen egal welche Optionen angelegt war. Ich denke diese Funktion ist wichtig und sollte auch unabhängig von der navigationnsoption ausgeschaltet werden

**Comment by DmitryAlexei** [comment]
Tested the auto-record track during navigation.
- In the navigation simulation and on short routes, this function worked fine: recording was automatically disabled after navigation was stopped.
- Once, track recording didn't stop after a long route (longer than 100 km). Once, it didn't stop when I dismissed navigation, having passed the destination by about 0.5 km (the route was recalculated several times).


Will continue testing. You can also report your observations.

**Comment by DmitryAlexei** [comment]
OsmAnd 4.6.13
Steps to reproduce in real life conditions:
- go to your driving profile (can be pedestrian profile) and enable _auto-record track during navigation_ option in trip recording settings (menu > settings > your driving profile > trip recording > auto-record track during navigation). In trip recording settings also set general logging interval - 5 seconds
- tap navigation button and go to your driving profile. Set destination point and start navigation 
- don't go directly to the end point, record your route for some time (for me it's about 200-500 meters)
- wait for the route to be recalculated (not sure if it is the obligatory condition)
- stop navigation not in your destination point

https://github.com/osmandapp/OsmAnd/assets/116079541/e0e0e5d9-14ac-47ce-a1c9-93012a688a04


Actual result (see video):
- trip recording doesn't stop after navigation have been dismissed
- trip recording continues to work after initial track has been saved
- when you try to stop trip recording using the trip recording widget or in the notification bar, it only produces additional tracks and do not actually stop trip recording (see export.osf file containing 5 tracks from 0 to 5 meters long)
- only killing OsmAnd app can stop trip recording

Expected result:
- Automatic track recording stops after navigation stops

[Export_2024-02-18.osf.txt](https://github.com/osmandapp/OsmAnd/files/14322899/Export_2024-02-18.osf.txt)
[logcat.log](https://github.com/osmandapp/OsmAnd/files/14322794/logcat.log)
