### ISSUE TITLE
Missing maps in Europe

### ISSUE THREAD

**Issue by zenonp** [osmandapp/OsmAnd#18601]
### Description

Finland: no contour lines
Norway: no standard map, only roads-only
Spain: no contour lines, no standard map, only roads-only
UK: no standard map, only roads-only

I haven't checked anything outside of Europe, but this smells like a scripting problem that might also occur elsewhere. 

### Steps to reproduce

Install Osmand+ and try to download Europe standard maps and contour lines.

### Actual result

Some maps are missing.

### Expected result

Not missing. 

### Your Environment (required)

```
OsmAnd Version: 4.5.10
Map download attempt date: 2023-11-21
```

**Comment by zenonp** [comment]
Checking the UK closer, it is divided in four regions: England, NI, Scotland and Wales. Each of those has a standard map, while the UK as whole does not (compare to other regionalised countries, e.g. Poland, Germany, France, where all map options appear both in the download options of each region and in those of the country as a whole). Exactly the same is the case with Norway and Spain, but not with Finland, which is not regionalised.

**Comment by mikehgentry** [comment]
Someone on Reddit reporting problems in Asia too

https://www.reddit.com/r/OsmAnd/comments/180m479/no_maps_available_of_southern_arunachal_pradesh/

**Comment by zenonp** [comment]
I just downloaded Arunachal Pradesh. Indeed, compared to https://www.openstreetmap.org/relation/2027346#map=7/27.596/97.707 it is missing everything roughly south of a Tezu-Lemmi-Hawai line. 

But that seems like a different problem. While the Osmand map of Arunachal Pradesh is missing *all* OSM data for that part, the Osmand maps that I am reporting have the OSM data, but miss rendering the corresponding maps. Arunachal Pradesh could be as simple as an incomplete download of OSM data. Finland, Norway etc seem to be configuration errors in what maps to produce from existing data.

**Comment by zenonp** [comment]
If you try to download a standard map for Poland, Germany, France etc, you get a select/deselect dialogue. If you leave everything selected, all the country's regions get downloaded one after te other. 

Out on a wild guessing spree now, I begin to suspect that the roads-only maps for Norway, Spain and the UK exist as single .obf files, while the standard maps are divided in region .obfs, and that what makes the full-country download option appear is the existence of a configuration of which regions constitute a country. If so, the absence of that configuration would cause the country itself to not offer the corresponding maps, while each region separately does have and offer them. 

Finland contour lines remains a separate problem.

**Comment by scaidermern** [comment]
Norway, Spain, UK, Poland, Germany etc became to large for having a single, full country-wide map. That's why the have been split into smaller regions. This is done deliberately.

**Comment by DmitryAlexei** [comment]
@zenonp could you please provide screenshots of your issues?

**Comment by zenonp** [comment]
@scaidermern

> Norway, Spain, UK, Poland, Germany etc became to large for having a single, full country-wide map. That's why the have been split into smaller regions. This is done deliberately.

Yes, I know, but that has nothing to do with this issue. Germany has been split in regions, but you can choose to download a standard map for all Germany, and that opens a new dialogue where all regions are selected and you can optionally deselect some, and when you tap OK all regions get downloaded and installed sequentially. That is the correct mechanism for split countries. 

For Norway, Spain, and the UK, this mechanism has not been implemented. And because of that, it seems at first sight that there is no standard map for them. If and when the user checks the separate regions and finds their separate standard maps, he still has to download each region separately. 

@ DmitryAlexei

> could you please provide screenshots of your issues?

I'd have to uninstall several gigabytes of maps to recreate the original screens. You can simply see the issue on your own device by comparing the first screen for Germany to the first screen for Norway, Spain and the UK. The former has the option "Standard map", the latter do not.

**Comment by DmitryAlexei** [comment]
OsmAnd 4.5.10 (free version) same situation with nightly build.
UK map is available only in regions for quite a long time.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/a30587a2-5f7b-4400-aced-fa0e568c933d"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/aeaafb2c-78fc-48c9-bb24-e9bf6b6e7ade"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/24e68136-f7e5-421c-bb38-718397127ff8"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by zenonp** [comment]
In Norway and Spain you see the option "Standard map". With Osmand+ 4.5.15 yesterday I did not. My Norway and Spain looked just like your UK. 

> UK map is available only in regions for quite a long time. I don't see an issue here. 

Aha, so if a bug has existed for a long time, it becomes a feature. OK, perfect logic. Just close this issue as NOTABUG or WONTFIX and we're done. No point in reporting anything anyway, if there is no reason and no room for improvement.

**Comment by scaidermern** [comment]
> @scaidermern
> 
> > Norway, Spain, UK, Poland, Germany etc became to large for having a single, full country-wide map. That's why the have been split into smaller regions. This is done deliberately.
> 
> Yes, I know, but that has nothing to do with this issue. Germany has been split in regions, but you can choose to download a standard map for all Germany, and that opens a new dialogue where all regions are selected and you can optionally deselect some, and when you tap OK all regions get downloaded and installed sequentially. That is the correct mechanism for split countries.
> 
> For Norway, Spain, and the UK, this mechanism has not been implemented.

It has, for me:
![21275](https://github.com/osmandapp/OsmAnd/assets/1040784/0bbf70e1-8ce7-4961-ba3a-f5ea9fe90e91)

OsmAnd 4.6.6 here.
Does refreshing the list of available maps help?

**Comment by zenonp** [comment]
If you're connected to the internet, the list of maps is refreshed automatically every time you tap "Download maps". See DmitriAlexei's comment at 10:28 UTC and my reply to it. You can see what I reported for three counties in DmitriAlexei's screenshot of the UK. If anything, by the fact that he and you see "Standard map" in the country screen for Norway while I don't, we might guess that the problem was introduced after 4.5.10 or only affects Osmand+. The latter is more likely. All available downloads are listed in an indexes.xml which might differ between app versions. If so, a diff of the xml files could pinpoint the cause of the missing region bundling.

**Comment by scaidermern** [comment]
Indeed, the organization of maps, contour lines etc. sometimes looks rather inconsistent.

**Comment by vshcherb** [comment]
Norway, Spain, UK wont' have maps cause it close to map limit of 2  GB.
Contour lines rather a one time download so there is no much issue to store it in many files, especially because we are moving away from large files, to avoid map overlaps
