### ISSUE TITLE
Full Screen feature name

### ISSUE THREAD

**Issue by Sonwon1** [osmandapp/OsmAnd#18607]
### Describe the idea (required)

Full screen doesn't really do what I would expect the name full screen to do. Full screen to me means all of the screen is used by the app. I would look at renaming full screen to reflect it's true function. Something like "Tap screen to hide all widgets." or "Tap screen to hide all screen elements."

### Tell us about the expected behaviour (required)

N/A

### Tell us about alternatives you've considered (required)

N/A

**Comment by DmitryAlexei** [comment]
That is how *Full screen mode* looks for me. Depending on your device model, you may also need to activate *Transparent status bar* option in the development plugin settings (menu > plugins > OsmAnd development > settings > Transparent status bar)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/42d7d57e-cef4-489d-96ba-84e0a121566c"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Sonwon1** [comment]
In the past with other apps full screen would hide the status bar using all of the screen. Maybe it is just my perception of what full screen should look like? Also I would not expect full screen to hide any screen elements, just use all of the screen. Since I am on a tablet and using Osmand in landscape mode I am not really worried about using the status bar sliver. I just don't think the description is correct however maybe I am outdated?

**Comment by vshcherb** [comment]
We don't plan to hide status bar as we think it's not needed on modern large devices. We make it transparent instaed

**Comment by Sonwon1** [comment]
> We don't plan to hide status bar as we think it's not needed on modern large devices. We make it transparent instaed

Sigh, my suggestion was to rename Full screen and had nothing to do with changing the screen.

**Comment by scaidermern** [comment]
Something like 'Hide user interface' would be a better name. 'Full screen' is rather misleading since the size of the screen doesn't get changed at all.

**Comment by Sonwon1** [comment]
> 'Hide user interface'

Why not 'Hide user interface' then, short and more descriptive?

**Comment by vshcherb** [comment]
Because it's not an option "Hide or not Hide" and a special mode where you can hide and reveal UI by tap on the screen

**Comment by Sonwon1** [comment]
> Because it's not an option "Hide or not Hide" and a special mode where you can hide and reveal UI by tap on the screen

Well 'Full Screen' certainly acts like a 'Hide user interface' toggle so maybe 'Toggle User Interface would make more sense.

Personally, I do not understand why there is so much resistance to improving the name of a feature?

I guess, you can have the last word since I am frustrated. I don't think the OsmAnd staff is listening to the users. Also, the reason for closing this issue made no sense in my opinion.

Thank you for listening I guess.  :(

**Comment by DmitryAlexei** [comment]
Changing a name of an option that has been around for quite a long time is a very difficult decision. Many people have used to it, and they may be disappointed when they don't find the right thing in the right place. It's much easier to change a name of a feature that hasn't been released yet.
