### ISSUE TITLE
No maps available of southern Arunachal Pradesh

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#18605]
### Description

The download of Arunachal Pradesh does not include the southernmost portion, see the white blank spot on the map of regions. there are no contours or slopes available either

|  |
|-----|
|![image](https://github.com/osmandapp/OsmAnd/assets/44466116/9d9169c2-cc31-47bf-a75a-7d3f327b5930)|

### Steps to reproduce

Download this region and neighbourd reqions

### Actual result

Not include the south part of Arunachal Pradesh

### Expected result

Download all Arunachal Pradesh map

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by xmd5a2** [comment]
Fixed. Map was regenerated and uploaded.
![image](https://github.com/osmandapp/OsmAnd/assets/5829014/ec6fce64-136b-4c9c-80fc-63749c035285)

Side note: border between north and south Arunachal Pradesh is disputed but we still show it.

**Comment by EugeneZmeuk** [comment]
- [ ] Contour lines map

**Comment by zipav** [comment]
OsmAnd Nightly 4.7.0#1226m, released: 2023-12-15

The map can be found in the list of available regions of India on the following path: Menu → Download maps → Downloads → Asia → India → Arunachal Pradesh
|  |
|-----|
|![image](https://github.com/osmandapp/OsmAnd/assets/123936521/7f3ac098-6356-498f-a11a-c8e60c56c35c)|
