### ISSUE TITLE
Turn screen on

### ISSUE THREAD

**Issue by Goodingn** [osmandapp/Osmand#1860]
This option has the sub-text 'Turn on device screen (if off)...'

Firstly, this needs expanding to include that it also turns the screen off.

Secondly, for me (probably because OSMAND is on the SD Card), it keeps loosing the Device Administrators privilege.  When OSMand is started (or navigation starts) with the 'Turn screen on' option turned on, it should check this privilege is set and warn with the option to jump to the Device Admin screen.

**Comment by vshcherb** [comment]
I think the original issue is that OsmAnd loosing privilege. If OsmAnd doesn't have this privilege, it won't be able to show the warning itself.

**Comment by wavexx** [comment]
I was looking for a way to keep the screen on *always* for the 'car' profile. Does setting "Turn the device screen (if off).. ' option set to 'Never' also prevents the screen to be turned off?

If that's the case, the text is really misleading and needs to be changed.

**Comment by sonora** [comment]
@wavecxx: By default the screen will be kept on in any mode as long as you are on the map screen. The setting you are referring to only matters if you had turned off the screen manually.

Regarding Goodingn's issue: I have tried hard, but cannot reproduce on nay of my devices. Yes, chances are part of the issue is that OsmAnd has been moved to the SD card. I never do this, it seems rather unnecessary, as the big data chunks are the maps, and those can be kept on the SD card (via OsmAnd's data folder setting) even with the app in its standard in-memory installation.

**Comment by wavexx** [comment]
On 26/01/16 20:37, Hardy wrote:
> @wavecxx: By default the screen will be kept on in any mode as long as
> you are on the map screen. The setting you are referring to only matters
> if you had turned off the screen manually.

That doesn't seem to be the case. When I start navigation, and the
screen is on, the screen is still turned off after the next navigation
waypoint + timeout.

If I turn on the screen just after it has been turned off, it stays on,
but it will still be turned off at the next waypoint + timeout.

This applies irregardless if the phone is powered.

It's also to note that when the screen is turned on again, it might take
1-2 seconds to bring the display up-to-date on my device. So if you're
about to announce some maneuver, it's actually a good idea to turn on
the screen a few seconds before using the TTS. I'd say the screen should
be turned on before the same number of seconds you set it to turn off
after the maneuver.

**Comment by sonora** [comment]
When you check your Android's "Device Administrator" setting (mostly under
"Security"), is OsmAnd listed there? If not, did you manually remove OsmAnd
there? If you re-install OsmAnd over the existing insatllation, does OsmAnd
re-appear there?

**Comment by wavexx** [comment]
On 26/01/16 21:10, Hardy wrote:
> When you check your Android's "Device Administrator" setting (mostly under
> "Security"), is OsmAnd listed there? If not, did you manually remove OsmAnd
> there? If you re-install OsmAnd over the existing insatllation, does OsmAnd
> re-appear there?

It's listed and checked.

**Comment by sonora** [comment]
Not 100% sure, but I think it must me listed, but be unchecked...

**Comment by wavexx** [comment]
Having it checked only gives OsmAnd extra permissions to control the lock-screen behavior, so it doesn't matter.

**Comment by sonora** [comment]
Not reproducible any more.

**Comment by DiJuMx** [comment]
I have observed the behaviour today. As soon as the text to speech finishes, the screen turns off. 

[Using OsmAnd~ 3.2.7]
