### ISSUE TITLE
Arunachal Pradesh map missing data south of a Tezu-Lemmi-Hawai line.

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd#18603]
I just downloaded Arunachal Pradesh. Indeed, compared to https://www.openstreetmap.org/relation/2027346#map=7/27.596/97.707 it is missing everything roughly south of a Tezu-Lemmi-Hawai line. 

But that seems like a different problem. While the Osmand map of Arunachal Pradesh is missing *all* OSM data for that part, the Osmand maps that I am reporting have the OSM data, but miss rendering the corresponding maps. Arunachal Pradesh could be as simple as an incomplete download of OSM data. Finland, Norway etc seem to be configuration errors in what maps to produce from existing data.

_Originally posted by @zenonp in https://github.com/osmandapp/OsmAnd/issues/18601#issuecomment-1821987168_

**Comment by DmitryAlexei** [comment]
To test:
- download map for coordinates 27.0979659, 93.6237291
- check for discrepancies between the OsmAnd map and the OSM  https://www.openstreetmap.org/relation/2027346
It seems, that in OsmAnd map some data south of a Tezu-Lemmi-Hawai line is missing

**Comment by zenonp** [comment]
See also the original report on Reddit: https://www.reddit.com/r/OsmAnd/comments/180m479/no_maps_available_of_southern_arunachal_pradesh/

**Comment by DmitryAlexei** [comment]
duplicate of https://github.com/osmandapp/OsmAnd/issues/18605
