### ISSUE TITLE
Widgets on left panel in landscape mode disappear after starting Navigation 

### ISSUE THREAD

**Issue by deprado63** [osmandapp/OsmAnd#18600]
### Description

Sobald Ich in den Navigationsmodus gehe verschwindet das linke Panel 

### Steps to reproduce

Navigation > Ziel eingeben >Navigation starten >Das linke Panel mit den Informationen verschwindet kpl vom Bildschirm

### Actual result

Das linke Panel ist nicht mehr sichtbar 

### Expected result

Das linke Panel sollte mit den angelegten Informationen sichtbar sein. 

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by DmitryAlexei** [comment]
@deprado63 Thank you for your request!
In OsmAnd there are different profiles for different purposes. For example Browse map profile, Driving profile, Bicycle profile.
Each profile can be configured according to your needs, so if you would like to see some widgets in the driving profile, you can add them using map > configure screen > left panel

**Comment by deprado63** [comment]
Das ist mir alles bekannt 
Das Problem tritt auch nur und immer wieder im Navigationsmodus auf.

**Comment by vshcherb** [comment]
Please create issue in english and provide some screenshots if possible, it's actually hard to understand whether it's an issue or not

**Comment by deprado63** [comment]
Danke für das abschließen des Problems Bin schon etwas enttäuscht Das Problem besteht weiterhin sowohl bei meinem Huawei tablet als auch OPPO Handy Danke für die Unterstützung

**Comment by scaidermern** [comment]
Maybe you should provide the screenshots that were asked for.

**Comment by deprado63** [comment]
Hallo
Ich habe jetzt eine kurze Strecke eingegeben und Screenshots erstellt 
Bild 1 Ansicht mit den Widgets auf der linken Seite 
Bild 2 Eingabe für die Navigationsberechnung 
Bild 3 Berechneter Weg ohne Widgets auf der linken Seite 

![Screenshot_20231126_135055_net osmand plus](https://github.com/osmandapp/OsmAnd/assets/52757019/b5a9557e-5f39-4429-ade5-b8e97337c272)
![Screenshot_20231126_135152_net osmand plus](https://github.com/osmandapp/OsmAnd/assets/52757019/792a53ff-d26a-440e-aeaf-b696b3d07dc0)

Hoffe es reicht aus

**Comment by deprado63** [comment]
Sorry das mittlere Bild fehlt.
Reiche ich hiermit nach
![Uploading Screenshot_20231126_135128_net.osmand.plus.jpg…]()

**Comment by deprado63** [comment]
![Screenshot_20231126_135128_net osmand plus](https://github.com/osmandapp/OsmAnd/assets/52757019/fba4f04f-5f73-4795-9d97-0949f269c7de)

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#1094m, released: 2023-11-26
**Steps to reproduce:**
- add widgets to left panel to your driving profile (see screenshot of my settings)
- using your device in landscape mode, set destination
- tap *Start*
- optional: Simulate navigation

**Actual result**
- manually added to left panel widgets are not displayed after starting navigation
- sometimes *Next turn* and *Second next turn* widgets are displayed during navigation, sometimes not
- widgets from left panel are still missing after navigation has ended (despite the fact that they are displayed as active on *Left panel* tab in Configure screen* menu)
- widgets can be activated again by changing the orientation of the device screen (go to portrait mode > widgets became visible > and still be visible in landscape mode)

**Expected result**
- widgets on the left panel are displayed during navigation and after the ride is over

Probably it is a regression after https://github.com/osmandapp/OsmAnd/issues/17960

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/e59b2ea3-5a6a-4acf-9563-d1fced21daa4"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/b6b1453a-4332-4339-afcd-602e12aea1ba"  width="450" height="auto"/> </td>
  </tr>
</table>

**Comment by deprado63** [comment]
Tut sich da was in naher Zukunft?

**Comment by pebogufi** [comment]
@deprado63 
You did not understand, that the forum is in **ENGLISH** ?

**Comment by DmitryAlexei** [comment]
@deprado63 what version of the app do you use? 
The fix is already in the release version (4.6.9 or 4.6.11 from Google Play). For me it works correctly
