### ISSUE TITLE
Turn lanes incorrect turn right from left lane

### ISSUE THREAD

**Issue by Prusaker** [osmandapp/OsmAnd#18610]
### Description

Incorrect turnlanes when approaching a road link. (No lanes marked on the OSM map).
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/32092837/5f18d2a6-681f-4ac9-921f-afcd905eb95e"  width="400" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/32092837/dde8f699-df78-4983-8de2-916c3b3ce007"  width="400" height="auto"/> </td>
  </tr>
</table>

[https://www.openstreetmap.org/way/25308483](https://www.openstreetmap.org/way/25308483)

### Steps to reproduce

Try to build route (car profile) from 53.7683364, 27.3474878 to 53.7672025, 27.3491824.

### Actual result

Turn lanes are displayed in the wrong order.
![image](https://github.com/osmandapp/OsmAnd/assets/32092837/f83f9cef-0fa6-4292-a515-fb8f7fe8a210)

### Expected result

Perhaps in this case the turnlanes at widget need to be swapped.

### Your Environment (required)

```
OsmAnd Version: OsmAnd Nightly 4.6.0 1075m
Android/iOS version: Android 11
Device model: Lenovo TB-8506X
```

**Comment by vshcherb** [comment]
Yes, lanes are incorrect - https://osmand.net/map/?start=53.768250,27.347540&finish=53.767007,27.346913&type=osmand&profile=car#17/53.76758/27.34553

**Comment by vshcherb** [comment]
- [ ] С++ transfer left

**Comment by yuriiurshuliak** [comment]
The bug has been fixed. Currently, the Lanes widget is working correctly.

OsmAnd~ 4.7.0#1655m, released: 2024-02-23

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/a2f1c4e2-02b6-49d1-8e48-7ced077cc280"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/140ffb5c-cd2a-48a4-8d6b-ada535c4dde2"  width="300" height="auto"/> </th>
  </tr>
</table>
