### ISSUE TITLE
Screen power profile

### ISSUE THREAD

**Issue by Goodingn** [osmandapp/Osmand#1861]
Although there's a 'Turn screen on [and off]' option that uses the Device Admin to turn the screen off almost immediately after a navigation point, I'd like the option for it to use some of the standard screen power profiles instead - turn screen off as per normal Android time-out (to allow some observation of the app after a navigation point) and the Dim Wake Lock option that allows the screen to dim to a very low level after the normal Android screen time-out (this would be ideal to allow constant use of the app while allowing some powersaving).

Because the screen is coming on at each navigation point, the screen would effectively stay on during lots of navigation.

Along with these power profiles, it would also be nice for the screen turning on automatically to be optional.  The navigation could then be visible for a few mins, then fade or turn off even if more navigation is happening, but audio can continue (if enabled) and if I feel like it I can turn the screen on for a while.

**Comment by sonora** [comment]
No action planned here for now, it seems.
