### ISSUE TITLE
[Bug] Current location button does not work properly.

### ISSUE THREAD

**Issue by franco999** [osmandapp/OsmAnd#18615]
### Description

In the developing version of OsmAnd, more specifically around version **4.6.0#1084m** (released on **2023-11-24**), when I want to track my location and click on such a button located in the lower right section of the map, it does not work correctly. It finds the location and shows it in the center of the screen but at the same time stops tracking it.

### Steps to reproduce

- Activate the location of the device.
- Once the location is marked as a point, move in any direction.
- Click on the location tracking button.
- Wait a few seconds to see if the tracking works or not.

### Actual result

It finds the location and displays it in the center of the screen but at the same time it stops tracking it and if you keep moving, the location arrow goes off the screen.

### Expected result

When you press the tracking button, you should be able to constantly see the location arrow in the center or at the bottom of the screen.

### Your Environment (required)

```
Device : devon
Brand : motorola
Manufacturer : motorola
Model : moto g32
Product : devon_g
Build : S2SN32.34-72-46
Version : Android 12
App Version : OsmAnd~
Apk Version : 4.6.0#1084m 4600 (released on 2023-11-24)
```
**Logcat:** [logcat.log](https://github.com/osmandapp/OsmAnd/files/13462573/logcat.log)

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#1091m, released: 2023-11-25

**Comment by Dollarius** [comment]
Tracking stopped working for me as well, also in map mode (i.e., no active navigation).

```
Android 14
Samsung Galaxy S23
OsmAnd 2023-11-23
```

**Comment by franco999** [comment]
I confirm that in #1134 it seems to have been resolved.
