### ISSUE TITLE
OsmAnd cloud - add option not to sync active (default) profile

### ISSUE THREAD

**Issue by vsassone** [osmandapp/OsmAnd#18620]
### Description

OsmAnd Cloud (free version) is a great thing. However, it keeps suggesting local changes to profiles and general settings even when there are none. Just  changing a profile produces a change in global settings and in the profile being left. This seems too fine a level, produces continuous changes. I wonder whether it’d be possible to remove from sync things like “current profile” etc. It would also be useful to see a list of local changes, a sort of diff between local and cloud versions. Regards. 

### Steps to reproduce

Change selected profile.

### Actual result

iCloud will report local changes in general settings and the previous profile. 

### Expected result

Personally I would not expect changing the active profile to create this, the selected profile could well be a device-dependent setting, not a cloud one. 

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 5.4.10
Android/iOS version: 12
Device model: Samsung active tab 3
Crash-Logs: ?
```

**Comment by DmitryAlexei** [comment]
You can choose what to sync in OsmAnd cloud settings (see docs https://osmand.net/docs/user/personal/osmand-cloud#settings)

**Comment by vsassone** [comment]
Thank you DmitryAlexei, I suppose what I’m saying is that I’d like more options in that menu: of course I want to sync both general settings and profile settings, but I don’t want to sync “active profile” because that’s not a “real” setting and changes very often creating confusion and potentially missing real changes. For instance say I’ve got two devices, say one in a car one and one on a motorcycle, they’ll be set to different profiles. Therefore OsmAnd Cloud will show they are out of sync. I’ll ignore that (as I do) because I know it’s because of the “active profile” setting. If at some point I make a real change to general settings (say display language) or to a profile (say the a map overlay), I’m likely going to miss that, or be confused about what device contains the correct profile.  More in general, I think OsmAnd Cloud is a great thing, but it could be a little better: it ought to be possible to merge local and cloud changes, not just override one with the other or viceversa. Cheers. On 28 Nov 2023, at 07:34, DmitryAlexei ***@***.***> wrote:﻿




CAUTION: This e-mail originated outside the University of Southampton.




You can choose what to sync in OsmAnd cloud settings (see docs 
https://osmand.net/docs/user/personal/osmand-cloud#settings)
—
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
You are receiving this because you authored the thread.Message
 ID: ***@***.***>

**Comment by vshcherb** [comment]
Related to https://github.com/osmandapp/OsmAnd/issues/17883

**Comment by vshcherb** [comment]
Suggested: We need to have separate item for Default profile. So user can disable Global Settings and Default profile (note default profile is not necessarily Browse Map)

![telegram-cloud-photo-size-4-5892982472470283892-y](https://github.com/osmandapp/OsmAnd/assets/1042025/91b14cb5-5bc0-482b-9cb1-e9f5f5c451ba)

**Comment by vshcherb** [comment]
We decied to not fix this action directly. 
1) You can disable syncing Global settings
2) Create different set profiles for each device which you don't want to synchronize, for example Driving (Tablet), Driving (Phone)
3) Then disable visibility of these profiles where it's needed and not needed
4) That will affect only Global settings which won't be synchronized and won't create a conflict. Profiles will keep saving into Cloud
