### ISSUE TITLE
Make our map fully interactive

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#1862]
**Edit:** See suggestion further below: Rather than what I originally suggested here, I think a great feature for our app would b to make the map fully interactive by having an always-on transparent POI layer. The list-display and selection mechanism for when you tap an area with multiple overlapping POIs is already in place for the POI layer, so WYSIWYG should not be an issue.

As originally reported in Issue #1841:
It would be nice to not only display the street name (finally address), but also see a short list of the say 3 or so closest POIs when long-tapping anywhere on the map, maybe as selection list under the details section of the Context bubble, or similar to how we already have it for the POI layer when user taps an area with several close-together POIs.

**Comment by sonora** [comment]
I thought about this some more and still think it is a much needed feature to "discover" things on a map, e.g. while on a sightseeing walk. I think the least intrusive way to implement it in our code and UI is to simply add a menu entry "Nearby POI" to the 3-dots menu of our context disply, which would call our existing Search POI /

**Comment by OpenSourceForEver** [comment]
I think a nice idea is to show POI'S information with a long tapping in the POI, Something similar to clicking a POI in the big company started by G (I do not know if i can use the name of the company).

**Comment by amenk** [comment]
:+1: How much effort is this feature? I might be able to sponsor it.

**Comment by vshcherb** [comment]
If you ask me that feature design could take between 1-10 days and discussions, and the implementation could definitely take from 3 to 7 working days, of course depends on details. Though it all requires clarification and thought through corner cases.

For example, which kind of POI need to be displayed, is there any preference, do they need to be displayed just on the bottom in context menu, sorted by distance?

**Comment by amenk** [comment]
I was actually heading here from #2178 (was marked as duplicate) ... I just want to be able to click such POIs which are already visible on the map. So maybe #2178 is not that much duplicate as supposed.

**Comment by vshcherb** [comment]
#2178 is planned (but not the highest priority though) and it will take 2-3 weeks of development (as we calculated).

**Comment by littlehelper** [comment]
+1
As mentioned here and in #2178, tapping a POI directly or selecting it via a selection menu showing the closest POIs when long-tapping on the map close to the POI would be great.

The selection menu could be similar to the menu shown when tapping close waypoints/markers.
In addition, the first entry should be the current location, clicking on it shall open the already implemented POI menu including address lookup which is shown when long-tapping somewhere on the map.
If it would be possible to even select the (closest point of the) road close to the marker, creating waypoints precisely on roads would be easy (in compare to snapping to road, #1696).

**Comment by sonora** [comment]
As I have already described eslsewher,  I think all that needs to be done is this:
- We create a filter for a POI layer "Show all POI transparently", identical to the existing "nearest POI" filter (which shows all POIs), but with this filter the POI disks would not be orange with white amenity icons, but both colors would be transparent.
- All else, like the selection menu for POIs if you tap an area with many overlapping POIs, is already implemented and working. So activating this new POI filter would do nothing less than create a **fully interactive and POI-discoverable map**.
- From what I see, we might even subsequenttly decide to have this filter on by default.
- The functionality to accentuate selected POI by  orange disks should remain unchanged, to facilitate visualizing certain types of POI. But yhis need not impact tappability any more (as all are tappable anyway by default).
- I notice we would need a small code correction to ensure that (while short tap on the map brings up a POI context or POI aelection list if POI(s) happen to be tapped, a long tap on the map always brings up the LatLong and starts a reverse geocoding search, even if a POI is in the vicinity. (Short tap brings up POI context or POI selection, while long tap always brings up Lat Long.Today long-tapping a tappable POI is captured by the POI layer and results in no actoon.

I think an implementation like this is a huge step towards the kind of interactive behavior users can expect from an electronic map?

 The resulting behavior can essentially be tested today already by activating the "nearest POI" filter. (without transparent look and without full long tap capability). See also issue #1447.

**Comment by raindropsfromsky** [comment]
I'd suggest a variation to what Sonora suggested:

As the user moves in the area, OSmAnd makes POIs around him (i.e., the current location) visible.
This "POI visibility radius" can be adjusted with a slider.

So both short and log taps can be used for other actions.

**Comment by raindropsfromsky** [comment]
For example, long-press on any other place on the map to toggle the visibility of POIs around that spot.

I am assuming that when POI becomes visible, it becomes tappable also.

**Comment by amenk** [comment]
Why can it not be done as in Google maps... just make the icons click able.
Drawbacks?

**Comment by vshcherb** [comment]
Transparent POI Layer is a good idea but it might contradict of principle what you see is what you get. We have that feature in iOS already and we plan to move to the common engine next release.

**Comment by sonora** [comment]
@vshcherb , @crimean 
Victor,  Alexey, some **very cool progress** here, I love it!  This is a big quantum leap for OsmAnd, we are entering a whole new field of possible use cases for the app!

One thing I still notice is this: When tapping on a Transport stop, we currently get the context menu for the **POI** "Transport stop", while it would be really cool if we could get the context menu for the **"Transport layer's"** transport stop (with all the functionality associated with it, like being able to tap on and highlight transport routes, etc.)

Best - Hardy

**Comment by utack** [comment]
@sonora nice idea on the transport stops
Even better: show and highlight all public transport tracks that use this stop, while it is selected

**Comment by amenk** [comment]
Can somebody explain the new feature? I still can not click POIs. Is that
intended? Thank you in advance.

**Comment by vshcherb** [comment]
Implemented in nightly builds.

**Comment by amenk** [comment]
Ah okay ... interesting thing is, that something like this was mentioned in the changelog at Google Play.

**Comment by sonora** [comment]
@vshcherb Some remaining issues listed here #3101 and here #3106, as follows:
- Tapping Transport stops, may already be fixed, but please see #3106 
- Wikipedia POIs not included as tappable
- Lag issue, user cannot be sure if a tap found a target or not
- Some suggestions about suburb etc. tapping behavior by Narayan.

**Comment by vshcherb** [comment]
- Wikipedia POI should be a separate issue, not planned by this one.
- Increased radius is planned and we will wait @xmd5a2  applying new icons

**Comment by littlehelper** [comment]
Great work! Thank you for implementing.
Greetings

**Comment by sonora** [comment]
@vshcherb Yes, increasing the tappable area for the icons  a bit is a good thought. Here is a test: Try to hit this bus stop http://www.openstreetmap.org/node/3922266263: Very difficult. Actually, You have to tap this node http://www.openstreetmap.org/node/3922280663, invisible in the vicinity. (The visible one with the icon is the platform, and it accepts no taps, but users will not know this). Best fix is to increase the hit areas a bit. This test example is particularly annoying because missing the bus stop will immediately result in having tapped the underlying suburb area.
