### ISSUE TITLE
Feature request: audible warnings without need for audible directions

### ISSUE THREAD

**Issue by outofcreativity** [osmandapp/Osmand#1863]
I'd like to have an option added where i can turn off audible directions, but not voice entirely.

When I'm driving in my car I have my Phone in my sight, so a quick look is sufficient, but a little reminder for, let's say a stop sign behind a turn, would be nice.

thank you in advance.

**Comment by outofcreativity** [comment]
While this is been worked on, I managed to create a temporary workaround for this issue.

I've copied a voice folder with actual sound files (like de, *not* de-tts) and overwrote the notification-files, which I do not want, with files containing silence. The other files were exchanged with short audible notifications like "attention!".

I'm quite happy with this solution and it could be made universal, if the sounds are generic like a horn or something like that.

**Comment by vshcherb** [comment]
You could also modify ttsconfig.P and replace "go.ogg" with "", in that case it will be silent as well. Unfortunately to make it as an option in the program requires code modification

**Comment by outofcreativity** [comment]
Thank you for your advice, unforunately I've totally missed it until now. I've tested my solution over the past few months and it works well. I also modified it further from sounds of the KDE project, so everything is just a short sound without interrupting much.

**Comment by sonora** [comment]
No further action planned.
