### ISSUE TITLE
Duplicate entries of favorite places with Cloud Sync

### ISSUE THREAD

**Issue by MiMoHo** [osmandapp/OsmAnd#18632]
### Description

I experienced duplicate favorites when using the Cloud Sync on two separate Android 13 devices with Osmand~ 4.5.10, one master, one slave device. In the settings, there is _OsmAnd Cloud_ with a big _Sync now_ option. The user expects to have the latest changes written over the outdated data which is not reliable. The options _Local changes_, _Cloud changes_ and _Conflicts_ are hidden as folded in despite being essential as one-way synchronization options.

After syncing the first device before the second, I'm confronted with many conflicts on both devices. Despite that I always kept the local version on the master device and opted for the cloud version on the slave device in _Conflicts_, the cloud mixed up things and produced lots of duplicates in _My Places_. I ended up with some favorites having dozens of identical entries.

When selecting one entry (place) for deletion, all other matching entries are selected automatically as well. I can't delete double entries that way and as my entire library got duplicated or even multiplicated, this would be too much effort anyway.

Please improve:
- The folded out state of favorite groups should not be saved in the gpx file.
- Cloud Sync must not damage the library but allow for foolproof backups. It is mandatory to show a proper sync direction for the user to define to only upload, download or use both directions.
- The backup download from the cloud is interrupted every few seconds or minutes so that a clean download is not possible.

### Steps to reproduce

I tried to export and import an OSF file but it restores the damaged library. Exporting the favorites.gpx results in a 25MB file. When importing it to an empty library after completely resetting the app, the double entries are gone and a new exported file is just 1MB in size, so this seems fixing it. I also experienced a crash upon importing the favorites whose log file is below.

### Actual result

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/37556964/b9c5a6db-5181-40b4-b54c-17c26a18dbac"  width="300" height="auto"/> </td>
  </tr>
</table>

### Expected result

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/37556964/1b5ab5ea-eeaa-4af1-9891-0f08a6be775f"  width="300" height="auto"/> </td>
  </tr>
</table>

### Your Environment (required)

```
OsmAnd version: 4.5.10
Android version: 13
Device model: Sony Xperia 5
Crash-Logs: ![exception.log](https://github.com/osmandapp/OsmAnd/files/13512598/exception.log)
```

**Comment by pawelpbm** [comment]
This duplication also happned to me. 

Any ideas how to clean it up?

**Comment by vshcherb** [comment]
Issue was fixed
