### ISSUE TITLE
AIDL navigate GPX ignores "start of track" option based on segments start / end points

### ISSUE THREAD

**Issue by pab2d** [osmandapp/OsmAnd#18638]
### Description

When calling navigateGpx() we have the problem that some parts of the track are skipped depending on the current position (start of track is active). We reduced the snapToRoadThreashold and the navigation seemed to work better. Until we had a track with several consecutive segments, where the end of one segment is the same point as the start of the next segment, and suddenly whole segments were skipped again.
The only solution to this was to set snapToRoad to false, which is not what we want and we don't understand why disabling this option suddenly makes it work.

Do you know why it behaves like this when the option is disabled? Or are we missing something behind snapToRoad?

Look at the two screenshots, both with the same NavigateGpxParams. On the left with separate segments and on the right with connected segments.

![1](https://github.com/osmandapp/OsmAnd/assets/101704058/e0f55cd8-8bcd-414f-bd63-a53abdc89846)               ![2](https://github.com/osmandapp/OsmAnd/assets/101704058/055a6a7c-1106-4eb3-9547-031431e50d36)

Our NavigateGpxParams for the call:
isPassWholeRoute = true
isSnapToRoad = true
snapToRoadMode = Car
snapToRoadThreshold = 6 - 50 (depends)
fileName = XY

### Steps to reproduce

Create Track file whe the end of one segment is the same point as the start of the next segment

### Actual result

Navigation does not start at the starting point of the first segment, but at the starting point of another (last?) segment, which is the end point of a previous segment, thus skipping entire previous segments. It also makes no difference where the current position is on the map.

### Expected result

Navigation starts at the starting point of the first segment and continues through the segments until the destination is reached.

### Your Environment (required)

OsmAnd Version: 4.5.10
Android version: API 26, 29 & 33
Device model: Multiple emulators and a Samsung Galaxy Tab Active3

**Comment by Chumva** [comment]
@pab2d can you please provide tracks for testing? Does this issue happen only with aidl navigateGpx(), or even if you start navigation in OsmAnd in UI with these tracks?

**Comment by pab2d** [comment]
Hi @Chumva, thanks for your reply. 
Sure, here are the two tracks you can see in the screenshots above. And yes, this issue only happens with the aidl navigateGpx() and not when starting the navigation directly in the OsmAnd UI (or setting isSnapToRoad = false in the NavigateGpxParams).
[Track_samples.zip](https://github.com/osmandapp/OsmAnd/files/13670161/Track_samples.zip)
