### ISSUE TITLE
Osmand nightly builds use roads tagged as private

### ISSUE THREAD

**Issue by hvdwolf** [osmandapp/Osmand#1864]
Versions 2.2.0#13873M (I used this one when I saw the error)
2.2.0#13990M 02-11 13:44 (Just downloaded this one and it has the same issue)

I just calculated a route and saw that OsmAnd uses a private road. This road is across a factory with gates to prevent access. OsmAnd should calculate a route around it (even if it had not gates on both ends).

**Comment by vshcherb** [comment]
Could you please give a link. It should not use private=yes

**Comment by vshcherb** [comment]
Actually I just checked it uses private by highly deprioritized.

**Comment by oopen** [comment]
Same problem, with a path. It was suggested in a rerouteing for escape a traffic jam.
