### ISSUE TITLE
Favorite place set on a modified POI is not linked even after replacing

### ISSUE THREAD

**Issue by MiMoHo** [osmandapp/OsmAnd#18653]
### Description

As result of #18648 , when a favorite place was placed on a newly created or modified POI (before upload), the favorite place will not be connected to the concerning POI after uploading the changes. This results in not showing data from the underlying POI like opening hours.

One can tap on a POI and choose _Add_ and it will create a favorite place that is linked, but when choosing to _Replace another point with this_ on the bottom of the settings and selecting the unlinked favorite place, it doesn't fix the issue. Sometimes, the favorite place is created slightly off the (new) POI but even correcting this slippage by replacing doesn't connect the places. The only current workaround is to create a brand new favorite place on top of the other favorite place and then copy the data (description) from the old favorite place manually and delete the old one so that one can use the underlying POI information for the favorite place.

I conclude that the linking of a favorite place with the POI is only made **once** and is not being done when the POI was newly created or modified by the user. On the other hand, every time a favorite place is successfully linked with a POI and then is being moved, it will keep the link even when moved far away. So when it is used to mark a different place, it will keep inapplicable data like showing irrelevant opening hours as only the address is being updated upon moving.

As automatically inserted address information is in an unusual format [road (suburb) house number, city] without postcode as reported in #5705 , I have to correct the address every time I even slightly move the favorite place.

### Steps to reproduce

Tap on a POI -> Modify POI -> add opening hours -> save
Create favorite place from green icon
Upload editing changes to OSM cloud and update the database by Live Update
Check that the favorite place doesn't show the opening hours
Now create a new favorite place "on top" of the POI -> save as new

### Actual result

The new favorite place will be linked showing all information like the opening hours:

| POI and favorite place | POI with opening hours | Favorite place | New favorite place created from POI with unfavorable address format |
| --- | --- | --- | --- |
| ![POI and favorite place](https://github.com/osmandapp/OsmAnd/assets/37556964/7616df0a-2b7f-4ae9-a5d3-72aadd63314a) | ![POI opening hours](https://github.com/osmandapp/OsmAnd/assets/37556964/544af6c8-94bd-47a7-bb8d-3415ee92cc90) | ![Favorite place](https://github.com/osmandapp/OsmAnd/assets/37556964/33785853-666e-42eb-ac3b-bd70dbaa5c72) | ![New favorite place created from POI with unfavorable address format](https://github.com/osmandapp/OsmAnd/assets/37556964/fffd9920-7c20-4058-8e2e-45ef8dd0a959) |

### Expected result

The previously created favorite place on the modified POI should be linked as well showing the same information as if creating a favorite place from an unaltered POI.

### Your Environment (required)

```
OsmAnd Version: 4.5.10
Android/iOS version: 13
Device model: Sony Xperia 5
Crash-Logs: no
```

**Comment by vshcherb** [comment]
Yes it's a good proposition for favorites to track map updates in general. It shouldn't be related for changes itself as it should be more generic, right now tags are stored inside favorite and probably not updated correctly that need to be checked.

**Comment by vshcherb** [comment]
It should work as you click on Favorites we should check POI data in background (Radius: 10m + POI Type or Radius 100m: Name) and "reload /update" internally saved tags

**Comment by dmpr0** [comment]
# Review

- [ ] Todo is missed

**Comment by dmpr0** [comment]
# Review 2

- [ ] Todo is missed
