### ISSUE TITLE
Bicycle routing should ignore vehicle=no (conditional case)

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#18652]
### Description

[Way 1226680710](https://www.openstreetmap.org/way/1226680710) has `vehicle:conditional=no @ (2023 Nov 23 - 2023 Dec 30)` set. So the road is currently closed for all vehicles.

When routing from 51.0507562,13.7286615 to 51.0489284,13.745656 OsmAnd correctly recognizes this tag for [car routing](https://osmand.net/map/?start=51.050756,13.728661&finish=51.048928,13.745656&type=osrm&profile=car#17/51.04993/13.73476) but _not_ for [bicycle routing](https://osmand.net/map/?start=51.050756,13.728661&finish=51.048928,13.745656&type=osrm&profile=bicycle#17/51.04993/13.73476).

This is mainly the same issue as #15844 from last year.

From #15844:
```quote
it's done intentionally ! vehicle-no is overridden by 'route_bicycle' and 'cycleway'
```
This is wrong in my opinion. OsmAnd simply ignores the access tags on this way.

### Steps to reproduce

See above.

### Actual result

OsmAnd essentially routes through `vehicle=no` in bicycle mode.

### Expected result

OsmAnd should not route through `vehicle=no` in bicycle mode.

### Your Environment (required)

```
OsmAnd Version: 4.6.6
Android/iOS version: Android 10
Device model: Samsung S9
```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. When setting navigation using the specified coordinates for a car, the routing considers the 'vehicle=no' tag. However, for bicycle navigation, this tag isn't factored in. You can observe this distinction in the web version for both car (link: [car route](https://test.osmand.net/map/?start=51.050754,13.728650&finish=51.048926,13.745659&type=osmand&profile=car#15/51.0494/13.7291)) and bicycle (link: [bicycle route](https://test.osmand.net/map/?start=51.050754,13.728650&finish=51.048926,13.745659&type=osmand&profile=bicycle#15/51.0512/13.7286)).

OsmAnd~ 4.6.0#1163m, released: 2023-12-06

<table style="width:100%">
  </tr>
  <tr>
    <th>Car</th>
    <th>Bicycle</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/6a001491-f8a0-4cef-bba4-c3d68cd99643"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/52ca4cce-b805-4b00-aadc-6ed4e66a967b"  width="300" height="auto"/> </th>
  </tr>
</table>



<table style="width:100%">
  </tr>
  <tr>
    <th>(Web) Car</th>
    <th> (Web) Bicycle</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/224abafa-98ce-4480-b189-71c265a6b2fd"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/96d5c158-0e8d-4e7c-bd70-70529b54d675"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
To do @xmd5a2 - should be investigated whether the general map state is ready to revert wrong fix with ```vehicle=no```

**Comment by scaidermern** [comment]
> All of these ways will be forbidden for bicycle if we will not ignore `vehicle=no` for bicycle routing.

Why?

All your examples have `bicycle=designated` set. `bicycle=*` weights stronger than `vehicle=*` for bicycle routing. [Access keys](https://wiki.openstreetmap.org/wiki/Key:access) in OSM have a well-defined hierarchy. If both `vehicle=no` and `bicycle=designated` (or `bicycle=yes`) are present, bicycle routing is and should be allowed!

**Comment by xmd5a2** [comment]
There are more than 230 cycleways in Europe returned from [this overpass query](https://overpass-turbo.eu/s/1FNl). All of them will be forbidden for bicycles if we remove ignoring of `vehicle=no`.
![Screenshot_2024-01-10_12-16-20](https://github.com/osmandapp/OsmAnd/assets/5829014/fcfb7446-0f0f-450e-baae-cfeb96cf21fc)
[cycleways.zip](https://github.com/osmandapp/OsmAnd/files/13885676/cycleways.zip)

Most of them have tags like this [way](https://www.openstreetmap.org/way/604240810) (looks like wrong mapping, `bicycle=yes/designated` missing): 
```
highway=cycleway
surface=asphalt
vehicle=no
```

**Comment by scaidermern** [comment]
> Most of them have tags like this [way](https://www.openstreetmap.org/way/604240810) (looks like wrong mapping, `bicycle=yes/designated` missing):

Yes, this is a mapping error that should be corrected.

Not all results of your queries are mapping errors, though. [Way 41055365](https://www.openstreetmap.org/way/41055365) looks correct, for example. This is a cycleway that has been closed. It has [gates](https://www.openstreetmap.org/node/500330464) on both ends with `access=no` and there is an [alternative path](https://www.openstreetmap.org/way/41055364) available. So the number of tagging errors is probably less than 230.

**Comment by xmd5a2** [comment]
Fixed. How to test: https://github.com/osmandapp/OsmAnd/issues/18652#issuecomment-1843062001

**Comment by yuriiurshuliak** [comment]
Bug has been fixed. I checked the fix by adjusting the date on my phone to December 25th and testing the issue. The vehicle=no tag is now properly considered for bicycle and car navigation.

OsmAnd~ 4.7.0#1390m, released: 2024-01-19

<table style="width:100%">
  </tr>
  <tr>
    <th>Car</th>
    <th>Bicycle</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/2ab48e5b-b734-4824-a859-3ab8bb5f0404"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/4669d49b-d060-4bc7-985c-189ef512f208"  width="300" height="auto"/> </th>
  </tr>
</table>
