### ISSUE TITLE
"enable" / "use of" the "back button", back to the result of a search

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#18661]
### Describe the idea (required)

Many times a search offers a long list of results and very often I dont know which one of these is the correct one.
Happens witrh small villages and (way more often) when searching for a shop like super markets (like searching one branch in a bigger city, the result can go up to 30 branches in the surrounding area). 

But once I´ve selected / displayed one on the map - and see it´s the wrong one - I can´t go back to the search result.
The "back" button as well as the "back arrow on top" closes the search and I have to start over from the beginning.

### Tell us about the expected behaviour (required)

Use of any "back"-option that brings me back to the search results would be a great help, thanks (and only the second "back" should exit the search).

### Tell us about alternatives you've considered (required)

No alternatives, I have to start the search again from the very beginning...

**Comment by DmitryAlexei** [comment]
Probably tap on the magnifying glass (search button) should return previous search results with the option to dismiss them, instead of starting a new search?

**Comment by Rowin63** [comment]
I don´t think this is what I´m missing. 
What I´m thinking is, after selecting/tapping ONE item of the search result list and get it displayed on the map (and see it´s not the one I was searching for), the possibility to go back via some kind of "back switch" to the search I´ve done right before and select another item of the searches result list. 

Like here: this is the result list from the search for "billa" (supermarkets):

![Screenshot_20231203_160802_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/95540936/424818c8-941a-4233-9bc5-a713f95a56a9)

After tapping one enty of this list I´m lead to the map.:

![Screenshot_20231203_160817_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/95540936/7ca2fa57-30a8-435b-a9f5-115153a7c385)

And here I see, it´s not the one I was searching for. 
But from here now I can´t go back to the search list again, to select another entry from this list. 
Tapping "back" closes the displayed result and brings me back to the map screen.

**Comment by itzikiap** [comment]
This is why " show on map " exist, it shows the search results as POIs on the map.
But I agree that it's comfusing, this option should be much clearer, and maybe even default behavior.

**Comment by Rowin63** [comment]
Hmm, in both you´re right. 
"show on map" displays all the results on the map,
And if already (some/many) other favorites and/or POI´s have been on display before, it´s getting a bit confusing to find .... 
But in general, yes, you´re right.

**Comment by vshcherb** [comment]
This is a valid request and if I'm not mistaken it was working like that till certain version.
- General rule is not followed you need to go back where you started unless you started interacting with the map
- Once you started interacting with the map (then we could allow to loose context ) to not show the whole history of fragments etc. 
- But until you stayed in context menu you should be able to go back (Track selection screen, Favorites, Search ...) Actually it works with Favorites.

**Comment by vshcherb** [comment]
To do: implement similar approach as we have with Tracks and Favorites.

**Comment by pebogufi** [comment]
Fixed, Now I love it  !

**Comment by dmpr0** [comment]
# Review 
Not all devices has back button, so for them it will only by back swap.
- [ ] Show white search bar above context menu when POI opened from search

**Comment by vshcherb** [comment]
Moved as separate task https://github.com/osmandapp/OsmAnd/issues/18727

**Comment by sonora** [comment]
> So do I 👍

Yes it's great, love it, too! Only one small thought! When after one search you later tap not the back button, but tap the search icon again (or Menu > Search), you would expect to start a _fresh_ search (with empty search string), not as it is now act the same as tapping the back button, i.e. go back to the last search?

**Comment by vshcherb** [comment]
Side effect but it might be useful, so we're not reverting it
