### ISSUE TITLE
Trafic Warning for Toll-bridge

### ISSUE THREAD

**Issue by CJTmmr** [osmandapp/Osmand#1866]
Hello,

In my neighbourhood there is a bridge, the [Tolbrug Nieuwerbrug](http://www.openstreetmap.org/way/362820327#map=18/52.07805/4.81205) for which you have to pay a small toll-fee (Eur 0.50, only for motorvehicles)
It is tagged with **toll=yes** (I shall add **toll:bicycle=no** in a minute..)

On Osmand-release 1.9 and 2.0 this you got a warning by a sign with a **$**.
On 2.1 and nightly's OsmAnd shows the : "forbidden for all-except pedestrians"-sign.
![2015-11-03 16 01 16](https://cloud.githubusercontent.com/assets/15076257/10918948/860c8a48-8268-11e5-9f0d-d067b1efa0aa.png)

This is confusing. 

Thanks,

CJTmmr

**Comment by sonora** [comment]
Yes, I can confirm that we somehow lost the Dollar sign in our icon and instead only display the  empty sign in many countries interpreted as "no access". Should be changed back.

**Comment by hakuchi** [comment]
I can confirm this.
On all barrier=toll booth I passed in the last, the sign was shown as CJ reported.

But the dollar symbol not looking good for all user.
I think it is better to ad a more international symbol, like this:
![Toll](http://www.startrescue.co.uk/blog/wp-content/uploads/2013/01/road-toll-300x204.jpg)

**Comment by vshcherb** [comment]
Dollar sign added temporarily, I think we will implement suggested image.
