### ISSUE TITLE
Osmand search does not honor city name when entered in the search field (lens) separated by comma

### ISSUE THREAD

**Issue by dbojan** [osmandapp/OsmAnd#18669]
### Description

Osmand search does not honor city name when entered in the search field (lens)
For example:
apostola, Dubica
should search for:
(Church) of Apostola, (in the city of) Dubica

### Steps to reproduce

click on lens,
enter  
apostola, Dubica

### Actual result

20+ results are shown, with various cities. this can be checked by clicking on the item list.
City of Vlasenica, which we did not search for. It is not limited to city of Dubica, or sorted by Dubica first.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/1901895/54c2e962-b713-4470-843a-a9bfc3ccd492"  width="300" height="auto"/> </td>
  </tr>
</table>

### Expected result

It should display only results which have 
'apostola', and 'dubica' in it
or atleast sort by city name 'dubica'. Instead two first results are for the city of Vlasenica.

the way it is done in magic earth app, which uses OSM data

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/1901895/5b8bbb0e-6e07-4591-a327-27ae4f9a0859"  width="300" height="auto"/> </td>
  </tr>
</table>

or Organic maps app, which also uses osm:
not limited to search city, but at least sorted properly.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/1901895/cb0c6d58-3d7d-4c24-b01b-43922af36276"  width="300" height="auto"/> </td>
  </tr>
</table>

Osmand has the city data, it is not used in the search, which can be checked when you click on the correct item, if you find it:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/1901895/fcc7c7b8-291d-4884-a1a1-968e2a4a935e"  width="300" height="auto"/> </td>
  </tr>
</table>

Yes I know about the last tab, which is supposed to be used by entering the city name, and then street. But
1. I am not looking for a street
2. that option is confusing, most people would just enter item they are using by with name of the city, separated or not by comma. Or at least I would search that way.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:4.6.0#1135m
Android/iOS version: android 10 / Syberia, no Google
Device model: Xiaomi Mi A3
Crash-Logs: ?
```

**Comment by dbojan** [comment]
could be related to: Searching for place should display city name, and street. #18668

**Comment by DmitryAlexei** [comment]
@dbojan in your first screenshot, the needed place of worship is the third search result.  Firs two results are the streets in Vlasenica. This is how offline search works. 

If you use online search inside OsmAnd (https://osmand.net/docs/user/search/search-all#online-search-android), you will get perfect search result (see screenshot). Please note that you need to center the map by the location where the search will be performed.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/be2b9ef1-db3c-4999-91ff-fd88d9890fd7"  width="300" height="auto"/> </td>
  </tr>
</table>

To get better search results using offline search, you should first search for a city and then for a POI (point of interest)
You can read how to search for POIs in the docs https://osmand.net/docs/user/search/search-poi#how-to-use
You'll get something like that 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/8d028d86-64a4-4759-aeaa-8d346a48cf08"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by dbojan** [comment]
Thank you for your reply.

> @dbojan in your first screenshot, the needed place of worship is the third search result. The first two results are the streets in Vlasenica. It is necessary to distinguish between address search and POI search.

Thanks, but how is user supposed to know that? It does not display city name anywhere.

 > If you use online search inside OsmAnd (https://osmand.net/docs/user/search/search-all#online-search-android), you will get perfect search result (see screenshot). Please note that you need to center the map by the location where the search will be performed.

Nice, but the point of offline maps is to be offline, and not to have to use mobile internet?

The way it is now, other programs have superior search results display. (Organic maps, Magic Earth). I'd rather see Osmand search improved, so I can use that if possible.

**Comment by vshcherb** [comment]
The icon on the left displays it's a street. 

So I think the issue is linked to display city next to the search. https://github.com/osmandapp/OsmAnd/issues/18668

Also if search would be faster x5-x10 times we could resort results based on the matching words cause dubica doesn't match with first 2 results. But that's require much faster search first of all.

Related issues:
- https://github.com/osmandapp/OsmAnd/issues/16397 - another issue cause here the focus is on Brands.
- https://github.com/osmandapp/OsmAnd/issues/4741 
- https://github.com/osmandapp/OsmAnd/issues/5409
