### ISSUE TITLE
New target zoom concept for "Show on map" operations

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#1867]
We are in the process of re-working our UI to the effect that tapping any location on e.g. a search results screen (POI, address, favorite, etc.) always first displays the location on the map, then a pop-up bubble offers all possible subsequent actions.

When displaying the location on the map, we always immediately zoom in to a "neighborhood" zoom level, arbitrarily set to 15 or 16 for most of our operations. And if the map is already zoomed in further than that we leave it at that zoom.

This is the "old fashioned" behavior internet map searches have to apply because they mostly have no history or context of what a user previously viewed or where they are located. Hence when for instance clicking on the "Where are we" widget on a hotel web site, the programmer has to make an assumption whether users clicking on that want to primarily see the hotel's neighborhood surrounding, the part of town, or the long distance "how to get there" map.

Being a map app, we can do better than that, because we know what the user previously viewed on the map, and can assume that users often first want to see a target location with respect to a previously viewed location (which will often, but not always, be their own location). What I am saying is when e.g. looking for a gas station, a restaurant, or a mountain peak name, users are mostly first interested where something is with respect to themselves (or another previously explored location), and the actual neighborhood view is secondary at most (or irrelevant, like for gas stations or mountain peaks).

As a result I suggest the following:
In our new UI, let us split the process of viewing found locations into 2 steps:
- The first tap on any location search result displays the location on the map at a zoom level such that the last map location viewed by he user (which can be the current position or another location the user previously explored, like a city center) fits on the same map screen. So the first view will be a perspective of the location searched with respect to the previously viewed location. (Almost like we first show the whole route for a newly calculated route).
- If subsequently the user taps on the location title in our new context popup bubble, the map will zoom in to the neighborhood level (say 15 or 16, let us make it consistent), much like we have it today.

This may sound unconventional, but may prove to be a true innovation beyond the old-fashioned "static" way of always showing the neighborhood map? And I think it also improves over the classic map search behavior of context-less internet map searches.

**Comment by vshcherb** [comment]
Just to clarify suggestion. Do we expect, that when user switches from the search back to the map, we would like to see both (!) previous viewed position and search location, in that sense we zoom out (up to 10th level) to make it visible.

**Comment by sonora** [comment]
Victor, yes, I have thought about it or a few weeks now, and that is my suggestion. And I would not limit it to any zoom level like "up to 10th level", just make it unlimited.

I often travel intercontinentally, and then e.g. in Mexico I may be asked by a Spanish colleague "Do you think we are further south now than my home town in the South of Spain?",  So that is a question people may want o clarify even on an intercontinental level. and while I realize that most searches will happen locally, regionally, or on a country level, there is  no harm If we also cater for the (very few) global searches where we may have to zoom out to level 1 or 0 to display the answer. Why not? No harm done, it will not happen very often,  but where it happens, it may be intentionally!  :-)

**Comment by Barrocas** [comment]
Sounds interesting. 
I have had situations where I had to search for fuel stations while navigating, and it would have been nice to have that view.

**Comment by vshcherb** [comment]
Pseudocode
while(!isLocationVisible(previousMapLocation, zoomToShow)) {
  zoomToShow—;
}

**Comment by crimean** [comment]
Previous location stays on map as suggested by sonora. 
Also I added new action: zoom in the map to 15 zoom level while pressing context menu title.
So pressing title first time while maker is not in center of the screen will center the map. And pressing on menu title while marker is in the center - causes zooming in to 15 zoom level if current zoom level < 15.

**Comment by sonora** [comment]
I think this works great, but I would like us to try one more small improvement:

Upon the first "Show on map" action, we currently already place the orange map marker in the middle of the map screen. With your own position being near one edge, we essentially "waste" half the screen and zoom too far out.

I guess for the first screen we could use the same approach as for when a route has finished calculating, where we display the entire route, with the staring point being near one edge of the screen and the destination being near the opposite edge?

This would also make it more discoverable how we actually chose tis initial zoom level.

Subsequently tapping on the context menu then would center the target and zoom in like @crimean has already implemented, no change there.

**Comment by vshcherb** [comment]
I think it is not a good idea because zoom in buttons won't work correctly (I put a comment in another thread).

**Comment by sonora** [comment]
That's a pity, because seeing both points and using the "full screen" in between would much better support the "user experience" of how this feature works.

I think what you mean is that a zooming action using zoom buttons would actually zoom into the "middle" of both points?

But that is just the same on the "Route is calculated - display entire route" screen (where we have always used this concept), and I think it is not an issue because (just like on the "Route is calculated - display entire route") on this "here is your search hit with respect to your position" screen also there are actually no zoom buttons!  Instead zooming in must be performed by tapping on the point's context menu  (in analogy in the navigation case by tapping the "Go button").

And exactly how to create better awareness that tapping on a point's context menu centers it and zooms in is the topic we explore in #2633.
