### ISSUE TITLE
Downloading offline Maps

### ISSUE THREAD

**Issue by bitnapper** [osmandapp/Osmand#1868]
When downloading offline maps OsmAnd first downloads all maps and then installs them. This takes a lot of space which is a problem on some devices. One can manually load the maps one by one when not enough space is available but it would be nice if osmand would automatically install a map after downloading instead of wating for all maps to be downloaded.

**Comment by vshcherb** [comment]
Already implemented

**Comment by bitnapper** [comment]
Really? I've just tried it and it tries to download all maps and install them after downloading them all instead of installing the downloaded map and then continuing downloading the next.

**Comment by vshcherb** [comment]
It was implemented 1-2 weeks ago in the nighly builds, so sooner will be in release

**Comment by bitnapper** [comment]
Oh, thats good. Thanks.

**Comment by SparkyCola** [comment]
You're welcome.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
