### ISSUE TITLE
"Inverse logic" of the Terrain switch ("Disable" makes the shades appear, and vice-versa)

### ISSUE THREAD

**Issue by Max1234-Ita** [osmandapp/OsmAnd#18681]
### Description

I created a virtual Tablet with Android 14, in Android Studio emulator, installed OsmAnd v. 4.5.10 and configured the map like this:
 - Contour lines: Enabled
 - Hillshades: Enabled
 - 3D relief: Enabled

Due to some reason, the hillshades were not visible, until I went back to _/// -> Configure map_ and DISABLED the hillshade layer: that made the shades appear. 

I also noticed that turning back on the option makes them disappear.

Unfortunately I could not understand how did I get into this state: this isn't the first emulator I set up with the same OsmAnd version, but I never saw that before today.

Also, another user from the English/International Telegram group confirmed the same behaviour with a real smartphone with Android 11: I have a smarphone with Android 11 too, but the Hillshade toggle is working properly there.

### Steps to reproduce

Here's what I did while configuring OsmAnd: hope the behaviour is reproducible

1. Have a Tablet with Android 14; In my case, I created a new AVD in Android Studio. Turn it to Landscape mode (I selected this mode as the default at startup) and perform all the next steps by keeping it in that orientation.
2. Install OsmAnd 4.5.10 from Google Play Store;
3. Perform login to OsmANd Cloud and restore the Pro subscription (Needed to enable the 3D relief rendering later);
4. Go to menu _/// -> Download maps_; install the following map packages in the presented order:
  <t>- World Altitude Correction
  <t>- General World map
  <t>- Europe/Italy/Standard maps (20 maps)
  <t>- Europe/Italy/Contour lines
  <t>- Europe/Italy/Terrain map

5. Go to menu _/// -> Configure map_ and perform the following settings:
  <t>- Contour lines: Enable
  <t>- Terrain: Enable (Hillshades, zoom: 4-17, opacity: 40%),
  <t>- 3D relief: Enable

6. Check the presence of the hillshades on the rendered map: in my case they were missing although the terrain switch was set to Enable.
7. Toggle the Terrain switch to "off" and check again the hillshades on the map: in my case they were visible (see attached screenshots)

![image](https://github.com/osmandapp/OsmAnd/assets/15315381/c4d1c2b5-c975-4f24-a0bd-19f5c2238372)

![image](https://github.com/osmandapp/OsmAnd/assets/15315381/2278025c-e5c2-4e85-9275-438aaf5d4f1c)

### Actual result

The hillshades are visible when the terrain switch is "off" and disappear when "on".

### Expected result

The hillshades should become visible when the terrain switch is "on" and disappear when "off".

### Your Environment (required)

```
OsmAnd Version: OsmAnd Plus v. 4.5.10
Android/iOS version: Android 14
Device model: Google Pixel Tablet (API 34, AVD, emulated in Android Studio); display: 2560x1600 px

Crash-Logs:  None
```

**Comment by DmitryAlexei** [comment]
@Max1234-Ita 
This issue appears to be very similar to these https://github.com/osmandapp/OsmAnd/issues/18179 and https://github.com/osmandapp/OsmAnd/issues/17783 issues. 
- It is not clear on your screenshot, but I think these shades are not hillshades, rather 3d relief (please see what is the difference in docs https://osmand.net/docs/user/plugins/contour-lines#hillshade-and-3d-relief)
You can check development plugin settings (vertex hillshades should be disabled) and clear cash of the app.
You can also try beta version of the app and see if hillshades are working.

**Comment by Max1234-Ita** [comment]
> @Max1234-Ita This issue appears to be very similar to these #18179 and #17783 issues.
> 
>     * It is not clear on your screenshot, but I think these shades are not hillshades, rather 3d relief (please see what is the difference in docs https://osmand.net/docs/user/plugins/contour-lines#hillshade-and-3d-relief)
>       You can check development plugin settings (vertex hillshades should be disabled) and clear cash of the app.
>       You can also try beta version of the app and see if hillshades are working.

Hi @DmitryAlexei,
In my screenshots all the features are used: Contour lines, hillshades and 3D Relief.
In the first, the Terrain switch is enabled but the hillshades are not visible; in the second, the same switch is turned off and the shades are present.

I also tried disabling the 3D relief, and there was no hillshades at all, no matter the status of the Terrain switch.
So it looks like the hillshade layer is masking somehow the 3D relief shading itself, making it visible when the terrain layer is disabled...

**Comment by DmitryAlexei** [comment]
@Max1234-Ita The issue you are describing should have already been resolved. Please try beta and say if it is ok for you.

**Comment by Max1234-Ita** [comment]
Tried with OsmAnd v. 4.6 Nightly, it looks to work properly.
I disabled the 3D relief and the hillshades are now visible.

Thank you so much!

![image](https://github.com/osmandapp/OsmAnd/assets/15315381/dcc33b20-7cb0-45fb-8720-55e513b0bc6e)
