### ISSUE TITLE
Missing Announcement Turn right - Straight Exit from Circle track 

### ISSUE THREAD

**Issue by Peter0** [osmandapp/OsmAnd#18699]
### Describe the routing engine used (required)

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Describe your routing Profile (required)

Bike

### Describe your start and end points (required)

Start: 49.13050 10.76437
Dest.: 49.12997 10.76516

### Describe the actual route (required)

The route looks ok, but ...

### Describe the expected route (required)

... at node 35510420 I expect getting a turn direction ("turn to the right"). Osmand gives no direction, encouraging the user to follow the road 82586625 heading to the north, if one don't stare at the map screen.

### Describe what Maps you used (online or offline) (required)

- [x] Offline maps offered within the OsmAnd app for download.  2023-12-09,2:10
- [ ] Online (tile / raster) maps 

### Your Environment (required)

```
OsmAnd Version: ~4.5.10
Android/iOS version: e/OS 0.12-p
Device model: Samsung J5
```

### Anything else? (optional)

I tried to change map data in a way that the junction looks more square, but currently I think the margins should not be more bent.

**Comment by mbartlett21** [comment]
![Screenshot_20231210-065427_OsmAnd_1.jpg](https://github.com/osmandapp/OsmAnd/assets/29034492/ca56093c-a95f-4d2e-9183-07e6722f818c)

Here is a screenshot of that route with old maps for reference

**Comment by zipav** [comment]
OsmAnd Nightly 4.6.0#1204m, released: 2023-12-13

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/8f5dd5f0-0d08-4696-8009-a929718ea4e6"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Peter0** [comment]
Currently the leaving way 1126450370 has tracktype=grade2, as well as the way to south east. Meanwhile the way to north east 82586625 has tracktype=grade1. I am currently not on the spot, but in my remembrance this is not justifiable. In my remembrance, the way from west and the one to north east appears as a smooth continuing way, while the one to south east's surface is clearly worse. I am discussing with locals if my remembrance is impartial or not. If that is true, I think this is worth giving the user/driver an acoustical turn direction, even if it would made out to something like "turn ahead" or "don't turn left". And even if not, I think there should be something like a "verbose mode" that is giving such directions anyway.
Hope that I got my ideas across, Peter

**Comment by vshcherb** [comment]
We need to fix and add test: https://test.osmand.net/map/?start=49.130500,10.764370&finish=49.129970,10.765160&type=osmand&profile=bicycle#20/49.13029/10.76461

**Comment by ivanPyrohivskyi** [comment]
Zoom of map is too small. We use bearing distance for calculate road intersection in 15 meters. If to decrease bearing to 5 meters then right turn was calculated. Otherwise turn calculated as continue of previous road (direct moving).

**Comment by vshcherb** [comment]
Based on this route do not displaying turn right is correct cause technically it's going straight. The only confusion here comes from the point that you are on a circle track and any straight or different exit should be announced. 
![image](https://github.com/osmandapp/OsmAnd/assets/1042025/ecfdf28a-8dfc-45e7-b78d-b2722b20a8c5)

So I think here is exceptional case that we can't support.
