### ISSUE TITLE
osmand considers hexagonal roads forms as roundabout

### ISSUE THREAD

**Issue by willemijns** [osmandapp/Osmand#1869]
hello, 

for this road http://www.openstreetmap.org/#map=18/49.58241/3.64490

a contributor created a long hexagonal http://pad1.whstatic.com/images/thumb/4/4e/Draw-a-Hexagonal-Prism-Step-1.jpg/670px-Draw-a-Hexagonal-Prism-Step-1.jpg to (badly) earn time

side effect is osmand think it is a roundabout ! 

X days ago, i exploded it in 2 parts and now OSMAND considers that as 2 parallels roads...

=> every hexagonal form are not roundabout ;) <=

**Comment by vshcherb** [comment]
May be it used to be tagged as roundabout, can't reproduce it. Just tested and I don't see any instruction related to roundabout

**Comment by willemijns** [comment]
I changed the attributes 2 days ago but the rounabout sign still be present with the October 3 version of compiled "picardie france" on http://download.osmand.net/list.php

**Comment by willemijns** [comment]
argh ! DB has been converted yesterday, osmand app tell me that....  not http://download.osmand.net/list.php

**Comment by vshcherb** [comment]
We can schedule one map update there is no issue. (picardie)

**Comment by willemijns** [comment]
sorry i do not follow you

**Comment by vshcherb** [comment]
I regenerated Picardie map on the server, so it should include the changes already.

**Comment by willemijns** [comment]
good for me. i had an older file from june 2015 which contains that...

https://drive.google.com/file/d/0B_qSrVQ92ur9NE8wSVJUTnNIVm8/view?usp=sharing

see yourself than OSMAND indicate a roundabout but it is not a square but a long hexagonal....

picardie file is here: https://drive.google.com/file/d/0B_qSrVQ92ur9cEQtMkMzN0doczQ/view?usp=sharing

**Comment by willemijns** [comment]
still closed ?
