### ISSUE TITLE
Calculation never finishes, Bad Brambach to Dresden, Germany

### ISSUE THREAD

**Issue by limbusdev** [osmandapp/OsmAnd#18707]
Edit: after a few minutes waiting it proceeded and finally calculated the Route. But it was stuck for quite a while.

### Describe the routing engine used (required)

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Describe your routing Profile (required)

Default car profile (no manual changes)

### Describe your start and end points (required)

Start: 50.22412° N, 12.29832° E
End: Bünaustr. 4, 01159 Dresden, Germany

### Describe the actual route (required)

Calculation never finishes

### Describe the expected route (required)

Any route

### Describe what Maps you used (online or offline) (required)

- [x] Offline maps offered within the OsmAnd app for download.  2023-12-01
- [ ] Online (tile / raster) maps 

### Your Environment (required)

```
OsmAnd Version: OsmAnd~ 4.5.10
Android/iOS version: Android 14
Device model: Pixel 6
```

**Comment by limbusdev** [comment]
Closed. Just took very long.

**Comment by vshcherb** [comment]
Will be improved with special routing in 4.6 and in 4.7 will be default algorithm
