### ISSUE TITLE
Offline Routing: Route through trunk_link

### ISSUE THREAD

**Issue by hsw** [osmandapp/Osmand#1871]
OsmAnd~ 2.1.1, Russia_central-federal-district_asia.obf (2015-11-04), Russia, Bryansk, P120

![2015-11-05 11 55 32](https://cloud.githubusercontent.com/assets/47301/10967963/597f5812-83cf-11e5-9a6a-7e2f8860ebe5.png)

vs. http://www.openstreetmap.org/directions?engine=osrm_car&route=53.2014%2C34.5069%3B53.1974%2C34.5140

Route must use trunk_link: http://www.openstreetmap.org/way/74117448

**Comment by utack** [comment]
"oneway" without a direction is really hard to process
It has to guess the direction based on the geometry
Maybe it could use trunk_links that are tagged with direction for now?

**Comment by vshcherb** [comment]
That's reproducible issue and it is very strange, I didn't manage to understand yet what exactly causes it.

**Comment by hsw** [comment]
It works correctly in version 2.2.4
