### ISSUE TITLE
access icons flooding the map at roads with access=private

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#18713]
### Description

Since recently OsmAnd draws oneway icons at the start and the end of (some?) roads that have access=private set:

![photo_2023-12-11](https://github.com/osmandapp/OsmAnd/assets/1040784/58bffc5b-9831-4c96-b4f4-14fd4ab9ae0e)
Location: 51.03030, 13.82014
https://www.openstreetmap.org/way/105644365
https://www.openstreetmap.org/way/202194762

This is quite irritating and also wrong in many cases. The oneway icons that I highlighted in blue are placed in the middle of the residential road and make it look like a oneway road, although the residential road is not oneway. Moreover, nowhere in this area is any oneway tag at all.

### Steps to reproduce

Open the specified location in OsmAnd.

### Actual result

Many oneway icons although no oneway roads are present.

### Expected result

No oneway icons.

### Your Environment (required)

```
OsmAnd Version: 4.6.6
Android/iOS version: Android 10
Device model: Samsung S10
```

**Comment by goldfndr** [comment]
https://github.com/osmandapp/OsmAnd/issues/10983#issuecomment-1845109178

**Comment by vshcherb** [comment]
Yes we will revert temporarily with these changes

**Comment by xmd5a2** [comment]
Reverted
