### ISSUE TITLE
Display top bar when opening from Search

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#18727]
- We need to display top bar when opening from Search so we can get back quickly.
- Once tap on screen top bar should disappear

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/7a22cc22-bfdf-415b-a1e9-d8f37aca6a69"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

Not all devices has back button, so for them it will only by back swap.
- [ ] Show white search bar above context menu when POI opened from search

**Comment by sonora** [comment]
We have the following inconsistency now we should try to align in the process:
- Go to MyPlaces > Tracks, tap on a track, it's shown on the map (with its context menu open). Now tap the Back buton: The track screen is shown again
- Go zo Search: It now behaves the same.
- But go to MyPlaces > Favorites, tap on any to view it on the map. Now tap the Back button: _The context menu simply disappears_. Only a second tap on back brings you back to the Favorites screen.

I guess all 3 cases should behave alike: Either a first tap on the Back button always just closes the context menu, or it always puts you back to the originating list screen.

**Comment by vshcherb** [comment]
With Favorites it's actually a bug but probably not related to Search
