### ISSUE TITLE
Map source "Define/Edit..." popup unusable in French (and probably other languages)

### ISSUE THREAD

**Issue by bagage** [osmandapp/Osmand#1872]
I think this is due to the too-long text "Choisir un fournisseur de tuiles existant...", but basically the popup does not fit the screen:

 ![screenshot_2015-11-05-19-46-11](https://cloud.githubusercontent.com/assets/1451988/10978337/a8680290-83f6-11e5-918f-3b8b73ead99f.png)
![screenshot_2015-11-05-19-46-25](https://cloud.githubusercontent.com/assets/1451988/10978338/a9544c54-83f6-11e5-829b-0e7aa6a060a0.png)

Of course an hint could be given to translators to not make long sentences to avoid this issue, but it would be great if Osmand could truncates to X (15?) maximum characters in any case to avoid this.

In the mean time I did a pull request on [OsmAnd-Misc](https://github.com/osmandapp/OsmAnd-misc/pull/90) but not integrated yet. Should I do it elsewhere or can you integrate it? Thanks!

**Comment by GaidamakUA** [comment]
Thank you for your suggestions. We made small redesign of this dialog with commit 3e1e89b and now it should not be problem any more.
