### ISSUE TITLE
Problem with road rendering in the live update

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#18722]
### Description

After dividing the street line into two, something strange is drawn in the live update.

### Steps to reproduce

Open in Osmand
https://www.openstreetmap.org/#map=18/59.91753/30.29700
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/12549744/8e133d47-4d3a-4ad7-ab91-93efbdb5797e"  width="300" height="auto"/> </td>
  </tr>
</table>

### Actual result

Given above.

### Expected result

Display data in live update without bugs.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:OsmAnd~ 4.6.0#1181m, Дата выпуска: 2023-12-09
Android/iOS version: 13
Device model: poco f3
Crash-Logs: ?
```

**Comment by Nine-Tailed** [comment]
Original source
https://t.me/ruosmand/142227?single

**Comment by Nine-Tailed** [comment]
When and how will it be possible to see that the problem has been solved?  At the moment the problem is still present in the latest nightly build of Osmand.

**Comment by vshcherb** [comment]
Next similar issue won't appear, this one won't be fixed unfortunatley cause it will require ful month regeneration

**Comment by zipav** [comment]
OsmAnd Nightly 4.7.0#1352m, released: 2024-01-11

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/9f3465cc-04a6-4607-861f-cafc94b71293"  width="300" height="auto"/> </td>
  </tr>
</table>
