### ISSUE TITLE
Locality names is hard to read

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#18728]
## Description
Locality names is hard to read on green background especially if Terrain is On.

### How to reproduce
* Open OsmAnd
* Search `47.03388° N, 8.96517° E`
* Try with enabled and disabled Terrain

### Actual result

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Terrain: On</th>
        <th>Terrain: Off</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/48deb5a4-cca2-4391-a542-44cf3afbddb0"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/df6d2f42-335d-461e-ae5f-3fe1390a0a3d"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

### Expected result
* Better visibility 

**Environment**
OsmAnd Version:
Android/iOS version:
Device model:

**Comment by xmd5a2** [comment]
Fixed. Should look like this in day mode on dark and light background.
![Screenshot_2023-12-14_09-35-14](https://github.com/osmandapp/OsmAnd/assets/5829014/9931d614-2c43-442c-b7b1-9ab731ecfd2d)
![Screenshot_2023-12-14_09-36-21](https://github.com/osmandapp/OsmAnd/assets/5829014/d46c783e-b46d-469b-83ed-e0b50bf21fb0)

**Comment by dmpr0** [comment]
# Review 
- [ ] All test should be done on real devices and software
- [ ] Use dark colors for stroke

**Comment by xmd5a2** [comment]
Can't agree with "Use dark colors for stroke" because this is text for **day** map and it will be hardly readable on light background. It is impossible for now to render text in different styles for dark and light background in **day** mode.

**Comment by vshcherb** [comment]
Dark text on white background is not readable in **dark mode**, that's obvious and can't be fixed. So only dark or transparent colors are acceptable  - @xmd5a2

**Comment by xmd5a2** [comment]
> Dark text on white background is not readable in **dark mode**, that's obvious and can't be fixed. So only dark or transparent colors are acceptable - @xmd5a2

@vshcherb Have you read original issue? If we use dark colors for stroke then we have to make text white or near-white. Issue concerns about **day** mode, **not** night (dark) mode. In day mode without terrain white text with dark stroke is near unreadable.
I don't know how to fix this another way. Proper fix can be done by adding **blending mode like in Photoshop** or something like that.
Besides we are talking about _place=locality_ which should be different from other place names.

**Comment by xmd5a2** [comment]
Actual screenshots:

![Screenshot_2023-12-28-13-52-36-624_net osmand plus](https://github.com/osmandapp/OsmAnd/assets/5829014/e493386e-ac59-4d67-8a63-577b95d3fda1)
![Screenshot_2023-12-28-14-09-23-233_net osmand plus](https://github.com/osmandapp/OsmAnd/assets/5829014/76ffb1f8-c0f8-4b0c-a508-523104ea3e6f)
