### ISSUE TITLE
Osmand opposite directions

### ISSUE THREAD

**Issue by Owen2159** [osmandapp/OsmAnd#18725]
### Description

I have created a driving route, the route shown on the screen is accurate but at some intersections the direction voice and the direction arrow are the opposite of the route on screen.
A left turn on shown on the map is advised as a right turn by vouce and arrow. Not all intersection advice messages  are incorrect, probably about 20%

### Steps to reproduce

See above

### Actual result

See above

### Expected result

See above

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```
Android

**Comment by DmitryAlexei** [comment]
Please attach your route, so we can reproduce the described behavior.
Build navigation > go to Details menu > export your route in .gpx format. Please add .txt extension to it, otherwise you won't be able to post it here.
For more information see https://osmand.net/docs/user/navigation/setup/route-details#share--export-actions

**Comment by Owen2159** [comment]
Not sure if this is what you need, do I just rename the file by changing .gpx to .txt

________________________________

**Comment by Owen2159** [comment]
On this route there are at least two intersections where the map shows turn left which is correct but the instructions say and show turn right.
I created the route using a PC running Windows11 Osmand is accessed through the Amazon app store, not sure if that is causing the issue.

________________________________

**Comment by Owen2159** [comment]
Please disregard my emails about this issue. I have found the problem "me".

When I was creating the drive route I was creating the waypoints at intersections, for some of those I dropped the pin slightly off the centre of the intersection so the directions mirrored that slight error even though the map continued on in the opposite direction.

________________________________
