### ISSUE TITLE
Searching emergency_access_point by its reference

### ISSUE THREAD

**Issue by bitnapper** [osmandapp/Osmand#1873]
The mountain rescue service in Sankt Andreasberg tries osmand as a tool for assisting on search for missing persons. Often lost persons can tell on which emergency_access_point they are by its reference but the name is often very different or they have none. It would be a great help if one could search them in osmand by its reference which is like e.g. GS-461 or OHA-123 (district abbreviation and a number).

Also when searching for emergency things in the surrounding area it would be helpful if the result would contain the reference in brackets after the displayed name.

**Comment by xmd5a2** [comment]
Fixed.

**Comment by bitnapper** [comment]
great. thanks.
