### ISSUE TITLE
Keyboard does not open when GPX waypoint is added

### ISSUE THREAD

**Issue by jengelh** [osmandapp/OsmAnd#18734]
### Description

The on-screen keyboard does not show on Android 13 when a new GPX waypoint is added.

Possibly related:
* https://github.com/osmandapp/OsmAnd/issues/11119
* https://github.com/osmandapp/OsmAnd/issues/15265

(Adding a *Favorite* on Android 13 successfully shows the keyboard.)
(Adding a GPX waypoint on *Android 9* successfully show the keyboard.)

### Steps to reproduce

Enable the OSM Editing plugin. Afterwards, click anywhere in the map to call up the point menu, then choose the GPX Waypoint icon to add one. On Android 13, the user needs to explicitly touch the name field to show the keyboard.

https://inai.de/files/osmand_on_moto_edge40.mp4 (Android 13 failure case)
https://inai.de/files/osmand_on_sony_g8441.mp4 (Android 9 success case)

### Actual result

On-screen keyboard is not automatically shown on the Motorola device (Android 13).

### Expected result

On-screen keyboard shall be shown automatically as it does on the Sony (Android 9), or with the Favorites menu (either Android 9 or 13).

### Your Environment (required)

OsmAnd Version: 4.5.10
Android/~~iOS~~ version: 13 Update 01-Nov-2023
Device model: Motorola Edge 40
~~Crash-Logs:~~

**Comment by scaidermern** [comment]
Related to #18258.

**Comment by vshcherb** [comment]
@scaidermern why do you think it's related? It looks Android 13 issue, yes I think we should open keyboard by default for waypoint / favorite.

**Comment by scaidermern** [comment]
> @scaidermern why do you think it's related? It looks Android 13 issue, yes I think we should open keyboard by default for waypoint / favorite.

Because there is a change in behavior between OsmAnd 4.5.x and 4.6.x. Yes, this one here might be an issue with a specific Android version. Still, just fixing opening the keyboard will lead directly to the behavior of this other issue. That's all I wanted to say with the above reference.

**Comment by zipav** [comment]
OsmAnd Nightly 4.7.0#1240m, released: 2023-12-19
Android 12
Nokia 5.3

https://github.com/osmandapp/OsmAnd/assets/123936521/c83647e7-f79a-45d5-9d86-d942d7b9613f

**Comment by vshcherb** [comment]
As we tested this behavior is broken in Android 13, but I don't think we have ability to fix it. Probably we will start using new components in 4.7 and this behavior will be fixed.
