### ISSUE TITLE
[Purchase issue] nautical depth state not stored between app restarts

### ISSUE THREAD

**Issue by quantenschaum** [osmandapp/OsmAnd#18732]
### Description

The state of the nautical depth map setting (en/disabled) is not stored when app is shut down.

### Steps to reproduce

1. enable nautical depth rendering in the map settings
2. quit the app
3. (re)start the app

### Actual result

nautical depth rendering is disabled

### Expected result

nautical depth rendering is enabled

### Your Environment (required)

OsmAnd Version: 4.6.7
Android version: 13
Device model: Nokia X20

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#1205m, released: 2023-12-13 cannot reproduce described behavior on the release 4.5.10 and nightly build. What have I made:
- nautical map view plugin enabled 
- Northern Hemisphere depth points map downloaded
- in configure map menu > nautical depth option enabled (i didn't change settings inside this option)
- displayed on the screen part of the map with nautical depths
- switched off OsmAnd several times
- when I started the app again, the depth points were on their places

**Comment by quantenschaum** [comment]
Sorry, there was a typo in the version number. Should be 4.6.7.

**Comment by quantenschaum** [comment]
[screen-20231214-102459.webm](https://github.com/osmandapp/OsmAnd/assets/3985599/3e09b3b7-41bd-4de5-8f24-cb1c0dff331b)

**Comment by vshcherb** [comment]
Issue is related that Nautical depth is a purchase item, so unless it's not "purchased" it will be reset each restart.

**Comment by quantenschaum** [comment]
OK. I purchased "pro", then nautical depth stays active between restarts of the app.
