### ISSUE TITLE
sqlitedb created by MapCreator can't be displayed in OsmAnd

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1874]
I'm trying to create big sqlite database with tiles. I downloaded area using map creator, then created .sqlitedb file. But in OsmAnd I can see only white background (no satellite imagery)
https://dl.dropboxusercontent.com/u/4624786/osm/Varkala%20Bing%20small.sqlitedb
Log:
```
Ð½Ð¾Ñ 06, 2015 11:54:05 AM net.osmand.swing.SQLiteBigPlanetIndex createSQLiteDatabase
INFO: Index created ÐžÐ±Ð»Ð°ÑÑ‚ÑŒ.Microsoft Earth.sqlitedb 12941 ms
```
http://www.openstreetmap.org/#map=12/8.752528/76.72582

**Comment by vshcherb** [comment]
The file attached looks like created by old MapCreator which is not supported. Just tested new file with 250MB works fine.
