### ISSUE TITLE
'Reset to default' sometimes works, has no confirmation dialogue in widget panel 'Edit' mode

### ISSUE THREAD

**Issue by mikehgentry** [osmandapp/OsmAnd#18754]
### Description

'Reset to default' mode on a widget panel normally has a confirmation dialogue. If you choose 'Edit' then scroll to the bottom, it doesn't. I'm not sure if that's deliberate.

### Steps to reproduce

as above

### Actual result

Immediately erases your widgets.

### Expected result

Perhaps either should have a confirmation dialogue, or be invisible in 'Edit' mode.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: + 4.6.8
Android/iOS version: 11
Device model: Xcover 4s
Crash-Logs: ?
```

**Comment by mikehgentry** [comment]
I stand corrected, it does work, it just doesn't bring up the Confirmation dialogue.

Sorry for the noise, will re-edit

**Comment by zipav** [comment]
OsmAnd Nightly 4.7.0#1240m, released: 2023-12-19


https://github.com/osmandapp/OsmAnd/assets/123936521/964a7ae4-c08a-49fa-bd9e-c3f1981ae810

**Comment by mikehgentry** [comment]
Hmm, sometimes it doesn't work after all actually. Steps:

1. Delete all widgets from a panel.
2. Hit 'Apply'.
3. Hit 'Edit' again.
4. Hitting 'Reset to default' doesn't do anything.

**Comment by vshcherb** [comment]
You can click Apply to confirm the changes or Cancel (top left icon) to not save changes.

In case we didn't understand correctly the issue please provide screenshots and sequence of steps.

**Comment by mikehgentry** [comment]
I created a profile based on Moped. Then I:

* Got to the widget panel, and hit 'Edit'.
* Deleted the default widgets.
* Hit 'Apply'.
* Hit 'Edit' again.
* Hit 'Reset to default' a few times.
* Hit 'Apply'

As you can see, it didn't do anything. Then from within the widget panel's default mode (so without hitting 'Edit') I hit reset to default, and it worked.

https://github.com/osmandapp/OsmAnd/assets/1724168/da6ddfa3-a07e-4cdf-8435-3e36144ee323

**Comment by mikehgentry** [comment]
As to whether it needs a confirmation dialogue, that's a matter of opinion, but I think actions are easy to do accidentally on a touchscreen, and this one's potentially quite destructive. I could definitely see myself scrolling to the bottom, accidentally hitting 'Reset to default' without realising I'd done it, then hitting apply.

A popup notification saying "Panel reset" would work, then the user can just hit 'Apply' or back out with the  back arrow top let to cancel.

**Comment by vshcherb** [comment]
It looks strag
