### ISSUE TITLE
Enable "Dirt Bike" routes settings based on `dirtbike:scale`

### ISSUE THREAD

**Issue by cmoffroad** [osmandapp/OsmAnd#18756]
### Describe the idea (required)

Activate the "Dirt Bike" option in the Route Options menu using a toggle switch for On/Off functionality.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/2485196/a123d5b3-3103-4a24-8d45-f1960a87d9a1"  width="300" height="auto"/> </td>
  </tr>
</table>

### Tell us about the expected behaviour (required)

Upon activation, display a colored route overlay for all paths marked with the `dirtbike:scale` tag, similar to the approach used for `mtb:scale` (Mountain bike).

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/2485196/643f721d-ddf1-4037-9bc4-ed6d5a2ce711"  width="300" height="auto"/> </td>
  </tr>
</table>

### Tell us about alternatives you've considered (required)

Currently, the only option available is to create a custom renderer. With the increasing popularity of dirt bike communities worldwide, particularly in developing countries, I believe it's crucial to enhance data accessibility for them.

### Context (optional)

Optionally, consider renaming the menu item to "Dirt Bike Routes." Alternatively, transform it into a "Motorcycle Routes" menu featuring a sub-menu dropdown:

COLOR ROUTES BY...
- Dirt Bike Scale

This could serve as encouragement for other mappers to introduce a separate scale for on-road motorcycles.

**Comment by vshcherb** [comment]
There is about https://taginfo.openstreetmap.org/keys/dirtbike%3Ascale#overview 8000 segments

**Comment by cmoffroad** [comment]
@vshcherb I have upgraded the existing wiki page and included references to OsmAnd rendering support, to give both tag and project more visibility: https://wiki.openstreetmap.org/wiki/Key:dirtbike:scale

Since `dirtbike:scale` is already supported in OBF process (see https://github.com/osmandapp/OsmAnd-resources/pull/829 ), and values match those of `mtb:scale`, I am hoping the implementation could be straightforward.

If you need any development support, I am happy to submit a partial/full PR if you provide me hints on what files need to be updated.

**Comment by cmoffroad** [comment]
> hello, I've added these tags to the “enduro” rendering that you can find here :

Thanks a lot, Christoph! Really appreciate what you're doing. Still it'd be great to make those `dirtbike:scale` routes visible to all OsmAnd users, no matter which renderer they're using.

By the way, I’d love to see your amazing routing work for enduro get added into OsmAnd :)

**Comment by cricri-du-lauragais** [comment]
thanks :)
 I've added these dirtbike:scale tags to the 3 routings, now it's time to test them.

**Comment by vshcherb** [comment]
The option will be called "Dirt bike roads"

**Comment by cmoffroad** [comment]
> The option will be called "Dirt bike roads".

Great. Can we rename 'roads' to 'trails' instead? Like in MTB, most dirtbike routes are single trails or old double tracks, while unpaved roads are more commonly used by light off-road adventure motorcycles.

**Comment by xmd5a2** [comment]
I've added "Show dirt bike trails" option. Name was chosen according to existing options.
Styling and colors according to @cricri-du-lauragais's [enduro style](https://github.com/OsmAnd-Rendering/Motorcycle/blob/main/Legend.md)
![изображение](https://github.com/user-attachments/assets/32de754a-5362-4a7e-a390-c7dc01dad400)

![изображение](https://github.com/user-attachments/assets/13d1b967-4fde-4908-9ffc-a2e08a5ab298)

**Comment by cmoffroad** [comment]
> I've added "Show dirt bike trails" option. Name was chosen according to existing options.
> Styling and colors according to @cricri-du-lauragais's [enduro style](https://github.com/OsmAnd-Rendering/Motorcycle/blob/main/Legend.md)

@xmd5a2 Great! 

Could you please also add the green dots for dirtbike:scale=0 ? 

I believe this is also how @cricri-du-lauragais designed it: https://github.com/osmandapp/OsmAnd/issues/18756#issuecomment-2082651475

**Comment by xmd5a2** [comment]
Done
![изображение](https://github.com/user-attachments/assets/436e7d4b-96d4-4a19-bae6-ac563ecaebde)

**How to test**: update Thailand map (will be available today), enable "Show dirt bike trails" rendering style option and go to https://www.openstreetmap.org/way/151464598

**Comment by cmoffroad** [comment]
> Done
> ![изображение](https://private-user-images.githubusercontent.com/5829014/365589781-436e7d4b-96d4-4a19-bae6-ac563ecaebde.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNDA2NzMsIm5iZiI6MTcyNjE0MDM3MywicGF0aCI6Ii81ODI5MDE0LzM2NTU4OTc4MS00MzZlN2Q0Yi05NmQ0LTRhMTktYmFlNi1hYzU2M2VjYWViZGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTJUMTEyNjEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjJjMmEzYjAxMGY5NjY0MjkzOGJhNmYwYTY3MTdhYzYyMzhiMjQ4NDUyM2EwZjk0NjA3YjRkOTQ4MDIwZmMzNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.r9OubBwthqBX5aI8oEHmYKT88UprQibdF4CZwWPI3MI)

Thanks, it looks awesome!

Quick thought—do you think it would make sense to use different shapes for levels that are grouped (1/2, 3/4, and 5/6)? Or maybe, since most tags will likely be at the lower end (0, 1, 2), it might be helpful to highlight number 1 with a different color, like yellow. What do you think?

**Comment by dmpr0** [comment]
## ToDo
Android team 

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/7922cfa9-2487-4740-8f05-a2a2761652de"  width="300" height="auto"/> </td>
  </tr>
</table>   


- [ ] Use icon – `ic_action_dirt_motorcycle`
- [ ] Rename to `Dirt bike trails`

**Comment by shurasmiling** [comment]
- https://osmand.net/docs/user/map/routes#dirt-bike-trails

**Comment by Busterama452** [comment]
Would it be a new feature request to add to the dirt bike rendering show any trails that are tagged with "dirtbike:scale=?" or is just adding this comment enough of a request?

From [openstreetmap wiki ](https://wiki.openstreetmap.org/wiki/Key:dirtbike:scale)on the dirtbike:scale tag: _"dirtbike:scale=? can be used to indicate that a specific route is known to be suitable for dirt bikes, although the exact difficulty scale is not known."_

**Comment by cmoffroad** [comment]
> * https://osmand.net/docs/user/map/routes#dirt-bike-trails

Thanks for the fantastic work, OsmAnd team! Hopefully, this feature will attract more dirtbike enthusiasts to the community.

> Would it be a new feature request to add to the dirt bike rendering show any trails that are tagged with "dirtbike:scale=?" or is just adding this comment enough of a request?

I think it’d be a nice addition, but I’m not fully convinced that dirt bike trails with unknown difficulties should be displayed by default to everyone. That said, they do provide a great incentive for mappers to head out, survey them, and retag them properly.

**Comment by Busterama452** [comment]
> > Would it be a new feature request to add to the dirt bike rendering show any trails that are tagged with "dirtbike:scale=?" or is just adding this comment enough of a request?
> 
> I think it’d be a nice addition, but I’m not fully convinced that dirt bike trails with unknown difficulties should be displayed by default to everyone. That said, they do provide a great incentive for mappers to head out, survey them, and retag them properly.

My questions is really: Should I create a new issue to discuss the addition of the "dirtbike:scale=?" or should it be here in this issue.

**Comment by vshcherb** [comment]
Yes please though rendering is limited by a predefined number of options, so additional options should be available by click in future

**Comment by cmoffroad** [comment]
> Yes please though rendering is limited by a predefined number of options, so additional options should be available by click in future

I submitted a proposal to use distinct colors for each dirtbike scale and to include the unknown classification "?" scale, which I believe can now be displayed without the need for custom options.

https://github.com/osmandapp/OsmAnd/issues/21611

Happy holidays!
