### ISSUE TITLE
The displayed router does not match the planned route

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#18752]
### Description

When inserting an intermediate point and changing the router, after clicking Apply, the router previously selected when inserting the point continues to be displayed, but when adding new points, the router does not match the one displayed in the option in the lower left corner of the screen. See video
https://t.me/ruosmand/142380

### Steps to reproduce

Start route planning in pedestrian mode
1. add 6 point
2. select the 3rd point and then the option to insert a point after.
3. click on the change router button, then the next segment button and change the router to the direct line.
4. Add pont and click apply.
5. Add new points

a straight line will be displayed in the left corner, but the route will be built for a pedestrian

### Actual result

the router does not advise the icon in the lower left corner

### Expected result

the router should match the displayed icon in the lower left corner

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:OsmAnd 4.6.8, Дата выпуска: 2023-12-14
Android/iOS version:13
Device model:poco f3
Crash-Logs: ?
```

**Comment by zipav** [comment]
OsmAnd Nightly 4.7.0#1261m, released: 2023-12-21

Reproduced on the latest build of OsmAnd Nightly.

https://github.com/osmandapp/OsmAnd/assets/123936521/e86c28e7-c864-49c3-9ccc-3af9564845f4

**Comment by vshcherb** [comment]
To do: After showed operations, profile should be used "pedestrian" for next segment (after the last point watch to the end of the video) as it shown on icon !
Also double check potential bug: undo/redo doesn't work correctly
