### ISSUE TITLE
The option to clear all in route planning does not work obviously

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#18751]
### Description

After clicking on the clear all item, the route continues to be displayed on the screen if it was drawn in several segments with different types of navigation.  See video:
https://t.me/ruosmand/142379

If there was only one type of navigation, then after applying the option, a line continues to be drawn from the last point of the route until a new point is created. See video:
https://t.me/ruosmand/142378

### Steps to reproduce

1 create a route with multiple segments with different router.
2. click clear all.

### Actual result

Described above.

### Expected result

After clearing, the route should disappear from the screen, and the extra lines too.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd 4.6.8, Дата выпуска: 2023-12-14
Android/iOS version: 13
Device model: poco f3
Crash-Logs: ?
```

**Comment by zipav** [comment]
OsmAnd Nightly 4.7.0#1254m, released: 2023-12-20

Reproduced on the latest build of OsmAnd Nightly.



https://github.com/osmandapp/OsmAnd/assets/123936521/884ea3ab-f76f-457d-acb5-dfe1cc88375c


https://github.com/osmandapp/OsmAnd/assets/123936521/c90fff62-9b22-41d1-9ac5-5ee2c10b2fb9
