### ISSUE TITLE
Replace labels building:type

### ISSUE THREAD

**Issue by franco999** [osmandapp/Osmand#1876]
The "building:type" (poi_building_type_*) label should be replaced by "building", since the former is deprecated and recommend replacement.

(building:type=church → building=church)

http://wiki.openstreetmap.org/wiki/Key:building:type => http://wiki.openstreetmap.org/wiki/Key:building#Civic.2FAmenity

**Comment by xmd5a2** [comment]
I leaf a comment in poi_types.xml: "building:type is internal tag here". It is internally created from "building" tag. In future possibility to add it to a new POI will be removed.
