### ISSUE TITLE
Widgets: More space for text

### ISSUE THREAD

**Issue by betamax256** [osmandapp/OsmAnd#18760]
### Describe the idea (required)

More space for information on top/bottom bar (Osmand 4.6).
Actually, there is enough space to include a third column in the top and bottom bars. But this new available space is poorly distributed.

In this area, the space used by the information modules could easily be reduced and would allow information to be displayed completely
The height of the top/bottom bars could also be easily reduced.

Note that the size of element is "small" (on widget setup) and the font on phone was "big" on setup phone, but the problem is already present after I put "medium font size" on my phone.

Thanks
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/107696645/422b71a6-d854-4a54-a9e4-615e75a5cd18"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by dmpr0** [comment]
Hello! Thank you for the feedback. 
There is no limitation no quantity of columns. You can disable icon in widget settings, it will gave more space for values.

**Comment by betamax256** [comment]
It's a terrible answer !
Why Osmand use most pace on this new feature?
This wastage of space cancels out all new feature advantages.

You know that disabling the icons will reduce the clarity and quality of the information.

If it's to develop like that, you might as well do nothing

NB : If I try to disable icon or change widget size, Osmand crash immediately after I apply change, so change never activated. My phone : Android 11 One plus

**Comment by vshcherb** [comment]
This task is missing details @dmpr0 which we need to put for internal documentation at least:
- What's the minimum font size (text size should gets smaller if it doesn't fit but to certain limit)
- Also icons are not possible scale down (only scale up with screen zoom sys settings).
- Also text is not possible scale down or up by sys settings

Besides that we should target to display **3 small widgets in a row** for 6'' phone in most comfortable way.
P.S. your case probably won't be solved anyway.

**Comment by betamax256** [comment]
Maybe.
Also add an option to disable the title to save vertical space.

![Screenshot_20231222-084553](https://github.com/osmandapp/OsmAnd/assets/107696645/40d100e9-c9c6-41f6-a8b1-6d5edb14a546)

**Comment by dmpr0** [comment]
> This task is missing details @dmpr0 which we need to put for internal documentation at least:
> 
> * What's the minimum font size (text size should gets smaller if it doesn't fit but to certain limit)
> * Also icons are not possible scale down (only scale up with screen zoom sys settings).
> * Also text is not possible scale down or up by sys settings
> 
> Besides that we should target to display **3 small widgets in a row** for 6'' phone in most comfortable way. P.S. your case probably won't be solved anyway.

All details are present in original task.

**Comment by dmpr0** [comment]
> Maybe. Also add an option to disable the title to save vertical space.
> 
> ![Screenshot_20231222-084553](https://private-user-images.githubusercontent.com/107696645/292422587-40d100e9-c9c6-41f6-a8b1-6d5edb14a546.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMzQ1NzQsIm5iZiI6MTcwMzIzNDI3NCwicGF0aCI6Ii8xMDc2OTY2NDUvMjkyNDIyNTg3LTQwZDEwMGU5LWM5YzYtNDFmNi1hOGIxLTZkNWVkYjE0YTU0Ni5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMlQwODM3NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZGFjNWVmM2Q5ZmJkNDdmZjU5YjY5NTk0NzM0YzQ4M2M5ZWJjZDMxMDkyMjc3MDNjMDYyMmYxYTY2MGI5MmJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CtIgp-lmX9dQQsMZovyIM1EMn_ynYVbjyP3FtsVPd64)

It's a terrible proposal! padding is needed.

**Comment by betamax256** [comment]
> > Maybe. Also add an option to disable the title to save vertical space.
> > ![Screenshot_20231222-084553](https://private-user-images.githubusercontent.com/107696645/292422587-40d100e9-c9c6-41f6-a8b1-6d5edb14a546.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMzQ1NzQsIm5iZiI6MTcwMzIzNDI3NCwicGF0aCI6Ii8xMDc2OTY2NDUvMjkyNDIyNTg3LTQwZDEwMGU5LWM5YzYtNDFmNi1hOGIxLTZkNWVkYjE0YTU0Ni5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMlQwODM3NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZGFjNWVmM2Q5ZmJkNDdmZjU5YjY5NTk0NzM0YzQ4M2M5ZWJjZDMxMDkyMjc3MDNjMDYyMmYxYTY2MGI5MmJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CtIgp-lmX9dQQsMZovyIM1EMn_ynYVbjyP3FtsVPd64)
> 
> It's a terrible proposal! padding is needed.

Of course padding is needed ...but not so large. 
Why don't conserve the same padding as widget ?

**Comment by betamax256** [comment]
Here an example of better use of screen space:

Instead of : 
![PS_231127_171638 22](https://github.com/osmandapp/OsmAnd/assets/107696645/7dd90214-0ec2-4e22-abf9-a42beafa2942)

Use : 
![SS_20231222_130935 33](https://github.com/osmandapp/OsmAnd/assets/107696645/0130dbe7-b753-46c3-b46d-f1615a5e5dd1)

**Comment by betamax256** [comment]
> All details are present in original task.
> Default 	Min 	Large
> [...]
> 
>     * Min is broken because of this [Map UI elements are too large on android 14 #18357](https://github.com/osmandapp/OsmAnd/issues/18357)

Thanks for share screenshot.

I see the same strange result on my Android 11 phone :
Using **Default** size, icon & value displayed smaller than using **Min** size, while title size respect the phone setup.

**Comment by betamax256** [comment]
> > This task is missing details @dmpr0 which we need to put for internal documentation at least:
> > 
> > * What's the minimum font size (text size should gets smaller if it doesn't fit but to certain limit)
> > * Also icons are not possible scale down (only scale up with screen zoom sys settings).
> > * Also text is not possible scale down or up by sys settings
> > 
> > Besides that we should target to display **3 small widgets in a row** for 6'' phone in most comfortable way. P.S. your case probably won't be solved anyway.
> 
> All details are present in original task.
> Default 	Min 	Large
> <img alt="" width="300" height="auto" src="https://private-user-images.githubusercontent.com/9365308/292439506-b9d285d5-3586-4ad6-b2e6-178d9fe416e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNTA3NDgsIm5iZiI6MTcwMzI1MDQ0OCwicGF0aCI6Ii85MzY1MzA4LzI5MjQzOTUwNi1iOWQyODVkNS0zNTg2LTRhZDYtYjJlNi0xNzhkOWZlNDE2ZTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjJUMTMwNzI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTYxYzUzZmMwM2YzZDBjMzEwNGUwMGQ1NDFkYWRmOWQ2NTAzOWE0NTMyYzkxZWUwZWVmNGYxY2M4ZjYxMWIxYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JEuLmmMxbomD050--xcp12vCaWJRaA4hUWpN8CSjgrg"> 	<img alt="" width="300" height="auto" src="https://private-user-images.githubusercontent.com/9365308/292439521-8bef1be8-998e-45be-a15f-207cefe6ab88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNTA3NDgsIm5iZiI6MTcwMzI1MDQ0OCwicGF0aCI6Ii85MzY1MzA4LzI5MjQzOTUyMS04YmVmMWJlOC05OThlLTQ1YmUtYTE1Zi0yMDdjZWZlNmFiODgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjJUMTMwNzI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDIyODUyOTRlNzA3Y2NlOWY0MDM3NTQ4YWJkZTY5NTc4MWViNjUwNzkzMDJmMWM2NmQ0OWVlN2Q1NDEyNTIxYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MVjAZQCbt4f2ruu-PQnh4VyLvxEbJpnATQexLi7zIv8"> 	<img alt="" width="300" height="auto" src="https://private-user-images.githubusercontent.com/9365308/292439533-9cf63c8b-9c0f-4c93-8e61-0bc271878d29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNTA3NDgsIm5iZiI6MTcwMzI1MDQ0OCwicGF0aCI6Ii85MzY1MzA4LzI5MjQzOTUzMy05Y2Y2M2M4Yi05YzBmLTRjOTMtOGU2MS0wYmMyNzE4NzhkMjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjJUMTMwNzI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjFiNmExMmY3NmYxYTE1NjVkODg5Y2ZkNzhiYTQzODNmN2Q5YzViNjk2YTMzZmY0MjNlNGMwNzgwZGIzY2NmYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EjHxRFAFwcl8d3ehNgJHw8zmsU9gvsURUcFHIsRjATg">
> 
>     * Min is broken because of this [Map UI elements are too large on android 14 #18357](https://github.com/osmandapp/OsmAnd/issues/18357)

Thanks for share screenshot.

I see the same strange result on my Android 11 phone :
Using Default size, icon & value displayed smaller than using Min size, while title size respect the phone setup.

**Comment by vshcherb** [comment]
This task will be waiting of checking the sizes, details will be pasted here. There are 2 issues related to it.

**Comment by dmpr0** [comment]
> Here an example of better use of screen space:
> 
> Instead of : ![PS_231127_171638 22](https://private-user-images.githubusercontent.com/107696645/292491428-7dd90214-0ec2-4e22-abf9-a42beafa2942.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NjU2NTYsIm5iZiI6MTcwMzY2NTM1NiwicGF0aCI6Ii8xMDc2OTY2NDUvMjkyNDkxNDI4LTdkZDkwMjE0LTBlYzItNGUyMi1hYmY5LWE0MmJlYWZhMjk0Mi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjdUMDgyMjM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGMwYzhkMTVmY2VkNDgzYTRiNzU5ZDA4MDBjZDE5MWEwYjIyMDY3ZDdmNzc4ZmQ3ZDdjODBhZjExM2E4YWU0MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4BIBVuiQVY6zWx0I69lCaUV-OpHwr0Y4BEDUDRzx9p4)
> 
> Use : ![SS_20231222_130935 33](https://private-user-images.githubusercontent.com/107696645/292491481-0130dbe7-b753-46c3-b46d-f1615a5e5dd1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NjU2NTYsIm5iZiI6MTcwMzY2NTM1NiwicGF0aCI6Ii8xMDc2OTY2NDUvMjkyNDkxNDgxLTAxMzBkYmU3LWI3NTMtNDZjMy1iNDZkLWYxNjE1YTVlNWRkMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyN1QwODIyMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjM4MmYzZGFlNzEwN2VmNjQzMjZjOWQ1YzhjMTkwZGM5N2MxNWZmYWE1YTUxMmFkYWI1ZDk5MmUzNTBiNmM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FK8F6dIVnN9Gzdon8jWUorY71eMh8So9GAvnziRj9nQ)

You have demonstrate Small widget size on second picture. Thank you!

**Comment by vshcherb** [comment]
We will double check the sizes and align in 4.7 release, this is issue became very cumbersome as it has lots of conversations and links to other issues still need to be resolved first.

**Comment by betamax256** [comment]
> > Here an example of better use of screen space:
> > Instead of : ![PS_231127_171638 22](https://private-user-images.githubusercontent.com/107696645/292491428-7dd90214-0ec2-4e22-abf9-a42beafa2942.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NjU2NTYsIm5iZiI6MTcwMzY2NTM1NiwicGF0aCI6Ii8xMDc2OTY2NDUvMjkyNDkxNDI4LTdkZDkwMjE0LTBlYzItNGUyMi1hYmY5LWE0MmJlYWZhMjk0Mi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjdUMDgyMjM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGMwYzhkMTVmY2VkNDgzYTRiNzU5ZDA4MDBjZDE5MWEwYjIyMDY3ZDdmNzc4ZmQ3ZDdjODBhZjExM2E4YWU0MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4BIBVuiQVY6zWx0I69lCaUV-OpHwr0Y4BEDUDRzx9p4)
> > Use : ![SS_20231222_130935 33](https://private-user-images.githubusercontent.com/107696645/292491481-0130dbe7-b753-46c3-b46d-f1615a5e5dd1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NjU2NTYsIm5iZiI6MTcwMzY2NTM1NiwicGF0aCI6Ii8xMDc2OTY2NDUvMjkyNDkxNDgxLTAxMzBkYmU3LWI3NTMtNDZjMy1iNDZkLWYxNjE1YTVlNWRkMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyN1QwODIyMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjM4MmYzZGFlNzEwN2VmNjQzMjZjOWQ1YzhjMTkwZGM5N2MxNWZmYWE1YTUxMmFkYWI1ZDk5MmUzNTBiNmM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FK8F6dIVnN9Gzdon8jWUorY71eMh8So9GAvnziRj9nQ)
> 
> You have demonstrate Small widget size on second picture. Thank you!

Absolutely not.

For the same information, the new feature use more screen space but values are croped !!!!
**Is it clear now that the new rows feature have a fucking design ?** :
![Screenshot_20231227-112942](https://github.com/osmandapp/OsmAnd/assets/107696645/b92a3a76-20a6-4c2a-bea3-8c17a682e05b)
