### ISSUE TITLE
Round up numbers in navigation widgets

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#18762]
As many navigation applications don't display ```1183 m to the next turn``` we should use formatting as well to have it easier / faster to read. 

Formatting rules ( https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd-java/src/main/java/net/osmand/util/Algorithms.java#L1429) - generate10BaseRoundingBounds(100, 5):
```
upper    lower    example    format    comment
  none   10000          12643        12 km  round to lower full kilometer
  9999     1000             3672      3.6 km  round to lower hundred meters, format kilometers
    999       300               462    400 m    round to lower hundred meters
    299        100                184     150 m    round to lower fifty meters
      99          40                 57       40 m     round to lower twenty meters
      39            0                  18        10 m     round to lower ten meters
```

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/pull/18773

**Comment by vshcherb** [comment]
Done: Settings updates all widgets DistanceToPointWidget, NextTurn Widgets, Lanes widgets, NavigationNotification (Voice was already rounded before) - it's controllable by setting to round or not

**Comment by vshcherb** [comment]
Design is neeeded

**Comment by dmpr0** [comment]
![Screenshot 2024-02-01 at 10 41 42](https://github.com/osmandapp/OsmAnd/assets/9365308/88550ad4-a434-4ecb-a32d-97a5c5f4e4c2)

**Comment by dmpr0** [comment]
# Review 
- [ ] Use `divider_color_light/dark` for divider in bottom sheet
