### ISSUE TITLE
Hide Water in Osmand Style

### ISSUE THREAD

**Issue by mariush444** [osmandapp/OsmAnd#18775]
### Describe the idea (required)

There is option in Osmand style - Hide Water
It seems that the option hides oceans and seas only.

### Tell us about the expected behaviour (required)

I'm not sure if the intention was to hide oceans and seas only but in my opinion it would be great to hide other waters (streams, rivers and lakes) too.

### Tell us about alternatives you've considered (required)

I can't find any alternatives but without this possibility some places are "not readable"
27.34965 41.38616

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/66887280/ebec1dc0-5ebb-4946-bd99-aecd9d993d38"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by zipav** [comment]
OsmAnd Nightly 4.7.0#1254m, released: 2023-12-20

After enabling the "Hide Water" option, it is still displayed.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/e3504747-5ce9-4e4f-8b12-2434ed4fc5fa"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by mariush444** [comment]
I created new render based on topo. you can test it.
[topoWater.render.zip](https://github.com/osmandapp/OsmAnd/files/13789095/topoWater.render.zip)
