### ISSUE TITLE
'Reset to default' in widget panel affects all panels

### ISSUE THREAD

**Issue by mikehgentry** [osmandapp/OsmAnd#18779]
### Description

I'm pretty sure it used to only affect the current panel, and it's not what I'd expect it to do.

### Steps to reproduce

Go into a specific panel in 'Configure screen'. Choose 'Reset to default'. The menu will say "\<Panel name\> Reset all settings to default?"

Hitting 'Reset' resets *all* panels.

### Actual result

All panels are reset

### Expected result

Currently selected panel is reset

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: + 4.6.8
Android/iOS version: 11
Device model: Xcover 4s
Crash-Logs: ?
```

**Comment by mikehgentry** [comment]
So, the behaviour isn't necessarily buggy, but I think the behaviour *with* the text is.

The menu stating the panel name strongly implies that the action applies only to that panel. You could get rid of the panel name in the menu, which perhaps isn't ideal because it'd leave it ambiguous. Better would be to make it only apply to that panel, or change the text to say something like "Reset all panels to default?"

**Comment by vshcherb** [comment]
To do: reset should affect only the widget panel it was related to

**Comment by dmpr0** [comment]
# Review
- [ ] Reset to default doesn't apply for similar widgets. If Right panel by default has Speed limit widget, adding new and then Reseting to default, doesn't remove copy of the widget.
