### ISSUE TITLE
Invalid redirecting from osmand.net to wikivoyage

### ISSUE THREAD

**Issue by nnngrach** [osmandapp/OsmAnd#18771]
**Steps to reproduse:**
Open in device any non-english wikivoyage article.
Click share and copy link. 
https://osmand.net/travel?title=%D0%99%D0%BE%D1%88%D0%BA%D0%B0%D1%80-%D0%9E%D0%BB%D0%B0&lang=ru

After opening link in browser all percent-encoded symbols replaces to "?" symbols.
https://ru.wikivoyage.org/wiki/??????-???

**Expectation:**
redirection to this article
https://ru.wikivoyage.org/wiki/%D0%99%D0%BE%D1%88%D0%BA%D0%B0%D1%80-%D0%9E%D0%BB%D0%B0

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-tools/assets/35684515/0c1d058c-377d-4d24-9330-2ca13f3895f1"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-tools/assets/35684515/9ab4d249-3edf-4048-ab9b-322a199a1ec6"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-tools/assets/35684515/eae50707-53da-4bbd-8987-c327b450e92f"  width="300" height="auto"/> </td>
  </tr>
</table>

 <table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-tools/assets/35684515/6f88dfc2-f52c-40a4-95f8-bef24ccc32c2"  width="500" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-tools/assets/35684515/0a08fc9c-ceeb-4359-b757-775b7913496c"  width="500" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
Duplicate to https://github.com/osmandapp/OsmAnd-Issues/issues/2337 (or related)

**Comment by alisa911** [comment]
All ok with the title https://github.com/osmandapp/OsmAnd-misc/blob/5d09817a49c6d56753cea4dd5169771ebbdc7132/config/nginx-main/server-static-include.conf#L27

nginx isn't support utf-8?

**Comment by RZR-UA** [comment]
Fixed. The problem was located in Java @RequestMapping(path = {"travel"})
