### ISSUE TITLE
Make PENALTY_FOR_REVERSE_DIRECTION profile dependent and configurable in routing.xml

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#18788]
- [x] DEFAULT_PENALTY_FOR_REVERSE_DIRECTION - 500 seconds which is too much for cycling / pedestrian (which should be probably ~ 10-20 or 0)
- [x] **Partially** (merged to routingHHBase) Fix for C++ as well
- [x]  Check / think about intermediate points (probably PENALTY_FOR_REVERSE_DIRECTION / 2 still makes sense)
- [x]  Test about Plan Route where it shouldn't be used

**Comment by vshcherb** [comment]
С++ needed

**Comment by yuriiurshuliak** [comment]
The route is built correct, proceeding directly towards the red endpoint without any looping involved.

https://github.com/osmandapp/OsmAnd/assets/127092082/74dbcb43-069c-43ab-be27-36d2b653aab8
