### ISSUE TITLE
POI editor, advanced tab: invisible 'Clear all' button

### ISSUE THREAD

**Issue by mhastu** [osmandapp/OsmAnd#18795]
### Description

When clicking inside far-right a value field in the "advanced" tab of the POI editor, the value is deleted (the invisible x is clicked). This is confusing behavior.

### Steps to reproduce

Open the POI editor, click "advanced" try to edit a value by clicking far-right inside the value field.

### Actual result

The value is deleted.

### Expected result

Two possible fixes:
- The value is not deleted when the x to delete a value is not displayed
- The x to delete a value is always displayed, indicating that a click on it will delete the value.

### Your Environment (required)

```
OsmAnd Version: 4.5.10
Android/iOS version: 12
Device model: FP4
```

**Comment by scaidermern** [comment]
Can be reproduced with OsmAnd 4.6.8.
The "x" in the value field is only visible _after_ tapping inside the field. However, it is _always_ present (just invisible) and can be activated when tapping at the end of a value field, deleting the value text.

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. Here are the steps to reproduce:

- Find any POI
- Click on it and choose Actions - Modify POI
- Then, select the Advanced tab
- Look for the final field with a name and click on the far right end of this field.
- The content will disappear without showing a closing 'X'.

In other words, clicking on the bottom right corner of the last line deletes the text. This might happen accidentally as the 'X' only appears when the field is in edit mode.

OsmAnd~ 4.7.0#1264m, released: 2023-12-22

https://github.com/osmandapp/OsmAnd/assets/127092082/79dcca54-56e2-4210-b3ec-43210c779ae2

**Comment by dmpr0** [comment]
## ToDo
- [ ] Disable touches on invisible buttons. Clear all button is visible and works only when Text field is in focus.

**Comment by dmpr0** [comment]
# Review
- [ ] Read ToDo
