### ISSUE TITLE
Set default sorting as Country > Region in Local maps

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#18803]
### Description

before regions were sorted by "country>region". Now again you went back to "region>country". 
Whats the benefit of it?
Anyway not an "easier data management" as advertised... This way it´s confusing, countries/regions are mixed up.

A few weeks ago it was a bug (#18257) - now it´s a feature?

### Steps to reproduce

have a look at it.

### Actual result

mixed up.

### Expected result

sorted as before "country>region"

### Your Environment (required)

OsmAnd Version: +4.6.9

**Comment by vshcherb** [comment]
To do: Set default sorting as Country > Region in Local maps

**Comment by Rowin63** [comment]
Issue was "closed as completed" three weeks ago but still (or again?) the sorting is region > country 
(+4.6.13 and ~4.7.0#1395)

**Comment by yuriiurshuliak** [comment]
I'm not experiencing any issues on my end. Could you provide more details about the problem you're encountering? Are you using the default sorting option?

Also try reinstalling the app. Reinstallation should clear any incorrect data in the app. Before reinstalling, please back up all your personal data such as tracks and favorites. You can do this by going to Menu > Settings > Export to file.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/993e1673-be04-43cf-81ee-9f743b5a5cfc"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/841128ff-4bd0-47ce-9ed0-6ea6484fd305"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Rowin63** [comment]
This is the details I can provide.
First region, then country. So all regions of one country are spread all over the list.



![Screenshot_20240122_184839_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/95540936/a09dfc0b-096e-42c2-8940-3fb9cb023773)
![Screenshot_20240122_184900_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/95540936/b670e326-f5a8-4e28-b3b6-6fff0b488de2)

**Comment by Rowin63** [comment]
My fault, I didn´t see there are TWO DIFFERENT sortings "A-Z":
"A-Z" by "name" and 
"A-Z" by "countryname"

Whats the benefit of this two options?
Why should one sort maps by "name" (regions) and mix up all entries to a confusing - with countries spread all over it - list?
