### ISSUE TITLE
Public transport routing broken (Bangkok)

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/OsmAnd#18809]
### Description

Public transport routing looks broken in OsmAnd. Here in Bangkok MRT subway is never considered. As I have been at Bangkok in 2018 it worked properly.
Seems to be no OSM issue. Works fine with Organic Maps.

Try to calculate a public transport route...
from: 13.72463, 100.5472375
to: 13.98198, 100.62086

Result OsmAnd:
No route found
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/6921696/d84065d7-a8cd-433b-8b83-6bde9da00e19"  width="300" height="auto"/> </td>
  </tr>
</table>

Result Organic Maps:
Good route found
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/6921696/c71af901-100b-4071-aeb2-c66f033fdbb5"  width="300" height="auto"/> </td>
  </tr>
</table>

Bug found with OsmAnd~ 4.5.10

### Steps to reproduce

See above

### Actual result

See above

### Expected result

See above

### Your Environment (required)

Android

**Comment by Norbert80** [comment]
Another set of example coordinates.

Try to calculate a public transport route...
from: 13.72463, 100.5472375
to: 13.710555, 100.60275

Result OsmAnd:
A bad route without MRT (subway) is calculated
![grafik](https://github.com/osmandapp/OsmAnd/assets/6921696/9dbc412c-daa2-475a-8594-1191cc807cba)
Additional info: It is completely broken. If i only turn off subway it does not find a at route at all. Neither with bus nor tram nor combinations.

Result Organic Maps:
A good route including MRT (subway) is calculated

Google Maps gives same good result as Organic Maps:
![Uploading grafik.png…]()

![grafik](https://github.com/osmandapp/OsmAnd/assets/6921696/8c7afdfb-4b19-471e-b9db-6e161b3d5181)

**Comment by DmitryAlexei** [comment]
OsmAnd 4.6.9

Steps to reproduce:
- build a route in *Public transport* profile using provided coordinates:
from: 13.72463, 100.5472375
to: 13.98198, 100.62086
- in navigation settings > route parameters try to change *Number of changes* to 1, 2, 3, 4

Actual result:
- route for these coordinates is not calculated, no matter how many changes have you specified in Route parameters
- in other profiles (e.g. on foot, driving), a route can be calculated for these coordinates. A route can also be calculated in Public transport profile for other locations
- the route can also be calculated in other apps, that use OSM data
- see screenshot

Expected result:
- route (or routes) can be calculated for specified coordinates

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/19ee37d1-5d38-40cc-8381-d325265b5198"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
We need to check if it's a regression

**Comment by ivanPyrohivskyi** [comment]
@xmd5a2 check regression before/after https://github.com/osmandapp/OsmAnd/issues/17530

**Comment by xmd5a2** [comment]
**OsmAnd 4.1.1 2021-12-15:**
6 PT routes was calculated
![Screenshot_2024-01-10-11-14-38-477_net osmand](https://github.com/osmandapp/OsmAnd/assets/5829014/0c2ed316-bfda-4884-8198-b2cb37c791bd)

**OsmAnd 4.7.0 2023-12-28:**
No PT routes found
![Screenshot_2024-01-10-11-22-23-804_net osmand plus](https://github.com/osmandapp/OsmAnd/assets/5829014/fa188a72-e747-4c5a-baa4-61fe71a02b60)

Map is the same. Obviously this is a regression.

**Comment by ivanPyrohivskyi** [comment]
Technical plan:
1. Investigate TransportRoutePlanner.java (see [request](https://github.com/osmandapp/OsmAnd/pull/18581))
2. Add logging like:
LATITUDE,LONGITUTE
123,123
123,123
LATITUDE,LONGITUTE
123,123
3. Save result of logging to *.csv file (manually) and visualize on https://www.gpsvisualizer.com/
4. After investigating suggest decision of the problem.

**Comment by RZR-UA** [comment]
> Another set of example coordinates.
> Try to calculate a public transport route... from: 13.72463, 100.5472375 to: 13.710555, 100.60275
> 
> Result OsmAnd: A bad route **without** MRT (subway) is calculated

Both cases happen due to the incomplete data.

Fix for public_transport=station generation is proposed.

This is actually only a part of problem, because 1st coordinates still failed (even with the data).

The route on 2nd coordinates seems fixed:

![fix2](https://github.com/osmandapp/OsmAnd/assets/90444451/54023abe-3377-4947-bd3e-8def1d7b4541)

**Comment by RZR-UA** [comment]
Overpass Turbo query to highlight "lost" stations in Bangkok:

https://overpass-turbo.eu/s/1GAf

**Comment by RZR-UA** [comment]
Finally:

1. Issue with broken routing happened due to the incorrect mapping. The role of 43 stations in Bangkok is not defined. Please use overpass query to check the list of broken stations: https://overpass-turbo.eu/s/1GBJ (I've checked this query on many locations in the US, UK, Europe, even on the while Thailand -- and I've found that only 43 stations in Bangkok are affected).

2. The first route (with finish nearby the Airport) is failed due to an overdistance between the finish point and the nearest public station (<1500m). Proposal is to increase walkRadius from 1500m to 3000m for public_transport.

**Comment by RZR-UA** [comment]
First route with data and walkRadius increased:

![photo_2024-01-29_21-42-41](https://github.com/osmandapp/OsmAnd/assets/90444451/bdf499cf-4912-4235-8cf3-ada84b313211)

![photo_2024-01-29_21-42-49](https://github.com/osmandapp/OsmAnd/assets/90444451/1acb5743-5626-4ac0-b0e2-87a3897a357a)

**Comment by vshcherb** [comment]
We found that Bangkok subway is not a standard mapping: https://www.openstreetmap.org/relation/444659

For most of the stops there is no role "platform" or "stop". Documentation proposes to have these roles, however "station" by documentation is not specific platform or stop, it's a collection of platforms and stops. So implementing it rather confusing.

I think the algorithm will be very cumbersome so changing mapping data is easier. Draft pull request could have other potential side effects https://github.com/osmandapp/OsmAnd-tools/pull/751

Query that shows that there is a problem only within Bangkok: [overpass link](https://overpass-turbo.eu/?q=W2Jib3g6e3vEgcSDfX1dOwoKbm9kZVsicHVibGljX3RyYW5zcG9ydCI9InN0YXRpb24iXS0-LsSpxKvErcSgxI1yZWwoYm7EtMSqxKzErnMpxJTElsSYxJrEnMSexKDEosSkxKbEqHRvcF9hxLphxLDEsi7FlWVhc193aXRoX8S1xYJuxI3Ej8SRxJPElcSXxJnEm8SdxJ_EocSjxKXEp8SpxZJfxKJzxaHEt8WYxLPFucW7xYPEucS7xL3Ev8W_xabFhMWGxa3FicWwxYzFs8WPxbbFk8WbxZfEscSzxpLFnsWgxaLFuG_FusaHxajEkMSSxonFiMWvxYvFssWOxKdwbMSrZsSjbcW9LsaoxqrGrF_Gn2VzxoLEvMS-xq_GqXTGq3JtxrPFqsaIxazGosWKxbHFjcW0xZDFt8aSxq7GlsWfxaHFo8awxrzGssa0xrbEjndhecahxa7HhcaNxqbElca7xr3GrcaUxrrGsca-xZ_HmMeVxLrGuHfHpMeSx6bHl3nHgsWHx5vGjMalx4jGkMWUxZbHjMWWxpfHj8W4x6DGssewx5UKKAoJxZrHvMeOxpnGhsS3x5UgyIfHjcaYx5DIgMemx5TEjciQyInIkse_x6XGv8iCxI0pxZnHjWdvxJHFqCjIiMWcx73GmcWlxLc7IC0gyKjFnV_Io8ilyKDGlciJYmFkyK4vLyBTRVQgT0YgIkJBRCLJgFRPUF9BUkVBU8SOxrQocsiyxZ7IumTFhceDx7TGpMeHxo_FgcW8x6PHlF_Jnci9yL_JgcmDyYXJh8mJyYsgTk9ERcmWyITIhseqxoQuyajJncmfx7PGi8mixbM6dmVyxbrErsWPMsSwyJfJu8a5yb7Iu8mfdHlwZcWPcm91dMqXxIwKyLfGr8WbbnTJnMi7xp7FqsmZyqHEusqjyqVkOseJcCLKoMmoyLXIvCDIvsmAyYLJhMmGIkdPybXJjMm0ybZTICjIkiDGkC3KmWxlKcSOyKfKkcq2yLDJvceByLTIpMi8yqBmaW5hbMmrIEZJTkFMIMmTU1VMVMSOLsuay5zLnsSOypp0IGdlb23EjQ&c=By1qLuVVrL&R=)
