### ISSUE TITLE
Rendering: map distortion near +/-180 east/west

### ISSUE THREAD

**Issue by RicoZ-OSM** [osmandapp/Osmand#1880]
When scrolling the map towards +/-180 from east or west map will be distorted as soon as the date line gets into view, the islands in view will jump around.

When panning across the date line the map on both sides is squeezed together and an empty area seen where the dateline would be expected.

**Comment by vshcherb** [comment]
Squeezing issue was fixed in 2.3 release, unfortunately displaying 2 parts of the map is an issue for current rendering engine. So geometry is now fine, but it is possible to see only 1 half of the sphere.

**Comment by RicoZ-OSM** [comment]
Who will be the brave man to test OsmAnd on Taveuni? Travelguides have many stories about GPS going mad at this place.

https://commons.wikimedia.org/wiki/File:TodayYesterday.jpg?uselang=en

**Comment by sonora** [comment]
I suggest let's pursue via #1968.
