### ISSUE TITLE
HHRoutePlanner Create C++ version

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#18815]
HHRoutePlanner Run v1 C++
Follow up https://github.com/osmandapp/OsmAnd/issues/18512

**Comment by ivanPyrohivskyi** [comment]
Already did:
- [ ] Transfer code for HH routing from Java to C++ (core-legacy)
- [ ] Debug of reading OBF files for routing
- [ ] Debug routing with one maps

What need to do:
- [ ] Debug routing with several maps
- [ ] Debug alternative routes
- [ ] Debug different profiles
- [ ] Intermediate points
- [ ] Memory leaks
- [ ] lseek function in OBF reading
- [ ] Tests
- [ ] iOS, Android, Map Creator C++ libraries
