### ISSUE TITLE
Photos kept on the device after deleted via OsmAnd

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#1881]
I take photos via the Audio/Video notes plugin in OsmAnd. Then I delete them from inside OsmAnd. But they are still on the phone and accessible via the Gallery and I have to delete them again from there (where they are mixed with normal photos taken by Camera app). The plugin is set to use the system Camera app. I think this started with v2.1 and is still happening in nightlies.

**Comment by vshcherb** [comment]
We are planning to improve non Camera app photo camera, but for the system Camera app it is outside of OsmAnd responsibility. So OsmAnd doesn't have access to control that.

**Comment by aceman444** [comment]
My photos are also stored on the SD card so in Android 4.4 OsmAnd can't even delete the file from the filesystem if it wanted to. Maybe my problem started when I moved to Android 4.4.

OK, maybe you could mention the fact directly in the settings, that OsmAnd does not manage the photos if system app is chosen.
