### ISSUE TITLE
Smart route recalculation skips Highway directions

### ISSUE THREAD

**Issue by Guylby** [osmandapp/OsmAnd#18824]
### Description

I've used Osmand Offline routing for two long trips (>500kms) during the holidays and got an issue that occured at least three times: 
When the app had to reroute (1 time in a city when a road was closed, 2 times when I took a break at a highway stop), the routing was succesful, the route was shown on the map correctly, but the 4-5 next directions were skipped, neither shown on the Navigational Widget (the 6th direction was displayed) or narrated by Voice prompt. 

### Steps to reproduce

The issue should be reproduceable as it happened three times in similar conditions but I don't know how to spoof a gps position to trigger a reroute:
Calculate a long route on highways with distant turns (at least 50kms between turns).
Travel along the route, and with at least 25kms still remaining up to the next turn, trigger a reroute. For example, exit the highway on a truck stop. The reroute will get you back on the same highway with identical pathing.
The next directions should be skipped in the Navigational Widgets and voice prompts. 

### Actual result

This is a description of the three times directions were skipped in my case:
I first left the city and got on a highway after a reroute, and the voice prompt and directions told "Keep straight for 450kms", when there was multiple highway interchange in between (3-4 different turns and highway changes, one at 150kms, 200kms and others). I had to manually stop routing and recalculate the route to have the missing directions back. 

Then it happened again, as I left the highway for a short break in a rest area, rerouting was succesful but again the 3-4 next directions were skipped (one highway interchange, then the highway exit and some turns). Before rerouting, the next turn was 35kms away, but then after the reroute the next turn was another one, 72kms away).

On the way back, through a different route, it happened another time, when taking a break in a highway service area. Reroute happened succesfully, but the next direction were skipped. The direction to get back on the highway was shown, but after that, the direction 35kms away to take the exit, and some turns after that were not shown on the widget or told by voice. The route was correct on the map (I had to manually check the map to not miss the exit), and the Voice and Alert Widget told the presence of the toll area at the exit, but no directions. 
I didn't restart the routing this time, and directions resumed as normal once I arrived at the 6th one after rerouting and everything worked as normal until the end of the trip. 
I stopped in a small village and rerouting did not skip directions this time. The next turn was only a kilometer away. 

It was almost like Osmand skipped the next few directions, then got back to normal. 
- Each time this bug occured, the next node or first direction change was at least 25kms away and on a highway (either highway interchange or highway exit). 
- The recalculted route was identical as the one before the reroute, and done under the same Offline Osmand standard car profile, or one modified with just the Heuristic Coefficient changed to 1.3 . 
- Smart route recalculation was on 
- Routing was from My Position to a Map Marker, with an Intermediate Waypoint that was already passed each time the bug occured. 

### Expected result

Directions are not skipped when rerouting. 

### Your Environment (required)

```
OsmAnd Version: 4.6.9
Android/iOS version: Android 13
Device model: Sony Xperia 10 III
```

**Comment by yuriiurshuliak** [comment]
We need to clarify the specific start and finish coordinates used during your initial trips where the problem occurred. So that we can reproduce the problem.

**Comment by Guylby** [comment]
I've managed to reproduce the issue by simulating my position along a gps track. I'm joining it below as a .zip file:
[Wed 27 Dec 2023.zip](https://github.com/osmandapp/OsmAnd/files/13777489/Wed.27.Dec.2023.zip)

Here is a screen recording of the issue being reproduced:
https://github.com/osmandapp/OsmAnd/assets/151167525/933f51ea-8e4a-4dc2-a251-ebd83697b223

- I first put my fake position on the map by loading the linked above gpx track and stopping it before it starts following along. Then - I start the routing from My Position to a Map Marker "retour suisse" (coordinates 43.56501°N, 6.00995° E). Routing is calculated and I start the navigation. I show the next directions, and you can see the highway exit turn at 33,7kms ("Serrez a droite A51 Echangeur de Manosque"), then the Keep right at 34,2kms ("Serrez a droite Echangeur de Manosque") and the 4th instruction is the "Giratoire : prenez la sortie 1 ...".
- I restart the simulated gps position with the gpx track. Directions are unchanged as there is no rerouting. 
- I show the turn instructions again, they are not changed.
- The simulated gps position goes to the highway stop, triggering a reroute. New turn instructions are provided to get back on the highway.
- Another reroute is triggered in the stop area, and the directions to get back on the highway and take the highway exit disappear.
I show the new turn instructions which are now missing the one to get back on the highway, then the Exit turn and Keep right that were displayed before. The 4th direction from before is now the 1st one.
Also, all roundabout turns changed to "prenez la sortie 1" (take first exit), when before it was 1st exit, then 2nd, then 1st. 

Screengrab of the first instructions provided:
![First instructions](https://github.com/osmandapp/OsmAnd/assets/151167525/9c2cae9c-4f68-4d23-8eb9-7e13a66f3228)
Screengrab of the instructions provided after rerouting: Directions are the same, but now all roundabout exit are stated as 1 when they were not before.
![Second instructions](https://github.com/osmandapp/OsmAnd/assets/151167525/c2f041af-ae1c-4728-8fd5-f9f0882378bd)

**Comment by Guylby** [comment]
Through testing I've found a workaround:

By adding an intermediary waypoint before the last highway exit, directions will not be skipped after rerouting. 
However, the route recalculation, even with Smart Route Recalculation ON, seems to recalculate the complete route up to the intermediate waypoint, which can be quite slow for long trip. 
Adding waypoints along the highway can speed up reroute but is cumbersome. 

It's almost like rerouting sees the whole highway section as a single segment regardless of interchanges.

**Comment by Guylby** [comment]
I've continued to tinker to find a solution and the problem seems to come from the Smart Route Recalculation option. You can't turn it off through the UI (the toggle does nothing, I'll open a separate issue here:) but by manually editing the routing xml and setting the "recalculateDistanceHelp" to 50kms for example and redoing the steps above of simulating a reroute, you can see that the highway directions are all skipped after 50kms:

Normal turn intrusctions before reroute:
<img src="https://github.com/osmandapp/OsmAnd/assets/151167525/a578818c-17fb-4f92-9671-3e4f39babf46" width="500" />

Skipped directions after 50kms after reroute:
<img src="https://github.com/osmandapp/OsmAnd/assets/151167525/bfe19053-1fc6-4abd-9a3b-b5da7ad07693" width="500" />

It seems that roundabout turn directions and highway directions are bugged after the distance set as "recalculateDistanceHelp" in the routing xml profile.

**Comment by Guylby** [comment]
As of Osmand beta 4.7.1, this issue seems to have been fixed with the "Special Routing" enabled. In the same scenarios as above, even with a route recalculation and Smart Route Recalculation turned On, accurate directions are given even on the highway after a reroute. 

While I could still reproduce the issue normal routing, this is not a problem anymore with "Special routing". 

Thanks a lot for your work!

**Comment by vshcherb** [comment]
Special routing doesn't have need Smart Route Recalculation to produce fast enough recalculations,  so I think we will close this issue. As we're moving to make HH Routing (Special) default
