### ISSUE TITLE
CRASH when opening tracks folder

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#18828]
### Description

When opening tracks folder i get a crash or sometimes freezing, then only the first lines (subfolders) are shown.

### Steps to reproduce

NO crash with older version
OsmAnd~ 4.7.0#1268m, veröffentlicht: 2023-12-24

### Actual result

Crash

### Expected result

No crash

### Your Environment (required)

OsmAnd Version: OsmAnd~ 4.7.0#1281m, veröffentlicht: 2023-12-27

Android version: 12
Device model: Samsung S10
Crash-Logs: 
[exception.log.zip](https://github.com/osmandapp/OsmAnd/files/13777504/exception.log.zip)

**Comment by Rowin63** [comment]
Same here on my S20+ (crash).
crashlog was sent to your support-mail.

**Comment by vshcherb** [comment]
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:860)
	at net.osmand.plus.track.data.TrackFolder.getFlattenedSubFolders(TrackFolder.java:108)
	at net.osmand.plus.track.data.TrackFolder.getFlattenedSubFolders(TrackFolder.java:109)
```
Just fixed yesterday
