### ISSUE TITLE
Link to install app and open a location

### ISSUE THREAD

**Issue by contrapunctus-1** [osmandapp/OsmAnd#18825]
I'm working on some OSM promotional material, which requires a link (shared as a QR code) which -
1. Installs OsmAnd on the user's device
2. Opens a specific location in OsmAnd

I attempted to use osmand.net/map/ links, but they have some crucial disadvantages -
1. The linked page doesn't provide a button to install OsmAnd. Even if an install link were provided...
2. ...the linked OsmAnd web page shows the location in the form of (less-appealing) raster tiles, which would defeat the intention of showcasing a location on OsmAnd's vector renderer (and to get them to install and maybe use OsmAnd). Having seen the raster tiles, people would be less likely to actually progress to installing OsmAnd to see the location.

This could be remedied in one of two ways -
1. (Probably way too much work) OsmAnd could add support for vector or 3D rendering in the web version (on par with its offline renderer), OR
2. Support for a link which, when opened, would install OsmAnd from any available app store (including F-Droid), and open the linked location.

**Comment by contrapunctus-1** [comment]
The equivalent issue in the Organic Maps repository contains valuable information on the subject.
https://github.com/organicmaps/organicmaps/issues/6978

**Comment by vshcherb** [comment]
Well we need to suggest to install OsmAnd once it's firstly open and we need to do it on website

**Comment by dmpr0** [comment]
## Description 
We need to add banner that should promote native apps for Android and iOS, when user open Osmand.net/map on mobile device. Apple do this automaticly on Safari 

<details>
    <summary>Safari on iOS</summary>
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-Issues/assets/9365308/937aaad7-f567-440b-bf45-7cfbbf9d8e32"  width="300" height="auto"/> </td>
  </tr>
</table>   
</details>  

## ToDo
Add banner to promote mobile version.
* Investigate https://developer.chrome.com/blog/app-install-banners-native/

- [ ] Banner for Android devices 
- [ ] Banner for iOS devices 
- - [ ] Should be disabled if browers is Safari?
