### ISSUE TITLE
OSMAnd crashes after start since update 4.5 and now also on 4.6

### ISSUE THREAD

**Issue by DesperateUser-gz2023** [osmandapp/OsmAnd#18831]
### Description

Since the last update to OSMAnd+ 4.6 OSMAnd crashes after start (briefly part of the UI is shown) without any error message. Si no access to the app is possible, in order to try things like cashe-delete or settings or others. De-Installation and new installation: same problem. This is on a Motorola g6 with Android 9. The same OSMAnd+ version works on my other devices (Lenovo Tablet with Android 6, Lenovo Tablet with Android 9, Xiamoi Redmi Note 11S with Android 13).
I did try to install the Nightly Build apk, but after showing "installing" the phone reports the error "can not install the app". (Permissions are set correctly and I can install other apks).
I did install now the version OSMAnd+ 4.4.7 again via apk and this works without problems.

The problem already appeared back in July with OSMAnd 4.5 and as all the above steps did not work at that time either, I rolled back to version 4.4.7 at that time already. Nevertheless this is not a solution, as I want the same version on all my devices.

### Steps to reproduce

start the app on same hardware

### Actual result

OSMAnd+ crashes after briefly showing part of the UI screen without error message.

### Expected result

OSMAnd+ running properly

### Your Environment (required)

OsmAnd Version: 4.6
Android/iOS version: 9
Device model:Motorola g6
Crash-Logs:  this is empty, I checked it on the device
```

**Comment by yuriiurshuliak** [comment]
Since the app functions on various devices running different Android versions, it could be valuable to explore whether there's a specific compatibility problem between OsmAnd and your particular device. To assist us in understanding the issue better, kindly forward the crash log file. When the app crashes, access Menu > Help > Send crash log file. Additionally, if possible, please include a screen recording demonstrating the actions leading up to the app crash.

**Comment by DesperateUser-gz2023** [comment]
Hi, as I wrote.... the app does not open at all, so no "Menu > Help > Send crash log file". Could you tell me, in which folder I could find it? So I could pick it up manually.

**Comment by vshcherb** [comment]
Did you try full reinstall? If the app keeps crashing then only thing you can do try to revert to older version, do backup and then do clean installation

**Comment by DesperateUser-gz2023** [comment]
What to you mean with „do backup and then do clean“?

You mean first install an older version (yes, 4.4.7 works, I did that already) and then uninstall and try actual version again? 

Sorry, I don’t get it

 

Von: vshcherb ***@***.*** 
Gesendet: Donnerstag, 28. Dezember 2023 14:54
An: osmandapp/OsmAnd ***@***.***>
Cc: DesperateUser-gz2023 ***@***.***>; State change ***@***.***>
Betreff: Re: [osmandapp/OsmAnd] OSMAnd crashes after start since update 4.5 and now also on 4.6 (Issue #18831)

 

Did you try full reinstall? If the app keeps crashing then only thing you can do try to revert to older version, do backup and then do clean installation

**Comment by vshcherb** [comment]
> You mean first install an older version (yes, 4.4.7 works, I did that already) and then uninstall and try actual version again

Yes

**Comment by DesperateUser-gz2023** [comment]
So: 
#2 version 4.4.7 which is running on the device; I uninstalled it.
#3 I installed the actual version of OSMAnd+ from the Google Play Store
#4 Result is that Version 4.6.11 is installed on the device
#5 I start the app and get the welcome screen which indicates searching for maps
#6 While in this process the app crashes with the message "OsmAnd+ repeatedly ended".
If I skip  in #5 the map download the same error message pops up.

![Screenshot_3](https://github.com/osmandapp/OsmAnd/assets/154995669/16e75ac7-468f-4a4f-846e-ff09d33deaad)
![Screenshot_4](https://github.com/osmandapp/OsmAnd/assets/154995669/c11b41a6-92e9-435a-b368-534eb59082f7)
![Screenshot_5](https://github.com/osmandapp/OsmAnd/assets/154995669/bf5ebffe-f6c7-4add-a7ae-a5ec1110cbce)
![Screenshot_6](https://github.com/osmandapp/OsmAnd/assets/154995669/b18ee47f-f081-4fed-9fdc-8939d286d5b1)
![Screenshot_2](https://github.com/osmandapp/OsmAnd/assets/154995669/05a80a01-e6af-4e45-bc0a-50b080843f65)

**Comment by yuriiurshuliak** [comment]
In this case, we need to check your tombstone files.

To export the tombstone files, you must first create a bug report using Android system settings:

- Activate Developer options by tapping Build number seven times in Software information. (Go to Settings → About phone → Software information
- Go to Developer options, choose Take bug report, select report type, and report it.
- Download the report, extract tombstone files, and send to crash@osmand.net for OsmAnd developers.

See: https://osmand.net/docs/user/troubleshooting/crash-logs#send-tombstone-files-android-only
