### ISSUE TITLE
Android Auto displays a black screen instead of presenting the map

### ISSUE THREAD

**Issue by Bubba0875** [osmandapp/OsmAnd#18835]
### Description

Good morning, I can't connect or rather Osmand connects to Android Auto, but it doesn't read the maps and I can't use it as shown in the video

Buongiorno, non riesco a collegare o meglio osmand si collega ad Android auto, però non legge le mappe e non riesco ad usarlo come da video

https://github.com/osmandapp/OsmAnd/assets/155012440/ea383aaf-b7b0-40e9-a92d-16a4bea926fd

### Steps to reproduce

I don't know

Non so

### Actual result

It does not work

Non va

### Expected result

That works

Che funzioni

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd + 4.6.9
Android/iOS version: android
Device model: HONOR 90
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
Have you attempted updating the app to the latest version or using our beta version? You can access our beta version here: [OsmAnd Beta Version](https://osmand.net/docs/versions/nightly_versions).

**Comment by vshcherb** [comment]
Could you please try to enable v1 rendering in OsmAnd Global Settings
