### ISSUE TITLE
Offline help articles: (Image not availabe offline) not always visible

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#1884]
Small problem with our style sheet, not sure how to fix it right now:

I had added <img src="xxx alt="(Image not available offline)" to our offline help htmls, because some users were confused why sometimes images did not show up.

Looks like there is a scaling issue in our stylesheet (class="centeredimageblog"), because the alt text, when images are not present, does not show up on many help pages. (Works fine for e.g. Map legend).

**Comment by vshcherb** [comment]
The images should not be available offline. If we want to display that text, we should find another solution. And actually people would see empty border for now anyway so they could recognize that feature.
Unfortunately alt="(Image not available offline)" is not right decision, alt should have information about the image, which would make perfect sense for blind people or pictureless browsers. So I would provide proper image description instead, for the sake of following standards.

To be honest if the solution to display "Internet is required" text, will be rather difficult, I would stay as we have today.

**Comment by sonora** [comment]
Yes, good point. I had thought about that, too, using "alt" as a picture description, but from what I see an image description cannot be useful, as all that can be said in text-form is already in the text above and below. Hence I decided to solve the issue that some users were not immediately aware they can view the help files all right offline, but needed internet to see the pictures ...

Also one more observation: All help pictures seem to be "cached" (I wonder where, probably in the app's cache?), what I mean is after having been downloaded once by the app, they continue to be available offline. Looks like this works for all help images but our legend (maybe because that image is in another folder?) Would be nice to have this "caching" work for the legend, too. Although we have to make sure we have a concept which does not eat up too much device memory jus for caching pics.

**Comment by vshcherb** [comment]
I would ask @GaidamakUA to check what exactly the difference, may be the difference is the size, if there is other difference, would be great to make legend available offline as well.

**Comment by sonora** [comment]
Deprecated.
