### ISSUE TITLE
OsmAnd doesn't display metadata on POI correctly

### ISSUE THREAD

**Issue by volucris-flagrans** [osmandapp/OsmAnd#18846]
### Description

When accessing a certain POI no metadata such as opening time is displayed. If you try to edit the POI the data is correctly displayed.
https://www.openstreetmap.org/node/601700080

I am using the "Rhineland-Palatine" Map of Germany

relevant screenshots:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/27222375/14789343-4a27-4a5e-943e-9e96c3bd98ec"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/27222375/29f19986-2a2d-49dd-8972-52387c32f6cf"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/27222375/ccd3ecf7-9bc2-4326-b69f-de01c46b348c"  width="300" height="auto"/> </th>
  </tr>
</table>

The map is the most up to date version available, the issue has been ocurring for some time

### Steps to reproduce

1. Install Rhineland-Palatine Map
2. Click on the mentioned POI at Haifa-Allee 40, Bretzenheim, Germany, Node 601700080 

### Actual result

The POI is displayed, as if no metadata existed.
When editing the metadata is displayed

### Expected result

Metadata such as opening times and the website are displayed

### Your Environment (required)

```
OsmAnd Version: 4.6.9
Android/iOS version: Android 13 - SparkOS 13.6
Device model: Xiaomi Mi 9%
Crash-Logs: no crash
```

**Comment by pebogufi** [comment]
shop=home_accessories is no "official" tag.

**Comment by volucris-flagrans** [comment]
shouldn't e.g. opening times always be displayed, regardless of the type of POI?

**Comment by vshcherb** [comment]
Opening hours are displayed only for supported POIs in OsmAnd. OsmAnd doesn't support all tags for all nodes basically
