### ISSUE TITLE
An easy way to share a POI

### ISSUE THREAD

**Issue by gordian-dziwis** [osmandapp/OsmAnd#18847]
### Describe the idea (required)

I would like to share a POI with another user of osmand.
This  is the link that is shared:
```
First stay
Location: geo:35.73163,139.68241?z=11
https://osmand.net/map?pin=35.73163,139.68241#11/35.73163/139.68241
```

### Tell us about the expected behaviour (required)

I would like to open the shared link in the osmand app by clicking on it.
But the link will be opened in Firefox.

### Tell us about alternatives you've considered (required)

Sharing the coordinates and copy lat and lon to osmand by hand like a Neanderthal.

**Comment by pebogufi** [comment]
With share don't use "send", try "geo".

**Comment by dreua** [comment]
On my lineage OS I needed to configure it manually in the apps settings:
![Screenshot_20231231-121102_Settings](https://github.com/osmandapp/OsmAnd/assets/15114715/010d6403-596c-4326-946b-063fd3adea66)
No idea why the list is that long
![Screenshot_20231231-121140_Settings](https://github.com/osmandapp/OsmAnd/assets/15114715/4575d7a1-4f1a-4a5d-8276-9d262acf19cf)

Note that in Firefox the link does not automatically redirect to the app but it adds a corresponding menu entry:
![Screenshot_20231231-121603_Fennec](https://github.com/osmandapp/OsmAnd/assets/15114715/8053a3b3-b032-4384-8a17-8991081f678e)

**Comment by yuriiurshuliak** [comment]
We already possess this capability. You might need to manually adjust the settings for the types of links that OsmAnd can open, as detailed earlier. 
You can test this with the following link: https://osmand.net/map?pin=50.42610,30.51512#17/50.42610/30.51512

**Comment by dreua** [comment]
Could osmand detect the missing configuration and instruct you to set it up? As it stands I assume that most people will never figure out how that works and will go back to google because it seems more user friendly :/

**Comment by vshcherb** [comment]
Yes configurations are important we have a related task to add instructions on the web page itself

**Comment by dreua** [comment]
Relevant SO question: https://stackoverflow.com/questions/71079961/how-to-verify-android-app-links-on-android-12-and-higher
I currently don't have an android development setup but maybe someone else want's to test this and verify everything is set up correctly. Maybe this is a Lineage OS issue and works fine in stock Android, I don't know.
The metadata exists at least, but is it correct? https://osmand.net/.well-known/assetlinks.json

**Comment by gordian-dziwis** [comment]
> On my lineage OS I needed to configure it manually in the apps settings:
> <img alt="" width="300" height="auto" src="https://private-user-images.githubusercontent.com/15114715/293502468-010d6403-596c-4326-946b-063fd3adea66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NzA1MDcsIm5iZiI6MTcwNDc3MDIwNywicGF0aCI6Ii8xNTExNDcxNS8yOTM1MDI0NjgtMDEwZDY0MDMtNTk2Yy00MzI2LTk0NmItMDYzZmQzYWRlYTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDAzMTY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMTNiOTYyMTY4ZjgwNzg1NmM5ZWVmZThlOTIwMmVjMTQ2YWI2YmI2ZTA1NzA5MjljNWZhOTJiYzk4NjI1M2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MCWfH5p7GWz4L1_xgDEgqELDl5oO2gD6kEpN-YlXzFI"> 	<img alt="" width="300" height="auto" src="https://private-user-images.githubusercontent.com/15114715/293502474-4575d7a1-4f1a-4a5d-8276-9d262acf19cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NzA1MDcsIm5iZiI6MTcwNDc3MDIwNywicGF0aCI6Ii8xNTExNDcxNS8yOTM1MDI0NzQtNDU3NWQ3YTEtNGYxYS00YTVkLTgyNzYtOWQyNjJhY2YxOWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDAzMTY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NDBlNzI1Y2NhMjk1YjUwYTZlYjllODlkOTAwZWY0NzJkMDNhODgyZWJmOTg2ZjkyZDM1NTZhNjcxMGEzODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U3nh2YpDyzrVDydgq8Ho-bG6MSmhIorFYJo_9-n1W5g"> 	<img alt="" width="300" height="auto" src="https://private-user-images.githubusercontent.com/15114715/293502490-8053a3b3-b032-4384-8a17-8991081f678e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NzA1MDcsIm5iZiI6MTcwNDc3MDIwNywicGF0aCI6Ii8xNTExNDcxNS8yOTM1MDI0OTAtODA1M2EzYjMtYjAzMi00Mzg0LThhMTctODk5MTA4MWY2NzhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDAzMTY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjMjAyNDJhY2NkM2E3OGQ1Njk2MDdjNTdhYjQ1MGFkZTU1ODFkYjYxODY4YjQwMjNjNWJmMzU0M2QzYTg0ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Psb9t4yMHBGqhNHxqmfva9gpkiVSjWL2BGRpPd6jXA0">
> 
> Screenshot 1
> 
> No idea why the list is that long Screenshot 2
> 
> Note that in Firefox the link does not automatically redirect to the app but it adds a corresponding menu entry: Screenshot 3

That and disabling the build in browser in telegram helped.
