### ISSUE TITLE
Car bearing icon don't use profile color

### ISSUE THREAD

**Issue by ZMJGMADHPXWT** [osmandapp/OsmAnd#18843]
### Describe the idea (required)

It would be great to make a colour of your position mark the same as your profile. On these 2 screenshot you can see 2 profiles with different colours but car's colour is the same. 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/130372617/aab46478-d42c-41cc-a5a1-cfa2b8776ba0"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/130372617/aebc7280-ad68-4566-aefe-1bfc43edf9d8"  width="300" height="auto"/> </th>
  </tr>
</table>

### Tell us about the expected behaviour (required)

From my perspective it would be nice to have same colours for car icon as your profile because it will help to understand which profile do you use at the moment.

### Tell us about alternatives you've considered (required)

Don't see other alternatives.

**Comment by yuriiurshuliak** [comment]
It really is. The car icon does not change color according to the profile, but always remains blue.

OsmAnd~ 4.7.0#1309m, released: 2024-01-03

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/c33ac519-1b9a-44ee-b52e-032e37531e8f"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
Yes, it's planned

**Comment by dmpr0** [comment]
## ToDo
- [ ] Fix the bug. Car icon should works as other bearing icons, it has separate layer for applying color.
