### ISSUE TITLE
map in mode "direction of movement" could benefit from some damping when walking

### ISSUE THREAD

**Issue by sjvudp** [osmandapp/OsmAnd#18848]
### Describe the idea (required)

Switching the map into mode "direction of movement" (that is quite adequate for walking), I realized that the map jitters with every step I made. So I think some tunable damping that would make the map a bit more stable would have two benefits:

1. Save power by less frequently redrawing the map
2. Make it easier to read the map while walking, because it's more stable

### Tell us about the expected behaviour (required)

I made a short video (down-scaled and truncated) to show the effect:

https://github.com/osmandapp/OsmAnd/assets/6734808/002d46c1-9c74-468b-8736-91b5c2d73edf

### Tell us about alternatives you've considered (required)

I could switch the map to a different mode, avoiding the "jitter".

### Context (optional)

When recording the video, I tried to keep the mobile as steady as possible, but still I was not "on rails". So I think the sensors of the mobile (gyro, compass) detect the lateral motion for each step I made.

**Comment by pebogufi** [comment]
As I can see on your screenshot you do NOT use "direction of movement" but compass. Dir of movement has less jittering, just try it.

**Comment by sonora** [comment]
Also: _Menu > Configure profile > General settings > Use Kalman filter_ is probably set to off? I think using it would exactly apply the damping you are loooking for.

**Comment by yuriiurshuliak** [comment]
Could you please confirm if the suggestions provided earlier helped resolve the issue you were facing?

**Comment by sjvudp** [comment]
> Also: _Menu > Configure profile > General settings > Use Kalman filter_ is probably set to off? I think using it would exactly apply the damping you are loooking for.

Having made a recent test with that filter on, I could still see a slight turn (rotate) movement for every step I made (taking about walking at normal speed like 4 km/h).  To compare, [Street Complete](https://streetcomplete.app/) has a similar setting, but it seems to work somewhat better.
