### ISSUE TITLE
Search POI by name does not find alt_name entries

### ISSUE THREAD

**Issue by Hooloovoo** [osmandapp/Osmand#1885]
The POI search allows the user to search for points of interest by name. If I type, for example, "Kauapea Beach" in Kauaʻi, it will find it as expected. If I type it's alternate name (by which it is actually more commonly known), "secret beach", it will not return any results on OSMAnd, even though it will on osm.org.

**Comment by vshcherb** [comment]
Fixed

**Comment by xmd5a2** [comment]
Search by alt_name does not works. See synthetic_test_rendering , 
```
man_made : building Allgemeiner Blinden- und Sehbehindertenverein Berlin Lat 45.712906 Lon 36.613632 id=-17559  alt_name=ABSV Berlin
```
