### ISSUE TITLE
"OsmAnd~ isn't responding" alert from Android while managing maps

### ISSUE THREAD

**Issue by diggernet** [osmandapp/OsmAnd#18852]
### Description

When you go into "Download maps", it is not uncommon to start getting "OsmAnd~ isn't responding" alerts, giving the choice of "Wait" or "Close app".  This can start happening at any time, from the initial "Downloading list of available regions" to doing various maintenance work in the "All Downloads", "Local", and "Updates" tabs.  My feeling is that this is the result of some background thread getting stuck.  OsmAnd *is* still responding, and you can keep working, but you need to hit "Wait" every few seconds to clear the popup alert.  This gets tedious and annoying fast.  If you tap "Close app" OsmAnd restarts (duh) and you need to start over what you were doing, including waiting for the available regions download.

### Steps to reproduce

There aren't specific steps to reproduce, but I find that if I spent much time poking around in map management (especially the "Local" tab) it will happen sooner or later.

### Actual result

"OsmAnd~ isn't responding" alerts, but OsmAnd is still responding if you repeatedly clear the alert with "Wait".

### Expected result

Don't do whatever is causing those alerts. :)

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd+ 4.5.10
Android/iOS version: Android 13
Device model: Nokia XR20
Crash-Logs: N/A
```

**Comment by yuriiurshuliak** [comment]
The latest versions feature a comprehensive redesign of the map loading interface, resulting in enhanced speed and efficiency. Consider updating your application to benefit from these improvements, or try using the most recent Nightly version available: [OsmAnd Nightly Versions](https://osmand.net/docs/versions/nightly_versions).

**Comment by vshcherb** [comment]
4.6 version is out and has different screen, so needs to be retested
