### ISSUE TITLE
OMC gpx -> obf

### ISSUE THREAD

**Issue by mariush444** [osmandapp/OsmAnd#18866]
is it possible to add support for style of tracks and points?

./utilities.sh convert-gpx-to-obf  xxxxx
creates tracks as a very thin red line and track points as red circle with small white star.

It would be nice to have possibility to create tracks with defined width and color as an option.
Track point should be the same as define in gpx (icon and color)

**Comment by mariush444** [comment]
Finally I got the same result. Reddit ;)

**Comment by DmitryAlexei** [comment]
2 tasks:
- add extensions to data (trk)
- improve Android UI

**Comment by brad10281** [comment]
Any update here? I would love the ability to change the width of the track in the resulting obf file.

**Comment by sonora** [comment]
Issue #19892 deals with rhe 'Waypoint' appearance (color/icon) portion of this question and seems currently 'work in progress'.

I am not aware of any activity about the track width, though. It would be coding similarly to what has recently been achieved here: https://github.com/osmandapp/OsmAnd/issues/20051

**Comment by RZR-UA** [comment]
Notes:

- [ ] waypoints labels are missed at z13 (z12 ok, z14 ok)

**Comment by RZR-UA** [comment]
Tech plan:

- [ ] implement `addOsmAndTags` to add `osmand:*` ext tags to `<way>` (OsmGpxWriteContext)
- [ ] add support for `width` into default.render.xml, test in v1, v2, v2/3d, v2/track3d
- [ ] generate `id` better to avoid id overlapping for multiple obf-gpx files
- [x] fix lost zoom 13 for "route" : "point"

Note: width might be string: thin/medium/bold or int-value (custom)

xmd5a:

- [ ] transfer support `width for "route" : "segment"` to other important styles (touring, offroad, etc)

**Comment by RZR-UA** [comment]
thin
![0](https://github.com/user-attachments/assets/e7a69bd9-5e48-473b-8fc9-bac2d4d127b4)

medium
![1](https://github.com/user-attachments/assets/e8e968ba-4cda-42a0-a678-7344d4ec35dd)

bold
![2](https://github.com/user-attachments/assets/4d9333d7-1979-48a6-977b-71d652d43b12)

custom-specified (not thin/medium/bold width=X) should be supported later

**Comment by vshcherb** [comment]
- [ ] Fix waypoint icon size
- [ ] Support custom icons and colors
- [ ] On click restore same GPX ? Travel POI.

Question about track - route (https://github.com/osmandapp/OsmAnd-Issues/issues/2277)
- Shields 
- Dash

**Comment by mariush444** [comment]
The link
https://github.com/osmandapp/OsmAnd-Issues/issues/2277
doesn't work.
I'm not sure if the chackboxe's are for user's voting or for osmand team.
If it is user voting then I vote 2 then 1.

**Comment by RZR-UA** [comment]
@mariush444, Issue 2277 is our internal task to implement travel OBF collection (just a reminder for connected tasks). The checkboxes are used as a TODO list for the current Issue, and I'm going to prettify waypoint icons and try to implement GPX-like customizations. I agree with you about 2 and 1 indeed.

**Comment by RZR-UA** [comment]
Devel notes:

- [ ] think about the `ref` tag - it is displayed as "736" in the second screenshot above, and it is clickable (the way is highlighted, but click activated like a point - all in v2 engine)

- [ ] fix wrong `diff_ele_down` / `diff_ele_up` in the generation in OsmGpxWriteContext (screenshot)

![ele-fix](https://github.com/user-attachments/assets/f612dfe1-3d36-4755-ab05-92eb344afe1e)

**Comment by RZR-UA** [comment]
TODO:

- [ ] port TravelGpx changes to OsmAnd iOS
- [ ] implement click-on-track, click-on-point, show/hide features from "Travel routes" menu (v2 engine)

**Comment by RZR-UA** [comment]
How to test (for OsmAnd QA team):

1. Use master/nightly build of OsmAnd Android
2. Choose 2-3 GPX to test (GPX should include track and points and be located in one region)
3. Randomize the appearance of the tracks (use different colors, widths, show_arrows, etc.)
4. Organize points into 2-3 point groups, randomize point colors, icons, etc.
5. Save each Track using the "Share track" feature (save them to GPX-files)
6. Create a track folder ("Test folder") and import previously saved files into the folder.
7. Sync your account to OsmAnd Cloud
8. Log in to OsmAnd Web using your account
9. Find your "Test folder" and click on "Download as OBF collection" in the menu
10. The file "OsmAndCollection.travel.obf" will be downloaded as a result
11. Install another (clean) master/nightly OsmAnd Android build, download the required maps
12. Import the OBF file into freshly installed OsmAnd (Maps -> Local -> Standard -> Import)
13. TEST: your tracks should appear on the map with the same color and width as set in clause 3
14. TEST: your points should have the same color and icon as set in clause 4
15. Select "Travel guides" from the main menu and click on some of your tracks there. The track should be saved and displayed on the map immediately
16. TEST: open the saved track. Compare color, width, appearance, points groups, points colors, and points icons. All should be the same as you have saved before in clauses 3, 4
17. Retry 15-16 with all other tracks from the test folder.

Happy testing!

**Comment by vshcherb** [comment]
To test current display (in Travel Guides and on the map in iOS version

**Comment by vshcherb** [comment]
https://creator.osmand.net:8080/view/OSM%20Planet/job/Planet__OSM_GPX_Query/7/console

**Comment by RZR-UA** [comment]
OsmAnd iOS report:

1. The style is OK (track width/color OK, custom icons/colors OK) - screenshot_1
2. Points are clickable (with details), but the track is not clickable - screenshot_2
3. The Travel Guides section shows the track without any actions ("Save" is not implemented?) - screenshot_3

![1](https://github.com/user-attachments/assets/0fda4e59-a2a3-4272-95e5-bab58014aa2f)

![2](https://github.com/user-attachments/assets/8b34c332-ead8-4e94-9da3-fbe9e6f7cbc1)

![3](https://github.com/user-attachments/assets/60a396fd-e5cc-4af0-8123-3db2f5c91c52)

**Comment by DmitryAlexei** [comment]
Tested using OsmAnd~ 4.9.0#3365m, released: 2024-10-07 and TestFlight 4.8.3.6 on iPhone 13 mini and on the desktop version

- 3 tracks with different standard thickness and different colors were created. Two of them also have waypoints [Mon 07 Oct 2024.gpx.txt](https://github.com/user-attachments/files/17279189/Mon.07.Oct.2024.gpx.txt) [Simul (1).gpx.txt](https://github.com/user-attachments/files/17279188/Simul.1.gpx.txt) [Sat 07 Sep 2024_1 (1).gpx.txt](https://github.com/user-attachments/files/17279186/Sat.07.Sep.2024_1.1.gpx.txt). See screenshot 1
- then these tracks were imported into the "Testing" folder in OsmAnd cloud. After that, [OsmAndCollection.travel (3).obf.txt](https://github.com/user-attachments/files/17279187/OsmAndCollection.travel.3.obf.txt) was created and imported both in OsmAnd on Android and iOS. The result you can see in screenshots 2 and 3. Coordinates 45.39891 11.15997
- There is a little difference in colors of the initial track and OBF (see the initial orange track). On OsmAnd iOS on my Mac green color looks strange, as the track was seclected. The starting and end points of the track, as well as turn arrows, are not preserved (this is expected, I guess).


<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/da214cbe-f606-4e8d-919d-b946c8122f56"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/e5eeb347-231e-4a4c-a6c2-31ecc168e31d"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/2fb8a3d0-7ce6-494e-8773-d3045da58e96"  width="300" height="auto"/> </td>
  </tr>
</table>

![Image](https://github.com/user-attachments/assets/ed755af8-5d57-408d-8745-c7497c4c1927)



### Bugs? 


- My .obf file was not present on the Travel guides tab
- (Android) Tracks from .obf cannot be selected when tapping on their names (this seems to be expected). At the same time, tracks can be selected (but only on the map!) when tapping "0" (zero) symbol, which becomes visible when you zoom to track (see video). There is also no Track context menu (see the second pair of screenshots)
- (iOS) tracks cannot be selected even when tapping on "0". Once I received and reported a crash. 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/4e028ea4-c58c-4fbc-90ba-a90311e7259d"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/3c68a12b-3a57-45ea-9e63-caf601ef3624"  width="300" height="auto"/>     
  </tr>
</table>



<table style="width:100%">
  <tr>
<th><video src="https://github.com/user-attachments/assets/e11e2295-b388-4166-8cb6-33cbf6dd716f"  width="300" height="auto"/> </td>
    <th><img src="https://github.com/user-attachments/assets/d36318ee-4438-405e-8dcf-0445b3274603"  width="300" height="auto"/> </td>    
  </tr>
</table>


- Sometimes I wasn't able to import .obf file to the Android app. I received an error about 80-90% of tries. See screenshot.

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/b9c9353a-567c-49ce-afd9-76975839baa1"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by brad10281** [comment]
I joined the beta program to get the latest version (4.9.2). I created a simple GPX file and used the example files you attached here to get the proper extensions for color, width, etc. Before updating to 4.9.2, I was able to at least get the map (obf file) imported and displayed (width did not work though). After updating to 4.9.2, I cannot get the map to display at all. It shows up under Maps & Resources but I can't get it displayed on the map. See the attached gpx file.
[test.gpx.txt](https://github.com/user-attachments/files/17581123/test.gpx.txt)

**Comment by brad10281** [comment]
I confirmed this is working as expected. Is there any way to get transparency applied to the color?

**Comment by RZR-UA** [comment]
@brad10281 you could tune GPX-in-OBF colors by editing `routes.addon.render.xml` file in OsmAnd `files/rendering` folder.

For example, you can try the following block with transparent colors:

(find the block by `OBF-GPX relation track width/color`)

Transparent colors:
```
<apply_if additional="color_white" color="#44ffffff"/>
<apply_if additional="color_gray" color="#44999999"/>
<apply_if additional="color_darkyellow" color="#44afb61c"/>
<apply_if additional="color_lightgreen" color="#446cb52b"/>
<apply_if additional="color_lightblue" color="#442ec6ff"/>
<apply_if additional="color_red" color="$osmcRedColor"/>
<apply_if additional="color_orange" color="$osmcOrangeColor"/>
<apply_if additional="color_brown" color="$osmcBrownColor"/>
<apply_if additional="color_yellow" color="$osmcYellowColor"/>
<apply_if additional="color_green" color="$osmcGreenColor"/>
<apply_if additional="color_blue" color="$osmcBlueColor"/>
<apply_if additional="color_purple" color="$osmcPurpleColor"/>
<apply_if additional="color_black" color="$osmcBlackColor"/>
```

And place it instead of the standard colors:

(find the block by `OBF-GPX track colors`)

Standard colors:
```
<apply_if additional="color_white" color="#ffffff"/>
<apply_if additional="color_red" color="#ff0000"/>
<apply_if additional="color_orange" color="#ff7200"/>
<apply_if additional="color_brown" color="#ba7007"/>
<apply_if additional="color_darkyellow" color="#afb61c"/>
<apply_if additional="color_yellow" color="#edc300"/>
<apply_if additional="color_lightgreen" color="#6cb52b"/>
<apply_if additional="color_green" color="#00842b"/>
<apply_if additional="color_lightblue" color="#2ec6ff"/>
<apply_if additional="color_blue" color="#4e4eff"/>
<apply_if additional="color_purple" color="#a71de1"/>
<apply_if additional="color_gray" color="#999999"/>
<apply_if additional="color_black" color="#000000"/>
```

**Comment by brad10281** [comment]
Thanks for the response. I'll give this a try.

One more question, What are all of the "0's" that are now displayed on the imported map? Is there a way to get rid of them?
![Screenshot_20241031_093715_OsmAnd](https://github.com/user-attachments/assets/9ecec4e3-f2ee-4e49-8ddf-db65dc716b01)

**Comment by RZR-UA** [comment]
The "0" will soon serve as the click-on-map icon. This feature is under construction now.
Could you share your OBF file and the GPX tracks included in it (make the ZIP archive)?

To remove it manually, you can play with the section `OBF-GPX usual shields (based on textLength)` in `routes.addon.render.xml` file.

Just try to edit out the following lines:

```
<case nameTag="ref" textOnPath="false" textColor="#404040" textShield="yellow_square_9_road_shield">
  <apply_if textLength="1" textShield="yellow_hexagon_3_road_shield"/>
  <apply_if textLength="2" textShield="yellow_hexagon_4_road_shield"/>
  <apply_if textLength="3" textShield="yellow_hexagon_5_road_shield"/>
  <apply_if textLength="4" textShield="yellow_square_6_road_shield"/>
  <apply_if textLength="5" textShield="yellow_square_7_road_shield"/>
  <apply_if textLength="6" textShield="yellow_square_8_road_shield"/>
</case>
```

**Comment by brad10281** [comment]
Just wondering, what exactly is the "click-on-map icon"?

That screenshot must have been a one-of-a-kind. I cannot get that many 0's to display on the screen anymore. It only shows one or two now. I attached the GPX file here. It's a rather large file.
[MI ORV Route.gpx.txt](https://github.com/user-attachments/files/17590185/MI.ORV.Route.gpx.txt)

**Comment by RZR-UA** [comment]
The "click-on-map" (aka Road Shield) icon will activate the Save-to-GPX dialog in the future. Additionally, GPX files would have unique tags such as shield_fg, shield_bg, shield_text, and shield_textcolor to customize the Shield appearance.

You can check how it could be displayed on our development screenshot:

![shields](https://github.com/user-attachments/assets/d33503fd-c134-49e3-991d-12a69b711fa3)

**Comment by brad10281** [comment]
Do you have an example of how to implement that in the GPX file? Does this work in v4.9.2? Is the idea to show a shield for each track segment?

**Comment by RZR-UA** [comment]
The feature is currently under construction.

The current approach is to define 1 shield_fg/bg/text per 1 GPX file, not for each distinct segment.

Your case with a really big GPX file seems unique. Your GPX has 34k points, which is greater than a standard Garmin device can display (AFAIK, a maximum of 20k per 1 GPX).

PS. OBF generation based on this kind of GPX-tags will be available soon. You could try matching the tags in the example below with the corresponding sections of routes.addon.render.xml (which has already been added in 4.9.2):

```
  <metadata>
    <name>Terchovsko - Oravská cyklomagistrála</name>
    <desc>Strečno - Terchová - Novoť</desc>
    <extensions>
      <osmand:relation_gpx>yes</osmand:relation_gpx>
      <osmand:color>red</osmand:color>
      <osmand:shield_text>C</osmand:shield_text>
      <osmand:shield_textcolor>red</osmand:shield_textcolor>
      <osmand:shield_bg>osmc_white_bg</osmand:shield_bg>
    </extensions>
  </metadata>
```

**Comment by brad10281** [comment]
This doesn't seem to work anymore. I can't get the color or the width of the track to change from a thin red line again. I'm using the latest public beta version of OsmAnd+ and the latest OsmAndMapCreator.

**Comment by brad10281** [comment]
> How to test (for OsmAnd QA team):
> 
> 1. Use master/nightly build of OsmAnd Android
> 2. Choose 2-3 GPX to test (GPX should include track and points and be located in one region)
> 3. Randomize the appearance of the tracks (use different colors, widths, show_arrows, etc.)
> 4. Organize points into 2-3 point groups, randomize point colors, icons, etc.
> 5. Save each Track using the "Share track" feature (save them to GPX-files)
> 6. Create a track folder ("Test folder") and import previously saved files into the folder.
> 7. Sync your account to OsmAnd Cloud
> 8. Log in to OsmAnd Web using your account
> 9. Find your "Test folder" and click on "Download as OBF collection" in the menu
> 10. The file "OsmAndCollection.travel.obf" will be downloaded as a result
> 11. Install another (clean) master/nightly OsmAnd Android build, download the required maps
> 12. Import the OBF file into freshly installed OsmAnd (Maps -> Local -> Standard -> Import)
> 13. TEST: your tracks should appear on the map with the same color and width as set in clause 3
> 14. TEST: your points should have the same color and icon as set in clause 4
> 15. Select "Travel guides" from the main menu and click on some of your tracks there. The track should be saved and displayed on the map immediately
> 16. TEST: open the saved track. Compare color, width, appearance, points groups, points colors, and points icons. All should be the same as you have saved before in clauses 3, 4
> 17. Retry 15-16 with all other tracks from the test folder.
> 
> Happy testing!

Tried this but it doesn't work. The GPX file looks good (color and width). But when I save it as an OBF Collection and import it into OsmAnd, it just shows the thin red line. I inspected the saved GPX file and it has all the proper info (color & width), but OsmAnd seems to ignore it.

**Comment by RZR-UA** [comment]
@brad10281, which OsmAnd version have you used? Could you post ZIP with both OBF, GPX input, and GPX output files?

**Comment by brad10281** [comment]
[northern_lp_orv_routes.zip](https://github.com/user-attachments/files/18830529/northern_lp_orv_routes.zip)

I'm using version 4.9.10 from the Play Store. I have attached the INPUT, OUTPUT and OBF files for your review.

Thanks

**Comment by RZR-UA** [comment]
@brad10281, OsmAnd 4.9.10 lacks support for refreshed Travel OBF styles.

Please try OsmAnd 5.0.0 beta or nightly or wait for the 5.0 release soon.

I've tested your OBF file, and it looks good (blue tracks, medium width)

![Image](https://github.com/user-attachments/assets/b1cda258-fd9a-49a5-b072-c811df472cb1)
![Image](https://github.com/user-attachments/assets/c3f0ffeb-f639-43e3-8642-3d2db89c88e5)

**Comment by brad10281** [comment]
Thanks. Updated to 5.0.1 and it's working as expected.
