### ISSUE TITLE
My Tracks, select multiple tracks then show on map does not work

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#18861]
### Description

Selecting multiple tracks then show on map does not work.
Showing single track is ok .

### Steps to reproduce

Open My tracks, rec, 2023-12, then select two (or more)  tracks, then 3 dots menu "show on map".

### Actual result

Nothing happens. The app stays on list view of 2023-12

### Expected result

Switching to map view, move and zoom so that the selected tracks are complete visible, like when showing a single track.

### Your Environment (required)

OsmAnd Version: OsmAnd~ 4.7.0#1308m, veröffentlicht: 2024-01-03
Android version: 12
Device model: Samsung S10

**Comment by Rowin63** [comment]
In the +4.6.11 the selected tracks are displayed on the map, but Osmand stays in the track list and does not switch over to the map.

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. Here are the steps to reproduce:

- Record two tracks and confirm their display on the map.
- Turn off the "show on map" feature for these tracks.
- Navigate to the "Rec" folder, tap the three dots, choose "Select," then select the two tracks, tap the three dots again, and select "show on map."

After following these steps, the expected outcome should be the successful display of the two tracks on the map.

OsmAnd~ 4.7.0#1320m, released: 2024-01-04


https://github.com/osmandapp/OsmAnd/assets/127092082/db84458f-ecb5-47bc-8102-e81b1f943916

**Comment by pebogufi** [comment]
I see on the video, that you need to tap three times "back" to go back to map view.
I think this should not be needed.
"Show on map" should directly show the selected items without further actions.

**Comment by Rowin63** [comment]
Exactly, as it was before 👍

**Comment by sonora** [comment]
> I see on the video, that you need to tap three times "back" to go back to map view. I think this should not be needed. "Show on map" should directly show the selected items without further actions.

#18490 "Show all tracks on the map" shows an equivslent issue, should probably also better be (re-)fixed like you describe.

**Comment by pebogufi** [comment]
@vshcherb 
NOT fixed.
Problem persists in
OsmAnd~ 4.7.0#1527m, veröffentlicht: 2024-02-05
as stated above...
...
you need to tap three times "back" to go back to map view.

**Comment by Rowin63** [comment]
Right, it still exists. Selected tracks are displayed, but the screen still does not switch over to the map, but remains in the tracks page.

**Comment by yuriiurshuliak** [comment]
This is expected behavior. Enabling or disabling the "Show on map" feature controls the visibility of tracks on the map but doesn't immediately display the chosen items; further actions are necessary.

**Comment by pebogufi** [comment]
If i go to a single track, then open three dots menu, then "Show on map" the track is shown immediately after the display has opened the map (automatically).

So, that is not consistent to the behavior you described as "expected behavior".

**Comment by Rowin63** [comment]
Also the "configure map > tracks" menu acts like this. Select some tracks, tap "apply" and osmand switches to the map, displaying your selected tracks.

**Comment by dmpr0** [comment]
> If i go to a single track, then open three dots menu, then "Show on map" the track is shown immediately after the display has opened the map (automatically).
> 
> So, that is not consistent to the behavior you described as "expected behavior". NO further actions are necessary.

Yes

**Comment by sonora** [comment]
"_Show on map_" means ""_Show on map_". And not:"_Mark to be shown on the map later..._" 😉 

(And why would we want to **remove** such a frequent use case?)

**Comment by sonora** [comment]
@dmpr0 I just notice you opened https://github.com/osmandapp/OsmAnd/issues/19050 yesterday, and your reply may relate to that  But there you are talking about the "Show on map" as a status menu item on the track's content menu, and it has an on/off switch.

This ussue here talks about about an action menu, where you had selected some tracks and nwt try perform an action, or also the folder-associated menu "Show wll tracks on the map" is an action in itself, which should be carried out immediately if selected.

**Comment by pebogufi** [comment]
I think two different terms should be used, otherwise there would be a misinterpretation or irriration for many users
- "show on map" for   _action_
- "visible on map" for   _status_

**Comment by vshcherb** [comment]
> If i go to a single track, then open three dots menu, then "Show on map" the track is shown immediately after the display has opened the map (automatically).

It's correct cause show on map for single action is different than for multiple. So it also requires additional confirmation.
