### ISSUE TITLE
A building missing in app compared to website

### ISSUE THREAD

**Issue by Volitonus** [osmandapp/OsmAnd#18873]
### Description

Hi,

A building is missing in the osm app, compared to osm website. What might be the reason? Is it possible fix this? Can I assist?

Location
65.74039 -19.63509

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/155091911/c0e21dbb-6dd7-4ffe-aa7c-e2dfee3592bc"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/155091911/dcc6908b-755b-47ec-8da8-1fffe5c864b9"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/155091911/78fe51ab-5ad0-41b7-99d3-661e97ef2ddb"  width="300" height="auto"/> </th>
  <th><img src="https://github.com/osmandapp/OsmAnd/assets/155091911/6269cf36-2878-4f19-97ff-ac958c474b5f"  width="300" height="auto"/> </th>
  </tr>
</table>

Regards,
Jonasz

### Steps to reproduce

Open 
https://www.openstreetmap.org/#map=17/65.74030/-19.63504
or
https://vesoyu.github.io/s2cell/
at that location and the building is there.

Open OsmAnd app or Pokémon GO at the same location and the building is missing.  

### Actual result

Web

Screenshot 3

App

Screenshot 4

### Expected result

Same building in both

### Your Environment (required)

```
OsmAnd Version: 4.6
Android/iOS version: iOS 17.1.2 (21B101)
Device model: iPhone SE 3rd gen
Crash-Logs: no
```

**Comment by scaidermern** [comment]
https://www.openstreetmap.org/way/1215867339

Added three months ago 🤔

**Comment by sonora** [comment]
Yes, just update your offline map in OsmAnd, then the building is there... 😉

**Comment by yuriiurshuliak** [comment]
This building is now displayed, just update the map.

OsmAnd 4.6.4.3

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/0e2a0d87-1480-4afa-ad35-e6170c52e507"  width="300" height="auto"/> </th>
  </tr>
</table>
