### ISSUE TITLE
After update: Track is displayed with some "standard settings" though set to user defined (color, start/finish symbols, ...)

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#18871]
### Description

I don´t know when this did begin, but recently after every update tracks are displayed with some "standard settings" though they are set user defined color, width, arrows, start/finish symbols.

### Steps to reproduce

My tracks are set to yellow and some other settings:
Screenshot 1

Update Osmand.
Select and display tracks.
What I see now is this:
Screenshot 2

Tapping a track opens the menue and now I see this:
Screenshot 3
(Osmand knows "my" settings, but does not display them)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/95540936/743bed43-9bcb-4ac0-85f1-f36ab4df317d"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/95540936/d1823de4-a297-4bec-b4af-aabc3649a54a"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/95540936/17561c8b-2ec3-4ff2-9a46-3dd4baa455d5"  width="300" height="auto"/> </th>
  </tr>
</table>

Canceling brings me back to those unwanted "standard settings", I have to edit/save all my tracks to get my settings back.

### Actual result

Wrong settings displayed

### Expected result

Use my settings, you know them!

### Your Environment (required)

OsmAnd Version: ~4.7.0#1320m (also previous)
Android version: 13
Device model: S20+

**Comment by zipav** [comment]
OsmAnd Nightly 4.7.0#1402m, released: 2024-01-21

| before updating | after updating |
| --- | --- |
| ![01](https://github.com/osmandapp/OsmAnd/assets/123936521/3f852647-ff59-4b87-a8e6-305c7a493afc) | ![02](https://github.com/osmandapp/OsmAnd/assets/123936521/9d001a96-dd92-48e2-9f9d-8340a47a6866) |

**Comment by Corwin-Kh** [comment]
Could not reproduce the issue.
| 4.6.0-1135 | 4.7.0-1406 | 4.7.0-1726 |
| --- | --- | --- |
|![01](https://github.com/osmandapp/OsmAnd/assets/29124437/41d726e8-4426-415b-99f5-23e8e44d1599)|![02](https://github.com/osmandapp/OsmAnd/assets/29124437/e4890d15-c6ae-474c-9361-29b33f6d56dc)|![03](https://github.com/osmandapp/OsmAnd/assets/29124437/8b3f2a98-38ab-46ee-b817-49e0e5583895)|

after updating track appearance stace the same.

**Comment by Rowin63** [comment]
Also here "not planned". But it happened again.
After the update to +4.7.17 ALL my tracks are set back to standard appearance.
By tapping "reset to original" I get my track colors back, one by one. 

Just boring.
