### ISSUE TITLE
Tracker-Status Widget can't be added

### ISSUE THREAD

**Issue by DavidWorm** [osmandapp/OsmAnd#18877]
### Description

I can't add the "OsmAnd Tracker-Status" Widget (the one to share locations via the telegram API.
I couldnt find any workaround yet.
All other widgets work as expected, so this widget has some special problem.

### Steps to reproduce

- Select Driving Profile (but it doesnt matter)
- Go to Menu->Configure Screen->Right Panel->OsmAnd Tracker-Status
- Tap on the name (nothing happens)
- Tap on the littel "i" at the end of the coloumn 
- Tap on add

### Actual result

- The widget is not listed in the active widgets for the right panel or shown on the map screen
- The App is not crashing or dropping an error, the widget just isnt listed

### Expected result

- The widget is listed in the active widgets for the right panel, like all the other widgets doo as well.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.6.11
Android/iOS version: 11
Device model: Carpe Iter Pad v4b
Crash-Logs: ?
```

**Comment by mikehgentry** [comment]
Probably a duplicate of #18235

**Comment by DavidWorm** [comment]
Yeah, the last comment of @DmitryAlexei is exactly my issue.
