### ISSUE TITLE
Routing ignored tag vehicle=no and uses motorcar= destination

### ISSUE THREAD

**Issue by fortranxx77** [osmandapp/OsmAnd#18878]
### Describe the routing engine used (required)

Routing by https://osmand.net/map/

### Describe your routing Profile (required)

Profile car or truck

### Describe your start and end points (required)

Start point : 53.586710,  8.574668
End point : 53.587334, 8.570516

### Describe the actual route (required)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/155267998/cf08c260-a684-43a1-973d-5a66deffb7c0"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/155267998/db176bee-5e88-4de2-89d9-0fcb5da308e1"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/155267998/8f443fb5-be86-4780-ba4a-c1caf63c67c5"  width="300" height="auto"/> </th>
  </tr>
</table>

### Describe what Maps you used (online or offline) (required)

OpenStreetMap

### Your Environment (required)

```
OsmAnd Version: 4.6.11
Android/iOS version: 13
Device model:
```

### Anything else? (optional)

Routing ignored tag vehicle=no

**Comment by scaidermern** [comment]
https://www.openstreetmap.org/way/34622131

There is `vehicle=no` but `motorcar=destination`. Maybe the `*=destination` isn't handled correctly and the penalty should be higher? On the other hand, handling this tag correctly isn't trivial and your destination is only shortly after this road. So maybe the calculated route is correct.

**Comment by fortranxx77** [comment]
Useing OSRM (FOSSGIS)  calculated route is correct, but useing osmand calculated route is not correct, why ?

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. When using point-to-point navigation in a car on OsmAnd, the vehicle=no tag isn't considered, resulting in a straight-line route calculation. Check out the link [here](https://test.osmand.net/map/?start=53.586710,8.574668&finish=53.587334,8.570516&type=osmand&profile=car#16/53.5874/8.5693).
Contrarily, when calculating the route by car on OpenStreetMap, it takes a detour into account. You can see the difference through [this OpenStreetMap link](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=53.58644%2C8.57462%3B53.58734%2C8.57052#map=15/53.5836/8.5798).

<table style="width:100%">
  </tr>
  <tr>
    <th>OpenStreetMap</th>
    <th>OsmAnd</th>
  </tr>
  <tr>
    <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/83930d18-0765-43fe-a73a-77d30bc9635f"  width="1000" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/ad42dc2d-0063-42f4-adb9-5d1bd440b117"  width="1000" height="auto"/> </th>
  </tr>
</table>

**Comment by mariush444** [comment]
agree, vehicle=no means don't go by car.
The problem is with OSM data.

but unfortunately there are planty bugs like that.
