### ISSUE TITLE
Wrong tag name when editing POI

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1889]
Если редактировать уже существующую POI, то на вкладке "Расширенные" в поле "Tag" находится не настоящий тег, а значение "name" из poi_types.xml. Здесь должно быть значение tag.
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot_2015-11-09-18-46-17.png
```xml
<poi_additional name="information_map" tag="information" value="map"/>
```

**Comment by vshcherb** [comment]
Что-то все баги про одно и тоже, объединить надо #1892 . Видно же что Editing POI редактируется совсем неправильно, по сути надо исправить одну вещь, а дальше будет работать как Create POI
