### ISSUE TITLE
Map zoom after searching for categories or housenumber should be increased

### ISSUE THREAD

**Issue by Max1234-Ita** [osmandapp/OsmAnd#18901]
### Description

I've noticed that, when searching for an address or a POI by category, the map zoom factor is adjusted to 15 and I have to manually zoom in to see more details.

I think this value is too little and should be increased a bit, at least to '17 or '18', in order to provide the user with a better view of the selected location and its neighbourings.

### Steps to reproduce

1. Launch OsmAnd
2. Enable the OsmAnd Development plugin and put the 'Zoom factor' widget in any panel (i.e. right panel)
3. Open the _Search menu -> Address_ and search for a complete address (city + street + housenumber)
4. Select the desired result and show it on map; notice that the zoom factor is set to '15'
5. Manually zoom in to factor 17 or 18: the chosen location is way more visible.
6. Open the _Search menu -> Category_ and search for a POI; show it on map and notice that the zoom factor is set to '15' again. Manually zoom in for more details

### Actual result

After searching for an address or POI, zoom factor is set to 15

### Expected result

Setting the zoom to 17 or 18 would immediately give the user a better view with more details on the chosen location without having him/her to zoom in manually.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd Nightly 4.7.0 #1356m, released 2024-01-12
   Observed also on OsmAnd Plus v. 4.6.11

Android/iOS version: Android 14, Android 11
Device model: Google Pixel Tab (emulated), Samsung Galaxy A50 (physical)
Crash-Logs: None
```

**Comment by vshcherb** [comment]
Agreed. To do: Zoom should be 16 cause that's default zoom to display Buildings and for searching a specific POI / Favorite / Waypoint / building / house 16 should be default. For streets, cities and other search results it could stay lower as it is.

**Comment by Max1234-Ita** [comment]
> Agreed. To do: Zoom should be 16 cause that's default zoom to display Buildings and for searching a specific POI / Favorite / Waypoint / building / house 16 should be default. For streets, cities and other search results it could stay lower as it is.

Hmm, I think 16 is still a little too low, however.

The town I live in has about 40000 inhabitants: if I search for a particular building, of which I know the house number, with zoom = 15 I can see all all of it, plus some surroundings; with 16 I see almost all the town centre; I think 17 would be good, 18 is great but you lose a little the overview, so I would candidate 17 as an optimal value to be adopted.

Attaching some pictures taken from my smartphone.

Anyway, I think @Sonwon1 is not wrong, the best would be adding an option in OsmAnd settings, allowing the (advanced) users to set the default value they prefer.

Zoom == 15
![image](https://github.com/osmandapp/OsmAnd/assets/15315381/c695f9fc-d4e8-4f56-92fb-12b33d062e89)


Zoom == 16
![image](https://github.com/osmandapp/OsmAnd/assets/15315381/cae22ec9-1f9a-4b58-8e21-ab52776783e9)



Zoom == 17
![image](https://github.com/osmandapp/OsmAnd/assets/15315381/82d18e31-9c2d-4cfc-ae63-595003e9fb48)



Zoom == 18
![image](https://github.com/osmandapp/OsmAnd/assets/15315381/e4201081-634b-476f-8a07-f8da3e2d3659)

**Comment by Sonwon1** [comment]
Just make it user adjustable, problem solved. Give the user control!

**Comment by sonora** [comment]
Well, yet another user setting, we must have hundreds by now. And then in every profile, I guess? 😉 

Trouble is that there is probably no one answer, not even one answer per user if you could adjust it. The issue above assumes that when you look for something you always,want to view the immediate vicinity of it, i.e. the surroundung buildings. But in as many cases I find myself not caring about the neighboring buildings, but trying to find out in which part of town or suburb something is located  (like e.g. a hotel).

So I guess there is no good one answer, not even if this were user definable. I always simply use the (+)/(-) zoom buttons depending on the actual use case, and would say @vshcherb  's suggestion of zoom 16 seems good enough as a starting point in all directions?

**Comment by Sonwon1** [comment]
> Well, yet another user setting, we must have hundreds by now. And then in every profile, I guess? 😉
> 
> Trouble is that there is probably no one answer, not even one answer per user if you could adjust it. The issue above assumes that when you look for something you always,want to view the immediate vicinity of it, i.e. the surroundung buildings. But in as many cases I find myself not caring about the neighboring buildings, but trying to find out in which part of town or suburb something is located (like e.g. a hotel).
> 
> So I guess there is no good one answer, not even if this were user definable. I always simply use the (+)/(-) zoom buttons depending on the actual use case, and would say @vshcherb 's suggestion of zoom 16 seems good enough as a starting point in all directions?

This is why I believe default settings that a user could change in an advanced settings menu would be the best solution. This allows everyone to use OsmAnd as they need and not how they are told it should be used. If you are worried about a user messing things up then include a return to default action in the menu.

**Comment by sonora** [comment]
Yes, but my point was even if you had this setting, depending on what you search for on different occasions you may find it needs a different value on every occasion?

**Comment by Sonwon1** [comment]
Exactly, which is why it is important to let the user decide which setting best suits their needs since not one default will work in all cases.

I am advocating for a design philosophy in whole not for just this setting. I left Google Maps because it became to restrictive and features were removed. I also left Garmin for the restrictions. Now on an Android tablet I can run OsmAnd and OBDII dashboard in split screen mode. I came here for the flexibility. I like to see all of the data that Garmin and Google Maps hides from me. As far as I can tell OsmAnd is currently the most flexible and feature rich nav/mapping app.

**Comment by sonora** [comment]
Yeah, we both agree, I'm not trying to hide anything. I am simply pointing out that a setting whichh would need frequent adjustnent per use case is questionable.

**Comment by dmpr0** [comment]
<table style="width:100%">
  <tr>
    <th>City – 15</th>
    <th>POI from search – 16</th>
    <th>Search > POI > Show on map – 12</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/d24d946d-5e2d-4d8e-b40b-583a5a7d7d7d"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/8c8e0970-c905-444b-9ddc-4598453ba87c"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/d8544176-6342-49d3-ad25-05cfe166c828"  width="300" height="auto"/> </td>
  </tr>
</table>  

<table style="width:100%">
  <tr>
    <th colspan=3><h3>Address</h3></th>
  </tr>
  <tr>
    <th>First open</th>
    <th>Second open</th>
    <th>Video</th>
  </tr>
  <tr>
    <td><img src=""  width="300" height="auto"/> </td>
    <td><img src=""  width="300" height="auto"/> </td>
    <td><video src=""  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by dmpr0** [comment]
# Review 
- [ ] Todo is missed. Based on available information I can't understand what was done and create task for iOS team.

**Comment by vshcherb** [comment]
**Implemented algorithm**
- If search object could be visible with previous map center (before search) to extent of ZOOM - 2, then map just zooms out and center moves to search object. For example, my location is in center with zoom 16, nearby searched POI is in 300m but doesn't fit visible bbox of zoom 16 and fits bbox on zoom 14 so both my location and searched POI is visble.
- In all other cases when zoom out doesn't help to see previous map center and search POI default constants are used: 
   - POI / Building - 16
   - Street - 15
   - City - 14
