### ISSUE TITLE
Smart route recalculation cannot be turned off through UI, doesn't work with intermediary destination.

### ISSUE THREAD

**Issue by Guylby** [osmandapp/OsmAnd#18908]
### Description

First let me say that I absolutely love Osmand and I use it every time I can, be it hiking, visiting cities and now for long car trips. But there has been inconsistencies in the behaviour of Smart route recalculation:

The UI toggle of Smart route recalculation does nothing and doesn't disable it, you have to manually edit the routing xml and the "recalculateDistanceHelp" to "0" to disable it. 
However, if you add Intermediary destination to a route, smart route recalculation will not work and Osmand will recalculate the whole itinerary up to the first intermediary destination point. 

This issue might be linked to #18824

I've tried uninstalling, reinstalling Osmand multiple times, reset profiles, use Truck profile (which I've never used) and this bug was there every time. 

### Steps to reproduce

I'll reuse the steps of issue #18824 as it can clearly show whether smart route recalculation is enabled or not:

Gpx used to simulate gps position:
[Wed.27.Dec.2023_1.zip](https://github.com/osmandapp/OsmAnd/files/13931676/Wed.27.Dec.2023_1.zip)
Destination point:
45.06718°N, 4.86215° E
  
**Smart route recalculation cannot be disabled:**
- load the gpx track in simulate position, start the simulation and stop it immediately to create a static gps position.
- in the standard car profile, navigate to the destination point above (end of the gpx track)
- start the navigation, load the details and look at the directions.
- in simulate position, load the gpx track and start the simulation.
After the first roundabout, a reroute will be triggered. New directions will be shown near instantly, as smart route recalculation is on (so only recalculate the first 10kms). It will also show the bug of issue #18824, skipping highway directions after 10kms. 

Go to Configure Profile>Navigation Settings>Route Parameters and disable Smart Route Recalculation. Restart Osmand and redo steps above:

Nothing changes, route is recalculated instantly, same bug appears.

Now edit the routing.xml file and change the "recalculateDistanceHelp" to "0" to disable it. 

<img src="https://github.com/osmandapp/OsmAnd/assets/151167525/de64f975-ed71-4d79-aecb-d589c59a2a88" width="500" />

Redo the steps above.
Now the route recalculation is much longer and the bug does not appear, as Smart Route recalculation is off. 

**Smart route recalculation does not work with intermediary destination:**
- Change back the routing.xml file to default (change the "recalculateDistanceHelp" to "10000") to enable Smart Route Recalculation. 
- Redo steps above but add an intermediary destination just before the end of the route, then start navigation and simulate the gps position. 
- Again, the route recalculation is much longer and the bug does not appear, as Smart Route recalculation is off. 

### Actual result

The UI toggle of Smart route recalculation does nothing and doesn't disable it, you have to manually edit the routing xml and the "recalculateDistanceHelp" to "0" to disable it. 
However, if you add Intermediary destination to a route, smart route recalculation will not work and Osmand will recalculate the whole itinerary up to the first intermediary destination point. 

### Expected result

Smart route recalculation can be turned through the UI toggle,
Smart route recalculation works with Intermediary Destinations.

### Your Environment (required)

```
OsmAnd Version: 4.6.11
Android/iOS version: Android 13
Device model: Sony Xperia 10 III
```

**Comment by vshcherb** [comment]
Not sure if we fix this issue separate from https://github.com/osmandapp/OsmAnd/issues/18824, I think with 4.7 release we will enable new routing engine that won't have such issue (now it's called Special Routing in Development settings)

**Comment by vshcherb** [comment]
recalculateDistanceHelp was only used for first segment and I think this option will be deleted - merge to https://github.com/osmandapp/OsmAnd/issues/18908
