### ISSUE TITLE
+4.6.11 crashes without report/log (Favorite deletion)

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#18907]
### Description

Actually I´m planning a new trip and therefore I´m zooming and panning around a lot in one country, seeking and marking (adding as favorites) interesting spots to see. Every now and then Osmand closes (maybe once an hour?). No report or notification is created. No freeze. Have some tracks on display, but far away from osmands previous (large tracks-)limits. It comes surprisingly, without any strange behaviour before. Nothing noticeable at Osmands next start.

Happened three more times since opening this issue, every time when zooming out after setting/editing a favorite. 

### Steps to reproduce

I don´t know, just zooming and panning around in the "show map"-profile, but somehow it seems to be "favorite-related" (I´m busy with favorites right now)

### Actual result

Osmand closes/crashes

### Expected result

No closing/crashing

### Your Environment (required)

OsmAnd Version: +4.6.11
Android/iOS version: 13
Device model: S20+
Crash-Logs: is not created

**Comment by vshcherb** [comment]
Please check tombstones https://osmand.net/docs/user/troubleshooting/crash-logs/. Unless we have tombstone at least it will be hard to fix it. So far we can't proceed with it but we will monitor other issues

**Comment by yuriiurshuliak** [comment]
Thank you for providing the tombstones files. Our developers had an attempt to identify the root cause of the crashes you've been experiencing. Unfortunately, based on the tombstones, we couldn't clearly find the exact problem. In order to better understand the issue, could you please provide us with a short video demonstrating the problem?

**Comment by Rowin63** [comment]
Hmm. I would like to, but I don´t know, howe to manage this. Can´t record hour by hour, waiting for it to happen.
Right now it happened again: 
I was in the "my places>favorites"- menu, editing some recently created favorites (moving them one by one in another group, or deleting one). At one point, osmand closes suddenly (I THINK it was after tapping the final "yes" after "delete this favourite?" but I´m not 100% sure) The "app closing" comes suddenly, unexpected and without any notice. Sorry I can´t provide you any further information. But it´s obvoius to me, it is "favorites-related". It always happens when being around somewhere in the favorites (like internal "updating" of the favorite-database by "save/move/delete"?). If I find out something new, I will let youknow. Thanks!

**Comment by yuriiurshuliak** [comment]
I managed to reproduce this crash on Android, moreover, a user with a similar problem on iOS contacted us at zendesk support. The crash occurs when deleting favorites, it may not happen immediately.
I also managed to get log files and crash logs.
[logs.zip](https://github.com/osmandapp/OsmAnd/files/14027380/logs.zip)


OsmAnd~ 4.7.0#1408m, released: 2024-01-23

<table style="width:100%">
  </tr>
  <tr>
    <th>Android</th>
    <th>iOS</th>
  </tr>
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/3799afa9-16ed-4d35-828d-09bb317af353"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/b79dcd38-0fd6-4bc5-a8dd-db299e426cdc"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
Potentially related -   #00  pc 0x000000000045a330  /data/app/~~FML5Bg0iJ7Na-aExyPiCJA==/net.osmand-TVvg1-mEMUAUzgzU3wR4RQ==/split_config.armeabi_v7a.apk!libOsmAndCoreWithJNI.so (Java_net_osmand_core_jni_OsmAndCoreJNI_PointI_1x_1get) (BuildId: 6c2baa65fc7ab40adf107adeea4e7b6dea82f82d)

**Comment by vshcherb** [comment]
This crash related only to favorites deletion

```
Exception occurred in thread Thread[AsyncTask #1,5,main] : 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String net.osmand.data.FavouritePoint.getCategory()' on a null object reference
	at net.osmand.plus.myplaces.favorites.FavouritesHelper.delete(FavouritesHelper.java:265)
	at net.osmand.plus.myplaces.favorites.dialogs.FavoritesTreeFragment$2.doInBackground(FavoritesTreeFragment.java:164)
	at net.osmand.plus.myplaces.favorites.dialogs.FavoritesTreeFragment$2.doInBackground(FavoritesTreeFragment.java:149)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```

We didn't discover any other crash, so we assume this need to be fixed.
