### ISSUE TITLE
Wrong POI type value in "Edit POI" dialogue while editing an existing POI

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1891]
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot_2015-11-09-18-28-40.png
"POI type" contains "name" from poi_types.xml. There should be english translation, not internal name, like in same dialogue during poi creation
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot_2015-11-09-18-30-55.png

**Comment by vshcherb** [comment]
Duplicate #1892
