### ISSUE TITLE
Double titles show even only one map activated

### ISSUE THREAD

**Issue by kirillaristov** [osmandapp/OsmAnd#18923]
### Description

No possibility to turn off map titles from local map.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/39505043/aa429134-2f4a-4c9b-a71c-980f31683de0"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/39505043/a001d2f4-cd4e-46c2-b94f-6f4e6a5024fb"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/39505043/69438cde-82ec-4a9f-94e8-d51d5c1cb81d"  width="300" height="auto"/> </th>
  </tr>
</table>

### Steps to reproduce

Open map "Osmand (online tiles)".
Turn off all other maps, overlays and features.
Despite this double titles appears.

### Actual result

Double titles

### Expected result

Possibility to fully turn off local map titles. View only current map and nothing more.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: Plus version 4.6.11
Android/iOS version: Android 7
Device model: Xiaomi Redmi Note 4
Crash-Logs: ?
```

**Comment by Vucumpra** [comment]
Cache problem ?

**Comment by yuriiurshuliak** [comment]
I tried to reproduce this bug and I see a similar result with Overlay/Underlay enabled. Tiles are saved in the cache during use of Online Raster maps as Main / Overlay / Underlay layer. Most likely, these are really cache problems.

Try to clear map tiles cache:
Menu → Download maps → Local → Online and cached tile maps → choose online maps →⋮ → Clear all tiles

If the problem persists, you can try clearing the app cache:
Settings > Apps > OsmAnd > Storage > Clear Cache
or reinstalling the app. Before reinstalling, please back up all your personal data such as tracks and favorites. You can do this by going to Menu > Settings > Export to file.

OsmAnd~ 4.7.0#1376m, released: 2024-01-17

<table style="width:100%">
  </tr>
  <tr>
    <th>With Overlay/Underlay enabled (online tiles)</th>
    <th>With Overlay/Underlay disabled</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/0daf3254-4af6-4b31-8cc3-a3526e650e66"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/7798fe2b-3f6e-43d1-ac0a-83c58b09ddfd"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by kirillaristov** [comment]
Restart the device helps — no double titles.

**Comment by kirillaristov** [comment]
Clearing the system cache of the application did not help, restarting the device did not help. Apparently, the titles didn't disappear last time because of the reboot.
![IMG_20240118_101133](https://github.com/osmandapp/OsmAnd/assets/39505043/171bcdcd-3f21-44d0-a26d-99a0352b8207)

**Comment by goldfndr** [comment]
When you tap one of the small circles in the "After clearing the cache" image, or a trees icon in the first image, does [a Map Context menu](http://osmand.net/docs/user/map/map-context-menu) appear?

**Comment by kirillaristov** [comment]
I got the idea. I compared the two versions of the app (old and new), but found no difference between them. I was unable to reproduce the error on the copy.

The error is not reproducible in version 1 of the map rendering engine (not OpenGL). When I turner on version 1 of map rendering engine, the error is gone.

I tried deleting all the maps and downloading them again, but it didn't help.

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. I tried to reproduce this problem again on the release version of the application, enabling live updates.
A similar behavior is reproduced, only when Overlay/Underlay is enabled. It is strange that in the application clone, you do not have this problem.

Please try to reset the profile settings. Menu - Settings - App profile (Driving,etc) - Reset to default
After that, try deleting and downloading the maps again. Also, as an option, you can reinstall the application.

<table style="width:100%">
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/2b8c86f2-b327-40fe-988c-a531258b0687"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/0897b38c-80cb-4640-9cc1-c6feea6003cf"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Raiedecharles** [comment]
ok i reset all parameters and i still have the problem
