### ISSUE TITLE
No raw tags on "Advanced" tab while editing an existing POI

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1892]
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot_2015-11-09-18-28-40.png
No raw tags on "Advanced" tab. There should be tags and values like in same dialogue during poi creation
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot_2015-11-09-18-30-55.png

**Comment by vshcherb** [comment]
Editing existing poi is not correct "traffic_signals" should not be displayed because it is not correct poi type (it is a tag value)

**Comment by Barrocas** [comment]
I believe what he meant is that the tag value is not displayed, (like
highway=traffic_signals).

In advanced tab we can only see 'highway', and no value is displayed to be
edited.


-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by Barrocas** [comment]
In the night build from day 10-11-2015, when editing an existing POI, the existing poi_type value was displayed and available for editing, both in the basic and advanced tabs, now it's not displayed anymore, only a blank field.

**Comment by GaidamakUA** [comment]
@Barrocas it was broken because of changes necessary to make possible to edit changes that are not yet upload to OSM. It will be working again soon.

**Comment by vshcherb** [comment]
Fixed
