### ISSUE TITLE
issue with central kurdish branch language

### ISSUE THREAD

**Issue by RenasAzad** [osmandapp/OsmAnd#18928]
hi osmand

there are an issue in osmand+ / map rendering engine / version 2 (OpenGL), with central kurdish branch language (CKB), while every thing is normal in version 1 of map rendering engine.

the issue is with numbers when they come with letters, the attached screenshot explaines the issue obviously.

see this location to see the example:
35.61117 45.32215

best regards

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/93521817/e7144ff6-b8b9-488b-8acf-8361f0981a26"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by yuriiurshuliak** [comment]
This bug has been reproduced. As you can see from the screenshots, only on OpenGL the names are displayed differently.

OsmAnd~ 4.7.0#1390m, released: 2024-01-19

<table style="width:100%">
  </tr>
  <tr>
    <th>OSM</th>
    <th>Web version</th>
    <th>Rendering version 1</th>
     <th>Rendering version 2</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/80f4a825-7a34-4ca9-8344-0a102ddb0571"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/e58617ae-bcfe-4baf-8f25-c9cda70a5900"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/4545c064-dce4-4c0c-9c6f-bf8c1b456f64"  width="300" height="auto"/> </th>
  <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/3edbd291-67a1-4cd2-b76e-c922523c10db"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by RenasAzad** [comment]
thank you for  solving the bug.
yes, the issue is  only in OpenGL.
you are the best developer team 👍.

**Comment by RenasAzad** [comment]
osmand+ 4.7.0 released and i tried it, but the issue not solved, still remain.

**Comment by yuriiurshuliak** [comment]
This task is still under development. Please, stay tuned for a future update.

**Comment by RenasAzad** [comment]
ok, thank you very much.

**Comment by dmpr0** [comment]
Done

<table style="width:100%">
  <tr>
    <th>Android</th>
    <th>iOS</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/52bccc26-1320-4ee2-be1b-030c0147c154"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/4073751e-ec95-47c1-b20f-ce0697b3b9a5"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by molaeiali** [comment]
I think there's still some issues here, I explained more here: #19542
