### ISSUE TITLE
wrong opening hours for mo-su

### ISSUE THREAD

**Issue by axayr25** [osmandapp/OsmAnd#18933]
### Description

I know a restaurant works for everyday and i added mo-su (no hours) to opening_hours. in the app it shows 'open 24/7'. mo-su doesn't mean that the restaurant works 7/24. it should be 'mo-su'

### Steps to reproduce

-open openstreetmap editor
-create a poi that support opening_hours
-type mo-su for opening_hours

### Actual result

'open 24/7'

### Expected result

mo-su

### Your Environment (required)

OsmAnd Version: 4.5.10 **`~`**
Android/iOS version: android 14
Device model: ---
Crash-Logs: ---

**Comment by vshcherb** [comment]
Without time specified it means 24/7. Mo-Su 00:00-24:00 it means

**Comment by scaidermern** [comment]
If the restaurant isn't opened 24/7 then Mo-Su is wrong, isn't it?
Are the correct opening hours just unknown to you or don't they exist at all?
If you want to indicate that the restaurant is opened every day but doesn't has fixed opening hours, then add a comment like `opening_hours=Mo-Su "only if weather is good"` or something similar. Check https://wiki.openstreetmap.org/wiki/Key:opening_hours.
