### ISSUE TITLE
Two new Transportation modes one for Manual Wheelchair and another for Electric Mobility devices.

### ISSUE THREAD

**Issue by lorentedford** [osmandapp/OsmAnd#18932]
### Describe the idea (required)

The idea of this is to have the GPS guide wheelchair users on routes that are safer and better for wheelchair users. I personally flipped my wheelchair coming off the Sidewalk here locally because there was no wheelchair ramp. Some way for users to add in no wheelchair ramp on sidewalks etc. Some sidewalks are torn up and not replaced this would be useful to report it and find a different route. 

### Tell us about the expected behaviour (required)

I think my expected behavior is it learns what routes I take and can learn whether i had to take the road or the sidewalk. Also the GPS could hopefully guide me to sidwalks that may have ramps and make it safer to navigate. 

### Tell us about alternatives you've considered (required)

I haven't found any alternative solutions for this issue anywhere.. No one seems to care about ADA or our routes we have to take to go anywhere. 

### Context (optional)

Please if its possible I would love to have a working gps for use with my wheelchair to assist me in navigating around and allow some sort of reporting feature to report sidewalk problems.

**Comment by scaidermern** [comment]
Related to #9415

**Comment by vshcherb** [comment]
Yes just added. If somebody has spare time, I think somebody could create a profile using custom routing.xml based on pedestrian profile

Closing as duplicate
