### ISSUE TITLE
Filter update for smart folders incorrect

### ISSUE THREAD

**Issue by ymuetzle** [osmandapp/OsmAnd#18938]
### Description

The option to create smart folders is very useful. Unfortunately, the contents of the folders are displayed incorrectly when renaming tracks. The renamed track appears twice. Refreshing does not change anything. To achieve the correct filtering, OSMAND must be closed and restarted.

### Steps to reproduce

See above

### Actual result

See above

### Expected result

See above

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version: 13
Device model: Oneplus 8pro
Crash-Logs: No crash
```

**Comment by zipav** [comment]
OsmAnd Nightly 4.7.0#1578m, released: 2024-02-12
### Steps to reproduce:
- OsmAnd Menu 
- My Places
- Tracks
- Three dots in the upper right corner of the screen
- Add smart folder
- Three dots in the upper right corner of the screen
- Edit filter button
- Choose the filter (I choose the Nearest cities filter)
- Rename 1 track by add to its name an underscore
- Choose the result (appears duplicate track with the original track in the same smart folder)
- After that close and reopen the app (all tracks disappear from smart folder)
- After that close and open the app again (all tracks appear in smart folder and duplicate disappears)


https://github.com/osmandapp/OsmAnd/assets/123936521/abeb9d21-925f-4a72-a13a-3f209e4b952c


https://github.com/osmandapp/OsmAnd/assets/123936521/f10182b2-3048-466f-911a-5cb17db59b7f

**Comment by dmpr0** [comment]
# Review

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/2ec7e790-3510-412c-9a1b-7556051e4316"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   


- [ ] Reproduced if Smart folder is filtered by Nearest city.

**Comment by dmpr0** [comment]
# Review
- [ ] Removed tracks is shown in Smart folder until app restart.
