### ISSUE TITLE
Text labels on the map detached from POI 

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#18946]
## Description
Nature reserve, protected area POI text lanes is lack POI details that can be found thru search.

> Relation – https://www.openstreetmap.org/relation/12045006
> POI Coordinates –  `51.33122, 29.88397`
> Text label coordinates – `51.37206, 29.66563`

### How to reproduce

**Text label** 
* Open OsmAnd – search `51.37206, 29.66563`
* Tap on **Chornobyl Radiation and Ecological Biosphere Reserve**
* POI details will be empty

**POI**
* Open Menu – Search
* Search for `Chornobyl Radiation... ` in the same area
* Tap on search result

### Actual result

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>POI</th>
        <th>Text label</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/0dea11b7-1599-494c-9061-f880bc73acde"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/2b0871a5-9f43-4b19-bf2b-d94b9c8b5c24"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

* Context menu for text label point lack POI details

### Expected result
* Taping on text label and to POI in search result, should show context menu with full list of details.

**Environment**
OsmAnd Version:
Android/iOS version:
Device model:

**Comment by Dima-1** [comment]
This fix also affects on relations with tag boundary have values protected_area, low_emission_zone, national_park, danger_area and haven't tag type=multipolygon

**Comment by Dima-1** [comment]
The fix will take effect when the new maps are generated next month.
