### ISSUE TITLE
Not all ruins are rendered on map

### ISSUE THREAD

**Issue by Max1234-Ita** [osmandapp/OsmAnd#18949]
### Description

I've noticed that OsmAnd properly renders ruined buildings if the tags are present:
_building=yes
ruins=yes_ 

i.e. this object: https://www.openstreetmap.org/way/892069771#map=18/45.24150/7.67737
is rendered by OsmAnd like this:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/15315381/cccbccc0-6e2c-4c3b-b09f-75c522e5b82a"  width="300" height="auto"/> </th>
  </tr>
</table>

Same object visible in JOSM:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/15315381/2fff6db6-2e04-4646-a6fc-59780d5d23e8"  width="300" height="auto"/> </th>
  </tr>
</table>

However, if the element is tagged, i.e. with _ruins:building=yes_, it is not displayed on the map: https://www.openstreetmap.org/way/1239141459#map=19/45.21745/7.73074

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/15315381/8331d493-0ec8-47ed-9d34-b6a102725691"  width="300" height="auto"/> </th>
  </tr>
</table>

JOSM:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/15315381/c5789b8b-26fc-4d77-8e5b-d39409c96bc0"  width="300" height="auto"/> </th>
  </tr>
</table>

The _ruins:*_ tag should be rendered on the map in the same style as _ruins=yes_, at least with the dashed contour.

Ruins may serve as a reference point i.e. in a trekking; they also provide additional information when searching for some shelter in case of bad weather (if I see a building from the distance but from the map I know it's ruined, then I will avoid it and look somewhere else).

NOTE: I'm not speaking about historic ruins (which are properly rendered), but of generic ruined structures, especially buildings (about 6500 occurrences in TagInfo), but also other categories might be useful.

https://taginfo.openstreetmap.org/search?q=ruins%3A#keys

### Steps to reproduce

1. Launch OsmAnd and locate an object which is tagged in OSM, with ruins:*, i.e. https://www.openstreetmap.org/way/1239141459#map=19/45.21745/7.73074

### Actual result

Such an object is not visible in the OsmAnd offline map

### Expected result

The _ruins:*_ tag should be rendered on the map in the same style as _ruins=yes_, at least with the dashed contour (optional: if the _ruins:building_ tag is present, it should have the same style of _building=yes_ + _ruins=yes_)

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:	OsmAnd Plus v. 4.6.11; Offline vector maps.
Android/iOS version:	Android 11
Device model:	Samsung Galaxy A50 (SM-A505 FN)
Crash-Logs: None
```

**Comment by scaidermern** [comment]
In case somebody wonders, the `ruins:*` prefix is part of the [lifecycle prefixes](https://wiki.openstreetmap.org/wiki/Lifecycle_prefix).

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced.

In the first case, the building is visible on the map, and the OSM tags are as follows:
[Link to OSM](https://www.openstreetmap.org/way/892069771#map=18/45.24150/7.67737)
building: yes
ruins: yes

In the second case, the building is not displayed on the map.
[Link to OSM](https://www.openstreetmap.org/way/1239141459#map=19/45.21755/7.73067)
ruins: building: yes
You can observe the discrepancy in the web version by visiting: [Web Version](https://test.osmand.net/map/?start=45.217570,7.730220&type=osmand&profile=car#19/45.21770/7.72993)

OsmAnd~ 4.7.0#1435m, released: 2024-01-26

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/b07e0555-8aa4-4e91-853d-05a19f8822ae"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/c3c852d6-2ce7-4994-af3d-c93d322c64a3"  width="700" height="auto"/> </th>
  </tr>
</table>

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/c0ee0764-dd47-4b83-997e-c55ad97cad1f"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/b8267685-01ca-45f8-bcc6-ea05a2d328d0"  width="700" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
6.5K https://taginfo.openstreetmap.org/keys/ruins%3Abuilding#overview
Overpass https://overpass-turbo.eu/?template=key-value&key=building&value=ruins

**Comment by xmd5a2** [comment]
Place to test: https://www.openstreetmap.org/way/1239141459#map=19/45.21745/7.73074
Map: Italy_piemonte

**Comment by zipav** [comment]
OsmAnd Nightly 4.7.0#1672m, released: 2024-02-26


<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/f679fd17-507a-45cd-b5b6-9990e916d34f"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/3629fff8-ca71-4450-a1b6-3e162080b542"  width="700" height="auto"/> </th>
  </tr>
</table>

**Comment by xmd5a2** [comment]
Please retest. Should work 
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/cd0f95cc-18e6-413c-9611-1e504114d503)

**Comment by zipav** [comment]
OsmAnd Nightly 4.7.0#1676m, released: 2024-02-26

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/6720ba2a-6ae4-4563-99ee-f42d477471c0"  width="300" height="auto"/> </th>
  </tr>
</table>
