### ISSUE TITLE
Street Name is not shown when reference is set on road

### ISSUE THREAD

**Issue by vrtareg** [osmandapp/Osmand#1894]
Hi

I have noticed that despite the fact that option "Show Street Names" is on latest builds stopped to show the street Names during free drive or navigation if there is a reference set on road.

Is this intended change?

Regards,
Areg

![screenshot_2015-11-10-09-41-24](https://cloud.githubusercontent.com/assets/2562730/11062064/8f5df7fe-87a3-11e5-80cc-0bc36840fee3.png)
![screenshot_2015-11-10-09-45-13](https://cloud.githubusercontent.com/assets/2562730/11062063/8f5bb426-87a3-11e5-831a-05a225083475.png)

**Comment by vrtareg** [comment]
Hi

Any update on this? 

Regards, 
Areg

**Comment by xmd5a2** [comment]
Can't confirm:
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot_2016-01-20-23-00-18.png
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot_2016-01-20-23-05-23.png
