### ISSUE TITLE
cannot start text-to-speech engine.

### ISSUE THREAD

**Issue by oxxm** [osmandapp/OsmAnd#18947]
### Description

The following error message is shown when switching profiles in the navigation screen: cannot start text-to-speech engine.

Question: under which circumstances this error message appears? It is a permission topic?

### Steps to reproduce

1- Tap on the navigation right arrow
2- switch to any profile

### Actual result

The following error message is shown: cannot start text-to-speech engine.

### Expected result

No error message

### Your Environment (required)

OsmAnd Version: 4.6.11 (not since this version, was in earlier versions as well)
Android Lineage OS 17.1
Device model: Samsung S9

**Comment by scaidermern** [comment]
Since you are using LineageOS, do you have a TTS engine installed?

**Comment by yuriiurshuliak** [comment]
Visit our troubleshooting guide on TTS-related issues:  https://osmand.net/docs/user/troubleshooting/navigation#tts-does-not-function-properly

**Comment by oxxm** [comment]
thanks for the feedback! Topic closed.
