### ISSUE TITLE
Incorrect display of rtsa_scale in certain mountain passes.

### ISSUE THREAD

**Issue by fftmp** [osmandapp/OsmAnd#18941]
### Description

Mountain passes have optional property [rtsa_scale](https://wiki.openstreetmap.org/wiki/Key:rtsa_scale).  Some values for this property are displayed incorrectly. Possibly, this is for unexpected values (i.e. values, that doesn't listed in wiki page above).
See also currently used values: https://taginfo.openstreetmap.org/keys/rtsa_scale#values. 

Not sure, whether this is problem of OsmAnd itself or may be OsmAnd-resources.
I found [code](https://github.com/osmandapp/OsmAnd-resources/blob/0b7663206d94520d7c5e296a2a38ff49ff8d2bf2/obf_creation/rendering_types.xml#L5371) there, that looks like sort of mapping. If this true, it's wrong to convert '1А-1Б' to '1А*' IMHO, better to remain value as-is. And anyway, I see '1А1' instead of '1А*'.

### Steps to reproduce

View map near https://www.openstreetmap.org/node/5569733509 for example.

### Actual result

"1A1" as rtsa_scale for example pass:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/25722875/fc40aecf-51ce-4efd-b446-57141d2cfc94"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/25722875/46f4b9d5-fe1b-4fb9-8b6e-a5534d12b2cb"  width="300" height="auto"/> </th>
  </tr>
</table>

### Expected result

rtsa_scale depicted as specified as in OSM, i.e. "1А-1Б" for example pass.

### Your Environment (required)

OsmAnd~ 4.5.10 from F-Droid repo.

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To observe the bug, navigate to the coordinates 42.63925° N, 44.71877° E, and select the LeraKT mountain pass. In the context menu, you will find 'rtsa_scale' labeled as '1А1.' The OSM displays 1А-1B, you can check it out via this link: https://www.openstreetmap.org/node/5569733509#map=17/42.63901/44.72002.

OsmAnd~ 4.7.0#1408m, released: 2024-01-23

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/b3976d1d-9c59-447c-9476-1bfdb1eaf230"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/63b2e919-956d-405d-a583-d6b385f1e305"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
We need to simplify value list to have proper search for POIs however we don't need to simplify to display text. Though this one doesn't look correct cause it should be "1A*" not "1A1".
Also we could have 2nd internal tag/value to keep and display value as it is.

**Comment by xmd5a2** [comment]
Value "1A1" in POI data was produced by some weird map processing bug. If value in entity_convert contains " * " then it is transformed to "1". But if name tag originally contains " * " all is ok.
I've changed conversion to avoid "*" which besides is more correct in my opinion.
Dev notes: currently we can't display original value in POI context menu while searching by simplified value. Yes we can add second internal tag but we can't hide original tag from context menu while allowing to search by it. **We need to add such functionality or leave it as is.**

**Comment by vshcherb** [comment]
Decided to leave as it is
