### ISSUE TITLE
Map doesn't update after underlay toggle

### ISSUE THREAD

**Issue by mbartlett21** [osmandapp/OsmAnd#18954]
### Description

When I enable or disable the satellite underlay, the areas shown on the map (grass/beach/etc.) don't hide or show until I zoom in or out.

### Steps to reproduce

1. Open the map.
2. Turn on the underlay map (use half transparency so you can tell)
3. Note that the areas shown on the map are visible
4. Zoom in or out enough to cause osmand to render more tiles.
5. Observe that the areas now correctly hide.

### Actual result

as above

### Expected result

I expected changing the map settings to rerender the appropriate tiles without having to change zoom level.

### Your Environment (required)

```
OsmAnd Version: 4.6.13
Android/iOS version: Android 13
Device model: Zenfone 9
Crash-Logs: -
```

**Comment by zipav** [comment]
OsmAnd Nightly 4.7.0#1633m, released: 2024-02-20

@mbartlett21 please clarify does the issue appear to be observed here?
If not, we kindly ask you to provide us with a video of exactly how the issue looks like on your device.

https://github.com/osmandapp/OsmAnd/assets/123936521/5ca9c5cb-4a6d-47df-865f-5f9152ea7990

**Comment by mbartlett21** [comment]
The issue seems to have been fixed / disappeared in the couple of versions since. (Now running 4.7.2)
