### ISSUE TITLE
Add medium speed. Rename "average speed" to "average driving speed"

### ISSUE THREAD

**Issue by snooppr** [osmandapp/OsmAnd#18964]
### Describe the idea (required)

![osmand](https://github.com/osmandapp/OsmAnd/assets/61022210/a1ef1827-9573-48e7-a8cc-09f93f91d99e)

When planning his route, the user sets the average speed.
Example, to cover 100 km in a day, an athlete knows that his average speed with stops must be no lower than v=S/t=4.17 km/h.
Problem: when the user stops for a rest, turns on the pause, OsmAnd begins to calculate the “average speed” as the “average speed in motion”, not taking into account the rests (and such an average speed will be overestimated in relation to the true overall average speed and you have to mentally recalculate the average speed, to keep the pace of 4.17 km/h.). Or don’t pause in the application during a rest/rest, but then the results will suffer. Typically, athletes like to upload pure results (net speed in motion, etc.) to sports social networks, which is why they take pauses at rest, but this interferes with planning at the moment of activity.
But at the same time, OsmAnd also displays, in addition to “movement time” from which it calculates the average movement speed and “total time (see screenshot 1, left)”, but from which OsmAnd does not calculate the overall average speed.

And so at the moment OsmAnd somewhat misleads the user, displaying the “average speed”, but does not tell whether this speed is relative to the movement or the “total average speed” relative to the start.
Rename "average" to "average in motion" and add "overall average speed" (see screenshot 1, right).

### Tell us about the expected behaviour (required)

To plan and maintain the calculated pace, the user will know exactly how much time he can spend resting in order to keep the average speed within the given limits, but at the moment he has to constantly recalculate it in his mind, because OsmAnd shows the average speed in motion, and not overall average speed.
You can add the parameters “average speed” and “total time” to the “analysis by intervals” section (see screenshot 1, on the right, highlighted in red).

### Tell us about alternatives you've considered (required)

Yes, there is an alternative, but it’s on Desktop, and you need it in your pocket; you won’t always carry a laptop with you.
Software alternative - GpsPrune
![gpsprune](https://github.com/osmandapp/OsmAnd/assets/61022210/d4a76f01-9ba0-4861-a251-2a7408b2662b)

**Comment by vshcherb** [comment]
I think it's quite different direction than we think. We think that you need to use markers with average speed (probably customizable), so you could always see ETA. Using ETA you can easily calculate how much do you have to rest to continue the route

**Comment by snooppr** [comment]
If I understand correctly, this means that you need to build a route and enable navigation along it, and the widget will notify you of the estimated time of arrival. The problem here is that route guidance is a significant overhead on the battery (at least that was the case before). Alternative: I build a track, visually divide it into segments, for example 1 km, and just look at the map at what mark/segment I am and how much is left, it’s convenient and cheap.

**Comment by snooppr** [comment]
![трекер](https://github.com/osmandapp/OsmAnd/assets/61022210/8531526a-6eb7-4295-8c34-101256c61c1b)
Just another example of this feature from a third-party application.

**Comment by snooppr** [comment]
And one more example, from another application.
![2024-02-15-23-40-30-133](https://github.com/osmandapp/OsmAnd/assets/61022210/d0ceb049-8e93-4e18-9d39-b25b4671faba)

@vshcherb As you can see, many programs display the average speed and average speed in motion, I think that OsmAnd missed this point.

**Comment by snooppr** [comment]
Your quote about comparing Garmin vs OsmAnd

>people who are starting to use OsmAnd instead of expensive Garmin devices, since we have now caught up with it in functionality.  I'm talking about various hiking trips, orienteering and offroad tourism.

![garmin](https://github.com/osmandapp/OsmAnd/assets/61022210/8df40266-90d2-4ea1-8bcf-90f5a8f835d2)
As you can see, even in the Garmin navigator there is a display setting for “average overall speed” and “average speed in motion.”

I hope someday active people will be able to change their sports trackers to OsmAnd, but at the moment the functionality of OsmAnd for them is weak.  This concerns not only the lack of understanding of such simple things as speed, but also the voice of a circle, etc.

**Comment by vshcherb** [comment]
Yes we have average speed in motion, though it's impossible to fit all indicators to this list. We're going to redesign however avg speed in motion is not a top widget in our metrics list. We have more important: duration, total uphill / downhill, average global speed, total distance

**Comment by snooppr** [comment]
In fact, see the very first cropped screenshot (on the right), only three lines are occupied, half of the screen is empty, gray and just idle, you can add a few more lines there.
If you plan to add a bunch more metrics, you can make these lines customizable, like in other applications, so that the user can choose which metrics to view on the secondary screen.
