### ISSUE TITLE
I cannot uninstall the app. Can you please help?

### ISSUE THREAD

**Issue by flawpc** [osmandapp/OsmAnd#18965]
OsmAnd author:flawpc I cannot uninstall the app. Can you please help?

flawpc@gmail.com

**Comment by pebogufi** [comment]
Uninstalling an app is NOT within the functionallity of the app, but within operating system, "apps"

**Comment by TheSnoozer** [comment]
https://support.google.com/android/answer/13627402?hl=en

```
Open the Google Play Store app Google Play.
At the top right, tap the Profile icon.
Tap Manage apps & devices and then Manage.
Select the name of the app you want to delete.
Tap Uninstall.
```

**Comment by flawpc** [comment]
I thank pebogufi, TheSnoozer, and others that helped.

**Comment by pebogufi** [comment]
@flawpc 
If your probem is fixed, please close this issue.
