### ISSUE TITLE
Map downloads named "download.php"

### ISSUE THREAD

**Issue by twzkxkan** [osmandapp/Osmand#1896]
On your [downloads page](http://download.osmand.net/rawindexes/), the map files default to being named "download.php". They function fine if they are renamed and the proper file extension is added, but it's a big inconvenience. Can this be fixed so the file extension and name are the same as they appear on the site?

I really appreciate that you offer these downloads because it makes it possible to use OsmAnd on devices without Internet access. Thanks! :)

**Comment by vshcherb** [comment]
We actually didn't offer it, it just internal api which we don't close outside
