### ISSUE TITLE
Difference between POI categories in Android / iOS version

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#18971]
## Description 
WIP

<table style="width:100%">
  <tr>
    <th>iOS</th>
    <th>Android</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/ce3706bf-6fa8-4a8d-82bf-39d271c55767"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/5fcb4ce0-8ec8-41a6-b14e-04948458a72e"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
Search code should be the same (migrated) - Android / iOS

**Comment by Dima-1** [comment]
<table style="width:100%">
  <tr>
    <th>iOS</th>
    <th>Android</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/31807095/11101f2c-18c4-4959-8653-312b2cd95a9e"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/31807095/b5f3877f-dd71-4b77-ba98-4b5e5e15af74"  width="300" height="auto"/> </td>
  </tr>
</table>
