### ISSUE TITLE
Sometimes the actual route becomes invisible

### ISSUE THREAD

**Issue by madbehaviorus** [osmandapp/OsmAnd#18987]
### Description

Sometimes I noticed an very awful bug during the navigation to a specific point.
During the routing I can see the yellow routing way and the blue and black arrows.
I don't know the trigger, but If it happens, than the blue and black arrows and the yellow route gets invisible.
The routing itself works, the announcement also, but without the arrows and the important yellow route, it is impossible or really difficult in big cities to take the right route.

### Steps to reproduce

This error only occurs if I set a destination point manually on the map with "Set destination" and route there from "my position".
It can happen on different ways, profiles, countries, time or high.

### Actual result
During routing, the blue and black arrows and the yellow route gets invisible (see discription above).
It depends on the driver, but in some situations it can be very dangerous.

### Expected result
A normal routing with the yellow route and the blue and black arrows within.

### Your Environment (required)

I don't have root or a custom recovery like twrp on this device.
So I can't get the logs with logcat.
Actually I use a Fairphone 4 with official CalyxOS. 

But this is not decisive. I can reproduce this bug on some Android devices with different roms on different Android versions.

```
OsmAnd Version: 4.5.10
Android/iOS version: 14
CalyxOS Version: 5.3.1
Device model: Fairphone 4
Crash-Logs: see above
```

### Other

I can't find any problems like mine. The only other opened bug with invisibility on paths or points that I see is [10192](https://github.com/osmandapp/OsmAnd/issues/10192), but mine is completely different.

**Comment by sonora** [comment]
I believe this was a known issue in v4.5 and has been fixed in 4.6 versions, looking for"route line disappears" or similar should produce the corresponding issue reports.

**Comment by yuriiurshuliak** [comment]
May be related to https://github.com/osmandapp/OsmAnd/issues/17506 or https://github.com/osmandapp/OsmAnd/issues/17908
Try to update the app or download the release version.

**Comment by madbehaviorus** [comment]
Thank you for your fast reply.
I changed to 4.6, but there's another big Issue with the tracking points. If I record the actual track, the points are get not registered, independent from using OsmAnd in background or in front, so I changed back to 4.5 and have to deal with it, up to the other issue is fixed. But this is not related to [18303](https://github.com/osmandapp/OsmAnd/issues/18303).
