### ISSUE TITLE
Analyze on map back button close context menu

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#18988]
## Description
Taping back button  on **Analyze on map** screen close the context menu and send user back to My Places, this is wrong if menu was open from context menu.

### How to reproduce
* Open OsmAnd – **Menu** – **My Places** – **Tracks**
* Tap on any track, content menu will be open
* Tap on **Options** –  **Analyze on map**
* Tap **Back** button in AppBar

### Actual result
<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Video</th>
        <th>Before opening</th>
        <th>After Back</th>
      </tr>
      <tr>
        <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/d2f831dd-6b58-47e8-8f02-be3e8785fffa"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/c4ea0039-b721-464e-84e3-adbc7cfec6ac"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/4b47fcee-afab-410c-8321-cb05d87c115f"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

* Taping back close track context menu 

### Expected result
- [ ] Screen is blinks, and shows: Map > My Places > Parent folder ?
- [x] Taping Back should redirect user back to the screen from which **Analyze on map** was opened. Analyze on map can be opened from: 
* * My Places > Track > three dot menu > context menu
* * Track > Options > Analyze on map

**Environment**
OsmAnd Version:
Android: 14
Device model: Pixel 6A

**Comment by divyesh-mali** [comment]
Hello sir, I'm interested in solving this issue. I'm beginner in Android dev and I want to help the open source community from my side while I'm learning. Please assign me this issue. I will try my best to solve it.

**Comment by Chumva** [comment]
@divyesh-mali you can try to fix any easy issue for you in [issues](https://github.com/osmandapp/OsmAnd/issues) and create pull request, if the fix is appropriate and issue is approved (for example from the next milestones) I will check it and, probably, merge

**Comment by divyesh-mali** [comment]
Thanks, @Chumva  
I'll definitely try to find some easy issues and submit pull requests.
