### ISSUE TITLE
Request: Center Double tap zoom while navigating

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#1899]
When we are browsing the map (not navigating), if we double tap a location, it is zoomed at the center of the screen.

But if we are navigating, it zooms and moves to the bottom center, almost out of reach.
I use the double tap to zoom and then more precisely add POI, but if it zooms to the bottom of the screen, I then have to pan it back up to the center, to be able to see and use that location spot.

Can the double tap on the map always zoom to center of screen, even while navigating?

**Comment by vshcherb** [comment]
After long discussions it is decided not to change cause it could be misleading. OsmAnd provides seamless switch between navigation and map browse, so this is unwanted change

**Comment by Barrocas** [comment]
Misleading in what way?

When we are not navigating, and just browsing the map, if we double
tap on a location, that spot it is centered in the screen.

If we start navigating and we double tap the same spot, it is zoomed
to the lower center part of the screen (instead of centered).

So what was proposed was in fact a simplification and unification of
the zoom behaviour.

-- 
Cumprimentos,
D.er Hugo Barrocas
