### ISSUE TITLE
Heightmap data wrong for Iceland region

### ISSUE THREAD

**Issue by l-mb** [osmandapp/OsmAnd#18992]
### Description

With the Pro subscription, OSMAnd makes the Topography plugin and additional data sets available.

For the coordinates at ~ 66N 23W in Hornstrandir, Iceland, the data set is incorrect. It appears as if the tiles aren't properly aligned at the 23W boundary (?).

This isn't just visual, it also affects elevation profiles for all routes planned and navigation.

### Steps to reproduce

Navigate to https://osmand.net/map?pin=66.32965,-22.99816#17/66.32965/-22.99816 in OSMAnd.

Activate the topography plugin, and either contour lines or slopes/hillshades.

### Actual result

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/1162196/eeae9659-bc34-4577-8c17-2090966c5e9f"  width="300" height="auto"/> </td>
  </tr>
</table>

You can see there's a break that can't be found on any terrain map or satellite.

### Expected result

The data should be aligned and match up with smooth slope, matching the actual shape of the planet :-)

Depending on the fix approach, if this data isn't properly available via the SRTM data set, perhaps ArcticDEM could/should be used? https://arcticdem.apps.pgc.umn.edu/

Here's an example of how the data looks there (hillshading with contour lines): 
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/1162196/28bbb1cf-7990-45cc-be89-77e61f0c7d1b"  width="300" height="auto"/> </td>
  </tr>
</table>

### Your Environment (required)

```
OsmAnd Version: 4.6.11, 2023-12-28
Android/iOS version: Android 14
Device model: Pixel 6 Pro
Subscription: OsmAnd Pro
```

**Comment by l-mb** [comment]
The `Heightmap Iceland europe.tif` provided via OSMAnd Pro (when translated via gdal) has clear artifacts and weird tiles. (And is real coarse, which isn't well documented?)

More uptodate and detailed heightmap data is available at https://data.pgc.umn.edu/elev/dem/setsm/ArcticDEM/mosaic/v4.1/ (as documented here: https://www.pgc.umn.edu/guides/stereo-derived-elevation-models/pgc-dem-products-arcticdem-rema-and-earthdem/#section-8 ).

I don't (yet?) understand how to translate the ArticDEM tiles into a (possibly higher-resolution?) heightmap for OSMAnd to use.

**Comment by l-mb** [comment]
https://osmand.net/docs/technical/map-creation/create-offline-maps-yourself does, unfortunately, not document how to create heightmaps.

The required tiles from ArticDEM for this particular issue are 17_50, 17_51, 16_50, 16_51 (but probably all of Iceland should be regenerated, if not the entire Arctic region).

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce, go to these coordinates 66.329515,-22.998161 , activate Contour lines, Terrain, 3D Relief and download the corresponding maps. A visually visible gap between the tiles will be displayed.

OsmAnd~ 4.7.0#1528m, released: 2024-02-05

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/3dbf030c-9e6d-4d71-b8a5-3904bd03a1c3"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/01fe11a4-daed-4480-a0f4-86b29be847bc"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by xmd5a2** [comment]
Fixed. Updated terrain maps for Iceland are available for downloading.
|    |  |
| ------------- | ------------- |
| ![Screenshot_2024-02-12-15-39-01-497_net osmand plus](https://github.com/osmandapp/OsmAnd/assets/5829014/7b5926df-2b0d-4a88-9c20-286a08cd45f5)  | ![Screenshot_2024-02-12-15-40-44-496_net osmand plus](https://github.com/osmandapp/OsmAnd/assets/5829014/89d11d08-1178-4896-9127-c8309455dfca)  |

|    |  |
| ------------- | ------------- |
| ![Screenshot_2024-02-12-15-42-13-140_net osmand plus](https://github.com/osmandapp/OsmAnd/assets/5829014/79c545b9-bc55-43d5-8741-bab3d25e3478)  |   ![Screenshot_2024-02-12-11-02-37-674_net osmand plus](https://github.com/osmandapp/OsmAnd/assets/5829014/e654ce50-59d8-45c9-9f78-24e66fd0a203) |

**Comment by l-mb** [comment]
This is awesome! Confirmed. Much more detailed as well.

Thank you very much.

**Comment by l-mb** [comment]
@xmd5a2 As this gets wrapped up, can I ask what the magic commands to convert the data sets are? Because I tried to figure them out myself and failed, so I'm curious.

Also, I was considering to experiment with higher resolution to see how that'd affect file size, performance, and results.

If not, no worries, the current state is already much improved :)

**Comment by xmd5a2** [comment]
@l-mb please look at https://github.com/osmandapp/OsmAnd-tools/tree/master/obf-generation/hillshade/V2. I've recently added up-to-date scripts into git.

**Comment by yuriiurshuliak** [comment]
The bug has been fixed. Gap between the tiles is not displayed.

OsmAnd~ 4.7.0#1617m, released: 2024-02-17

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/97f422d7-84b2-49d7-8d50-df1bdc204903"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/d5f3af63-e16b-485f-9bdb-4734e8f54759"  width="300" height="auto"/> </th>
  </tr>
</table>
