### ISSUE TITLE
Regression: Altitude Widget is Broken

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#18998]
I am at a location roughly 500m above sea level, and OsmAnd builds of 2024-01-29 or 2024-01-31 now show this as 49m. A previous build of 2024-01-16 still seems to not have this issue.

**Comment by sonora** [comment]
PS: It"s only the on screen widget. Tapping  on the My Position marker reports correct altitude in the Context card's details.

**Comment by Sonwon1** [comment]
I've noticed the altitude is off by around 50 meters according to signs posted in the mountains. It would be nice if we could add a plus or minus offset to the altitude reading in the settings.

**Comment by sonora** [comment]
> I've noticed the altitude is off by around 50 meters according to signs posted in the mountains. It would be nice if we could add a plus or minus offset to the altitude reading in the settings.

That's a different issue, you may either have to download or de-activate the "World Altitude Correction" map file to fix this. Some chipsets need this, some don't. There is probably also an article in our documentation on osmand.net, I suppose.

**Comment by sonora** [comment]
I think this commit may have broken it: https://github.com/osmandapp/OsmAnd/commit/3aaaa0e78879ed27094ab10957462138a120ab38

**Comment by Rowin63** [comment]
Happens in both versions. The +4.7.1 and also in the ~4.7.0#1559

**Comment by sonora** [comment]
Well spotted, @Chumva ! I had also looked at it but overlooked... 😉

**Comment by Sebf69** [comment]
M'y elevation IS Always a 45m on altitude widget, even if i'm at 1000m or 2000m

**Comment by yuriiurshuliak** [comment]
Please try to update the app or use our [nightly](https://osmand.net/docs/versions/nightly_versions#nightly-builds) version where this should be fixed.
