### ISSUE TITLE
Regression: Custom plugin

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#19000]
### Description

- [x] not showing Plugin Logo

<details>
    <summary>Plugins list</summary>
    <table style="width:100%">
      <tr>
        <td><img width="380" alt="image" src="https://github.com/osmandapp/OsmAnd/assets/44466116/fc3c2ed1-4bbf-43c0-94a7-022906370e9a"> </td>
      </tr>
    </table>   
</details>   

- [x] not showing an image of Plugin description

<details>
    <summary>Plugins Description page</summary>
    <table style="width:100%">
      <tr>
        <td><img width="369" alt="image" src="https://github.com/osmandapp/OsmAnd/assets/44466116/0bf1678d-2e03-439f-ad97-a6e6e65a0731"> </td>
      </tr>
    </table>   
</details>   

- [x] not correct file name on the downloads list

<details>
    <summary>Downloads list</summary>
    <table style="width:100%">
      <tr>
        <td><img width="376" alt="image" src="https://github.com/osmandapp/OsmAnd/assets/44466116/7584f790-cb5d-4ce4-b2a2-a3cc7793f4d2"> </td>
      </tr>
    </table>   
</details>   

### Steps to reproduce

Unzip the Custom plugin:
[US Maps Plugin.osf.zip](https://github.com/osmandapp/OsmAnd/files/14124948/US.Maps.Plugin.osf.zip)
Click on it and open by OsmAnd app 
1. Open Plugins Menu > US Maps Plugin
2. Menu > Download maps > Extra maps > US map data

### Actual result

- Plugin Logo

<details>
    <summary>Plugins list</summary>
    <table style="width:100%">
      <tr>
        <td><img width="380" alt="image" src="https://github.com/osmandapp/OsmAnd/assets/44466116/fc3c2ed1-4bbf-43c0-94a7-022906370e9a"> </td>
      </tr>
    </table>   
</details>   

- image of Plugin description

<details>
    <summary>Plugins Description page</summary>
    <table style="width:100%">
      <tr>
        <td><img width="369" alt="image" src="https://github.com/osmandapp/OsmAnd/assets/44466116/0bf1678d-2e03-439f-ad97-a6e6e65a0731"> </td>
      </tr>
    </table>   
</details>   

- file name on the downloads list

<details>
    <summary>Downloads list</summary>
    <table style="width:100%">
      <tr>
        <td><img width="376" alt="image" src="https://github.com/osmandapp/OsmAnd/assets/44466116/7584f790-cb5d-4ce4-b2a2-a3cc7793f4d2"> </td>
      </tr>
    </table>   
</details>   

### Expected result

- Plugin Logo

<details>
    <summary>Plugins list</summary>
    <table style="width:100%">
      <tr>
        <td><img width="368" alt="image" src="https://github.com/osmandapp/OsmAnd/assets/44466116/447d399d-7a41-49a1-8b65-71854315c5a6"></td>
      </tr>
    </table>   
</details>   

- image of Plugin description

<details>
    <summary>Plugins Description page</summary>
    <table style="width:100%">
      <tr>
        <td><img width="385" alt="image" src="https://github.com/osmandapp/OsmAnd/assets/44466116/9c245777-1a92-472e-95c5-c7fac39678a0"> </td>
      </tr>
    </table>   
</details>   

-  file name on the downloads list

<details>
    <summary>Downloads list</summary>
    <table style="width:100%">
      <tr>
        <td><img width="377" alt="image" src="https://github.com/osmandapp/OsmAnd/assets/44466116/7f900212-95f9-4ee8-a26d-1da390115359"> </td>
      </tr>
    </table>   
</details>   

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.7
Android/iOS version: 14
Device model: S22
Crash-Logs: 
```

**Comment by mariush444** [comment]
as described in https://github.com/osmandapp/OsmAnd/discussions/18959
