### ISSUE TITLE
Incorrect maxspeed for CH:rural in Switzerland

### ISSUE THREAD

**Issue by beatnickgr** [osmandapp/OsmAnd#19009]
### Description

The rural maxspeed in Switzerland is 80km/h as you can see here https://www.mapillary.com/app/?pKey=284515370033865&focus=photo and here https://wiki.openstreetmap.org/wiki/Key:maxspeed#Implicit_maxspeed_values

### Steps to reproduce

Drive in Switzerland on a way with is tagged with maxspeed=CH:rural 

### Actual result

Osmand~ 4.6.12 shows a wrong maxspeed of 90km/h

### Expected result

It should show the correct maxspeed of 80km/h

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
This bug was not reproduced. I tried the navigation simulation on this stretch of road: https://www.openstreetmap.org/way/127788275

The speed limit was 80 kilometers.

OsmAnd~ 4.7.0#1497m, released: 2024-02-02

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/f46435f7-5bb7-4323-af30-9fc14142f9c0"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by beatnickgr** [comment]
This road is tagged as maxspeed=80
I'm updating it now as maxspeed=CH:rural
Please do a live update on your map and try again driving the same segment.

**Comment by yuriiurshuliak** [comment]
Confirmed, the issue has been reproduced. I updated the maps and conducted a navigation simulation on the same road segment; presently, the maximum speed is indicated as 90 kilometers per hour.

OsmAnd~ 4.7.0#1528m, released: 2024-02-05

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/85625e10-daa7-4572-9292-73950f36db44"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by dmpr0** [comment]
Not reproduced with latest maps:

<table style="width:100%">
  <tr>
    <th>Android</th>
    <th>iOS</th>
  </tr>
  <tr>
    <td><img src=""  width="300" height="auto"/> </td>
    <td><img src=""  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by beatnickgr** [comment]
@dmpr0 You say you have live update=off, and this segment was tagged 80 at the time of your last update, 
Better try on that other segment https://www.openstreetmap.org/way/37415960 which was already tagged CH:rural since January (if you have the february update).

**Comment by xmd5a2** [comment]
Map is ready for test

**Comment by yuriiurshuliak** [comment]
Tried to reproduce the issue with live updates enabled. Currently, the maximum speed in this area is 80 km/h, with the indicated fixed speed of 141 km.

OsmAnd~ 4.7.0#1848m, released: 2024-03-16

https://github.com/osmandapp/OsmAnd/assets/127092082/b5429e43-e3e9-4bc4-aaa8-a10f66a113da

**Comment by vshcherb** [comment]
@beatnickgr please test either live maps or full april maps

**Comment by beatnickgr** [comment]
Working perfectly in April! Thanks!
