### ISSUE TITLE
Showing GPX tracks: speed and/or height

### ISSUE THREAD

**Issue by trapicki** [osmandapp/Osmand#1900]
I really like the feature to show a recorded GPX track and get marks for distance or elapsed time.

What I currently miss is information about speed or height. 

Speed and height may be not so easy to show as distance or time because they are non-monotone, and it's not trivial to decide when to show a mark for speed. When it chanced a certain amount? I have no good idea.

One thing that could work would is color coding speed or height. The color of the track is not fixed, but every segment is colored by according speed or height value. Maybe both height and speed can be visualized, painting the left half oft the track for speed, the right for height. If still a color is needed to tell different tracks apart, an outline of a fixed color could be used.
Something like https://mycarta.wordpress.com/color-palettes/ would be a color palette to differentiate even small changes.

With speed, maybe some filtering is necessary when point distances are in the range of the accuracy. I noted that my phones position solution is sometimes jumping, and as speed is the ratio if distance per time, this could result in jolty speed results. Maybe some smoothing will help in that case, but of course that needs testing.

**Comment by sonora** [comment]
For a simpler solution: Maybe we could just make the selected GPX interval marks tappable, and upon tapping one the new context bubble shows up which displays all the details about the past interval?

This would be MUCH less intrusive for all other users preferring a simple display over "rainbows" on the screen ..  ? :-)

**Comment by trapicki** [comment]
* My point is about having the speed/height information of the whole track or parts of it continuously. 
* I do not propose to force that on everyone, that would not be an improvement. An option additional to a fixed color would be maybe fine.
* @sonora's suggestion could be added any way, independently. Having all kind of details in written text to a very point of a track would in deed be very interesting.

**Comment by cepesko** [comment]
talking about gpx speed: 
The information on recorded gpx show average speed and max speed, but only calculated time per preset distance (e.g. 12 minutes/km). Could the display also show the more widespread calculation in mph or km/h (5 km/h)?

**Comment by sonora** [comment]
Looks like no action planned here for now.
