### ISSUE TITLE
Pedestrian routing issue

### ISSUE THREAD

**Issue by letypequividelespoubelles** [osmandapp/OsmAnd#19003]
### Description

When I try to create a (pedestrian) route from [here](https://www.openstreetmap.org/node/1569131277) to [here](https://www.openstreetmap.org/node/1538718989), OsmAnd creates a route where I'm supposed to cross the road somewhere between [this point](https://www.openstreetmap.org/node/1569123697) and [this point](https://www.openstreetmap.org/node/3130906078). Bute there are no pedestrian crossing between thos two points. It should create a route and make me cross [here](https://www.openstreetmap.org/node/4430187776). OSRM and GraphHopper create expected route.

### Steps to reproduce

Create the route between given point.

### Actual result

cf description

### Expected result

cf description

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.6.11
Android/iOS version: FDroid
Device model: 
Crash-Logs: ?
Map of the 01/01/2024 + live update
```

**Comment by scaidermern** [comment]
For reference:
* OSRM: https://www.openstreetmap.org/directions?engine=fossgis_osrm_foot&route=45.56384%2C5.91538%3B45.56415%2C5.91559#map=19/45.56402/5.91530
* GraphHopper: https://www.openstreetmap.org/directions?engine=graphhopper_foot&route=45.56384%2C5.91538%3B45.56415%2C5.91559#map=19/45.56401/5.91529

The road (https://www.openstreetmap.org/way/445619717) has `sidewalk=*` tags. So it would be nice if OsmAnd could respect them and try to cross the road where crossings are mapped (here: https://www.openstreetmap.org/node/4430187776). There is an old ticket for this: #2567.

However, OSRM nor GraphHopper don't do this either.

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. If you select a pedestrian profile and create a route from coordinates 45.56384, 5.91538 to 45.56404, 5.91543, the route will be built along a path where there is no pedestrian crossing, as illustrated here: [link to map path](https://www.openstreetmap.org/way/835789149). Ideally, the route should traverse this designated crosswalk: [crosswalk link](https://www.openstreetmap.org/node/4430187776).

For the web version, click [this link](https://www.osmand.net/map/?start=45.563840,5.915380&finish=45.564040,5.915430&type=osmand&profile=pedestrian#19/45.56399/5.91534).
To access OpenStreetMap, follow [this link](https://www.openstreetmap.org/directions?engine=fossgis_osrm_foot&route=45.56384%2C5.91538%3B45.56405%2C5.91543).

OsmAnd~ 4.7.0#1537m, released: 2024-02-06

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/f83536b2-c071-44ea-a4dc-e76642b30cc6"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
Suggested route is allowed for pedestrian but it has a cost 167 instead of 135. I suspect due to roundabout
![Screenshot 2024-02-08 at 19 14 16](https://github.com/osmandapp/OsmAnd/assets/1042025/911e4845-6689-41d7-948a-6ded52709674)

If we talk about this crossing https://www.openstreetmap.org/node/4430187776 than it's simply not possible today cause the graph needs to be split in 2 parts left sidewalk and right sidewalk which will be very confusing even to indicate without separate lanes.

I think it's a long running issue which not possible to fix
