### ISSUE TITLE
Android Auto refresh rate drops significantly if OsmAnd+ UI is displayed on the phone's screen

### ISSUE THREAD

**Issue by mdykierek** [osmandapp/OsmAnd#19014]
### Description

If phone's screen is on and OsmAnd+ UI is shown the car's display refresh rate is bad.
It is very significant in the night mode when some frames or their parts are plain black.
When the phone display is off, the refresh rate is back to normal.

### Steps to reproduce

Connect Android Auto
Open OsmAnd+ and specify a route with a couple of intermediate stops and start navigation.
Put the phone aside (the display remains on). 

### Actual result

The map refresh is bad.
Turn the phone display off - the refresh is back to normal. 

### Expected result

There should be no refresh rate difference whether display is on or off. OsmAnd does not show map anyway.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.6.13
Android/iOS version: 13 / Android Auto 11.1.640234
Device model: Moto Edge 40 Pro / Toyota Corolla 2021
Crash-Logs: ?
```

**Comment by DmitryAlexei** [comment]
OsmAnd 4.7.17, released: 2024-05-07 Samsung Galaxy Note 20 ultra.
I simulated navigation for 0.5 hour when the screen of the phone was on and off, and I didn't notice a significant difference in rendering. 
It seems, that huger impact on rendering has map details (menu > configure map > map details (hide)) on a different parts of the route. Also see my comment in very similar issue https://github.com/osmandapp/OsmAnd/issues/18894#issuecomment-2078304152
Need to mention, that after ~5-10 min of navigation, the phone became very hot, no matter if the screen was on or off. Thus, it is possible that the phone's processor starts to work worse after some time since the start of navigation (CPU throttling)

**Comment by mdykierek** [comment]
How does one simulate navigation with Android Auto? I could try.
What I meant is:
1. When phone does not display OsmAnd+, then the refresh rate on car's display is bearable
2. When the phone display is on and OsmAnd+ interface is displayed (with information that you should watch car's display), then it updates rarely. The map "jumps" like it was twice or more less frequent.
It has nothing to do with heating. It slows down immediately and comes back to normal when OsmAnd+ is not displayed (in background) or the phone's display is off.

**Comment by DmitryAlexei** [comment]
@mdykierek Does the behavior you described apply to the latest version from the Google Play?

**Comment by mdykierek** [comment]
Yes.

**Comment by mdykierek** [comment]
> OsmAnd 4.7.17, released: 2024-05-07 Samsung Galaxy Note 20 ultra. I simulated navigation for 0.5 hour when the screen of the phone was on and off, and I didn't notice a significant difference in rendering. It seems, that huger impact on rendering has map details (menu > configure map > map details (hide)) on a different parts of the route. Also see my comment in very similar issue [#18894 (comment)](https://github.com/osmandapp/OsmAnd/issues/18894#issuecomment-2078304152) Need to mention, that after ~5-10 min of navigation, the phone became very hot, no matter if the screen was on or off. Thus, it is possible that the phone's processor starts to work worse after some time since the start of navigation (CPU throttling)

I am observing this heat issue and plan on reporting a separate issue for that. I already compared OsmAnd+ rendering on car display via Android Auto with the same for Google Maps and Sygic. Now taking temp measurements. As much as I love the app, I hate to admit that it tends to fry the battery.

**Comment by vshcherb** [comment]
Actually no plan on this cause we're going to drop for AA refresh rate to 30FPS to consume less batter though will try to keep it smooth. We have separate task about energy consumption for AA

**Comment by vshcherb** [comment]
Then it's not reproduced, with latest changes on all 3 cars we have - we don't see slow FPS (40-50FPS), actually we see only high energy consumption

**Comment by mdykierek** [comment]
I'll try to film this. I am really not referring to FPS. It is more like user experience thing. It seems like it jumps by bigger distance than when OsmAnd is not shown on the phone's screen.

**Comment by mdykierek** [comment]
Filmed today with 4.8.4.
Note that when I unlocked the phone with OsmAnd+ on the display (foreground), the view starts to scatter. The unlock happens by the parking, about 5 seconds into the video, 13.5 km from the manouver. Note the little circle that appears over the arrow and then disappears. It looks like it skips several frames.
I hope now it's clear what I meant all the time.

https://github.com/user-attachments/assets/2adad45d-77f1-4962-9756-98bf5f3ca5ac

**Comment by mdykierek** [comment]
1. I don't know where the location comes from, but it happens when I am roaming or not. If I am in flight mode or not.
2. There seems to be a regression with location on the 4.8.6. There are random messages with GPS signal lost. Usually right after I start driving, so I have to stop, unlock the phone, display OsmAnd on the phone or start the navigation from car's display again. I happens also, at random points of the drive. No pattern yet.

**Comment by vshcherb** [comment]
Yes, I know that's why we're updating with nightly build. In 4.8.6 Android randomly disallow restart background service (each 2-3 run) so we are looking for workaround and in nightly it works differently
