### ISSUE TITLE
Turn assist should show all appropriate lanes

### ISSUE THREAD

**Issue by mdykierek** [osmandapp/OsmAnd#19015]
### Description

In the below situation both left and the middle lanes should be highlighted for turning left.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/27214784/08246a78-5711-4bba-a033-2fbea3628db4"  width="300" height="auto"/> </th>
  </tr>
</table>

### Steps to reproduce

Navigate from this road https://www.openstreetmap.org/way/215636691 left.

### Actual result

In the image provided in the description.

### Expected result

Both left and the middle lanes should be highlighted.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.6.13
Android/iOS version: 13
Device model: Moto Edge 40 Pro
Crash-Logs: ?
```

**Comment by Sonwon1** [comment]
I would add if the next turn is another left very soon after this turn that it should direct you into the far left lane.

**Comment by mdykierek** [comment]
In my case, it was straight ahead as shown in the picture.

**Comment by Sonwon1** [comment]
> In my case, it was straight ahead as shown in the picture. It is not that easy, it has to take into consideration the turn lanes.

Yes, I was just trying to insert some intelligence into the lane directions.

**Comment by yuriiurshuliak** [comment]
As per the data available on OpenStreetMap, the current mapping of intersections is as follows:

left | through; left
left | through

For additional details, you can explore the mapping information at these locations:
[Link 1](https://www.openstreetmap.org/way/215636698)
[Link 2](https://www.openstreetmap.org/way/95291285)

If there is missing information or if you spot any errors, feel free to contribute by registering on openstreetmap.com and rectifying the issues. Further guidance is available in the [Beginner's Guide](http://wiki.openstreetmap.org/wiki/Beginners_Guide_1.3).

**Comment by mdykierek** [comment]
Please review your screenshot on the left. The left turn is allowed from both the left and the middle lane. Only the left is higlihgted in green - should be both the leftmost and the middle with the left arrow in green.
Believe me I know this intersection well. See the OSM history and you'll see that I made it right.

**Comment by mdykierek** [comment]
I updated the link between the lanes on Bytomska to be left|through;left and checked the lane guidance after live update.
Now it shows middle then right lane only, which actually is much better (yet the description still applies - it should allow the left lane too).

**Comment by yuriiurshuliak** [comment]
I checked again on the release version and with live updates, everything is the same.

OsmAnd 4.7.1, released: 2024-02-06

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/1c6398ed-d378-4589-8c41-a12857edb43d"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/2a473465-1f4d-460e-82b5-ecae0a3a4cca"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by mdykierek** [comment]
I think you failed to live update. Mine is:
![Screenshot_20240209-133042](https://github.com/osmandapp/OsmAnd/assets/27214784/fa932b25-3bfb-4c7f-926a-edcd00a2b857)
![Screenshot_20240209-133108](https://github.com/osmandapp/OsmAnd/assets/27214784/b6d57db0-7ea4-4172-b3e1-1a80508d711a)

**Comment by yuriiurshuliak** [comment]
With live updates, turn lanes may not work correctly. In this case, it is better to wait until the next map update, and check again.

**Comment by yuriiurshuliak** [comment]
I rechecked with live updates, it has been observed that the turn lanes continue to exhibit the same behavior, showing the middle and right lanes only when the left lane should also be allowed. This is noteworthy, as the modification of tags was expected to result in the lanes displaying according to the provided description.

OsmAnd~ 4.7.0#1698m, released: 2024-02-28

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/e598c1f9-d71f-425a-b5f3-aaa177f958c1"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/acdb054d-c736-414d-9912-b7ad4c64275b"  width="300" height="auto"/> </th>
  </tr>
</table>
