### ISSUE TITLE
There is no display of turn lanes when driving along a route (Car profile).

### ISSUE THREAD

**Issue by jolaae** [osmandapp/OsmAnd#19017]
### Description

The bug is reproduced only when actually moving along the route! If you drive without routing, then the traffic lanes are shown normally.

### Steps to reproduce

Try to actually drive (without simulation) on any route where there are turn lanes. They will not be displayed.
top control panel: 1. line: lane assistent, 2. line: Map marker bar, 3. line: Strett names
transparent widgets
car profil

### Actual result

Lane assistent widget is not be displayed

### Expected result

It is necessary for turn lanes to be displayed when driving along a route.

### Your Environment (required)

OsmAnd Version: 4.6.13 published 2024-01-19
Android/iOS version: 14
Device model: Google Pixel 7+
Crash-Logs: no

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/113899038/ed73d49a-33ef-49d0-a169-bbd23215d778"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/113899038/c0e06fcb-41e4-41bb-b619-8e43626e8e50"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/113899038/5932d303-6094-48ce-8e2b-a9ae54e5da17"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/113899038/d0084376-aebf-48f7-ae55-e4f792e72b7c"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
@jolaae if you are driving along a .gpx track, please use *[Attach to roads](https://osmand.net/docs/user/navigation/setup/gpx-navigation#attach-to-roads)* option.

**Comment by jolaae** [comment]
Dmitry, attach to roads has no influence, I checkt it and maybe there is a misunderstanding about the issuses lane assistants yourside.

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. I have tried to reproduce the bug in the two locations mentioned above. Lanes widget works correctly. 

Here are the coordinates:
52.09879029986951, 9.35078692599729

52.08753321323644, 9.347890629493625

OsmAnd~ 4.7.0#1549m, released: 2024-02-07

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/1695c62c-a890-49ca-9096-086d803d0170"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/0cce8f55-c86e-43d0-8f9c-41b97221d1c6"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by jolaae** [comment]
Oh, you use a different version of osmand.   The currently version I had is 4.6.13. released 2024.01.19.Can you try it with the released version?Is you version a nightly build?Regards JosefAm 07.02.2024 17:19 schrieb yuriiurshuliak ***@***.***>:
The bug was not reproduced. I have tried to reproduce the bug in the two locations mentioned above. Lanes widget works correctly.
Here are the coordinates:
52.09879029986951, 9.35078692599729
52.08753321323644, 9.347890629493625
OsmAnd~ 4.7.0#1549m, released: 2024-02-07
photo_2024-02-07_17-52-12.jpg (view on web) photo_2024-02-07_17-52-14.jpg (view on web)

**Comment by Guylby** [comment]
Can the missing directions be reproduced by introducing a reroute at the start of the trip ? (this is maybe why the bug only shows on a real trip and not in a simulation with a "perfect" tracking).

**Comment by jolaae** [comment]
I check the lane assistants too condition. 1. In a real navigation and 2. In a simulation. The lane assistant not displayed as I  wrote. I think, in the meantime in a further Version the bug is solved. For me it's interesting, since witch working version is it solved and when osmand will release an official version without this bugAm 08.02.2024 09:48 schrieb Guylby ***@***.***>:
Can the missing directions be reproduced by introducing a reroute at the start of the trip ? (this is maybe why the bug only shows on a real trip and not in a simulation with a "perfect" tracking).

**Comment by yuriiurshuliak** [comment]
You are right, I used the nightly version. However, I have now tried to reproduce this problem on release version 4.6.13 and also failed to reproduce this bug. 
Try reinstalling the app. Reinstallation should clear any incorrect data in the app. Before reinstalling, please back up all your personal data such as tracks and favorites. You can do this by going to Menu > Settings > Export to file.

Also please check how it works in the nightly build: https://osmand.net/docs/versions/nightly_versions#nightly-builds

OsmAnd 4.6.13, released: 2024-01-19

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/605cf678-a984-4b6f-a79e-36f46eda10cf"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/7cba0f49-9a4a-4d4e-88cb-4bae0af8df9c"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by jolaae** [comment]
Hello Osmand support team, I uninstalled and reinstalled my Osmand 4.6.13. 

Unfortunately, Lane Assist does not appear even after reinstallation. 

 

With the installation of the nigtly build, the lane assistant is visible and shows the turns... 

Unfortunately, this still does not solve the issue satisfactorily. 

 

Von: yuriiurshuliak ***@***.***> 
Gesendet: Dienstag, 13. Februar 2024 16:53
An: osmandapp/OsmAnd ***@***.***>
Cc: jolaae ***@***.***>; Mention ***@***.***>
Betreff: Re: [osmandapp/OsmAnd] There is no display of turn lanes when driving along a route (Car profile). (Issue #19017)

 

You are right, I used the nightly version. However, I have now tried to reproduce this problem on release version 4.6.13 and also failed to reproduce this bug.
Try reinstalling the app. Reinstallation should clear any incorrect data in the app. Before reinstalling, please back up all your personal data such as tracks and favorites. You can do this by going to Menu > Settings > Export to file.

Also please check how it works in the nightly build: https://osmand.net/docs/versions/nightly_versions#nightly-builds

OsmAnd 4.6.13, released: 2024-01-19


photo_2024-02-13_17-40-08.jpg (view on web) <https://github.com/osmandapp/OsmAnd/assets/127092082/605cf678-a984-4b6f-a79e-36f46eda10cf>  

photo_2024-02-13_17-40-10.jpg (view on web) <https://github.com/osmandapp/OsmAnd/assets/127092082/7cba0f49-9a4a-4d4e-88cb-4bae0af8df9c>

**Comment by jolaae** [comment]
Update

1.	In the meantime, I was able to make the lane assistant visible through various tests/measures in the current version 4.6.13. 1. Measure: Data/settings exported from nightly Build 4.7.0#1549m and imported into the current version 4.6.13. This meant that the lane assistant was visible again, as it was in the nightly build version. After adjusting the settings according to my ideas and needs, the lane assistant was no longer available. I think the main cause of Lane Assist disappearing was the adjustment of the top panel display. Even through a variety of configurations, the lane assistant remained missing. 
2.	The wizard was visible again using the “Reset to default” function in the “Configure display” menu. As soon as I changed the configuration back to my needs in the various control panels, the assistant disappeared again.
3.	Another unexpected influence is the navigation setting. If I switch the navigation type from offline to online (car), the lane assistant no longer appears. After switching back to offline, the lane assistant appears again as expected. 

 

I hope these tips give your software developers tips to improve the software and make it more stable.

 

Von: yuriiurshuliak ***@***.***> 
Gesendet: Mittwoch, 14. Februar 2024 14:48
An: osmandapp/OsmAnd ***@***.***>
Cc: jolaae ***@***.***>; Mention ***@***.***>
Betreff: Re: [osmandapp/OsmAnd] There is no display of turn lanes when driving along a route (Car profile). (Issue #19017)

 

It is interesting. Please provide a short video of how you start the navigation simulation.
Also, please try the point-to-point navigation simulation without a previous track. For example, from this point 52.09879376814375, 9.350783855797442 to this point 52.08482875841091, 9.3528591695627

**Comment by jolaae** [comment]
In the meantime I have deleted some test *.osf, because I now have a state in which the lane assistant and further personalization is ok for me. 

- Export_2024-02-16 is ok 

- Export_2023-02-19 is probably the parameterization in which the lane assistant does not work. 

 

I hope that I was able to help you with this

 

Von: yuriiurshuliak ***@***.***> 
Gesendet: Freitag, 16. Februar 2024 17:09
An: osmandapp/OsmAnd ***@***.***>
Cc: jolaae ***@***.***>; Mention ***@***.***>
Betreff: Re: [osmandapp/OsmAnd] There is no display of turn lanes when driving along a route (Car profile). (Issue #19017)

 

Kindly share your profile settings to facilitate bug testing using your specific configurations. The most convenient method is to export your profile, including all necessary information. Navigate to Menu → Settings → Export, and choose the data you wish to export.

**Comment by yuriiurshuliak** [comment]
If you have specific files related to the issue, please consider uploading them directly to the GitHub repository. Unfortunately, GitHub does not support file attachments via email.

**Comment by jolaae** [comment]
Sorry, I tryed to upload des profil backup, but I did’t found to do it.

I red the hepldesk and create a repository.  Did not found a button to upload files.

Mybe I need a bit more help.

 

Von: yuriiurshuliak ***@***.***> 
Gesendet: Montag, 19. Februar 2024 15:02
An: osmandapp/OsmAnd ***@***.***>
Cc: jolaae ***@***.***>; Mention ***@***.***>
Betreff: Re: [osmandapp/OsmAnd] There is no display of turn lanes when driving along a route (Car profile). (Issue #19017)

 

If you have specific files related to the issue, please consider uploading them directly to the GitHub repository. Unfortunately, GitHub does not support file attachments via email.

**Comment by yuriiurshuliak** [comment]
Upload the previous files directly to the GitHub repository. To facilitate the file attachment process, please follow the guide provided in this link: [Attaching Files on GitHub](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files).

**Comment by jolaae** [comment]
It is not pssible upload export_xxx_.osf files.

 

Von: yuriiurshuliak ***@***.***> 
Gesendet: Donnerstag, 22. Februar 2024 10:41
An: osmandapp/OsmAnd ***@***.***>
Cc: Lane Assistent ***@***.***>; Mention ***@***.***>
Betreff: Re: [osmandapp/OsmAnd] There is no display of turn lanes when driving along a route (Car profile). (Issue #19017)

 

Upload the previous files directly to the GitHub repository. To facilitate the file attachment process, please follow the guide provided in this link: Attaching Files on GitHub <https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files> .

**Comment by mikehgentry** [comment]
You have to rename them.

This profile will never show the lanes widget on my device (XCover 4s) as far as I can tell.

[Export_2024-02-24.zip](https://github.com/osmandapp/OsmAnd/files/14391873/Export_2024-02-24.zip)

**Comment by yuriiurshuliak** [comment]
It appears that the issue you're experiencing with the lanes widget may be related to the use of BRouter. The lanes widget might not be supported when using BRouter for routing. Please try to download the route, attach the downloaded route to the road. Ensure that the route is calculated.

**Comment by jolaae** [comment]
Sorry, I haven't used broute so far. All route and tracks have been created and tested with OsmAnd-App. 

 

Lane Assist does not appear when the navigation mode is switched from offline to online. (https://zlzk.biz/). 

I didn't test the online demo version of OsmAnd (https://routing.openstreetmap.de/). 

 

If this is feasible for you, an instruction should be given in the help for the online routing of OsmAnd so that the user is informed.

 

 

Von: yuriiurshuliak ***@***.***> 
Gesendet: Montag, 26. Februar 2024 14:51
An: osmandapp/OsmAnd ***@***.***>
Cc: Lane Assistent ***@***.***>; Mention ***@***.***>
Betreff: Re: [osmandapp/OsmAnd] There is no display of turn lanes when driving along a route (Car profile). (Issue #19017)

 

It appears that the issue you're experiencing with the lanes widget may be related to the use of BRouter. The lanes widget might not be supported when using BRouter for routing. Please try to download the route, attach the downloaded route to the road. Ensure that the route is calculated.
