### ISSUE TITLE
"switched off" waypoints contained in tracks are always set back to be "on display" again...

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#19010]
### Description

Many of my tracks contain waypoints (like the TETs sections e.g.). I dont like to see them always (it fills up the map). But unfortunately there is no global setting "waypoints in a track > "off", like "favorits on or off". 
So for every single track I have to do: tap the diplayed track>points>3dots>display on map "off">exit (three times "back", there is no "exit" or "finish" option) So thats at least 7 actions per track. 30 tracks in a folder, a lot to do. 

Now going to "configure map > tracks" and select just one more track (any, does not have to from the same folder) to be on display, brings back all those just "switched off" points again on display! 

So >>> starting over from the beginning...   

A global funcion to switch them on or off would be nice, but at least they should remain switched off once they are switched off.

### Steps to reproduce

pls try as described

### Actual result

swiched off points are back on display again

### Expected result

switches off points should remain switched off

### Your Environment (required)

OsmAnd Version: +4.7.0
Android/iOS version: 13
Device model: S20+

**Comment by mariush444** [comment]
But global switch off is not solution. I preffere "should remain switched off once they are switched off" because thrre are tracks that contain groups of point. Many times I switch off 17 from 20. So global it is not a solution. It should be remembered.

**Comment by mariush444** [comment]
Probably, the best solution is to add on/off info in osmand's extention tag in gpx

**Comment by Rowin63** [comment]
everytime you switch one track "display on map" off and an again, all the disabled point come back again...

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced.  When you disable the waypoints display for the initial track and subsequently enable the 'Show on map' for the second track, the waypoints revert to the first track.

OsmAnd~ 4.7.0#1549m, released: 2024-02-07

https://github.com/osmandapp/OsmAnd/assets/127092082/d146dbe2-ed55-4c87-9596-fd448a64c714

**Comment by dmpr0** [comment]
## ToDo
- [ ] Save group visibility status. (Similar to favorites)

**Comment by yuriiurshuliak** [comment]
The bug has been fixed. When turning off the display of waypoints for one track, after displaying another track, the waypoints do not return to the first track.

OsmAnd~ 4.7.0#1841m, released: 2024-03-15

https://github.com/osmandapp/OsmAnd/assets/127092082/e9e182f8-457e-4e4e-ba2d-1363a6cf4bd5
