### ISSUE TITLE
Width of the GPX track is not rendered correctly

### ISSUE THREAD

**Issue by smirnov-d-a** [osmandapp/OsmAnd#19020]
### Description

The issue arises when a GPX track is first opened with the map zoomed out, so that the displayed area is larger than (or equal to) that of the track's bounding box - the track is then rendered noticeably thinner than expected. Should any other tracks be opened after that, they will also be rendered thin regardless of zoom level when opening them. This behaviour can be reset by closing OsmAnd (removing it from cached processes) and starting again.

If the first track is opened on a zoomed in area lesser than the track's bounding box, then it is rendered with correct width, and all other subsequently opened tracks are also rendered correctly.

Opening a track via _Main menu - Tracks_ or _Configure map - Tracks_ doesn't make a change.

### Steps to reproduce

1. Start OsmAnd
2. Zoom out of the area of the track to be opened
3. Open the track via _Main menu - Tracks_ or _Configure map - Tracks_

### Actual result

The track is rendered thinner than expected (the track width is set to **Medium** beforehand).

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/27347991/c44cd760-3820-48c6-94aa-16d593c17543"  width="300" height="auto"/> </th>
  </tr>
</table>

### Expected result

The track is rendered with correct width.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/27347991/d65e6442-d902-425d-90c2-e052d0a854d7"  width="300" height="auto"/> </th>
  </tr>
</table>

### Your Environment (required)

OsmAnd Version: 4.6.13 (though the issue was observed at least since 4.5.10)
Android version: 14
Device model: Samsung Galaxy S21 FE 5G

**Comment by yuriiurshuliak** [comment]
I could not reproduce this bug. Please describe the steps in more detail and attach a video of how you reproduce it from your end.

**Comment by smirnov-d-a** [comment]
Here's the video.
First I open the track while zoomed out - the track is therefore rendered thin. Then, after hiding the track, I close OsmAnd (closing is essential here to reset the behaviour) and start it again, this time opening the track while zoomed in - the track is rendered visibly thicker (which is how it should be). Compare the width or the track at **0:30** and **1:00** (zoom ruler is 500 m) OR at **0:21** and **1:06** (zoom ruler is 5 km).
https://github.com/osmandapp/OsmAnd/assets/27347991/17e0ee37-0409-43b8-bb83-ae96618ab817

On this video I opened the track via _Show tracks_ hot action button for the sake of quickness, but the method does not matter, be it _Show tracks_ button, or _Main menu - Tracks_, or _Configure map - Tracks_ menu, as I mentioned above.

**Comment by zipav** [comment]
OsmAnd Nightly 4.7.0#1633m, released: 2024-02-20

Only reproduced, however, if a semi-transparent track colour is selected.

https://github.com/osmandapp/OsmAnd/assets/123936521/e3904a83-b71d-4d80-b758-f02aca03a8e8


https://github.com/osmandapp/OsmAnd/assets/123936521/da53a393-171f-4a60-96a1-0fcdcdadf156

**Comment by dmpr0** [comment]
Not reproduced

**Comment by vshcherb** [comment]
Let's see if we get something similar reported, unfortunately we didn't manage to reproduce
