### ISSUE TITLE
No announcements when on motorway

### ISSUE THREAD

**Issue by ReinerMeyer** [osmandapp/OsmAnd#19025]
### Describe the routing engine used (required)

- [ X] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Describe your routing Profile (required)

I used the car profile

### Describe your start and end points (required)

Dear service experts,
on 29.1.2024 I once again had the problem that the route announcement via voice was incomplete.
Please find attached the droven route as gpx file. The destination for the route calculation was: L4142 (N47.69560° E16.10736°).
I started in the parking garage in Wiener Neustadt. I had to leave the parking garage in a downward spiral over 3 floors. The route was recalculated several times before leaving the parking garage.
From leaving the parking garage to the highway entrance to Graz, the announcements were correct.
When entering the highway, the announcement was: "Follow the road to the L141."
I had already wondered, because I had to leave the highway at Seebenstein and I expected a corresponding announcement - which usually happens.
In fact, this instruction to leave the highway and further instructions that should have followed until the junction of the L141 from the federal highway B54 did not exist.
After that, the instructions up to the destination were correct again.

This incomplete route instruction did not happen only once. In the meantime I used OSMAND further 3 times with the same problem. In each case I used the motorway as part of the route and the problem seems to come up only for this part of the calculated route (no announcements when changing the motorway (from A2 to S6) or leaving the motorway).

Unfortunately, I don't know the reason. May-be this is a problem of fine tuning of the car profile. But I cannot remember that I changed parameters actively.
What else could it be? Can you help me to fix this problem?

Regards
Reiner
[2024-01-29_10-40_Mon.zip](https://github.com/osmandapp/OsmAnd/files/14164532/2024-01-29_10-40_Mon.zip)

### Describe the actual route (required)

starting in a park garage in Wr. Neustadt - driving to motorway A2 - using motorway A2 - leaving at exit "Seebenstein" - using other streets to come to the destination in Lindgrub

### Describe the expected route (required)

I know the route and it was the route what OSMAND suggested, but there were no announcements for staying at the left lanes were the S2 branches at the right site, no announcing the exit for Seebenstein, no announcement the drive on the B54. The first announcement thereafter was to keep right onto the L141

### Describe what Maps you used (online or offline) (required)

- [X ] Offline maps offered within the OsmAnd app for download. 
- [ ] Online (tile / raster) maps 
I used the offline map of Austria

### Your Environment (required)

```
OsmAnd Version: OSMAND+ 4.6.13
Android/iOS version: ONE-UI 5.1, Android Version 13
Device model: Samsung XCover 5, Modell name: SM-G525/DS
```

**Comment by yuriiurshuliak** [comment]
If you used this gpx track for navigation, please try using the [Attach to roads](https://osmand.net/docs/user/navigation/setup/gpx-navigation#attach-to-roads) option.

**Comment by ReinerMeyer** [comment]
Hi,
I'm sorry that I made wrong assumptions based on the information provided.
I did not use a track for navigation but a POI. I have mentioned this POI with exact geodata in my text. The track provided is the recorded track of the route driven, which is identical to the planned route.

In the meantime I had reset the car profile to see if it gets better. Unfortunately, no.
I then uninstalled OSMAND+ and reinstalled it. I'll have to try that out first.
If the reinstallation doesn't help either, I'd like to try the previous version of 4.6.13. Because this undesirable behavior of OSMAD+ only occurs after an automatic update in mid-January. How can I get the previous version?
Reiner

**Comment by ReinerMeyer** [comment]
So, I tested the vocal announcements after deinstallation and reinstallation. And I'm frustrated. This procedure doesn't come back to the correct announcments what I experienced till mid of January.
Any other idea what could have been caused this bug or misbehavour?
Reiner

**Comment by Guylby** [comment]
I think you've encountered the same issue as me: #18824

I've narrowed down the cause to the Smart Route Recalculation setting. It's what is causing the missing highway directions after a reroute. But there's another bug where you cannot turn it off through the UI toggle, but there's a few workarounds I've found:

- Add an intermediary step on your trip towards the end (or just before the last highway exit), Smart Route Recalculation doesn't work with intermediary destinations so the bug won't appear (but reroute calculation time will be longer).
- Or manually edit the routing.xml file to disable smart route recalculation (this is what I did personnally while waiting for a fix).

**Comment by ReinerMeyer** [comment]
Many thanks for the videos. Of the 6 videos that reflect the critical parts of the route, I did not receive the instructions as heard in videos IMG_4758.2.MOV and IMG_4759.MOV.
These dropouts only occur when the instructions are on the highway=motorway or highway=link. All instructions until entering the motorway and after exiting the motorway or motorway-link are still correct. This has been happening regularly since January (now about 5 times, every time on other routes, where motorways or there links are involved).

Even completely uninstalling and reinstalling OSMAND+ did not change anything.

How can I record such videos to demonstrate this suspicious behavior?
How can I see the list of instructions like on your first picture?

**Comment by ReinerMeyer** [comment]
Today I tested 2 variants for calculating the same route.
Variant 1: Start "My position" - Destination "Dammgasse, Wartmannstetten"
Variant 2: Start "Hirtenberger Straße, Leobersdorf" - Destination "Dammgasse, Wartmannstetten"
Note: "Hirtenberger Straße, Leobersdorf" is 945 m away from "My position", but on the route of variant 1.
In variant 2 there are 2 additional "Turn-by-turn information" (see attached pictures).

So, I have the turn-by-turn problems if I use "My position" as the start, which is the normal case.
How is the start selection "My position" related to the missing "Turn-by-turn" instructions - only concerning the highway?
[Variants.zip](https://github.com/osmandapp/OsmAnd/files/14318575/Variants.zip)

**Comment by ReinerMeyer** [comment]
On February 20 and 21, I once again carried out 3 routes where a part of the streets was highway=motorway.
Fortunately, the route instructions work correctly again, as I was used to before entering this issue.
I have no explanation for how the problem was solved.
Has something been fixed in the app in the meantime and was the app updated in the background on my smartphone?
Or did I change something in the settings without knowing why? In the meantime, I have not only carried out the two route variants (see above), but also tried "Plan route" as an alternative. Unfortunately, I don't know what the connection is to the elimination of the problem. I can only hope that the problem does not occur again.

**Comment by ReinerMeyer** [comment]
When there is no further comment to explain the background for this issue I suggest to close this issue.

**Comment by vshcherb** [comment]
Well I will close as we can't proceed it for it now. Anyway once we have more other cases we can always reopen it.
