### ISSUE TITLE
Flooded map in El Harrach, Algeria.

### ISSUE THREAD

**Issue by Yakoobb** [osmandapp/OsmAnd#19035]
### Description

When attempting to zoom in on the Al-Harrach region in Algiers, and surrounding areas, I have noticed a significant issue with the map display. Upon zooming in, the color of the map changes to blue, rendering it difficult to navigate and understand the geographic layout of the area accurately.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/159156098/5628eddd-7dc7-45e7-b4f6-a00e06e42ece"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/159156098/dd121a82-7d2a-426d-ba60-a82fbea620e8"  width="300" height="auto"/> </th>
  </tr>
</table>

### Steps to reproduce

1. Open the Osmand application.
2. Navigate to the Al-Harrach region in Algiers.
3. Attempt to zoom in on the map.

### Actual result

Upon zooming in, the map color changes to blue, making it challenging to discern landmarks, roads, and other essential geographic features accurately.

### Expected result

The map should smoothly zoom in, maintaining its original color scheme and providing clear geographic details of the Al-Harrach region and surrounding areas.

### Your Environment (required)

Operating System: [Android 12, 13]
Osmand App Version: [Osmand / Osmand+ 4.6.13]
Device Model: [Samsung Galaxy F13, Redmi Note 10 Pro]
Connection Type: [Wi-Fi, Mobile Data]

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. Follow these coordinates 36.72058709381326, 3.137639931115084 and note that the area was flooded.

OsmAnd~ 4.7.0#1549m, released: 2024-02-07

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/f6be5936-7643-486b-86f5-a20ae868c246"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/bfb9c106-b60e-4b05-b4b5-d97a598171e0"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by dmpr0** [comment]
<table style="width:100%">
  <tr>
    <th>Android</th>
    <th>iOS</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/ba0865de-41eb-4a1b-bb54-d975174424ad"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/38a4979d-22fc-458b-bfde-9963012fb1e4"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.7.0#1857m, released: 2024-03-18 Cannot be reproduced any more.

<details><summary> 36.72058709381326, 3.137639931115084 </summary>
<video src="https://github.com/osmandapp/OsmAnd/assets/116079541/ed6b9798-ad86-4a4c-9f45-46cf49222efc"></video>
</details>
