### ISSUE TITLE
Improve "Apply sorting order to all subfolders – Tracks"

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#19048]
Following improvement suggestion:

We now have 2 strangely separated mechanisms to sort the Tracks list items, a rather discoverable button at the top of the list itself for the direct track items, and a comparatively less discoverable, and also "unexpectedly elsewhere", menu entry under 3 dots affecting only sub-folders. 

Wouldn't the more discoverable, way to handle this be simply our conventional popup to ask, when a user performs a sort operation via the list button,  _and only if the current screen contains subfolders_, to simply ask if the sorting should also apply to all subfolders?

It would not be very intrusive, because it would only pop up on occasions where a user actually has subfolders (many don't). But it would be much more in line with how we handle things when e.g. we ask if a settings change should apply to all profiles or just the current one. It is simply  the righr question to ask at the right time, and only if it is applicable. No extra menu needed.

The reason I am asking is that I know many users who had rrequested to be able to sort subfolders, but now after this claims to be fixed, _not a single one_  had discovered the fix as currently implemented...not a perfect feature fix if nobody notices the availability... 😉

**Comment by dmpr0** [comment]
No, adding additional popup after each sorting will not add simplicity.

**Comment by pebogufi** [comment]
What about using two or three different buttons to close the window (currently only "abort")
- "apply only to current folder"
- "apply to current and all subfolders"
- "abort"

**Comment by vshcherb** [comment]
Tricky and actually original request was questionable was it really function. As we searched all analogs across other apps / os, this is only option to not make most useful function of sorting just 1 folder overcomplicated
