### ISSUE TITLE
Tracks sort button is half hidden

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#19049]
This appeared together with the new Tracks UI and has never been fixed, see below. I only see this on some devices, probably dependent on screen resolution and/or font size selected.

PS: As can be seen from the spinner and the still "empty" list, this screenshot was taken during the 12-15 second wait I experience upon every opening of this screen, or every scroll operation to the top of the list on this screen which also initiates a 12-15 sec list refresh, see #17805.

![Screenshot_20240208-063342_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/845735/22f747d0-f2ea-4b34-af31-5819272bc3c5)

**Comment by yuriiurshuliak** [comment]
The bug can be reproduced if you increase the font size or display size.

OsmAnd~ 4.7.0#1554m, released: 2024-02-08

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/186f3e47-8064-4c18-adc7-bda4f8818cfc"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Rowin63** [comment]
I see this "half hidden" on my Tab Active 3 but on none of my other devices (S20+, Tab S6).

**Comment by dmpr0** [comment]
## ToDo
- [ ] Sort bar should have min. default height
- [ ] Text in all sizes should be visible

**Comment by sonora** [comment]
PS: There's a similar occurrence on our 'Configure screen' menu, here it"s cut off both at the top (by the Android system notification area) as well as at the bottom by the OsmAnd profile icon bar.

![Screenshot_20240227-094717_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/845735/39d9f4fa-fef9-4a66-9f8f-f38cfeb5c4ef)

**Comment by sonora** [comment]
@0xRe1nk0  Thanks for the PR! Have you seen the second screenshot I posted above? That may require a similar fix?
