### ISSUE TITLE
shop=general nodes have no name in search and details

### ISSUE THREAD

**Issue by teacupmaps** [osmandapp/OsmAnd#19045]
### Description

i can't find this shop in search

### Steps to reproduce

try searching:
- La Ema
- https://www.openstreetmap.org/#map=18/44.44384/26.11803&layers=D

### Actual result

name doesn't find it, link does

### Expected result

it's foumd by name

### Your Environment (required)

```
OsmAnd Version: OsmAnd~ 4.6.12
Android/iOS version: 10
Device model: Galaxy S9
Crash-Logs: didn't crash
```

**Comment by hehehe92** [comment]
also its name isn't displayed after i clicked it:
![Screenshot_20240207-173352_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/158172547/371d2f05-a08d-42a7-a9de-a141c829db6a)

**Comment by hehehe92** [comment]
nearby контора for comparison:
![Screenshot_20240207-173900_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/158172547/293606ee-4ef4-443a-b2c5-3437000a0a2f)

**Comment by XandrexOSM** [comment]
hello, I see that there is a pharmacy next to those two items, can you describe what happens when you do a search on "Farmacia Ana Maria"?

I have a feeling that the name is stored only for some types of shops but not all (for instance not for `shop=general`).

**Comment by hehehe92** [comment]
the farmacia works:
![Screenshot_20240207-192241_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/158172547/f4eb80ac-85bb-4329-a5e2-6a631054767e)

**Comment by hehehe92** [comment]
looks like the same applies for any shop=general

**Comment by hehehe92** [comment]
![Uploading Screenshot_20240207-192602_OsmAnd~.jpg…]()

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. I tried to check the La Ema shop that you indicated and the name of the shop really does not appear.
Moreover, I tried to check other shops with shop=general tag, the other two places have the same problem.
Here are the coordinates to check:

44.44384, 26.11803

44.47957, 26.09578

44.43951, 26.09992

OsmAnd~ 4.7.0#1594m, released: 2024-02-14

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/5648f7c5-84c3-404c-94c5-2c3038828346"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/4cc562e9-0ed9-4370-a9e9-3ff6e3f63c0e"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/1633e862-a61c-4442-9277-8c275745a9fb"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by hehehe92** [comment]
also the same happens for trees

**Comment by vshcherb** [comment]
To  do shop=general should be indexed in POI

**Comment by xmd5a2** [comment]
Place to test: https://www.openstreetmap.org/node/6670394909
Map: Luxembourg

**Comment by xmd5a2** [comment]
Issue is ready to test

**Comment by yuriiurshuliak** [comment]
The bug has been fixed. A shop with the shop=general tag is displayed on the map with the name.

OsmAnd~ 4.7.0#1802m, released: 2024-03-11

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/a18dcb7a-a72a-48ca-a3a1-67e1eeca3e6b"  width="300" height="auto"/> </th>
  </tr>
</table>
