### ISSUE TITLE
Incorrect turn lanes

### ISSUE THREAD

**Issue by Prusaker** [osmandapp/OsmAnd#19041]
### Description

Lanes are displayed incorrectly when making a smooth right turn.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/32092837/bf71435c-d874-4fdc-916e-713d12294fdc"  width="300" height="auto"/> </th>
  </tr>
</table>

[https://www.openstreetmap.org/way/651662103](https://www.openstreetmap.org/way/651662103)
[Yandex panoram](https://yandex.by/maps/157/minsk/?l=stv%2Csta&ll=27.536624%2C53.878698&panorama%5Bdirection%5D=200.403770%2C-5.197025&panorama%5Bfull%5D=true&panorama%5Bpoint%5D=27.535020%2C53.879330&panorama%5Bspan%5D=110.422015%2C60.000000&z=17.88)

### Steps to reproduce

Try to build route (car profile) from 53.8796662, 27.5351541 to 53.8783564, 27.5340767

### Actual result

The program shows that you need to drive in the lane that goes straight.
![image](https://github.com/osmandapp/OsmAnd/assets/32092837/d7bad75b-a744-4eb4-89f8-b9253ec4c11f)

### Expected result

The program needs to show that you can drive in the two right lanes to the right.

### Your Environment (required)

OsmAnd Version: OsmAnd Nightly 4.7.0 1545m
Android version: Android 11
Device model: Lenovo TB-8506X

**Comment by ivanPyrohivskyi** [comment]
C++ version will do after Java review and together with issue https://github.com/osmandapp/OsmAnd/issues/18158 and https://github.com/osmandapp/OsmAnd/issues/18853

**Comment by vshcherb** [comment]
- Regression 01-2023: Turn slightly right (TL|C|+TSLR|+TSLR)  - all 3 turns work correctly.
-

**Comment by ivanPyrohivskyi** [comment]
Regression in the code
https://github.com/osmandapp/OsmAnd/pull/17487
Conception of virtual turn lanes is wrong (method _getVirtualTurnLanes_).
From task [Impossible lane assist - left and straight simultaneously](https://github.com/osmandapp/OsmAnd/issues/15350)
Data in the task was mapped wrong if compare with Google Street View.
Place https://www.openstreetmap.org/way/1092129867

**Comment by yuriiurshuliak** [comment]
The issue has been resolved. Lanes are now being displayed accurately. Here is the link to the web version: [link](https://test.osmand.net/map/?start=53.879666,27.535154&end=53.878356,27.534077&profile=car#18/53.87911/27.53436)

OsmAnd~ 4.7.0#1961m, released: 2024-04-02

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/db89a77c-6a7f-4624-a63f-702a3bd322d7"  width="300" height="auto"/> </th>
  </tr>
</table>
