### ISSUE TITLE
Pause Navigation

### ISSUE THREAD

**Issue by schnedann** [osmandapp/OsmAnd#19057]
### Describe the idea (required)

Pause Navigation, e.g. when one wants to enter a shop aloong the route. Case: one just wants to take the device from a car (navigation) to a shop (no navigation), just to continue with car (navigation) a few minutes later

### Tell us about the expected behaviour (required)

a button to pause navigation (speach output...)

### Tell us about alternatives you've considered (required)

Cancel route, restart route

**Comment by yuriiurshuliak** [comment]
If you want to stop for a break and deviate from the route for a short time, you can use the Pause/Resume navigation function to pause voice prompts and stop recalculating the route.
This option is availible in Android version of the app in [Notification list](https://osmand.net/docs/user/navigation/guidance/voice-navigation#text-notifications) or from the [Quick actions menu](https://osmand.net/docs/user/widgets/quick-action)

Here is the documentation:
https://osmand.net/docs/user/navigation/setup/route-navigation#pause--resume-navigation

**Comment by schnedann** [comment]
Okay, was not aware of that - also that is a place I would not search for something like pause... I always use the app directly - e.g. when I navigate my car and stop in front of a shop, OSMAND is already the active app on the screen. So I would expect a pause button just there...

Maybe provide just both options might be the best solution

**Comment by vshcherb** [comment]
With quick action button now it's possible to create - single tap button
