### ISSUE TITLE
Altitude Widget does not work

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#19054]
### Description

The altitude widget displays 48m, no matter where I am.
The phone knows the correct altitude, also all other apps do so.

### Steps to reproduce

don´t know...

### Actual result

wrong/no altitude

### Expected result

correct altitude

### Your Environment (required)

OsmAnd Version: +4.7.1
Android/iOS version: 13
Device model: S20+

**Comment by CJTmmr** [comment]
The same on Samsung S22 Ultra, Android 14
Osmand 4.7.1
Both with Android API and Google Play Services for Location always about 46-51m even as I am now on 1650m above sea level... 

If I record a GPS-track the right heigth is displayed in the track/details

**Comment by sonora** [comment]
Duplicate of https://github.com/osmandapp/OsmAnd/issues/18998?

**Comment by Rowin63** [comment]
Yes. Sorry, didn't see it.
