### ISSUE TITLE
navigation: voice announcements and visual clues (top left) do not match

### ISSUE THREAD

**Issue by sjvudp** [osmandapp/OsmAnd#19067]
### Description

Navigating with the car I noticed the following problem: When a road makes a right turn, and you are to follow that road, there is no visual turn indication, but (sometimes only?) a voice announcement to go right. If a crossing is rather close where you are expected to go left, the following confusing situation exists: The visual clue says "turn left", while the voice announces to go right.
Things can become more complicated if there is a fork to the left shortly before the crossing to go left.

Also overloading the user with information (like arrows on the map at a specific scale, navigation preview arrows with distance given as numbers, voice announmcements with distance spoken) is not helpful: The user has to concentrate on driving; he cannot stare at the display to find out what to do.

### Steps to reproduce

Example:
![Imagepipe_57 1](https://github.com/osmandapp/OsmAnd/assets/6734808/a79f2db7-b690-4c85-96fd-5eaef76e8b1c)

### Actual result

User not knowing the situation may be confused.
Also, the warning about pedestrian crossing is displayed to early (the crossing is on the main road after the turn to the left).

### Expected result

It should be clear all the time which way to go.
Also, whenever you are expected to use the car's turn indicator (blinking light), the navigation aid (OsmAnd) should announce the change of direction, too. (My older TomTom says something like "keep right" in such situations)

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by TheSnoozer** [comment]
Mentioned route from above:
Start: 49.19783, 12.26985
Finish: 49.19765, 12.27269

https://osmand.net/map/?start=49.197830,12.269850&finish=49.197650,12.272690&type=osmand&profile=car#19/49.19718/12.27103

**Comment by yuriiurshuliak** [comment]
As we checked, Sankt-Wolfgang-Straße is the only street considering the turn, so this turn may not be displayed. Check this OSRM link: https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=49.1979%2C12.2699%3B49.1976%2C12.2726#map=18/49.19756/12.27141

**Comment by vshcherb** [comment]
It really depends on roads priority, if roads have the same priority then it definitely should say that. However if it's not the same priority and lower and the turn angles are not sharp (visuals could be different from reality so sometimes it's a mapping issue). Over informing about adjacent roads also doesn't make driving safer. That's what we've come up 5 years ago during intensive testing

So every case we need double check very specifically.

From the map perspective (not actual perspective) I think the turn indications are correct.

**Comment by sjvudp** [comment]
> Over informing about adjacent roads also doesn't make driving safer.

Maybe, but I think visual and audio should be treated independent:

- A co-driver could continuously look at the map and tell the driver which way to go
- voice output should be able to replace the co-driver, so that the driver finds the way *without* having to look at the map actually.

That would be a good user interface.
And additional warnings (like pedestrian crossing ahead) should be sorted that they are displayed once on the road with the crossing (i.e.: after having followed the turn instructions that lead to that road), not before.
