### ISSUE TITLE
Incorrect "Next turn" widget

### ISSUE THREAD

**Issue by Prusaker** [osmandapp/OsmAnd#19064]
### Description

When driving through a road junction and exiting onto a link, the wrong next turn widget is shown on the screen:
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/32092837/ef808d5c-3f24-4d10-870c-e3ec3516da76"  width="400" height="auto"/> </td>
  </tr>
</table>
This bug is observed only at this junction!
[(https://www.openstreetmap.org/node/275073193#map=18/53.83754/27.53428)](https://www.openstreetmap.org/node/275073193#map=18/53.83754/27.53428)

### Steps to reproduce

Try to build route (Car) from 53.8385572, 27.5331064 to 53.8362687, 27.526326.

### Actual result

When turning right wrong widget displayed:
![image](https://github.com/osmandapp/OsmAnd/assets/32092837/f152cde5-bd41-44e3-a6da-2e13bbb36d5f)

### Expected result

"Right turn" widget must be displayed in whis case.
![image](https://github.com/osmandapp/OsmAnd/assets/32092837/f2a4d891-d5ae-4179-9ca1-3d67ea823b1d)

### Your Environment (required)

OsmAnd Version: OsmAnd Nightly 4.7.0 1563m 2024-02-09
Android version: Android 11
Device model: Lenovo TB-8506X

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. The wrong next turn widget is displayed.

OsmAnd~ 4.7.0#1578m, released: 2024-02-12

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/1a4aeda3-32f9-4363-bc54-5d5e3ad2b575"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by pl71** [comment]
Smoot turns are often ignored as turns. I have to turn left at the next junction. This is not displayed.

![Screenshot_20240301_090706_OsmAnd](https://github.com/osmandapp/OsmAnd/assets/4776779/3628009e-6067-4b8e-aff3-6af25d9a53b0)

**Comment by vshcherb** [comment]
Keep left should be displayed (? check android) and also it should be turn left https://test.osmand.net/map/?start=42.680661,23.321196&finish=42.678224,23.324302&profile=car#18/42.67901/23.32246

**Comment by pl71** [comment]
Yes, it should be a left turn at [this junction](https://www.openstreetmap.org/#map=19/42.67847/23.32144).
But having a smooth turn (way https://www.openstreetmap.org/way/728202686)  just in front of it, it is more like going **straight** I suppose so.
And straight crossings are not displayed, right?
Probably this is more of a geometry issue. Any advice?
![0-02-05-2090c4946e01606c5898f1ab9e677d4271b8b5f71a3a344e33e0b62220f16fa3_e4e77408a520c60b](https://github.com/osmandapp/OsmAnd/assets/4776779/c2d05d45-5fd1-429a-a961-3dfcca38fc84)

**Comment by ivanPyrohivskyi** [comment]
Fixed:
https://test.osmand.net/map/?start=53.838300,27.533120&finish=53.836040,27.528240&profile=car#16/53.8382/27.5269
<img src="https://github.com/osmandapp/OsmAnd/assets/127092082/1a4aeda3-32f9-4363-bc54-5d5e3ad2b575"  width="300" height="auto"/>

---------------

In this case need to fix data, need to make intersection without sharp angles from the one point.
Way [746064115 (бул. Арсеналски)](https://www.openstreetmap.org/way/746064115) detect as right U-turn.
<img src="https://github.com/osmandapp/OsmAnd/assets/4776779/3628009e-6067-4b8e-aff3-6af25d9a53b0"  width="300" height="auto"/>

**Comment by pl71** [comment]
So how to fix OSM data? I can't see anything wrong with it.

**Comment by vshcherb** [comment]
Smoothen the angle would definitely help . It should be more 60 degrees to turn right otherwise it's a U-turn to the right. Another fix could be to map u-turn in turn:lanes or put a restriction if it's forbidden. In that case it will match 4 allowed roads and 4 directions

<img width="144" alt="Screenshot 2024-04-02 at 00 39 19" src="https://github.com/osmandapp/OsmAnd/assets/1042025/a347dab3-6c17-4d8b-b948-b5c599767776">

**Comment by pl71** [comment]
Looks like it is a difficult to map situations where wide roads with several lanes continue to a much smaller streets. Google is using another approach - merging parallel ways behind intersection, which results in right angles to athwart ways.
