### ISSUE TITLE
Speed limit not showing when an itinerary is set

### ISSUE THREAD

**Issue by hayvan96** [osmandapp/OsmAnd#19066]
### Description

Hi, I'm running osmand 4.6.11
When set in car mode, with no itinerary defined, then the speed limit widget displays correctly (I've set it on the right panel). Also warnings appear (bottom left) as defined in settings (for instance speed limit with the local sign).
But when I define a destination, and start navigating, they disappear : the speed limit widget no longer displays (actual speed does), and no warnings on the bottom left. As soon as I stop navigating, they return.
When using 4.5.x, I didn't have that behaviour. 

### Steps to reproduce

Configure screen to as speed limit as a widget. Turn warnings on map in settings as well. 

### Actual result

As described : speed limit widget doesn't show during navigation, neither the warnings. 

### Expected result

Navigating or free driving should make any difference. 

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.6.11
Android/iOS version: 13
Device model: pixel6a
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
I could not reproduce this bug. In OsmAnd the alert is shown when you exceed the speed. You can set parameters of speed exceeding.
The speed limit widget becomes visible during navigation when driving on a road with maxspeed tag. 

Please attach the specific coordinates where you have this problem and it would be good if you could attach a video of how it works for you.


OsmAnd~ 4.7.0#1578m, released: 2024-02-12

https://github.com/osmandapp/OsmAnd/assets/127092082/90200776-590e-44a5-a7fe-7cdc98ee4cc6

**Comment by hayvan96** [comment]
Hi

Here's a video between Lieksa centre (Finland) and Sarkkila. You can see that when destination is not set, warnings appear on bottom left and speed limit on top right. Once destination set they disappear. When navigation is stopped, they reappear. 

https://github.com/osmandapp/OsmAnd/assets/37040583/97167a61-9f74-4310-9ae2-90121372cfdc

**Comment by yuriiurshuliak** [comment]
Kindly clarify if you are referring to online navigation. In case you are utilizing offline navigation, kindly provide your profile settings for our assessment. You can do this by navigating to Menu → Settings → Export and selecting the data you want to export.

**Comment by hayvan96** [comment]
I've checked and routing is set to online for my car profile, specifically openrouteservice (car). Do you want me to check with routing set to offline?

**Comment by yuriiurshuliak** [comment]
Yes, please verify this with offline navigation and provide your feedback.
