### ISSUE TITLE
Navigation/waypoints setup modifications

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#1906]
The night build from day 10-11-2015 was using a setup that was nice, fast and simple to use.
Tapping a spot or POI , opened the spot options, where there was a big blue circle with the 'turn right' signal. 
Taping it would set it as the destination, and proceed to route calculation. Nice and simple.
To add a waypoint, we could choose the desired waypoint location, and tap the smaller 'flag' on the bottom bar.

Now all changed again, the blue circle pops-up 4 more options, like navigate to, set as destination, add as waypoint... But this adds more steps to what was simple.
And tapping the bottom flag (previously to add a waypoint) now sets it as destination?

**Comment by sonora** [comment]
I tend to agree, we could, and probably should, use the bottom "Waypoint" button to add waypoints. But we must improve on what we had previously, see issue 1841, point(1): Accidentally tapping on that button happens very easily, and should not automatically create a waypoint without further notice. Instead, we could display the waypoint/destination-related popup menu we now shown after tapping the blue the "Directions" button.

**Comment by stephan75** [comment]
And now it finally seems to be possible to set a STARTING point, even before a destination point is defined! Or am I wrong?

But so far there is no flag for a starting point ... or is my nightly-build already outdated in this issue?

What about a flag with a kind of arrow from the flag's bottom that directs away? Or a green flag?

**Comment by sonora** [comment]
Yes, historically in our code we use actions "Set s destination" and "Add as waypoint" to add points semi-permanently (i.e. they have to be deleted again explicitly by the user) in the list of points the navigation must pass. While we use the actions "Directions to" and "Directions from" to start the actual navigation. And "Directions from" is really very "transient", because is many (not all) cases on a navigation device (unlike a navigation website) this will only be used while the actual position is not yet known (and some users expect it to be overwritten once the position becomes available).

It is a little tricky to cater for all use cases here, takes more thinking, suggestions welcome.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/commit/0daa278bd18dc82557ec3ed487a920cb8ec57f1b#commitcomment-14401101, I left a comment here

**Comment by raindropsfromsky** [comment]
I have several suggestions explained here:
https://drive.google.com/open?id=0BwaOwUJ0zbWRdmtGcDhvZXZreTA

**Comment by Barrocas** [comment]
You are right,  the Waypoints list ordering/elimination should be easier to
access, and I agree with most of those suggestions, but I think some of
them are based on a previous Osmand version, and some details are already
changed.

Good work, I was planning on doing something similar to be a demo of what
could be changed in this great app.

..

No dia quarta-feira, 25 de novembro de 2015, raindropsfromsky <
notifications@github.com> escreveu:

> I have several suggestions explained here:
> https://drive.google.com/open?id=0BwaOwUJ0zbWRdmtGcDhvZXZreTA
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osmandapp/Osmand/issues/1906#issuecomment-159494428>.
>


-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by raindropsfromsky** [comment]
Yes, this is part of an old discussion. But IINW all the observations are still relevant, because this part of the GUI has not changed at all.

**Comment by raindropsfromsky** [comment]
1. Provide option for the current location to be added as Start point
2. Allow user to rename the waypoints, start point and destination.
3. Eliminate the redundant "Waypoints" screen (allow user to edit the waypoint directly)
4. In the Navigation dialog, provide an X button against the current destination, to dismiss it directly.
    (currently you have to replace an existing destination with a new point: you cannot dismiss it.)
5. When a POI is added as waypoint, its name should be retained.
6. Add the "change order" and "sort door-to-door" buttons to the single waypoints screen.
    (instead of having a separate screen for it, manage this within a "waypoint editor")
7. The "waypoint editor" screen should also have "add waypoint" button.
    Thus a single editor should be able to add, delete, move, sort, and rename waypoints.

**Comment by vshcherb** [comment]
The issue is deprecated, I think for 2.2 we added back most important options. For 2.3 we will need to reiterate design based on your comments. Thanks!
