### ISSUE TITLE
Download skips sub areas

### ISSUE THREAD

**Issue by takosalad** [osmandapp/OsmAnd#19073]
### Description

If I start download of a region it will skip its sub regions, forcing me to perform 100+ clicks manually to add them all.
Also a global "download all world maps" button is missing.

### Steps to reproduce

Click on download USA maps

### Actual result

Doesn't download most sub or sub-sub maps, leaving them coloured grey in the list.

### Expected result

Download all sub bulletin points.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by goldfndr** [comment]
A screenshot of the missed maps might help. Also, I'm not seeing a "download USA maps" option anywhere, just (menu) / Download maps / North America / United States, which doesn't do anything until tapping further.

Some of the maps are composites of other maps. For example, if one downloads the Texas Standard map, that includes the data found in the San Antonio Standard map and the other 10 Texan Standard maps.

**Comment by DmitryAlexei** [comment]
@takosalad please add information about OsmAnd version and Android version
Moreover, a short video of your issue may help us better understand it.
