### ISSUE TITLE
Temperature data not displayed in profile

### ISSUE THREAD

**Issue by albansuser** [osmandapp/OsmAnd#19075]
### Description

External sensor temperature data not recorded to GPX.

External Device:
Garmin Tempe Ant+ temperature sensor.

Tested on:
1/ Samsung S8 running Andoid 9 with built in Ant+
2/ Samsung S22+ running Andoid 14 with Garmin Ant+ USB Stick (adapter)

### Steps to reproduce

Both mobiles are set up to display and to save, to GPX, the temperature data.

On both mobiles the temperature is displayed correctly in the onscreen external temperature sensor widget. Displayed temperature changes accordingly.

Confirm  the record temperature data to GPX is set correctly.

Start recording a track.

Finish recording the track and save track as GPX file.

### Actual result

For the saved track select the "analyse on map" option.

Search for temperature from  drop-down Y axis list. 

Temperature is not in list.

### Expected result

Temperature is shown in drop-down Y axis list.

Temperature can be selected and displayed accordingly.

Note: On the Samsung S22+ running Andoid 14 (with USB Ant+ adapter for temperature) heart rate from a BT external sensor is simultaneously displayed on screen, saved correctly to GPX,  and subsequently displayed in profile correctly 

### Your Environment (required)

OsmAnd Version: OsmAnd~ 4.7.0#1569m, released: 2024-02-11 and earlier

**Comment by yuriiurshuliak** [comment]
Please provide us with your GPX file that you recorded. You indicated that the data was visible in the widget, but was not visible in the "analyze on map" option. The question is whether the data was not recorded at all, or whether the data is simply not showing up in the analysis.

**Comment by albansuser** [comment]
As requested, I have attached a test GPX file
[OSMAnd - HR and Temperature Test.zip](https://github.com/osmandapp/OsmAnd/files/14252673/OSMAnd.-.HR.and.Temperature.Test.zip)

As you will see, the GPX contains both heart rate and temperature data. However only the HR profile is displayed in OSMAnd and via the application GPXSee.

In the GPX file the temperature code is "wtemp". After some research, I changed all occurences of that to "atemp". The temperature profile subsequently displayed correctly in GPXSee, but not OSMAnd.

(The attached GPX is in its original form)

Regards

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. Upon reviewing the provided GPX file, I observed temperature data recorded with the value gpxtpx:wtemp29.32</gpxtpx:wtemp>.

Nevertheless, upon inspecting the application, it was noted that there is no temperature tab visible on the Y-axis graph.

OsmAnd~ 4.7.0#1627m, released: 2024-02-19

<img width="406" alt="image" src="https://github.com/osmandapp/OsmAnd/assets/127092082/b2ba2aff-9108-45af-aa1e-89be01d9dbde">

<table style="width:100%">
  <tr>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/ae18fbf7-4ccd-4778-a8d1-f12e14e64f56"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by dmpr0** [comment]
## ToDo
- [ ] Read and Display temperature data from both:`<gpxtpx:atemp>` and `<gpxtpx:wtemp>` tags

**Comment by albansuser** [comment]
Thanks

**Comment by yuriiurshuliak** [comment]
The bug has been fixed. After checking the app, it was observed that a temperature tab is now visible on the Y-axis graph, and a corresponding temperature graph is being presented.

OsmAnd~ 4.7.0#1786m, released: 2024-03-08

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/631e4f08-c2c5-45f9-96fa-39348ff3086f"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/aef16049-80b5-4cf7-bda5-280a0778826c"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
https://github.com/osmandapp/OsmAnd/issues/19315
