### ISSUE TITLE
Commit POI - OK and Cancel button sizes

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#1907]
On previous versions (10-11-2015) the 'Ok' and 'Cancel' buttons on the 'Commit POI' context (or for example the 'Cancel Route') were big and easy to tap, because they shared the context box available horizontal space between the 2 options (yes or no).

Probably due to the color changes with the recent issue of Android 5.0, the buttons are now smaller,  in the same size as the text they contain.

So in the 'commit POI' context box, the 'Cancel' is bigger, and the 'Ok' is rather small. 
It would be better if they were the same size, as in previous versions, since the 'Ok' should be the primary choice, and the 'Cancel' just in case it was pressed by mistake.

**Comment by Barrocas** [comment]
Also, can the cancel button be colored red, or in another color that the green/blue used in the 'Ok' button (using dark theme)? 
It would be better to visually perceive the difference.

Another related doubt: 
Are the chosen colors tested for daltonic users?
I'm not daltonic, but I know that they see certain colors as grey, so depending on the used colors, they may see grey text on grey background.

**Comment by GaidamakUA** [comment]
About small buttons. Seems like we can't reproduce this issue. Can you please post screenshot?
We think it is not good UI wise to change color of the button.
Thank you for your suggestion about daltonic people. I can't promise you that such test will take place any time soon but we will keep it in mind. If people someone you know will face this issue, please, contact us.

**Comment by Barrocas** [comment]
The previous versions, same size for 'cancel' and 'ok' buttons:
![screenshot_2015-11-18-15-03-42](https://cloud.githubusercontent.com/assets/4006691/11245181/4c710820-8e09-11e5-85ca-82957d3b3189.png)

The most recent, bigger 'cancel' and smaller 'ok':
![screenshot_2015-11-18-15-01-40](https://cloud.githubusercontent.com/assets/4006691/11245455/c4ba2392-8e0a-11e5-862f-5ea6a5e75d3f.png)

**Comment by GaidamakUA** [comment]
Dialog was redesigned according to new Google design guidelines. Those buttons are quite high. You don't have to click exactly on the text. They are approximately as high as on first screenshot even though it is not visible. I don't think it's an issue.

**Comment by vshcherb** [comment]
Now it is aligned with application style, in other case we need to update it everywhere. So it is much bigger issue.

**Comment by Barrocas** [comment]
I was refering to the width, not the height.

-- 
Cumprimentos,
D.er Hugo Barrocas
