### ISSUE TITLE
Regression: Standard routing has issues

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#19071]
Using today's nightly code, both with the Development plugin's "Special routing" on **or even off**, the app never finishes some car routes of about 100 km in length. Reverting back to a build I compiled on Feb 7, the identical routes calculate ok in about 6 sec or so.

**Comment by RZR-UA** [comment]
Hardy, please disable the option: "Recalculate route" -> "In case of reverse direction" and try calculate the route again.

![try](https://github.com/osmandapp/OsmAnd/assets/90444451/31e007b2-c3aa-47e0-b878-4e6d7a3918a2)

Anyway, could you post start lat/lon, finish lat/lon and car profile settings exported to file (is they aren't default).

I've got the similar bug yesterday but I'm not sure exactly.
In my case the bug disappeared with disabled `In case of reverse direction`.

Need more information about your case.

**Comment by sonora** [comment]
Thanks for looking into this! :wink:

Please note that I am trying this at rest, not moving. I have now disabled "_In case of reverse direction_", but the situation is unchanged.

After a while., and in both cases, I get this message:
![Screenshot_20240214-185639_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/845735/a78f56de-5784-4067-ac03-d9282fae5eda)

Here's a route I just randomly picked, using default Car profile and my Germany_Bavaria map (on this phone still a 2022 edition):  From "Erding" (Town) to "Schwabach" (Town), just using OsmAnd's address search, "First specify city/town/locality", then simply accepting the town name with no street name specified afterwards. this route takes along time, perhaps finishes never,m not sure, while on an old build a route is found in a few seconds.

Looks like I can pick any other places about 100 km or so part, with the same effect.

**Comment by sonora** [comment]
PS: Please note that I am talking about the **standard** routing, i.e. our old mechanism, which seems broken here...

**Comment by RZR-UA** [comment]
Hardy, please check on the tomorrow's nigthly. Today I can not reproduce broken standard routing on master branches.

**Comment by sonora** [comment]
Sure, I have just re-built and retested (from the master branch):

It's weird, I see no change. I have updated the map to the latest, same symptoms. Like for the example route specified above, after the first minute of waiting has passed the message in the screenshot above appears. And after 2 or so minutes have passed, the route calculation still has not finished.

Going back to my Feb 7 build, the issue disappears.

I have then retested with 'Special routing', and that seems much improved now. But still, the issue I observe here is for our old routing, and I wonder what has impacted/broken it between Feb 7 and Feb 9.

**Comment by DmitryAlexei** [comment]
@sonora I tried routing from "Erding" to "Schwabach" with nightly 4.7.0#1629m 4700
It took quite a long time to calculate a route (more than 3 minutes), but it was done without crashes and freezing. 
https://github.com/osmandapp/OsmAnd/assets/116079541/d344a072-e6c1-4a45-bc48-4ed4664fd1f4

How long does it take to calculate this route on your device?

```
routing_time=11024.9, vehicle=car, base=false, start_lat=48.30645, start_lon=11.90766, target_lat=49.32955, target_lon=11.01951, complete_distance=153947.2, complete_time=7928.1, native=true
02-19 18:37:46.368 11343 13889 I System.out: Route <metrics>: tilesPerSec=413.3, segmentsPerSec=6053.1
02-19 18:37:46.368 11343 13889 I System.out: Route <segments>: visited=517600, queueDirectSize=11576, queueOppositeSize=13140, visitedDirectPoints=1214650, visitedOppositePoints=1231141, finalSegmentsFound=0
02-19 18:37:46.368 11343 13889 I System.out: Route <tiles>: loadedTiles=52340, loadedTilesDistinct=11274, loadedTilesMax=12152, loadedTilesPrevUnloaded=10152, unloadedTiles=48849
02-19 18:37:46.368 11343 13889 I System.out: Route <time>: timeToCalculate=212.3, timeToLoad=124.5, timeToLoadHeaders=2.1, timeToFindInitialSegments=0.1, timeExtra=0.0
02-19 18:37:46.408 11343 13889 I net.osmand: RouteProvider Finding route contained 2926 points for 216746 ms {pool-6-thread-1}
```
[logcat.log](https://github.com/osmandapp/OsmAnd/files/14334563/logcat.log)

**Comment by sonora** [comment]
I've now waited over 6 minutes, and _Erding -> Schwabach_ still had not finished calculating. Then I went back to my build of Feb 7 and it took only 35 seconds....

Here's another one: _Amberg -> Forchheim (95.4km)_, old build 14 sec, newer builds take 1:10 to calculate this.

**Comment by yuriiurshuliak** [comment]
I attempted to route in the release version, and it took 1 minute and 25 seconds. The relevant log information indicates that timeToCalculate=68.0, timeToLoad=17.4.

[logcat.log](https://github.com/osmandapp/OsmAnd/files/14379121/logcat.2.log)
OsmAnd 4.6.13, released: 2024-01-19


https://github.com/osmandapp/OsmAnd/assets/127092082/f1262445-5a6e-4b3f-84ce-734647ca6d7d

**Comment by RZR-UA** [comment]
It seems that Native 2-phase routing (which is default for car profile) is broken, possibly by commit 5522a72b2c623d41d72d21296e6fbba9c5bfa950. We will review and fix the problem next week.

**Comment by sonora** [comment]
https://github.com/osmandapp/OsmAnd-core-legacy/commit/5522a72b2c623d41d72d21296e6fbba9c5bfa950 may be too early, the last build I have which does not exhibit this issue was of Feb 7, 23:30, while the referenced commit seems to have been at 18:30 already that day....

**Comment by pebogufi** [comment]
My latest without this issue is
OsmAnd~ 4.7.0#1553m, veröffentlicht: 2024-02-08

**Comment by vshcherb** [comment]
Ready to test

**Comment by pebogufi** [comment]
Not really better, may be a few bit.
Immediately after start (of prepare) the progress bar stops for about 20 sec. , but only on a calculation which i do repeatedly. If i start calculation directly after a clear cache it is much faster, less than half the time, distance ~250 km, profile car.

**Comment by sonora** [comment]
@pebogufi Yes, but that seems perhaps like another issue introduced at some point, the issue I discovered here originally seems actually fixed now for me.
