### ISSUE TITLE
Color walking paths

### ISSUE THREAD

**Issue by blackboxlogic** [osmandapp/OsmAnd#19078]
### Describe the idea (required)

Render ways with `osmc:symbol`s the same way hiking route relations are rendered (when the OSMC setting is turned on in OsmAnd).

### Tell us about the expected behaviour (required)

A way with tags like `highway=path`, `trailblazed=symbols`, and `osmc:symbols=red:red` should be rendered as a red line when the hiking/OSMC setting is on.

### Tell us about alternatives you've considered (required)

I've considered tagging trails like `name=yellow blazes`.
I've considered making many route relations that include single small ways.
I've considered explaining to new mappers what a relation is and why coloring a small hiking trail is so hard.
I've considered using other mobile navigation apps.

### Context (optional)

Tag `osmc:symbol` is already implemented in OsmAnd for hiking **route relations** (settings -> configure map -> routes -> hiking routes -> OSMC). I'd like to be able to apply similar trail coloring to the short hiking trails (as ways) at my local land trust. These trails are so short that creating a hiking route relation seems silly. According to [OSM's wiki](https://wiki.openstreetmap.org/wiki/Key:trailblazed), using `osmc:symbol=red:red` is **valid on ways**.

I'm suggesting OsmAnd render this tag combination (when a route relation with `osmc:symbol` doesn't exist) so users can see colored hiking ways, even when there isn't a hiking route relation. Choosing to render colors/symbols on ways could be controlled by the same setting as rendering them on route relations.

I'm pretty sure you don't already do this because I'm looking at [Big Falls Preserve](https://www.openstreetmap.org/way/991578881) in hiking mode on OsmAnd with the OSMC setting turned on.

Overpass Turbo is showing that [many of these exist already](https://overpass-turbo.eu/s/1Hdx). If it rendered in OsmAnd, I would start using these tags for many short tails. I come across many trails with colored blazes mapped as `name=yellow` and I'd like to improve them.

**Comment by yuriiurshuliak** [comment]
To reproduce and visualize these problems with the colorization of walking paths, please provide specific coordinates. Moreover, attach screenshots and clarify exactly where you see this incorrect visualization of paths.

Also provide your version of the app and try our nightly version to see if this issue is fixed there.
https://osmand.net/docs/versions/nightly_versions#nightly-builds

**Comment by blackboxlogic** [comment]
Originally: OsmAnd~ 4.5.10 on a Pixel 3 running Android 12.
An example, [this trail](https://www.openstreetmap.org/way/1243596237#map=16/43.9805/-70.2431) at 43.97977,-70.23918 is a `way` tagged with `osmc:symbol=yellow:yellow` and I'd expect something about the trail to render yellow.

Retested: I joined the beta tester program in google play for OsmAnd v4.7.1, downloaded/installed/ran, downloaded my local map, switched to hiking profile, turned on OSMC routes setting, zoomed to 43.97977,-70.23918 the result is unchanged (trail is not rendered with color). Screen shot to follow in a separate comment.

I believe osmand is operating as designed and currently only colors hiking route relations, and not ways. This ticket is a request to **also** color ways.

**Comment by blackboxlogic** [comment]
![Screenshot_20240213-092427.png](https://github.com/osmandapp/OsmAnd/assets/31355456/d5fe077c-ac1f-443d-a16e-5b0ddf36c61c)

**Comment by yuriiurshuliak** [comment]
This bug was not reproduced. Please try to use the nightly version https://osmand.net/docs/versions/nightly_versions#nightly-builds and enable live updates.

OsmAnd~ 4.7.0#1594m, released: 2024-02-14

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/81b62a27-2e35-45e7-8d0e-e9376f0a4d58"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by blackboxlogic** [comment]
Your screenshot clearly shows the problem. Those trails should be colored according to their `osmc:symbol` tag but they all have the same style. They should have different colors:
![image](https://github.com/osmandapp/OsmAnd/assets/31355456/37851ee0-b0ed-42d2-b8e7-e781265a885f)

[Here's a link to the red trail's way](https://www.openstreetmap.org/way/1243596239) so you can verify its tags.

**Comment by yuriiurshuliak** [comment]
You are right, it is a misunderstanding. The yellow squares represent surface smoothness. Upon reviewing similar routes edited previously, they are displayed accurately. It might be necessary to await the upcoming monthly map update.

**Comment by blackboxlogic** [comment]
I can't tell if you're saying you've fixed it but I'll need to wait for a map update, or if you haven't made any changes but you think a map update will resolve the issue.

I've found another case of a way with "osm:symbol" which isn't being renderred with any color and was last updated over 7 months ago to demonstrate that the issue isn't being caused by a way being recently edited.
It's at **43.50108° N, 71.31230° W**
Way 561040440, "name=precipice Path West (Purple)", "osm:symbol=purple" and isn't being rendered with any purple.

**Comment by DmitryAlexei** [comment]
@blackboxlogic 
According to OpenStreetMap wiki: 
- key [osmc:symbol](https://wiki.openstreetmap.org/wiki/Key:osmc:symbol) is used to describe route symbol that is used as waymarker or on guideposts. This tag also requires tag **type=route**.
- at the same time, key colour=* is used to indicate the official colour within the sRGB gamut associated with the object.

So key **osmc:symbol** is used to display a waymark (or shield) on a route, but it is not used for coloring routes. 
Please see https://www.openstreetmap.org/relation/11679302#map=16/55.8468/23.1347
- it is tagged with osmc:symbol=green:green:black_dot:4:white . This symbol is rendered on the shield on some parts of the route
- it is also tagged with colour=#9CEB00 . And you can see, that this color is used to display this route on the OmsAnd's map.

Considering the above, coloring ways using **osmc:symbol** will not lead to the desired result. Moreover, implementation of your feature request will break the current state of the map.

**Comment by blackboxlogic** [comment]
@DmitryAlexei 

[Yes, that wiki page](https://wiki.openstreetmap.org/wiki/Key:osmc:symbol) says `osmc:symbol` is only for route relations. But [another wiki page](https://wiki.openstreetmap.org/wiki/Key:trailblazed) implies it is valid on ways. I was considering updating the `osmc:symbols` wiki to allow for tagging on ways, and started a discussion on the talk-side of that page and another in the hiking slack channel.

You're saying `osmc:symbols` is for shields, I'm suggesting a trail blaze could be (and is) expressed as a shield with only a background color.

You're saying `osmc:symbols` on ways would break the map, I don't see how, but you have more context than me. Using `osmc:symbols` to style a hiking way was an implementation suggestion, and **I would be happy using the `colour` tag**, as you seem to suggest. But after checking [a hiking trail with colour=yellow](https://www.openstreetmap.org/way/380628490) that's only implemented for hiking route relations (and not on hiking ways). Another option might be [ref:colour](https://wiki.openstreetmap.org/wiki/Key:ref:colour)?

Creating a route relation for each way is cumbersome, which leads to [`name=River Loop (White)`](https://www.openstreetmap.org/way/80989758), but that's clearly wrong. I see colors and names as similar, and we're all ok with a hiking way having a name.

**Comment by blackboxlogic** [comment]
Can you clarify "done"? Is there now a way to color a hiking trail in osmand without creating a route relation? If yes, which tags should be used?

**Comment by vshcherb** [comment]
No It's only possible with custom rendering style. Also there is a way to select route save as GPX and color it as you want.

**Comment by blackboxlogic** [comment]
The work-around you gave seems to imply that I'm trying to get a feature just for me, or for one trip. I'm suggesting that **all hiking OsmAnd users and all mappers would benefit from a simple/common tag which renders the color of hiking trails.**

I'm about to edit a lot of trails (I do imports and mechanical edits occasionally). I want to tag hiking trails in a way that will render in OsmAnd as the designated color (a core feature for a hiking map, like showing trail name). **This feature is already implemented in OsmAnd for route relations** which shows that the rendering engine is capable. You haven't acknowledged this existing feature, so I'm not sure if I've been clear?

I first asked about `osmc:symbol` for this, you suggested the `colour` tag. That sounds great! **Can we get the `colour` tag on a hiking way to render as the way's color?** Would that break something?

The lack of this feature leads to [bad tagging practices](https://overpass-turbo.eu/s/1IZm) like [name = Loop Trail (red blazes)](https://www.openstreetmap.org/way/835331210) and a poor user experience (hiking trails aren't colored).

I'm being persistent because I suspect this would be simple to implement, high value to both mappers and navigaters, and I don't see any downside.

**Comment by blackboxlogic** [comment]
For anyone following in my footstep, related: https://github.com/waymarkedtrails/waymarked-trails-site/issues/454
