### ISSUE TITLE
Calculating the route after removing an intermediate stop takes longer than calculating the route when adding the stop

### ISSUE THREAD

**Issue by sjvudp** [osmandapp/OsmAnd#19070]
### Description

By mistake I had added an intermediate stop three times. When removing the duplicates, I noticed that OsmAnd 4.6.13 takes much longer to re-calculate the route when removing a stop than when adding a stop. Actually I think it even took longer than calculating the complete route.

### Steps to reproduce

Add a rout with an intermediate stop. Notice the time to route. Then delete an intermediate stop. Again notice the time to update the route.

### Actual result

The time to update the route seems much longer than the time to create the route.

### Expected result

Updating the route should be faster.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
When computing the route for an extended journey, the inclusion of an intermediary point really affects the time of calculating the route. Interestingly, if you build the navigation separately and add an intermediate point, it is quite fast. Similarly, creating navigation from point to point separately, without any intermediate points, is also quite fast. However, when performed on a single route, the removal of intermediate points notably increases the time required.

OsmAnd~ 4.7.0#1578m, released: 2024-02-12


https://github.com/osmandapp/OsmAnd/assets/127092082/6cbb69cd-733e-4deb-8e56-4733be64ba8c

**Comment by vshcherb** [comment]
I suspect it's realted to useSmartcaclulation route

**Comment by vshcherb** [comment]
New routing should calculate it faster

**Comment by yuriiurshuliak** [comment]
It appears that the issue persists. Adding an intermediate point takes a brief moment, whereas removing one results in a significantly longer calculation time, taking three times as long. I tested this with both HH x Java routing and HH x C++.

OsmAnd~ 4.7.0#1864m, released: 2024-03-19

<table style="width:100%">
  </tr>
  <tr>
    <th>Adding an interpoint</th>
    <th>Deleting an interpoint</th>
  </tr>
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/7274072d-80dd-43d7-8a1a-93eb800608d6"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/17c72aba-e49d-45fc-9482-29b9b7d0e3be"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by Dima-1** [comment]
Delay before apply [reduced](https://github.com/osmandapp/OsmAnd/commit/b653eb0fb4a1183fcc69d9228a8cdc379d364c83)

**Comment by yuriiurshuliak** [comment]
The bug has been fixed. Deleting an intermediate point takes much less time.

OsmAnd~ 4.8.0#2161m, released: 2024-04-23

<table style="width:100%">
  </tr>
  <tr>
    <th>Adding an interpoint</th>
    <th>Deleting an interpoint</th>
  </tr>
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/56c21dad-79f0-4d39-8ab4-f811fbcd87e2"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/3f0b8fbc-0f5d-4aad-98aa-9aaa33db0319"  width="300" height="auto"/>   </td>
  </tr>
</table>
