### ISSUE TITLE
Use same name for the Maps menu in Android and iOS

### ISSUE THREAD

**Issue by Max1234-Ita** [osmandapp/OsmAnd#19079]
### Description

I've noticed that in Android the option _Download maps_ in the main menu gives access to a section where maps, voices, etc. can be downloaded, updated and removed.

In iOS, the same is done by the menu _Maps and Resources_. 

I wonder if the two menus should have the same name in both Android and iOS, in effect the iOS name seems to be more appropriate.

### Steps to reproduce

- Launch OsmAnd in both Android and iOS environment
- Open the main menu and check the option allowing to dowload maps.

### Actual result

Android: "Download maps"; 
iOS: "Maps and resources".

### Expected result

Perhaps there should be a "Maps and resources" menu in both versions.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd+ v. 4.7
Android/iOS version: all
Device model: N/A
Crash-Logs: None
```

**Comment by vshcherb** [comment]
IOS as for now has Plugins inside Maps & Resources and that's  a difference (if I'm not mistaken)

**Comment by vshcherb** [comment]
We agreed to change in Android to ```Maps & Resources```
CC @sonora
