### ISSUE TITLE
World_altitude_correction stays in actualization panel. 

### ISSUE THREAD

**Issue by Tchiller** [osmandapp/Osmand#1908]
I always have one item in the panel for map actualizations. I can't get rid of it and have actualized it several times. 

The map is called "Höhenkorrektur (weltweit)" which could be translated to "altitude correction (worldwide)". OsmAnd shows me a map date of 08.07.2005. In the panel "all downloads" it has a black "08.07.2005 1.6 MB" and an orange "Lokale Version 13.11.2015" written below. In the panel "local" is does not appear at all. 

I have taken a look onto my SD card and even deleted the file. Under /storage/external_SD/Android/data/net.osmand.plus/files I can only find a file World_altitude_correction_WW15MGH.extra which I have deleted (with no effect to the problem). 

Is there some way to get rid of this behaviour? Thanks in advance!

**Comment by sonora** [comment]
Yes, the "World_altitude_correcetion_WW..." file is the one in question. Deleting it, then restarting the app  or the device should resolve the issue. Then downloading it again via the OsmAnd App should actually work without reproducing the issue.... ?!

**Comment by Tchiller** [comment]
That is exactly what I have done. It looked fine for a little time, now it is back in the "updates" list.

**Comment by sonora** [comment]
What app version do you report this for?
Thanks - Hardy

**Comment by Tchiller** [comment]
Version: OsmAnd+ 2.1.1
Published: 2015-06-20

**Comment by sonora** [comment]
Same as issue #1909. The fix is ready will be released very soon.

**Comment by vshcherb** [comment]
I will close that issue in the matter of fact that it could be validated.
