### ISSUE TITLE
Semicolon separator gets read out from the navigation

### ISSUE THREAD

**Issue by Tchiller** [osmandapp/Osmand#1909]
If a street uses the semi-colon (http://wiki.openstreetmap.org/wiki/Semi-colon_value_separator) in order to use something like ref=3:4 for a street which belongs to two routes, the navigation voice reads this semicolon. I am hearing something like "please turn left on road three semicolon four" which should not be the way to parse that. 

Thanks for your work. Much appreciated!

**Comment by sonora** [comment]
I think I already fixed that months ago, but it is not yet in our release version. Please report if you are using the release (like from the Play store), for now the fix is only in our nightly build.

**Comment by Tchiller** [comment]
I am using the current version of the android Play store. I will show patience than until the fix gets released. Thank you very much.

**Comment by sonora** [comment]
We are getting ready for the next release the fix will be included.  :-)

**Comment by vshcherb** [comment]
I will close in the matter of fact that it could be validated.
