### ISSUE TITLE
Show `cuisine=fish` separately from `cuisine=seafood`

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/OsmAnd#19098]
The key `cuisine=fish` should shown as `Dish:Fish` in OsmAnd.     
At the moment the fish restaurant is shown as seafood restaurant.

Example:     
https://www.openstreetmap.org/node/1838455251     

![Screenshot_20240213-130253](https://github.com/osmandapp/OsmAnd/assets/9936160/da6063c7-4d26-43e1-9b68-2ced3190e9ac)

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. Dish: Seafood is displayed instead of Dish: Fish.

OsmAnd~ 4.7.0#1594m, released: 2024-02-14

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/d3dd0edd-1bb7-4d24-b7a8-0d76902b8722"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by dmpr0** [comment]
## ToDo

OsmAnd show `cuisine=fish` as `cuisine=seafood`.

Examples:
* Seaside  – `cuisine=fish`,  https://www.openstreetmap.org/node/4508185226
* Austernbank  – `cuisine=seafood`, https://www.openstreetmap.org/node/542575908

<table style="width:100%">
  <tr>
    <th colspan=2>Seaside</th>
    <th colspan=2>Austernbank</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/b11175e8-9a9b-4695-9f2e-1acebe3c6304"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/1eac48b9-58f9-4b1f-b786-971b5b25402a"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/dfa6e659-9dbc-437e-86f9-9645275720f1"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/a6ea0ede-78a3-4013-a566-7c2dbc534730"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by xmd5a2** [comment]
Place to test: https://www.openstreetmap.org/node/10750556331
Map: Luxembourg

**Comment by hakuchi** [comment]
@xmd5a2 tested with Lukembourg map 03.2024 but it shows seafood...

**Comment by xmd5a2** [comment]
> @xmd5a2 tested with Luxembourg map 03.2024 but it shows seafood...

Yes, it is not done yet

**Comment by xmd5a2** [comment]
Issue is ready to test

**Comment by yuriiurshuliak** [comment]
The bug has been fixed. The Dish: Fish tag is now displayed.

OsmAnd~ 4.7.0#1802m, released: 2024-03-11

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/cbf7eaa3-46c4-4f3a-b0dc-71fe79445b6b"  width="300" height="auto"/> </th>
  </tr>
</table>
