### ISSUE TITLE
level is shown as floor instead of addr:floor

### ISSUE THREAD

**Issue by teacupmaps** [osmandapp/OsmAnd#19105]
### Description

the text under "Floor" in the poi menu is the value of "level" tag, not the "addr:floor"

### Steps to reproduce

open the poi: 
BarBaris
Гарматна вулиця 29/31, Київ
Розташування: geo:50.44733,30.43328?z=17
https://osmand.net/map?pin=50.44733,30.43328#17/50.44733/30.43328

or any poi with the level tag

### Actual result

Floor: 0

### Expected result

Floor: 1

### Your Environment (required)

OsmAnd~ 4.6.12

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. Here is a link to OSM: https://www.openstreetmap.org/node/10554050924

OsmAnd~ 4.7.0#1617m, released: 2024-02-17

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/16166876-b5ad-4cbd-80a4-ef4861d6a195"  width="300" height="auto"/> </th>
  </tr>
</table>
