### ISSUE TITLE
Map language is only applied if zoomed in

### ISSUE THREAD

**Issue by qwerty287** [osmandapp/OsmAnd#19106]
### Description

In map settings, I configured osmand to use the local names of places, but this is not working as intended: on a zoomed out level, my system's language is used.

### Steps to reproduce

1. Set map language to local language
2. Zoom out

### Actual result

Example from US, zoomed out ("Vereinigte Staaten von Amerika" = "United States of America" in German, my system language):
Zoomed out:
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/80460567/ad2ddc80-7fe8-4165-b891-42ba56fd447a"  width="300" height="auto"/> </td>
  </tr>
</table>

Zoomed in:
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/80460567/c2182104-49a5-40a8-99b7-5b05b5f09752"  width="300" height="auto"/> </td>
  </tr>
</table>

### Expected result

Both show the local name.

### Your Environment (required)

OsmAnd Version: 4.5.10 from f-droid
Android/iOS version: 12
Crash-Logs: app does not crash

**Comment by DmitryAlexei** [comment]
On Android with **Map language = local names** option enabled, local names are displayed only starting from 7th zoom. On iOS, local names are displayed from the 2nd zoom level. 

<table style="width:100%">
  <tr>
    <th>iOS TestFlight 4.7.1.9 </th>
    <th>OsmAnd~ 4.7.0#1603m, released: 2024-02-15 </th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/2d93910c-003e-4b8f-85ae-53cd43d2010c"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/2caf33ca-54cd-487d-8370-e1d506894394"  width="300" height="auto"/> </td>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/450d47f9-81aa-4e2e-95fb-95315afcdc3a"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/33ebb6e4-c5d3-4ed2-8a3e-f3e1e868a964"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
@scaidermern it's not a regression it was always designed and work as now. For basemap < 7 zoom Application language is used to comfort users not familiar with different writing systems and then local names are used
