### ISSUE TITLE
Track editing menu: all options dispapear when switching a track "invisible"

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#19108]
### Description

Tapping a track which is displayed on the map and then tap "visible" to "off", all options from the menu disappear, the menu changes into an empty page. Can not switch the track to "visible" again (or anything else from this section of the menu).

### Steps to reproduce

do as describrd

### Actual result

as describred, all options disappear

### Expected result

don´t do so ;-)

(never before it was like this - it was always possible to switch a track "invisible" and see, if it perhaps covers/hides another track - and switch it "visible" again (as long as you didn´t exit this menu)

![Screenshot_20240214_185328_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/95540936/5844f896-9a4f-4350-a8c9-9e089cdfec18)

### Your Environment (required)

OsmAnd Version: +4.7.1, ~4.7.0#1588
Android/iOS version: 13
Device model: S20+, Tab S6

**Comment by smirnov-d-a** [comment]
I can confirm that.
Moreover, just switching to _Track_, _Points_ or _Options_ tabs and then back to _Overview_ also produces the same effect as described above.

**Comment by zipav** [comment]
OsmAnd Nightly 4.7.0#1672m, released: 2024-02-26

### Steps to reproduce

- Menu
- My Places
- Tracks
- select a track
- show on map
- Open the Track context menu
- tap on the Hide button

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/576fdcb6-5bb2-4bac-85f4-3fb4a6fff228"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by dmpr0** [comment]
## ToDo
- [ ] Fix
