### ISSUE TITLE
Improve GPX navigation with TCX addon

### ISSUE THREAD

**Issue by sierrabobusa** [osmandapp/Osmand#1910]
Osmand has long offered the ability to navigate GPX files.  The preferred GPX file, GPX Track, does not provide street name annunciation.  TCX,  a variant of GPX created for Garmin devices, does provide this information and more.  I propose that Osmand allow the upload of TCX files.

Using a route planning service such as RideWithGPS, a bicyclist or motorcyclist can plan a ride that is then shared with many others through an online service.  The planned event includes a printable cue sheet with turns and street names.  This ride can be exported as a GPX or TCX file.  The TCX file includes the cue sheet as well as the GPX track file.

Adding TCX compatibility to Osmand would provide a dramatic increase in the utility of the app.  It would merge the street name annunciation capability of the main Osmand navigation function with its secondary ability to navigate GPX tracks, but without street name annunciation.  Please consider this as an extremely important upgrade.  

Archived issues have addressed this desired function, but have not correctly identified the problem and the solution.  Adding TCX compatibility will provide the user with the ability to navigate a planned route using street names plus additional words (e.g., rest stop, caution, water) included in the cue sheet development process.

**Comment by vshcherb** [comment]
OsmAnd still displays current street name (correct me if I'm wrong), but the biggest issue we experienced  to attach GPX route to existing map data (where we can take all possible information, like speed info etc).

**Comment by vshcherb** [comment]
Regarding TCX I would ask if someone knows what is the format is it and where it is possible to read about it.

**Comment by sierrabobusa** [comment]
Please find more detailed information on both GPX and TCX files as described by the RideWithGPS route planning service:

http://ridewithgps.com/help/export-file-formats

Also, for a sample TCX file with turn alerts at 300 ft and15 mph average speed, please click the following:

https://drive.google.com/file/d/0B8L-LCq1__heeE5FUng1c2tSdk0/view?usp=sharing

This is a GPX track file of the same routing:

http://ridewithgps.com/routes/11073251

Note that the preferred GPX file type is GPX track, as this consists of the many turns used to create a course.  Osmand will not provide street names with this file type.  The other GPX file type, GPX route, will provide street name annunciation when used with Osmand; however, this is not optimal as Osmand may recalculate the original plan between points.

**Comment by sonora** [comment]
I think I had implemented the capability that we display and announce location names contained in GPX.
