### ISSUE TITLE
Multiple no left turn restrictions are not respected correctly

### ISSUE THREAD

**Issue by Vucumpra** [osmandapp/OsmAnd#19107]
### Describe the routing engine used (required)

OsmAnd's in-app offline routing

Hello, OsmAnd don't respect follow turn restriction :

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/156325356/43877243-baad-417c-9f57-84a66a8c9deb"  width="500" height="auto"/> </th>
  </tr>
</table>

Here, route proposed by OsmAnd for car :(
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/156325356/e1c886c4-cb7b-4dcc-a9e4-48abf720bfbd"  width="300" height="auto"/> </th>
  </tr>
</table>

Global position : 
https://osm.org/go/0EqqPjeeM--?m=

### Describe your routing Profile (required)

Car routing
Other option change nothing, the error is already present.

### Describe your start and end points (required)

https://osm.org/go/0EqqPjeeM--?m=

### Describe the actual route (required)
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/156325356/2bb6ab23-6fde-40e0-aaa6-60e3899fc572"  width="300" height="auto"/> </th>
  </tr>
</table>

### Describe the expected route (required)

Ok, just no turn left on first crossing

### Describe what Maps you used (online or offline) (required)

- [ ] Offline maps offered within the OsmAnd app for download.
- [ ] February

### Your Environment (required)

```
OsmAnd Version: latest
Android/iOS version: 11
Device model: One+ Nord 100
```

**Comment by yuriiurshuliak** [comment]
Kindly specify exactly where you think the turn restriction should be. Also, indicate the current turn restriction on OpenStreetMap at https://www.openstreetmap.org/way/1192673686#map=19/50.64249/5.57745.

For reference, here is a link to our web version: https://test.osmand.net/map/?start=50.642320,5.577400&finish=50.643800,5.578030&type=osmand&profile=car#17/50.64331/5.57459

**Comment by Vucumpra** [comment]
Hello, I'm not sure that I understand your request.

So, the route proposed by Osmand is not correct :
![SS_20240219_142702-88](https://github.com/osmandapp/OsmAnd/assets/156325356/91e7410c-2bf4-49ae-911e-576f7d86adf8)

The good route :
![SS_20240219_142605](https://github.com/osmandapp/OsmAnd/assets/156325356/6287072c-92ce-4509-b62e-e86bef583469)

In this point ( https://osm.org/go/0EqqPjfk4?m= )  I think that the interdiction is coded correctly in the openstreetmap database

**Comment by yuriiurshuliak** [comment]
I attempted to reproduce the bug under various conditions, including both with and without live updates. Furthermore, I cross-verified the routing on OpenStreetMap and our web version. Unfortunately, in all scenarios, the route displayed differently, highlighting a clear discrepancy and an issue with the route calculation.

Link to OSRM: [Directions on OSRM](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=50.64226%2C5.57737%3B50.64362%2C5.57863#map=17/50.64355/5.57716)
Link to the web version: [Web Version](https://test.osmand.net/map/?start=50.642260,5.577370&finish=50.643700,5.578340&type=osmand&profile=car#17/50.64344/5.57498)

OsmAnd~ 4.7.0#1648m, released: 2024-02-22

<table style="width:100%">
  </tr>
  <tr>
    <th>Without live updates</th>
    <th>With live updates</th>
    <th>Web version</th>
    <th>OSRM</th>
  </tr>
  <tr>
  <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/bc03263e-9bc3-459a-9b73-99835e4d893a"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/5ddda8a3-75f8-4c94-8607-58764aca242e"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/4178992c-cf94-4f9b-90f6-cb70092833d6"  width="400" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/c876e57b-367f-4544-835b-ce5bf73b438f"  width="400" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
This issue looks very strange 
as https://www.openstreetmap.org/relation/16159765 properly handled 
but https://www.openstreetmap.org/relation/16133752 not handled correctly

**Comment by Vucumpra** [comment]
@yuriiurshuliak The good version without route error is OSRM !
The fisrt example (OsmAnd without liveupdate) have a problematic first turn right

**Comment by vshcherb** [comment]
It's already fixed https://test.osmand.net/map/?start=50.642260,5.577370&finish=50.643700,5.578340&profile=car#17/50.64344/5.57498
