### ISSUE TITLE
Wikidata tag is present - no Wikipedia link (Photos fixed)

### ISSUE THREAD

**Issue by mariush444** [osmandapp/OsmAnd#19112]
### Description

https://www.openstreetmap.org/way/787883229#map=19/27.51707/41.70358&layers=D

this object has definition of wikidata but osmand doesn't show this.

### Steps to reproduce

* find castle at `27.51706, 41.70337`
*  tap on it. (Saudi Arabia map)

### Actual result

<img src="https://github.com/osmandapp/OsmAnd/assets/66887280/b7a42705-bbc1-4030-9bfb-fe85b5ce55ca"  width="300" height="auto"/> 

* "nearby wikipedia" is only shown.

### Expected result

direct info and photo from wikipedia should be shown

### Your Environment (required)

```
OsmAnd Version: 4.5.10
Android/iOS version: 11

```

**Comment by goldfndr** [comment]
Removed: #9671

**Comment by goldfndr** [comment]
Planned: #18845

**Comment by DmitryAlexei** [comment]
@mariush444 are there any images in Wikidata by the link?
https://www.wikidata.org/wiki/Q22689273

**Comment by mariush444** [comment]
There is a tag
wikimedia_commons	File:قلعة عيرف.jpg

**Comment by vshcherb** [comment]
There is tag wikimedia commons so it's a bug

**Comment by vshcherb** [comment]
Photo is displayed

**Comment by vshcherb** [comment]
Unfortunately it will be hard to do because wikidata will bloat the data with links to all possible translations. It's better to add wikipedia tag manually to OSM
