### ISSUE TITLE
Objects complying to boundary=protected_area && protect_class=14 are differently treated by OsmAndMapCreator 3.0

### ISSUE THREAD

**Issue by Chefche** [osmandapp/OsmAnd#19119]
### Description

Hello:
I used OsmAndMapCreator 3.0 to convert .osm files into .obf.
I am especially interested in objects complying to boundary=protected_area && protect_class=14.
I wonder about the different treatment of those objects, i.e.
[204145192](https://www.openstreetmap.org/way/204145192) is transferred into the .obf file but
[925545733](https://www.openstreetmap.org/way/925545733) is not transferred into the .obf file.
Is this by some intention that I cannot guess?
Thanks and best regards

### Steps to reproduce

1. Download OSM for the considered area and store it into an .osm file.
2. Open the .osm file by an editor and look for the considered protected area. Most probably it can be found, then continue with 3.
3. Convert the .osm file into an .obf file.
4. Check the created .obf file with inspector.sh -vmap -vmapobjects -osm for the considered protected area.

### Actual result

[204145192](https://www.openstreetmap.org/way/204145192) is transferred into the .obf file but
[925545733](https://www.openstreetmap.org/way/925545733) is not transferred into the .obf file.

### Expected result

I would prefer to have all objects complying to boundary=protected_area && protect_class=14 in the OsmAnd Map, since they are recently used to register seasonal or not seasonal sanctuaries not only with no access but also with only discouraged access, especially interesting for winter ski touring or snow shoe hiking.
How they are rendered and enabled or disabled by which options is a different question. Primarily, these objects must be included in the map to be rendered at all.

### Your Environment (required)

OsmAndMapCreator 3.0

**Comment by vshcherb** [comment]
I don't know what's protect_class=14 and indeed we don't include all possible tags in the maps. 
As I see both have tags and I think they should be be indexed at least
Requires
--
boundary=protected_area or boundary=national_park

**Comment by xmd5a2** [comment]
Actually all of your examples are not added to obf data because of [this string](https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml#L6256)
`	<entity_convert pattern="tag_transform" from_tag="boundary" from_value="protected_area" if_not_tag1="leisure" if_not_tag2="nature" if_not_less_tag1="protect_class" if_not_less_value1="5" poi="no"/>`
It removes `boundary=protected_area` if `protect_class` is not less than 5.
This was done to limit quantity of protected areas because in some areas they are overwhelming a map making it less readable. May be this can be done more efficient way.

**Comment by xmd5a2** [comment]
Ok, I've added `protected_class` tag to obf data, removed mentioned rule and added hiding of some `protected_class`'es which are not rendered in osm-carto (according to [wiki](https://wiki.openstreetmap.org/wiki/Key:protect_class))

**Comment by Chefche** [comment]
I thank you very much. To display these areas will really be a great help.

**Comment by DmitryAlexei** [comment]
@Chefche may we consider this issue as resolved?

**Comment by Chefche** [comment]
Sure, thanks again.
