### ISSUE TITLE
The dialog for adding favorite point via quick action is broken

### ISSUE THREAD

**Issue by Prusaker** [osmandapp/OsmAnd#19116]
### Description

When adding a point to favorites using quick actions, the cursor is not displayed on the screen, with which you could indicate the location of the point on the map.

It was like that before:
![image](https://github.com/osmandapp/OsmAnd/assets/32092837/a2df7661-be73-4317-9fc3-9fc83fa78664)

Now in nightly builds, when you try to add a point, the cursor is not displayed on the screen, but a window immediately appears where you need to enter a name for the point.

### Steps to reproduce

Add quick action "Add to favorite" and try to create favorite point.

### Actual result

This is how a favorite point is added in OsmAnd nightly build 1603:
https://github.com/osmandapp/OsmAnd/assets/32092837/ac40b91c-b2d0-47a6-af3a-7a788cfbbe73
A window immediately appears asking you to enter a name for the point to be added. But before that, I cannot specify where on the map I want to add a point.

### Expected result

We need to return the add point dialog to the way it was before. It is necessary to be able to specify the position of the point to be added.

### Your Environment (required)

OsmAnd Version: OsmAnd Nightly 4.7.0 1603m 2024-02-15
Android version: Android 11
Device model: Lenovo TB-8506X

**Comment by yuriiurshuliak** [comment]
I tried to reproduce it from my end. It appears that the dialog window for adding a favorite doesn't actually show up. Instead, when you select the quick action, your favorite is automatically added to the center of the map, with the address or name of the location pre-filled.

OsmAnd~ 4.7.0#1617m, released: 2024-02-17

https://github.com/osmandapp/OsmAnd/assets/127092082/6fcf2071-ffc9-419a-ab84-d4131a1210ec

**Comment by dmpr0** [comment]
I can't reproduce the issue.
* Make sure Show interim dialog switch is On on action settings
* Positioning of the point should be done before taping on action

**Comment by Prusaker** [comment]
OsmAnd 4.7.0 1676. The bug is reproduced. Try to delete all actions and add quick action again. See below (tested at "clean" OsmAnd installation):

https://github.com/osmandapp/OsmAnd/assets/32092837/59763031-409a-4313-ac4f-a909d0a936cb

**Comment by yuriiurshuliak** [comment]
I can reproduce the behavior shown in the above video. When using quick actions to add a favorites, the cursor isn't visible on the screen, making it impossible to indicate the point's location on the map.

OsmAnd~ 4.7.0#1897m, released: 2024-03-22

https://github.com/osmandapp/OsmAnd/assets/127092082/599a288d-f0cc-425f-b471-5f02e64366a6

**Comment by vshcherb** [comment]
It's not broken it was always like that cause name was designed for non-dialog option. Though we need to fix it as it works unexpected

**Comment by vshcherb** [comment]
To do: for original quick action button (if it's only one - old one) we need to display selection dialog even for 1 quick action

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.7.0#2035m, released: 2024-04-10
Now for old quick actions, when you try to add a point, the cursor is displayed on the screen.

https://github.com/osmandapp/OsmAnd/assets/116079541/ccf1af05-cc02-486b-a8ba-c82702bcdc7e
