### ISSUE TITLE
OSMand uses incorrect time

### ISSUE THREAD

**Issue by NastyFlytrap** [osmandapp/OsmAnd#19128]
### Description

The public transport planning is completely useless because it always thinks its midnight and therefore it only recommends night buses and other things that run at midnight.

### Steps to reproduce

Try to use public transport planning

Have it recommend you night buses at 13:47 because it thinks the currebt time is always 0:00

### Actual result

It thinks 0:00 is the current time planning the route

### Expected result

It using the correct current time.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.5.10
Android/iOS version: 13
Device model: samsung a32 4g
Crash-Logs: ?
```

**Comment by teacupmaps** [comment]
what is the location you're routing in?

**Comment by NastyFlytrap** [comment]
> what is the location you're routing in?

Same issue in multiple european cities

**Comment by teacupmaps** [comment]
i can't reproduce in Bucharest

**Comment by NastyFlytrap** [comment]
![Screenshot_20240217_231441_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/43176063/92f503a7-1076-44fd-b6c2-9f1341c32657)
I can.

Notice how the random starting location i picked says 0:00 as what i assume to be 'current time'. Starting time, but starting time is current time, yea.

**Comment by mariush444** [comment]
The problem is that osman has no time table. Just line and stops the it takes just shortest/fastest connection.
It doesn't take current time into consideration at all.

**Comment by NastyFlytrap** [comment]
> The problem is that osman has no time table. Just line and stops the it takes just shortest/fastest connection. It doesn't take current time into consideration at all.

Alright, but why isnt the other guy having the issue then?

**Comment by mikehgentry** [comment]
I've noticed that it'll take a diversion *to get you on a bus*, even if it would be quicker to just walk straight to the destination.

Very much still a feature in beta I think.

**Comment by sonora** [comment]
OsmAnd merely goes by map data to find routes you could take. There is no time table information available in the map data - what you see is the estimated **travel** time (always starting at 0:00), not the clock time! :wink:

**Comment by NastyFlytrap** [comment]
> OsmAnd merely goes by map data to find routes you could take. There is no time table information available in the map data - what you see is the estimated **travel** time (always starting at 0:00), not the clock time! 😉

Yea, i heard that earlier aswell but thats dumb. 
Look at the timetable, and compare it to my current time, because night buses dont exist at 2pm damnit.
Also, as i asked earlier, why isnt this an issue for the first guy then?

**Comment by yuriiurshuliak** [comment]
Unfortunately, timetable information is not available in the map data. The displayed time reflects estimated travel time, always starting at 0:00, rather than the actual clock time. Regrettably, this issue cannot be fixed since the necessary timetable information is not present in OpenStreetMap (OSM) data.

**Comment by NastyFlytrap** [comment]
> Unfortunately, timetable information is not available in the map data. The displayed time reflects estimated travel time, always starting at 0:00, rather than the actual clock time. Regrettably, this issue cannot be fixed since the necessary timetable information is not present in OpenStreetMap (OSM) data.

Okay then im asking for the third time.

Why isnt this an issue for the first guy then?

**Comment by NastyFlytrap** [comment]
> Unfortunately, timetable information is not available in the map data. The displayed time reflects estimated travel time, always starting at 0:00, rather than the actual clock time. Regrettably, this issue cannot be fixed since the necessary timetable information is not present in OpenStreetMap (OSM) data.

Okay then im asking for the third time.

Why isnt this an issue for the first guy then?

**Comment by sonora** [comment]
Because your issue is simply flawed ... :wink:  Both of these statements are false:

> It thinks 0:00 is the current time planning the route

- Not true, as explained above.

>  it only recommends night buses and other things that run at midnight.

- Not true, I see plenty of non-night busses also shown.

So "_i can't reproduce in Bucharest_" is quite plausible, I probably couldn't either if I was in Bucharest.  :wink: 

Again: OsmAnd has so far no access to a time table where it could look up when a bus runs or does not. OsmAnd simply shows all connections there are, independent of the time of day your are running the query.

**Comment by vshcherb** [comment]
Night buses schedule is  a duplicate for https://github.com/osmandapp/OsmAnd/issues/6700. For GTFS schedules there is another issue but anyway OSM doesn't support GTFS so it becomes tricky for OsmAnd to support it as well.

For the rest, as answered 0:00 means beginning of intervals not an actual time. I don't think it's very confusing for many people.
