### ISSUE TITLE
and arrive at your destination (too soon)

### ISSUE THREAD

**Issue by RussNelson** [osmandapp/Osmand#1912]
I'm not sure how best to describe this routing problem in 2.1.1. Several times I have been routed into a turn, and immediately after zero distance routed back onto the main road. I don't understand why it does that, but .... that's not my issue. My issue is that it announces "turn right and arrive at your destination". This can happen any number of miles from my destination.

My speculation is that the zero distance turn back onto the main road is triggering the "arrive at your destination" message.

**Comment by sonora** [comment]
Russ, just t make sure: It does not announce "After x miles, turn right and arrive at your destinarion", right?

In principle, I would be interested in running your tests with the latest nightly build, as both voice prompts and routing have been changed (I hope improved  :-)) to some extent, and we need some testing before the next release on the google Play store. So maybe you want to give it a shot, or at least report specific locations where you find bugs with v2.1.1

Thx  - Hardy

**Comment by RussNelson** [comment]
Unfortunately, I don't recall the exact location where this happened. I would shrug it off except that it happened several time in the last week. It was definitely "After x miles, turn right and arrive at your destination" because I remember thinking "wait, no, it's nowhere near that close." Then, when I got close, it said "Turn right and arrive at your destination".

**Comment by RussNelson** [comment]
Mmmmm, this is not the case you're thinking of. There were many turns remaining. And the "turn right" was spurious. It was more like "turn right and arrive at your destination. After 0 miles turn right". Obviously I need to reproduce this. Next time it happens I'll make a note of the location.

**Comment by shadow-identity** [comment]
@sonora @RussNelson have same bug sometimes for at least last 5-6 months. Now I'm on 2.1.1 Pro and this problem is 100% reproducible for several crossings. For example, yesterday I've moved on the belt way, and OsmAnd said I should **turn right then after 0 meters turn right** and I'll be at the destination point (really destination point was at 10 km). And what is ugly, really I was should not turn right at all, more, I should be at left three lanes.
![screenshot_2015-11-24-18-35-44](https://cloud.githubusercontent.com/assets/1223112/11389429/b0f96f6a-9351-11e5-9f17-999921cad620.png)

There is the map: http://www.openstreetmap.org/?mlat=53.8334&mlon=27.6107#map=15/53.8334/27.6107

**Comment by sonora** [comment]
The new release is just out. Is it unchanged in v2.2.x ?

**Comment by shadow-identity** [comment]
@sonora , tested it today on latest stable OsmAnd Pro and maps and it was here: http://www.openstreetmap.org/?mlat=53.95532&mlon=27.63982#map=18/53.95532/27.63982&layers=N

Instructions was: turn right then after 0 m turn left and destination point.

**Comment by sonora** [comment]
Ok, this sounds like a duplicate (or at least relative) of Issue #1871,and several other issues we have out there about "Offline routing". his needs a bit more research, I think it is in our roadmap to address these promptly after the current context-UI changes have stabilized, i.e. release 2.3+.

**Comment by vshcherb** [comment]
Related to #1871, should be addressed together ( this issue will be visible there)
