### ISSUE TITLE
Use system font everywhere

### ISSUE THREAD

**Issue by ghost** [osmandapp/OsmAnd#19123]
### Describe the idea (required)

currently osmand's ui uses a mix of its own font and the system font.
i've marked the system font in green and osmand's font in orange on this screenshot:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/158172547/a545a365-12d5-412f-a345-59f5926758d8"  width="300" height="auto"/> </th>
  </tr>
</table>
even the font for elevation and distance is different.

### Tell us about the expected behaviour (required)

the system font is used on the map (like google maps) and in all ui (like in organic maps)

### Tell us about alternatives you've considered (required)

- only use the system font for the whole ui, but not on the map, like organic maps does?
- only use osmand's own font?

### Context (optional)

my system font is samsung choco cooky, i like it

**Comment by yuriiurshuliak** [comment]
I attempted to change the system font, and now both the system font and the app font appear to be displayed in a mixed.

OsmAnd~ 4.7.0#1634m, released: 2024-02-20

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/c3f4f07a-362a-46b5-8a47-ad82c73cd5c1"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Vucumpra** [comment]
> ## ToDo
> 
>     * [ ]  Use system font
> 
>     * [ ]  Replace **Roboto Medium** with Medium / Bold text style.

Hello, I'm not sure what you mean by "Use system font".
Note that on my phone (and many other devices) Android does not allow the user to change the system font. So if the future version of OsmAnd only uses the system fonts, for many users it will be the same as today.
A better alternative would be to let users import their preferred TTF font file into osmand, and then let them choose whether to use it for the GUI, for maps or for both.

**Comment by teacupmaps** [comment]
> In addition of this new functionality, it is imperative to generate a slider to adapt the font size, independently of the android system.

why, don't all devices have this in system?

**Comment by Vucumpra** [comment]
Switching font maybe generate a different scale.
I see this on my KDE desktop. I leave _Noto_ font and switch to _Barlow Semi Condensed_.
After this action, while de font size was the same (12pt), the visually result will be different. Heigh letter are smallest on _Barlow_ font.
So, additional slider implemented on OsmAnd is imperative.

**Comment by dmpr0** [comment]
# Review
- [ ] Replace bold with medium

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/start-with/first-steps#how-to-enable-system-fonts

**Comment by vshcherb** [comment]
**First steps** -  bad place for system fonts. Reverted.
