### ISSUE TITLE
Navigation by track from finish to start using attach to roads

### ISSUE THREAD

**Issue by Biker729** [osmandapp/OsmAnd#19132]
When starting the navigation, the road guidance is displayed correctly.

After activating the "Snap to roads" option, only a direct 
direct connection line from the location to the first waypoint is displayed.

Is there a possibility to execute the option "Snap to roads" still at the location
and also navigate to the first waypoint (starting point) without displaying a direct
direct connection line is displayed.

![1](https://github.com/osmandapp/OsmAnd/assets/146021011/b2e051e1-05fc-4765-9f59-01eb86c45cdf)
![2](https://github.com/osmandapp/OsmAnd/assets/146021011/42b118be-e45f-4fdf-a0a8-075e516c45e0)

---------------------------------------------------------------------------------------------

Beim Start der Navigation wird die Straßenführung korrekt angezeigt.

Nach betätigen der Option „Auf Straßen einrasten“ wird nur eine 
Direkte Verbindungslinie vom Standort zum ersten Wegpunkt angezeigt.

Gibt es eine Möglichkeit die Option „Auf Straßen einrasten“ noch am Standort auszuführen
und sich auch zum ersten Wegpunkt (Startpunkt) navigieren zu lassen ohne dass eine
Direkte Verbindungslinie angezeigt wird.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by Biker729** [comment]
The nightly version solves this problem.
When will it be available in the OsmAnd+ Pro version?
Can I use the Nightly version with my OsmAnd+ Pro version ?


Die Nightly-Version löst das Problem.
Wann wird es in der OsmAnd+ Pro Version verfügbar sein ?
Kann ich die Nightly-Version mit meiner OsmAnd+ Pro Version benützen ?

**Comment by Biker729** [comment]
?

**Comment by DmitryAlexei** [comment]
@Biker729 You can use Pro subscription with Nightly builds

**Comment by Biker729** [comment]
How can I use my Pro subscription with Nightly builds?

**Comment by yuriiurshuliak** [comment]
Register your OsmAnd Cloud account : OsmAnd Menu → Settings → OsmAnd Cloud → Create new account
After that, use your email as a login to activate OsmAnd Pro on your Nightly build: OsmAnd Menu → Settings → OsmAnd Cloud → I already have an account.

**Comment by Biker729** [comment]
Thank you very much

**Comment by Biker729** [comment]
After trying again with the Nightly version, the problem occurs again:

After activating the option "Align to streets"
only a direct connection from the location to the first waypoint is displayed.

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.7.0#1733m, released: 2024-03-03
[2_5278265728745615672.gpx (2).txt](https://github.com/osmandapp/OsmAnd/files/14482090/2_5278265728745615672.gpx.2.txt)

### Steps to reproduce
- start navigation using gpx track
- go to navigation > settings > navigation settings > follow track menu 
- choose your track for navigation 
- select **Revers track direction** option and attach track to the roads

### Actual result
- track is attached to roads as if it was in original (not in reverse) direction
- see video
- the need to select a track in the follow track menu looks redundant for me 

https://github.com/osmandapp/OsmAnd/assets/116079541/f607565e-c9da-46f9-8d26-614287b2cb82

**Comment by Biker729** [comment]
My problem:
If the starting point of my track is several streets away from my location
and I start the navigation, I want to be navigated from the location to the starting point.
Navigation type: External BRouter-offline

**Comment by Biker729** [comment]
https://github.com/osmandapp/OsmAnd/issues/19132#issue-2141136430

"Attach to roads" is necessary because otherwise every little turn will be announced.

**Comment by Biker729** [comment]
The problem that only a direct line is displayed from the starting point to the first waypoint 
only occurs in the setting: "Navigation type: External BRouter-offline"



Das Problem dass vom Startpunkt zum ersten Wegpunkt nur eine direkte Linie angezeigt wird 
kommt nur in der Einstellung vor: „Navigationstyp: Externer BRouter-offline“

**Comment by vshcherb** [comment]
Based on testing only 2 out of 8 scenarios work. The easiest way to test is to draw a route that goes next to my location (50-100m) and try all combinations of 3 options for navigation and simuations:
1. Reverse / non-reverse point
2. Navigate to start point / closest point
3. Build route / straight line.

**Comment by Biker729** [comment]
The route is displayed correctly in the Offline - Motorcycle navigation mode.
In der Navigationsart Offline - Motorrad wird die Route korrekt angezeigt.

The route is not displayed correctly in navigation mode BRouter (offline).
In der Navigationsart BRouter (offline) wird die Route nicht korrekt angezeigt.


![1](https://github.com/osmandapp/OsmAnd/assets/146021011/bb126787-c463-42b0-a66b-353eeca859a8)

**Comment by DmitryAlexei** [comment]
what is your Brouter profile? Also see https://osmand.net/docs/user/navigation/routing/brouter#osmand-version-471

**Comment by Biker729** [comment]
my Brouter profile is: car-fast.brf & driving-cruiser.brf

**Comment by Biker729** [comment]
I have tried different BRouter route profiles,
with route profile "fastbike" & server mode "motocar_short" the route is displayed correctly.

The easiest would be if OsmAmd would provide a customized route profile for BRouter motorcycle, bicycle, car.

![22](https://github.com/osmandapp/OsmAnd/assets/146021011/cd8c243e-f04b-4e14-bd6b-790103703384)


Habe mal mit verschiedenen BRouter Routenprofil probiert,
mit Routenprofil „fastbike“ & Server-Modus „motocar_short“ wird die Route korrekt angezeigt.

Das einfachste wäre wenn OsmAmd ein angepasstes Routenprofil 
für BRouter Motorrad, Fahrrad, Auto zu Verfügung stellen würde.

**Comment by Biker729** [comment]
Due to your hint "What is your Brouter profile?" 
I have experimented with different BRouter route profiles 
and with route profile "enduro, fastbike, gravel, mtb" & server mode "motocar_short & motocar_short" 
in BRouter, the route is displayed correctly in OsmAnd.

I use the navigation type Offline "External BRouter (offline)" because the route calculation 
with "Offline Motorcycle" after "Snap to road" took more than 5 minutes depending on the route length.

With Extern BRouter, the route calculation with "Snap to road" takes 
takes less than 1 min, depending on the route length.

Now, after trying again with "Offline motorcycle" after "Snap to road"
the route calculation is completed much faster.

I will continue testing with the navigation type "Offline Motorcycle" and maybe 
I may no longer need "External BRouter (offline)".
