### ISSUE TITLE
Following a gpx track in reverse direction and attached to roads is not possible

### ISSUE THREAD

**Issue by RheinSkipper** [osmandapp/OsmAnd#19131]
### Description

I want to navigate a gpx track in reverse direction and attached to roads.
It is possible to navigate my track either in reverse direction or attached to roads, but not both.

### Steps to reproduce

- select an imported gpx track on the map
- select navigation icon
- select settings
- select Follow track
- activate Reverse track direction
Now the route preview looks correct
- select Attach to the roads
- press Continue
- press Apply (after calculation completed)
Now the route preview is not reverse direction anymore.

### Actual result

Navigation along gpx track while "attached to the roads" is always in normal direction.

### Expected result

Navigation along gpx track while "attached to the roads" should be in reverse direction if reverse direction switch is on.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.6.13
Android/iOS version: 13
Device model: Samsung S24 or CarlinKit T-Box
Crash-Logs: no crash
```

**Comment by zipav** [comment]
OsmAnd Nightly 4.7.0#1764m, released: 2024-03-06

### Steps to reproduce

Select track > Navigation > Settings > Follow track > Attach to the roads > Continue > choose profile > Apply


https://github.com/osmandapp/OsmAnd/assets/123936521/4caca853-ec61-415c-ba21-37389ec65bf2

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/19132
