### ISSUE TITLE
construction is avoided

### ISSUE THREAD

**Issue by RussNelson** [osmandapp/Osmand#1913]
While driving on I-787, OSMAND tried to route me off the Interstate and around a section of the road tagged construction=motorway and highway=construction . Tags have been removed because the construction is finished, but you can see them in the history here: https://www.openstreetmap.org/way/25290784/history

I'm not quite sure why this is happening. I speculate that the "construction" tags are being interpreted as "not open yet". I think some people put highway=construction on roads that don't exist yet because they're under construction. nfgusedautoparts tagged it because, although they exist, they're being REconstructed. Tagging shouldn't be ambiguous. If it is, then we need to correct the people who are using tags ambiguously.

**Comment by sonora** [comment]
Well, as a matter of fact http://wiki.openstreetmap.org/wiki/Key:construction#Values states:

As OSM data is often used offline (and therefore may be several months old), only tag construction sites (particularly roads and railroads) if they are planned to be closed for at least six to nine months. Don't use construction=* to tag short-term closures (e.g. a road closed over a weekend to replace a sewer pipe); consider using conditional restrictions instead.

I am not sure I can think of a good strategy of how we deal with situations where people are not sticking with this guideline when tagging things ...

**Comment by vshcherb** [comment]
The general rule to draw existing highway and new construction next to each other, if there is another road is building. For the case some lanes reconstructed I actually don't know exact mapping, but may maxspeed:proposed that what could be used to reflect the sutuation.

**Comment by RussNelson** [comment]
Thanks. This was minor work, and was tagged improperly. I've contacted the editor, who is a friend of mine.
