### ISSUE TITLE
Rendering.  A city surrounded by water is flooded on the map.

### ISSUE THREAD

**Issue by snooppr** [osmandapp/OsmAnd#19133]
### Description

It seems the problem only affects the v1 rendering engine.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/61022210/7a60a7e3-2f8c-422a-a999-c5c36757d60d"  width="600" height="auto"/> </th>
  </tr>
</table>

On the left is the rendering engine v1.  The problem is that the city is flooded with water (false).  On the right is the v2 opengl rendering engine, true.

https://github.com/osmandapp/OsmAnd/assets/61022210/5ab44832-a390-4136-80f0-ca85e9bc5b25
Scrolling engine v1.

another example:

<table style="width:100%">
<tr>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/61022210/eabca505-bf0f-4d42-a956-fbd48fb44891"  width="300" height="auto"/> </td>
  </tr>
</table>

### Steps to reproduce

Select engine v1 and check out the rough terrain: https://www.openstreetmap.org/node/499635446

### Actual result

on some scales osmand says the city is flooded.

### Expected result

see screenshots above.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: f-droid
Android/iOS version: LOS16 
Device model:
Crash-Logs: ?
```

**Comment by Nine-Tailed** [comment]
there is also a problem on the version 2 engine
![Screenshot_2024-02-19-01-16-27-040_net.osmand.jpg](https://github.com/osmandapp/OsmAnd/assets/12549744/73a9ae1d-efec-4cd2-95f9-c378b0b44688)

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. On Version 1 of the rendering, the area is completely flooded, on Version 2 of the rendering it is partially flooded.
Here are the coordinates: 53.24988222637783, 50.37470237391456

OsmAnd~ 4.7.0#1634m, released: 2024-02-20

<table style="width:100%">
  </tr>
  <tr>
    <th>Version 1</th>
    <th>Version 2</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/14688ca8-20e7-47de-a254-1ea08f7c81fa"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/a59648f7-84d4-4a6a-8efe-699464995b76"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by xmd5a2** [comment]
Not reproducible anymore with today's OSM data. I suppose that some "natural=coastline" object existed here for some time. This is known to cause such errors in OsmAnd.
Should be fixed in march maps.

**Comment by yuriiurshuliak** [comment]
I checked this issue again, with live updates and without live updates. Also on two rendering versions. There are no changes, everything is displayed as flooded on the phone.

OsmAnd~ 4.7.0#1718m, released: 2024-03-01

<table style="width:100%">
  </tr>
  <tr>
    <th>No live updates</th>
    <th></th>
    <th>With live updates</th>
    <th></th>
  </tr>
  <tr>
  <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/fdb3455a-0c73-4b87-8a79-03da09136c1e"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/af361f1c-9782-478a-933a-b4c33a0e75c1"  width="350" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/240fcf68-5742-4cb5-80e6-c3e02217c70a"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/fb590115-0943-4892-89ea-b06a81a8e845"  width="350" height="auto"/> </th>
  </tr>
</table>
