### ISSUE TITLE
OsmAnd+ sometimes crashes when I try to export

### ISSUE THREAD

**Issue by johnmcd88** [osmandapp/OsmAnd#19140]
### Description

Sometimes when I select 'Settings/Export to File', the app pauses for a few seconds, then when I try to select/check items to export the app crashes (not hangs - crashes). Sometimes it happens 2-3 times in a row, then works fine the next time I try.

### Steps to reproduce

select 'Settings/Export to File', select items to export

### Actual result

App crashes
[logcat.log](https://github.com/osmandapp/OsmAnd/files/14334900/logcat.log)

### Expected result

Allow items to be selected and exported

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd+ 4.6.13, Release 2024-01-19
Android/iOS version: Android 12
Device model: OnePlus Nord N20
Crash-Logs: Logcat output attached

**Comment by yuriiurshuliak** [comment]
Unfortunately, we could not find the cause of the crash in the logs you attached. Please attach Crash logs files immediately after application crash: Menu → Help → Send crash log (Send logcat log)

**Comment by albansuser** [comment]
I also experience a problem with Export. It writes the export file to the Temp directory but no longer initiates the save exported file in user specified folder routine.

As a temporary fix, I manually copy the exported file to where I want it.

OsmAnd~ 4.7.0#1653m, released: 2024-02-23 and previous.
Samsung Galaxy s22 running Android 14.

Cheers

**Comment by yuriiurshuliak** [comment]
I tried to reproduce yours export issues. As I see now, there is a problem with the progress bar, the percentages and the download line are not displayed there. However, everything else works correctly, the crash does not occur and the file is saved in the folder.
So, please attach a video of how it happens from your end.

@albansuser Also provide us more steps for your problem. Specify the size of the file you are exporting and clarify what you mean by Temporary directory.

OsmAnd~ 4.7.0#1655m, released: 2024-02-23

https://github.com/osmandapp/OsmAnd/assets/127092082/8f48f301-2001-43b7-a306-82e2fd2f3e1f

**Comment by albansuser** [comment]
"@albansuser Also provide us more steps for your problem. Specify the size of the file you are exporting and clarify what you mean by Temporary directory."

Reponse:
Normal export of settings via System - Export to File - then select options and Continue. The export proceeds as normal until final step where normally the user selects preferred destination folder.  Instead "Could not export file" is displayed. 

The temporary directory I referred to is the "temp" folder in the "net.osmand.plus" directory.

Export file  sizes range from 600MB to 1500MB.
