### ISSUE TITLE
Map Language not using correct

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/Osmand#1914]
I use OsmAnd+ 2.1.1 and latest offline maps.

If I set Map Language to German, the map show German names, but for navigating use and display(next turn) only Italian names.
If I set to Italian, the map shows Italian names and for navigating use only "name=..." and if no "name:it=..." is present, OsmAnd use/display(next turn) "name:de=..."

With "name=..." "name:de=..." and "name:it=..."
http://www.openstreetmap.org/way/29899813
http://www.openstreetmap.org/way/40504242

with "name=..." "name:de=..." but without "name:it=..."
http://www.openstreetmap.org/way/41678743

http://www.openstreetmap.org/way/29899813
![Image with wrong name:de](http://fs5.directupload.net/images/user/151115/orquwwwz.png)
in next turn not display "Itaienalle". OsmAnd display Italian name "Corso Italia"

**Comment by vshcherb** [comment]
I think that bug duplicated and it might be already fixed, need to find confirmation.

**Comment by hakuchi** [comment]
Can this are a problem with the data of the map?
Some months ago with older maps I think it worked normaly.

Can I download older maps from this region somewhere to test this bug?

**Comment by hakuchi** [comment]
I tested this map and location with the latest nightly.
Same bug as 2.1.1

I received from a friend a older map from this location.
On these old map, the next turn are displayed correct.

So the bug is from OsmAnd during converting map from OSM to OsmAnd.

**Comment by crimean** [comment]
Fixed. Will be available with maps update soon.
