### ISSUE TITLE
After failed OSM upload, "Try again" fails to clean up

### ISSUE THREAD

**Issue by ceever** [osmandapp/OsmAnd#19148]
### Description

If an OSM upload of POI changes fails, e.g. due to missing WiFi, the consequent "Try again" uploads the POI changes but ultimately fails to directly cleanup the local POI changes list. Then retrying to upload the still existing POI changes will crash OsmAnd or duplicate the POIs in OSM. However, after any restart of the OsmAnd (e.g. due to the crash), the POI list becomes empty.

I think the solution to the problem is the proper cleanup after successful "Try again". However, maybe one should also have a look at why OsmAnd crashes when trying to delete an already just deleted POI.

### Steps to reproduce

1. Have a list of POI changes (including some deletions)
2. Try uploading the POI changes to OSM while offline => Error overlay box with "Try again" option (see 1st screenshot)
3. Connect to the internet and push "Try again"
4. Wait for the upload to finish and observe the list of POI change (everything is still there)
5. Try a POI change like "delete POI" and try upload again => crash
6. Scenario 1: Crash => see POI changes being empty now
7. Scenario 2: Restart OsmAnd => see POI changes being empty now

Screenshots in the order of procedure:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/40247591/3a24d46d-707a-4bd4-a1a7-986531f3ff51"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/40247591/cb17f190-e020-4919-a049-6ffe3a1cd9da"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/40247591/542c6015-a996-4047-b7b5-de212cdbe074"  width="300" height="auto"/> </th>
  </tr>
</table>

<table style="width:100%">
  <tr>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/40247591/4b8737fc-41f0-40b0-86b3-ac6374b46887"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/40247591/b3b93137-b4f5-4bfb-8c0a-91972bec3ea1"  width="300" height="auto"/> </th>
  </tr>
</table>

### Actual result

1. POI changes list remains unmodified despite successful "Try again" upload of POI changes.
2. OsmAnd crashes when trying to re-delete a POI

### Expected result

1. POI changes list becomes empty immediately after successful "Try again"
2. OsmAnd does not crash on a POI delete in case the POI has already been deleted (through the "Try again" procedure before)

### Your Environment (required)

```
OsmAnd Version: 4.6.12
Android/iOS version: 9
Device model: Galaxy S8
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
@ceever Could you please export  a list of your OSM notes and POIs so we can reproduce the issue on our side? Please export your OSM POI changes and OSM notes from My Places → OSM Edits → Bottom panel → Share button.

**Comment by vshcherb** [comment]
Let's see if that https://github.com/osmandapp/OsmAnd/issues/19985 will close this issue
