### ISSUE TITLE
Cross Country Ski Trail

### ISSUE THREAD

**Issue by QuestionsForThose** [osmandapp/OsmAnd#19150]
### Describe the idea (required)

Whilst there is a filter for Ski this does not find cross country ski trails, nor can I find a filter that will. 

### Tell us about the expected behaviour (required)

There needs to be a distinction in the Ski filter to find Cross Country trails

### Tell us about alternatives you've considered (required)

Cannot find this using any tools

### Context (optional)

Cannot even be found using Nearest POI filter

**Comment by vshcherb** [comment]
Indeed they are not very popular in OSM - https://overpass-turbo.eu/s/1HQf. And currently we only display from OSM, so these are authorized Cross Country Ski Trail. 
Though you can still find them in Germany for example
