### ISSUE TITLE
Display ref=* instead of local_ref=* for bus stops

### ISSUE THREAD

**Issue by dafadllyn** [osmandapp/OsmAnd#19156]
Numbers or letters of bus stops  are mainly tagged with `ref=*`—analoguous to numbers or letters of (railway) platforms. Therefore please display `ref=*` instead of the less common tag `local_ref=*`. See also https://wiki.openstreetmap.org/wiki/Key:local_ref.

**Comment by sonora** [comment]
It's tricky, see here: https://wiki.openstreetmap.org/wiki/Key:local_ref. How things are actually tagged varies with regional habits, perhaps we need a priority strategy or even display both.

**Comment by vshcherb** [comment]
Not sure we need to change it as OPNV uses local_ref as well

**Comment by dafadllyn** [comment]
I've learnt in the meantime (see [discussion](https://www.openstreetmap.org/changeset/147785844) in German) that contrary to what is stated on [the wiki](https://wiki.openstreetmap.org/wiki/Key:local_ref) `local_ref=*` is still more frequently used to tag the letter or number of a bus stop (edge).

The reason for this is that before PTv2, `ref=*` on `highway=bus_stop` has been used to store the reference number of the whole bus stop area (i.e., bus stops with the same name), like on `railway=station` or `amenity=bus_station` while `local_ref=*` has been used to store the number or letter of a specific bus stop (edge) in that stop area, in the same way `ref=*` has been (and still is) used on `railway=platform` or `highway=platform`.

However, [PTv2](https://wiki.openstreetmap.org/wiki/Proposal:Public_Transport) introduced `public_transport=platform` as a replacement for both `railway=platform`/`highway=platform` *and* `highway=bus_stop` and definied `ref=*` as the number or letter of the platform/edge/waiting area. That is, it redefined `ref=*` on bus stops, thus introducing an incompatibility with PTv1. Because almost all bus stops are now tagged `highway=bus_stop` + `public_transport=platform`, the meaning of `ref=*` has become unclear. As `local_ref=*` is unambiguous, it seems better to stick with that tag and display it on OsmAnd.
