### ISSUE TITLE
Tracks info it seems to reindexing after each Force stop?

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#19151]
### How to reproduce
* Import few track to OsmAnd
* Restart OsmAnd with Force stop 

### Actual result
<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Before Restart</th>
        <th>After restart</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/d37a6793-5b77-4478-a152-c51621dd3794"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/9d8ee6ce-d8e7-413b-90b5-e9201397bb7f"  width="300" height="auto"/> </td>
        <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/c39f7a10-2bf9-4ec1-83b3-e58f73af3e05"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

* All **stats data**, **appearance**, **visible track** – is missed for some time
* Log file – [logcat (1) (2).log](https://github.com/osmandapp/OsmAnd/files/14342795/logcat.1.2.log)
* Tracks https://t.me/c/1193274712/8479

### Expected result
* All data should be available after restart for previously imported tracks

**Environment**
OsmAnd Version: 4.7.0#1631m 4700
Android: 14
Device model: Pixel 6A

**Comment by sonora** [comment]
I think this is #17805. And iit seems reindexing may happen not just at every new app start, but even in addition _every time you enter the My tracks screen_, and again when you enter the 'Visible on map' tracks screen.
