### ISSUE TITLE
Do not switch profile during initial Route calculation 

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#19166]
Testing it more and more, I think the change that was made last years, I do not feel comfortable at all.

Initially profiles were assumed mostly for **active navigation**, so in case I calculate car route it doesn't mean I'm ready to go with Car I just want to see the route. Though over time implementation has changed

**Negative impact** that I feel with current solution:
- Switch of all preconfigured widgets when I just want to see any route
- Switch between day/night map mode
- Switch map orientation that for viewing route is not good as mostly preffered to view with North Up

I couldn't backtrace in which issue it was introduced so please feel free to comment

**Comment by Rowin63** [comment]
My 2c to the "north up" issue are in here #18805
And the switching from day to night bothers me too sometimes. A little bit.

**Comment by scaidermern** [comment]
Not sure why this needs a new ticket instead of reopening and fixing #18805 but great to hear that this change will be reverted!

**Comment by dmpr0** [comment]
Hi, @vshcherb ! 
Did you try to switch **Default profile** to **Last used** in **Menu** – **Settings** – **OsmAnd Settings**?

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/18805 Nope this won't be implemented cause we need special "mode" of route planning which is not planned for now. Instead I propose to not change App profile when you didn't start navigation, so it will keep using Browse Map profile.

**Comment by sonora** [comment]
> I propose to not change App profile when you didn't start navigation, so it will keep using Browse Map profile.

Yes! Thank you Victor!  :wink:

**Comment by dmpr0** [comment]
> @dmpr0 - changed to last used, no changes I see.

That means you don't start Navigation.

**Comment by vshcherb** [comment]
https://docs.osmand.net/docs/user/navigation/setup/route-navigation#start--stop-navigation
``` Once start and end points are selected, the app will create a route between them using active profile. ```
```Once start and end points are selected, the app will create a route between them using active profile. App profile (link) and widget set ... will only switch once you click Start navigation ```

**Comment by EugeneZmeuk** [comment]
**23.05.2024**
- [ ] [Start/stop navigaton](https://docs.osmand.net/docs/user/navigation/setup/route-navigation#start--stop-navigation)
