### ISSUE TITLE
Track overview dissapears when reloaded

### ISSUE THREAD

**Issue by spaanse** [osmandapp/OsmAnd#19169]
### Description

The track overview dissapears when switching tabs or hiding a track

### Steps to reproduce

Select a track
Go to the Track tab
Go back to the overview tab

or

Select a track
Hide the track

### Actual result

The track overview dissapears, window stays open

### Expected result

The track overview remains visible

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.7.2 (2024-02-13)
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by spaanse** [comment]
https://github.com/osmandapp/OsmAnd/assets/19549928/1c18aa81-13f1-4a07-bc89-76005c01137e


https://github.com/osmandapp/OsmAnd/assets/19549928/c7aa766a-04f8-48a3-b218-9427986b8c7a

**Comment by DmitryAlexei** [comment]
duplicate of https://github.com/osmandapp/OsmAnd/issues/19108

**Comment by spaanse** [comment]
Closed as duplicate
