### ISSUE TITLE
Android Auto navigation-session get's out of sync when hardware-back-button is being used

### ISSUE THREAD

**Issue by ntruchsess** [osmandapp/OsmAnd#19168]
### Description

In Android-Auto, during an active navigation (on NavigationScreen) clicking the (hardware-)back-button of a rotary-device does cause the NavigationScreen being popped from the stack of active screens. The LandingScreen then will be the visible screen on top of the stack while the active navigation session continues. As the Landingscreen doesn't have a stop-button there is no way to cancel the running navigation in this situation.
Starting a new navigation and then stopping it by clicking the stop-button doesn't resolve the issue reliably. There is a 50/50 chance the RoutePreviewScreen is visible only for a moment before the NavigationScreen becomes active (without clicking 'start' on the RoutePreviewScreen). When this happens klicking 'stop' will end the navigation-screen but instead of the LandingScreen the RoutePreviewScreen will show (with no route to start).

The issue can be reproduced also on the desktop-head-unit being startet with --input=rotary and simulating a hardware-back-keypress by hitting the 'back'-key on the keyboard (see https://developer.android.com/training/cars/testing/dhu for details)

this behavior has previously been reported as a secondary issue in #17353
see comments:
https://github.com/osmandapp/OsmAnd/issues/17353#issuecomment-1594261956
https://github.com/osmandapp/OsmAnd/issues/17353#issuecomment-1595843021

### Steps to reproduce

see description

### Actual result

see description

### Expected result

when clicking the hardware-back-button during an active navigation-session OsmAnd shouldn't do anything. Instead of navigating to the LandingScreen the current NavigationTemplate should just stay. What shall happen instead is that the focus of input-cursur should switch to the Android-auto buildin-menue-area. (This is what happens e.g. in Google-maps or other apps when hitting back while there are no other Screens on the stack).

### Your Environment (required)

```
OsmAnd Version: 4.7.1
Android/iOS version: 12
Device model: Samsung Galaxy S10
Crash-Logs: none, no crash.
```

**Comment by ntruchsess** [comment]
Analysis: the problem is that the NavigationScreen is on top of the LandingScreen on the ScreenManagers stack. Because of this the hardware-back-button will just pop that screen and the previous screen (the LandingScreen) becomes visible.

Solution-alternatives:
The best solution requires some refactoring: Instead of pushing the NavigationScreen on top of the LandingScreen the LandingScreen itself would switch the template from PlaceListTemplate to NavigationTemplate. Then there is no Screen to pop and the hardware-back-button will have no influence on the running apps screen stack and instead the focus will leave the application.
As a workaround the NavigationScreen would be started using pushForResult with an [OnScreenResultListener](https://developer.android.com/reference/androidx/car/app/OnScreenResultListener) that either does terminate the navigation doing propper cleanup of the existing references to NavigationScreen. Just setting the NavigationSession property navigationScreen to null from the OnScreenResultListener also does work. In this case the navigation continues and the next update of navigation-data will resume creating a new instance of NavigationScreen on the stack.

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.8.0#2093m, released: 2024-04-16
Steps to reproduce:
- android auto should be set up using ./desktop-head-unit --usb -i, --input=rotary
- simulate navigation using .gpx track
- pres back (backspace) button on the keyboard (same as (hardware-) back-button on a rotary-device)

Actual result:
- after hitting "back" button user was redirected to the AA landing screen
- no "back" button on the landing screen is present, so user cannot get back to navigation on the full screen.
- if user hits "free ride" button, navigation stops. Although the user can continue navigation by hitting "resume" on the phone screen, but turn instructions will not be displayed (only voiced).



https://github.com/osmandapp/OsmAnd/assets/116079541/b160de79-999f-450d-91cc-4a74f8e100ee

**Comment by vshcherb** [comment]
If navigation is active, we need to add "COntinue navigation" as first item to select

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.8.0#2839m, released: 2024-07-25
When user clicks the hardware stop button on Android Auto head unit with rotary-device, he is being redirected to the landing screen, where “Continue navigation” is available as a first option 


https://github.com/user-attachments/assets/4970f380-2a0a-4d3e-9d9c-b44bef700f07

**Comment by dmpr0** [comment]
# Review 
- [ ] Crash [exception (2).log](https://github.com/user-attachments/files/16392113/exception.2.log)

**Comment by Chumva** [comment]
Crash should be fixes [here](https://github.com/osmandapp/OsmAnd/commit/b8688db9b776d563f16fc05a5cf4ff0c42dd9728)

**Comment by dmpr0** [comment]
### 



<table style="width:100%">
  <tr>
    <td><video src="https://github.com/user-attachments/assets/f1ed0f5e-0977-4151-8692-17d84e4389ec"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] Button "Continue navigation" appears only after hiding / showing side menu

**Comment by Chumva** [comment]
"Continue navigation" button visibility should be fixed [here](https://github.com/osmandapp/OsmAnd/pull/20464)

**Comment by dmpr0** [comment]
# Review

<table style="width:100%">
  <tr>
    <th>Current route template</th>
    <th>Continue navigation button</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/7f7bc075-5288-4701-a3b7-a06c41a4fe0a"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/b12a4461-340c-4ce2-8d81-7990f4582a00"  width="300" height="auto"/> </td>
  </tr>
</table>   

* Maybe we can show template with Start button instead of this? Currently there is no way to dismiss this Continue navigation button without taping it to then tap Stop on the next screen.
