### ISSUE TITLE
Add POI crash

### ISSUE THREAD

**Issue by franco999** [osmandapp/Osmand#1916]
When I want to create a new POI, the application is closed. I have Moto E XT1527 with Android 5.0.2 and OsmAnd 2.2.0#14311M 231

Attached: [exception.log.txt](https://github.com/osmandapp/Osmand/files/34912/exception.log.txt)
![crash](https://cloud.githubusercontent.com/assets/12088580/11169753/32732ba4-8b9f-11e5-9205-0912d5431eca.png)

**Comment by vshcherb** [comment]
Fixed already.

**Comment by vshcherb** [comment]
I hope after today OSM POI/NOTE functionality is completely stabilized so it should be good for testing.

**Comment by franco999** [comment]
Great, thanks!
