### ISSUE TITLE
Grid for buttons and widgets on the map screen

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#19164]
### Describe the idea (required)

positioning the user symbols (like quick action, 2D/3D switch, ...) in a nice line comparing to the other symbols is difficult. 
Some kind of "automatic grid" would be appreciated.

### Tell us about the expected behaviour (required)

user symbols nicely aligned to the other symbols

### Tell us about alternatives you've considered (required)

free positioning always looks a bit messy (you never get them aligned nicely)

### Context (optional)

thank you :-)

**Comment by mikehgentry** [comment]
I think a 'copy from another profile' option would be helpful too, I can open another ticket if that's out of scope for this one.

**Comment by dmpr0** [comment]
# Review 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/f2c16b28-ea2c-4e8a-b88e-8995a0c733d9"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  


- [ ] Buttons not aligned after moving

**Comment by DmitryAlexei** [comment]
related issue
https://github.com/osmandapp/OsmAnd/issues/21128

**Comment by dmpr0** [comment]
# Review 

<table style="width:100%">
  <tr>
    <td><video src="https://github.com/user-attachments/assets/f991b8db-aaa1-4734-b290-ffe2dbce40b0"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] First button is jumps on move

**Comment by dmpr0** [comment]
# Review 2 

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/67c5b07e-1dbd-4451-80d4-48c75851d78d"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] Wrong shadow angle

- - -

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/8554d012-1bf5-4291-a084-bf16f768390f"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/1fa1e6d3-9fa8-497c-998f-315592c62f02"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [ ] Additional padding form the right in RTL

**Comment by dmpr0** [comment]
# Review 3

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/13923533-97a4-4c33-98ec-4a915ef26e60"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] Zoom buttons is overlapping
- [ ] Different margins for Zoom buttons on the map and above the context menu

**Comment by Rowin63** [comment]
Issue is closed as completed, but when it wil be released?
~5.0.0#3803 still does not look like having a grid:

![Screenshot_20241126_080311_OsmAnd~](https://github.com/user-attachments/assets/168d2299-113c-463d-959b-39de02e9a569)

**Comment by vshcherb** [comment]
It has grid but it's flexible grid cells to align are 8dp, button size is 48dp. So you can perfectly align yourself. There will be no grid per button cause button could be different size.

**Comment by Rowin63** [comment]
Ah, I see. Thanks 👍

**Comment by DmitryAlexei** [comment]
https://osmand.net/docs/user/widgets/quick-action#change-position-on-the-map

**Comment by vshcherb** [comment]
Grid layout should be probably documented as separate section here - https://osmand.net/docs/user/widgets/map-buttons. We also already have specific layouts for portrait / landscape - inset / wide(?).

We need to explain which corners are positioned buttons. So each button is assigned to 1 of 4 corners and if not enough place it will start move from this corner horizontally and/or vertically. One example screenshot could be when widgets on the right fill up full space and will push buttons to the left for example

**Comment by TinaPohor** [comment]
@vshcherb I propose adding the new section “Grid layout for buttons” right after “Change Position on the Map” [the article](https://osmand.net/docs/user/widgets/quick-action)
The “Change Position on the Map” section already explains how buttons can be manually moved, so it is logical to follow it with an explanation that they are now also automatically aligned to the grid.

[**Current structure:**](https://osmand.net/docs/user/widgets/quick-action)

```
## Overview
## Quick Action Widget
    ### Add and Delete Actions
    ### Action Parameters
    ### Change Position on the Map
    ### Custom buttons
    ### Quick Action Button Appearance
## Action Types
    ### Configure Map
    ### Interface
    ### Map Interactions
    ### My Places
    ### Navigation
    ### Settings
## Use Keyboard for Actions
## Related Articles
```
[**Suggested structure:**](https://test.osmand.net/docs/user/widgets/quick-action)

```
## Overview
## Quick Action Widget
  ### Add and Delete Actions
  ### Action Parameters
  ### Change Button Position
  ### Grid Layout for Buttons
## Custom Buttons
  ### Button Appearance
## Action Types
  ### Configure Map
  ### Interface
  ### Map Interactions
  ### My Places
  ### Navigation
  ### Settings
## Use Keyboard for Actions
##Related Articles
```
