### ISSUE TITLE
Show content from `note=*` tag only if Note tags is On

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#19160]
### How to reproduce
* Open OsmAnd
* Go to `50.43795, 30.51307`

### Actual result

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Note tags – Disabled</th>
        <th>Note tags – Enabled</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/8010b95b-f548-49fe-8c17-1435de408526"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/f5b5a35f-e638-4f64-9791-f054a2b89cd4"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

* `note` tag is visible starting 18 zoom level

### Expected result

> From https://wiki.openstreetmap.org/wiki/Key:note
> _A note is used to inform other mappers about non-obvious information about an element,_
> _Standard maps normally don't show notes._

* Show notes if OpenStreetMap editing plugin is On and Note tags option is On

## ToDo

- [ ] Show data from `note=*` if 
* * OpenStreetMap editing plugin is On 
* * and Note tags option is On

**Comment by goldfndr** [comment]
Similar to #18736

**Comment by xmd5a2** [comment]
Fixed. Please update OsmAnd and retest. No new maps required.
