### ISSUE TITLE
Live update and added maps cause current map section to disappear

### ISSUE THREAD

**Issue by MiMoHo** [osmandapp/OsmAnd#19175]
### Description

When hourly live updates are enabled for all maps, the app is barely usable as the updates cause the map to disappear for 2 seconds every time a map is being updated regardless if it is the current map section or not.

### Steps to reproduce

Select several local maps at once and leave them downloading and installing in the background. Look at a map that is already available and wait for the other downloads to finish.

### Actual result

Every time a map is being added or updated in the back, the visible map extract will disappear for about 2 seconds. This is disturbing and hinders interaction and functionality.

### Expected result

Adding or updating maps must not affect rendering of other maps, especially when they are not bordering each other. Otherwise, with a dozen maps that have live updates enabled, the app is unsuable when it is opened or when the update timer kicks in.

### Your Environment (required)

```
OsmAnd version: 4.5.10
Android version: 14
Device model: Sony Xperia 5
Crash logs: no
```

**Comment by vshcherb** [comment]
Yes 4.5 could be easily the reason
