### ISSUE TITLE
Using "Plan route" causes problems

### ISSUE THREAD

**Issue by ReinerMeyer** [osmandapp/OsmAnd#19173]
### Describe the routing engine used (required)

- [ ] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Describe your routing Profile (required)

Car profile
[Fitnessland (Navigation route).zip](https://github.com/osmandapp/OsmAnd/files/14386380/Fitnessland.Navigation.route.zip)

### Describe your start and end points (required)

see above the file "Fitnessland (Navigation route).gpx

### Describe the actual route (required)

[2024-02-18_11-59_Sun (recorded track).zip](https://github.com/osmandapp/OsmAnd/files/14386412/2024-02-18_11-59_Sun.recorded.track.zip)

### Describe the expected route (required)

Hi, a deviation from the planned route caused an unnecessary detour.
The saved "planned route" (file "Fitnessland (Navigation route).gpx") was used for navigation. The route was left to the left at the B17/Handelsstraße intersection in order to reach the destination via Jochäckergasse (file "2024-02-18_11-59_Sun (recorded track).gpx"). As expected, the route was recalculated, but I was first supposed to drive to a point on the B18 and then drive the same route back to the destination (see screenshot).
I can't imagine that this is a feature, but a bug.
This strange behavior could be repeated.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/94683660/0e48562e-5c19-4a07-8155-0c3a7fd9c30e"  width="300" height="auto"/> </td>
  </tr>
</table>

### Describe what Maps you used (online or offline) (required)

- [x ] Offline maps offered within the OsmAnd app for download. 
- [ ] Online (tile / raster) maps 

### Your Environment (required)

```
OsmAnd Version: OSMAND+ 4.6.13
Android/iOS version: ONE-UI 5.1, Android Version 13
Device model: Samsung XCover 5, Modell name: SM-G525/DS


### Anything else? (optional)

_No response_

**Comment by ReinerMeyer** [comment]
There is also a directional error (see added picture).
At the traffic light crossing in Günselsdorf B18/B17 the direction of the turn is correct, but the destination is wrong. The correct destination would be "Wien;Traiskirchen".
![Screenshot_20240224_072240_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/94683660/a4ed9704-8a60-48e6-93dd-ebd1a2ded94a)

**Comment by ReinerMeyer** [comment]
There are 2 different aspects.
Aspect 1 concerns the recalculation of the route after leaving the original calculated route and the consequences of deviating from the originally planned route. As described above, the recalculation took place after I had turned off the Handelstraße into the Jochäckergasse. It was still about 300 m to the finish.

Aspect 2 (my addendum) concerns turning left from the B18 onto the B17 in the direction of Vienna, but where the destination to Wr. Neustadt|Graz is indicated.

These 2 aspects occurred simultaneously within the same route, although they are independent.
I hope I could explain better the 2 different aspects.

**Comment by yuriiurshuliak** [comment]
It seems there might be a difference in routing behavior when using a saved route for navigation versus selecting a point on the map. Consider joining our beta testing program to verify if the issue persists there. To sign up, visit: [Beta Testing Sign-Up](https://osmand.net/docs/versions/nightly_versions).

When navigating, try utilizing the "Attach to Roads" feature. Instructions on enabling this can be found here: [Attach to Roads Setup](https://osmand.net/docs/user/navigation/setup/gpx-navigation/#attach-to-roads).

For more insights, refer to the "Navigate by Track" documentation available at: [Navigate by Track Documentation](https://osmand.net/docs/user/navigation/setup/gpx-navigation/).
