### ISSUE TITLE
Tracker related issue. Telegram friends pins doesn't move on Osmand map

### ISSUE THREAD

**Issue by ferpg81** [osmandapp/OsmAnd#19176]
### Description

Using osmand from F-Droid, 4.6.12 (but some earlier versions too), and previous and curreny version of Tracker (0.91). Battery also unrestricted for tracker.

When any friends shares their location on telegram, location pin appears on map, but doesn't move. I observed if osmand is restarted, pin moves to current position, and also, if changing from day mode to night (or viceversa), the pin moves to current position.

### Steps to reproduce

I don't know how anyone can reproduce it, in my case is always.

### Actual result

Pin doesn't move naturally, I have to cause it as said before.

### Expected result

Pins moving naturally when contacts change their location, without any action done by me.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:4.6.12
Android/iOS version:14
Device model:Samsung Galaxy A33 5G
Crash-Logs: no crash logs
```

**Comment by ferpg81** [comment]
Issue remains on version 4.7.10.

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. When someone shares their location with me via Telegram, their icon shows up on the map, but it doesn't move in real-time. The pin remains stationary. However, if you restart the app and the person has changed locations, the icon updates to their new position.

Additionally, in the Timeline tab, you can see a track of the person's movements.

OsmAnd~ 4.8.0#2591m, released: 2024-06-26
Tracker (0.91)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/23f1836b-e6c8-43e1-aad8-d09af9d8c40d"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/46bd6c02-5952-45a8-88a7-c251e1670d06"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/9fe2924f-bc05-45a8-b970-4521e2a6eb5e"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by alberto4github** [comment]
Same problem from several moths ago. Last versions, all permissions,...

**Comment by DmitryAlexei** [comment]
Tested the last available Nightly version of OsmAnd tracker with OsmAnd~ 4.9.0#2879m, released: 2024-08-01
When OsmAnd tracker works - Friend's pins are moving on the OsmAnd map

But OsmAnd Tracker not always send location via telegram. In my case, 
- when **Sharing time is set to 1h**, location is frequently been sent for about 30 sec, then it stops. When Sharing 
On the screens below, you can see, that transmission of my location has stopped after about a minute. And I also stop to receive friend's location after a minute.
- when **Sharing time is set to 6h** or more - tracker works ok and pins moves
- logcat buffer Option is luggy. tracker freezes after opening tracker settings > Logact buffer (on my device it took more than 2 min to unfreeze)

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/195a5ac2-d3b9-4c62-b433-982ab58ca6a3"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/user-attachments/assets/af3269e5-213d-46e9-bfbc-6d14587f6199"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by ferpg81** [comment]
Tested today with Osmand 4.8.3 from F-Droid and Tracker 1.0 from GPlay. Problem remains with these versions.
