### ISSUE TITLE
Turn lanes - Turn left instead of Straight

### ISSUE THREAD

**Issue by ReinerMeyer** [osmandapp/OsmAnd#19178]
### Describe the routing engine used (required)

- [ x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Describe your routing Profile (required)

Car

### Describe your start and end points (required)

[Sat 24 Feb 2024.zip](https://github.com/osmandapp/OsmAnd/files/14392009/Sat.24.Feb.2024.zip)

### Describe the actual route (required)

[Sat 24 Feb 2024.zip](https://github.com/osmandapp/OsmAnd/files/14392010/Sat.24.Feb.2024.zip)

### Describe the expected route (required)

The attached image shows (red rectangle) the location of the incorrect routing instruction. There should be no instruction here or the direction should be straight ahead.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/94683660/cae37061-b313-4022-a41e-9d07351eff13"  width="300" height="auto"/> </th>
  </tr>
</table>

### Describe what Maps you used (online or offline) (required)

- [x ] Offline maps offered within the OsmAnd app for download. 
- [ ] Online (tile / raster) maps 

### Your Environment (required)

```
OsmAnd Version: OSMAND+ 4.6.13
Android/iOS version: ONE-UI 5.1, Android Version 13
Device model: Samsung XCover 5, Modell name: SM-G525/DS
```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. During point-to-point navigation with the coordinates (47.93309377972923, 16.210501291993477) to (47.93587854580459, 16.227779540937934), the turn line is displayed even though there is no actual turn at that location.

OsmAnd~ 4.7.0#1672m, released: 2024-02-26

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/88c0a390-0a18-4ef7-b1fb-7fd56f9293be"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/d2b54538-763c-44bf-9a0c-f2bb3aee1dcb"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by ivanPyrohivskyi** [comment]
Better to divide way [146372116](https://www.openstreetmap.org/way/146372116) on two.
Turn lanes instruction mistaken accept because way [146372135](https://www.openstreetmap.org/way/146372135) divide way on two segments with specific tag turn:lanes:backward.
In other case turn:lanes:forward will work fine.
File for look *.osm in JOSM:
[file.tar.gz](https://github.com/osmandapp/OsmAnd/files/14450991/file.tar.gz)

**Comment by vshcherb** [comment]
It's a regression since 4.5 and probably we will need to understand what caused it. To understand how to proceed with other turn lanes issues in future

**Comment by vshcherb** [comment]
Same as https://github.com/osmandapp/OsmAnd/issues/19343

**Comment by yuriiurshuliak** [comment]
The bug has been fixed. During point-to-point navigation, the incorrect turning line is no longer displayed.

OsmAnd~ 4.7.0#2031m, released: 2024-04-10

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/0770490c-027c-43b9-960a-a431b45313ed"  width="300" height="auto"/> </th>
  </tr>
</table>
