### ISSUE TITLE
Highlighted POIs filtered by tag disappear when leaving app

### ISSUE THREAD

**Issue by MiMoHo** [osmandapp/OsmAnd#19174]
### Description

When I search for an arbitrary tag, OsmAnd shows all relevant POIs on the map. When I change to a different app and return to OsmAnd or turn off and on the screen, the highlighted POIs are gone.

### Steps to reproduce

1. Download an arbitrary local map like Germany, North Rhine-Westphalia.
2. Search for an arbitrary tag like "vegan". OsmAnd marks the concerning POIs in orange on the map.
3. Switch to another app and back to OsmAnd or turn off and on the screen.

### Actual result

The orange-marked POIs are gone. You have to redo the search in order to see the filtered orange-marked POIs again.

### Expected result

The orange-marked POIs must persist as it is when filtering and displaying POIs by category. With the latter, the search bar disappears, though, when switching to another app and back to OsmAnd, so in order to hide the highlighted orange-POIs, one has to deactivate the "POI Overlay" in the map customization settings. Similar as with the tag issue: the search bar on the top must persist until the user either goes back, closes the search bar oder fully closes the app.

### Your Environment (required)

```
OsmAnd~ version: 4.5.10
Android version: 14
Device model: Sony Xperia 5
Crash-Logs: no
```

**Comment by DmitryAlexei** [comment]
cannot reproduce with nightly OsmAnd~ 4.7.0#1657m, released: 2024-02-23

**Comment by yuriiurshuliak** [comment]
To resolve the issue you've reported, we suggest verifying that your phone has the most recent version of the app installed.

Updating to the latest version typically incorporates bug fixes and enhancements that could potentially resolve issues and optimize the app's performance.

**Comment by vshcherb** [comment]
The issue is easy to reproduce and it even doesn't require app restart. Switching app to background causes search status bar gone.

**Comment by vshcherb** [comment]
I think we have more generic issue that it's probably ok to loose search status after app restart but we should keep same search bar and do not refresh screen if app was just brought back from background.

**Comment by Corwin-Kh** [comment]
Could not reproduce with specified steps on current version

**Comment by dmpr0** [comment]
# Review

<table style="width:100%">
  <tr>
    <th>Search bar</th>
    <th>After reopening the app</th>
    <th>Video</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/e18515a1-b69b-4028-ac29-65aef14e2520"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/59313905-f6ee-477a-84b0-5bb2a8b20746"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/7f1cd2d6-e3e4-4919-8dff-dc5750903fd6"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] Reproduced
