### ISSUE TITLE
Illogic/malfunction in filtering/finding POIs by tag

### ISSUE THREAD

**Issue by MiMoHo** [osmandapp/OsmAnd#19172]
### Description

There is illogic and missing results when filtering tags:

When I look up the tag "**organic**", I can either choose "yes" or "only". Most other tags like "vegan" or "kosher" do not differentiate here. When I go for "yes", I do not see stores that "only" have organic products although they are most of my interest.
It may be a good idea to let the user choose whether a store _only_ or _also_ has organic products so that I can exclude supermarkets that feature an organic selection although they are not completely organic, but the current either/or choice is counterproductive as the minor does not include the superior.

A sightly different issue is with **wheelchairs**. I can search for the "designated" value but won't find any results that are "wheelchair=yes". So the designated search option is redundant and not working. The value "limited" and "yes", however, do not find e.g. supermarkets with (limited) wheelchair access but primarily sports facilities.

Filtering **payment options** like cash and credit cards also works just for sports facilities.

### Steps to reproduce

1. Download a local map like Germany, North Rhine-Westphalia.
2. In the search field, type in "organic" and choose "yes".
3. In the search field, type in "wheelchair" and choose "yes" or "limited".
4. In the search field, type in "payment" and choose "cash" or "credit cards".

### Actual result

You won't find reliable results for the aforementioned specifications.

### Expected result

"Organic" -> "yes" should also include POIs with "limited" and "only" value.
"Wheelchair" -> "limited" should show all applicable POIs for "limited" and "yes"; "yes" only for "yes".
Payment options should show all applicable POIs.

### Your Environment (required)

```
OsmAnd~ version: 4.5.10
Android version: 14
Device model: Sony Xperia 5
Crash logs: no
```

**Comment by scaidermern** [comment]
If you open the filter in the search screen (top right, filter icon) you can select "yes" _and_ "only" in the organic section.

**Comment by yuriiurshuliak** [comment]
I attempted to reproduce the reported issues by searching for tags like "organic," "wheelchair," and "payment" using different options like "yes" and "only." However, I didn't encounter the issues you described, as the expected results showed up during my tests. For better assistance, could you share additional details, like a walkthrough or an error video, illustrating the steps and discrepancies you're experiencing?

Also ensure that you have the latest version of the app installed on your phone.

OsmAnd~ 4.7.0#1718m, released: 2024-03-01

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/3712226b-8bef-4e4c-b188-423e14aedbba"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/7b035cc0-ecf8-4c9a-99b7-4f80df933a6a"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/7c57f8f8-1971-4a37-850e-2cdbd2dfa1b8"  width="300" height="auto"/> </th>
  </tr>
</table>
