### ISSUE TITLE
Marker on POI - display address 

### ISSUE THREAD

**Issue by MiMoHo** [osmandapp/OsmAnd#19177]
### Describe the idea (required)

Similar to proposal #10421, an address for a marker could be shown automatically in the line where it currently says "Map marker" (inbetween the marker's name and its current distance).
When a marker is set on an existing POI, they get connected so when I tap on the marker, it functions as if I tapped on the POI icon. However, I don't see the marker in the pop-up details on the bottom of the screen. This is unfavorable when several options come up that I tapped on due to a macro zoom level and have to figure out which is the one with the marker.

### Tell us about the expected behaviour (required)

"Map marker" does not have an added value and takes the line that could be used to show an automatically populated address from its location as it is the case with every POI I tap on that does not have an address noted inside.
The marker icon should show next to the POI's icon on the right-hand side when I select a marker connected to a POI. The same must be for favorites. I don't see a marker icon in the favorite's details on the bottom of the screen either.

### Tell us about alternatives you've considered (required)

Current unfavorable alternative is to write the address in the marker's title.

**Comment by vshcherb** [comment]
It's not clear from your description when you click on POI you see details from POI, so you could see address immediately.
