### ISSUE TITLE
In planning mode it is impossible to change the appearance of the track

### ISSUE THREAD

**Issue by snooppr** [osmandapp/OsmAnd#19196]
### Description

When planning a route, in the settings you can select/change the color of the track and the thickness of the line, but when you change nothing happens, the track remains configured by default (for me it’s blue thin).  Notably, Night mode defaults to orange and that doesn't change either.

The problem is that the user's tracks are divided by color, for example, red - running, blue - bicycle, green - car.  And when you are planning a route, you cannot choose the desired color, it is the default.  You can change the color of a track only after it has been created (and during planning, colors may overlap with existing tracks, blue and blue).

### Steps to reproduce

https://github.com/osmandapp/OsmAnd/assets/61022210/4d695126-5949-4fd3-8a9b-9c04f206cd9c

Main menu - route planning - create a new route - gear - route line settings - (choose any color, but it will not be applied, the default one will be).

### Actual result

When you select a track color, the track color does not change.

### Expected result

When you select a track color, the track color should change to the selected color.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: f-droid
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by zipav** [comment]
OsmAnd Nightly 4.7.0#1710m, released: 2024-02-29

### Steps to reproduce
Menu > Plan a route > Create new route > Settings button > Customize route line > choose the custom settings > Apply > Done


https://github.com/osmandapp/OsmAnd/assets/123936521/053d4f31-f635-4060-9eb6-867b668af0ea
