### ISSUE TITLE
Can't update or delete "World altitude correction" map

### ISSUE THREAD

**Issue by l0b0** [osmandapp/Osmand#1920]
I downloaded this map some time ago, and now whenever I go to the map updates screen it's listed there with a date of "08/07/2005" and a size of 1.6 MB. **If I try to update it, OSMAnd+ simply says it was successful, but it's still there (even if I refresh)**. It doesn't show up in the "Local" tab, so **I can't delete it**.

Using OsmAnd 2.1.1 on Android 5.0.2.

**Comment by hakuchi** [comment]
08.07.2005 is the latest actual file.
there existing no newer file!

**Comment by l0b0** [comment]
That doesn't explain why it's always listed in the updates, and why I can't delete it.

**Comment by vshcherb** [comment]
That issue is fixed in coming release, expected this or next week.
