### ISSUE TITLE
Tittle above "і" and "j" are missed for some cyrillic / latin names in online tiles

### ISSUE THREAD

**Issue by mitharp** [osmandapp/OsmAnd#19203]
### Description

Some Cyrillic letters are being rendered wrong at [OsmAnd Web Maps](https://osmand.net/map) and in the OsmAnd application if choosing Online tiles as the source of the maps. The dot over the Cyrillic letters **і** and **ј** is not rendered at all the zoom levels. Instead, the dot over the Latin **i** and **j** is present. It's not common to omit the dot over these Cyrillic letters.
The Turkish language is known to use dotted and dotless "i" as distinct letters, and it's correctly rendered in the maps.
Here's what a part of Europe looks like in OsmAnd.
![image](https://github.com/osmandapp/OsmAnd/assets/19957708/0d2edef3-38e2-42d2-9bbe-3dbb4b7cad3d)
And here's the (of course low-quality, but <ins>correct</ins>) [osm.org](https://osm.org/) rendering with the dots present.
![image](https://github.com/osmandapp/OsmAnd/assets/19957708/2a031869-4539-4d90-9eb0-777c2ab1143d)

### Steps to reproduce

Choose Online tiles as the map source in the mobile app. Or, open the [OsmAnd Web Maps](https://osmand.net/map) page in the browser. Locate the map over the country with its national language written in Cyrillic script. Captions will have the Cyrillic letters **і** and **ј** dotless.

### Actual result

Cyrillic letters **і** and **ј** are dotless.

### Expected result

Cyrillic letters **і** and **ј** are dotted.

### Your Environment (required)

```
OsmAnd Version: 4.6.13
Android version: 14
Device model: any
```

**Comment by DmitryAlexei** [comment]
See
- https://test.osmand.net/map/#7/44.308/20.890
- https://test.osmand.net/map/#8/49.838/24.623

**Comment by mitharp** [comment]
Thank you for the fix. Now it's correct on both the web and the app.
