### ISSUE TITLE
Add all POI icons to be selected for Favorites

### ISSUE THREAD

**Issue by infinity0** [osmandapp/OsmAnd#19204]
### Description

The icons given as options for a new favourite are limited and don't cover the full list of icons. For example, the icons for Video games (there are several: pac-man ghost, nintendo-style controller, PS2-style controller, two dice, etc) don't show up in any of the categories including Amenities.

### Steps to reproduce

1. Add a favourite for some random place on the map.
2. Try to change its icon to one of the Video games icons.

### Actual result

3. It's not possible.

A workaround is to first find a real POI on the map that uses the icon. For example the game shop "Game" has the PS2-style controller icon, that can be found in various places across the UK. Depending on the icon this might be very hard though.

3a. Add any "Game" store as a favourite.
3b. Add your original favourite from (step 1).
3c. The icon for "Game" (step 3) now appears in the icon history. You can now select this icon as the icon for your own favourite.
3d. Delete the "Game" store as a favourite since you didn't actually want it.

### Expected result

3. It is always possible, without doing the workaround supplied, which might be extremely impractical or infeasible depending on the icon you want.

### Your Environment (required)

```
OsmAnd Version: 4.5.10
Android/iOS version: irrelevant
Device model: irrelevant
Crash-Logs: irrelevant
```

**Comment by yuriiurshuliak** [comment]
Based on my investigation, it appears that when adding a favorite, the joystick icon (representing video games) is not available. This particular icon can only be saved in the history if the video games POI has been added to favorites beforehand.

OsmAnd~ 4.7.0#1718m, released: 2024-03-01

https://github.com/osmandapp/OsmAnd/assets/127092082/72448033-9de3-4d9e-8f3e-17d9a11393ab

**Comment by infinity0** [comment]
To be clear, many many icons are not available. It's not just the joystick. Even the pint glass icon (used for pubs in the UK) is not available.

**Comment by vshcherb** [comment]
That's a known limitation the list for icons will be too long and we need to create proper search for it and redesign categories.

**Comment by vshcherb** [comment]
We could names and icons hierarchy from Custom Filter. Special we can leave as is.
