### ISSUE TITLE
OpenGL: Red boxes all over

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#19205]
Not sure what these are, I get them with last night's build, and only when using the V2 engine. Seems these are areas around labels or something ..

![Screenshot_20240228-142147_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/845735/2cf7551a-d7a3-4cde-955d-9978a3990ace)

**Comment by Nine-Tailed** [comment]
in the osmand development plugin in the map texts section there is an option show debug information

**Comment by sonora** [comment]
Ah, that's it thank you!!

Looks like I had always only used that with the v1 engine, had never seen this effect it has under v2. :wink:
