### ISSUE TITLE
Search Radius

### ISSUE THREAD

**Issue by Scrat80** [osmandapp/OsmAnd#19211]
Why is the default search radius only 10km? Does OSM not have the ability to search for address all over the globe if I want? There should be a "global" search radius setting option.

**Comment by sonora** [comment]
In particular, the need for countless _manual increases_ is annoying: Search for a search string which has zero hits in your neighborhood. OsmAnd  asks you for _5 successive taps_ to manually increase the radius to 20km, 50km, 100km , 200km, 500km. That should happen _automatically_, if there are no or only few hits?

**Comment by Scrat80** [comment]
It hasn't been happening automatically for me. I have to manually extend the range.. at least going by how it has been for me.

**Comment by vshcherb** [comment]
Nope address is not 10 km, address is 100km or 1000km for some addresses. For POI from a category it's 10km radius by default

**Comment by TheAlex25** [comment]
> Nope address is not 10 km, address is 100km or 1000km for some addresses. For POI from a category it's 10km radius by default

Why can't the radius be 1000 miles by default? Simple solution in the code.

**Comment by sonora** [comment]
Cross-linking to https://github.com/osmandapp/Osmand/issues/25797.
