### ISSUE TITLE
When creating a new POI, POI types on the list disappeared.

### ISSUE THREAD

**Issue by franco999** [osmandapp/Osmand#1921]
When creating a new POI and pressing the icon label, POI types on the list is disappeared.

![poi](https://cloud.githubusercontent.com/assets/12088580/11172754/1e108e30-8beb-11e5-8c61-94545b4b533a.png)

**Comment by Barrocas** [comment]
This is being modified, we have to wait for it.

-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by franco999** [comment]
Great, sorry.

**Comment by vshcherb** [comment]
It has been fixed.
