### ISSUE TITLE
Don't change original GPX

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#19212]
## Extra task
- On **Actions** – **Share** return original track (if no appearance changed for this track i.e. default / group appearance shouldn't impact on original track export) 

## Description
After importing and then exporting track from OsmAnd, without performing any other operation track has changes:

> Main task https://github.com/osmandapp/OsmAnd/issues/19027

* Added additional information
* All custom extension changed to `osmand:`

### How to reproduce
* Import file  – [custom_extenstion.gpx.zip](https://github.com/osmandapp/OsmAnd/files/14433050/custom_extenstion.gpx.zip)
* In context menu tap on **Actions** – **Share**

### Actual result

<details>
    <summary>Original file</summary>

```
<wpt lat="37.5460870" lon="-77.4532843">
    <time>2023-06-07T12:31:35Z</time>
    <name>Test</name>
    <type>SOTM</type>
    <extensions>
        <osmand:address>Floyd Avenue (The Fan) 907, Richmond</osmand:address>
        <osmand:icon>place_town</osmand:icon>
        <osmand:background>circle</osmand:background>
        <osmand:color>#ff4e4eff</osmand:color>
        <test:country>United States</test:country>
        <test:state>Virginia</test:state>
        <test:telephone>(804) 828-0100</test:telephone>
        <test:postcode>23284</test:postcode>
        <test:start_date>Thursday, June 8, 2023</test:start_date>
    </extensions>
</wpt>
```

</details>  

<details>
    <summary>Export from OsmAnd</summary>

```
  <wpt lat="37.546087" lon="-77.4532843">
    <time>2023-06-07T12:31:35Z</time>
    <name>Test</name>
    <type>SOTM</type>
    <extensions>
      <osmand:country>United States</osmand:country>
      <osmand:address>Floyd Avenue (The Fan) 907, Richmond</osmand:address>
      <osmand:color>#ff4e4eff</osmand:color>
      <osmand:background>circle</osmand:background>
      <osmand:icon>place_town</osmand:icon>
      <osmand:postcode>23284</osmand:postcode>
      <osmand:telephone>(804) 828-0100</osmand:telephone>
      <osmand:state>Virginia</osmand:state>
      <osmand:start_date>Thursday, June 8, 2023</osmand:start_date>
    </extensions>
  </wpt>
```

</details>  

* `<test:telephone>` became `<osmand:telephone>`
* `<metadata>` part with `<name>` and `time` was added
 * Exported from OsmAnd – [custom_extenstion_export.gpx.zip](https://github.com/osmandapp/OsmAnd/files/14433047/custom_extenstion_export.gpx.zip)

### Expected result

* Don't change custom extensions

**Comment by vshcherb** [comment]
Nope this task is not correct. We don't have UI to change original or modified GPX with colors. So probably GPX wasn't changed and could be restored original during backup for example

**Comment by vshcherb** [comment]
To do: Export should retain original file with custom extensions. Note this is not about managing extensions, we shouldn't touch GPX during simple procedure Import / Export
