### ISSUE TITLE
Bicycle Router chooses an astonishing long footway

### ISSUE THREAD

**Issue by Peter0** [osmandapp/OsmAnd#19219]
### Describe the routing engine used (required)

- [×] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Describe your routing Profile (required)

Bicycle; kind of driving: balanced; no considering of height data; no use of motor highways; no stairways; avoid fords

### Describe your start and end points (required)

50.71414 7.11268
50.71306 7.11421

### Describe the actual route (required)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/2462058/03315c10-7ee5-4495-b117-01133f18b8ac"  width="300" height="auto"/> </th>
  </tr>
</table>

### Describe the expected route (required)

The router includes way #53157191 into its propose, resulting that more than half the way you are on a way tagged as foot=designated and highway=footway – without serious necessity. One could easily include way #1079606651 and ...2 instead. Placing destination a few meters more in the south results in route like this, already. Increasing medium/maximum driven speed at bicycle routing preferences by a huge amount (from 18 to about 40 km/h) doesn’t change the position of this tripping point, so I don’t believe the router thinks that dismounting quickens the thing by and large.

### Describe what Maps you used (online or offline) (required)

- [×] Offline maps offered within the OsmAnd app for download as of Feb. 2024, including live updates. 
- [ ] Online (tile / raster) maps 

### Your Environment (required)

```
OsmAnd Version: ~4.6.12
Android/iOS version: 9
Device model: Samsung Galaxy J5
```

### Anything else? (optional)

By occasion, I’ll test behaviour without live-updates. Experience: At https://github.com/osmandapp/OsmAnd/issues/17047 this made a difference.

**Comment by zipav** [comment]
OsmAnd Nightly 4.7.0#1815m, released: 2024-03-12

Not reproduced both with and without Live Updates (offline OsmAnd map). The result is the same:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/b1110838-3b14-4d15-883e-d030901f3515"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
Rouing has changed a lot in 4.7 release so we close this issue as it's not longer reproducible in 4.7
