### ISSUE TITLE
Configure screen label is half hidden

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#19226]
Re-tabling https://github.com/osmandapp/OsmAnd/issues/19049#issuecomment-1966060948:

> PS: There's a similar occurrence on our 'Configure screen' menu, here it"s cut off both at the top (by the Android status bar) as well as at the bottom by the OsmAnd profile icon bar.

![308100863-f06b3487-79c8-47f3-9fbc-4676550e97ab](https://github.com/osmandapp/OsmAnd/assets/845735/906f8839-04c9-45e6-b237-d9df946df475)

**Comment by mariush444** [comment]
probably you use bigger andriod fonts (settings in android GUI) than standard for your device

**Comment by sonora** [comment]
Yes same as already explained in #19049, this occurs on some devices and font sizes.

**Comment by sonora** [comment]
Checking all our menues, it seems we have no consistency and have different setup each to handle how the top of the dislog is displayed. We coild unify the look and feel some time. But it seems as of today none of the other menus have a similar display issue.

**Comment by mariush444** [comment]
![Screenshot_2024-03-03-17-35-10-06_014aeb6b5e04ee7837dcdaecc5244511](https://github.com/osmandapp/OsmAnd/assets/66887280/7191daa9-fa1f-4b66-8ef5-7350fbaca9fa)

**Comment by zipav** [comment]
OsmAnd Nightly 4.7.0#1764m, released: 2024-03-06
Android 12
Nokia 5.3

Reproduced only if to increase the font to the maximum value in the device settings and also zoom the screen to the "Large" size

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/137e391e-e209-4e54-b020-eeb7a3ac0d0f"  width="300" height="auto"/> </th>
  </tr>
</table>
