### ISSUE TITLE
Fake highway on our latest World Overview map

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#19227]
Spot it! 😉

![Screenshot_20240301-195234_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/845735/1d48fe66-ab00-4aad-837c-d9baa32a495f)

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. Try to download the World Overview map and navigate to these coordinates:

36.0013594253859, -5.605973423951756

OsmAnd~ 4.7.0#1726m, released: 2024-03-01

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/9e560e79-4dd0-4b56-882f-0d3dc5c6e217"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by xmd5a2** [comment]
Fixed by regenerating basemap. Should be available today.

**Comment by yuriiurshuliak** [comment]
Currently, the above highway is not displayed when the World Overview map is downloaded.

OsmAnd~ 4.7.0#1848m, released: 2024-03-16

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/2f00a655-8604-4832-a408-5c1b9ac2651d"  width="300" height="auto"/> </th>
  </tr>
</table>
