### ISSUE TITLE
Names on map in funny languages

### ISSUE THREAD

**Issue by 9662** [osmandapp/Osmand#1923]
![tmp_screenshot_2015-07-04-04-09-36-2089232011](https://cloud.githubusercontent.com/assets/13080040/11180580/16ce8db8-8c5c-11e5-9930-0cf7013332f7.png)

As per screenshot. My system language is English and display language is set to System.

OsmAnd~ 3.1.1 but this has been there for ages.

**Comment by hakuchi** [comment]
Your Maplanguage is set to Thai.

Fix:
Click in the left top corner on the left symbol.
Scroll down and change your "Map Language" to English

**Comment by vshcherb** [comment]
Can you explain please how did you enable it? Did you just install application ?

**Comment by 9662** [comment]
Map language is not Thai (which wouldn't explain the Armenian, I think, text over Italy). It is set to Local Names. Even so, if I set it to English it still does not come up in English (I want local names anyway, as I get around quite a bit).

For example:

![tmp_screenshot_2015-11-19-14-27-221544805576](https://cloud.githubusercontent.com/assets/13080040/11272002/0852c55e-8eca-11e5-8b2e-50b775153190.png)

Results in this:

![tmp_screenshot_2015-11-19-14-27-04-1455796578](https://cloud.githubusercontent.com/assets/13080040/11272012/29684110-8eca-11e5-951b-db36a5eda7b1.png)

**Comment by 9662** [comment]
The application has been installed for years, but it was accidentally removed and reinstalled once, on one of the 3.0 versions, a few months back.

**Comment by 9662** [comment]
And this problem has been present for months as well. IIRC, since the 3.x series. I just never got around to reporting it before.

**Comment by vshcherb** [comment]
I remember this problem was in 1.9, but it was fixed since then. We can't reproduce that issue on latest 2.2 release (please try beta release which is already out on Google Play)

**Comment by vshcherb** [comment]
Deprecated 2.2 release is out
