### ISSUE TITLE
Osmand +4.7.1 does not find existing favorites.

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#19235]
### Description

Sometimes existing favorites are not found. 
The search keeps spinning for minutes without result. The searched favorite exists in "my places".

### Steps to reproduce

Search an existing favorite.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/95540936/fc051166-b627-417e-933e-972343e54b99"  width="300" height="auto"/> </th>
  </tr>
</table>

### Actual result

Notghing found for minutes, search keeps spinning.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/95540936/dd3b58d5-bf9a-4d70-a023-b01e45bed3e5"  width="500" height="auto"/> </th>
  </tr>
</table>

Quit the search after about five minutes.

### Expected result

Find that favorite.

### Your Environment (required)

Android 12
Osmand +4.7.1

See the attached logfile, perhaps it helps.
Does not happen everytime. Sometimes it happens, sometimes not.
This time I quit the search after about five minutes.

[logcat.log](https://github.com/osmandapp/OsmAnd/files/14479291/logcat.log)

**Comment by yuriiurshuliak** [comment]
I could not reproduce this bug. Tried to reproduce it several times. All times, the search for favorites took place instantly and without delay.

OsmAnd~ 4.7.0#1752m, released: 2024-03-06

<table style="width:100%">
  </tr>
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/24f198af-8e57-45fc-a8fb-b7bf2620a208"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/d667e94b-edc2-4f71-bfa7-d11cd70a9a77"  width="300" height="auto"/>   </td>
  </tr>
</table>
