### ISSUE TITLE
add `indoor_seating` to POI details

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/OsmAnd#19231]
Osmand is supporting outdoor seateng but not `indoor_seating` on POIs

Example with booth taggings:
https://www.openstreetmap.org/node/3364670542

Please add this to OsmAnd

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.7.0#1733m, released: 2024-03-03
https://www.openstreetmap.org/node/3364670542 is tagged with indoor_seating=yes and outdoor_seating=no (that object was last edited 5 months ago)

### Steps to reproduce:
- go to 50.58241 12.63496 and tap on POI Fast food
- see the POI context menu 

### Actual result
- **indoor_seating=yes is not displayed**
- outdoor_seating=no is displayed
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/0f9abd45-dfe5-4285-849c-f2d0a80243ba"  width="300" height="auto"/> </td>
  </tr>
</table>


According to [tag.info](https://taginfo.openstreetmap.org/tags/indoor_seating=yes#overview) there are more than 77 k objects tagged indoor_seating=yes

**Comment by xmd5a2** [comment]
Fixed but maps are not done yet

**Comment by xmd5a2** [comment]
Map is ready for test

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.7.0#1848m, released: 2024-03-16 and TestFlight 4.7.2.8
Up-to-date Germany > Saxony map downloaded on both Android and iOS
- indoor_seating=yes tag added to POI details
- **tag is incorrectly displayed on iOS**: indoor_seating_yes:yes 

<table style="width:100%">
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/3c6b5ecb-1e3f-40a8-be24-d79b976c3155"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/83c58d4c-0c65-4986-835a-6b9529ac7db1"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
iOS 4.7.2.10 fixed

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/ceffeb60-cddb-45e7-beb1-1f04ff34c9c1"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
May be in future
