### ISSUE TITLE
OOM every place with large tracks collection

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#19234]
### Description

The app frequently crashes after starting. I'm panning around in the map and notice osmand getting slower and slower.
When this happens, logcat is busy for minutes!
After crash the app remains open and the search doesn't find existing favorites anymore. 
Then I restart the app and it works fine again. 

### Steps to reproduce

Don't know. 

### Actual result

Crash 

### Expected result

No crash. 

### Your Environment (required)

Android 13
S20+, Tab S6
Osmand +4.7.1

Sent already several logs to your support, without any response.

**Comment by yuriiurshuliak** [comment]
I attempted to locate the log files you mentioned using your email address, but unfortunately, they are not found in Zendesk or our mailbox, nor in the spam folder. 
Kindly attach the log files directly to this error report. If you can reproduce the issue, go to Menu → Help → Send logcat log. Additionally, providing steps to reproduce the problem and, ideally, a video of the sequence leading to the crash would be highly beneficial.

**Comment by Rowin63** [comment]
Hello!

I checked my gmail account and this are the last crashlogs I did send. I guess they probably all refer to this issue. Thanks!

[exception(3).log](https://github.com/osmandapp/OsmAnd/files/14480834/exception.3.log)
[exception(4).log](https://github.com/osmandapp/OsmAnd/files/14480835/exception.4.log)
[exception(5).log](https://github.com/osmandapp/OsmAnd/files/14480837/exception.5.log)
[exception(6).log](https://github.com/osmandapp/OsmAnd/files/14480839/exception.6.log)
[exception(7).log](https://github.com/osmandapp/OsmAnd/files/14480840/exception.7.log)
[exception(8).log](https://github.com/osmandapp/OsmAnd/files/14480841/exception.8.log)
[exception(9).log](https://github.com/osmandapp/OsmAnd/files/14480844/exception.9.log)

**Comment by yuriiurshuliak** [comment]
It's not entirely clear from the logs what the problem is. The last crashes seem to be Out of Memory (OOM) errors, indicating insufficient memory. It is advisable to check the amount of memory used, considering tracks, online maps, etc.

**Comment by Chumva** [comment]
App only has access to some part of RAM on device. You could add a ram widget to understand how much it uses. Also, do you have many big tracks or online tiles enabled?

**Comment by Rowin63** [comment]
Yes, both ;-)  (many tracks, some big ones, and Microsoft Earth Overlay)
We had that "OOM" issue last year very intense here #17290, but it was solved finally. Don´t want it to be back...

**Comment by Rowin63** [comment]
It didn´t happen for some time now, but finally OOM is back.
At the first app-start after the update.

Version  OsmAnd+ 4.7.3
07.03.2024 6:59:52
Apk Version : 4.7.3 4703
Exception occurred in thread Thread[AsyncTask #3,5,main] : 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 4755872 free bytes and 4644KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at net.osmand.plus.views.AutoZoomBySpeedHelper.getFocusPixel(AutoZoomBySpeedHelper.java:264)
	at net.osmand.plus.views.AutoZoomBySpeedHelper.calculateRawZoomBySpeedForChart(AutoZoomBySpeedHelper.java:202)
	at net.osmand.plus.views.AutoZoomBySpeedHelper$1.onAnalysePoint(AutoZoomBySpeedHelper.java:308)
	at net.osmand.plus.plugins.PluginsHelper.lambda$getTrackPointsAnalyser$1(PluginsHelper.java:819)
	at net.osmand.plus.plugins.PluginsHelper$$ExternalSyntheticLambda0.onAnalysePoint(Unknown Source:2)
	at net.osmand.gpx.GPXTrackAnalysis.addWptAttribute(GPXTrackAnalysis.java:631)
	at net.osmand.gpx.GPXTrackAnalysis.prepareInformation(GPXTrackAnalysis.java:579)
	at net.osmand.gpx.GPXFile.getAnalysis(GPXFile.java:303)
	at net.osmand.plus.track.helpers.GpxReaderTask.doInBackground(GpxReaderTask.java:81)
	at net.osmand.plus.track.helpers.GpxReaderTask.doInBackground(GpxReaderTask.java:37)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more

**Comment by Rowin63** [comment]
What is it, that keeps the app busy for minutes and leading to crash?
Pls see the attached files. Logcat was created shortly before the crash.


[exception.log](https://github.com/osmandapp/OsmAnd/files/14533786/exception.log)
[logcat (1).log](https://github.com/osmandapp/OsmAnd/files/14533788/logcat.1.log)

**Comment by sonora** [comment]
It's an out-of-mempry situation in connection with the GPXTrackAnalysis, so in this way it is what I reference as the "remaining root cause" of https://github.com/osmandapp/OsmAnd/issues/17805.

Even after my recent code improvements to that other issue (and even though I've always used release-type builds for my benchmarking) there is a remaining slugginess, and it's noticeably worsened by what the app does at every startup.

One situation I find very reproducible is this: Fresh start of the app, within the first 10sec after the map has appeared go to MyPlaces/Tracks. Depending on the timing, this may be  (for my 3500 tracks) in the 3-6 sec range, or could at this time still take up to 10 sec. When/if you can, leave that screen, then enter it again. After latest the second time, the app will freeze (you may be on the tracks or on the map at the time) for like 30 sec. I think the appp is busy updating the GPX stats in its database, annd probably with a lot of other tasks), and on some devices Andtoid gives me a "App not responsive: Close/Wait" warning. I think that is when in your setup you encountrr the out-of-memoy.

Not sure what else the app does that this time. But I guess we could somehow make the GPX stats more intelligent, e.g. update based on checksun or time stamps only if something jas really changed. (I observe the above at _every_ app start, even with no changrs to my track files or favorites)..

**Comment by Rowin63** [comment]
Thanks for analyzing it.
So perhaps also #19235 may be related to this problem...?

**Comment by sonora** [comment]
Yes, I suspect so. Something the app does about listing and analyzing gpx files (which favorites and tracks both are) is not as optimized as it should be. I had only recently looked into our code creating the item list on the management screens, and that code was (and still is to a now lesser extent) slowed down by the smart folder functionality, even for users who don't use smart folders. And I think closely linking the management screens with track analysis data, reading and analyzing the content of **all** your GPX files may keep the app very busy ar times and derserves improvement.

**Comment by Rowin63** [comment]
It´s so confusing. At one launch the app crashes, at the other time it does not. 
My data content (tracks, favorites, ...)  is always the same.

**Comment by Rowin63** [comment]
Can you tell me, why the app one time runs into OOM and crashes and the other time it does not?

Before again, the app was busy for minutes after start, then crashed with OOM. Crash dialog appeared to send the log.

I closed and started the app again, now it didn't crash. This is the log from this non-crashing start:
[logcat (2).log](https://github.com/osmandapp/OsmAnd/files/14549256/logcat.2.log)

Why?!?

**Comment by sonora** [comment]
It"s a good point and observation. Looks to me like we have timing issues with the many things which may be ongoing during every app startup, particularly perhaps in-depth analyses blocking things if you have large collections of data (like offline maps or gpx files), which the two of us,seem to have ,but most average users don't to that extent.

Something does not scale well here, more than likely the app does somethingv which requires _reading_ much of that data (probably its _content_, not just a listing!) and in that respect OsmAnd seems to not work like a normal file manager would handle things.

Unfortunately I am lacking both the time and the knowledge for an in depth analysis here for now.
The strategy seems clear:  Such activities needsto be set to "background trickle" or to "on demand", but must not keep the app and device busy at every app startup, and the user waiting...

**Comment by Rowin63** [comment]
It´s definitely the tracks data, that causes the problem.
After a fresh install and then restoring the data, the problem exists unchanged.

I know, my track collection is huge (>1Gb). This causes recently the crashes on almost every App start here.
But not even reducing the tracks folders data to <300Mb does really help. Still it takes several seconds until the tracks content is displayed. "my places" is a bit quicker, "configure map / tracks" is noticeably slower and takes at least 20s. But with reduced content the app does not crash. 

Everytime you get out of "tracks" and back again, this searching process starts over again and keeps Osmand incredible busy again.

) Start the app
) go to "my places" >>> after several seconds, see how the tracks content is listed
) switch over to "configure map/tracks" >>> the same again, it takes several seconds until the content is displayed
) get out of this menues (close "x" tracks) and get back in > same again
) this works but slow with reduced data and crashes frequently with all of my data

As already mentioned earlier here, this OOM problem did exist last year (#17290) but was solved!
The content of my data did not change much until then, but the problem is right back.

Please solve that (again).
Like last year, again I´m planning a trip and at the moment I´m hopping from one crash to the other.
It´s so annoying seeing previously solved problems coming back again. 
Thanks.

**Comment by Rowin63** [comment]
Can someone of you PLEASE tell me whats going on here?!?!?

Yesterday I moved Osmands datafolder to user specified "Android/media/net.osmand.plus/files/" and in the beginning everything looked fine. But see whats happening now:

pic(1) At app start the section "data folder" is displayed and a notification "Osmand has no permission to use..." can´t read more.
pic(2) second pic is scrolled down a bit to see the selected folder
pic(3) tapping "back" leads to immediate crash

And at the next app start this does not happen...
It only seems to happen after a phones restart.

This happens on two devices, S20+5G and S20+ both Android 13, both up to date.

![20240312_153728](https://github.com/osmandapp/OsmAnd/assets/95540936/b9215256-c9eb-4d4b-bb9d-0b1959b2e99c)
![20240312_153747](https://github.com/osmandapp/OsmAnd/assets/95540936/8d214080-1135-45fb-a289-ba735d1ffae8)
![20240312_153820](https://github.com/osmandapp/OsmAnd/assets/95540936/10668e1b-4fed-4b7e-a98c-20add0fb7b90)

**Comment by Rowin63** [comment]
Seems to be "time dependend". 
If Osmand is launched immediately after the phone´s restart, this "Android/media/ ...data folder" error appears.
If I wait for some time (like a minute or so) nothing happens and osmand starts properly.

But my tracks remain set back to standard (color, line, symbols "on", ...) 
Much work again to get my preferred settings back. I´m getting a bit tired of it...

**Comment by vshcherb** [comment]
Once permission is gone, OsmAnd switches to default folder so you see these standard view (not configured by you). But I totally don't understand what depends that sometimes you get permission sometimes you're not. Looks like "removeable storage" with removeable permission.

**Comment by Rowin63** [comment]
Hi!

No removeable storage, it´s the devices internal memory.
As mentioned above, it is time dependent - launching osmand immediately after a phones restart, when screen is ready, this happens (like permission is not granted yet).

) does not happen when waiting some time after phone restart
) never befor happened when using Android/obb/... or Android/data/... only here at Android/media/...
) does not happen on my Tab S6 running Android 12 - happens only on my two S20+ running Android 13

Now that I know how to avoid it (just wait a short time after phone restart), it´s not a problem anymore (but perhaps it´s of interest for you?). I only have to set all my tracks back to my desired appearance again... That´s a pain xx xxx xxx that all my tracks have been set back to "standard", on both S20+ ...

The main problem that still remains is having the OOM back again.

**Comment by Rowin63** [comment]
A perhaps intersting note to this OOM:
Osmand crashes, creates a report, but does not close - app remains running.
I can continue, my favorites and selected tracks are still on display.
But again, everytime I switch to "my places/tracks" or "configure map/tracks" it takes noticeably long (>20s) until the content is displayed.
And as soon as I move the map around, Osmand slows down and crashes again - without closing the app.
This can be continued, hopping from one OOM to he next.

**Comment by Rowin63** [comment]
I had to reduce my track´s data to 1/3 (kicking away 65% of my collection) to get Osmand running without OOM-related crashing.
My data content has never raised that much since this previous OOM-fix here #17290.

So there has to be a change in the app that causes this OOM crashing again.
And still "configure map / tracks" is terribly slow in displaying the content and is the same slowl re-indexed again everytime you´re out and in this menu again. 

I guess that´s not how it´s supposed to be.

**Comment by vshcherb** [comment]
I don't think we've managed to reproduce as our collections are not big enough . Hopefully some tactical improvements that we did also will help in future

**Comment by Rowin63** [comment]
when this improvements will be released? ~4.7.0#1872 still crashes

**Comment by sonora** [comment]
@vshcherb You dont need to possess a big GPX collection to reproduce. I can create all these,issues also using a 'fake' big collection, by
- using a smaller collection of say 500 tracks,
- creating e.g. 10 subfolders _tracks01_, _tracks 02_, _tracks03_,..._tracks10_ under OsmAnd"s root _'tracks'_ folder
- and placing a copy of your '500 collection' into each one.

That should create an environment which reproduces all these app behaviors.

Chances are that the number of copies you need,to create to reach the critical total collection size may vary with device or setup. I usually clearly see the adverse effects at total collection  sizes of 4000 tracks, at least on low to mid range devices.

**Comment by Rowin63** [comment]
Thanks for your further investigating.
Both Samsung S20+ and Tab S6 (at least) I wouldn´t rate as "low range devices".
