### ISSUE TITLE
Add tunnel=flooded render

### ISSUE THREAD

**Issue by Velomeloman** [osmandapp/OsmAnd#19237]
### Describe the idea (required)

tunnel=flooded has over 50k objects according to [taginfo](https://taginfo.openstreetmap.org/tags/tunnel%3Dflooded#overview)

### Tell us about the expected behaviour (required)

tunnel=flooded renders

### Tell us about alternatives you've considered (required)

Maybe same render as tunnel=yes on waterways

**Comment by xmd5a2** [comment]
Fixed. Maps are not ready yet.
Object to test: [186155752](https://www.openstreetmap.org/way/186155752)
Map: Bulgaria_europe
Need to enable option "Waterway tunnels" in "Configure map - Details"

![Image](https://github.com/osmandapp/OsmAnd/assets/5829014/1b205b6f-cb36-4fb8-a4f7-c5d5a5984bc6)

**Comment by xmd5a2** [comment]
Map is ready to test

**Comment by Velomeloman** [comment]
![Screenshot_20240315_122008_net.osmand.plus.jpg](https://github.com/osmandapp/OsmAnd/assets/109347561/e682c128-0d06-4756-b65b-5e95c82d1be1)

Disabling option "Waterway tunnels" make waterway completely invisible. I think it must be visible as ordinary waterway in that case.

**Comment by Velomeloman** [comment]
OK, I agree. Thanks for quick response.

**Comment by yuriiurshuliak** [comment]
When the "Waterway tunnels" option is enabled, this path can be seen outlined on the map.

OsmAnd~ 4.7.0#1848m, released: 2024-03-16

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/9503a1f8-5d52-4e5a-ba28-69bc7411cab7"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
It would be nice to add info ablout how tunnel=flooded should be rendered to https://osmand.net/docs/user/map-legend/osmand#waterways
Also rendered on iOS 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/2bc1ddf5-7233-4b67-8ad4-eabaf3575fb8"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by dmpr0** [comment]
# Review

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/10c0daa6-bd6d-44ec-b153-1c72fb864166"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/2cf2e6a4-541f-4063-a4c0-c4369f39c06d"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   


- [ ] Any difference if **Waterway tunnels** if Off or On 
* * Tested on https://www.openstreetmap.org/way/556204427

**Comment by xmd5a2** [comment]
Manually generated map with [way](https://www.openstreetmap.org/way/556204427)
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/bf7d6c8c-363b-478c-913d-303d867e466f)
I'll try to regenerate Ukraine_kiev-city_europe_2.obf after all maps are done

**Comment by Velomeloman** [comment]
![Screenshot_20240405_120017_net.osmand.plus.jpg](https://github.com/osmandapp/OsmAnd/assets/109347561/fafd3243-8491-4f2f-afb6-568409388f92)

![Screenshot_20240405_120003_net.osmand.plus.jpg](https://github.com/osmandapp/OsmAnd/assets/109347561/f728070b-f386-40c8-bd14-bdfcb493ff52)

Works fine with new maps

**Comment by dmpr0** [comment]
# Review 2
- [ ] Rename `Waterway tunnels` to `Waterway tunnels on low zoom levels`, currently even in if option is Off, tunnels will be visible from 17 zoom level.

**Comment by vshcherb** [comment]
I propose "Increase visibility waterway tunnels"

**Comment by xmd5a2** [comment]
https://github.com/osmandapp/OsmAnd/commit/e7c82d8d5e958307ab7927c4fbe5451bf3b17e8b
