### ISSUE TITLE
Add button to quickly hide all POIs

### ISSUE THREAD

**Issue by basings** [osmandapp/OsmAnd#19241]
### Describe the idea (required)

Add button to quickly hide all POIs

### Tell us about the expected behaviour (required)

Right now it's difficult to hide POIs.

### Tell us about alternatives you've considered (required)

Currently you have to add a button to the quick settings to show a POI type. Once that is toggled, you can untoggle it.

**Comment by basings** [comment]
@yuriiurshuliak thanks. I wasn't clear enough.

Example: 

You search for recycling and display it on the map. The POIs stay on the map indefinetly. My current workaround (for years, btw) is to show nearest POIs and then hide nearest POIs again.

**Comment by yuriiurshuliak** [comment]
We already have a similar solution in the nightly build, which you can find [here](https://osmand.net/docs/versions/nightly_versions#nightly-builds).

You can now add a quick action button to hide or show POIs. Additionally, if you use the search function, you can type the category you need, view it on the map, and then close it by clicking on the top right of the page, clicking on the cross.

OsmAnd~ 4.7.0#1752m, released: 2024-03-06

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/369bb7a4-7516-4d2a-bcf0-698147c7b402"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by scaidermern** [comment]
> You search for recycling and display it on the map. The POIs stay on the map indefinetly. My current workaround (for years, btw) is to show nearest POIs and then hide nearest POIs again.

You can simply turn them off again via Configure map / POI Overlay. This isn't obvious, I agree.

**Comment by basings** [comment]
@scaidermern that is too much work. To exit the view I have to press at least 3 times.

The quick action button is a good solution. Thanks!
