### ISSUE TITLE
'Visible on map' Tracks screen needs a way to get to My Places/Tracks screen

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#19257]
You can go from the 'MyPlaces/Tracks' management screen to the 'Visible on map' Tracks visibility management screen by tapping the corresponding list entry.

But you cannot get back, and and in general from the second there is no link to the first, that's sort of an issue for many users. I suggest the visibility screen needs e.g. an entry in its 3-dots menu called "Manage tracks".

**Comment by vshcherb** [comment]
To do: If Visible on Map screen is opened from My Places, instead of 'X' on top left it should have '<-' to get back to My Places / Tracks.

**Comment by sonora** [comment]
> To do: If Visible on Map screen is opened from My Places, instead of 'X' on top left it should have '<-' to get back to My Places / Tracks.

Yes, and in addition, can we not also have a '_Manage tracks'_ button or 3-dots menu entry for users who entered via 'Configure map>Tracks' to be able to advance to the 'MyPlaces>Tracks' screen. That path is direly missing today.
