### ISSUE TITLE
March 6/7th Nightly doesn't install

### ISSUE THREAD

**Issue by albansuser** [osmandapp/OsmAnd#19262]
### Description

The two most recent nightly compilations (android-full-arm64) prior to March 7th 00:25 GMT will not install as an update.

### Steps to reproduce

Update installed version with recent nightly compilation

### Actual result

The message shown in image is displayed

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/66352711/328d0994-64be-4822-a86b-b629901f6162"  width="300" height="auto"/> </th>
  </tr>
</table>

### Expected result

Update succeeds without problem.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: post OsmAnd~ 4.7.0#1750m, released: 2024-03-05
Android/iOS version: Android 14
Device model: Samsung S22+
Crash-Logs: ?
```

**Comment by goldfndr** [comment]
Same, with OsmAnd~ 4.7.0#1726m, released: 2024-03-01, Android 14 on Samsung Z Fold3.

**Comment by pebogufi** [comment]
Last before which could be installed was
OsmAnd~  4.7.0#1752m.apk 2024-03-06
Based on OsmAnd-android-full-arm.apk

All Downloads later are all about 7 MB smaller with the described error message.

Devices:
Samsung S5e Android 10
Samsung S10 Android 12

**Comment by scaidermern** [comment]
In the OsmAnd Telegram channels there was the following announcement:

```quote
⚠️⚠️⚠️ Important Update for [OsmAnd Nightly Build](https://download.osmand.net/latest-night-build/) Users (Android):

We have updated the certificate for the OsmAnd nightly builds. As a result, the current update mechanism is not functioning. To continue receiving the latest updates, users will need to manually remove the existing nightly version and install the new one. This action will restore the updating process.

Thank you for your understanding and cooperation.
```

**Comment by pebogufi** [comment]
Remove means 
backup, uninstall, install new one and hope that restore works reliable ?!?!?

**Comment by sonora** [comment]
See my comment here https://github.com/osmandapp/OsmAnd/issues/17805#issuecomment-1981633706. I think the way we compiled it was changed, but also the signature, and I think the latter causes the issue, and I am not convinced is actually necessary.

**Comment by sonora** [comment]
I have tried as I suggested above, and it works for me: Building like I propose above, and signing with our debug key as always produces the "fast", 7MB smaller apk which installs over our previous series of nightlies without issues.

(Actually I have been doing this for years myself, since I use builds with the "All files access" permission because for my purposes I need OsmAnd to use a dara folder readily file-system assessible by other means.)

**Comment by pebogufi** [comment]
But you did not check the download from
https://download.osmand.net/latest-night-build/
?
Again with version 07:58h #1773
Message file not installed.

**Comment by albansuser** [comment]
Before my original post I tried uninstalling OSMAnd completely and installing the "problem" new compilation. This seemed successful but the subsequent import of the previous working setup failed and the new OSMAnd crashed.

I don't mind doing the above but the failure of importing the previous setup is disappointing, particularly with a complex and comprehensive setup.

I reverted to a previous working version of OSMAnd and re-imported the saved setup. Working fine.

**Comment by albansuser** [comment]
> > Before my original post I tried uninstalling OSMAnd completely and installing the "problem" new compilation. This seemed successful but the subsequent import of the previous working setup failed and the new OSMAnd crashed.
> 
> Maybe your crash is caused by the height map / terrain map / 3D relief being enabled (see #19263).

Thanks.

The crash occurred during the importing of the previously working setup. Restarting caused an immediate crash.

However I  will check out your suggested link.

**Comment by albansuser** [comment]
> > > Before my original post I tried uninstalling OSMAnd completely and installing the "problem" new compilation. This seemed successful but the subsequent import of the previous working setup failed and the new OSMAnd crashed.
> > 
> > 
> > Maybe your crash is caused by the height map / terrain map / 3D relief being enabled (see #19263).
> 
> Thanks.
> 
> The crash occurred during the importing of the previously working setup. Restarting caused an immediate crash.
> 
> However I will check out your suggested link.

Yes, the existence of data in the geotiff folder caused the problem relating to the most recent nightly crashing.

As an aside, importing previously  saved/exported settings, profiles and resources worked acceptably well. However when importing the settings section the import progress screen never shows completion and eventually need to abort OSMAnd and restart.

**Comment by vshcherb** [comment]
Crash of 3D was reverted, related to Weather new functionality actually. The transition period was finished already and as I mentionned in another issue I don't think we can even  (not sure even if we will) sign with debug certificate release build. 

Debug builds could be still produced though I don't want to see complaints about performance issue, so I want to see more realistic results from nightly builds usage. 

Actually I see that on the server side compilation process for release is visibly longer and takes more memory, so I assume lots of performance optimizations done during compilation. That's also the reason why performance degrade happened for users who stayed with same android version

**Comment by franco999** [comment]
Nightly version from [March 11](https://download.osmand.net/night-builds/OsmAnd-master-opengl-nb-2024-03-11.apk), cannot be installed. [March 10](https://download.osmand.net/night-builds/OsmAnd-master-opengl-nb-2024-03-10.apk) version, installs correctly.

Android 13 (Motorola G32)

**Comment by vshcherb** [comment]
Can't explain ... need to check

**Comment by albansuser** [comment]
OsmAnd~ 4.7.0#1808m, released: 2024-03-11 installs normally.

**Comment by franco999** [comment]
As @albansuser says, I have tried downloading a more recent version again (OsmAnd~ 4.7.0#1809m, released: 2024-03-11) and it installs correctly.

**Comment by verdulo** [comment]
I noticed that the nightly version with new signature lacks permission REQUEST_INSTALL_PACKAGES, so it cannot update using in-app "Install versions" menu.

**Comment by verdulo** [comment]
The version 4.7.0#1817m installed from https://osmand.net/docs/versions/nightly_versions only downloads .apk file but does not try to install it. In the mentioned by you menu only OsmAnd~ (from F-Droid) shows up. I have to navigate to the catalog /Android/data/net.osmand.dev/files/ to install it. I'm using Android 14.

**Comment by albansuser** [comment]
> The version 4.7.0#1817m installed from https://osmand.net/docs/versions/nightly_versions only downloads .apk file but does not try to install it. In the mentioned by you menu only OsmAnd~ (from F-Droid) shows up. I have to navigate to the catalog /Android/data/net.osmand.dev/files/ to install it. I'm using Android 14.

OsmAnd~ 4.7.0#1817m, released: 2024-03-13 installs normally on my Android 14 mobile.

**Comment by sonora** [comment]
@vshcherb 
> (...) as I mentionned in another issue I don't think we can even (not sure even if we will) sign with debug certificate release build.

I have no indication that signing  an apk with a debug key has any impact on performance vs. signing it with the release key, as long as you compile it correctly as,'release'. But  I would like to verify this one time to be sure. Can you PM me instructions (probably just  OSMAND_APK_PASSWORD) how I can build an apk using our release key?

**Comment by sonora** [comment]
@vshcherb PS: Look at this: _OsmAnd-default.apk_ is signed with our release key, _OsmAnd-hardy.apk_ with our debug key. I am rather convinced the few bytes difference both apks exhibit in size indicates they are pretty much equivalent, a fundamental change in the way they are compiled would have to show up in a noticeable size difference?
![image](https://github.com/osmandapp/OsmAnd/assets/845735/cb2e440c-c26c-4e56-b63f-57bb9cd9c607)

**Comment by vshcherb** [comment]
I will align with release signature if you let me know.

I believe that now its same code but I don't want to switch back because
android auto, messy operation for updates and future issues debug vs
release

**Comment by sonora** [comment]
@vshcherb  Ok, understood, thanks!

I have in creator>osmand-hardy>Configuration created the Password Parameter OSMAND_APK_PASSWORD. So I guess if you put the password in its  default value, I can then in my build.gradle determine myself when to use the debug and when then release cert, right?

**Comment by vshcherb** [comment]
Yes I put the pwd, you can determine in gradle indeed
