### ISSUE TITLE
"Road style" menu caption is not translated

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1926]
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot_2015-11-17-18-08-17.png
But in "Configure map" this string is translated correctly
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot_2015-11-17-18-30-06.png
ru strings.xml:
```xml
    <string name="rendering_attr_roadStyle_name">Стиль отображения дорог</string>
```

**Comment by Zahnstocher** [comment]
@xmd5a2 
Russian translation for rendering_attr_roadStyle_description is missing.
