### ISSUE TITLE
Weather view is randomly and unpredictably rendering layers incorrectly

### ISSUE THREAD

**Issue by SteffenBauer** [osmandapp/OsmAnd#19264]
### Description

The weather view randomly renders parts of the screen incorrectly.  
I want to render the precipitation and cloud layer, and the cloud contour lines.  
Often, and unpredictably, parts of the screen are not rendered correctly, in a uniform deep purple color. (see example screenshots below)  
Sometimes I can fix this by tapping a different day and then going back to the day view that was incorrectly rendered.  
I can reproduce the bug on two different devices, both on my smart phone and my tablet.

### Steps to reproduce

* Open weather view by tapping side bar -> Weather
* Activate precipitation and cloud layers, and cloud contour lines.
* Render any day and time.
* Observed result: Parts of the weather layer are sometimes incorrectly rendered, in an unpredictable way.
* Also parts of the contour lines are not rendered (see especially the tablet screenshot below, where the '40' contour line is broken in the middle)
* Sometimes re-rendering the specific day/time by going back to another day and back again solves the problem, but not always.
* Waiting for a longer time in hope that the wrong areas will finally get rendered does not help. Rendering seems to be finished.

### Actual result

Example screenshots, please note the purple areas that are not rendered correctly, also the broken contour lines in the tablet screenshot:
Smartphone screenshots:
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/5973070/000a00ac-9774-4a9b-bf2c-2f35b7bf735d"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/5973070/2bad2591-3935-476b-ab07-0d5e9adfca4d"  width="300" height="auto"/> </td>
  </tr>
</table>

Tablet screenshot:
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/5973070/e9b4cd4d-6be5-4761-abcb-32e539ddc49e"  width="300" height="auto"/> </td>
  </tr>
</table>

### Expected result

Weather view is rendered on all first tries without broken areas, examples what should be the result (I got these screenshots only after several retries rendering the weather view)
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/5973070/34dcd98f-4a08-4cb9-8a85-973f79e5066b"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/5973070/27008405-c268-4c39-9b62-4972cf6560b9"  width="300" height="auto"/> </td>
  </tr>
</table>

### Your Environment (required)

OsmAnd Version both devices: 4.6.13 released 2024-01-19
Android version both devices:  Android 13
Device 1 model: Samsung Galaxy XCover 5
Device 2 model: Samsung Galaxy Tab S6 Lite

**Comment by DmitryAlexei** [comment]
Have you tried to download weather forecast for needed country or for the whole world? (menu > download maps > select a country or go to world maps > all world). In that case, animations become smoother.
In any case, weather animation will be reworked in the feature release (awaiting soon). You can also try beta from Google play in a few days.

**Comment by DmitryAlexei** [comment]
Of course, it's best to download the weather forecast for the whole world. The forecast for a single country may not contain data from the nearest weather tiles that is important for smooth weather animation. 

I also suggest that you wait for the new release and see if the situation with weather animation has improved.

**Comment by SteffenBauer** [comment]
I think then I wait for the next release. As the datafile for the whole world forecast is nearly 2 GB, it is rather unpractical to download it especially when on a vacation trip with limited mobile data volume; further the weather forecast should be updated regularly.

Anyway, I still wonder what is going on here, because my issue is not about the smoothness of the weather screen rendering, but rather that the weather screen sometimes renders correctly, and sometimes doesn't. In the cases where the display is broken, it looks like it stops right in the middle of rendering.

**Comment by SteffenBauer** [comment]
I will test again with the next release, until then closing this issue now.
