### ISSUE TITLE
Download .apk from github directly with Obtainium

### ISSUE THREAD

**Issue by HomemadeAdvanced** [osmandapp/OsmAnd#19268]
### Describe the idea (required)

I would like to pull the latest .apk directly from github using Obtainium. In order to do this, the latest released .apk would have to be listed under Releases. Would this be possible or is there another way to get the latest .apk directly from github?

Thanks in advance.

### Tell us about the expected behaviour (required)

-

### Tell us about alternatives you've considered (required)

-

**Comment by TheSnoozer** [comment]
Just saying: you could also download the latest from https://osmand.net/docs/versions/nightly_versions, or actual released versions from https://osmand.net/docs/versions/free-versions.

I'd agree though that the information should be made available in github.

**Comment by HomemadeAdvanced** [comment]
I use the version OSMand+ from the F-Droid Store. I don't want to use a nightly build, which probably has stability issues. It would be nice if I can pull the newest version with Obtainium directly from github in the future.

**Comment by mickelsonmichael** [comment]
The Obtainium dev helps maintain a list of apps you can import to Obtainium, and OsmAnd is one option:

https://apps.obtainium.imranr.dev/

Not certain if the plus version is a separate download or not but you can potentially update the configuration to target whatever version of the app you wanted
