### ISSUE TITLE
Revert nightly build signature change

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#19270]
On March 6 we started building and publishing our nightly apks with release code so they deliver true benchmarks.

But we also changed the key signing them, and that's an unnecessary complication which makes them incompatible with everybody's previous setups, and is totally unecessary?

I suggest this simple change to build.gradle would rectify the situation: https://github.com/osmandapp/OsmAnd/issues/17805#issuecomment-1981633706.

A change to one of the 2 buildTypes here is enough, either case yields the same, high performance apk:

![Screenshot_20240308-082919_Firefox](https://github.com/osmandapp/OsmAnd/assets/845735/c8ec36b8-b8bd-4975-8c1c-faa74d207f48)

**Comment by vshcherb** [comment]
I don't think we're going to revert. As we already updated and notified. Current approach is much more reliable and and doesn't depend on gradle Google implementations. 

So there is no vision that ```debuggable false ``` is fast enough or will be fast enough. 

Also current release starts working with Android Auto and allows almost seamless updates between betas and other versions.

**Comment by vshcherb** [comment]
P.S. You can't use debug certificate for release build. That's what I remember
