### ISSUE TITLE
No right turn or keep-right announced at motorway fork

### ISSUE THREAD

**Issue by aceman444** [osmandapp/OsmAnd#19275]
### Description

When navigating in OsmAnd across  node https://www.openstreetmap.org/node/3411602871 there was no indication to turn right at this point into the right-going motorway branch.

### Steps to reproduce

Give this route specification into OsmAnd to calculate a route and start navigation:
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=48.19025%2C16.42206%3B48.19170%2C16.41438#map=17/48.19184/16.41899

The bug is also seen when navigation simulation is used.
The map is Austria-Lower Austria of 1st Mar 2024 .

### Actual result

No right turn or keep-right voice command announced at motorway fork at node https://www.openstreetmap.org/node/3411602871 .
Nowever, there is only a keep-left voice command announced at node https://www.openstreetmap.org/node/5961486651 , which is correct.

You can compare OsmAnd turn commands vs. OSRM engine on osm.org on the link above. On osm.org the instruction numbered '2.' is the 'go right' command missing in OsmAnd navigation.

### Expected result

I would expect a keep-right voice command announced at node https://www.openstreetmap.org/node/3411602871 . Otherwise you have no idea you should go left or watch the lanes. You would only notice the rendered route goes right if you constantly watch the screen, which is not safe when driving.

### Your Environment (required)

OsmAnd Version: 4.6.12
Android/iOS version: 10

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. Attempt to create a route from coordinates 48.19117, 16.42042 to 48.19224, 16.41891. It is apparent that the turning lanes fail to indicate a right turn, resulting in the absence of a corresponding voice prompt. Here is a link to this route in the [web version](https://test.osmand.net/map/?start=48.191170,16.420420&finish=48.192240,16.418910&profile=car#18/48.19174/16.41858).

OsmAnd~ 4.7.0#1802m, released: 2024-03-11

https://github.com/osmandapp/OsmAnd/assets/127092082/fad85e80-976d-4595-99f8-17367770cc24

**Comment by aceman444** [comment]
Thank you very much for testing and confirming.

**Comment by vshcherb** [comment]
Turn lanes are mute which are not correct - [MUTE] Keep right (C|C|+TSLR|+TR) and go 0.1 km.

**Comment by vshcherb** [comment]
FYI Not a regression since 2023-01-30

**Comment by vshcherb** [comment]
Probably same as https://github.com/osmandapp/OsmAnd/issues/18789

**Comment by pl71** [comment]
What about [change:lanes](https://wiki.openstreetmap.org/wiki/Key:change).
[Previous segment](https://www.openstreetmap.org/way/884615665) has it and I thing it is not quite correct.

**Comment by vshcherb** [comment]
To do: turn shouldn't be mute https://test.osmand.net/map/?start=48.191170,16.420420&finish=48.193170,16.417630&profile=car#17/48.19193/16.41696

Same as [Incorrect "Next turn" widget](https://github.com/osmandapp/OsmAnd/issues/19064), https://github.com/osmandapp/OsmAnd/issues/19379

**Comment by yuriiurshuliak** [comment]
The bug has been fixed. Currently, the turn lanes are displayed correctly and the turn is also announced.

OsmAnd~ 4.7.0#1969m, released: 2024-04-03

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/0cffbcf5-af18-41aa-b81f-d6c4f87abb68"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by aceman444** [comment]
Very nice, thank you. Works for me in 4.7.
