### ISSUE TITLE
Selection of Osmands data folder > "manually specified" does not work at all

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#19281]
### Description

For Osmands data folder I selected the option "manually spezified" and set a folder I manually created: Android/_Osmand_/
After "apply" the app ask me to move all data over there and so I did. Then immediately the app asked for a restart. So I did.

But finally not one single file was moved over to it´s new place. 
Only a folder "Android/Osmand/_net.osmand.plus_/" was created, but nothing else happened.

Using a manually specified folder outside "obb" or "data" would help having access to Osmands data folders. 

### Steps to reproduce

Try it as I described above.

### Actual result

Nothing.

### Expected result

Move the app to my user specified data folder, as selected in the datafolder-options

### Your Environment (required)

Galaxy S20+
Android 13
Osmand +4.7.4

**Comment by sonora** [comment]
Our published OsmAnd builds do not have "All files access", hence are subject to google's standard file system access policy which for newer versions of Android does not allow access to the path you mention.

**Comment by Rowin63** [comment]
So which path - outside of "Android/data" and "Android/obb" - I can use? (pls tell me, I assume you know and I don't want to try and find out by myself and perhaps crash my installation by trial & error ...)

**Comment by sonora** [comment]
It depends on several factors like internal vs. external storage and Android version, and has become so convoluted that I am not very sure anymore.

I believe we had several posts here who report that the only reasonably accessible and performant path remaining  is under /Android/media (perhaps you need an especiallynamed subfolder there, not sure).

I personally use OsmAnd like a,file manager for my scientofic gpx collection, and hence always build a special build which can write anywhere. (https://github.com/osmandapp/OsmAnd/issues/16059)

**Comment by Rowin63** [comment]
I will try the Androud/media/...
And I've read your linked issue, but in fact it's more than I can understand. I'm a user, not developer.
But thanks anyway.

**Comment by sonora** [comment]
Ok, sure. I am also much more of a 'knowlegeable user and scientist' than a dev.;) Fact is that Google has restricted apps' use of the entire file system to only their own system apps and something like file managing or virus scan apps. I think we could sell osmand as a file manager...

In any case, the limitation only applies to Play Store published apps.

**Comment by Rowin63** [comment]
I moved the data folder (for testing, on my first device...) to Android/media/net.osmand.plus/files and it seems to work. 
All data seems to be moved over correctly and Osmand runs fine ("fine" as usual) ;-)

Most important to me: 
I am able to sync again Osmands data (tracks, favorites, av-notes, ...) between my three devices (for this I use the app "FolderSync Pro" that does everything I need)

Thanks for helping!!!

 > In any case, the limitation only applies to Play Store published apps.

Does that mean, Osmands F-Droid downloads don´t have this restriction?

**Comment by Rowin63** [comment]
Could be closewd from my side, because finally changing to "Android/media/" did work.

But:
It would be fine and user-friendly, if the app would recognize "forbidden" folders and inform the user about.
Doing just nothing and continue like "to finish, the app has to be restarted" is a bit irritating and creates false expectations in an already confusing situation.

**Comment by Rowin63** [comment]
Before I just forgot to not launch Osmand immediately after the phone restart and I unfortunately did so.
It crashed again (user defined data storage "Android/media/net.osmand.plus/files/...") and this causes again to reset all my tracks to standard settings (color, line, symbols, ...)

This issue is reproduceable.
