### ISSUE TITLE
Zoom jumps when underlay/overlay switch

### ISSUE THREAD

**Issue by Velomeloman** [osmandapp/OsmAnd#19285]
### Description

Zoom jumps from fractional value to nearest integer when underlay or overlay is turned on or off.

### Steps to reproduce

Scale map to any fractional zoom value. Turn on/off underlay/overlay by Configure map menu, quick action or quick button.

### Actual result

Zoom jumps to integer value.

https://github.com/osmandapp/OsmAnd/assets/109347561/27552b2b-abfd-46c2-8321-f08904a7c24d

### Expected result

Map save current zoom value and position.

### Your Environment (required)

OsmAnd~ 4.7.0#1789m, released: 2024-03-08

**Comment by Velomeloman** [comment]
Addition: this issue is relevant for all items in "Show" and "Routes" sections in the Configure map menu. Also for Fixme tags, Notes tags, Icons at low zooms in Openstreetmap section.

**Comment by yuriiurshuliak** [comment]
The bug has been fixed. Now, toggling the underlay or overlay no longer triggers a change in zoom level.

OsmAnd~ 4.7.0#1897m, released: 2024-03-22

https://github.com/osmandapp/OsmAnd/assets/127092082/ef7c0f2c-382a-4e6a-9ee7-5095421c1a1a
