### ISSUE TITLE
Brouter

### ISSUE THREAD

**Issue by Robgru2** [osmandapp/OsmAnd#19283]
### Description

I use Brouter as an offline routerengine for cycling trips because it is much faster. I also use the brouter app.
In the brout| app you  define the profile ( fast bike , trekking etc .)
Problem is that Now the tracks follow the highway  which are not allowed for bicycles. It seems that it stays in car mode...

Drives me crazy your help is much appreciated.
Robert 

### Steps to reproduce

1. Start brouter app ( osmapp must be closed)
2. In the app select brouter apo
3. Select profile example trekking
4. Exit
5. Select server mode
6. Start osmand select profile bike with brouter
7. Create route

### Actual result

Route calculated follows highway

### Expected result

Route should avoid highway 

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by vodie** [comment]
I think you don't use the BRouter profile you expect, because your steps to select the BRouter profile is wrong. Please look at the documentation: https://github.com/abrensch/brouter/blob/master/docs/users/osmand.md

**Comment by Robgru2** [comment]
Thank you problem solved

**Comment by Robgru2** [comment]
Thanks
