### ISSUE TITLE
Map tiles loading too slow if not in navigation mode

### ISSUE THREAD

**Issue by Tchiller** [osmandapp/Osmand#1928]
Sorry for the title, I was not too sure on how to name that. 

When I am opening the map without any navigation just in order to see where I am driving through (as I think that maps real art, I like doing that quite often) the map centres it self by my GPS-location. When driving, the current map tile moves stepwise according to my driving speed which is fine. When I am now driving, say, to the west, I am getting a light grey border of some millimetres on the left side of the screen until it gets reloaded. Not too disturbing but when I am driving, say, to the north west, I am getting two borders of my screen flashing all the time which is kind of annoying and distracting. 

I guess that an easy solution would be to have a map tile of 110 % the screen dimensions loaded all the time which would compensate the moving in any direction sufficiently. More sophisticated and maybe less data consuming could be a preloaded margin as function of the current moving speed. But that would be some more work on programming, I fear. 

Just a "nice to have" I would like to share with you. 
Thanks for that great tool and my kind regards!

**Comment by sonora** [comment]
No action planned, I guess (?)
