### ISSUE TITLE
Show Bus Guideways on Map

### ISSUE THREAD

**Issue by dmklinger** [osmandapp/OsmAnd#19296]
### Describe the idea (required)

There is a type of public transit that involves buses moving along guided tracks. This is tagged with the "bus_guideway" highway type (see [here](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dbus_guideway) in the OSM wiki), and is distinct from normal roads that are reserved for buses (which is ["busway"](https://wiki.openstreetmap.org/wiki/Key:busway))

It appears that this is even [ignored](https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml#L1971) in the rendering type file, which I believe means that even modifying the rendering xml will not allow them to render.

### Tell us about the expected behaviour (required)

These systems are important pieces of public transit infrastructure that ought to be included like other types of roads and rails. Right now, it is not possible to see them.

### Tell us about alternatives you've considered (required)

Some notable examples of infrastructure tagged as guided busways include

* [the Morgantown PRT](https://www.openstreetmap.org/way/243119879)
* [the Adelaide O-Bahn](https://www.openstreetmap.org/way/23148886)
* [the Nagoya Yutorito Line](https://www.openstreetmap.org/relation/17292767)
* [the Cambridgeshire Guided Busway](https://www.openstreetmap.org/way/92924794)

The roads themselves do not render in any existing style, leaving a conspicuous gap:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/25443497/d893c9b7-3d07-4d9b-b15d-e05408214c12"  width="300" height="auto"/> </td>
  </tr>
</table>

One thing I have noticed is that it's possible to "force" it by showing the bus route itself, this doesn't really show a complete picture, omitting yards and failing to properly distinguish it from other routes. 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/25443497/7c8f3263-587c-4bf7-a195-0f8c81e21638"  width="300" height="auto"/> </td>
  </tr>
</table>

I believe the ideal solution is to render it as blue tracks or similar, as OSM online does. Then the color matches non-guided busways, while also distinguishing it as rail.

**Comment by xmd5a2** [comment]
Fixed. Place to test: https://www.openstreetmap.org/way/243119879
Map: Us_west-virginia_northamerica
Map is not ready yet

**Comment by xmd5a2** [comment]
Map is ready to test

**Comment by yuriiurshuliak** [comment]
At the moment, bus routes are displayed on the map as a white-blue dotted line.

OsmAnd~ 4.7.0#1889m, released: 2024-03-21

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/34e8d27c-f472-4866-bc10-9e3aedc00a75"  width="300" height="auto"/> </th>
  </tr>
</table>
