### ISSUE TITLE
Certain crashes don't create a crash log

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#19291]
### Description

Certain crashes (such as the one from #19263) don't lead to the creation of a `exception.log`.

I have a feeling that since switching to rendering enginge v2, (some) crashes related to rendering no longer produce this crash log.

### Steps to reproduce

Let OsmAnd crash.

### Actual result

In some cases no `exception.log` is written.

### Expected result

All cases produce a `exception.log`.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: all recent versions
Android/iOS version: probably all Android versions
Device model: probably all devices
Crash-Logs: 🤡
```

**Comment by vshcherb** [comment]
Yes, nothing could be done. Please tombstones https://osmand.net/docs/user/troubleshooting/crash-logs/
