### ISSUE TITLE
Poi long tap - street name and ref

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/Osmand#1929]
In the screenshot you can see, that only the ref of the street of poi  is shown.  To show street name and ref would be good.
![screenshot_2015-11-18-14-40-45](https://cloud.githubusercontent.com/assets/11144987/11242562/caf95938-8e02-11e5-9a3c-7079d703366a.png)

Simon

**Comment by jf-simon** [comment]
Thanks

**Comment by jf-simon** [comment]
Sorry, but there is a“null“ if there is no ref, and only street name if both, ref and street name, are tagged
![screenshot_2015-11-25-14-15-38](https://cloud.githubusercontent.com/assets/11144987/11398183/475c2538-937f-11e5-9cd4-29513a20274f.png)
![screenshot_2015-11-25-14-18-56](https://cloud.githubusercontent.com/assets/11144987/11398236/a396af6c-937f-11e5-9105-c847f4514fca.png)

**Comment by vshcherb** [comment]
Thanks nice finding!

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/commit/43c12feb478ac50ec69c8e3e2c570499c4fe506b

**Comment by jf-simon** [comment]
Tested and works good, thanks
