### ISSUE TITLE
Search issue in Clayton (reverse geocoding)

### ISSUE THREAD

**Issue by Raycock2** [osmandapp/OsmAnd#19290]
### Description

These two photos are of the same place. One with your software and one with openstreetmap. The openstreetmap is correct but your software is showing a different city. None of the business on NC-42 in Clayton are in Wilson's Mills.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/100967885/b3c8895e-c909-4854-8b9e-173ebc686e9f"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/100967885/387cb575-6a9b-4b34-a918-60a18f71f93d"  width="300" height="auto"/> </td>
  </tr>
</table>

### Steps to reproduce

Search anything in Clayton, NC along NC-42 and it will come back Wilson's Mills. This is not shown in Openstreetmap. It is showing correctly.

### Actual result

Different city.

### Expected result

When search for things in Clayton, NC, I expect to get back things in Clayton, NC not Wilson's Mills, NC

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. I reproduced this issue specifically on iOS, as it doesn't occur on Android where Wilson's Mills is not indicated, despite live updates. You can review the OSRM link here: https://www.openstreetmap.org/node/11519317897#map=19/35.64863/-78.39307 and the web version link here: https://test.osmand.net/map/#18/35.64873/-78.39337.

OsmAnd~ 4.7.0#1802m, released: 2024-03-11

<table style="width:100%">
  </tr>
  <tr>
    <th>Android</th>
    <th>iOS</th>
    <th>OSRM</th>
  </tr>
  <tr>
  <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/4858304d-733d-489e-b6ca-097723683a62"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/8e815732-febc-4680-9294-368691ea0276"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/47d8a2ee-8515-4e04-92fd-9f5f5368a86f"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
To do: iOS code should be synced with Android, so the issue is gone

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-core/pull/800

**Comment by Zirochkabila** [comment]
`35,6486834, -78,3931318`

iOS - still present




<table style="width:100%">
  <tr>
    <th>4.9.0.11</th>
    <th>OsmAnd~ 5.0.0#3875m, Released: 2024-12-04</th>
  </tr>
  <tr>
<th><img src="https://github.com/user-attachments/assets/b0ad1639-7408-4d89-ab39-c9eeab2ab858"  width="450" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/943577e1-13d3-41d0-bad5-d5bd57dcd495"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
Needed to check 5.0 iOS
