### ISSUE TITLE
POI search: "enter" inside search string causing confusion

### ISSUE THREAD

**Issue by RicoZ-OSM** [osmandapp/Osmand#1930]
It is possible to hit "enter/return"  and when it happens the results are almost allays not what you want. I frequently hit it thinking it will start the search.  Maybe it could be disabled or filtered?

**Comment by vshcherb** [comment]
We should start search by name on button enter I think

**Comment by sonora** [comment]
Yes, exactly.

**Comment by RicoZ-OSM** [comment]
Perhaps start search on first offer bellow the text field would be even better. That is, if the textfield contains "waterf" and the first completion offered is waterfall, search that on enter
