### ISSUE TITLE
Vector texts are displayed even when selecting a raster image map source in OpenGL

### ISSUE THREAD

**Issue by geoffreytools** [osmandapp/OsmAnd#19303]
### Description

When I select Microsoft Maps as a map source (or overlay) and the OpenGL rendering engine is used, vector texts such as street names are displayed on top.

### Steps to reproduce

- Use Microsoft Maps as source or overlay with full opacity;
- Switch to Version2 (OpenGL) rendering engine in the OsmAnd parameters
- restart the app

Interestingly, changing the rendering engine without restarting the app does not reproduce the problem.

### Actual result

I can see vector steet names displayed on top of the raster map.

### Expected result

Vector street names should not be displayed as they are redundant. It's also not expected that a change of rendering engine, which is an optimisation, affects the observable behaviour.

### Your Environment (required)

```
OsmAnd Version: 4.6.13
Android/iOS version: Android 14
Device model: OnePlus Nord CE # Lite 5G
```

**Comment by Nine-Tailed** [comment]
That's how it's intended, and there's even an option in the overlay map settings to turn off poi and text display.

**Comment by DmitryAlexei** [comment]
@geoffreytools have you set underlay map? Do you use vector or online OsmAnd maps?
Could you please provide your profile settings. Go to menu > settings > your profile > export profile.

**Comment by geoffreytools** [comment]
@DmitryAlexei [here it is](https://github.com/geoffreytools/osmand-profile/blob/main/Browse%20map.osf).

I have no underlay map. The map source or online map is Microsoft Maps, which is a raster map.

When I noticed vector text was appearing on top I tried using the same map as an overlay.

I installed the app recently on a new phone and did not migrate any settingfrom an older version. I just dropped my old favorites files in Android/data/net.osmand/files

**Comment by goldfndr** [comment]
#18923?

Do you have any *Tracks* enabled?

If you go to Download maps then deactivate the Standard maps, do the street names disappear?

**Comment by geoffreytools** [comment]
@goldfndr I have no tracks enabled. If I remove the standard maps and clear the application cache, then only the vector city names are displayed.

**Comment by ThibaultPelloquin** [comment]
Hi!

Same problem here. With all tiles maps I want to display.

The switch of "Version 1", go back to "Version 2 OpenGL" parameter solves the problem, just for the current "session"...

"Fun" fact : if I set the overlay "50%" of opacity I can see not only the names but all the vector map appears... :(

It appeared to me with the last version of OsmAnd.

**Comment by geoffreytools** [comment]
@ThibaultPelloquin If I am not mistaken trashing standard maps will make search non-functional so beware.

**Comment by ThibaultPelloquin** [comment]
@geoffreytools I cleaned only cache (in Android options). I didn't erase data.

**Comment by vshcherb** [comment]
I didn't understand whether we reproduced it or not? Clearly if Show map symbols is off they shouldn't be displayed

**Comment by Andrewschenko** [comment]
Can't reproduce. Switch "Show map symbols" works as expected all the time.
