### ISSUE TITLE
Osmand prefers highway=service when "avoid unpaved ways" is activated

### ISSUE THREAD

**Issue by Discostu36** [osmandapp/OsmAnd#19309]
### Describe the routing engine used (required)

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Describe your routing Profile (required)

bike, use elevation data, driving style: safety, avoid unpaved roads

### Describe your start and end points (required)

https://osmand.net/map/?start=54.348962,10.125940&finish=54.349545,10.126018&profile=bicycle&params=bicycle,driving_style_safety,driving_style_balance:false,avoid_unpaved,height_obstacles#19/54.34928/10.12613

### Describe the actual route (required)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/30999326/8b0d3ad1-913b-4e9a-b935-c152954965ac"  width="300" height="auto"/> </td>
  </tr>
</table>

### Describe the expected route (required)

The route should stay on the cycleway

### Describe what Maps you used (online or offline) (required)

- [x] Offline maps offered within the OsmAnd app for download. 2024-03-01 with Osmand Live.
- [x] Online (tile / raster) maps: Osmand map in browser

### Your Environment (required)

```
OsmAnd Version: 4.5.10
Android/iOS version: Android 13
Device model: Fairphone 4
```

### Anything else? (optional)

Variant of issue #17532. "Avoid unpaved ways" in combination with "prefer safety" leads to unexpected results. Can reproduce in app and online.

**Comment by Discostu36** [comment]
The routing algorithm still considers all "highway=path" and "highway=track" as "unpaved way", I don't know why hasn't been changed after I have mentioned it in the last ticket.

https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#L1674-L1677

**Comment by DmitryAlexei** [comment]
- When **Avoid unpaved roads** option enabled routing algorithm uses [this road](https://www.openstreetmap.org/way/65544353)
instead of [bicycle designated](https://www.openstreetmap.org/way/1104954129) road

<table style="width:100%">
  <tr>
    <th>Avoid unpaved Cost 29</th>
    <th>Avoid unpaved with intermediate Cost 40</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/53b6f758-aeb3-4151-af08-bd77b15cf668"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/16bb8800-11de-4b8e-b13e-df54e5efd27e"  width="300" height="auto"/> </td>
  </tr>
</table>

- If **Avoid unpaved roads** disabled, routing works ok. Same route costs 8.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/f69892d0-2de6-42bf-86a2-5094fca219c7"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
Obviously it assumes that service is paved - https://www.openstreetmap.org/way/65544353.859375#map=19/54.34924/10.12595
But it's not sure if paved or unpaved cycleway. 
https://www.openstreetmap.org/way/1104954129.296875#map=18/54.34908/10.12603

I think we can only do a random search to make a decision cause we have no tag information to prove or disprove it.

**Comment by scaidermern** [comment]
> I think we can only do a random search to make a decision cause we have no tag information to prove or disprove it.

The section in the routing.xml for `avoid_unpaved` linked by @Discostu36  doesn't even take the `surface` tag into account. Why is that?

**Comment by Discostu36** [comment]
@vshcherb I don't see why a service road should be assumed to be paved but not a designated cycling path.

**Comment by xmd5a2** [comment]
Issue is in [this part of code](https://github.com/osmandapp/OsmAnd-tools/blob/master/java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/osm/MapRenderingTypesEncoder.java#L1571-L1590)
https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#L1507

_osmand_highway_integrity_brouting_ for [this way](https://www.openstreetmap.org/way/1104954129#map=18/54.34908/10.12603) should be lower than 4 to fix this issue.

**Comment by ivanPyrohivskyi** [comment]
Fixed map generation.
@xmd5a2 test needed

**Comment by DmitryAlexei** [comment]
Issue fixed
When Avoid unpaved roads option enabled routing algorithm uses [bicycle designated](https://www.openstreetmap.org/way/1104954129) road.
- see web [link](https://osmand.net/map/?start=54.348962,10.125940&end=54.349566,10.126023&profile=bicycle&params=bicycle,driving_style_safety,driving_style_balance:false,avoid_unpaved,height_obstacles#19/54.34913/10.12653)
- Android OsmAnd~ 4.7.0#2035m, released: 2024-04-10 and
- iOS TestFlight 4.7.3.4.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/ab8c6d14-224e-4b94-95b5-99e8e5849697"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/d84447cd-050f-439c-9097-97dab3b48b79"  width="300" height="auto"/> </td>
  </tr>
</table>
