### ISSUE TITLE
Incorrect or Unnecessary Y axis with HR and Temp graphs

### ISSUE THREAD

**Issue by albansuser** [osmandapp/OsmAnd#19315]
### Description

There are incorrect or unnecessary right side Y axes with Heart Rate and Temperature graphs derived from external sensor data.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/66352711/dc939fdc-49c1-48cd-84f2-0eb0384e2e19"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/66352711/3dfaa1bd-fac1-4180-8ebf-923485de7cb2"  width="300" height="auto"/> </td>
  </tr>
</table>

### Steps to reproduce

For a recorded track (GPX) that includes heart rate and ambient temperature sensor data select Analyse on Map option then select either of the above parameters to be displayed as a graph.

Note the irrelevant right side Y axis.

Actually an incorrectly labelled or derived right side Y axis is also displayed for the slope and altitude graphs. Maybe others.

### Actual result

As shown above

### Expected result

Clean graph without right side Y axis or a correctly labelled right side Y axis.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd~ 4.7.0#1838m, released: 2024-03-14
Android/iOS version: 14
Device model:
Crash-Logs: ?
```

**Comment by DmitryAlexei** [comment]
Should be fixed in https://github.com/osmandapp/OsmAnd/issues/18204

**Comment by albansuser** [comment]
OsmAnd~ 4.7.0#1860m, released: 2024-03-18

No sign of the fixes yet. 

How long do they normally take to get through the system?

Thanks

**Comment by DmitryAlexei** [comment]
@albansuser https://github.com/osmandapp/OsmAnd/issues/18204 is not completed yet. So we should wait a little more.

**Comment by albansuser** [comment]
No problem.

Thanks
