### ISSUE TITLE
Wikimedia Photo is not visible for mapped wikidata 

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#19329]
OSM: https://www.openstreetmap.org/node/9578634049
Wikidata: https://www.wikidata.org/wiki/Q111243500
Photos to be visible: 
https://commons.wikimedia.org/wiki/File:Siilinkarin_talvikahvio.jpg
https://commons.wikimedia.org/wiki/File:Siilinkarin_talvikahvila.jpg
https://commons.wikimedia.org/wiki/File:Siilinkari_winter_cafe.jpg
Empty
```
select * from wikidata where wikidataid = 'Q111243500';
```

Strangely enough https://www.openstreetmap.org/node/9578634049#map=12/61.5205/23.8050 node should have been in previous wikidata database
-------------------------
Big thanks!! :tada: I suppose this is now in OsmAnd 4.6.14? It seems like that, but at least one node isn't showing the photos for me in OsmAnd..

The node: https://www.openstreetmap.org/node/9578634049

The wikidata page: https://www.wikidata.org/wiki/Q111243500

The three photos: https://commons-query.wikimedia.org/#%23cache-control%3Ano-cache%0A%23defaultView%3AImageGrid%0ASELECT%20%3Ffile%20%3Fimage%20WHERE%20%7B%0A%20%20%3Ffile%20wdt%3AP180%20wd%3AQ111243500.%0A%20%20%3Ffile%20schema%3Aurl%20%3Fimage.%0A%7D

There are three photos but OsmAnd doesn't show any of those to me. Any ideas why?

_Originally posted by @jluttine in https://github.com/osmandapp/OsmAnd/issues/13926#issuecomment-1999625957_

**Comment by vshcherb** [comment]
2 is certainly another feature. 
But with 1 still needs fixing, good that you mention test point. Also photos don't appear immediately and our cycle is 1 month to regenerate database.

**Comment by vshcherb** [comment]
@contrapunctus-1 better to add https://www.openstreetmap.org/node/11228824231 wikidata id (all other information will be retrieved) WIP

**Comment by vshcherb** [comment]
Ready for test

**Comment by vshcherb** [comment]
Test OSM objects:
- wikidata tag
- wikipedia tags
- wikimedia_commons

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/pull/19710

**Comment by vshcherb** [comment]
We need to test Android & iOS

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.8.0#2239m, released: 2024-05-03 iOS Testflight 4.7.5.2. 
- https://www.openstreetmap.org/way/787883229
 
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/71d75ca1-bf73-46bd-8e46-9600d9ecdb9c"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/44a999ef-74fd-4850-982e-3f78a3e5187d"  width="300" height="auto"/> </td>
  </tr>
</table>

 - https://www.openstreetmap.org/node/9578634049 on both devices all 3 photos are present
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/ff4a6034-14a3-41c8-a6ee-4b81616e6375"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/941dfee8-3aa2-4711-88ae-27e34922bf6c"  width="300" height="auto"/> </td>
  </tr>
</table>

- https://www.openstreetmap.org/node/3426332293 dos't work on iOS version
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/7d2d581a-a51b-4b44-ba9e-9b758fe5f1fb"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/0a5ab296-4f12-46e2-92b6-fac83abd5eb7"  width="300" height="auto"/> </td>
  </tr>
</table>

- https://www.openstreetmap.org/way/500272608 Android 10 images are present, iOS = 0

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/79bc5900-e9e0-4a70-b95c-3654e17b4a7b"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/0cba79d9-4be1-416b-a843-f9642405be95"  width="300" height="auto"/> </td>
  </tr>
</table>


- https://www.openstreetmap.org/way/27830097 works on both devices
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/d584fab7-b745-48cd-9af7-a73bfcb09ad7"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/6ca073fd-69ff-4158-a921-39886fc6ea21"  width="300" height="auto"/> </td>
  </tr>
</table>

- https://www.openstreetmap.org/way/27830130 same photos on Android and iOS devices

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/574a5fd2-34e1-4555-8eaf-737d9f5ac81d"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/dd043869-542a-4f35-9023-0fb5ff5068f8"  width="300" height="auto"/> </td>
  </tr>
</table>

- https://www.openstreetmap.org/node/11228824231 doesn't work - no photos - (as expected) on both Android and iOS devices
- https://www.openstreetmap.org/way/44147751 doesn't work - no photos - (as expected) on both Android and iOS devices

**Comment by dmpr0** [comment]
Done

<table style="width:100%">
  <tr>
    <th>Android</th>
    <th>iOS</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/da9553fd-aebc-40d0-a601-0a1d17d247f9"  width="300" height="auto"/> </td>
    <td><img src="ttps://github.com/osmandapp/OsmAnd/assets/9365308/344efc91-e18d-44f7-8dc8-d17a0e5f897c"  width="300" height="auto"/> </td>
  </tr>
</table>
