### ISSUE TITLE
wrong bicycle routing against oneway in france

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#19326]
### Description

Weeks ago was a discussion, that in France it is allowed to drive against oneway with bicycle, **if maxspeed is 30 km/h or less.**
Currently it looks like that routing uses direction against oneway **without regarding maxspeed**. I had a lot of such unallowed routings in the last days.
Example: 
[favorites-Wrong_Routing.gpx.zip.txt](https://github.com/osmandapp/OsmAnd/files/14623905/favorites-Wrong_Routing.gpx.zip.txt)
At position "Oneway direction SouthEast" the routing should not go there. Compare routing with bicycle and car (which refuses this part of street).

### Steps to reproduce

See above, use waypoints in gpx, drive from "start" to "destination"

### Actual result

Osmand bicycle routing drives agains oneway street at position "Oneway direction SouthEast"

### Expected result

Osmand bicycle routing should NOT go agains oneway street.

### Your Environment (required)

OsmAnd Version: OsmAnd~ 4.7.0#1847m, veröffentlicht: 2024-03-15
Android version: 12
Device model: Samsung S10

```

**Comment by vshcherb** [comment]
I couldn't reproduce using web route - https://test.osmand.net/map/?start=44.052330,5.054902&finish=44.055321,5.051739&profile=bicycle&params=bicycle,height_obstacles,noglobalfile#17/44.05388/5.05314. It doesn't match car routing as you mentioned wrong one (https://test.osmand.net/map/?start=44.052330,5.054902&finish=44.055321,5.051739&via=44.053876,5.051683&profile=bicycle&params=bicycle,height_obstacles,noglobalfile#17/44.05449/5.053690.

So I think if we won't reproduce in nightly build than issue is fixed

**Comment by pebogufi** [comment]
The first link _(bicycle)_ uses a route AGAINST oneway, which is not allowed. That is the bug.
The street "chemin de st.labre" is onway direction to south east.

**Comment by vshcherb** [comment]
I dont think it's correct, oneway:bicycle should be used then

**Comment by scaidermern** [comment]
> I dont think it's correct, oneway:bicycle should be used then

What about #17426? This has been implemented, hasn't it?

**Comment by vshcherb** [comment]
Let's ask @xmd5a2

**Comment by pebogufi** [comment]
> I dont think it's correct, oneway:bicycle should be used then

I understand oneway is general for all vehicles and oneway:bicycle is an exception from oneway just for bicycles.
So in the example street "chemin de saint labre" you find this tags:
highway=residential
name=Chemin de Saint-Labre
oneway=yes

**Comment by DmitryAlexei** [comment]
related issue https://github.com/osmandapp/OsmAnd/issues/18710

**Comment by DmitryAlexei** [comment]
In France OsmAnd uses streets tagged oneway=yes for bicycle routing in the opposite direction when max speed on these streets are higher than 30 km/h 
- [OsmAnd routing](https://test.osmand.net/map/?start=44.052330,5.054902&finish=44.055321,5.051739&profile=bicycle&params=bicycle,height_obstacles,noglobalfile#17/44.05388/5.05314)
- [OSRM routing](https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=44.05229%2C5.05494%3B44.05485%2C5.05187#map=18/44.05353/5.05464)
- routing through [this street](https://www.openstreetmap.org/way/892635444#map=19/44.05396/5.05277) shouldn't be allowed 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/8aa5082f-ebae-41f0-b015-72488a30ddd0"  width="500" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/f90ba6a0-74d7-4e97-a9ca-11829590a87e"  width="500" height="auto"/> </td>
  </tr>
</table>

According to french rules, When the speed limit is less than or equal to 30 km/ h, roadways are two-way for drivers of motorized personal transport vehicles, light bicycles and cyclists, unless otherwise decided by the police authority ([link](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000045025523))

**Comment by pebogufi** [comment]
> In France OsmAnd uses streets tagged oneway=yes for bicycle routing in the opposite direction when max speed on these streets are higher than 30 km/h

... and that is wrong

> 
>     * [OsmAnd routing](https://test.osmand.net/map/?start=44.052330,5.054902&finish=44.055321,5.051739&profile=bicycle&params=bicycle,height_obstacles,noglobalfile#17/44.05388/5.05314)
> 
>     * [OSRM routing](https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=44.05229%2C5.05494%3B44.05485%2C5.05187#map=18/44.05353/5.05464)
> 
>     * routing through [this street](https://www.openstreetmap.org/way/892635444#map=19/44.05396/5.05277) shouldn't be allowed
> 
> 
> <img alt="" width="500" height="auto" src="https://private-user-images.githubusercontent.com/116079541/313430722-8aa5082f-ebae-41f0-b015-72488a30ddd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NTU2ODcsIm5iZiI6MTcxMDY1NTM4NywicGF0aCI6Ii8xMTYwNzk1NDEvMzEzNDMwNzIyLThhYTUwODJmLWViYWUtNDFmMC1iMDE1LTcyNDg4YTMwZGRkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxN1QwNjAzMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YzExZmQ3ZDk3MWNhNTU3ZTcwZmJmYjEyODU5NTUwYmM2NDk0MGNlZjFjZDVlNGEyYjY2OTk2MTVjY2ZiOGVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P5af0O__2AxTlPmJ5RIibHl2cP3eGIQupIoHfbibd7M"> 	<img alt="" width="500" height="auto" src="https://private-user-images.githubusercontent.com/116079541/313431103-f90ba6a0-74d7-4e97-a9ca-11829590a87e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NTU2ODcsIm5iZiI6MTcxMDY1NTM4NywicGF0aCI6Ii8xMTYwNzk1NDEvMzEzNDMxMTAzLWY5MGJhNmEwLTc0ZDctNGU5Ny1hOWNhLTExODI5NTkwYTg3ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxN1QwNjAzMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTdjY2ZiZTlkNDc1MWE0YTI2NjZhMTExY2Q3OTdjYWZlZGQxZWQ5NzU5N2Q1ZWE2N2VkYWNhNzg4ZmYzMWYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.23Al2h6yFHFvl6h9BCR5mBdHRTFaQ3ivUSZMce5I7Hw">
> 
> According to french rules, When the speed limit is less than or equal to 30 km/ h, roadways are two-way for drivers of motorized personal transport vehicles, light bicycles and cyclists, unless otherwise decided by the police authority ([link](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000045025523))

Fully agree, that is what i tried to describe as bug.

**Comment by xmd5a2** [comment]
Fixed. Map to test: France_provence-alpes-cote-d-azur
[Route to test](https://test.osmand.net/map/?start=44.052330,5.054902&finish=44.055321,5.051739&profile=bicycle&params=bicycle,height_obstacles,noglobalfile#17/44.05388/5.05314)
It shouldn't use [this way](https://www.openstreetmap.org/way/892635444#map=19/44.05431/5.05212)
Map should be updated today or tomorrow

**Comment by pebogufi** [comment]
I downloaded and tested with
- OsmAnd~ 4.7.0#1880m, veröffentlicht: 2024-03-20
- France_provence-alpes-cote-d-azur_europe.obf

but the map has identical file datime as before
and also filesize 544.213.787b
Unfortunately the routing is wrong as before, checked with the described route and one more example.

**Comment by vshcherb** [comment]
Full map was uploaded #55 (21 Mar 2024, 13:12:17)

**Comment by pebogufi** [comment]
i am sorry, but the map i downloaded here has no difference to prior version:
https://download.osmand.net/list.php
Again the map has identical file datetime as before
and also identical filesize 544.213.787b
Unfortunately the routing is wrong as before, checked with the described route and one more example.
OsmAnd~ 4.7.0#1892m, veröffentlicht: 2024-03-22
Do you recomend a different place to download ?

**Comment by pebogufi** [comment]
@xmd5a2 
Again I downloaded map and app.
App is now OsmAnd~ 4.7.0#1907m, veröffentlicht: 2024-03-23
Result of testing same as above reported bug unchanged.

**Comment by pebogufi** [comment]
One more test.
It works now with map
France_provence-alpes-cote-d-azur_**vaucluse**_europe.obf
but only with driving_style_speed, 
not with other driving_style

**Comment by pebogufi** [comment]
Ok, after more zooming in, i can see it. 
I did not expect that. Thanks a lot.

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.7.0#1930m, released: 2024-03-27 Issue is fixed on Android and iOS
- Tested on route [OsmAnd routing web](https://test.osmand.net/map/?start=44.052330,5.054902&finish=44.055321,5.051739&profile=bicycle&params=bicycle,height_obstacles,noglobalfile#17/44.05388/5.05314) (On OsmAnd web this issue will be resolved at the beginning of the April, when new maps are generated)
- Downloaded Provence-Alpes-Cote-D'Azur or Vaucluse map

There is a slight difference in routing with different riding styles (see screenshots).

<table style="width:100%">
  </tr>
  <tr>
    <th>Prefer unpaved roads, prefer byways, Balanced </th>
    <th>iOS </th>
    <th>Shorter routes (same on iOS) </th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/1920775c-27e0-40f9-9557-492ce275a4a5"  width="300" height="auto"/> </th>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/abb78f6a-3d4f-4704-8b75-118f195f2c19"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/d7e5d7de-79a6-4445-b357-aa585639b2ec"  width="300" height="auto"/> </th>
  </tr>
</table>
