### ISSUE TITLE
Map orientation by compass direction is 180 often degrees wrong.

### ISSUE THREAD

**Issue by TimothyEBaldwin** [osmandapp/OsmAnd#19334]
### Description

Map orientation by compass direction is 180 often degrees wrong.

### Steps to reproduce

1. Enable automatic rotation in Android
2. Set map orientation to "compass direction"
3. Rotate phone to vertical portrait (power socket down)
4. Rotate phone to landscape orientation (volume buttons up)
5. Rotate phone to screen horizontal 
6. Rotate phone to landscape orientation (volume buttons down)
7. Rotate phone to screen horizontal 

### Actual result

The map view is 180 degrees rotated with respect to reality, so that north on the map is actually south.

### Expected result

The map view is aligned with reality.

### Your Environment (required)

```
OsmAnd Version: 4.6.13
Android/ version: 13
Device model: Fairphone 5
OS build Number: FP5.TT46.A.144.20240205
Crash-Logs: None
```

**Comment by yuriiurshuliak** [comment]
I could not reproduce this bug. In the provided video, after following the steps you outlined, the map orientation reverts to its initial position. Please confirm whether you observe the bug described in the attached video. Additionally,  if possible, please share your video demonstrating this error.

Furthermore, I recommend attempting to calibrate the compass in the phone settings to see if the issue persists.

OsmAnd~ 4.7.0#1879m, released: 2024-03-20

https://github.com/osmandapp/OsmAnd/assets/127092082/bee1ba83-07fc-486b-9cc2-6ec55782d78d
