### ISSUE TITLE
MyPlaces>Tracks root folder and subfolders lose sorting order

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#19333]
Have to re-open this. With intense use in the last 2 weeks, at least once daily the sorting order of MyPlaces>Tracks and its subfolders resets to "Last modified", while I positively always set everything to A-Z.

There must be one or several remnants in our code always setting things back to "Last modified".

Candidates are after a fresh app start, manual profile change, a navigation (without using turn-by-turn mode), or after making more track folders visible on map.

**Comment by scaidermern** [comment]
A never ending story ☹️

- #17955
- #17475
- #17278
- #17315

**Comment by scaidermern** [comment]
In #17955 I added a video how to reproduce this bug.

And just now I reproduced it by simply changing the visibility of two tracks to false. This also changed the sorting order of the tracks root folder.

**Comment by sonora** [comment]
I believe there are multiple different ways to independently reproduce issues about the sorting order of the new tracks screens. Someone knowledgeable about that code should go tyhroug the entire code base, search for places where the sort order is changed, and check for potential occurences of unwanted changes happening... or else we may not fix these issues for good for another long time...

**Comment by sonora** [comment]
Side note: about something which confuses some readers of the screenshots and recordings: 

When using the "Sort subfolders" action, its initial screen highlights one of the sorting options with a color. By convention you may think this is the current sorting order used for the subfolders, but in fact it seems not. (In fact it even shows if not all subfolders are sorted the same.) Not sure what it means to be - perhaps the highlighting needs removing here to avoid confusion.

**Comment by Rowin63** [comment]
I don´t know why, but all my tracks sub-folders are set back to sorting "last edited".

**Comment by Rowin63** [comment]
I think, changing Osmands data folder could have caused it.
And new created folders do have this sorting as "standard".

**Comment by sonora** [comment]
In my cases it had nothing to do with changing the data folder or creating new folders... happens during app use, with just occasionally displaying/hiding groups of tracks.

**Comment by vshcherb** [comment]
@sonora it's impossible that setting would randomly changed, @Chumva please share what setting is for sorting and where it's possibly changed in the code

**Comment by Rowin63** [comment]
After editing some folders names, the listing gets mixed up in "configure map>tracks"

![Screenshot_20240422_074324_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/95540936/8d981e80-e9d0-491a-898d-4313e820f59f)

But it is correct in "my places > tracks"

**Comment by vshcherb** [comment]
The problem of that issue it's still in reproducing phase (I hope we will get more time to put some logs after release rush)

**Comment by sonora** [comment]
But @yuriiurshuliak confirms "QA Reproducing" in https://github.com/osmandapp/OsmAnd/issues/19333#issuecomment-2007298285 above?

**Comment by sonora** [comment]
I suspect that this issue is related to https://github.com/osmandapp/OsmAnd/issues/19634#issuecomment-2075893541. Often when visiting the Visible tracks screen the sorting order gets reset to 'Last modified', potentially somehow 'inherited' from the 'Visible on map' screen.

**Comment by sonora** [comment]
And PS: This fix increases for my setup (3500 tracks in 70 subfolders) the time to enter that screen which was meanwhile down to 2-3sec to like 15+ sec again...

**Comment by Rowin63** [comment]
> And PS: This fix increases for my setup (3500 tracks in 70 subfolders) the time to enter that screen which was meanwhile down to 2-3sec to like 15+ sec again... (_every_ time I enter it, there seems no caching or remembering)

THIS is exactly the behavior I have on my Tablet (Galaxy Tab S6), since a few releases (maybe a month or so?). Takes around 20s every time I open "my places / tracks" or "configure map / tracks". 
I did a complete fresh install but it did not change (latest Osmand+ 4.7.11) 
The tablet runs Android 12. 
I dont see this issue on my other devices, all running Android 13 (Android 12 seems to be the only difference). Didn´t open an issue yet, was searching the cause on my side. Have the same data on all devices (reduced track data, not as many as before).

**Comment by sonora** [comment]
Looks like the problem is associated with the "Visible on map" tracks screen, we have 2 error cases:
- Any sort modification (also to e.g. 'Nearest') on any tab of the Visible Tracks screen resets the MyPlaces>Track (and subfolder sorting) screen reverting to 'Last Modified'.
- Adding or removing a visible track via the Visible on map screen (independet of how the Visible folder is sorted) resets the MyPlces>Tracks screen (and subfolder sorting) to 'Last Modified'.

**Comment by sonora** [comment]
BaseTrackFolderFragment.java's `TracksSortMode getTracksSortMode()` is the faulty method, I've verified that both  error cases come from this line

https://github.com/osmandapp/OsmAnd/blob/73a7b1b744d42bfc7972cd46c4badff9bf9abcd6/OsmAnd/src/net/osmand/plus/myplaces/tracks/dialogs/BaseTrackFolderFragment.java#L331

**Comment by sonora** [comment]
To elaborate: The issue comes from the different scopes of sort modes we save on the 'MyPlaces>Tracks' vs. the 'Visible on map' screens. Tentative TODOs:

1. On Configure map>Trscks  we do not display a tab for folders which contain no tracks directly  but only subfolders. Correspondingly, their sort order gets lost in https://github.com/osmandapp/OsmAnd/blob/21d390dc18ea61bbfaf60f97288f439e7d6015eb/OsmAnd/src/net/osmand/plus/configmap/tracks/TrackTabsHelper.java#L311 This needs mitigating. Most prominently for the root ("Tracks") folder.

2. Reversely, the sort order for tabs which have no folder equivalent gets lost when the sort modes are saved from MyPlaces>Tracks. Most notably "ALL" and "ON MAP".

3. The sort order for the **tabs** needs to be synced with that of the root **folder** and remembered (saved) "in both directions".

**Comment by sonora** [comment]
This PR fixes (1) and (2) above https://github.com/osmandapp/OsmAnd/pull/19814. It  preserves the existing sort modes when saved in the two separate tack screens we have.

As a consequence, we need to have the method `removeSurplusTabsSortModes()` to at some point clean up the `TRACKS_TABS_SORT_MODES` no longer needed on both screens. For now I only call it under `sortSubFolder(...)`, we may find better or additional places to call it, e.g. when folders are deleted.

Issue #19634 is not yet fixed by this PR. We now need code sorting the tabs on 'Configure map/Tracks' according to  the 'MyPlaces>Track's' screens rootFolder's sortMode, from what I see that is so far completely missing.
