### ISSUE TITLE
build failed 

### ISSUE THREAD

**Issue by jlmalet** [osmandapp/Osmand#1933]
:OsmAnd:mergeFreeLegacyArmv5DebugResources
AAPT err(2033414097): F:\GIT\osmand\Osmand\OsmAnd\res\drawable-mdpi\progress_green.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(2033414097): F:\GIT\osmand\Osmand\OsmAnd\res\drawable-hdpi\progress_green.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(1704997980): F:\GIT\osmand\Osmand\OsmAnd\res\drawable-hdpi\ic_btn_wocheckbox_selected.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(80490430): F:\GIT\osmand\Osmand\OsmAnd\res\drawable-hdpi\ic_overflow_menu_light.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(80490430): F:\GIT\osmand\Osmand\OsmAnd\res\drawable-hdpi\warnings_speed_camera.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(80490430): F:\GIT\osmand\Osmand\OsmAnd\res\drawable-hdpi\ic_btn_wocheckbox_notselected.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(80490430): F:\GIT\osmand\Osmand\OsmAnd\res\drawable-hdpi\progress_blue.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(2075454215): F:\GIT\osmand\Osmand\OsmAnd\res\drawable-large\warnings_speed_bump.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(2075454215): F:\GIT\osmand\Osmand\OsmAnd\res\drawable-mdpi\progress_orange.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(1636997736): F:\GIT\osmand\Osmand\OsmAnd\res\drawable-hdpi\monitoring_rec_small.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(1536293574): F:\GIT\osmand\Osmand\OsmAnd\res\drawable-hdpi\pedestrian_small_white.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(2145730690): F:\GIT\osmand\Osmand\OsmAnd\res\drawable-hdpi\monitoring_rec_big.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(1281331770): F:\GIT\osmand\Osmand\OsmAnd\res\drawable-large\warnings_traffic_calming.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(240995919): F:\GIT\osmand\Osmand\OsmAnd\res\drawable-mdpi\progress_grey.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(240995919): F:\GIT\osmand\Osmand\OsmAnd\res\drawable-mdpi\progress_blue.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(1311998865): F:\GIT\osmand\Osmand\OsmAnd\res\drawable-hdpi\ic_btn_wocheckbox_pushed.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(1311998865): F:\GIT\osmand\Osmand\OsmAnd\res\drawable-large\warnings_speed_camera.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(985041113): F:\GIT\osmand\Osmand\OsmAnd\res\drawable-hdpi\warnings_speed_bump.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(748934081): F:\GIT\osmand\Osmand\OsmAnd\res\drawable-hdpi\progress_grey.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(748934081): F:\GIT\osmand\Osmand\OsmAnd\res\drawable-hdpi\progress_orange.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(1075872774): F:\GIT\osmand\Osmand\OsmAnd\res\drawable-hdpi\pedestrian_small.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(1536293574): F:\GIT\osmand\Osmand\OsmAnd\res\drawable-hdpi\monitoring_rec_inactive.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
:OsmAnd:processFreeLegacyArmv5DebugManifest
:OsmAnd:processFreeLegacyArmv5DebugResources
warning: string 'poi_bedding' has no default translation.
warning: string 'poi_building_poi' has no default translation.
warning: string 'poi_car_wash_self_service' has no default translation.
warning: string 'poi_general_tourist_attraction_yes' has no default translation.
warning: string 'poi_historic_monastery' has no default translation.
warning: string 'poi_level_crossing' has no default translation.
warning: string 'poi_mill_pond' has no default translation.
warning: string 'poi_team_handball' has no default translation.
warning: string 'poi_tourism_attraction' has no default translation.
warning: string 'poi_wiki_link' has no default translation.
F:\GIT\osmand\Osmand\OsmAnd\res\layout\dash_osmo_fragment.xml
Error:(23, 28) No resource found that matches the given name (at 'text' with value '@string/osmo').
F:\GIT\osmand\Osmand\OsmAnd\res\layout\fragment_edit_poi_advanced.xml
Error:(40, 40) No resource found that matches the given name (at 'text' with value '@string/tag_poi_name').
Error:(78, 40) No resource found that matches the given name (at 'text' with value '@string/tag_poi_amenity').
Error:Execution failed for task ':OsmAnd:processFreeLegacyArmv5DebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'F:\GIT\ANDROID\android-sdk-r24.0.2\build-tools\23.0.1\aapt.exe'' finished with non-zero exit value 1
Information:BUILD FAILED
Information:Total time: 7 mins 56.706 secs
Information:4 errors
Information:0 warnings
Information:See complete output in console

any idea?
thanks
JLM

**Comment by GaidamakUA** [comment]
The problem is that, for some reason Android Studio removes file no_translate.xml from res/values. Gradle though builds project. As a workaround I'm doing this:
$ cp OsmAnd/no_translate.xml OsmAnd/res/values/skip_translate.xml
