### ISSUE TITLE
The arrows on mtb:scale:uphill disappeared

### ISSUE THREAD

**Issue by Velomeloman** [osmandapp/OsmAnd#19348]
### Description

In previous versions there was arrows on ways with mtb:scale:uphill + incline (ver. 4.6.13):
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/109347561/a8d4046d-f8e1-47d0-baa6-7fcebf6dd902"  width="300" height="auto"/> </td>
  </tr>
</table>
In actual Nightly build arrows doesn't shown.

### Steps to reproduce

Set Configure map - Mountain Bike Routes - MTB scale.
Example: https://www.openstreetmap.org/way/1211650652

### Actual result

The arrows doesn't shown:
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/109347561/3c48ab26-43bb-468e-9485-006fb976be72"  width="300" height="auto"/> </td>
  </tr>
</table>

### Expected result

The arrows are displayed as before.

### Your Environment (required)

OsmAnd~ 4.7.0#1855m, released: 2024-03-18

**Comment by xmd5a2** [comment]
Dev notes: images **mm_arrow_red_down_big** and **mm_arrow_red_up_big** are missing in **OsmAnd-resources/rendering_styles/style-icons/map-icons-svg** but exist in **OsmAnd-resources/rendering_styles/style-icons/map-icons-png**

**Comment by Velomeloman** [comment]
OsmAnd~ 4.7.0#1939m
Problem still exist

**Comment by cepprice** [comment]
@Velomeloman Fixed nightly should be available in day or two

**Comment by zipav** [comment]
OsmAnd Nightly 4.7.0#2022m, released: 2024-04-09

The route arrows are displayed as they should be.
No longer reproduced.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/a5b48dc0-194f-4785-8669-56f75ec66cbc"  width="300" height="auto"/> </td>
  </tr>
</table>
