### ISSUE TITLE
Oceania map height lines

### ISSUE THREAD

**Issue by RicoZ-OSM** [osmandapp/Osmand#1934]
Downloaded maps for Tahiti, regular maps went fine, wikipedia as well - but contour map list does not give me any reasonable choice. 

Should I be downloading "Oceania" which is 518.9 MB worth? What went wrong there? The contour lines of the Pacific islands should not be more than a few dozens of megabytes altogether.

Seychelles maps, which similarly cover huge areas of ocean has height line data in just 0.4 MB

**Comment by vshcherb** [comment]
I think we need to provide srtm maps for countries where we already have regular maps

**Comment by xmd5a2** [comment]
@vshcherb We already have such a maps. Regular map for Tahiti is Oceania. SRTM is named "Oceania" too.

**Comment by vshcherb** [comment]
I was wrong, then let's just make separate maps for Tahiti?

**Comment by xmd5a2** [comment]
Tahiti is among hundreds of small islands in Oceania (it is divided to Polynesia, Melanesia, Micronesia). I think we can make maps for all *nesias, but in fact New Zealand is part of Polynesia.

**Comment by xmd5a2** [comment]
@vshcherb But some time ago we merged polynesia, melanesia and micronesia hillshade into Oceania because they were too small. Oceania hillshade file size is 500mb file because of Papua-New Guinea.

**Comment by RicoZ-OSM** [comment]
It is nice to have the Pacific Islands together in one map which is just around 50MB.  Papua-New Guinea is obviously quite big and rarely of interest to people travelling to Pacific islands so I would vote to split it out. Also the regular Paua-New Guinea maps will probably also get too large when more of it will be mapped.

As of Pacific islands, it would be nice to have Rapa Nui (Easter Island) and Galapagos included (currently Chile and Ecuador) or available without downloading the mainland of those countries.

**Comment by xmd5a2** [comment]
I removed Papua-New Guinea from Oceania. It is still available as separate map. Oceania SRTM is only 86Mb in zip now.

**Comment by vshcherb** [comment]
Good work, I guess we can close the issue.
