### ISSUE TITLE
OSMAnd loses track of navigation in background

### ISSUE THREAD

**Issue by NastyFlytrap** [osmandapp/OsmAnd#19352]
### Description

Whenever i put the app in the background for a bit of time like 15 minutes it forgets where im going and what the navigation is supposed to be saying

### Steps to reproduce

Navigate somewhere
Open another app or put osmand in the background
Wait 15-20 minutes
Osmand doesnt know where you were going last time the app was open

### Actual result

A reset of the navigation data as if i just opened the app fresh from a cold boot

### Expected result

It remembering where it was supposed to navigate me to

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.6.12
Android/iOS version: 12 i think
Device model: Samsung A32 4G
Crash-Logs: ?
```

**Comment by scaidermern** [comment]
Please check if you disabled battery optimization for OsmAnd. If not, disable it. This is an Android setting.

**Comment by yuriiurshuliak** [comment]
Yes, you are right, please check if your device has any power optimization settings that may be affecting the app's performance. You can refer to this website https://dontkillmyapp.com/ for more information on power optimization.

And please provide feedback whether it worked.

**Comment by NastyFlytrap** [comment]
> Yes, you are right, please check if your device has any power optimization settings that may be affecting the app's performance. You can refer to this website https://dontkillmyapp.com/ for more information on power optimization.
> 
> And please provide feedback whether it worked.



> Please check if you disabled battery optimization for OsmAnd. If not, disable it. This is an Android setting.

OSMAnd was set to restricted battery access, i may have done that, i dont remember why, the samsung default is optimised. I'll report back if this does anything. I can still turn off adaptive battery or put OSMAnd on unrestricted. We'll see. My bet is on adaptive battery doing this

**Comment by DmitryAlexei** [comment]
You should set OsmAnd battery usage to **Unrestricted** if you would like to record your tracks in the background.
I also recommend adding OsmAnd to "Never sleeping apps".

**Comment by NastyFlytrap** [comment]
> You should set OsmAnd battery usage to **Unrestricted** if you would like to record your tracks in the background. I also recommend adding OsmAnd to "Never sleeping apps".

It seems to have done the trick, it wasnt reset today and i tried really hard to test it with as harsh of a conditions as i could. 

How do tracks work, exactly? I still havent gotten around to testing them, and what is the point of them?

**Comment by scaidermern** [comment]
> How do tracks work, exactly? I still havent gotten around to testing them, and what is the point of them?

Recorded tracks just show you where you have been. They contain statistics (length, speed, height) about your trip and you can use them in case you want to do the same trip again or a similar one.

Third-party tracks work similar except that usually someone else did either record or plan them.

**Comment by NastyFlytrap** [comment]
> > You should set OsmAnd battery usage to **Unrestricted** if you would like to record your tracks in the background. I also recommend adding OsmAnd to "Never sleeping apps".
> 
> It seems to have done the trick, it wasnt reset today and i tried really hard to test it with as harsh of a conditions as i could.
> 
> How do tracks work, exactly? I still havent gotten around to testing them, and what is the point of them?
Edit: No, it didnt. It still reset, it was just harder to reproduce. I set it to unrestricted and an hour or two later it completely broke on me and wouldnt do any public traffic calculations what so ever no matter what i tried. I set it back to optimised and it came back to life an hour later, while i was stranded without a way to figure out which vehicle goes where

> > How do tracks work, exactly? I still havent gotten around to testing them, and what is the point of them?
> 
> Recorded tracks just show you where you have been. They contain statistics (length, speed, height) about your trip and you can use them in case you want to do the same trip again or a similar one.
> 
> Third-party tracks work similar except that usually someone else did either record or plan them.
Is there a way to auto record my trips?

**Comment by NastyFlytrap** [comment]
> You should set OsmAnd battery usage to **Unrestricted** if you would like to record your tracks in the background. I also recommend adding OsmAnd to "Never sleeping apps".

Cant, osmand doesnt show up under never sleeping apps, therefore i cant turn it on for that

**Comment by scaidermern** [comment]
> Is there a way to auto record my trips?

Yes. You can enable it via Trip recording / Auto-record track during navigation. See https://osmand.net/docs/user/plugins/trip-recording/

**Comment by DmitryAlexei** [comment]
@NastyFlytrap 
Only OsmAnd from Google Play is shown under never sleeping apps.

Can we consider this issue as resolved?

**Comment by NastyFlytrap** [comment]
> @NastyFlytrap Only OsmAnd from Google Play is shown under never sleeping apps.
> 
> Can we consider this issue as resolved?

I should be able to do that from the f-droid version, but, yea, go ahead. Thats a different topic.
