### ISSUE TITLE
Subway stations on click don't display and suggest subway lanes

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#19354]
All subway stations
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/1042025/3b16280e-ad79-42c3-8e0e-66dc9938d119"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/1042025/01f5d55c-59df-4e63-9c7d-fbcc50cec08e"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Dima-1** [comment]
When you click on the metro Olimpiiska icon, a context menu of public transport now appears. Some missing public transport stops were also fixed.

**Comment by Dima-1** [comment]
Now, clicking on any subway station displays the corresponding subway line.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/31807095/e0e0331b-61f5-48be-acf0-a2d3bceefba0"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/31807095/86ed767c-3ac9-47d5-9963-3806f4ea9a29"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
- Pull request conflict
- Test plan to mass compare (on base of ObfCompare code) before/after Kyiv / Berlin maps

**Comment by Dima-1** [comment]
Now iOS version works as Android.  When clicking on any subway station, the corresponding subway line is displayed.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/31807095/dc5725cf-61ef-4139-9801-a5459d2010f4"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/31807095/237d3fa3-c7a0-4d4a-bb0e-b836ac911da9"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.8.0#2108m, released: 2024-04-18 and iOS OsmAnd TestFlight 4.7.3.9
- wrong icon for iOS subway station in POI context menu (it is displayed as bus station)
- in Android, the metro line (U5) is mixed with other transport routes
- Android shows more transport routes than iOS
- in iOS there is a statement, that all transport routes are situated within 150 m. What is the distance for Android? Does this distance for iOS remain the same (only 150 m) ?



<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/059f9d55-0f2e-4176-a347-3913123b48d8"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/7850ee73-4c4a-4ea9-82b0-9042307ae778"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Dima-1** [comment]
Fixed multiple lines (U2/U9) and suggested metro line at the subway exit.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/31807095/8b8ac0b5-78b2-47f9-bf4a-c1d943fe721a"  width="200" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/31807095/8000370d-429f-4aa6-a851-6c62ae34a846"  width="620" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
OsmAnd 4.7.4.3
- for some subway exits metro line is not suggested
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/774b850c-b6f6-442d-bb2a-42e09aa34c88"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/7f88c1b2-8d00-4e87-bcbc-8f8e536f6ed9"  width="300" height="auto"/> </td>
  </tr>
</table>

- for some subway exits only one metro line is suggested
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/b7f39fef-4318-459f-986b-1740b6225dd8"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/31c85974-fd8c-4381-9386-df5694cca219"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
Double check https://github.com/osmandapp/OsmAnd-iOS/issues/3402#issuecomment-2088628223

**Comment by Dima-1** [comment]
The metro lines for the subway exits in Minsk will be fixed with the new maps generation.
<table style="width:100%">
  <tr>
<td><img src="https://github.com/osmandapp/OsmAnd/assets/31807095/1a9a401e-2240-4e81-ac10-58ed777a567c"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Dima-1** [comment]
Now, all exits will suggest all accessible metro lines.
<table style="width:100%">
  <tr>
<td><img src="https://github.com/osmandapp/OsmAnd/assets/31807095/380ca302-4103-4592-b6b4-ceb4a6352a8d"  width="300" height="auto"/> </td>
  </tr>
</table>
