### ISSUE TITLE
Voice navigation doesn't work on marshmallow

### ISSUE THREAD

**Issue by wisemonkey** [osmandapp/Osmand#1935]
Phone: Nexus 6p
OS: pure nexus (custom ROM)
No gapps installed.

**Comment by vshcherb** [comment]
Did you enable it? Do you use TTS or recorded ? ( could you try other one that you tried)? Could you try Development -> Test Voice

**Comment by wisemonkey** [comment]
Sorry forgot to update the ticket,
 
Recorded voice works, TTS doesn't.
Thanks for the tip about testing voice but I couldn't find development options. Please point me to it I'll try TTS again.



On November 23, 2015 12:42:49 AM PST, vshcherb <notifications@github.com> wrote:
>Did you enable it? Do you use TTS or recorded ? ( could you try other
>one that you tried)? Could you try Development -> Test Voice
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/osmandapp/Osmand/issues/1935#issuecomment-158877634

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sonora** [comment]
Got to "Plugins" (either via the Dashboard or via the Menu) and enable the OsmAnd development plugin. It comes with settings where you will find "test voice prompts".

**Comment by wisemonkey** [comment]
Tested them.
TTS voice doesn't work.
Recorded voice works.



On November 23, 2015 4:36:22 AM PST, Hardy <notifications@github.com> wrote:
>Got to "Plugins" (either via the Dashboard or via the Menu) and enable
>the OsmAnd development plugin. It comes with settings where you will
>find "test voice prompts".
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/osmandapp/Osmand/issues/1935#issuecomment-158922750

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sonora** [comment]
Another test:  Go to your Android's (not OsmAnd's) settings, find something like "Language and input" / "Text-to-Speech settings" / "Listen to an example". Wording and location of this menu varies from device to device but the functionality should be there: This checks if TTS on your device is activated and setup correctly, independent of OsmAnd. If it does not work there either, you need to check your Andrpid's TTS setup, if it works there, we need to check again in OsmAnd.

**Comment by wisemonkey** [comment]
Yes I think that is a problem.
I don't have any TTS engine installed, going to try installing espeak and report back

On November 23, 2015 1:42:05 PM PST, Hardy <notifications@github.com> wrote:
>Another test:  Go to your Android's (not OsmAnd's) settings, find
>something like "Language and input" / "Text-to-Speech settings" /
>"Listen to an example". Wording and location of this menu varies from
>device to device but the functionality should be there: This checks if
>TTS on your device is activated and setup correctly, independent of
>OsmAnd. If it does not work there either, you need to check your
>Andrpid's TTS setup, if it works there, we need to check again in
>OsmAnd.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/osmandapp/Osmand/issues/1935#issuecomment-159074537

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by wisemonkey** [comment]
Espeak itself has some issue so I guess I'll use recorded voice for now and will update this ticket once I get proper TTS engine

On November 23, 2015 1:42:05 PM PST, Hardy <notifications@github.com> wrote:
>Another test:  Go to your Android's (not OsmAnd's) settings, find
>something like "Language and input" / "Text-to-Speech settings" /
>"Listen to an example". Wording and location of this menu varies from
>device to device but the functionality should be there: This checks if
>TTS on your device is activated and setup correctly, independent of
>OsmAnd. If it does not work there either, you need to check your
>Andrpid's TTS setup, if it works there, we need to check again in
>OsmAnd.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/osmandapp/Osmand/issues/1935#issuecomment-159074537

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sonora** [comment]
Get a 3rd party TTS engine some are really good.
