### ISSUE TITLE
Route planning online broken

### ISSUE THREAD

**Issue by snooppr** [osmandapp/OsmAnd#19361]
### Description

Route planning online (ZLZK) broken

The problem affects only the provider of online ZLZK routes. Remove it from Osmand, or fix it.

### Steps to reproduce

https://github.com/osmandapp/OsmAnd/assets/61022210/1af163be-92dd-40e2-aaef-c5a4e0a50473

When planning the route, change the route strip from offline, on the online ZLZK supplier.

### Actual result

The route is not created

### Expected result

The route is created

### Your Environment (required)

Osmand version f-droid 4.6.14

**Comment by vshcherb** [comment]
Online Service doesn't provide service in Russia and occupied territories.
