### ISSUE TITLE
High battery usage with app on foreground (screen on) on phones with high refresh rate (90-120Hz)

### ISSUE THREAD

**Issue by UnlacedFountain** [osmandapp/OsmAnd#19365]
### Description

I've searched the issues and despite seeing a lot of battery drain reports, didn't found one related to phones with high refresh rates.

On smartphones with refresh rates of 90 or 120hz, OSMAnd with settings by default, will drain its battery way too quickly due to constant high GPU usage to generate all those frames.

### Steps to reproduce

Turn on high refresh rate for all apps on the smartphone if it's not and make sure OSMAnd is set to use the highest possible in system settings, start navigation with a freshly installed OSMAnd.

### Actual result

Watch the battery drain almost as quickly as you were playing a videogame.

### Expected result

Despite this being probably the desired behaviour as it offers a smooth experience, it drains the battery way too quickly making OSMAnd not very viable as a navigation app.

You can try the same with Google Maps and it won't drain the battery as quickly because the map viewport is locked at 60fps when browsing and locked at 30fps when in navigation mode regardless of the phone's target refresh rate while the rest of the app UI (menus) runs at the phone's maximum framerate. You can try yourself panning in navigation mode with Google Maps and see how choppy it is.

In order to improve the battery usage of OSMAnd, I'd suggest doing the same that Google Maps does by at least locking the framerate of the map viewport to 30fps while in navigation mode and set is as the default setting.

Meanwhile, it can be workedaround by setting OSMAnd to run at the lowest framerate possible in phone settings (usually minimum is 60hz) and turn off "Animate own position" setting in OSMAnd.

On my device, OSMAnd navigation mode with "Animate own position" on at 120hz:  constant ~65% GPU usage, at 60Hz: constant ~35%; With "Animate own position" off at 120hz: ~65% GPU usage every 1 second, at 60hz: ~35% GPU usage every 1 second. For comparison, Google Maps navigation mode uses around 12% of the GPU.

### Your Environment (required)

OsmAnd Version: 4.6.12
Android version: 13
Device model: RMX3370
Crash-Logs: not applicable

**Comment by Sonwon1** [comment]
I suggest this should be a user selectable option.

**Comment by DmitryAlexei** [comment]
I've tested battery usage with fps widget enabled (how to enable see https://osmand.net/docs/user/widgets/info-widgets#fps-widget) using Samsung galaxy note 20 ultra with adaptive screen refresh rate enabled (up to 120 Hz, see screenshot). I've made tests on the latest OsmAnd nightly build (not release version). 

- I've noticed, that more than 60 fps can be obtained mostly when browsing the map and only for a short period of time.
- When simulating navigation, fps stay around 10-50 which corresponds to fps in normal mode (I also performed navigation simulations with standard (60Hz) refresh rate)
- On the third screenshot, OsmAnd consumes about 0.4% battery pro minute while simulating navigation (my device has an old battery). The battery charge decreased by 9-10% after 20 min of navigation simulation.

<table style="width:100%">
  </tr>
  <tr>
    <th> Screen refresh rate settings </th>
    <th> FPS while browsing the map </th>
    <th> Battery usage from dev.plugin </th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/098b9526-7f8a-4bc8-b866-9bb18ce673e6"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/450a7ae5-fc27-4a04-8303-cd0c995b2477"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/799dbdf2-1ee3-49d2-a311-74e522afc10c"  width="300" height="auto"/> </th>
  </tr>
</table>

Screenshots below shows fps with adaptive refresh rate while simulating navigation

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/01396126-ab0c-43db-aa31-bb91f52ec63e"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/f7954f03-02f0-439d-a2bb-e6c3773a49e5"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/3f98198b-321f-4117-83fe-d0e3cd51d8db"  width="300" height="auto"/> </td>
  </tr>
</table>




P.S. we've added battery consumption information to the development plugin
It is now available in nightly builds (https://osmand.net/docs/versions/nightly_versions#nightly-builds) when development plugin enabled

**Comment by vshcherb** [comment]
Please test new beta to catch rendering stats
