### ISSUE TITLE
Development plugin missing translation

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/OsmAnd#19378]
In the settings of the development plugin are missing some translations.
Weblate is complete for german bit these lines are not translated.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/9936160/0af728b4-a4a8-4bc7-bf92-4eb0a02515f0"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by mariush444** [comment]
https://osmand.net/docs/technical/contributions/translating-osmand/

**Comment by yuriiurshuliak** [comment]
The bug has been fixed. Currently, in the development plugin settings, all options are translated correctly.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/397de129-11e9-4f1c-9683-22ce225475f2"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/93154672-9e6b-44fc-8979-f6708e6a8665"  width="300" height="auto"/> </th>
  </tr>
</table>
