### ISSUE TITLE
Crash when pressing button to set delay for automatic route calculation

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#1937]
OsmAnd+ 2.2 always crashes when clicking in the navigation settings the last button to define a time to automatically start routing.

**Comment by Norbert80** [comment]
![screenshot_2015-11-21-10-41-19](https://cloud.githubusercontent.com/assets/6921696/11317833/22b78c76-903d-11e5-99f4-05a8817ab3be.png)
![screenshot_2015-11-21-10-41-56](https://cloud.githubusercontent.com/assets/6921696/11317834/2657b086-903d-11e5-9d40-b27d491ebda9.png)

**Comment by vshcherb** [comment]
Yes it was fixed. Meanwhile the settings was disabled because in new UI it will be completely different.

**Comment by Norbert80** [comment]
Thanks for the information. I can confirm it as fixed/integrated in OsmAnd+ 2.2.1.
