### ISSUE TITLE
OSMAnd wont route at all in the public transport profile, no matter what.

### ISSUE THREAD

**Issue by NastyFlytrap** [osmandapp/OsmAnd#19389]
### Description

I try to go from one place to another, and no matter which city or country i do it in, it refuses to get me there.

### Steps to reproduce

Try to route
Have it fail. There is no trick to it, its inconsistent and uncommon, but when it does happen it lasts for hours and then magically fixes itself.

### Actual result

'Unfortunately, OSMAnd could not find a route suitable for your settings'

### Expected result

It giving me options on what to take to go where. I understand this is bad for reproducing it, but there is no trick or magic at work. Sometimes it does sometimes it doesnt. 

I open the app, i click on the navigation button, i click on the public transport button, i select the start and end locations and it slaps me in the face with the stop sign, and it keeps slapping me for hours until it decides to work again. Until then im almost stranded because of its temperamentalness

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.6.12
Android/iOS version: 12 i think
Device model: Samsung A32 4G
Crash-Logs: ?
```

**Comment by NastyFlytrap** [comment]
> Unfortunately, I was unable to reproduce this bug. Please try to increase the number of changes (Menu → Navigation →Settings →Navigation settings → Route parameters → Number of changes. And also make sure that you are not using online maps.

Yea i figured. I changed a bunch of settings like setting osmand back optimized battery settings, and restarting it a bunch but assuming it was the last change i made that fixed it, i turned off automatic track saving or whatever its called, and pressed the apply to all profiles button, restarted, and it worked then. 

Also, the number of changes is set to 0 for some reason, and i never changed this myself, and saw several route options in the past with up to 3 changes, and even two were very common. Why did the option change itself, or why is the option useless if it was always set to zero and i was still shown multiple change routes?

**Comment by derei** [comment]
@NastyFlytrap I also seem to be unable to make Public Transport work. Sometimes (rarely), it seems to work, but most of time it won't find any routes.

Would you mind detailing the steps to make it work, eventually screenshots?

Btw, running GrapheneOS on Pixel 7Pro.

**Comment by NastyFlytrap** [comment]
> @NastyFlytrap I also seem to be unable to make Public Transport work. Sometimes (rarely), it seems to work, but most of time it won't find any routes.
> 
> Would you mind detailing the steps to make it work, eventually screenshots?
> 
> Btw, running GrapheneOS on Pixel 7Pro.

I dont think i can help you. I just randomly changed settings like a caveman and eventually it decided to work. It wasnt even instantenious when i changed one setting. I just changed a bunch of them, got sick of it, put down the app, and when i came back 15-30 minutes later it worked again.

I set it from unrestricted to optimized in the settings, i changed the amount of transfers in the navigation settings, i restarted the app countless times between changing these settings, switched from one profile to the other (btw, it works perfectly with all others, even the trains which are somehow routed on asphalt roads but i digress....) except the public transport profile. I pressed the button that appears when you change a setting, to apply it to all the profiles, i turned automatic track recording on and off, its a rare bug but when it happens it gets stuck like that for 1-2 hours without me being able to budge it.

**Comment by derei** [comment]
Thank you for the detailed description.
It's a complete mess. If OsmAnd would peovide proper public transport routing, I wouldn't even look back.

I don't know if this also happens to you, but when I use the public transport routing, the phone gets warm fast, cpu is maxed all the time, and obviously, battery gets drained fast. All this without providing any routes 😆.

**Comment by yuriiurshuliak** [comment]
Attempt to reproduce the issue by resetting the profile settings via Menu → Settings → App profile → Reset to default. Additionally, review the provided guide to ensure all steps have been correctly followed: https://osmand.net/docs/user/map/public-transport.

**Comment by NastyFlytrap** [comment]
> Thank you for the detailed description. It's a complete mess. If OsmAnd would peovide proper public transport routing, I wouldn't even look back.
> 
> I don't know if this also happens to you, but when I use the public transport routing, the phone gets warm fast, cpu is maxed all the time, and obviously, battery gets drained fast. All this without providing any routes 😆.

i am heavily considering going back to google maps, not because i want to, i really dont fuckin want to, but i've been stranded by osmand twice already, without any way for me to know what bus or tram i need to take, and each time it took an hour of me sitting in front of a rando building, fucking with this thing, and then resorting to the web version of google maps, which sucks ass. Intentionally too, i presume.

And yes, it does get hot when its calculating the routes. Thankfully it only lasts like 40 seconds, but i can feel the camera area of the phone getting warm. It is a right mess.

> Attempt to reproduce the issue by resetting the profile settings via Menu → Settings → App profile → Reset to default. Additionally, review the provided guide to ensure all steps have been correctly followed: https://osmand.net/docs/user/map/public-transport.

Alright, but its going to be a few days before it'll even have a chance of showing up again, if it ever does.

**Comment by vshcherb** [comment]
We didn't reproduce the issue

**Comment by derei** [comment]
So many users from all over report issues with using public transport in OSMAnd, but "you can't reproduce the issue"?
Did it cross your mind that perhaps you're trying in some ideal setup, that (intentionally or not) happens to be optimized for this, but which is not the case in a lot of regular use cases? In simpler words: have you tried in real world, or only in the lab??

Honestly, this lack of drive to fix and strengthen such essential feature is shocking.
1. Most people nowadays live in cities, not in the wild.
2. More people use public transport compared to private cars.
3. A lot of cars come with preinstalled gps functionality, and such clients are less likely to happen to want OSMAnd.

Who is your market, then? The app is made for Android, hence it implies the necessity of such device. Is a travel app, which implies mobility. The vast majority of mobile android devices are phones, not tablets. And most people carrying phones use public transport (this is implied from the statement that most people in general use public transport). That would be a much better market, especially with this times when privacy awareness is increasing.

Instead, your de-facto market is those few who use android devices in their cars and want to use OSMAnd fanatically.

I wanted to ditch Google Maps for good, as is one of the few google services I'm using. I switched on GrapheneOS, Tutanota, pCloud (not the best, but not the worst), duckduckgo, LibreOffice/Collabora, and list can continue. But as you can grasp already from the body of this message, Google Maps doesn't yet have any worthy alternative. I wonder why.

**Comment by vshcherb** [comment]
Please specify coordinates and examples to test public transport to reproduce the issue otherwise nothing is going to happen

**Comment by NastyFlytrap** [comment]
I give up, noone can ever reproduce the issues im bringing up, gee, i wonder why there are almost three thousand open issues...

**Comment by derei** [comment]
I did some more testing. I think I figured out how to reproduce it. I'll make a video recording (i just need to download a gps spoofing app, for haters to not know where I live 😆😆)

**Comment by NastyFlytrap** [comment]
> We didn't reproduce the issue

I just did the same, brand new settings after the reset, as i was asked like a week ago, and its doing it again. Wont fucking route me anywhere, from any place, even if i just put a location on the map and set that as my starting point, it does not care. It did this in multiple different cities and i am sick and tired of this thing having constant issues and everyone telling me that it could not be reproduced. I get it, it doesnt happen for you, but its still broken, and we're never going to achieve our mission if shit doesnt work. I put up with it because im conscious of my privacy even if it comes at the expense of my convenience, but we'll never win if you cant do convenience to entice the normies.... Ugh

Fuck this shit. I cant even reset the cache of this stupid thing, like how we reboot computers to magically fix the issues with them. Cant even do that here.

**Comment by derei** [comment]
@NastyFlytrap Take a breather my friend. I promised a proof of the issue, and I will deliver. I just had to deal with some exhaustion and fever. Now only the exhaustion is left 😜. I may do it this evening.

**Comment by NastyFlytrap** [comment]
> @NastyFlytrap Take a breather my friend. I promised a proof of the issue, and I will deliver. I just had to deal with some exhaustion and fever. Now only the exhaustion is left 😜. I may do it this evening.

I know, i know. Im sorry.
Besides, i wasnt angry at you, or even the devs for letting me down, just the situation that it doesnt work, and that it always breaks when i need it for real purposes, and not fun looking around and travelling purposes...

Obligatory get well soon, it can wait. Its not like its going to be fixed any time soon anyway, even with the proof. The app receives updates like once every two months.

**Comment by alxmamaev** [comment]
Any updates? Public transport routing stops work for me some update ago, it not able to find the direct bus and changing the number of changes does not help at all. I'm trying to do it from IOS app

**Comment by alxmamaev** [comment]
Actually it does not need anything to reproduce, I've just removed the app and installed its again, and nothing work 

![image](https://github.com/osmandapp/OsmAnd/assets/17113191/1ae62bc4-8fe1-4300-be87-be53ac7f69cd)

**Comment by NastyFlytrap** [comment]
> Actually it does not need anything to reproduce, I've just removed the app and installed its again, and nothing work
> 
> ![image](https://private-user-images.githubusercontent.com/17113191/331689167-1ae62bc4-8fe1-4300-be87-be53ac7f69cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMDQ3ODgsIm5iZiI6MTcxNjAwNDQ4OCwicGF0aCI6Ii8xNzExMzE5MS8zMzE2ODkxNjctMWFlNjJiYzQtOGZlMS00MzAwLWJlODctYmU1M2FjN2Y2OWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDAzNTQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5NDQ0YmQxNzVmZjk4Y2NlODY2OWNiOTkzYWM5Yjc2MmIzNjk4ZDZjNGMxNjgwNmZjZTNiMDk3NmY3NmNlZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ijP2CU0KO_zb3Wl_U19OD61khUDOB4pA4VSQai-63BM)

The support for this app is awful. I get that you're volunteers but you can just say that you're doing this for free and that you're doing your best and i'd respect that. But all this excuses and responsibilty dodging is just annoying. 

The public transport routing is *ass* and no amount of blaming me is going to change that.

**Comment by vshcherb** [comment]
Ios is fixed, public beta release is available, it's being prepared for release

**Comment by Martin-L-H** [comment]
I know I'm 2 years late to the last comment but it just happened to me. After it never doing it for years, updating it, I had encountered it. It calculates routes for a while, then the app crashes and closes. This does NOT happen with places near me. Looking for a public transport routing 600 meters away from me gave me the result almost immediately. Looking for one 4km away hung up, so it seems like it's a calculation or algorithm issue.

**Comment by 3zet** [comment]
Fairphone 5, Android 15, osmand version 5.3.10 and I have exactly same error, even if I install the app fresh (or clean both storage and cache).
