### ISSUE TITLE
Implausible time estimates for gpx track

### ISSUE THREAD

**Issue by foss-** [osmandapp/OsmAnd#19383]
This bug sounds like the same problem which was closed back in 2020:
https://github.com/osmandapp/OsmAnd/issues/3807

### Describe the routing engine used (required)

- [ ] OsmAnd's in-app offline routing

### Describe your routing Profile (required)

Reproduce:

Not providing a sample gpx file because the requirement for this issue to show is, that your current location is close but not identical to where your gpx track starts.

1. create a gpx file with a starting point close to your current location but not your exact location, in my case it was ~1km away from current location, I used https://bikerouter.de to create the gpx file
2. Osmand > My Places > Import > select gpx file (it will import as track)
3. open track and select navigation

When checking the estimated times for the 73 km, walking says: 34 min and cycling says: 11 min
That is very off timing-wise.

I wanted to provide a sample gpx file and created that in another city. Noticed a few things:
- and all times were plausible
- while gpx start point was not my current location osmand was not connecting my current location with the gpx track

So while I could provide a sample file with which I am seeing the issue, it would not help you reproduce the issue, as you are not at the same location I am at and you would be seeing plausible times just like I did, when creating the sample gpx files in a different town.

### Describe your start and end points (required)

See above: create a start point near but not identical location and and end point a few km away.

### Describe the actual route (required)

The route itself is fine, just the time calculations are off.

### Describe the expected route (required)

See above.

### Describe what Maps you used (online or offline) (required)

- [x] Offline maps offered within the OsmAnd app for download.

But again, map does not seem relevant here. It is something about how the routing times are calculated when start point is near current location.

### Your Environment (required)

```
OsmAnd Version: Android 4.6.14 and iOS 4.6.6.1
Android/iOS version: Android 13.1, iOS 17.4.1
Device model: Xiaomi Lisa, iPhone xr
```

### Anything else? (optional)

Screenshot of the wrong calculated times:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/5708172/b345c742-1a37-4115-a606-fc79d84731cd"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/5708172/60fa3301-07b3-4d2f-9b58-26df6cda05f0"  width="300" height="auto"/> </th>
  </tr>
</table>

Funnily while the times on Android are much too short (11 mins for a bike ride of 73 km 😃) on iOS the times are much too long and walking the 73 km supposedly is just 23 minutes slower than taking the bike 😳
Bike: 20:03 h 
Walk: 20:26 h

**Comment by sonora** [comment]
Regarding your "iOS" observation above: Probably iOS suffers from the same bug, only that what you report there as 20:03 and 20:26 is the arrival _clock time_, not the _travel time_ estimation? (Toggle between the two by tapping, in many places.)

**Comment by foss-** [comment]
> Regarding your "iOS" observation above: Probably iOS suffers from the same bug, only that what you report there as 20:03 and 20:26 is the arrival _clock time_, not the _travel time_ estimation? (Toggle between the two by tapping, in many places.)

No, I did not confuse those numbers. iOS reproducible shows over 20 hours of traveling time for the 73 km. Don't have the time, but can attach a screenshot later if needed.

**Comment by vshcherb** [comment]
We found many code that wasn't migrated in iOS and today is going to merged related to GPX approximation, so I think it will be merged today. 
Though your times looks very wrong, so in case you can create another GPX and share with us, so we can reproduce, then we can fix.

**Comment by foss-** [comment]
Thanks for your response. While the new code may improve the situation on iOS, it does not explain the false time calculations on Android. Happy to test any iOS changes in the testflight beta.

As for providing a gpx track to reproduce, that is explained above:
> Not providing a sample gpx file because the requirement for this issue to show is, that your current location is close but not identical to where your gpx track starts.

When testing with gpx files not close to current location I received sensible time calculations.

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. I attempted to create a route on the recommended service, ensuring it was in close proximity to my location. Notably, the route calculated on this service, https://bikerouter.de, appears unrealistic, indicating a distance of 3.1 km to cover in 8 minutes by both bicycle and car. Please be aware that we do not take responsibility for routes generated on third-party platforms. 
Consider utilizing the "Attach to roads" feature. Once your route is chosen as the destination, you can locate the "Attach to roads" option either in the Navigation or Follow track menu.

OsmAnd~ 4.7.0#1938m, released: 2024-03-28
OsmAnd 4.7.2.11

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/8af8c78d-95a1-472d-9f04-07926b5680ec"  width="800" height="auto"/> </th>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/9427cf15-781c-45b2-b880-d78e37fa93c5"  width="300" height="auto"/> </th>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/dfa722a6-90dc-4417-be21-e2a01cb3dfec"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by foss-** [comment]
Sorry for the late reply. Retested with the problematic gpx file from bikerouter and was still able to reproduce the problem. The estimated time for a  73 km trip was 10 minutes.

After following your suggestion and using the `Attach to roads` option, the time estimate was ~4:30h which seems correct.

**Comment by sedrubal** [comment]
I guess the time shown, when the track is not attached to the road, is the time required to navigate *back to the track*, which is very confusing. So in my opinion, this *is* actually a bug which should be fixed.

**Comment by DmitryAlexei** [comment]
@sedrubal @foss- osmand allows using different types of tracks for different types of navigation. For example, users can use tracks recorded in pedestrian profile for car routing. Or users can use airplane tracks for ski routing. In these cases, the estimated time of arrival (ETA) is not good or bad, it is simply incorrect. The same is also true for tracks created in third-party applications and not attached to roads. All these tracks may not have timestamps and other important information to calculate ETA correctly without attaching them to roads. 
In addition, please see OsmAnd documentation https://osmand.net/docs/user/navigation/setup/gpx-navigation/#guidance
