### ISSUE TITLE
Update subway entrance logo - Subte Buenos Aires

### ISSUE THREAD

**Issue by ignaciolep** [osmandapp/Osmand#1938]
Please, update the newly added subway entrance logo with the new one currently in use:

https://upload.wikimedia.org/wikipedia/commons/2/24/Subte_gcba_logo.png

Subte Buenos Aires - Argentina

https://es.m.wikipedia.org/wiki/Subte_de_Buenos_Aires

**Comment by xmd5a2** [comment]
Done
