### ISSUE TITLE
Some issues regarding DownloadedRegionsLayer

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#1939]
Carry-over from discussion here https://github.com/osmandapp/Osmand/commit/0f2d547a109ee2b89f6b4eabb08fcc90f71aa7b3:

(1) Color pattern consistent with icon color pattern: Implemented here: https://github.com/osmandapp/Osmand/commit/4a87cc3f39720634579ffd6a165f733e1e8bee10

(2) A region must not be shown as "selected" immediately after any map tap in the region, as long as a multi-selection menu appears on the screen, but only after the user really selected a region in that menu. (User could also be trying to select a POI, marking the region on the map is then counter-productive.)

(3) There is still a bug with drawing the regions, reproduce as follows: Have a region selected which is also part of downloaded or uptodate regions: Now zoom in or out: After zooming, color_selected (yellow) somehow becomes overwritten on the screen by color_uptodate (green) or color_updateable (orange), respectively, creating a weird mix color. Color_selected should always prevail unmixed ("on top").

**Comment by vshcherb** [comment]
xmd5a

**Comment by xmd5a2** [comment]
I like colors (except "downloading" color) except opacity. It's too opaque and may be not easy to notice in field under direct sun. So I slightly decreased opacity of these colors.
Downloading color is completely not visible in night map mode.

**Comment by sonora** [comment]
Yes, I made a mistake with the opacity in my original commit, please see my
comment on your commit (
https://github.com/osmandapp/Osmand/commit/d0c93aa171ccf73df0d88afe95b1d044f4fd82ca).


Regarding the transparency of the marking colors: I would say that we
should make them as transparent as we can, because they naturally obstruct
map browsing, and map browsing is the more important feature over marking
regions and downloading?

**Comment by xmd5a2** [comment]
Current variant is: https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot_2015-11-23-19-47-59.png

**Comment by sonora** [comment]
I think it is ok!

Originally I thought that maybe we can make the "selected color" even more
transparent, but I think it is ok.

Also, I am having trouble producing the "_downloading" color on my screen,
looks like while downloading a region it remains simply shown as
"selected", but apparently it works on your screenshot. (Have to check
again what I do wrong.)

**Comment by sonora** [comment]
PS: color_downloading works all right, only that color_selected takes priority so you have to manually de-select a region after the downloading started to actually see the downloading color. Could be considered a small bug, but no big issue, I think.
