### ISSUE TITLE
Map moves up when context menu is open

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#19399]
### How to reproduce
* Set **Map orientation** to **Compass** or **Movement direction**
* Tap on POI or city name on the map

### Actual result

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>North is up</th>
        <th>Compass</th>
        <th>Movement direction</th>
      </tr>
      <tr>
        <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/5072eaf9-19c6-4930-9fc2-2aa258b42294
"  width="300" height="auto"/> </td>
        <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/438a372a-98fe-483d-bfb9-65032d23f1e4
"  width="300" height="auto"/> </td>
        <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/2cd2023b-baa3-4d32-aa05-02dc9b719b5e
"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

* Map moves up when context menu is open when Map orientation is Compass or Movement direction

### Expected result

* Map doesn't move up if tapping point is above context menu (as it works when Map orientation is North is up)

**Environment**
OsmAnd Version: 
Android: 13
Device model: Pixel 6a

**Comment by Rowin63** [comment]
Perhaps a similar behaviour: (may I add it here? If no, I´ll add a new issue))

Having some tracks on display and zoomed in to see map/track details > tap one track > context menue opens > 
tap "not/visible" on/off > nothing happens (beside switching track on/off)

tap "colour" > map zooms out all the way to display the whole track (not practical - no need to see the whoile track when changing its color) > tap "back" > context menue closes, but map remains zoomed out, far away from the initial spot > have to search this point again

**Comment by vshcherb** [comment]
For track not practical - I don't know if track appearance will be fixed in this issue, but in track appearance we should not change the map view as it's not needed.
