### ISSUE TITLE
Speedometer Fix Sizes

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#19396]
Part 2 for [Current speed / speed limit widget (including Android Auto) #13413](https://github.com/osmandapp/OsmAnd/issues/13413)

## Review sizes

<details>
    <summary>Size chart</summary>

|**Current speed** | S | M | L |
|---|---|---|---|
| Width | 56 dp | 72 dp | 96 dp |
| Height | 56 dp | 72 dp | 96 dp |
|**Text size** | | | |
| Value max. | 24 sp |  36 sp | 60 sp  |
| Value min. | 16 sp |  16 sp | 16 sp  |
| Units text size | 11 sp | 11 sp | 11 sp |
|**Corner radius** | | |
| Android | 6 dp | 6 dp | 6 dp  |
| Android Auto | 16 dp |16 dp | 16 dp |

 
</details>  

- [x] Use red color for current speed value when it exceeds the limit

# Design speedometer widget
- Moved to https://github.com/osmandapp/OsmAnd-Issues/issues/2501

## Speed limit

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Expected</th>
        <th>Result</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/a0cbbfb6-7d82-4b4d-bece-394c7a077d08"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/2e5562f6-b120-4f50-92a6-556f025275d8"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [x] Wrong size for **S**

### Widget width

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Size L</th>
        <th>Size M</th>
        <th>Size S</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/16f1e5f9-460f-4b2a-bd37-bd899e2be1e9"  width="auto" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/6c7d7258-1286-4ffc-bc46-c93efa45bebc"  width="auto" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/acadbb16-fcca-471f-bc83-763a67f64008"  width="auto" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [x] Change Speedometer width:
- - [x] **L**, size = `96x96 dp` 
- - [x] **M**, size = `72x72 dp`  
- - [x] **S**, size = `56x56 dp` 

- - -  

### Text size

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Text size</th>
        <th>Max</th>
        <th>Fit to width</th>
      </tr>
      <tr>
        <th>L</th>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/0a9a365a-1cda-4560-b791-3ad5ec5234b7"  width="auto" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/a131efff-0289-4dec-b3e7-d4853b59dbdc"  width="auto" height="auto"/> </td>
      </tr>
      <tr>
        <th>M</th>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/41ccb6a6-944a-4ea0-9210-8335a0197c1f"  width="auto" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/d6c825ef-2754-4207-911a-c55341595d58"  width="auto" height="auto"/> </td>
      </tr>
      <tr>
        <th>S</th>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/5778604c-35eb-4c80-a9e0-ba8b00db6543"  width="auto" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/4815f1a1-36d7-4ab8-93ec-fad30c2c9065"  width="auto" height="auto"/> </td>
      </tr>
    </table>   
</details> 

- [x] Set max. and min. text size for widget value:
- - [x] **L**, max / min  = 60 sp / 16 sp
- - [x] **M**, max / min =  36 sp / 16 sp
- - [x] **S**, max / min = 24 sp / 16 sp

**Comment by DaanLT** [comment]
nightly build 2024-03-27 OsmAnd~ 4.7.0#1928m:
some updates:
now speedometer is displayed in all modes - thank you.
but problem remains with speedometer cut text:
![Screenshot_2024-03-27_111211](https://github.com/osmandapp/OsmAnd/assets/128729388/6f4b2b3f-4847-4af1-bbbb-f4f896d97fa4)
---
aslo current speed is displayed with dot, not rounded number - but only in browse profile. In navigation/car mode its displayed rouded in both speedometer and widgets area
![Screenshot_2024-03-27_111231](https://github.com/osmandapp/OsmAnd/assets/128729388/18ce9284-0568-4cba-8ce6-140930b3243b)

**Comment by gkalausis** [comment]
Hi, tested today speedometer and if speed is higher than 99 it cuts last number and show only first two digits e.g. actual speed 110, osmand shows 11.

**Comment by dmpr0** [comment]
# Review

- [ ] Shadow is cropped for Speedometer

**Comment by dmpr0** [comment]
# Review 2

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/a8add5fd-4360-4dba-a11b-3cbce84a1301"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [ ] Wrong value color if app theme = dark, map mode = light

**Comment by dmpr0** [comment]
# Review
We need to decrease paddings to give values for free space, that allows us to get bigger font size. 

### Large

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/b63c1b6a-7da1-418b-a379-3a224f5ddf5e"  width="auto" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [ ] Remove padding between value and units
- [ ] Padding top – 3dp
- [ ] Padding bottom - 12 dp
