### ISSUE TITLE
Insurmountable Checkpoints

### ISSUE THREAD

**Issue by mirsto** [osmandapp/Osmand#1940]
Apparently, osmand handles checkpoints like insurmountable barriers. Such a checkpoint exists at the inner-Mexican border between the states of Campeche and Tabasco on MEX 186. It is tagged as barrier=checkpoint. If you try to establish a route from a point North of the ckeckpoint to a point South of it, osmand will always route somewhere else, just like if the road is not connected at that point.

Checkpoints should not be avoided. If desired, a warning could be issued, but re-routing is not a viable option.

**Comment by twzkxkan** [comment]
As far as I can tell barrier=checkpoint is not a documented tag, nor is it widely [used](https://taginfo.openstreetmap.org/tags/barrier=checkpoint), and in my opinion too vague to be useful. Is there a better way the feature could be mapped or not at all?

At least add the proper access tags like motor_vehicle=yes if they aren't present.

**Comment by xmd5a2** [comment]
Why not to use barrier=border_control?

**Comment by mirsto** [comment]
Ok, so what is the default behavior of osmand for barrier= tags? The documented barriers pose different restrictions (from none over some to all). Does osmand implement each of them differently? And how does it handle unknown barrier= tags? Would barrier=somethingelse as well be treated as insurmountable? And would it allow overrides by access tags? (BTW: I would prefer access=yes over motor_vehicle=yes as I don't see a reason for a restriction to motor_vehicles).

@xmd5a2 : From the wiki page of border_control: "This is a control point at an international border between two countries." - The checkpoint here is not a border control, it's just an inner-Mexican checkpoint.

**Comment by mirsto** [comment]
OK, I guess this should answer my question: http://wiki.openstreetmap.org/wiki/Barriers#Routing
> Each barrier has its own accessibility defaults. Use tag access=* to override them.

> Barriers with undocumented default access imply access=no. This default restriction prevents softwares from routing through undocumented barriers (and generating a potentially unsafe route).

So, the way the barrier is tagged right now, osmand behaves exactly as specified in this wiki entry. I will now add access=yes and see if it solves the problem.

**Comment by mirsto** [comment]
Ok, unfortunately that didn't solve the problem. However, as this ticket doesn't really address the actual issue (it's not about checkpoints, it's about the access tag), I opened a new ticket for osmand to ignore the access tag at [1] and close this one.

--

[1] https://github.com/osmandapp/Osmand/issues/2021
