### ISSUE TITLE
Osmand nighlies crashing since more than 200 versions

### ISSUE THREAD

**Issue by MAlfare** [osmandapp/OsmAnd#19416]
### Description

Crashes immediately after start, before showing map.
Last working version I own:
OsmAnd~ 4.7.0#1521m, released: 2024-02-04

Have emailed logs almost daily,
since some weeks, installation is not possible:
"App was not installed"

Is above Version the latest one, I can use?

### Steps to reproduce

Install  android-full-arm.
Start OsmAnd

### Actual result

Crash

### Expected result

Not to crash

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: Successors of OsmAnd~ 4.7.0#1521m, released: 2024-02-04
Android/iOS version: 8.1.0
Device model: Moto G4 Plus (XT1642)
Crash-Logs: ?
[exception.log](https://github.com/osmandapp/OsmAnd/files/14796125/exception.log)
[logcat.log](https://github.com/osmandapp/OsmAnd/files/14796126/logcat.log)

**Comment by pebogufi** [comment]
There was a problem with signature.
See
https://github.com/osmandapp/OsmAnd/issues/19262
Try 
- making a backup of everything
- Uninstall osmand
- Download latest nigthly and install
- Restore backup

For me that was the only way to solve the install problem with two devices.

**Comment by yuriiurshuliak** [comment]
Yes you're right. We have updated the certificate for the OsmAnd nightly builds. As a result, the current update mechanism is not functioning. To continue receiving the latest updates, users will need to manually remove the existing nightly version and install the new one. This action will restore the updating process.
