### ISSUE TITLE
Longer route preferred?

### ISSUE THREAD

**Issue by mirsto** [osmandapp/Osmand#1941]
There is some strange routing behavior for the following route:
from: Champoton, Campeche, Mexico, intersection of MEX 180 and MEX 261, just go a few meters North of that intersection
to: Benito Juarez, Campeche, Mexico

There is two alternatives:
A: MEX 180 -> SW; left on MEX 259; right on MEX 186
B: MEX 261 -> Southbound; right on MEX 186 at Francisco Escarcega

All roads on both routes are highway=primary. A is 12 km more than B. Nevertheless, osmand selects A. I don't see any reason to prefer A over B.

**Comment by xmd5a2** [comment]
Please provide us exact coordinates of the end point

**Comment by mirsto** [comment]
91° 05' 42.9"W,  18° 16' 41.6"N

**Comment by vshcherb** [comment]
Fixed
