### ISSUE TITLE
Bug parsing finish/end URL parameter IntentHelper

### ISSUE THREAD

**Issue by OscarDorronzoro** [osmandapp/OsmAnd#19422]
### Description

Android app doesn't show intended location and route when opening a link with OsmAnd containg the finish parameter.

### Steps to reproduce

Web app original link:
https://osmand.net/map/?start=-34.603722,-58.381594&finish=-34.607709,-58.370587&profile=car#16/-34.6063/-58.3798
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/48965382/4fc329e7-b5e9-4996-b223-24165d1de9fe"  width="500" height="auto"/> </th>
  </tr>
</table>

The IntentHelper class looks for an "end" parameter when parsing URL
https://github.com/osmandapp/OsmAnd/blob/4b8107f44fda6d425e83675b2566817783309a43/OsmAnd/src/net/osmand/plus/helpers/IntentHelper.java#L93

Workaround:
I tried to rename the "finish" URL parameter to "end", like this:
https://osmand.net/map/?start=-34.603722,-58.381594&end=-34.607709,-58.370587&profile=car#16/-34.6063/-58.3798
and it works, now android app opens the route correctly, plus web app is still working, it actually rewrites the URL with the "finish" parameter name instead of "end".

### Actual result

Original link led the app to open normally without any information from the link.

### Expected result

It should open on indicated location and show navigation menu, like the following (workaround applied):
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/48965382/d62d8349-7c6b-4f2c-a77c-d5726238b70d"  width="300" height="auto"/> </th>
  </tr>
</table>

Could you guys add the "finish" parameter to IntentHelper class, or rather modify web app to accept "end" parameter?
Thanks.

### Your Environment (required)

```
OsmAnd Version: 4.6.13
Android/iOS version: Android 11
```

**Comment by vshcherb** [comment]
Obviously we need to be backward compatible, so we will update web version I think

**Comment by RZR-UA** [comment]
There are few other discrepancies:

1. intermediate points Android: `ipoints`, which web never used (actually: "inter" and "via")
2. mode-string (profile,params) Android `mode`, which web never used (actually: "profile", "params")

@vshcherb please decide how to do a better fix:

- [ ] fix Android for all actual parameters (lose backward compatibility)
- [ ] fix Web/random-tester for "end" parameter only
- [ ] fix Web/random-tester for all parameters

Current URL fomat:

start=L,L&finish=L,L&via=L,L;L,L&profile=pedestrian&params=pedestrian,height_obstacles

Compatible URL format (seems to be not so pretty):

start=L,L&end=L,L&ipoints=L,L;L,L&profile=pedestrian&mode=pedestrian,height_obstacles

**Comment by vshcherb** [comment]
To do:
1. Web parse both finish & end, but in url use end
2. Android switch to profile instead of mode
3. Extra Android (if it's not easy) - support ```params``` and ```via```

**Comment by RZR-UA** [comment]
All done.

`end` fixed instantly on web

`profile`, `interpoints` should be ok in the next release

https://github.com/osmandapp/OsmAnd/assets/90444451/bf7a3f68-455f-4377-a0e1-9e19f395b1ce

**Comment by DmitryAlexei** [comment]
On Android works as expected. OsmAnd~ 4.7.0#1981m, released: 2024-04-04
- Android app opens web links with and without intermediate destinations.
- iOS app opens only direct routes, routes with intermediate destinations are not supported

[route](https://osmand.net/map/?start=-34.603722,-58.381594&end=-34.607709,-58.370587&profile=car#16/-34.6052/-58.3770) 

[route with intermediate destinations](https://osmand.net/map/?start=-34.603237,-58.381053&end=-34.607709,-58.370587&via=-34.598419,-58.374440;-34.603082,-58.372207&profile=car#15/-34.6023/-58.3824) 

<table style="width:100%">
  <tr>
    <th>route</th>
    <th> route with intermediate destinations</th>
    <th> ios route with intermediate destinations not supported</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/116079541/cc737512-c302-4b04-9090-f84bdedf70a3"  width="200" height="auto"/></td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/116079541/1c604ec5-40a8-4f8b-99ca-28b124118eaa"  width="200" height="auto"/></td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/116079541/f1e21c46-f9fe-4e30-a863-a4e355b00fc4"  width="200" height="auto"/></td>
  </tr>
