### ISSUE TITLE
improvement of the deleting process (maps, topo, wiki)

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#19428]
### Describe the idea (required)

The deleting procedure could need some improvement.
It is not possible to make a selection of what to delete (all data maps+topo+wiki by country, or at least a selection of maps/topos/wikis). 

Deleting a large number of data needs really a looot of clicks.
Downloading data still is nicely grouped by country, but deleting it is spread now (new layout) several sections.

Example Spain: it is 19 regions, each region has its own topo and its own wiki. Every single delete is three clicks (selecting, deleting, confirm). So only deleting Spain data is roundabout 180 selections/clicks. And Spain is only one of many large countries.

Cleaning up a large database is really much work. That could be smplified (like selecting more data, not doing one by one).

### Tell us about the expected behaviour (required)

simplfy it :-)

### Tell us about alternatives you've considered (required)

no alternatives, do it one by one by one by one....

**Comment by sonora** [comment]
On the "Local" tab (and after picking a map category like e.g. "Satandard maps") there is a "Select" functionality (under the 3 dots menu), after ticking any number of items, you can collecively delete. But it's true that after the recent refactoring of that screen you have to repeat this per map type, e.g. wikipedia, contour lines, etc. are in a separate list each.

**Comment by Rowin63** [comment]
Aah, sorry, yes! I didn't see the 3dots on top, only the 3dots at every map 😉
So it's only three lists to work, that's ok 👍
My mistake 😎
