### ISSUE TITLE
Let's delete "Show toll restrictions"

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#19423]
As is noted here https://github.com/osmandapp/OsmAnd/issues/19087#issuecomment-2027946789, we now seem to have an option "Show toll restrictions"  under Configure map>Details, but at least in the OsmAnd default  and also Touring view maps  styles (the latter very closely leaning on default for all rhese advanced details) the option has no effect.

Showing toll is instead controlled via "Show access restrictions", and rightly so.

Reasoning: More and more diversification and detailing of options increases not only the complexity and effort for code maintenance (and opens new occasions for bugs to occur and performance to slow), but in the end also demands more time from users to configure everything to their liking and usability.

I suggest we remove the separate "Show toll restrictions" option.

**Comment by pebogufi** [comment]
Please rename "Show access restrictions" to
"Show access and toll restrictions"
as it was long ago before this separation.

**Comment by vshcherb** [comment]
Well toll and access roads should be dislayed with pictograms and thus applied to all styles like routes. There is another task to display access restrictions. 
But I don't like idea combining them - toll roads is different from access.

**Comment by sonora** [comment]
They had always been combined Now they appear as separate options, but in all renderers I have tested, Show toll has no effect. Toll roads are controlled via Show access, as slways..

**Comment by vshcherb** [comment]
@xmd5a2 please provide details whether we can combine back or not

**Comment by xmd5a2** [comment]
Yes, for some reason option "Show toll" do nothing. I agree with Hardy that single option for access and toll if preferable because they logically related to each other.

**Comment by xmd5a2** [comment]
Fixed. How to test: open _Configure map - Details_ and see that there is no "Show toll" option.

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.7.0#2035m, released: 2024-04-10
I've looked through the Details sections for all basic map styles and there are no more "Show toll" option.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/540374f5-a345-4c89-ad48-9ae60e9a0732"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by pebogufi** [comment]
> Please rename "Show access restrictions" to "Show access and toll restrictions" as it was long ago before this separation.

Please rename...
