### ISSUE TITLE
Odd routing with live updates using HH

### ISSUE THREAD

**Issue by pgerber** [osmandapp/OsmAnd#19420]
### Description

See title

### Steps to reproduce

1. Enable HH x C++
2. Calculate route: https://osmand.net/map?start=47.166473%2C7.994892&end=47.196384%2C7.973160&mode=car#14/47.175205/7.990053

### Actual result

Instead of following the primary road, a "detour" is picked. 
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/11895833/0d805071-98b1-49c3-8e3b-227ae4525ce1"  width="300" height="auto"/> </th>
  </tr>
</table>

### Expected result

Route simply follows the primary road. Example using A* routing:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/11895833/85607bf0-1598-4b97-be2b-e5cecea91a55"  width="300" height="auto"/> </th>
  </tr>
</table>

### Your Environment (required)

```
OsmAnd Version: 4.7.4 / Nightly 4.7.0#1943m (2024-03-29)
Android/iOS version: Android 13
Device model: Galaxy Tab Active3
```

**Comment by RZR-UA** [comment]
Reproduced:

Route is OK using Default map: 98932163 Mar  1 01:00 Switzerland_central_europe_2.obf

But the Live updates (up to today) lead to the bug you described.

Affected: HH-java, HH-cpp
Not affected: BRP-slow, BRP-2phase (both Java/cpp are ok)

Day live obf with the bug 1117425 Apr  1 17:38 Switzerland_central_europe_24_03_06.obf

Precise live obf with the bug 161063 Mar  6 16:50 Switzerland_central_europe_15_50.obf

[ch-19420-live-hh-bug.zip](https://github.com/osmandapp/OsmAnd/files/14825954/ch-19420-live-hh-bug.zip)

```
1:brp-java cost=334.83 dist=3847.81 segments=716 seconds=0.2 via=0 profile=car
1:brp-cpp cost ok dist ok segments=717 seconds=0.0
1:**hh-java** cost +66.09% dist +61.23% segments=17594 seconds=0.2
1:**hh-cpp** cost +66.09% dist +61.23% segments=17594 seconds=0.2
```

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-core-legacy/compare/2093630a57267f4bd67843e1e7f703fe322ccd91..master

**Comment by yuriiurshuliak** [comment]
The bug has been fixed. Currently, the route is being built through the main road, and not through the detour.

OsmAnd~ 4.8.0#2212m, released: 2024-04-30

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/5d603be1-213a-499a-863d-5f11c8a75a12"  width="300" height="auto"/> </th>
  </tr>
</table>
