### ISSUE TITLE
Rendering of amenity=training

### ISSUE THREAD

**Issue by Edward17** [osmandapp/Osmand#1942]
Please add a rendering of objects with tag [amenity=training](http://wiki.openstreetmap.org/wiki/Proposed_features/training).

With this objects your map would looking more complete, for example: [MapSurfer.NET](http://openstreetmap.ru/#mmap=18/48.75118/37.61225&map=18/48.75118/37.61225&layer=S) (renders `amenity=training`), [OSM Standart style](http://openstreetmap.ru/#mmap=18/48.75118/37.61225&map=18/48.75118/37.61225&layer=M) (doesn't renders `amenity=training`).

They should be rendered with these rules:

* If the feature is a polygon - filling and border as of `amenity=school`; icon as of `amenity=school` (or, if you can propose something better, your variant); name as of `amenity=school`
* If the feature is a node - icon as of `amenity=school` (or, if you can propose something better, your variant); name as of `amenity=school`

Thanks!

---

_In Russian:_

Пожалуйста, добавьте рендреринг объектов с тегом [amenity=training](http://wiki.openstreetmap.org/wiki/Proposed_features/training).

C этими объектами ваша карта будет выглядеть более полной и привлекательной. Для сравнения: [MapSurfer.NET](http://openstreetmap.ru/#mmap=18/48.75118/37.61225&map=18/48.75118/37.61225&layer=S) (рендерит `amenity=training`), [OSM Standart style](http://openstreetmap.ru/#mmap=18/48.75118/37.61225&map=18/48.75118/37.61225&layer=M) (не рендерит `amenity=training`).

Они должны рендериться по следующим правилам:

* Если объект - полигон: заливка и граница как у `amenity=school`; иконка как у `amenity=school` (или, если у вас есть идея получше, то ваш вариант); подпись как у `amenity=school`
* Если объект - точка: иконка как у `amenity=school` (или, если у вас есть идея получше, то ваш вариант); подпись как у `amenity=school`

Спасибо!

**Comment by xmd5a2** [comment]
Done
