### ISSUE TITLE
Features with `demolished:*` tags are rendered

### ISSUE THREAD

**Issue by DIWesser** [osmandapp/OsmAnd#19432]
### Description

Demolished features are rendered in map. This lifecycle prefix is meant as a way to tag "features that have been demolished, without any traces left" that still show up in imagery.

[OSM wiki page for `demolished:*](https://wiki.openstreetmap.org/wiki/Key:demolished:*)

### Steps to reproduce

View a building or other feature with a tag beginning with `demolished:*`. (e.g. [this building](https://www.openstreetmap.org/way/84194728).)

### Actual result

Demolished features are displayed.

### Expected result

Demolished features are not displayed.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.6.12 (f-droid)
Android/iOS version: CalyxOS 5.5.1 (Android 14)
Device model: Google Pixel 5
Crash-Logs: ?
```

**Comment by DIWesser** [comment]
I have not tested how these tags are rendered in OSMand, but there are several similar lifecycle tags that should not be rendered:

[``]()
[``]()
[``]()
[``]()
[``]()
[``]()
[``]()
[``]()

**Comment by pebogufi** [comment]
Also this way is visible, and should not be rendered:
abandoned:highway=track
44.12946° N, 5.03425° E

**Comment by DIWesser** [comment]
I think it would make more sense to rendering `abandoned:*` like ruins rather than remove them. Looking at the wiki, [`abandoned:*`](https://wiki.openstreetmap.org/wiki/Key:abandoned:*), [`ruined:*`](https://wiki.openstreetmap.org/wiki/Key:ruined:*), [`ruins:*`](https://wiki.openstreetmap.org/wiki/Key:ruins:*) are all for features that are in a severe state of disrepair to the point where they are no longer fit for their original purpose, but are "**still useful for navigation and visible in the landscape**."

**Comment by pebogufi** [comment]
But i think abandoned:highway should not be used for navigation.

**Comment by DIWesser** [comment]
Oh, "navigation" is a bit ambiguous here. I think it makes sense to use it as a landmark for navigation, but I agree that it should not be used for routing.

**Comment by xmd5a2** [comment]
OsmAnd **doesn't** renders objects with prefixes `demolished:`, `no:`, 'removed:`, 'razed:`. See https://www.openstreetmap.org/way/152204576.
![Screenshot_2024-04-05_15-17-57](https://github.com/osmandapp/OsmAnd/assets/5829014/d921a103-cf19-447a-afc4-649db17cc66a)

But it renders objects like `leisure=sports_centre` from issues starter's example (https://www.openstreetmap.org/way/84194728)
That's why building is still visible in OsmAnd and osm.org. It is bad practice to keep such tags on demolished buildings because it is unlikely that search engines will consider `demolished:` prefixed tags.

**Comment by scaidermern** [comment]
> But it renders objects like `leisure=sports_centre` from issues starter's example (https://www.openstreetmap.org/way/84194728) That's why building is still visible in OsmAnd and osm.org. It is bad practice to keep such tags on demolished buildings because it is unlikely that search engines will consider `demolished:` prefixed tags.

If this sports center doesn't exist anymore then indeed the tagging is wrong. `leisure=sports_centre` should become `disused:leisure=sports_centre` and `name=Devonshire Arena` should become `old_name=Devonshire Arena`.

**Comment by DIWesser** [comment]
Thanks, that's good to know. I've updated the tags.
