### ISSUE TITLE
Sensor speed is writing into wrong tag

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#19435]
### How to reproduce
* Connect Speed sensor to OsmAnd
* Set it as source for recording
* Start track recording with sensor

### Actual result

* Speed is writing into `<osmand:osmand_-_speed_sensor>`
* Original track – [2024-04-01_13-15_Mon_Speed& Cadence .gpx.zip](https://github.com/osmandapp/OsmAnd/files/14822810/2024-04-01_13-15_Mon_Speed.Cadence.gpx.zip)

```
      <trkpt lat="50.4376657" lon="30.5070591">
        <ele>158.5</ele>
        <time>2024-04-01T10:15:16Z</time>
        <hdop>5</hdop>
        <extensions>
          <gpxtpx:TrackPointExtension>
            <gpxtpx:cad>18</gpxtpx:cad>
          </gpxtpx:TrackPointExtension>
          <osmand:osmand_-_speed_sensor>4</osmand:osmand_-_speed_sensor>
        </extensions>
      </trkpt>
```

### Expected result

* Speed is writing into `<osmand:speed_sensor>`, https://github.com/osmandapp/OsmAnd-Issues/issues/2158

**Environment**
OsmAnd Version: 4.7.0#1952m 
Android: 14
Device model: Pixel 6A, Garmin Speed Sensor 2

**Comment by DmitryAlexei** [comment]
Related td-android issue https://github.com/osmandapp/OsmAnd-Issues/issues/2448
