### ISSUE TITLE
Enabling track split interval removes graph with entire track height profile

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#19431]
### Description

Enabling the split interval for a track removes the possibility to view the entire height profile of the track.

### Steps to reproduce

* Enable a track that as height information
* Tap on the track on the map
  * In the track widget go to the track tab
    * The height profile for the entire track is visible 🙂
  * Go to the track appearance and set a split interval (e.g. 500 m distance)
  * Go back to the track tab
    * The height profile of the entire track is still visible 🙂
* Close the track widget
* Tap on the track on the map again
  * In the track widget go to the track tab
    * The height profile of the entire track is gone :cry:. Instead the height profile is now split into many different sections, each has the length of the previously configured split interval (e.g. 500 m). This is not useful and there is no option to view the entire height profile again.
  * Go to the track appearance and remove the split interval
* Close the track widget
* Tap on the track on the map again
  * In the track widget go to the track tab
    * The height profile of the entire track is visible again 🙂

https://github.com/osmandapp/OsmAnd/assets/1040784/e7b169c1-1471-49f5-a1e6-a307754ad5fe

### Actual result

Height profile of the entire track is gone and not accessible anymore.

### Expected result

Height profile of the entire track stays visible despite the split interval setting.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.7.4
Android/iOS version: Android 10
Device model: Samsung S9
```

**Comment by vshcherb** [comment]
Looks like split interval mistakenly does split analysis which is completely separate function. Split mark appearance shouldn't affect anything except UI marks
