### ISSUE TITLE
Incorrect altitude on tracks and points

### ISSUE THREAD

**Issue by Cubly** [osmandapp/OsmAnd#19430]
### Description

The correct altitude is reported on the map widget, but when recording/importing tracks or placing a marker, the elevation is reported ~50m higher than reality.

I have the world altitude correction map installed.

### Steps to reproduce

Record or import a track or place a marker and view the altitude.

### Actual result

About 50-60m higher elevation that reality.

### Expected result

Correct altitude consistently reported across the app

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.6.11
Android/iOS version: Android 14
Device model: 
Crash-Logs: ?
```

**Comment by sonora** [comment]
Can't reproduce for tracks recorded by OsmAnd. Perhaps the tracks you import had been recorded by some other app which saved ellipsoidal elevation with no altitude correction applied? Open one in an editor and check...

Regarding "Markers": Can you specify steps how to reproduce?

**Comment by DmitryAlexei** [comment]
Please update your app to the latest version or try beta from GPlay. Similar issues have been resolved.
If the issue persists, please attach to the comment your tracks, that have wrong altitude information (simply add .txt extension)

**Comment by Cubly** [comment]
Thanks for the responses, I have updated to 4.6.14 from F-Droid and the elevation correction option for existing tracks appears to have worked now. 

I recorded one track on OSMAnd and it had incorrect altitude, but I will try recording a new one next time I get out and see if my issue is resolved.

**Comment by Cubly** [comment]
Appears to be in working order now. Thanks.
