### ISSUE TITLE
Android Auto instructions don't make sense

### ISSUE THREAD

**Issue by limbusdev** [osmandapp/OsmAnd#19438]
### Description

Hi there. First of all: great work!

Now to my issue. When using android auto, some of the instructions don't make sense. In the following screenshot it says:

```
> 16.4km
turn right,
then
```

![signal-2024-04-01-14-23-52-124](https://github.com/osmandapp/OsmAnd/assets/6540152/81954fae-cab1-4884-91d4-1f7ea47480e5)

That "then" in the last line does not make sense here, since there are no additional instructions.

### Steps to reproduce

Simply use android auto with OSM+. Maybe only in German.

### Actual result

16.4 km turn right, then

### Expected result

16.4 km turn right

### Your Environment (required)

```
OsmAnd Version: OSMAnd+ 4.6.13
Android/iOS version: Android 14
Device model: Pixel 6
Crash-Logs: none
```

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.8.0#2184m, released: 2024-04-26
The issue can be reproduced in different locations. For example, for [this](https://osmand.net/map?start=53.934135%2C27.675997&end=53.939762%2C27.683659&profile=car#14/53.933195/27.683596) random route.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/355f8fe2-c53b-46c4-8d9d-5839ebf28514"  width="300" height="auto"/> </td>
  </tr>
</table>

<img width="600" alt="Screenshot 2024-04-26 at 18 34 44" src="https://github.com/osmandapp/OsmAnd/assets/116079541/d20e3a41-f7e4-4bff-a5c3-73f91fb52f7c">

<img width="800" alt="Screenshot 2024-04-26 at 18 35 22" src="https://github.com/osmandapp/OsmAnd/assets/116079541/d8998d86-17cc-4984-a06f-c4edd5a73bef">

**Comment by DmitryAlexei** [comment]
Important to note, that on web information is displayed correctly

<img width="824" alt="Screenshot 2024-04-26 at 19 03 29" src="https://github.com/osmandapp/OsmAnd/assets/116079541/224cca93-c6d0-47fc-8226-4f8d00d2dc18">

**Comment by vshcherb** [comment]
To do: check en/de it should be written "Turn right and go XXX km"

**Comment by alex-osm** [comment]
Probably fixed by https://github.com/osmandapp/OsmAnd-core-legacy/pull/231

**Comment by Chumva** [comment]
In RouteDetailsFragment we use [RouteDirectionInfo.getDescriptionRoutePart()](https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/routepreparationmenu/cards/RouteDirectionsCard.java#L112) & same happens in android auto, we could use [RouteDirectionInfo.getDescriptionRoute()](https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/routing/RouteDirectionInfo.java#L56) which adds distance to every RouteDirectionInfo

**Comment by vshcherb** [comment]
To do remove "and go/than" from strings - https://github.com/osmandapp/Osmand/blob/66bb20ff1b21cc98b3bf2b5c020c2f8f5f65dc79/OsmAnd/src/net/osmand/plus/auto/TripHelper.java#L249

**Comment by dmpr0** [comment]
## Review
We could show street name instead of turn type (we do so on CarPlay), arrow icon is already indicates turn side. Additionaly we can add street name next to distance into Second next turn widget https://github.com/osmandapp/OsmAnd-iOS/issues/3847

<img src="https://github.com/user-attachments/assets/49800332-275b-4118-a5df-8dbe72f39600"  width="300" height="auto"/>

**Comment by DmitryAlexei** [comment]
Docs:
Probably we need to add another section to Additional features 
- Next turn widget (+ second next turn widget)

**Comment by vshcherb** [comment]
[http://localhost:3000/docs/user/navigation/auto-car#next-turn - docs](http://localhost:3000/docs/user/navigation/auto-car#next-turn--route-info)

**Comment by dmpr0** [comment]
iOS task https://github.com/osmandapp/OsmAnd-iOS/issues/3847
