### ISSUE TITLE
On motorway exits no turn lanes are displayed or muted

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#19441]
From different tasks
- [x] From https://github.com/osmandapp/OsmAnd/issues/18789 - https://test.osmand.net/map/?start=49.177720,9.224997&finish=49.041469,9.267654&profile=car#18/49.16105/9.28233 - as it goes to motorway link (motorway another side) it shouldn't be muted - https://www.openstreetmap.org/way/4228009.296875
- [x] From https://github.com/osmandapp/OsmAnd/issues/19065 https://test.osmand.net/map/?start=52.282337,4.952173&finish=52.286098,4.945972&profile=car&params=car,prefer_unpaved#17/52.28475/4.94752 - all routes motorway link so they should be announced - keep left / right

**Comment by vshcherb** [comment]
Migrate C++:
- [ ] Self - https://github.com/osmandapp/OsmAnd/issues/19441
- [ ] https://github.com/osmandapp/OsmAnd/issues/19343
- [ ] https://github.com/osmandapp/OsmAnd/issues/19458
- [ ] https://github.com/osmandapp/OsmAnd/issues/19178

**Comment by ivanPyrohivskyi** [comment]
No tertiary turn on iOS UI for turn instruction ```Turn right (+TR,C,TSLR)```:
<img width="400" src="https://github.com/osmandapp/OsmAnd/assets/1040293/f45f8657-1dd8-431f-a1ac-4cdf4f103bc6" />
