### ISSUE TITLE
Idea: Allow to upscale 3D relief and 3D Track visualization

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#19443]
We need a slider [1-3] where we could make "artificial view" on 3D relief and 3D track.
This task is combined of 2 cause they need work together.
- 3D Relief Scale - values 1-3 call ```ReliefScale```
- 3D Track Scale - values 1-3 call ```TrackScale```

1. For all 3D points ```ReliefScale``` should be applied last.
2. For all Track points ```TrackScale``` is applied first by formula ```(Alt - MinTrackAltitude) * TrackScale + MinTrackAltitude```

Final formula for Track is ```((Alt - MinTrackAltitude) * TrackScale + MinTrackAltitude)*ReliefScale```

- - -

> Android task https://github.com/osmandapp/OsmAnd/issues/19474
> iOS task https://github.com/osmandapp/OsmAnd-iOS/issues/3560

**Comment by dmpr0** [comment]
# Review

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/7998e930-9b75-402a-bc3e-2f4a628aaec0
"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>  


- [ ] Issue with map zoom in / out gestures when Vertical exaggeration is on
