### ISSUE TITLE
AGPS updated or not?

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1944]
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot_2015-11-23-08-25-27.png
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot_2015-11-23-08-25-39.png
Cold GPS start is very slow. Can't figure out is AGPS data updated or not.

**Comment by sonora** [comment]
Leonid, unfortunately there is no global setting or flag in Android recording when A.GPS was updated, so what you find in the GPS Status app is when GPS Status last updated A-GPS, and what I have put in OsmAnd's development settings is when OsmAnd last updated AGPS.

Both values are "correct", but hey will not co-incide! The value in OsmAnd (I suppose also the one in GPS Status, but cannot say) is updated only after a successful AGPS update, so is very reliable!

Behavior of GPS and fix time after cold start or device-restart generally depends on the device's chipset, I don't think we can do more than we do today with the automatic a-GPS update.

PS: I had also implemented that you can force A-GPS update by tapping on the status setting in the development setting.
