### ISSUE TITLE
Missing or muted turn directions

### ISSUE THREAD

**Issue by Guylby** [osmandapp/OsmAnd#19458]
### Describe the routing engine used (required)

- [X] test.osmand/map online routing

### Describe your routing Profile (required)

Standard car profile

### Describe your start and end points (required)

Hi, I've found some routes where turn directions are either muted or inexistant when they shouldn't be. Here is some examples:

1. Along this route:
![Screenshot 2024-04-03 at 15-22-22 OsmAnd Map](https://github.com/osmandapp/OsmAnd/assets/151167525/a59d127a-55ed-488d-9942-641d771da6f5)

https://test.osmand.net/map/?start=43.139250,6.014183&end=43.140428,5.999568&profile=car#17/43.14000/6.00489
Two muted directions that probably shouldn't be: First should be a Keep left, but routing is "[MUTE] Keep left (+KL,KR)" and makes you miss the road separating. Second should be a turn right (or keep right at least) but is "[MUTE] Go ahead (+C,TSLL)".

2. At this intersection:
![Screenshot 2024-04-03 at 15-21-30 OsmAnd Map](https://github.com/osmandapp/OsmAnd/assets/151167525/73ce70d5-c6fa-421a-8089-7652b3d02039)

If you turn left: instructions are provided:
https://test.osmand.net/map/?start=43.120536,5.939929&end=43.122483,5.939521&profile=car#18/43.12093/5.94118
If you have to go ahead or turn right, instructions are muted:
https://test.osmand.net/map/?start=43.120536,5.939929&end=43.122158,5.943582&profile=car#18/43.12141/5.94180
https://test.osmand.net/map/?start=43.120536,5.939929&end=43.120834,5.943759&profile=car#18/43.12104/5.94140

3. At this highway interchange:
![Screenshot 2024-04-03 at 15-28-22 OsmAnd Map](https://github.com/osmandapp/OsmAnd/assets/151167525/46e9206b-200c-4879-9ad4-00785cfa2dd9)

If you have to go left, no directions are generated:
https://osmand.net/map/?start=43.459040,5.568920&end=43.481823,5.549823&profile=car#14/43.4759/5.5508
If you have to go right, a direction is generated but is incorrect and muted: Should probably be Turn Right but is [MUTE] Go ahead (TSLL|+C,TSLL)
https://osmand.net/map/?start=43.459040,5.568920&end=43.479456,5.595088&profile=car#14/43.4733/5.5708

4. This highway exit:
![Screenshot 2024-04-03 at 15-38-26 OsmAnd Map](https://github.com/osmandapp/OsmAnd/assets/151167525/e2285c9b-9a63-46cb-872d-adec16cfc64e)

The exit direction is muted as is the direction to follow once inside the exit:
https://test.osmand.net/map/?start=43.141352,6.003782&end=43.142980,6.011332&profile=car#17/43.14269/6.00756
Exit should probably say Turn right but is [MUTE] Go ahead (TSLL|+C,TSLL)
Once in the exit, if you turn right at the route separating in three, directions are provided:
https://test.osmand.net/map/?start=43.141352,6.003782&end=43.142462,6.010833&profile=car#19/43.14269/6.01002
But if you turn left or have to go ahead, instructions are muted:
https://test.osmand.net/map/?start=43.141352,6.003782&end=43.142618,6.011069&profile=car#19/43.14269/6.01002
https://test.osmand.net/map/?start=43.141352,6.003782&end=43.142746,6.010828&profile=car#19/43.14269/6.01002

### Describe the actual route (required)

Presented above

### Describe the expected route (required)

Presented above

### Describe what Maps you used (online or offline) (required)

- [X] Offline maps offered within the OsmAnd app for download. 
- [ ] Online (tile / raster) maps 

### Your Environment (required)

https://test.osmand.net/map/
Same results with https://osmand.net/map/

**Comment by vshcherb** [comment]
To fix: 
- [ ] https://test.osmand.net/map/?start=43.141352,6.003782&end=43.142618,6.011069&profile=car&params=car,noglobalfile#19/43.14275/6.00966 - Go ahead (+C,TSLR,TSLR) Should be Go ahead (TSLL, +C,TSLR)

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-core-legacy/commit/e61d9d07b4ee2147fda51d17b169ebf5b1614985

**Comment by vshcherb** [comment]
I think server was not updated, for last 2 days @Guylby please try again your 2 cases are fine now

**Comment by Guylby** [comment]
Yes everything is fixed on my end too, sorry for the post.

Thank you for all your work on the new routing!
