### ISSUE TITLE
Export heartrate and other sensor data in the gpxtpx format

### ISSUE THREAD

**Issue by Cubly** [osmandapp/OsmAnd#19453]
### Describe the idea (required)

Currently exported GPX files contain heartrate and speed in a 'osmand' tag, for example `<osmand:hr:>85</osmand:hr>`
It would be preferable if this data was tagged as standard with a gpxtpx tag, using heartrate as an example again `<gpxtpx:hr>85</gpxtpx:hr>`
This way the exported data would be readable by more applications by default, rather than being 'proprietary'.

I was slightly confused to discover this is the case as on the OsmAnd documentation, it does display the data is saved as such anyway: https://osmand.net/docs/technical/osmand-file-formats/osmand-gpx/#tags-name-for-sensor-data

(Unless I am missing some setting somewhere to change this)

### Tell us about the expected behaviour (required)

GPX data exported as defined in the documentation https://osmand.net/docs/technical/osmand-file-formats/osmand-gpx/#tags-name-for-sensor-data

### Tell us about alternatives you've considered (required)

No, it should be saved as standard

**Comment by dmpr0** [comment]
Hi! 
You need to use **Menu** – **Settings** – **Export to file**, in this case: `<gpxtpx:hr>`, `<gpxtpx:wtemp>` and `<gpxtpx:cad>` will be stored as TrackPointExtension.
As I know there is no tag in gpxtpx for speed, so it will be stored in OsmAnd extension.

**Comment by DmitryAlexei** [comment]
@Cubly Available in OsmAnd 4.7

**Comment by Cubly** [comment]
@DmitryAlexei Oh thanks, I thought they meant the speed tag specifically.

**Comment by Cubly** [comment]
@vshcherb I can only download 4.6.14 from F-Droid?
