### ISSUE TITLE
Leave address and location search only via "Show on map" - Let's temporarily fix for 2.2

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#1945]
On the Search address and Search location screen, under some conditions we still show the bottom icon bar displaying icons for "Directions to", "Waypoints", "Show on map", and "Favorites".

I suggest that in order to create interim consistency with the rest of our new context-sensitive UI, we delete this icon bar, instead consistently show a "Show on map" tick mark (or icon) in the top right corner of the search screen, tapping of which displays the location on the map and opens the context menu for it (exactly like we have it for tapping on any other location data now elsewhere throughout the  app).

The way we have it now, it is very inconsistent: Under some circumstances, we show the tick mark (like when you are on the street search subscreen), but on other occasions we show the bottom icon bar (like when you enter the address search tab from a neighboring search). When exactly we do what is a little unpredictable and actually also depends on the use history of the screens.

I have watched many new OsmAnd users trying to perform one of our main functionalities, the navigation to a street address. And the issue (and inconsistency) of how to leave the search address screen via the bottom icon bar (with icons not known to them) after finding an address/location via Search was the main showstopper they encountered. I think we could make an interim easy fix for this and get the app more in line with our new UI behavior in release 2.2, even before we actually tackle the search functionality later in 2.3.

**Comment by vshcherb** [comment]
It is an interesting question, I've thought OSM already provides most of the house numbers, so people don't need to need to go to search screen. I've thought it will be very special case when they want to select just city or something like that. Now I think you have a point, but I'm afraid it could create another issue or not.

**Comment by sonora** [comment]
House number coverage varies in OSM, good in some cities, completely missing in others. Also: Some people do not know the house number, they simply look for a street (or maybe just a town).

But the major issue I observed is: Sometime people end up on the screen displaying the region/town/street buttons, either by switching over from another search tab, or by tapping the back button from the street or similar screen. Then they may see the address they are looking for already displayed there, but have no idea what to do next. A single (and singular) "show on map" icon (or tick mark icon) instead of our legacy icon bar would likely solve the issue.

Cannot see what other issues it would cause? We simply delete the other 3 icons, and move the remaining "Show on map" icon+function to the top right corner? (Activate once the address is specified well enough)

**Comment by vshcherb** [comment]
@vshcherb	Fix issue #1945 -requires additional testing and cherry-picking to r2.2

**Comment by sonora** [comment]
I have tested the latest build, and find no issues!  But I am not 100% sure what was actually achieved, other than that on the street selection screen we now have a "Show on map" (which is good!), which formerly was a tick mark.

(On the select region and select city screen it is still tick mark:
- Tick mark on the select region screen makes no sense and should be removed?
- And tick ark on the select city screen should be made "Show on map" also, I guess ?).

But what I actually meant us to do is MUCH simpler. I have observed that some people get stuck when they are actually on the screen I attach below. and I wanted us to do the things I mark in red: Remove the 3 icons we now always have on the context menu (red X'es), and move the "Show on map" to the top right for consistency with the other screens.  (and do the same on the Search location) screen.
<img width="270" alt="screenshot_2015-11-24-08-30-24" src="https://cloud.githubusercontent.com/assets/845735/11360788/e53cc1c0-9287-11e5-9bac-2fcf7ccbb555.png">

**Comment by vshcherb** [comment]
Well looks like there was misunderstanding. I'm against refactoring that screen release 2.2, I know many many people were using that screen and for them it will be quite much to change it. I even think the change with show on map is quite a change. So I would postpone that feature for 2.3 release.

**Comment by sonora** [comment]
Well, we have always had the tick mark on the top right corner of the street selection screen. Mostly tapping it took you to the map screen all right, I think, but under some conditions it took you back to the screen my picture shows (had not researched when what happend). So unifying that was a good move and should be in 2.2.

Regarding
- unifying he remaining top-right "tick-marks" vs. "Show on map"
- and deleting the bottom icon bar:
I think it would be a harmonization and completion of our new context-centric UI, and superbly follows a "less is more" approach. If you ask me, I would seriously put it in r2.2: we introduce a major context-sensitive UI change now everywhere, and this is part of the logic, so we might as well make it complete as a big bang now. It is better than incremental changes later, where we will take the heat repeatedly.

**Comment by vshcherb** [comment]
For other screens I feel it was intuitive and here I'm not that sure... So I will change for nightlies and postpone for 2.2

**Comment by sonora** [comment]
My judgment is clear: I like it like we it have in the nightly now !  :-)
Thx - Hardy
