### ISSUE TITLE
Support multiparameters - Avoid motorways + "prefer unpaved roads" 

### ISSUE THREAD

**Issue by sinkoneri** [osmandapp/OsmAnd#19456]
### Describe the routing engine used (required)

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Describe your routing Profile (required)

I have a motorcycle profile where I enable "prefer unpaved roads"  bcos if I can I would love to ride offroad, but if no offroad route available I would like to go on paved backroads as a fallback option and awoid motorways in any circumstances.
But seems if no offroad route available, the navigation planner fallback logic doesn't take into account the avoid road settings.

### Describe your start and end points (required)

Test1
From: Budapest, Hungary
To: Velence, Hungary

Test2
From: Berhida, Hungary
To: Velence, Hungary

### Describe the actual route (required)

Test1 OsmAnd route (should not contain M7 which is a Motorway)
https://youtu.be/nO2mWsiIGa4?si=4c78oV-eYp3Gwl6M

Test2 OsmAnd route  (should not contain M7 which is a Motorway)
https://youtu.be/jokYmFxpHjo?si=V8yk6GLhCI2vI1sU 

### Describe the expected route (required)

Test1:
At 0:18 avoid motorways enabled, than route calculated fine
At 0:38 see the excpected route in the linked video 0:38 via route 7 which is paralel with M7 motorway. Expected route.
At 1:07 I enble "prefer unpaved roads" then the route gets recalculated but the resulting route is wrongly goes via M7 motorway bcos avoid motorways is still enabled.

Test2:
Avoid motorways enabled and prefer unpaved roads also enabled.
Navigation wrongly goes via M7 motorway
0:25 prefer unpaved roads disabled route gets recalculated and the route is fine via E66.

### Describe what Maps you used (online or offline) (required)

- [x] Offline maps offered within the OsmAnd app for download. 
- [ ] Online (tile / raster) maps 

### Your Environment (required)

```
OsmAnd Version: 4.6.13
Android: 14
Device model: Samsung S21 Phone

OsmAnd Version: 4.6.13
Android: 13                          
Samsung S6 lite tablet
```

**Comment by yuriiurshuliak** [comment]
It appears that the "prefer unpaved roads" setting may not be accurately influencing route calculations when combined with "avoid motorways." In this case, the "prefer unpaved roads" option is not affecting calculations for unpaved roads, but rather for motorways. Most likely, this is expected behavior and as the route you indicated is quite difficult to calculate only on unpaved roads. The "prefer unpaved roads" option doesn't completely exclude unpaved roads from consideration but rather lowers their priority. You can find the web version of the map [here](https://test.osmand.net/map/?start=47.497380,19.037180&end=47.229784,18.650196&profile=car&params=car,avoid_motorway,prefer_unpaved,nativerouting#11/47.4046/18.7626).

**Comment by sinkoneri** [comment]
The map you linked doesn't contain any unpaved roads so if "avoid motorways" enabled, and can't calculate the route with unpaved tracks the prefered route should be [this](https://test.osmand.net/map/?start=47.497380,19.037180&end=47.229784,18.650196&profile=car&params=car,avoid_motorway,nativerouting#12/47.2895/18.5995) via route 7, which avoids M7 motorway.
I think the fallback route should check the avoid filters but now it ignores.

**Comment by vshcherb** [comment]
Tha's not an issue of routing engine but issue of routing configuration - https://test.osmand.net/map/?start=47.497380,19.037180&end=47.229784,18.650196&profile=car&params=car,avoid_motorway,prefer_unpaved,noglobalfile,hhoff#14/47.2507/18.6793

**Comment by xmd5a2** [comment]
I've made some corrections. Routes are calculated as expected but surface for motorway is not considered. It can be an issue in places like Alaska, Siberia where motorways have bad surface. At that moment I don't see how this can be improved without routing engine enhancement. New maps are not required.
| Case 1 | Case 2 |
|--------|--------|
| ![Screenshot_2024-04-10_14-15-08](https://github.com/osmandapp/OsmAnd/assets/5829014/a7ccef34-ccc1-49ae-a4b5-1227da3a8230) | ![Screenshot_2024-04-10_14-17-44](https://github.com/osmandapp/OsmAnd/assets/5829014/7ecf212a-f0e0-4a00-95cf-4356ad2d327d) |

**Comment by vshcherb** [comment]
We need ```if=motorcycle, avoid_motorway, prefer_unpaved```

**Comment by sinkoneri** [comment]
> I've made some corrections. Routes are calculated as expected but surface for motorway is not considered. It can be an issue in places like Alaska, Siberia where motorways have bad surface. At that moment I don't see how this can be improved without routing engine enhancement. New maps are not required.

This routes looks good although I don't understand what do you mean by surface for motorway is not considered? Yes, b'cos it is set to avoid them. And if it is set to avoid motorways why could be a bad surface a problem? (The route doesn't even go via motorways. (Although with a motorcycle it shouldn't be a big problem at least with an adventure motorocycle with off-road capabilities)

**Comment by vshcherb** [comment]
We don't support proper multiparameter choice so our routing works fine with 1 selected parameter but with 2+ it doesn't find the right balance for penalties

**Comment by RZR-UA** [comment]
Routing.xml is updated and the original issue is fixed by https://github.com/osmandapp/OsmAnd-resources/commit/9edd7402af8b8d40042f27237d82b99c5d4ad06a (even without using multi-parameters).

Multiparameters requests are verified and tested. Ready to merge.

**Comment by xmd5a2** [comment]
This construction works:
```xml
			<if param="prefer_unpaved">
				<if param="avoid_motorway">
					<select value="0.05" t="highway" v="motorway"/>
					<select value="0.05" t="highway" v="motorway_link"/>
				</if>
```
Tested on [this route](https://test.osmand.net/map/?start=47.500397%2C19.060164&end=47.233323%2C18.667493&profile=motorcycle&params=motorcycle%2Cavoid_motorway%2Cprefer_unpaved#11/47.3774/18.7695) with my fix in [this commit](https://github.com/osmandapp/OsmAnd-resources/commit/ea34144d0f13bc4ddb6d78b7f106777093c209af).
Routing parameters used: **motorcycle, avoid_motorways,prefer_unpaved**
Without `<if param="avoid_motorway">` it uses [this motorway](https://www.openstreetmap.org/way/17350894)
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/1a6d7a81-088a-48c4-b852-8000bc566053)

With `<if param="avoid_motorway">`  it doesn't go via this motorway:
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/b8c29073-07f3-44aa-a766-b6d3d4e2d3fe)

Original issue is not reproducible

**Comment by RZR-UA** [comment]
> Route is still not fixed apparently this fix is not enough for HH routing. It should however work with AA routing

How we can fix it in HH routing? HH uses pre-generated shortcuts. Custom penalties such as `avoid_motorways,prefer_unpaved` broke the costs of shortcuts.

On short routes, HH-reiterations shoud fix broken shortcuts. On longer routes, A* routing would be automatically used if HH failed.

@sinkoneri could you confirm that issue is solved on your devices? It should be OK with OsmAnd 4.7.x release.

**Comment by vshcherb** [comment]
- [x] A* works correctly https://test.osmand.net/map/?start=47.497380,19.037180&end=47.229784,18.650196&profile=car&params=car,avoid_motorway,prefer_unpaved,routing:astar_normal_java,noglobalfile#12/47.2622/18.6956
- [ ] Default routing doesn't work - draws straight line (should be working

**Comment by RZR-UA** [comment]
Notes:

- [ ] double MEM_LIMIT on Web and check on HH+BRP route specified above (OOM problem)

- [ ] think about dynamic MAX_COUNT_REITERATION to drastically fast up the transition HH->BRP

- [ ] think about adding special penalties for motorway enters (for avoid_motorway param) instead of cutting the cost by extremely low values such as 0.05 (test the problem by comparing total_cost / visited_vertices on route specified above)

**Comment by RZR-UA** [comment]
Web (HH Java as default) done without Crash and/or OOM:

![web](https://github.com/osmandapp/OsmAnd/assets/90444451/e8cd8efd-5ece-4eb9-81e0-4429f86fd40f)

Android (simulator) tested in HH Java/C++ and A* Java/C++ modes:

![and](https://github.com/osmandapp/OsmAnd/assets/90444451/de104854-e98a-47da-bea2-c525561e9e07)

**Comment by RZR-UA** [comment]
The Web Routing's out-of-memory crash happened (by the "bad combination" of this 2 bugs) ~1600 times last 30 days, according to maptile server log.

**Comment by dmpr0** [comment]
Route – https://test.osmand.net/map/navigate/?start=52.297352,13.261871&end=52.309108,13.510780&profile=motorcycle&params=motorcycle,avoid_motorway,prefer_unpaved#12/52.3072/13.3237

<table style="width:100%">
  <tr>
    <th>Avoid motorways + Prefer unpaved roads</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/13f78bc1-89c8-41a7-b627-40ddb34c50b7"  width="600" height="auto"/> </td>
  </tr>
</table>   

<table style="width:100%">
  <tr>
    <th>Avoid motorways</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/3361f028-e60f-40b2-a86e-20dd8600c456"  width="600" height="auto"/> </td>
  </tr>
</table>   

<table style="width:100%">
  <tr>
    <th>Without applied options</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/45316f0a-8ed3-49eb-9ace-67e46e35732f"  width="600" height="auto"/> </td>
  </tr>
</table>   

<table style="width:100%">
  <tr>
    <th>Prefer unpaved roads</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/80c41303-45e4-4077-9d28-8e3a636aa074"  width="600" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
It's still navigation from A to B not a route planner to find any random road, so options prefer unpaved, prefer hilly could give confusing result as still navigation will try to find optimal (fastest route). 
For non-fast route there should be a limit how many hours trips should take
