### ISSUE TITLE
track´s folder "set standard appearance" does not work as expected

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#19455]
### Description

the "standard apperance" of a track´s folder in "my places / tracks" does not work - or at least I dont understand how.

### Steps to reproduce

go to:
) my places / tracks / 3 dots of a folder / set standard setting: offered preset is "blue / start & finish symbols ON / width medium"
) I set "symbols OFF ( meanwhile I really hate this fxxxxg symbols being ON again and again) / red / medium" / apply / apply changes? / apply  
) at this point I´m back to the tracks folder overview
) go again to the right before edited folder > standard setting again is "symbols ON (WTF) / blue / medium"

### Actual result

as described above.

### Expected result

remember my set standard appearance...

"set standard appearance" could be such a powerful tool...
Set it, and all tracks copied/moved to this folder get this selected standard settings... Something to dream about.

### Your Environment (required)

OsmAnd Version: +4.7.4
Android/iOS version: 13
Device model: S20+

**Comment by yuriiurshuliak** [comment]
Related to https://github.com/osmandapp/OsmAnd/issues/16943

Please let's hold on until that task is completed. Once resolved, we can reassess whether the problem you described has been addressed.

**Comment by Rowin63** [comment]
It perhaps may be a part of this other issue.
