### ISSUE TITLE
Let me ban Night buses from transport routing I BEG YOU

### ISSUE THREAD

**Issue by NastyFlytrap** [osmandapp/OsmAnd#19463]
### Describe the idea (required)

I dont want the public transport routing to even consider using night buses. Its the middle of the fucking day, and yes, i KNOW that osmand doesnt know when when vehicles leave, only the times it takes to get to each station, I KNOW, but telling me that wont fix the fucking issue that 75% of my route results use night buses, and i just have to keep scrolling past them every single time. What the fuck am i supposed to do with that? The night bus is not going to come at 2pm, and even calculating for it is a waste of good energy, and my time. 

Therefore, let me turn them off completely. Dont even waste the electricity in my phone's battery on calculating it. 

### Tell us about the expected behaviour (required)

Button that makes it so it doesnt even consider night buses when calculating the routes for public transport. 

### Tell us about alternatives you've considered (required)

Google maps, because that one actually works unlike osmand. 

If all you care about car drivers then you've pretty much lost by default because those people will never use osmand to begin with. Not in numbers big enough for development to be worth it. There are so many alternatives to driving instructors anyway. For public transport, where you're supposed to be competing, there's google maps and only that.

**Comment by mariush444** [comment]
I use osmand as car driver.

Anyway good idea but how to know which bus is night one without time table?

**Comment by NastyFlytrap** [comment]
> I use osmand as car driver.
> 
> Anyway good idea but how to know which bus is night one without time table?

Its marking them as night buses with the colour red based on something, so that could easily be reused for this purpose. Or, the buses in a lot of places have the N in front of their number, to signify that its only operating at night.

**Comment by sonora** [comment]
Best I lnow OSM data does not commonly contain when buses run, so likely there is no way to reliably identify something like a 'night bus' to fulfil this request.

**Comment by NastyFlytrap** [comment]
> Best I lnow OSM data does not commonly contain when buses run, so likely there is no way to reliably identify something like a 'night bus' to fulfil this request.



> OsmAnd relies solely on map data to determine possible routes. There's no timetable information included in the map data. The estimated travel time displayed reflects duration only, always starting at 0:00, and doesn't correspond to clock time.

Seems like i attracted the parrots again. Bummer.

**Comment by NastyFlytrap** [comment]
> OSM does not know what a "night bus" is. And relying on something like an "N" in a ref number is certainly unfounded.
> 
> Seems like currently this cannot be done, if you ask me.

At this point, 'it cant be made to work' = 'we dont give a shit'

It is only impossible with the current way osmand works, and this would help out a lot more feature, not to mention that if you genuinely want to compete with google maps, then 'we dont care' is not an option when it comes to making it work. 

That is, unless you only care to make a driving assistant, which is completely and utterly useless to me, and at that point you shouldnt even pretend to be working on a public transport routing system. What is this half baked bs. 

Yes, i know its in beta, but it sucks, and its also not moving forward from what i can see. Heck, the more i use it the more issues i have with the app as a whole. Its completely dysfunctional a lot of the times for multiple reasons.

**Comment by sonora** [comment]
@NastyFlytrap This being an Open Source project, perhaps with all the ranting you find some time to contribute some code? Code that works would beat arguing about it, hands down ... 😉

**Comment by mariush444** [comment]
> @NastyFlytrap This being an Open Source project, perhaps with all the ranting you find some time to contribute some code? Code that works would beat arguing about it, hands down ... 😉

His voice is not nice but reasonable but your opinion is not pleasant because you propose that every one should be baker, shoemaker, doctor and coder...

**Comment by sonora** [comment]
I meant it slightly different: The people willing to look into this have repeatedly assessed that this currently can't be done. B,ut the rant just calls them 'parrots' and repeats the request with no viable way forward, at least none visible to me.

**Comment by scaidermern** [comment]
In OSM, a [bus route](https://wiki.openstreetmap.org/wiki/Tag%3Aroute%3Dbus) (and probably other public transport routes) supports the [`opening_hours`](https://wiki.openstreetmap.org/wiki/Key:opening_hours) key.

So there is a way to fix this:
* Add appropriate `opening_hours` tags to all bus routes in your area
* Make OsmAnd evaluate the `opening_hours` key for public transport routes

**Comment by sonora** [comment]
@scaidermern Yes, I like that, good finding! Probably would need some kind of further configuration then to decide if a user is looking for PT connections now or for some other time...

Also: Not sure if _opening_hours_ is very commonly maintained for PT routes, need to research if usability is not rather disappointing.

**Comment by vshcherb** [comment]
It's a duplicate issue for Night busses and opening hours. I think @NastyFlytrap is a troll, so I close this discussion
