### ISSUE TITLE
Get rid of long-tap

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#1946]
When I watch my beta users play with our new context-sensitive UI, I observe that they frequently frown upon our long-tap vs. short tap behavior on the map screen.

Looks like we use short-tap to mark/select, and produce the context (or before the multi-selection) menu
- when tapping on objects on the Favorite, POI, or Downloaded Regions layer or other overlay layers
- (and of course when tapping on a results item on a search result screen, or the "Show on map" button there)

But we use long-tap to bring up the context menu for locations which are not objects of any overlay layer.

To the normal user not thinking about "layers" this is not obvious and awkward!

I guess we would produce a much snappier app handing if we abolished long-tap and made it all short-tap?

(It may also be a necessary unification if we ever wanted to combine to show address location and POIs around a selected (by short tap :-) ) map location in one multi-selection menu). We better think about creating a new handling now with te context changes we put in r2.2, rather than changing again later.

**Comment by vshcherb** [comment]
Not sure I want to keep it as Github open issue, especially from sonar, I've thought you are aware of our plans to make it by 2.2, but we didn't finish yet. So it will be available 2.3. 
And yes short click will be available only on names! So it will be still possible to use double tap to zoom in without awkward consequences.

**Comment by sonora** [comment]
Victor, no, I was not aware, sorry. This comes up as one of the top 3 observations I have when confronting inexperienced OsmAnd users with our new UI, so in a way I am trying to mitigate what can be done before the 2.2 release.  :-)

And please note that my suggestion simply is "get rid of long-tap", and convert it to short-tap. Nothing else. (Not sure I understand your reply about double-tap, zooming, or "short click will be available only on names". All other things should remain unchanged.) (Of course we would have to combine the one area where long-tap and short tap overlap today: the tapping on unnamed vs. named-layer items in close vicinity, but this can be dne via the multi-selection menu we already have.)

Best, Hardy

**Comment by vshcherb** [comment]
Short tap is important but not implemented yet. Short tap should be working like GMaps when you click on any label or icon.
Long tap is very important thing when you want to achieve precise lat/lon i.e. with stylus.

**Comment by jkufner** [comment]
@vshcherb I aggree with this. Short tap to select POIs, destinations and other marked places on map. But long tap is important for selecting other places where nothing is marked.

**Comment by sonora** [comment]
So why not use short-tap for _both_ scenarios?   I.e., if there is no POI,
destination. etc. in the area tapped , we immediately show the precise
position context bubble?  And if a user mis-tapped slightly, which happens
often, a correction by a subsequent tap can be made much faster!

I feel like the long-tap is an unwanted delay, serving no purpose?

(Of course, if there is also ad POI, destination, etc. in the immediate
vicinity taped, we would pop-up the multi-selection menu, like we do today
already if not one but several several named POIs are in the tap area.)

**Comment by vshcherb** [comment]
Don't like this approach there are 2 false possible cases:
- Double click on the map could be reacted as single click
- Accidental clicks on the map

**Comment by sonora** [comment]
True. but these are issues we already have on the DownloadedRegionsLayer,
on the POIl ayer (if you display many POIs), etc.

And I guess this may be exactly what bugs some people: That in some OsmAnd
situations they have to deal with these issues, in others not.

We should try to find a solution to unify the 2 approaches. In my mind, in
the long run tapping a named place like POI or destination, tapping a
region, or tapping on an unnamed point on the map are no different (!)
(certainly not to the user), so we should treat them the same and harmonize
how we handle them. Right?

**Comment by vshcherb** [comment]
I'm aware of that behavior for world map and we used to test that idea, so far that doesn't look convincing to me. Usage of that functionality is limited to low zoom levels which are fine for that purpose, but having this over >13 or >15 will raise another issues
