### ISSUE TITLE
Widget pointing arrow to waypoint and showing distance killed since last big update Jan or feb 2024?

### ISSUE THREAD

**Issue by erikrr** [osmandapp/OsmAnd#19466]
Using this widget the last ten years to point  to my hotel, station or other waypoint to find my way back.
Late feb I noticed in a new city it’s was gone!!  Removed I cannot chose the widget anymore only 
Choose the big arrow / Distance in de upper widget, but even after calibrate my gps it always seems at least 10 degrees off I even had 40 degrees one time.

I used my widget only show in left or right bar, and the widget in above bar they point never in the same direction that’s why I never used it. Also the upper bar widget arrow seems to broad it should be smaller to show the direction imho 

so please bring back the widget in the right bar it was was simple, always worked, always did its job to show me where is am in a city and where my waypoints are in an easy way.. I believe there are more witgets missing, but for now this the most important I missed. Without it OSMAND isn’t  usefull to me anymore. The arrow in the upper bar always feels off and because of not pointing exactly to the chosen way point I had it sometimes 20 degrees wrong.

Why nobody noticed it?
It was 1 widget and it showed a small arrow 100% pointing to waypoint and the distance to it.
I really hope it comes back  quickly because I never found that function in another gps  program.
I need a quick show on the map where I am don’t want to walk like a lost tourist in not so nice nabourhoods.
Sorry for my English not my native language

**Comment by dmpr0** [comment]
Hi! 
I didn't remember such widget. Maybe you have a screenshot?
OsmAnd can show arrow to map marker in **Map markers bar** or right on the map, it can be setup in Menu – Map markers – Options – More – Appearance on the map – Show arrows on the map

**Comment by yuriiurshuliak** [comment]
I understand you may be referring to the Map marker widget.  You can find more information here: https://osmand.net/docs/user/navigation/setup/markers-navigation/#pass-markers
If you could confirm whether this is the widget you are referring to, it would help us better understand the problem you're facing. Additionally, any further details you can provide, such as the version of the application you're using and any screenshots or videos demonstrating the issue, would be greatly appreciated.

**Comment by erikrr** [comment]
Device : e3q
Brand : samsung
Manufacturer : samsung
Model : SM-S928B
Product : e3qxeea
Build : UP1A.231005.007.S928BXXU1AXCA
Version : 14
App Version : OsmAnd+
Apk Version : 4.6.13 4613 

Hello, thank you so much for watching to find a solution. I wanted to respond earlier but I couldn't find the menu suggestions in the Dutch version.  I spent many hours clicking on possible options and 1 time, I managed to get an arrow and a line to the target. There was a solution here somewhere. And then it became clear to me that it wasn't a widget, sorry, but a combination of a distance widget and an arrow on the screen that always pointed to the chosen endpoint. So by default you have an arrow instead of a circle that moves when you walk and always points forward. Above that, another arrow pointing to the target. Now I had to find a way to set the line. Unfortunately I had to search for hours via a detour but in the end I managed to find a quick way to find the right setting screen. I was able to test it briefly and it seems to work well

I have included the version number that I am using now. It seems that this version turned off some settings without being asked, which caused me to run into this problem. These settings are so deep in the menu that I would never have found them. Thank you so much for your help

**Comment by erikrr** [comment]
I'd like to see if I can make a screenshot of this arrow towards the target and the arrow in the top widget row, where it's clear that sometimes they both don't point exactly to the same goal, e.g. 10 degrees deviation, which I think should always be the same :-)

**Comment by erikrr** [comment]
Here 2 arrows both pointing to the same waypoint they say. The one in upper widget is wrong how is that possible? The one in the middle is 100% good
Makes it difficult to depend on it for navigation 

![Screenshot_20240408_122831_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/35615542/990fd1a2-4b7a-4c2c-a84a-69225924fb26)

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce it, follow these steps: activate the Map markers bar, then within the Map markers settings, turn on "Show arrows on the map." Next, add a Map Marker and attempt to simulate navigation away from the Marker location. You'll notice that while the arrow on the map correctly indicates the direction to the Map Marker, the arrow in the Top bar widget is pointing in the wrong direction from the current location.

OsmAnd~ 4.7.0#2050m, released: 2024-04-12

https://github.com/osmandapp/OsmAnd/assets/127092082/e0097965-f79f-4703-b23e-8957c64fd8b3

**Comment by vshcherb** [comment]
I don't understand 
- Arrow on map is located according to the map
- Arrow in widget is located according to compass
