### ISSUE TITLE
Some aesthetic corrections.

### ISSUE THREAD

**Issue by franco999** [osmandapp/Osmand#1948]
1. It would be nice to be able to replace some icons (email and website) context menu for a more obvious.

(image modified by me)
![icons](https://cloud.githubusercontent.com/assets/12088580/11368838/a278f9ea-929a-11e5-946f-948041e03e34.png)

2. Also, you would have to add a space between the id and the error description, because it confused when written numbers.
![bug](https://cloud.githubusercontent.com/assets/12088580/11368839/a2852314-929a-11e5-938d-4d2ed922b368.png)

Icons: 
![email-icon](https://cloud.githubusercontent.com/assets/12088580/11368852/c536fbd0-929a-11e5-8fcb-ccd3d109797d.png)
![link-icon](https://cloud.githubusercontent.com/assets/12088580/11368853/c542b8e4-929a-11e5-80da-6846189ffb56.jpg)

**Comment by jf-simon** [comment]
Also by fax number there is a "Fax" text. by  phonenumber there is none

**Comment by franco999** [comment]
To display the information, I'd rather have an icon that identifies and not the word (email, facebook, etc) as in the previous photo.

**Comment by vshcherb** [comment]
Done
