### ISSUE TITLE
GPX sources from URL

### ISSUE THREAD

**Issue by jaller94** [osmandapp/OsmAnd#19485]
### Describe the idea (required)

Allow to import a GPX file from a URL.

### Tell us about the expected behaviour (required)

As a user I want to subscribe to a GPX file on a specific URL.
I want the import to update when the GPX file changes.

* The GPX import can be read-only because it changes when the external source changes (or OSMAnd could try to `HTTP PUT` a new file for collaborative favourites and tracks).
* I want to be able to configure 0 to unlimited URLs.
* For each file, I want to configure a schedule of how often it should be automatically updated. The schedule can also be disabled. The file can also be updated on the press of a button.

## From file system
* Allow to import from the file system and watch for changes

## Manual (works already)
* Manually downloading GPX files, importing them into OSMAnd, using them, and deleting them before importing a newer version

## Use cases
* Hiking trails
* Rapid POI updates in disaster regions (e.g. road blocks, first aid stations, supplies, people in distress, broken buildings)
* Temporary / private event maps (e.g. festivals, conferences, parades)
* Friends' live location, if they publish their location / trail as a GPX file
* OpenStreetMap mapping issues from external sources (e.g. https://osm-check.chrpaul.de/report/taiwan-metro-entrances-wheelchair/#downloads)

**Comment by vshcherb** [comment]
We promote of idea of online plugins. There is already online plugin for US Maps. It's possible to create another one and this one will keep import. 

Plugin is just a backup of OsmAnd (osf is a zip format). https://osmand.net/uploads/plugins/us.maps/1/us.maps-1.osf
