### ISSUE TITLE
After using the API to add new favorites, the original favorites will be lost.

### ISSUE THREAD

**Issue by tch123** [osmandapp/OsmAnd#19488]
### Description

In most cases, adding a favorite using the API will cause the original favorite to be
 deleted, leaving only the currently added favorite.
When this happens, I will use backup to restore. The maximum number of backups is 10. Sometimes after adding multiple favorites in succession, the correct backup will be overwritten by the new one.

Is this my API usage wrong?

### Steps to reproduce

Android [Tasker](https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm) Create tasks using the following API
osmand.api://add_favorite?lat=%gl_coordinates1&lon=%gl_coordinates2&name=%input&category=00inbox

### Actual result

After adding a new collection point, all original collections will be lost, and only the currently added collection will be retained.

### Expected result

Original favorits will not be lost after new additions

### Your Environment (required)

OsmAnd Version: Version 4.6.12
Android version: LineageOS 20 (Android 13)

**Comment by vshcherb** [comment]
I think it's correct but do you get that bug in a reproducible way or it happens randomly?

**Comment by tch123** [comment]
This happens randomly, I have tried to reproduce it but I can't find a way to do it

**Comment by yuriiurshuliak** [comment]
Please inform me if you're aware of how to reproduce this bug, including any steps involved. Also, could you confirm if this bug is still reproducible and relevant at present?

**Comment by yuriiurshuliak** [comment]
The issue might be closed due to the impossibility of reproduction.
