### ISSUE TITLE
Missing navigation details when offroad map style selected

### ISSUE THREAD

**Issue by Dan2077** [osmandapp/OsmAnd#19491]
### Description

Details such as Road Type, Surface and Steepness are missing when the Offroad map style is selected

### Steps to reproduce

In any of the profiles, configure the map style to Offroad then navigate to any location then check the details of the rout.

### Actual result

In the details section of the navigation menu, Road Type, Surface and Steepness are missing.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/108411636/b57ce1ba-3159-4646-98d9-c0cfaae3c78a"  width="300" height="auto"/> </th>
  </tr>
</table>

### Expected result

Road Type, Surface and Steepness should appear like in other map styles. Would be interesting to include Smoothness like in the walking navigation.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/108411636/e9784652-da2f-406b-b748-44020ac0cdb4"  width="300" height="auto"/> </th>
  </tr>
</table>

### Your Environment (required)

OsmAnd Version: 4.6.12
Android/iOS version: Android 14
Device model: Pixel 6
Crash-Logs: No crash

**Comment by zipav** [comment]
OsmAnd Nightly 4.7.0#2046m, released: 2024-04-12

Reproduced on the latest OsmAnd Nightly. When Offroad map style is selected, the Surface, Road Type and Steepness are missing.


|OsmAnd Map style| Offroad Map style|
|---------|---------|
|![image](https://github.com/osmandapp/OsmAnd/assets/123936521/57e2cf28-9529-416c-8b8b-ada5b4afbf5b)|<img width="373" alt="image" src="https://github.com/osmandapp/OsmAnd/assets/123936521/00dbbff0-38fe-4676-910e-ad8b950867e6">|

**Comment by xmd5a2** [comment]
Style was updated

**Comment by zipav** [comment]
OsmAnd Nightly 4.8.0#2182m, released: 2024-04-25

No longer reproduced. The Surface, Road Type and Steepness are displayed in both OsmAnd and Offroad style.

|OsmAnd Map style| Offroad Map style|
|---------|---------|
|<img width="373" alt="image" src="https://github.com/osmandapp/OsmAnd/assets/123936521/698f91c4-687b-4888-b908-334924b59262"> | <img width="373" alt="image" src="https://github.com/osmandapp/OsmAnd/assets/123936521/6080ff95-d4a2-4e73-9854-a74421fa9a4a">|
