### ISSUE TITLE
Offline navigation stopped while driving and OsmAnd asked to download maps

### ISSUE THREAD

**Issue by danielmmmm** [osmandapp/OsmAnd#19498]
### Description

I set up a route in OsmAnd+ (v4.7.6, Android) from "Maridalsveien 119, 0461 Oslo, Norway" to "St. Georgs vei 19, 0377 Oslo, Norway" and somewhere along Ring3/Rv150, the navigation stopped. At a gas station, I checked OsmAnd+ and got the error "Some offline maps for this route are missing", and I was asked to download offline maps for Trøndelag, Nordland, and Svalbard. None of these three regions are even remotely close to the Oslo region (300, 600, and 1900 km away!). The navigation would refuse to continue and the "Resume" button was disabled. When I went into "Maps & Resources" later, I saw that the map for Oslo was actually outdated too.

So, either a GPS glitch moved my position way up north for a split second (to a region I don't have maps for), or OsmAnd+ was missing the current map for Oslo but suggested the wrong maps to download (it was really just the three unrelated maps mentioned above).

For a possible GPS glitch, a sanity check would have avoided this situation. Like, if my position changes faster than a fast car would have managed (e.g. >80 m/s), OsmAnd should pause my position at the last known meaningful location, until new meaningful GPS data is available again.

If the navigation was stopped because of an outdated map, OsmAnd+ should (A) suggest to download the correct map, and (B) give me the choice to continue the navigation with an outdated map.

### Steps to reproduce

Use the navigation while a map update for the currently used map gets available.

And/or, trigger a GPS glitch during navigation.

### Actual result

The navigation stopped, (wrong) offline maps were suggested to be downloaded, the "Resume" button was disabled.

### Expected result

The currently used map (and only this map!) should be suggested for download. A warning message should be displayed that gives users the option to continue the navigation with an outdated map.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.7.6
Android/iOS version: Android 10.0 (LineageOS 17.1)
Device model: F(x)tec Pro1 (QX1000)
Crash-Logs: None
```

**Comment by ivanPyrohivskyi** [comment]
Need set CALCULATE_MISSING_MAPS=false during navigation

**Comment by danielmmmm** [comment]
Oh my, it happened again yesterday, two times actually. Both times, the bug was triggered after exiting a (short) tunnel. Now I am convinced we are dealing with a GPS glitch.

Both times, after exiting one of Oslo's many tunnels, OsmAnd told me that I was off the route for 3000 km. This would explain the unexpected suggestion to download offline maps far away from Oslo.

Both times, OsmAnd would seemingly "resume" navigation, but tell me immediately that I was 0 minutes away from my destination. My destination was still marked correctly on the map, and my position was correctly shown to be ~10 km away from said destination. The route, however, was not visible, and OsmAnd didn't give navigation instructions any more.
I had to cancel the navigation and start a new navigation with the same destination to get OsmAnd to calculate a new route.

I think "CALCULATE_MISSING_MAPS=false" during navigation is a good thing to implement. But the current issue is clearly not related to missing or outdated maps, but rather meaningless GPS data that OsmAnd doesn't check for validity. After all, a car cannot travel 3000 km within a split a second.

**Comment by vshcherb** [comment]
@danielmmmm OsmAnd checks GPS points for HDOP accuracy but this one gets triggered, we need to fix and recalculation should triggered even when no maps are downloaded.

 I thinnk @ivanPyrohivskyi is not correct that we shouldn't run check, we should:
1. run check for missing 
2. it fails
3. we get new current location routing should restart and all checks will pass

**Comment by danielmmmm** [comment]
Thanks for looking into this 💖

I just wanted to emphasise that the second time I encountered this glitch, OsmAnd did _not_ ask me to download missing maps.

OsmAnd told me that it would resume navigation. I don't know why OsmAnd thought I was "0 minutes away from my destination" directly after the GPS glitch occurred. Maybe that's part of the reason resuming the navigation failed? OsmAnd falsely assumed I reached my destination, while it also knew I was still 10 km away.

**Comment by ivanPyrohivskyi** [comment]
**GPX for test** (neet to unzip):
[Gps_fail.gpx.zip](https://github.com/osmandapp/OsmAnd/files/15036953/Gps_fail.gpx.zip)

**How to test:**
Import GPX.
Configure screen - Custom button (Quick action) - Simulate location by GPX - select GPX file
On main screen click on quick action button and start simulation. Select finish point and start navigation. 
**Expected result:** navigation continue after jumping location.
