### ISSUE TITLE
Importing specific GPX files for favorites crashes OsmAnd+

### ISSUE THREAD

**Issue by Barro** [osmandapp/OsmAnd#19492]
### Description

OsmAnd+ crashes when importing a lot of favorites or a smaller amount of favorites when there are more than 200 favorite points already imported (not a strict requirement). This is a flaky bug, that it doesn't happen with 100% certainty even with import file combinations that reliably cause it to happen at some point of time.

### Steps to reproduce

Select My Places -> My Favorites -> Import -> import the attached merged.gpx from Google Drive.
This is not 100% certain that the crash happens, but when you import these files several times, it'll happen eventually. Sometimes it's 100% consistent even after closing OsmAnd+. You can try out different combinations of these files, as sometimes the merged.gpx crashes OsmAnd+, but you can mostly work around importing those separate files individually. But then the last one of the collection that you try to import crashes.

[gpx-files.zip](https://github.com/osmandapp/OsmAnd/files/14897721/gpx-files.zip)

### Actual result

OsmAnd crashes.

### Expected result

Favorites should be imported without crashing the program.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.6.13, 4.7.6
Android/iOS version: 14
Device model: Samsung Galaxy S21, Galaxy S23, Tab Active 5 
Crash-Logs: attached
```
[OsmAnd bug S23.txt](https://github.com/osmandapp/OsmAnd/files/14897676/OsmAnd.bug.S23.txt)
[OsmAnd bug S21.txt](https://github.com/osmandapp/OsmAnd/files/14897677/OsmAnd.bug.S21.txt)
[OsmAnd bug Active5.txt](https://github.com/osmandapp/OsmAnd/files/14897678/OsmAnd.bug.Active5.txt)

**Comment by zipav** [comment]
OsmAnd+ 4.6.13, released: 2024-01-19

Not reproduced after several (8) consecutive attempts to import a file.
Imports both as a GPX file and as Favorites successfully.

**Comment by Barro** [comment]
Happened now with OsmAnd 4.7.7 (beta). Attaching the exception log and file that caused this crash. I'm also having 11 tracks that I'm synchronizing from OsmAnd Cloud with the Pro subscription. Would it help with debugging this, as one of those files crashes the web version of OsmAnd? Although I would need to adjust them for privacy related purposes.

I also got to import the favorites several times successfully today. But they didn't always show up in the user interface and had to delete and re-import them to make them show up. And that was also quite flaky to reproduce or not to reproduce.

[OsmAnd bug Active5-4.7.7.txt](https://github.com/osmandapp/OsmAnd/files/14924191/OsmAnd.bug.Active5-4.7.7.txt)
[merged.gpx.zip](https://github.com/osmandapp/OsmAnd/files/14924195/merged.gpx.zip)

**Comment by Barro** [comment]
I uninstalled OsmAnd+ 4.7.6 and imported the merged.gpx file attached in the previous comment without modifying/restoring any settings (so no OsmAnd Pro subscription was active) or downloading any map data. And OsmAnd+ crashed on import. So I don't think that the tracks that I previously had have any effect on this.

What kind of debugging could I do to help with this if you can't replicate the problem, as this relatively reliably happens with 3 different Samsung devices?

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.7.0#2031m, released: 2024-04-10 
Samsung galaxy note 20 ultra Android 13

Cannot reproduce crash wile importing favorites (see video 1). Although the app crashes after tap on a newly imported favorites from  [gpx-files.zip](https://github.com/osmandapp/OsmAnd/files/14897721/gpx-files.zip) (see video 2)
When I tap my old favorite the app doesn't crash.

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd/assets/116079541/1734f078-dfe7-4c28-a38f-fc6d83ddbaaa"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/osmandapp/OsmAnd/assets/116079541/a6f28e2c-c4d2-4ac0-ba7c-af71359c35a6"  width="300" height="auto"/> </td>
  </tr>
</table>
