### ISSUE TITLE
Crash trying Attach to the roads 

### ISSUE THREAD

**Issue by Velomeloman** [osmandapp/OsmAnd#19496]
### Description

Application crashes when I try to Attach to the roads downloaded gpx (rename without ".txt")
[Ясногорск - Тарусская (1).gpx.txt](https://github.com/osmandapp/OsmAnd/files/14903501/-.1.gpx.txt)

### Steps to reproduce
**Route parameters - GPX approximation - Geometry-based(Java, fast)** 
Import file - edit track - attach to the roads 

### Actual result

Crash

### Expected result

Normal behavior.

### Your Environment (required)

Device : HWMNA
Brand : HUAWEI
Manufacturer : HUAWEI
Model : MNA-LX9
Product : MNA-L29
Build : MNA-L29 13.1.0.206(C10E3R3P2)
Version : 12
App Version : OsmAnd~
Apk Version : 4.7.0#2008m 4700
[exception.log](https://github.com/osmandapp/OsmAnd/files/14903545/exception.log)

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce the described crash, follow these steps: import the indicated gpx file, build a route using this track, switch the GPX approximation to Geometry-based (Java, fast), and then attempt to attach to the roads this track. This will cause the app to crash.

[exception (7).log](https://github.com/osmandapp/OsmAnd/files/14906836/exception.7.log)
OsmAnd~ 4.7.0#2017m, released: 2024-04-08

https://github.com/osmandapp/OsmAnd/assets/127092082/9c721fd2-e59c-4515-9f36-49dde4ef557c

**Comment by RZR-UA** [comment]
Connected with https://github.com/osmandapp/OsmAnd/issues/18343

**Comment by RZR-UA** [comment]
Fixed (there was incorrect cleanup of finalPoints after approximation).

![photo_2024-04-09_14-11-52](https://github.com/osmandapp/OsmAnd/assets/90444451/124e69a8-ae1e-47b2-b1cc-22ddc9a7f71d)

**Comment by yuriiurshuliak** [comment]
The bug has been fixed. After changing the GPX approximation and attach to the roads specified track, the app does not crash.

OsmAnd~ 4.7.0#2031m, released: 2024-04-10

https://github.com/osmandapp/OsmAnd/assets/127092082/f90dc395-fddc-41be-ad0c-8abf74749041
