### ISSUE TITLE
Add Lithuanian voice package

### ISSUE THREAD

**Issue by embar-** [osmandapp/OsmAnd#19502]
### Describe the idea (required)

Lithuanian TTS for navigation is submitted here: https://github.com/osmandapp/OsmAnd-resources/pull/1061
Lithuanian voice OGG for navigation is submitted here: https://github.com/osmandapp/OsmAnd-resources/pull/1065
We need to package it make ready to use with OsmAnd

### Tell us about the expected behaviour (required)

LT voice is available option in OsmAnd application to choose for download

### Tell us about alternatives you've considered (required)

Manual copying into 
`/storage/...-.../Android/obb/net.osmand.plus/voice`
or 
 `/storage/emulated/0/Android/data/net.osmand.plus/files/voice`
 works.

**Comment by sonora** [comment]
Thanks - merged and uploaded.
