### ISSUE TITLE
Problems moving OSMAnd+ Folder

### ISSUE THREAD

**Issue by AndrewPButchart** [osmandapp/OsmAnd#19512]
I am running OSMAnd+ on my Samsung S23 android device.  I use an external app (MetaCtrl - Autosync) to back up track data and to load in updated maps.

A recent Android update has now blocked this external app from accessing the files under Android/data/net.osmand.plus/files.

I have tried using the "Manually specified" option to go to another folder that I created and that I know that I can synchronize to.  When I do this though, I get a message "maps could not be created in the specified directory".  So it would appear that this feature has also stopped working?

I also tried the "Multiuser Storage" option which goes to /storage/emulated/0/Android/obb/net.osmand.plus but that also appears to be blocked.

I reached out to Metactrl and they have no solution (looks like a common problem for similar software).  I tried support@osmand.net and they sent me here.

Any advice?

**Comment by Rowin63** [comment]
"manually specifiecd" does work in the "android/media/..." path.
Had the same problem, and here (and only here) it works now.

**Comment by AndrewPButchart** [comment]
> "manually specifiecd" does work in the "android/media/..." path. Had the same problem (synching my data), and here (and only here) it works now.

MY HERO!!!!

Many thanks.

**Comment by albansuser** [comment]
> "manually specifiecd" does work in the "android/media/..." path. Had the same problem (synching my data), and here (and only here) it works now.

Same here. Had to switch to the media folder a few weeks ago and OSMAnd, my file management app, and syncing/backup to PC all worked normally again.

**Comment by scaidermern** [comment]
Maybe OsmAnd should also offer the media directory as storage path?

**Comment by DDzwiedziu** [comment]
I've tried the manual directory with a Android 11 LineageOS-based ROM on a Sony phone and a Motorola G60 stock Android12. Setting it for `/storage/emulated/0/Android/Sync/net.osmand.plus/` causes the error “Maps could not be created in the specified directory”.

OsmAnd 4.7.10

**Comment by KronosTheLate** [comment]
I also encountered this issue. It would be great if the error (or the menu before selecting a folder)showed the limitations on the path format.
