### ISSUE TITLE
height in OSMand is saying it shows mean sea level but shows geodatic height 

### ISSUE THREAD

**Issue by paulle** [osmandapp/OsmAnd#19513]
### Description

![image_2024_04_09_23_28_01](https://github.com/osmandapp/OsmAnd/assets/4852079/0e9e29b0-f3b7-4b48-a8b8-a5f1bc747b5a)
Here is height measured with gpstest. Pink arrow is geodatic height and green arrow is the mean sea level. OSMand says it's showing msl, but it shows the geodatic height. Here in Germany it's a difference between 36-50 m (depending of the location).

### Steps to reproduce

Look at height widget in OSMand 

### Actual result

Showing gedatic height 

### Expected result

Showing height of mean sea level

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```
Osmand 4614
Android 14
Sony experia 5v

**Comment by sonora** [comment]
Do you have the "World altitude correction" downlosd active or not? You can find it under 'World maps'  in 'Download maps' (or 'Maps and resources' in newer versions). Most chipsets require this to produce MSL, but there are a few exceptions.

**Comment by paulle** [comment]
Thank you @sonora this solved the issue.
