### ISSUE TITLE
Direct display of address in object properties

### ISSUE THREAD

**Issue by Prusaker** [osmandapp/OsmAnd#19517]
### Describe the idea (required)

At the moment, when selecting an object, the OsmAnd does not show the direct address of the object, but seems to be looking for it. In some cases, the wrong address is displayed or the address is not displayed at all.

### Tell us about the expected behaviour (required)

This problem can be solved by allowing the OsmAnd to show the address in the object properties, and take the address directly from the object tags.

### Tell us about alternatives you've considered (required)

To solve the problem, just add two lines to file poi_types.xml:
<poi_additional name="addr_housenumber" tag="addr:housenumber" type="text"/>
<poi_additional name="addr_street" tag="addr:street" type="text"/>

I tried this method privately and it works:

![image](https://github.com/osmandapp/OsmAnd/assets/32092837/7e9a36f7-db07-4d07-8049-6b5cdd536b93)

**Comment by Prusaker** [comment]
Clarification: this method will only work if the buildin is marked as POI.
All other buildings that only have an address will appear as a "location" and will not show address tags :(

**Comment by DmitryAlexei** [comment]
@Prusaker have you accidentally closed this issue?

**Comment by Prusaker** [comment]
There is an important detail: in order to correctly display building tags with an address, this building must itself be like a POI. Without this, nothing will work :(
So, this issue must be closed as incorrect.
