### ISSUE TITLE
Viewing a specific track in OsmAnd+ crashes the application

### ISSUE THREAD

**Issue by Barro** [osmandapp/OsmAnd#19514]
### Description

When I open a track in OsmAnd+ that I had created and edited with https://osmand.net/map/, OsmAnd+ crashes. Also the web interface crashes if I remove the second to last point from the map. I have removed some points from between by using the web interface, so this could have changed the track to a format that OsmAnd can't handle. I'm using bicycle routing between points with this track. Following exception occurs when the track is viewed in OsmAnd+:

[lounais-vantaa-crash.txt](https://github.com/osmandapp/OsmAnd/files/14924290/lounais-vantaa-crash.txt)

### Steps to reproduce

Open the attached "Lounais-Vantaa.gpx" track in OsmAnd+. OsmAnd+ crashes.
Edit the "Lounais-Vantaa.gpx" track in the osmand.net/web and delete the second to last point in the track. The web interface goes blank.

Lounais-Vantaa nocrash.gpx is attached for a reference of the track what was modified with the web interface.
[lounais-vantaa.zip](https://github.com/osmandapp/OsmAnd/files/14924308/lounais-vantaa.zip)

### Actual result

OsmAnd+ crashes.

### Expected result

OsmAnd+ should show the track as it has previously done before I modified the track with the web interface.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.7.6
Android/iOS version: 14
Device model: Samsung Galaxy Tab Active 5
Crash-Logs: attached in the description
```

**Comment by DmitryAlexei** [comment]
reproduced with lounais-vantaa-crash.gpx
[exception.log](https://github.com/osmandapp/OsmAnd/files/14931134/exception.log)
Samsung galaxy note 20 ultra, 13 Android
App Version : OsmAnd~
Apk Version : 4.7.0#2023m

**Comment by DmitryAlexei** [comment]
I also tried deleting points from lounais-vantaa.gpx on the web. After deleting 5-6 points the screen went blank.

**Comment by vshcherb** [comment]
looks like indexing in GPX is broken, so it could be "fixed" by not causing crash
```
Caused by: java.lang.IndexOutOfBoundsException: Index: 487, Size: 437
	at java.util.ArrayList.get(ArrayList.java:437)
	at net.osmand.binary.BinaryMapRouteReaderAdapter$RouteRegion.quickGetEncodingRule(BinaryMapRouteReaderAdapter.java:365)
	at net.osmand.router.RouteSegmentResult.fillNames(RouteSegmentResult.java:246)
	at net.osmand.router.RouteImporter.parseRoute(RouteImporter.java:103)
	at net.osmand.router.RouteImporter.parseRoute(RouteImporter.java:84)
```

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.7.N#2092m, released: 2024-04-16
crash cannot be reproduced anymore
