### ISSUE TITLE
Android Auto - regression of split-screen

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#19527]
### Description

During navigation, when we switch to the split-screen and return to the full screen the landing screen appears, and the route line disappears.

### Steps to reproduce

1. Start navigation on AA on full screen
2. Switch to the split-screen (or another app with full screen) 
3. return to OsmAnd full screen

### Actual result

We see landing dialogue. 
The route line disappears.
The navigation process works and voice prompts are active.

<details>
    <summary>Screenshots (Nightly)</summary>
    <table style="width:100%">
      <tr>
        <th>Split-screen to Full screen (it's a first scenario)</th>
        <th>Full screen to Split-screen (after first scenario)</th>
      </tr>
      <tr>
        <td><img width="400" alt="image" src="https://github.com/osmandapp/OsmAnd/assets/44466116/2651b68c-5e2d-464d-ae86-5f43c9db4932"> </td>
        <td><img width="400" alt="image" src="https://github.com/osmandapp/OsmAnd/assets/44466116/c6ed386c-0e05-4fcc-9c0f-c785f2c32535"> </td>
      </tr>
    </table>   
</details>   

For the release version (4.7.7 4707) sometimes the black screen appears:

<details>
    <summary>Screenshots 4.7.7</summary>
    <table style="width:100%">
        <td><img width="400" alt="image" src="https://github.com/osmandapp/OsmAnd/assets/44466116/16e28e5b-7af2-43a1-a0aa-494a24ec392e"> </td>
        <td><img width="400" alt="image" src="https://github.com/osmandapp/OsmAnd/assets/44466116/311bfdf6-e16e-4290-98fb-d61875d58370"> </td>
      </tr>
    </table>   
</details>   

the 

### Expected result

We need to have a full screen in navigation mode.

### Your Environment (required)

It reproduces for Nightly and Release versions:

Device : r0s
Brand : samsung
Manufacturer : samsung
Model : SM-S901B
Product : r0sxeea
Build : UP1A.231005.007.S901BXXS7DXBD
Version : 14
App Version : OsmAnd~
Apk Version : 4.7.0#2046m 4700

App Version : OsmAnd
Apk Version : 4.7.7 4707

**Comment by EugeneZmeuk** [comment]
Device : r0s
Brand : samsung
Manufacturer : samsung
Model : SM-S901B
Product : r0sxeea
Build : UP1A.231005.007.S901BXXS7DXBD
Version : 14
App Version : OsmAnd~
Apk Version : 4.7.N#2073m 4708


https://github.com/osmandapp/OsmAnd/assets/44466116/c12e6bed-a83b-4fac-8559-a8fce93c0238

**Comment by vshcherb** [comment]
**To do**: do not loose navigation mode (line / instructions) while switching between apps

**Comment by EugeneZmeuk** [comment]
OsmAnd 4.7.9 (2024-04-15)

https://github.com/osmandapp/OsmAnd/assets/44466116/2dec935d-b19b-4939-921f-93b90dc2ad33
