### ISSUE TITLE
Add "Search" option to the Navigation dialog (in both start and end points)

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/OsmAnd#1952]
Once we launch the Navigation dialog, OsmAnd does not allow us to search for a new point to be added anywhere to the route (as start, waypoint or destination).

Like the ingredients in a cooking recipe, we have to keep all the points ready beforehand!
(search them and add them as a favorites)

This is a major limitation.

Desired: Add "search" option in both "from" and "to" menus.
In addition, the "Waypoint editor" dialog also should have this option.

**Comment by utack** [comment]
Oh yeah, enables a much smoother workflow and should technically somewhere between possible and easy.

**Comment by vshcherb** [comment]
For now it is not that feasible to implement, cause we have many screens, even though I like this way of thinking and we definitely need to implement it once we align our search technique.

**Comment by Chumva** [comment]
There is an option "search" in `Set starting point`, `Set destination` and `Add intermediate` dialogs in the new route preparation menu.

**Comment by sonora** [comment]
The entire route setup still has some room for improvement. As Victor correctly noticed: We have too many different screens/dialogs (and behind them code structure), which makes it both difficult to maintain, and spoils user experience.

I invite us to embark on my journey to reduce the number of screens, dialogs, settings, and configuration options, while still maintaining the same high level of sophistication and functionality we have implemented in all these years ... :)

- **I have the vision of on app where you do not have to configure anything at all.**

Let me repeat that:
- **I have the vision of on app where you do not have to configure anything at all.**

The app would conclude from situations and environment what your choices are. It may intelligently make the most likely best choices for your, or where needed would make suggestions, and ask you for best case a yes/no decision.

I know this is rather visionary, but we could try! I all too often support users saying "_you need to select this_" and "_set that_", and "_when you are hiking in a forest you better do this_", and "_there is a great setting for something here_". Some users admire everything we have, but others are just frustrated saying "How would I know?", or "I have better use for my time than feeling bad about taking the time or not knowing how to best configure some stupid app".

Our next challenge may not be "the next great feature", maybe it could be something along the lines I lay out?

**Comment by Discostu36** [comment]
I don't want to lock @sonora 's visions into the archive, but the original issue is fixed, isn't it?

**Comment by Chumva** [comment]
Yes, it is possible to open search for a start, finish, and intermediate points in the new navigation dialogue.
