### ISSUE TITLE
Allow OsmAnd to resume an interrupted download of map files

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#1953]
When I download updated map files, the download often fails.
And then OsmAnd starts the download afresh.

This wastes time and money.

Desired: Let OsmAnd server provide "resume" facility.
IINW some other apps have this facility.

**Comment by sonora** [comment]
This could be achieved by using the system download API, but I guess no further action planned here at the moment (?)

**Comment by DFyson** [comment]
This would be really nice to have.
I have had many experiences of trying to download map files over 1GB on slow speed internet and connection gets interrupted overnight and wake up to find it was never downloaded. Or pausing a download so other people can use some bandwidth.

Maybe a solution in the meantime might be to host the files as torrents and users can download them with an external client?

Infact maybe using a basic torrent client as the backend for the downloads in OsmAnd would be a good idea? Could distribute the files to anyone willing to seed them and thus reduce bandwidth costs and improve download speeds.

**Comment by DFyson** [comment]
This was also requested in a comment in #1134
