### ISSUE TITLE
there is no debug build of `libosmand.so` in the ivy repository, and I can't find instructions for building it from source

### ISSUE THREAD

**Issue by Mis012** [osmandapp/OsmAnd#19543]
### Describe the idea (required)

there are debug versions of .so files available for the `opengldebug` flavor, but for whatever reason `libosmand.so` is provided separately from that and therefore doesn't have a version with debug symbols available

### Tell us about the expected behaviour (required)

it would probably not be much work to upload the version with debug symbols, not sure if it should be used in all debug builds or only opengldebug builds

### Tell us about alternatives you've considered (required)

I considered compiling `libosmand.so` from source, but I wasn't able to find instructions for that, it seems it's not part of the `core`, maybe the android app still uses `core-legacy` rather than `core`?

**Comment by vshcherb** [comment]
Here is a good source https://osmand.net/docs/technical/build-osmand/setup-the-dev-environment/

**Comment by vshcherb** [comment]
Nobody debugged it via OsmAnd I guess
