### ISSUE TITLE
Railway service=yard not recognized as service rail

### ISSUE THREAD

**Issue by MeijiRestored** [osmandapp/OsmAnd#19545]
### Description

Railways tagged as service=yard are not recognized as service railways in OsmAnd, causing them to render differently :
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/42336759/5461f21f-83f5-4b27-85aa-94d41b06eece"  width="300" height="auto"/> </td>
  </tr>
</table>

Top is service=sliding, bottom is service=yard.

I tried editing the rendering styles to make the light gray color apply to service=yard as well but it had no effect, and they still rendered with the dark gray color.
Looking at the default rendering style, service=sliding seems to have been assimilated as service=spur, but not service=yard.

It would be nice to have service=yard assimilated as spur as well.

### Steps to reproduce

OSM Carto seems to be the only style that differentiates service railways.

### Actual result

service=yard should be recognized as a service rail and thus be rendered with a lighter gray

### Expected result

service=yard seems to not be recognized as a service rail.

### Your Environment (required)

```
OsmAnd Version: 4.7.0#2044m
Android/iOS version: 13
Device model: Poco X3 Pro
```

**Comment by DmitryAlexei** [comment]
@MeijiRestored Please clarify your point. 
In [Openstreetmap wiki](https://wiki.openstreetmap.org/wiki/Tag:service%3Dyard#How_to_Map) stated that, 

- A line within the yard should selected as the "main route", and the service tag should not be applied to it. This is to allow renderers to show the track at a higher zoom, and so that yards which are connected to a main line at both ends may be rendered unbroken.

At the same time, on the Openstreetmap.org I see, that service=yard is rendered with a light gray.

**Comment by MeijiRestored** [comment]
Yes that is right, see for example here :
osm.org
![Screenshot_2024-04-14-09-53-39-191_com opera gx-edit](https://github.com/osmandapp/OsmAnd/assets/42336759/a4c6d468-b8cc-4cb4-ae01-a14d691077d9)
osmand
![Screenshot_2024-04-14-09-54-20-974_net osmand plus-edit](https://github.com/osmandapp/OsmAnd/assets/42336759/aa728ed2-661d-4d3f-80b7-16b20de5455a)
The main way is not tagged with service=yard but the others are. However in OsmAnd the service yard does not get the lighter gray color even though service=sliding has it.

**Comment by xmd5a2** [comment]
Fixed. Map: France_hauts-de-france will be updated today
https://www.openstreetmap.org/?mlat=50.42167&mlon=2.95083&zoom=12#map=17/50.41706/2.95491
![Image](https://github.com/osmandapp/OsmAnd/assets/5829014/1f7af26f-29d2-4717-a4ca-e238761b9beb)

**Comment by zipav** [comment]
OsmAnd Nightly 4.8.0#2208m, released: 2024-04-29

Not reproduced on the latest build of OsmAnd Nightly.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/a3150ca9-861b-49d8-b86d-07621a43f721"  width="300" height="auto"/> </th>
  </tr>
</table>
