### ISSUE TITLE
crash on prog start immediately after show favorites

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#19546]
### Description

Crash.
(No crash with samsung tab s5e android 10)

### Steps to reproduce

Start app

### Actual result

Crash

### Expected result

No crash

### Your Environment (required)

OsmAnd Version: OsmAnd~  4.7.0#2064m.apk
Android version: 12
Device model: samsung S10
Crash-Logs:  
[exception.log.zip](https://github.com/osmandapp/OsmAnd/files/14967394/exception.log.zip)

```

**Comment by vshcherb** [comment]
Same crash https://github.com/osmandapp/OsmAnd/issues/19535

**Comment by Vucumpra** [comment]
Hello, Bug already exist today on  4.7.17 F-Droid version

Crash immediatly after show favourite routes but no crash for favourites POI.
