### ISSUE TITLE
Out of memory issue on startup 20 s after app launch

### ISSUE THREAD

**Issue by esilja** [osmandapp/OsmAnd#19548]
### Description

This issue started happening without a version change, I believe. I was previously recording GPX data, maybe the crash is related to that. I temporarily moved all the GPX tracks from tracks to tracks.bak, but that did not change the crash.

### Steps to reproduce

Probably not reproducible without my app data.

1. Open the app.
2. Wait 20 seconds. During this time, the launch logo flashes, the map is initially rendered a little, moving it feels sluggish and other parts of the map don't render. After ~20 seconds, the app crashes.

### Actual result

Crash due to OOM.

### Expected result

No crash, I'm able to use the app.

### Your Environment (required)

```
OsmAnd Version: 4.6.12 from F-Droid before trying to upgrade, but it also happened with 4.6.14 from F-Droid.
Android/iOS version: LineageOS 20 with microG
Device model: Pixel4a
```

Crash log obtained with `adb logcat | grep osmand | grep -vE '(ContextImpl|StrictMode)'`: [osmand.log](https://github.com/osmandapp/OsmAnd/files/14967497/osmand.log).

**Comment by vshcherb** [comment]
Looks like the app is reindexing GPX tracks and it takes lots of time. Please try to keep first smaller portion of your GPX and then add larger GPX 1 by 1

**Comment by esilja** [comment]
> Looks like the app is reindexing GPX tracks and it takes lots of time. Please try to keep first smaller portion of your GPX and then add larger GPX 1 by 1

I removed all GPX tracks in tracks/rec and it did not change this issue. It's still crashing.

**Comment by sonora** [comment]
I notice that there are lots of occurrences in your log file saying "`net.osmand.core:native: More than 1 basemap available`". Perhaps try temporarily removing the work overview map?

**Comment by traschke** [comment]
I have a similar issue with the app crashing shortly after starting. I did not do anything specific before the crash, but as GPX tracking mentioned before: I have a few tracks imported (around 10 to 15) and the tracking addon enabled, but I did not record tracks before the crash.
Interestingly the app crash also takes down the whole Android Window Manager Session which restarts after the app crashes.

OS: LineageOS 21 (Android 14, with Google Play Services)
App Version: 4.6.14 (F-Droid)

**Comment by yuriiurshuliak** [comment]
Could you please test our nightly version to see if this issue persists? You can download it from this link: [nightly builds](https://osmand.net/docs/versions/nightly_versions#nightly-builds).

**Comment by vshcherb** [comment]
> I notice that there are lots of occurrences in your log file saying "net.osmand.core:native: More than 1 basemap available". Perhaps try temporarily removing the work overview map?

Looks like this is the main after that app crashes

**Comment by esilja** [comment]
> I notice that there are lots of occurrences in your log file saying "`net.osmand.core:native: More than 1 basemap available`". Perhaps try temporarily removing the work overview map?

Does not change the problem.

> Could you please test our nightly version to see if this issue persists? You can download it from this link: [nightly builds](https://osmand.net/docs/versions/nightly_versions#nightly-builds).

How do I bring it into the same state as the other version? Just executing it results in a map view with no maps, no GPX tracks, but it also doesn't crash.

> Looks like this is the main after that app crashes

I don't understand this sentence. Was the issue closed intentionally? What can I do to resolve the issue?

**Comment by esilja** [comment]
> Could you please test our nightly version to see if this issue persists? You can download it from this link: [nightly builds](https://osmand.net/docs/versions/nightly_versions#nightly-builds).

After copying the data folder (with all my maps etc.) to the nightly build, I can only get it to crash after zooming around a lot on the map. So it might be a different problem.

**Comment by vshcherb** [comment]
That's might be an issue with data corruption which will be hard to reproduce, so if you don't experience it with nightly it's good.
Please let us know how does it go with fresh build
