### ISSUE TITLE
Turns slightly left when the main road turns left

### ISSUE THREAD

**Issue by pl71** [osmandapp/OsmAnd#19541]
### Describe the routing engine used (required)

- [X ] OsmAnd's in-app offline routing
- [X] Any online routing provider (YOURS, openrouteservice, OSRM, etc.) 

### Describe your routing Profile (required)

car

### Describe your start and end points (required)

from: 43.108315,27.775326
to: 43.106529,27.769049

### Describe the actual route (required)

https://osmand.net/map/?start=43.108268,27.775369&end=43.106545,27.769092&profile=car#17/43.10652/27.76916

### Describe the expected route (required)

The route is correct. First navigation point is misleading:
`Turn slightly left (+TSLL,C) and go 0.3 km.` is confusing, since there is another way going left.
![Turn slightly left](https://github.com/osmandapp/OsmAnd/assets/4776779/99730fc7-ab4b-45d9-90fb-1e5953ccfb7b)

### Describe what Maps you used (online or offline) (required)

- [X] Offline maps offered within the OsmAnd app for download.  Bulgaria 1.04.2024
- [X] Online (tile / raster) maps  https://osmand.net/map/

### Your Environment (required)

```
OsmAnd Version: 4.6.13
Android/iOS version: Android 14
Device model: S22 Ultra
```

### Anything else? (optional)

Google Maps would not announce anything here.

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-core-legacy/commit/36db3a4d9398bfcb63c11f53b27c00fd76317418
