### ISSUE TITLE
Crash on startup: null pointer exception invoking getPoiTypes()

### ISSUE THREAD

**Issue by spaanse** [osmandapp/OsmAnd#19556]
### Description

Open application, after a few seconds it crashes.
It is possible to use the app during those few seconds
Issue persists even when disabling plugins or enabling "safe mode" in the development plugin

### Steps to reproduce

Open app

### Actual result

It crashes

### Expected result

It should just work

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.4.4 4404
Android/iOS version: 
Device model:
Crash-Logs: 
```
[exception.log](https://github.com/osmandapp/OsmAnd/files/14971864/exception.log)

**Comment by DmitryAlexei** [comment]
Your actual version is Apk Version : 4.7.8 4708
Please, update your app to the latest version. Crash after update should be fixed already.
related https://github.com/osmandapp/OsmAnd/issues/19550
