### ISSUE TITLE
Can't navigate from Barcelona to Valencia (Spain)

### ISSUE THREAD

**Issue by Galbar** [osmandapp/OsmAnd#19551]
### Description

I have all Spain maps downloaded. I ask OsmAnd to calculate the route between Bacelona and Valencia and I get a message saying that there are missing maps. I click to download them and I'm met with an entry that has no name and size 0.0MB that brings me to the "Maps and resources" view in the app.
|||
|---|---|
|![image](https://github.com/osmandapp/OsmAnd/assets/3595851/a8ba7161-4234-48ef-9033-53ef14168923)|![image](https://github.com/osmandapp/OsmAnd/assets/3595851/ef0525cd-4fe6-41bf-ab70-222d90f92f72)|

Setting two stops in the middle (Reus and Amposta) seems to do the trick. But if I set Tarragona instead of Reus it doesn't work:
|Reus|Tarragona|
|---|---|
|![image](https://github.com/osmandapp/OsmAnd/assets/3595851/198f0a94-ca92-4257-a6b3-d6d439990303)|![image](https://github.com/osmandapp/OsmAnd/assets/3595851/41343da1-5115-4b8b-83cd-6becae657598)|

I suspect the issue may have to do with the "line of sight" between Barcelona and Valencia going over the sea.

### Steps to reproduce

1. Download Spain maps
2. Set navigation between Barcelona and Valencia
3. See the problem

### Actual result

I can't use the app to navigate between the two cities

### Expected result

Route is generated

### Your Environment (required)

```
OsmAnd Version: OsmAnd+ 4.7.6
Android/iOS version: Android 13
Device model: Fairphone 4
```

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.7.N#2076m, released: 2024-04-15
Steps to reproduce:
- search for Barcelona city, mark it as your starting point.
- search for Valencia, mark it as your destination point
- swipe navigation menu and see, that OsmAnd proposes you some maps to download (see screenshot) 
- download proposed maps and try to calculate your route once again (see video)

Actual result:
- you are proposed to download strange map named "."
- after downloading all the necessary maps, this map (with a "."" as a name) is still missing
- while there are missing maps, the route cannot be calculated

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/7552e021-643b-4741-9f40-91c7d3052c8d"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/osmandapp/OsmAnd/assets/116079541/701a9856-35ce-45a6-b2a7-9cc2c40de223"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
Similar result for iOS version of the OsmAnd app. Tested on TestFlight 4.7.3.6
- all needed for routing between Barcelona and Valencia maps are downloaded, but route cannot be calculated
- it is proposed to download missing maps, but required maps section is empty (see screenshots and video)

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/711c062a-a55c-4b58-96b4-c2d05bfb0e8c"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/f845a22c-41cb-42b7-96af-3efee2651dbe"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/osmandapp/OsmAnd/assets/116079541/f1bd467f-303e-4ea1-aea6-47d472157e19"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
Issue android fixed

**Comment by vshcherb** [comment]
Triangle is not part of the issue, the problem with Spain road only map - now it is fixed.

**Comment by vshcherb** [comment]
- [ ] Should be fixed and tested in IOS

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.7.N#2077m, released: 2024-04-15
No longer reproducable, route calculation works as expected 
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/4367398e-4b22-48a5-8ff1-4f73d6fb4cbd"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.7.N#2081m, released: 2024-04-15
tested on various routes, routing works as expected

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/12a80a27-0739-4547-b083-3cd7ccb2d023"  width="300" height="auto"/> </td>
  </tr>
</table>
