### ISSUE TITLE
track added via osm cloud is marked as deleted by local device after first sync

### ISSUE THREAD

**Issue by matejbart** [osmandapp/OsmAnd#19554]
### Description

If a new track is created on the cloud, or if an existing track is just renamed, then right after syncing the cloud changes to the android app, the app will immediately show that there are local changes (a delete of the recently synced track). So if the sync is performed again, then the new track is moved to the cloud trash folder, however, the local track is still accessible in the app.

- If the second sync has not been performed yet, and the app is killed and started again, then the local changes will disappear.
- If the second sync already has been performed, and the app is killed and started again, then the app tries to correct the cloud state by syncing it with the cloud folders.

I guess that this issue is also related to #19447

### Steps to reproduce

1. Create a new track on the web frontend osmand.net and upload it to the osm cloud.
2. Go to the (android app) to the "osmAnd Cloud" screen.
3. Tap on "Sync now": As a result the app shows that there are cloud changes (newly created track).
4. Tap again on "Sync now": The cloud changes will be downloaded, however the app will immediately show that there are "local changes" (the recently downloaded track is being moved to the cloud trash folder).
5. Tap again on "Sync now": The local changes will be uploaded, the recently created track is moved to the cloud trash folder.

### Actual result

After performing a sync, the app immediately shows that there are local changes that needs to be synchronized.

### Expected result

After performing a sync, I would expect to see no immediate local changes that needs to be synced.

### Your Environment (required)

```
OsmAnd Version: 4.6.13
Android/iOS version: 14
Device model: Pixel 6A
Crash-Logs: None
```

**Comment by dmpr0** [comment]
Fixed in release 4.7, it will be available for all users in less than a week.
