### ISSUE TITLE
Edit POI: "name" is truncated in "Advanced" list

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1955]
http://www.openstreetmap.org/node/3816339708
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot_2015-11-25-16-51-32.png

**Comment by GaidamakUA** [comment]
It truncates name, so it fits two lines. Is this an issue?

**Comment by xmd5a2** [comment]
Name should be 'Панно "Владимирская область" на стене' no matter how many lines.
