### ISSUE TITLE
Edit POI: can't upload POI

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1956]
When I create POI and then edit it (all in OsmAnd) it can't be uploaded to OSM. Error "Not Found", "Unknown problem" is displayed.

**Comment by MarkusH** [comment]
I encountered the same / similar error. The messages I receive are
"Loading POI...-2 failed : Not found"
and
"Committing node... failed : Bad Request"

For each of the POIs with -2 being the ID.

**Comment by vshcherb** [comment]
Fixed

**Comment by nakic** [comment]
I see this error now on when uploading changes made to an existing POI: I get "unknown error". I made the change from my laptop as a workaround, but I couldn't from OSMAnd after trying several times.
