### ISSUE TITLE
when using vectorial map 

### ISSUE THREAD

**Issue by alessandroame** [osmandapp/OsmAnd#19561]
### Description

When I use vector maps it ignores the visualization settings of the poi and always seems to show them all 

### Steps to reproduce

Selece vectorial map in map source
Disable POI from configure map / show

### Actual result

always shows tons of pois at high zoom levels

### Expected result

no pois should be visualized

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:  4.6.13
Android/iOS version: 13
Device model: realme 8 pro
```

**Comment by scaidermern** [comment]
> Disable POI from configure map / show
> 
> always shows tons of pois at high zoom levels

This is the expected behavior. Configure map / POI overlay is just to highlight POIs. They don't disappear if you disable this.

To disable POIs, use Hide / POI icons instead.

**Comment by alessandroame** [comment]
understood thank you is what i was looking for
