### ISSUE TITLE
Late map rendering update after profile change

### ISSUE THREAD

**Issue by Velomeloman** [osmandapp/OsmAnd#19562]
### Description

The rendering is not updated after switching between bicycle and pedestrian profiles, until you zoom or move the map, if the same map styles are selected in different profiles.

https://github.com/osmandapp/OsmAnd/assets/109347561/d62ed521-dc1a-4a3d-9178-f72539e73dc9

### Steps to reproduce

Set same map style for pedestrian and bicycle profiles, touring view for example. Switch from one to another profile.

### Actual result

Late map rendering update

### Expected result

Instant map rendering update

### Your Environment (required)

OsmAnd~ 4.7.N#2073m, 2024-04-14

**Comment by sonora** [comment]
I am wondering if simply "reading the map files" is very slow with recent builds. There could be a cross-connect to https://github.com/osmandapp/OsmAnd/issues/19373.

I have the experience with new builds that e.g. when I quickly pinch-zoom out rather far to the world-overview scales (where you see countries or continents), it takes a rather long time (even longer than your video shows until the correct map update) before the map is correctly filled again at al. Almost like reading the map files from storage for the first time per app session has become noticeably slow...

**Comment by Velomeloman** [comment]
If the map styles are different, the update occurs instantly. Updates are also quick when switching between car and pedestrian/bicycle profiles, regardless of map style.
https://github.com/osmandapp/OsmAnd/assets/109347561/90d4b312-ed5c-47fc-a73e-8e47fba47bc0

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced.  Choose the bicycle and pedestrian profiles and increase the level of detail in one of them to highlight the contrast. Then, switch between the profiles. The map will appear partially in the previous style and partially in the updated style until you zoom in or out, or adjust the map's position.

OsmAnd~ 4.7.N#2084m, released: 2024-04-15

https://github.com/osmandapp/OsmAnd/assets/127092082/f5108b9f-552b-41ab-a7b4-b9d2ed11caf2

**Comment by sonora** [comment]
Seems to only affect the V2 rendering engine, V1 works as expected for me.

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/commit/f3cf8cc3303f9b98385e9d33748f71a7b3bda932

**Comment by yuriiurshuliak** [comment]
The bug has been fixed. When switching between profiles, the map now displays in its entirety according to the selected profiles, without any delays.

OsmAnd~ 4.8.0#2831m, released: 2024-07-24

https://github.com/user-attachments/assets/5c009a3b-3be6-4afc-9629-82219a35397e
