### ISSUE TITLE
Downloads doesn't work on Android versions below 7.1

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#19575]
## Description
Due to changes in security certificates, starting 2024 users of Android devices with Android version below 7.1 unable to download or update maps.

### How to reproduce
* Get Android device with Android 6
* Open Menu – Downloads

### Actual result

* Empty map list

### Expected result

* Ability to download maps

**Environment**
OsmAnd Version:
Android: below 7.1

**Comment by DmitryAlexei** [comment]
https://osmand.net/docs/user/start-with/download-maps
probably here we should add info, when support for older devices will be stopped
