### ISSUE TITLE
Android Auto - incorrect radius-ruler font and flickers it during zoom

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#19573]
### Description

Scenario 1. Radius-Ruler flickers during zoom on Android Auto screen and has a huge font.
Scenario 2. My location radius appears during the change of map zoom.

### Steps to reproduce

Scenario 1:
1. add and enable Radius-ruler tool for Car profile
2. start navigation (or free-ride) on AA

Scenario 2:
1. change map zoom 

### Actual result
Scenario 1:

Look at my movies:
- 1 

https://github.com/osmandapp/OsmAnd/assets/44466116/280364ef-1816-435f-91ee-1826bd5755e0

- 2 

https://github.com/osmandapp/OsmAnd/assets/44466116/e3bd01bd-11bf-4fbd-abfc-43a93f037a3c

Scenario 2:

![telegram-cloud-photo-size-2-5255885925932717551-y](https://github.com/osmandapp/OsmAnd/assets/44466116/135f23c9-364e-4072-9782-82825c77a5c7)

### Expected result

Scenario 1:
Radius-ruler doesn't flicker during map zoom changes and has a normal (readable) view.

Scenario 2:
Radius artifact doesn't appear during map zooming.

### Your Environment (required)

```
Device : r0s
Brand : samsung
Manufacturer : samsung
Model : SM-S901B
Product : r0sxeea
Build : UP1A.231005.007.S901BXXS7DXBD
Version : 14
App Version : OsmAnd
Apk Version : 4.7.9 4709
```

**Comment by EugeneZmeuk** [comment]
This issue is similar with https://github.com/osmandapp/OsmAnd/issues/19406

**Comment by dmpr0** [comment]
# Review 



<table style="width:100%">
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/58c1acac-2bd9-4164-b0bf-c630dd455304"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] Radius ruler showing but with artefacts

**Comment by undrwater** [comment]
Radius ruler still does not display during zoom. OP's Scenario 2.
