### ISSUE TITLE
Incompleted offline map of Gansu China

### ISSUE THREAD

**Issue by thinjade** [osmandapp/OsmAnd#19571]
There is some offline map part missing  in west of Gansu China, the white area of the image. Could someone help to fix it? appreciate for that!

<img src="https://github.com/osmandapp/OsmAnd/assets/59408701/728d6f3f-cdef-4f8d-bda1-a376ed391da5"  width="500" height="auto"/>

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced.To test this, download the maps for Gansu, Qinghai, and Xinjiang. Then, navigate to coordinates 40.11678° N, 94.64823° E. You will observe that when the downloaded maps' borders are activated, the map along the border does not fully display in green, indicating it hasn't been fully downloaded.

OsmAnd 4.6.13, released: 2024-01-19

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/006db670-0dbc-41b4-b927-6a300998dbfd"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by xmd5a2** [comment]
Poly was updated. New map will be available at the beginning of may.

**Comment by yuriiurshuliak** [comment]
The bug has been fixed. At the moment, the borders of the loaded maps are displayed solidly and completely in green, without gaps.

OsmAnd~ 4.8.0#2422m, released: 2024-05-31

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/a7fdfe93-46cb-48e3-9c0a-764cd87f93f4"  width="300" height="auto"/> </th>
  </tr>
</table>
