### ISSUE TITLE
POI search: somehow highlight categories in search results list

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1958]
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot_2015-11-25-20-57-33.png
"Мастерские" is category but there is no obvious way to determine that. All other POIs here are in this category.

**Comment by vshcherb** [comment]
Don't have strong opinion here and don't see necessity.

**Comment by sonora** [comment]
Deprecated with new search interface, I guess.
