### ISSUE TITLE
Travel Guides not working in Danish

### ISSUE THREAD

**Issue by ERYpTION** [osmandapp/OsmAnd#19593]
### Description

The Travel Guides feature doesn't work when the language setting in the OsmAnd app is Danish. There is no content (nearby Wikivoyage articles) at all when I open the Travel Guide and I can't get any results from doing a search.

### Steps to reproduce

If the language in the app settings is English, everything works fine in Travel Guides. I can see and search all the Wikivoyage content (for the regions I have downloaded). However when the language is Danish (and possibly others) there is no content at all in Travel Guides. I tried bookmarking a Wikivoyage article while using the app in the English language setting. Switching back to Danish I can still see this bookmarked article in Travel Guides but nothing else. 
I have tried (repeatedly) clearing the app cache.

### Actual result

No Wikivoyage content in Travel Guides when using Danish as app language. No nearby articles or possible to get any search results.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/80313840/acc218f7-efcb-4721-9cb2-e31722d39f71"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/80313840/f16cd78b-1a37-4b84-96e1-63e23093bc53"  width="300" height="auto"/> </td>
  </tr>
</table>

### Expected result

Same Wikivoyage content as when using English as the app language. Of-course the Wikivoyage content will not be in Danish but I still think it should show anyway.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd+  4.7.9
Android/iOS version: Android 10
Device model:
Crash-Logs: ?
```

**Comment by vshcherb** [comment]
It's just not ready yet... https://meta.wikimedia.org/wiki/Requests_for_new_languages/Wikivoyage_Danish

There are no dumps from Wikivoyage for danish yet
