### ISSUE TITLE
Proposed layouts for the "Route Editor" dialog

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#1959]
Hi

Currently OsmAnd uses multiple dialogs to manage the points (start point, waypoints, destination).
The whole Information Architecture is very intricate and confusing for the average user.

Further, the **From** and **To** points are defined in a rigid manner; and are not interchangeable.
This creates further complication.

I propose to eliminate this complexity, and use a single dialog called the **Route Editor**.
(see attached file, which contains two _separate_ alternative designs).

All operations can be carried out in a single place:
- Adding points
- Giving meaningful names to the points
- Shuffling their order manually
- Automatic route optimization ("door-to-door" sorting)
- Deleting all selected points in one stroke. 

Note that I created the diagram just to illustrate the idea. So I left out some buttons (e.g. Navigation mode, settings,). It is easy to visualize them, though.

I personally like the second proposal, because it is much simpler. 
Yet it is more intuitive in visualization of the route. 
Plus, it can swap the start and end points very easily; thus creating the path for the return journey. 

[Route Editor - Proposed designs.pdf](https://github.com/osmandapp/Osmand/files/44148/Route.Editor.-.Proposed.designs.pdf)

**Comment by Barrocas** [comment]
That's more or less what I also would like to have to add/order/delete
waypoints (or destinations, whatever).
All in one screen, simpler and easier for the user.
I would prefer proposal 2.


-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by vshcherb** [comment]
I agree it makes sense

**Comment by gorn** [comment]
+1 this makes much sense! Currently it is very confusing. It happens to me very often that i want to (for example) delete a waypoint and it is even difficult to GET to the place where you are editing them. Than you press the x button and miss quite hidden checkbox to save changes and you can start again! Grr.

**Comment by gorn** [comment]
I like second proposal I would only make start and destination more visually set apart. Maybye it would be sufficient to replace 01 and 04 in left column by start and finish icon (finish coud use chckered flag) and leave numbers for waypoints

**Comment by sonora** [comment]
I also vote for suggestion 2, certainly a step towards better UI!

**Comment by zeromap** [comment]
The second suggestion is good, the illustrations are helpful in understanding. My only suggestion is to use a long press to select one or more waypoints instead of a dedicated delete mode and checkboxes. If anyone has used [Amaze file manager](https://github.com/arpitkh96/AmazeFileManager), similar to that.

Then you could apply actions more precisely such as sort door-to-door a selection or move a group of waypoints at once.


Example from Amaze
![unselected](https://cloud.githubusercontent.com/assets/15248277/12003445/ba5f75c4-aaec-11e5-885f-30344f7a41d5.png)
Unselected list
![selected](https://cloud.githubusercontent.com/assets/15248277/12003448/c6727f46-aaec-11e5-8930-73e4865cbebf.png)
Selection (Notice the change in color and icons in top right corner)

**Comment by ppenguin** [comment]
This would be great! The current version (which I use on an in-car head unit) is really a pain in that respect and really made me reconsider my options. 
I think long press to select (thereby eliminating the check-boxes for delete) would make sense (as indicated by zeromap), as it is already somewhat convention on touch-screens anyway.

Such a (sub-selection) of waypoints could then be subjected to delete or "optimised sort" (the term door-to-door is misleading), thereby making it possible to maintain partial mandatory (not-optimised) order for manual reasons (e.g. time constraints of the traveller).

Swipe to delete is also very intuitive, could be implemented both?

**Comment by raindropsfromsky** [comment]
I like both ideas, which are both used in Google apps (e.g. gmail) as well.

I have refined the idea in another closely related [issue] (https://github.com/osmandapp/Osmand/issues/2158#issuecomment-172741364).

IMHO that single window is the perfect solution; and meets all our needs.
* Single window (no jumping here and there)
* Handles all operations intuitively
* Streamlined (separate the "Find POI/Favorites along the route" command, and make it available directly during Navigation.)

Everyone (including Victor and Sonora) likes the idea. So don't know what's holding up.

**Comment by sonora** [comment]
Let us merge this into #2765.
