### ISSUE TITLE
When creating/modifying a quick action or custom button, ask whether to copy it to all other profiles

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#19609]
### Describe the idea (required)

When changing many other profile-specific settings, OsmAnd asks whether to modify just the current profile or to apply the change to all profiles.
When creating a new custom button or modifying an existing one, no such question is asked. It is possible to go to each individual profile and to copy all custom buttons from another profile. However, this is very cumbersome and annoying. 

### Tell us about the expected behaviour (required)

Adding/modifying a custom button of a profile should ask whether to apply this modification to all profiles.

### Tell us about alternatives you've considered (required)

Crying.

**Comment by vshcherb** [comment]
It's a good point. Though quick actions used to be Global across application and buttons are profile based

**Comment by mikehgentry** [comment]
Maybe you could add a 'Copy from another profile' option in the 'Custom buttons' screen, similar to the way it works with widget configuration.
