### ISSUE TITLE
Some translation issues

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/Osmand#1961]
See screenshots
![img_20151125_193708](https://cloud.githubusercontent.com/assets/11144987/11406074/fdcec86c-93ab-11e5-9805-bfcc3a1d9054.jpg)

![img_20151125_193424](https://cloud.githubusercontent.com/assets/11144987/11406095/1692c5b0-93ac-11e5-8db0-4a00a406460b.jpg)

Greetings Simon

**Comment by vshcherb** [comment]
It will be translated by community just later or you can contribute as well translate.osmand.net

**Comment by jf-simon** [comment]
Thanks for the hint, I'm working on it
