### ISSUE TITLE
Solomon islands Honiara Street Names

### ISSUE THREAD

**Issue by Dave-A-A** [osmandapp/OsmAnd#19613]
Hi

I work with with Solomon Islands Government and we have Street Names available for Honiara. 

We have provided this to Google Maps and would also like to provide these details to OSM

But we aren't sure how to provide this and in what formats.

Please advise and we want to help make OSM better for Solomon Islands

**Comment by pebogufi** [comment]
First steps for information how OpenStreetMap works
https://wiki.openstreetmap.org/wiki/How_to_contribute
https://wiki.openstreetmap.org/wiki/Getting_Involved
https://wiki.openstreetmap.org/wiki/Notes
https://wiki.openstreetmap.org/wiki/How_to_map_a

Or you can contact to a local comunity to ask them for assistance
https://community.openstreetmap.org/c/communities/9/none
