### ISSUE TITLE
In the elevation profile scale of the entire route

### ISSUE THREAD

**Issue by FlorianMattes** [osmandapp/OsmAnd#19619]
### Description

The elevation profile uses the scale of the entire route permanently. When I drive, I see the elevation profile for the next 10km, but unfortunately with the scale of the entire route and not with that of the displayed section of the route.

### Steps to reproduce

Take any route through the mountains with a length of 100km. Then the route starts and shows you the elevation profile.

### Actual result

If the 100km is between 100m and 1600m altitude, then this scale is always displayed. Even if the next 10km are between an altitude of 1200m and 1500m.

### Expected result

Before the last update, the scale was adjusted. In our example, the scale was set to 900m and 1600m altitude and adjusted as the route continued.

### Your Environment (required)

Device : star
Brand : Xiaomi
Manufacturer : Xiaomi
Model : M2102K1G
Product : star
Build : UKQ1.231207.002 release-keys
Version : 14
App Version : OsmAnd
Apk Version : 4.7.9 4709

**Comment by FlorianMattes** [comment]
![Screenshot_2024-04-19-16-07-10-477_net osmand-edit](https://github.com/osmandapp/OsmAnd/assets/159344850/22409bdd-6e78-4dfd-b36e-0afada2d5afb)

**Comment by dmpr0** [comment]
# Review 
- [ ] ToDo is missed
