### ISSUE TITLE
Add shields for routes without `symbol` tag

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#19617]
## Description 
We can add custom shields for route without `symbol`:
* White background or equal to  route color
* Symbol equal to route type

**Examples:**

* MTB – https://www.openstreetmap.org/relation/1777778
* Hiking – https://www.openstreetmap.org/relation/4483721, no icon and color
* * With colour – https://www.openstreetmap.org/relation/12540906

**ToDo**
* Prepare icons for all supported route types:
* * hiking
* * horse
* * fitness_trail
* * bicycle
* * mtb
* * running

**Comment by xmd5a2** [comment]
Fixed. Germany_hessen,brandenburg and berlin will be regenerated today.
