### ISSUE TITLE
download percentage should have more digits

### ISSUE THREAD

**Issue by HolgerJeromin** [osmandapp/Osmand#1962]
On a slow internet connection you need 1-2 hours for downloading a large offline map. Right now the percentage is displayed as an integer. Could be rather annoying to see a change only every 10 minutes.
So please display `12.49%` instead of `12%`.
Or even `12.49% (25.21MByte/200MByte)` or something like that. There is enough space in the GUI iirc.

**Comment by sonora** [comment]
Not a priority issue, I guess.
