### ISSUE TITLE
Moped navigation build a rout through private roads

### ISSUE THREAD

**Issue by Nihisil** [osmandapp/OsmAnd#19628]
### Description

When creating a route with the Moped profile, it navigates through roads that have gates tagged with:
```
access=private
barrier=gate
bicycle=no
foot=no
horse=no
motor_vehicle=no
```

### Steps to reproduce

Check the online route (it also happens on the iOS app) with Moped profile selected: https://osmand.net/map/?start=13.736858,100.621408&end=13.740365,100.621988&profile=moped#18/13.73795/100.62051

Access to private roads wasn't enabled:
![image](https://github.com/osmandapp/OsmAnd/assets/475367/33834e21-737d-4cdc-bd10-84180746977e)

### Actual result

![image](https://github.com/osmandapp/OsmAnd/assets/475367/86c2ba28-0701-4a64-86d8-9661252b3efc)

### Expected result

Private roads are not used when building navigation routes.

### Your Environment (required)

```
OsmAnd Version: web version
iOS version: 4.6.6.1
```

**Comment by DmitryAlexei** [comment]
Confirmed
moped routing uses this [node](https://www.openstreetmap.org/node/6681014870) tagged access=private, private=gate,  bicycle=no, foot=no, horse=no, motor_vehicle=no
![Screen Shot 2024-04-21 at 21 38 21 PM](https://github.com/osmandapp/OsmAnd/assets/116079541/a2d122a2-0268-47c8-b639-b411bb7ca86f)
![Screen Shot 2024-04-21 at 21 38 33 PM](https://github.com/osmandapp/OsmAnd/assets/116079541/afa82c13-a03e-4bb8-b16e-ed5efd021615)
![Screen Shot 2024-04-21 at 21 38 42 PM](https://github.com/osmandapp/OsmAnd/assets/116079541/3ce6699a-7666-4382-985b-6750e446ebb8)
![Screen Shot 2024-04-21 at 21 38 55 PM](https://github.com/osmandapp/OsmAnd/assets/116079541/c37084d5-7b74-42e5-a2b6-8569b315a38b)

**Comment by vshcherb** [comment]
@xmd5a2 Probably we just need to add penalties to routing.xml section

**Comment by DmitryAlexei** [comment]
Routing for moped correctly works on web (https://osmand.net/map/?start=13.736858,100.621408&end=13.740365,100.621988&profile=moped#17/13.73900/100.61944)

- moped route on android follows web version
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/e8fd4c78-7f70-4a4b-a3d7-91a48ae118f5"  width="300" height="auto"/> </td>
  </tr>
</table>

- on iOS OsmAnd proposes different route (default profile settings)
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/1b14ba99-4ac7-4850-8c6d-3ecc2232f76b"  width="300" height="auto"/> </td>
  </tr>
</table>
