### ISSUE TITLE
Zoom scales flickers although zoom changes deactivated

### ISSUE THREAD

**Issue by FlorianMattes** [osmandapp/OsmAnd#19621]
### Description

The zoom adjusts while driving even though it is set to manual.

### Steps to reproduce

Just drive and see

### Actual result

The zoom adjusts while driving.

### Expected result

If automatic zoom is disabled, the zoom should not change.

### Your Environment (required)

Device : star
Brand : Xiaomi
Manufacturer : Xiaomi
Model : M2102K1G
Product : star
Build : UKQ1.231207.002 release-keys
Version : 14
App Version : OsmAnd
Apk Version : 4.7.9 4709

**Comment by nazar-kutz** [comment]
Can't reproduce.
Disabling automatic zoom in the settings results in it not working when navigate (as expected).

For a more precise understanding of the problem, please provide a video of the problem and/or specific steps on how to reproduce the problem.

**Comment by FlorianMattes** [comment]
Next time i'm driving I will take a video.

**Comment by FlorianMattes** [comment]
https://github.com/osmandapp/OsmAnd/assets/159344850/bf3effec-d9c9-4e70-92b9-371e0c9c365a
I recorded a video where you can see how the scale changes and the map is zoomed in. This time it was just a small zoom correction. And the scale flashes the whole time. That wasn't the case in the previous version.

**Comment by vshcherb** [comment]
It's possibly related to 3d relief, even though I'm not sure map scale changes (looks very similar). You can put widget Map zoom so it will be more obvious.

**Comment by FlorianMattes** [comment]
https://github.com/osmandapp/OsmAnd/assets/159344850/7dab3d5b-98b3-4559-8e5a-7b4ad993fdb5
In this video you starting Android Auto changes zoom.

**Comment by FlorianMattes** [comment]
https://github.com/osmandapp/OsmAnd/assets/159344850/27247bfc-a19d-4eb3-9951-b31dc6d3d43a

Here you see the zoom moves. Video is not normal speed.
Without Android Auto zoom stays, does not change.

**Comment by FlorianMattes** [comment]
Yes, it's flickering. That only happens in Android Auto.
But in the video you clearly see the scale ist changing.
Now I installed the Version 4.6 because I need the navigation nearly every day.

**Comment by DmitryAlexei** [comment]
todo:
- [ ] disable zoom bar flickering while using android auto

**Comment by Corwin-Kh** [comment]
When disabled, ruler still changes it's size and scale. While the map is hidden when android auto is connected, the ruler was hidden.
