### ISSUE TITLE
Motorway exit is no longer displayed

### ISSUE THREAD

**Issue by FlorianMattes** [osmandapp/OsmAnd#19620]
### Description

On a route from Valencia to Montanjeos I noticed that after the last update, the motorway exit is no longer displayed. If you drive on the motorway, a roundabout is displayed next. The exit that was previously required is not mentioned or displayed.

### Steps to reproduce

See above

### Actual result

See above

### Expected result

The exit should be indicated before the roundabout comes.

### Your Environment (required)

Device : star
Brand : Xiaomi
Manufacturer : Xiaomi
Model : M2102K1G
Product : star
Build : UKQ1.231207.002 release-keys
Version : 14
App Version : OsmAnd
Apk Version : 4.7.9 4709

**Comment by RZR-UA** [comment]
@FlorianMattes Could you make a screenshot with exact location of missed motorway exit?

Please check the link with pin and route: https://test.osmand.net/map/?start=39.674114,-0.299241&end=40.069127,-0.522918&profile=car&pin=39.921275,-0.566162#16/39.9218/-0.5707

Is it the exit from Autovia Mudejar to CV-195?

Please confirm the location.

**Comment by RZR-UA** [comment]
Please check my screenshot.

For that last exit from Autovia Mudejar to Montanjeos (road CV-195) I have got no problem with missed/not-displayed exit.

There is turn right (80 m) from Motorway to CV-195 displayed and the next roundabout comes in 300 meters.

@FlorianMattes please specify exact location where the problem you described happens.

![ok](https://github.com/osmandapp/OsmAnd/assets/90444451/abe7972a-8ded-41f3-9c31-bdff72525f7d)

**Comment by FlorianMattes** [comment]
It was exactly at this exit.
I drove on the highway and it said „in 64km drive into the roundabout and take exit 2“ (I don’t know which numbers it really said).
If it happens again somewhere I will take a screenvideo.

Florian Mattes

**Comment by RZR-UA** [comment]
I've just retested the problem in r4.6, r4.7 and Master builds.

Everywhere is the same positive result: 1st notification for highway exit, then for roundabout

Possibly, you were used some of recent nightly builds in a period when the Turn lanes were broken.

Please try again with the fresh Release or Nightly builds.

There is video (+ voice) from current Master build:

[ok.webm](https://github.com/osmandapp/OsmAnd/assets/90444451/42d62f69-06e0-4f7e-a232-30487997a40e)
