### ISSUE TITLE
Osmand seems to ignore bicycle:backward=no

### ISSUE THREAD

**Issue by Peter0** [osmandapp/OsmAnd#19638]
### Describe the routing engine used (required)

- [×] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Describe your routing Profile (required)

bicycle
ignoring height data
consider temporary issues

### Describe your start and end points (required)

Start: 50.74431° N, 7.15323° E
Dest.: 50.74253° N, 7.14855° E

### Describe the actual route (required)

Route goes straight trough Way #31768289.

### Describe the expected route (required)

As there is a bicycle:backward=no tag at Way #31768289, I expect to route a detour, as is the case if I mark the street by means of button "Avoid Street" (supposed translation of button to English)

### Describe what Maps you used (online or offline) (required)

- [×] Offline maps offered within the OsmAnd app for download.  
- [ ] Online (tile / raster) maps 

Among others Europe/Germany/Nordrhein-Westfalen/Regierungsbezirk Köln, standard type, 2024-04-01, 02:00
Live updates as of today 13:12

### Your Environment (required)

```
OsmAnd Version: OsmAnd~ 4.6.14
Android/iOS version: /e/OS similar Android 9
Device model: Samsung Galaxy J5
```

### Anything else? (optional)

Until issue doesn't go away with May edition maps, I’d take into consideration if this may be an issue with occasional Live updates’ tags scrambling. Ref. #19201 for this issue.

**Comment by scaidermern** [comment]
I can confirm the same behavior with OsmAnd 4.7.10.

[This way](https://www.openstreetmap.org/way/8070137) is routeable in both directions in bicycle mode although it has `bicycle:backward=no`.

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. When setting up the navigation using the specified coordinates, the route is built via [Way: Marktstraße (31768289)](https://www.openstreetmap.org/way/31768289#map=19/50.74322/7.15115) with the tag bicycle:backward=no applied there. This behavior is also observed on OSRM. You can view the web version [here](https://test.osmand.net/map/?start=50.744450,7.153070&end=50.742530,7.148550&profile=bicycle#17/50.74338/7.14892).

OsmAnd~ 4.8.0#2166m, released: 2024-04-24

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/78742b3a-71d5-45e3-b4ab-04d09d858b34"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/05e4e987-25cd-4831-9bf2-7a54d15d3e61"  width="500" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/221adc58-1cd4-4aed-a7ab-3f42148406bf"  width="500" height="auto"/> </th>
  </tr>
</table>

**Comment by Peter0** [comment]
problem still exists even with new May released maps. But I have to confess that I haven’t tested with really switched off Live updates. Just updated maps and then hoped that there is no disturbing live update.

**Comment by xmd5a2** [comment]
Fixed. Now new maps required.
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/7fabaeb8-5518-43d5-8ea3-6ec94dd01c94)

**Comment by Peter0** [comment]
Does that mean the problem goes away with update to maps from June 2024?

**Comment by yuriiurshuliak** [comment]
The bug has been fixed. Currently, the bicycle route is no longer being built via [Way: Marktstraße (31768289)](https://www.openstreetmap.org/way/31768289#map=19/50.74322/7.15115) with the tag bicycle:backward=no applied there.
Check the web version [here](https://test.osmand.net/map/?start=50.744450,7.153070&end=50.742530,7.148550&profile=bicycle#17/50.74338/7.14892).

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/41a745f8-ebda-4f32-bdb1-b95bb3c63061"  width="300" height="auto"/> </th>
  </tr>
</table>
