### ISSUE TITLE
Bug with destination tags in new map generations

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#1963]
I am not sure when it started, but just notice that in our current obf maps we apparently have a problem treating "destination" tags.

As an example: when OsmAnd instructs to turn onto http://www.openstreetmap.org/way/23444897, our tts voice prompter says "Turn right onto none, none, airport, none, Regensburg;Würzburg;Nürnberg-Nord;Berlin", which apparently somehow reads the "destination:symbols" (while ignoring "destination:ref"). Using a map a few months old, OsmAnd correctly announces  "Turn right onto A3 Regensburg;Würzburg;Nürnberg-Nord;Berlin". (Tested with release version 2.2.1 and 2.2.2)

**Comment by vshcherb** [comment]
Just 2 weeks ago we fixed bug with incorrect names in routing files, so it might be related

**Comment by sonora** [comment]
Appears fixed with latest map generation.
