### ISSUE TITLE
Hide power tower in car profile

### ISSUE THREAD

**Issue by Velomeloman** [osmandapp/OsmAnd#19636]
### Describe the idea (required)

Partially related to #14536.
Power towers are rendered in too much contrast. This is not very important, but distracting information while driving.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/109347561/cb285ec1-3e62-4d4f-9263-38598bc11e91"  width="300" height="auto"/> </td>
  </tr>
</table>

### Tell us about the expected behaviour (required)

Hide power towers in car profile. 

### Tell us about alternatives you've considered (required)

Add switch to Configure map - Hide menu.

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.8.0#2151m, released: 2024-04-21

- power lines are visible while driving
- some unimportant POI (recycling center on my screenshot) also rendered in driving profile
- also district borders, should they be rendered?

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/a9a33f06-5a65-4c5c-9ade-9f0405f66a89"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/1ba5e3e4-b913-4161-822f-f1fe6ba7665a"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
Not convinced it's by default

**Comment by Velomeloman** [comment]
Closed https://github.com/osmandapp/OsmAnd-resources/commit/16f3af9425f58b127c3d91000291ec90f9d67734
