### ISSUE TITLE
Delete the distance column in Waypoint list

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#1964]
The "Waypoints" screen has a **Distance** column, but it does not add any value, because-
1. It actually shows the "as the crow flies" distance from the center of the screen.
   As we browse the map, the center changes, and makes the distance irrelevant.

2. It does not show the distance along the route (naturally, because the route is yet to be calculated)
   Even if it were to show the distance along the route, this information would not be useful to the user.

Thus, this column can be eliminated in the present design.

In fact, in my proposed layout of the **Route Editor** GUI, I had included the distance column.
But now I have realized that it has no value. 
Therefore I propose that it should be dropped in the future design too.

**Comment by Barrocas** [comment]
Not so, if Osmand could find our position by gps, and set that displayed
distance acording to our position, it would be very usefull for planning an
immediate route.

Even when planning another route (without gps) it os nice to be able to
have an idea of the distance to the points, depending on where the starting
position is.


-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by raindropsfromsky** [comment]
yes, but these distances are "as the crow flies", measured from the center of screen, which may be any random point on earth. On the other hand, the route is usually much longer. 

Thus all the vectors we see are like spokes of a wheel.
But the actual route is from point A to B to C...
Thus these distances (and even bearings) are useless for planning the journey.

The GPS has no role to play here. 
It is immaterial whether the device has knowledge of the actual position.

**Comment by Barrocas** [comment]
Yes, I know how it works, I understand what you mean, since if we pan the
map around, those distances will change according to our view on the map.

But if you place your center of screen on (or near) where you want to start
your route, then you have an idea of the distances for each waypoint.

Or if you are just planning, and have a way of marking your starting point,
then it would give a better result.




-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by raindropsfromsky** [comment]
oops- Due to connectivity issue, could not upload the illustration file.

In the mean time I saw your response. So I have changed my example a little to prove my point.
Here, we are planning a "Munich -> London -> Zurich" trip  (please see the attached file).

* At the start of the trip, the vectors look like black arrows (but remember that OsmAnd shows only the distances; and not the directions).
* But after the trip is set, the second leg of the journey is much larger and in different direction, as compared to the "Munich -> Zurich" vector.(see the red arrow) 

Thus the initial display of distances is never going to be reliable enough to serve any purpose.
 
[Waypoint distance.pdf](https://github.com/osmandapp/Osmand/files/45072/Waypoint.distance.pdf)

**Comment by sonora** [comment]
Distance display does actually make sense for users judging positions vs. known reference points, like golf players, backpackers, surveyors ...

**Comment by raindropsfromsky** [comment]
On the contrary, this tool would not make no sense to these users.

Instead, they can easily use the **Distance Measuring plugin**  which is free, and shows them both distance and bearing directly overlaid on the map.

It can even show a polyline connecting the different dots, or show each segment separately.

And it shows the result directly on the map. In contrast, the **Waypoints list** is a transitory screen, and in the next step it is replaced with the actual route.

In any case the route planning screens should show the distances as measured along the route, not "as the crepe flies", and with respect the the center of the display.

Please consider reopening this issue.
