### ISSUE TITLE
The coloring switch between hike vs. bike-routes doesn't work immediately

### ISSUE THREAD

**Issue by bane2** [osmandapp/OsmAnd#19649]
### Description

The coloring switch between hike vs. bike-routes doesn't work immediately if you change the view (from hike to bike or vice versa).

### Steps to reproduce

Open OSMand and choose hike view. Activate showing hiking routes. Switch to bike view (biking routes has to be activated before) -> coloring of routes doesn't work immediately.

### Actual result

You have to zoom out or in die get the correct coloring.

### Expected result

Immediately colring of the corresponding routes.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.7
Android version: 11
Device model: Samsung Galaxy A70

**Comment by Velomeloman** [comment]
Seems related to #19562
