### ISSUE TITLE
Move speedometer widget settings

### ISSUE THREAD

**Issue by Velomeloman** [osmandapp/OsmAnd#19647]
### Describe the idea (required)

Move speedometer widget settings at Configure screen menu from Other section to Widgets section. The placement of that settings is bit confusing now for some users.
![Screenshot_20240423_173351](https://github.com/osmandapp/OsmAnd/assets/109347561/9ade0703-7a45-4bdf-b53a-e5a9efbbcd9b)

### Tell us about the expected behaviour (required)

-

### Tell us about alternatives you've considered (required)

-

**Comment by dmpr0** [comment]
Speedometer is not part of the widget panels

**Comment by Velomeloman** [comment]
I suggest moving it not in the panels, but next to them. Is Speedometer widget? Or it's Other?
