### ISSUE TITLE
Proposal: Separate the add POI to route screen

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#1965]
This is in connection with the new proposed layout of "Route Editor".

I was looking for any possible hickups in that new design, and found this:
Currently the **Waypoints list** screen allows us to see POIs and favorites.
Then the selected points are added to the route.

Well, this approach needs a clean up too.

I remember that the core idea was to use this while we are already driving along a route.
In that case, this feature was supposed to show us the POIs that we need quickly, and without getting distracted from our driving.

For example, while driving, we get hungry, and look for a POI that provides food (restaurant, store, cafe, anything!)
But we also realize that we don't have cash, so we look for the nearest ATM along the way.
And all this must happen without our grappling with our phone.

Also, once we make our selection, the display must go away.
(Keeping this panel on would distract the driver.)

In short, this is the counterpart of another feature: "The next segment is blocked. Find me an alternate route!"
Both these features are needed while we are driving, and should be available when needed.

In other words, this dialog is not meant to be used when we are planning a route.
During this phase, we should be using the newly proposed "search and add" option.

Also, as we drive along a route, this feature should keep finding POIs of the selected type(s).
But once we select a particular POI, it also means OsmAnd should stop looking for more POIs.

With that logic, I propose the following changes in this feature:
1. Remove it from the "Route Editor", and present it directly on the main screen
2. It should be visible during navigation mode only.
3. User should be able to switch it on easily (provide a gesture/button during navigation mode)
4. An audio alert should tell the driver about the next approaching POI/favorite.
   e.g. "Next gas station 400 m ahead, on left."
5. If the user ignores it and passes it, OsmAnd should pick the next one along the route.
6. When the user makes up his mind to approach a particular POI, he would double-click anywhere on screen.
   Immediately OsmAnd should add that POI to the route, and recalculate the route.
   It should also toggle the feature off.

**Comment by sonora** [comment]
No immediate action planned for this, I guess.
