### ISSUE TITLE
Reconnecting AA: Navigation is stopped 

### ISSUE THREAD

**Issue by souvenir1981** [osmandapp/OsmAnd#19651]
### Description

HI
I'm using the osmand app (latest osmand+ pro version) with android auto.
the problem occurs when I set and navigate a track...every time I turn off the bike and Android Auto automatically turns off, when I turn it back on the track disappears.
in this way it is not possible to navigate....
this problem does not occur with google maps.
I also tried with another smartphone to no avail.
[Osmand android auto.zip](https://github.com/osmandapp/OsmAnd/files/15080230/Osmand.android.auto.zip)

I hope to be clear...I am at your disposal
I attach the video of the problem

### Steps to reproduce

Attached you will find a dedicated video of the problem

### Actual result

with android auto I can't use osmand as a navigator

### Expected result

I hope you fix it with an app update

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by DmitryAlexei** [comment]
Issue confirmed by @EugeneZmeuk 
- after reconnecting to AA after the engine was stopped, navigation is lost. The driver must enter the destination again.
- other apps (such as Google Maps) continue to provide navigation instructions.

**Comment by souvenir1981** [comment]
I tested it this weekend and it still freezes and the track disappears
