### ISSUE TITLE
Osmand bicycle navigation bug

### ISSUE THREAD

**Issue by JuergenMasch** [osmandapp/OsmAnd#19650]
### Description

I often found that when calculating a route for the bike with the option „shorter route“ the route was longer than with the option „balanced“.

### Steps to reproduce

I compared the result from three Samsung devices. All three devices are equipped with the latest version of Osmand+ and the latest offline maps. The shortest route for Hamburg, Leverkusenstieg 32 to Eppendorfer Weg 159. 

### Actual result

The shortest route for Hamburg, Leverkusenstieg 32 to Eppendorfer Weg 159 was

3,82 km (balanced 3,57 km) for the Tab S6 Lite, 
3.87 km (balanced 3,57 km) for the S20 FE and 
4,56 km (balanced 3,99 km) for the S23. 

### Expected result

For comparison: The walking route was calculated as 3,41 km (All 3 devices. This route is also suitable for bikes). 

### Your Environment (required)

OsmAnd Version: + 4.7.9
Android/iOS version: 13
Device model: Samsung Tab S6 Lite, S20 FE, S23
Crash-Logs: ?
```

**Comment by JuergenMasch** [comment]
I just discovered that the speed setting under Navigation–Settings – Vehicle Parameters has a big impact on the route. So I was able to almost reproduce your route for the shortest distance (5/14/17 km/h).
![Screenshot_20240424_191119_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/167891617/60ff3eec-abcb-4e07-97cc-4a0dbd8a7547)
![Screenshot_20240424_191138_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/167891617/0655186f-6894-44f8-8a9e-1faa50336fac)

**Comment by JuergenMasch** [comment]
I accidentally closed the issue yesterday. But now it's open again with my
new comments.

yuriiurshuliak ***@***.***> schrieb am Mi., 24. Apr. 2024,
15:52:

**Comment by vshcherb** [comment]
Looks like new bug is open

**Comment by JuergenMasch** [comment]
Exactly, and I think the same goes for the settings "balanced" and
"avoiding main roads".

vshcherb ***@***.***> schrieb am Mo., 13. Mai 2024, 17:09:
