### ISSUE TITLE
Additional turn on straight section of junction

### ISSUE THREAD

**Issue by fvanrenterghem** [osmandapp/OsmAnd#19666]
### Describe the routing engine used (required)

- [x ] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Describe your routing Profile (required)

Car

### Describe your start and end points (required)

https://osmand.net/map/?start=-32.035706,115.747528&end=-32.037567,115.754013&profile=car#17/-32.03666/115.74836

Routing results:

![tempFileForShare_20240425-213724](https://github.com/osmandapp/OsmAnd/assets/6618468/b91176a5-b797-463f-b32a-d6fe9238bab3)

### Describe the actual route (required)

https://www.openstreetmap.org/directions?engine=fossgis_valhalla_car&route=-32.03732%2C115.75090%3B-32.03662%2C115.75654 shows the route as calculated online. The ZLZK online routing engine from within OsmAnd also gives the correct route i.e. without the unneeded right turn in step 2.

### Describe the expected route (required)

The step to turn right and go 204 Tydeman Road is unneeded. In the graphical view, it is actually shown as a white arrow that goes straight.

### Describe what Maps you used (online or offline) (required)

- [X ] Offline maps offered within the OsmAnd app for download. 
- [ ] Online (tile / raster) maps 

Live updates last updated 2024-04-25.

### Your Environment (required)

```
OsmAnd Version: 4.6.14
Android/iOS version:
Device model:
```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced.  When setting up the navigation using the provided coordinates, the additional turn on the straight  section of the road is reflected.

OsmAnd~ 4.8.0#2184m, released: 2024-04-26

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/c9c173cb-0842-49c8-ac62-97ae517784ee"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/4df8157c-ca0d-4407-8b83-b92cf2449550"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
This issue is related to https://www.openstreetmap.org/way/319289853 ("|through;right|right"). Empty lane is not recognized as turn left and leads to one more turn announcement without hilighlighting turn slightly as a lane.

I think it's common issue with Australia turns for now, so I guess it's a duplicate with existing issue.
