### ISSUE TITLE
Track statistics in the My Places list are not updated after changes

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#19667]
### How to reproduce

* Import any track
* Go to **Menu** – **My places**, find it in the list
* Statistic on the second line show info after import
* Tap on track > **Edit**
* Add few new points, tap Save
* Get back to **My Places**, find the same track

### Actual result

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Before editing, my places</th>
        <th>After editing, context menu</th>
        <th>After editing, my places</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/8d780c7d-b35a-4530-8a2b-e845438bdb04"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/4df7d83a-517b-47fa-a878-d05306c30c2e"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/8d780c7d-b35a-4530-8a2b-e845438bdb04"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

<details>
    <summary>Video</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/56bc7376-ab6f-4bd4-a165-9a7cfdd416b5"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

* Statistic on the second line are not updated

### Expected result

* Statistic will be updated after changes

**Environment**
OsmAnd Version: 4.8.0#2177m 
Android: 15
Device model: Google Pixel 6A

**Comment by vshcherb** [comment]
Probably related to refactoring

**Comment by sonora** [comment]
Yes, let's please fix together with #19683, clearly connected.

**Comment by Chumva** [comment]
It is probably already fixed [here](https://github.com/osmandapp/OsmAnd/pull/19665)
