### ISSUE TITLE
Crash in Plan route

### ISSUE THREAD

**Issue by Velomeloman** [osmandapp/OsmAnd#19678]
### Description

Application crashes in Plan route mode

### Steps to reproduce

Plan route -> add first point

### Actual result

App crashes

### Expected result

App works

### Your Environment (required)

OsmAnd~ 4.8.0#2187m, дата выпуска: 2024-04-26

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.8.0#2186m, released: 2024-04-26 reproduced
[exception (6).log](https://github.com/osmandapp/OsmAnd/files/15135575/exception.6.log)

https://github.com/osmandapp/OsmAnd/assets/116079541/fa3cbb1d-30be-424b-8544-45dfc86e687c

**Comment by Nine-Tailed** [comment]
И в OsmAnd 4.7.11, дата выпуска: 2024-04-26

**Comment by Nine-Tailed** [comment]
On OsmAnd~ 4.8.0#2191m, Дата выпуска: 2024-04-27 the bug no longer reproduces.

**Comment by Chumva** [comment]
It should be fixed [here](https://github.com/osmandapp/OsmAnd/commit/8a3e5a24a1c108c1bf3403e99f90b55c08628f3e)

**Comment by Velomeloman** [comment]
OsmAnd~ 4.8.0#2191m, дата выпуска: 2024-04-27 fixed
