### ISSUE TITLE
OsmAnd ignores manoeuvre relation

### ISSUE THREAD

**Issue by spaanse** [osmandapp/OsmAnd#19679]
### Describe the routing engine used (required)

- [x] OsmAnd's in-app offline routing

### Describe your routing Profile (required)

bike

### Describe your start and end points (required)

from: 51.81671°N 5.86839°E
to: 51.81647°N 5.86619°E
https://www.openstreetmap.org/directions?engine=fossgis_valhalla_bicycle&route=51.81671%2C5.86839%3B51.81647%2C5.86619

### Describe the actual route (required)

OsmAnd shows the same route as all other routers integrated into openstreetmap.org
The step-by-step instructions are as follows:
1. Head Kwekerijweg
2. Turn right and go Houtlaan
3. You have arrived
With the given instructions (and not knowing the road names) I might turn onto Heyendaalseweg

### Describe the expected route (required)

I would expect either:
1. Head Kwekerijweg
2. Continue onto Houtlaan
3. You have arrived

or

1. Head Kwekerijweg
2. Turn left onto Heyendaalseweg
3. Turn right onto Houtlaan
4. You have arrived

It is understandable that the router does not see the transition onto the cyclepath as a turn, it is basically a straight-on.
This is because of the pencil-tip intersection for the Kwekerijweg as well as the pencil tip created because the cycle path seperates from the road. I have added a type=manoeuvre relation here which makes Valhalla and OSRM recognise this as a left turn (though they seem to ignore the direction value). 

### Describe what Maps you used (online or offline) (required)

- [x] Offline maps offered within the OsmAnd app for download. 
Netherlands Gelderland - Live 2024-04-27 10:15

### Your Environment (required)

```
OsmAnd Version: 4.7.10 - 2024-04-18
Android/iOS version:
Device model:
```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. If you build  navigation using the provided coordinates, an additional turn will appear. 

You can view the issue in action on the web version here: [link to web version](https://test.osmand.net/map/?start=51.816710,5.868390&end=51.816470,5.866190&profile=bicycle#18/51.81684/5.86650).

OsmAnd~ 4.8.0#2191m, released: 2024-04-27

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/fd9d123a-db37-4d13-901d-198b1736966d"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/abe36c1a-a2c8-4027-a28b-6eb4058969e4"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
I think based on current geometry https://test.osmand.net/map/?start=51.816710,5.868390&end=51.816470,5.866190&profile=bicycle#18/51.81684/5.86650 turn right is correct indication. It's anyway very confusing with roads moving to cycleway, so you will need to consult with the map
