### ISSUE TITLE
"Plan route" OsmAnd will be closed

### ISSUE THREAD

**Issue by APneunzehn74** [osmandapp/OsmAnd#19685]
### Description

OsmAnd will be terminated when setting the first point "Plan route"

### Steps to reproduce

Open "Plan route" no matter which profile, when you set the first point OsmAnd will close.

### Actual result

OsmAnd Crash 

### Expected result

Plan a rout

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:4.7.11
Android Version 13

**Comment by Rowin63** [comment]
Can confirm this.
After tapping "add" the app crashes (it "disappears" from the screen) but seems still to be running in the background. Tapping again the app window brings the app back and displays the Crashlog dialog. After "send" or "cancel" the app is running again. Now you can again start over with a new route and create that issue. 
The app never really "closes" when crashing.

**Comment by Nine-Tailed** [comment]
Fixed [here](https://github.com/osmandapp/OsmAnd/issues/19678)

**Comment by Rowin63** [comment]
> Fixed [here](https://github.com/osmandapp/OsmAnd/issues/19678)

Thanks, I didn't see it exists in the "closed" issues.
