### ISSUE TITLE
One specific road does not render, when OsmAnd Live update is enabled.

### ISSUE THREAD

**Issue by TLDuhamel** [osmandapp/OsmAnd#19687]
### Description

A [specific `highway=residential` road feature](https://www.openstreetmap.org/way/25059929) does not render on the map: 
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/2009756/897f5305-8086-4044-a3bf-61ec190b80e4"  width="300" height="auto"/> </th>
  </tr>
</table>

This does not appear to be due to any OpenStreetMap tagging, or any recent edits to the feature which might explain the rendering issue.

The issue has been isolated to be seen occuring **only when OsmAnd Live is enabled** (For New Zealand updates). Disabling OsmAnd Live results in the road showing as expected.

Issue was first raised on reddit r/OsmAnd here: https://www.reddit.com/r/OsmAnd/comments/1cez9jt/why_wont_this_road_render_in_osmand/ f

### Steps to reproduce

1. Enable OsmAnd Live download for New Zealand, downloading the latest update file.
2. Navigate to the top of Te Atatū Peninsula in Auckland, New Zealand (-36.82714, 174.64568)
3. Notice that Murray Road is not rendering.

### Actual result

Murray Road is not visibile
<tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/2009756/be6c513c-69d8-4bfd-adda-2e436f59ecb6"  width="300" height="auto"/> </th>
  </tr>
</table>

### Expected result

Murray Road should be shown like the other roads around it.
This screenshot is what is seen when OsmAnd Live is disabled.
<tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/2009756/b8f62035-27d1-491f-9e02-43a95d58069c"  width="300" height="auto"/> </th>
  </tr>
</table>

### Your Environment (required)

OsmAnd Version: **4.7.10**
Android/iOS version: **Android 13**
Device model: **Samsung Galaxy S20+ (SM-G986B/DS)**

**Comment by vshcherb** [comment]
Probably related to the bug recently fixed with OsmAnd live. Though it doesn't fix already happened issues

**Comment by TLDuhamel** [comment]
No longer experiencing an issue with this specific road
