### ISSUE TITLE
GPS widget caches outdated values

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#19681]
The GPS widget seems insensitive to when there is no GPS location update, instead keeps displaying formerly valid numbers.

To reproduce: Check the GPS widget, say it correctly displays something like 24/30. Now turn off the phone's Location service in Android's Location settings.. The GPS widget will continue to show the prior satellite counts indefinitely, misleading users and making situations harder to debug.

**Comment by sonora** [comment]
The fix has not changed it for my setup, still reproducible exactly as described above (Android 11).

**Comment by dmpr0** [comment]
# Review
- [ ] Todo is missed

**Comment by vshcherb** [comment]
Something was lost in translation ... We need to write again what exactly needs to be done and how it works. Probably this task needs to be reproduced first

**Comment by vshcherb** [comment]
As issue now doesn't seem critical moving to 4.8

**Comment by sonora** [comment]
After https://github.com/osmandapp/OsmAnd/commit/36d5266962abb7d49d8cddacbda3ee6e76008f87, this now looks ok to me, I would consider it fixed(?)
