### ISSUE TITLE
Wikivoyage latest issues with new Travel topics   

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#19686]
- [x] Context menu Wikipedia / Phone... (visible on Test.gpx)  - https://github.com/osmandapp/OsmAnd-Issues/issues/2360
- [x] Delete Default_wikivoyage (not needed anymore) - not clear why did we add it ? Answer needed.
- [x] Destinations Top article doesn't work and not selectable
- [x] Missing Translation Travel_topics
- [x] Online photos context menu (wikidata / category) - for waypoints in GPX (correct wikidata / category should be passed to Web)
- [x] Support transition between en: articles in hierarchy - uk:Вісбю
```
┌─lang─┬─title────────┬─is_part_of───────────────────┬─aggregated_part_of───
│ uk   │ Вісбю        │ en:Gotland                   │ en:Gotland,Йоталанд,Швеція,Скандинавія,Європа,en:Destinations                      
```

**Comment by Dima-1** [comment]
Context menu now contains all Wikivoyage tags.

<table style="width:100%">
  <tr>
    <th>Android</th>
    <th>iOS</th>
  </tr>
  <tr>
    <th><img src="https://github.com/osmandapp/OsmAnd/assets/31807095/9a619c01-8a81-45b7-80ff-35f35f764c48"  width="300" height="auto"/> </th>
    <th><img src="https://github.com/osmandapp/OsmAnd/assets/31807095/b5491edc-b5da-4942-85fe-495183ee3b5a"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
- [ ] From demo @Dima-1, @DmitryAlexei

**Comment by DmitryAlexei** [comment]
- [ ] change generation of wikivoyage obf files and (add or not delete destination from obf)
- [ ] check if the destinations articles are present (in the UI)

**Comment by Dima-1** [comment]
- https://github.com/osmandapp/OsmAnd/pull/20061
