### ISSUE TITLE
Map still rotatable when set to 'North is Up'

### ISSUE THREAD

**Issue by mtbspace** [osmandapp/OsmAnd#19680]
### Description

It's not 100% clear to me whether this is a bug or by design, but regardless, I should not be able to rotate the map when set to 'North is Up'.  If I'm sat at my desk, I'm unlikely to accidentally rotate the screen when zooming.  If I'm using my mobile device when I'm out and about, which is probably the most common use case, it's far too easy to accidentally rotate the map, and I find myself endlessly setting it back to 'North is Up'

### Steps to reproduce

When set to 'North is Up', attempt to zoom map using pinch to zoom while I am walking, or I am a passenger in a moving vehicle.

### Actual result

I accidentally zoom and rotate at the same time, unless I'm extremely careful.

### Expected result

Rotation should be blocked when set to 'north is up'.  If this is not intended behaviour, it needs a new mode 'Lock North is Up'

### Your Environment (required)

Android 13 on Xiaomi Poco F3 with touch screen

**Comment by Nine-Tailed** [comment]
In 4.7.10 menu - settings - profile- general settings -enable fixed north up

**Comment by MikeTango** [comment]
![signal-2024-04-29-124036](https://github.com/osmandapp/OsmAnd/assets/3368005/229e8230-bf87-434f-b889-07036c0bc86a)

If it is this, it does not keep the map from being accidentally rotated.
