### ISSUE TITLE
Too many "POI type" when no name

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1969]
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot_2015-11-26-19-40-10.png
Object has no name but have "ref"
```
emergency : emergency_access_point Saint John Ambulance Lat -38.45431 Lon 176.70253 id=1502689015  ref=Saint John Ambulance
```
I propose to do something with it. Three poi type name is too much.

**Comment by vshcherb** [comment]
Poi type should not be displayed in the title itself, I think it should be fixed. Only  name on 1st line and poi type is on 2nd line
