### ISSUE TITLE
Osmand+ 4.7.10 crashes repeatedly when trying to start navigation

### ISSUE THREAD

**Issue by speleoluc** [osmandapp/OsmAnd#19690]
### Description

After solving issue #19317 caused by replacing the SD card in my cellphone, I can't get Osmand+ to navigate a route as it crashes repeatedly. The furthest I got was to find a route; hitting Start then crashed the app. Further retrials crashed even before that, sometimes as early as hitting the Navigate button. The alert I get offers to stop the app, but it seems to only close the window, and I have to go to Preferences to actually stop Osmand+ to retry, without any better result. Osmand+ has Location and Storage permissions.

Sadly, since the latest versions, Osmand+ has become unusable, at best unreliable :(

### Steps to reproduce

Open the app, hit Location, ask for a bicycle route and hit Start.

### Actual result

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/57163823/50a60697-bb16-43d9-a1e4-a53082591c09"  width="300" height="auto"/> </th>
  </tr>
</table>

* App crashes.

### Expected result

* Proper navigation.

### Your Environment (required)

OsmAnd Version: 4.7.10
Android:  8.0.0
Device model: Samsung A5-2017 1Gb free memory
Crash-Logs: None

**Comment by yuriiurshuliak** [comment]
Could you, please send us a crash log file? When you notice that the app crash  →  go to the Menu → Help → Send crash log file
It would also be helpful if you could send a video showing step by step what leads to the crash.

**Comment by speleoluc** [comment]
Sending the attached crash log file, I get

[exception.log](https://github.com/osmandapp/OsmAnd/files/15151709/exception.log)

Device : a5y17ltecan
Brand : samsung
Manufacturer : samsung
Model : SM-A520W
Product : a5y17ltevl
Build : R16NW.A520WVLSECTJ1
Version : 8.0.0
App Version : OsmAnd+
Apk Version : 4.7.10 4710

I uploaded at
https://auriga.top/tmp/P4290001.MOV
a one-minute video that shows a rapid crash after first stopping Osmand+ to start from scratch.

**Comment by vshcherb** [comment]
Please test 4.7.13 or higher once it's available
