### ISSUE TITLE
route transparency not applied with version 4.7.12

### ISSUE THREAD

**Issue by cricri-du-lauragais** [osmandapp/OsmAnd#19702]
### Description

when creating a route, the transparency coming from the style or defined in the profile options is not applied, the color remains opaque

### Steps to reproduce

use the default osmand style (or any other) and select a destination to obtain an itinerary, and watch the color of the guidance,
go to guidance options to change the color, the preview shows the color transparent, but after validation on the map the color remains opaque

### Actual result

guidance color remains opaque

### Expected result

guidance color is transparent

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.7.12
Android/iOS version: 14
Device model: samsung galaxy A33
Crash-Logs: ? no log
```

**Comment by cricri-du-lauragais** [comment]
hello, after further tests this problem occurs only with openGL renderer.

**Comment by Corwin-Kh** [comment]
![image](https://github.com/osmandapp/OsmAnd/assets/29124437/afbeefb5-55d2-4cc2-8b36-ffae99988670)
Not reproduced on current version. Could be fixed by recent changes
