### ISSUE TITLE
Routing prblem: OsmAnd fails to use the nearest link between two halves of a highway

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#1970]
When a highway has two roadways (two parallel roads carrying traffic in opposite directions), it has links that connect these two halves. (e.g. an intersection with another road, or a median break that allows U-turn).

OsmAnd is supposed to use these links to make a U-turn when (a) our target is on the other side of the road, and (b) there is no other way to reach the destination, other than go ahead and turn back.

But often OsmAnd misses the nearest link, and goes ahead by a long distance; and then makes a U-turn; often using other roads.

Here are some examples, where OsmAnd cannot cross the road:
12.987,77.648
12.981,77.637
12.983,77.637
12.953, 77.591

**Comment by raindropsfromsky** [comment]
A simple test to verify this defect is to pick a dual roadway, and pick the From and To points on the opposite halves of that road.

Ideally OsmAnd should make a U-turn at the very next junction, but this does not happen.

**Comment by sonora** [comment]
Your positions may be imprecise (you may have to specify more digits), but I find no indication in OSM for any legal u-turns near those locations?

**Comment by raindropsfromsky** [comment]
Yes, but that's how the OsmAnd shows the coordinates in its dialog. 
(I actually copied all digits from old screenshots.)

But this happens consistently: Take any dual roadway road, and pick any two points on the opposite halves. Ideally OsmAnd should draw the route from the start point along the flow of traffic, take a U-turn at the nearest intersection (or median break), and return to the destination. But this does not happen. There are no turn restrictions on the junction.

**Comment by raindropsfromsky** [comment]
Here is a fresh example:

From-
http://osmand.net/go?lat=12.950495&lon=77.699646&z=19

To-
http://osmand.net/go?lat=12.950593&lon=77.6998&z=19

...does not take a U-turn at the median break located at-
http://osmand.net/go?lat=12.950198&lon=77.69968&z=19
because the link is "yellow" (secondary road)

...but goes farther on the ORR, till-
http://osmand.net/go?lat=12.947793&lon=77.699135&z=19
because this link is "pink"
![u-link problem](https://cloud.githubusercontent.com/assets/9047168/12412795/b4fe5d3a-beaf-11e5-9f3f-3687556fabaf.png)
 (primary road).

**Comment by raindropsfromsky** [comment]
Yet another example:
From
http://osmand.net/go?lat=12.970592&lon=77.617836&z=21

To
http://osmand.net/go?lat=12.970533&lon=77.6179&z=21

**Comment by hakuchi** [comment]
For me it looks as if Osmand have difficulty to find the shortest route in the middle of the long one, and so Osmand use the small service road(2-3m) for navigating.

Is on all points reported from you a U-turn allowed?
Are this link not only for reaching the residential in the north?
https://www.openstreetmap.org/way/296167495
https://www.openstreetmap.org/way/296167496

**Comment by raindropsfromsky** [comment]
No there are no such turn restriction.
I have checked that already, using ID Editor.

BTW if my understanding is correct, OSM does not define a "U-turn" at all.
It is always two right-turns (in India, where we drive on the left).

Thus the first right-turn brings us to the link, and the second right-turn brings us to the other way (which may be one-way or bi-directional). 

This dual-maneuver can be used to make a U-turn on a dual carriage highway; or to exit from a road to a service road that runs parallel to the main road.

**Comment by vshcherb** [comment]
Routing engine bug.
Calculated:
    start_lat="12.993591879654103" start_lon="77.66232585906982" target_lat="12.993821870331674" target_lon="77.66195034980774" loadedTiles = "20" visitedSegments = "14" complete_distance = "2674.3562" complete_time = "165.10577" routing_time = "139.56467"  >

Expected:
    start_lat="12.993591879654103" start_lon="77.66232585906982" target_lat="12.993821870331674" target_lon="77.66195034980774" loadedTiles = "22" visitedSegments = "23" complete_distance = "1216.8386" complete_time = "82.86804" routing_time = "83.13248"  >

**Comment by raindropsfromsky** [comment]
Finally a break-through? If so, it's exciting!

BTW even the addition of spurious detours (#2354) may be related to this.

**Comment by vshcherb** [comment]
Finally the issue has been fixed.
@xmd5a2 can we have a test for https://github.com/osmandapp/Osmand/issues/1970#issuecomment-209651749 (this comment), formerly it used a wrong junction to make a uturn http://www.openstreetmap.org/export#map=19/12.98881/77.65147  instead of http://www.openstreetmap.org/export#map=19/12.99161/77.65773 (please put this intersection http://www.openstreetmap.org/export#map=19/12.99021/77.65502 also in the test)

**Comment by raindropsfromsky** [comment]
I repeated all the tests described earlier. In general, those problems are resolved. But I noticed another problem:










![screenshot_20160814-200349](https://cloud.githubusercontent.com/assets/9047168/17649974/7752941c-625e-11e6-9320-9704ce09bee8.png)

Compare the two screenshots: The **shortest way** option actually yields a longer route!

![screenshot_20160814-200410](https://cloud.githubusercontent.com/assets/9047168/17649975/77648816-625e-11e6-9398-f4a5a47182ff.png)

**Comment by raindropsfromsky** [comment]
Please re-open the issue
