### ISSUE TITLE
Blinking of the current track while recording

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#19705]
### Description

When recording a track it blinks and besides that osmand slows down and does not react adequately to the presses on the screen.
Video in telegram chat:
https://t.me/ruosmand/150744

### Steps to reproduce

Start recording the track. After a while, the osmand will start to slow down.

### Actual result

Now it’s impossible to use Osmand when recording a track.  It’s easier to run the free version in parallel and view the map in it.

### Expected result

The track should not blink, and viewing the map should not slow down.

### Your Environment (required)

```
OsmAnd Version: OsmAnd~ 4.8.0#2199m, Дата выпуска: 2024-04-28
Android/iOS version: 13
Device model: pocof3
Crash-Logs: ?
```

**Comment by zipav** [comment]
OsmAnd Nightly 4.8.0#2216m, released: 2024-04-30

No longer reproduced.

https://github.com/osmandapp/OsmAnd/assets/123936521/654eca15-7ed7-4c84-85b0-897613318d63

**Comment by yuriiurshuliak** [comment]
The bug could not be reproduced. To reproduce the issue, I configured the track appearance to match yours, downloaded and enabled Contour lines, Hillshade, and the Terrain map (3D). And then turned on Track recording to see if the track would blink during recording.

As a result, the current track did not Blinking during recording.

OsmAnd~ 4.8.0#2700m, released: 2024-07-08

https://github.com/osmandapp/OsmAnd/assets/127092082/c9208eff-3dff-49fb-ada5-cc8d05da668f

**Comment by Nine-Tailed** [comment]
@yuriiurshuliak, you can test it by recording a track for a long time, I see this bug many times.

**Comment by yuriiurshuliak** [comment]
I can't reproduce the issue on my end. I tried recording a longer track of 5 kilometers over 22 hours but did not encounter the blinking result you mentioned.

OsmAnd~ 4.9.0#2872m, released: 2024-07-31

https://github.com/user-attachments/assets/0e2748e8-5abe-4fc7-8767-0de4d2888425

**Comment by Nine-Tailed** [comment]
Can you check with these settings? I have a suspicion that maybe this is due to the number of points in the track, I have a minimum time of 0 s, although I tried 1 s.

![Screenshot_2024-08-02-15-25-30-410_net.osmand.plus.jpg](https://github.com/user-attachments/assets/c54fe022-d483-4a8b-af23-d891fb9334c4)
