### ISSUE TITLE
Osmand in Car profile routes through a bicycle path

### ISSUE THREAD

**Issue by Guylby** [osmandapp/OsmAnd#19719]
### Describe the routing engine used (required)

- [X] OsmAnd's in-app offline routing
- [X] OsmAnd online test Map
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Describe your routing Profile (required)

Standard car profile

### Describe your start and end points (required)

Here is the route on the Osmand test map server:
Start: 47.275244,-0.079356
End point: 47.263714,-0.093738
https://test.osmand.net/map/?start=47.275244,-0.079356&end=47.263714,-0.093738&profile=car#16/47.2702/-0.0872

Tested on both 4.7.12 and Osmand Test Map server, both route through the bicycle path.
I've tested the same route on OSRM with a car profile and the routing only takes normal roads.

### Describe the actual route (required)

Osmand use the bicycle path

### Describe the expected route (required)

Osmand doesn't use the bicycle path

### Describe what Maps you used (online or offline) (required)

- [X] Offline maps offered within the OsmAnd app for download. 
- [ ] Online (tile / raster) maps 

### Your Environment (required)

```
OsmAnd Version: 4.7.12
Android/iOS version: 13
Device model: Sony Xperia 10 III
```

**Comment by scaidermern** [comment]
[way 255322799](https://www.openstreetmap.org/way/255322799) has `motor_vehicle=permissive` set, this looks wrong?

**Comment by pebogufi** [comment]
@scaidermern you have been faster than i, but only 1 minute 😃

**Comment by vshcherb** [comment]
Probablyy mapping should be fixed cause this looks ok - https://test.osmand.net/map/?start=47.277104,-0.076153&end=47.266344,-0.093899&profile=car#15/47.2650/-0.0959. and mapping is the king anyway
