### ISSUE TITLE
Feature request: Provide fuzzy search

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#1971]
Often we do not know the precise name of a place or a road. If we enter even one letter wrongly, the search fails.

Secondly, several European languages have accent marks, and so if we search using plain English characters, again the search fails.

Thirdly, in the rest of the world, names are transliterated into English and entered in OSM. This introduces a great variety in the spelling of the same name. 

For example, take the real life examples of  "Sarjapura" and "Sarjapur";  "Maruthi" and "Maruti".

This forces us to search repeatedly, using different combinations of letters and spellings as trial and error, but with no guarantee of success.

Instead, OsmAnd should allow us to use fuzzy search, to find names that nearly match (but not exactly).

Also provide a slider to control the degree of fuzziness.

**Comment by sonora** [comment]
No action planned for this, I guess(?)

**Comment by johnwhelan** [comment]
My email is getting swamped with emails from this list.

I do not seem to be able to unsubscribe.

Can someone unsubscribe me please.

Thanks John
