### ISSUE TITLE
Reset average speed (on long press widget)

### ISSUE THREAD

**Issue by rysson** [osmandapp/OsmAnd#19713]
### Describe the idea (required)

Very small change – I propose reset the current value in the average speed widget on long press.
After reset average speed should be calculated from the beginning (like on the app start).

I could be useful for short time measurements, especially for average speed enforcement camera (until #13430).

### Tell us about the expected behaviour (required)

On long press the average speed widget the average speed should be reset and should be counted from beginning.

### Tell us about alternatives you've considered (required)

Current workaround is kill OsmAnd and start the app again. 
It's harder if OsmAnd is running on Head Unit.

**Comment by shurasmiling** [comment]
- https://osmand.net/docs/user/widgets/info-widgets#average-speed
- https://osmand.net/docs/user/widgets/configure-screen#panel-widgets-settings
