### ISSUE TITLE
trip recording - the smart way (like Garmin does)

### ISSUE THREAD

**Issue by nosorozec** [osmandapp/OsmAnd#19718]
### Describe the idea (required)

Before OsmAnd I used Garmin devices to track my adventures. They use quite smart system for points recording - if you are moving the same direction (straight line) they record less information but when you start turning there is a lot more points in the log. See below image for visualisation:

<img width="821" alt="Screenshot 2024-04-30 at 19 04 48" src="https://github.com/osmandapp/OsmAnd/assets/1448681/8583c72c-491e-450e-b737-9f997fee0220">

Can we have something like this in OsmAnd?

### Tell us about the expected behaviour (required)

Recording plugin automatically saves the GPX track log based on type of movement. Going in a straight line - less information logged, start turning - more information.

### Tell us about alternatives you've considered (required)

No clue, tried varied setting in the recording plugin - but cannot replicate the garmin behaviour.

**Comment by albansuser** [comment]
"if you are moving the same direction (straight line) they record less information but when you start turning there is a lot more points in the log."

Am curious as to the practical advantages of such a feature?

Thanks

**Comment by pebogufi** [comment]
@albansuser 
Have a look at
https://en.m.wikipedia.org/wiki/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm

**Comment by sonora** [comment]
We must be aware that many such (often post-processing) algotithms are usually targeted at fitting the geometric shape of a track with fewer points than their raw data has as e.g. recorded at a fixed tome interval.

But this also removes other information(!), which may not be desired, e.g. time, speed, altitude, cadence etc.data, which was contained in points the geo- simplification removes or manipulates.

So what kind of track sinplification makes sense for you depends on your actual purpose and use case.

**Comment by Sonwon1** [comment]
> We must be aware that many such (often post-processing) algotithms are usually targeted at fitting the geometric shape of a track with fewer points than their raw data has as e.g. recorded at a fixed tome interval.
> 
> But this also removes other information(!), which may not be desired, e.g. time, speed, altitude, cadence etc.data, which was contained in points the geo- simplification removes or manipulates.
> 
> So what kind of track sinplification makes sense for you depends on your actual purpose and use case.

It could be an option letting the user decide which is more useful for their usage.

**Comment by sonora** [comment]
Exacttly.Just saying that "the smart way" is not necessarily "smart" for all use cases.

And perhaps optimizations like this should even be a post-processing option you can apply to a track once it's been saved, there may be little benefit enforcing a,decision before recording.

**Comment by albansuser** [comment]
> Exacttly. Just saying that "the smart way" is not necessarily "smart" for all use cases.
> 
> And perhaps optimizations like this should even be a post-processing option you can apply to a track once it's been saved, there may be little benefit enforcing a decision before recording.

I agree. No sense in unnecessarily increasing the processor load while recording, especially if external sensors are being used. Then there's also data loss.

I can't think of any benefits of such "optimization".
