### ISSUE TITLE
Issues with Olympiiskaya subway station

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#19715]
## Description 
Fix issues related to visibility of public transport stops.

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/1042025/e962adcc-661c-4294-8515-cbdb770a643c"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/1042025/3ad95686-c387-4a63-989d-e153d5911033"  width="300" height="auto"/> </td>
    <td> <img src="https://github.com/osmandapp/OsmAnd/assets/1042025/b1474569-8bb9-46f7-95db-147b451b26d7"   width="300" height="auto"/></td>

  </tr>
</table>   

* Coordinates `50.43214, 30.51630`

- [ ] Too many same titles Olympiiskaya - should be only one visible ! Idea: Probably apply mechanism with same title in radius (@xmd5a2 )- https://github.com/osmandapp/OsmAnd-core-legacy/blob/1d39a1a0fde5b25afbfcf75010ac2a80ef714fb5/native/src/textdraw.cpp#L547C20-L547C50 (debugText..SameName). Compare not final name ```text == text ``` but compare ```baseText == baseText``` if not empty (where baseText doesn't contain nameTag2)
- [x] **2 Issues with bus stop** : No nearby transport in 150m (UI issue)
- [ ] **2 Issues with bus stop** : No transport at bus stop (data issue)

- - - 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/7796a880-f280-41f8-bddb-ee44ea153808"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/1042025/caef3812-b947-48db-a72d-da18ebc6ff65"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x] Olympiiskaya (3) - has different icons (test with June maps / Kyiv)

**Comment by Dima-1** [comment]
- https://github.com/osmandapp/OsmAnd/pull/19797
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/31807095/659019c2-21f5-490d-a896-d23722dbc967"  width="300" height="auto"/> </td>

  </tr>
</table>

**Comment by xmd5a2** [comment]
Subway entrances icons in Kyiv will be fixed in june maps.
Regarding "Too many same titles Olympiiskaya": where is no mechanism in rendering styles to suppress identical names. Same thing was done for place names (village, city etc.) by modifying rendering engines.

**Comment by Andrewschenko** [comment]
Symbols with similar content is hidden now. However, in case they all have equal priority, which of them should be shown is unpredictable. Such situation might need further examination.

**Comment by xmd5a2** [comment]
| |
|--------|
|![Screenshot_2024-05-24_11-28-58](https://github.com/osmandapp/OsmAnd/assets/5829014/7d656f09-3773-4559-a177-1b88c1d874aa)  |
![Screenshot_2024-05-24_11-29-13](https://github.com/osmandapp/OsmAnd/assets/5829014/314a9368-547c-46cb-a344-1b220b2b89a2)  |
 ![Screenshot_2024-05-24_11-29-28](https://github.com/osmandapp/OsmAnd/assets/5829014/13f3e37e-ad24-4e27-8fa4-4da471989286)  |
| ![Screenshot_2024-05-24_11-29-52](https://github.com/osmandapp/OsmAnd/assets/5829014/8ccaffda-6d00-481a-9bf8-9967dfffd2bc)  |
 ![Screenshot_2024-05-24_11-30-10](https://github.com/osmandapp/OsmAnd/assets/5829014/282920df-2218-4faf-9bec-d980322c01e4)  |  |
