### ISSUE TITLE
Navigation by Track needs to be Auto-tested & Fixed

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#19725]
**To Test**
Based on testing only 2 out of 8 scenarios work. The easiest way to test is to draw a route that goes next to my location (50-100m) and try all combinations of 3 options for navigation and simuations:
1. Reverse / non-reverse point
2. Navigate to start point / closest point
3. Build route / straight line.
4. + option - Attach to roads (only if track is not OsmAnd created)

**4.8** - UI tests for all 8 cases are needed

_Originally posted by @vshcherb in https://github.com/osmandapp/OsmAnd/issues/19132#issuecomment-2080752535_

**Comment by dmpr0** [comment]
<table style="width:100%">
  <tr>
    <th colspan=2>Attached to the road track</th>
  </tr>
  <tr>
    <th>Track direction</th>
    <th>Reverse direction</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/1d80e6df-6ac0-4f2d-92d1-cef6640c6f45"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/a1a5664e-a0bd-4bd7-87c5-8ff80ce5209c"  width="300" height="auto"/> </td>
  </tr>
</table>
