### ISSUE TITLE
In search by name mode, OsmAnd ignores the distance criteria; cannot set it manually

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#1973]
When OsmAnd is in "Search by name" mode, it ignores the distance limit, and finds matching POIs from much longer distances. 

This is undesirable, because we are looking for a *local* POI; not a namesake POI from a neighboring city, state or country!

Desired: OsmAnd must respect the distance limit.

Also, if we edit/change the search string, OsmAnd does not reset the search distance. For example, suppose that I was searching for *string_1*, and have expanded the search range to <500 km. Now if I change the search string to *string_2*, OsmAnd will search for this new string, but it will not reset the search distance to <1 km: It will launch this new search in <500 km area directly.

Thirdly, we cannot manually set the search distance. We should have this control as a pull-down list.

**Comment by vshcherb** [comment]
I don't see an issue here, you can select what is the closest and it is sorted by distance.
