### ISSUE TITLE
Double sets of contour lines and depth contour lines

### ISSUE THREAD

**Issue by Thunichgud** [osmandapp/OsmAnd#19736]
### Description

When activating contour lines at mountain "Zugspitze" in Germany (47.42069 N, 10.98605 E) all contour lines are shown in a double set of different contour lines. This occurs all along the border of Germany and Austria. 
When activating depth contour lines in the Atlantic ocean western of Scottland (e.g. 57.45795 N, 11.05292 W) from zoomlevel 8 and up or in the baltic sea northern of Rostock (e.g 54.24691 N, 12.10356) from zoomlevel 13 and up the depth contour lines are shown in a double different set. In the Atlantic this bug occurs also in front of the french and the spanish coast. It seems that the complete maps have double sets of depth contour lines.
It is not a mapping problem, it is a problem of creating the OSMand maps.

### Steps to reproduce

Look at the coordinates.

### Actual result

2 various sets of contour lines on the same areas.

### Expected result

Single sets of contour lines.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: various versions
Android/iOS version: various OS-versions
Device model: various models
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
Please share your profile settings with us.  You can do this by going to Menu → Settings → Export and selecting the data you wish to export.

**Comment by Guylby** [comment]
I actually had the same exact bug, double coutour lines on all the offline maps I had downloaded.

I found a fix that worked for me:
In the topography maps, I had both downloaded and enabled France (Contour lines) and France (Terrain Map (3D)). 
I disabled one after the other, restarted the app and got only one set of contour lines.

It seemed as if Osmand generated contour lines from both files. 

But I can't reproduce the issue anymore, even with both files downloaded and activated.

**Comment by NielsBem** [comment]
Hi, I have the same problem here. Map: Italy, Abruzzo region, offline vector maps, downloaded the contour lines as well, no overlay or underlay maps, just simple map with co tours on. I deleted the Terrain Map 3D, as suggested in post above, but still double contour lines. 
![Screenshot_20241124-171810](https://github.com/user-attachments/assets/2eb7d899-314d-45fe-91ca-0eb6c51aa462)
Any insights?

**Comment by yuriiurshuliak** [comment]
Try removing all maps, including contour lines, and redownloading them. Additionally, clear the app cache to ensure a fresh start.

**Comment by leongma** [comment]
@yuriiurshuliak: thank you for the hack. It removed the bug. 

Notice that just removing the contour lines file work for me (no need to remove and reload that file or map files). I do not know whether it caused the bug, but contour lines files for both the whole country (France) and the region (Auvergne Rhône Alpes)  were on my device. I removed the regional file while keeping the national one
