### ISSUE TITLE
MyPlaces>Tracks>Show on map removes all previously visible tracks

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#19749]
I assume the following is not intended behavior:

- Have some tracks displayed on the map
- Now enter MyPlaces>Tracks, long tap on a track to enter the screen's selection mode.
- Tap the 3 dots menu and select 'Show on map' to view the selected track on the map.

- [ ] As a result, the track is marked as visible on map now, but all previously visible tracks are removed from the map!

- [ ] Side finding: After selecting 'Show on map' the app remains in the track list screen. It would lilkely be preferable to show the map after such action, centering in on the one or several tracks selected for the 'Show on map' operation.

**Comment by sonora** [comment]
PS: The 3 bullet points in post 1 above reset the screen's sorting order to 'Last modified' and are hence yet another way to reproduce https://github.com/osmandapp/OsmAnd/issues/19333.

**Comment by Rowin63** [comment]
> * [ ]  As a result, the track is marked as visible on map now, but all previously visible tracks are removed from the map!

This problem has been previously discussed in another issue, but I don't find it anymore. 

But this here seems to be similar in parts #18861. Isn't it?

**Comment by zipav** [comment]
OsmAnd Nightly 4.8.0#2325m, released: 2024-05-17

Reproduced on the latest OsmAnd Nightly build. 

https://github.com/osmandapp/OsmAnd/assets/123936521/e885af0c-7134-48cc-b13f-f4d0157b130a

**Comment by sonora** [comment]
- [x] Fixed by https://github.com/osmandapp/OsmAnd/commit/6fa232e78e07b0b2ea2114cc3d7a1aa702eb7206.
- [ ] Side finding carried over to https://github.com/osmandapp/OsmAnd/issues/19893
