### ISSUE TITLE
4.7.13 on Android not rendering a map

### ISSUE THREAD

**Issue by myfta** [osmandapp/OsmAnd#19746]
### Description

I have been using OSMand+ for some time without issue. Now even the offline map fails to be displayed at start up. 

### Steps to reproduce

Start OSMand+

### Actual result

One tile is typically shown around the current location. A variety of issues occur. The remainder of the  screen is blank (white). If you try and move the map the whole screen goes black. It sometimes returns but often the app crashes and asks to close or wait.

### Expected result

Map should be displayed and enable navigation.

### Your Environment (required)

```
OsmAnd Version: 4.7.13
Android: 11
Device model: Moto G10
Crash-Logs: Already emailed to crash@osmand.net
```

**Comment by scaidermern** [comment]
Another user on Telegram reported problem that is somewhat similar. After upgrading to 4.7.x their OsmAnd app got really slow while panning the map until crashing. Redownloading all maps solved the problem (probably).

**Comment by vshcherb** [comment]
Probably related due to reindexing large number of tracks after update

**Comment by myfta** [comment]
Do we know why the update affects existing tracks? I have re-downloaded the previously installed maps and it does appear to be better.

**Comment by vshcherb** [comment]
Reindexing of all tracks was done by mistake (will be corrected in release 4.7.14)

**Comment by yuriiurshuliak** [comment]
Could you please confirm whether the issue you encountered still exists in the latest version of the app?

**Comment by myfta** [comment]
Cleared for me now.

Thanks.
