### ISSUE TITLE
Feature request: In case of stacked roads, allow user to define the actual current location.

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#1974]
Often the GPS fix is not accurate. As a result, OsmAnd shows the blue dot in wrong place. 

This inaccuracy creates serious problems when we are driving in closely placed roads. For example, Bangalore has many roads where there is the main road, flanked by a service road; and a stilt (elevated) road overhead. All three roads run in parallel, almost overlapping. But each road has a different set of junctions with the other roads.

In such situations, OsmAnd often shows the current position on the wrong road, leading to wrong directions ahead. Worse, it suddenly corrects itself, and snaps to a different road. The directions again change abruptly. This makes driving extremely unpredictable and dangerous.

**Desired:** Allow the user to long-press on the blue circle/triangle (which shows the current location), and trigger a context menu, which tells OsmAnd which road we are on. After that, it should stay snapped to that road, and not snap to a different road.

**Comment by sonora** [comment]
Frankly,  think getting a better piece of GPS hardware is the only useful solution to this issue ... :-)

I test OsmAnd on dozens of different devices, and the difference between many of them is outrageous. It is unbelievable how badly some chipsets and their drivers perform. Many times, cheaper devices with plastic covers do a much better job than high-end devices with metal covers or metal coatings.  :-)

Regarding your suggestion: I think this would be tail-wagging the dog, really ... your device should tell you where you are, not the other way round ... :)  I simply cannot picture myself driving and telling my device where I am after each turn ... :-)

**Comment by raindropsfromsky** [comment]
No my latest one is OnePlus 2, which has Snapdragon 810, which should be one of the best in GPS in the business. And the phone does have a plastic back and its metallic body itself is turned into GPS antenna (essentially same design as iPhone). This combination of chip and body design is the best possible.

But when the roads are stacked, even a most sophisticated device would not work any better. 

Thus it would be best to manually resolve the misreading. And this would be needed only once, as the "snap to road" feature should prevent straying to the other roads.

I will send some photos to show how the roads are stacked in Bangalore (and even more to come, as traffic situation worsens). In fact, we will soon have even Metro Rail sharing the vertical space over the major roads.

**Comment by raindropsfromsky** [comment]
Here is a typical situation in Bangalore: Each roadway of the stilt road is a 2-lane road directly stacked over a 4-lane road below.
   
http://s153.photobucket.com/user/grv_2007/media/gps/ENIMAGE1323915369777.jpg.html

When we are using the central two lanes, vehicles on both roads would get identical satellite signal. But if we change lanes and come to the outer lanes of the lower road, OsmAnd suddenly snaps us to that road.

**Comment by sonora** [comment]
Narayan, ok, understood!  MA-GPS: "Manually Assisted GPS"  :-)

But I still cannot picture how you envision it: You somehow, potentially while driving, tap on a road on the map, select something like "Snap to this one", and then what? You repeat that after each turn?

**Comment by raindropsfromsky** [comment]
Ah! This is the best part: Once OsmAnd gets that INITIAL offset, and then snaps to the correct road, it would calculate the further route based on that. As we move along the road, it will tend to get ambiguous signal from the satellite, but the "snap to road" feature will keep the location on the desired road. If the error becomes too large, OsmAnd will recalculate the route, and try to a different road once again.  We may correct that once again, but only if needed.

BTW there is yet another situation where this can happen: When inexperienced mapper(s) trace the satellite imagery without correcting its offset error. In that case, the GPS actually shows the location correctly, but the faulty map shows it at wrong place. Then OsmAnd tries to find a way back to the correct route. In this situation too, a little cheating carries the day!

Note that in both cases, the corrective offset is only temporary (one-time application).

**Comment by raindropsfromsky** [comment]
Another thought: When the GPS fix has a large circle of uncertainty (=when the light-blue circle is very large), our actual position could be **anywhere** in that circle, right? 

So if that circle falls on two closely spaced (or vertically stacked) roads, there is a good chance that we are NOT on the road shown by the GPS. 

This is even more likely in places like Bangalore, where it is cloudy almost through the year; or where there are trees.

So the "MA-GPS" should be provided to cater to such cases.

**Comment by sonora** [comment]
I may be wrong, but you will have the same uncertainty after EACH turn,
right? Each turn may have ambiguous roads (parallel again, but at say 90
degrees vs the prior calibration), so you are assuming the user took the
correct road to turn onto, which may or may not be correct - So this does
not help without constant re-calibration?

**Comment by raindropsfromsky** [comment]
No, because not all roads are stacked. Similarly, not all areas would have
the mappers errors.

So this is required in certain areas, once.

**Comment by raindropsfromsky** [comment]
Hi Hardy and Victor,

I thought of an argument in favor of this feature. It is so simple that I
am surprised why no one thought about it on the first place!

Here goes:

Just turn off the "snap to road" feature, and observe the actual GPS
location. Is it anywhere near the road?

So actually OsmAnd is constantly bringing it back to the road.

Note that OsmAnd can do this ONLY IF  a route is planned, not otherwise!
Why? Because it ASSUMES that we are going along that road only. That is why
it is able to fake the position all the while.

And there lies the trouble: in case of closely spaced roads, it may make a
mistake. For example, apart from vertically staked roads, the same ORR has
a 4 lane road flanked by a 2 lane service lane. Both are separated by a 1m
wide rain drain. How can GPS tell which road we are on?

And that is why we should be able to manually correct the position.

**Comment by raindropsfromsky** [comment]
I also suspect that the "snap to road" algorithm is promiscuous when it
finds multiple roads that run parallel towards the destination. Then it
selects any one of those roads.

This weakness also needs a review.

**Comment by raindropsfromsky** [comment]
The post has become too long, and the arguments are scattered.
I am summarizing the issue below, so there is no need to go through the entire post.
****************************************************************************************************

The GPS location is shown with a large light-blue circle, which is several meters in diameter. 

Practically, you could be actually **anywhere** in the area marked by the circle, but OsmAnd **assumes** that your current position is at its center (marked by the blue dot/arrow).

Further, OsmAnd's "snap to road" feature may snap your current location to the nearest road, which introduces an additional error.

And there lies the problem: You may be actually located on the wrong road, compared to what OsmAnd assumes!
 - On a major road, you may be on the other side of the divider . 
 - On a major road, you may be on the service road instead of the main road.
 - When an elevated road runs over another road, you may be on the road below.

If OsmAnd assumes you to be on the wrong road, it will provide completely wrong directions.

The only solution is to tell OsmAnd where the actual location is. From that point onward, the "**Snap to Road**" function can take over and adhere to the correct road.

The actual implementation of this feature is simple: Let the user long-press on the **current location** pointer (the blue dot or arrow), and drag-n-drop it to the correct location. 

 - During this operation, let OsmAnd automatically zoom in to level 16-18, to allow precision placement. 
 - Once the point is dropped, go back to original zoom level.

**Comment by sonora** [comment]
Looks like no action is planned here.
