### ISSUE TITLE
Bugs: The "Next turn" icon and "Lane guidance" icons have several bugs

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#1976]
I mention them together because together they provide safe driving.

As the attached screenshots show, they have several bugs:
1. The next turn indicator misses turn/fork on the road, and focuses far ahead.

2. OsmAnd provides no visible/audio hazard warnings at junctions, where incoming traffic can suddenly appear in front of the driver at high speeds.

3. At junctions, the driver should be warned to avoid the lanes closest to the merging side lane.
    OsmAnd does not do this.

4. The top bar often shows only a manoeuvre (such as U-turn icon), but does not show the road's name.

5. OsmAnd often fails to snap the route to the road. The route line often jumps across roads. 

6. Often a flyover/underpass has exit lanes just before it. In such cases, OsmAnd does not direct the driver to take the proper lanes.

7. Before exiting from a road, we have to change lanes. But OsmAnd does not guide the driver to execute this lane-changing operation well before the exit comes up. Changing lanes at the last minute may be dangerous!

[Bugs - Next turn indication, Lane guidance.pdf](https://github.com/osmandapp/Osmand/files/45203/Bugs.-.Next.turn.indication.Lane.guidance.pdf)

**Comment by sonora** [comment]
Cannot address all issues, here, just some partial remarks:

- Display issue in the top bar should have been fixed already

- I advise against audible beeps as warnings signs where there is no clear indication what a warning is about - this may distract more than help (at exactly a crucial point in time). In most cars I know, and in some countries this may be legally regulated, all warnings are accompanied by a clear visual indication

- We have lots of feedback that OsmAnd is too chatty already. Additional announcements about lane changes where traffic  may be merging really adds more chattiness. and it may be pointless, we have no indication how much traffic there actually is. If I got an audio prompt to change lanes at every highway entrance I pass where traffic would merge, it would drive me nuts.

- Situations where you follow a major highway, and a smaller highway forks are hard to judge from map data. I find that in the majority of cases, if the mapping is correct, it produces undesired results to announce a turn, when you really only just follow the major highway.  Prime example (and we used to have this years ago!) is that you follow a primary or secondary highway, and a trail forks. Announcing a "turn" to follow the primary highway is really weird, most people do not even perceive the trail...  Situations vary, hard to judge by the map.

**Comment by vshcherb** [comment]
1st one is duplicate and already fixed.
OsmAnd is already too chatty in my opinion as well. There is a separate discussion about audible beeps and the implementation has been postponed, it is definitely should be used only by professionals to avoid confusion, though OsmAnd is not targetting at specific areas, cause it could be special forks and builds for that.

**Comment by raindropsfromsky** [comment]
sonora- "Situations vary- Hard to judge by map" is the exact dilemma the driver faces too! 
And that's the precise reason OsmAnd should err on positive side.

Of course, the lane guidance is not an essential feature: Even if there is no lane guidance at all, the driver can always steal a glance at the screen to check which way the purple line (route) is headed.

**Comment by sonora** [comment]
Let me close this one, I think much has been changed and improved, so this is outdated here.

There are some ideas which should actually be feature requests, but they mostly would lead to increased chattiness (we are going the opposite way), and they basically should anyway not be hidden in a "bug" issue.
