### ISSUE TITLE
Bicycle long Route - crash

### ISSUE THREAD

**Issue by anten1222** [osmandapp/OsmAnd#19760]
### Description

Start 52.50906° N, 13.39835° E
target point 52.27491° N, 8.03270° E

calculate route.  5 Minutes then Crash 

Start 54.77021° N, 9.44086° E
Target Point 48.00053° N, 7.85236° E
Calculate does not start

Osmand 4.7.13
Profile Bicycle 
contour lines not activated

### Steps to reproduce

Start 52.50906° N, 13.39835° E
target point 52.27491° N, 8.03270° E

calculate route.  5 Minutes then Crash 

Start 54.77021° N, 9.44086° E
Target Point 48.00053° N, 7.85236° E
Calculate does not start

Osmand 4.7.13
Profile Bicycle 
contour lines not activated

### Actual result

Crash

### Expected result

T

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:4.7.13
Android/iOS version:14
Device model:
Crash-Logs: ?no
```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. In the initial scenario, the route covered 451.0 km and took about 5 minutes to calculate before crashing. Similarly, in the second case, with a route spanning 969.3 km, the app also crashed after approximately 3 minutes of calculation. There were no intermediary points used in these calculations. To recreate this issue, follow these steps:

- Select a bicycle profile
- Reset the profile settings
- Download the required maps
- Input the provided coordinates for the start and end points

For the first route, use this web link: [link to first route](https://test.osmand.net/map/?start=52.509060,13.398350&end=52.274910,8.032700&profile=bicycle#7/52.452/9.042)

For the second route, use this web link: [link to second route](https://test.osmand.net/map/?start=54.770210,9.440860&end=48.000530,7.852360&profile=bicycle#6/53.019/6.130)

Here are the corresponding crash logs:
[exception.zip](https://github.com/osmandapp/OsmAnd/files/15237707/exception.12.zip)

OsmAnd~ 4.8.0#2266m, released: 2024-05-07

<table style="width:100%">
  </tr>
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/05d341a7-2d05-42d5-be69-52854c1f8e9f"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/466a91f5-5fcf-4d42-be70-4773f36f46b9"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
Probably issue fixed in 4.7.17

**Comment by yuriiurshuliak** [comment]
Upon re-checking, I confirmed that the 451.0 km route calculates without issues, completing in approximately 1 minute and 30 seconds.

However, in the second scenario involving a 969.3 km route, the app crashes and fails to calculate the route. No crash logs were generated.

OsmAnd~ 4.8.0#2309m, released: 2024-05-15

<table style="width:100%">
  </tr>
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/0479bdf8-4508-44a8-bb71-dfee5610c866"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/2a00a243-d816-42b2-a8cd-0dd1941f2c8f"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by anten1222** [comment]
From 53.70930° N, 9.38912° E
To 48.01306° N, 7.82504° E
Plan route
Aborted after 20 minutes

**Comment by anten1222** [comment]
With the nightly of 16.050 it works, so it can be considered done
