### ISSUE TITLE
Rendering GPX Tracks is slow due to constant checks

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#19768]
## Description
Rendering GPX Tracks is slow due to constant checks

## To do: 
- [x] Implement proper fix that check for gpx attributes happens only once something has changed in appearance, probably Global version of Appearance should be maintained or Version per track (int variable )
- [x] Auto test

**Comment by alex-osm** [comment]
Hot fix - https://github.com/osmandapp/OsmAnd/commit/9556fd1bb630d3d98308f0ac33ed6919fb5486f2

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.8.0#2539m, released: 2024-06-20
on my setup works well
