### ISSUE TITLE
OsmAnd should display names of gates for gardens and stadia

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#1977]
Large public gardens and stadia have several gates, and each has typically separate parking area and approach (service) road. 

Therefore it is important to treat these gates as POIs, so that we can search for a specific gate and set it as destination.

Currently OsmAnd does not have this provision.

**Comment by xmd5a2** [comment]
Added name and ref to rendering (barrier tag). I see no reason to add barriers (even only named) to POI because numbers in search results can interfere with finding other POI.

**Comment by raindropsfromsky** [comment]
Thanks. But every such entry may not be marked as "Barriers" ("gate" in iD editor): In case of entrances of stadia, they may be defined as "entrance" (http://wiki.openstreetmap.org/wiki/Key:entrance). 

So just to confirm, does your change allow us to (a) search for and (b) set the specific gate/entrance as destination? (note that depending on the location, we may have to use the appropriate mode of navigation: **Car** or **pedestrian**).

**Comment by xmd5a2** [comment]
No, it's just map rendering

**Comment by raindropsfromsky** [comment]
That's fine, then. If it is visible on map, then we can long-press there and set it as destination.

BTW I hope you have made "entrance" tags visible too, just like the "gate" tag.
