### ISSUE TITLE
vehicle:conditional=no spreads from one node to whole highway

### ISSUE THREAD

**Issue by Peter0** [osmandapp/OsmAnd#19773]
### Describe the routing engine used (required)

- [×] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Describe your routing Profile (required)

Standard car
Consider temporary restrictions

### Describe your start and end points (required)

Start: 50.73183 7.08673
Dest.: 50.73099 7.08747

### Describe the actual route (required)

Actual route doesn't lead into dest. street (way #4692930). Route ends at position with lowest distance at neighbor-street (way #1152458094 or #1152458088).
Note that there is a new node with temporary vehicle blocking (node #11877065356).

### Describe the expected route (required)

I’d expect that route ends upon way #4692930.
It does so already if I don't tick option "consider temporary restriction".
Flipping direction shows no strange behaviour: Starting point opon way #4692930 seems to be no problem.

### Describe what Maps you used (online or offline) (required)

- [×] Offline maps offered within the OsmAnd app for download. 
- [ ] Online (tile / raster) maps 
Current maps used: Europe, Germany, NRW, LVR Köln as of May 2024
Live updates

### Your Environment (required)

```
OsmAnd Version: ~ 7.4.10
Android/iOS version: e/OS similar Android 9
Device model: Samsung Galaxy J5
```

**Comment by aceman444** [comment]
Why is the tag vehicle:conditional=no? There is no condition specified.
There is no OsmAnd 7.4.10. Did you mean 4.7.10 ?

But other than that, I agree OsmAnd should route up to that point where the blockade is, not just some neighbouring road.

**Comment by Peter0** [comment]
Of course, I meant 4.7.10.

Both Vespucci, as well as https://www.openstreetmap.org/node/11877065356 shows "no @ (2024 May 1-2024 Dec 31)". Where do you see that there is no condition?

**Comment by aceman444** [comment]
It was 'vehicle:conditional=no' in your report title :) Yes, the data real has a condition specified. But that node is only 2 days old. It is quite possible it is not yet in OsmAnd maps. Do you use the Live updates of maps in OsmAnd?

**Comment by Peter0** [comment]
Yes, I use live updates.

**Comment by aceman444** [comment]
I think routing using live updated maps does not work 100% correct. You can see there is an option in navigation settings whether to use data from live updates or not. So maybe developers know there are some problems with it yet.

**Comment by Peter0** [comment]
Indeed, I wasn’t aware of such an option. Could you please describe where it is? I’d expect it under "Settings" at the navigation start/dest. input dialog requester, where one can also find things like "permit private ground", "consider temporary restrictions" and the like.
(Note that all mentioned setting’s names are translated by me on an ad hoc basis and therefore probably wont exactly match the english version’s terms.)

**Comment by aceman444** [comment]
It is there below "consider temporary restrictions", there is "navigation settings", then "route parameters" and inside it is "OsmAndLive data" -> enabled/disabled .

**Comment by Peter0** [comment]
To me, your video shows a slightly different effect/issue. The original posting is about an issue during route-planning time. Yuri's video, as well as the mentioned issue #19707 are about issues during navigation-in-progress time.

**Comment by Peter0** [comment]
May the video shows an effect of inconsistent data? Take into consideration that the "barrier" node is a relatively young/new part of OSM data. It looks like the barrier wasn't seen during route planning, but was "feeled" during navigation-in-progress.
In addition, I can't tell whether the last bit of planned route is a straight line due to the straight underlying street, or due to a tangled router that simply draws a straight line from last "accessible" place to final destination as kind of last resort action.

**Comment by vshcherb** [comment]
Looks like this https://www.openstreetmap.org/node/11877065356 not supported however it looks a bit strange

**Comment by DmitryAlexei** [comment]
Todo:
- investigate how the tag vehicle:conditional=no should work. Is it already supported?
-

**Comment by xmd5a2** [comment]
`vehicle:conditional` means access restriction while condition is true. As far as I know it is supported in routing: [link]
(https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd-java/src/main/java/net/osmand/binary/BinaryMapRouteReaderAdapter.java#L243)
We do have `vehicle:conditional` in data not on a whole way but only on a way's node
`Road 300347531 osmid 4692930 highway='residential' lit='yes' maxspeed='30' surface='asphalt' osmand_ele_start='59' osmand_ele_end='59' osmand_highway_integrity_brouting='0' sidewalk='yes' name="Händelstraße" name:etymology:wikidata="Q7302" pointtypes [[2. vehicle:conditional='no @ (2024 May 1-2024 Dec 31)' 50.730923 / 7.0865946 ]] lat/lon : 50.73091 / 7.0864444 , 50.730923 / 7.0865946 , 50.731037 / 7.0882792 , 50.73106 / 7.088362 , `

**Comment by Peter0** [comment]
From a mapper's point of view, using it on a node instead of on a way seems straightforward, as long as there is a relatively small/short obstacle. Even when there is a direction-dependent tag (e.g. a short piece of oneway), it would seem reasonable that the direction is "inversely" heritated from the "underlying" way.

**Comment by RZR-UA** [comment]
The tag `vehicle:no` (also with `conditional`) is processed by OsmAnd in same way as any other "restriction" tags.

The problem happens only when "restriction" node is placed on the edge of the long road segment (the whole highway is not affected indeed).

In such situation a whole street might be "avoided" if most of the street consists of 1 long segment.

That's exactly what this Issue's case is.

The fix is proposed.

Check the video:

https://github.com/user-attachments/assets/0707e2f4-d56c-44a8-80fa-e8c067a6e717

**Comment by RZR-UA** [comment]
- [x] Java
- [ ] C++

**Comment by RZR-UA** [comment]
Android/iOS tested:

![a1](https://github.com/user-attachments/assets/9d6d6442-a46f-471e-9b0a-9ecfd21a9206)
![a2](https://github.com/user-attachments/assets/0b69b2d4-e351-4ab4-bd17-c1f03f8c9907)
![ios1](https://github.com/user-attachments/assets/82779022-9f1a-493d-8657-a09c005be322)
![ios2](https://github.com/user-attachments/assets/cabb5cbd-da71-4752-be3e-9a9b878fb40b)

**Comment by RZR-UA** [comment]
> Simpler approach to be tested (https://github.com/osmandapp/OsmAnd/pull/20610/files)

It is not working correctly.

The tests are improved.

Please review.

**Comment by vshcherb** [comment]
- [ ] Attach OSM.gz to 68-70 test 
- [ ] Port to C++

**Comment by vshcherb** [comment]
Looks the same issue but that wasn't fixed correctly ? https://github.com/osmandapp/OsmAnd/issues/16173

**Comment by Peter0** [comment]
Thanks

**Comment by vshcherb** [comment]
Site clearly was not reloaded as it has bugs even for https://github.com/osmandapp/OsmAnd/issues/19773#issuecomment-2295382709. Probably site doesn't use current time restrictions
