### ISSUE TITLE
Adding wrong "original_poi_type_tag" tag

### ISSUE THREAD

**Issue by mueschel** [osmandapp/OsmAnd#19770]
OsmAnd recently started adding wrong "original_poi_type_tag" tags to objects.

http://overpass-turbo.eu/s/1Lb4

**Comment by matkoniecz** [comment]
Thanks for a fix!

Is version with fix released? Do you plan to propose and make automated edit (see https://wiki.openstreetmap.org/wiki/Automated_Edits_code_of_conduct ) that will clean up damage?

See http://overpass-turbo.eu/s/1M2a for affected objects.

**Comment by vshcherb** [comment]
Yes this version is released. Not sure how to address automated edits...

**Comment by matkoniecz** [comment]
In this case I would probably make thread at https://community.openstreetmap.org/ - and announce that this tag was added by accident, propose mass removing all occurrences and wait week or two whether anyone protests. And then mass remove all instances of this tag with level0, JOSM or script (I can do edit itself of noone wants to do it among osmand makers)

Or just mass remove all instances of this tag as it was added only as result of obvious bug and had no real use (outside this bug). Can be described as revert of undiscussed bot edit if anyone will ask.

**Comment by mueschel** [comment]
In this particular case I would just do the removal with a good explanation and a link to this issue in the description.
The tag is clearly a mistake and doesn't contain any information - all proper tags were still added as they should be.
