### ISSUE TITLE
"World overview map" (disabled) then always asked to be updated

### ISSUE THREAD

**Issue by aceman444** [osmandapp/OsmAnd#19776]
### Description

Always proposes to download "World overview map" even though World overview mini map exists.

### Steps to reproduce

I have the "World overview map (mini)" enabled and the full "World overview map" disabled (backed up).

### Actual result

Every time I manually update any country map, or even start the Live update, OsmAnd offers to download the "World overview map" thinking it doesn't exist. But it does exist and is up to date, just disabled, and the mini version is used instead.

### Expected result

I would understand it if both maps were disabled, then one of them needs to be enabled. OsmAnd even forcefully enables one of them, see issue #17085 . But this is not my situation. The 'mini' version of the map is supposed to be enough for OsmAnd so no World map download should be forced.

### Your Environment (required)

OsmAnd 4.7 but existed in older versions too.

**Comment by yuriiurshuliak** [comment]
OsmAnd~ 4.8.0#2256m, released: 2024-05-06


https://github.com/osmandapp/OsmAnd/assets/127092082/82d78dc2-f8db-4ef0-8d37-088c3e9dc362

**Comment by aceman444** [comment]
Also, you have to restart OsmAnd after you disabled the full World map.

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. Here are the steps to reproduce:

- Download both maps: "World overview map" and "World overview map (mini)."
- Deactivate the "World overview map."
- Attempt to navigate through a map that is not loaded.
- Then, try to download the map for further navigation.

The outcome is that the prompt to download the "World overview map", which is already downloaded, appears again.

OsmAnd~ 4.8.0#2288m, released: 2024-05-13

https://github.com/osmandapp/OsmAnd/assets/127092082/0ddbb586-7da5-49a0-93fb-0d655594a951

**Comment by aceman444** [comment]
Thank you.

**Comment by vshcherb** [comment]
The way it's reproduced it assumes that World basemap is loaded and archived

**Comment by vshcherb** [comment]
To do: we could disable this dialog completely cause wolrd overview basemap is now fully optional

**Comment by yuriiurshuliak** [comment]
The bug has been fixed. Currently, "World overview map" is not offered to re-download.

OsmAnd~ 4.8.0#2559m, released: 2024-06-22

https://github.com/osmandapp/OsmAnd/assets/127092082/fb96a8ff-d867-42eb-934e-3a3894570d8d
