### ISSUE TITLE
Suggestion for french translation

### ISSUE THREAD

**Issue by Vucumpra** [osmandapp/OsmAnd#19784]
Avoid road...

"No sett" => **éviter les pavés taillés**
"Avoid cobblestone" => **éviter les calades**

**Comment by DmitryAlexei** [comment]
Translations can be modified by users via weblate. Please see
https://hosted.weblate.org/projects/osmand/

**Comment by Vucumpra** [comment]
Thank for the link but It is impossible to 

> Translations can be modified by users via weblate. Please see https://hosted.weblate.org/projects/osmand/

Well, I try some things, some link, both in french and english section to translate or suggest a new translation but the word "cobblestone" never found or find only associated with key "surface" but never in "avoid context".
So I conclude that weblate seem very not user friendly.
infortunatly, I don't have time to study "How to" about weblate. So I prefer stay with bad translation, sorry
