### ISSUE TITLE
New "Round up" label incorrectly translated to German

### ISSUE THREAD

**Issue by bluezed** [osmandapp/OsmAnd#19783]
### Description

The new "Round up" label gas been translated to German as "Abrunden" which actually means "Round down", so exactly the opposite of what the setting is actually for.

### Steps to reproduce

Use the App in German and look at the setting label.

### Actual result

It says "Abrunden" (round down).

### Expected result

It should say "Aufrunden" (round up).

### Your Environment (required)

```
OsmAnd Version: 4.7.10
Android/iOS version: 12
Device model: Xiaomi Mi Note 10 Lite 
```

**Comment by DmitryAlexei** [comment]
Users can change translations via weblate (https://hosted.weblate.org/projects/osmand/main/de/)
