### ISSUE TITLE
Feature request: Fuel economy routing

### ISSUE THREAD

**Issue by qantourisc** [osmandapp/Osmand#1978]
It would be nice to have fuel based routing.

This would require the following changes:
- Adding a path-cost calculation based on fuel-time-ratio (more on that later). But I suspect most of that code is already in place since we can choice between distance-cost and time-cost routing.
- Ability to add speed / fuel-consumption at different speeds in the settings. (Linearly blend for speed-fuel points that have not been set.)
- Ability to set breaking cost (hybrid cars have reduced breaking cost) (Might wish to disable this item for now if OSM doesn't take into account deceleration, stop signs, lights etc...)
- As a result of the request above, ability to select different vehicle profiles, in case they use 2 or more vehicles.
- Slider in the route visualization to change fuel/time ratio.
- Ability to set max-speed (to limit speed on highways, due to fuel considerations). This setting would also be useful for vehicles that have a technical speed limit !!! : such as scooters, and light EV vehicles.

About the fuel/time ratio:
The most fuel economic mode for a lot of vehicles is driving at (I think) ~40 km/h, of course travelling at this speed is not realistic. As such the fuel-cost VS time-cost ratio slider is required. What it should do, is linearly blend the speed-cost and the fuel-cost routing. So if the slider is set all the way to fuel side, you get a ~40hm/h route. If it's all the way to speed side, you get the identical result as if you picked fastest route routing.

In rough pseudo code:
```
//Calcs the routing cost of a piece of road
getSegmentCostEconomy(){
     global fuel_time_ratio;
     float time_cost = this->getSegmentCostTime();
     float fuel_cost = this->getSegmentCostFuel(); // <- Actual fuel cost calculation goes here
     cost = fuel_cost * ratio + time_cost * (1-ratio);
     return cost;
}
```

**Comment by naoliv** [comment]
Doesn't some commercial apps calculate the `green`, `eco`, `economic`, etc route as a function where the fastest route matches the shortest route? (ie, an "intermediary" solution between both)

**Comment by sonora** [comment]
Economy option added, no further action planned for now, I guess.

**Comment by naoliv** [comment]
Is "fuel-efficient" the same as "shortest"?

If I enable "fuel-efficient" I see that the fastest route gets disable (which means that it's using the shortest route)

**Comment by sonora** [comment]
Check out #2654  for an explanation, fuel-efficient is not 100% the shortest, but the economic route.

**Comment by notEvil** [comment]
Hi,

I sometimes wished there were an option which defines the tradeoff between fastest and shortest (economic) route, because in most cases I would like the fastest route which is also reasonable short. As an example: prefer 10km shorter route over 2min shorter one (I can find a real example if necessary). An implementation could look similar to

    C = t*alpha + s*(1 - alpha)

with time `t`, distance `s` and tradeoff `alpha` e [0, 1]. The tradeoff value obviously trades distance for time and can be expressed as 1 min = x km. I assume this is rather easy to implement and doesn't increase complexity too much.
