### ISSUE TITLE
Telugu language label display incorrectly getting cropped

### ISSUE THREAD

**Issue by arjunaraoc** [osmandapp/OsmAnd#19780]
### Description

Telugu (part of indic, complex text layout language used widely in India) label display is  incorrectly getting cropped. 

### Steps to reproduce

1. On Android device, enable  Telugu language as an additional language.
2.  Install OsmAnd and download map for Andhra Pradesh, India.
3.  Search for Jaggayyapeta. (This corresponds to the location https://www.openstreetmap.org/node/245638877#map=13/16.8930/80.0986) 
4. Observe  Telugu (part of indic, complex text layout language used widely in India) label display. It  incorrectly getting cropped. It should be displayed as జగ్గయ్యపేట, with descenders on the second and third complex character properly shown.

### Actual result

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/524249/8f769e0f-4428-4cfc-b212-02cd08c0fa67"  width="300" height="auto"/> </td>
  </tr>
</table>
Observe the cropping of descenders on second,  and third complex characters. compare with  the same label in the bottom part of the screen.  Note the name for near by place called చిల్లగల్లు (Chillagallu) is also  impacted.

### Expected result

Display of Telugu labels with full descenders where present needed.  For the location it should be జగ్గయ్యపేట

### Your Environment (required)

`
OsmAnd Version: 4.7.10
Android/iOS version:11
Device model:OnePlus 6 (Model ONEPLUS A6000)
Crash-Logs: Not relevant
```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. Try switching the map language to Telugu and navigate to coordinates 16.893, 80.09862. You'll observe that the map labels appear in Telugu; however, pay attention, and you'll notice that the lower portions of these labels cut off.

OsmAnd~ 4.8.0#2256m, released: 2024-05-06

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/7ab3782e-d396-4c68-9dbd-d75e17aa3c4a"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/a0b5f887-67ea-4866-90f5-7ce5f39cc7a4"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/2ea38f90-4f65-4cd7-88dc-bc126886244b"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by yuriiurshuliak** [comment]
The bug has been fixed. When changing the map language to Telugu, the names are now displayed in full without any parts being cut off at the bottom.

OsmAnd~ 4.8.0#2738m, released: 2024-07-15

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/bb037a8a-c6ca-425f-8d46-7ecb0d26c856"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/86381c57-b5bf-4d95-b99b-269beafbe72c"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/bccfdcc7-adb6-4082-ab5c-5d67bb6690e4"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by dmpr0** [comment]
iOS 

![Screenshot 2024-07-16 at 17 44 12](https://github.com/user-attachments/assets/c08a1503-416c-4a0c-800b-df7b5d42cb96)
