### ISSUE TITLE
Osmand slows down when selecting a route

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#19795]
### Description

I highlighted the "Волжская тропа" route with a length of 304 km.  After this, scrolling the map began to slow down.
After I hid the route track, scrolling the map became more responsive.
Link to route:
https://www.openstreetmap.org/relation/15678293

See video in telegram chat:
https://t.me/ruosmand/151205

### Steps to reproduce

Highlight the route on the map.  And scroll through the map.

### Actual result

Scrolling the map is slow.

### Expected result

Scrolling the map should not slow down.

### Your Environment (required)

```
OsmAnd Version: OsmAnd~ 4.8.0#2258m, Released: 2024-05-06
Android/iOS version: 13
Device model: poco f3
Crash-Logs: ?
```

**Comment by DmitryAlexei** [comment]
I didn't manage to reproduce this issue 
on Samsung note 20 ultra (Android 13) using OsmAnd~ 4.8.0#2286m, released: 2024-05-13 and OsmAnd 4.7.17, released: 2024-05-07
- I downloaded Tatarstan (Russia) map
- then I enabled hiking routes (3d relief was also enabled)
- I highlighted and downloaded "Волжская тропа" route (loading of this route took about 5–6 seconds in both OsmAnd versions - comparable to previous versions)
- with the track turned on I looked through the map zooming in and out from various points


The map was responsive and tiles reloaded quick, **but the back of the phone got very hot** - that was only one issue I encountered. See video made with the latest nightly build.

@Nine-Tailed please confirm, that issue persists in the latest nightly (or release) build. 


https://github.com/osmandapp/OsmAnd/assets/116079541/dfa8e410-d1f0-4e4b-b945-565f30208f3d
