### ISSUE TITLE
Motorway-junction not editable

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#1979]
On previous builds, we could choose a 'motorway_junction' point and there was the option to 'modify POI'. 
Very handy, worked great to update local information.

On today build, the 'modify POI' option is not available anymore for 'motorway_junction'?

**Comment by xmd5a2** [comment]
Fixed

**Comment by Barrocas** [comment]
Thanks for the fast fix.
Cheers!


-- 
Cumprimentos,
D.er Hugo Barrocas
