### ISSUE TITLE
Regression: Track folder statistics preliminary, never updated

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#19804]
This is a regression, reverting this commit (i.e. preventing interim progress publishing) seems to solve the issue: https://github.com/osmandapp/OsmAnd/commit/f0e141b9df0965a38b3ea9f64a26a37278f2f096 (at the cost of the Adapter only filled once complete).

To reproduce: Simply have many tracks, open the MyPlaces>Tracks screen and check the stats at the bottom of the screen. I e.g. have 3000 tracks, the stats may only show 100 or so (likelya n interim count). This gets never updated. Except when I do a pull refresh, then I may get yet another count.

(The issue is not only for the root folder, but fo all reasonably large folders.)

**Comment by sonora** [comment]
I've double-checked that in deed commenting out the progress publishingi in the loop produces correct folder stats everywhere.

With our latest build we have for my setup successfully reduced the MyPlaces/Tracks loading time to snappy 1-2 sec (!) now (with the false folder stats). But with commenting out the progress interim publishing (correct folder stats) it increases to about 6 sec, so how we produce the stats seems rather expensive.

**Comment by Chumva** [comment]
So our progress update leads to x3 time for tracks loading? Probably because of recalculation of track stats every time

**Comment by sonora** [comment]
I am not sure if it is the progress updates themselves causing this performance hit, or the stats calculation, probably the latter.

If it is not buggy in itself, perhaps we need to either cache it in the db, or perhaps just provide it upon a separate tap request or something. Producing it live upon every action on the tracks management screens seems overkill with no sufficient usecase?

**Comment by Chumva** [comment]
We can calculate stats in TrackFolderLoaderTask after we get everything from loadGPXFolder & not try to call it during the progress update

I am unsure about adding these stats to db because they may be often changed & we have to support additional db/updates which may lead to more issues

Strange, I still have logs per 100 files, we can remove them after finalizing code in TrackFolderLoaderTask

**Comment by sonora** [comment]
Ues I fully agree. And let's keep it out of the db!

Regarding the logging: Perhaps I am overlooking somethig, never mind for now.

**Comment by sonora** [comment]
@Chumva: This fixes the underlying issue: https://github.com/osmandapp/OsmAnd/commit/fa12fce532b8033ee1b03bfdf872e1a6aa48a147.

Still not optimized for speed, though, probably could save some cycles by improving something about the folder stats calculation.

**Comment by dmpr0** [comment]
# Review

<table style="width:100%">
  <tr>
    <th>Sub folder</th>
    <th>Main folder</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/eec58a29-6bf5-48a3-8a7b-165ffd10c151"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/62fdb92d-c79d-4700-88f8-67e49fa72c3a"  width="300" height="auto"/> </td>
  </tr>
</table>   



- [ ] Uphill / Downhill is broken, for tracks that already present in OsmAnd it show 0 for both as on folder statistics and on track context menu. Re importing the same track, uphill / downhill is present.

**Comment by sonora** [comment]
@dmpr0 What build number is this, Dmytro? Can't seem to reproduce, actually.

Related question is why we need a pull refresh here at all? Because as it is coded now, the screen is refreshed upon every entering, anyway?

(Perhaps to facilitate a pulldown becomes meaningful if we implement reading from preloaded objects in #19683, but how that ends up still remains to be seen.)

**Comment by dmpr0** [comment]
@sonora 
Build `OsmAnd~ 4.8.0#2359m, released: 2024-05-21`, pull-to-refresh is needed to import tracks manually copied to OsmAnd folder.

**Comment by sonora** [comment]
> pull-to-refresh is needed to import tracks manually copied to OsmAnd folder.

I use manual copying a lot, but never pull down: _Everything is updated upon each entering of the screen_, which is expected list update behavior in a lot of software. So for the rare case that users perform their copying _exactly while on this screen_, in my experience their first impulse is to leave and re-enter the screen anyway to immediately find everything ok... :wink:

But if we still wanted to fix, rather than disable: This is likely a timing issue of overlapping `AsyncTasks`. As `AsyncTask` are deprecated, we will have to eventually move the code to `ExcecutorService` or similar anyway, could look a things then. I have also noticed that if you quickly perform 6 or so pulldown refreshs, you may run into an NPE of calling the flattened tracks on a null object. (Also a timing issue of too many overlapping threads.)

This can all be fixed. I was just wondering if this is worth our dev effort, and the resulting code overhead, for what may be a 'fringe' functionality.

**Comment by sonora** [comment]
PS: I went through my old screenshots from when I had worked on this code last week, and also found one where the downhill meters where shown as "0m". Looks like this may be limited to the downhill display only...(?)
