### ISSUE TITLE
NPE in Downloads Layer

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#1980]
https://github.com/osmandapp/Osmand/issues/1274#issuecomment-160095592

We already fixed it for 2.2 may the merge didn't happen.

**Comment by sonora** [comment]
Yes, I was just going t open an Issue about it. The NPE is not related to #1274 at all, as expected.

The NPE happens on the latest master nightly, I am not talking about the release here.

I can spuriously reproduce it tapping e.g. on the Atlantic Ocean off the coast of Morocco (north-east of the Canary islands, but south east of the area covered by the Portugal "cone" region to include Madeira). Looks we somehow have an issue assigning the region or something.

May also be related to our definition of the Canary Islands,
- they do not show a "cone" towards the Spanish man land.
- Also, while their regular map is included in Spain,  their SRTM file is a separate download, a Hillshade file seems entirely missing? All these may be unrelated, but need fixing.

**Comment by vshcherb** [comment]
Should be fixed

**Comment by sonora** [comment]
Yes, gone on new builds.
