### ISSUE TITLE
No POIs are shown

### ISSUE THREAD

**Issue by YosypC** [osmandapp/OsmAnd#19810]
### Description

Every POI is selected with point labels on, but none is shown.

<img src="https://github.com/osmandapp/OsmAnd/assets/50027752/8df3b425-a48f-48f2-b4fd-cdd560d0803d"  width="300" height="auto"/> 

### Steps to reproduce

Freshly installed app, using online tiles.

### Actual result

<img src="https://github.com/osmandapp/OsmAnd/assets/50027752/2080933b-3a61-4cbb-9996-9b164a7ad501"  width="300" height="auto"/> 

### Expected result

![image](https://github.com/osmandapp/OsmAnd/assets/50027752/43c187f7-3fbe-4152-8e11-dafb7b74f486)

Taken from a web browser.

### Your Environment (required)

```
OsmAnd Version: 4.7.17
Android/iOS version: 14 Android
Device model: Galaxy S21 FE
```

**Comment by dmpr0** [comment]
Offline maps are required to show POI. 
Mostly all OsmAnd features are based on offline maps, you need to download a map for the needed region.
