### ISSUE TITLE
Search in Favorites doesn't find home

### ISSUE THREAD

**Issue by KnollFrank** [osmandapp/OsmAnd#19815]
### Description

Search in Favorites doesn't find Home using the search query "Home".

### Steps to reproduce
1. Define a home address on the navigation screen:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/23587457/00ac78a0-6de7-48e9-9946-dc8e05d2f487"  width="300" height="auto"/> </th>
  </tr>
</table>

2. Edit the name of the home address to "My address":

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/23587457/34132379-84e9-4982-b9d2-aa09cce7b178"  width="300" height="auto"/> </th>
  </tr>
</table>

3. Open the Favorites Search via Menu -> My Places -> magnifying glass symbol: 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/23587457/06cda495-6629-47f0-bf64-7d064b143aaa"  width="300" height="auto"/> </th>
  </tr>
</table>

4. Enter "Home" as the search query: 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/23587457/fe7cc44e-2acb-4628-8519-78436aa90c5a"  width="300" height="auto"/> </th>
  </tr>
</table>

or see this video:

[video](https://github.com/osmandapp/OsmAnd/assets/23587457/cd3de6de-07e0-4896-810c-657a93710f70)

### Actual result

The result list below the search query "Home" is empty.

### Expected result

The result list below the search query "Home" should display my home address.

### Your Environment (required)
```
OsmAnd Version: nightly build with revision number 080b64043e24a529c29581864039b23a6330f2f3
Android version: 14
Device model: sdk_gphone64_x86_64
```

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced.  I attempted to rename "Home" to "My Address" and added this favorite in navigation via the context menu. When I searched for "Home" in favorites, it was found successfully. 

Could you test this on our nightly version of the app to see if the bug occurs there as well? You can download it from: [Nightly Builds](https://osmand.net/docs/versions/nightly_versions#nightly-builds)

OsmAnd~ 4.8.0#2277m, released: 2024-05-09

https://github.com/osmandapp/OsmAnd/assets/127092082/0ac466d7-2c47-44d9-a5d0-c2542b541195

**Comment by KnollFrank** [comment]
I added a first step in the description above on how I defined the home address. Please do not add a second favorite, just edit the single home address. I could reproduce the bug with the nightly build as you mentioned.

**Comment by zipav** [comment]
OsmAnd Nightly 4.8.0#2341m, released: 2024-05-20

Reproduced on the latest OsmAnd Nightly.

https://github.com/osmandapp/OsmAnd/assets/123936521/629ac77d-d9e9-44d0-8198-cfd5e272f19a

**Comment by dmpr0** [comment]
## Review
- [ ] ToDo is missed
