### ISSUE TITLE
Allow create routes from a specific starting point (not current position); load/save/share them.

### ISSUE THREAD

**Issue by StyXman** [osmandapp/Osmand#1981]
I like to plan trips with friends. For that I mostly like to set a starting and destination point, maybe several intermediate points. I can do this with sites like https://osrm.at/, but not OsmAnd+, but only because I can specify the starting point.

A second part of the feature request is to load and save those routes , and maybe share them (GPX) with the rest of the trippers.

**Comment by sonora** [comment]
There are 2 ways to specify a starting point:

Either, on any location's context menu, hit the 3-dots menu in the lower right corner and select "Directions From", or on the navigation toolbar (which appears along the lower edge of the screen when you have started a navigation), select the little waypoints flag, then tap on the "From" line.

Regarding saving any route: On the same dialog, in the bottom line you can see a description of the route (once calculated). Tapping on it opens a detailed turn.by-turn description which can also be saved.

**Comment by StyXman** [comment]
This is the workflow I would have for planning a trip: Add several waypoints in a map, with a starting and finish points. At the end I get a route with the times between waypoints.

I did what you said: set a point as starting waypoint, then add more waypoints manually, but then when I hit the 'Go' button to calculate the route and get distances and times, OsmAnd waits for a GPS lock. For me this is contradicting the idea that I set a starting point.

**Comment by sonora** [comment]
Well, hitting the "Go" button implies you now want to start a real-life
navigation, (respecting your actual position). While the route with the
pre-set arbitrary start point is only displayed BEFORE you hot the GO
button.

If, on the other hand, you wan to *simulate* a life navigation from an
arbitrary solution, a functionality which should only be needed by us
developers for testing purposes and to reproduce bugs, you can use the
"simulate your position" functionality provided by the development plugin.
