### ISSUE TITLE
roundabout - gpx issue

### ISSUE THREAD

**Issue by Lore2688** [osmandapp/OsmAnd#19818]
Hi all, just one question: i have gpx files produced from https://www.mygpsfiles.com and i’m using it with osmand (i select attach to the road in osmand options) but i have a  problem: when i’m near a roundabout osmand say “at the roundabout take undefined exit”. I have tried to use osmand map (on osmand web site) to make gpx but is the same story..can someone help me? Thank you a lot!

**Comment by vshcherb** [comment]
You need to use Attach to roads to here proper instructions. We plan to do it automatically in 4.8.

**Comment by Lore2688** [comment]
Thank you vshcherb, i’m using attach to roads already but my issue remain. I have no ideas about why..

**Comment by vshcherb** [comment]
Please share your track to reproduce

**Comment by Lore2688** [comment]
ok. but can tell me how to share it? i can't attach gpx file here

**Comment by Lore2688** [comment]
> Please share your track to reproduce

https://drive.google.com/file/d/1WhOl5R2qPydNToPkn8NTzGDPiMo9jOlm/view?usp=sharing

here a link with a example gpx (is a very little file just to show..)

**Comment by Lore2688** [comment]
Just to ad one more info: i have tried to plan directly in osmand (point by point) but the problem remain. One fried of me, with android mobile, no have this issue!

**Comment by vshcherb** [comment]
Tested on web https://osmand.net/map/?start=43.875840,11.066556&end=43.877804,11.068130&profile=car#17/43.87632/11.06731
App should work the same attach to roads - so 2nd exit is displayed
![Screenshot 2024-05-13 at 18 21 10](https://github.com/osmandapp/OsmAnd/assets/1042025/ef2933f2-b435-44dd-b107-febe6eb5a81c)

**Comment by Lore2688** [comment]
Scaidermern: the problem persist even if i plan a trip directly into osmand (and i have tried on 3 iphone, 15 pro max, xs max and se)..
Vshcherb: yes ok but vocal indication say “undefined exit” 

https://github.com/osmandapp/OsmAnd/assets/169367212/5277e585-21a2-4524-9f50-0df9c14b5bcc

**Comment by Lore2688** [comment]
https://github.com/osmandapp/OsmAnd/assets/169367212/3cf591b7-a7bb-4ede-ad69-d77394258d28

**Comment by scaidermern** [comment]
> Scaidermern: the problem persist even if i plan a trip directly into osmand (and i have tried on 3 iphone, 15 pro max, xs max and se)..

Can't reproduce, works for me. But I'm on Android, not iOS.
