### ISSUE TITLE
The video note plugin has four bugs

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#1982]
The **Video Notes** feature has 4 specific bugs, as shown in attached screenshots:
1. While shooting, the video frame itself covers the "Stop" button. To uncover the button, we have to press the "Back" button of the phone, and then tap on the "Stop" button. This is extremely clumsy.
2. The video appears sideways on the screen (rotated by 90 degrees)
3.  The video is stretched (its aspect ratio is distorted).
4. The video frame has a header, but it is blank.

[Video note bugs.pdf](https://github.com/osmandapp/Osmand/files/45927/Video.note.bugs.pdf)

**Comment by sonora** [comment]
All fixed, I think.
