### ISSUE TITLE
Old route still shown after choosing new destination

### ISSUE THREAD

**Issue by limbusdev** [osmandapp/OsmAnd#19823]
### Description

I missed an exit and later took a turn. I stopped to re-start navigation. After that the new route was displayed next to the old one. See the screenshot.

### Steps to reproduce

1. Don't follow the calculated route and stop before it re-calculates.
2. go to search > recent searches > tap last one
3. wait for calculation and tap start

### Actual result

Both old and new routes are displayed. The thinner one is the old route I didn't follow. 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/6540152/ae48d773-543c-44fc-8c13-2f66b24e7195"  width="300" height="auto"/> </th>
  </tr>
</table>

### Expected result

Only new route is displayed

### Your Environment (required)

```
OsmAnd Version: OsmAnd+ 4.7.10
Android/iOS version: Android 14 / GrapheneOS
Device model: Pixel 6
```

**Comment by yuriiurshuliak** [comment]
Please specify the exact steps of actions needed to reproduce the issue, and include the starting and ending points of both the original and updated routes.

**Comment by yuriiurshuliak** [comment]
@limbusdev Please let me know if this issue is still valid and if you are still experiencing this behavior?

**Comment by vshcherb** [comment]
unfortunately we did not reproduce
