### ISSUE TITLE
Office engineer 

### ISSUE THREAD

**Issue by APneunzehn74** [osmandapp/OsmAnd#19829]
### Describe the idea (required)

Hello office engineer will be evaluated in Osmand I. Would be nice to have.
https://wiki.openstreetmap.org/wiki/Tag:office%3Dengineer

### Tell us about the expected behaviour (required)

Engineering offices are displayed as a symbol including additional data such as contact details.

### Tell us about alternatives you've considered (required)

no alternative

**Comment by letypequividelespoubelles** [comment]
See #15889 

Imho all office=* should be rendered

**Comment by APneunzehn74** [comment]
> Siehe #15889
> 
> Imho sollten alle office=* gerendert werden

That's right, an icon (Office) is displayed but all other information is missing. But there is no indication that it is an engineer and other information such as contact etc. is also missing.

**Comment by yuriiurshuliak** [comment]
https://taginfo.openstreetmap.org/tags/office=engineer#overview

**Comment by xmd5a2** [comment]
Fixed. Place to test: https://www.openstreetmap.org/node/10095463694
Map: Luxembourg
