### ISSUE TITLE
Feature request: Allow OsmAnd to import geo-tagged photos

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#1983]
One of the important missions of OsmAnd is to create new POIs in OSM.

And we can create new POIs in large numbers with this simple method:
1. As we pass through a new area, take photos as notes attached to specific location.
2. Later on look at each photo, and convert it into one or more POIs.

Over the past months, I have used this technique and created a lot of new POIs.
But this procedure has a major limitation: It requires us to do the roaming and shooting ourselves.
No person would be able to roam far and wide to capture photos in this manner.

The solution is to allow us to import geo-tagged photos taken by others.

Now any user can import photos taken by himself and his friends; and convert them into POIs.

**Comment by xmd5a2** [comment]
Must better and convenient way to do this - use JOSM.

**Comment by raindropsfromsky** [comment]
yes, that is possible, but this approach also allows us to add a POI while being mobile.

JOSM is strictly for remote/armchair editing of OSM.
OsmAnd and Vespucci can do both remote and on-site editing.

So importing photos into OSM is a good idea.

BTW it will also help us in planning a trip, by allowing us to attach previously taken geo-tagged photos to all the waypoints in one stroke!

**Comment by sonora** [comment]
No action planned, it seems. (?)
