### ISSUE TITLE
External Temperature Sensor - gpx data incorrectly labelled 

### ISSUE THREAD

**Issue by albansuser** [osmandapp/OsmAnd#19834]
### Description

I use a Garmin Tempe external air temperature sensor. Unfortunately the resultant data are stored in the gpx file incorrectly labelled as water temperature ("wtemp").

The data should be stored as air temperature "atemp". The error means that the gpx file temperature data cannot be read by the other gpx file viewing apps I use.

Can this be corrected? Maybe with a air/water user set option?

Thanks

### Steps to reproduce

Record air temperature data using external sensor

### Actual result

Data labelled as water temperature

### Expected result

Air temperature correctly labelled 

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd~ 4.8.0#2282m, released: 2024-05-10
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
Please upload the GPX file containing the data that was not saved correctly, so we can investigate the issue.

**Comment by albansuser** [comment]
Thanks for your response.

Here's a screenshot of the relevant data section in a typical GPX file:
![Screenshot_20240513_201559_SimpleEditorFree](https://github.com/osmandapp/OsmAnd/assets/66352711/1bba2f00-42d8-4de1-b4df-6d1555a9d047)

**Comment by vshcherb** [comment]
To do: double check we use atemp - as air temperature

**Comment by albansuser** [comment]
Thanks. Will be good to have it fixed. 

Will correcting the temperature label affect the temperature profile display in "Show on map"? That is, does the current temperature profile display depend upon the incorrect "wtemp" label?

Cheers

**Comment by dmpr0** [comment]
> Thanks. Will be good to have it fixed.
> 
> Will correcting the temperature label affect the temperature profile display in "Show on map"? That is, does the current temperature profile display depend upon the incorrect "wtemp" label?
> 
> Cheers

Yes it will be fixed too.

**Comment by albansuser** [comment]
Hello

Any progress on fixing the temperature label?

Thanks

**Comment by albansuser** [comment]
Works as intended woth correct label.

Thanks.
