### ISSUE TITLE
Public transport routing became unable to find routes to almost anything

### ISSUE THREAD

**Issue by helloyanis** [osmandapp/OsmAnd#19836]
### Describe the routing engine used (required)

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Public transport, as default with no restrictions.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/40769776/75ee8fa1-5551-4a17-8acd-fba5ebaf2b0f"  width="300" height="auto"/> </th>
  </tr>
</table>

### Start point
`50.65152° N, 2.97601° E`, "Armand Thiery" clothes shop in Lomme, next to the subway station `Saint Philibert` on line 2 of the subway.

### End point
`50.60542° N, 3.13646° E`, "Restaurant Universitaire Sully", near the subway station `4 Cantons - Stade Pierre Mauroy`, on line 1 of the subway.

### OsmAnd doesn't find a route

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/40769776/82db5e9c-6cf0-4cb9-9290-8f6c512a1b6c"  width="300" height="auto"/> </th>
  </tr>
</table>

### Describe the expected route (required)

- Take the subway on line 2
- Switch to line 1 at the `Porte des Postes` or `Gare Lille-Flandres` station (the only ones where the two lines connect)
- Stay on line 1 until the last stop

Here's how Ilévia (the transpor company)'s website calculates it (and how it should be) :

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/40769776/82d9f8d0-bc57-49f6-a970-58603cde201f"  width="300" height="auto"/> </th>
  </tr>
</table>

[Link to this website](https://www.ilevia.fr/carte-interactive) (it's in french)

### Describe what Maps you used (online or offline) (required)

- [x] Offline maps offered within the OsmAnd app for download. Downloaded on May 1st 2024
- [ ] Online (tile / raster) maps 

### Your Environment (required)

```
OsmAnd Version: 4.6.14
Android/iOS version: 14
Device model: Samsung Galaxy A52S 5G
```

### Anything else? (optional)

It used to work fine in a previous (not sure which) version of OsmAnd, after a very long load time. Now it loads fast but doesn't find anything.

I don't really have an idea of why this happens

Thanks for the help!!

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. When attempting to calculate routes using the Public transport profile directly, regardless of the number of changes and the country of use, an error message "Unfortunately, OsmAnd could not find a route..." is displayed.

Interestingly, if you first calculate a route using the Car profile and then switch to the Public transport profile to calculate the same route, the route is successfully calculated without errors.

OsmAnd~ 4.8.0#2288m, released: 2024-05-13

https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/99f90980-72aa-49ce-b0e4-43ecebb654da

**Comment by vshcherb** [comment]
Android / iOS needs to be tested

**Comment by vshcherb** [comment]
Looks like we didn't reproduce the issue. So on 2nd attempt it always works, it doesn't work on first attempt only if you have public transport default profile
```
Interestingly, if you first calculate a route using the Car profile and then switch to the Public transport profile to calculate the same route, the route is successfully calculated without errors.
```

**Comment by alxmamaev** [comment]
Im really confused about why is this issue mention as complete when it is still there

**Comment by alxmamaev** [comment]
@vshcherb Im really confused about why is this issue mention as complete when it is still there

**Comment by alxmamaev** [comment]
@vshcherb For example, there many buses between this two points


Железничка станица терминал
Location: geo:45.26519,19.83004?z=20
https://osmand.net/map?pin=45.265188,19.830038#20/45.2652/19.8300
The location was shared with you by OsmAnd


And 

Булевар ослобођења - Футошка пијаца
Location: geo:45.25247,19.83690?z=18
https://osmand.net/map?pin=45.252474,19.836899#18/45.2525/19.8369
The location was shared with you by OsmAnd


Even in osmand itself I can find the route by the list the busses passed by this stops, but OSMand itself cannot. 
That's fresh installed app from AppStore, there no special needs to test it. Can you please check it?
Im really sad with this, because im paying for osmand and navigation feature just does not work for the last 3 months.
![image](https://github.com/osmandapp/OsmAnd/assets/17113191/8da86b23-9bb8-4a95-9c0d-25036371930d)

**Comment by helloyanis** [comment]
@alxmamaev I agree, it feels like it got closed because there is a workaround to avoid the bug if I understand right?
Yes, switching to another profile and letting it calculate then switching back to public transport works, but that's not how it's intended to be so I think this should still be open
Plus, the workaround also crashes the app once you click on "Details" of any of the results, but let's focus on one problem at a time, I'll open an issue if that's still a thing after this one is fixed (if it does)

**Comment by helloyanis** [comment]
@alxmamaev I agree, it feels like it got closed because there is a workaround to avoid the bug if I understand right?
Yes, switching to another profile and letting it calculate then switching back to public transport works, but that's not how it's intended to be so I think this should still be open
Plus, the workaround also crashes the app once you click on "Details" of any of the results, but let's focus on one problem at a time, I'll open an issue if that's still a thing after this one is fixed (if it does)

**Comment by alxmamaev** [comment]
For me switching between profile is no working btw, even if its works, that's not how bugs should be solved

**Comment by alxmamaev** [comment]
So @vshcherb I think that issue should be re-open until it actually will fixed. Searching by buses was one of the main factor to choose Osmand over than organic maps, and right now seems that functionality just does not work on many devices.

**Comment by vshcherb** [comment]
You're mixing 2 issues up, iOS issue is here https://github.com/osmandapp/OsmAnd-iOS/issues/3695, Android issue is  reproduced in a very specific case that probably doesn't make sense to fix

**Comment by alxmamaev** [comment]
Ok, got it, my fault
