### ISSUE TITLE
Pleas chache already calculated routes

### ISSUE THREAD

**Issue by Mannshoch** [osmandapp/OsmAnd#19849]
### Describe the idea (required)

- If a route is calculated, cache it for later use. 
- Split the route into. local to speedway, speedway and speedway to local. (if a speedway is included)
- In background calculate, with low priority, the backward route also. (check if differences appear)

### Tell us about the expected behaviour (required)

- first calculation takes it's time, second is instant here.
- if you modify your route, it use the already calculated route, for the first show. After that do a refinemend if needed.

### Tell us about alternatives you've considered (required)

no idea, except to calculate it first time with google.

### Context (optional)

Osmand is not best for planing long trips. I have less Problems with waiting once several minuts until complete. But do waiting after every modification, that is frustrating.

**Comment by sonora** [comment]
Do you use the latest maps, and the HH C++ routing type (under Navigatiion settings of your car profile)? Because 'several minutes' should actually be a ghost of the past now, I experience even 600km routes being calculated in like 30 sec.

**Comment by Mannshoch** [comment]
I do not find a setting called hh c++:
on fdroid I was on 4.6.14 and I updated now to 4.7.10

**Comment by DmitryAlexei** [comment]
@Mannshoch please enable the development plugin (go to menu > plugins)
