### ISSUE TITLE
Short way depends on maximum speed bicycle navigation 

### ISSUE THREAD

**Issue by JuergenMasch** [osmandapp/OsmAnd#19846]
### Description

I just discovered that the speed setting under Navigation–Settings – Vehicle Parameters has a big impact on the route.

### Steps to reproduce

The route for the shortest distance from Hamburg, Leverkusenstieg 32 to Eppendorfer Weg 159 with the setting 5/14/17 km/h is 3,82 km.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/167891617/e9f0be4b-6fb2-4092-a4d1-10d6502990f4"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/167891617/f101c5cc-55e6-456c-9964-f9e8c94b9486"  width="300" height="auto"/> </th>
  </tr>
</table>

### Actual result

If I reset the speeds to the factory settings (5/10/33 km/h), I get a very unfavorable route suggestion for the shortest route (4,56 km). 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/167891617/0a57c7b2-39df-4e3f-ae52-55eee1367c00"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/167891617/d01f8bb0-5df7-43db-8539-12a3e26dde8f"  width="300" height="auto"/> </th>
  </tr>
</table>

### Expected result

That doesn’t make sense! The route suggestions, especially for the shortest distance, must be independent of the speed settings.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
You should customize the bike parameters based on your specific needs. The maximum and minimum speeds are utilized to determine which roads are selected.

- The Minimum Speed setting establishes the minimum driving speed applicable to all road types on the route. This setting prioritizes roads with recommended speeds below the minimum speed.
- The Maximum Speed setting defines the maximum permissible driving speed and deprioritizes roads with potential speeds exceeding this limit.

https://osmand.net/docs/user/navigation/guidance/navigation-settings#road-speeds

**Comment by vshcherb** [comment]
Short way uses the maximum speed of 15 kmh (private static final float BICYCLE_SHORTEST_DEFAULT_SPEED = 15/3.6f;), so making it lower it could affect shortest route

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. Speed settings really affect the distance of the route.

In the first test, with Vehicle Parameters set to 5/14/17, the Balanced and Shorter Routes driving styles calculated a route of 3.69 kilometers.

In the second test, with Vehicle Parameters set to the default 5/10/33, the Balanced driving style calculated a route of 3.89 kilometers, and the Shorter Routes driving style calculated a route of 4.35 kilometers.

However, the route time for Shorter Routes is consistently shorter, regardless of the distance.

OsmAnd~ 4.8.0#2362m, released: 2024-05-21

<table style="width:100%">
  </tr>
  <tr>
    <th>5/14/17</th>
    <th>Balanced</th>
    <th>Shorter Routes</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/360ea170-82dc-424b-b191-e73188c8bfdd"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/861727d0-0f26-4284-9edd-d33ea244fcbc"  width="300" height="auto"/> </th>
  <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/8851cf60-52a2-4c04-9024-4daff87189dc"  width="300" height="auto"/> </th>
  </tr>
</table>

<table style="width:100%">
  </tr>
  <tr>
    <th>5/10/33</th>
    <th>Balanced</th>
    <th>Shorter Routes</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/21c49db0-fe8e-405d-96eb-18db8712ce55"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/89b168cb-3fa3-4a8a-9c91-073a31db4a36"  width="300" height="auto"/> </th>
  <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/6b10b188-9624-47ba-85cf-f823336f58ff"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
We are not going to fix cause it's reduces functionality.
1. If you really need to shortest route, you need to set min=max speed
2. Default settings find the shortest route still prioritizing cycleway vs generic roads, so it's technically better
