### ISSUE TITLE
Feature request: Allow user to attach an existing file to a point on map

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#1984]
Currently OsmAnd allows us to attach a audio/video/photo to any point on map.
This is excellent, and has several uses.

But there is a inexplicable limitation: All this content has to be freshly generated.

Why can't we attach a previously created file to the point?
(and that could be any type of file: a photo, audio file, video file or a pdf.)

A typical example is a file (photos, notes, anything!) created by a friend who visited the place earlier.

**Comment by sonora** [comment]
No action planned, it seems. (?)
