### ISSUE TITLE
'Manage Tracks' menu item

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#19850]
Quite a few users enter the Tracks screen via 'Configure maps>Tracks', and there have no way to discover or change over to our 'Manage tracks' screen 'MyPlaces>Tracks'.

This could be fixed via in the 3-dots menu of the 'Configure map>Tracks' adding an menu item 'Manage tracks'.

**Comment by vshcherb** [comment]
There is 'Visible on map', so I see no point in this

**Comment by sonora** [comment]
Not sure we're talking about the same: When from the map screen you tap "Menu > Configure map > Tracks", you end up on the "Visible on map" tracks screen ok.

But it's a dead end, from there you cannot go to the "Manage tracks" screen?

(Unless you **came from there**, that gap we had closed here: https://github.com/osmandapp/OsmAnd/issues/19257. But the fix applied there only works if you came via "MyPlaces > Tracks", it fails if you come via "Configure map > Tracks".)

**Comment by sonora** [comment]
Yes, true, it's clear for some. Some others are surprised by the concept that we a have two screens
- to manage Favorites, and control their visibility,
- to manage Tracks, and control their visibility, etc.

**Comment by vshcherb** [comment]
Well that's the whole story. Configure Map to manage visiblity on the map, My Places (My data) to manage data itself. So if it's an issue, it's definitely not only for Tracks but for all data.

**Comment by sonora** [comment]
Yes, the more complex way to deal with this is to unify the screens, like some apps do. The easier way for us at this point is to somehow interlink these screens for better discoverability, via some "Manage..." button or menu item.

It's also not a big deal if we stay put doing nothing at this point - I had just raised this because on and off, but rather consistently, I receive user feedback in trainings about this...
