### ISSUE TITLE
Feature request: OsmAnd should be able to load a location from clipboard

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/OsmAnd#1985]
Hi

Sometimes neither OsmAnd nor Nominatim are able to find a location. In such cases, the best way is to use Google search, find the location link and then onwards use it in OsmAnd. 

But OsmAnd cannot use a location link that is on clipboard.

Please provide this facility.

**Comment by DaMonk45** [comment]
That would help a lot for searches.

**Comment by ADepic** [comment]
Couldn't you copy the longitude and latitude for the location and paste into osmand?

**Comment by under-score** [comment]
+1

**Comment by raindropsfromsky** [comment]
Checked this now, and the plus coordinate works.
