### ISSUE TITLE
Show location on Google Maps

### ISSUE THREAD

**Issue by Biker729** [osmandapp/OsmAnd#19857]
### Describe the idea (required)

A quick change from OsmAnd to Google Maps and back to OsmAnd, is that possible / feasible ?

<img width="284" alt="1" src="https://github.com/osmandapp/OsmAnd/assets/146021011/89f6b19e-4109-4226-9d83-7aa118219db3">

<img width="283" alt="2" src="https://github.com/osmandapp/OsmAnd/assets/146021011/cf0942d4-c4d0-4ee1-8b65-69b9564be8be">

and back from Google Maps to OsmAnd

 
<img width="287" alt="3" src="https://github.com/osmandapp/OsmAnd/assets/146021011/16b74e0b-737d-4598-92d9-dde37c1a3eaa">

<img width="281" alt="4" src="https://github.com/osmandapp/OsmAnd/assets/146021011/ba1d5fc0-8d0a-49bc-8c26-74d02ed1dbfb">

<img width="259" alt="5" src="https://github.com/osmandapp/OsmAnd/assets/146021011/1fee83b2-e55e-43b6-b896-52cf30111731">

### Tell us about the expected behaviour (required)

A quick switch from OsmAnd to Google Maps to select a favourite 
and add it to the OsmAnd map.

### Tell us about alternatives you've considered (required)

From Google Maps directly back to OsmAnd without the Map2Geo app would be better.

**Comment by dmpr0** [comment]
I think it can be partly achieve after implementing this task https://github.com/osmandapp/OsmAnd/issues/17727

**Comment by pebogufi** [comment]
I can use Gockel Satelite with overlay. 
I suppose it should also be possible to use G Maps. Somebody should create the script for calling, thats all.

**Comment by scaidermern** [comment]
You can share a position with the share action ("Teilen"). Then select "geo". A list of apps should appear that can handle this geo intent, with Google Maps among them.
