### ISSUE TITLE
Issue with phone nr in poi details

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/Osmand#1986]
If the is no international nr like +49 for Germany in front the phone nr osmand don't recognize it as phone number. You can't click it to dial the nr. like with the international nr. 
![screenshot_2015-11-28-11-38-54](https://cloud.githubusercontent.com/assets/11144987/11451413/b3ce8556-95c5-11e5-82a7-a08d06db7cbd.png)

![screenshot_2015-11-28-11-47-10](https://cloud.githubusercontent.com/assets/11144987/11451415/cab9b916-95c5-11e5-9f97-875b7fa67ed8.png)

Greetings Simon

**Comment by crimean** [comment]
Could you please give us exactly POI where it does not work?

**Comment by jf-simon** [comment]
Pizza Express Da Mario
Position: geo:48.527733,8.562641?z=17
http://osmand.net/go?lat=48.527733&lon=8.562641&z=17

This one. But maybe I added the +49 for Germany

And
Pizzeria Bella Italia
Position: geo:48.526085,8.564529?z=18
http://osmand.net/go?lat=48.526085&lon=8.564529&z=18

**Comment by hakuchi** [comment]
this is a error in the OSM database.
If you find more of this phone numbers you can fix this by yourself, or report them to OSM.
In OSM you have to use international numbers.

for correct tagging of phone numbers reed this:
http://wiki.openstreetmap.org/wiki/Key:phone#Usage

Osmand wil not support regional phone numbers from all country's around the world.

**Comment by jf-simon** [comment]
I understand, but why not interpret all numbers tagged with phone:* as a phone number and add a link to the dialer app. I think a lot of phone numbers aren't tagged with international pre number.

**Comment by crimean** [comment]
Fixed

**Comment by jf-simon** [comment]
Thanks
