### ISSUE TITLE
Tapping "navigate home" at the homescreen symbol does...

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#19877]
### Description

) not _route_ home (shows just a straight line)
) not switch to the driving profile (but remains in the "view map"-profile

### Steps to reproduce

try it.

### Actual result

as I described.

### Expected result

do as the function says.

### Your Environment (required)

OsmAnd Version: +4.7.17
Android/iOS version: A13
Device model: S20+

![Screenshot Home](https://github.com/osmandapp/OsmAnd/assets/95540936/d8c9e8e4-f662-4abe-8829-00126babbb37)

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. Here are the steps to reproduce it:

- Attempt to add a Home tab in Navigation menu
- Fully close the app
- On the desktop, long-press the app until 'Navigate to Home' appears
- Click on this option and observe the outcome

In conclusion, navigation is calculated in a straight line from the point where you are to the point Home.

OsmAnd~ 4.8.0#2318m, released: 2024-05-16

https://github.com/osmandapp/OsmAnd/assets/127092082/45f48280-7d04-4345-b316-05a01504b9a1

**Comment by yuriiurshuliak** [comment]
The bug has been fixed. If you press 'Navigate to Home' on the desktop, the navigation will not be built in a straight line, but correctly.

OsmAnd~ 4.8.0#2559m, released: 2024-06-22

https://github.com/osmandapp/OsmAnd/assets/127092082/dc4fcac8-f40c-4a62-bc2e-cd949dd21985

**Comment by Rowin63** [comment]
I don´t know how to reproduce it, it "just happens":

A long tap at the app´s icon sometimes opens this:

![LongTap1](https://github.com/osmandapp/OsmAnd/assets/95540936/5d8175ba-7d7f-4752-8e98-2de0baf6446f)

Sometimes this:

![LongTap2](https://github.com/osmandapp/OsmAnd/assets/95540936/b11e7ae7-4adf-482f-96d1-98129326c927)

And only sometimes opens the correct option:

![LongTap3](https://github.com/osmandapp/OsmAnd/assets/95540936/b9766c3b-523c-454c-af43-cee12553482f)

+4.8.0 / Galaxy S20+ / A13 / media-path
