### ISSUE TITLE
Sat reception lost while on the MyPlaces>Tracks screen

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#19879]
Not sure this is a big issue but it may be in some cases:

I've noticed that OsmAnd loses satellite reception (Location) while on the MyPlaces>Tracks screen (at least if no foreground service like a track recording is active).

This does _not_ happen on the "neighboring" screens like MyPlaces>Favorites, or Configure map>Tracks, so it may be worth investigating and perhaps fixing.

To verify, watch the system's Location icon in the Android status bar disappear while viewing that screen, and upon returning to the map screen watch the GPS info widget initially showing 0/0, then rebuilding sat reception as if just turned on freshly.

**Comment by yuriiurshuliak** [comment]
When switching between favorites and tracks in MyPlaces, the system location icon in the Android status bar disappears and reappears.

OsmAnd~ 4.8.0#2309m, released: 2024-05-15

https://github.com/osmandapp/OsmAnd/assets/127092082/6d97e65a-e8e7-4035-8725-1479cfd15373

**Comment by vshcherb** [comment]
Well.. it's since beginning OsmAnd 2010 as My places still separate activity and not a fragment. I think it's ok for now however over time we might finally delete this activity and make it part of map. So I don't think it should be a dedicated task for that refactoring
