### ISSUE TITLE
Side effect while track appearance change 

### ISSUE THREAD

**Issue by Velomeloman** [osmandapp/OsmAnd#19885]
### Description

When changing the color of a track, all displayed tracks temporarily acquire the color type property of the selected color type.

### Steps to reproduce

https://github.com/osmandapp/OsmAnd/assets/109347561/65edb0ff-c601-4162-b667-9e61cbdff627

Example 1.
1) Open several tracks
2) Select one track
3) Open Appearance menu
4) Change Color from current to any another type (e.g. Surface)

_All tracks displayed will be shown with the surface color type._

5) Apply Appearance

Only selected track will be shown with the surface color type. It's correct.

Example 2.
1) Select another track with Solid color type
2) Open Appearance menu

_First track with Surface type color will be shown with the Solid type color_

3) Apply Appearance

First track will be shown correctly.

### Actual result

Description in _italics_ above

### Expected result

Only selected track change Appearance in preview 

### Your Environment (required)

OsmAnd~ 4.8.0#2315m, release: 2024-05-16

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. Here's how to reproduce it:

- Create multiple tracks in close proximity.
- Alter the display of each track with different colors.
- Attempt to change the color using options from the dropdown list (Surface, Slope).
- All tracks will display with the surface color type.
- Upon saving, all tracks revert to their original colors, with only the selected track displaying the surface color type.

OsmAnd~ 4.8.0#2330m, released: 2024-05-17

https://github.com/osmandapp/OsmAnd/assets/127092082/831626ac-7d3f-42d3-8b97-fe126c73111f

**Comment by vshcherb** [comment]
Summary: changing track appearance of 1 track shouldn't affect other tracks that are visible on map

**Comment by Corwin-Kh** [comment]
Can't reproduce at current version. (4.9.0#2909m)

**Comment by Velomeloman** [comment]
Confirm. Can't reproduce.

**Comment by yuriiurshuliak** [comment]
The issue is no longer reproducible in version 4.9.0.

OsmAnd~ 4.9.0#2909m, released: 2024-08-06

https://github.com/user-attachments/assets/81e09a3b-2bce-4f7d-9d86-bfc74adcf9a5
