### ISSUE TITLE
Release armv8 version

### ISSUE THREAD

**Issue by utack** [osmandapp/Osmand#1988]
Maybe in the future you could release a version that compiles all C parts of the app specifically for armv8, and is hopefully a bit faster on these devices.

**Comment by vshcherb** [comment]
Fixed with merge request in nightlies

**Comment by utack** [comment]
Did the build process not work out too well? (it was reverted a while ago)

**Comment by vshcherb** [comment]
Nope build process failed waiting for pull-request comment, we can track it.

**Comment by utack** [comment]
Any news on this?
