### ISSUE TITLE
To much text on small display depending on screen size ?

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#19880]
### Description

To much text on small display depending on screen size ?

Screenshots are from
Samsung Tab S5e, Android 10, 10,5" -- OK
Samsung S10, Android 12, 6,1"  -- To much text

same version OsmAnd~ 4.8.0#2308m, veröffentlicht: 2024-05-15
settings at both devices
Point labels OFF
Details, More Details OFF

![Samsung Tab S5e](https://github.com/osmandapp/OsmAnd/assets/18628183/e7da5f57-d3b6-4e59-bf6f-e3847dd83195)
![S10 OsmAnd #2308~01](https://github.com/osmandapp/OsmAnd/assets/18628183/597cec62-4af3-4e68-8a83-527fc70ff61e)

### Steps to reproduce

Just open
Edit: **It looks like "Point labels" is allway set to ON, changing this option does Not change this overcrowded texts.**

### Actual result

To much text on small display depending on screen size 
at Smartphone 6,1" screen

### Expected result

See screen of tablet Samsung tab S5ee

### Your Environment (required)

See above

**Comment by pebogufi** [comment]
One more example Gemany, Freoburg, 47.99636° N, 7.84920° E

![Uploading Screenshot_20240515_165004_OsmAnd~~01.jpg…]()

**Comment by pebogufi** [comment]
One more example Germany, Freiburg, 
47.99636° N, 7.84920° E

![Screenshot_20240515_165004_OsmAnd~~01](https://github.com/osmandapp/OsmAnd/assets/18628183/c787110c-0080-435e-a11c-950364ca5469)

**Comment by vshcherb** [comment]
Is this related to map magnifier ? 25% ?

**Comment by pebogufi** [comment]
No, 100.
It looks like "Point labels" is allway set to ON, changing this option does Not change this overcrowded texts.

**Comment by pebogufi** [comment]
Yes, you are right !!
I switched it on - not knowing what it makes, just to explore it...
But - what is this option good for ???

**Comment by pebogufi** [comment]
@Nine-Tailed 
Yes, you are right !!
I switched it on - not knowing what it makes, just to explore it...
But - what is this option good for ???
-
Sorry Victor, for bothering you

**Comment by Nine-Tailed** [comment]
> But - what is this option good for ???

there are two options related to the displacement of nearby poi and text.  This option may be useful for cartographers, as poi will not be hidden if they are close to each other.

**Comment by pebogufi** [comment]
Ahhh, thanks
