### ISSUE TITLE
Descriptions created for routes/tracks disappear after the route is closed

### ISSUE THREAD

**Issue by ETZ-Martin** [osmandapp/OsmAnd#19883]
### Description

Hello,

I would like to report an error that I noticed in the last few days when using **OsmAnd+ 4.7.17** under **Android 10**, **One UI version 2.5**.

**Error: Description of a route/track**

**Error Description:**
If I want to add a description to a created or recorded route, I first open it and then click on the “**_+ Add description_**” button (see red arrow in Fig. 1).

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/169939830/90ea8006-8ac7-448a-b0fb-ec7ec4561b30"  width="300" height="auto"/> </th>
  </tr>
</table>

The “**_Edit Description_**” window then opens in which I can enter the description (see Fig. 2). If I then click on “**_Save_**” (see red arrow in Fig. 2), the “**_Edit Description_**” window closes and I go back to the previous window.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/169939830/8bbf7986-5ba9-422f-926f-b30b700ba974"  width="300" height="auto"/> </th>
  </tr>
</table>

In this window, my added description is now displayed at the bottom under “**_Additional_**” (see red arrow in Fig. 3). However, unlike in previous versions of OsmAnd+, the description can no longer be opened and/or edited subsequently.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/169939830/865befc3-f5a1-4215-998d-0110bf93466f"  width="300" height="auto"/> </th>
  </tr>
</table>

**If I then close the route completely and hide it on the map interface and then reopen it, the description I entered has completely disappeared. This is the case with all of my routes recorded in the past -> the descriptions I entered earlier have completely disappeared.**
I hope that these have not been irretrievably deleted by the new OsmAnd+ version.

Best regards
Martin

### Steps to reproduce

See under Description.

### Actual result

See under Description.

### Expected result

I expect that the descriptions in all of my previously recorded routes/tracks will be displayed properly again and can be changed again if necessary.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.7.17
Android/iOS version: 10 One UI version 2.5
Device model: SAMSUNG Galaxy Note 9 (SM-N960F)
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
The bug was partially reproduced. Follow these steps to reproduce:

- Create a new track without a description.
- Add a description to the track.
- Attempt to edit this description; editing is not possible.
- Toggle the display of the track on the map off and then on again.
- Check the description; you should now be able to edit it.
- Edit the description and repeat the process of toggling the track display on and off.
- Review the track description again.

As a result, the original description will be displayed instead of the edited one.

OsmAnd~ 4.8.0#2318m, released: 2024-05-16

https://github.com/osmandapp/OsmAnd/assets/127092082/d7175ec9-3393-4fe5-8c77-ac3c38e16188

**Comment by sonora** [comment]
Possibly caused by https://github.com/osmandapp/OsmAnd/commit/0ef533484095afff347c765f4c78ac85d36472d8.

**Comment by sonora** [comment]
@vshcherb Perhaps here https://github.com/osmandapp/OsmAnd/blob/0ef533484095afff347c765f4c78ac85d36472d8/OsmAnd-java/src/main/java/net/osmand/gpx/GPXUtilities.java#L677 we should concatenate desc and readDescription rather than filtering a shift action to cases where desc is empty?

**Comment by vshcherb** [comment]
Hm... tricky... @sonora you didn't actually compared if they are the same, so it's possible to have "XXX;XXX". Do we really need to recover, it's a bit cumbersome of course due to this backward compatibility but probably based on your examples you have a right fix

**Comment by sonora** [comment]
It's true, but remember we are talking about rare cases here anyway, users who had performed manual edits, etc. I think it was urgenr to prevent any further data loss, from my point of view we are good now.  😢
