### ISSUE TITLE
The "MyPlaces>Tracks>Show on map" menu action does not switch to the map screen

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#19893]
Carryover from #19749 and also a previous discussion linked from there:

When on the 'MyPlaces>Tracks' screen in selection mode you tick some items, then select the menu action "Show on map", nothing visibly happens. (The items are correctly marked in the background, but the user stays on the same screen not noticing this or knowing how to proceed.)

As a result of tapping the "Show on map" action, users would like the app to change over to the map screen (and roughly zoom correctly) to display these tracks.

**Comment by sonora** [comment]
PS: Folder menu action "Show all tracks on the map" at least switches over to the "Visible on map" tracks screen with all selected items correctly ticked. Creating consistency with this behavior should be the very least.

**Comment by vshcherb** [comment]
That would require 2 actions probably go to map or stay on my places screen, I think consistency is important but now we provide 2 options so user can choose what his primary intent is.

**Comment by vshcherb** [comment]
I think here we could leave as it is... Not consistent but 2 options are provided
