### ISSUE TITLE
minSDK9 build has minor design flaw

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#1990]
Not a real issue, just for the record, I am aware we do not want to officially support it any more:

There are still a bunch of Android 3.x tablet users out there who desperately wanted the new release 2.2 functionality (primarily the context sensitive address display) on their devices. So for a laugh I generated a minSDK=9 version of our master for them, and it seems to work pretty flawlessly!

They have reported only 1 cosmetic issue so far: When the context menu comes on, the blue button with the "Direction" icon in it does not display on the top right corner of the context menu, but instead on the top right corner of the map screen (obstructing the right column of the map widgets there). The button is fully functional, though (and without the directions icon). So this seems a minor design flaw, but functionally they say they much prefer this over our old release 2.1, (where we still officially built for SDK9). Not sure if we want to consider producing one upgraded release for SDK9, also.

**Comment by sonora** [comment]
I just notice we do produce a build with minSDK=9, only save it in a different place ... :-)

Same issue I describe above: The blue button appears in the top right corner of the map screen, not of the context menu popup.

**Comment by vshcherb** [comment]
We still provide http://download.osmand.net/latest-night-build/OsmAnd-nightly-2.3.apk and quite regular fix issues related to 2.3, but there will be no official support in Google Play, so only in nightlies and it is own risk.
