### ISSUE TITLE
Can´t (re)name favorites.

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#19907]
### Description

Mark a spot on the map > add it as a favorite > delete the given name > now I can´t enter the name field anymore >>> can´t save the favorite without a name.

And it is also not possible to rename existing favorites. Can´t enter the name field.

### Steps to reproduce

do as I described above

### Actual result

can´t rename a favorite

### Expected result

I can change the automatic given name.
Once again, I´m preparing for a trip and again I can´t proceed my planning.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/95540936/69891236-5f7a-4a29-b819-fd61775596b9"  width="300" height="auto"/> </td>
  </tr>
</table>

https://github.com/osmandapp/OsmAnd/assets/95540936/bca0cb00-5de6-4014-be72-79e52c34cc81

### Your Environment (required)

OsmAnd Version: +4.7.17
Android/iOS version: 13
Device model: S20+

**Comment by Rowin63** [comment]
Tried it again, today it works as usual 🤔

**Comment by DmitryAlexei** [comment]
@Rowin63 Doesn't work with favorites made from .gpx file

**Comment by Rowin63** [comment]
Thanks for investigating!
Usually all my favorites are made/created by tapping/marking on the map. Sometimes I copy a favorite file from one device to the other, but I never had an issue with that.

**Comment by DmitryAlexei** [comment]
On the latest fresh nightly build cannot reproduce this issue anymore.
All types of favorites can be renamed without any issue.
