### ISSUE TITLE
Auto-record track doesn't start

### ISSUE THREAD

**Issue by bast69** [osmandapp/OsmAnd#19905]
### Description

Automatic recording of the track does not start.  I tried on different profiles, the result is the same.  I have uninstalled and reinstalled without success.
 On another phone, startup works.

### Steps to reproduce

Configure the plugin for automatic start.

### Actual result

When I launch navigation the recording does not start

### Expected result

Recording should start automatically 

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.7.17
Android/iOS version: Android 12
Device model: Poco X3 NFC 
Crash-Logs: ?
```

**Comment by pebogufi** [comment]
Yes I also had this or a similar problem days ago.
https://github.com/osmandapp/OsmAnd/issues/19845
Sometimes it works sometimes not.
Maybe the problem is:
On a hiking tour or biking i start recording then switch off screen. Later i switch on the screen, Sometimes recording has started sometimes not.

**Comment by bast69** [comment]
J'ai testé avec profil voiture, camion, vélo, pédestre.
Les paramètres sont définis comme sur l'image
![Screenshot_2024-05-19-14-42-03-147_net osmand](https://github.com/osmandapp/OsmAnd/assets/6906908/441bc1aa-4b91-4d91-beb0-a200cfd548f3)

**Comment by DmitryAlexei** [comment]
I didn't manage to reproduce this issue.
@bast69 please share your profile settings, and we will reproduce it again. Go to menu > settings > your profile > export profile. You can attach it to the message after adding .txt after file extension.

**Comment by bast69** [comment]
[Uploading Export_2024-05-21.osf…]()

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. When the automatic track recording function is activated and you proceed with the navigation, the track recording is initiated automatically.

OsmAnd~ 4.8.0#2370m, released: 2024-05-22

https://github.com/osmandapp/OsmAnd/assets/127092082/f571c51a-aa0f-480f-b6b8-b08ff82501ad

**Comment by bast69** [comment]
Here is an export of all my settings, hope it helps.
[Export_2024-05-22.osf.txt](https://github.com/osmandapp/OsmAnd/files/15408583/Export_2024-05-22.osf.txt)

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. First, enable the automatic track recording feature and set the default profile to "car." Next, try to enable navigation within the car profile. As a result, the automatic track recording does not start, and no track is recorded.

On the other hand, if you set a default profile other than "car," activating navigation within the car profile will automatically trigger the track recording without issues.

OsmAnd~ 4.8.0#2383m, released: 2024-05-24

<table style="width:100%">
  </tr>
  <tr>
    <th>Car - Default profile</th>
    <th>Car - Profile not by default</th>
  </tr>
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/3cf047f3-3525-4e62-82ba-f888d92bd160"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/96bdbc2d-8752-4d09-981d-27f408d38036"  width="300" height="auto"/>   </td>
  </tr>
</table>
