### ISSUE TITLE
Commit history question

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#19901]
I am currently a bit baffled why this commit to the master branch https://github.com/osmandapp/OsmAnd/commit/f1aa507175e4f549469c7734f46c3e5e093a70e2

![image](https://github.com/osmandapp/OsmAnd/assets/845735/0e431e84-5386-4ce9-9761-98d4e732d92d)

is not reflected in this commit's history https://github.com/osmandapp/OsmAnd/commit/290c953e1bd47fe8655f0b4b546d71c1605caaea, which leads to the comment added by @ivanPyrohivskyi  not being visible in our master branch now?

![image](https://github.com/osmandapp/OsmAnd/assets/845735/fa3fbeee-c3fd-423b-8a9b-0cff57ee9a92)

**Comment by ivanPyrohivskyi** [comment]
Comment is visible now in master
https://github.com/osmandapp/OsmAnd/blob/6d21ec8174d5fd7ac19c2d2bacc86584318ffa6a/OsmAnd-java/src/main/java/net/osmand/binary/CachedOsmandIndexes.java#L44

**Comment by sonora** [comment]
So what had happened, can anybody explain?

**Comment by vshcherb** [comment]
nothing, have no idea. Commit was merged from 4.7?

**Comment by scaidermern** [comment]
I haven't checked this particular example (I'm on a mobile phone right now) but git allows to perform changes _within a merge commit_ which you won't see when looking at the individual commits. You have to look at the diff of the merge commit instead.

This is a really strange and scary behavior of git in my opinion.

**Comment by vshcherb** [comment]
It's in master branch - git log -1000 | grep -A 5 -B 5 f1aa507175
```
commit f19be09322886d10e5fa6c711fdd5ce6df94d33e
Merge: f1aa507175 598a538632
Author: Victor Shcherb <victor.shcherb@gmail.com>
Date:   Fri May 3 17:11:07 2024 +0300

    Merge remote-tracking branch 'origin/r4.7'
commit f1aa507175e4f549469c7734f46c3e5e093a70e2
Author: ivanPyrohivskyi <ivan.pirogovsky@gmail.com>
Date:   Fri May 3 14:37:36 2024 +0300
```

I don't see anything strange. it was merged from r4.7 to master

**Comment by sonora** [comment]
Perhaps a UI peculiarity I fail to understand or glitch on github.com then. Because as you can see in the second screenshot I had provided above, the comments in code line t44 should have been present but are not reflected.
