### ISSUE TITLE
Map Radius Tool 

### ISSUE THREAD

**Issue by PietBlootvoet** [osmandapp/OsmAnd#19902]
We urgently need a map radius tool.  If I want to plan travels within a certain radius from a fixed point, I want everything within that radius to be lightly shaded.  For instance, I wish to see what lies within my car's fuel range of 1080km from Pretoria, South Africa.  The map radius tool should shade everything within that radius, or draw the radius or circle.

**Comment by sonora** [comment]
This already exists, try the radius ruler under 'Configure screen'.

(But before you run out of fuel unexpectedly: Drawing a circle on a map is in practice not too closely related to how far you can get on one tank of gas... 😉 )

**Comment by PietBlootvoet** [comment]
Hello

No, this radius ruler works with altitude in meters.  What one needs, is a radius that can display distances set by the user, for eg "256km from Cape Town."

**Comment by PietBlootvoet** [comment]
Can we get the map radius to stick to my departure point?  My area of interest moves off-screen, rendering it quite useless.

**Comment by DmitryAlexei** [comment]
Related issue
https://github.com/osmandapp/OsmAnd/issues/18229

**Comment by vshcherb** [comment]
Request is reasonable merged to https://github.com/osmandapp/OsmAnd/issues/18229
