### ISSUE TITLE
Wikipedia content skewed by Infoboxes

### ISSUE THREAD

**Issue by morray** [osmandapp/Osmand#1991]
Sometimes infoboxes skew the content of the wikipedia entries. For example Spanish at Lat 19.42861 Lon -99.16172 reads:in the preview:

right|225px|thumb|Reforma 222 Torre 1 a la izquierda, a la derecha Reforma 222 Centro Financiero.right|225px|thumb|Reforma 222 a la derecha y a la izquierda Edificio Reforma 222 Torre 1. right|225px|thumb|Complejo Reforma 222. 

El Reforma 222 Centro Financiero es un edificio que forma parte del com

**Comment by vshcherb** [comment]
Duplicate
