### ISSUE TITLE
Quick action to switch between Terrain styles

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#19916]
## Description

As we now have multiple terrain styles available it would be better to have a switch between styles similar  to switch between layers as we have for online map sources.

**Later**: quick action to switch road styles as well.

### Topography group, [Figma](https://www.figma.com/design/95sVxDjUfZ0afiW7XmTUYx/Configure-screen?node-id=1987-81776&m=dev)
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/b087e78b-21be-40b0-b3f5-834e243a8231"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Add new quick action `Change Terrain color scheme` to **Topography** group
- - [x] Icon – `ic_action_appearance`
- - [x] Visibility should be related to the group

### Change Terrain color scheme, [Figma](https://www.figma.com/design/95sVxDjUfZ0afiW7XmTUYx/Configure-screen?node-id=1987-77455&m=dev)

<table style="width:100%">
  <tr>
    <th>Terrain Color Scheme</th>
    <th>Add dialog</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/c32880f9-7c40-4554-8a56-a5a63730df44"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/929956f1-05eb-4813-998e-7ba3053dc1ba"  width="150" height="auto"/> </td>
  </tr>
</table>   

- [x] Should work the same as **Change Overlay Map action**
- [x] Allow to add list of color schemes to switch between

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.8.0#2539m, released: 2024-06-20 Works

**Comment by shurasmiling** [comment]
- [QA - Configure map](https://osmand.net/docs/user/widgets/quick-action#configure-map)
- [Topography plugin](https://osmand.net/docs/user/plugins/contour-lines#quick-actions-for-topography-layers)

**Comment by EugeneZmeuk** [comment]
**01.01.2024 Review**
- [ ] [Topography](https://osmand.net/docs/user/plugins/contour-lines/#quick-actions-for-topography-layers)
  - added links for each setting: "..[Contour Lines](https://osmand.net/docs/user/plugins/contour-lines/#contour-lines), Terrain layers, and Color palettes."
