### ISSUE TITLE
Glide Ratio widget shows (completely) wrong values

### ISSUE THREAD

**Issue by ManDay** [osmandapp/OsmAnd#19913]
I have no details yet, but trying the GR widget during a flight today it seemed that the values were **entirely** off. At a constant, prolonged sink of ca. 1 m/s and speed of ca 30 km/h it kept showing values of **minus 40**, and so forth. In fact, I wasn't able to discern an actual pattern, it was almost as if the GR values were random (though somewhat stable).

I'll provide some further diagnostics (possibly a GPX and video of the GR values, if I can manage) as soon as I can; in the meantime I thought I should open a bug for this.

**Comment by vshcherb** [comment]
Yes would be good. Minus 40 means that you were not descending... I have tested it during airplane flight 
[2023-08-13_16-38_Sun.gpx.zip](https://github.com/osmandapp/OsmAnd/files/15381191/2023-08-13_16-38_Sun.gpx.zip)


Please run this track simulation (developer settings) and check if you see something wrong with glide ration widget.

**Comment by ManDay** [comment]
I downloaded the Polish terrain map and ran the simulation; it looks similar to what I see in real life. The altitude decreases constantly but a GR of ca. -40 is advertised (btw: it shouldn't matter for GR whether I have 3D maps, right?):

https://github.com/osmandapp/OsmAnd/assets/1059827/03a3e72a-7bda-430c-9c0b-62a6dff03e4c

**Comment by vshcherb** [comment]
You should have 3D maps downloaded but not necessary enabled. You have only the average glide ratio but not the target. I have configured average glide ratio for 15 seconds and it displays correct positive numbers as plane is descending.

![telegram-cloud-photo-size-4-5940719556496572362-y](https://github.com/osmandapp/OsmAnd/assets/1042025/e8045f72-0520-4848-8177-3a539842a258)

**Comment by ManDay** [comment]
Okay, the wrong values come from the fact that I had a **30 minutes** GR timespan! With 15 Seconds I also get your values!

I think the algorithm for the GR calculation should be changed. Using a fixed timespan is often not helpful. I will propose a PR for that as soon as I can and I hope for your approval!

In the meantime may I suggest that the range for the duration be changed? GR for aviators is typically used to estimate the current sinking behaviour (which angle, how far will it carry) and this would typically average over something like 5 seconds to 1 minute, depending on the aircraft. For paragliding, for example, 15 seconds is already too long. I don't think a 60 minute average makes a lot of sense.

**Comment by vshcherb** [comment]
Well we need to change min / max value and obviously default to 15 seconds at least

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. To reproduce the issue, I imported the mentioned track, loaded the 3D maps, added the Glide Ratio Widget, and set the average glide ratio to 15 seconds. Consequently, the widget displays a positive value.

OsmAnd~ 4.8.0#2422m, released: 2024-05-31

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/80d0daa8-f141-470c-a2e9-959cd470b43e"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by ManDay** [comment]
Yes, there is no actual bug. It was just the setting of 30 minutes average which caused the problem.

Re "not using a fixed duration" average, retract my previous claim that I could come up with another solution. Even when I try to reasonably determine the GR by some other criteria (like speed or oscillation), it eventually all boils down to a single characteristic time, over which we pretty much have to average.

Surely though, the averaged times should be configurable to something like 1, 2, ... 60 seconds, though, as @vshcherb said.
