### ISSUE TITLE
Wikipedia language not setable

### ISSUE THREAD

**Issue by morray** [osmandapp/Osmand#1992]
It seems that the app shows the content of the article with the lowest alphabetical order ISO language code first. I.e if there is the en the fr and the es wikipedia it will show the English content. If de is added German will be shown first. Instead there should either be an easier way to switch in the preview, a menu which allows to define an order or a automatic selection by length and our region.

**Comment by sonora** [comment]
No, it should not be alphabetically, please try again! Instead: We had tweaked this quite a bit, I think what e have implemented is:
- The primary choice is your selected display app language (usually the device language)
- secondary choice is your selected map display language
- third choice is English
- only then any other language in which the article exists.

Or similar, I may not be 100% on the point with all 4 rules, but this is roughly how we did it, I think.

**Comment by morray** [comment]
Hm, could actually be. At least that set of rules also comes to the same result.
