### ISSUE TITLE
Repeted recalculation, turn command, next turn

### ISSUE THREAD

**Issue by thuryn** [osmandapp/OsmAnd#19921]
### Description

Navigation route for example with these points (car profile, offline maps, offline routing):
Start: https://www.openstreetmap.org/#map=19/50.01685/14.40234
End: https://www.openstreetmap.org/#map=19/50.20039/14.49740

I have three points:
1) when I go through the part highway exit, see:
![photo_2024-05-21_20-26-02](https://github.com/osmandapp/OsmAnd/assets/11028346/2d203f4a-d327-4fe5-86a3-98e7d2008b87)

it repeats all the time, that route is recalculated (is says 20x or something like that). The same problem when occurs when I start navigation on gas station and till I start to go, it repeats recalculation over and over again. The same problem in tunnel.

2) turn command when I have to exit highway (same picture) is keep right - but it's not keep right, it's really turn right. So first, it should consider that there is point called motorway_junction, second - it should consider the turn angle from longer distance.

3) When I'm passing this part of the road (again the same picture), the next turn is shown as the round about (at the end of the road). But there are some other crossroads on the way. It works generally this way - when calculated road are longer, it does not show next cross road turn but it shows major turn from main road after for example 1 km instead. But it would be useful to show next crossroad turn.

### Steps to reproduce

Just put the points from previous paragraph and start navigation.

### Actual result

Actual result is written in the first paragraph.

### Expected result

Expectešd result is written in the first paragraph.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.7.17
Android/iOS version: Android 14
Device model: Oneplus 9 Pro
Crash-Logs: no
```

**Comment by yuriiurshuliak** [comment]
Please indicate whether you use the GPX track for navigation. If you are using a GPX track, consider attaching it to the road. 

Additionally, please verify if you encountered any issues with the GPS signal.

You also have the option to select the distance at which the road will be recalculated. For further guidance, refer to the following link: [Navigation Settings Guide](https://osmand.net/docs/user/navigation/guidance/navigation-settings/#recalculate-route)

**Comment by thuryn** [comment]
> Please indicate whether you use the GPX track for navigation. If you are using a GPX track, consider attaching it to the road.
> 
> Additionally, please verify if you encountered any issues with the GPS signal.
> 
> You also have the option to select the distance at which the road will be recalculated. For further guidance, refer to the following link: [Navigation Settings Guide](https://osmand.net/docs/user/navigation/guidance/navigation-settings/#recalculate-route)

Good points:
1) I don't use GPX track
2) GPS signal is really good - you have clear view on the sky on a motorbike
3) Recalculation is set to 10m - yes, this could be a problem - GPS is not so precise maybe. I'll try to increase it.

**Comment by vshcherb** [comment]
- Route https://osmand.net/map/?start=50.016774,14.402304&end=50.200341,14.497664&profile=car#17/50.17385/14.45653

You should see Turn Slight right there (not keep right)

**Comment by thuryn** [comment]
I've tried to set the distance in Navigation Settings to 20 m and it seams it is better - I'll be testing it again in the next week.
What is not good - if you put destination next to roundabout (https://www.openstreetmap.org/#map=18/50.20212/14.49801), I see that next turn is roundabout on highway - but it should be the exit from highway and then next cross road etc. When I try to simulate the situation on Osmand it works fine. But on motorbike in real situation not. I'll try to record the screen.
Regarding the turn commands - maybe it says Turn slight right (I have it in czech), but it sould say something like "turn right", because it's really turn or leave the motorway on exit two or something like this.

**Comment by thuryn** [comment]
When I started to record screen to catch it it starts to work fine :-) Ok. There could be an option to show every crossroad on the way but this is not a bug it's a feature. Anyway I'm not satisfied with behaviour in tunnels - I'll try to record some screen casts and open separate bug for it (if it does not exists already.
