### ISSUE TITLE
Wrong city on addresses

### ISSUE THREAD

**Issue by wolfy1339** [osmandapp/OsmAnd#19930]
### Description

In the app, there seems to be an issue with displaying the proper city when you put down a marker when browsing the map.

The addresses and the city boundaries have not been changed recently.
Nominatim on the main OSM website can get the addresses just fine
![image](https://github.com/osmandapp/OsmAnd/assets/4595477/962fa525-8e32-43d9-9b38-64f155dec803)

What seems to happen is it is ignoring `addr:city`
I have the latest map updates, as well as live update downloads that are up to date.

### Steps to reproduce

1. Browse to 45.93918,-70.94224
2. Click anywhere in the vicinity to put a marker
3. Observe the city given is incorrect

### Actual result

The city listed is incorrect, it lists the next city over instead of the proper one.
It is not listing the city that is in `addr:city`

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/4595477/48a7b7b1-0261-456f-8376-7910f33c2c41"  width="300" height="auto"/> </th>
  </tr>
</table>

### Expected result

For the proper city to be listed on addresses

### Your Environment (required)

```
OsmAnd Version: 4.7.17
Android/iOS version: 14
Device model: Google Pixel 7 Pro
Crash-Logs: N/A
```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. If you navigate to coordinates 45.93919, -70.94177 and click on any nearby point (e.g., a church), the context menu incorrectly displays the city as La Guadeloupe. It should correctly show Saint-Évariste-de-Forsyth.

Here is the link to OSRM: [OSRM Link](https://www.openstreetmap.org/way/1155763341)

OsmAnd~ 4.8.0#2383m, released: 2024-05-24

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/92107fa6-3d8f-4164-92cd-283c91570362"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/6a6d4de2-5c9a-43cd-8dcd-217bb10776f8"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by wolfy1339** [comment]
This is also happening for another area
https://www.openstreetmap.org/way/99971378

The city is wrongly displayed as Sainte-Clotilde-de-Beauce when it should be Saint-Victor
![share_2072113227403384157](https://github.com/osmandapp/OsmAnd/assets/4595477/a4e501d6-1365-4c0e-b2ab-4e2458ec45d8)

**Comment by vshcherb** [comment]
https://nominatim.openstreetmap.org/ui/reverse.html?format=html&lat=45.93932&lon=-70.94170&zoom=&accept-language=en-NL,en,nl-BE,nl,en-US,ru,be Sainte-Clotide-De-Beauce (? can't find link in Nominatim... ) instead of Saint-Évariste-de-Forsyth 
https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=1155763341&class=amenity

**Comment by wolfy1339** [comment]
> This is also happening for another area
> https://www.openstreetmap.org/way/99971378
> 
> The city is wrongly displayed as Sainte-Clotilde-de-Beauce when it should be Saint-Victor
> 
> <table style="width:100%">
>   <tr>
> <th><img src="https://github.com/osmandapp/OsmAnd/assets/4595477/a4e501d6-1365-4c0e-b2ab-4e2458ec45d8"  width="300" height="auto"/> </th>
>   </tr>
> </table>

This is the nominatim link for this instance of wrong city: https://nominatim.openstreetmap.org/ui/search.html?q=46.14771%2C-70.90532

https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=99971378&class=amenity

**Comment by wolfy1339** [comment]
> https://nominatim.openstreetmap.org/ui/reverse.html?format=html&lat=45.93932&lon=-70.94170&zoom=&accept-language=en-NL,en,nl-BE,nl,en-US,ru,be Sainte-Clotide-De-Beauce (? can't find link in Nominatim... ) instead of Saint-Évariste-de-Forsyth https://nominatim.openstreetmap.org/ui/details.html?osmtype=W&osmid=1155763341&class=amenity

@vshcherb 
Those show as [La Guadeloupe](https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=8089954&class=boundary) in OSMAnd instead of [Saint-Évariste-de-Forsyth](https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=8089955&class=boundary) as mentioned https://github.com/osmandapp/OsmAnd/issues/19930#issuecomment-2129765089

While the second one I posted in https://github.com/osmandapp/OsmAnd/issues/19930#issuecomment-2192948481  shows as [Sainte-Clotilde-de-Beauce](https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=8055322&class=boundary) in OSMAnd instead of [Saint-Victor](https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=8090034&class=boundary)

I hope it clears up any confusion

**Comment by vshcherb** [comment]
https://www.openstreetmap.org/node/305550668 - is a quarter, so I think it's the same as https://github.com/osmandapp/OsmAnd/issues/19943.

**Comment by vshcherb** [comment]
Regarding Saint-victor I couldn't reproduce on website (where am I?) - 1. 298 str. Rue Principale city Saint-Victor dist=15 - https://osmand.net/map/#19/46.14765/-70.90545
So probably the issue is gone with map updates
