### ISSUE TITLE
Position point remains after previewing the graph

### ISSUE THREAD

**Issue by Velomeloman** [osmandapp/OsmAnd#19936]
### Description

https://github.com/osmandapp/OsmAnd/assets/109347561/9451a8ae-e969-4a04-a985-55c1f7cfd078

### Steps to reproduce

1) Open track editing mode (plan a new route or edit existing track). 
2) Open Graph. 
3) Swipe your finger across the graph to see a point on the track.
4) Save result or Exit without saving.

### Actual result

The blue point is still displayed on the track

### Expected result

The blue point is no longer displayed

### Your Environment (required)

OsmAnd~ 4.8.0#2369m, released: 2024-05-22

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce it, try to create a new track ccess the graph, and drag on it until the blue position icon becomes visible. Upon saving the track, the blue icon persists on the track.

OsmAnd~ 4.8.0#2383m, released: 2024-05-24


https://github.com/osmandapp/OsmAnd/assets/127092082/b9536c5a-4180-452b-9937-84ca63174a78
