### ISSUE TITLE
Option to create multiple obf in parallel

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#1993]
Could we have an option in OsmAndMapCreator to create multiple `obf` in parallel?
For example, I have a directory full of `pbf` files and I would like to have them processed in parallel.
Since OsmAndMapCreator is CPU bound, processing one `pbf` at the same time with each available CPU in my machine should bring a great improvement in total time.

As it is now, when running in batch mode it is only possible to process them sequentially (one at a time)

**Comment by vshcherb** [comment]
Nothing stops to run multiple processes with new comand line utilities.bat/sh it is very-very easy to process obf.

**Comment by naoliv** [comment]
I mean when using MapCreator in batch.
I have 32 PBF files in one dir and I run MapCreator in batch mode (using a modified `batch.xml`), but it process them sequentialy, one by one.

I didn't try it, but reading `utilities.sh` it seems that it runs the MapCreator  in UI mode?

**Comment by vshcherb** [comment]
nope it runs exactly as batch one and it is much easier for scripting then batch creator which we use for server operations
