### ISSUE TITLE
Let users choose fonts

### ISSUE THREAD

**Issue by Vucumpra** [osmandapp/OsmAnd#19938]
### Describe the idea (required)

Let users choose fonts by importing MyFontsFamily.ttf

### Tell us about the expected behaviour (required)

In "general Setup"

### Tell us about alternatives you've considered (required)

Alternative is put files.ttf on hardware memory but Android don't let this :(
Another alternative is use semi-condensed font for all osmand.

**Comment by DmitryAlexei** [comment]
Partially duplicate of https://github.com/osmandapp/OsmAnd/issues/19123
