### ISSUE TITLE
Japanese appearing as empty boxes.

### ISSUE THREAD

**Issue by dsbrooks** [osmandapp/Osmand#1994]
I'm using the F-Droid version on the latest Cyanogen Mod nightly on my Nexus 5, but I've confirmed it in the Google Play version as well running stock Android.

There are other examples around the map, but I've added these personally so I'm using them as the example. The text here shows up as empty white boxes like it should.

Attached is a screen shot from my phone as well as one from the web.

![osmand-report-android](https://cloud.githubusercontent.com/assets/642495/11454792/17135588-967f-11e5-915c-de804278cae3.png)
![osmand-report-web](https://cloud.githubusercontent.com/assets/642495/11454791/170fa6d6-967f-11e5-82a3-3eff3835790d.png)

**Comment by vshcherb** [comment]
Duplicate issue in progress.

**Comment by dsbrooks** [comment]
Sorry! I couldn't find a similar issue. Would you mind linking to the duplicate?

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/issues/1161
