### ISSUE TITLE
remove (rejected) tourism=lean_to from presets

### ISSUE THREAD

**Issue by osmtools** [osmandapp/OsmAnd#19949]
### Description

In https://www.openstreetmap.org/node/4730429495/history you can see, that current OsmAND still uses `tourism=lean_to` which is [rejected](https://wiki.openstreetmap.org/wiki/Proposal:Lean_to). I think #16083 isn't fixed.

### Steps to reproduce

add POI, type `lean to`

### Actual result

proposed tag: `tourism=lean_to`

### Expected result

proposed tag should be: `amenity=shelter` `shelter_type=lean_to`

### Your Environment (required)

none environment

**Comment by xmd5a2** [comment]
Map rendering and POI was updated. Map to test: Germany_thueringen will be available today.
https://www.openstreetmap.org/node/4730429495/history
However we currently don't have mechanism to propose more than 1 tag in POI editor.

**Comment by DmitryAlexei** [comment]
Android OsmAnd~ 4.8.0#2491m, released: 2024-06-12 and iOS TestFlight 4.7.7.3
Tested on this POI https://www.openstreetmap.org/node/7760890347 with fresh June maps
- object tagged tourism=lean_to are shown on the map (**OpenStreetMap doesn't render objects with this tag**) in both Android and iOS apps. Tag lean_to is transformed to amenity=shelter. Later (with May maps) lean_to objects were not seen on the map (see screenshots)
- when creating a POI, tag tourism=lean_to is not proposed anymore.

Screenshots from iOS; the same for Android.
<table style="width:100%">
  </tr>
  <tr>
    <th>May map</th>
    <th>June map</th>
    <th>Creating POI lean_to</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/9fcc4bdb-f98f-4cb6-9acc-daf8379f3583"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/725407b0-a80d-40fc-8735-9604caf95b2a"  width="300" height="auto"/> </th>
  <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/8b46e04d-8d48-46f0-a520-b844c3532bd8"  width="300" height="auto"/> </th>
  </tr>
</table>
