### ISSUE TITLE
playing golf? , improving map colors and visibility of golf courses.

### ISSUE THREAD

**Issue by T40M** [osmandapp/OsmAnd#19956]
### Describe the idea (required)

just started working on a golf course, du to the size of the golf course im still not know all the ways and hols by name. thats why i tried using OSMand on the golf course, and were i found this bugg.

Disclaimer:
the map of the golf course on OpenStreetMap map is not great ass wel (im working on that one to improve it on OpenStreetMap editor) but i can't change the way OSMand read the information from OpenStreetMap.

Non of the available map layouts give useful visibility of the golf courses. bunker's ar green (please make them yellow/with) the green have to light color to see it next to the gras of the fairway. on OpenStreetMap.org its bright green. i think that is much better.

I love using this app hiking and cycling,
maybe you can make is great for golfing as wel. only neet a small improvement of the colors.

just go to a few random golf course on the OSMand+ app and you will see wat i mean.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/170854992/4e0c0ed3-27ad-4424-a17b-de76a551dafd"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/170854992/7a9de55b-c0ee-4467-aeeb-1023d0044510"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/170854992/8e8aad7f-df7d-4334-83da-bb04c0bb1fa5"  width="300" height="auto"/> </th>
  </tr>
</table>

the split window screenshots ar on thop OpenStreetMap.org WebViewer.
down it OSMand+ app in the two different map layouts. (the ones i can see the most of the golf course.

### Tell us about the expected behaviour (required)

i expected that the bunker's where yellow withe like on. fairway clearly visible different type of green than the reuff or the semi reuf (grasland on the open steet map map data, no semi reuf)

### Tell us about alternatives you've considered (required)

different color for golf specific grasslands.

**Comment by sonora** [comment]
Here's the mapping info and rendering suggestion (in section "Features within a golf course"). Very likely, many of the features would need inclusion in our obf files first, so I can't fix on the fly, I think.

**Comment by xmd5a2** [comment]
Fixed. New maps will be available in a couple of days.
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/f77011c0-fc32-463c-8d64-c36a97e6c86c)

**Comment by T40M** [comment]
Hi
 
thank to everyone working on the improvement's.

i do probably something wrong.

![Screenshot_20240727-010118](https://github.com/user-attachments/assets/291784ab-8613-48ea-9416-2842e497aa03)

i went to the same spot as @DmitryAlexei.
and this is wat i see in the OSMand app for Android.
i can't find the setting that probably make this difference.

please help.

**Comment by vshcherb** [comment]
Which map style do you use?

**Comment by T40M** [comment]
> Which map style do you use?

thank you for your reply,

its solved now very happy with it.
it works on most map style

i use different map style in my profiles, (walking, cycling and so on)

OSM carto use for most of them. for cycling i use the cycle map,
