### ISSUE TITLE
OsmAnd using lots of unexplainable mobile data (4G) 

### ISSUE THREAD

**Issue by 5a54a** [osmandapp/OsmAnd#19959]
### Description

Status and observations:
- Using prepaid simcard with limited 4G data available;
- Using OsmAnd (Fdroid) with an imported GPX track for cycling;
- OsmAnd is using precise location permission (not approximate location permission);
- Mobile data is enabled during ride (for receiving emergency IM-messages);
- Total (all apps, all periods) used 4G data before cycle-ride: 3MB;
- During ride received notifications that 90MB (this warning has been put by me to prevent accidental high data usage) data has been used, after ride (max. 1,5 hour) total used _only_ by OsmAnd was 103MB;
- No maps (or other resources such as voices) were downloaded or updated during the ride;
- Live-updates is not enabled.

Questions:
1. What is causing OsmAnd to use this much mobile 4G data?
2. Is it possible that A-GPS (assisted GPS) is using this much data and how is this possible when using the Fdroid version of OsmAnd? (Using the Fdroid version it is not possible/available to select location services, and I assume it is using Android API version)

### Steps to reproduce

- Go ride with 4G mobile data enabled
- Observe data usage by OsmAnd (as shown in Settings - Network and Internet - Mobile Network - Data usage of app - OsmAnd: 103MB)

### Actual result

Lots of 4G data usage while no map download or live updates are done/enabled.

### Expected result

Do not use mobile data when no maps are being downloaded and also no live updates are enabled.

### Your Environment (required)

OsmAnd Version: 4.7.10 (Fdroid)
Android/iOS version: Android 12
Device model: Crosscall Action-X5

All Google options have been disabled and all Google apps (including Google Play Services) have been disabled on this phone before installing any new apps (all from Fdroid), such as OsmAnd (also from F-droid).

**Comment by scaidermern** [comment]
Do you have an online map or other map overlay/underlay enabled, instead of or additionally to a vector map?

**Comment by 5a54a** [comment]
Currently only the following plugins are enabled: Wikipedia and Topography. Could be that "Weather" was also enabled (not entirely sure) during ride. I think "Online maps" plugin was also not enabled during ride (disabled by default, I presume). Does "Weather"  plugin use mobile data?

**Comment by sonora** [comment]
It's definitely not normal. I have just checked my OsmAnd's Mobile Data Usage **for the entire month**, and it is at 2 MB.

**Comment by DmitryAlexei** [comment]
@5a54a Please close the *Online photos* tab in the POI Context menu (see screenshot). That should prevent additional data usage along your route.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/d2db381c-d26f-4dcb-95c0-3bb21ca72035"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
Unfortunately we didn't reproduce the issue
