### ISSUE TITLE
Nursing home Icon missing

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/Osmand#1995]
See screenshot
![screenshot_2015-11-29-02-05-11](https://cloud.githubusercontent.com/assets/11144987/11454820/dc258ca2-963d-11e5-99bf-c969ba233b53.png)

Getting Simon

**Comment by jf-simon** [comment]
Also Metal construction craft Icon
![screenshot_2015-11-29-12-28-25](https://cloud.githubusercontent.com/assets/11144987/11456788/d73f8e02-9694-11e5-97ae-e56c1d73c0f5.png)

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/issues/1998#issuecomment-160482948 
Basically same comment here.

**Comment by xmd5a2** [comment]
It is ok, icons for nursing home disappeared because they are now converted to amenity=social_facility + social_facility=group home. They'll back with forthcoming maps update.

**Comment by jf-simon** [comment]
Thank You
