### ISSUE TITLE
TTS: Destinations listing cut (probably because of slash '/')

### ISSUE THREAD

**Issue by vmicho** [osmandapp/OsmAnd#19957]
### Describe the routing engine used (required)

- [ x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Describe your routing Profile (required)

The reading of destinations is cut.
I observed the problem on when one of the destiantions is 'Biel/Bienne'.
On openstreetmap all looks OK. Even the destination:ref tags are not present

![Screenshot_20240526-133136_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/66125746/710b6f59-dff9-4130-b2c8-62b23f95bce4)
Here the reading stops after "Biel" (Bienne is omitted)
when turning onto: https://www.openstreetmap.org/way/307451529
route: https://osmand.net/map/navigate/?start=46.968909,7.460130&end=46.972354,7.471350&profile=car#16/46.9709/7.4626

![Screenshot_20240526-134913_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/66125746/cf402de0-e14e-451c-8837-445109d471df)
It reads "turn slightly right onto exit 38, towards A6, Biel Bienne" (Schonbuhl is omitted)
when turning onto: https://www.openstreetmap.org/way/4482242
route: https://osmand.net/map/navigate/?start=47.008203,7.496409&end=47.011952,7.497573&profile=car#17/47.01018/7.49699

Here are used destination (which I suppose should be read) "Biel/Bienne;Schönbühl", destination:ref="A6" (OK, shown and read)  and destination:lanes="Biel/Bienne|Biel/Bienne;Schönbühl;Einkaufszentrum" (which is useless(?) here when turning onto it, this is more like what will come next)

All destinations are correctly shown on top of the screen. It's just the are not all read.
My suspicion is the slash character (might escape something?)

### Describe your start and end points (required)

included in description

### Describe the actual route (required)

route is OK

### Describe the expected route (required)

in description

### Describe what Maps you used (online or offline) (required)

- [x] Offline maps offered within the OsmAnd app for download. 
- [ ] Online (tile / raster) maps 

### Your Environment (required)

```
OsmAnd Version: 4.7.10 - 2024-04-18
Android/iOS version: 12 (lineageos 19-20230722)
Device model: xiaomi mi10T
```

**Comment by sonora** [comment]
Yes, a lot of TTS engines have issues with slashs, at least used to, some time ago.. But from what I see, we replace by a comma before passing it on. Will need Investigate closer , at first sight it's odd.

**Comment by sonora** [comment]
Fixed here: https://github.com/osmandapp/OsmAnd/commit/ec91a7159c0fda86a32c435fb6ca74b570c6d723. Thanks for reporting!

**Comment by vmicho** [comment]
wow that was fast. From the commit, it looks like reasonable fix ;)
