### ISSUE TITLE
MyPlaces>Tracks screen's Search is buggy

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#19953]
The search for tracks fails if not started from the Tracks root folder.

To verify: In your Tracks folder, have subfolder A, which contains a subfolder B, which again contains tracks.

If on MyPlaces>Tracks you are in OsmAnd's Tracks root folder and search for name portions of the tracks in folder B, they are found ok.

But if on the MyPlaces>Tracks screen you first switch to folder A, or even to folder B, before tapping the Search (magnifying glass) button, they will not be found.

It seems this may be due to a buggy "Folder" filter being set in these cases, as such a "Filter=1" is indicated top right on the Search dialog. That filter has problems, it shows e.g. the current folder selected, but ignores files and folders it contains. Contained folders are listed separately, and are unselected.

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. When you create a folder and add multiple subfolders with tracks inside, the tracks won't be directly searchable within those subfolders.

OsmAnd~ 4.8.0#2400m, released: 2024-05-27

https://github.com/osmandapp/OsmAnd/assets/127092082/dfe80598-9d5c-4558-9ee9-7bcea6daeb20

**Comment by dmpr0** [comment]
# Review
- [ ] ToDo is missed
