### ISSUE TITLE
Editing contourlines.addon.render.xml file to give a custom color to contour lines does not fully work.

### ISSUE THREAD

**Issue by patdu1** [osmandapp/OsmAnd#19958]
### Description

With the attached contourlines.addon.render.xml file (had to zip it to upload) when selecting my custom color (magenta) only the text (elevation) is displayed with the proper color, the lines keep their brownish (default?) color, as seen in the screenshot (color_issue.png).
[contourlines.addon.render.zip](https://github.com/osmandapp/OsmAnd/files/15447697/contourlines.addon.render.zip)

### Steps to reproduce

Trying to understand what mistake I made I finally found that the contourline colors are also defined in topo.render.xml, and it seems that the values coming from this file take precedence over the ones from contourlines.addon.render.xml
In the attached topo.render.xml I commented out some lines defining the attribute contourLineColor (see comments labeled with PAT) and one line using the $contourLineColor value.
After these edits I get the expected contour lines color (see screenshot color_OK.png).
The topo.render.xml contains several additional occurrences of contour line or text color definition, but always in commented out blocs, so I think that the block that I had to comment out had just been missed so far...
Regarding the single line using $contourLineColor I had to take it out because otherwise Osmand would crash, but I have no idea about the real impact on other parts of the application.
[topo.render.zip](https://github.com/osmandapp/OsmAnd/files/15447711/topo.render.zip)

Finally one more point that I don't understand, but it's only cosmetic: in the render file the color names are defined in lowercase but in the Osmand window they appear with the first letter capitalized... except for the additional custom color I added into contourlines.addon.render.xml (see color_menu.png). Are these color names defined somewhere else again? This is just a cosmetic point, it doesn't impact the functionality.
![color_menu](https://github.com/osmandapp/OsmAnd/assets/66574244/19cecd64-dda7-4c66-b444-aac7f32c3606)

### Actual result

Magenta elevation text and brown contour lines
![color_issue](https://github.com/osmandapp/OsmAnd/assets/66574244/40669bb5-9d97-4ac5-b3df-68091936ceb7)

### Expected result

Magenta contour lines & text
![color_OK](https://github.com/osmandapp/OsmAnd/assets/66574244/d2b741e7-00a1-4639-be8e-d46243620cc4)

### Your Environment (required)

Osmand version: 4.7.17 (SRTM plugin activated)
Android version: 14
Device: Pixel 6a

**Comment by patdu1** [comment]
Not sure how to do that:
1. I don't want to mess up my working Osmand install
2. The nightly build is the free version and does not include the SRTM plugin... which I am not going to buy again
Also "this feature" being now available and working with my edited files on my phone...

**Comment by yuriiurshuliak** [comment]
Please be aware that we are still in the process of implementing this feature.
Related to https://github.com/osmandapp/OsmAnd/issues/6636

**Comment by patdu1** [comment]
OK, thanks for the info.
Scope of issue 6636 is much bigger, I was just trying to adjust contour lines visibility (and text size) to my old eyes ;-)

**Comment by xmd5a2** [comment]
Fixed. Contour lines code moved from topo to contourlines.addon.render.xml. Dark orange and purple color schemes added.

**Comment by patdu1** [comment]
Great! Thanks a lot.

**Comment by DmitryAlexei** [comment]
Dark orange and purple color schemes are now available on Android OsmAnd~ 4.8.0#2598m, released: 2024-06-26
For iOS new TestFlight build is needed

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/54255a89-52be-480b-a759-5c0a07718a95"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/1e83980b-42f8-4bd5-8333-09af4da45bfe"  width="300" height="auto"/> </td>
  </tr>
</table>
