### ISSUE TITLE
Some names appear in forieing language on road-only maps

### ISSUE THREAD

**Issue by vzsze** [osmandapp/Osmand#1997]
Some village names appear in foreign language or font on road-only maps on my device, while they apear to be ok in the normal map. See the attached screenshots. Device: Galaxy S4edge, OsmAnd+ Version 2.2.2

![screenshot_2015-11-29-12-39-17](https://cloud.githubusercontent.com/assets/541560/11456839/5e116c5a-9697-11e5-8944-b98537016184.png)
![screenshot_2015-11-29-12-39-40](https://cloud.githubusercontent.com/assets/541560/11456840/5e136cda-9697-11e5-925f-2b2da74882ba.png)

**Comment by morray** [comment]
Probably in the road only maids only the name tag is included. This is by definition the local name. And thus your chosen display language cannot be shown

**Comment by vzsze** [comment]
The area is in Germany (see link below), so the local name should be in German. Other towns of that size, but not all are showing the same problem. 

http://www.openstreetmap.org/#map=13/51.9400/13.8874&layers=H

**Comment by vzsze** [comment]
This one does: http://osm.org/go/0NIsx5g?layers=H
![screenshot_2015-11-29-19-16-42](https://cloud.githubusercontent.com/assets/541560/11459080/7b4fea80-96ce-11e5-8fc6-b9462f4fa7d0.png)


This one doesn't: http://osm.org/go/0NIBchd?layers=H

![screenshot_2015-11-29-19-17-47](https://cloud.githubusercontent.com/assets/541560/11459067/56007d3a-96ce-11e5-895e-b9cf5d394e9a.png)

**Comment by vshcherb** [comment]
In New maps (December) & new release the issue will be gone

**Comment by vzsze** [comment]
The issue is still present in the map from 2.12.2015.

**Comment by xmd5a2** [comment]
It is because of wrong name order in routing data
```
Point types [place-town (489)] add_types [population_rounded-20000(710)] Names [name:ru(275) - Люббен  (Шпревальд), name(1) - Lübben (Spreewald), ele(150) - 50] id 240079590

```

**Comment by vshcherb** [comment]
New maps should be ok.

**Comment by vshcherb** [comment]
We will regenerate maps with Lubben to test it quicker.

**Comment by vzsze** [comment]
In the map from today the issue is fixed.
