### ISSUE TITLE
[Routing] transition from unclassified road to residential

### ISSUE THREAD

**Issue by SnejPro** [osmandapp/OsmAnd#19974]
### Describe the routing engine used (required)

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Describe your routing Profile (required)

Default car routing profile without short_way

### Describe your start and end points (required)

[https://osmand.net/map/navigate/?start=48.211634,11.356945&end=48.211040,11.349725&profile=car#17/48.21263/11.35435](https://osmand.net/map/navigate/?start=48.211634,11.356945&end=48.211040,11.349725&profile=car#17/48.21263/11.35435)

### Describe the actual route (required)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/11321022/91f091ed-d87c-464b-9f32-9938270c7d7d"  width="500" height="auto"/> </th>
  </tr>
</table>

### Describe the expected route (required)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/11321022/45654122-e66d-40bd-a27e-b4d1cd80e4bc"  width="500" height="auto"/> </th>
  </tr>
</table>

Default car routing profile with short_way

### Describe what Maps you used (online or offline) (required)

- [x] Offline maps offered within the OsmAnd app for download. 
- [ ] Online (tile / raster) maps 

### Your Environment (required)

```
OsmAnd Version: 4.7.17
Android/iOS version: 14
Device model: Pixel 8a

OsmAndMapCreator
OsmAndOnline
```

### Anything else? (optional)

I have tried out a few things:
It looks like this is where the problem lies: https://github.com/osmandapp/OsmAnd-resources/blob/197f4b7c42b224b9d8b01813693b0f5de9b5ddd3/routing/routing.xml#L785:

When I add a line for highway=unclassified the routing works as expected
e.g.:
```
			<select value="130" t="highway" v="tertiary_link"/>
			<select value="155" t="highway" v="unclassified"/>
			<select value="167" t="highway" v="residential"/>
```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. The route takes a detour instead of a straight path. 

You can check the Web Version here: [link](https://test.osmand.net/map/navigate/?start=48.211630,11.356940&end=48.211040,11.349720&profile=car#16/48.2138/11.3499).
Check the OSM version here: [link](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=48.21164%2C11.35695%3B48.21082%2C11.34971).

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/6d36d919-5def-475f-9b9b-5857e57e2388"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by xmd5a2** [comment]
Fixed. No new maps required.

**Comment by yuriiurshuliak** [comment]
The bug has been fixed. The route is now being built via a straight road.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/848da67c-07d3-4536-b8bf-e163411f3f75"  width="300" height="auto"/> </th>
  </tr>
</table>
