### ISSUE TITLE
POIs without icon

### ISSUE THREAD

**Issue by Tchiller** [osmandapp/Osmand#1998]
I just observed that I am having some POIs in my list with no item on the side which appear with an item in the map, when I select them. E.g. "glass bottles recycling" (don't know how it is exactly named in English) has no orange symbol but in the map it shows the circular recycling arrows. Why this inconsistency? The symbols help when searching for something, I think. 

On another topic which is a it related: I am getting cinema or in German "Kino" twice in the list. One with and one without symbol. The version without symbol does not show me any cinemas in my area. 
If you need more example for both cases, I can do some research. 

Thanks a lot.

**Comment by vshcherb** [comment]
That's quite normal situation, thanks for feedback, we keep adding icons as we can.

**Comment by xmd5a2** [comment]
Duplicate "Kino" is a translation problem. First "Kino" is "amenity=cinema", second - "club=cinema". You can correct it by yourself using https://hosted.weblate.org/projects/osmand/

**Comment by Tchiller** [comment]
Thanks. Have done that. Added "Filmklub" (whatever that is... but it's used on http://wiki.openstreetmap.org/wiki/DE:Key:club)
