### ISSUE TITLE
""Lanes" not displayed (anymore)

### ISSUE THREAD

**Issue by zehess** [osmandapp/OsmAnd#19987]
### Description

I am using OsmAnd worldwiede for driving, but since about the last (or the update before the last) the "lanes" are not displayed anymore. Although the widget is activated in the top panel. I once recognized it showed up a short time (few seconds) after activating, but i could not reproduce this... 

### Steps to reproduce

Activate "lanes" widget in top- and/or bottom-panel.

### Actual result

No display of "lanes" at no time.

### Expected result

Display of "Lanes" in top- and/or bottom-panel

### Your Environment (required)

OsmAnd +4.7.17
Android 13
Moto g72

**Comment by mikehgentry** [comment]
Definitely lots of reports of this, but nobody seems to know how to reproduce it. E.g.

#19017, #18755, #18387, #3898

**Comment by yuriiurshuliak** [comment]
Could you please check if you've downloaded maps for the area where the lanes are missing? Also, ensure that your track is attached to the road. 
Also could you provide the start and end coordinates for reproduction? A video or screenshot clearly showing the issue would be very helpful.

**Comment by zehess** [comment]
Hi, thanks taking care. Charts are downloaded and current. Track is
attached to the road. First i discoverd the missing lanes back home in
germany and right while on vacations in Mexico. Therefore having the
"lanes" avlb would be very helpful for navigaton 😀. The lanes are not
showing at all (sometime, only a few seconds, after reconfiguring the
display)
The lanes widget is one of the other thousand reasons to use osmand!!!
Thanks

yuriiurshuliak ***@***.***> schrieb am Fr., 31. Mai 2024,
03:30:

**Comment by mikehgentry** [comment]
In my experience (admittedly not having tested on the latest version) resetting the top panel to default fixes it.

**Comment by vshcherb** [comment]
Please share any start/end cooridnates and run Route simulation for example and we could get it reproduced. You also can simulate location without navigation
