### ISSUE TITLE
Not calculated a route from Qal’ai Khumb to Rushon 

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#19982]
### Description

No calculated route from Qal’ai Khumb to Rushon (177 km) - Tajikistan (Car Profile)

### Steps to reproduce

* Download **Tajikistan** map
* Switch to **Car** profile
* Set **Start point** – Qal’ai Khumb `38.45728, 70.78783`
* * End point – Rushon `37.94753, 71.55744`
* * Route https://test.osmand.net/map/navigate/?start=38.457285,70.787830&end=37.947527,71.557437&profile=car#9/38.3783/71.4221

### Actual result

<table style="width:100%">
  <tr>
    <th>Missed maps</th>
    <th>Empty Suggested maps dialog</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/e6414b84-cb80-4721-a47e-99a56879385e"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/12a9fd9a-c943-424a-87c3-1eaaa72cbdb0"  width="150" height="auto"/> </td>
  </tr>
</table>   

* No route. 
* But when I downloaded the Afghanistan map, this route was calculated at once.

I can calculate the route from Qal’ai Khumb to https://osmand.net/map?pin=38.30532,71.33596#17/38.30532/71.33596
I think the road points from this place were on the Afganistan map during map generation. 

### Expected result

* The route from these two points is calculated. 

https://test.osmand.net/map/navigate/?start=38.457285,70.787830&end=37.947527,71.557437&profile=car#10/38.2269/71.0472

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.8 (Nightly)
Android/iOS version: 13
Device model:
Crash-Logs: ?
```

**Comment by Max1234-Ita** [comment]
The problem was reported by an user who's currently in Tagikistan; I reproduced it on my Android Device: attaching some screenshot.


Adding some screenshot:

<table>
<tr>
 <td>
![image](https://github.com/osmandapp/OsmAnd/assets/15315381/03e454db-f989-45a4-b77b-9ec80050bee4)

 <td>
![image](https://github.com/osmandapp/OsmAnd/assets/15315381/02f98fbb-0bce-4645-97a2-029a9a170453)

 <td>
![image](https://github.com/osmandapp/OsmAnd/assets/15315381/a4a448cf-3311-431f-bbf9-cf137c5b8023)

 <td>
<tr>
</table>

**Comment by xmd5a2** [comment]
|  |  |
|--------|--------|
| ![Screenshot_2024-05-30-13-37-06-361_net osmand plus](https://github.com/osmandapp/OsmAnd/assets/5829014/90f2a24e-7d65-41e5-96dd-bd776bd590a0) | ![Screenshot_2024-05-30-13-38-15-501_net osmand plus](https://github.com/osmandapp/OsmAnd/assets/5829014/ae1cf705-a102-4b39-985a-46d781c463e5) |
|![Screenshot_2024-05-30-13-37-43-668_net osmand plus](https://github.com/osmandapp/OsmAnd/assets/5829014/8ec256db-cad5-45c1-9735-839171898e2c)  |  |

**Comment by RZR-UA** [comment]
Tajikistan w/o Afganistan:

![af](https://github.com/osmandapp/OsmAnd/assets/90444451/167dfcf4-75ba-4557-a664-9e4a50358cc7)

Austria via Germany:

![at](https://github.com/osmandapp/OsmAnd/assets/90444451/508326b5-a11c-41bf-acbd-7042e0453823)

**Comment by vshcherb** [comment]
To do: add static boolean CALCULATE_USE_EXISTING_MAPS - will skip completely Missing Maps check (Android / iOS)

**Comment by RZR-UA** [comment]
Potential issue with MISSING_MAPS.

![empty](https://github.com/osmandapp/OsmAnd/assets/90444451/b8e084fe-90c1-49b5-88ce-ed6ab11f43a4)
**(Qal'ai Khumb to Rushon: empty Download Missing Maps list, disabled Download button)**

MissingMapsCalculator.addPoint() [comparator] should consider the case when the point(s) are located at the border of adjacent regions and therefore belongs to more than 1 map (for example - the start/finish of this Qal'ai Khumb to Rushon route). For example: first sort by /([a-z]+)_/ and then by String length.

checkIfThereAreMissingMaps() should consider more than 1 different region than `result.addMissingMaps(p.regions.get(0))` - but anyway somehow skip the region which is bigger than already added ones. For example: walk thru whole List and add all regions which are not already added by match /([a-z]+)_/

**Comment by RZR-UA** [comment]
MissingMaps bugs to research and fix:

- [ ] Activation of World_seamarks might break MissingMapsCalculator and lead HH to crash (iOS, Android)

- [ ] Tajikistan/Afhganistan route "catches" strange non-existing region afghanistan_badakhshan_asia (the reason of "empty" download list)

- [ ] 2 different countries/regions should be proposed for download by MissingMaps in case of close-to-border points (when the point exists in both countries/regions)

- [ ] DISTANCE_SPLIT should be decreased to 10-15km for EU "slightly" border-crossing routes such as Salzburg-Innsbruck via Germany-Bavaria

**Comment by vshcherb** [comment]
To fix:
- [ ] Nautical shouldn't missing maps calculator (Android / iOS)
- [ ] MissingMaps "Calculate online" helper should not send previous full route on the second run

**Comment by RZR-UA** [comment]
To Design:

![design](https://github.com/osmandapp/OsmAnd/assets/90444451/bd974702-e757-46d3-8fa5-931e0483335a)

**Comment by RZR-UA** [comment]
- [ ] split request by parts (1 bug/feature = 1 request)
- [ ] design for "Use existing maps" button/text
- [ ] implement iOS fixes
