### ISSUE TITLE
Multi gpx track import: colors not preserved

### ISSUE THREAD

**Issue by 4e868df3** [osmandapp/OsmAnd#19995]
### Description

A .gpx containing multiple tracks does not respect trk colors when imported.

### Steps to reproduce

* Download [North_Creek_(Right_Fork).gpx.zip](https://github.com/user-attachments/files/15544891/North_Creek_.Right_Fork.gpx.zip)
* Import GPX

### Actual result

<table style="width:100%">
  <tr>
    <th>Preview</th>
    <th>After import</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/13629dd6-0278-4ce0-9daf-e9c22f89c84a"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/00bfbf09-798e-4272-a227-da5d33c0ee95"  width="150" height="auto"/> </td>
  </tr>
</table>   

* Preview shows all tracks are **black**
* After import all tracks  are **red**.
* There is no difference if track were imported as one or divided.
* On iOS works as expected

### Expected result

Tracks should respect the colors defined by ropewiki/caltopo.

### Your Environment (required)

```
OsmAnd Version: version 4.7.17, net.osmand.plus
Android/iOS version: Android 14
Device model: Pixel 7 Pro
Crash-Logs: N/A
```

**Comment by sonora** [comment]
Looks like ot's the 'Import' functionality messes this up.

When simply placing the original file (as downloaded) anywhere in OsmAnd's "tracks" folder (or a subfolder there), I see the  track line colors preserved.

With one notable exception: All sections labeled "DarkRed" in the file use the selected Map style's default color, which for the OsmAnd style happens to be red also, but for e.g. the more detailed 'Touring style' popular exactly for trips like this is cyan.

So there may be two things to fix here: The 'Import' code, and (perhaps?) automatically using the renderer default color only if a track does not come with its own color specification?

**Comment by sonora** [comment]
Just like for waypoint colors/icons (see separate issues), we should probably establish this default hierachy behavior:
- user'sappearance setting in OsmAnd (only if/once selected later) overrules
- file-internal trk specification, overrules
- file-internal group specification, overrules
- renderer default.

**Comment by sonora** [comment]
@Chumva Preliminary testing: The color recognition works now! 

But this (I think it is this change) now more than doubles the time it takes to enter either one of the 2 tracks screens... We've had it down to 1-2 sec in my setup ever since the late May builds, today's build is back up to more like 3-5 sec...

**Comment by sonora** [comment]
Hete's a glitch still: The colors are not taken over to the Appeatance menu: Take any track with an in-file line color definition: The line is now displayed on OsmAnd's map in the correct color. But then, on the map, tap on the track  and then in its context menu on the 'appearance (palette icon) button: The track's line color will immediately fall back to the renderer's defaulr(!The curremt track appearnance seems not handed over to the appearance dialog.

**Comment by vshcherb** [comment]
To fix:
- [ ] The track's line color (all portions) will immediately fall back to the renderer's default. The track color should only change when the user specifies a color change, not already upon entering the dialog. (User may e.g. only want to change the width.)
- [ ] The appearance dialog's ''Reset to original' button should reset the track's appearance to its in-file appearance, but it resets it to the renderer default.

**Comment by dmpr0** [comment]
# Review

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/d4888e96-903c-460e-88a4-750af261293e"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/c6dac761-4379-4e00-b7f2-56de0b4fd213"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] All tracks are black on preview?

**Comment by sonora** [comment]
It works for me. @dmpr0 Are you sure you use the unmodified version of the file as shared in this issue above.?
