### ISSUE TITLE
App crashes on specific coordinates

### ISSUE THREAD

**Issue by yuriiurshuliak** [osmandapp/OsmAnd#19998]
### Discussed in https://github.com/osmandapp/OsmAnd/discussions/19994

<div type='discussions-op-text'>

<sup>Originally posted by **maierkurt** June  2, 2024</sup>
Description:

App crashes every time when zooming around this point:
Coordinates: N50.98969°, E8.00371°

Steps to Reproduce:

- Navigate to the coordinates 50.98969, 8.00371.
- Download the corresponding map.
- Zoom in and out several times.

Observations:

- The app crashes consistently at these coordinates.
- Live updates were not enabled during this process.

Your Environment (required):

App Version: OsmAnd~ 4.8.0#2431m
Release Date: 2024-06-03

</div>

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. When you navigate to these specific coordinates: 50.98969, 8.00371, download the corresponding map, and zoom in and out several times, the app crashes. Live updates were not enabled during this process.

Here are the corresponding crash logs:
[exception.zip](https://github.com/user-attachments/files/15534473/exception.11.zip)


OsmAnd~ 4.8.0#2431m, released: 2024-06-03


https://github.com/osmandapp/OsmAnd/assets/127092082/74e1af09-a27a-41d2-b106-e1544b4ee6e8

**Comment by sonora** [comment]
I doubt it has to do with these coordinates ... :wink: This is about track group handling, a little similar to #19993. (Probably it may disappear if you temporarily hide your tracks.)

**Comment by maierkurt** [comment]
What can I do to help fixing this problem? 
Sonora, You are right: It is not only a problem of the coordinates givrn above. I have found another pice of map, where Osmand crashes.

**Comment by DmitryAlexei** [comment]
@maierkurt please add coordinates of a new place

**Comment by maierkurt** [comment]
51.02277° N, 8.02242° E
App crashes here too.
