### ISSUE TITLE
Osmand is not able to open openstreetmap links correctly

### ISSUE THREAD

**Issue by Tchiller** [osmandapp/Osmand#1999]
When I am opening some link from openstreetmap on my cellphone (Android 5.x), it directs me to some location below Ghana. See the first image. 

![screenshot_2015-11-29-19-46-38](https://cloud.githubusercontent.com/assets/2923006/11459318/09ea740e-96d4-11e5-9406-7a4ae9964be4.png)

The same happens when I am trying to open traces from OSMtracker or from the email link like in the second photo. 

![screenshot_2015-11-29-19-46-09](https://cloud.githubusercontent.com/assets/2923006/11459322/1d12ef02-96d4-11e5-938a-e2950bca5adf.png)

**Comment by vshcherb** [comment]
It is not clear what is the link

**Comment by Tchiller** [comment]
Oh, sorry. It happens for me with any openstreetmap link. 
See here: http://www.openstreetmap.org/way/25553598 for a street
or here: http://www.openstreetmap.org/node/240109189 for a city.

**Comment by vshcherb** [comment]
These links are not supported , but this are supported http://www.openstreetmap.org/#map=15/12.9870/77.6480
