### ISSUE TITLE
Obsolete call to  BinaryMapIndexReader?

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#19990]
@vshcherb , @Chumva  Spin-off from a performance investigation: I think this line serves no purpose, or am I overlooking anything?
https://github.com/osmandapp/OsmAnd/blob/202f20c47bd44521bd7ff6e5d899e4599067b10a/OsmAnd-java/src/main/java/net/osmand/search/core/SearchCoreFactory.java#L368

**Comment by vshcherb** [comment]
Merge back to https://github.com/osmandapp/OsmAnd-Issues/issues/1982
