### ISSUE TITLE
Trip recording length inconsistent between map screen, overview and notification

### ISSUE THREAD

**Issue by speleoluc** [osmandapp/OsmAnd#19999]
### Description

While recording a trip, the displayed length is inconsistent with what appears in the track overview or trip notification. The map screen would not update itself over time.

Note: the battery was at 12%, but the displayed track was correct, only the length count was wrong.

### Steps to reproduce

Start recording a trip and check the track overview or notification

### Actual result

During a kayak trip, Osmand+ would display a current recorded length of 8.72 nautical miles while both the trip recording notification and the track overview would display 11.2 nautical miles.

### Expected result

All displayed track lengths should be identical

### Your Environment (required)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/57163823/1087fbd2-1611-430e-bcc8-661ba266357f"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/57163823/0e9a55e5-94ba-4cca-af1e-a2bc5e940989"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/57163823/0d9f9449-0e36-42c6-8a86-73abd4280ff0"  width="300" height="auto"/> </th>
  </tr>
</table>

OsmAnd Version: 4.7.17
Android version: 8.0.0
Device model: Samsung Galaxy A5 2017 phone
Crash-Logs: no crash

**Comment by sonora** [comment]
Is it reproducible? It looks like something weird happened exactly at that point, check your overview graph: The elevation shows a sudden drop of 8m or so, then slowly recovering and finally overshooting - quite an unusual behavior assuming you were paddling?

Could it be that this coincided with your battery hitting the 20% mark and perhaps some power saver kicking in, stalling something?

**Comment by speleoluc** [comment]
Yes, I was paddling on a (big) lake, but I don't recall air turbulences that would have dropped us by 8 m...

I attach the GPX that was self recorded before the phone turned itself off due to a low battery. The track is 24.8 km, i.e. 13.4 nm, as reported by the notification.

[2024-06-02_Valcour.txt](https://github.com/user-attachments/files/15539070/2024-06-02_Valcour.txt)

I'll go paddling again this week and I'll compare the distance on the map vs the notification to see whether this is always the case.

**Comment by yuriiurshuliak** [comment]
The bug could not be reproduced. I attempted to replicate the issue by enabling the Track Recording feature and walking a certain distance under real-world conditions. Upon review, the traveled distance was consistently displayed across the map screen, the full trip overview, and the notifications. It is likely that the problem may be associated with the activation of the power-saving mode.

OsmAnd~ 4.8.0#2434m, released: 2024-06-04

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/9c9aff8b-b4e8-40cf-8583-6f001c7d9e2d"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/0bcf8152-be2b-4e81-85d9-51315b57f660"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
@yuriiurshuliak you need to retest with nautical miles

**Comment by speleoluc** [comment]
Firstly, I have all power saving setting disabled and Osmand+ has unrestricted use of battery. So, even if battery is low, it doesn't make sense that the track gets updated on screen and the recorded distance is correct in track overview and notification, only to be lagging on the screen widget.

I paddled the same area yesterday, which I recorded. At lunchtime, I checked my emails. Returning to Osmand+, the trip recording widget had gone from 6.46 nm to REC and the track was gone from the map and no recording was available in the files. I restarted trip recording, it showed 0 and after switching to another app and returning to Osmand+, the count and the map track were restored! I'll open another issue about this because it seems part of a broader bug. Despite later turning on the phone at various times, the recording is lacking the rest of the loop back to launch except for a short leg between Valcour island and shore, that appears with double arrows, but that we only paddled in the west direction. The battery is still at 38%.
[2024-06-04_Valcour.txt](https://github.com/user-attachments/files/15585577/2024-06-04_Valcour.txt)

**Comment by speleoluc** [comment]
Here's a track of what we actually paddled yesterday, as recorded by Gaia.
![Screenshot_20240605-065216_Gaia GPS](https://github.com/osmandapp/OsmAnd/assets/57163823/25612651-001d-4ce9-b532-c3b3513c4d3d)

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. I attempted to reproduce it by selecting the boat profile, adjusting the unit settings for length and speed to nautical miles, then simulating my position and activating the Track Recording function, but to no avail.

OsmAnd~ 4.8.0#2440m, released: 2024-06-05

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/79055f3c-d3b9-4714-850b-0f3a21768d2c"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/98c84829-7322-41f0-99f0-adef9543563f"  width="300" height="auto"/> </th>
  </tr>
</table>
