### ISSUE TITLE
lamps shown even at daytime despite settings

### ISSUE THREAD

**Issue by kadlecf** [osmandapp/OsmAnd#19997]
### Description

Among the details to be displayed, one can choose lit streets and street lamps to be shown - "Always" or within the "Night map" only, proceeding through the menu: Configure map |Details |Street lighting - _Night map_. This works in an unexpected way: whereas "Always" shows the lighting - always, indeed, the option "Night map" will activate the display of both lit streets (yellow and red highlighting) and street lamps in the night map. In contrast, in the day map view, the highlighting of lit streets disappears but the street lamps are still shown; I think they should not be shown in the day view.

### Steps to reproduce

From menu select Configure map |Details |Street lighting - _Night map_. 

### Actual result

street lamps are shown in both night and day views.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/81177285/421d518b-0415-4ab6-adaa-a2c82e782094"  width="300" height="auto"/> </th>
  </tr>
</table>

### Expected result

street lamps should be shown only in the night view.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.7.17
Android/iOS version: 12
Device model: Nokia 5.3
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To recreate it, navigate to coordinates 50.14276, 14.08726 and activate street lighting within the configure map, specifically in night mode. Follow this path: Configure map > Details > Street lighting > Night map. Consequently, street lighting will appear in both night and daytime modes.

OsmAnd~ 4.8.0#2431m, released: 2024-06-03

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/516a1c75-2cc9-46b7-85a7-29ee0cd572af"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/5e07b296-654d-4dfd-bf96-42b6b9570506"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by xmd5a2** [comment]
Fixed. Lamps were removed from day view when Street lighting - Night map is enabled.

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.8.0#2491m, released: 2024-06-12 (nightly) and OsmAnd TestFlight 4.7.7.3
On Android and iOS works fine. But for iOS all the settings in menu>configure map>details are messed up. It is not clear, that  "Show only at night" option should also be enabled for this feature to work correctly. 
https://github.com/osmandapp/OsmAnd-iOS/issues/3761#issuecomment-2163325779

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/1cb794e4-fea8-4694-8442-90dc495cb6a5"  width="300" height="auto"/> </td>
  </tr>
</table>
