### ISSUE TITLE
Mess with a contour lines download options

### ISSUE THREAD

**Issue by brbar** [osmandapp/OsmAnd#20002]
### Description

Contour lines download options does not render according to selected preferable units.

### Steps to reproduce

1. Go to settings -> Browse map profile -> General settings -> Units of length and choose Kilometers/meters
2. Go to Maps & Resources -> choose any non downloaded country

If you can't reproduce this issue try to select different profiles.

### Actual result

You will notice that Contour lines in ft will be selected by default instead of meters

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/97563684/c46e7ca7-88f3-42fe-873a-fb2a5400d449"  width="300" height="auto"/> </th>
  </tr>
</table>

### Expected result

Contour lines in meters should be selected by default

### Your Environment (required)

```
OsmAnd Version: 4.7.17
Android/iOS version: 13
```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce this issue, you need to try several times with different profiles and possibly with different countries.  I managed to reproduce it by selecting the bicycle profile and change the Units of length to Kilometers/meters specifically for that profile. Subsequently, you need to find the map of North Korea and go to the context menu to download Contour Lines.

OsmAnd~ 4.8.0#2434m, released: 2024-06-04

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/6b2fcbbc-3180-401b-978f-14e276a838e0"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/a9546b63-6b29-4e43-b4b0-67634242a7e1"  width="300" height="auto"/> </th>
  </tr>
</table>
