### ISSUE TITLE
Comma as decimal point causing line feed

### ISSUE THREAD

**Issue by CJTmmr** [osmandapp/Osmand#2000]
Hi,
We noticed that when system settings in Android define comma as decimal point (yes, this is true in some non-latin languages, e.g Dutch)  OsmAnd is inserting new line immediately after comma.
For example in the following string: "Total distance %1$s, travelling time %2$d h %3$d m."
In Dutch: "Totale afstand   .... km, reistijd   ...u....m.".

See screenshot,
![freshpaint-4-2015 11 29-09 41 21](https://cloud.githubusercontent.com/assets/15076257/11459921/1dd0b466-96e2-11e5-8e5b-e7fca7705024.png)

(thanks to user pl on osmand forum)

**Comment by vshcherb** [comment]
That screen will be mostly refactored soon because of new design, so it will be taken there.
