### ISSUE TITLE
OSM Editing: "Unable to preform operation without a connection to Internet."

### ISSUE THREAD

**Issue by maltfield** [osmandapp/OsmAnd#20017]
### Description

It's no longer possible to upload data to OSM from OsmAnd using the built-in `OpenStreetMap editing` plugin.

### What changed?

5 days ago (on 2024-06-01), [OSM deprecated HTTP Basic Auth and OAuth 1.0a](https://wiki.openstreetmap.org/wiki/2024_authentication_update).

Previously, I'd been authenticating with OSM in OSMAnd via Hamburger Menu -> Plugins -> OpenStreetMap editing -> overflow menu -> Settings -> Login to OpenStreetMap -> Use username and password. But I guess that won't work anymore.

Now, I tried the `Sign in with OpenStreetMap` option instead, but when I click that, I get an error message

```
Unable to preform operation without a connection to Internet.
```

I am, definitely, connected to the Internet.

### Steps to reproduce

1. Tap the OSMAnd Hamburger Menu
2. Tap `Plugins`
3. Next to `OpenStreetMap editing`, tap the triple-vertical-dot overflow menu
4. Tap `Settings`
5. Tap `Sign in with OpenStreetMap`

### Actual result

Error message "toast" appears:

```
Unable to preform operation without a connection to Internet.
```

### Expected result

I guess a browser should open and I should be receive a credential challenge to login to OSM and grant OsmAnd permission via OAuth 2.

### Your Environment (required)

```
OsmAnd Version: 4.6.14
Android/iOS version: 14
```

**Comment by dfandrich** [comment]
Version 4.7 supports oauth2: https://osmand.net/blog/osmand-android-4-7-released/#oauth-20-for-osm-login

**Comment by DmitryAlexei** [comment]
@maltfield Please update OsmAnd to the latest version and try again.

**Comment by maltfield** [comment]
The reason I'm running an older version is because I get an error

```
Could not calculate route.: Empty result
````

...when I install newer versions.

I had to downgrade before a recent trip to make this error go away. At your request, I just upgraded to OsmAnd v4.7.10, and the error re-appears. Unfortunately, I can't use these versions since route calculations are broken. Is this a known bug?

**Comment by maltfield** [comment]
I'm going to downgrade again shortly, but before I do, I opened OsmAnd (v4.7.10) and went to Hamburger Menu -> Plugins -> OpenStreetMap editing -> overflow menu -> Settings -> Sign in with OpenStreetMap.

That opened a web browser. I typed my username and my password, and clicked ??. This brought me to a page that says

> **Webpage not available**
> The webpage at **https://www.openstreetmap.org/login** could not be loaded because:
> net::ERR_HTTP_RESPONSE_CODE_FAILURE

So I'm still stuck.

**Comment by maltfield** [comment]
I copied the URL to another (non-security-hardened) web browser on my phone, and I was able to login.

But, after I login, wtf am I supposed to do. I'm logged-in on my browser; I'm not logged-in in the app.

So I'm still stuck. I can't upload my changeset in this newer version of OsmAnd, either.

**Comment by dfandrich** [comment]
The net::ERR_HTTP_RESPONSE_CODE_FAILURE issue sounds like
https://github.com/osmandapp/OsmAnd/issues/20018

**Comment by DmitryAlexei** [comment]
@malfield
Please consider using the latest version of OsmAnd from Google Play and default browser and see if it is working for you. 
For correct routing results, please update your maps to the latest version.
Also note, that OsmAnd team is not responsible for f-droid version of the app.

**Comment by maltfield** [comment]
I can't run Google Play because I don't have gapps installed. All users can intsall OsmAnd from F-Droid. Not all users can install it from Google Play.

OsmAnd does not prompt me which browser to open.

Since this workflow is broken, Is there a guide describing how I can generate the OAuth keys and then copy and paste them manually into OsmAnd?

**Comment by maltfield** [comment]
> Choosing the username/password form of login instead of oauth worked for me, although it's less secure and desirable.

@dfandrich did you auth with this method recently? OSM [deprecated `HTTP Basic Auth` 7 days ago](https://wiki.openstreetmap.org/wiki/2024_authentication_update), so I would be surprised if this method still works..

**Comment by dfandrich** [comment]
It worked for me yesterday.
