### ISSUE TITLE
HH-Routing not automatically enabled after update

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#20019]
### Description

Multiple users (including myself) report that after updating to OsmAnd 4.7.x, HH routing wasn't configured for them. They had to enable the development plugin to change the routing type to HH (https://osmand.net/docs/user/navigation/guidance/navigation-settings/#development-settings).

My case was upgrading via the Playstore from 4.6.x to the 4.7.x beta.
Two other user upgraded via F-Droid from 4.6.x to 4.7.x.
The upgrade path from other affected users is unknown.

### Steps to reproduce

Upgrade from 4.6.x to 4.7.x

### Actual result

HH not always automatically enabled.

### Expected result

HH always automatically enabled.

### Your Environment (required)

.

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce this issue, join the Beta test, perform the update, then open and check the routing algorithm. Navigate through Menu - Settings - Driving - Navigation settings - Route Parameters - Development - Routing algorithm. The HH routing option will not be selected by default.

OsmAnd~ 4.8.0#2454m, released: 2024-06-07

https://github.com/osmandapp/OsmAnd/assets/127092082/f2cae285-493e-4364-a497-adf26785ddd1

**Comment by vshcherb** [comment]
we can reset setting (rename key) to enable everywhere - renaming should also happen in iOS

**Comment by RZR-UA** [comment]
Android request created. Additionally, it seems that OsmAnd iOS is not affected by this issue (option use_old_routing was created with correct default "NO" initially).

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.8.0#2598m, released: 2024-06-26
HH x C++ was enabled after fresh installation

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/210cdb69-561f-4424-b043-319680916424"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by dmpr0** [comment]
# Review

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/ef64f39c-7f9e-4ebc-b1b4-297e578cdb9a"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/91353410-996a-4c4e-a5de-12f31150e979"  width="300" height="auto"/> </td>
  </tr>
</table>   

* I have install 4.6.9, launch it, download one region map. 
* Open Google Play, update OsmAnd to the latest beta 4.8.0.
* Trying to calculate route to the city without map, Missed maps dialog appear.
* Route parameters show **A* 2-phase** as selected 
* Log – [logcat (2) (1).log](https://github.com/user-attachments/files/16011486/logcat.2.1.log)

**Comment by dmpr0** [comment]
# Review 2

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/ef64f39c-7f9e-4ebc-b1b4-297e578cdb9a"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/91353410-996a-4c4e-a5de-12f31150e979"  width="300" height="auto"/> </td>
  </tr>
</table>   

* I have installed 4.6.9, launched it, download one region map. 
* Open Google Play, update OsmAnd to the latest beta 4.8.2, released 10.07.2024
* Trying to calculate a route to the city without a map, "Missed maps" dialog appears.
* Route parameters show **A* 2-phase** as selected, for Driving and Cycle profiles.
* Reseting profile settings to default, switch Routing type to `HH x CC++`

**Comment by RZR-UA** [comment]
I can not reproduce this case either in Simulator or Samsung Galaxy Tab with Android 13.

I've tried 2 options:

1) clean setup 4.6.9 (apk), download one map, update to 4.8.2 (apk, 10.07.2024), try to calc with Missed Maps, enable Devel plugin and check Routing Type => HH C++ in all profiles

2) similar clean setup, but playing with options in 4.6.9 (special routing on/off in Devel plugin, routing type A* phase on/off in options) => the same result after update to 4.8.2 = HH C++

@DmitryAlexei please try to reproduce on your device(s).

**Comment by RZR-UA** [comment]
It should be re-tested with next beta version which will include this commit: https://github.com/osmandapp/OsmAnd/pull/20312
