### ISSUE TITLE
Online photos don't work

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#20022]
### How to reproduce
* Got to Map, zoom in to any city
* Tap on city name to open context menu
* Tap Details, scroll to Online photos block

### Actual result
<table style="width:100%">
  <tr>
    <th>Android – Release</th>
    <th>Android – Nightly</th>
    <th>iOS</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/38adb414-c37f-4364-8a8f-15c55a941c45"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/8cfba0d5-3365-45e5-8f82-760d830d6153"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/79970b34-9eef-49ee-9456-f0303cbff571"  width="300" height="auto"/> </td>
  </tr>
</table>   

### Expected result

* Online photos from Wikimedia
* Works on iOS

**Environment**
OsmAnd Version: OsmAnd~ 4.8.0#2441m, released: 2024-06-05
Android: 15
Device model: Pixel 6A

**Comment by vshcherb** [comment]
All tags now have changed name internally to ```osm_tag...```, Probably there are bugs now across whole application which is strange.
![Screenshot 2024-06-10 at 13 16 09](https://github.com/osmandapp/OsmAnd/assets/1042025/05447572-6c75-47d8-
affd-4c712f586115)

**Comment by dmpr0** [comment]
## Review

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/7ffc7096-3173-4e50-82e7-56592102dd07"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/282aadec-2b5b-49ce-8895-7d10eb0cbade"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] Doesn't work in overview map

**Comment by vshcherb** [comment]
Separate issue to backend to add tags to basemaps
