### ISSUE TITLE
Use localised names for routes

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#20020]
## Description
Hiking routes and probably other types, can have `name` tag with translated route name, but it don't use.

## Example

<table style="width:100%">
  <tr>
    <th></th>
    <th>Lycian Way</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/eca224d3-562d-4533-b49b-2ec42ac1ad6b"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/49064a49-2eed-4d2c-a170-786a2d2e53a5"  width="300" height="auto"/> </td>
  </tr>
</table>   

* Map language is set to Ukrainian 
* [Lycian Way](https://www.openstreetmap.org/relation/51855#map=9/36.9301/30.7727), have `name:uk | Лікійська стежка`, but not used
* [Eiffel Tower](https://www.openstreetmap.org/way/5013364#map=18/48.85826/2.29450)

**Comment by DmitryAlexei** [comment]
Todo:
- use localized names for routes (when present)
- use localized names when saving routes

**Comment by dmpr0** [comment]
## Review 
<table style="width:100%">
  <tr>
    <th>POI</th>
    <th>Route</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/ae2607cc-1f29-4699-abc1-05e6ca8e3f0b"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/62e088af-a6ae-48cc-884f-a9a563a056fa"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] Route name language should use the same algorithm is used for POI names.

**Comment by dmpr0** [comment]
## Review
Route menu should show name following the same rules as in POI. POI or Route name = map language.

**Comment by dmpr0** [comment]
Works on iOS too

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/4fa31c87-ca92-4ac7-94e2-9185db5c1ff9"  width="300" height="auto"/> </td>
  </tr>
</table>
