### ISSUE TITLE
Map style Touring View does not show tunnel

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#20032]
### Description

Map style Touring View does not show tunnel
Profile bike
see tunnel North west of 43.85898° N, 5.58868° E
compare to Map style OsmAnd

### Steps to reproduce

See above

### Actual result

Tunnel is not visible

### Expected result

Tunnel should be visible like in map style osmand.

### Your Environment (required)

OsmAnd Version: OsmAnd~ 4.8.0#2460m, veröffentlicht: 2024-06-08

Android version: 12
Device model: samsing S10
Crash-Logs: Np

**Comment by sonora** [comment]
Strange, there is code in place to render the tunnels (https://github.com/osmandapp/OsmAnd-resources/blob/7041e4192e4f99f7782c74f4dd0767d4eeba259d/rendering_styles/Touring-view_(more-contrast-and-details).render.xml#L1289), just like there is for bridges 5 lines below that.

But while for bridges it seems to always work (at least I find no situations where not), for tunnels we have ways where it works
https://www.openstreetmap.org/way/26736197#map=17/47.43057/11.29891
and ways where it fails:
https://www.openstreetmap.org/way/490986133#map=16/43.8586/5.5889
https://www.openstreetmap.org/way/981288914#map=18/43.39895/12.73589

And perhaps for different reasons, not sure. Perhaps @xmd5a2 spots something in the code I currently do not? :wink:

**Comment by pebogufi** [comment]
The tags for my example 
https://www.openstreetmap.org/way/490986133/history
are
highway=track
railway=abandoned
surface=ground
tunnel=yes

Is the "abandoned" in railway=abandoned a problem ?

**Comment by sonora** [comment]
Some layer/color conflict. Here's a way with railway=abandoned which renders correctly: https://www.openstreetmap.org/way/911882528.

**Comment by sonora** [comment]
Look like LightRS is also affected, although not dependent on default...
