### ISSUE TITLE
OsmAnd messed up OSM polygon

### ISSUE THREAD

**Issue by rene78** [osmandapp/OsmAnd#20031]
### Description

After [changing a single tag of a rectangular polygon](https://www.openstreetmap.org/way/87292135/history/9) with the "OSM editing" plugin OsmAnd copied the associated nodes multiple times. So instead of a rectangle with 5 nodes there was suddenly one with 20 nodes after uploading.

### Steps to reproduce

1. Changed this polygon and multiple other OSM elements
2. Tried to upload everything but got "unknown error". Tried to upload around 4 times - always the same error message.
3. Removed and readded my OSM account within the "OSM editing" plugin
4. Only tried to upload the above mentioned polygon as a test. The upload succeeded but with 20 nodes instead of 5.

### Actual result

Polygon has 20 nodes instead of 5. The 5 original nodes are copied multiple times.

### Expected result

Upload without changing the geometry since I have only edited one key-value-pair.

### Your Environment (required)

OsmAnd Version: OsmAnd+ 4.7.17
Android/iOS version: Android 14
Device model: Galaxy Z Flip 4

**Comment by vshcherb** [comment]
Likely issue related to "unknown error". it happened 5 times, so it correlates with number of errors 5 = 4 + 1. Probably we have an issue once osm upload fails it copies nodes in polygon

**Comment by yuriiurshuliak** [comment]
Unfortunately, I don't fully understand the steps to reproduce. Please provide the coordinates of the objects and describe the steps to reproduce this bug in more detail. You can also attach screenshots to help clarify the issue.

**Comment by rene78** [comment]
> Unfortunately, I don't fully understand the steps to reproduce. Please provide the coordinates of the objects and describe the steps to reproduce this bug in more detail. You can also attach screenshots to help clarify the issue.

A bit hard to reproduce since the uploading to OSM from OsmAnd works fine again. The object can be found when clicking on the hyperlink.

I think @vshcherb is right. After each failed upload the nodes have been copied.

**Comment by rene78** [comment]
> @rene78 Please clarify if the problem has been resolved and if we can proceed to close this issue.

I don't know if the problem has been resolved.

**Comment by yuriiurshuliak** [comment]
The issue might be closed due to the impossibility of reproducing it.

**Comment by rene78** [comment]
Okay. Gonna close it.
