### ISSUE TITLE
Route shields not correct for National Highways in India

### ISSUE THREAD

**Issue by SirSireesh** [osmandapp/OsmAnd#20043]
### Description

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/22617812/da98586f-af31-4b20-9f31-91e11948dd0e"  width="300" height="auto"/> </th>
  </tr>
</table>

The route shield is rendered incorrectly. It shows a "44" with a white background in a generic rectangular box, where as its expected to show the route shield (shown in the same image).

The most likely reason for this is that India switched to using only the route number in the relation, so the relation for all national highways now use `ref=xx` instead of `ref=NHxx`. Ways are still tagged with `ref=NHxx`, which is probably why osmand is still showing the correct route shields some times. It appears tagging like this is the preffered way, according to the [wiki](https://wiki.openstreetmap.org/wiki/Key:ref).

### Steps to reproduce

1. Download a standard road map for an Indian location (screenshot is from Karnataka)
2. Scroll to a national highway (the screenshot is of NH44 near Chikkabalapur)
3. Zoom in or out until the white-box route-shields are shown

### Actual result

Route numbers are rendered with a generic white box

### Expected result

Route numbers should be rendered inside the relevant shield

### Your Environment (required)

```
OsmAnd Version: 4.7.10
Android/iOS version:  14
Device model: OnePlus 6
Crash-Logs: NA
```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce, visit these coordinates: 20.66747, 78.92451. When zooming in, you'll see two shields for Highway 44, but the "44" on a white background should not be appearing. Check it out on OSM: [OSM Link](https://www.openstreetmap.org/way/182450919#map=14/20.6804/78.9249).

OsmAnd~ 4.8.0#2469m, released: 2024-06-10

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/c79d08ee-ed3e-4b7d-b36a-646e4dffbd36"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by xmd5a2** [comment]
Fixed. Karnataka and Maharashtra will be regenerated today.
