### ISSUE TITLE
Unable to uninstall OSMand~

### ISSUE THREAD

**Issue by Nono-m0le** [osmandapp/OsmAnd#20044]
### Description

I used to install and update osmand~ via F-Droid, but since few weeks now, I'm not able to uninstall the apps anymore.
Simply nothing happens...

### Steps to reproduce

Click "uninstall"

### Actual result

Nothing happen

### Expected result

The app should uninstall

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.7.17
Android/iOS version: android 13
Device model: Samsung S20 5G
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
Try these steps to uninstall app:

- Restart your device.
- Use system settings to uninstall the app.
- Clear F-Droid cache in system settings.
- Update F-Droid to the latest version.
- Use ADB commands: adb uninstall net.osmand.plus.
- Check if OSMand~ is a device administrator and disable it.
- Boot into Safe Mode and try uninstalling.
