### ISSUE TITLE
Search for street truncates first letter from the street name

### ISSUE THREAD

**Issue by pl71** [osmandapp/Osmand#2004]
First letter of the street name is missing if the name starts with "ул." (in Bulgaria, possibly in Russia also) and there is no space between "ул." and the rest of the string.

Note: "ул." is abbreviated from "улица" [ulitza], meaning "street" in Bulgarian. So, "ул." is same as "str."
Some streets in Bulgaria are named in the following manner:
name="ул. Победа", which means "Pobeda str."
In German is common "straße" to appear at the end: Kreuzstraße

So, somewhere in the Search function there is a filter, which truncates street names from OSM starting with "ул." , but this filter truncates first 4 letters, assuming (but not checking!) that 4th letter is a space.
For some weird reason in some names space between "ул." and the actual street name is missing like:
"ул.Победа". (Yes, there is no consistency in the naming of streets)

On map window that name is shown in full : "ул.Победа"
But in Search function same is shown like : "обеда"

Removing "ул. " from street names is a good feature, but should be done more carefully.

One suggestion: remove "ул." (3 characters) and after that remove leading spaces if any.

Regards, 
Pl

**Comment by vshcherb** [comment]
Fixed, will be released with december maps.
