### ISSUE TITLE
Imported tracks are displayed in a wrong color.

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#20051]
### Description

Afzter importing tracks (copying them into a track folder by a file manager) the tracks are displayed in a wrong color. 
Red instead of green.

### Steps to reproduce

Tracks are colored in green on device A. 
Copy those tracks to device B. 
Tracks are not displayed correctly anymore, but in some standard color.

### Actual result

Though osmand KNOWS the correct color, it does not display it correctly.

- Tracks are GREEN on device A
- Tracks are RED after copying them to debice B

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/95540936/847b8791-4fe0-44d1-8e61-13f7e31a5937"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/95540936/6500d65a-ddc9-439e-91c7-7d1d4e4d1a58"  width="300" height="auto"/> </th>
  </tr>
</table>

- Tapping a track and entering it´s menu, the track is IMMEDIATELY displayed in the correct color GREEN.
- Aftre applying this, the track is correctly displayed GREEN again.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/95540936/37386c73-80cb-4f08-9402-53c8b2f29fff"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/95540936/665a54f9-4ace-49e9-8f4b-c4d90ce2ee6e"  width="300" height="auto"/> </th>
  </tr>
</table>

### Expected result

Just display my tracks in their set color. 
Dear app, try it, you know it.

### Your Environment (required)

OsmAnd Version: +4.7.17 (but this problem exists since as long as I can remember)
Android/iOS version: 12 and 13
Device model: Tab S6, S20+

**Comment by vshcherb** [comment]
Merge to https://github.com/osmandapp/OsmAnd/issues/19995

**Comment by Chumva** [comment]
@Rowin63 could you please provide one of the tracks that has this behaviour?

**Comment by Rowin63** [comment]
Yes of course. This is one of those tracks (renamed it from gpx > txt for uploading).
Thanks!

[Wien - Wachau - Wien.txt](https://github.com/user-attachments/files/15814354/Wien.-.Wachau.-.Wien.txt)

**Comment by sonora** [comment]
It seems to me @Chumva has fixed this ok öast night.

At first sight, this track has no **built-in** color information. So the next thing OsmAnd uses is the **default color as specified in the renderer ("Map style")**. You can temporarily chose Map style Touring view, the track should switch to cyan/illuminated blue, to verify if OsmAnd uses the renderer default.

It would also explain that the track looks different on different devices or in different app profiles, if you use different Map styles.

Next thing is if you override the renderer default by **soecifying a deviating appearance in OsmAnd**. That again is resettable by either tapping the 'Reset to original' button in the apprarance menu, or by renaming the gpx file in the file system (not in OsmAnd!) and restarting OsmAnd.

For me this works ok now for the track **line**. We have a separate thread somewhere for the waypoints, still work in progress.

**Comment by Rowin63** [comment]
> It seems to me @Chumva has fixed this ok last night.
> 
> At first sight, this track has no **built-in** color information. So the next thing OsmAnd uses is the **default color as specified in the renderer ("Map style")**. To verify if this is the case, you can temporarily chose Map style 'Touring view', the track should switch to cyan/illuminated blue.
> 
Yes, right. Has switched to Cyan.

> It would also explain that the track looks different on different devices or in different app profiles, if you use different Map styles.
> 
I use "Osmand" as mapstyle on all devices in the "View Map"-profile, so it shouldn´t be different.

> Next thing is if you override the renderer default by **specifying a deviating appearance in OsmAnd**. That again is now correctly resettable by either tapping the 'Reset to original' button in the appearance menu, or by renaming the gpx file in the file system (not in OsmAnd!) and restarting OsmAnd.
> 
Tapping "reset to original" did not change anything, track remained "red" (so this seems to be "original" in this case?).
Renaming the track in the file manager did not change anything, still the same behaviour: track is displayed "red" in the map, but opening the tracks menu displays still "set to green" 

> For me this works ok now for the track **line**. We have a separate thread somewhere for the waypoints, still work in progress.
>
 
> PS: Apparently, in addition to specifying an OsmAnd appearance for a gpx **file** you can also specify an appearance for a **folder**, inheriting to all files it contains, perhaps including future ones... Have not experimented with this, neither know how to reset this... Overall, perhaps there is one too many options/rules here for a normal user to understand what's going on. 😉
>

Hey, that really works (specifieing the appearance by folder!) 👍 
Unfortunately there is no option for "existing" AND "future ones" (and you can´t use first the option "existing ones", apply it to the existing tracks, and then change to "future ones", because without making a change after applying "existing ones" there is no active "apply" button to set for "future ones". This seems to be modified! (i´m running 4.8.0#2501)

But anyway, having the possibility to specify the appearance by folder is a great !!! feature and once it works well, it may solve all problems with different track´s appearance on different devices 👍  

Thanks for your detailled explanation, but I still don´t understand why those tracks are "red" after importing/copying (mapstyle standard?) but at the same time "green" is displayed as the selected color as I open the tracks menu...

I don´t mind, specifying tracks appearance by folder is the right way to solve "my" problem.
I only miss "apply to existing AND future tracks" 👍 

Thanks!

**Comment by sonora** [comment]
_Thanks for the flowers ..._ 

**"Thin" and "Red**", from what I remember, is the default appearance of the track line in the OsmAnd (default) Map style. Just like e.g. **"Medium"and "Transparent Cyan"** is the default for the "Touring view". Just to solve that mystery.

I am not sure about the "_but opening the tracks menu displays still "set to green"_" thing though, what it means and where it comes from. In all cases, I think the color palette offered in the appearance menu is the one specified in the selected Map style (and rightly so, because it depends on the colors used in the Map style).

Overall, I think we've made good progress in being able to control the appearance of tracks, both by file-built-in ways as well as using OsnAnd means (experts need both). Still some things to sort out and make easier to use, but I will monitor and create future issues for ideas, let's first stabilize the current improvement ...  :wink:
