### ISSUE TITLE
Feature request: Long-press on the "Start" button to let user select between video, audio and photo

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2006]
Currently OsmAnd has a program option to assign a default action to **Start** button. While this makes one action convenient, it makes the other actions out of reach.

For example, suppose that I have set "Photo" as my default action. But what if I want to take a video (or audio) for a specific location? That option is not available as easily!

**Suggestion:** Allow the user to long-press on the "Start" button to invoke all three options. Now he can select the desired option with a second tap. 

(The idea behind offering all three options is to make this dialog predictable. Since the user is driving at the same time, he cannot afford to manipulate screen controls for too long. So if the list of options is known, he will automatically know where to tap.)

**Comment by sonora** [comment]
I guess with the new context menu always offering all options it became easier to select, so no further action planned here?
