### ISSUE TITLE
Labels on weather contour lines is hardly visible 

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#20068]
### How to reproduce
* Enable **Weather** plugin
* Open **Menu** – **Weather** 
* Turn on **Contours** and any Weather layer

### Actual result
<table style="width:100%">
  <tr>
    <th>Android</th>
    <th>iOS</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/501f2821-d0c8-4aa7-820e-e7d17d3f9a9a"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/17e375fd-0300-453b-9263-100a81a2ec90"  width="300" height="auto"/> </td>
  </tr>
</table>   

* Hardly visible

### Expected result
* Match line color with text color
* Add halo

**Environment**
OsmAnd Version: 
Android/iOS version:
Device model:

**Comment by xmd5a2** [comment]
Fixed

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.8.0#2598m, released: 2024-06-26
Labels on contour lines are better visible now.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/699d26d3-025e-4cfe-a0cb-7f62d033c42b"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by dmpr0** [comment]
## Review

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/e2a37f2f-1291-467a-8043-e39d7aa2e693"  width="300" height="auto"/> </td>
  </tr>
</table>   


It still hard to see. This would be the issue for custom terrain color schemas too.
* We need to introduce dynamic text color. 
* Use total black text / white stroke and vice versa for night mode.

**Comment by vshcherb** [comment]
They are all different contour lines on precipitation need to change to make more sense in future
