### ISSUE TITLE
Route loops left and U-turns, should bear right

### ISSUE THREAD

**Issue by lunkhub** [osmandapp/OsmAnd#20078]
### Describe the routing engine used (required)

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Describe your routing Profile (required)

Car, fuel-efficient, no toll-roads, no motorways.

### Describe your start and end points (required)

Example, approximate
Start: 35.39894, -80.60776
End: 35.40181, -80.60878
Can start farther south, and end farther north.

### Describe the actual route (required)

Says turn left then U-turn. 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/66975721/69b5c0d8-88df-4bc3-be6e-323d47d3449d"  width="300" height="auto"/> </th>
  </tr>
</table>

### Describe the expected route (required)

Should slight turn right or bear to right or almost stay straight, not turn left and U-turn.

### Describe what Maps you used (online or offline) (required)

- [x] Offline maps offered within the OsmAnd app for download. North Carolina USA June 1, 2024, or previous, with weekly updates
- [ ] Online (tile / raster) maps 

### Your Environment (required)

```
OsmAnd Version: 4.7.17 from F-Droid Main
Android/iOS version: 14 (CalyxOS)
Device model: Pixel 6a
```

### Anything else? (optional)

Looked at openstreet map, but did not find error to correct.

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce it, follow these steps:

- Build the navigation route using the provided coordinates with the fuel-efficient option disabled.
- Then, enable the fuel-efficient option and build the route again.

When the fuel-efficient option is enabled, the resulting route includes a detour.

You can view the example here: [web version link](https://test.osmand.net/map/navigate/?start=35.398940,-80.607760&end=35.401810,-80.608780&profile=car&params=car,short_way#17/35.40030/-80.60948)

<table style="width:100%">
  </tr>
  <tr>
    <th>The fuel-efficient way option is disabled</th>
    <th>The fuel-efficient way option is enabled</th>
  </tr>
  <tr>
  <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/553f2f59-84a1-4f9a-9629-61740b2cf3b5"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/437f2c56-0917-424c-963b-4f0e8c5704ec"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by 0709wiwiwi** [comment]
Strange is that even the graphHopper router as shown in openstreet results in  the same yet very weird route result.
https://www.openstreetmap.org/directions?engine=graphhopper_car&route=35.39872%2C-80.60771%3B35.40399%2C-80.60951#map=17/35.40136/-80.60861

This could possibly be optimised ?  This by tagging the highway junction as well as the next merge in osm as: Tag:highway=motorway_junction
A local osm mapper should eventually perform this and after the routing data is  updated then check this result again.

https://www.openstreetmap.org/edit#map=17/35.39977/-80.60772
https://wiki.openstreetmap.org/wiki/Tag:highway%3Dmotorway_junction

**Comment by 0709wiwiwi** [comment]
Patience. The data of the route service providers is not immediately updated. It can take a few days before an osm change has effect.

**Comment by vshcherb** [comment]
We need to retest after results changed

**Comment by 0709wiwiwi** [comment]
As for GraphHopper, I checked this out in the GH forum.  
What do the OsmAnd router devs think about the reply ?   
https://discuss.graphhopper.com/t/strange-routing-result/8736

**Comment by yuriiurshuliak** [comment]
The bug persists. When using the fuel-efficient navigation option, the road is being built through a detour, even after the above map change. Without this option, the road is built in a straight line.

Additionally, on OSM with the OSRM engine, the road is routed directly, while with the GraphHopper engine, it built through a detour.

This suggests a potential data issue.

[Web version](https://test.osmand.net/map/navigate/?start=35.398940,-80.607760&end=35.401810,-80.608780&profile=car&params=car,short_way#17/35.40041/-80.61025)
[OSM link](https://www.openstreetmap.org/directions?engine=graphhopper_car&route=35.3987%2C-80.6077%3B35.4040%2C-80.6095)


<table style="width:100%">
  </tr>
  <tr>
    <th>Web version - The fuel-efficient way option is disabled</th>
    <th>Web version - The fuel-efficient way option is enabled</th>
  </tr>
  <tr>
  <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/8cfc5c67-5e6f-4262-997f-a892ee858cee"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/4539ca2d-ab9d-4aea-9680-7f556061856c"  width="300" height="auto"/> </th>
  </tr>
</table>

<table style="width:100%">
  </tr>
  <tr>
    <th>OSM - Car (OSRM)</th>
    <th>OSM - Car (GraphHopper)</th>
  </tr>
  <tr>
  <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/5488e0c6-90f9-4311-8fa5-8843edadc493"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/16158788-a3c3-4ec3-aeb3-b9e0f9dd539b"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by ivanPyrohivskyi** [comment]
Cause of bug is road sign highway=give_way . This is adding [obstacle in 5 units](https://github.com/osmandapp/OsmAnd-resources/blob/2e4c0d3db30cde719950a4f65cf725bb8f50ac02/routing/routing.xml#L1143).
