### ISSUE TITLE
Feature request: Markers for photos/video/audio notes should have a direction-pointer  

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2008]
When we take a note (photo/video), we are-
(a) standing somewhere and 
(b) pointing our device at something. 

But when OsmAnd places a marker on the map, it only records only the location(a); and not the direction of our camera (b).

This detail is critical when we don't remember the place well.

**Desired:** The marker for any type of notes must have a direction-pointer, which points in the direction the camera was pointed at. 

This will also allow us to stand in one place, turn around, and take multiple snaps; thus capturing all details in all directions. Then the markers will tell me which photo records which direction. 

This applies to even the audio notes, because we are usually facing the object while talking about it. So the phone usually points to that object. 
- If the phone was held vertically, its back will face the object.
- If the phone was held horizontally, its top will face the object.

**Comment by sonora** [comment]
No action planned here, it seems.
