### ISSUE TITLE
cycleway:both=share_busway is too less used

### ISSUE THREAD

**Issue by schenklklopfer** [osmandapp/OsmAnd#20089]
### Describe the routing engine used (required)

- [x] OsmAnd's in-app offline routing
- [x] Any online routing provider: https://www.openstreetmap.org/

### Describe your routing Profile (required)

Routing Profile: bike, no restrictions

### Describe your start and end points (required)

https://osmand.net/map/navigate/?start=48.370671,10.901020&end=48.369521,10.892373&profile=bicycle#17/48.37050/10.89544

I just want to cycle up the road.
There is a nice cycleway on the whole road, but OSMand is planning a massive detour.

### Describe the actual route (required)

Both the app and https://osmand.net/map planes a detour here
![image](https://github.com/osmandapp/OsmAnd/assets/6595165/dc8e7ca6-1fd8-46ec-95d3-b0bffe7b2ce6)  
![image](https://github.com/osmandapp/OsmAnd/assets/6595165/65bed8ee-a4d3-4618-b240-bb72874910ee)

### Describe the expected route (required)

Route as the official [openstreetmap.org](https://www.openstreetmap.org) page route, in all three engines:
![image](https://github.com/osmandapp/OsmAnd/assets/6595165/1799f07f-120e-408f-83d8-9cb20903dad5)

https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=48.37065%2C10.90094%3B48.36982%2C10.89318#map=18/48.37027/10.89709
https://www.openstreetmap.org/directions?engine=fossgis_valhalla_bicycle&route=48.37065%2C10.90094%3B48.36982%2C10.89318#map=18/48.37027/10.89712
https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=48.37065%2C10.90094%3B48.36982%2C10.89318#map=18/48.37030/10.89706

### Describe what Maps you used (online or offline) (required)

- [x] Offline maps offered within the OsmAnd app for download. Map from: on iPad 01.06.2024 | on iPhone via OSMand+ 12.06.2024
- [ ] Online (tile / raster) maps 

### Your Environment (required)

```
OsmAnd Version: 4.7.6.3 | 4.7.7.3 (via Testflight)
Android/iOS version: iOS 17.4.1 | iOS 17.5.1
Device model: iPad 7th gen | iPhone 13 Mini
```

### Anything else? (optional)

If I choose a more direct startpoint the routing is correct!  
https://osmand.net/map/navigate/?start=48.370539,10.897890&end=48.369521,10.892373&profile=bicycle#18/48.36999/10.89403  
![image](https://github.com/osmandapp/OsmAnd/assets/6595165/258f9495-405c-4910-9610-3bdaa181a88d)  
![image](https://github.com/osmandapp/OsmAnd/assets/6595165/77511483-4a5b-4f05-829a-401bef0c4a35)  

I think this is related to a bus stop.
This bus stop is directly on the cycleway. This is correctly mapped in OSM data with "cycleway:both=share_busway":
https://www.openstreetmap.org/way/589530816

This Tag is correctly recognized in OSM, support has been added here: https://github.com/osmandapp/OsmAnd-resources/pull/861

So maybe this is an issue with "priority" of this Tag?  
If the way is short and direct enough the way is used, if it is longer a detour is planned.

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce this issue, choose the bicycle profile and attempt to create a route using the provided coordinates. Instead of following the bicycle path, the route takes a detour. 

You can view this in the web version [here](https://test.osmand.net/map/navigate/?start=48.370670,10.901020&end=48.369520,10.892370&profile=bicycle#16/48.3704/10.8917).

<table style="width:100%">
  </tr>
  <tr>
    <th>Web version</th>
    <th>OSM</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/cd1aab55-6a58-4125-b911-5502a2087086"  width="500" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/2190a6c5-b244-4bf8-84c4-90ee5c5cf995"  width="500" height="auto"/> </th>
  </tr>
</table>

**Comment by xmd5a2** [comment]
Fixed. No new maps required.

**Comment by DmitryAlexei** [comment]
now [OsmAnd web](https://osmand.net/map/navigate/?start=48.370671,10.901020&end=48.369521,10.892373&profile=bicycle#17/48.37049/10.89431) routing is the same as on [OSM](https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=48.37065%2C10.90094%3B48.36982%2C10.89318#map=17/48.37027/10.89710)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/bc124059-6d3a-4cda-996b-ed33ad272224"  width="600" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/3c4c6b46-f444-49bd-8a65-4f57fbae2731"  width="500" height="auto"/> </td>
  </tr>
</table>

- Android app matches web routing with the same settings. 
- in iOS app there is no separate setting for fastest route, so when balanced driving stile is selected, the route is different 

<table style="width:100%">
  </tr>
  <tr>
    <th>andoird</th>
    <th>ios balanced</th>
    <th>ios shortest routes</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/138edf33-afe8-4a99-9f7f-2d9829167a56"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/3ed28caf-a043-45f4-828c-3a57cd249a17"  width="300" height="auto"/> </th>
  <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/f6a1be55-77a7-4776-b64c-ff55ca0cc5a6"  width="300" height="auto"/> </th>
  </tr>
</table>
