### ISSUE TITLE
Option to lock the position of the movable buttons

### ISSUE THREAD

**Issue by hahihohehe** [osmandapp/OsmAnd#20081]
### Describe the idea (required)

My idea is to have an option to lock the 2D/3D toggle and quick action buttons in their position so that they cannot be moved accidentally.
Maybe a snapping option for moving the buttons could also help, but for my use case, being able to lock the buttons in the default position would be enough.

### Tell us about the expected behaviour (required)

My problem with the current behavior is that
a) The buttons are too easy to move and I accidentally move them every time I use OsmAnd as my bike computer app
b) It is hard to move the buttons back to their original position
c) The UI looks awkward with the two buttons adhering to the usual grid layout

### Tell us about alternatives you've considered (required)

Maybe an easier workaround is to add an action that relocates the buttons to their original positions (like double or triple tapping the button for example). This way moving the buttons back would be much easier and not a big deal.

### Context (optional)

#18022 is also related to buttons but is basically the opposite feature request to make the other buttons movable as well.
Maybe a combination of treating all buttons the same, having the option to move them, lock them in their position and snap them to a grid would be something everyone is happy with?

**Comment by dmpr0** [comment]
Duplicate https://github.com/osmandapp/OsmAnd/issues/19164
