### ISSUE TITLE
Reading map screen while navigating shouldn't require to unlock screen

### ISSUE THREAD

**Issue by speleoluc** [osmandapp/OsmAnd#20092]
### Describe the idea (required)

When navigating a (bicycle route), the user should be able to turn on the screen and get to the Osmand map without unlocking the phone, just like it works in Google Maps.

### Tell us about the expected behaviour (required)

Turn on the phone screen while Osmand has an active navigation and the map appears with having to unlock the screen.

### Tell us about alternatives you've considered (required)

Removing screen security :(

**Comment by dmpr0** [comment]
Implemented as Screen Control.
You can find it in Menu – Settings – Profile – General settings.

**Comment by speleoluc** [comment]
Cool! And best off all, it works not only while navigating a route, but
also while just recording a track.


-- 
Luc Le Blanc
