### ISSUE TITLE
bug: The video note does not produce a marker

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2009]
1. Long-press on any point on map.
2. From the overflow menu (three dots icon), select "Take video note" option.
3. After recording the video, check the place on the map. There is no marker (BUG!)
4. Check the video folder. The video is there.

**Conclusion:** While OsmAnd takes a video, it neither creates a video note marker nor associates it with the video.

**Comment by vshcherb** [comment]
Audio/Video is subject of big refactoring, so this issue won't be addressed now.

**Comment by raindropsfromsky** [comment]
Great! Only thing, I need this feature badly for creating OSM POIs. 
So any idea when this refactoring would be finished? Is it ongoing?

Thanks in advance!
