### ISSUE TITLE
My places / tracks / 3 dots / set "standard appearance" misses one option

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#20101]
### Describe the idea (required)

In this menu you can choose "existing" or "future" tracks. With this two options it is not possible to get the existing and the future tracks the same appearance. 

### Tell us about the expected behaviour (required)

Assuming a folder already contains some tracks.
Using standard appearance for the existing ones leaves the future tracks untouched.
Using standard appearance for the future ones, leaves the existing ones untouched.

### Tell us about alternatives you've considered (required)

An option "all" (existing AND future tracks). 

### Context (optional)

I thought:
deleting all tracks of a folder / setting standard appearance of the folder for future tracks / moving back the tracks into this folder
would help (all tracks are new then, but it didn't.
Tracks are still displayed in the standard profile-settings (red).

**Comment by sonora** [comment]
Regarding a 'manual reset', Iv would have thought this procedure helps:
- Stop Osmand
- In a file manager (not in OsmAnd),  rename a track or folder
- Restart OsmAnd: Since OsmAnd will not find the old folder anymore (and has no awareness it was simply renamed), it will delete its associated appearance settings in the database. And the renamed items are cosider3e new ones, there are no settings yet, anyway.
- May rename back then as needed.

**Comment by Rowin63** [comment]
It really works this way 👍
But that's really a lot to do, instead of having an option/setting for it. This can be a (temporary) workaround, but not "the" solution 😉

**Comment by sonora** [comment]
Regarding the feature request: Have you checked if not the option _'Apply to existing_' is simply mislabelled and actually performs '_Apply **also**  to existing''_? 

For me, then it would be good enough, I am not sure if there is really a use case for '_Apply to existing but not to new_. Because that contradicts with the purpose of a '_Folder **default** appearance_'?

**Comment by Rowin63** [comment]
Using "existing" just applies to the existing ones. Added tracks remain in the "standard" setting.

**Comment by Rowin63** [comment]
Anyway I don't see a need for separating in "existing" and "new" tracks.
If I set the sppearance _by folder_, I want it to affect the complete folder, all contained tracks, and not just for a selection.

What"s  your idea behind that?

**Comment by sonora** [comment]
I agree! Default is default for the folder. Period.

If you want certain files to appear different, you can always multi-select them (in selection mode  in the file list) and then collectively change particularly their appearance to deviate from the default.

'Apply to existing' to me is a buggy option inside a 'Folder default appearance' menu.

**Comment by yuriiurshuliak** [comment]
You can get that both current and future tracks have a same appearance. For a folder with multiple tracks, you can update the appearance for all tracks, for the entire folder.
To make sure new tracks added to the folder have the same appearance, select the folder - click the three dots - choose "Change default appearance," - select "Apply only to new." Make sure to match the appearance settings with those of the existing tracks.

OsmAnd~ 4.8.0#2545m, released: 2024-06-20

https://github.com/osmandapp/OsmAnd/assets/127092082/e868b3c3-536c-49ec-b653-39e0a149dcc0

**Comment by Rowin63** [comment]
Thank you!

**Comment by Rowin63** [comment]
> You can get that both current and future tracks have a same appearance. For a folder with multiple tracks, you can update the appearance for all tracks, for the entire folder. To make sure new tracks added to the folder have the same appearance, select the folder - click the three dots - choose "Change default appearance," - select "Apply only to new." Make sure to match the appearance settings with those of the existing tracks.
> 
> OsmAnd~ 4.8.0#2545m, released: 2024-06-20
> 

It's a bit complicated and confusing.
I will color my tracks as I did until now, I don't want to have to think about it how to do it correctly at every use.
But thanks anyway for explaining it 👍

**Comment by sonora** [comment]
It's really convoluted... Standard is standard.

So a potentiol for simplification would be to always apply a folder standard to all folder content which does not have an entry specific override. In my mind distinguishing between current and future standard is awkward.... 😉
