### ISSUE TITLE
kannada language rendering issues 

### ISSUE THREAD

**Issue by karthik-holla** [osmandapp/OsmAnd#20107]
The rendering of kannada language is not correct.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/25195422/b14cf941-70f5-44a9-b7b2-80eead8e79f0"  width="300" height="auto"/> </th>
  </tr>
</table>

All glyphs of the font is not seen properly.

We can add new light fonts like noto kannada font to render all glyphs correctly.

**Comment by yuriiurshuliak** [comment]
Related to #19780

**Comment by yuriiurshuliak** [comment]
The bug has been confirmed. To see it for yourself, switch the map language to Kannada and navigate to the coordinates 13.57665943854077, 74.86878943923617. You'll see that while the captions on the map display in Kannada, the lower portions of these characters are being cut off.

OsmAnd~ 4.8.0#2528m, released: 2024-06-18

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/7abf8736-866c-4c65-aafb-6e658159518d"  width="300" height="auto"/> </th>
  </tr>
</table>
