### ISSUE TITLE
roads appear on map (osmand online tiles)

### ISSUE THREAD

**Issue by basings** [osmandapp/OsmAnd#20108]
### Description

![Screenshot_20240615-073356](https://github.com/osmandapp/OsmAnd/assets/92867705/e9a83e53-fcac-4492-9c1a-1284085878df)
![Screenshot_20240615-073457](https://github.com/osmandapp/OsmAnd/assets/92867705/4b507034-abb7-4145-9902-3bded31251aa)
![Screenshot_20240615-073505](https://github.com/osmandapp/OsmAnd/assets/92867705/065f06a7-93fe-48d0-9fba-97add3b442a5)
![Screenshot_20240615-073523](https://github.com/osmandapp/OsmAnd/assets/92867705/c9cfa671-0930-4f1d-8e22-72dd1f7609db)

### Steps to reproduce

At this stage I don't know if it is reproducible

### Actual result

Roads on map

### Expected result

No roads

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.7.10
Android/iOS version: Grapheneos A14
Device model: Pixel 6
Crash-Logs: ?
```

**Comment by scaidermern** [comment]
Unfortunately there is currently some vandalism in the OpenStreetMap database, see https://community.openstreetmap.org/t/the-osm-standard-tile-layer-looks-wrong-white-lines-abusive-comments-etc/111583.
This affects all OSM database users, especially users of online tiles.

**Comment by basings** [comment]
Thank you!
