### ISSUE TITLE
Distance to map marker (flag) location alternates wildly (when map location is not GPS location)

### ISSUE THREAD

**Issue by mnalis** [osmandapp/OsmAnd#20112]
### Description

When you current map view is different from current GPS location (i.e. you have panned the map away), the distance to map marker alternates in confusing way. See the video:

https://github.com/osmandapp/OsmAnd/assets/156656/242e0dd6-8704-4a0b-9c06-cb08b6bdd472

_"dud Beina baka"_ sometimes show `60m` (i.e. distance from my current GPS location to the marker position as I'm very near physically) and sometimes `234 km`! (from current map view to the marker position)

### Steps to reproduce

1. have the `Map markers bar` widget enabled 
2. select `make active` on a map marker (flag) near your real position
3. pan the map to some faraway location
4. continue panning map around 

### Actual result

the distance (and direction) from current map location to map marker would always be shown

### Expected result

instead, display alternates randomly between showing:
- distance and direction to map marker from current map view
- distance and direction to map marker from GPS location

with no indication which one it is showing.

### Your Environment (required)

```
OsmAnd Version: 4.7.17 (from F-droid)
Android/iOS version: Android 14
Device model: Samsung Galaxy S23+
Crash-Logs: no crash
```

**Comment by sonora** [comment]
Yes, looks like _while you are in a panning gesture_, always about 1 sec after you start the gesture and until you take the finger off the map again, does the widget show the distance from the map center. Then reverts to the distance from the device location.Not sure if it's designed like that on purpose.

Also: Is it intentional that the widget does not appear immediately after setting a map marker, but only after subsequently tapping the "Back to location" button?

**Comment by mnalis** [comment]
> Not sure if it's designed like that on purpose.

I certainly hope that was not by design :sweat_smile: . If it was indeed intended that different data alternates while panning, some differentiation text should've absolutely been added to the text, e.g. `60m from GNSS location` / `234km from map center`, but even with such necessary clarifications it would be very strange UI decision IMHO.

**Comment by vshcherb** [comment]
It's documented so widget displays distance from touch

**Comment by mnalis** [comment]
> It's documented so widget displays distance from touch

Um, where is it documented? I'm looking at https://osmand.net/docs/user/widgets/markers/ and it says:

> The Map markers bar (Android) widget / Distance indication - Top bar (iOS) widget displays:
> * Distance from your current location to the selected point indicated by the Marker on the map ([Units of length](https://osmand.net/docs/user/personal/profiles/#general-settings) can be choosed in the Profile settings).

As far as I can see, it has no wording to indicate that the distance and direction displayed will change into something else if you touch the screen to pan the map (and then change again when you stop touching). 
I've created PR https://github.com/osmandapp/web/pull/427 in attempt to clarify that.

If that is indeed wanted behaviour as indicated, I'd still suggest that OsmAnd:
- indicates that in the widget itself (e.g. by adding `from map center` after the displayed distance in the widget while map is panning) to reduce confusion, and
- actually make the widget follow the map center while the map is panning (currently, it seems to display distance only to the initial point of touch which initiated panning, and does not update even while panning/zooming changes both distance and direction to the Marker position - which only adds to the confusion)

**Comment by EugeneZmeuk** [comment]
@mnalis I corrected Docs articles with actual info. (before I merged your commits). 
When the location is off, the widget shows a distance from the center map point to the marker.

**Comment by mnalis** [comment]
thanks for merging

>  When the location is off, the widget shows a distance from the center map point to the marker.

@EugeneZmeuk  I though so initially too, but my testing seems to show this is not the case. 

See this example video - center of the map is about the same in all cases, but:
- if I press on the upper part of the screen and pan a little, it says about 2km  
- if I press on lower part of the screen and pan a little, it says only about 800m. 
- if I press on the upper part of the screen again and pan a little, it says about 2km again 

So it seems always to be dependent exactly on which part of the screen I touched, and not on a center of the map.

https://github.com/osmandapp/OsmAnd/assets/156656/dfc7c66d-1286-4e00-928a-c3b1d8cc07a2

**Comment by EugeneZmeuk** [comment]
@mnalis 
yes, you are right, there are two scenarios for showing distance without the Location.
 - with touching map 
 - without touching

I re-wrote this info for Docs.
