### ISSUE TITLE
Editing the standard appearance of a Track folder is buggy...

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#20125]
### Description

) three tracks in a folder, named A, B and C.
) in "my places" I set the folders "standard appearance" to yellow and apply (at this point no question "existing or new" is asked). Apply.
) tracks A, B and C are yellow now.
) move one more track, named D, into this folder
) A, B and C are yellow, D is green.
) set the folders "standard appearance" again to yellow, now Iḿ asked "existing or new?" and select "new"
) tracks A, B, C and D are yellow. Fine!
) add another track named E to this folder.
) track E is green, but at this point also track D has switched back to green again!
) you can continue this game, and every time only the initial tracks A, B and C keep their color when adding a track. All the others are always set back to their previous color, when adding a new track.

### Steps to reproduce

See above.

### Actual result

Switching the previously added tracks color back to their origin when adding a new track.

### Expected result

Keep the color as defined.

### Your Environment (required)

4.8.0#2515

**Comment by Rowin63** [comment]
The same issue in the last playstore release +4.7.17

**Comment by Rowin63** [comment]
I couldn't reproduce today as it was yesterday, but the behavior is different every few uses...

Like: 
) In a YELLOW folder there are three tracks. 
) I move one track from the GREEN folder to the YELLOW one, and there it still is GREEN.
) set standard appearance of the YELLOW folder again to YELLOW and apply to "existing tracks"
) all four tracks are YELLOW now
) move one more GREEN track into the YELLOW folder
) content now is 3 Yellow and 1 GREEN
) but setting standard appearance again to YELLOW is not possible now, though there is a GREEN track in the YELLOW folder. But the color menu still shows YELLOW as set and I can't apply it again.

**Comment by Rowin63** [comment]
And "apply to new" on an empty folder does not do anything to moved tracks in this folder.

**Comment by Rowin63** [comment]
One question:
setting a folders appearance AFTER adding  tracks to it: are this NEW or EXISTING tracks?
Because they are ALWAYS changed, no matter what you select.
(+4.7.17)

**Comment by Rowin63** [comment]
Anyway, applying the standard appearance of a TRACK-FOLDER should automatically apply to all added tracks. Why should tracks I moved to a folder I defined as YELLOW be displayed in any other colour? Why to set the folders appearance as standard if the tracks don't follow this setting?

**Comment by vshcherb** [comment]
Default appearance only applied for tracks which don't have track color selected so it works as expected,  yo u need to change track appearance of selected tracks

**Comment by yuriiurshuliak** [comment]
As I understand it, this is expected behavior. The "Apply only to new" option affects only tracks that have not been assigned a specific color, meaning those with the default appearance. If you've set the default appearance for a folder and chosen "Apply only to new,"it won't affect tracks that already have a custom appearance set.

OsmAnd~ 4.8.0#2568m, released: 2024-06-24

https://github.com/osmandapp/OsmAnd/assets/127092082/7769064e-c8c3-42cc-9e31-88c1936a00e3

**Comment by Rowin63** [comment]
Yes of course, it depends on how you define it.
"new" to me is "new in this folder, no matter if editet previously or not". So "my" new is different from "your" new.
But: choosing "existig" does not follow this rule, "existing" means "all existing", even previously edited ones.
