### ISSUE TITLE
Unnecessary live update artifacts when downloading a network route gpx

### ISSUE THREAD

**Issue by Velomeloman** [osmandapp/OsmAnd#20122]
### Description

After editing the network route in osm, outdated parts appear when trying to download gpx. At the same time, the route is rendered correctly.

### Steps to reproduce

1) Find the recently edited route. [Example](https://openstreetmap.org/relation/9438111/)
2) Download Live updates
3) Make sure that the route is rendered correctly 55.61985 37.50595 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/109347561/5209c2b9-8710-40e9-a2a0-b44cf880a21d"  width="300" height="auto"/> </th>
  </tr>
</table>

4) Tap on the Name or Ref to display info about the route

### Actual result

Outdated parts appears:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/109347561/56bfb338-600e-4ad6-a536-db14db7a4022"  width="300" height="auto"/> </th>
  </tr>
</table>

### Expected result

The actual route GPX is loaded and displayed correctly same as render

### Your Environment (required)

OsmAnd Version:
OsmAnd~ 4.8.0#2528m, released: 2024-06-18

**Comment by vshcherb** [comment]
I suspect that Network Load Route doesn't take into account deleted ways (osm_way_delete tag) which is important to produce correct gpx

**Comment by ivanPyrohivskyi** [comment]
Maps for test:
[Russia_moscow_asia.obf on 01 June 2024](https://drive.google.com/file/d/1cAZowyyOLpGp2n7kjcReUfeGztssxE1o/view?usp=sharing)
[Russia_moscow_asia_24_06_00.of live-updates for June 2024](https://drive.google.com/file/d/1cAZowyyOLpGp2n7kjcReUfeGztssxE1o/view?usp=sharing)

**Comment by ivanPyrohivskyi** [comment]
Old part of _Зелёное Kольцо Москвы_ https://www.openstreetmap.org/way/1184447587

**Comment by ivanPyrohivskyi** [comment]
Tried tested on iOS.
Track is not show on the map.
<img width="400" src="https://github.com/user-attachments/assets/a0310dc8-ca72-429b-987c-e525bd6c5376" />

**Comment by Velomeloman** [comment]
> Maps for test:
> [Russia_moscow_asia.obf on 01 June 2024](https://drive.google.com/file/d/1cAZowyyOLpGp2n7kjcReUfeGztssxE1o/view?usp=sharing)
> [Russia_moscow_asia_24_06_00.obf live-updates for June 2024](https://drive.google.com/file/d/1cAZowyyOLpGp2n7kjcReUfeGztssxE1o/view?usp=sharing)
> 
> How to test.
> Disable live-updates and remove newly Russia_moscow map (June/Aug 2024).
> After put files into net.osmand.plus/files/Russia_moscow_asia.obf and net.osmand.plus/files/live/Russia_moscow_asia_24_06_00.obf .
> First test on night build before change (26.07.2024) and take attention on place 55.62120, 37.50140 . After using new build and compare change.
> 

Both links on same file Russia_moscow_asia.obf

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.8.0#2855m, released: 2024-07-29
tested with maps provided in the post above (from June) > issue fixed

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/1f0b3ac7-bbd9-4151-b375-299a37fc1e62"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/2f9245e1-2042-4811-849a-997a264d290a"  width="300" height="auto"/> </td>
  </tr>
</table>

OsmAnd TestFlight 4.8.0.4 
tested with June maps from the post above > no action needed 
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/980da960-934b-40d8-8ef9-41629ce3d374"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/17065545-edde-4ebf-bac4-8e33ada0e41b"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Velomeloman** [comment]
![Screenshot_20240730_081403_net.osmand.plus.jpg](https://github.com/user-attachments/assets/4e106c42-751c-4508-80bd-34ff28974bfe)

Fixed
