### ISSUE TITLE
Wrong city names in poi details

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/Osmand#2012]
I noticed different city names in poi details for poi in the same city. 
All are in 'pfalzgrafenweiler', but in some poi the city is 'haiterbach or 'dornstetten' with are nearby.
See screenshots for details
![screenshot_2015-12-01-07-53-41](https://cloud.githubusercontent.com/assets/11144987/11497949/9f1a2da0-981c-11e5-9622-bee8ecf67d66.png)
![screenshot_2015-12-01-07-53-07](https://cloud.githubusercontent.com/assets/11144987/11497951/a4e40396-981c-11e5-89cb-19e214544072.png)
![screenshot_2015-12-01-07-52-50](https://cloud.githubusercontent.com/assets/11144987/11497957/ab34f0de-981c-11e5-83e0-fc8689c03ece.png)

Maybe this is an osm map issue, but I don't know what is wrong.

Getting Simon

**Comment by sonora** [comment]
I think this could be the same issue I just opened here https://github.com/osmandapp/Osmand/issues/2013, and already referenced in comments here https://github.com/osmandapp/Osmand/commit/899ca5323125461364bb26ee4d674e46e4b14049#commitcomment-14697241

**Comment by jf-simon** [comment]
Yes looks similarly

**Comment by vshcherb** [comment]
Basically there some issues and now they fixed. I'll shortly explain how it works to simplify finding issues.

1. Searches for roads with name in routing section (road only maps) (!)
2. Searches in address section (Address search) street with that *name* in the radius 15 KM (used to be 20), so it could find streets in neighboor cities as well.
3. Sorts found streets by central location and ignores streets that are > 1 KM from the closest street (recently added)
4. Loads all the buildings from these streets and checks if there are buildings in 100 M radius.
If no buildings are found streets are displayed.
If no streets are found, road name is displayed

**Comment by sonora** [comment]
Victor, ok, see my comments and findings in #2013.

Looks like we sometimes still receive results either as road or as street (your points 1 and 2) for tapping on 2 different points on the very same street My point (2) in my latest comment in #2013. Not sure why. Looks like it depends on how far away from one end or from the other end of the street I tap?
