### ISSUE TITLE
Issue with village/town/city lookup in new geocoding module

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2013]
We have an issue still our new reverse address (village/town/city) lookup in the new geocoding module:

It appears that reverse lookup of places where a house number is associated with functions correctly, the village/town/city assignment seems to be the correct one. (this may jus be coincidental though, because maybe most street / house number combinations are unique to a single village/town/city only.)

But what fails regularly is the assignment of he correct village/town/city to places where only a street name resolution is possible (i.e. no house numbers in OSM, or nearest house numbers too far away from the point tapped): See screenshots below as an example, but this happens very frequently: The screenshot with the house number assigns the correct place name (Au-Haidhausen is the correct part of Munich [though not the postal address, but that's another issue]), while tapping on a nearby place in the same street where no house number is resolved produces "Dachau", a town about 20 miles away where also a street by the same name happens to exist.
![untitled1](https://cloud.githubusercontent.com/assets/845735/11500719/43585920-982f-11e5-84c6-57e9194877d0.png)
![untitled2](https://cloud.githubusercontent.com/assets/845735/11500724/478a0642-982f-11e5-8038-629ef9e9ff3e.png)

**Comment by vshcherb** [comment]
Just tested and it shows now Untere Au (for street) and with house (Obere Au). I guess it is not an issue because the street is in both and for house it shows correct

**Comment by sonora** [comment]
It works now for the Munich example location above, and also now explicitly shows "Munich" in addition t the correct city part, which is a good improvement. :)

Unfortunately, the original bug was not fixed elsewhere, here is another example location:
- In the address search, go to Germany-Bavaria / Hirschau / Hauptstraße
- When it is displayed on the map, long-tap on it: In all cases I have tried the reverse lookup will display "Hauptstraße (Dorfgmünd), Grafenwöhr", which is about 17km away from there.

I find countless examples where the correct address is listed in the (forward) address search, but for the reverse lookup a street name duplicate in a completely different town (but usually in the vicinity <20km) is shown.

"Hauptstraße" is a good test case for tis on German maps, because it means "Main Street", and many towns and villages have one, so there are usually many street name "duplicates" between different villages.

Also, related but not the same: When we  long-tap on a street name which also has a highway  ref, the reverse lookup *only* specifies the ref, not the street name. This could be improved to maybe show both, because in many villages streets like the "Main Street" will also carry a ref  like "A1234" for  e.g. a primary highway. People using the reverse lookup may be looking for the street (address)name or the ref, we do not know, so should probably show both, i.e. "A1234, Main Street, Amsterdam"

**Comment by sonora** [comment]
Yes, looks like now it works!

Remaining issues I now find, we can address or not:

(1) When we skip one or more unnamed roads to finally find a named one and display its name, I wonder if we should prefix the reverse lookup result with "Near  ". I have instances where I tap on an unnamed road, and the result displays the name of a nearby primary highway, which looks weird, because the point tapped is clearly NOT on that highway, but on the unnamed road some 500 m off.

(2) Another oddity, not sure if it is functionally important: I see residential streets in some villages, where
 - when I tap on some points on the street, the result correctly display "street_name, village_name"
 - while tapping on a similar point on the same residential street produces "street_name (village_name), county_name".
It is no big practical issue, but would not hurt if we understand why we have this behavior. Can provide examples if needed.

(3) Sometimes the reverse lookup takes a while, and it is unclear if OsmAnd is still looking, or has given up and no result could be found. Some sort of activity spinner somewhere on the screen while looking would resolve that ...

(4) the issue described above, where only ref and no street name is returned by the reverse lookup, which is bad in city/town environments, where people probably need street name or both

**Comment by vshcherb** [comment]
(4) where only ref and no street name,
That should be a situation when street name not found, otherwise we always display both. I'm afraid that can't be address and that's map issue
(3)
I do like current setup, because spinner is not related to primary function of context menu, it just additional information but let's see if we address it later when we get more concerns
(2)
This is exactly what we have in address search section, basically we have address search bug, because we should not (!) register county name as cities, so I think that's either map issue or address issue.
(1)
I agree with word "Near" we will hear less complains if it is not exactly correct.

**Comment by sonora** [comment]
Ok, thank you for the comments, but please have a look at the following:

Ad (4) Tap anywhere on "Bavaria / Oberding / Hauptstr." (http://www.openstreetmap.org/way/326137445). OsmAnd only shows "ED 5", right?

Ad (2) Have you inspected my example http://www.openstreetmap.org/way/29431102  ? I find no mapping issue there, but still, tapping on the western half of the street yields a different result than tapping on the eastern half, right?

**Comment by vshcherb** [comment]
(2) http://www.openstreetmap.org/relation/1059448#map=14/49.7353/12.1889
I think different relation is used http://www.openstreetmap.org/relation/2986290#map=11/49.7345/12.1498
Neustadt a.d.Waldnaab
Has a small mapping incosistency. 
Could be fixed either 1) either 2)
1) Name of relation boundary is different than city name "Neustadt an der Waldnaab"
2) Relation could have admin_centre http://www.openstreetmap.org/node/282442829 and that would fix the problem

**Comment by vshcherb** [comment]
(4) I think it used be a small issue in previous maps generation which caused it, please try new maps.

I will close the issue because only "Near " part is addressable for now feel free to open new issue for  "Near..." or fix it.

**Comment by sonora** [comment]
(4) confirmed fixed with new map generation.
Follow-up issue see #2018.

**Comment by sonora** [comment]
Still confused about your explanation regarding (2): Neither of the boundaries you mention seem to contain the residential street in question, right?

**Comment by vshcherb** [comment]
The issue that if city doesn't have proper boundary, then it will attract/steal streets from other villages (satellites) which also don't have boundary. If villages have boundary, then street will be registered for 2 cities.
