### ISSUE TITLE
Crash during backup process

### ISSUE THREAD

**Issue by Max1234-Ita** [osmandapp/OsmAnd#20144]
### Description

A friend who's currently travelling abroad just sent me this crash report:

```
Device : RT5
Brand : OUKITEL
Manufacturer : wheatek
Model : RT5
Product : RT5_EEA
Build : OUKITEL_RT5_EEA_V5.0_20230724
Version : 13
App Version : OsmAnd
Apk Version : 4.7.17 4717

```

[exception.log](https://github.com/user-attachments/files/15919341/exception.log)

### Steps to reproduce

Not sure of what to do to reproduce, the user was just trying to navigate to his destination.

### Actual result

The app kept crashing a few seconds after it was launched; the issue persisted even after restarting the tablet several times.

While traveling, the device has no network connection; only offline vector maps are present, mainly of Central Asia countries (Kyrgyzstan, Tajikistan): it kept crashing about 10/20 seconds after it was launched.

The user reported that the issue started occurring after he tried a data sync with OsmAnd Cloud, which apparently was successful.
OsmAnd started working again after cleaning up the app cache and restarting the device again, but the map updating was clunky and slower than before the issue occurred.

Switched to Rendering v.1 (v.2 was used until then) the performances improved a little, even though some info is not available, .i.e the road slopes, but at least he was able to reach the destination.

Hope these info are useful.

### Expected result

The device should not crash, some unhandled exception occuured (see atttached logfile).

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.7.17
Android/iOS version: Android v.13
Device model: Wheatek RT-5
Crash-Logs: 
[exception.log](https://github.com/user-attachments/files/15919530/exception.log)

```

**Comment by yuriiurshuliak** [comment]
The latest crash is in the backup when choosing to download. However, this issue doesn't appear to impact the navigation or post-start crashes, unless there is an issue with the maps. And, If you have live updates enabled, try deleting and disabling them as well.

Please also send us the logcat.log file generated when the app crashes.

**Comment by rimaille** [comment]
Hi, same problem here, android 11 (RMX3506_11.A.82 on a realme narzo 50i rmx3506.
Osmand from fdroid v4.7.10

Just opening the app and it crash after few seconds.
Deleting cache and rebooting the phone does not work.
Switching from rendering v2 to v1 is OK, Osmand does not crash anymore (thanks Max1234-Ita for the tip)

Here's the logcat.log.
[logcat.log](https://github.com/user-attachments/files/15935607/logcat.log)

**Comment by yuriiurshuliak** [comment]
Based on the information provided, it appears there are two issues:

- A crash during the backup process when selecting what to download, according to the crash logs in the bug description. [exception.log](https://github.com/user-attachments/files/15919341/exception.log)
- A crash related to OpenGL rendering, as noted by [rimaille](https://github.com/rimaille) in the comments, "Switching from rendering v2 to v1 is OK, OsmAnd does not crash anymore."

Regarding the second point, it might be related to live updates or another issue. There is no log of this crash.

**Comment by yuriiurshuliak** [comment]
@Max1234-Ita Could you please clarify if deleting live updates helped resolve the issue? Is this crash still occurring?
If so, please provide a crash video and profile settings.

**Comment by Max1234-Ita** [comment]
> @Max1234-Ita Could you please clarify if deleting live updates helped resolve the issue? Is this crash still occurring? If so, please provide a crash video and profile settings.

Actually the user ended up reinstalling OsmAnd from scratch, anyway he was not using any Live update, just offline vector maps with corresponding 3D relief and contour lines.

The dynamics of his crash, though, were quite similar to the description made by @yuriiurshuliak: some unspecified issue occurred during Cloud sync, then crash and rendering reverted to v1, then the app kept crashing as soon as v2 was re-enabled.

Sorry, but that guy is traveling through the entire Asia and he needed to continue his journey, so that seemed the most viable option.

**Comment by yuriiurshuliak** [comment]
The initial problem can be fixed by the Android team referring to the [exception.log](https://github.com/user-attachments/files/15919341/exception.log) attached above.
