### ISSUE TITLE
Imported track is flickering

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#20145]
### Description

I have a set of tracks and when displaying them, they are never stopping flickering.
Also they appear as dashed line (which does not exist in Osmand).

### Steps to reproduce

I don´t know, please see the attached track.

### Actual result

flickers, dashed line

### Expected result

Change that behaviour?

### Your Environment (required)

+4.8.0 but has been like this ever before with this set of tracks.

https://github.com/osmandapp/OsmAnd/assets/95540936/c05557ae-e5eb-4766-9761-961505bcde06

[Kap5_S_210_Omalo_Shatili.txt](https://github.com/user-attachments/files/15923489/Kap5_S_210_Omalo_Shatili.txt)
(track was renamed from gpx to txt for uploading)

**Comment by 0709wiwiwi** [comment]
The uploaded file is not a gpx (trk) track but a gpx (rte) route.
Find a conversion into a gpx (trk) track. Pse test again. (Remove .txt)
[Kap5_S_210_Omalo_Shatili.gpx.txt](https://github.com/user-attachments/files/15923859/Kap5_S_210_Omalo_Shatili.gpx.txt)

**Comment by Rowin63** [comment]
Thanks, I´m aware about the fact it´s a route ;-)

If this is the cause of this issue, you should inform your mail-support about that.
Long time ago, when I noticed this for the first time, I did ask the support about exactly this "effect" and I was told (when asking about the different behaviour between rte/rtept and trk/trkpt) that Osmad does not differentiate between and it´s all the same.

Thanks you confirmed it´s not the same for Osmand (and in general of course it´s not).

**Comment by 0709wiwiwi** [comment]
I am not part of OsmAnd support team nor even An OsmAnd app user.  (Mainly do some  tests with the OsmAnd web road matching feature). That's why I suggested to test the track file in the app. As most apps are supposed to trigger a calculation by a gpx rte import. Maybe the OsmAnd app implementation is different ?

**Comment by yuriiurshuliak** [comment]
The bug could not be reproduced. After importing the specified track, there is no flickering observed, but the track really does appear as a dotted line.

OsmAnd~ 4.8.0#2591m, released: 2024-06-26

https://github.com/osmandapp/OsmAnd/assets/127092082/cf5d4e67-ef64-46f3-8297-cf1604702ae3
