### ISSUE TITLE
Offline Routing: Unable to make simple left turn

### ISSUE THREAD

**Issue by 0xE1E10** [osmandapp/Osmand#2015]
For some odd reasons, osmand really really hates making a left turn at this particular intersection. http://www.openstreetmap.org/#map=19/37.38772/-122.08883
![screenshot_2015-11-24-23-08-50](https://cloud.githubusercontent.com/assets/16014333/11522625/fe11c696-986d-11e5-85ed-20d28322e35c.png)
It'd rather make a right turn and then u-turn.

This is a dual carriage way. So we're going thru 3 intersections nodes here. Let's zoom closer in to isolate the problem by telling it to make just the left turn right inside the intersection.
![screenshot_2015-11-24-23-09-42](https://cloud.githubusercontent.com/assets/16014333/11522665/850f6c0c-986e-11e5-886e-c115c3fadc24.png)

Zooming back out, you can see that osmand is telling me to go straight and make 3 right turns all around the block instead of making a simple left turn right in front of it!
![screenshot_2015-11-24-23-09-55](https://cloud.githubusercontent.com/assets/16014333/11522674/b7ed40b8-986e-11e5-8d2b-56da5a56aae2.png)

I checked the OSM data on JOSM. Don't see anything obviously wrong. The only thing I noticed is that El Camino Real (going east-west in the screenshot) is a member of a "right turn only" turn restriction. But not this intersection. It's with another road much much further down the road in the west outside of this screen.

**Comment by vshcherb** [comment]
There is algorithm specific in OsmAnd that it try to use roads of the same priority, so small interval of secondary between primary creates a big penalty and algorithm tries to avoid it.
To illustrate it I made a change http://www.openstreetmap.org/changeset/35718028 ( which doesn't change only priority for that small segment) and routing algorithm functions as expected. 

There is already another open issue related to basically same problem, so we are planning to address these issues in another way.

**Comment by pl71** [comment]
This issue is closed and I hope routing to be corrected soon.
My case is similar - 10 km detour i/o simple left turn from primary to tertiary road. No turn restrictions, all speed limits - 50 km/h
![screenshot_2015-12-07-10-50-38](https://cloud.githubusercontent.com/assets/4776779/11622872/7f8f3c1e-9cd1-11e5-92d4-0f71b76480b3.png)

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/issues/2015#issuecomment-162452656
To be honest with latest map (just updated myself don't see any issue).

**Comment by pl71** [comment]
With latest map from Dec, 07th:
![screenshot_2015-12-11-14-02-58](https://cloud.githubusercontent.com/assets/4776779/11743640/c8b70320-a011-11e5-8cc5-72a5f3829297.png)
Later I added turn restriction (no_u_turn) at the bottom of the image (where you can not make any u-turn in reality), so next map will be interesting.
