### ISSUE TITLE
Rendering, zoom and moving speed very poor since update 4.7.17

### ISSUE THREAD

**Issue by Udo1966** [osmandapp/OsmAnd#20154]
### Description

everything is describesd in the above title

### Steps to reproduce

zoom, moving screen. At the left upper corner a watch with seconds is diplayed, as well any touches at the screen is displayed

https://github.com/osmandapp/OsmAnd/assets/173617085/cd27eb4c-c77e-43cd-8eaa-62232ddd0711

 

### Actual result

no result, very poor speed, perhaps it was happend as well some software versions before. I haven't updated osmand for a long time.

### Expected result

fast application as before

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by Udo1966** [comment]
I've downloaded offline cards new and it works as before

**Comment by yuriiurshuliak** [comment]
The issue may be related to live updates, which should be fixed now. Please try to completely remove live updates, clear the cache, and then re-enable live updates.
