### ISSUE TITLE
Shape of favourites is not shown correctly

### ISSUE THREAD

**Issue by sushifan233** [osmandapp/OsmAnd#20152]
### Description

I'm using a lot of favourites with different colors, symbols and shapes. Problem is that in many cases the shape of a favourite is not shown correctly on the map, e.g.:

- An existing favourite has a square ==> shown correctly on the map
- Change the square to a circle ==> still a square on the map

- A new favourite is stored with a square - on the map the favourite has a circle

There are no problems with showing the correct colors and symbols.
There are no problems showing the shape on the list of favourites under "my places".

### Steps to reproduce

This issue does not happen all the time and I tried to find a "rule" when the error occurs - but I could not find such a rule. Therefore, I cannot provide "steps to reproduce" - sorry.

### Actual result

In many cases (but not always) the shape of a favourite is not shown correctly on the map, e.g. the favourite is stored with a square, but on the map you can see a circle.

### Expected result

The shape on the map should be shown as stored.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.7.10, downloaded from F-Droid
Device 1: Xiaomi Mi 10T Lite with Android 11
Device 2: Samsung Galaxy Tab S7+ with Android 13
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce this bug, ensure you have many favorites of various shapes, colors, and symbols on one map. When selecting a square-shaped favorite and attempting to change it to a circle, it will remain square-shaped on the map. However, clicking on it will show a circle in the context menu, and it will also appear as a circle in "my places."

The exact conditions to consistently reproduce the bug are unclear, but it doesn't occur if there are only a few favorites on the map.

Here's an export file of my favorites: [Export_2024-06-24.zip](https://github.com/user-attachments/files/15956237/Export_2024-06-24.zip)


OsmAnd~ 4.8.0#2568m, released: 2024-06-24


https://github.com/osmandapp/OsmAnd/assets/127092082/69fd85b4-3bda-428b-8ce7-168567d2824c

**Comment by sushifan233** [comment]
Many thanks for confirming the issue. And yes, my main favorites group contains about 150 members using all three shapes and a lot of different colors - I think that is "many".

**Comment by yuriiurshuliak** [comment]
The bug has been fixed. Now, if you select a favorite that is in the shape of a square and attempt to change it to a circle, it will successfully change its shape.

OsmAnd~ 4.8.0#2831m, released: 2024-07-24

https://github.com/user-attachments/assets/4fc595ae-4ab9-44e0-9fb3-91df7394a47d
