### ISSUE TITLE
Complex charachter rendering broken.

### ISSUE THREAD

**Issue by manuvarkey** [osmandapp/Osmand#2016]
Indic scripts (Devanagiri, Tamil, Malayalam, Telugu etc.) unlike western scripts (which has one character per codepoint) requires multiple codepoints to encode a charachter. The complex rendering required is already implemented in android. All android applications are displaying the scripts correctly. See the screenshot below.
![screenshot_2015-12-02-14-19-47](https://cloud.githubusercontent.com/assets/4415312/11526389/27310996-9900-11e5-9228-1b163bd27fe3.png)

Currently OsmAnd displays these scripts (checked in Malayalam script) without complex rendering. 
![screenshot_2015-12-02-14-16-06](https://cloud.githubusercontent.com/assets/4415312/11526420/665d2884-9900-11e5-8dba-82a48473825c.png)
However if the POI layer with point labels are selected, the point labels are printed out with proper rendering!
![screenshot_2015-12-02-13-33-21](https://cloud.githubusercontent.com/assets/4415312/11526457/a25dfcf0-9900-11e5-8497-a3f17f587d6a.png)

So it seems to be a problem with the the main vector renderer. I have tried changing the default fonts. But the issue persists. Kindly look into this issue as this makes the maps in many indic languages unreadable. The issue may also affect other scripts which may require complex rendering (like Arabic). Can anyone concur ?

OS: Android 5.1.1 (Cyanogenmod 12.1)
OsmAnd version:  OsmAnd+ 2.2.2

**Comment by vshcherb** [comment]
Duplicate #1161
