### ISSUE TITLE
Export Track

### ISSUE THREAD

**Issue by anten1222** [osmandapp/OsmAnd#20178]
if I want to open a track in another navigation system I get something like this

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/73232079/4ca79818-e069-4e71-ad67-166303adf11b"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by albansuser** [comment]
This seems to be normal when importing into Komoot. I just select the track that looks correct (bottom one) and everything works correctly.

Not sure that it is a fault with OsmAnd.

Cheers

**Comment by Velomeloman** [comment]
Edit track and save it simplified
![Screenshot_20240626_120312.jpg](https://github.com/osmandapp/OsmAnd/assets/109347561/0e147924-3b1f-4794-b269-670b10a8df37)
