### ISSUE TITLE
Remaining improvements for our new reverse geocoding lookup functionality

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2018]
(1) Implementation reminder: When we skip one or more unnamed roads to finally find a named one and display its name, prefix the reverse lookup result with "Near ".

(2) To make our reverse geocoding functionality complete, we should also display (in the details section of the context menu) the "Nearest POIs", either all within say a 100m radius, or  maybe the nearest 5 or so.

**Comment by sonora** [comment]
Victor, regarding implementation of (1): Do you think it is a good idea to implement like I originally thought: "Near" will only appear if we skipped unnamed routeDataObjects to finally find a named one, or should we simply implement a distance limit for p.dist of say 100m, above which "Near" would appear? - Thx, Hardy

**Comment by sonora** [comment]
Regarding (1): Let's see if this is good enough: https://github.com/osmandapp/Osmand/commit/3da2b24527777bd2854587e9bf5894ac87766367, think it might suffice (100m between connectionPojnt and searchPoint yields prefix "Near").

**Comment by sonora** [comment]
(1) Seems to work ok, except for long stretches of streets or highways, where even tapping directly on the can produce "Near ...", because the distance to the connectionPoint is too far. Not sure how t fix, but surely no big issue.

**Comment by sonora** [comment]
(3) Not sure yet why, but on some occasions our reverse lookup can take *extremely* long (like several minutes, sometimes it never seems to finish), seems to happen e.g. with searches around here: http://www.openstreetmap.org/#map=17/29.11908/-13.56849. (Looks like the address lookup somehow hangs, while November 28 build reports route name without address lookup comparatively fast).
When this happens it "blocks" also all subsequent searches, i.e. the search does not seem to get properly cancelled when a new location is long-tapped.
(Also RAM memory usage seems about 50% higher than with November builds, but not sure this is a necessity or an issue.)

**Comment by vshcherb** [comment]
(2) May be we could leave it as nice to have feature, not sure it is really needed.

**Comment by vshcherb** [comment]
(4) I think to rename the string to "Address not determined" back,  so people don't wait eternally.

**Comment by vshcherb** [comment]
(3) Requires investigation

**Comment by sonora** [comment]
Regarding (2): Urgently needed feature in my mind! People now see e.g. a restaurant icon or similar, tap on the map, and expect to find details about the restaurant. But for now we only deliver address - not enough!

(3+4) Tested I for some days now. I really like it how I works now!  I can only reproduce the issue where the reverse search seems to "hang" with this one area in the Canaries, my be a ma issue. I vote for leaving the strings as is, as it really works well 99%, rather investigate why sometimes it hangs (maybe we have a memory leak which needs fixing anyway, but it does not look like it).

**Comment by sonora** [comment]
Issue (3) has disappeared when upgrading to the latest Spain map.

So this leaves

(4) Issue with lookup if within the first 5 or so seconds after app startup, but it is probably a rare use case. All later or subsequent lookups work anyway, so not a priority, I would say.

(2) "List also nearby POIs, not just street address" as a significant feature improvement, because it makes our maps sort of "interactive"

If we invest any more time, I strongly recommend (2), it is a great step towards map discoverability without having to go through a "search" operation, so it is more apt while e.g. walking a sightseeing tour. through a city, discover things, and tap on the map to see details about them !  :-)

**Comment by vshcherb** [comment]
(2) Yes but I need to work on really "interactive" map i.e. all icons on the map should be clickable not only poi. So I will better focus on this.

**Comment by sonora** [comment]
Not sure what you are saying: All "icons" are POIs, in a sense?

**Comment by vshcherb** [comment]
I mean that icons on the map could be clickable the same as POI layer is clickable now.
