### ISSUE TITLE
Address search does not extend beyond 500 km

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#20180]
This issue was present even before the current bbox limitation to 500 km for #19932:

Go to the address search tab and type a street name: You will get only results which are closer than 500 km. Then tap the 'Increase search radius' button at the end of the search hits: The spinner will start again, but the list of displayed results never changes beyond the ones already found, still all <500 km.

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. When searching by object name, the search results are shown instantly within a 500 km radius. Pressing the 'Increase search radius' button does not update the displayed results; it continues to show only those within the initial 500 km radius.

OsmAnd~ 4.8.0#2610m, released: 2024-06-28

https://github.com/osmandapp/OsmAnd/assets/127092082/e1d895e2-3ff6-4430-9b7d-05c0bdf1b037

**Comment by vshcherb** [comment]
@yuriiurshuliak your video related toi POI which is different than Address search.
Not plan to fix address search > 500 km by street name, it's hard coded to have balanced speed for cases with many downloaded maps. 
Probably we will need to limit it more as we have different limits for cities
