### ISSUE TITLE
“Announce deviation from route” should run with every setting

### ISSUE THREAD

**Issue by EssBee59** [osmandapp/OsmAnd#20187]
### Describe the idea (required)

Message announcement by deviation from route is essential, especially when the option screen on/off is activated!
With the following setting I missed most of the time the announcement:

-Osmand 4.8.0 (compiled with the sources from 23th june)
-Bike profile (with brouter)
-"recalculate route by deviation" is ON
-"Minimal distance to recalculate route" (ROUTE_RECALCULATION_DISTANCE) = 20m (same problem with 50m)
-"Voice prompts" is ON
-"Announce deviation from route" is ON
-"Timeout after wake-up"  15 sec (turn screen on with "Navigation instructions Enabled") 

The idea is to get the announcement also with this setting

### Tell us about the expected behaviour (required)

The announcement of deviation from route should be functionning with every setting

### Tell us about alternatives you've considered (required)

As work-around I also tried to activate “Announce route recalculation”, but it in some situations the message were repeated continuously!

So I analysed the JAVA-sources and found a solution that seems well running for my setting!

Note: not tested with other setting, as example by parameter recalculate route by deviation is OFF), or with car profiles, etc..
It could also be necessary to set a minimum value for “minimal distance to recalculate route”, 20 m for bike, 50 m for car?

My changes:
VoiceRouter.java
Here the voice-message is only spoken when deviation-dist is >  OFF_ROUTE_DISTANCE (75 m in my case)
But as the route is recalculated after 20m the message is never sent…
Changes:
1-Call “announceOffRoute“ from RoutingHelper only when deviation-dist >  ROUTE_RECALCULATION_DISTANCE  (suppress the dist check)

2-announce the message only each 12 seconds (to keep my screen on in a deviation situation)

3- suppress the message “announceBackOnRoute”: 
    As the route is recalculated the message is not clear and confusing 
      a-The biker do not know whether he is back on the initial route or on a new calculated route
                b- The position is ok, but what about the direction?

RoutingHelper.java

1-Call “announceOffRoute” only when deviation-dist >  ROUTE_RECALCULATION_DISTANCE  
2-When “currentRoute == 0, use a new logic to calculate “distOrth”

(I attach the sources of my code which include special logging  )

### Context (optional)

[RoutingHelper.java.txt](https://github.com/user-attachments/files/16009797/RoutingHelper.java.txt)
[VoiceRouter.java.txt](https://github.com/user-attachments/files/16009799/VoiceRouter.java.txt)

**Comment by DmitryAlexei** [comment]
To summarize. 
You would like to have a faster (in time) notification about "deviation from the route"? 
So users can quickly know that they have left the track even when driving with the screen off.

**Comment by EssBee59** [comment]
> To summarize.
> 
> * You would like to have a faster (in time) notification about "deviation from the route".  So users can quickly know that they have left the track even when driving with the screen off.

Hello!
thank for reading my issue!
Yes, exactly: I want to know quickly that I have left the track even when driving with the screen off.
To have "faster"... I want first to receive the anouncement at all, if possible fast!

2 days ago I did not know, that only when ROUTE_RECALCULATION_DISTANCE >= OFF_ROUTE_DISTANCE the announcement occurs...
(who know that, who can calculate OFF_ROUTE_DISTANCE?)

I am just coming back from a MTB travel using my own/new version of Osmand;
With ROUTE_RECALCULATION_DISTANCE=10 meters...
The navigation and notifications worked fantastic, every deviation were announced within 12 and 15 meters!

It was a very good surprise to see that it is possible to navigate with this occuracy!
(On the 30 km tour I had only 1 error, as the OSM track was not perfectly mapped- it was 14 meters away!.) 

So, for bikers it would be nice to support ROUTE_RECALCULATION_DISTANCE >= 20 meters!
Regards

**Comment by vshcherb** [comment]
Voice prompt setting affects how fast turn or announcement is calculated however it's not possible to separate from other turns from now

**Comment by EssBee59** [comment]
> Voice prompt setting affects how fast turn or announcement is calculated however it's not possible to separate from other turns from now

Hello vshcherb,

Thank for your response...
But sorry, I do not understand what you mean with "separate from other turns"?

The enhancement I suggest is very limited and simple:
The "route recalculation" in Osmand is for me perfect.
(it is optional, the minimum deviation to recalc is configurable.. and it works in any situation)
 
But...currently  the min deviation to announce the deviation is not the same as the min deviation  to recalc!
So we have as example a deviation of 20 m that triggers a recalc  (same with 50m)
As the voice announcement is only done with a a deviation > 75 m, no message is announced...
By the next iteration 1 second later the route recalc is terminated (at least when using the Brouter) and the deviation is quite 0...

So, the biker who is not continously looking at the screen (possibly Off!) is not aware of the deviation/recalculation

Regards

**Comment by vshcherb** [comment]
That means we need to introduce setting or probably trigger announcement always with B-Router engine

**Comment by EssBee59** [comment]
> That means we need to introduce setting or probably trigger announcement always with B-Router engine

Hello vshcherb,

I created this isssue as I beleaved, there was an inconsistensy in the "deviation" processing:
(The min deviation to trigger a recalc is not the same as to annouce a deviation per voice)

But the logic in Osmand seams more complex as I thought.... (I tested with standard Osmand routing, the deviation were not announced in every situation- but it works possibly as designed)  

If a change for the "deviation announcement" is too complex or at risk, I would be happy with a change for https://github.com/osmandapp/OsmAnd/issues/20205 !

(please close this issue in that case)
Without loops in the recalc announcement by activating the announcement of route recalculation, the screen will be turned on in each deviation situation.
Regards

**Comment by EssBee59** [comment]
As the issue description is not clear, I now close it and will try to open a simplier request!
Regards
