### ISSUE TITLE
Search does not find Scottish parliament despite me hovering over it

### ISSUE THREAD

**Issue by mlell** [osmandapp/OsmAnd#20185]
### Description

it doesnt find it, maybe because its a relation?

### Steps to reproduce

* Go to cordinates: `55.95200 -3.17509*
* Tap the Search icon (looking gjass)
* Enter "Parliament"

### Actual result

the top hit is "Parliament Square" (55.94885 -3.19073), which is not near the Parliament in Edinburgh

### Expected result

Expected: It shows me [The Schottish Parliament, Relation 4599](https://www.openstreetmap.org/relation/4599)

### Your Environment (required)

```
OsmAnd Version: 4.7.10
```

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. To reproduce this bug, I downloaded the relevant map and navigated to coordinates 55.95200, -3.17509. When searching for "Parliament," I successfully found "Parliament building" and "Parliament house." However, "Parliament building" appeared 11th in the search results, and "Parliament house" was 18th.

OsmAnd~ 4.8.0#2591m, released: 2024-06-26

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/91142ee4-fc62-49b7-afda-10fcd49ef0a4"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by mlell** [comment]
Thanks for taking a look into this. "Parliament building" is indeed the name of one of the buildings that make up the mentioned relation. However, this is a mere coincidence. The tags for Tourist Attraction and Government building are not on this building but on the relation. Conversely, for example the debating chamber, clearly part of thw parliament, is not part of the "Parliament building" object. Therefore, I have the impression thad you did in fact reproduce the buggy behaviour by not recovering the mentioned relation.

"Parliament House" is unrelated to the Scottish Parliament" (https://en.m.wikipedia.org/wiki/Parliament_House,_Edinburgh)

26.06.2024 16:29:10 yuriiurshuliak ***@***.***>:

**Comment by mlell** [comment]
I just noted that I was not entirely correct. The found "Parliament building" is [Relation 12659152](https://www.openstreetmap.org/relation/12659152). The aforementioned relation 4599 contains most objects of relation 1265192, but in addition e.g. the MSP House at the west side of the parliament building. But neither of the two relations is contained within the other. So one could debate whether it could be mapped in a better way but the core problem stays that there is a government office/tourist attraction object which does not get picked up by the search

**Comment by vshcherb** [comment]
Fix needs to be carefully reviewed

**Comment by xmd5a2** [comment]
Parliament POI now appears in search list. However looks like sorting by distance is incorrect?
Scotland map will be regenerated today.
![photo_2024-08-16_10-22-56](https://github.com/user-attachments/assets/4430af31-5ef0-4306-a517-94e43fc513d1)

**Comment by ivanPyrohivskyi** [comment]
@xmd5a2 sort of searching results depends from the type of searched result item. Searched address (Parliament Square) is higher than point of interest (Parliament Building).
Priority is set in the [code](https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd-java/src/main/java/net/osmand/search/core/SearchCoreFactory.java#L110). Less number mean higher position in the list.

Priority of Parliament Square = 500 .
Priority of Parliament Building = 700.
