### ISSUE TITLE
Outdated menu item

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#20191]
### Description

The copy menu item in quick buttons is no longer needed.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/12549744/8d7d0e72-c50f-4f62-a93e-c04a9c173727"  width="300" height="auto"/> </th>
  </tr>
</table>

### Steps to reproduce

-

### Actual result

menu item doesn't work

### Expected result

The menu item is no longer needed and should be deleted

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
Upon investigation, you can notice that once Quick action buttons are added and enabled on one profile, they are automatically replicated to other profiles, but in a disabled state.  Therefore, using the "Copy from another profile" button on a chosen profile will just activate the Quick action buttons that are already enabled on the profile from which it was copied.

OsmAnd~ 4.8.0#2610m, released: 2024-06-28

https://github.com/osmandapp/OsmAnd/assets/127092082/8569d361-b6b6-44ec-b167-65fa9b4c3b5d

**Comment by Nine-Tailed** [comment]
Yes you are right.  Then it might be worth renaming the item.  copy button state from another profile

**Comment by DmitryAlexei** [comment]
Todo:
- [ ] disable action menu item (copy from another profile)
