### ISSUE TITLE
Fix for Persian and Urdu language maps

### ISSUE THREAD

**Issue by AmZaf** [osmandapp/Osmand#2019]
I have fixed a bug related to Arabic shaping which causes incorrect rendering of place names on Persian and Urdu language maps. The fix involves the icu4j library on OsmAnd/libs/icu4j and OsmAnd-java/libs/icu4j path. I have filed a ticket upstream at http://bugs.icu-project.org/trac/ticket/12021. The fix is slated for the next major release of the library. 
In the mean time, what is the best way I can contribute to Osmand? Will you accept a patched version of icu4j? I reckon the issue deserves high priority.

**Comment by AmZaf** [comment]
Edit:The original link to the icu4j bug report page was incorrect and has been corrected.

**Comment by sonora** [comment]
See my comment here!  https://github.com/osmandapp/Osmand/commit/d73f34d9d341fffa0d51c2c698dc8666acb806c3
