### ISSUE TITLE
OsmAnd Online GPS Tracker stuck at Authorization

### ISSUE THREAD

**Issue by tdoerges** [osmandapp/OsmAnd#20209]
### Description

It seems the OsmAnd Online GPS Tracker cannot log into the Telegram account. It is stuck in the authorization screen.

Telegram itself (i.e. the regular app) is working. It can send and receive messages.

### Steps to reproduce

- Start app
- Click `Continue` in **Welcome** screen
- Click `Accept` for privacy policies in **How it works** screen
  - FWIW: clicking on either privacy policy link (OsmAnd, Telegram) does not work, i.e. no privacy policy is shown.
- Enter phone number in field `Enter phone number` in Screen **Authorization** and click `Continue`

#### Actual result

Spinner keeps turning, but nothing else happens, see screenshot: ![osmand-tracker-authorization-hangs]

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/13660777/8380f9de-f881-4385-a67e-6f95979063c0"  width="300" height="auto"/> </th>
  </tr>
</table>

#### Expected result

After clicking `Continue` in the **Authorization** screen the app should not hang, but move to the next screen.

### Your Environment (required)

```
OsmAnd Version: 4.7.10 (F-Droid, net.osmand.plus)
OsmAnd Online GPS Tracker Version: 0.91 (Play store, net.osmand.telegram)
Android version: 14 (LineageOS 21-20240529)
```

**Comment by tdoerges** [comment]
Apparently some part of the OsmAnd tracker app must be updated.

Taking a look with `adb logcat | egrep -i 'osmand'` yields:

```
06-30 21:50:56.614  9076  9104 E net.osmand: TelegramHelper Receive an error: Error {
06-30 21:50:56.614  9076  9104 E net.osmand:   code = 406
06-30 21:50:56.614  9076  9104 E net.osmand:   message = "UPDATE_APP_TO_LOGIN"
06-30 21:50:56.614  9076  9104 E net.osmand: }
```

**Comment by amakhn** [comment]
Same here. Observing such behaviour for 2-3 days.

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce it, install the OsmAnd Online GPS Tracker app and attempt to register using your phone number. After clicking the Continue button, the loading icon spins indefinitely without completing the registration process. 

OsmAnd~ 4.8.0#2643m, released: 2024-07-01

https://github.com/osmandapp/OsmAnd/assets/127092082/dcd8256e-cf27-4316-9d2e-7ccd472fccc6

**Comment by dmpr0** [comment]
## ToDo
- [ ] Fix Authorization


**Additionally** 
Tapping on the **Telegram** and **OsmAnd Privacy Policy** links doesn't do anything

- [ ] Fix Privacy Policy links

**Comment by yuriiurshuliak** [comment]
The bug was fixed in the last nightly version. After entering the phone number, the authorization continues successfully.

https://github.com/user-attachments/assets/9f217f34-15c5-47a3-b06d-853049fd0d4c
