### ISSUE TITLE
OSM Live changes don't appear in Version 2 rendering, but do in Version 1

### ISSUE THREAD

**Issue by Enovale** [osmandapp/OsmAnd#20204]
### Description

I made many changes to the region around me to add new POIs, update Opening Hours, etc. This was a few days ago, so I see the up-to-date changes on the OSM website and on OSMAnd's web viewer. I made enough changes that I qualify for OSM Live, but after downloading the Live updates for my region, my changes didn't appear initially. After some troubleshooting I realized they do appear if I change to the Version 1 rendering engine. Switching back to Version 2 makes them disappear. I can search for the updates POIs and see the pin for it on Version 2, but I cannot see or click them otherwise.

### Steps to reproduce

- Add new visible data to the map via the Editing plugin or JOSM or whichever editor.
- Qualify for hourly updates.
- Go to Maps & Resources -> Updates, and enable updates for the relevant region.
- Update that region manually.
- Look at the map and notice the lack of new information.
- Enable Settings -> OsmAnd Settings -> Map Rendering Engine -> Version 1
- Go back to the map and notice the new data being rendered as expected.

### Actual result

Cannot see, or interact with data from the hourly update data that isn't in the base map unless Version 1 Map Rendering is enabled.

### Expected result

All new data is shown and intractable regardless of map rendering mode.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd~ 4.7.17
Android/iOS version: GrapheneOS 2024061700 Android 13
Device model: Pixel 4a
Crash-Logs: N/A
```

**Comment by yuriiurshuliak** [comment]
Related to https://github.com/osmandapp/OsmAnd/issues/20190
