### ISSUE TITLE
Introduce a new road-style "pale"

### ISSUE THREAD

**Issue by njam** [osmandapp/OsmAnd#20208]
### Describe the idea (required)

I'd like to propose adding a new road-style "pale" to the default map-style, which is defocusing roads by rendering all roads in the same bright grey.

This new road-style improves the readability of overlays like bicycle paths, hiking paths, public transport routes etc.

### Tell us about the expected behaviour (required)

When using the road-style "pale" I expect the road network that is rendered by default to have a non-colorful style, to not disturb other overlays rendered on top that use colors.

For example, let's say I enable the _bicycle_ app profile with the default map-style. It's very difficult to know which of these colored lines are bike paths, and which are road types:  
<img src=https://github.com/osmandapp/OsmAnd/assets/360800/ee97bb9a-0555-4da5-baed-d9a722b96e12 height=250>

With the "pale" road-style instead I can easily identify bike paths, basically any colorful line:  
<img src=https://github.com/osmandapp/OsmAnd/assets/360800/eebf818e-4075-4fb8-a5fd-41a8c6808ee9 height=250>

More examples:
| Default street style | Pale street style |
| ------------- | ------------- |
| Base map |
| <img src="https://github.com/osmandapp/OsmAnd-resources/assets/360800/f411b301-5ad6-4b25-9bdb-870424c532da" height=300>  | <img src="https://github.com/osmandapp/OsmAnd-resources/assets/360800/34362162-f3e9-42df-af43-9a70e3178e26" height=300>  |
| Public transport (tram + bus) |
| <img src="https://github.com/osmandapp/OsmAnd-resources/assets/360800/786af3b7-f9d7-4ba9-b0aa-bc3e1fe664d5" height=300>  | <img src="https://github.com/osmandapp/OsmAnd-resources/assets/360800/9386e84c-d8db-42e9-8567-0a8545d33b15" height=300>  |
| Bicycle routes |
| <img src="https://github.com/osmandapp/OsmAnd-resources/assets/360800/7c5d1b56-2d98-4fc2-82f8-3ee37e812bd9" height=300>  | <img src="https://github.com/osmandapp/OsmAnd-resources/assets/360800/28e93b51-5439-4781-9191-15e6225af29c" height=300>  |
| Base map zoomed out |
| <img src="https://github.com/osmandapp/OsmAnd-resources/assets/360800/d4f8a446-83e4-4bf0-bcfe-956158f90aae" height=300>  | <img src="https://github.com/osmandapp/OsmAnd-resources/assets/360800/9ba79acf-239f-4518-922f-bb051e7a3468" height=300>  |

### Tell us about alternatives you've considered (required)

Alternatively a different map-style could be used, but what I've seen there's no map-style available that defocuses streets, but still shows all relevant information as a base map.
It'd be possible to create new map-style, but that would be much more work and means a lot of functionality will be duplicated, and probably not maintained well (see also this ticket: https://github.com/osmandapp/OsmAnd/issues/18807).

### Context (optional)

The road-style "pale" would be useful for these existing tickets:  
- https://github.com/osmandapp/OsmAnd/issues/17373
- https://github.com/osmandapp/OsmAnd/issues/3168

I've created an initial pull request adding this new road-style "pale" here: https://github.com/osmandapp/OsmAnd-resources/pull/1085

**Comment by DmitryAlexei** [comment]
https://osmand.net/docs/user/map/vector-maps#road-style

**Comment by Friptick** [comment]
Amazing work @njam. This really closes the gap with Organic Maps on public transit. Thanks so much.
