### ISSUE TITLE
Xmas special 2016?

### ISSUE THREAD

**Issue by Matthias84** [osmandapp/Osmand#2020]
Hi there,

some FLOSS applications have an special christmas mode for fun (e.g. VLC, SuperTuxKart, ...). OSM on the other side has also some nice [Christmas related information](http://be2art.de/xmasmap/). So I like to suggest, to add an Christmas-POI Layer as a nice gimmick during december :santa:

**Comment by vshcherb** [comment]
I think we can make a Christmas map updated every day, though we don't have enough time to prepare properly for it.

**Comment by vshcherb** [comment]
May be next year :)
