### ISSUE TITLE
Location Not Yet Known

### ISSUE THREAD

**Issue by nimdajitam** [osmandapp/OsmAnd#20207]
### Description

OsmAnd+ installed via Play on GrapheneOS doesn't get location. No matter how long I wait. If I install OsmAnd~ it works normally and get location soon. Other apps work fine too (just like OsmAnd~). Location access is granted.

### Steps to reproduce

Install OsmAnd+ from Play on GrapheneOS and tap on "locate" icon.

### Actual result

I get error message 'location not yet know' in Slovene. No matter how long I wait.

### Expected result

Location pointer should mark my location on map.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.7.17
Android/iOS version: Android 14 (GrapheneOS)
Device model: Pixel 6
Crash-Logs: ?
```

**Comment by Jasper-Ben** [comment]
I sometimes face a similar issue. As a workaround I use [GPSTest](https://f-droid.org/packages/com.android.gpstest.osmdroid/). Maybe that helps?

**Comment by scaidermern** [comment]
Try setting the "Location source" in the OsmAnd Settings from "Google Play Services" to "Android API": https://osmand.net/docs/user/personal/global-settings#location-source

**Comment by nimdajitam** [comment]
@scaidermern Thanks, it worked. I use Google Play Services strictly in isolation without granting access to my location but didn't imagine OsmAnd has so many options available under settings.
