### ISSUE TITLE
access-Tags with barriers ignored

### ISSUE THREAD

**Issue by mirsto** [osmandapp/Osmand#2021]
osmand offline routing ignores access tags specified with a barrier to override default access patterns. This can be verified by asking osmand to find a route along node 287049957 at [1]. This node is tagged with barrier=checkpoint; access=yes. However, osmand handles it just like access=no, i.e., it computes major detours to avoid this checkpoint.

Default access patterns should only be assumed at barriers if no access tag is set.

--

[1] http://www.openstreetmap.org/#map=18/17.9366484/-91.738322

**Comment by Zahnstocher** [comment]
OsmAnd considers access tags on barriers.
But access=yes was added 10 days ago [1], the OsmAnd map is about one month old.
Please test it again with updated map, which should be available shortly.

[1] https://www.openstreetmap.org/node/287049957

**Comment by mirsto** [comment]
Sry, just received updates of some maps and didn't notice that Mexico wasn't the December version yet. Will try again.

**Comment by Zahnstocher** [comment]
New map was released, OsmAnd considers access=yes.

**Comment by mirsto** [comment]
Yes, works fine. Sorry for this invalid bug report. Closing it.
