### ISSUE TITLE
When changing a recorded track's name before saving, use that name in GPX, too

### ISSUE THREAD

**Issue by sjvudp** [osmandapp/OsmAnd#20211]
### Describe the idea (required)

When I change the suggested name at the end of a track recording, the name entered is being used to save the file, but the name inside the GPX file is *not* changed from the suggested one.
It would be much more consistent to use the same name inside GPX and for file name.

I'm talking about
```
  <metadata>
    <name>2024-06-15_15-31_Sat</name>
  </metadata>
```
being saved as  `2024-06-15_15-31_Something_Else.gpx` (for example)

### Tell us about the expected behaviour (required)

The name used to save the file should be the name stored inside GPX.

### Tell us about alternatives you've considered (required)

Editing the GPX file to make the name match.

**Comment by Rowin63** [comment]
Some other apps read/display this name tag and not the given file´s name, so it´s always a little bit confusing...

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce it, record a track using the Trip recording feature and give it a custom name. After recording, export the track using the Share function. Open the exported file in Notepad, and you will see that the custom name you specified is not displayed. Instead, it shows the default name, which includes the date and time of the recording.

OsmAnd~ 4.8.0#2652m, released: 2024-07-02

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/3ce08b14-4d79-4586-86c1-08789896a2fe"  width="300" height="auto"/> </th>
  </tr>
</table>

![photo_2024-07-02_12-26-21](https://github.com/osmandapp/OsmAnd/assets/127092082/468a7955-e0ad-468d-9538-c4145ab9dafb)

**Comment by Rowin63** [comment]
When saving a planned/created trip, both "route" and "track" names in the gpx file remain as "creating date" and are not changed to the given name.

**Comment by DmitryAlexei** [comment]
- [ ] track's name in metadata should be changed if track was created in OsmAnd
