### ISSUE TITLE
Driving region for India is incorrect

### ISSUE THREAD

**Issue by sanatsathaye** [osmandapp/OsmAnd#20227]
### Description

India is grouped under "UK, India, and similar" but we do not use miles at all, we use kilometers only. Left-hand drive is correct but not the unit.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/15162329/b750297c-0415-4daf-b6fe-254b6c581003"  width="300" height="auto"/> </th>
  </tr>
</table>

### Steps to reproduce

Go to Settings -> Browse Map (or any profile) -> General settings -> Driving Region.

### Actual result

India is grouped alongside UK in driving region.

### Expected result

India should not be grouped with UK. I have no idea what is the difference between Japan and Australia but either of those two are correct as we drive on the left hand side of the road and use kilometers/meters.

### Your Environment (required)

```
OsmAnd Version: OsmAnd~ 4.7.10
Android/iOS version: Android 14
Device model: Pixel 7
```

**Comment by vshcherb** [comment]
To do: We need to create separate entity for India (alternative to have Japan, India)

**Comment by sanatsathaye** [comment]
Thanks for the fix :D
