### ISSUE TITLE
Hide underground does not hide Operatunnelen / Festningstunnelen in Oslo, Norway

### ISSUE THREAD

**Issue by gjvons** [osmandapp/OsmAnd#20224]
### Description

The underground tunnels named _Operatunnelen / Festningstunnelen_ in the Oslo city center are showing up on the map even when hide underground objects is enabled.
The location of the tunnels: https://www.openstreetmap.org/search?query=oslo#map=15/59.9085/10.7367
These objects are tagged as tunnels with layer -2.

### Steps to reproduce

Open OsmAnd, navigate to Oslo, Norway.
Hide underground objects.
Look at the map.

### Actual result

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/16147699/a177987a-6b86-477b-a1fc-345092c0e8ee"  width="300" height="auto"/> </th>
  </tr>
</table>

### Expected result

As these tunnels are underground objects, the expectation is that they are not visible when underground objects are hidden.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.7.17
Android/iOS version: 14
Device model: grus (Xiaomi Mi 9 SE)
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
The bug has been confirmed. To reproduce it, go to coordinates 59.91041, 10.7356 and enable the "Hide underground objects" option. This should hide the tunnels, but the Operatunnelen / Festningstunnelen remain visible.

Web version link: [link](https://test.osmand.net/map/navigate/?start=59.910410,10.735600&profile=car#17/59.91112/10.73268)
OSM object link: [link](https://www.openstreetmap.org/way/204039531#map=15/59.9096/10.7396)

OsmAnd~ 4.8.0#2652m, released: 2024-07-02

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/fd82003f-003c-4ed8-9498-f77e61261ee6"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
tunnels are important for highway network and not consinder as underground objects such as rivers, tram lines...

**Comment by gjvons** [comment]
> tunnels are important for highway network and not consinder as underground objects such as rivers, tram lines...

...but not important for pedestrians or cyclists, as they usually are not allowed to use this kind of tunnels.

**Comment by vshcherb** [comment]
True we could hide for pedestrian / cyclists

**Comment by xmd5a2** [comment]
Fixed. No new maps required.

**Comment by dmpr0** [comment]
## Review 
- [ ] Todo is missing

**Comment by vshcherb** [comment]
we hide for pedestrian / cyclists

**Comment by dmpr0** [comment]
# Review 2
Hide what?

<table style="width:100%">
  <tr>
    <th>Car</th>
    <th>Pedestrian</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/3076d305-5e74-4929-b10a-4cbe98baf559"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/6b4af915-4970-4683-b342-ab5546663806"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] Tunnel and tunnel name is visible in Car and Pedestrian profiles

**Comment by Velomeloman** [comment]
The user should be able to enable the display of tunnels if necessary. Please add a switch to the Configure map - Details menu.

**Comment by xmd5a2** [comment]
In addition, cyclists and pedestrians are generally allowed to travel through tunnels.

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.9.0#3044m, released: 2024-08-21
Some tunnels that are allowed for pedestrians (and cyclists) are hidden on the map (see screenshots).
https://www.openstreetmap.org/way/750280494

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/5be3fe99-1335-49d1-9a2f-d6d6266df84b"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/908325fe-5488-4f2a-9ff7-5dbaed5447e0"  width="300" height="auto"/> </td>
  </tr>
</table>

- [ ] It is proposed to hide only tunnels prohibited for pedestrians / cyclists

**Comment by Velomeloman** [comment]
The basic request was to hide the tunnels when underground object hidden.
I think you should add a extra setting to the Configure map - Hide menu and not link it to cyclists and pedestrians.

**Comment by Velomeloman** [comment]
Some thoughts about this issue. Now, when hiding tunnels, interrupted road lines are formed that look incomplete. The idea is to show an icon at the ends of hidden tunnels, as it is now done for stairs.

![Screenshot_20240905_104650.jpg](https://github.com/user-attachments/assets/be17096b-1404-4f9d-b190-0e3e2a1f5a38)

**Comment by dmpr0** [comment]
Subway platforms should be hidden to.

**Comment by vshcherb** [comment]
Yes makes sense to have icon tunnel entrance

**Comment by xmd5a2** [comment]
Icons for hidden tunnels were added but there is a bug: if tunnel **without foot/bicycle=no** touches **highway= + tunnel=yes + foot=no** then no icon is added 
![изображение](https://github.com/user-attachments/assets/44c230aa-06d2-4240-b4ee-fc2789be6818)

**Comment by vshcherb** [comment]
We need maps for testing @xmd5a2

**Comment by xmd5a2** [comment]
**norway_oslo** map was regenerated
