### ISSUE TITLE
Edit POI: POi type is not removed from OSM

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#2023]
POI type is not removed from OSM when I edit POI and manually remove it.
I wanted to remove POI type and change it to not supported by osmand (custom tag). So I removed POI type (warning was displayed) and added custom tag. Then uploaded to OSM and checked data. There were two tags: old POI type and newly created tag. Old tag should be removed.

**Comment by vshcherb** [comment]
Store in map deleted keys ("--highway" means tag "highway" deleted)

**Comment by vshcherb** [comment]
#3470 & #2023 should be tested together

**Comment by rbovard** [comment]
@vshcherb Is this issue suposed to be fixed in OsmAnd+ 2.6.5? Because I had the same kind of #3470 today.
