### ISSUE TITLE
Osmand Live Data slows down routing considerably

### ISSUE THREAD

**Issue by Guylby** [osmandapp/OsmAnd#20231]
### Description

If "Osmand Live Data" is enabled in the routing configuration with the default Car profile, routing calculation time is very slow compared to "Osmand Live Data" Off
For example, for routing between:
Start: 43.11757 5.93478
End: 45.75915 4.86127
With"Osmand Live Data" Off: calculation ~11s
With "Osmand Live Data" On (Live updates enabled and downloaded only for half the regions the itinerary crosses): ~27s
With "Osmand Live Data" On (Live updates enabled and downloaded for all the regions the itinerary crosses): ~34s

| Osmand Live Data OFF  | Osmand Live Data ON (half the regions with Live Updates) |
| ------------- | ------------- |
| <video src="https://github.com/osmandapp/OsmAnd/assets/151167525/bd6cf80c-9d1c-47fa-8d3b-4e53daca7f6e">| <video src="https://github.com/osmandapp/OsmAnd/assets/151167525/9227bd82-c243-4ca2-b8cc-655efa2484a6">  |

### Steps to reproduce

Use a default Osmand Car profile, make sure that Osmand Live Data is off in the routing parameters and the app is restarted.
Start a navigation between two points
Record the calculation time

Change the Osmand Live Data to On in the routing parameters, make sure Osmand Live updates are On and updated for the regions the itinerary crosses
Restart the app
Start a navigation between two points
Record the calculation time that should be much longer

### Actual result

Routing with "Osmand Live Data" On is 3x slower than with Off

### Expected result

Routing takes a similar time with "Live updates" On or Off

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.8.0
Android/iOS version: 13
Device model: Sony Xperia 10iii
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. I attempted to create the same route with Osmand Live Data both turned off and on. As shown in the attached video, the time taken to build the route was identical in both scenarios.

OsmAnd~ 4.8.0#2670m, released: 2024-07-03

<table style="width:100%">
  </tr>
  <tr>
    <th>Osmand Live Data is turned off</th>
    <th>Osmand Live Data is turned on</th>
  </tr>
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/0810fac6-e64d-4c47-9d67-a0ef9a8eebe7"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/08f7b42b-9647-4284-aea4-cbc247d2c778"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by Guylby** [comment]
I tested again with the same route as above and the behaviour is not consistent:

First tries, the route could not even be calculated and a few errors popped up:
Error 1:
`net.osmand: RouteProvider Runtime error: Attempt to invoke virtual method 'net.osmand.binary.BinaryMapRouteReaderAdapter$RouteTypeRule net.osmand.binary.BinaryMapRouteReaderAdapter$RouteRegion.quickGetEncodingRule(int)' on a null object reference {main}`
Error 2:
`net.osmand: RouteProvider Runtime error: Attempt to invoke virtual method 'net.osmand.binary.BinaryMapRouteReaderAdapter$RouteTypeRule net.osmand.binary.BinaryMapRouteReaderAdapter$RouteRegion.quickGetEncodingRule(int)' on a null object reference {pool-5-thread-1}`

After that I deleted then downloaded all live updates again
Then everything worked as expected

However, deleting the live data again, then downloading it again (switching the update interval from Hourly to Daily for example), the problem started again.
Now route cannot be calculated again and the same error message pops up.

**Comment by yuriiurshuliak** [comment]
To clarify, it seems this is expected behavior, especially noticeable on longer routes. Our new HH routing relies on pre-calculated routes stored in maps that are updated monthly. Live updates do not include these pre-calculated routes, so the older A* routing is used instead. As a result, routes take longer to calculate when OsmAnd Live Data is enabled.

**Comment by Guylby** [comment]
Thanks for the update!

Maybe adding a warning as a subtitle to the Osmand Live Data toggle like "warning, may result in slower routing" would make it clearer

Should I close the issue since this is normal behaviour? Or leave it open for the bug found?

**Comment by vshcherb** [comment]
As new maps arrived and there is a problem to fix cumulative error, we advise to update main maps to July
