### ISSUE TITLE
Emergency access points clutter the map

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd#20230]
### Describe the idea (required)

Emergency access points are visible starting from 16 zoom level. In some locations (see 43.0057 -1.8933) , there are too many POI of this type, so they clutter the map. 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/009406c0-d779-4942-91ab-7b896fc61787"  width="300" height="auto"/> </td>
  </tr>
</table>

### Tell us about the expected behaviour (required)

It is proposed to show emergency access points starting from 18-19 zoom level and implement an algorithm to limit the number of objects of the same type on the map

### Tell us about alternatives you've considered (required)

Add option in Hide menu (or Details menu) to hide (or show) emergency access points on the map

**Comment by xmd5a2** [comment]
Fixed. No new maps required.

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.8.0#2816m, released: 2024-07-23 and TestFlight 4.8.0.1
issue was fixed in Android and iOS: emergency access points are visible starting from 18 zoom level, and they do not overlap other POI icons

https://github.com/user-attachments/assets/f67c370a-8789-4733-a39d-aa7da106c8d7


https://github.com/user-attachments/assets/a79eacab-59aa-4f02-8664-c4f11aae9a9a
