### ISSUE TITLE
Optimizing the terrain settings screen

### ISSUE THREAD

**Issue by Velomeloman** [osmandapp/OsmAnd#20241]
### Describe the idea (required)

Terrain settings have too many nested submenus.
Main screen:
![Screenshot_20240704_132918_net osmand plus](https://github.com/osmandapp/OsmAnd/assets/109347561/461c5cb3-5efc-4afb-a231-62b1c3fbee0c)
Color scheme screen activated by Modify button:
![Screenshot_20240704_132908_net osmand plus](https://github.com/osmandapp/OsmAnd/assets/109347561/0f92b50d-85eb-4a48-9ce6-7010ef453b33)
All colors screen activated by All colors button
![Screenshot_20240704_132904_net osmand plus](https://github.com/osmandapp/OsmAnd/assets/109347561/cd9f1e75-9ad2-4f16-a6e7-63847afd98c4)
Visibility screen activated by Visibility section in main screen:
![Screenshot_20240704_135034_net osmand plus](https://github.com/osmandapp/OsmAnd/assets/109347561/1ec8efed-28ff-4e4a-bdbf-a604d8f5a99d)

The user has to perform a lot of actions, switching to different screens to control the display of the terrain. You can't adjust transparency and change the color scheme at the same time. You cannot see the name of the color scheme without going to the All colors submenu. 

### Tell us about the expected behaviour (required)

![New](https://github.com/osmandapp/OsmAnd/assets/109347561/21d56afd-7fce-486e-bc34-4609106ea30a)
I suggest combining all the settings on the main screen. A preview of the available color schemes under the scheme legend. When the scheme is activated, its name is displayed below. The Visibility slider is available immediately on the main screen.

**Comment by dmpr0** [comment]
If you need to change terrain colorisation too often you can use Quick Action for this. It will be improvied to follow new structure.
