### ISSUE TITLE
Update: Android Playstore installs over a Nightly

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#20249]
### Description

On one device I´m running the nightly version.
Now, though nightly, the latest Android Playstore Update is offered for installing.
If doing so, the "nightly" is gone and you´re back to the Playstore Version. You then can´t update any nightly anymore, the option is gone.

This happened already at the previous Playstore Update and I was surprised and wondering what happened...
Finally had to de-install the Playstore Release and install a nightly again.

So if now again it will accidentally happen to run this offered Playstore Update, the nightly status will be lost again. I´ll try to remember and avoid that ;-)

But why this happens? 
This began perhaps one or two Playstore releases ago, but never before.
(as I remember, trying to install nightly and regular on one device alsways caused a conflict)

This button disappears after the update, because of the "regular" release:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/95540936/b8c0fa61-5ef7-4fe1-9cbd-2c22abd89b52"  width="300" height="auto"/> </th>
  </tr>
</table>

This is running:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/95540936/139282ec-ee9c-4b02-b5e2-973bbef4b5c0"  width="300" height="auto"/> </th>
  </tr>
</table>

Though in a nightly, the regular update is offered:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/95540936/889f49e3-59cd-4320-b20e-8c6669c736a6"  width="300" height="auto"/> </th>
  </tr>
</table>

I always use tis one:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/95540936/4eb0b85c-6564-49ca-bd84-cc9e537b4732"  width="300" height="auto"/> </th>
  </tr>
</table>

### Steps to reproduce

pls see above

### Actual result

pls see above

### Expected result

pls see above

### Your Environment (required)

Tab S6, Android 12

**Comment by sonora** [comment]
From what I know, essentially 2 things govern in Android what can be upgraded with what:
1. The software signature must be the same. And here I think ever since some time ago OsmAnd changed to also sign the nightly builds with the google release key (probably causing this phenomenon in the first place).
2. The apk (internal) version number must be the same or greater, but not smaller.

So very likely, in many scenarios you can actually manually update a google release installation again with a new enough nightly build. But since the google release version does not have the Builds menu item in its code, you have to manually download the nightly build install file you want (e.g. the full-arm64 apk file) from OsmAnd's download server.

**Comment by Rowin63** [comment]
I didn't try "download & install" a nightly again, over the playstore release. As I remember, this was not possible and caused a conflict... 
I was surprised that this "cross way" happened anyway.

I will give it a try somewhen.

**Comment by Rowin63** [comment]
Hmmm.
The installed nightly is ~4.8.0#2693 and the playstore is +4.8.1.
Ran the update, now it's the +4.8.1 without this "Build" button.
Downloaded the latest nightly (don't know about it's release number), tried installing it and got this message 👍

![20240706_105042](https://github.com/osmandapp/OsmAnd/assets/95540936/04941f36-c6b3-4666-a0df-9165ae13dd0f)

Probably because the nightly's number is lower than the playstores?

That would mean, I can't install any nightly anymore unless it's getting higher than 4.8.1?

**Comment by Rowin63** [comment]
At this point I have to de-install the playstore release to be able to use the nightly again.

**Comment by dmpr0** [comment]
You can disable automatic updates in Google Play for OsmAnd

**Comment by Rowin63** [comment]
Automatic updates anyway is disabled.
But if there is a bunch of updates offered you have to be careful to not tap Osmand accidentally (everytime tapping one app moves the list up or down, so it can happen easily).

But still my question from above is: will I have to wait now until nightly release number is higher than the playstores number is?

**Comment by sonora** [comment]
For the release build the apk number seems well synced with the official version number lately, current release 4.8.1 seems to have apk version 4801.

Perhaps the nightly is still at 4800 (or perhaps even at 4700,) would have to check in the code.

It's usually a good idea to not feverishly update the dev build apk numbers, so we can switch back and forth for testing.

**Comment by yuriiurshuliak** [comment]
I was unable to reproduce the bug on my end. To reproduce it, I installed both the release version from Google Play and the nightly version.Then updated the app via Google Play. After the update, I checked the nightly version and found that it remained unchanged. So, the nightly build was not replaced by the Playstore version. 

Meanwhile, the release version was successfully updated, as demonstrated in the video I attached.

In my experience, the two versions of the app update separately and do not interfere with each other.

OsmAnd~ 4.8.0#2700m, released: 2024-07-08

https://github.com/osmandapp/OsmAnd/assets/127092082/9d094585-43cf-4387-8e89-2ce147754805

**Comment by sonora** [comment]
@yuriiurshuliak Quite possibly your observations are accurate,  have never tried myself and am not saying they are not.

But just to eliminate some possible mistakes, have you tried this with equivalent packages? E.g. our google free release installs into net.osmand, and so probably do our nightly builds as featured on our web server. But our nightly dev builds install into net.osmand.plus and thus arw more like the paid google packages. I understand only packages which install alike are eligible to install over each other, while differing package names should install side by side, i.e. in parallel.

**Comment by DmitryAlexei** [comment]
In PlayStore it is proposed to update OsmAnd+ version (OsmAnd-android-full-arm64.apk), althoght I haven't got it purshased and installed (see screenshot). @EugeneZmeuk reported, that with automatic updates enabled his nightly version was replaced by the OsmAnd + version.
- As a workaround it is proposed to disable automatic updates for OsmAnd + in PlayStore

- Also tested OsmAnd nightly default (OsmAnd-default.apk) and it cannot be replaced by the OsmAnd free version.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/87ef59fd-0dd7-4c00-8f69-0a2d8c59b08a"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
As expected with same signatures

**Comment by Rowin63** [comment]
After de-installing the (unwanted updated) playstore release (and keeping the data) it is not possible to re-install a nightly again (... bla bla bla conflict...). It is necessary to de-install AND delete all data.

I don´t know and care about your signatures.

**Comment by Rowin63** [comment]
Since the nightly is a 4.9.x, the playstore update is not offered anymore 👍 Finally the "risk" of an "accidentally" update is gone.

**Comment by sonora** [comment]
Let's see if the issue returns  though, once the Play Store version gets updated to 4.9.x also....
