### ISSUE TITLE
Hungarian TTS reads Hungarian text with English voice

### ISSUE THREAD

**Issue by rkrisztian** [osmandapp/OsmAnd#20248]
### Description

When I configure the navigation voice (TTS, not pre-recorded) to Hungarian, it sounds like the Hungarian text is being read aloud with an English voice. Why is that? Only the pre-recorded Hungarian voice works properly.

For context, my phone's OS language is set to English, and the app's display language is also set to English. However, even if I change the app's display language to Hungarian, it doesn't make any difference.

### Steps to reproduce

Configure cycling with voice navigation enabled, with the language set to Hungarian (TTS, formal), and start navigation using the cycling profile.

### Actual result

You should hear Hungarian words spoken with an English accent.

### Expected result

Hungarian words should sound like Hungarian, not English.

### Your Environment (required)

```
OsmAnd Version: 4.7.17
Android/iOS version: 11
Device model: Galaxy XCover 4s
Crash-Logs: (Let me know if needed.)
```

**Comment by sonora** [comment]
You need to set your TTS engine to Hungarian. For this, go to your **Android** (not OsmAnd) settings menu and find tve Text to Speech item. For the selected engine, set the language to Hungarian. You may have to download or update  a respective language pack.

If the engine selected does not offer Hungarian as a choice, select or install another one . There is usually a Test button there to verify things work and sound correct.

**Comment by rkrisztian** [comment]
Thanks! The problem was that **I did not have the Hungarian TTS language pack installed at the OS level**. After downloading it, OsmAnd finally spoke in true Hungarian. Luckily, I did not need to set my TTS engine to Hungarian at the OS level, which would have been difficult for me to accept. Normally, I prefer English, but Hungarian street names are unrecognizable when the TTS engine speaks in English, so I make an exception there.

**Comment by sonora** [comment]
Yes, it's true. If you have the correct language pack present on the OS level (or TTS engine level if 3rd party), OsmAnd can usually use it based on the TTS language selection you make in the app, without having to change the TTS language setting at the OS level. (And this is also again independent from what display language you set for Android on the OS level, or for OsmAnd on the app level, or for the map).
