### ISSUE TITLE
Add the dirtbike:scale=survey option

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd#20258]
### Describe the idea (required)

The issue is created to discuss pull request
https://github.com/osmandapp/OsmAnd-resources/pull/1087

### Tell us about the expected behaviour (required)

See wiki update: https://wiki.openstreetmap.org/wiki/User:CMoffroad/Key:dirtbike:scale#How_to_map

### Tell us about alternatives you've considered (required)

dirtbike:scale=survey option is added to encourage mappers to explore and document additional trails in the network

**Comment by cmoffroad** [comment]
I've found a workaround that eliminates the need for the additional key, so you can close this item for now. Thanks for your understanding!
