### ISSUE TITLE
cannot zoom past level 19-20 in rendering v2 after a while

### ISSUE THREAD

**Issue by spongebyte** [osmandapp/OsmAnd#20250]
### Description

Hi,

I have a set of tiles in an sqlitedb file with zoom levels 10-21. I have the `OsmAnd development` plugin enabled which lets me have the `Zoom level` widget.

I am noticing a bug where I cannot zoom further than level 19, sometimes 20, when I am using `Map rendering engine` version 2.
I have noticed that if I switch to `Map rendering engine` version 1, the problem goes away and I can actually zoom up to level 23 (sometimes 22, is that another issue?).
If I switch back to `Map rendering engine` version 2, things will temporarily work as expected (also able to zoom up to 23 or 22), but after just a few minutes out of the app (a simple restart does not suffice, I am not sure how to trigger this bug precisely), the zoom level will be stuck again at 19 or 20.
The problem does not seem to happen with `Map rendering engine` version 1, i.e. I can activate version 1, leave the app for a good while, return, then still be able to zoom up to 23 or 22.

Thanks.

### Steps to reproduce

Enable the `Zoom level` widget.
Vector map on its own is enough to illustrate the problem on my side, no need to use raster tiles.
Try and zoom in. You may get past 19-20, or you may get stuck there.
If not stuck: leave the app and get back to it a few minutes later.
When stuck: switch to `Map rendering engine` version 1. It should be problem-free.
Switch back to version 2. For a short while it will work as intended. Then the problem will happen again.

### Actual result

Cannot zoom further than level 19-20 in `Map rendering engine` version 1.

### Expected result

Should be able to zoom to the same levels in both `Map rendering engine` version 1 and version 2, i.e. apparently level 22 or 23.

### Your Environment (required)

OsmAnd Version: OsmAnd~ 4.7.17
Android/iOS version: LineageOS 21
Device model: Pixel 6a

logcat01: when initially stuck at 19 on `Map rendering engine` v2
logcat02: switched to v1, zooming up to 22-23 works fine, then switching back to v2
logcat03: a few minutes later, stuck at 19 again
[logcat01.log](https://github.com/user-attachments/files/16115464/logcat01.log)
[logcat02.log](https://github.com/user-attachments/files/16115465/logcat02.log)
[logcat03.log](https://github.com/user-attachments/files/16115466/logcat03.log)

**Comment by yuriiurshuliak** [comment]
- Can you specify the type of tiles you are using? Are they custom tiles stored in an sqlitedb file, or tiles downloaded from OsmAnd? Were they added manually? If possible, could you provide a link to the sqlitedb file containing the tiles you are using?

This issue doesn't seem to occur with standard vector maps.

- Does this problem happen every time you follow the reproduction steps, or is it intermittent?

- What specific settings do you have enabled, such as map source, overlay, or underlay, that might affect rendering?

Could you also attach a video demonstrating how this bug is reproduced?

**Comment by vshcherb** [comment]
With vector maps it's possible to zoom in up to 22. Probably it's related to online maps

**Comment by spongebyte** [comment]
Hi. Apologies for the long delay.

Please see the 2 attachments.

In the video I show OsmAnd in a "stuck" state. I cannot zoom beyond level 19. If I go back to the home screen and resume OsmAnd, I'm still stuck at 19. If I close OsmAnd and re-open it, you can see that I am able to go to level 22.

The tiles I'm using are just a red rectangle as webp images in a sqlitedb file.

It is very difficult to say what triggers this. Sometimes I can go hours without facing the problem, sometimes I face it every few minutes. One trick is to exit OsmAnd and restart, another trick is to switch to rendering v1 then back to v2.

Thank you.

[red.sqlitedb.zip](https://github.com/user-attachments/files/17179530/red.sqlitedb.zip)

https://github.com/user-attachments/assets/3ab0e69e-29f3-4117-8ff7-6fd476e8390b

**Comment by Hedaja** [comment]
I can confirm this behavior on my phone.
I noticed it today when I was using a raster map and then switched back to offline vector map. I still couldn't zoom past zoom 19. After restarting OsmAnd it works again.

Device : kiev
Brand : motorola
Manufacturer : motorola
Model : moto g 5G
Product : kiev_retaile
Build : RZKS31.Q3-25-15-11
Version : 11
App Version : OsmAnd~
Apk Version : 4.8.6 480603
[logcat.log](https://github.com/user-attachments/files/17531008/logcat.log)
