### ISSUE TITLE
Offline navigation: Strange detour through service route.

### ISSUE THREAD

**Issue by pl71** [osmandapp/Osmand#2025]
![screenshot_2015-12-03-11-33-39](https://cloud.githubusercontent.com/assets/4776779/11601334/13eca250-9adb-11e5-83ac-86dba56865eb.png)

You can see on the attached screenshot - recommended route passes through gas station instead on the main street. Location is here: http://osm.org/go/x1u3eA01k--?m=

There are turn restrictions at both ends of the service road, but they should not assume such a routing.
Maybe OsmAnd wrongly interprets turn restrictions?

**Comment by stephan75** [comment]
Does this service way have a maxspeed tag in raw  OSM data ?

**Comment by pl71** [comment]
No, there is no maxspeed tag at the service road, but tag exists on the main road - 50 km/h (within city limits).
Probably that is the reason - passing through service road with higher speed is faster in theory.
So the question is - what speed OsmAnd uses for calculations? :)
And is it possible speed for all streets within area=residential for a given country to be set at max 50 km/h or what are the local regulations?

**Comment by Zahnstocher** [comment]
There is a wrong turn restriction:
https://www.openstreetmap.org/relation/5175959
https://www.openstreetmap.org/directions?engine=mapzen_car&route=43.23202%2C27.89408%3B43.23132%2C27.89596#map=16/43.2327/27.8939
Maybe there was another wrong turn restriction at OsmAnd map creation time.

**Comment by Zahnstocher** [comment]
By the way, you can check turn restrictions here:
http://map.comlu.com/?zoom=19&lat=43.23148&lon=27.895298&layer=Grayscale&overlays=FTT
There is a warning:
> Really only_straight_on? Deviation angle is 129.1°

**Comment by pl71** [comment]
Yes, this turn restriction was wrong. Already corrected.

**Comment by sonora** [comment]
I had 2 complaints from r2.2.3 users last week saying they were routed via a motorway rest area on a Germany motorway instead of going straight on. Not quite sure, it this may actually be a new issue we have in our routing, and not just related to mapping issues?

**Comment by Zahnstocher** [comment]
> Not quite sure, it this may actually be a new issue we have in our routing, and not just related to mapping issues?

Yes, it seems to be a new OsmAnd issue, not a mapping issue.
I didn't find another (now deleted) turn restriction in old data.
I also blocked the service road (block road feature of OsmAnd) to force OsmAnd to use the secondary, but then it was not able to calculate any route, thus it is not a weighting/speed/priority problem.

**Comment by vshcherb** [comment]
Map regenerated, about deviation from motorway. It can't be a new bug, because routing didn't change for 2.2. But I can confirm that bug still exists, we need to investigate it.
