### ISSUE TITLE
Brands in Search categories

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#20256]
### Description

What is this kind of bullshit ?
How can i remove it ?
It is not possible to handle / remove it in "Rearrange categories"

Lukoil to Super u
Carrefour market to Sparkasse

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/18628183/5af47d8b-9321-4302-b38a-94829beb7630"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/18628183/96318ec8-4b8e-44bc-8e37-9d9b4b511064"  width="300" height="auto"/> </td>
  </tr>

### Steps to reproduce

Open search

### Actual result

Dammned advertising

### Expected result

No advertising

### Your Environment (required)

OsmAnd Version:  OsmAnd~ 4.8.0#2682m, veröffentlicht: 2024-07-04
Android version: 10, 12
Device model: samsung s10, tab s5e

**Comment by pebogufi** [comment]
The list changes from time to time. Sometimes more items, sometimes less and other items.

**Comment by dmpr0** [comment]
We are working on adding search and filtering by Brands that present in POI data. 
Do you have custom categories for Filling / Gas station?

**Comment by dmpr0** [comment]
> > We are working on adding search and filtering by Brands that present in POI data. Do you have custom categories for Filling / Gas station?
> 
> No, nothing like that. Do you want a export for examining ? Very surprising in both vevices:
> 
> * This morning no more ads like in that example.
> * App version unchanged.
> * The only thing I changed is July update for some maps.

We have added brand data since the July map update. We were able to reproduce the issue. Thank you!

**Comment by dmpr0** [comment]
Fixed https://github.com/osmandapp/OsmAnd/pull/20260. Should be available in the next nightly updates

**Comment by pebogufi** [comment]
Thanks a lot and sorry for my angry comment

**Comment by vshcherb** [comment]
-  [ ] Crash Show on map
