### ISSUE TITLE
regression. color palette is much reduced

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#20255]
### Description

A lot of colors are lost, default colors and user defined

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/18628183/0ab4aa88-a049-4961-beaa-b21061a03921"  width="300" height="auto"/> </td>
  </tr>
</table>

### Steps to reproduce

set a color of a poi

### Actual result

Only 5 colors available

### Expected result

My existing colors available (much more)

### Your Environment (required)

OsmAnd Version: OsmAnd~ 4.8.0#2694m, veröffentlicht: 2024-07-06
Android version: 12
Device model: samsung S10

**Comment by pebogufi** [comment]
I made same investigations.
I found this color handling, in example all with same color, bright yellow.
(1) Color palette   (FF**EEEE10**), first two digits are transparency
(2) favorit, extension group def (color="#**eeee10**")
(3) new file user_palette_default.txt (5.0,238,238,16,255)

The first two formats are the same, (1) with leading transparency, (2) without transparency.
With Color palette it is possible to import or export color with the hex code via clipboard.
So a user is able to get a special color from a different installation or source and import it via Color palette or export for different use.
This is a very nice feature !
Unfortunately the new file "user_palette_default.txt"  does NOT use hex  format for RGB coding.

**My recommendation:** 
 -1 please use new file **user_palette_default** also in **xml format**, then the coding format will be the same and transferable/interchangable between different installations or purpose.

-2 after installing a older version (about 4 weeks old), all my colors are back !! 
So it is obvious, that the colors are somewhere in the database. 
**Please convert all existing colors to new version** !

**Comment by pebogufi** [comment]
I suppose the problem occured after installing nightlys during some days or weeks, while the new color handling was created.
If you remove the file "user_palette_default.txt" the color palette is empty.
Currently i get it work.

Please have a look on my ideas above in second posting...

My recommendation:
-1 please use new file **user_palette_default** also in 
**xml format**, then the coding format will be the same and transferable/interchangable between different installations or purpose.

**Comment by nazar-kutz** [comment]
@pebogufi It seems like You already had old "user_palette_default.xml" file that contained only 3 predefined colors in it. This file was edited on repository and predefined colors count was increased, but new version of this file did't import when You install a new app version, becouse You already had one.

What about custom colors, we need more information to fix this problem. Could You please send us a backup file with Your settings?

We will fix both this problems and increase colors count presented by default.

**Comment by pebogufi** [comment]
I think our last posting were overlapping. 
On one device i got it work, then copied "user_palette_default.txt" to second device. 
So this problem is solved.
I had NO user_palette_default.**xml**.

What do you think about my recommendation above to use user_palette_default in **xml** format for geting it
transferable/interchangable between different  purpose (same color code format with favorit and color code palette).

**Comment by sonora** [comment]
Perhaps this is somehow related to  #20233, in particular to the second post there with my observation about the much reduced color selection for gpx tracks?

**Comment by nazar-kutz** [comment]
@pebogufi Yes, I accidentally made a mistake. I meant the file "user_palette_default.**txt**", not "user_palette_default.**xml**". Regarding the using of **xml** format, I need to discuss this idea with Product Owner.

**Comment by pebogufi** [comment]
I suppose there is an old place (database) with colors before new file user_palette_default.txt was created. What about if this file does not exist, then create it new and fill it from the old db? So the situation with only 3 colors can be handled by deleting the file.
