### ISSUE TITLE
Improvements for OSM carto style

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd#20259]
### Describe the idea (required)

It is proposed to change style of admin borders & parking spaces in OsmAnd's OSM carto style.
Issue is created to discuss proposed changes

### Tell us about the expected behaviour (required)

See pull request https://github.com/osmandapp/OsmAnd-resources/pull/1088

### Tell us about alternatives you've considered (required)

It is expected, that admin boundaries and parking space rendering in OsmAnd will match OSM carto.

**Comment by xmd5a2** [comment]
PR merged and tested. No new maps required.
