### ISSUE TITLE
Do not use the gray color for slopes

### ISSUE THREAD

**Issue by Vucumpra** [osmandapp/OsmAnd#20264]
### Describe the idea (required)

When the route color is set to slopes, flat roads are gray and therefore not sufficiently or immediately visible.
At present, the route is not clearly identifiable :
1. It's difficult to appreciate the choice of roads when the entire route is visible.
2. it's dangerous when driving.

![Screenshot_2024-07-08-21-31-10-161_net osmand plus](https://github.com/osmandapp/OsmAnd/assets/156325356/f59448d9-cbf1-4891-b4c6-0b682d85632d)

### Tell us about the expected behaviour (required)

Abandon gray for flat roads.
Gradually change from green to yellow without using grey.

For ascents, do not change anything.
For flats and descents: use green earlier, and when the road is downhill, start using shades of blue.

Perhaps add a border as well?

### Tell us about alternatives you've considered (required)

no idea

**Comment by sonora** [comment]
It would mean to abandon a clearly identifiable and rather self-explanatory color for flat slopes, they would then disappear in the 'soup' of colors used to identify ascents and descents.

**Comment by Vucumpra** [comment]
**Yes of course, a personal palette is the best way !**
I didn't propose the idea of a personalized palette because it had already been suggested but never adopted.

**Comment by dmpr0** [comment]
> **Yes of course, a personal palette is the best way !** I didn't propose the idea of a personalized palette because it had already been suggested but never adopted.

Current nightly and beta builds is supports custom color palettes for routes and terrain. You can get example files here https://github.com/osmandapp/OsmAnd-resources/blob/master/color-palette/route_slope_default.txt

**Comment by sonora** [comment]
Exactly. Put a copy of that file in your device's OsmAnd color-pallette folder, replacing (or simply editing) the corresponding file new builds (and the next release version) already have there.You simply need to edit the 0-value line of the file, which produces the current gray.

**Comment by Vucumpra** [comment]
Ok nut I don't have access to slope palette on nightly because I dont't have an account forOsmand+
So, actually I use Fdroid version

**Comment by sonora** [comment]
Next Fdroid version probably will have it also.
