### ISSUE TITLE
Online tracking is always loggin even when no recording is done

### ISSUE THREAD

**Issue by martinmolema** [osmandapp/OsmAnd#20268]
### Description

I have recently configured OsmAnd to start online logging. Reading the docs it seems that it should only do http-calls when the recording is done. However, when I start OsmAND on my android phone (android 14, Samsung A25 5g) it immediately starts doing http-requests

### Steps to reproduce

- Start OsmAnd on Android
- go to plugin-settings via the hamburger menu
- install the GPX Recording plugin 
- go to settings
- enable online tracking
- set update interval to 5 seconds
- update URL to reflect your online destination
- create an online script to capture the results
- close OsmAND
- Look at your logged results
- open OsmAND and do *NOT* start to navigate or record a trip
- wait a minute and look at your logged results. 
- notice how the logs fill although no recording is done in OsmAND
- optionally add the 'record gpx' widget to see if the light is white (not recording), red (recording but not sending http calls) or green (recording and sending requests)

This is my script:
```php
<?php
   $lat = filter_input(INPUT_GET, "lat", FILTER_SANITIZE_STRING );
   $long = filter_input(INPUT_GET, "lon", FILTER_SANITIZE_STRING );
   $timestamp = filter_input(INPUT_GET, "timestamp", FILTER_SANITIZE_STRING );
   $hdop = filter_input(INPUT_GET, "hdop", FILTER_SANITIZE_STRING );
   $altitude = filter_input(INPUT_GET, "altitude", FILTER_SANITIZE_STRING );
   $speed = filter_input(INPUT_GET, "speed", FILTER_SANITIZE_STRING );

  $fp = fopen('gpslog.txt','a');

  fprintf($fp, "%s|%s|%s|%s|%s|%s\n", $lat, $long, $timestamp, $hdop, $altitude, $speed);
  fclose($fp);

?>

```

### Actual result

Online trackign is always sending http-requests
The recording light on the widget is white (not recording)

Using the script i get these results:

```text
52.51145|6.1518087|1720515114647|3.6|-9.209999|4.4775305E-16
52.51145|6.1518087|1720515120266|3.307|-9.209999|4.4775305E-16
52.51145|6.1518087|1720515125631|3.666|-9.209999|4.4775305E-16
52.51145|6.1518087|1720515130651|4.147|-9.209999|4.4775305E-16
52.51145|6.1518087|1720515136636|3.915|-9.209999|4.4775305E-16
52.51145|6.1518087|1720515143634|3.8|-9.209999|3.9262214E-17
52.51145|6.1518087|1720515149636|3.91|-9.209999|3.9262214E-17
52.51145|6.1518087|1720515155637|3.5|-9.209999|3.9262214E-17
52.51144|6.1518154|1720515160651|3.337|-7.209999|0.01637021
52.51144|6.1518154|1720515166637|3.594|-7.209999|1.3823051E-5
52.51144|6.1518154|1720515171662|3.4|-7.209999|2.7363166E-8
52.51144|6.1518154|1720515177630|3.729|-7.209999|1.0736591E-11
52.51144|6.1518154|1720515182635|3.439|-7.209999|2.0737196E-14
52.51144|6.1518154|1720515187647|3.5|-7.209999|2.762551E-16
52.51144|6.1518154|1720515193634|3.882|-7.209999|2.762551E-16
52.51144|6.1518154|1720515199639|3.5|-7.209999|2.762551E-16


```
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/3585494/1a83958c-fa66-40f5-92d1-9ac26cff269d"  width="300" height="auto"/> </th>
</table>

### Expected result

Only do HTTP calls for online tracking when I actually pres the record button in the widget. This is costing too much mobile internet traffic.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.7.17 (2024-05-07)
Android/iOS version:14
Device model: Samsung A25 4G
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
Referring to the documentation, if the option is enabled and the recording is in progress, the Distance/Start-Stop (REC) widget turns green instead of red, and each point is transmitted to a specified URL.

**Comment by martinmolema** [comment]
@yuriiurshuliak that is correct. However, my point is that the logging is also sending HTTP-requests IF the recording button wasn't pressed yet. So the (local) GPX-recording is not running, but the online tracking IS running and sending HTTP-requests

**Comment by vshcherb** [comment]
@yuriiurshuliak to reproduce just enable Online recording and walk around without enabling GPS trip recording, in Logcat logs of OsmAnd, you should be able to see that Online Track recording is called, as all online interactions go to log file

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. To test it, I enabled Online tracking in the Trip Recording plugin settings without activating track recording.

According to the developers' review of my Logcat logs, entries with the LiveMonitoringHelper tag should appear here. https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/plugins/monitoring/LiveMonitoringHelper.java#L209.

Also mentions that when tracking is disabled, old locations that couldn't be sent might still be transmitted. However, I'm not certain that this is the cause of the bug.

[logcat (6).zip](https://github.com/user-attachments/files/16637669/logcat.6.zip)

**Comment by martinmolema** [comment]
Thank you for your investigations. It appears to be working as designed now. I guess somehow the tracking was enabled after all. Cannot explain it now, but problem solved for now
