### ISSUE TITLE
No background location access in Android 13!

### ISSUE THREAD

**Issue by esrat** [osmandapp/OsmAnd#20270]
### Description

On Android 13, OsmAnd seems to miss the background location permission!
Android 13 settings are only showing foreground permission. This enables the usage of foreground navigation but makes it impossible to use pocket navigation for hiking or recording tracks while the app is not opened in the foreground!

### Steps to reproduce

Just install the current F-Droid build and try to edit / set the needed location permission with the Settings app of Android.

### Actual result

There is no "always" setting available for the location like it is for OruxMaps and other apps!

### Expected result

There should be an "always" setting available for the location like it is for OruxMaps and other apps!

### Your Environment (required)

```
OsmAnd Version:  4.7.17 (471703) from F-Droid
Android/iOS version: Android 13
Device model: moto e13
Crash-Logs: none
```

**Comment by dmpr0** [comment]
Since Android 11 location access rules have changed.
* https://github.com/osmandapp/OsmAnd/issues/12397
* https://github.com/osmandapp/OsmAnd/issues/10782

**Comment by scaidermern** [comment]
Turn off battery optimization for OsmAnd in your Android settings.

**Comment by esrat** [comment]
I did that before!
I always disable battery optimization, for every background app!

I also read both of the mentioned issues. No help anywhere!
The given link to follow **precisely** (within #12397) is not online any more.

Does the mentioned foreground service need to get its permissions explicitly somehow? I do see the notification that OsmAnd **should** be recording a track - but when it does not get any location information!?
It does not look like it could be anything else but the permission itself. When I go for a walk and turn off the screen the moment before I would get the direction to take the next turn - I will not hear that direction at all!

Android 13 might also act somehow different from Android 11 (and older) to which the mentioned issues pointed. Or Motorola does take the permissions more seriously than other manufactures?
Fact is: I cannot use OsmAnd any more as soon as the screen is off!
(While e.g. OruxMaps is recording as good as always.)

Will I ever be able to navigate or record a track again, with OsmAnd, when the screen is off?
I cannot even follow a walking route I just clicked together.

**Comment by sonora** [comment]
I have updated the link in https://github.com/osmandapp/OsmAnd/issues/12397#issuecomment-955420132, from my own experience it is still valid for the devices I have trsted in person

**Comment by esrat** [comment]
Hi,
I want to give some more feedback about this issue:
I read the hints some days ago and went through the list of settings. I even switched my Android to American English to be able to search for the options, any part of their names.
I only found one or two of them on Android 13 - and I already had switched them (once even more restrictively than your suggestion). So the Android 9, 10 and 11 settings didn't help me.

But while in the process of searching and checking I found another setting which I already had switched for my comparison candidate (OruxMaps) but not for OsmAnd:
It is called **"Pause app activity if unused"** and is found within the Settings app when configuring a specific app.
This option does exactly what I suspected - it does revoke an app's permissions immediately when the screen is turned off! No matter if the app has started a foreground service!

It would be nice if you could add this option to the list of problematic settings - as Android 13's additional culprit.

Today, for the first time with this device, I was taking a walk with a working OsmAnd! 😀

**Comment by sonora** [comment]
@esrat Let me please understand something: To my knowledge the Android setting "**Pause app activity if app unused**" is just another name (perhaps on Android 13) for what on e.g. many Android 11 devices seems labeled "**Remove permissions if app isn't used**". It is subtitled with "Remove permissions, delete temporary files, and stop notifications". And it really only impacts apps you have not used for a long time, like many months.

So chances are the setting has no immediate effect on OsmAnd's behavior, can you check? Much more likely, if things work now for you, maybe it was one of the settings,I already list in the documentation?

**Comment by esrat** [comment]
You are right about this setting!
In the first place, I did not want to believe it but my little walk right now did convince me that I was wrong. Before switching this setting the first time, I could reproduce the exact same behaviour on several days, on hiking tours as well as my own walk on urban streets. - But now, on my little test walk I was switching this option back and forth and even restarting the whole device many times - impossible to reproduce the immediate loss of the location permission!

I was so sure about this option, because it was the only one I did change at all!
Most of the settings on your list I could not find on android 13 and "Adaptive battery" I did already disable before.
So I cannot say what was the culprit! Maybe all those restarts did their part to heal the error?

Sorry to bother you.

**Comment by sonora** [comment]
Don't worry, it's not a problem. We are all here to exchange knowledge about issues and are trying to identify how to fix them.

So if the issue re-occurs, please speak up. Systems may differ, and reported issues have a better chance of someone finding a solution! 😉
