### ISSUE TITLE
Clarify licence issues

### ISSUE THREAD

**Issue by RicoZ-OSM** [osmandapp/Osmand#2027]
what is the purpose of this: https://github.com/osmandapp/Osmand/commit/31d22cd57f6944820ef5838e0885c0838540769b

afaik GPL itself is copyrighted and does not allow exceptions or modifications. My understanding is if you try modify it you may be without a valid license altogether.

Why "SHOULD  be done with written permission". Either it is a MUST or it is pointless.

You may achieve the MUST part by the use of your artwork and branding just like Firefox does it.

You may also create your own GPL-like license with said exceptions though it might not be trivial.

https://wiki.openstreetmap.org/wiki/Talk:OsmAnd#Is_osmAnd_still_free.3F

**Comment by vshcherb** [comment]
Indeed the exception is not needed to the code, I think it should be related to artwork, there is already CC-BY-ND-NC part there, will move it to that part.

**Comment by vshcherb** [comment]
I don't think question is free or not relevant at all. It was free for personal usage and still free for personal usage, but you need to build it yourself. And yes publishing to repositories such as F-Droid was compliant with License and it is still compliant (without any written permission), though I gave that written permission years ago.

**Comment by RicoZ-OSM** [comment]
Thank you, much better now. The original question is indeed no longer relevant after https://github.com/osmandapp/Osmand/commit/b26ac2b4bb168eb81981de86c07ec54b4b02e0ee
