### ISSUE TITLE
Abnormal work of Attach to the roads 

### ISSUE THREAD

**Issue by Velomeloman** [osmandapp/OsmAnd#20280]
### Description

Attach to the roads doesn't work correctly 
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/109347561/e8a7f0a0-cf1f-4274-902a-4dc933a19a59"  width="300" height="auto"/> </td>
  </tr>
</table>

Related [message](https://t.me/ruosmand/154181).

### Steps to reproduce

Try attach to the roads [Обручева тест.gpx.txt](https://github.com/user-attachments/files/16162122/gpx.txt)

### Actual result

Incorrect work

### Expected result

Correct Attach to the roads like in stable 4.7.17.

### Your Environment (required)

```
OsmAnd Version: OsmAnd~ 4.8.0#2705m, released: 2024-07-09
```

**Comment by Nine-Tailed** [comment]
I had this
![IMG_20240710_193441_859.jpg](https://github.com/osmandapp/OsmAnd/assets/12549744/d52c915c-c234-4db9-8db4-1d10c2360e1d)

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce it, import the provided GPX file and attempt to attach the track to the road. You'll observe that at a threshold distance of 50 meters, the blue dotted line fails to properly connect with the track. However, reducing the threshold distance to around 5 meters resolves the issue.

OsmAnd~ 4.8.0#2722m, released: 2024-07-12

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/2abfbdb6-a34d-4843-a1ac-424cc467fb41"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/154946ac-e46a-46ce-b703-f06f04479caf"  width="300" height="auto"/> </th>
  </tr>
</table>

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/9c0ecdc0-38c5-42e9-9e05-4c5d6cc1c5c8"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/9076801f-68ae-4dc2-a41e-acfffdc34162"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by RZR-UA** [comment]
Wrong approximation is reproduced in Android Simulator on a developer machine. As a temporary workaround you can enable Developer plugin and then Switch to Routing-Based Gpx Approximation in Navigation Settings / Route Parameters. The problem comes from a loop in your gpx-track which should be processed better. Working on fix.

**Comment by Velomeloman** [comment]
Confirm. Routing approximation works well.

**Comment by RZR-UA** [comment]
The problem emerges in conditions when algorithm must approximate gpx points (short segments) to highway roads (long segments).

Possible solution is to split roads segments virtually to match gpx points better.

Additional method would be better considering of gpx-point-to-road-projection.

- [ ] split long road segments virtually
- [ ] consider a dist-to-projection to next gpx point for non-findRouteSegment data
- [ ] think about recalc findRouteSegment projection to the next gpx point (instead of current point)

**Comment by RZR-UA** [comment]
car/bicycle profile: attached to the highway

![car](https://github.com/user-attachments/assets/a1ec8a1a-66f8-43e3-8c78-6fc70896513c)

pedestrian profile: mostly attached to highway=path

![foot](https://github.com/user-attachments/assets/94a8298a-0c26-47c6-8e49-3c34b476c211)

**Comment by RZR-UA** [comment]
Possible routing-based approximation broken in 4.8 ?

https://github.com/osmandapp/OsmAnd/issues/20426#issuecomment-2282877014

**Comment by RZR-UA** [comment]
- [ ] compare performance on Rescuetrack device (routing-based vs final geo-based)
- [ ] port changes to C++ core-legacy, test Android / iOS

**Comment by vshcherb** [comment]
- [ ] Add tests for recorded tracks (mark ignore for points based non-passing)
- [ ] Add 1 item for default Segment based vs Points based
- [ ] C++-Segment based

**Comment by RZR-UA** [comment]
RZR notes:

- [ ] implement switches (Java, JNI, core-legacy)
- [ ] complete iOS build (core cmake files for core-legacy)
- [ ] review recent Java commits to calculateGpxRoute() method
- [ ] check OsmAnd iOS on 1000km gpx-approximate (performance, memory usage)

**Comment by RZR-UA** [comment]
To do before close:

- [ ] compare points vs segments algorithms on RT device
- [ ] make MultiSegments default for 4.9 (both Android, iOS)

**Comment by RZR-UA** [comment]
![rt](https://github.com/user-attachments/assets/ce6f3ce6-c266-4c96-a395-d05916aa2c0f)

**Comment by RZR-UA** [comment]
![default](https://github.com/user-attachments/assets/de99d862-a3a3-49d4-9344-24bd90a9b71b)

**Comment by DmitryAlexei** [comment]
The new approximation algorithm works as expected with 1-segment tracks both on android and iOS devices.
There are still some issues with multisegment tracks, that will be fixed in another task.
