### ISSUE TITLE
Closed bridge

### ISSUE THREAD

**Issue by mariush444** [osmandapp/OsmAnd#20294]
### Routing engine

- [X] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Car with no toll roads

### Start and end points

37.91815 23.00697
closed bridge but osmand "goes" through in both directions.
It seems that osm data are OK

### Actual route

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/66887280/46a3d99c-3439-400f-afb2-c7a50755fc77"  width="300" height="auto"/> </td>
  </tr>
</table>   

### Expected route

Don't go through closed bridge

### Maps you used (online or offline)

- [ ] Offline maps offered within the OsmAnd app for download. 
- [ ] Online (tile / raster) maps 
Offline Greece full map 01.07.2024

### Your Environment

```
OsmAnd Version: 4.5.10
Android version: 11
Device model:

```

**Comment by scaidermern** [comment]
Your OsmAnd version is outdated. Maybe try again with a more recent version.

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce the issue, create a route from coordinates 37.91707, 23.00623 to 37.91977, 23.00872. You will see that the navigation will be built over a bridge that is still under construction.

Link to the object: [OpenStreetMap](https://www.openstreetmap.org/way/30111253)
Link to the route (Web version): [OsmAnd](https://test.osmand.net/map/navigate/?start=37.917070,23.006229&end=37.919765,23.008716&profile=car#16/37.9184/23.0038)


OsmAnd~ 4.8.0#2722m, released: 2024-07-12

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/8f0b6403-cd09-4636-86ab-c2b612615725"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/724870dd-d39a-4432-ad1b-e06d2e991966"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/df1a54d0-dec7-467b-9675-873658cfa3f1"  width="600" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
Way - https://www.openstreetmap.org/way/30111253#map=18/37.91769/23.00829

**Comment by xmd5a2** [comment]
Not reproducible with latest OSM data (16.07.2024). Bridge was modified 01.07.2024 and our current maps doesn't contains these changes.
![изображение](https://github.com/user-attachments/assets/44ca435b-3775-4820-8654-748e376cf0eb)
This will be fixed in the beginning of august.

![изображение](https://github.com/user-attachments/assets/612975fe-f854-4c73-83e9-ecd654a9a17b)
