### ISSUE TITLE
OpenStreetMap editor plugin failed to login

### ISSUE THREAD

**Issue by ogor89** [osmandapp/OsmAnd#20308]
### Description

When trying to upload notes I get strange message and uploads fails. Login with OSM is working, only login / passwd fails.

Messages says:
"Failed to send
Error: https://api.openstreetmap.org/api/0.6/user/details"

Or just a address. Dependt if I directly click "Prześlij" (Send) or I use login/passwd option. I use key manager and finally I tried first option with the same credentials and it worked.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/dd606878-4874-43e8-9a92-a55ce5a6007a"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/f38ce03b-f67f-4026-8415-c2d267916f1a"  width="300" height="auto"/> </td>
  </tr>
</table>

### Steps to reproduce

No credentials to osm.org provided to OsmAnd
Create new osm note
Send to osm
Click on "Send" or:
  use login and password
  provide correct credentials
  send

### Actual result

Ac on screenshots

"Failed to send
Error: https://api.openstreetmap.org/api/0.6/user/details"

### Expected result

Login / passwd method should work.

### Your Environment (required)

OsmAnd 4.7 for Android

**Comment by hayvan96** [comment]
Same here. The provided Url redirects to a suspicious website, I guess they have to fix it on the openstreet map.org side.

**Comment by vshcherb** [comment]
login password is not possible anymore

**Comment by yuriiurshuliak** [comment]
The bug couldn't be reproduced. In the current nightly and latest release versions, logging in with a username and password is no longer possible. This feature has been removed in recent versions. Now, logging in can only be done using a token, as demonstrated in the video.

Therefore, if you use the token login method, it will function correctly.

OsmAnd 4.8.1, released: 2024-07-03
OsmAnd~ 4.8.0#2738m, released: 2024-07-15

https://github.com/user-attachments/assets/9fffa60f-0923-4a71-8217-316c332ea5cc
