### ISSUE TITLE
Incorrect text for action

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#20307]
### Description

![Screenshot_2024-07-13-12-16-04-097_net osmand plus-edit](https://github.com/user-attachments/assets/cff04529-5a65-4e4f-83f4-b6a2241b7345)
![Screenshot_2024-07-13-12-31-55-833_net osmand plus-edit](https://github.com/user-attachments/assets/de148c07-0ad5-4e73-9f63-19ae3c1ac533)

### Steps to reproduce

-

### Actual result

-

### Expected result

-

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd~ 4.8.0#2725m, Дата выпуска: 2024-07-12
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by dmpr0** [comment]
```
    <string name="quick_action_move_map_left">Map to the left</string>
    <string name="quick_action_move_map_right">Map to the right</string>
    <string name="quick_action_move_map_down">Map down</string>
    <string name="quick_action_move_map_up">Map up</string>
```

**Comment by Nine-Tailed** [comment]
@![Screenshot_2024-07-15-10-15-40-249_net.osmand-edit.jpg](https://github.com/user-attachments/assets/1cdf784f-0a9b-4d96-a16a-2a959fba0116)
