### ISSUE TITLE
Consolidate map names

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#20323]
**Rename** - rename poly / copy maps / copy live maps 
- [x] https://github.com/osmandapp/OsmAnd-resources/pull/1094
- [x] Ukraine_kiev-city_europe_2.obf.zip-> Ukraine_kyiv-city_europe_2.obf.zip
- [x] Ukraine_kiev_europe_2.obf.zip-> Ukraine_kyiv_europe_2.obf.zip
- [x] dnipropetrovsk -> dnipro
- [x] odessa -> odesa
- [x] kirovohrad -> kropyvnytskyi

Old Maps could be deleted after release
---------------------------
- [x] Fix log errors https://creator.osmand.net:8080/job/OsmLive_DB_Update_Changesets/41349/console

**Comment by DmitryAlexei** [comment]
- [ ] live updates
- [ ] updating maps
- [ ] poligons
- [ ] wikipedia maps
- [ ] possible problems with HH routing
