### ISSUE TITLE
Distance between two points

### ISSUE THREAD

**Issue by luigifab** [osmandapp/OsmAnd#20335]
### Describe the idea (required)

Could you add a new widget (on top right) that display distance between my position and the center top of the map (near number 480) ?

![Capture d'écrans_20240717-163444](https://github.com/user-attachments/assets/3da8c959-d573-47cd-8b78-32018849c6f5)

### Tell us about the expected behaviour (required)

The idea is to estimate the distance. I know that there is the scale on bottom left, but it does not help me.

### Tell us about alternatives you've considered (required)

Nothing.

**Comment by pebogufi** [comment]
Try using Markers, with Gps on and off.
It is very easy for measuring distances, like you want it.

**Comment by sonora** [comment]
> Try using Markers, with Gps on and off. It is very easy for measuring distances, like you want it.

Yes, exactly. And you don't lose the reference when e.g. changing your zoom level.

Another feature already existing is "Distance by tap", to be found under the "Configure screen" menu.

**Comment by luigifab** [comment]
oh nice, distance by tap is good, thanks!
