### ISSUE TITLE
"Show all on map" button missing on some devices

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2033]
On some devices (in portrait mode only), like the htc Desire X (480x800 px screen), on the "Search 'POI" results screen, the "Show all on map" button (usually visible in the lower right corner of the screen, to the right of the "Filter" button) is not shown on the screen, i.e. entirely missing. "Show all on map" cannot be triggered on those devices at all, unless the screen is viewed in landscape mode.

**Comment by vshcherb** [comment]
Sounds bad, though it is very long existing bug I guess.

**Comment by vshcherb** [comment]
I don't have simple explanation why it doesn't work.  If "Find more" fits the screen, it should be there.

**Comment by sonora** [comment]
Yes, I investigated the code and could not find an issue either ... could
be an SDK bug with some not-so-common screen resolutions - not sure. I also
see similar effects in Mozilla Firefox for Android, with no identifiable
root cause there either ..

**Comment by sonora** [comment]
I still see this on some devices, but do not know what we can do about it in OsmAnd.
