### ISSUE TITLE
F-droid app is outdated

### ISSUE THREAD

**Issue by ArchangeGabriel** [osmandapp/Osmand#2034]
Hi,

It looks like the F-droid version of OsmAnd is quite outdated (in comparison to the G/A/A stores…). I’m not sure whether this is the right place for reporting this, please tell me if I need to report that somewhere else (and then where).

Thanks!

**Comment by RicoZ-OSM** [comment]
F-droid is the place and it seems they are working on it.

**Comment by vshcherb** [comment]
It is not the right place, cause we don't maintain that repository :)

**Comment by ArchangeGabriel** [comment]
OK, but I’ve look a bit around there and can’t find the right place. Could you give me a hint?

Thanks!

**Comment by RicoZ-OSM** [comment]
try searching somewhere here https://f-droid.org/forums/topic/new-version-of-osmand/page/13/

**Comment by ArchangeGabriel** [comment]
Many thanks, strangely this forum escaped from my searches.
