### ISSUE TITLE
[Bug] OSM Edits: Problems with scrolling or buttons

### ISSUE THREAD

**Issue by franco999** [osmandapp/OsmAnd#20358]
### Description

In recent nightly versions, I have noticed that in the advanced editing screen of OSM elements, the bottom buttons for Delete, Add, etc. they disappear when the keyboard is shown, so it does not move down and I have to remove the keyboard every time I add a new label

### Steps to reproduce

1. Activate OSM editing plugin.
2. Try to create or modify an OSM element, using advanced editing.
3. Check if you are scrolling and if there are easily visible buttons.

### Actual result

`OsmAnd~ 4.8.0#2796m, Released: 2024-07-19`

<img alt="" width="300" height="auto" src="https://github.com/user-attachments/assets/45539663-d784-4f41-b9c5-582425f3ab90">

### Expected result

<img alt="" width="300" height="auto" src="https://github.com/user-attachments/assets/ac7b54c8-3c7e-43a4-86a2-f19e227d42f0">

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd~ 4.8.0#2796m, Released: 2024-07-19
Android/iOS version: Android 13
Device model: Motorola G32
Crash-Logs: ?
```

**Comment by vshcherb** [comment]
Probably we can redesign to give more empty space on sides so there is space to scroll

**Comment by dmpr0** [comment]
<table style="width:100%">
  <tr>
    <th>4.9.0#2880m</th>
    <th>4.6.8</th>
  </tr>
  <tr>
    <td><video src="https://github.com/user-attachments/assets/aab90c8b-db86-4942-b898-da2415c4a291"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/user-attachments/assets/25c8e192-9182-46c2-8a5c-ce0c94e9b887"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by luigifab** [comment]
Yes same for me since 4.8.4, before when the keyboard was open, buttons were moved. Same problem for tags drop-downs.
