### ISSUE TITLE
unable to export to file

### ISSUE THREAD

**Issue by tiptoptom** [osmandapp/OsmAnd#20360]
### Description

When I want to export my settings and the share dialog opens, no app can accept the exported file, no matter which one I select. An error always occurs in the selected app (e.g. Telegram “unsupported file”, FairEmail “java.io.IOException: read failed: ENOENT (No such file or directory)”, all other apps I have tried abort without an error message).

### Steps to reproduce

Go to OsmAnd~ Settings > Export to file > choose any app

### Actual result

The selected app cannot save/send the file.

### Expected result

The selected app can save/send the file.

### Your Environment (required)

```
OsmAnd Version: OsmAnd~ 4.7.17 from F-Droid
Android/iOS version: Android 11, LineageOS 18.1 
Device model: Xperia X
Crash-Logs: ?
```

**Comment by DmitryAlexei** [comment]
Cannot reproduce your issue with OsmAnd from GPlay or the latest nightly build. Telegram, files, viber and other apps 
As a workaround, it is recommended to sync your favorites and settings via OsmAnd cloud and after that reinstall OsmAnd.

**Comment by tiptoptom** [comment]
Seems like there was a problem with the external memory.

My workaround had the following steps:
1. delete downloaded maps (for memory reasons only)
2. settings > OsmAnd settings > Data storage folder > Internal app memory (it was external before)
3. settings > Export to file

I suspect this is due to my hardware. I am therefore closing the issue. Sorry for the false alert.
