### ISSUE TITLE
Routing tells me to cross a lake unnecessarilly

### ISSUE THREAD

**Issue by PistachioGuy** [osmandapp/OsmAnd#20364]
### Routing engine

- [X] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Car

### Start and end points

from:
Blind Bay Road, Parry sound
to:
Killbear Provincial Park

All part of Canada, Ontario, Barrie map.

### Actual route

It decides that I can't cross the gatehouse, so it takes me way off onto another road and suggests I swim across the lake. This was very confusing. Going across the lake added about 30 minutes to the route estimate.
<table style="width:100%">
  <tr>
  <img src= https://github.com/user-attachments/assets/97fa7f4e-b1b3-4af7-a745-8b29b3174e75>
  </tr>
</table>

### Expected route

Take me to or maybe past the gatehouse instead of road far from destination

### Maps you used (online or offline)

- [x] Offline maps offered within the OsmAnd app for download. Canada, Ontario, Barrie 2024-6-30

### Your Environment

```
OsmAnd Version: OsmAnd~ 4.7.17
Android version: 14
Device model: Google Nexus 5

```

### Anything else?
I think it might be because the end of the road it sent me to is a little closer in a straight line to the destination.

**Comment by DmitryAlexei** [comment]
OsmAnd web https://osmand.net/map/navigate/?start=45.378196,-80.217876&end=45.350698,-80.195732&profile=car#12/45.3623/-80.2194

**Comment by DmitryAlexei** [comment]
car routing to the final destination is not possible, so that issue will be merged to https://github.com/osmandapp/OsmAnd/issues/17987
