### ISSUE TITLE
Opening GPX files

### ISSUE THREAD

**Issue by jkufner** [osmandapp/Osmand#2037]
Osmand works with GPX files, but it does not have an intent registered, so Osmand is not offered to user when GPX file is to be opened.

For example when I send GPX file from computer to my phone via bluetooth, I have to open file manager on my phone and move the GPX file to Osmand's directory and then I  can open the file in Osmand to actually see the track. This is far from user-friendly.

I would like to click the file from notifications when it is received, Osmand should start and ask whether to move or copy the file to tracks directory and then open it, like when user clicks it in list of tracks.

**Comment by vshcherb** [comment]
Which file manager do you use? From application downloads it could be opened, though it could not be opened directly from GMail for example.

**Comment by jkufner** [comment]
I clicked the GPX file in notification after it was received via Bluetooth and it did not work.

When I use filemanager, It works from TotalCommander and from Samsung's My Files, but not from OI File Manager.

**Comment by SCHAKKEBROEK** [comment]
connect the two devices via USB, now you can do what you want with explorer

**Comment by SCHAKKEBROEK** [comment]
the gpx-files must be lower case for OsmAnd

**Comment by RicoZ-OSM** [comment]
Works with Ghost Commander.

Sharing from RunnerUp does not work as it uses a strange mime type.

Also the filter to receive mime-type GPX is missing:
  https://github.com/osmandapp/Osmand/issues/2896

**Comment by sonora** [comment]
Fixed via #2896, I think.
