### ISSUE TITLE
External input device : missing key map "Opens Wunderlinq dashboard"

### ISSUE THREAD

**Issue by Buzzz57** [osmandapp/OsmAnd#20382]
### Description

The latest OSMand version has a different mapping for the Wunderlinq device.
Before, there were 3 possible actions. Now only 2 (zoom in/out)

Before 
 ![image](https://github.com/user-attachments/assets/a8546ae6-9af6-4f41-ade3-cdf9e70ee75e)

After
![image](https://github.com/user-attachments/assets/fd43bca0-a22f-4d4b-8cb3-0f58dc395bcb)

### Steps to reproduce

Install latest OSMand

### Actual result

Missing key map

### Expected result

Full key map

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.8.1
Android/iOS version: 13
Device model: BV8900
Crash-Logs: ?
```

**Comment by boxsection** [comment]
I have the same problem.
OSMAnd 4.8.4 24/07/2024
Android 14.

This is a key usability feature for the wunderlinq integration, why has it disappeared as it did work and there are Youtube videos demonstrating the same. Once you access OSMAnd you lose control of all other wunderlinq / Mobile phone functions from the motorbike controls as you can no longer escape back to Wunderlinq. As a motorcyclist you generally wear gloves which rules out touching the screen unless you stop and take your gloves off.

This key mapping seems to be in the source code but is not making it into the build or at least the version in the Google Play store.


The Code in question is at:
OsmAnd/src/net/osmand/plus/keyevent/devices/WunderLINQDeviceProfile.java

**
 * WunderLINQ device, motorcycle smart phone control
 */
public class WunderLINQDeviceProfile extends DefaultInputDeviceProfile {

	@Override
	protected void collectCommands() {
		super.collectCommands();
		bindCommand(KeyEvent.KEYCODE_DPAD_DOWN, MapZoomCommand.ZOOM_OUT_ID);
		bindCommand(KeyEvent.KEYCODE_DPAD_UP, MapZoomCommand.ZOOM_IN_ID);
		bindCommand(KeyEvent.KEYCODE_ESCAPE, OpenWunderLINQDatagridCommand.ID);
	}

	@Override
	public String getId() {
		return InputDevice.WUNDER_LINQ.name();
	}
}

**Comment by EugeneZmeuk** [comment]
> I have the same problem. OSMAnd 4.8.4 24/07/2024 Android 14.
> 
> This is a key usability feature for the wunderlinq integration, why has it disappeared as it did work and there are Youtube videos demonstrating the same. Once you access OSMAnd you lose control of all other wunderlinq / Mobile phone functions from the motorbike controls as you can no longer escape back to Wunderlinq. As a motorcyclist you generally wear gloves which rules out touching the screen unless you stop and take your gloves off.
> 
> This key mapping seems to be in the source code but is not making it into the build or at least the version in the Google Play store.
> 
> The Code in question is at: OsmAnd/src/net/osmand/plus/keyevent/devices/WunderLINQDeviceProfile.java
> 
> **
> 
> * WunderLINQ device, motorcycle smart phone control
>   */
>   public class WunderLINQDeviceProfile extends DefaultInputDeviceProfile {
>   @OverRide
>   protected void collectCommands() {
>   super.collectCommands();
>   bindCommand(KeyEvent.KEYCODE_DPAD_DOWN, MapZoomCommand.ZOOM_OUT_ID);
>   bindCommand(KeyEvent.KEYCODE_DPAD_UP, MapZoomCommand.ZOOM_IN_ID);
>   bindCommand(KeyEvent.KEYCODE_ESCAPE, OpenWunderLINQDatagridCommand.ID);
>   }
>   @OverRide
>   public String getId() {
>   return InputDevice.WUNDER_LINQ.name();
>   }
>   }

@Buzzz57 @boxsection thank you for your feedback. We will check it this week.
