### ISSUE TITLE
Winter and ski: Display piste and aerial lift directions

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#2038]
For the "winter and ski" map style it would be very useful to see directions of aerial lifts and pistes. At least for piste:type=downhill and piste:type=sled since there are other piste types without a specific direction. According to the screenshots of [OsmAnd Ski Map](https://play.google.com/store/apps/details?id=net.osmand.skimapsPlugin) this had already been implemented.

**Comment by vshcherb** [comment]
True that's misleading screenshot, we need to replace them. They are implemented in non-released engine and in IOS.

**Comment by scaidermern** [comment]
Does this really need additional engine modifications? Drawing direction arrows for oneway streets is already implemented. So it just seems like some modifications on the style sheet could be sufficient. Am I wrong?

**Comment by vshcherb** [comment]
Yes it is hardcoded for highways with oneway, but I would ask @xmd5a2  if we can implement oneway in a same way?

**Comment by xmd5a2** [comment]
Fixed. However arrows for skimap must be redesigned.
