### ISSUE TITLE
[bug] Loss of data, metrics when recording a track during analysis

### ISSUE THREAD

**Issue by snooppr** [osmandapp/OsmAnd#20381]
### Description

I encountered a bug in the field, it was unpleasant. I didn't understand what happened, what caused the failure. After some time, I reproduced the bug in test conditions.

Meaning: during track recording, the user has access to time and distance metrics, after analysis, time and distance are reset to "0".
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/89be21a9-d3b7-4e2b-8699-bec9f78b918c"  width="300" height="auto"/> </td>
  </tr>
</table>

### Steps to reproduce

The bug can be reproduced in two ways: via the widget and by clicking on the recorded track on the map.

The video shows imitation of movement by GPS. The key moment of bug reproduction: after clicking "**track analysis on the map / опции -> анализ на карте**" all metrics "distance/total time" are reset to "0" and after continuing to record the track the values ​​remain frozen at zero. Only the widget with the red button continues to display the distance traveled, the second widget is dead, the statistics are dead.

1) Via Widget:

https://github.com/user-attachments/assets/aafb7fb8-6f83-4d0f-bf1e-f21c55e0219c

2) by clicking on the track:

https://github.com/user-attachments/assets/a7332241-ec09-416b-9b0d-466099f75774

### Actual result

but the values ​​are reset to zero.
the "duration" widget always shows zero and is no longer clickable. After recording the track, the track is intact. 
The problem is that during the recording of the track, the statistics are no longer available.

### Expected result

The statistics should show the distance and time traveled during recording.
The duration widget should display metrics and be clickable.

### Your Environment (required)

f-droid v 4.7.17.

**Comment by yuriiurshuliak** [comment]
The bug could not be reproduced. I enabled track recording, recorded for a while, then selected Options - Analyze on map after clicking on the track. As a result, the distance and total time were displayed correctly and did not reset to zero. Please try using the release version of the app.

OsmAnd~ 4.8.0#2841m, released: 2024-07-25

https://github.com/user-attachments/assets/eaa7adc7-9c6a-401a-b0b0-7c2025d2261c

**Comment by snooppr** [comment]
@yuriiurshuliak Reinstalling OsmAnd from f-droid to the release test version is a hassle. I will wait for the new release of OsmAnd on f-droid. and let you know if the bug in the update is fixed.

**Comment by snooppr** [comment]
OsmAnd 4.8.5 fix.
