### ISSUE TITLE
Address should use ``addr:*`` tags when available

### ISSUE THREAD

**Issue by MarioSwitch** [osmandapp/OsmAnd#20391]
### Description

When clicking on a POI, OsmAnd tries to get the point address.

However, some POIs already have ``addr:*`` tags, especially ``addr:housenumber``, ``addr:street``, ``addr:postcode`` and ``addr:city`` to describe the address.

OsmAnd should use these tags when there are filled to precisely give address instead of "guessing" one using nearest roads.

### Steps to reproduce

1. Search POI where ``addr:*`` tags are filled in OpenStreetMap
2. Select the POI on the OsmAnd map
3. OsmAnd address is "generated" using nearest roads instead of using ``addr:*`` tags

### Actual result

OsmAnd address is "generated" using nearest roads.

### Expected result

OsmAnd uses ``addr:*`` tags to build address when these tags are filled.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.8.2
Android/iOS version: Android 14 
Device model: Google Pixel 7 
Crash-Logs: Not needed 
```

**Comment by vshcherb** [comment]
Duplicate - ...
