### ISSUE TITLE
add translation POI "dressing room"

### ISSUE THREAD

**Issue by snooppr** [osmandapp/OsmAnd#20396]
### Describe the idea (required)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/887981ff-503b-4149-a4e5-56730874842e"  width="300" height="auto"/> </th>
  </tr>
</table>

POI "dressing room" exists only in EN language regardless of user locale. Add translation, for example, to RU "раздевалка". The lack of translation also prevents adding "dressing room/раздевалка" to osm maps using osmand map editor.

"раздевалка" is None Edit POI:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/b501fda3-1099-45d3-aa5b-9f98597c53f2"  width="300" height="auto"/> </th>
  </tr>
</table>

And of course, you won't find POI by the keyword "раздевалка" in the search.

### Tell us about the expected behaviour (required)

No

### Tell us about alternatives you've considered (required)

No

**Comment by yuriiurshuliak** [comment]
After reviewing the files, I found that the string 'dressing_room' is indeed missing from the corresponding language file: [phrases.xml for Russian](https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/res/values-ru/phrases.xml). However, it is present in the [Polish language file](https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/res/values-pl/phrases.xml).
