### ISSUE TITLE
Search building number without street

### ISSUE THREAD

**Issue by shadow-identity** [osmandapp/Osmand#2040]
Some villages have a lot of buildings and several roads, but still haven't any street names. For example, Lesnoy (Лесной) near Minsk
Please add possibility of using address search by building number at those cases. Now we should select street, but those villages haven't street names.

**Comment by pl71** [comment]
How postmen delivers mail? You have building No.12 in the city of Lesnoy or what? Do you have two buildings with same numbers?

**Comment by vshcherb** [comment]
This possibility was already added, as a street you should select City name in brackets.
Lesnoy -> <Lesnoy> -> 1, ..2
Please mind that you need to have proper boundaries so the buildings will not be "stolen" by other cities/streets.

**Comment by shadow-identity** [comment]
@pl71 yes, it's just "Lesnoy, 12". We haven't two buildings with same numbers.
@vshcherb is it possible to make it more obvious? To add, say, special case "Unnamed street" or just when user can leave Street field blank and see buildings without "addr:street" tag?

**Comment by shadow-identity** [comment]
I believe: not less than 95% users don't know anything about how to skip street using brackets.
