### ISSUE TITLE
Light background on a dark theme in QA menu

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd#20407]
### Description

Follow-up for https://github.com/osmandapp/OsmAnd/issues/18821

### Steps to reproduce

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Image</th>
        <th>Video</th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/669c44cd-fa98-4de6-ac74-15c4da1b597f"  width="300" height="auto"/> </td>
        <td><video src="https://github.com/user-attachments/assets/a8c23f65-8e7c-4cdc-b939-d09435a48a53"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

### Actual result

Light background in Dark theme

### Expected result

Background should follow the app theme

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by vshcherb** [comment]
Not planned for now
