### ISSUE TITLE
Car navigation - Lane assistance not always active

### ISSUE THREAD

**Issue by MarcMart** [osmandapp/OsmAnd#20416]
### Description

Previously lane assistance would ALWAYS indicate in which lane to drive. This was of course true when navigation required a change from one road to another but also when passing by potential leaving lanes alongside the route. In the latter case lane assistance would briefly pop up to indicate in which lanes to stay, e.g driving on a motorway and passing by a service area exit.
Now it seems that lane assistance only pops up before a necessary change of road. 
The previous behavior was extremely useful, especially when navigating through huge unknown metropolitan areas where there might be e.g. 7 lanes with 4 different driving directions. It makes a huge difference looking at the app and seeing at a glance "keep in the two middle lanes"  instead of having to read all signs (potentially with different alphabets) and compare with what it says in the road description field of the app.

### Steps to reproduce

Make the app create a route wherever you know are exit roads/lanes on the way to see that no indication appears to "keep on lanes x" 

### Actual result

Lanes assistance does not pop up except when a significant road change is required

### Expected result

Lane assistance should always indicate in which lane to stay.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.7.17
Android/iOS version: Lineage 18.1
Device model: BQ Aquaris X Pro
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
- Could you please clarify if you are using live updates? 
- Are you navigating point-to-point or using a GPX track? 
- Does this issue occur on all routes with exit lanes or only on specific ones? 
- Could you attach a screenshot that shows this problem? 

For us to reproduce the issue, we need your profile settings and the specific coordinates of the start and finish points where you encounter this issue.

Additionally, please try updating the app to the latest version and let us know if the problem persists.

**Comment by MarcMart** [comment]
Could you please clarify if you are using live updates?
-> Deactivated 
    Are you navigating point-to-point or using a GPX track?
-> Point to point
    Does this issue occur on all routes with exit lanes or only on specific ones?
-> All routes
    Could you attach a screenshot that shows this problem?
Please see the NOW and BEFORE pictures. Note: Don't get confused by the BEFORE picture, it is just intended to show what I expect to see when driving along the motorway without having to leave, so the lane assistant should pop up but instead show the straight ahead lanes.

![Lane assistance issue #20416_BEFORE](https://github.com/user-attachments/assets/199363f8-0f92-4b4c-b945-04666e01ada0)
![Lane assistance issue #20416_NOW](https://github.com/user-attachments/assets/da8059cc-f641-4c9b-95fc-912cd2f99568)

**Comment by vshcherb** [comment]
Before you entered the exit now, you don't. So you compare different routes.
