### ISSUE TITLE
Delay switch profiles (quick action)

### ISSUE THREAD

**Issue by mikehgentry** [osmandapp/OsmAnd#20429]
### Describe the idea (required)

An enhancement for #17021 (custom buttons to jump forwards / backwards by profile)

I'm very pleased this has been implemented so well, thanks for that! It even responds to multiple taps, which I wasn't expecting.

The 'cherry on top' to make it perfect would be if you pressed it multiple times and it didn't bother drawing the profiles in between, this would presumably speed things up noticeably.

### Tell us about the expected behaviour (required)

If multiple taps are detected don't draw the intervening profiles.

### Tell us about alternatives you've considered (required)

n/a

**Comment by vshcherb** [comment]
To do: Change profile could happen with a delay for quick action to allow switch profiles quicker

**Comment by Zirochkabila** [comment]
# Testing 1
`OsmAnd~ 5.0.0#3921m, Released: 2024-12-10`

1. If copy Custom buttons to another profile, they are deactivated

https://github.com/user-attachments/assets/dcd8141b-823b-4ee0-9d68-2bdaa5bb9b0e

**Comment by vshcherb** [comment]
If they are disabled in another profile, then in target profile they shouldn't be enabled
