### ISSUE TITLE
parallel installation of osmand and osmand+

### ISSUE THREAD

**Issue by EssBee59** [osmandapp/OsmAnd#20427]
### Describe the idea (required)

Hello,
For testing new versions I liked to install Osmand+ (daily build as ex.) parallel to the standard (gpl) Osmand.
But this is since some days not longer possible:
The installation of Osmand+ fails in that case with the error:
PackageManager: Package net.osmand.plus attempting to redeclare permission net.osmand.SERVICE_PERMISSION already owned by net.osmand

### Tell us about the expected behaviour (required)

It would be nice to keep the possibility to install osman and osmand+ parallel

### Tell us about alternatives you've considered (required)

Tests of daily build is only on a separate smartphone possible

### Context (optional)

Android 14
Osmand 4.8.4
Osmand+ 4.8.0#2849m  sdk 34

**Comment by yuriiurshuliak** [comment]
Please note that OsmAnd+ has the same signature as OsmAnd Nightly, so they cannot be installed simultaneously. However, you can install the free version of the app alongside OsmAnd Nightly, and they should work together without issues.

As a workaround, you can install [OsmAnd-default.apk](https://download.osmand.net/latest-night-build/OsmAnd-default.apk) along with OsmAnd+, and they should work fine together.

**Comment by vshcherb** [comment]
Should work fine nightly / release version
