### ISSUE TITLE
Weekdays in poi details not translate able

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/Osmand#2043]
The weekdays like mo, th, we ... In poi details aren't translate able. See screenshot. Language is set to German.

![screenshot_2015-12-10-20-24-49](https://cloud.githubusercontent.com/assets/11144987/11725948/8f282e58-9f7c-11e5-8f17-42259784e0d8.png)

Simon

**Comment by pl71** [comment]
Most probably data here is copied directly from OSM tag without any further modifications. Note that `opening_hours` tag is not always set as per [wiki recommendations] (http://wiki.openstreetmap.org/wiki/Key:opening_hours) in OSM database. But translation of weekdays 'Mo', 'Tu',... could be implemented anyway.

**Comment by jf-simon** [comment]
Thanks, looking forward to translate on translate.osmand.net

**Comment by GaidamakUA** [comment]
@jf-simon there are no need for that. Android and Java doing pretty good job localizing dates by themselves.

**Comment by jf-simon** [comment]
Thanks
