### ISSUE TITLE
2 finger zoom isn't smooth

### ISSUE THREAD

**Issue by TheSikal** [osmandapp/OsmAnd#20455]
### Description

The two-finger zoom seems slightly shaky, as if the application perceives that the fingers are moving a few pixels all the time.

The zoom level and the amount of detail displayed on the map do not change this behavior.

This is not due to my phone's touchscreen, no such problem has been observed with other applications.

### Steps to reproduce

Open OsmAnd and (un)zoom with 2 fingers.

### Actual result

https://github.com/user-attachments/assets/ad975014-e408-4cd8-b546-8559e2c9f10c

### Expected result

Smooth zoom

### Your Environment (required)

OsmAnd Version: 4.8.4
Rendering: Version 2 (OpenGL)
Android Version: 14
Device model: Samsung Galaxy A52

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce this issue, try zooming the map slowly and smoothly using two fingers. When doing so, the zooming appears unstable and shaky, with noticeable screen shaking during the process.

OsmAnd~ 4.9.0#2872m, released: 2024-07-31

https://github.com/user-attachments/assets/8e45d595-95bf-4bc1-b343-1a6c1c959fed

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.9.0#2894m, released: 2024-08-02
- 3d view enabled
- two-fingers zoom at the top of the screen

https://github.com/user-attachments/assets/ca9729fa-7cad-497f-b99f-e028c063b04b

**Comment by Andrewschenko** [comment]
This particular gesture isn't exactly a zoom, but a kind of "two-finger drag," so when your fingers move unevenly and irregularly, the area of ​​the map between them may shake slightly.

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.9.0#3305m, released: 2024-09-27
Map shaking when zooming in and out was seriously reduced.
At the same time, slight map rotation when zooming was introduced.

https://github.com/user-attachments/assets/769334fb-25f9-46c9-9c92-9ddf7490f8d5
