### ISSUE TITLE
highway=emergeny_access_point with ref= is rendered as cycle route node

### ISSUE THREAD

**Issue by matthijskooijman** [osmandapp/OsmAnd#20453]
### Description

Nodes with `highway=emergency_access_point` and a `ref=` tag are rendered as cycle route nodes, which they are not. This pollutes the map with invalid cycle nodes, obscuring the actual nodes sometimes.

### Steps to reproduce

On a clean osmand, switch to cycling view (probably not really needed) and enable cycle route display (default settings are fine).

Download Europe/Netherlands/Utrecht standard map and then navigate to this node: https://www.openstreetmap.org/node/8325501119

### Actual result

This looks like: 
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/490550e2-64bd-4676-970e-67f0f06df6cf"  width="300" height="auto"/> </td>
  </tr>
</table>

DHT22 near the top is the referenced nodes, all other DHTxx refs are similar nodes.

Tapping the icon shows that it is displayed as a cycling node (also confirmed by disabling cycle routes - then they disappear):

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/03b9014e-21c1-45a3-9ec6-ac7fa6d0f9e8"  width="300" height="auto"/> </td>
  </tr>
</table>

### Expected result

The ref should not be displayed as a cycling node, only (when zooming in sufficiently), shown as an emergency access point (probably without ref - you can tap the icon to view the ref). When zooming in, the emergency access point icon is already shown as expected, so that part already works:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/7fb13f92-c3fd-4697-9e05-17f2b61a0f6f"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/b245e4a1-34db-4e27-880f-973186d92e1d"  width="300" height="auto"/> </td>
  </tr>
</table>

Similarly, a [`highway=emergency_access_point` without `ref=`](https://www.openstreetmap.org/node/631616168#map=18/52.34188/5.61769&layers=C) is *not* shown as a cycling node:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/660f99ae-b249-4e04-b6d7-57f81011dd77"  width="300" height="auto"/> </td>
  </tr>
</table>

### Your Environment (required)

```
OsmAnd Version: Nightly 4.9.0#2869m, 2024-07-30
Android/iOS version: Lineage 20-20230903, Android 13
Device model: Samsung S10e

Also seen with OsmAnd 4.7.17 and on Samsung Galaxy Tab A 8.0" 2019 with Android 9, 
```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce it, navigate to the coordinates 52.12729, 5.37277 ([link](https://www.openstreetmap.org/node/8325501119#map=18/52.12711/5.37321)) and enable the cycle routes display. You'll observe that nodes tagged with highway=emergency_access_point and ref=tag are incorrectly shown as cycle route nodes on the map.

OsmAnd~ 4.9.0#2872m, released: 2024-07-31

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/f102ce06-a2ee-49db-99c5-2ae77d1433c8"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
Yes, we should increase text minzoom to 17 emergency_access_point

**Comment by xmd5a2** [comment]
These labels are from *lcn_ref* nodes [like this](https://www.openstreetmap.org/node/7252370714). This is not related to *highway=emergency_access_point* nodes. They are just close.
```
Point types [highway-emergency_access_point (70)] Names [ref(60) - DTH22] id 1065664143348 osmid 8325501119
Point types [multiple_node_networks-true (30), node_network_point-lcn (28), route_mtb (24)] add_types [network-lcn(23), osmc_foreground-blue_pointer_4(10), osmc_background-blue_4(11), osmc_waycolor-blue(12), route_mtb_1-(13), route_mtb_1_osmc_textcolor-black(18), route_mtb_1_network-lcn(25), route_mtb_1_osmc_foreground-blue_pointer_4(20), route_mtb_1_osmc_background-blue_4(21), route_mtb_1_osmc_waycolor-blue(22)] Names [route_mtb_1_name(14) - Treeker MTB Trail (Blauwe Route), operator(33) - Den Treek Henschoten, lcn_ref(29) - DTH22, lcn_ref_value(31) - DTH22, osmc_stub_name(5) - ., bicycle_mtb:name(6) - Treeker MTB Trail (Blauwe Route), bicycle_osmc_text(8) - Tre-B, bicycle_osmc_textcolor(9) - black, bicycle_operator(47) - Den Treek Henschoten, route_mtb_1_mtb:name(15) - Treeker MTB Trail (Blauwe Route), route_mtb_1_osmc_text(17) - Tre-B, route_mtb_1_osmc_stub_name(19) - ., route_mtb_1_operator(48) - Den Treek Henschoten, bicycle_ref(7) - Tre-B, route_mtb_1_ref(16) - Tre-B] id 928303451508 osmid 7252370714
```
