### ISSUE TITLE
Post Office Deutsche Post Filiale 401 Am Dalmannkai 8, 20457 Hamburg 

### ISSUE THREAD

**Issue by Clemenssss** [osmandapp/OsmAnd#20456]
Please do not file questions or support requests on the GitHub issues tracker.

In case you aren't sure whether to open an issue or not, please send your request to support@osmand.net.

You can get your questions answered using the [Google group](https://groups.google.com/forum/#!forum/osmand) or chat in real-time via our Telegram instances: [English](https://t.me/OsmAndMaps), [German](https://t.me/deosmand), [French](https://t.me/frosmand), [Ukrainian](https://t.me/uaosmand), [Italian](https://t.me/itosmand), [Russian](https://t.me/ruosmand).

Thank you!

**Comment by yuriiurshuliak** [comment]
Your request is not clear and lacks essential details. Could you please provide more information regarding the issue you're experiencing with the Post Office Deutsche Post Filiale 401 at Am Dalmannkai 8, 20457 Hamburg?
Providing more context and details will help us better understand and address your issue.

**Comment by Clemenssss** [comment]
The Location is missing.I am not able to add it. Anyone can do it?
Vielen Dank und viele Grüße

Clemens Li

0173 912 5566

Am 31. Juli 2024 09:56:20 MESZ schrieb yuriiurshuliak ***@***.***>:

**Comment by MarioSwitch** [comment]
@Clemenssss Map Data are provided by OpenStreetMap. If a POI / location is missing on the map, you should add it on OpenStreetMap. Beware that maps are updated only once a month (except if you have enable Live Updates)!

**Comment by MarioSwitch** [comment]
@Clemenssss Just added the point, please check https://www.openstreetmap.org/changeset/154637418 😉
