### ISSUE TITLE
Contour lines artefacts in Zhaosu, Xinjiang, China

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#20457]
### How to reproduce
* Go to Menu – Maps & Resources – Asia – China
* Find **Xinjiang**, download **Standard map** for the region
* Download contour lines for **Ili Kazakh Autonomous Prefecture** 
* Go back to map screen, open map at:
*  * First place – `42.54186° N, 80.99929° E` 
*  * Second place – `42.75416° N, 82.00020° E`

### Actual result

<table style="width:100%">
  <tr>
    <th colspan=2>First place – 42.54186° N, 80.99929° E</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/28278ce6-156d-44b3-a126-2833b3d60688"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/8d383518-cbfe-4d08-b101-a67b8e92bce0"  width="300" height="auto"/> </td>
  </tr>
</table>   

<details>
    <summary>Second place</summary>
    <table style="width:100%">
      <tr>
        <th></th>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/62de585d-df0d-409a-b57c-2f7b5bdd8b9b"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/bf98aa37-440e-4a9b-b2f9-cea58bd0f8c7"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

### Expected result

* Contour lines without artefacts 

**Environment**
OsmAnd Version: OsmAnd~ 4.9.0#2872m, released: 2024-07-31
Android: 15
Device model: Google Pixel 6A

**Comment by xmd5a2** [comment]
Fixed. Contour maps were updated.
