### ISSUE TITLE
Compass orientation no longer works 

### ISSUE THREAD

**Issue by pfbreton-perso** [osmandapp/OsmAnd#20454]
### Description

We used to be able to click on the compass button to cycle through the modes.  This no longer works with version OsmAnd 4.8.2, released: 2024-07-10.

It works with long hold but that isn't working for remote controls like Carpe Iter which sends a single tap .

### Steps to reproduce

Display map with compass
Single tap on compass
 

### Actual result

Mode doesn't change anymore

### Expected result

Tap should cycles through different compass modes (always up north, movement direction etc)

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```
OsmAnd 4.8.2, released: 2024-07-10
Android 11

**Comment by mikehgentry** [comment]
Double tapping works. It was always like this during navigation, but they've changed it now so it's universally like this.

**Comment by ratti** [comment]
I have the same issue.

Additionally another method doesn't work anymore: You could always rotate the map with two fingers, the compass then switched automatically from "North always on top" to "Manually rotated".

This doesn't work anymore. To rotate the map, you first have to switch the compass from fixed  north to rotation mode.

Can we please get feedback this are bugs indeed? It feels a bit like this is intentionally, and in that case it's really... not a good idea.

**Comment by dmpr0** [comment]
Hi! Yes, we have changed the compass button behavior:

Single tap: Rotate map orientation to the North in all orientations.
Double tap: Switch map orientations (previously worked for single taps).
Long tap: No changes.
Additionally: All map rotation has been disabled for North is up mode, and Manually rotated is now the default mode.

**Comment by pfbreton-perso** [comment]
I don’t understand what’s the goal behind this change. All other applications work with a single tap on the compass to set the north up .  This change makes it feel that a button on the screen is a no op.

Your breaking a user and interaction pattern and introducing inconsistency:  buttons on screen all respond to a single tap (zoom, 3d, burger menu, navigation etc) except this one.  That introduces a discrepancy and reduces discoverability.

i don’t see what is the improvement by changing the compass to no longer respond to a single tap?

**Comment by vshcherb** [comment]
We plan to add hint that orientation modes are configured by long tap.

Single tap is used in several modes like most important and default "Manually rotated" it switches to North from manual rotation. And mode "North is up" doesn't allow manual rotation, this is done to avoid confusion between these modes and allow single tap to be used in each mode as an action.

**Comment by ratti** [comment]
Wow. That's a _really_ bad design decision. Not only OsmAnd now works different than absolutely _every_ other software, the change even comes with absolutely no benefit, just making an important function difficult to access. I don't get it. Why?

**Comment by dmpr0** [comment]
> Wow. That's a _really_ bad design decision. Not only OsmAnd now works different than absolutely _every_ other software, the change even comes with absolutely no benefit, just making an important function difficult to access. I don't get it. Why?

OsmAnd now works as any other map software:  https://github.com/osmandapp/OsmAnd/issues/20494#issuecomment-2268395012. 

And even better, I can't find any other map software with more than two compass modes.
