### ISSUE TITLE
Portugal map - Live Updates

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#2046]
I have the Spain and Portugal maps installed, the most recent from 02-12-2015.
If I download the 'Live Update' for Spain, it gets the Spain_europe_15_12_00.obf and the current day file.
But if I do the same for Portugal, it downloads the  07, 08, 09, 10, 11 and 12 month files. 
I would expect these past month files to be already included in the most recent map from month 12, right?

**Comment by Barrocas** [comment]
This issue with Portugal map still happens when the 'Live' folder is deleted, and we do the OSM Live update.

**Comment by Barrocas** [comment]
Using the night builds, and 01-2016 maps.

**Comment by Barrocas** [comment]
Issue is still the same, when the Live folder data is deleted, Osmand Live Update "Update Now" downloads all data from 2015-07 until today, causing a lot of unnecessary data traffic to download.

**Comment by vshcherb** [comment]
Can't reproduce, just downloaded Portugal map and got only 2 updates 16-02 and 16-02-23

**Comment by Barrocas** [comment]
That's also what I get in the Live folder files, but if the Live folder is deleted, and you download the Live data again, it does download all data since 2015-07, then in the end it groups it all in those two files.
Spain updates run as expected (only downloads 2 files).
Portugal updates don't do what is expected, it  downloads 9 files, in the end results in 2 files.

**Comment by vshcherb** [comment]
>>  the Live folder is deleted
Did you try to delete portugal map and download new one fresh?

**Comment by Barrocas** [comment]
Yes, I did that today, and it remained the same.
And I also install fresh builds almost daily for testing, all do the same.


-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by vshcherb** [comment]
Do you have any explanation why I can't reproduce it or why Spain works for you fine?

**Comment by Barrocas** [comment]
Sorry, I have no clue. If I had any idea of what could cause this, I would
have suggested.

I tried deleting the Portugal map and downloading it again, installed
several night build versions, but no luck. If I delete the Live files (like
when starting over) it always downloads those 2015-07 files onward.

And Spain map Live updates works nice and simple, just the 2 expected files.

I also cannot explain why it happens on my phone and not on your setup.

For me, it really doesn't make a difference, since I have no problem with
data download restrictions.
but if it happens to a user with limited data access, it may be unpleasant.


-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by vshcherb** [comment]
The main question is : does it happen for other people with other maps. If it is one device/ one map problem, that's not a big issue. Most likely it is something hidden, I asked other people to reproduce it and monitor the situation. The issue it updates from certain month is completely unclear.
May be you build Portugal map yourself or you have Portugal road only maps or may be contour lines have impact on it.

**Comment by xmd5a2** [comment]
When I use live updates over fresh Portugal maps it downloads only two files - 16_02_00 and 16_02_24

**Comment by Barrocas** [comment]
For me it still downloads from 2015-07 until today.
I've removed Spain map, and added Spain-Galiza map (much smaller), and it does the same.
Always most recent maps.

**Comment by Barrocas** [comment]
Maps are downloaded within Osmand (not build by me) and they're full data maps, not road only.
