### ISSUE TITLE
`Terrain` (Hillshade / Slope) toggle inverted operation

### ISSUE THREAD

**Issue by ManDay** [osmandapp/OsmAnd#20466]
As of 4.8.3 (F-Droid), the "Terrain" toggle for *Hillshade* / *Slope* will have the opposite effect in the map view **if the mode is set to Hillshade** (and only then). **Enabling** it will *not* show the overlay, and **Disabling** it *will* show the overlay.

**Comment by ManDay** [comment]
There seem to be related issues. For example:

- Enable "Terrain"
- Set mode to "Slope"
- Disable "Terrain"
- Enable "Terrain"

the mode will still be set to "Slope" but "Hillshade" will be displayed

**Comment by yuriiurshuliak** [comment]
Currently, the latest version of the OsmAnd app is 4.8.4. Please try using this release version and let us know how it works for you.

Also in the future, please attach screenshots or videos that clearly show the problem.

**Comment by ManDay** [comment]
4.8.3 is 2 days recent on F-Droid, I'm not sure where/if a nightly APK of OsmAnd~ is released anywhere, if yes, please point me to it. Video attached.

https://github.com/user-attachments/assets/537f9409-933a-47e2-b87a-6e403a514212

**Comment by dmpr0** [comment]
@ManDay Hi! Did you have 3D Relief turned on?

**Comment by ManDay** [comment]
@dmpr0 I did. When I disabled it just now (and cleared the cache), Hillshade started working and kept working after I re-enabled relief. Now I can't reproduce it anymore (feel free to close?)

**Comment by ManDay** [comment]
I take that back, the issue has indeed *returned* (with relief enabled)!

**Comment by ManDay** [comment]
I figure what I'm seeing with "Relief" enabled isn't actually the Hillshade, but the "Relief"s own shading of the slopes, and activating "Terrain"/"Hillshade" makes that disappear but fails to render its own (darker) shading...

**Comment by ManDay** [comment]
Fixed in 4.8.4, it seems.
