### ISSUE TITLE
Export/Import of Profiles in readable format

### ISSUE THREAD

**Issue by GuentherGredy** [osmandapp/OsmAnd#20461]
### Describe the idea (required)

The idea is to export/import profiles in a readable format, e.g. XML. This would allow to compare different versions of the same profile, resp. compare settings across different profiles; also it would be possible to quickly edit a parameter and import the modified profile again.

### Tell us about the expected behaviour (required)

Recently while biking I had a problem with the power consumption of the application. I had no idea, which setting caused the enormous consumption while navigating a route. So I asked your support and got a few suggestions what to configure. This helped. Thank you.
The high number of features of the application makes a fine tuning of parameters rather difficult.

### Tell us about alternatives you've considered (required)

The current format is not readable, so there is no alternative.

### Context (optional)

No.

**Comment by Velomeloman** [comment]
osf is just zip archive. Unpack it to see  some of json files with settings.
