### ISSUE TITLE
Improvement: Not all amenities are interesting (POIs)

### ISSUE THREAD

**Issue by pl71** [osmandapp/Osmand#2047]
In Search/POI there is a menu item at the bottom named 'Nearest POIs'.
Search results here include some strange items like **Stairs** (from [highway=steps] (http://wiki.openstreetmap.org/wiki/Tag:highway%3Dsteps)), **Stop lights** (from [traffic signals] (http://wiki.openstreetmap.org/wiki/Tag:highway%3Dtraffic_signals)), even [Survey points] (http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dsurvey_point). 
As per my opinion there should be a more strict filter implemented.

**Comment by xmd5a2** [comment]
Stairs can be interesting for disabled (handrail, ramp, step count). Traffic lights and highway crossings too (traffic_signals:sound=*). Survey points are often good landmarks and can be used for orienteering.

**Comment by vshcherb** [comment]
Nearest POI introduced in the bottom because many people want to see everything in OSM, but it is not generally advised to use it at all. On of the discussion could be related to enable it or move it to settings.
