### ISSUE TITLE
Direction arrows is wider than route line – Android Auto

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#20470]
### How to reproduce
* Connect mobile device to vehicle
* Start navigation using OsmAnd on Android Auto

### Actual result

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/1e7f5267-8f04-4d17-8e39-529b3c97c405"  width="400" height="auto"/> </td>
  </tr>
</table>   

* Direction arrows is wider that route line

### Expected result

* Direction arrows and route line width should be scaled correctly. Direction arrows should be narrower than a route line.

**Environment**
OsmAnd Version: 4.8
Android: 15
Device model: Google Pixel 6A

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/commit/8ef89cc4bedfb9ac6e138f6ed1003fd1156a6d51
https://github.com/osmandapp/OsmAnd-core/commit/ada80c0ec1b22bcb078898bda9932eec1ff429c7

**Comment by Zirochkabila** [comment]
`OsmAnd~ 5.0.0#3869m, Released: 2024-12-03`

Directional arrows do not go beyond the route line
