### ISSUE TITLE
Icon of position when moving

### ISSUE THREAD

**Issue by luigifab** [osmandapp/OsmAnd#20475]
With the latest OsmAnd update, the icon of my current position (circle) doesn't change (to arrow) when I'm moving.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/e0dab976-62b7-454e-9b12-4957bdee564c"  width="300" height="auto"/> </th>
  </tr>
</table>

OsmAnd 4.8.4 on Android Go 11

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce this issue, ensure that in Profile appearance, the Resting position icon option is set to a circular position icon, and the Navigation position icon is set to an arrow position icon. Then start the navigation.

As a result, you will notice that during navigation, the position icon arrow is not displayed for the Navigation position icon; instead, a circular position icon is shown.

OsmAnd~ 4.9.0#2887m, released: 2024-08-01

https://github.com/user-attachments/assets/d7748d58-97b2-4ac5-b102-150a41d5f0ab

**Comment by MarioSwitch** [comment]
I've had the same problem when updating to 4.8.x (don't know exact version).

My workaround was to change one icon and reset the same icon, and at this moment, you could click "Apply" and the bug disappears...
