### ISSUE TITLE
Please update Lithuanian voice packages from recent OsmAnd-resources source code

### ISSUE THREAD

**Issue by embar-** [osmandapp/OsmAnd#20476]
### Description

The last packaged Lithuanian (LT) voice had error, which was fixed in https://github.com/osmandapp/OsmAnd-resources/pull/1090 . Please @sonora  update LT voice packages, both versions: single TTS version and packaged with "recorded" OOG audio version.

This update request was already in https://github.com/osmandapp/OsmAnd-resources/pull/1090#issuecomment-2260250699 but seems actions in https://github.com/osmandapp/OsmAnd-resources/pull/1090#issuecomment-2263381773 did not take effect...

### Steps to reproduce

Several ways to test:
- Open OsmAnd 4.7 or 4.8, go Maps and Resources, Voice prompts (either TTS, either recorded)
- Go to https://download.osmand.net/list.php or 
- directly download https://download.osmand.net/download?standard=yes&file=lt_0.voice.zip

### Actual result

LT voice package version is old: date of 2024-05-08

### Expected result

Version date is recent

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.8
Android/iOS version: Android 14
Device model: Samsung tablet
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
By visiting the OsmAnd Local Indexes List at [this link](https://download.osmand.net/list.php), you can see that the Voice Data for Lithuanian was updated on 08.05.2024.
Related to https://github.com/osmandapp/OsmAnd-resources/pull/1090

**Comment by embar-** [comment]
Yes, 08.05.2024 = 2024-05-08 = May 8th, but it is outdated, because few days ago we fixed LT TTS JavaScript

**Comment by sonora** [comment]
TTS should be fine, because the file is packaged with the app, so the next update (presumably 4.8.5) will contain it. Should also be already contained in the nightly build.

But in deed the recorded voice package has not updated on https://osmand.net/list.php, although I've run the job twice now. Either I am fatfingering something here, or there is an issue. @vshcherb  Any idea?

**Comment by sonora** [comment]
It seems this has finally updated on August 4, so I am closing this issue.

**Comment by embar-** [comment]
I confirm that updated voice package works.
