### ISSUE TITLE
Terrain Slope and Hillshade share same Visibility setting.

### ISSUE THREAD

**Issue by Guylby** [osmandapp/OsmAnd#20488]
### Description

Hi,

I think this is a bug as with the new color palettes and Altitude terrain shading settings the Visibility setting is independent for each profile. 
However, if you change the Visibility setting for the Slope profile, when going back to the Hillshade visibility will be changed and vice versa. This behaviour is not present with the Altitude setting (and if using different Altitude color palettes, each palette has its own Visibility setting and can be individually customized).

### Steps to reproduce

Go the the Configure Map>Terrain>Visibility Setting and change opacity.
Change Terrain setting from Hillshade to Slope or vice-versa
Notice that the visibility setting affected both Hillshade and Slope

### Actual result

<video src=https://github.com/user-attachments/assets/2ba058bf-a9e4-4b67-aa6e-0fc66a60c5d1></video>

### Expected result

Slope and Hillshade have their own independant Visibility setting

A workaround is to manually change opacity in the hillshade and slope .txt file with the RGBA code, but it's not ideal

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.8.4
Android/iOS version: 13
Device model: Sony Xperia 10 III
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
The bug has been successfully reproduced. To replicate it, navigate to Configure Map - Terrain and set Hillshade visibility to 100%. Next, select Slope and adjust its visibility to 50%. Then, when you go back to Hillshade, you'll see its visibility has also changed to 50%, matching Slope's setting.

This dependency prevents independent adjustment of these settings. To fix it, we need to make Hillshade and Slope visibility settings independent of each other.

OsmAnd~ 4.9.0#2909m, released: 2024-08-06

https://github.com/user-attachments/assets/a7f156e1-d8c0-4b42-8f85-aab642366807
