### ISSUE TITLE
Problem of compile OSMAnd with android studio

### ISSUE THREAD

**Issue by NewbieOfAndroid** [osmandapp/Osmand#2048]
I am trying to build the OSMAnd using Android Studio

I am getting following error message
![error_1](https://cloud.githubusercontent.com/assets/16266117/11761441/18532f34-a0fe-11e5-80a6-44b4e5538161.PNG)

and i try ignore it with using comment the code with error(cannot resolve symbol), with that i able to build and run the project

![error_3](https://cloud.githubusercontent.com/assets/16266117/11761527/5f50c59c-a101-11e5-95fe-86212d9444a5.PNG)

but when the application running, it will pop up the error message, then the application crash and close automatically.

![screenshot_2015-12-12-18-09-07](https://cloud.githubusercontent.com/assets/16266117/11761515/ba97b83a-a100-11e5-8e90-8455b879772c.png)![screenshot_2015-12-12-18-07-37](https://cloud.githubusercontent.com/assets/16266117/11761516/c0acb1e4-a100-11e5-979e-672d3bf4703e.png)![screenshot_2015-12-12-18-25-25](https://cloud.githubusercontent.com/assets/16266117/11761518/d2daa678-a100-11e5-819c-583ec6a682ba.png)

may i known how to fix this? 
sorry for the long question, i am newbie in android

**Comment by vshcherb** [comment]
Please search for similar issues, not using Android Studio.
