### ISSUE TITLE
Android Auto - not inform about leaving motorway/espressway

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#20498]
### Description

It randomly doesn't inform about leaving the motorway/expressway. When I set the route and check directly on my mobile everything looks correct and I have the "turn slightly right" command. When riding on AndroidAuto I just have next command after leaving the trunk.

|Android Auto| Web simulation|
|---|---|
|<img width="400" alt="image" src="https://github.com/user-attachments/assets/96909fe1-4400-4019-a4f5-dbf38868818b">|<img width="400" alt="image" src="https://github.com/user-attachments/assets/6ae8ec7d-f397-4f10-b78f-4cea55bce858">|

### Steps to reproduce

1. https://osmand.net/map/navigate/?start=52.094642,20.382181&end=52.103339,20.360686&profile=car#15/52.0931/20.3650

### Actual result

For AA not to show about leaving motorway/expressway

### Expected result

Show "turn slightly right" for AA

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.8
Android/iOS version: 14
Device model:
Crash-Logs: ?
```

**Comment by dmpr0** [comment]
![telegram-cloud-photo-size-2-5298778566021996849-x](https://github.com/user-attachments/assets/4bb52a21-1af3-4acd-a55d-d29e274445b9)
