### ISSUE TITLE
Some street numbers don't appear despite the address being on the area/node

### ISSUE THREAD

**Issue by klondi** [osmandapp/Osmand#2049]
https://www.openstreetmap.org/node/3860938999 is a "main entrance" node added so I coould tag number 8 of the "Avenida de Francia" street so at least some of the street numbers would appear.

Despite this, after waiting for the obf maps to update the node is shown on the map but no street numbers appear for the street.

A similar issue happens with https://www.openstreetmap.org/way/298794518 which despite being tagged with the full address won't appear on the map.

**Comment by xmd5a2** [comment]
Fixed. Fix will come with new maps.

**Comment by klondi** [comment]
Thanks!
