### ISSUE TITLE
Android auto: map orientation always set to north

### ISSUE THREAD

**Issue by gryf** [osmandapp/OsmAnd#20496]
### Description

Whether or not map orientation for driving profile (in fact, I've set it to all) is set to "Movement direction", when select navigation through Android Auto, it switch to "north is up". There is no way to change orientation, as the icon for cycle options is not shown - it's only available in "Free ride" mode.

### Steps to reproduce

Use OSMAND with Android Auto, set navigation, map is north oriented.

### Actual result

Map is north oriented when using Android Auto when in navigation.

### Expected result

Map is oriented to whatever is set in driving profile when using Android Auto in navigation mode.

### Your Environment (required)

```
OsmAnd Version: 4.8.4, released 2024-07-24
Android/iOS version: 14
Device model: Motorola moto g32
Crash-Logs: n/a
```

**Comment by vshcherb** [comment]
If you click on icon Direction it should switch to movement direction, however it could be related to this issue https://github.com/osmandapp/OsmAnd/issues/19839 when buttons are not active

**Comment by gryf** [comment]
When in navigation mode there is no Direction icon on the car display, only gear. As I said, it is only visible in "free ride".

**Comment by dmpr0** [comment]
Hi!
Could you please provide photo or screenshot from Android Auto screen?

**Comment by gryf** [comment]
Free ride:
![freeride](https://github.com/user-attachments/assets/4de30de0-27d0-4b3e-bd8c-e9fe99efb7f0)

and navigation:
![navigation](https://github.com/user-attachments/assets/f7680c32-0132-45bd-939a-b109746c6290)

**Comment by gryf** [comment]
hm. just realized, those pics are done when I've driving north :sweat_smile:

**Comment by dmpr0** [comment]
@gryf thanks for photos

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/eacea1fd-a779-466e-86fe-e7348eafa212"  width="300" height="auto"/> </td>
  </tr>
</table>   

The compass button is the third from the right on the Free ride photo.
- - -

<table style="width:100%">
  <tr>
    <th>Emulator preview</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/d231c6d0-2d0f-4942-a1cb-5d2897fc491b"  width="300" height="auto"/> </td>
  </tr>
</table>   
 

The second photo shows the route preview screen, which currently doesn't have a compass button. I'm checking if we can add one to this view. However, once you tap 'Start,' a new screen will open, and the compass button will be available there.

**Comment by gryf** [comment]
oh! I totally missed not-so-obvious thing as "start" to click/tap. I'll check it out, and let you know.

**Comment by dmpr0** [comment]
@gryf Unfortunately we can't do this, because all layouts are provided by Google and they all similar for all app of one type.

**Comment by gryf** [comment]
I see. So it's Google fault ;P Anyway, thanks for giving me right directions.
