### ISSUE TITLE
Feature request: Support for custom map styles

### ISSUE THREAD

**Issue by OWL4C** [osmandapp/OsmAnd#20491]
### Describe the idea (required)

Allow for custom offline map styles, so you can create versions of inbuilt styles by editing their xmls.
For example, you could download the osm map style from opentopomap.org, import it into osmand and have the custom style (with fallback so non defined things just look like one of the built in styles)

### Tell us about the expected behaviour (required)

Add a custom settings page where you can add new offline map styles.
Within this page you can create a new style, which is just custom xmls you import on top of a chosen style. So you could have the standard map style but use the street style from topo, or change the color of single objects to your liking.

### Tell us about alternatives you've considered (required)

-

### Context (optional)

-

**Comment by dmpr0** [comment]
You can duplicate and modify any OsmAnd map style https://docs.osmand.net/docs/technical/osmand-file-formats/osmand-rendering-style

**Comment by OWL4C** [comment]
Forgive me if I misunderstood that page, but as far as i understand it, you would have to make a custom build/app or similar, i was more hoping for an in app theme manager akin to the profiles list, where you can import custom themes. 
At least for the iOS App, i have not found such an option.

**Comment by dmpr0** [comment]
> Forgive me if I misunderstood that page, but as far as i understand it, you would have to make a custom build/app or similar, i was more hoping for an in app theme manager akin to the profiles list, where you can import custom themes. At least for the iOS App, i have not found such an option.

Unfortunately OsmAnd doesn't have in app theme editor. OsmAnd can import and export `.render.xml` files, both on Android and iOS

**Comment by OWL4C** [comment]
So maybe the FR can be reinterpreted as a in App Editor then, but thank you for the info about .render.xml!
