### ISSUE TITLE
Vector text on WMS

### ISSUE THREAD

**Issue by Raiedecharles** [osmandapp/OsmAnd#20497]
### Description

Hello,
On a raster stream display, we see the labels of the vector layers... it's very annoying.

### Steps to reproduce

just launch a WMS stream

### Actual result

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/1678bb93-5fcd-4d3c-be94-560abbb17326"  width="300" height="auto"/> </th>
  </tr>
</table>

### Expected result

desactivate vector text 

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
Related to https://github.com/osmandapp/OsmAnd/issues/18923 https://github.com/osmandapp/OsmAnd/issues/19303

**Comment by yuriiurshuliak** [comment]
Try to clear map tiles cache:
Menu → Download maps → Local → Online and cached tile maps → choose online maps →⋮ → Clear all tiles

Also have you set underlay map? Do you use vector or online OsmAnd maps?
Could you please provide your profile settings. Go to menu > settings > your profile > export profile.

**Comment by vshcherb** [comment]
Duplicate https://github.com/osmandapp/OsmAnd/issues/20003#issuecomment-2269907801

**Comment by Raiedecharles** [comment]
ok i delete all the data via android menu.

I dl vector map et i have still the problem .... there is unstability with the render engine : 

i can't put osf extension in this message 
thanks

**Comment by vshcherb** [comment]
You can delete all data world basemap mini is still present it's part of the app, it's a duplicate issue needs to be solved

**Comment by Raiedecharles** [comment]
i delete all the basemap and other data. If i download vector data on a zone...i still have the same problem all the time with a raster map stream

**Comment by vshcherb** [comment]
Duplicate https://github.com/osmandapp/OsmAnd/issues/20003#issuecomment-2269907801 - going to be fixed there
