### ISSUE TITLE
Some borders with admin_level=2 are not included in basemap

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#2050]
Look at France, Nepal:
https://dl.dropboxusercontent.com/u/4624786/osm/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%20%D0%BE%D1%82%202015-12-11%2021%3A04%3A25.png
Also look at thin lines: Russia, India, Norway does not have admin_level=2 borders at all. Visible thin border is taken from neighbourhood countries.
polygon_admin_level2.osm does not contains at all these lines. OSM data is correct. admin_level=2 tag exists on these ways and also relations.
Way to test:
https://www.openstreetmap.org/way/173204589

**Comment by vshcherb** [comment]
We need to check osm db for these lines.

**Comment by xmd5a2** [comment]
gis=> select name from planet_osm_line where osm_id = '173204589';
         name         
----------------------
 France - Deutschland
(1 row)

**Comment by vshcherb** [comment]
I guess that issue could be internally resolved, at least we don't track it here, unless the screenshots are taken from the map we already released
