### ISSUE TITLE
Analyze by intervals - "None" does not work

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#20503]
Small UI glitch, as follows:

- On a GPX track's context menu, tap "3-dots (Options)", then "Analyze by intervals", and select a value, e.g. "1km".
- Now on that screen decide to go back to "None": The screen will accept to go to any other interval, but not back to "None".
- Also leaving the screen via the back-button after selecting "None" and then re-entering it will bring it back up with the previiously selected interval.

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. Try to click on the GPX track, select Options, then Analyze by intervals, and choose 1km in the Split interval column. After that, try selecting "None" again.

In my case, the selection changes from 1km to "None", but the information still displays as if 1km is selected. Also if you exit the screen using the back button after selecting "None" and re-enter, it resets to the previously selected 1km interval.

Additionally, leaving the Split interval at 1km, exiting settings, and re-entering through Options - Analyze by intervals changes the interval back to "None."

OsmAnd~ 4.9.0#2909m, released: 2024-08-06

<table style="width:100%">
  </tr>
  <tr>
    <td> <video source src="https://github.com/user-attachments/assets/64b5f75d-aa24-402e-a256-126414e90485"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/user-attachments/assets/769684e1-c048-44a1-81ac-7706ca46552d"  width="300" height="auto"/>   </td>
  </tr>
</table>
