### ISSUE TITLE
OsmAnd~ 4.8.4 conflicts with free OsmAnd

### ISSUE THREAD

**Issue by andrzej-gmt** [osmandapp/OsmAnd#20500]
### Description

Since version 4.8.4 one can't install simultaneously free OsmAnd from Playstore and OsmAnd~ from F-Droid. Trying to sideload OsmAnd~ 4.8.4 gives info about conflict with other app.

There is no conflict with Playstore OsmAnd 4.8.4 and Playstore OsmAnd+ 4.8.4.
There is no conflict with Playstore OsmAnd 4.8.4 and F-Droid OsmAnd~ 4.8.3.

### Steps to reproduce

As in description: try to install OsmAnd~ when OsmAnd is already installed.

### Actual result

Can't install or upgrade OsmAnd~.

### Expected result

Normal upgrade of OsmAnd~ form 4.8.3 to 4.8.4, regardless if OsmAnd is installed.

### Your Environment (required)

OsmAnd Version: 4.8.4
Android/iOS version: Android 12, LineageOS 19
Device model: Xiaomi Poco X3 Pro

**Comment by yuriiurshuliak** [comment]
If you have issues after updating to F-Droid OsmAnd~ 4.8.4, this is an issue on the F-Droid side. We are not affiliated with the app on F-Droid. We advise you to contact them with this question.

**Comment by andrzej-gmt** [comment]
Yes, it seems that problem is only with F-Droid compilation. Sorry to bother you.

**Comment by SpiritInAShell** [comment]
AFAIK, the F-Droid builds are signed with their (F-Droid's) keys. Android seems to not allow to update an installed app signed with key A with another same-name package with key B.

With other tools like Termux it is not even possible to install the extensions like Termux:Boot from Play store, when having Termux from F-Droid and vice-versa.

So the key seems to be not only specific to the package, but to the author.
