### ISSUE TITLE
Not showing next maneuvers during routing

### ISSUE THREAD

**Issue by JustACasual** [osmandapp/OsmAnd#20516]
Hi all,

From time to time when I go for longer trips, Osmand will only show the first few turns, then (I think once I enter the highway) it will just show me the very last turn on the whole trip as being the next turn. So it skips all of the turns in between. Navigation is correct though. If during driving I stop the current navigation and re create it, it will correctly show me the next turn.

Please see these 2 screenshots, first one shows I should go 358km of my 360km trip on the same highway, which is wrong.

Then I made a screenshot, stopped navigation and newly navigated to the same destination. That's the second screenshot.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/933f785d-17fc-4191-97de-c5c9c34f61fe"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/0679b95b-f2ac-4faa-8fde-9ec6a3f68e28"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by JustACasual** [comment]
Not sure if this might be related to #20123

**Comment by JustACasual** [comment]
This is another occurrence where the screen shows it is correctly expecting me to leave the highway, but next turn shows being only in 11 km.

![Screenshot_20240714-161618.png](https://github.com/user-attachments/assets/989bcef5-2816-4dc3-b910-bcfce4af5a3e)

**Comment by DmitryAlexei** [comment]
initial issue https://github.com/osmandapp/OsmAnd/issues/19065
@JustACasual  do you use the latest 4.8 build?
Could you please provide your route from [OsmAnd map](https://osmand.net/map/) ?  Simply copy it from the address bar.

**Comment by JustACasual** [comment]
> @JustACasual  do you use the latest 4.8 build?

No, I am on 4.7.17, also Google play doesnt offer me any update.
I got this Osmand live subscription if that's of any help
![Screenshot_20240807-201220_1.png](https://github.com/user-attachments/assets/27076af1-6bee-490b-a930-21a9e881c9bd)


> Could you please provide your route from [OsmAnd map](https://osmand.net/map/) ?  Simply copy it from the address bar.

To be honest, I don't know what to do I am sorry. Can you give more details on what you need from me? :)

**Comment by DmitryAlexei** [comment]
There are few options to make sure that your issue is fixed or not:
- you can join beta testing program in Google Play or try OsmAnd nightly (here the links to beta and nightly https://osmand.net/docs/versions/nightly_versions) and try your route next time or by simulating navigation. Turn information can also be found in route details 
or
- you can try to replicate your route on OsmAnd map (link https://osmand.net/ ) and see if the turns are correct

If the lanes' indication on the OsmAnd map isn't correct, please provide the link from the address bar in the comment below. For example see https://osmand.net/map/navigate/?start=49.386968,11.150951&end=49.384866,11.126254&profile=car#15/49.3808/11.1417

<img width="1235" alt="Screenshot 2024-08-08 at 00 36 27" src="https://github.com/user-attachments/assets/06a86560-1794-4a24-9667-df41da9054ab">

**Comment by JustACasual** [comment]
Hi, thanks for the hint that route details in the app should also show all the turns, even without starting the navigation. I did that with some routes I know the bug happens on, but could not provoke it this way, also not on 4.7. Route details always correctly showed all the turns. I am sure the website would behave correctly as well. Although I was not able to test it as I don't have a laptop with me right now and I find it hard to use on mobile.

I remembered now that I installed Osmand through F-Droid, not Play store. So I upgraded manually to 4.8.4 on F-Droid and will just continue to observe it the next weeks.

Anything more I could do when the error occurs again? I mean in that very moment?

**Comment by DmitryAlexei** [comment]
@JustACasual you can continue testing and report issue here, on Github. 
We are reviewing all new messages and will try to reproduce new cases - so developers can fix them.

**Comment by JustACasual** [comment]
Hi, I made a few longer trips in the meantime and it didn't happen anymore on 4.8.
So it might really be a bug in the 4.7 version :O

I consider this issue solved.

Also, offline route calculation is so much faster with this version. Has this been optimized in this version? 
Great!!!
