### ISSUE TITLE
Chiang Mai Thailand Error

### ISSUE THREAD

**Issue by dellboy218** [osmandapp/OsmAnd#20515]
### Description

Good Day.  I was advised to send a map error to this address.
Just to correct your map. The name of the village in the attachment is a nonsense as is the sxy designation. I also attach a Google Map screen shot of the same area. The village name is Chiang Mai View Suay (or Suai)2. Sxy should be replaced by Soi which means a lane. Google maps has a road going through my garden. In that they are wrong as is my house number. It isn't 208. Google maps preface the village name with Mu Ban, one of many spelling variations. It just means village.
![Ashampoo_Snap_Tuesday, August 6, 2024_20h19m3s_001_8pYOWd6fz00sa3K02WPcW0Pa6 (1080�2400) - Comodo Dragon](https://github.com/user-attachments/assets/838282f6-fc63-4244-b9e4-3156b6b5c1f5)
![Ashampoo_Snap_Tuesday, August 6, 2024_20h19m45s_002_swsCGNnCrAk7f3aU81cLT2dre (1080�2400) - Comodo Dragon](https://github.com/user-attachments/assets/0c4c4078-f434-473a-9172-653a37425773)

Thankyou

### Steps to reproduce

OSM map any device

### Actual result

A really annoying attempt at speaking the name

### Expected result

Hopefully You can correct it!

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by MarioSwitch** [comment]
Map data are provided by OpenStreetMap, feel free to correct / add information on their website: https://www.openstreetmap.org/
