### ISSUE TITLE
incorrect lane indicator

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#20524]
### Description

At an exit on a tree-lane-higway the lane indicator tells me to keep left to get the exit to the right

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/9c7ded80-b5a2-4ed5-a166-0eb39335bc27"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/7ff956df-e631-4eda-bfd9-da4778ad0f3e"  width="500" height="auto"/> </td>
  </tr>
</table>

It happened here:

https://www.osmand.net/map/navigate/?start=48.244082,16.397846&end=48.253927,16.377354&profile=car#16/48.2541/16.3843

### Steps to reproduce

I dont know, it just happened

### Actual result

wrong information

### Expected result

show the correct information

### Your Environment (required)

OsmAnd Version: nightly 4.9.0#2904 
Android/iOS version: 13
Device model: S20+

**Comment by schnedann** [comment]
what about that smaller right in 100m below? and maybe the yellow arrow mean continue going in straight direction after crossing the river?

**Comment by Rowin63** [comment]
This "keep left" refers to this one exit directly before. But routing leads to the next exit, so this "keep left" is irritating, because all previous exits all the kms before are not announced to "keep left".

 
![keep left](https://github.com/user-attachments/assets/06b0fa36-4fc3-499c-a777-951d84c12e1a)

**Comment by DmitryAlexei** [comment]
- works correctly on web
- OsmAnd nightly: correct turn arrow in Lanes widget, but the arrow in the Next turn widget may be incorrectly interpreted by the user

https://www.osmand.net/map/navigate/?start=48.244082,16.397846&end=48.253927,16.377354&profile=car#16/48.2541/16.3843
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/8913a006-4d64-4f67-ac93-a425018d4f40"  width="700" height="auto"/> </td>
  </tr>
</table>

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/dc7c3d14-a4db-430f-b2b7-368fa1ccbfe1"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/e2c0d527-4f67-4586-a576-f1df1d8ebd3d"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Rowin63** [comment]
It still doesn't feel correct to me. There's no right turn at all at the first exit, you're just passing it by.

**Comment by DmitryAlexei** [comment]
@Rowin63 turn:lanes =  none |none |through | **slight_right**;right - this is how turn lanes are mapped in OSM https://www.openstreetmap.org/way/658308474

and lanes at the next junction:  none |none |through | **slight_right** https://www.openstreetmap.org/way/525350137
