### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by NewbieOfAndroid** [osmandapp/Osmand#2052]
when open the app it will crashes and close automatically
![screenshot_2015-12-13-16-21-05](https://cloud.githubusercontent.com/assets/16266117/11766186/a2aaeaa6-a1b6-11e5-8531-b018c3bb0ee7.png)   ![screenshot_2015-12-13-16-19-09](https://cloud.githubusercontent.com/assets/16266117/11766187/a3e2ddac-a1b6-11e5-8b59-4a0f3e271ea7.png)

here is the logcat
![log](https://cloud.githubusercontent.com/assets/16266117/11766194/0a17f2ec-a1b7-11e5-97ba-5e2ffa058e95.PNG)

[logcat.txt](https://github.com/osmandapp/Osmand/files/60385/logcat.txt)

**Comment by vshcherb** [comment]
Looks like it was assembled in a wrong way.
