### ISSUE TITLE
Very strange map scale factor within screen

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#20531]
### Description

As you can see in screenshots 1 and 2, the map scale factor looks different in upper against lower part of map, the gap grows when moving map up and reduces when map moving down.
In the video i move the map in a circle, you see the upper and lower part moving with different speed right - left and the gap resizing.

Problem exits since nightly version about 
OsmAnd~ 4.8.0#2856m, veröffentlicht: 2024-07-29 and also with tested 2868, 2876, 2887, 2902, 2904, 2929.
I have this problem with
Samsung S10, Android 12.
Maps Germany_baden-wuerttemberg_europe.obf, Germany_baden-wuerttemberg_freiburg_europe.obf, both with date 07/2024 and 08/2024
Of cource the two tested maps are not active at same time.
Edit: problem only with **Rendering engine 2**, no problem with r.e.1

NO problem with Samsung tab S5e Android 10 with
OsmAnd~ 4.8.0#2849m, veröffentlicht: 2024-07-26
same map as with other device from 07/2024.

Position of green map marker is 47.98987 7.84422, city of Freiburg
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/3e91a7bf-7154-4eb0-9dd5-1c663b7fdfea"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/6f2654f3-ee29-47d4-aaf0-096481aa5ff7"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/7a87febe-08d6-425a-95f7-943e037545a8"  width="300" height="auto"/> </td>
  </tr>
</table>

https://github.com/user-attachments/assets/58f3d06a-7186-448c-ba38-08edbe43b4b6

### Steps to reproduce

See above

### Actual result

See above

### Expected result

See above

### Your Environment (required)

See above

**Comment by pebogufi** [comment]
First screenshot was taked at app start before rendering of map, see the different size of squares in upper vs lower part.

**Comment by pebogufi** [comment]
Uper left edge of problem area is near 47.98979° N, 7.73452° E (orange flag).

![Screenshot_20240808_113436_OsmAnd~](https://github.com/user-attachments/assets/a8bd9443-19fd-4b49-a6db-9534a16d6096)

**Comment by pebogufi** [comment]
Lowe rightcornet (red flag) is 47.98954° N, 8.43772° E

![Screenshot_20240808_114130_OsmAnd~](https://github.com/user-attachments/assets/8faab740-f4c9-4f1a-801c-a668ccf6983e)

**Comment by Andrewschenko** [comment]
It looks like the heightmap cache has some inconsistent data. Try to clean app's cache.

**Comment by pebogufi** [comment]
After removing (renaming) dir geotiff no more problem. It is reproducable (by renaming back).
So problem solved.
Close issue ?

**Comment by Andrewschenko** [comment]
It would be great to know if clearing the cache can solve this problem. Geotiff is a data folder. Was there any custom data put there?

**Comment by pebogufi** [comment]
I checked again. Only removing cache did not change/solve the problem, only removing geotiff folder. In geotiff i did never change or add anything. In this folder are 10 files (Heightmap France provence-alpes-cote-d-azur europe.tif) and other but all of france, file date 202**3**-04-01. 
No file of problem region in Germany_baden-wuerttemberg. That is surprising.

**Comment by pebogufi** [comment]
Ok, thanks a lot.

**Comment by vshcherb** [comment]
It doesn't look like regression. It was always like that, so it is known issue
