### ISSUE TITLE
Regression about foreground service / notification control

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#20536]
Observed with today's nightly, not yet present on 07-26 nightly:

- Record a track
- Tap the record widget
- On the record control dialog, tap 'Options', then 'Stop without saving'
- Confirm with 'Stop'

With the latest build, the Android notification is not removed from the notification bar, likely the foreground service is not stopped cleanly. Even after stopping the app, the notification remains visible (its Save button has no functionality in this situation).

EDIT: Issue also occurs when finishing a recording 'normally', i.e. with saving the track.

**Comment by sonora** [comment]
Potentially caused by https://github.com/osmandapp/OsmAnd/commit/fd3474ac6e3ef427f451bf9099f05e1bd8c0b393.

**Comment by vshcherb** [comment]
Yes we almost wrapping up this FGS / targetSDK  = 34, hopefully now we have full picture of what's going on

**Comment by sonora** [comment]
Looks like our release version 4.8.5 contains the above commit, so is potentially affected by a notable bug here... (?)

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. In my case, when you enable track recording and select 'Stop without saving' in the app, the recording stops as expected. However, the notification panel still displays the recording track tab as if the recording is paused, and you can't clear it from the panel. The options to delete and save are unresponsive.

OsmAnd~ 4.9.0#2935m, released: 2024-08-08

<table style="width:100%">
  </tr>
  <tr>
    <td> <video source src="https://github.com/user-attachments/assets/c5e0aa8f-81f2-4acd-8a63-594a7cb7b6d4"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/user-attachments/assets/899a69e4-e8f8-425d-bae6-638b2b2affa0"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by scaidermern** [comment]
I experienced the same with 4.8.6. After stopping and saving the track, the notification remains and says "paused" which is wrong. A (hard) restart of OsmAnd is required to make the notification disappear.

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/commit/fd7d0d07b6998407b6aa70b9534a3056d9fee25b

**Comment by sonora** [comment]
I still see that issue, it's likely not fixed...

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/commit/f6a3c1e8fe32169139e28cfe545c70e783a06558
Please check last nightly version of OsmAnd

**Comment by sonora** [comment]
Appears to work again, thank you! Will do some more testing.
