### ISSUE TITLE
Center map without increasing zoom factor

### ISSUE THREAD

**Issue by MichaelZ4714** [osmandapp/OsmAnd#20535]
### Describe the idea (required)

The button on the bottom, second from right, centers the map and activates moving map. But it has a bad side effect: it changes the zoom to a very high value. It would be much, much better to keep the present zoom. For people that want the present behaviour, a long touch of the button could center the map, activate moving map and increase zoom as it is default now.

### Tell us about the expected behaviour (required)

see above

### Tell us about alternatives you've considered (required)

Changing the zoom with two finger swipe doesn't help since you loose the center and moving map. Using the - button multiple times is very inconvenient, eg. when you are on a bicycle ride.

**Comment by PekeTim** [comment]
This is really annoying for me too. But I noticed that the zoom level only changes to the fix level of 200 m if you're on a bigger scale (e.g. 2 km). Not if you're for example at 50 m....
I would really appreciate if the zoom level will not alter when pressing "My Position" button...
