### ISSUE TITLE
Weather layer alpha slider don't change it immidietely

### ISSUE THREAD

**Issue by nnngrach** [osmandapp/OsmAnd#20533]
### Description

video: 

https://github.com/user-attachments/assets/be7a982a-6e9a-422a-9554-5c469b52de0e

### Steps to reproduce

1. Configure map -> Weather -> Temperature
2. Turn layer on
3. Change Transparency slider position

### Actual result

Weather only blinks, but layer alpha doesn't change at all for tiles on the screen. Only new loaded tiles (after map moving) will have new alpha value.

### Expected result

Weather layer alpha changes immediately for tiles on the screen

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: Nightly 4.9.0#2939m, released 20204-08-07
Android/iOS version: Android 9
Device model: Samsung Galaxy S10
Crash-Logs: ?
```

**Comment by nnngrach** [comment]
This code can fix the problem, but I don't sure if this is a correct way.

<img width="791" alt="Screenshot 2024-08-07 at 22 55 53" src="https://github.com/user-attachments/assets/fc5692fc-1dd4-4f43-8109-139b55088d5e">

**Comment by DmitryAlexei** [comment]
reproduced on Samsung galaxy note 20 Android 13 OsmAnd~ 4.9.0#2932m, released: 2024-08-07

https://github.com/user-attachments/assets/26355b76-7384-4640-94a1-b679f6e9bb3d

**Comment by vshcherb** [comment]
Cache needs to be cleared after transparency changed

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.9.0#3024m, released: 2024-08-19
Works very slow on my device

https://github.com/user-attachments/assets/65eb9f9d-c195-4bbd-bdd4-9796ddffd363

**Comment by dmpr0** [comment]
# Review 

<table style="width:100%">
  <tr>
    <th>21%?</th>
    <th>20%?</th>
    <th>Video</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/55d36885-93ac-4036-a952-eaecfe04aa67"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/3340396b-04af-470b-863c-9f43cd47f380"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/user-attachments/assets/41880b12-8435-4615-83e9-b260f4306d74"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] Slider updates with the lag

**Comment by dmpr0** [comment]
# Review 2 

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src=""  width="300" height="auto"/> </td>
    <td><img src=""  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
Previous https://github.com/osmandapp/OsmAnd/pull/21040 was reverted, no decision was made and new bug introduced

**Comment by vshcherb** [comment]
- [ ] Slider should apply immediately to settings and to values on UI
- [ ] Progress bar should be shown until changes are not applied on UI preview (until all calculations are finished)
