### ISSUE TITLE
Selecting tree object does not show POI details 

### ISSUE THREAD

**Issue by milindoka** [osmandapp/OsmAnd#20537]
### Description

Tree tag ( natural=tree ) can be added with long press - Actions - Create POI - UPLOAD . After updating the tree icon 🌴 is displayed but if this tree object is selected like other tags,it shows an action popup as location as if there is no POI and you are creating a new one. 

The dialog should displayed with proper title tree. 

For example tapping on bench object, the dialog shows bench as title

### Steps to reproduce

1 Create tree POI with long press - Action - Create POI - POI type Tree - Upload.
2. Wait till the map updates and tree icon is shown 
3.  Try to select the tree by tapping on it.

### Actual result

The dialog shows locaton without title as if there is no POI at this location 

### Expected result

Tree object should get marked and Action dialogue should be shown  with title tree,

(As an additional feature species:en or species tag ,
if present, can be clubbed with 'tree' in the title and displayed on map like other POI's)

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd~ 4.7.17
Android/iOS version:12
Device model: samsung galaxy M11
Crash-Logs: ? None
```

**Comment by yuriiurshuliak** [comment]
Please clarify is the benefit of having each tree marked? Provide the coordinates of a specific object that you would like to see marked?

Also note that each tree object is unlabeled, as this is most likely expected behavior.

**Comment by vshcherb** [comment]
Only POI objects have additional information, tree is not poi object. Probably if it has specific name it could be in future

**Comment by milindoka** [comment]
Bench also has no label. When we select bench to add-modify tags, the popup bar notifies the contributor that the desired object is ready for modification. Tree also has no label and the same notification with title tree with tree icon is expected here to assure the user-contributor that desired object is tapped and not another closer object. The notification for tree is same as if empty location is long-pressed. Pl compare all  three images. Hope they will clarify my point.
![osmand-Tree Selected](https://github.com/user-attachments/assets/9919520c-94ab-4901-887e-5e9075356d07)
![osmand-Blank location](https://github.com/user-attachments/assets/c8005cf5-6f97-40c7-9e1d-ea26422efd1f)
![osmand-Bench selected](https://github.com/user-attachments/assets/dd231be8-a447-4df0-bbb6-a333da460e06)
