### ISSUE TITLE
Hiking/trekking icon is missing (as are others)

### ISSUE THREAD

**Issue by gpsvisualizer** [osmandapp/OsmAnd#20538]
### Description

Recently, OsmAnd vastly expanded the icons available for Favorites.  However, the "hiking" icon is no longer available, which seems like an odd omission.

In the favorites.gpx file, this icon's code is **special_trekking**.  Please bring it back!

And while you're at it, **special_camper** and **special_wagon** were also useful. Why get rid of them?

### Your Environment (required)

OsmAnd Version: 4.8.5
Android/iOS version: Android 12
Device model: Google Pixel 4a

**Comment by vshcherb** [comment]
We need to create special group "Activities" which will be perfect for these icons

**Comment by gpsvisualizer** [comment]
> We need to create special group "Activities" which will be perfect for these icons

I think the hiking/trekking icon could probably go in "Sport", and the camper and wagon could be in either "Tourism" or "Transportation".

**Comment by vshcherb** [comment]
Sport is a group that represents OSM POIs so that's why it's limited and doesn't display custom icons

**Comment by Boothy99** [comment]
Wish I'd spotted this earlier !!! I've just gone partially blind after scanning every icon in the list trying to find my favourite li'll "hinking with a stick" icon. Looking forward to getting it back 👍

**Comment by vshcherb** [comment]
To do:
- [ ] Move activity icons from ic_... to mx_...
Developers:
- [ ] In activities.json use mx_ icons
- [ ] Create special group "Activities" in UI which will use icons from (https://github.com/osmandapp/OsmAnd-resources/edit/master/poi/activities.json)

**Comment by dmpr0** [comment]
Icon https://github.com/osmandapp/OsmAnd-resources/pull/1147
