### ISSUE TITLE
"Transparent skin" option can't turn off transparency

### ISSUE THREAD

**Issue by enomat** [osmandapp/Osmand#2054]
Configure screen -> Transparent skin
If I disable transparency, it changes the transparency only for the top-right buttons. Nothing else changes. Most of the buttons stay transparent. Moreover, all buttons remain transparent in night map mode.

How it should work:
If the Transparent skin option is unticked/disabled, it should completely remove the transparency of all buttons, including the buttons in night map mode.

**Comment by vshcherb** [comment]
As it is designed, transparency skin related only to widgets.

**Comment by enomat** [comment]
@vshcherb 
If it only changes the top-right buttons, then the "Configure screen -> Transparent skin" option is misleading and confusing. It does not do what it suggests. It suggests that the user can completely disable the transparency of the skin, not only for some buttons and only in day map mode.
So the option is misleading.

(If you want to keep this behaviour, another solution is to add another option that turns off the transparency of all buttons. This would improve the customizability of the UI.)

The transparent skin is annoying, because often the transparent buttons blend into the background/map and hard to distinguish them. This problem is more pronounced in night map mode.

**Comment by sonora** [comment]
I also cannot see how this is a big issue. I have now changed the wording of this menu item to "Transparent widgets", I guess this avoids any confusion about what exactly is meant by "skin" in tis context.
