### ISSUE TITLE
Refugee sites are categorized as "Tourism"

### ISSUE THREAD

**Issue by davidkopp** [osmandapp/OsmAnd#20546]
OsmAnd shows "Tourism" as the category for refugee sites. Phrasing refugees as tourists is problematic and insensitive.

I assume that if the `amenity` attribute is set to `refugee_site` OsmAnd shows "Tourism" as the category.

Example:

<img src="https://github.com/user-attachments/assets/7e8d8ec2-35b0-4ceb-8606-23a54d3c3f6e" width="300">

Refugee site
Voithstraße (Malmsheim) 10, Renningen
Location: geo:48.78170,8.89868?z=18https://osmand.net/map?pin=48.78170,8.89868#18/48.78170/8.89868

**Comment by yuriiurshuliak** [comment]
The bug has been successfully reproduced. To observe it, go to the provided coordinates and click on the POI.

You will see that the Refugee site is incorrectly categorized under Tourism.

Here’s a link to the OSM node: https://www.openstreetmap.org/node/10740793216.

OsmAnd~ 4.9.0#2935m, released: 2024-08-08

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/04e2418e-0457-4ee4-a5a4-ee95c9a73f0c"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by xmd5a2** [comment]
Refugee sites were moved to "service" POI category. Updated Stuttgart map will be available today.
