### ISSUE TITLE
Allow to disable navigation button

### ISSUE THREAD

**Issue by luigifab** [osmandapp/OsmAnd#20561]
### Describe the idea (required)

Could you add the possibility to hide the button on map?

Mainly because I don't use it, secondly, because navigation is a straight line for me.

### Tell us about the expected behaviour (required)

Hide the button.

### Tell us about alternatives you've considered (required)

Option not found.

**Comment by DmitryAlexei** [comment]
Have you tried Fullscreen mode?
Go to menu > settings > your profile > general settings > Fullscreen mode?
After a tap on the map, all the buttons and widgets disappear.

**Comment by vshcherb** [comment]
We plan to allow customize standard buttons in 4.9

**Comment by rogercreagh** [comment]
I'd really like this. I never use navigation and would like to disable it completely - it just gets in the way.
I'd also like to disable the tap the map to drop a pin and look up the address - that is really frustrating when you are trying to move the screen around especially when outdoors and taps are not clear.
And a third thing is to turn off the pinky/light purple dotted lines that I think must be parish boundaries but look like footpaths. They ate really really confusing and totally unnecessary unless you specifically need to see minor adminisyrative boundaries

**Comment by vshcherb** [comment]
Implemented in 4.9

**Comment by auxbuss** [comment]
Any idea when this is coming to iOS?
