### ISSUE TITLE
Track recording notification

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#20571]
### Description

When closing the application, the notification about the track recording remains in the status bar.

### Steps to reproduce

1. Open osmand.
2. Close osmand.

### Actual result

When closing the application, the notification about the track recording remains in the status bar.

### Expected result

Hide notification when app closes.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd~ 4.9.0#2947m, Дата выпуска: 2024-08-10
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by thuryn** [comment]
I have the same problem

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.9.0#2946m, released: 2024-08-10
- I recorded and saved a track 11.08.24
- 12.08.24 I still have a notification, informing that track recording is paused (actually my track was already saved)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/33cb5f8e-985a-4d50-8251-ce6e445a5e65"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
Need to be retested after issue https://github.com/osmandapp/OsmAnd/issues/20536 been fixed

**Comment by vshcherb** [comment]
We can't remove notification as we don't application is closed. There is a setting to control it.

**Comment by DmitryAlexei** [comment]
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/c921be00-cab6-4de2-9367-170616bd5d98"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Nine-Tailed** [comment]
I know about the option to disable the notification. But I wonder why in 4.7.17 when closing the application the notification disappeared, but now it doesn't and you have to remove it manually. Isn't this a bug?

**Comment by thuryn** [comment]
I have two comments to this:
1) I've tried to switch the notification off, but it still there.
2) it happens several times before - there is some feature which works fine, you change it and it stops to work and when bug is open you claim that this is not a bug but fetaure. Notification icon works perfectly as one can expect. It works wierd now - it's not a feature but bug
