### ISSUE TITLE
ATM cash_in filter

### ISSUE THREAD

**Issue by Riksu9000** [osmandapp/OsmAnd#20574]
### Describe the idea (required)

Hi. Having the option to find ATMs that allow depositing cash would be very useful. There are lots of ATMs, but few that accept cash in.

### Tell us about the expected behaviour (required)

In the filter screen there would be a checkbox for only showing ATMs with [cash_in](https://wiki.openstreetmap.org/wiki/Key:cash_in)=yes.

### Tell us about alternatives you've considered (required)

There is a payment type filter with lots of random options, including coins and cash, but this tag is not really meant or used for ATMs AFAICT.

**Comment by xmd5a2** [comment]
Fixed

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.9.0#3122m, released: 2024-09-03
49.611830 6.126790
Android version: works fine in POI context menu and in Categories search

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/557495cb-56ff-43f0-9a71-d2fa856e5182"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/user-attachments/assets/4b0f8647-9a98-4dd7-9c5e-678a4ad159cc"  width="300" height="auto"/> </td>
  </tr>
</table>

TestFlight 4.8.3.0 works fine in Categories Search. Search for cash_in=yes through the POI Context menu is slow and shows street names instead of ATMs (ATMs are only shown for a brief moment).

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/d6a8784a-0f8b-4a03-b6dc-549219731a09"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/user-attachments/assets/ad287571-b8f1-4c9b-8622-fc39678c4eec"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by dmpr0** [comment]
# Review 

- [ ] Todo is missing

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/4019

**Comment by DmitryAlexei** [comment]
Fixed
Now the list of ATMs are identical for iOS and Android
49.611830 6.126790

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/dada0db7-6398-4c39-b5ad-aa63794d88e6"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/eef7c1f2-e310-440e-9b3d-af6615301c70"  width="300" height="auto"/> </td>
  </tr>
</table>
