### ISSUE TITLE
Attach to roads for BRouter navigation

### ISSUE THREAD

**Issue by Pick-Nick10** [osmandapp/OsmAnd#20570]
### Describe the idea (required)

It would be nice if routes generated when using the offline navigation type of 'BRouter' were able to use the attach to road function. As it currently is I get a lot of "Turn slightly left" "Turn slightly right" on curved roads, and no street names for turns.

### Tell us about the expected behaviour (required)

The expected behavior would be routes generated using the offline android Brouter app making use of the existing attach to roads feature.

### Tell us about alternatives you've considered (required)

Using the build in navigation settings

**Comment by scaidermern** [comment]
Related to #15139

**Comment by vshcherb** [comment]
Merging to online / 3rd party routing issue
