### ISSUE TITLE
Feature request: Add the "diet:" osm tag to POI search for vegetarian and vegan users

### ISSUE THREAD

**Issue by Guylby** [osmandapp/OsmAnd#20583]
### Describe the idea

Hi,

When searching for restaurants, the osm tag "cuisine:" adds in Osmand a clickable search that shows all other restaurants sharing the same "cuisine:" tag
Would it be possible to do the same for the "diet:" tag? It is especially useful as it shows the vegetarian and vegan options. This way, you would be able to search for all other vegetarians or vegan restaurant near you, the same as with the "cuisine:" tag
~As it stands, I didn't find any way to search for vegetarian restaurants in Osmand~
Edit: vegetarian or diet options are already searchable via the "diet" search or the localized type of diet (ex: searching for "vegetarian" directly)

Here is an example of a vegan restaurant: as you can see, the diet:vegan is shown but is not clickable or searchable, as can be the cuisine:burger tag. 
<img src=https://github.com/user-attachments/assets/13235094-2a13-4187-bf49-826a425a8663 width="50%">

### Expected behaviour

Osmand add a clickable POI search based on the "diet:" tag, and behaves the same as the "cuisine:" tag

### Alternatives you've considered

No real alternatives have been found

**Comment by scaidermern** [comment]
You can already search for vegetarian and vegan diets via the search function and the filter menu. However, being able to tap on these things to start a search would be very nice.

**Comment by Guylby** [comment]
Oh wow I was always searching for "Restaurant vegetarian" and didn't even try other searches, no wonder it came up empty everytime...
For sure if you search for the osm tag "diet" or just type "vegetarian" (or the localization depending on the app language) all nearby vegetarians options can be shown on the map
Thanks for the tip!

**Comment by scaidermern** [comment]
Actually I was referring to the filter function (the filter icon in the top right after you searched for something). But good to know that searching for vegetarian also works :)

**Comment by Guylby** [comment]
Didn't even know this filter search window... When you think you have a good understanding of the app you just find new features and functions you didn't even know existed or were already in the app

**Comment by vshcherb** [comment]
To do: make Vegan clickable and open search filter

**Comment by vshcherb** [comment]
![telegram-cloud-photo-size-2-5321034347815492866-y](https://github.com/user-attachments/assets/3412f758-e3db-4c0b-826b-3cc2735dfc02)
combine diet as dish

**Comment by xmd5a2** [comment]
Fixed. Duplicate lines (like Vegan, Vegetarian on your screenshot) will be removed with new maps generation but filter like cuisine doesn't require new maps.

**Comment by Guylby** [comment]
tested on 4.9.0, works like a charm, thanks!
