### ISSUE TITLE
Offline Routing: fastest route vs. shortest

### ISSUE THREAD

**Issue by pl71** [osmandapp/Osmand#2058]
Recently I had the following route calculated (ver. 2.2.3) - first screenshot.
Which looks strange since I had to make a big detour back. So I checked 'shortest' option and indeed shortest route was pretty acceptable. What was strange - shortest way was much more faster, than the other - 4:35 min vs. 8:06 min. But OsmAnd still offers the second route as the fastest.

![screenshot_2015-12-14-09-08-35](https://cloud.githubusercontent.com/assets/4776779/11782292/dfeaf876-a278-11e5-9b54-ac40edad356f.png)
![screenshot_2015-12-14-09-08-39](https://cloud.githubusercontent.com/assets/4776779/11782381/5fc5f942-a279-11e5-8097-d18529168924.png)

As per OpenRouteService [the second option is shortest and fastest] (http://bit.ly/1NZzMTU).

**Comment by hakuchi** [comment]
is it allowed to make a u-turn in this crossings?

**Comment by pl71** [comment]
Yes, at both crossings U-turns are allowed. As I said, shortest route is the fastest also (and in every other respect preferable), but the first option is still offered when **Shortest way** is unchecked.

**Comment by OpenSourceForEver** [comment]
The same case in: https://github.com/osmandapp/Osmand/issues/1704

**Comment by xmd5a2** [comment]
Tested this case with current maps.
1)This is a default route
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot_2016-01-25-21-02-34.png
2)Shortest
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot_2016-01-25-21-01-13.png

**Comment by vshcherb** [comment]
I guess this issue is not reproducible any more
