### ISSUE TITLE
Automatic 3D view when starting navigation.

### ISSUE THREAD

**Issue by raleik-pl** [osmandapp/OsmAnd#20605]
### Describe the idea

Right now, it is only possible to manually change the view 2D<>3D, either with a button, or with two-finger up-down swipe.

### Expected behaviour

It would be nice to have an option to automatically switch to 3D view when starting navigation and back to 2D view when browsing the map. This is what all other apps (I'm aware of) do.

### Alternatives you've considered

there aren't any

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/20606
