### ISSUE TITLE
Compass is broken on current Moto G

### ISSUE THREAD

**Issue by mbethke** [osmandapp/Osmand#2060]
Osmand seems to be affected by the same Android "feature" [mentioned and fixed here for CGeo](https://github.com/cgeo/cgeo/issues/5250): the compass hasn't been working since the last sytem update on the Moto G. The long explanation is [here](https://github.com/cgeo/cgeo/pull/5265); essentially the system update breaks the Rotation Vector sensor, however one can use the Magnetic Field and Accelerometer sensors to rovide the same functionality.

**Comment by vshcherb** [comment]
Please try Magnetic Sensor in OsmAnd Development Settings.
