### ISSUE TITLE
Red lines

### ISSUE THREAD

**Issue by max69dm** [osmandapp/OsmAnd#20609]
### Description

Every now and then there is the presence of these very annoying red lines 

### Steps to reproduce

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/3e164277-7106-4e3b-9525-46676707d9de"  width="300" height="auto"/> </td>
  </tr>
</table>   

### Actual result

Presence of red lines 

### Expected result

Who no longer present themselves

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by dmpr0** [comment]
Hi! 
Probably it could be weather contour lines, please check if they enabled in Menu – Configure Map – Weather – Contour lines.

**Comment by max69dm** [comment]
Ciao
Ho tolto l'opzione come mi hai detto....ci aggiorniamo nei prossimi gg
Grazie e Buon ferragosto

Il Gio 15 Ago 2024, 09:25 Dmytro Prodchenko ***@***.***> ha
scritto:
