### ISSUE TITLE
Issue with 'configure map' - 'hiking symbol overlay'

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/Osmand#2061]
If you set hiking symbol overlay to other than 'disabled' it will show 'standard' instead of 'disabled'. 
See screenshot 
![img_20151215_092533](https://cloud.githubusercontent.com/assets/11144987/11805716/6119cfea-a30e-11e5-9cc5-d0e2ded87809.jpg)
If you close the menu and go back, it is right labeled with 'disabled' 
#14900M

Getting Simon

**Comment by xmd5a2** [comment]
Seems that bug was fixed after release. Can't reproduce anymore but some time ago I was able to do it and not only with hiking symbol overlay.

**Comment by jf-simon** [comment]
I can produce it in #14929
