### ISSUE TITLE
Duplicate renderings when using online tiles

### ISSUE THREAD

**Issue by schubeda** [osmandapp/OsmAnd#20613]
### Description

When using the osmand online tiles, I get some additional things (names, symbols like bus stops, ...) shown on top, which are just redundant and hide information from the online tiles.

I have used osmand for a long time, this never ocurred to me. Now it is already the second device in a short time.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/396def82-de6b-4117-84e1-2f4a780dd353"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/2c031ae3-9cbd-4a08-9964-025dc138bb64"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/f6dfbc7d-4161-46ee-b845-3ae3eee8a940"  width="300" height="auto"/> </td>
  </tr>
</table>

### Steps to reproduce

Choose osmand online tiles as map source while also having offline maps downloaded for the same place.

### Actual result

Duplicate information shown on top of online tiles

### Expected result

Only online tiles are shown

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.8.4
Android/iOS version: Android 14 (GrapheneOS)
Device model: Google Pixel 8a
Crash-Logs: ?
```

**Comment by scaidermern** [comment]
Duplicate of #20003?

**Comment by schubeda** [comment]
> Duplicate of #20003?

Looks pretty similar. I can't judge if the fix helps, but I'm happy to wait for the next release and close this for now.
