### ISSUE TITLE
Render unexpected EOF Nexus 5 Android V6.0.1 no map displayed

### ISSUE THREAD

**Issue by xplora1a** [osmandapp/Osmand#2062]
![screenshot_20151214-103428](https://cloud.githubusercontent.com/assets/1844128/11809646/3488e2ec-a320-11e5-94f4-0460afd6491c.png)
I am getting this error since I upgraded to Android V6.0.1

org.xmlpull.v1.XmlParserException: Unexpected EOF (position:START_TAG <poi_additional n='information_hikingmap'>@1967:22 in java.io.InputStreamReader@2a3b3df)

**Comment by xplora1a** [comment]
It seems that the file poi_types.xml was corrupted somehow, deleting the file restored rendering. Is there some way to restore this file? is it needed?

**Comment by jf-simon** [comment]
Here is mine, try it.
[Uploading poi_types.txt…]()


Rename it to poi_types.xml

**Comment by vshcherb** [comment]
We will check it, but I think reinstalling the app should help.
