### ISSUE TITLE
Wrong height number.

### ISSUE THREAD

**Issue by davidq1973** [osmandapp/OsmAnd#20625]
### Routing engine

- [X] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Bike, no rrstrictions
![image](https://github.com/user-attachments/assets/17df9587-2075-4878-bb64-7910bba48843)

Height is on location is 17 meters above sealevel the 62 on location do not make sence.

### Start and end points

Annabijnsstraat 21 Helmond
See picture

### Actual route

![image](https://github.com/user-attachments/assets/c218cb71-88a2-4d9c-ae4c-9f98ecc665b4)

### Expected route

Height on location 17 m

### Maps you used (online or offline)

- [ ] Offline maps offered within the OsmAnd app for download. 
- [ ] Online (tile / raster) maps 

### Your Environment

```
OsmAnd Version: 4.8.6
Android version: ?
Device model: S20

```

**Comment by mikehgentry** [comment]
Have you tried installing (/uninstalling) the 'World Altitude Correction' map?

**Comment by davidq1973** [comment]
Yes, thats it. Thanks!

Op za 17 aug. 2024 01:27 schreef mikehgentry ***@***.***>:

**Comment by davidq1973** [comment]
Downloading correction map solved the issue.
