### ISSUE TITLE
Tourism=attraction object with id 12059348539 is not found and not displayed in OSM AND (although visible in Organic Maps)

### ISSUE THREAD

**Issue by gitmuti** [osmandapp/OsmAnd#20629]
### Description

Hello,

the following tourism=attraction object with the node ID **12059348539** 
(see [https://www.openstreetmap.org/node/12059348539#map=19/50.11546/8.67275](https://www.openstreetmap.org/node/12059348539#map=19/50.11546/8.67275) )
and the name 
**Kandelaber** 
is not **found** and not displayed in _OSM AND_. However, it is displayed in _Organic Maps._

This heritage listed, worth seeing street lamp is not displayed as tourist object in _OSM AND_ even is not found if you search for it.

A picture of this street lamp can be found on the URL [https://www.kunst-im-oeffentlichen-raum-frankfurt.de/de/page205.html?id=75&stadtteil=9](https://www.kunst-im-oeffentlichen-raum-frankfurt.de/de/page205.html?id=75&stadtteil=9) 

My speculation about the reason why it is not shown in _OSM AND_: 
Perhaps because the object 
- is not found in OSM AND and 
- it's a street lamp?

My expectation is that the node #**12059348539** will be displayed in OSM AND.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/a3d16175-31aa-4d14-958d-48114c819405"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/6a6f1c30-68c3-427b-ae9f-af3bf99ce660"  width="300" height="auto"/> </th>
  </tr>
</table>

### Steps to reproduce

- Search in OSM AND for "Kandelaber Frankfurt am Main" or search for "Alte Oper Frankfurt am Main Opernplatz"  (way id 384153099 ). 
- In the second search look at the square in the southeast of the Alter Oper building about 30 m away.
- Optionally activate the attraction overlay

### Actual result

Kandelaber object ( node ID 12059348539 ) is not found and not shown.

### Expected result

Kandelaber object ( node ID 12059348539 ) is at least found when you search for it and is then shown, and optionally additionally marked as tourism attraction. 

### Your Environment (required)

Device : r9q
Brand : samsung
Manufacturer : samsung
Model : SM-G990B
Product : r9qxeea
Build : UP1A.231005.007.G990BXXS9GXF3
Version : 14
App Version : OsmAnd+
Apk Version : 4.8.6 4806

**Comment by Nine-Tailed** [comment]
osmand shows lanterns only when lighting is on in details. I don't remember if it was always like that

**Comment by vshcherb** [comment]
that's bug cause it's an tourism=attraction object as well

**Comment by xmd5a2** [comment]
Fixed. No new maps required.
