### ISSUE TITLE
Incorrect OsmAnd Routing Instructions

### ISSUE THREAD

**Issue by Sonwon1** [osmandapp/OsmAnd#20638]
### Description

Please see the attached file, at the very beginning. The route goes to the south however the routing has you take the north bound entry ramp and then do a U-turn to go south.

### Steps to reproduce

Load file and navigate.

### Actual result

The beginning of the route should go to the south however the routing has you take the north bound entry ramp and then do a U-turn to go south.

### Expected result

Route to south bound entry ramp.

### Your Environment (required)

Route: 
[Route shared via OsmAnd.txt](https://github.com/user-attachments/files/16650970/Route.shared.via.OsmAnd.txt)

Screenshot: 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/f953486b-019a-4857-ba76-4da3482568b9"  width="600" height="auto"/> </th>
  </tr>
</table>

```
OsmAnd Version: 4.8.6
Android: 13
Device model: Samsung SM-T575
Crash-Logs: None


```

**Comment by scaidermern** [comment]
Looks like a map data issue, not an OsmAnd issue: https://www.openstreetmap.org/way/18191413
There is no u-turn restriction at this intersection. The map data should be fixed. Also check other ramps nearby for the same issue.

**Comment by yuriiurshuliak** [comment]
The issue couldn't be reproduced. Based on the OSM routing mechanisms, the route calculation matches ours. The problem likely stems from the OSM data.

Here is a link to OSM: [OpenStreetMap Directions](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=46.01257%2C-92.92967%3B46.00171%2C-92.93637#map=16/46.01150/-92.93150).

Here is a link to the Web Version: [OsmAnd Web Version](https://test.osmand.net/map/navigate/?start=46.012565,-92.929673&end=46.001660,-92.936380&profile=car#16/46.0124/-92.9348).

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/76bdcc47-b907-4dc1-a616-6d3f0fe590ed"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/dd303e75-3a38-4f35-8a6e-d305c7efc44d"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Sonwon1** [comment]
Okay
