### ISSUE TITLE
Keep information for tunnel=avalanche_protector

### ISSUE THREAD

**Issue by hhornburg** [osmandapp/OsmAnd#20637]
### Describe the idea

For cyclists in the mountains it can make a big difference if you have to ride alongside cars in a closed tunnel (very noisy and tight if they try to overtake) or in an avalanche protector (still very tight, but at least not that noisy). It would thus be nice to differentiate the two in renderings.

### Expected behaviour

Do not convert away `tunnel=avalanche_protector` to `tunnel=yes` in [rendering_types.xml](https://github.com/osmandapp/OsmAnd-resources/blob/a6227f36f27fcd7b9947665712712105046e73ad/obf_creation/rendering_types.xml#L725)

### Alternatives you've considered

Set both tags in [rendering_types.xml](https://github.com/osmandapp/OsmAnd-resources/blob/a6227f36f27fcd7b9947665712712105046e73ad/obf_creation/rendering_types.xml#L725):
`<entity_convert pattern="tag_transform" from_tag="tunnel" from_value="avalanche_protector" to_tag1="tunnel" to_value1="yes" to_tag2="tunnel" to_value2="avalanche_protector" routing="no" poi="no"/>`

**Comment by xmd5a2** [comment]
New tag **osmand_avalanche_protector=yes** was added to such tunnels. Now it is possible to render them differently in custom rendering styles.
