### ISSUE TITLE
Offline routing stalls during generation

### ISSUE THREAD

**Issue by myfta** [osmandapp/OsmAnd#20655]
### Description

Using the standard OsmAnd profile "Cycling" the app (Android) stalls soon after it starts, at about 20% complete. 

### Steps to reproduce

Select 'Cycling' profile.
Navigation
Enter From
Enter To

### Actual result

Never completes routing.
The same destination run on a different profile e.g. 'Walking' does complete as expected.

### Expected result

Tracked route from start to destination. 

### Your Environment (required)

```
OsmAnd Version: 4.8.6
Android/iOS version: 11
Device model: Moto G10
Crash-Logs: No
```

**Comment by yuriiurshuliak** [comment]
Please provide the exact coordinates for both the start and finish points, along with the settings of your profile where this issue occurs. You can export your profile settings by going to Menu → Settings → Export, and then selecting the data you wish to export.

Additionally, it would be helpful if you could attach a video demonstrating the issue.

**Comment by myfta** [comment]
I will have to close this, as today it is working correctly!
