### ISSUE TITLE
Regression: New track analysis graph is missing speed data

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#20656]
Probably a result of https://github.com/osmandapp/OsmAnd/issues/18204:
- There is no orange (speed) curve on any of my recorded track's context menu graphs
- The speed value the movable marker on the graph displays is bogus (always numerically the same as the elevation, it seems)
- Have not checked if the red speed curve (for tracks which have no speed values but time stamp values facilitating a speed estimate) is also affected.

**Comment by dmpr0** [comment]
I have empty speed graph on my tracks too, probably after this task https://github.com/osmandapp/OsmAnd/issues/17937

**Comment by sonora** [comment]
@0xRe1nk0 Seems to fix it by my testing. Thank you!
