### ISSUE TITLE
Voice that indicates warning without direction

### ISSUE THREAD

**Issue by adrien-github** [osmandapp/Osmand#2065]
Hi,

I used to drive on long way (900km). It's always the same road, so I know it quite well, I don't need directions.

But it is very useful to have the voice indications : speed limits, pedestrian crossing, speed camera, etc.

Could it be possible to have only the indication without the directions ? For now it seems not to be possible.

Thanks for this nice app!

Adrien

**Comment by vshcherb** [comment]
Closed, because it is already implemented. You can just change the app mode to the car and you will see most of that functionality (speed cams, max speed).

**Comment by sonora** [comment]
I am not 100% sure, but if it does not work for you, you may have to try this:

Start a brief, arbitrary navigation with voice guidance, then you can immediately stop it again (using the X button). This will initialize the (tts engine) voice prompts, and subsequently all warnings etc. will be announced, even if you do not have an active navigation any more. 

I also think this works in any profile like map browsing then.

**Comment by adrien-github** [comment]
Hi,

Thanks for the answers. With your method (start direction and then stop it) it works perfectly.
Sorry for the noise…

Kind regards

Adrien

**Comment by pl71** [comment]
I'm wandering why I still receive voice warnings after arrival at the destination. I do not need them any more.
