### ISSUE TITLE
Widget context menu missing for radius ruler widget

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#20654]
### Description

When you long press on the radius ruler widget, the context menu does not appear.

### Steps to reproduce

Long press on the radius ruler widget.

### Actual result

Nothing happens.

### Expected result

A context menu should appear

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd~ 4.9.0#3035m, Дата выпуска: 2024-08-20
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce it, you'll need the latest nightly version, which includes the new context menu function for widgets. Enable the Radius Ruler widget and attempt a long press on it.

The context menu for this widget will not appear, even though this option is already available for other widgets.

OsmAnd~ 4.9.0#3041m, released: 2024-08-21

https://github.com/user-attachments/assets/9a3a9528-0d5b-4361-aa41-9b82e80ea626
