### ISSUE TITLE
NB: POI/note - zoom when click on name

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#2066]
While navigating (in Landscape mode), I usually create notes along the way. 
After the recording stops, a note/POI menu shows from the left side.

Some builds ago, tapping the POI/note name would pan/zoom the map to the place where the POI/note is located.

In the current build, it doesn't zoom anymore. But if we immediatelly tap on the map area, then it instantly shows the POI/note location.

**Comment by vshcherb** [comment]
We added that behavior to help people discover extended map menu. 
On the other hand, after some usability testing, we think to add centering of POI on tapping of the marker itself.

**Comment by Barrocas** [comment]
The issue is that tapping the name works fine in portrait mode, it pans and
zooms to POI, but it doesn't do the same in landscape mode.

-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by crimean** [comment]
Fixed

**Comment by Barrocas** [comment]
Thanks! :)

-- 
Cumprimentos,
D.er Hugo Barrocas
