### ISSUE TITLE
NB: TTS voice fails

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#2067]
Setup a navigation, start navigating, and cancel it.
When starting navigation again, there are no voice announcements.
Sometimes it also happens after finishing navigation, and starting navigation again.

**Comment by gh88** [comment]
I experience the same problem. But this time it's with using "Pause" function. I reach my next waypoint, put app on pause and exit. Next time I start the app again - there is no sound... I have to kill it (using third party tools) and then start it again. Only after that I can hear voice announcements.

**Comment by Barrocas** [comment]
Yes, i also experienced the same, the  'pause' also had the same results in
my phone.

-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by sonora** [comment]
I cannot reproduce this. What version are you reporting this for?

**Comment by Barrocas** [comment]
I'm using latest night builds.
I also cannot reproduce it anymore.

>

-- 
Cumprimentos,
D.er Hugo Barrocas
