### ISSUE TITLE
Profile-specific custom buttons gone (regression from 4.7.10)

### ISSUE THREAD

**Issue by sbr61** [osmandapp/OsmAnd#20673]
### Description

Version 4.7.10 (F-Droid) introduced the feature of local custom buttons (with different quick actions per profile). This is gone with 4.7.17 and 4.8.x (F-Droid).

### Steps to reproduce

In version 4.7.10, under Configure screen/Custom buttons, configure a "Quick action" button in each profile, but add actions that are different in the various profiles. Then update to 4.7.10 or 4.8.x.

### Actual result

Except for the "Browse map" profile, the profile-specific actions are all lost. Instead, the "Browse map" actions are repeated in all other profiles. The same is true when re-importing settings exported with 4.7.10 into 4.7.17 or 4.8.x.

### Expected result

The profile-specific quick actions should have survived the update from 4.7.10 to 4.7.17/4.8.x.

This problem seems to be related to issue [19609](https://github.com/osmandapp/OsmAnd/issues/19609). But instead of adding a choice to apply a quick action change to other profiles, quick actions have been made global again in 4.7.17 (like they were in 4.6.x).

Why are different quick actions per profile important?

We can configure everything else per profile (even the UI). It would also make sense to make quick actions again profile-based. For instance, an action to show/hide filling stations and parking is helpful for the Driving profile, but not for the Walking profile. Conversely, an action to show/hide Cafe and restaurant, Sightseeing, Tourism, Wikipedia is helpful for the Walking profile (sightseeing mode), but not for the Driving profile. Another example is an action toggling between LightRS and OsmAnd maps in the Driving profile and one switching between Hiking, Topo, Offroad, and Outdoor explorer maps in a Hiking profile. I have lots of such differences in my 4.7.10 configuration.

Alternatives considered:

I could add as many global custom buttons as profiles are available (there are 13 default profiles in OsmAnd). For each of these buttons, I could add actions that make just sense for one profile. In each of the profiles, _all_ these buttons would be available in Configure screen/Custom buttons, but I could enable just one of them - that one with the actions meaningful for that profile.

Disadvantages:
- It looks quite cumbersome to have 13 custom buttons (with different actions) in 13 profiles, where just the right one is enabled but 12 others are disabled.
- In version 4.7.10, it is not possible to copy the profile-specific actions under different names to the "Browse map" profile in order to make them survive the update to 4.7.17/4.8.x. The only method to have them again after the update would be to make screen shots of the configuration in 4.7.10 and re-configure them as separate buttons in 4.7.17/4.8.x.

At the moment, I stick to version 4.7.10, hoping that you could resurrect the per-profile quick actions in 4.9. If not possible, I might accept the disadvantages later this year and re-configure everything in the cumbersome way.

### Your Environment (required)

```
OsmAnd Version: 4.7.17, 4.8.x
Android/iOS version: 14
Device model: Samsung Galaxy S23
```

**Comment by Nine-Tailed** [comment]
The buttons are the same for all profiles, but different buttons can be enabled in different profiles.

**Comment by vshcherb** [comment]
@Nine-Tailed gave a correct answer, so you can have different set of buttons and easier reuse buttons in different profiles

**Comment by sbr61** [comment]
I manually configured everything I had per profile in 4.7.10 as different buttons in 4.8.5 (which took me a couple of hours), so I can live with it now.

However, the user experience is somewhat inconsistent:

For other settings, a choice to save changes to all profiles is offered, which is convenient for people who want to share configurations between profiles. Additionally, a profile may offer to copy settings from another profile, which is convenient for creating a variant (by changing after copying). 4.7.10 tried to follow that method for custom buttons (just the choice to save to all profiles was missing).

With the current implementation, users who want different menus per profile end up with more than a screenful of custom buttons visible in _all_ profiles, where all but one (profile-specific) is being disabled. This is a different user experience than for all other settings.

**Comment by vshcherb** [comment]
>  4.8.5 (which took me a couple of hours),
Sorry to hear that

Yes it's now not attached to profile though you could still export it as 1 osf file including actions and profile you want.

The benefit we think most important that you can reuse same button in 2 profiles and don't need to configure twice - is very valuable

**Comment by sbr61** [comment]
I understand. That will be useful for sharing a button between all profiles and also allows to add an extra button for a specific profile only (disabled elsewhere). My use case with so much different buttons might be a bit special.

It is very helpful that we can actually have different buttons per profile. Thanks very much for that.
