### ISSUE TITLE
resort = kids_camp doesn't render

### ISSUE THREAD

**Issue by Velomeloman** [osmandapp/OsmAnd#20688]
Resort = kids_camp exist as category in search, but search results contain only leisure=summer camp. 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/021b5439-f579-4fe6-9557-81c71510be04"  width="300" height="auto"/> </th>
  </tr>
</table>

Also leisure = resort + resort = kids_camp doesn't render.

**Comment by yuriiurshuliak** [comment]
https://taginfo.openstreetmap.org/tags/resort=kids_camp#overview

**Comment by xmd5a2** [comment]
@Velomeloman I've found some errors in rendering_types.xml regarding kids_camp and fixed it. To work properly new maps required. moskovskaya-oblast will be updated today. Please test it and provide test instructions to our testing crew. It is not clear whether POI issues have been fixed or not.

**Comment by xmd5a2** [comment]
@Velomeloman done

**Comment by Velomeloman** [comment]
Works properly with new maps in Nightly, Google Play and Huawei versions.

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.9.0#3289m, released: 2024-09-26
55.92450,49.04454 
kids camp can be found via search and 
<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/c84d8449-714c-4e4b-b505-934d811c2cbb"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/38c63214-8c0d-415b-9801-481fc9854777"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/user-attachments/assets/87b84bc4-5b41-4ccb-bac2-6fc63ee514eb"  width="300" height="auto"/> </td>
  </tr>
</table>
