### ISSUE TITLE
GPX Extension Handling: Fix Using osmand:points_groups to Save File I/O

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#20695]
Consider a GPX file with many (I often have thousands) of `<wpt>` entries, all (or most) of which have no individual custom appearance tagging like
```
      <osmand:color>#ff5020</osmand:color>
      <osmand:background>circle</osmand:background>
      <osmand:icon>special_star</osmand:icon>
```
Instead in the end there is an OsmAnd points_groups extension specifying **`<wpt>` default appearance**, like
```
    <osmand:points_groups>
      <group name="XXX" color="#ff5020" icon="special_star" background="circle" />
    </osmand:points_groups>
```

### I notice that:
- [ ]  **(1)** Upon **importing such a file as favorites**,
 - Bug: OsmAnd does not correctly displays each `<wpt>` in their default or custom appearance, as applicable. Instead of using the points_groups default, it seems some app default is used (at least often).
 - Also: OsmAnd blows up its (favorites backup) file by adding **obsolete individual appearance extensions** to EVERY `<wpt>` section:
```
      <osmand:color>#ff5020</osmand:color>
      <osmand:background>circle</osmand:background>
      <osmand:icon>special_star</osmand:icon>
```
   - This increases file I/O unnecessarily, upon every read/write handling of the file. And: Having an `osmand:` custom extension section in every single `<wpt>` section instead of just one default one in the end makes the file unnecessarily inflated and clumsy when using it in other apps.

- [ ] **(2)** Bug: Upon **displaying such a file as a track**, the `points_groups` extensions seem completely ignored. Instead the track's wpts are displayed in some app default color and appearance. We should display each `<wpt>` without individual custom appearance tag using the corresponding  `points_groups` tag (similar to how the favorite import performs it, but without modifying the original GPX file).

- [ ] **(2a)** Bug: Looks like **importing such a file as track** even fails producing an error toast saying
`undefined prefix: osmand (position:START_TAG <(null)osmand:points_groups>@[line-no] in java.io.InputStreamReader@ff4d95)`

**Comment by vshcherb** [comment]
With bugs it's quite unclear probably it's a separate bug with importing.

```points_groups``` represent default appearance favorites not the actual, as favorites could be different than default appearance of the group. The optimization could be don't repeat if it's the same as points_groups

**Comment by sonora** [comment]
Yes, quite buggy. Item (1) may also have a bug, I only accidentally missed it.

The app **writes** the default appearance for each group to the `osmand:groups_points` extensions, but seems to ignore these upon reading, at least under some circumstances.

Instead of the desired order
- **individual `wpt` appearance tag:** _if present overwrites:_ **`points_groups` appearance tag:** _if present, overwrites:_ **app default**

it looks like the app often simply uses
- **individual `wpt` appearance tag:** _if present overwrites:_ **app default**

Not sure yet under what circumstances the app ignores the points_groups tags entirely and directly applies some other default. But it seems a bug worth fixing, or else our entire implementation of the `osmand:points_groups` extensions is flawed.

**Comment by sonora** [comment]
Something is really flaky here. It seems that even the option "_Change default appearance > Only apply to new favorites_" sometimes works, but sometimes also affects all existing ones.

I just re-discovered #19971, and think, all these issues are related, either some evasive bug, or even entirely missing code do do things as designed.

**Comment by vshcherb** [comment]
Yes we plan to fix it with https://github.com/osmandapp/OsmAnd/issues/19971 so it's a duplicate. 

UnWe probably think to redesign default appearance to add exceptions list to easier control it, same for tracks.
