### ISSUE TITLE
Proposed railways/railways in construction are visible in "Transport - tram and train routes"

### ISSUE THREAD

**Issue by ale-xy** [osmandapp/Osmand#2069]
In "Configure map":
"Transport" - "Tram and train routes" - enabled
"Hide" - "Hide proposed objects" - enabled

Tel Aviv light rail is shown in the same way as existing railways.
Examples:

http://www.openstreetmap.org/way/244188131 (proposed=light_rail, railway=proposed)
http://www.openstreetmap.org/way/357556279 (construction=light_rail, railway=proposed)

![device-2015-12-18-202001](https://cloud.githubusercontent.com/assets/7405393/11903880/06050430-a5c5-11e5-8b9a-2e332b3c1f34.png)

**Comment by xmd5a2** [comment]
Fixed. Fix will come with new maps.
