### ISSUE TITLE
Group translations for all POI types with `lang="true"`

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#20697]
## Description
We need to group into one line translations for all poi types that can have it, currently we do it for: name, alt name, old name.

* POI Types – https://github.com/osmandapp/OsmAnd-resources/blob/master/poi/poi_types.xml
* Example – https://www.openstreetmap.org/node/7140575085

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/222574e7-3e04-444f-8459-6a09b923e4f8"  width="300" height="auto"/> </td>
    <td><img src=""  width="300" height="auto"/> </td>
  </tr>
</table>   

## ToDo

- [x] Group translations
- [x] Use the same UI as for Name tag

**Comment by DmitryAlexei** [comment]
iOS task - https://github.com/osmandapp/OsmAnd-iOS/issues/3951

**Comment by nazar-kutz** [comment]
**Potential Future Tasks to Improve User Experience**

1. Some tags arrive without explicit localization. For example, a point may include three tags describing a brand: "brand", "brand:uk", "brand:en". Currently, the "brand" tag is displayed without specifying the locale associated with it. However, it’s generally accepted that tags without a locale should be assigned the locale of the country where the point is located. Therefore, we can link such non-localized tags to the current locale of the object to display it on the UI. For example, for points located on the Ukraine, display "Brand: Ukrainian", not "Brand".

2. Some points have more localized tags than what the app receives. For instance, the OSM website displays several localized versions of the "operator" tag for a specific point (https://www.openstreetmap.org/node/2343609267). However, OsmAnd only receives the general (non-localized) "operator" tag, while the others with extensions are lost somewhere. This might also need fixing.

3. We have a significant issue with dividers between items on the Context Menu. They disappears between some menu rows. This requires additional time for investigation and fixing, and it might need to be addressed as a separate task.

**Comment by vshcherb** [comment]
1. "Brand" should be translated as "Brand", later we can add "Local brand" if there are multiple
2. easy to fix by @xmd5a2 
3. have separate issue
