### ISSUE TITLE
track not shown on map when importing GPX file containing unjoined `trkseg`

### ISSUE THREAD

**Issue by monperrus** [osmandapp/OsmAnd#20696]
### Description

Import a GPX file, the track is not shown in OsmAnd

### Steps to reproduce

1. Open the file attached
2. Import as GPX
3. Double-check that the track is selected as "on map" on the "Tracks" config screen
[sport_1_2024_08_27_083447-1.gpx.txt](https://github.com/user-attachments/files/16759507/sport_1_2024_08_27_083447-1.gpx.txt)

### Actual result

Nothing is displayed on the map, the track is not shown,

### Expected result

The track is displayed on the map

### Your Environment (required)

OsmAnd 4.8.6

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. To reproduce, try importing the provided track. You may notice that the track does not appear on the map initially. However, if you go to the Track tab and toggle the "Join segments" slider after importing, the track will then be displayed on the map.

OsmAnd~ 4.6.0#868m, released: 2023-10-13


https://github.com/user-attachments/assets/2a6873ff-1792-4889-bd40-e50e52597b82

**Comment by 0709wiwiwi** [comment]
@monperrus 

_The problem is the import file does not apply the gpx standard.
So for optimization you better contact the creator zeblazefit_

1. The gpx file is not valid. 
Strict apps (Garmin) even so reject the file import as corrupt.

- According to the gpx standard: 
  http://www.topografix.com/GPX/1/1/#SchemaProperties

Bad.

```
<?xml version=“1.0” encoding=“UTF-8”?
<gpx version="1.1”
 creator=“zeblazefit”>

```
Good.
 
```
<?xml version=“1.0” encoding=“UTF-8” standalone=“no”?>
<gpx version="1.1”     
creator="GPX Editor 1.8.0.1760”     
xmlns="http://www.topografix.com/GPX/1/1”     
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance”     
xsi:schemaLocation=“http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd”>
```

2. The gpx track file structure is bad.

_Each track point within the original file is placed into a separate track segment. 
In an unbroken normal gpx track record, this is sure not the intention._

![image](https://github.com/user-attachments/assets/f869e3db-23fd-4a1b-a932-204c5bbdd7a3)

- A gpx track segment should be used according to the gpx standard as follows.
  http://www.topografix.com/GPX/1/1/#type_trksegType

_A new track segment is only started when the gps reception was interrupted.
A transparent line between track segments than prevents possible visual chaos._

Translated with DeepL.com (free version)

**Comment by monperrus** [comment]
Agree, thanks a lot @0709wiwiwi 

Closing the issue.

Thanks for the great app!
