### ISSUE TITLE
'Change default appearance' for track wpts is buggy

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#20705]
Aa a spin-off of #19971: The dialog '_Track context card > Points button > 3 dots > Change default appearance_' is faulty.

Instead of facilitating to change the default appearance of the wpt points in the very selected category of a GPX file, this opens a dialog titled '_Edit Category_', which in line 1 expects "Please use a category name which does not yet exist"(?!?)

Leaving that line empty creates a new (additional) 'group' line in the GPX file's points_groups tag, and eventually modifies all waypoits' type tags with a bogus value.

Creating the new group line is a bug. And in addition, all handling of appearance should probably happen in the db, without modifying the GPX file anyway.

**Comment by sonora** [comment]
To illustrate: This file [ITSF_initial.gpx.txt](https://github.com/user-attachments/files/16776862/ITSF_initial.gpx.txt) eventually became this file [ITSF_final.gpx.txt](https://github.com/user-attachments/files/16776805/ITSF_final.gpx.txt). Note how
- The `<type>` tag of the 4 `<wpt>` became modified to say `<type>special_star</type>` (the default icon name!)
- An extra line for an empty points_group name was introduced (line 54)
- This identical (and obsolete) code block was introduced to every `<wpt>` section:
```
    <extensions>
      <osmand:color>#8e2512</osmand:color>
      <osmand:background>circle</osmand:background>
      <osmand:icon>special_star</osmand:icon>
    </extensions>
```

**Comment by yuriiurshuliak** [comment]
@sonora Could you please provide the steps I should follow to reproduce the issue on my end?

**Comment by sonora** [comment]
@yuriiurshuliak Sure! I use a track like **ITSF_initial.gpx** (see above).

(Originally coming from a 3rd party source, and edited on a PC, to add
- `xmlns:osmand="https://osmand.net"` to the end of the gpx tag in line 2
- and add this code block to the end of the file before the `</gpx>` line,
```
  <extensions>
    <osmand:points_groups>
      <group name="IT_SlowFood_(PoiGPS.com)" color="#8e2512" icon="special_star" background="circle" />
    </osmand:points_groups>
  </extensions>
```
These 2 measures add an Osmand default appearance to the file, and this works fine when using the file as import to **favorites**.)

But I place the file in OsmAnd's 'tracks' folder, so it appears as a **track** under the "My Places" menu.

When you now (in OsmAnd) make it visible on the map, the waypoints do **not** appear in the default color specified in the file (code block above, which specifies a brownish red), but in some app default color (bright red in my case). I hence
- tap on one waypoint, 
- on its context card tap "Open Track"
- then on the track's context card tap the "Points" button
- then on the subsequent dialog select the 3-dots menu next to the Category and select "Change default appearance"

Simply accept the dialog's suggestion of the brownish/red appearance by tapping "Save", and subsequently "Apply to all Existing". This works to change the appearance. But go to the 'change default appearance' menu again, you will e.g. see that the "Category" has now been changed to "special_star" (and all the other side effects described above have been written to the GPX file).

**Comment by vshcherb** [comment]
That looks like "" group doesn't process correctly waypoints

**Comment by sonora** [comment]
@vshcherb Small typo, big effect... : https://github.com/osmandapp/OsmAnd/commit/9c0ec1a100c6da261d8e5e234428323881dac11d :wink:
