### ISSUE TITLE
Live updates screw up map

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/Osmand#2070]
Maps are Germany -> baden-württemberg
Live Updates are current.

![screenshot_2015-12-19-22-43-04](https://cloud.githubusercontent.com/assets/11144987/11915339/7585120e-a6a2-11e5-8b6d-3a53df7acdd7.png)

If i delete live updates I looks fine
![screenshot_2015-12-19-22-44-01](https://cloud.githubusercontent.com/assets/11144987/11915341/7f9f8a62-a6a2-11e5-85e1-ffe94100547e.png)

Greetings Simon

**Comment by Barrocas** [comment]
I could not see your pictures, but I have the same problem in Portugal,
LiveUpdates generate long straight diagonal lines that cut through the map,
and mess it up, sea vanishes, land areas get flooded, natural green areas
get distorted, etc.

-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by vshcherb** [comment]
Fixed. Tested turn restriction http://www.openstreetmap.org/relation/6104572.  New diffs require new maps and diffs could be found here http://builder.osmand.net/aosmc/

**Comment by vshcherb** [comment]
The comment related to another issue though it is also fixed.
