### ISSUE TITLE
"OsmAnd-resources/countries-info/regions.xml"

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#2071]
Sorry, but I do not  understand "OsmAnd-resources/countries-info/regions.xml". I want to change the name of some regions of spain that are shown when Display language is Spanish.

"Andalusia" in spanish is "Andalucía"
"Principallity of Asturias" in spanish is "Principado de Asturias"

**Comment by vshcherb** [comment]
I think it is taken from OSM, so please check admin-levels in OSM. More information could probably @xmd5a2  provide. 
https://github.com/osmandapp/OsmAnd-resources/blob/master/countries-info/regions.xml#L189
If you are talking here, it uses the value of translate to search for translations. OSM data may be outdated https://github.com/osmandapp/OsmAnd-misc/tree/master/osm-planet/osm-data, in that case scripts need to be rerun.

**Comment by xmd5a2** [comment]
At first look at region in regions.xml
```
	<region name="andalusia" hillshade="no" />
```
See "andalusia". Next: search OsmAnd-misc/osm-planet/osm-data/*.osm for "andalusia". By default translation (name or name:en) is taken from OSM from node type object. You'll find out that k="name:en" v="Andalusia" is found two times - states_places.osm contains  node id="949522007" and states_regions.osm contains   relation id="349044". In this case translation is taken from node. Then look for this node in OSM and change it using regular OSM editor. Then OsmAnd-misc/osm-planet/update-osm-all.sh script must be rerun (I do it manually time to time) and new regions.ocbf must be regenerated (I do it time to time too).
