### ISSUE TITLE
cycleway:both = lane incorrect render in touring view

### ISSUE THREAD

**Issue by Velomeloman** [osmandapp/OsmAnd#20721]
### Description

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/0ad54772-0c72-401b-9678-a90cc4c4d567"  width="300" height="auto"/> </th>
<th><img src="https://github.com/user-attachments/assets/1cb2a643-ca79-4360-a767-c21e1f90c8b3"  width="300" height="auto"/> </th>
  </tr>
</table>

In Touring view tag cycleway:both = lane renders with extra dash line in the center of highway. 

### Steps to reproduce

1. Bicycle profile
2. Map style - Touring view
3. Search 55.68597° N, 37.59358° E

### Actual result

Винокурова st tagged with
cycleway:both = lane has extra dash line in the center of highway.
Большая Черемушкинской st tagged with
cycleway=lane
cycleway:both=yes
renders correctly

### Expected result

cycleway:both = lane renders similarly as cycleway=lane
cycleway:both=yes

Also cycleway:left and cycleway:right 

### Your Environment (required)

```
OsmAnd~ 4.9.0#3096m, released: 2024-08-29 
```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce this issue, change the map style to "Touring view," select the cycling profile, and enable cycle routes. Then, navigate to these coordinates: 55.68597, 37.59358.

As a result, you'll notice an additional dashed line displayed in the center of the road. If you switch the map style back to the default OsmAnd, this line will no longer be visible.

OsmAnd~ 4.9.0#3104m, released: 2024-09-02

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/29788d82-5465-4a2c-8ced-bda503d7e2ea"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/3f49b39d-342c-4908-adff-4ba74e34df2a"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Velomeloman** [comment]
I tryed to find how fix it in [touring-view.render.xml](https://github.com/osmandapp/OsmAnd-resources/blob/master/rendering_styles/Touring-view_(more-contrast-and-details).render.xml#L1490), but all described cycleway tag combinations listed in one condition. I have no idea what to do. Also I can't find conditions for cycleway:left and cycleway:right tags.
 @sonora, can you help with this issue?

**Comment by sonora** [comment]
Probably it's this block, which may need (partially or entirely, not sure) disabling for the v2 engine:

		
		<switch>
			<case tag="cycleway" value="lane"/>
			<case tag="cycleway" value="track"/>
			<case tag="cycleway" value="opposite_lane"/>
			<case tag="cycleway" value="both"/>
			<case tag="cycleway:both" value="lane"/>
			<case tag="cycleway:both" value="track"/>
			<apply_if baseAppMode="bicycle" minzoom="14" color="$cyclewayColor" strokeWidth="2" pathEffect="8_4"/>
		</switch>


But I am not sure how to best resolve conflicts between the v1 and the v2 engine, would appreciate @xmd5a2 's advice and action on this...

**Comment by Velomeloman** [comment]
cycleway:left/right supported, but renders also incorrect 
![Screenshot_20240920_074922_net.osmand.plus.jpg](https://github.com/user-attachments/assets/b0570b32-2899-44c0-ba22-2c3f2f976e96)

**Comment by sonora** [comment]
Ok, thanks. Like I said, and I am not quite sure, I believe that the 'center line' is the workaround  for the old v1 render engine (think it does not support the proper positioning of the line), and it may require to be explicitly supressed when the user uses the v2 engine, to prevent both appearances to be shown together...

**Comment by Velomeloman** [comment]
![Screenshot_20240920_114918_net.osmand.plus.jpg](https://github.com/user-attachments/assets/90b6454a-50f4-4f75-b3e0-5ac6d90a37f7)
I just commented out this whole block and everything works fine. Even v1.

**Comment by sonora** [comment]
Ah, I guess we just overlapped. Yes, I think I have meanwhile fixed it, please test.

Discovered one other small glitch regarding coloring path's with bicycle=designated, will fix also.

**Comment by sonora** [comment]
I also see issues now with cycleway rendering, something seems to have changed vs.my Feb 28 build where things still look ok.... (v1 and v2 engine).
