### ISSUE TITLE
OsmAnd's routing engine favors bigger roads way too much

### ISSUE THREAD

**Issue by lucb1e** [osmandapp/Osmand#2072]
The old routing engine was next to prefect. The newer one, which is probably a year old by now (I don't remember) can often be improved. It tries to take bigger roads all the time, making the route simpler but going around where I need to be.

It's probably a good idea to prefer bigger roads, but not this much.

**Comment by sonora** [comment]
I have varying experience with this, but also have observed some situations where I would say we should systematically observe and evaluate this ...

**Comment by raindropsfromsky** [comment]
Yes, probably my observation fits here:
Suppose we expect OsmAnd to take a U-turn on a dual carraigeway road.

Logically, OsmAnd should use the closest link that joins the two carriageways.
But practically OsmAnd ignores any link that results from a lower-raking road crossing the dual carraigeway road.

For example, if we are on a primary dual carriageway road, and if a secondary road crosses the road **without** any turn restrictions at the junctions, this link is a good candidate for taking a U-turn. But OsmAnd ignores this lower-ranking cross-link. It will try to find a primary link that joins the carriageways; thus taking a far longer route unnecessarily.

**Comment by razor74** [comment]
Yes this problem is frecvent. I reported many times, but lately i didnt reporty this problem , because i fear they will destroy the entire routing again. In this moment the routing, generally is good enough.
PS: This software is old enough to have 3D vector rendering engine until now. But they "are stick in the mud" with basic function like routing...

**Comment by sonora** [comment]
Closing this one as it is very general with no specific input - we have issues elsewhere o tweak the routing.
