### ISSUE TITLE
4.9 Nightlies crash changing track colour attribute

### ISSUE THREAD

**Issue by albansuser** [osmandapp/OsmAnd#20724]
### Description

This bug, which crashes the app, was reported recently by email. It involves changing the colour attributes of a recorded track.

I have made further observations regarding the circumstances underwhich the crash occurs. 

The bug occurs starting with 4.9 nightlies a few days after the 15th August and continues until at least the 30th August.

### Steps to reproduce

Scenario 1 The track has the default colour (solid) attribute, that is, attribute not previously changed.

Attempting to change the track colour attribute to either speed, slope or altitude causes the app to crash.

Scenario 2 The track colour attribute has previously been changed to either speed, slope or altitude by a nightly compilation prior to the occurrence of the bug, for example 15th August. 

Attempt to change any track attribute by clicking the palette icon. The app will spontaneously crash.

### Actual result

OSMAnd crashes

### Expected result

Track colour attribute changes without issue.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd~ 4.9.0#3098m, released: 2024-08-30
Android/iOS version: 14 and 12
Device model: Samsung S22 and A70
Crash-Logs: ?
```

**Comment by sonora** [comment]
@Corwin-Kh  Class cast exception in new file: [exception.log.txt](https://github.com/user-attachments/files/16826301/exception.log.txt)

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce this issue, start recording a track, and after the recording is complete, attempt to change the Track Appearance to "speed."

As a result, the application crashes. Here are the corresponding crash logs: 
[exception (20).zip](https://github.com/user-attachments/files/16837446/exception.20.zip)

OsmAnd~ 4.9.0#3104m, released: 2024-09-02

https://github.com/user-attachments/assets/1a1d4275-2f93-4c63-a3bd-66a6983d997f

**Comment by albansuser** [comment]
I confirm the fix.

Thanks
