### ISSUE TITLE
To see edit points in Plan Route you need to zoom in too far to

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#20722]
### Todo
We need to  display editing points on the screen if there are < ~ 30-50 points. Here screenshots you see 4 points but I can't click on them cause they are not display. So I need to zoom in up to 5 m scale.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/e46bb32b-0627-4dcb-889b-806a232bae9c"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/848b3d10-0005-484f-9147-4d2df317b89e"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Chumva** [comment]
https://github.com/osmandapp/Osmand/blob/ddaf4e957f2c5da8465dc78c955b9616efe81f02/OsmAnd/src/net/osmand/plus/measurementtool/MeasurementToolLayer.java#L721
