### ISSUE TITLE
Downloaded maps are shown as available too.

### ISSUE THREAD

**Issue by Ratterkresch** [osmandapp/Osmand#2073]
Although the files/ maps are already downloaded (green areas), they are shown in the list of available files for an area:
![image](https://cloud.githubusercontent.com/assets/8234960/11927723/e6e7317a-a7ce-11e5-9aa2-033ab3f5b287.png)

It would be better to filter them and not to show up to date maps. Also to flag outdated ones, and offer an update button then instead of download.
So user can easily see when a map is missing or outdated only and decide the next step more effective.

**Comment by vshcherb** [comment]
I don't see the exact value of filtering out the maps, but indeed to not create confusion only maps are shown to update (not hillshade or wikipedia)

**Comment by Ratterkresch** [comment]
Well, let's say it in other words:
The feature to show, which maps are available in an area is more than nice.
In the map library you have already downloaded some and all of them have a time stamp.
What would reduce the confusion of the picture shown above?
Mark in different ways (e.g. colors or text such as new/update) whicht of those is already inside your library an which not.
Also mark, if one of those has an old time stamp OR do only show not downloaded ones (may be user can choose one of this two options in map management settings?).

**Comment by Barrocas** [comment]
Or in other simpler words (if I understood correctly), only show the ones
that are outdated or available for download.

If we already have them and are up-to-date, it's not necessary to show them
as available for download in the map screen.


-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by sonora** [comment]
Not showing them is also logically false, and will create other confusion like e.g. me on my device seeing them while a buddy on his device does not see them (if he already has them). The correct and consistent way to do it is to simply make their icon green (like we do with the map region), maybe in addition state the text "Up to date" where for the others we would put the Update or repectively Download button.

**Comment by sonora** [comment]
No action planned here, I guess.
