### ISSUE TITLE
Osmand gets killed by GPS Info / size: small

### ISSUE THREAD

**Issue by Hnfdorteebikio** [osmandapp/OsmAnd#20730]
### Description

I was on a trip, and I wanted to see the satellite status, but it was annoyingly large on the screen (big white bar), so I tried to made it smaller. That completely killed Osmand, and I was struggling to complete my trip without a navigation system.

### Steps to reproduce

I reproduced the issue several times at home then:

Osmand runs fine,
then I add GPS Info via Configure Screen / Top Panel / GPS Info / add
Osmand is still running.
Then I click the Gear icon right to "GPS Info", and change the Size from Medium to Small, click Apply,
and Osmand immediately crashes: it closes without any message or warning.

And I can not start Osmand again: if I try, the start screen logo appears for about 2 seconds, then it disappears, and I land back on my Android home screen. 
Something seems to run though, because in "Settings / Apps / Osmand~" I can "Force Stop" once every time after I tried to launch it.

When I "clear data" via "Settings / Apps / Osmand~ / Storage", it works again, but all settings, and much worse, all maps, are gone.
And as soon as I again add "GPS Info", and make it "small", it immediately crashes again.

- How can I reset only the configuration without deleting all the maps? By deleting some single file? Some xml or so? Which one? (Directory, file name)
- Can anyone reproduce the "GPS Info - Set to Small" - Crashing I observe?

Thanks!

### Actual result

Osmand crashes without any message.

### Expected result

Osmand does not crash.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
Osmand 4.8.5 via f-droid. No google play on my phone.
OS: LineageOS 14.1-20240521 (non-official), Android 7.1.2 with Kernel 3.10.100. Not rooted.
Phone: old Samsung SM-J320F with 1.5GB of RAM.
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. To replicate this bug, add the GPS Info widget to the top bar, start navigation, long-press the widget, select settings from the drop-down list, change the Size from Medium to Small, and click Apply.

As a result, the application does not crash, the widget reduces in size as expected, and navigation continues smoothly.

Please try using the release version from Google Play or test it on our beta version: https://osmand.net/docs/versions/nightly_versions.

OsmAnd~ 4.9.0#3104m, released: 2024-09-02

https://github.com/user-attachments/assets/b439165e-e197-4041-a8eb-e6b15956b381

**Comment by Hnfdorteebikio** [comment]
Thanks. OK, as I see on the screenshot above, even the "small" gps info widget is still way too large; I will anyway not use it then. In the past, I am very sure that there was some really small GPS info in the size like the distance, the time of arrival or the "REC" in the above screenshot, but I did not manage to find it in the current version... probably my bad, but I will not continue searching and experimenting as long as it makes the whole app unusable all the time and I have to re-install all the maps.

So the first question remains:

Is there a way to reset only the configuration about such widgets and stuff like that without deleting all the maps if one is not able to launch the app any more? By deleting some single file? Some xml or so? Which one? (Directory, file name)

**Comment by sonora** [comment]
@Hnfdorteebikio I have _Menu > Configure screen > Right panel > GPS Info_ checked, and have used that for years with no issues. Seems to work unaltered, also today. Are you saying not for you?

![Screenshot_20240903-092538_OsmAnd~](https://github.com/user-attachments/assets/3ff66bc9-15f0-452e-a112-cd63e2087142)

**Comment by Hnfdorteebikio** [comment]
Yes, thanks, that looks like the one I remember from my last install. But as long as I still do not know how to reset the settings without deleting all the maps if the app possibly again crashes all the time after I change any such setting, I really do not like to make any more attempts.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
The problem is much less that I do not see proper GPS info, but much, much more that there obviously always is the (in my case reproducible) risk of loosing the app and all offline map data while I am on a bicycle trip without internet connection.
