### ISSUE TITLE
Octagons on Quick buttons

### ISSUE THREAD

**Issue by Velomeloman** [osmandapp/OsmAnd#20749]
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/97d89dcf-ca67-41ea-8968-37a272f6b081"  width="300" height="auto"/> </th>
  </tr>
</table>

Some extra octagons displays in the not center of Custom buttons after adding ability to edit Appearance

**Comment by Nine-Tailed** [comment]
why even put it in a round button, it looks terrible

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. Please try updating to the latest nightly version and add some Quick action buttons.

After doing so, you’ll notice that extra octagons appear within the translucent buttons.

OsmAnd~ 4.9.0#3134m, released: 2024-09-06

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/8dd25d05-5bb1-480a-8f96-307531223655"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Nine-Tailed** [comment]
Some of the bugs have been fixed, but the compass button is too pale gray. And if you change the button's transparency, the polygon becomes visible again.
![Screenshot_2024-09-06-21-28-31-920_net.osmand.plus-edit.jpg](https://github.com/user-attachments/assets/453b6188-185a-49b4-b61f-342a75fc0f2e)

![Screenshot_2024-09-06-21-27-26-735_net.osmand.plus-edit.jpg](https://github.com/user-attachments/assets/a45a7ef7-6487-4fda-a79d-b797162cedc6)

**Comment by Nine-Tailed** [comment]
also, when you expand the application, the background of the buttons changes to a darker one for a while
https://github.com/user-attachments/assets/6514d7df-f5b2-4bc6-a742-6dd6e3bb5a1d
