### ISSUE TITLE
Moped disable  cycleways by default

### ISSUE THREAD

**Issue by mem76** [osmandapp/OsmAnd#20743]
### Description

OSMAND (both the app and the online map) routes moped on to cycleways, the default access for cycleways is no motor vehicles, this includes mofas and mopeds.

There are some countries that allows mofas and/or mopeds on cycleway, if this is the case the cycle-way should be tagged with `moped=yes` or OSMAND should have a geographical exeption for those countries.

### Steps to reproduce

Here is an example illegal routing.

https://osmand.net/map/navigate/?start=60.418556,5.313070&end=60.434727,5.315902&profile=moped#16/60.4258/5.3078

### Actual result

The moped is routed onto cycleways.

### Expected result

The routing should not use cycleway or sidewalks. It should use the trunk road but not though the tunnel, as this is tagged with moped=no.

### Your Environment (required)

```
OsmAnd Version: 4.8.6
Android version: -
Device model: -

```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce it, navigate to the specified coordinates and attempt to create a route using the moped profile.

You'll notice that in some sections, the navigation directs through bicycle lanes.

You can check it out in the web version here: https://test.osmand.net/map/navigate/?start=60.418556,5.313070&end=60.434727,5.315902&profile=moped#13/60.4239/5.2940

Alternatively, you can switch to the motorcycle profile or customize your routing by creating or modifying a routing.xml file. More details can be found here: https://osmand.net/docs/user/navigation/routing/osmand-routing/#customize-offline-routing

OsmAnd~ 4.9.0#3122m, released: 2024-09-03

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/8fcee87b-859c-47ce-9ef6-ec3c6a7b957a"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/2ae83dd6-2ce0-4e9e-bf40-d54d090f9d2e"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
As we have rising number of bicycles with engines which are definitely allowed on cycleways, it looks like moped restrictions are mostly related to combustion engines and maximum allowed speed. 

In most of real cases it's clear that moped won't be driving motorway and driving road next to motorway.

**Comment by mem76** [comment]
> As we have rising number of bicycles with engines which are definitely allowed on cycleways, it looks like moped restrictions are mostly related to combustion engines and maximum allowed speed.

Those are not mopeds, mopeds has, per Europe standards has a max speed of 45km/h. Electric assisted  bike-cycles have a max speed of 25km/h and is limited to 250W.

The classification of moped has nothing to do with if it is combustion or electric. 

> 
> In most of real cases it's clear that moped won't be driving motorway and driving road next to motorway.

In this case there is no motorway along the route, so that argument is null and void.

**Comment by mem76** [comment]
[vshcherb](https://github.com/vshcherb) 
> changed the title OSMAND routes motor-vehicles onto cycleways Moped allows to use default cycleways

wiki.openstreetmap.org
> Ways that are not marked as cycleway by traffic signs (and are therefore open to non-bicycle traffic (e.g., moped or horse) should typically be tagged as [highway](https://wiki.openstreetmap.org/wiki/Key:highway)=[path](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dpath) instead of [highway](https://wiki.openstreetmap.org/wiki/Key:highway)=cycleway,

So according to the community standards defined on the wiki mopeds do not have access to cycleway.

The list of singe track according to the access tag:

> Single-tracked
>
> * bicycle=* – cyclists
> * electric_bicycle=* – bike limited to a slow speed (e.g. 25 km/h). No licence plate or driving licence required
> * mtb=* – for rare cases where there are different legal access restrictions indicated for mountain bikes then for other types of bicycles (such as "access only allowed on mountain bikes" or "cycling allowed, but not on mountain bikes". For legal access restrictions that to apply to all types of bicycles use bicycle=*. To indicate practical (un)suitability for certain types of cycles / riders do not use mtb=* (a form of access=*), but tags as smoothness=* , mtb:scale=* or surface=*
> * cargo_bike=* – bikes used for transporting heavy or bulky loads
> * kick_scooter=* – Non-motorized vehicle to stand on with a handle bar. Accelerated by kicking.

**Comment by vshcherb** [comment]
As moped our fresh routing profile, we didn't run deep investigation yet regarding cycleway. Though you are right about wiki definition but we need to check the actual map data.
Outside city cycleway I know allow moped, however I checked and they have specific tag ```moped=destination```. And I checked cycleway that moped is not allowed, they have specific ```moped=no```.

So we need to understand when cycleway doesn't have ```moped``` tag whether it's correct ```moped=no``` or it's just missing information about moped. Most important that cycleway is well defined type of road and in Netherlands big portion of them allows moped and big portion doesn't.

**Comment by mem76** [comment]
> Though you are right about wiki definition but we need to check the actual map data. 

The  table in the wiki is the default, map data overrides the default...

> Outside city cycleway I know allow moped
This is country dependend. In this locations mopeds are not allowed on cycle-ways.

> So we need to understand when cycleway doesn't have `moped` tag whether it's correct `moped=no` or it's just missing information about moped. 

In my opinion the most strict access should be the default, so users are not users are sent on a detour or getting a fine.

In Norway [motor_vehicle=destination](https://wiki.openstreetmap.org/wiki/Tag:motor_vehicle%3Ddestination) is quite common on cycleways in order to give access to residential properties, moped would in those cases inherit the access from motor_vehicle if moped=(.*) is missing.

 > Most important that cycleway is well defined type of road and in Netherlands big portion of them allows moped and big portion doesn't.
 
And in that case I would assume that the cycleways there would be well defined in the map data with moped=(.*) tags.

**Comment by xmd5a2** [comment]
Fixed

**Comment by DmitryAlexei** [comment]
Moped routing now doesn't use cycleways. 
Initial route seems to be correct now. 
https://test.osmand.net/map/navigate/?start=60.418556,5.313070&end=60.434727,5.315902&profile=moped#17/60.42939/5.29088
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/42ee9460-6a0d-4b2c-af70-9c9c52330c2d"  width="600" height="auto"/> </td>
  </tr>
</table>

However, the initial part of the route looks different on the OsmAnd~ 4.9.0#3289m, released: 2024-09-26 (Android Nightly)
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/e6c05752-3821-4c3b-9296-ba7dc3f1132f"  width="300" height="auto"/> </td>
  </tr>
</table>
