### ISSUE TITLE
Regression: Route context card title broken

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#20741]
Observed with latest nightlies:
- Have 'Hiking routes' displayed on the map
- Tap on one route shield / OSMC logo
- If there is an interim menu asking which of several routes you meant to tap, on it both the Route names and Subtitles (route type etc.) still show ok.
- But as soon as you tap to end up on one specific route's context card, its subritle is empty, and its title is also often empty, or sometimes displays an unrelated static string like "Currently recorded track". 

Looks like some false resource reference...

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce it, go to these coordinates: 46.56362694531492, 7.883723821784882, and enable the display of 'Hiking routes'. Then, try clicking on the shield of a route to open a path. Also, zoom out and click on the route shield to open the list of routes and select one.

You'll observe that the subritles for these routes will either be empty or display the message "Currently recorded track."

OsmAnd~ 4.9.0#3122m, released: 2024-09-03

<table style="width:100%">
  </tr>
  <tr>
    <th> Selecting one route</th>
    <th>Selecting from a list of multiple routes</th>
  </tr>
  <tr>
    <td> <video source src="https://github.com/user-attachments/assets/f6ed4dcc-b6b3-4e81-9672-c6ed3a2a78dc"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/user-attachments/assets/1631de64-f5f3-4abe-8cb6-d5708294db62"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by sonora** [comment]
Probably a side effect of the same bug: After hiding the context menu again, the selected route remains highlighted on the map forever...

**Comment by dmpr0** [comment]
## Review
- [ ] Todo is missing

**Comment by vshcherb** [comment]
- [ ] Name should be displayed in context menu for selected Routes (same as for GPX 
- [ ] After hiding the context menu again, the selected route remains highlighted on the map forever...
