### ISSUE TITLE
Radius ruler widget displays illogical distance from tap

### ISSUE THREAD

**Issue by ossilator** [osmandapp/OsmAnd#20757]
### Description

under some circumstances, the reference point for the radius ruler's distance widget is assumed to be the screen center, despite the ruler's actual center being at the bottom, thus yielding a wrong distance.

### Steps to reproduce

- enable the radius ruler widget
- cause the ruler's center to be at the bottom. i'm actually not sure how this can be achieved reliably (#5703 seems related).
- drag the map with a finger

### Actual result

while dragging, the distance is wrong because a wrong reference point is used.

### Expected result

the ruler's center point is used, like when not dragging the map.

### Your Environment (required)

```
OsmAnd Version: 4.8.5
Android version: 13 (hyperos 1.0.5)
Device model: xiaomi redmi note 11s (fleur)
```

**Comment by yuriiurshuliak** [comment]
I was unable to reproduce this bug on my end. I tested by enabling the radius ruler widget and using the Distance by tap tool to compare the distances, and they were approximately the same in all cases.

Could you please provide detailed steps to reproduce the issue? We also need a video showing how the error occurs, along with the specific conditions and coordinates where you observe the incorrect distance calculation.

Additionally, how did you determine that the distance is being calculated incorrectly?

You might also find this guide helpful: https://osmand.net/docs/user/widgets/radius-ruler/#center--bottom-position

OsmAnd~ 4.9.0#3136m, released: 2024-09-06

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/007848d8-0d2a-4360-b7a8-c81c5f87281a"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by ossilator** [comment]
the bug is blatantly obvious, because the distance jumps from zero to the distance to the screen center as indicated by the ruler circles, as soon as the map is dragged, and jumps back as soon as the drag is released. no tool whatsoever is necessary to see it.

i can't describe the conditions more clearly than i already did. but they don't seem to be too critical, as this has been happening on my previous phone (galaxy S5) for years already.

how can i _quickly_ fake the current position? i don't want to post a video that reveals my home address.

**Comment by yuriiurshuliak** [comment]
To simulate GPS locations on your device, you can use various apps. Here's how you can do it and some recommended apps for Android platform:

1. Enable Developer Options:

- Go to Settings > About phone.
- Tap Build number 7 times to enable Developer Options.
- Now, in Settings > System > Developer options, look for Select mock location app.

2.Install a GPS Spoofing App: After enabling mock locations, you can use one of these apps to simulate GPS locations:

- Fake GPS Location: A simple app to set a fake GPS location on your device.
- Fake GPS Joystick & Routes Go: Allows you to not only set a static location but also simulate movement by creating routes.
- Mock GPS with Joystick: Similar to the others but with a joystick for easier navigation.

**Comment by ossilator** [comment]
there you go:
https://github.com/user-attachments/assets/c8eeeda5-318f-4588-83a6-b19f334c5102
the tap/drag gesture at the center has somewhat low contrast, but it's good enough.

**Comment by ossilator** [comment]
your observation is correct and consistent with my description.

but i don't see how your reasoning for this being intentional makes any sense. why would anyone _want_ that behavior? it serves no obvious purpose, and it is certainly surprising and disruptive.

**Comment by vshcherb** [comment]
@yuriiurshuliak it's intentional and documented, it's distance from finger to my location.

**Comment by vshcherb** [comment]
As this functionality implemented as it was always for Map Markers, Radius ruler widget displays location from map center to my location, so it's logical that hold & touch changes map center to the selected point on the map. As I know we don't plan to make this optional

**Comment by ossilator** [comment]
i don't think that it's "logical", as it makes for a rather "jumpy" experience, while not adding much value - you can just drag your finger to the ruler origin instead.
and the inconsistency between different origins disqualifies the current behavior anyway.

**Comment by ossilator** [comment]
the linked commit most definitely does **not** address the issue described here.
and even if it did, documenting an obviously counter-productive behavior instead of just changing it is not reasonable.
