### ISSUE TITLE
Weird bicycle routing. Maybe because of "class:bicycle=-1"?

### ISSUE THREAD

**Issue by blaueente** [osmandapp/OsmAnd#20759]
### Routing engine

- [X] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

bike (standard)

### Start and end points

https://osmand.net/map/navigate/?start=48.145566,11.534920&end=48.141155,11.534089&profile=bicycle#17/48.14276/11.53519

### Actual route

The router instructs to leave the bridge cycleway via stairs, then cycle through a passage and then use the stairs to got to the bridge again:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/ee5c57aa-6013-4622-b8ab-7047ad592bd0"  width="300" height="auto"/> </th>
  </tr>
</table>

### Expected route

Just stay on the nice bridge cycleway, which looks like this: https://www.mapillary.com/app/?lat=48.1428151429&lng=11.5343560409&z=19.398604445342272&pKey=210933860621538&focus=photo&x=0.4940183440953334&y=0.5091100746394124&zoom=0 

### Maps you used (online or offline)

- [X] Offline maps offered within the OsmAnd app for download. (From a week ago) 
- [X] Online (tile / raster) maps https://osmand.net/map/ from today

### Your Environment

This happens on a current OsmAnd, but on the website as well, so leaving this empty.

### Anything else?

I am not sure but it might be related to the class:bicycle=-1
 https://www.openstreetmap.org/way/338471764 
A political bicycle advocacy group has been increasingly adding negative class:bicycle values to cycleways all over the city (specifically for this bridge: https://www.openstreetmap.org/changeset/139223108#map=15/48.13469/11.53148 )  
Technically they might be correct (criteria: https://www.munichways.de/osm/): this cycleway could be nicer, e.g. wider, not shared with pedestrians, physically separated from the street, etc. but it is decent, reasonably safe and a good way to cross the railway. But that shouldn't be leading the router to avoid this way so hard, the alternative offered by the router with steps etc. is ridiculous.

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To compare the navigation results, please check both the Web version and OSM using the links below:

Web version: https://test.osmand.net/map/navigate/?start=48.145570,11.534920&end=48.141150,11.534090&profile=bicycle#16/48.1438/11.5271
OSM: https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=48.140996%2C11.534089%3B48.145714%2C11.534990#map=16/48.14375/11.53127

**Comment by vshcherb** [comment]
Yes this path looks wrong - https://test.osmand.net/map/navigate/?start=48.145570,11.534920&end=48.142688,11.534383&profile=bicycle#17/48.14404/11.53325

**Comment by vmicho** [comment]
According to doc:
https://wiki.openstreetmap.org/wiki/Key:class:bicycle

this should be `class:bicycle=2`. So I suggest fixing it on OSM.

**Comment by rafalwlo** [comment]
The description on https://www.munichways.de/radlvorrangnetz/ says (in English):

> Actual situation:
> partly wide cycle path partly shared foot/cycle path - a lot of motor vehicles/noise/pollutants - flat - narrow sections and conflicts in the middle at the bus stops
> Mapillary Link:
> Mapillary street view
> Description:
> Alternative is the Arnulfsteg - danger points are before and after the bridge at the huge intersections Arnulfstr. and Landsberger Str.
> Measures to be taken:
> wide protected cycle path - separated from pedestrian traffic

Together with the street level photo, the `class:bicycle=-1` seems to be correct for this way.

What doesn't look correct, is taking stairs over `class:bicycle=-1`, where imo stairs should rather be preferred over `class:bicycle=-3` or `class:bicycle=-2` but not over `class:bicycle=-1`.

Also the difference in the routing mentioned in https://github.com/osmandapp/OsmAnd/issues/20759#issuecomment-2333519709 should be investigated.

**Comment by xmd5a2** [comment]
Fixed. No new maps required.

**Comment by DmitryAlexei** [comment]
Fixed both on the web and in the app (tested using TestFlight 4.8.3.5)
https://test.osmand.net/map/navigate/?start=48.145570,11.534920&end=48.141150,11.534090&profile=bicycle#18/48.14328/11.53497
<img width="608" alt="Screenshot 2024-09-26 at 16 42 02" src="https://github.com/user-attachments/assets/1e49125e-a810-4af7-8b3d-33c628c99b1b">
