### ISSUE TITLE
Option to calculate time to destination using actual/average speed instead of Default

### ISSUE THREAD

**Issue by jjgknapik** [osmandapp/OsmAnd#20752]
### Describe the idea

OsmAnd with the Aircraft profile is great backup/support for private pilots, especially outside of the US. There is only one, although significant, issue: time to destination (or immediate destination) is calculated using Default vehicle speed instead of actual/average. 
The average speed widget is already available, so I ask to have the option to use it for time to destination calculations.

### Expected behaviour

It should be possible to switch time to destination (final and/or intermediate) widget to use actual speed (possibly from Average speed widget) instead of Default speed from vehicle settings.

### Alternatives you've considered

I was advised to use Glide Ratio widget, but I don't see how that could help. Also setting Default speed is not a viable solution, as pilots sometimes prefer, or are forced/required to, to fly slower or faster, not to mention the wind which greatly affects the actual ground speed.

### Context

I can imagine that this option could be also very useful with other profiles (boat, walking, cycling).

**Comment by yuriiurshuliak** [comment]
In this case, you can use navigation via Markers. Map markers can act as destinations when creating a route. To do this, you'll need to enable the Map Markers widget. The Map Markers widget and the Distance Indication widget will display:

- The distance from your current location to the selected marker on the map.
- The estimated time of arrival.

For more details, check out this guide: [Markers Widget Guide](https://docs.osmand.net/docs/user/widgets/markers/#panel-widgets).
