### ISSUE TITLE
[BUG] Share notes doesn't send nothing. Nigthly build

### ISSUE THREAD

**Issue by mircozorzo** [osmandapp/Osmand#2075]
Sharing a photo taked with OsmAnd sends a void mail or message.

**Comment by mircozorzo** [comment]
Stll it happen in today nightly build. Trying to share by email tells "Can't share a empty file".

**Comment by crimean** [comment]
Are you sure this is the problem of share and not recording? Can you play this file on the device?

**Comment by mircozorzo** [comment]
Hi, yes, I can see the photos or hear the audio notes but cant' share with Telegram or by mail. Trying to attach the file to a mail gives an error about an empty file. Still present in nightly build.

**Comment by crimean** [comment]
What device/android version do you have?

**Comment by mircozorzo** [comment]
Hi, thanks for the reply, device is a Samsung GT-I8260 with 4.1.2 Android.

Mirco
Il 15/gen/2016 15:16, "Alexey" <notifications@github.com> ha scritto:

**Comment by vshcherb** [comment]
Can you try sharing by gmail? I tried gmail, viber, hangouts and it works so far.
