### ISSUE TITLE
remember 2D/3D setting android auto

### ISSUE THREAD

**Issue by imyxh** [osmandapp/OsmAnd#20779]
### Describe the idea

Since the last update to my app (Google play beta, if it matters) OsmAnd has been defaulting to 3D view every time it starts on android auto. This is annoying because I use the "north is up" orientation while driving so looking at the map on a slant makes no sense. It's pretty trivial for me to click the toggle every time, but annoying nonetheless.

### Expected behaviour

OsmAnd should remember the last used setting for 2D/3D view, and start up with that.

### Alternatives you've considered

At minimum, OsmAnd should default to 2D for map orientations other than movement direction.

### Context

Love this project <3

**Comment by imyxh** [comment]
Sorry, I initially specified this as if it affected only the android auto component, but seems to apply to the view on my phone too.

**Comment by imyxh** [comment]
See also #20605 #20606

**Comment by vshcherb** [comment]
Looks like state on the phone after usage AA is inverted
![telegram-cloud-photo-size-4-6032851458308817251-y](https://github.com/user-attachments/assets/3c8143ed-d99e-42ce-8886-108c7cfefc41)

**Comment by dmromanov** [comment]
@vshcherb Thanks for sharing your screenshot.

I would also like the developers to pay attention to the "3d" button in the screenshot: this button is useless, since the application is already in 3d mode.

**Comment by imyxh** [comment]
It wouldn't be a huge problem if we just had to click it once every time we had to drive, but the problem for me is that when I reverse my car, AA is replaced with the backup camera, and when I shift back into drive then the setting is forgotten. So I have to click the map every time I reverse my car, or open spotify, etc.

**Comment by imyxh** [comment]
I think there needs to be a call to `setLastKnownMapElevation` here?

https://github.com/osmandapp/OsmAnd/blob/a9e4f8782edca284362c9179d8003e001f3dcc52/OsmAnd/src/net/osmand/plus/auto/SurfaceRenderer.java#L267-L278

Seems like a quick fix and I don't have a testing environment set up so might be easier for one of the main devs to try it.

**Comment by vshcherb** [comment]
There are some tricky issues after route calculation / preview, sometimes 2d/3d is reset again

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/commit/d392a02603dca535939e6ccaca031c4d6af15242

**Comment by Zirochkabila** [comment]
# Testing 1
`OsmAnd~ 5.0.0#3970m, Released: 2024-12-19` - Fixed

**Comment by dmpr0** [comment]
> Expected behaviour
> OsmAnd should remember the last used setting for 2D/3D view, and start up with that.

* Expected behavior is not achieved

**Tested:**
* Connect to Android Auto (AA) change map to 3D mode
* Calculate route, Start – Stop. 
* Disconnect AA
* Close OsmAnd on smartphone
* Reconnect to AA
* App Start in 2D, Navigation start in 2D
