### ISSUE TITLE
Is osmand can import kml (google maps) as favorites?

### ISSUE THREAD

**Issue by tbicr** [osmandapp/Osmand#2077]

**Comment by sonora** [comment]
Converting them to .gpx with any kind of converter and then using Osmand to open them will definitely work (option to import the favs is displayed).

**Comment by stephan75** [comment]
and just a kind hint to @tbicr :
I think the Osmand googlegroup mailinglist at https://groups.google.com/forum/#!forum/osmand is a much better place to aks such questions ... because this feature in github here is an issue tracker.

**Comment by tbicr** [comment]
Unfortunately converting to `.gpx` really not easy when somebody share `.kml` on mobile device, look like easily just use maps.me for this.

**Comment by PanderMusubi** [comment]
Here is a script to convert `favourites.gpx` to `My Places.kml` https://github.com/PanderMusubi/osmand2mapswithme

You can use e.g. syncthing to get the file from OsmAnd from your mobile device to a server or desktop and after conversion send it back to MapsWithMe on your mobile device.

**Comment by black-square** [comment]
I wrote a script which can convert favourites and labels from `Google Maps` to `OsmAnd (GPX)` by using an Android device only:
https://github.com/black-square/gis_tools
