### ISSUE TITLE
4.9.0 has some issue with displaying routes

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#20772]
### Description

I planned a route and after finishing it, it is displayed on the map. But as soon as I edit it's appearance (color), it's not displayed anymore.
I see the start and finish symbols, I can tap it and open it's menu, but not even "reset to original" does repair this issue.

Happens in the 4.9.0 but not in the previous 4.8.x.
But not to every route. Some routes work, some don't and have this issue. Others are only displayed partly. Very strange. 

### Steps to reproduce

See description above. 
It only happened when creating short, almost closed loops (like around a plot,, lake, small area)  and not when creating a longer driving route. 

### Actual result

Route is not visible anymore. 

### Expected result

Display the route 

### Your Environment (required)

OsmAnd Version: +4.9.0

**Comment by Rowin63** [comment]
[Sat 07 Sep 2024.gpx.txt](https://github.com/user-attachments/files/16915130/Sat.07.Sep.2024.gpx.txt)

This one for example was not displayed anymore after creating it. I just see the start and finish symbols.

**Comment by Rowin63** [comment]
![Screenshot_20240907_094058_OsmAnd+](https://github.com/user-attachments/assets/6e9813ae-b13c-4dd4-a838-49a3eeaf3de8)
This is right after creating the route.
I can tap it and open it's menu, but no matter what color I select, it remains non visible.

**Comment by sonora** [comment]
@Chumva, @Andrewschenko  Perhaps an unwanted  side effect of https://github.com/osmandapp/OsmAnd/commit/232841b984649014719f2ef1529b07813c005fca ?

**Comment by vshcherb** [comment]
It's probably already fixed, please double check

**Comment by Andrewschenko** [comment]
[Fixed](https://github.com/osmandapp/OsmAnd-core/commit/99dc9d50eedfe07a271d50de17e4bdcf4c9792b0)
