### ISSUE TITLE
android auto decoupled from map on phone

### ISSUE THREAD

**Issue by imyxh** [osmandapp/OsmAnd#20780]
### Description

When using android auto (Maps+), the map on my car and the map on my phone are not synced to one another.

### Steps to reproduce

Part A:

1. connect phone to android auto and open OsmAnd
2. start navigation (e.g. from favorites) on android auto
3. observe that navigation works fine on the car screen but is not started on your phone.

Part B:

1. connect phone to android auto and open OsmAnd
2. start navigation on phone (can do this before step 1)
3. observe that navigation is not started on car's screen but works fine on phone.

### Actual result

The map on android auto's screen is basically completely independent of the map on my phone; modifying navigation on one doesn't start it in the other.

### Expected result

The previous behavior was actually quite good. The navigation on my phone was coupled to the navigation on my car, so for example if I needed to zoom in the map without taking my eyes off the road, I could reach for my phone and click the volume buttons. Also, I could hand my phone to a passenger and ask them to modify the route to add an intermediate destination, or delete one we had passed, etc. Lots of functionality for controlling navigation settings isn't available in the android auto screen so it was really helpful to be able to set those on my phone and have it update on my car.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.9.0
Android/iOS version: 11
Device model: Nokia 4.2
Crash-Logs: N/A
```

**Comment by vshcherb** [comment]
Map couldn't be displayed on both devices obviously. Then use case when you start navigation on the phone and connect to AA works fine, it switches navigation to AA. This behavior was not reproduced during our intensive testing.
If you switch off AA (in case it's wired connection), map is brought back to the device which I think doesn't happen in your case. 
That means we didn't see that behavior yet in our 4 tested environments.

**Comment by imyxh** [comment]
Oh, so when you test 4.9.0, there is only one map shown at a time? That was the behavior for me before the update but now I have two maps being displayed and controlling navigation settings on my phone doesn't do anything for the car.

**Comment by imyxh** [comment]
As proof, here's a screenshot of my phone doing split-screen between osmand and opencamera. You can see that I've managed to route my phone and my car to completely different destinations at once!

![Screenshot_20240908-191358](https://github.com/user-attachments/assets/1f7905cb-4f10-4f60-8938-11fbc654dfe5)

btw, *sometimes* it seems that when I connect to AA the route on my phone will copy to my car. But then I lose the ability to select new destinations from my car, and also if I change the route on my phone it doesn't update on the car. I don't know what the heck is going on but it's very buggy.

This is after a fresh reinstall.

**Comment by vshcherb** [comment]
this is weird and probably it's not AA but Automative OS? It's only possible if you run 2 osmand instances

**Comment by imyxh** [comment]
no, it's android auto

**Comment by vshcherb** [comment]
Fixed
