### ISSUE TITLE
threshold before rotating while pinching to zoom

### ISSUE THREAD

**Issue by imyxh** [osmandapp/OsmAnd#20781]
### Describe the idea

When I pinch to zoom in or out, the map shouldn't rotate unless I am intentionally twisting my fingers (i.e. there should be some rotation threshold). Especially if orientation is set to north-is-up.

### Expected behaviour

Prior to 4.9.0, when I set north up and pinched to zoom, the map wouldn't rotate unless I intentionally twisted my fingers.

### Alternatives you've considered

N/A

**Comment by yuriiurshuliak** [comment]
Could you please attach a video or screenshot that clearly shows the issue? I'm having trouble fully understanding your description based on the information provided.

**Comment by DmitryAlexei** [comment]
@imyxh you still can rotate the map when map mode is set to "north is up"?
could you please provide short video and logcat log file

**Comment by imyxh** [comment]
Yeah, to be clear this is for the "manually rotated" mode and I do think the threshold should still exist.

For example, someone might want to rotate the map to align with the grid of Manhattan, and then want to pinch to zoom in and out without screwing with the rotation. "Manually rotated" with a threshold before rotating was perfect for this.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/commit/4605371d9a0caa57c50fc2217cd2cd1695a935b8

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/commit/13a67f09a2c9df8e8c1aad7cc7f55d8abaef1f28

**Comment by alex-osm** [comment]
Commit to master branch for testing in nightly version - https://github.com/osmandapp/OsmAnd/commit/6582369956a3f5f7f009da0aaa921c23dd470077
