### ISSUE TITLE
Copied coordinates should be ASCII/ANSI coded

### ISSUE THREAD

**Issue by gitmuti** [osmandapp/OsmAnd#20783]
### Description

If you select a coordinate from a marked location in the details by clicking on it and it is automatically copied to the clipboard, 
then a character set is used which is obviously not ASII/ANSI. 
This can lead to the fact that if you then copy the clipboard with the coordinates into another application, the coordinates are not recognized because they are not ASCII/ANSI.
Examples with Windy app and a text application.

I suggest that **all** available clickable coordinates (even those without apostrophe) are checked with regard to the automatically copied character set and that the character set in the clipboard is automatically converted to ASCII/ANSI.
This ensures the practical use of the copied data in all applications.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/0d3efa9d-2d0d-485b-962e-c1d9492ba318"  width="300" height="auto"/> </th>
  </tr>
</table>

### Steps to reproduce

**Use case 1 with Windy App:**

- Select a location in the OsmAnd app by pressing and holding .
- Click on Details
- Expand the coordinates 
- Click on a coordinate in DMS format
- Start Windy App on Android
- Open the search
- Paste the clipboard

**Use case 2 :**

- Select a location in the OsmAnd app by pressing and holding .
- Click on Details
- Expand the coordinates
- Click on a coordinate in DMS format
- Copy this into a text application that retains the copied character set.

### Actual result

**Use Case 1:**
The coordinates are not recognized because the character set of the copied data is not ASCII/ANSI.

**Use Case 2:**

![Result_2](https://github.com/user-attachments/assets/b0db9303-6fab-4775-9bc8-176520ab798d)

The apostrophe is tilted to the right --> no ASCII/ANSI character set

### Expected result

Use Case 1:
The coordinates are recognized correctly.

Use Case 2:
48°10'11.8" N, 10°41'25.1" E

### Your Environment (required)

OsmAnd+ 4.8.6, veröffentlicht: 2024-08-08
Device : r9q
Brand : samsung
Manufacturer : samsung
Model : SM-G990B
Product : r9qxeea
Build : UP1A.231005.007.G990BXXU9GXH2
Version : 14
App Version : OsmAnd+
Apk Version : 4.8.6 4806

Windy mobil app on android version 42.5.3

**Comment by imyxh** [comment]
ANSI/ASCII doesn't have the proper prime and double prime characters; using apostrophe and quote for that is technically incorrect.

Can you not just copy it as decimal instead of sexagesimal?

**Comment by gitmuti** [comment]
Hi there,
Thanks for your reply!

I can give the following three answers:

### First answer
The Windy application accepts the following coordinate formats:

![windy_coordinate_formats](https://github.com/user-attachments/assets/02f10ff2-6f62-4fce-9272-2b23c2e02bb5)
Source: https://github.com/osmandapp/OsmAnd/issues/20783

The OsmAnd app offers the following coordinate formats:
![OsmAnd_2](https://github.com/user-attachments/assets/82b35d94-f75e-44cd-a121-12a1d23870d2)


a) When the format 
46.00254 9.89388
is copied and pasted to Windy search input field it does not work in Windy due to the missing comma.

b) 
When I convert the OsmAnd format 
48°10'11.8" N, 10°41'25.1" E
using an external third party tool to ASCII then this string accepted by Windy search.


### Second answer
your wrote: _ANSI/ASCII doesn't have the proper prime and double prime characters; using apostrophe and quote for that is technically incorrect._

OK.
But then should it be probably a proper UTF-8 encoding? 

### Third answer
If I look at the coordinates copied from OsmAnd 
46°00′09.2″ N, 09°53′38.0″ E
in the clipboard using a HEX editor, it looks like this:

![hex_code_1](https://github.com/user-attachments/assets/7a141244-acfb-4efa-b305-a39a30e89dd3)

That looks very strange to me! That is  not UTF-8. 
I don't know what OsmAnd is copying into the clipboard. 
Or there is a strange change within the clipboard when using the clipboard that distorts the content of the clipboard.

**Comment by imyxh** [comment]
I think it's E2 80 B2, which is U+2032 PRIME. Similar for U+2033.

**Comment by imyxh** [comment]
(the 30 is ASCII zero)

**Comment by H--W** [comment]
I too have run into this problem transferring lat/long into a legacy application. In my case adding a new format of ddd mm' ss.s"<NSEW> would solve the need to edit the lat/long where the format has no degree symbol, uses apostrophe instead of prime and double quote instead of double prime. Sadly one case required a comma between the lat and long while another required a space. More recent applications have happily digested UTF-8.
Best Rgds, -H-

**Comment by gitmuti** [comment]
> I think it's E2 80 B2, which is U+2032 PRIME. Similar for U+2033.

That is correct. My marking had slipped by one.

**Comment by vmicho** [comment]
My note: Using prime + double prime (there are also triple and quadruple primes, but not much used) is the correct format for DMS angle notation ( see https://en.wikipedia.org/wiki/Degree_(angle)#Subdivisions )
For example OSM accepts both formats (with primes and with apostrophe+quote).

However I'd appreciate if the copy coordinates menu would be customisable.
For example I personally only use the decimal angles notation and the 'copy' (with osmand link) so it would be practical to uncheck some options to disappear from the copy coordinates menu ;)

**Comment by vshcherb** [comment]
We probably can change "33.232 5.3212" to "33.232, 5.3212". So this is more commonly accepted format

**Comment by sjvudp** [comment]
> We probably can change "33.232 5.3212" to "33.232, 5.3212". So this is more commonly accepted format

Sorry, I fail to see the difference!

**Comment by vshcherb** [comment]
To do: we need to update to "48°10'11.8" N, 10°41'25.1" E" (fix quotation)

**Comment by readonly24** [comment]
> Sorry, I fail to see the difference!

It's the comma in between.
