### ISSUE TITLE
Context menu buttons are truncated when using big system font

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#2078]
When using system font bigger than normal (in android settings) and long tapping to place with very long address, context menu buttons are truncated and drawn outside of visible screen.
Place: http://www.openstreetmap.org/?lat=56.1286932541208&lon=40.4030514075433&mlat=56.1286932541208&mlon=40.4030514075433&zoom=16

Screenshot: https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot_2015-12-23-17-41-31.png

**Comment by sonora** [comment]
Yes, very annoying, we should try to fix, as using large system fonts is not uncommon for outdoor use.

**Comment by crimean** [comment]
Will be fixed soon
