### ISSUE TITLE
Custom color dialog produces bogus color codes

### ISSUE THREAD

**Issue by Boothy99** [osmandapp/OsmAnd#20799]
### Description

When attempting to change the group default color in "My Favourites", the color is not saving for any group if selecting a "Custom" color **(EDITED.....) + Transparency slider to reduce opaqueness**

### Steps to reproduce

Open My Places / My Favourites,
Select menu options for a group & choose..
Change default appearance,
Produce a custom colour **+ decrease opacity** & select it (or any previous custom **semi-transparent** colour),
Apply to existing,
Check colour changed (yes)
Fully close OsmAnd after waiting a while for changes to register (remove from background apps)
Re-open OsmAnd - the group colour has reverted to a default yellow.

### Actual result

As above, on re-opening OsmAnd - the group colour has reverted to a yellow.

### Expected result

On re-opening OsmAnd - the group colour should remain as selected custom colour.

### Your Environment (required)

Device : oriole
Brand : google
Manufacturer : Google
Model : Pixel 6
Product : oriole
Build : AP2A.240905.003.F1
Version : 14
App Version : OsmAnd+
Apk Version : 4.9.0 4900

**Also occurs on Samsung Galaxy Tab S4 ...**
Device : gts4lwifi
Brand : samsung
Manufacturer : samsung
Model : SM-T830
Product : gts4lwifixx
Build : QP1A.190711.020.T830XXU5CVG2
Version : 10
App Version : OsmAnd+
Apk Version : 4.9.0 4900

**Comment by Boothy99** [comment]
I'm wondering if an issue I'd emailed support about recently (request **63480**) has anything to do with this? It regards export of favourites.gpx file being smaller file size than all other exports for backup. Previously, after adding POI's etc, the file size is larger NOT smaller !

" _Hi team,
A quick question regarding exporting favourites.gpx -
I noticed yesterday that the favourites.gpx file size is now smaller than the last export(s), even though I've added numerous POI'S / notes, and deleted nothing. I checked this on both of my devices as above with the same result.
All exports for this file have been incrementally larger (if I've added to the POI's etc) each time I've saved them as a backup (previously the last "largest" was 1.96 MB, but now is 1.58 MB). Has something changed to reduce it's size / compression recently?_ "

**Comment by Boothy99** [comment]
**Today, I added...**

" _In addition to this, I just noticed that if I import the (recent "smaller") favourites.gpx to my other device (Samsung Galaxy Tab S4), the groups icons and colours have been corrupted. Icon colours are generally yellow, and icons are either incorrect or a default.
If I delete all favourites then import an older (larger file size), favourites.gpx backup, then all is good + icons and colours are correct. 
I noticed this today after writing on GitHub ....
"My Favourites" default color not saving for group if using "Custom" color. #20799_ "

**Comment by Boothy99** [comment]
((If these concerns are considered not related, I'll be happy to open a separate issue if required))

**Comment by Boothy99** [comment]
I've opened a separate report here -
https://github.com/osmandapp/OsmAnd/issues/20805#issue-2516609899

Again .... I'll delete the above comments relating to Export / Import if required.

**Comment by Boothy99** [comment]
Thanks for confirming the bug can be reproduced @yuriiurshuliak 👍👌
I also see that you received a "Add favourites / import" screen on initially opening My Favourites. I've seen that too.
Cheers

**Comment by sonora** [comment]
@yuriiurshuliak watching the video, perhaps this is a simple timing issue, killing the app after the change is applied, but not yet written: Can you please test giving the app some time to write the change (I believe that the change is actually written to the end of the backup file, and if your ioverlander.com group is extremely large, it may take some time).

For all my groups 5 sec seems to suffice, but perhaps not for your experiment?

**Comment by Boothy99** [comment]
@yuriiurshuliak - thanks again for testing. I think I've narrowed things down (& edited the title + method to reproduce).

What I missed out was the fact that for certain categories of POI, I'd chosen a Custom colour AND **reduced it's opacity**. If I select any of the default colours, then I saw there's no issue in it getting saved. As soon as I make a custom colour + use the transparency slider (~50%) ... THEN the colour will not save - even after I leave OsmAnd open for 5 to 10 minutes. Any standard default colour (full opacity) is saved without issue.

So, for me at least ... it seems that reducing the opacity appears to be the culprit. Any custom colour I choose is remembered, so long as I don't reduce it's opacity. Any thoughts and comments appreciated. Thanks for testing @yuriiurshuliak 👍👌

**Comment by sonora** [comment]
Good observation! And it looks like the problem is in the _slider_. I had initially always used the _text field_ (editing the first two hex characters after the # sets the opacity), and colors inlcluding their opacity then seem to be saved ok?

**Comment by sonora** [comment]
Confirmed. Using the slider produces values like `color="#-77010000` in the gpx file.

**Comment by Boothy99** [comment]
Sending thanks over to yet again tonight, @sonora 😁 
Do I get my bonus points back for zeroing in on the issue after losing some on the Export / Import non-issue ? 😂 
Cheers for changing the title to a more technical version 👌

**Comment by gpsvisualizer** [comment]
I discovered this opacity issue today and am glad to see someone's aware of it.  It applies both to individual favorites AND to the default appearance of a favorites group: everything's fine while the app is opened, but a not-fully-opaque color saved in the GPX file gets turned into a "negative" hex code.

**Comment by Boothy99** [comment]
Thanks for your comments & confirming, @gpsvisualizer 👍

**Comment by sonora** [comment]
We have 3 places (room for simplification) converting color to string, all slightly different:
https://github.com/osmandapp/OsmAnd/blob/69047bd65e28ee1d63d97f5298603c1563fb9fe6/OsmAnd/src/net/osmand/plus/helpers/ColorDialogs.java#L156
https://github.com/osmandapp/OsmAnd/blob/69047bd65e28ee1d63d97f5298603c1563fb9fe6/OsmAnd-java/src/main/java/net/osmand/util/Algorithms.java#L1065
https://github.com/osmandapp/OsmAnd/blob/69047bd65e28ee1d63d97f5298603c1563fb9fe6/OsmAnd-java/src/main/java/net/osmand/render/RenderingRulesStorage.java#L203

Either the issue is with `Integer.toHexString(colorInt)` producing an explicit "-" sign in the string for negative integers, or we re-parse such a created hex string and then interpret it as a negative.

**Comment by sonora** [comment]
This PR fixes it: https://github.com/osmandapp/OsmAnd/pull/20825.

Optimization may still be done consolidating all the various `colorToString` and `parseColor` methods.

**Comment by Boothy99** [comment]
Appreciate you getting on to this so quickly 👌

**Comment by Boothy99** [comment]
A quick thanks to @sonora and team for fixing this 👍👌
Updated Beta to OsmAnd+ 4.9.2, (released: 2024-10-25) and translucency of icons works perfectly again, cheers.
