### ISSUE TITLE
Slope color map does not represent true slope of terrain

### ISSUE THREAD

**Issue by marcelharing** [osmandapp/OsmAnd#20797]
### Description

My gut feeling was that the slope map based on OsmAnds DTM underestimated the steepness of the terrain (which would not be good for avalanche risk assessment), so I compared it with Sonnys 50m DTM and openslopemap.org low resolution layer (20-30m) in QGIS with the avalanche color ramp from OsmAnd:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/77102a68-b03e-4ac7-9f23-37054c9cc547"  width="600" height="auto"/> </th>
  </tr>
</table>

Although Sonnys DTM resolution is lower, it represents the terrain much better. 
OsmAnd's DTM somehow underestimates it? I don't know why, but maybe you smoothed it too much? Afaik you also use Sonnys DTMs, but the 50m or the 20m resolution DTMs?

### Steps to reproduce

Calculate the slope of OsmAnd's DTM and [Sonnys 50m DTM](https://sonny.4lima.de/) (in this case for Austria) and style it based on the predefined avalanche color map of OsmAnd with slope steps of 30°, 35°, 40°, 45° in QGIS or add [OpenSlopeMapLayer LR TMS Layer](https://qms.nextgis.com/geoservices/6689/).

### Actual result

Slope steepness underestimated

### Expected result

See picture for comparison

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.8
Android version: 13
```

**Comment by vshcherb** [comment]
In OsmAnd you can use different geotif (though it should be in Mercator projection), and it could be much more detailed. Mostly artifacts are related that maps are condensed and don't have enough details for slope maps

**Comment by vshcherb** [comment]
In OsmAnd you can use different geotif (though it should be in Mercator projection), and it could be much more detailed. Mostly artifacts are related that maps are condensed and don't have enough details for slope maps

**Comment by vshcherb** [comment]
In OsmAnd you can use different geotif (though it should be in Mercator projection), and it could be much more detailed. Mostly artifacts are related that maps are condensed and don't have enough details for slope maps. As I remeber OsmAnd maps are roughly 50m  per pixel in many regions.

**Comment by xmd5a2** [comment]
See https://github.com/osmandapp/OsmAnd/issues/6636

**Comment by xmd5a2** [comment]
This happens cause in app we use height maps with lower resolution than sources we used to obtain these data.
But I've changed avalanche color palette a bit and now it reflects slope much better in my opinion.
![Image](https://github.com/user-attachments/assets/94a0284b-6f03-462c-8769-e5c2d887df56)

**Comment by DmitryAlexei** [comment]
### Later (bottom right corner)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/77102a68-b03e-4ac7-9f23-37054c9cc547"  width="600" height="auto"/> </th>
  </tr>
</table>

### Today 
OsmAnd~ 4.9.0#3365m, released: 2024-10-07
Color scheme > Avalanche, transparency 100%
go to coordinates 47.21036 11.54391 and see, that
**The Avalanche scheme now much more convenient for avalanche risk assessment.**

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/99f43cca-1a6e-4dab-91ae-f4dc9db7f68f"  width="600" height="auto"/> </th>
  </tr>
</table>

**Comment by valschneider** [comment]
Hi,

I've been experimenting with this on parts of the French Alps I'm familiar with, and the latest slope_avalanche.txt (https://github.com/osmandapp/OsmAnd-resources/commit/ac3abb03aa9ec6c99c2011ce7736c4e77aa94927) still isn't very accurate. I can mess with the values to get the slope representation to be good enough for one location, but it'll still be quite misleading two valleys over.

Is this comment about 3D height map zoom changes still relevant? https://github.com/osmandapp/OsmAnd/issues/6636#issuecomment-2128878449

**Comment by vshcherb** [comment]
You can create custom palette import and use it for now. As we don't have interface to change it in the app itself

**Comment by vshcherb** [comment]
Custom 3D maps geotif also could be imported, we don't know if we provide more detailed 3D maps as they increase size significantly x4

**Comment by marcelharing** [comment]
Yes, it still underestimates the slope a bit, as you can see in the comparison images. It seems this is due to the resolution of the DTM.

I still wouldn't recommend the current slope layer for avalanche risk assessment, because probably a resolution of 10m - 20m would be needed to assess the terrain correctly. Here is a slope layer in OsmAnd .sqlitedb format in 10m resolution for the Alps to download: https://info.skitourenguru.ch/index.php/swisstopo4guru

**Comment by valschneider** [comment]
Thanks for the link! I'll give this a try and tinker with it a little. FWIW another use I have for this is to figure out the steepness of the slope for skiing it, either before or after the fact - e.g. if I found a specific part was steeper than usual, how steep was it, and this gives me data on how well I can ski said slope / how I'm progressing.
