### ISSUE TITLE
Wrong interpretation of date on access:conditional=no

### ISSUE THREAD

**Issue by vmicho** [osmandapp/OsmAnd#20798]
### Description

A weird route is suggested:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/4545ddac-b72f-4ca4-895f-5088a29e3fd5"  width="600" height="auto"/> </th>
  </tr>
</table>

After looking a bit into OSM, I found out that portions of B31 (e.g. this one https://www.openstreetmap.org/way/41476627) are marked as:
`access:conditional=no @ (17 Jun 2024-07 Jul 2024)`
which is pretty unsuspecting right?

Well after some unholy digging through the (not so clear) OSM documentation I found out that the correct date format should actually be `2024 Jun 17` (that date format works, tested on another road I've marked closed a month or so ago).
I am sure that `17  Jun 2024` is interpretable without any doubts, as well `2024 17 Jun` or `Jun 17 2024` ...

The bug: osmand still considers the road closed for some unknown reason.

It should either:
* ignore the condition (not great though)
* ignore and warn (not sure if there is already some mechanism for showing some floating warnings on map) (still not great)
* interpret the date in any of above formats (and ideally also warn if not conform to YYYY MMM DD format)

### Steps to reproduce

https://osmand.net/map/navigate/?start=47.575599,9.710712&end=47.609288,9.587803&via=47.576269,9.709924&profile=car#13/47.5861/9.6242

### Actual result

a long way around is taken

### Expected result

main road (B 31) should be taken

### Your Environment (required)

```
OsmAnd Version: 4.8.6
Android/iOS version: android 13
Device model: xiaomi 11i
Crash-Logs: ?
```

**Comment by vshcherb** [comment]
This format is not supported  ```17 Jun 2024-07 Jul 2024```.
Correct version is ```2024 Jun 17 - 2024 Jul 07```
