### ISSUE TITLE
Correct "bearing" position icons still missing for night view

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2079]
In commit https://github.com/osmandapp/Osmand/commit/2b3892ce86f86756ba7bffc6c8c7868e3d95919b we intrduced light blue position icons for the night view, which proved to be well visible on our night maps. Now we are still missing the correct corresponding color "bearing" position icons, like map_car_bearing_night.png.

**Comment by vshcherb** [comment]
Should be fixed in today's nighlties.

**Comment by sonora** [comment]
Yes, confirmed working now. I see we yesterday also changed the day icons to the light blue version (from the conventional darker blue used by many nav apps), not sure that was necessary as on day maps there are many other lighter-colored features, so this reduces contrast. But we can test.
