### ISSUE TITLE
The context menu does not register any touch at a certain section

### ISSUE THREAD

**Issue by enomat** [osmandapp/Osmand#2080]
At the highlighted area, the context menu does not register any touch, which means you can touch the map through the context menu.

![screenshot_2015-12-24-18-58-27](https://cloud.githubusercontent.com/assets/12612250/11997060/f5632826-aa71-11e5-8d70-669fcbb1d284.png)

It happened many times that I tried to expand the details section of the context menu, but I accidentally touched the above mentioned area and it closed the context menu.

**Comment by vshcherb** [comment]
Reproduced.
