### ISSUE TITLE
problem with downloading offline maps

### ISSUE THREAD

**Issue by pius7** [osmandapp/OsmAnd#20808]
### Description

Downloading maps works randomly. in about 30% of the cases the map actually gets downloaded and is available afterwards. a lot of the time the download finishes and the map wont be avaible. Its mysterious, as it is not predictable.
I am running the osm app on sailfish os, which is not using google play services. Maybe the app is not intended to work on an OS like this.

### Steps to reproduce

go to maps and ressources. download a map for offline use.

### Actual result

sometimes the map is there and can be used offline. sometimes it shows like you never downloaded the map at all. and you are able to download it again.

[logcat.log](https://github.com/user-attachments/files/16962348/logcat.log)

### Expected result

map available for offline use after download.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
Device : voyager
Brand : Sony
Manufacturer : Sony
Model : Xperia XA2 Plus Dual (AppSupport)
OS: Sailfish OS 4.6
Product : aosp_h4413
Build : RSV1.210329.104
Version : 11
App Version : OsmAnd~
Apk Version : 4.8.5 480501
Crash-Logs: 
[logcat.log](https://github.com/user-attachments/files/16962348/logcat.log)

```

**Comment by DmitryAlexei** [comment]
Does OsmAnd stays on the foreground when you download maps?
Have you given the app the necessary permissions? 

Could you provide additional info: screenshots, short video with the problem?

**Comment by JLou5641** [comment]
Hi,

Same for me. Tested on 3 different phone, and also with bluestack.
The only way to download tiles, is to download them by selecting little area... too bad, cause it take lot of time, and you don't see what is already download

**Comment by JLou5641** [comment]
Okey, i find why. It's like Mobac, you can't download more than 500000 tiles once a time.
Just pay attention to not download more than 500000 each time you update your offline map tiles
