### ISSUE TITLE
Route begins >200m away from actual position

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#20816]
### Description

The beginning of the route line is displayed in a distance of more than 200m away from the actual vehicles position.
This makes navigation somehow difficult at lower speed / zoom level. Then the route line can even dissappear completely from the screen.

Turn arrows are displayed correctly, but no colored line.

### Steps to reproduce

follow a route and see.

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/bf5897c7-b3d1-42dd-b492-79435d94cb48"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/17168da3-8f07-41c9-b1b7-4d0b6209c638"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/621054c1-5501-4642-b42f-b734cb672c13"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/d13ddbec-ddad-4f5b-87d2-05e9b6f33ede"  width="300" height="auto"/> </td>
  </tr>
</table>  

### Actual result

no route line at the next >200m

### Expected result

show me the rout line

### Your Environment (required)

Osmand+4.9.0
Android 13

**Comment by vshcherb** [comment]
Work in progress
