### ISSUE TITLE
Trip Recording "Notification Disabled" Setting Ignored

### ISSUE THREAD

**Issue by yet-another-steve** [osmandapp/OsmAnd#20817]
### Description

I have disabled the screen notification when recording a trip.  This is because the notification opens the lock screen and when in my pocket this leads to pocket presses which on one occasion called the emergency services!! and on others has lead to photos being taken.  Only Osmand does this with notifications.  Changing Android settings for notifications does not prevent this from occurring.

I disabled trip recording notifications but to no effect; they still appear regularly and allow the 'phone to do pocket presses.

### Steps to reproduce

1. Disable trip recording notifications in the settings screen for ALL profiles
2. Start recording a trip then immediately click the button to close and lock the screen.
3. Wait.  The notification will pop up and switch the screen on.  (Screen presses can now take photos and call emergency services)

### Actual result

 The notification will pop up and switch the screen on.  (Screen presses can now take photos and call emergency services)

### Expected result

Notifications should not pop up when the setting is set to disabled in the trip recording settings for the profile.

### Your Environment (required)

```
OsmAnd Version: 4.8.6
Android/iOS version:  Android 13 TKQ1.221114.001
Device model: Xaiomi Poco F3 OS version 1.0.3.0.TKHEUXM
```

**Comment by DmitryAlexei** [comment]
@yet-another-steve Your issue might have been resolved (see https://github.com/osmandapp/OsmAnd/issues/20536)
Could you try the Nightly version and see if it works for you? See https://download.osmand.net/latest-night-build/OsmAnd-default.apk

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.9.0#3173m, released: 2024-09-12
"Notification disabled" option is really ignored when trip recording is enabled

Steps to reproduce:
- I disabled notifications in all active profiles
- started recording in browse map profile (see video)

Actual result:
- notification appears in the status bar

https://github.com/user-attachments/assets/1d05528d-46b1-480a-b2be-c68b960cb2cf

**Comment by yet-another-steve** [comment]
Thank you for testing that Dmitry.  I'll await the resolution of the option being ignored and try not to record tracks in the meantime.

**Comment by sonora** [comment]
@DmitryAlexei  To my knowledge:: That OsmAnd setting "Notification" actually controls if the Android notification bar, **when no recording is active**, shows an entry which allows you to start a recording without having to go through the OsmAnd map screen.

That setting does nothing about the fact that **during each ongoing recording** there is a corresponding notification visible in Android's notification bar. I believe this is even an Android requirement, that every (so-called "ForeGround") Service active on the device needs to be visible like this to the user, (and that may explain why it cannot even be suppressed via Android's settings).

But @yet-another-steve What strikes me in your report is that the screen seems to get activated under some conditions?! That's definitely not standard behavior, I have never experienced this. Have you set anything in OsmAnd's `General settings > Screen control`? Also: When you check the recording notification (pull down and pan it to the left), does it really show as as a "Silent" notification? Perhaps you have accidentally changed it to an "Alarm" notification?

**Comment by DmitryAlexei** [comment]
@sonora you are completely right
I've also consulted with the development team. I will summarize:
- without notification in the notification bar, trip recording will be stopped by the Android
- when Notification option in Trip recording is disabled, it only affects the situation when recording is not active.
- so it is the expected behavior of the notification

**Comment by vshcherb** [comment]
Isn't it documented properly?

**Comment by sonora** [comment]
@vshcherb  Not really ... :wink: It rather verbous, but misses the point  :wink:

![image](https://github.com/user-attachments/assets/493c349d-4155-4b09-a443-f7fc844651c7)
