### ISSUE TITLE
3D Track doesn't work correctly

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#20810]
# Review 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Solid</th>
        <th>Speed</th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/3494e413-aa5b-462d-aec0-f95ccdeb71d3"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/4a81d4ca-0c2d-4831-bf2f-0c73ef752a8f"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [x] Wall color doesn't work. Track line color parameter is always used, but should only if Solid is selected.

- - -

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Fixed height</th>
        <th>Speed</th>
        <th>Heart rate</th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/996e94e9-d885-498b-ad82-e2ad9c84d2b6"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/4b40edb4-b67d-44dc-8377-63b520c442a5"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/b9896dba-43a8-4677-9d5f-cd8ec79d614b"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [x] The same triangle is displayed no matter what visualization parameters is selected

_Originally posted by @dmpr0 in https://github.com/osmandapp/OsmAnd/issues/19785#issuecomment-2338320087_

**Comment by Chumva** [comment]
Track height should be fixed [here](https://github.com/osmandapp/OsmAnd-core/commit/ed0840677a2032475ccfb9efd05f9c7ee1740f1a#diff-1610d46924eaf85ce1bd98464dd806aea39932a0e6d243d0b84db38e715712daL717)
