### ISSUE TITLE
Incorrect turn directions (Turn left became Keep left)

### ISSUE THREAD

**Issue by Guylby** [osmandapp/OsmAnd#20828]
### Description

Hi, 

Since 4.9.0 I've noticed during car navigation that turn directions that previously were "Turn left" or "Turn right" have become "Keep left" and "Keep right" but this is incorrect. The intersections need you to exit the main road or are 1 lane only, so there is no lane to follow.

### Steps to reproduce

Standard car profile was used, the problem is seen both in Osmand+ and osmand web
Start point: 43.252674,6.099703
End point: 43.242835,6.085042

Here is two examples:
https://test.osmand.net/map/navigate/?start=43.252674,6.099703&end=43.242835,6.085042&profile=car#16/43.2477/6.0873

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/5f46cc8e-99fa-4b99-a861-0efa599b515a"  width="600" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/67fe91e9-09f7-453f-b942-643b491571d2"  width="600" height="auto"/> </th>
  </tr>
</table>

### Actual result

Instructions are Keep left and Keep right

### Expected result

Instructions should be Turn left and Turn right (as they were before)

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.9.0
Android/iOS version: 13
Device model: Sony Xperia 10 III
Crash-Logs: ?
```

**Comment by Guylby** [comment]
Another example:
A highway exit that should be "Turn right" is "Keep right":
https://osmand.net/map/navigate/?start=43.251853,6.101178&end=43.249677,6.093786&profile=car#17/43.25089/6.09650
![Screenshot 2024-09-13 at 09-23-43 OsmAnd Map](https://github.com/user-attachments/assets/f4afc118-9162-4aa6-9848-8e0f399ea591)

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. During navigation, the turning directions are incorrectly indicated as "Keep left" and "Keep right" when exiting the main road or when driving in a single lane.

The expected behavior is for the directions to be "Turn left" or "Turn right."

You can view the web versions [here](https://test.osmand.net/map/navigate/?start=43.252674,6.099703&end=43.242835,6.085042&profile=car#16/43.2477/6.0873) and [here](https://osmand.net/map/navigate/?start=43.251853,6.101178&end=43.249677,6.093786&profile=car#17/43.25089/6.09650).

OsmAnd~ 4.9.0#3179m, released: 2024-09-12

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/69c9fd42-2590-4ea4-be0f-7774716b1720"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/8f904e1e-7b19-4aa1-956a-4bc6a7441da9"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
To have Keep left keep right is a correct version for many motorway link, to have correct or better interpretation ```turn:lanes``` are needed, we constantly fixing bugs so this change might be a problem for other cases and in situations where we can't determine unique behavior across all types we recommend using turn:lanes mapping

**Comment by Guylby** [comment]
I'm not a fan of this change has it results in more misunderstandings than correct routing especially considering how Osmand behaved before this change.
When I hear "keep right", my understanding is to stay on the main road but keep to the rightmost lane. However all the examples I've presented require to exit the main road (or highway) and therefore there should be a "turn left or right" prompt as you have to change directions.
Here is an example with the topology of the first intesection presented on the first post:
When you have to go to the yellow road Osmand says "keep right", which is incorrect as you have to exit the main road and take the other road:
![Screenshot 2024-09-13 at 15-31-43 Google Maps](https://github.com/user-attachments/assets/e409a538-8b2f-455a-988c-537b404ea723)

Before you heard turn right and you'd know that you should take the first exit that appeared. Now with this behaviour you have to check on the gps to know if it's a "keep right" to stay on the main road or a "keep right" to exit the same road, which is really confusing.
Just yesterday on a short 1h trip without going on highways I had five times the "Keep right" instead of "Turn right" instructions, when in reality it was all the same scenarios as presented above, a single lane with an exit going another direction. 
I've tested OSRM and other route navigation software and all used a "Turn" instruction and not a "Keep". 

With this change you'd have to manually edit an enormous number of intersections with single lanes with the turn:lanes key to correct them just for Osmand which seems an absurd amount of work. 

It's also not consistent on highways, some exit are "turn slighty right", other "keep right" when they are mapped the same and are identical in reality: an exit where you have to exit the rightmost lane:

![Screenshot 2024-09-13 at 15-49-53 Google Maps](https://github.com/user-attachments/assets/8788c638-8d22-4798-bd6a-85af802bb66a)
If I hear "Keep right" I'd stay on the rightmost lane which is the Red one and miss the exit

**Comment by Guylby** [comment]
Another example at this intersection:
https://test.osmand.net/map/navigate/?start=43.220322,6.067811&end=43.220357,6.067656&profile=car#17/43.22267/6.06873

Here you have a keep left on a single lane road to take the left exit and go on the motorway with a sharp turn
![Screenshot 2024-09-13 at 16-38-52 OsmAnd Map](https://github.com/user-attachments/assets/a81844ac-2af3-4915-82b6-b3b87b17bf51)
