### ISSUE TITLE
"\" sign on the quick action button

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#20826]
Also about the buttons - there were quick buttons for showing poi, which changed their appearance when they were turned on, the image in the button became crossed out. Now this does not work

![Screenshot_2024-09-06-16-37-55-309_net.osmand-edit.jpg](https://github.com/user-attachments/assets/629c2af9-4c18-4308-a7cf-98a152acf8ba)

_Originally posted by @Nine-Tailed in https://github.com/osmandapp/OsmAnd/issues/20764#issuecomment-2334083370_

**Comment by DmitryAlexei** [comment]
The state of the buttons changes after extracting the app from the background. 

https://github.com/user-attachments/assets/67bf6d79-b7e9-4fa5-a8fb-6edd2e9a8f95

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.9.0#3361m, released: 2024-10-05
The image of the activated quick action button is crossed out now

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/681ddd24-8228-4d8b-9705-2c6b22028483"  width="300" height="auto"/> </td>
  </tr>
</table>
