### ISSUE TITLE
Cannot start text-to-speech engine

### ISSUE THREAD

**Issue by araaschou** [osmandapp/OsmAnd#20839]
### Description

When I start the OsmAnd+ app (Android, Aug 8 version) and start navigation (press the arrow) I get the error message in the title.
**PS: I have no interrest in using Text-to-speech, and I have as far as I know never enabled it.**

### Steps to reproduce

As written in the description: When I start the OsmAnd+ app (Android, Aug 8 version) and start navigation (press the arrow) I get the error message in the title.

### Actual result

See https://drive.proton.me/urls/89W9RYFN7G#C590xZOjl78r
(The long wait has been shortened by hiding som elements.)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/a38c0384-91a6-463c-85ea-7bc5e3671b06"  width="300" height="auto"/> </th>
  </tr>
</table>

### Expected result

I don't understand what to write here.
I just want the message to not pop up.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd+ 4.8.6, released: 2024-08-08
Android/iOS version: 13, security update : August 5, 2024
Device model: Fairphone 3, Build number 6.A.030.0
Crash-Logs: No Crash-log was available, but a logcat.log was (attached).
[logcat.log](https://github.com/user-attachments/files/17002204/logcat.log)

```

**Comment by yuriiurshuliak** [comment]
The issue could not be reproduced. On my end, I was unable to trigger the "Cannot start text-to-speech engine" error. This is likely a local issue related to your device’s system settings.

As a workaround, I suggest switching the voice prompt option from TTS to a recorded voice. You can do this by going to Navigation → Settings → Language → Recorded → Download and select your preferred language, then turn off voice prompts.

Here’s a detailed guide: [Recorded Voice Prompts Guide](https://osmand.net/docs/user/navigation/guidance/voice-navigation/#recorded-voice-prompts).

Additionally, I've attached a video below demonstrating the steps.

OsmAnd~ 4.9.0#3224m, released: 2024-09-19


https://github.com/user-attachments/assets/01a625d3-1863-478f-9f04-470f89c29a6f

**Comment by araaschou** [comment]
Thank you for the suggestion.

I have now

- selected Voice prompts (recorded, limited..) / Beep: minimal
- enabled Voice prompts and disabled every setting in there
- disabled Voice prompts

and it looks like that did it. I do not know if it was selecting Beep or disabling all settings that did it.

Regards,
Arne

**Comment by sonora** [comment]
Well, the Beeps options simply play pre-recorded beep sounds, that's why OsmAnd lists them under 'recorded voices'. In other words, by selecting a recorded voice you are not solving the (potential device) issue that your setup does not properly facilitate TTS (the sythesized pronunciation of _any_ text, even e.g. street names), you are merely avoiding it.

May be worth investigating if/how your device can properly enable TTS. If it has no TTS engine installed by default, you can always install one.

**Comment by sonora** [comment]
Ah, ok! probably you had selected a tts voice when first prompted.

I will close the issue then.

**Comment by ProBackup-nl** [comment]
Even on OsmAnd.plus 5.0.5 the "_Cannot start text-to-speech engine_" message appears when starting a new navigation taks.

My [Lineage 18 MicroG Android OS](https://download.lineage.microg.org/jfvelte/lineage-18.1-20250203-microG-jfvelte.zip.sha256sum) has no TTS installed. I don't want to use TTS. The navigation profile has "Sound | Voice prompts" disabled (not enabled).

Please try to not touch the Text-To-Speech service when sound is disabled in OsmAnd.

Note: when I remove to English and Dutch TTS components in section "Installed", these components automagically re-appear there.

PS From a user perspective it's not logical that one must download "prerecorded hints" to make the "_TTS cannot be started_" messages disappear.
PS2 Even with the "prerecorded hints" downloaded, and audio instructions set to "off", the cannot start TTS message keeps appearing upon starting a new navigation.

**Comment by Shituation** [comment]
I want to use TTS and the app sees no TTS even If I install the google one. Tried the one called "Sherpa TTS" and did not work (FOSS) either.

This app has a problem with synthesized voice, users that don't want it see an error and I that want it to work see the same error.

**Comment by sonora** [comment]
@ProBackup-nl I just happen to see
> Please try to not touch the Text-To-Speech service when sound is disabled in OsmAnd.

I have not tried, but if this is still true I would judge it is bug and probably worth opening a separate Issue here for it to get checked.

@Shituation I advise to open a new issue, this one being closed. They will probably guide you through providing log files then for that to be checked out properly.

**Comment by Shituation** [comment]
fixed it with an older version of sherpa tts. Google tts and latest sherpa tts engines do not work in lineage since they crash the settings. I think that the problem may be lineage OS 22.
