### ISSUE TITLE
Tram rails are rendering below roads in Driving profile

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#20833]
### How to reproduce
* Switch to any Driving profile
* Go to `52.51894° N, 13.39045° E`

### Actual result
<table style="width:100%">
  <tr>
    <th>Pedestrian</th>
    <th>Car</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/d80b891d-d2a4-49ce-8318-4de5af813ccf"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/287bf527-daf7-4916-9710-0472aad80455"  width="300" height="auto"/> </td>
  </tr>
</table>   

* Tram rails are below roads

### Expected result

* Tram rails visible above roads

**Environment**
OsmAnd Version: OsmAnd~ 4.9.0#3179m, released: 2024-09-12
Android: 15
Device model: Google Pixel 6A

**Comment by xmd5a2** [comment]
Fixed. No new maps required.

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.9.0#3289m, released: 2024-09-26
tram roads are visible above roads when using car profile

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/1685f0ee-c531-4694-9d2a-6bb14c871297"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/66790d7f-c3b7-40ac-b6e8-176b9f258ca9"  width="300" height="auto"/> </td>
  </tr>
</table>
