### ISSUE TITLE
Using webp for all res images?

### ISSUE THREAD

**Issue by Self-Perfection** [osmandapp/Osmand#2083]
Osmand apk with last releases inflates rapidly. :(

I've checked latest release apk contens and it looks like it carries several screenshots in webp format, therefore I conclude OsmAnd is able to recode webp images.

But most of images are stored as png. As an experiment I tried to recompress them as webp in lossless mode:
```
shopt -s globstar
for f in **/*.png; do
    cwebp -lossless  -o "${f%.png}".webp "$f" && rm "$f"
done
```
Uncompressed res directory size was reduced by 6MB:
```
$ du -sb osmand_*/res
17163415        osmand_png/res
11262620        osmand_webp/res
```
However it looks like png images are compressible a bit, so in zip archive space savings is just 4 MB:
```
$ ls -1s osmand_*/res.zip
17484 osmand_png/res.zip
13656 osmand_webp/res.zip
```

Switching to lossless webp for resources seems like an rather easy and effective optimization for me.

**Comment by vshcherb** [comment]
We don't think it is critical for now.
