### ISSUE TITLE
It´s not possible to set user defined track colors (android release AND nightlies), followed by a crash

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#20855]
### Description

I have a set of imported tracks. I want to change their color. Two different devices, two dofferent Osmand releases.

This is what happens in the ~4.9.0#3200m (but also before):

Though set to "red":
![Screenshot_20240917_041233_OsmAnd~](https://github.com/user-attachments/assets/ea52582b-068b-45cb-8115-e43bd8338085)

They look like this (blue, red, green):
![Screenshot_20240917_041441_OsmAnd~](https://github.com/user-attachments/assets/70dc132e-6f32-4041-bcf8-faab3a29373a)

Back in the editing mode I see this color selected at all tracks:
![Screenshot_20240917_041515_OsmAnd~](https://github.com/user-attachments/assets/c71b391e-d46c-4e9c-8b62-ace29fefdea5)

I change the color to green and apply:
![Screenshot_20240917_041527_OsmAnd~](https://github.com/user-attachments/assets/9aac53dd-054b-4f8b-bc9a-377391990a50)
![Screenshot_20240917_041540_OsmAnd~](https://github.com/user-attachments/assets/e3c3affd-1a30-4035-95ff-5387289582a4)

After closing the app and starting Osmand again, I´m back to the beginning:
![Screenshot_20240917_041621_OsmAnd~](https://github.com/user-attachments/assets/106e7ce3-7de2-4bb6-ae73-8616036a35f6)

And this is what happens in the Android Playstore release +4.9.0:

The same set of tracks, all set to "red":
![Screenshot_20240917_041830_OsmAnd+](https://github.com/user-attachments/assets/b704da9d-9c26-46fc-a664-4fb4692d3252)
![Screenshot_20240917_041816_OsmAnd+](https://github.com/user-attachments/assets/1525bd32-9074-4fa8-8d94-0f266a01ca9c)

I change one of them to "green":
![Screenshot_20240917_041854_OsmAnd+](https://github.com/user-attachments/assets/d0f980f5-4335-458f-982b-dde2170a9c62)
![Screenshot_20240917_041912_OsmAnd+](https://github.com/user-attachments/assets/91532de4-fbd5-4fed-8a60-9d5f5bb0ca9d)

Close Osmand and start it again, I´m back where I started:
![Screenshot_20240917_041936_OsmAnd+](https://github.com/user-attachments/assets/667ccd75-94ab-423a-977c-8bdaf2e9950e)
![Screenshot_20240917_041951_OsmAnd+](https://github.com/user-attachments/assets/5903b7b6-7ca5-4245-aed8-516449ccf3b5)

And going back to the editing mode, again I see this color selected (what I never did):
![Screenshot_20240917_050005_OsmAnd+](https://github.com/user-attachments/assets/e66de970-1de7-4496-ba08-ba302808cfcc)

While writing this text here, the +4.9.0 crashed:
[exception.log](https://github.com/user-attachments/files/17022441/exception.log)

[edit] the yellow color-picker perhaps is caused because of selecting tracks with different colors?

### Steps to reproduce

see above.

### Actual result

see above.

### Expected result

see above.

### Your Environment (required)

2x Galaxy S20+
Android 13
Osmand +4.9.0
Osmand ~4.9.0#3200m

**Comment by Rowin63** [comment]
All this, both described issues, don´t happen in the +4.8.6
There changes remain as done!

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce it, add three tracks to a folder and changing their appearance, specifically their color. After changing the color and confirming that the tracks reflect the changes, close the app entirely. Upon reopening the app, you will notice that the previously set colors are lost, and the tracks revert to the default red color.

OsmAnd~ 4.9.0#3203m, released: 2024-09-17

https://github.com/user-attachments/assets/234ac517-da03-4127-8574-b86e68540dc8

**Comment by arncor** [comment]
Same problem here on 4.9.0 (android9).
Osmand also doesn't remember track width and direction arrows, or even the list of tracks that are shown on the map.

**Comment by vshcherb** [comment]
Not reproduced any more
