### ISSUE TITLE
Car icon orientation sometimes get stuck during navigation with screen timeout enabled

### ISSUE THREAD

**Issue by Guylby** [osmandapp/OsmAnd#20858]
### Description

Hi,

During a long car trip recently I've noticed on three occasions that after the screen waking up to give directions, the car orientation cursor was stuck and not following the correct heading anymore.
The phone was plugged in so no battery optimization were on. 
One time the issue fixed itself after a few screen wake ups, other times it needed to restart navigation. 

This did not happen in previous versions of Osmand on my phone

### Steps to reproduce

Take a car trip with navigation with this screen control settings:
Use system screen timeout > OFF
Timeout after wake-up > 30 seconds
Proximity sensor > ON
Navigation instructions > ON
Power button > OFF

### Actual result

Here is a screen recording of the issue. Notice that panning the map so that it is not centered anymore on position fixes the issue momentarily. But the map centered to the position again gets the cursor stuck again. The itinerary line was also not starting on the cursor anymore:
<video src="https://github.com/user-attachments/assets/b8195191-8ff6-4212-bc37-e504efc89e63">

### Expected result

Map cursor follows current heading. 

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.9.0
Android/iOS version: android 13
Device model: Sony Xperia 10 III
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
The bug couldn't be reproduced. To reproduce, configure Screen control with system screen timeout off, timeout after wake-up at 30 seconds, proximity sensor on, navigation instructions on, and power button off. After waking up the screen, the location cursor continued to move along the route as expected.

OsmAnd~ 4.9.0#3203m, released: 2024-09-17


https://github.com/user-attachments/assets/4fd5c114-f908-4710-b297-8ff2e2b833ac

**Comment by efi99** [comment]
I have a somewhat similar problem. During navigation, the icon gets stuck about every 1-2 minute, it stops, as if I had stopped the car suddenly. After 5-6 seconds, it suddenly jumps forward to the correct position and continues to move normally.
It is as if there is suddenly no GPS signal, even though there is, the widget also indicates it, and other navigation applications also run normally on the same route.
The screen is always on.

**Comment by yuriiurshuliak** [comment]
The bug was reproduced during actual navigation. To reproduce it, switch the location source to Google services, set the map orientation mode to "North is Up," and select "Use system screen timeout" for the screen timeout option.

Begin navigating as the car starts moving, manually turn off the phone’s screen, and wait for a bit. Then, turn the screen back on with navigation active.

As a result, is that the arrow icon moves in a slow, jerky way, while the position icon stays locked in one orientation and keeps moving in that fixed direction.

Note: This behavior does not occur in simulation mode, only during real navigation. Here are the profile settings under which this was reproduced: [Driving (2).zip](https://github.com/user-attachments/files/17601113/Driving.2.zip)


OsmAnd~ 5.0.0#3623m, released: 2024-11-01

<table style="width:100%">
  </tr>
  <tr>
    <td> <video source src="https://github.com/user-attachments/assets/c0dfb721-dd5d-4d7e-ae37-f5970ff2b592"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/user-attachments/assets/f19db0fc-535a-4bfc-9817-fe74b0b806ca"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
@Guylby I tested the latest [nightly](https://osmand.net/docs/versions/nightly_versions) version with the @yuriiurshuliak  profile, which was used to reproduce the bug, and with the settings you specified—this bug is no longer reproduced.

**Comment by Guylby** [comment]
Thanks for the fix, I'll check during navigation but I'm sure everything's good now!

**Comment by vshcherb** [comment]
Probably this variable should be deleted - https://github.com/osmandapp/Osmand/blob/71dd64edc161e7989431d1eaa400b787a3507e0c/OsmAnd/src/net/osmand/plus/views/layers/RouteLayer.java#L472

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/commit/12f9b5ff1f25d384aa1d66f9be6740abe852cdd3

**Comment by Zirochkabila** [comment]
`OsmAnd~ 5.0.0#3860m, Released: 2024-12-02`

Not reproduce
