### ISSUE TITLE
Islands are displayed blue instead of yellow at zoom level 11 (worldmap only)

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#2086]
Island is displayed blue instead of yellow at zoom level 11. This only happens with worldmap (if singapore map is not installed).

This is possibly related with:
https://code.google.com/p/osmand/issues/detail?id=2497

Found with OsmAnd+ 2.2.4.

Zoom level 10 (good)
![singapore zoom level 10](https://cloud.githubusercontent.com/assets/6921696/12007841/8b5fcfb8-ac17-11e5-8ce7-f91e03695c50.png)

Zoom level 11 (bad)
![singapore zoom level 11](https://cloud.githubusercontent.com/assets/6921696/12007840/8b5fa308-ac17-11e5-9fbe-9a6ae57b38b0.png)

**Comment by xmd5a2** [comment]
Can't reproduce this particular case but I've seen some similar bugs.

**Comment by Norbert80** [comment]
@vshcherb
Why has this issue been closed?
