### ISSUE TITLE
Custom button icons in settings export/import

### ISSUE THREAD

**Issue by Velomeloman** [osmandapp/OsmAnd#20867]
### Description

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/e9a81531-6b8a-4cea-b2bf-b90aa52ddb48"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/b7818dc8-deed-4c69-a8c4-200794d56a38"  width="300" height="auto"/> </th>
  </tr>
</table>

Custom button icons resets to default after export + import settings. 

### Steps to reproduce

1. Add some custom buttons
2. Export settings
3. Import settings on new device or clear Osmand setup.

### Actual result

Icons of all buttons resets to default 

### Expected result

Icons of all buttons restores from osf file

### Your Environment (required)

```
OsmAnd Version: OsmAnd~ 4.9.0#3211m, released: 2024-09-17
```

**Comment by vshcherb** [comment]
Bug: export / import custom buttons don't save configured icons
