### ISSUE TITLE
Track line not rendered (or rendered behind)

### ISSUE THREAD

**Issue by Dollarius** [osmandapp/OsmAnd#20865]
### Description

In the latest nightly (4.9.0#3211m, released: 2024-09-17),
the gpx track line is not shown on the map, while the split-interval numbers are correctly displayed.
The track is possibly rendered behind some layers, but I could not figure out which ones because disabling all the overlays (3D relief, contour lines, etc.) did not make the track appear.

### Steps to reproduce

1. Import a new gpx file: no track is displayed on the map
<img width="296" alt="image" src="https://github.com/user-attachments/assets/810358cb-c973-473f-b270-e43910d947ad">

2. On appearance, set split interval 500m and colour red: red numbers appear, but the track is still invisible
<img width="297" alt="image" src="https://github.com/user-attachments/assets/93496aa6-539e-4db7-b3cc-92bf487de860">

3. Click edit track: the whole track appears as a dashed line (so the gpx is correctly recognised by the app)
<img width="294" alt="image" src="https://github.com/user-attachments/assets/0d2776b1-e0a0-41f6-a546-ee4b6c53edf7">

### Actual result

It is not possible to follow the gpx track

### Expected result

The track should be displayed on top.
It happened in a previous version (few days ago) that the track customisation was lost upon closing/reopening the app, possibly related to what described in the following, so the issue may be caused by very recent changes to the rendering code.
https://github.com/osmandapp/OsmAnd/issues/20855

### Your Environment (required)

```
OsmAnd Version: 4.9.0#3211m, released: 2024-09-17
Android/iOS version: 14
Device model: Samsung S23
```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce it, create a track and view it on the map.
You'll notice that the track line is missing; only the icons, including the start and finish points, are displayed on the map.

OsmAnd~ 4.9.0#3212m, released: 2024-09-18

https://github.com/user-attachments/assets/b588a929-48fa-470b-8362-64c604857e3b

**Comment by Andrewschenko** [comment]
It needs to be reproduced again due to the recent fix to [this issue](https://github.com/osmandapp/OsmAnd/issues/20772)
