### ISSUE TITLE
Reverse geocoding does not find named tracks or footpaths any more

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2087]
Subject says it all. Functionality should be restored, was useful for e.g hikers or in regions where named tracks are common, often as part of an address.

**Comment by vshcherb** [comment]
There were issues with using pedestrian profile for 1st level search, so now it is swtiched to well tested car profile and this doesn't include tracks and footpaths. The issue is valid, for now it is known issue rather than regression.

**Comment by sonora** [comment]
This commit, I guess: https://github.com/osmandapp/Osmand/commit/b06d004f77904de1ae471cd7828d7da309c98511. What were the issues? Prior builds seem to work ok?

**Comment by vshcherb** [comment]
The issues that geocoding based on footpath is mostly wrong in city. It is better to see "Near Beneluxbaan" rather than "Near fietspad 25"

**Comment by sonora** [comment]
Agreed. I suppose it is complex to have a 2-tier approach, i.e. try the ped profile as a fallback after the case the car profile results in "No address determined"? This would provide the proper result also for people out in the woods, who would be happy if their nearest hiking trail was properly discovered,

**Comment by vshcherb** [comment]
This issue is complex by itself. Imagine a road with access=no, it will be eliminated from the search, even though it could be 100% correct. I'm not that familiar yet with geocoding, though the main goal is to find the closest house, if it is far enough I actually don't know what should be shown, just the closest street or path. So looks like using the routing profiles to search roads may be not a good idea at all and it needs to changed.

**Comment by vshcherb** [comment]
I keep the issue open, but we need to focus on examples, please submit it here, so in case we find a solution we will have the tests.

**Comment by sonora** [comment]
First of all, I think what we have now  is fine for 90%+ of all users an use cases, hence this issue is not a priority issue at all.

The one use case I find we could cater for this: Rural areas, like forest or mountain areas, where people may want to find out what the nearest named trail or similar feature is, or (probably more often) if they are still on the (e.g. named hiking-) trail they want, by verifying that it says e.g. "Badger Mountain Trail #65" below "My Position" on the context menu card. And that functionality worked when we used the ped routing profile for searching, but I agree using ped had other issues.

So the idea is maybe using the ped profile in a second (subsequent) try of the geocoding search,using the very same code, just change the profile, if, and only if, the car profile resulted in "No address determined".

As far as the logic is concerned: I think it is fine like we have it now: <100m: House or street is displayed, 100m<d<500m : "Near <street>" is displayed, <500m nothing is displayed.

As far as examples for the "named trail" feature: They can be found on many maps with Alpine mountain ranges with a hiking trail system, likely no point in listing many locations here. But one as a reference is http://www.openstreetmap.org/way/111545980#map=15/46.21031/12.36919. where a hiker may appreciate "Sentiero CAI n. 905" being displayed (the name of the trail), rather than "No address determined" (For  location http://www.openstreetmap.org/#map=15/46.2103/12.3692).

**Comment by vshcherb** [comment]
Using the path is not really bad idea, but just using pedestrian profile is bad, cause it could filter out motorway or not accessible for pedestrian roads. It is quite unlikely  we would see really bad geocoding with profile that allows all the roads, but we don't have that profile, so I think that bug is mostly to create it.

**Comment by vshcherb** [comment]
I guess that issue is fixed, cause now we have a special section for geocoding https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#L822. Though I'm not sure if we want to add footway, but it is definitely worth to add pedestrian road (which I already did)

**Comment by sonora** [comment]
Finding named hiking trails was nice. But I guess it is ok, will be glad to test. Yes, lets close this, good enough for the next release.
