### ISSUE TITLE
Trip Recording plugin: Auto-record track during navigation does not record anything

### ISSUE THREAD

**Issue by david-gpu** [osmandapp/OsmAnd#20871]
### Description

When the *"Auto-record track during navigation"* option is enabled in the *"Trip recording"* plugin, no track is recorded.

### Steps to reproduce

Enable the *"Trip recording"* plugin. Click on its settings, then enable the *"Auto-record track during navigation"* option.

Now go back to the main menu. Click on the navigation icon on the bottom left corner. Select an arbitrary destination, then click *"Start"* on the bottom right.

### Actual result

Navigation starts, but no track is recorded. The *"REC"* icon stays gray, instead of turning red.

If you do click on the *"REC"* button, then recording does work as usual. The only issue is that it does not start automatically.

### Expected result

Trip recording should start automatically when the navigation *"Start"* button is pressed. The *"REC"* button should turn red.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.8.6
Android/iOS version: Android 13
Device model: Samsung A71
Crash-Logs: ?
```

**Comment by dmpr0** [comment]
Hi! Yes there was the issue in 4.8 release, it already fixed https://github.com/osmandapp/OsmAnd/issues/19905, you can install Beta version from Google Play: [OsmAnd](https://play.google.com/apps/testing/net.osmand) or [OsmAnd+](https://play.google.com/apps/testing/net.osmand.plus  )
