### ISSUE TITLE
Touring style: Cycle paths in night mode hardly visible

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#20872]
### Description

<table style="width:100%">
</th>
    <th>Touring style in night mode:
    <th>OsmAnd style in night mode:</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/a884ef64-6e83-442c-8857-c2aa6e5cac05"  width="400" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/dca702f3-6ba0-4531-939d-22d681cec809"  width="400" height="auto"/> </td>
  </tr>
</table>   

### Your Environment (required)

```
OsmAnd Version: 4.8.6
```

**Comment by sonora** [comment]
I'm not sure what a good solution is. The contrast used in Touring view is consistent with that of other tracks across most map situations. Choosing a brighter color creates contrast issues in frequent situations where cycle tracks lead along highways, compare these screenshots of Touring View vs. OsmAnd.

![3](https://github.com/user-attachments/assets/32d5afb7-53e0-4b2d-98f6-0f7c8f1e05a3) ![2](https://github.com/user-attachments/assets/ad0d54e6-4bc9-48f7-b3f8-7f6c152b8351)

Overall, I am not sure how much priority should be really given to cycle paths in night view. Probably, they should definitely not outshine other routes more regularly viewed and used with a night view?

**Comment by scaidermern** [comment]
> Overall, I am not sure how much priority should be really given to cycle paths in night view.

With the bicycle profile being enabled, they should get a high priority I guess. The styles are profile-aware, aren't they?

**Comment by scaidermern** [comment]
But maybe it's just my phone's display that is currently dying 😕

**Comment by sonora** [comment]
Let me know if it's a real showstopper for you also on a new device. I hardly have a use case for the bicycle profile in night mode... 😉 Also: We need to look at the situation at night. What seems as too low contrast in daylight is sometimes the right contrast in darkness.

Yes, you can make features of a map style profile-dependent. I have always kept this to a minimum, as it complicates the code, all testing, and the user perception of what's going on if too many things like colors not only change between day/night but also between profiles... 

Probably there is some middle ground in lighting the cyclepath/cycleway/etc. color some for the bike profile at night, but not too much to create the effect I demonstrate above. Main effort after coding is finding/testing the right nuance. And surprisingly, things have been like this for some 10 years now, never drew any feedback so far ... (but not saying you are wrong :wink:)

**Comment by scaidermern** [comment]
I'll check again when I have a replacement device. Will probably take about two weeks since I'm currently on vacation 🙂

**Comment by sonora** [comment]
No rush, my vacation is coming up next, too!

**Comment by mikehgentry** [comment]
For what it's worth I use night mode for cycling sometimes (in the day!), higher contrast can make it easier to read in bright sunlight.

**Comment by sonora** [comment]
Thanks for the heads-up! So how would you rate the cyclepath and cycleway contrast on average, is it sufficient?

**Comment by mikehgentry** [comment]
I will test that properly at some point when the sun reappears (which could be a while! \#British problems)

**Comment by sonora** [comment]
I have brightened the night cycleway night color by ten percentage points - perhaps that does the trick!   :wink:
