### ISSUE TITLE
Tag:emergency=ses_station is discouraged

### ISSUE THREAD

**Issue by Almorca** [osmandapp/OsmAnd#20883]
### Description

Tag tag emergency=ses_station is discouraged, use [emergency](https://wiki.openstreetmap.org/wiki/Key:emergency)=[disaster_response](https://wiki.openstreetmap.org/wiki/Tag:emergency%3Ddisaster_response) instead

### Steps to reproduce

Search emergency

### Actual result

Ses_station is sugested

### Expected result

Emergency=disaster_response must be sugested and show in the map

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
https://taginfo.openstreetmap.org/tags/emergency%3Ddisaster_response#overview

**Comment by vshcherb** [comment]
Yes we need to replace ses_station to disaster_response

**Comment by xmd5a2** [comment]
Fixed. Maps will be regenerated in a couple of days.

**Comment by dmpr0** [comment]
# Review

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/5c69b496-4105-45e6-830d-9effda8f7018"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/5b9e8a39-0a8d-49bd-b2b8-38de6bfc1f42"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/0ff51f10-ef89-440e-8f4f-0968ef30b29b"  width="300" height="auto"/> </td>
  </tr>
</table>  

Tested on Berlin map from 01.10.2024

- [ ] Building with this tag doesn't have info about [disaster_response](https://wiki.openstreetmap.org/wiki/Tag:emergency%3Ddisaster_response)
- [ ] Node doesn't visible on the map? https://www.openstreetmap.org/node/3892599896#map=19/52.578056/13.352938
- [ ] Search, show SEC Station, after selection as Nautical

**Comment by xmd5a2** [comment]
Fixed. No new maps required.

**Comment by EugeneZmeuk** [comment]
Two icons are not load for [barriers (map legend)](https://osmand.net/docs/user/map-legend/osmand/#barriers):

<img width="762" alt="Screenshot 2024-10-21 at 13 03 42" src="https://github.com/user-attachments/assets/e01d6414-2f1d-4a1b-b6a8-78567700bdf3">

**Comment by vshcherb** [comment]
- [ ] Fix legend
