### ISSUE TITLE
Osmand slows down when turning on the track and coloring by speed and height

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#20889]
### Description

I have a track with a lot of points. When trying to display the track and color it by speed/height, osmand slows down, a system window constantly appears with a suggestion to wait or kill the process.
However, there are no such problems on rendering engine 1.
Link to track in telegram chat:
https://t.me/ruosmand/161961

### Steps to reproduce

Download my track recorded by osmand, open it, change the coloring according to the speed, turn on the arrows.

### Actual result

Slows down.

### Expected result

Works fast.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd~ 4.9.0#3258m, Дата выпуска: 2024-09-23
Android/iOS version: 13
Device model: poco f3
Crash-Logs: ?
```

**Comment by vshcherb** [comment]
- [ ] No logs start / end process (issue to understand)
- [ ] UI thread is frozen (critical issue)
- [ ] Very slow initialization for 500 tracks on start

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/commit/41a6e880c29be69c6abc6072e12265e53db05776
