### ISSUE TITLE
OsmAnd has no logical provision to search for roads

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2088]
By definition, a "POI" is a point; not an open way (=road).
Therefore, if I want to search for a specific road, I would not be using the "POI search" screen.
 
Unfortunately, OsmAnd does not provide any other screen for such a search.

Try searching for "Parijatha", which is a road in Bangalore. OsmAnd fails to find it.

Now try the same search in openstreetmap.org website (Nominatim search).
It shows the road with an orange line. 

OsmAnd should be able to find the road in similar way (preferably with offline search, but if that is not possible, through Nominatim search).

**Comment by sonora** [comment]
Deprecated with new search interface, I think.
