### ISSUE TITLE
Feature Request: Focus on "key" field in newly added tag

### ISSUE THREAD

**Issue by yuriiurshuliak** [osmandapp/OsmAnd#20896]
### Discussed in https://github.com/osmandapp/OsmAnd/discussions/20311

<div type='discussions-op-text'>

<sup>Originally posted by **OpenOrangeData** July 15, 2024</sup>
I've been using (and recommending) OsmAnd+ for years now and although for beginners some aspects may be hard to grasp, I'm really happy with most of its features - thanks for the great work!

The following is related to the **Plugin "OpenStreetMap editing"**:
Recently, I've been editing OSM very often through OsmAnd+. It works well for keys/values that I already know by heart, however, what would really help to speed up editing would be if the cursor would automatically "jump" (focus) to the "key" field once I hit the button "add tag". 
Currently, an empty tag is added and automatically scrolled to, so that the user/editor can see it (so far so good), but the cursor is stuck in the field which was edited last (unwanted behaviour) instead of letting me directly type the key of the new tag.

Currently I often think I'm already in the new key and continue typing, only to discover that I'm actually adding letters to an old tag which
makes it invalid. E.g. I already marked a bicycle parking, then I want to add "covered = yes", but instead of writing "covered" in the new tag, it turns out I'm accidentally producing the value "Bicycle parking**covered**".

Is this feature (from my perspective almost a bug ;-)) something you're already working on?</div>

**Comment by vshcherb** [comment]
I didn't reproduce it.

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. To reproduce  the issue, try the following steps: click on any POI, choose "Actions," then select "Create POI" or "Modify POI." Next, go to the "Advanced" tab and click "Add tag."

In my case, the cursor automatically focuses on the selected field, and everything functions as expected.

[@OpenOrangeData](https://github.com/OpenOrangeData), could you please share a video showing the issue from your side?

OsmAnd~ 4.9.0#3300m, released: 2024-09-27

https://github.com/user-attachments/assets/d950dfbc-6422-493f-9c03-73c8e79e52e7
