### ISSUE TITLE
Add option (de-)activate maps for regions in map view 

### ISSUE THREAD

**Issue by quelbs** [osmandapp/Osmand#2089]
If a map is downloaded but deactivated and you tap on a region being offline, the only option is "download" although this is not possible being offline. The existing deactivated map of the region is not offered to be activated here. You need to go to the "local" tab in the map management.

The same is true the other way round if you activate an active region (with green overlay) you have a button "Download". It would be much nicer to have a deactivate option here.

If you are online and select a deactivated region there is a check for updates of the map and for inactive maps it is offered to "Download" or "Delete" them, but not to activate them. If the deactivated map is out of date "Update" and "Delete" are offered. In both cases the "Activate" option would be nice to have.
For active regions the Download option is also shown with no need to be shown, because the map is up to date and active already (see issue #2073).

**Comment by vshcherb** [comment]
We need to redesign UI to add this functionality

**Comment by sonora** [comment]
I think this is related to #2156, see my suggestion there.

**Comment by quelbs** [comment]
2dfd2bd does fix the activate part of this request. I do not see a need for the deactivate part as there are two other intents already for active maps. Thank you @crimean for the fix!
