### ISSUE TITLE
Build Fails

### ISSUE THREAD

**Issue by sapstern** [osmandapp/OsmAnd#20907]
### Description

Since recently (Last successful build on my side was on September 14.) build fails.
The java jni class net.osmand.core.jni.MapObjectList seems to be missing.
I tried to locate the place where these jni classes are defined, but could not find it.
Here is the error:
> Task :OsmAnd:compileNightlyFreeLegacyFatDebugJavaWithJavac
/home/matthias/gitOsmAnd/android/OsmAnd/src/net/osmand/core/android/MapRendererContext.java:26: error: cannot find symbol
import net.osmand.core.jni.MapObjectList;
                          ^
  symbol:   class MapObjectList
  location: package net.osmand.core.jni
/home/matthias/gitOsmAnd/android/OsmAnd/src/net/osmand/plus/views/layers/geometry/GeometryWayDrawer.java:337: error: cannot find symbol
                                line.setStartingDistance(startingDistance);
                                    ^
  symbol:   method setStartingDistance(float)
  location: variable line of type VectorLine
/home/matthias/gitOsmAnd/android/OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java:2448: error: cannot find symbol
                        mapRenderer.enableBatterySavingMode();
                                   ^
  symbol:   method enableBatterySavingMode()
  location: variable mapRenderer of type MapRendererView
/home/matthias/gitOsmAnd/android/OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java:2450: error: cannot find symbol
                        mapRenderer.disableBatterySavingMode();
                                   ^
  symbol:   method disableBatterySavingMode()
  location: variable mapRenderer of type MapRendererView
/home/matthias/gitOsmAnd/android/OsmAnd/src/net/osmand/core/android/MapRendererContext.java:700: error: cannot find symbol
                MapObjectList polygons = mapPrimitivesProvider.retreivePolygons(point, zoomLevel);
                ^
  symbol:   class MapObjectList
  location: class MapRendererContext
/home/matthias/gitOsmAnd/android/OsmAnd/src/net/osmand/core/android/MapRendererContext.java:700: error: cannot find symbol
                MapObjectList polygons = mapPrimitivesProvider.retreivePolygons(point, zoomLevel);
                                                              ^
  symbol:   method retreivePolygons(PointI,ZoomLevel)
  location: variable mapPrimitivesProvider of type MapPrimitivesProvider
/home/matthias/gitOsmAnd/android/OsmAnd/build/generated/aidl_source_output_dir/nightlyFreeLegacyFatDebug/out/net/osmand/aidl/IOsmAndAidlInterface.java:526: warning: [dep-ann] deprecated item is not annotated with @Deprecated
    @Override public boolean setNavDrawerLogo(java.lang.String imageUri) throws android.os.RemoteException
                             ^
/home/matthias/gitOsmAnd/android/OsmAnd/build/generated/aidl_source_output_dir/nightlyFreeLegacyFatDebug/out/net/osmand/aidl/IOsmAndAidlInterface.java:2830: warning: [dep-ann] deprecated item is not annotated with @Deprecated
      @Override public boolean setNavDrawerLogo(java.lang.String imageUri) throws android.os.RemoteException
                               ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
6 errors
2 warnings

> Task :OsmAnd:compileNightlyFreeLegacyFatDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':OsmAnd:compileNightlyFreeLegacyFatDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.

BUILD FAILED in 1m 44s
97 actionable tasks: 87 executed, 10 up-to-date

### Steps to reproduce

Follow the build instructions under 'How to Compile the Android Version' and start the build with ../gradlew assembleNightlyFreeLegacyFatDebug.

### Actual result

Error, see above.

### Expected result

Assembled apk OsmAnd-nightlyFree-legacy-fat-debug.apk in target folder.

### Your Environment (required)

Build on Linux:

NDK: 27.0.12077973
SDK Tools: 26.1.1
SDK Platform Tools: 35.0.2
[build.txt](https://github.com/user-attachments/files/17145370/build.txt)

**Comment by vshcherb** [comment]
Did you try to run with --refresh-dependencies?

**Comment by sapstern** [comment]
Perfect, thanks, that was it
