### ISSUE TITLE
Search for a type of POI and show them on map. This causes display of duplicate POIs.

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2090]
Search for a type of POI (e.g. "Finance")
Tap on "Show all search results on map" button. 

Now the POIs are marked on the map.
But the OSM itself also shows the same POIs already (icon and label).
Thus each POI is displayed twice (duplication of both icon and label). 

Often the two labels overlap, making it difficult to read.

**Comment by xmd5a2** [comment]
Possibly that you mean that issue https://github.com/osmandapp/Osmand/issues/2121

**Comment by sonora** [comment]
Also: Please double-check that you do not have 2 ("regular") maps activated concurrently which cover the same region, see Issue #2101. If this is a common issue for many users, we may have to somehow prevent this in our code, or produce a warning.

**Comment by raindropsfromsky** [comment]
I have only one India obf, so the possibility of two maps being active is ruled out. 

Also, the overlapped POI labels appear only when the ***Show all search results on map*** button is pressed. But if we have two maps concurrently displayed (IINW one of them as underlayer?), they would show at all times.

Specifically, OSM already has labels for all POIs. On top of that, OsmAnd places labels. This makes a dense cloud of overlapping labels, where you cannot read most of the labels.
![screenshot_2016-01-14-11-02-49](https://cloud.githubusercontent.com/assets/9047168/12316624/d7df6902-baae-11e5-90fa-7a1af99b1c3a.png)

As you zoom in, the POI marker placed by OsmAnd starts separating from the OSM's marker for the same POI (WHY?? They should be at the same spot on map!). Thanks to this separation, it is possible to read both labels.
![overlap in poi labels](https://cloud.githubusercontent.com/assets/9047168/12316694/ae298f06-baaf-11e5-9b2a-ceb1202bdae8.png)

***Desired:*** At low zooms, show only the POI markers. 

Actually the user selects the ***Show all search results on map*** button only when he is NOT searching for a particular POI by name. (He may select a POI based on location/proximity.) Therefore if it OK if OsmAnd does not show labels in this mode.

**Comment by raindropsfromsky** [comment]
oops!

I just discovered that this control is already provided to the user, in the form of a ***Point labels*** check box. 

I may have missed it because this control appears in the ***Configure map*** screen rather than ***Configure screen*** screen. Markers for POIs and favorites should be considered as screen elements (just like points on the route). They are not map elements.

**Comment by vshcherb** [comment]
Known issues:
1) POI have different coordinates - not planned to be fixed soon.
2) Too much text producing is a known issue and is already in backlog.
