### ISSUE TITLE
External input device : customizable Wunderlinq profile

### ISSUE THREAD

**Issue by Buzzz57** [osmandapp/OsmAnd#20908]
### Describe the idea

At the moment, in the menu for the external inputs, you can either :
- select the Wunderlinq profile, but it contains only 3 commands and you can't customize it with other commands
- create a custom profile, but then you can't affect the specific Wunderlinq command "OpenWunderLINQDatagridCommand.ID" because it's not available in the list of commands.

### Expected behaviour

Ideally, you could customize an existing profile (ie. Wunderlinq profile), or be able to find specific commands to add to a custom profile.

### Alternatives you've considered

I don't see which alternate method I could use...

**Comment by dmpr0** [comment]
## ToDo

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/ae7894e3-cbcf-4e13-9a32-4191a4663491"  width="300" height="auto"/> </td>
  </tr>
</table>   



- [ ] Add new action – `Open – WunderLINQ Data grid`
- [ ] Icon – 
- [ ] Add to **Interface** group
