### ISSUE TITLE
The "Directions" dialog shows green circle for any start point that is not the current location

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2091]
Follow these steps:

Open the "Directions" dialog, and select any point on map as starting point (favorite, select on map, address). Similarly, select any destination point.

Now look at the icon used for the "From" point. Although this point is NOT the current location, OsmAnd still shows the green circle for it.

**Desired:** OsmAnd should use a different icon for the start point if it is not the current GPS fix.

**Comment by sonora** [comment]
Fixed. Showing map marker icon now for all other start points.
