### ISSUE TITLE
The "Live updates" feature shows confusing date label for the updates

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2092]
I selected the Live update feature, and then selected "update now". 
The download summary (the orange/black progress bar) shows two map updates below it.
If I tap on it, a dialog pops up showing two distinct downloads.

Bug#1:
The two updates are labeled as follows--
India Asia 15 12 00
India Asia 15 12 29

Only the second update makes sense (It is dated 29th December 2015).
But what is the first update?? There cannot be a "00" date!

Bug#2: 
The dialog showed the status as "Last map change: Dec 3, 2015"
Then how come it has two updates, dated 29th Dec 2015 and one other?

Bug#3:
Even after both updates, the "Last map change" status has not changed.
It still shows 3rd Dec 2015.

**Comment by vshcherb** [comment]
Work in progress...
