### ISSUE TITLE
bearing widgets do not work

### ISSUE THREAD

**Issue by spongebyte** [osmandapp/OsmAnd#20935]
### Description

The bearing widgets do not seem to work.
(My phone does have a compass and using "compass direction" as map orientation works fine.)

### Steps to reproduce

Hamburger menu > Configure screen > Right panel > Bearing > tick all 3.

### Actual result

Nothing is shown on the screen, even though other widgets show up just fine.

### Expected result

I want to see the bearing in a widget.

### Your Environment (required)

OsmAnd Version: OsmAnd~ 4.8.6
Android/iOS version: LOS 21 / Android 14
Device model: Pixel 6a

**Comment by yuriiurshuliak** [comment]
The bug could not be reproduced. The widgets are visible during navigation. When you add the Bearing widget and enable navigation, everything functions as expected. To display the bearing, make sure a target point is selected.

OsmAnd~ 4.9.0#3300m, released: 2024-09-27


https://github.com/user-attachments/assets/e6b06975-c288-4c8c-9d0b-67051ad31bf2

**Comment by spongebyte** [comment]
Thanks for your response. Sincere apologies, I hadn't realised that the bearing widgets are active during navigation only.

What I'm after is a compass widget, I'd like to display the compass bearing of my phone.

Can we keep this open as a feature request please?

Thank you.

**Comment by spongebyte** [comment]
There seems to be a feature request already for this: https://github.com/osmandapp/OsmAnd/issues/20304

Closing this.
