### ISSUE TITLE
Gaps in contour along Kizilsu, Xinjiang, China - Tajikistan border

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#20932]
## Description
Previous issue with contour lines in China https://github.com/osmandapp/OsmAnd/issues/20457

### How to reproduce
* Go to Menu – Maps & Resources – Asia – China – Xinjiang – Kizilsu
* Download contour lines 
* Go to map screen, open map at:
*  * First place – `38.46087° N, 74.76916° E` 
*  * Second place – `38.64752° N, 74.18061° E` 

### Actual result

<table style="width:100%">
  <tr>
    <th>Kizilsu contours</th>
    <th>Kizilsu + Tajikistan contours</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/d7dbd9f4-66ac-4305-95dc-4ca59ac063e0"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/3b7fa3cb-5f95-4f9e-99ae-2c2ea9b64643"  width="300" height="auto"/> </td>
  </tr>
</table>  

### Expected result

* Contours without gaps

**Comment by Zirochkabila** [comment]
# Testing 1
`OsmAnd~ 5.0.0#3985m, Released: 2024-12-23` - Fixed (m/ft)
`4.9.2.4929` - Fixed (m/ft)

**Kashgar** maps should be downloaded



<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/ff009610-ac8f-46fe-98e8-4725d11bd457"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/140231a9-9c60-469d-be73-921f5346d9d6"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/3fead14e-ef05-48de-bfec-eaf098cb5416"  width="600" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/673460b6-0d8b-49b1-bc5b-a1415b89f1a5"  width="600" height="auto"/> </th>
  </tr>
</table>
