### ISSUE TITLE
Replace the default OsmAnd vector maps rendering engine with something like Maplibre

### ISSUE THREAD

**Issue by quickfixdemon** [osmandapp/OsmAnd#20930]
### Describe the idea

The default OsmAnd vector maps rendering engine is terrible at its job. Even if I switch to offline vector maps, it glitches constantly and pixelates. I can see pixels and glitching at higher zoom levels. Compared to other maps, this experience is terrible. Therefore, I suggest OsmAnd switch to MapLibre as the default rendering engine.

### Expected behaviour

_Expected behaviour:_
When I zoom in or out, no glitching, pixelation or lag should occur.
_Actual behaviour:_
When I zoom in or out, it glitches, pixelates and takes time to load map tiles.

### Alternatives you've considered

I don't see any alternatives worth considering.

**Comment by scaidermern** [comment]
It might be worth investigating this option.

OsmAnd's rendering engine is quite slow. Switching to a (presumably) faster one that is developed externally could improve rendering speed while reducing development resources at the same time.

This option is only valid if Maplibre is equally powerful.

**Comment by quickfixdemon** [comment]
> It might be worth investigating this option.
> 
> OsmAnd's rendering engine is quite slow. Switching to a (presumably) faster one that is developed externally could improve rendering speed while reducing development resources at the same time.
> 
> This option is only valid if Maplibre is equally powerful.

Maplibre is very fast and very powerful, it doesn't drop a frame no matter how fast you zoom in, out or around the map. You can have a look at MapLibre in a few ways:
1. Use SCEE version 59.0 from F-droid(they recently changed their map implementation of MapLibre and version 59.0 has that update
2. Download the Wikipedia app from F-droid and go to More -> Places. You will see Wikipedia's MapLibre implementation.
3. OpenHistoricalMap uses MapLibre.
Take a look at the implementations mentioned above.
Please implement MapLibre in OsmAnd, the default rendering engine is just terrible.

**Comment by scaidermern** [comment]
> Disagree, opengl rendering engine works pretty smooth. I don't see any pixelation.

Compare a densely populated area such as London in OsmAnd vs StreetComplete. You will see a noticeable difference in rendering speed, although both use vector tiles. Even with OpenGL OsmAnd becomes very sluggish on my Samsung S9.

**Comment by Nine-Tailed** [comment]
Something really needs to be done about the osmand rendering performance, unfortunately the rendering engine 2 did not live up to expectations. It's like a fly in the ointment.

**Comment by quickfixdemon** [comment]
I think the other comments here oppose that. The OpenGL rendering engine isn't smooth at all, and it does pixelate. I'm on the latest Android version(14) and it is terrible. I've tested it on my other device(same android version, different skin and manufacturer)

**Comment by satmandu** [comment]
Maplibre now supports Vulkan on Android:

https://maplibre.org/news/2024-12-12-maplibre-android-vulkan/

**Comment by tjmoore** [comment]
> Disagree, opengl rendering engine works pretty smooth. I don't see any pixelation.

Diasgree. opengl rendering is terrible on a lot of devices, and in my experience it doesn't have to be a dense area. Mid range type devices. Shouldn't need a top end device to make it useable especially as some other mapping apps have smooth rendering on the same devices.

Switch to v1 and it's smooth, but missing some features sadly.

Also see #22408, though it refers to high end and places like Tokyo but I see it just about everywhere with a mid range device.

**Comment by quickfixdemon** [comment]
@vshcherb please reconsider switching to MapLibre or at the very least making the default OsmAnd map rendering engine smoother. Everyone in this comments section unanimously agrees that the performance of the default OpenGL rendering engine is absolutely terrible. Please reconsider.

**Comment by quickfixdemon** [comment]
Also, please keep in mind that the latest versions of Android are set to replace OpenGL ES with Vulkan eventually. Please do take notice of this issue.
