### ISSUE TITLE
If Live updates are available for any map, OsmAnd should show a yellow icon for it

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2093]
I have selected the "Live updates" feature, and right now I am downloading two live updates for India.

But I also noticed that OsmAnd shows a green icon in the "India" row, meaning the map is updated.
This is obviously not correct.

**Desired:** If there are any live updates for a map, a yellow icon should be displayed against it.

Or design a new overlay to denote "live update(s) available for this map!"

**Comment by vshcherb** [comment]
@sonora is approaching simplification for these layers in a different issue, I think it makes sense to avoid such confusions.

**Comment by sonora** [comment]
Very hard (and obscure) to depict too many different states by color-coding them as a map overlay. Simplification s probably better than overcomplicating here, see #2156.
