### ISSUE TITLE
Broken Favorites gpx inside Export.osf

### ISSUE THREAD

**Issue by Velomeloman** [osmandapp/OsmAnd#20934]
### Description

All favorites containing gpx files inside exported osf have incorrect header and xml tags. Impossoble to save Favorites to osf and import it later.

### Steps to reproduce

Settings - Export to file - My places - check Favorites - Export

### Actual result

Corrupted gpx inside osf

### Expected result

Correct gpx that can be imported properly

### Your Environment (required)

```
OsmAnd~ 4.9.0#3301m, released: 2024-09-27

```

**Comment by yuriiurshuliak** [comment]
Can you specify which version of Android you're using?

If you're on Android 14, it may not be reading the files correctly, which could be causing this issue. It's related to unzipping GPX files on Android 14. A fix for this should be included in future updates.

**Comment by Velomeloman** [comment]
EMUI 14.2 based on Android 12

**Comment by alex-osm** [comment]
@Velomeloman could you please attach OSF with one or few such favorites?

**Comment by Nine-Tailed** [comment]
this is the favorites file unpacked from osf:
![tmp.zip](https://github.com/user-attachments/files/17163419/tmp.zip)

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/commit/a9e4f8782edca284362c9179d8003e001f3dcc52

**Comment by RZR-UA** [comment]
To Do:

- [ ] search/cleanup corrupted files in the Cloud
- [ ] test OsmAnd Web Backup (verify GPX-files correctness)
