### ISSUE TITLE
OsmAnd Cloud Start does not work with F-Droid builds

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/OsmAnd#20945]
### Description

Registering works but synchronization fails with an error toast.

![grafik](https://github.com/user-attachments/assets/48593665-42ab-4e2e-bc27-d7df6aca3c3c)

OsmAnd~ 4.8.5 from F-Droid

### Steps to reproduce

- Tap on Synchronization

### Actual result

- Error Toast about missing subscription

### Expected result

- No error.

### Your Environment (required)

See above.

**Comment by yuriiurshuliak** [comment]
We don’t handle F-Droid app builds since we only support official platforms. Please reach out to the app developer on F-Droid for assistance.

**Comment by vshcherb** [comment]
It's probably not correctly built, as it tries to enable all Pro features however OsmAnd Cloud subscription is checked on the server side. So it won't work, we build special OsmAnd~ nightly build that could be checked

**Comment by Norbert80** [comment]
@vshcherb why don't you offer Pro subscriptions without Google? There are many users who like to support development but do not like to obtain apps from Google Playstore.

**Comment by vshcherb** [comment]
We don't have the way to work with people, so we can process payouts only from business entities
