### ISSUE TITLE
Sometimes osmand crashes with the message native library is not supported

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#20944]
### Description

Sometimes osmand crashes with the message native library is not supported.
[exception.log](https://github.com/user-attachments/files/17176685/exception.log)

### Steps to reproduce

.

### Actual result

.

### Expected result

.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:OsmAnd~ 4.9.0#3308m, Дата выпуска: 2024-09-28
Android/iOS version:13
Device model:poco f3
Crash-Logs: ?
```

**Comment by vshcherb** [comment]
There are multiple crashes related to slider values but likely they are not related to crash that Native library not supported. 
For slider crash it's probably related to Vertical Exaggeration somehow as it values from 0-4 or something similar
```
java.lang.IllegalStateException: Slider value(333.0) must be greater or equal to valueFrom(0.0), and lower or equal to valueTo(4.0)
	at com.google.android.material.slider.BaseSlider.validateValues(BaseSlider.java:575)
	at com.google.android.material.slider.BaseSlider.validateConfigurationIfDirty(BaseSlider.java:628)
	at com.google.android.material.slider.BaseSlider.onDraw(BaseSlider.java:1771)
	at android.view.View.draw(View.java:23845)
	at android.view.View.updateDisplayListIfDirty(View.java:22682)
```

**Comment by Nine-Tailed** [comment]
Problem with slider it concerns filter in smart folder. For it already created issue.
https://github.com/osmandapp/OsmAnd/issues/20918
