### ISSUE TITLE
Route line colored by elevation/slope does not follow cursor

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#20941]
### Description

Route line colored by elevation/slope does not follow cursor. I only checked it in simulation mode, I didn’t check it in reality, it’s raining outside.
Video in telegram chat:
https://t.me/ruosmand/162620

### Steps to reproduce

Set up route line coloring by slope/elevation, run navigation simulation.

### Actual result

route line does not follow cursor

### Expected result

the route line should follow the cursor

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:OsmAnd~ 4.9.0#3308m, Дата выпуска: 2024-09-28
Android/iOS version:13
Device model:poco f3
Crash-Logs: ?
```

**Comment by Andrewschenko** [comment]
Applied [https://github.com/osmandapp/Osmand/commit/aab44b70824c80b9d33fc683ed1296407e51ac28](fix) for static route line in legacy renderer, which also removes gap when location animation is disabled.

**Comment by dmpr0** [comment]
Unable to review

**Comment by vshcherb** [comment]
? Start navigation with Route line colored by elevation/slope
