### ISSUE TITLE
Osmand generates blank instruction during routing

### ISSUE THREAD

**Issue by Guylby** [osmandapp/OsmAnd#20955]
### Routing engine

- [X] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Hi,

During a recent road trip I noticed once that Osmand gave me a "blank" instructions, that is there was an instruction, but it displayed nothing:

<img src="https://github.com/user-attachments/assets/dc85af49-eaf5-4e7d-b162-f50c5570ae8c" width="50%">

It can be reproduced on test.osmand/map with this settings:
Start point 43.126341, 5.925193
End point 43.128418, 5.916958
https://test.osmand.net/map/navigate/?start=43.126341,5.925193&end=43.128418,5.916958&profile=car#18/43.12789/5.91935

<img src="https://github.com/user-attachments/assets/f2cd7432-b4e1-4944-a1fd-e88339ae174e">

### Start and end points

Start point 43.126341, 5.925193
End point 43.128418, 5.916958
Using the standard Osmand car profile

### Actual route

Blank routing instruction is provided

### Expected route

Detailed routing instruction is provided

### Maps you used (online or offline)

- [X] Offline maps offered within the OsmAnd app for download. 
- [ ] Online (tile / raster) maps 

### Your Environment

```
OsmAnd Version: 4.8.6 (was 4.9.0 during the trip)
Android version: 13
Device model: Sony Xperia 10 III

```

**Comment by yuriiurshuliak** [comment]
The bug has been successfully reproduced. When using the [web version of the route](https://test.osmand.net/map/navigate/?start=43.126341,5.925193&end=43.128418,5.916958&profile=car#18/43.12756/5.91945) and clicking on the navigation instruction, it shows "net.osmand.router.TurnType@159bb08c onto D N8 and go 0.1 km. Way 30841933."

This results in an empty instruction with no specific turn details or guidance.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/b35b7378-a114-48a2-9f80-9a9e5a76142c"  width="500" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
@Guylby Bug has been fixed

**Comment by Guylby** [comment]
Can confirm on my end that instructions are now correctly provided, thanks for the fix!
