### ISSUE TITLE
Google Street View link

### ISSUE THREAD

**Issue by luigifab** [osmandapp/OsmAnd#20960]
### Describe the idea

When you display information of anywhere, you get the coordinates and some other information.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/5cc9ca01-2044-4eb8-8421-04c0c1c14ef0"  width="300" height="auto"/> </th>
  </tr>
</table>

### Expected behaviour

Can you also add a button/link that open Google Street View in a browser?

### Alternatives you've considered

Open visugpx.com, use the map, go to the coordinates, press the button ggsv (next to the blue marker on the right), press on the map (blue marker on the left), and street view is opened in a new tab.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/124c6e2a-35b0-40cf-b7da-cf6779fc42eb"  width="300" height="auto"/> </th>
  </tr>
</table>

Yes, if you try to view ggsv in a field or in a desert, this does not work...

**Comment by scaidermern** [comment]
Please don't add links to proprietary services. Add support for Panoramax instead (#20555).

**Comment by vshcherb** [comment]
no need to support custom maps there are plenty good formats for coordinates. If google wants to get support, they need to reveal geo:// protocol
