### ISSUE TITLE
Developing OsmAnd using Android Studio

### ISSUE THREAD

**Issue by jsanguesa** [osmandapp/Osmand#2096]
Hi, I'm would like analyze OsmAnd in order to add it a safety module. I' trying to import the code using Android Studio but I have not been able at all... I have not been able to find any guide or tutorial, i have tried using Git and downloading different branches... 

I have solved som codification problems and the resources issues but now i find the following error when I try to lauch it to the device:

Error:Execution failed for task ':OsmAnd:preDexFreeLegacyFatDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_65\bin\java.exe'' finished with non-zero exit value 1

Someone could help me? 

I have to admit that the last app I developed for Android was using Eclipse and maybe that's the problem.

Thank you in advance.

**Comment by vshcherb** [comment]
The issue is not clear and the server compilation succeeds, it requires specified android sdk & ndk verions.
