### ISSUE TITLE
Routing jumps from ground level to tunnel

### ISSUE THREAD

**Issue by clementcontet** [osmandapp/OsmAnd#20970]
### Routing engine

- [X] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Bike or pedestrian

### Start and end points

https://osmand.net/map/navigate/?start=45.773458,4.829080&end=45.773647,4.829004&profile=bicycle#19/45.77336/4.82940

### Actual route

![image](https://github.com/user-attachments/assets/717e35c3-62ac-4be1-a488-cdfc14f17ab7)

### Expected route

On third turn, the router jumps from a ground level way to an underground (and thus unconnected) one.

### Maps you used (online or offline)

- [x] Offline maps offered within the OsmAnd app for download, Sept 1st 2024

### Your Environment

```
OsmAnd Version: 4.8.6
Android version: 10
Device model: OnePlus5
```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. When building a route using the provided coordinates, the router incorrectly switches from the surface path to an underground path at the third turn, despite there being no entrance to the underground tunnel.

Here is the link to the web version: [OsmAnd route](https://osmand.net/map/navigate/?start=45.773458,4.829080&end=45.773647,4.829004&profile=bicycle#19/45.77342/4.82926)

Here is the link to the OSRM: [OSRM route](https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=45.77350%2C4.82907%3B45.77364%2C4.82900#map=16/45.77169/4.83411)

<table style="width:100%">
  </tr>
  <tr>
    <th>Web version</th>
    <th>OSM</th>
  </tr>
  <tr>
<th><img src="https://github.com/user-attachments/assets/9c6f598e-18c7-45c5-a60e-625c53ba3983"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/042d32b6-4023-4b3e-9406-aa4957010405"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by scaidermern** [comment]
Sounds like #3634

**Comment by clementcontet** [comment]
Oh, I didn't dig enough: it should be caused by this node, which incorrectly belongs to both a surface path and an undeground one:
https://www.openstreetmap.org/node/12061289105
I'm fixing it in the map.

**Comment by scaidermern** [comment]
Good find! Better also check the other tunnels and bridges nearby :)

**Comment by vshcherb** [comment]
No plan to fix in OsmAnd
