### ISSUE TITLE
Speedometer jumps when speed limit sign in shown

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#20976]
### How to reproduce
* Open **Menu** – **Configure Screen** - **Speedometer** – Turn on
* Set option **Speed limit warning** to **When exceeded**
* Start navigation simulation

### Actual result

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/fdbc7471-570f-4d54-8b2f-1d042384e99f"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/c6156c50-e86d-4a5c-b4c7-4e1736a2c253"  width="300" height="auto"/> </td>
    <td width="300"><video src="https://github.com/user-attachments/assets/e746bbca-6363-48fb-b7f5-1fb62cd9da30"   height="auto"/> </td>
  </tr>
</table>   

### Expected result

- [x] Replace speed limit image
- [x] EU – `ic_warning_speedlimit_eu_dark/light`
- [x] US – `ic_warning_speedlimit_us_dark/light`
- - [x] Add text label `LIMIT` for US
- - [x] Add text label `MAXIMUM` for Canada
- [x] Speedlimit icon size should be equal to Speedometer = 56 / 72 / 96

**Comment by dmpr0** [comment]
# Review
- [ ] Text color in night mode 

- - -

- [ ] Value text align in US / Canada variant

**Comment by dmpr0** [comment]
# Review

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/1927f2e6-3faf-441e-9e45-88bbe11f557b"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/ede82b44-d9c8-4ce9-989f-9727faa1d72f"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] Font size is too small, in US speedlimit. It seems big padding from the bottom?

**Comment by dmpr0** [comment]
# Review 

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/d99be579-23bc-4d4b-b96f-51b539c6dd52"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] Speed limit value should take all red space

**Comment by Zirochkabila** [comment]
Looks done
`OsmAnd~ 5.0.0#3793m, Released: 2024-11-25`

**Comment by vshcherb** [comment]
![telegram-cloud-photo-size-4-5924577892577166191-y](https://github.com/user-attachments/assets/604289c4-2405-4d6d-9777-d002980bee7c)
