### ISSUE TITLE
Opening Maps & Resources / Local takes very long

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#20974]
### Description

Opening the "Local" tab at Maps & Resources takes very long (about 40 seconds). This happens both right after starting the app and also when coming back again later. It doesn't happen after loading finished and switching between the tabs Downloads and Local.

I tried to move all my maps, geotiff, heightmap and tracks to a different location so that OsmAnd doesn't have to index them. The behavior stays the same.

I already cleared OsmAnd's cache. The behavior stays the same.

Map panning/zooming speed is normal (within OsmAnd's abilities, at least :)).

Not sure if this is a new behavior with OsmAnd 4.9.0 since I had to replace my old phone and there is no easy way to switch back to the old, stable version.

I can provide a video but I don't think it will be of much use.

### Steps to reproduce

Open Maps & Resources / Local.

### Actual result

A loading icon appears for about 40 seconds.

### Expected result

The content is shown almost immediately.

### Your Environment (required)

```
OsmAnd Version: 4.9.0
Android version: 13
Device model: Fairphone 4
```

**Comment by scaidermern** [comment]
I can't reproduce this behavior with the current nightly. Was there any fix for this problem?

I'm not sure if reproducing it with the nightly really tells me if this problem got fixed since it has a different storage path etc.

**Comment by DmitryAlexei** [comment]
This information worth adding to documentation (Troubleshooting section or [Maps and resources > local](https://osmand.net/docs/user/personal/maps-resources#local)  )

**Comment by scaidermern** [comment]
> was a sqlite big ?

Which sqlite?

From the video I recorded "Maps sources" was 0.6 MB. However, I don't really believe that. I had tiles from various different online map sources (OsmAnd online, Microsoft Earth, ...) in various geographic regions. Must have been more than just 0.6 MB, also considering that removing the tiles directory took quite some time.

**Comment by Rowin63** [comment]
The "tiles" folder is growing with every use (XX-thousand files) and can not be cleared easily. It´s ojnly possible by using a file commander, and then one never knows what to delete or not (it´s not possible to delete just the tiles/areas/countries not used/wanted anymore).

**Comment by vshcherb** [comment]
Tiles folder should not calculating at all if it's takes > 2-3 seconds and in background, so we need than kind of a link "Calculate size" as we did in Storage analyzer

**Comment by scaidermern** [comment]
For testing I redownload various online tiles (OsmAnd says 0.2 MB), now loading the local tab takes about 18 seconds again.

**Comment by Rowin63** [comment]
I guess we're facing the same issue.

I'm using the Microsoft Earth overlay and it's content is around 30000 tiles /500MB.

In "map sources / Microsoft Earth" Osmand tells me a size of 3,4kb like the other (empty) folders.

It takes about 15s to be displayed, getting slower every few days of use (using new earth tiles). 
After deleting all tiles the page is displayed within 1s again.

**Comment by scaidermern** [comment]
Even with all tiles removed, the operation "Clear all tiles" takes ~3 seconds. This is quite strange. I've checked the sub directories in the tiles directory, they are really empty.

**Comment by Gregor0000** [comment]
A quick solution for me was to switch for the online tiles from storing as individual files to SQLite db. No more waiting times.

**Comment by scaidermern** [comment]
> A quick solution for me was to switch for the online tiles from storing as individual files to SQLite db. No more waiting times. Shouldn't this be set as default?

Oh, there _is_ a setting for this! I totally missed this. Thanks!

Now it loads faster but still takes about 6 seconds. Looks like indexing is really slow.
And after switching to SQLite db OsmAnd finally shows a more realistic size of the tiles like 40 MB. Before that it just showed 0.2 MB which was totally wrong.

**Comment by Rowin63** [comment]
How/where please?

**Comment by scaidermern** [comment]
> How/where please?

Maps & Ressources / Local / Map sources / Three dots menu / Edit / Storage format

Any reason for SQLite not being the default?

**Comment by Gregor0000** [comment]
Just go to "Maps & Ressources", then in the "Maps Sources" of your online tiles in question,  tap the "Edit" button and there you can set the format.
I attached a screenshot for the manually added Google Earth Satellite online tile where I highlighted the setting.
![Screenshot_20241013-132049](https://github.com/user-attachments/assets/74a432af-bef4-421e-8afc-2b6243ed9ab2)

**Comment by Rowin63** [comment]
Danke

**Comment by scaidermern** [comment]
I've switched the storage path on my external SD card from `/storage/asdf/Android/data/net.osmand.plus/files/` to `/storage/asdf/Android/media/net.osmand.plus/files/` (Android 13) and now several things are a lot faster. The Local tab opens immediately whereas it was delayed by 4-6 seconds before. There is no more lag when opening the navigation menu or the Plan a route tool (which was also delayed by several seconds before). Track indexing happens much faster (took ages before) etc.

**Comment by Gregor0000** [comment]
Interesting, however, I always had it on "/storage/asdf/Android/media/net.osmand.plus/files".
Only switching the storage format to "SQLite db" did the trick for me.

**Comment by vshcherb** [comment]
- [ ] Change 5 MB -> 50 MB
- [ ] If you have 1 folder that's more than >= 50 MB, then for other map sources you should still see the size. Currently all sizes are gone.
