### ISSUE TITLE
Extreme slow search for addresses

### ISSUE THREAD

**Issue by noci2012** [osmandapp/Osmand#2097]
Maps: Netherlands
For some reason the search for major towns is Fast (name list is updated, with every new character that is typed).
For the smaller towns/villages this does not work which is a pain (waiting up to 2 minutes) as those do sometimes happen more often. Also ZIP code search is extremely slow, while this should also be easy for the same method as the mayor towns. 
And off course the overhead of looking up the list once and index it, or create an alphabetically sorted derivative is faster when info is requested.
Getting an incomplete Zipcode will be a real pain if the wrong one is chosen from a list, as the search needs to be redone, for each attempt.)

**Comment by vshcherb** [comment]
That's a known issue for now and we are working on it to get it fast.

**Comment by kompowiec** [comment]
not necessarily, if the begin to look immediately afther starting application (which not loaded tiles) 
indeed it happens. If wait a moment on load tiles and then until begin search, will work faster. These are the last of my feelings. But unfortunately it's pain in the ass.

**Comment by noci2012** [comment]
searching for zip codes (in stead of a town) or hamlet search is reeeaaallly slow, any time it is used...
(the list is huge, in NL the zipcode list is almost as big as the street list, maybe even slightly bigger as various streets have multiple zipcodes.)  so YMMV depending on the size of the list. Sorting them alphabetical + quicksearch would be an improvement.

**Comment by noci2012** [comment]
when will this be in release?

**Comment by vshcherb** [comment]
Mid July most likely

**Comment by noci2012** [comment]
ok
