### ISSUE TITLE
The track moves to Osmand web

### ISSUE THREAD

**Issue by Mototeuccio** [osmandapp/OsmAnd#20988]
https://github.com/user-attachments/assets/649381e5-c6c5-4f2f-8026-372fd0dabf46

### Description

When creating a gpx track from Osmand web happens that when zooming in and zooming out the track move in an imprecise way compared to the map.

### Steps to reproduce

I prove the track update on the map

### Actual result

The track will follow the map

### Expected result

The track will follow the map

https://github.com/user-attachments/assets/649381e5-c6c5-4f2f-8026-372fd0dabf46

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by Mototeuccio** [comment]
I tried with crome and safari browser

**Comment by Max1234-Ita** [comment]
Also tried on Windows, with Firefox browser.
It looks like the issue is triggered when quickly panning or zooming in/out, either with mouse wheel or the (+)/(-) buttons, after several points have been added to the new track.

![image](https://github.com/user-attachments/assets/2f79496e-9c32-49fc-b15e-cd433633007d)

**Comment by yuriiurshuliak** [comment]
Unfortunately, I was unable to reproduce the specific bug you mentioned. However, I did encounter another issue when canceling a previously added point to a track.

To reproduce this bug, open the track in the "Plan a Route" feature, add a new point to it, and then immediately cancel the addition.

As a result, when zooming out, you’ll notice that the track line stretches across the entire map.

https://github.com/user-attachments/assets/a9176dcb-a4c7-4182-8d48-b12ca5ab5c8a

**Comment by Mototeuccio** [comment]
the problem is exactly this


Matteo


Il giorno lun 7 ott 2024 alle 16:07 yuriiurshuliak ***@***.***>
ha scritto:

**Comment by vshcherb** [comment]
Fixed
