### ISSUE TITLE
Broken sharing for media notes

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#20989]
### Description

osmand can't share media notes if external storage is selected (/storage/emulated/0/Android/data/net.osmand.plus/files)

### Steps to reproduce
* Add Audio note
* Go to Menu – My Places – A/V Notes
* Tap on 3 dot's menu right to media note
* Select Share in bottom sheet 

### Actual result

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/b001941c-4832-4c17-a812-d6c64d7dbc30"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/79467f00-2909-4a27-9cf5-fb8bd25346cb"  width="300" height="auto"/> </td>
  </tr>
</table>   

* You will see empty system share sheet.

### Expected result

* Working share

**Comment by yuriiurshuliak** [comment]
The issue has been reproduced. To reproduce it, enable the Audio/Video notes plugin, add a A/V Notes Widget , and take a photo. Then, go to My Places - A/V Notes - select the photo - tap the three dots on the right - choose Share, and try to send the photo via Telegram.

As a result, the photo will not be sent, and an "Unsupported content" error will appear.

OsmAnd~ 4.9.0#3365m, released: 2024-10-07

https://github.com/user-attachments/assets/6b72ea97-9b12-4692-a011-1cf0db32bcbd

**Comment by Nine-Tailed** [comment]
I will add that there is no such problem if you set Android\media as the storage, for example.
