### ISSUE TITLE
Profile icon does not change (switch) 

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#20997]
### Description

When changing the profile, the "see map" (earth) icon is displayed in all profiles.
The profile changes, but the icon does not. 

### Steps to reproduce

Change the profile 

### Actual result

"see map" icon does not change 

### Expected result

Display the profiles' icon

### Your Environment (required)

~4.9.0#3363

**Comment by Velomeloman** [comment]
build 3372 can't reproduce

**Comment by Rowin63** [comment]
Hm...
Updated to the 3372 and still does not switch the icon. Created a new car profile, does not help.
Icon is the "world" icon, in all profiles.
In the 3-bars-menu the correct profile icon is displayed also in the profile selection (tapping the profile icon). But not in the map!

**Comment by yuriiurshuliak** [comment]
The issue could not be reproduced. The icon updates correctly when switching profiles. Please try updating the app and see if the problem persists.

OsmAnd~ 4.9.0#3386m, released: 2024-10-09

https://github.com/user-attachments/assets/1ec78502-b746-4d9e-99f2-44b230ee8801

**Comment by Rowin63** [comment]
Unfortunately still the same (3386).
I do as you do - the profile itself switches correctly (map and settings change) but the map symbol remains the "world" icon.
No big issue, perhaps it will disappear again by itself, as it came ;-)

**Comment by franco999** [comment]
I can reproduce this bug with OsmAnd~ version 4.9.0#3449m, Released: 2024-10-15.

**Comment by yuriiurshuliak** [comment]
Could you please export your settings by going to Menu → Settings → Export, and attach the file here? This will help us investigate the issue based on your current settings.

**Comment by Rowin63** [comment]
[Export_2024-10-16.osf.txt](https://github.com/user-attachments/files/17396534/Export_2024-10-16.osf.txt)

All the profiles. I also tried to create a new one ( + new profile, car), did not help.

**Comment by franco999** [comment]
> Could you please export your settings by going to Menu → Settings → Export, and attach the file here? This will help us investigate the issue based on your current settings.

My settings (Removing some private data)
[Export_2024-10-16.osf.txt](https://github.com/user-attachments/files/17396867/Export_2024-10-16.osf.txt)

**Comment by yuriiurshuliak** [comment]
The bug can be reproduced using the provided [settings](https://github.com/user-attachments/files/17412512/Export_2024-10-16.1.zip). To test it, import the settings and switch the profile from "Browse map" to "Motorcycle" (or any other profile). You will notice that the profile icon doesn't update; instead of displaying the motorcycle icon, it shows the planet icon, but in a different color.

OsmAnd~ 4.9.0#3456m, released: 2024-10-16

https://github.com/user-attachments/assets/705720c2-08bd-4598-aa56-aea4925cfbf5

**Comment by sonora** [comment]
Well, at least the color changes ... :wink::wink::wink:

**Comment by Rowin63** [comment]
(temporary) solution:
In every profile go to "menu > configuire display" select "standard buttons" > "configure map" > "appearance".
Here tap the icon and apply. Now the profile has it´s icon back.

![Screenshot_20241023_202455_OsmAnd~](https://github.com/user-attachments/assets/257d4857-3eff-469b-aff7-d4cbb79f7022)

You can see, the actual icon is the "earth", but the profile should have the "motorbike". After tapping "motorbike" and apply it, the profile has it´s motorbike icon back! (all icons are set to "user defined"; I was in this menu before, but only to set the opacity to 100%. Didn´t change anything else)

**Comment by nazar-kutz** [comment]
@Rowin63, In the current nightly build, this issue has been fixed, but you need to follow a few steps to resolve it on your device:

Go to "Menu" -> "Configure Screen" -> "Default Buttons" -> "Configure Map" -> "Appearance", and select "Dynamic" as the icon type from the dropdown menu next to the "Icon" heading (it likely shows "Custom" currently). Save these changes.

To apply this fix to all profiles, you need to set "Dynamic" for each profile manually or choose "Apply to all profiles" on the snackbar that appears after confirming changes in the "Appearance" screen.

**Comment by Rowin63** [comment]
Sorry for the late reply - thanks for this instruction, that helped!
