### ISSUE TITLE
Import (or export) not working - trying to move my settings and tracks to new phone

### ISSUE THREAD

**Issue by Arputikos** [osmandapp/OsmAnd#21003]
### Description

I click import and nothing happens, just blinks and nothing is imported. I tried like 10 times. 

### Steps to reproduce

Export on old phone POCO X5 Pro, import on new one Samsung Galaxy S22 Ultra Android 14 OneUI 6.1

### Actual result

Not importing anything, backup file around 10 times smaller than approximate sayingbefore export

### Expected result

Working import!

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.8.6
Android/iOS version: 14 / OneUI 6.1
Device model: Galaxy S22 Ultra EU SM-S908B
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
Related to https://github.com/osmandapp/OsmAnd/issues/20937 or https://github.com/osmandapp/OsmAnd/issues/20937
The issue will be resolved in the next update. If you'd like to receive the fix sooner, you can access the beta version here:
https://osmand.net/docs/versions/nightly_versions#google-play-beta-builds

**Comment by octagonsquare** [comment]
I have the same issue. What exactly is not working, the export or the import? I would like to know whether the export file is correct. Can I reset my old smartphone or do I have to create the export file with the new version of OsmAnd later on my old device?

**Comment by vshcherb** [comment]
4.9 Beta is released
