### ISSUE TITLE
Render issue causing double up of roads at some zoom levels

### ISSUE THREAD

**Issue by humphrey** [osmandapp/Osmand#2101]
At some zoom levels, roads render doubled up, as shown in the attached screenshots.  Phone: HTC One M8.  Android 5.0.1

Example 1: Roads are doubled up (with gps coordinations)

![screenshot_2016-01-01-13-00-02](https://cloud.githubusercontent.com/assets/229874/12069508/5ce36ed6-b088-11e5-9903-3e1d875f000f.png)

Example 2: Another double up, different zoom level

![screenshot_2016-01-01-13-06-40](https://cloud.githubusercontent.com/assets/229874/12069517/fb3eb428-b088-11e5-86ce-0f2101ce7f4b.png)

Example 3: Renders correctly, at a different zoom level (Zooming out heaps seems to be ok)

![screenshot_2016-01-01-13-06-55](https://cloud.githubusercontent.com/assets/229874/12069524/13be6368-b089-11e5-8ffc-01d68e8c772a.png)

Example 4: Also renders correctly. (Zooming in heaps seems to be ok also)

![screenshot_2016-01-01-13-07-04](https://cloud.githubusercontent.com/assets/229874/12069527/33221916-b089-11e5-9efe-fa3537456647.png)

**Comment by sonora** [comment]
Have you checked if you do not have 2 maps active covering the area at the same zoom level, like maybe a country and a regional map?

**Comment by humphrey** [comment]
Oh wow!  That fixed it!  Cheers!

I didn't notice that I had downloaded both "Australia" and "Australia Roads Only".  I didn't realise that it would try and render both.

Perhaps in a future version, the GUI could make it clear that you only want to choose one map for each region?  Or perhaps it could disable the "roads only" version if you have the full edition.

**Comment by vshcherb** [comment]
Known issue, though we have a dialog to prevent people downloading 2 maps
