### ISSUE TITLE
Sample rate of audio notes

### ISSUE THREAD

**Issue by blaueente** [osmandapp/OsmAnd#21028]
I found that for audio notes the sampling rate is always 8000Hz, even if one selects AAC with a high bitrate.
This is landline phone quality and makes notes sometimes hard to understand. Also this makes the user options to select better quality AAC or higher bitrates basically useless.

How to solve:

around [AudioVideoNotesPlugin.java#L1207](https://github.com/osmandapp/OsmAnd/blob/b13907d3eaec096170be2756414f1c8d990b53df/OsmAnd/src/net/osmand/plus/plugins/audionotes/AudioVideoNotesPlugin.java#L1207), please use this call to set the sampling rate:

[MediaRecorder#setAudioSamplingRate](https://developer.android.com/reference/android/media/MediaRecorder#setAudioSamplingRate(int))
It would be best if the user could choose the rate, just has he can select the bitrate. The usual options would be: 8000, 16000, 22050, 24000, 44100, 48000.

**Comment by dmpr0** [comment]
## ToDo

<table style="width:100%">
  <tr>
    <th colspan=2>Format</th>
    <th></th>
  </tr>
  <tr>
    <th>Default</th>
    <th>AAC</th>
    <th>Audio sample rate</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/ac2c68f2-f6cb-41c2-925e-dc9d91bccf24"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/2bc498d5-1f08-4c03-8fb5-07782441d736"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/bd3bea70-4009-4282-ae3a-1632b926c47a"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
I think we will by default set 24 kHz, and avoid doing UI cause then task could be completed this release vs waiting next

**Comment by blaueente** [comment]
Maybe this table with recommended sample rates is helpful? So the sample rate could be automatically selected depending on the configured bitrate, that would be a simple array map: https://wiki.hydrogenaud.io/index.php?title=Fraunhofer_FDK_AAC#Recommended_Sampling_Rate_and_Bitrate_Combinations (I guess it is AAC-LC)

Btw, there are even codecs such as opus that do not care about input sample rate, opus just resamples any input that is not 48khz to 48khz, and filters out higher frequencies depending on configured bitrate. Not sure how AAC behaves in case of maximum sample rate but low bitrate, but I guess the mapping table is more suitable for it.
