### ISSUE TITLE
De-clutter Drawer menu again

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2102]
Recent developments have blown up our drawer menu, I suggest before our next release we shorten it again as follows:

1. "Waypoints": Delete, now obsolete. This is a sub-function of the Directions functionality only and can now be logically accessed from the nav config screen. In addition, we also have other ways to delete waypoints, e.g. long-tapping them using context menu.

2. "OSM Live" clearly is a sub-function of Manage map files, and should be a tab on that screen with no seperate drawer entry.

3. "Builds" is a developer functionality and should move to the dev plugin settings only, remove from drawer (even if it is only visible with plugin enabled, it still clutters our drawer)

I think implementing these will not only shorten our drawer menu again, but also sort access to our functionality in a more logical way, and optically create a "cleaner" and simpler look for our UI.

**Comment by raindropsfromsky** [comment]
I agree. 

In any case, in version 2.3 the ***waypoints*** item will become totally redundant.
In that version, we will have a unified "Route Editor" GUI, with single list of points on a route. A given point's position in the list itself will define whether it is "start point", "end point" or a "way point". They do not need separate methods of renaming or deletion.

**Comment by vshcherb** [comment]
1. Waypoints will be deleted, I agree, but not now, we will first implement it in the branch.
2. OSM Live we want to make separate for now, I don't see issue with this item.
3. Builds is purely development and available only for nightly builds, so there is no issue with this. I like it there and we are not that many "developers"

**Comment by sonora** [comment]
My principal thought is to use the drawer as some sort of self-explanatory guidance how to use the app (for the 99% of people who want to understand what an app is basically about without having to read any documentation, and remember how the app basics work even if they only use it occasionally).

And for that the drawer should display
(a) only the very few basic functionalities people use the app for, i.e. search locations (+ navigate, but even hat could be linked behind "Search"), and Explore the map (essentially everything we now put in our "Use location" context-sensitive functionality) 
(b) display the necessary Settings people need to find to perform the basic customizations everybody would like to find and make

All other stuff
(c) which is used by few people (I call that "fringe functionality", even if some of it is a unique selling feature for OsmAnd!!)
(d) strictly refers to some functional context (like navigation parametrization, navigation settings, Plugin settings, etc.)
should be placed to obvious screens which pop up when people use that functionality (much like we do with our routing screens now).  ("Functionality-related user guidance".)

So that is why I think it is possible to bring down the drawer to as few as a handful of needed entries! And that would make a "clean and simple" first time impression for our users, and would still provide the functionality 95% of them will ever need and use in OsmAnd.

Special, new, etc. functionality should be used in "Marketing", like on the "What's New" popups, on our web site, etc. but must not clutter our app unless it belongs to categories (a) or (b) above.

EXAMPLE: (As a drastic, hypothetical example  :) ): We do not need to have a setting like "GPS wakeup interval" or "GPX display color" on our top drawer, because most people do not use GPX recording or displaying, and of those who do only, a small fraction will need to change this from our automatic default. So that is why we have pushed this "very special functionality" way back in our settings and widgets. And the same still needs to happen with even more mainstream actions (like, but not limited to, the examples I noted in this issue):

Again: Most of the things we have in the drawer are NOT "tier 1"!  Not by their functional logic or context, and not by the frequency with which they need t be accessed. Let's think about it ... :)

**Comment by raindropsfromsky** [comment]
Another example: The "Use location" option.

Although this command appears to originate from the drawer menu, it actually does not do anything at all, except place a point at the exact center of the screen.  Then OsmAnd shows a card. The user has to tap its ***overflow*** button to select the real command.

Given this, why do we have this command in the Drawer Menu at all?

BTW when we use OsmAnd, we keep zooming and panning the map. So, at any given point of time, our display shows a random part of map at a random zoom factor. What is the point of finding the exact center of that random area?

Instead, it would be better if we select a specific point on the map with a long-press. As soon as a point is defined, OsmAnd can pop up the card, and then the user can select a command.

Thus the ***Use location*** command is also a misfit on the Drawer Menu.

**Comment by vshcherb** [comment]
Hardy: I agree with your points, though the plugins I think should have possibility to enable special items like OsMo or possibly New GPX Trip, cause user makes an intention to enable the plugin. 

Use location is there for historical reason and we will remove once we implement icons click, which is not currently WIP but it is in a short list.

**Comment by sonora** [comment]
Victor, yes, that's a good point. If users enable plugins, this could of course result in then displaying the "tier 1" actions associated with those plugins, and they could appear in widgets or even in the drawer as appropriate.
