### ISSUE TITLE
Live updates bug

### ISSUE THREAD

**Issue by Velomeloman** [osmandapp/OsmAnd#21047]
### Description

It looks like a [clumsy edit](https://www.openstreetmap.org/changeset/157759818) caused an immutable change for live updates

### Steps to reproduce

Look at ‎55.64916° N, 37.53598° E and download live updates

### Actual result

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/5db8edd3-3d7e-49bf-9409-3a56331e35f7"  width="300" height="auto"/> </th>
  </tr>
</table>

Wrong industrial zone rendered. There is no mistake at osm.org anymore. 

### Expected result

All subsequent changes are taken into the live update

### Your Environment (required)

Nightly and GP versions

**Comment by Velomeloman** [comment]
I wiped all app data of 4.8.6 through system settings, downloaded Standard maps and Live updates.
Incorrect large industrial area in mobile version:
![Screenshot_20241015_185900.jpg](https://github.com/user-attachments/assets/3e9d618f-9b83-4977-8cc4-21c7a6e59e1a)

Correct small industrial area in web version and OSM.org:

![Screenshot_20241015_185949.jpg](https://github.com/user-attachments/assets/d768d344-01a7-400d-bc7d-76a879f6f766)

![Screenshot_20241015_185924.jpg](https://github.com/user-attachments/assets/ff9d2ae2-c63f-4658-9d5f-70cd8ae24152)

**Comment by yuriiurshuliak** [comment]
We have checked the industrial zone in the application, and it shows different borders compared to OSM. Additionally, on OSM, the boundaries of this industrial zone appear to change at different zoom levels.

It’s possible that something went wrong during the editing process. We recommend reviewing the edits for this zone and then checking it again in the nightly version with live updates enabled.

OsmAnd~ 4.9.0#3456m, released: 2024-10-16

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/759cdba1-71e3-42b1-aee0-778d11dd1c72"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/7ce8ec0c-f89f-4e9f-b8c4-43094f793d24"  width="500" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/5b2431f9-3516-41a5-8cf3-6a47a1c88868"  width="600" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
Let's wait for a new bug where it could be simpler to trace back the problem here it's too many changes and hard to understand what went wrong
