### ISSUE TITLE
Routes to Zermatt are wrong

### ISSUE THREAD

**Issue by Gravity2106** [osmandapp/OsmAnd#21041]
### Routing engine

- [X] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

The routes suggested seems to have bad info about the geography and it paints the last part of the way straight through the mountains

### Start and end points

For example Bern -> Zermatt 4

### Actual route

It fails, it has no sense

### Expected route

Google maps offers a way to arrive 

### Maps you used (online or offline)

- [X] Switzerland 1.10.24
- [ ] Online (tile / raster) maps 

### Your Environment

```
OsmAnd Version: 4.8.6
Android version: 14
Device model: pixel 7a

```

**Comment by scaidermern** [comment]
Maybe this is because of the `motor_vehicle=permit` tag: https://www.openstreetmap.org/way/30952472

**Comment by yuriiurshuliak** [comment]
While checking, I found that the route from Bern to Zermatt 4 on Google Maps matches the route created by our web version. 
You can view it here: [Web version link](https://test.osmand.net/map/navigate/?start=46.947974,7.447447&end=46.173437,7.800819&profile=car#9/46.6087/6.9873).

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/be771636-1dea-47b3-9b23-435de1e9fe90"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/bfc14f4d-7d84-4d20-b0d6-bbd51a309a5f"  width="300" height="auto"/> </th>
  </tr>
</table>
