### ISSUE TITLE
'Plan a route' has annoying map drift when adding points

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#21046]
Here is a small, rather annoying glitch hopefully easy to fix:

The Plan a route tool has progressed to be very useful, but the following behavior should be stopped: To add (also move) a point, you pan the map to where the cursor is. Then you lift your finger (to tap the "Add" (or "Apply") button), _but the moment you lift your finger, quite regularly there is some flinging animation shifting the map a bit, away from your carefully aligned position._

I have disabled all animation settings, but this behavior is always present.

I believe the solution is that while in edit mode we need to disable the map flinging (which otherwise facilitates to pan the map by big distances), because in the edit mode precision is key, not panning speed.

**Comment by yuriiurshuliak** [comment]
I was unable to reproduce the issue. I opened the 'Plan a Route' tool and began creating a route by panning the map and moving the cursor to the desired location. After lifting my finger, I pressed the 'Add' button.

In my case, the map remained stable, with no drifting, jerking, or unexpected animations.

I’ve attached a video for reference. Could you please confirm if I followed the correct steps? Additionally, do you notice any potential mistakes in my process?

OsmAnd~ 4.9.0#3449m, released: 2024-10-15

https://github.com/user-attachments/assets/40f749e9-3a83-4a1f-ac83-4ff1b60cd0eb

**Comment by sonora** [comment]
@yuriiurshuliak Yes, you are using the correct procedure, thank you!

Essentially, the effect is caused by the user lifting their fingers not 100% vertically, so there is a certain learning curve.

I have tried on different devices, and the effect seems more pronounced on some than on others (probably low dpi devices have a bigger issue). I will research some more and also try with different users. Will close the issue for now to not engage undue resources. - Thank you @yuriiurshuliak

**Comment by scaidermern** [comment]
I can reproduce your behavior on a Fairphone 4. When lifting the finger, the map moves slightly. Sometimes more, sometimes less. I guess it also depends a little on the user, as you already suggested.
