### ISSUE TITLE
Limited number of Sub-Folders?

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#21051]
### Description

I created a new Folder and wanted to move some other, existing, folders into it, as subfolders.
I could move 19 existing folders into this new "main" folder, and now it is not possible to move any other folder into this new "main" folder.

Also it is not possible to move other folders into another new "main" folder.
Like there is a limitation of subfolders.
At this point a phone restart did not change anything.

### Steps to reproduce

All my TET tracks are stored in a separate country-folder, like TET Andorra, TET Montenegro, TET XXX and so on. 
Now I wanted to create a TET "main" folder and move the existing country folders into it. That would be around 30 country-subfolders inside the main TET-folder.

I moved 19 country folders and now I cant move any other folder.
I can mark/select it and tap "move to", but nothing happens.

Also it is not possible to move other folders as sub in another new main folder. Just nothing happens when selecting "move to". 

### Actual result

Long tap a folder in my places/tracks. Folder is selected.
3dots > move (at this point the app crashed right now)
Again: 3dots > move > select the new "main" folder "TET"
Nothing happens. Selected folder is not moved. Just nothing happens.

### Expected result

move the selected folders into the selected main-folder, as sub-folders

### Your Environment (required)

Adroid 13, +4.9.0 (2024-09-04)

**Comment by Rowin63** [comment]
After this, I moved all the existing "TET country" folders by a file manager into the new TET "main" folder and all sub-folders are correctly displayed in Osmand (TET/country1, TET/country2, ...)

**Comment by Rowin63** [comment]
The app seems to be overloaded by moving that many tracks at once. It frequently crashes and the tracks don't show any details

![Screenshot_20241015_205920_OsmAnd+](https://github.com/user-attachments/assets/1aaf9551-5271-4933-81e6-55800f0920fe)

**Comment by Rowin63** [comment]
Since I moved the folders Osmands Logcat is very busy and the App is crashing every few minutes.

**Comment by Rowin63** [comment]
There mus be something wrong with Osmands istallation.
Though I deleted almost 90% of the tracks, the remaining ones are not processed anymore in a reasonable time.
It takes minutes until the tracks data (time, lenght, ...) is diplayed in the track list.

**Comment by Rowin63** [comment]
I fear I have to go for a fresh install.

**Comment by Rowin63** [comment]
Did a fresh install and a step back to the +4.8.6
Tracks details are now processed without any problem and no OOM anymore.

But still i can´t move existing folders into another folder.

**Comment by vshcherb** [comment]
That need to be reproduced and fixed, probably moving to folder is very not optimized especially for large tracks

**Comment by yuriiurshuliak** [comment]
I attempted to reproduce the issue by creating a main folder and 30 subfolders, each containing 2-3 tracks. I successfully moved all subfolders into the main folder without encountering the problem you described.

To investigate further and try to reproduce your exact conditions, it would be helpful if you could export and share the subfolders you are trying to move. You can either attach the export to this issue or send it directly to support@osmand.net.

Additionally, we recommend trying the new beta version, which will be available tomorrow, as this issue might already be resolved in that update.
