### ISSUE TITLE
Too early lookup hangs reverse geocoding forever

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2106]
Here is how to reproduce:
- Fresh start of OsmAnd
- As soon as the map appears, long-tap any location to trigger a reverse address lookup via the context menu
- The lookup will hang forever at the stage "Looking up address...", and all subsequent lookups for other locations will also hang with that result.

If, on the other hand, after a fresh app start you wait say 30+ seconds before starting the first context menu / reverse lookup, all is fine. The first as well as all subsequent lookups will then speedily either produce a result, or immediately report that no address can be determined.

The issue is observed with latest nightlies. Our nightly of Dec 5 did not have the issue yet (there only the very first lookup failed if it was too early, with subsequent lookups working ok).

This issue is also the underlying issue for Issue #2104, which I closed again because I think fixing this one will make that one obsolete.

**Comment by sonora** [comment]
The behavior aggravating the issue happened on Dec 27, so it seems we need to amend commit https://github.com/osmandapp/Osmand/commit/45b7f61fe8fd434e4d4b7bde5be706c5cd26499a.

**Comment by sonora** [comment]
This commit https://github.com/osmandapp/Osmand/commit/c7ae34e1f6b0f1a6d2cb601698d31825adc413d5 fixes it.

(Restoring the behavior of former builds, where only the very first reverse lookup fails, and only if it was executed within seconds after a fresh app start. Looks like somehow there is a timing issue if a reverse search is started before everything is properly initialized. We seem to somehow be missing a proper end condition for the search / geocoding publish in this case.

Not a frequent issue, so main issue can be considered solved now.)

**Comment by vshcherb** [comment]
Good but let us overview the commits

**Comment by crimean** [comment]
It was wrong fix. Anyway - fixed few days ago.
