### ISSUE TITLE
Sorting gets reset to "last edited"

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#21068]
### Description

All my tracks are sorted by "A-Z" (my places > 3dots > Unterordner sortieren).
Everytime one folder gets deleted, ALL folders sorting is set back to "last edited". 

### Steps to reproduce

see description.

### Actual result

see description.

### Expected result

see description.

### Your Environment (required)

Android, +4.8.6

**Comment by yuriiurshuliak** [comment]
The bug could not be reproduced. To attempt reproduction, go to My Places > Tracks and ensure you have a folder with subfolders containing tracks. Then, set the Sort by option to "A-Z" in My Places > Tracks, My Places > Tracks > Folder, and My Places > Tracks > Folder > Subfolder. Next, delete one folder, restart the app, and check if the Sort by setting remains "A-Z" in all locations where it was configured.

In my case, the Sort by setting for all folders and subfolders stayed correctly on "A-Z" and did not revert to the default "last edited".

OsmAnd~ 4.9.0#3456m, released: 2024-10-16

<table style="width:100%">
  </tr>
  <tr>
    <th>Sorting in the folder itself</th>
    <th>Sorting in a folder with folders</th>
    <th>Sorting in My Places > Tracks</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/user-attachments/assets/4df8b43d-14bb-4d65-88a6-7d1c2781c90e"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/user-attachments/assets/970aa727-aabd-4283-ab29-f39cda2cd32c"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/user-attachments/assets/9575a048-738b-4af9-97ff-f084d6595701"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by Rowin63** [comment]
I tried the nightly and also could not reproduce it.
It happens in the +4.8.6 but perhaps/probably not in the later nightlies anymore (don´t know about the +4.9.0 which I try to skip... waiting for the following update!)
