### ISSUE TITLE
Rendering of Network node

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#21076]
### Description

Node networks show on a small zoom 

<img width="377" alt="image" src="https://github.com/user-attachments/assets/d8fb18b5-3927-46f9-80bd-cb782a537d35">

### Steps to reproduce

1. Download the France map and switch on Routes > Hiking routes: 
https://osmand.net/map/search/?pin=44.666272,4.362259#14/44.6682/4.3564

### Actual result

<img width="382" alt="image" src="https://github.com/user-attachments/assets/413e4287-8736-4e13-8ddd-40ac0f146280">

### Expected result

without this node signature for a small zoom

### Your Environment (required)

```
OsmAnd Version: 4.9
Android/iOS version: 14
Device model: s22 Samsung
```
date map 1.10.2024

**Comment by vshcherb** [comment]
These nodes - https://www.openstreetmap.org/node/9959324582#map=14/44.72969/4.36792 should be visible from zoom 16-17.

**Comment by xmd5a2** [comment]
Zoom levels for there label were adjusted:
Colouring according to OSMC: starting from zoom 16
Colouring according to route scope: starting from zoom 16
Node networks: starting from zoom 14
