### ISSUE TITLE
Map could be "downloaded" twice, double entry

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/Osmand#2107]
While updating a map,  pressing "update all" will add the same entry twice. See screenshots
Version #15111
Greetings Simon
![screenshot_2016-01-02-10-15-51](https://cloud.githubusercontent.com/assets/11144987/12073967/de184046-b13a-11e5-933a-f4bf442a4f2a.png)
![screenshot_2016-01-02-10-16-01](https://cloud.githubusercontent.com/assets/11144987/12073968/e39dcae0-b13a-11e5-9bf2-1e6420bba691.png)

**Comment by raindropsfromsky** [comment]
Confirmed. 
I also have faced this problem.

**Comment by GaidamakUA** [comment]
Fixed with commit fdfb81422b432df1a2700d0f490478a7006574ae
