### ISSUE TITLE
Moped routing doesn't avoid highway pedestrian. 

### ISSUE THREAD

**Issue by theodoor** [osmandapp/OsmAnd#21087]
### Routing engine

- [X] OsmAnd's in-app offline routing
- [X] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Moped

### Start and end points

https://osmand.net/map/navigate/?start=51.445128,5.474024&end=51.431324,5.485439&profile=moped#13/51.4270/5.4956

### Actual route

![image](https://github.com/user-attachments/assets/a29a8743-1fbd-49d1-9d9e-de016573ef46)

### Expected route

Routing avoids highway: pedestrian roads for mopeds. 

### Maps you used (online or offline)

Online

### Your Environment

Online

**Comment by xmd5a2** [comment]
Fixed. No new maps required. Map to test: **netherlands_noord-brabant**
