### ISSUE TITLE
Touringview vs. default - parking rendering

### ISSUE THREAD

**Issue by mariush444** [osmandapp/OsmAnd#21088]
### Description

There is intention to change parking color in TouringView
Lines 618-629

```
<renderingAttribute name="parkingColor">
		<case nightMode="true" attrColorValue="#36455a"/>
		<case attrColorValue="#f6eeb7"/>
	</renderingAttribute>
	<renderingAttribute name="parkingPrivateColor">
		<case nightMode="true" attrColorValue="#7741536c"/>
		<case attrColorValue="#77f6eeb7"/>
	</renderingAttribute>
	<renderingAttribute name="parkingCustomersColor">
		<case nightMode="true" attrColorValue="#7741536c"/>
		<case attrColorValue="#77f6eeb7"/>
	</renderingAttribute>
```
but in default rendering
there is wrong definition in lines 9253-9272

```
			<case minzoom="15" tag="amenity" value="parking" color="$parkingColor">
				<apply>
					<switch>
						<case additional="parking=multi-storey"/>
						<case additional="parking=underground"/>
						<apply color_2="#555555" strokeWidth_2="0.7">
							<apply_if nightMode="true" color_2="#999999"/>
						</apply>
					</switch>
				</apply>
				<apply showAccess="true">
					<switch minzoom="16">
						<case additional="access=private" color_2="$accessPrivateColor"/>
						<case additional="access=permissive" color_2="$accessPermissiveColor">
							<apply_if nightMode="true" color_2="$accessPermissiveColorNight2"/>
						</case>
						<case additional="access=customers" color="$parkingCustomersColor" color_2="$accessCustomersColor" strokeWidth_2="3" pathEffect_2="8_6" cap_2="ROUND">
							<apply_if nightMode="true" color_2="$accessCustomersColorNight2"/>
						</case>
						<apply strokeWidth_2="3" pathEffect_2="1_6" cap_2="ROUND"/>
					</switch>
				</apply>
```
It should be

```
<case additional="parking=multi-storey"/>
					<case additional="parking=underground"/>
					<apply color_0="$parkingColor" 
 color_2="#555555" strokeWidth_2="1:0.7"/> 
```
**color_0="$parkingColor"** 

and
```
<case additional="access=private" color="$parkingPrivateColor" color_2="$accessPrivateColor"/>
					<case additional="access=permissive" color="$parkingPermissiveColor" color_2="$accessPermissiveColor"/>
					<case additional="access=customers" color="$parkingCustomersColor" color_2="$accessCustomersColor"/>


```

**color=**
have to be added

### Steps to reproduce

Try to change parking color useing definition in touringview rendering

### Actual result

Color parking can't be change

### Expected result

It should be possible to change color parking as there was such intention

### Your Environment (required)

Current official version for android

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. The reason is that parking zones are marked as POIs (Points of Interest) in OsmAnd, and the color for a POI cannot be changed through the rendering rules. POI icons and colors are predefined in the app and are not customizable in this way.

OsmAnd~ 4.9.0#3507m, released: 2024-10-21

<table style="width:100%">
  </tr>
  <tr>
    <th>OsmAnd style</th>
    <th>Touring View style</th>
  </tr>
  <tr>
<th><img src="https://github.com/user-attachments/assets/774adbd4-38fd-47d7-bbc3-cc86e9f7fdb3"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/4a5140ad-93be-4ac7-9d3a-a34bb0c6f607"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by mariush444** [comment]
It is not about POI but area.
But OK, it is your problem and your decision.
I've already implemented my needs.
