### ISSUE TITLE
Increase zoom level for route preview – Android Auto

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#21097]
### How to reproduce
* Connect to **Android Auto**
* Select **Destination**
* Wait until route will be calculated

### Actual result
<table style="width:100%">
  <tr>
    <th>2D Mode</th>
    <th>3D Mode</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/3a203672-f35e-4a1d-9895-342f086933bc"  width="350" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/9e445a0c-56cc-4672-a0a5-cbe165452b44"  width="350" height="auto"/> </td>
  </tr>
</table>   

* Route line takes less than a half of the screen height in 2D mode
* Route line takes less than a 25% of the screen height in 3D mode

### Expected result

**Environment**
OsmAnd Version: 
Android: 15
Device model: Google Pixel 6A

**Comment by RZiarnik** [comment]
In my opinion, even in 3D mode route preview should be showed in 2D mode and of course North should be up for it.

**Comment by vshcherb** [comment]
To do
- [ ] double check Android phone route preview. 
- [ ] on Android Auto implement similar strategy, after route calculated switch to 2D mode (switch back to original on back and on start) and display route maximum in right panel box. My location shouldn't be centered or placed at bottom (check Android phone UI).

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/pull/21260

**Comment by vshcherb** [comment]
- [ ] Broken view (north up) if navigation started on the phone with AA connected (check non-connected)
- [ ] Broken view (north up) if route is recalculated
