### ISSUE TITLE
Don't stop routing because of outdated maps

### ISSUE THREAD

**Issue by mwerle** [osmandapp/OsmAnd#21092]
### Describe the idea

Use existing offline maps for routing even if they are "outdated".

_Especially_ if those maps were used to calculate the original route anyway!

----

Recently (OsmAnd 4.8.6, possibly a version or two earlier), I've had situations where my routing stops. The route disappears and refuses to recalculate, often after passing through a tunnel or missing a turn.

Looking at the routing tab, "Details", the cause is listed as "Missing or Outdated Maps". The route calculated just fine prior to setting off, and clicking on "use offline maps" (sorry, I can't remember the exact UI wording) it again recalculates fine. The device I am using is offline (no internet connection), so I have no idea how it suddenly decides that some maps are "outdated". When I do update the maps, I update all of them at once so they should all be from the same time.

IMHO, there is absolutely NO REASON EVER for OsmAnd to :

1. automatically stop displaying a calculated route unless it is immediately replaced with another route. (ie, recalculate the route in the background so the driver can attempt to get onto the old route manually in the meantime)
2. refuse to recalculate using old maps - using old maps is better than no route at all!

Stopping routing part-way through a trip can cause significant difficulties, especially on a motorcycle.

### Expected behaviour

Routes continue to be displayed and/or recalculated using the offline maps on the device.

This _should_ be the default, but if, due to legal requirements in the US or whatever it is necessary to stop routing and have this manual override to resume routing, at least please make this an option so people do not need to stop in order to re-enable routing.

### Alternatives you've considered

Using an alternative product. 

No real workaround apart from finding somewhere safe to stop (not always possible on highways in Japan) and forcing the App to recalculate using the offline maps which it thinks are "outdated" for some reason.

### Context

OsmAnd 4.8.6 on Android 13 using offline maps for Japan.

----

Also, semi-relatedly, when GPS signal is lost, OsmAnd often "jumps" to a location nearly 6000km away. I don't know if this is the default for OsmAnd, or the phone's / Android's location service.  Again, this should not happen, ideally the location should be interpolated based on the last known velocity and time until signal is regained, or the location should stay on the last known good location if the new location reported by Android is patently absurd (middle of the ocean thousands of kilometers away)

----

Thanks to all the developers for an overall amazing product!

**Comment by dmpr0** [comment]
Hi! Could you please provide example route?

**Comment by Guylby** [comment]
For the loss of routing at the end of tunnels this may be related to #20485 
I've also experienced this loss of routing numerous times with the deviation of itinerary of more than 5000kms when gps signal is reconnected after exiting tunnels

**Comment by mwerle** [comment]
> Hi! Could you please provide example route?

So it happened again, tonight, roughly in the circled area, while I was guiding a friend home (we were on two motorcycles with an intercom, her first time riding and didn't have her own navigation solution yet). No loss of signal as far as I could tell, no tunnels. Just in-between glancing at my phone, the route was suddenly gone. At an incredibly inopportune moment as the sharp left-hander there is to avoid going the wrong way into a one-way section of road. As I was late directing her and she was overwhelmed with everything she actually entered the one-way section. The destination was still selected.

This time there was no option to ignore old maps - I had to completely dismiss the route, re-select the destination, and have OsmAnd recalculate the route.

![image](https://github.com/user-attachments/assets/0262eef0-e10f-446a-9078-7e3534873cf6)

It's just a plain GPX - remove the ".zip" ending.
[Mon 21 Oct 2024.gpx.zip](https://github.com/user-attachments/files/17462606/Mon.21.Oct.2024.gpx.zip)


This is starting to be a big issue. OsmAnd also, for some unfathomable reason, wanted me to download a russian map.. as I was on the bike I did not note down the exact region it wanted.

Again, please note that I use OsmAnd completely offline; I occasionally update the maps when at home, but generally just use it offline. I don't recall this issue a year or so ago, this is a fairly recent occurrence.

**Comment by yuriiurshuliak** [comment]
Related to #21094

We've implemented fixes for it. Please try using our nightly build and let us know if the problem persists: https://osmand.net/docs/versions/nightly_versions#nightly-builds

**Comment by vshcherb** [comment]
Reason that routing stopped is not directly clear cause it shouldn't behave like that. Routing doesn't check outdated maps, it checks inconsistent maps. If you managed to start routing initially, recalculation should work same way. The issue might be with jumping GPS signal however in your file I didn't find anything strange. 
We will simulate with your track to see what's going on

**Comment by yuriiurshuliak** [comment]
Unfortunately, I am unable to import your file [20241012-211040.zip](https://github.com/user-attachments/files/17467940/20241012-211040.zip), as the application shows an error when attempting to open it. Could you please check the file and provide it again?

OsmAnd~ 4.9.0#3527m, released: 2024-10-23

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/1eecd63f-2308-4ade-88e5-f31c5dae7f87"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by mwerle** [comment]
> Unfortunately, I am unable to import your file [20241012-211040.zip](https://github.com/user-attachments/files/17467940/20241012-211040.zip), as the application shows an error when attempting to open it. Could you please check the file and provide it again?
> 
I just downloaded it, extracted it, and could open it with "Viking" and "GpxSee" applications.

I'm not sure what's wrong with it that you can't open it? There are some extensions at the beginning of the file, maybe your application doesn't ignore those?

**Comment by yuriiurshuliak** [comment]
The issue could not be reproduced in testing. Here’s a summary and observations:

- Testing Setup: GPS was disabled on the device, navigation was set up with the specified track, and the "Simulate your position" feature was activated in the OsmAnd development plugin.

- Observed Behavior: Navigation did briefly stop at the segment highlighted in the screenshot, displaying "GPS Signal lost." However, after a short delay, navigation resumed without encountering a "Missing or Outdated Maps" error. This behavior was consistent in both the nightly and release versions of the app.

- Limitations of Simulation: Tunnel-related bugs may not be reliably reproduced under simulation. Real-world conditions might be necessary to reproduce the results described by the user, as simulation may lack accuracy for issues involving GPS signal variations in tunnels.

In summary, while the "GPS Signal lost" message appeared briefly, navigation did not fully stop, nor was there any map-related error.

OsmAnd~ 4.9.0#3527m, released: 2024-10-23
OsmAnd 4.8.6, released: 2024-08-08


<table style="width:100%">
  </tr>
  <tr>
    <th>Nightly version</th>
    <th></th>
    <th>Release version</th>
    <th></th>
  </tr>
  <tr>
    <td> <video source src="https://github.com/user-attachments/assets/bff01c80-70c6-44f8-aacb-3a5b702f7bcd"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/user-attachments/assets/cb21d63d-ff05-4a46-9997-8463ebbc29ab"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/user-attachments/assets/d4195c38-1ee5-44dd-a948-7cb9735f5779"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/user-attachments/assets/f787d49f-bbc7-446e-878f-2246c31395d7"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by mwerle** [comment]
I'm sorry, I can't see any of the videos you attached : 

![image](https://github.com/user-attachments/assets/32453a56-d36a-4f18-88d8-f55faebb4b67)


----

> In summary, while the "GPS Signal lost" message appeared briefly, navigation did not fully stop, nor was there any map-related error.

Well, I'm dreadfully sorry, but in the -real world-, this did happen (navigation stopped and had to be manually restarted). Simulations cannot reproduce all aspects of real-world situations. Perhaps device-type (I'm using a Ulefone Armor 22) also has an impact and sends invalid GPS coordinates to OsmAnd when it loses GPS signal (I often get OsmAnd displaying a bogus position 5000+ km away from where I really am after losing GPS signal).

**Comment by vshcherb** [comment]
Yes we believe that hapened, though as application development goes on it's hard to fix something which is not reproduced.

That's why we ask to record tracks with high precision so later it's possible to reproduce with exact precision what was going on though it still doesn't always help. 

As I mentionned we checked the code / the concept routing doesn't stop (shouldn't ) when you have outdated maps, it doesn't start when you have 1 map 01.01.24 and another 01.02.24 and they are both used for the route, but it doesn't check the freshness of the map. It's possible to change routing algorithm to A* and then the dates are ignored

**Comment by mwerle** [comment]
I understand.

I missed the fact that you checked the code for outdated maps. If this is no longer a trigger for bad routing, perhaps the error message should be updated to reflect that?

The other factor might be the jump to a location ~5000km away when GPS signal is lost; I have no idea why that's not in the logs. It might be possible to manually insert such data into a log file to see how the app responds in such as case?  I know there's been some work/investigation done around this when losing GPS positions in tunnels..

I've been reluctant to join the beta program as this is my only means of navigation on the motorbike, but I'll try it to see if there's any improvement.

Thank you for your investigation.

**Comment by mwerle** [comment]
Closing as apparently not due to "outdated maps".  (Although still suggest to improve the error message).  Thank you for your support, even if it hasn't resolved my issue.  Much appreciated!

Related discussion in #20485

**Comment by vshcherb** [comment]
GPS spoofing happens more and more often around the wolrd by unknown reasons so we need to detect it better that's also true
