### ISSUE TITLE
Quick action - show/hide wikipedia bug

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#21095]
### Description

I added a quick action "show/hide Wikipedia" 

### Steps to reproduce

Add the quick action to user defined switches 

### Actual result

"show Wikipedia" puts Wikipedia on display, but quick action "hide Wikipedia" does not remove them. 

Have to go to "configure map" and switch Wikipedia off again. 

### Expected result

Switch the displayed wiki poi off again 

### Your Environment (required)

Android +4.9.0

**Comment by Biker729** [comment]
Nach Update auf 4.9.2 stürzt die App nach öffnen der Schnellaktion vom Display immer ab.

**Comment by scaidermern** [comment]
The same issue (crash after using quick action) was reported by a user of the OsmAnd Telegram group for version 4.9.2. But this belongs into a separate ticket.
