### ISSUE TITLE
Add support for some common POI

### ISSUE THREAD

**Issue by math1985** [osmandapp/Osmand#2109]
Would it be possible to add support for the following common POI? All have more than 5000 occurrences according to taginfo. Thanks in advance for considering this request!

* [ ] ~~amenity=vending_machine~~
* [x] man_made=silo
* [ ] man_made=embankment
* [x] man_made=gasometer
* [x] man_made=dyke
* [x] man_made=mine
* [x] man_made=dolphin

**Comment by Barrocas** [comment]
At least the 'Vending machine' I know that is already rendered and
available.

-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by math1985** [comment]
You're right, that one is available, I didn't look well.

**Comment by xmd5a2** [comment]
1.man_made=silo,storage,fuel_storage_tank,gasometer are merged to poi_type name="storage_tank" tag="man_made" value="storage_tank"
2.Why do you need embankment as POI?
3.dyke added.
4.mine added (merged to mineshaft)
5.dolphin added.

**Comment by math1985** [comment]
You're right, embankment is not useful as POI.

**Comment by math1985** [comment]
Is embankment actually used at all in rendering? I can't find any references to embankment in the repository.

**Comment by xmd5a2** [comment]
Yes it is
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot%20from%202016-01-12%20221628.png

**Comment by math1985** [comment]
You're right! Where would I be able to find this rendering rule in the code?

**Comment by xmd5a2** [comment]
https://github.com/osmandapp/OsmAnd-resources/blob/master/rendering_styles/default.render.xml#L7224

**Comment by math1985** [comment]
Thanks!
