### ISSUE TITLE
Low position animation frame rate – Android Auto

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#21099]
### How to reproduce
* Connect device to Android Auto
* Start navigation (doesn't work on simulation)

### Actual result

* Location animation looks jumpy 

### Expected result

**Environment**
OsmAnd Version:
Android/iOS version:
Device model:

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/commit/60288cb3cb903628959ee96a472d4e403e4b8609
