### ISSUE TITLE
"pre-turning" map rotation when following a route

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#21107]
### Description

I know, this "feature" was mentioned some time ago in another issue.
It would be great to be able to switch it "off".
Especially in unfamiliar areas / cities and in heavy traffic this function sometimes is VERY irritating. like:
heading to an intersection (left or right), being busy with watching lots of traffic, then >>> havin a short view at osmands screen >>> seeing "straight route line".

But: my position still is BEFORE the intersection, but Osmand already did the turn and shows the route already as a straight line, as being around the corner already.

This does not happen on every intersection, but sometimes, especially if one has to stop immediately before the intersection.
And if one is already busy with the rush hour traffic, this "pre turning the map" is really annoying.

It really would be great to have the possibility to switch this funcion off. it frequently drives me crasy.
Thanks!

### Steps to reproduce

see above.

### Actual result

see above.

### Expected result

see above.
Thanks!

### Your Environment (required)

A13, +4.8.6

**Comment by scaidermern** [comment]
I think this was fixed in #19706 for 4.9.x

**Comment by Rowin63** [comment]
Ah, thanks! "premature" was the term I didn't find 😉👍
