### ISSUE TITLE
Current track blinking while recording

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#21106]
## Description
Previous issue https://github.com/osmandapp/OsmAnd/issues/19705

### How to reproduce
* Start trip recording

### Actual result

<table style="width:100%">
  <tr>
    <th>Android</th>
    <th>Android Auto</th>
  </tr>
  <tr>
    <td><video src="https://github.com/user-attachments/assets/071ea3fe-8d4b-47ed-9bb4-3dc34ab21c33"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/user-attachments/assets/192fe663-3e6e-4930-b948-e2da51ca3196"  width="480" height="auto"/> </td>
  </tr>
</table>   

* Track link blinking

### Expected result

* Updates without blinking

**Environment**
OsmAnd Version: OsmAnd~ 4.9.0#3514m, released: 2024-10-22
Android: 15
Device model: Google Pixel 6A

**Comment by dmpr0** [comment]
# Review 

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src=""  width="300" height="auto"/> </td>
    <td><img src=""  width="300" height="auto"/> </td>
  </tr>
</table>   


- [ ] Direction arrows is blinking / redraw too each time new recorded segment adding. 

- - -

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/ed5c8da6-da9d-4883-b854-7ba9ec78d597"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

**Probably different task**
- [ ] Strange gaps between arrows

**Comment by vshcherb** [comment]
-  [ ] We need to avoid provider recreation and also allow animation to be updated for smooth results

**Comment by Zirochkabila** [comment]
# Testing 1

`OsmAnd~ 5.0.0#3985m, Released: 2024-12-23` - Blinking of the recorded route and directional arrows is Fixed

But:
1. Route being recorded is ahead of the location (AA also) 
2. Directional arrows (on the track being recorded) are constantly changing their location - **perhaps** we can leave an arrow in place and add a new one as the track is being recorded (something like snapping an arrow to an imaginary point)




<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><video source src="https://github.com/user-attachments/assets/72f403fe-4f3e-4f3f-ae96-3ae25c1d6317"  width="300" height="auto"/></td>
    <td><video source src="https://github.com/user-attachments/assets/d05470a1-14a1-4961-a76f-3dbc6c0f5e19"  width="300" height="auto"/></td>
    <td><video source src="https://github.com/user-attachments/assets/cc7d79a9-e6ff-469e-983b-f681d1ae2766"  width="300" height="auto"/></td>
  </tr>
</table>
