### ISSUE TITLE
Link from http://osmand.net/help/docs/Custom_Rendering_How-To.htm broken

### ISSUE THREAD

**Issue by SomeoneElseOSM** [osmandapp/Osmand#2111]
There's a link from there to https://github.com/osmandapp/OsmAnd-jni/tree/master/java/net/osmand/render , which doesn't seem to exist currently.  Has it moved somewhere (and if so where?) or is http://osmand.net/help/docs/Custom_Rendering_How-To.htm itself out of date?

**Comment by sonora** [comment]
The updated link is https://github.com/osmandapp/OsmAnd-resources/tree/master/rendering_styles. The file to use as a template if you wanted to create a completely new "depends" renderer (i.e. defining all the diffs from our default renderer default.render.xml) is "Depends-template.render.xml." Our built-in renderers in that same rendering_styles folder on github can serve as examples of such "depends renderers".

**Comment by sonora** [comment]
Fixed via https://github.com/osmandapp/osmandapp.github.io/commit/f8037b532ccad757e5f0cc1bdf814630092a6fa7

**Comment by SomeoneElseOSM** [comment]
Excellent - just what I was looking for, thanks.
