### ISSUE TITLE
Live Updates allows duplicate downloads of maps  

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2112]
Hi

The Live Updates feature allows duplicate download of maps.
(This problem is already reported for the normal map update as well.)

Instead of downloading, OsmAnd downloads two copies of the same live update in parallel.

**Comment by vshcherb** [comment]
Can't reproduce for now.

**Comment by raindropsfromsky** [comment]
Strange! I can do this consistently!

But it happens with India map only, not with English Wikipedia map.

This is how to reproduce this bug:
1. In the Drawer menu, tap on the "Live updates" option.
    It shows India and Wikipedia entries.
    If I tap on any one, it shows the control panel.

2. For the India map, the Last map update is dated 3rd Jan, and Last update is 5th Jan.
    (In other words, there is no Live update available now.)
    In fact, the **Update size** is 0 KB; which confirms this.

    Yet, if I tap on the **Update now** button, OsmAnd starts downloading SOMETHING.
    Further, if I tap the same button multiple times, it launches one more download.
    I could add up 10+ downloads this way.

    I have taken the screenshot, but cannot upload it right now (connectivity issue at work).
    Will update it from home tonight.

**Comment by raindropsfromsky** [comment]
Here is the screenshot: 
![screenshot_2016-01-05-17-04-06](https://cloud.githubusercontent.com/assets/9047168/12117337/30ccaf68-b3e6-11e5-9131-3a5f6d5214ee.png)

**Comment by raindropsfromsky** [comment]
I just noticed that they have three different sizes: 1.3 MB, 2 MB, and 2.8 MB,

**Comment by vshcherb** [comment]
It was fixed the same day actually and it was related to all downloads
