### ISSUE TITLE
deviation from the main road

### ISSUE THREAD

**Issue by brunodebiasi55** [osmandapp/OsmAnd#21123]
### Routing engine

- [X] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

motorcycle, no restrictions

### Start and end points

START: Italy - Comeglians (UD)
ENDPOINT: lago di Cavazzo

<table style="width:100%">
  </tr>
  <tr>
    <th>Actual route</th>
    <th>Expected route</th>
  </tr>
  <tr>
<th><img src="https://github.com/user-attachments/assets/b66ab555-b518-4e41-8726-21e7832bf601"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/119f0d18-bcbd-4bd4-abb6-ed5aebbd613d"  width="300" height="auto"/> </th>
  </tr>
</table>

### Maps you used (online or offline)

- [x] Offline maps offered within the OsmAnd app for download. 
- [ ] Online (tile / raster) maps 

### Your Environment

```
OsmAnd Version: OsmAnd+ 4.8.6
Android version: 14
Device model: SAMSUNG S21 Ultra

```
/

**Comment by brunodebiasi55** [comment]
track:
[Comeglians - lago di Cavazzo.zip](https://github.com/user-attachments/files/17494155/Comeglians.-.lago.di.Cavazzo.zip)

**Comment by scaidermern** [comment]
Could be because of `maxspeed=50` here:
* https://www.openstreetmap.org/way/25337492
* https://www.openstreetmap.org/way/52576858
While the link road has no maxspeed tag: https://www.openstreetmap.org/way/25337435

Is this low maxspeed correct? Does the link road really have no maxspeed?

**Comment by DmitryAlexei** [comment]
Actual route [link](https://osmand.net/map/navigate/?start=46.406506,12.985228&end=46.404390,12.993629&profile=car#17/46.40530/12.98683) cost **341**

proposed route [link](https://osmand.net/map/navigate/?start=46.406506,12.985228&end=46.404390,12.993629&via=46.405589,12.990260&profile=car#17/46.40530/12.98683) cost **344**

**Comment by brunodebiasi55** [comment]
I don't know the limits of those roads, since I don't live in the area
I just asked to take me from one place to another

**Comment by Max1234-Ita** [comment]
> Is this low speed limit correct? Does the link road really have no speed limit?

Hi, suppose that OsmAnd applies some default speed limit based on the road type and the country, i.e. on residential roads in a city 50 kph, on motorways 130kph, on secondary/tertiary outside  the city 90 Kph (that's the values specified by the law in Italy)...

So also for trunk link there should be some implici speed limit also for trunk and motorway links (in Italy, usually it's 40 Kph, unless another value is explicitly specified).

Am I  wrong?

**Comment by brunodebiasi55** [comment]
hi,
yes you are right, but I don't know why the main road has a 50 km/h limit
while the exit doesn't.
maybe when it was classified they were doing work on the bridge.
in any case it's wrong that they make me exit the main road to re-enter
immediately after

Distinti saluti

Bruno De Biasi
***@***.***


Il giorno sab 26 ott 2024 alle ore 21:15 Max1234-ITA <
***@***.***> ha scritto:

**Comment by vshcherb** [comment]
```maxspeed=50``` is certainly a problem as for trunk_link max speed is higher. Probably it's possible to set tag ```maxspeed:practical=50``` on trunk_link and issue will be resolved or put "give_away" signs as it will introduce extra penalties

**Comment by scaidermern** [comment]
Just for the record, other routers don't have this problem:
* GraphHopper: https://www.openstreetmap.org/directions?engine=graphhopper_car&route=46.406573%2C12.985174%3B46.404257%2C12.994034
* OSRM: https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=46.406573%2C12.985174%3B46.404257%2C12.994034#map=17/46.405419/12.989611&layers=N
* Valhalla: https://www.openstreetmap.org/directions?engine=fossgis_valhalla_car&route=46.406573%2C12.985174%3B46.404257%2C12.994034#map=17/46.405411/12.989611&layers=N

Somehow they manage to not exit the trunk road, pass two trunk links and enter the same trunk road again that was previously left.
