### ISSUE TITLE
Show "Avoid this spot" markers on map

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2113]
The length of a typical road may vary from a few meters to a few thousand km.
But when a user asks OsmAnd to avoid a road, he does not mean "avoid the entire road".
The ban is applicable to the SPOT, till the next junction on that road.
(OsmAnd is free to skirt the spot and continue on the road from the nearest junction).

In other words, only a segment of the road is banned, containing the specified ***point on map***.

Given this, OsmAnd should display a "Men at work" or "Banned" marker on that spot.

This will be useful when the "Avoid road" list is inherited from a previous trip (#2103).

The user will be alerted that the current shape of the route is thanks to a block at a given spot.
If that block is not in effect any longer, he can remove it and get a natural routing.

**Comment by sonora** [comment]
Related to issue #2103.

**Comment by GaidamakUA** [comment]
We have implemented markers on road, but changing routing algorithm is a bit more complex.

**Comment by raindropsfromsky** [comment]
I had not envisaged any change in the routing algorithm; except-
 * When the ***break-point*** is selected and deleted, OsmAnd should automatically recalculate the route, without waiting for a second command.

BTW is this feature available in the nightly now?

**Comment by raindropsfromsky** [comment]
Update: Checked the latest nightly and found that this feature is working. The marker can be deleted, and OsmAnd immediately restores the original route.

But I also found that sometimes the "Men at work" icon is too far from the diverted route. In that case the user never gets a hint that this is a diverted route; not original. Thus he stands the risk of using a route that is unnecessarily long.

So, the features suggested in #2103 also are needed. 

But note that OsmAnd must calculate the new route first, and only then it can check whether any of the existing road-blocks are in the path of that new route. At that stage, the user has already set all points on the new route (start-point, way-points, end-point); and pressed ***Go***. He normally does not expect any adverse indication at all. (OsmAnd announces the route length and trip time; and shows the purple route line.)

So if there is a glitch, the best way to alert him is to pop up an warning message card: This route passes through x road-blocks. Do you want to review them? 

Also make audio announcement.

If the user knows that those road-blocks are eliminated, he can delete them.

**Comment by sonora** [comment]
Implemented.
