### ISSUE TITLE
Feature request: add option to validate OSM login details

### ISSUE THREAD

**Issue by keunes** [osmandapp/Osmand#2114]
Currently there is no way to validate OSM login details that are entered in the 'Edit OSM' settings. If a user (this happened to me) doesn't fill in correct login details, OSM remarks/edits (don't know the correct English term) are uploaded as 'anonymous' rather than giving an error for the login details. This is annoying if you want to be able to find, give extra info to or solve your own remarks on a computer.

It would be nice if login details could be validated with the tap of a button after filling in the two settings.

As a user, i could imagine the following solution: another button between 'password' and 'offline editing' with the title 'Validate login' or sth, plus
- default: 'tap to check your login credentials' (regular text colour)
- 'your login details are correct' (green text)
- 'we couldn't log in with these details' (red text)

Where the additional text should revert back to the default after password or username has been edited.

**Comment by vshcherb** [comment]
To validate user  we could use  https://api.openstreetmap.org//api/0.6/user/details call and Basic Authorization.
