### ISSUE TITLE
Feature request: Country-specific preferred language

### ISSUE THREAD

**Issue by jonlachmann** [osmandapp/Osmand#2115]
I am from Sweden and use Osmand while abroad and while at home, while abroad I prefer to use English names to be able to understand and pronounce names of cities and places. But when I am at home I prefer to see the names in Swedish.

My feature request is that I should be able to set a preferred language per country that overrides the global setting.

**Comment by vshcherb** [comment]
Now you can do that manually, we have information about what is the mostly spoken language. Though we need to know is the device abroad or home to understand and switch it. For now it is not that critical to switch manually, cause it doesn't happen often, but we need to think how to implement this simplification.

**Comment by mxa** [comment]
I think this would be the best to handle like a browser handles languages. The user sets a priority list of languages and osmand will display objects with the language tags of the list. Sounds trivial, but is also tricky in the details as you can see in this example from the Go language https://blog.golang.org/matchlang

**Comment by sonora** [comment]
User can simply adjust manually, no further action planned here, I guess.
