### ISSUE TITLE
PNOA (ES) map shown misplaced

### ISSUE THREAD

**Issue by NeilJared** [osmandapp/OsmAnd#21159]
### Description

See caption, as seen zooming out to understand it is not working as it should

### Steps to reproduce

Just activate PNOA (ES) map layer and zoom out to see it misplaced 

### Actual result

Map layer shown out of boundaries

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/c9e69bdd-9c43-4885-8a80-d6d819b658cd"  width="300" height="auto"/> </th>
  </tr>
</table>

### Expected result

Should match coordinate systems

### Your Environment (required)

```
OsmAnd Version: latest
Android/iOS version: 14
Crash-Logs: none
```

**Comment by NeilJared** [comment]
![Uploading Screenshot_2024-10-27-09-46-42-524_net.osmand.plus-edit.jpg…]()

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To replicate it, navigate to Menu → Configure map → Overlay map → PNOA (ES), and zoom out the map to the maximum level.

At the smallest scale, you’ll notice that the map layer appears disjointed, displaying in a chaotic manner with various layers not aligned integrally.

OsmAnd~ 4.9.0#3591m, released: 2024-10-29

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/68e8e742-822b-4202-bacc-5e5dc5f6e42f"  width="300" height="auto"/> </th>
  </tr>
</table>
