### ISSUE TITLE
Fords, displaying depth

### ISSUE THREAD

**Issue by 7tonin** [osmandapp/OsmAnd#21163]
### Describe the idea

When you are planning a hike, reading the map you see a ford. But there is no clue if this ford is easy to cross or not. 

### Expected behaviour

When a travel crosses several fords, the details screen lists them like it does for the surface, quality, ... etc, of road.
On the map, when selecting a ford, the depth is displayed somewhere.

### Alternatives you've considered

watching the node data on openstreetmap.org

### Context

Some fords are 0.05 m depth, orther 0.8 m depth. Expectation depends on: walking, or riding bicycle or horse.

**Comment by vshcherb** [comment]
As of now, you can click on icon and see details.

**Comment by yuriiurshuliak** [comment]
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/b70c5439-fd70-4982-ba1b-4dfc7b8b7dfe"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by 7tonin** [comment]
Yes, indeed, it is. 
Sorry 😳

**Comment by 7tonin** [comment]
Well 😳😳
the only missing information is a summary or list of fords when the calculated itinerary is displayed with its details.

**Comment by vshcherb** [comment]
Yes we have planned the whole Route details redesign to display waypoints and obstacles such as fords to be displayed their. I will close as duplicate
