### ISSUE TITLE
Region name "Lower Saxony, Bremen" not translated into german

### ISSUE THREAD

**Issue by BlueIce** [osmandapp/OsmAnd#21161]
### Description

I'm using OsmAnd on a phone with german as system language. All german region names are translated correctly into german except of `Lower Saxony`.

Might be related to #19459.

### Steps to reproduce

1. Use OsmAnd with german language
2. Go to map downloads
3. Select `Europa` -> `Deutschland` (`Europe` -> `Germany`)
4. Scroll down to regions

### Actual result

There is a region with name `Lower Saxony, Bremen`.

### Expected result

The name for the region should read `Niedersachsen, Bremen`.

### Your Environment (required)

```
OsmAnd Version: OsmAnd+ 4.8.6
Android/iOS version: Android 15
Device model: Pixel 6a
Crash-Logs: -
```

**Comment by scaidermern** [comment]
Can confirm with OsmAnd 4.9.0.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-iOS/issues/4044

**Comment by vshcherb** [comment]
Translations should be present already https://github.com/osmandapp/OsmAnd-iOS/issues/4044, if it doesn't work please consult @xmd5a2
