### ISSUE TITLE
Search for category school does not work

### ISSUE THREAD

**Issue by Spielmops** [osmandapp/OsmAnd#21162]
### Description

I'm in Germany and had to search for a certain school in Hamburg. So I tapped on search/catergory and typed "schule". All I got was "Nachhilfe", " Schule (Gastronomie) and "search Schule". No category "Schule"!
I could create a customized category, " Schule" was as expected in "Bildung".

Spielmops

OS: LineageOS 20
Osmand 4.8.6

### Steps to reproduce

Search for category "Schule"

### Actual result

Nothing

### Expected result

Shown category "Schule"

### Your Environment (required)

LineageOS 20
Osmand 4.8.6

**Comment by yuriiurshuliak** [comment]
The issue could not be reproduced. To reproduce, try locating the School category via search, or go to Search > Categories > Custom Search > Education > School.

When tested, the School category successfully displayed relevant results on the map. You can refer to this guide for further assistance: https://osmand.net/docs/user/search/search-poi/#custom-poi-search

Additionally, you may test this on our nightly version: https://osmand.net/docs/versions/nightly_versions#nightly-builds

OsmAnd~ 4.9.0#3582m, released: 2024-10-27

https://github.com/user-attachments/assets/25896887-46ea-49e9-bad8-0033ee6faa13

**Comment by Spielmops** [comment]
Either my english is bad or you did not read, what I wrote. Your video ist not helpful, because it it to fast, I can not follow.

"So I tapped on search/catergory and typed "schule". All I got was "Nachhilfe", " Schule (Gastronomie) and "search Schule". No category "Schule"!"

![Keine-Kategorie-Schule](https://github.com/user-attachments/assets/82aed27c-a882-4539-951d-10a5ac6c605a)

**Comment by Spielmops** [comment]
Ok, I will wait for that version.

**Comment by vshcherb** [comment]
4.9.2 is in beta and we plan this / next week release 4.9.3 for 5% staging rollout
