### ISSUE TITLE
Showing interests points of Wikivoyage Tokyo leads to Xinjiang China

### ISSUE THREAD

**Issue by Guylby** [osmandapp/OsmAnd#21160]
### Description

Hi,

When trying to see the gpx points of interests of Wikivoyage of the region around Tokyo, you will be redirected to some area in China.
I've tried this with Tokyo and a few other areas like Shibuya or Shinjuku and the result is the same.

All the gpx points are aligned along one longitude and share the same long coordinate: 84.55110°E

I've checked directly on wikivoyage and their points seem to be correctly shown in Tokyo. 

### Steps to reproduce

Download Wikivoyage data for Asia
Go to Tokyo, open the Wikivoyage travel guide for Tokyo
Open points on the bottom
All points are in China

### Actual result

https://github.com/user-attachments/assets/8624c98c-da1e-4c81-a58a-dd219145d9fb

### Expected result

Points are correctly shown on the Tokyo map

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.9.0
Android/iOS version: 13
Device model: Sony Xperia 10 III
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce it, download Wikivoyage data for Asia, navigate to the Travel guides (Beta) tab, search for Tokyo, and select Points at the bottom of the screen.

As a result, you'll observe that all Tokyo points appear incorrectly located within China.

OsmAnd~ 4.9.0#3582m, released: 2024-10-27

https://github.com/user-attachments/assets/23db7e1b-5938-4930-8d1d-6a5f0dd77d7e

**Comment by vshcherb** [comment]
They located wrongly at 84.55110 E where it supposed to be at  long=139.7417818 (according to https://en.wikivoyage.org/wiki/Tokyo?action=raw)
```
* {{flag|Poland}} {{listing
| name=Poland | alt= | url=http://tokio.msz.gov.pl/en/ | email=tokio.amb.sekretariat@msz.gov.pl
| address=2-13-5 Mita, Meguro-ku, 153-0062 | lat=35.63942 | long=139.70861 | directions=
| phone=+81 3 5794-7020 | tollfree= | fax=+81 3 5794-7024
| hours= | price=
| wikidata=Q30906141
| content=
}}```

**Comment by vshcherb** [comment]
Wikidata also has correct location - https://www.wikidata.org/wiki/Q30906141 (```35°38'21.80"N, 139°42'31.18"E```), probably parsing is not correct

**Comment by RZR-UA** [comment]
The bug is fixed, and *.travel.obf.zip files are regenerated. @Guylby, please update (remove+download) the Asia wikivoyage map file and try again.

**Comment by Guylby** [comment]
I've updated the Asia wikivoyage file and everything works perfectly! Thanks for the fix!
