### ISSUE TITLE
The order of Objects (wrong rendering)

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#21164]
### Description

objects are displayed in the wrong order for Eindhoven Centraal

### Steps to reproduce

1. Download the Eindhoven map (the Netherlands) 
2. Go to this object https://osmand.net/map/configure/?pin=51.443115,5.480150#18/51.44323/5.47933
3. for rendering type Version 1 and Version 2 we have the same result.

### Actual result

 the picture shows wrong order where the platform goes under the building

<img width="400" alt="image" src="https://github.com/user-attachments/assets/a58b41d6-7424-4f3c-8af7-b26d144a13dc">

### Expected result

 the picture based on OpenStreetMap shows the correct order with the platform and the railway track above the building.

<img width="400" alt="image" src="https://github.com/user-attachments/assets/a9a57fec-5d37-4f04-b720-5550352f8320">

### Your Environment (required)

```
OsmAnd Version: 4.9.2
Android/iOS version: 14
Device model: Samsung S22
```

**Comment by xmd5a2** [comment]
Fixed. No new maps required.

**Comment by Zirochkabila** [comment]
# Testing 1

**Fixed**
> Web
> OsmAnd~ 5.0.0#3935m, Released: 2024-12-16
> 4.9.1.4923
