### ISSUE TITLE
Quotes are rendered as &quot; at 10-11 map zooms

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#2117]
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%20%D0%BE%D1%82%202016-01-05%2011%3A14%3A58.png
This is zoom 10, map is Russia_vladimir_asia_2.obf.zip
Other zooms (12+) are ok.

**Comment by vshcherb** [comment]
The issue is in the data and in the python script I guess, we need to download the basemap.osm.bz2 and check the xml. Please contact me to resolve that issue.

**Comment by xmd5a2** [comment]
Fixed
