### ISSUE TITLE
Broken Link: OSMAnd Live

### ISSUE THREAD

**Issue by jaller94** [osmandapp/OsmAnd#21172]
### Description

The OSMAnd Live view has a broken documentation link 

### Steps to reproduce

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/40f7424a-ccab-4f1f-87dc-164f71d07d1d"  width="300" height="auto"/> </th>
  </tr>
</table>

### Actual result

Links to a Page Not Found error

https://osmand.net/docs/user/personal/maps#osmand-live

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/8c2245dd-4c32-4ea9-9794-941879017d90"  width="300" height="auto"/> </th>
  </tr>
</table>

### Expected result

* Fix the link in the app
* Revive the broken URL by redirecting people to the new URL

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.8.6 from F-Droid
Android/iOS version: 14
Device model: Fairphone 4
Crash-Logs: ?
```

**Comment by vshcherb** [comment]
Fixed https://github.com/osmandapp/Osmand/blob/f1ffbac9f3bda36ada3373b58f74895c1f3556e2/OsmAnd/res/values/links.xml#L44
