### ISSUE TITLE
Navigation mode for Android Auto not working correctly

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#21177]
### Description

Navigation mode doesn't work correctly for Android Auto. 

### Steps to reproduce

1. Launch the device to a vehicle multimedia system with Android Auto
2. Start navigation in OsmAnd 4.9.2 (Beta) Android Auto

### Actual result

Navigation Mode for Android Auto has a navigation line but no navigation instructions (it's very similar to Free ride mode). The device's screen doesn't have a block screen when using AA. 

<img width="586" alt="image" src="https://github.com/user-attachments/assets/e7750d48-00d4-4d6c-ae2b-cebcc01f2f6a">

Sometimes for night mode

<img width="600" alt="image" src="https://github.com/user-attachments/assets/ee889b21-f5bf-4c30-adee-607f6f2f96d1">

It looks like some hidden profile is being used, not the one that is active in the application itself.

### Expected result

<img width="953" alt="image" src="https://github.com/user-attachments/assets/8cffdff9-9d3b-429a-8417-ba362bf5f4b2">

### Your Environment (required)

Device : r0s
Brand : samsung
Manufacturer : samsung
Model : SM-S901B
Product : r0sxeea
Build : UP1A.231005.007.S901BXXSBEXG8
Version : 14
App Version : OsmAnd
Apk Version : 4.9.2 4902

**Comment by Yaper** [comment]
Yes, I can confirm it. Navigation started, but there are no route info at all.
Additionally there is no possibility to terminate navigation from AA.
This is very annoying bug.
![screendump - 2024-10-26-19_30_17](https://github.com/user-attachments/assets/7af9c4ae-fc1e-4196-bc57-9a5c7f50cb97)

**Comment by vshcherb** [comment]
Yes, it's very strange cause it's not reproducing with nighly builds before and after. Potentially there is a fix here https://github.com/osmandapp/OsmAnd/commit/155fed6a8ccf4e7cf440e9ea090acad775ad9195

**Comment by EugeneZmeuk** [comment]
> Yes, it's very strange cause it's not reproducing with nightly builds before and after. Potentially there is a fix here [155fed6](https://github.com/osmandapp/OsmAnd/commit/155fed6a8ccf4e7cf440e9ea090acad775ad9195)

It's reproduced for the last beta version (4.9.2 4902). I will test with the next release (or beta) version
