### ISSUE TITLE
Break up large regions

### ISSUE THREAD

**Issue by morray** [osmandapp/Osmand#2118]
Some regions have become really big ( e.g. larger than 400 mb). It should be considered to split them up into smaller subregions so users use less space on their phone and servers face lower load. Also offering some major cities like new York, Sydney, Hong Kong, and Tokyo could be a way.

**Comment by vshcherb** [comment]
We do it one by one and we try to monitor the next big region. The city option is nice to have but this requires some implementation.

**Comment by sonora** [comment]
Mostly implemented or ongoing process.
