### ISSUE TITLE
Osmand 4.8.6 4806 crashes just after starting to find a way between two locations

### ISSUE THREAD

**Issue by CharlieLedocq** [osmandapp/OsmAnd#21195]
Hi,
Since I have upgrade from version 4.2  to 4.8.6 4806, I cannot use Osmand any longer: it crashes just after defining start and arrival locations upon pressing the start key. A message reports " The Osmand application has been stopped" or something like that. I have sent a few crash reportsDOTlog. I would like to downgrade to Version 4.2. which has worked like a charm without flaws for  at least two years as now.
Thanks for any help.
 🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please do not file questions or support requests on the GitHub issues tracker.

In case you aren't sure whether to open an issue or not, please send your request to support@osmand.net.

You can get your questions answered using the [Google group](https://groups.google.com/forum/#!forum/osmand) or chat in real-time via our Telegram instances: [English](https://t.me/OsmAndMaps), [German](https://t.me/deosmand), [French](https://t.me/frosmand), [Ukrainian](https://t.me/uaosmand), [Italian](https://t.me/itosmand), [Russian](https://t.me/ruosmand).

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by vshcherb** [comment]
Related to broken october maps and bug in the code. Bug is fixed in 4.9.2 beta and new maps are being prepared in 3-4 days.
