### ISSUE TITLE
The current recording track disappears when scaling on engine 1

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#21193]
### Description

If you scale a track so that it doesn't fit entirely on the screen when recording it, it disappears. The problem is only with rendering engine 1.

https://github.com/user-attachments/assets/ed64c6ec-63c8-42e0-80c0-871e79e69b0c

### Steps to reproduce

described above.

### Actual result

the track stops displaying

### Expected result

the track does not disappear

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:OsmAnd~ 4.9.0#3600m, Дата выпуска: 2024-10-29
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
The bug has been confirmed. To reproduce it, switch the rendering to Version 1, start recording your route with Trip Recording enabled, and attempt to zoom in on the recorded path.

The result shows that at certain zoom levels, the recorded track disappears from map.

OsmAnd~ 5.0.0#3623m, released: 2024-11-01

https://github.com/user-attachments/assets/b2366a15-f548-4a03-8492-9cebe6c22391

**Comment by vshcherb** [comment]
Yes but low priority as it only legacy rendering engine

**Comment by Zirochkabila** [comment]
# Testing 1

`OsmAnd~ 5.0.0#4062m, Released: 2025-01-06` - Fixed
