### ISSUE TITLE
Unable to export Wikipedia filex

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#21205]
### How to reproduce
* Download **Wikipedia** file for any country
* Go to **Menu** - **Settings** – **Export to file** - **Resources** – **Wikipedia and Travel maps**
* Tap on checkbox 

### Actual result

<table style="width:100%">
  <tr>
    <th>Wikipedia files</th>
    <th>Video</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/ee4ecb97-c619-427e-abe7-12ca7bd57a6b"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/user-attachments/assets/e8ac7ab7-0168-44cc-b03b-3be53ce02374"  width="300" height="auto"/> </td>
  </tr>
</table>   

* Error toast `You have no items of this type`

### Expected result

* Export 

**Environment**
OsmAnd Version: OsmAnd~ 5.0.0#3620m, released: 2024-11-01
Android: 15
Device model: Google Pixel 6A

**Comment by 0xRe1nk0** [comment]
Bug couldn't be reproduced

https://github.com/user-attachments/assets/f6d82d4b-2327-4d25-a083-bcf16b4cc674
