### ISSUE TITLE
Disable POIs

### ISSUE THREAD

**Issue by Goodingn** [osmandapp/Osmand#2121]
I'd like the cleanest possible view of the roads when navigating.  I've turned off (selected) all the hide details options and turned off all the Transport options, but POIs still show at most zoom levels:

1000 yd, train stations and some bus
500 yd, above and petrol stations
200 yd, above and bus stops
100 yd, everything

200 yd is included in long range auto zoom and 100 yd is included in mid range auto zoom.

**Comment by vshcherb** [comment]
I think it is related to the car navigation only, we need to thoroughly looked into it to not create another issue, while fixing this one.

**Comment by xmd5a2** [comment]
Added "Hide icons" option in "Hide" submenu.
