### ISSUE TITLE
Sun position Widget -  column jittery when information changes

### ISSUE THREAD

**Issue by Davi427** [osmandapp/OsmAnd#21213]
### Description

The widgets (in this case the time until sun position next event) change length when going from 1 hour to 59 minutes. This results in the whole column being resized again and again and again.

### Steps to reproduce

Have a widget on screen that has a variable length, for example time until sun position next event.

### Actual result

The column is resized, in certain cases over and over.

https://github.com/user-attachments/assets/b562a53a-a3e1-48e0-96ab-a239078c5b9d

### Expected result

The column is fixed width, it does not get resized during navigation because this is an unnecessary distraction.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd+ 4.9.2, Released: 2024-10-25
Android/iOS version: 14
Device model: FP5
Crash-Logs: ?
```

**Comment by vshcherb** [comment]
Label should always be "h" as it doesn't change format
