### ISSUE TITLE
Switching "Hiking trails difficulty grade" on hides highway=path (without grade, I suppose)

### ISSUE THREAD

**Issue by grinapo** [osmandapp/OsmAnd#21218]
### Description

Switching "Hiking trails difficulty grade" make `highway=path` invisible, unless it has a SAC grade. 

### Steps to reproduce

1. Choose OsmAnd (or UniRS) style
2. switch on "Hiking trails difficulty grade"
3. paths are gone.

### Actual result

Paths invisible.

### Expected result

Paths without SAC scale stay as they were, while those with SAC scale shown... whatever their appearance is supposed to be (apart from invisible).

### Your Environment (required)

```
OsmAnd Version: Nightly 4.9.0#3500m 2024-10-21
Android/iOS version: 12
Device model: mi10p
```

**Comment by yuriiurshuliak** [comment]
I reviewed the "Hiking Trails Difficulty Grade" feature, but could not reproduce the issue. Here’s a summary of how this feature works:

Some trails show different colors for difficulty based on either the SAC (Swiss Alpine Club) or CAI (Italian) classifications, each specifying the required equipment for mountain trails. Currently, OsmAnd only supports these two classifications.

If SAC is enabled, only trails marked with SAC difficulty will display; the same applies if CAI is selected.

Here is the relevant documentation: https://osmand.net/docs/user/map/routes/#hiking-trails-difficulty-grade

To view all hiking trails, enable Hiking Routes. This includes trails categorized by type: local (lwn), regional (rwn), national (nwn), and international (iwn).

**Comment by grinapo** [comment]
> If SAC is enabled, only trails marked with SAC difficulty will display; the same applies if CAI is selected.

Help me to exactly understand:

If I enable "Hiking Trails Difficulty Grade" feature and none of the ways on the display does have SAC (or CAI, depending on the setting) tagging then all the ways will be invisible?

### My expectation was
- if a trail is SAC tagged then it is displayed and colored accordingly
- if trail does not have SAV tagging then it is displayed and colored as it was without the feature, according to the general coloring rules.

### What I see 
instead, when I switch it on and move to an area where nothing is SAC-scale-tagged:
- tracks and highways are as they were
- paths are all **invisible** (gone)
- path OSMC coloring is visible _without_ the paths.

**Comment by vshcherb** [comment]
Routes and Trails are displayed as special transparent lines or bubles on top of existing lines, so if you disable them you should still see normally rendered paths.
In theory routes and trails (difficulty grade is a trail feature) don't exchange, so you should be able to see both of these features independently.

**Comment by grinapo** [comment]
@vshcherb that is what I expected. Also, since I have switched it off the "hidden paths" problem wasn't reoccuring (but I weren't using it a lot since), but right now I cannot reintroduce the bug by simply switching it on again (no matter whether it's SAC or italian), even if I remember exactly the area where it have failed. (I remember it well since it was pitch dark, forgot to bring headlight and OsmAnd didn't show the path :-)).

So I guess it's not "just" related to switching it on but keeping it on while changing possibly other things, but I cannot reproduce it right now. You may keep this issue open and wait whether it's coming back (now I know where to look) or close the issue and I'll reopen it in case of reappearing problem. Probably that'd be best.

Thanks!
