### ISSUE TITLE
"Osmand keeps crashing" v 4.9.2 beta

### ISSUE THREAD

**Issue by CharlieLedocq** [osmandapp/OsmAnd#21219]
Osmand 4.9.2 do not stop crashing

A first crash happened after planning and starting a bicycle trip.

When reopening the navigation screen, I see the formerly start and arrival encoded adresses already filled in.
Just after pressing the start key, and before of the trips calculation, Osmand crashes with "Osmand do not stop hanging up" (french: "Osmand ne cesse de s'arrêter".

(Crash report logcat.log sent via gmail to crash@osmand.net)
Thanks for your time. Charlie

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/469f719a-27d0-417c-bc6d-1cb8d648b420"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/70e474d2-e18a-4390-bc5b-55e285135d8a"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by yuriiurshuliak** [comment]
We received your logcat.log, but unfortunately, it’s not sufficient to determine the cause of the crash. Please provide a Crash log file instead. When the app crashes, go to Menu > Help > Send crash log file to help us investigate the technical details of the issue.

Additionally, please provide detailed steps to reproduce the crash, including the coordinates or a GPX file where it occurred, along with an export of your profile settings. You can zip these files and attach them directly here.

**Comment by vshcherb** [comment]
If it crashes during routing, you need to redownload new maps and try new version 4.9.3 beta
