### ISSUE TITLE
Crash when recalculation is needed

### ISSUE THREAD

**Issue by thuryn** [osmandapp/OsmAnd#21216]
### Description

I've checked an existing issues and no one is the same.

It started to happen recently but I'm not sure if this is caused by update od OS or Osmand.

When recalculation is needed sometimes app crashes (sometimes not - I'm not sure why, maybe the length of the route).
I've tried to capture logcat - see attachement. It seams that the crach start with:
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8 in tid 25958 (pool-6-thread-1), pid 25837 (net.osmand.plus)
[osmand_logcat_11-03-2024_12-55-31.txt](https://github.com/user-attachments/files/17610756/osmand_logcat_11-03-2024_12-55-31.txt)

### Steps to reproduce

I'm not sure how to reproduce this error. It happens whem I'm driving and route should be recalcualted. But it works sometimes.

### Actual result

App craches.

### Expected result

It recalucalculates and continues working.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: Osmand+ 4.8.6
Android/iOS version: Evolution-X 9.5 (Android 14,  security fix from 1.10.)
Device model: Oneplus 9 Pro
Crash-Logs: attached
```

**Comment by yuriiurshuliak** [comment]
Please try our nightly version to check if this crash still occurs: [Nightly Builds](https://osmand.net/docs/versions/nightly_versions#nightly-builds).

Additionally, to help us identify the issue, we need a Crash log file rather than a logcat. When the app crashes, go to Menu > Help > Send crash log file. This will provide us with the necessary technical details for investigation.

**Comment by thuryn** [comment]
I've just installed nightly release a I will try it. I also do my best to send crash report from the app even it is hard to do it on motorbike. I'll do my best to get rid with this problem. Thank you.

**Comment by yuriiurshuliak** [comment]
The nightly version of the app provides early access to updates that will be included in the official release, allowing for testing and feedback. OsmAnd produces daily Ready-To-Use builds, enabling users to stay informed about new features and contribute to OsmAnd's development.

**Comment by thuryn** [comment]
I can confirm that the nightly version works fine. When does it go to production?

**Comment by vshcherb** [comment]
Updating maps is already possible, beta release, release is currently 2% out. So overall probably this / next week
