### ISSUE TITLE
Living street access in different country's

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/Osmand#2122]
In Austria/Hungary/Poland/Russia/Slovakia/Ukraine it is not allowed to drive trough living streets.
Osmand+ 2.2.4 not support the [Access-Restrictions] (http://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Access-Restrictions).

I tested this in Austria with way [4448846] (http://www.openstreetmap.org/way/4448846).
Omand sold use the way from second picture without extra waypoint.

1.
![wrong way](http://fs5.directupload.net/images/user/160106/3992erm5.png)

2.
![correct way](http://fs5.directupload.net/images/user/160106/x22omptm.png)

**Comment by vshcherb** [comment]
Can we automatically add tag destination for routing for Hungary during generation?
OsmAnd routing engine doesn't support country specific rules.

**Comment by xmd5a2** [comment]
Fixed 5503e077d951be3145717773d9ec6e26f2b607e1
