### ISSUE TITLE
Elevation widget has no night mode ? 

### ISSUE THREAD

**Issue by Vucumpra** [osmandapp/OsmAnd#21222]
### Description

Switching screen to dark theme is not complete

### Steps to reproduce

Simply use OSMAND with the display always on when switching from daytime to night-time hours.
When the changeover takes place, only part of the screen adopts the dark theme.

### Actual result

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/4ae35e71-b654-4827-b94d-cf7ca3db45e3"  width="300" height="auto"/> </th>
  </tr>
</table>

### Expected result

All element in dark theme

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.8.6
Android/iOS version: Android 11
Device model: One+ Nord N100
Crash-Logs: ? no crash.
```

**Comment by dmpr0** [comment]
### How to reproduce
* Set OsmAnd **App Theme** to – **System default** 
* Set **Map mode** to – **App theme**
* Set Android theme to **Day**
* Launch OsmAnd – **Navigation** with **Elevation profile** widget
* Change **Android theme** to **Night**

### Actual result

<table style="width:100%">
  <tr>
    <th>UI after theme is change</th>
    <th>Video</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/2796d233-6875-4df4-83d0-5abab317f1b9"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/user-attachments/assets/2fb4a108-61c1-4c00-af82-b1e84ef5d2b3"  width="300" height="auto"/> </td>
  </tr>
</table>   


* All UI is change to Dark theme except Elevation profile widget
* Elevation profile widget change theme only after app 

### Expected result

* All UI change theme simultaneously 

**Environment**
OsmAnd Version: 5.0.0
Android: 15
Device model: Google Pixel 6A
