### ISSUE TITLE
Broken search by coordinates

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#21223]
### How to reproduce
* Launch **OsmAnd** – **Menu** – **Search** 
* Search for ‎`49.40597 20.94758`

### Actual result

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/3864d77d-3857-4c3c-b500-663e1152e5ea"  width="300" height="auto"/> </td>
  </tr>
</table>   

* No results

### Expected result

* Search results related for coordinates

**Environment**
OsmAnd Version: OsmAnd~ 5.0.0#3641m, released: 2024-11-04
Android: 15
Device model: Google Pixel 6A

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/4091
https://github.com/osmandapp/OsmAnd/pull/21225
