### ISSUE TITLE
Offline maps on SD are not working on latest version

### ISSUE THREAD

**Issue by DangerDane** [osmandapp/Osmand#2125]
I just updated to the newest version and OSMAnd+ can see the map files and tell me there are no updates. BUT when I go to the map and start trying to type in an address i get told there are no supported maps on the SD card and tells me to download from the net. And I am at a loss since the app can find the maps but just don't want to use them... what to do???

**Comment by sonora** [comment]
Android or IOS? in Android, under the "Address search", on the top level ("Country") you should see a list of maps OsmAnd has found, indexed, and is using.

Can you please verify, not via the Update tab, but via the "Local" tab under "Manage map files", that the maps are listed there ok?

If not, please double-check in Settings/General Settings/Data storage folder that this really points to the appropriate folder where the xxx.obf files are located.

If all that is ok, please re-start your device. I'd be surprised if it still does not work, we would need more info then.

**Comment by vshcherb** [comment]
This is a known issue when you move existing sdcard between devices.
In order to get it working, your osmand maps should be in sdcard/Android/data/net.osmand.plus/files/. This is safe approach cause it works with phones > 4.4. Also you need to specify that folder in settings as  @sonora pointed out (General Settings / Data Storage).

**Comment by techlady** [comment]
I have the same issue with OSMAnd (not +) and I cannot find some of the OSMAnd tabs you mentioned. When I search for an address, I am told there are no .obf files on the SD card, despite the fact that I have created, carefully, the proper folder under Android/data on the SD card. I have rebooted twice after doing that. 
When I go into Android "Settings" then "Storage" (there is no "General Settings" or "Data storage,") I can get no listing of files. However, I can see the files on the SD card under "File Manager."
I do not see "Manage Map Files" or the "Local" tab you talk about, though I have searched every option within OSMAnd.
My device is an LG Tribute running Android 4.4. I am using the SD card with this device alone.

**Comment by techlady** [comment]
I just figured out why I cannot see the setting controls you suggested above. When I load OSMAnd, the three horizontal lines at the top left are not there. I did a reboot and they showed up briefly, but, as soon as I went back to the main OSMAnd screen, they disappeared and were replaced by an icon that looks like the "layers" icon in OSM. Does this mean I have to reboot every time I want to access "Manage Map Files" in OSMAnd?

**Comment by sonora** [comment]
While being on OsmAnd's map zcreen, can't you see the OsmAnd menu when e.g tapping your device's menu button?

**Comment by techlady** [comment]
Hardy,

         My device has no menu button. It is a 
Sprint LG Tribute. There are three electronic 
"buttons," or icons, at the bottom of the screen: 
a "Back" arrow, a "Home" button and a button that 
shows all open programs. What should this "Menu button look like?
         Another complication is that there is no 
"/" character on the keyboard, making it very 
difficult to type in the file location manually. 
It seems this device is designed to prevent use of the SD card.

Charlotte


At 03:24 PM 5/10/2016, you wrote:

>While being on OsmAnd's map zcreen, can't you 
>see the OsmAnd menu when e.g tapping your device's menu button?
>
>­
>You are receiving this because you commented.
>Reply to this email directly or 
><https://github.com/osmandapp/Osmand/issues/2125#issuecomment-218310204>view 
>it on GitHub

Charlotte Wolter
927 18th Street Suite A
Santa Monica, California
90403
+1-310-597-4040
techlady@techlady.com
Skype: thetechlady

**Comment by sonora** [comment]
Charlotte, on some devices long-tapping (for like 3 seconds or so) the "Show all open programs" button produces the functionality of a menu button. But if this does not work for you, please see my explanations in your other issue #2533, you should always see a menu button directly on the OsmAnd map screen, if not, it sounds like a bug and we need a screenshot.

**Comment by techlady** [comment]
Hardy and everyone,
Thanks for your help. Unfortunately (or maybe fortunately) my Tribute has been disabled by getting a tiny piece of paper stuck in the microUSB charging slot. So far all efforts to get it all out have failed, and I can't charge the device. So, I may have to buy a new one. This time I'll carefully check the amount of internal memory. I'll let you know how all this does or doesn't work out.
Thanks again.
