### ISSUE TITLE
wrong translation to German for tag shelter_type=lean-to 

### ISSUE THREAD

**Issue by uegert** [osmandapp/OsmAnd#21268]
### Description

The German surface of OSMand 4.9.3. (Android) translates  the tag "shelter_type=lean-to"  as "Anbau". This is not correct and could be misleading. The correct term of the German OSM for this tag is "offene Schutzhütte", as defined on https://wiki.openstreetmap.org/wiki/DE:Tag:amenity%3Dshelter.
"Anbau" in German describes an attachment to an existing building, never a standalone structure, as lean-tos are. It thus implies that there is another main building or structure that the lean-to is "leaning to" - which is never the case.

### Steps to reproduce

Set OSMand language to German. Search for shelter Rödskojan in Sweden. Open the pull up for the shelter and look for the field "Art".

### Actual result

It shows "Anbau" and "Unterstand (nicht für öffentliche Verkehrsmittel)"

### Expected result

Should show "offene Schutzhütte" and "Unterstand (nicht für öffentliche Verkehrsmittel)"

### Your Environment (required)

No crash log needed

Device : beyond0q
Brand : samsung
Manufacturer : samsung
Model : SM-G970U
Product : beyond0qltesq
Version : 12
App Version : OsmAnd+
Apk Version : 4.9.3 4903

**Comment by yuriiurshuliak** [comment]
The shelter_type=lean-to tag is no longer used in OsmAnd, as it was removed for being a duplicate. Currently, such features have been transformed to the amenity=shelter tag. You can find more details about this update in [this comment](https://github.com/osmandapp/OsmAnd/issues/19949#issuecomment-2163265308).

**Comment by uegert** [comment]
Hi, the comment you linked is about objects tagged tourism=lean_to, which would be incorrect tagging to begin with. The objects I'm referring to are tagged amenity=shelter + shelter_type=lean_to. So I think this is different. In the former case, the question would then be how the German text "Art" - "Anbau" comes about because it does show up with objects tagged amenity=shelter + shelter_type=lean_to in OSM if I pull up the objects properties. I did not try to create POIs but I would expect them to look as on the "June map" screenshot.

**Comment by DmitryAlexei** [comment]
@uegert thanks for update! Users can change translations for OsmAnd using Weblate (please see docs https://osmand.net/docs/technical/contributions/translating-osmand )  

German translation for poi_shelter_type_lean_to can be found by the link
https://hosted.weblate.org/translate/osmand/phrases/de/?checksum=28bdcbb3bdf8ed77
