### ISSUE TITLE
[amenity=fuel] Show brand insted of operator tag as title

### ISSUE THREAD

**Issue by ignaciolep** [osmandapp/Osmand#2126]
Please, consider showing the brand tag instead of the operator as the fuel station information tab title. The brand is more relevant to the end user.

![screenshot_2016-01-08](https://cloud.githubusercontent.com/assets/13091755/12198795/dd46a4d0-b5f1-11e5-878a-47417b4eb420.png)

Thanks!

**Comment by vshcherb** [comment]
Fixed
