### ISSUE TITLE
Track line disappears when the starting point is out of the map screen

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd#21266]
### Description

Sometimes when the starting point of the currently recorded track is out of the current map screen, the track line disappears. 
The exact conditions for reproducing that issue are unknown. Probably the length of the track, zoom level and maps downloaded matter.

### Steps to reproduce

OsmAnd+Apk Version : 4.9.0 4900
- start track recording
- record a track > 500 km long
- see if the track line of the currently recorded track is visible when the starting point is out of the screen

### Actual result

<table style="width:100%">
  </tr>
  <tr>
    <th>Starting point of the track on the map screen</th>
    <th>Starting point out of the screen</th>
  </tr>
  <tr>
<th><img src="https://github.com/user-attachments/assets/77cac5c5-2054-47be-b11f-78783df19d35"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/3de1d295-56ea-4393-ac35-df6abd688a52"  width="300" height="auto"/> </th>
  </tr>
</table>

### Expected result

Track line of the currently recorded track should be visible on the map screen, even when the recorded track is quite long and the starting point is out of the screen.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by Nine-Tailed** [comment]
Duplicate? https://github.com/osmandapp/OsmAnd/issues/21193

**Comment by yuriiurshuliak** [comment]
It is necessary to specify the rendering version used by the user who reported this issue for accurate investigation.

**Comment by yuriiurshuliak** [comment]
Since this user is also using 1 rendering version, this is a duplicate.
