### ISSUE TITLE
speed sign is malformed.

### ISSUE THREAD

**Issue by noci2012** [osmandapp/Osmand#2127]
When speeding a sign with the speed limit is shown. The white in the sign is not aligned with the red border. (on the left there is no red, on the right it is twice the presumably intended thickness)

**Comment by vshcherb** [comment]
Could you please provide screenshot, it is not visible for us yet.

**Comment by noci2012** [comment]
hard to make screenshot while driving... so i'll try, just don't hold your breath,

**Comment by vshcherb** [comment]
There is a simulation mode, enable Development plugin, calculate route, Dashboard, Simulate your route

**Comment by noci2012** [comment]
Might have been the previous version then, Saw this morning everything shows normal
If i see it again i will try to get more background info.
It showed up for 120 and 130 kmph short before i issued this.

BTW, simulation fails when i have no GPX and also when there is no GPS fix. it's hard to set a startpoint for route calculation (or i didn;t find it).

**Comment by vshcherb** [comment]
You can select start point on the map, simulation works only if the route is already calculated or you have recorded GPX.
