### ISSUE TITLE
Reasonable Routing tertiary -> primary causes too much penalties

### ISSUE THREAD

**Issue by AutomCoding** [osmandapp/OsmAnd#21275]
### Routing engine

- [X] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Car

### Start and end points

From [Bårslöv, Helsingborgs kommun, Sweden](https://www.openstreetmap.org/node/565488901) to [Rosengården, Helsingborgs kommun, Sweden](https://www.openstreetmap.org/relation/5525174)

### Actual route

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/6bf72131-43eb-41af-b694-5bd6a2d8c65d"  width="300" height="auto"/> </th>
  </tr>
</table>

This is the route chosen onto road 111 from E4.

### Expected route

After going round the clover leaf off E4, a left turn onto road 111 is both permitted and prefered in reality. I can not se any obstacles to this in the OSM data.

### Maps you used (online or offline)

- [x] Offline maps offered within the OsmAnd app for download. 
- [ ] Online (tile / raster) maps 

### Your Environment

```
OsmAnd Version: 4.8.6
Android version: 14
Device model: Samsung Galaxy S21 5G

```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce it, try building a route using the coordinates above and note the circuitous routing through the interchange.

In the web version, navigation through the roundabout is detoured, whereas in OSM, it takes a shorter route by simply turning right.

Here is the link to the Web version: [OsmAnd Web](https://test.osmand.net/map/navigate/?start=56.011968,12.801886&end=56.049724,12.725209&profile=car#16/56.0191/12.7596)

Here is the link to OSM: [OpenStreetMap](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=56.01199%2C12.80123%3B56.04923%2C12.72587#map=16/56.01851/12.76133)

<table style="width:100%">
  </tr>
  <tr>
    <th>Web version</th>
    <th>OSRM · Graphhopper · Valhalla</th>
  </tr>
  <tr>
<th><img src="https://github.com/user-attachments/assets/12d43935-1b09-4b7a-8b99-b5f3f7d946c5"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/bb697f2e-a7a5-4681-8cdf-b9e890a36d5c"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
Issue is probably with https://www.openstreetmap.org/way/31874746 as it  could be mapped as primary_link

**Comment by vshcherb** [comment]
Short version:
https://test.osmand.net/map/navigate/?start=56.018709,12.759397&end=56.020124,12.761307&profile=car#17/56.01897/12.76190 - Cost 101

https://test.osmand.net/map/navigate/?start=56.018709,12.759397&end=56.020124,12.761307&avoid=15222284509&profile=car#17/56.01897/12.76190 - Cost 149

https://www.openstreetmap.org/way/31874746#map=18/56.019021/12.761824 - tertiary -> primary_link will fix it. 

We need to investigate what else could be done

**Comment by vshcherb** [comment]
Probably we can only fix this at data preparation level, if short way is connected mostly to primary, motorway and only 1 edge to tertiary than it should be primary_link at least
