### ISSUE TITLE
Routing issue

### ISSUE THREAD

**Issue by noci2012** [osmandapp/Osmand#2128]
Lately i started driving before a GPS Fix was received. So it was still searching for a route.
During driving a GPS fix was gained, a route calculated and the GPS signal was lost again.
A few minutes later GPS fix was regained again. From then on Osmand insisted to First return to the place where the first fix was received/route calculated and not a recalculation from the current location to the endpoint.

It was needed to REMOVE the route and select the destination again which in this case involved searching for a Zip Code and a looong wait before that turned up an location.. I was lucky i had a passenger on this one otherwise a stop over on a safe place would be needed to solve it.

**Comment by sonora** [comment]
In deed if I remember correctly, we have something like a "fast route recalculation" in place, which at first tries to route you back where you "left" the route OsmAnd had proposed. Obviously this is the very fast fix for people on a longer route which would take long to re-calculate, while they just missed a turn.

But if you just keep driving for a few more seconds, OsmAnd should eventually re-calculate the complete route (which can of course take some time depending on its length). Maybe you should have just given it a few more seconds? Can you re-try this?

**Comment by sonora** [comment]
PS: Cancelling a route keeps the destination, so no need to re-search it (not even via the Search screen's "History" tab). So just cancelling the navigation via the (X) button (confirm with "YES"), then re-starting it (using the little navigation button near the lower left corner of the map screen) should have done the trick also.

**Comment by noci2012** [comment]
Ok, explain how the program works to someone unfamiliar with the application while in heavy traffic.
Osman is not that intuitive to use, it is not hard but not self explaining either.

The gps fix was on for a few seconds, then off for a minute or so, then on again.
It took 5 minutes before I gave up on return at the next corner...  so clearly the few seconds didn't materialise for at least 300 seconds. (and  6-7 km from where the fix was lost).

**Comment by sonora** [comment]
Sounds like a bug, need to investigate. Could not reproduce so far, though ... Can you please state the app version you are reporting this for - Thx.

**Comment by noci2012** [comment]
Osmand+ 2.2.4 issued on 2015-12-22

**Comment by noci2012** [comment]
Oh by the way i forgot to mention that i was driving along the route that i should take after i would have passed the "Starting point"... (So i would pass the same spot say 10-15 minutes later if i followed the Osmand directions.)

**Comment by sonora** [comment]
I think this is fixed, if not, please re-open or report again.
