### ISSUE TITLE
Roundabout exit number unreadable 

### ISSUE THREAD

**Issue by Davi427** [osmandapp/OsmAnd#21280]
### Description

A few minutes after sunset (16:23), in dark mode, the roundabout exit number was still black and thus unreadable. The next instruction set was the correct colour.

### Steps to reproduce

Drive at sunset,
go on a roundabout 

### Expected result

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/08423da8-fef4-4b52-a42a-b88c6ae92bbb"  width="300" height="auto"/> </th>
<th><img src="https://github.com/user-attachments/assets/8deb7ca7-90fe-4612-9394-d5d0693c55cd"  width="300" height="auto"/> </th>
  </tr>
</table>

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd+ 4.9.3, Released: 2024-11-01
Android/iOS version: 14
Device model: FP5
Crash-Logs: ?
```

**Comment by DmitryAlexei** [comment]
The same issue for speedometer widget 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/2736f7a6-3ba0-4db2-b18a-0ffb72a952e4"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/5aec1359-20c2-4512-b88d-4219a2aaf5ea"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Davi427** [comment]
Could this be related, as a dark/light mode switch issue?

I noticed the route line was missing so did a screen record. Sunup was around 7:44 here this morning so the recording is from right around that switch.
https://github.com/user-attachments/assets/1747c513-4283-4b9f-9165-ba88319efff7

Immediately after I stopped the recording, Osmand went to light mode and the route line is visible.
![Screenshot_20241112-074444](https://github.com/user-attachments/assets/3dd93a22-bf4c-480c-9d07-368882f786eb)

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/21305

**Comment by DmitryAlexei** [comment]
25/11/24
![telegram-cloud-photo-size-4-5920420798026334744-y](https://github.com/user-attachments/assets/13e7feee-bd6a-42e0-b198-34a1f763a203)

**Comment by Zirochkabila** [comment]
OsmAnd~ 5.0.0#3840m, Released: 2024-11-29
Done
