### ISSUE TITLE
No 3D Mode in Pro version from Play Store purchased via Huawei AppGallery

### ISSUE THREAD

**Issue by piorun-sudo** [osmandapp/OsmAnd#21286]
### Description

Hello, so I bought Pro version of Osmand (this one with cloud, etc.) via Huawei AppGallery due to issues with adding payment method to Play Store. Then I downloaded Play Store version due to it receiving latest updates the fastest. After activation of Pro version on Play Store version, there is no button to turn on and off the 3D Mode. I was unable to resolve it via support.

### Steps to reproduce

1. Get App from Huawei AppGallery
2. Buy Pro version
3. Download app from Play Store
4. Log in
5. Restore purchase
6. Go to the map

### Actual result

No 3D Mode button available even though it is enabled in settings

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/99100634-babf-4ddd-adad-7e546b496ab7"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/87245817-89cd-482f-9b98-1e33e3e87917"  width="300" height="auto"/> </th>
  </tr>
</table>

### Expected result

3D Mode button is available as usual 

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: Newest
Android/iOS version: Newest GrapheneOS
Device model: Pixel 8A
Crash-Logs: n/a

**Comment by scaidermern** [comment]
Check in OsmAnd settings if your rendering engine is set to v2 (OpenGL).

**Comment by piorun-sudo** [comment]
I didn't thought it will be that easy - now it works, issue resolved, thanks!
