### ISSUE TITLE
App crashing while calculating route

### ISSUE THREAD

**Issue by TheFighter137** [osmandapp/OsmAnd#21285]
### Description

When I'm trying to calculate a 60km driving route, the app crashes.

Here are a few things I tried which didn't fix the issue :
- Disabling my usual restrictions (no unpaved roads ; no toll roads ; fuel-efficient way)
- Using a closer destination (only 1km away from starting point)
- Clearing the app's cache

Here are a few things I tried which didn't make the app crash :
- Use the cycling and walking presets for the same route
- Using a starting point 250m further up the road

The issue seems to be related to the starting point's area, however after checking the area in JOSM, I didn't find anything suspicious.

Looking at the logs, it looks like after restarting the app, it has detected that it crashed. However, no obvious error seems to appear before the crash.

### Steps to reproduce

1. Open the OsmAnd app
2. Open the navigation tab
3. Select the driving profile
4. Select the "no unpaved roads", "no toll roads", and "fuel-efficient way" conditions
5. Select the following starting point (49.446578, 1.071752)
6. Select the following destination (49.868749, 0.711705)
7. Let the app calculate the route

### Actual result

The app crashes when it is about to show up the route.

### Expected result

The driving route should be calculated without issues.

### Your Environment (required)

OsmAnd Version : 4.8.6 (latest on F-Droid)
Android version : 14
Device model : Samsung Galaxy A34 5G
Crash-Logs : [osmand.log](https://github.com/user-attachments/files/17682659/osmand.log)

**Comment by yuriiurshuliak** [comment]
The bug could not be reproduced. To attempt reproduction, select the car profile, enable the "no unpaved roads," "no toll roads," and "fuel-efficient way" settings, and try building a route using the following [coordinates](https://test.osmand.net/map/navigate/?start=49.446580,1.071750&end=49.868749,0.711705&profile=car#9/49.7841/0.6070).

The navigation calculates correctly, quickly, and without crashes. Please try using the official version from Google Play and also test the nightly version to see if the issue appears there: [Nightly builds](https://osmand.net/docs/versions/nightly_versions#nightly-builds).

OsmAnd~ 5.0.0#3692m, released: 2024-11-12

https://github.com/user-attachments/assets/b1dba561-bbe9-4468-9cbc-b52260782303

**Comment by vshcherb** [comment]
With new maps even old verison should work fine, 4.9 is about to be released this week with future-proof crashes like that
