### ISSUE TITLE
Import out of a file doesn't work 

### ISSUE THREAD

**Issue by prallo** [osmandapp/OsmAnd#21290]
### Description

I installed Osmand+ and tried to import my settings from a file but doesn't work.

### Steps to reproduce

See video

### Actual result

Doesn't work 

https://github.com/user-attachments/assets/5db7b1d2-fcc0-46ff-bc6b-a0aa6745aa72

### Expected result

Does work 

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.8.6
Android/iOS version: 14
Device model: Samsung Galaxy S23 Ultra 
Crash-Logs: NA


```

**Comment by scaidermern** [comment]
Looks like the same Android 14 specific bug as in these issues: #20949 #21003 #20937
The fix is contained in OsmAnd 4.9.x.

**Comment by prallo** [comment]
I don't want to update to beta 4.9.1 because my maps are stuttering with that version.
Filed a bug report for that already.

**Comment by DmitryAlexei** [comment]
@prallo try to import OsmAnd settings without tracks and favorites
Issue is fixed in 4.9 for android 14 devices
FYI, beta OsmAnd+ 4.9.3 is available in Google Play

**Comment by prallo** [comment]
Version 4.9.3 also stuttering !
Went back to version 4.8.6.

**Comment by prallo** [comment]
You imported only my places while my import includes my places, settings and sources !

**Comment by prallo** [comment]
I tried that too but didn't help.
As noone else reported this issue it can be closed. I will stay with version 4.8.6 and will try again with later versions next year.
Thanks to all for your help !
