### ISSUE TITLE
Intermediate destination and destination icons

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2129]
We need a small concept, then initiative, to homogenize the icon appearance we use for intermediate destination and destination (and corresponding actions) everywhere.

As for the concept, I would say let us do it exactly like we do it on the map screen: Intermediate destinations are marked by an indented flag (orange), while the final destination is depicted by a rectangular target flag (black and white ?).

Once the concept is agreed, we need to change the "wild mixture" we have now (intermediate dest / final dest):

(1) Map screen:
    Indented (orange, numbered) / rectangular (black/white)
(2) Route configuration dialogue:
    Triangular (not filled, orange) / Rectangular (orange)
(3) Route configuration screen, action bar:
    Triangular (not filled) / -
(4) Context menu, action bar:
    - / Triangular (filled)
(4) Context menu, "More", Add as last intermediate destination:
    Triangular (not filled) / -
(5) Waypoints config screen and Dashboard:
    Indented (orange) / Rectangular (b/w)    (These are currently the only places where we correctly resemble the icon appearance of the map screen)
(6) Map widgets:
    Triangular (filled orange) / Rectangular, filled orange)
(7) Drawer:
    Triangular (not filled) / -    (Drawer entry likely disappears entirely)

Needless to say: Making our icons in lists, dialogs and on action buttons closely resemble how they are on the map screen significantly paves the way for the user to comprehend the UI.

**Comment by raindropsfromsky** [comment]
Why do we have flags of different shapes as spot markers? 
All point-markers should have the standard tear-drop shape, with a distinct icon inside.

The icon for these points can be borrowed from [F1 car race] (https://en.wikipedia.org/wiki/Racing_flags).

For example, 
***Start point:*** [Green circle] (https://en.wikipedia.org/wiki/Racing_flags#Green_flag)
***End point:*** [B/W Checkered] (https://en.wikipedia.org/wiki/Racing_flags#The_chequered_flag)
***Waypoints:*** [Circle with a number inside] (http://www.sciencekids.co.nz/images/pictures/math/number1.jpg).

***Buttons:***
For the start-point and end-point, the same icons can be used in any dialog.

But the button for "waypoints" is always for multiple waypoints; not for a single waypoint.
Therefore its icon should be different from the icon used in a waypoint-marker.
I'd suggest using a curve with two dots (signifying waypoints along a route).

**Comment by sonora** [comment]
Actually, I quite like the flags, their different shape alone makes it easier to distinguish destinations from other types of points we have like Favorites, highlighted POIs, GPX waypoints, etc. My point was only to harmonize the flag appearance between the map and all other different screens.

Buttons: Also here, flags are more unique to actions referring to destinations and intermediate destinations. A curve with dots we already use for tracks, something entirely different.

**Comment by raindropsfromsky** [comment]
Well, when POIs are displayed along the route, we see a large variety of shapes, apart from the features of the map itself (compare this with Google map, where the map is stripped of most details). So it would be impossible to have a distinct shape.

What makes them distinct is their position: These points are always on the route (purple line). All other POIs are scattered on the map, but not on the route.

I had not mentioned the following point before, but any flag shape is difficult to tap (we have to tap at the base of the flag). On the other hand, the inverted teardrop shape offers a far larger and perfectly regular (circular) area; and therefore it is far easier to tap.

**Comment by vshcherb** [comment]
I think it is mostly fixed already
