### ISSUE TITLE
Turn restriction is ignored when live updates are active

### ISSUE THREAD

**Issue by lintux** [osmandapp/OsmAnd#21304]
### Description

Creating a route (Car Profile) from here 50.76946, 6.11914 to here 50.76725, 6.10396 will ignore [the turn restriction](https://www.openstreetmap.org/relation/6441507) once Live Updates are active.

Issue seems identical to (closed):
https://github.com/osmandapp/OsmAnd/issues/17047
https://github.com/osmandapp/OsmAnd/issues/18008

mapillary: [Example OTG View](https://www.mapillary.com/app/?lat=50.770669100003005&lng=6.116631999999981&z=19.9&focus=photo&pKey=3167384106863230) 

### Steps to reproduce

Download the latest version of Germany_nordrhein-westfalen_europe.obf - enter the above route with the Car profile. Result is as expected - Routing via Goerdelerstraße. 
Then --> Switch on and download live updates, recreate the route

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/036cefde-f238-4f1f-b896-bf4f0d485a36"  width="300" height="auto"/> </th>
  </tr>
</table>

### Actual result

routing will lead from Adalbertsteinstraße left into Bevernstraße (ignoring previously respected turn restriction)

### Expected result

Routing via Goerdelerstraße respecting [turn restriction](https://www.openstreetmap.org/relation/6441507) 

### Your Environment (required)

OsmAnd Version: OsmAnd+ 4.8.6, released: 2024-08-08
map: Germany_nordrhein-westfalen_europe.obf, released: 2024-11-01
Android/iOS version: 13
Device model: motorola edge 20 (XT2143-1)
Crash-Logs: no Crash

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce it:

1. Select the **Car** vehicle profile.  
2. Create a route from **50.76946, 6.11914** to **50.76725, 6.10396**.  
   - The route respects the turn restriction and directs via **Goerdelerstraße**.  
3. Enable **Live Updates** for the downloaded map.  
4. Recreate the same route.  

**Observed result:**  
With Live Updates active, the routing incorrectly ignores the turn restriction and allows a left turn from **Adalbertsteinstraße** into **Bevernstraße**.  

Route on the Web version: [OsmAnd Web Route](https://test.osmand.net/map/navigate/?start=50.769460,6.119140&end=50.767250,6.103960&profile=car#17/50.77051/6.11303)
Turn restriction on OSM: [OpenStreetMap Relation 6441507](https://www.openstreetmap.org/relation/6441507#map=18/50.770691/6.116043)

OsmAnd~ 5.0.0#3746m, released: 2024-11-18

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/1d466675-a0b9-4029-a2f1-e994dcda11e2"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/f88dfb8b-bb59-4244-993c-c230de408f97"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by RZR-UA** [comment]
OBF with the problem: 24_11_07_10_10.obf 

It was reproduced in MapCreator, but the source OSM file was expired.

Ways to consider:

https://www.openstreetmap.org/way/120424462#map=19/50.770651/6.118258
https://www.openstreetmap.org/way/120424453#map=19/50.770599/6.118248

**Comment by RZR-UA** [comment]
It seems that the Live update file(s) `24_11_07_10_10.obf` was generated incorrectly and might include an unknown amount of unchanged ways with lost relation-based restrictions. Manual regeneration of 2024/11/07 10:00-10:10 data was successful (to compare whether it was a bug or not).

The problem must be solved automatically by the next Maps generation (in the first week of December).

Additionally, the Live update script is now better protected against potential errors that could lead to the same bug.

@lintux, if you need the fixed maps sooner, we could regenerate the Germany region manually.

**Comment by lintux** [comment]
Hi @RZR-UA .. thanks .. I think I can wait until the December Maps release.

**Comment by Zirochkabila** [comment]
I'm waiting for December 7th to check the restriction after the live updates `50.76946, 6.11914` - `50.76725, 6.10396`

**Comment by Zirochkabila** [comment]
OsmAnd~ 5.0.0#3875m, Released: 2024-12-04
4.9.0.11

Done iOS & Android version (Decembers maps & Live updates too)
