### ISSUE TITLE
`access:conditional=no @ (Mar 15-Aug 31)` not applied

### ISSUE THREAD

**Issue by raboof** [osmandapp/OsmAnd#21323]
### Routing engine

- [X] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

pedestrian

### Start and end points

https://osmand.net/map/navigate/?start=52.032801,5.439007&end=52.042976,5.437872&profile=pedestrian#16/52.0385/5.4334

### Actual route

![route](https://github.com/user-attachments/assets/f096904b-30b1-42fa-a149-96cf13eda948)

### Expected route

I would expect the routing to ignore the route going north from the Heulweg.

https://osmand.net/map/ and the app get this wrong, just like Graphhopper and Valhalla. OSRM gets it right, however.

### Maps you used (online or offline)

- [x] Offline maps offered within the OsmAnd app for download. Up-to-date at the time of writing.

### Your Environment

```
OsmAnd Version: 4.8.5
Android version: 14 (CalyxOS 5.12.1)
Device model: FairPhone 4

```

### Anything else?

From https://github.com/osmandapp/OsmAnd/issues/20798 it sounds like OsmAnd might expect spaces around the `-` in the date format, but looking at https://wiki.openstreetmap.org/wiki/Conditional_restrictions and https://wiki.openstreetmap.org/wiki/Key:opening_hours#Values the currently used format look OK to me.

**Comment by scaidermern** [comment]
https://www.openstreetmap.org/way/403895028
Mar 15-Aug 31? According to my calendar we currently have November. November is outside of this range.
