### ISSUE TITLE
Please implement double-tap-slide zoom

### ISSUE THREAD

**Issue by uqs** [osmandapp/Osmand#2132]
I can't remember which version of Android introduced this, but Google Maps can use it, Chrome uses it, all Image/Gallery apps can use it etc. It allows for nice zooming when using your phone one-handed (as opposed to pinch zoom).

https://www.youtube.com/watch?v=h8Z91ND1kl4 (in case you don't know how it works).

Once you're used to that zoom method in all other apps, using OsmAnd becomes annoying as it doesn't implement that gesture.

Thanks!
Uli

**Comment by GaidamakUA** [comment]
Please try last nightly build.

**Comment by quelbs** [comment]
When you double tap, the zoom-in functionality is triggered before you lift your finger, so before you can do the double-tap-slide zoom, the map is zoomed in once.
Also this led me to a problem when already in max-zoom (#2197). I think the same problem appears when you do the double-tap-zoom and use it to zoom out, it may be possible to leave the valid zoom range (at least a plain gray map area is displayed if I zoom out to the max possible).

**Comment by uqs** [comment]
It kinda works, but the double-tap will *always* trigger a re-center-and-zoom-in first. When I leave my thumb down then I can slide up and down to zoom. It's a bit finicky.
