### ISSUE TITLE
Lanes widget not showing

### ISSUE THREAD

**Issue by Davi427** [osmandapp/OsmAnd#21326]
### Description

The lanes widget does not show unless certain conditions are met. When it is placed at the bottom, it does not show at all unless another widget is below it (I used the street name widget).

### Steps to reproduce

Add the lanes widget at the bottom and find a lane instruction .

### Actual result

<table style="width:100%">
  <tr>
    <th>Lanes widget not shown when there is no other widget.</th>
    <th>Lanes widget not shown when it is below the street name widget.
</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/2b019689-d7fd-4e98-af14-ee07ebd63114"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/8343a721-342d-44ce-8a34-d7e2e1bdb930"  width="300" height="auto"/> </td>
  </tr>
</table>   

### Expected result

Lanes widget is shown regardless of whether other widgets are active.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd+ 4.9.3, Released: 2024-11-01
Android/iOS version: 14
Device model: FP5
Crash-Logs: ?
```

**Comment by Zirochkabila** [comment]
OsmAnd~ 5.0.0#3780m, Released: 2024-11-21

Done -  Car & Moto profiles

**Comment by dmpr0** [comment]
# Review
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src=""  width="300" height="auto"/> </td>
    <td><img src=""  width="300" height="auto"/> </td>
  </tr>
</table>   


- [ ] Starts to display only after app reopening

**Comment by Zirochkabila** [comment]
OsmAnd~ 5.0.0#3860m, Released: 2024-12-02
Not reproduce

**Comment by dmpr0** [comment]
It is still unclear when and why it should be shown or not.
