### ISSUE TITLE
The card for some POIs do not show the bearing+distance blue arrowhead

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2133]
When we search for a point, OsmAnd pops up a card for that spot. In some cases, that card does not show the bearing+distance blue arrowhead.

See an example
![screenshot_2016-01-10-19-13-47](https://cloud.githubusercontent.com/assets/9047168/12221813/cdef35b2-b7cf-11e5-8cbd-0ee3f8fc6fb9.png)

**Comment by sonora** [comment]
Please check if you had a position fix at all, seems to me you had not. Blue distances and directions are from "My Position", hence only shown if ""My Position" is know.

The only observation I seem to be able to confirm is that the direction/distance data is not shown if the position fix is obtained only after the context menu is already shown (i.e. the context menu is not updated once "My Position" is found). You would have to manually refresh the dialog (tap the map, then tap the POI marker again) to produce it. Can be considered a small bug, probably worth fixing.

**Comment by raindropsfromsky** [comment]
Since this is not repetitive, I am willing to concede that the GPS fix may have been lost momentarily.

But then we lose GPS often, especially indoors and/or cloudy days. Worse, OsmAnd does not announce this when we are in ***Browse*** mode (it announces whenever GPS is lost only in the ***Navigation*** mode).

Therefore, if GPS fix is lost, rather than presenting a blank space, OsmAnd should display a "No GPS fix" icon in place of {blue arrowhead and distance}.
![gps lost](https://cloud.githubusercontent.com/assets/9047168/12256535/c51d0658-b923-11e5-840d-876c172cb0db.png)

In fact, this same icon should be used in other screens also when the GPS connection is lost.

**Comment by sonora** [comment]
Narayan, not sure what you are suggesting here, but the current GPS status icon in the Android notification bar is created by Android, not by OsmAnd. In most versions not-visible=disabled, blinking=looking-for-a-fix, permanent=fix-obtained. Apps could produce additional icons, but I am not sure creating even more notification icons is really the way to go here.

**Comment by raindropsfromsky** [comment]
Well, first of all my phone does not show any notifications whether the GPS fix is available or not (see the screenshots below). I guess that a lot of other devices also will have this limitation.

BTW even if your device shows the GPS icon in the notification bar, it is not usable, because the blue arrowhead takes some time to appear, as can be seen from my screenshots below. 
![missingbluearrow](https://cloud.githubusercontent.com/assets/9047168/12317694/9abd199c-bab9-11e5-8804-af1e80e796c8.png)
By the time I took the left screenshot, the GPS fix was just restored. So it shows the current location (blue circle), but the arrowhead is still missing. Because of the lag, the status is ambiguous!

If the GPS fix is available intermittently, the situation becomes even worse.

Therefore it is best to show this alert in the card itself, as shown below. 
![nogpsfix](https://cloud.githubusercontent.com/assets/9047168/12317747/16c8696a-baba-11e5-9063-37abd8f4a21a.png)
This way, the card will show either a ***"Lost GPS fix!"*** alert, or the blue arrowhead. No ambiguity!

**Comment by vshcherb** [comment]
Doesn't look really appealing UI.

**Comment by raindropsfromsky** [comment]
Victor,

Well, visually it can always be made appealing. For example, the icon can be much smaller if you prefer. But it does provide a missing information.
