### ISSUE TITLE
POI = ATM only shows distinct ATMs, not banks w/ ATM

### ISSUE THREAD

**Issue by Shurakai** [osmandapp/Osmand#2134]
The title says it all. On openstreetmap.org, when I edit and add a bank, I can tick a checkbox that says "ATM". Hence, not all ATMs have their own dataset in openstreetmap.

I therefore propose to change the query for the ATMs in OsmAND: It should also show all banks that have this specific flag set.

Thanks guys!

**Comment by hakuchi** [comment]
OsmAnd also sold show ATM in bank description if they have tagged atm=yes.

**Comment by xmd5a2** [comment]
This is a known issue but I added atm=yes/no to additional POI list.

**Comment by xmd5a2** [comment]
#2209

**Comment by xmd5a2** [comment]
I propose to implement something like "alias" to poi_types.xml. But in case of atm it requires to solve https://github.com/osmandapp/Osmand/issues/2209

**Comment by vshcherb** [comment]
@xmd5a2  Let's convert atm=yes with bank to atm, so it will be visible in the list and mark it as belongs_to_bank=yes.  
I also suggest to move away from "amenity" tag and use different tags otherwise we will need to use "split" which is quite bad operation for OSM Edit

**Comment by vshcherb** [comment]
The issue has been fixed
