### ISSUE TITLE
🐞 OSMand fails to display images from newly added wikimedia_commons=Category tags

### ISSUE THREAD

**Issue by DavidOsipov** [osmandapp/OsmAnd#21343]
### Description

OSMand does not display images from Wikimedia Commons when a `wikimedia_commons=Category:CategoryName` tag is newly added to a POI.  This issue persists even after updating OSM data in OSMand after 15 minutes and waiting for several days (tested up to 5-7 days).  However, using `wikimedia_commons=File:SpecificFileName.jpg` works correctly and displays the image immediately.  Furthermore, POIs with `wikimedia_commons=Category:CategoryName` tags that have existed in OSM for a longer period *do* display images correctly in OSMand. This suggests an issue with updating or processing newly added category tags.

### Steps to reproduce

1. Add a `wikimedia_commons=Category:CategoryName` tag to a POI in OpenStreetMap, where "CategoryName" is a valid Wikimedia Commons category.  For example, [Category:Otar Taktakishvili Art School No. 19](https://commons.wikimedia.org/wiki/Category:Otar_Taktakishvili_Art_School_No._19) of the POI in OSM [Otar Taktakishvili Art School No. 19](https://www.openstreetmap.org/way/77758670)
2. Wait 15 minutes.
3. Update OSM data in OSMand.
4. Open the POI in OSMand.  The images from the specified Wikimedia Commons category are not displayed.
5. Wait 4-5 days. 
6. Update OSM data in OSMand.
7. Open the POI in OSMand.  The images from the specified Wikimedia Commons category are not displayed.

### Actual result

OSMand does not display any images from the newly added `wikimedia_commons=Category:CategoryName` tag. Images from older, pre-existing category tags on other POIs *are* displayed correctly, [like this one](https://www.openstreetmap.org/way/405852444).

### Expected result

OSMand should display images from the specified Wikimedia Commons category after the OSM data is updated, similar to how it handles `wikimedia_commons=File:SpecificFileName.jpg` tags.

### Your Environment (required)

```
Device : joyeuse
Brand : Redmi
Manufacturer : Xiaomi
Model : Redmi Note 9 Pro
Product : joyeuse_global
Build : SKQ1.211019.001 test-keys
OS: Android
Version : 12
App Version : OsmAnd~
Apk Version : 4.8.6 480603
```

**Comment by alisa911** [comment]
Hello. Yes, to make sure images with new category tags appear in our search, we run certain processing tasks on the server. Previously, this update happened once a month, but we've increased the frequency, and it will now run 3 times a month.
