### ISSUE TITLE
Climbing Sport center is shown as "remarkable stone"

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#21352]
### Description

A sports center for climbing is shown as "remarkable stone".

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/795f9368-eb29-447d-aab2-625bb613dd00"  width="300" height="auto"/> </th>
  </tr>
</table>  

https://www.openstreetmap.org/node/12287417030

### Your Environment (required)

```
OsmAnd Version: 4.9.5
```

**Comment by fe60** [comment]
I guess it's the tag "climbing" with value "boulder" causing this rendering.

https://wiki.openstreetmap.org/w/index.php?title=Climbing&uselang=en#Boulders

**Comment by yuriiurshuliak** [comment]
It seems that the rendering of the climbing=boulder tag is causing the object to appear as "remarkable stone." Unfortunately, we cannot always determine the intended display for such objects in every country, as this depends on how the map data is tagged in OSM.

If you believe the object should be displayed differently, you may need to adjust the tagging in OSM. Once the changes are made in OSM, they should reflect correctly in OsmAnd after map updates.

**Comment by scaidermern** [comment]
> If you believe the object should be displayed differently, you may need to adjust the tagging in OSM. Once the changes are made in OSM, they should reflect correctly in OsmAnd after map updates.

I'm certainly not changing the tagging of this POI (and various other POIs). The tagging is correct. Changing the tagging to make it render differently is wrong. Please read https://wiki.openstreetmap.org/wiki/Tagging_for_the_renderer

The main tag here is `leisure=sports_centre`, not `climbing:boulder=yes`.

**Comment by yuriiurshuliak** [comment]
After checking the map, I confirm that the issue is reproduced as you indicated: the object tagged with `leisure=sports_centre` and `climbing:boulder=yes` is rendered as "remarkable stone" in OsmAnd.

If the main tag `leisure=sports_centre` is not being prioritized for rendering, it may indicate a need for adjustment in how OsmAnd interprets these combinations of tags.

OsmAnd~ 5.0.0#3746m, released: 2024-11-18

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/0dd17140-806d-4952-886f-c41cd638af99"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by mdykierek** [comment]
Improved tagging. Check in a couple of hours.

**Comment by scaidermern** [comment]
> I guess it's the tag "climbing" with value "boulder" causing this rendering.
> 
> https://wiki.openstreetmap.org/w/index.php?title=Climbing&uselang=en#Boulders

> Improved tagging. Check in a couple of hours.

Thanks! `climbing=boulder` was indeed not the correct tag for an indoor boulder facility. `climbing:boulder=yes` is the correct tag.

**Comment by vshcherb** [comment]
@xmd5a2 please provide details whether we're going to fix and how

**Comment by scaidermern** [comment]
With the changed tagging OsmAnd now displays it correctly as "sport center".
This probably means that the `climbing=boulder` tag has a higher priority for OsmAnd when choosing the category than `leisure=sports_centre`. This is only a minor issue in my opinion.
