### ISSUE TITLE
Address lookup missing for some use cases

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2135]
We correctly perform an address lookup (and flash the corresponding "Skip" dialog) when adding a destination or intermediate destination to a route via the context menu's "Add as (intermediate) destination" button. But activating the address lookup is not activated for the following cases:

(1) Adding a destination via the route configurations ""Select on map" function
(2) Adding a destination via the context menu's blue "Directions" button
(3) Adding an intermediate destination via Context Menu / More / "Set as last intermediate destination"

**Comment by vshcherb** [comment]
Good point.

**Comment by vshcherb** [comment]
(4) Add Favorites

**Comment by raindropsfromsky** [comment]
Of course, as Sonora pointed out in a different issue, the lookup should generate a human-readable identity of the point. 

At present, the lookup generates only road name and city. But a road can be several thousand km long, so such an address is not sufficient to define the point.

We need nearest landmarks, including road junctions, POIs and locality. The name of city can be omitted, as that information is obvious.
 
For example,
 1. Road Junction ---> 1st Main, 3rd Cross, Indiranagar, Bangalore.
 2. Nearby POIs -----> Near KFC, MG Road, Bangalore.

**Comment by crimean** [comment]
You are talking about issue not related to current one

**Comment by raindropsfromsky** [comment]
Guilty! 

Well, I should have left a "related to..." link. But then even that issue also mentions several closely related things to do, so....

**Comment by crimean** [comment]
I just want to say that I will fix "perform an address lookup" for few places and close it. Thus your comment will be lost here.

**Comment by raindropsfromsky** [comment]
Yes, you are right!

Thanks!
