### ISSUE TITLE
Track thickness is not applied immediately

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#21360]
### Description

On the track appearance settings screen, when changing its thickness, it does not change. and even after pressing the apply button, this does not happen immediately, but it is advisable to kill osmand and restart it.

https://github.com/user-attachments/assets/13115e9c-e724-4408-a333-26985b3c8750

### Steps to reproduce

described above

### Actual result

the thickness of the track line does not change

### Expected result

the thickness of the track line should change

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:OsmAnd~ 5.0.0#3732m, Дата выпуска: 2024-11-15
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce this bug:
  
1. Select any GPX track on the map.  
2. Click on it and choose **Track Appearance** → **Width**.  
3. Change the track width (e.g., to "Bold").  

**Observed Behavior:**  
- While the context menu is open, the track width does not change as a preview.  
- After pressing "Apply," the width still does not update on the map.  
- However, upon completely closing the app and reopening it, the new track width is applied.

OsmAnd~ 5.0.0#3756m, released: 2024-11-19

https://github.com/user-attachments/assets/5b6aed4a-888b-4e4a-a3a1-b7ae20f7a31d

**Comment by vshcherb** [comment]
After apply click, map view should be updated

**Comment by vmicho** [comment]
Same observation using v4.9.7 on offline track (already recorded).
Selecting track -> options -> appearance -> change Width : does not change the width of track on screen, even after pressing "Apply".
The width changes however when changing the track color or after changing screen orientation (portrait/landscape).

No such problems observed on v4.8 and v4.7.

Example: the track stays on medium width, should already be thin:
![Screenshot_20241210-205849_OsmAnd+](https://github.com/user-attachments/assets/ff2125fe-71ee-4fd4-8394-f88ceef32718)

**Comment by Vopi2024** [comment]
Ik ervaar zelfde probleem , Dikte van routelijn word Niet veranderd na toepassen 
Maar ook de richtingpijlen van de route track kunnen niet aan of uit worden gezet na toepassen 
>uiterlijk>richtingspijlen>aan/uit>toepassen 
Fout doet zich voor in versie 4.9.7 en 4.9.10 Osmand+

**Comment by Zirochkabila** [comment]
# Testing 1
`OsmAnd~ 5.0.0#3992m, Released: 2024-12-24` - The display of turn arrows works only after changing the color (updating the data), the same applies to tourist routes


https://github.com/user-attachments/assets/27f7730c-cecd-419f-9a0c-1b055723a8e5

**Comment by Zirochkabila** [comment]
# Testing 2
`OsmAnd~ 5.0.0#4011m, Released: 2024-12-27` - Fixed
