### ISSUE TITLE
Fix shields & destination in widgets (Android & iOS)

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#21362]
- [ ] Duplicate shields (from destination:ref and ref) are displayed
- [ ] Destination:ref causes empty commas in Destination. 

Solution: destination:ref should be combined with ref and used a common united set.

Should be tested with:
- Current Street Widget 
- AA / CarPlay Widget 
- Next turn Widget 
- Route Details
- Voice instruction

----------
`4.8.4`
`OsmAnd~ 5.0.0#3746m, Released: 2024-11-18`

[OsmAnd](https://osmand.net/map/search/#17/51.28857/22.44057)
[OSM](https://www.openstreetmap.org/search?query=51.2871697317902%2C%2022.444053620061002#map=17/51.287104/22.445229)
`51.2871697317902, 22.444053620061002`

Duplicate names in Street name widget - Shields duplicate with names. 51.29146 22.43126

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/3c8cac14-bdbb-4059-b367-49f2a99f03b1"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/827003fc-cfc8-4b9b-b8cd-4bf3406a5ca2"  width="310" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
iOS **4.8.4** - same
[OsmAnd](https://osmand.net/map/search/#17/51.28857/22.44057)
`51.2871697317902, 22.444053620061002`


<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/827003fc-cfc8-4b9b-b8cd-4bf3406a5ca2"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by ivanPyrohivskyi** [comment]
Problem with UI in iOS.
Show only one shield (12) instead three (17, S17, 12)
In [code](https://github.com/osmandapp/OsmAnd-iOS/blob/a1f620175653d4dabe843ecb8b3e27eac8fa1c97/Sources/Controllers/Map/Widgets/OATopTextView.mm#L669) shields are set three times, but show only once.
<img width="300" src="https://github.com/user-attachments/assets/a97196d3-c794-448d-bfcf-825fc791a48d" />

**Comment by vshcherb** [comment]
![image](https://github.com/user-attachments/assets/b7807317-e0ee-43b4-99cb-42ece0fdd247)

**Comment by DmitryAlexei** [comment]
Android part can be tested

**Comment by Zirochkabila** [comment]
`OsmAnd~ 5.0.0#3863m, Released: 2024-12-02`
Android version & AA - Clear

It is clear that the iOS version still needs to be worked on. `4.9.0.10`
But please note that now the information in the widget is different from the one shown in the screenshot at the beginning of the task

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/c08019b5-5b1c-450d-918e-e7cad2fcc7ef"  width="400" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/a23e09c1-86cf-429c-8a94-3ed179754d68"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
# Testing 2
`4.9.0.18` - Fixed


<img width="510" alt="Screenshot 2024-12-12 at 16 42 32" src="https://github.com/user-attachments/assets/abbd86cc-6a75-4cd9-adc3-4c52da5ebd12" />

**Comment by RZR-UA** [comment]
https://github.com/osmandapp/OsmAnd/issues/21618
