### ISSUE TITLE
Correctly reset routePlanningMode switch in new UI

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2136]
In https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/views/MapControlsLayer.java#L496 and https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/views/MapControlsLayer.java#L511 we hide the mapAppModeShadow and change the directions icon on the map to the start nav icon if  route planning or navigation is ongoing.

In our new UI there were two issues with this: routePlanningMode falsely reported as true if

(a) you had pressed the "Directions" button on the map screen (while no destination was set), but then backed out of the pop-up route planning dialog again either by simply tapping on the map or by sing the device's BACK button (so still no destination is set).

(b) or you had a route, and then on the new Waypoint edit screen removed the destination (and all intermediate destinations, if present).

In both cases I guess you should afterwards end up with routePlanningMode=false, because there is no destination and hence no routing going on. But it seems routePlanningMode actually stayed as "true".

PS Our new UI now has more places where you can delete the destination point, and the issue appears then, to:
(c) after the Destination is deleted via the context menu's "DELETE" function.
(d) if Destination is deleted by tapping (X) on the Dashboard's Waypoint card

**Comment by sonora** [comment]
See https://github.com/osmandapp/Osmand/commit/80d3d79668d9c59b66a2400e9e2bf05dbacbbe54. Issue needs to be fixed by correctly setting routePlanningMode, because other behavior is affected too, like the resetting the appMode after (a) and (b).

**Comment by sonora** [comment]
(a) fixed via https://github.com/osmandapp/Osmand/commit/d4a8fabda942a226f763d1798cae41f8b68ff287

**Comment by vshcherb** [comment]
Let's not hurry up with fixing this issue, cause the commits I see are not thought through. Even if surprisingly they start working, the logic behind will be confusing. Let's reiterate and fix it properly.

**Comment by vshcherb** [comment]
The fix in TargetsPointHelper is definitely wrong intention, because there it should be impossible to use UI actions. Cause this part is still in development, it is worth to let it stabilize a bit.

**Comment by vshcherb** [comment]
The 2 from left bottom icon should always reflect the current state and we should use to verify the issues:
- Directions icon - not a planning mode and not a following mode
- Blue arrow - route planning mode (possible with following and non-following mode)
- Buttons not visible - not a planning mode, but a following mode
(a) not sure if I can reproduce. So let me reiterate how I would expect it to work.
Directions -> Back / Cancel -> should cancel route  and go to map mode
Tapping on the map should cancel only if there is no destination.
(b)  Agree navigation should be finished. Later it will be impossible to open Waypoints without opening the bottom sheet with route preparations.
(c) Should be implemented with a Bottom Sheet finish navigation. Technically it should be impossible to delete these point and it should be a title Finish navigation instead of delete. 
(d) Agree navigation should be finished.

**Comment by sonora** [comment]
Ok, what I have learned trying to fix it today is this:
- https://github.com/osmandapp/Osmand/commit/d4a8fabda942a226f763d1798cae41f8b68ff287 is a good fix for (a), should stay in place (this fixes entering the route planning menu, then leaving without having set an destination),
- https://github.com/osmandapp/Osmand/commit/ec81f45ee8fbece8fba5f6079a3fd4f628117de5 is a reliable fix for (b), i.e. when user deletes the (last) destination point in the Waypoint dialog. Please note that the Waypoint dialog can e.g. be entered from the Dashboard's "Waypojnts/Show all" function (even once we delete it from the Drawer), so I am not sure this issue would automatically disappear
- So I tried to fix this globally by capturing if no destination was present any more after anybody deleted a waypoint/destination _anywhere_, in this commit: https://github.com/osmandapp/Osmand/commit/f75a8a0a4e46342d519510e4de6eb054678195b8. I still think this is the clean way to fix I, but it had a technical issue, as you mentioned.

I will wait for Alexey's judgment, but still think something like https://github.com/osmandapp/Osmand/commit/f75a8a0a4e46342d519510e4de6eb054678195b8 is probably the way to go here, rather than relying we put a fix after any code which allows to remove a destination.

**Comment by crimean** [comment]
Fix for (a) - https://github.com/osmandapp/Osmand/commit/926670f9b44003ac5daa50eb794ad82370a94438
Fix for (b and d) - https://github.com/osmandapp/Osmand/commit/c3004c08c82c6a377dfe4d5f73d4ef3d51ef7937
Fix for (c) - https://github.com/osmandapp/Osmand/commit/108984926eec23531bbf8869f6d9cf8a81103df9

However I did one thing which was not described here: when destination point is deleted and there are few or one intermediate waypoint exists - then last intermediate point becomes destination and so on until no intermediates left.

**Comment by sonora** [comment]
Yes, ok, thank you! The mechanism about intermediate destinations taking over the destination role as long as there are any should remain untouched, so your remark is exactly correct. I always only meant to talk about when the LAST destination was removed with no further intermediate destinations present.

Regarding the fixes:
(b), (c), (d) Works well. Thanks!

(a) also confirmed working, but with one smaller side effect:: 
 - When you leave the route planning dialog by pressing the "GO" button, but with no destination selected, we now leave the route planning dialog for good, i.e. the "Please select destination first" toast displays all right, but the user ends up on the map screen, Maybe we need another exception for this case, similar to  && !selectFromMapTouch?  But it is not a very big issue.

**Comment by vshcherb** [comment]
Agree, we shouldn't close dialog on GO.

**Comment by vshcherb** [comment]
Even though that's an amendment I will reopen the issue to not forget.
