### ISSUE TITLE
Android auto - preview screen issues - continue navigation

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#21363]
- [x] If you start navigation on disconnected AA and turn on AA, you will see Continue Navigation instead navigation screen itself  - https://github.com/osmandapp/OsmAnd/commit/47a11b302ab5b14741ccd23eb9f6c938608637c9
- [x] Once AA connnected: If navigation started on the phone - preview screen stays on sometimes
- [x] Once AA connnected:  If you start navigation on the phone too quickly (before calculation finished) - menu on the left stays on (route preview doesn't appear at all)

https://github.com/user-attachments/assets/6a67c4be-64eb-49fa-b697-769776a8e62d

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/pull/21399

**Comment by vshcherb** [comment]
- [ ] Stop on the phone doesn't stop on AA

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/commit/fa6b292168c373ee4456ad3e50bdd42d300f8fc3

**Comment by Zirochkabila** [comment]
`OsmAnd~ 5.0.0#3813m, Released: 2024-11-26`

If the device is connected for more than 10 seconds, the image is still broadcast when disconnected (on the first screenshot - less than 10 seconds, on the second - the device is disconnected after 10 seconds).


<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/30b22f43-5a13-45dc-9e21-0747657d5921"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/ac508d5f-1114-4a77-bf4e-b63bf3fbdead"  width="550" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
Preview has incorrect margin on the top 
![Screenshot 2024-11-27 at 12 43 44](https://github.com/user-attachments/assets/c054afc7-8218-4170-975c-df2970e96c66)

**Comment by vshcherb** [comment]
To TEST only preview route fits screen (other items has been tested - OK)!
As issue touches refactoring of preview screen, all combinations need to be tested for preview route:
1. RTL / LTR
2. Tablet landscape
3. Phone portrait / Phone 
4. On the phone: with menu bottom visible and without (navigation could be started from history then menu appears or replace destination once route is calculated)
----
Android Auto:
1. Preview could be left or right (if car driving left or right)

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/commit/77689da7f6d7e4de27dea2f19248a759f5653d86

**Comment by vshcherb** [comment]
- [ ] AA density could vary 1 - 2 ? needs to be fixed properly

**Comment by vshcherb** [comment]
Fixed but requires investigation for weird code

**Comment by Zirochkabila** [comment]
# Testing 2

`OsmAnd~ 5.0.0#3911m, Released: 2024-12-09`

- [ ] No changes are displayed in RTL mode (RTL video)
- [ ] The route is not visible on the screen
- [ ] If the route does not start from the geolocation, it is displayed on the side
- [ ] After starting navigation, the zoom does not respond for about 10 seconds (video)

[Video](https://drive.google.com/file/d/1QslsyIYX57MxI5QRf-S7wum5mWzaM97n/view?usp=drive_link)

<img width="805" alt="Screenshot 2024-12-09 at 15 34 10" src="https://github.com/user-attachments/assets/ed54f3e6-f98b-4ebc-8371-11ac90f23939">
<img width="805" alt="Screenshot 2024-12-09 at 15 34 31" src="https://github.com/user-attachments/assets/9b21ddc0-e923-4333-bfc9-485f312db868">

**Comment by vshcherb** [comment]
2, 3, 4 - Not reproduced
1 - not clear how to change 
- [ ] With player on (route is displayed)
![Screenshot 2024-12-10 at 16 11 28](https://github.com/user-attachments/assets/a779fda3-9195-4450-8922-f347c8766010)

**Comment by Zirochkabila** [comment]
# Testing 3
`OsmAnd~ 5.0.0#3921m, Released: 2024-12-10`

1. Combining and activating three possible RTL activation options one by one did not work for AA:
-  Settings in the developer section on the device
-  Activation of the driving region “Japan”
- Set the application language to “Arabic”
2. If we create a route through AA, sometimes it is not displayed completely (in some cases, we need to add indents on top, in some cases, the route does not fit on the screen at all).

<img width="869" alt="Screenshot 2024-12-10 at 19 10 26" src="https://github.com/user-attachments/assets/9f77cdfb-d577-4824-b030-c5cf997c17a5">
3. If we create a route with the device (using Favorites) and do not use the location as a start or finish point, the route preview (finish point) moves out of the screen

<img width="869" alt="Screenshot 2024-12-10 at 19 19 30" src="https://github.com/user-attachments/assets/16795bf8-498d-4dbf-afbe-d03e91d3c7e4">

4. After starting navigation, the zoom does not respond for about 10 seconds

https://github.com/user-attachments/assets/b9360874-eb4c-4a05-be69-d5d0032d5625



5. If we create a route through AA > switch to YouTube > return to OsmAnd - the route preview is no longer displayed

https://github.com/user-attachments/assets/18edb7bb-fc9d-4b16-85ac-2499a9f92741

6. The case with simultaneous display of the player and the route is not reproduced
<img width="869" alt="Screenshot 2024-12-10 at 19 25 30" src="https://github.com/user-attachments/assets/015853c0-31d4-4561-b799-0248ca0f9fc5">

**Comment by vshcherb** [comment]
Increased borders - https://github.com/osmandapp/OsmAnd/commit/b3f8a034798f6248bcd2ecb3b8a6e142ae141ed4

**Comment by Zirochkabila** [comment]
# Testing 4
`OsmAnd~ 5.0.0#3935m, Released: 2024-12-16` - Increased borders **Added**
