### ISSUE TITLE
Auto zoom forces 3D view all the time - regression

### ISSUE THREAD

**Issue by mdykierek** [osmandapp/OsmAnd#21367]
### Description

If Auto zoom is enabled (I guess default in driving mode) then it switches to 3D all the time.
If I use the button to go to 2D it goes back to 3D all the time.
I want to use 2D and still have zoom at intersections as it was before.

### Steps to reproduce

Use Osmand+ in driving mode.

### Actual result

Switches to 3D all the time.

### Expected result

Should stay in the mode I chose. In this case 2D.

### Your Environment (required)

```
OsmAnd Version: 4.9.6
Android/iOS version: Android 14
Device model: Motorola Edge 40 Pro
Crash-Logs: ?
```

**Comment by Zirochkabila** [comment]
`OsmAnd~ 5.0.0#3764m, Released: 2024-11-19`

Done
