### ISSUE TITLE
2D navigation broken 

### ISSUE THREAD

**Issue by Davi427** [osmandapp/OsmAnd#21372]
### Description

After updating to OsmAnd+ 4.9.6, Released: 2024-11-17 I cannot navigate in 2D anymore, it always goes to 3D.

### Steps to reproduce

Navigate
Press 2D button

### Actual result

Navigation goes to 3D 

https://github.com/user-attachments/assets/c9836be2-1a1f-47a6-97be-dd66f82efea0

### Expected result

2d navigation 

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:OsmAnd+ 4.9.6, Released: 2024-11-17
Android/iOS version:14
Device model:FP5
Crash-Logs: ?
```

**Comment by vshcherb** [comment]
Duplciate, already fixed. 4.9.7 is about to release
