### ISSUE TITLE
Option to disable "auto 3d zoom angle"

### ISSUE THREAD

**Issue by NickSlash** [osmandapp/OsmAnd#21382]
### Describe the idea

"auto 3d zoom angle" seems to have been added in the latest update (it did not auto-tilt before). There is no option to NOT use auto-tilt. 

### Expected behaviour

Disable it, it map doesn't tilt automatically.

### Alternatives you've considered

Using the older rendering method which should not be a solution.

**Comment by Zirochkabila** [comment]
@NickSlash [dublicate ](https://github.com/osmandapp/OsmAnd/issues/21372#issuecomment-2483593794)

**Comment by Buzzz57** [comment]
It has nothing to do with #21372.
At the moment, when you use the zoom -/+ buttons on the screen, the tilt angle changes on its own.
On the opposite, if you use an external device to control zoom, the tilt angle doesn't change.
The behaviour should be consistent and it would be great to have the choice of having an autotilt or not.

Here is an example vidéo showing both behaviours.
https://youtu.be/Ls47cpyVsUQ
