### ISSUE TITLE
Transport stops: description in context menu

### ISSUE THREAD

**Issue by yepyepyep4711** [osmandapp/Osmand#2138]
Hi,

here's my use case:
I use transport stops. From the "transport" section of the "map rendering" options.
Before 2.2.4, I could just tap on a bus stop and see the bus lines halting at a certain stop. One tap.
Now, although we have a context menu, I have to tap on the stop, then on the three dots for "more" of the context menu, then on "Show POI description" to finally see the information I want. So it's a big step backwards for me. 
Is there a a way to turn off the context menu and revert to the old behaviour? Or at least have the description displayed in the extended context menu, after sliding up?

**Comment by hakuchi** [comment]
for me the description is showing in 2 clicks maximal 3.
1. activated transport in map configuration
2. the map is showing me the bus stop as a orange extra POI
3. after long click it showing me a pop-up with name of stop or some time more name's
4. after click on the name(or switching the name to the top of your phone), OsmAnd showing me the description, Lat/Lon, ref, operator, Wikipedia link, bench, shelter, and if it is a bus stop, taxi, or railway stop. + a lot of more if it is tagged on the stop.

you dont need to click on the tree dots to showing description

**Comment by sonora** [comment]
It sounds like a bug.

How hakuchi describes it is how it works ok for all highlighted POIs (orange disks, via "Menu / Search POIs / Show all on map", or via "Menu / Configure map / POI"). But how yepyepyep4711 describes it is how it appears when you highlight transport stops as blue squares via the transport layer ("Menu / Configure map / Transport / Transport stops"). I think this needs to be fixed.

**Comment by xmd5a2** [comment]
I think "blue squares" should be removed as obsolete.

**Comment by xmd5a2** [comment]
Transport route numbers are already displayed in context menu
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot_2016-01-12-21-50-45.png
but without start and destination.

**Comment by yepyepyep4711** [comment]
What? No! The blue squares are fine! They are accessible together with other public transportation items like metro and tram lines, where I need them. They also contain the more accurate/complete information. If you want to cut the redundancy, do so on the pois. Or look for a way to synchronise those two

**Comment by yepyepyep4711** [comment]
also, the fact that the useful information is now hidden away needs to be addressed, no?

**Comment by hakuchi** [comment]
the blue squares not looking so good. 
I think they sold change it to a symbol or something other.
And how reported yepyepyep4711: the description/info of the transport layer sold work in the same way as the POI(orange) description/info.

**Comment by yepyepyep4711** [comment]
well I don't care too much for the looks (although that's nice too), but the quick access to information is important. Especially if you're late and are looking for the right bus ;)

**Comment by yepyepyep4711** [comment]
I'm going to have to downgrade over this. It's worse than I thought. If you select a transport POI the name you get is *not* its POI label but its location, which is utterly useless when you want to know where to get off the bus. I've just missed my stop because of this on a line I didn't know well enough

**Comment by xmd5a2** [comment]
@yepyepyep4711 What POI name are you talking about? Please attach screenshot and give us coordinates.

**Comment by yepyepyep4711** [comment]
@xmd5a2 sure. Here's what I get, the name of the street (the coordinates you wanted are at the bottom):
![screenshot_2016-01-25-23-12-04](https://cloud.githubusercontent.com/assets/10447816/12566631/eaaa5ad2-c3ba-11e5-807c-6f7b640f3457.png)
Here's what I need, the name of the stop and the lines stopping there. It's also what I used to get with one single tap in the previous version and not three like in this one:
![screenshot_2016-01-25-23-12-10](https://cloud.githubusercontent.com/assets/10447816/12566637/f23925a8-c3ba-11e5-93d1-b1ce35343b8d.png)

**Comment by xmd5a2** [comment]
I propose to move this information directly to context menu's bottom.
