### ISSUE TITLE
During navigation, map automatically changes to 3D view

### ISSUE THREAD

**Issue by vmicho** [osmandapp/OsmAnd#21390]
### Description

Just updated from 4.8.6 to 4.9.
When navigating (car) the map constantly changes to 3D view. After clicking on th now-appeared 2D button and changing to 2D, the map changes back to 3D nearly immediately (well, after ~1 second). Sometimes it stays in 2D, you can scroll around, then after pressing the current position button, it changes back to 3D (after a second, very few time it doesn't).
Tried in bicycle mode, 'North up' and in 'Movement direction' map orientaions, same results.

### Steps to reproduce

start navigation somewhere. (real or simulated, both work)

### Actual result

Map switches to 3D, and switches again to 3D after setting it to 2D (2D widget button or finger gesture)

### Expected result

Should stay indefinitely at the current setting.

### Your Environment (required)

```
OsmAnd Version: osmand+ 4.9.6
Android/iOS version: android 13
Device model: xiaomi mi 11i
Crash-Logs: ---
```

**Comment by pingping01** [comment]
Experiencing same issue. Had to use an alternative app to drive several hundred miles home today as I dislike using 2.5D view. 

When the map switched to 2.5D view i didnt notice an option to switch to 2D.

Unless I'm mistaken the option to disable 2.5D has been removed? It was previously in Settings >Profile >General settings then toggle on/off 2.5D view

**Comment by vmicho** [comment]
For me the 2D button appears as soon as it goes to 3D.

**Comment by pingping01** [comment]
It seems that the update last night has fixed this. Drove a short journey this morning & map remained in 2D mode. The app unexpectedly closed towards the end of the journey but I hope that was a one off glitch (I have some automation going on when connected to car)

This probably isn't the place but if anyone knows where the 2.5D toggle is now located please let me know. A change view option should be fairly prominent but although I paid for & used this app for years I can't find the setting anywhere.

**Comment by vmicho** [comment]
yes, just tried 4.9.7, looks stable now :D

**Comment by vmicho** [comment]
can close this then
