### ISSUE TITLE
Offline Routing Engine Error

### ISSUE THREAD

**Issue by CentroneF** [osmandapp/Osmand#2140]
On the cross road in Location: lat = 32.32352; lon = 34.90429 the calculated route from the offline routing engine is forcing the user to make a circle on the cross road instead of turning right before the cross road starts. In addition this maneuver is illegal. 

                
![osmand offline routing engine problem 2](https://cloud.githubusercontent.com/assets/11270732/12197254/cfac62ec-b605-11e5-96f9-af6f611f5e1c.png)
![osmand offline routing engine problem 1](https://cloud.githubusercontent.com/assets/11270732/12197255/cfae23fc-b605-11e5-9f45-43c45d6df046.png)

**Comment by hakuchi** [comment]
report this on [OSM] (http://www.openstreetmap.org/note/new#map=19/32.32342/34.90430&layers=N)
this is a map error no OsmAnd error.
there are missing a lot of turn restrictions on this intersection!

**Comment by utack** [comment]
Still pretty odd Osmand does not take the shorter trunk_link

**Comment by stephan75** [comment]
What is the routing on that position via:
openrouteservice.org
Maps.me app
MagicEarth
Navit
Be-on-Road
EB Dirigo
Mapfactor Navigator free
???
Please give some answers.

Because I think that this is NOT an error in the OSM data.
See http://www.openstreetmap.org/#map=19/32.32302/34.90375

**Comment by hakuchi** [comment]
with the(absolute correct) edits from utak the offline routing is no longer working correct in this crossing.
Osmand will not use the trunk_link.

![crossing] (http://fs5.directupload.net/images/160114/538uvrvn.png)

**Comment by utack** [comment]
Sorry for ruining it ;)
But seriously this is really lucky, a simple case for the developer to find a bug in their routing engine.
Maybe the nodes shared with the "proposed" road confuse the router, since proposed routes may never be used?
It is at least "unclean" because a node on both a proposed highway and a real highway is kind of a "Schrödingers Node": It is existing and not existing at the same time.

**Comment by vshcherb** [comment]
Did you try to regenerate this part of map and routing?

**Comment by utack** [comment]
Yes, I tried the first example, routing from the top to the left.
original: original route layout
noproposed: all proposed routes are gone
forceroute: part of the route is deleted, so it has to use the trunk
[osmand.zip](https://github.com/osmandapp/Osmand/files/91725/osmand.zip)

**Comment by hakuchi** [comment]
tested again with self made map from this crossing, and now OsmAnd is using trunk_link
