### ISSUE TITLE
Freshly installed OsmAnd is confusing new users

### ISSUE THREAD

**Issue by readonly24** [osmandapp/OsmAnd#21419]
### Describe the idea

When you install OsmAnd for the first time, you end up with an empty screen and just nothing happens. For first time users this is very confusing.

### Expected behaviour

After OsmAnd was installed

1. Ask for GPS permission. 
2. Set the zoom level, that one actually can see something of the basic world map.
3. Ask for downloading the more detailed world map, show a toast message that the map is being downloaded in the backgroud. After download has finished load the map and display it.
4. If GPS is fixed, ask for download the detailed map of the current location, load the map and display it.

### Alternatives you've considered

None

### Context

Demo video

https://github.com/user-attachments/assets/dcbd370b-8458-42b6-83d2-8f839537085f

**Comment by yuriiurshuliak** [comment]
We appreciate your feedback and will review these ideas to improve the onboarding experience for new users.

**Comment by vshcherb** [comment]
We need to understand what location by default is displayed, probably it should be worldwide overview and not a blank screen? Like (0,0) - zoom 5

**Comment by dmpr0** [comment]
> Ask for GPS permission.
OsmAnd request GPS when it needed. 

> Ask for downloading the more detailed world map
Most users doesn't need these maps, basic is included with the app

> Ask for downloading the more detailed world map
Use declined, and _end up with an empty screen and just nothing happens._

**Comment by DmitryAlexei** [comment]
Probably we can show online map at a first start?

**Comment by Nine-Tailed** [comment]
> Probably we can show online map at a first start?

Then users will remain on the online map without figuring out how to switch to the offline map ;)

**Comment by readonly24** [comment]
> OsmAnd requests GPS access only when it is needed.
Yes, but I think this should be the first question, because I think almost every new user wants to use GPS.

> Most users don't need these maps; the basic version is included with the app.
That's ok, but set the zoom level, that one actually can see something of the basic world map.

There are not only technically skilled users, so I think they should have a more user friendly start.

**Comment by readonly24** [comment]
If I start from myself, when I install a navigation app, I expect to see a map and my location or so right after the first run, but for sure not just an blank screen.

**Comment by vshcherb** [comment]
Is it reproduced? @DmitryAlexei - it's still in reproducing stage to figure out if there are other conditions involved

**Comment by vshcherb** [comment]
Intitial zoom should be 7.

**Comment by Zirochkabila** [comment]
`OsmAnd~ 5.0.0#3830m, Released: 2024-11-28`

Behavior has not changed


https://github.com/user-attachments/assets/c8bed8de-6324-4473-a43c-a6759e9722d5

**Comment by readonly24** [comment]
Also for me nothing changed. 5.0.0#3841m - I can still see a lot of question marks floating over new users heads.

Why not ask for GPS permission, go to current position and show the basic map in a zoom level where one actually can see a map (I had to press 7! times the minus button) and ask for downloading the detailed map?

**Comment by Zirochkabila** [comment]
# Testing 2

`OsmAnd~ 5.0.0#3911m, Released: 2024-12-09`

Changes arenʼt visible


https://github.com/user-attachments/assets/60bed284-d5cd-4f63-9c49-4328cad8aa64

**Comment by vshcherb** [comment]
> I still can't see the basic map, if I choose not to download a map. I would decrease the zoom level 2 steps (like pressing 2 times the minus button).

That's not the idea, if you skip download you should see City name and see button to download the map. If you choose to use as a world overivew application then you can just zoom out after it and use it
