### ISSUE TITLE
Short way routing - weird unnecessary turns - not enough penalty for turns

### ISSUE THREAD

**Issue by abclop99** [osmandapp/OsmAnd#21424]
### Routing engine

- [X] OsmAnd's in-app offline routing
- [X] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Routing profile: Car
Restriction: None?

Enabled:
- Fuel-efficient way
- Consider temporary limitations
- Minimal distance to recalculate route: 120m
- In case of reverse direction

### Start and end points

An example route on [openstreetmap.org](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=45.290465%2C-75.694099%3B45.292685%2C-75.693967#map=18/45.291566/-75.694031).

Example route on [osmand.net](https://osmand.net/map/navigate/?start=45.290935,-75.693934&end=45.292460,-75.694111&profile=car&params=car,short_way#19/45.29178/-75.69407)

Any route that goes through that intersection in that direction has the same problem.

### Actual route

The actual route turns onto Leitrim Road then turns immediately back onto River Road.

![Screenshot of actual route in the app](https://github.com/user-attachments/assets/68ccb37f-c8aa-4780-b4ab-eb411691112e)

It also shows up on [osmand.net](https://osmand.net/map/navigate/?start=45.290935,-75.693934&end=45.292460,-75.694111&profile=car&params=car,short_way#19/45.29178/-75.69407) with "Short way" enabled

![image](https://github.com/user-attachments/assets/aea9f8aa-a9a4-49b2-bd65-8d695bce02b3)

### Expected route

The route should go straight through the intersection along River Road as on [openstreetmap.org](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=45.290465%2C-75.694099%3B45.292685%2C-75.693967#map=18/45.291566/-75.694031).

Also works properly on [osmand.net](https://osmand.net/map/navigate/?start=45.290935,-75.693934&end=45.292460,-75.694111&profile=car#18/45.29151/-75.69318) without "Short way" enabled.

![image](https://github.com/user-attachments/assets/1433fc17-9f1f-4d91-8c7d-046b53a97847)

### Maps you used (online or offline)

- [x] Offline maps offered within the OsmAnd app for download. 
  - 2024-11-23 10:30
- [x] Online (tile / raster) maps 
  - Whatever is currently on [osmand.net](https://osmand.net/map/navigate/?start=45.290935,-75.693934&end=45.292460,-75.694111&profile=car&params=car,short_way#19/45.29178/-75.69407)

### Your Environment

```
Device : HWBLA
Brand : HUAWEI
Manufacturer : HUAWEI
Model : BLA-L29
Product : BLA-L29
Build : BLA-L29 [10.0.0.159](http://10.0.0.159/)(C605E4R1P3)
Version : 10
App Version : OsmAnd~
Apk Version : 4.8.6 480603
```

**Comment by Sonwon1** [comment]
I have seen this behavior more than once with Osmand. It is usually a map problem. I suggest again that the routing algorithm incorporate some common sense to see if the route makes sense.

**Comment by yuriiurshuliak** [comment]
The bug has been confirmed. Here's how you can consistently reproduce the behavior:

1. Build a route in the Car profile using these coordinates:
   - Start: `45.29093, -75.69393`
   - End: `45.29246, -75.69411`
2. Observe that the route is built correctly when the "Short way" option is not enabled. This aligns with the expected behavior, as seen in this example: [Correct Route](https://test.osmand.net/map/navigate/?start=45.290930,-75.693930&end=45.292460,-75.694110&profile=car#18/45.29179/-75.69485).
3. Enable the "Short way" option and rebuild the route.
4. Notice that the route now includes unnecessary detours via Leitrim Road and back to River Road, as shown here: [Route with Detour](https://test.osmand.net/map/navigate/?start=45.290930,-75.693930&end=45.292460,-75.694110&profile=car&params=car,short_way#18/45.29179/-75.69485).

The issue appears to be specifically linked to the "Short way" routing option. 

<table style="width:100%">
  </tr>
  <tr>
    <th>"Short way" is disabled</th>
    <th>"Short way" is enabled</th>
  </tr>
  <tr>
<th><img src="https://github.com/user-attachments/assets/3025360e-2c57-4afc-b69c-0cee90bdf405"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/df4f7591-8ee9-461d-b92f-849567f742ee"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
It looks like not enough penalties for turns in shortway somehow. But there is a penalty for traffic signals 5 seconds

**Comment by mdykierek** [comment]
To be honest, the penalty of 5 seconds for traffic signals is surprisingly low to me. No traffic lights switch every 20 seconds.
The probability of arriving at traffic signals at red would be close to 50%. The time to stay put at red would be close to 50% of the time, too.
I wonder if the left turn at this intersection is allowed in the end. It's probable that there should be no left turn.

**Comment by mdykierek** [comment]
If someone can confirm the no-left-turn restriction (no street-level available and aerial are inconclusive), I will fix the map.

**Comment by RZR-UA** [comment]
A very similar old Issue: https://github.com/osmandapp/OsmAnd/issues/17641

Technically, we do not consider any penalty for turns in the short_way mode. Ref: GeneralRouter - calculateTurnTime - shortestRoute.

Additionally, penalty_transition could help, but in this case, the difference between secondary and secondary_link is zero (15-15 = 0). Ref: routing.xml lines 759-760 (penalty_transition - short_way).

It seems that short_way's traffic_signals penalty of 5 seconds is useless in this case and should be set to 0.

We're working on the fix and tests.

**Comment by mdykierek** [comment]
You know your product best, but no penalty for traffic lights... + in the app I see that the mode is called "fuel efficient". Standing at traffic lights in not fuel efficient at all.
The intersection needs "no left turn" anyway. Let me know when I can fix the map (OsmAnd fix confirmed).

**Comment by mdykierek** [comment]
Good points. Yet left turns (assuming right side traffic) are always slower and less safe than straight and right. Always involve yield the opposite traffic. I bet there are lots of variables e.g. should paths (non-public) roads follow the same rules, should profile /e.g. bicycle/ affect these rules? For sure I don't know enough to play the smart guy. Keep the good work!

**Comment by Sonwon1** [comment]
I suggest shortest route should be exactly what it says it is shortest route. If politics or climate concerns says an economy mode is needed then that should be added as another routing algorithm.

**Comment by mdykierek** [comment]
It literally reads "Fuel-efficient way" in the app. Standing is inefficient even for all-electric car - heating, A/C, infotainment etc...

**Comment by vshcherb** [comment]
Discussed with @ivanPyrohivskyi, we need to penalties for turns as for usual routing (probably less). Main reason to produce more straight "routes" with obstacles, obstacles still could exist (not only traffic lights) in short way (efficient) routing.

5 seconds for traffic lights is questionable but penalty might exist to avoid multiple stop-go situations comparing 2 residential roads same length 1 with traffic lights and 1 completely without

**Comment by vmicho** [comment]
> If someone can confirm the no-left-turn restriction (no street-level available and aerial are inconclusive), I will fix the map.

In this kind of organization of crossroad, you can safely assume the no-left and other weird turns, and add it directly to OSM - It is not intended to have such turns.

**Comment by RZR-UA** [comment]
To Do

- [ ] transfer Java code to C++

**Comment by Sonwon1** [comment]
@vshcherb Since there is no Shortest Routing way the name of this thread should be Fuel-efficient routing - weird unnecessary turns - not enough penalty for turns #21424

**Comment by vshcherb** [comment]
C++

**Comment by RZR-UA** [comment]
@DmitryAlexei please focus on OsmAnd iOS testing

- [ ] test Web
- [ ] test Android
- [ ] test iOS
