### ISSUE TITLE
Strava overlay has trouble rendering

### ISSUE THREAD

**Issue by Guylby** [osmandapp/OsmAnd#21427]
### Description

Hi,

I've been trying to use a Strava heatmap overlay inside Osmand but the rendering is not smooth at all. Sometimes tiles don't render, sometimes they flicker in and out, some tiles are missing even though they are all downloaded for offline use

What is strange is that another transparent overlay I use for google traffic does not exhibit this behaviour, neither utilising a microsoft earth satellite image overlay.

### Steps to reproduce

Add a strava heatmap overlay
The map source settings I used are as follow:

Link:
`https://heatmap-external-a.strava.com/tiles-auth/run/bluered/{0}/{1}/{2}.png?Key-Pair-Id={REDACTED}&Policy={REDACTED}&Signature={REDACTED}`
You have to have your own KeypairID, Policy and Signature for it to work

Zoom: Min 8 - Max 19
Expiry: 43829mn (1month)
Mercator projection: pseudo-mercator
File format: 1 image file per tile

For the last settings, using sqlite db results in the same behaviour

### Actual result

Two examples of tiles not loading, are flickering in and out. All tiles were downloaded offline and stored on the device, so it's not a problem of missing data (especially as you can see them flickering in and out, showing they are indeed present)

| Example 1  | Example 2 |
| ------------- | ------------- | 
| <video src="https://github.com/user-attachments/assets/9f80323b-7fe7-48ae-906c-68e2f3b1cd79"></video> | <video src="https://github.com/user-attachments/assets/1f63c230-a851-410d-a66d-7f15407d4dc8"></video> |

### Expected result

Tiles are loaded correctly and don't flicker

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.9.7
Android/iOS version: 13
Device model: Sony Xperia 10 III
Crash-Logs: ?
```

**Comment by Guylby** [comment]
This is the link for the google traffic overlay:
`https://mts0.googleapis.com/vt/lyrs=m,traffic&x={1}&y={2}&z={0}&style=15`
You still get a little bit of superfluous information like some location and POIs but it's the one that is the cleanest that I found

**Comment by pebogufi** [comment]
Thanks a lot !

**Comment by yuriiurshuliak** [comment]
I was able to reproduce the issue with the Strava heatmap overlay. Here's what I did:  
1. Set the Overlay map to a custom Strava heatmap using the link: [https://t.me/ruosmand/167446](https://t.me/ruosmand/167446).  
2. Kept the map source as an offline vector map.  
3. Set the Overlay visibility slider to maximum.  
4. Scrolled the map and zoomed in and out.  

**Observed Behavior**:  
- Some tiles do not load immediately but appear after a short delay.  
- I did not observe flickering or tiles temporarily disappearing during my testing.  

This behavior seems consistent with how online maps load tiles, even when pre-downloaded.

OsmAnd~ 5.0.0#3807m, released: 2024-11-26

<table style="width:100%">
  </tr>
  <tr>
    <td> <video source src="https://github.com/user-attachments/assets/877ee2ae-8d63-4fc0-b3fe-ebeccc835353"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/user-attachments/assets/94db3329-b64e-4103-8d0b-632893dd0c8c"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by Guylby** [comment]
I don't know if anything changed with Osmand+ 4.9.8 but I can't reproduce the issue anymore so I guess it's fixed!
