### ISSUE TITLE
maxspeed:conditional @ wet / @snow always announced as the current speed limit

### ISSUE THREAD

**Issue by vmicho** [osmandapp/OsmAnd#21426]
### Description

Example way: https://www.openstreetmap.org/way/158074867
Here, osmand announced speed limit 80, while it is 130 (110 at night).
The road segment (quite long one) is marked additionally with `maxspeed:conditional=110 @ (22:00-05:00); 80 @ wet; 80 @ snow` (also marked with a roadsign)
Not sure is the wet or snow or both are interpreted. Anyway if Osmand doesn't know wet/snow conditional, it should better not interpret it at all.

Nice to have: perhaps an icon with wet / snow pictogram with maxspeed.
Note: could not reproduce right now (4.7 and 4.9). It looks like the 110 condition is right now in effect (it is 23h+ right now)

### Steps to reproduce

drive through this segment: https://www.openstreetmap.org/way/158074867

e.g. osmand maps: https://osmand.net/map/navigate/?start=47.445174,9.723276&end=47.474229,9.739857&profile=car#13/47.4607/9.7079
(starting on bridge over Senderstrasse, the maxspeed changes to 80)

### Actual result

starting on bridge over Senderstrasse (direction N), the maxspeed changes to 80

### Expected result

should be still 130 (for car)

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.9.7 + 4.8
Android/iOS version: android 13
Device model: xiaomi mi 11i
Crash-Logs: ---
```

**Comment by vshcherb** [comment]
To do: As we don't have weather information we should use ignore 'snow', 'wet' and other weather condtions (find by taginfo)

**Comment by RZR-UA** [comment]
The bug has been found and fixed [4.9]. The  C++ code was not synchronized with Java. Additionally, a better parsing for conditional tags is proposed [master].

**Comment by vshcherb** [comment]
Will leave for future as we need to migrate these changes to IOS - have UI to support this.

**Comment by Zirochkabila** [comment]
OsmAnd~ 5.0.0#3840m, Released: 2024-11-29   ---   **Done** (AA too)
4.9.0.9   ---   Should be fixed too
