### ISSUE TITLE
Add construction=yes to POI details widget

### ISSUE THREAD

**Issue by vlotorev** [osmandapp/Osmand#2142]
Currently, POI "construction=yes" tag doesn't get shown on POI details. But it might be frustrating to user to navigate to POI only to view the actual POI under construction.
Also it might worth to render such POI in a different way, e.g by overlapping small hammer icon on POI label.

According to http://taginfo.openstreetmap.org/search?q=construction%3Dyes it's set on > 50K POIs.

**Comment by hakuchi** [comment]
do you have some examples for your POI under construction?
becouse not all 50k construction=yes are POI
and the tag construction=yes is not he best way to map something under construction

**Comment by xmd5a2** [comment]
Fixed
