### ISSUE TITLE
Incomplete recorded GPX track

### ISSUE THREAD

**Issue by luigifab** [osmandapp/OsmAnd#21429]
### Description

As usual, I press end, and I saved the GPX track of the afternoon. But when I tried to open it in another place, it doesn't open, and when I display it in OsmAnd, 50% of the track is lost!

The red path is the recorded track. When I saved it, it was displayed full (to the current position), it didn't stop near FE20.

How to recover?

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/d7043838-b4d2-4c97-8766-942c20d4ec36"  width="300" height="auto"/> </th>
  </tr>
</table>

I think OsmAnd crashed today, but I don't remember when, and again, my GPX track was fully displayed when I saved/ended it.

### Steps to reproduce

I don't know

### Actual result

Recorded track incomplete [track.zip](https://github.com/user-attachments/files/17894258/track.zip)

### Expected result

Recorded track complete

### Your Environment (required)

```
OsmAnd Version: 4.9.7
Android/iOS version: 11
Device model: wiki power u10
```

**Comment by yuriiurshuliak** [comment]
I was unable to reproduce this bug under default settings. It's possible that this behavior is related to specific recording settings in your setup. Here are a few steps to investigate and potentially resolve the issue:  

1. **Check the "Auto-split recordings after gap" option**: If this is enabled, it's possible that the recording was split into multiple tracks. Please check if another track exists for the same date.  

2. **Optimize your recording settings**:  
   - Reduce the **General logging interval** to 1 second.  
   - Disable the **Minimum accuracy** option.  
   - Reset the plugin settings to default by going to **Trip Recording Plugin Settings > Reset to Default**.  

3. **Disable unnecessary functions**: Visit [Trip Recording Settings](https://osmand.net/docs/user/plugins/trip-recording/#recording-settings) and turn off any features that you don’t require.  

If these steps do not resolve the issue, please provide the following for further analysis:  
- Your profile settings (including any custom configurations).

**Comment by vmicho** [comment]
I have same issues with 4.9.7, the 4.8.x and previous versions were perfectly fine.
Seems to happen on longer gpx. Happened last weekend on a 20 km and a 30 km gpx.
I only have a screenshot (the issue disappears after osmand restart, or probably also after reloading gpx track), the saved gpx is whole OK.

The dots mark very approximately the remaining of the gpx:
![image](https://github.com/user-attachments/assets/638afa0e-4faf-43ab-b35f-40766652e1f6)

Analyzing on the gpx (I do not have the very original, just a processed one) and with the screenshot, the virtual cut was produced after about 1h05m and 8.8...9 km.

**Comment by akkana** [comment]
I'm having the same issue, just in the last few days, on a hike two days ago then again today. I'm in the beta program; in the menu under About OsmAnd/"What's new" it says OsmAnd+ 4.9.8, released 2024-11-29, on a Pixel 6a running Android 14. My last successful trip recording was on 11-29 which I'm guessing was before I picked up the most recent update. Trip recording has been working fine until two days ago.

On today's hike, for the first half it seemed to be recording okay when I happened to look. At about the 3/4 mark I added a waypoint, and that seems to be where the trouble started (I think that was true on Monday too, that it was okay until I added the first waypoint). Suddenly the track it had been showing me earlier wasn't visible any more; I could see my waypoints, but a lot of the track wasn't showing. I added a second waypoint and it seemed like things got worse and I lost even more of the track. When I finally Finished, came home and uploaded, the track saved two short segments of the hike and the two waypoints, but not the rest of the hike.

Here's a map of the full hike, in blue (which it was showing as the currently recording track until most of it vanished near the end); and a map showing the two short segments, in red and yellow, that it actually recorded. On the second map I've zoomed in one extra zoom level so the yellow track shows up better.
![actual-hike](https://github.com/user-attachments/assets/65f05e79-1401-40d6-a209-445ae86f08e3)
![recorded-track](https://github.com/user-attachments/assets/a00f7932-f3fa-4fbd-a53f-7e0096069883)
Github won't let me attach a .gpx, but I could rename it and upload it if it might be helpful.

Settings: "Auto-split recordings after gap" is on (I thought I had it off before: could the update have turned it on?) But there was only one recorded track available.
General logging interval is 5.
Minimum accuracy is 50m (a default, I never noticed this setting before). I'll try changing it to "Not selected".
At the top of the Trip Recording settings is a warning about Android battery optimization. If I tap on the more info button, it takes me to an App battery usage screen that lists apps; if I choose OsmAnd, it shows only one setting, Allow background usage, which is on.

I'll run some experiments at my next opportunity to see if it's really related to setting waypoints.

**Comment by vmicho** [comment]
note: you can rename the file.gpx to file.gpx.txt if you want to upload it (anyway it is a text file).

PS: my settings are: 0 s, 2 m min, 50 m accuracy, no splitting (I prefer max accuracy and 1 whole gpx track per trip)
I was also adding map markers during trip, doesn't have any visible effect on recording.
The cut does not correlate with any stop (I made a stop a bit later)
The track shows OK on screen during the whole recording. It is only after saving it is cut on screen, then after reloading Osmand it is shown correctly whole, the saved gpx is also whole.

**Comment by vshcherb** [comment]
- It could happen that currently recorded track is incomplete, however after saving it is in most of the cases ok
- If you had a specific crash that caused incomplete saving it's probably better to attach so we can investigate.

As of now we didn't reproduce neither crash nor track incompleteness after saving

**Comment by luigifab** [comment]
Again now, there is a major problem! Check the current position on the map and the end of the recorded track!! When I press end the red track continue until the current position.

![Capture d'écrans_20241205-171012](https://github.com/user-attachments/assets/7e3625dc-ee9e-4ebb-8113-b31865eb56cb)

![Capture d'écrans_20241205-171309](https://github.com/user-attachments/assets/e42806a8-2a1a-4375-a9a4-59344b1ee980)

Auto-split recordings after gap is off.
How can I recover the recorded track?

How can I install the previous version?
I'm sorry but I'm loosing my time, because now I have to redraw the track of the day.

**Comment by luigifab** [comment]
Is it possible this happen because I started by mistake the navigation? Because now we can hide the useless navigation button on the screen, there there are a lot of navigate button elsewhere.

**Comment by luigifab** [comment]
lol, sorry I'm on fire, this time the GPX file is full when si display it on another place, but the first one attached wasn't

**Comment by akkana** [comment]
I reset my Trip Recording Plugin Settings yesterday after reading through this. Today I did about a 3.5-mile bike ride, and didn't take the phone out at all during the ride, no waypoints or checking the route or anything. When I got home and looked at my phone, I couldn't see a track line drawn anywhere along the route I'd taken. I clicked Finish, then Analyze on map, and the route it's showing me has a Distance of 11 ft, and doesn't show a track even if I zoom way in. So much for my theory that it's related to setting waypoints.

Just tried another experiment: I clicked the concentric-circles icon next to REC, then Start (concentric circles changes to a red circle), then rode about 1/4 mile, took the phone out -- it had no track visible and said 0 ft. I rode back home (maybe 5 min total). Still 0 ft and no track, but it showed two checked-flag icons, one at my current location and one displaced a bit east of the actual location.

But while I was typing that, a red line appeared going from my current (start and end) position out to the place where I stopped earlier. Just a single line, not the every-5-second track I would normally expect. And a third checkered flag appeared there, and the mileage changed to 0.29 mi (which, by the distance measuring tool, is the straight line distance between my start point and my pause point).

Just checked settings to verify: General logging interval is still 5 seconds (which is what I got from Reset plugin settings to default yesterday).

**Comment by vmicho** [comment]
Another bicycle experiments (recording done on Browse map profile):
* 4.2 km gpx: no problem observed - seems too short
* 32 km gpx: was cut on screen after saving, on a straight segment (no physical pause there); Show on map turned off -> all OK, track disappeared; the saved gpx is whole, reappears on screen OK after reopening the gpx
* 18 km gpx: cut at around 7.5 km mark / 1630th point (from Viking, at the approximate point given the screenshot). Again no pause made there just going steadily. After saving, I pressed in track properties "Show on map" to turn it off -> Osmand CRASHED. After app restart the track shows whole. Again saved gpx is whole too. Example screenshots below:

![Screenshot_20241206-220434_OsmAnd+ WHOLE](https://github.com/user-attachments/assets/a375351c-b57c-4004-a12d-64aeaf06b174)

![Screenshot_20241206-220541_OsmAnd+ CUT](https://github.com/user-attachments/assets/86ec4619-1a25-4b9e-8e48-9a55a40ab1c8)

I'd say there is some problem on visualisation, can cause crash.

**Comment by luigifab** [comment]
With version 4.9.9 the trip isn't always displayed on the map when recording:

![Capture d'écrans_20241211-103450](https://github.com/user-attachments/assets/9314a015-4f38-47ea-a058-a5d290f6c813)

**Comment by luigifab** [comment]
yes... and no!
again here, I didn't stop, I only switch off the screen, and track is recorded! (no stop from the end of the recording and current position)

![Capture d'écrans_20241211-105755](https://github.com/user-attachments/assets/de4850e9-16f3-4ef6-85e8-f1067b76937a)

where can I download v4.8 for this shit of android 11? I tried from your website, in version history, but when I tried to install it, Google files said: you can't, not you are not allowed, without any reasons.

**Comment by luigifab** [comment]
here the screen switch off automatically

![Capture d'écrans_20241211-111451](https://github.com/user-attachments/assets/f2e0ad8b-3597-4db6-b109-8279b7bcc498)

**Comment by luigifab** [comment]
here the track isn't recorded because I was using Firefox for my previous message

![Capture d'écrans_20241211-111807](https://github.com/user-attachments/assets/4d676e83-b8fb-44d3-bf87-ddd67da5d9a0)

here track isn't displayed only for the current zoom level 

![Capture d'écrans_20241211-112240](https://github.com/user-attachments/assets/3fa50e9c-e99e-4942-80b2-3c55188a9c40)

**Comment by akkana** [comment]
The problem in my case definitely isn't only display. The distance shown while still tracking stops after just a few feet -- 11 feet seems to be the most common number shown as the total distance after it stops recording, though I've seen other numbers too.

Sometimes after 5-10 minutes or more, it will randomly wake up and record a few more feet, then stop again, so at the end I'll have several disjoint segments, each anywhere from a single point to a few tens of feet.

It fails every time; I haven't successfully recorded a track with OsmAnd since 11-29.

**Comment by luigifab** [comment]
Recording issues **seems** to be resolved in 4.9.10.
But recording track isn't always displayed (it depend if the zoom & position & direction of the map).

**Comment by yuriiurshuliak** [comment]
Related to https://github.com/osmandapp/OsmAnd/issues/21549
Fix already in 4.9.10

**Comment by yuriiurshuliak** [comment]
@luigifab We encountered a similar issue, but it only occurred with the first rendering version. Please try switching to the second rendering engine to see if it resolves the problem. You can do this via: **Menu → Settings → OsmAnd settings → Map rendering engine.** Let us know if this fixes the issue.

**Comment by vmicho** [comment]
actually on 4.9.10 it is still cutting the track on display (gpx is fine as before) ...

**Comment by luigifab** [comment]
I don't remember exactly, but there are no more problems (for me).
