### ISSUE TITLE
Add TTS in Vietnamese 

### ISSUE THREAD

**Issue by zipav** [osmandapp/OsmAnd#21438]
### Describe the idea

A user contacted us with a problem that Vietnamese is not available in the list of languages for voice prompts, although it is available in the list of languages at the link: https://accessibleandroid.com/list-of-languages-with-available-tts-engines-on-android/

### Expected behaviour

Vietnamese language is not available (see screenshot)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/951f12f6-e810-4246-bc37-faaae32eab42"  width="300" height="auto"/> </th>
  </tr>
</table>

### Alternatives you've considered

The customer provided a json file for Vietnamese language: https://drive.google.com/file/d/1SeKd0CBHZayhu5TrkShOVTDyVzTc93Vh/view?usp=drive_link

**Comment by vshcherb** [comment]
[vi_tts.js.zip](https://github.com/user-attachments/files/17933858/vi_tts.js.zip)
CC - @sonora

**Comment by sonora** [comment]
The file is metric units only, otherwise in great shape from what I see. (Not meaning to say I can judge the linguistic content ... :wink:)

I have added it to our repository and will include it in the resource definitions and strings, so it becomes part of the app.

If we have any details or username of the contributor, I would be happy to credit that in the comment header.

**Comment by vshcherb** [comment]
Many thanks @sonora

**Comment by Duc9101** [comment]
> The file is metric units only, otherwise in great shape from what I see. (Not meaning to say I can judge the linguistic content ... 😉)
> 
> I have added it to our repository and will include it in the resource definitions and strings, so it becomes part of the app.
> 
> If we have any details or username of the contributor, I would be happy to credit that in the comment header.

I'm the one who creates the file. It's great to see that Vietnamese's going to be added. And in Vietnam, we only use metric units so I didn't include other units.

**Comment by Zirochkabila** [comment]
Need added to iOS version too

<table style="width:100%">
  <tr>
    <th>4.9.0.11</th>
    <th>OsmAnd~ 5.0.0#3869m, Released: 2024-12-03</th>
  </tr>
  <tr>
<th><img src="https://github.com/user-attachments/assets/6bc27d38-8351-42ed-a420-604d839ea1f5"  width="500" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/de101d04-52f2-4398-ab19-3f7788dccc70"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/navigation/guidance/voice-navigation#tts-text-to-speech
