### ISSUE TITLE
Bremen and Berlin in standard map of Germany but regional maps not marked as downloaded

### ISSUE THREAD

**Issue by skwde** [osmandapp/OsmAnd#21436]
### Description

It seems like the regions Bremen and Berlin are included in the standard map of Germany because they are shown as green on the map.

When I check under Map resources I can still separately download these regions (not marked with green).

Moreover when downloading the standard map I cannot chose these to regions.

Possibly related:

- https://github.com/osmandapp/OsmAnd/issues/15273
- https://github.com/osmandapp/OsmAnd/issues/11642

### Steps to reproduce

1. Try to find Bremen and Berlin in standard map download (where you can select the regions)
2. Download the standard map of Germany and check on the map if the regions Berlin and Bremen are available.
3. Check the regions download and see that you can still download Bremen and Berlin even if they are already present

### Actual result

- Bremen and Berlin are missing from standard map Germany download menu
- Bremen and Berlin are downloaded with the standard map but not marked as downloaded

### Expected result

The standard map for Germany should include all regions and mark all regions as downloaded.

### Your Environment (required)

```
OsmAnd Version: 4.9.7
Android/iOS version: 15 (GOS)
Device model: Pixel 7a
```

**Comment by scaidermern** [comment]
I can see Berlin and Bremen in the list of maps for Germany (OsmAnd 4.9.7) :thinking: 
Does refreshing the list help?

**Comment by skwde** [comment]
Ohh I see, under regions they are called "Berlin" and "Bremen", while under "Standard Maps" before pressing download they are called "Brandenburg, Berlin" and "Lower Saxony, Bremen".

Consistent naming would be helpful.

What I still notice though, not all Regions are marked with green on the left even though I downloaded "Standard Maps".
In particular the maps "Berlin" and "Bremen" still marked gray and I am able to download them.

I did notice the same for all regions in "Austria" and "Switzerland".

I only downloaded "Standard Maps" of above mentioned countries almost all regions are still marked with gray. Only for Germany all regions (apart from Berlin and Bremen) are marked green.

So why is that? What am I missing here?

**Comment by yuriiurshuliak** [comment]
I attempted to reproduce the problem following the described steps:  
1. Opened the OsmAnd app and navigated to the **Standard Maps** download menu for Germany.  
2. Downloaded the **Standard Map of Germany**.  
3. Verified the status of regions **Berlin** and **Bremen** in the **Map and Resources** section.  

**Result**:  
Both **Berlin** and **Bremen** are visible on the map, included in the **Standard Map of Germany**, and correctly marked as loaded (green) in **Map and Resources**.  


OsmAnd~ 5.0.0#3793m, released: 2024-11-25

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/53ad19ea-d5f7-4433-b9f7-20ef10058de7"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/173e5feb-700e-43f2-a732-c1688b88eb6a"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by skwde** [comment]
Hmm that's surprising.

Here are the screenshots from my device

![Screenshot_20241125-114603](https://github.com/user-attachments/assets/84dcc29e-6304-4243-9a5c-7a8db69ad478)
![Screenshot_20241125-114634](https://github.com/user-attachments/assets/924c575a-ae54-475f-8c29-04a651306ccb)

I also just noticed, that there is "Berlin" and "Brandenburg, Berlin" as well as "Bremen" and "Lower Saxony, Bremen".

What is the difference of those?

Here are similar ones for Austria and Switzerland

![Screenshot_20241125-114650](https://github.com/user-attachments/assets/84bdcce3-858a-442d-95ed-1df9900930c8)
![Screenshot_20241125-114704](https://github.com/user-attachments/assets/2dd95b74-74ee-4591-a542-83619de89174)

**Comment by scaidermern** [comment]
> I also just noticed, that there is "Berlin" and "Brandenburg, Berlin" as well as "Bremen" and "Lower Saxony, Bremen".
> 
> What is the difference of those?

"Berlin" contains Berlin, "Brandenburg, Berlin" contains Brandenburg+Berlin. The same for Bremen and Lower Saxony.

**Comment by skwde** [comment]
Ok, thanks for the info.

Any idea why in my case the regions are not marked as downloaded and how to fix that?

**Comment by scaidermern** [comment]
Not sure if I understand this correct but after downloading "Brandenburg, Berlin" you also expect "Berlin" to be shown in green in the list of downloadable maps?
This region is already covered by "Brandenburg, Berlin" but nevertheless "Berlin" is still a separate map (which you shouldn't download, otherwise you have to maps installed for the same region, leading to bugs). So showing in in green wouldn't be correct I guess. Still, I can understand that this can be confusing.

**Comment by skwde** [comment]
1. A inconsistency / confusion in display:

    To be more precise, I only downloaded the "Standard Maps" for "Germany", "Austria" and "Switzerland" and **no** "Regions" maps.
    While for "Germany" all "Regions" but "Berlin" and "Bremen" are green, no "Regions" are green in "Austria" and "Switzerland".

    Why is that?

    Besides that, I still don't know what expected behavior here should be.

2. Regarding "Germany" with "Berlin" and "Bremen" in Green I think boils down to what Green should actually present.
    
    From a user perspective, I am only interested to see / know that I downloaded all "Regions" when downloading the "Standard Map". It certainly is confusing that I download the "Standard Map" which is thought to include all regions and then find some regions not downloaded?!

    In addition to that, when I now download "Berlin" and "Bremen" I don't get warned that this leads to Problems and instability of the app (something I already experienced before looking into the Maps a bit closer). I think many users are just interested in *getting the entire* map without checking every "Regions" map or what is included in "Standard Map".

    So from that perspective it just makes sense to use green for *maps present on the device*.
    At least the current status is fairly error prone and requires *a lot more looking into the details*.

**Comment by scaidermern** [comment]
> To be more precise, I only downloaded the "Standard Maps" for "Germany", "Austria" and "Switzerland" and no "Regions" maps.
> While for "Germany" all "Regions" but "Berlin" and "Bremen" are green, no "Regions" are green in "Austria" and "Switzerland".
> 
> Why is that?

Because Switzerland and Austria are small enough that they have _one_ map that contains the whole country. Additionally, they have smaller regions in case you don't need the full map.
Germany in contrast is too large to have one full map. It only has regions. You can see this by looking at the "Standard map" entry that displays "All regions: 14" (or alternatively "All regions: 5/14" if you didn't download all of them). Switzerland and Austria have no "All regions" text in their standard map.

And yes, this is definitely not obvious.

> In addition to that, when I now download "Berlin" and "Bremen" I don't get warned that this leads to Problems and instability of the app (something I already experienced before looking into the Maps a bit closer).

True :( I've created #15039 for this quite some time ago.

**Comment by skwde** [comment]
Alright, thanks for the explanation.

> Because Switzerland and Austria are small enough that they have one map that contains the whole country. Additionally, they have smaller regions in case you don't need the full map.
Germany in contrast is too large to have one full map. It only has regions. You can see this by looking at the "Standard map" entry that displays "All regions: 14" (or alternatively "All regions: 5/14" if you didn't download all of them). Switzerland and Austria have no "All regions" text in their standard map.

Is this behavior documented somewhere?

"Standard Map" being independent from "Regions" but still providing the same data seems really counterintuitive and very error prone to me. Just to give you an example of how it went for me

- At first I thought I have to download everything "Standard Map" and "Regions" to get the most detailed map. (I thought Standard Map having less details than Regions) I ran into problem with inconsistency, so I started to search for a solution. It took me a while to find a (german) discussion in some forum which gave me the clue that both actually give the same maps.
- Next I downloaded only Standard Maps and found that only some regions are marked, thus I created this issue.
- After some discussion (and time investment on your and my side) we arrive here just to find clarify that both Standard Map somehow reference the same maps but are downloaded via different package.

In any case, I am aware of that now but still hope that it is some day made a bit more intuitive!

I close this issue because from my end I am satisfied with the solution.
Though a link to documentation of this would still be nice!

Thanks for time investment and patience on your end!

**Comment by scaidermern** [comment]
> > Because Switzerland and Austria are small enough that they have one map that contains the whole country. Additionally, they have smaller regions in case you don't need the full map.
> > Germany in contrast is too large to have one full map. It only has regions. You can see this by looking at the "Standard map" entry that displays "All regions: 14" (or alternatively "All regions: 5/14" if you didn't download all of them). Switzerland and Austria have no "All regions" text in their standard map.
> 
> Is this behavior documented somewhere?

I'm afraid it isn't or I can't find it. There is no such explanation here: https://osmand.net/docs/user/personal/maps-resources
