### ISSUE TITLE
Add support for some common POI

### ISSUE THREAD

**Issue by math1985** [osmandapp/Osmand#2143]
Would it be possible to add support for the following common POI? All have more than 2000 occurrences according to taginfo. Thanks in advance!

* [ ] man_made=street_cabinet
* [ ] ~~man_made=watermill~~
* [ ] leisure=firepit
* [ ] ~~office=religion~~
* [ ] ~~craft=metal_construction~~
* [ ] ~~historic=wreck~~

**Comment by xmd5a2** [comment]
Please check https://github.com/osmandapp/OsmAnd-resources/blob/master/poi/poi_types.xml
Most of these are already supported https://github.com/osmandapp/OsmAnd-resources/blob/master/poi/poi_types.xml

**Comment by math1985** [comment]
Sorry, not sure why I couldn't find these myself. Will triplecheck things before submititng from now on!

**Comment by xmd5a2** [comment]
Fixed

**Comment by math1985** [comment]
Thanks!

For future reference, this was fixed in https://github.com/osmandapp/OsmAnd-resources/commit/35dff4dd13112609146cb715c89e4f2d68f939d1.
