### ISSUE TITLE
Add some POI to the map

### ISSUE THREAD

**Issue by math1985** [osmandapp/Osmand#2144]
Would it be possible to consider rendering of the following objects POI? All have more than 10000 occurrences according to Taginfo.

* [ ] man_made=works
* [ ] amenity=parking_space
* [ ] man_made=surveillance
* [ ] office=company
* [ ] man_made=flagpole
* [ ] man_made=gasometer
* [ ] man_made=water_works
* [ ] amenity=bbq
* [ ] shop=newsagent

I'm not sure if all of them make sense to render, so feel free to discard as appropriate.

**Comment by Barrocas** [comment]
I know that at least these two are already rendered as POI in Osmand:

man_made=works (I think this one is not rendered on OSM)
office=company

-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by math1985** [comment]
I think they are in the POI database, so you can search for them, but they are not rendered by default.

Especially shop=newsagent seems to be an omission.

Unless I'm overlooking things again, of course.

**Comment by xmd5a2** [comment]
Do you mean rendering on map or just POI (search, orange circles)? If just POI then 8 of 9 already supported except parking_space. Can't imagine use case of searching this as POI instead of parking. Again, check poi_types.xml and default.render.xml (map rendering style) before asking to add some tags.

**Comment by math1985** [comment]
I mean rendering on map (changed title to match), i.e. changing default.render.xml.

As I said, for some of them it probably doesn't make sense to render them, so feel free to dismiss these suggestions. However, I think at least newsagent should be rendered, as all other popular shops are rendered too.

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/9931e644e3169c95abeb35ce4b39761f34906a9c
Other POI in your list is less important. May be I'll add some of them in future.

**Comment by math1985** [comment]
Thanks!
