### ISSUE TITLE
Search for brands not always show results on map

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd#21440]
### Description

When searching for brands, POIs are displayed in the search results, but don't highlighted on the map.

### Steps to reproduce

- search for a specific brand (especially when map is centered on a location without maps)
- tap "show @brand name@ on the map"

### Actual result

POIs are not displayed on the map when zoom level is higher than 9.

### Expected result

POIs should be displayed on the map

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd~ 5.0.0#3798m, released: 2024-11-25
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by Zirochkabila** [comment]
Brands are displayed on both platforms, but different data is shown in the search bar

<table style="width:100%">
 <tr>
    <th>4.9.0.7</th>
    <th>OsmAnd~ 5.0.0#3821m, Released: 2024-11-27</th>
  </tr>
  <tr>
<th><img src="https://github.com/user-attachments/assets/3857ad55-ca29-4eaf-98e5-b712bfc2d5d4"  width="425" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/9dcc1b83-7510-498e-b1c1-b08e69dea6c2"  width="300" height="auto"/> </th>
  </tr>
</table>
