### ISSUE TITLE
Creating favourite: "Save" option not visible on small screen

### ISSUE THREAD

**Issue by martenjj** [osmandapp/Osmand#2145]
Trying to create a favourite by doing a long press on map and then tapping the "star" at the bottom left.  On my phone (Galaxy S5) the top bar is not visible when the keyboard is shown, see screenshot 1:

![screenshot_2016-01-13-16-49-22](https://cloud.githubusercontent.com/assets/10631760/12301242/e1f35608-ba16-11e5-8a03-f328bd9b3269.png)

Pressing the "back" button to hide the keyboard shows the top bar with the "Save" option, see screenshot 2.

![screenshot_2016-01-13-16-49-31](https://cloud.githubusercontent.com/assets/10631760/12301273/0518253c-ba17-11e5-905a-ff265f16582b.png)

Only after trying out the app on a larger screen tablet did it become apparent how to save the favourite.

**Comment by sonora** [comment]
I am not even sure it is a matter of screen size, looks like the top row with the SAVE button gets scrolled off the screen on many f not all devices while the keyboard is shown.

We must either prevent this scrolling, or maybe even better place the SAVE button next to the REPLACE button, so these 2 are closer together and more visible.

**Comment by vshcherb** [comment]
Let's try to make topbar visible

**Comment by sonora** [comment]
Fix works well, thanks!
But fact is the orange REPLACE butoon still remains a lot more visible than the white SAVE. And I guess there is no logical or functional justification for this, they should have the same style and be in the same area?
