### ISSUE TITLE
Travel guides issues

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#21452]
### Description

1. Show more button does not work immediately
2. OsmAnd crashes after the third click on Show more, starting the download, and clicking on the link in the guide article

[logcat (93).log](https://github.com/user-attachments/files/17921020/logcat.93.log)
[exception (62).log](https://github.com/user-attachments/files/17921021/exception.62.log)

### Steps to reproduce

1. Menu > Travel guides > Show more
2. Menu > Travel guides > Show more (3 times) > Europe > "hight speed train"

### Actual result

https://github.com/user-attachments/assets/3741cfae-686c-4c56-96a4-38be9304e9c2

### Expected result

- [ ] "Show more" button works the first time
- [ ] OsmAnd continues to work without failures

### Your Environment (required)

OsmAnd~ 5.0.0#3806m, Released: 2024-11-26

**Comment by vshcherb** [comment]
Button works differently if maps are downloaded, so you could see other articles
