### ISSUE TITLE
No apparent way to remove the orange position marker

### ISSUE THREAD

**Issue by martenjj** [osmandapp/Osmand#2146]
After making a position by a long press on the screen, there doesn't seem to be any way to remove the orange marker.  I've tried short tap on the map, zooming, scrolling far away, showing and hiding the dashboard/menus, and even going to the home screen and then back to the OsmAnd app.  The only way to remove it seems to be to kill and restart the application.

**Comment by sonora** [comment]
Simply sliding down the context menu will remove the marker.

**Comment by martenjj** [comment]
So it does, assuming that by "menu" you mean the information pane that appears at the bottom with the address and option buttons.  But it's not obvious, and of the two possible ways to dismiss the pane only one of them clears the marker (slide down => marker disappears;  press "Back" button => marker stays).  If this is intended to be the way then the marker should disappear on "Back" too.

**Comment by utack** [comment]
Agree with @martenjj, pressing back should clear it together with the context menu

**Comment by sonora** [comment]
Well, yes, not sure, I have not coded this myself. I guess the intention was to provide both alternatives: One where the location context menu can be hidden while the map marker stays in place, the other one killing the marker itself, too.

I personally got used to it myself over the last few days, not sure if there is a more intuitive way to implement the same degree of flexibility.

**Comment by raindropsfromsky** [comment]
I prefer to call the context menu a "card", as Google calls them.

I'd suggest yet another method to close the "card" and also to dismiss the point-marker: Just tap on the ***grippy*** (=the thin strip with three dots, located at the top of the card). Currently you have to push it down with a definitive motion.

This is a standard way to open/close (toggle) the side panels of browsers (e.g. Firefox).

**Comment by jkufner** [comment]
It took me while to discover how exactly it works too. I think there should be some visible hint. Maybe a small cross in corner to close the card.

**Comment by vshcherb** [comment]
There will be an icon to delete it as well.

**Comment by vshcherb** [comment]
Implemented
