### ISSUE TITLE
Red text in the current speed widget in "night" mode is illegible

### ISSUE THREAD

**Issue by mdykierek** [osmandapp/OsmAnd#21477]
### Description

The red color of the text in the current speed widget when the speed limit is exceeded is illegible when driving after dark.
Yellow, light orange would improve the situation. 

### Steps to reproduce

Drive after dark. It is worse on Android Auto than on the phone but the different is not significant. It is simply hard to read.

### Actual result

Red text, hard to read

### Expected result

Better color choice for higher contrast.

### Your Environment (required)

```
OsmAnd Version: 4.9.7
Android/iOS version: 14
Device model: Motorola Edge 40 Pro
Crash-Logs: ?
```

**Comment by mdykierek** [comment]
That is what I mean but now consider car's display, far right corner and the angle of view.
Yes - the car should show current speed... but still not very good from usability point of view.

**Comment by vshcherb** [comment]
To do specify variable in xml and pass to ui review

**Comment by 0xRe1nk0** [comment]
Speedometer exceed text color now is specified in [colors.xml](https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/res/values/colors.xml)

- speedometer_text_speed_exceed_day
- speedometer_text_speed_exceed_night
