### ISSUE TITLE
Support additional Intents (google.navigation)

### ISSUE THREAD

**Issue by ngt-github** [osmandapp/Osmand#2147]
Add the Intent "google.navigation:q=<address>".

An app using the Intent "google.navigation:q=<address>" is starting osmand, but osmand cannot recognize the address and doesn't parse it. It seems, only google.navigation:q=<lat>,<lon> is supported by OsmAnd. Some apps unfortunately don't provide a geo-intent so OsmAnd cannot be used for routing.
Following https://developers.google.com/maps/documentation/android-api/intents "geo" is for searching a location and "google.navigation" is to navigate to the given point or address. I believe OsmAnd should fully implement the "google.navigation" intent to ensure full interoperability with other apps.
Since OsmAnd can use "geo:0,0?q=<address>" it should be pretty easy to implement the additional Intent. Other routing-apps like here are working properly.

**Comment by sonora** [comment]
Should be fixed.

**Comment by ngt-github** [comment]
Thanks for taking care of this request! But unfortunately it is not fixed completely:

The Issue is still open. Osmand displays still an error "Ungültiges Format: q=Taronga Zoo, Sydney, Australia". Translated something like  "format exception".
It seems the Osmand implementation expects lat and lng to be set but not a search term like 
"google.navigation:q=Taronga+Zoo,+Sydney,+Australia"

Both formats are valid:
google.navigation:q=a+street,+address
google.navigation:q=latitude,longitude

I would try to split the part after Q= using ',' and then try to cast the result to double. If that fails, treat the whole thing as a string
