### ISSUE TITLE
Wrong coordinates interpretation from Instagram

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#2148]
When you open a location from Instagram using OsmAnd, it cuts the first symbol from the coordinates, thus, you get a completely different country.

Open location in Kyiv, Ukraine - receive Uganda.

![screenshot_2016-01-14-12-09-14](https://cloud.githubusercontent.com/assets/12711814/12321910/724b79e0-bab9-11e5-85b3-ebc61e2cc7fb.jpg)
![screenshot_2016-01-14-12-09-28](https://cloud.githubusercontent.com/assets/12711814/12321912/724ecfb4-bab9-11e5-9210-ffce08e8959b.jpg)
![screenshot_2016-01-14-12-10-12](https://cloud.githubusercontent.com/assets/12711814/12321911/724d7a1a-bab9-11e5-9659-a56c9b0e14fb.jpg)

**Comment by GaidamakUA** [comment]
Fixed by commit f5127caf519befe969788853c5b959c6fdc100f7
