### ISSUE TITLE
Detour in the bicycle profile

### ISSUE THREAD

**Issue by wolfwehl** [osmandapp/OsmAnd#21492]
### Routing engine

- [X] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

bike

### Start and end points

Germany, Heilbronn, "Neckartal-Radweg"
Position 1 49.1410402  9.1997077
Position 2 49.1604490  9.2045841

### Actual route

Between the both coordinates 
![Teststrecke](https://github.com/user-attachments/assets/851af804-97f5-4d5d-85d3-9102753c1e9b)
there is a straight main bicycle and footpath (bicyle = designated, foot = designated). Nevertheless, as can be seen in screenshot 1, OsmAnd suggests major detours. (The route in the pedestrian profile is also incorrect.)

### Expected route

As shown in screenshot 2, you have to set five intermediate points over a distance of 2.2 km to force OsmAnd to route the simple, straight route.
![Teststrecke 2](https://github.com/user-attachments/assets/bd85a253-9914-4679-8677-2ae119b09373)

### Maps you used (online or offline)

- [x] Offline maps offered within the OsmAnd app for download. <**edition date** of the map 11/01/2024>
- [ ] Online (tile / raster) maps 

### Your Environment

```
OsmAnd Version: 4.9.7 and all older versions, i used before
Android version: 14
Device model: Samsung Galaxy A53 5G

```

### Anything else?

Bike profile: If there is a cycle path parallel to and close to a road, OsmAnd regularly routes across the road and not the cycle path.

**Comment by vshcherb** [comment]
Cost 298 (https://osmand.net/map/navigate/?start=49.141071,9.199854&end=49.154994,9.203394&profile=bicycle#18/49.14347/9.19959) vs cost 307 (https://osmand.net/map/navigate/?start=49.141071,9.199854&end=49.154994,9.203394&avoid=2815689799&profile=bicycle#16/49.1507/9.2024)

**Comment by wolfwehl** [comment]
> Cost 298 (https://osmand.net/map/navigate/?start=49.141071,9.199854&end=49.154994,9.203394&profile=bicycle#18/49.14347/9.19959) vs cost 307 (https://osmand.net/map/navigate/?start=49.141071,9.199854&end=49.154994,9.203394&avoid=2815689799&profile=bicycle#16/49.1507/9.2024)

Unfortunately, I do not have enough experience to understand your brief commentary on my issue.

**Comment by xmd5a2** [comment]
Not reproducible on latest OSM data in OsmAndMapCreator (**driving_style_balance**) but reproducible with **driving_style_speed**
| driving_style_balance | driving_style_speed |
|--------|--------|
| ![Screenshot_2024-12-09_09-36-49](https://github.com/user-attachments/assets/7f4f5bf2-fe60-462a-99fc-96d7c3ca85ad) | ![Screenshot_2024-12-09_09-37-12](https://github.com/user-attachments/assets/c75a3d58-98f5-4b3b-af3d-09789b28254d) |

**Comment by vshcherb** [comment]
@xmd5a2 reproducible with web version https://osmand.net/map/navigate/?start=49.141071,9.199854&end=49.154994,9.203394&profile=bicycle#16/49.1454/9.1980. Needs to be investigated what;s the reason of costs difference for straight line. Which specific tag could cause it?

**Comment by xmd5a2** [comment]
Fixed by increasing speed for bicycle routes. No new maps required.

**Comment by Zirochkabila** [comment]
# Testing 1

By an inexplicable coincidence, the most anticipated route is in the iOS version - but changes to it have not yet been made 
@vshcherb @xmd5a2 We need a clear understanding of what the expected result should look like (distance, time, cost)

__________

**WEB** 
Expected result only in **OsmAnd Safety, Plains/OsmAnd Prefer, Plains** (4&5) but has different times 5 and 8 minutes

[OsmAnd Balance, Plains](https://osmand.net/map/navigate/?start=49.141040,9.199710&end=49.160450,9.204580&profile=bicycle#15/49.1520/9.2008)
[OsmAnd Speed, Plains](https://osmand.net/map/navigate/?start=49.141040,9.199710&end=49.160450,9.204580&profile=bicycle&params=bicycle,driving_style_balance:false,driving_style_speed#15/49.1520/9.2008)
[OsmAnd Safety, Plains](https://osmand.net/map/navigate/?start=49.141040,9.199710&end=49.160450,9.204580&profile=bicycle&params=bicycle,driving_style_safety,driving_style_balance:false#15/49.1520/9.2008)
[OsmAnd Prefer, Plains](https://osmand.net/map/navigate/?start=49.141040,9.199710&end=49.160450,9.204580&profile=bicycle&params=bicycle,driving_style_prefer_unpaved,driving_style_balance:false#15/49.1520/9.2008)
[OsmAnd Balance, Plains, Use elevation](https://osmand.net/map/navigate/?start=49.141040,9.199710&end=49.160450,9.204580&profile=bicycle&params=bicycle,height_obstacles#15/49.1520/9.2008)
[OsmAnd Balance, Plains, Short way](https://osmand.net/map/navigate/?start=49.141040,9.199710&end=49.160450,9.204580&profile=bicycle&params=bicycle,short_way#15/49.1520/9.2008)

<details><summary>WEB</summary>
<img width="800" alt="Screenshot 2023-01-31 at 11 19 41" src="https://github.com/user-attachments/assets/95988048-495e-427c-a72b-ec2fa9df8670">
<img width="800" alt="Screenshot 2023-01-31 at 11 19 41" src="https://github.com/user-attachments/assets/b403c536-f797-4138-9d68-ce63f76a1064">
<img width="800" alt="Screenshot 2023-01-31 at 11 19 41" src="https://github.com/user-attachments/assets/7fde5812-d81c-486d-bcee-fc6b45edbdb1">
<img width="800" alt="Screenshot 2023-01-31 at 11 19 41" src="https://github.com/user-attachments/assets/166a24ac-0956-4f4b-8e09-ebc550b016ee">
<img width="800" alt="Screenshot 2023-01-31 at 11 19 41" src="https://github.com/user-attachments/assets/da439f8f-b18a-400e-81b8-6f22cbf12e95">
<img width="800" alt="Screenshot 2023-01-31 at 11 19 41" src="https://github.com/user-attachments/assets/235da075-59e9-49d7-abcd-26ce0ade0ff2">
</details> 

____________________

**OsmAnd~ 5.0.0#4079m, Released: 2025-01-08**

Expected result in **Byways**, **Unpaved**, **Balanced**, **Use elevation**, **Balanced, Fastest route OFF** (3-6) but has different times 3, 5, 3, 5 minutes

<details><summary>Android</summary>
<table style="width:100%">
  <tr>
    <th>Balanced</th>
    <th>Shorter</th>
    <th>Byways</th>
    <th>Unpaved</th>
    <th>Balanced, Use elevation</th>
    <th>Balanced, Fastest route OFF</th>
  </tr>
  <tr>
<th><img src="https://github.com/user-attachments/assets/b4501605-2cba-4bf6-967f-a59eb62f7295"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/8e1d7ba9-777f-4bb9-89bf-aebcf1024ead"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/7fbf2d6c-896f-43fb-86f0-e8b16ebba439"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/6da0ac2b-a048-42eb-8ea9-b7e423f41eda  "  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/63f0fa42-74b9-40b2-b645-31a3a35b3184"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/25353668-2639-40ba-b7c7-d82619109209"  width="300" height="auto"/> </th>
  </tr>
</table>  
</details> 

________________________

**iOS 4.9.3.4936**


<details><summary>iOS</summary>
<img width="800" alt="Screenshot 2023-01-31 at 11 19 41" src="https://github.com/user-attachments/assets/3529c7e5-9d40-4ba5-853f-267e69f6dd3a">
<img width="800" alt="Screenshot 2023-01-31 at 11 19 41" src="https://github.com/user-attachments/assets/d2fdaa65-f4dc-4bd7-8e35-8074554b307b">
<img width="800" alt="Screenshot 2023-01-31 at 11 19 41" src="https://github.com/user-attachments/assets/0a975220-c299-42df-bc47-1c70f4fc744b">
<img width="800" alt="Screenshot 2023-01-31 at 11 19 41" src="https://github.com/user-attachments/assets/216294cb-0825-4266-b87d-49b579183133">
<img width="800" alt="Screenshot 2023-01-31 at 11 19 41" src="https://github.com/user-attachments/assets/8a41c8f6-9bbe-4405-bf1b-06266d5e8569">
<img width="800" alt="Screenshot 2023-01-31 at 11 19 41" src="https://github.com/user-attachments/assets/64073808-0bdb-4136-bbb2-c4ed30659fe0">
<img width="800" alt="Screenshot 2023-01-31 at 11 19 41" src="https://github.com/user-attachments/assets/982f9ea2-4b32-4330-8886-d29bc30d8369">
</details>

**Comment by xmd5a2** [comment]
I've increased speed for route_bicycle in balanced profile even more. iOS screenshots are not from this issue.

**Comment by Zirochkabila** [comment]
# Testing 2

**OsmAnd~ 5.0.0#4096m, Released: 2025-01-10**

@xmd5a2 All the changes seem to be only that now in the “Byways” and “Balanced, Fastest route OFF” options the route is not displayed in a straight line - that is, no positive changes are observed

<details><summary>Android</summary>
<table style="width:100%">
  <tr>
    <th>Byways</th>
    <th>Balanced, Fastest route OFF</th>
  </tr>
  <tr>
<th><img src="https://github.com/user-attachments/assets/9a291320-1581-4bc0-930c-2ddb485a3e9e"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/5f7fe695-d8c0-44e9-8de8-7b5ab9d895c5"  width="300" height="auto"/> </th>
  </tr>
</table>  
</details> 

________

**WEB** - No changes
**4.9.3.4937** - No changes
