### ISSUE TITLE
Unexpected detour in foot routing

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#21499]
### Routing engine

- [X] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

🦶

### Start and end points

51.062233 13.770716
51.059593 13.762407

### Route

| Actual Route | Expected Route |
| ------------- | ------------- |
| <img src="https://github.com/user-attachments/assets/cbdccae2-cdc7-4b1d-b7d8-019c8fbdfb6c"  width="300" height="auto"/> | <img src="https://github.com/user-attachments/assets/4f877440-945d-4928-8fe4-53640fae610b"  width="300" height="auto"/> |

Actual route:
https://osmand.net/map?start=51.062233%2C13.770716&end=51.059593%2C13.762407&profile=pedestrian#16/51.061600/13.766557
Expected route:
https://osmand.net/map?start=51.062233%2C13.770716&via=51.061623%2C13.768012%3B51.060337%2C13.764072&end=51.059593%2C13.762407&profile=pedestrian#16/51.061668/13.766755

### Maps you used (online or offline)

- [X] Offline maps offered within the OsmAnd app for download. 
- [ ] Online (tile / raster) maps 

### Your Environment

```
OsmAnd Version: 4.9.8
Android version: 13
Device model: Fairphone 4
```

**Comment by scaidermern** [comment]
Same behavior here:

https://osmand.net/map?start=51.058243%2C13.736876&end=51.061459%2C13.734304&profile=pedestrian#17/51.060711/13.735767

![Screenshot_20241130-214726](https://github.com/user-attachments/assets/24d330f4-899c-4aac-8381-f4c2ef6c7bda)

**Comment by xmd5a2** [comment]
Reproducible in OsmAndMapCreator
![Screenshot_2024-12-09_09-51-06](https://github.com/user-attachments/assets/90c1551c-9166-4fe5-bf6f-6fcc00cc948c)
but increasing priority for  **foot=designated** from 1 to 1.1 fixes this case.

**Comment by xmd5a2** [comment]
Fixed. No new maps required.

**Comment by Zirochkabila** [comment]
# Testing 1
`OsmAnd~ 5.0.0#4079m, Released: 2025-01-08` - Fixed
`Web` - Fixed
`iOS` - Waiting

<img width="515" alt="Screenshot 2025-01-08 at 14 58 42" src="https://github.com/user-attachments/assets/cb650274-2648-4c3e-aa03-cff4bc5cb988" />
