### ISSUE TITLE
Crash when tapping on image

### ISSUE THREAD

**Issue by uegert** [osmandapp/OsmAnd#21500]
### Description

I've send a couple of crash reports from Osmand directly, but that doesn't seem to create a reaction. So here it comes again. 
The issue: Online images linked from various servers I tested show as 1 larger and several smaller tiles. A tap on the large tile causes Osmand to crash reliably. This does seem to depend on wether the image is linked via the image=* tag or wikimedia_commons=Category:* or wikimedia_commons=File:*. 
If I use "show all" if there are several, all images can be tapped on, including the one that caused the crash when tapped on. 

On the other hand, in v. 4.9.8 4908 wikimedia_commons=Category:* does not work reliably for me, which may or may not be connected to the above issue. This is shown in the last example in the "Steps to reproduce" section.

Note that I did clear the Osmand cache and did not use stored POIs but searched freshly for each item (see below).

### Steps to reproduce

Search for "Dorerbühl-Hütte" (for example) - here the **large tile shows the image= tag. The small tiles the wikimedia_commons=Category:** entry
Scroll to "Online-Photos" 
Tap on the large tile -> crash

Search for "Rödskojan" (for example) - here the **large tile shows the image= tag. The small tiles the wikimedia_commons=File:** entry
Scroll to "Online-Photos" 
Tap on the large tile -> crash

Search for "Langeckhütte Waldkirch" (for example) - here the **large tile shows the image= tag. No wikimedia_commons entry**
Scroll to "Online-Photos" 
Tap on the large tile -> crash

Search for coordinates 57.6698083, 12.0393803 (https://www.openstreetmap.org/node/11104158547)
It has an entry **Wikimedia_commons=File:Norra Långevattnets vindskydd.jpg**. **No tag image=** 
Scroll to "Online-Photos" 
Tap on the large tile. **The image pops up, NO** crash

Search for coordinates 57,7650048, 12,1039923 (https://www.openstreetmap.org/#map=18/57.7650048/12.1039923), that is a shelter northeast of Flatevattnet.
It has an entry to **Wikimedia_commons=Category:Flatevattnet vindskydd with 2 images**. **No tag image=** 
(https://commons.wikimedia.org/wiki/Category:Flatevattnet%20vindskydd?uselang=en)
**Neither image is shown in Osmand.**

### Actual result

Osmand crashes (see description above)

### Expected result

pop up of the picture tapped. No crash, of course.

### Your Environment (required)

Device : beyond0q
Brand : samsung
Model : SM-G970U
Product : beyond0qltesq
Build : SP1A.210812.016.G970USQU9IXE3
Version : 12
App Version : OsmAnd+
Apk Version : 4.9.8 4908

example log
[exception.log](https://github.com/user-attachments/files/17968513/exception.log)

**Comment by Zirochkabila** [comment]
`OsmAnd~ 5.0.0#3862m, Released: 2024-12-02`
Fixed
