### ISSUE TITLE
Dirt Bike Routes Not Showing

### ISSUE THREAD

**Issue by Busterama452** [osmandapp/OsmAnd#21513]
### Description

I'm on android version 4.9.7 and dirt bike routes are not showing in this area.
 
https://www.openstreetmap.org/#map=15/31.61710/-111.14312

There are paths tagged for Mountain Bikes and dirt bikes.  Toggling mountain bike routes works, but the dirt bike routes feature does not work.

### Steps to reproduce

Go to coordinates 31.61710,-111.14312 on the map.

Open "Configure Map" and turn on Dirt Bike Routes

### Actual result

No change happens to the map.

### Expected result

Dirt bike routes should be highlighted with the newly implemented render styles to emphasize them over the surrounding features.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.9.7
Android/iOS version: 14
Device model: Samsung S22+
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
To reproduce:

1. Navigate to these coordinates: [31.6087, -111.1325](https://osmand.net/map/search/#13/31.6087/-111.1325).
2. Ensure the appropriate map for this area is downloaded.
3. Open the **Menu** > **Configure Screen** > Turn on **Dirt Bike Trails**.

### Observed Behavior:
Dirt bike trails do not appear on the map as expected.

### Likely Cause:
This may be related to the `dirtbike:scale` tag used in this area. Based on the OpenStreetMap data, these routes are tagged with `dirtbike:scale?`, and the question mark might be causing an issue with rendering. It seems that OsmAnd does not recognize or render trails tagged this way.

OsmAnd~ 5.0.0#3926m, released: 2024-12-11

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/f7591ed5-8d49-4beb-a646-e95d82ccaf73"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Busterama452** [comment]
dirtbike:scale=? is a valid tag valud for dirtbike routes according openstreetmaps wiki.  Probably just need to add another line style for that value.

**Comment by vshcherb** [comment]
We support only specific values however ```?``` https://www.openstreetmap.org/way/1131443775 is questionable how to suport

**Comment by cmoffroad** [comment]
> We support only specific values however `?` https://www.openstreetmap.org/way/1131443775 is questionable how to suport

The `dirtbike:scale=?` tag is already supported by the OBF creation [[process](https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml#L3023)](https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml#L3023), so it's just a matter of rendering it.

I've submitted a proposal to render those values in silver color:  
https://github.com/osmandapp/OsmAnd/issues/21611
