### ISSUE TITLE
Flickering POIs and road shields when Terrain 3D enabled

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd#21512]
### Description

POI icons and road shields flicker during navigation in navigation mode when Terrain 3d enabled
It might be related with https://github.com/osmandapp/OsmAnd/issues/21288

### Steps to reproduce

- enable 3d relief (configure map > topography > 3d relief) and download Belarus Terrain map (3d)
- simulate navigation from 53.94428 27.68287 to 53.94256 27.67871

### Actual result

POIs and road shields flicker during navigation

https://github.com/user-attachments/assets/5a41e93c-03fe-4c5d-9626-27fe526912a9

### Expected result

- [ ] POI labels, road shields, street names don't flicker

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd~ 5.0.0#3869m, released: 2024-12-03
Android/iOS version: 13
Device model: samsung galaxy note 20 ultra
Crash-Logs: ?
```

**Comment by Zirochkabila** [comment]
`OsmAnd~ 5.0.0#3888m, Released: 2024-12-05`
Done
