### ISSUE TITLE
Long tap track move (Configure map)

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#21531]
### Description

Cannot move a group of selected tracks to another folder

> Menu > My Places > Tracks > Open any folder > Long press > Select two or three tracks > Three dots > Move > Movement takes place - **Right behavior**

### Steps to reproduce

Configure map > Tracks > Chose any folder with tracks > Select two or three tracks in checkboxes > Long press on any of the selected tracks > Move > Chose Folder > **Only the track that was long pressed is moved**

### Actual result

https://github.com/user-attachments/assets/a942b23d-769c-4e5a-9f00-ca3c19927f20

### Expected result

- [ ] All selected tracks are moved (as it is implemented in My Places)

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd~ 5.0.0#3888m, Released: 2024-12-05
Android/iOS version: Android 14
Device model:
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced successfully using the steps you provided:  
1. Navigate to **Configure Map > Tracks**.  
2. Open a folder with tracks.  
3. Select multiple tracks using checkboxes.  
4. Long press on any of the selected tracks.  
5. Tap "Move" and select a destination folder.  

**Actual Result:** Only the long-pressed track gets moved.  
**Expected Result:** All selected tracks should be moved, similar to the behavior in **My Places > Tracks**.  

OsmAnd~ 5.0.0#3908m, released: 2024-12-09

https://github.com/user-attachments/assets/7b582368-c6e0-4b67-9a40-52533fc581f5

**Comment by vshcherb** [comment]
Long tap is applicable to 1 track action. it shouldn't be confused with selection mode which is not present here @
