### ISSUE TITLE
Clicking on row in Route Settings produces wrong selection

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#2153]
https://www.dropbox.com/s/5mohb1gyhtejnjr/2016-01-15%2009.20.28.png?dl=0

**Comment by vshcherb** [comment]
Clicking on row in Route Settings produces wrong selection instead of row click item

**Comment by vshcherb** [comment]
Another issue https://www.dropbox.com/s/3hebw3rofsueywe/2016-01-15%2009.22.22.png?dl=0 (should be 2 lines not 1)

**Comment by sonora** [comment]
Really? Cannot reproduce here (Issue 1). What do you mean? Things like "Avoid motorways" works for me, just tested...

**Comment by vshcherb** [comment]
Fixed already
