### ISSUE TITLE
Maps scaled and totally unreadable AA

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#21536]
1. Source - online maps tile (to easier spot discrepencies)
2. Map magnifier - 100%
3. Resolution resolution = 1280x720, dpi = 160 (dpi=160 corresponds to pixel perfect tile size 256)

- [ ] Result totally blurred and not correct.

<img width="1272" alt="Screenshot 2024-12-06 at 11 37 53" src="https://github.com/user-attachments/assets/043d8e55-0da3-4089-bf4f-208217810ded">

Observation:
Default zoom widget converts from 16 +0 (on device) to 16 -1.22 once AA connected

Broken API:
- [ ] https://github.com/osmandapp/Osmand/blob/a439a2cccfd613f69977983a53e62ed5f9f2bd68/OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java#L1750  (running animation to 17 - 0.1 results to zoom displayed in widget 17 -0.8) - Phone density 2.5. After it's fixed - commit should be revereted (https://github.com/osmandapp/OsmAnd/commit/b7fb2e68cc4f8e5d741baa0b2a28e8a667fc6dab#diff-92104a1cc11659420a8f29173965890c9b166711306b25b77efa061894495821R108)
```
//				tb.mapDensity = surfaceRenderer.density.toDouble() * app.settings.MAP_DENSITY.get();
				tb.mapDensity = surfaceRenderer.density.toDouble() * app.osmandMap.mapDensity;
```
- [ ] If phone zoom displayed 16 + 0.0 in zoom widget before connection to AA, it rewrites to 16 -1.2 which causes blurry image

**Comment by alex-osm** [comment]
Car density coef has been dropped from getMapDensity. But getCarDensityScaleCoef is still used for getTextScale, otherwise map icons become too large.  https://github.com/osmandapp/OsmAnd/commit/6bb3982c6325b43148f315a95d314b6db4ef6012

Needs to be tested.

**Comment by vshcherb** [comment]
- [ ] 2 Navigation icons
- [ ] Navigation icon + Favorites are too big
- [ ] Navigation line is too thick
- [ ] Map is fixed, however line changing from high density tiles to low density tiles appears below expected (comparing to the phone) on AA

**Comment by Zirochkabila** [comment]
`OsmAnd~ 5.0.0#3925m, Released: 2024-12-11`

It seems that this is due to the zoom level (at different zoom levels, the icons are displayed differently) and the fact that two icons are displayed

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/7d5911c8-f620-4022-a915-f426ce91978b"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/46bc8957-10cc-4a7d-9c0a-aa43cbd2c211"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/commit/255e3ac123681284c82b0751d0028bdf3ed83c47

**Comment by Zirochkabila** [comment]
# Testing 1
`OsmAnd~ 5.0.0#3985m, Released: 2024-12-23` - Fixed
