### ISSUE TITLE
some POI categories messed up

### ISSUE THREAD

**Issue by VSCHULTE** [osmandapp/OsmAnd#21545]
### Description

When trying to show all poi with tag cafe or university on the map it only offers me empty subcategories (healthcare and leisure) with zero hits.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/5616ea84-19b6-4613-94cf-feb78459b56a"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/1cef5b7f-68b3-4ba6-a4b6-361146d19064"  width="300" height="auto"/> </th>
  </tr>
</table>

### Steps to reproduce

Tap on search,  select category, enter cafe or university

### Actual result

Only empty subcategories (healthcare and leisure) are shown

### Expected result

The main categories are shown

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.8.6
Android/iOS version: android 15
Device model: pixel 6a
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
We couldn’t reproduce the bug. Please follow these steps:

1. Open OsmAnd and tap the search option.
2. Select the POI category and enter "cafe" or "university."
3. The main categories should appear.

-Check the **Filter** function by selecting the category and tapping the filter icon below the input field. 
-Also, update the app to version 4.9.9.
-If the issue persists, back up your data via **Menu > Settings > Export to file** and reinstall the app. Let me know if this helps!

OsmAnd~ 5.0.0#3926m, released: 2024-12-11

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/5aa829dd-63e4-4393-879b-baa0f9c7d74b"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/12eb76e2-f4f2-4837-b23b-e4ba9d3907bb"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by VSCHULTE** [comment]
I installed the newest apk offered on the website.
Then the behaviour does not occur.
After importing my settings, the issue returns.

I'll play arround with that and import/recreate my settings step-by-step.
