### ISSUE TITLE
Resting position icon is combined with Navigation position icon (AA)

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#21552]
### Description

When displaying the location on the map, the two icons are combined (Resting position icon with Navigation position icon)
**It is very difficult to reproduce this on a smartphone (rare)**

### Steps to reproduce

1. Show your location on the map 
2. Navigation > Select point of destination > Wait (If first option doesn't work)

### Actual result

![2024-12-10 11 45 50](https://github.com/user-attachments/assets/e61969a7-edba-4449-b6ee-b1ce3c4a9c41)

### Expected result

- [ ] Different icons are displayed for different states (not combined)

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd~ 5.0.0#3918m, Released: 2024-12-10
Android/iOS version: Android 14
Device model:
Crash-Logs: ?
```

**Comment by vshcherb** [comment]
Duplicate
