### ISSUE TITLE
Change activity doesn't work

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#21553]
### How to reproduce
* Open **Menu** – **My Places** - **Tracks**
* Long tap on track to open **Selection mode**
* Select needed track – tap on 3 dot's menu – **Change activity**
* Select needed activity

### Actual result

<table style="width:100%">
  <tr>
    <th>Before change</th>
    <th>After change</th>
    <th>Video</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/0d4ed9df-fe01-4e78-bef0-32f8d02de4e6"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/78619b5f-056f-450a-a0fe-698d6764bcf5"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/user-attachments/assets/13fe665c-f794-444a-b930-f0934e73891a"  width="300" height="auto"/> </td>
  </tr>
</table>  

* Nothing happens visually 
* Track doesn't have activity 

### Expected result

* Apply selected activity
* Tracks uploaded to OSM without activity

**Environment**
OsmAnd Version: OsmAnd~ 5.0.0#3919m, released: 2024-12-10
Android: 15
Device model: Google Pixel 6A

**Comment by Zirochkabila** [comment]
# Testing 1
Fixed
`OsmAnd~ 5.0.0#3921m, Released: 2024-12-10`

1. Track activity changes even if the tracks are not displayed on the map.
2. The activity of tracks (that do not appear on the map) is displayed on OSM
3. For tracks that are displayed on the map, the result is the same
