### ISSUE TITLE
Wrong "Select destination" title

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#2155]
When no destination is set, tapping to "Select destination" produces incorrect first line of pop-up menu:
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot_2016-01-15-14-31-03.png
Tapping to "Select destination" line on screenshot leads to closing pop-up menu without any visible action. I propose to remove that line.

**Comment by sonora** [comment]
This is the default entry displayed in the spinner when nothing is selected ... would not know how to remove unless we decide to have no text displayed (which would be an even worse issue).

**Comment by crimean** [comment]
Fixed https://github.com/osmandapp/Osmand/commit/3b1b7e0e812b9acc850dc1aeb3a838d8fc7f4eff
