### ISSUE TITLE
OMC problems

### ISSUE THREAD

**Issue by mariush444** [osmandapp/OsmAnd#21569]
### Description

simple example for creating obf with OMC.
After creating obf I see that html tags in `<desc>` are not interpreted. Look at wpt named `html doesn't work 1` and `html doesn't work 2`
1 and 2 uses different method of tagging. Maybe this is intention that html tags shouldn't be interpreted  but:
- it is inconsistent with the fact as gpx file is interpreted in osmand (so why not in obf)
- tag `<p> `is somehow interpreted and brakes "next line". Compare `<desc>` in wpt named `enter OK` and `enter NOT OK`. After adding `<p>` to wpt `enter OK` the next line doesn't work.

Problem with colors. Let's assume that orange is "similar to orange" in wpt  `html doesn't work 2` but for sure wpt `enter NOT OK` is not light green but something like pink-red.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/5b94ded2-df3e-40f2-9fce-68a7b4cb738e"  width="300" height="auto"/> </td>
  </tr>
</table>

for colors I tried `<color>` and `<osmand:color>`. The same result

According to https://github.com/osmandapp/OsmAnd/issues/18866 I know that OMC is under development so this is to inform you. 

### Steps to reproduce

example gpx and created obf is attachet in zip
you can use my obf or create new one with command
`./utilities.sh convert-gpx-to-obf zzz.gpx  `
[zzz.zip](https://github.com/user-attachments/files/18141493/zzz.zip)

### Actual result

html is not interpreted.
colors are sometimes wrong

### Expected result

html should be interpreted properly as in gpx
OR should not be interpreted at all and then `<p> `shouldn't brake new line

colors should be as are coded

### Your Environment (required)

OsmAnd Version: 4.9.9.
Android/iOS version: 11
OMC: 3.0  - downloaded 13/12/24

**Comment by RZR-UA** [comment]
Hello, @mariush444 

The TravelGpx collection feature has been recently significantly updated.

A lot of TravelGpx features were added, including support for user-defined tags, configurable track colors, custom width, shields, better GPX file restoration from OBF collection, click-on-track (name, shield), grouping by activity type, and even searching by name and activity groups and types.

It will be slightly improved soon, including the light-green and orange background icons you just requested.

Supporting every color for the icon background is complicated because backgrounds are just a limited set of colored icons (shields).

The case with HTML in the description is planned to be implemented in another task: https://github.com/osmandapp/OsmAnd/issues/19787

**Comment by RZR-UA** [comment]
https://github.com/osmandapp/OsmAnd-resources/pull/1168

**Comment by RZR-UA** [comment]
Test resources (html, gpx, obf) for this issue:

[test-html-and-link.zip](https://github.com/user-attachments/files/18259669/test-html-and-link.zip)

**Comment by mariush444** [comment]
hmm.. I downloaded new OMC 27.12.24 with jar's created at 18:47 and I have different results with osmand 4.9.10.

Lost icon's shape (just stars instead archaelogical sites, bridge ....) - regression
![IMG-20241227-WA0002](https://github.com/user-attachments/assets/478aa866-1816-4705-af70-e208a55bb391)

example of WPT html  is:

![IMG-20241227-WA0003](https://github.com/user-attachments/assets/06b6a419-3883-4e26-a7fc-5e69d159b54d)
![IMG-20241227-WA0004](https://github.com/user-attachments/assets/0d36ec52-2890-4f00-9a53-017293c1f928)

result is regardless I tested your obf or mine.
Have you tested osmand 5.* ?
But anyway, icons shape is stepped back in 4.9.10

**Comment by RZR-UA** [comment]
@mariush444 please try the very fresh OsmAnd nightly build (5.0.0) to activate the latest features. We've simplified the tag schema for waypoints (gpx_bg -> background, gpx_icon -> icon), so you should update OsmAnd to test new features.

My screenshots:

<details><summary>Details</summary>
<p>

![a](https://github.com/user-attachments/assets/8635bac7-2c98-49c6-a250-b53a46485bbe)
![b](https://github.com/user-attachments/assets/0b2a51b5-3ebf-4357-b8ad-07f45cc4d363)
![c](https://github.com/user-attachments/assets/eafc6cc8-bacf-436f-b3f5-3d2dc1c10b3a)

With "square" background (limited colors supported):

![d](https://github.com/user-attachments/assets/31bb7b77-6608-446c-9a98-2eb810fcc823)

</p>
</details>

**Comment by mariush444** [comment]
that's what I assumed, I will test it later on, I have lost my test device :(

**Comment by mariush444** [comment]
It seems that it works OK but ...
1. Can you verify current OsmAndMapCreator.zip , please. It doesn't contain OsmAndMapCreator.**jar** 
2. Why some icons e.g military, bridge_structure_arch are black and others are white?

**Comment by RZR-UA** [comment]
@mariush444 

1. Just verified the very current OsmAndMapCreator-main.zip (07-Jan-2025 14:26 142611821 bytes) - it contains OsmAndMapCreator.jar and should work

2. Some rare icons are black (possibly old ones or designed to be used with some map styles), but others are primarily white-colored. In the case of using waypoints in OBF, the main complication is the limited supported colors of shields (background).

**Comment by Zirochkabila** [comment]
# Testing 1
`OsmAnd~ 5.0.0#4086m, Released: 2025-01-09` - Fixed 
[test-html-and-link.zip.zip](https://github.com/user-attachments/files/18361139/test-html-and-link.zip.zip)

**Comment by mariush444** [comment]
Can you try to use `open track` button?
![opentrack](https://github.com/user-attachments/assets/7fbd36aa-4994-41db-8bf4-92057866399f)

**Comment by Zirochkabila** [comment]
@mariush444 **Open Track** button is working


https://github.com/user-attachments/assets/088542b3-bfc0-4c86-89d9-cfbc9052a523

**Comment by mariush444** [comment]
hmmm.... 
I tried `testtravel.obf` with `OsmAnd~ 5.0.0#4097` and `open track` didn't work.
No idea what is going on. Android 11?

https://github.com/user-attachments/assets/b8edb23a-56ad-4197-9c01-e671eef2499c

**Comment by RZR-UA** [comment]
@mariush444, could you share your `logcat` (Menu - Help - Send logcat log)? Additionally, please share the screenshot with the name and location of `test.travel.obf`. You can try to save this obf file into `files/` or `files/travel/` folder in the main OsmAnd folder. Finally, the file name matters: it should contain `.travel.obf`.

**Comment by mariush444** [comment]
I just got your obf from [test-html-and-link.zip.zip](https://github.com/user-attachments/files/18361139/test-html-and-link.zip.zip) and I didn't know that obf should be renamed to `test.travel.obf`

so you solved my problem :)

**Comment by mariush444** [comment]
what should be used for `next line /new line` in osm file?
I tried: `&#10;`  `&#13;&#10;` `\n` `&lt;br&gt;` but nothing works.

The "hard" next line at `lat='47.23393' lon='-1.54657'` it is close to work but it is not perfect.
![enter](https://github.com/user-attachments/assets/42500a9d-7c41-4eb4-893e-020dbda8b067)

I used command `./utilities.sh generate-obf fr-fuel.osm`   

files are attached
[fuel.zip](https://github.com/user-attachments/files/18431081/fuel.zip)

**Comment by RZR-UA** [comment]
@mariush444, HTML support for usual OSM files (Amenity objects) is slightly out of the original topic of this Issue. We've implemented support for HTML-code in Description in GPX-in-OBF files (AKA TravelGpx).

Currently, there is no option to display a new line in Amenity descriptions.

You can remove whitespace gap just by removing leading spaces, for example:

```
                  <tag k='description' v='Gazole: 1.729€ (2025-01-14 12:39:5)
E85: 0.809€ (2024-10-14 14:40:1)
E10: 1.769€ (2025-01-14 12:39:5)
SP98: 1.849€ (2025-01-14 12:39:5)'/>
```
