### ISSUE TITLE
Osmand seems to ignore oneway:conditional

### ISSUE THREAD

**Issue by Peter0** [osmandapp/OsmAnd#21560]
### Routing engine

- [X] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Car; any options like freshly installed.

### Start and end points

Start: 50.73632 7.09409
Dest.: 50.73623 7.09259
Via Way #4365495

### Actual route

Osmands avoids Way #4365495

### Expected route

Expected route via Ways #171842119, #4365495, and #33322755.

### Maps you used (online or offline)

- [×] Offline maps offered within the OsmAnd app for download.  Normal (detailed) map for DE, NRW, Reg.Bez. Cologne, Ed. 2024-12-01
- Hourly live updates
- [ ] Online (tile / raster) maps 

### Your Environment

```
OsmAnd Version: ~4.9.7
Android version: /e/OS 2.5 /Android 13
Device model: Pixel 5

```

### Anything else?

Note that there is a oneway=yes tag, overriden by oneway:conditional=-1 @ (2024 jan 1 - 2025 mar 31).
Using other carefully choosen start points reveals that Osmand respects the non-overridden plain oneway-tag.
Omiting this pair of tags and using simple oneway=-1 instead lets Osmand do the routing like desired.

Issue #19549 is known.

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced.  

### **Steps to Reproduce:**  
1. Select the **Car** profile.  
2. Build a route:  
   - **Start:** `50.73632, 7.09409`  
   - **Destination:** `50.73623, 7.09259`.  

### **Result:**  
OsmAnd ignores the `turn:lanes:conditional` (`left;through;right|none|none @ (2024 jan 1 - 2025 mar 31)`) and incorrectly routes through this section.  

### **Expected:**  
The route should follow the restriction, as seen on Google Maps.  

### **References:**  
- OSM Link: [Way #4365495](https://www.openstreetmap.org/way/4365497)
- OsmAnd Web [OsmAnd Web](https://test.osmand.net/map/navigate/?start=50.736320,7.094090&end=50.736230,7.092590&profile=car#18/50.73625/7.09242)  
- Google Maps Reference: [Google Maps](https://www.google.com/maps/dir/50.73632,+7.09409/50.73623,+7.09259/@50.7362365,7.0907132,17z/data=!3m1!4b1!4m10!4m9!1m3!2m2!1d7.09409!2d50.73632!1m3!2m2!1d7.09259!2d50.73623!3e0!5m1!1e2?entry=ttu&g_ep=EgoyMDI0MTIxMS4wIKXMDSoASAFQAw%3D%3D).  



<table style="width:100%">
  </tr>
  <tr>
    <th>Web</th>
    <th>OSM</th>
    <th>Google maps/th>
  </tr>
  <tr>
<th><img src="https://github.com/user-attachments/assets/be03d960-6188-48a8-8e9b-324eb3ab9413"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/da5cc242-6b56-4077-aa73-357018edb853"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/b3a8e880-561e-4af2-81c7-d7692f535a76"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
```turn:lanes:conditional``` doesn't affect the routing .
As ```oneway:conditional=-1 @ (2024 jan 1 - 2025 mar 31)```, it was probably incorrect and supposed to be oneway:...=0

**Comment by vshcherb** [comment]
It's quite confusing actually the idea, probably you can attach small osm file so it could be tested. In current osm data / routing I don't see anything weird

**Comment by Peter0** [comment]
A similar problem exists with way https://www.openstreetmap.org/way/84507638 
It has tags
oneway=yes
oneway:conditional=no @ 2025
And here, Osmand also seems to ignore the conditional tag. Note that the tags are freshly made. They are only visible in live data, but not in the February map data.
