### ISSUE TITLE
Functional Issues with our downloaded regions layer

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2156]
While Issue #2152 refers to our download maps screens, this Issue refers to how we indicate the download status of regular maps by dyeing them on the map at zooms 4-6:

(1) Without Internet connection, all activated maps are always reported as uptodate, while their update status is actually "unknown".

(2) Without Internet connection, deactivated maps are not indicated at all

(3) But with Internet connection, deactivated maps are suddenly reported also (at least after the All downloads list was refreshed), but are always reported as outdated, even if they are uptodate.

(4) There are maps which we changed or which do not exist anymore. Examples are Mexico_centralamerica (is now Mexico_northamerica), or Italy, or Africa (we now only offer Region_italy, or Country_africa). Whoever still has these maps: They are always reported as uptodate, while their "true" status is actually "not found/identified on server at all".

These points (particularly (3) and (4) triggered this issue, surprisingly), confuse some users because they think they have maps ready, which they actually cannot use (deactivated ones, (3)), or do not see maps which are actually indexed ok and are usable (4). Then they find they cannot rely on the whole DownloadedRegionsLayer at all (1+2).

We either need to
(A) Fix what we actually wanted to achieve by color-coding the regions here, i.e. consistently show all a regions, and also consistently indicate when regions are deactivated, and when their update status is unknown
(B) or we should strictly simplify all this to a "coverage only" functionality, by simply only showing all actually indexed standard maps here, regardless of their update status. (Maybe or not indicate deactivated ones in a second color).

For now I am leaning towards (B), because
- having many different overlay shading colors on the map screen (we already have uptodate, selected, being-downloaded, and now would also need unknown, deactivated, and possible combinations of all these) is extremely confusng and not helpful. We have no good legend either.
- Plus: Detailed status requires looking at more map types like Wikipedia etc. anyway, which we cannot code here.
- Plus: Maps get outdated within days (because we update regularly), so for the majority of users who have many countries present, they are all shown outdated most of the time, so color-coding for them this is not very useful information. (Most will use this layer only to see what they have and what not, and to select new regions for download).
- And for those who are interested in their update status on a day-2-day basis, they will probably use our new OSM Live mechanism anyway, and check status on that screen.

**Comment by vshcherb** [comment]
I possibly agree with arguments here, because I don't have strong feeling here. I don't really use color coding here so I can live without it at all. So please propose your simplification, cause I didn't really get this simplification from the big list, i.e. "how it should look like " or "what shall we change"

**Comment by sonora** [comment]
Apologies, looks like sometimes I get carried away describing what is wrong, rather than clearly stating how to fix it.  :-)

Here is my recommendation: Let us simplify the Downloaded Regions Layer in this fashion:
- One color (green) shows if a standard map for a region is correctly indexed (i.e. in the activated indexes)
- A second color (orange) shows if there is a standard map present on the device for a region, but "deactivated".

As a result, this layer will only display map coverage by standard map files present on the device. No statement is made here if any map is updatable, up-to-date, etc.

Consequently
- Tapping on a not-shaded area will trigger a "Download" button on the area's card
- Tapping on an orange area will produce an "Activate" button on the area's card
- Tapping on a green area will produce an "Update" button on the area's card.

**Comment by vshcherb** [comment]
I think it makes sense

**Comment by sonora** [comment]
For now, headline icons have the same color if you do not have a map from that category at all (like I have none from Africa), of if you only have maps from 2 categories below (like Europe has the same icon color on my "All Downloads" screen, no indication hat I have maps of German states).  any chance we introduce some gray or something to better depict the difference here?
