### ISSUE TITLE
Geometry duplication in live update

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#21561]
### Description

After making changes to the road geometry in the OSM, a doubling of the geometry is observed in the Osmand.
Roads that doubled:
https://www.openstreetmap.org/way/862777724
https://www.openstreetmap.org/way/1263010449
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/6b59bd78-b2ab-4ec8-a74a-9d1f2765310c"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Steps to reproduce

-

### Actual result

incorrect road geometry.

### Expected result

correct road geometry.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd~ 5.0.0#3921m, Дата выпуска: 2024-12-10
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
The bug has been **reproduced** using the following steps:  
1. Locate the coordinates of the roads provided:  
   - [Way 862777724](https://www.openstreetmap.org/way/862777724).
   - [Way 1263010449](https://www.openstreetmap.org/way/1263010449).  
2. Load the map and view the road segments — initially, they appear **correct** as per OpenStreetMap data.  
3. Enable **Live Updates** and check the geometry of the updated roads.  

**Actual Result:** The road geometry appears duplicated in OsmAnd.  
**Expected Result:** The road geometry should match the updated OpenStreetMap data.  


OsmAnd~ 5.0.0#3944m, released: 2024-12-17

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/d0d560d7-ee3e-4cd6-8b55-2ac975524967"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/9123831c-5bb3-4ddb-990d-224001d08eaa"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by ivanPyrohivskyi** [comment]
Fixed for future live-updates. Nothing to test.

**Comment by Zirochkabila** [comment]
`55.69829° N, 37.34792° E`

<img width="515" alt="Screenshot 2024-12-23 at 17 36 44" src="https://github.com/user-attachments/assets/99030d84-cb0d-4b5e-8189-f0d890bd17b2" />
