### ISSUE TITLE
Route tearing

### ISSUE THREAD

**Issue by liphistius** [osmandapp/Osmand#2157]
Steps to reproduce:
1) Establish route between two locations
2) Examine turns to find tears in the highlighted route.

Device: Redmi Note 2
Chipset: Mediatek MT6795 Helio X10
CPU: Octa-core 2.0 GHz Cortex-A53
OS: MIUI 7

Thank you for your time!

![photo_2016-01-16_12-04-11](https://cloud.githubusercontent.com/assets/16261334/12371844/f48a5926-bc49-11e5-8430-28e77b8537cc.jpg)
![photo_2016-01-16_12-04-16](https://cloud.githubusercontent.com/assets/16261334/12371845/f6f0d83e-bc49-11e5-88b0-7d880e71fd10.jpg)

**Comment by xmd5a2** [comment]
Duplicate https://github.com/osmandapp/Osmand/issues/2035
