### ISSUE TITLE
More natural handling of the POI/Favorite along the route

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2159]
When we are navigating along a route, OsmAnd can (optionally) display the POIs/Favorites along that route. Let's call it the "POI/Favorite card" for the sake of this discussion.

This card only allows the user to dismiss the next suggested place. 

But what if we want to accept the suggestion and stop over at that point? There is no such provision.

**_Desired:**_ 
Let the user tap on the left side of the card (area that displays (a) the icon of the place, (b) the distance+offset and (c) the name of the place.)

Immediately, OsmAnd should add that point to the route, and recalculate the route.

---

The  **_overflow**_ button in the card is meant to be used while the user is driving. But this is not useful at all: If he taps this button, he is presented with a bewildering list of destinations, POIs and Favorites. Clearly, he cannot deal with the complexity while driving. So why is this quick control provided??

If he pulls aside his car, he can simply go back to the **_Waypoints**_ dialog in just two steps: First he taps on the blue arrowhead, and then the white triangular flag button. Now he can see all the POIs/Favorite settings.

**Comment by vshcherb** [comment]
I agree nice suggestion.

**Comment by vshcherb** [comment]
Let's add to 3 points context menu navigate to (add as first waypoint) and show the list

**Comment by raindropsfromsky** [comment]
Yes, the context menu requires affirmative action, so it ensures that an accidental tap on the card does not automatically add it to the route. (Once added, the user cannot remove it easily, especially while he is driving).

**Comment by sonora** [comment]
Please note that this is logically very close to suggestion #1862 (only there not with respect to a route, but with respect to your position alone)). In m mind such a "map discoverability" feature s one of OsmAnd's big business opportunities, developing our app to some sort of electronic tour guide, facilitating e.g live discovery of POIs along a route (e.g. on a tourist walking tour through a city, where your decide if what you want to see next is rather a cathedral, or a pub for lunch).  :-)

**Comment by vshcherb** [comment]
Yes I remember #1862 and immediately made mental connection. I also have couple examples where closest poi would be great.

**Comment by sonora** [comment]
Quick implementation would be having a button "Show nearby POI", which would put you on the existing Search/POI/categories screen. (Very similar to the already existing "Search near hear" menu option, which puts you on the Search screen also, but does not force the "POI" tab there).

While this new "Show nearby POI" option may actually be worth a button of its own, a menu item under "3-dots" may suffice?

**Comment by raindropsfromsky** [comment]
Well, the context of route makes the situation radically different!

When we drive along a route, we are looking for POIs contained in a narrow corridor on either side of it. That means the POIs are presented to us in a certain order (there is no randomness at all). In fact, city roads do not allow lingering and stopping, and so we pass by the POIs rather fast. Thus we have to decide fast, in real time. Finally, the core idea is to alter the route to accommodate the POI.

None of these factors apply when a tourist is discovering POIs in a neighborhood (most probably on foot). There is no route, so the scope of search is much wider (not restricted along the route). There is no pressure to drive on. So the tourist can go anywhere, according to what catches his fancy. 

But the question is, do we really need a dedicated button for this? The tourist can find all nearby POIs in just three taps (search -> Select POI type -> Show all on map). On the other hand, the dedicated button cannot predict as to which types of POIs he wants to see (or all). Thus more taps are inevitable. In that case, why not use the existing feature?

**Comment by sonora** [comment]
Just to answer the questions raised:
- "Dedicated button" (or at least "Nearby POIs" menu entry): I have watched so many users not being aware (a) we have a "Search near here" function hidden behind the 3-dots menu, and (b) not hitting on the idea they could use it to suggest Nearby POIs by using it, then navigate to the Search/POI tab, then specify what they need. So my answer leans towards "Yes"  :-)
- From my observations, most people would not want to see ALL nearby POIs, but a certain type only, so the "Nearby POIs" (or maybe "Discover") button I suggest would have to lead people to our (existing) Search POI tab, where they can then make their own POI category selection.
- Structurally, I think this functionality it is not much different whether look near/along a (2D) route, or just use the very similar "discover" functionality near a "1D-route", your static position.  :-)

**Comment by raindropsfromsky** [comment]
But the very point is, why have this dedicated function at all, when the generic search itself can do the exact same thing, with the same number of taps? 

In fact, what we need is a ***Search*** (magnifying glass) button directly on the screen. (Let there be a option in the ***Configure Screen*** screen to show/hide this button.)

Currently the search button is put in a very obscure place (item#4 in the ***Drawer*** menu).

**Comment by raindropsfromsky** [comment]
So, in my imagined scenario, the user taps the ***Magnifying glass*** button, and gets the usual 5-tabbed ***Search*** screen. But by default, open the ***POI*** tab, which prompts him to select a particular type of POI.

Another improvement is to place the "Nearest POI" option to the top of the POI list. This makes a new user aware that such an option exists. (A user is more likely to look for all types of POIs; NOT any particular type of POI.)

**Comment by raindropsfromsky** [comment]
To sum up, the search function should behave differently in ***Browse*** mode and ***Navigation*** mode, as described below:

 1 Remove the ***POI*** and ***Favorites*** sections from the ***Route Editor*** screen.</br> &nbsp;&nbsp; Instead of that, provide a ***POIs on route*** button on the screen (Navigation mode only).</br> &nbsp;&nbsp; But do not allow user to edit the POI list (by closing some POIs).</br> &nbsp;&nbsp; Directly start showing the "Next upcoming POI" cards.

 2 If the user taps on a "Next upcoming POI" card, add that POI to the route, and re-calculate the route.

 3 If the user taps the ***POIs on route*** button again, toggle the feature off.</br> &nbsp;&nbsp; (Stop displaying the "Next upcoming POI" cards).

 4 In ***Browse*** mode, add a ***Search*** button directly on screen.</br> &nbsp;&nbsp; Change the POI screen as described above.

**Comment by sonora** [comment]
Let us consider in connection #2765.
