### ISSUE TITLE
Options to choose location sources - GPS vs network

### ISSUE THREAD

**Issue by nhan000** [osmandapp/OsmAnd#21608]
### Describe the idea

Location coordinates can be obtained from GNSS or internet connection. I'd like to be able to choose between these sources.

### Expected behaviour

I'd to like to be able to choose the location sources, whether it's from GNSS, internet connection, other apps, or a combination of these sources (please see the Context below).

### Alternatives you've considered

Turn wifi off, mobile data on and off manually, which can be tedious.

### Context

[GPSLogger](https://gpslogger.app/) allows to choose whether to fetch the location coordinates from GNSS satellites or internet connection. Their recommended settings is to [use satellites exclusively](https://gpslogger.app/#arethereanyrecommendedsettings).

Here's the toggles in GPSLogger.

![share_2220378532167391365](https://github.com/user-attachments/assets/50bf60fe-53d1-4385-bcd2-f7942536fdc8)

**Comment by vshcherb** [comment]
It's implemented with accuracy set not specified. All location will be recorded

**Comment by nhan000** [comment]
What settings do I need to choose if I want to obtain location data exclusively from GNSS (not from internet connection even when I'm connected to the internet)?

**Comment by vshcherb** [comment]
There is no such setting, but if you set accuracy to 10m you won't get internet connection as it won't pass the threshold
