### ISSUE TITLE
OsmAnd 2.2.4 (Free, Google Playstore) and OsmAnd+ 2.3.0 (Nightly) can not be installed both

### ISSUE THREAD

**Issue by CJTmmr** [osmandapp/Osmand#2161]
With PlayStore version 2.1.* is was possible to have both OsmAnd Free 2.1 and Osmand+ 2.2.* installed.

OsmAnd Free from PlayStore could be installed next to OsmAnd+ from nightly's (*OsmAnd-nightly.apk* from http://download.osmand.net/latest-night-build)

or

OsmAnd+ from PlayStore could co-exist next to OsmAnd Free from nightly's (*OsmAnd-default.apk*)

Both OsmAnds could share the maps on SD-card (on Android 4.3)

After PlayStore update to OsmAnd 2.2.* it is no longer possible to install the other OsmAnd 2.3.*

When I wanted to upgrade the release version to 2.2. That failed for "unknown reason".
I uninstalled the nightly version and the release version could then be upgraded.
Now I try to install nightly again and it fails with a reason "not installed".
The error is "double provider authentiation " ( if I translate correct.. in Dutch: * Dubbele providervertificatie*)

What's up?

See also forum-thread: https://groups.google.com/forum/#!topic/osmand/Mu8i4t-XgEI

Somehow Free and + do have the same "manifest"?

**Comment by vshcherb** [comment]
That's known issue. Nighlies can not be used any more with released versions. We didn't find a solution yet, but we don't really want to sign nightlies with release certificate. So far it is advised to use only nightlies or only release versions

**Comment by aceman444** [comment]
That's bad, it means we can no longer test the nightlies (if we want to keep release version around).

**Comment by jkufner** [comment]
There is simple solution: When stable release is created, make nightly build of the same version and keep it around. Then user of nightly builds can have both stable release and nightly build. Only complication is that to switch between nightly and stable Osmand must be reinstalled, but that is easy when you have both APKs on SD card.

**Comment by vshcherb** [comment]
We are going to create new packages net.osmand.dev and net.osmand.plus.dev soon

**Comment by aceman444** [comment]
So that should allow to have full paid version and also a nightly of the full version?

**Comment by vshcherb** [comment]
This is not decided yet, possibly yes, but for some developers including me, it will cause some issues, and we are testing this approach still. Today nightly free, release free, release paid could be installed at the same time and majority of people uses nightly free + release paid with some exceptions of course.
