### ISSUE TITLE
Improve dirtbike routes support by providing more detailed colors

### ISSUE THREAD

**Issue by cmoffroad** [osmandapp/OsmAnd#21611]
### Describe the idea

The current color scale for dirtbike routes includes duplicated colors for values 1/2, 3/4, and 5/6, which creates confusion.

![365589781-436e7d4b-96d4-4a19-bae6-ac563ecaebde](https://github.com/user-attachments/assets/9d552643-efa4-4436-a0cb-e0768de72e5e)

 The colors are misleading because the difficulty and skills required differ significantly between each scale. Additionally, the current dirtbike:scale definitions are more closely aligned in terms of descriptions and skill gaps between 0/1, 2/3, and 4/5 (with 6 being impossible). The duplicated colors also risk encouraging mappers to downgrade values to the wrong scale, making them fit better visually but inaccurately.

I strongly suggest updating the color scale to use distinct and clear values, along with a silver option for `dirtbike:scale=?` to represent known dirtbike routes that have not yet been classified.

### Expected behaviour

Clear distinct colors per available scale:

<img width="293" alt="Screen Shot 2567-12-24 at 12 57 15" src="https://github.com/user-attachments/assets/db31c5ce-bdda-43a9-8eda-85e6996ca54a" />

### Alternatives you've considered

n/a

### Context

https://github.com/osmandapp/OsmAnd/issues/18756

**Comment by xmd5a2** [comment]
Fixed. How to test: https://github.com/osmandapp/Os
![osmand-routes-dirtbike](https://github.com/user-attachments/assets/ea871e10-396d-4641-b19d-780aed35043e)
mAnd/issues/18756#issuecomment-2337588463
