### ISSUE TITLE
OsmAnd should generate human-readable address for any POI

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2162]
The ***POI lookup*** function should generate a human-readable identity of the point.

At present, the lookup generates only road name and city. But a road can be several thousand km long, so such an address is not sufficient to define the point.

To locate a point, we need nearest landmarks, including road junctions, POIs and locality. In the context of an intra-city navigation, the name of city is obvious, so it can be omitted.

For example,
 * Road Junction ---> 1st Main, 3rd Cross, Indiranagar, Bangalore.
 * Nearby POIs -----> Near KFC, MG Road, Bangalore.

**Comment by vshcherb** [comment]
It is not planned in the nearest future
