### ISSUE TITLE
The door-to-door sorting does not minimize the route

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2163]
Add any 3-4 points on map to a route, and then do the door-to-door sorting.
Watch the total length of the route.

Now sort the points manually, and keep observing the total route length. 
You will find that some of the combinations yield shorter routes.

***Desired:*** The door-to-door sorting should find the shortest route.

**Comment by vshcherb** [comment]
Just tested looks fine, it reorganizes the points in order to find the best allocation. If the points are close then it is a subject of generic algorithm, which doesn't calculate precise route, sorting is done only by direct distances between points

**Comment by raindropsfromsky** [comment]
Does that mean that OsmAnd compares the direct (aka "as the crow flies") distances between the points and finds the shortest path that passes through them all?

If so, that logic is incorrect, because for each order of points, the route faces different traffic restrictions (like one-ways), which means sometimes OsmAnd has to take a long detour to reach the next point. This increases the overall length of the route for some particular order of points.

Therefore, the logic should compare the ***total route length***, not ***direct distance between points***.

**Comment by raindropsfromsky** [comment]
I mean, while we think that the waypoints has found the optimum order, but in reality OsmAnd makes us drive much more. How's that desirable?

**Comment by vshcherb** [comment]
The issues represents not desirable but expected behavior. Bug tracker is not a wishlist, for these reasons should be another possibly tracker

**Comment by raindropsfromsky** [comment]
Well, compare this with the UPS case: They used a [route-finding algorithm] (http://priceonomics.com/why-ups-trucks-dont-turn-left/) for their delivery trucks that avoids taking left turns. This saves them 10 million gallons of gas annually. 

Now a proposal to implement this kind of algorithm can be considered a "wish list".

But here, the OsmAnd algorithm actually increases the overall driving effort, without bringing any tangible benefit to the user. So IMHO it should be considered a bug, even if that's the way it was designed deliberately!
