### ISSUE TITLE
The "Reverse starting point and destination" command does not handle "My position" well

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2165]
The following is a very frequently encountered use case:

We set a remote point as destination, and start navigating. OsmAnd automatically treats the current GPS fix (current location) as the starting point. On reaching the destination, we swap the start and end points, and navigate back.

The new Waypoints dialog should handle this scenario, with its "reverse..." command.
But it has a bug, as described below:

Tap on the Directions button, and select any point as destination. 
Now tap on the white triangle flag button to launch the ***Waypoints*** screen.

It shows "My Position" as ****Starting point***. 
Now tap on its ****overflow*** icon, and select the "Reverse starting point and destination" command.

OsmAnd should replace the "My position" label with the lookup address of the current location.
But this does not happen: OsmAnd labels it simply as "Destination".

**Comment by raindropsfromsky** [comment]
Just discovered an additional issue: OsmAnd does not allow us to delete the "Current location" point, both when it is the starting point; and also after swapping the starting point and destination.

For example, if I want to check out the route between two random points on the map, I will have to remove the current location. But this is not possible.

**Comment by vshcherb** [comment]
Fixed
