### ISSUE TITLE
How to switch TTS engine & enhancement request

### ISSUE THREAD

**Issue by keunes** [osmandapp/Osmand#2166]
It bugged me that I couldn't get Dutch voice guidance, so I checked the website. Just read the following:
> **TTS does not function properly (i.e. Dutch)**
If you have issues with the TTS voice guidance, please check if you have a TTS engine compatible with the language in question installed on your Android device. It is a known issue that e.g. one of Android's default TTS engines (Pico) does not support Dutch. You can try to use something like SVOX or Espeak.

1. Can more info be provided on the website how to actually switch TTS engines, or a link to more information or links to the app(s) that users need to install.
2. Can't Dutch be a disabled option in the voice engine settings when the default TTS engine (Pico) is installed (or provided with some information on the issue). Currently users don't get any feedback on why things don't work (whilst it's a known issue).

**Comment by vshcherb** [comment]
I'm not sure that I could agree with such interpretation of fixing that issue. I just tried out of the box standard Android TTS and it works fine with dutch. Of course you need to have Android >= 4.4, but majority of OsmAnd users have it, so it should function fine.

**Comment by keunes** [comment]
> so it should function fine

Obviously it's not working for me. Should've said that I'm using OsmAnd 2.2.4 (release date 2015-12-22) on a Fairphone 1 with Android 4.2.2; my dad's on a Samsung Galaxy Core (GT-I8262) with Android 4.1.2. I'm afraid neither of our phones will be see an update of their OS, so I'd appreciate it very very much if you could at least help me out here even if you don't feel like/have the time to for proposal nr 2 :)

**Comment by vshcherb** [comment]
I'm not against neither of proposals, but they need to be justified.
(2) Disable if it is not supported
(1) Documenting requires collecting information first. 
I will let people more related to documentation aware of it but they need to collect more information first.

**Comment by keunes** [comment]
Thanks for getting back and informing the ppl working on documentation. I think the knowledge is already there, given the fact that documentation already mentions names (but without description (e.g. whether they're an app or otherwise) or links).

> I'm not against neither of proposals, but they need to be justified. 

What d'you mean with that exactly? Seems a bit contradictory to your first response. Do I need to provide further explanation or anything as justification? (If yes; what?)

**Comment by vshcherb** [comment]
I just reread the whole thread and I think the main problem is coming from slightly different side. I think during first time usage/navigation there could be a greeting message and popup "If you don't here the voice please click here... for troubleshooting". And there it could be a list of languages where you can test and select which actually works and some sentences to install other TTS engine for example.
That will be a generic solution for all languages and also will be useful enough. 
Documentation will be less helpful because there are lots of phones with different TTS engines and there are quite a lot of languages, so buidling a good matrix is definitely difficult.

Will put it on the roadmap.

**Comment by keunes** [comment]
> I think during first time usage/navigation there could be a greeting message and popup "If you don't here the voice please click here... for troubleshooting"

To be honest from a communication perspective it's not really smart to 'welcome' first time users (of the navigation feature) with a dialog stating "Welcome, our app maybe doesn't work. If that's indeed the case, here you can find a solution". This is exagerated of course, but I'd rather a) disable (parts of) a feature or b) provide a little bit more info on the website than currently is the case, rather than welcoming users with a negative welcoming message about the app not (fully) working properly.

> Documentation will be less helpful because there are lots of phones with different TTS engines and there are quite a lot of languages, so buidling a good matrix is definitely difficult

Personally I would already be helped with way way simpler documentation, namely what you suggested to put in a dialog (i.e. "some sentences to install other TTS engine", plus *links* to them)

**Comment by keunes** [comment]
@vshcherb Could you reopening this issue? I think the problem of a lack of info is still valid, and this is a good place to discuss the options further.

**Comment by keunes** [comment]
@vshcherb @sonora Could this issue be reopened please? My personal issue has been solved but the problem of unhelpful information/documentation still persists. Like I said before: it would already be helpful to include "some sentences to install other TTS engine", plus links to them, in the documentation.

**Comment by sonora** [comment]
@keunes : I think it is better to start fresh and open a new issue if you have good suggestions what to do. This issue originally dealt with a specific problem on a specific TTS engine, with both an older Android version and an old app version. I( think part of what is mentioned here is outdated.)
