### ISSUE TITLE
"Downloading list of available regions" persistant when no internet available

### ISSUE THREAD

**Issue by keunes** [osmandapp/Osmand#2168]
Reproduce:
- put phone in flight mode (no internet connection)
- tap on a region when on the right zooming level, so that OsmAnd will try to download a list of available regions
- OsmAnd will keep displaying "Downloading list of available regions", even after notification 'list of regions could not be downloaded from osmand.net' (translated from Dutch) -> see screenshot below

Problem: user cannot remove region from this particular view, because the 'downloading...' notification keeps being displayed.

Expected behaviour: 'downloading...' notification disappears and show 'DELETE' button, as it does when there is an internet connection, so that users can remove the region if it has been downloaded.

![screenshot_2016-01-16-17-18-14](https://cloud.githubusercontent.com/assets/11229646/12380012/be4bbfb6-bd67-11e5-8f73-82461abc113e.png)

**Comment by vshcherb** [comment]
I think we should not try at all and make special button enable internet. We have a check if internet is available in OsmAndSettings

**Comment by keunes** [comment]
To be honest I'm very happy for OsmAnd to try and download it. Adding a special setting seems to me like unnecessary clutter for such a small thing. The settings are pretty much complicated already, IMHO.

Just would like the "List of available regions being downloaded..." notification (with the moving blue bar) to disappear when the attempt to download the list fails, and makes place fore the DELETE button that would appear if there *was* an internet connection.

**Comment by vshcherb** [comment]
DownloadRegionsLayer:
BinaryMapDataObject o = it.next();
						boolean downloaded = checkIfObjectDownloaded(osmandRegions.getDownloadName(o));


private boolean checkIfObjectDownloaded(String downloadName) {
		final String regionName = Algorithms.capitalizeFirstLetterAndLowercase(downloadName)
				+ IndexConstants.BINARY_MAP_INDEX_EXT;
		final String roadsRegionName = Algorithms.capitalizeFirstLetterAndLowercase(downloadName) + ".road"
				+ IndexConstants.BINARY_MAP_INDEX_EXT;
		return rm.getIndexFileNames().containsKey(regionName) || rm.getIndexFileNames().containsKey(roadsRegionName);
	}
