### ISSUE TITLE
Separate the "Display POI/Favorite along the route" function from route planning

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2170]
At present, the ***Waypoints*** screen shows the points on the route, and then provides three sections (POIs, My Favorites, and Traffic Warnings).

The idea is to prompt the user when he is driving: A card shows the next POI/Favorite.

But this design has the following drawbacks:
 1 The user has to delete a huge number of points</br> &nbsp;&nbsp;(or else he will keep getting pop-up reminders while he is driving, which is annoying and distracting)</br>
 2 While setting up the route, the user is expected to plan everything in advance.
&nbsp;&nbsp;But in practice, we cannot make such meticulous plans in advance. </br>
&nbsp;&nbsp;In fact, we do many unplanned things along the way: </br>&nbsp;&nbsp;We get hungry/tired on the way. We run low on gas. Then we start looking for a right kind of POI.</br>
&nbsp;&nbsp;So, the design should be such that the driver can find any types of POIs whenever needed.</br>&nbsp;&nbsp;This search should not distract him from his driving.</br>&nbsp;&nbsp;(Imagine him asking Siri, "where is the nearest gas station?" and getting directed there...)</br>

***Suggestion:***
Remove the POI+Favorite lists from Route Editor altogether.</br>&nbsp;&nbsp;Instead, provide a button in Navigation mode, where the driver can quickly call for POIs of certain type with only 2-3 taps.
 * If user taps on a card and selects the ***Go there!*** context menu, re-calculate the route </br>&nbsp;&nbsp;(I have already suggested this)
 * The user should be able to toggle the cards off any time, again without much fiddling.

**Comment by vshcherb** [comment]
I think this issue is very much related to #2158 and it is not needed to spread it around with many issues.
