### ISSUE TITLE
Plugin develop

### ISSUE THREAD

**Issue by Qavai** [osmandapp/Osmand#2173]
How develop plugin for OSMAND+ for android?

**Comment by vshcherb** [comment]
For now the plugins are tight to the osmand project itself and they are part of the osmand source code. There is an entity called OsmAndPlugin and there are special packages for the plugin code. Plugins could not be built separately from OsmAnd for now.

**Comment by Qavai** [comment]
Can i write my own plugin for OSMAND and is it possible that it will be include in project?

**Comment by vshcherb** [comment]
Yes it is possible if we agree on the way it works and implements.Another approach would be extend the plugin api and use DexClassLoader, so OsmAnd will support 3rd party plugins without necessity of repackaging.

If you want to contribute, the most important that code will be maintainable by other project members, so it requires some communication. Please share your idea or you can also send me a private message to discuss details
