### ISSUE TITLE
Ability to disable/enable TTS guidance through bluetooth

### ISSUE THREAD

**Issue by AlexZvonik** [osmandapp/Osmand#2176]
When my phone connected to car through bluetooth i can't hear any voice guidance.
It would be nice to have an ability to disable the announcements playing over bluetooth that will make us answer calls and use navigation with voice guidance simultaneously.

**Comment by sonora** [comment]
Here is what is going on, and a possible workaround for you:

Your phone will route the voice output to the car radio and not play it itself if you chose General settings/Voice guidance output /Media/music audio. And unless you car radio is set to play the Bluetooth input, you will not hear anything, neither from the phone, nor from the car stereo.

If, however, you selected "Notification audio" as the OsmAnd output, in my experience you would hear OsmAnd's prompts from the phone's ringtone speaker, even if your phone has a BT connection to he car stereo, and  the car stereo is set to play its radio etc., CD, etc.

**Comment by AlexZvonik** [comment]
"Notification audio" as the output doesn't work.
Seems like audio still goes via bluetooth.

**Comment by sonora** [comment]
It does. But in addition, it should also go via the device's speaker, at
least there should be a way to configure your device like that.
