### ISSUE TITLE
Feature request: Allow clicking on POI Icons to launch extendable actions

### ISSUE THREAD

**Issue by amenk** [osmandapp/Osmand#2178]
It should be possible to click POIs.
When doing so, several actions, like attach an OSM Note, edit tags on osm.org and so on should be possible.
Also plugins should have the possibility to add completely new actions to such a POI context menu.
Also newly created POIs (in the OSM upload queue) should allow for a similar same functionality.

**Comment by xmd5a2** [comment]
Do you mean clicking directly on map (not orange circles)?

**Comment by amenk** [comment]
Yes on the map. Which orange circles are you talking about?

**Comment by amenk** [comment]
I guess you are talking about the orange circle (with a nose) which appears after searching for a POI? 
But I am usually not searching but just panning the map. So is there a way to open such a clickable circle in another way?

Until now I did not know about this menu I get when clicking on the orange circle.
So this is actually to issues:

* Make POIs clickable without the orange circle
* Let me customize the actions in the POI menu

**Comment by xmd5a2** [comment]
Duplicate https://github.com/osmandapp/Osmand/issues/1862

**Comment by amenk** [comment]
@vshcherb  please reopen - see https://github.com/osmandapp/Osmand/issues/1862#issuecomment-175870247

**Comment by littlehelper** [comment]
+1
As mentioned here and in #1862, tapping a POI directly or selecting it via a selection menu showing the closest POIs when long-tapping on the map close to the POI would be great.

The selection menu could be similar to the menu shown when tapping close waypoints/markers. In addition the first entry should be the current location, clicking on it shall open the already implemented POI menu including address lookup which is shown when long-tapping somewhere on the map.
