### ISSUE TITLE
Some POIs not found with specific search criteria

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#2180]
When I search near me for shop=weapons store, I do find certain shops, but not all.  For example, this one, with multiple shop= values, is not found:

http://osm.org/go/ZQqtDVDNt?layers=N&node=2691823132

Just for comparison, this multiple-value-tagged store is returned in search results:

http://osm.org/go/ZQq8IRHnD?layers=N&node=2691736667

It fails for me with both Play store version 2.2.4 as well as several recent nightly builds, including the 2.3.0 #15358M one that I just downloaded.

With the Play store version 2.2.4, I'm using US Georgia map dated 2016-01-04.
With the nightly builds, I'm using that same map with the latest Live update (currently 2016-01-20).

**Comment by stephan75** [comment]
Hmmm, so both seems to have shop= tag with multiplr values ...

Is that a general problem of Osmand when dealing with http://wiki.openstreetmap.org/wiki/Semi-colon_value_separator from raw OSM data?

And are you sure that the second POI is found inside Osmand really according to the shop=* tag?
Or is that found by another tag?

**Comment by jfburke3** [comment]
It's being found by the shop=weapons tag.  I'm doing a search by going to the search->POI , and then in the freeform text box I start typing "weapons" which OsmAnd starts to match against "weapons store."  I select that from OsmAnd's results list, and it starts finding the shops.  I can keep pressing the "find more" button at the bottom and it does successfully expand the search area, and starts showing me more stores, but the first one in my original post never shows up.

The main difference I can think of is the 2nd one only has two values for shop= (weapons;hunting) while the 1st one has four values (weapons;hunting;fishing;outdoor).

**Comment by xmd5a2** [comment]
OsmAnd does not support multiple tag values at all.

**Comment by Al-Hun** [comment]
Multi values are neither shown (first value could be used...) nor used for searches. Really a lack : contributor think it will offer more information and you have less...  :(

**Comment by sonora** [comment]
I think this is deprecated as it references the old search. Not sure if the new search fixes this, but we should re-base the issue if still significant.

**Comment by jfburke3** [comment]
I'll do some testing and open a new issue if necessary.
