### ISSUE TITLE
Routing problem: bypassing destination then backtracking to get there

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#2182]
I've seen several instances (unfortunately, usually while driving long distances, so I can't make any notes about it) where OsmAnd will route me *past* my destination, then backtrack to get me to the destination.

I've managed to find a simple route that reproduces the problem.  Using nightly builds, for this example I have 2.3.0 #15358M installed with the 2016-01-04 US Georgia map with the 2016-01-20 Live update.

Starting point:   http://osm.org/go/ZQqt3RV0M?layers=N&way=280413948
Destination:  http://osm.org/go/ZQqt7QInd?layers=N&way=280413948
Waypoint:  http://osm.org/go/ZQqt8t89s--?layers=N&way=280413948

OsmAnd routes me past the destination, under the Interstate bridge, then has me do a U-turn and go back to where I can turn to the destination point.

**Comment by xmd5a2** [comment]
Confirmed

**Comment by vshcherb** [comment]
Do we have a test for it?

**Comment by jfburke3** [comment]
The only test I can cite is the one involving the points noted originally; I never did write down any of the other times I encountered this, but I will try to reproduce one if I can remember it well enough.

--jack

**Comment by vshcherb** [comment]
Sorry that was to @xmd5a2 and that's why I assigned it to him.

**Comment by vshcherb** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/3240dcc06ebfbb524b3efd12f2f0d68a467160d3
