### ISSUE TITLE
Hillshade rendering issue.

### ISSUE THREAD

**Issue by DFyson** [osmandapp/Osmand#2183]
The edges of the hillshade tiles don't line up. I uploaded a [screenshot](https://cloud.githubusercontent.com/assets/12941728/12466015/4b1ad786-bf9f-11e5-9555-b42c35bdbc24.png). The zoom level doesn't matter and in really bad cases I can see it as far out as zoom level 9. Also tried playing around with map magnifier and that doesn't change it. I'm using OsmAnd+ 2.2.4 (2015-12-22)
This issue was also noted [on the forum](https://groups.google.com/forum/#!searchin/osmand/hillshade/osmand/LOCK6TGNTbM/Qsl92Wp_XxsJ).

**Comment by vshcherb** [comment]
Couldn't show on a screenshot cause I didn't find that area. Though I've found something close to that situation locally, I definitely see the difference before and after fix. Please try the latest nightly.

**Comment by vshcherb** [comment]
The code of the alignment is hard to find most likely it is here https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/views/MapTileLayer.java#L215. Hillshade maps are just sqlite maps of 13 zoom.

**Comment by DFyson** [comment]
I think the hillshade layer is only up to zoom 10. I checked the database and manually stitched some tiles together and had no problems. The mis-aligned squares are smaller than the tiles and only really visible past zoom 10. The problem is also noticeable with Mapnik online tiles. Looking at any of the examples I uploaded, at 100% magnification, the mis-alignment squares are 512px wide at any zoom level. So it confirms it's not an issue with the tiles but likely an issue with the oversampling?

To make the issue really obvious, set a tile server's max zoom to say 10 (same as hillshade layer), then use it as an overlay map (setting as normal map source only allows to zoom in +2 past max zoom). Set opacity to full, magnification to 20% and zoom to 17.

I also noticed that strange gap I found is in the tiles, not a rendering problem. For example in the Canada - British Columbia hillshade database, the png image tile at x=170 y=347 z=7 shows both a vertical and horizontal gap.

**Comment by DFyson** [comment]
I've figured out why this effect happens. It's because the upsampling algorithm needs to know what is around it to properly upsample, however it doesn't know what's beyond the edge of a tile. It needs to know what the adjacent tiles are to seamlessly upsample.  Here's a portion of a test tile I made of an 8x8 pixel array zoomed in with the original next to it.
![upsampled](https://cloud.githubusercontent.com/assets/12941728/21740259/4f026410-d482-11e6-9c02-fd55d07df08d.png)
You can also recreate the artifact in say Gimp just by upsampling then tiling it.

This problem occurs in two places; between the tiles and inside a tile.
Inside a tile happens because OsmAnd chops the zoomed tile into squares of 512px for the screen, then performs the upsampling. If it were the other way around (upsample the tile before cutting up) this artifact would disappear.
For between the tiles, the algorithm would need to do something like combine the 4 (or ideally 8 with corners) surrounding tiles, perform the upsampling, then crop it.

I've noticed there is a margin=1 and innerMargin but I'm having trouble understanding what's going on there.

**Comment by littlehelper** [comment]
I still can see some minor hillshade rendering issues which look similar to @DFyson observations.
Zoom level 13:
![tmp_30225-screenshot_20170219-0845441249501722](https://cloud.githubusercontent.com/assets/378407/23100594/833168d8-f685-11e6-8f9e-49d6dd96aa64.png)
Zoom level 14:
![tmp_30225-screenshot_20170219-084553-96744762](https://cloud.githubusercontent.com/assets/378407/23100592/7c710260-f685-11e6-90be-19e4d44097eb.png)
(Sorry for the big images, I do not know how to attach them without pasting them. At lower resolution you will not see the issue.)

Is this something Osmand related, like @DFyson assumes, or hillshade data related?

**Comment by littlehelper** [comment]
In #3359 @sonora commented: "I would argue it is a bug with our hillshade files, it should be solved by creating new hillshade data [...]" and @vshcherb answered "New hillshade data will be 4 times bigger at least."
This ticket is closed although the issue is still noticable. Does this mean 'won't fix'?

**Comment by yvecai** [comment]
DFyson probably describes it properly: intial implementation was taking into account border tiles to compute oversampling.
At the time, there was an overhead in computation, but nothing that would be noticeable today. Oversampling does not need bigger initial data.
