### ISSUE TITLE
share link

### ISSUE THREAD

**Issue by tla-dev** [osmandapp/Osmand#2184]
When sharing a place, the url is like http://osmand.net/go?lat=

In OsmAnd/src/net/osmand/plus/mapcontextmenu/other/ShareMenu.java

public void share(ShareItem item) {
	...
	final String httpUrl = "http://osmand.net/go?lat=" + ((float) latLon.getLatitude())
				+ "&lon=" + ((float) latLon.getLongitude()) + "&z=" + zoom;
	...
}

Can this variable be in a place where we can configure it?

My goal is to have a sharing url more like this :
http://maps.apple.com/?q=38.886595,-77.094892

Because it works better when sharing between android and iphones
http://stackoverflow.com/questions/18223533/how-to-launch-google-maps-on-iphone-via-web-link

**Comment by vshcherb** [comment]
Not sure we can change it, osmand.net is domain we own and osmandnet something is not really clear. For IPhone version we use similar URL

**Comment by tla-dev** [comment]
Thanks for your answer. The idea is not to change the url but to be able to configure it so that it's not in the java code.
