### ISSUE TITLE
default data location

### ISSUE THREAD

**Issue by Albirew** [osmandapp/Osmand#2185]
Default data location should not be directly in memory's root (/sdcard/osmand) but inside Android/data (/sdcard/Android/data/net.osmand.plus)

The reason to keep clean the memory's root is to makes easier for user to find important folders like DCIM, Downloads, Music and such on a glimpse. Also, [the folder created there is automatically removed upon app uninstallation](https://developer.android.com/reference/android/content/Context.html#getExternalFilesDir%28java.lang.String%29) making app remnant's cleaning automatic.

**Comment by stephan75** [comment]
under what android version do you have that experience?

What Osmand version exactly?

Where do you see exactly that folder path /sdcard/osmand is defined?

**Comment by utack** [comment]
And Androids madness with non allowed external SD access does not interfere I think

**Comment by Albirew** [comment]
So far I've experienced it with Android 4.3 (stock samsung), 4.4 and 5.1.1 (both stock cyanogen OS)
Osmand versions are both previous major version and latest (since I've installed it a couple of weeks ago on my Android 5.1.1 phone)
I believe the osmand folder in internal memory root (/sdcard/osmand/, /mnt/sdcard/osmand/, /storage/sdcard0/osmand/ or /storage/emulated/0/osmand/ depending on manufacturer and Android version) is created upon first run since it contains app prefs, tiles and downloaded content.

**Comment by vshcherb** [comment]
This is implemented for backward compatibility and it won't change until we reach > 60% Android 5. We want to achieve that after reinstall it would still find the previous folder. Of course something smarter could be invented.

Pull-requests are welcome, but this is not high-prio issue.
