### ISSUE TITLE
POI Context menu covers navigation route

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#2187]
When navigating with the phone in landscape mode, if we create a note, or tap on a POI, the resulting context menu (that pops out from the left) occupies more than half the screen.
That's fine to be able to see all the available info, but the issue is that when the map centers the view (I have it set for auto center map view in 5s), that center is in the middle of the screen, that is still not visible because the context menu is open and covering that area, so the navigated route stays out of sight while the context menu remains open.

If the map was instead centered to the available portion of the screen that is visible at the right of the POI context menu (only when it is opened), it would be better.

**Comment by crimean** [comment]
Fixed by freezing map while context menu is opened

**Comment by Barrocas** [comment]
Thanks, but if we are navigating, the map shouldn't freeze, it should continue navigation, but our gps position could be centered in the remaining portion of screen available (at the right side of the context menu), instead of the usual screen center (that is under the context menu).
