### ISSUE TITLE
OSM Live - 'Ok, Cancel, Update' buttons

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#2188]
On the OSM Live section, when viewing the maps info, there are three buttons on the bottom: Ok, Cancel, Update Now.

The 'Ok' and 'Cancel' buttons do the same (go back), so they could be just one button, or even no button at all, since the phone 'back' button can do the same action.

The 'Update now' could just be 'Update', it's simpler.

**Comment by GaidamakUA** [comment]
Ok and Cancel do different staff. Ok saves your changes and closes dialog, while cancel just closes dialog. I will address your suggestion about "Update now" to our designer.
