### ISSUE TITLE
Poi context menu - map pan

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#2189]
With the phone in landscape position, when tapping on a POI or Note, if the POI is positioned at the left part of the screen, the map pans to the right when the POI context menu opens from the left side, so that the POI position is also visible while the context menu is open. Really nice.

But sometimes, the map pans to the right, and then jumps back to the previous position, now placing the POI position under the context menu.

On occasions, I have even seen it panning back and forward, as if osmand was undecided if it should show the POI position or not.

Probably related to the hidden navigation route issue I just reported in #2187

**Comment by vshcherb** [comment]
The description is not really clear how to reproduce it. How often does it happen and what are other circumstances do you see.

**Comment by Barrocas** [comment]
It happens at random, just tested with today night build.

When taping on a POI or note, and the phone is placed in landscape position.
Try taping one POI, then another, then another, after some attemps, it happens as reported.

Most times it works as expected, and the POI is displayed at the right side of the context menu.

but other times it pans the map to the right, and then immediately back to the left, with the POI endind hidden under the context menu.
