### ISSUE TITLE
Add POI - Advanced - Add tag

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#2190]
I add a lot of POI, and also modify existing ones with additional info.

The Advanced tab with the 'Add tag' could be reviewed, it is not working properly.

When tapping on the field to insert the desired OSM tag, a huge list pops open, but I have to close it to be able to write the tag I want, then come the available tags according to what is being written, and that is fine.
Same for the value field.

In landscape mode, it's even worse.
The list pops open, I have to close it to write.
When writing, suggestion are welcome, but even if I select one of the suggested tags, when pressing the 'done' button, the suggestion list pops out again, instead of accepting what was inserted and going to the next 'value' field to add the rest of the value info.
Same for the 'value' field in landscape mode, pressing the 'done' button only opens the list again.

**Comment by vshcherb** [comment]
Let's limit autosuggestsions list to maximum 5 entries

**Comment by xmd5a2** [comment]
No, let's remove list which pops up after tapping to "tag" input field
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot_2016-01-28-00-23-10.png
It occupies all screen space and it is easier to input tag name using autosuggest feature.
