### ISSUE TITLE
Keep green flag for starting point when switching to normal map view

### ISSUE THREAD

**Issue by stephan75** [osmandapp/Osmand#2192]
Preparation for reproducing issue: (seen on 2.3.0#15390 from 22-01-2016)

Have NO destination and NO waypoint defined inside Osmand app, and have NO GPS fix.

When defining the destination point via long tap on the map and pressing the blue circle button, I can define a destination.
Then I can return to normal map view in order to pan, zoom and scroll the map like I want. The chequered flag for the destination point is still visible. Fine!
So I can do route planning like I want without loosing destination point.

Same is possible for waypoints.

Further consider this:

clear destination point and all waypoints if still defined.

When defining a STARTING point via long tap on the map, via three-dots-menu and then choose "Directions from" ... I can see the starting point with the green flag, covered by the orange round position marker, with the "Navigation Menu" where you can choose car foot bicycle etc. OK.

BUT when I now tapping on any position in the map (or chooseing the "X" button in the bottom left corner of Navigation Menu, the green flag DISSAPPEARS.

Why?

What is the reason for "deleting" the green flag, and not keeping it like the destination flag or waypoint flag?
Are there any technical reasons?

Because I really would appreciate **when a defined starting point is kept by osmand**, to do a free route planning.
Starting point and green flag could be overridden when navigation is started by user via Go-button or similar, and when Osmand app HAS a GPS fix.

So please:
**Keep green flag for starting point when switching to normal map view.**

**Comment by vshcherb** [comment]
It is not clear why the green flag got deleted
