### ISSUE TITLE
[Accented Search] search names including their diacritics alternatives

### ISSUE THREAD

**Issue by okias** [osmandapp/Osmand#2193]
When entering name of street, please consider searching for "č" when entered "c" etc. This could be really helpful and navs like Waze does it.

My proposal is first list names specific to entered letter, in second pass check for all accented letters and print them below first search result.

Of course, this should work even when street with non-accented letter is found, because for example, in Czech republic, there is majority of streets which containts accented letters and lot of similiar ones.

Some resources:
[1] http://stackoverflow.com/questions/14083446/accented-search-in-sqlite-android
[2] http://stackoverflow.com/questions/16282083/how-to-ignore-accent-in-sqlite-query-android

**Comment by hakuchi** [comment]
this sold work with all diacritics, not only "č", "ø", "ü" etc. 

here a list of diacritics:
`À    Á    Â    Ã    Ä    Å    Ā    Ă    Ą    Æ    Ç    Ć    Ĉ    Ċ    Č    Ď    Đ    Ð    È    É    Ê    Ë    Ē    Ĕ    Ė    Ę    Ě    Ĝ    Ğ    Ġ    Ģ    Ĥ    Ħ    Ì    Í    Î    Ï    Ĩ    Ī    Ĭ    Į    İ    Ĳ    Ĵ    Ķ    Ĺ    Ļ    Ľ    Ŀ    Ł    Ñ    Ń    Ņ    Ň    Ŋ    Ò    Ó    Ô    Õ    Ö    Ø    Ō    Ŏ    Ő    Œ    Ŕ    Ŗ    Ř    Ś    Ŝ    Ş    Š    Ţ    Ť    Ŧ    Ù    Ú    Û    Ü    Ũ    Ū    Ŭ    Ů    Ű    Ų    Ŵ    Ẁ    Ẃ    Ẅ    Ỳ    Ý    Ŷ    Ÿ    Ź    Ż    Ž    Þ    à    á    â    ã    ä    å    ā    ă    ą    æ    ç    ć    ĉ    ċ    č    ď    đ    ð    è    é    ê    ë    ē    ĕ    ė    ę    ě    ĝ    ğ    ġ    ģ    ĥ    ħ    ì    í    î    ï    ĩ    ī    ĭ    į    ı    ĳ    ĵ    ķ    ĸ    ĺ    ļ    ľ    ŀ    ł    ñ    ń    ņ    ň    ŉ    ŋ    ò    ó    ô    õ    ö    ø    ō    ŏ    ő    œ    þ    ŕ    ŗ    ř    ſ    ß    ś    ŝ    ş    š    ţ    ť    ŧ    ù    ú    û    ü    ũ    ū    ŭ    ů    ű    ų    ẁ    ẃ    ŵ    ẅ    ỳ    ý    ŷ    ÿ    ź    ż    ž `

**Comment by renekliment** [comment]
+1 on this. It would bring better UX for people in Slavic countries as well as people in Spanish and German speaking countries and I guess that pretty much every European country uses a language with non-ASCII characters.

**Comment by jkufner** [comment]
Yeah, the "Nice to Have" label is not very appropriate here. It is more like "Search mostly does not work in any non-English language" ;)

**Comment by vshcherb** [comment]
We are using standard java collator primary, which should ignore diacritics. There a special fix for "ro" and "sk", cause we don't have enough local knowledge we try to not change in the beginning. 

public static net.osmand.Collator primaryCollator() {
		// romanian locale encounters diacritics as different symbols
		final java.text.Collator instance = Locale.getDefault().getLanguage().equals("ro")  ||
				Locale.getDefault().getLanguage().equals("sk")? java.text.Collator.getInstance(Locale.US)
				: java.text.Collator.getInstance();
		instance.setStrength(java.text.Collator.PRIMARY);

**Comment by vshcherb** [comment]
If you change the phone locale it will work differently. The fix suggestion is not clear yet, so will keep it close for a while.

**Comment by okias** [comment]
When switched phone to "sk" language, search works fine. So for now, I just send commit allowing use it normally when czech (cs) is set..
