### ISSUE TITLE
Add Asturian Language Support

### ISSUE THREAD

**Issue by softastur** [osmandapp/Osmand#2194]
Currently OsmAnd is being translated into Asturian but the app still doesn't support it in nightly builds although the "values-ast" is present in /OsmAnd/res/

**Comment by vshcherb** [comment]
As I see Asturian is not really supported by Android yet http://stackoverflow.com/questions/7973023/what-is-the-list-of-supported-languages-locales-on-android

**Comment by softastur** [comment]
Since Android 5.0 now is possible to use 3 letter code locales and at the moment Asturian is supported on CyanogenMod. Please, update your information.

Thank you.

**Comment by vshcherb** [comment]
Well, there is no exception we do on the languages. It just simply not picked correctly by OS, it could be the issue of Android SDK we are using, but it is the latest, so we need to wait for proper OS support. 
I simply see no difference how we compile and package languages.

**Comment by softastur** [comment]
It is and it isn’t.  There is no way to select the Asturian language on most devices — Cyanogen, is a notable exception.  Nonetheless, applications can be developed for and built with Asturian resources — in fact, any language that only has a 3-letter code.

The trick is, because of some backwards compatibility issues, they had to design a somewhat convoluted system of naming the resource folders.  So whereas the English folder is simply “values-en” and the Spanish “values-es”, Asturian’s resource folder must be “values-b+ast”.  The -b+ part tells it to use BCP 47 instead of ISO 639-1.

**Comment by vshcherb** [comment]
Thanks for pointing out fixed here https://github.com/osmandapp/Osmand/commit/a0c1c05, but I guess translate.osmand.net won't support Asturian any more so we need to contact weblate team
