### ISSUE TITLE
"Take the Nth exit" - but what counts as an exit?

### ISSUE THREAD

**Issue by tobydickenson** [osmandapp/Osmand#2196]
When navigating with "avoid motorways" enabled, osmand can give misleading voice instructions which, if followed, would take you onto a motorway.

If you reach a motorway junction like the one linked below (from the south), osmand correctly routes you to the second exit (heading north). However the voice instructions say "take the first exit".

http://osm.org/go/eui9kkvOA-

I'm guessing this happens because it doesnt count exits which are not allowed. "take the first exit" really means "take the first allowable exit".

**Comment by hakuchi** [comment]
Osmand should say: "take the second exit", no matter if you avoid motorway or not.

found more roundabout with the same error as reported above.

Russia:
http://www.openstreetmap.org/#map=17/55.16073/37.92799

Germany:
http://www.openstreetmap.org/#map=17/51.00551/10.26511
http://www.openstreetmap.org/#map=17/51.38131/11.27644

France:
http://www.openstreetmap.org/#map=17/49.25444/3.97384

Italy:
http://www.openstreetmap.org/#map=18/41.09720/14.25352
http://www.openstreetmap.org/#map=18/44.50658/8.70633

Brasil:
http://www.openstreetmap.org/#map=19/-26.64568/-48.68581

USA:
http://www.openstreetmap.org/#map=16/39.0903/-76.7556

Australia:
http://www.openstreetmap.org/#map=18/-32.43418/115.80694

**Comment by vshcherb** [comment]
Duplicate #1202
