### ISSUE TITLE
Nigthly build crash

### ISSUE THREAD

**Issue by mircozorzo** [osmandapp/Osmand#2198]
Hi, in the nightly from 24 January, crashes every time after the start of the app before the home screen. On a 4.1.2 android device a Samsung GT-I8260.

**Comment by xmd5a2** [comment]
Please attach crash log here

**Comment by mircozorzo** [comment]
Hi, thanks for the reply.

Last exception log attached. Is it this the crash log
[exception.log.zip](https://github.com/osmandapp/Osmand/files/103406/exception.log.zip)
?

**Comment by xmd5a2** [comment]
Yes, thanks.

**Comment by mircozorzo** [comment]
Thanks a lot to you.

**Comment by mircozorzo** [comment]
Great! Thank you so much!

**Comment by mircozorzo** [comment]
OsmAnd still crashes in nightly build. Log attached. Thank you

[exception.log.zip](https://github.com/osmandapp/Osmand/files/104128/exception.log.zip)

**Comment by GaidamakUA** [comment]
I am afraid you are using old version. Crash report says your vesrion is Version OsmAnd~2.3.0#15393M
24.01.2016 8:04:04. though bug supposedly was fixed 21 hour ago. Can you please update your version and send us new log. Thank you for your support.

**Comment by mircozorzo** [comment]
It's not true, the last report is that because the last nightly cannot
start properly.  Now I've installed the today's 13.24 nightly and is still
crashing but the log wasn't updated.
Il 26/gen/2016 14:09, "Yurii Mazurevich" <notifications@github.com> ha
scritto:

**Comment by GaidamakUA** [comment]
We can't reproduce this issue on our hardware. So we really need to know acurate position where it crashes. This log file is outdated. Can you please try removing your log file and and sending us new version or can you use logcat for that purpose?

**Comment by mircozorzo** [comment]
Hi thanks for the reply.

The solution come by deleting the exception.log itself!
