### ISSUE TITLE
Allow user to move a marker/flag with a long-press and then drag to new position

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2199]
Sometimes we need to adjust the position of a marker a little. However, OsmAnd does not allow this. 

The only method is to add a new marker nearby and delete the old marker.
This is tedious.

Instead, consider this scenario:
 1 The user long-presses on the marker.
 2 OsmAnd gives a little buzz to let him know that the marker is now movable.
 3 The marker jumps a little upward, to be visible (its starting position is right under the finger)
 4 Without lifting the finger, the user drags the marker to the new position.
 5 When the exact location is found, the user lifts the finger. The marker is anchored at that spot.

This applies to the ***Blue dot*** also (only when OsmAnd is manipulating the natural GPS fix. For example, in "snap to road" mode.)

**Comment by ppenguin** [comment]
+1

**Comment by littlehelper** [comment]
+1
While dragging the marker to the new position, magnifying the map around the marker position automatically (like using a magnifying glass) would be helpful to set the marker at the exact location precisely.

**Comment by raindropsfromsky** [comment]
YAY!

BTW can we also club #1974 with this?
(The discussion in that thread grew too long, so I have summarized that issue, in the last post.)

**Comment by vshcherb** [comment]
Fixed

**Comment by raindropsfromsky** [comment]
I tried again, and found the following problems:

1. If I long-press on a point, the point jumps a little up. But it cannot be dragged.
2. If the point is part of a route (start/waypoint/destination), it cannot be moved at all.
3. If this marker is for a audio/video/photo note, it cannot be moved.
4. The current position marker (blue dot/arrowhead) also cannot be moved.

Thus the implementation is not finished in any way.

Please reopen the bug.
