### ISSUE TITLE
Trim search query for POIs

### ISSUE THREAD

**Issue by ByteHamster** [osmandapp/Osmand#2200]
When searching for a POI by name, it would be better if the search string could be trimmed (remove trailing spaces). If you select a prediction on the keyboard, it adds a space after the word. Therefore, `"ABC "` will not find the result `"ABC" `. This just confused me because I knew I found the POI previously. Simple and easy-to-implement feature but might help quite a few users

**Comment by GaidamakUA** [comment]
I believe space is ignored now. I've checked Drawer -> Search -> POI screen and Search by name screen. Can you please post screenshot?

**Comment by ByteHamster** [comment]
Obviously, both screenshots were recorded in the exactly same GPS location.

<img src="http://i.imgur.com/MI42uQl.png" width="300"> <img src="http://i.imgur.com/phmgp4u.png" width="300">
