### ISSUE TITLE
Wrong navigation route rendering: too wide

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#2201]
The navigation route is extremely wide: it covers the road and map details.

HUWEI Y 6 (SCL L21) double SIM, 2 GB RAM
OsmAnd+ Ver. 2.2.4. 

![rsz_screenshot_-_01282016_-_032939_pm](https://cloud.githubusercontent.com/assets/12711814/12645732/a172943a-c5d4-11e5-8fd9-3d614e517aac.jpg)

**Comment by raindropsfromsky** [comment]
I too reported this issue a few days back.

**Comment by vrtareg** [comment]
Hi
I have used today nightly build and it was absolutely fine. 
Regards, 
Areg

**Comment by xmd5a2** [comment]
Can somebody experiencing this bug test latest nightly but with UniRS rendering style?

**Comment by sonora** [comment]
Leonid, cannot reproduce on any of my test devices. Must be very special settings, or very specific hardware when it occurs, not sure. - Hardy

**Comment by raindropsfromsky** [comment]
I am also not seeing this problem in the nightlife for the last one week
(at least)

**Comment by xmd5a2** [comment]
If anyone still experiences this bug please let us know:
1)Android OS version
2)"Configure map" - "Map magnifier" value
