### ISSUE TITLE
Doubletap-Zoom problem when already at min-zoom

### ISSUE THREAD

**Issue by quelbs** [osmandapp/Osmand#2202]
There is a small glitch when you try to zoom beyond min-zoom using the new doubletap-zoom feature.

Steps to reproduce

1. Zoom to min-zoom or near min-zoom
2. use double-tap-zoom and try to zoom out

What happens:

- Map center moves, but map zoom does not change

What should happen:

- nothing

**Comment by vshcherb** [comment]
Not critical, map center moves is a good feedback as well.
