### ISSUE TITLE
Oneway arrows not rendered

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#2203]
After the changes made with the waterways direcion arrows in #1330, the highway 'oneway' arrows fail to render most of the time. 
They are only visible occasionally at some zoom levels, but just by changing the zoom level, the arrows disappear.

**Comment by xmd5a2** [comment]
Can't reproduce. Are you using custom rendering style or default style?

**Comment by Barrocas** [comment]
Using latest night build (from today morning), with custom rendering
file, but it's based on the default (only changes colors and the route
line is dashed).

Changing to the default Osmand style gives exactly the same result, no
difference.

I know these ways are oneway for sure (I'm also OSM mapper), even in
motorways, the 'oneway' direction arrows just stopped being rendered
in Osmand.

-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by Barrocas** [comment]
In build 2.3.0#15477M the oneway highway arrows still render as was usual.
In build 2.3.0#15492M they render with the slightly thicker arrows, that look a bit too fat (maybe i'm not yet used to them), but also renders fine.
then at least from build 2.3.0#15516M until today, they fail to render.

**Comment by xmd5a2** [comment]
I'm using 15551 and arrows are fine

**Comment by Barrocas** [comment]
Phone is a BQ Aquaris E6, running Android 4.4.2
Just downloaded and installed Osmand build 15552, and sorry, but I have no oneway arrows at all.

**Comment by xmd5a2** [comment]
I think I forgot to set default value to noHighwayOnewayArrows. Please test 15554 (latest)

**Comment by Barrocas** [comment]
Fixed, thanks.
Tested v15555, and the thicker oneway arrows are rendered.
