### ISSUE TITLE
waterways with tag 'layer=-1' are not rendered

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#2204]
As the title says, waterways with tag 'layer=-1' are not being rendered.
They are rendered in OSM, but are absent in Osmand.

**Comment by xmd5a2** [comment]
They are rendered but starting from zoom 19. In many places underground waterways creates unnecessary distraction to map. 90% of users does not need to see them. However they can be needed for OSM mappers. Added them to OSMMapperAssistant mode.

**Comment by Barrocas** [comment]
Thanks! :)
