### ISSUE TITLE
disable duplication notice

### ISSUE THREAD

**Issue by philipzae** [osmandapp/Osmand#2205]
I use osmand heavily to add features that will go into OSM like street bumps, pay phones, etc and these cant be unique in name and always get the name duplication error notice and it would be nice to have a means of disabling this notice, as it delays the addition process.

**Comment by vshcherb** [comment]
It is not clear why name should be unique, you can always overview and edit your changes in My Places - OSM Edits. Please clarify your message

**Comment by philipzae** [comment]
So as an example, i'm driving down a residential street and it has 3 bumps (traffic_calming=bump) along the road. i add a favourite at the first one as 'bump' and when i add the second one with the same name, a notice titled "Favourite point name duplicate" appears and i press 'OK' to rename it to 'bump (1)'. Adding the third one brings up the notice and renames it to 'bump (2)'. It would be nice to not have to press 'OK' each time the name is a duplicate.

Screenshot of notice: http://www.picpaste.com/pics/20160201_175710-fSrF5v7S.1454335455.jpg

**Comment by daltux** [comment]
You could also open an OSM Note with the description "bump" instead of marking the place as a Favorite named "bump". But to do so, you have to enable Osmand OSM Editing plugin. http://osmand.net/features?id=osm-editing-plugin

**Comment by philipzae** [comment]
What would i lable each bump favourite, if i were to put "bump" in the note? I would assume it would be easy to have a setting to disable the notification from popping up every time. Imagine if you received a notice after every addition of a favourite saying the same message (e.g. "Your favourite has been create"). It would be an annoyance and would slow down productivity.

**Comment by sonora** [comment]
No action planed here, it seems.
