### ISSUE TITLE
OsmAnd cannot handle address from phone's address book

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2206]
In my address book, I have the following address:
36, 1st Floor, 33rd Cross, 16th Main, 4th T Block, Jayanagar, Bangalore 560041

My address book shows two buttons: a "tear-drop" marker, and a "Direction" marker.
The former is supposed to show the spot on a map, and the latter is supposed to set up a route from the current location to that spot.

When I tap on any button, the phone first asks me to choose an app to open with.  
- Both buttons work properly in Google Map.
- But if I select OsmAnd, both buttons don't work. </br>&nbsp;OsmAnd shows a wrong Latlong for the spot (36.0,0.0) (Note that it has only one decimal point)</br>&nbsp; (OsmAnd shows this point in the sea, north of Algeria).</br>&nbsp;The following error keeps popping up: </br>&nbsp;&nbsp;&nbsp;`Error calculating route: Ending point too far from nearest road.`

**Comment by vshcherb** [comment]
Known issue, the address search is not supported
