### ISSUE TITLE
Tahiti/Oceania height lines gone completely wrong

### ISSUE THREAD

**Issue by RicoZ-OSM** [osmandapp/Osmand#2208]
Thanks for fixing #1934 - I have downloaded the height lines in OsmAnd 2.2.4.

Something must have gone wrong generating them  - they are not visible anywhere except completely "runaway" heightlines which possibly wrap east-west around the whole world at the latitude of Huahine Iti.
-16,77072; -150.99001 is the place I am looking at.

Another 180° meridian problem?

**Comment by xmd5a2** [comment]
Confirmed
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot%20from%202016-02-01%2016%3A46%3A52.png

**Comment by RicoZ-OSM** [comment]
Just noticed that Taveuni might be an even better example: west of the 180th meridian you get the correct height lines *and* the horizontal run-away lines, east of the meridian just the run-away lines.

**Comment by vshcherb** [comment]
@xmd5a2 In case I can fix something please let me know.

**Comment by xmd5a2** [comment]
Please check today's Oceania srtm update. Issue should be fixed now.

**Comment by RicoZ-OSM** [comment]
Thanks, looks great.
