### ISSUE TITLE
mtb stylesheet: Render mtb:scale with +/-

### ISSUE THREAD

**Issue by anderfo** [osmandapp/Osmand#2211]
The mtb stylesheet in OsmAnd does not render mtb:scale=1-, 1+, 2-, 2+, etc., ref. [OsmAnd legend](http://osmand.net/help/Map-Legend_default.html). I.e. they are rendered identical to trails without mtb:scale.

However, such grades (+/-) are described on the [OSM wiki](https://wiki.openstreetmap.org/wiki/Key:mtb:scale#How_to_Map_it_-_Usage.2C_Tags_and_Values), and although they are not extensively used, they should be rendered.

For example, mtb:scale=1- and mtb:scale=1+ could be rendered identical to mtb:scale=1, as a starting point... (unless you have a better idea of how to render them).

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/f7dd0cb8b74e6ce0d4b1f7f5ac9a2bbedf171ea0
