### ISSUE TITLE
Improvements to mtb stylesheet (use mtb:scale=0 and class:bicycle:mtb)

### ISSUE THREAD

**Issue by anderfo** [osmandapp/Osmand#2212]
Some small changes could make the OsmAnd [mtb stylesheet](http://osmand.net/help/Map-Legend_default.html) much better:
* Use a separate color for mtb:scale=0. Right now, it is impossible to see the difference between a trail with mtb:scale=0 and a trail without mtb:scale (which could be anything between 0 and 7).
* Use a highlighting based on the class:bicycle:mtb (see [OSM wiki](https://wiki.openstreetmap.org/wiki/Class:bicycle)) tags, to highlight the nice trails and hide the ugly trails.

In general, consider using the colors of [mtbmap.no](http://mtbmap.no/#15/63.4306/10.3329), which fits better with the colors people are used to from e.g. skiing maps / piste maps. See [mtbmap.no stylesheet](http://mtbmap.no/assets/legend_retina.png). This stylesheet works excellent and is more easily readable than your current mtb stylesheet, in my opinion.

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/6f91242b94faf99e1f9d076d57603cdc70f18bc8
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot%20from%202016-02-10%2021%3A38%3A50.png

**Comment by anderfo** [comment]
Looks better!
Is there a way to tell the app to use/download the last version of the stylesheet, or is it rather a part of the app (i.e. need to wait for next update of the app)?

**Comment by xmd5a2** [comment]
It is part of the app. You can use nightly build http://download.osmand.net/latest-night-build/
