### ISSUE TITLE
Improve Street name search

### ISSUE THREAD

**Issue by james2432** [osmandapp/Osmand#2215]
Living in the Ottawa Valley we have to deal with bilingual (French and English) street names all the time seeing as it's on the boarder of Quebec and Ontario.

One thing I've noticed with the street name search is it searches with a "begins with" algorithm.
The problem that this causes is in French the street type is at the start i.e. Boulevard Montclair. Where in English this would be Montclair Boulevard. This causes problems when you don't know if the street is: Rue, Boulevard, Avenue, Impasse, etc

One solution would to allow results that contain what your are typing and not necessarily only starting with it.

**Comment by johnwhelan** [comment]
I seem to recall going through all the street names in OSM within the City
of Ottawa and correcting them a couple of years ago.  At that time I didn't
spot a single French street name that was correctly spelt.

The name contains the English version of the street name name:fr contains
the French version of the name.  You can have the Ottawa street names
display in English or French in OSMAND or Maperitive.

There maybe some roads that do not have both an English and French name
they need to be corrected sometime.

Cheerio John

**Comment by james2432** [comment]
The problem isn't Ottawa in itself, it's Quebec which is primarily French, which could go for France and any other country that the language has the street type before the streetname. Sure in an ideal world everything would have an English equivalent, but it doesn't.

**Comment by johnwhelan** [comment]
If you're talking about the Quebec side then I agree the name does not
start with the street name in French and I concurr it could do with
accomodating.

Cheerio John

**Comment by vshcherb** [comment]
It is partially correct, the search is focused on begin with but it also searches the names that have a middle part match. The only possible issue they are displayed on the bottom of the list. 
For example here: https://www.dropbox.com/s/4k4b2wbtl1gc3pb/2016-02-20%2014.17.25.png?dl=0

Another feature already implemented is Configure Map -> Map Language, there you could select french or english and it will use name:fr, name:en for search.
