### ISSUE TITLE
Slovak maps of 3rd Feb 2016 broken

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#2216]
When I try to download full map of Slovakia_europe from 3rd Feb 2016, it is advertised as ~180MB inside OsmAnd. The download is fine, unpacks the map but it is only ~80MB in OsmAnd. There is no error reported but looking at the rendered map I see it is completely broken. Most objects are missing. I did not see this problem on other neighbouring countries. Also the roads-only map of Slovakia is fine. This is on the stable 2.2.4 version.

**Comment by xmd5a2** [comment]
Fixed

**Comment by aceman444** [comment]
Confirming. Map of 6th Feb 2016 is working fine.
What was the problem? Would you notice it with some automatic mechanism even if I didn't report it?
