### ISSUE TITLE
opening_hours displayed incorrectly when there are multi day entries

### ISSUE THREAD

**Issue by cart0** [osmandapp/Osmand#2217]
I am using OsmAnd 2.4.4 on Android 4.4 and am noticing a bug in how it shows if an amenity is open (green) or closed (red) if the `opening_hours`  covers multiple days.

If the amenity has for example `opening_hours` = `mo-fr 07:00-19:00; sa 12:00-18:00`  and you are checking the opening hours in OsmAnd 2.4.4 on mo-fr, OsmAnd ignores the opening hours and takes it from `Sa` times.

Also if you Search for POI and select for example `Restaurant and Cafe`  it will bring up a list of the closest but, using the above time sample, the poi listed will have the days from the first (`mo-fr`) but display the times for `sa`.

Similarly if the `opening_hours` was `mo-fr 07:00-19:00; sa 12:00-18:00; su 14:00-17:00` all the time information would be taken from `su`

**Comment by vshcherb** [comment]
The issue is in the syntax, it should be "Mo-Fr ...", actually now OsmAnd support lower case as well, but previous versions not.
