### ISSUE TITLE
Request to render: landuse=plant_nursery

### ISSUE THREAD

**Issue by CJTmmr** [osmandapp/Osmand#2219]
In my area are a lot of plant nurseries.
But landuse=plant_nursery is not rendered yet by OsmAnd.
A import many years ago tag those plant nurseries incorrectly as landuse=orchard.

http://wiki.openstreetmap.org/wiki/Tag:landuse%3Dplant_nursery 
and
http://wiki.openstreetmap.org/wiki/Proposed_features/Plant_nursery

Proposed rendering:
basic color of "landuse=farmland" with overlay of (not too dark) tree-symbols (like landuse=orchard, )

When plant_nursery is rendered, we can correct the false tags.

Thanks
Kees-Jan

**Comment by hakuchi** [comment]
you should not tag the plant_nursery as orchard for showing something in OsmAnd or OSM.
The Netherlands using a lot of wrong [tagging for the renderer](http://wiki.openstreetmap.org/wiki/Tagging_for_the_renderer).

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/a753413c2640cc8cc1f449fbbf0a44c3938bc9e1

**Comment by CJTmmr** [comment]
Thanks for very quick respons,sure looks good. 
PS  A request at gravitystorm for standard Mapnik still had no effect since August 2015....
