### ISSUE TITLE
Unnecessary line break in route info

### ISSUE THREAD

**Issue by firesharker** [osmandapp/Osmand#2220]
If you use Osmand with comma as a decimal separator, there will be an unnecessary line break in the total distance. (red arrow)
I think the bug is in [this line](https://github.com/osmandapp/Osmand/blob/r2.2/OsmAnd/src/net/osmand/plus/views/controls/MapRouteInfoControl.java#L399). Using ` replace(", ", ",\n")` instead of ` replace(",", ",\n")` should solve the problem, although this is not the best solution.

![screenshot_2016-02-07-15-43-26](https://cloud.githubusercontent.com/assets/11246384/12873189/5ecfd2ba-cdb7-11e5-93b6-5294b4637e27.png)

**Comment by vshcherb** [comment]
Already fixed
