### ISSUE TITLE
TTS speech navigation not working on Android 5.1

### ISSUE THREAD

**Issue by keunes** [osmandapp/Osmand#2223]
English TTS speech navigation worked on my FP1 (Android 4.2.2), but on my new phone FairPhone 2 (Android 5.1) it doesn't work. Recorded instructions do work (apart from street names etc, obviously).

Was TTS tested on Android 5.1, and confirmed to work (or not)?

**Comment by sonora** [comment]
When ypu go to your Android (not OsmAnd) settings, find the voice output / tts section, set it up correctly, then it "Listen to an example" (most Android versions have this, although it may b called slightly different), can you hear anything then?

**Comment by keunes** [comment]
Ah, thanks. I wasn't able to do the test and other settings wouldn't load either, after which I figured I disabled almost all Google apps. After re-enabling Google's TTS app it works (doh)

Thanks :)

**Comment by sonora** [comment]
There are alternative TTS engines if you are not fond of google ... but you do need to install and activate one TTS engine, or it won't work   :-)

**Comment by keunes** [comment]
@sonora Yup, that was quite dumb :P
Can you recommend any in particular?

**Comment by vrtareg** [comment]
Hi

I am using IVONA speech engine.


Quite good one.


Regards,

Areg

> --


Regards,
Areg
