### ISSUE TITLE
[Proposed] Add shields road in Argentina

### ISSUE THREAD

**Issue by franco999** [osmandapp/Osmand#2224]
As I see you are designing several coats of road for the US and Europe, take the opportunity to propose that the shields can be added to Argentina. I link shields example in SVG format.

For national routes (network=ar:national): http://wiki.openstreetmap.org/wiki/File:RN1-AR.svg
For provincial routes (network=ar:provincial): http://wiki.openstreetmap.org/wiki/File:Ruta_prov_2.svg
For secondary provincial roads (network=ar:provincial:secondary): the same as the provincial routes.
More info: http://wiki.openstreetmap.org/wiki/Señales_viales_en_Argentina#Nomenclatura_vial_y_urbana

I do not know the structure in the rest of the shields, but in Argentina, should be added depending on the tag network route relations.

**Comment by xmd5a2** [comment]
Fixed aed013d4e6e58ce479c383f6b568e63055c45021

**Comment by franco999** [comment]
Thanks, but in the latest nightly is not changing the shield. It considers that the labels (ar:national, ar:provincial and ar:provincial:secondary) agreed to include in relations route and not on the road. The ref tag is included on the ways and relations.

example: https://www.openstreetmap.org/relation/3429120

**Comment by xmd5a2** [comment]
It should work only with new maps.

**Comment by franco999** [comment]
@xmd5a2 
I think you should make a change in the way of showing the reference shield with respect to **RNAxxx**

Line [#L1258](https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml#L1258) should not be because the **A** of **RNA** should be displayed.

For example: _National Route A001, National Route A008, National Route A012_

See more: https://es.wikipedia.org/wiki/Categoría:Rutas_nacionales_de_Argentina

**Comment by xmd5a2** [comment]
@franco999 Do you mean that shield shape and color is correct but "A" prefix should be displayed?

**Comment by xmd5a2** [comment]
Fixed
