### ISSUE TITLE
[IMPROVEMENT] Error "Position is to far" should be "A map is missing to calculate a route"

### ISSUE THREAD

**Issue by therob84** [osmandapp/Osmand#2225]
This error messages appeared, while I drove through a region, in which I did not had an offline map downloaded before and after I started a navigation to a destination at a map region which I downloaded.
(original in german: "Position zu weit entfernt")

It took my quite some time to figure out why no map was displayd at the current position and why no rout is calculated and what this error message means.

The error message should be changed to something like:
"A map is missing to calculate a route." Or something similar. 

I used v2.5.2 at Android 5.1 with a Fairphone 2.

**Comment by vshcherb** [comment]
That's currently not possible to implement cause we don't really no, if the road is disconnected from road network or the map is missing. We have plans to improve that case for transit countries but it is not possible in all situations.

**Comment by therob84** [comment]
OK, you admit this is a problematic issue.
But why you closed it, if it not solved yet?
