### ISSUE TITLE
[IMPROVEMENT] waypoint option only "add as LAST waypoint" and "navigate FROM" only available

### ISSUE THREAD

**Issue by therob84** [osmandapp/Osmand#2226]
From v2.1.1 I was used to a more detailed menu for a selected point at the map, it included "navigate from/to", "add as waypoint" and allow to order it manually and add as destination...

Now in v2.2.4 it is only available "add as LAST waypoint" (in routing mode) without the chance to sort the order manually and only "navigate FROM" in the normal mode without the option to choose "navigate to".

As I find it a real mess in v2.2.4 to make a route with some waypoints I really vote for a rework or a re-implemention of the v2.1.1-way of handling this!
This is connected #2158 ([my comment](https://github.com/osmandapp/Osmand/issues/2158#issuecomment-181026570))

**Comment by vshcherb** [comment]
It should be a dialog to add as last or as first, that is missing now

**Comment by therob84** [comment]
It should be "add as..." --> 
"...destination"
"...start"
"...first waypoint"
"...last waypoint".

But an overall re-design of the nagivation/window as [suggested here](https://github.com/osmandapp/Osmand/issues/2158#issuecomment-172741364) would makes things even more simple.

**Comment by vshcherb** [comment]
Fixed
