### ISSUE TITLE
[IMPROVEMENT] Use tooltips consequently in all menus of the GUI

### ISSUE THREAD

**Issue by therob84** [osmandapp/Osmand#2227]
Although after using OSMAnd for 2 years (up to v2.1.1) I struggeld to perform simple navigation tasks with waypoints in current v2.5.2 (which you can e.g. [read here](https://github.com/osmandapp/Osmand/issues/2158#issuecomment-181026570))

A main problem for me was the **missing tool-tips** (with normally should appear with a long-tap at the questionable symbol in modern piece of software).

Without these tooltips I had to click every and every symbol to discover its functionality (which provides in the case of routing and waypoints massive room for improvment in comparison to v2.1.1) and sometimes don't have the possibility to go back easily.

The OSMAnd GUI now follows the principle "learning-by-doing-and messing-up" instead of "learning-by-reading" which I would much prefer!

Please introduce tool-tips for each symbol to learn its function and to allow a more intuitive handling, especially of new OSMAnd verisions.
Thanks

**Comment by vshcherb** [comment]
Yes it is work in progress if you know how please submit pull-requests

**Comment by therob84** [comment]
Unfortunately I don't know how it is possible, as I am no coder.
But I thought tool-tips is one of the basics in object-related programming for Android, as nearly all good Apps do support it?!

The simpler version would be to make the tool-tip available using the black bubble of notifications, which already is used by OSMAnd.
