### ISSUE TITLE
[BUG] profile (car/bike/foot) is not kept after leaving navigation mode

### ISSUE THREAD

**Issue by therob84** [osmandapp/Osmand#2228]
If I leave the navigation menu (by clicking the X at the lower left corner) OSMAnd switches back to the standard profile instead of keeping the profile I used the second before I left the nagivation mode.

It drives my completely crazy while playing arount with a route optimization. I needed to change the profile from car to bike everytime after I canceled the route mode.

In my opinion the "standard profile" should only be activated at program startup and not during normal usage, as the user normally don't changes the kind of vehicle between two route calculations.

Is the "standard profile" even necessary? I would prefer that OSMAnd just remembers the last used profile at the next start (or make this behaviour optional in the settings).

I use v2.5.2 at Android 5.1 with a Fairphone 2.

**Comment by vshcherb** [comment]
Works as intented, if you want to change for application, you need to change in the Settings or without navigation

**Comment by therob84** [comment]
OK, you said it is intented and closed it.

But I really vote to change it to [IMPROVEMENT], as it bothers me every time a lot.

Do you understand my line of arguments provided above? 
If **yes**: can we change it and please include it as a [IMPROVEMENT]?
If **no**: can you provide scenarios, where the current behaviour makes really sense in daily life?

I still vote for my suggestion as I find it much more intuitive:

> "In my opinion the "standard profile" should only be activated at program startup and not during normal usage, as the user normally don't changes the kind of vehicle between two route calculations." 

Please think about this.
