### ISSUE TITLE
FC when displaying tracks with short split interval (Regression)

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2233]
Select a recorded track of say 10 km length, select a short split interval of 20m, 50m or 100m, then select "Show on map". OsmAnd FCs, see log attached.

This is a regression, build of e.g. 2016-01-19 does not have this issue.

[exception.log.txt](https://github.com/osmandapp/Osmand/files/120993/exception.log.txt)

**Comment by sonora** [comment]
PS: Looks like it is some "overflow" issue. For really long tracks of several hundred km even the 5km split interval fails. Again. Older builds never had any issues.

**Comment by sonora** [comment]
Looks like the issue started on Feb 2, here are the 2 likely commit candidates: https://github.com/osmandapp/Osmand/commit/56ea9d74a35c5aaf2efb41bd831761c1a6216496, https://github.com/osmandapp/Osmand/commit/829a43d8ae3dd2b485ac1a63088a8ebbaaf30446

**Comment by GaidamakUA** [comment]
I have no idea, how problem didn't appeared before. But now it should be solved for good.

**Comment by sonora** [comment]
Yes, true, some shift in painting time it took to make all the dots on the map, it seems, but reproducible.

Good job, seems fixed now, thanks!
