### ISSUE TITLE
French Souther and Antarctic Lands

### ISSUE THREAD

**Issue by kubrickfr** [osmandapp/Osmand#2234]
French Souther and Antarctic Lands are made of Kerguelen Island, Saint Paul and Amsterdam islands, Crozet islands and a few islands in the Mozambican channel (and also Adélie land in Anatarctica). Most of them are currently in the Australia & Oceania Maps, they should be moved to  French Souther and Antarctic Lands.
See: https://en.wikipedia.org/wiki/French_Southern_and_Antarctic_Lands

**Comment by xmd5a2** [comment]
Yes, it was a wrong border bug. Will be fixed with new maps generation.

**Comment by kubrickfr** [comment]
Hi,
I downloaded the newly generated maps, it's weird, it seems it only contains recent updates to the area and not all the rest, the file is still very small (<1MB). I can see bits of coastline here and there, a few summits, etc...
I think it needs a forced complete generation if there is such as thing...
F.
