### ISSUE TITLE
waterway cut man_made=bridge

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/Osmand#2236]
If a bridge is tagged with man_made=bridge, the waterway cut the part from the rendered area, however the riverbank is under the bridge.

Example:
Link to [OSM](http://www.openstreetmap.org/#map=19/47.28035/11.19822&layers=N)
![PIC](http://fs5.directupload.net/images/user/160211/vxxndg37.png)

**Comment by vshcherb** [comment]
The issue has moved to https://github.com/osmandapp/Osmand/issues/2538
