### ISSUE TITLE
Is there a guide or some way to open .OBF maps in code and use its data ?

### ISSUE THREAD

**Issue by jokoon** [osmandapp/Osmand#2243]
I want to build a 3D application and load OSM data with it.

The OBF format seems to suit my need, since it's packed and already indexed.

Mapbox's MBTILES already supplies their own format, which are zipped protocol buffers inside a sqlite file.

Does OSMand also provide a way to open .obf files, or at least some sample C++ or java code example to do so ? What kind of dependencies would it require ?

**Comment by stephan75** [comment]
I recommend to ask that general question at https://groups.google.com/forum/#!forum/osmand and **NOT** on this issue tracker.

or have a look at http://wiki.openstreetmap.org/wiki/Vector_tiles

but please no reply here, but on googlegroup.
