### ISSUE TITLE
Osmand ignores direction of highway=stop, traffic_calming and other

### ISSUE THREAD

**Issue by daltux** [osmandapp/Osmand#2246]
When driving "backward" on a two-way road, Osmand shows a stop sign and says "attention, stop", but the respective node was tagged correctly as `highway=stop` and `direction=forward`. The router should be aware of the element direction when it is known, at least when not on a one-way road, triggering the alert only when the route follows the same direction as the sign, bump or other kind of highway feature.

**Comment by naoliv** [comment]
It should not be only specific for `highway=stop`, but for any element in the highway with `direction`
For example, http://www.openstreetmap.org/node/2464290699

**Comment by daltux** [comment]
> It should not be only specific for highway=stop, but for any element in the highway with direction

True. Issue description edited in order to reflect this.

**Comment by sonora** [comment]
Implemented for stops and speed limits.
