### ISSUE TITLE
Import from "Wandeltochten" (walking tour) app does not works

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#2247]
The new hiking club in Flanders, Belgium in particular, “Wandelsport Vlaanderen”, unites 350 Flemish hiking clubs with more than 60000 members account for about 2000 hiking organizations with approximately 1,700,000 entries. (http://www.wandelsportvlaanderen.be/)

She has also a free app "Wandeltochten" (walking tour), here you can see the walking calendar.

Choose a date, and choose a walk, press now on top right click Properties, then you can go to the start navigating with Google Maps or with OsmAnd+,
but that  give a error, for example: OsmAnd gives Invalid format: q=Gildestraat+9,+3582+Beringen,+België .

Many hikers use OsmAnd and can not use he navigation, too bad.

https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot_2016-02-09-13-37-56.png

**Comment by vshcherb** [comment]
Known issue, search is not supported via intent
