### ISSUE TITLE
Should group nearby objects with the same features when issuing an aural warning

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#2248]
While navigating from https://www.openstreetmap.org/node/2464290690 to https://www.openstreetmap.org/node/2464290699 we can hear osmand saying a lot (really a lot) of "Attention, traffic calming", one after the other, without any pause.

Of couse, it is saying one "attention" for each `traffic_calming` we have there:

![](http://i.imgur.com/Pa3TleZ.png)

Since we don't want to listen "attention" for 11 times, nor it's benefical to have that amount of aural warning, osmand should group identical nearby objects and issue just one warning for a group.

It should be the same case for very near `highway=stop`, `highway=crossing`, etc.

**Comment by vshcherb** [comment]
I think we should disable rumble_strip. According about suggestion to combine attention, true it will be nice to have feature

**Comment by naoliv** [comment]
Indeed I agree that there should be no warning for `traffic_calming=rumble_strip` too.

**Comment by xmd5a2** [comment]
Removed rumble_strip from routing announcements

**Comment by sonora** [comment]
It looks like this has been satisfactorily resolved (?).

**Comment by BalooUriza** [comment]
Could we get this reopened and reintroduce the warning?  Maybe have Osmand not audibly alert for the same kind of warning multiple times in a certain distance?  This would also resolve problems where multiple tightly spaced uncontrolled crosswalks trigger an annoying number of warnings as well, without eliminating the utility factor.

**Comment by scaidermern** [comment]
Yes, this sounds like a good idea. After emitting a warning just temporarily suppress the same warning for, say, 10 or 20 seconds. This should be enough to make this really useful feature way less annoying.

**Comment by BalooUriza** [comment]
Heck, even 30 to 45 seconds would help so long as there's still visual indication.
