### ISSUE TITLE
Specific car routing map style

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#2249]
I feel a difficulty and need to have a specific style for driving mode (using a car) in osmand and I think that it needs a map style for this.

It should prioritize, whether possible, driving and highway related stuff:

* exit numbers/names (`highway=motorway_junction`)
* highways's `ref`
* `amenity=fuel`
* `highway=services`
* `highway=rest_area`
* `emergency=phone`
* `barrier=toll_booth` (with a possible different color when the highway has `toll=yes`)
* `traffic_calming`

Pedestrian related objects (`highway=path`, `highway=footway`, `highway=steps`, etc) shouldn't be displayed.
Most probably polygons should be ommited as well (`landuse`, `building`, etc), together with shops/amenities, `leisure`, etc.

I think that MapQuest Open style does a good job in highlighting the highways, `ref` and `motorway_junction`, for example:

![](http://i.imgur.com/Jji6mzw.png)

Maybe it could be based on MapQuest Open.

It also recalls what I see in my TomTom:

![](http://i.imgur.com/M4RGZuM.png)

For the night mode, LightRS already has an almost-ready style:
![](http://i.imgur.com/IA97pH5.png)

It's very similar to what I see in TomTom, with the exception that highways are black and the background red:
![](http://i.imgur.com/5G65rVN.png)

Is it possible to have, by default (for driving mode), such specific rendering?

**Comment by vshcherb** [comment]
We have separate issues for highway's ref and motorway_junction. Fuel and other icon are displayed till 15-16.

**Comment by naoliv** [comment]
Sure.
What I am trying to say is that this new style should include and display all these characteristics, in an easy to view mode (like MapQuest Open does with the `motorway_junction`s, displaying they in a green box).

**Comment by vshcherb** [comment]
Yes, we have 2 separate user stories: 1 is actively in progress to display better shields and 1 is to display proper refs in address bar. We definitely like the MapQuest and we are going to improve our shields.

**Comment by naoliv** [comment]
Maybe I didn't properly explain this: what I would like is an specific map style for driving mode.
What we have in osmand now is:

* OsmAnd
* Touring view
* UniRS
* LightRS
* Nautical
* Winter and ski

With the exception of "nautical" and "winter and ski", the other styles are generic and not specific for driving. They display too much information on screen and/or not everything needed/wanted for driving.

MapQuest Open was just an example of what I think would be a good style for driving (likewise LightRS' night mode).

While I know that there are still some things to work (`ref`, shield, etc), my request is to have a style designed specifically for driving mode, which included all the elements from my first message: being simpler than the current default themes, with colors designed specifically for driving and displaying only important features/elements for the driver.

**Comment by vshcherb** [comment]
I'm not sure, this exactly correct each style supports different vehicles, so OsmAnd default is different than OsmAnd car. In case LightRS is completely different style and it is designed from scratch. 
UniRS most likely will be removed because it has only different colors. Touring view/UniRS are maintained by different persons.
I don't think we should make new style, we should first improve shields and other info in OsmAnd car mode.

**Comment by naoliv** [comment]
The OsmAnd theme in car mode displays elements not related with driving.
For example, I can see soccer fields, swimming pools, churches, schools, shops, historic monuments, etc.

This is what I am trying to say: right now there isn't one specialized style which shows only driving/car related objects.
