### ISSUE TITLE
Displaying at the same time ETA and remaining travel time

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#2250]
When selecting `Time to go` in  `Configure screen` we can see an app where we can choose to display the ETA or the remaining travel time (by clicking at it), but it's not possible to see both at the same time.

If possible, we should have one app for each function:
* one to display only the ETA
* one to display only the remaining travel time

This would allow to have both informations displayed at the same time.

**Comment by littlehelper** [comment]
In #1734 ideas about how to possibly display several data on the screen at once can be found.

**Comment by sonora** [comment]
Let me close this one, we can pursue in #1734.
