### ISSUE TITLE
English TTS voice sounds very unnatural on one of my devices

### ISSUE THREAD

**Issue by black-square** [osmandapp/Osmand#2251]
On **Xiaomi Redmi Note 2** TTS-en sounds very unnatural (probably because of the playback speed):
- OS: Android 5.0.2 (MIUI Global 7.1 stable 7.1.3.0)
- Chipset: Mediatek MT6795 Helio X10
- CPU: Octa-core 2.0 GHz Cortex-A53
- GPU: PowerVR G6200
- OSMand+

On **Zopo ZP980** TTS-en sounds significantly better:
- OS: Android 4.2.1
- Chipset: MediaTek MT6589T
- CPU: Quad-core 1.5 GHz Cortex-A7
- GPU: PowerVR SGX544
- OSMand+

I've recorder the both voices: [Recording.zip](https://github.com/osmandapp/Osmand/files/135634/Recording.zip)

**Comment by vshcherb** [comment]
Playback speed could be changed in accessibility settings plugin, but it should be possible to configure in Android settings as well. You also can install other TTS than system has already.

**Comment by black-square** [comment]
The problem has been solved by changing the Text-to-speech Engine form Pico TTS to Google TTS in the Android settings.
