### ISSUE TITLE
OsmAnd not opening location from Whatsapp anymore

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#2255]
Today I received a location in Whatsapp and after clicking on it, it directly opened Google Maps.

Maps isn't defined as the default application and I remember that OsmAnd was able to process and open the links.

Is it a recent issue with OsmAnd or maybe some problem introduced by Android 6.0?
What can I do to help in debugging this, please?

**Comment by vshcherb** [comment]
I think it  is related to #2256

**Comment by naoliv** [comment]
Updated to the latest nightly (`OsmAndF~ 2.3.0#11959D`) and it still fails.
When clicking on a location it directly opens Google and doesn't ask to open with osmand.

There isn't any error in logcat.

**Comment by vshcherb** [comment]
Let's validate it again. I'm afraid your settings now pointing to Google directly.

**Comment by naoliv** [comment]
Right. In this new android version Google Maps was configured to always open compatible links  (which includes location).
While it's not the default app for anything, it was always capturing the links without asking.
Sorry for that.

**Comment by naoliv** [comment]
(another sorry for reopening)
While testing it I am seeing that `lon` has a `0.0` value.

For example, the location that I received is `https://www.google.com/maps/search/-23.2776,-45.8443128/data=!4m4!2m3!3m1!2s-23.2776,-45.8443128!4b1` 

OsmAnd is interpreting it as this:

![](http://i.imgur.com/ulmXptW.png)

**Comment by njohnston** [comment]
I get the same behaviour as naoliv. I'm using OsmAnd+ 2.2.4 on a Samsung Galaxy S5 running Android 5.0.

**Comment by jumbo1960** [comment]
I am using Android 7
1- Go to setup
2- chose app than Google maps
3- chose default settings
4- press clear default 

Thats all, now watsapp asking Google maps or Osmand or earth or yandex  :))
