### ISSUE TITLE
Position hops between GPS and last Passive/Network 

### ISSUE THREAD

**Issue by whyteks** [osmandapp/Osmand#2257]
This is happening on an Android 4.2.2 device.
It may or may not be relevant that the device runs the UnifiedNLP Legacy Network Location and the PersonalWifiBackend

This used to happen sporadically and a reboot of the device would correct it.
Since some update of osmand it happens all the time. Sorry I can't be more specific. It's only now that I am convinced that the behaviour is constant. 

When I open osmand it will usually show the position as determined by wifi APs and as soon as the device acquires GPS lock, the position begins to hop between the wifi and the gps position, this happens about once every second. This can be annoying if there are no currently known APs as it can cause a jump of large distances as one moves away from the last know wifi based location. 
If there are wifi APs about, the position will constantly jump back to the last position when the AP was observed, which is consistent with how personalwifibackend works, but it's very annoying.

I have no idea where to go looking in the code, and I note nobody else reports this, but then it is a special case. I'm reporting the issue in case it might grab somebody's attention. 

As I said it may or may not be an osmand issue, but I am only observing this behaviour with osmand. Maybe something to do with the way it polls the location?

**Comment by vshcherb** [comment]
After some investigation and testing, couldn't reproduce that bug.
Looking into the details:
Here we request network listener to search first time
https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/OsmAndLocationProvider.java#L247
After that we check that gps location is not lost for 12 seconds https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/OsmAndLocationProvider.java#L600.

Of course it is possible that your GPS provider works with period of 15 seconds but that will be strange cause OsmAnd requests GPS location for 1 second.

I'm not sure if we can fix that issue.
