### ISSUE TITLE
Sprachpaket

### ISSUE THREAD

**Issue by wolf41** [osmandapp/Osmand#2261]
Wo finde ich das osm Sprachpaket?

**Comment by jf-simon** [comment]
Was genau meinst du? 
Unter Karten Management sind die sprachansagen

**Comment by wolf41** [comment]
Habe osm  installiert ,funktioniert auch,er schreit aber nach dem Sprachpaket,wo finde ich das?

**Comment by wolf41** [comment]
V

**Comment by jf-simon** [comment]
Du hast osmand installiert. Im Menü unter Karten Management

**Comment by wolf41** [comment]
ICH HABS DANKE

 

Von: jf-simon [mailto:notifications@github.com] 
Gesendet: Montag, 22. Februar 2016 14:37
An: osmandapp/Osmand
Cc: wolf41
Betreff: Re: [Osmand] Sprachpaket (#2261)

 

Du hast osmand installiert. Im Menü unter Karten Management

**Comment by jf-simon** [comment]
Bitte Issue schließen
Please close this issue

**Comment by stephan75** [comment]
IMHO this is a typical case why the newly available issue templates in github could lower the traffic here a bit:

see https://groups.google.com/d/topic/osmand/RxsMIMdjyzk/discussion
