### ISSUE TITLE
Strange map error on Taveuni/Fiji

### ISSUE THREAD

**Issue by ghost** [osmandapp/OsmAnd#2262]
At higher zoom levels there is a strange "polygon" not present in the OSM data, at lower
levels this polygon cuts the island and parts of the island disappear on one side of it.

One edge of the polygon is here:
Location: geo:-16.941154,179.89377?z=22
http://osmand.net/go?lat=-16.941154&lon=179.89377&z=22

Similar phenomenon strikes the neighboring Savusavu, here it appears that the mysterious polygon is part of some coastline shape file which seems to cause trouble only on the far east end of the island where for some reason it cuts through the island. This cut line is not the 180th meridian but west of it and not exactly north-south.

Maybe the coastline - in areas where it crosses the 180th meridian - is incomplete in the osmand map data and the missing information is replaced by some higher order shapelines?

**Comment by dmpr0** [comment]
<table style="width:100%">
  <tr>
    <th>OSM</th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/a0631ee1-74e5-4dce-879c-ea6b5b73135b"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/357775fa-1685-43e7-a3a7-cb54f3476ef9"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/32d0e52d-9e45-485d-bb45-2a7c31959f5c"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/e871dd7b-a657-4005-bf2c-778a19d247e9"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
Merged with https://github.com/osmandapp/OsmAnd/issues/5973

**Comment by dmpr0** [comment]
# Review 

<table style="width:100%">
  <tr>
    <th>Offline Rendering</th>
    <th>OsmAnd Online tiles</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/f0649a67-cdd3-42e4-9ce5-5928db39a4b5"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/ec37cd92-dfbe-4ff7-b9b6-0a2f770d6c35"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] Data is not present

**Comment by xmd5a2** [comment]
Poly was fixed and **Oceania_australia-oceania** map was regenerated. Should be fixed now.

**Comment by vshcherb** [comment]
Extra fresh testing is needed

**Comment by zipav** [comment]
OsmAnd Nightly 4.7.0#1735m, released: 2024-03-04

# Testing

<table style="width:100%">
  <tr>
    <th>Offline Rendering</th>
    <th>OsmAnd Online tiles</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/bd73c169-233d-4358-9fdb-6b859c440f8a"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/dbb4d35a-53d4-4afd-b687-e7206391e58e"  width="300" height="auto"/> </td>
  </tr>
</table>   

<table style="width:100%">
  <tr>
    <th>14</th>
    <th>15</th>
    <th>16</th>
    <th>17</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/1e009e0e-e87d-444e-8f6b-e03ad351445a"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/803bf2a9-46f4-4172-8662-5be41c5cf416"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/8fc46a39-5f19-44e7-992c-b038de14f385"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/48d34e0b-748c-4b53-ab91-21cb886db172"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by dmpr0** [comment]
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/362ac6a9-f89f-4a6d-85da-6db4ac68e153"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/a7f0f972-0865-42b7-80a2-160fb59ff54c"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/5aea28bd-53c7-4045-b2fe-74fa9c120761"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/c4fa528b-4bbc-4dcc-8447-d863898379e5"  width="300" height="auto"/> </td>
  </tr>
</table>
