### ISSUE TITLE
NB - No street names

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#2264]
Yesterday I was walking along a street, browsing Osmand map, adding POI and checking for street names, then I noticed that most of the street names are no longer displayed, in Osmand latest night build.

**Comment by vshcherb** [comment]
Could you provide a screenshot? Was it a temporary issue and gone after restart?

**Comment by Barrocas** [comment]
![screenshot_2016-02-23-11-51-33](https://cloud.githubusercontent.com/assets/4006691/13250789/ce7d3c10-da23-11e5-991b-45ff049612d9.png)

Using Portugal map, most street names are not displayed.
I can see some names if the higways are tracks or unclassified, but the on the other higways it only displays the ref tag (if available).
Not temporary. Remains the same after closing app and restart.
The names are correctly tagged, and they are displayed in the navigation instructions, but not on the map browsing.

**Comment by Barrocas** [comment]
Build from 2016-02-20 still works ok, then from day 21 the street names are missing.

**Comment by xmd5a2** [comment]
Fixed just now. Thanks for noticing it. Bug was related to new road shields which are under development.
