### ISSUE TITLE
Coordinate support for UTMREF / MGRS / USNG

### ISSUE THREAD

**Issue by kralo** [osmandapp/OsmAnd#2265]
I would like to request the support of another UTM-"Variant" to be used when entering POI/Location or getting coordinates.

It seems support is already there through the  `Osmand/OsmAnd/src/com/jwetherell/openmap/common/MGRSPoint.java`.

This UTMREF differs from the standard UTM in that it has two additional letters that show a 100x100km square.

This format is used in German /Austrian civil protection by the [USGS](http://www.fgdc.gov/usng/)

And I would suggest to call it "UTMREF / MGRS / USNG" as label!

**Comment by vshcherb** [comment]
In search location we support format UTM, I'm not sure if it is not the same.

**Comment by kralo** [comment]
No, it is not! Although similar, it has an additional "hierarchy" with a two-letter code:
![auswahl_003](https://cloud.githubusercontent.com/assets/3055678/13388896/1f04df86-dec4-11e5-9a2d-da24dcdf19f7.png)

Could you consider reopening ?

**Comment by vshcherb** [comment]
I think it makes sense to have this feature.

**Comment by devurandom** [comment]
What is requested here is a variant of [UTM](https://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system) called [MGRS](https://en.wikipedia.org/wiki/Military_Grid_Reference_System) in English and [UTMREF](https://de.wikipedia.org/wiki/UTM-Referenzsystem) in German. It is primarily used by the NATO and civil protection services / disaster management services.

**Comment by vshcherb** [comment]
Yes we don't support it unfortunately

**Comment by jonasstein** [comment]
I can see MGRS support:
![xRt44h9nQ-qFvOfyfjNmDA_f4e0f253f7a05f2faf077e704469a81c211dac41](https://github.com/osmandapp/OsmAnd/assets/298682/9596559d-54af-41bd-ad1b-e311b78be727)

Unfortunately it takes many steps from the map to the MGRS coordinates.

Can we close it as fixed?
