### ISSUE TITLE
[Feature Request] Ability to specify specific units of measure for distance, speed and height.

### ISSUE THREAD

**Issue by DFyson** [osmandapp/Osmand#2266]
Currently can only select a group of units for speed, distance and elevation. These should all be separate options so one can pick the individual units.
For example in sailing knots are common with either ft or m for depth. Or driving with km/h and using either ft or m.

**Comment by vshcherb** [comment]
Today we have separate settings for speed and distance already but not for elevation. For example pedestrian speed is min/km or km/h.

**Comment by sonora** [comment]
No action planned here.
