### ISSUE TITLE
[Feature Request] Implement hardware menu button

### ISSUE THREAD

**Issue by DFyson** [osmandapp/Osmand#2267]
The left hand menu button on my phone doesn't do anything and never has. Normally this is used to bring up the menu in applications. Seems a waste of a good button. This issue has been brought up in the forums several times [[1]](https://groups.google.com/forum/#!searchin/osmand/menu$20button/osmand/E_JE-8dDEPc/zZnsxKbs9L8J) [[2]](https://groups.google.com/forum/#!searchin/osmand/menu$20button/osmand/0-M_8JZxBfk/nGbLl9GZk_gJ) [[3]](https://groups.google.com/forum/#!searchin/osmand/menu$20button/osmand/oWXJHGy53d8/2rfZRnxe_h4J) but can't find an issue here.
I am using Samsung S3 with OsmAnd+ 2.2.4 (2015-12-22)

**Comment by sonora** [comment]
Known issue on Samsung phones, already fixed in nightlies, but not yet released.
