### ISSUE TITLE
Map files: listed download sizes and actual files sizes don't match.

### ISSUE THREAD

**Issue by DFyson** [osmandapp/Osmand#2268]
In Map Management -> All Downloads, the file size listed for regions seems to be out of date. Ontario, Canada for example says 440MB but once downloaded shows as 616MB in the local files. I suspect this isn't a bug with OsmAnd but is something wrong with the file sizes listed in the file index which OsmAnd downloads. Where should this bug be filed?

**Comment by franco999** [comment]
I was the same with the map of Argentina

**Comment by sonora** [comment]
The file sizes are listed as stored on the server (download file sizes), but the files are then de-compressed in your local file system.

**Comment by DFyson** [comment]
If that's the case then I'd say it's pretty unclear. If you go into All Downloads (which are the files located on the server) and say go to Austria, the standard map shows 420MB. If you click on it to download, I am prompted with "Free space now 960MB! Download 1 file(s) (670MB)". So maybe you're right it's just telling me it will end up taking 670MB of space but in a misleading way.
Sounds to me like the information should be a little more clear to the user. Required disk space and required data bandwidth.

**Comment by vshcherb** [comment]
It was recently change the dialog, so the message is more verbose now
