### ISSUE TITLE
Searching POIs: App closes when pressing back button.

### ISSUE THREAD

**Issue by DFyson** [osmandapp/Osmand#2269]
Steps to reproduce (using OsmAnd+ 2.2.4):
Menu > Search > pick one, say 'Food' [goes to search results] > Press show on map button in bottom right corner [brings up map with POIs on it] > select back button [goes back to search results] > back button again [goes back to search field]. Now either press the hardware back button or the back button in the upper left hand corner. I would expect it to go back to the map, however instead the app exits.
It would be nice to have a warn-on-exit option to stop accidentally exiting the app.

**Comment by sonora** [comment]
Already fixed, not yet released, I think.
