### ISSUE TITLE
Bug: Checkbox for map overlay or underlay can display wrong state.

### ISSUE THREAD

**Issue by DFyson** [osmandapp/Osmand#2270]
In map configuration, the state of the checkboxes for selecting map overlays and underlays can become unsynchronized with the over/underlay being enabled.
Steps to reproduce:
Select overlay map [checkbox gets set and list pops up with maps to select] > hit back button instead of selecting a map > checkbox is still marked even though nothing has been selected.
Now that checkbox is selected, click on it and it becomes unselected but the list comes up.

OsmAnd+ 2.2.4

**Comment by xmd5a2** [comment]
This UI was completely redone some time ago. It can be tested using nightly builds http://download.osmand.net/latest-night-build/

**Comment by DFyson** [comment]
thanks, looking good!
