### ISSUE TITLE
Rendering of wikipedia articles need fixing and cleanup

### ISSUE THREAD

**Issue by DFyson** [osmandapp/Osmand#2272]
For wikipedia POIs, the article summary and full articles have various problems:
- Some text is missing completely. Note how the numbers are missing from the OsmAnd rendering in these screenshots [[1]](https://cloud.githubusercontent.com/assets/12941728/13276535/5ed33f0c-da8e-11e5-9aef-10bb5c8dd481.png) [[2]](https://cloud.githubusercontent.com/assets/12941728/13276543/6d822c0c-da8e-11e5-9a71-9fdcbf1c9980.png)
- Images arn't loaded but take up large blocks of space. So remove them (or since they link to the image in wikipedia, then have an small clean icon indicating an image.
- TOC and reference links don't do anything. They should be re-written to navigate the article.
- With the dark theme, the article summary looks fine but the full article still has black text on white background which is inconsistent with the theme and irritating to read in the dark.
- The article summary should be stripped down such as removing images, image descriptions, TOC.
- Some numbers in the article summary (eg 2006) act as URLs which are opened as phone numbers.
- Link to to full online wikipedia article should be easier/faster to get to (less clicks). Maybe for consistency have same as the rest of the POIs with the link in the details (ie have the "Wikipedia" label as a link to external apps similar to phone numbers and websites. related: #2273

**Comment by vshcherb** [comment]
Today we didn't manage to find good rendering of wikipedia articles and the one we use is simple wiki-> html translator. We use 3rd party library but it is not as good as original wikipedia rendering. We don't plan to invest time in our own rendering engine instead we hope to find proper library from wikimedia. So far the situation is not clear.

**Comment by DFyson** [comment]
I've tried Aard2 and Kiwix and both are pretty good for rendering Wikipedia. Maybe the easiest and most accommodating solution would be an option in the preferences to pick what to do for viewing the full wikipedia articles: use the internal reader, Aard2, Kiwix, Wikipedia app, or default web browser with the link. But the key here is that it has to be seamless. The external app has to come up in one tap, no picking which app to use, no manually switching applications, etc. I know apps can do this (ex Shazam can callup up Spotify directly with a search search query for a song).

**Comment by sonora** [comment]
@vshcherb  For now I at least greatly improved our Wiki article display:
- Font sizes are now scaled in accordance to what a user has set on their Android system's "Display / font size" setting (this fixes the problem that on some devices the base font was illegibly small)
- Pinch zooming and panning the offline Wiki article display screen now also works properly
- Tapping (also page internal) links in our offline wiki articles (like in the article's table of contents) now works correctly and puts you to the correct target section

**Comment by vshcherb** [comment]
Great job!!!

**Comment by sonora** [comment]
No further action planned for now, I guess.
