### ISSUE TITLE
POI information need some fixing & visual improvements

### ISSUE THREAD

**Issue by DFyson** [osmandapp/Osmand#2273]
Searching for and displaying a POI will show extra info about it such as website and phone number. However the look and feel is not quite right:
- For POIs which have both a website and wikipedia entry, the wikipedia url entry takes priority over the poi webpage url when really they both should be displayed. And the full wikipedia URL does not have to be shown, just an icon or text linking the url. [Example screenshot](https://cloud.githubusercontent.com/assets/12941728/13277034/65385850-da93-11e5-99c7-67053786e946.png)
- Urls would look cleaner if they were stripped of the http:// and any trailing /.
- For phone numbers, depending on the format, the number is not properly parsed and linked for handling by external applications. eg the format (123) 456-7890 works fine but 123 456 7890 does not. Ideally the entries in OSM should conform to a standard format but in reality that can't be expected. [Example screenshot](https://cloud.githubusercontent.com/assets/12941728/13277034/65385850-da93-11e5-99c7-67053786e946.png)
- Ideally raw tags should be cleaned up to a more human readable format. For example see "Cuisine: coffee_shop" should really be Cuisine: Coffee Shop.
- Instead of explicitly writing out tags for boolean features of a place (eg "internet access:yes" or "drive-in:yes", wheelchair, etc) it would look cleaner and easier to read if they were represented as icons indicating 'yes' or 'no'. Then can click on the icon to get the meaning of the icon or more info.

**Comment by sonora** [comment]
Mostly fixed already, I think.
