### ISSUE TITLE
Simplify GPX file import steps

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2275]
While fixing a small bug with GPX2favorutes import (https://github.com/osmandapp/Osmand/commit/8365f70eb5cd084b571b8ea3c7015285abc9145e) I notice that we probably have an obsolete wiggle in our file import process:

Here https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/helpers/GpxImportHelper.java#L70 we fork to either handleFavouritesImport (if the file name in question contains "favorite" or "favourite"), subsequently user has the choice to either import wpt points contained in the GPX file to favorites, or simply copy the GPX file to the osmand/tracks/import folder. Otherwise we fork to handleGpxImport, where the file is directly copied to the tracks/import folder without interim choice dialog.

I think the second case is obsolete. Instead, we should always, regardless if the file name contains 
"favo(u)rite" or not, show the dialogue offering the choice between "copy" and "import to favorites".

Making the appearance of the dialog dependent on the file name is not obvious to any user, and serves no functional purpose, I think?

I suggest replacing lines 70 - 75 of GpxImportHelper.java by simply the following code: (The handleGpxImport case deleted here is automatically forked to later after the dialog):
		} else {
			handleFavouritesImport(intentUri, fileName, saveFile);
		}

**Comment by sonora** [comment]
Fixed and tested ok(https://github.com/osmandapp/Osmand/commit/ba568480b5d0728fd199930c1ba3f3ffc4432c17).

**Comment by vshcherb** [comment]
Makes sense. 
Offtopic: please overview the last changes with markers (it is still configurable via development settings), we have plans to start release around next week and this one is the last big piece in the release

**Comment by stephan75** [comment]
> we have plans to start release around next week and this one is the last big piece in the release

@vshcherb 
also offtopic here, but can you announce that also in the osmand googlegroup so that all translators can start last efforts to complete translations as much as possible and test new features (which ones?) before the new release? Would be great!

**Comment by vshcherb** [comment]
Yes will do.
