### ISSUE TITLE
Screen settings - jumps to top

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#2277]
When changing the Screen settings, selecting one of the options (altitude, transparent skin, etc), the list imediately jumps to the top, and we have to scroll down again to be able to select other options.

**Comment by xmd5a2** [comment]
What OsmAnd version do you use? Can't reproduce with current nightly

**Comment by Barrocas** [comment]
2.3.0#15875M and previous versions also do it.



No dia sábado, 27 de fevereiro de 2016, xmd5a <notifications@github.com>
escreveu:

> What OsmAnd version do you use? Can't reproduce with current nightly
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osmandapp/Osmand/issues/2277#issuecomment-189699055>.
>


-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by vshcherb** [comment]
I can reproduce but after a while it doesn't jump any more. We experienced with Alexey it 2 times, so it looks a little bit mysterous but very annoying may be looking at the code might help.

**Comment by crimean** [comment]
Fixed
