### ISSUE TITLE
Wikipedia PT - local names are in Russian?

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#2279]
If the map settings are in the default mode for map names, it shows the 'local names'.
On most places it works fine, but wikipedia-PT POI names are displayed with Russian names (see screenshot)

If the map language is set to Portuguese, it then works as expected, and the names are displayed in Portuguese.

Shouldn't the local names for wikipedia-PT be Portuguese by default?

![screenshot_2016-02-25-19-21-31](https://cloud.githubusercontent.com/assets/4006691/13331586/08c18f92-dbf6-11e5-9e8c-da04ae463b5e.png)

**Comment by vshcherb** [comment]
Of course should be shown in english, looks very strange may be there are some test issues.

**Comment by DFyson** [comment]
I noticed something similar. Turn on POIs -> Wikipedia and there will ones in Russian on the map but written in latin, no cyrillic. Click on it, open full article and click change language and it shows it's only available in Russian. Open it with say the wikipedia app or webbrowser and it's available in English and Russian.
Now turn on POIs -> Wikipedia English and that POI will no longer be shown.

Another one is seeing the name in latin Ru, clicking on it, and the wikipedia text will say it's in Fr with Fr text but the title will be in latin Ru. The only two options will be Ru and Fr when there is also En available. Click on Ru and get the cyrillic Ru title.

These issues are only for some POIs, not all.

**Comment by crimean** [comment]
If there is no EN name - random name translation is taken
https://github.com/osmandapp/OsmAnd-tools/blob/master/OsmAndMapCreator/src/net/osmand/osm/util/WikipediaByCountryDivider.java#L423

**Comment by Barrocas** [comment]
If I am travelling in Portugal, I would expect that the selection of 'local
names' for map language would be in local language, so in Portugal it would
be portuguese (in my case, it's the same as phone sistem settings), or even
in English if all else fails.

-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by crimean** [comment]
Please do not worry, it will be fixed. It was just a tech note above.

**Comment by Barrocas** [comment]
Sure, no problem.

-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by vshcherb** [comment]
Should be fixed by https://github.com/osmandapp/OsmAnd-tools/commit/c6c9d9e132478fb9153b71267b60d3f50c2ca535. Requires verification, new maps will be generated.
