### ISSUE TITLE
Public transport stops displayed with wrong names

### ISSUE THREAD

**Issue by andrewshadura** [osmandapp/Osmand#2281]
After a recent update, tapping on a public transport stop doesn't always display the correct name anymore. Sometimes the displayed names are of a nearby street, but not of the stop itself.

I'll add a screenshot in a couple of minutes, let me fetch it from the phone.

**Comment by sonora** [comment]
Yes, confirmed, it looks like we perform a reverse geocoding lookup for transport stops even if we know the name of the stop. (Names of stops are correctly displayed if an area of multiple stops is tapped on at higher zooms in the multi-selection popup menu.)

**Comment by andrewshadura** [comment]
Haha, sorry it took me so long :-) I've got distracted and completely
forgot about the screenshots.

**Comment by vshcherb** [comment]
There is another issue with public transport stops and we want to finish it before release. Today public transports are completely not integrated with context menu it is not that difficult to fix, so I hope next week it will be there.
