### ISSUE TITLE
Misinterpreting geo: locations

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#2282]
I have some contacts on my phone with a _geo:_ field.
For example, fields like `geo:home = -22.0 -47.0`

While osmand properly understand it, it seems to be misinterpreting the latitude.

When clicking at the field and choosing to open it in osmand, it opens the location as `Lat: 22.0, Lon -47.0`

Note that **-22.0** wrongly becomes **22.0**

Version is OsmAndF~ 2.3.0#12030D

**Comment by sonora** [comment]
No change to that code in a long time, at first glance ...

Also: I have just tried a umber of my links, and they al seem to work fine, so I cannot reproduce.
Please note that per documentation the syntax is as follows: 
geo:latitude,longitude
geo:latitude,longitude?z=zoom
geo:0,0?q=lat,lng(label)
geo:0,0?q=my+street+address

All of these seem to work ok. I have also tried your example, but removed the blanks and inserted a comma between lat and lon, and it also seems to work ok (returns a place in Brazil)?

Please double-check. Thx- Hardy

**Comment by vshcherb** [comment]
We have unit tests for that parser and so far we double check if everything works ok. 
Fields like geo:home = -22.0 -47.0 don't look correct because it is not correct url.

**Comment by naoliv** [comment]
Right, the problem was with the missing comma.
Didn't know about this small detail.
Thanks!
