### ISSUE TITLE
Favorites GPX import terminates at '&' character

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2283]
Small issue in our GPX import code, went unnoticed because our toast claims "Favorites successfully imported", while not all Favorites contained in the file are actually imported:

Our GPX import routine ignores anything after the first occurrence of an '&'' character in the GPX file (at least in the name tag of a `<wpt>`). As an example: If you had a Favorite called `<name>This & that</name>`, OsmAnd correctly exports this line to `<name>This  &amp; that</name>` in favourites.gpx. But in any later import, this favorite (and anything after it in the entire GPX file) is never imported any more, import seems to stop after encountering an &.

**Comment by vshcherb** [comment]
& should be proper encoded as "&amp;" in xml. It might be bug in Android xml writer because we use standard library. Let's check.

**Comment by sonora** [comment]
Sorry, I just notice I had not tagged the details as "code" above, so the actual information was hard to read. Amended now. Looks like we export & as `&amp;`, but then do not make it to import that again.
