### ISSUE TITLE
Map markers: The map marker widgets only appear very sporadically

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2287]
The colored direction arrows to the off-screen map markers only appear very sporadically, mostly only after panning for a minimum distance and only until the panning stops.

**Comment by vshcherb** [comment]
That's not an issue and it is something to discuss. We use that approach in IOS, so it doesn't raise question why I see all the time directions. Second the arrow from my location is always visible on top and it fits most of use cases except the use case when user pans the map and that's how it works.

Backward compatible behavior is implemented if you switch Markers -> Toolbar to Markers -> Widgets.

**Comment by sonora** [comment]
Yes, actually, I quite like it now that the arrows only appear while
panning. It only appeared a little sporadic at first sight, because they
really needed panning, just tapping or anything does not suffice.
