### ISSUE TITLE
Map markers: If the marker history is empty, and the last (only) active marker is swiped out, it does not get added to the marker history

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2288]

**Comment by vshcherb** [comment]
There is a small delay they show up in the history, is it a different issue?

**Comment by sonora** [comment]
No, I fixed it by https://github.com/osmandapp/Osmand/commit/4f5a254dbb3fffe5441bdde69d77447c19b2df59. Will need to test if this has other side effects. The issue arose from getActiveObjects() being empty upon returning from updateMarkers().
