### ISSUE TITLE
[IMPROVMENT] Make "unit of velocity" as a toggle when click at it in map/nav mode

### ISSUE THREAD

**Issue by therob84** [osmandapp/Osmand#2290]
In current version (2.2.4) you can choose in 
settings-->navigations-->[walk]-->"Unit of velocity"-->"km/h, mph, ... , min/km,..."

I would suggest to have this setting also available as a quick setting:
--> clicking at the velocity value in the map/navigation main screen should toggle through all different modes!

**Comment by sonora** [comment]
This should be very infrequently accessed, it is a one time config for most users, if t all. Guess we should close this.
