### ISSUE TITLE
Integrating project to Android Studio

### ISSUE THREAD

**Issue by deiauk** [osmandapp/Osmand#2291]
I'm trying to integrate this project to Android Studio and I'm getting lots of errors. First of all string resources is not found on layout files (I have fixed this manually just replace path to string.xml file to my own string). But here are other errors in AndroidManifest.xml for example I get that android:installLocation, android:versionCode, android:versionName and other attributes are not allowed there. What's wrong with that? Have anyone import this project to Android Studio successfully?
Also I get this error WARNING [Project: :OsmAnd] Current NDK support is deprecated.  Alternative will be provided in the future.

**Comment by vshcherb** [comment]
This is not a functional issue.
