### ISSUE TITLE
Search History entries for points selected from the map displayed as LatLon only

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2293]
I notice that ever since recently we automatically delete the destination point (and all interim destinations, if set) whenever a user cancels a route calculation by tapping the route screen's (X) button.

We should at least make sure users can reasonably easy re-instate their destinations if they need them again. The obvious functionality would be via the Search / History screen, but 2 issues here:

(1) Looks like the prior final destination gets listed there, but for points a user had selected directly on the map (more precisely: for points of type="Location"), the history entry title shows their Lat/Lon values instead of their reverse geocoding result. We should likely use the result of the reverse geocoding lookup, if successful, as title, and only use the LatLon if no address was determined.

(2) Loos like any intermediate destinations a user may had added to a previous route (by direct selection on the map) are never added to the search history screen at all?

**Comment by sonora** [comment]
I think (1) should be fixed via https://github.com/osmandapp/Osmand/commit/df96865a74cd8912ed0a8abf63b68dbb91c5b19f

**Comment by sonora** [comment]
(1) seems fixed.
(2) It looks like it is a little sporadic when we add a point to the history and when not. Seems that when a point is selected and subsequently e.g. shared, added to favorites, or used for "directions from", no history entry is created. In other cases (used as destination, and I am not quite sure and about intermediate destinations), an entry is created.

I guess we can close this issue for now unless anybody has the time to systematically check when we create history entries.

**Comment by crimean** [comment]
> (2a) I just notice: Looks like if points are added to the Search history also partially depends on whether the map marker setting is on or off.

We should consider Map markers setting as turned ON only.

Regarding (2) - I need exact algorithm when points should be added to the history

**Comment by sonora** [comment]
For lack of a better "algorithm", I guess I suggest we make the Search/History as global as possible, meaning it should contain EVERY singluar point  the user ever searched (Poi, location, address, etc.), and in addition every point the user ever marked on the map and then used in any fashion, be it as a map marker, destination, or intermediate destination, avoid road, etc.

In this fashion this is our surefire list to get back what otherwise may be lost, and the separate map marker history list exists as a as cleaner list for points expressively used as map markers (but they are in any case also contained in the global history).

**Comment by vshcherb** [comment]
Not sure yet. Will mark observed and hope to get back to this issue next release.

**Comment by sonora** [comment]
From testing this in recent months: Looks like we correctly add a point to he history as soon as it is once used as  destination. (But not if it only selected on the map). Probably ok, think we can close this?
