### ISSUE TITLE
Can't delete amenity tag for POI

### ISSUE THREAD

**Issue by geoeki** [osmandapp/Osmand#2294]
Following [this recent blog entry](http://blog.3rik.cc/2016/02/i-love-free-software-how-to-edit-openstreetmap-in-osmand/) I tried using OSMand not just for navigating, but also for editing. Upon creating a new POI I have to select a name for it as well as a tag. I can chose from several tag types (leasure, transportation, natural, etc.) but when I check on advanced, the dafault is always 'amenity', no matter which tag I chose. I can add additional tags below the amenity tag and it works there, but I can't change the default amenity tag.

I asked this on the osm forum and a more experienced user shares this issue with the not deletable amenity tag.

**Comment by Barrocas** [comment]
Using what osmand version?

I'm using today's nightly, and the Advanced  'amenity' tag is changed as
soon as any other value is inserted/chosen in the Basic 'POI Type' tag
field (where there's a 'user defined' written on it, while the tag is
blank).

So I see no issue there, it works fine.

..


No dia segunda-feira, 29 de fevereiro de 2016, geoeki <
notifications@github.com> escreveu:

> Following this recent blog entry
> <http://blog.3rik.cc/2016/02/i-love-free-software-how-to-edit-openstreetmap-in-osmand/>
> I tried using OSMand not just for navigating, but also for editing. Upon
> creating a new POI I have to select a name for it as well as a tag. I can
> chose from several tag types (leasure, transportation, natural, etc.) but
> when I check on advanced, the dafault is always 'amenity', no matter which
> tag I chose. I can add additional tags below the amenity tag and it works
> there, but I can't change the default amenity tag.
>
> I asked this on the osm forum and a more experienced user shares this
> issue with the not deletable amenity tag.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osmandapp/Osmand/issues/2294>.
>


-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by stephan75** [comment]
uiuiuiui,

as the quoted "more experienced user" I have to admit that today's nightly build really works, so when you choose something like "craft=carpenter" or similar, then amenity=... disappears.

But this was not in my last nightly build from last week, I swear.

So @geoeki : you will have to wait for next main release of Osmand 2.3 on two or three weeks, or try the nightlybuilds of Osmand on your own.

**Comment by vshcherb** [comment]
Duplicate #2023
