### ISSUE TITLE
Localization: Support plural forms

### ISSUE THREAD

**Issue by SafaAlfulaij** [osmandapp/Osmand#2298]
There are many plural strings in the app that doesn't act like a plural form (check http://developer.android.com/guide/topics/resources/string-resource.html#Plurals).
For example: "days behind" (Which is also not a good practice as the variable is not in the string).
I'll try to get all the problematic strings and list them (and maybe create a PR! :smile: )

**Comment by sonora** [comment]
Please create PR if possible.
