### ISSUE TITLE
Airhorn

### ISSUE THREAD

**Issue by ruudveld** [osmandapp/Osmand#2301]
Hello,

When a waypoint is approached the sound of an airhorn is played.

Code: VoiceRouter.java line 841:
`soundClick = sp.load(settings.getContext().getAssets().openFd("sounds/airhorn.ogg"), 1);`

Could anyone choose a more gentle sound please? Since a voice TexttoSpeech (TTS) message is played, an additional sound may not be necessary.

I have another question: I looked into the sounds folder of Osmand on my Android phone, but I couldn't find the airhorn.ogg. But I do hear the sound of it. Where is the file if the app looks in the sounds folder?

Also I am having difficulties setting up Osmand in Android Studio on a Windows machine. Is there a clear instruction I can follow? In that case I could change it myself.

Thank you,

Ruud

**Comment by Zahnstocher** [comment]
>  I looked into the sounds folder of Osmand on my Android phone, but I couldn't find the airhorn.ogg. But I do hear the sound of it. Where is the file if the app looks in the sounds folder?

assets are inside the APK (assets folder) and are not unpacked to the external Android storage.

**Comment by ruudveld** [comment]
thank you for your answer!

Can you solve the problem please?

**Comment by Phyxion** [comment]
I agree, worst sound ever.

**Comment by sonora** [comment]
If anyone has a better, non-copyrighted sound, could they please post it here? Thx -Hardy

**Comment by vshcherb** [comment]
This one
https://freesound.org/people/Corsica_S/sounds/91926/
 https://freesound.org/people/austin1234575/sounds/213795/ 
https://freesound.org/people/pan14/sounds/263133/
?

**Comment by Phyxion** [comment]
First one is pretty nice.
