### ISSUE TITLE
distorted map details for OSM user

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/Osmand#2303]
If I activate "_OSM mapper assistant_" in the map details, the _fixme_ appear distorted on the map.
sometimes I have to zoom in to level 19 or 20 to reed the _fixme_.

**Example 1:**
![1](http://fs5.directupload.net/images/user/160306/qkjlcm2r.png)

**Example 2:**
![2](http://fs5.directupload.net/images/user/160306/3a3xhost.png)
![2.1](http://fs5.directupload.net/images/user/160306/jgzgt3on.png)

**Comment by vshcherb** [comment]
Not sure if this can be fixed with current text rendering, the only thing suggested to use horizontal text or shields text and not on path draw.

**Comment by xmd5a2** [comment]
Let's try. Fixed.
