### ISSUE TITLE
Problem in viewing Persian character "ی".

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#2304]
In Persian language, there is a problem in viewing character "ی".

It should be connected to the next character in some cases, but it is not. The native speaker says the search results are fine, the error only occurs on map.

For example, a street called "شهید ابراهیم نوری".
![rsz_screenshot_2016-02-28-20-34-49](https://cloud.githubusercontent.com/assets/12711814/13554450/af8ff180-e3b0-11e5-93b0-3691d4bf4e00.jpg)

**Comment by vshcherb** [comment]
Duplicate issue and known issue too.

**Comment by AmZaf** [comment]
Issue fixed in Osmand release 2.3.5 (c.f. #2019 )
