### ISSUE TITLE
Null pointer (?) when stop recording

### ISSUE THREAD

**Issue by pajakgdynia** [osmandapp/Osmand#2305]
Operating voice recording with Camera button doesn't work (partially)
Starting is ok, but when trying to stop "Error during recording occurs: null" (or something like that, message is in Polish in my case). Recording stops, but icon doesn't change the state.

**Comment by vshcherb** [comment]
More information is needed may be screnshot, it is not clear why voice recording doesn't work. 

The icon is a consequence of the recording failure.

**Comment by pajakgdynia** [comment]
Pressing camera button second time causes:
![130885d5-8008-4565-98ff-f654ce4635fe](https://cloud.githubusercontent.com/assets/6771720/13717752/03276bc0-e7e4-11e5-89ce-99993ad42026.png)
Recording is stopped, but the widget is "enabled". Until the widget is pressed, it is impossible to record audio again.

**Comment by crimean** [comment]
@pajakgdynia could you please specify version of android, version of OsmAnd, your device model?
Does the issue appear all the time or not? Would be good to have a log (exception.log)

**Comment by pajakgdynia** [comment]
Android 4.1 (xperia active) and 5.1.1 (xperia z3). OsmAnd 2.1.x and 2.2.4 (from Google Play on updates). Both have same behavior.

**Comment by vshcherb** [comment]
7.2 Beta is already out, it is worth to try cause the issue is not reproducible on latest.
