### ISSUE TITLE
[IMPROVEMENT] Allow to store all sessions automatically

### ISSUE THREAD

**Issue by pajakgdynia** [osmandapp/Osmand#2307]
Option in the plugin to enable storing files automatically (without operator actions). Saving to .gpx file should be done on app exit.

**Comment by xmd5a2** [comment]
GPX saved automatically on program start

**Comment by pajakgdynia** [comment]
I ask about default state: all movements shall be collected by default (no matter when saved, no difference if at start or at quit)
Currently if not started in the dashboard nothing is stored.
