### ISSUE TITLE
[IMPROVEMENT] Hide plugins panels

### ISSUE THREAD

**Issue by pajakgdynia** [osmandapp/Osmand#2308]
All plugins should have option to hide their panels (when in "default" form).
It would be usable when "button" commands are mostly used.
Very often i press wrong button by mistake, what causes not expected results..

**Comment by xmd5a2** [comment]
You can hide most of widgets using "Configure screen" menu

**Comment by vshcherb** [comment]
Not clear what to fix
P.S. by default all plugins disabled
