### ISSUE TITLE
Fix miles/feet display to more conventional

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2309]
Implementation reminder: Miles/feet distances: Distances should be displayed as miles all the way down to (including) 0.25 miles, only below that switch to feet (current switchover limit is 1.0 miles, which is rather unconventional). (Affects displayed values only, voice prompts are fine).

**Comment by vrtareg** [comment]
Hi

Please keep in mind yards too.

Regards, 
Areg

**Comment by vshcherb** [comment]
I guess we are talking something similar to this https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/OsmAndFormatter.java#L107 (Nautical miles don't have feet).

**Comment by vshcherb** [comment]
@sonora Can you please try & test it?

**Comment by sonora** [comment]
I am on a cell phone only with almost no usable internet for a few weeks, but I think I managed to commit this without fatfingering it. Tested ok!

**Comment by sonora** [comment]
Let me re-open this so we do not forget to fix a small side effect (I think in calculateRoundedDistance): We now have a GPX split interval value and a ruler length notch at 0.38 miles for miles/feet, which used to be the 2000 ft notch. Should change that notch to 0.5 mi. (Similarly the former 1000 yd and 500 yd now displays as 0.57 and 0.28 mi, should likely suffice to only have a 0.5 mi notch here, too.

**Comment by sonora** [comment]
PS: I think it is done by using 0.45f instead of 0.9f for cases MILES_AND_FOOTS and MILES_AND_YARDS near the end of calculateRoundedDist, maybe someone can add these 2 cases to that already existing if statement switching from major to minor unit.

**Comment by vshcherb** [comment]
Well, the issue is not that easy to fix. What you are asking is to skip some measurements, but that will have negative effect. I think I understand that 0.5mi and 0.25mi is more preferable than feet/yards. So it requires a little bit thinking in that function.

**Comment by sonora** [comment]
Yes, I noticed, too.. That is why I tried to explicitly fix the 3 exception cases 2000ft, 1000yd, and 500yd.. See my FIXME, all that remains to be done is convert all roundDist in there to meters?

**Comment by vshcherb** [comment]
That's code wrong and I deleted, I need to think a bit :)

**Comment by sonora** [comment]
I have just amended a bit so it is easier to understand. But it looks like it has no effect,not yet sure why.

**Comment by sonora** [comment]
Fixed it. This was the decisive issue https://github.com/osmandapp/Osmand/commit/b2628f2e3514c2458130c9e89fdfbe80321cd113

**Comment by vshcherb** [comment]
Yes, now the fix is correct!
