### ISSUE TITLE
 Osmand includes winter road (piste:type tag) 

### ISSUE THREAD

**Issue by bagage** [osmandapp/Osmand#2310]
When I tried to go from `45.1305, 5.4343` to `45.1434, 5.4798`, OsmAnd told me to take [several Nordic ski pistes](http://www.openstreetmap.org/way/213139523) while according to [the wiki](http://wiki.openstreetmap.org/wiki/Piste_Maps#Type):
> The `piste:type` tag can be used on any existing or new way. Specifically it is very useful for marking a piste that uses an existing way, like for example a track. *This is very useful (e.g. in the Apls) where forestry tracks can be used in Winter for hiking, sledding, skitouring and nordic skiing.* 

![screenshot_20160306-184013](https://cloud.githubusercontent.com/assets/1451988/13555869/fba5bd50-e3cb-11e5-9315-e724f538edfa.png)

Expected route is [actually quite longer](http://brouter.de/brouter-web/#zoom=13&lat=45.0987&lon=5.4148&layer=OpenStreetMap&lonlats=5.434628,45.13059|5.391369,45.066368|5.479903,45.145151&nogos=&profile=trekking&alternativeidx=0&format=geojson).

It looks to me there is no easy way to know if a road / track is usable by car during winter, because it depends if it already has snowed or not. I guess that user has to tell OsmAnd if these routes are open or not. At least, should OsmAnd warn the user `Warning: this route may be closed depending on snow conditions.`? 

I am using Osmand Android version, downloaded from Fdroid. With OsmAnd's in app offline-routing (car profile), but the behavior can be replicated with openstreetmap.org, both with [OSRM](http://www.openstreetmap.org/directions?engine=osrm_car&route=45.1305%2C5.4343%3B45.1434%2C5.4798) and [Mapzen](http://www.openstreetmap.org/directions?engine=mapzen_car&route=45.1305%2C5.4343%3B45.1434%2C5.4798)

**Comment by vshcherb** [comment]
After investigation it is not clear why piste tag should impact the routing. Probably access=destination or something more specific should be used which would change the routing. Also access time restrictions would be better or access = 4 wheel drive.
