### ISSUE TITLE
Sleep / background navigation working well on one Android 4.4.2 device, but not on another 

### ISSUE THREAD

**Issue by lvml** [osmandapp/Osmand#2311]
I'm using Osmand (2.2, source code as of 2016-01-05) on two devices, both of which run Android 4.4.2, and on both of which only (A-)GPS is used as location source: A Samsung "Note 2" and an "Elephone Q".

Foreground navigation runs equally well on both devices, including TTS-voice-announcements that come "at about the right time" on both devices.

But "sleep mode" aka "background" navigation runs well only on the Note 2, while on the Elephone Q, it seems that only very seldom (like every other minute or so) the location is updated, resulting in voice announcements that come far too late, long after a turn should have been taken.

Another symptom is that on the Note 2, when leaving sleep mode (by pressing the key), the GPS indicator shows immediately that there's a GPS lock, while on the Elephone Q, when leaving sleep mode, the GPS indicator always says "0/_n_", indicating no GPS lock, and it takes a second or two until a GPS lock is again established.

So it seems that for whatever reason, GPS positioning is turned of most of the time when the display is off, only on the Elephone Q. 

I have looked for any options regarding GPS activity in sleep mode, but didn't find any, not even in the Elephone Q's comprehensive "engineering mode" (YGPS, invoked via *#*#3646633#*#*).

Any idea what could keep Osmand from keeping GPS "alive" while sleeping?

(I use OsmAnd's in-app offline routing, routing profile bicycle, but that probably isn't involved with the issue.)

**Comment by vshcherb** [comment]
Every phone has own interval to keep GPS alive setting and it depends on Android as well. 
Continuous mode is available only if you select "continuous", even that mode is power safe! Your screen doesn't consume battery. 

We have an algorithm for how long GPS position should be looked up 
https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/NavigationService.java#L129 (shortly serviceError = serviceOffInterval / 5;)
For every 30 minutes it will be around 6  minutes to wait GPS.

I would recommend to use continuous background mode (or simply switch off the screen) it will safe enough power and give stable result

**Comment by lvml** [comment]
By "selecting continous" you mean the choice between "continous" and "every N seconds" as offered when clicking on the "x/n" sattelite display in Osmand? Of course I did use that "continous" all the time. Other than that setting, I did not find a setting when/how to keep GPS alive in any of the "normal" Android 4.2.2 settings menus.

However, I did find an (albeight ugly) workaround: I can cause the Elephone Q to keep GPS running in background by running another App that utilizes the location service: "YGPS". This "YGPS" comes pre-installed with the phone, and can be started by first entering the "engineering mode" (via the phone dial App, "dialing" *#*#3646633#*#* ), then sliding to the "Location" menu, there starting YGPS, and inside YGPS, pushing the menu button, which brings up a two-entry menu with one entry being "enable background GPS [needs restart]". After restarting the phone, YGPS can be started again as written above, and only then GPS positioning keeps running while the screen is switched off - also when Osmand is running, too. And that finally allows to use Osmand navigation with the screen off.

This is of course an ugly workaround, if only because running YGPS wastes additional CPU time.

But the interesting part here is: YGPS is obviously capable of keeping the phone's GPS running continously while in background, while I cannot achieve the same with just Osmand running. I wonder what that special thing YGPS does is.

**Comment by vshcherb** [comment]
True, though it is not clear why do you need to use background service at all.
If you just start navigation and press "Home" button on the phone or turn off the phone, the navigation will continue and messages will be repeated.

**Comment by lvml** [comment]
Like I wrote in the issue description: If I only run Osmand, yes, the navigation will continue with the display turned off, but with such a low frequency of location updates (only every other minute or so) that the voice announcements simply come way too late to be useful.
That's why running "YGPS" in the background helps, then the voice announcements from Osmand come at the same (and useful) times before I need to take a turn.
