### ISSUE TITLE
No road shields displayed on US maps at all

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2314]
Just discovered, may have never worked with new shields yet, not sure. March 6 maps, latest nightly, driving region US, map style Touring (but region and style make no difference, I think)

**Comment by vshcherb** [comment]
We changed the maps and I think the issue is already fixed

**Comment by xmd5a2** [comment]
Please ensure than map is really new. I checked Washington state just now - it's ok

**Comment by xmd5a2** [comment]
No shields should appear with old maps and new Osmand, but older  osmand releases with new maps should display oldstyle shields.

**Comment by sonora** [comment]
Confirmed, new maps work ok. The issue seems a different on: Sometimes when you update one or multiple maps via our update tab, the maps download ok but in the end finally do not get installed, and the old map remains effective. This is hard to ddtect, because we post different dates on different tabs (with no direct comoarison of local vs. update date stamps on any tab. Also: Not 100% reproducible, looks like it primarily happens when multiple updates are selected. Will open a new iissue when I find out what is going on.

**Comment by sonora** [comment]
PS: Also the colors and map dates on our download tabs do not reliably seem updated after update downloads. Only after app restart, it seems.

**Comment by sonora** [comment]
Pity we cold not make it backward-compatible with old road shields and old maps, receive many support calls about missing shields, all are due to old maps, and world basemap ...

**Comment by vshcherb** [comment]
It is backward compatible there is a mistake somewhere we still generate "ref" tag.

**Comment by sonora** [comment]
True, ref seems still created. Fact I that with all old maps including our world basemap we currently seem to not display any road shields at all, which is the initial trap I fell into when opening this issue.
