### ISSUE TITLE
End of Navigation in night-mode-colors

### ISSUE THREAD

**Issue by CJTmmr** [osmandapp/Osmand#2317]
Still in latest nightly's:

The "End of Navigation" menu in night-mode is hard to read: black on dark gray:
All other night-mode panels have white text.
On a clear desktop-screen it is okay; but at night with a dimmed screen not

![2016-03-06 03 16 05](https://cloud.githubusercontent.com/assets/15076257/13648650/08b0dfd2-e63a-11e5-9397-6a1134fd29ab.png)

**Comment by sonora** [comment]
The selection and tick boxes (but not the captions) in most of the sub-menus (section Map rendering and Other map attributes) of our Configure map menu have the same color issue in the dark theme.

**Comment by crimean** [comment]
This is known issue, but not related to current one
