### ISSUE TITLE
Offline routing: "Turn" vs "keep"

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#2321]
Car routing. Osmand 2.2.4

How does Osmand distinguish betwen "turn right" and "keep right"?
I think this is a little confuse because sometimes Osmand says "turn" when should say "keep" or says "keep" when should say "turn"

**Comment by vshcherb** [comment]
That's more a question than a bug description. It differentiate by the turn angle, so it is not very precise method.
