### ISSUE TITLE
Some France maps classified wrong

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2325]
On our All downloads screen we have a few France maps listed under Other maps instead of Europe/France, probably a naming convention error somewhere.

**Comment by xmd5a2** [comment]
Nord-Pas-de-Calais and Picardy was merged to Nord-Pas-de-Calais-Picardie region. https://en.wikipedia.org/wiki/Nord-Pas-de-Calais-Picardie
I have merged them in OsmAnd too. "Other maps" contains these old non-existent regions. We can delete their regular maps but srtm and wiki must be combined (and there are some difficulties with that).

**Comment by vshcherb** [comment]
Will be fixed with new maps.
