### ISSUE TITLE
Navigation does not start after route calculation ready.

### ISSUE THREAD

**Issue by ChrisPHL** [osmandapp/Osmand#2326]
As the title says, the navigatikn does not start when route calculation ready. The track to route does not show up marked and I get no spoken navigation too.
This happens with version 2.2.4 of OSMAnd~, running on CM11 on Samsung Galaxy S2, i9100g.
Running OSMAnd~ version 2.1.1, everything runs just as expected. (Thanks to F-Droid I'm able to downgrade...)
Any further information needed to catch that issue? I'll get it and post it here.

**Comment by vshcherb** [comment]
Did you click the button GO.

**Comment by vshcherb** [comment]
It used to start automatically but we disable it to avoid confusion.

**Comment by ChrisPHL** [comment]
Sorry for the gap, I'm pretty sure that I did click the Go button. I tried to reproduce the issue installing latest version again. Cleared the cache too. Everything works like expected. :-|
