### ISSUE TITLE
Osmand does not find addresses from my contacts

### ISSUE THREAD

**Issue by quelbs** [osmandapp/Osmand#2328]
I select the address of a contact and choose "Osmand" as App to use. Afterwards it says
"Search geo location"
"Searching..."
"Searching address..."

And then there is a toast message "Nothing found" and the contact is shown again.

Other apps do find the addresses on the same phone. Is there a special requirement for the addresses to be found?

**Comment by vshcherb** [comment]
OsmAnd doesn't support free text search yet.

**Comment by n0-1** [comment]
Since you closed this ticket, does that mean there is no intent in working on this?

While Osmand is awesome, it's limited and overly complicated address search is it's weakest point in my opinion. Improving this should have a great impact on user experience.

**Comment by vshcherb** [comment]
There is intent but this is not a "bug". There is a plan to focus first on advanced search and then simply integrate with it. Though search is in progress this will depend on it.

**Comment by n0-1** [comment]
Sure, from one perspective weak searching abilities are not a bug but lack of feature. Regular users though just see that Osmand is offered as application to lookup the address of a contact and that it's not found (although valid) is a bug from their perspective. And finding this ticket to be closed might accidentally communicate the wrong message, hence my provocative question. :)

Anyway, good to see you still have it on your radar.

Thanks, Phil

**Comment by DuncanLithgow** [comment]
I really do this needs to be a priority however the search works in the background. The fact that osmand is non functional if set as my default map lookup is really disappointing.

**Comment by vshcherb** [comment]
First of all, OsmAnd supports much more search inputs since 2016 :-) Second there is another issue to search from any Text selection, hopefully will be released in 3.8
