### ISSUE TITLE
OsmAnd ignores OSM oneway:conditional road settings during offline routing

### ISSUE THREAD

**Issue by SkeLLLa** [osmandapp/Osmand#2333]
The road on OSM have conditional tag.
Example:
```
oneway:conditional yes @ (Mo-Fr 17:00-20:00;PH off);-1 @ (Mo-Fr 07:00-10:00;PH off)
```
So on Mo-Fr in specific hours 2-way road turns into 1-way road.

But OsmAnd ignores that and calculates route like it is usal 2-way road.

Here's a link to that road on OSM: http://www.openstreetmap.org/way/30746240

Navigation profile: car, fastest route enabled.

**Comment by vshcherb** [comment]
I think it will be much better to make safe mapping.
Put oneway=yes, oneway:conditional=no@.... 

Many programs don't support conditions and it will be very important for routing work safer

**Comment by SkeLLLa** [comment]
@vshcherb the thing is that the one way changes it's direction depending on time, if you can see. Then tag oneway=yes is not quiet safe

**Comment by vshcherb** [comment]
It is much safer if road will be blocked for navigation though it could be driven in the night.

So now it is not *safe* if navigation guides you through the road which is oneway. It is totally dangerous.

**Comment by vshcherb** [comment]
Similar to #1794
