### ISSUE TITLE
mute button (for voice guidance) disappeared in 2.3?

### ISSUE THREAD

**Issue by ppenguin** [osmandapp/Osmand#2334]
I installed a self-compiled snapshot (2.3, master branch checkout of March 9th) on my in-car head unit, and couldn't find the button to un-mute voice guidance.

Has it by accident disappeared during optimisation of the routing menu, or am I just not finding it?

It would be logical though, to have mute/unmute readily available on the dash board, transparent status icon or main menu.

As things are now, I'd have to re-install 2.2.4. to unmute my sound (or hack a settings file?).

**Comment by vshcherb** [comment]
It didn't disappear it is still in same place (route configuration -> settings), though the settings screen looks a bit different. https://www.dropbox.com/s/u9fs2b0tai2ha6u/2016-03-13%2021.46.02.png?dl=0

**Comment by ppenguin** [comment]
Hm, my screen looks slightly different:
https://www.dropbox.com/s/mp4v7n031gk5760/Screenshot_2016-03-13-22-59-49.png?dl=0
indeed I can't recall having seen "sound" there before as well, only more detailed settings. With 2.2.4 I used to mute/unmute directly in the navigation interface (if I recall correctly, it was in map->3-lines menu button->right in the title bar (orange) of the appearing menu window)

This screen shot is from my Galaxy S6, but on my in-car head unit it looks pretty much the same...
