### ISSUE TITLE
[IMPROVEMENT] Playing recording layer points

### ISSUE THREAD

**Issue by pajakgdynia** [osmandapp/Osmand#2335]
Recorded points should be played when passing by (in the way similar to POIs, but instead of reading the name.. just file should be played)
At least audio point shall be played in internal player. TTS announcement would be nice (but "rename" should be possible then, listening to the date is useless)
It would be nice if points have direction, only "matching" current direction should be played.

**Comment by sonora** [comment]
No action planned, it seems.
