### ISSUE TITLE
OSM live

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#2336]
Osmand 2.3.0#12205D

When I update the map with OSM live supermarket's phone is not updated.
![screenshot_2016-03-15-00-56-24](https://cloud.githubusercontent.com/assets/12786225/13763826/82c2c3ae-ea49-11e5-979c-292d467e9e51.png)

**Comment by OpenSourceForEver** [comment]
http://www.openstreetmap.org/node/2585758851#map=19/40.72803/-4.01524&layers=D

![screenshot_2016-03-15-01-04-10](https://cloud.githubusercontent.com/assets/12786225/13763908/42372996-ea4a-11e5-9311-ea0798b362a8.png)

**Comment by xmd5a2** [comment]
We can't check it because we don't have old February maps. Change was done 2016.02.11 and it is present in Spain_madrid_europe_16_02_12.obf
```
shop : supermarket Unide Lat 40.72809 Lon -4.015653 id=2585758851  phone=+34 918 56 01 70
```

**Comment by OpenSourceForEver** [comment]
But OSM Live has updated my map on 2016-03-14.

Does OSM Live update tags like phone? I have moved a interior decoration store because it has changed its location and after update with OSM Live the store appears on the new location and on the old location, it is repeated, OSM Live has created the new location but the old location has not been removed.  

Maybe supermarket's phone is repeated too (old phone and new phone).  Is it possible?

**Comment by vshcherb** [comment]
I think that's a known issue today. We are discussing how to fix it. When object changes location to quite far it is still displayed in the old location.

We track that issue separately.
