### ISSUE TITLE
"Turn" vs "Keep"

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#2337]
https://github.com/osmandapp/Osmand/issues/2321

I think there is a bug, the angle is 90º and Osmand says "Keep right" Osmand 2.3.0#12205D

![screenshot_2016-03-15-01-19-51](https://cloud.githubusercontent.com/assets/12786225/13764133/9dcafd6c-ea4c-11e5-811b-b6d05ffa316e.png)
![screenshot_2016-03-15-01-20-52](https://cloud.githubusercontent.com/assets/12786225/13764137/a7c91812-ea4c-11e5-8f77-888b4489e3c8.png)

**Comment by vshcherb** [comment]
It is not clear why routing doesn't go parallel to the visible roads. In case you used osm live, you should use latest night build cause it has an important fix.

**Comment by OpenSourceForEver** [comment]
It is ok with latest night buid. Thank you.
