### ISSUE TITLE
One more problem while parsing whatsapp location

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#2338]
I've found another problem with whatsapp location.
When receiving a location from a contact, like
`https://maps.google.com/maps?q=loc:-21.2088886,-50.4286597 (Contact Name)`
osmand perfectly understand and locates it.

But when we receive a location from somebody who isn't in our contacts (from somebody in a group, for exaple), we receive a location like
`https://maps.google.com/maps?q=loc:-21.2088886,-50.4286597 (‪+55 99 99999-9999)`

osmand interprets it with a `Lon: 0.0` instead `Lon: -50.4286`

Note that there is a small difference here: while in the first case we have the contact name, for the second case we have the phone number.

osmand should also support this second case (with a phone number instead a contact name).

**Comment by GaidamakUA** [comment]
Fixed with commit d159648df5b631786346f879496abbf9b6441480
