### ISSUE TITLE
Night Build - fails to calculate routes

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#2341]
Using night builds after day 2016-03-14, with native routing, in-app Portugal and Spain maps, Osmand fails to calculate routes.

Using a BQ Aquaris E6, running stock Android 4.4.2.

After day 14, I've experienced problems in calculating routes, complaints about errors in calculation, that the calculated route is an empty result, and keeps on recalculating endlessly.
Tested on several random locations and destinations, got the same results.

Installing the night build from day 14, all works fine again.

**Comment by vshcherb** [comment]
Now builds doesn't use osm live for routing, please add exception.log info to description.

**Comment by Barrocas** [comment]
It didn't crash, I have no log. It just recalculates over and over again.

..



No dia quinta-feira, 17 de março de 2016, vshcherb <notifications@github.com>
escreveu:

> Now builds doesn't use osm live for routing, please add exception.log info
> to description.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/osmandapp/Osmand/issues/2341#issuecomment-198024115>
>


-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by vshcherb** [comment]
Do you see any message on the screen? Can you please try latest nightly build.

**Comment by Barrocas** [comment]
![screenshot_2016-03-18-14-33-54](https://cloud.githubusercontent.com/assets/4006691/13880980/ce842948-ed16-11e5-9c68-3ce7e29bc763.png)

![screenshot_2016-03-18-14-34-05](https://cloud.githubusercontent.com/assets/4006691/13880986/e177dacc-ed16-11e5-9c3a-62f7aebab06e.png)

With today's latest night build.
No route is calculated.
Same errors, and it just recalculates endlessly.

**Comment by Barrocas** [comment]
Using v16172M

**Comment by Barrocas** [comment]
With v16107M (from day 14), all works fine, it calculates the same route fast, without any errors.

**Comment by vshcherb** [comment]
Fixed

**Comment by vshcherb** [comment]
The issue was with live maps (if you delete them it would work fine), but it is already fixed so you don't need to delete live maps
