### ISSUE TITLE
Suggestions to POI editing and data collection

### ISSUE THREAD

**Issue by d1g** [osmandapp/Osmand#2345]
When entering time, there should be opening_hours=24/7 checkbox ([every 7 value is 24/7](http://taginfo.openstreetmap.org/keys/opening_hours#values))

When entering time, there should be option to select all 5 or 7 days. Clicking each day individually wastes time. I would use text input instead.

When adding custom tags, there too many name:xx tags - iD handles this by collapsing them into their own sub-group. Nobody would use 20 languages all at once during OsmAnd mapping.

When adding custom tags, I wasn't able quickly to find/enter fixme=_, note=_ values. This is nice to have in field.

Also, I would like ability to link recently taken photos/videos with notes/geodata using custom tags.

**Comment by d1g** [comment]
Probably, 1/60 selector (a minute) is too precise for OSM needs. It is easy to select 58/[59](http://taginfo.openstreetmap.org/api/4/key/values?key=opening_hours&filter=all&lang=en&sortname=count&sortorder=desc&page=1&rp=13&query=59&qtype=)/01/[02](http://taginfo.openstreetmap.org/api/4/key/values?key=opening_hours&filter=all&lang=en&sortname=count&sortorder=desc&page=1&rp=13&query=%3A02&qtype=) minutes. But they are so rare IRL.

http://github.pavie.info/yohours/ snaps to 15 minutes
JOSM opening_hours plugin also snaps to 15 minutes

**Comment by d1g** [comment]
Is it possible to add opening_hours=* to existing POI using OsmAnd?

**Comment by d1g** [comment]
level=* field is missing

**Comment by d1g** [comment]
Questions "Are you sure to save feature without main tag?" are too frequently when I use only unknown tags (to OsmAmd).

I shouldn't be asked more than 5 times per single day with this question...

**Comment by kompowiec** [comment]
> When entering time, there should be option to select all 5 or 7 days. Clicking each day individually wastes time. I would use text input instead.
In my places often some shopping i have that Pn-Fr is eg. 8-18 and in one day is hour early. If anything, it would be better to done extra options on the bottom simply Working days, weekend and marked automatically.

>Also, I would like ability to link recently taken photos/videos with notes/geodata using custom tags.
Good idea.

>Questions "Are you sure to save feature without main tag?" asked too frequently when I use only unknown tags (to OsmAmd). I shouldn't be asked more than 3-5 times per single day/session with this question...
No better give option to turn if off and not some stupid sessions?

**Comment by d1g** [comment]
> extra options on the bottom simply Working days, weekend and marked automatically.

@kompowiec this is roughly what I meant. Missing "24/7" and too sensitive time controls is bigger problem IMO.

> >  Questions "Are you sure to save feature without main tag?" asked too frequently when I use only unknown tags (to OsmAmd). I shouldn't be asked more than 3-5 times per single day/session with this question...

> No better give option to turn if off and not some stupid sessions?

Yes, usually this is node as checkbox in popup menu.

But this principle can be applied to any frequently questioned pop-up and I don't know how many pop-us were in OsmAnd code or if it applicable to them.

**Comment by d1g** [comment]
I wasn't aware of http://osm.cupivan.ru/tags/opening_hours.html

> When entering time, there should be option to select all 5 or 7 days. Clicking each day individually wastes time.

Yes, you have to tick 5/7 times, but otherwise, **it is +/- what I was looking for at android/mobile**

I would like to enter freetext note when I enter opening_hours, as some rules are not trivial.

**Comment by sonora** [comment]
No actions planned, it seems.
