### ISSUE TITLE
disallow routes through highway=... + access=private and barrier=... + access=private

### ISSUE THREAD

**Issue by DinamikGitHub** [osmandapp/Osmand#2347]
I've found, that OsmAnd builds pedestrian routes through highway=service + access=private and through barrier=gate + access=private. I think, it is a mistake: there should be no any route through way or node with access=private.

**Comment by xmd5a2** [comment]
It is common that access=private tag is used incorrectly. Mappers mean that only cars can't pass but adding access=private disallows access for all. Nevertheless, I am inclined to disable routing for pedestrians through access=private.

**Comment by vshcherb** [comment]
Let's disable it.

**Comment by xmd5a2** [comment]
Fixed
https://github.com/osmandapp/OsmAnd-resources/commit/d7b771762ba2505053e6920033b14007844b332c

**Comment by CJTmmr** [comment]
What if destination is on a road, tagged with acces=private?

**Comment by xmd5a2** [comment]
OsmAnd will navigate to closest point near this road but not to road with access=private.

**Comment by DinamikGitHub** [comment]
I've found, that restriction works now only for ways with access=private, not for nodes with access=private (they often put access=private to barriers, for example, barrier=gate).
