### ISSUE TITLE
Steps and elevators not properly recognised

### ISSUE THREAD

**Issue by Posteinwurf** [osmandapp/Osmand#2348]
Osmand seems to disregard two values in my routing.xml for bicycles: 

I have set the "obstacle" values for "elevator" and "steps" very high (for example 55 or even 999), but Osmand will still not avoid routes with elevators and steps. 

Any ideas? Thanks everyone in advance

Malte

P.S.: Excluding steps entirely does work. But I want to set a value instead, under "point attribute = obstacle"

**Comment by vshcherb** [comment]
You can put it here https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#L450.
Please don't forget that tags should be added to the routing section https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml

**Comment by Posteinwurf** [comment]
I know that I can exclude steps entirely (as an option that users can choose). That works well! 

But I also want some seconds penalty for steps (it is necessary for the users that accept steps!). This does not seem to work. Why?
