### ISSUE TITLE
Provide "Slope" raster overlay (similar to current Hillshades)

### ISSUE THREAD

**Issue by poidi** [osmandapp/Osmand#2349]
hi there,

this is a featrue request for the contour-lines. it would be great to not nly have the hillshading in black gradients, but to color code the steepnes of the slope like in common ski touring overlays:
<30 no color
<35 light orange
<40 darker orange

> 40 red 

look for an example:
http://s0.outdooractive.com/map/xGradient/14/8657/5755.png

this would help to check for the risks of avalanches whil ski touring!

thanks for the consideration.

**Comment by vshcherb** [comment]
I think we can use GDAL (the tool we use to generate SRTM maps), though that could be only raster layer same as Hillshade maps

**Comment by miramikes** [comment]
Hi, this feature would be highly appreciated especially for ski mountaineering.
Is there any progress or is it intended?
mira

**Comment by dmpr0** [comment]
Hello, @miramikes! 
You can try Slope maps right now in current nightly builds https://download.osmand.net/latest-night-build/OsmAnd-default.apk, we combine Hillshade and Slope menu in Configure Map — Terrain.

**Comment by miramikes** [comment]
Hi there,
I just tried this feature in nightly OsmAnd and it looks simply great !!!
Will be this included in next release?
Or when it can be expected?

best regards

mira

**Comment by dmpr0** [comment]
@miramikes Yes, it will be in the next 3.7 release, we are planning to publish it in the middle of April.

**Comment by aceman444** [comment]
@vshcherb isn't this already implemented in current OsmAnd released and can this be closed?

**Comment by cycore** [comment]
actually, the way it is implemented right now doesn't fullfil the use case at all. it is impossible to distinguish between slopes <30° and >=30°. and that's the relevant part for determining avalanche danger
