### ISSUE TITLE
contour lines - denseness dependent on zoom level

### ISSUE THREAD

**Issue by poidi** [osmandapp/Osmand#2350]
when you activate the contour lines, you cannot use ist in higher zoom levels (apart from setting the minimum level of zoom)

it would be great to have the amount of contourlines dependend on the zoom factor.

i.e.:
zoom 11: only show contourlines vor 1000s of meter
zoom 12: only show contourlines vor 500s of meter
zoom 13: only show contourlines vor 200s of meter
zoom 14: show it for 100
zoom 15: 50
zoom 16: 10

**Comment by vshcherb** [comment]
It is quite hard to implement with today tools and rendering engine.

**Comment by sonora** [comment]
No action planned.

**Comment by DFyson** [comment]
I was also thinking how nice it would be to have this. It can get quite slow and resource intensive trying to render so many contours not to mention cluttered.
Is the contour lines file not just another vector map file? Thus, using filters, can't you pick and choose which vectors are rendered?

**Comment by sonora** [comment]
Please note that dense countour lines do have a purpose! They visulalize steep grades, cliffs, mesas, or canyons, and usually only a thick density of lines makes potential canyon exit routes (or possible mountain descends in gullies) rather visible (something I can sadly claim has saved my life on more than one occasion). So if we implemented a feature with customized spacing, I would certainly never use it. The coutour lines for me are not optical beauty enhancers for the map, that's what we have the Hillshade files for. For countour lines I recommend you develop a habit and experience to derive slope via fixed vertical spacing without having to consider what customization setting you are on ...

**Comment by DFyson** [comment]
I'm more about the practicality than the eye candy. I too like the density of contour lines in some situations for the reason you mention and I find the combination of contour lines with good hillshade work well together for visualizing the topography. I also determine the slope by measuring the horizontal distance between lines, and consistency is good for that. I've also been experimenting with slope shading. But in other situations I like to be aware of the general elevation trends when zoomed out, without too much contour line clutter and without taking too long to render. It also makes it easier to follow the contours. For [example](https://cloud.githubusercontent.com/assets/12941728/24068983/be0437cc-0b72-11e7-9493-dc0e75001410.png) at zoom 13 in mountains, I find the contour lines to be much too dense for most practical purposes. Infact I've never come across a topo map with such dense contour lines. But you can easily pick out the steep bits. So I think it just comes down to two use cases... which can only mean more options! For me I think being able to turn on/off 10m between the 100m would be fine.
Is the rendering of the contour lines dictated by some *.render.xml? I'd be curious to play around..

**Comment by sonora** [comment]
Point taken. Yes, it may be easiest to just go to the rendering sub-folder of the osmand data folder on your device, find the Touring-view render xml and create a copy there to edit
 I should have a section in there about countour lines. I may have commented it out at some point in favor of the default.render mechanism. You can uncomment there and play with the lines for the different countour lines, to see what can be done and how it looks (and/or likewise check default.render directly)

**Comment by xmd5a2** [comment]
Solution mentioned in first post will not work for plains. There will be so few contour lines. At that moment some contour types are not rendered through all zooms. Ideally, number of contour lines to render at one map screen should be limited but it is hard to implement. So I added "Contour lines density" option to Topo style which allows to manually select density.
