### ISSUE TITLE
[Improvement] Rendering of Tanning Salon

### ISSUE THREAD

**Issue by CJTmmr** [osmandapp/Osmand#2352]
Request to add "leisure=tanning_salon" to POI and rendering

http://wiki.openstreetmap.org/wiki/Tag:leisure%3Dtanning_salon

Proposed icon: simple sun-symbol, like:
![image](https://cloud.githubusercontent.com/assets/15076257/13932899/b77c075c-efaa-11e5-932c-445ad8e99d79.png)

**Comment by naoliv** [comment]
I don't think it's good to include/render a not yet accepted tag (nor discussed, it seems).

**Comment by xmd5a2** [comment]
There is also a similar tag
https://taginfo.openstreetmap.org/search?q=amenity%3Dsolarium

**Comment by vshcherb** [comment]
May be too much details on the map and unclear for non-experienced users, please be careful.
