### ISSUE TITLE
The routing algorithm adds spurious detours to the route

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2354]
Using OSmAnd 2.3.0#16193M
Profile: Car
Algorithm: OsmAnd's in-app offline routing
Routing option: fastest (The "shortest" check box is unselected)

Route in Bangalore City
Start point:12.98172,77.60159
End point:12.92408,77.66969

Both these points are already saved in OsmAnd as Favorites.

When I set the route yesterday, I saw an extra loop in the route that adds ~250m to the route.
But I re-created the exact same route today, and it turned out to be fine. 

I have captured both screenshots and compared them side by side. 
The loop was added near 12.92449,77.65044 
 
[RoutingDetours.zip](https://github.com/osmandapp/Osmand/files/183544/RoutingDetours.zip)

**Comment by raindropsfromsky** [comment]
Yesterday once again I faced a similar -but worse- problem: While driving in familiar areas of the city, I check out how the routing behaves. 

For this, I have saved my routing destinations as Favorites. This allows me to quickly set my route to match my daily journey. 

Yesterday the route was et well initially, but in the last 500 m, OsmAnd recalculated the route (even when I had NOT deviated from the route), and added a worthless loop to the journey. (Just take a wrong turn, go ~200m, take a U turn and return to the spot, and then continue on the desired route.) 

When I ignored this loop and drove in the correct direction, OsmAnd recalculated the route again and routed me wrongly AGAIN! This time, the shortest route was to simply take a left turn after 150m and drive a few meters to arrive at my destination. Instead, OsmAnd asked me to drive straight past this turn, take the next left turn (on a parallel road), and then take a left turn again to come back to the first road, and take left again.

I can provide the screenshots if needed.

**Comment by raindropsfromsky** [comment]
On second thoughts, I'd better provide the details!
[Spurious loops in route.zip](https://github.com/osmandapp/Osmand/files/203874/Spurious.loops.in.route.zip)

**Comment by raindropsfromsky** [comment]
Yesterday I tried the same journey once again (same pair of favorites as start+end points).
I again faced the same issue with OsmAnd 2.3.0#16193M. (It startea good route, but sudd with
But this time the extra loop was different.

**Comment by polarbearing** [comment]
why did you close the issue, as it is not solved? I would have similar problems to report. However it might be easier to attach screenshots directly and not wrap them in pdfs in zips.
