### ISSUE TITLE
In compass mode, OsmAnd fails to rotate the map sometimes

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2355]
Using OSmAnd 2.3.0#16193M
Profile: Car
Algorithm: OsmAnd's in-app offline routing
Routing option: fastest (The "shortest" check box is unselected)

Route in Bangalore City
Start point:12.98172,77.60159
End point:12.92408,77.66969

Both these points are already saved in OsmAnd as Favorites.

As the attached file shows, when I turn, the light blue pie segment rotates to show my bearing correctly. But the map is not rotated to match the surrounding. (BUG)

But today I repeated the same experiment, and the map rotates correctly.

The only difference I see is the **Navigation** button: Yesterday (in fail condition), it appeared like a "Direction arrow" sign. Today (in ok condition) it appears like a blue arrow ("Go" icon).

[CompassModeFails.zip](https://github.com/osmandapp/Osmand/files/183566/CompassModeFails.zip)

**Comment by sonora** [comment]
Deprecated.
