### ISSUE TITLE
BUGLET: The notification says "g p s signal lost", and does not use a caution icon

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2356]
Using OSmAnd 2.3.0#16193M

This is a buglet: The notification says "g p s signal lost" instead of "GPS signal lost"
(note capitalization and spaces)

Also, this notification shows a vaguely shaped icon (white on gray) that look like a clipboard. 
It fails to alert the driver. Since this is a "Caution" state, this icon should be a yellow triangle with a [red exclamation mark](http://www.clipartbest.com/clipart-ycogyBK9i).

**Comment by sonora** [comment]
Narayan, the blanks between the letters have been inserted to get as many as possible TTS engines to speak this as 3 letters, rather than trying to speak it as a word. It works ok on my test devices, what is the issue you observe?

**Comment by raindropsfromsky** [comment]
Well, my problem is not with the TTS announcement. Rather, it is with the way the text looks: It is not recognizable at a glance. 

Compare **g p s** with **GPS**. 

BTW why small letters are used?? That has no impact on the pronunciation!

The TTS issue would be there in a very few languages. The translators should take care to separate the letters in that particular language. Thus in majority languages, it should be "GPS".

**Comment by sonora** [comment]
Strange, I find no occurrence of "g p s" in our entire code outside our voice prompt files which are used to produce the audio output. Can you provide a screenshot where you see this?

**Comment by raindropsfromsky** [comment]
I think the code has changed since I reported that bug, because now I see a different notification.

Earlier the icon looked like a clipboard outline (or a camera outline) (one large square and a smaller square on top of it).

Now the icon looks like a donut with a small beak at bottom.
The text also has changed.

Even the new notification is totally ineffective:
**Running in background (navigation). GPS...**

Here's why:
 1. The first sentence is not needed: When the device is locked, it does not matter if the app is running in background or in foreground.
 2. The second sentence breaks off after "GPS...". So the user never knows what it tries to say! What is he supposed to do??
 3. If I tap on the notification, my phone says "tap again to open" (at bottom of the screen).
     But if I tap the notification once again, the phone shows me the dot grid, and asks me to draw my screen unlock pattern.
     I expect OsmAnd to bypass the lock and come up directly (like the Camera app). In fact, its audio/video/note functions should work even when the screen is locked.

**Comment by raindropsfromsky** [comment]
BTW the notification is not read out, so the TTS issue with "GPS" cannot be an issue. 
So why is the "g p s" separation needed?

**Comment by sonora** [comment]
Narayan, regarding the Android system notification: Unfortunately in many Android versions the text does not seem to line-break, so on very small screens the info about the GPS wakeup interval in use may only be visible in landscape mode.

Regarding the original issue with "g p s":  Are you saying the issue has disappeared and we can close this?   Thx - Hardy

**Comment by raindropsfromsky** [comment]
Yes, but the change has given rise to other problems I described.
Should I raise a separate bug for that?

**Comment by sonora** [comment]
It has gotten kinda convoluted here, let me close this. Please start a fresh analysis with a new build and document any new findings from the start in a new issue.
