### ISSUE TITLE
Speed units don't respect settings

### ISSUE THREAD

**Issue by mattok** [osmandapp/Osmand#2358]
This affects OsmAnd+ Android app version 2.2.4. The road system in Cyprus is based on the UK's (eg: driving on left) except that they have adopted km and km/h for distances and speeds, whereas in the UK miles and miles/hour are used. I recently used OsmAnd in Cyprus. I first set the driving region as UK, India, etc. Doing this sneakily changes the units to miles/feet without warning you. To correct this, I went to the units setting and changed it to kilometres/metres. Despite the driving region and units now being correct for Cyprus, the speeds and speed limits displayed on the map view are still in miles/hour, rather than kilometres per hour.

I'd be grateful if this could be fixed. Thank you.

**Comment by mattok** [comment]
Sorry.. I was trying to open a new issue using the mobile view if the website. It asked me for a title only, but I couldn't see where to enter the main body of the issue... So I switch to the desktop version and find the text above. I guess I'll just close this. Apologies.

**Comment by mattok** [comment]
I've fixed the text and reopened this. Thanks.

**Comment by vshcherb** [comment]
Can't reproduce it. After I change unit of measure the speed settings were correctly changed. Please keep in mind that speed settings could be also modified in Navigation settings, once it was modified it won't switch back.

**Comment by mattok** [comment]
I think I understand what's going on. Under the global app settings it says:

Unit of measure
Change units of length and and speed

However, this description is misleading. I naturally expected this to also affect the way in which speeds are displayed/reported (eg: miles per hour vs km per hour), but it doesn't affect the way speeds are displayed at all. The setting only changes the way units used to display distances.

The units used to display speeds are controlled by a Navigation parameter, dependent in the mode of transport (car, bicycle, foot). The setting is:

Speed measurement
Define speed measurement system

This controls the units used when displaying/reporting speeds, irrespective of the global "unit of measure" setting.

To help prevent other people from falling into the same traps as me, I would recommend the following changes:

1) The description of the global "unit of measure setting" should be corrected (or at least improved) to indicate that it affects how distances are displayed, but not speeds.

2) If, when changing the "unit of measure" setting, this results in units that are inconsistent with those used to display speeds via any of the "speed measurement" settings, then the application should warn the user about it so that they have an opportunity to correct it (if they want), before they set off. (Note that it generally only becomes apparent that the units of speed are incorrect once you have already set off and are moving.)

3) If you change the driving region, then Osmand may surreptitiously change the unit of measure too. If it does this, then it should warn you about it.

4) Due to point 3), Osmand can end up needlessly changing your settings from displaying yards to displaying feet without warning you. Being told that there are 2841 feet until the next junction is silly because it involves far too much precision to be useful. By the time it has been spoken in it's entirety it's generally no longer relevant! My recommendation would be to make miles/yards the default for the UK driving region.

You may wish to separate these related issues into separate bug reports.

Thank you.

**Comment by vshcherb** [comment]
To 4) we started refactoring to display and talk "half of a mile", "quarter of a mile", so it is easier to understand.

**Comment by mattok** [comment]
That would be a welcome improvement. Thank you.

**Comment by sonora** [comment]
mattok, I am not sure of any portion of this issue is still open using the latest nightlies, can you please check and specify?

In general. I have to say that when travelling I only use the "Driving region" setting, and am quite satisfied with the way it does things and changes settings. I am not sure if it is worth to implement lots of warnings etc. about he other settings which most people would probably not use a lot anyway.

Also: After any changes t the settings it makes sense to kill OsmAnd and restart the app, as only then all display settings are reliably observed.

Thx- Hardy

**Comment by mattok** [comment]
> mattok, I am not sure of any portion of this issue is still open using the latest nightlies, can you please check and specify?

I tried downloading the latest nightly build from [http://download.osmand.net/latest-night-build/](http://download.osmand.net/latest-night-build/), but I just get a "not installed" message. My understanding is that, excepting vshcherb's comments on a separate issue relevant to my point 4) above, no-one has attempted to make any code changes associated with this issue.

> In general. I have to say that when travelling I only use the "Driving region" setting, and am quite satisfied with the way it does things and changes settings. I am not sure if it is worth to implement lots of warnings etc. about he other settings which most people would probably not use a lot anyway.

Regarding point 3) above, I suspect that you've been lucky that you have only travelled in countries where the default behaviour of osmand works: Setting the "driving region" will (without any warning or notification) change the units of measure - but it doesn't always get it right though. In fact, depending on how you look at it, it can mostly get it wrong. The driving region setting provides several possibilities:

- Europe and Asia
- United States
- Canada
- UK, India, Australia & Others
- Japan

I could be wrong, but the UK, India, Australia & Others setting is presumably intended for all left-hand traffic systems that aren't Japan, most of which will probably have been based at one time in the past on the UK system. This includes Cyprus, as in my original post. According to [Wikipedia](https://en.wikipedia.org/wiki/Right-_and_left-hand_traffic), this would therefore be used for the countries listed below. Now, selecting this option within osmand automatically changes the units of measure to Miles/feet. In the list below, I have used [information from Wikipedia](https://en.wikipedia.org/wiki/Miles_per_hour) to embolden all of those countries that use miles per hour as units of speed (and by implication miles for units of distance, although this could be wrong in one or two cases below): 

- Anguilla
- **Antigua and Barbuda**
- Australia
- **Bahamas**
- Bangladesh
- Barbados
- Bermuda
- Bhutan
- Botswana
- Brunei
- Cayman Islands
- Christmas Island
- Cocos Islands
- Cook Islands
- Cyprus
- **Dominica**
- East Timor
- **Falkland Islands**
- Fiji
- **Grenada**
- Guernsey
- Guyana
- Hong Kong
- India
- Indonesia
- Ireland
- Isle of Man
- Jamaica
- Jersey
- Kenya
- Kiribati
- Lesotho
- Macau
- Malawi
- Malaysia
- Maldives
- Malta
- Mauritius
- Montserrat
- Mozambique
- Namibia (1918)
- Nauru (1918)
- Nepal
- New Zealand
- Niue
- Norfolk Island
- Pakistan
- Papua New Guinea
- Pitcairn Islands
- **Saint Helena, Ascension and Tristan da Cunha**
- **Saint Kitts and Nevis**
- **Saint Lucia**
- **Saint Vincent and the Grenadines**
- **Samoa (2009)**
- Seychelles
- Singapore
- Solomon Islands
- South Africa
- Sri Lanka
- Suriname
- Swaziland
- Tanzania
- Thailand
- Tokelau
- Tonga
- Trinidad and Tobago
- **Turks and Caicos Islands**
- Tuvalu
- Uganda
- **United Kingdom**
- **British Virgin Islands**
- **U.S. Virgin Islands**
- Zambia
- Zimbabwe

So, osmand will be configured incorrectly and require manual intervention for most left hand traffic systems (all those not emboldened above), including Australia which is one of the ones in the text for the setting. To help users of osmand get it configured correctly, I suggest one or both of the following is implemented:

- The text associated with each driving region option should be expanded to state what units of measure will be set, so that the user will know if they need to manually change them.
- Alternatively (or in addition), when the driving region is changed, if (and only if) this results in a change of the units of measure, a small box could appear for a few seconds saying what the new units of measure are.

Clearly, the first of these options would be trivial to implement. If implemented as suggested, the message box in the second option would only appear when it resulted in a change of unit of measure - which means it wouldn't appear for most people most of the time. It would only appear when it would be likely to contain useful information and so wouldn't be an annoyance.

Regarding the other points I made above....

Regarding point 1). If my assertion that the units of measure setting does not affect the display of speeds - only distances - is confirmed, then this bug should be trivial to fix. It's just the description of the setting that needs adjusting.

Regarding point 2). This is an important warning that will only be shown to people for whom the setting they have just made wont be applied because it is being overridden elsewhere in the application. For most people, most of the time, this warning wont appear. It will only appear for people who are at risk of getting caught out in exactly the same way as I did, and so it will help prevent bug reports like these in future.

> Also: After any changes t the settings it makes sense to kill OsmAnd and restart the app, as only then all display settings are reliably observed.

I'm not sure I understand what you are suggesting here. Are you suggesting that the user should know that every time they change a setting they should kill and restart the app for it to work properly. If it's the latter, I think it is unreasonable for any user to know or do this. Firstly, no other Android app I know requires this, and so it would not be expected. Secondly, how exactly do you 'restart an app' in Android? Do you mean having to find it in the system settings, and then force the process and any cached versions of it to be killed? Can't the app transparently and automatically do a reboot whenever a setting is changed that requires such a reboot?

Thanks.

**Comment by homersimpsons** [comment]
An other option could be to convert units to match those chosen (m/h <-> km/h <-> m/s)

**Comment by sonora** [comment]
I wonder if we could solve most of this issue by a simple text change in the Driving region selection menu, like by going from today's
- "Driving region: United States"

to displaying something like something like
- "Driving region: Right-hand driving, miles and feet (e.g. United States)", or
- "Driving region: Left-hand driving, kilometers and meters (e.g. Japan)",

i.e. we explicitly state the characteristics and units which would be selected, and mention the major countries as examples?

**Comment by homersimpsons** [comment]
Yes, it could be easier.
The best would remain, as @mattok said, to have this settings dinamyc (change to match the currenct map position) or be able to choose one type manually to already get the same measure.

**Comment by mattok** [comment]
@homersimpsons Dynamically choosing the driving region and units of measure based on the map position isn't something I suggested. On the face of it it sounds like a sensible long term goal... but it also signs like a major change that would take a lot of effort and therefore time to implement, potentially for not much gain. It also sounds like it would need quite a bit of thought in terms of how best to implement it. For example, if you were using Osmand for walking of cycling, not driving, then you might not want Osmand automatically changing the units if measure based in your map position.

@sonara The simple idea of updating the text sounds like a great and simple idea to me. I tried to suggest the same above. The particular examples you gave might need tweaking though... My understanding it's that Japan's left hand traffic system is special because it is primarily based on the American system, whereas most others are based on the UK system. I imagine Osmand must treats the two differently (although I'm no expert so I can't be sure.) The text should somehow convey that difference if so.

Thinking about it, it might also be convenient to expand the range of driving region options by one if it's easy to do do, so that you could choose, for example,

- "UK based, left hand traffic system, miles and feet (eg: UK, Bahamas)",
- "UK based, left hand traffic system, kilometres and metres (eg: Australia, Cyprus...)" (new), or
- "US based, left hand traffic system, kilometers and metres (eg: Japan)"

(Note: I have used the British English spelling of metres in my examples, but presumably this would be locale dependent.)

**Comment by vrtareg** [comment]
Hi

What about the UK miles/yards option? ?

Regards,
Areg

**Comment by mattok** [comment]
Personally, I'd be happy for both
- "UK based, left hand traffic system, miles and feet (eg: UK, Bahamas)", and
- "UK based, left hand traffic system, miles and yards (eg: UK, Bahamas)"
to appear in the list of options. I don't know whether it would make the list too long and unwieldy though... If people would prefer to restrict it to just one of the two variants above, I would personally prefer miles and yards at the moment. (I find it hard to judge distances to junctions expressed large numbers of feet.) However, vshcherb mentioned above that they have started refactoring to display and talk "half of a mile", "quarter of a mile", etc. on the approach to junctions (which will be). So, once that has been done, my preference for one or the other disappears.

**Comment by mattok** [comment]
Personally, I'd be happy for both
- "UK based, left hand traffic system, miles and feet (eg: UK, Bahamas)", and
- "UK based, left hand traffic system, miles and yards (eg: UK, Bahamas)"
to appear in the list of options. I don't know whether it would make the list too long and unwieldy though... If people would prefer to restrict it to just one of the two variants above, I would personally prefer miles and yards at the moment. (I find it hard to judge distances to junctions expressed large numbers of feet.) However, vshcherb mentioned above that they have started refactoring to display and talk "half of a mile", "quarter of a mile", etc. on the approach to junctions (which will be). So, once that has been done, my preference for one or the other disappears.

**Comment by mattok** [comment]
Personally, I'd be happy for both
- "UK based, left hand traffic system, miles and feet (eg: UK, Bahamas)", and
- "UK based, left hand traffic system, miles and yards (eg: UK, Bahamas)"
to appear in the list of options. I don't know whether it would make the list too long and unwieldy though... If people would prefer to restrict it to just one of the two variants above, I would personally prefer miles and yards at the moment. (I find it hard to judge distances to junctions expressed large numbers of feet.) However, vshcherb mentioned above that they have started refactoring to display and talk "half of a mile", "quarter of a mile", etc. on the approach to junctions (which will be). So, once that has been done, my preference for one or the other disappears.

**Comment by mattok** [comment]
There are issues to be addressed in this thread, but I suspect they are at risk of getting overlooked due to the issue being marked as closed. Please could someone with the powers to do so reopen it? (It doesn't look like I can do this myself.) Thank you.
