### ISSUE TITLE
Intermediate destination is not routed on residential ways

### ISSUE THREAD

**Issue by thuryn** [osmandapp/Osmand#2362]
Correct cases:
1) only one destination point is on residential street - way is routed directly to the destination point - OK
2) destination is outside of residential street - way is not routed throught residential street - OK
Incorrect case:
3) There are two destinations. First stop destination is on residential street, the second destination is outside. Osmand navigate to the nearest point to the residential street, but don't navigate to the first destination.

![residentialok](https://cloud.githubusercontent.com/assets/11028346/14002027/8fdcd51e-f149-11e5-9417-d69de2e9404d.png)
![residentialnok](https://cloud.githubusercontent.com/assets/11028346/14002043/99c6ddea-f149-11e5-820b-d1cd755be4b1.png)

**Comment by xmd5a2** [comment]
Can't reproduce https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot%20from%202016-05-04%2012%3A06%3A21.png
