### ISSUE TITLE
POI - Opening Hours - Time span

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#2364]
What version of OsmAnd are you using, on what device and Android/iOS version?
2.3.0#16214M, Bq Aquaris E6, Android 4.4.2

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?
Latest Portugal + Spain Offline maps + live Updates

..

When entering the opening hours time span, if we scroll the available hours / minutes, it works ok.

But if we tap the numbers to manually type and enter the value, like for example 08:30h, when clicking 'save', it changes the inserted value to 08:00h.

**Comment by GaidamakUA** [comment]
@Barrocas Can you please provide exact string you typing in.
As I understood:
1. Open "Advanced tab"
2. Type in some string
3. Press save.
4. Open created POI.
Expected result: 08:30
Actual result: 08:00

**Comment by Barrocas** [comment]
Hi, 
no, the issue is not in the Advanced tab, but in the Basic tab, in Opening Hours.

To reproduce do this:
Choose a POI
open context menu
Modify POI
In the Basic mode, add Opening_hours
Select any days

Now for the Hours/Minutes, if you scroll up/down to choose, and press 'save', it works fine.

But if you click on the hours/minutes to change the value by typing, and then press 'save', it doesn't work.

It only keeps the typed values if you click on the other field.

for example, you type 12h and click on the minutes to add 30min, press save, the result is 12:00

Now click the hours again and type it to 14h, click minutes to set it to 15min, click on the hours again, press save, and now it works, the result is 14:15

Pressing 'save' does not store the last inserted value.
Only clicking the other field stores it, before pressing 'save'

**Comment by Barrocas** [comment]
Same for the hours, if the time is 12:00 and you type 11:00 and press 'save', it remains 12:00

**Comment by xmd5a2** [comment]
Personally I can't type anything in time fields at Basic tab. Dialog with clock appears.

**Comment by Barrocas** [comment]
Choose any editable POI
Modify POI
Scroll down in the Basic tab
click 'Add Opening Hours'
set the weekdays

Now for the opening_hours, if you have Android 5.0, you're right, you
get the 'Dialog with clock'.

But on devices before Android 5.0, like the one I have with Android
4.4.2, you get a scollable 'hours:minutes', that can also be clicked
to manually enter the value, and there's the catch.

For example, to set (or change) the closing time from 18:00 to 18:30

Click on the 'minutes' and a numpad appears to enter the value.

Type 30 (minutes), and if we press the 'save' button right next to the
'minutes', what we entered is ignored, the time remains 18:00

It only works if we type the value in the numpad, and press the lower
right numpad button 'done' (may be some other word in english), and
only then press 'save'.
Time is then set to 18:30 as intended.

-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by GaidamakUA** [comment]
Took me some time to understand what's wrong. Fixed bu commit https://github.com/osmandapp/Osmand/commit/e67d2ec88c1f847698550cbec3d9bd597dfa51b1
