### ISSUE TITLE
Request: My Places - Favorites - categories (opened vs closed)

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#2366]
When going to 'My Places - Favorites', some categories are 'open' (if they have less favorites), and some are 'closed' (if they have more favorites).

This is confusing.
It would be easier for the user if all categories were inicially closed, and only opened when selected.

Please read comments here:
https://groups.google.com/forum/m/#!msg/osmand/xj8oZNAvs3U/H5OAGDjiBQAJ

**Comment by mattok** [comment]
This has been annoying me for some time too. Small categories that I grouped for rarely used trips would always be expanded by default, and I could never understand why.

I think a better solution than the one proposed above would be for it to simply remember whatever state you put it in.

Categories are generally used to group related locations. Personally, I use it to group locations in different countries I visit, and to separate personal favorites from work favorites. The point is, once I'm in a category, I tend to want to keep choosing others from that category for a while. Therefore, keeping it open would be the most convenient.

**Comment by Barrocas** [comment]
Good point, totally agree with mattok.

**Comment by Barrocas** [comment]
Working perfectly, very nice! 
Great work, Thanks!

**Comment by mattok** [comment]
Thank you for implementing this so promptly. I haven't been able to get a nightly installed, so I look forward to trying it out in the next release.
