### ISSUE TITLE
Incomplet search for cemeteries/Recherche cimetière incomplète

### ISSUE THREAD

**Issue by Al-Hun** [osmandapp/Osmand#2367]
I searched for a known cemetery, using the cemetery POI "search around", and I was surprised not to find its position, but surprised too of the few answers. It seems that only amenity=grave_yard is used, despite the more common tag is landuse=cemetery (when distinct of cult place).

La recherche d'un cimetière connu en utilisant le "rechercher autour" des POI "Cimetière", non seulement a échoué mais rapporté très peu de réponses. Il semblerait que seuls les objets tagués amenity=grave_yard soient recherchés, alors que landuse=cemetery, qui est plus commun (cimetière à l'écart du lieu de culte), est ignoré.

Alain.

**Comment by xmd5a2** [comment]
There are two tags in osm with different meaning - amenity=grave_yard and landuse=cemetery. In french translation their strings was translated identically: "Cimetière". You can see two poi types when you type in search.

**Comment by Al-Hun** [comment]
Hello,
I tried again but on my device, as you can see on the screen copy, I have only one proposal of POI. And this one is for the grave_yard. If I proceed to search by name it's ok and both of them appear with the same icon in the results' list. On the map too the rendering is identical.
The problem is that the landuse=cemetery is widely more often encountered (in France ?) since grave yards close to churches have been deplaced for the majority because of salubrity.
My version is 2.1.1
Thanks for your attention and developpments,Hope my poor english is not too difficult to understand  :D

Alain.


Envoyé depuis Yahoo Mail pour Android

**Comment by xmd5a2** [comment]
I don't see any screenshots.

**Comment by Al-Hun** [comment]
It was in the mail reply. Seems not kept on the page.
Here is...
![screenshot_2016-03-25-10-28-39](https://cloud.githubusercontent.com/assets/14762270/14043815/b9a6fc40-f288-11e5-8fd9-80057a02f831.jpg)

**Comment by xmd5a2** [comment]
Please update. 2.1.1 is very old release.

**Comment by Al-Hun** [comment]
I didn't have realized I wasn't with the last version. It seems that there was a pb with the automatic update. Many thanks to have pointed this stupid error : no more pb with my search, and more a lot of improvments I was waiting for ! The return of the search for all POI near location, better UI to add POI...

All is fine   :)))
Thanks again

**Comment by xmd5a2** [comment]
Glad to hear that!
