### ISSUE TITLE
[Suggestion] Option to use GPX files from other paths

### ISSUE THREAD

**Issue by p-p-s** [osmandapp/Osmand#2368]
Hi, I am using OsmAnd+ on non-rooted Android 4.4. Hence, I cannot move GPX files to <ext SD>/Android/data/net.osmand.plus/files/tracks on the device or using an access method from a PC. I always power off the device, remove the SD card, insert it into a USB adapter and plug this into a PC to move GPX files to the path, then reverse everything. This is cumbersome. Could you add a new option to enter alternative paths from where the app would read GPX files? Sure, that would work only read-only. But this way I could move tracks onto the device simply by syncronizition using anything like box.com or dropbox. Or I could download tracks in other apps like Bikemap or GPS-Tracks, but use them in OsmAnd+.

**Comment by vshcherb** [comment]
Another way is to open GPX file via File Manager and select OsmAnd as a target app.
