### ISSUE TITLE
Distorted offline map rendering near German-French border

### ISSUE THREAD

**Issue by RalfJung** [osmandapp/Osmand#2370]
Offline map rendering near borders is rather distorted: Some streets are not connected properly. This is best demonstrated by screenshots:

![screenshot_2016-03-26-13-22-25](https://cloud.githubusercontent.com/assets/330628/14060042/d3f45b64-f356-11e5-9ea4-f5a8a3dd5c6c.png)
This is roughly <https://www.openstreetmap.org/#map=17/49.20217/6.96757>. You can see that the yellow main street is not connected properly.

![screenshot_2016-03-26-13-22-43](https://cloud.githubusercontent.com/assets/330628/14060045/efc27b00-f356-11e5-832d-389188dae294.png)
This is roughly <https://www.openstreetmap.org/#map=17/49.20421/6.94788>. The "Rue Pasteur" roundabout-like structure being teared apart is the most noticeable bug, plus all those side streets of "Rue de Verdun" not being connected to the latter.

The affected map tiles here should be "Germany - Saarland" from 2016-03-04 and "France - Lorraine" from 2016-03-04 (not sure about the name of the latter in English; this is the French name, German name is "Lothringen".)
This is using OsmAnd~ 2.1.1 from F-Droid on CyanogenMod 12.1.

**Comment by xmd5a2** [comment]
Problem appears only at 1-19 (sometimes at 1-20) zooms when France - Lorraine and Germany - Saarland maps are installed together. But when France - Lorraine is the only map these roads are visible normally.

**Comment by xmd5a2** [comment]
Saarland only:
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot%20from%202016-03-30%2012%3A35%3A10.png
Lorraine:
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot%20from%202016-03-30%2012%3A35%3A41.png
Saarland + Lorraine:
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot%20from%202016-03-30%2012%3A36%3A02.png

**Comment by xmd5a2** [comment]
Problematic way 37165601:
Lorraine obf: 
```xml
<way id = '18144284' version='1'>
        <tag k='highway' v='residential' />
        <tag k='oneway' v='yes' />
        <tag k='name' v='Rue Clemenceau' /> 
        <tag k='original_id' v='37165601'/>
        <nd ref = '18144277'/>
        <nd ref = '18144278'/>
        <nd ref = '18144279'/>
        <nd ref = '18144280'/>
        <nd ref = '18144281'/>
        <nd ref = '18144282'/>
        <nd ref = '18144283'/>
</way>
```
Saarland obf:
```xml
<way id = '2267667' version='1'>
        <tag k='highway' v='residential' />
        <tag k='oneway' v='yes' />
        <tag k='name' v='Rue Clemenceau' />
        <tag k='original_id' v='37165601'/>
        <nd ref = '2267662'/>
        <nd ref = '2267663'/>
        <nd ref = '2267664'/>
        <nd ref = '2267665'/>
        <nd ref = '2267666'/>
</way>
```

**Comment by RalfJung** [comment]
I am actually surprised to see these streets in the Saarland map, they are all entirely in France -- the boarder is a few hundred meters to the East.

**Comment by xmd5a2** [comment]
Maps are overlapped to avoid gaps.

**Comment by xmd5a2** [comment]
@RalfJung can you please recheck if issue is exists with current maps?

**Comment by RalfJung** [comment]
It seems to be all fixed, thanks :-)
