### ISSUE TITLE
Display protected areas only from protect_class=1 to 4

### ISSUE THREAD

**Issue by cepesko** [osmandapp/Osmand#2371]
In version 2.3.3 any protected area seems to be marked with a green P. 
Please deselect less highly protected areas (maybe class 5 and lower) from being displayed as this leads to an inappropriate coverage of complete cities, industrial areas, agricultural landuses (see example [www.openstreetmap.org/relation/5411343](url) ). Or make it an optional display, just like boundaries. Thank you.

**Comment by xmd5a2** [comment]
Hope this commit fixes a problem
https://github.com/osmandapp/OsmAnd-resources/commit/80f6d7e7ad65306004dd6db02a3f9c9dafbe2678

**Comment by streckenkundler** [comment]
In additional to the Ticket from cepesko: https://github.com/osmandapp/Osmand/issues/2371
I Think, only boundary with protect_class=4 should be marked with a green P. 
Boundarys with protect_class=1|1a|1b should be marked with thin red vertical lines. All other protect_classes like protect_class=2|3|5|6|7|97|98 should be marked only with a dashed outline. From the other protect_class – values should be rendered only ndividual values: protect_class=14 and protect_class=16 like protect_class=1 and protect_class=25 like military areas.
For South Brandenburg the current situation with several protect_classes: http://overpass-turbo.eu/s/fgS.

**Comment by xmd5a2** [comment]
Ok, I partially agree. Problem lies in fact that release is already out and if we does not remove most of protected_area objects they will be visible in release version with green P. I think it is better do not touch anything but implement these changes only before next release.

**Comment by streckenkundler** [comment]
I think, th current rendering-situation is not a problem. My example of the current situation, I have captured months ago. So, I can wait. 

I forgot one thing. A protect_class=1|1a|1b area can be a part of a protect_class=4 area. In these cases can the area marked with the green P and with the thin red vertical lines. I think, this is also not a problem.

**Comment by xmd5a2** [comment]
Why do you propose that protect_class=1|1a|1b should be marked with vertical red lines?

**Comment by streckenkundler** [comment]
I don't no... it can be also horizontal black lines, or pink Elefants (OK, very bad idea), or x-crosses or others...
It is important that the user is looking: "Ok, this is a restricted area!"
