### ISSUE TITLE
Hard to see the turn lane arrows

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/Osmand#2372]
Thanks for working on turn lanes like issue #1198. 
But now it is hard to see the arrows courses of the colors. See screenshots.
![screenshot_2016-03-26-17-30-37](https://cloud.githubusercontent.com/assets/11144987/14065700/95642f94-f434-11e5-93b1-054c8b17cbc4.png)
![screenshot_2016-03-26-15-08-05](https://cloud.githubusercontent.com/assets/11144987/14065702/a5db1a68-f434-11e5-9b32-9c0d2210af99.png)

Using osmand 2.3.0 #16231
Offline maps. Germany
Thanx Simon

**Comment by Barrocas** [comment]
I also noticed this issue, the arrows got thinner and lost the black outline, so they are more easily confused with the map background.

**Comment by vshcherb** [comment]
Work in progress. Today should be better, though the black outline might not get back (it is not clear yet) we change the way we generate/draw icons.

**Comment by vshcherb** [comment]
I will close it because today it should be better but anyway work in progress, please comment if there is no reaction in 1 week.

**Comment by jf-simon** [comment]
one thought. maybe an option, to set the transparency of the wite background of the widgets, would help

**Comment by Barrocas** [comment]
You can disable the transparency, but that is a workaround, not a solution for this issue.
Before the change, the arrows were easily visible even with the transparency enabled, because they were larger an had the black outline to separate them visually from the background map.

Let's wait and see how this goes...

**Comment by vshcherb** [comment]
The size should be reasonable now
