### ISSUE TITLE
OsmAnd 2.3 crashes in Android 6 if location permissions are not enabled

### ISSUE THREAD

**Issue by DFyson** [osmandapp/Osmand#2373]
Using OsmAnd 2.3 nightly. I had recently installed CyanogenMod 13 (Android 6 Marshmellow) which has new permission settings. Tried starting OsmAnd and it continuously crashed. Going to Settings → Apps, turned on location for OsmAnd and it worked fine. It's odd since usually the OS will have a popup and ask something like "Allow this app wants to use location services?"

Related: if permissions to edit storage haven't been enabled and you try to pick a directory other than the default locations, it will silently fail instead of asking to enable storage permissions.

> Crash report:
> Version  OsmAnd~ 2.3.0#3273M_2.3
> 26.03.2016 12:54:49
> Apk Version : 2.3.0#3273M_2.3 231
> Exception occured in thread Thread[main,5,main] : 
> java.lang.RuntimeException: Unable to start service net.osmand.plus.NavigationService@b624ff6 with Intent { cmp=net.osmand.plus/.NavigationService (has extras) }: java.lang.SecurityException: **"gps" location provider requires ACCESS_FINE_LOCATION permission.**
> 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3061)
> 	at android.app.ActivityThread.-wrap17(ActivityThread.java)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1461)
> 	at android.os.Handler.dispatchMessage(Handler.java:102)
> 	at android.os.Looper.loop(Looper.java:148)
> 	at android.app.ActivityThread.main(ActivityThread.java:5461)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
> Caused by: java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.
> 	at android.os.Parcel.readException(Parcel.java:1620)
> 	at android.os.Parcel.readException(Parcel.java:1573)
> 	at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:606)
> 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:892)
> 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:465)
> 	at net.osmand.plus.NavigationService.onStartCommand(NavigationService.java:146)
> 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3044)
> 	... 8 more

**Comment by vshcherb** [comment]
Thanks for info we were looking for that exception.

**Comment by numbnut** [comment]
Hi,
is this already fixed? If that's the case, when will it be released?

**Comment by vshcherb** [comment]
It is already in Beta build, I think this week.
