### ISSUE TITLE
Offline Routing: "Head..." appears twice

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#2376]
Osmand 2.3.0#12370D. Osmand in-app offline routing (car, fastest). Osmand in-app Offline Maps

Sometimes in Route Details appears twice "Head..." with no pattern well deffined (appears only in some cases)
![screenshot_2016-03-27-00-37-24](https://cloud.githubusercontent.com/assets/12786225/14067859/92091540-f46f-11e5-8495-38333d356b5a.png)
![screenshot_2016-03-27-22-49-21](https://cloud.githubusercontent.com/assets/12786225/14067860/9dcfd0b2-f46f-11e5-8819-ec4d78188adb.png)

**Comment by vshcherb** [comment]
It makes sense, for some intersections we want exactly be spoken. There are some mute highlights but this is spoken. Usually motorway split to motorway+motorway is spoken, and to motorway+motorway_link is mute.

**Comment by OpenSourceForEver** [comment]
maybe time and distance at the right of the arrow (time and distance to next intersection) could be moved to the end of the text in order to distinguish it better from time and distance at the left of the arrow (total time and  total distance)

**Comment by OpenSourceForEver** [comment]
Ok. I thought "head..." was a bug. I have understood it.

**Comment by OpenSourceForEver** [comment]
On first Screenshoot motorway split to motorway+motorway. On second screenshoot motorway split to motorway+motorway_link so I do not understand it. Sorry

**Comment by vshcherb** [comment]
I don't see an issue here and the code which it differentiates spoken split and non-spoken split is not that easy to project to the screenshots you provide. So it is self-explainable here https://github.com/osmandapp/Osmand/blob/master/OsmAnd-java/src/net/osmand/router/RouteResultPreparation.java#L838
