### ISSUE TITLE
Direction to destination does not display

### ISSUE THREAD

**Issue by BenyTheKid** [osmandapp/Osmand#2378]
Just a heads up, I've tried on the 2.3 nightly and on the play version of osmand plus, and show destination direction doesn't work on either of my devices. I can get the pointer to show up only if I physically manipulate the map with the touch screen and when I stop, it disappears again. Nightly is running on Samsung tab s2 and play store version on Sony Xperia z5. Using offline vector.

For **general questions** about Osmand, please use the [googlegroup](https://groups.google.com/forum/#!forum/osmand).

Please be sure to have read our [FAQ](http://osmand.net/help-online) before creating an issue here. (Also tell us in googlegroup when the FAQ is wrong or outdated.)

The best way to get help about an Osmand issue is to create a valid and detailed issue content.
Please give us the following information so that we can try to **reproduce** your issue:

What version of OsmAnd are you using, on what device and Android/iOS version?

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

__*In case of wrong routing:*__

Tell us whether you have used OsmAnd's in-app offline routing, or any online routing provider like YOURS, OpenRouteService or OSRM.

What routing profile is choosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest)

Please specify as exactly as possible the start and end point of your route by telling us city name and street name so that we can find it via in-app address search easily. Also a permalink from openstreetmap.org can be helpful.

Tell us your expected routing, and how OsmAnd routes, or add screenshots here.

**Comment by vshcherb** [comment]
There is a discussion already on googlegroup, shortly it works as we visioned it but we are going to change it so it will be displayed constantly according to the setting.
