### ISSUE TITLE
Getting quick voice instructions from OsmAnd about the upcoming junction

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2381]
After I switched to a 5.5" phone, even my old phone mount is unable to handle it. My second car does not have a mount for a phone at all.

Thus I have to leave the phone down on the co-driver's seat and rely on OsmAnd's voice guidance (which are usually sufficient).

But this creates a new problem: The FM radio of my car may mask any voice instructions from OsmAnd, and I may miss a turn instruction.

On the other hand, OsmAnd often keeps silent when we are supposed to pass straight through a road junction, or a multi-lane situation. 

So at each crossing or fork, I face a dilemma: Did I miss the voice instruction from OsmAnd, or does it want me to go straight??

At such times, there should be a gesture that forces OsmAnd to respond with a voice instruction, about what to do with the upcoming junction.

For example, imagine that a double-tap on screen evokes "keep going straight" voice response. 
Or it could be "take the left lane and then go to the flyover."

This feature is different from tapping on the arrow icon (at the top-left corner of the screen).
But equally useful.

**Comment by vshcherb** [comment]
> This feature is different from tapping on the arrow icon (at the top-left corner of the screen).
I think it should be enough and I often use it my self, the touch area is pretty big to click it. I might be wrong.

**Comment by raindropsfromsky** [comment]
Actually when I put the phone on the co-driver seat, its screen is turned off. So the "Next turn" icon (at the left-side top corner of the screen) is not available for tapping.

So, can we tap the blank screen instead?

Secondly, when we tap the "Next turn" icon, the voice describes that particular turn, which may be several km away. But in this case, I am more concerned about the upcoming junction, which I would be crossing in a few seconds. Therefore we need a different command here.

**Comment by sonora** [comment]
2 comments here:

(1) "The FM radio of my car may mask any voice instructions from OsmAnd": I am assuming you have the car stereo coupled to the phone via Bluetooth. Yes, issue is, the phone will now direct all audio to the BT channel, but most if not all car radios will not play the phone audio output unless they have the Aux/BT (and not FM etc.) input as the selected source. I am not sure there are good ways to fix it. The way I handle it is this: In OsmAnd, go to Settings / General / Voice guidance output, and select "Notification audio". On most devices this will cause the phone to output both via BT (if connected) _and_ the phones ring tone speaker, which may suffice if at full volume.

(2) In OsmAnd, like in all other nav systems I am familiar with, we only announce turns you need to make, remain silent for "no turn". Even with this, we already have some issue with OsmAnd being too chatty. Imagine what going straight  through a city would sound like if at each intersection we also announced all "go straight aheads"!  For now I have no better idea than you relying on OsmAnd immediately re-routing (and saying so, test it!) in case you have missed a turn, or if this takes a little longer you would definitely hear "You have been off the route for x-hundred meters". (Though both messages under some circumstances sometimes seem also played if you followed the correct route, small bug, needs some investigation).

But re-routing works pretty reliably, and also we announce each turn reliably and usually repeatedly before it occurs, I believe introducing a general "go straight ahead" voice prompt is not a good solution.

**Comment by raindropsfromsky** [comment]
Responses:

(1) No my phone is not connected to the car electronics. Thus the voice guidance of OsmAnd just competes with the car FM radio; and my phone is no match for the car amplifier. 

(2) But my suggestion does not make OsmAnd chattier!

I am not saying OsmAnd should announce each "go through" situation by default. Let this be a user option, just below the Voice on/off slider button. 

In addition, let the user tap the screen to know which way to go (this is because OsmAnd may have already told you to turn, but you could not catch that because of the FM Radio). This is just like how visually impaired people check time.

Note that if OsmAnd wanted me to turn, but I missed that, OsmAnd will definitely re-route and prompt me. But that's like crying after split milk. You may have to detour a few km before you can come back to the route.

**Comment by sonora** [comment]
No action planned here for now, I guess.
