### ISSUE TITLE
Clearer voice instructions for (a) lane guidance and (b) entering a flyover or underpass

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2382]
By and large, OsmAnd provides human-like voice instructions.

In the following two conditions, the sentence needs to be improved, though:

**1. Approaching a flyover of underpass:**
When we are supposed to take a flyover or underpass, OsmAnd should tell us to "go up the flyover" and "go down the underpass". This results in clearer meaning.

**2. "keep left" vs "take the left-most lane"**
Often the voice instruction is a little vague. In Bangalore, we have some flyovers where the center lane enters a flyover, while the left and right lanes split up the road and turn left and right. So a "keep left" instruction sounds vague, and does not fit the scene ahead of us. (keep how much left??)

Instead, it should say "TAKE the left-most lane" or "TAKE the middle lane and then enter the flyover"

**Comment by vshcherb** [comment]
We just started creating tests and working thoroughly on turn lanes instruction unfortunately it is not close to what we expect and any error in the lane could be very misleading.

**Comment by sonora** [comment]
No action feasible for now.
