### ISSUE TITLE
Istanbul at 5km zoom shows as in water

### ISSUE THREAD

**Issue by smith51** [osmandapp/Osmand#2385]
Sony Xperia Z3 Compact, Android v5.1.1

OsmAnd+ version 2.3.3 from Google Play (2016-03-25).

World overview map (2016-01-18), Full map of Turkey (2016-03-04), Turkey Wiki (2015-11-09), World seamarks (2016-03-01).

East part of Istanbul, Turkey shows as in water at 5km zoom and more. I attached two screenshots. Zoom level at 10 km shows fine but turns in water at 5km zoom level.

![istanbul-5km-screenshot_2016-03-29-23-53-22](https://cloud.githubusercontent.com/assets/13431977/14119269/9b6ea5ba-f617-11e5-88d7-b2787ce70667.png)
![istanbul-10km-screenshot_2016-03-29-23-53-14](https://cloud.githubusercontent.com/assets/13431977/14119270/9b71d58c-f617-11e5-8f8b-6f35de373536.png)

**Comment by kompowiec** [comment]
simply disable configure map-->POI ;] and not will see.

**Comment by smith51** [comment]
I disabled POI and it doesn't help.

**Comment by kompowiec** [comment]
hmm, maybe you switch off plugin "Nautical map view"?

**Comment by smith51** [comment]
Switching off plugin "Nautical map view" doesn't help too. See screenshot.
![istanbul-5km-woseaplgn-screenshot_2016-04-25-01-46-10](https://cloud.githubusercontent.com/assets/13431977/14769662/e3f4d69a-0a87-11e6-96ad-f501d2ec8eb1.png)

**Comment by kompowiec** [comment]
i think so that helped, because hide POI. If you want hide tracks, IMO it just has to be - unless you uninstall map for boat. Boat tracks is the same as every other way.

**Comment by vshcherb** [comment]
Is it ok that you see russian names in turkish map? Can't reproduce with latest map https://www.dropbox.com/s/lr7quzzlki74lol/Screenshot%202016-04-27%2000.58.20.png?dl=0

**Comment by kompowiec** [comment]
@up osmand allowed setting set yourself np. local names or other if someone add on OSM. At last in theory.

**Comment by smith51** [comment]
Ok, this issue was fixed by latest maps and app updates.

![screenshot_2016-06-06-11-14-13](https://cloud.githubusercontent.com/assets/13431977/15811895/9bab09dc-2bd8-11e6-8f48-10470859cacb.png)
