### ISSUE TITLE
Misleading notification bar entry

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2386]
While (and only while) OsmAnd is the foreground app and no trip recording or navigation is active, we show an entry in the Android notification bar with
- a track icon
- title "OsmAnd"
- subtitle "trip recording (xx m)"

This seems misleading and useless, in particular since the entry changes to our background service and icon once a navigation or trip recording has actually been started, i.e. is only present while NO trip recording is active. I am not sure if this notification entry has any point at all?

I suggest to suppress the entry entirely. If this is not possible, we should at least change the icon from the track related to something like our "browse map" mode icon, and remove the misleading subtitle about trip recording?

**Comment by vshcherb** [comment]
This entry is a "shortcut" to start/stop recording.

**Comment by sonora** [comment]
Then I guess it is somehow malfunctioning, because it only appears while NO trip recording is ongoing?

Also: I notice that we have another notification entry which does actually have a different icon (I think the normal background service icon) and does SOMETIMES have stop and save buttons for trip recording (which is in fact useful). But I do not know how to reliably show that, the stop/save buttons sometimes show up and sometimes not, even though OsmAnd is trip recording. And this seems a different notification from the one I am talking above, which strictly only appears when both no trip recording is active, and while OsmAnd is in the foreground anyway.

**Comment by sonora** [comment]
Related:  Our background notification seems to work reliably in all cases, and its subtitle also correctly indicates the underlying reason, e.g. ongoing navigation,  and/ or trip recirding, both when OsmAnd is in the foreground and in the background.

But when OsmAnd is moved to the background during an ongoing navigation, we produce a second (car icon) notification, tapping on which has no other effect than tapping on the notification we have anyway, which is bringing OsmAnd back to the foregroubd? Seems the second notification is totally obsolete?

**Comment by sonora** [comment]
Overall,  I guess we could have just one OsmAnd notification bar entry, add all buttons to it as we may want or need, rather than producing 2 or 3 different notification entries which appear unreliably in wrong situations,  and carry no or inadequate functionality?

**Comment by Barrocas** [comment]
Agree with sonora.
It would be simpler and more usefull.

I'd also like to point out another related thing about the notification, when we finish navigation, and tap the phone Home button, the notification stays on the status bar, even though navigation has stopped, and we got out of the app (no ongoing recording), so there is no need to maintain the notification.

The notification only clears if we get back to Osmand and tap the phone Back button.

**Comment by vshcherb** [comment]
Could you please provide screenshots, I'm not sure any more if it works exactlly as designed and as described.

**Comment by sonora** [comment]
(1) I have looked at the code and the first thing which was wrong is that the Trip recording notification (GPX track icon) was always on whenever
- service==null
- monitoringPlugin != null
- OsmAdn was in the foreground
This "misleading track icon" in the task bar under "normal" operating conditions, i.e. when OsmAnd was in the foreground, but no trip recording or navigation was ongoing, was my original issue here.

This had never worked before, it had been a bug for many months now. Improved by this commit: https://github.com/osmandapp/Osmand/commit/8aaaab9bad32aad668cee21cc24ee202809644d4

(2) Remaining issue: We still always show an OsmAnd notifictation under the above 3 conditions, now with the "normal" bgs icon. I think we should hide the notification totally if no service is running, and nor tracking is ongoing, or unsaved tracks>0 exist (i.e. expand my commit to not call notificationBuilder at all then)

(3) Then I have tried to de-crowd the notificationText layout a bit: https://github.com/osmandapp/Osmand/commit/82545c0fda4a0747de2eab0ecb1c7a544ebaf380, but it seems the notification text does not take line breaks?

(4) I still say we could really limit ourselves to just have one combined bgs notifcation (and icon), and drop all other separate notifications, i.e. never show 2 or more OsmAnd notification icons in the top bar? (Currently we still pop up the additional car if a navigation is ongoing, as soon as Osmand is moved to the background)

(5) Still have to research when and in what notification the GPX Record-STOP and SAVE buttons appear, they somehow seem to not appear reliably.

**Comment by sonora** [comment]
PS: Screenshots almost overkill: But here is how to reproduce (Trip recording plugin is enabled in all cases):
(a1) OsmAnd in the foreground, no navigation, no trip recording ongoing, no unsaved track: before  8aaaab9: Trip recording notification was on. Now, bgs icon notification is on (2 above). Both should be off.
(a2) Now move OsmAnd in the background: notification disappears, this is ok.
(b1) OsmAnd in the foreground, follow navigation: Now bgs notification is on (this is ok)
(b2) Now move OsmAnd to the background: bgs notification remains on, this is ok. But now a second notification appears with a car profile icon, which offers no additional functionality.
(c) Appearance of GPX START/STOP/SAVE buttons somehow erratic.

**Comment by vshcherb** [comment]
Initially we did a combining notifications but it leads to many different situations and it was hard to test and full of small glitches. Having 2 separate notifications simplified testing a lot.

**Comment by vshcherb** [comment]
> Missing noti refresh upon SAVE operation, I guess.

On save I think notification should be just recreated of course.

Notification MapActivity, line 184, was historically there and I think today we have a notification that goes back to OsmAnd (OsmAnd is working in background). So I agree it could be deleted.
I think the main reason to have 2 notifications because they have completely different meaning and run with different status. 1 notification - OsmAnd works in background, 2nd notification - you can control GPX recording easily. 1st is very important, 2nd is shortcut. Of course situation when you have 2 notifications for GPX recording looks slightly too much but it gives consistent notification look and feel.

**Comment by sonora** [comment]
Yes, I remember now, it is  historic: On the background service notification, we initially used to have a button to stop the bg service,  which raised many functional issues. Now the background service notification is more like the master noitification , listing all reasons why Osmand is running in the background,  and tapping it will simply return to OsmAnd, which is much better. So I think we should really get rid of all secondary notifications now.

Start/stop/save buttons issue seems also only related to this background notification, looks like the other notifications never carried any buttons or actions.

**Comment by sonora** [comment]
Ok, We have had a series of logical issues in that code.

I have removed all duplicate OsmAnd notifications (only OsMo untouched, though), so for now we only have one OsmAnd system notification, and it only displays if the background service is on. It reports all reasons and status why the BG service is active. Tapping it puts OsmAnd in the foreground, unless it already is.

One issue observed is this: The Start/Stop GPX logging / SAVE buttons do now appear correctly, _however_, at least on my test devices and Android versions, ONLY while the Android system's GPS notification is OFF. This means that the buttons disappear while
- OsmAnd is in the foreground (unless you manually disable GPS)
- a navigation is in follow mode (which puts GPS in continuous mode)
- GPX logging is on with intervals < 30 sec (which also puts GPS in continuous mode).

If you have only GPX recording on with interval >=30sec, the buttons only disappear while GPS is woken up, are visible during other times.

If anybody knows any way to fix this, please add here. I will close the issue, 95% fixed.
