### ISSUE TITLE
GPX selection dialog marks all tracks with ticks

### ISSUE THREAD

**Issue by andrew-davie** [osmandapp/Osmand#2387]
New behaviour of the GPX selection dialog by default marks all GPX tracks with a tick. This is bad; only the previously selected track(s) should be marked. Currently I have to manually un-tick every track (all 30 or so) just to test any one track.  

This behaviour was introduced recently, I think perhaps by someone testing GPX display?

**Comment by sonora** [comment]
Yes, see also my remarks to this commit:  https://github.com/osmandapp/Osmand/commit/60073c4ff32c90af730e95710ad8613d3db9ba65
