### ISSUE TITLE
Context menu timeout

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#2389]
Remove context menu after timeout after making audio-video-photo using OsmAnd.

**Comment by Barrocas** [comment]
Yes please, I had asked for that before on another issue/request. 

It's even more important when we are navigating, and take a audio/photo/video note, then the context menu stays opened cobering the screen, and the navigation route is not followed until we tap the map to clear the context menu.

Suggest maybe a 3s timeout for clearing the context menu out of the screen?

**Comment by Barrocas** [comment]
Working great! 
Less clicks needed to close the context menu, mostly when driving, is a bonus.

Could this context menu timeout also be applied to when we choose to add/modify POI?
