### ISSUE TITLE
[UI] Disfunctional arrow button in top-right corner

### ISSUE THREAD

**Issue by RalfJung** [osmandapp/Osmand#2390]
In the top-right corner of the screen when viewing the map, there is an arrow button that does nothing.

Steps to reproduce:
* Start OsmAnd~, stay in map view (offline maps)
* Tap the button in the top-right screen corner

Actual behavior:
The button changes its direction. Nothing else happens.

Expected behavior:
*Something* should happen. I have no idea what the intended purpose of this button is, but I doubt it is meant to do nothing :)

Here's screenshots of before and after pressing the button:
![screenshot_2016-03-30-13-43-33](https://cloud.githubusercontent.com/assets/330628/14141346/b9866c38-f67e-11e5-86e5-722921b8edf1.png)
![screenshot_2016-03-30-13-43-38](https://cloud.githubusercontent.com/assets/330628/14141348/bbdeb094-f67e-11e5-97e9-968b4632efa3.png)

This is using OsmAnd~ 2.1.1 from F-Droid on CyanogenMod 12.1.

**Comment by Barrocas** [comment]
That arrow button is to expand/contract the available/selected widgets (top right bar info, like speed, gps, altitude, etc).

You can update your Osmand version to a more recent release or build, and see if that solves it for you.

I have a more recent app version, an that arrow button only shows up if the selected widgets are too many to fit on the screen, so no issue there.

**Comment by RalfJung** [comment]
I have the latest F-Droid version installed. I don't have GApps, so I'm afraid I have to wait until someone bothers to update the freely available version.

**Comment by Barrocas** [comment]
You can try the (testing) night builds, there is even a link on the bottom of Osmand.net webpage, like this one:

http://download.osmand.net/latest-night-build/OsmAnd-default.apk

You do have to check Android Settings to enable the installation of apks out of GApps (unknown sources), but in this case, it's fine.

**Comment by xmd5a2** [comment]
This can happen if current speed is selected with "+" (or "Hide" now) option in Configure screen and current state is not navigation mode. Current speed widget is hidden in these conditions but this arrow not.

**Comment by RalfJung** [comment]
Actually, I am on version 2.2.4. Not sure where I got the other version from.

**Comment by vshcherb** [comment]
Not clear what should be fixed. The arrow is properly indicated the state of Configure Screen.

**Comment by RalfJung** [comment]
Clicking the arrow does not do anything. There is no visible state change here. How is this properly indicating anything?
