### ISSUE TITLE
If phone is locked, the voice prompt does not announce the "GPS is recovered" message

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2396]
When the screen is on, OsmAnd announces the "GPS signal is lost" and "GPS signal is recovered" messages properly.

But when the screen is turned off, OsmAnd announces only the "GPS signal is lost" message, but does not announce when the GPS signal is recovered. But it resumes the voice-assisted navigation.

Strangely, when I unlock the phone, OsmAnd immediately makes the pending "GPS signal restored" announcement. (But the actual GPS signal was recovered long ago!)

A major issue with this is, you never know if OsmAnd will alert you about the next turn, or are you on your own??

**Comment by kompowiec** [comment]
maybe enter to settings-->Navigation-->Turn screen On-->Never he can work? Then i can turn off screen and I further voice navigation.

**Comment by raindropsfromsky** [comment]
No that's not the correct solution. I do want to turn the screen off, to
save power.

But when I return to OsmAnd, it should bypass the lock screen and come to
top directly.

On Apr 23, 2016 8:58 PM, "kompowiec" <notifications@github.com> wrote:
>
> maybe enter to settings-->Navigation-->Turn screen On-->Never he can
work? Then i can turn off screen and I further voice navigation.

**Comment by kompowiec** [comment]
Above setting it allows you on manually screen control. Run routing with GPS with voice and click on power button on the unit to turn off the screen. For me doesn't cause however locking screen.

**Comment by sonora** [comment]
Cannot reproduce.
