### ISSUE TITLE
Transparency seekbar not preserved between runs

### ISSUE THREAD

**Issue by andrew-davie** [osmandapp/Osmand#2399]
I use underlay maps and turn on the transparency seekbar (an option in the underlay map dialog). This seekbar works fine, but it is not present when OsmAnd is stopped/started.  So, this is a bug. Correct behaviour would be for the seekbar switch option to be displayed always, if you have it selected as ON in the underlay map settings.

**Comment by GaidamakUA** [comment]
Can't reproduce.

**Comment by andrew-davie** [comment]
This is very easy to reproduce.  Simply select an underlay map. You now have a transparency slider at the bottom of the map screen.  Quit OsmAnd and restart. The slider is no longer there, yet the underlay map is still selected.  I see it *every single time*

**Comment by scaidermern** [comment]
Can't reproduce it on my device either. Are you sure you are not accidentally pressing the little x next to the slider?

**Comment by andrew-davie** [comment]
Very sure. Strange, as it has NEVER worked for me.
Video shows an emulator run with the problem… I go to the underlay configuration and turn on transparency slider.
It’s there. I use it. I quit OsmAnd and come back. It’s not there. I go to the underlay configuration and see that the slider is not turned on.
https://www.youtube.com/watch?v=Tum5kDoCOuw&feature=youtu.be <https://www.youtube.com/watch?v=Tum5kDoCOuw&feature=youtu.be>
Essentially, the slider on/off state is not preserved between OsmAnd runs.
