### ISSUE TITLE
Double name text on motorway_junction

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#2402]
Go to 'Configure map'

Select to enable the first 2 checkboxes, POI and names.

All motorway_junction appear with double text overlapping.

**Comment by Barrocas** [comment]
![screenshot_2016-03-31-17-17-35](https://cloud.githubusercontent.com/assets/4006691/14182854/39403968-f765-11e5-8a7e-e92678c2421c.png)

**Comment by vshcherb** [comment]
I'm not sure why do we have that kind of POI. That's a known issue so far and that's why we have checkbox POI Labels.

**Comment by Barrocas** [comment]
The POI is fine, since it allows editing for name, ref, (etc) within
Osmand, and I use it a lot.

The issue here is just the double text.
If there is a name displayed, it doesn't need a second name on top of it.


-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by Barrocas** [comment]
The blue text is always rendered with the roads.
The black text is a PoI Label, but if we disable it, all the other PoI are rendered unnamed...

I would just like to suggest that the motorway_junction could still be an editable PoI, but this PoI could be rendered without the name label, since it doesn't need it on top of the already rendered blue name.

**Comment by vshcherb** [comment]
It is planned to refactor text rendering so for now it is a known issue.
