### ISSUE TITLE
Continual tile download in background - bug?

### ISSUE THREAD

**Issue by andrew-davie** [osmandapp/Osmand#2403]
I was just watching the 'logcat' output from OsmAnd and while the emulator was sitting there displaying the area just fine - with no movement or any interaction at all, I would expect nothing much to be happening. But no, there is a continual stream of tiles being downloaded - according to the log. Here's a short snippet.

04-01 03:42:01.079    9338-9897/net.osmand D/net.osmand﹕ MapTileDownloader Start downloading tile : http://tile.osmand.net/hd/14/14931/10282.png
04-01 03:42:10.581    9338-9897/net.osmand D/net.osmand﹕ MapTileDownloader Downloading tile : http://tile.osmand.net/hd/14/14931/10282.png successfull 9501 ms
04-01 03:42:10.581    9338-9897/net.osmand D/net.osmand﹕ MapTileDownloader Start downloading tile : http://tile.osmand.net/hd/13/7464/5139.png
04-01 03:42:12.998    9338-9345/net.osmand W/art﹕ Suspending all threads took: 18.550ms
04-01 03:42:14.560    9338-9899/net.osmand D/net.osmand﹕ MapTileDownloader Downloading tile : http://tile.osmand.net/hd/14/14931/10281.png successfull 18579 ms
04-01 03:42:14.563    9338-9899/net.osmand D/net.osmand﹕ MapTileDownloader Start downloading tile : http://tile.osmand.net/hd/13/7464/5140.png
04-01 03:42:16.741    9338-9899/net.osmand D/net.osmand﹕ MapTileDownloader Downloading tile : http://tile.osmand.net/hd/13/7464/5140.png successfull 2178 ms
04-01 03:42:16.742    9338-9899/net.osmand D/net.osmand﹕ MapTileDownloader Start downloading tile : http://tile.osmand.net/hd/13/7464/5141.png
04-01 03:42:19.130    9338-9899/net.osmand D/net.osmand﹕ MapTileDownloader Downloading tile : http://tile.osmand.net/hd/13/7464/5141.png successfull 2388 ms
04-01 03:42:19.130    9338-9899/net.osmand D/net.osmand﹕ MapTileDownloader Start downloading tile : http://tile.osmand.net/hd/13/7465/5139.png
04-01 03:42:21.759   9338-10033/net.osmand D/net.osmand﹕ MapTileDownloader Downloading tile : http://tile.osmand.net/hd/14/14931/10280.png successfull 36726 ms
04-01 03:42:21.762   9338-10033/net.osmand D/net.osmand﹕ MapTileDownloader Start downloading tile : http://tile.osmand.net/hd/13/7465/5140.png
04-01 03:42:22.713    9338-9979/net.osmand D/net.osmand﹕ MapTileDownloader Downloading tile : http://tile.osmand.net/hd/14/14930/10281.png successfull 40384 ms
04-01 03:42:22.713    9338-9979/net.osmand D/net.osmand﹕ MapTileDownloader Start downloading tile : http://tile.osmand.net/hd/13/7465/5141.png
04-01 03:42:24.017    9338-9345/net.osmand W/art﹕ Suspending all threads took: 8.121ms
04-01 03:42:33.005    9338-9349/net.osmand W/art﹕ Suspending all threads took: 5.833ms
04-01 03:42:33.034    9338-9349/net.osmand I/art﹕ Background sticky concurrent mark sweep GC freed 90023(3MB) AllocSpace objects, 0(0B) LOS objects, 2% free, 117MB/120MB, paused 8.552ms total 64.718ms
04-01 03:42:37.010    9338-9345/net.osmand W/art﹕ Suspending all threads took: 12.508ms
04-01 03:42:37.270    9338-9349/net.osmand I/art﹕ Background sticky concurrent mark sweep GC freed 93005(3MB) AllocSpace objects, 0(0B) LOS objects, 2% free, 117MB/120MB, paused 12.739ms total 58.556ms
04-01 03:42:40.163    9338-9897/net.osmand D/net.osmand﹕ MapTileDownloader Downloading tile : http://tile.osmand.net/hd/13/7464/5139.png successfull 29582 ms
04-01 03:42:40.163    9338-9897/net.osmand D/net.osmand﹕ MapTileDownloader Start downloading tile : http://tile.osmand.net/hd/12/3731/2569.png
04-01 03:42:42.565    9338-9979/net.osmand D/net.osmand﹕ MapTileDownloader Downloading tile : http://tile.osmand.net/hd/13/7465/5141.png successfull 19851 ms
04-01 03:42:42.565    9338-9979/net.osmand D/net.osmand﹕ MapTileDownloader Start downloading tile : http://tile.osmand.net/hd/12/3731/2570.png
04-01 03:42:45.715    9338-9349/net.osmand W/art﹕ Suspending all threads took: 5.007ms
04-01 03:42:45.755    9338-9349/net.osmand I/art﹕ Background sticky concurrent mark sweep GC freed 87761(2MB) AllocSpace objects, 0(0B) LOS objects, 2% free, 117MB/120MB, paused 7.581ms total 115.664ms
04-01 03:42:49.130    9338-9899/net.osmand W/net.osmand﹕ MapTileDownloader Cannot download tile : http://tile.osmand.net/hd/13/7465/5139.png
    java.net.SocketTimeoutException
            at java.net.PlainSocketImpl.read(PlainSocketImpl.java:484)
            at java.net.PlainSocketImpl.-wrap0(PlainSocketImpl.java)
            at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
            at com.android.okhttp.okio.Okio$2.read(Okio.java:135)
            at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
            at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
            at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
            at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
            at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
            at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
            at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:904)
            at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:788)
            at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:439)
            at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:384)
            at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:231)
            at net.osmand.map.MapTileDownloader$DownloadMapWorker.run(MapTileDownloader.java:270)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
04-01 03:42:49.130    9338-9899/net.osmand D/net.osmand﹕ MapTileDownloader Start downloading tile : http://tile.osmand.net/hd/12/3731/2571.png
04-01 03:42:50.544   9338-10033/net.osmand D/net.osmand﹕ MapTileDownloader Downloading tile : http://tile.osmand.net/hd/13/7465/5140.png successfull 28782 ms
04-01 03:42:50.544   9338-10033/net.osmand D/net.osmand﹕ MapTileDownloader Start downloading tile : http://tile.osmand.net/hd/12/3732/2569.png
04-01 03:42:53.800    9338-9349/net.osmand W/art﹕ Suspending all threads took: 6.576ms
04-01 03:42:58.038    9338-9345/net.osmand W/art﹕ Suspending all threads took: 5.918ms
04-01 03:43:06.039    9338-9979/net.osmand D/net.osmand﹕ MapTileDownloader Downloading tile : http://tile.osmand.net/hd/12/3731/2570.png successfull 23474 ms
04-01 03:43:06.041    9338-9979/net.osmand D/net.osmand﹕ MapTileDownloader Start downloading tile : http://tile.osmand.net/hd/12/3732/2570.png
04-01 03:43:07.557    9338-9345/net.osmand W/art﹕ Suspending all threads took: 7.501ms
04-01 03:43:10.565    9338-9345/net.osmand W/art﹕ Suspending all threads took: 11.329ms
04-01 03:43:10.590    9338-9349/net.osmand W/art﹕ Suspending all threads took: 8.346ms
04-01 03:43:14.732    9338-9349/net.osmand I/art﹕ Background sticky concurrent mark sweep GC freed 84141(2MB) AllocSpace objects, 0(0B) LOS objects, 2% free, 117MB/120MB, paused 3.752ms total 112.607ms
04-01 03:43:14.740    9338-9349/net.osmand W/art﹕ Suspending all threads took: 7.971ms
04-01 03:43:14.748    9338-9899/net.osmand D/net.osmand﹕ MapTileDownloader Downloading tile : http://tile.osmand.net/hd/12/3731/2571.png successfull 25618 ms
04-01 03:43:14.748    9338-9899/net.osmand D/net.osmand﹕ MapTileDownloader Start downloading tile : http://tile.osmand.net/hd/12/3732/2571.png
04-01 03:43:32.619    9338-9345/net.osmand W/art﹕ Suspending all threads took: 9.451ms
04-01 03:43:33.232    9338-9897/net.osmand W/net.osmand﹕ MapTileDownloader Cannot download tile : http://tile.osmand.net/hd/12/3731/2569.png
    java.net.SocketTimeoutException
            at java.net.PlainSocketImpl.read(PlainSocketImpl.java:484)
            at java.net.PlainSocketImpl.-wrap0(PlainSocketImpl.java)
            at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
            at com.android.okhttp.okio.Okio$2.read(Okio.java:135)
            at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
            at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:50)
            at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:418)
            at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:349)
            at java.io.InputStream.read(InputStream.java:162)
            at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:149)
            at java.io.BufferedInputStream.read(BufferedInputStream.java:295)
            at java.io.InputStream.read(InputStream.java:162)
            at net.osmand.util.Algorithms.streamCopy(Algorithms.java:320)
            at net.osmand.map.MapTileDownloader$DownloadRequest.saveTile(MapTileDownloader.java:122)
            at net.osmand.plus.resources.AsyncLoadingThread$TileLoadDownloadRequest.saveTile(AsyncLoadingThread.java:201)
            at net.osmand.map.MapTileDownloader$DownloadMapWorker.run(MapTileDownloader.java:271)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
04-01 03:43:33.232    9338-9897/net.osmand D/net.osmand﹕ MapTileDownloader Start downloading tile : http://tile.osmand.net/hd/12/3733/2569.png
04-01 03:43:33.396    9338-9979/net.osmand D/net.osmand﹕ MapTileDownloader Downloading tile : http://tile.osmand.net/hd/12/3732/2570.png successfull 27355 ms
04-01 03:43:33.396    9338-9979/net.osmand D/net.osmand﹕ MapTileDownloader Start downloading tile : http://tile.osmand.net/hd/12/3733/2570.png
04-01 03:43:34.095    9338-9899/net.osmand D/net.osmand﹕ MapTileDownloader Downloading tile : http://tile.osmand.net/hd/12/3732/2571.png successfull 19347 ms
04-01 03:43:34.095    9338-9899/net.osmand D/net.osmand﹕ MapTileDownloader Start downloading tile : http://tile.osmand.net/hd/12/3733/2571.png
04-01 03:43:35.097    9338-9897/net.osmand D/net.osmand﹕ MapTileDownloader Downloading tile : http://tile.osmand.net/hd/12/3733/2569.png successfull 1864 ms
04-01 03:43:35.098    9338-9897/net.osmand D/net.osmand﹕ MapTileDownloader Start downloading tile : http://tile.osmand.net/hd/15/29786/20494.png
04-01 03:43:35.136    9338-9345/net.osmand W/art﹕ Suspending all threads took: 15.485ms
04-01 03:43:35.152    9338-9349/net.osmand W/art﹕ Suspending all threads took: 20.058ms
04-01 03:43:35.194    9338-9349/net.osmand I/art﹕ Background sticky concurrent mark sweep GC freed 83921(2MB) AllocSpace objects, 0(0B) LOS objects, 2% free, 117MB/120MB, paused 22.262ms total 125.974ms
04-01 03:43:39.133    9338-9345/net.osmand W/art﹕ Suspending all threads took: 14.008ms
04-01 03:43:43.138    9338-9345/net.osmand W/art﹕ Suspending all threads took: 14.288ms
04-01 03:43:43.429    9338-9349/net.osmand I/art﹕ Background sticky concurrent mark sweep GC freed 83275(2MB) AllocSpace objects, 0(0B) LOS objects, 2% free, 117MB/120MB, paused 23.791ms total 87.078ms
04-01 03:43:46.240    9338-9979/net.osmand D/net.osmand﹕ MapTileDownloader Downloading tile : http://tile.osmand.net/hd/12/3733/2570.png successfull 12843 ms
04-01 03:43:46.242    9338-9979/net.osmand D/net.osmand﹕ MapTileDownloader Start downloading tile : http://tile.osmand.net/hd/15/29786/20495.png
04-01 03:43:54.650    9338-9345/net.osmand W/art﹕ Suspending all threads took: 11.132ms
04-01 03:43:56.150    9338-9345/net.osmand W/art﹕ Suspending all threads took: 10.601ms
04-01 03:43:56.475    9338-9899/net.osmand D/net.osmand﹕ MapTileDownloader Downloading tile : http://tile.osmand.net/hd/12/3733/2571.png successfull 22380 ms
04-01 03:43:56.475    9338-9899/net.osmand D/net.osmand﹕ MapTileDownloader Start downloading tile : http://tile.osmand.net/hd/15/29787/20495.png
04-01 03:43:57.151    9338-9345/net.osmand W/art﹕ Suspending all threads took: 8.009ms
04-01 03:43:57.650    9338-9345/net.osmand W/art﹕ Suspending all threads took: 7.321ms

So.... why are tiles being downloaded, and isn't this a huge bandwidth/time waste?  As you can see, many of the tiles are being downladed more than once, too. This seems like a bug to me, especially when the screen is completely static and all needed tiles are already shown!

**Comment by vshcherb** [comment]
If the map bbox is visible, it is not a bug (it is a feature). The connection could be interrupted by server but that doesn't mean the tile should not be tried to downloaded again.

**Comment by andrew-davie** [comment]
I think you are too dismissive.  How is it that tiles are downloading successfully, and yet they are still later being downloaded again?  Many examples in that log - e.g., 5140, 5141, 2570 (immediately downloading again after a successful download!). I don't think the connection is being interrupted - at least not according to this log which clearly shows downloads successful and subsequent downloads of the same file(s). I think it's a bug!

**Comment by vshcherb** [comment]
I think you created another issue which is already closed, so I don't need to comment here.
