### ISSUE TITLE
Use different shields for State and County Routes

### ISSUE THREAD

**Issue by mhyqwvcu** [osmandapp/Osmand#2404]
(USA only)

Osmand renders State and County routes with the same shield which can be confusing as numbering can be similar. To fix this I think either the rendering should fall back to the older "CR *"
 prefix or by using the standard shield below.

The template for a standard county shields are [2 digit](https://commons.wikimedia.org/wiki/File:MUTCD_M1-6_template_00.svg) [3+ digit](https://commons.wikimedia.org/wiki/File:MUTCD_M1-6_template_000.svg). The name and county words are probably not needed, only the route number.

EDIT: Looking again, I see CR is rendered in the shield before the number sometimes but not always.

**Comment by xmd5a2** [comment]
These shields are state-dependent.

**Comment by mhyqwvcu** [comment]
When you say "these shields" which ones are you referring to? State or County?

**Comment by xmd5a2** [comment]
I mean both State and County highway. I tried to find a way to separate one from another in OSM data but failed
https://wiki.openstreetmap.org/wiki/United_States_roads_tagging#County_Highways
Sometimes there is no relation and prefix only but sometimes network=US:xx:xx indicates county road. Wiki says that "network=US:NY:Onondaga for county routes in Onondaga County, New York". But what rule to separate this from for example US:NE:Link or US:GA:Bypass ?

**Comment by mhyqwvcu** [comment]
Ok, I see. County Route relations are not as completely mapped as others like US:I, US:US and state routes. Can you use the ref=CR * tag on ways to  render the shield? Limited to the US there should be no name collision.

Another method would be to make a list of all key:network values for every county (over 3000 though not that many relations yet in OSM) which I could compile a list of.

**Comment by xmd5a2** [comment]
Trying now to get list of strings after second delimiter in network tag (US:??:*) to use condition like
```
if not (list) then draw county shield
```
Not sure though that this will work adequately.

**Comment by mhyqwvcu** [comment]
I have considered that but to make it more confusing there are other routes that are not state or county such as US:NY:Thruway (Toll road with it's own [shield](https://en.wikipedia.org/wiki/File:NYS_Thruway_Sign.svg)) and a lot of noise with tags like US:MA:old_turnpike and incorrectly formatted values.

**Comment by xmd5a2** [comment]
I added support for counties for all used in OSM in network tag. Also ref=CR* and network=US:xx:CR* are supported.
https://github.com/osmandapp/OsmAnd-tools/commit/cf8e34482e411de1b976ccbc8fca6ce7c7eeaea3
Looks like it is all we can do now.
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot%20from%202016-04-02%2014%3A12%3A34.png

**Comment by mhyqwvcu** [comment]
This is great! 

Adding shields was an excellent choice.  It's a minor visual difference, but it seems like a big improvement at least to me and other users I've talked to.

**Comment by mhyqwvcu** [comment]
@xmd5a2 Is the county list hardcoded? If new county network values are added to OSM do they have to be added to OsmAnd as well?

**Comment by xmd5a2** [comment]
@mhyqwvcu yes they are hardcoded. Ideally in osm should be tag like county=yes. If we don't have a simple way to separate county roads from others I see no other solution but to hardcode county list.
