### ISSUE TITLE
We need to stop track recording when a user disables the trip recording plugin

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2407]
Currently, if a user somehow happens to have track recording active and then disables the plugin, the track recording remains active indefinitely, and causes significant battery drain the user may not even be aware of. To make things worse, the settings is persistent, i.e. even after killing OsmAnd or restating the device the background track recording comes back on with no obvious way to stop it.

Chances are this is also behind some bad criticism OsmAnd sometimes receives to be a battery hawk.

**Comment by vshcherb** [comment]
I think it is fixed.

**Comment by sonora** [comment]
Yes, I think the worst thing is fixed:  Lokks like if a manual recording is ongoing, it is at least stopped for good the next time Osmand is killed.

Question (related to #2386): Do you think it makes sense at all to have a separate system notification for the case there is an unsaved GPX track? I am talking about the case where the recording has been paused so that our bgs system notification, which also has this information, is off. I wonder if we should not just unconditionally put return null in NotificationHelper line 109, and thus get rid of an obsolete notification, because we have a widget showing the status of recordings reliably, while the notification has refresh issues.

**Comment by vshcherb** [comment]
I need to recall discussion on some forums may be I could bring these people to github, so we can discuss why notification is needed. I don't have strong opinion about it. @xmd5a2  do you remember why did we introduce a separate notification?
