### ISSUE TITLE
Background interval not re-set from previuosly selected if follow-nav is started

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2415]
To be verified, but I think we have the following issue:

If in OsmAnd you first start a GPX logging, say with interval 30sec, so that the background service is started with interval also set to 30 sec., and you then start a navigation in follow mode, the bg service interval does not seem to be updated from 30sec to "Continuous", hence the backkgrund navigation will be carried out with the 30sec interval.

Maybe this accounts for one or the other navigation issue we have heard about late or missing turn instructions, screen not coming on in time, etc.

**Comment by vshcherb** [comment]
Looks the solution is in place by you:

			//TODO: fallback to custom USED_BY_GPX interval in case all other sleep mode purposes have been stopped
			getSettings().SERVICE_OFF_INTERVAL.set(0);
