### ISSUE TITLE
Various crashes

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#2417]
I'm experiencing various crashes with OsmAnd. They happen fairly often as can be seen on the time stamps. Unfortunately I haven't found a simple way to reproduce them but I hope these backtraces are still kind of useful. The crashes happen both after startup (either instantly or a little later during panning) and during routing.

Maybe the cause is just my phone having too few RAM. It's a Huawei Y300 with Android 4.4 and has a total memory of 512 MB but of course the available free memory is way less than that.

See the exception log for details: 
[exception.log](https://github.com/osmandapp/Osmand/files/201406/exception.log.txt)

Tell me if there is a way to provide more useful information.

**Comment by vshcherb** [comment]
We fixed some crashes and create new issue for another one https://github.com/osmandapp/Osmand/issues/2421
