### ISSUE TITLE
Lock screen "spasms"

### ISSUE THREAD

**Issue by mathstuf** [osmandapp/Osmand#2423]
Not really sure how best to describe the problem. Sometimes if the screen is locked and navigation is active, if the screen times out, turning the screen back on will flip between the lock screen and OSM's screen until it either times out or I press the home button (which goes to the lock screen). May have something to do with screen orientation (lock screen is only portrait, but phone is in landscape), but I'm not sure.

Android 6, Nexus 5X. From F-Droid.

**Comment by mathstuf** [comment]
Ugh. That's meant to be "spasms" in the title (can't edit from Octodroid?).

**Comment by vshcherb** [comment]
We observed these issues but we can't do much. It really beyond application itself and depends on Android operating system. It also behaves differently on different phones.

**Comment by janvlug** [comment]
For the record: I see this behaviour the last few months as well on my ASUS Nexus device. Actually, it happens quite often when navigating in my car, forcing me to park and restart my device.

**Comment by mathstuf** [comment]
Yep, this still happens for me too. However, if I lock the screen and unlock using the fingerprint reader (it can take a bit as the CPU and/or GPU is very busy when this happens), I can progress without a reboot.
