### ISSUE TITLE
Pedestrian navigation pathing corner cases

### ISSUE THREAD

**Issue by mathstuf** [osmandapp/Osmand#2424]
When pathing for pedestrian navigation (particularly in the back country), sometimes crazy routes will be created (e.g., going the wrong way and over mountains instead of staying on the flat sections). Things can usually be fixed by excluding trail sections which aren't important, but sometimes the pathing is a little ridiculous. Will try to upload screenshots tomorrow.

**Comment by mathstuf** [comment]
Path generated when going from a shelter in the Adirondack High Peaks (along John's Brook) to the Garden (the parking area):

![tmp_5791-screenshot_20160404-215058-1087737280](https://cloud.githubusercontent.com/assets/97253/14269318/35beab54-fab1-11e5-9a8f-f67890a0d819.png)

Zoom in showing the trail that is available between the two locations:

![tmp_5791-screenshot_20160404-214746164208083](https://cloud.githubusercontent.com/assets/97253/14269322/3f0a2666-fab1-11e5-8e29-61f435aa7957.png)

**Comment by mathstuf** [comment]
Hrm. Sorry about that, Octodroid isn't rendering the issue templates. I'll move this over to the group.

**Comment by vshcherb** [comment]
Fixed
