### ISSUE TITLE
Factor elevation into non-vehicle distance and pathing

### ISSUE THREAD

**Issue by mathstuf** [osmandapp/Osmand#2425]
It seems that GPX tracks are only calculated over a projection to a certain elevation. It'd be nice if contour information were available to factor that into distances. Also nice would be factoring elevation gains and losses into pathing and displaying it in the route summary.

**Comment by sonora** [comment]
Implemented, I think.

**Comment by mathstuf** [comment]
The analysis of GPX tracks does indeed have this information now. I don't know if it is factored into estimated travel time though.

**Comment by sonora** [comment]
It is for bicycle and pedestrian now, and a non issue for car mode, I think.

**Comment by mathstuf** [comment]
Cool, thanks. I look forward to using it this winter :) .
