### ISSUE TITLE
The card at the end of the journey needs some modifications

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2428]
When we reach the end of journey, OsmAnd presents a card with three options:

**You have arrived at your destination.**
1. Find a parking
2. Recalculate route
3. Finish Navigation. 

This needs the following changes:
 1. In the first option, remove "a" (the correct phrase is "Find parking")
   Optionally, use "Find parking nearby"

 2. There is no point in recalculating the route, unless you are able to move the blue dot (the current position) to the correct spot. For example, you may have actually reached the other side of a compound wall; and now you would like to navigate back to your destination. But unless you feed that information into OsmAnd, recalculation will not help.

 3. Add an option called "Set up return journey".
   When we reach the destination, most often we need to set up the return journey back to where we came from. This is useful when we are in strange cities; and do not know exactly where we started. So this option will help us go back exactly to the spot where we started.

**Comment by vshcherb** [comment]
Please feel free to create pull request for language corrections, other observations don't seem much important

**Comment by raindropsfromsky** [comment]
How about suggestion#3 (functionality to set return journey)?
