### ISSUE TITLE
Opening hours with public holiday 

### ISSUE THREAD

**Issue by HolgerJeromin** [osmandapp/Osmand#2429]
I added a opening hours of 

Mo-Su,PH 10:00-22:00

https://www.openstreetmap.org/node/3988669698

It is shown always closed.

**Comment by vshcherb** [comment]
Test that fails 

		hours = parseOpenedHours("Mo-Su, PH 10:00-22:00"); //$NON-NLS-1$
		System.out.println(hours);
		testOpened("08.08.2012 09:00", hours, false);
		testOpened("08.08.2012 21:50", hours, true);
		testOpened("10.08.2012 15:00", hours, true);

**Comment by HolgerJeromin** [comment]
Sa 18:00-24:00; Mo-Fr,Su,PH 12:00-14:00,18:00-24:00
Is not working, too

**Comment by vshcherb** [comment]
Fixed
