### ISSUE TITLE
Roads missing and distorted

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#2432]
While routing along yesterday, I noticed there were some bits of roads missing in the rendered map in Portugal, near Spain.

Gaps at main road (with or without Osm Live): 
Lat 42.06809 Lon -8.42712
![screenshot_2016-04-05-10-53-43](https://cloud.githubusercontent.com/assets/4006691/14278769/48e1b562-fb21-11e5-8813-6979d39846c4.png)

Distorted secondary road (it is now rendered straight in Osmand, but in reality it's all curvy), without Osm Live: 
Lat 42.07188 Lon -8.37513
![screenshot_2016-04-05-10-53-16](https://cloud.githubusercontent.com/assets/4006691/14278803/80ee4cae-fb21-11e5-877d-05c364f82b91.png)

Near same location, but with Osm Live active:
![screenshot_2016-04-05-10-51-16](https://cloud.githubusercontent.com/assets/4006691/14278842/bdfb112c-fb21-11e5-9d36-74d993cd70a3.png)

At first I thought it could be related with #2070 (Live Updates cutting lines), but even after removing the 'live' folder from the system and restarting Osmand, the gaps and distorted road still appear.

I've checked Osm map and it looks fine.

Routing seems to not be affected, and it shows the route correctly, but it doesn't render these roads at the missing parts.

Using yesterday night build, Android 4.4.2, Bq Aquaris E6

**Comment by Barrocas** [comment]
After some tests, discovered that after removing the Spain_galicia_europe.obf map file, the map rendering goes normal, no missing roads, neither distorted roads, even with Live Updates enabled.

![screenshot_2016-04-05-12-49-20](https://cloud.githubusercontent.com/assets/4006691/14280788/e0541d58-fb2c-11e5-8544-522d226e478f.png)

**Comment by Barrocas** [comment]
So the problem is when both maps are activated (Portugal + Spain_Galicia), maybe some border areas that are overlaping and that causes the map rendering issues?

**Comment by vshcherb** [comment]
Fixed. New diffs require new maps (will be generated 1st May) and diffs could be found here http://builder.osmand.net/aosmc/
