### ISSUE TITLE
Request: Avoid this spot... permanently (like favorites)

### ISSUE THREAD

**Issue by MaxC70** [osmandapp/Osmand#2433]
Hi All.
I'm a cyclist and often I plan routes with OsmAnd. It would be very useful that spot/roads to be avoided would be permanent and managed in a section, as the favorites.

It may be that,  for a user like Me, a particular spot is always to avoid  and he never want to go through.

I tested last nigthly build and avoid 'spot' ( [#2113](https://github.com/osmandapp/Osmand/issues/2113)) works correctly, avoiding only a part of the road. But restarting the application, spots to avoid are erased, and new calculated routes pass through them.

It would be nice to be able to set the points to avoid either temporarily (as now), or permanently, in a sort of black-list you may manage (as favorites).
In case of permanent avoid-spot, they should be shown on the map.

thank you,
MaxC.

**Comment by sonora** [comment]
Max, do you realize that out of 100 OsmAnd users, may be 2 or so may have this request, while 98 may find this is a strange complication, and some10 or so may actually have played with it, and  created some strange behavior which they were never able to explain and finally attributed to some strange OsmAnd bug? As a result this may either lead to 

It is not extremely often that I raise principle issues, but I feel that OpenSource Softeware is still used by 98% users without special nowhow, so we have to watch the we do not

**Comment by sonora** [comment]
Let us not cater for individual issues which would not be accepted by 98% of laymen users, but would potentially create obscure issues for them and support cases for us.

**Comment by mhyqwvcu** [comment]
@MaxC70 There is a third party plugin for OsmAnd, [Brouter](https://play.google.com/store/apps/details?id=btools.routingapp) that has exactly this functionality called [nogo areas](http://brouter.de/brouter/vianogo.html).

**Comment by MaxC70** [comment]
Thanks for the quick response.
I'll try to better explain the need, which I think might be useful to more than 2% of users :-).
Many cyclists planning their routes with various tools (Osmand and others), with waypoints, and save them in GPX files that will follow in the future. There are more points that a cyclist wants to always avoid (dangerous roads, bad asphalt, etc), despite for O.S.M. are passable.
These points are included in more paths within the same zone, or in a path that, saved, is repeated several times over time.
For this would be helpful if these points were not to be set every time before you start cycling, but could be saved on a blacklist, and OsmAnd exclude them from the routing.

This functionality is present in other software that I tested (MapFactor) and I think that does not confuse users. The road segments to avoid (blocked roads) are always highlighted in purple on the map, and manageable in a special list.

I'm sorry if I have not convinced you; however, with the latest changes (my request to turn on the screen only a few seconds to conserve battery, and the ability to jump missed waypoints while pedaling), OsmAnd remains the best navigator to plan and follow bike paths.

My congratulations to all of you.
I purchased the paid version of Amazon, but I think you deserve even a small donation :-)
Thank you,
MaxC.
P.S. I will try third-party plugins and I will let you know.

**Comment by vshcherb** [comment]
That could be implemented I think in OsmAnd itself especially for some simple cases.

**Comment by sonora** [comment]
Yes, true, now I understand, thanks! We have to make sure, though, it is visible that/when there are permanent exclusions and how to delete them again, or else we may create a major cause for support calls here.

**Comment by GaidamakUA** [comment]
It's already implemented. And I hope, soon it will be merged into main.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/pull/2670/files

**Comment by vshcherb** [comment]
Fixed
