### ISSUE TITLE
trip recording plugin: turn off annoying "0 m" notification

### ISSUE THREAD

**Issue by dingens** [osmandapp/Osmand#2437]
The trip recording plugin creates a notification saying "Trip recording (0 m)" _all the time_ while osmand is running, also when no trip is being recorded. This is extremely annoying (it made me turn off the plugin) and I see absolutely no reason for it (clicking it just opens osmand).

I suggest to just turn it off, as long as no trip is being recorded.

**Comment by sonora** [comment]
This is part of #2386, I have already fixed it last week!

**Comment by dingens** [comment]
Ah, cool, didn't spot that. Thanks! So we close that one here?
