### ISSUE TITLE
Update F-Droid repo

### ISSUE THREAD

**Issue by homersimpsons** [osmandapp/Osmand#2438]
Hi, 
Thank you a lot for Osmand. 
I notice that F-Droid repo is not updated with the latest version of osmand. Then, please, update this :)

**Comment by vshcherb** [comment]
Please open that issue on F-Droid repo, we don't maintain it.

**Comment by stragu** [comment]
Just FYI, the build failed for 2.3.3 on F-Droid, see the report: https://f-droid.org/wiki/page/net.osmand.plus/lastbuild_235

I am not sure what the problem is, do you think you could have a quick look to make sure it is indeed not on your side?

**Comment by homersimpsons** [comment]
I had published a issue : https://gitlab.com/fdroid/fdroiddata/issues/434
And they redirect me to this pull request : https://github.com/mvdan/OsmAnd-submodules/pull/18
I see that it's merge then maybe it will be fixed
