### ISSUE TITLE
please add narrow=yes to warning

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/Osmand#2439]
This is a nice to have warning.
narrow=yes is a dangerous part, where one car have to stop, so please add to OsmAnd.

**Comment by vshcherb** [comment]
I think it is also related to dangerous turn we don't add the signs cause the signs is better to see outside on the other hand voice notification would be good.

**Comment by aceman444** [comment]
The definition at http://wiki.openstreetmap.org/wiki/Key:narrow does not imply that one car has to stop (maybe only if you change lanes=2 to lanes=1 on a oneway=no road).

**Comment by hakuchi** [comment]
the possibility that one driver have to stop, is higher as on a normal road.
In Europe for a narrow existing street sings they say exactly who have to stop and who can pass first.


Site with this sing have to stop:
![image 1](https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Slovenia_road_sign_II-33.svg/120px-Slovenia_road_sign_II-33.svg.png)

Site with this sing can pass first:
![image 2](https://www.wiemann-lehrmittel.de/shop/media/images/ArtList/1380-Verkehrsschild-308-Vorrang-Vor-Gegenverkehr.jpg)

Right site have to stop, left can pass first:
![image 3](https://image.jimcdn.com/app/cms/image/transf/dimension=666x10000:format=gif/path/sb5b469c672f7a33d/image/i841c7099f36da278/version/1456096384/image.gif)

And some meters before the sings above are this sings:
![image 4](http://www.upps.at/shop/images/product_images/info_images/612_0.gif) ![image 5](http://www.upps.at/shop/images/product_images/info_images/613_0.gif)

**Comment by aceman444** [comment]
But there is no indication in the wiki text that the narrow=yes tag means this specific traffic sign. It only shows this sign in the picture. A road can be narrower just by going from 4m to 3m wide lanes, but cars can still pass without one of the stopping. That still meets the description on the wiki page.

For your scenario you would also need to tag the middle segment of the road (in the picture) with lanes=1 so that it is clear that cars must stop (or somehow avoid each other).

**Comment by hakuchi** [comment]
of course can a road going from 4m to 3m, but this is only a narrow, when the road go up to 4m after some meters.
Wiki says: highways or waterways get narrower for a **brief period of time**.
The tag narrow=yes is not to map one of this traffic sings, this tag is to map the narrower part of the way.

for this I think, OsmAnd should have ways with narrow=yes in the warnings and thinner line in rendering.

**Comment by hakuchi** [comment]
is this planned or still a nice to have?

**Comment by sonora** [comment]
No action planned here, I am afraid.
