### ISSUE TITLE
[Feature request] Enable announcement of "Nearest POIs"

### ISSUE THREAD

**Issue by chau-intl** [osmandapp/Osmand#2440]
When turning on Announcements in OSMAnd (Settings/Navigation settings/Announce...) and enabling _Nearest POI_ it works with specific POIs selected in Configure map/POI.../Food, Cafe and restaurant and so on. But if I select _Nearest POIs_ in configure map, I get no announcements.

Would it be possible to enable _Nearest POIs_ to be announcable?

**Comment by vshcherb** [comment]
Today poi announced related to your route, I think you can do it if you save Nearest POI as a custom filter, so you can enable it in the Waypoints dialog (Flag icon once route is calculated).
