### ISSUE TITLE
Add support for more area:highway values

### ISSUE THREAD

**Issue by pbb72** [osmandapp/Osmand#2444]
As far as I can tell from a quick scan of the source code, Osmand supports area:highway with 11 different values for common highway types.

Please add support for the following missing highway types:
- motorway
- trunk
- motorway_link
- trunk_link
- primary_link
- secondary_link
- tertiary_link
- living_street
- bridle_way
- steps
- path
- cycle_way
- proposed
- construction
- junction

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/73d98ce7bc36bf9758d409206fe9259b4ba8504d

**Comment by pbb72** [comment]
Has this been implemented into a nightly yet? Because I don't see any change. Check for example http://www.openstreetmap.org/way/168642128#map=19/53.93984/27.67069&layers=D (area:highway=primary) which is displayed, versus http://www.openstreetmap.org/way/168642132 (area:highway=trunk) which is not.

**Comment by xmd5a2** [comment]
New maps are required.

**Comment by pbb72** [comment]
Ah of course, the change is in the map files. Thanks! :+1:
