### ISSUE TITLE
Weird crossings and roundabouts

### ISSUE THREAD

**Issue by massic80** [osmandapp/Osmand#2448]
Hi,
I'm wondering why Osmand has weird behavior on certain crossings and roundabouts.
It sometimes tells me to make a complete loop in a roundabout, then quit on the (for instance) second exit (so, it tells me sixth exit in case of a for-roads roundabout).
In some other cases it tells me to take a road with no clear reason: for instance, on this route
https://www.openstreetmap.org/directions?engine=osrm_car&route=45.19359%2C7.64069%3B45.18796%2C7.64134#map=17/45.19077/7.64039
it tells me to take the first crossing row on the east (heading south), then turn left and go on, instead of the correct routing shown on OSM.
On the inverse, making the west-east route, it asks me to turn right into the crossing, then come back on the same road.
https://www.openstreetmap.org/directions?engine=osrm_car&route=45.18697%2C7.64366%3B45.19206%2C7.63122#map=18/45.18803/7.64265

**Comment by vshcherb** [comment]
1) Roundabout fixed
2) Not reproducible any more (possibly fixed earlier)
3) Add restrictions to the map itself (the reason is in the traffic_signals) there are different issues discussion whether it is reasonable or not to have traffic_signals as obstacle

**Comment by massic80** [comment]
1) Thanks for the intervention:
2) I'll check it out, thanks anyway
3) Finally I got a reason 😄 In fact traffic_signals as an obstacle are a hard discussion: In general, I hate them and I consider them an obstacle, but I would never "drive around a crossing" like in this issue for avoiding them ;) As of the restrictions I should add, it's technically not forbidden to drive that way... In Italy we say "dog biting its own tail" :)
