### ISSUE TITLE
incorrect housenumbers offered when there are capitalization variants of street name in OSM

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#2450]
Steps to reproduce:

Use map of Slovakia of 03.03.2016.
Search for addresses.
Select city Bratislava.
Type street 'krizi'
Notice two variants are offered, "Pri krizi" and "Pri Krizi" (different capitalization).
Choose any of them.
See offered house numbers.

Result:
If you choose any of the variants, you always get only the number 11 offered. Which is in OSM with "addr:street=Pri Krizi" tag.

That is wrong, the street has many more numbers in OSM data, under the "addr:street=Pri krizi" variant.

I have since fixed the house number 11 in OSM database, but you can reproduce the problem with that map snapshot.

**Comment by rominf** [comment]
Thank you for report, @aceman444.
It looks that this issue has been resolved. I've just verified it with latest OsmAnd version 2.3.5 and map of Slovakia of May 1.
Feel free to comment on this issue.

**Comment by aceman444** [comment]
You need to use map of 3.3.2016, only then you can claim it is fixed in any way.

I already said in the original report that I fixed the DATA in OSM. But it needs fix in OsmAnd address search too in case such a situation arises again (or already exists in other city/country).

This report should be reopened until you can provide link to OsmAnd source code where this situation is handled.

**Comment by rominf** [comment]
@aceman444, understood.

I'll try to reproduce this bug with old data in next few days and will reopen it in case it's still valid with new OsmAnd and MapCreator.

**Comment by rominf** [comment]
I've downloaded OSM dump of Bratislava of 03.03.2016 using Overpass API and generated a map with MapCreator and tested it with OsmAnd night build. Here is what I got:
![screenshot_20160605-095640](https://cloud.githubusercontent.com/assets/3449635/15804079/2ee4e014-2b0d-11e6-8bbe-605d8c332b80.png)
![screenshot_20160605-095650](https://cloud.githubusercontent.com/assets/3449635/15804080/2efefc88-2b0d-11e6-9434-a1625f6e4ab6.png)

I think that's a correct behaviour.

**Comment by aceman444** [comment]
OK, that would be the correct outcome. But I have now tried with OsmAnd 2.3.5 with map of 1st June, and street of "Stare Grunty". OsmAnd also offers "Stare grunty" and choosing any of the variant shows the same housenumbers. If it would be a sum of all housenumbers with any of the addr:street variant, that would be fine (but in my original report it wasn't).

Can you try that?

**Comment by rominf** [comment]
OK, I will look at this.

**Comment by rominf** [comment]
@aceman444, I've checked this street and found that lot's of streets like this one could be easily merged and already prepared PR fixing that: https://github.com/osmandapp/OsmAnd-tools/pull/123.

I suppose, July’s maps would include _good_ streets.

Thank you again!

**Comment by aceman444** [comment]
So you plan to merge the street names in the map creation process? So OsmAnd then operates on the cleaned up names with no duplicates? That is also a possibility, thanks!
