### ISSUE TITLE
GPX waypoints in My Places?

### ISSUE THREAD

**Issue by littlehelper** [osmandapp/Osmand#2451]
Hi,
I am wondering if it is possible to show and search for GPX waypoints or track points part of an active track (GPX file) in 'My Places'?
If not, what about adding them temporary, as long as the corresponding track is active (shown on the map), to 'My Places' to provide quick access to them? From my point of view, an additional page 'My track points' beside 'My favourites' and 'My tracks' under 'My Places' would be suitable for listing these waypoints.
To distinguish these GPX waypoints or track points from 'Favourites' I would prefer to see a different icon/symbol on the map rather than the star icon for favourites.
Greetings.

**Comment by sonora** [comment]
You are probably aware, but just to make sure: While the tab "Track points" is not available on the top level, it is available (per track) when  tapping (on the top level tab "My tracks") on any of the selected GPX tracks (which are all sorted near the top of that tab). So the tab you are looking for is already present, just one click further away than you are requesting.

GPX track point names are, however, not included in any search it seems.

**Comment by littlehelper** [comment]
Hi sonora,

Yes, I am aware that GPX **waypoints are shown as track points** per track. These waypoints are sorted as written in GPX file (if I am right) which totally makes sense but without bearing information (direction, distance).
First I thought that adding a separate view to list these **GPX waypoints like favourite waypoints** (sorted by name and shown with direction and distance) would be helpful to find waypoints more easily.
A solution I could go along with would be to add bearing information (direction, distance) to the GPX waypoints listed in tab 'Track points' of selected tracks and to add the **possibility to select how these points are sorted** e.g. sorted as written in GPX file (default), sorted by name, sorted by distance.

Looking at the nomenclature consisting of favourite waypoints, GPX waypoints, (GPX) tracks and track points, ...
From my point of view I find it confusing that GPX waypoints are listed as 'track points' because according to the [GPX file format](https://en.wikipedia.org/wiki/GPS_Exchange_Format) **waypoints are not the same as track points**.

In future I like to see a menu/tab where I can **enable and disable GPX files** and the corresponding waypoints, tracks (including track points) and/or route points out of active GPX files shall be listed in **separate tabs like 'GPX waypoints' (similar to 'My favourites'), 'GPX tracks', 'GPX track points' and 'GPX route points'**.

However, the option to **add GPX waypoints to the search index** would be very helpful.

Greetings

**Comment by sonora** [comment]
Ok, wording of the tab header now changed to "GPX waypoints" now, I think that is what we show there.

As for the other feedback, yes, I see some valid points, but this is the first request in this area ever, so it seems not an issue of widespread interest, I am afraid.

**Comment by sonora** [comment]
PS: I just notice that with a single tap on the star or map marker buttons on that tab you can add the GPX Waypoints to either group, so I would think these are very flexible and good workarounds. 

Particularly the map markers also offer a good heading display in the top bar or in widget view with arrows on the map.

**Comment by vshcherb** [comment]
I think the original request is planned in our roadmap. We are planning to evolve Map Markers to something like "Current Trip". So every GPX track could be selected as a "Current Trip". Today you can select all GPX points (actually they waypoitns or route points depends on the content) as Map Markers (descriptions and order will be preserved. Later it will be easier to do.
