### ISSUE TITLE
Turn handled as straight

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2452]
I currently see some work being done on lanes and turns, and wonder if this issue observed needs also be factored in or is a mapping issue: The right turn in the middle of the screenshot (near where the location marker is placed, where the route turns off the primary highway), is obviously recognized by OsmAnd' offline routing as "going straight" (routing description just says "Head ..."), and hence is in a navigation not announced (nor displayed) as any kind of turn.

![screenshot_2016-04-12-08-49-40](https://cloud.githubusercontent.com/assets/845735/14452084/4715c6d6-008c-11e6-8250-76cee28d29d1.png)

**Comment by CJTmmr** [comment]
Maybe related:
In latest nightly a turn to left is announced and shown as turn-around:
It is at [this](http://www.openstreetmap.org/directions?engine=osrm_car&route=52.02734%2C4.71856%3B52.02609%2C4.72068#map=18/52.02634/4.71860)  location:
![2016-04-12 06 10 46](https://cloud.githubusercontent.com/assets/15076257/14454641/d0052ad6-009b-11e6-9b30-ec90ecdcd8e4.png)

**Comment by vshcherb** [comment]
@sonora Usually if there is no turn:lanes then it is not guaranteed to work correctly, with slight turns it could be displayed as lane going straight. The mapping could fix that issue.
