### ISSUE TITLE
Persian (farsi) tts is corrupted

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#2453]
When I try to select "fa" tts in route configuration OsmAnd shows "Specified voice data is corrupted" message. _ttsconfig.p exists in "voice/fa-tts" dir.

**Comment by sonora** [comment]
Issue fixed, wrong delimiter characters had been used in 3 places.

On the occasion: fa-tts updated with latest features (traffic warning types, POI announcements, etc.). Some translations missing and some machine translations ought to be checked.
