### ISSUE TITLE
DownloadedRegionsLayer displayed erroneously

### ISSUE THREAD

**Issue by siggie0815** [osmandapp/Osmand#2459]
On my device the downloaded (green) and selected (yellow) regions are displayed erroneously. The opaque  polygons are distorted and also move somehow connected to the current view. As this is hard to explain in words, I took a short screencast:

https://drive.google.com/file/d/0B_45r8bsup--QzhqQVdWaFFDTTA/view?usp=sharing

I could only observe this behavior on one device (Android 5.0 on Xiaomi Redmi Note 2). The behavior is observable on both the free and plus versions. I tried to get more information using the development plugin but I could see nothing useful.

Might be related to #1749 #1939

**Comment by crimean** [comment]
@siggie0815 Do you use Live updates (OSM Live)?

**Comment by siggie0815** [comment]
No, I don't think so... Live Updates are disabled in the menu. Also the problem was observable before  the update to 2.3.x.

**Comment by sonora** [comment]
Deprecated or not?

**Comment by siggie0815** [comment]
Well on my new Phone this does not occur any more, and as there were no other reports on this issue, one could say so.

**Comment by sonora** [comment]
Ok, let us close this for now.
