### ISSUE TITLE
please add phone:mobile=... in POI

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/Osmand#2462]
In OSM are used _phone=..._ and _phone:mobile=..._ on some POI.
sometimes no one is responding on phone so I will contact on the mobile number.
Please add the mobile number(with some other symbol) in the description.

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/cb7f46a0020044a20539453dccca7a68ba22689d
