### ISSUE TITLE
please add "destination:lang:<lang code>" and "destination:lang:<lang code>:lanes"

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/Osmand#2463]
OsmAnd is supporting name:en, name:it, name:fr ect.

Please also add:
```
destination:lang:<lang code>
destination:lang:<lang code>:backward
destination:lang:<lang code>:forward
destination:lang:<lang code>:lanes
destination:lang:<lang code>:lanes:backward
destination:lang:<lang code>:lanes:forward
```

**Comment by sonora** [comment]
destination:lang:<lang code> already supported for some time, also :forward/backward.

Combinations of both not, I think, but this is rather complex, and maybe not the very highest priority, I would say (the more combinations we consider, the fewer occurrences we are talking about).

I think I am not planning on much further dev work for this any time soon.
