### ISSUE TITLE
Mulitpolygons crossing map boundary completely broken?

### ISSUE THREAD

**Issue by RicoZ-OSM** [osmandapp/Osmand#2464]
Some time ago I have reported https://github.com/osmandapp/Osmand/issues/1814, now with 2.3.3 and a recent Bavaria map update  the problem did get worse. Not only is the forest still missing but also the multipolygon representing the riverbanks of the river Walchen/Ache is missing.

eg 
http://www.openstreetmap.org/way/224678349
http://www.openstreetmap.org/way/230568501

are completely missing, only the river line is drawn.

**Comment by RicoZ-OSM** [comment]
Tested with the map of Austria, the multipolygons are shown correctly there (both this and #1814  issue). The multipolygons should appear in the Bavaria map as well as a significant part of them is on Bavarian territory.

Anyway.. rendering seems perfectly ok, the problem seems to be realted to splitting OSM data along the Bavarian border and might hit other borders as well?

**Comment by vshcherb** [comment]
Should be ok with new maps, can you please test? We found out that we used a buggy version of osmconvert before.

**Comment by RicoZ-OSM** [comment]
Not much improvement.  Forest polygon is displayed in low detail zoom levels (scale showing 5km and larger) but completely missing in more detailed views.

No visible change with the missing river polygons from the other issue.

Height lines in Polynesia still broken.

Rendering of SavusSavu and Taveuni/Fiji not improved. It seems that everything between 179.86464 (2m accuracy) and 180 is clipped away. May not seem like much but thats more than the whole island of Taveuni. Could not find any OSM object associated with the 179.86464 cutoff line.
