### ISSUE TITLE
Coastline updates for world map stuck? Please update/fix Huahine Iti.

### ISSUE THREAD

**Issue by RicoZ-OSM** [osmandapp/Osmand#2465]
The coastline for Huahine Iti is missing in the world overview map
http://www.openstreetmap.org/way/96660137

It has been accidentally deleted by a local mapper ( http://www.openstreetmap.org/changeset/28554441 ) more than a year ago and was fixed not long after that by me (http://www.openstreetmap.org/changeset/29233919). Apparently the OsmAnd world map was last updated exactly while it was broken?

**Comment by vshcherb** [comment]
OsmAnd doesn't uses OSM Data for world map.

**Comment by RicoZ-OSM** [comment]
No matter how, the land-plygon of Huahine-Iti is missing. You can see the road but it is in the middle of ocean.

**Comment by vshcherb** [comment]
We have plans to update it, let's see.

**Comment by RicoZ-OSM** [comment]
16 months later - Huahine-Iti is still missing. Would you mind reopening this so it does not get lost completely?

**Comment by vshcherb** [comment]
We will try to update basemap coastlines, so far it is a manual and very time consuming process.
