### ISSUE TITLE
[Request] POI - amenity=sanitary_dump_station

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#2466]
Could the tag 'amenity=sanitary_dump_station' be added to the available POI?

Sometimes I want to add it as a POI, and other users would like to be able to search for it.
When mapped in Osm, it's not rendered in Osmand.

https://groups.google.com/forum/m/#!topic/osmand/nTa9pP75jc4

https://groups.google.com/forum/m/#!topic/osmand/YS7r9Ndkh00

**Comment by homersimpsons** [comment]
To wait this implementation, you can use [Overpass](https://overpass-turbo.eu/):
you select a area, then cut and paste this query:
`node
  [amenity=sanitary_dump_station]
  ({{bbox}});
out;`
you execute and export data in gpx.
you paste that data in osmand/track folder in your device and activate this from map configuration/GPX track and check the box.
Each white star in a red circle is a sanitary dump station.

**Comment by xmd5a2** [comment]
Fixed
https://github.com/osmandapp/OsmAnd-resources/commit/16892d8b2fc00dd422abfb2fef967d5ccd05eeac

**Comment by pebogufi** [comment]
Did you realize that there ist not only a 
amenity=sanitary_dump_station
but as well a
sanitary_dump_station=yes 

see https://groups.google.com/forum/#!topic/osmand/nTa9pP75jc4
thanks for solving both tags.

@homersimpsons 
Thanks for that nice workaround !!!

**Comment by xmd5a2** [comment]
@pebogufi these tags are already supported
https://github.com/osmandapp/OsmAnd-resources/blob/master/poi/poi_types.xml#L724

**Comment by pebogufi** [comment]
I don't want do bother you, but...
If I search near a wellknown sanitary_dump_station with "Nearest POI", nothing is found, so I don't think that they are allready on the map.
Tested with several POIs, much older than createdate of map.
Thanks.

**Comment by xmd5a2** [comment]
This will work only with new maps (and OsmAnd). Better to wait for the beginning of may.

**Comment by pebogufi** [comment]
Test of map
with the latest map german_baden-wuerttemberg_europe with 
https://overpass-turbo.eu
    node   [amenity=sanitary_dump_station]   ({{bbox}}); out;
    node   [sanitary_dump_station=yes]         ({{bbox}}); out;
---> Both kinds if POI are now on the map. (checked with nearest POI)


Test of osmand 2.4.0#16554M (may 25)
---> there is a new search-term for sanitary_dump_station.
This search-term finds 
**ALL** of  amenity=sanitary_dump_station
but **NOTHING** of sanitary_dump_station=yes

Please check that again.
Thanks and regards Peter

**Comment by xmd5a2** [comment]
sanitary_dump_station=yes is ADDITIONAL tag and can't be searched directly in current OsmAnd. It should appear in context menu of camp_sites or something.

**Comment by homersimpsons** [comment]
@pebogufi note that you can tag this yourself on osm.org
