### ISSUE TITLE
GPX waypoints in Directions From:/To:

### ISSUE THREAD

**Issue by littlehelper** [osmandapp/Osmand#2468]
Hi,
I love to use Osmand for planning my trips. I manage several GPX files (currently in Osmand called tracks) with GPX waypoints since it is easier to share these files with desktop applications than using groups of favourites from my point of view.

My suggestion would be to add the possibility to choose from GPX waypoints of active GPX files ("tracks" shown on map) when selecting "From:" and "To:" in the Directions menu:
Currently Osmand provides the possibilities to choose "My position", "Favourite...", "Select on map" and "Address...". I would love to see "GPX waypoints..." there too.

Greetings

**Comment by sonora** [comment]
Supported, as follows:

Either tap on any GPX waypoint's icon on the map to get to its context menu, or go to "Menu / MyPlaces /MyTracks", select a track, go to its GPX waypoints tab, and tap the waypoint you need.
