### ISSUE TITLE
Address search for Liechtenstein not working

### ISSUE THREAD

**Issue by barilla-aldente** [osmandapp/Osmand#2471]
can't use address search for Liechtenstein , when i type the city/zipcode in for one of the 11 town in this small country, no of them appearing on the screen.
![screencast_2016-04-17-14-56-01](https://cloud.githubusercontent.com/assets/4014688/14587445/8effd54c-04b3-11e6-9194-a23d04da6e02.gif)
Reverse geocoding is working and
 when i use inspector the output seams correct.
```
/tmp/testmap$ ./inspector.sh -vaddress Liechtenstein_europe.obf |grep City
		City [VILLAGE] Balzers 240100249	(111)
		City [VILLAGE] Eschen 3022807519	(130)
		City [VILLAGE] Gamprin 240080206	(40)
		City [VILLAGE] Gamprin-Bendern 240070712	(15)
		City [VILLAGE] Mauren 3022807520	(83)
		City [VILLAGE] Nendeln 240046176	(11)
		City [VILLAGE] Planken 32011242	(19)
		City [VILLAGE] Rotenboden 935278226	(8)
		City [VILLAGE] Ruggell 240120066	(53)
		City [VILLAGE] Schaan 240079149	(152)
		City [VILLAGE] Schaanwald 240060684	(10)
		City [VILLAGE] Schellenberg 240077147	(47)
		City [VILLAGE] Triesen 240092661	(94)
		City [VILLAGE] Triesenberg 240106262	(122)
		City [VILLAGE] Vaduz 1932181216	(163)
		City [HAMLET] Ebenholz 3577169505	(5)
		City [HAMLET] Malbun 347290636	(4)
		City [HAMLET] Oberplanken 32011241	(2)
		City [HAMLET] Steg 1796218506	(2)

```
This screencast is record on osmand~ 2.3.3. but this issue was existing on earlier version to. (include google play verion of it)
Map tested with :
-self build map  with OsmAndMapCreator.sh:
-http://download.osmand.net/list.php ( version 01.03.2016)
-osmand inapp download (version 01.03.2016)

**Comment by kompowiec** [comment]
proably isn't related with application... (no address point on the OSM):
![not related](https://cloud.githubusercontent.com/assets/15860246/14768795/81433a82-0a4b-11e6-85e3-7ba55a38f677.png)
]
IMO to close.

**Comment by barilla-aldente** [comment]
good example this building in this area are mapped not long ago...
https://www.openstreetmap.org/changeset/38455120 but  this is like most building in this country they not jet tagged with address, some  have address tag like [Gapont 3,Triesen](http://nominatim.openstreetmap.org/search?q="gapont 3,Triesen") .  For me that is not the issue i can not even choose a town/village, of course i can not chose a street in osmand. Reverse geocoding working:
![screenshot](https://cloud.githubusercontent.com/assets/4014688/14847329/50db1b3e-0c68-11e6-9e60-7e98be91b132.png)

This working also for building with no address tag (street only) but i can't find any  this street/town with osmand address search, (my self i use often Nominatim workaround but that is not a solution for everyone, like my parents)

**Comment by kompowiec** [comment]
Nominatim default give street closed to the road, if users isn't marked.

**Comment by rominf** [comment]
@barilla-aldente 
Next night build will contain the fix.
Feel free to comment on this issue again, if it's not working for you.
