### ISSUE TITLE
Erase all waypoints in the route.

### ISSUE THREAD

**Issue by sdesimeur** [osmandapp/Osmand#2472]
There is no way to erase all the waypoints of a navigation's route in once time.

**Comment by kompowiec** [comment]
it's in newest version (2.2.4) where add markers.

**Comment by vshcherb** [comment]
It is not exactly clear where did you expect it, though today is possible to use flexible map markers to define a route (there is clear button there).

**Comment by andkirby** [comment]
@vshcherb could you please guide me where is the clear button? I want to remove this red route.

iOS 14.x, the app is up to date. 

![4CF06EA2-4ECC-4D88-896F-DE9D6EC30630](https://user-images.githubusercontent.com/1828532/135414139-9165cdc7-b66d-4133-86be-ab8db72ca3ae.png)
![A0611DF8-A33C-45A0-BEF9-66F0424026CA](https://user-images.githubusercontent.com/1828532/135414147-03d3eb43-19fd-4059-b249-d3417be61994.png)
