### ISSUE TITLE
Upcoming POI announcement contains strange characters/words

### ISSUE THREAD

**Issue by chau-intl** [osmandapp/Osmand#2473]
I'm using the Danish TTS to announce POI's. When I'm about 1 kilometer from the POI the voice announcement says something like (translated from Danish):

_In 1 kilometer_ & RU _ RU POI . _description of POI._

The strange part is the "& RU _ RU POI .", or pronounced: "And are you underscore are you POI dot".

Is this in some way intentional?

**Comment by sonora** [comment]
Think I caught it, and 2 other issues as well in that file.  (One is that Traffic warning types should be announced now, too. The other one was  a small distance announcement issue,

Please test in latest nightly (or next release), and report here if you still find an issue,

**Comment by chau-intl** [comment]
Hi Sonora.

I have tested a nightly from a couple of days ago and both the issue with strange announcements and the warning types seems to work perfectly now. I can't comment on the distance issue you found though.

Thanks!
