### ISSUE TITLE
Can't read everything from the 'OSM Live' map menu 

### ISSUE THREAD

**Issue by Phyxion** [osmandapp/Osmand#2475]
If you click the three dots to get the map menu from OSM Live, I can only read a small portion of the 'Update' text as the remaining text is under a white block.

**Comment by GaidamakUA** [comment]
@Phyxion can you attach screenshot please.

**Comment by Phyxion** [comment]
http://i.imgur.com/P1dblAU.png

Only seems to happen in landscape.
