### ISSUE TITLE
Save Current GPX track doesn't start recording over

### ISSUE THREAD

**Issue by vrtareg** [osmandapp/Osmand#2479]
Hi

I have noticed that now pressing GPX Recording widget and choosing "Save Current GPX track" option no longer zeroing and resetting the GPX Recording. 

It was working a while ago. 

Am I missing any new features or improvements? 

Regards, 
Areg

**Comment by crimean** [comment]
Cannot reproduce. 
What OsmAnd and Android version do you have?

**Comment by vrtareg** [comment]
Hi

It is on Samsung Note 4 with Android 5.1.1 and latest OSMAND. 

Sometimes hitting save doesn't do that on a first time. 
Retry doing the job. 

Regards, 
Areg
