### ISSUE TITLE
Voice guidance reading out full destination on motorway multiple times

### ISSUE THREAD

**Issue by kerosin** [osmandapp/Osmand#2486]
Hey,

One thing that really annoyed me when using OsmAnd Navigation:
The voice guidance repeated all destinations mentioned on a sign 2-3 times on a stretch less than 1kilometer.

Here is the route:
http://www.openstreetmap.org/directions?engine=osrm_car&route=54.3127%2C10.0816%3B54.3137%2C10.1053#map=17/54.31456/10.10117

I would suggest that the full destination list is only read out once.

Thanks for this great project!

**Comment by kompowiec** [comment]
In OsmAnd can you setting frequency:
setttings-->Navigation set-->Repeat navigation instructions

if that was it, of course.

**Comment by kerosin** [comment]
This is set to "Only manually (by tapping on arrow)"

**Comment by sonora** [comment]
Yes, we have recently changed this, see also issue #2377 and discussion there after the change.

The full destination is now only read for the pre-announcement (After about 1 km ...) and a second time after the turn in announcements (In 500 m turn ...), while it is deleted for the extreme long-distance and the last "turn now" prompt, which tended to make it extremely crowded in clover-leaf motorway intersections. Please test with our attest nightly or wait for he next release, and report here if you still have an issue,.
