### ISSUE TITLE
Transifex translations

### ISSUE THREAD

**Issue by unaizalakain** [osmandapp/Osmand#2488]
Three years ago, I created a Transifex project so that me and a couple of friends could easily translate OsmAnd to basque. It wasn't an official OsmAnd project, but more of an ad hoc thing. We translated OsmAnd to basque and got our translations into the master.

Since then, without me noticing, people has submitted many translations to the Transifex project. For some reason, I didn't receive email notifications for the messages people sent me on Transifex. Recently, one of the translators contacted me by email asking about the current state of affairs.

I would want to merge all these translations on Transifex into OsmAnd, so that they don't get lost. I pushed to Transifex the changes to the source file and translations, and then pulled the translations from Transifex into my working copy.

What I'm afraid of is that it might be the case that some of these translations are wrong because they are based on an out-of-date source. Maybe we could only merge translations that are on Transifex but that are not in master, so we don't override correct translations in master with out-of-date translations from Transifex.

Together with that, I would propose removing the Transifex configuration (at `.tx`), and the Transifex project altogether, and leave the Weblate project as the only source for translations.

**Comment by vshcherb** [comment]
I'm afraid today there should be more or less a manual check for each translation to avoid conflicts. For this work it would be great to create a pull-request.

**Comment by unaizalakain** [comment]
People has submitted translated content for quite a few different languages. I can only manually check the ones in basque and spanish.

What are the possible issues with submitting a PR with only the translations that translate strings that aren't already translated, for all languages?

**Comment by vshcherb** [comment]
If they are already translated to different language then I'm afraid we need to contact people from weblate and ask them to merge what's missing. If it is not present at all, then it is easier.

**Comment by unaizalakain** [comment]
Would it be acceptable to create a new branch with all the translated content so that translators on weblate can slowly merge those changes?

**Comment by vshcherb** [comment]
I think yes, by creating pull-request it would mean a branch.

**Comment by unaizalakain** [comment]
https://github.com/osmandapp/Osmand/pull/2512
