### ISSUE TITLE
Path for avnotes and poi_modifications.osc should be changeable by user

### ISSUE THREAD

**Issue by bitnapper** [osmandapp/Osmand#2492]
I use Osmand a lot for taking notes withe the editor plugin and taking photos for later use in JOSM. After survey I move them to the folder DCIM/osmand because my DCIM folder is automatically synced to my other devices. Out of convinience I'd prefer not to sync the osmand folder and osmand/avnotes (avnotes would be ok but the whole osmand folder is to much with all the other stuff).

It would be great if osmand had an option to set the path for photo, audio and video notes manually to a different location and also have the poi_modifications.osc automatically stored in a location of my choice.

**Comment by sonora** [comment]
There are severe limitations of choice now with the latest Android restrictions. Non-system apps can only access their own file tree (on external storage, but I guess this is where you would want this data).)
