### ISSUE TITLE
Wrong unit for speed used in statistics of tracks

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#2493]
In statistics of tracks spead is measured in min/km instead of km/hour at
- avarage speed (DE:Durchschnittsgeschwindigkeit)
- max speed (DE:Maxmimale Geschwindigkeit)
Version 2.4.0#16531

![screenshot_2016-04-24-16-26-41](https://cloud.githubusercontent.com/assets/18628183/14768230/ac36f576-0a3c-11e6-9529-45af05eeec7f.png)

**Comment by kompowiec** [comment]
can try this: settings-->navigation-->speed measurement?

**Comment by pebogufi** [comment]
It was correct on km/h, but I changed it to a different value, saved it, then changed it back to km/h. Then the refered values in the statistic where correct in km/h. 
So I suppose, it is a wrong or missing intialisation of this setting, because the smartphone is brandnew, I just installed osmand a few days before.
Thanks a lot, Peter

**Comment by vshcherb** [comment]
It is an interesting issue, this speed measurement are displayed in the Pedestrian profile. May be you switched in the application so it affected all UI.
