### ISSUE TITLE
Add current and maxspeed parameters to speed_alarm

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#2496]
Could we please get the numeric speed limit and the the currently driven speed as parameters into in CommandBuilder's speedAlarm() function?

This would allow more concise and helpful announcements such as
"This road is 50" or "Drive 50 not 67" instead of the stilted "you are exceeding the speed limit".

**Comment by vshcherb** [comment]
Nice idea.

**Comment by kompowiec** [comment]
I don't want to duplicate topics so i'll just add that is similar annoying message: New route has been calculated AND arrive/pass POI... the replace whenever first part of words - not better do simply: you pass POI? without and/next?

**Comment by polarbearing** [comment]
Not duplicate topics is generally a good idea, however, your issue is completely unrelated. My issue needs a parameter coming from the code internals. 

Your phrase is defined for English [here](https://github.com/osmandapp/OsmAnd-resources/blob/master/voice/en/ttsconfig.p) in section ```%NEARBY POINTS```.  The German version indeed uses 'dann' (then). These files are locally on your device in the 'voice' subfolder, you can play with them and test better phrasing, and come up with a specific proposal.

**Comment by kompowiec** [comment]
I used polish voice and can't simply use better formulation (my english isn't perfect).

>These files are locally on your device in the 'voice' subfolder, you can play with them and test better phrasing, and come up with a specific proposal.
Maybe i try, i think so even on ported on other lang (actually someone written in pascal [rolling eyes]) but i don't promise anything.

**Comment by polarbearing** [comment]
Actually the language files ```ttsconfig.p``` are in Prolog, not Pascal, to represent the grammar of different human languages.

**Comment by kompowiec** [comment]
Oh possible.. simply my vim detected file type as pascal (strange by the way).

**Comment by sonora** [comment]
Regarding the speed limit:
Guys, it is really hard to please everyone ... :)

I have no issue implementing something like a numeric speed limit prompt, but may I please draw your attention to Issue #1739, which in my experience also represents a large portion of our user community.

So we can either try to please everyone by offering lots of customization settings. That I know bothers many people and has a very negative impact on how users feel about an app "being complicated". 
Or we can go a middle route, which is pretty much what is implemented.

I have also looked at many other nav systems, because if in doubt, I tend to go with what is "conventional". And a majority of them seem to announce warnings by type, i.e. more specific than a "beep", but then display further details only on screen.

Regarding @kompowiec : Can I please ask you to test this again with the latest nightly build, because there have been some changes since you commented. Can I then please ask you to open a separate issue here so I can fix that for you. I need to identify if you are talking about a wording issue (some voice files have weird placeholders which were never translated correctly), or some other bug. I need to know which voice language you are talking about, and we need to compare with what you hear in that same situation when you switch to TTS English vice. Please also describe when this occurs, like e.g. does this happen only when in navigation settings you have check ""Announce Nearby POI" ? Does it only happen  when the route is really recalculated, or all the time? 

Thx - Hardy

**Comment by polarbearing** [comment]
Hard to keep two issues in one track here, can they be separated by the project owners?
Regarding the speed limit:
Even in the cited #1739, people are in favour of short verbal announcements including the allowed speed. Having those variables available in the TTS files makes it configurable for the advanced user at least, and we can gain some experience.

**Comment by sonora** [comment]
Yes, I can do it by expanding announceSpeedAlarm() to announceSpeedAlarm(speedAlarm.getIntValue, loc.getSpeed) and adjusting the command builder accordingly . It requires code changes in several places, eventually including all our productive tts files (even to just ignore the new parameters initially), so I would like to wait for Victor's opinion before implementation.

**Comment by polarbearing** [comment]
I could help with a PR for the TTS files once the syntax for the call is clear.

**Comment by kompowiec** [comment]
#2606

**Comment by sonora** [comment]
@polarbearing : Thanks, I have worked a bit on this today and have created the main project pull request, but do want Victor to review it.

If it gets merged, I also need to go to all 34 productive tts files and replace the string
"speed_alarm()" by "speed_alarm(_MaxSpeed, _Speed)" so they continue to work, but I have a tool which can quickly do that.

Then, if you want to experiment, I suggest on your device you locate the "voice" folder in the OsmAnd folder (often something like .../Android/data/net.osmand.plus/files/voice), in it create a new folder called "en_test-tts", and in it place a copy of the _ttsconfig.p from the "en" folder.

In that file (you do not need pull requests!) you can simply experiment with a statement like
`speed_alarm(MaxSpeed, Speed) -- ['exceed_limit.ogg', I, J] :- num_atom(MaxSpeed, I), num_atom(Speed, J).
`
Go to Menu/Settings/OsmandDevelopment/TestVoicePrompts/en_test.tts/ExceedingSpeed-button to test your work (you need to temporarily select a different tts-voice every time you access the menu for it to properly initiate).

I currently pass maxSpeed as an integer, and speed as a float. Not sure that is ideal, but this is how they occur in the next upstream code.

Issues which need testing include distance unit chosen, metric/miles conversion, rounding effects by this conversion, etc. For conversion we should of course re-use the existing distance unit conversion code as much as possible.

**Comment by sonora** [comment]
PS: maxSpeed is already unit-converted. 

I think I will in the production tts generally convert the  prompt to saying "Speed limit: XX !".  (XX being the maxSpeed, without announcing the current speed). This is short, I hope a good compromise for everyone, and I can reasonably produce it from all existing translations.

**Comment by sonora** [comment]
Fixed.

**Comment by polarbearing** [comment]
Thanks a lot @sonora, I tested yesterday with the voice tester, and today while driving. 

For those who want to implement the extended version in their local tts file, [here](https://github.com/osmandapp/OsmAnd-resources/commit/2112fafb2dfa7211e64f7af1b3da260f3232547e#commitcomment-17671350) is a statement that also converts the current speed from m/s into km/h before announcing. I need a deeper look into the prolog books to see if the intermediate variable K could be avoided.

**Comment by sonora** [comment]
Very welcome.

From reading all the feedback on your voice routing in recent months I definitely conclude most users prefer shorter prompts over longer ones. Hence I advice against also adding the current speed to the voice prompts for the general public. Still, I have provided the 'Speed' parameter to be passed to TTS, so you may create a custom _ttsconfig.p file and put it locally on your device if you need it for special purposes.

**Comment by polarbearing** [comment]
Fully agree. My plan was to get an optimised statement as a %commented line for those interested.

**Comment by sonora** [comment]
Ok! In this case, if you want to make it more general, you also need to run the "Speed" parameter through a  possible miles conversion (if that is what is set as unit in the app), similar to how we do it for distances (use same code, I think). But as that code may differ some for different grammars (mostly complex plurals) in some languages, it may not generally work with just one line of code. 

Maybe not worth the effort, though, people will get the idea from what you already specified above, and take it from there if needed.
