### ISSUE TITLE
When any new OsmAnd nightly is installed, it fails to load the map

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2498]
Currently using OsmAnd 2.3.0#16193M

The problem is, when any new OsmAnd nightly is installed, it fails to load the map. The screen only shows the current location and direction (in other words, the blue dot, blue circle and swiveling cone).

If I close the OsmAnd and restart, the map appears normally.

**Comment by vshcherb** [comment]
Minor issue I guess, for me it is not reproducible.
