### ISSUE TITLE
information pane is missing grip in device landscape mode

### ISSUE THREAD

**Issue by martenjj** [osmandapp/Osmand#2502]
As I found out on #2146, it is possible to dismiss the information pane that appears when long pressing on the map, together with the orange marker, by sliding the pane away using the 3-dots grip on its edge.  Unfortunately, although the grip appears correctly and works in portrait mode, it does not appear in landscape.  See the attached screen shot.

The pane can be dismissed by either pressing on the map outside it or by using Back, but this means that the orange marker stays on the map.
![screenshot_2016-04-28-16-53-28](https://cloud.githubusercontent.com/assets/10631760/14892603/79b044a2-0d63-11e6-8b52-13c872271d6f.png)

**Comment by vshcherb** [comment]
That's a known issue for landscape mode cause there is no grip here and sliding action is intercepted by main menu (drawer).

**Comment by sonora** [comment]
Same as #3053.
