### ISSUE TITLE
[Feature request] Add the advanced search by tags

### ISSUE THREAD

**Issue by mchapliuk** [osmandapp/Osmand#2503]
For instance: I want to find all tyres services, not car repair station and not tyres shops.

If I select POI filter `Tyres` - I'll see only tyres shop
If I select POI filter 'Car Repair' - I'll see the all car repair stations, and then I have to click on each icon and look for 'tyres' service in it.

It would be great to add advanced search option and create detailed search request.

Or user can choose `Car Repair station` POI and then click on the `Advanced Search` and choose what kind of service he is looking for.

(Tyre service is just an example)

P.S. I couldn't find such issues
P.P.S I've found similar issue #1156, but it describes only religion objects

**Comment by kompowiec** [comment]
IMO nice to have. Not when it creates tags in OSM that you couldn't find them. Even if it would be checked bench have backrest :P

**Comment by mchapliuk** [comment]
@kompowiec Ok, not search by tags, but create detalization for some entities. For instance, I need an atm machine with `cash in` - so, when you choose `atm`, you can detail your search with its possible options: 

- bank name
- cash in
- etc...

**Comment by RicoZ-OSM** [comment]
See also #2209

**Comment by sonora** [comment]
Deprecated with new search interface, I think.

**Comment by Suncatcher** [comment]
>> Deprecated with new search interface, I think.

Could you please describe why it is deprecated? How can one search by tags?
