### ISSUE TITLE
Wrong color for communal road(ref=GS/SC...) in Italy

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/Osmand#2504]
OsmAnd using same background color for state-, provincial- and communal road.

Osmand should use correct colors in Italy:
Background color **blue** for:
[Street view **SS**](https://www.google.at/maps/@46.7293017,12.2650298,3a,25.8y,61.42h,83.44t/data=!3m6!1e1!3m4!1suh-8hyYrFXdLI8QURzyeoA!2e0!7i13312!8i6656?hl=en)
[Street view **SP**](https://www.google.at/maps/@46.0317409,10.8689532,3a,23.4y,356.39h,86.03t/data=!3m7!1e1!3m5!1s8b7BqFKqcmps1IuxvnrcSg!2e0!5s20111001T000000!7i13312!8i6656?hl=en)
[Street view **LS/SP**](https://www.google.at/maps/@46.6539261,11.1462901,3a,16.8y,200.72h,90.07t/data=!3m6!1e1!3m4!1sbY_A4Hbp41BbHroT8dVOug!2e0!7i13312!8i6656?hl=it)

Background collor **white** for:
[Street view **GS/SC**](https://www.google.at/maps/@46.8828282,11.4485501,3a,64.9y,107.68h,64.57t/data=!3m6!1e1!3m4!1sgNkrIgS0AcWB9j_a3EEpFQ!2e0!7i13312!8i6656?hl=de)
**SC**

![image] (http://fs5.directupload.net/images/user/160430/99i62sxu.png)

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/c11bebb61697ae8a32382d0f0b7faa23d8d6f68e
