### ISSUE TITLE
OSM live: duplicate POI on the map

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#2506]
I moved POI and downloaded live updates. Result: duplicate POI on map (not in search)
https://www.openstreetmap.org/node/3160921836
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot_2016-05-01-17-58-58.png
https://overpass-api.de/achavi/?changeset=39014986

**Comment by vshcherb** [comment]
The issue is wider none of the old POI are deleted. So if you delete a POI it will stay on the map.
The proper fix will require changing id for POI which might break released version for OSM Editing.

**Comment by sonora** [comment]
Let us merge with #3034, sounds closely related.
