### ISSUE TITLE
Local names display is broken

### ISSUE THREAD

**Issue by jafd** [osmandapp/Osmand#2507]
The local names display as of 2.3.5 seems totally broken.

First, the "local names" display setting is effectively ignored, and display language is used instead. That is, when my display language is Polish, I see Polish labels in Ukraine, which is exactly the wrong thing.

Second, when "local names" is used, many streets in Wrocław and Szczecin are shown in German. I understand the cities were German at some point in time, but as of 2016, these street names are not used for at least 71 years.

**Comment by jafd** [comment]
Sorry, will edit this issue, mobile github interface is weird

**Comment by vshcherb** [comment]
Did you check that is not running in Safe Mode?

**Comment by xmd5a2** [comment]
@jafd Please provide some screenshots and links to objects. Cant' find anything you described.
