### ISSUE TITLE
OSM Live: map doesn't changes when fixme tag is removed

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#2508]
I moved bus stop and removed fixme tag from it.
https://www.openstreetmap.org/node/3160921836
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot_2016-05-01-17-58-58.png
https://overpass-api.de/achavi/?changeset=39014986
New bus stop position is to the bottom. Fixme icon is displayed at the old place.

**Comment by vshcherb** [comment]
Fixed
