### ISSUE TITLE
Trivial, short bike routing suggests huge detour - unlike car or pedestrian route

### ISSUE THREAD

**Issue by lvml** [osmandapp/Osmand#2509]
Management summary: When asking Osmand to route from '50.131, 8.672' to '50.137, 8672' in "bike" mode, a 1.17 km long route with a huge detour is suggested, while "car" and "pedestrian" modes yield reasonable routes of only 0.7 km length, which would also be much better for biking.

(This is just one example of very unreasonable inner-city bike routings of which I experienced a lot lately - this is the most trivial/short one exposing the problem easily reproduceable.)

Details:

OsmAnd Version:  OsmAnd~ 2.2.4
Android: 4.4.2
Offline map used: "Germany Hesse" (as of April 1st 2016 - updating this map from older versions didn't change the behaviour).
OsmAnd's in-app offline routing used.

Expected routing would be like the "car" routing is: Just staying on the street going north until the one turn to the right required to get to the destination. But in "bike" mode, a huge detour with 3 turns is suggested.

Bike mode:
![osmand_bike](https://cloud.githubusercontent.com/assets/9969397/14944406/8d5e5b74-0ff2-11e6-838f-8c613f22ba36.jpg)

Car mode:
![osmand_car](https://cloud.githubusercontent.com/assets/9969397/14944407/9693f622-0ff2-11e6-867f-4b4d2cdf73f1.jpg)

BTW: I would be willing to experiment with changing "routing.xml" to tweak bike routing, and I was wondering whether I can edit routing.xml and make osmand use it without recompiling the App from the source code. I found advice on this at https://groups.google.com/forum/#!msg/osmand/JmMQ0bQV68I/8PZlDwTtiOAJ: 

> https://github.com/osmandapp/OsmAnd-jni/blob/master/java/net/osmand/router/routing.xml
> 
> Put it to /sdcard/osmand

However, `/sdcard/osmand` does not exist on the Android device I installed osmand on.

Is the existing `/Phone/osmand/` just as well?
And can you hint on what in routing.xml would need to get tweaked to make the bike routing "more car like" in above example?

**Comment by scaidermern** [comment]
[Way 4746899](https://www.openstreetmap.org/way/4746899) (Eduard-Rüppell-Straße) has tags *oneway=yes* and *cycleway=opposite* meaning that bicycles are allowed to drive against the oneway direction. Is this combination wrongly interpreted by osmand? In the screenshots above it seems like osmand *only* allows bicycles to drive in the opposite direction.

**Comment by kompowiec** [comment]
You can try Brouter too ;) and and compare the results.

**Comment by lvml** [comment]
@kompowiec I have tried Brouter (installed from fdroid.org), but it doesn't work for me, when Brouter is selected as the bike router, Osmand only says `Error calculating route: Brouter service is not available`. I also find it odd that I need to keep a complete, large, second set of map data stored and up to date on the device to use Brouter - if it could utilize the maps already downloaded for Osmand, that would be way more efficient.

**Comment by vshcherb** [comment]
>  oneway=yes and cycleway=opposite 
OsmAnd allows to use way in both ways https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#L511. Is it incorrect?

**Comment by lvml** [comment]
It's absolutely ok that OsmAnd allows biking in the opposite "one way" direction of the destination street, the only thing incorrect is that there would be no reason to go that way because it's much shorter here to bike in the direction of the destination street that is also allowed for cars.

**Comment by vshcherb** [comment]
P.S. answering the first question, routing.xml is stored in the same folder as all maps. It varies from device to device

**Comment by vshcherb** [comment]
I took a risk and increased based on many requests speed of primary roads (https://github.com/osmandapp/OsmAnd-resources/commit/0cc6e39a2cac31b6b0d279de5142de248957caa7) that primary/secondary/tertiary are not different in sense of speed they are different because of priorities, so it should be a setting to avoid primary/secondary road.

Small deviation is related to lots of traffic signals and crossing which routing tries to avoid (you can see routing.xml section obstacle)
https://www.dropbox.com/s/b1s6xqufqmnp3xy/Screenshot%202016-05-08%2001.06.33.png?dl=0

**Comment by lvml** [comment]
Hmm. Putting the current routing.xml into /Phone/osmand/ didn't change the detour-routing described above. But I doubt this changed routing.xml is used at all - when I make some arbitrary to it and copy it, Osmand doesn't seem to notice. (And yes, of course I did end / restart Osmand after copying routing.xml.)

Is there any way to find out why Osmand doesn't seem to use the changed routing.xml?

**Comment by vshcherb** [comment]
You can forbid some roads in the routing.xml (access section) or also you could try to change it in OsmAndMapCreator there it should be more obvious using settings.

**Comment by lvml** [comment]
I meanwhile updated to [Osmand version 2.3.5 from f-droid.org](https://f-droid.org/repository/browse/?fdfilter=osmand&fdid=net.osmand.plus) - this changed neither the odd bicycle routing nor the non-relevance of a modified "routing.xml" file when stored in the osmand/ directory.

Since bicycle routing is essentially unusable in this state for me, I re-tried installing brouter, and this time succeeded. It's pretty cumbersome to keep brouter updated with another set of maps, I'm also missing the spoken announcements of street-names when navigating with brouter, but at least the routes computed by brouter for bicycles do make sense.
