### ISSUE TITLE
Pedestrian crossings not shown

### ISSUE THREAD

**Issue by PinkDuck** [osmandapp/Osmand#2510]
Using 2.3.5 on Android 4.4.4 with UniRS or OsmAnd style in pedestrian view/rule mode:

I find that crossings tagged as:

highway=crossing
crossing=uncontrolled // A marked on road but pedestrian self-risk crossing

or

highway=crossing
crossing=uncontrolled
crossing_ref=zebra // This is typical British white/black striped Zebra crossing with foot priority

are **not** rendered with a pedestrian icon regardless of zoom level or participation in a way.

For example OSM+OBF see [Crossings.zip](https://github.com/osmandapp/Osmand/files/245282/Crossings.zip) in JOSM and OsmAnd.

I think they should be as it causes wasted effort otherwise in thinking that they haven't been mapped.

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/c98f45ff7857427b8378a9c80b9d55560ff8b38e
