### ISSUE TITLE
ghost lines showing in higher zoom

### ISSUE THREAD

**Issue by gorn** [osmandapp/Osmand#2511]
There are strange lines showing on some rare places. Here is how to reproduce:

Have a look at  geo:6.268544,1.7850057?z=13
http://osmand.net/go?lat=6.268544&lon=1.7850057&z=13

there are strange lines diagonally crossing the screen. 

More info:

- I have Android OsmAnd+ ver 2.3.3 installed
- using offline maps
- I have Czech republic and World downloaded (in case it is important)

**Comment by vshcherb** [comment]
That's related to the old live updates, please remove old live updates and download new version of application (2.3.5).
New maps are in process and will be delivered soon.

**Comment by gorn** [comment]
It worked, thanks.
