### ISSUE TITLE
Turn off GPS while viewing the Wiki screen

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2514]
We do, and rightly so, turn off the location service while you are e.g. on any of our settings or help screens, because it is not needed there and this saves battery power.

I think we should do the same for the Wiki article screen shown below: We have developed OsmAnd far enough so it can be used as a travel guide book (using our offline Wikipedia capability). And I have watched people sitting in museums or churches reading the respective Wiki articles in OsmAnd, while the device in the background was heavily draining its battery trying to uselessly find a GPS fix.

<img width="270" alt="wiki-article" src="https://cloud.githubusercontent.com/assets/845735/15025279/c6fdf752-1238-11e6-8957-c26e768fa07b.png">

**Comment by sonora** [comment]
Looks like we are talking about POIMapLayer.java/showWiki(...).  Sensor activity is stopped for other screens via MapActivity.java going onPause(), but this does not happen for the showWiki screen.

**Comment by vshcherb** [comment]
Wikipedia is not an activity it is a dialog fragment. If you read for 2-3 minutes I think it is harmless. When GPS is setup it doesn't take much power.

There is a big advantage dialog vs activity, dialogs are much more responsive.
