### ISSUE TITLE
Separate POI subcategory for guideposts in tourism

### ISSUE THREAD

**Issue by littlehelper** [osmandapp/Osmand#2515]
Hi,
As already suggested in #1492, from my point of view, it would make sense to show guideposts as 'guideposts' rather than 'tourist information'.
Many guideposts on mountains are tagged with tourism=information and information=guidepost as suggested [here](http://wiki.openstreetmap.org/wiki/Tag:information%3Dguidepost). Currently Osmand shows these guideposts as 'tourist information', which is irritating.
Please, add a separate subcategory 'guidepost' in the POI category 'tourism' for these guideposts.
Greeting

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/960b48368e483b62e6f58fd6fb29a45eefb9180e
