### ISSUE TITLE
Most of the dialogs on Configure Map don't have Cancel button

### ISSUE THREAD

**Issue by vrtareg** [osmandapp/Osmand#2516]
Hi

I have noticed that most of the dialog windows in Configure Map screen doesn't have Cancel button. 

Only dialog windows with multi select has Cancel and Ok combination. 

The rest you need to assume to press back button to go back.

It will be visually better to have at least Cancel in place to make screens consistent. 

Regards, 
Areg

**Comment by vshcherb** [comment]
Don't agree. Single selection - don't, multiple - do (more details, transport). Also now POI, GPX, Underlay, Overlay are redesigned.
