### ISSUE TITLE
Add support of maxspeed values RU:motorway and other XX:motorway

### ISSUE THREAD

**Issue by DinamikGitHub** [osmandapp/Osmand#2517]
They say, that there is no support of maxspeed value RU:motorway now. There is support of RU:urban (60) and RU:rural (90), but no support of RU:motorway. When you are travelling across street with maxspeed=RU:motorway, programm doesn't show maxspeed limit.

RU:motorway means 110. I think, we should add support of this value.

Also, please, check support of RU:living_street (means 20), IT:motorway (means 130), RO:motorway (means 130), UK:motorway (means 70 mph).

See http://wiki.openstreetmap.org/wiki/Speed_limits

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/b730d9153d501340b592ff4247d57f8b827d0fcc
