### ISSUE TITLE
Route action yellow arrows obscure road information

### ISSUE THREAD

**Issue by njohnston** [osmandapp/Osmand#2523]
OsmAnd overlays routes with yellow action arrows at turns, roundabouts and other places.

Unlike the purple route overlay, these yellow arrows (which are actually a small yellow arrow joined to a path shaped along the route) are fully opaque, so they obscure details beneath.

The problem is most noticeable for short routes with many turns, which is common in urban areas. Often street names are completely obscured, as are road or path types, for example:

![opaque_yellow_arrow](https://cloud.githubusercontent.com/assets/638458/15075852/75d9a8c8-139e-11e6-8ed0-7d1c7b0949b1.jpg)

Please make the yellow arrows semi-transparent so details beneath can be seen.

I tried adding an alpha component to nav_arrow in res/values/colors.xml, but this made no difference.

I made some changes to net/osmand/plus/views/RouteLayer.java:
- In `initUI()` I added:

```
    actionPaint.setAlpha(125);
    paintIconAction.setAlpha(125);
```
- In `updatePaints()` I added:

```
    actionPaint.setAlpha(125);
```

With this change, the arrows are semi-transparent:

![semi_transparent_yellow_arrow](https://cloud.githubusercontent.com/assets/638458/15075858/82670e0a-139e-11e6-9ff9-5738fa78f77c.jpg)

(I don't know why the arrowhead is lighter than the path connected to it.)

Please make the arrows transparent. You don't need to use the amount of alpha that I did--I just used a relatively high value to make the change obvious.

**Comment by vshcherb** [comment]
I think it is a rendering bug, we should write labels over lines and that would not be a problem.

**Comment by njohnston** [comment]
Writing labels over lines would make the labels (like street names) readable, but could still obscure the road or path type. For example, I wouldn't be able to see if I was being routed along a road or path.

**Comment by vshcherb** [comment]
The color of action labels is customizable via rendering style though I don't feel comfortable with so much transparent lines.

**Comment by njohnston** [comment]
Where can these be customised in the rendering XML? I'd like to change it locally for myself for now :)

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-resources/blob/master/rendering_styles/default.render.xml#L176 color_3, you can ovewrite in depends.style and put it rendering styles folder

**Comment by sonora** [comment]
Transparent on transparent and then on various solid backgrounds in deed yields rather unpredictable results, often looking very "washed out".

A possible mitigation could be continue to use the clearly visible solid yellow, but make the arrows thinner. Inspecting our code I just find we do not actually support  strokeWidth_3 but use a hardcoded action arrow style. So if we wanted to explore that we would need to enhance out code in RouteLayer.java. Not sure it's worth it, though.

**Comment by sonora** [comment]
PS: In the map style "Toruing view" I do actually use a thinner route line width to mitigate the issue: In this fashion, at least at close-up zooms, like where the auto-zoom feature puts you for intersections, you can see the road type by it being slightly wider than the route line. This doe not, however, solve the issue that the road name is obscured.

**Comment by sonora** [comment]
No further action planned.
