### ISSUE TITLE
What happened to Spanish voice? (Spain)

### ISSUE THREAD

**Issue by Yajo** [osmandapp/Osmand#2527]
Since some moment in last month OsmAnd's Spanish TTS voice switched from a Spain Spanish to a Mexican Spanish.

In my phone's settings I have Spain Spanish but no luck.

I feel way more comfortable with the old voice, is there any way you could revert it, or give the choice between Spanish Spanish or Mexican Spanish? Or to make OsmAnd use android's built-in TTS engine?

Thank you!

**Comment by sonora** [comment]
Yajo, from what I can see at a first glance, no change was made to the Spanish tts voice in about 4 months.

OsmAnd does in fact completely use your device's tts engine and all its settings. Are you sure you have not made any changes there, or changed devices? Please go to your Android's (not OsmAnd's) tts settings, pick "Listen to an example" and see how it sounds there.

If you still have an issue, please specify more detailed what it is, wording or pronunciation, and specify a specific command so I can reproduce.

Thanks, Hardy

**Comment by Yajo** [comment]
In the example it's Spain Spanish. I changed some Android settings and put all of them back as they were just to "force reset" somehow and it seems to work.

But if you use system's tts I'm puzzled about why ever does OsmAnd need TTS language packs :confused:

**Comment by sonora** [comment]
The tts language  file you install in OsmAnd is not a language pack, OsmAnd uses the language pack(s) you install in your device's tts engine. The file you activate in OsmAnd contains the actual commands, i.e. their wording, word order, etc.

**Comment by Yajo** [comment]
Ah of course, interesting. Thanks for the support and sorry for the not-bug :sweat_smile:
