### ISSUE TITLE
UK (and maybe other) road shields regressed in 1st May map update

### ISSUE THREAD

**Issue by njohnston** [osmandapp/Osmand#2530]
I'm using OsmAnd 2.3.5 on a Samsung Galaxy S5. I updated my local maps of England to the 1st May edition, and noticed that shields on A (main) roads are no longer displayed correctly.

They are now displayed the same way as B (secondary) roads:

![broken_shields_england](https://cloud.githubusercontent.com/assets/638458/15109275/8d9e0b30-15d2-11e6-8fb8-61309e218fa6.jpg)

Note the A46, A417 and A435 shields. They should have a green background with yellow text as shown here:

![correct_shields_england](https://cloud.githubusercontent.com/assets/638458/15109281/97b17d5a-15d2-11e6-904b-6699c4d69eb7.jpg)

I'm fairly sure this is a map-related problem. I still have an older (4th March) map of Northern Ireland, which uses the same road signage as England. Shields on A roads there are displayed correctly.

Other countries might be affected too. With the updated Singapore map, shields on motorways don't seem to be shown correctly. Note the SLE, TPE and ECP shields here:

![broken_shields_singapore](https://cloud.githubusercontent.com/assets/638458/15109288/a2b76818-15d2-11e6-88bc-28231a0e16d0.jpg)

(I don't have a before comparison for this, sorry. These shields should be shown on a blue background with white text.)

**Comment by xmd5a2** [comment]
Gb shields fixed (wait for a day for regenerated maps). Regarding Singapore. I do not find any reliable information about road shields. Can you provide some sort of evidence?

**Comment by njohnston** [comment]
@xmd5a2 sorry for the slow reply. I found a screenshot of OsmAnd showing a map of Singapore from March. You can see that the motorways have shields with white text on a blue background:

![singaore_shields_correct](https://cloud.githubusercontent.com/assets/638458/15563667/7730a718-233d-11e6-967b-1dc0fc20e0a5.jpg)

This [Singapore government site](http://www.onemotoring.com.sg/publish/onemotoring/en/on_the_roads/traffic_management/traffic_signs.html) has some details on the traffic signs used. You can see motorways like BKE and PIE shown in white on a blue background.

**Comment by xmd5a2** [comment]
Road shields on your screenshots are old-style. Earlier all motorways has blue shields. But OK, I added blue background to all shields at motorways. https://github.com/osmandapp/OsmAnd-resources/commit/b8fced70229f4eed26e3d8b76af7d33e1bc4776f
