### ISSUE TITLE
Roads not showed at high zoom level

### ISSUE THREAD

**Issue by FrancescoCellepathy** [osmandapp/Osmand#2531]
I noticed that very often the Map Renderer of OSMand map doesn't draw part of the roads. 

I found these tickets talking about the same problem:
https://github.com/osmandapp/Osmand/issues/1248
https://github.com/osmandapp/Osmand/issues/1385
https://github.com/osmandapp/Osmand/issues/1686

In my opinion this is caused by the rendering algorithm. 
The actual rendering algorithm doesn't draw a way if none of the nodes that compose the way are showed on the screen. Is it correct?
 
This problem shows more often when the zoom is high (>17). This confirms my theory because with high zoom level the probability that a straight way doesn't have nodes shown on the map increases significantly. 

Is that right? If yes, does OSMand 2.3 correct this (I am using 2.2)?Or is someone handling this correction/problem in a future version?

**Comment by vshcherb** [comment]
These are different problems, 2 out of 3 are fixed. Please provide screenshots to be sure.

You assumption is not correct.

**Comment by FrancescoCellepathy** [comment]
Thank you for answering.

Here is a link to a video showing the problem:
https://www.dropbox.com/s/ki74cgakqxwvb7c/uiproblem.mp4?dl=0

**Comment by andrew-davie** [comment]
Looks like the same basic clipping bug to me that culls line-draws if it thinks the line is totally offscreen.  We see this in the route line drawing, too.

**Comment by vshcherb** [comment]
It was recently fixed via pull request https://github.com/osmandapp/Osmand/commit/7fd2802efefc89d5098aa0aedefca4b604324fc7
