### ISSUE TITLE
Settings icon disappears after one use

### ISSUE THREAD

**Issue by techlady** [osmandapp/Osmand#2533]
I have been trying to update the storage location so I can use maps from the SD card. While reading suggestions, I was wondering why I could not find the "Settings" tab everyone was referring to. I rebooted and three parallel lines appeared at the top left corner of the screen. They were not there before. It seems that the "Settings" icon disappears and is replaced by an icon that looks like the "layers" icon in OSM whenever you return to the OSMAnd main page. To change any more setting you have to reboot the phone.
Android is 4.4.2
The phone is an LG Tribute
The OSMAnd app has been moved to the SD card.
The SD card has been used only with this phone

**Comment by sonora** [comment]
OsmAnd's "Menu" button is in the lower left corner of the map screen.  (But you should also get to the OsmAnd's Menu if, while on the map screen, you tap the device's menu button, if it has one).

If you tap the OsmAnd menu button (lower left corner of the map screen, as I say), either the menu will appear directly, or you will get to what we call the "Dashboard", showing the last used favorites, etc. What you get first (Dashboard or Menu) can be configured: If you see the Dashboard, there is a button in the upper right corner allowing to select what behavior you want.

From the Dashboard screen, you can go to Menu by tapping the upper left corner (the button has now in deed moved there). Reversely, form the Menu there is an option to go to the Dashboard (near the top of the menu, second entry or so).

If your device behaves any different, please post a screenshot so we know what you are talking abut.

Thanks, Hardy

**Comment by vshcherb** [comment]
Application restart should be enough, not sure why reboot is needed.
