### ISSUE TITLE
Offer to download/update overlay/underlay maps

### ISSUE THREAD

**Issue by littlehelper** [osmandapp/Osmand#2534]
If raster maps are selected as main map in "Map source..." the options "Update map" and "Download map" appear in the 3-dot-menu after long-tabbing on the map. Downloading raster maps in this manner by selecting the maximum zoom to preload is great!

It would be comfortable if these options also appear if the "Offline vector maps" are selected as main map and raster maps are activated as overlay/underlay maps to download/update these raster maps. Regardless of whether "Download map" or "Update map", I suggest that the subsequent menues to download or update should provide at least two checkboxes (one for overlay and one for underlay) to select whether (1) the raster map used as overlay map, (2) the raster map used as underlay map or (3) both raster maps shall be downloaded or updated.

An additional checkbox could be inserted to allow downloading/updating the offline vector map of the corresponding region too.

**Comment by sonora** [comment]
No action planned, it seems.
