### ISSUE TITLE
Crashes during navigation according to GPX route.

### ISSUE THREAD

**Issue by devanes** [osmandapp/Osmand#2536]
I used Osmand+ for the first time for navigation using an externally created GPX route. I used a bicycle.

After a while the app crashed. I was driving quit fast at the time, so I may have missed one of the points making up the track. The fact that after this first crash Osmand tried to get me to turn back and redo a section of the route seems to point to this.

Later during the same trip, Osmand crashed again and kept crashing over and over again. When I had the time to quietly look at this I saw a question indicating the route was lost and asking me whether I want to continue with the route. This seems to default to yes after which the app crashes again. After I selected no, the crashes stopped.

This makes the app unusable for this kind of navigation for me. If I miss a point, but am still on the route, navigation should just continue where I am, not trying to redirect me to the missed point and most definitely not crash.
Also it should be possible to take a detour without losing the route or having to answer questions. There might be traffic conditions or just an interesting thing along the route causing a detour. Just (using a different coloured line for example) redirect to a suitable point on the route, without asking a question which requires interaction which may not always be possible during driving/biking. And again it should not crash. Losing a route is no reason for crashing.

Exception log shows (over 30 times):

> Version  OsmAnd+ 2.3.5
> 06.05.2016 12:23:04
> Apk Version : 2.3.5 238
> Exception occured in thread Thread[main,5,main] : 
> java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
> 	at net.osmand.plus.helpers.WaypointDialogHelper.updatePointInfoView(WaypointDialogHelper.java:187)
> 	at net.osmand.plus.views.mapwidgets.MapInfoWidgetsFactory$TopTextView.updateWaypoint(MapInfoWidgetsFactory.java:322)
> 	at net.osmand.plus.views.mapwidgets.MapInfoWidgetsFactory$TopTextView.updateInfo(MapInfoWidgetsFactory.java:267)
> 	at net.osmand.plus.views.MapInfoLayer.onDraw(MapInfoLayer.java:276)
> 	at net.osmand.plus.views.OsmandMapTileView.drawOverMap(OsmandMapTileView.java:592)
> 	at net.osmand.plus.views.OsmandMapTileView.refreshMapInternal(OsmandMapTileView.java:527)
> 	at net.osmand.plus.views.OsmandMapTileView.access$900(OsmandMapTileView.java:62)
> 	at net.osmand.plus.views.OsmandMapTileView$3.run(OsmandMapTileView.java:665)
> 	at android.os.Handler.handleCallback(Handler.java:739)
> 	at android.os.Handler.dispatchMessage(Handler.java:95)
> 	at android.os.Looper.loop(Looper.java:135)
> 	at android.app.ActivityThread.main(ActivityThread.java:5255)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at java.lang.reflect.Method.invoke(Method.java:372)
> 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

I used a Cat S40 smartphone using Android 5.1 and map of the Netherlands with contour lines and hillshade layer enabled.

If you need any more info, let me know.

**Comment by vshcherb** [comment]
Thanks for feedback.

**Comment by marco44** [comment]
I got the exact dame issue today. I dont think it occured un previous versions.

**Comment by GaidamakUA** [comment]
Routing algorithm hasn't changed but app shouldn't crash anymore.

**Comment by marco44** [comment]
Just to confirm, I just tested the daily apk with a complex GPX route, problem solved :)
