### ISSUE TITLE
Feature request: cross-cutting rendering priority for ways and polygons

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#2538]
In current rendering engine ways can't be lower than polygons. I propose to introduce cross-cutting rendering order. This will solve things like https://github.com/osmandapp/Osmand/issues/2236
This issue requires next rendering order of elements:

- river (way)
- water (polygon)
- bridge (polygon)

In rendering style element orders will be like this: water (10), river (20), polygonal bridge (30)

**Comment by RicoZ-OSM** [comment]
I think that makes sense although I don't quite understand why rivers should be above  water polygons.

Some time ago I tried to summarise the issue in more detail here:
http://wiki.openstreetmap.org/wiki/Key:layer#Data_consumers

In particular I found it useful to do a clean pure 3D model first and then use  "visual priorities" to do the rendering. Visual priorities can override the rendering that would result from the pure 3D model but doing it explicitly means that you know why you are doing it.

**Comment by xmd5a2** [comment]
Yes, rivers should be under water polygons

**Comment by vshcherb** [comment]
OSM Link http://www.openstreetmap.org/#map=19/47.28035/11.19822&layers=N

**Comment by vshcherb** [comment]
Implemented, style could be updated
