### ISSUE TITLE
FR: able to search countries when base world map available

### ISSUE THREAD

**Issue by keunes** [osmandapp/Osmand#2539]
Call me stupid, but my geographical memmory isn't too good. When friends speak of far-away countries they have visited, I often want to quickly check where exactly it is located.

I have the world overview map (or whatever the proper English name might be) installed, and would like to be able to search countries as this data is available anyway. I imagine it could work as follows:
- menu -> search -> address; tapping on 'country'
- the downloaded countries/regions are displayed on top (as the case now)
- when starting to type a country, OsmAnd searches the world base map for countries, and shows the relevant results (similar to how searching for postal codes work)
- when selecting the country:
 - all other fields are greyed out, or
 - the user immediately gets shown the map with the full country in the screen<br />
As other levels cannot be set, there is no point in keep showing the address search view, except in the case a user might have mis-tapped. In all other cases it's just taking away the step 'tap on the 'show on map' icon'

**Comment by Paviluf** [comment]
"Region" should replaced by "Country" to make a search. I have a standalone GPS and this is how it work. Now I often have to search on Wikipedia to find in what region the address I want to go is :(

OsmAnd "just" have to make the search in all the maps that correspond to the Country and add the region (region + postal/zip codes) name to the results.

It will be great too to have the possibility to download a full country map.

Thanks !

**Comment by keunes** [comment]
> "Region" should be replaced by "Country" to make a search. I have a standalone GPS and this is how it work. Now I often have to search on Wikipedia to find in what region the address I want to go is [@pauviluf]

I guess that's another question than mine for which you'd have to create another issue. Your proposal doesn't affect me, but can imagine it would be nice.

**Comment by Paviluf** [comment]
Done https://github.com/osmandapp/Osmand/issues/2594

**Comment by vshcherb** [comment]
BTW it is available FR: able to search countries when base world map available #2539.
You can search it in POI "Search by name"

**Comment by keunes** [comment]
Oh wow. A country could hardly be called a 'point of interest' so i would still keep (ie: reopen) this FR to improve usability of the app.

Thanks anyway for helping me :)

**Comment by homersimpsons** [comment]
And it's impossible to fill adress search with this method...

**Comment by keunes** [comment]
> And it's impossible to fill adress search with this method [@homersimpsons]

Can you explain why you think this is the case? I really don't see how this makes finding addresses impossible.

**Comment by homersimpsons** [comment]
It's possible to get to the city/village, but then it's impossible to fill adress search to go to a specific road and number

**Comment by keunes** [comment]
> It's possible to get to the city/village, but then it's impossible to fill adress search to go to a specific road and number  [@homersimpsons]

Sorry, I still don't get your point. If you didn't download the map of a specific country/region and select that country/region (or a city within that country/region), then it is totally expected that you cannot search a specific road and number. But what's the problem then?

---
@vshcherb Would you mind reopening this issue? Even though only 'nice to have' it improves usability + it would make it possible to search for bigger cities included in the world map (not necessarily possible via POI's)

**Comment by homersimpsons** [comment]
I've region map downloaded, and I would like to avoid to search on Internet which region is this city. Thanks to this work around I can go directly to a city, but it's impossible to go to a specific adress (road + number/intersection). Then it would be useful that Osmand can fill adress search with current city/region selected (reverse geo?). There are 19 region in France, and it's hard to know for each city/village the region it is located.

**Comment by keunes** [comment]
> I've region map downloaded, and I would like to avoid to search on Internet which region is this city. Thanks to this work around I can go directly to a city, but it's impossible to ...

Ah, so that still concerns the other issue (#2594), not this current feature request. Please go there and copy-paste your feedback there to show your support :)

**Comment by keunes** [comment]
@vshcherb @sonora Could this issue be reopened please? Even though only 'nice to have' it improves usability + it would make it possible to search for bigger cities included in the world map (not necessarily possible via POI's, which has been suggested above).

**Comment by vshcherb** [comment]
Countries are searchable via POI

**Comment by keunes** [comment]
Yes, you're right. It seems I haven't explained myself clear enough, so let me give it another try:

Let's replace 'searchable' by '(easily) findable'.
1) POI search is not the first place users will check if they're looking for a city;
2) If you're trying to find a city via POI search results get massively polluted with unwanted items. Let me give an example: I live in The Netherlands, say I want to search for 'Brussels', the first item *actually in Brussels* is over 50th (I stopped counting at 53rd item). Try that for any (major) city and you'll have the same issue.

So I guess what I'm trying to say is: sure it's *possible to search* cities via POI search, but it's *not* the most user-friendly way to *find* cities.

Trying to look at it this way, might that change your line of thinking @vshcherb? (I'm not trying to force you to say 'yes I'll implement it', rather I'm trying to get your opinion on my arguments). Hoping to hear back ;)
