### ISSUE TITLE
Intruduce consistent translation policy

### ISSUE THREAD

**Issue by verdulo** [osmandapp/Osmand#2542]
I really cannot understand why some incomplete (even not started) translations are included in the program, for example Armenian - 5.5%, while another - for example Chinese - 100% are not.

My proposition:
1. All translations completed in at least 90% on Weblate (I count only 'Android' phrases pool, not 'Phrases' or 'iOS') should be in program, currently only 'Chinese (Traditional)' is missing.
2. Languages translated in 50-90% should be available in program and marked as 'incomplete', add 'Esperanto' and 'Chinese (Simplified)'.
3. If complete translation after some update goes below 90%, then mark is as 'incomplete', if some incomplete translation goes below 50%, then DO NOT remove it unless it goes below 20%, for example don't remove Hebrew, only mark it as 'incomplete'. Languages to be removed from the program (translated in less than 20%): Welsh, Armenian, Bosnian, Indonesian, Albanian.

Why in 'Map preferred language' there's Volapuk included, but not another constructed languages (Esperanto, Interlingua) with far more speakers?

**Comment by vshcherb** [comment]
1. 'Map preferred language' is based on OSM popularity, though I agree Volapuk might be excluded.
2. All translated languages are available in the program they are not selectable in OsmAnd UI, but if you change language for Android, they will appear. I agree traditional chinese is missing in the list because it is widely spoken language.
3. Incomplete/complete translations that's all manual work that somebody needs to monitory and sometimes update, it is searchable in the code and could be always updated i.e. pull-request.

**Comment by verdulo** [comment]
2. The problem is, that Esperanto cannot be selected in Android settings. It's already translated in 60%, could you please make it selectable in OsmAnd UI?

**Comment by homersimpsons** [comment]
Or why don't just display All languages with percentage (only if it's not >95%) ? For example :
"English 
French
Deutsh
Volapuk (10%)
Italian (92%) etc... "
Percentage given are arbitrarily. 

This percentage could be calculated on the first display of language selection and then store

**Comment by sonora** [comment]
I have performed a one-time maintenance as follows:
- Added all languages with more then marginal translation rates (>~10%)
- Display all with less than ~80% with "incomplete" suffix
- Also will try to added all regional variants, with these same rules, but this needs a bit more time

This is not extremely dynamic, I think no automatism is needed here. If you think you want to point out a change is needed for any language, please post an issue or pull request.
