### ISSUE TITLE
Exclude pedestrian streets for bike route calculation, except when destination is there

### ISSUE THREAD

**Issue by keunes** [osmandapp/Osmand#2544]
A couple of times I was **cycling** and the **internal OsmAnd routing** sent me over a pedestrian street.

Example case:
When cycling from Zwijndrecht train station to Rotterdam (both NL) I missed some instructions and ended up [here](http://www.openstreetmap.org/?mlat=51.85840&mlon=4.54363#map=18/51.85840/4.54363). From there, OsmAnd sent me over [this 'street'](https://www.openstreetmap.org/way/159401954), which is not the most convenient route: the indicated street is actually pavement around the dressing rooms & canteen of the football club. It is not an ongoing path and you have to cross a kerb. As you can see in the image below, there's a bike path left from all the football fields which OsmAnd probably have taken with the following proposal implemented.

Therefore, I'd propose:
Avoid pedestrian streets in route calculations, unless a route point/destination is on that pedestrian street. I would do that always, although I can also imagine an extra option "Avoid footpaths" like there already is 'Avoid stairs' (both may be badly translated from Dutch).

![screenshot_2016-05-14-13-02-33](https://cloud.githubusercontent.com/assets/11229646/15268173/6e884370-19d6-11e6-837f-6b5b1289af18.png)

(BTW a similar issue appeared when I somehow got directed through [this small alley](https://www.openstreetmap.org/way/28325512). Allowed: yes. Convenient: not at all. Faster than the streets around it: nope.

**Comment by scaidermern** [comment]
Whether highway=pedestrian is appropriate depends on whether you want to prefer speed or safety. Usually driving on highway=pedestrian is slower than for example highway=residential or highway=cycleway since you have to take care of pedestrians. But on the other side highway=pedestrian is more safer to use than say highway=residential.

Ideally the user should be able to select his/her preference (speed or safety) via a radio button? Will make the UI a little more complicated, though.

**Comment by keunes** [comment]
> Ideally the user should be able to select his/her preference (speed or safety) via a radio button [@scaidermern]

So that's kind of the same like my proposal, right?

> I would do that always, although I can also imagine an extra option "Avoid footpaths" like there already is 'Avoid stairs' (both may be badly translated from Dutch).

**Comment by vshcherb** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/6227875d1191613de39ae51674c77e7846eb307a
@xmd5a2 please add the test.
