### ISSUE TITLE
Use maxspeed:advised like maxspeed:advisory in routing.xml

### ISSUE THREAD

**Issue by Yorkshire-Jack** [osmandapp/Osmand#2545]
When looking for a fastest car route, Osmand uses estimated speeds for each way.  In issue #1664 the tag `maxspeed:advisory` was added to [routing.xml](https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#L221) as a source of speed information. `maxspeed:advised` is also used to convey the same information, so could be treated the same way.
`maxspeed:advisory` is used [2850](http://taginfo.openstreetmap.org/keys/maxspeed%3Aadvisory#overview) times and is documented on the [wiki](http://wiki.openstreetmap.org/wiki/Key:maxspeed:advisory)
`maxspeed:advised` is used [6141](http://taginfo.openstreetmap.org/keys/maxspeed%3Aadvised#overview) times but is not documented on the wiki.

An example of where this results in wrong routing is in Edinburgh. From the [intersection of north castle street and queen street](http://www.openstreetmap.org/node/606316) to [the east end of Cumberland street](http://www.openstreetmap.org/node/641386). The route goes down Howe street and St Vincent Street, and all the way along Cumberland street, across Dundas Street.  It should go down Queen Street Gardens East and Dundas Street.  The west section of Cumberland Street should be avoided as it is narrow and cobbled.  It is tagged `maxspeed:advised=20 mph`.

Also, it seems odd that routing.xml has a speed of [45 for tertiary roads](https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#L230) but [50 for other roads through residential areas](https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#L252).  I haven't opened an issue for that though as it's quite possible that I misunderstood how the speed allocation works.

**Comment by vshcherb** [comment]
We can combine tags maxspeed:advisory and maxspeed:advised.

P.S. I reduced speed for abutters to 30, so it seems more logical.

**Comment by xmd5a2** [comment]
Fixed by converting maxspeed:advised to maxspeed:advisory
