### ISSUE TITLE
"Avoid unpaved roads" for bike doesn't work as it supposed to!

### ISSUE THREAD

**Issue by shamsartem** [osmandapp/Osmand#2546]
I'm using: 
1) Latest android version of Osmand 
2) Offline maps offered within the OsmAnd app for download
3) OsmAnd's in-app offline routing with bike routing profile and avoid unpaved roads

Route is:
From here http://www.openstreetmap.org/node/341282880#map=19/53.88584/27.56695
To here http://www.openstreetmap.org/node/341282880#map=19/53.89020/28.03408

It doesn't avoid unpaved roads. Routes me through a forest begining from here http://www.openstreetmap.org/node/341282880#map=19/53.87420/27.69761 

I looked this roads in openstreetmap.org and the pavement is undefined, but Osmand thinks that roads are paved. 

Maybe you can implement "Avoid "unknown type of pavement" roads" or something like that, because I am sure EVERYBODY who uses road bike will agree that roads for cars will be much better in the case when there are no other options.

Thank you!

**Comment by vshcherb** [comment]
This is http://www.openstreetmap.org/way/36792368 the road

**Comment by vshcherb** [comment]
It is hard to say if it works as expected or not, but it works as designed. It avoids road with knonw bad surface
```
<select value="0.4" t="tracktype" v="grade2"/>
				<select value="0.1" t="tracktype" v="grade3"/>
				<select value="0.1" t="tracktype" v="grade4"/>
				<select value="0.1" t="tracktype" v="grade5"/>
```
So usually to specify grade for track, tracktype tag is used, grade1 considered to be very good for bicycle. You can change routing.xml https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml and use your own.

BTW the path from example is no longer reproducible but it is very easy to find similar examples, downgrading highway/track leads to very long detours.

**Comment by shamsartem** [comment]
Thank you very much for your response, really appreciate your work!
