### ISSUE TITLE
[Feature / help request] Depends render XML coding / syntax for tag mtb:scale

### ISSUE THREAD

**Issue by hdmtb** [osmandapp/Osmand#2547]
I'm hoping someone can reply with the basic proper code syntax / structure so I can figure out how to create a custom "depends" render style for the tag mtb:scale.  I have spent many hours researching web posts, looking at render code examples, and testing my coding attempts but still can't get it to work properly.  Also posted this request on OsmAnd Google Group with no responses.

I want to create a "depends" render file that will render (off-line) paths and tracks tagged with mtb:scale in different colors.  I'd also like to be able to specify custom path effect and stroke width for different zoom levels.

I know this goes at the top: renderingStyle name="mtb-scale" depends="default" defaultColor="#f1eae4" version="1"

When saved in the OsmAnd rendering folder and selected from the Map Style menu, the functionality I want is:

If the tag "mtb:scale" for a path or track = "0", render that path / track in color X.

If the same tag = "1", render feature in color Y.

And so on, rendering different path / track colors for mtb:scale values 0-6 (I know how to code for the color values).

Even more helpful would be a simple code example that also varies the pathEffect and strokeWidth for different zoom levels.  I know how and where to save the render file on my phone.

Thank you in advance to someone for helping me figure this out!  Once I get it working properly I may propose it for inclusion as a standard vector renderer option.

**Comment by xmd5a2** [comment]
If you want to change color depending on mtb:scale tag:
```xml
	<renderingAttribute name="footwayColor">
		<case additional="mtb:scale=0" attrColorValue="#ff0000"/>
		<case attrColorValue="#0033ff">
			<apply_if nightMode="true" attrColorValue="#c79f00"/>
		</case>
	</renderingAttribute>
```
If you want to change strokeWidth (this attribute is used for tracks,footways and paths):
```xml
	<renderingAttribute name="trackStrokeWidth">
		<case minzoom="14" maxzoom="16" attrIntValue="4"/>
		<case minzoom="17" attrIntValue="16"/>
	</renderingAttribute>
```
pathEffect of tracks,footways,paths can't be changed this way but if you really need it I can try to modify default.render.xml and create new renderingAttribute.

**Comment by hdmtb** [comment]
When I tested the code below it rendered all paths in blue (#0033ff) and did not render the paths with tag mtb:scale=0 as red (#ff0000).  Did I mess something up, or possibly the .obf file I extracted using Planet.osm does not contain the mtb:scale tag?  That's all I can think of as a reason for it not rendering.  Thanks for your help.  (The code below was formatted correctly - just don't know how to do that in these comments).

`<renderingStyle name="mtb-scale" depends="default" defaultColor="#f1eae4" version="1">
<renderingAttribute name="pathColor">
 <case additional="mtb:scale=0" attrColorValue="#ff0000"/>
<case attrColorValue="#0033ff">
 <apply_if nightMode="true" attrColorValue="#c79f00"/>
 </case>
 </renderingAttribute>
 </renderingStyle>`

**Comment by xmd5a2** [comment]
You can format code this way https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot%20from%202016-05-16%2012%3A15%3A01.png
Please ensure that your data really contains mtb:scale=0 tags. I added this tag to test osm file and it renders as expected with your code (see red line. UniRS is used as base style)
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot%20from%202016-05-16%2012%3A14%3A20.png

**Comment by hdmtb** [comment]
Still not working for me.  There are definitely mtb:scale=0, 1, 2, and 3 tags on the paths and tracks I'm testing this on.  The Map Creator version I downloaded one week ago.  Is there any way to view a .obf file from Map Creator on my desktop to query the attributes of these path features to make sure they contain the tag?  Here is the trail network I'm testing this on: [https://www.openstreetmap.org/#map=16/42.5973/-70.8175&layers=C](url).  Thanks again for helping me out on this.

**Comment by xmd5a2** [comment]
You can convert obf to osm like this:
```
inspector.sh -vmap -vmapobjects -zoom=16 -osm $1 > $1.osm
```
