### ISSUE TITLE
Cannot select United States as Driving Region

### ISSUE THREAD

**Issue by osMatt** [osmandapp/Osmand#2548]
In Settings > General Settings > Driving Regions (see screenshot below) I cannot select "United States" for some reason. All other regions can be selected without any problem. 

![screenshot_driving_region](https://cloud.githubusercontent.com/assets/19366767/15271121/3132b4f8-19f7-11e6-92ae-fdc511ccd9c6.png)

Most of the time, nothing happens when I tap on "United States". After multiple taps, "Europe & Asia" or "Canada" get selected, most likely because I did move my finger a bit up or down. 
After some repeats an exception was generated which seems to be linked to this issue, see [exception.txt](https://github.com/osmandapp/Osmand/files/264750/exception.txt). While the no-action is repeatable, I do not always get this exception on my Android 4.2.1 Samsung phone.

**Comment by vshcherb** [comment]
I tried on LG G2 and I can't reproduce it. May be there are other phones it also reproducible, we need to check more devices.

**Comment by osMatt** [comment]
As a workaround I use the combination of selecting "Canada" as Driving Region (to get right hand side driving and American signs) and change the units to miles and feet. This should then result in the same effect as selecting "United States" as Driving Region.

**Comment by sonora** [comment]
Cannot reproduce at all on Samsung S4, S4 Mini, S5 Mini, Galaxy tab 3.7, htc Note, and several htc Desire models, in fact I use and change this setting a lot and have never seen an issue like this.
- osMatt, I suppose this happens also with the app in portrait mode?

Victor, there seem issues with filling list in the onClick event, see http://stackoverflow.com/questions/23050150/create-listpreferences-in-android. But I have not checked if our code here is even remotely similar to hat is described on stackoverflow. Strange also that none of us can reproduce this ...

**Comment by osMatt** [comment]
Thanks for looking into this. I tried in landscape mode and strangely it works there. So from my side this is nothing urgent to fix as apparently it is not too common and even I get around it by turning the phone.

**Comment by sonora** [comment]
I have not heard of anybody else reporting this issue anywhere. I guess we can assume this may be device or firmware-specific, or even resolved?

**Comment by vshcherb** [comment]
I guess it is fixed actually
