### ISSUE TITLE
[BUG] Force close when moving the map (RAM issue ?)

### ISSUE THREAD

**Issue by homersimpsons** [osmandapp/Osmand#2549]
> What version of OsmAnd are you using, on what device and Android/iOS version?

App Version : OsmAnd~
Apk Version : 2.3.3 235

> Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

All France maps, include Hillshade, Online tile enable. I think this can happen with every map.

> If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

France Ile de France maps (full), 1 may 2016

> Step to reproduce

1. Choose zoom level: 100 m(eters)
2. Drag slowly the map to generate new tiles
3. Observe force close: [exception.log](https://github.com/osmandapp/Osmand/files/264919/exception.txt)

> My opinion

In my mind it's a RAM issue, because while tiles are generated I saw my RAM to decrese.

> Android information

Device : hammerhead
Brand : google
Model : Nexus 5
Product : hammerhead
Build : MOB30H
Version : 6.0.1

**Comment by vshcherb** [comment]
Yes, there is an out of memory error, it is Android Bitmap Memory and it is smaller than RAM on the device.

**Comment by homersimpsons** [comment]
How can you solve this issue?

**Comment by vshcherb** [comment]
I can't you better not use so many map layers at the same time on your device or tweak it to allow more RAM allocations.

**Comment by homersimpsons** [comment]
It's impossible to get the max size of ram and get size of loaded bitmap then, if the next one is higher than max, delete the oldest one.

**Comment by vshcherb** [comment]
No it is impossible, all bitmaps should be stored in the memory, it requires a huge refactoring which I'm not sure is doable. Though you might try Qt engine which is a parallel development thread and there memory issue could be gone. http://download.osmand.net/latest-night-build/OsmAnd-qt-arm-nightly.apk
Please don't forget to enable it in Development Settings.
