### ISSUE TITLE
Local cycling network nodes  when searching nearest POIs - whats the point of it?

### ISSUE THREAD

**Issue by RicoZ-OSM** [osmandapp/Osmand#2550]
When searching "nearest POIs" I get plenty of those points - most of the time totally unremarkable points in the middle of a track without any obvious significance. Sometimes They are lit, sometimes not..

Is there a reason to display them as POIs? Should the cycling/hiking route be displayed instead of all the particular points?

**Comment by RicoZ-OSM** [comment]
it can get really bad crap : trying to search "Velden" with a map of Bavaria I am getting literally 1000s of nodes belonging to some hiking routes. Finding the place in that is impossible unless the map center is right next to it.

Are all those crap points indexed in some POI database? No wonder the map size is so huge...

**Comment by xmd5a2** [comment]
These POIs was added by request. Users wanted to search routes. Better to keep them until more convenient route search and highlighting implemented.

**Comment by RicoZ-OSM** [comment]
Does it need every single node of a way as POI? Isn't it possible to search for ways? I do easily search for waterways, should work here?

**Comment by xmd5a2** [comment]
Waterways and routes can only be found as POIs. Waterways have longer way segments but route segments usually are shorter. That leads to tons of route POIs but very few river POIs.

**Comment by RicoZ-OSM** [comment]
what I was trying to say - the returned route "POI"s are just single nodes,  not ways or way segments like for waterways.

Returning way segments instead of every single node for routes would already be an improvement.

**Comment by xmd5a2** [comment]
It is planned in future

**Comment by vshcherb** [comment]
We planned, the filter of this POI type will be more aggressive in the release (so much less duplicates - same names), though we decided to keep search results in place
