### ISSUE TITLE
accidental click protection screen mode?

### ISSUE THREAD

**Issue by RicoZ-OSM** [osmandapp/Osmand#2552]
quite often I don't have the time to mount the device in the car and give it into the hands of someone on the passenger seat to hold it. From experience, the passengers quite easily click something accidentally.

Would it be possible to have a mode which would display everything but would be somehow click-protected? In particular the edges of the touchscreen are highly prone to accidental touches.

**Comment by vshcherb** [comment]
That's possibly duplicate #1855
