### ISSUE TITLE
Vector map displacement when using underlay

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#2553]
Sometimes (often) when using underlay and zooming vector map is displaced.
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot_2016-05-07-15-15-56.png
Track with mapnik background:
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot%20from%202016-05-16%2010%3A10%3A57.png

**Comment by vshcherb** [comment]
Не думаю что мы пофиксим, но интересно что все-таки, какой слой, misplaced (можно проверить через контекстное меню)

**Comment by xmd5a2** [comment]
Смещается векторная карта (первый скриншот)
