### ISSUE TITLE
Italian ref over 9 letters/numbers

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/Osmand#2554]
In Italy some ref is not showing correct.
if the ref have 10 or more letters/numbers, Osmand is not showing the box around the ref symbol.

incorrect with 10:
![image](http://fs5.directupload.net/images/user/160516/rdaxo222.png)
correct with 9:
![image](http://fs5.directupload.net/images/user/160516/m3qzwmxo.png)

incorrect and correct in one:
![long short](http://fs5.directupload.net/images/user/160516/d92jae9l.png)
![long short 2](http://fs5.directupload.net/images/user/160516/illuyvvt.png)

the "[SR75bis/racc](https://it.wikipedia.org/wiki/Strada_statale_75_bis_del_Trasimeno#Strada_statale_75_bis.2Fracc_del_Trasimeno)" ist the longest ref I found in Italy.

**Comment by xmd5a2** [comment]
This behaviour is a fallback when ref length is more then provided by rendering style. Always there is lengthy ref we can't support. All resources are stored in png. We tried to minimize their size in mobile application. These cases are very rare and at this moment I see no point of fixing them by adding more graphics to apk. Fix can come after possible moving to compressed svg.
