### ISSUE TITLE
History Entries and Favorites need to contain link to the original (e.g. POI) object, not just its LatLon data

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2558]
On the Search screen's History tab, tap on any previously selected POI entry, like a restaurant or a Wikipedia entry.

OsmAnd will only produce a marker to the location with an "empty" context menu, which is mostly not what the user needs. Expectation is to produce the very POI entry itself and context menu, with its description and the available details like wikipedia article, restaurant opening times, etc.

In analogy, if the history entry points to a favorite, let's produce the favorite and its description (user may e.g. want to edit it), not just a pointer to its location.

**Comment by vshcherb** [comment]
I would say nice to have though it is doable and we might implement but in favor of different feature.

**Comment by sonora** [comment]
From a usability perspective, I still find this one of our major flaws, (also affecting usability of the new search). If a user had once found e.g. a hotel, and reselects the entry in the search history, he expects to somehow be able to see the original object to e.g check opening times, contact data etc. (We are more than just a navigation tool now we have evolved into a geo database).

Likewise actually for favorites, we have to equally re-think the concept here, too: For now we only capture the LatLon data in favorites, but users find it hard to display the original object they marked as favorite (if in fact it was more than just markinv a position on the map).

Conceptually, think web browser favorites here: While we certainly need not save the whole web site inside a favorite entry, we need to somehow include the **link** to it.

**Comment by crimean** [comment]
@sonora already done for POIs and Favs

**Comment by sonora** [comment]
Alexey, wow, I just see the commit, we had just overlapped in our thinking ... :) Thanks!

**Comment by sonora** [comment]
In history entries it works (for poi and favs), favorites do not have the capability yet, it seems.

**Comment by sonora** [comment]
(1) From my testing, it apparently does not work if the history entry refers to a Transport stop?

(2) Also, the issue still exists in Favorites (if a favorites was created from a map object like an amenity, i.e. other than just a LatLon object), and of course in the History section of the search if the history entry relates to such a favorite.

Regarding (2), I understand we do not want to include much more detail in our Favorites.xml file. If possible, we could either just include a custom xml tag `(<osmand-map-object>` or similar) with a link to the original map object, or even less intrusive we could solely make an expansion to our context menu for favorites by adding a line in the context details section saying "Search for the original map object", which would start the search with the Fav name preselected, or similar?

**Comment by sonora** [comment]
Related, but very different:

(3) When looking up this object http://www.openstreetmap.org/node/638929296, its entry gets added to the History as LatLon, not object. Maybe a parsing issue with some of the details attached where we catch the exception or something, because adding POIs to History as objects works well for other similar objects (this one is a restaurant).

**Comment by sonora** [comment]
(4) Maybe check when we refresh the History tab. Looks t me like you have to close then re-open the search screen before the ListAdapter in History is updated, which can be confusing if no update happens when just changing tabs on the screen.

**Comment by vshcherb** [comment]
(1) Transport stops are not searchable, so this is not an issue
(2) is a separate issue might worth to enter (same to open transport stop object, cross object links poi -> transport_object, favorite -> poi)
(3) we need to check
(4) known issue, I would consider it is a feature that you need to start search again.

**Comment by sonora** [comment]
Ad (1) Transport stops now carry the line and "other stops on the line" information, which is a great feature!! After selecting one on the map, the stop gets added to the history. But when re-selecting it from the history, all he add-on info is lost, this is why this is significant.

Ad (2) Adding the "link2object" capability also to our Favorites is one of the 2 original issues I mention above in the issue title.

If it helps, we can certainly break (1) and (2) out to different issues, but we have already collected a lot of background, details, and implementation ideas in this issue here.

**Comment by vshcherb** [comment]
(1) Agree, I've thought you selected POI and expected transport information to show up.

**Comment by vshcherb** [comment]
(2) should be a different issue not related to 2.4, sorry misused this issue. May be I should have opened a separate.

**Comment by vshcherb** [comment]
I think only (3) is relevant to this issue, (1) could not reproduce because transport stops don't get into history when you select them on the map.

**Comment by vshcherb** [comment]
(1)

**Comment by sonora** [comment]
(1) is in fact very weird. I have Transport stops in my Search history showing the behavior I reported above, but cannot seem to produce new transport stop history entries like that any more. I guess the behavior has changed in the last few days, but should be fine as it is now. 

I also notice that the search history entries on the OLD search screen do not have the object link fixes the QuickSearch history screen now has, but I guess we will consolidate the 2 screens anyway before releasing?

**Comment by vshcherb** [comment]
True and weird. Anyway it should be a separate issue and it should work for POI type = transport. So it should have seamless experience between POI and  Transport.

**Comment by sonora** [comment]
I guess a history should **always** only contain **a link** to the original object,, never a "copy" of it .... but looking at how we seem to struggle to implement this principle separately for all the different object types and use cases, this seems much easier said than done ...  :)    A rather flat statement, apologies, but I have not looked at the code of how we produce "history" entries ...
