### ISSUE TITLE
POI categories become mixed up

### ISSUE THREAD

**Issue by pbb72** [osmandapp/Osmand#2559]
After selecting multiple POI categories, they become combined and mixed up. It's not possible to get the standard categories back without killing OsmAnd.

![screenshot_2016-05-17-10-34-41](https://cloud.githubusercontent.com/assets/1436366/15316254/73926ea2-1c1c-11e6-8684-068206c08bda.png)

**Comment by xmd5a2** [comment]
Please try latest nightly. This bug was already fixed.

**Comment by pbb72** [comment]
Yes you're correct, I should've first updated.
