### ISSUE TITLE
Double rendering map at zoom level 11

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#2565]
At zoom level `11 2` osmand is double rendering the global map together with the local map.
For example:

![](https://cloud.githubusercontent.com/assets/982338/15357663/82d66cf0-1cd6-11e6-8542-20e5aa9b3a34.png)

As can be seen at the arrow, the global map is rendering the road as a primary way, on top of the local map (it was fixed to secondary).

Shouldn't only one map be rendered at this zoom level? Probably the global map only.

Version is 2.4.0#12810D

**Comment by vshcherb** [comment]
I think we should update basemap only. On 11th zoom we get an improvement from detailed maps.

**Comment by naoliv** [comment]
But with basemap updated, won't it keep rendering both maps at the same time?
