### ISSUE TITLE
Feature request: Improve bicycle routing by supporting cycleway:left and cycleway:right

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#2566]
Similar to the [_cycleway_ key](https://wiki.openstreetmap.org/wiki/Key:cycleway) there are _cycleway:left_ ([used 24k times](https://taginfo.openstreetmap.org/keys/cycleway%3Aleft)) and _cycleway:right_ ([used 48k times](https://taginfo.openstreetmap.org/keys/cycleway%3Aright)). They are present if the track or lane is only on one side of the street. Typical values are _lane_,  _track_, _opposite_ and _opposite\_lane_ similar to the regular, already supported cycleway key.

Supporting these two additional keys will improve bicycle routing in well-mapped areas.

Also see issue #2567 for similar tags regarding foot routing.

**Comment by vshcherb** [comment]
They are used in combination with opposite_lane and lane which is already used.

**Comment by scaidermern** [comment]
No, they are used *instead of* cycleway=lane/track/opposite_lane. Look at the various [examples](https://wiki.openstreetmap.org/wiki/Bicycle).

**Comment by scaidermern** [comment]
Please reopen. The [Key:cycleway](https://wiki.openstreetmap.org/wiki/Key:cycleway) wiki page explicitly states that _cycleway:left=opposite_lane_ and _cycleway:right=opposite_lane_ should be used *instead of* *cycleway=opposite_lane*:

> Use cycleway=opposite_lane for a contraflow cycle lane, that is, a cycle lane travelling in the opposite direction to other traffic on a oneway=yes road. Consider using the cycleway:left=opposite_lane or cycleway:right=opposite_lane tags instead, as this describes on which side the contraflow lane is.

The same applies to *cycleway=track* and *cycleway=opposite_track*:

> Consider using the cycleway:left=opposite_track or cycleway:right=opposite_track tags instead, as this describes on which side the contraflow track is.

Bicycle support is incomplete without handling of these tags. It is even broken for roads tagged with *bicycle=no* and *cycleway:right=track*.

**Comment by vshcherb** [comment]
Bicycle support is incomplete without handling of these tags. It is even broken for roads tagged with bicycle=no and cycleway:right=track.

Are you share this mapping is correct? It is  2 contradictive tags, as I see bicycle is forbidden in any direction.

**Comment by scaidermern** [comment]
>> Bicycle support is incomplete without handling of these tags. It is even broken for roads tagged with bicycle=no and cycleway:right=track.

> Are you share this mapping is correct? It is 2 contradictive tags, as I see bicycle is forbidden in any direction.

I *think* it is correct because *bicycle=no* applies to the street whereas *cycleway:right=track* applies to a separate cycleway next to the street. But this was just an (admittedly rare) example where the incomplete bicycle support would fail. Adding support for *cycleway:left* and *cycleway:right* will improve bicycle routing in many not so rare situations.

**Comment by vshcherb** [comment]
Turns out we already support these tags long time ago https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml#L2713

**Comment by scaidermern** [comment]
Are they also considered during routing?

**Comment by vshcherb** [comment]
Yes they are used for routing & for rendering
