### ISSUE TITLE
Offer rendering of toll roads (under Configure map / Details)

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2568]
I received a request to add an option to accentuate toll roads (tag toll?yes) in our vector maps, similarly to how we already offer the option to show lit up roads under Configure map / Details / Street lighting.

**Comment by vshcherb** [comment]
Suggestion, possibly we could have it rendered in OSM Mapper and there we could have exclusive choice option what to render, otherwise we run out of options how to highlight features.

**Comment by xmd5a2** [comment]
We already render toll roads. Turn on "access" rendering option.

**Comment by sonora** [comment]
Thanks, Leonid, I missed tha1 one! I guess I will change the menu text label to "Show access restrictions and toll", that will likely make this transparent to more users.
