### ISSUE TITLE
Fast route calculation failed (Attempt to invoke interface method 'int java.util.List.size()' on a null object reference)

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#2573]
Sometimes when trying to use a GPX route for navigation I get a notification saying
*Fast route calculation failed (Attempt to invoke interface method 'int java.util.List.size()' on a null object reference), fallback to slow calculation.*.

![photo_2016-05-20_17-08-32](https://cloud.githubusercontent.com/assets/1040784/15432212/8c1a517c-1ead-11e6-8973-c410cea0a2ec.jpg)

There is no exception.log and I also couldn't found a corresponding entry in catlog (happens both with latest OsmAnd stable and nightly version).

Interestingly fast route calculation always seems to fail when using a GPX route for navigation. Usually there is just some cryptic and seemingly random number reported as error instead of the mentioned exception. I'm not sure if this message is an actual error but it definitely irritates the user. If this is intended behavior then I suggest to change the message to something less irritating, like "Fast route calculation not appropriate, fallback to slow calculation.".

**Comment by vshcherb** [comment]
Yes exception.log is empty though if it is possible to get the log from Android (aLogCat) that would be very helpful

**Comment by scaidermern** [comment]
I'll try to reproduce it and attach the log.

**Comment by scaidermern** [comment]
I couldn't reproduce the exception from the original screenshot so far. However here are two logs where _Fast route calculation failed (-some number)_ has been reported: 
- [2016-05-24-20-43-52.txt](https://github.com/osmandapp/Osmand/files/280218/2016-05-24-20-43-52.txt)
- [2016-05-24-20-48-50.txt](https://github.com/osmandapp/Osmand/files/280226/2016-05-24-20-48-50.txt)

Another log where a _Loading data exception_ occured: [2016-05-24-21-02-14.txt](https://github.com/osmandapp/Osmand/files/280282/2016-05-24-21-02-14.txt)
![photo_2016-05-24_21-08-42](https://cloud.githubusercontent.com/assets/1040784/15516596/cbf39fee-21f3-11e6-9e4c-acad1703a0a2.jpg)
There has been another longer exception right before this one but I didn't manage to capture the screen fast enough. This exception seemed to happen roughly the same time while switching from day to night mode. But could just be a coincidence. Killing and restarting the app resolved the issue.

**Comment by vshcherb** [comment]
Because the bug is hard (impossible) to reproduce and there is not enough information yet, it will be closed without any action. Once additional information comes or somehow the root cause will be found, it will be reopen.
