### ISSUE TITLE
Calculated route takes unnecessary detour through complete roundabout

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#2574]
I couldn't find the right words for the title but the screenshot says it all:

![photo_2016-05-20_17-37-10](https://cloud.githubusercontent.com/assets/1040784/15433184/80fc3964-1eb1-11e6-92e1-3250d4d29d29.jpg)

This can be reproduced (using the latest nightly 2.4.0#12934D, probably also using the stable version):
* Download map region Germany Thuringia
* Download [this track](https://github.com/osmandapp/Osmand/files/274924/planned2_track.gpx.txt), fix the file ending and put it in OsmAnd's track directory
* Manually select [this](http://www.openstreetmap.org/?mlat=50.69420&mlon=11.58829#map=19/50.69420/11.58829&layers=N) start location which is located in Pößneck, Thuringia, Germany. If you have problems with Umlauts then just use online search for "Kletterwald Koala" which is just a few meters to the north.
* Select to navigate along the downloaded GPX track

Now OsmAnd should calculate the route shown in the screenshots.

Note that this does only occur when trying to use the GPX track for navigation. Regular navigation doesn't produce this error:

![photo_2016-05-20_17-37-12](https://cloud.githubusercontent.com/assets/1040784/15433185/80fe8eee-1eb1-11e6-9469-d634761d9e6c.jpg)

Also note that the mentioned GPX track does *not* pass this roundabout. OsmAnd produces this strange route while trying to navigate *to* the GPX track.

**Comment by teriblus** [comment]
I've got the same issue with and without gpx navigation.
I also tested with and without the native library and I still get the issue.

To reproduce on the version from the play store (2.3.5 2016-04-28):
1. navigate from "rue de l'aérodrome (le roudour), lannion" (france)
2. navigate to "boulevard d'armor (le roudour), lannion"
3. start navigation

You should get this:
![screenshot_2016-05-26-08-44-04](https://cloud.githubusercontent.com/assets/17048774/15565951/759c40b6-231e-11e6-9fca-0af06a43647f.png)

I noted that when going through this roundabout from a different street or going to a different street, I do not get the issue. I also checked the roundabout definition in OSM and it seems ok (I'm not familiar with OSM) (https://www.openstreetmap.org/#map=19/48.74635/-3.46617)

**Comment by teriblus** [comment]
In "shortest route" mode, the problem does not occur on this roundabout.

**Comment by noci2012** [comment]
I have observed this issue in real life during a trip in Sweden. Complete roundabout is one issue.
Another is leaving the autoway rounding a roundabout next to the road and the continue on the autoway. (80km /h road).

Another i met is leaving the autoway entering a small village and leave the village on the other side to enter the same autoway again there. (Note the detour was considerable longer then the router on the autoway, and 40Km/h in vilages). 

Fast route is enabled, as well as avoid softroads toll-roads and ferries.

**Comment by scaidermern** [comment]
> Another is leaving the autoway rounding a roundabout next to the road and the continue on the autoway. (80km /h road).

> Another i met is leaving the autoway entering a small village and leave the village on the other side to enter the same autoway again there. (Note the detour was considerable longer then the router on the autoway, and 40Km/h in vilages).

These are separate issues and belong into a separate bug report. If possible include examples for these routes.

**Comment by vshcherb** [comment]
Fixed
