### ISSUE TITLE
Wrong location interpretation from hiking app

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#2576]
When using "Wandeltochten" app, as you choose a walk, tap Properties button and choose Navigation, OsmAnd cannot open the location. Google maps do it.
![screenshot_2016-05-21-16-05-48](https://cloud.githubusercontent.com/assets/12711814/15448601/5ef4a39c-1f6f-11e6-9237-279f0c8bcbfc.jpg)
![screenshot_2016-05-21-16-05-55](https://cloud.githubusercontent.com/assets/12711814/15448602/5f1b323c-1f6f-11e6-9d06-629dc13a50ce.jpg)

**Comment by homersimpsons** [comment]
I think that is normal because Osmand doesn't get an adress search engine compare to Google Maps

**Comment by vshcherb** [comment]
Known issue, not supported
