### ISSUE TITLE
When a GPX track is part of the nav. route, the intermediate points are not added

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#2577]
If you choose to follow a GPX route during navigation and then tap a point on map and select Add as last intermediate waypoint, OsmAnd says "route is recalculated", but it ignores the intermediate point.

**Comment by vshcherb** [comment]
Known issue, they could not be added, GPX is a prepared route, so intermediate points are not needed. At least I don't see proper use case for this.
