### ISSUE TITLE
Remaining turn lane issue?

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2579]
When going straight on http://www.openstreetmap.org/way/30405356, our turn lane widget indicates you can take all 4 lanes, although only the 2 through lanes should light up. The lanes seem correctly mapped as turn:lanes=left|left|through|through, and our widget also correctly paints them like that. Why are the turn lanes suggested as well, OsmAnd bug or mapping issue?

**Comment by osMatt** [comment]
I have noticed this issue to occur when there is a left turn lane mapped before the intersection, but only to a node where no left turn is possible (in this case until http://www.openstreetmap.org/node/15159499). There are no left turn lanes mapped on the intersection (http://www.openstreetmap.org/way/32493519) until the actual left turn. Adding `lanes=4` and `turn:lanes=left|left|through|through` to that way should remedy the problem. 
While I think this is less than ideal tagging (the short way on the intersection represents 4 lanes of which 2 are left turn lanes, so I think this should be reflected in the tagging), there are currently a lot of turn lanes added in major US cities (https://github.com/mapbox/mapping/issues/180) and these seem to have the same issue. Just taking a brief look at recent turn lane mapping reveals that this will happen at many more intersections (e.g. http://www.openstreetmap.org/way/28357394 or http://www.openstreetmap.org/way/419790104). Thus it might be preferable to capture this in Osmand, e.g. by checking whether there is a turn within the next 30(?) meters.

**Comment by vshcherb** [comment]
We should create a test for this if it is still reproducible

**Comment by xmd5a2** [comment]
Test added

**Comment by sonora** [comment]
osMatt, I think you are perfectly correct, I can confirm your observation at all examples I have collected. I am beginning to wonder if there is also a connection to another issue I am trying t debug where we sometimes detect the beginning of turn lanes as separate turns and fail to combine them with the actual subsequent turns (if any).

**Comment by sonora** [comment]
Well, I have now been looking at some locations which do _not_ suffer from this issue, like e.g. the next intersection to the west http://www.openstreetmap.org/way/30405356. The mapping is kind of similar, the turn lanes are also not connected through the intersection, but still, I see no issue there with OsmAnd's lane assignment...

**Comment by osMatt** [comment]
The difference between the two intersections is that http://www.openstreetmap.org/way/32493519 does not have a `turn:lanes` tag, while http://www.openstreetmap.org/way/4319353 has a `turn:lanes` tag. The problem occurs when there is a gap in tagged turn lanes before the actual turn.

**Comment by sonora** [comment]
Ah, sorry, yes, I had looked at (and referenced above) the wrong way, I in deed mean http://www.openstreetmap.org/way/4319353 and there are turn:lanes connecting to the actual turn! Thx!

**Comment by vshcherb** [comment]
Fixed
