### ISSUE TITLE
Turn:lanes when "left;through" on a lane

### ISSUE THREAD

**Issue by CJTmmr** [osmandapp/Osmand#2581]
Another turn:lanes issue?

On an intersection with divided ways;
When left and through are combined on one lane, and you are turning left, the through arrow is highlighted.

Example 1 : driving [this route:](http://www.openstreetmap.org/directions?engine=osrm_car&route=52.03015%2C4.71298%3B52.02835%2C4.71589#map=17/52.02896/4.71482)
OsmAnd shows:
![2016-05-17 14 32 15](https://cloud.githubusercontent.com/assets/15076257/15455521/aa0f92aa-2056-11e6-95b8-0c12ddfaa235.png)
Only on the last meters (already on the intersection) the left-arrow is turning green.:
![2016-05-17 14 32 44 cut](https://cloud.githubusercontent.com/assets/15076257/15455533/1943272c-2057-11e6-91c7-6b9b66d84ad6.png)

Example 2: On another location, driving [this route:] (http://www.openstreetmap.org/directions?engine=osrm_car&route=52.12196%2C4.67418%3B52.12375%2C4.67949#map=17/52.12163/4.67721)

![2016-05-09 13 34 48](https://cloud.githubusercontent.com/assets/15076257/15455537/5a7b69d4-2057-11e6-8003-813ec9b9dc3d.png)

**Maybe another issue; but related??**
At these intersections; the new(coming) streetname (with left-arrow) is not shown in the topbar; 
The current streetname is displayed is stead. Only on the last few meters the new name is shown.
The voice-announcement is okay, like "in *so many meter* turn left to *new streetname*"

Last example 3 showing both issues:
A [video](https://www.dropbox.com/s/hjrw7sodm8n4ufl/Turn%20left%20Gouda.mp4?dl=0)  of [this turn to left](http://www.openstreetmap.org/directions?engine=osrm_car&route=52.01613%2C4.70950%3B52.01535%2C4.71102#map=19/52.01576/4.71006)

**Comment by vshcherb** [comment]
We used to have 10+ issues and it is not that easy to fix them all, anyway we are adding them to our test collection and in case we can't fix them we will report here.

**Comment by xmd5a2** [comment]
Tests added

**Comment by vshcherb** [comment]
Fixed
