### ISSUE TITLE
Routing issue: favoring highway=primary over short highway=residential

### ISSUE THREAD

**Issue by qantourisc** [osmandapp/Osmand#2583]
At the time of writing (I fixed a few turn restriction on that intersection while I was looking at it) so bug might not be reproducible/worked-around as soon as the maps update.
On the route:
[https://www.openstreetmap.org/directions?engine=osrm_car&route=51.21156%2C4.25262%3B51.21126%2C4.25272#map=19/51.21141/4.25259)]

It would rather first send you to the bottom-left and let you make a u-turn there then to send you over the intersection part.

One could argue the piece between the 2 primary roads should be also a primary road (I would agree) but that still means the routing is not optimal regardless. (Will also fix this as soon as I get an OK from other people in the OSM community)

**Comment by vshcherb** [comment]
Yes, we have a penalty when you transition between primary and resedential. As I see the map data has changed and it is not reproducible any more. On the other hand I think it would work now in original case as well
