### ISSUE TITLE
OsmAnd fails to handle shared locations from Google Maps

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#2584]
OsmAnd fails to handle shared locations from Google Maps. (At least here in germany it does not work.) OsmAnd is not offered as option.

(I need to pass the locations to "POI pocket" app and from there to OsmAnd as workaround.)

I think pull request #1061 would fix this issue.

Found in OsmAnd+ 2.3.5.

**Comment by sonora** [comment]
I also get many user requests about this, from Germany and elsewhere. For some users this becomes a real showstopper when it comes to usability of OsmAnd, I guess we need to do something about this some time soon ...

**Comment by homersimpsons** [comment]
I was thinking about regex but [this thread](http://stackoverflow.com/questions/30207293/android-intent-filter-androidhost-with-regexp) and [this one too](http://stackoverflow.com/questions/34788745/how-can-i-write-regular-expression-for-androidhost/34789710) say that it's impossible

**Comment by vshcherb** [comment]
I think to give it a try and merged pull-request, though now we need to test if it works correctly.

**Comment by sonora** [comment]
From my testing so far it really works well!

**Comment by Norbert80** [comment]
Thanks. But I cannot find it implemented in OsmAndF~2.4.0#13267D. Which build do I need to test?

**Comment by sonora** [comment]
Please check the footer of http://osmand.net/ to find the info about our nightly test build.

**Comment by Norbert80** [comment]
I still can't find OsmAnd as option to handle the shared locations with build...

OsmAndF~2.4.0#13396D

**Comment by sonora** [comment]
Just tap on a location URL (e.g. generated by the google maps web page) in an app which provides links in a tappable fashion. All default messaging/SMS apps should do this.

There will be a dialogue asking with what app to view the link, and OsmAnd will be in the list of selections. Please note that on some devices **you may have to SCROLL the list(!),** many people did not realize this....

**Comment by Norbert80** [comment]
@sonora
I just received the update to OsmAnd+ 2.4.2 and it still is not possible to select OsmAnd to receive the links. Here is a example if such an link:

https://goo.gl/maps/Jw1FyhtvhD82

**Comment by sonora** [comment]
Yes, goo.gl seems not supported yet, (but the link resolves to https://www.google.com/maps/place/L335,+88285+Bodnegg,+Deutschland/@47.6915117,8.5876113,8z/data=!4m5!3m4!1s0x479ba7157fc7834f:0x17058fd52e5c5402!8m2!3d47.6915117!4d9.7082167?hl=de and that works).

**Comment by Norbert80** [comment]
@sonora:
It resolves in a browser but I requested to open them in OsmAnd. So this issue is not fixed. I still cannot open OsmAnd by clicking "Share" in Google Maps.

**Comment by raindropsfromsky** [comment]
I agree; short links should work directly in OsmAnd because that's how they are shared between users. No one is going to resolve the link with another application first, copy the expanded link on clipboard and then see it in OsmAnd.

Please re-open the bug.
