### ISSUE TITLE
Streets and housenumbers are in wrong town in Belgium

### ISSUE THREAD

**Issue by kroeckx** [osmandapp/Osmand#2587]
It seems to me that streets are indexed based on the nearest town and not the town they're actually mapped in.  For instance if I look up Wingepark, which is located in Rotselaar, it's showing me the street as "Wingepark (Wezemaal)".  But it's not located in Wezemaal, the centre just happens to be closer.

Note that Wezemaal is a subdivision of a the municipality of Rotselaar.  That is, the municipality of Rotselaar exists of (among others) towns Rotselaar en Wezemaal.  In this case they even have there own zip code, but that's not always the case.  When looking up an address and you're at the city level it's only showing Rotselaar and not Wezemaal, so that's fine.  But when showing Wingepark it shouldn't be showing anything related to Wezemaal.

If you look up "Aarschotsesteenweg" instead, it also shows it as being located in Wezemaal.  But it's actually located in both, and other towns. At some borders the numbering restarts, but it's the same street name.  When I look that up, it's showing me house numbers like 1, 2, 4, 6, 8, 10, ..., 82, 126, 130, 134, 136, 140, 184, 186, 188, 190, ..., 213, 224, 300A, 320, 341, 365.  But even numbers up to 72 and odd numbers up to 77 could be shown as in Rotselaar, clearly not in Wezemaal, while higher numbers could be shown as in Wezemaal.  (It's also missing house numbers that are shown on the map, but I guess that's a different issue.)

I guess this is all in offline mode.

**Comment by hakuchi** [comment]
have you reported this on openstreetmap.org ?

**Comment by kroeckx** [comment]
Why would I report it there?  There is nothing wrong with the data.

**Comment by scaidermern** [comment]
[This street](https://nominatim.openstreetmap.org/details.php?place_id=2597604500)? Nominatim seems to geocode it correctly according to your description. Also, the [administrative border of Wezemaal](https://www.openstreetmap.org/relation/3082310) (admin_level=9) doesn't contain this street but the [administrative border of Rotselaar, admin_level=9](https://www.openstreetmap.org/relation/3098134) and the [administrative border of Rotselaar, admin_level=8](https://www.openstreetmap.org/relation/214462) both do. So the data seems to be correct if I didn't miss something.

**Comment by vshcherb** [comment]
I would still argue that's a mapping issue though it is not a technical but conceptual problem. Suburbs/viilages are often part of the city so we use their names to resolve other problem (street name duplicates) and find by proximity the neighbor city. 

Though the issue is reported correctly because
a) there is no street name duplicate in that city so we should not use that suburb
b) suburb itself is not located in the city and should be eliminated 

The issue won't have a generic fix because that feature is used in many large cities.

**Comment by kroeckx** [comment]
I'm not sure I understand what you're saying.

You could argue that Rotselaar and Wezemaal have their own version of the Aarschotsesteenweg (https://www.openstreetmap.org/way/51517602, https://www.openstreetmap.org/way/231865517, there are more parts).  From the map data it's clearly now not obvious if it should show them as "Aarschotsesteenweg (Rotselaar)" and "Aarschotsesteenweg (Wezemaal)" or just "Aarschotsesteenweg", and either should work in this case.  Just to confuse you, there is an associatedStreet that has some road parts in it, but not nearly all of them.  We should fix that. I assume that if I add all street parts and houses to that relation that it should only show 1 street and if I put them in 2 relations that it might or might not show 2 of them.

But for Wingepark, it's clear in the data that it should only show up in Rotselaar, it has no relation to Wezemaal.

**Comment by vshcherb** [comment]
Just to clarify. OsmAnd doesn't say Wingepark belongs to Wezemaal. OsmAnd says Wingepark belongs to Rotselaar and that's visible via search "Select city Rotselaar, street .. " . Then in street list you will see Wingepark (Wezemaal), which means Wingepark belongs to city Rotselaar but close enough to Wezemaal. 

That's creates confusion and in this case it is unnecessary confusion, though in some cases this proximity feature is useful.

**Comment by rominf** [comment]
@kroeckx I made a MapCreator fix. Here is [generated map](http://download.osmand.net/special-maps/Rotselaar.obf) of Rotselaar. Can you verify? I recommend you to use OsmAnd night build, as the address search has been improved recently.
