### ISSUE TITLE
Mark a waypoint as passed

### ISSUE THREAD

**Issue by rododevr** [osmandapp/Osmand#2588]
Request to make the variable POSITION_TOLERANCE in RoutingHelper.java configurable in navigation settings.
It is now a fixed value of 60, which keeps people from using waypoints.
See: https://groups.google.com/forum/#!topic/osmand/NzlJ5HNTfcM
I suggest to let the user choose from some values in navigation settings, like, for instance:

Consider a waypoint reached if:
- Exactly reached (tolerance 60)
- Passed near (200)
- Passed distant (600)

**Comment by vshcherb** [comment]
It is configurable in Accessibility Settings if I'm not mistaken.

**Comment by rododevr** [comment]
I cannot find it there. The most related setting in Accessibility is "Prevent automatic route recalculation when you are quite far from the right way", but that one seems to serve another purpose. How is the option called?

**Comment by vshcherb** [comment]
Sorry it is in Navigation Settings <string name="arrival_distance">Arrival announcement</string>

**Comment by DaMonk45** [comment]
Victor I disagree, that does not solve the problem.
That just gives a distance. The issue is I am NOT going to that way point. I will not be near that way point. I do not want to go back to that way point.
I am on a motorcycle traveling at 60mph. 
How would you suggest I do this? 
I would like a warning that I missed it and then the warning time out and move on to the next point.

**Comment by vshcherb** [comment]
This is completely different that original issue. 
> Consider a waypoint reached if:
Exactly reached (tolerance 60)
Passed near (200)
Passed distant (600)

In your case it should be "ignore waypoint if you further than 1km"  and to be honest it is not clear how to detect if you passed it or not.

**Comment by rododevr** [comment]
@DaMonk45: What you need is a perfect detection of passing a waypoint without failing to detect it.
Now that is exactly, what I try to achieve with my proposal, because even if you pass a waypoint at a longer distance, it still should be recognized as being reached.

@Victor
Now, a waypoint is considered to be reached if the distance to that point is less than 120 m. Then the system proceeds to the next waypoint.
See your routingHelper.java:

line 46: private static final float POSITION_TOLERANCE = 60;
       
line 474:  if(route.getIntermediatePointsToPass()  > 0
               && route.getDistanceToNextIntermediate(lastFixedLocation) < POSITION_TOLERANCE * 2
               && !isRoutePlanningMode) { .......}

These 120 m. seems to be a too low value in many cases, especially when lastFixedLocation is not accurate enough.
My proposal is to introduce a setting in Navigation Settings that sets the value of POSITION_TOLERANCE in a menu with 3 or 4 choices.
Maybe 60, 120, 180, 240, so the actual "snap" radius becomes 120, 240, 360 or 480 m.
If users cannot approach the waypoint within 500 m, well, then bad luck, that should be a rare exception (road works etc.).
Osmand obviously cannot provide a solution for every exceptional circumstance, but those 120 m. do cause problems frequently.

**Comment by DaMonk45** [comment]
This would work but I would make the last option 1 km. And if I miss it I miss it, I know that will be too far for some and not far enough for others but this at least gives us a chance, and will cut down on the issues we currently have.

**Comment by vshcherb** [comment]
I added multiplier which was missing in that case, so the setting will be properly used, we might need to add more settings option.

**Comment by rododevr** [comment]
I think the destination  and waypoints ask for a different setting. The destination is the point where the user wants to arrive exactly, the waypoints not (always). But if you don't like to extend the menus (which is quite understandable), I suggest to increase the multiplication constant, so it becomes:

if(route.getIntermediatePointsToPass()  > 0 && route.getDistanceToNextIntermediate(lastFixedLocation) < POSITION_TOLERANCE * 4 * settings.ARRIVAL_DISTANCE_FACTOR.get() && !isRoutePlanningMode).

For users, who accept the default values, the waypoint tolerance becomes 240 m., which can be increased to 360 m. if they set the arrival announcement to "early" or can be decreased to 60 m. for arrival announcement "in the last meters". This might be enough to solve the majority of problems.

**Comment by vshcherb** [comment]
I agree , refactored code to have same number as for arrival though for intermediate it has special multiplier of 2.

**Comment by rododevr** [comment]
Ok, thank you for the changes. So now the default "snap distance" is increased from 120 to 180 m. with the new possibility to increase it further by setting the arrival_distance_factor to "early", then it becomes 270 m. 
If this is correct, I shall document it in the google group and wiki. If not, please let me know.
I'm not sure if it solves all the related problems, but this is a real improvement! Thanks.
