### ISSUE TITLE
New Feature: Interrupt Car FM Radio or Car CD for Navigation Voice Prompts

### ISSUE THREAD

**Issue by Gabor-B** [osmandapp/Osmand#2590]
Hello, this seems to be an issue for more people, see links below.
Problem:
- The Phone is connected to the car audio, which is playing for example radio.
- When receiving a phone call, the radio is interrupted, and the call routed through the car audio system
- When OsmAnd outputs TTS guidance messages or beeps, the radio is NOT interrupted, regardless of the voice output option (media/audio, notification, phone call)
- When switching to bluetooth audio source on the car audio, the voice output works. But in that case on cannot hear radio or CDs anymore, of course...

Note: Sygic offers the same settings, and there the routing as a phone call correctly interrupts radio playback and plays the voice message. (and it also offers a preamble of a predefined length of silent output, so that the message is not truncated while the BT connection is being re-established)

When looking into the code, it seems that:
- all BT handling is just a passed setting to android.media.Audiomanager (in activities.SettingGeneralActivities.java the setting updates the CommandPlayer class
- routing.VoiceRouter.java seems to have a hardcoded MediaAudio.STREAM.MUSIC setting

Sadly I am new to OsmAnd and Android and cannot give more specific info.

Found links in OsmAnd GG:
[link1](https://groups.google.com/forum/#!searchin/osmand/bluetooth/osmand/_6jJDZJ57b0/3Bu1co_F7BAJ)
[link2](https://groups.google.com/forum/#!searchin/osmand/bluetooth/osmand/XmYhie1oo5U/2k0OmdSDDgAJ)

**Comment by vshcherb** [comment]
- When OsmAnd outputs TTS guidance messages or beeps, the radio is NOT interrupted, regardless of the voice output option (media/audio, notification, phone call)
There is a setting for this option to interrupt or make the volume lower (in General Settings).

Please describe wanted behavior or split the story in different use cases. It looks like there are different issues in your request.

**Comment by Gabor-B** [comment]
>  There is a setting for this option to interrupt or make the volume lower (in General Settings).

This setting only applies for music played on the phone, not for an external bluetooth device

I presumed the description was clear, here another try:
- Phone connected to car audio via bluetooth (on my device both over HFP and A2DP)
- car audio playback from radio, USB or CD source
- Osmand running on phone, in navigation mode
- Osmand outputting audio commands over bluetooth, but nothing can be heard because the audio playback is not overriden by the incoming bluetooth input. Note that during playback of a radio signal means that the car audio has to switch the input source to bluetooth, play the received audio and then revert to radio mode.

So, wanted behavior:
- If bluetooth output "as phone call" is selected, the current playback on the car audio system shall be overriden by the bluetooth input
- osmand's output shall be played back over the car audio - preferably with a configurable delay (x*100ms of silent playback) to tackle the time needed for the audio system to change the source
- the original playback shall resume on the car audio system

This behavior works well in Sygic when the option "as phone call" is selected, but not in Osmand.
If you can be more specific what info you need, I can try to describe that part better.

**Comment by sonora** [comment]
This has also annoyed many users and me for a very long time, and often leads to bogus "OsmAnd voice output not working" support requests.

Victor, if you google keywords interrupt car  stereo android, you will find multiple hits explaining how this works well for iPhones, but seems a problem in Android for many navigation apps including google maps. Only few seem to have solved it. There are some spurios reports how people managed to fix this using a sequence of tasker actions, but so far I found no good code example how to fix. Have not yet investigated to depth, but it looks like for this to work using the phone call output in audiomanager is not enough. In addition we would have to somehow add a pre sequence to all voice commands simulating that an incoming phone call is signalled to the car stereo and appears accepted by the car stereo, and a post sequence simulating that this "phone call" is hung up again, so the car stereo returns to FM radio or CD mode again automatically.

**Comment by vshcherb** [comment]
We are using this API

return AudioManager.AUDIOFOCUS_REQUEST_GRANTED == mAudioManager.requestAudioFocus(this, streamType, 
              ((OsmandApplication) context.getApplicationContext()).getSettings().INTERRUPT_MUSIC.get()?
              AudioManager.AUDIOFOCUS_GAIN_TRANSIENT: 
              AudioManager.AUDIOFOCUS_GAIN_TRANSIENT_MAY_DUCK );

**Comment by sonora** [comment]
I know. But I can confirm from my tests on quite a number of car stereos that OsmAnd did not manage on any of them to interrupt the car FM radio or CD Player to make a navigation announcement.

It looks like very few Android apps have actually solved this ....   Needless to say, not having this capability is a very decisive limitation for an external navigation product!  :)

**Comment by vshcherb** [comment]
True, thoguh we can't target to all specific devices, especially which one we don't have. So far we targetting very broad set of them and I'm afraid there will be always a possible problem.

**Comment by sonora** [comment]
I think so far it is not device-specific, nor is it specific to what car radio you look at. My impression is we have not solved this **at all**. (And neither have most other Android apps solved this). It seems very hard to fix, I am still looking for a useful documentation f what to do about this...

**Comment by Gabor-B** [comment]
This is not device specific, it occurs on several radios with BT capability.
There are some third party apps offering this capability, but an in-app solution would be preferable
Examples:
- [AudioBT/ AudioBT Plus](https://play.google.com/store/apps/details?id=com.turboled.audiobt&hl=de): This one realizes the interruption functionality for all audio output made by the phone. It also offers the a configurable delay. Sadly not open source, but the dev is on xda-developers, maybe willing to contribute
- [Blue Mono](https://github.com/soynerdito/BlueSound/blob/HEAD/README.md): This one changes the output to mono, which is then obviously also treated as a phone call and interrupts radio playback. This may be a viable workaround

**Comment by sonora** [comment]
@Victor After a lot of reading, I believe the solution is via toggling between
`AudioManager.setMode(AudioManager.MODE_IN_COMMUNICATION);`
and 
`AudioManager.setMode(AudioManager.MODE_NORMAL);`
possibly in combination with
`AudioManager.setBluetoothScoOn(true);`
`AudioManager.startBluetoothSco();`
and
`AudioManager.setBluetoothScoOn(false);`
`AudioManager.stopBluetoothSco();`

Let me test this when I have time, will report here.

**Comment by sonora** [comment]
Ok here is the basic fix: https://github.com/osmandapp/Osmand/commit/21d433bf757225eea74d66ebe2895644e8814d35

You need to tick setting "Interrupt music" on the latest nightly to see if this works for your car stereo.

- Voice quality is limited to 8/16kHz.
- We need to delay our voice prompts a bit to keep the very beginning from being cut off.
- I need to double-check the TestVoiceActivity, after playing prompts from there we do not seem to come across my code to reset the car stereo (mock call remains connected)

**Comment by vrtareg** [comment]
Hi

I have tested this today and it is working but volume is toooooo low.

I have tried all the options and even to turn up to maximum all phone
volumes.

Radio in car is with normal volume but voice prompts are hardly hearable. ..

Regards,
Areg

**Comment by sonora** [comment]
Needs more testing, then investigation. For my current setup, volume is about the same as the car radio sound when "Voice guidance output" is set to "Phone call audio". Only about half when set to "Notification audio" and very low for "Media/music". But this may somehow depend on phone or car volume settings, not sure yet.

**Comment by vshcherb** [comment]
Great findings!
May be that a "feature" to have they low volume for this notifications to less interrupt driver.

**Comment by sonora** [comment]
I hope the volume issue is solved with my latest adjustments, BT SCO stream now seems to always use my car stereo's default PHONE volume (but still need to test).

Main issue I am still fighting with is the initialization glitch when the user tries to start using BT SCO (or actually any other voice stream) sort of "too early after app start".

**Comment by Gabor-B** [comment]
I could check it on my device, the music playback is interrupted correctly, the volume is also good. The sound output delay is appropriate for my device, although it could be a little less. The voice quality is also adequate.
- I did not encountered the "too early start glitch"
- I did encountered a bug where the playback was not ended and the channel was left open without any sound output. Sadly I could not reproduce it.

**Comment by sonora** [comment]
Thank you for the test report!

I think we can consider this new functionality as "implemented".   :)

I will take this through a thorough test procedure. Whoever can, please help, as this needs testing with different car audio systems. I suggest for glitches we see now we start fresh issues to properly document environment, what happens, and how to reproduce.

@vshcherb, @Gabor-B
