### ISSUE TITLE
Progress bar blocks turn arrows

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#2592]
When selecting a GPX route then _sometimes_ the progress bar is drawn above the turn arrows instead of below:
![photo_2016-05-24_20-07-43](https://cloud.githubusercontent.com/assets/1040784/15514934/d2d396c8-21eb-11e6-8c5d-40754c0d8a6b.jpg)

Also it keeps getting drawn all the time until the first way point of the GPX route is reached. It even doesn't go away if routing is aborted:
![photo_2016-05-24_20-12-11](https://cloud.githubusercontent.com/assets/1040784/15514935/d2d4a1f8-21eb-11e6-822c-27a1add2e1ef.jpg)

Can be reproduced both with latest stable version 2.3.5 and with latest nightly 2.4.0#12985D.

**Comment by sonora** [comment]
Deprecated? See #3010.
