### ISSUE TITLE
"Region" should be replaced by "Country"

### ISSUE THREAD

**Issue by Paviluf** [osmandapp/Osmand#2594]
"Region" should be replaced by "Country" to make a search. I have a standalone GPS and this is how it work. Now I often have to search on Wikipedia to find in what region of the country the address I want to go is :(

OsmAnd "just" have to make the search in all the maps that correspond to the Country and add the region (region + postal/zip codes) name to the results.

It will be great too to have the possibility to download a full country map.

Thanks !

**Comment by vshcherb** [comment]
I agree that's neither a comprehensive neither a handy approach.
Currently available workaround:
You can also download maps directly from the map or you also can search in POI (we have all the cities available offline in the world base map).

**Comment by Paviluf** [comment]
Ok thanks for the workarounds !

**Comment by homersimpsons** [comment]
I think region is quite good, in France I have downloaded full for region where I go and road only for others. But getting a single index for whole country would be really helpful.

**Comment by Paviluf** [comment]
Any news on this ?

**Comment by Paviluf** [comment]
Still no plan for this ?

**Comment by sonora** [comment]
Obsolete with new search interface.

**Comment by Paviluf** [comment]
> unless I misunderstand this

I will check when the apk will be available. Thank you !

**Comment by homersimpsons** [comment]
I don't think that this is really obsolete. 
Because:
1. use the navigation shortcut (bottom right)
2. Select From or To
3. Select address 

Here you are on the old address search.

**Comment by Paviluf** [comment]
is it "fixed" ?

**Comment by sonora** [comment]
I think we do now not re-direct to the legacy search interface any more, so it is deprecated, or am I mistaken?

Also: The "best" wording is debated above, so it is not clear which one to use to please everyone?
