### ISSUE TITLE
OsmAnd's behavior when deleting images/audio/video from storage during operation

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#2597]
1.Take photo
2.Do not kill OsmAnd and delete image from storage
3.Image date becomes 1 jan 1970
I suggest to delete such objects completely. If no file exist why show it?
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot_2016-05-25-13-02-28.png

**Comment by kompowiec** [comment]
>Do not kill OsmAnd

Maybe it's cause?

**Comment by vshcherb** [comment]
We are just discussing that OsmAnd should not be magic program that tracks everything but it could display context menu slightly better.
