### ISSUE TITLE
OsmAnd offline router is not choosing optimal route.

### ISSUE THREAD

**Issue by teriblus** [osmandapp/Osmand#2599]
OsmAnd does not choose the optimal route in the following example:
![screenshot_2016-05-26-10-06-52](https://cloud.githubusercontent.com/assets/17048774/15568013/016068a6-232a-11e6-9edd-10473fbe9b13.png)

I expect it to turn left to get to the destination, but it decide to do a loop around the block instead.
There is no turn restriction on the OSM map:
![selection_002](https://cloud.githubusercontent.com/assets/17048774/15568079/4407b510-232a-11e6-9dcb-564e2ffe16d2.png)

The location is: https://www.openstreetmap.org/#map=19/48.74641/-3.47409

I'm using OsmAnd offline routing. 
The problem occurs in both native and safe modes. 
The problem occurs in both shortest and fastest modes.
Version 2.3.5 / 2016-04-28

**Comment by lvml** [comment]
(For a similar problem with bike routing see #2509)

**Comment by vshcherb** [comment]
Looks like it is very similar to #2748
