### ISSUE TITLE
Direction from

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#2600]
When you put the Destination from, then on to another point tap FAB (Route), Destination from erased from Route Preparation.

**Comment by sonora** [comment]
Not sure if this is what you  mean, or if this is just a similar bug:

When you long-tap any point on the map, the "3 dots" button in its context menu popping will offer "Directions from", but only when no route has been or is being calculated.

Some users select the destination first by selecting a location and tapping its blue Directions button, and then OsmAnd will start calculating the route from the current position. When the user then says "No, I actually want it from there" and then long-taps a point on the map, there will be no "Directions from" option shown for that point (instead I think we convert that menu entry to "Add as last intermediate destination").  I think "Directions from" may have to be available regardless.
