### ISSUE TITLE
OSM Live: Roads from zoom 13-14 are rendered duplicate or missing 

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#2603]
https://www.openstreetmap.org/#map=14/56.0686/40.4953
http://builder.osmand.net/aosmc/russia_vladimir_asia/Russia_vladimir_asia_16_05_15.obf.gz
13-14 zoom: part of highway disappeared
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot%20from%202016-05-16%20102349.png

**Comment by robinpaulson** [comment]
Yep, I get this too. Intermittently though. Ask if you want more infi

**Comment by jej** [comment]
I don't think it's exactly a duplicate. I cannot see the screenshot so not possible to tell if the visual problem is the same.
I tested on a fresh install without Osm live and the problem is the same. But it's sure that the problem disappears when safe mode is enable.

**Comment by vshcherb** [comment]
This issue is fixed since September maps & September updates. Note the base map should be from September 2017
