### ISSUE TITLE
OSM Live: after update previous road is still partially visible (geohash collision)

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#2604]
http://www.openstreetmap.org/#map=15/56.277267/40.3089
http://builder.osmand.net/aosmc/russia_vladimir_asia/Russia_vladimir_asia_16_05_15.obf.gz
No track: https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot%20from%202016-05-16%20102834.png
Track is visible after map position change: https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot%20from%202016-05-16%20102913.png

**Comment by vshcherb** [comment]
Not reproducible
