### ISSUE TITLE
OSM Live: part of highway rendered as was before update

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#2605]
http://www.openstreetmap.org/#map=15/56.32412/40.40293
http://builder.osmand.net/aosmc/russia_vladimir_asia/Russia_vladimir_asia_16_05_15.obf.gz
Zoom 14: https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot%20from%202016-05-16%2010%3A53%3A42.png
Zoom 15: https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot%20from%202016-05-16%2010%3A53%3A07.png

**Comment by vshcherb** [comment]
Duplicate #2603
