### ISSUE TITLE
Shall we delete the approach messages for POI (GPX waypoints, Favorites) ?

### ISSUE THREAD

**Issue by kompowiec** [osmandapp/Osmand#2606]
I was asked about create new issue so i do ;)
"I need to know which voice language you are talking about, and we need to compare with what you hear in that same situation when you switch to TTS English vice."
I used Polish TTS voice, message it looks something like this:
Straight ahead for about one kilometer,  **then you will** pass POI [type] [name].
(pl. Prosto przez około jeden kilometr, następnie miniesz POI [rodzaj] [nazwa])
message appears every time, when i pass some POI (if is this eg. fuel, it's quite often), replace how much is left to the next instruction and after say about POI. After a shorter time say a way for me to correct or "You pass POI" (pl. mijasz POI). Better simply delete instruction with "then" which needlessly replace how many kilometers yet to drive.Even without up message, navigation can be repeated often enough instructions.

"Can I please ask you to test this again with the latest nightly build, because there have been some changes since you commented."
I tested now, acually i have newest version with f-droid and not fixed.
edit: night bulid proably not fixed too.

I hope that write mair understandable. If anything, ask.

**Comment by sonora** [comment]
@kompowiec, thank you for reporting this here! Two things:

(A) Announcing the POIs is not our standard, you can disable this any time in OsmAnd by going to Menu -> Settings -> Navigation settings -> Announce...: There disable "Nearby POi" if you do not need any announcement for them. Our default is to only to announce GPX waypoints, not "Nearby Favorites" and not "Nearby POI" (because you may hear way too much talking.).

(B) If you need Nearby POI announcement: Please help improve the Polish translations. I will tell you below what the correct sentence is in English (x.1), and then what the Polish TTS currently says (x.2). So could you please translate each first line into correct Polish ? Thanks!

(1.1) "Continue for 3 kilometers."
(1.2) "Prosto przez 3 kilometrów"   (I think this means:  "Straight through 3 km"?)

 (2.1) "Continue for 3 kilometers and pass POI <name>"
(2.2) "Prosto przez 3 kilometrów, następnie miniesz POI <name>"  (I think the second half may be correct, but he first half sounds wrong?)

(3.1) "You are passing POI <name>"         (Means: hat you are passing the POI now, now you are closest.)
(3.2) "mijasz POI"

**Comment by kompowiec** [comment]
>(I think the second half may be correct, but he first half sounds wrong?)
Yes, because navigation say about km quite often already without this too (i know that can it change in settings, but no for nearby POIs exactly)
>(I think this means: "Straight through 3 km"?)
Yes, this translate is exactly correct. As for me, is OK.

I think so enough simply delete 2.1/2.2 line which replace 3.1/3.2. Because it's quite annoying when driving.

**Comment by sonora** [comment]
I see. So the idea is to actually generally delete our approach voice prompt for POI.  I think this may be a good chance to reduce OsmAnd chattiness. I am wondering
 - anybody would really miss these POI approach messages functionality-wise (maybe in situations where you have very few around, like gas stations or alpine huts in remote areas?)
 - if for consistency we should delete the approach prompts for GPX waypoints and Favorites as well.

I assume we could suppress all 3, I would just comment this out in our code everywhere, but let me run this by Victor first.

**Comment by sonora** [comment]
PS: Including a distance parameter in prompt 3.1 may be difficult, because some points are right on your route, others you pass at some distance. The 2 cases may require substantially different wording in most languages.

**Comment by kompowiec** [comment]
>if anybody would really miss these POI approach messages functionality-wise (maybe in situations where you have very few around, like gas stations or alpine huts in remote areas?)

It's a bit confusing, similar messages:
after 1520m turn slightly left
(pl. skręć lekko w lewo za około dwóch kilometrów)
I think so in English this is done correctly, but in polish It sounds more like this:
**Turn slightly** to the left for about two kilometers.
after 1520m **turn slightly** left
Translate is opposite. It's confusing, because i on a highway if you hear that I turn, I turn to it just in case you do not lose the exit. Should be like in english version.

**Comment by sonora** [comment]
@kompowiec: Your word order issue is done. You can test in latest nightly, if you want. Please comment if you want the distance portion all the way at the end (after the street and destination name), or before the street name as it is now.

So in Polish, other than "**after** 1520m", you have no good different word for **"in** 1520 m", indicating this is slightly closer now? In German people use something like after="later in" and in="in":
"**Later in** 2km turn left", and "**In** 300m turn left."

If you want to assist even further, you can do the following:
1. In OsmAnd, go to Menu/Plugins and enable the OsmAnd Development Plugin.
2. Restart OsmAnd, then go to Menu/Settings/OsmAndDevelopment.
3. Go to "Test Voice prompts", select pl-tts, and test all buttons. Tell me which buttons need fixing in Polish.

(If you go to "Test Voice prompts" and no buttons appear, go back, re-select "Test voice prompts" and select another language first, like en-tts.)

Thanks!

**Comment by kompowiec** [comment]
ARGHHH i'm idiot shit.I'm very sorry. I'm so sorry.

**Turn slightly** to the left for about two kilometers.
(pl. **skręć lekko w lewo** za około dwóch kilometrów) 

after 1520m **turn slightly** left
(pl. Za około dwóch kilometrów **skręć lekko w lewo**)
other, for about two kilometers **turn slightly** in left

You give english messages i did it correct, but i do mistake translate polish - in other words, nothing has changed. Simply This same sentence as before:

>It's a bit confusing, similar messages:
after 1520m turn slightly left
**(pl. skręć lekko w lewo za około dwóch kilometrów)** (i critical actually message)
[...]
>Correctly translate:
after 1520m turn slightly left
(pl. Za około dwóch kilometrów skręć lekko w lewo) - badly
**(pl. skręć lekko w lewo za około dwóch kilometrów)** - (but put it back)

Sorry ;(

it, what is in english on end, in polish it's on begin. logical conjunction languages fail.

>So in Polish, other than "after 1520m", you have no good different word for "in 1520 m", indicating this is slightly closer now? In German people use something like after="later in" and in="in":
"Later in 2km turn left", and "In 300m turn left."

normally word "in" is translated in polish as "w" but i think so don't have here use.

**Comment by sonora** [comment]
So are we back to word order:  "Distance ---- Turn Type ---- Street Name/Destination" ? That's how most languages have it. Or how else?

And you want "After 1520m turn slightly left" sound the same as the next announcemen1 "In 300m turn slightly left", no different wording, right?

Could ypu please check ALL buttons from "Test Voice Prompts" in Development Settings, and tell me which ones need changing (just give the button name and the correct Polish)

**Comment by kompowiec** [comment]
>And you want "After 1520m turn slightly left" sound the same as the next announcemen1 "In 300m turn slightly left", no different wording, right?

In english sure no, in polish unfortunately yes - are it two different wording (but no meaning different, just chic sentence)  It's difficult to explain to a person who does not know language. Sorry, sorry, sorry ;(
It, what is in english of the end, in polish is sometimes on the begin and opposite. Therefore in english no haven't different, because in english is poorer compared to other languages.

from the beginning I wanted the formula of which you write, (begin distance) but by my stupidity it didn't happen ;(

>Could ypu please check ALL buttons from "Test Voice Prompts" in Development Settings, and tell me which ones need changing (just give the button name and the correct Polish)

of course i checked early (even i see in latest nightly new prompt "You are back on route"). Others voice messages is perfectly.

>So are we back to word order: "Distance ---- Turn Type ---- Street Name/Destination" ? That's how most languages have it. Or how else?

My mistake resulted from this that i give identical sentence as before exists in app, so by my stupidity nothing has changed. Sorry ;(

if you can improve yourself translation? I'd rather not bother anyone ass and improve what I can. Eg. Change marker's position isn't translated (should be "zmień pozycję markera" - i checked this sentence at least 5 times, have no right to be a mistake).

**Comment by sonora** [comment]
@kompowiec : Regarding your word order question: I have made some changes, please test latest build. If it is still not correct, please open a separate issue, ok?

**Comment by vshcherb** [comment]
@sonora can you mention please commits included. From the code for me it will be easier understand what is exact change. Though I don't agree we should suppress these messages, I think we have separate setting to disable it.

**Comment by sonora** [comment]
Victor, there is no commit yet.

I think what the user suggests is that we should generally remove the voice prompts which are created via
 - (VoiceRouter.jave) public void approachPoi(...)

(and possibly also approachFavorite and approachWaypont).

The user says the respective announcePOI (announce Favorite/announceWaypoit) prompts are sufficient, and OsmAnd is way too chatty with the additional "approachPOI" prompts, because you approach POIs of most types selected very frequently, and there is no point in always hearing that there is one in 1 km or so away, which you cannot even see yet.

I can imagine he is right, but have never tested myself. Guess we need some testing to judge this.

You are right that we have a setting to disable announcing nearby POIs (which is actually our default and I use it all the time), but it affects both the approachPOI and the anouncePOI prompts.

**Comment by kompowiec** [comment]
>Regarding your word order question: I have made some changes, please test latest build. If it is still not correct, please open a separate issue, ok?
Wow, it's work perfectly! Very thanks! ;)

**Comment by vshcherb** [comment]
Now I see, I guess I have no enough test experience in my cases I always use rear POI's like fuel station and with POI like restaurants it could be very chatty, I did put a delay to not speak too often about POI's may be that creates an issue? APPROACH_POI_LIMIT = 3. 
private static final int LONG_ANNOUNCE_RADIUS = 700;
	private static final int SHORT_ANNOUNCE_RADIUS = 150;

**Comment by sonora** [comment]
@kompowiec Ok, I will set APPROACH_POI_LIMIT = 1, please test today's nightly. This means that there will only be approach messages for **one** POI at a time, hence no overlapping/interleaving prompts for POIs, and I guess this should do it.

As a last resort we could also try  APPROACH_POI_LIMIT = 0 which should suppress the approach POI message altogether, but that may not be good on many occasions, I think.

**Comment by sonora** [comment]
I consider this is fixed. (?)
