### ISSUE TITLE
Water disappears on closer zoom

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#2607]
Sweden, lake Stora le/ On closer zooms water disappears.

![image1](https://cloud.githubusercontent.com/assets/12711814/15613276/67f22fc0-243b-11e6-9928-de34b2def404.jpg)
![image2](https://cloud.githubusercontent.com/assets/12711814/15613275/67ef0746-243b-11e6-889e-b057d5851ff4.jpg)

**Comment by vshcherb** [comment]
https://www.openstreetmap.org/way/57042857#map=11/58.9863/12.0654

**Comment by vshcherb** [comment]
@xmd5a2 Can we prepare a small map containing just this lake and convert with obf2osm, so we might see something wrong in the obf data. This lake also is not displayed in the legacy rendering

**Comment by njohnston** [comment]
I discovered similar behaviour for [Lundy, a small island off the coast of England](http://www.openstreetmap.org/#map=13/51.1896/-4.6539).

At zoom 12, the island is rendered correctly:

![osmand_water_issue_ok_small](https://cloud.githubusercontent.com/assets/638458/16422782/8c124f50-3d51-11e6-88df-db548d4572fc.jpg)

At zoom 13, the water disappears:

![osmand_water_issue_broken_small](https://cloud.githubusercontent.com/assets/638458/16422768/83e73976-3d51-11e6-8c4e-1c50ef67e897.jpg)

logcat shows:

```
I net.osmand: MapRenderRepositories RENDER MAP: new request RotatedTileBox [lat=51.179412841796875, lon=-4.666409969329834, rotate=0.0, density=3.0, zoom=13, mapDensity=3.0, zoomAnimation=0.0, zoomFloatPart=0.0, cx=900, cy=1386, pixWidth=1800, pixHeight=2772]
I net.osmand:native: Route objects 182
I net.osmand:native: Islands 33, closed water 2, coastline touches screen 0
```

Note "coastline touches screen 0". I think it should be 1.

The water is also missing at zoom 14, but returns at zoom 15:

![osmand_water_issue_ok_higher_zoom_small](https://cloud.githubusercontent.com/assets/638458/16422891/e5376746-3d51-11e6-93d2-5c852ba79b20.jpg)

At zoom 15, logcat includes:

```
I net.osmand: MapRenderRepositories RENDER MAP: new request RotatedTileBox [lat=51.179412841796875, lon=-4.666409969329834, rotate=0.0, density=3.0, zoom=15, mapDensity=3.0, zoomAnimation=0.0, zoomFloatPart=0.0, cx=900, cy=1386, pixWidth=1800, pixHeight=2772]
I net.osmand:native: Route objects 284
I net.osmand:native: Islands 22, closed water 5, coastline touches screen 1
```

Note "coastline touches screen **1**".

**Comment by Leif-W** [comment]
Similar behavior noticed in the US, not sure if it's related.  Assuming zoomed all the way out is level 0, then at zoom level 10, there is water for lakes, at zoom level 11, some larger bodies of water disappear while other smaller lakes and ponds remain.  The larger bodies of water should remain.  It's a handy visual cue when driving if you glance quick at map and verify that you are supposed to be driving by a lake, and not a field or woodlands or a hill, etc.  Not sure how to generate detailed logs.

**Comment by xmd5a2** [comment]
Issue in first post is resolved by fixing our planet update process. @njohnston your case is completely different. Please create separate issue.
