### ISSUE TITLE
Make POI display profile dependent

### ISSUE THREAD

**Issue by kompowiec** [osmandapp/Osmand#2611]
When click on menu-->configure map-->exploring mode-->POI-->nearby POIs (is very useful show all POIs on exploring mode when eg. add something to fav) it in other mode (car, bicycle, pederastian) i have identical setting. Why can't set different POI for every mode?

**Comment by sonora** [comment]
I think we already had this, but many non-expert users where confused by POIs sometimes showing, sometimes not, especially since we switch modes automatically for navigation...
