### ISSUE TITLE
Overlay map is not displayed

### ISSUE THREAD

**Issue by Zahnstocher** [osmandapp/Osmand#2612]
The overlay map is not displayed, but the same map is working as underlay map.
The transparency slider which should appear under
Overlay map -> Overlay transparency
is not visible.
Also the transparency slider on the map is not shown anymore (underlay and overlay).

**Comment by GaidamakUA** [comment]
@Zahnstocher please give us more info. What map you have problems with?

**Comment by Zahnstocher** [comment]
Online maps (for example "Microsoft Earth") and offline maps (for example SQLite or tiles) don't work.
I don't think, that it has something to do with the map itself, because the same maps work as underlay, but they do not work as overlay.

**Comment by Zahnstocher** [comment]
I cleaned the app data (via Android settings) of OsmAnd, now it is working again.
I think OsmAnd was not able to read the stored transparency value, because it was somehow wrong or corrupt.
