### ISSUE TITLE
Allow offline upload of crash reports

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#2613]
Currently crash reports are encouraged to be submitted via an email client or skype, while driving.

It might be worthwhile to allow, as a further option, to save the report for later upload, for these reasons:
- submission while driving might be dangerous
- the phone is offline
- starting skype starts another memory hog that squeezes out OsmAnd
- OsmAnd should better recalculate the route, which is often the reason for the crash.

So just saving them into the OsmAnd folder would help.

**Comment by kompowiec** [comment]
email can save in drafts - afther crashing OsmAnd see option "send report"/"cancel". Click option 1, choice via email and save in draft. You send later (however i use K-9 Mail and always crashed this app, strange)

**Comment by polarbearing** [comment]
Thanks @kompowiec - but that still requires to call an email client (memory consumption) and multiple clicks, which is unsafe while driving. Further it requires the email client to be configured on the device, which is not necessary if the device is not used for mailing.

**Comment by scaidermern** [comment]
My pre-installed mail app never managed to save/send the attachment where the exception is stored, only the basic information including the device info and app version. But OsmAnd stores the exception.log in its directory so it is possible to dismiss this dialog and obtain the exception at a later point from the log file.

**Comment by vshcherb** [comment]
They will be sent all together in exception.log file so you can send them later after driving. Don't bother while you are driving.
