### ISSUE TITLE
Zoom in/out like google maps (double tap + drag) is very unreliable for some users

### ISSUE THREAD

**Issue by bjohas** [osmandapp/Osmand#2617]
It would be nice if osmand supported zoom in/out like google maps, i.e. double tap + drag up to zoom out, and double tap + drag down to zoom in. The double tap (without drag) should be maintained to zoom in. The large "+" and "-" buttons could (optionally) be hidden.

**Comment by stephan75** [comment]
This feature is already implemented in Osmand, I can do this zooming in and out with only one finger.

Why are you not able to do this? What Osmand version?

**Comment by homersimpsons** [comment]
Works for me too

**Comment by xmd5a2** [comment]
Already fixed

**Comment by bjohas** [comment]
I'm on the 2.3 nightly from yesterday, OSMAnd~ 2.4.0#3754M_2.3. 

How do you zoom out with one finger? Same as google maps, i.e. tap plus tap-drag? Doesn't work for me.

(In case it's relevant, double tap to zoom in also didn't work in the 2.3 nightly for some time. However, I upgraded recently, and it's now working.)

**Comment by homersimpsons** [comment]
@bjohas For me this works; I'm on Osmand~ 2.3.5 from F-Droid

**Comment by scaidermern** [comment]
Doesn't work for me in OsmAnd, neither in stable nor nightly. It always reacts on the first tap and uses it to center the position. Is there some specific plugin or setting required?

**Comment by bjohas** [comment]
I've just tested this also with OsmAnd 2.3.5 (free version) and it doesn't work either. How do you get this to work?

**Comment by vrtareg** [comment]
Just tested on nightly builds. 
Double tap on map and hold, then move up or down on screen to zoom in and out. 
There is a slight glitch when map actually zooms in on double tap but reverts back to original zoom once detects holding.

**Comment by scaidermern** [comment]
Now I got it working a few times. But this seems to be extreme buggy. Most of the time the map just gets centered, a marker gets set and the location lookup panel appears at the bottom. This works way better in Google Maps, unfortunately :/

**Comment by bjohas** [comment]
Thanks - I can confirm that I managed to get this to work a few times too, but as https://github.com/scaidermern mentioned,  it's not reliable at all. Most of the time there's a zoom (like double tap), then a pin is dropped and tray opens, no further zoom in/out possible. (I.e. two separate gestures). Agreed that it works in goggle maps without problems.

**Comment by bjohas** [comment]
@xmd5a2 - I've changed the title of this issue - could you reopen?

**Comment by bjohas** [comment]
Latest nightly (2.3) - it seems that up to about zoom level 9, the double tap + drag works as advertised, but for higher zoom levels, it doesn't. Maybe that's where the different reports in this thread came from?

**Comment by bjohas** [comment]
Also in the latest nightly, POIs/Favourites can only be selected through tap+hold, which is different from earlier versions, where a single tap selected the POI. Single tap (on POI or otherwise) now gives "destination not set".

**Comment by bjohas** [comment]
Latest nightly: The "orientation button" now works as expected again, but POIs still require long press.

**Comment by GaidamakUA** [comment]
Please check out tomorrow's nightly. Behaviour should be much more stable.

**Comment by bjohas** [comment]
Great stuff - will do!

**Comment by scaidermern** [comment]
Not sure if it works slightly better. But 2.4.0#13192D still produces a marker on first tap wich in turn produces the annoying popup at the bottom which in turn stops dragging. So it still works rather unreliably for me.

**Comment by GaidamakUA** [comment]
Hope this commit will finally solve the issue. https://github.com/osmandapp/Osmand/commit/3d66b5bf224cc3c052bbb5c331c719e686cf30a2

**Comment by scaidermern** [comment]
Still produces 9/10 times a marker instead of zooming :( I wonder how/why it works for your.

**Comment by bjohas** [comment]
Just tested this on build 3851, and similarly it only works very rarely. 9 out of 10 you still just get the marker, rather than zooming.

**Comment by bjohas** [comment]
I've tested this again - there seems to be some improvement at some zoom levels, but still not that reliable.

**Comment by bjohas** [comment]
Thanks! Works well now!

**Comment by bjohas** [comment]
I've discovered another problem with this feature. Imagine moving the map downwards, i.e. repeatedly swipe down along the screen. On Google maps, this swipe is detected as a swipe, and the map just keeps moving down. However, in OSMAND, the map starts zooming. Maybe the tap-swipe needs to be constrained so that the first tap really is a tap, and not a swipe?

**Comment by crimean** [comment]
@bjohas do you use latest build?

**Comment by bjohas** [comment]
Ah - no, I was a couple of days back! Just upgraded, and the problem is fixed - thanks!

**Comment by scaidermern** [comment]
Works great now even when tapping on markers. Thanks!
