### ISSUE TITLE
Adding map orientation "North is up, fixed"

### ISSUE THREAD

**Issue by bjohas** [osmandapp/Osmand#2618]
The suggestion is to add another option to map orientation, which is "North is up, fixed". In that mode, the map cannot be rotated manually. I.e. this contrasts with the existing "N is up, don't rotate" mode, where the map can still be rotated manually. (I'm suggesting this because during sight seeing I found myself often accidentally rotating the map manually while zooming in/out, which was inconvenient.) See thread "Various suggestions", on google groups.

**Comment by sonora** [comment]
I also know many users having an issue with accidentally rotating the map manually, then not knowing what they did and not knowing how to reset, or even not being aware of it ...

Most of them recommend removing this feature of "manual map rotation" completely, saying this functionality is obsolete. (If need be, you can in most cases  rotate the device. :smiley:  )

Should we decide to move the map rotation button to the Configure map menu (see #2621 ), we may want to remove the functionally, or disable it and make a boolean "enable map twisting" setting for it.

**Comment by littlehelper** [comment]
I use the "manual map rotation" feature quite often. Please do not remove it completely from the map screen (also discussed in #2623).

**Comment by bjohas** [comment]
I'd definitely suggest to retain the manual map rotation. It means that an interesting feature can be rotated so that it fits onto the screen. :)

But the extra option ("fixed") would be nice to have.

**Comment by bjohas** [comment]
This issue https://github.com/osmandapp/Osmand/issues/2617 concerned zooming (in comparison to Google maps). However, the rotation is also different: Google maps rotates (with the same gesture), but less so by accident. Whereas OSMAND can rotate "by accident". I would suggest that in addition to the suggested feature, the gesture for rotation should be improved, to avoid accidental rotation.

**Comment by sonora** [comment]
Mostly fixed, no further action planned it seems.
