### ISSUE TITLE
Fix confusing "Configure map" interaction between "World/Car/Bike/Walk"

### ISSUE THREAD

**Issue by bjohas** [osmandapp/Osmand#2619]
The current "configure map" options have confusing interaction between "World/Car/Bike/Walk". The rule seems to be the first menu item under "Show" doesn't depend on "World/Car/Bike/Walk", while the other two sections "Map rendering"  and "Other..." depend on  "World/Car/Bike/Walk" as follows: if a setting in "Car/Bike/Walk" has never been altered, and the setting in changed in World, the corresponding setting in "Car/Bike/Walk" also changes. If the setting in "Car/Bike/Walk" has been altered, it's independent of World. This is confusing.

My suggestions would be to make all "Configure map" settings specific to "World/Car/Bike/Walk" (including the "Show" section, i.e. including POI), without any interaction between World and the others.

If some interaction between World and the other settings is desirable to other users, then either:
- when you change a setting in World, there should be a popup "Copy settings to other views? Yes, no, never, always" or similar. 
- or, each setting within "car/bike/walk" should have an additional option: "same as world".

**Comment by bjohas** [comment]
In relation to https://github.com/osmandapp/Osmand/issues/2626, it would be helpful to implement this for POI display first.

**Comment by jkufner** [comment]
I found relations between these options confusing too, I wasn't even aware there is a relation. As I mentioned earlier in mailing list, I would like to see tri-state options. The third state would mean "use World settings". Then the world settings would act as a base for all other profiles/views, where the specialized profiles would change only a few options and left most options to inherit from the World. This is exactly what is in the last point in this issue description.

Copying settings may be difficult when some options shall be preserved and others not and I believe the tri-state options would do the trick in a simpler way.

**Comment by enomat** [comment]
@bjohas 
I agree with your first suggestion.

"World/Car/Bike/Walk" should have their own specific settings profile without any interaction between them. This would the simplest and most obvious way.

**Comment by bjohas** [comment]
See also https://github.com/osmandapp/Osmand/issues/2704

**Comment by bjohas** [comment]
"Transport options" has now been moved up in the menu next to POIs - that's great. It also remains specific to the profile, which is also great, and important. As commented by @enomat and @jkufner it would be really good to have the same for POIs. Totally independent settings (bringing it in line with transport options) would be fine for me.

**Comment by vshcherb** [comment]
That's a bug rather than a feature, especially property for transport stops (not rendering style)

**Comment by sonora** [comment]
Looks like no further action planed here for now(?).
