### ISSUE TITLE
Additional "transport mode icons" under "Configure map" and "configure screen"

### ISSUE THREAD

**Issue by bjohas** [osmandapp/Osmand#2620]
I'd suggest adding icons (transport modes) alongside "World/Car/Bike/Walk", such as "Train", "Plane", "Boat". The new set of icons would be "World/Car/Bike/Walk/Train/Plane/Boat".

**Comment by vshcherb** [comment]
It is available in Development settings

**Comment by bjohas** [comment]
Ok, I found it under plugins > OSMAnd Development > Application Profiles. 
Thanks!
