### ISSUE TITLE
Make "search icon" more prominent.

### ISSUE THREAD

**Issue by bjohas** [osmandapp/Osmand#2623]
Rather than accessing the search only the settings menu, a "search icon" should (optionally) be placed on the main screen.

**Comment by rwoloszyn** [comment]
or even search box in the top of the map.

**Comment by sonora** [comment]
Very little screen real-estate on small devices.

But I seriously suggest to remove the "map orientation" button, which is a setting comparatively rarely changed (move the functionality into "Map configuration"), and put a "magnifying glass" Search button in its place (pointing to our search screen with all the search tabs). Search is a CORE and often needed functionality of our app!

**Comment by Barrocas** [comment]
Please do not remove the 'map orientation' that I suppose is the small
round compass button on the top left corner.

It's been there since the begining, and it's the only indication to our
'North' heading while navigating.


-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by littlehelper** [comment]
I use the "manual map rotation" feature quite often. Please do not remove it completely from the map screen (also discussed in #2618).

Since we have several ideas about which features to show on the map screen, I recommend to offer the possibility to display or hide each feature individually (similar to the widges).

**Comment by bjohas** [comment]
Agreed that treating the buttons as widgets (enabled/disabled through "configure screen") would be good.

**Comment by rwoloszyn** [comment]
+1 to threating buttons as widget idea

**Comment by bjohas** [comment]
See also https://github.com/osmandapp/Osmand/issues/2706

**Comment by sonora** [comment]
Already fixed via new search button.
