### ISSUE TITLE
Easier on/off switching of POI

### ISSUE THREAD

**Issue by bjohas** [osmandapp/Osmand#2626]
The process of switching POIs on/off currently involves more steps than switching "underlay map". The suggest is to make POI display the same as (e.g. for) "underlay map".

Explanation: To switch POIs on, these steps are required:

1. Tap configure map
2. Tap POIs
3. Potentially scroll
4. Tap OK.

If POIs are switched off, and back on, the complete process needs to be repeated, making it hard to switch POIs on/off easily.

By contrast, e.g. for underlay "underlap map", the underlay map itself is remembered, and can be switched on/off (tapping on the right) without needing to re-select the map (which can be done by tapping on the left). The process should be the same for POIs.

**Comment by sonora** [comment]
Problem is that for the overlay/underlay what is selected is a single parameter and can be easily displayed as etxt, while, if we "remembered" the previously selected POIs (or POI combinations, like we now support), it could be any combination of tick boxes, many of hem not visible on the POI selection screen without scrolling.

So users re-entering that screen when no POIs are displayed may not be aware, and may not see that there are pre-selections "remembered" from way before, and may get weird results. I also think that in many use cases when re-entering that screen with no POIs displayed, users may want to start from fresh, they do not regularly want to re-create the last POI lookup selection they had. (And if they do, they could always save it as a Custom filter so it can be re-selected with fewer clicks.)

**Comment by bjohas** [comment]
I guess I do switch them on/off a fair bit. They do make the map harder to read, so e.g. when sightseeing I want to switch wikipedia icons on to find nearby information, but then switch it off again to find my bearing. Maybe it could become an option to remember or not remember it...

**Comment by vshcherb** [comment]
I don't expect it will be easy to fix cause we moved from single selection to multiple selection.
