### ISSUE TITLE
Additional "application profiles" for bus and train

### ISSUE THREAD

**Issue by bjohas** [osmandapp/Osmand#2629]
OSMAnd has some additional transport mode icons available under "plugins > OSMAnd Development > Application Profiles" (see https://github.com/osmandapp/Osmand/issues/2620). However, there are no icons for "bus" and "train" - common modes of transport with specific requirements (e.g. display of bus routes). 

The suggestion is to add icons for bus and train to "plugins > OSMAnd Development > Application Profiles".

**Comment by vshcherb** [comment]
It is not much clear how it will be used but I think it is possible to add them.

**Comment by bjohas** [comment]
The idea is that e.g. bus can be (manually configured) to show all bus lines, meaning that it's easy to switch to a view that shows bus lines. Similarly for "train", which could be configured to show train lines. Alternatively, both of these just provide two additional configuration ops, to customise maps views.

**Comment by GaidamakUA** [comment]
https://github.com/osmandapp/Osmand/pull/2646 first version implemented.

**Comment by vshcherb** [comment]
Fixed e2231dd

**Comment by bjohas** [comment]
Thanks! Much appreciated!
