### ISSUE TITLE
Possibility to highlight a single bus route

### ISSUE THREAD

**Issue by morray** [osmandapp/Osmand#2634]
There should be a possibility to highlight one single bus/train/... route. In a second step also routing using these routes would be good. In a third timetables of these routes ;-).
Great app. Keep on.

**Comment by sonora** [comment]
I think (other than time tables) this is fixed in our latest version?

**Comment by morray** [comment]
Cool! Is it already released? Just tried in my installed version and didn't find anything like this.

**Comment by sonora** [comment]
Yes, see info and screenshot here http://osmand.net/blog under "OsmAnd 2.4", Section "Better Public Transpport Information".

**Comment by aceman444** [comment]
Yes, it is available in 2.4. Timetables are not in OSM yet.
