### ISSUE TITLE
no Osmand-directory visible

### ISSUE THREAD

**Issue by Atompilz** [osmandapp/Osmand#2635]
Hi,

I wanted to see GPX-Tracks and maps, which are created with OsmandMapCreator, on Osmand but there is no visible Osmand-directory on my phone although Osmand says that the directory is /data/data/net.osmand.plus/files/osmand/tracks.

It's possible to make GPX-tracks with Osmand and save them. It's also possible to open them again, but outside of Osmand the GPX-Tracks aren't visible: there is no directory /data/data/net.osmand.plus/files/osmand/tracks on the phone. I even searched for the GPX-Files with the Linux-Terminal, but they aren't visible (other test-files from outside Osmand had been visible).
When I want to change the Osmand-directory in deleting the last folder-name (/data/data/net.osmand.plus/files/osmand  -> /data/data/net.osmand.plus/files) Osmand says that the directory doesn't exist! If /data/data/net.osmand.plus/files/osmand exists the mother-directory /data/data/net.osmand.plus/files must exist too!
Even the log-files created  by Osmand aren't usable outside of Osmand: When I try to send a crash-report, the email-app always says that there isn't such a log-file (which is automatically tried to be appended at the email).
With the Apk Version : 2.4.0#16960M 231 I made the same experience as the current version which is on GooglePlay.

Device : cosmopolitan
Brand : lge
Model : LG-P920
Product : cosmo_open_eu
Build : ICS
Version : 4.0.4
App Version : OsmAnd~

Is there any possibility to use data from Osmand outside of Osmand and to use data from outside of Osmand in Osmand?

best reguards

**Comment by homersimpsons** [comment]
I've got osmand in 'sdcard/osmand'
maybe you have it under 'sdcard/Android/data/net.osmand.plus' try to search 'osmand' via your explorer

**Comment by Atompilz** [comment]
yes, I searched osmand via explorer and via terminal on linux, but the directories haven't been visible.
Now I changed the Osmand-Directory to "/sdcard/osmand" successfully. There everything is visible :+1:

**Comment by sonora** [comment]
Android keeps changing the folders an app has write access to, particularly for external storage.

While e.g. in Android <4.4 the folder could be pretty much everything (we used <media>/osmand), in 4.4.x this folder was mandatory if external storage is used: <media>/Android/data/net.osmand(.plus)/files.

(Rules for internal storage usually less restrictive). OsmAnd sub-folder structure is the same in any case, for documentation see or tech articles..
