### ISSUE TITLE
Public Transport: Show stop names from the parent relation

### ISSUE THREAD

**Issue by mchapliuk** [osmandapp/Osmand#2637]
It's a good way to add stop's name only to a relation `stop_area`, and remove the `name` attribute from the `stop_position`s and `platform`s of that relation.

At this moment Osmand does not take the name attribute from a parent relation, just shows a bus stop without names.

**Expected:** If `stop_position` and/or `platform` don't have `name` attribute - take the name from the parent relation `public_transport=stop_area`. Or even override children names with the name from the `stop_area` relation.

Osmand+ 2.3.5

**Comment by vshcherb** [comment]
Can you please give an OSM example

**Comment by mchapliuk** [comment]
https://www.openstreetmap.org/edit#map=20/50.43816/30.46608

edit mode (yes, OSM doesn't show stops if they don't have names :(), in the middle of the map https://www.openstreetmap.org/edit#map=20/50.43816/30.46608
