### ISSUE TITLE
Missing maps..... (Download selection issue)

### ISSUE THREAD

**Issue by noci2012** [osmandapp/Osmand#2639]
Downloading of maps fail.

First note that the maps are on the download site, they can be downloaded manualy and unzipped and manually placed. 

The OSMAND+ maps only shows 3 global maps, and other maps.
Opening othermaps gives a HUGE list maps from Algeria, Australia, Bhutan, Brazil..China, 
virtually all of Europe, US, Canada,  is wiped of the world.
The only exception seems to be Sweden, Norway, US Hawaii

Just opening the Map selection screen shows the omission.

What version of OsmAnd are you using, on what device and Android/iOS version?
Most recent update (April, 2016, no obvious version # found).

This is about off-line maps only as i have no use for online maps. And concerns the map selection for download.

Besides this issue
The Extra-Maps section is unusable as well as it is a huge sequential list of maps, not even sorted alphabetically.   It would be an improvement to do grouping based on first word IMHO.
Or categorized by map type, the current mish mash is hardly usable.

**Comment by vshcherb** [comment]
The bug report is not clear, please redownload the maps.

**Comment by noci2012** [comment]
The maps (EU, US, CA) are NOT shown on the map download menu.
There are 3 maps shown "wereldkaarten"  (worldmap, height correction, seamap) + "Extra kaarten"
with all kinds of countries like algeria, chad, sudan, china (many times), russia (many times).....
Sweden, Norway (for europe)

There is no way to download the maps i need: Germany (Hamburg, Bremen, Vorpommern, ...) , Denmark.  Also not shown other EU coutries like france, belgium, netherlands...

When googling for how to manually download maps i can find current maps on all EU countries.
So maps are not missing on the website for maps, there is no way to click an item on the phone to download them... (This is OSMAND+, the one with unlimited downloads... at least that was promissed when i payed for it).

**Comment by scaidermern** [comment]
I think I experienced the same problem once but I can't remember the cause or how I fixed it. Maybe your _regions.ocbf_ is broken? Try deleting it, it should be located directly in the osmand directory.

**Comment by noci2012** [comment]
![Uploading Screenshot_2016-06-02-18-36-58.jpeg…]()

**Comment by noci2012** [comment]
I tried to upload a screenshot...., no luck appearantlu an image (.jpeg, or .png) cannot be uploaded.

**Comment by noci2012** [comment]
![screenshot_2016-06-02-18-36-58](https://cloud.githubusercontent.com/assets/1962961/15760364/27d86832-2913-11e6-850e-13192f3ecb26.jpg)

**Comment by noci2012** [comment]
And yes, deleteing regions.ocbf did help.

**Comment by noci2012** [comment]
@vshcherb    if it is not clear ASK for information, don't jump to conclusions of invalid claims.
and this issue is not actualy solved yet, there is a solution which will work on a rooted device where a file browser is installed. Hardly something a regular user can do.
Deleting and reinstalling the app will also require about 8GB of maps te redownload... so not a valid workaround either.

in short:
A corrupted file appearantly caused the problem, and one needs a rooted phone to get rid of it, so maybe a forced reload of regions.ocbf or reset of regions file is required as an option to the user to repair it.

So maybe an option should be added to erase the regions file .....

**Comment by scaidermern** [comment]
You shouldn't need root to delete this file, a file browser is usually installed on every device (... I had so far). Also it should not be necessary to re-download all the maps if re-installing the app.

Nevertheless OsmAnd *should* be able to detect a corrupted *regions.ocbf* and re-download it automatically or at least ask to re-download it. Doesn't seem to be such a special case since I also experienced this issue.

@vshcherb I suggest to reopen this issue and maybe rename it to "Broken regions.ocbf not detected / automatically re-downloaded" or something similar. This problem should get fixed.

**Comment by vshcherb** [comment]
@vshcherb I suggest to reopen this issue and maybe rename it to "Broken regions.ocbf not detected / automatically re-downloaded" or something similar. This problem should get fixed.
It should give an error message if it is broken, it was not giving as I see, so validation could not handle

**Comment by noci2012** [comment]
The  file is in Android/data/net.osmandplus/files   which is not accessible for other apps except osmandplus. (hell when 4.4 came out, it wasn't even accesible on the SDext card for the app itself).
In a previous phone those directories were not even shown to a user.

**Comment by noci2012** [comment]
There is no way for me to reopen. (No button visible) I will create a new one and point here.
