### ISSUE TITLE
Search: Changing between house number and street intersetion mode too hidden

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2640]
Not sure if this is going to be changed any time anyway soon by our work on ""searching", but just for documentation:

When you start searching on our address search tab, we initially hide the radio button selector to look for either house number or street intersection on that screen. But when you then go through selecting Country/City/Street, users do normally not go back to that screen to see the option appearing after they have specified the (first) street, so the functionality is lost to hem. 

I guess a quick fix could be we always from the beginning how the radio button house-number/intersection selector, even I no street is yet filled?

**Comment by vshcherb** [comment]
Good for documentation but in many many cases users still go to housenumber.
