### ISSUE TITLE
Save current GPX trace takes some time and needs a progress indicator

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#2641]
I pressed "Save current GPX track" and assumed that, when the dialog disappeared, the track was already saved. I did not realise that saving the current GPX track(s) takes quite long time. While I saw that the GPX-button had turned to "Save" it was unclear that this was still in progress, and I closed the app.

What I found were a few gpx files, the most recent missing, and the last one being written was truncated.

I tried again and let the "Save" run, which took 5 min until it turned back into the "GPX" button, and wrote 24 MB of files. 

The good thing is that no data were missing, the app had kept the internal storage until the saving was successful in the end.

Suggestions: 
- Indicate more clearly that the saving is still in progress (progress bar, rename "Save" to "Saving", have the word "Saving" blink), 
- give a warning before closing the app that saving is still in progress
- rename "Save current GPX track" into "Save recent GPX tracks" since it can a couple of them.

(tested in 2.4.0#16950M, on Nexus S)

**Comment by sonora** [comment]
You are correct, you will never lose data, hence I think this is really a non-issue.

Plus: unless I am very mistaken, I think I had once implemented the red recording indication in the GPX recording widget to blink while a track is being saved. Not sure this is still functional, though ... (takes a really long track to test :) )

**Comment by Barrocas** [comment]
Yes, the gpx widget blinks red while recording a track.
But was the problem while the track was being made, or when we have to
choose 'stop gpx track' and then 'save current gpx'?

That leads to another basic question, why doesn't Osmand just auto-save the
gpx track as it is being recorded?
Why do we have to 'stop' and then press the widget again to 'save' that
track?

The process could be easier:
1) start a gpx track, and while being recorded, the following options could
be...
2a) pause recording
2b) stop and auto-save the recorded track



-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by sonora** [comment]
Regarding the blinking: It think the behavior should be:
- Red dot indicates track is being recorded (lights up continuously), but
- dot briefly "blinks" whenever a point is being recorded, i.e. e.g. every 5 seconds if that is your recoding interval
- The dot should flash in quick succession as long as a save operation is ongoing.

Regarding the separation of "stop" and "save": I think this is a wording issue: "Stop" is really "Pause" by most conventions. So if you are e.g. on a hiking tour and want to pause your recording while being inside an alpine hut, but want to resume the same track after you get going again, you would hit "Stop", but would not "save" the track yet, as this would attach the end mark to the track and close the file.

**Comment by polarbearing** [comment]
The renaming in my third suggestion would already help to understand, that it is not just one track I save, it is all the tracks from the last month that I haven't saved yet.

**Comment by Barrocas** [comment]
What I suggested was that Osmand could have already saved those last
month tracks, the user shouldn't have to do it manually.

So a 'Stop and Save' would stop recording and save it, while a 'Pause'
would... well, pause recording, and wait for a restart.

-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by sonora** [comment]
I cannot actually reproduce how you would have more than one track in memory. Either you saved it, or one is still open. Even if OsmAnd crashes or gets killed, any open the track will be saved to the file system at the next app start, I just tested this once more.

Please note that it is rather unreliable when you will "see" the file in the file system. When connected to a PC, you often have to disconnect and re-connect the USB cable. When viewing on your device directly, it depends on the tool.

If it helps any, I could think about re-wording as follows:
- "Stop GPX logging" becomes "Pause GPX logging"
- "Save GPX file" becomes "Stop and Save GPX file"
The latter actually requires a small code change also, because the current "Save GPX file" does NOT stop the logging.

**Comment by Barrocas** [comment]
I think that would be more intuitive for the user.

-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by polarbearing** [comment]
> I cannot actually reproduce how you would have more than one track in memory

In "Trip recording", "Log tack to GPX file during navigation" is ON. Thus driving around for four weeks with navigation collects a new ```<trkseg>``` for each route, internally. When I "Save current GPX track", all these data are written into multiple files, one file per day, with possibly multiple ```<trkseg>```s in it.

**Comment by sonora** [comment]
Looks like no action is planned here.
