### ISSUE TITLE
Turn:lanes oddities without reason in the data

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#2642]
Version: 2.4.0#16950M / Car profile / Device: Nexus S
OBF: Germany_brandenburg_europe_2.obf, 1 May 2016

Situation: B1 jct Kressenweg. Screenshots collected in simulation mode after real traffic experience.

Routing from [here](https://www.openstreetmap.org/node/21509213) to [there](https://www.openstreetmap.org/node/59851167)

**First problem:** On this [segment](https://www.openstreetmap.org/way/316318948) I am getting told to prefer the left Through-lane, no reason why.
![screenshot_2016-06-01-20-52-22_a](https://cloud.githubusercontent.com/assets/8266355/15723676/dcc813da-2843-11e6-87f8-5168217e6ef9.png)

**Second problem:** Continuing on these segments [1](https://www.openstreetmap.org/way/166973639) [2](https://www.openstreetmap.org/way/159300046) [3](https://www.openstreetmap.org/way/159294607) [4](https://www.openstreetmap.org/way/304980024) [5](https://www.openstreetmap.org/way/343841020), most of the time before the junction, the left turn lane is green in addition to the two through lanes:
![screenshot_2016-06-01-20-52-31_x](https://cloud.githubusercontent.com/assets/8266355/15725321/a200dd10-284b-11e6-9404-691a39ed12fb.png)

![screenshot_2016-06-01-20-50-26_y](https://cloud.githubusercontent.com/assets/8266355/15724536/be3c5c24-2847-11e6-9462-e025694cf36f.png)

Immediately before the junction, the turn lanes become correct:
![screenshot_2016-06-01-20-50-32_z](https://cloud.githubusercontent.com/assets/8266355/15723866/9fe819e6-2844-11e6-82d4-ce2d6d290b01.png)

Now, before passing the junction, the left lane is dropped:
![screenshot_2016-06-01-22-46-40_zz](https://cloud.githubusercontent.com/assets/8266355/15725370/d9a80734-284b-11e6-8f8f-b29a65ab3cfe.png)

After the junction, the B1 continues with 2 lanes, which matches the 2 through lanes.

**Comment by polarbearing** [comment]
Turning right from [Blumberger Damm](https://www.openstreetmap.org/way/185661961) into [Warener Str](https://www.openstreetmap.org/way/66218888) indicates a through lane in addition to the right turn lane. The lane count of all surrounding streets appears to be correct. 
![screenshot_2016-06-01-16-34-53_warner_str](https://cloud.githubusercontent.com/assets/8266355/15725717/78965ab6-284d-11e6-983b-d06e30876ef6.png)

**Comment by vshcherb** [comment]
@xmd5a2 Please create all of these tests even if they are passing now

**Comment by xmd5a2** [comment]
Tests added

**Comment by polarbearing** [comment]
Turning from [Schildhornstr](https://www.openstreetmap.org/way/318138844) ```none|through|right``` via [node](https://www.openstreetmap.org/node/26583824) into [Lepsiusstr](https://www.openstreetmap.org/way/4475167) (1 leaving lane)

Version: 2.4.0#17009M / Car profile / Device: Nexus S
OBF: Germany_brandenburg_europe_2.obf, 1 May 2016

![screenshot_2016-06-03-13-55-54_lepsiusstr](https://cloud.githubusercontent.com/assets/8266355/15798792/e4707cea-2a45-11e6-9826-0a4a00f924f6.png)

**Comment by scaidermern** [comment]
_turn:lanes:backward=none|through|right_? Is there really no left turn arrow? However highlighting the through arrow seems odd.

**Comment by polarbearing** [comment]
No there isn't, and that is quite common in Berlin. Only lanes that have a restriction are marked, from the unmarked you can make any turn that does not collide with the marked lanes. So in this case, from the unmarked I can turn left and go through, but not turn right since it collides with the middle lane 'through'.

**Comment by vshcherb** [comment]
Fixed

**Comment by polarbearing** [comment]
Tested in 17145M (2016-06-16), simulation mode, confirming fix. Will keep an eye open while driving.
