### ISSUE TITLE
Non-functional OsmAnd instances after app has been started via "Open URL" action

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2643]
Under some circumstances we somehow have an issue in the program flow, or we kind of have 2 active instances of OsmAnd "interfering", not sure. This can be reproduced as follows:

1. Have OsmAnd running, started via its shortcut in "All apps" (or a shortcut you may have on the home screen).
2. Switch to some other app, e.g. an SMS, where you tap a location (e.g. google maps or osmand.net) URL, and select OsmAnd to perform the "Open URL" action. -> OsmAnd pops up and correctly displays the location.
3.Now tap the home button to put OsmAnd (or should I say: this instance of OsmAnd?)  in the background 
4. Go to "All apps" (or use an OsmAnd shortcut on your home screen) to return to OsmAnd.

The instance of OsmAnd you are looking at now behaves weird:
(a) Long-tapping on arbitrary locations on the map produces the orange marker, but no context menu pops up. 
(b) Tapping the orange marker itself does not produce a context menu
(c) Going to search, searching something, then selecting a search hit returns to the map, but still displays the last orange maker. Map does neither pan the map to the location of the search hit, nor mark it, nor produce its context menu.
(d) Same as (c) for e.g. going to favorites
(e) Sometimes: The Search/POI tab will show all pre-defined search categories duplicated, tripled, etc. (I think an additional set is added for each time a new OsmAnd instance is started via the URL method.)

I think we end up in a situation here where there are 2 instances of OsmAnd somehow "overlapping". Killing OsmAnd in the task manger remediates the situation. Tapping the Back key often enough to put you on the home screen, then tapping an OsmAnd shortcut there remediates the situation, too. But going to Androids "recent apps" bar seems to indicate another instance of OsmAnd running labeled "SMS" (i.e. under the app you had the URL in.) switching to that task returns you again to a non-functional instance of OsmAnd.

**Comment by sonora** [comment]
@vshcherb From my tests, issues (a) - (d) are fixed by using android:launchMode="singleTask" in https://github.com/osmandapp/Osmand/blob/master/OsmAnd/AndroidManifest.xml#L76.

But issue (e) remains:  Each time we launch OsmAnd via a geo-search URL, we again add a duplicate of all SearchPOI categories (I think we have code to add any pre-used ones, so this is what must somehow happen here).

**Comment by vshcherb** [comment]
So I guess (e) is the only issue left and it could be attacked separately.

**Comment by sonora** [comment]
I have committed this https://github.com/osmandapp/Osmand/commit/e4d546f7bd493ce7750a6e7187969fa315c36d20 to master now, had been testing it for 2 days and it works well, I see no adverse effects.

Yes, (e) needs to be attacked separately, small glitch somewhere in EditPoiFilter, SearchPoiFilter, or related helpers.

**Comment by vshcherb** [comment]
I fixed (e), though it was a surprise that every time OsmAndApplication.startApplication is called. So looks like it is completely reinitialized except something that was stored in static variables
