### ISSUE TITLE
Incorrectly calculated offline route with "beelines"

### ISSUE THREAD

**Issue by fkoester** [osmandapp/Osmand#2645]
I recently noted a miscalculated long-distance route between Bochum, Germany and Veere, Netherlands using downloaded offline maps and offline routing with car profile (fastest). As you can easily see on the attached screenshot, the calculated route is wrong. It does not follow any roads but goes straight from one point near the start location to one point near the target location.

I am using OSMAnd+ 2.3.5 on Android installed from Play Store. Device is a Moto G3 with Cyanogenmod 13 (Android 6).

The relevant map files are Germany -> North Rhine-Westphalia (01.05.2016) and The Netherlands (01.04.2016).

The start point is:
Germany-> North Rhine-Westphalia -> Bochum -> Ehrenfeldstraße 8

The target point is:
Netherlands->Veere->Koningin-Emmaweg 1

![screenshot_20160602-102315](https://cloud.githubusercontent.com/assets/1298987/15740614/dd4dac76-28b5-11e6-8ca1-6bd092350210.png)

![screenshot_20160602-102352](https://cloud.githubusercontent.com/assets/1298987/15740652/0bfba898-28b6-11e6-8034-986444ade961.png)

![screenshot_20160602-102401](https://cloud.githubusercontent.com/assets/1298987/15740671/1ff07ac2-28b6-11e6-95a7-3899fc19c77d.png)

![screenshot_20160602-113324](https://cloud.githubusercontent.com/assets/1298987/15740673/23be354a-28b6-11e6-8a25-2c3a4743b86b.png)
.
![screenshot_20160602-113333](https://cloud.githubusercontent.com/assets/1298987/15740680/30c7b270-28b6-11e6-973d-6ab6c40bb33c.png)

**Comment by fkoester** [comment]
A workaround is to manually add some waypoints in between

**Comment by fkoester** [comment]
Also happens with the current map data (NRW, Netherlands, Belgium) from June.

**Comment by vshcherb** [comment]
Can't reproduce it https://photos.google.com/share/AF1QipNb6BxkjOe5LgOSORcDbmiLD075qsZqJg65W5XfvO2HI162kMxSYgYJf-vpni3MJQ?key=Q1NYd2NQUG9JSmlERWRwamRFYnFxZl9obVpmZ0R3.

It might be related that phone runs out of memory, these long routes are not perfectly working in OsmAnd.
