### ISSUE TITLE
Zoomlevel 20 and above with tile maps

### ISSUE THREAD

**Issue by dpuschek** [osmandapp/Osmand#2648]
This Issue was already solved in past: https://code.google.com/archive/p/osmand/issues/896
For a few month it's reappeared :(

Osmand-nightly 26.12.2015 (Ver 2.3): Can zoom to zoomlevel 20
Osmand-nightly 14.02.2016 (Ver 2.3): Can just zoom up to zoomlevel 18
Osmand-nightly today (Ver 2.4): Can still just zoom up to zoomlevel 18

Please fix this issue again! All my own tile-maps have just zoomlevel 17 and (19 or 20). 

The issue:

What steps will reproduce the problem? use own created SQLite atlases from MOBAC with sat-tiles at Zoomlevel 20. Select it in Osmand ->  map source -> own.sqlitedb 3. Try to zoom to zoomlevel 20

What is the expected output? What do you see instead? Cannot zoom higher than zoomlevel 18.

What version of the product are you using? On what operating system? - OsmAnd-nightly.apk from 02-Jun-2016

Please provide any additional information below.

By using the 'Offline vector maps' and my own tile map as 'Overlay map', I'm able to zoom to zoomlevel 20 and higher! But I don't want to use 'Offline vector maps' additionally

**Comment by dpuschek** [comment]
Tested OsmAnd-nightly.apk	03-Jun-2016 12:58

Now I can zoom up to level 19, but still not 20.

**Comment by dpuschek** [comment]
OsmAnd-nightly.apk	03-Jun-2016 21:58

Same problem

**Comment by xmd5a2** [comment]
@dpuschek can you upload somewhere this problematic sqlitedb?

**Comment by xmd5a2** [comment]
@dpuschek this is zoom 20 from your map with current osmand-nightly
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot_2016-06-07-19-08-02.png

**Comment by dpuschek** [comment]
Yes, indeed! This is zoomlevel 20! What osmand-nightly do you use?
At 16:43PM CEST I downloaded http://download.osmand.net/latest-night-build/OsmAnd-nightly.apk and this version doesn't work with zoomlevel 20 for me (as source map)

**Comment by xmd5a2** [comment]
I use exactly this version. Downloaded half a hour ago and selected cologne.sqlitedb3 as source map.

**Comment by dpuschek** [comment]
Maybe I'm stupid :(. Please tell me, what I'm doing wrong:
http://dom.homenet.org/MAQ00828.mp4

**Comment by xmd5a2** [comment]
That's very strange. Looks like you simply can't go deeper than zoom 19 but I can.

**Comment by dpuschek** [comment]
Now I tried
- settings -> apps > osmand -> clear data
- create a total new osmand folder und internal storage
- test on a second phone from my wife: 
 - Sony Z1C with Android 4.4.4 stock rom.
 - my one: Motorola Moto G with Android5.1/CM12)

No luck: I cannot zoom higher than 19. Maybe I use the wrong path for sqlitedb files? I always put them to osmand/tiles folder. Tried just the osmand-folder, but there they aren't recognized. I also have to activate the "Online Maps" plugin, to use my offline sqlitedb tile-maps.

**Comment by sonora** [comment]
I assume tapping the zoom+ button instead of pinching makes no difference?

**Comment by dpuschek** [comment]
That's it! With zoom+ button I can go to zoomlevel 20! I never use these buttons. So it is a "pinch to zoom" bug.

**Comment by dpuschek** [comment]
Now it works fine! Thank you!
