### ISSUE TITLE
Offline routing: Route calculation can get hung

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2652]
If you start a navigation (in Follow mode) while you are still on a parking lot separated from the public roads by a lift-gate with access=private (as some supermarket parking lots are sometimes mapped), the route calculation seems to get stuck with the progress indicator shortly before the end.
- This seems to stay like this forever, we do not "detect" this situation?
- But what is worse: If you drive though the lift_gate and are on public roads now, the situation never recovers. To remediate the situation, you need to manually cancel the route calculation and manually re-start it, which many users are not aware of. Deserves fixing.

**Comment by vshcherb** [comment]
It is handled by saying the road could not be calculated but may it is not displayed correctly.

**Comment by sonora** [comment]
Some more details, this is interesting: Yes, we used to detect this condition and stop the route calculation, and then have a toast message, I think (Probably RoutingHeper.java, line 850 or so).

What I reported was user experience from several reports. Now I just ran some tests myself using a simulation (User reported this starting from http://www.openstreetmap.org/way/233704441): Funny thing is this:
- A short route (3km) from there calculates perfectly correct, exiting through http://www.openstreetmap.org/node/345671579 onto the public side.
- A Long route (150km) from the very same starting point "hangs" forever, (or for very long, I waited like 5 minutes), and I think this is what users see. The route calculation progress bar is stuck at what looks like 100% (or near 100%) of the _second_ time it runs (know how it runs twice for each route calculation). Looks like the route calculation never finishes. Killing it manually by tapping the (X) button takes unusually long (~10 sec), until the button color goes from blue to gray again, almost like OsmAnd has to clear a lot of garbage from memory.
- The same 150km route from just outside the gate http://www.openstreetmap.org/node/345671579 calculates correctly in about 15 sec.

I notice this parking lot 2 exits, both access=private. Not sure if that impacts this issue.

**Comment by vshcherb** [comment]
The fix is incomplete and possibly breaks other corner cases https://github.com/osmandapp/OsmAnd-resources/commit/fa680fc4d107f971a8ca0b286deeb1ab2a64ca1c. Though the reason is in small coefficients of private roads and high barriers timestamps. So low coefficients make it almost impassable from point A and bidirectional A* chooses to grow from the other side (from point B). The network graph in Bayer is so huge that it takes very long time to stop doing it and connect to point A. This is a correct implementation of bidirectional A* but it leads to inneficient routing

**Comment by sonora** [comment]
I guess we must have changed something some time ago, because some users are certain these very same routes had worked perfectly ok at some point (maybe months or years ago, no details available here) with older OsmAnd versions, but then with some update it had stopped working.

**Comment by vshcherb** [comment]
Yes there was a raise with timings in order to avoid private roads and of course the map is changing. As I see that's the only reason.
