### ISSUE TITLE
Highway shields in Brazil

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#2653]
Even with the latest nightly osmand and a freshly generated map I don't see any kind of customized highway shields in Brazil:

![](https://cloud.githubusercontent.com/assets/982338/15788643/e1afdcb4-299e-11e6-889d-661bbe3cf000.png)

**Comment by xmd5a2** [comment]
Did you generated map by yourself?
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot%20from%202016-06-03%2022%3A29%3A47.png

**Comment by naoliv** [comment]
Yes, I am using the latest MapCreator in batch mode like:

```
java -cp "./OsmAndMapCreator.jar:./lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.data.index.IndexBatchCreator batch.xml
```

Inside `batch.xml` I only changed the directories.

**Comment by xmd5a2** [comment]
Map source name should start with "Brazil" (registry independent).

**Comment by naoliv** [comment]
Didn't know it was necessary to start with "Brazil". I was using "Brasil".
Now it's working. Thanks!
