### ISSUE TITLE
Poor routing with "Shortest way" enabled

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#2654]
OsmAnd appears to make poor routing choices when using Shortest Way.  I've noticed this on several occasions, but I wanted to wait until I had a very clear example to use.

- OsmAnd release version 2.3.5 (2016-04-28) and many nightly builds, including 2.4.0#16999M (2016-06-02)

- Android 5.0 on Samsung Galaxy S5, and Android 6.0.1 on Samsung Galaxy S7

- Using OsmAnd's offline maps.  On the S5, the United States Georgia April 30, 2016 map.  On the S7, the United States Georgia April 30, 2016 map with the latest Live updates.

Problem occurs with both Car and Bike profiles.  (Pedestrian profile routes correctly.)

Steps to reproduce:

For the Start and End points, I select the hamlet Henderson, Georgia http://osm.org/go/ZHF91YmU-?node=154364175 and the city Vienna, Georgia http://osm.org/go/ZHFsjbyI-?relation=119829.  I've tried it routing in both directions.  For my testing, I did not bother to select a street, I just used the town nodes.

For routing options, I begin with all of them unselected (i.e., none of the "avoid" settings selected, and I use Fastest way instead of Shortest way).

For Car profile, results are as expected:
OsmAnd routes me to the nearby freeway I 75, along it, and then off at an appropriate exit to reach my destination, about 20 miles.

For Bike profile, results are as expected:
OsmAnd routes me along primary road US 41/GA 7, about 19.5 miles.

Next, enable the Avoid Motorways setting.  OsmAnd recalculates the route.

For Car profile, results are as expected:
OsmAnd routes me along US 41/GA 7, about 19.5 miles.

For Bike profile, results are as expected:
OsmAnd routes me along US 41/GA 7, about 19.5 miles.

Next, enable the Shortest Way setting.  (You can do this with or without Avoid Motorways enabled.  The results are the same.)  OsmAnd recalculates the route.

For Car profile, results are NOT as expected:
OsmAnd routes me along US 41/GA 7, which is not the shortest route.  It _should_ route me along US 41 until it reaches Old National Highway/Old Vienna Road (depending on which direction you're going), then along that route, until it reaches US 41 again, about 17.4 miles.

For Bike profile, results are NOT as expected:
OsmAnd routes me along US 41/GA 7, which is not the shortest route.  It _should_ route me along US 41 until it reaches Old National Highway/Old Vienna Road (depending on which direction you're going), then along that route, until it reaches US 41 again, about 17.4 miles.

Pedestrian profile *does* use Old National Highway/Old Vienna Road in the route.  Simply select it to see the route I expected the Car and Bike proflies to use.

I will note that in the current US Georgia map file, Old National Highway and Old Vienna Road are classified as Residential, with no road surface or maxspeed tags.  I recently drove that route to capture data about it, and I'm using that information to update OSM (in progress).  Even so, I would expect the Shortest Way option to choose that route without my updates.

**Comment by vshcherb** [comment]
Situation with latest version:
1. car, fastest - uses I75 - distance 34064 meters
2. car, short_way - uses US41 - distances 31658 meters
3. bicycle (doesn't have short_way) - CR331 - distance 28172 meters.

Even though 2nd is not the shortest option but it works as expected. It is economic way which limits speed to 55kmh, in order to produce short way using CR331, this constant need to be 40kmh which is undesirable for other situations.

I agree that's confusing so I opened another issue to resolve confusion https://github.com/osmandapp/Osmand/issues/2943, this one though will be closed

**Comment by jfburke3** [comment]
Thanks for the clarification.  I did not realize that the option also limited maximum speed (which I could probably have determined from routing.xml if I had thought to look there).

**Comment by vshcherb** [comment]
Unfortunately not it is hardcoded https://github.com/osmandapp/Osmand/blob/master/OsmAnd-java/src/net/osmand/router/GeneralRouter.java#L26

**Comment by jfburke3** [comment]
Just adding a remark that in the latest nightly builds, both car "fuel economy" routing as well as bicycle routing uses the Old National Highway/Old Vienna Road/CR 331 road.  I'm going to guess that the maxspeed tags I was able to add have helped some, along with whatever tweaks you made in recent code releases.
