### ISSUE TITLE
Improved address determination of addr:*-less POI nodes

### ISSUE THREAD

**Issue by jengelh** [osmandapp/Osmand#2655]
# What version of OsmAnd are you using, on what device and Android/iOS version?

OsmAnd+ 2.3.5, released: 2016-04-28. Android 5.1.1.

# Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps? If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

Germany Lower Saxony offline vector, dated May 1 2016.

Concerning the town of Göttingen. Zoom to lat=51.53366,lon=9.93517. Use the "Search nere hear" feature to select precisely the Footlocker store (node 447956646) in the vincinity. As the node has no address information attached to it (some intelligent OSM users removed these), OsmAnd tries to derive the address, and arrives at "Barfüßerstraße 10". This however is grossly incorrect, and there is an easier way to determine it, since the shoe store node is part of a way (technically "one or more ways…") which have addr:* tags, such as way 50223573. OsmAnd should make use of this information where so derivable.

**Comment by vshcherb** [comment]
Fixed
