### ISSUE TITLE
Edit notes

### ISSUE THREAD

**Issue by kompowiec** [osmandapp/Osmand#2656]
Isn't it strange that can edit local POIs but Note (so-called bug-id) or not?

POI (modify OSM change)
https://i.imgur.com/TT3BEfk.png

Note (none option "modify note/bug fix")
https://i.imgur.com/yRXpLqm.png

**Comment by vshcherb** [comment]
Don't see anything strange, all buttons are related to Notes layer, so you need to enable it first.
