### ISSUE TITLE
Search functionality can get hung over time

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2657]
Due to @rominf 's work, some of our search functionality has turned lightning fast!

But we (still) have a condition where the search functionality can get hung almost completely, (actually not hung, but it takes many minutes to display results).

This is essentially created by doing e.g. a "Search by name" over a large area. It looks like after OsmAmd at one point had to perform such a "very big search", search performance for all subsequent searches can be extremely affected, and then even things which normally took only seconds to show up, like a POI/Wikipedia search with 1km radius, or even just showing the initial  "big city list" after tapping a region in the address list screen, can take like 3-5 minutes to pull up (before that just showing an empty list and the spinner). Looks like a memory or index housekeeping issue, or something, maybe we need  better "reset" strategy?

Condition is reliably remediated after staring OsmAnd fresh.

**Comment by sonora** [comment]
I wonder if we simple never call AsyncTask.canel(true) anywhere, and hence under some circumstances have a search task (or several?) continuing on in the background...

**Comment by sonora** [comment]
After my fix for 2667 it became pretty easy to test out that the issue here seems in deed that any previous search AsyncTask keeps running to its regular end before any new search starts up. Hence the challenge is to find a way to kill the currentSearchTask if the user abandons it via the search screen's "back-arrow" button or the device's back button. (Not quite straight forward as it does not consist of a loop but rather is essentially one long running statement.)

**Comment by sonora** [comment]
Ok, this implements that the search gets properly shortcut when a UI action says so https://github.com/osmandapp/Osmand/commit/cf897d68ca6e3f43145981baa2c5454bf54dce2b

There is one small glitch still, as follows: If you cancel a long-running search (say a 200km radius search), and then **very quickly** (i.e. before SearchAmenityTask/postExecute has run, typically 1-3 sec) start (the same or a new) POI search, the first results screen of this subsequent search shows no results, but they immediately become visible after tapping "Find more".

Will look into this remaining issue as I find time.

**Comment by vshcherb** [comment]
Unfortunately we need to revert this commit because of the code guidelines, we should never use UI classes in backend classes ResourceManager. I think it is good reference and Roman will look at it later.
P.S. you can't simply kill asynctask, the only thing you can do is wait until it finishes, but if we are talking about destroyactivity we can ignore running task

**Comment by sonora** [comment]
Ok. I wanted to avoid killing the AsyncTask, because its doInBackgrund(...) does not contain a loop. Instead, all of the search time is actually spent in the loops in RessourceManager, which is why I simply introduced the custom stopSearching flag there to "normally terminate" the AsyncTaks per onDestroy() request from the UI.

Maybe we can leave this in as a workaround until another solution is found, because it works well fixing an issue where the Search remained in a situation not producing any results for several minutes, very disconcerting for the user. And the issue was accumulating when the user then performed BACK and re-search on the UI.

**Comment by vshcherb** [comment]
Unfortunately we can't leave that nasty code cause there will be high risk that it stays forever. Cause right the full focus will be on new search this issue will be under low attention. 
To check new search we will start with http://download.osmand.net/latest-night-build/OsmAnd-qt-sample-armv7.apk. Unless we don't finish it next month, it is worth to consider reopening this issue.

**Comment by sonora** [comment]
Ok, I have provided a better fix, see https://github.com/osmandapp/Osmand/commit/0927e79974fa574ce75a7011a86cb29a2915d7b1. I think this should be acceptable?

**Comment by vshcherb** [comment]
It is much better

**Comment by sonora** [comment]
Yeah, works flawlessly on all Android versions I have tested so far. And even if I find one where it does not work (different APIs may exhibit slightly different Async.cancel behavior), no harm should be done, as I simply re-used the query we have always had  in https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/resources/ResourceManager.java#L863, applied it in 2 more places (lines 760 and 839), and now use it as a break point for when the UI want to cancel the search.

Thanks for keeping a watchful eye on our code :)
