### ISSUE TITLE
[Feature request] Improvment in route recalculation

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#2660]
When you are on a motorway and want to recalculate a route avoiding motorways in future, the navigation starts from a nearest non-motorway road. It does not help you get to that road. If you enable "avoid motorways" then OSMAND believes you can't be on a motorway. 
![motor_1](https://cloud.githubusercontent.com/assets/12711814/15804907/090924e4-2b22-11e6-84e4-7fd260c51822.png)
![motor_2](https://cloud.githubusercontent.com/assets/12711814/15804906/0908fe4c-2b22-11e6-8249-bfba4d4965f7.png)

**Comment by sonora** [comment]
Well, the question is here: Why do you want to avoid motorway you are already on, and at what "cost"?

I think if you just exit the motorway any time you like, it will always rectify your issue? But OsmAnd can surely not know if you want to get off at the next exit, or what other "optimization criterion" you may have in mind to chose any exit after the next?

**Comment by vshcherb** [comment]
This has pros and cons and I think this setting has ambiguous meaning, I do believe in this situation you can simply find first exit "manually" not using navigation and then it will guide correctly avoiding motorways.
