### ISSUE TITLE
Change width of current track

### ISSUE THREAD

**Issue by littlehelper** [osmandapp/Osmand#2662]
As selecting the width for the currently recorded track is possible (refer to #1410) I would suggest to enable selecting independent track widths for active/visible tracks too.
Therefore I would introduce the menu "My places" - "My tracks" - track - button at top right (map) - select width (similar to changing the track color, ref. #1212).

**Comment by vshcherb** [comment]
That could be customized with a custom rendering style. For now we don't plan of doing it.
