### ISSUE TITLE
Download map hint in Configure map menu

### ISSUE THREAD

**Issue by littlehelper** [osmandapp/Osmand#2663]
When opening the Configure map menu in landscape mode, a hint "download xyz" is shown on the right part of the screen which opens a menu listing all maps covering the current region/country xyz available for download. This hint is very helpful to identify the corresponding map required for the current region/country, but this hint is only shown in landscape mode and only if no base map is already downloaded/installed locally.
Therefore, my suggestions would be (1) to show this hint also in portrait mode and (2) to show an additional hint "download further maps for xyz" or similar (also directing to the Manage map files menu) if the base map for region/country xyz is already downloaded/installed locally.

**Comment by sonora** [comment]
Looks like no action planed here for now.
