### ISSUE TITLE
Automatic filtering of current region/country in Manage map files

### ISSUE THREAD

**Issue by littlehelper** [osmandapp/Osmand#2664]
From my point of view the Manage map files menu is the place where I would expect to find hints telling me which map I have to download for the current region/country (similar to #2663).
My suggestion (a) would be to add an additional tab "Current region" or similar to the Manage map files menu which shows only the regions/countries currently visible on the map screen. Or to introduce (b) a menu button close to the refresh and search button (top right corner) in the Manage map files menu leading to the same results by filtering the available maps (like when using the search function to search for the region/country of interest).
This would easily help to identify which maps are required to download and would provide a quick access to the available maps for the current region/country of interest. I am aware of the possibility to zoom out in map view several times and select the region/country of interest there - but the Manage map files menu is the place where I would go first for searching and downloading new/additional maps.

**Comment by sonora** [comment]
Download hints are present when selecting locations on the map. No further action planned here.
