### ISSUE TITLE
Middle layer for raster map between vector map and its polygons

### ISSUE THREAD

**Issue by littlehelper** [osmandapp/Osmand#2665]
It is great that Osmand offers to show raster maps overlaying the offline vector map's polygons. But often I would like to have the possibility to show the vector map's lines (streets), points (pois) and labels at the highest layer overlaying even the overlayer map.
Is it possible to use a layer configuration like (top) vector map's streets, pois and labels, (mid) transparent raster map and (bottom) vector map's polygons or underlay raster map?
If no, would it be an idea to introduce a middle layer for raster maps shown underlaying the vector map's lines, points, labels but overlaying the polygons?
In total Osmand would provide the following layers:
1. Overlay map,
2. Vector map's information layer (streets, pois, labels),
3. Middle layer map,
4. Vector map's polygon layer,
5. Underlay map.

**Comment by sonora** [comment]
No action planned for now.
