### ISSUE TITLE
Fix search POI "Filter" behavior

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2667]
Our "Filter" functionality has at least 2 issues creating a strange behavior of our Search POI functionality:

(1) Filter changes typed while a search is running may not be correctly applied to the hit list. Only way to reliably apply them is after the end of the search (i.e. when the  "Find more" button is enabled again) type another change in the Filter field.

(2) The Filter field on he SearchByName  appears as if the "name" query itself is part of the Filter (also explicitly displays "name"), but this is not how the code behaves. Changes applied to the Filter while a search is running produce erratic results. May even be connected to #2657.

**Comment by vshcherb** [comment]
This is a subject to change soon, so the issue won't be fixed now.

**Comment by sonora** [comment]
@vshcherb  Ok! For the record, there is one more bug our "future change" will have to fix:

(3) Allowing to repeatedly apply, change, then re-apply a filter while the Async search task is still running produces incomplete results (results already found but not matching the first filter are dropped).

I have applied the obvious fixes here https://github.com/osmandapp/Osmand/commit/de4d2a2ad3add403cf5e60ebbe525630ba9b4bb4, so for the current interface it works as expected now. (Main trick is to apply all filtering only to each final result list after AsyncTask has finished, not interim.)
