### ISSUE TITLE
The use of flag-shaped buttons is confusing

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2668]
OsmAnd has three different buttons with flag icons. They are used for different purposes:
1. To switch to "POIs along the route" screen
2. To plant a flag at the selected point on the map
3. To fit the selected point into the existing route, as destination or waypoint.

Logically, these buttons should not have "flag" icons at all.
It is better to use an icon that fits their function.

See the attached file for explanation.
[Confusing use of flags.zip](https://github.com/osmandapp/Osmand/files/300090/Confusing.use.of.flags.zip)

**Comment by sonora** [comment]
Let's pursue this in the context of  #2765.
