### ISSUE TITLE
Location of OSMAnd files in storage - manual setting of path occasionally required

### ISSUE THREAD

**Issue by bjohas** [osmandapp/Osmand#2672]
Has the location of OSMAnd files (on storage) changed in 2.4, or is being handled differently? Would make sense if it did, to ensure compatibility with how 5.0 handles locations.

When I first upgraded to the nightly, it went smoothly, but occasionally (after a crash) the nightly cannot find the OSMAnd files (e.g. maps etc), and behaves as if there are no map files. It works again if I manually enter the location through the settings, or re-select "shared memory".

Should there be a feature in 2.4 where it checks several locations and then prompts the user for action? Or some kind of migration assistance in case the way it's handled has changed?

**Comment by sonora** [comment]
Should be deprecated.
