### ISSUE TITLE
Adding new GPX waypoint takes too many taps

### ISSUE THREAD

**Issue by daganzdaanda** [osmandapp/Osmand#2674]
Hi all, 
first off, thank you very much for Osmand, it's very good!

Often, I use Osmand to record a gpx track and information about things that I want to add to the OSM database later with JOSM. Sometimes I take a photo or audio note, but often I want to write a short note to myself. For this, I use gpx waypoints. Since the interface updates, the procedure to add a gpx waypoint has gotten more complicated:
1. long-tap at the desired location (not always my current position)
2. tap the three dots on the bottom right
3. tap "add GPX waypoint"
4. tap the last field (note?)
5. tap "save"
6. tap screen again to see the whole map

I believe only step 2 has been added, but maybe also the 6th step was not necessary before?

Would it be possible to speed up that procedure somehow? 

Unfortunately I can't think of a good solution: expanding the A/V-notes widget would only make it quicker for the current location. 

Maybe allow customizing the pop-up that appears on long-tap? Having a "mapper preset" to show the most important buttons for mappers, or a fully customizable mode, that lets people choose what will be in the pop-up?

**Comment by vshcherb** [comment]
Confirmed, we are in progress to make quick action setup.

**Comment by daganzdaanda** [comment]
Thank you very much!

**Comment by sonora** [comment]
Consolidating into #2765.
