### ISSUE TITLE
Netherlands_overijssel_europe.obf, 1.06.2016 does not render..

### ISSUE THREAD

**Issue by CJTmmr** [osmandapp/Osmand#2675]
The June-map for The Netherlands, Overijssel does not render properly,

Routing, Adress-and POI-search, reverse geocoding all work well, but the map is not displayed. 
Only the "world base map" and bus-stops are rendered.

On the left is a part of Netherlands-Gelderland; on the right Overijssel; 
![2016-06-08 18 07 58](https://cloud.githubusercontent.com/assets/15076257/15906380/dbd7628a-2db8-11e6-9aea-f7fdde89ba8d.png)

![2016-06-08 18 08 20](https://cloud.githubusercontent.com/assets/15076257/15906383/dff12162-2db8-11e6-991f-9e3645f4a53f.png)

All other provinces of The Netherlands are okay.

Could this map be generated again?

Thanks,
Kees-Jan

(with regards to [richardbrinkman ](http://forum.openstreetmap.org/viewtopic.php?id=54836) for noticing)

**Comment by vshcherb** [comment]
Fixed
