### ISSUE TITLE
Attr: value missing on poi additional='brewery_addItional'

### ISSUE THREAD

**Issue by Eibriel** [osmandapp/Osmand#2676]
On CyanogenMod osprey 5.1.1

Map: Argentina southamerica 2016/3/6

Error: 
```
org.xmlpull.v1.XmalPullParserExeption:
Attr: value missing f. additional (possition:START_TAG <poi additional='brewery_addItional'>@418:18 in java.io.InputStreamReader@1f3c1280)
```

Notice th uppercase i or lowcase L on addItional, i can't tell wich is, im copying the error by hand.

Bests!

**Comment by vshcherb** [comment]
Unfortunately we can't neither reproduce neither find where exactly this line is in the code. Could you please try latest nightly and use something like aLogTrace to share the full exception.
