### ISSUE TITLE
OSM Live: SPB subway relation

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#2677]
Duplicate subway line (blue - old, darkred - new):
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot_2016-06-09-19-11-50.png
https://www.openstreetmap.org/way/154420475#map=17/59.90577/30.31939
No subway relation https://www.openstreetmap.org/relation/252540 in acquired overpass data.

Extract from full map dated 1 june: https://dl.dropboxusercontent.com/u/4624786/osm/Russia_leningradskaya_asia_2_cut.obf.zip
obf->osm https://dl.dropboxusercontent.com/u/4624786/osm/Russia_leningradskaya_asia_2_cut.obf.osm
OSM Live update: http://builder.osmand.net/aosmc/russia_leningradskaya_asia/Russia_leningradskaya_asia_16_06_03.obf.gz
http://builder.osmand.net/aosmc/russia_leningradskaya_asia/2016_06_03/russia_leningradskaya_asia_11_00.osm.gz
Data from full map:

``` xml
<way id = '525' version='1'>
    <tag k='railway' v='subway' />
    <tag k='layer' v='-1' />
    <tag k='tunnel' v='yes' />
    <tag k='route' v='subway' />
    <tag k='color_blue' v='null' />
    <tag k='name:de' v='Moskowsko-Petrogradskaja-Linie (Linie 2)' />
    <tag k='ref' v='2' />
    <tag k='name' v='Московско-Петроградская линия (Линия 2)' />
    <tag k='original_id' v='154420475'/>
    <tag k='osmand_id' v='19765820875'/>
```

Data from OSM Live update:

``` xml
<way id = '32762' version='1'>
    <tag k='railway' v='subway' />
    <tag k='layer' v='-1' />
    <tag k='tunnel' v='yes' />
    <tag k='name:de' v='Moskowsko-Petrogradskaja-Linie (Linie 2)' />
    <tag k='name' v='Московско-Петроградская линия (Линия 2)' />
    <tag k='name:ru' v='Московско-Петроградская линия (Линия 2)' />
    <tag k='ref' v='2' />
    <tag k='original_id' v='154420475'/>
    <tag k='osmand_id' v='19765820907'/>
```

There are two issues:
1)Double line
2)No color on new subway line

**Comment by vshcherb** [comment]
Hard to reproduce today, we have test framework and we should catch new issues with it.
