### ISSUE TITLE
feature request: caching rendered tiles

### ISSUE THREAD

**Issue by Be-ing** [osmandapp/OsmAnd#2682]
There is a substantial discrepancy in how long it takes to show different areas when moving the map around using prerendered tiles versus vector data as the main map source. Downloading tiles for an area and configuring them as the underlay alleviates the issue of seeing large gray patches when moving the map quickly. But it is still annoying to have to wait for my phone to render every time to have the map show all features in the ways I have configured for my personal preferences.

I think the user experience could be improved by adding an option to cache tiles rendered from vector data. There could be options to limit the size of the cache or how long tiles are kept in cache. The cache would automatically be cleared when the user changes any option in the "Configure map" menu that affects how the map is displayed. It may also be helpful to be able to render tiles for an area in batches using a similar UI to that used for downloading tiles (a menu item that appears when tapping a point on the map and pressing the "..." icon) within OsmAnd without requiring the use of the Map Creator tool on a separate device (which also doesn't offer the same options as OsmAnd).

**Comment by thinking-aloud** [comment]
This is my biggest critique one this otherwise awesome app as well.

**Comment by thinking-aloud** [comment]
I really don't think, this is nice to have. It is the biggest missing feature of osmand. 
When I show someone something on a map, it takes like 10 seconds to render the view and panning around another 2-5 seconds every time to see all the detail (Using MotoG 2014).
EVERY time people are like: "oh, this map looks nice, but its too slow, for me to use it."
I then go along and tell people about the cool features and explain, that its vector based the that the developers still did not implement a caching feature.
I really can't imagine, that caching is so difficult to implement. So PLEASE give us caching of vector data!

**Comment by Be-ing** [comment]
> I really don't think, this is nice to have. It is the biggest missing feature of osmand.

I agree that this is a bit more important than "nice to have".

> I really can't imagine, that caching is so difficult to implement.

I can imagine that it would take quite a lot of work to implement.

**Comment by Freedoo** [comment]
YES!! This ist not only "nice to have"! 
Osmand is really awesome for planning outdoor routes. And exactly when doing this you have to zoom in and out, scroll over the map back and forth.
And osmand re-renders any part of the map again and again if it has been only one second out of sight. This is so much annoying and lowers user experience so much!!
Please, please, add this!

**Comment by seniorm0ment** [comment]
Please make this happen, it is so frustrating it takes so long to render even on modern devices like a Pixel 6 Pro

**Comment by vshcherb** [comment]
This feature request is outdated cause in 4.2 we've released OpenGL rendering. In 4.3 it becomes default

**Comment by nils-werner** [comment]
Does the OpenGL renderer have output caching? On my phone it doesn't seem to be the case.

Granted, the new renderer is much faster, but especially in large cities rendering is sometimes still slow, and the constant re-rendering is very noticeable. 

Also from an energy conservation standpoint I think output caching should still be considered.
