### ISSUE TITLE
Numbers in opening_hours should not be clickable

### ISSUE THREAD

**Issue by HolgerJeromin** [osmandapp/Osmand#2686]
In the latest play store Osmand plus i can click on some numbers and the call intend is called.
"15" is no useful telephone number to call if a shop opens at 15:00 :-)

**Comment by verdulo** [comment]
Only numbers in "phone" and contact:phone" fields should be clickable; currently almost every number (for example start_date, description) is recognised by OsmAnd as phone number.

**Comment by HolgerJeromin** [comment]
Clicking on urls or numbers in a description is a good thing IMO. start_date is perhaps another candidate for blacklisting. Probably whitelisting is easier. Not sure

**Comment by HolgerJeromin** [comment]
Height is clickable, too
