### ISSUE TITLE
"no_left_turn" "no_right_turn" not implemented ?

### ISSUE THREAD

**Issue by willemijns** [osmandapp/Osmand#2687]
> The best way to get help about an Osmand issue is to create a valid and detailed issue content.
Please give us the following information so that we can try to **reproduce** your issue:

https://groups.google.com/forum/#!topic/osmand/PdHW4G0zAvI

> What version of OsmAnd are you using, on what device and Android/iOS version?
latest osmand 2.3.5 / android 4.4.X

offline maps

> If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

latest build (day-1) complied thanks to osmandmapcreator

> Tell us whether you have used OsmAnd's in-app offline routing, or any online routing provider like YOURS, OpenRouteService or OSRM.

always offline.

YOURS from "Laon Gallet" to "Laon Manoise" give the trouble. (motorcar / shortest). seems their data for calculation are not up to date because the angle drawed by YOURS as the result is different than 
https://01027865525950270145.googlegroups.com/attach/20f54eed8d82a/Screenshot_2016-06-06-16-36-33.png?part=0.1&view=1&vt=ANaJVrHn4r3Ju400ukMBv7Iwnww7I0W_OapJXrPR38RQNpqje9mzYLDpL_mApxDKGLMFJ-_Pcu_JxhWFCLmv0zrpTzXQCfA8juBqhPxD6h6nBXbMGTnczgs

> What routing profile is choosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest)

car.

Please specify as exactly as possible the start and end point of your route by telling us city name and street name so that we can find it via in-app address search easily. Also a permalink from openstreetmap.org can be helpful.

did it on google groups osmand.

> Tell us your expected routing, and how OsmAnd routes, or add screenshots here.

same as precedent

**Comment by vshcherb** [comment]
Way tags no_left_turn are not supported and I hope it won't be popular mapping so we will need to change that decision. The proper way is to tag by relation which includes from, to roles.
