### ISSUE TITLE
Remove POI category "Cafe and restaurant" 

### ISSUE THREAD

**Issue by verdulo** [osmandapp/Osmand#2688]
Currently there is 3 similar POI categories: "Cafe and restaurant", "Food", "Food store". "Food store" is obvious, it's place where you buy store but don't consume it there. But what is the purpose to differentiate inter "Food" and "Cafe and restaurant" - "Food" seems to be a bit broader category, which includes restaurants, cafes and pubs, water taps... I suggest to remove "Cafe and restaurant" category which is a almost duplicate of "Food" to make the POI list shorter.

**Comment by vshcherb** [comment]
In default list there are only 2 of them, "Food" is broader category and it includes fastfood as well and other. It is more related to OSM specifics.

**Comment by homersimpsons** [comment]
I got the same with Osmand~
