### ISSUE TITLE
Impossible to show on map only given additional POIs

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#2689]
Go to Configure map - POI and type "glass", select "Glass (recycling)", search. Appears list of found POI and it seems to be correct. But if I tap "show on map" icon all recycling POIs are shown, not only ones with "glass" additional property.

**Comment by rominf** [comment]
I haven't found exact source of bug, but this place looks suspicious:
https://github.com/osmandapp/Osmand/blob/b8dc11bad9d124d5d1cbf9cc504d96e065c5d42d/OsmAnd/src/net/osmand/plus/poi/PoiUIFilter.java#L463

Here `additionals` for `recycling:glass` are initialized to `recycling`'s additionals (list of 134 values). I didn't understand how `additionals` are used, so I cannot fix it now.

@vshcherb, can you explain?
