### ISSUE TITLE
FR: Show confirmation dialog for deleting maps in free version with no downloads left

### ISSUE THREAD

**Issue by keunes** [osmandapp/Osmand#2691]
For the free version, it would be nice to notify the user that they won't be able to download a new map if they attempt to delete one, while they have no downloads left. Reason: Most users would prefer an outdated map to no map at all.

*I started to think about this when I deleted a map to afterwards download it again, so that I could check if the latest version of a map still had some particular errors or not in navigation. I thought I was contributing to the project, but it felt like being punished for it.*

**Comment by vshcherb** [comment]
In current version there is a progress bar which is irreversible, so deleting one map makes it visible. Though we need to take into consideration your request.

**Comment by keunes** [comment]
> there is a progress bar which is irreversible, so deleting one map makes it visible

In all honesty, the 'empty' progress bar doesn't give me much of a warning (to me it could be equally full or empty). Moreover, when busy with trying to update/delete a map one doesn't pay attention to the text/progress bar so an active warning would be useful.

> we need to take into consideration your request

Why then, may I ask, did you immediately close this issue? The issue being closed feels like "issue has been dealt with, no more action needed" -> contradicts with what you wrote.
