### ISSUE TITLE
More flexible/different freemium model

### ISSUE THREAD

**Issue by keunes** [osmandapp/Osmand#2692]
I am a happy noob contributor to a few FOSS projects via translations, minor changes, feedback and such. In those situations I'm happy to donate, but don't really like it to be forced.

One of those projects is OSM in combination with OsmAnd. I'd be happy to also provide a monetary contribution, but the current system forces you in  nasty way: OsmAnd has a max of 7 downloads. When it's done it's done, and so I have a few remarks around this:

1) How does the live updates subscription work together with limited downloads? (I suspect this limitation is lifted, but there's no info on the main pages)

2) The total lifetime max of 7 updates renders the free app somewhat pointless in a year or two (in regular use, could be 0,5 if you're an active OSM contributor). I would rather see an open source project takes a little more flexible freemium model:
 - rather than having a lifetime maximum of 7 downloads, have:
 - maximum number of _simultaneously installed maps_ (eg maximum one region at a time, the world overview map excluded), and/or
 - maximum number of _downloads per timeframe_ (say max 1/2 download(s) per year)

3) To at least give users a warning before deleting a map in case they have no downloads left (#2691)

*I started to think about this when I deleted a map to afterwards download it again, so that I could check if the latest version of a map still had some particular errors or not in navigation. I thought I was contributing to the project, but it felt like being punished for it. What I'm hoping for is an open discussion here following this experience.*

**Comment by sonora** [comment]
Regarding "... the free app somewhat pointless in a year or two": I guess the idea was if you use OsmAnd regularly over such a long period, you should kindly consider the paid version? :smiley:

**Comment by vshcherb** [comment]
Opensource project should be still supported somehow. There were plenty opensource projects that are already dead in maps area just because there was no financial investment. 
Few comments;
- OSM Live unblock full downloads for the period it works
- OSM Live provides hourly updates and paid version provides monthly updates

**Comment by keunes** [comment]
Sigh... So sad to see happening exactly what I expected: issue closed by @vshcherb without any proper reply countering my arguments. So so disappointing :/

I'd be happy to explain my rational and reply to your (not so much thought through) statements @sonora & @vshcherb, but from the _immediate_ closure I take there's no interest in some user feedback & thoughts. Missed opportunity.
