### ISSUE TITLE
[usability] Save button difficult to find when saving favorite

### ISSUE THREAD

**Issue by sliedes** [osmandapp/Osmand#2694]
The Save button in the Favorite display is so well camouflaged that it causes a bafflement when trying to save a location as favorite. I would say the problem is that it both does not look like a button and that it is in a completely unintuitive position after you have changed the name of the location.

I remember scratching my head twice about how to save a favorite. The second time I remembered there was some trick to it, but could not remember what it was. Anecdotally, I also did a quick usability test and showed the screen to two friends and asked them how to save the favorite. Neither of them noticed the Save button. One of them eventually suggested a Done button in the keyboard, which does not save the favorite. The other one would have tried "Replace" (which doesn't look much like a button either).

**Comment by sliedes** [comment]
![screenshot_20160613-212738](https://cloud.githubusercontent.com/assets/2307997/16019384/5ac5fa38-31b1-11e6-859a-71bf9a420149.png)

**Comment by dmpr0** [comment]
New design for "Add Favorites" screen.
https://www.dropbox.com/s/360g53eltcf9nyu/Favorite_s2-1.png?dl=0
https://www.dropbox.com/s/wnolbr4t2qnyh5w/Favorite_s2-2.png?dl=0

**Comment by pfalcon** [comment]
This UI change, done in 2.2 (or was it 2.1?) is simply atrocious. Actually, with each new version, the UI of OsmAnd gets worse and worse (upgraded to 2.3 before jumping to a car, and cursed OsmAnd all the way - it simply impossible to create a route in a sane way with these new idiotic "map markers"). Funny thing, "new design" from the previous comment is how it was in 1.5 (which was the best version UI-wise, while even then it was much worse than classy software like OziExplorer). Keep breaking users' workflow guys, that's a sure way to lose those users.

**Comment by polarbearing** [comment]
With the recent fix bringing the save button down, the name of the favourite and the folder disappear (white font on white?), I have to edit them blindly when adding or editing one. If a word fragment is selected.
![screenshot_2016-07-13-22-48-35](https://cloud.githubusercontent.com/assets/8266355/16819605/7f06e48a-494d-11e6-81ed-e051b7de5b76.png)
