### ISSUE TITLE
Improve TTS documentation on website

### ISSUE THREAD

**Issue by keunes** [osmandapp/Osmand#2695]
As a follow-up from #2166 (adviced by @sonora to provide concrete suggestions):

For users that are lost with their (Dutch) TTS not working with OsmAnd, it would be nice to "a list of languages where you can test and select which actually works and some sentences to install other TTS engine for example" (@vshcherb's words)

Concrete, on http://osmand.net/help-online#tts_not_working:
- change "Evona" to "IVONA"
- provide links to the different TTS engines, as noob users (like I was) have no clue what TTS engines are, let alone how to install them:
 - https://play.google.com/store/apps/details?id=com.googlecode.eyesfree.espeak
 - https://play.google.com/store/apps/developer?id=IVONA+Text-to-Speech
 - https://play.google.com/store/apps/details?id=com.svox.classic
- Change the text
 - from:<br />"If you have issues with the TTS voice guidance, please check if you have a TTS engine compatible with the language in question installed on your Android device. It is known that many "smaller" languages are not supported by Google even though the number of languages is continuously growing. You can try to use some other TTS engine like SVOX, Evona or Espeak."
 - _to_ (something along the lines of; changes in italics):<br />"If you have issues with the TTS voice guidance, please check _both the settings within OsmAnd as well as the settings on your phone (Language > Speech). Then check_ if you have a TTS engine compatible with the language in question installed on your Android device. It is known that many "smaller" languages are not supported by Google even though the number of languages is continuously growing. You can try to use some other TTS engine like [SVOX](https://play.google.com/store/apps/details?id=com.svox.classic), [_IVONA_](https://play.google.com/store/apps/developer?id=IVONA+Text-to-Speech) or [Espeak](https://play.google.com/store/apps/details?id=com.googlecode.eyesfree.espeak)."

**Comment by vshcherb** [comment]
@sonora can you please it https://github.com/osmandapp/osmandapp.github.io?

**Comment by sonora** [comment]
Ok, thank you! I have completely re-worked the TTS section in our online help, and also merged the hints you provided. Please report here if there are any issues still.

**Comment by sonora** [comment]
PS: @vshcherb , @annasoloviova : Our online help page does not very nicely display unnumbered lists (`<ul><li>`), they are shown indented but without the bullet symbols). Maybe Anna can fix?

Best, Hardy

**Comment by vshcherb** [comment]
Nope Anna can't fix it. May be you forgot to use <ul class="textlist"> please check other lists

**Comment by keunes** [comment]
That seems actually informative. Thanks @sonora!

**Comment by sonora** [comment]
@keunes  My pleasure, thanks for pointing this out!
@vshcherb : I use  `<ul class="list">` like is used throughout faq.html.  When viewing a local copy of faq.html + style.css, it displays ok. Not sure why it does look different when viewing online from http://osmand.net/help-online, must be some style we overwrite on the server?
