### ISSUE TITLE
OSMAND data, maps and folder are not to find  on an Android 5.1.1. smartphone

### ISSUE THREAD

**Issue by MikeAle** [osmandapp/Osmand#2696]
I  have  now for one week the Redmi 3 Pro with Android 5.1.1 and MIUI  7.3.1.0. The installed OSMAND Plus works fine. Unfortunately  stored GPX tracks  cannot be find. I used Windows explorer, ESD File Explorer, Total commander, Android integrated data explorer w/o success. I searched for OSMAND folders but found only net.osmand.plus but this one was empty. I checked other apps and I found that for some apps the same problem exist too. Folder are not visible. Even data storage analyzer found only music data of 3MB  as the largest datas though themaps are much bigger.  I guess this is not a OSMAND problem but an Google problem!

**Comment by vshcherb** [comment]
Yes when you store in default folder (Google recommendation) all your data will be deleted once the app is deleted :( This is new Google way of handling app data.

If you use Shared Memory option, OsmAnd will ask permission to "Access photos" though it won't access photos it will just access sd card to store maps and tracks. Then this approach work flawlessly with reinstalling the app.

**Comment by MikeAle** [comment]
Thanx
