### ISSUE TITLE
Map differences between Osmand Repository and Osmand 2.3.5

### ISSUE THREAD

**Issue by FrancescoCellepathy** [osmandapp/Osmand#2697]
Hello,

Osmand Group Forum post: https://groups.google.com/forum/#!topic/osmand/ZbCKx_x_RwA

I noticed that there are differences between the Osmand map rendering of the  v.2.3.5 downloaded from google play and Osmand map rendering on Osmand v.2.4 build from the code from the repository. 

Besides the 'look&feel' of the map, on Osmand map build from the repository there are bugs that in the downloaded version are solved. 

For example: at high zoom levels the roads disappears in the Osmand from repository. (32.11609;34.79337) This LatLon is not the same as the screenshots but in that point you can see the same problem.

OSMand from repository:
![screenshot_2016-06-14-08-13-05](https://cloud.githubusercontent.com/assets/17949928/16036798/c791ce64-321d-11e6-8a2d-a15b09248e4f.png)
![screenshot_2016-06-14-08-14-02](https://cloud.githubusercontent.com/assets/17949928/16036796/c790e7ba-321d-11e6-9ea5-f7cd13ba2e36.png)

OSMand 2.3.5
![screenshot_2016-06-14-10-33-03](https://cloud.githubusercontent.com/assets/17949928/16036795/c7909e18-321d-11e6-8876-6cb2c9137fe8.png)
![screenshot_2016-06-14-10-33-12](https://cloud.githubusercontent.com/assets/17949928/16036797/c791c478-321d-11e6-9ca8-45ecbd47bccc.png)

Somebody can help?

Thank you in advance.

**Comment by vshcherb** [comment]
Probably it doesn't run native library and uses old java rendering.

**Comment by FrancescoCellepathy** [comment]
How to correct it?

**Comment by rwoloszyn** [comment]
I get the same problem when building from main. Any additional configuration is needed ? @vshcherb 
you mentioned about native library, what I need to configure to use it ?


![ezgif com-crop](https://cloud.githubusercontent.com/assets/1964439/16071967/8ddfc7b8-32de-11e6-848d-2d7c8daf4a8d.gif)

**Comment by vshcherb** [comment]
You can compile it but I don't advise of doing it if you didn't do it before . Just download latest night build and copy native libraries to libs folder.

**Comment by rwoloszyn** [comment]
@vshcherb do I need to change any configuration when building Osmand ? Which flavour should be selected to use native library or it's done by default ?
