### ISSUE TITLE
Audio notes moved to sd card by OsmAnd lose timestamp

### ISSUE THREAD

**Issue by jose1711** [osmandapp/OsmAnd#2698]
when osmand detects inserted sd card and user confirms to move data to it, *amr files are moved without modification timestamps. this makes later processing in JOSM very cumbersome (still possible though). it would be nice if this information is preserved

**Comment by vshcherb** [comment]
Not clear what OsmAnd can do in order to avoid this issue.

**Comment by jose1711** [comment]
doesn't java provide an api to make a copy of filetree while preserving modification times (something like cp -p in unix/linux world)?

**Comment by vshcherb** [comment]
Yes it provides everything is possible, though GPX tracks itself have plenty of timestamps, so it is possible to recover such information

**Comment by jose1711** [comment]
just to be sure we're on the same page. gpx files are not an issue, audionotes are:

    -rwxrwx--- 1 jose users  30650 May 19 23:59 0LBKPlXN--.1.3gp
    -rwxrwx--- 1 jose users  14964 May 19 23:59 0LBKPwIB--.1.3gp
    -rwxrwx--- 1 jose users  44954 May 19 23:59 0LBKPwI5--.1.3gp

sure, i can still determine their location from filename but order at which the points were recorded is lost (since gpx file does not contain reference to them).

**Comment by mnalis** [comment]
nowdays `.gpx` files produced by OsmAnd do have reference to `.3gp` files, so this can be closed
