### ISSUE TITLE
Add navigation pause/resume/simulate functionality 

### ISSUE THREAD

**Issue by fho** [osmandapp/Osmand#2699]
Add the functionality to pause and resume navigation.

When I'm doing longer trips, I often make breaks in between or get of the road to visit something and then return.
Currently there are 2 options to handle it in OSMand:
- continue the navigation, this means you will get nonstop announcements regardings the route, OSMand recalculates the route nonstop and drains the phone's battery
- stop the navigation, when you want to continue it you have to setup the whole navigation again, which can be cumbersome

I think it would be handy to be able to pause the navigation instead

**Comment by homersimpsons** [comment]
In Dashboard I've got this option (there is a pause button at the right of current route) just at the left of cancel button.

**Comment by fho** [comment]
Thanks, I found it! 
I was searching for it in the navigation view, which is I think a more intuitive position for it. Everything else regarding navigation your also can configure and control there. 
Would it make sense to also include or move the pause button to the  navigation view? 
It could make it easier to find it for everybody :)

**Comment by homersimpsons** [comment]
I think that Osmand Devs will allow to custom shortcut for some menu, then maybe they will implement this for navigation view.

**Comment by vshcherb** [comment]
It is already possible on the dashboard we plan it for 2.6 make it easier in new UI.
