### ISSUE TITLE
import poi file does not work

### ISSUE THREAD

**Issue by promeneur** [osmandapp/Osmand#2703]
What version of OsmAnd are you using, on what device and Android/iOS version?
samsung galaxy s2 plus
android 4.2.2
osmand 2.3.5

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?
offline maps

the last year i imported camp_site poi gpx file to osmand by following the method
http://osmand.net/help-online?id=technical-articles#Using_KML_Files
with gpsbabel 1.5.1 and osmand map creator 1.8 4670M
no problem to displayed the camp_sites pois of my file in osmand

this day i updated my camp site poi file with gpsbabel 1.5.2 and osmand map creator 1.8 4670M
but i can't display the camp_sites pois

i investigated the pb 
then 
i see that last year gpsbabel produced an osm file with

<osm version='0.5' generator='GPSBabel-1.5.1'>

this year gpsbabel produces an osm file with

<osm version='0.6' generator='GPSBabel-1.5.2'>

then

i changed 0.6 by 0.5 and recomputed the obf file and this time the camp-site pois are displayed

**Comment by vshcherb** [comment]
Not all tags are supported for poi. You can use tag "user_defined_other" https://github.com/osmandapp/OsmAnd-resources/blob/master/poi/poi_types.xml#L2943 or any other supported tag.
