### ISSUE TITLE
no more separate settings for each profile!

### ISSUE THREAD

**Issue by promeneur** [osmandapp/Osmand#2704]
What version of OsmAnd are you using, on what device and Android/iOS version?
osmand 2.3.5
samsung galaxy s2 plus
android 4.2.2

if i set  for cars "poi activated" then for all other profiles "bike" and "foot" poi is activated
if i unactivate sound for bike then sound is unactivated for "car" and "foot"  etc.

it seems for that kind of settings in fact there is no setting for each profile but a global setting!

**Comment by homersimpsons** [comment]
Please check these 2 issue: https://github.com/osmandapp/Osmand/issues/2556 and https://github.com/osmandapp/Osmand/issues/2619 maybe your problem is already open.

**Comment by bjohas** [comment]
It's a different aspect of https://github.com/osmandapp/Osmand/issues/2619.

**Comment by vshcherb** [comment]
These settings are global and work as designed
