### ISSUE TITLE
Show Download in the context menu if the map is not available

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#2705]
To be able to download the map after search, we need to add an option to the context menu to download the region.
Option should be available as a row in all context menu if context menu location is not present in any downloaded map.

**Comment by crimean** [comment]
Which search and where exactly it should be added?

**Comment by crimean** [comment]
https://www.dropbox.com/s/jvw9s9gwbfojjpn/Map_Download-4.png?dl=0
