### ISSUE TITLE
Force Close with latest nightlies

### ISSUE THREAD

**Issue by CJTmmr** [osmandapp/Osmand#2707]
On Samsung Galaxy Camera 2; Android 4.3
Osmand+ installed on SD-card; with map-location on storage/ExtSdCard/osmand

After installing latest nightlies from yesterday-evening/night:
OsmAnd starts up and crashes before showing the map.
Short toast: "==null=="

It appears the file "poi_types.xml" has a size of 0 bytes..
Deleting this file, and restart has no effect.

After re-install of nightly from 14-06: also crash..
Deleting poi_types.xml and restart, made this one work okay again.

Installing latest-nightly, then using a copy op poi_type.xml from 14.06: also crash, 
with toast: "corrupted file - is should end as it started"

See [exception.log](https://www.dropbox.com/s/6157vb15d6io4w1/exception%202016-06-15.log?dl=0) with several crashes since last night...

**Comment by vshcherb** [comment]
This is a corrupted installation. You need to install a new build.

**Comment by polarbearing** [comment]
Confirming the crashes in the June-15 version, no rendering. However the toast "==null==" was there for a while.

**Comment by polarbearing** [comment]
OsmAnd-master-nb-2016-06-16.apk (16-Jun-2016 01:07) # 17143 as the latest nightly still crashes:
```
Apk Version : 2.4.0#17143M 231
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalStateException: java.lang.IllegalArgumentException
	at net.osmand.router.RoutingConfiguration.getDefault(RoutingConfiguration.java:171)
...
Caused by: java.lang.IllegalArgumentException
	at org.kxml2.io.KXmlParser.setInput(KXmlParser.java:1615)
...
```

**Comment by CJTmmr** [comment]
"install a new build"
Does that mean: wait for next nightly
or: delete existing install (with app-management) and do a fresh install with current nightly.?

In the last case we lose a lot of settings and preferences..
Thanks

**Comment by polarbearing** [comment]
* 16-Jun-2016 around 15h (2.4.0#17144M) crashed, poi_types.xml and regions.ocbf were empty.
* reverted to 10-Jun-2016 which I knew it worked, and it did again
* 16-Jun-2016 17:29 # 17145 works again (without any need to deinstall)

The .apk file is back to 50MB, which was only 46MB for the broken builds, so I guess something was incomplete.

**Comment by vshcherb** [comment]
Right, we also discovered it but fixed only now. It was yesterday pull-request broken. Sorry for inconvenience.
