### ISSUE TITLE
Land disappears in 14, 15 zoom level

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#2708]
Land disappears in 14, 15 zoom level.
Riekkalansaari Island in Russia, Karelia.
61.66685, 30.75986

**Comment by vshcherb** [comment]
Here as well can we please small map containing just this object and check via obf2osm. Once we have these artifacts it will be easier to go further

**Comment by xmd5a2** [comment]
Fixed by removing unnecessary natural=coastline from OSM
