### ISSUE TITLE
stray waterway all across Bavaria (and possibly Austria)

### ISSUE THREAD

**Issue by RicoZ-OSM** [osmandapp/Osmand#2710]
Downloaded a map of Bavaria yesterday, there is a mysterious waterway starting near http://osmand.net/go?lat=49.93193&lon=10.864509&z=22 and going all across Bavaria (btw of airport Munich) all the way to the border near Kiefersfelden.

The mystery stream was there already in the May edition and it was not in the main OSM database when I checked in May and it is not there now.

**Comment by pebogufi** [comment]
could you please provide a screenshot ?

**Comment by RicoZ-OSM** [comment]
where it starts
![image463115676](https://cloud.githubusercontent.com/assets/6632966/16176633/7e99ed8c-3613-11e6-8f46-98392a43b11f.jpg)

overview where it starts
![image-377148412](https://cloud.githubusercontent.com/assets/6632966/16176638/ac1d1766-3613-11e6-8b3b-a23c6bcbbfdf.jpg)

going through airport Munich
![image-966862536](https://cloud.githubusercontent.com/assets/6632966/16176646/caa10d78-3613-11e6-8ca4-1f20e2515a4a.jpg)

My Bavaria map says 811.3 MB Jun 1, 2016

**Comment by quelbs** [comment]
On my devices I have similar problems. I also have streets crossing Munich that are not present in OSM database. They start west of Munich and go beyond the German-Austrian border. There they continue normally as in the OSM Data and cross the border back to Germany. I currently only have a screenshot of the end next to Munich:
![screenshot_streets_munich](https://cloud.githubusercontent.com/assets/570222/16301113/cab776ca-3943-11e6-85e9-e683d51c7217.png)
The corresponding area in OSM:
https://www.openstreetmap.org/#map=15/48.1460/11.3833

**Comment by quelbs** [comment]
Two more screenshots of the other end:
![screenshot_2016-06-26-19-21-46](https://cloud.githubusercontent.com/assets/570222/16363750/ab298742-3bd4-11e6-8937-669f037c6ae9.png)
![screenshot_2016-06-26-19-23-12](https://cloud.githubusercontent.com/assets/570222/16363751/b88efa20-3bd4-11e6-8d5b-ca1be5d79b7b.png)

Position: geo:48.55255,13.463696

**Comment by xmd5a2** [comment]
Fixed. It was a problem with our planet.osm update process.
