### ISSUE TITLE
Foot routing through entrance with access=private

### ISSUE THREAD

**Issue by utack** [osmandapp/Osmand#2711]
When using foot routing, Osmand ignores [a node](https://www.openstreetmap.org/node/4158575464) with  
entrance=service  
access=private  
that is on the way  
I hope it does not cost too much performance to add this  
Thanks

**Comment by scaidermern** [comment]
access=private means that your are not allowed to enter this entrance (except for rare circumstances). I don't see a bug here. OsmAnd has to respect access tags, otherwise routing becomes useless.

**Comment by utack** [comment]
I see it the same way, but it routes through this node and ignores the access tag at the moment

**Comment by scaidermern** [comment]
Oh, then I got it wrong. Of course it should not ignore the access tag and stop routing through it.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-resources/commit/0312dfe33b8ce1e8dc6fb92ea98260973f5e01f2

**Comment by utack** [comment]
Thanks for the quick fix on this

**Comment by utack** [comment]
Thanks for the quick fix on this
