### ISSUE TITLE
Option for modifying filters is hard to find

### ISSUE THREAD

**Issue by fho** [osmandapp/Osmand#2712]
Make it easier to modify existing filters.
The option to modify a filter is currently hard to find and requires several steps:

- Go to POI View (Search/Configure Map)
- Choose existent filter
- Funnel Button 
- Edit

A more user-friendly way to modifying filters could be:
- When you tap an existing filter for >X seconds, in the POI view, a dialogue pop-ups where you can choose e.g.:
- modify filter
- rename filter
- delete filter

**Comment by vshcherb** [comment]
Thank you for your input. It will be considered in a redesign.
