### ISSUE TITLE
[Feature request] Adding arrows to GPX track

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#2715]
The iOS version has arrows showing the direction of the track. The request is to add them in the Android verion also.
![android](https://cloud.githubusercontent.com/assets/12711814/16148743/465d17d0-3494-11e6-8154-a6190127c6cf.jpg)
![ios](https://cloud.githubusercontent.com/assets/12711814/16148742/465a27fa-3494-11e6-9bd0-9a210a722f43.jpg)

**Comment by vshcherb** [comment]
We will have it soon with new engine

**Comment by jensMF** [comment]
Is this feature implemented? If yes, how can I enable it, if not, will it be implemented?

**Comment by vshcherb** [comment]
That feature was implemented though later we've changed a rendering engine to have more robust display, so now it is missing again. Yes it is planned in this year roadmap
