### ISSUE TITLE
name of towns displayed in wrong language depending on zoomlevel

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#2717]
Since some weeks the name of towns or villages is displayed in wrong language depending on zoomlevel.
It is OK in zoomlevel >= 12, local names
it WRONG in zoomlevel <= 11, the names are displayed in user-language (for me it is german) instead of local names (french) (which is selected in settings).
It looks like a problem of world_basemap.obf, which is used in this zommlevels, regional maps are ok.

The problem is easy to see in france-alsace which was german in former times and has a lot of towns and villages with old german names and of course french names.
Example  
addr:postcode=67210
name:de=Oberehnheim
name=Obernai
place=town
...

world_basemap.obf Date=16-06-13, same problem in older version.

osmand 2.4.0#17146M
android 5.1.1
device samsung S5 Neo (SM-G903F)

Regards Peter

**Comment by vshcherb** [comment]
If you see name:de=Oberehnheim, then your device language is German, you can change it in OsmAnd as well. For world base map we display device language name. If it is an old german name than I guess it is wrongly mapped and should be old_name:de

**Comment by sonora** [comment]
@pebogufi : I had stumbled about this, too. But I guess it makes sense, the point is this: If you use the setting "local names", this makes sense for most users in their regional context. But if you zoom way out to a more global level, it would produce a mixture of city names in all foreign type writing, like Chinese, Arabic, etc., which is probably less useful.

**Comment by pebogufi** [comment]
Thanks to both of you for your explanation. I understand your arguments, but I am not happy with the situation. These historic names in the map are irritating.
But I have to open a discusion in the german forum to change the name:de in old_name:de.
Regards Peter

**Comment by vshcherb** [comment]
Well we have discussion to display always name:en on the basemap but then took a look around and it turned out that major cities have good translation in many languages.
