### ISSUE TITLE
The psychological hazard of GREEN turn indicators

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#2719]
_You're approaching the junction, one of your eyes takes a glimpse of the navigation screen. The "turn left" arrow just changes from yellow to green. Wow, green for turning left, some neurons recognise the green light and fire -- they are connected to the muscles [1] pushing the accelerator down._

_Wait!!! shouts the Cerebrum [2]. This is just the navigation screen, the traffic lights are still red! Stop!_

Honestly, I had the temptation to drive on a couple of times while checking the _turn_ or _turn:lane_ indicators, and seeing the yellow-green transition. In the nightlies a few weeks ago, the indicators changed from yellow to orange, and I liked that a lot more. Any other colour would also do (blue for example), except green. 

---

The [Cerebellum](https://en.wikipedia.org/wiki/Cerebellum) ("little brain") is responsible for sub-concious planning and trained motion patterns. Responding to traffic lights is certainly such a trained pattern.
In the [Cerebrum](https://simple.wikipedia.org/wiki/Cerebrum) ("major brain"), the concious actions are planned, judged and performed.

**Comment by sonora** [comment]
So by your very theory shades of orange/red must also be avoided, as this would cause you subconsciously slam in the break when you see that transition, right?

I any case, we must keep the colors for where you go and where you do not go in sync for both the lane selection widget and the turn indication widget. And anything "reddish" conventionally (subconsciously?  :)  ) signals a restriction, like "do not take that lane" (or road).

Looking at the market: Garmin uses green arrows and turn-road background all along, and TomTom uses flashing green on-road arrows for e.g. turn lane selection...

Some blue could be an option, but would be rather unconventional from what I see.... I vote for not changing unless we get more definite feedback from more users.

**Comment by polarbearing** [comment]
> shades of orange/red

No I think the orange we had temporarily in the nightlies was distinct enough from the signal-red of a traffic light. Also stopping unnecessarily is less dangerous than accelerating when not allowed.

> we must keep the colors ... in sync for both the lane selection widget and the turn indication

Yes absolutely, I think I said that above as well. Happy enough to collect more opinions here.

**Comment by vshcherb** [comment]
It would be to organize a poll at some moment from my vote collection green is better because it means safety. Everything big red on screen attracts attention even if you don't want to see it now. So we use red signs when you exceed a limit to attract attention

**Comment by sonora** [comment]
Looks like no action is planned here.

**Comment by polarbearing** [comment]
Appreciate @sonora tidying up. Still liked the orange more ;)

**Comment by sonora** [comment]
Yes, thanks for the flowers :) But I do think it creates value for all of us to tidy up and focus on the issues which seem to have significant resonance or value-add. I still see a point in you raising this issue, but somehow it did not make the cut by these standards for now (does mot necessarily mean it is forgotten ;) )
