### ISSUE TITLE
Bug with reference's boxes

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#2720]
OsmAnd 2.4.0#13267D on BQ 5.7 (Android). Offline maps (Spain-Europe - 01/06/2016)

Sometimes Boxes with road's references are not shown properly (I think it depends on zoom level).
![a66 a](https://cloud.githubusercontent.com/assets/12786225/16174047/a665bbf8-35b3-11e6-8df5-224b6a381d18.png)
![a66 b](https://cloud.githubusercontent.com/assets/12786225/16174049/ac5b5766-35b3-11e6-9daf-dc667d0dbaba.png)
The same point of this highway is shown with a blue box or a white box depending on zoom level.

![601](https://cloud.githubusercontent.com/assets/12786225/16174063/2ae50ce4-35b4-11e6-9755-093e2ad6fa60.png)
M-601 has highway=Trunk's tag but is shown with a white box on some sections and with a orange box on other sections.     The same with M-607

**Comment by vshcherb** [comment]
It depends on many cases. Most likely the relations route=.. needs to be checked

**Comment by xmd5a2** [comment]
Spain seems to have random colours for road shields which does not corresponds to prefixes or road class
https://en.wikipedia.org/wiki/Highways_in_Spain
We do support tag ref:colour but this way https://openstreetmap.org/way/323157147 (and many others) does not contain it.
This way has ref:colour tag https://www.openstreetmap.org/way/375012371 and his shield is rendered as orange box.
In short: insufficient data in OSM.
