### ISSUE TITLE
Trip recording (plugin) - add "Stop and Save"

### ISSUE THREAD

**Issue by bjohas** [osmandapp/Osmand#2721]
For the Trip recording (plugin), would it be possible to add an additional option "Stop GPS logging and save current track"? (I usually find myself first "stopping" and then "saving", i.e. extra taps.)

**Comment by homersimpsons** [comment]
I think this is a duplicate of #2641

**Comment by bjohas** [comment]
Ah yes - or at least a duplicate of one suggestion in https://github.com/osmandapp/Osmand/issues/2641.
