### ISSUE TITLE
The Netherlands (1.6.2016): Search street in neighborhood cities

### ISSUE THREAD

**Issue by CJTmmr** [osmandapp/Osmand#2728]
Using latest nightly, with the new (merged??) complete map for The Netherlands (1.6.2016, 1552.1 MB).

Adress Search.
Seach streetname.
"Search street in neighborhood cities" only finds streets in city and town (which are already pre-listed in city-search) 
No streets are found in villages/hamlets.

(But Village/Hamlet is still found while typing inCITY-field)

**Comment by vshcherb** [comment]
There were some issues could you please redownload the map (yes, it has the same timestamp, delete and redownload). 

And please, please, specify examples in the issue, so it is easier to rediscover it.
