### ISSUE TITLE
Position menu sliding in after highlighting POI search results

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#2733]
- Go to Search/POI
- Search for any POIs
- Click the button to highlight the search results on the map

Note that a position menu slides in with details of the _current_ GPS position. This does not make sense and should therefore not happen.

Builds: OsmAnd+ 2.3.5 and OsmAndF~2.4.0#13267D
Devices: Samsung Galaxy Note 4 and Huawei Y625

**Comment by vshcherb** [comment]
Agree. Perfectly spotted.
