### ISSUE TITLE
Map stops rotating in Compass mode if a route is defined.

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2735]
Actually this is a update of issue  #2355: Earlier the map stopped rotating randomly when in **Compass** mode.

But now the map stops rotating when I set up a route.

Even if a route is defined, the map should not stop rotating in **Compass** mode.

OsmAnd~2.3.0#16193M, 
**Mobile:** OnePlus 2 
**OS:** OxygenOS 3.0.2 (based on Android Marshmallow 6.0.1).

**Comment by vshcherb** [comment]
It is by design.

**Comment by raindropsfromsky** [comment]
What is the benefit of stopping the alignment of the map with the surrounding once a route is set?

In fact, it stops matching with the surrounding area, (because the user will start driving immediately, and so he cannot use the "To the direction of movement" mode)
 
The different modes (North, Compass, Follow movement) should continue working in their respective ways.

**Comment by raindropsfromsky** [comment]
HI Viktor,

The clinching argument is that the compass mode works as soon as we press **Go**, and the phone switches to **Navigation** mode.

So why lock the rotation when the phone is NOT in the **Navigation** mode??

I hope this bug is re-opened and resolved.

**Comment by vshcherb** [comment]
I'm not sure if rotation is locked, we always display routes in the North up mode, it is convenient to users

**Comment by raindropsfromsky** [comment]
That's fine. Indeed, while identifying the start/destination points by selecting on the map, I find "North up" mode more convenient, because I can select the point quicker from memory.

But once the route is set, then it should be swing around to match the surrounding area.

Even if the default mode is "North up", it should be possible to change the mode. **But I am unable to change the mode. [BUG]**

**Comment by Zahnstocher** [comment]
> That's fine. Indeed, while identifying the start/destination points by selecting on the map, I find "North up" mode more convenient, because I can select the point quicker from memory.

> But once the route is set, then it should swing around to match the surrounding area.
> 
> Even if the default mode is "North up", it should be possible to change the mode. **But I am unable to change the mode. [BUG]**

Yes, I agree.
This is an annoying change.
I often set a destination and let OsmAnd calculate a route on the fly, without actually start the navigation.
This is a nice feature, for example to know, how far I could go away to get back in time.
But without rotation, this is not useful in many situations.

@vshcherb 
Please let the user decide, if the map rotates or not!
It is ok for me to show the route in North up mode by default, but please let the user switch the rotation mode and don't lock it.

**Comment by vshcherb** [comment]
@Zahnstocher If you touch the map you can rotate it as normal screen. After route calculation it changes rotation, zoom to fit it into the screen, it is not much about user preference it is how the screen is designed. And we don't provide any map interaction control in that context.

**Comment by Zahnstocher** [comment]
> And we don't provide any map interaction control in that context.

@vshcherb 
But zoom, follow position and manual two finger rotation does work.
Why not make it possible to toggle the rotation mode, actually this seems the only thing which is locked...

**Comment by vshcherb** [comment]
It doesn't, after touch it goes to another mode where toggle is enabled. Please provide screenshot

**Comment by raindropsfromsky** [comment]
Viktor, 

A screenshot is not warranted for this. Probably I was not clear about the actual issue. Let me paraphrase it:

1. You can tap on the **Map orientation** button to cycle between North up/compass/direction modes 
2. This button stops functioning as soon as you define a route.
3. When we press the **blue arrowhead** (Go) button, the **Map orientation** button starts working again. 

So, the problem is, in state#2, why does the button not work?

If the map switches automatically to "North up" mode after we set a route, that's fine.
But the **Map orientation** button should not stop functioning.

**Comment by Zahnstocher** [comment]
> If the map switches automatically to "North up" mode after we set a route, that's fine.
But the Map orientation button should not stop functioning.

I fully agree.
I don't understand, why you don't want the user to have the choice to turn rotation on again also in planning mode, if the user explicitly requests it by tapping on the compass icon.
