### ISSUE TITLE
Bug: Avoid road in routing doesn't work

### ISSUE THREAD

**Issue by hvdwolf** [osmandapp/Osmand#2738]
OsmAnd 2.3.5, Samsung S5 mini, Android 5.1.1
Using OsmAnd's own routing algorithm for car and bicycle on latest offline June maps.

2 Scenarios:  first with roads_only maps, second with full maps.

= roads_only maps: 
When I have calculated a route and long-press the map on a certain road and select the "avoid road"  from the context menu, OsmAnd crashes. Always, on multiple roads and on multiple routes. For car and bicycle route calculation.

= full maps (3 different regional maps from the Netherlands)
When I have calculated a route and long-press the map on a certain road and select the "avoid road"  from the context menu, OsmAnd recalculates the original road without blocking the road and leading me over another road. Always, on multiple roads and on multiple routes. For car and bicycle route calculation.

**Comment by Norbert80** [comment]
I experience crashes with German Baden-Württemberg full map during bicycle navigation. On a certain road I have tried to avoid during a bicycle tour OsmAnd crashed on every try.

**Comment by vshcherb** [comment]
Unfortunately can't confirm at all. There are possible glitches that it doesn't select exact road. If you can share a video with start lat/lon and end lat/lon within Netherlands Noord Holland for example, it will be great. I will be happy to pick up and fix it.

**Comment by Norbert80** [comment]
As far as I remember the crashes where not triggered by the recalculation but immediately when starting to follow the new route (with avoided road).

So I don't know how I could help you to reproduce this problem. Let me know if you plan to go to germany... ;-)

**Comment by CJTmmr** [comment]
Please check [this video](https://www.dropbox.com/s/20ft1rllagcqkrm/OsmAnd%20Avoid%20Road%20example.mp4?dl=0)

Using MAP: Netherlands Zuid Holland 01-06-2016; with live updates enabled
with nightly from yesterday : OsmAndF~2.4#13267D
[This route](http://www.openstreetmap.org/directions?engine=osrm_car&route=52.0913%2C4.7349%3B52.1503%2C4.7818#map=13/52.1198/4.7550)

My experience: sometimes is works okay, sometimes crash (I did sent several crash-reports in the last weeks). This is a recent [exception.log](https://www.dropbox.com/s/10fw1kqmhp08uxh/exception%202016-06-22%20Avoid%20Road.log?dl=0) with problems in ImpasseleRoadsLayer.

**Comment by hvdwolf** [comment]
@Victor: Please don't close a bug report because you can't reproduce it. If many users can reproduce it is certainly a bug. 
This is like a helpdesk saying: "It works for me so there is nothing wrong". 
What do you want us to do: Open a new bug report (and again and again) until you confirm it is indeed a bug?

**Comment by victor** [comment]
Please @-mention the right Victor.
Thanks

**Comment by vshcherb** [comment]
No luck, https://photos.google.com/share/AF1QipNZsCqQzWiZbeG4Hn8cPZRA1PHck1n8rGuxjMfMyUuQPc6bzAXvd5GD8Ts1sVhXYw?key=ZzgwNkJqLUFPZkEwN29sU3FXLXQ5UVMzdU1nYXJn. 
@hvdwolf Yes I would like to have a new bug which I or somebody from developer can reproduce, if it appears to be a mass problem, sometimes I reopen bugs and fix them. If not a mass problem or an old release or weird data, then it is better to have it closed. I track all comments anyway.

**Comment by pebogufi** [comment]
I think I understand the reason of the problem: I have a routing.xml which I downloaded seconds before the test with only this change (
<osmand_routing_config defaultProfile="car">
...
	<attribute name="heuristicCoefficient" value="1.35" />
) 
If I remove the routing.xml from the directory (...net.osmand.plus\files) , everything works as expected, at the position of the blocked road i see a traffic sign for construction, the part of the road is avoided.
If move the routing.xml back to the directory, there will be no traffic sign, and no avoiding.
@hvdwolf: I know, you like the routing.xml as I do, would you please be so kind to verify that?
Regards Peter

**Comment by CJTmmr** [comment]
Sorry - No luck indeed.
Please check [this video](https://www.dropbox.com/s/vxs8y2jq7d7nbgg/OsmAnd%20Avoid%20Road%20Crash.mp4?dl=0)
made this afternoon. 
Resulting in[this exception.log](https://www.dropbox.com/s/zv05srjddibl9si/exception%202016-06-24%20Avoid.log?dl=0)

I set a Avoid Road, route was recalculated, avoiding this location, but no avoid-road-icon appeared.
As soon as I tried to move the map a bit - crash: and restart of OsmAnd

Made on Samsung Galaxy Camera2; Android 4.3
OsmAnd nightly from yesterday-evening 13296D
MAP: Netherlands[complete] (fresh download from yesterday evening, date 2016-06-01)
OsmAnd-map om SD-card: /storage/extSdCard/osmand.
No Live Maps present. No routing.xml 
I cleared cache, deleted ind.cache, regions.ocbf, poi_types.xml for fresh indices


**UPDATE**: I just now tried again and Avoid Road works perfect. Both with Netherlands-maps as Netherlands-Zuid-Holland-map.....
No setting were changed in the meanwhile (expect de-activating/activating some maps)
Ideas?

**Comment by vshcherb** [comment]
Hm... Have no ideas, though it is very-very strange. We will be watching other reports and may be find a root cause
