### ISSUE TITLE
Build number display is broken

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2739]
It looks like ever since this commit https://github.com/osmandapp/Osmand/commit/b050670e36eb8eee45fe3fbb29559043857168a7
the build version counter which we pass to our nightly apks in Jenkins via export APK_VERSION_SUFFIX=#${BUILD_NUMBER}XXX ceased to increase.

Somehow we have an issue with our resource assignment, it seems. Build version for e.g. master builds is ever since frozen at number 17146M, so master build 17147 seems to be the first suffering from this issue.

**Comment by vshcherb** [comment]
Yes the issue is in this commit https://github.com/osmandapp/Osmand/commit/b050670e36eb8eee45fe3fbb29559043857168a7 fixed added cleanNoTranslate task to each build in jenkins
