### ISSUE TITLE
Search > Location, add formats: "DDD.DD,DDD.DD" and Open Location Code

### ISSUE THREAD

**Issue by bjohas** [osmandapp/Osmand#2740]
Under "Search > Location > Format", it would be good to add "DDD.DD,DDD.DD", so that numbers in that format can be entered. It works for example on google maps, and often coordinates are given like that. I've found that I have a coordinate "DDD.DD,DDD.DD" on the clipboard, and then need to split it, to fit into the dual "DDD.DD" boxes.

The second format I'd like to suggest is the "Open Location Code", a relatively recently developed "postcode-like" encoding for coordinates, see http://openlocationcode.com/. I guess the format isn't widely used, but it was developed by Google Zurich, and Google Maps does support it. The code to go to/from Open Location Code is available here https://github.com/google/open-location-code/tree/master/js/src and is easy to adapt. In my opinion, it would be good to support.

**Comment by vshcherb** [comment]
It is in our plan

**Comment by sonora** [comment]
Closing this, should be implemented.
