### ISSUE TITLE
Updating french "GPS signal lost/restored"

### ISSUE THREAD

**Issue by breversa** [osmandapp/Osmand#2741]
Hi,

The french TTS voice for GPS signal lost/restored is a bit flaky : for lost signal, the voice says "Signal GP S restauré", with a noticeable pause between "P" and "S" which sounds very awkward.

Also, GPS is only one of several positionning systems, along with GLONASS, Beidou, Galileo (in the future), and also an indian one whose names escapes me at the moment, so speaking about "GPS signal" may well be milsleading or inaccurate. GPS is NOT a synonym with "satellite positionning". It's merely one of several systems

I hence suggest rephrasing to :
* "Satellite positionning lost" (fr : "Position/localisation/emplacement par satellite perdue")
* "Satellite positionning restored" (fr : "Position par satellite retrouvée")

Also, what about the future, when precise location (as opposed to Android's "coarse location") will be accessible via extensive wifi/Bluetooth mapping and won't require satellites ? Why not go even further and rephrase to :
* "Position lost" (fr : "Position perdue")
* "Position restored" (fr : "Position retrouvée")

**Comment by sonora** [comment]
Pronunciation and intonation, like breaks between words or letters, are very much dependent on the device, respectively the TTs engine you are using.

But I have adopted the shortest of your wording suggestions for the French voice hoping t not introduce too much ambiguity of what is meant by the prompt, Let's test end see what others think.

Needless to say, in English "GPS" is a rather well known acronym of how electronic positioning is achieved, while many other synonyms or generalizations may cause many question marks.

**Comment by breversa** [comment]
@sonora :
What I forgot to mention was that "Signal **GPS** perdu" (= lost) is pronounced perfectly fine. It's only for "Signal **GP S** restauré" that there's a noticeable pause. I believe it's a typo in the text-to-speech process somewhere…

> But I have adopted the shortest of your wording suggestions for the French voice hoping t not introduce too much ambiguity of what is meant by the prompt, Let's test end see what others think.

That means you went for "Position perdue" and "Position retrouvée" ? That's great, thanks !

**Comment by sonora** [comment]
"No", and "Yes". :) See here: https://github.com/osmandapp/OsmAnd-resources/commit/c480ac3aadb024e8c63d69035ea715f1471173ff
"No" for there was no typo, I guess it was a peculiarity of the specific TTS engine you are using. And yes, I went witj the new suggestions, let's see how other users feel about it.

Best, Hardy
