### ISSUE TITLE
Impossible to delete & swap Start Point in Waypoints

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#2742]
There are several issues with setting start point:
1) When route is calculated it is impossible to choose "Directions From" from context menu
Calculated route -> Flag (Waypoints)
2) If Starting point is not "My location" and there are other interemediate points, it is still impossible to delete start point (neither swipe, niether menu)
3) If Starting point is not "My location", it is impossible to Move Down it or Move Up first intermediate point.

All these cases should be possible

**Comment by crimean** [comment]
Fixed first case. For 2-3 need UI
