### ISSUE TITLE
New roundabout navigation looks weird on 4th exit

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#2745]
2.4.0#17177M 231 OsmAnd-master-nb-2016-06-23.apk (morning) / screenshots in live traffic

The roundabout drawing looks weird when it recommends the 4th exit, like bouncing off the middle.
3rd exit looks better, but misses the fact that the roundabout has 5 arms. The recommended exit number is correct. Maybe you draw the arrow with an angel >360 deg?

![screenshot_2016-06-23-16-32-18](https://cloud.githubusercontent.com/assets/8266355/16322723/7ee37980-39a5-11e6-87c9-07bbd072f190.png)
![screenshot_2016-06-23-16-44-06](https://cloud.githubusercontent.com/assets/8266355/16322727/8a315ba4-39a5-11e6-8db4-311650c73f86.png)

Situation shown is [this roundabout](http://www.openstreetmap.org/?mlat=52.51262&mlon=13.32193#map=18/52.51262/13.32193), routing towards Bismarckstr, coming from Hardenbergstr in the first and from Std.d.17. Juni in the second case. 

Another issue is this recommendation for the 1st exit, which in reality is about 90 degrees to the right, shown as going straight over. The junction also has 5 arms as the previous roundabout.
![screenshot_2016-06-23-22-49-31](https://cloud.githubusercontent.com/assets/8266355/16322867/934a659a-39a6-11e6-89e7-771cd33b13c6.png)

Situation is on [Großer Stern](http://www.openstreetmap.org/?mlat=52.51404&mlon=13.34947#map=18/52.51405/13.34947), but not suitable for a long-term test since I had to remove the junction=roundabout today since the ring traffic has no priority.

Also examples of the misplaced zoom button (#2638).

**Comment by sonora** [comment]
Additional related issue: The roundabout appearance in the small (e.g. next_next) widgets is inferior to what it used to be, mostly because the strokewidth of the black fringe lines are too thick compared with the fine structure. I guess it should be chosen significantly thinner in all (also the large) widgets.
![day](https://cloud.githubusercontent.com/assets/845735/16331021/889b3c7c-39ed-11e6-83ac-3b3f19a8b4f5.png) ![night](https://cloud.githubusercontent.com/assets/845735/16331025/8d501fda-39ed-11e6-8166-99dc5e054729.png)

**Comment by vrtareg** [comment]
I have noticed this today.
Latest nightly.

**Comment by polarbearing** [comment]
Have another case [here](http://www.openstreetmap.org/?mlat=52.39168&mlon=13.82578#map=18/52.39168/13.82578). OsmAnd telling me to make a U-turn, cause it loves the motorway so much. 
Roundabout is classical 4-arm, rectangular exits. Anyway, the circle should be filled to take the same exit I came in, not empty:

![screenshot_2016-06-30-11-50-43](https://cloud.githubusercontent.com/assets/8266355/16569881/4f858ddc-423c-11e6-8a6c-ea2c4e784b88.png)

**Comment by polarbearing** [comment]
Thanks, we are getting better with non-U-turns. However when I have to go back to the road I came from, the angle is inconsistent. Simulations in NB 06-Aug-2016 23:30.

First test: [Here again](http://www.openstreetmap.org/?mlat=52.51262&mlon=13.32193#map=18/52.51262/13.32193), coming from / returning to Hardenbergstr, the exit count it correct (5) but the angle is shooting to the first exit.
![screenshot_2016-08-07-00-16-18](https://cloud.githubusercontent.com/assets/8266355/17459431/85cc1e0a-5c37-11e6-96b7-317f4bc8ab49.png)

Second test: [Here again](http://www.openstreetmap.org/?mlat=52.39168&mlon=13.82578#map=18/52.39168/13.82578), the 4th exit (number shown correctly later) is correct, but the arrow pointing 45 deg too short. 

![screenshot_2016-08-07-00-20-56](https://cloud.githubusercontent.com/assets/8266355/17459437/e45a4abe-5c37-11e6-9fec-6c88d572c63a.png)

**Comment by vshcherb** [comment]
(1) Hardenbergstr was not supported feature of complex roundabout that consists of many ways. So it is displayed incorrectly (http://www.openstreetmap.org/way/25185006). 
(2) For 360 degrees roundabout  is displayed as designed.

**Comment by polarbearing** [comment]
Thanks a lot, both situations look much better now, in particular the unused exits are helpful!
![screenshot_2016-08-11-13-18-10](https://cloud.githubusercontent.com/assets/8266355/17587189/efba75f4-5fc6-11e6-996a-ffb05cc6bd9f.png)
![screenshot_2016-08-11-13-21-23](https://cloud.githubusercontent.com/assets/8266355/17587197/fa1b20de-5fc6-11e6-89b6-4a637423765c.png)
