### ISSUE TITLE
Make turn:lanes=merge_to_left the same as slight_left instead of straight arrow

### ISSUE THREAD

**Issue by cmeeren** [osmandapp/Osmand#2746]
Lanes marked as `merge_to_left` (e.g. short acceleration lanes where traffic enters the highway) are currently shown with a straight arrow in the lanes view. It would be better if the arrow was the same as `slight_left`. I expect it is similar for `merge_to_right` (untested).

I don't know how the lanes view is implemented, but I guess this is a very quick fix, right?

**Comment by vshcherb** [comment]
Do you have an example of these lanes?

**Comment by polarbearing** [comment]
They are quite common on motorways here.

In this example, 2 lanes are reduced to one: way https://www.openstreetmap.org/way/292532878
This is the classic acceleration lane: way https://www.openstreetmap.org/way/322543963

**Comment by vshcherb** [comment]
The issue is that OsmAnd doesn't interpret as an intersection, though it doesn't suggest to take any action. Though I fixed the icon itself and in case of any intersection (technically road split), road merges are not count as intersection, it will be displayed
