### ISSUE TITLE
Offline Routing: mysterious wrong routing in Leipzig, Germany

### ISSUE THREAD

**Issue by stephan75** [osmandapp/Osmand#2748]
According to this thread, we have a non-explainable wrong routing in Leipzig, Saxony, Germany:

https://groups.google.com/d/topic/osmand/cs_MQnzkYjo/discussion

Please read the mails to get needed map file and address to find that position.

AND:
Even with Osmand map creator  and the fresh OffRoad program on my PC, Osmand routing fails there for car, bike and foot routing.

Anyone can explain??

**Comment by polarbearing** [comment]
Confirming the issue in 2.4.0#17177 (23 June):
Car profile, Sachsen data 1 May 2016. I double-checked the data, also cannot see a reason why the segment of Richterstr is avoided. Data have not been changed recently, they date back to 2015 and earlier. Everyting is connected.
![screenshot_2016-06-24-22-30-45](https://cloud.githubusercontent.com/assets/8266355/16349941/d9336b32-3a5b-11e6-9801-f15c233de3f3.png)

**Comment by madprogger** [comment]
OsmAnd+ 2.3.5. Map "Germany Sachsen" is up to date as of 04.07.2016.
Looks like the intersection Richterstraße/Ehrensteinstraße is broken, it won't tell me to simply turn right. 
![screenshot_2016-07-04-16-27-25](https://cloud.githubusercontent.com/assets/9883575/16564198/790d5c10-4206-11e6-846e-447672986d23.png)
![screenshot_2016-07-04-16-27-09](https://cloud.githubusercontent.com/assets/9883575/16564199/791adbc4-4206-11e6-869c-640e917b55e1.png)

**Comment by polarbearing** [comment]
I don't think it is the intersection, it must be in the routing. I have a similar example which I watch for a while, screenshot is with 2.4.0#17177 (23 June). Location is [here](http://www.openstreetmap.org/?mlat=52.46709&mlon=13.69194#map=19/52.46709/13.69194). Destination is set to the junction of Eichenstr and Parkstr. 

When I come from the north via Eichenstr, the destination is hit directly. When I come from the east (Parkstr), the routing makes this extra loop, passing the destination, going around and hitting it from the south:

![screenshot_2016-06-23-23-34-22](https://cloud.githubusercontent.com/assets/8266355/16569825/98524a92-423b-11e6-8927-c759e51bb895.png)

**Comment by vshcherb** [comment]
Fixed

**Comment by madprogger** [comment]
fix confirmed: ![screenshot_2017-01-12-10-46-54](https://cloud.githubusercontent.com/assets/9883575/21884689/ac1a6c52-d8b4-11e6-8b5c-4cc920a4468e.png)
