### ISSUE TITLE
Feature request: traveler mode plugin

### ISSUE THREAD

**Issue by alexkmbk** [osmandapp/Osmand#2749]
When you travel for a long distance (especially with bicycle) you need to know where you can find some amenities along the road, such as:
hotels\motels\campings,
bus\train stations (long-distance tickets),
road cafes,
groceries shops,
water wells\springs\water taps.
Normally you don't need to see them, because in cities there are lots of them and usually it is better to see them only in the close view (as it is now).
But while travelling, it would be really useful to see those things enlarged, so, probably for this purposes it would be nice to have special mode in osmand, named probably "traveler mode" or something in main program or in external plugin (preferable).

**Comment by sonora** [comment]
Just do the following, I have this for all my different types of trips: Create and save a custom POI filter, adding to it all the amenities you are interested in (and perhaps naming it something like bike tour POIs or so). Then, whenever you want, go to search POI or to Configure map/POI and just select to show your custom filter on the map.

**Comment by RicoZ-OSM** [comment]
He was asking to see those POIs along his route. It might be interesting to see only POIs which are less than a certain distance away from the planned route?

**Comment by sonora** [comment]
Yes, you can also just select the ones near the route: Once the route is calculated, go to the route settings, tap the "Waypoint" button ()second one from the left at the bottom of the route settings, then chose your POI filter selection.
