### ISSUE TITLE
Not possible to turn on safe mode

### ISSUE THREAD

**Issue by krzysztofjanski** [osmandapp/Osmand#2755]
Hello,

I'm using up to date version of OsmAnd+ from play store.
When I check the "safe mode" box, the setting persists for some time or until I "force stop" the app in Settings->Applications. After consecutive application start, the "safe mode" checkbox is empty.

**Comment by sonora** [comment]
I think this is by design, the safe mode is for temporary debugging only.

**Comment by krzysztofjanski** [comment]
Well, description does not state that. What about devices where native code is not provided?

**Comment by sonora** [comment]
My answer was formulated imprecise, probably should have said: Upon each app start, it is tested if the native libraries initialize successfully, and if yes, the safe mode flag is removed again so users do not unknowingly and unnecessarily stay with slow performance. 

I have not checked our code just know, but this is how I remember it is (and I think makes sense) .

**Comment by krzysztofjanski** [comment]
In principle it does not make sense: https://en.wikipedia.org/wiki/Principle_of_least_astonishment

Second, I have a problem with contour lines plugin as it is crashing not only the app but also the system, i.e. the phone is restarting. I'm not able to enable the safe mode upon app startup, because the first thing the app is doing is drawing a map, which is crashing the phone. So I do not see any sense in giving a user a safe mode if a user has no chance to enable it.
I'm not able to check whether safe mode has influence on the system crash.

**Comment by sonora** [comment]
Like your reference to POLA :)  I can concur with that many of times.

But with respect to the issue you raise here: Our menu item "Safe mode" does exactly what its description says: "using slower Android instead of native code". Things like the contour plugin are not affected at all.

I will leave this issue open for others to comment. But chances are the only action, if any, may be to rename "Safe mode" to something like "Use Java only". Which would raise many question marks with people not knowing what this means...

**Comment by krzysztofjanski** [comment]
If I may suggest, I see options:
- During initial setup, when some configuration file is not existing, set the recommended setting and user changes later are persistent.
- Indicate somehow the recommended setting in description or near the option.

Either way it is an advanced option. I think "native code" is more fuzzy than "Java only" :)

**Comment by vshcherb** [comment]
Safe mode is very buggy (in sense of rendering) and very slow. We are inclined to completely disable it. It has the same meaning as Safe boot for Windows (special mode to boot Windows).
