### ISSUE TITLE
Osmand folder in Lollipop 5.1.1

### ISSUE THREAD

**Issue by cuervosanto** [osmandapp/Osmand#2757]
I am using a mobile with Lollipop 5.1.1. I need to move maps from the pc to the mobile, but I don't know where is the Osmand folder maps. Can someone help me with this ? Thanks is advance ! Miguel

**Comment by sonora** [comment]
When in OsmAnd you go to "General Settings", the line below "Data storage folder" should display your current data folder? (You can also change it there to your liking, subject to what your particular version of Android permits, which can be a bit tricky.)

**Comment by cuervosanto** [comment]
Hello, thanks you for your prompt answer !
As I can can see, I can edit the path regarding your directions.
So, the thing is to move the maps from the pc to the mobile folder that I
specify as the new path ?
Do you know if I can move the whole content in the default path to the new
one ?
And the last one: is there a way to import the favourite Osmand file from
my old mobile to my new mobile ?

Thanks in advance !

**Comment by sonora** [comment]
Yes, you can simply copy the contents of the OsmAnd data folder of the old device to the OsmAnd data folder of the new device (even if the path to the top folders folders on both devices differ). This should also take care of importing the favorites.

To explicitly import the favorites, just copy the favourites,gpx file to anywhere on the new device, then in some sort of Android file manager tap on it. Select OsmAnd it handle it if prompted, then select "Import" when asked.

**Comment by cuervosanto** [comment]
I don't know your name, but thank you very very very much !!!

**Comment by vshcherb** [comment]
I think the issue was solved but we will change default folder anyway for new version.
