### ISSUE TITLE
Problem with arabic font display

### ISSUE THREAD

**Issue by BoFFire** [osmandapp/Osmand#2758]
Hi, I'm an OSM contributor who uses regularly OSMAnd.
When creating a neighbourhood POI in arabic by mixing numbers and caracters, the numbers are displayed but not the name.

Example :
name:fr=05 juillet 1962
name:ar=in arabic*

OSMAnd displays only 1962              05 without the arabic caracters جويلية.
Salutations amicales.

**Comment by BoFFire** [comment]
The problem occurs even if I switch OSMAnd to full arabic :

Screeshot 1 : http://image.noelshack.com/fichiers/2016/26/1467190958-screenshot-2016-06-29-09-20-57.png
Screenshot 2 : http://image.noelshack.com/fichiers/2016/26/1467190956-screenshot-2016-06-29-09-55-21.png

**Comment by vshcherb** [comment]
This is a duplicate issue OsmAnd has a rendering issue when mixing characters from 2 fonts in the same name.
