### ISSUE TITLE
Lake Ijsselmeer disappears in 14, 15 zoom level.

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#2759]
Zooming in on the "ijsselmeer" the water that was light-blue suddenly turned the same colour as the land: yellow-brown. It happened between the zoom levels "1km" and "500m".
https://www.dropbox.com/s/lu9o9zzk85vwf9h/lake_1.png?dl=0
https://www.dropbox.com/s/8xr757igt0m6ctu/lake_2.png?dl=0

**Comment by xmd5a2** [comment]
Note: Ijsselmeer multipolygon is incomplete in Flevoland obf
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot%20from%202016-06-29%2021%3A10%3A40.png

**Comment by xmd5a2** [comment]
Fixed
