### ISSUE TITLE
UTM coordinate bug

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#2761]
Recently I used the UTM coordinate location feature of OsmAnd+ 2.3.5 (2016-04-28)

I was in Germany located near the city of wegberg (5747300 614452 31U, 31N).

Technically the UTM zone is 32U - using OsmAnd the lookup returns 32N which is in Africa. Also it was not possible to enter the correct coordinates and resolve a point on the map.

**Comment by vshcherb** [comment]
Not a bug. We are using UTM Standard and not UTM NATO.

**Comment by vshcherb** [comment]
https://www.uwgb.edu/dutchs/UsefulData/ConvertUTMNoOZ.HTM

**Comment by devurandom** [comment]
For a ticket tracking support of the UTM variant [MGRS](https://en.wikipedia.org/wiki/Military_Grid_Reference_System) / [UTMREF](https://de.wikipedia.org/wiki/UTM-Referenzsystem) used by the NATO and civil protection services see #2265.
