### ISSUE TITLE
Wrong screen orientation after "Take a photo note"

### ISSUE THREAD

**Issue by juhanjuku** [osmandapp/Osmand#2762]
After "Take a photo" screen orientation locks on landscape position regardless how I turn my phone.
Rotating unlocks after I switch to another app and back to OsmAnd.
OsmAnd+ 2.3.5, Sony Xperia Z3 Compact, Android 6.0.1, 
settings > Screen orientation = Same as device,
happens in all map modes (map, car, pedestrian)
Discovered this bug after last upgrade.

**Comment by crimean** [comment]
Cannot reproduce
