### ISSUE TITLE
Rename Map markers

### ISSUE THREAD

**Issue by juhanjuku** [osmandapp/Osmand#2763]
I really miss any possibility to add some text to map markers. They suppose to help remember something on map for later actions, but I cant' add comment, what I must remember. There is only flag and location name. I can add audio note, video note but no text note. Flag description could contain my comment instead of text about location (which I see anyway on map)

**Comment by sonora** [comment]
Side note: The more features we add to the "Map markers", the ore questions we raise what the actual difference is vs. "Favorites" ....

**Comment by vshcherb** [comment]
Map markers could be easily renamed as they are used as favorites. We have plans to combine Map Markers and Trip Planning plugin in future, so there we might introduce that feature, though I don't think we are going to complicate map markers themselves. Favorites are always a better option to give a name.
