### ISSUE TITLE
Save  current GPX track does not do anything

### ISSUE THREAD

**Issue by phil123456** [osmandapp/Osmand#2764]
Hello,

1) as I click on "Save current GPX track" it does not do anything

the "log track to gpx file during navigation" says it should record tracks in the tracks folder

I searched on my phone and phone card, there is no tracks folder nor gpx file

actualy both Android/data/osmand/files are empty

2) also I cannot share my tracks by sending them by mail
the email I receive contains no attachement

I have a samsung xcover 3
android 5.1.1

please let me know if you need more infos

**Comment by sonora** [comment]
When after saving a GPS track in this fashion, in OsmAnd you go to "Menu / My Places / My Tracks", can you locate the track on that screen? (It should be in a sub-folder called "rec", and the default name should be something like "yyyy-MM-dd HH-mm_DAY".

**Comment by phil123456** [comment]
indeed but how do you get the file as gpx ?
as I said, mail sharing sends a mail without atachement

**Comment by sonora** [comment]
The tracks should normally be gpx files, and after saving should automatically be located in the Osmand Data storage folder (the one indicated in the General settings under "Data Storage folder"), sub-folder tracks/rec. From here they can be copied using a file manager, or via USB connection to a P, or via "Share" actions. I have heard this may differ under some circumstances in Android 5 and 6, but have no experience with this so far,

**Comment by phil123456** [comment]
no gpx file at all anywhere
I would have to install adm to check the logcat on android...

**Comment by sonora** [comment]
What version of OsmAnd are you using?

**Comment by phil123456** [comment]
2.3.5 rel 2016-04-28

**Comment by vshcherb** [comment]
Most likely they are in internal memory, you need to change app folder. We already noticed that issue and going to change default installation folder https://github.com/osmandapp/Osmand/issues/2766

**Comment by vshcherb** [comment]
So this issue will be fixed by https://github.com/osmandapp/Osmand/issues/2766

**Comment by phil123456** [comment]
well that's the problem, there is no way for me to say I want it on the sdcard for instance

**Comment by phil123456** [comment]
still no option to export/save whaterver
still no attachment sharing by mail

**Comment by phil123456** [comment]
restarted the device, saved one of the tracks to abcdef, and searched on the device memory and on sd card, no file found, where the f... are thes files stored
they are still there if I restart the fone, they got to be somewhere

**Comment by vrtareg** [comment]
Mine one:

Latest OsmAnd nightly
Samsung Galaxy Note 4
Android 6 something

Saved path is

/storage/B906-AFA5/Android/data/net.osmand.plus/files/Tracks/

Where B906-AFA5 looks like formatted sdcard partition serial number or
something like that.

Some of the files are under additional "rec" subfolder.

Regards,
Areg

**Comment by phil123456** [comment]
I'll try to find another app that currently save gpx files on my phone

**Comment by vshcherb** [comment]
We recently changed the default location of the track files, cause it was very difficult to retract them from the internal storage. Next release it will be available on the external storage

**Comment by laszlobortel** [comment]
Hi,
I have run into the same trouble as phil123456 and I REALLY need to get my gpx tracks. Anyone can write me a recipe exactly how to get them from internal storage?

**Comment by vshcherb** [comment]
Change storage folder in general settings or share single track you need.

**Comment by laszlobortel** [comment]
Thanks for the advice. However sharing does not work at all, as phil123456 described the issue. The tracks are already recorded in to internal application memory. If I change the storage folder in general settings will the already recorded gpx tracks get copied into the new, accessible location?

**Comment by sonora** [comment]
Yes, you will see a question whether to copy all data that when changing the data storage.

**Comment by laszlobortel** [comment]
Hi Sonora, hi vshcherb!
Thank you very much for your help: using your advice I managed to switch from internal to shared memory then to save my valuable tracks of our summer holiday. The copy function took care of all map files and all tracks as well.
Actually I am using Osmand+ and I will keep using and supporting this great application in the future.
Thanks again!
