### ISSUE TITLE
Make default storage External Storage 1

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#2766]
Keep backward compatible for users who are using Internal Storage

**Comment by njohnston** [comment]
@crimean: good change but I noticed a typo (memoryStickOnClickListene**s**r) in  OsmAnd/src/net/osmand/plus/OsmandSettings.java.

**Comment by crimean** [comment]
@njohnston thanks! Fixed https://github.com/osmandapp/Osmand/commit/0668dbe992183aed992f43b38afee4d03615d103
