### ISSUE TITLE
Amend text of "OSM Mapper assistant"

### ISSUE THREAD

**Issue by bjohas** [osmandapp/Osmand#2768]
The purpose of the  "OSM Mapper assistant" ("Configure map" > "Details" > "OSM Mapper assistant") seems to be to display extra text on nodes that have the "note"/"fixme" tag (green for note, purple for fixme). (Are other items also shown, e.g. "comment"?)

I would suggest that the text of the item  "OSM Mapper assistant" be changed to  "OSM Mapper assistant (Show OSM tags 'note' and 'fixme')", or perhaps just "Show OSM tags note and fixme". That would make the function of this setting clearer.

Also see https://github.com/osmandapp/Osmand/issues/2767.

**Comment by xmd5a2** [comment]
Too long name. Besides "OSM Mapper assistant" shows not only fixme/note, but also objects that normally are not rendered by style.

**Comment by tazva** [comment]
I agree that more of a description (either through tutorials/manual online, or in the app) needs to exist for this rendering option. For the longest time I couldn't figure out why my screen was cluttered with--sometimes the whole screen--lengthy portions of text. Some people use the notes section to provide long descriptions for things like pieces of art.
