### ISSUE TITLE
A new map language "name:eo=*"

### ISSUE THREAD

**Issue by dotevo** [osmandapp/Osmand#2770]
Hi,

Could you add a new map language? I could not find Esperanto.
http://taginfo.osm.org/keys/name%3Aeo

Br,
Adam

**Comment by verdulo** [comment]
Esperanto estas disponebla kiel map lingvo kaj (parte - la traduko ne estas ankoraŭ kompleta) kiel lingvo de fasado (ang. interface); tamen nur en "Nightly" versio. Vi povas elŝuti ĝin el: http://download.osmand.net/latest-night-build/OsmAnd-default.apk. Bonvolu sciigi min, ĉu ĉiuj frazoj/vortoj estas kompreneblaj kaj ĝustaj/korektaj...

**Comment by dotevo** [comment]
Mojose :+1: . Cxu vi povas diri kial "Ŝĉecino" mi vidas kiel "Szczecin"?
https://www.openstreetmap.org/relation/34293

**Comment by verdulo** [comment]
Ĉiuj ŝanĝoj en la OSM mapo bezonas tempon por dissendado al uzantoj; bonvolu atendi ĝis la nova versio de mapo estos disponebla (oni kutime preparas novajn mapojn je la komenco de monato). Mi mem estas kontraŭ esperantigado de nomoj de urboj, rigardu al tiu ĉi aĉa transliterado: https://eo.wikipedia.org/wiki/%C5%9Cvintohuvitso.

**Comment by dotevo** [comment]
Mi ne estas en OSM de hodiaǔ :) Mi scias ke ŝanĝo bezonas tempon
https://www.openstreetmap.org/user/Dotevo
https://www.openstreetmap.org/user/DotevoCC
Sed esperanta nomo estis aldonata 10 monatoj. https://www.openstreetmap.org/changeset/33853744

**Comment by vshcherb** [comment]
Is not it too few objects? Only 4000 around the world

**Comment by verdulo** [comment]
Tio eble estas problemo kun OSM mem, ne kun OsmAnd - en tiu ĉi mapo: http://mlm.jochentopf.com/ mi ankaŭ ne vidas nomon "Ŝĉecino".

This is probably problem with OSM itself, not with OsmAnd - on this map: http://mlm.jochentopf.com/ I can't see "Ŝĉecino" either.

**Comment by sonora** [comment]
Yes, exactly, it is a data issue. Question is if we cause not more question marks than benefit if I enable a map language which has almost no entries mapped to it globally?

**Comment by dotevo** [comment]
I do not think that is too few. I think that all countries and capitals are already in and many other cities. But if you want we can dalay it a little. I will add more data.

**Comment by sonora** [comment]
I guess you are right: It is quite natural that for regional languages local names exist mostly in only a regional area, so this is not a mapping deficit.

For now we have no other concept to support showing regional language map names than offering these as "Map language" by one entry each in our menu.
