### ISSUE TITLE
Normal mode routing not using routing.xml

### ISSUE THREAD

**Issue by cl604** [osmandapp/Osmand#2772]
Hi,
I struggle with the calculation of routes using the routing.xml.
I need to check the safe mode in order to force osmand to calculate the route with the restrictions I set (height, weight) to route correctly (means avoiding bridges not high enough etc.). In the "normal mode" osmand takes those settings not into account when routing.

This issue appears with:
osmand offline routing with offline vector cards (full standard maps downloads)
Version 2.3.5 tested on Android 4.4 and 5.0.

Best regards

Dominic

**Comment by vshcherb** [comment]
Yes it is existing bug https://github.com/osmandapp/Osmand/issues/1830
