### ISSUE TITLE
In obf_creation/rendering_types.xml convert tags of the form access:X=Y to X=Y

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#2773]
In obf_creation/rendering_types.xml convert tags of the form access:X=Y to X=Y (X is e.g. vehicle, bicycle, foot, hgv, etc.). It seems the keys without "access:" prefix are used much more. In routing.xml we only support the X=Y tags (without access: prefix). But we could accept (by converting them) the access: prefixed keys as they are also valid.

**Comment by xmd5a2** [comment]
Fixed b0e256969a82ccb31bb287a5535851ac40c89700

**Comment by aceman444** [comment]
Thanks, please also add access:vehicle.

**Comment by aceman444** [comment]
ping :)

**Comment by xmd5a2** [comment]
access:vehicle to vehicle conversion added in jule

**Comment by aceman444** [comment]
I see now, thanks. You just didn't paste the commit link.
https://github.com/osmandapp/OsmAnd-resources/commit/fb07a3165128530eea025c83360538a31377d8d1
