### ISSUE TITLE
Confusing string "Filter open"

### ISSUE THREAD

**Issue by verdulo** [osmandapp/Osmand#2774]
The string "Filter open" in "Search POI" dialog is composed of 2 strings: 1674: "Filter" and 358: "Open". The problem is that string 358 is described as "shared_string_open"; which suggest that it can be used somewhere in the program in for example "Open File". It can be translated correctly neither into Polish neither into Esperanto, so please add new string to the program: "Filter open", or even maybe "Filter 24/7".

**Comment by sonora** [comment]
Renamed `shared_string_open` to `shared_string_is_open`.

**Comment by sonora** [comment]
PS: Also localized 24/7 string  `shared_string_is_open_24_7`, and fixed bug when translated 'open' strings contained blanks.
