### ISSUE TITLE
Support of "level" tag

### ISSUE THREAD

**Issue by bjohas** [osmandapp/Osmand#2775]
The suggestion is for OSMAND to support the "level" tag, similar to OSM data shown by level here: http://openlevelup.net/?lat=51.530174&lon=-0.124900&z=18&t=0&lvl=-2&tcd=1&urd=0&bdg=0&pic=0&nte=0&ilv=0

Ideally it would be possible to show levels by level selection (as in openlevelup), but also in a simple way, just giving two options: "0 and above" (i.e. don't show underground), and "-1 and below" (only show underground, for subway routing).

**Comment by vshcherb** [comment]
Will be quite complicated to change, I don't expect this change any time soon.

**Comment by bjohas** [comment]
I noticed that under "Configure map > Hide" there's an option to "Hide underground objects", which is already similar to the functionality suggested. I assume that this must work by eliminating objects with certain tags - so display by level should be possible too?

**Comment by bjohas** [comment]
I've had a look at the code - would you be able to give me a tip as to how "Hide underground objects" is implemented?

**Comment by bjohas** [comment]
Related suggestion here https://github.com/osmandapp/Osmand/issues/2910

**Comment by xmd5a2** [comment]
At that moment all rendering data is obfs can be at layer=-1,0,1. "Hide underground objects" uses "layer" tag, not "level".

**Comment by bjohas** [comment]
What do you mean by "At that moment all rendering data is obfs can be at layer=-1,0,1." ? Do you mean that the obf doesn't have all tags?

**Comment by xmd5a2** [comment]
Yes. rendering_types.xml
```xml
	<type tag="layer" value="0" minzoom="10" additional="true" poi="false"/>
	<type tag="layer" value="1" minzoom="10" additional="true" poi="false"/>
	<type tag="layer" value="-1" minzoom="10" additional="true" poi="false"/>
	<entity_convert pattern="tag_transform" from_tag="layer" from_value="+1" to_tag1="layer" to_value1="1"/>
	<entity_convert pattern="tag_transform" from_tag="layer" from_value="2" to_tag1="layer" to_value1="1"/>
	<entity_convert pattern="tag_transform" from_tag="layer" from_value="+2" to_tag1="layer" to_value1="1"/>
	<entity_convert pattern="tag_transform" from_tag="layer" from_value="-2" to_tag1="layer" to_value1="-1"/>
	<entity_convert pattern="tag_transform" from_tag="layer" from_value="3" to_tag1="layer" to_value1="1"/>
	<entity_convert pattern="tag_transform" from_tag="layer" from_value="+3" to_tag1="layer" to_value1="1"/>
	<entity_convert pattern="tag_transform" from_tag="layer" from_value="-3" to_tag1="layer" to_value1="-1"/>
	<entity_convert pattern="tag_transform" from_tag="layer" from_value="4" to_tag1="layer" to_value1="1"/>
	<entity_convert pattern="tag_transform" from_tag="layer" from_value="+4" to_tag1="layer" to_value1="1"/>
	<entity_convert pattern="tag_transform" from_tag="layer" from_value="-4" to_tag1="layer" to_value1="-1"/>
	<entity_convert pattern="tag_transform" from_tag="layer" from_value="5" to_tag1="layer" to_value1="1"/>
	<entity_convert pattern="tag_transform" from_tag="layer" from_value="+5" to_tag1="layer" to_value1="1"/>
	<entity_convert pattern="tag_transform" from_tag="layer" from_value="-5" to_tag1="layer" to_value1="-1"/>
```

**Comment by bjohas** [comment]
Ok - great.

Two questions:
- What happens to layer=0 or where layer is not present?
- Is the level tag discarded (i.e. not in the obf file)?

Here are three suggestions: 

(1) In the same way as hide underground objects is presumably hiding anything that has layer=-1, there could be a "hide overground objects", that hides anything with layer=0, layer not present, and layer=+1. Is that possible? 

(Btw. in case the above s the complete extract: There seem to be cases where the layer goes beyond +/-5. I can investigate if that would be useful.)

(2) My understanding is that the layer tag is not supposed to be used for absolute vertical order, but is  used to indicate a "local" relation. However, in practice ground level objects are layer=0, and overground>0, underground<0, so the above kinda works in practice (and suggestion 1 is therefore useful). However, I would suggest to rename the options to "Hide negative layers" and "Hide positive layer and zero layer" (or perhaps "Hide layers < 0" and "Hide layers >= 0").

I guess I could do a separate request for (1)/(2)?

(3) My original suggestion would then be to include the "level" tag in the obf file (if it's not present already), and add UI elements accordingly. 

What do you think?

**Comment by bjohas** [comment]
Level is referenced in rendering_types.xml twice

	<entity_convert pattern="tag_transform" from_tag="floor" to_tag1="level"/>
	<entity_convert pattern="tag_transform" from_tag="seamark:signal_station_warning:category" from_value="level" to_tag1="seamark:signal_station_warning:category_name" to_value1="Level"/>

**Comment by xmd5a2** [comment]
layer=0 is default layer where all objects without this tag is rendered by OsmAnd. Level tag is not properly supported yet.
Yes, UI needs to be updated to support this tag.

**Comment by sonora** [comment]
No action planned any time soon here.
