### ISSUE TITLE
Add POI-type for "accessibility"

### ISSUE THREAD

**Issue by bjohas** [osmandapp/Osmand#2776]
At the main POI level, add an option for "accessibility" to provide users with reduced mobility with information on access features. If selected, the POIs shown would be features marked with wheelchair=yes/no, highways=steps (with conveying=yes/no), etc.

**Comment by vshcherb** [comment]
For now it is impossible to implement cause these objects are not part of the POI data in OsmAnd. For such wide range of objects we will need to adopt Map Data which contain all objects (POI is tiny preselected subset of map objects).
