### ISSUE TITLE
exception in OsmAnd~ 2.3.5

### ISSUE THREAD

**Issue by homebeaver** [osmandapp/Osmand#2780]
While testing the app I an exception occured - see log

Device : gt510wifi
Brand : samsung
Model : SM-T550
Product : gt510wifixx
Build : MMB29M.T550XXU1BPE1
Version : 6.0.1
App Version : OsmAnd~
Apk Version : 2.3.5 238

[exception.log.txt](https://github.com/osmandapp/Osmand/files/347220/exception.log.txt)

**Comment by vshcherb** [comment]
Known exception so far, though we don't know exact way how to reproduce it.

**Comment by scaidermern** [comment]
The crash in GeneralRouter is the same as #2521 and should already been fixed in the nightlies.
