### ISSUE TITLE
Voice Prompts After Routing has Finished?

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2781]
Not sure this is intended behavior, but for the record:

We initialize the voice command player (via `initVoiceCommandPlayer`) upon entering the route planning screen (actually in `enterRoutePlanningModeGivenGpx`), but we never shut it down after route cancellation.

I think this leads to the announcement of traffic warnings etc. even when not routing, but only after a route had been calculated at least once in the current app session.

We can leave it like that (it can actually be used as a feature), but it may be a little intransparent behavior.?

**Comment by vshcherb** [comment]
I think this is the issue though other way around. We should never hear message with profile World, but it is supposed to talk in an other profile.

Though you are right looks like it get quite weird that no one complained we might not need to change it.

**Comment by sonora** [comment]
I hate to change it, because I know some people use it as a feature when driving with the browse map profile (which is default after stopping/finishing an navigation).

Only way I can think of to make it more transparent would be to have a setting "Traffic warning prompts while not navigating", and I hate us creating eve more settings either   :-)

**Comment by vshcherb** [comment]
I'm afraid it is not designed to drive with browse map profile, the audio should work in other profiles only. We could easily agree to that because it was designed from the beginning, though the bugs and people get used to them as features

**Comment by vshcherb** [comment]
BTW application not always switch to "default" profile, you can change it in OsmAnd Settings

**Comment by sonora** [comment]
I have done a lot of cleanup to our voice engine code in recent weeks, think I may have changed that behavior anyway, accidentally though. But you are right, it was never designed to be that way, so no one will complain, I hope. Code is much cleaner and more predicable now, I think.
