### ISSUE TITLE
route=foot;bicycle not rendered ?

### ISSUE THREAD

**Issue by adrien-github** [osmandapp/Osmand#2782]
Hi,

Some trails are not rendered on OSMand, like this one : 
http://hiking.waymarkedtrails.org/#route?id=6183132

Maybe it's because this trail is tagged « route=foot;bicycle;horse » and not simply « route=foot » ?

Kind regards

Adrien

**Comment by xmd5a2** [comment]
Semicolon separated tags are not supported in OsmAnd and not recommended in OSM.

**Comment by adrien-github** [comment]
So how should I map these trail, so it appears as a foot trail and also a bicycle/horse trail ? Maybe this is better from OsmAnd point of view ?
route = foot
bicycle = yes
horse = yes

I have asked on the french OSM list how to map it, and the answer was with the semicolon. As it was well recognized on waymarked trail, I investigated not much.

**Comment by xmd5a2** [comment]
I think that best you can do is to create separate relations for every route type. Support of semicolon in tag values is rather poor in applications using OSM. This tagging in general is confusing:
```
network=lwn;lcn
route=foot;bicycle;horse
```
It is assumed that rendered should split these values and find appropriate value for network=lwn and network=lcn. What if their order is wrong? There is too much complication.

**Comment by adrien-github** [comment]
Ok, so I can try 3 relations like this : 
- one with route = foot, with all the members of the trail
- one with route = bicycle, with the first relation as one only member
- one with route = horse, the same way

With this, I got 3 relation, so it should pass in osmand ? and if the trail change, I juste have to modify the first one. Do you think it's a good idea ?

**Comment by xmd5a2** [comment]
OsmAnd will render all relation members. If relation contains only one member hence it will be rendered but not others from other relations.
But are you really sure that this route is really dedicated to foot, bicycle or horse? Do you have any other map sources or this is just your assumption based on exploration at place?

**Comment by adrien-github** [comment]
I am living near, and I use it very often. So yes, I know it's specially dedicated to foot, bicycle and horse.
