### ISSUE TITLE
gps widget on bottom on the widgets bar

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#2785]
On the latest builds, the widget for the gps signal was moved to the lowest part of the right side widgets bar.

This creates some conflict with using the previous bottom widget, that was the button 'Start' to record a note.

Having the 'start' button on the bottom of the bar is more handy to choose to start and stop a recording.

Now it's harder to choose the 'start' record button, since it's sandwiched between the gpx and the gps buttons, more so if we are moving, or driving, and just want to tap it to make a fast audio recording.

Please put the 'Start' note recording button back on the bottom of the widgets bar.

**Comment by sonora** [comment]
Barrocas, users asked for
-some structure in this and
-consistency between the order on the map screen and in the config menu.
The suggestion was these categories:

- Group 1: navigation-related
- Group 2: position-related
- Group 3: recording- and other plugin-related
- Group 4: general device information
- Group 5: widgets for debugging-purposes

So based on what internal or external plugins you have enabled, the visible widgets will adhere to this order. You can of course make one of the recording widgets the last one in the stack by hiding all below, I guess this is what you had before?
Best,
Hardy

**Comment by Barrocas** [comment]
Hi,

No, I never had any of the widgets hidden. All visible at all times.

I consider the GPS widget as a good information about position, so I
am used to seeing it at a position closer to the top of the widgets
bar, as in related to group 2.
If I have no GPS signal (or weak), then I have no trusty navigation or position.

Previously, the recording plugin has always been the last one in the
stack (bottom), and that position was great for a quick tap to record
or stop recording.
Not so great now, since it's been moved upward, and now rests between
other widgets, so when using small phones, on a moving car, requiring
fast/short action, it just doesn't help at all.

What happens now, is that instead of clicking the 'Start', it's the
GPS widget that gets a touch, so a popup appears, and after closing
the unwanted popup, the place where the recording was necessary, has
already passed by...

-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by sonora** [comment]
Ok, I have moved "GPS Info" to the bottom of the "position-related" group 2, I think this achieves what you want: Audio note's "Start" button is again the bottom of the stack, unless you have the Distance measurement plugin or any device/debugging-related widgets activated.

**Comment by Barrocas** [comment]
Thanks :)

-- 
Cumprimentos,
D.er Hugo Barrocas
