### ISSUE TITLE
Download 'Contour/HillShades' not working

### ISSUE THREAD

**Issue by postadelmaga** [osmandapp/Osmand#2787]
How to reproduce:
-> Manage Map Files
-> go to Asia -> Thailand
-> click on 'get' button next to 'Contour' or 'HillShades'

at this point suddenly the main OsmAnd window is presented, but nothing else happens/ nothing is downloaded ...

**Comment by homersimpsons** [comment]
You need to get the add-on

**Comment by postadelmaga** [comment]
ok,thanks, I didn't know, It will be nice to make it more clear so ...
