### ISSUE TITLE
UI Feature request : Bulk upload for OSM Edits

### ISSUE THREAD

**Issue by paskalito** [osmandapp/Osmand#2788]
With the great osm edit tool, one can pretty conveniently add nodes.
Since im usually offline i do not upload them on creation but at sometime at home.

It would be great to have an option "upload all osm edits" - since its quite annoying to search every chang on the whole map and click ~3-4 times to upload it.

maybe that option could live in a new osm edits menu entry in the sidebar. (where one also could list all the changes?) or just in the regular preferences or the plugins page to begin with.

**Comment by jf-simon** [comment]
You can do this. Go to settings->osm edit. Here you can find your offline edits. 
Press the button to upload all edits.see screenshot
![img_20160707_104748](https://cloud.githubusercontent.com/assets/11144987/16647632/6e373884-4430-11e6-8d7a-0e393aab5e22.jpg)
Greetings Simon

**Comment by paskalito** [comment]
woow thanks a lot my fault then.. i did not come up with the idea of searching for that within my places...
