### ISSUE TITLE
Difficult to use map markers in a journey

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2789]
We have already a closed issue about naming the flags. The wisdom is that if naming is allowed, then there is no difference between a Favorite and a flag.

That's good logic. 

But the remaining logic is not compatible with this logic.

I think the best application of flag markers is to plan a rapid-fire trip.
So imagine a few flags are already planted on the map.
1. When we tap on each flag, the context menu is too big+complex. We don't need a choice of last/first destination points, destination, etc. We already have a waypoint editor for that, where the user can do the same thing visually, and fast. The context menu should simply add the waypoint.
2. In many cases, OsmAnd cannot resolve the address. In that case, the spot is known as "No address determined". If you have >2 flags like this, the whole purpose is defeated! Which is which??
3. The original flag color is shown only on map, but not in the **Destinations** dialog. This is a major bummer. For example, the Destinations dialog shows them all as orange flags. The quick identity is lost.

**Comment by sonora** [comment]
I think this will be considered in #2765.
