### ISSUE TITLE
Crossing: zebra and crossing: uncontrolled

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#2791]
OSMAND 2.4.0#13396D    Navigation service: OSMAND     car profile.    Offline maps (Spain jun 1,.2016)

On traffic warnings appear nodes with tags highway: crossing    crossing: uncontrolled  but do not appear nodes with tags highway: crossing    crossing: zebra.

I think pedestrian crosswalk would appear on  traffic warnings section in both cases (crossing: zebra and crossing: uncontrolled).

**Comment by vshcherb** [comment]
We display notification only on uncontrolled tags to raise driver attention, all other crossings should be visible enough.

**Comment by polarbearing** [comment]
crossing=zebra is a tagging error. Basically, traffic_signals control a crossing, while zebra stripes don't. 

The correct crossing for zebra stripes is: 
```highway=crossing + crossing=uncontrolled + crossing_ref=zebra```.

**Comment by OpenSourceForEver** [comment]
Ok, I will try fix tags crossing: zebra

Thank you

**Comment by vshcherb** [comment]
If we can depict that crossing:zebra means crossing:uncontrolled than we can change it in OsmAnd as well.

**Comment by OpenSourceForEver** [comment]
Thank you

**Comment by polarbearing** [comment]
> If we can depict that crossing:zebra means crossing:uncontrolled than we can change it in OsmAnd as well.

The tagging error crossing=zebra should not be consolidated by OsmAnd supporting it.

**Comment by OpenSourceForEver** [comment]
It seems there is no agreement for it con osm.    

https://github.com/openstreetmap/iD/issues/3244
