### ISSUE TITLE
Improved gesture handling for rotation

### ISSUE THREAD

**Issue by bjohas** [osmandapp/Osmand#2792]
This issues https://github.com/osmandapp/Osmand/issues/2617 and  https://github.com/osmandapp/Osmand/issues/2618 concern zooming and accidental rotation. Google maps rotates (with the same gesture), but less so by accident. Whereas OSMAND can rotate "by accident". I would suggest that in addition to improved zooming, the gesture for rotation should be improved also, to avoid accidental rotation.

**Comment by vshcherb** [comment]
#2617 was significantly improved and I don't that issue much anymore.
