### ISSUE TITLE
Copy text dialog at wiki full text page

### ISSUE THREAD

**Issue by bes-internal** [osmandapp/Osmand#2794]
Download wiki layer and select wiki poi, go to the full downloaded article, try select a text.
Buttons work, I was trying to select all the text and copy it, but nothing is copied.

Osmand+, 2.3.5 at 2016-04-28

Screenshot:
![screenshot_2016-07-08-00-05-08](https://cloud.githubusercontent.com/assets/2046529/16691776/abdebc3c-4536-11e6-9277-8f29d17c1a18.jpeg)

**Comment by vshcherb** [comment]
Tested on Android 5,6, it looks ok. It is an internal error of webview which was fixed in later Android. As workaround it is suggested to read full article.
