### ISSUE TITLE
Allow interactions while screen is locked

### ISSUE THREAD

**Issue by tko** [osmandapp/Osmand#2796]
Previously discussed in https://groups.google.com/forum/#!searchin/osmand/lock/osmand/WuQ_QwUA6rI/hLJIhWeA5qwJ

Currently osmand is useless when screen lock is password protected to prevent access to email etc.

There's not much in osmand that requires same level of protection and being able to see the map, zoom in/out etc. while the screen is otherwise locked would make osmand _much_ more usable. For reference, see how Sports Tracker and other similar apps manage to be accessible even if the screen is otherwise locked.

From what I gather all it takes is to set few flags when creating the activity, `FLAG_SHOW_WHEN_LOCKED` and `FLAG_DISMISS_KEYGUARD`

**Comment by johnwhelan** [comment]
How do I unsubscribe from this list?

Thanks John

**Comment by tko** [comment]
https://help.github.com/articles/managing-notifications/

Yes, I fat fingered premature submit, I bet you didn't even see the edit.

**Comment by DiGitHubCap** [comment]
This is fairly critical when biking, especially if you have a long PIN or password. You either need to unlock the phone with one hand while riding (dangerous) or stop and unlock it (inconvenient).

**Comment by Chumva** [comment]
This functionality was added and you can find preferences in `Configure profile` settings - `General settings` - `Screen control`.
