### ISSUE TITLE
World altitude correction file map is not listed

### ISSUE THREAD

**Issue by mircozorzo** [osmandapp/Osmand#2798]
World correction altitude map is not listed under "manage map files> local" even if yet downloaded and working fine. On Android 5.1.1 and 4.1.2 nightly version of app.

**Comment by mircozorzo** [comment]
Any news? Bug still present.

**Comment by vshcherb** [comment]
It is not going to be fixed, this file is highlighted green and could be deleted on the first tab. Second tab is used only for maps.
