### ISSUE TITLE
Direction arrows in POIs aren't updating

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#2802]
While taking a look at the POIs screen it seems that the direction arrows aren't updating when moving the phone:

![](https://cloud.githubusercontent.com/assets/982338/16711647/37dbc8fa-463c-11e6-90c5-613b6bdf720c.png)

It seems they are calculated once (when opening/searching the POIs) and never updated anymore.

osmand is 2.4.0#13524D

**Comment by vshcherb** [comment]
Orange arrows are not updating (they are from a given location), only blue are updating.

**Comment by naoliv** [comment]
But shouldn't they be updated here in POIs too?

**Comment by vshcherb** [comment]
Yes there is a small bug that arrow is rotating and it could be very confusing, it will be fixed in the new search.
