### ISSUE TITLE
Speed cameras not working since OsmAnd 2.3

### ISSUE THREAD

**Issue by stefanodroghetti** [osmandapp/Osmand#2803]
Version: Osmand Plus 2.3.x on Android (tried all 2.3.x, included nightly builds)

Offline maps used: official italy-emilia-romagna.obf and unofficial maps made with OsmAndMapCreator of the same area

Point of the map: all speed cameras mapped off road in an enforcement relation, i.e. http://www.openstreetmap.org/?mlat=44.84957&mlon=11.56487#map=19/44.84957/11.56487

Routing used: OsmAnd in-app offline routing (any route passing for those points)
Routing profile used: car

Enabled options: show speed cameras, speed cameras alert

Since OsmAnd shifted from 2.2 to 2.3, **speed cameras mapped as off road nodes into an enforcement=speed_camera relation** (classic three points role=from,device,to where the speed camera is "device") don't generate an alert any more. An icon, neither.

Speed cameras as nodes on the way, work well. On all versions.

**On 2.2.x versions, everything works back**. Just tried with a Plus version thanks to FDroid repositories.

Tested only on Android.

**Comment by xmd5a2** [comment]
This way of tagging is unsupported (no data in obf). Not sure how this could work in earlier versions.

**Comment by stefanodroghetti** [comment]
It's been working since 1.8. And that is the correct way of mapping speed cameras according to OSM Wiki:
http://wiki.openstreetmap.org/wiki/Tag:highway%3Dspeed_camera

> (older versions of OsmAND and OsmandMapCreators did not evaluate the enforcement relation correctly. This has been fixed in OsmAnd since Version 1.8 and current OsmandMapCreators since April 2014.)

**Comment by polarbearing** [comment]
I have a camera on my way (node 326847472) that is mapped off-road as a member of an enforcement relation. The camera itself has a highway=speed_camera as well. It is announced correctly, and only on this of the two carriageways that has the relation on. Lastest nightly less than a week old.

**Comment by stefanodroghetti** [comment]
At the moment I'm not able to reproduce it. I downloaded and installed the latest nightly build, I saved that Berlin area with JOSM, converted in obf with OsmAndMapCreator, put on my phone's SD card, set OsmAnd to alert for speed cameras, set a route passing for that speed camera, simulated my position with the proper plugin... but no speed camera alert.
I have to try with a downloaded map. Maybe the problem is OsmAndMapCreator? :-o

**Comment by polarbearing** [comment]
Having problems now as well, and I'm pretty sure it used to work with off-road nodes in enforcement relations, since I took the node off in 2014 and have got the warning on the road often enough, until recently. See details in [#2921](https://github.com/osmandapp/Osmand/issues/2921#issuecomment-238089826)

**Comment by polarbearing** [comment]
Confirming fix with the September maps for my case.

**Comment by stefanodroghetti** [comment]
It looks like it was not an OsmAnd problem, but a OsmAndMapCreator's bug.
Last version I checked didn't work perfectly, but... almost :-)

Speed cameras are often in a relation, where there is a "from" node on the way, a "device" node not on the way, and a "to" node on the way. The correct behaviour would be to show an alarm from "from" to "to" node. Now it shows an alarm some metres before and after the "from" and the "to" nodes, like they were speed cameras themselves.
Anyway, better than nothing.
