### ISSUE TITLE
Search Sometimes Slow When Returning to the Search Screen via BACK

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2804]
I have been watching this for a while but am not yet sure how to reliably re-produce:

- Go to Menu/Search/POI, tap on any category.
- The search results will start to be displayed really fast (mostly instantaneous).
- Now tap on one of the search hits: It will get indicated on the map, and its context menu will popup.
- Now tap the device's (hardware) BACK button (a frequent use case!) twice: First tap will hide the context menu again, second tap will bring you back to the Search/POI/category screen.

Now, even though this is the very same screen which initially swiftly produced search results, sometimes (often) this screen will remain with the spinner on and not display any results for about 15 sec or so. 

It feels like either there is no list adapter refresh displayed for a long time, or there is still a previous async task running and the system first waits for its termination. The latter seems unlikely, as this is similar to #2657, and there I had already introduced the fix to terminate the Async search task in  onDestroy(). That fixed #2657, but the issue I describe here remains.

**Comment by vshcherb** [comment]
Not much relevant any more

**Comment by sonora** [comment]
Ok, but still see similar effects with the new search. We may again be forgetting to cancel any async processes when leaving the search activity (as was the problem in #2657) - should double-check when it is finished.
