### ISSUE TITLE
Map compression?

### ISSUE THREAD

**Issue by RicoZ-OSM** [osmandapp/Osmand#2808]
Osmand maps are pretty big, close to the point that offline use may become impractical on many devices.

Any hope for a better compression?

**Comment by kompowiec** [comment]
maybe support obf? I'm not sure if you already don't support this format, but manually move map on SD card me doesn't work with geofabrik maps

**Comment by vrtareg** [comment]
OsmAnd is already using obf file format ....

**Comment by polarbearing** [comment]
Seems @kompowiec mixed up the formats. From the Geofabrik you download the *pbf format, than you let OsmAndMapCreator compile the *obf format for OsmAnd. For my region, the geofabrik *pbf extract is 142 MB, the *obf file 299 MB. Certainly there must be a trade-off between preprocessing in compiling the map file and execution time during navigation.

Thet's why for larger countries the data is portioned by region or state.

**Comment by sonora** [comment]
pbf's contain the OSM map data, OsmAnd's binary format also includes the routing data needed for navigation.

**Comment by utack** [comment]
Is it compressed at the moment?

**Comment by johnwhelan** [comment]
Compared to .OSM format it takes up roughly 10℅ if that including indexes.

Cheerio John

**Comment by stephan75** [comment]
To examine whether osmand‘s obf format has still some potential for compressing:
Have some obf files and compress them with any ZIP compressor ... then compare the compression result in percent rate.

And the only alternative I remember:
have a look at the map file format of maps.me ... it is said to be quite compact, and its tools are opensource, or not?

**Comment by kompowiec** [comment]
>Seems @kompowiec mixed up the formats.
yes, little typo. I of course i mean pbf, this which is avaliable on geofabrik.

Now i checked.

For my region (silesia map) values are as follows:

obf (actually with OsmAnd) - 175 MB
geofabrik:
.osm.bz2 - 151 MB
.shp 142 MB
.pbf 88 MB
.kml 3766 B

I pretty compression...

**Comment by utack** [comment]
>have a look at the map file format of maps.me ... it is said to be quite compact  
  
It is also missing quite a bit of stuff  
No "lit" tags, no road lanes, no bicycle parkings and certainly more stuff

But one question:
How about keeping the files compressed by default, with something super fast like zopfli?
Modern phones have at least 4 cores, OsmAnd seems to use 1 for rendering, 1 for routing, so there is always one free core that can decompress the files, and it should not impact performance very much?

**Comment by RicoZ-OSM** [comment]
There is little doubt  the maps could be much more compact.. the question is how to do it without getting even slower.

* is the data preprocessed with Douglas-Pecker to reduce excessive number of nodes on some geometries?
* could the data be more compact if coordinates precision is limited to something like 0.1 metres ?
** could smaller shapes be stored with relative instead of absolute coordinates?
** could https://en.wikipedia.org/wiki/Variable-length_code be used for some data?
* could names and other texts be compressed using https://en.wikipedia.org/wiki/Incremental_encoding ?

**Comment by xmd5a2** [comment]
@stephan75 maps.me maps contains MUCH less data then OsmAnd obfs

**Comment by sonora** [comment]
Without investigating to detail, my gut feeling is that potential may be limited. Also: Live de-compresssion also needs more battery power, which is also a concern for an outdoor/offline app.

**Comment by kompowiec** [comment]
"Seems @kompowiec mixed up the formats"
Typo :/

For my region looks like:

Geofabrik:
.pbf - 88 MB
.shp -  142 MB
.osm - 151 MB

.obf with OsmAnd - 170 MB (one voivodeship with PL)

pretty compression...

**Comment by vshcherb** [comment]
BinaryInspector provides details information about sizes. Please enjoy road only maps they are much smaller and have missing "only buildings on the map".
BTW: pbf is zipped format, so it is better to compare it with obf.zip. Zipped formats are useless for instant access on mobile devices.

**Comment by RicoZ-OSM** [comment]
Compare your road only maps with full mapsforge maps
  http://download.mapsforge.org/maps/europe/

They don't have routing but the level of detail is comparable to OsmAnd and map painting is a bit faster.
