### ISSUE TITLE
disappearing the upper part of the beam.

### ISSUE THREAD

**Issue by kompowiec** [osmandapp/Osmand#2813]
I think that image speaks for itself:
![hjutxma](https://cloud.githubusercontent.com/assets/15860246/16731889/be946e9e-477a-11e6-9875-8b2de6c81567.jpeg)
i use of course night bulid

**Comment by vshcherb** [comment]
Not reproducible on 5 available devices so far.

**Comment by kompowiec** [comment]
It works for me every time

Proably must:
1. Create POI
2. insert some name for POI
3. page down screen
4. insert street or other textspace on bottom
5. page up

I try record if I had such an opportunity.

**Comment by xmd5a2** [comment]
Can't reproduce on android 5.1.

**Comment by kompowiec** [comment]
My version android it old 4.4.4 so proably possible is that can just concern this system. I checked on stable version from Fdroid, can't reproduce too, just night bulid no reason..

Sure i must finally do CyanogenMod ;)
