### ISSUE TITLE
Overlay map transparency slider unaccessible 

### ISSUE THREAD

**Issue by scit2010** [osmandapp/Osmand#2814]
After having set the transparency of the overlay map to zero the slider has become unaccessible.
I touch the slider field in the preferences dialog but am not able to increase transparency anymore. 
Neither disabling the overlay map, choosing another overlay map source, restarting Osmand nor rebooting my phone have effect.

**Comment by xmd5a2** [comment]
Can't reproduce. Please inform us about steps how to reproduce.

**Comment by scit2010** [comment]
How to reproduce:
1. Open the Hamburger menu, select Configure map.
2. Show: Overlay map...
3. Set overlay map to Enabled, drag the "Overlay transparency" slider to the most right.
4. Return from this dialog.
5. Later: Repeat these steps and try to drag the "Overlay transparency" slider to the left.

I don't remember the steps for sure anymore. It might also be that I dragged the on-canvas-slider on the map to make the overlay map transparent.

Expected result:
After step 4 the map is fully transparent.
In step 5 the slider can be dragged to the left to decrease the transparency=make the map visible again.

Actual result:
After step 4 the map is fully transparent.
In step 5 the slider can NOT be dragged to the left to decrease the transparency. Therefore the map stays transparent.

**Comment by xmd5a2** [comment]
Can you reproduce this?

**Comment by scit2010** [comment]
Sorry?
I wrote what I did and that I am not able to change the slider value at all. How am I supposed to reproduce the error then?

**Comment by crimean** [comment]
@scit2010 what version of OsmAnd do you use?

**Comment by scit2010** [comment]
It's version 2.3.5.

**Comment by crimean** [comment]
@scit2010 
1 - Slider should be scrollable when you touch it at center.
2 - You may try nightly build. It may have the fix.

**Comment by scit2010** [comment]
Thank you for your attempt to help. However it seems my verbal description wasn't clear enough. Therefore I'm attaching a screenshot now. It would be nice of you to show me where in the red rectangle I can touch a scrollable slider. There is none.
Nightly builds: 
1. I don't find any nightly builds to download nowhere.
2. Comparing the r2.3.5. release branch and the master branch tells me that they differ by 1'520 commits. Is the answer really to check them all and then search nightly builds which are nowhere and can't even be installed on my device  because they haven't made it into the app store yet?

![2814](https://cloud.githubusercontent.com/assets/2828370/16855739/f86e02bc-4a16-11e6-8058-9b38d44e44d4.jpg)

**Comment by crimean** [comment]
Thanks for the screenshot. The issue already fixed, but not released yet.
I think you may try to turn on "Show transparency seekbar" and adjust it on the map. The small seekbar will appear at the bottom of screen.

From the other hand you may turn on "OsmAnd development plugin" and find Builds item in the main menu (drawer). Then you may download "nightly" build. However this build is development one and it may contain some bugs and unfinished things.

**Comment by scit2010** [comment]
Thank you! After showing and adjusting transparency seekbar the slider in the dialog is back again.
