### ISSUE TITLE
Latest build download gets canceled if I change the mobile orientation (portrait<-->landscape)

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2815]
I am using OnePLus 2, running OxygenOS 3.0.2 (based on Android 6.0.1).

When I am viewing the list of builds, every time I change the mobile orientation (portrait<-->landscape), the list is once again downloaded automatically. **[BUG-1]**

When I am downloading a particular build, the download gets cancelled automatically every time I change the mobile orientation (portrait<-->landscape). The failure is silent: There is no error message. **[BUG-2]**

**Comment by vrtareg** [comment]
This is very old and existing behaviour.
Everything got reinitialised in OsmAnd if you rotate device ....
Very annoying
Other apps are surviving this but not OsmAnd

**Comment by vshcherb** [comment]
Known issue
