### ISSUE TITLE
Need Assistance Testing BT SCO Init under Android v4.2 and v4.3

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2816]
I need some quick support testing something on Android 4.2 and 4.3, but do not have any hardware actually running  these Android versions.

Maybe someone running Android 4.2 or 4.3 and using our nightly builds could run this quick test and report here?

- Use an OsmAnd nightly build dated 2016-07-13 or later
- On the device, activate Bluetooth (no need to connect to anything, but it should be on)
- In "OsmAnd / Menu / Plugins", enable the OsmAnd Development plugin (unless already enabled)
- In "OsmAnd / General Settings / Voice guidance output", select the 3rd option "Phone call audio (also tries to interrupt car BT stereos)"
- In "OsmAnd / Settings / OsmAnd development", select the entry "Test voice prompts"
- On the language selection dialog, select "en-tts"
- Scroll down and tap the very last button (11.1) at the bottom of the screen

You should see a toast message on screen. I would need to know if the toast looks like what I framed in red on the screenshot attached, or if you see any "NO" with additional detail?

![btscoinit](https://cloud.githubusercontent.com/assets/845735/16786585/30c256e0-4896-11e6-9a40-7c05b3c680fe.png)

After the test, please disable the Dev plugin, and revert your selection of "Voice guidance output" (Media is the default) and the language selection under "General Settings / Voice guidance" to your needs.

Thanks, much appreciated! - Hardy

**Comment by Barrocas** [comment]
Tested on a THL T200 with Android 4.2.2, toast message is exactly like you
pictured.
Hope that helps.
Cheers!

-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by sonora** [comment]
@Barrocas: I appreciate it, thank you!
I think this clarifies it, if my code works under 4.2.x it should also work under 4.3, so my implementation of the BT SCO capability in OsmAnd should essentially be finished.

This means that OsmAnd can try to interrupt a car stereo, if one is connected via Bluetooth and has speaker phone capabilities, so you can optionally hear OsmAnd's navigation voice prompts via the car speakers and not just your Android device. All you have to do is in **"OsmAnd / General Settings / Voice guidance output"**, select the 3rd option **"Phone call audio (also tries to interrupt car BT stereos)"**.

It may depend on the capabilities of your car stereo, but I have tested successfully on some, users are invited to give it a try.
