### ISSUE TITLE
Incorrect maxspeed values

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#2817]
Sometimes somebody in Iran adds incorrect maxspeed values like "60.70.80.90" or arabic letters. This breaks map creation of the whole country. After last live update process iteration we can't just regenerate map with new data. Map can be generated only during monthly generation process. We need to handle this situation and remove incorrect tags but don't let map creator crash.

**Comment by vshcherb** [comment]
Fixed
