### ISSUE TITLE
amenity=register_office is discouraged

### ISSUE THREAD

**Issue by thetornado76** [osmandapp/Osmand#2819]
The tag amenity=register_office (german "Standesamt") is discouraged. The new approved tag for this is
office = government
government = register_office

https://wiki.openstreetmap.org/wiki/Tag:government%3Dregister_office
http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dregister_office

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/4ebc09a264c1cf01641980139b3d89e56e503fec
