### ISSUE TITLE
Support diaper tag

### ISSUE THREAD

**Issue by HolgerJeromin** [osmandapp/Osmand#2820]
A poi with diaper tag should show this in the detail view. Often this is probably a restaurant, shop or toilet. 

And it should be possible to search for pois with diaper=yes or diaper= (number >0)

Thank you

**Comment by xmd5a2** [comment]
diaper=yes,no,room already supported as POI additional. Unfortunately searching additional tags is not planned.
Added support for diaper=1,2,3..

**Comment by HolgerJeromin** [comment]
Ok, thanks

**Comment by HolgerJeromin** [comment]
But you did with glass recycling container didn't you?

**Comment by xmd5a2** [comment]
@HolgerJeromin what do you mean?

**Comment by xmd5a2** [comment]
https://github.com/osmandapp/OsmAnd-resources/blob/master/poi/poi_types.xml#L2638

**Comment by HolgerJeromin** [comment]
OK, now I understand the search for glass bottle containers. Not suitable for diaper

**Comment by thetornado76** [comment]
One year later. - Maybe it is now planned? This would be great to search for diaper tag.

**Comment by bkil** [comment]
There is an ongoing proposal to enhance tagging of baby changing tables. Please share with whoever may be concerned and feel free to comment:
https://wiki.openstreetmap.org/wiki/Proposed_features/baby_changing_tables
