### ISSUE TITLE
Map download extremely slow 

### ISSUE THREAD

**Issue by cgogolin** [osmandapp/Osmand#2821]
I am not entirely sure this is the right place to report this bug. Please forgive me in case it isn't...

Since a few days ago map downloading in OSMAND on Android (version 2.3.5 from Play Store) is extremely slow. So slow in fact that it is impossible to download any larger map. I managed to download the world base map over night, but downloading Spain Cataluña for example (which is where I am located) is impossible. After many hours the download simply gets stuck at some random low percentage.

I tried two different Android devices and the wifi over which I am downloading is otherwise working just fine.

This is a severe problem as it makes an offline maps application completely useless if you can not download maps.

**Comment by stephan75** [comment]
What is free storage space on your device,  where ypur maps are located, in bytes?

When on an sd card: check whether it is ok.

**Comment by vshcherb** [comment]
Servers now functioning fine

**Comment by cgogolin** [comment]
Yes, I can confirm that everything is back to normal and map downloading works again. Thanks!

**Comment by homersimpsons** [comment]
If this was because there are too much downloads, maybe you can reconsider my proposal in #1134 (adding torrent download)
