### ISSUE TITLE
Bicycle route names rendering

### ISSUE THREAD

**Issue by ad47** [osmandapp/Osmand#2822]
I think, bicycle route names should be aligned with ways, current way of their rendering makes them useless.
https://www.dropbox.com/s/qdbjny96o2zdeje/textonpath_false.png?dl=0
https://www.dropbox.com/s/46f8njhgobmoywz/textonpath_true.png?dl=0

The same is true for mtb routes, but text alignment along winding paths often makes it unreadable. So may be rendering of mtb:names only on hi-scales (z16-17) is a partial solution (now mtb captions emerged even on z11 when only city names are displayed).
https://www.dropbox.com/s/z4qwrrv6r9fray3/mtb_name.png?dl=0
https://www.dropbox.com/s/9bynujil8m7kbi0/mtb_name_on_path.png?dl=0
http://www.openstreetmap.org/#map=15/48.9300/13.0419

**Comment by sonora** [comment]
Ad 1: Yes, possibly but the text is mostly VERY long, it may be hard to read if stretched along the path?

**Comment by ad47** [comment]
Yes, sometimes name is long, but your can scroll screen along the route in such cases.

**Comment by xmd5a2** [comment]
That's why I did not use textOnPath="true". @ad47 on your screenshots it is pretty clear what path corresponds with MTB path name.

**Comment by xmd5a2** [comment]
Maybe it will be better to increase minzoom for bicycle route names to 14 or 15.

**Comment by ad47** [comment]
For bicycle route names increasing min zoom to 15 also may be a solution, only until z15 "Maxhof - Eichelgarten" renders on another route on the first screen.

There is still a problem with parallel routes, especially from north to south (which name corresponds to blue route?).
https://www.dropbox.com/s/52mobye5ighp1s0/bicycle%2Broute_NS.png?dl=0
https://www.dropbox.com/s/3l7quh9m8nnpfl2/bicycle%2Broute_NS_onpath.png?dl=0

**Comment by xmd5a2** [comment]
I understand that it is possible to find a case where it would be difficult to determine which way the inscription refers, but in my opinion it's better than bad read long inscription along the way.

**Comment by ad47** [comment]
Yes, I agree. Rendering of mtb and bicycle names only from z15 will be a solution for most cases.

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/b46fb782065d476d2471f72a99c11380ee43ce8d
