### ISSUE TITLE
MaxSpeed in speed limit prompt for recorded voices

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2823]
@vshcherb : Victor, in order for the MaxSpeed announcement in the new speed limit prompt to properly work also for recorded voices, I guess we would need the recorded voices to also include ogg files for 110.ogg, 120.ogg, 130.ogg. 140.ogg (all other common speed limits are already included, see respective `ispeech_XX.csv` files). Or do I misunderstand how it would function?

Where in what file do I have to specify that future authors of recorded voice should include these? (Or does it work differently?)

My ref code in ttsconfig.p is https://github.com/osmandapp/OsmAnd-resources/blob/master/voice/en/ttsconfig.p#L224

Thx - Hardy

**Comment by vshcherb** [comment]
Unfortunately ispeech is gone and there is no plans to get it back (they deleted paid account with some balance on it) . The only possibility to regenerate all files using google speech (I think it was available option in the script settings), though I'm not sure.

**Comment by sonora** [comment]
Ok. Config files updated anyway: https://github.com/osmandapp/OsmAnd-resources/commit/46fb5c9e6b8923efb6cb2b1062425f988ec5a2c2

**Comment by sonora** [comment]
PS: Our recorded voices are mostly 3 years old, many bug fixes and much translation maintenance has been performed, and many new features have arrived since. Maybe it is worth at some point to start n new generation, it seems there is still some need for the voices not easily played via TTS.

**Comment by OpenSourceForEver** [comment]
I am willing to send you all files recorded (.ogg) maked with "eSpeak text to speech" (open source software) or another software you want. What do you think?

**Comment by sonora** [comment]
From what is foreseeable, I am done for now adding features to our voice prompts which require new vocabulary. And I have updated all our 35 TTS languages to version 13 and the latest feature set. (TODO: We could actually remove v102 support from our code.)

Maybe @vshcherb  could somehow run the script so at least the "word list" `ispeech_en.csv` or similar is re-created new for all recorded languages, so people willing to help with pull request would at least have a an updated list which words are needed as .ogg recordings?

**Comment by vshcherb** [comment]
@sonora  It useless to run script cause we can't use ispeech any more. There was a script to use Google TTS, that we could test if it works. Though ISpeech should be deleted with csv files (once we find a replacement). For now all these languages are not editable any more

**Comment by sonora** [comment]
All I was saying is we have no updated "vocabulary list" for people offering to **manually** produce a recorded language, which they could simply  "read off" and record, and know it is complete.

It is rather complex for non-experts  to deduce from the ttsconfig.p file which ogg-files are actually needed, while the `ispeech_XX.csv`  files doubled as a positive list each (but are now all outdated).

**Comment by vshcherb** [comment]
ispeech_XX.csv was introduced to not pay for already translated files. So it is useless for any other use case, it is very very bad to mix different voices. So all ispeech voices should be regenerated with something else if we want to add new features

**Comment by sonora** [comment]
Understood. I occasionally see offers from people to record voices
themselves - but they ask for a positive list to read all needed files
from. :)

**Comment by vshcherb** [comment]
All needed files are files from config https://github.com/osmandapp/OsmAnd-resources/blob/master/voice/en/ttsconfig.p - '*.ogg' matches  + numbers! That's it. Or simply check existing files . Though for max speed limit we have numbers but we might be missing some other words.

**Comment by sonora** [comment]
I know, but I have also statements there like

 `string(Ogg, A) :- voice_generation, interval(X, 100, 140, 10), atom_number(A, X), atom_concat(A, '.ogg', Ogg).`

which for non-programmers like some of our voice providers may be hard to comprehend ... : )

**Comment by vshcherb** [comment]
Yes, quite hard I guess. Though I still think this is a number.
