### ISSUE TITLE
Should support routing from/to access=private highways

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#2824]
It seems that it's not possible to route from/to `access=private` highways.
For example, osmand creates a route to the closets non-private place while trying to go to a place that has `access=private`.

Could osmand support cases like this, exclusively when from/to are inside a restricted place? (ie, it should not route through restricted road unless it's strictly necessary (when we *want* to go to that destination, for example))

**Comment by vshcherb** [comment]
This is a known limitation or a feature you could consider. There is no fix we can provide for that.
