### ISSUE TITLE
Destination is not set, measuring distances (rules widget)

### ISSUE THREAD

**Issue by bjohas** [osmandapp/Osmand#2825]
Tapping the map gives "destination is not set". Is that expected?

The ruler widget to measure distance does not work. With the widget started, tapping the map just gives "destination is not set". (Same as if the widget wasn't running.) No starting position is marked.

Latest build 2.4.0#4100

**Comment by vshcherb** [comment]
Very confusing description could you please describe from the beginning when you open a map after a full restart.

**Comment by bjohas** [comment]
Apologies. This affects the "ruler widget" used to measure distances. With the widget enabled, testing tapping the widget gives the  help dialogue. Dialogue dismissed as usual. However, tapping the screen to add the first point just gives "destination not set". Points are not marked.

Affects latest nightly.

**Comment by vshcherb** [comment]
Just tested, Widget -> Start Editing -> then tapping on the screen create points. I don't see any issue yet.
Destination is not set is related for navigation.

**Comment by bjohas** [comment]
Exactly the same process doesn't work for me. Just tested again. What could this be to do with? Other plugins? Other settings?

When I tap the widget again, it offers "finish editing", so it's clearly in editing mode.

**Comment by vshcherb** [comment]
I will ask other people around to test it, may be we will see more cases like this.

**Comment by bjohas** [comment]
Still doesn't work for me in #4541.

**Comment by bjohas** [comment]
In v. 4802, the issue is still there (at least for me).

**Comment by Boothy99** [comment]
On my tablet Samsung Galaxy Tab S 8.4  running android 6.0.1 I'm getting this "destination not set" with any short taps on the map. Have latest OsmAnd+ 2.5.4 (22-11-16) with updated maps.

If I try to use measurement tool (see above github link), I'm unable to get it to measure. I simply get "destination not set" popup message. Same message appears without measurement tool activated anyway.

On my phone, using android 5.0.2, there are no problems. All works as expected with no "destination not set" message with short taps on the maps.

**Comment by Boothy99** [comment]
See - Ziel ist nicht festgelegt / Destination is not set Error
https://groups.google.com/forum/m/#!topic/osmand/n1Y6iCu8MUk
