### ISSUE TITLE
Track colour in my tracks cannot be set

### ISSUE THREAD

**Issue by bjohas** [osmandapp/Osmand#2826]
My places > my tracks, select track > track segments. Then click map icon to adjust track settings. The colour can be set, but doesn't show on the map. When the colour setting is reopened, it's reset to "none".

Latest build 2.4.0#4100

**Comment by xmd5a2** [comment]
Can't reproduce. There is two tracks with different colors https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot_2016-07-25-21-17-08.png

**Comment by bjohas** [comment]
Thanks - confirm that this is working in 2.4.0#4176M_2.3.
