### ISSUE TITLE
Do not display menu item to search for parking when reaching destination during bicycle or pedestrian navigation 

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#2828]
OsmAnd opens a menu when reaching the destination that has an item to search for parking space.

This item should not be displayed for bicycle or pedestrian navigation. It should be only available for car navigation.

Found with OsmAnd+ 2.3.5 and earlier.

**Comment by osMatt** [comment]
This might have already been added: https://github.com/osmandapp/Osmand/pull/2671

**Comment by sonora** [comment]
It is already fixed: https://github.com/osmandapp/Osmand/commit/4b83ecb9f5486b406fec428cad26ffe9ac67233a
