### ISSUE TITLE
Routing through roads with tag barrier=toll_booth and "avoid toll" option

### ISSUE THREAD

**Issue by hitmanx4** [osmandapp/Osmand#2830]
Hello,

Lately I was driving through Czech Republic and on one section of the road there was a problem with routing. It told me to turn right instead of driving straight (longer distance). It turned out that the problem is the "barrier" tag on the road. When option "avoid toll roads" is unchecked then everything is OK. I attach screenshot with both variants. I think that Osmand ignores the toll=no option.

Osmand version: 2.3.5 on Android
Offline maps and routing (car)
the problematic node: http://www.openstreetmap.org/node/3044169508
There's no physical barrier, just cameras above the road.

![2016-07-17 17 10 18](https://cloud.githubusercontent.com/assets/20503832/16902082/64009a32-4c54-11e6-80b5-0a620a2d356a.png)
![2016-07-17 17 10 25](https://cloud.githubusercontent.com/assets/20503832/16902083/64013aa0-4c54-11e6-9f40-a1e1b3c830c3.png)
![2016-07-17 17 11 02](https://cloud.githubusercontent.com/assets/20503832/16902084/640347f0-4c54-11e6-962c-0b9cc5eee410.png)

**Comment by aceman444** [comment]
Yes, OsmAnd does not ignore the toll booth if it has toll=no. Thanks for noticing.

**Comment by vshcherb** [comment]
We could add before line https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#L356
```<select value=“0” t=“tool” v=“no”/>```

Though it needs to be tested

**Comment by aceman444** [comment]
Wouldn't that also hit for e.g. toll=no+barrier=block , thus allow to route though it? We only need to ignore barrier=toll_booth (with toll=no) not any other barriers. AFAIK it is hard to match on multiple tags in routing.xml.

**Comment by polarbearing** [comment]
> There's no physical barrier, just cameras above the road.

In this case they should be tagged as enforcement devices, not as toll booth. We had this discussion in Germany, where cameras monitor HGV movement, however the HGV-only toll is being paid in fuel stations or online.

**Comment by hitmanx4** [comment]
> We had this discussion in Germany, where cameras monitor HGV movement, however the HGV-only toll is being paid in fuel stations or online. 

But I don't know if it works the same way in other countries. 

http://wiki.openstreetmap.org/wiki/Tag:barrier%3Dtoll_booth
> An exception is the system for HGV toll in Germany [...]

**Comment by xmd5a2** [comment]
There are 10 points in OSM database with tags barrier=toll_booth + toll=no + toll:hgv=yes. Since we don't have working HGV profile shouldn't be enough to remove barrier=toll_booth when used with toll=no? https://github.com/osmandapp/OsmAnd-resources/commit/75244cccb7a1d4079e8b4bd6e3e8329533b7e320

**Comment by aceman444** [comment]
Yeah, the wiki says the tagging is correct (toll_booth is also for "cameras above the road") and only Germany has an exception for now.
So the preprocessing solution seems fine, if that removes the barrier altogether, thanks.

**Comment by polarbearing** [comment]
Just for clarification, it is not important what Germany has an exception for, it is important what process the camera is tied to.

If you get €2.50 deducted from your account each time you pass a camera, it is a (vitual) toll booth. It the payment is separate, and the camera is jut for monitoring compliance, it is an enforcement device.
