### ISSUE TITLE
Voice settings are not intialized by default

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#2832]
Hi,

voice settings are not initialized by default. In the attached screenshot you can see that there is no radio button selected by default (after a setting up a fresh installation or clearing OsmAnd's  app settings).

Found with build OsmAndF~ 2.4.0#13396D.

![screenshot_2016-07-17-12-32-03](https://cloud.githubusercontent.com/assets/6921696/16907236/0f4837b6-4cc2-11e6-88f3-4ffde66b8518.png)

**Comment by sonora** [comment]
True. But user interaction may be required here to some extent (it depends on system capabilities and user preference), I am not sure it can be 100% automated. And how we have it now I think we ensure the user comes across this language selection dialog at least once to initialize it?

**Comment by vshcherb** [comment]
This is more or less ok
