### ISSUE TITLE
Different names of cities depending on use of regional or global map (offline maps)

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#2833]
Currently names of cities are displayed in local names on regional maps (zoomlevel >11) and names with display language ("my own language") on global map.
For a lot of situations this is quiet good, but in some cases this different language is irritating.

When I am traveling I often use paper maps additional to osmand for orientation. On these paper maps all names are in the language of the mentioned country.
This differs from the names of osmand on zoomlevels when global map is displayed. I often can't find a city due to a very different name on the other (of these both) maps!

My suggestion:
Please add a new option flag with the content:
For global maps use local names (like in regional maps) instead of names in display language (which is default).

This would help very much.
Thanks Peter

**Comment by vshcherb** [comment]
There is a solution which will work in other cases. You can select "Configure Map" language as a target language i.e. name:ru in Russia, for local map  name:ru will be missing and name will be shown instead
