### ISSUE TITLE
The new search function lists far-off places at top

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2835]
The new indexed search function (launched directly from the map screen) lists 1-2 far off places at the top of the search results  (in ascending order of distance).

The real nearby POIs are listed below these 1-2 places.

**Comment by raindropsfromsky** [comment]
![screenshot_20160718-163250](https://cloud.githubusercontent.com/assets/9047168/16914233/238a7666-4d0e-11e6-8830-2e8940a68f4a.png)
![screenshot_20160718-114635](https://cloud.githubusercontent.com/assets/9047168/16914230/1d4d84d2-4d0e-11e6-825f-f4c82cb311c9.png)

**Comment by vshcherb** [comment]
Work in progress
