### ISSUE TITLE
Should not display "height" on parkings

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#2836]
It seems that osmand is displaying the `height` of some `amenity=parking`, like here:

![](https://cloud.githubusercontent.com/assets/982338/16914799/8fb07dca-4cca-11e6-93c0-d282e7c839e2.png)

This object is https://www.openstreetmap.org/way/427351559

It would be better if it didn't display such information, since it only confuses the user (he can think that it could be the `housenumber` or `capacity`, for example).

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/3720ead09451acd6d0698b5be5a43f4312fcaead

**Comment by naoliv** [comment]
I never remember reporting such issues in OsmAnd-resources, sorry.
Thanks for the fix!

**Comment by sonora** [comment]
We have one consolidated issue list, so this is fine here.

**Comment by pebogufi** [comment]
...but it would be a good idea to add information of 
maxheight=
which can be connected to
barrier = height_restrictor
Drivers of camping cars and other big cars will love it !
Regards Peter
