### ISSUE TITLE
Should not penalize barrier=height_restrictor

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#2837]
Taking a look at https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#L336 it seems that `barrier=height_restrictor` implies some penalty in the routing, while it shouldn't (since a smaller car passing through a height restrictor won't have any kind of time penalty).

**Comment by vshcherb** [comment]
It is just 5 seconds, not much time and it seems to be reasonable time to slow down
