### ISSUE TITLE
OSM Live: enhancements (Update All button)

### ISSUE THREAD

**Issue by bitnapper** [osmandapp/Osmand#2838]
I'd like to propose a few enhancements for OSM Live. 

1. optional: Update on WiFi only and/or on power only

It would be nice if there were options for limiting live update to available WiFi connection and/or power supply but still be able to invoke it manually if necessary.

2. Update All button

If I feel the need to update my maps, I have to to it 16 times for each German state. I don't need that very often but it would be nice if there were a Update All button.

3. Update can't be stopped or paused

I'm often in regions with bad mobile reception. The update is supposed to start nightly but it seems that it starts in the morning. If I forget to stop it – which is only possible by killing the app from the android settings – it drains my battery and still doesn't update when the perception is bad. It would be great to be able to pause or skip the updates – even deactivating live update from osmand has no effect on an ongoing update.

And thanks for the great work.

**Comment by BoFFire** [comment]
Yep nice to have.

**Comment by vshcherb** [comment]
3. If you click on notification you will be moved to Downloads where you could cancel update.

**Comment by vshcherb** [comment]
I think the issue is fixed. Just disable/enable Live updates and it will suggest to download all live updates.

There was a possibility to add it to the end of list but that requires too much to scroll, I think enable/disable is obvious operation and fixes another use case when you turn off for a certain reason temporarily
