### ISSUE TITLE
Unable to reorder waypoints by dragging

### ISSUE THREAD

**Issue by Alootje** [osmandapp/Osmand#2839]
In version 2.3.4 I am able to reorder the waypoints by dragging the icon with the four horizontal bars. 
In version 2.3.5 this functionality doesn't work for me. I can only tick on the icon and move the waypoint up/down or remove it. Dragging the waypoints is much faster for me and therefore more convenient.

Steps how I create the route:
1. Select "navigation arrow"
2. Select 'From:' - 'Favorite...' - pick favorite
3. Select 'To:' - 'Favorite...' - pick favorite
4 Scroll over the map, long press a road, select "waypoint flag" (the one in the blue circle) - 'Add as first intermediate destination' or 'Add as last intermediate destination'
5. Select "navigation arrow" - 'Via' (the "orange waypoint flag"
6. Order waypoints in appropriate order by dragging the icon behind the waypoint (four horizontal bars) **<-- working in v.2.3.4, not working in v.2.3.5**

- Version of OsmAnd: 2.3.5
- Android phone (Samsung galaxy Note 3, N9005 and Samsung Galaxy S3)
- With offline maps offered within the OsmAnd app for download, using OsmAnd's in-app offline routing.
- Selected profile: motorbike

**Comment by vshcherb** [comment]
The is not reproducible and there were couple of changes in 2.4 (it is going to be released soon), which allow also to use actions instead of dragging. So it is definitely worth to test it on 2.4, I guess it is already fixed

**Comment by Alootje** [comment]
I did some more investigation. In v2.3.3 you can reorder the waypoints by holding my finger in the orange square below. In the latest nightly (v2.4.0#17960M) this area seems a lot smaller and inconsistent: sometimes I need to hold my finger on the bottom right corner of the 'four horizontal bars' icon, the next time in the center, etc. I've checked with both the dark and light theme, this makes no difference.

![dragging_waypoints](https://cloud.githubusercontent.com/assets/20538605/17522201/6dccc40a-5e56-11e6-9866-cd8da22ab5f3.jpg)
