### ISSUE TITLE
incorrect route calculation

### ISSUE THREAD

**Issue by okias** [osmandapp/Osmand#2840]
Setup:
Starting point: Czech Republic, Prague, Biskupcova 83
Destination: Prague, Radlická 355/133
Checkpoint for debugging: Prague, Radlická 3201/14 (it's on preferred shorter path).

OSMAnd Mode: The shortest route (in CZ: "Nejkratší cesta")
With checkpoint: 11,9 km 0:46 minutes (displays correct path)
Without checkpoint: 12,6 km 0:45 minutes

OSMAnd Mode: The shortest route DISABLED
With checkpoint: 11,9 km 0:46 minutes (displays correct path)
Without checkpoint: 11,9 km 0:47 minutes (displays correct path)

I checked openstreetmap editor, if there could be issue in map, but didn't found any. Path should be straightforward, so not sure, why OSMAnd chose longer path without reason?

With checkpoint, path is perfect (there shouldn't be any obstacles, at least as I know the path).
Without checkpoints, OSMAnd drags me into tunnel without reason.

**Comment by vshcherb** [comment]
Not reproducible any more, works fine.
