### ISSUE TITLE
RTL langages display

### ISSUE THREAD

**Issue by BoFFire** [osmandapp/Osmand#2841]
Hello,
We have pushed arabic translation during these 3 days #OSMAlgeria :) but we gave noticed that OSMAnd displays RTL (Right To Left) as if they are LTR (Left To Right) ones in the menus. Could you make it possible ?
- Can you introduce a concept of langage profile based on country profiles. For example in Algeria, Morocco, Tunisia ... we don't use indiens numbers, in Egypt they do. But we use Arabic numbers 1234567890 and not ١٢٣٤٥٦٧٨٩٠ This is a big problem for us we don't understand these indian numbers.

Thank you very much :)

**Comment by BoFFire** [comment]
Forgot to post a screenshot link about RTL displayed LTR : http://image.noelshack.com/fichiers/2016/29/1469011796-screenshot-2016-07-20-11-35-43-1.png

**Comment by vshcherb** [comment]
This doesn't look OsmAnd issue, looks more as Android OS.

**Comment by BoFFire** [comment]
Thank you, tonight I'll try it on the latest Android version. Mine is a little bit old in fact.
