### ISSUE TITLE
No longer possible to download map by zooming in/out on world map

### ISSUE THREAD

**Issue by hvdwolf** [osmandapp/Osmand#2842]
Since 2.3.5 and in the current 2.4 dev builds it is no longer possible to download a region/country by zooming in/out on the world map.

**Comment by xmd5a2** [comment]
What do you really mean? I can download maps from zoom 3 to 7 without problem.

**Comment by hvdwolf** [comment]
Peter B. and I can't. 
If I zoom on a piece of map that I do not have from level 1 to 17 I never get an option to download that map.
If I do that on a country that has both the country map and regional maps, it doesn't work either.

**Comment by hvdwolf** [comment]
I just found that the functionality has changed. Previously you had an automatic popup when hovering over a country. 
Now you have to tap the map.
But it does indeed work fine.
