### ISSUE TITLE
OSM Live (Beta) : No more updates July 2016

### ISSUE THREAD

**Issue by BoFFire** [osmandapp/Osmand#2847]
Hi,
As a Beta testers and OSM contibutors, we noticed that the Algerian Map has no more updates since July 16th. Is the service under maintainance ?
We use this dev version : http://image.noelshack.com/fichiers/2016/29/1469115878-screenshot-2016-07-21-16-37-20.png

Thank you for reading us.

**Comment by xmd5a2** [comment]
OSM Live depends on overpass which has some problems with 64bit IDs. We're working to bring it back to life.

**Comment by vshcherb** [comment]
Yes, the maps should be back tomorrow, now they've processed 16-18 July
