### ISSUE TITLE
Setting up development environment of Osmand app for ios in Xcode 

### ISSUE THREAD

**Issue by EoANishant** [osmandapp/Osmand#2848]
Objective : Setup development environment for iOS Application in Mac

I have Implemented the following commands to setup the repository :

```
> mkdir ~/bin
> PATH=~/bin:$PATH
> $ curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
> $ chmod a+x ~/bin/repo
> $ repo init -u git://github.com/osmandapp/OsmAnd-manifest.git -m jenkins_ios.xml 
> $ repo sync 
```

> Performed the following installations :

`sudo port install cmake`

installed cmake-3.6.0-Darwin-x86_64   ( A bit confused here if this is a right version but i went through one of the files where it had this line : cmake_minimum_required(VERSION 3.0 FATAL_ERROR) )

```
sudo port install imagemagick
sudo port install librsvg
```
 
`bash prepare.sh`

After this , the following started happening

Cloning into '/Volumes/WIN7VISTA/osmand/core/externals/qtbase-ios/upstream.original'... Checking out files: 100% (21117/21117), done. Preparing copy for patching...

It then failed after this point : 

Error Screenshot :

Error Description :
Checking out files: 100% (21117/21117), done.
Preparing copy for patching... Looking for 'qtbase-ios' patches... 
Found: 0-inflate-mkspecs.sh 
1-remove-simulator-suffix.patch 
2-separate-device-and-simulator-builds.patch 
3-use-libcpp.patch 
4-cxx11-atomic.patch Patching 'qtbase-ios' located at '/Volumes/WIN7VISTA/osmand/core/externals/qtbase-ios'...
 Applying 0-inflate-mkspecs.sh 
Applying 1-remove-simulator-suffix.patch patching file mkspecs/features/qt_functions.prf 
Applying 2-separate-device-and-simulator-builds.patch patching file mkspecs/macx-ios-clang-device/qmake.conf patching file mkspecs/macx-ios-clang-simulator/qmake.conf 
Applying 3-use-libcpp.patch patching file mkspecs/common/ios/qmake.conf Applying 4-cxx11-atomic.patch patching file src/corelib/arch/qatomic_cxx11.h CMake Error at utils/common.cmake:58 (message): 
Failed to build upstream "/Volumes/WIN7VISTA/osmand/build/../core/externals/qtbase-ios" for ios/clang/fat: No such file or directory 
Call Stack (most recent call first): qt.cmake:31 (build_upstream_ex) CMakeLists.txt:243 (include) -- Configuring incomplete, 
errors occurred! Failed to bake project files 'fat-ios-clang.xcode' (1) 
Failed to generate project for XCode, aborting...

CmakeOutput.log file:
The target system is: iOS -  - fat
The host system is: Darwin - 15.0.0 - x86_64

Can you please guide me how to get rid of this error ?
Can you  please tell me what other tools do i need to install to successfully complete my build ?

Thanks & Regards,

**Comment by vshcherb** [comment]
This is android project, though here is instruction
1. Macports: bash, bzip2, curl, git, ImageMagick +rsvg, librsvg, p7zip, python3*, wget 
2. CMake 3.0.2 minimum
3. PATH for all Macports things
4. xcode + ios sdk
5. google repo http://source.android.com/source/downloading.html#installing-repo
6. mkdir OsmAnd && cd OsmAnd
7. repo init -u https://github.com/osmandapp/OsmAnd-manifest
8. ./ios/prepare.sh
9. ./ios/prebuild-core.sh

**Comment by EoANishant** [comment]
I wanted to know the xcode version you are using. I tried the commands on
xcode 7+ and I was getting the error that I had posted. But when I tried
the same in xcode 6.1.1 , the build was successful and the app was loaded
in the xcode

On 22 Jul 2016 12:46 p.m., "vshcherb" <notifications@github.com> wrote:

This is android project, though here is instruction
1. Macports: bash, bzip2, curl, git, ImageMagick +rsvg, librsvg, p7zip,
python3*, wget
2. CMake 3.0.2 minimum
3. PATH for all Macports things
4. xcode + ios sdk
5. google repo
http://source.android.com/source/downloading.html#installing-repo
6. mkdir OsmAnd && cd OsmAnd
7. repo init -u https://github.com/osmandapp/OsmAnd-manifest
8. ./ios/prepare.sh
9. ./ios/prebuild-core.sh

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/osmandapp/Osmand/issues/2848#issuecomment-234470173>,
or mute the thread

**Comment by HimanshuDudhat** [comment]
@vshcherb I have tried with provided steps but getting build :

**build faied**
CompileC /Users/goldenmace/Downloads/cmake/Project/baked/fat-ios-clang.xcode/core/externals/giflib/OsmAnd_projects.build/Debug-iphoneos/gif_static.build/Objects-normal/arm64/gif_hash.o /Users/goldenmace/Downloads/cmake/Project/core/externals/giflib/upstream.patched/lib/gif_hash.c normal arm64 c com.apple.compilers.llvm.clang.1_0.compiler

Can you please assist me to resolve this issue
