### ISSUE TITLE
Map update for Poland

### ISSUE THREAD

**Issue by sledzik1984** [osmandapp/Osmand#2850]
Hi! 

Is there any possibility to delay update of Poland Maps? 
Many roads in Cracow are now set to vehicle=no because of World Youth Days (24.07 to 1.08). If you update maps on 1.08 people that use offline routing will have crappy routes until next update (1.09)

If you delay map creation for few days - tag vehicle=no will be removed and routes generated offline will be OK

**Comment by xmd5a2** [comment]
Unfortunately it is not possible because of OSM Live update process. All maps must be the first day of the month GMT 00:00. If not true then OSM Live will not work properly.

**Comment by sledzik1984** [comment]
Ok... so I have to revert many changesets 15 minutes before midnight :)
