### ISSUE TITLE
The route (purple) line goes zigzag along bends

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2854]
The route (purple) line goes zigzag along bends, as shown in screenshots.
![screenshot_20160721-160400](https://cloud.githubusercontent.com/assets/9047168/17083559/bd9f49da-51c2-11e6-857a-aa3442e6663c.png)
![screenshot_20160721-160351](https://cloud.githubusercontent.com/assets/9047168/17083560/bf5c3ec2-51c2-11e6-9cac-230598dddc64.png)

**Comment by polarbearing** [comment]
You should provide a link to the location in OSM, so the underlying data can be checked.

**Comment by vshcherb** [comment]
Looks weird, but that's possible, in case too many points are used underneath to make the road round. OsmAnd could simplify points differently for routing and rendering. 

Not planned to fix now.

**Comment by raindropsfromsky** [comment]
Hi Viktor,

The road does not have too many points. So this must be some other reason.
The problem is consistent across multiple nightlies, so you can cross-check it easily.

The problematic link is here: https://www.openstreetmap.org/edit#map=22/12.95691/77.70134

**Comment by polarbearing** [comment]
Again the junction has several issues in the OSM mapping, such as link roads drawn that do not exist and go across the median; and road crossing without joining node. 

As Bing is quite blurred there and there are no mapillary pictures on the junction, I cannot improve the data remotely. 

In you screenshots you are zoomed in extremely, so I think the problem is just cosmetic and does not affect usability.

**Comment by raindropsfromsky** [comment]
Yes, the layout is not ideal, but that's the exact replica of situation on ground. 

(We started with a badly engineered junction, and successive brainwaves from the traffic police has resulted in this one-of-a-kind layout. Given time, they may end with even more grotesque design.)

But all those problems you mentioned should not matter, so far routing is concerned...

**Comment by polarbearing** [comment]
But apparently routing is not affected, it is just a display artefact when you zoom in unnaturally deep.
