### ISSUE TITLE
The next turn indicator does not match the road

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2857]
In the screenshot below, the **next turn** indicator shows a left turn, but there is no such turn at 66m. 
![screenshot_20160708-191530](https://cloud.githubusercontent.com/assets/9047168/17083656/0ee3acbc-51c5-11e6-8351-dc6fd4f968c4.png)

**Comment by polarbearing** [comment]
Again without the OSM location this is hard to analyse. Indeed the link road has a left-turn-angle in the position of the traffic light. Would be important to compare against the real junction layout in sat image.

**Comment by sonora** [comment]
Mapping issue.

I guess we are talking http://www.openstreetmap.org/query?lat=12.97546&lon=77.60823#map=19/12.97522/77.60838. Here is how it is mapped, you will have to admit there is a pretty pronounced "left turn" there ... which does probably not reflect the real world  :)

(North is up on my screenshot, not on yours)

![screenshot](https://cloud.githubusercontent.com/assets/845735/17085153/de0c240e-51d1-11e6-9d1d-c6052586a92b.jpg)

**Comment by polarbearing** [comment]
Junction layout improved in OSM.

**Comment by sonora** [comment]
Good job, that should fix it!

But also an example of what I just talked about in my comment https://github.com/osmandapp/Osmand/issues/2855#issuecomment-234798477
