### ISSUE TITLE
Quick Search Stalls MyPlaces Display

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2858]
This is similar to #2804, but here the new QuickSearch triggers it, and affects the MyPlaces display:

Here is how to reproduce:

1. Fresh start of OsmAnd
2. Go to `Menu / My Places / My Tracks`. Note how swiftly the content is displayed.
3. No go back to the map screen and tap the new QuickSearch button. (No need to search anything, you can just leave again tapping "back")
4. Now again go to `Menu / My Places`. Note how on the MyFavorites tab already the progress indicator is on, and remains on indefinitely (or very long). Now go to the MyTracks tab.  Progress indicator remains on, and no results are displayed (other than the generic "Current recording track" entry.) 

Chances are we somehow have an issue with repeated use of Async tasks, and something is waiting for a previous execution which never finishes or runs extremely long.

In an unrelated but similar issue #2657 it had helped to cancel the long running Async task in the activity's onDestroy() (https://github.com/osmandapp/Osmand/commit/0927e79974fa574ce75a7011a86cb29a2915d7b1).

**Comment by crimean** [comment]
@sonora should be fixed. Please check it again.

**Comment by sonora** [comment]
Yes, fixed, thanks, good job!!
