### ISSUE TITLE
Osmand doesn't find street based on town name but only based on district name

### ISSUE THREAD

**Issue by Scindix** [osmandapp/Osmand#2859]
### Steps to reproduce
1. search "Von-Linde-Straße Erding" in OpenStreetMaps ( http://www.openstreetmap.org/search?query=Von-Linde-Stra%C3%9Fe%20Erding#map=19/48.31064/11.89505 )
You'll see the following entry: "Von-Linde-Straße, Sandgrubensiedlung, Altenerding, Erding, Landkreis Erding, Upper Bavaria, Free State of Bavaria, 85435, Germany", where "Erding" is the town and "Altenerding" the district.
2. While using offline maps search on Osmand for:
 * **Region:** Germany Bavaria
 * **City:** Erding
 * **Street:** Von-Linde-Straße

3. While also using offline maps search on Osmand for:
 * **Region:** Germany Bavaria
 * **City:** Altenerding
 * **Street:** Von-Linde-Straße

### Expected behaviour
Osmand should find the street wether you search for "Erding" or wether you search for "Altenerding".

### Actual behaviour
The street is only found when searching for "Altenerding". Which is very misleading because naturally you would search for Erding and all addresses I know only say "Erding", not "Altenerding". Erding is not a big city. OpenStreetMaps itself is able to find that street. why isn't Osmand able to? Also why isn't there a simple search field that works similar than the one openstreetmap.org (or Google Maps, Bing Maps, ...) has?

**Comment by vshcherb** [comment]
As I see it is part of this relation http://www.openstreetmap.org/relation/3884044 which takes precedence over http://www.openstreetmap.org/relation/934743.

In new search it is not a big problem cause city name could be omitted. Though this issue was recently fixed in Belgium with similar symptoms when town have such a big boundaries that shadowed neighbor villages.

**Comment by vshcherb** [comment]
This is the lowest boundary for Erding http://www.openstreetmap.org/relation/3884045#map=14/48.3040/11.9133&layers=N. So technically the categorization is correct. With new search it is not a big issue cause you can search just street by name without entering city.
