### ISSUE TITLE
Place search?

### ISSUE THREAD

**Issue by RicoZ-OSM** [osmandapp/Osmand#2860]
Didn't find an easy quick way to search for places (village, town, city). Typing place name and search won't work well because of https://github.com/osmandapp/Osmand/issues/2550

Implementing https://github.com/osmandapp/Osmand/issues/2181 would solve it but maybe as an intermediate step something to find places could be implemented.

**Comment by sonora** [comment]
Things are under way. For now simply use the address search under `Menu / Search /(Address tab)`. First button, type "b", select you Bavaria map, then type "vel". You should see the about half doze Velden listed for Bavaria in seconds. (Release version  is a little slow, nightly version much snappier.)

**Comment by RicoZ-OSM** [comment]
thanks, it was not exactly obvious how to got to the place without entering the whole address.

**Comment by sonora** [comment]
I know ... there is a button with a marker icon. top right of the address search screen. Using that displays what you have searched so far, no need to always specify street or house number. But the new search is under way .. :)
