### ISSUE TITLE
Allow user to set up a new route without interference

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2866]
When the user is trying to set up a new route, OsmAnd still remembers both start+end points for the last journey. 

As soon as the user defines one of these points, OsmAnd immediately jumps the gun, and uses the other point from the old route, and creates a new route. 

**Desired:** 
1. Let the user clear the points in one tap, and start afresh.
2. Let the user confirm that he has defined all points and waypoints (if any), and only then launch the routing.

**Comment by sonora** [comment]
let us consider in master issue #2765.
