### ISSUE TITLE
Searching by name not working

### ISSUE THREAD

**Issue by verdulo** [osmandapp/Osmand#2867]
The classic (not the new on-screen widget) search "by name" is not working in nightly builds. When I type a name (for example of the nearest city, or shop), OsmAnd finds them, but when the search is finished (the circle stops rotating) all results disappear.

**Comment by crimean** [comment]
@verdulo cannot reproduce. Can you confirm it with latest build?

**Comment by verdulo** [comment]
Yes I can confirm it: when I type for example "Bytom", I can get Bytom city and various streets and bus-stops with Bytom in name, but when the search is finished all names disappear; but when I start deleting letters to "byt" I can see 3 Wikipedia templates*; when only "b" letter remains, I can see all results! I've tried to use different app-keyboard, problem still occurs.

I deleted app-data, I started the program, changed the map-path, the app crashed (it's not important), I searched again, and now the program works. I've set (display, not map-language) language to Esperanto, now I cannot search again, when I change to Polish (Polish, not system default:polish) all works fine. German, still works fine.

Does it mean, that some phrase in Esperanto translation contains some kind of "illegal character" which disrupts searching?

* Will it be possible to not to index all Wikipedia templates and lists which are useless?

**Comment by xmd5a2** [comment]
@verdulo Wikipedia without junk articles is in the processing now.

**Comment by xmd5a2** [comment]
@verdulo Tried to reproduce case with "Bytom". No luck. All search results stay on screen after finish.

**Comment by verdulo** [comment]
The problem occurs when you change program language to ANY language not supported by the device (on my phone for example: Esperanto, Belorusian (latin script), Asturian (it's not working because of another bug)). The names with capital letters cannot be searched, for example there's POI with name "Abc", when I type "abc", or "a", or "Abc" I'll find nothing, but the POI would be visible when I type "bc", "b", or leave empty field. Android version 4.0.4.

**Comment by verdulo** [comment]
Why is this issue marked as 'Closed' if the problem still occurs (I checked on it 2 devices)?
