### ISSUE TITLE
[nice to have] Save time and altitude info for favourites and GPX points

### ISSUE THREAD

**Issue by ohhai** [osmandapp/OsmAnd#2869]
It's not possible for now to have timestamp and altitude data in favourites export or GPX tracks. Favourites miss both of that. GPX has time but doesn't export altitude and requires a bit more actions to use.
Is it possible to add this info? Altitude may be just skipped if it's not provided by GPS service for the current point.

My usecase is to have GPS track of a long trip without writing an continuous track to save battery and mark only an interesting points.
Favourites are more comfortable to use than GPX plugin, but they lack most of the info.

osmand+ 2.3.5, android 5.0

**Comment by vshcherb** [comment]
Thanks for request

**Comment by NilsSei** [comment]
Is there any update regarding the missing elevation data in the favourites / group export in the GPX file?

**Comment by partiemann** [comment]
A timestamp for each wpt in favourites would be very helpful. I use favourites to save interesting points while traveling, but later i can't see when i was there. This change would help me a lot.

**Comment by dmpr0** [comment]
We need to:
- Add timestamp for newly created favorites and waypoints, don't change timestamp after editing.
- Add altitude if it available for newly created favorite and waypoints

**Comment by pebogufi** [comment]
What about zwo buttons (add timestamp and altitude) which add theese data in current position within description ?

**Comment by NilsSei** [comment]
There is no way to extract elevation data from map data as first proposed input for elevation? (I can only see elevation data on hills (this would help to take over) and we have elevation lines inbetween a point)
