### ISSUE TITLE
Hearing traffic warnings twice, before and after passing them

### ISSUE THREAD

**Issue by Alootje** [osmandapp/Osmand#2873]
With the solution of #2843 speed cameras are announced before and after passing them.

As indicated by @sonora (https://github.com/osmandapp/Osmand/issues/2843#issuecomment-235240517):

> (1) Hearing traffic warnings twice, before and after passing them: May be an unrelated bug. Sounds like our code to filter only traffic warnings in "forward" direction is buggy, I think I may have seen similar symptoms in other situations.

**Comment by vshcherb** [comment]
As I saw @sonora already made an attempt to fix it, let's see if it works

**Comment by sonora** [comment]
With respect to this particular issue, I only have only done a little code clean-up so far. From what I see, we do not apply any directional analysis at all to any traffic warnings other than the speed limit alarm.  Will need to find some time to investigate.

**Comment by raindropsfromsky** [comment]
I was going to raise this doubt: I keep seeing two "You have arrived!" screens. Is this a related bug, or should I raise it separately?

**Comment by sonora** [comment]
Hello @Alootje , can I please ask you to verify this issue exists in the "real world", and also how it behaves:
- Do traffic warnings really display/announce **twice**, one before and once after he location in question?
- Is it consistent or sporadic?
- Or do they really only come once, but their positioning is imprecise so sometimes they may even appear **after** the location in question?

I have a hard time reproducing this, but have to admit I have very little experience using "routing-by-GPX".

Thx - Hardy

**Comment by Alootje** [comment]
Hello @sonora, I tried to test it in the neighborhood, however the speed cameras that are present, weren't on the map in Osm(And), while they are present on http://frink.bplaced.de/blitzer/#map=15/51.431/5.4678.
I plan to test this next Sunday when I take the motorbike to the location where I heard the warning twice during route simulation*.

*: for info; the route simulation passed by this speedcam (going from north to south): http://frink.bplaced.de/blitzer/#map=16/50.657/5.6459

**Comment by sonora** [comment]
Thank you!  If you use GPX routing a lot, you may like what I have implemented here #2894, now when you save GPX routes they should contain the road reference, street name, and destination tags which are then also re-used in instructions and voice prompts if you use the GPX file again for routing.

Regarding this issue: I have tried to test it today, and my impression is I am not really sure how to fix this. the issue may less be that we have no directional analysis if the location of a traffic warning is in front of or behind you, but rather that our code for the "off route" case (which we now also  apply when using GPX routing), will merely detect if a traffic alarm is "in the vicinity", but I find no precise way to locate it with reference to your own position. I may not have research well enough, though, all i am saying is I find no quick fix (and also no good way to reproduce / test).

**Comment by sonora** [comment]
I have tried to reproduce this now in many "real world" test drives, and I have to say I **can not**. I think we do not have the issue which is described here, that you hear traffic warnings twice in the off-route case.

We may perhaps have some issue with positioning precision, as I describe above, but I am not convinced this is significant at all, and it would take a lot more research to pin-point it before we can make this an issue clear enough to be fixed, so I think I will close this one for now.

**Comment by Alootje** [comment]
Today I had the chance to test it in the "real world", I only heard the traffic warning once, so it is OK.
