### ISSUE TITLE
Incorrect traveling time on GPX routes

### ISSUE THREAD

**Issue by Alootje** [osmandapp/Osmand#2874]
A difference in traveling time is noticed when navigating a 'OsmAnd created route' and a GPX file, see comparison below. According Google Maps the traveling time is 22 minutes, therefore the 'OsmAnd created route' seems to be the correct traveling time and the GPX route is way too optimistic.

V2.3.5_Route_created_in_OsmAnd:

- 17.6 km
- 24 min

V2.3.5_GPX_from_above (v2.3.5):

- 17.6 km
- 13 min

V2.4.0_4202_Route_created_in_OsmAnd:

- 17.5 km
- 23 min

V2.4.0_4202_GPX_from_above (V2.4.0_4202):

- 17.5 km
- 12 min

Additional information:
- Android phone (Samsung galaxy S3)
- With offline maps offered within the OsmAnd app for download, using OsmAnd's in-app offline routing.
- Selected profile: motorbike (all occasions)

**Comment by scaidermern** [comment]
Are these really GPX _routes_ and not GPX _tracks_?

**Comment by vshcherb** [comment]
Can you please share partially what is inside GPX file (rtept, trkpt, ...) and can you please say how do you calculate the route (all options you select)

**Comment by Alootje** [comment]
@scaidermern, @vshcherb; don't know if it is a GPX route or track? The GPX, created within OsmAnd (changed .gpx to .txt to be able to attach it):
[_2016-07-28_Travel_Time.txt](https://github.com/osmandapp/Osmand/files/388794/_2016-07-28_Travel_Time.txt).
Looking at the amount of points under <trkseg>I assume this is a track? I don't know if OsmAnd can save it as a route (if that would be a better option)?

Steps how I create the route:

1. Select "navigation arrow"
2. Select 'From:' - 'Favorite...' - pick favorite
3. Select 'To:' - 'Favorite...' - pick another favorite
4. Scroll over the map, long press a road, select "waypoint flag" (the one in the blue circle) - 'Add as first intermediate destination' or 'Add as last intermediate destination'
5. Select "navigation arrow" - 'Route details' - 'Save'

Route calculation options:

- Profile: car
- Navigation service: OsmAnd
- Fastest route: selected
- Avoid: nothing selected
- Weight limit: -
- Height limit: -
- Avoid roads: none

GPX navigation options:

- Calculate OsmAnd route for first and last routesegment selected, everything else turned off.

**Comment by sonora** [comment]
I am rather convinced this is fixed when tackling (a) and (b) in the 3rd post in #2906.

**Comment by sonora** [comment]
Should be fixed via https://github.com/osmandapp/Osmand/commit/15d9ea2e756db2d32b6dd30fcc5cc412b85efddb, please test.

**Comment by Alootje** [comment]
Tested an the GPX traveling time is much closer to the OsmAnd route traveling time:

Created a route in OsmAnd v2.4.0#17960M (with OsmAnds off-line routing engine):

- 77.5 Km
- 1u42min

v2.4.0#17960M_GPX_from__route_above:

- 77.5 Km
- 1u36min

Tested the same GPX in v2.3.5 (with latest maps, same as used in v2.4.0#17960M):

- 76.7 Km
- 26min
