### ISSUE TITLE
Thinking of new Basemaps concepts

### ISSUE THREAD

**Issue by BoFFire** [osmandapp/Osmand#2875]
Hi,
This is not a bug. I was thinking that a 186 MB map of the World is really huge to download. This may be ridiculous but a truth in some countries like in Africa startinf from Algeria to South Africa.
Can we generate our own base maps ?
Example : Special basemap for the Maghreb Region and an another for Africa (only level 2 boundaries).
The aim is to have a lightweight basemap.

Best regards,
Athmane MOKRAOUI.

**Comment by vshcherb** [comment]
In case you want to use for yourself please  use http://builder.osmand.net/basemap/World_basemap_mini_2.obf

**Comment by BoFFire** [comment]
Thank you vshcherb :)
