### ISSUE TITLE
Search UI: Support Basic Search Syntax

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2878]
Looks like in our new search UI the BLANK separator (" ") functions as an OR operator, which is fine.

I guess it would not be very complicated now to also support some basic useful other search syntax, like 
- AND: to force an AND operation for search terms
- the quotation marks, as in "best western" instead of best western, to force OsmAnd to search for exactly this occurrence of words. (Use case example: So far searching for best western returns all sorts of hits with occurrence of the term "best" alone, but it is hard to e.g. find only hits for the hotel chain "Best Western")

**Comment by vshcherb** [comment]
1. AND is assumed by default though it doesn't exclude other results
2. "Best Western"  precise matching also changes priority and it should be first result, though it doesn't exclude other results starting with Best 

All these 2 requests quite hard to implement and they don't fit regular schema.

**Comment by sonora** [comment]
Ok, would have thought it was easy to implement, not worth it then, maybe. Complete full text search without pre-selecting any category is a lot slower than after pre-selecting a category (like "Accomodation"), so maybe that is the better workaround for many use cases.

**Comment by sonora** [comment]
Let us merge this to #3086.
