### ISSUE TITLE
Show the nearest POI when long-tap

### ISSUE THREAD

**Issue by jalil1408** [osmandapp/Osmand#2880]
Hello, when I long-tap on the map, OsmAnd looks up the address and show it but it does not show the information about the nearest POI! 
I used MapFactor navigator for almost 3 years and currently I quit it and toggled to OsmAnd cause MapFacor's maps are not updated frequently as OsmAnd's maps are. But the first thing I faced is I cannot got the nearest POI information, MapFactor does!
Another thing is that OsmAnd doesn't offer the user to change the view when navigating.
Finally I really like your application, please keep it up.

**Comment by sonora** [comment]
Similar to #1862.

**Comment by vshcherb** [comment]
Yes very similar, though for searching nearest pois, you could click long tap now and select Search near here. That functionality will be improved by release with new search and will fit more to search POI by any category

I will close that issue in favor #1862
