### ISSUE TITLE
The "You are off the route for xx m" announcement has two bugs

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2883]
The "You are off the route for xx m" announcement has two problems:

1. It does not alert immediately. Typically, it says "You have been off the route for the last 350 m". This distance is practically as good as getting lost in terms of urban trips.
2. When the "Settings > Navigation settings > Turn screen on" option is selected, OsmAnd fails to warn the user entirely. As and when the user turns on the screen, OsmAnd tells him casually that he has been off the route!

**Desired:** 
 1. It should warn the user as soon as a turn is missed. Often the user can simply apply brakes, go in reverse (or take a U-turn) and follow the right turn. No need to re-route.
 2. The warning should not be suppressed when the screen is turned off.

**Comment by sonora** [comment]
Current strategy is this:

Immediately when OsmAnd detects you have left the calculated route (there are a number of criteria, like travelling direction and projected distance to the route, but with regular GPS reception mostly you can assume if the distance from the route exceeds 100m), a route-recalculation is started. If your route is not extremely long, or you have not deviated more than 3 times already, it will finish within seconds and you will hear "Route recalculated, in 50m turn right" etc.

Only if for some reason no new route could be found until you have deviated from the old route by at least 350m, you will hear "You have deviated from the route", so this is a fallback strategy only, not the norm.

I have no clue why the prompt would be suppressed while the screen is off, will have to try to reproduce.

**Comment by sonora** [comment]
I have driven for about 1 hour today with OsmAnd navigation set to a very long route, and my phone put in sleep mode. I have positively heard the prompt in question several times, so I cannot reproduce (2) . If I missed any specific action how to reproduce, please post here. Thx!

**Comment by polarbearing** [comment]
> or you have not deviated more than 3 times already

what is the purpose of this criterion, with which consequences?

**Comment by sonora** [comment]
I have not looked at the code lately, but think we have an algorithm where when a deviation from a calculated route is first detected, we only re-calculate the first portion (20km or so) , hence essentially guide you back onto somewhere on the originally calculated route. Only after that  has been done repeatedly (I think 3 times) without you re-entering the route, the COMPLETE route is re-calculated from scratch. This is unrelated to this issue, I only mentioned it because of its impact on timing, which again has impact on the prompt this issue is about.

**Comment by polarbearing** [comment]
Thanks, it definitely helps to know when observing off-route behaviour in various issues.

**Comment by raindropsfromsky** [comment]
I tested this again several times, by setting fictitious destinations along
my 17 km long journey home.

Each time I selected a spot that braved off to left or right (we drive on
the left). In each case OsmAnd just waited till the bus overshot the
expected torn by ~100m and then simply informed me "route recalculated".
From that point, the new route became the de facto route, and this route
adjustment continued for each missed opportunity (generally to take a
U-turn, but sometimes by taking a genuine alternative route.)

Never did it say anything about being off the route.

Is this good? I am not sure. In a human situation, my wife would shriek or
something. So why not have an alarm buzz?

BTW my route was along a dual carriageway, but if the road is a single road
(as in rural areas), OsmAnd should immediately tell me to slow down and
turn around!

**Comment by sonora** [comment]
Behaves as desired: The notification "Route recalculated ..." informs you that you are off the route, and the second half of the very same prompt tells you what to best do now. As I said, the more generic "You have been off the route" prompt is only a fallback if OsmAnd cannot give you better instructions yet.  (3rd option would be your wife shrieking, probably even one stage less informative :-) )

**Comment by raindropsfromsky** [comment]
Yes, I agree. It's best not to cause the driver to swerve wildly (and here
I am speaking from experience)

**Comment by sonora** [comment]
Yes, on a more general note: De-cluttered voice prompts is key for any good navigation system. When you have missed turns, you may be in a stress situation already, so any tool "bombarding" you with instructions  (particularly with limited guidance what to do) is not helpful. It is best to continue, and wait/get few but solid instructions what to do next. Anything causing you to "hit the breaks" is definitely not desired functionality we want to go for. :)

**Comment by raindropsfromsky** [comment]
Wow! Why can't all wives be like OsmAnd? So gentle and understanding!
