### ISSUE TITLE
Easier way to get POI details

### ISSUE THREAD

**Issue by HubMiner** [osmandapp/Osmand#2884]
I am trying to get a info on POI spotted on a map (not found through search).

Currently, I have to (1) in advance, create search covering all POI, (2) long hold the found POI and run all-POI search around that point, (3) click on found POI, and I can finally can see description (if any).

I would like to be able to quick touch the screen once (not drag), and see the description pop up.

**Comment by sonora** [comment]
Unless I misunderstand, this is a duplicate of #1862, see my latest comments there?

**Comment by vshcherb** [comment]
Definitely a duplicate in that sense, cause we want to upgrade to clickable items on the map.
