### ISSUE TITLE
Add Directional Analysis for STOP Sign

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2885]
If during a navigation the route turns from a major road onto a minor road, and in the **opposite** direction the minor road has a stop sign at the intersection with the major road, we do detect and announce that stop sign as being on our route although it does not apply.

According to http://wiki.openstreetmap.org/wiki/Tag:highway%3Dstop, stop signs are often not mapped with `direction=` tagging, their directional applicability can rather  `usually be deduced by finding the shorter distance to the priority intersection`.

We need to:
(1) Add code to perform the directional applicability analysis based on if a stop line is before or after the nearest intersection
(2) May in addition evaluate any `direction=forward/backward`, if stop sign is tagged with it
(3) May want to evaluate `stop=minor/all`, if tagged

**Comment by osMatt** [comment]
See also related issue https://github.com/osmandapp/Osmand/issues/2246.

**Comment by vshcherb** [comment]
Sounds quite difficult and not clear how much OSM data provides useful information about stops.

**Comment by sonora** [comment]
Yes, needs more research. From what I see, most stop signs are within say 30 or so meters of an intersection. So I guess the majority of the issues seen in practice would be fixed by analyzing if a stop sign on your route  is **before** or **after** the intersection node (suppress in the latter case.)

**Comment by jfburke3** [comment]
Would it be "easy enough" to be able to parse the direction=forward/backward tags?  I include those on (almost) every stop sign I add.  Of course, that doesn't mean everyone else does, and OsmAnd wouldn't be able to give proper notifications where those tags aren't included, but if you can add that ability, it might help encourage mappers to use the direction tag.

**Comment by sonora** [comment]
Yes, forward/backward parsing support is needed here, like we already have for maxspeed, and still also need for e.g. `destination:` (and probably a few other tags). But in this case I think the OSM wiki I quote above states that the norm is to deduct from the placement relative to an intersection, so I guess we need to support that, too.

**Comment by polarbearing** [comment]
#2968 destination:forward/backward

**Comment by sonora** [comment]
Did some preliminary work here, but needs more work and refinement: https://github.com/osmandapp/Osmand/commit/94706ec8dc3766ea056b7f4212144ef6b0564483.

**Comment by aceman444** [comment]
This also applies to highway=give_way and highway=traffic_signals . Also, there are penalties in OsmAnd for passing these objects so properly ignoring them should be a win for better routing. Or at least more precise estimated time calculation.

**Comment by osmvermesser** [comment]
in germany osm-forum current is a big discussion about mappen stop-sign.

https://forum.openstreetmap.org/viewtopic.php?id=58801

Jan

**Comment by TimMagee** [comment]
I strongly recommend that we support direction:forward, direction:backward, and stop=all on stop signs. These are the BEST way to indicate the direction of the stop sign. Other methods (like seeing which end of the road its on) seem more like hacks then anything else.

**Comment by kennykb** [comment]
Why is this just 'Nice to Have' and not 'Observed'? There are tens of thousands of STOP signs with direction=*, and we still get noisy warnings when approaching them from the irrelevant direction.

**Comment by TimMagee** [comment]
The constant reminders when there is no relevant stop sign make this feature pretty much useless.

**Comment by jfburke3** [comment]
I agree that this should be implemented.

As a side note, I (almost always) include a relevant direction modifier when I add a stop sign.  I use either stop=all, direction=forward, or direction=backward.  I avoid the stop=major and stop=minor modifiers, since their meaning will completely change if someone changes the road's classification.

**Comment by sonora** [comment]
Looking at https://taginfo.openstreetmap.org/tags/?key=highway&value=stop#combinations, what is worth supporting is primarily `direction=forward` and `direction=backward`. Plus: We should likely try to advocate that kind of mapping.

- `stop=all` should automatically be ok, as these nodes are to be placed right on the conflicting node and are always applicable.
- `stop=minor` is rather hard to support, but also has rather low usage. The same is true for `direction=N/E/S/W`, etc.
- I have now added code (`isStopApplicable()`) to support `direction=forward` and `direction=backward`, but this currently seems to not work ok, likely a bug on my side. @xmd5a2 Leonid, could you maybe verify if we correctly include the direction=* for highway=stop nodes in our offline maps?

Final question is what we do with the many highway=stop which have other or no additional tagging. I suggest to always treat them as alarms and rather risk false positives than masking them out and creating false negatives, which may create a safety issue?

**Comment by sonora** [comment]
Let us try this: It is a bit experimental but I have added a distance analysis to the end points of the route object for all STOPs for which no direction analysis was detected. This should mask most STOPs which are pointing in the wrong direction because they would normally/often be closer to the beginning of a route object than to its end.

But this needs testing(!). So when you test and report results, please take a note if you are reporting for
- `highway=stop` also tagged with `direction=forward/backward`,
- or `highway=stop` and other or no additional tags.

**Comment by kennykb** [comment]
@sonora - I hope that you're treating highway=stop ON an intersection with no additional tagging as an "all-way stop"?

**Comment by aceman444** [comment]
@sonora thanks! Please do not forget the same for  highway=give_way and highway=traffic_signals .

**Comment by osmvermesser** [comment]
@sonora - where it is possible to test?

Jan

**Comment by sonora** [comment]
Can be tested with our latest nightly build. For highway=give_way and highway=traffic_signals please open a new issue explaining the significance, these are not traffic warnings hence need different treatment.

**Comment by sonora** [comment]
@vshcherb From my testing this feature now works as intended and is ready for inclusion in the next minor release so we seem some broader feedback.
