### ISSUE TITLE
At the end of journey, I see multiple "You have arrived!" cards

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2886]
At the end of a journey, sometimes I cannot respond to the "You have arrived!" card. 
If I open my mobile to check the status, I see multiple cards.
I have to close them all by tapping on the **x** button.

Probably the reason is, as I move near the destination, the GPS senses multiple times that I have gone out of the area and again come in. Each time OsmAnd pops up a new card.

**Comment by vshcherb** [comment]
Was not able to reproduce it yet. May be requires more testing

**Comment by Barrocas** [comment]
Sometimes I also get multiple arrival cards, but I have stopped and
stayed still, so they all poped out at the same time, it did not
depend on gps position variations.

It happens occasionally.

-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by raindropsfromsky** [comment]
Ah!

Then I have two cents to add: When we stop moving, the GPS still senses
some small, random movement.

If we were trailing at high speed, and stop suddenly, the movement is more.

Could this be a reason?

**Comment by Barrocas** [comment]
I'm usually in a car, already slowing down before I arrive, and even
before I've stopped, all the multiple arrival cards are already there.

-- 
Cumprimentos,
D.er Hugo Barrocas
