### ISSUE TITLE
How to mark azebra crossing that involves a passage through the median also?

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2888]
The OSM [wiki](http://wiki.openstreetmap.org/wiki/Tag:highway%3Dcrossing) prescribes that to depict a zebra crossing, we have to insert a point on a road and tag it as **Highway=crossing**.

But I am not sure whether this fits the OsmAnd way of working:

In a typical zebra crossing, a pedestrian can cross from one side of the road to the other side of the road. 

But in OsmAnd, routes are not set like that: In the "Walk" mode, the route is not aligned to one side of the road to mimic a pedestrian walking on a footpath on one side of the road. Rather, OsmAnd shows a purple line right in the middle of the road (just like **Car** mode), as if the person is walking in the middle of a road. So IMHO when OsmAnd finds a POI on a road, with a **Highway=crossing** tag, it won't work. 

Secondly, this idea of inserting a dot does not work with a dual carriageway, because in OSM, both halves of the dual carriageway are shown separately, with a physical separation between them. In real world, this space could be just plain ground or a barrier (RCC slab, or a garden patch). In this context, a zebra crossing across a dual carriage means the median is cut there, to let the pedestrians cross it. That idea is better expressed with a link across the two halves and name it "crossing".

Well, I tried this method of mapping a zebra crossing ([link](https://www.openstreetmap.org/edit#map=22/12.97302/77.61693)). But OsmAnd does not recognize it.

So the question is, how should we mark a zebra crossing across a dual carriageway, which cuts across the median as well?

**Comment by polarbearing** [comment]
> how should we mark a zebra crossing across a dual carriageway

with a short highway=footway connecting the two crossing nodes. If there are indeed zebra stripes, giving the peds special rights, the appropriate crossing tags should be added to the joining nodes. If it is just a break in the median barrier, allowing the eds to cross while waiting for the road traffic, I prefer no crossing tagging at all.

> as if the person is walking in the middle of a road

A sidewalk that is attached to a road without physical separation is modelled in OSM by attaching "sidewalk=both|right|left" to the road.

**Comment by raindropsfromsky** [comment]
Not really: OsmAnd should respect all alternative tags, which in this case it did not.
In that sense it is very much a bug.

IINW OsmAnd team converts the variants in tags to one standard tag while creating the OSM updates, and then OsmAnd acts on that tag. (For example, pharmacy/chemist/apothekery etc, )  

So in this case also, it should have done the same. But the problem is, wiki recommends a point-solution rather than a link-based solution!

**Comment by sonora** [comment]
Could be, have not researched to detail. If one of the other members catches this and finds an action item, they can always re-open.
