### ISSUE TITLE
OsmAnd does not turn the screen on when I arrive at the destination

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2892]
I have set the navigation settings to allow OsmAnd to turn on the screen for 5 seconds.

While OsmAnd turns on the screen for all voice guidance events (turns), it does not turn the screen on when I arrive at the destination. As a result, it shows the arrival card only when I manually turn on the device.

**Desired:** OsmAnd should turn on the screen when we arrive at the destination, and keep it open for our action. (If we have set it to any time-limit, such as 5 seconds, it should be ignored, and extended to some reasonable time, such as 1 minute, or to the default turn-off time for the device.

**Comment by vshcherb** [comment]
At the end it should be voice notification "You have arrived at your destination", it happens earlier but that's not a big issue. When you already arrived, you could turn the screen on.

**Comment by raindropsfromsky** [comment]
There are two issues here:

1. The announcement of arrival is often before the actual point is reached. Further, at this point, if the destination is not familiar, the user will have to check where the checkered flag is on the map. Therefore it is essential to turn on the screen (not optional). Then why not make the user do it manually? Let OsmAnd turn on the screen!

 2. Soon after arriving, often the very next task is to locate a nearby parking. This feature is offered by the arrival card. But the card is not available till the user turns on the screen manually. Why? OsmAnd can turn on the screen and present the card to him. With a single tap, he can drive on to the parking.

Note also that turning on the screen manually is often not convenient and quick, especially when the mobile is held in a mount. Tapping the screen is far easier.

Kindly reconsider re-opening the issue. Thanks in advance!
