### ISSUE TITLE
The History tab in Quick Search has "Share" and "Delete" features, but they are hidden

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2893]
The new indexed search (directly accessible from the map screen) has a **History** tab now. 

These entries can be shared or deleted, but it all appears only after long-tapping on any one entry.
This is accidental discovery, and most users will miss this feature.

**Desired:** Please provide a better affordance for these features.

**Comment by raindropsfromsky** [comment]
For example, provide an **Overflow** button (three dots, vertically stacked).

**Comment by vshcherb** [comment]
For now we don't want to put too much functions that could interfere with simple UX.

**Comment by sonora** [comment]
I tend to agree, from all user feedback I have scanned lately, users tend to prefer simple UX over complex, and the minority thinking different is swift enough to find some more camouflaged features.

**Comment by sonora** [comment]
Looks like no action planned here for now (?).
