### ISSUE TITLE
The "Turn the screen on" feature also turns off the screen unexpectedly!

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2895]
If the "Turn the screen on" function is active, OsmAnd turns the screen off even if I want to do something else with the map (for example, add a waypoint, or force the route to a specified path (by either adding intermediate destinations, or avoiding the alternative routes.)  

This happens even when I have turned on the screen (by pressing the **Power** button).

**Desired:** When the user has turned on the screen, OsmAnd should not turn off the screen.

**Comment by jfburke3** [comment]
+1

**Comment by oliv3r** [comment]
Duplicated by #4525
