### ISSUE TITLE
add intent filter to open mime type "application/gpx+xml "

### ISSUE THREAD

**Issue by RicoZ-OSM** [osmandapp/Osmand#2896]
When opening a GPX track from email (k9mail) it sends the following intent (caught by IntentIntercept):
`
ACTION:android.intent.action.VIEW
DATA:content://com.fsck.k9.attachmentprovider/7701a9c7-0d95-4477-b64a-f84a96d19f24/81/VIEW
TYPE:application/gpx+xml

FLAGS:
FLAG_ACTIVITY_CLEAR_WHEN_TASK_RESET
FLAG_RECEIVER_FOREGROUND
`

Hopefully catching this and similar would enable direct sharing of gpx tracks from many more apps.

**Comment by RicoZ-OSM** [comment]
RunnerUp shares gpx tracks in a pretty interesting way:
`
ACTION:android.intent.action.SEND
DATA:null
TYPE:application/vnd.garmin.workout+json

FLAGS:
FLAG_ACTIVITY_CLEAR_WHEN_TASK_RESET
FLAG_ACTIVITY_FORWARD_RESULT
FLAG_RECEIVER_REGISTERED_ONLY_BEFORE_BOOT
FLAG_ACTIVITY_PREVIOUS_IS_TOP
FLAG_RECEIVER_FOREGROUND

EXTRAS:
EXTRA: 1:

Class:android.net.Uri$StringUri
Key:android.intent.extra.STREAM
Value:content://org.runnerup.activity.provider/gpx/7/activity.gpx
`

**Comment by vshcherb** [comment]
```
<intent-filter>
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.DEFAULT"/>
				<data android:mimeType="application/gpx+xml" />
			</intent-filter>
```
Is already in place so it should be handled.

**Comment by rgh36167** [comment]
Thanks, I notice it has been added on May 31st ( https://github.com/osmandapp/Osmand/commit/1e255fa95a501b7ac3710d5d55ef9f9ff43a2cc2#diff-a3c8269ddedbd15469a9520e44980d8f ) and not yet in my version. Will test some nightly when I get at it.
