### ISSUE TITLE
[Feature Request]:  Please integrate routsearch by train

### ISSUE THREAD

**Issue by Mannshoch** [osmandapp/Osmand#2897]
Maybe you could use [Transportr](https://github.com/grote/Transportr) for that.

**Comment by vshcherb** [comment]
They use http://www.navitia.io/ which is a paid service. We better focus on OSM data providers

**Comment by Mannshoch** [comment]
Seems they take money for the use of the server only, they are an Open Source Project.
https://github.com/CanalTP/navitia

They are like you. Osmand take also money if we get the Osmand form Google/Itunes/amazone.

**Comment by vshcherb** [comment]
They are very different, they build API and we build a product. Even if the API is completely free, it is not clear of License issues. 
So it is very weird that users provide GTFS files themselves it could violate some data licenses. In that case we hope to see something closer to OSM. Non-OSM data will have correlation problems with OSM data.

**Comment by Mannshoch** [comment]
Interesting Point. Thanks for the explanation.

The point why I wish a Integration of public transport is because I configured a device for a friend of mine also with Osmand. He changed back to Google Maps because of the great feature which include Public Transport in routeplaning.
