### ISSUE TITLE
QuickSearch still crashes

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2898]
Just for the record: Quick search still often crashes, release-critical. Slightly different variants of error logs, but all same root cause I guess:
[exception.log.txt](https://github.com/osmandapp/Osmand/files/400948/exception.log.txt)
[exception.log.txt](https://github.com/osmandapp/Osmand/files/400961/exception.log.txt)

**Comment by vshcherb** [comment]
It is not clear if it is related to QuickSearch, for crashes it says that is related to reverse geocoding.   And it is not clear how to reproduce it to understand the problem. Please specify more information what do you do. Looks like you click on element during route calculation.

**Comment by sonora** [comment]
This comes up on different occasions, but always when playing with Quick Search. No route being calculated or even having been calculated ever in that session previously.  Procedure:
- Fresh start of OsmAnd
- Wait till the map shows, then tap the QuickSearch widget.
- Go to the Categories tab and select a category. Then tap on a search hit to get the entry displayed on the map.
- Then, on the map, tap on the Quick Search widget again, go to the Categories tab again, and repeat the procedure (normally choosing a different category, and selecting a different entry).

On most, but not on all of my devices, it does not take more than 2-3 tries to reproduce this.

Mostly, the search will run for a second or so, and before displaying any results Osmand will crash. On some occasions, the search will very quickly finish, and the "Find more button" is displayed. The crash will then usually come up after tapping "Find more" once, or sometimes repeatedly (never see any search results displayed any more).

Leonid had actually posted an error log here: https://github.com/osmandapp/Osmand/issues/2831#issuecomment-234018013. The error log was not related to that issue, it rather looks like he saw the very same thing I am posting here, so it looks like he also sees the issue.

Cold potentially be related to map versions, or to Android versions. The devices I see this on run Android 4.0 and 4.4.2. Map versions are mostly the June 1 generation, often as old as March 4. I also see this on devices with older maps. But I have an Android 5.1.1 with March 4 maps and have not yet seen the issue on that one.

**Comment by sonora** [comment]
The behavior has changed, I have not seen the crash in about 2 days, could it be that we catch the exception now?

Now the exact procedure I outline in the comment above does not seem to lead to a crash any more, but rather after a second of the progress indicator spinning, the search terminates with no search hits displayed, and the "Find more" button is shown.

Whatever you do from then on, (go to the map screen and back , or change the search criteria), the QuickSearch will always just result in the screen without results and with the "Find more" button. This can only be re-set by a fresh app start. (Think this started around 8-10).

**Comment by vshcherb** [comment]
Alexey let me know that he wrapped exception, though may it was not the best solution.

**Comment by vshcherb** [comment]
I tested today deeply but didn't manage to reproduce, may be it is because "Looking up address" is quite quick on my phone 1-2 seconds.

I found the fastest way to select different entry, "Select entry -> click hardware Back -> and select another entry". @sonora  could you please confirm 2 things:
1) this quicker interaction also crashes or leads to undefined behavior
2) if you want till address is found in the context menu, then crash is not reproducible

**Comment by sonora** [comment]
@vshcherb: Yes, looks like I can confirm both that
1. this quicker way also leads to the same bug
2. the issue does not seem to come up after the reverse geocoding lookup has finished. I guess this is the reason why I cannot reproduce on faster high end devices, but all my mid-grade and more dated devices show the issue all the time.

**Comment by vshcherb** [comment]
So it looks as I posted in the beginning, it is not related to quick search, but it is related to concurrent reverse geocoding operation.

**Comment by sonora** [comment]
True. And I just notice this issue is probably the same as #2804. I can also re-produce with our old search. Only the old search seems to recover once geocoding lookup finishes or something, while the new search currently seems to become stalled forever for that app session.

**Comment by vshcherb** [comment]
Completely refactored way how to work with files, now should function fine. Though requires quite deep testing (enabling all layers that could use files : Map, Quick Search, Old Search, Transport, POI, Geocoding, Routing). And possibly some tests with downloading new files and disabling old files. 
The good thing now there should be no conflicts and everything should function concurrently and even use less resources.

**Comment by sonora** [comment]
Victor, intense testing for like an hour now - no issue yet. Looks like this is a quantum leap for OsmAnd!

**Comment by vshcherb** [comment]
Thanks, it will be in the release next week 2.4.4
