### ISSUE TITLE
Landscape screen orientation setting allows one rotation 

### ISSUE THREAD

**Issue by agilob** [osmandapp/Osmand#2901]
When selecting screen orientation to landscape application does not rotate when device is up-side-down.

1. Select Landscape screen orientation
2. Rotate device to position [top|bottom]-(charging socket on left side)
3. Rotate device to position [bottom|top]-(charging socket on right side)

I would expect the map to rotate to my current rotation, not stay up-side-down.

OsmAnd 2.3.5

**Comment by agilob** [comment]
thanks @tmct :)

**Comment by tmct** [comment]
No problem :)
