### ISSUE TITLE
Improvement in Quick Search GUI, to show the filtered search results on map 

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2902]
Often we want to go to a particular type of POI (e.g. McDonalds, Starbucks, Dominos..) But we are not exactly looking for the nearest joint. Sometimes we prefer to go a particular locality.

In the following example, I have selected restaurant with "Lassi" in it. OsmAnd shows a few matches, but it shows only distances, no localities.

![which restaurant to go to](https://cloud.githubusercontent.com/assets/9047168/17394275/df5be05c-5a45-11e6-95c6-10e718f884df.png)

So the best workaround is to see them all on the map, and then make our choice.

But there are two problems here:
**Bug#1:** the button says "Show cafe and restaurant on the map". But it does not show **all** cafes and restaurants: It shows only the POIs that are there in the filtered list. Therefore it is more accurate if the button is labeled "Show search results on map", or if the text is omitted altogether, and replaced with an icon. The old icon (a point-marker on a half-folded map sheet) is good enough for this purpose.

 **Bug#2:** In the above case, OsmAnd shows only two POIs on screen. It should show all four results. In general, all the POIs in the filtered list must be shown on the map. The map must zoom and pan to show all results at once. The POI orange disks must be full size at that zoom.

**Comment by sonora** [comment]
I think this is deprecated and works now.
