### ISSUE TITLE
Bug with writing or re-reading our own GPX route files

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2906]
- Calculate a route with OsmAnd's offline router (take fixed start and end point to rule ot GPS fix variations)
- then save the route as GPX file
- then re-read the file again via "route by GPX"
- then save again under a different name (2nd generation file)

The resulting 2nd generation route file significantly differs from the original one (different number of turn points, different distances between turns, turns in different locations, different time estimates between turns).

The differences are only in the rte section of the file, not in the trk section.

In the 2nd generation, not all points are shifted or newly introduced, some remain unchanged. Looks like upon re-reading an OsmAnd-router generated GPX file, some turns somehow get processed/consolidated: The originally saved file may e.g. contain 40 rtep points, the re-read-then-re-saved 2nd gen file may only have as few as 24.

Possibly also cross-connected to Issue #2874 (time/offset tagging also seems affected).

**Comment by sonora** [comment]
Preliminary findings:
- Looks like the issue affects route points with TurnType.C, where we record no turn and turn-angle tag. There may be some exception when reading these so they are skipped..
- Also weird that Lat/Lon coordinates for some route (never track) points differ very slightly after re-reading, maybe starting 3-4 digits after the decimal point. There may be some additional precision issue.

**Comment by sonora** [comment]
The issue that points were shifted in repeated saves resulted from us inserting the start point (again?). From my research the start point was already present twice in the very first save list to be saved, hence see this commit: https://github.com/osmandapp/Osmand/commit/0edd82d158ecd54b44876695fccdbc2f82da21d8. 

If we need the code I commented out, then we need to make sure we do not insert duplicate points, and also re-adjust all offset values, which caused the turn location shift portion of this issue.

**Comment by sonora** [comment]
Remainng problem seems this:

We call `removeUnnecessaryGoAhead(` and `addMissingTurnsToRoute(` in `RouteCalculationResult`, even for OsmAnd generated GPX routes. (Not sure if this makes sense.)

But this resets most time tags, and then `updateListDistanceTime(` seems buggy, it does not re-set the time tags (no ref to time at all, I think).

**Comment by vshcherb** [comment]
Please keep in mind, that is very generic algorithm to support other GPX files, so it is not wise to change much cause it could break backward compatibility with external GPX files. 
We didn't implement fully featured read of GPX file, we make it more or less compatible with Cloudmade (dead format). Though it had always the least priority and we didn't work on a separate function reading which of course would be proper implementation.

Please keep in mind providing turn-lanes, speedcams, ... is a dead end for GPX files, IMHO. We could of course much speed up the calculation by using intermediate points from GPX file and that would be proper implementation I think

**Comment by sonora** [comment]
Ok, good hint, thanks! I think I will limit the fix to
- Fixing (b): Set the time tags correctly in `updateListDistanceTime(`
- Perhaps investigate if it makes sense to somehow call `removeUnnecessaryGoAhead(` and  `addMissingTurnsToRoute(`  before saving (and not just after reading) an OsmAnd-generated GPX route file in the first place, so we have no inconsistencies between a 1st and a 2nd save?

If we make no other changes, these 3 should be the low-risk actions here?.

**Comment by vshcherb** [comment]
Saving is not a big concern to change cause the most important is to save geometry (track) and rtept (as points where driver needs to make decision). I don't see a problem of inconsistence 1st and 2nd save. 
I think removeUnnecessaryGoAhead (same addMissingTurnsToRoute) is very tricky function cause many routers produce unnecessary goaheads, though  for OsmAnd router it doesn't make any sense to remove (if we save only speakable warnings).

**Comment by vshcherb** [comment]
Again proper fix is to distinguish OsmAnd GPX and non-OsmAnd GPX (keep backward compatible is the best).  For OsmAnd GPX we should use and give only prompts at rtept and don't try to analyze geometry of the track.

**Comment by sonora** [comment]
Exactly, I arrive at the same conclusion:

We will save OsmAnd's own routes as they are first produced (not subsequently remove any straights or add any turns), but leave things as is for all non-OsmAnd generated GPX files (except fix re-adding the correct time tags in `updateListDistanceTime(`  which seems a bug)

**Comment by sonora** [comment]
PS: This issue now tested to positively fix the problems with OsmAnd-generated route files, their (also repeated) saving and re-reading (without changing start or destination points).

Side finding from testing: Looks like when you e.g. change the start point and use OsmAnd's setting "Calculate first and last route segment (onto the GPX)", travel times indicated then are still wrong, both for OsmAnd- and non-OsmAnd generated GPX route files. Similar but different issue.
