### ISSUE TITLE
Wrong german translation for poi description internet_access:fee=no

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#2907]
The german translation for poi description internet_access:fee=no
Is currently 
"Internetzugang kostenpflichtig"
but it should be
"Internetzugang kostenfrei"
Which is just the opposite !
Please make a correction.
Regards Peter

**Comment by sonora** [comment]
Fixed. Thanks, well spotted. In fact looks like the translations for access_fee=yes and =no were swapped.

**Comment by pebogufi** [comment]
Tested with 2.4.0#17901M.
Now ok, thanks, Peter
