### ISSUE TITLE
Settings in Configure map - Transport are reverted to default when turning Transport off

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#2908]
Overlay/underlay works differently: it saves options state. Also previously these settings were placed in "Map rendering" option group and were permanent.

**Comment by bjohas** [comment]
I agree that this would be good to have.

I've made a similar proposal here, regarding POIs https://github.com/osmandapp/Osmand/issues/2626 - the comment thread makes the distinction between "switches that have a single option (such as the map type in overlay map)" and "switches that have multiple options". There seem to be technical issues in implementing this too - but I do agree that it would be better for options to be remembered in the "off" state.

Just as a side note: What's changed seems to be the addition of the on/off button.
Unless I'm mistaken, the settings still work the same as before if you ignore the on/off button, but just tap on the left instead. In particular they are still specific to the profile selected (which is important to me). So what's new is that you can now turn them off as a group, but can't turn them back on as a group (remembering the previous selection). Please correct me if I've got this wrong!
