### ISSUE TITLE
On context menu, indicate how to zoom in

### ISSUE THREAD

**Issue by bjohas** [osmandapp/Osmand#2909]
Searching sometimes drops you into a zoomed-out map state. It's then tricky to zoom in. If you close the tray to get the zoom buttons, the search result disappears. If you zoom in with gestures, you may loose the point.

Is there a reason why the map zoom can't always be maintained when searching (unless there's multiple results, needing zooming out).

Alternatively (but perhaps much harder to do) can the search results stay irrespective of the tray being open?

**Comment by sonora** [comment]
Simply tapping on the point title in the context menu zooms you in. I guess we could add an icon to make this clearer.

The initial map zoom is chosen so that you see where the point is in relation to you own position, so if it is far away, the map will be further zoomed out than if you view a nearby location.

**Comment by bjohas** [comment]
Ah right - yes, that works well. I'd tried all sorts of other things to zoom it, but that hadn't occurred to me!

**Comment by sonora** [comment]
Implementation suggestion: I guess we could just place an orange `map_my_location.png` crosshair icon somewhere next to or below the title of the map content menu while the map is not zoomed in, this would greatly improve the discoverability of "how to easily zoom in".

**Comment by sonora** [comment]
Maybe display the POI title in the context menu as an orange button while it is not zoomed in?   (Just like we display each "Nearby Wikipedia article")

**Comment by sonora** [comment]
The goal of this issue was to optically indicate to users that you can zoom in to displayed search results etc. by tapping on the content menu's point title. Not  sure we achieved this, really?

**Comment by vshcherb** [comment]
If user pulls the context menu up or tap on it, it behaves consistently by zooming in to the location. If user pulls the context menu down, the map zoom out to original location. If user taps on the map it keeps the shown zoom. 
This is more consistent behavior and makes the feature discoverability of tapping not important cause it is logically equal to pulling up. Before it was inconsistent which created a different UI flow.

**Comment by sonora** [comment]
Yes, we know how it works. But I have watched many users searching for something, tapping a search hit, then seeing the hit's marker on the map, but zoomed out really far, and the target's context menu is visible.

From what I observe, 4 out of 5 average OsmAnd users are not aware **they can simply tap on the context menu title to zoom in to the found point.** Instead, almost all clumsily start pinch-zooming the map, accidentally maybe even tapping on another point or POI on the map in the process, lose their search hit, etc.

**Comment by vshcherb** [comment]
> they can simply tap on the context menu title to zoom in to the found point.
This is extra functionality, today they can simply drag to zoom in as well. The functionality is duplicated, so the chances are doubled. Anyway there is no space for another indication.
