### ISSUE TITLE
(feature) hide overground objects

### ISSUE THREAD

**Issue by bjohas** [osmandapp/Osmand#2910]
Under "Configure map > Hide" there's an option to "Hide underground objects". The request is to add an option "hide overground objects", offering the reverse.

Hide overground objects would hide all objects without level tag or 0 or positive level tag. If possible nodes connected  to an object with negative level tag should remain visible.

**Comment by vshcherb** [comment]
It is for @xmd5a2 to decide

**Comment by xmd5a2** [comment]
Done. But please note that this option hides all objects without layer tag (by default layer=0) and with layer=-1(-2,-3...). There is some junk in maps at this point of view but it can be useful to observe subway transitions. https://github.com/osmandapp/OsmAnd-resources/commit/e946d1c508c4323b3aea2f357a57c95c38e02c03

**Comment by bjohas** [comment]
@xmd5a2 - do you mean "hides all objects ... with layer=1(2,3...)" ?

Many thanks!

**Comment by bjohas** [comment]
Works great, thanks!
