### ISSUE TITLE
Show road/street names inside them, as it is done in Google Maps

### ISSUE THREAD

**Issue by KOLANICH** [osmandapp/Osmand#2911]
When maximum zoom and vector maps are used they are not visible.

**Comment by vshcherb** [comment]
Planned for new rendering

**Comment by littlehelper** [comment]
Please, why not tagging such feature requests or ideas with 'planned for future release' or simular? It would be easier to identify and separate these issues from other closd ones.
Why do you close such planned feature request issues?

**Comment by sonora** [comment]
Please note that this is an issue tracker, not a roadmap documentation  ... ;)
I hope you can understand that it is not helpful for us to have long-range plans marked as "open" here for extended periods, where they overlap with short-range criticalities.
