### ISSUE TITLE
Add waze plugin to share and get info about traffic troubles (accidents, hits, repairing, traffic cops ambushes, etc)

### ISSUE THREAD

**Issue by KOLANICH** [osmandapp/Osmand#2914]
At least Google Maps and Yandex.Navigator have this feature.

**Comment by clessley** [comment]
@KOLANICH You can import a layer to show live traffic from Google Maps when on network data. See here: [OsmAnd + Google Maps Live Traffic](http://gfist.com/index.php/en-us/blog/37-osmand-google-traffic). If you love Waze, use Waze.

**Comment by sonora** [comment]
@KOLANICH, @vshcherb This is cool, thanks!!

**Comment by KOLANICH** [comment]
@clessley, I know this trick, but this is just a raster layer, so no routing taking this in account and no contribution. Under Waze support I mean fully-functional support.
