### ISSUE TITLE
Are Google maps supported?

### ISSUE THREAD

**Issue by KOLANICH** [osmandapp/Osmand#2916]
>Secondly, there are licensing issues. Although OsmAnd cannot be distributed with Google Maps data, you can, however, add the tile source manually, if you know the tile source URL. 

1 Why do you care about this? It is user's responsibility not to break license, not osmand's.
2 What do you mean under "tile source url"?

**Comment by homersimpsons** [comment]
Try to use online map add-on and set up Google map

**Comment by KOLANICH** [comment]
I see no pref to add Google Maps as underlay

**Comment by homersimpsons** [comment]
You can manually add one, but I don't get the tile syntax, then I can't help you for now
