### ISSUE TITLE
Lanes ahead (fork lanes) shown instead of turn lanes

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#2918]
Simulations in NB 06-Aug-2016 23:30 / map Brandenburg/Germany/Aug-01 

Großer Stern in Berlin is now correctly tagged as non-roundabout, and turn:lanes have been added before the 1 Aug map files were created. 

![screenshot_2016-08-07-00-29-59](https://cloud.githubusercontent.com/assets/8266355/17459469/d9202720-5c39-11e6-8b76-03bcc662d8c1.png)

turn:lanes are shown correctly inside the circular traffic as above, but before exiting, on https://www.openstreetmap.org/way/61820398 which has 5 turn:lanes, 7 straight arrows are shown which symbolise the lanes ahead in way 30806884 (4 lanes) and way 4400154 (3 lanes)

![screenshot_2016-08-07-00-34-38](https://cloud.githubusercontent.com/assets/8266355/17459464/c17edd1e-5c39-11e6-8816-155bb7d21bf0.png)

One idea might be that the angle of the through lanes continuation is a bit too sharp into the circular shape so they are not recognised as valid? However on the road they are painted straight, so that is what I have to map.

**Comment by vshcherb** [comment]
Fixed

**Comment by polarbearing** [comment]
Confirming fix on Grosser Stern, also for the opposite direction. (Simulation on v11-Aug-2016 11:23)
