### ISSUE TITLE
distinguish fork lanes from turn:lanes

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#2919]
OsmAnd analyses lanes ahead in forking situations and shows the recommendation to keep left or right in the turn:lane widget. However since it is the same widget, and the layout looks quite similar, the two cases are hard to distinguish. Users may wonder why there are more turn:lanes displayed than the road has lanes, because they are fork lanes instead. An example is in #2918.

Thus I propose to draw fork lanes differently. A possibility is shown below as a mockup, where all arrows are oblique but not bent. As the second example shows, based on the count of the leaving and the target lanes, one lane could be shown splitting.

![fork_lanes](https://cloud.githubusercontent.com/assets/8266355/17459582/a8d7177c-5c3e-11e6-8e88-d6cedfb73cc8.png)
![fork_lanes1](https://cloud.githubusercontent.com/assets/8266355/17459583/ad582714-5c3e-11e6-8d04-50864d2cd998.png)

**Comment by vshcherb** [comment]
Still in these cases turn:lanes is leading if we can't distinguish it in OSM data, it doesn't make much sense to suppose what we don't know i.e. layout of how lanes are split. I'm afraid this could lead to other mistakes

**Comment by polarbearing** [comment]
Well the splitting is just a partial issue. However, isn't the logic that when a+b=c lanes are leaving the fork, and c lanes are approaching, we have no split. If c-1 are approaching, we have a split of approaching lane number a ? We cannot have a split in a further lane since it would cross over its neighbour. 

Showing the splitting or not, I think that the forking should be better distinguished from the turn:lanes.

**Comment by vshcherb** [comment]
Unfortunately I don't see two separate issues and I see only one #2918. Cause all turns have turn:lanes everything should be drawn as expected. There are many very confusing situation when turn:lanes are not drawn and it is advised to draw them, so I think this issue is quite irrelevant.

**Comment by polarbearing** [comment]
Seems I need to clarify myself:
- #2918 is a bug report, where a 5-lane turn:lane scheme (through|through|through;slight_right|slight_right|slight_right) is mapped and should be shown instead of the 7 lanes ahead.
- this issue #2919 is a feature request that asks for a different display of "lanes ahead" in general. E.g. I have [this situation](https://www.openstreetmap.org/way/44152838#map=18/52.51001/13.52466) where a 4-lane road splits into 2 that go into the tunnel and 2 stay above. As there is no junction, and no arrows painted on the asphalt, it would help the user to understand why a lane recommendation is shown with no junction in sight. 
- the splitting case is a further refinement of feature request #2919, where from the middle lane I can go in both directions.

**Comment by vshcherb** [comment]
#2919 wouldn't happen and it is not needed if turn:lanes are present (except bug #2918).
