### ISSUE TITLE
OsmAnd+ 2.4 regression: OsmAnd's voice does not annouce speed cams anymore

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#2921]
OsmAnd's voice does not announce speed cams anymore since release OsmAnd+ 2.4.

**Comment by sonora** [comment]
Norbert, can you please elaborate?
- is the warning sign displayed?
- have you checked if the setting is on or off?
- can you specify a location to test? With what map generation date?

Thx - Hardy

**Comment by polarbearing** [comment]
Is 2.4 released now? Anyway, I was observing intermittent problems with the announcements in the nightlies. Cams are neither shown nor announced. Started around the time #2803 and 
#2843 were created. 

Nightly 06-Aug-2016 23:30, map Germany/Brandenburg Aug 01. Just simulated a route along a camera I was missing recently:

Frankfurter Allee, device node 326847472, mapped off-road as a member of an enforcement relation. The camera itself has a highway=speed_camera as well. 
Used to be announced correctly a while ago, I think earlier this year, while the node is off-road since 2014. No sign, no announcement. Not shown in dashboard.

Trying A100 tunnel. Simulated start programmed, dashboard shows 2 cameras, 763m, 1.91km. Both devices shown and announced. 
Nodes node 27543311 and 27540883, device mapped incorrectly on the road despite an enforcement relation.

**Comment by Norbert80** [comment]
@sonora 

Hi Hardy,

I am not sure if the warning sign has been displayed.

Voice announcement of speed cams is checked.

Below I have attached a screenshot with the position of the speed cam.


Regards,
Norbert
![screenshot_2016-08-07-21-40-19](https://cloud.githubusercontent.com/assets/6921696/17464830/4729ac88-5ce8-11e6-87bc-7133f2a96bb4.png)

**Comment by Norbert80** [comment]
@polarbearing 

>> Is 2.4 released now?
It is distributed for beta testers over PlayStore now.

**Comment by vshcherb** [comment]
It is about to increase the audience, so far it is released for 1%. This week will be about to find and fix maximum regression issues and next week to make final release.

**Comment by Norbert80** [comment]
@sonora: Are you able to reproduce this bug? Do you need additional information?

**Comment by sonora** [comment]
Sorry, I can't, it is illegal in many countries I work and live in. (And please test things like this in the real world, there may be artifacts in a simulation.)

From going through my notes of recent weeks, I have not willingly changed any code just affecting speed cams, all the issues which were fixed should have affected all warnings alike (railroad crossings, pedestrian crossing, etc.).
- So it would really help to know if really only speed cams are affected or not?
- Are you on the route when the warning seems missing (turn arrow shown), or off route (gray dashed arrow shown)?
- Another thing which bogs me is that some people seem to report things work, others say they don't. If this keeps manifesting, we may have to collect data how those which work are mapped vs. those which do not.

**Comment by Norbert80** [comment]
@sonora 
My "complaint" is a result from real navigation. Not a simulation. Btw... simulation seems to be no more available in recent builds although the development plug-in is enabled.

I remember that THIS speed cam was announced with older builds.

As soon as I drive this road again I will provide additional information.

**Comment by Norbert80** [comment]
@sonora:

Other user experience similar problems:
https://groups.google.com/forum/#!msg/osmand/a8lFGYgix-8/lKFGyQJKBQAJ;context-place=forum/osmand

**Comment by sonora** [comment]
So it looks like we are strictly talking about speed cams mapped in an enforcement relation, correct?

Is this the same Issue as #2803 , where Leonid says that mapping was not (yet) supported, or are we talking something different here?

**Comment by Norbert80** [comment]
I am not very familiar with different ways of mapping speed cams. But I am sure that this on was announced with older OsmAnd builds.

![bildschirmfoto vom 2016-08-09 22 05 48](https://cloud.githubusercontent.com/assets/6921696/17531747/8a916114-5e7d-11e6-9e15-d7006fef8e55.png)

**Comment by sonora** [comment]
Please link ccords from OSM, your screenshot contains no useful info to identify the object or for debugging.

**Comment by Norbert80** [comment]
@sonora:
https://www.openstreetmap.org/node/1853252710

Thanks for investigation!

**Comment by sonora** [comment]
@xmd5a2 Leonid, can you confirm this is not supported mapping-wise? Anything we can do about it? -Thx

**Comment by xmd5a2** [comment]
@sonora I've checked obf with this speed camera: it is absent in routing data. 
But if I move it to node which is part of road then camera becomes available for routing. Looks like off-road cameras not supported for routing (or broken)

**Comment by vshcherb** [comment]
Sorry, didn't understand original request, it is a known issue! Routing data doesn't support any single points! Though I hope there could be workaround found

**Comment by vshcherb** [comment]
these speed camera should be available as poi and shown on the map even with road only maps

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-tools/commit/1e74ef9984ad843bdd5c226b9c4d1efacb49def0

**Comment by polarbearing** [comment]
Just to confirm my simulation with a real drive, my Frankfurter Allee case was not shown as well. 

An enforcement relation has the 'from' and 'to' nodes on the route. Is that what your OsmAndMapCreator commit was fixing now?

**Comment by vshcherb** [comment]
Maps should be regenerated, the issue is fixed

**Comment by polarbearing** [comment]
Confirming fix with the September maps for my case.
