### ISSUE TITLE
Routing fails to take specific road

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#2922]
NB 06-Aug-2016 23:30, Brandenburg/Germany map Aug 01.  

Fails to create car route using way [140656356](https://www.openstreetmap.org/way/140656356). Experienced while driving, confirmed in simulation, it takes a 14km diversion instead of 50m through.  Simulation was narrowed to take only this way, which was last changed in 2015 and never had a blocking access.  OSRM [routes through](https://www.openstreetmap.org/directions?engine=osrm_car&route=52.45092%2C13.69116%3B52.45192%2C13.69171#map=19/52.45142/13.69143).

The road has maxheight=3.7, however in my car profile Height limit was unset, it is now set to '-' (cannot get unset anymore, tried limit 2m, same problem). 
No road block entered. 
I fixed one of the man_made=bridge not having a layer tag - but that would not block the road underneath?

There is a little purple "MM" rendered on the road, not sure what that means?

![screenshot_2016-08-07-22-12-23](https://cloud.githubusercontent.com/assets/8266355/17465143/fcb33f68-5cef-11e6-8d47-13f0f9e6da20.png)

**Comment by raindropsfromsky** [comment]
I have many such observations. But instead of "failure to take a certain route", I see it as random routing, based on other observations. I have multiple screenshots. Should I post them all like the above, or enclose as a zip, or directly send them as email to Viktor (the bug assignee)?

**Comment by raindropsfromsky** [comment]
P.S. I am not sure what "2.4" label means. Does that refer to Gingerbread (Android 2.4)?
Then I am at wrong place: I am using Oxygen 3.0.2 based on Android Marshmallow 6.0.1

**Comment by homersimpsons** [comment]
2.4 refer to  the next version of osmand

**Comment by vshcherb** [comment]
Fixed

**Comment by polarbearing** [comment]
Confirming fix in 09-Aug-2016 09:36. Not sure was the related commit was...

**Comment by raindropsfromsky** [comment]
So should I post my screenshots or not?

**Comment by polarbearing** [comment]
@raindropsfromsky - apparently this was a maxheight issue that has been fixed, so you should test your cases with a new nighty build first, and analyse if there are any maxheight tags on your affected roads. If not, you should open a new ticket and analyse the tagging of the affected road.

**Comment by raindropsfromsky** [comment]
Oh OK.

This road does not have any cross beams, or low bridge, so the "max height"
tag cannot be a factor at all.

Will raise a separate bug. Thanks!
