### ISSUE TITLE
weather map

### ISSUE THREAD

**Issue by Mannshoch** [osmandapp/OsmAnd#2923]
I found in the Plugin Online-Map the hint for using also wether maps as an Overlay but I was not able to find a Map for that. the Map "Cloudmade" seem to not show any wether data.

Maybe helpful: 
https://opendata.swiss/en/organization/bundesamt-fur-meteorologie-und-klimatologie-meteoschweiz
http://openweathermap.org/

**Comment by edrex** [comment]
I'm interested in this. In EE.UU my preferred data source is NWS:

 - [NDFD](https://www.weather.gov/mdl/ndfd_home)
 - Web viewer: [National Weather Service - Graphical Forecast](https://digital.weather.gov/)
 - [WMS details: National Digital Forecast Database Web Map Service](https://digital.weather.gov/staticpages/mapservices.php)

There are several products (daily high, daily low) with a required date parameter (VT).

So I think for NWS at least this boils down to needing support for selecting a date parm. Added #8064

**Comment by Mannshoch** [comment]
I like this Map. May a bit out of scope. But the appearance is amazing.
https://earth.nullschool.net/

**Comment by Mannshoch** [comment]
Se also:
https://windy.com
https://github.com/windycom/

**Comment by Max1234-Ita** [comment]
Hi there, I stumbled into this issue just by chance.

I guess the weather feature has been implemented in 2023, v. 4.4 or so. 
If this is the case, then shouldn't this ticket be closed?

Cheers,
Max
