### ISSUE TITLE
Sharing a route from the Route Info screen shares useless file

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2925]
I guess the idea is that we create a plain vanilla gpx file and share it? What I actually receive when sharing an OsmAnd GPX route file e.g. via Bluetooth or WiFi Direct is the gpx file
- being wrapped in `<html>` tags, with also `<head>` content="text/html;charset=UTF-8" being added
- all lines starting with `<br>` tags.

This result cannot be re-used by OsmAnd, nor viewed well in any kind of browser or other reader, so I guess this is a bug?

(Code ref: XmlSerializer in GPXUtilities.writeGpx)

**Comment by vshcherb** [comment]
Please check commit, now it should be good and customizable

**Comment by sonora** [comment]
@vshcherb : Hello Victor, will have to review the 2 commits in detail.

From a quick test on my standard device, it now looks like this (both for sharing the favorites list or a route):
<img width="135" alt="screenshot_sharing_50" src="https://cloud.githubusercontent.com/assets/845735/17615212/f1676c9e-606c-11e6-85d7-e9a936d78c53.png">
Probably not a big issue, but here may be too many MIME types offered which do not work, because trying out the options results as follows:

- [ ]  "Add to Firefox": Produces Toast: "No link found in this Share", nothing else.

- [X] "Bluetooth": Works, sends the favorites.gpx or route.gpx files all right!

- [ ] "Convert to PDF" produces a message "Unfortunately Adobe Reader has stopped". (Please note that the "Route/Print" option works -has always- and produces a file called "webview.pdf" all right)

- [ ] "Messages" produces an SMS which just says "Favorites/Route shared via OsmAnd", but no other content.  (I have no EMail account configured on that device, so, using "Mail" produces the same as using "Messages"). Ideally, with "EMail" we would try to attach favorites/route.gpx, while in a SMS we would convert the gpx-file-context to a string any include, so it can be copy/pasted on the receiving device?

- [ ] "Share via barcode" provides a message "Could not encode a barcode from the data provided"

- [ ] "WiFi Direct" produces a status message in the Android notification bar saying "Failed to generate data" (both for favs and for route). Not sure yet if this is an OsmAnd issue or a system issue, as "Bluetooth" works as desired.

**Comment by vshcherb** [comment]
Well yes text/plain could have too many acceptors and not all of the works. It works nicely only with GMail. It generates html with instructions (very simplified) + gpx route file (which is the most valuable I think).

**Comment by sonora** [comment]
Ok, so we leave it like this, I guess, right?

PS: Double-checked option "WiFi Direct": This works in my setup when sharing something from a file manager, but OsmAnd creates referenced issue and "Sending failed" toast. Not sure why.
