### ISSUE TITLE
The "Avoid Road" control works with off-road points, but applies to nearby road

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2930]
OsmAnd allows user to long-press any point that is NOT on any road, and select the **Avoid road** option. While it places the marker at the off-road spot, it actually blocks the nearest road. If we tap on that point, a card pops up, which mentions the nearby road.

**Desired:** OsmAnd should provide the feature only if the user long-taps **on** the road.

**Comment by littlehelper** [comment]
If I want to avoid a specific road, then in most cases I am standing just in front of a "road closed / construction" barrier. To tap exactly on the corresponding road - even tabbing long - is not that easy in some situations.
I would recommend that Osmand should snap the avoid marker to the nearest road or ask for which nearby road the avoidance should be applied if it is not clear.

**Comment by sonora** [comment]
Equivalent to #1696, let us merge into #2765.
