### ISSUE TITLE
Quick Search: POI incorrect order

### ISSUE THREAD

**Issue by franco999** [osmandapp/Osmand#2934]
When using the function "Search nearby" with the Quick Search (without GPS) shows me first POIs further and to near the bottom of the list which are closer.

I'm using OsmAnd 2.4.0#17999M (2016-08-11)

![1](https://cloud.githubusercontent.com/assets/12088580/17591761/e5927ac4-5fb5-11e6-8ba7-dd913b7a0328.png)
![2](https://cloud.githubusercontent.com/assets/12088580/17591764/e84135e4-5fb5-11e6-8ca8-23a9b7654556.png)

**Comment by vshcherb** [comment]
Distance should be displayed from the selected point now.
