### ISSUE TITLE
Show town names in search results

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/OsmAnd#2937]
While searching for a bakery I get a lot of results. But I don't know in which town the shown bakerys are. In my opinion it would be great to show the town names in the search list too.
![screenshot_2016-08-12-07-33-50](https://cloud.githubusercontent.com/assets/11144987/17613644/c0013282-605f-11e6-8384-2d4919ea59f2.png)

Using #18025 

Greetings Simon

**Comment by vshcherb** [comment]
That's true and we also were thinking about that feature, unfortunately precise location could take up to 3-5 seconds per item. We can support only the distance from center of the closest big city, but that doesn't look so cool.

**Comment by jf-simon** [comment]
ok 3-5 seconds are too long.But what about the city infos in the poi itself? I guess you read the openinghours out of it. sure not all poi have a city tag.

**Comment by vshcherb** [comment]
We don't want to make maps significantly (i.e. > 5-10%), though I will investigate if it is possible to meet all criterias

**Comment by homersimpsons** [comment]
You could preprocess city for poi in Osmand map creator? 
A show on map feature would help too

**Comment by scaidermern** [comment]
Should be merged with #2993.
