### ISSUE TITLE
[FEATURE REQUEST] Use int_name in directions

### ISSUE THREAD

**Issue by Almorca** [osmandapp/Osmand#2938]
I use Osmand in spanish language. When I search in a country with no spanish language Osmand show name with this algorithm

If name:XY exists
  show name:XY / name
else
  show name

![screenshot_20160812-101607](https://cloud.githubusercontent.com/assets/498083/17616612/2b4a1caa-6076-11e6-84b4-df728c430b14.png)

My propose is modify algorithm to

If name:XY exists
  show name:XY / name
If name_int exists
  show name_int / name
else
  show name

int_name is a key very used in non-latin countries where is difficult for us understand names. You can confirm this with this query run in Overpass turbo over a non-latin area.

/*
This query looks for nodes, ways and relations 
with the given keys.
Choose your region by bounding box and hit the Run button above!
*/
[out:json][timeout:25];
// gather results
(
  // query searches for: “place“(city, town, village, hamlet) & “int_name=*”
  node["place"]["int_name"]({{bbox}});
  way["place"]["int_name"]({{bbox}});
  relation["place"]["int_name"]({{bbox}});
);
// print results
out body;
>;
out skel qt;

There are more comments in https://groups.google.com/forum/#!topic/osmand/KnbY7v6Pai0

**Comment by vshcherb** [comment]
We use name:en for this kind of searches which in most of the cases gives same result. New quick search works better with 2-3 names.
