### ISSUE TITLE
Problem with Greece map. name:en don't show

### ISSUE THREAD

**Issue by Almorca** [osmandapp/Osmand#2939]
I use Osmand 2.3.5 in spanish with 1st Agust Greece map. According with #2938 I could find a place using name:es and when this key doesn't exist with name:en but I can't find Salamina node.

![salamina](https://cloud.githubusercontent.com/assets/498083/17621402/5c323326-6093-11e6-8e94-0d6d38b070c6.png)

I have the same problem with all town that don't have name:es

**Comment by vshcherb** [comment]
I don't see any issue with 2.4.3 and new search. Please use latest version

**Comment by Almorca** [comment]
I have updated my app and I continue with the same problem. If I configure "Map preferred language" to Spanish I only see in Spanish the nodes with name:es. Other nodes only show name not name:en / name.
If a town have name:en, int_name and name in the search I only see 'name'.
You can take Sparta (Esparta in Spanish) as example.

**Comment by vshcherb** [comment]
Now it is clear, search works but it displays name or name:es. We are missing this setting right now.

**Comment by vshcherb** [comment]
This will be  a new feature #2959 .
