### ISSUE TITLE
Suggestion on Map Drawing-Rendering

### ISSUE THREAD

**Issue by JeanDom** [osmandapp/Osmand#2941]
For trip planning, users frequently study maps by zooming in-out, touch-scrolling to nearby towns etc., just to get acknowledged to an area they want to go to.

Currently, when displaying a new area, OSMand first draws details, as streets and roads etc., and this can take time, especially on slow devices. Names (as town or street names) are appearing only after that drawing process has finished.

SUGGESTION: SIMPLY GET NAMES BEING DISPLAYED FIRST.

With names appearing first (for example, Boulevard St. Michel) the user knows immediately whether or not he zoomed or touch-scrolled to the area he was looking for.  If not, he can scroll further without waiting each time the whole drawing process finishes.  

I don’t know whether this is doable, but it looks easy and would really improve the user experience of OSMand.

**Comment by vshcherb** [comment]
This is already part of new rendering engine which is going to be released this year. To test http://download.osmand.net/latest-night-build/OsmAnd-qt-arm-nightly.apk

**Comment by scaidermern** [comment]
> This is already part of new rendering engine which is going to be released this year.

Sounds interesting. Is there any information about the new rendering engine? Does it finally use multithreading? Sorry for hijacking this bug report.

**Comment by JeanDom** [comment]
Thank you for the information.
I just tried the nightly apk with the provided link, but texts still appearing last (after everything else is rendered).

Thanks for your efforts

**Comment by vshcherb** [comment]
It appears last initially, but then it stays on the movement and keep displayed. New engine will be multithreading. Also new engine works faster on newer devices and there are caching possibilities there. I will close that issue in favor of development of the new engine .
