### ISSUE TITLE
UX: Confusing Buttons when creating Favorite Point

### ISSUE THREAD

**Issue by allo-** [osmandapp/Osmand#2942]
When i create a favorite in the _android_ app, the ui has the "replace" button where i would except the "save" button. The first few times i were very confused and did not find the "save" button (top of the screen, semi-transparent) at all, because all the UI seemed to be located at the bottom third of the screen, where the input fields are.

I would suggest to try either:
- Add all the buttons on the form, nothing at top of the screen.
- give the top of the screen a good contrast, i.e. black on white, so its obvious, that there appeared a part of the add-point user interface.

**Comment by vshcherb** [comment]
I think it is changed in 2.4, please try it.

**Comment by allo-** [comment]
Indeed, works as expected there.
