### ISSUE TITLE
Routing drives circle

### ISSUE THREAD

**Issue by quelbs** [osmandapp/Osmand#2944]
**Destination**
Position: geo:48.15928,11.547276?z=14
http://osmand.net/go?lat=48.15928&lon=11.547276&z=14
**Start**
Position: geo:48.159542,11.546987?z=14
http://osmand.net/go?lat=48.159542&lon=11.546987&z=14
When testing after #2871 I found an issue where the route goes one circle and passes the startpoint again.
![screenshot_2016-08-14-15-24-45](https://cloud.githubusercontent.com/assets/570222/17649406/02478a8e-6235-11e6-81e1-bfd5927aec99.png)

**Comment by vshcherb** [comment]
Was broken today and fixed properly already
