### ISSUE TITLE
Manage map files: contour lines inconsistency

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#2945]
Under _Manage map files -> All Downloads_ contour lines for Germany are displayed as being not installed:
![photo_2016-08-14_21-46-12](https://cloud.githubusercontent.com/assets/1040784/17651507/af18e8f6-6268-11e6-87e7-ebdcf6460c81.jpg)

Under *Local* they are being displayed as being installed:
![photo_2016-08-14_21-46-16](https://cloud.githubusercontent.com/assets/1040784/17651508/af1e3b58-6268-11e6-8b64-6058e27e9ee7.jpg)

These contour lines are indeed installed and they are also getting rendered when browsing the map.

Contour lines plugin is enabled the whole time. Restarting OsmAnd doesn't solve the problem. I can re-download these contour lines and then they are displayed as being installed even under _All Downloads_. After restarting OsmAnd it looks like on the first screenshot again.

**Comment by vshcherb** [comment]
There was a glitch 2 days ago, please verify on the latest build.

**Comment by vshcherb** [comment]
Just retested with latest looks fine. There will be release 2.4.4 around this week, so this will be fixed there as well.
