### ISSUE TITLE
Expanding "nn stops before" does not work any more

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2946]
Tap on a transport stop, then tap on a route (like a bus or train line) in its context menu.

Transport stops "before" the stop selected are summarized as "nn stops before". Some night builds ago you could tap on this to get them displayed entirely (expanded) which has seized working now.

The functionality is needed
 -  if you want to view stops the transport line comes from
 - or actually view stops in your direction of travel, because in some areas transport lines are mapped only once for both directions, so what we assume as "stops **before**" may actually be the very direction of travel the user needs.

**Comment by sonora** [comment]
PS: Issue was introduced on August 6. (There were 3 larger commits dealing with this functionality on that day.)

**Comment by vshcherb** [comment]
Will be fixed today by @crimean (2.4 as well)
