### ISSUE TITLE
Add "Zoom in" indication on the map context menu

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2947]
I observe users having difficulties discovering that they can zoom in onto a point (search hit etc.) by simply tapping on its title in the context menu.

I guess we should add some sort of indicator to make this more discoverable, like maybe add an orange crosshair image next to or below the title while not zoomed in.

**Comment by vshcherb** [comment]
For me it is the same as #2909. Will merge this issue into it #2909

**Comment by sonora** [comment]
True, I mistakenly thought we had closed that one.
