### ISSUE TITLE
Intelligent language search for OSMAnd

### ISSUE THREAD

**Issue by BoFFire** [osmandapp/Osmand#2948]
Hi,
I would like to propose an intelligent search bar for language search instead of a long list with radio buttons. Could even integrate little flag for each language if possible.
(For arabic GUI language choice, for example, the flag of arab league, to avoid any confusion).
Do you have other better ideas ?

Salutations amicales :)

**Comment by l2212** [comment]
I was right about to open an issue for this as well! I guess it would be the same thing, that's what I was about to post:

> In the 2.3.5 version I saw that you can't find a city/town using a name different from the one in tag:name unless you change the map language. Example:
> 
> name:       London
> name:ca    Londres
> 
> I have to switch to Catalan to find it in the list if I have "local names" as map language. It would be cool to be able to find the city using all the different names all the time, even more in cases where the two names would be way more different. The double name with the / could appear in the results, but also just "London" could be fine (the double name is awesome if you have selected a language, but in this case I guess it would be confusing to have it for all the names in the list of towns of a region and all the languages).

With an intelligent language search it would be even easier, I think.

Bye!

**Comment by sonora** [comment]
Similar to #3616, let's pursue there.
