### ISSUE TITLE
Replacing favourites should be undoable

### ISSUE THREAD

**Issue by allejok96** [osmandapp/Osmand#2950]
I recently wanted to move a favourite, so I created a new favourite in the correct position and then used the handy Replace button. But I accidentally selected the wrong favourite to replace. Now I don't know where that favourite used to be, and I'll never be able to find that place again (well, not really, but you get it).

There should be a confirmation dialog before a favourite gets replaced so this doesn't happen. Or at least a toaster message with an Undo button - but that could disappear if you are to slow.

**Comment by vshcherb** [comment]
Actually there are backups 7 recent changes in your folder with maps. So please take a backup favorites.gpx as a safe  option.
