### ISSUE TITLE
Online nominatim address search does not display search results

### ISSUE THREAD

**Issue by pingping01** [osmandapp/Osmand#2951]
Hi thanks for fixing the recent issue with the July map updates with  the new version of OsmAnd+ 2.4.3 however with 2.4.3 I am now seeing problems with searching when using Online Nominatim - Address.  I have online maps plugin enabled but when searching for a street OsmAnd+ either:

1) displays no search result (also there is no circular "searching" animation)
2) flashes a search result for a split second & but will not display any search results

I have tested on a Note 4 running Marshmallow 6.0.1 & another Note 4 running Lollipop 5.1.1.  The issue was NOT present in OsmAnd+ 2.3.5.  Other users have also been able to replicate this issue on other devices as detailed in this thread:

[https://groups.google.com/forum/#!topic/osmand/1dz9y6ivKr4](url)

The error is very easy to replicate & I have found a workaround however it clearly is not supposed to behave in this way:

1) Ensure online maps plugin is enabled
2) Search for street name & town under POI tab, example Haynes Way, Rugby then select Online Nominatim Address
3) OsmAnd will switch to search screen however **no search results will be displayed**
4) Delete town, eg Rugby
5) Search result is now displayed

Many other examples of error taken at random for testing:
Old Park Road, Telford
Corporation Street, Birmingham
Felspar Road, Tamworth
Jackdaw Lane, Oxford
The Hide, Milton Keynes
Nethergate, Dundee (Scotland)
Achenkamp, Bielefeld (Germany)

Strangely addresses in Sutton Coldfield produce search results:
Clarence Road, Sutton Coldfield
The Parade, Sutton Coldfield

Leamington Spa either produces or fails to produce a result depending on what is input:
Buckley Road, Leamington Spa = no search result, unless above method is used
Buckley Road, Royal Leamington Spa produces a search result

There appears to be some form of display bug which I hope you can please fix.

Thanks

**Comment by Boothy99** [comment]
I can confirm above address search issue / online nominatim, as described above.
Using latest OsmAnd+ 2.4.3 & August 1st maps (England, Scotland etc).
On HTC One M7.
As mentioned - search results flash up for s fraction of a second then disappear until the town is deleted leaving just the street name in the search field. Results then appear instantly.

**Comment by Boothy99** [comment]
@vshcherb,
Thanks for sorting it.
