### ISSUE TITLE
Avoid motorways in pedestrian settings

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/Osmand#2952]
In the pedestrian settings it is possible to avoid motorways. 
In Germany, maybe in other countries, it is not allowed to walk on motorways.
Do we need this option, or avoid the routing engine motorways it self?

2.4.0 #18096M
Greetings Simon

**Comment by hakuchi** [comment]
I think all highway=motorway in OsmAnd are not for foot, bicycle and horse, so we don't need the option "avoid motorways" for foot etc.

**Comment by sonora** [comment]
Overall rare, but there are motorways, e.g. in remote US areas, which are not legally closed to bike or foot traffic.

**Comment by vshcherb** [comment]
They are highly deprioritized but there are some areas where it is only an option.
