### ISSUE TITLE
Update F-Droid

### ISSUE THREAD

**Issue by homersimpsons** [osmandapp/Osmand#2953]
Same as #2438 

I reopen issue https://gitlab.com/fdroid/fdroiddata/issues/434 and they redirect me to https://github.com/mvdan/OsmAnd-submodules/pull/20 so please merge this.

**Comment by RealRancor** [comment]
@homersimpsons This is really the wrong place to report / request this. Please please have some patience and don't annoy upstream (osmand) with F-droid related stuff.

**Comment by vshcherb** [comment]
That's not an OsmAnd team responsibility and I would advise to wait 2.4 will have 2.4.4 and possibly 2.4.5
