### ISSUE TITLE
Highlight Transport Routes

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2954]
Our website seems to say that in v2.4 tapping on a route in a transport stop's context menu details highlights the route, there is even a screenshot for this. Does this work? I never see any route highlighted ...

**Comment by njohnston** [comment]
It works, but it's not obvious.

First, enable display of transport stops:

![osmand_transport_enable_small](https://cloud.githubusercontent.com/assets/638458/17708322/619e1130-63dc-11e6-9fe1-017dc36b3daf.jpg)

Tap one of the stops:

![osmand_transport_stop_selected_small](https://cloud.githubusercontent.com/assets/638458/17708334/70d2b39a-63dc-11e6-9d78-f126e4506a8d.jpg)

Drag the context menu up to show the route relation name:

![osmand_transport_stop_route_name_small](https://cloud.githubusercontent.com/assets/638458/17708379/9bafb540-63dc-11e6-8f02-97e36f48b3aa.jpg)

Tap the route relation name, and the whole route is highlighted:

![osmand_transport_stop_route_displayed_small](https://cloud.githubusercontent.com/assets/638458/17708393/af6b51f2-63dc-11e6-9f1f-bc0754cba4c3.jpg)

(The route looks incomplete but this is most likely a problem with OSM data, not OsmAnd.)

This example is from Cheltenham in England.

The context menu needs a "show route" or similar button.

**Comment by vshcherb** [comment]
We even have screen shot about it in 2.4 http://osmand.net/blog

**Comment by sonora** [comment]
Sorry, you misunderstood what I am reporting here: When tapping on the Transport route,
- screen zooms out ok to the area the route covers
- Display of Transport stops is correctly filtered to then only show the stops of that particular route
- But the actual route (the thick blue line in njohnston's final screenshot above) does not show in all cases I have tested (several dozen in different areas of the world).

Chances are this is the same issue njohnston mentions by saying "(The route looks incomplete but this is most likely a problem with OSM data, not OsmAnd.)". Maybe the routes I am trying to view show so "disjunct" that non of the adjacent transport stops are connected?

Example is any Munich subway, check Line "S1", Transport stop Munich Marienplatz.
<img width="135" alt="screenshot_2016-08-17-10-29-46" src="https://cloud.githubusercontent.com/assets/845735/17729702/b89b0f2c-6465-11e6-9124-1d884873ac7d.png">

**Comment by sonora** [comment]
Issue solved: Looks like the (mostly June 1) maps I have on all my testing devices are just to dated to contain the right data :)

May want to add a note to our web site reminding to update maps for some of our new features.

**Comment by sonora** [comment]
@vshcherb PS: Route line disappears at zooms <=11, which is quite early for train routes stretching 100km or so.
