### ISSUE TITLE
Double yes in favorite replace

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/Osmand#2955]
See screenshot
![screenshot_2016-08-16-17-00-16](https://cloud.githubusercontent.com/assets/11144987/17703745/1c1e9908-63d3-11e6-89d4-3a7c227942db.png)

#18108M

Greetings Simon

**Comment by njohnston** [comment]
Caused by a typo in src/net/osmand/plus/dialogs/FavoriteDialogs.java. Pull request submitted.
