### ISSUE TITLE
Keep right on a 90° turn

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#2957]
![screenshot_2016-08-16-12-59-17](https://cloud.githubusercontent.com/assets/12786225/17709767/c860ba04-63ea-11e6-84da-e9cd574f94d9.png)

Osmand 2.4.0#14184D.     Spain Offline map Aug 1, 2016
Car profile fastest route

Location http://www.openstreetmap.org/#map=19/40.73310/-4.02027

**Comment by hakuchi** [comment]
in reality these are 20°-30° turns.
You made a lot of 90° turn where are exit from motorway or trunk, this is not the standard to made edits in OSM.
here a example with not real 90° turn: https://www.openstreetmap.org/way/309644976
same at all these exits: https://www.openstreetmap.org/#map=19/40.73369/-4.02021

OsmAnd give correct output when it say "keep right"
This is not a bug

**Comment by vshcherb** [comment]
Checked on satellite, OsmAnd definitely gives correct output even based on the wrong mapping

**Comment by OpenSourceForEver** [comment]
Ok. I am so sorry.

I thought keep right is when there is two lanes and each one has a different destination.
