### ISSUE TITLE
Current road name on unnamed road?

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#2960]
With nb-2016-08-12 I was driving on a unnamed road ( [this way](https://www.openstreetmap.org/way/207548703) towards [that way](https://www.openstreetmap.org/way/98985388) ), and the names of the near-by roads I had left and was approaching were _flashing_, showing the crosshair placeholder '+' (introduced in #2862) in front.

While the flashing appears to be intended, I do not see the value of flashing the name of a road I am not on. Anyway, the crosshair icon should not be shown, because I am not on this road. A different icon could be feasible, symbolising that I am away from that named road, e.g. a double-arrow: ↔︎

![screenshot_2016-08-15-10-24-56](https://cloud.githubusercontent.com/assets/8266355/17717979/9ea187b2-6411-11e6-88f3-cb632da55429.png)
![screenshot_2016-08-15-10-25-33](https://cloud.githubusercontent.com/assets/8266355/17717991/a939162c-6411-11e6-8dc0-0c43c18c6054.png)

**Comment by vshcherb** [comment]
+ is removed now, it should be more obvious. That was a temporary fix

**Comment by sonora** [comment]
Yes, the reason I had temporarily inserted he "+" sign (which has finally been corrected to a blue straight arrow now) was to test if our logic is right.

And I guess that polarbearing's observation may indicate that we did not yet get it correct: The blue arrow indication is meant to appear when the position is **on** the road (vs. yellow turn instruction arrows when the widget indicates the next turn). We need to review the code one more time.

**Comment by sonora** [comment]
Problem is we are defaulting to the lastKnownRouteSegment rather than going through a reverse geo-lookup.

**Comment by vshcherb** [comment]
This is not a navigation mode, so it is a bit source of other errors. Yes, geocoding lookup doesn't support empty names or that road. So that purely related to geocoding itself cause it skips empty names.

**Comment by polarbearing** [comment]
Was testing nb 17-Aug-2016 13:43 and replaying some GPX recordings and now saw some "Near RoadName" in the proximity range @sonora mentioned. Did not yet see anything on the road from the first post since nothing was shown due to #2962.

**Comment by sonora** [comment]
From how I remember our code, we do not cache geocoding results but essentially repeat lookups with every location update, i.e. pretty much all the time when moving. We may have to look into how to cache results a little, or at least not do widget refreshs when no real update is found.
