### ISSUE TITLE
Intermittent loss of current road display

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#2962]
In nb-2016-08-12 and earlier, I often experience that in non-navigation, the road name or ref is not shown, despite them being named, while the location provider is connected, we have good GPS reception with good HDOP value, and the blue arrow correctly moving along the road, even in high zoom. The widget remains empty.

The situation is mostly observed after the app being started and getting the GPS fix, or after a mode change such as switching navigation off, and can continue for seconds, minutes or the whole trip. 

Examples:
![screenshot_2016-08-15-19-12-31](https://cloud.githubusercontent.com/assets/8266355/17718243/0b6eaa40-6413-11e6-8d58-331eb4ad6f70.png)
![screenshot_2016-08-13-09-14-19](https://cloud.githubusercontent.com/assets/8266355/17718276/383df120-6413-11e6-9211-e9136575912f.png)
![screenshot_2016-08-04-15-35-27](https://cloud.githubusercontent.com/assets/8266355/17718307/6a3ea566-6413-11e6-87dc-aa7dc75bfa12.png)

**Comment by sonora** [comment]
From my research, what you are seeing is the time lag reverse geocoding needs to determine the street name, I have seen this take quite long on some devices (there seem situations with 30 sec or so even on mid-grade devices.)

**Comment by polarbearing** [comment]
It's quite non-deterministic, sometimes the name is shown immediately, sometimes never. 

With the time lag, do you mean to start geocoding in general, or 30 sec for each little road segment I encounter? 

With the current trend in OSM to fragment roads for every change in turn lanes, surface, cycle lanes etc, this problem would increase.

**Comment by polarbearing** [comment]
Just went for a walk with the device, in car mode, so it had time enough to lag around, but I was left without street name for 90% of the time. When it had shown one occasionally, it even displayed Near L338 when I was already 80m on another named road (screenshot). It even displayed Near AnotherRoad before I had even reached it.

![screenshot_2016-08-17-17-20-14](https://cloud.githubusercontent.com/assets/8266355/17742478/77ac2330-64a0-11e6-8604-b8981b53dc9a.png)

**Comment by vshcherb** [comment]
I could see 2 issues:
1) I reduced the timeout between reschedule
2) it might be related that screen is not refreshed, the street is queried when location is updated

**Comment by sonora** [comment]
Just to be sure: When this happens, tap on the position (blue dot or triangle), and check what is displayed in the context menu as "address". It should normally be in sync with what is displayed in the top bar (empty top bar should correspond with "Looking up address..."), unless we have a refresh issue, which should become obvious by comparing the 2.

One minor discrepancy: I think I use >100m threshold for using "Near" in the context menu, while Victor introduced only >50m today for the top bar.

Question @vshcherb : Our reschedule distances had been unchanged for a very long time. Would reducing them now potentially increase overall battery consumption significantly?

**Comment by sonora** [comment]
PS2: I did the "walking in car mode" test today in a residential neighborhood and have t say it behaved just fine, all street names correctly displayed (also correctly switched say 30m past turning onto another street), with never any "Near" showing up (unless you leave a named street or are on a unnamed one).  So I have to say I cannot reproduce the issue in the last screenshot above.

**Comment by polarbearing** [comment]
Ok, so it turns out to be a failure to geocode. Tapping on the triangle, I get "My position...Looking up address", which does nothing for eternity. Equally, tapping on a different road, I get the same issue. However, on my way back, there were problems for the first half, then it started to work, and was then very fluent when changing roads. 

Thus it is not a general lag in geocoding, it must be something blocking the thread under certain conditions. 

![screenshot_2016-08-18-16-49-43](https://cloud.githubusercontent.com/assets/8266355/17791004/56ff2854-6599-11e6-8fdd-58dc36bea3fb.png)

![screenshot_2016-08-18-16-54-02](https://cloud.githubusercontent.com/assets/8266355/17791055/97bb122c-6599-11e6-9743-a68486b1470e.png)

**Comment by vshcherb** [comment]
The blocking issues where totally redesigned last week, still some concurrency is in place i.e. determine location and determine current road are using same data and same threads.

**Comment by sonora** [comment]
Let's merge to #3898.
