### ISSUE TITLE
Intermittent loss of the location provider

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#2963]
In nb-2016-08-12 and earlier, I often experience the loss of the location provider in the starting phase. The typical sequence is that the app is started, waits for GPS fix with the location icon in the status bar flashing, gets a coarse GPS fix with a number of sats, shows the road position with a big uncertainty halo, and then disconnects. The location icon in the status bar disappears, and so does the blue arrow, and the sat number goes back to 0/0. So far it only reconnects when I close and restart the app, so far the second or third attempt have worked correctly.

This issue here is different from #2962, where we have full GPS reception in OsmAnd.
It is also not an issue of bad GPS reception, in this case (e.g. in a tunnel) the location icon remains but gets empty.

Happens both in navigation and non-navigation.
![screenshot_2016-08-11-15-38-34](https://cloud.githubusercontent.com/assets/8266355/17718583/0ab29484-6415-11e6-972b-418c2c072b67.png)

**Comment by vshcherb** [comment]
Unfortunately can't reproduce and I can't recall any recent change in that area, it could be related to Android system itself. If anyone experience the same please share the symptoms, or if you could find anything related, please mention it

**Comment by sonora** [comment]
This sounds like you are getting your position fix from 2 different sources: Many devices offer combined location provisioning, like via google's WiFi db **and** via GPS.

Please test by setting your **Android Locations** settings to strictly "GPS only", (and disallow any other source, like maybe in WiFi's advanced settings also disable "Allow google to WiFi scan even when WiFI is turnd off", or whatever the setting my be called on your device). Then see if the issue disappears.

**Comment by polarbearing** [comment]
Thanks, but I was always using GPS only. Wifi-Db could not work anyway since the device has no data connection. Will continue to observe.

**Comment by polarbearing** [comment]
Mostly using a more powerful device recently, I have not observed the issue on the new device so far.
