### ISSUE TITLE
Investigate why 3-letter locales are not displayed

### ISSUE THREAD

**Issue by BoFFire** [osmandapp/Osmand#2966]
Hi,
Is there anyway to choose a new and incompleted language in dev builds so that we can follow and complete translations ?
For example : Kabyle language thar has been introduced recently.
Can we have something that points translation team to translate.osmand.net to download and test incompleted languages and/or carry on translating.
This could be good for OSMAnd localization.
If there is a manual method, please let us know.
Greetings :) and thanks for all.

**Comment by verdulo** [comment]
Unfortunately, are you aware that there's bug in Android, and all languages with 3-letter codes don't work? So your Kabyle translation (kab), Asturinan (ast), and Upper Sorbain (hsb) simply won't work, unless Google fixes it and you buy new phone. You can still use it as map-language, there's [1442 translated names](https://taginfo.openstreetmap.org/keys/?key=name:kab), so maybe at least ask developers of OsmAnd for adding it as map-language?

You can use [this program (requires root)](https://f-droid.org/repository/browse/?fdid=fr.simon.marquis.preferencesmanager) to enable Kabyle language by-force in OsmAnd, but it won't do anything because of bug mentioned earlier...

@Hardy It would be nice to warn users on weblate in "Disclamer" that languages with 3-letter ISO codes cannot be used.

**Comment by sonora** [comment]
Yes, unfortunately 3-letter ISO 639-2 code locales currently seem to have issues in Android, see e.g. 
 -  https://code.google.com/p/android/issues/detail?id=49120
 -  https://code.google.com/p/android/issues/detail?id=106574

As I have stated elsewhere, with this bug or not, I see no value in including languages in OsmAnd where translators have not invested the effort to at least translate 10%, I think this is a fair expectation.

I am happy to include any language >10% translation rate (will mark it as "incomplete" until it reaches ~80%), please post an issue if you need this done, I only sporadically watch this on weblate.

Will also investigate putting some info on weblate regarding the current Android difficulties with 3-letter ISO codes as display language, if I find a suitable place and have the access rights to post there.

**Comment by sonora** [comment]
I have contacted the weblate team to include this text somehow in our Android translation space:

--------------------------------------------------------------------------------------------------------------
Dear translators,

thank you all very much for your efforts to complete our display language translations here, and also to localize OsmAnd in more and more languages.

Can I please make you aware of the following:

- I am happy to include any language with >10% translation rate into OsmAnd’s display language selection menu, (will mark it as "incomplete" until it reaches ~80%). Please post an issue with OsmAnd if you need this done, I only sporadically watch these figures on weblate.

Unfortunately languages featuring 3-letter ISO 639-2 codes currently seem to have issues in Android, see e.g. 
• https://code.google.com/p/android/issues/detail?id=49120 
• https://code.google.com/p/android/issues/detail?id=106574
This means that, unfortunately, any such language may not display in OsmAnd menus on your device. (This issue only affects the language used in the app menus, not in the map, of course.)

Thanks,
Dr. Hardy Mueller

--------------------------------------------------------------------------------------------------------------

**Comment by BoFFire** [comment]
Hi, @sonora @verdulo :
Actually kabyle lang characters (which are latin ones) are displayed very well on the GUI.
Link 1 : http://image.noelshack.com/fichiers/2016/48/1480842139-screenshot-2016-12-04-10-00-44.png

Link 2 : http://image.noelshack.com/fichiers/2016/48/1480842176-screenshot-2016-12-04-09-53-16.png

Link 3 : http://image.noelshack.com/fichiers/2016/48/1480842174-screenshot-2016-12-04-09-54-07.png

At the moment the partially imported kabyle from webplate is displaying in indian or urdu language ;)

Salutations amicales.

**Comment by sonora** [comment]
Ok thanks for the feedback. Somehow related also to #3145. Still not sure if it is universally fixed, depends on your device or Android version or what ...

**Comment by BoFFire** [comment]
Hi @sonora,
I tried the Preference Manager to betatest this language but I think there is an error in importing "kab" language (confusion between ka and kab, whuch are two different iso languages).
Can you check that and confirm that kab is using latin charachers please ?
Thank you for reading me.
Salutations amicales :)

**Comment by BoFFire** [comment]
Actually it should display this : 
https://github.com/osmandapp/Osmand/blob/1930f9a970c977b7fa1e7b258da6f623e02838f1/OsmAnd/res/values-b%2Bkab/strings.xml

**Comment by sonora** [comment]
@BoFFire Maybe I misunderstand your question, but yes, I have verified that the menu entry for "lang_ka" points to he values-ka folder, while the entry with label lang_kab refers to kab, which should actually by the convention I read use the values+b-kab folder.

I believe that if this does not produce the desired result, it may be due to remaining
- the Android version you use,
- perhaps the specific capabilities of your device ROM
- maybe our gradle version, or any remaining android issue, not sure...

**Comment by BoFFire** [comment]
@sonora yeah thank you. I have installed many locale apps to force the langage but yeah Android thing.
This is not related to OSMAnd. Grrr frustrating.
Thank you very much :)

**Comment by BoFFire** [comment]
Update @sonora 
Sir Belkacem was translating Mozilla Firefox on Desktop and mobile and Kabyle language was recently added to the Firefox Beta. I wonder how they made it possible :D
Some screenshots :
http://image.noelshack.com/fichiers/2016/51/1482426325-screenshot-2016-12-22-17-48-39.png
http://image.noelshack.com/fichiers/2016/51/1482426321-screenshot-2016-12-22-17-32-47.png
http://image.noelshack.com/fichiers/2016/51/1482426295-screenshot-2016-12-22-17-59-49.png
http://image.noelshack.com/fichiers/2016/51/1482426315-screenshot-2016-12-22-17-49-04.png
I think it all another method they use for localization.
Have a nice day :)

**Comment by sonora** [comment]
I have re-opened this as a reminder to investigate, but cannot promise I find much time any time soon.

**Comment by sonora** [comment]
Had another look and find no glitch in our code. I think it must be in our compilation environment or device capabilities.
