### ISSUE TITLE
destination:forward and destination:backward appear unsupported

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#2968]
nb 17-Aug-2016 13:43 / map 1 Aug 2016:

[here](https://www.openstreetmap.org/way/152148189) ```destination:forward``` was added on June 30, but is not shown with the 1 Aug map:

![screenshot_2016-08-17-15-41-05](https://cloud.githubusercontent.com/assets/8266355/17742839/e517cb58-64a1-11e6-93e7-30b5c2a7cef1.png)

**Comment by sonora** [comment]
@vshcherb  Needs research. My first guess is we have no support yet at all for destination:forward (?)

**Comment by sonora** [comment]
@vshcherb : I think this should work, but still needs double-checking and testing: https://github.com/osmandapp/Osmand/commit/08a5ed8494e89ff29767d027353d602a849fca32 and https://github.com/osmandapp/Osmand/commit/d2d08addc048df12d057ae71e42009e91a1fff3c.

**Comment by polarbearing** [comment]
nb 19-Aug-2016 16:09, simulation, seems to work for my example above.

**Comment by polarbearing** [comment]
Do we support ```destination:ref``` ? if so, we would need to expand this issue to ```destination:ref:{forward|backward}```

**Comment by sonora** [comment]
Yes, supported, `destination:ref` takes precedence over just `ref`.

Implemented: https://github.com/osmandapp/Osmand/commit/a97fbba7242ef7361ccc76362ce73c66a62b3633.

Please test thoroughly.

**Comment by franco999** [comment]
It could also support the tag `destination:street` ?
Example: https://www.openstreetmap.org/way/258946901
Wiki: http://wiki.openstreetmap.org/wiki/Exit_Info

**Comment by sonora** [comment]
Regarding `destination:street`: Please open a separate issue if you need this, so we can discuss there. My gut feeling is the primary purpose of this all is to produce correct and precise but **short** navigation instructions. So supporting too many cumulative or too rarely used cases is not helpful, may even be counter-productive, either performance- or clutter-wise. The destination display alone is in many cases already a add-on to other, often sufficient specifications.

**Comment by polarbearing** [comment]
In a quick simulation, my test case from above works fine with both destination:ref and destination:ref:forward. Will keep looking for more. 

The >> sign should probably come _before_ the destination:ref, destination:ref:forward or destination:ref:backward :

![screenshot_2016-08-21-22-14-45a](https://cloud.githubusercontent.com/assets/8266355/17839635/039d79a2-67ee-11e6-9d4e-2329362b617b.png)

**Comment by sonora** [comment]
@polarbearing: Yes, the》》will always show to indicate the destination field, but not the ref field. To keep the entire info short, we map ref tags into one field only, which will contain destination:ref(:fw/bw) if present, else just ref, else nothing. We do not keep track which ref field is taken, hence neither the display widget nor the voice navigation prompts are aware. But I have seen no practical issues arising from this. If you can demonstrate any, it would be worth a seperate issue.

**Comment by polarbearing** [comment]
Thanks, I understand. It might be a bit more an issue for the voice prompt. When testing the above, the voice was something (in German) along "turn right into the A10 towards Dresden, Frankfurt", as if the link road were the motorway already; instead of "turn right towards the A10 Dresden, Frankfurt". I'll keep an eye, hm, an ear on it how it affects announcements in practical driving.

**Comment by sonora** [comment]
Our German TTS file is rather complex, trying to detect male/female street names, and using accusative/dative, and looking at it I think it may not even yet cover all combinations of the 2 (e.g. no article used for the Continue prompts), so there may also just be an overlapping issue here with Germany grammar.

In any case the priority practice I describe above for the ref field has been in place for a long time with no practical issue reported, so we should work with examples where this matters at all before considering any far-reaching code complications.
