### ISSUE TITLE
OsmAnd fails to refresh list of maps to be updated after downloading

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#2969]
- Go to Maps Management / Updates
- Update all maps

Note that the updated maps stay as green items in the list.

- Switch tab to Local or All Downloads

- Switch back to Updates tab

Note that now these items have vanished.

Solution: Updated maps should vanish from the list after updating  automatically (without the need to switch to other tabs).

Found with OsmAnd+ 2.4.3.

**Comment by vshcherb** [comment]
They change color so it indicates they are updated

**Comment by Norbert80** [comment]
@vshcherb

This is not a good user experience. Green indication makes only sense in the list if of all available maps.

Here we have a double indication. Green and not present.
