### ISSUE TITLE
Banks with atm are not displayed correctly

### ISSUE THREAD

**Issue by verdulo** [osmandapp/Osmand#2972]
Object amenity=bank, atm=yes are displayed in OsmAnd as Bank (correctly), but in POIs properties we can see English text: "Atm_yes: yes" and "Additional atm yes" instead of "Atm: yes" (or translated equivalent).

**Comment by vshcherb** [comment]
It is already fixed in map generation, but the new maps will be available 1st next month. 
@xmd5a2 I still think we are missing translations I see now only 1 entry "Additional atm yes" which corresponds to osmand_additional_atm_yes/yes

**Comment by sonora** [comment]
I guess I  fixed this via https://github.com/osmandapp/Osmand/commit/5cba154a6ab8ddcaf7c55a5b75bbe07bf045084c ?
