### ISSUE TITLE
opening_hours interpretation issue

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#2973]
OsmAnd versions 2.4.3 (released 2016-08-11) and nightly build 2.4.0#18150M (released 2016-08-17), on Android.

I've noticed a problem in how OsmAnd handles opening_hours fields that include some of the more exotic combinations of values.  I am **not** referring to the difficulty in handling those values to display the red/green closed/open feature (e.g. the "PH" issue brought up in github #2610 ).

For this supermarket http://osm.org/go/ZQqt~l_L7?node=1894137664 the business hours field is:
opening_hours=Mo-Su 07:00-23:00; Easter off; Dec 25 off

However, OsmAnd displays this as "Mo-Su 07:00-23:00; Mo-Su off" in red, all the time, even when the store is open.  (Screenshot attached.)

I understand that it may be a very long time before OsmAnd can handle things like PH and other extended possibilities, but (to my way of thinking, anyway) it should be able to discard values in opening_hours that it doesn't know how to process, and at least show red/green appropriately.  In particular, there seems to be a bug in that it substituted Mo-Su in place of Easter and Dec 25 (which is my main point).

As a side note, would it be possible to work on adding specific-date parsing ability, so that it can handle dates such as "Dec 25"?  Values like "PH" will obviously have to wait for a good solution, but I'd think a single date (or list of them) should be do-able.  "Easter" might be more difficult, even though it can be calculated (or found in tables) for the next few millennia, for the simple reason that it would depend on which country you are in (the Eastern Orthodox vs. Catholic/Protestant difference in calculation), which relates to the "PH" problem.

![screenshot_20160817-201129](https://cloud.githubusercontent.com/assets/11140831/17757890/883aabfa-64b8-11e6-90f6-d9c4aecf7b1e.png)

**Comment by vshcherb** [comment]
Fix opening hours
