### ISSUE TITLE
Simplify UI to plan, route, and navigate

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#2976]
Following the discussion in #2958, I understand the intention to simplify the user interface for quickly starting to navigate. However I still have two steps after I found a target, first I have to press the route button, then again the Go button. Further, the interface is different when I  came from a favourite or from address search. Screenshots below. 

![screenshot_2016-08-18-09-48-21](https://cloud.githubusercontent.com/assets/8266355/17766793/20f5de9a-652d-11e6-8361-d447f79160fd.png)
![screenshot_2016-08-18-09-50-41](https://cloud.githubusercontent.com/assets/8266355/17766799/2770d0e0-652d-11e6-854a-e4496724889a.png)
![screenshot_2016-08-18-10-00-53](https://cloud.githubusercontent.com/assets/8266355/17766818/37158cd4-652d-11e6-818f-137f7df22c3f.png)

Thus I propose to unify the interfaces as below, showing prominently the buttons for "Cancel", "Plan" (set destination), "Route", and "Go" (turn-by-turn).  Thereby, "Plan" is a subset of "Route", and "Route" is a subset of "Go", thus the buttons are ordered in this sequence. 

All fav editing and point sharing can go into the menu (reached from the 3 dots), I'd prefer to keep the setting cog wheel visible. 

An advantage is that when I select "Plan", the route calculation does not start immediately (which currently makes the device sluggish when I want to continue setting further destinations).  And when "Plan" is selected, we can get the air distance and red arrow again.

![screenshot_2016-08-18-09-48-21_mock](https://cloud.githubusercontent.com/assets/8266355/17766964/20ba8ba0-652e-11e6-8924-56a70a487c31.png)

**Comment by vshcherb** [comment]
Merged #2765
