### ISSUE TITLE
The time stamp of the map is different in "Live updates" and in "Manage map files" menu

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2978]
My OsmAnd is set to update the map regularly through live updates. The latest update is shows as today (19th August 2016).

The OsmAnd map [website](http://download.osmand.net/rawindexes/) shows the latest India map dated 1 Aug 2016.

Which means the map on my device is later than the map downloadable from the website.

But in the "Manage map files" menu, if I select "Local" tab, OsmAnd shows me a time stamp of Jul 1, 2016!
This clearly means that my local map is outdated. (**wrong status!**)

Not only that, but the map icon is green, which means the local map is NOT outdated.

Desired: If the map is live-updated, all displays should show the same (actual) date. Further, if the live update is later than the web-based map, it should show as "updated" (green icon).

**Comment by vshcherb** [comment]
In Local OSM Live maps are not displayed only base maps are displayed.
