### ISSUE TITLE
In Quick Search results, the directional arrowhead does not turn toward the actual POI

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2979]
Reporting for OsmAnd~2.4.0#18186M

The **Quick Search** results show (orange) directional arrow-heads for each matching result.
But these arrowheads do not turn when the orientation of the phone is changed.

**Comment by raindropsfromsky** [comment]
I tried many more times, and found that they can be in blue color also, in which case they turn when the device is turned.

So I am guessing that when the GPS signal is lost, OsmAnd shows the arrow directions in orange, which are locked.

But this sign is too subtle, and the user may miss it altogether. Also, it is not clear which direction the orange arrows point to. Is it assuming North up?

**Comment by vshcherb** [comment]
Yes it is assuming north up, without location rotating arrows doesn't make much sense
