### ISSUE TITLE
In Quick Search, the show on map button does not show the results (orange icons) at all

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2980]
Reporting for OsmAnd~2.4.0#18186M

When I press **Show on map** button, the map should zoom in or out sufficiently, and show all/most results. At that zoom, the orange icons should be visible.

But often OsmAnd just shows a map, and the POI markers for search-results are totally missing.
They appear only when we experiment with zoom+pan.
By that time, the current position is lost!

**Comment by sonora** [comment]
From what I see there is only a time delay until the current search task is through, so it is not a bug per se, but a problem of the search not being very fast ...
