### ISSUE TITLE
[Feature request] Adding default speed limits by coutry

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#2981]
The issue description from user:
There are may roadways in OpenStreetMap that are not tagged with any particular speed limit. In those cases OsmAnd does not give any speed limit information, and of course no warnings if you exceed the limit. This is a shame, because there are default speed limits, known as implicit speed limits and well documented as such: wiki.openstreetmap.org/wiki/Key:maxspeed (http://wiki.openstreetmap.org/wiki/Key:maxspeed) Because of this, tagging of speed limits in OpenStreetMap is generally not really needed, although possible, except on specific pieces of road where the normal default speed limit is inappropriate (too fast) and so a lower limit will be sign-posted.

Do you think that it will be possible, in future versions either of the application or of the extracted OSM roadway information, to make available the appropriate speed limits. For a start, it would be a big help already if for example roadways in France tagged as highway=residential were automagically given a speed limit of 50: i.e. when highway=residential but without any maxspeed tag, then treat it as though it was also tagged maxspeed=50 & source:maxspeed=FR:urban. Perhaps you already apply some similar logic, so as to estimate travel times when making routing choices, but didn't think it useful to display the resulting speed limits - I think that you can, and should. Perhaps you could add a parameter so that the user would decide, if speed limits are being displayed, then should implicit limits also be displayed - or not.

**Comment by homersimpsons** [comment]
If osmand display those speed limits, it needs to show a sign to explain that this road don't have max speed tags, then it's only informative and can be another speed limit.

**Comment by polarbearing** [comment]
The default speed limit does not depend on the road type. In many countries I know, it depends on being within or outside a defined settlement. Thus the same highway=secondary is max 100 outside, and 50 within a city boundary. It would require tremendous containment calculations, when the city boundary is already mapped, while being extremely unreliable.

Better add the limits in OSM.

**Comment by vshcherb** [comment]
We can support multiple transformations at the preprocessing OSM stage i.e. we support tags maxspeed=ru:rural etc... Though it is almost impossible distinguish rural and cross-country road, this should be a manual process by tagging it in OSM. In many countries it is already done

**Comment by Talkless** [comment]
> The default speed limit does not depend on the road type. 

@homersimpsons What do you mean by that..?

In Lithuania:
motorways: 130/110 (depending on season)
trunks: 120/110
Other paved with asphalt: 90
Other unpaved roads: 70

There's big table of different speeds depending on road type: https://wiki.openstreetmap.org/wiki/Default_speed_limits

@vshcherb so we should map with maxspeed=lt:urban or maxspeed=lt:rural etc, or directly with maxspeed=90 source:maxspeed=lt:rural, and OsmAnd should start showing these limits?

**Comment by homersimpsons** [comment]
@Talkless I guess you mented to mention @polarbearing 

That said his example is right. For reference: in France, you have a default speed limit of 80km/h outside of cities and 50km/h inside cities.

**Comment by Talkless** [comment]
@homersimpsons yea sorry for miss-mentioning.

So I wonder, how does OsmAnd calculates ETA (fastest routes, etc) when routing via roads that does **not** have maxspeed set?
