### ISSUE TITLE
Use of speech synthesis markup language?

### ISSUE THREAD

**Issue by RicoZ-OSM** [osmandapp/Osmand#2983]
Just came across
   https://www.w3.org/TR/speech-synthesis/

and think it could be extremely useful. You can embed commands like `<break .../>,  <emphasis>,  <phoneme>,  <audio src=file>` and similar into the strings to be spoken. Android TTS supposedly supports it although it might be available in some TTS engines only?

Does OsmAnd do anything about it?

**Comment by vshcherb** [comment]
Not yet.

**Comment by sonora** [comment]
Roadmap issue at most, let's keep the issues list clean.

**Comment by xandro0777** [comment]
So is it on the roadmap now?
