### ISSUE TITLE
Osmand writing recorded GPX tracks to private memory, and unable to export them

### ISSUE THREAD

**Issue by brycenesbitt** [osmandapp/Osmand#2988]
It seems that quite a few people are either trying to upload gpx tracks, or export recorded gpx tracks, and not finding them.  Reports on this are all over the Google forum.

The common thread seems to be that some setups of osmand write these files to the private data area. When the gpx tracks are "shared" via Google/Drive/Beam/Skype they are unreadable and the transfers fail.

For example: https://groups.google.com/forum/#!topic/osmand/iIbByH5zUFY and http://jeroenmols.com/blog/2016/07/21/cyclinggps/

Please note this is apparently depended on setup, and some people have had success chaning the storage location _before_ recording tracks.  Is there a solution for those with files trapped in private storage?

**Comment by brycenesbitt** [comment]
Note that switching the data storage from "internal" to "shared storage", then selecting "copy" does appear to work.

**Comment by vshcherb** [comment]
It is fixed in 2.4 already

**Comment by shirishag75** [comment]
I am using Samsung Galaxy J5 and in it, it is easily seen using MTP at Card/Data/net.osmand.plus/files/rec but this is only seen if osmand itself is running otherwise not.

**Comment by fabeit** [comment]
I have fix this issue selecting shared storage, but now I have two copies of the maps and I can't access the original files. How to fix this?

**Comment by vshcherb** [comment]
You can change the storage via settings and change it back with option "Copy files"

**Comment by spacemanspiff2007** [comment]
> You can change the storage via settings and change it back with option "Copy files"
What do you mean by that? I have the same problem that I can't access my internal gpx data. Unfortunately when I change to "external storage" the gpx tracks do *not* get copied.
I only get an empty folder structure and can not select my gpx tracks any more.
When I change it back to "internal storage" I can show my tracks on the maps again.

**Comment by vshcherb** [comment]
That doesn't sound good, did you grant permssion on external storage, are the maps copied as well?

The other to get your gpx files is to press button Share and you can share them 1 by 1.

**Comment by spacemanspiff2007** [comment]
I did grant file permissions in the app permissions.
When I change the folder in the general settings I did not get any prompt to copy files and an empty folder structure is generated. However nothing gets copied, all folders are empty.
The maps have then disappeared from the local maps overview.
When I change the folder back the map appears again under local maps.

Unfortunately I can not share the gpx files since they are in the "internal storage" (/data/user/0/net.osmand.plus/no_backup).
When the shared application launches I get a permission error.
Can I provide you with any further information/logfiles/screenshots/whatever?

**Comment by vshcherb** [comment]
@spacemanspiff2007 Something is definitely wrong. When you click on share button, it should generate a "special" file and grant permission to share app, this is how it was tested. No copied files also proves the point that application somehow couldn't get enough permission.
There should be at least 4 type of memories, please try External Storage cause usually it doesn't require extra permission. Shared storage should be allowed to write after permission is granted "Video, Media access permission", though it could be buggy on some Android devices. External Storage should copy to sdcard/android/net.osmand/data/...

**Comment by spacemanspiff2007** [comment]
Running OsmAnd+ 2.5.4 on a OnePlus 3 with Android 6.0.1:
I just tried to share my gpx file with the share-button but I get the "Insufficient Access" error.
When I change to "External Storage" (/storage/emulated/0/Android/data/net.osmand.plus/files) I just get an empty folder structure. Also no "copy" option whatsoever appears.
When I change back to "Internal Storage" everything appears again but sharing is not possible (Insufficient Access). Was sharing verified with internal storage?
On app I tried sharing with showed the following errormessage:
`/data/user/0/net.osmand.plus/no_backup/tracks/rec/2016-09-13_11-44_Tue.gpx: open failed: EACCES (Permission denied).`
From the filename it does not seem like a special file is created!
Maybe there is a mixup with `net.osmand` and `net.osmand.plus` in the file paths?

**Comment by spacemanspiff2007** [comment]
With OsmAnd+ 2.5.4 and Android 7.0 the copy dialog appears. Is fixed for me. Thanks for your support.

**Comment by philip-n** [comment]
I'm afraid I have the same problem as described above. I'm running OsmAnd+ 2.8.2 on Android 7.0 (Samsung S6). I had initially installed OsmAnd+ on the internal storage (/data/user/net.osmand.plus/no_backup) and it's been working fine. By now, I have some 20 recorded GPX tracks that I need to copy to my PC. They are listed and displayed just fine inside OsmAnd+, but I cannot access them as the folder is not accessible and sharing does not work (no file permissions etc as mentined above).

Changing the storage to "external storage 1" (/storage/emulated/0/Android/data/net.osmand.plus/files) shows the copy dialog and I confirm, but this only creates the folder structure without cactually copying any files. On the next restart, OsmAnd+ shows a "Welcome to OsmAnd+" dialog, asking if I want to download some maps to start, ... . None of the downloaded maps or recorded tracks are visible inside OsmAnd+.

Changing the storage back to internal storage "fixes" the reset (all data is shown again in the app), but does not bring me closer to actually transferring the GPX-files from the mobile to the PC.

Any further advice on this?
