### ISSUE TITLE
In the "Tour details" screen, the alignment of the last column is uneven

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2989]
In the **Tour details** screen, all the rows in each column must be aligned.

But whenever the third column has **km** as unit (instead of **m**), the last column gets shifted to the right by one character.

See this [example](https://cloud.githubusercontent.com/assets/12786225/12213046/16c1a194-b672-11e5-9220-4d156b4bc0bd.png)

Here, the first four rows of the table have one alignment, but the last four rows have another alignment with a shift of one character.

**Desired:** The alignment of the last column should be the same regardless of the unit used in column#3.
(this problem may be there only when **metric** system is used, not in **imperial** system).

**Comment by raindropsfromsky** [comment]
p.s. I think the same problem may be there even in Column#1, in which case, all the other columns would be shifted to the right by one character.

So even Column#1 needs to be padded to accommodate both units: **m** and **km**.

**Comment by vshcherb** [comment]
Not planned to be fixed now
