### ISSUE TITLE
terminus is not displayed in stop list

### ISSUE THREAD

**Issue by miklcct** [osmandapp/Osmand#2990]
The terminus of a circular bus route (i.e. start and end stops/platforms are the same) is not displayed in OsmAnd.

1. Enable the public transport layer
2. Click on a stop of a circular route (e.g. Bus 701 http://openstreetmap.org/relation/3518858 )
3. Click on that route
4. Open the stop list
The ending stop (e.g. Hoi Lai Estate) is not displayed on the stop list.

**Comment by vshcherb** [comment]
For me it looks like a big surprise, I didn't expect that Relation could contain same entity with same  role twice. So the error is on the very low level and it will be very hard to fix.

**Comment by vshcherb** [comment]
fixed
