### ISSUE TITLE
[Feature request] Adding Bulgarian TTS

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#2992]
Recently, I've seen many requests concerning adding Bulgarian voice guidance. I think we should add it.

**Comment by vshcherb** [comment]
We need somebody with language knowledge, usually we kindly request native speakers to help us if they have technical background. It will be very hard to do ourselves in the end we will still need native person, so we will be looking for a volunteer and we could provide help how to configure it.

**Comment by sonora** [comment]
See here: #3209. Same info + answers apply.

**Comment by edy1** [comment]
Any news on this?

**Comment by psyhlo** [comment]
How can i help for adding Bulgarian guidance?

**Comment by sonora** [comment]
Please have a look at 'Creating a New TTS Voice Language' at http://osmand.net/help-online/technical-articles.

**Comment by psyhlo** [comment]
Is it mandatory to have voice folder?
Can i make only tts guidance?

**Comment by sonora** [comment]
Don't bother for now, creating the `bg_tts.js` file is what matters primarily. There are a number of languages which currently have no voice subfolder, i.e. no recorded `*.ogg` files.

**Comment by psyhlo** [comment]
ok thanks i'll try to steal some time to make it

**Comment by atdimitrov** [comment]
@psyhlo, is there any progress on this? If not, I'm interested in adding it.

**Comment by psyhlo** [comment]
i forgot about it :D
it is finished but not tested
i'll make pull request

I want to test them first, before pull request, any one know how to do that :)

**Comment by sonora** [comment]
Yes, simply create a folder bg-tts manually under OsmAnd's voice subfolder (next to where the other xx-tts folders are). Put your bg_tts.js file in it, then it will be selectable in OsmAnd.

**Comment by psyhlo** [comment]
May be i'm missing something it doesnt sounds like bulgarian at all :(

**Comment by sonora** [comment]
Does the TTS engine on your device support Bulgarian?Go to the Android (not OsmAnd) settings and chose Bulgarian. If there is no such option, maybe go to the Play store and test some third party TTS engines.

**Comment by psyhlo** [comment]
found one tts engine that support Bulgarian - espeak ng in play store or https://github.com/espeak-ng/espeak-ng
the translation need some tweaks

**Comment by psyhlo** [comment]
i've made a pull request and hope someone continues my work and make it better if the request is accepted :)

**Comment by vshcherb** [comment]
Accepted - https://github.com/osmandapp/OsmAnd-resources/pull/656
Please test it.

**Comment by psyhlo** [comment]
@vshcherb thanks
@atdimitrov can you test it too

**Comment by atdimitrov** [comment]
> @atdimitrov can you test it too

Sure, I'll try to squeeze it in the schedule :)

**Comment by atdimitrov** [comment]
I've tested it, it works as expected. There are few phrases that sound weird but other than that it is decent.

The problem however is that the experience is as good as the TTS engine is. There are only few engines that support bulgarian and the quality varies between average and bad. Because if that I'm looking into creating bulgarian voice files. Would such PR be accepted? Also, are there any requirements on how it is executed?

**Comment by sonora** [comment]
Just look at the config file to see what vocabulary is needed, then record and provide as a  PR in the same structure as already existing recorded voices. All file names must of course correspond to the .ogg's specified in your config file.
