### ISSUE TITLE
show city next to search result

### ISSUE THREAD

**Issue by schiessle** [osmandapp/OsmAnd#2993]
If you search for something which exists multiple times in your region, e.g. a shopping center like Ikea, you get multiple results and it is hard to judge which one ist he right one. On the search result, the only additional information you have is the distance to your current location. But that's not always enough, especially if you are in a foreign location. Therefore it would be really helpful to add some additional information to the search result, like for example the city.

**Comment by vshcherb** [comment]
It's kind of duplicate nice to have.  Though it doesn't require full results geocoding and could be implemented just for city name.

**Comment by sonora** [comment]
This is requested very frequently, guess it should be in our 3.0 milestone.

**Comment by vshcherb** [comment]
@sonora Very unlikely it will happen soon. The frequency of requests shows popularity but doesn't show the complexity. Ideally all POIs should have Street, City. City is not enough but in order to achieve it addresses should be prepared in the data which makes that story difficult to implement

**Comment by schiessle** [comment]
@vshcherb why not doing it step-by-step if showing only the city would be easier? Sure, showing the complete address would be the perfect solution but having just the city would make search in many cases already much easier.

**Comment by vshcherb** [comment]
If we are talking about popular POI in large cities than their name is mostly irrelevant. If we are talking about correct information it requires address lookup for each poi.

**Comment by jfburke3** [comment]
Would displaying the value for the "branch" tag be easy, if the value is not null? E.g., a displayed result might appear as "Wells Fargo (Wildwood)" for a Wells Fargo bank location with `branch=Wildwood` set in OSM.

I don't know about the rest of the world, but in the US and Canada, it is fairly common for some types of businesses to identify various locations by branch.

**Comment by EvanCarroll** [comment]
@jfburke3  that be preferable imho and no more difficult. We track that here https://github.com/osmandapp/OsmAnd/issues/6947 For reference the OP is from Stuttgart, Germany. In Stuttgart there are five Starbucks. Knowing that they're all in Stuttgart is not very useful, however the branch names seem much more valuable:

* Koenigstrasse 44
* Stuttgart, Koenigsbau Passagen
* Stuttgart HB Kiosk
* Milaneo Kiosk
* Milaneo

What would you rather have @schiessle those names above or just "Stuttgart". If you want the branch names, would it be cool to close this as a duplicate of this https://github.com/osmandapp/OsmAnd/issues/6947 ?

**Comment by schiessle** [comment]
I agree, with your example the branch name makes totally sense. I just wonder if this always works? For example, assume that I'm in a place with three IKEA around. All with more or less the same distance, will in this case the branch name also tell me which one is the right one? Or will in this case the address/city be the better differentiator?

**Comment by EvanCarroll** [comment]
Branch is left for the operator to assign. The idea being if the operator disambiguates their stores we do not have to. In the case of multiple stores in the same city, you'll typically find the name of the commercial center they're located in but not always. Sometimes, like with Dominos, you see the street name. I don't think there are _ever_ two IKEA's in the same city. At least in the USA. Looking it up the `tag:branch` for the IKEA, is always city. You can see it with their [store locator,](https://www.ikea.com/us/en/?ref=gwp-start)

```text
IKEA Houston
7810 Katy Freeway
Houston, TX 77024
```

Houston is the branch.

**Comment by mmacura311** [comment]
This is also a problem when using osmand with android auto. I search for "decathlon" or "ikea" and I have no clue which one to select, as there are multiple in roughly the same air distance.
It would be great to see a city and maybe even full address of the poi.

**Comment by scaidermern** [comment]
I guess it is an expensive operation to perform reverse geocoding for each search result. Maybe this step can already be performed during map generation?

**Comment by sonora** [comment]
Organic maps seems to have this pretty instantaneous, we could research how.

Also, not sure if this is a notable relief, but I think you need the street address on the search result screen only for vicinity hits, maybe closer than 10 km or within the same town, while for farther hits the town or village should suffice?

So I guess either our search index could tag all hits with a municipality denoting town/village, or we create such a municipality raster and an associated lookup method which would use any arbitrary coordinates input to output the municipality.

**Comment by canoine** [comment]
I met an annoying case today : a hamlet with a common name :

[![Screenshot-20230714-165047-Osm-And.jpg](https://i.postimg.cc/cHStsxL5/Screenshot-20230714-165047-Osm-And.jpg)](https://i.postimg.cc/cHStsxL5/Screenshot-20230714-165047-Osm-And.jpg)

Here, I need to know how far is my destination. But that's **precisely** what I **don't** know, as I need a navigator to go there.
After half an hour of "die-and-retry" tests to find the right hamlet, I asked my wife to run Waze on her phone.

Is it possible to add, say... the postal code of the results ?

**Comment by lcosmin** [comment]
> I met an annoying case today : a hamlet with a common name :
> [...]

Annoyances like this make the search sometimes impossible to use. 

Not sure if this approach is possible to implement, but when the exact address is missing for a search result, the closest (important) street could be located (like with a 100 m radius), then the "next big feature" that contains the street (e.g. city), then the next big feature that contains the city (like the local region name or whatever administrative division there is in that country) and then the  country itself. 

So, I have 3 Hornbach stores near me,  for all of them, when I search, I get "HORNBACH - home improvement store ~12km".  Needless to say the results are pretty useless. 
But with the above mentioned heuristic, I could get:
* "Hornbach - near Str. Drumul Gilaului, (Bucharest, Bucharest, Romania)"  - the part in parenthesis could be omitted since it coincides with my GPS position.
* "Hornbach - near Str. Hornbach, Domnesti, Ilfov(, Romania)" - similarly, the part in parenthesis could be ommited since it coincides with my GPS position
* "Hornbach - near Calea Balotești, Balotești, Ilfov(, Romania)" 

I realize this is probably easier said than done, but maybe it's something that could be taken into consideration.

**Comment by blackboxlogic** [comment]
A **similar issue** but at higher scale, that may be easy to fix simultaneously.

When I **search for a town by name** (for example "Concord"), OsmAnd shows a list of results including: Name, Type, Distance. But **there are two Concords**, at 67 miles and 91 miles away, I don't know which one I want. I'm trying to go to Concord, Massachusetts, but I must use **guess-and-check** to find it.

The search result would be much more helpful if (when searching for municipalities) it named the next one or two higher municipal boundaries. Example:
* Concord (Massachusetts)
* Concord (New Hampshire)

Or maybe, small text at the bottom of the result, the full chain of higher boundaries:
* Concord (Middlesex County, MA, USA)
* Concord (Merrimack County, NH, USA)

**Comment by vshcherb** [comment]
Technical plan:
- We need to have 2 options (calculate correct cities based on boundaries on server and encode in data) and calculate runtime (for live maps)

**Comment by vshcherb** [comment]
Technical note:
- [ ] First of all we need to store city information for POI.  As it duplicates a lot and we want to compress - proposing new OBF structure. https://github.com/osmandapp/OsmAnd-resources/pull/new/cityPoiIndex
- [ ] We can index POI (to Address search as last step - when we about to write OBF or as we go - same code as for Street -> City detection (getOrRegisterStreetIdForCity). Multiple cities could belong to same POI

**Comment by vshcherb** [comment]
- Android complete - new maps required

**Comment by ivanPyrohivskyi** [comment]
Need new maps (October 2024) for test

**Comment by dmpr0** [comment]
# Review 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>"silpo"</th>
        <th>Selected brand</th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/716b00d2-05bd-45ce-a3d0-76027024a762"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/0112a700-1727-4b2a-b6df-bd4610665acf"  width="300" height="auto"/> </td>
        <td><video src="https://github.com/user-attachments/assets/733b34df-b90a-472f-ad22-60a425086e1f
"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details> 


- [ ] Cities doesn't visible while searching by brand name (not selecting Brand)

**Comment by MarioSwitch** [comment]
@dmpr0 Build 4.9.0#3416m
Not reproduced with Hauts-de-France map (october 2024, with Live Updates)

**Comment by sonora** [comment]
I have tried with latest maps and latest nightly - I never see a city or location under any search result...

**Comment by vshcherb** [comment]
To fix:
- [ ] Indeed latest app + latest maps doesn't show city names in search
- [ ] https://github.com/osmandapp/OsmAnd/issues/2993#issuecomment-2397118471

**Comment by vshcherb** [comment]
@sonora tested again in Netherlands - sometimes it shows. Germany maps need to be regenerated, today will be scheduled tomorrow should be available to redownload - @ivanPyrohivskyi will let know  

Fixed - https://github.com/osmandapp/OsmAnd-tools/pull/928

**Comment by vshcherb** [comment]
- [ ] Regenerate europe maps
- [ ] Crash on iOS device

**Comment by vshcherb** [comment]
Maps with Germany France updated and cities are present

**Comment by MarioSwitch** [comment]
@vshcherb No updates available, search results doesn't show cities with latest Live Updates (3:00 PM GMT+2)

**Comment by pebogufi** [comment]
> @vshcherb No updates available, search results doesn't show cities with latest Live Updates (3:00 PM GMT+2)

Confirm that. No cities...
Maps downloaded 2024-10-15 15:03
France_great-east_europe_2.obf.zip
Germany_baden-wuerttemberg_europe_2.obf.zip

**Comment by MarioSwitch** [comment]
@pebogufi I don't know if "updates" are Live or not?

Because app still says latest (non-Live) update for France and Germany are Oct 1, 2024...

**Comment by pebogufi** [comment]
I removed last obf, downloaded the available from https://download.osmand.net/list.php and installed them.
Same result with Live on/off (for test "off" i renamed dir)

**Comment by MarioSwitch** [comment]
> @sonora tested again in Netherlands - sometimes it shows. Germany maps need to be regenerated, today will be scheduled tomorrow should be available to redownload - @ivanPyrohivskyi will let know  
> 
> Fixed - https://github.com/osmandapp/OsmAnd-tools/pull/928

You're right, it works in the Netherlands 😅

![Screenshot_20241015-155715.png](https://github.com/user-attachments/assets/a8af9d13-2db8-4a0a-bac9-29679120524f)

**Comment by vshcherb** [comment]
Maps needs to be deleted and redownloaded. Please let us coordinates and poi category to test

**Comment by MarioSwitch** [comment]
It works after re-download maps!

![Screenshot_20241015-170037.png](https://github.com/user-attachments/assets/faebf04a-224a-425d-8d42-0d5f167260df)

**Comment by MarioSwitch** [comment]
> Please let us coordinates and poi category to test

It's around Arras, Hauts-de-France, France

**Comment by sonora** [comment]
No luck here, also with new map:
![Screenshot_20241016-182234_OsmAnd~](https://github.com/user-attachments/assets/295a1841-0ece-40b4-8c41-5df8fc5d486a)

Map position somewhere near Stuttgart.

**Comment by MarioSwitch** [comment]
@sonora 

Reproduced, Burger King near Stuttgart

![Screenshot_20241016-203557.png](https://github.com/user-attachments/assets/1a7d9852-ea87-4a0e-83e9-5aeecb6dfc4f)

**Comment by vshcherb** [comment]
Combined maps will be regenerated tomorrow and once tested, updated will be posted

**Comment by vshcherb** [comment]
Right now you can download individual maps of Stuttgart

**Comment by ivanPyrohivskyi** [comment]
Test on countries
Germany_baden-wuerttemberg_europe_2.obf Germany_bayern_europe_2.obf Germany_hessen_europe_2.obf Germany_niedersachsen_europe_2.obf Germany_nordrhein-westfalen_europe_2.obf Ukraine_europe_2.obf

**Comment by vshcherb** [comment]
Follow up to display street name here https://github.com/osmandapp/OsmAnd/issues/18668, planned for 5.2
