### ISSUE TITLE
Cannot change color of GPX waypoint

### ISSUE THREAD

**Issue by jkufner** [osmandapp/OsmAnd#2996]
When editing GPX waypoint, there is no way of changing the color of the waypoint. The color is correctly loaded and stored to GPX file and I can edit the GPX file on computer and send it back to change the color. But there is no way to change color on the phone, directly in Osmand.

Osmand version: few days old nightly build -- 2.4.0#18062M, 2016-08-14

**Comment by vshcherb** [comment]
Valid point

**Comment by dmpr0** [comment]
Fixed in current versions.
