### ISSUE TITLE
(Germany) Wrong shields for tertiary roads starting with A or B

### ISSUE THREAD

**Issue by daganzdaanda** [osmandapp/Osmand#3000]
Using Osmand 2.3.5, with current Germany-Bayern-Europe.obf map downloaded from within the app.

I've noticed a funny little bug with the shields for tertiary roads in Bavaria. 

E.g. in this area in Augsburg-County:
http://www.openstreetmap.org/#map=14/48.4080/10.6822
there are tertiary roads that have the refs "A 33" and "A 5". Also, the Autobahn "A 8" motorway is close by. 
Osmand 2.3.5 seems to see the "A" at the beginning of the ref as an indication that the road is a Autobahn / motorway. The result is, that the tertiary roads also get a blue motorway shield with just the number "33" and "5".

Same issue close to Ansbach:
http://www.openstreetmap.org/#map=14/49.2760/10.6810
Tertiary "AN 12" gets a blue shield "N 12" (the A has been cut off).

It also works with "B" (for primary "Bundesstraßen") as seen close to Bayreuth:
http://www.openstreetmap.org/#map=17/49.97073/11.52803
Here, tertiary road "BT 14" gets the shield "T 14" in the same style as the primary "Bundesstraße" B 85.

This may only affect Germany and maybe only Bavaria (other German states have other naming schemes for their tertiary roads). I haven't checked other countries since I don't know where to look for possible errors.

Probable solution: decide the style of the shield by looking at the class of the highway, not at the letters of the ref. Use the full ref for tertiary roads.

**Comment by xmd5a2** [comment]
Fixed
https://github.com/osmandapp/OsmAnd-resources/commit/4c21bd2b02b614519f1d967f07e118313aebf74f
https://github.com/osmandapp/OsmAnd-resources/commit/8559213de6b27707e2a910e6be02ba25575b8fd6

**Comment by daganzdaanda** [comment]
Thanks, that was quick!
But maybe this introduces a new wrong label for Bundesstraßen that are trunks? See the [comment on the commit](https://github.com/osmandapp/OsmAnd-resources/commit/8559213de6b27707e2a910e6be02ba25575b8fd6#commitcomment-18832480)
