### ISSUE TITLE
Some poi icons are missing

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/Osmand#3001]
- Beachvolleyball
- Equestrian
- Standpipe
- Metal construction craft
- Window construction
- grit bin

Maybe more

#18318M

Greetings Simon

**Comment by xmd5a2** [comment]
This is a known issue and we will come back to it periodically.
Added beachvolleyball, equestrian, metal construction, window construction icons.

**Comment by jf-simon** [comment]
Thanks
