### ISSUE TITLE
Idea: Best view on navigation screen

### ISSUE THREAD

**Issue by Chti-Steph** [osmandapp/Osmand#3002]
In the navigation sreen, I would like to have 2 improvements:
– The navigation information Can only be white or transparent.
=> Should be good to be half transparent.

– The order of the right information cannot be changed.
=> Allow to change the order or group it by type (mph, time…) 
=> and allow to change the text size or bold.

![screenshot 94](https://cloud.githubusercontent.com/assets/21244834/17977028/4999776c-6af0-11e6-8c94-bff51069df9d.jpg)

Thanks, regards

**Comment by Unnamed-1** [comment]
I think this can be merged with #3121 .

**Comment by sonora** [comment]
Yes, let us merge with #3121.
