### ISSUE TITLE
Roundabout 1st exit: Wrong turn angle displayed for left-hand driving

### ISSUE THREAD

**Issue by vrtareg** [osmandapp/Osmand#3003]
Hi

I havenoticed strange icon for roundabout 1st exit.

Can be map but not sure. 

Regards, 
Areg 

![screenshot_2016-08-20-15-13-29](https://cloud.githubusercontent.com/assets/2562730/18010090/584e7aa4-6baf-11e6-92f7-386615c128a0.png)

**Comment by vrtareg** [comment]
Forgot to mention 
Latest maps and nightly.
Region of driving UK.

**Comment by vrtareg** [comment]
Same again ....
Looks like that icon is for opposite way driving region. 
This is for A14 roundabout from Fulbourn side.


![screenshot_2016-08-29-16-00-31](https://cloud.githubusercontent.com/assets/2562730/18060761/ce458e40-6e17-11e6-999a-9ce39852ec25.png)

**Comment by sonora** [comment]
@vshcherb Have not checked to depth, but chances are that for leftSide we need to adjust turnType.getTurnAngle() in https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/views/TurnPathHelper.java#L295, maybe with a minus sign or something.

**Comment by vrtareg** [comment]
Hi 

Any progress on this? 

Regards, 
Areg

**Comment by sonora** [comment]
@vshcherb Looks like `turnType.getTurnAngle()` returns the same number regardless if leftSide is true or false. Hence we can either fix this directly in TurnType.java, or via https://github.com/osmandapp/Osmand/commit/8a83ec45743f1c647ccfe070190f3cc7526134ff.

I leave this open for you to decide it we should rather fix it in turnType's turnangle.

**Comment by vshcherb** [comment]
As I remember this is wrong commit, though I need to check. We have this bug mostly for 1st exit on roundabout, in your case the turn angle is flipped for all exits.

**Comment by sonora** [comment]
True, I never noticed that only first exits seem affected...

**Comment by sonora** [comment]
I just notice we have no good analogy between the angle calculation here https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/routing/RouteProvider.java#L922 (!osmandRouter case) and here https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/routing/RouteProvider.java#L957.

Particularly the reference to `res.size() - 1` in line 960 bogs me, and also we have a roundabout condition in the first block but not in the second?

**Comment by vshcherb** [comment]
Please test it.
