### ISSUE TITLE
Turn lanes doesn't fit in screen and shows wrong direction 

### ISSUE THREAD

**Issue by vrtareg** [osmandapp/Osmand#3004]
Hi 

I was driving in Copenhagen and noticed that lines direction and turn sign acted a bit wrong. 

Lines sign was not fitting in screen and together with direction sign was showing left turn instead of right when route was correctly directing to right ...

Latest maps and nightly.
Driving region Europe. 

Regards, 
Areg 

![screenshot_2016-08-26-16-44-14](https://cloud.githubusercontent.com/assets/2562730/18010395/9a438c1e-6bb0-11e6-99e6-cca72d8357c7.png)

**Comment by Chti-Steph** [comment]
Hi, I have also seen this case in Spaine 3 or 4 times. The voice is also wrong.

**Comment by vrtareg** [comment]
Hi 

Any progress on this? 

Regards, 
Areg

**Comment by sonora** [comment]
@vrtareg What is the thin red line, are you navigating by GPX with the "reverse track" feature on or something?

**Comment by vrtareg** [comment]
Hi Hardy

No it is just all my travel GPX track actually.

The parallel line is the one that I drove before off that road.

You can see that I am going to turn right and sign shows turn left . ...

Regards ,
Areg



On Tue, 1 Nov 2016, 8:20 a.m. Hardy, <notifications@github.com> wrote:

@vrtareg <https://github.com/vrtareg> What is the thin red line, are you
navigating by GPX with the "reverse track" feature on or something?

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/osmandapp/Osmand/issues/3004#issuecomment-257511692>,
or mute the thread

**Comment by sonora** [comment]
Interesting: I had an old Denmark map on my phone (June11, 2014), and just tried this turn using that map (but current OsmAnd nightly), and our turn arrow appears correctly ...

**Comment by vrtareg** [comment]
Could be. 
I can’t test it now so this I'd unconfirmed for now. 
I will try to simulate somehow and update issue.

**Comment by vshcherb** [comment]
Double checked that turn currently there is no issue but we will double check the lanes.
