### ISSUE TITLE
[Android] Download "Contour lines" crashes the app

### ISSUE THREAD

**Issue by pihug12** [osmandapp/Osmand#3006]
Manage Map Files > Europe > France > Midi-Pyrénées > Contour lines :arrow_right: crash
The same bug is occuring with several regions.

Tested with two devices (CM12.1 / Android 5.1).
F-Droid builds : Osmand~ 2.3.5 and Osmand~ 2.4.4

---

**EDIT:** just saw https://github.com/osmandapp/Osmand/issues/2787 
It works after installing https://f-droid.org/repository/browse/?fdid=net.osmand.srtmPlugin.paid
Too bad it crashes without displaying this info. :worried:

**Comment by homersimpsons** [comment]
Do you get the contour lines add-on (from F-Droid)?

**Comment by pihug12** [comment]
I just did and it now works. I think this info should be displayed instead of causing a NullPointerException.

**Comment by vshcherb** [comment]
Couldn't reproduce it, it might be related to a specific build of FDroid. Actually this button suppose to open Google Play with application, though I'm not sure how it works for FDroid build

**Comment by pihug12** [comment]
Here is the **exception.log**: https://gist.github.com/pihug12/ce5aa911ca8d3ba413a1e03aef036888
I don't have Google Play (nor any GApps) on my devices.

**Comment by vshcherb** [comment]
Fixed
