### ISSUE TITLE
Wikipedia and website of POI incorrectly displayed

### ISSUE THREAD

**Issue by verdulo** [osmandapp/Osmand#3008]
Properties of POIs are not correctly displayed: if object has tag wikipedia: then OsmAnd displays "Globe icon" instead of W-icon; and if point has both website: and wikipedia: tags then no website link is displayed in the app (only link to wikipedia is displayed).

**Comment by vshcherb** [comment]
Please provide screenshot and object to check.

**Comment by verdulo** [comment]
The error occurs with ANY (point, way, relation) object, example:
https://www.openstreetmap.org/way/337765496

![screenshot_2016-08-27-17-53-59](https://cloud.githubusercontent.com/assets/16842967/18028451/a79288e4-6c77-11e6-85e0-8a53f644a246.png)

In the screenshot you can see only wikipedia link (with wrong icon), but not website link to www.zoo.opole.pl.

**Comment by vshcherb** [comment]
The code is here that makes url out of wikipedia https://github.com/osmandapp/Osmand/blob/master/OsmAnd-java/src/net/osmand/osm/edit/EntityParser.java#L132, though what is not clear why we don't see wikipedia article (wikipedia icon).

I couldn't say that's a bug yet it is possibly designed in such a way.

**Comment by sonora** [comment]
When we determine if an object is tagged with a web site,.`getWebSiteURL(`, the exact code Victor references, evaluates if an object is tagged with either `wikipedia` or `website`. If `wikipedia` is found this takes precedence, any additional `website` is ignored. This is the primary bug and needs fixing.

Secondary: The result is always displayed next to a hyperlink ("globe") type icon, no matter if it resulted from a wikipedia or website tag.

**Comment by sonora** [comment]
I would think something like this https://github.com/osmandapp/Osmand/commit/7b0eecef194419643e861a58836df8bd3412337d could basically fix it, but cannot test right now.

It also needs to be investigated if we want to map the OSM `wikipedia` tag to something like "wikipedia" in our `AdditionalInfo` LinkedHashMap, or if there was a good reason reasons to map it to "website" there.

**Comment by vshcherb** [comment]
Looks like the fix is correct

**Comment by verdulo** [comment]
It's not fully repaired: still no Wikipedia 'W' icon is showed, or the text 'Wikipedia' should be translatable (it has been added to weblate when I reported the bug, but it's not displayed in the app; although it would be better to don't show any text, just 'W' icon).

**Comment by jayvdb** [comment]
Maybe the fix hasnt been released yet?
