### ISSUE TITLE
Turn:lanes oddities without reason in the data (more)

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#3009]
nb-2016-08-23

![screenshot_2016-08-25-16-43-02_tl_error](https://cloud.githubusercontent.com/assets/8266355/18022124/99cdeb62-6bec-11e6-9a4a-108181ee4582.png)
Going straight, both through arrows should be yellow. way 332306827.

![screenshot_2016-08-25-16-07-39_tl_from_stern_not_from_spreestr](https://cloud.githubusercontent.com/assets/8266355/18022224/5d1c2db8-6bed-11e6-8d1a-d247821edcec.png)
TL through|through|through;right from Spreeweg (way 206170870) should be shown, added 2016-07-27, instead we see already the upcoming turn lanes from Grosser Stern (way 30194726), added the same day.

**Comment by vshcherb** [comment]
(1) confirmed there is a bug and @xmd5a2 we will need to have a test created
(2) there is no "intersection", technically there is no road split cause you can move only to 1 direction to the roundabout and in that case we don't display turn:lanes, there is another open issue to display "turn:lanes" also at "road merge intersection" (this is the case here).

**Comment by polarbearing** [comment]
(2) - just want to add that Grosser Stern is not a roundabout, it is just circular traffic. However the turn:lanes on the roads into the circle help to position yourself for the planned exit from the circle, as the lanes in the circle are spiralling outwards. 

There is a true roundabout further west, [Ernst-Reuter-Platz](https://www.openstreetmap.org/search?query=ernst-reuter-platz%2C+berlin#map=19/52.51260/13.32187) which also has spiralling lanes in the circle and preparatory turn:lanes leading into. There, only the roundabout icon is shown although the turn:lanes might be helpful as well. Maybe we need a strategy for those large roundabouts/circular traffics in general.

**Comment by vshcherb** [comment]
I definitely agree though they fall into the case of merging roads and if you think in many cases when 2 roads are merging, it will be also good to see it. 
I'm actually more surprised that we don't see roundabout icon with exit number.

**Comment by vshcherb** [comment]
@xmd5a2 please add to the test left turn to Steubenplatz ( http://www.openstreetmap.org/export#map=19/52.51639/13.26041) it was also incorrect. Right turn to Steubenplatz was correct but we could add that test too.

**Comment by polarbearing** [comment]
In (2) we don't see the roundabout icon because the place is not a roundabout. Circular traffic has to give way to incoming traffic, which is the opposite of the roundabout definition. Thus there is no junction=roundabout.

**Comment by xmd5a2** [comment]
@vshcherb tests added
