### ISSUE TITLE
Separate route-progress bar from lane widget

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#3010]
nb-2016-08-23

route-progress bar in a re-calculation situation appears in the same widget as the lanes. Having only one lane, it looks unnaturally left-aligned, with lots of white space. 

If you cannot separate the widgets, maybe the lanes display could at least be centered. 
![screenshot_2016-08-26-14-22-16_left_aligned_panel](https://cloud.githubusercontent.com/assets/8266355/18022276/b9fb3c4a-6bed-11e6-8cf1-b95bc3b20817.png)

**Comment by sonora** [comment]
Let's merge to #4149.
