### ISSUE TITLE
Easier route making using favorites

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#3015]
When you are creating a route from favorites, only the last one is added as map marker.
Steps to reproduce:
go to My places - My favorites and tap the flag button. Add several favs.

Tap flag button again.

Go to map screen and tap navigation button. In the context menu, you'll see My position and the last fav as start and end.
![screenshot_2016-08-28-17-27-24](https://cloud.githubusercontent.com/assets/12711814/18034476/dd3cb65c-6d46-11e6-8949-e38c34c3d655.jpg)
![screenshot_2016-08-28-17-27-40](https://cloud.githubusercontent.com/assets/12711814/18034475/dd3cb530-6d46-11e6-9785-17d75e81195a.jpg)

However, if you select all favorites and then tap the three-dot button in the map marker menu on the top of the screen, you see them all.

Suggestion: create route including all favs as map markers after selecting them. The step of 
going to map marker menu to add them all is not obvious.

**Comment by vshcherb** [comment]
We plan to improve the route using all map markers

**Comment by HJarausch** [comment]
Hi,
it would be nice if one could import waypoints from other software (like JOSM) and generate a route from these.
Or is this possible already? I haven't found anything how to do this.

**Comment by vshcherb** [comment]
We are working on new iteration to make Markers more usable. Importing GPX, Favorites -> Markers is 1 click, planning route from markers will be a nice screen in 2.8.
