### ISSUE TITLE
Gpx Track Road (Map) Matching

### ISSUE THREAD

**Issue by boldtrn** [osmandapp/Osmand#3016]
I have not found a similar issue, so I thought that I might open one.

Whem importing a Gpx Track, the Track seems not to be matched to existing roads. 

There are turn instructions were actually no other road to turn exists (not even a a small path or something). On the other hand, there are no turn instructions when a turn instruction would be required (the track is only slightly bending - but it's acutally a road change). Roundabouts are not recognized. 

I know that map matching is not trivial and I am not sure if the implementation overhead justifies the usage, but it would be a really nice to have feature.

**Comment by sonora** [comment]
You need to provide a track so we can check what you are talking about, or explain how you created the track so we can try to reproduce this, or else we cannot help.

**Comment by vshcherb** [comment]
Yes it is a known issue, there were already 2 attempts to implement that feature and both failed.

**Comment by boldtrn** [comment]
> Yes it is a known issue, there were already 2 attempts to implement that feature and both failed.

Ah ok, sorry. I did not know that and could not find the related issues. Map matching is pretty tricky unfortunately.
