### ISSUE TITLE
Map show when arrived at destination not wrong color scheme

### ISSUE THREAD

**Issue by PanderMusubi** [osmandapp/Osmand#3017]
When arriving at your destination and getting the message `You have arrived at your destination` with the options `FIND PARKING`, `RECALCULATE ROUTE` and `FINISH NAVIGATION`, the map is shown in the wrong color scheme. The map is shown the default color scheme (e.g. bright for daylight) when the navigation itself was in dark colors for night time navigation. Please fix this to show a map conform to the map configuration and prevent decreasing night sight of the user.

**Comment by sonora** [comment]
The app goes back to the Browse map profile, so all you have to do is set the Configure map/day/night view setting there to the same value you have in the profile you use for navigation (car/bike/ped).

**Comment by PanderMusubi** [comment]
Okay, than this can be closed as invalid bug report.
