### ISSUE TITLE
Report number of time maximum speed was exceeded

### ISSUE THREAD

**Issue by PanderMusubi** [osmandapp/Osmand#3018]
When you have reached your destination, please report the number of times you have exceeded the maximum speed. The minimal value is of course 0 and that should also be shown as can work as a reward for obeying the speed limit.

A separate issue could concern on also appraising or reporting (no scolding or putting a value on it because it was needed or the map data was incorrect) the user for not exceeding or exceeding the speed limit, e.g. "Well done, you did not exceed the maximum speed." or "You exceeded the maximum speed X times."

**Comment by sonora** [comment]
Not a very mainstream request, if you ask me ...
You are probably aware that you can have exceeding the speed limit announced and indicated during your trip, which is the much more relevant information that "counting" this, IMHO.

**Comment by PanderMusubi** [comment]
Understandable that the count in OsmAnd is not what is actually happened. So it has to be phrased like that too. Nevertheless a way of rewarding a driver if OsmAnd did not had to notify it.

**Comment by polarbearing** [comment]
Difficult to implement reliably as well. You can have short GPS displacement errors e.g. from a temporary reflection which result in speed spikes, so you would need advanced filtering algorithms. Also the counting is difficult, when someone drives approximately at the limit, you get numerous measurements above and below the limit.

I would not see this as a feature many people expect from a navigation tool. Monitoring the driver behaviour could be a separate app, if needed.

**Comment by sonora** [comment]
No action planned.
