### ISSUE TITLE
Show zero decimals in distance

### ISSUE THREAD

**Issue by PanderMusubi** [osmandapp/Osmand#3019]
Currently, for distance the zero decimals are not shown in distance for integer numbers which are between non-integer numbers for which it is shown. This makes it a too much visually altering experience for the user and is distracting and contributes to a higher risk.

When distance is alternating between numbers which are very similar, but different number of digits are shown, this is bad for readability as the `km` also jumps left and right. See:

    4.99 km
    5 km
    4.99 km
    4.98 km
    5 km
    5.01 km
    4.99 km
    5 km
    5.01 km

or

    49.9 km
    50 km
    49.9 km
    49.8 km
    50 km
    50.1 km
    49.9 km
    50 km
    50.1 km

For example, numbers are reported:

0
0.01
0.02
...
4.99
5
5.01
...
9.99
10
10.1
...
19.9
20
20.1
...
99.9
100
101

which should be:

0**.00**
0.01
0.02
...
4.99
5**.00**
5.01
...
9.99
10**.0**
10.1
...
19.9
20**.0**
20.1
...
99.9
100
101

Note that the last three numbers are all right.

**Comment by Norbert80** [comment]
Please also for coordinates in decimal degrees.

**Comment by sonora** [comment]
I will try to get t this in the next few days. It would be a great help for me if someone could post here a list in which of our displays and widgets this is an issue and should be changed.

Thx - Hardy

**Comment by PanderMusubi** [comment]
At least in the widgets for navigation.

**Comment by vshcherb** [comment]
@sonora  we need to change only one function https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/OsmAndFormatter.java#L103. If this is not a case, let's discuss what we can do, cause I don't to have different code in different screens. It is possible that in some screens we would like to have rounded values like ruler, but in general it will be ok to display 50.0 km if the value could change to 49.9 km, so we just need to format in such case that close values will have close formatting with exception like 0.

**Comment by Norbert80** [comment]
Please also consider to fix
![coordinates](https://cloud.githubusercontent.com/assets/6921696/18103207/e6dc85ce-6ef5-11e6-9b2f-eac186232ad0.png)
 this for coordinates.

The screenshot on the left side is good. But in the screenshot on the right side trailing zeros are missing for:

- The toast
- The button below the toast
- And the content copied to clipboard after long pressing the button

Note that both latitude and longitude are affected while the example coordinates only have  a trailing zero in  the longitude.

**Comment by sonora** [comment]
Not sure we should do this globally, may have to have exceptions like for the ruler - will investigate.

**Comment by Norbert80** [comment]
@sonora does your fix also cover the coordinates?

**Comment by sonora** [comment]
Norbert, Yes. In addition, the display on the "Move Map Marker" screen will now properly respect the coordinate format you have chosen in General settings.
