### ISSUE TITLE
Issue with new search feature in 2.4.4

### ISSUE THREAD

**Issue by Cool-hand-fluke** [osmandapp/Osmand#3020]
I have installed osmand 2.4.4 with Harry van der Wolf's UK post code POI file from here

https://github.com/hvdwolf/OsmAnd-UKpostcodes/releases

The original POI search works correctly and only shows the postcode i am searching for. A space is required between the two parts of the postcode e.g po9 2xe

Unfortunately the new search feature is displaying all the results for the first part of the postcode (eg all po9 postcode locations) up to the space. It is not using the subsequent part of the postcode after the space in the search.

This is on a moto g 4g and a LG G2 running CM13.

Hope this helps

Regards Paul

N.B. this has been confirmed by Harry in this forum post

https://groups.google.com/forum/m/#!topic/osmand/E15FujmNH7c

**Comment by hvdwolf** [comment]
Being a beta-tester I'm on 2.4.6+ on a Samsung S5 mini. The issue is the same.

**Comment by vshcherb** [comment]
Quite sad this a known issue for now. We need somehow add special cases for it cause search with space works very different.
