### ISSUE TITLE
"Minutes" or "min" in parking time limit missing

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/Osmand#3022]
The value is in minutes. I think it would be good add this to be clear
See screenshot
![img_20160829_183953](https://cloud.githubusercontent.com/assets/11144987/18059273/951f1af4-6e18-11e6-85fa-c371131d2621.jpg)

Greetings Simon

**Comment by vshcherb** [comment]
This is osm data that could be fixed http://wiki.openstreetmap.org/wiki/Key:maxstay

**Comment by jf-simon** [comment]
Ok Thanks
