### ISSUE TITLE
Bad route calculation by default (2-phase routing)

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#3023]
If found that OsmAnd displays a toast saying that  FAST calculation has failed and SLOW calculation is used instead in some cases.

So I found routes that sometimes are calculated with FAST and sometimes with SLOW algorithm. But I found no way to control this reliably. But it may be memory usage depending since after an reboot FAST calculation is used.

I also found that SLOW algorithm calculates other routes. Is this a known problem?

Bug found with OsmAnd+ 2.4.6.

**Comment by Norbert80** [comment]
After more investigation it turned out the the SLOW algorithm calculates correctly. The Problem is the 2-phase routing which calculates a "bad" result. Below you find screenshots.

2-phase routing on (OsmAnd default) - "bad" result
![2-phase on](https://cloud.githubusercontent.com/assets/6921696/18066777/23794a38-6e3a-11e6-9a35-e13f92ceeed2.png)

2-phase routing turned off (using developer plugin) - good result (identical with SLOW algorithm in case of fall-back)
![2-phase off](https://cloud.githubusercontent.com/assets/6921696/18066842/6b5c160a-6e3a-11e6-9fd7-3632ff151361.png)

START coordinates: Lat 47.80221 Lon 9.63108
DESTINATION coordinates: Lat 48.0111 Lon 9.69192

**Comment by Norbert80** [comment]
@vshcherb do you plan to fix this bug with priority?

**Comment by Norbert80** [comment]
@vshcherb Do you plan to fix these problems in the current algorithm?

**Comment by sonora** [comment]
Norbert, there is no easy fix for these issues, I'm afraid. It is a mater of which algorithm performs best under what circumstances and pre-conditions, and this is not just a simple software bug fix, but a full-grown science (or at least optimization problem) requiring considerable research.

While we are constantly investigating issues like this, trying to understand what is going on, and how the situation can improved with general and not just situation-specific validity, you will find similar weaknesses in almost any navigation system. At the end of the day, it may well turn out that the "state of the art" of what is the better route and what not will always to some extend depend on local circumstances and experience which no map data and algorithm can objectively provide.

So yes, collecting situations like this will aide the investigations, but there cannot generally be a "plan to fix this bug with priority". Looking a the map, I cannot even readily agree if route 1 or route 2 is the "better" one, and their calculated time requirement seems to differ by only 2 minutes. :)

**Comment by vshcherb** [comment]
I took a look at it and this is what I've found :
Default
2phase routing_time = "2438.918"  (2438 seconds)

Default 1 phase: routing_time = "2342.465" 
Default 2 phase with intermediate point so the route is the same as 1phase: routing_time = "2338.6812" .

What I see now somehow complex route calculates wrong result

**Comment by vshcherb** [comment]
Ok mystery solved: 
Base routing (1st phase of 2) routing_time = "1823.8849" 
Base routing (1st phase of 2) with intermediate point routing_time = "1880.4023".

Basically 1st phase which drives only major roads and doesn't consider route details graph like barrier / traffic signals etc. Calculates route correctly to the settings / routing.xml !

Obviously 1 phase algorithm could not be applicable to long distances.

Cause it is not obvious why 1st route is worse than I would close that issue. They look pretty much in the same time range.

**Comment by sonora** [comment]
Yes, that's what I am saying above, too. Sometimes from our real world experience we "feel" that a specific route must me way better than another one, but then investigating this it turns out that this is either due to some circumstances which cannot be extracted from the map data at all, or sometimes we are even fooled by our feelings and an objective check via algorithms and parameters (like projected travel time) shows our feeling is actually wrong.

PS: An interesting psychological phenomenon is actually this: I have found that we sometime intuitively prefer routes which earlier "point" directly at our target. Meaning: Let's say you have 2 route possibilities: 

- (1) You first go left for 2km, then turn right on a road which will directly hit you target after 10 km (so for 10 km you will drive with your target directly in front of you).

- (2) You first go straight for 10 km (driving in a direction which would actually clearly miss your target), then turn left for 2 km to get to the same target

In many cases, people would prefer route (1), even if route (2) was equal in distance, or even slightly longer.

Sometimes, on the way back, people would often intuitively **take route (2) !**

(Looking at your screenshots, one could argue that screenshot 1 is a little like (1) and 2 like (2)  :) )

**Comment by Norbert80** [comment]
Guys, this bug is way more user confusing tgan you might consider.

The start/end scenario of this report lead to confusion of me and some friends because after a recalculation during driving OsmAnd has chosen the other route.

The 1-phase result is the good one which is also calculated by TomTom and other commercial routing services.

Please also note that I already have reported other scenarios that triggers the bug on the old Google Code bugtracker. There a slight variation of the start point leads to a bad route where the user is guided through private roads.

**Comment by sonora** [comment]
Norbert, I have never seen a situation where an underway route-recalculation leads to a significantly different route, but in principle this cannot be ruled out, there must exist situations where things depends critically on starting conditions.

Regarding "guidance through private roads": We would need to examine the specific situation. Could be map errors, or your GPS position fix was bad and detected you and the other side of a roadside gate, etc. Not sure I can help much here on the basis of what is supplied, I'm afraid...

**Comment by Norbert80** [comment]
@sonora are the old Google Code bug reorts still available? I filed a detailed reorts on this there.

**Comment by sonora** [comment]
I found something here in a google archive: https://code.google.com/archive/p/osmand/issues.

But it may be better to work from scratch, with latest maps, latest app version, etc.

**Comment by Norbert80** [comment]
@sonora @vshcherb 

Thanks to my bookmarks collection I have found the old bug report:
https://code.google.com/archive/p/osmand/issues/2580

This is another coordinate scenario where the 2-phase rooting has been revealed as root cause. That issue has bee reported based on an old OsmAnd 1.9.5 build.

However the situation on that scenario has become even worse with OsmAnd+ 2.4.6 build. Now, OsmAnd always chooses the bad route. Since all other OSM based routing services still and always choose the good route on that scenario (Google Code bug 2580) another change to the OsmAnd router seems to cause this degradation of OsmAnd's routing results.

No there are two topics open/arising:

1. The 2-phase bug has never been fixed and might be triggered by different coordinate scenarios now (compared to older OsmAnd builds) because of changes of the routing algorithm.

2. Should we file a separate bug report because the scenario of Google Code bug 2580 now always leads to a bad result?

**Comment by Norbert80** [comment]
I have filed bug #3334 for problem 2.

Please re-open this one to keep track on the 2-phase-rooting bug (1.).

**Comment by Norbert80** [comment]
@sonora @vshcherb Would you please comment on this issue?

**Comment by vshcherb** [comment]
The word "regression" is not applicable if we talk about different route i.e. start/end position is different.

**Comment by Norbert80** [comment]
@vshcherb I never said that this issue (#3023) is a regression. But I wonder why it is closed without any patch!?

**Comment by vshcherb** [comment]
@Norbert80 it is closed because it is not considered as an issue. There is no routing engine issue and the configuration change (routing.xml), which of course could influence the route and give a desirable ('expected') route , is very debatable. In sense it could make worse other routes and it is not obvious that 2nd route is worse.
