### ISSUE TITLE
OSM Live doesn't fully update bus routes

### ISSUE THREAD

**Issue by Kjarrval** [osmandapp/Osmand#3027]
Subscribed to OSM Live last night and activated hourly updates for Iceland and the app claims its map is updated. Bus route 18 was modified in mid-August which entailed removing some ways from the bus route relation. However, OSM live didn't remove the corresponding ways but it seems to be keeping the ones which were added in the process.

Example;
Check out this area online and compare it with the OSM Live version:
https://www.openstreetmap.org/#map=14/64.1308/-21.7437&layers=T

**Comment by vshcherb** [comment]
Live updates having issue with complex relations and it looks the same asa https://github.com/osmandapp/Osmand/issues/2677
