### ISSUE TITLE
Correct phrase atm

### ISSUE THREAD

**Issue by franco999** [osmandapp/Osmand#3028]
For the former (Atm_yes: yes), there is no translation.

![w](https://cloud.githubusercontent.com/assets/12088580/18103756/5f353520-6ece-11e6-80c0-ad55aeec6daf.png)

**Comment by verdulo** [comment]
I've already reported this: https://github.com/osmandapp/Osmand/issues/2972

**Comment by franco999** [comment]
Apparently, there was a problem with _Weblate sync_, because in some languages are duplicated or unnecessary phrases.

**Original version:** https://github.com/osmandapp/Osmand/blob/master/OsmAnd/res/values/phrases.xml#L2583

**es-rAR:** 
- https://github.com/osmandapp/Osmand/blob/master/OsmAnd/res/values-es-rAR/phrases.xml#L2614
- https://github.com/osmandapp/Osmand/blob/master/OsmAnd/res/values-es-rAR/phrases.xml#L3062
- https://github.com/osmandapp/Osmand/blob/master/OsmAnd/res/values-es-rAR/phrases.xml#L3063

**Search:**
- https://github.com/osmandapp/Osmand/search?utf8=%E2%9C%93&q=poi_osmand_additional_atm_yes
- https://github.com/osmandapp/Osmand/search?utf8=%E2%9C%93&q=poi_additional_atm_yes&type=Code
- https://github.com/osmandapp/Osmand/search?utf8=%E2%9C%93&q=poi_atm_yes&type=Code

**Comment by xmd5a2** [comment]
@franco999 If phrase is renamed or removed from english phrases.xml it is not automatically removed from other languages. But these phrases are just not used more than and does not interfere with other phrases. At that moment we have two phrases related to presence of ATM:
```xml
	<string name="poi_additional_atm_yes">Atm: yes</string>
	<string name="poi_amenity_atm">ATM</string>
```
First is used when bank is tagged with atm=yes. Another POI object is created for that case to allow searching for these ATMs. Second is standalone ATM.
Issue you experienced can be related to old maps where this new scheme was not correctly implemented. OsmAnd itself needs to be updated too. poi_additional_atm_yes string is translated correctly in nighty.

**Comment by franco999** [comment]
When updating the map, that error I no longer appears, but the phrases are still occupying place. With old maps the error appears (also converted with OsmAnd Map Creator), but not with the new maps downloaded.

Do not be deleted phrases that are unused, to avoid confusion?
I should also update OsmAnd Map Creator?

**Comment by sonora** [comment]
I just cleaned this up for all languages (https://github.com/osmandapp/Osmand/commit/5cba154a6ab8ddcaf7c55a5b75bbe07bf045084c), should be fine now, I hope. We now only have 
```xml
	<string name="poi_amenity_atm">ATM</string>
	<string name="poi_additional_atm_yes">ATM: yes</string>
	<string name="poi_atm_no">ATM: no</string>
```

**Comment by sonora** [comment]
Leave a comment

**Comment by franco999** [comment]
Thanks. 
Why is **poi_atm_no** instead of **poi_additional_atm_no** ? 
Or, why is **poi_additional_atm_yes** instead of **poi_atm_yes** ?

**Comment by sonora** [comment]
From what I see, the 3 string names I list above are the ones actually used, al else were obsolete, see also (@xmd5a2 's comment above.  We could certainly change, and I can offer to assist once more, but not sure if its worth it. Leonid, your decision.

**Comment by xmd5a2** [comment]
Originally it was @vshcherb decision and we argued a lot about it

**Comment by franco999** [comment]
What I want to say is: Why both are different?
It should not be?
poi_atm_yes
poi_atm_no
or
poi_additional_atm_yes
poi_additional_atm_no

**Comment by vshcherb** [comment]
Well we didn't have any other solution, so we have 2 different POI objects "attached atm to the bank" and "separate atm".
