### ISSUE TITLE
search by address almost unusable in the french countryside

### ISSUE THREAD

**Issue by saccharomyces-cerevisae** [osmandapp/Osmand#3029]
hi, i'm trying for months to use osmand in my lost countryside of france, i very often fall back to other navigation systems, and i can't recommend it to anyone because of the "search by address" system wich is really hard to use here, i tell you why in some points:

- accents: for example the nearest town from my place is "Bélâbre", if you don't type all the right accents, you don't find it, which is really tricky because it's many times not possible to know only with the pronunciation, so as in other systems, "é" "è" "ê" or even "ë" (only used in the west of france) should be considered the same as simple "e".

- more tricky: the town "Vendoeuvres" is written "Vendœuvre" in osm. we call that char "e in o", it's the right spelling but it's really old-school deprecated char in french and you don't even think about using it when trying to find your destination. "œ" is not even existing on a french keyboard!
so "œ" and "oe" are equal

- isolated places: in my place there are more isolated farms than 'normal' addresses like number+street, here no number and street, only a farm name. all the other navigation systems can find that kind of places when looking by addresses, isolated places should appear with street names.

- region: i live on the frontier between 3 regions, it's really hard to know if the next village is in the region "Poitou-Charentes" or "Region centre" or "Limousin", is it really necessary to start by a region field? it's the first navigation system i try that works like that...

but, when i select my destination directly on the map, it works really great, thanks for the job :)

**Comment by saccharomyces-cerevisae** [comment]
things i forgot: my town " saint hilaire sur benaize" can only be found when typing "saint-hilaire-sur-benaize" quite tricky also. in french there are also a lot of 'â' to consider like simple "a".

**Comment by homersimpsons** [comment]
Then you need to remove diacritics, there was a post on iD (osm) about this

**Comment by vshcherb** [comment]
I do believe, you didn't use the latest search which is available 2.4 (search on screen) and next release will become the main one.
For 1st one could not reproduce the issue https://www.dropbox.com/s/20bc0m09x9w4yx3/Screenshot_20160831-100444.png?dl=0.

Vendœuvre I guess should be changed in the OSM cause it is not a normal diacritics symbol

**Comment by sonora** [comment]
@saccharomyces-cerevisae : To clarify: Use the "Magnifying glass" search button near the top left corner of the map screen (on the latest OsmAnd releases), it takes you to a new search interface which has fixed many of the issues you describe.
