### ISSUE TITLE
If I use quick search during navigation, the screen flashes on/off, and device has to be rebooted

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#3030]
Using OsmAnd~2.4.0#18333M on OnePlus 2 running on OxygenOS 3.0.2 (which is based on Android M 6.0.1).

If OsmAnd is in Navigation mode, and if I use QuickSearch, the screen starts flashing on/off.

OsmAnd locks the device: I cannot use the device's **Recent apps** menu to switch to another app, or to kill OsmAnd.

The only way left is to reboot the device by long-pressing on the **Power** button.

Note that the actual onset of the problem occurs at different stage of using the **Quick Search** function.
- As soon as I tap on the magnifying glass icon. 
- When I select a category
- When I select a category and then type in some characters
- When I select a POI from the search results

But ultimately I am able to crash the device while using **Quick Search** in 90% of the cases.
(In the remaining 10%, it happens if I retry the **Quick Search** for the second time).

**Comment by vshcherb** [comment]
Couldn't reproduce

**Comment by raindropsfromsky** [comment]
oops- Forgot to mention that I have enabled the **Turn screen on** setting, and set it to 5 seconds.
(Settings> Navigation settings)

I think this is a factor.

**Comment by JanWielemaker** [comment]
Rather odd that this is apparently so hard to reproduce.  Been using osmand+ quite a bit over the last two months and had this crash at least 10 times.  Currently on Motorola G-play, Android 6.0.1, but I had the same issue on my crashed Sony Xperia and my wife has it on a current Xperia running Android 7.

Indeed, we both have __Turn screen on__ enabled (a very nice feature on bicycle if you have to conserve energy).

Never got exactly clear how to reproduce, but a clue is to interact with it while it it computing a route or navigating.  As it requires a complete reboot cycle of the phone to recover I consider this really severe.

**Comment by raindropsfromsky** [comment]
I have this issue in OnePlus 3T.

On 23-Apr-2018 10:09, "Jan Wielemaker" <notifications@github.com> wrote:

Rather odd that this is apparently so hard to reproduce. Been using osmand+
quite a bit over the last two months and had this crash at least 10 times.
Currently on Motorola G-play, Android 6.0.1, but I had the same issue on my
crashed Sony Xperia and my wife has it on a current Xperia running Android
7.

Indeed, we both have *Turn screen on* enabled (a very nice feature on
bicycle if you have to conserve energy).

Never got exactly clear how to reproduce, but a clue is to interact with it
while it it computing a route or navigating. As it requires a complete
reboot cycle of the phone to recover I consider this really severe.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/osmandapp/Osmand/issues/3030#issuecomment-383452281>,
or mute the thread
