### ISSUE TITLE
OSMAnd 2.4.6 consistently crashes on startup and on selecting map-style

### ISSUE THREAD

**Issue by noci2012** [osmandapp/Osmand#3031]
There are 4 crash reports sent through google play about this on august 31, around 10:00-11:00 CET.
some crash reports are during startup, some are on selecting map-style.

The map is not shown afterward, if unzoomed sufficiently the green contours of downloaded maps are shown. POI are shown or not depending on selected option. No roads/buildings etc.

There is a notification: the internal library is not supported on this phone. 
an error has occurred with mapgeneration of the selected area. (when update of the screen should be done). Only the blue arrow is visible.

The maps involved Netherlands, dated August 1,  2016. (downloaded after upgrade).
(A total of 8GB of maps is present on the phone).

An  (12:06 ocurred) OSMAND crash report about a previous crash. (I started OsmAnd for getting the version #) this option was not presented on the google play reported ones.
This report has been sent by  email.

Selecting the map-style setup option from the mapoptions menu will crash OSMAND also, the option item does not tell which map-method is used.
It used to be OsmAnd.

Only off-line use is enabled for this installation. There is a lack of general WiFi coverage throughout the country, so online is not really an option.

Phone is Samsung S5-mini (SM-G800F

**Comment by vshcherb** [comment]
Could you please attach a crash ? exception.log file on sdcard, possibly you need to switch to smaller files of the Netherlands, please try 1 province for example.

**Comment by noci2012** [comment]
Here is the exceptionlog
[Uploading excepti
[exception.txt(https://github.com/osmandapp/Osmand/files/452963/exception.txt)
on.txt…]()

**Comment by noci2012** [comment]
[exception.txt](https://github.com/osmandapp/Osmand/files/452965/exception.txt)
Here is the exceptionlog.

**Comment by noci2012** [comment]
Note that routing does work, the route is drawn on the screen on an empty canvas as a narrow black line with arrows. Also the voice directions  (english) are given. As dutch appearantly on this (original german language phone, with dutch language setting) doesn't work. The beeps starting announcing various messages are heard though.

**Comment by vshcherb** [comment]
I'm afraid you need to do reinstall, if you switch the storage folder to "Shared storage" it won't  to delete your data favorites / maps and etc. Though it is always recommended to make backup of favorites (copy favorites.gpx file). Please let us know if reinstall doesn't help.

**Comment by noci2012** [comment]
Again? 2.4.2 -> 2.4.4 was the same. (It did show some info on the maps) but there was troubles.
Besides: "Shared Storage" cannot hold all that data. So that was a reload of all 8GB of maps again.
A 16GB uSD is used to store all map etc.
Copying in maps from outside gives wierd results on a map (country select). ie. Double names of countries of which only one works.

**Comment by noci2012** [comment]
This might be caused by this: http://www.securityfocus.com/archive/1/539562 
As starting Osmand will active gps which Might activate a download of agps data.
(I have seen crashing the application as well as crashing the whole phone into cold booting it).

**Comment by noci2012** [comment]
And it does it again after yesterdays update to 2.5.4
So i have to assume that delete, reinstall and reload all maps in the future will be more convenient then just update?

And this is not related to the Qualcomm GPS Crash which i have observed again earlier this week, prior to updating.

**Comment by sonora** [comment]
Looks like deprecated(?)
