### ISSUE TITLE
crash performing restaurant search

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#3033]
Osmand nightly build 2.4.0#18372M, released 2016-08-31 and nightly build 2.4.0#18324M, release 2016-08-27.   ** NOT reproduced in current Play store release version 2.4.6 released 2016-08-22.

Nightly builds running on Samsung Galaxy S7 Edge, Android 6.0.1
Play store version running on Samsung Galaxy S5 Active, Android 5.0

With the nightly builds, using US Georgia map dated Jul 31, 2016, with this morning's OSM Live update for Georgia.

With the Play store version, using US Georgia map dated Jul 31, 2016, no updates.

With the map centered here http://osm.org/go/ZQqvF2A4t?m= press the Menu button in Osmand and select search.  Create a custom filter for Restaurant and begin to search.  You should get the first screen of POIs OK, but when you press Find More and then scroll down, before you reach the bottom of the extended list of POIs, Osmand will hang for a few seconds, then crash.

I have verified that if I move the map to a location farther away, such as here http://osm.org/go/ZQrpxgQB8-?m=   then I can get a longer list of POIs before it hangs.

Note:  you can achieve the same results by just using the default Food category.  I used custom filters to try to narrow down which sub-category might be the problem.  I have not observed the problem with other categories yet.

I don't know if it's a bug in Osmand or a malconfigured POI (in which case it might still be considered a bug in Osmand if it is not able to work past malformed data).  If it is a restaurant POI with bad data in it, I haven't yet been able to figure out which one.  Hopefully a debug build can show that?

I've considered the possibility that the problem might be related to the recent opening_hours fix in #3021 but unless I can find the specific POI causing this (if it is in fact a POI problem), there's no way I can tell. 

I send in a crash log from Osmand with the same subject line as this GitHub entry.  If you can't find it, let me know and I'll try to get it attached here.

**Comment by jfburke3** [comment]
Done.  I'll try to remember that for the future.

[exception.txt](https://github.com/osmandapp/Osmand/files/448310/exception.txt)

**Comment by vshcherb** [comment]
The main reason is some opening hours were not parsed and caused crash, cause I don't known which value causes crash, I will catch that exception and ignore. Though it is not 100% correct fix.

**Comment by jfburke3** [comment]
So it *is* a problem with opening hours somewhere.  Since I have a general idea what area the problem is, I'll look through OSM when I have some time and see if I can identify likely candidates, and let you know what they are.  (Of course, if their hours are seriously bogus, then I'll fix that.)

**Comment by jfburke3** [comment]
Wait....  What did the code in those builds do if it encountered:

opening_hours=Mo-Su sunrise-sunset

I centered my map here http://osm.org/go/ZQqvH2Soh?m=&node=1810573872 and then tried to do the search again, and it hung and crashed without showing me any results.  The opening_hours above *were* what was on that drinking_water POI, but it just so happens that I changed the value last night to more closely match how the park service defines the hours.  The new value is:

opening_hours=Mo-Su (sunrise-00:30)-(sunset+00:30)

in case you want to test against that.

**Comment by vshcherb** [comment]
I added this value to not supported

**Comment by jfburke3** [comment]
Not trying to insist that you support this, I promise.  But I'm pretty sure that it worked with those opening_hours values a while back.

**Comment by sonora** [comment]
@jfburke3 Yes, parser code has changed significantly last month, so I am not surprised. From what I see, we do support sunrise/sunset, but not any calculation with it like +00:30. It seems feasible to support this, but I am not sure how frequently this type of tagging occurs ...?

**Comment by jfburke3** [comment]
I retagged several things that way because that's how the National Park Service defines the open/close times for some parks.  But I can go back and change it to sunrise/sunset without the offset.

Do you support dawn/dusk as values, too?  I could use them if you do.  It might not fit the park service's definition, but we're talking about a "time" that is variable and changes throughout the year, anyway, so if it's "wrong" by several minutes it probably doesn't matter.

**Comment by vshcherb** [comment]
The crash should be fixed actually, but the value is not fully supported, so it will work ok, but might not highlight green correctly.
