### ISSUE TITLE
road division not voice signaled

### ISSUE THREAD

**Issue by pauser0000001** [osmandapp/Osmand#3036]
Hello,

In the Android version 2.4.4 there is place where the road is divided in two and osmand keeps silence.
I do not know if it is a problem within the OSM or it is really a missing case.

The problem happens in Autoroute de Normadie, Giberville, direction Caen.
Between Lat 49.1671 Lon -0.28651 and Lat 49.16728 Lon -0.29286

Or in the OSM https://www.openstreetmap.org/#map=18/49.16703/-0.29203

The application is spectacular. I've never got lost and always arrived to the nearest parking place.

**Comment by vshcherb** [comment]
Cause one of the road is motorway_link https://www.openstreetmap.org/way/164328608, it won't be notified if you continue navigation on motorway. This is a data issue or may be it is correct data and correct behavior. To get always notified 2 roads should be motorway_link or motorway.

**Comment by pauser0000001** [comment]
I understand why it is not currently notified. The problem here is that unless you pay careful attention to the road signs, and you are driving by the rightmost lane, you will exit the motorway (Autoroute) instead of following in the motorway as the calculated route said so.
Is it possible to at least show the widget with the lanes to follow in those cases?

**Comment by vshcherb** [comment]
As I see adding turn:lanes actually helped and now this split will be announced. Though not announced should be also shown but with different priority and only 300m ahead, of course tagging turn:lanes make that situation displayed nicer.
