### ISSUE TITLE
Support for display and automatic rerouting on minspeed

### ISSUE THREAD

**Issue by BalooUriza** [osmandapp/Osmand#3037]
> What version of OsmAnd are you using, on what device and Android/iOS version?

OsmAnd~ 2.4.4 on Android 6.0.1

> Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

Osmand's standard offline maps.

Nice to have item: Display minspeed similarly to maxspeed; automatically avoid routes with minspeed should speed stay under minspeed for a certain amount of time.  Rationale: Some places require vehicles to exit as soon as legally possible if they're no longer capable of maintaining minimum posted speed, even if the reason is due to traffic tailback.

**Comment by sonora** [comment]
Not planed any time soon, I guess.

**Comment by BalooUriza** [comment]
Why not leave this open for future consideration?

**Comment by polarbearing** [comment]
The ticket is not lost when it is closed. 

However I'd see the use case for this request rather exotic. Typically, minimal speed is required on motorways, and there is already a routing option to avoid motorways.

**Comment by BalooUriza** [comment]
The idea being if the speed drops under the minimum and stays there, to automatically avoid minimums for a bit.
