### ISSUE TITLE
Some issues while displaying boundaries

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#3038]
I was noticing that I can't see the boundaries in osmand (with `admin_level` `8`, `9`, or `10`, it seems).
For example, [here in OSM](https://www.openstreetmap.org/#map=12/-21.6673/-48.3216) we have a `admin_level=8` boundary:

![](https://cloud.githubusercontent.com/assets/982338/18180838/fb25cdfa-705e-11e6-89d2-a90ec5f40d3c.png)

But in osmand I just can't see anything:
![](https://cloud.githubusercontent.com/assets/982338/18180855/10d89f88-705f-11e6-8022-ac461e5e249e.png)

No matter if `Hide boundaries` is checked or not in the default style.

Also, it seems that it's also not possible to hide the boundaries in lower level zooms:

![](https://cloud.githubusercontent.com/assets/982338/18180984/a123ec32-705f-11e6-8261-fbe1cd1745ac.png)

By marking `Hide boundaries` I can't hide the countries nor the states boundaries.

osmand version is 2.4.0#14427D

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/1c532379f641c2e7d8254f9dc54f3241f5a8cacc
