### ISSUE TITLE
Solarium

### ISSUE THREAD

**Issue by verdulo** [osmandapp/Osmand#3039]
OsmAnd currently recognizes Solarium as amenity=solarium; but this is incorrect and it's not mentioned on the OSM wiki, the correct tag is [leisure=tanning_salon](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dtanning_salon), usually with shop=beauty. There's currently [93 objects](https://taginfo.openstreetmap.org/tags/?key=amenity&value=solarium) marked as amenity=solarium, and [665 objects](https://taginfo.openstreetmap.org/tags/?key=leisure&value=tanning_salon) marked correctly; so I suggest to add into program the correct tag leisure=tanning_salon; but don't temporary remove the incorrect tag.

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/d54cb2074435c6f8622b54bd3a58337c79e1a0d2
