### ISSUE TITLE
"%1$d" not filled when upload osm note from offline to osm over dashboard

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/Osmand#3040]
while upload locally saved osm notes, i get this message. the string "%1$d" is not filed with data. This message appears when uploading via dashboard and not while upload from "my places"
#18381
![screenshot_2016-09-02-11-35-15](https://cloud.githubusercontent.com/assets/11144987/18199712/dffbfda8-7101-11e6-927c-8985d90e0696.png)

Greetings Simon

**Comment by sonora** [comment]
Looking a the current code, (which is marked for revision anyway), I think there can only be a "1" there ?

I have added that. If "1" is not always correct, please report here.

**Comment by jf-simon** [comment]
Working. Thanks
