### ISSUE TITLE
Map download incredible slow

### ISSUE THREAD

**Issue by FiniteElementGuy** [osmandapp/Osmand#3042]
Two issues:

1. I just bought Osmand plus a few minutes ago and I am a bit frustrated that it takes a long time (hours) just  to download the base map. Are there any backup servers where I can download these files manually and move them to the Osmand folder? 

2. It seems to me that newer Osmand versions need more time for GPS fix (I noticed this with the free version in a forest). Also Osmand loses the GPS position more often and the recorded track (e.g. when cycling in the forest) is less accurate than before.

**Comment by vshcherb** [comment]
1. If you use Storage Folder = Shared Storage, you don't need to redownload map files
2. it should be exactly the same as in free version, though it depends on weather condition sometimes.

**Comment by vshcherb** [comment]
About map downloads being slow we will investigate networking issues through the logs, looks fine now

**Comment by Nutomic** [comment]
I'm also having very slow downloads right now. I can't see the download speed anywhere, but downloading the world overview app takes at least one hour.
