### ISSUE TITLE
Upper Sorbian is "map language", but not displayed on map

### ISSUE THREAD

**Issue by juliannyca** [osmandapp/Osmand#3043]
Hello,

recently Upper Sorbian (hsb) has been added as a map language (thanks for that!). Search for Sorbian adresses and places already works, but the Sorbian names are not displayed on the map, when I chose Sorbian as map language in the configuration menu. At first I thought it is a matter of map actualization, since version 2.4 came after the maps. But updating maps of northern Czechia now, I still don't see the Sorbian names of places there.

Regards,
Julian Nyča

**Comment by sonora** [comment]
Should be fixed with next map generation, I think (https://github.com/osmandapp/Osmand/commit/43a36f86ea6ceb81ce2c9fff268bba6d4676f724). If not, please post an example here.
