### ISSUE TITLE
Ability to dynamically recolour rendering style icons

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#3047]
Topo style requires icons with appropriate color scheme. It is required to recolour existing icons by setting something like iconFill="#ff0000" in rendering style.

**Comment by vshcherb** [comment]
Very tricky and it is not clear whether we could support in the opengl rendering.

**Comment by vshcherb** [comment]
The easiest we can recolor all icons in the code by style and it will be much more difficult to make it attribute or property dependent.
