### ISSUE TITLE
Pre-recorded voice navigation guidance issue (Russian)

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#3048]
When using a pre-recorded Russian voice for navigation guidance, the voice engine does not finish phrases sometimes. It 'swallows' words and starts the next phrase.

**Comment by sonora** [comment]
Can you please do the following:
- Go to Menu/Settings/Plugins, and enable the Development Plugin
- Then, go to Menu/Settings/Development Settings, and chose "Test voice prompts". Select the appropriate language to test.

Please report here which prompt button numbers fail, and try to explain (with their English button caption) in what way they fail, i.e. what portions of the prompt are missing.

It would be interesting for me if ru-tts fails in the same way than the pre-recorded ru, or works ok.

**Comment by annasoloviova** [comment]
TTS prompts work fine. I guess the issue is only reproducible with pre-recorded voices.
