### ISSUE TITLE
Hide underground objects does not hide all underground objects

### ISSUE THREAD

**Issue by quelbs** [osmandapp/Osmand#3049]
If I select "Hide" -> "Underground objects" not all underground objects are hidden. E.g. http://www.openstreetmap.org/node/2758352721 and many other objects next to it are still shown.
It can be observed best, when you select both, hide underground objects and hide overground objects at the same time. There should nothing be shown with this selection but this is not the case. (In my opinion selection both options at the same time should not be allowed anyway.)
Osmand 2.4.0#18410M

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/a974abe830a43935582ca8e31eb8c8155f83ea0a
Please test. No new maps needed.

**Comment by quelbs** [comment]
For the layer attribute everything works as expected now. As far as I understood from #2775 level is not available, so until access to level attribute is available nothing more can be done.
