### ISSUE TITLE
There is no way to search a city address offline if the proper country submap is not known

### ISSUE THREAD

**Issue by emuzychenko** [osmandapp/Osmand#3050]
I use OsmAnd+ 2.4.6 on Android 5.1.1. Planned to visit some France provinces so had downloaded the appropriate offline submaps. But when I want to search an address in a town, I not always remember which province it belongs to. Since OsmAnd+ requires to select a particular country/region first, I'm unable to specify the "all french regions" or even "all offline maps". So I have either to try all offline regions one by one, or find town/province relationship from a separate source.

I know that POI search can be used but Internet assess may not be available each time, and/or may be very expensive.

If possible, please add a region selection feature (at least a possibility to search in all offline maps).

**Comment by sonora** [comment]
I think you are still talking about our "old" legacy search interface, which is accessed via Menu button / Search. It is still left there in our current 2.4.x release to facilitate transitioning.

Please try the **new search interface**, accessible either via the magnifying glass button near the top left corner of the map screen, or on any point's context menu via "Search near here" (behind the 3-dots extended menu). It is a fully indexed text search and should e.g. solve the exact issue you are describing. For best result, first pan the map to roughly the area where you expect the result should be (or where you would be interested in finding the results for).

**Comment by polarbearing** [comment]
> For best result, first pan the map to roughly the area

This is a bit paradox, so I need to know where a feature is before I search for it?
I tried to search for a street in another federal state and it failed. But that would be the normal situation when travelling to a distant address...

**Comment by sonora** [comment]
True,  but it is about the only rule I can think of you can apply: Search the neighborhood first,  then more distant destinations. How else? Certainly makes sense if you look for "gas station"  :)

**Comment by vshcherb** [comment]
New search UI is sufficient to close the original issue

**Comment by emuzychenko** [comment]
Thank you, new search feature does the job. Just thought that every on-screen button has an appropriate menu item with the same functionality.
