### ISSUE TITLE
Can not remove dropped pin in horizontal orientation

### ISSUE THREAD

**Issue by BenyTheKid** [osmandapp/Osmand#3053]
When you drop a temporary pin in portrait mode, the menus automatically displays and has a tab. If you swipe down on the tab, the pin disappears. In landscape mode there's no tab and no way to get rid of the pin unless you drop another.

Running Osmand 2.3 nightlies on a Samsung tab S2
![20160909_101210](https://cloud.githubusercontent.com/assets/17969672/18378543/507af38a-7676-11e6-8379-66a09b41aebc.png)
![20160909_101143](https://cloud.githubusercontent.com/assets/17969672/18378548/567d8d74-7676-11e6-9fe8-3ff7daabbb14.png)

**Comment by vshcherb** [comment]
Long click will be deleting the pin

**Comment by BenyTheKid** [comment]
I don't know how you're doing it but it doesn't work for me. I don't have
the option and actually, long press doesn't call up anything.

**Comment by BenyTheKid** [comment]
![screenshot_20161019-002152](https://cloud.githubusercontent.com/assets/17969672/19498399/48729570-9599-11e6-9d97-8d7336a3190e.png)

**Comment by vshcherb** [comment]
Long tap can't be used

**Comment by harvey637** [comment]
simply use the tab with the three dots inside rotated 90° right on the right side of the area in picture 1.
slide to the left to remove informative area and orange marker. this is consistent with portrait orientation and very intuitive. adding something on to of the area conflicts with android statusbar pulldown.

**Comment by BenyTheKid** [comment]
I'll check the latest update, but that was my point at the time. There was
no tab with three dots in landscape mode. Check the screen shots.

**Comment by harvey637** [comment]
sorry for confusion, I WOULD LIKE to have this "three_dots_tab" on every menu, that slides in.
slide_in from left, slode_out to the left ("three_dots_tab" on the right side of the menu.
slide_in from buttom, slide_out to buttom ("three_dots_tab" on to of the menu.

And consistently working in portrait and landscape mode. This is still missing, so Your issue is still valid and unfinished.

**Comment by vshcherb** [comment]
Proposed solution: swipe down on the title could work similar to the portrait orientation.
