### ISSUE TITLE
OsmAnd+ 2.4.6 regression: "Add as last destination" no more available

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#3057]
Hi,

since OsmAnd+ 2.4.6 I am missing the menu item "Add as last destination".

I'm not absolutely sure if it has vanished exactly with build 2.4.6 but it was definitely available in builds before. (Perhaps it has vanished from 2.3.x to 2.4.x. I am rather sure that I have used this function often with 2.3.5 build during my holidays.)

"Add as last destination" is a common use case that defines the current last destination as last intermediate destination and the new position as last destination. With this function no more available the user has to completely redefine the route if he wants to add one more destination after the currently defined last destination.

Please make this item available again.
![osmand](https://cloud.githubusercontent.com/assets/6921696/18419878/3a556428-7865-11e6-814a-f604c8d75305.png)

**Comment by sonora** [comment]
Second option on your screenshot :)

I guess we changed the wording since "last"  sounded too "final".

**Comment by Norbert80** [comment]
@sonora you are right. Thanks.

But the German translation is wrong: "Als Zwischenziel einfügen". That's why I were missing this feature.

**Comment by sonora** [comment]
Well spotted, thanks. I fixed this in our nightly builds, will be in next release then.
