### ISSUE TITLE
Wrong city in reverse geocoding

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#3058]
nightly 11 Sep 2016

Geocoding [this road](http://www.openstreetmap.org/way/57386690) claims it is Friedhofstr, Schöneiche bei Berlin; while it is in Hoppegarten (admin level 8), county Landkreis Märkisch-Oderland (admin level 6), even a different county than Schöneiche which border is about 2.5 air km away.

**Comment by xmd5a2** [comment]
Yes, there is something wrong with geocoding
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot_2016-09-16-21-16-53.png
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot%20from%202016-09-16%20212037.png

**Comment by polarbearing** [comment]
Just checked in today's nightly, it is still wrong. I can produce more wrong villages/suburbs then tapping around in this location. 

One reason might be that there is a road with the same name in a village/suburb nearby. 

Example:

I tap on this road [Ahornstraße, Waldesruh](https://www.openstreetmap.org/way/25888970) and the geocoder shows "_Ahornstraße (Kaulsdorf), Berlin_"; 

and indeed there is another [Ahornstr in Berlin-Kaulsdorf](https://www.openstreetmap.org/way/24966655)

**Comment by vshcherb** [comment]
@polarbearing suburb are not considered as administrative entities ( Waldesruh ). They are considered as justifying entities to city/town/village.

**Comment by vshcherb** [comment]
Both issues are related to Berlin map and are not reproducible on Brandenburg map

**Comment by polarbearing** [comment]
I was only using the Brandenburg map, in the latest monthly version available, respectively. Closed prematurely. 

Don't understand what you mean with  'not considered as administrative entities'. The issue is that the geocoder apparently picks the wrong item from the list of streets named "Ahornallee", when there are more of one around.

**Comment by polarbearing** [comment]
Configuration: nb-2017-02-23
Germany_brandenburg_europe_2.obf (2017-Feb)
World_basemap_2.obf

1. the first issue, Friedhofstr, Waldesruh, is both in Brandenburg (real and coded location)
tap on https://www.openstreetmap.org/way/57386690, show "Schöneiche b Berlin". In this case I did not find a street with the same name in the shown location. 

2. Ahornstraße as above, trying on different ends of the road.

3. just below, [Robinienweg, Waldesruh](https://www.openstreetmap.org/way/128459777) shown as "Robinienweg, Schöneiche b Berlin". No such real way in Schöneiche.

4. [Eichenstr, Waldesruh](https://www.openstreetmap.org/way/253153520) shown as "Eichenstr, Kaulsdorf, Berlin. There exists an [Eichenstr, Kaulsdorf-Süd](https://www.openstreetmap.org/way/181612974)

5. [Mahlsdorfer Allee, Waldesruh](https://www.openstreetmap.org/way/128459772) shown as being in Schöneiche. No such real way in Schöneiche.

going north of the B1,

6. [Carenallee in Dahlwitz-Hoppegarten](https://www.openstreetmap.org/way/25605097) shown as being in Neuenhagen.

This also applies to full addresses:

7. [Iffezheimer Ring 26, 15366 Hoppegarten](https://www.openstreetmap.org/node/2977310078) shown as being in Neuenhagen.

Need more examples? Screenshots?

**Comment by polarbearing** [comment]
Just tested some of the examples with the April 2017 Brandenburg map and latest nightly. Issues still present.
