### ISSUE TITLE
"Max zoom" is ignored for raster tiles

### ISSUE THREAD

**Issue by robinpaulson** [osmandapp/Osmand#3061]
Hi,
I have a tile set I would like to use offline on my phone. The tiles are here:
https://bumblepuppy.org/ssci/

There are tiles from zoom 15-23 (I generated them, so I know they are there). When I add them to my osmand app (Replicant 4.2), latest osmand from f-droid, I only get tiles from 15-20, the rest are ignored. Using a File Manager app, there are only tiles to zoom 20 on the phone. I've tried restarting the phone, the wifi, killing and restarting osmand. Nothing works.

I'm not sure what more info you need, so please ask away and I will provide it.

**Comment by littlehelper** [comment]
Is this somehow related to #2713 ?

**Comment by robinpaulson** [comment]
Possibly, but it happens regardless of whether or not the map is an underlay or the main map
