### ISSUE TITLE
QuickSearch: Also prioritize villages and hamlets

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#3062]
When typing a location name, our QuickSearch displays cities or towns by that name (if existing) near the top of the hitlist, which is very useful.

But if you are looking for something smaller, like a village name, the entry for the village itself (which contains the essential information near which town it is, much needed where many duplicates exist) is "buried" in the middle of -potentially dozens- of search hits for streets in that village(s). 

I guess we should prioritize displaying the village/hamlet  entries themselves just like we do for cities and towns.

**Comment by vshcherb** [comment]
Screenshot and information where to see it would be good

**Comment by sonora** [comment]
Screenshots attached, as follows:

First screenshot shows the perfect solution as it occurs when looking for a **city or town** (here "Hamburg"): The very first search hit displayed on top of the list shows the city entry for Hamburg. (Actually the 3rd one also, and the 2nd one may be a village which has no streets associated, or I do not have a detailed map for that. But no big issue here.)

<img width="135" alt="city-search_page1" src="https://cloud.githubusercontent.com/assets/845735/18549261/c3d7ffa4-7b4d-11e6-9b56-20bc23a2bcf4.png">

On the second screen I look for a **village** called "Moosbach": The first screen of search hits shows all sorts of surrounding suburbs (organizationally belonging to Moosbach, so they are not wrong), then (not shown in a screenshot) I have to scroll down across about 3-4 screens of streets **(!)** all belonging to Moosbach, until I finally find the main "Village" entry for Moosbach. This "village" entry is what I suggest should have the priority to be shown before all the street-entries (and perhaps the suburbs) just like we do for the "city" entries)

<img width="135" alt="vilage-search_page1" src="https://cloud.githubusercontent.com/assets/845735/18549339/2d6494c8-7b4e-11e6-8b8f-6f8c93cba145.png">
<img width="135" alt="vilage-search_page4" src="https://cloud.githubusercontent.com/assets/845735/18549349/33b130c0-7b4e-11e6-94b1-62dba1f9e487.png">


Moosbach is in Germany/Bavaria, but this issue is not specific to maps or village names, it is universal.
