### ISSUE TITLE
Osmand Crashing when redering maps on MIUI 8

### ISSUE THREAD

**Issue by deavid** [osmandapp/Osmand#3063]
Hello everyone.
I always used Osmand+ (paid version) and Osm Live on MIUI. It worked. The redering was certainly slow, but it worked more or less.

Yesterday I upgraded to MIUI 8 (with full wipe), and everything works fine, excepting OsmAnd+. Now it crashes every time it tries to render. Seems it's something at the final steps of rendering, because I have 4-5 seconds until it crashes. (Maybe near contour rendering)

I tried to activate Safe Mode and works, but it is hard, because I should be faster than the render, or it will crash before i click the option. 

I tried on other phone with MIUI 8 and it also works, seems the problem is with android 4.4.4 + MIUI 8. My phone is a Xiaomi Note 4G Single Sim.

Today I did a fatal mistake: I activated LightRS and now it renders faster and I can't activate Safe mode anymore or disable LightRS before OsmAnd crashes.

I read in some other issue that Safe Mode will disable itself by design if native code loads correctly. But for me Safe Mode is the only way I can use OsmAnd now. And anyway, I also had slow rendering when native code was working, so is not a problem for me.

I'm going to need some external way to tell osmand to not to load native code, and/or activate safe mode. For example, using some sort of config file.

Please, any kind of solution or temporal fix would be greatly appreciated, as OsmAnd is a very useful tool for me.

Thank you!

**Comment by vshcherb** [comment]
Hello could it be related to #3065? Safe mode is quite bad, we need to debug how to get it working.

**Comment by deavid** [comment]
yes, certainly is the very same issue. Sorry I couldn't find it using google while I was searching for this.

Even safe mode being *very bad* it will be useful to have it enabled by default in these cases. Maybe Osmand could look in maps folder for the existence of a file called "enable_safe_mode", and if it exists, disable native mode entirely. That would be easy to code, and almost no one would use it accidentally. And because it would be on maps folder, anyone even without root acces could create or delete the file. And being a file, I could create it without launching osmand.

Anyway I'm going to comment on #3065 from now on and help you debugging as I have a rooted phone.
