### ISSUE TITLE
Can't see osmlive menu anymore

### ISSUE THREAD

**Issue by hughdavenport** [osmandapp/Osmand#3066]
Hi,

Installed osmand on new phone (oneplus3 with cyanogenmod 13) via fdroid (2.4.6). 

I've downloaded a local map and recall seeing the osmlive option, but now it doesn't show.

Where can I get any debug logs from to show?

Cheers,

Hugh

**Comment by kparal** [comment]
I have the same problem on my phone and my tablet. I've seen the osmlive menu once, I configured it, and after next launch the menu is not present anymore. Also it seems like the standard map updates are overwriting the live updates, which is unpleasant.

**Comment by vshcherb** [comment]
>> Also it seems like the standard map updates are overwriting the live updates, which is unpleasant.
This is by design and it is better, cause standard map updates have fuller information (like address)

**Comment by vshcherb** [comment]
Osm Live menu is enabled in developer build only and in paid version OsmAnd+. So it might be related how it is packaged by FDroid (code link https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/Version.java#L100)

**Comment by hughdavenport** [comment]
Can see it. Once I sign up and update it goes away. Assume it will come back when next update comes. Also couldn't pay with osmand~ so will just throw some coin in the address on the page. Is there a way to limit donations by country that way?

**Comment by kparal** [comment]
@vshcherb F-Droid packages it as `OsmAnd~`. So according to what you say, I should see it (where exactly? In `manage map files -> local`?), but I don't. It was visible on the first run as a box "Try OSM Live", but after configuration it's not present anywhere.

**Comment by sonora** [comment]
It should be here: `Menu button (lower left corner of the map screen) / OSM Live (beta)`.  Should you have the Dashboard set to appear immediately when taping the menu button, to see the menu you need to tap the additional menu button in the top right corner of the Dashboard screen.

You can also always simply open the menu by swiping it in from the left screen edge of the map screen.

**Comment by kparal** [comment]
@sonora No, it's not there. But I've seen it updating the maps once in the middle of the night, so the functionality is active, it just does not show up anywhere. A UI bug?

osmand~ 2.4.6 (f-droid)

**Comment by hughdavenport** [comment]
Yeah I don't see it in the main menu. Just saw it once under manage maps -> updates. But disappears after config (and didn't let me pay). Seems to update thougg

**Comment by kparal** [comment]
Could we reopen this? There's definitely a bug somewhere. I don't understand why this was closed.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/activities/MapActivityActions.java#L707
So in the build it should be (versionFeatures="+play_market") cause osm live screen uses inAppHelper for Google Play API it requires to have it.
return ctx.getString(R.string.versionFeatures).contains("+play_market");

**Comment by kparal** [comment]
IIUIC, I should report a bug against f-droid to build osmand~ with `versionFeatures="+play_market"`, right? (Because I have google play and it doesn't show up). OTOH, does that "force" osmand~ users to have google play? Because some f-droid users might not have google play and I imagine f-droid wants to care for such users as well.

**Comment by kparal** [comment]
I reported this at f-droid:
https://gitlab.com/fdroid/fdroiddata/issues/524

**Comment by kparal** [comment]
So, f-droid developers say:
> F-Droid can't build it with features that depend on non-open libs like Googles.

Can something be done from osmand side? Because the functionality **seems** to be working, just the menu item is not displayed, that is all.

If proprietary google play is really required for some reason for osm live, can you perhaps make it a dynamic dependency - if it is present, allow osm live (show it in menus, etc), if it is not present, hide it? So that f-droid can build it without google play library, but if the user has it installed, osmand can still use it?

**Comment by vshcherb** [comment]
Enabled https://github.com/osmandapp/Osmand/commit/d912960f1c30c0a54c83933b7897c1dc95da3dd1, though it needs to be tested

**Comment by kparal** [comment]
Thanks, will report back once a new version is released.

**Comment by kparal** [comment]
After the latest update, I see `OSM Live` in the main menu. Thanks everyone.
