### ISSUE TITLE
Blank screen on Galaxy devices

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#3068]
Different Samsung galaxy devices share the same issue: on OsmAnd 2.4 there's a blank screen and all menus are white, as well. Below is an example from our user.

![rsz_osmand_screenshots](https://cloud.githubusercontent.com/assets/12711814/18468459/c105590e-79ac-11e6-9336-f772d34517e9.jpg)

**Comment by NHellFire** [comment]
Seeing this too on my Note 7 with osmand 2.4.6. All menus are still blank after clearing data.

**Comment by vshcherb** [comment]
@NHellFir please could you do a favour and  answer these questions:
Is it possible to see any map information? Are the menus clickable. If they are clickable, then if you change in settings the theme will it start working.
Was release 2.3.5 ok? http://download.osmand.net/releases/net.osmand-2.3.5-238.apk

**Comment by NHellFire** [comment]
I haven't got any maps installed, so I only get a couple UI buttons. No, I
don't seem to be able to navigate the invisible menus. 2.3.5 works
perfectly. 2.4 is also going underneath the status bar, where as 2.3
doesn't.

**Comment by NHellFire** [comment]
Apparently my screenshots didn't attach. Here: https://imgur.com/a/uUwup

**Comment by vshcherb** [comment]
@NHellFire when you do fresh install of 2.4, you should be able to see first screen and download a specific map. Could you please also provide screenshots of Configure Map (button top right) and Directions map button, just to verify if something visible or not.

**Comment by NHellFire** [comment]
With a map installed, the menu shows. But I did have to clear data several times to get the option to install a map. It kept giving me "get started", then straight to the map, not the map download.

**Comment by NHellFire** [comment]
It seems to be an issue with threads  it looks like the UI isn't being drawn until the map list download finishes, which could take a while if you're on an unstable connection..

**Comment by vshcherb** [comment]
>> It kept giving me "get started", then straight to the map, not the map download.
It should always suggest to download map if maps are not installed. So I'm surprised if we see even more issues.

**Comment by NHellFire** [comment]
See my last comment.

**Comment by vshcherb** [comment]
@NHellFire To confirm, did you see the map menu after a while (when map list is downloaded)? Is it possible to collect logs for the start (https://play.google.com/store/apps/details?id=com.nolanlawson.logcat&hl=ru)

**Comment by crimean** [comment]
@NHellFire Please try nightly build

**Comment by vshcherb** [comment]
Release version which is going to be relaesed to address this issue. http://download.osmand.net/releases/net.osmand-2.4.7-247.apk

**Comment by sonora** [comment]
Please note #3088.

**Comment by vshcherb** [comment]
Fixed
