### ISSUE TITLE
Missing alerts/announcements on speed_camera

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#3069]
Since some weeks I don't get announcement for highway=speed_camera, no vocal no visual announcement.
Both checkboxes (in show alerts and announce) are ON, (I switched them off, closed osmand, and again to ON).
I tested on a road where I got them in the past, tagging is ok.

Versions checked: 2.4.0#18318, 18411
Same problem on pedestrian crossing, see
https://groups.google.com/forum/#!topic/osmand/N78_BYvpLjA

Regards Peter

**Comment by polarbearing** [comment]
Which map version are you using? There was a fix recently that affected cameras mapped as enforcement relations, that requires to use September 2016 maps. See #2921.

If that does not help, you should point to a camera or crossing that is mapped in OSM but not announced.

**Comment by pebogufi** [comment]
I use latest (september) map. No change to older map.
Peter

**Comment by amontag52** [comment]
I think that also traffic lights, pedestrian crossing and speed limit are not announced. Using last Osmand+ and September maps of three regions in northern Italy

**Comment by amontag52** [comment]
you can check traffic lights, pedetrian crossing and speed limit in Viale Prealpi, Saronno, Italy

**Comment by polarbearing** [comment]
You should give specific examples of OSM objects that are not announced.

**Comment by amontag52** [comment]
if you check Viale Prealpi Saronno Italy you will find at least 4 pedestrian crossing and two traffic light (& spedd limit is 50 km/h)

**Comment by polarbearing** [comment]
Seems you are talking about [this road](https://www.openstreetmap.org/way/220662661). The crossings are mapped sloppily, no crossing type is set. A zebra crossing should be tagged crossing=uncontrolled + crossing_ref=zebra. 

Never seen traffic lights being announced in OsmAnd?

Speed warning is only announced when you exceed it, how much did you exceed with which tolerance setting?

Is that happening in navigation or non-navigation mode? Car mode? Snap-to-road on? Is the street name shown on top of the display while driving? Can you provide a screen shot?

**Comment by vshcherb** [comment]
It still not clear about  highway=speed_camera, do we have an example what's not announced?

**Comment by pebogufi** [comment]
Sorry for the delay, I am just back from a test with 2 devices.
Device-1 tablet Samsung Galaxy Tab 2 7.0 (GT-P3100) Android 4.2.2
osmand 2.4.0#16602   2016-05-01
map Germany_baden-wuerttemberg_europe 2016-07-01

Device -2 Smartphone Samsung S5 Neo (SM-G903F) Android 5.1.1
osmand 2.4.0#18411  2016-09-07
map Germany_baden-wuerttemberg_europe 2016-09-01

Start 48.03054 7.85946
Destination 48.02957 7.84382

speed_camera 48.02607 7.84731   Nodeid= 1274634606 (48.0260595, 7.8473207)
highway=speed_camera, with relation

pedestrian-crossing  48.02462 7.85548   NodeId= 3175678914 (48.0246144, 7.85549)
highway=crossing
(maybe here is missing a crossing_ref=zebra, this pedestrian-crossing  was only accidentally in this test)

railway 48.02405 7.84887 637460357 (48.0240522, 7.8488705)
crossing:barrier=no
railway=level_crossing
(the railway=level_crossing was only accidentally in this test)

**Result identical for both devices**:
NO announcement (neither visual nor vocal) for speed_camera and pedestrian-crossing.
Visual announcement for railway.

With device-1 I was in holidays in may and had **a lot of announcements for speed_camera** (pedestrian-crossingwas switched off), but **with older maps**. So i wonder if not the app but the map is the problem.
Need more info or tests ?
Regards Peter

**Comment by vshcherb** [comment]
Fixed, new maps should be generated.
