### ISSUE TITLE
Wrong units of measure in Australia driving region?

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#3070]
If you set "Uk India Australia" as your driving region, the speed is measured in miles per hour. However, Australia uses metric system.

**Comment by crimean** [comment]
How it can be fixed by adding unused enum?

**Comment by sonora** [comment]
True, I got sidetracked researching if there is a Locale country constant for AUSTRALIA (for DrivingRegion getDefaultValue() ), while my commit seems to have closed this issue by some automatism (probably because it contained "Fix")...
