### ISSUE TITLE
Feature: smooth zoom in

### ISSUE THREAD

**Issue by sedrubal** [osmandapp/Osmand#3071]
When zooming in to a position (e.g. double tab on the map or ) osmand first zooms out, moves the object into the center of the view and then zooms in. For better UX this should be done at once in one smooth animation.
- Android: `6.0.1`
- OsmAnd~: `2.4.6`
- offline maps and online

![current zooming](https://cloud.githubusercontent.com/assets/5571650/18480152/e5f8a7ae-79d7-11e6-9bd8-05f8c198d623.gif)

**Comment by sonora** [comment]
Looks like no action planned here for now.
