### ISSUE TITLE
Improve display of cycle routes

### ISSUE THREAD

**Issue by thinking-aloud** [osmandapp/Osmand#3077]
It is awesome, that Osmand can show bike routes in touring view with cycle routes enabled.
Unfortunately, they are hard to see. This is while driving and even worth, when zooming out to plan a route.
Since it is all vector data which is rendered, it is just a styling matter. I assume, the devs did not want to distract with the information. I disagree! I if I activate an optional feature explicitly for my bike tour, than I want to see the feature. Please make it as clearly visible as the cyclemap style.

The other day I wanted to follow the D7 and got like 20KM off track, because I followed the wrong bike-way, as it was so hard to see what to follow.

### Offline tiles in touring with cycle routes enabled:
![screenshot_20160914-235520](https://cloud.githubusercontent.com/assets/1903874/18531747/20c1ad4e-7ad8-11e6-91a1-b6f612d3b523.png)

### Cyclemap online maps:
![screenshot_20160914-235605](https://cloud.githubusercontent.com/assets/1903874/18531758/2ef41974-7ad8-11e6-9f8b-8e82e35cbfba.png)

**Comment by sonora** [comment]
Thanks for the feedback.

Things depend quite a bit on display type, resolution and size, and also on the OsmAnd screen magnification setting you use (you can experiment with this also). But I certainly agree that a feature explicitly selected should be accentuated enough to be clearly visible.

I have made a small correction, effective immediately in our nightly build and can be tested there. Maybe you can test and comment here if the change is enough (from what I see it is a significant improvement).

**Comment by thinking-aloud** [comment]
Jep, that is much better, thx alot

**Comment by sonora** [comment]
Yes, that is the trouble when doing stuff like this: It depends on many parameters like hardware, maps background, lighting, etc., and it is hard to objectively test everything.

Functionally: The more we would decrease the transparency here, the harder it would become to see the underlying type of road, like if it is an (often unpaved) track or a (presumably paved) higher-degree road. 

I will put it up another notch for you to test, let me know if it is too much.

**Comment by thinking-aloud** [comment]
sounds good

**Comment by sonora** [comment]
Yes, from my testing also, it should be good now.

**Comment by thinking-aloud** [comment]
I went cycling the last weekend. Saturday I rode 105KM with the changes, as you made them. I thought, that the second increase was a little too much, so I changed the second changes from this commit back and found it better: 
https://github.com/osmandapp/OsmAnd-resources/commit/b34aef008c264252cd241d9bc3d301febc0fb982

**Comment by sonora** [comment]
Ok, thanks for testing, went back to the middle solution.
