### ISSUE TITLE
Unparsable opening hours are not shown

### ISSUE THREAD

**Issue by HolgerJeromin** [osmandapp/Osmand#3079]
https://www.openstreetmap.org/way/4443742
Has the tag
opening_hours=Feb 16-Oct 15: 09:00-18:30; Oct 16-Nov 15: 09:00-17:30; Nov 16-Feb 15: 09:00-16:30

It is sad that this complex hour is not parsed, but the raw value should at least be visible. 
Right now the row is empty.

**Comment by vshcherb** [comment]
They should be shown in the new version as "Feb 09:00-18:30; Oct 09:00-17:30; Nov 09:00-16:30" which is incorrect but it is a version to see it. 
The format currently supported is "Feb-Oct: 09:00-18:30; Oct-Nov: 09:00-17:30; Nov-Feb: 09:00-16:30"

**Comment by vshcherb** [comment]
@crimean if the value is not parsed we still should display it context menu. On click (may be small icon there) we should display original (not shorten and not translated) opening_hours, please double check design with @dmpr0

**Comment by sonora** [comment]
I guess we have 3 targets to implement here:
(1) Always display opening times as originally specified in the OSM key, not like we interpret of parse it
(2) Display this same text in the search results and on the context card (they differ today!)
(3) Display opening times our parser does not handle in gray, not in red?

**Comment by vshcherb** [comment]
(1) disagree, text is too long
(2) agree
(3) I think we display in gray, red is for closed objects

**Comment by sonora** [comment]
Issue is that our parser makes mistakes in a significant portion of cases. Now just assigning a wrong color is one thing, and can be easily optically verified **if we display the original tag content**.

But if we also modify the tag content and then display it wrong, **we needlessly display bogus**, and I think this is unacceptable?

Regarding "gray" text color: I think I have never seen that for opening times, looks to me like we always default to red.

**Comment by sonora** [comment]
True logic.  :)    But we know we have parsing errors, and as we do it now we remove any capability for a manual/visual double-check...

**Comment by dmpr0** [comment]
https://www.dropbox.com/s/3yiraduzwa0wyk1/Opening_Hours-1.png?dl=0
https://www.dropbox.com/s/7l8tc1sjc3xpt0z/Opening_Hours-2.png?dl=0

**Comment by sonora** [comment]
Looks like we fixed this good for the context menu. Still a small oddity on the search results screen, though, as follows:

Perform e.g. a category search for "convenience stores": If a store is deteced as "open" at the time you perform the search, the opening hours are correctly displayed in green in he second line of the search result in question.

But if a store is "closed" at the time the search is performed, sometimes we only display a red clock icon, see here:
![untitled](https://cloud.githubusercontent.com/assets/845735/20037361/685306d4-a41e-11e6-9cbc-2c9d291bf819.png)

The supermarket is in OSM tagged with opening_hours = Mo-Sa 07:00-20:00 , and this is correctly displayed in this fashion on he POI's context menu (in red and in gray). and if you perform the search when the store is open, it is also displayed like this in green on the search hitlist.

**Comment by vshcherb** [comment]
@sonora this is correct, there is not enough space to show the whole string. If the shop is closed, we can't select one specific rule why it is closed, though if it is open, we can. That's why we display a specific rule when it is opened, but we omit *all* rules if no rules are acceptable

**Comment by sonora** [comment]
I see. What had confused me was that sometimes I did see some red strings like e.g. "Mo, Su off". But that' s in line with your explanation, so ok, I think.
