### ISSUE TITLE
public transport: current stop name displayed in route list rather than "that" stop name

### ISSUE THREAD

**Issue by miklcct** [osmandapp/Osmand#3080]
Enable public transport stops in "configure map". Tapping on a stop shows the routes passing through that stop, and also the routes nearby. However, I expect that the routes nearby shows the stop name of "that" route, rather than the stop name I have tapped on if the stop name of that route is different from the stop name I have tapped on.

In the attached example, I have tapped on a stop of route 214, and it shows nearby routes 58X, 59X, etc. However, the name of stops of 58X, 59X, etc. are different.

![osmand transport stop](https://cloud.githubusercontent.com/assets/2827264/18538059/91a412e0-7b3c-11e6-9762-f5db2c8d65b5.png)

**Comment by vshcherb** [comment]
The link to osm could help, 1 stop position could have only 1 name, usually it is aggregated and taken from platform.

**Comment by miklcct** [comment]
http://www.openstreetmap.org/node/4348153113

This platform is served only by route 214 in the current map data, where the buses 58X, 59X, etc all runs through Cheung Sha Wan Road.

**Comment by aceman444** [comment]
Yes, similarly e.g. at https://www.openstreetmap.org/node/2008956745.
This particular stop "Nam. L. Stura" is only served by bus N33, however tapping it in OsmAnd lists all other routes of busses and trams that stop at the nearby stops with the same name. If that is intentional, there should be some indication that the other routes just go nearby (you can transfer by foot) but do not stop exactly on this exact stop_position.

**Comment by vshcherb** [comment]
@aceman444 it is intentional and you should see how many meters to that stop in braces.

**Comment by aceman444** [comment]
Ok, I can see that distance. But it is still surprising to see buses that do not stop at the selected stop. maybe there could be a toggle in the dialog directly.

**Comment by vshcherb** [comment]
The issue is gone  with latest maps

**Comment by miklcct** [comment]
sorry, still present in 2.5.1 with maps generated with 2016-11-08 master OsmAndMapCreator

**Comment by vshcherb** [comment]
Can't reproduce the provided screenshot with latest map, I see only 214 on that stop

**Comment by miklcct** [comment]
http://www.openstreetmap.org/node/4350900259

This represents a platform at the bus terminus. However, in the following screenshot, buses K75, K75P and K75S do not stop at the terminus but at a bus stop on the street outside.

![screenshot_2016-11-09-01-03-55](https://cloud.githubusercontent.com/assets/2827264/20108922/e2f7568c-a618-11e6-92ad-bee9ea396137.png)

**Comment by vshcherb** [comment]
this is correect that's why you see 100m and the bus stop name where it stops, if you click on it it will be highlighted

**Comment by miklcct** [comment]
but the stop name 100m away is different, called Hung Fuk Estate rather than Hung Shui Kiu (Hung Fuk Estate) Bus Terminus



On Thu, Nov 10, 2016 at 4:02 AM +0800, "vshcherb" <notifications@github.com<mailto:notifications@github.com>> wrote:


this is correect that's why you see 100m and the bus stop name where it stops, if you click on it it will be highlighted

-

**Comment by vshcherb** [comment]
Unfortunately can't reproduce with latest map https://www.dropbox.com/s/357adn7tlnnqqh2/Screenshot_20161110-143511.png?dl=0

**Comment by miklcct** [comment]
Sorry, you have clicked on the wrong item. You should click on a "stop" but not a "public transport stop" to reproduce this issue.

**Comment by miklcct** [comment]
![screenshot_20161114-234621](https://cloud.githubusercontent.com/assets/2827264/20271231/1561f856-aac5-11e6-87f4-24cc3d86c223.png)

The light rail stops are not called Sheung Cheung Wai.

**Comment by miklcct** [comment]
This issue still exists in the current version at the location specified in the above screenshot, where the Light Rail stations are called 坑尾村 Hang Mei Tsuen instead of 上章圍 Sheung Cheung Wai as shown in the screenshot.
