### ISSUE TITLE
Support for what3words.com addresses

### ISSUE THREAD

**Issue by MelTraX** [osmandapp/Osmand#3081]
It would be nice to have support for the what3words addresses in the search and displayed in the pull-up-menu when a location is selected. Offline support would be even cooler than online support obviously.

DuckDuckGo for example already has support for them build in: https://duckduckgo.com/?q=index.home.raft

When parsing the address, keep in mind that several languages are supported and they can contain non-ASCII characters.

**Comment by borghal** [comment]
+1 this would be a nice gimmick.

**Comment by VolkerH** [comment]
+1
I think it is more than a gimmick. Whenever I try to convey an exact location via the phone or similar means this is very useful.
I think  even  "routes" as series of 3 word coordinates could be a simple alternative to GPX files in some cases.

**Comment by scaidermern** [comment]
No, please don't.

what3words is closed, patented and run by a private company. See [what3words in the OSM wiki](https://wiki.openstreetmap.org/wiki/What3words) and also [What3words#Disadvantages at Wikipedia](https://en.wikipedia.org/wiki/What3words#Disadvantages_and_clones) for a list of reasons to _not_ support this address system.

**Comment by karussell** [comment]
@scaidermern exactly!

If you care for open data and open source you should not support them. Read more about it [here](https://blog.ldodds.com/2016/06/14/what-3-words-jog-on-mate/).

(If you really need an alternative use plus code which is [open location code](https://github.com/google/open-location-code))

**Comment by MelTraX** [comment]
Just for the record: By now I agree that it shouldn't be implemented. I won't close this issue myself because it's pretty much still a valid "Nice to Have" but I vote for closing it.

**Comment by wolfwehl** [comment]
There is a small detour via OsmAnd to determine the three What3Words words. To do this, the What3Words app must first be installed.
If you mark a point in OsmAnd, its GPS data can be displayed via "Details". Copy this GPS data (long press) to the clipboard and paste it into the What3Words search in the same way. Now the three words are displayed and - if you are online - shown on a Google map or satellite image.
