### ISSUE TITLE
voice guidance for bike routing

### ISSUE THREAD

**Issue by tobydickenson** [osmandapp/Osmand#3083]
Using osmand for voice guidance with bike routing mostly works very well, but there is one area where I suggest extra voice output would be useful....

In general we dont need any voice guidance when going straight over a crossroads junction. This is true when two roads cross (whether on car routing or bike routing), or when one cyclepath crosses another (on bike routing). There are lane markings etc which makes the "straight over" option easy.

Thats not true when following a cyclepath which crosses a road. This is a significant event which justifies having voice output.

Not having any voice output when cyclepaths cross roads has proved to be misleading on a couple of occasions recently. A good example is at http://www.openstreetmap.org/#map=18/50.88221/-1.24473
When following the red arrow the voice output is "turn left". It is referring to the blue turn, but it is very easy to mistakenly think it means the green turn. Ideally this would say "cross [road details] then turn left"

![screenshot351](https://cloud.githubusercontent.com/assets/292492/18564093/0d485e3e-7b82-11e6-939a-96786f6ea074.png)

**Comment by vshcherb** [comment]
Not sure we could easily fix it, in such cases it is better to look at the map as well.

**Comment by sonora** [comment]
Yes, very tough to improve anything here, I am afraid.There will always be many situations which are only clear optically, but which cannot be sufficiently announced by voice prompts with enough precision,  clarity and the brevity to be in time. Completely "explaining" in a sense of "narrating" Ithe route accoustically takes a lot more AI than is currently feasible,  have no idea for now what could be done here.

**Comment by tobydickenson** [comment]
Yeah, I understand the difficulty of the problem here. I was hoping that detection of cyclepath/road crossings would be an easy thing to fall out of the existing processing.

**Comment by sonora** [comment]
No action planned for now.
