### ISSUE TITLE
Important string with wrong translation

### ISSUE THREAD

**Issue by l2212** [osmandapp/Osmand#3084]
I don't know if there will be a new update for the app soon, but if that's the case I'm asking, if it's possible, to include the new updated "Phrases" strings in it. 

I've noticed, in the 2.4.4 version, that "Library" , in both Italian and Sardinian, was translated as "Libreria", that actually means "Bookstore" (there were two kinds of POIs with the same name). I replaced it with the correct translation ("Biblioteca") but it was not included in the new 2.4.6 version. I'm specifically asking here just because it's a kind of POI that it's quite important, and it would create confusion.

**Comment by sonora** [comment]
Looks to me like we had a number a smaller but significant bugs and outright false translations slipping into 2.4.6, which would probably justify another release update.

**Comment by l2212** [comment]
There were bugs as well? In the case I described the error was man-made, made on the translation system (by me for Sardinian, and another user for Italian). I noticed it using the app, and corrected it after the 2.4.4 update and before the 2.4.6. It was just not included in the update.

**Comment by sonora** [comment]
I am referring to other translation mistakes like #3057, and some other bugs we still had in 2.4.6 but fixed now in the nightlies, unrelated to translations.

**Comment by vshcherb** [comment]
Please create pull-request to appropriate branch if needed.
