### ISSUE TITLE
More UI/behavior parameters as hidden settings

### ISSUE THREAD

**Issue by emuzychenko** [osmandapp/Osmand#3085]
There are many hardcoded values in the application (element size/color/transparency, auto-zoom speed/magnification steps, light sensor sensitivity for day/night mode etc.). Maybe it would be better to move them to settings/preferences files to have a possibility to alter them manually (with a text editor or a simple built-in value editor). It would allow experienced users to fine-tune the app and "run in" some visual/behavior configurations. Users would share their settings and most popular ones could be later implemented as defaults.

**Comment by vshcherb** [comment]
It will be hard to maintain

**Comment by emuzychenko** [comment]
In such case, it would be better to move these parameters to the UI settings. For example, black direction triangles on the blue/cyan route line are poorly distinguishable at low/average brightness levels. Arrows on fully transparent widgets are sometimes completely invisible but opaque widgets cover a significant part of the nearest route if it goes to the upper direction. Optimal speed/distance/zooming parameters are different for different drivers. Each device has its own light sensor sensitivity and calibration is not always possible.

But I understand that moving all the parameters to UI settings will be a hard work and unlikely to be implemented. It is because I proposed to use a hidden settings instead. In Windows, many apps (and Windows itself) have a lot of parameters stored in registry that are inaccessible from the native UI. For example, Miranga IM/NG maintain a registry-like database format and has a free-form editor plugin so an advanced user can change every existing application parameter.

**Comment by Lee-Carre** [comment]
Another one for #7655.
