### ISSUE TITLE
Quick search is unable to find multi-word destinations (phrase search)

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#3086]
In Bangalore, we have community centers called "Bangalore One", where they provide centralized services for multiple public utilities; such as bill payment, grievances, etc.

If I search in opensteermap, I get a [lot of results](https://www.openstreetmap.org/search?query=bangalore%20one#map=19/12.99614/77.54319).

Note that I simply enter **Bangalore** and **one** (two words, without any double-quotes).

But if use the same search in OsmAnd, I get nonsensical results.

**Desired:** The quick search in OsmAnd should handle multi-word searches (phrases) well.

**Comment by littlehelper** [comment]
I observed the behavior described by @raindropsfromsky some time ago too.
But with the latest (nightly) builds I cannot reproduce anymore. For me, it seems to be fixed.

**Comment by raindropsfromsky** [comment]
No I checked this on the latest nightly, and the same problem continues.

**Comment by littlehelper** [comment]
I have played a little bit more with the Osmand search. And I indeed found some cases where Osmand could do better:

I searched for 'Sonnenstraße' (english 'sun street'), a street in my village. I expected to find at least addresses. I entered...
Sonnenstraße - it finds at least the address 'Sonnenstraße',
Sonnen straße - it finds only POIs with 'Sonnen...' but no address anymore,
Sonnen - it finds everything (including addresses) with 'Sonnen...'. 

The same with street name 'Sonnenburgstraße' (english 'sub castle street'). I entered...
Sonnenburgstraße - it finds the address 'Sonnenburgstraße',
Sonnenburg straße - if finds nothing (there do not exist POIs with 'Sonnenburg...'),
Sonnen burg straße - it finds only POIs with 'Sonnen...' but no address,
Sonnen - it finds everything (including addresses) with 'Sonnen...'. 

It seems to me, that especially the address search is affected.

Searching for POIs works fine for me. But it could be improved too:

When entering 'Sonnen burg', Osmand finds a lot of POIs starting with 'Sonnen...', including POIs named 'Sonnenburg', but these ones (I am interested in) are not on top of the result list.
I would love to see the search results which match best on top of the result list (after found matches in my favourites).

greetings.

**Comment by polarbearing** [comment]
@littlehelper - this sounds a bit odd. Your search gives you correct results when you spell the street correctly. So you deliberately split the name into chunks with spaces in between, and complain that it is not found anymore? This is not what the OP meant with multi-word destinations.

**Comment by littlehelper** [comment]
@polarbearing - yes, you are absolutely right. I have chosen my examples unsuitable to demonstrate my issue. Please find an update of my previous comment.

**Comment by raindropsfromsky** [comment]
I think @littlehelper is asking for **fuzzy search**, where matches are found with a little different spellings.

This is an important feature, which is required around the world in Non-English countries (especially where accent marks are used. So if I search for **Mueller**, it should also find **Müller**. If I search for **cafe**, it should also find **Café**. In fact, I have raised this issue as #1971, but it was closed prematurely.

But my bug is not about this feature.

**Comment by raindropsfromsky** [comment]
Coming to my original bug, here is a real life example:

I wanted to go to a spot near the [HAL Police Station](https://www.openstreetmap.org/node/844415776#map=19/12.95508/77.68279).

(Here, "HAL" is a company. Since the police station is located within its premises, it is named after HAL.)

So if I search for **HAL police station**, I get a lot of hits but not the police station! 
![screenshot_20170226-090342](https://cloud.githubusercontent.com/assets/9047168/23337440/fef4deb2-fc13-11e6-82bd-84487305ffbd.png)
![screenshot_20170226-090439](https://cloud.githubusercontent.com/assets/9047168/23337446/0c8049c2-fc14-11e6-97c6-2ebeb6a3f2fd.png)
![screenshot_20170226-090446](https://cloud.githubusercontent.com/assets/9047168/23337447/11865a06-fc14-11e6-81e2-5c1961ccaa12.png)

1. Obviously my intent is to see the result ONLY IF all three terms are present. </br> But I get a large number of hits, most of which have "HAL" in their names, but do not have the other two terms.  </br> Thus the result is useless for me.[Bug#1].
2. Some of these have 'hal" in their name (e.g. "Halal" restaurant,) or in other tags (e.g. "Town hall") [Bug#2]
3. The police station is not in the list at all [Bug#3]

**Comment by raindropsfromsky** [comment]
I had to edit the last post multiple times. 
If you have read it in email, please read the latest version at the GitHub site.

Sorry for the inconvenience!

**Comment by polarbearing** [comment]
> In German-speaking countries it is possible that the example street from above is spelled 'Sonnen Burg Straße', 'Sonnen-Burg Straße' or 'Sonnen-Burg-Straße' etc. 

No that is against German spelling rules, check with your Duden please, K162. Street names are written without space, with the exception of having an adjective derived with -er from a location name (Hamburger Straße), or a multi-part name after a person (Fritz-Moser-Allee). So it is Sonnenburgstraße, however it would be Sonnenburger Straße.

**Comment by DFyson** [comment]
Same could be said searching for _car wash_. It should be the first result, but instead is the 11th result, and the first 10 don't match nearly as well; for example _bicycles_, _cable car_, _auto parts_, etc. This along with #1115 indicate the search algorithm could do with improvement. Aswell, adding house numbers to the search should still return the street at the very least.

**Comment by DFyson** [comment]
Maybe the search needs improved ranking based on the best, most complete match. So currently, for example, it appears searching 'car wash' returns results for anything with 'car' and 'wash'. But how about promoting any results which have full matches of the two words together as 'car wash'?. Then follow this with the AND results but not in any particular order such as 'wash car'. Then all the OR results?
Or better yet, I wonder if would be feasible to just use the search algorithm from mature search engines.

**Comment by UserX404** [comment]
Hello to all.
I also want to report a misbehavoir.
On a Erisin Android device (car radio) I don't have the possibility to enter a 'ß' (sharp S). So i have problems to find anything which include 'Straße'. The search functionality seems to differ between 'Straße' and 'Strasse'. In my point of view 'ss' should be handled as 'ß' whitch is quite the same meaning, isn't it?

**Comment by scaidermern** [comment]
@UserX404 This is a different problem. Better create a new issue for it.

**Comment by ADepic** [comment]
Anything on this? This search mechanic is very frustrating.

This is the quickfix in my opinion:

When searching for "car wash", the app currently returns all results in the nearby area containing "car" and "wash". This should be changed. The app should ONLY return results with both "car" and "wash".

As for bus stops (or railway station or any POI), for example with "Deptford Bridge" bus sop, if the user searches "Deptford Bridge" and "Deptford Bridge Bus Stop", both should return the correct result. When searching for POIs, the POI should be indexed as "<name> <POI type>" - So for example: "Deptford Bridge Bus Stop", "Paddington Railway Station". What is displayed as the results will be "Deptford Bridge" along with "Bus Stop" in a smaller font below it.


This small fix should make the search 100,000x better and it is very easy to implement

**Comment by vshcherb** [comment]
The original issue is already fixed
