### ISSUE TITLE
Crash when tapping the screen while it is being rendered

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#3088]
Rather unclear issue, here is what I know so far. Started yesterday, so I want to document immediately:

Fresh start of OsmAnd, wait until the map is rendered. Then display a city center, something densely mapped (via Search, history, a favorite, does not matter). Tap on the context menu title so map zooms in, then while the map is being rendered, tap somewhere on the map (or pan it a little).

- OsmAnd may crash
- When it happens, it shows the "Unfortunately, OsmAnd has stopped" dialog.
- Afterwards, the GPS icon in the Android notification bar curiously remains on for maybe 3-5 seconds before it disappears.
- No exception.log is being created (!). OsmAnd does not on the next start announce that it previously crashed.
- The issue seems to have started on September 16, I never could reproduce on our last Sept 15 or earlier builds
- The crash is not 100% reproducible, it may take a repeated attempt to produce it. But it does not depend on the map area, seems to happen anywhere.

There are only 3 or so commits on 9/16 to be investigated which can have caused this.

**Comment by sonora** [comment]
@vshcherb : I just noticed that we started building a v2.4.7 service release, pls. note that this regression is release-critical. Versions up to end of Sept. 15 are fine.

**Comment by vshcherb** [comment]
This is only 3.0, it is work in progress. And should be fixed today actually, 2.4.7 has only 1 small change  comparing 2.4.6 and no other changes at all.

**Comment by sonora** [comment]
Ok, fine! Anyway, I had run the 9/15 version through very intensive testing over the weekend, I rate it stable and it has several bugfixes over 2.4.6. It may be a worthy base for a 2.4.7r, but if you rate the risk too high, I certainly understand.

**Comment by sonora** [comment]
PS: So far it looks like this issue here may have dissappeared after this commit https://github.com/osmandapp/Osmand/commit/98cc820fcdb85115eeff4f7f1bc27d5782117d7d
