### ISSUE TITLE
possibility to change crossing icons

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/Osmand#3089]
can we change the crossing icon in OsmAnd?

crossing with highway=crossing + crossing=unmarked have a gray icon.
can we change this to red.
![gray](http://fs5.directupload.net/images/user/160918/uqwxmrc5.png)

crossing with highway=crossing + crossing=uncontrolled have a red icon.
can we change this to blue.
![red](http://fs5.directupload.net/images/user/160918/wnwrxq3d.png)

crossing with only highway=crossing have a blue icon.
can we change this to gray.
![blue](http://fs5.directupload.net/images/user/160918/ln8anuv6.png)

The unmarked crossing is more dangerous as the uncontrolled. On a unmarked crossing, a car not have to stop, but on a uncontrolled crossing, a car have to stop if some one will cross the street.
For this I think we should change the color from the crossings.
If a mapper see some gray crossing in OsmAnd, he can check this on OSM to ad [more detailed](http://wiki.openstreetmap.org/wiki/Key:crossing) information to the database.

**Comment by sonora** [comment]
Makes sense to me. @xmd5a2 We could simply achieve this by rotating the 3 icon names, I think.

**Comment by vshcherb** [comment]
Agree

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/a04ef0e84c90067c870c7b0386f6e3945817aaf9
