### ISSUE TITLE
show rwn_ref on map (just like rcn_ref)

### ISSUE THREAD

**Issue by richardbrinkman** [osmandapp/Osmand#3091]
In the Netherlands (and probably elsewhere) we have cycling and hiking networks consisting of numbered nodes (tagged with rcn_ref for cycle nodes and rwn_ref for hiking nodes (and rhn_ref for horse routes)) and route relations between them.

OsmAnd does render the numbers of rcn_ref's on the map (after selecting the option to show cycle routes), but it does not render rwn_ref when selecting the option to show hiking routes. Is it possible to render the rwn_ref's the same way as rcn_ref's?

OsmAnd~ 2.4.6
Offline maps
Android 6.0.1

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/a60afc73721503b671fe41a1c0283dd58200b79c
Will work with new maps. @richardbrinkman you can help if you test latest nightly with newly generated maps.
