### ISSUE TITLE
Change "current road" icon from blue arrow to blue cross-hair icon

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#3092]
In #2862, an icon has been introduced, both in navigation and non-navigation mode, to indicate that a street name is the road currently being driven on, in contrast to navigation instructions.

The icon was chosen as a blue arrow. Blue is consistent with the blue 'jump to current location' button.
![blue-arrow](https://cloud.githubusercontent.com/assets/8266355/18625345/5816c346-7e4e-11e6-9310-80ce0e8c0beb.png)

However the arrow is being misinterpreted by users as a navigation instruction. 

It is understood as '_follow XYZ road until further instructions_', while it means '_you are currently spotted on XYZ road_'. In particular, the icon might appear in situations where the straight arrow contradicts navigation instructions. See discussion in #3007.

The situation was initially tested with a crosshair UTF character ⌖, which failed on some devices due to font implementation. 

Thus, with hoping for @sonora's support, I repropose to use an icon graphic for a crosshair, mockup as below, but probably better blue on white: ![screenshot_crosshair-name](https://cloud.githubusercontent.com/assets/8266355/17085263/5861b6ae-51d4-11e6-82b9-7a572bfa7394.png)

**Comment by sonora** [comment]
Yes, I think it makes sense. Here my mockup, using our `map_my_location.png`.

<img width="274" alt="5861b6ae-51d4-11e6-82b9-7a572bfa7394_" src="https://cloud.githubusercontent.com/assets/845735/18630563/bbf60fce-7e6d-11e6-9ff0-f3831b469d1d.png">.

**Comment by vshcherb** [comment]
I quite disagree and I think the icon is more confusing cause 
1) it looks clickable
2) it doesn't mean "current street", "my location", I think it means "find my location" .
The arrow means "go forward on ...", though I think it might be possible to have another icon "arrow" which could mean "driving on .."

**Comment by polarbearing** [comment]
thanks @vshcherb - certainly a different icon would help as well. Probably the icon would be used in other transport means as well, so we might search not only for "driving on" but more general for "being on". Ideas:
- a pin http://icons.iconarchive.com/icons/icons8/windows-8/128/Editing-Pin-3-icon.png
- a locator https://cdn4.iconfinder.com/data/icons/pictype-free-vector-icons/16/location-alt-512.png
