### ISSUE TITLE
Openstreetmap hyperlinks not recognized

### ISSUE THREAD

**Issue by zeljkovukovic** [osmandapp/Osmand#3094]
When I click a hyperlink in some app, OsmAnd is available as one of the handlers. If the link is for Google Maps it works, but strangely if the link is in the format that OpenStreetMap uses,  OsmAnd does not always read Lat/Long correctly. To sum it up, here are some examples:

https://www.google.rs/maps/@45.2441623,19.843583,16z?hl=en
Opens up correctly, POI is added to where the Google Map was centered.

https://www.openstreetmap.org/#map=18/45.24491/19.84450&layers=N
Opens as Lat: 45.24491,Lon: 0.0

http://osm.org/go/0KgT5mK9Z--?layers=N&m=
Opens up correctly (Short "share" link)

OsmAnd 2.4.6

**Comment by sonora** [comment]
Looks like the error is caused by the trailing `&layers=N` in the second URL. Will have to look at our parser to see how to fix this.
