### ISSUE TITLE
Incorrect rendering on map for complex characters in Devnagari script, Marathi language

### ISSUE THREAD

**Issue by onkarshinde** [osmandapp/OsmAnd#3096]
Please give us the following information so that we can try to **reproduce** your issue:

What version of OsmAnd are you using, on what device and Android/iOS version?
OsmAnd+ 2.4.6

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?
Offline maps

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.
Asia -> India -> Maharashtra, 1 Sep 2016
1. Set the map language to Marathi (mr)
2. Search for Kolhapur using quick search
3. Show the first city on map
4. The rendering of the Marathi name on map is wrong. If your select the node, the rendering in the info bar at bottom is correct.

Please see attached screenshot demonstrating the problem.
![screenshot_2016-09-20-01-41-01](https://cloud.githubusercontent.com/assets/5102265/18647949/0b738154-7ed6-11e6-9308-fe50e83ee375.png)

**Comment by onkarshinde** [comment]
Forgot to include OS details - Android 5.1.1, Nexus 4

**Comment by arjunaraochavala** [comment]
Same problem for Telugu language names.
Redmi Note 4, Android 7.0 NRD90M
Osmand  3.4.4

**Comment by Oymate** [comment]
Bangla names too, Android 10, 3.8.5

**Comment by Oymate** [comment]
Any update? The maps are unusable in native language :(

**Comment by Oymate** [comment]
Is the app using harfbuzz library or something else?

**Comment by vshcherb** [comment]
Nope we have another task / issue to integrate harfbuzz it still uses icu which doesn't work correctly

**Comment by vshcherb** [comment]
Should be fix with 4.1 release actually
