### ISSUE TITLE
While navigating along a route, a "nearby POIs" card pops up and hides the current position marker

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#3102]
Using the OsmAnd~2.4.0#18519M nightly, with the latest "active POI layer" feature.

While navigating along a route, a "nearby POIs" card pops up at the bottom of the screen.

I have set the map orientation to "To direction of movement".
In this mode, the current location marker is at the bottom of the screen during navigation.
Thus the  "nearby POIs" card ends up hiding the current position marker.

**Comment by vshcherb** [comment]
We can't confirm that  "nearby POIs" pops up from bottom, any screenshot is needed.
