### ISSUE TITLE
Fully interactive map: Include Wikipedia POIs

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#3109]
Just an implementation reminder:

If we want to go the route I suggest with OsmAnd, i.e.  to develop it also further in the direction of an **electronic travel guide**, we need to include the context menu display of Wikipedia POIs (paid OsmAnd version) as tappable objects in our new Interactive map / Single-tap functionality. (Carry-over from #1862).

**Comment by vshcherb** [comment]
Will be hard to do, but we can do it similar to the transport search we already have
