### ISSUE TITLE
Osmand+ crashes when charging is cut off

### ISSUE THREAD

**Issue by PoloShock** [osmandapp/Osmand#3110]
Very annoying issue we were experiencing during our travels. When our tablet is plugged charging and the cable is suddenly unplugged (before full charge), Osmand+ 2.4.6 is almost guaranteed to freeze in that moment. Closing Osmand and relaunching it will eventually cause Osmand to "stop" (the Android message) and then it can be finally re-started properly.
The freezes were common during offline navigation, although I think it happens even without ongoing navigation.

The tablet is Sony Z3 tablet LTE
Osmand version is 2.4.6

Thank you for any fix on this issue. Osmand is otherwise very capable nav app and I love using it. :)

**Comment by sonora** [comment]
@PoloShock, This really sounds to me like a hardware issue. If this is a new device I  would ask the dealer to exchange it, it sounds to me yhat there is some flaw which does not take the brief voltage bump too graciosly...

**Comment by vshcherb** [comment]
Unfortunately can't reproduce it on our devices.

**Comment by PoloShock** [comment]
It seems the problem (and others as well) disappeared when I disabled Contour lines plugin. The whole app is now stable for me. I will keep an eye on it.

Anyone else is having instability issues when contour lines are turned on?
For example zooming anything above 50km scale will almost certainly result in a crash for me.

**Comment by sonora** [comment]
Could be a faulty SD card, if you are using one, try re-formatting it or
try another one.

On Tue, Oct 18, 2016 at 6:20 PM, Miroslav Bartyzal <notifications@github.com

**Comment by PoloShock** [comment]
I think the problem was that I had all maps of Europe active at once. Deactivating maps I don't use (via deactivate context menu) solved most the issues with instability.
