### ISSUE TITLE
Tap to select GPX track

### ISSUE THREAD

**Issue by PoloShock** [osmandapp/Osmand#3111]
It would be great to be able to directly tap-select GPX track on the map in order to navigate to it / display its name etc.

**Motivation**:
Before we take off on our trips, we put in a lot of GPX tracks which are named according to their attributes (paved road / offroad + difficulty) etc. Later, as we go from POI to POI, from Track to Track, it is very difficult for us to get the info about the on-map displayed track since it can't be selected by tapping on it. Then we have hard time deciding where to go next. Currently, I am forced to disable viewing all other (20+) tracks by trial and error in order to find out what track am I looking at.

**Comment by sonora** [comment]
Here is what I do (and maybe his is really the best solution, actually):

Add a GPX Waypoint to each of your tracks (I do it at the very beginning of each track). GPX Waypoints can be viewed both in our "My Tracks" interface (tap on any track then view the waypoints screen), or can be tapped on the map (very much like Favorites).

In its name tag and its desc tag (think we do not yet support the cmt tag, but it is on my roadmap, as many hiking books use it) you can code any details you would quickly want to be able to see about the track.

Syntax, if you want to do things manually:
```
<wpt` lat="xx.x." lon="yy.y">
<ele>939</ele>
<name>NAME</name>
<cmt>COMMENT</cmt>
<desc>DESCRIPTION</desc>
<sym></sym>
</wpt>
```

**Comment by sonora** [comment]
cmt tag now also supported to be displayed.

**Comment by PoloShock** [comment]
That is a very smart way of working it around, thank you for sharing the idea! :)

**Comment by vshcherb** [comment]
Tappling on the line is not supported yet, same applies to public transport route.
