### ISSUE TITLE
Add ability to create public book case POI

### ISSUE THREAD

**Issue by vlotorev** [osmandapp/Osmand#3112]
As of 2.4.7 it is not possible to create public book case POI: http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpublic_bookcase.

if I fill amenity=public_bookcase manually, then application does not allow to create such POI.
Please, allow creating such POI.

**Comment by xmd5a2** [comment]
It is possible to create unsupported POIs. Just do not fill poi type field and go to "additional" tab and add tag manually. But I'll add this POI to osmand.

**Comment by vlotorev** [comment]
Thanks

4 окт. 2016 г. 2:23 PM пользователь "xmd5a" <notifications@github.com>
написал:

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/db96a695d1c17159779528ab2f8eb827a3a18e50
