### ISSUE TITLE
Website spelling error:  "record you trips"

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#3114]
The scrolling screenshots at http://osmand.net/ for Android contain a spelling error.  One of the screenshots is "Record you trips" and it should be "Record your trips."

**Comment by sonora** [comment]
Fixed, thanks! (https://github.com/osmandapp/osmandapp.github.io/commit/26d26322c5649ebe36dcca4dff965f42b5359827)

**Comment by njohnston** [comment]
@sonora: the mistake is still on the Google Play listings for both the free and paid versions. Could you fix it there too please? :)

**Comment by sonora** [comment]
In the Play Store listing? Can't see it... can you provide a screenshot?  Thx!

**Comment by sonora** [comment]
@vshcherb , @annasoloviova : I uploaded a fix for this by amending the faulty png file, but did not find the original vector source of the caption, meaning the amended picture has sligly worse quality. Please check if you can overwrite with a better version created from the original source.
