### ISSUE TITLE
Fails to interpret geo coordinates from an external navigation request

### ISSUE THREAD

**Issue by Code7R** [osmandapp/Osmand#3115]
Precondition:
Using Osmand version 2.4.6
Using https://play.google.com/store/apps/details?id=com.dapr.lpgfinder.activity&hl=de to find a compatible fuel supplier.

Repro steps:
clicking identified fuel station
selecting "navigate to..."
When the navi app selector pops up, select Osmand instead of Google Navigation

Expected outcome:
Osmand places a destination mark on that location and starts routing

Actual outcome:
Osmand shows a tooltip "Invalid format: q=49.0183 ,8.35441" and nothing else happens

Tried to monitor this with logcat, here is the relevant part. Note: the space char before comma is really there, maybe this is the trouble maker?

V/WindowManager(  870): not Base app: Adding window Window{e5b14a1 u0 com.dapr.lpgfinder.activity/com.dapr.lpgfinder.activity.LpgMap} at 15 of 22
I/ActivityManager(  870): START u0 {act=android.intent.action.VIEW dat=google.navigation:q=49.0183 ,8.35441 flg=0x10000000 cmp=android/com.android.internal.app.ResolverActivity} from uid 10103
 on display 0
V/WindowManager(  870): addAppToken: AppWindowToken{1a14e423 token=Token{1b6cc952 ActivityRecord{237359dd u0 android/com.android.internal.app.ResolverActivity t5871}}} to stack=1 task=5871 at
0
D/WifiService(  870): acquireWifiLockLocked: WifiLock{NlpWifiLock type=2 binder=android.os.BinderProxy@11b4dfce}

**Comment by vshcherb** [comment]
Intent google.navigation:q=49.0183 ,8.35441 not supported yet.

**Comment by sonora** [comment]
Maybe it actually makes sense we introduce some sort of "**fallback parsing**" as a last-try resort, where we just strip any text from the URL in the intent and interpret the first occurrence of a number as Lat, the second as Lon. While this can certainly fail also (or produce crap), from what I see, this could correctly interpret many (even otherwise unknown to us) geo links correctly...

**Comment by vshcherb** [comment]
That's actually true we need to get back to our intent handler and redirect to our new search.

**Comment by georg-d** [comment]
I experience exactly that issue in OsmAnd 4.1.11 – is it a regression or was the fix buggy? 

I would not mind that if the search request from the other app would appear in search history, so "48.0769666667 ,11.1156222222" appeared as a recent search and I could easily correct the format (that's how I do it in Locus). Sadly, the search term does not appear in search MRU.

![OsmAnd called from outside app](https://user-images.githubusercontent.com/45993293/160306250-2c86c10f-0f43-44f9-88c5-b406a529d5dc.jpg)
