### ISSUE TITLE
Idea: save/load selection of destinations

### ISSUE THREAD

**Issue by Unnamed-1** [osmandapp/Osmand#3117]
Hi,

right now, a user can plan the route locally by setting start and destination and some intermediate destinations. Now it would be really nice to be able to save this selection (start point and all destinations and maybe the routing profile) as some kind of preset (or "plan" or "trip" or "route project", you name it).

There is a usecase for that. When I am on vacation, I would like to plan and preview the hiking trip the day before. Then make another calculation (a car or train trip to somewhere close to the target area). And when arrived at the site, I would like to reload the previous route calculation for hiking.

Right now you cannot do that. You could add both kinds of destinations to the same route plan but it's bad because the waypoints for hiking are not accessible to cars and the routing goes nuts all the time.

**Comment by sonora** [comment]
We have functionality implemented which is more or less equivalent: When setting up a route enter the starting point, destination, and any interim destinations you want. Then after the route is calculated, simply save the route as a GPX file (On the route config dialog, tap on the line with the route details, which puts you on the route detail screen, there is a save button).

Any saved route can be displayed on the screen again via our "My Places / My Tracks" interface. It will also display all destinations formerly set as tappable icons. You can either use the GPX route directly (hit route, answer "yes" when asked if you want to use the displayed GPX), or setup a new navigation by tapping on the GPX waypoint cons one by one and adding them to a new route.

Hence if you want to save groups of destinations, you can use this functionality, and if you want to save single points, we have the Favorites for that, I would think no new mechanism is needed?

**Comment by Unnamed-1** [comment]
Hello,

first, thanks for pointing out how to store the route as GPX track. I never found that option and I checked all menus I was aware of (main menu, dash board, navigation options, map layers, ...).

Using that feature would cover a part of the mentioned scenario. However, it's not flexible. Just imagine what happens - you plan your hiking trip (with that method), you walk along a GPX track. But then a forrest path is blocked (closed because of flooding, for example). And then getting around becomes tricky.

Another option would be, as you mentioned, saving every waypoint as favorite. But then you lose the connections. And you clutter your favorite list with waypoints having minor temporary meaning. And you need to restore the order by adding them manually one after another. I mean, this is a viable workaround but it's not convenient. It would be nice if you could store a group of waypoints and their order on the navi route as one item.

**Comment by sonora** [comment]
Thinking about this some more I actually fail t see what the difference would be for yet another "save" feature.

Flexibility: For blocked paths we have the "Avoid" feature in the navigation menu.

Maybe you also want to play with the trip planning plugin, it has yet again functionalities to save GPX files, maybe it helps?

**Comment by sonora** [comment]
Should be part of coming Map marker improvements, I guess.
