### ISSUE TITLE
Idea: display and filter subtypes in the POI selection

### ISSUE THREAD

**Issue by Unnamed-1** [osmandapp/Osmand#3118]
Hi,

it would be nice to reduce the offered available POIs and filter them a bit.
I am not sure about the exact details because I don't know how you store data and which kind of query semantics are possible in your search engine. The exact selectors might need to get some hardcoded grouping descriptors which is manual work and needs additional maintenance. However, at least for some usecases the work is worth it.

And there are usecases like:

- as car driver, I am looking for an Ethanol fuel station, I would like to skip all other types of fuel (the same applies to users of gas cars, like LPG or CNG, also see #656 )
- as non-religious person, I would like to see some nice sights but skip churches. Unfortunately, in some regions if you select "sights" in the POI selector, 9 of 10 POIs will be churches... every boring church in every boring village will be displayed on the map *sigh*
- as busy traveler, I would like to see only fast-food restaurants on the map. However, there is no clear distinction right now if you select "gastronomy".

**Comment by vshcherb** [comment]
This will be done in a future release but slightly different form.

**Comment by matthijskooijman** [comment]
For anyone stumbling upon this old issue (like I did), it seems this is now possible using the "search" feature. When doing a normal search, POI (sub)types now appear in the results. E.g. if I search for "Camp site", it shows the "Camp site / Tourism" POI category in the results. If I tap that, and then tap "SHOW CAMP SITE ON THE MAP", a POI overlay for this subtype is shown on the map. If I then go to the map configuration, I see that the POI overlay now is set to "Camp site" as well.
