### ISSUE TITLE
Zoom level changes sporadicaly

### ISSUE THREAD

**Issue by Unnamed-1** [osmandapp/Osmand#3120]
Using version: 2.4.6 (F-Droid build)

Problem: I am sitting in a room and scrolling around the map, then stop. No routing/navigation is active. And suddenly, the zoom level changes! But why? At that moment, the displayed map tile is far away from my current position.

I have a hunch - my GPS receiver is flaky, the fix is not precise, appears or gets lost every minute. When such zoom jumps happen, the speed indicator also displays random walking speed, 4km/h or 16km/h or 24km/h or something. The moments when this ghost speed changes seem to correlate with the zoom level changes.

However, if that is the reason, I am not sure how to detect the bogus position reports. Maybe use the accelerometer sensor to obtain more data for the Kalman filter?

**Comment by sonora** [comment]
I have never seen this kind of behavior on any of my devices under any circumstances ... will need some help here to debug:
- does it disappear when you select "No auto zoom" in the navigation settings?
- does it disappear when you turn your device's GPS off`?
- does it disappear when you turn your device's location service to use just GPS, not a combination of network and GPS methods?

**Comment by Unnamed-1** [comment]
Cannot reproduce it anymore. Auto-Zoom was set to "middle". GPS was turned on but the GNSS chip of my phone sucks. Usually Osmand reports the wifi-based position only for a very long time then after about a minutes I see a FIX but for a while it's unstable, reported every 5-10 seconds and with a precission of 10-50 meters.
