### ISSUE TITLE
Idea: limit the maximum slope in bicycle routing

### ISSUE THREAD

**Issue by Unnamed-1** [osmandapp/Osmand#3123]
Hi,

in the latest F-Droid version (2.4.6) I was not able to find any option to avoid too steep roads and it would be good to have one (maybe even two, different for up- and down-hill).

Rationale: there are urban areas where you can go the easy way (which is longer when looking at the 2D map) and a crazy way (driving straight over a high hill), and Osmand usually prefers the crazy way.

I know there is the commercial "contour lines" plugin in the Play store but according to the description, it can only display the lines or shading. But if it cannot influence the routing algorithm it's not really helpful.

**Comment by utack** [comment]
If you are really into bike routing, consider installing BRouter. It is a dedicated router for bikes, very advanced.
You can play with some profiles on http://brouter.de/brouter-web/ and use the one you like best in the BRouter Android app, which can be selected as routing method in OSMAnd

**Comment by vshcherb** [comment]
There are features coming this release which are solving most use cases of this issue.
