### ISSUE TITLE
Share Locations

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#3124]
1. When application was open and you click the link from external app, the shared location marker is not shown

2. When application was closed and opened via osmand link, there are problems with touch zoom in/out and pan the map

**Comment by sonora** [comment]
Victor, are you talking about our release, or our nightlies? Because
**(1)** Sounds like #3097, and I think my commit there had fixed that. Cannot reproduce ever since.
**(2)** Sounds like #2643, and that was also fixed reliably, from my testing...

**Comment by vshcherb** [comment]
The issues I experienced where from last week build. So I think #2643 is not fixed yet, but #3097 may be is fixed.
