### ISSUE TITLE
Waypoint names cover the map

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#3126]
Users request an option to hide names of the waypoints because they can cover up the map.
![rsz_screenshot_2016-09-10-09-50-44](https://cloud.githubusercontent.com/assets/12711814/18881547/67aef476-84e4-11e6-8a45-5bc603a005f4.jpg)

**Comment by sonora** [comment]
Anna, It is implemented: `Menu / Configure map / Point labels`
