### ISSUE TITLE
[Feature request] Larger navigation widgets for visually impaired users

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#3127]
Our visually challenged users request big arrow widgets to be able to see the direction of the next turn better. Also, they request a wider variety of colors for GPX tracks because some colorblind people cannot distinguish them well.

**Comment by sonora** [comment]
Regarding the GPX colors: People could use the Map style "Touring view", which also provides a little more contrast than our default style. When it is used, I also then provide the full range of rainbow colors available in the "GPX color" menu.

**Comment by Merida1** [comment]
Hi, I hope there is a user who can help me solve my problem for bigger widgets.

**Comment by sonora** [comment]
Can you elaborate:
- Which widgets would you like to see bigger, all of them?
- If you are talking about the font size: Are you aware it can be scaled on most devices in the Android system settings? 
- If you are talking about the widgets as a whole: Do you need to see the map at all? Or are you suggesting a mode where the nav arrow widget covers the entire screen?
- If you are talking about all widgets, but still want to see the map, what is your target scenario how the screen should look? Simply as is today, but all widgets scaled up, by how much?

**Comment by Merida1** [comment]
Hi Hardy

Tanks for your interest in my question.

It wouldt  be nice if the widget in the left upper corner would be scalable so I could choose a good size for me. Also it would be nice if the direction arrow would appear as a big widget in the center of the screen showed on the map when I am approaching the turn I have to make. 
For a registration of speed and other information I use my Garmin Edge 1000 so the widgets in the right upper corner are of less interest for me.
Only the widget to start the track recording is very importent to me.  And the + and - widgets on the right down corner could be bigger for me.
I appologice for my bad English. I hope you understand what I mean.

Regards
Jos

**Comment by sonora** [comment]
Jos, thanks for clarifying, I think this request is now much better specified and understood.

Looks like a possible enhancement to the Accessibility plugin, or maybe also something similar to what is suggested in #3127.

The only immediate workaround I can think of: Not sure if you are familiar with the "Triple tap" functionality, I have seen this on some Samsung devices. You can triple-tap any area of the screen, and it will enlarge the section by a factor which can be controlled by pinch-zoom (you can also pan with 2 fingers if needed). So if you enlarge the upper left corner of your screen before setting of, it may sort of solve your issue.

**Comment by Merida1** [comment]
I tried the 3 tap method on my Samsung S7 but only the map will zoom in.
You can't zoom in the widgets.

**Comment by sonora** [comment]
Weird, I have just tried on an S4 Mini and the attached screenshot shows my **entire** screen when 3-tap-zoomed to the nav icon (magnification factor is of course adjustable, I have it enlarged so that the widget fills the entire screen), so it works ok there. Strange that this OS feature should make a difference between OsmAnd map background and map screen widgets ...?!?

![screenshot_2016-09-28-12-07-45](https://cloud.githubusercontent.com/assets/845735/18909637/a7c9ced8-8574-11e6-9e47-8a0ebb9a3e93.png)

**Comment by sonora** [comment]
PS: Maybe you are talking about the "Map magnifier" feature we have in OsmAnd's Configure map menu.

I am talking about an Android feature some (maybe all) newer Samsung and maybe also other devices have: In the Android (not OsmAnd) Settings, go to the Accessibility settings and activate "Magnification gestures".

**Comment by Merida1** [comment]
Hi,

I activated “Magnification gestures” 
> Op 28 sep. 2016, om 12:19 heeft Hardy <notifications@github.com> het volgende geschreven:
> 
> PS: Maybe you are talking about the "Map magnifier" feature we have in OsmAnd's Configure map menu.
> 
> I am talking about an Android feature some (maybe all) newer Samsung and maybe also other devices have: In the Android (not OsmAnd) Settings, go to the Accessibility settings and activate "Magnification gestures”. on my samsung S7 but I only can magnify the map and none of the widgets. Do I have to adjust a setting in Osmond so I can use the Android function to magnify the widgets? Maybe the 3 tap function does not work on a S7.
> 
> 
regards
Jos

**Comment by Merida1** [comment]
Hi Hardy

The 3 tap function works. I found out that I had to tap 3 times quickly after each other to zoom in on the widget.

Regards
Jos

**Comment by sonora** [comment]
No immediate action planned, I guess.
