### ISSUE TITLE
Opening hours parsing issue where only weekdays are mentioned

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#3128]
For this node http://www.openstreetmap.org/node/638929296 OSM tagging is opening_hours = We,Sa,Su, but OsmAnd displays We, Sa, Su **off**.

**Comment by aceman444** [comment]
What do these opening hours actually say? Is that shop open on We, Sa and Su 00-24? Probably not, it looks like incomplete tagging.

**Comment by sonora** [comment]
Good point, I think you are right! My concern is mainly that we add the "off" here for no apparent reason (and with no "off"  or "except" appearing in the tag), so I think that may be an OsmAnd flaw we want to look into.

This seems to be some sort of mountain hut and I think what is meant here is that it is manned only on these 3 weekdays .... can't say why no time is specified, but that certainly seems a tagging deficit.

**Comment by vshcherb** [comment]
This is incorrect tagging, so results are rather unpredictable and we couldn't fix it from our side easily.
