### ISSUE TITLE
military=bunker POIs can't be found

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#3129]
In the latest OsmAnd 2.4.6 I can't find any military=bunker POIs. The search even offers a "Bunker" category, but it shows no results. No POIs found in the list, none shown on map.
Try map of Slovakia as of 1st Sep. 2016.

**Comment by aceman444** [comment]
Maybe the problem is that there is no military=bunker in https://github.com/osmandapp/OsmAnd-resources/blob/master/poi/poi_types.xml ? There is only building=bunker. But in rendering_types.xml you convert building=bunker to military=bunker. The bunkers are being rendered, they just can't be found, not even by 'name' tag.

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/1de963f35f3d2c7b84dd23de2012c87c1c6c4662

**Comment by aceman444** [comment]
Thanks.
