### ISSUE TITLE
Reach required accuracy before logging a point

### ISSUE THREAD

**Issue by jkufner** [osmandapp/Osmand#3130]
When logging a track every few seconds/minutes GPS needs to get fix before every point. But it takes additional few seconds to get a good fix of nice accuracy. Now osmand accepts any fix and immediately logs a point. The result is a very ugly recorded track - the line jumps randomly around the real path.

I tested this with [GPS Logger](https://f-droid.org/repository/browse/?fdfilter=logger&fdid=com.mendhak.gpslogger) and when the minimal accurancy is set, it produces nice lines on the map even with larger logging interval.

However, the reasonable minimal accuracy may be dependent on device and maybe even on external conditions (forest, mountains, tunnels). Maybe the condition for a nice accurancy could be something like "wait max X seconds after getting fix if accuracy or until accuracy is getting better" to automatically adjust desired accuracy using heuristics to guess whether it makes sense to wait a little or not.

**Comment by vshcherb** [comment]
Agree, we need to have minimal accuracy setting and minimal radius. For now all points with accuracy 50 m are accepted

**Comment by sonora** [comment]
In adverse conditions, a bad point is better than no point. I guess the best and simple fix for this is simply to wait 3 seconds after acquiring a fix before logging a point, this solution will very likely suffice in all situations.

**Comment by jkufner** [comment]
Simple wait may or may not work. There should be some adaptive heuristic, which will decide whether to wait for better point or not.

Example 1: Osmand wakes up and reads a point from GPS. It gets 50m accuracy and decides to wait for a better point. After a short while the second point is read with 40m accuracy. Since the improvement is detected, Osmand waits again. The third point has 8m accuracy. But the fourth has 10m accuracy, so Osmand decides that best point was the third and is logs it.

Example 2: GPS is being used actively and Osmand reads the first point. It has accuracy 4m. Osmand decides it is good enough and log the first point.

Example 3: We are inside a tunnel. There is no fix for X seconds. Osmand gives up and waits for a next interval 2*X seconds. (X may be 60 seconds or so.) Later we left the tunnel, GSM network is detected and Osmand tries to get a point instantly, not waiting 2*X anymore.

Example 4: In deep forest, bad signal. Osmand receives a first point with 60m accuracy. 2sec later the second point with 40m accuracy, the third again with 40m accuracy. It tries the fourth point, but it is also with 40m accuracy. Osmand gives up and logs average of three bad points.

Example 5: As in Example 4, but fourth point has 20m accuracy. Osmand does not wait anymore, because it took too long already (sum of waits >= X).

I don't specify exact timming, just trying to describe, how it could work.

**Comment by sonora** [comment]
Please note that there is no such thing as "meters accuracy" in current GPX chipsets. You are probably misinterpreting hdop. From my testing, in the vast majority of all cases, the 3rd point after GPS wakeup  (usually one fix is provided per second) is significantly better than the 1st, so I still vote for simply trying  (3sec to start with)  wait period before developing any complex heuristics here.  I think he results may be very convincing.   :)

**Comment by jkufner** [comment]
The heuristic does not have to be complicated. What I described is basically a simple combination of a timeout and a desired accuracy with increasing the timeout when the accuracy is getting better (because then it makes sense to wait a little more).

The [GPSLogger](https://github.com/mendhak/gpslogger) I mentioned has option to set timeout and minimal accuracy (nothing more complex there). The constants needs to be fitted to match quality of your GPS receiver and current environment, but then it logs nice smooth tracks with little battery usage. I would like to avoid such constants in Osmand and make it work out-of-the-box without messing with some numbers users don't care about nor understand.

**Comment by sonora** [comment]
Exactly: zero new parameters- we have too many already for the general usrr to understand. Please test OsmAnd loggibg with an interval of 15s or shorter. This way you log an accuracy essentially equivalent of what I am suggesting.

**Comment by sonora** [comment]
Could be improved, but basically implemented.

See also http://osmand.net/features?id=trip-recording-plugin#Trip_Logging:_Some_Basics_on_Parameters_and_Filtering.
