### ISSUE TITLE
Navigation not fallowing turn restrictions 

### ISSUE THREAD

**Issue by idenkov** [osmandapp/Osmand#3131]
What version of OsmAnd are you using, on what device and Android/iOS version?
OsmAnd 2.4.7 
Samsung j3
Android 5.1

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?
Offline maps

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.
Bulgaria - September 2016

The problem is that the navigation in car mode will calculate turns that are not allowed. Not sure how and if you pull that data from OSM. The fallowing screenshots are from the same intersection.
![screenshot_2016-09-28-02-46-10](https://cloud.githubusercontent.com/assets/8784288/18895974/7bc5067a-8526-11e6-8d8d-33075325fc1f.png)
![selection_001](https://cloud.githubusercontent.com/assets/8784288/18895979/874c2f64-8526-11e6-8e75-d7bc702741bc.png)

**Comment by stephan75** [comment]
There has been an issue with map creating tool about that.

Some users confirmed that re-download of the map file helped.

**Comment by sonora** [comment]
See #3067, it should be fixed already.
