### ISSUE TITLE
FAQ formatting is broken

### ISSUE THREAD

**Issue by Nutomic** [osmandapp/Osmand#3132]
https://github.com/osmandapp/Osmand/wiki/FAQ

Edit: [TechnicalArticles](https://github.com/osmandapp/Osmand/wiki/TechnicalArticles) also looks weird with the code formatting.

**Comment by vshcherb** [comment]
Not supported any more, same information is present on the website

**Comment by Nutomic** [comment]
In that case, you should just delete the wiki pages.
