### ISSUE TITLE
render feeding places

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#3134]
Please render amenity=feeding_place and amenity=game_feeding.
They are mostly the same for now:
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dfeeding_place
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dgame_feeding

You can render them the same and even preprocess one into another when creating obf file.
Thanks

**Comment by xmd5a2** [comment]
@aceman444 can you explain how this relates to the game?

**Comment by aceman444** [comment]
I'm not sure I understand your question. 'Game' in this context are wild forest animals, like deer. Feeding places are installations where people put food (hay, grass or something) and the animals come there to eat it (when people are not there). In some areas of world such places are placed often in forests or boundaries of fields/meadows.

Yes, feeding_place is not only for game (forest animals), it is more universal (for any animals). BUt the usage counts are not yet high enough to distinguish the objects or even determine the correct tagging. So I propose to render them the same for now.

**Comment by vshcherb** [comment]
Sounds very interesting, usually these icons are in inhabitant areas so we could have it displayed.

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/8b13a24c7ebeda60406a066ce1b803e550172b08

**Comment by aceman444** [comment]
Thanks! Will this be in 2.5?

**Comment by xmd5a2** [comment]
@aceman444 yes
