### ISSUE TITLE
resource leak: database cursor not closed

### ISSUE THREAD

**Issue by andrew659** [osmandapp/Osmand#3135]
Dear developers,

I was learning and analyzing your code, which is great. I found one potential issue in the following file:

https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/helpers/GpxImportHelper.java

```
private String getNameFromContentUri(Uri contentUri) {
    final String name;
    final Cursor returnCursor = application.getContentResolver().query(contentUri, null, null, null, null);
    if (returnCursor != null && returnCursor.moveToFirst()) {
        name = returnCursor.getString(returnCursor.getColumnIndex(OpenableColumns.DISPLAY_NAME));
        returnCursor.close();
    } else {
        name = null;
    }
    return name;
}
```

In the above code, returnCursor may not be closed when moveToFirst returns false (meaning an empty cursor). I think even empty cursors need to be closed properly. Thanks.

**Comment by osMatt** [comment]
This should have been fixed by merging the pull request and should be closed.
