### ISSUE TITLE
Additional POI icons missing

### ISSUE THREAD

**Issue by RealRancor** [osmandapp/Osmand#3137]
Hi,

i'm not sure how to interpret the comment in https://github.com/osmandapp/Osmand/issues/3001#issuecomment-243227828 (should such missing POI icons are reported here or not?) so hope its ok to post that here.

Using osmand 2.4.7 it seems the following POI search icons are missing which are used on openstreemap.org with an own icon:

- office:therapist
- craft:photographer
- craft:metal_construction
- shop:deli
- sport:equestrian
- club:chess
- shop:massage -> Newly added in scope of this issue

**Comment by AndreasTUHU** [comment]
natural:rock POI icon is missing also:
https://wiki.openstreetmap.org/wiki/Tag:natural%3Drock

Osmand 2.4.0#18687M

**Comment by xmd5a2** [comment]
craft=winery, landuse=plant_nursery, man_made=works in fact fully supported.
Added rendering of point natural=rock with natural=stone icon.

**Comment by xmd5a2** [comment]
@RealRancor  Why did you decide that these icons are missing? Only missing icon is shop=deli because I cant imagine a simple recognisable icon for that shop

**Comment by RealRancor** [comment]
@xmd5a2 Steps to reproduce:

1. Tagging POIs with these tags on openstreetmap.org a few months ago
2. Checking openstreetmap.org and see that the icons exist on the map there
3. Downloading current osm maps in osmand
4. See that no icon exist for the mentioned POIs on the osmand map (even if the POI itself is there)

**Comment by xmd5a2** [comment]
@RealRancor please do not mix a)POI overlay and search icons and b) map icons. There are basically the same image files but not every POI is rendered on map directly using rendering style. Their appearance can be limited by zoom or frequency of occurrence or other methods of rendering are more appropriate (shaders, text).

**Comment by xmd5a2** [comment]
Added shop=massage to rendering. Craft tags are lower importance.

**Comment by RealRancor** [comment]
Hey, thanks for your reply, the update of shop=massage and sorry for mixing the POI overlay and search icons with the map icons.  If you don't have the knowledge about Osmand internals its not that obvious. :-/

> but adding all these craft=shoemaker, winery, brewery directly to map is very controversial issue.

I don't know the drawbacks of adding these so i can't say something about that. Just can tell from user side that the map icons (especially craft=) are quite useful when driving around with navigation. I'm not using the POI search that often and using the map itself to see interesting stuff around me.

Is there anything left here or should i close?

Thanks again for your reply and the clarification.
