### ISSUE TITLE
Additionals like "diesel" can't be found using new search

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#3139]

**Comment by onkarshinde** [comment]
Go to the POI search from dashboard. Just type diesel. You should see several options, one of them Diesel (Gas Station). Tap on it and it should bring up the fuels stations which have fuel:diesel tags.

**Comment by vshcherb** [comment]
I guess it is already fixed @xmd5a2

**Comment by xmd5a2** [comment]
No, it's not

**Comment by crimean** [comment]
Fixed - https://github.com/osmandapp/Osmand/commit/c5edcae2065e06f4f6edad7c7a6f379dcd59afae
