### ISSUE TITLE
[nautical] seamarks not visible in higher zoom levels in some areas

### ISSUE THREAD

**Issue by niendo1** [osmandapp/Osmand#3140]
Hi, 

I'm using OsmAnd +2.4.7 2016-09-19 and Android 6.0.1.

I activated the nautical plug-in and I'm using the nautical charts.

In the area of Mecklenburg-Vorpommern/germany (Germany_mecklenburg-vorpommern_europe.obf),
all the sea marks are only visible in some lower zoom levels .. if you zoom in they all disappear and don't come back.
There are three screen shots:
1. with low zoom: you can see all the watermarks
2. next zoom level: all watermarks/signs/harbours etc. disappear
3. details of one of the disappearing buoy

![screenshot_low_zoom_all_visible](https://cloud.githubusercontent.com/assets/22622265/19086067/f9d0f786-8a6c-11e6-8d79-a08c951c5c32.png)
![screenshot_next_zoom_level_no_water_mark_visible](https://cloud.githubusercontent.com/assets/22622265/19086077/02cfcaa6-8a6d-11e6-90aa-e32e231b16b5.png)
![screenshot_watermark_details](https://cloud.githubusercontent.com/assets/22622265/19086090/0f6ad710-8a6d-11e6-89c5-bfabb090ab1d.png)

This behaviour makes the use of  this nautical features in osmand in this area useless. As if you zoom in, you don't see any sea marks.

It seems all the sea marks in this area are effected. In other parts of Germany it works as expected.
But to be sure here is the XML-Dump of this buoy:
`<osm version="0.6" generator="CGImap 0.5.3 (6611 thorn-01.openstreetmap.org)" copyright="OpenStreetMap and contributors" attribution="http://www.openstreetmap.org/copyright" license="http://opendatacommons.org/licenses/odbl/1-0/"><node id="751574339" visible="true" version="2" changeset="8338303" timestamp="2011-06-04T11:40:57Z" user="malcolmh" uid="128186" lat="54.3395600" lon="13.6451000"><tag k="seamark:buoy_safe_water:colour" v="white;red"/><tag k="seamark:buoy_safe_water:shape" v="spherical"/><tag k="seamark:light:colour" v="white"/><tag k="seamark:type" v="buoy_safe_water"/></node></osm>`

Thanks for having a look...
Peter

**Comment by xmd5a2** [comment]
Can't reproduce. Here is my screenshot of that area
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot_2016-10-10-21-31-45.png
Try temporarily move (or archive) all maps except Germany_mecklenburg-vorpommern_europe.obf and World_basemap to check if there is any map interference. It is the only possible source of issue in my opinion.

**Comment by niendo1** [comment]
Hm, no osmand updates and no map updates, but I can confirm its working now.
Very strange, as for me it was never working before, even with different mobiles and different android versions. Maybe some out-of-memory problems?

But now it is OK...so I'm closing this issue...

Thanks...
