### ISSUE TITLE
ref:colour tag not shown properly

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#3141]
OsmAnd 2.4.0#14642D on BQ 5.7 (Android)
offline map (Spain - October map)

Therea are some roads with ref:colour tag in openstreetmap not shown properly. The most roads are shown properly but not all of them.

Some examples (all examples has ref:colour tag in Openstreetmap):
https://www.openstreetmap.org/#map=18/40.47225/-3.89363
https://www.openstreetmap.org/#map=17/40.41849/-3.82647
https://www.openstreetmap.org/#map=18/40.47427/-3.74140
https://www.openstreetmap.org/#map=17/40.71842/-3.97047

**Comment by xmd5a2** [comment]
@vshcherb Проблема в следующем. Есть highway, входящий в отношение route=road. Если тег ref:colour прописан на самой дороге (не на отношении), то в тег road_ref:colour_*=* ничего не попадает. Если удалить отношение то ref:colour корректно берётся с highway. Если добавить ref:colour в отношение то он тоже корректно работает. Проблема в комбинации highway+ref:colour+(отношение route_road без ref:colour). Не смог починить.
osm для теста: https://dl.dropboxusercontent.com/u/4624786/osm/spain_road_test.osm

**Comment by vshcherb** [comment]
Fixed

**Comment by OpenSourceForEver** [comment]
It is not fixed.  Osmand 2.5.0#15273D
Offline maps November. OSM Live

**Comment by sonora** [comment]
User claims it is not fixed (have not checked myself).

**Comment by OpenSourceForEver** [comment]
Fixed with new december maps (sorry).

Thank you.
