### ISSUE TITLE
Too prolonged mute between .ogg files (recorded voice prompts)

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#3142]
OsmAnd 2.4.0#14642D on BQ 5.7 (Android)
offline map (Spain - October map)
Voice prompts (Recorded) English (Aug 18, 2016)

Recorded voice (all languajes) has a too prolonged mute between .ogg files. For example:
Test voice prompts (en) 3.1 After (prolonged mute) 1520m (prolonged mute) turn slightly left

**Comment by sonora** [comment]
I have researched this but find no way to improve the situation. TTS is preferred anyway, there is no such issue.
