### ISSUE TITLE
Offer downloads for largest cities

### ISSUE THREAD

**Issue by PanderMusubi** [osmandapp/Osmand#3144]
For many countries, one can download the details maps for the entire country or regions or major roads only versions. However, it is not possible to download only large cities. For certain tourists and business people (which sometimes have no idea in which region a certain city resides) it is easier to offer downloads for only the largest cities.

Recently I helped a Spanish speaking person to find the map for Amsterdam, but even I had no idea that in the Spanish app you have to download Holanda Septentrional (which is apparently Noord-Holland) for Amsterdam.

In order not to offer too many downloads, for countries such as Netherlands, I would like to request detailed downloads for:
1. Amsterdam
2. The Hague
3. Rotterdam
4. Utrecht
5. Maastricht

and for Belgium:
1. Brussels
2. Antwerpen
3. Ghent
4. Bruges
5. Leuven

(Selection criteria used are size in area, inhabitants, popularity and geopolitical importance.)

Benefit for users is to with more ease find the map of the city they are in. Also when city hopping or doing business in certain cities, the space needed for those maps is considerable less than for using entire countries.

**Comment by vshcherb** [comment]
I agree with that proposal but we need to deal with it carefully cause it is good to start with though it has problems with navigation and other features if you decide to use application for a wider reason.

So for a city trip it is more than enough but it definitely not good for navigation planning

**Comment by PanderMusubi** [comment]
Intermap navigation should work or be failsafe.

**Comment by sonora** [comment]
I think I vote against this. It complicates support and debugging, and the benefit is limited. Countries with weaker Internet infrastructure usually also have smaller OSM file sizes to deal with, so there is no pronounced benefit there either.
