### ISSUE TITLE
New Search option, please add MultiSelect Poi as in other situations

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#3147]
The new Search option becomes better and better !
Thank you.
Please add MultiSelect for the POIs as in other search:
![multiselectpois](https://cloud.githubusercontent.com/assets/18628183/19148420/f0ce8134-8bbc-11e6-91f6-a308eae8b24a.png)
- globe symbol (top left corner)
- POI
- multi select (lower left corner)

**Comment by sonora** [comment]
Do you realize you can do this via creating a custom filter? This should be sufficient?
