### ISSUE TITLE
[Feature Request] Time to destination/next waypoint widgets

### ISSUE THREAD

**Issue by YuppieScum** [osmandapp/Osmand#3148]
Simply stated, I would like a navigation widget to show the time **to** a destination, as this would be more useful (to me anyway) than the arrival time **at** a destination.

**Comment by polarbearing** [comment]
Touching the ETA widget toggles between ETA and time to travel.

**Comment by YuppieScum** [comment]
Aha - I didn't know that.

Many thanks.
