### ISSUE TITLE
[Feature Request] Plug-in to show route weather

### ISSUE THREAD

**Issue by YuppieScum** [osmandapp/Osmand#3150]
When planning a trip of many hours/hundreds of miles, it would be immensely helpful to have an overlay of the expected weather conditions on the route for the time one will reach them, especially if one could set a departure time.

Knowing that by leaving 30 minutes earlier or later on a journey one could miss a thunderstorm (or example) would, I feel, be of great benefit.

**Comment by polarbearing** [comment]
It is unlikely to find a data provider who can give forecasts at which minute when a thunderstorm hits a particular road segment. Without such precise forecast, the proposed plugin would not be feasible.

**Comment by sonora** [comment]
Looks like no action planned here for now.
