### ISSUE TITLE
Missing information by POI search

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#3151]
When I use a search with **Nearest POI** I get for this POI only ONE result with 
restaurant. 
If I open the POI I see the information for restaurant, **but I don't see that this POI is also a hotel.**
In older versions I got ZWO results, one for restaurant and one for hotel.
The second screenshot (hotel) I got when using search for hotel.
In both views (screenshots) I should see Information about hotel AND restaurant !

amenity=restaurant
building=yes
cuisine=regional
name=Ferme Auberge Soultzersmatt
phone=+33 3 89 77 25 75
source=survey
tourism=hotel

![soultzersmatt restaurant](https://cloud.githubusercontent.com/assets/18628183/19151685/57a150e2-8bce-11e6-83ec-31058b144e61.png)
![soultzersmatt hotel](https://cloud.githubusercontent.com/assets/18628183/19151686/5b64b692-8bce-11e6-956b-74e2d7f9a45e.png)

**Comment by hakuchi** [comment]
you should not use amenity=restaurant and tourism=hotel on the same point or way.
If the restaurant is not only for the hotel user you should add a additional POI to the OSM database.
http://wiki.openstreetmap.org/wiki/One_feature,_one_OSM_element
It the restaurant is only for the hotel guests, you should delete the amenity=restaurant from this POI.

**Comment by pebogufi** [comment]
This is not correct. 
In most of this situations (or at least a lot of them) the tagging is on a building in which is a hotel with restaurant, and the restaurant is not restricted to guests of the hotel.
The tagging as described above is very commonly used and conform to the "one feature" description.

**Comment by hakuchi** [comment]
tourism=hotel: you can eat(breakfast, lunch, dinner) and sleep.
amenity=restaurant: you can eat    
So if the hotel have a restaurant not only for guest, this is a "additional feature" to the hotel.

**Comment by vshcherb** [comment]
The fix need to be double checked.
