### ISSUE TITLE
zoo overlapping landuse

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/Osmand#3152]
sometimes tourism=zoo covers landuse and sometimes the landuse covers the zoo.

Examples:
zoo covers landuse
![zoo](http://fs5.directupload.net/images/user/161006/flt7b2hw.jpg)

landuse covers zoo
![landuse](http://fs5.directupload.net/images/user/161006/wmurzwts.jpg)

can we make the zoo transparent like the nature_reserve
![nr](http://fs5.directupload.net/images/user/161006/nuvl3mtt.jpg)

**Comment by xmd5a2** [comment]
Fixed  https://github.com/osmandapp/OsmAnd-resources/commit/707dfbbe12a4fdc0e587d35e6ee0fc0fa795a44e
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot%20from%202016-10-10%2019%3A42%3A47.png

**Comment by hakuchi** [comment]
in new renderer the problem is again present in OsmAnd
