### ISSUE TITLE
Wikipedia articles with spaces linked incorrectly

### ISSUE THREAD

**Issue by IByte** [osmandapp/Osmand#3153]
If POIs have Wikipedia tags, but the article name contains spaces (which is of course common on Wikipedia), the hyperlink is not generated correctly; it stops at the first space. See screenshot.

Using OsmAnd 2.4.7 released 2016-09-19 running on Android 5.1.1 on a Samsung SM-G800F (Galaxy S5 mini). Using offline maps for Gelderland, Netherlands, compiled 2016-10-01.

![2016-10-06 11 19 46](https://cloud.githubusercontent.com/assets/708282/19173572/720c6160-8c28-11e6-9d94-5ffc1a453fd9.png)

(This issue was previously [posted to the OsmAnd forum](https://groups.google.com/forum/#!topic/osmand/Hyptbo3PCOM) )

**Comment by osMatt** [comment]
I think this issue is already fixed (but has not made its way into a released version yet): #3078
