### ISSUE TITLE
rest_area covers parking/landuse

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/Osmand#3154]
highway=rest_area covers amenity=parking and landuse

Examples:
http://www.openstreetmap.org/#map=17/48.41052/10.64275
![parking](http://fs5.directupload.net/images/user/161007/ss7dcz7s.jpg)

http://www.openstreetmap.org/way/327727975
![landuse](http://fs5.directupload.net/images/user/161007/9va7e3o4.jpg)

it should be like highway=services
http://www.openstreetmap.org/#map=18/47.83650/13.39576
![services](http://fs5.directupload.net/images/user/161007/e9iffmzh.jpg)

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/b43cee4105b934b604b8a6f0b8c60b9eb0d01973
