### ISSUE TITLE
Unnamed surveillance not searchable

### ISSUE THREAD

**Issue by yoptesui** [osmandapp/Osmand#3155]
Searching for surveillance only prints named features. The vast majority of man_made=surveillance is unnamed and thus is invisible.

Using latest OsmAnd stable and recent data.

**Comment by xmd5a2** [comment]
@yoptesui I disabled it because there are areas with huge density of these cameras and they can interfere with other more useful POIs when "Nearest POI" filter is used. Why do you need to search surveillance?

**Comment by yoptesui** [comment]
Usefulness is subjective. I thought OsmAnd displays all mapped features.

I can understand if you need to discriminate in a general view, but why even have an entry for surveillance if they aren't shown? It misleads users into thinking their are fewer mapped features than there are.

**Comment by xmd5a2** [comment]
> why even have an option for surveillance if they aren't shown?
Because most important objects are usually named and they can be searched in OsmAnd.
> Are other tags censored in this way?
Yes. Search name_only="true" in https://github.com/osmandapp/OsmAnd-resources/blob/master/poi/poi_types.xml

**Comment by vshcherb** [comment]
OsmAnd is not an editing tool in case it is used like that then all map features need to be indexed with all descriptions which makes the map bigger. It is possible to do with OsmAndMapCreator and custom rendering_style and custom poi_types without modifying any line of code

**Comment by sonora** [comment]
No action planned, it seems.

**Comment by scaidermern** [comment]
Is this decision still up to date? Currently the _surveillance_ category doesn't display surveillance features (such as cameras) that don't have a name. Consequently 99% of surveillance cameras are not shown. Is this the intended behavior?

**Comment by vshcherb** [comment]
Yes it intended behavior, for several POI types we display POI's only with names to avoid search clutter. Same applies to very frequent objects such as trees and so on. They are still displayable and stored on the map but not in the POI structure

**Comment by leethax666** [comment]
can confirm on latest. really annoying for privacy advocates.

**Comment by Percherie** [comment]
Good evening,

It induces errors, thinking that there was no camera in my city, I added them several times with OsmAnd and it created duplicates a little bit everywhere.

Without displaying them when searching for all the POIs nearby, being able to see the node symbol when you're nearby would avoid this kind of error.

Moreover the goal is to be able to see during my walks if everything is well added on OSM.

Is it possible to have them displayed soon? Even if, in reality, no name or reference is written at the foot of the cameras.

Translated with www.DeepL.com/Translator (free version)
