### ISSUE TITLE
GPX track recording: Motion detection / minimum velocity / minimum position change

### ISSUE THREAD

**Issue by bonanza123** [osmandapp/Osmand#3158]
I'm often recoding GPX tracks, e.g. while hiking, and make every now and then a pause of a couple of minutes. Osmand keeps recording the GPX points every X seconds. Depending on how long the pause is, there are a lot of GPX points around my static position which increase the total length and altitude of the track I hiked, although I was just making a pause.
I have seen in several apps that they have some kind of motion detection to prevent this. E.g. they just save a GPX point if my velocity is greater than X or my position with respect to the previous point has changed by Y.

**Comment by bjohas** [comment]
GPSLogger is one such (free) app and can filter by position change and many other features.

**Comment by vshcherb** [comment]
UI settings are added for 3 dimensions: min distance, min speed and precision. Default values for different profiles could be justified.

**Comment by sonora** [comment]
As I have stated elsewhere (#3200), all that is needed here is a simple **motion detection check**, which is best achieved via the primary GPS output (horizontal position), i.e. a **displacement filter of x meters vs. the last recorded point.**

Triggers for secondary GPS output parameters like speed or hdop are not needed and may have undesired side effects the users are not aware of, which may accidentally cripple their recordings.
