### ISSUE TITLE
KML import broken

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#3161]
Trying to import a KML file ends with with an error message importing a GPX file. No POIs are imported. I have tried different files from public Google Maps.

(Works fine with MAPS.ME. MAPS.ME puts all POIs from one KML file successfully into a common group.)

Found with OsmAnd+ 2.4.7. (I think older builds are affected by this bug too.)

**Comment by vshcherb** [comment]
Please attach the file here.

**Comment by Norbert80** [comment]
[Berlin.kml.zip](https://github.com/osmandapp/Osmand/files/519759/Berlin.kml.zip)

One of many examples. I had to archive it into a ZIP file because of Github limitations. The problem happens with any Google Maps generated KML file.

**Comment by Norbert80** [comment]
@vshcherb KML support ist still broken in DomAnd+ 2.5.

**Comment by vshcherb** [comment]
The issue is still open.

**Comment by Norbert80** [comment]
Fix confirmed for OsmAnd+ 2.5.1. Thanks!
