### ISSUE TITLE
[Feature request] Build routes inside areas with private access by request.

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#3164]
In some countries, for example, Philipines, there are many city districts with private areas tagged as allowed access - private. Inside those areas, the routes are not built, though they can include several streets. Thus, users cannot get to their destinations. Request: allow building routes inside such areas by user decision.

Example: Vista Granda Subdevision http://www.openstreetmap.org/way/418063718 cannot be entered from Cebu South Road.

**Comment by aceman444** [comment]
I thought OsmAnd allows routing into private roads (with low priority), if there is no better option.

**Comment by annasoloviova** [comment]
No, it completely avoids private roads. At least, on Philipines.

**Comment by sonora** [comment]
Must be some other issue, maybe a barrier issue? We have fixed the following a long time ago and I just verified it again: Routing both to and from destinations in street mesh tagged as access=private seems to work ok. I tried different big employee parking lots in the US, though.

**Comment by vshcherb** [comment]
That's slight different request, we need to prompt user that there the end of the road is in the private location and after that still build a road via it. Today we build to the closest reachable point but on the big areas it is unreachable. 
If I'm not mistaken...

**Comment by vshcherb** [comment]
Hm... according to this line https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#L305, the original issue is fixed.

**Comment by vshcherb** [comment]
@xmd5a2  could you please double check that area.
