### ISSUE TITLE
Voice guidance on Samsung Android Phone fails sometimes

### ISSUE THREAD

**Issue by noci2012** [osmandapp/Osmand#3169]
Some extra info to enlight this a bit.....
This is an issue on OsmAnd 2.4.7 on a Galaxy S5 mini 5.1.1 where Samsung chose to create their OWN crippled TTS engine that doesn't have a dutch voice. SVOX just crashes the system (soft reboot) choosing the Google engine actually works. 
The phone has a German G800FXXU1BPC3 Native image(Grey import probably by a dutch webshop) , but has dutch language settings just tts for at least  Osmand doesn't work. 
The beeps that prompt a announcements are heard but no text.
After selecting the Google TTS engine a dutch voice can be heard, so checking if the manufacturer of the phone screws you might help.

On testing settings: How about an option Test TTS setting that pronounces a sentence on command, no automatic greeting.

**Comment by polarbearing** [comment]
TTS testing is already implemented, go to 
Settings -> OsmAnd development (at the bottom) -> Test voice prompts. Here you can select a language from installed the TTS config files, and play all announcements.

**Comment by sonora** [comment]
Yes, please use the test buttons and try to find some rules of what does and does not work. Please report the button numbers I have inttoduced some time ago, it will make debugging this easier. Chances are, however, this cannot really be fixed in OsmAnd.
