### ISSUE TITLE
Allow user to tap on the header to toggle between current road and upcoming road

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#3170]
Currently, OsmAnd shows the name of the current road (with blue UpArrow). When a junction comes near, it shows the next road (with appropriate curve). At this time it stops showing the current road's name. So if the driver was not paying attention, he cannot know the current road's name any more.

To solve this, allow the driver to tap on the header. OsmAnd should toggle between the current road and next road. 

The icon shows clearly which is the current road and which is the next road. So there won't be any confusion.

**Comment by sonora** [comment]
Not planned, I guess.
