### ISSUE TITLE
New search gives emphasis to first word / buildings, not exact match

### ISSUE THREAD

**Issue by bjohas** [osmandapp/Osmand#3171]
E.g. searching for "Liberty State Park" (map centred in New York) gives pages and pages of partial matches ("liberty"), some 100s/1000s km away, before the exact match "Liberty State Park" occurs.

It may be that the search gives emphasis to the first word, or lists buildings first, before listing anything else?

**Comment by bjohas** [comment]
(version 4802)

**Comment by raindropsfromsky** [comment]
I have reported this earlier. (#3086)

**Comment by vshcherb** [comment]
This is a known issue, first of all it is an incremental search and second we are not sure in OSM data yet, in many cases people use shorten words or parts of the name i.e. "Liberty park". We might split search in 2 groups "exact" and "autosuggestion" though we could solve this in future

**Comment by sonora** [comment]
In a way this is also related to #3062: Today, a hierachical address search, which should be the fastest way to search for an address, has become very slow: User types the name of a village, and may have to wait for more than one minute before getting the result, and then the actual village result itself (the exact-match result) willl be obscured in the potentially long list of streets and other search results related to the village.

**Comment by sonora** [comment]
Let us merge this to #3086.
