### ISSUE TITLE
Street disappearing at higher zoom levels + POI missing in some zoom levels

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#3172]
I am seeing a strange issue here.
With a map created today (with the latest mapcreator) and the latest osmand (version `2.4.0#14847D`), at [-21.7849752, -48.1877383](https://www.openstreetmap.org/#map=18/-21.78498/-48.18774)

At zoom level 16 it's OK:
![](https://cloud.githubusercontent.com/assets/982338/19399596/b6731ab4-9228-11e6-840c-70e3e9e558a4.png)

At 17 the restaurant disappears (but we can see the housenumber); I guess this is also OK:
![](https://cloud.githubusercontent.com/assets/982338/19399611/c24065ae-9228-11e6-9e74-42c16a009a9b.png)

At 18 we can't see the restaurant nor the housenumber:
![](https://cloud.githubusercontent.com/assets/982338/19399616/c9d42030-9228-11e6-905d-897649693f99.png)

And at 19 we can see the restaurant back, but note that the street above the park disappears:
![](https://cloud.githubusercontent.com/assets/982338/19399622/cd7b0b72-9228-11e6-83f5-34c9d3b0356f.png)

**Comment by vshcherb** [comment]
In theory even restaurant should not disappear on 17th level

**Comment by naoliv** [comment]
I can't reproduce it anymore with a newer osmand and newer maps too.
I will reopen if I see this problem again.
