### ISSUE TITLE
Configure Map > Transport > Station Entrances

### ISSUE THREAD

**Issue by bjohas** [osmandapp/Osmand#3173]
Under "Configure Map > Transport", add an item "Station Entrances". 

The current options allow you to see transport stops. However, for railway (especially underground), the station entrances can be some way from the transport stops. It would thus be helpful to have the option to show "station entrances" (railway=subway_entrance) as well.

**Comment by vshcherb** [comment]
We have them displayed on the map itself, though they are not poi objects.

**Comment by vshcherb** [comment]
CC @xmd5a2

**Comment by xmd5a2** [comment]
They are POI objects and can be easily found

**Comment by bjohas** [comment]
Sure! I was just thinking of those in analogy with the transport stops themselves, which can be labeled through the transport menu. (Btw. the transport menu is great!) For some of the large underground stations, the entrances are quite spread out, so it may be useful to separately label them as well.

**Comment by sonora** [comment]
No immediate action planned.
