### ISSUE TITLE
Checkboxes not working in Accessibility plugin menu

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#3175]
In Plugins - Accessibility - Settings, you cannot check any box. Or does this require the accessibility feature to be turned on on the phone first?
![rsz_checkboxes](https://cloud.githubusercontent.com/assets/12711814/19410011/df84d82c-92e9-11e6-8474-13e222984a2c.jpg)

**Comment by vshcherb** [comment]
Accessibility settings should be enabled in Android first.
