### ISSUE TITLE
Traffic jams layer

### ISSUE THREAD

**Issue by Paviluf** [osmandapp/Osmand#3176]
I contacted opentraffic.io (https://github.com/osmandapp/Osmand/issues/1432) to ask them if we can use freely their data and this is their answer
> Alyssa Wright, Oct 14, 13:52 PDT
> 
> Hello Jeremy,
> 
> Thank you for contacting us at OpenTraffic headquarters. We appreciate your traffic interest. We are currently locked in the basement preparing a large scale unveiling of the platform. Once released you will be able to freely use the traffic data!
> 
> We recommend joining our newsletter to follow our progress and stay involved: http://eepurl.com/cg7Ncb
> 
> Kind regards,
> The OpenTraffic Team.

**Comment by vshcherb** [comment]
reopened #1432
