### ISSUE TITLE
Speed limit missing in one direction when maxspeed:backward and maxspeed:forward tags are also present

### ISSUE THREAD

**Issue by AndreasTUHU** [osmandapp/Osmand#3178]
OsmAnd~2.4.0#18786M, offline router, car mode, map: Hungary 2016.10
Samsung Galaxy S5 Android 6.0.1 (stock Android version), 

Simulate a route between 
https://www.openstreetmap.org/#map=18/47.2016595/18.4047794
and
https://www.openstreetmap.org/#map=18/47.20391/18.40643

When simulation reaches this way segment the speed limit disappears:
https://www.openstreetmap.org/way/428535513

Travelling same route in opposite direction the speed limit is working.

**Comment by vshcherb** [comment]
@sonora  could you please and possibly share more details if it is related to the road direction feature . Please let me know if I can review some code as well.

**Comment by sonora** [comment]
Code is here https://github.com/osmandapp/Osmand/blob/b2f158c97d4c2431e2d360964b0bf7d05dc905e1/OsmAnd-java/src/net/osmand/binary/RouteDataObject.java#L257 plus dependencies. Needs a deeper look.

**Comment by sonora** [comment]
@vshcherb : Unless I am mistaken, this should fix it? https://github.com/osmandapp/Osmand/commit/b7252dead7e61f8b45075869d22fbece117c8335

**Comment by AndreasTUHU** [comment]
@sonora : It is working now, thanks for fixing!

By the way..  during testing I realized that 'Directions from' and 'Search near here' functions not working anymore. Nothing happens after touching. Should I open a new issue?

<img width="135" alt="screenshot_2016-10-25-15-21-47" src="https://cloud.githubusercontent.com/assets/14630009/19687876/93158b90-9ac7-11e6-9869-68da62635ec6.png">
