### ISSUE TITLE
Create option to show/hide the "+" and "-" buttons via "configure screen" (like "compass", map orientation)

### ISSUE THREAD

**Issue by bjohas** [osmandapp/Osmand#3179]
Recently an option was added to show/hide the compass (map orientation) button. Now that the tap-drag zoon works really well, it would be great to have show/hide for the "+" and "-" buttons as well.

**Comment by vshcherb** [comment]
No objection, though it will create unbalanced UI more buttons on the left side than on right.

**Comment by sonora** [comment]
Should be viewed in the context of #2551.
