### ISSUE TITLE
TTS-PT needs correction/reordering

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#3180]
When arriving at a highway exit, we now have three warnings as we aproach, two with destination, and one just before the exit itself.

1 - turning right after X meters, to 'ref',  'destination' (bad, misleading)
2 - after X meters, turn right, to 'ref', 'destination' (good)
3 - turn right to 'ref' (good)

In TTS-PT voice guidance, the first warning is misleading, because it first says to turn right (not yet, it misleads), and only after it says the distance to the turn.
It should first say the distance, and then the turn indication, like it says on warning number 2.

**Comment by sonora** [comment]
I can fix next week. Can you please state one example each in Portuguese how it should sound?
In English, we have actually settled to use'after' for the far and 'in' for the closer announcement, I guess the task is to find equivalent wording for pt.

**Comment by Barrocas** [comment]
Thanks.
The words are not that important here, but the ordering is.

The second warning is fine.
You can copy it, and 'paste' it on the first warning.

If you prefer to use different words for each warning, in PT the 'after'
can be 'depois de', and the 'in' could be 'após' (as it is now).

But if the wording 'após' is used on both the first and second warnings, it
would be fine too, no problem, since they have similar meanings.

**Comment by sonora** [comment]
Ok, I have made the change as I understand it in both European and Brazilian Portuguese. I have also made it for the roundabout and U-turn pre-announcements.

Could you please test all these  (latest nightly) and report if it is ok now. Thx!

**Comment by Barrocas** [comment]
It's working much better, thanks! :)
