### ISSUE TITLE
Visualize that public transport lines in a stops's context menu are tappable

### ISSUE THREAD

**Issue by bjohas** [osmandapp/OsmAnd#3182]
The ability to show the railway line run via the tray (i.e. pulling up the tray and then clicking on the line) is great. Also, when you view the line, the stops appear in the tray - that's excellent! Whoever implemented this: Well done!

It would be great if that feature could be highlighted. Similar to https://github.com/osmandapp/Osmand/issues/2909 it's not obvious that this is possible, i.e. that the line items in the tray are clickable (other items aren't clickable). 

I don't have a good suggestion for drawing attention to this though. I'd be happy to write some documentation on such public transport features. Or perhaps some contextual information could be added somewhere on first use?

**Comment by sonora** [comment]
We could maybe visualize each line by a button, similar to how we now display the "Nearby Wikipedia articles".

**Comment by Chumva** [comment]
It is possible to select public transport lines in the context menu

<img src="https://user-images.githubusercontent.com/19220417/178827642-86cf3d65-a11a-45f1-8c72-004e99aa6c9e.png" width="330" height="700">
