### ISSUE TITLE
Looking for address when geo: link is opened

### ISSUE THREAD

**Issue by jkufner** [osmandapp/Osmand#3184]
Today nightly build and few older builds (I'm not sure how long it is) just looks for address without going to coordinates specified in geo: link instantly. And the searching for address takes a very long time.

To reproduce click [geo:50.08,14.4](geo:50.08,14.4) or scan following QR code and open the location on map.

![qrgeo](https://cloud.githubusercontent.com/assets/16572/19514266/350e4fb0-95f3-11e6-979e-ae1db698bcaa.png)

When Osmand is already started (it is running on background and is in the recent apps list), it wont find the address. If Osmand is stopped (swiped away from the list of recent apps), it will find the address as expected (but not always).

**Comment by crimean** [comment]
Looks like it is fixed already
