### ISSUE TITLE
Issues with GPS config items interoperation

### ISSUE THREAD

**Issue by ohhai** [osmandapp/Osmand#3185]
All the following is about GPS trip recording plugin, I think.

The case: I want to enable background GPS trip recording with some interval.
Have two alternative flows:

1)
a) Configure 5 or 30 sec GPS wakeup interval by the satellite button in top right corner. Not to be confused with general logging interval in plugin's settings.
b) Start track recording by another button in top right corner.
c) Check GPS wakeup interval: it switched to continuous unexpectedly.

2)
a) Start track recording by the button in top right corner.
b) Have to stop background mode (satellite button in top right corner) and then restart with 5 or 30 sec wakeup interval. There is no possibility to just change the interval without restart.
c) Background logging is stopped unexpectedly. The stopped status is shown only in OSMAnd notification (not on OSMAnd screen).
At the same time track recording is active and wakeup interval shown as properly configured, so the status in notification could be easily missed.

Expected behaviour for all of that follows. If there are some internal reasons, it's good to have them documented at the plugin's help page. For now it gives only simple and obvious instructions.
- Starting track recording should not unobviously reset wakeup interval. Merge these two dialogs, maybe?
- It's better to have a possibility of changing wakeup interval on the fly, without restart. Not very important, though.
- Changing wakeup interval (by restarting for now) should not stop background service.
- Three mandatory interface controls (two main screen buttons and one notification button) is too much and hard to understand. There is also some intervals in plugin's settings in addition...

To be more clear, I'm a fan of huge number of settings while they are easy enough to understand and operate.

Related ticket: https://github.com/osmandapp/Osmand/issues/1903

Unrelated:
I see that general logging interval has an influence on the wakeup interval (default value, at least).
Does it work in another direction? I mean, setting some value for wakeup interval affects logging interval or not?
It should affect (and be obvious), as for me, since some of the updates (either GPS fix or track file) are useless otherwise.

SW versions: osmand+ 2.4.7, samsung S5 @ android 6.0.1

**Comment by ohhai** [comment]
Just in case: influence of logging interval on wakeup interval is the reason why I can't set update interval smaller than 30s, as far as I understand. If you think it has no sense because of no effect on powersaving (as described in #1903), please make the reason more clear. I'd just make 30s the smallest possible interval, maybe.
For now it's quite frustrating constantly falling back on "continous".

**Comment by sonora** [comment]
If you are using the latest nightlies, there is a possible cross reference here to #3200. this is work in progress.

Should you report for any build older than say 2 weeks, here is the behavior, and I believe it to have no bugs, as I have used it for years, and no changes were made (unto recently):

(1) To log a track, do not use the GPS status widget, instead use the GPS trip recording widget. It will pop up a dialog asking at what interval you want points to be logged. **This is the master parameter**. The GPS wakeup interval is adjusted automatically to fit the needs of the app (all functions not just logging) and to save battery power. It depends on circumstances as follows:
- GPS logging interval <=15sec: Continuous. It makes no sense here to switch GPS off at all, it only degrades the track quality
- GPS logging interval >=30sec: The GPS wakeup interval is taken accordingly, i.e. GPS is mostly off. On my backcountry trips I usually get 24+hours of logging with interval set to 30 sec or 1 min with one battery charge, this works great.
- Please note that other factors change the GPS wakeup interval, like a navigation will need to adjust it to "continuous"! So the GPS wakeup interval is a parameter in the background, I guess we should maybe not even make it user-accessible, it is a possible course of confusion and misconfiguration (as your question shows :) ).

Any re-adjustments should be made to the logging interval, not to the wakeup time, if you ask me.  Please state if you concur.  Thx - Hardy

**Comment by sonora** [comment]
Fixed. All interaction is now fully automatic, and solely controlled via the services you use (trip recording, navigation).

**Comment by ohhai** [comment]
(Ok, I am late, but anyway)
Using v2.4.7+ as mentioned (release from google play), so that latest changes should be absent for my case.
I can believe that this behaviour was stable for years, but it's still very confusing ;)

Using trip recording widget (circles labeled "GPX") does not pop up anything for me, it just starts logging. Might be related with the fact that I already set an interval in plugin's settings.
Then you describe a good flow, but I have a question for it: what sense is given to exposing wakeup interval if it's controlled by logging interval so smartly?

Again, I always support huge number of options and even after reading #3200 it doesn't seem a problem--there is a good common approach with separating not-very-important settings into an "advanced" section hidden by default. But again, they should be easy to understand the correct usage.
So, I'd vote for asking for a single interval while activating track recording (with "notagain" checkbox, maybe; or adding long-press...). If the separate wakeup interval has some practical usage, then keep it in plugin's settings or another place with second-level parameters.
And please explain something on the help page. Even with copying there the most of your post above.

**Comment by vshcherb** [comment]
I agree we need to move setting about how often to record GPS in settings and setup default values. Actually "continuously" has another meaning "as often as possible". I think sooner or later we will get rid of this dialog and we have other issues which will cover it.
