### ISSUE TITLE
Search is slow when GPX track with GPX waypoints is active

### ISSUE THREAD

**Issue by littlehelper** [osmandapp/Osmand#3187]
Searching GPX waypoints from active GPX tracks is already implemented. Great :)

But, in my case, activating a GPX track containing waypoints slows down the whole (new) search significantly. It takes up to 20 seconds until the first matching POI category, POI or GPX waypoint is listed.
Deactivating all corresponding GPX tracks restores the original search performance which is realy good.

Greetings

**Comment by vshcherb** [comment]
Is it possible to share GPX or share some numbers, how many waypoints are present in GPX file

**Comment by littlehelper** [comment]
I attached my GPX file (had to append file extension .txt for upload) containing about 140 POIs.
[-Italy.gpx.txt](https://github.com/osmandapp/Osmand/files/542823/-Italy.gpx.txt)

As long as this GPX track is selected as active, searching for e.g. 'Sella' is very slow.

(The GPX file is the result of how I collect all possible interesting POIs and waypoints in a country I plan to visit in my upcomming hollidays :)

**Comment by crimean** [comment]
Temp fix by removing country name from results - https://github.com/osmandapp/Osmand/commit/b652687d3740387842f0daa5c5993defe7887161
