### ISSUE TITLE
Display information when POI search result is empty

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#3189]

**Comment by vshcherb** [comment]
https://www.dropbox.com/s/9osa1qpq9890zu6/Empty-state.png?dl=0

**Comment by sonora** [comment]
Also: Should we reintroduce to automatically increasing the search radius if there are no hits?

We do not display the radius any more, so it seems awkward to a user to see an empty results list indicating nothing can be found, but then a button saying "Find more"?

**Comment by vshcherb** [comment]
This story has lots of debate, main purpose is to show more information to the user, so he understand whether he need to click button "find more" or it is enough. So let's say the radius is "500km" already and not found, for most of the cases it's enough to search. 

Automatically increasing radius could work only for POI List search but not for initial search where we search by name.

P.S.: does anybody knows good wording for word "radius" - "We've search 500km around you" sounds good?

**Comment by sonora** [comment]
Ok, understood.

Good wording could be "No hits within 500km", or probably more precise "No hits within a 500 km radius".

**Comment by breversa** [comment]
The word "hit" should be changed to something more understandable, like…
"result".

2016-11-06 17:39 GMT+01:00 Hardy <notifications@github.com>:

**Comment by sonora** [comment]
Yes, no prob!
