### ISSUE TITLE
HTTPS on website

### ISSUE THREAD

**Issue by rugk** [osmandapp/Osmand#3190]
Please use HTTPS on your website.

You can do this for free and in an automated way with https://letsencrypt.org/.

**Comment by arbie65** [comment]
This is important especially when you are asking for peoples OSM username and password over [unencrypted channels](http://osmand.net/osm_live).   You are leaving people open to having their openstreetmap accounts stolen

**Comment by vshcherb** [comment]
Yes, it is very important in that case. We will need to upgrade our infrastructure to support let's encrypt we still are busy of doing it.

**Comment by vshcherb** [comment]
Done https://osmand.net/osm_live
