### ISSUE TITLE
Contour lines on/off slider in configure map menu

### ISSUE THREAD

**Issue by littlehelper** [osmandapp/Osmand#3192]
In the configure map menu the sliders for quickly turning the display of favourites, POIs, map layers etc. on/off are very handy.
Please, also provide such an slider for the contour lines to enable displaying/hiding them quickly without the need to open the submenu or even change the options in the submenu.
(Please keep the submenu to select the minimum zoom level from which contour lines are displayed.)

**Comment by sonora** [comment]
Limited value-add, the submenu provides this functionality already.
