### ISSUE TITLE
Adjust brightness/contrast of raster maps

### ISSUE THREAD

**Issue by littlehelper** [osmandapp/Osmand#3193]
It is great that Osnand is capable of displaying raster maps like satellite images. But sometimes satellite photos or orthophotos are too dark due to e.g. mountain or cloud shadows.
Is it possible to adjust the display brightness and contrast of raster maps by e.g. introducing sliders in the corresponding configure map submenus to temporary adjust these settings or adding parameters to the raster map's .metainfo file for permanent adjustment?

**Comment by vshcherb** [comment]
There is transparency bar today, other image manipulation are not supported
