### ISSUE TITLE
Voice over bluetooth audio delay

### ISSUE THREAD

**Issue by HellSpawn754** [osmandapp/Osmand#3197]
Hi! I have experienced problems using 3 different car sterios with the bluetooth feature, "New Feature: Interrupt Car FM Radio or Car CD for Navigation Voice Prompts". The start of the message is always cut, so i think it would be necessary to let the user adjust the delaytime in 
OsmAnd/src/net/osmand/plus/voice/AbstractPrologCommandPlayer.java in line 310?

Greetings

**Comment by sonora** [comment]
Yes, possibly. May add this to our development settings when I find some time.

So far I have about 30 feedback items on the new feature, 28 say it mostly works ok as I have parameterized it now, 2 report similar issues you have. From what I see it is not 100% consistent, there are variations even in the same hardware configuration from occurrence to occurrence, maybe depending on other tasks the smartphone or car radio may be performing.

I guess I would like to understand that better before making a change here, as a static adjustment may not be the apt solution.

- Can you help investigate if the time cut off seems fairly constant, or variable? (Re-check the same voice prompts at different times)
- Is it very clearly associated with the connection of the mockup phone call, or does it also occur when that was already shown as connected. (For closely spaced consecutive announcements, where the phone call stays connected, does it strictly affect only the first one?)
You can also use the "Test voice prompts" buttons (activate the Development Plugin, then go to its Settings) to experiment and test this.
- Can you try different Android devices with the same car stereo, to check how it depends on this? 
Any additional data much appreciated!

**Comment by HellSpawn754** [comment]
Thanks for your effort!

-) The cut off is pretty constant, but not 100% constant. 
-) It doesn´t matter if it´s the first command after being connected.

I tried it with a Samsung Galaxy S3 (with cyanogen mod) and it connects and the radio switches to "call mode" but i can´t hear anything. (on different radios).

With a Samsung S4 (stock) works but with the cut off as mentioned. This is the same with different radios. Here is a video of me trying the "the trip is 150 meters. Time is 4 minutes". When is burst 2 commands at once the second command is not cut off: 
[Video](https://www.youtube.com/watch?v=1qY_wkRp6SY)

**Comment by sonora** [comment]
Ok, thanks!

I have made the parameter adjustable in the latest nightly. To change it, please enable the OsmAnd Development plugin, then in its settings go to "Test voice prompts", and tap button (11.2) to select between 1000ms / 1500ms (current default) / 2000ms / 2500ms.

I would expect the 2.0 or 2.5 sec setting should work for you?

**Comment by HellSpawn754** [comment]
Thanks, now it works!

**Comment by sonora** [comment]
Just for my statistics:, with which value? Thx - Hardy

**Comment by HellSpawn754** [comment]
2500ms.
2000ms is slightly too short

**Comment by MichalK6677** [comment]
It's not working for me. The start of the message is always cut. If I set delay to 3000ms then I hear 3000ms of silence and the same message with the cut. I can set whatever delay, tt just adds silence before the message with the cut.
