### ISSUE TITLE
Double-check conceptional issues of our enriched trip recording

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#3200]
Several issues worth checking here, let me first summarize what I think we were trying to achieve:

**(A)** The logging interval still strictly defines our **sampling rate** for when we log a point a all. (So this is our raster, not just another filter dimension.) Nothing happens between time-defined sampling points no matter what (and we even turn GPS off for sampling >=30sec to conserver power).

**(B)** Now we add an additional distance filter to check if at such a time-defined sampling point the position has a certain minimum distance from the last point logged, or else we discard it.

**(C)** We also add a speed filter to see if the point handed down from the GPS chipset has a certain (small) minimum velocity, or else we discard it. I assume what we really intend here is not really a low-speed cut-off, but rather checking if we are basically in motion, right?

**(D)** We also added a precision filter to discard points which do not fulfill a minimum quality criterion. (I guess what we really should try to achieve here is to make sure we always capture the best track which can reasonably be acquired under the given circumstances)

Here are the issues I think I observe:

**(1)** Logging is basically a device-global action and/or should be treated as such. Its parameters should not depend on the profile of some app. (It is not even clear what profile is used, because you can start logging from the notification bar now. Or you can change the OsmAnd profile after logging has started - very intransparent.)  I think we need to make all manual logging parameters global settings, and also ensure once again that whenever you start logging, the master sampling rate dialog is displayed (unless the user has set a default to not see that dialog again). I see the good intention in having profile-dependent defaults and settings, but think the complexity added kills the feature here. (And the settings are obsolete, see below).

**(2)** The distance filter was a much needed addition we now have. This is likely the only additional setting we should keep. Please note that in all reviews of our app we are criticized for being too complicated and cater for things not 1% of users use, but complicate things for 99% of the userbase. When balancing usability vs. features, we always seem to err on the "feature" side :)

**(3)** Speed filter: We really only want "motion detection", right? And even if you happen to stand at a stop light or have a short breathing break during a hike at the time the sampling is to happen (e.g. 5 minutes on backcountry expeditions), you probably wanted that point to be recorded once, rather than omitted? I think functionally there is 99% overlap with the distance filter here, where this is achieved much simpler. I vote for removing the speed filter, I see no use case. Using a low-speed cut-off for recording may produce side effects if you do not clearly understand our logic of how we sample and record, which again 99% of our users will not.

**(4)** Precision filter: Again: I guess most users would want to automatically record the best precision possible, but not filter any points on the basis of settings they do not understand (and their effect they cannot verify?) I vote for an automated solution like this: If a point fails a certain precision (say hdop>=6), lets immediately take 2 (or 4) more at a 1 second spacing, and record the best of the 3 (or 5). No settings needed.

Please note that our "Precision setting" is flawed conceptionally, hdop is **not** anything like precision in meters. hdop is a scale for reliability under given reception conditions, something 99% of our users will not be bothered with. (It is roughly like this: 1 = good, 6 = fair, >=10 = useless.)

**Comment by sonora** [comment]
PS: Wording suggestion for the only remaining new logging filter setting (after removing speed and precision filter) would be:

- "Logging motion detection" - "Minimum distance from last position for point to be logged".

**Comment by vshcherb** [comment]
The conversation was moved to another topic and I don't see here anything immediately actionable.

**Comment by vshcherb** [comment]
I guess for wording you could apply proposed change, it is always better to adjust initial wording

**Comment by sonora** [comment]
Ok, wording is changed to "Logging motion detection - Set minimum distance from last position for point to be logged".

I cannot help but summarize how I think we are doing a bad job here, the 2 outstanding issues are:

**(1)** Profile-dependent logging settings. Overly complex. It is unclear what settings are used (e.g. when you start logging in the Browse map mode?), and what happens (are any or all parameters changed?) if during a recording you use the app and switch profiles.

**(3)** Low-Speed cutoff filter between 0 an 7km/h: I fail to see any use case so common that it justifies we set this as **default**. We present the user with a peculiar menu offering 0 to 7 km/h values in 1 km/h steps, with no obvious purpose or guidance what a user should chose here and why ...
