### ISSUE TITLE
OsMo: Not possible to enable a group

### ISSUE THREAD

**Issue by seppwabala** [osmandapp/Osmand#3203]
I successfully can enter a group in Osmo with menu entry Join.
Then I can activate the group by adding the tick mark to the box.

Now i can not find any way to get back to the map without the tickmark at the group is deleted again, as
- klicking the back arrow in the title line
- using the mobile's back function

OsmAnd+ 2.4.7
Osmo Plugin

**Comment by vshcherb** [comment]
May be you can share a screenshot, unfortunately we are not able to reproduce it.
