### ISSUE TITLE
Configure map button icon on the map screen does not update in navigation case

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#3208]
Fresh start of OsmAnd, select a destination, start routing and hit "Go":

While the map display will change to car mode, the icon near the top-left corner of the map screen, will still reflect the Browse map mode.

**Comment by vshcherb** [comment]
Related #2744

**Comment by vshcherb** [comment]
Another issue Markers are not hiding in pedestrian profile during navigation.

**Comment by crimean** [comment]
Markers hiding fixed - https://github.com/osmandapp/Osmand/commit/d965472bb07dda62bf562b0c9989d44f21703427

**Comment by sonora** [comment]
Alexey, I cannot see a change yet in latest nightly, the original bug seems not fixed?

**Comment by crimean** [comment]
Just checked with fresh install. Image on the button change to auto when navigation starts.

**Comment by sonora** [comment]
Mixed success here: Yes, looks like when starting a follow-mode navigation, the icon seems to correctly change on devices where I had never produced the bug before. But on all devices (fresh installs and update installs) it seems that no icon change is triggered if you change the app mode manually after the navigation was already started?

**Comment by vshcherb** [comment]
@sonora Sounds like UI-design issue, in my opinion we should not allow to change user profile in navigation at least I don't see use case here.

**Comment by sonora** [comment]
Something is weird here, we have to review the code. I have a feeling right now that it is a simple bug, I think it occurs exactly when there is a day/night mode change associated with the profile change, i.e. if e.g. the Browse map profile has Day/Night-Mode "Day", while the Car profile has "Sunrise/Sunset", and you start your navigation after sunset.

So it should be a simple thing.

Changing the transport means after the routing has already started should be no problem in principle (and has always worked). Use  case is simply the after you started the navigation you detect you had selected the wrong transport means. You can change without first having to stop he routing again, should not be an issue, I think (and never was).

**Comment by sonora** [comment]
Really weird issue, the coherence with day/night changes may just be coincidental.

But it seems clearly a regression, when we still had the quick selector above the menu button it worked ok for all changes and use cases.

**Comment by vshcherb** [comment]
Weird, we will double check that application mode is consistent with icon and widgets, though it could be different in some situations with routing profile. And of course if we change routing profile in navigation, application mode should change as well.

**Comment by sonora** [comment]
From what I see, app mode, map rendering, day/night mode, the position icon, widgets, and the route itself all change 100% correctly (both for navigation started, navigation stopped, or app mode manually changed during navigation cases). Only the icon on the "layers" button often gets "stuck" and does not reflect the app mode status change.

**Comment by sonora** [comment]
It reminds me a bit of the initialization issue #2744 - I think app mode icon is also assigned via ApplicationMode.java....

**Comment by crimean** [comment]
Hardy, I made some changes - https://github.com/osmandapp/Osmand/commit/c5b49de6deff0e0d7eae9412b36b19542d5a08ca
Please check if it work as expected.

**Comment by sonora** [comment]
Alexey, what a crazy issue this is :)

I have just commented in #2744, it looks like it may somehow be connected to the day/night mode change, but it may also just be associated with the day/night presets associated with each profile. I  keep going througbthe code, but cannot find the issue ..

**Comment by crimean** [comment]
Made other fix :) https://github.com/osmandapp/Osmand/commit/7e55dfeed45b0086c77397b0679ff5fad4379e76

**Comment by sonora** [comment]
Looks like this works! Good job!!  ;)
