### ISSUE TITLE
[Feature request] Add Arab voice guidance.

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#3209]
Many users have requested this feature. Should we consider this?

**Comment by vshcherb** [comment]
We don't have any volunteer with Arabic knowledge yet :) So if they are ready to volunteer please invite them, I think with my help and help @sonora @xmd5a2, they will be able to create TTS file.

**Comment by sonora** [comment]
See #3254. I have no TTS engine capable of testing anything, nor any knowledge of the language, but can offer to work with whoever wants to assist here.

**Comment by sonora** [comment]
Very basic version implemented, for improvements please provide a pull request or contact me with how you can help.

**Comment by BoFFire** [comment]
Now we have at least one volunteer ;) and don't forget to ping us on openstreetmap forum ;)

**Comment by sonora** [comment]
@BoFFire  could you maybe have a look at the comments attached to this commit https://github.com/osmandapp/OsmAnd-resources/commit/2d2a8ccd5a2ea03ac0c9ab46bdae5002d2e20734#commitcomment-20145384 and perhaps try to get in touch with @ChaoukiBC  , maybe the 2 of you can load-balance some work :) Thx!

**Comment by BoFFire** [comment]
@sonora done :) thank you for the notification \o/
