### ISSUE TITLE
Notifications remain in place after app is closed and terminated 

### ISSUE THREAD

**Issue by vrtareg** [osmandapp/Osmand#3213]
Hi 

I have noticed that after latest nightly install notifications are left in notification area after app closure and termination. 

Regards, 
Areg

**Comment by vrtareg** [comment]
![screenshot_2016-10-30-12-52-19](https://cloud.githubusercontent.com/assets/2562730/19836692/4d6b2c58-9ea0-11e6-9292-b2ee0bc9c391.png)

**Comment by sonora** [comment]
Yes, the notifications are now by default also there even when nothing is ongoing (as long as the app is in memory). I guess the idea is to facilitate starting the related actions without pulling up the app GUI. A questionable concept which will likely confuse sone users (and raise misunderstandings and  discussions about power consumption again). Maybe we should go back to strictly starting actions from inside the app (usually the action widgets on the map screen) and have notifications only visible for things already running?

**Comment by vrtareg** [comment]
Hi Hardy

I am happy with this notifications. 
The only problem that in previous versions if app was cleared out from memory all notifications were cleared too.

Now they left there.

Looks like a new bug.

Regards, 
Areg

**Comment by vshcherb** [comment]
Notifications are destroyed automatically only when service is not running, in other cases notifications identify that background service is still running.

**Comment by vshcherb** [comment]
Actually there is one glitch that need to be fixed, if there is no active recording but the notification is present, the notification should be removed automatically when application is killed by swipe from recent apps list.

**Comment by crimean** [comment]
@vrtareg Please try latest nightly build

**Comment by sonora** [comment]
Alexey, Behavior now as follows (with no trip logging ongoing): notification present while app is in the foreground, and gone when put in background.

What is our target bahavior, actually? I suggest it must certainly always be visible during recording. Possibly also while there is an unsaved track, i.e when recording is paused.

But when there is no recording, and while the app is in the background, the only purpose could possibly be to facilitae quick-start logging without havinv to pull up the app? But with what parameters then (unfortunately they are profile-dependent?)

**Comment by sonora** [comment]
PS: One solution could be as we have it in latest nightly, with one exception:
- ongoing logging or unsaved track: always show notification: is OK
- no logging and no unsaved track: hide notification when app is in background. Is OK
- but: no logging and no unsaved track when app is in the foreground: We should hide the notification, as it has zero functionality?

**Comment by vshcherb** [comment]
Tested, looks good.

**Comment by vshcherb** [comment]
no logging and no unsaved track when app is in the foreground: We should hide the notification, as it has zero functionality?
It has functionality similar to widget

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/commit/5e044a51e25c5ace692d23caafbe69399dc04f1e

**Comment by sonora** [comment]
It may depend on Android version, but on all devices I have tested so far:
- "no logging and no unsaved track when app is in the foreground" case : Produces a notification only saying "Trip recording" with no Record etc. buttons. Tapping it does nothing but go back to OsmAnd, where you were anyway. (Buttons on notifications seem only show up if the underlying app is in the background, at least under all Android 4.x variants I have tested so far.)

**Comment by vrtareg** [comment]
Still same.
On Note 4 if I swipe out OsmAnd from last used applications list it doesn't remove  notifications and they remain stuck there ....

**Comment by vrtareg** [comment]
Hi

I am really struggling to understand how this is working now.

PreviouslyI was opening application and then was swiping it off from used
applications to get rid of notification without stopping GPX tracking which
is on by default in my configuration.

Now whichever I am doing notifications left there for days .....

Please consider to recheck and reopen please.

Regards ,
Areg


On Tue, 1 Nov 2016, 3:25 p.m. Areg, <notifications@github.com> wrote:

Still same.
On Note 4 if I swipe out OsmAnd from last used applications list it doesn't
remove notifications and they remain stuck there ....

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/osmandapp/Osmand/issues/3213#issuecomment-257596190>,
or mute the thread

**Comment by sonora** [comment]
@vrtareg  I think the target behavior is like this (and has always been, I guess):
- A notification is shown if the related functionality is on
- No notification if the related functionality is off

Whether the app is in the foreground, background, or terminated should not matter, as the functionalities we are talking about here are performed via an Android service (which is why we show the notifications, to make users aware something is running), not the app directly.

Is whatever you observe in ne with this, or do you see a different behavior?

**Comment by vrtareg** [comment]
Hi Hardy

I agree with the logic that if feature is on that notifications is on and
vice versa.

I don't agree with the part that it doesn't matter if app is in foreground,
background or complete off.

If I have opened app and functions are on so notifications should pop up to
show the status.

If I have used back button to go back it will continue to run in background
and I can return back normally.

If I swiped off app from last used list Android trying to gracefully close
application so there should be a piece of cleanup code that removing all
leftovers and also notifications.

So now when I close app by swiping it from last used list notifications are
left there and only way to get rid of them is to restart phone.

This is BUG!!!!!!!!

It was working in the way that I have described about a month ago.

Regards,
Areg

**Comment by sonora** [comment]
It may be Android dependent? I find that on all my test devices I can always tap on a notification, which puts me back to OsmAnd, then stop any functionality, and the corresponding notification disappears. On all devices I have tested so far, the notifications are correctly present only when a functionality (navigation, logging, OsMo) is still active. Please note that swiping the app does not necessarily end previously started background functionality (only if that is selected in the settings e.g. for logging). That could be new, not sure, but it may make sense.

**Comment by vrtareg** [comment]
I haven't upgraded Android lately but following nightly builds all the
time.
At some point it started to act weird.
I Samsung Galaxy Note 4 with Android 6.0.1 with security patch from October
1st.
