### ISSUE TITLE
The road number (in yellow pentagon) overlaps with bus stops

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/OsmAnd#3216]
I have observed where a pair of Road number markers (yellow pentagons) are overlapping on bus stop (shelter) markers. (In this case, the bus shelter markers are placed right on the road, not at one side of the road.)

Secondly, unlike the road name labels, the road number markers do NOT shift when we pan/zoom the map. As a result, they remain in the same place, and continue to cover the bus stop markers. 

Thus I am unable to see the bus stops. (Only a small part is visible)

**Desired:**
1. The road number markers should shift when we zoom/pan the map (just like road name labels)
2. The road number markers must not overlap with any features.

**Comment by dmpr0** [comment]
Not reproducible.

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/18944
