### ISSUE TITLE
basin=detention rendered as water body

### ISSUE THREAD

**Issue by azrdev** [osmandapp/Osmand#3226]
I discovered a `basin=detention` [here](https://www.openstreetmap.org/way/184804280) which is rendered as a body of survace water, even though it's only a "to be flooded when neccessary" area.

Running Osmand~ 2.4.7 from f-droid with offline maps.

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/845d325674515022ac9bec42bcad04037a800ad5
