### ISSUE TITLE
Invalid rendering of multipolygons

### ISSUE THREAD

**Issue by arturcz** [osmandapp/Osmand#3228]
Please compare screenshot from OsmAnd+ application and screenshot from OpenStreetMap site. You can see the application renders water by default in places where there is a land. The area where problem happens is http://www.openstreetmap.org/#map=16/53.8150/-1.6045

I am using OsmAnd+ 2.4.7 on Samsung XCover 3 with Android 5.1.1.

Application:
![osmand-screenshot](https://cloud.githubusercontent.com/assets/557490/19986785/f89320a0-a20f-11e6-9293-d2738cf2ed81.jpg)

Screenshot:
![osm-standard-rendering](https://cloud.githubusercontent.com/assets/557490/19986786/f8955c9e-a20f-11e6-9096-153ac655d30d.png)

**Comment by yxnyqcpw** [comment]
The data is in error. The waterway=riverbank tag should be on the [relation](https://www.openstreetmap.org/relation/582200) instead of the [outer way](https://www.openstreetmap.org/way/56256470).

**Comment by vshcherb** [comment]
waterway	=riverbank should be present on relation and that would fix situation.

**Comment by arturcz** [comment]
Thanks.

**Comment by arturcz** [comment]
FYI: I've fixed the map at the location. Thanks again for hint.
