### ISSUE TITLE
Multipolygons with `role:house` in the associatedStreets are breaking search of house numbers

### ISSUE THREAD

**Issue by Andygol** [osmandapp/Osmand#3231]
A similar issue was raised in #3064 and I would like to renew that ticket.

cc @vshcherb 

---

In case if the buildings multipolygons are the members of the associatedStreets relation with an assigned `role:house` it becomes impossible to find those building multipolygons in a search dialog pane and get info about their addresses via a pin drawer. Some buildings that are formed as closed ways, and are members of the relation, are missing in search results too.

Here is an example - the relation `Velyka Diivska Street` in Dnipro, Ukraine <http://www.openstreetmap.org/relation/1182272>

Building with the `addr:housenumber=22` is a [multipolygon](http://www.openstreetmap.org/relation/6084859) but other buildings with numbers `22а`, `24`, `24а` that were formed as closed ways and they are missed out in the search result too. The next building listed after the building with `addr:housenumber=12` is one with `addr:housenumber=26` - <http://www.openstreetmap.org/way/37848865>.

Some buildings in this `associatedStreets` relation have tag `addr:street=Велика Діївська вулиця`, some don't have.

OsmAnd|OSM data
---|---
![image](https://cloud.githubusercontent.com/assets/369696/20007336/705e4f12-a2a4-11e6-8d2b-88ac08838ccf.png) | ![image](https://cloud.githubusercontent.com/assets/369696/20007352/8bce8820-a2a4-11e6-93ea-fac077e07b96.png)

I downloaded `OsmAndMapCreator` and conducted several experiments. (Now, by using current map data, houses at streets described below weren't found)

1.  I added tag `addr:street` to all members with `role:house`of the  associatedStreets relation for `Monitornaya Street`, and
2.  I removed the building that was formed as a multipolygon from the relation of `Metrobudivska Street` and removed the tag `addr:street` from buildings along this street.

After that, I converted locally these changes for testing.

And for houses along these streets a search function started to work as was expected.

Map Data | Monitornaya Street | Metrobudivska Street
---|---|---
![s61104-16081669](https://cloud.githubusercontent.com/assets/369696/20009129/f44b7e56-a2ab-11e6-8a98-016e0dc57c97.jpg) | ![s61104-16073480](https://cloud.githubusercontent.com/assets/369696/20009135/fc0a096e-a2ab-11e6-982d-e56d1e967746.jpg) | ![s61104-16362094](https://cloud.githubusercontent.com/assets/369696/20009395/062f1910-a2ad-11e6-9a99-af17c9ca9b77.jpg)

The example of the data after changes -- [Osmand_test.obf.zip](https://github.com/osmandapp/Osmand/files/571760/Osmand_test.obf.zip)

**Comment by Andygol** [comment]
Here 👇 initial data that were used for testing - `osmand_test_ini.osm` and `osmand_test_ini.obf`
[osmand_test_init.zip](https://github.com/osmandapp/Osmand/files/572250/osmand_test_init.zip)

**Comment by vshcherb** [comment]
Hi @Andygol, I will take a look. Most likely the problem is in OsmAndMapCreator.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-tools/commit/a19e120e7315f016879a3a77e3719932ee352d6d
