### ISSUE TITLE
incorrect free space requested when downloading map update

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#3232]
There seems to be some issue with the display of the warning about disk space in 
 OsmAnd/src/net/osmand/plus/download/DownloadValidationManager.java , function downloadFilesCheck_3_ValidateSpace().

I have free space of 813MB. I try to download e.g. Austria that is said to be 466MB. I understand OsmAnd needs that space + more space to unpack the file before replacing the existing one (this is an update).

But the message I get is:
Really download 1 file(s)? This would temporarily need 747 MB and permanently 8,14 MB. There is only 813MB free.

So that permanent 8 MB seems incorrect as otherwise there would be enough space to do the operation (747 + 8 < 813). Maybe there is just improper order of magnitude displayed and it wants to say 814 permanently (current size of Austria unpacked is 739MB).
The problem with both download_files_error_not_enough_space and download_files_question_space_with_temp strings (OsmAnd varies between them for different maps).

**Comment by aceman444** [comment]
This is with OsmAnd 2.4.7 and maps of 1.11.2016.

**Comment by sonora** [comment]
I have not checked the code, but it looks to me like the message is informative only and does not say you cannot perform the operation?

The way I read it is that the new Austria map will ultimately be 8 MB larger than your current one which is being replaced, but interim the process will require 747 MB for storing+unzipping the download?

But I have to check the code when I get a chance.

**Comment by aceman444** [comment]
Thanks, in that interpretation the maths could add up. current 739 + 8 = 747 MB permanent, which is also the size of the temporary file after unpacking. However in that case, where will the downloaded file (packed) be stored? Is it that after download (before unpacking), the previous map is deleted and then the downloaded file is unpacked in its place?

From my experience it looked like download+unpack, THEN replace the old file with the new unpacked one. So you would temporarily need the size of unpacked and downloaded file, not just the downloaded (packed) file.

**Comment by sonora** [comment]
I changed the wording of the messages a bit to make tings clearer.

As to your question: Chances are the zipped file is only stored in internal memory, from there unpacked to the storage data folder, then the previous one deleted there.

But I leave the issue open for one of us to comment who knows, or for us to look at the code.

**Comment by aceman444** [comment]
So what does the fix do?

Also, I can confirm that currently I didn't have space for another copy of the unpacked file + the packed file, and the map update still worked properly. So it really seems you need space for the new unpacked file. So where is the packed file downloaded temporarily?

**Comment by crimean** [comment]
The old file replaces with the new one, so you need space for the packed + difference between old and new file. We added threshold = 10 MB. I.e. if you will have less than 10 MB free space after new map will be installed - you will see the warning before download.

**Comment by aceman444** [comment]
Ok, that makes sense, but in that case the message is incorrect. See the original report. It says about temporarily needing 747MB. That is the size of the new unpacked file, not the packed downloaded file (which is 466MB). Can you please check if the proper values are put into the message placeholders?
