### ISSUE TITLE
Bad offline route calculation

### ISSUE THREAD

**Issue by RealRancor** [osmandapp/Osmand#3233]
##### What version of OsmAnd are you using, on what device and Android/iOS version?

2.4.7, Motorola MotoG, Cyanogenmod 13

##### Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

Offline Maps within OsmAnd

##### If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

Germany_baden-wuerttemberg_europe_2.obf.zip 01.11.2016, also checked with 01.10.2016

__*In case of wrong routing:*__

##### Tell us whether you have used OsmAnd's in-app offline routing, or any online routing provider like YOURS, OpenRouteService or OSRM.

OsmAnd in-app offline routing

##### What routing profile is choosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest)

Car, fastest (other settings are defaults)

##### Please specify as exactly as possible the start and end point of your route by telling us city name and street name so that we can find it via in-app address search easily. Also a permalink from openstreetmap.org can be helpful.

Start point: Breslauer Straße 5, Villingen-Schwenningen
-> https://www.openstreetmap.org/way/94100693

End point: Goldenbühlstraße 25, Villingen-Schwenningen
-> https://www.openstreetmap.org/node/883462426

##### Tell us your expected routing, and how OsmAnd routes, or add screenshots here.

I have checked the way on openstreetmap.org itself and wasn't able to find any issues on the map itself. However OsmAnd is currently calculating a quite strange route like seen on the following screenshot:

![screenshot_20161104-180625](https://cloud.githubusercontent.com/assets/2248459/20015260/0cd3bb28-a2bb-11e6-875b-d60148c2f57d.png)

The expected routing is e.g. seen on OSRM:

http://map.project-osrm.org/?z=17&center=48.067609%2C8.460352&loc=48.081333%2C8.455462&loc=48.066702%2C8.453432&hl=en&alt=0

On-line YOURS routing (fastest and shortest) in OsmAnd is also calculating the correct route like map.project-osrm.org is doing.

Just also re-checked with "shortest" with  and the Off-Line Routing in OsmAnd which leads to the following (from my PoV still incorrect) route:

![screenshot_20161104-185702](https://cloud.githubusercontent.com/assets/2248459/20016735/fdf11d8e-a2c0-11e6-8c2c-6fde8bca3988.png)

**Comment by osMatt** [comment]
I am not sure whether [this turn restriction](https://www.openstreetmap.org/relation/193167) is the culprit. The to and from ways exceed the beginning and the end of [the small link road](https://www.openstreetmap.org/way/142706337). I had a similar case where splitting the 'from' way helped (here, this would mean splitting the 'from' way at [this node](https://www.openstreetmap.org/node/1561698276)). However, I think that the algorithm that processes the turn restrictions should be able to handle these cases.

**Comment by RealRancor** [comment]
Hey, thanks for your reply. I didn't noticed that turn restrictions but i must admit that i'm not too familiar with mapping / routing on OSM. Could it be possible that these mentioned issues is causing another wrong routing like this?

Start point: Heidplatz 1, Villingen-Schwenningen
https://www.openstreetmap.org/node/316692673

End point: Am Kneippbad 1, Villingen-Schwenningen
https://www.openstreetmap.org/way/53562281

Issue is at: https://www.openstreetmap.org/#map=19/48.06422/8.44188

Correct routing would be http://map.project-osrm.org/?z=17&center=48.064405%2C8.441805&loc=48.061342%2C8.449448&loc=48.067534%2C8.435015&hl=en&alt=0

but OsmAnd is currently doing the following routing:

![screenshot_20161105-151708](https://cloud.githubusercontent.com/assets/2248459/20030730/0237903a-a36b-11e6-8a54-c8316624c7fd.png)

**Comment by vshcherb** [comment]
The 2nd problem is related to a number of traffic signals. The routing engine calculated the fastest route correctly cause it takes into account traffic signals, this issue could be fixed by introducing traffic lights for the right turn or making impossible Uturn with restriction.

**Comment by vshcherb** [comment]
1st issue is a bug related to https://www.openstreetmap.org/relation/1931674#map=19/48.06703/8.45713 restriction. First of all it is quite untypical to draw such relations but this is not incorrect. Unfortunately restrictions could apply differently using via way and node. Technically speaking osmand format data doesn't support via at all, so that issue could not be fixed. 
However it is quite easy to fix the map, just splitting the way. Because it is very rare case, I will split the way on the map.
