### ISSUE TITLE
Trip recording somehow can block access to the tracks storage

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#3234]
How to reproduce:
- Fresh start of OsmAnd
- Start a manual trip recording
- Change profile from Browse map to Car (not sure that's actually needed, but seems it make it more reproducible)
- Then go to Menu / MyPlaces / MyTracks, to look at some of your recorded tracks (or details of the currently recorded track)
- Often, (not always, not sure), I see the spinner turning there and it never finishes or takes very long (minutes), as if OsmAnd somehow has no access the tracks folder (screen remains empty).
- Also, when trying to stop recording and saving the track now (via the GPX widget), the widget seems to hang in status "Save" (The track can finally only be saved after the next app start.)
- Also: If you now go to "Download maps / Local", also there the file listing seems blocked, with the spinner on that screen turning continuously ...

Sounds similar to #2967 (though we finally attributed that to a faulty SD card). This here looks a bit like a shared access to files issue?

**Comment by vshcherb** [comment]
Procedure is not that simple to reproduce, though we will try on other devices. @xmd5a2  could you please try to reproduce?

**Comment by sonora** [comment]
Yes, not 100% clear. From what I see have so far observed it where the data storage folder is in the extSdCard file system under Android 4.4 -5.1, but this may not be the root cause, just coincidental.

**Comment by polarbearing** [comment]
> widget seems to hang in status "Save" 
I observed this behaviour in recent nightlies on my Nexus S / 4.1.2 stock rom device, osmand storage on the non-removable "external" Sdcard.

**Comment by sonora** [comment]
May be deprecated, closing for now.
