### ISSUE TITLE
Trip recording filter behavior

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#3235]
I think this line https://github.com/osmandapp/Osmand/blob/835c8e90c75b137f5773181843a621b279f59984/OsmAnd/src/net/osmand/plus/OsmandSettings.java#L1072 causes manual trip recording in the Browse map profile to always apply the displacement filter of 5meters, **but this setting can nowhere be accessed or changed** (only for the car/bike/ped add profiles).

(1) So I think we need to set the preset for the default profile to "0" ?  (Equally for SAVE_TRACK_PRECISION and SAVE_TRACK_MIN_SPEED, but there it currently is anyway.)

Please note that post-processing a track where points have been pre-filtered at recording time (in specialized GPX software) is more involved and less reliable when no points for the device being at rest are recorded to the file at all, as the GPS chipset's motion detection is circumvented. (I also had to adjust our OsmAnd built-in track analysis with a workaround to try discover at-rest situations while no points are logged). So we should at least provide a way to remove all filtering, if not even make this the default.

(2) Also: Changing the app profile during a recording seems to adjust the filter settings on the fly, not sure this is by design? (It is not obvious to the user and may 'cripple' recordings to some extent.)

**Comment by sonora** [comment]
I have committed the fix for (1) here https://github.com/osmandapp/Osmand/commit/9965615bf1d6a6329a62a47b0f5e247b4e400026, hope there are no objections.

**Comment by vshcherb** [comment]
(2) I think it is ok. Though I'm not sure if default settings should be that much different. If they are changed by user than I believe by changing his profile his achieving exactly the precision he wants to have. I also believe we need to move setting about how often to record position to the settings (it could be difficult to depict "default" mode) but in that case recording could start without any dialog.

**Comment by vshcherb** [comment]
(1) no objection from my side

**Comment by sonora** [comment]
@vshcherb I've probably said it before :)  We would considerably simplify all things if we simply made the entire logging settings screen (file recording, online tracking, navigation logging, filtering) profile-independent.

As it turns out now, we have almost the same defaults for all profiles anyway, and I can hardly see a use case where it is really essential to have some of these settings differ from profile to profile.

**Comment by vshcherb** [comment]
Most likely you are right, most of the settings should be profile independent. I have only one remark (automatically record trips for profile), though it could be redesigned.

**Comment by sonora** [comment]
Are you talking about "Log track to GPX file during navigation"? I guess there is no big harm done if we make that, together with its associated logging interval, a global setting, too?

**Comment by vshcherb** [comment]
Yes. May be you are right. My gut feeling we need to open a separate issue about trip recording:
- to make all settings global 
- to make no dialog when start recording and create a global setting of interval

**Comment by sonora** [comment]
Ok, carried over to #3247 .
