### ISSUE TITLE
German “ä,ö,ü“ are not rendered

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/Osmand#3236]
The German characters  “ä,ö,ü“ are displayed as "a,o,u" the dottes are missing.
I noticed this on map and also in tts output.

Using #19104M 
Maps are from 1.11.2016

Greetings Simon

**Comment by sonora** [comment]
I cannot reproduce this (latest nightly), neither with old maps (August) nor with new ones. Chances are you have your Map language set to e.g English and not "Local names"?

**Comment by jf-simon** [comment]
Tested it with "local names". Then it works current. With "german" the dotts are missing.

**Comment by quelbs** [comment]
I also cannot confirm this on the map. Umlauts are displayed correctly for me.
#19113M - Tested with Map of Bavaria from October and November.

**Comment by jf-simon** [comment]
Strange. For me I have only ä,ö,ü., if I have "local names" for map language selected. 
My system is CM 12 Android 5.1.1
System language is English

**Comment by sonora** [comment]
Jus to confirm:
- Android device locale: "English (United States)"
- OsmAnd General Settings / Display language: "Same as device" (?)
- Map language: Manually set to German (from default "Local names")
- "Transliterate" setting under the "Map language" is really set to "off" ?

**Comment by jf-simon** [comment]
Found it. I have only looked in the settings ->"Preferred map language" and forgot to look in "configure map". There was under "German" "transliterate" enabled.
After disabling that, all works fine.
Thanks for help

**Comment by sonora** [comment]
Ok,that's what I thought ;)

**Comment by sonora** [comment]
@vshcherb Let me keep this open for Victor to see, because I now understand why you had the issue, and it could be considered a bug: We never ported the "Transliterate" feature to the Map language selection on the General settings screen.

**Comment by vshcherb** [comment]
@sonora shall we delete that option from general settings, of course we could introduce another setting but it won't be clear and it will be a duplicate comparing to configure map. I think "Configure Map" is a proper and should be the only place to change how the map looks like. General settings to adopt how app interacts with Android System.

**Comment by vshcherb** [comment]
Driving region will be improved so we don't need to send user to general settings at all.

**Comment by sonora** [comment]
Yes, I think I agree, let's keep the General settings clear of parameters how the map looks, that is the cleaner UI!

**Comment by vshcherb** [comment]
@sonora  could you change it?

**Comment by sonora** [comment]
Sure, I think this will do it: https://github.com/osmandapp/Osmand/commit/220419635aed816e7a984bdce4c71739a8a12dab
