### ISSUE TITLE
User defined POIs can't be searched anymore in new Search functionality

### ISSUE THREAD

**Issue by hvdwolf** [osmandapp/Osmand#3237]
OsmAnd+ 2.4.7 and 2.5
I created UK postcode POI files for use inside OsmAnd (https://github.com/hvdwolf/OsmAnd-UKpostcodes/releases).
With those files a user could search for the postcode via the POI search screen in previous versions of OsmAnd.
In the new OsmAnd version with the universal search screen it doesn't work anymore. Not via the mapscreen magnifying glass nor via the menu->Search  #option.

The POI category used is "user_defined_other". My POI type is "user_defined_other_postcode" as can be seen here:
https://github.com/osmandapp/OsmAnd-resources/blob/master/poi/poi_types.xml#L3405

Please fix this bug for UK residents and UK visiting users.

**Comment by hvdwolf** [comment]
Just tested it in the latest beta (8 Nov). It is fixed and works again. Thanks.

**Comment by hvdwolf** [comment]
And now I rebooted and it doesn't work anymore. I don't know what that means.

**Comment by crimean** [comment]
@hvdwolf probably this fix will help - https://github.com/osmandapp/Osmand/commit/bdc99eee15a471db34bc552138312f43317c26b4

**Comment by hvdwolf** [comment]
Unfortunately not. I see that your string was at 13:10 (CET) so I downloaded the "nightly" of 13:27.
Or am I too early.
Besides (not being a java programmer): I seed that you do a replaceAll("\n", " "). 
Maybe I see it totally wrong but if I search for a postcode 'CY14 9AA' there is no \n in that string.

**Comment by crimean** [comment]
You should have build number #19171

**Comment by hvdwolf** [comment]
So I have to wait a little longer. That 13:27 version was 15266D

**Comment by crimean** [comment]
Version is ok. I tried to search postcodes of Wales and it works ok. However you need to have current location or center of the map within this area.

**Comment by hvdwolf** [comment]
I will try but it is strange. If I'm in south of England and want to travel to Scotland I first have to go to Scotland. If it is some small town I might not even know where it is. Also: OsmAnd always defaults to the current location. In any app I select/search a destination. It would be very strange if I first have to go there. I even use OsmAnd (and others) to display a village if I don't know where it is. ("Kidmore End" : Where is Kidmore End?)

I always test without an active map of England or one of the regions. Some postcodes are in the normal map so they will be found.
I make sure the postcodes are not in the map like the Deal, Kent CY14 9* or Reading RG1 1* series (apart from RG1 1AF which is available).  And there are more of course.

**Comment by hvdwolf** [comment]
It does work fine.
I understand what you mean with going to the approximate location, but that's not very useful.
However, if I search from the Netherlands for a UK postcode it doesn't find it. 
If I then click "Find more" it takes some time, but then it finds all the postcodes. It can take quite some time depending on the distance and other maps (within that distance) loaded.

I forgot about this "Find more". When giving feedback on the 2.5 beta earlier I mentioned that I could find them and not anymore after a reboot.
I acted like a stupid beginner. Before the reboot I did use the "Find more" and after the reboot I completely forgot.

So I tried again the 2.5 beta from Google Play and even there it already functions. Or you need to be very close to find the postcode, or you need to use the "Find more".

Sorry for causing the confusion. I should have tested better.
