### ISSUE TITLE
Faulty behavior for taps on the route details screen

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#3241]
I think this is a regression, but have not yet found out when this started:

App in Browse map profile: Calculate a route (no follow mode), then go to the route details screen (by tapping on the route details line), and tap any of the turns.

(1) We used to mark the turn with the orange map marker (this still works), and we used to center (I think also zoom) the map in on the turn in question (this does not work anymore.)

PS: When you tap the little arrows in the route details line on the route configuration dialog, you can still correctly step through the map and the map centering works as it used to.

(2) Also, now for a tapped turn the street name display at the top of the map screen and the lanes widget show up (this may make sense, but I am not sure.), but they cannot easily be made to disappear somehow? I guess we should at least make it disappear again once the user hides the route config dialog?

**Comment by sonora** [comment]
@crimean  Alexey, street name widget hides ok now when route details dialog is removed, but the lanes widget (if any, i.e. if user had tapped a turn with lanes) still remains stuck. - Best, Hardy

**Comment by crimean** [comment]
Hardy, you are right. Fixed - https://github.com/osmandapp/Osmand/commit/dd26edd6a406540240d2fe01d8f0e424654b5712

**Comment by sonora** [comment]
Yes, confirmed working! Good job, thanks!
