### ISSUE TITLE
Default POI icons and house numbers are displayed at wrong positions

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#3248]
Hi,

if I click for example the "Holiday World" in the search results or if I click the POI icon of the "Holiday World" to set the marker I found that the marker is miss-positioned (not on the icon). This is clearly not the behaviour the user expects.

This happens with many POI icons on the canary islands but the "Holiday World" is an extreme example.

![screenshot_2016-11-07-20-57-49](https://cloud.githubusercontent.com/assets/6921696/20074738/d41b5fce-a531-11e6-9fd9-fecb2c21c903.png)

Found with OsmAnd+ 2.5.1.

**Comment by sonora** [comment]
Looks like only area POIs are affected, he POI icon often does not seem to be in the center of the area (while the map marker is). (The object in question here is http://www.openstreetmap.org/way/218738804).

**Comment by Norbert80** [comment]
@sonora I see that the icons of punctual POIs are affected as well. Just try high zoom levels...
![screenshot_2016-11-08-21-09-56](https://cloud.githubusercontent.com/assets/6921696/20116327/1c60af4e-a5fc-11e6-9cce-52b8868f1d8a.png)

**Comment by Norbert80** [comment]
On the two screenshots attached below I have enabled the orange POI icons. You can see that there is always a distance between the orange POI icons and the default POI icons. Since the marker matches the position of the orange POI icon it is very likely that the positions of the default POI icons are wrong. But for my understanding this is not proven at the moment.

![screenshot_2016-11-09-08-35-40](https://cloud.githubusercontent.com/assets/6921696/20136883/9ad0f9d0-a677-11e6-820c-b103ce1690fa.png)
![screenshot_2016-11-09-08-37-32](https://cloud.githubusercontent.com/assets/6921696/20136884/9af0b450-a677-11e6-8f9f-f45598f30448.png)

**Comment by Norbert80** [comment]
It is indeed very likely that the default POI icons are in the wrong positions. I had a more detailed look at some area type POIs. It looks like the orange POI icons and the markers are at the center while the default POI icons are not centered.

**Comment by vshcherb** [comment]
Please provide a scale is it 2-5 meters error? We don't justify icon to the POI location so the pin stays at the location of the icon which could be not precise if you zoom in from 15 to 22 level

**Comment by sonora** [comment]
I had measured it, it looked like it can be up to 20-30 meters. The case in the first screen shot above seems like 25m, and it remains constant at that when changing zoom levels

**Comment by sonora** [comment]
Strangely, (but probably unrelated), from zoom level 20 and higher I even get 2 icons, see sreenshot (lower right icon is the original and in the original position like for zoom levels <=19.

<img width="135" alt="screenshot_2016-11-12-14-40-32" src="https://cloud.githubusercontent.com/assets/845735/20238205/4bf68fde-a8e6-11e6-97c0-49735ec741df.png">
)

**Comment by vshcherb** [comment]
amenity attraction is not implemented and not clear if it shold be as you see marker correctly positioned to the label ( which is correct according to the geometry), poi and another point is distanced because it is a different object

**Comment by Norbert80** [comment]
Below I have attached a screenshot where you can see that house numbers (which I think are technically the same as the default POI icons) are display at wrong positions too. The "5" is positioned out of the area of the house.

![screenshot_2016-11-29-19-35-27](https://cloud.githubusercontent.com/assets/6921696/20766978/c9cc42a4-b738-11e6-9647-171a3ad43420.png)

**Comment by Norbert80** [comment]
@vshcherb would it be possible to set a target milestone for this one?

**Comment by vshcherb** [comment]
@Norbert80 not clear yet, possibly next release. For release after we usually don't plan.

**Comment by Norbert80** [comment]
@vshcherb Any update if this one will be fixed for the next release? Many thanks in advance!

**Comment by vshcherb** [comment]
Yes, the problem is quite complicated. The POI icons are calculated on the server and they try to find the best position in the polygon and the map icons position calculated on the device, though it is trick to solve but I guess solvable.

**Comment by Norbert80** [comment]
@vshcherb. I saw that you have added 2.6.1 as milestone for other bugs. Is this possible for this one, too?

**Comment by Norbert80** [comment]
@vshcherb I still experience this bug with today's OsmAnd+ 6.1.0 release on Google Play.

**Comment by Norbert80** [comment]
@crimean Do you have any idea why I still experience this bug?

**Comment by crimean** [comment]
@Norbert80 no, please wait for @vshcherb answer.

**Comment by Norbert80** [comment]
@vshcherb this bug still persists in recent OsmAnd builds. Please re-open it.

**Comment by Norbert80** [comment]
@vshcherb why did you close it????

**Comment by Norbert80** [comment]
@vshcherb why don't you comment? I need to file a new duplicate report if you don't react.

**Comment by vshcherb** [comment]
@Norbert80 calm down you are not running this project. You can open if you think it helps the product evolve but you can't control developers what to do.

It couldn't be completely fixed yet cause POI label location is calculated during map processing and map label location is calculated during map rendering. On your screenshot it doesn't look very critical issue.

**Comment by Norbert80** [comment]
@vshcherb It looks like you really have no idea how to communicate with a community and its collaborators.

- You confirmed the bug.
- You added a milestone.
- You close the bug after reaching the milestone.
- Than I see that the bug is not fixed in that milestone release.

What do you expect in such a situation? For me it looks like something went wrong or has been forgotten.

**Comment by vshcherb** [comment]
@Norbert80 is somebody can do it better, why not? Again who said it is my job, so far I'm the only who manages the contribution to OsmAnd but nobody is against other contribution and fixes. 

This issue is duplicate https://github.com/osmandapp/Osmand/issues/3684. Once #3684 is fixed it will be fixed as well. Technically it is the same

P.S. Why are you calling me personally? I'm fine that you report as many issues as you want, I'm fine reading but I'm not fine fixing or being responsible for all issues you reported.

**Comment by sonora** [comment]
Let's simply conclude here that the remainder of this issue has been merged with #3684. :)

Please note that we are a rather small team, and our focus often is on the code more than on maintaining issue content and interdependency (naturally, many issues are often reported more than once).

**Comment by Norbert80** [comment]
It looks like POI and marker positions have improved in 2.8.0.
