### ISSUE TITLE
[Feature request] Adding Arabic TTS

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#3254]
We've been receiving these requests for a while now. Arab users will be glad to see their language added)

**Comment by sonora** [comment]
For what it's worth, I have provided a starting point here: https://github.com/osmandapp/OsmAnd-resources/commit/574ee0d9c258564e2e767682606a582b0782d926

This is completely machine-translated, based solely on English grammar, and will be lacking correct word order and plurals. But it may be a starting point which I hope can lower the barrier for someone knowledgeable starting to work on it.

**Comment by vshcherb** [comment]
We had other issues about Arabic TTS as well we might want to link them together.
