### ISSUE TITLE
OsmAnd DPI bug with Android 7.x "display size" setting

### ISSUE THREAD

**Issue by valynor** [osmandapp/Osmand#3255]
Android 7.x Nougat has a new option in settings > display > display size for resizing all Android UI elements, which I set from _standard_ to _small_. 

All UI elements in OsmAnd are now much **larger** than usual (buttons, widgets, scale, even the menu). 
With the setting set to small they should be **smaller** or at least unchanged.

Here's a picture how this looks on a Nexus 6P:

https://lh3.googleusercontent.com/NfkOYEpDp0LFPnbpeCvcdEmoLtkPo2eoqZioVJQ0qWVTxCI9XJqhRRT4CnfqYVziCYDkSurosF-7ztvvfEj11m4Yb-ah1rQ_UhBebRx3_Q-N_RLF1z7xxmpTTc9eBgc8nvcl0wuBKpC15MrdEoHcdk_A0SAKt2Ag25uIIFJcnXZgLhwF1gzbvwN1ieEej1EuikIdfocw9zE1-Baxx8dLaMBXRr8W5X_gNUM3Egya86uoiXM5e6dDsW4mVqMTcv1IctLLwz7GSVW0Iig4tcCNJK4u7SZ3CEUgpIjOW_JT4kV7FcQRLDTrnx67ND6j3bFi075PwANGPPjEvT5HD5hz5pamMNehWOiM1k96rwLHnleum796EJpCsls8EZIpbahAzrkUH5IKAhEaPe95_kBz9S4Gs6xftR8pnG5TWpXhhyqWlzEsz0-O9Kg2zbzItgT9iM_P9Uv7wyCw1u5UFFMymFv7O4sxIe0UNGJUEUv_Vzq6ywTJO2alC7uCRGjqbQeTMryc3xrUgYSlpAtzKIXND3N3XGCgChAoPtu9HP9GBXnRzBFifmqY1QEnyepxwSiM5B6ywto=s1080-w608-h1080-no

**Comment by valynor** [comment]
None of the devs with Android Nougat on their device(s)? :-) 

Bug is still present in 2.5.4 and so far OsmAnd is the only app on my device that doesn't play along with the new "display size" feature.

**Comment by thinrope** [comment]
Picture is not accessible, check "sharing permissions".

**Comment by valynor** [comment]
Link changed to the original URL .. no idea why link shortening removed the public viewing permission. Thanks.

**Comment by vshcherb** [comment]
None devs have Android 7. Is it possible to reshare the picture?

**Comment by BOHverkill** [comment]
Not the original Picture but with the same issue: https://i.imgur.com/Fkhe7WJ.jpg

Device Info:
Nexus 5X
Android 7.1.1
Display size "Small"

**Comment by vshcherb** [comment]
That's potentially tablet layout bug,  Potentially fixed by https://github.com/osmandapp/Osmand/commit/10ccc2da2549808cdb49cdc8d20299c27d7f8cc8 (needs testing)
