### ISSUE TITLE
Crash when long-pressing map (version 2.5.2)

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#3258]
What version of OsmAnd are you using, on what device and Android/iOS version?

Android 6.0.1, Samsung Galaxy S7, osmand 2.5.2 (the just released one) 

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

Osmand-provided map. US Georgia and Florida, the latest ones released a few days ago. 

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

United States of America Georgia and Florida dated October 31, 2016

What routing profile is choosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest)

Doesn't seem to matter, it crashes with all of them. 

Long- pressing on the map *anywhere* causes an immediate crash. 

I also tried searching for nearby places using the new search feature. Search worked, but when I selected a place at random, it crashed. 

Selecting one of my favorites also caused a crash.

**Comment by vshcherb** [comment]
Could you provide a crash log please?

**Comment by jfburke3** [comment]
Arg, slight correction.  This is happening on my Samsung Galaxy S5 running Android 5.0. I don't know where my brain is this morning.

**Comment by jfburke3** [comment]
[exception.log.zip](https://github.com/osmandapp/Osmand/files/585906/exception.log.zip)
[Uploading exception-1.log.zip…]()

**Comment by jfburke3** [comment]
[exception-1.log.zip](https://github.com/osmandapp/Osmand/files/585910/exception-1.log.zip)

**Comment by jfburke3** [comment]
Someone also started a discussion about it yesterday in the Google group.

**Comment by crimean** [comment]
Thanks for the log! Fixed by https://github.com/osmandapp/Osmand/commit/8e32731ce7cc8e1987a85c5ea269283536dfe7da

**Comment by jfburke3** [comment]
Yay!
