### ISSUE TITLE
Ask to enable permissions more often (location and storage)

### ISSUE THREAD

**Issue by DFyson** [osmandapp/Osmand#3262]
When selecting a custom data storage folder from options menu, if storage permissions have not been granted, the error "Maps could not be created in specified directory" gets sent. Most apps now will ask the user. Makes it more clear why there is an error and faster to fix. I noticed the app can do it from the first-start splash screen which is great.

The other one is location permissions. For some reason the app doesn't ask to grant it location permissions if it is disabled.

 Using latest OsmAnd+ 2.5.2 on Android 6.

**Comment by vshcherb** [comment]
We double checked settings and route planning permissions are asked in these places, so it looks we cover 90% of main cases.
