### ISSUE TITLE
crash on setting a marker 

### ISSUE THREAD

**Issue by lanlock** [osmandapp/Osmand#3263]
Hi guys,

since the last 2.5.2 update i am not able to set a marker or hit a POI without the app to crash.
I am using a HTC one x+ with a custom rom Cyanogenmod 11 (Android 4.4.4)

This is not just inconvenient. It makes the OSMAND unusable. 

I attached the exeption.log 

[exception.txt](https://github.com/osmandapp/Osmand/files/587049/exception.txt)

**Comment by jfburke3** [comment]
They just fixed this.  See #3258

https://github.com/osmandapp/Osmand/issues/3258

**Comment by sonora** [comment]
I think this is the same as #3256  and #3258 . It should be fixed in our nightly, can anyone confirm?

( @Crimean )

**Comment by jfburke3** [comment]
Yes, seems to work in last night's nightly.

**Comment by jfburke3** [comment]
I just installed the release that showed up in the Play store this morning  (in signed up for the beta channel, so I assume it's not the general release version), and it works there, too.
