### ISSUE TITLE
Default Activity

### ISSUE THREAD

**Issue by abbasiehsan1991** [osmandapp/Osmand#3267]
Hello
I am new in android and i use  git clone for downloading this source.
When it finished i  opened osmAndCore-sample with android studio , but when i run this project i got this  error " Could not identify launch activity: Default Activity not found Error while Launching activity ".
Excuse me if my question was too simple but after two days i couldn't fix this.
Thank you for  your answers .
![dsdf](https://cloud.githubusercontent.com/assets/23223511/20256770/d220d9aa-aa5a-11e6-9358-1f9427a502cc.PNG)

**Comment by abbasiehsan1991** [comment]
It's really important for me , i really appreciate it if anybody help .

**Comment by vshcherb** [comment]
Not an osmand product issue, so I need to close it.
