### ISSUE TITLE
Improve Spanish Play Store screenshot captions

### ISSUE THREAD

**Issue by franco999** [osmandapp/Osmand#3269]
The corrected versions should be:

1 **Title:** Navegación sin conexión

3 **Title:** Grabación de viajes | **Desc:** Grabe trazas GPX y úselas para viajar
4 **Title:** Estilo de mapa senderista
5 **Desc:** Rutas y paradas de transporte público (metro, tranvía y autobús)

7 **Title:** Fotos satelitales | **Desc:** Combina los mapas de vector detallados con teselas de mapas en línea
8 **Desc:** Obtiene actualizaciones de mapas cada hora, día o semana

**Comment by vshcherb** [comment]
Done
