### ISSUE TITLE
Unwanted "trip recording" notification appears on start-up

### ISSUE THREAD

**Issue by njohnston** [osmandapp/Osmand#3270]
I just upgraded to OsmAnd+ 2.5.3. I'm using a Samsung Galaxy S5 running Android 6.0.1.

When OsmAnd starts, a trip recording notification appears:

![osmand_trip_recording_notification_small](https://cloud.githubusercontent.com/assets/638458/20359376/753d7396-ac27-11e6-8b63-6415c4026e38.jpg)

I have the trip recording plugin enabled, but I am not recording a track. There is no track data to save either.

This notification is completely unnecessary. It doesn't tell me anything. I cannot interact with it. It just clutters my notification bar and forces me to swipe it out of the way.

I know there was some discussion about this in #3213, and it looks like @vshcherb added a setting to disable the notification by default in 5e044a51e25c5ace692d23caafbe69399dc04f1e. However, the setting ("Trip recording (no data) - Show notification which allows to start trip recording by pressing the Record button") is enabled by default for me. Also, there's no record button in the notification either.

**Comment by vshcherb** [comment]
You can disable it in settings. Record is visible if you expand the notification by dragging.
