### ISSUE TITLE
Restore "Configure map" item on main menu

### ISSUE THREAD

**Issue by njohnston** [osmandapp/Osmand#3272]
I just upgraded to OsmAnd+ 2.5.3. I'm using a Samsung Galaxy S5 running Android 6.0.1.

I've used OsmAnd for about 2.5 years, and I was completely confused. I couldn't find "Configure Map" on the main menu. Eventually I realised that "Configure map" can be accessed by tapping the profile/mode button at the top left of the screen. This is not very discoverable.

I'm not only the person confused by this. Here's a review someone posted on Google Play:

![google_play_review_configure_map_missing](https://cloud.githubusercontent.com/assets/638458/20360087/550d89dc-ac2a-11e6-8bb4-7b98495b7352.jpg)

To access "Configure map" I still unconsciously try accessing the main menu and then "Configure map".

I know you want to simplify the interface. That's good, but I'm so used to having "Configure map" in the main menu that its removal is very disruptive.

One other point: having "Configure map" in the main menu makes it much easier to access when using a phone one-handed, because you can just swipe anywhere from the left to show the menu and then select "Configure map", rather than trying to reach the top left corner which is harder.

**Comment by pebogufi** [comment]
"Use location..." is also missing in latest builds/version.
Please add it again.
Regards Peter

**Comment by sonora** [comment]
My 5 cents:
- Regarding "Configure Map": Yes, it is very debatable. But most map programs make what affects how the map looks accessible via a button on the map, not in a general app menu. In a sense "moving what belongs together closer together"
- Regarding "Use location...": I had coined the wording for that menu item years ago when we did not have an interactive map yet. But isn't it much more intuitive now that you can long/tap or short tap on the map and get all related actions offered via the popup context menu? Same philosophy here: move objects and all related actions closer together, without the "detour" via a separate menu. (?)

**Comment by pebogufi** [comment]
Regarding "Use location...":
If gps is on and I want to add a poi (favourite) or a flag or something else to current position, the Use location was the most precise possibillity to use this position.
All tapping around on the screen is less precise, especially, if I am on a lower zoom level. To get a precise position I first have to change the zoom level to a very high degree.
Peter

**Comment by sonora** [comment]
Now you can do this in 2 taps only (one less than before):
- You can simply short-tap your position icon (the blue dot or arrow), then tap the star. 

(I do this on the golf course all the time to measure the distance of my shots :) )

**Comment by pebogufi** [comment]
Sonora, thanks for this hint, it is fantastic.
Now it is ok for me to have it removed.
