### ISSUE TITLE
NPE when selecting some Wikipedia POIs

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#3278]
It is article-specific, happens when tapping certain articles  both under e.g. "Nearby articles" or in the search hits.
[exception.log.txt](https://github.com/osmandapp/Osmand/files/601570/exception.log.txt)

**Comment by sonora** [comment]
This prevents the app crash https://github.com/osmandapp/Osmand/commit/90fe2b405f33aed592a07949bf60f7a76cfab7a5, but it is still unclear why there is null content for some wiki pages.

**Comment by sonora** [comment]
Most likely an issue with our Wiki creation: Tapping this village http://www.openstreetmap.org/relation/1059450 does offer the correct "Nearby Wikipedia article", this one: https://en.wikipedia.org/wiki/Theisseil.
- But with null content (though the article contains some text.)
- And despite there being more language versions, it looks like we offer only the EN version? (The most complete one being the German one, but it references slightly different coordinates)

**Comment by sonora** [comment]
It looks like our language detection code is correct now. From my testing, when the issue occurs, exactly this line  https://github.com/osmandapp/Osmand/blob/master/OsmAnd-java/src/net/osmand/data/Amenity.java#L201 (not any earlier case) returns `defLang`, indicating that no content in any language was detected in our Wiki obf file for the article in question.

There may be issues with our wiki.obf's...

**Comment by crimean** [comment]
@sonora Thank you!

**Comment by sonora** [comment]
App code is ok now, but we still somehow have an issue with our wiki.obf creation, I assume?
