### ISSUE TITLE
to much TTS after update

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/Osmand#3279]
If a new update comes to OsmAnd+ a lot of TTS-voices come installed as standard.

The most user from OsmAnd+ don't need all these TTS-voices.
A lot of user will only use 1 or 2 TTS-voices.
If the TTS-voice have a update this can be found in the map manager and don't need update by App-update.

Can we delete the TTS-voices from OsmAnd+ installation file?

regards

**Comment by sonora** [comment]
There is no benefit, the files are extremely small (it is only the vocabulary, not the synthesizer libraries), and having things as is makes it easier for someone with a fresh installation sitting in the car and selecting the correct TTS voice (from the worlds more common languages) upon a first navigation attempt.
