### ISSUE TITLE
missing internet based search in 2.5.3

### ISSUE THREAD

**Issue by outofcreativity** [osmandapp/Osmand#3280]
Yesterday I've upgraded to the new stable version from Google Playstore and since then I can't find the internet based search. I really like the online search, because it is faster on my fairly rusty device.

Previously I've used the POI Tab (which included Nominatim) and had the Plugin for onlinemaps activated, but without the switch for downloading maps, because I use offlinemaps.

I've already read #3261, but that seems to cover another issue. I've also tried "search more" as suggested in #3261, but that does not help either.

Did I really miss something, or is it broken in the newest version on Google Play?

Device: HTC Desire HD, Android 5.1.1
Osmand: Osmand+ 2.5.3, 2016-11-13

**Comment by vshcherb** [comment]
That's true. We have it missing now, I think we will need to add back for online plugin.

**Comment by crimean** [comment]
We have added new item "Show legacy search" to development plugin settings. It will show old search in the drawer list when activated.
