### ISSUE TITLE
Language codes >2 letters in length

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#3282]
Implementation reminder: Android now supports language codes >2 letters in length (https://developer.android.com/reference/java/util/Locale.html).  We have some issues in our code , to be amended.

One example is in OsmamdApplication.java
```
public String getLanguage() { 
(...)
	if (lang != null && lang.length() > 2) { 
		lang = lang.substring(0, 2).toLowerCase(); 
	} 
	return lang; 
```
There are likely others.

**Comment by vshcherb** [comment]
That's going to be tricky... but I guess here we could just use number 3 and I don't think it will break.   To be honest I don't know why substring is used here.

**Comment by sonora** [comment]
Not sure either. I guess years ago it may have served as a simplification to unify language codes like en_GB or es_AR to just 2-letter codes.

If that's the case, I guess we could replace by cutting at the first occurrence of an undersore "_" with no harm done, but it will require some testing.
