### ISSUE TITLE
Name are changing of language/alphabet when zoom changes

### ISSUE THREAD

**Issue by bagage** [osmandapp/Osmand#3284]
## Description:
Using Android version 2.4.7 from F-droid on Android 5.1.1 AND 7.0. Using the offline maps offered within the OsmAnd app for download. I downloaded Cambodia country file from today (15.8 MB). 

1. Search for Cambodia capital `Pnom Pehn` using an English device. The city is displayed, as expected, with its name. (using either `name:en` or `int_name`, I don't know which one is used since they have the same value).
2. Zoom on the city so that the city fits the whole screen. Zoom a bit more.

## Expected:
Either `Pnom Pehn` should continue to be displayed, or some lower elements should replace it.

## Actual behavior:
`Pnom Pehn` is replaced by the Cambodian value of it eg tag `name` (រាជធានីភ្នំពេញ).

Maybe this is because English value cannot fit the screen anymore while the Cambodian one can, but I think this is a bug.

**Comment by sonora** [comment]
Go to the "Configure map" menu (top left button on the map screen), and verify your ""Map language":  I guess you have "Local names" selected. If you want English, then select accordingly. (On the world overview map, i.e. zoomed far out, we always use English, or else you would get a mixture of all sorts of characters.)

**Comment by bagage** [comment]
Your assumption was right indeed, I did not know about that nice feature. My apologies!

**Comment by vshcherb** [comment]
@sonora I would like to correct. For basemap we always use "Device language" i.e. System language or what is configured in the settings!

**Comment by sonora** [comment]
@vshcherb  Victor, yes, right! Most of my test devices are set to US English, your comment reminds me it is a good idea to change some of them ... :)
