### ISSUE TITLE
Display element ID for a selected object.

### ISSUE THREAD

**Issue by DFyson** [osmandapp/Osmand#3286]
I've sometimes wanted to get the OSM element ID (node, way, relation ID) of an object in OsmAnd to lookup the history on openstreetmaps.org or load into JOSM. Obviously this depends on if OsmAnd .obf map files still contain the orignial OSM id.

I was thinking it would be nice to see it listed in the description of an object. Then for maybe if you tap it will open OSM url, and if you hold-tap it copies to clipboard or something. Since most people don't care about this, it could be an option in the OSM editing plugin or developer options.

**Comment by vshcherb** [comment]
For OSM Editing plugin we could enable row with url pointing to Object id on openstreatmap.org
i.e. http://www.openstreetmap.org/node/2182352349

**Comment by DFyson** [comment]
It seems to only be available for a few things. As examples, churches, fountains, parks, supermarkets, and parking have it but other things like bus stops, addresses, car repair, trees, restrooms, bars, pubs, bakeries and atms don't.

**Comment by vshcherb** [comment]
Recently we fixed another issue, it should work much more reliable for node objects, so the latest version needs to be tested.
