### ISSUE TITLE
short touch on map selects multiple posibilities - no closing offered

### ISSUE THREAD

**Issue by harvey637** [osmandapp/Osmand#3287]
when you tap on the map with single poi you get an orange marker and (sadly only in portrait #3053) 
three dots in a tab in the middle to close the description of the poi (slide down). 
- ok so far (no closing in landscape still)

If you happen to tap on the map with more than one poi/item there is a selection context menu,
where you ca select one of the listed items like poi or my_location(blue dot) or favourite(star). 
After selecting of a single item you get the normal orange marker and the (in portrait) 
closable contextmenu.

What about the same tree dots closing tab also for the intermediate selection menu? 
please in landscape and portrait :-)

**Comment by sonora** [comment]
It can be closed by either tapping the device's "BACK" button (like conventionally all menus should behave), or by tapping somewhere else on the map. Isn't that sufficient?

**Comment by harvey637** [comment]
back-button is correct.
But this behaviour is simply inconsistent. If you happen to touch a single poi you close with sliding down
the three-dots-tab. If you accidently happen to touch a point on the map with more 
pois/favourites/items you have to touch the back button, because thre are no three_dots.
That means that you have to really "read" the context menu to close it accordingly.
Which causes more distraction while driving.
And also the back-button is dangerous, as there is no end-the-application button. which very often 
closes the app unwantingly.
Same goes to the landscape-bug with the missing three_dots #3053, just keep the contextmenu closable
always with the same "slide away the menu" handling.

**Comment by harvey637** [comment]
The three_lines main menu slides in from left, and can be close with "slide_to_left" (as nice to have there could be this tree_dots_tab on the right side as optical hint of the correct working "slide_to_lift" action)

Map configuration also slides in from the left (as main menu), but only uses lower part of my tab. 
Closing is done with the left_arrow in the top line of the display. Consistent it should slide into from buttom_up, as it uses the lower part of the display. And it should be closed (with the visable three_dots_tab) sliding down.

The routing menu also slides up from the button, but to close it we have to touch the "x" button.
If I close this menu with the back_button, it calculates! the route, even if I only accidently touched the 
routing_menu button.

**Comment by vshcherb** [comment]
I think main issue is still #3063 and we need to review back button so it works correctly.

**Comment by harvey637** [comment]
hippo new year!
yes, that sound great - pls with the three dots as other swipe_down menus.
(and pls remember to implement this also to the portait mode menus.)
Thx
Harvey

**Comment by matthijskooijman** [comment]
I believe this issue is no longer relevant, because:
 - The "What's here" popup now behaves the same as the POI dialog, and can be closed by swiping down (or left in portrait mode).
 - The "What's here" popup additionally has its own "Close" button now.
 - The 'three-dots-tab' seems to be no longer used in any part of the interface, so this inconsistency is no longer present either.

@harvey637 Can you confirm and close this issue if you agree?

**Comment by harvey637** [comment]
working
