### ISSUE TITLE
TTS destination:ref should use toward

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/Osmand#3289]
`destination:ref` should use `toward` and not `onto`

example:
https://www.openstreetmap.org/way/145035982

turn slightly right **onto** A99 toward Nürnberg
~but it should be:~
~turn slightly right **toward** A99 toward Nürnberg~

turn right on way with destination = toward
turn right on way with name/ref = onto

Tested on OsmAnd 2.5.4 and Nightly 2.5.0#15419D with latest Bavaria map.

**Comment by sonora** [comment]
Theoretically correct. But in practice: I happened to drive that section some time ago myself, and I found no unusual or misleading prompt there. The section to turn onto (like most which are labeled with a destination:ref) is the direct link to A99, and it is also labeled accordingly, I think there is hardly any room for confusion ?

In our code, from what I remember, we only pass 3 different parameters to the voice engine: One is geared at containing a ref, the second a destination, and the 3rd a street name. The grammar for these 3 types may differ significantly in several languages. and this is why we pass destination:ref, being type ref, to the first field, and not to the second. (Resulting in the grammatical treatment you observe.)

We only use destination:ref as a fallback for if there is no ref present, anyway. And with the current practice we automatically ensure that we do not result in awkwardly announcing 2 different refs. 

Looking at all this, I am afraid there is no easy improvement which would not potentially break several other pieces of long-tested logic and grammar....

**Comment by hakuchi** [comment]
what about combine the two keys "destination: ref" and "destination"

from:
turn slightly right **_onto_** A99 **_toward_** Nürnberg
to:
turn slightly right **toward** A99, Nürnberg

Can this handle the map creator by converting `destination:ref=A99` `destination=Nürnberg` to `destination=A99; Nürnberg`?

So this works also on streets with "ref", "destination:ref" and "destination".

Examples:
http://www.openstreetmap.org/way/31957655#map=15/45.8734/10.9004

On this roundabout exit, the voice guidance will be:
take second exit **_onto_** SS240 **_toward_** A22, Mori, Rovereto

2th:
www.openstreetmap.org/way/370563044
On this roundabout exit, the voice guidance will be:
take second exit **_onto_** N 4 **_toward_** B 2, A 73, Würzburg, Suhl, Fürth, Centrum

**Comment by sonora** [comment]
Yes, possible. But as you can see by your own examples, this possibly lengthens the voice prompts by pronouncing repeated references (ref and destination:ref), which in some cases/countries could mean 2 repeated lengthy series of letters and digits being read.

From most user feedback I gather on the topic of voice prompts, people prefer concise prompts. After all, the purpose is giving quickly comprehensible, unambiguous directions, there is no per se value in giving as complete as possible lengthy prompts.

We even have requests to shorten multiple directions (like in your example "Feucht, Wendelstein, Kleinschwarzenlohe") to pronounce just one prominent one, but the algorithm of how to identify what would the "prominent one" is unclear...

**Comment by hakuchi** [comment]
I agree that we should have short voice prompts.

But actually OsmAnd using only `destination:ref` and `destination` if `ref` is also present:
EN
take the second exit **_onto_** A22 _**toward**_ Mori, Rovereto
DE:
nehmen Sie die zweite Ausfahrt **_auf_** die A22 **_Richtung_** Mori, Rovereto
IT:
pendere la seconda uscita **_su_** A22 _**verso**_ Mori, Rovereto

on this place all the **onto**/**auf**/**su**  are wrong because this is the SS240 and not the motorway A22.
same on the example in Bavaria.

some other solution can be to delete `ref` if `destination:ref` is present.
So the voice guidance is:
take second exit **_toward_** A22, Mori, Rovereto
without **onto** voice prompts, because not all intersections have a visible `ref` sing(example [Italy](https://www.google.at/maps/@46.5943364,11.5279612,3a,26.8y,53.04h,90.29t/data=!3m6!1e1!3m4!1sUF3rB0R4RcInZbNJCC3Rvg!2e0!7i13312!8i6656), [France](https://www.google.at/maps/@44.833359,0.7067009,3a,26.1y,300.17h,87.98t/data=!3m7!1e1!3m5!1sRupnPAcAeYiI_J3fZWYpUA!2e0!5s20110401T000000!7i13312!8i6656))


A limit from about 2 or 3 for destination I think is ok.
Example for A99:
[Mapillary](https://www.mapillary.com/app/?focus=photo&lat=48.01876064&lng=11.66307458&z=17&pKey=xrWmz2hLZtguJvEQn5WILQ&menu=false)
[OSM](http://www.openstreetmap.org/way/145035982)
`turn slightly right toward A99, Nürnberg, Stuttgart` I think is enough. `Messe/ICM, München` can be cancelled from the OsmAnd map. First 2 or 3 from destination are the first/second from above.

**Comment by sonora** [comment]
Let me re-open this, I guess you at least half way convinced me that we should improve here.

I will need to find some time to investigate, but I guess a rule set could be guided along the following principles:
- `destination:ref` must linguistically be treated like a destination, not like a `ref`
- Therefore we may have to concatenate `destination:ref` with `", "destination`, as you suggest
- In order to avoid too lengthy prompts, we may actually want to suppress `ref` where a `destination:ref` is present.

The 3rd rule would mean that we always consider `destination:ref` more valuable than `ref`, something which am not universally convinced of., but it may be true ... Feedback anybody?

**Comment by sonora** [comment]
Let's do this step by step. In the latest nightly I have implemented moving the `destination:ref` to the beginning of Destination field, which should fix the grammar problem originally stated in this issue.

Let's please test this thoroughly. Then we can decide whether to implement rule 4 from above, which I believe we will find highly necessary.

**Comment by polarbearing** [comment]
> Rule 4 would mean that we always consider destination:ref more valuable than ref

I'd say it is highly situation-dependent, in particular depending on the related signposting. When I approach a motorway A10 that leads to Frankfurt at this and to Hamburg the other side of the bridge, ``destination`` is more important. When I wait for a crossing with the B123, the ``destination:ref`` is more significant. Sometimes signs show only one of them, not both.

In summary, I'd see both ``destination`` and ``destination:ref`` equally important.

**Comment by sonora** [comment]
Let's please test as I have it now: I use the true `ref` now for the time being, but in addition added `destination:ref` before `destination` (unless it is identical with `ref`, which sometimes occurs).

**Comment by hakuchi** [comment]
Tested on the roundabouts in _Italy_ and _Germany_ and on _Kreuz München-Süd_, and for me it sounds good.

Also on different intersections with `ref`, `destination:ref`, `destination:lang:XX` and `destination` sounds good.
what I can see, nothing is broken with this modification.

**Comment by sonora** [comment]
You have not tried the latest nightly, I had already implemented this check.

**Comment by hakuchi** [comment]
Tested now some way with 2.5.0#15533D.

the Kreuz München-Süd(from A8 up to A99) sounds good, because this not have`ref`, only `destination:ref` and `destination`. So the destination is combined to "toward A99, Nürnberg".

Some other intersection give not correct voice prompts.
http://www.openstreetmap.org/way/65535918
On this intersection is `destination`, `ref` and `destination:ref` present.
So the voice prompts is:
turn slight right **_onto_** A 8 **toward** Salzburg
but it should be:
turn slight right **toward** A 8, Salzburg

http://www.openstreetmap.org/way/191501895
On this is only present `ref` and `destination:ref`.
Voice prompts is:
turn right **_onto_** A 94
but it should be:
turn right **toward** A 94

But on this two examples the `destination:ref`(**toward**) should be used, not the `ref`(**onto**)

**Comment by sonora** [comment]
From my testing, we got it functionally correct now.

What remains is the fact that we lengthen directions (displayed and announced) by including both `ref` and `destination:ref` (if present, and different).

While in most countries `destination:ref` is usually shown on the street signs (and when  `ref` is used should also be), some countries label as "`ref`" also street refs (for very small roads like community roads etc.) which are not commonly displayed or publicly used in directions.

I guess by common OSM rules they should really be tagged `unsigned_ref,` but it looks like common practice in some countries like Germany deviates.

Regarding your feedback on when both `ref` and `destination:ref` are present and identical: I see no reason why we would not announce `ref` then, it produces a comprehensive and still grammatically correct prompt. I have checked many of these situations and see nothing wrong with saying "Turn right onto A 94 toward Munich", in situations when you are e.g. on the overpass and turn onto the A 94 ramp. In situations where this is wrong, I would argue the tagging is wrong, `ref` must not be used in these cases.

**Comment by polarbearing** [comment]
> the destination:ref and ref not should be the same on a way

indeed that sounds like a tagging error. I remember cleaning ref tags from motorway links that were put on too generously, before destination:ref was properly introduced. 

>  I had already implemented this check.

the question is, should OsmAnd conceal the tagging error, or keep it obvious so people check the OSM data?

**Comment by sonora** [comment]
I guess we should really leave it as we have it now: In this fashion a ref tagging error, if any, has become detectable while at the same time we create no usability issue at all for our navigation functionality and users.

**Comment by hakuchi** [comment]
Why is this not working in the latest version(2.6.0) from PlayStore?
In the nightly version it works.

**Comment by vshcherb** [comment]
Thank you very much for your observation, looks like we uploaded 2.5 to Play Store instead of 2.6. We will fix it soon.
