### ISSUE TITLE
Overlapping menus (race condition)

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#3292]
- Start a route calculation
- Immediately click on a POI icon on the map

The result are overlapping menus.

(Found with OsmAnd+ 2.5.4.)
![screenshot_2016-11-23-10-45-36](https://cloud.githubusercontent.com/assets/6921696/20574060/083d525c-b1b3-11e6-9ac9-10f3ce80da85.png)

**Comment by Norbert80** [comment]
@vshcherb @crimean I still experience this bug with today's OsmAnd+ 2.6.1 release on Google Play.

**Comment by crimean** [comment]
@Norbert80 do you experience it with single or multiple menu?

**Comment by Norbert80** [comment]
@crimean 
![capture _2017-04-04-14-38-33](https://cloud.githubusercontent.com/assets/6921696/24658081/f23478f2-1948-11e7-9da7-b88fdd5a2424.png)

**Comment by Norbert80** [comment]
![capture _2017-04-04-14-43-45](https://cloud.githubusercontent.com/assets/6921696/24658122/0f7b9fe4-1949-11e7-9b75-3cb14a0e8c70.png)

**Comment by crimean** [comment]
Fixed

**Comment by Norbert80** [comment]
Commit?

**Comment by crimean** [comment]
https://github.com/osmandapp/Osmand/commit/ab95b5b71b364e029d8293949c490d3af55b7b23

**Comment by Norbert80** [comment]
Thanks!
