### ISSUE TITLE
Compass disappears

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#3294]
The Compass button, on the top left of the screen, when browsing the map view with 'North up' set, appears on app startup, and then disappears, not allowing to do the usual fast option (one tap) to change the view from North up, to compass, or following the direction of movement.

It only re-appears when screen is rotated?

**Comment by njohnston** [comment]
According to the [2.5 release notes](http://osmand.net/blog?id=osmand-2-5-released), this is a feature. Compass is hidden when the map is in "north up" view.

As explained in the release notes too, you can force the compass button to be displayed all the time by opening "Configure screen", scrolling to "Left panel" and enabling "Compass".

**Comment by Barrocas** [comment]
Ok, thanks for the info.

-- 
Cumprimentos,
D.er Hugo Barrocas
