### ISSUE TITLE
use junction=circular if needed

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#3298]
After a request from the OSRM folks and some discussion on the tagging list, ``junction=circular`` has been introduced, and tagged to those circular traffic installations in Berlin, that fail the roundabout definition. Read here which they are: Project-OSRM/osrm-backend#3361, and the [wiki page is here](https://wiki.openstreetmap.org/wiki/Tag:junction%3Dcircular).

I'd be willing to test newly implemented behaviour in Berlin. However please also read the discussion in the OSRM issue, that a user would need more lane support in those large circles than exit counting.

**Comment by hakuchi** [comment]
Today are only _13_ in the OSM database.
I found some wrongly tagged in other country's:
3 more in :de:
over 30 in :es: (a lot in Madrid)
over 40 in :ru:
30 in :it: 
30 in :fr:
20 in :netherlands:

So there can be around 150-200 non tagged as `junction=circular`


What voice guidance you think is the best? 
"turn right" or "**exit right**"
and if you drive left?
"turn left" or "make a u-turn" or "turn left and give way" or "**give way and turn left**"
(the **black** are my favorite)

**Comment by polarbearing** [comment]
> Today are only 13 in the OSM database.

Well the tag has just been introduced because it solves a particular problem. While the tag is used 51 times, some junctions have multiple segments, so your estimate might be right if you mean junctions. 

> I found some wrongly tagged in other country's

Fine, what do you mean by "wrongly tagged"? Non-roundabouts that are tagged roundabouts?
How did you find them?

> What voice guidance you think is the best?

Probably there is not one single answer to this question, it depends on the circumstances. I learned from what OSRM are doing, and still experimenting, that they apply heuristics to distinguish different situations. Criteria can be diameter and number of lanes. 

Both roundabouts and circular traffic range from small, residential situations, some easily to oversee as a driver, some going around a church; up to large, multi-lane situations, with lanes either circular or spiralling out. 

Have a look in the OSRM-issue cited above, there are a few more considerations.

**Comment by hakuchi** [comment]
> How did you find them?

about 40 roundabouts in Germany, they not ar mapped as `junction=circular`:

[circular.zip](https://github.com/osmandapp/Osmand/files/629880/circular.zip)

**Comment by xmd5a2** [comment]
Added entity_convert junction=circular => roundabout

**Comment by polarbearing** [comment]
@hakuchi 
> about 40 roundabouts in Germany, they not are mapped as junction=circular

Seems you misunderstand. There is a distinction between junction=roundabout and junction=circular. Take for example Ernst-Reuter-Pl in Berlin which you flagged in your GPX/Zip file (node 251106773 etc), which is a true roundabout since the ring traffic has priority. Thus it remains ```junction=roundabout```.

**Comment by vshcherb** [comment]
@polarbearing that's mostly driven by me. If I understand correctly, OsmAnd never displays road priority, so fix provided by @xmd5a2 is correct cause we will see a round junctions as a next turn.

Looking at the round junction simplifies navigation through these junctions very much cause you can count exits, especially in Paris. As a driver you should always look at "give a way" traffic signs anyway and on most of the junctions there are traffic lights.

**Comment by polarbearing** [comment]
thanks @vshcherb - yes we are in agreement here that both junction=roundabout+circular are very similar from the perspective of a driver, and the large ones have traffic lights anyway. That was the same problem that OSRM had, and that's why adding junction=circular was a good solution, and mappers apparently accepted it, with 458 uses today, just in a few months. (My previous comment was for hakuchi)

In the long run, users need help to start in the best lane, which either requires sophisticated algorithmic planning through the junction, or maybe a new tag. In Berlin, those large circles have a "spiralling out" lane system, so if you are able to pick the correct one before entering, you spiral out at exactly the exit you want without changing lanes.

**Comment by polarbearing** [comment]
ok so the [related commit](osmandapp/OsmAnd-resources/commit/8ace9c382b1a8aefa234c360768beae23453f93b) is in OsmAnd-resources/obf_creation, so I conclude we need a new map to test this?

**Comment by vshcherb** [comment]
yes new map will be needed but don't expect much it will look exactly as 2 years ago before introduction junction=circular (I'm referring to Paris, cause many junctions transformed to this mapping scheme).

**Comment by polarbearing** [comment]
Confirming that my major junction=circular here in Berlin now behaves as roundabout with exit counting. 
I'm going to propose a tagging scheme that might allow to give lane advise in conjunction with exit counting over the next days.
