### ISSUE TITLE
Separate emergency department from emergency infrastructure

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#3299]
How to reproduce: Have a little accident, and get somebody to drive you to the next hospital with an A/E-department. 

Go to Search->Categories (or Legacy Search->POI) -> Emergency.

Get a list of hundreds of Fire Hydrants, some Emergency Phones, a few voluntary fire brigades, water police, an ambulance car depot, the list is endless. No hospital with A/E to find between the clutter.

Try -> Healthcare.

Get Doctors, Dentists, Pharmacies, a rehabilitation clinic, social facilities (why is the clothing depot, an asylum and a senior residence under healthcare?), physiotherapists, vets, a geriatric clinic, etc. 

The next real hospital with A/E would have been in 10,2 km distance, imagine through how much irrelevant stuff I'd have to scroll. 

**Proposal:** Separate all the hydrants and fire brigades as "_emergency infrastructure_" from the manned departments you'd expect to provide direct assistance 24/7, such as A/E-Hospitals and police stations, as "_emergency departments_" or "_accidents/emergencies/police_" or similar. 

![screenshot_20161126-022522](https://cloud.githubusercontent.com/assets/8266355/20637211/f2a3f9e0-b37f-11e6-8554-0d9e581a8ee4.png)

osmand: todays nightly, however it's a long running problem

**Comment by xmd5a2** [comment]
Agree. Fixed https://github.com/osmandapp/OsmAnd-resources/commit/c6f98cb322a32953ffecf0281a97d2504fccf031

**Comment by polarbearing** [comment]
Thanks. Indeed there are less hydrants in the "Emergency" category. However I cannot see an "Emergency infrastructure" category in the search menu. 

I installed today's nightly (Dec 13) and checked my files. I do have 
```275914 2016-12-11 11:09 poi_types.xml```
which contains
```<poi_category name="emergency_infrastructure" default_tag="emergency" excluded_poi_additional_category="wheelchair_accessibility,fee,payment_type,internet_access_type,opening_hours">```

**Comment by polarbearing** [comment]
should we re-open or make a separate issue?

**Comment by xmd5a2** [comment]
I see no point to add "Emergency infrastructure" to top of categories list (search - categories). However it is accessible via search and custom category filters.

**Comment by polarbearing** [comment]
Thanks for the explanation, I fully agree.
