### ISSUE TITLE
OsmAnd Live Routing: Tag "destination" not included 

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/Osmand#3300]
I have tagged a lot of destinations. But it seems they're not included in osm live.
I would be nice to have them.

Greetings Simon
#19353m

**Comment by vshcherb** [comment]
Possibly you need to enable Routing for OSM Live, it is in early development stage.

**Comment by jf-simon** [comment]
Was enabled.

**Comment by CJTmmr** [comment]
I also have OSM Live enabled for Routing (in development plugin)
In my experience newly mapped roads etc. (mapped after last monthly map-update) are correctly rendered with the daily OSM-Live Update.
But they are never used for routing. Routing also uses roads that where deleted since last montly map update.

About one year ago routing did actually use the OSM Live Updates.
I think it stopped, when the setting "Use OSM Live for routing" was introduced in Development Plugin.

**Comment by vshcherb** [comment]
Could you please send example of region and place edit?

**Comment by CJTmmr** [comment]
Using latest nightly: OsmAndF~ 2.5#15590D and OsmAnd offline routing, car profile.
Map: Netherland.obf, dated 01-12-2016 
With OSM Live Updates: date 09-12-2016 00:30
In Dev.Plugin: OSM Live Navigation is enabled

Example on [this location:](http://www.openstreetmap.org/#map=17/52.07727/5.47896)

This is what is looked like on 01-12-2016:
![2016-12-09 20 40 39](https://cloud.githubusercontent.com/assets/15076257/21064033/060dd922-be59-11e6-9839-9f384942d90a.png)

New buildings and streets [Heijhorst]  were mapped on 07-12-2016:
They are rendering okay in OsmAnd:
![2016-12-09 19 13 12](https://cloud.githubusercontent.com/assets/15076257/21064042/0f95df08-be59-11e6-80be-0c0d94f6d473.png)


But routing is still using the old street (the "loop", which is no longer present), and not using the new streets.

An other example on [this location:](http://www.openstreetmap.org/#map=18/52.15313/4.53039)
This is what it used to be on 5th Dec:
![2016-12-09 20 39 19](https://cloud.githubusercontent.com/assets/15076257/21064050/1d473a8e-be59-11e6-8c8f-bb544c3e3d0d.png)

On Dec 8th new buildings and streets (Leithonpark) were added:
Way IDs: [458464544](http://www.openstreetmap.org/way/458464544); [458464547](http://www.openstreetmap.org/way/458464547)

They are rendering perfect in OsmAnd:
![2016-12-09 19 14 42](https://cloud.githubusercontent.com/assets/15076257/21063488/20c5f8f6-be56-11e6-9b1b-d84f982317fc.png)
But routing will not go into the new streets.

Good Luck and Thanks
Kees-Jan

**Comment by skylerbunny** [comment]
I suspect the same thing is true with the 'maxspeed' tag when routing along a way. It's hard for me to describe the mechanism, but I think if the only update to a way is the addition of 'maxspeed', that speed isn't used in routing that uses osm-live. If OTHER things are changed (such as the number of nodes in the way), then that's sufficient to trigger a "change" to the way in osm-live's eyes, meaning it will show that maxspeed when navigating along the way.

**Comment by vshcherb** [comment]
The original issue is rather old because too many things has changed if the issue appears please take a note of existing maps and coordinates
