### ISSUE TITLE
Restaurant filtering

### ISSUE THREAD

**Issue by FTno** [osmandapp/Osmand#3302]
Search and filter

Filtering for Diet Vegetarian lists only restaurants with the OSM tags 'diet:vegetarian yes' and 'diet:vegetarian only'. It would be nice if restaurants with the OSM tags 'diet:vegetarian few' and 'diet:vegetarian few (own menu chapter)' were listed too.

Osmand 2.5.4 and with offline maps updated this month. (Android 4.2.2)

**Comment by xmd5a2** [comment]
diet:vegetarian=few is internally converted to diet:vegetarian=yes. Is there a difference in practical application between "yes" and "few"?

**Comment by FTno** [comment]
Here are some examples of nearby restaurants with the OSM tags 'diet:vegetarian few' and 'diet:vegetarian few (own menu chapter)':

With 'diet:vegetarian few':
http://www.openstreetmap.org/#map=19/27.75922/-15.57475 (Look for Fusion Restaurant & Loungebar)
http://www.openstreetmap.org/#map=19/27.75736/-15.57929 (Dayana)

With 'diet:vegetarian few (own menu chapter)':
http://www.openstreetmap.org/#map=19/27.75922/-15.57475 (Gasthaus Atlantis)
http://www.openstreetmap.org/#map=19/27.75036/-15.57714 (Golden Bamboo)

When I try to filter with diet vegetarian neither of these are listed. The only restaurant that is filtered and listed in the area is Maharaja Palace (http://www.openstreetmap.org/#map=19/27.75898/-15.57644) and it has the tag 'diet:vegetarian yes'.

'diet:vegetarian few' and 'diet:vegetarian few (own menu chapter)' are rather new OSM tags and give more precise information than the yes tag, and that is why I, some time ago, modified the tags for the mentioned restaurants and many more from yes to one of the two few variants.

**Comment by xmd5a2** [comment]
Added diet:vegetarian=few to poi filters and context menu. Will work with december maps and nightly.
