### ISSUE TITLE
Allow navigation without sound information 

### ISSUE THREAD

**Issue by HolgerJeromin** [osmandapp/Osmand#3303]
I have listened to music and wanted to have osmand navigation only on screen for osm debugging (lanes) active. 
I found no way to deactivate navigation sound. 
I even selected no speech output (none instead of German or TTS German) in global settings. 

But Osmand used the last used language and interrupted the music. 

Thanks for the great software 
OsmAnd + 2.5.4

**Comment by sonora** [comment]
Strange, I have just tested and find no flaw.

Please understand that the setting is profile dependent, i.e. you can set it different per transport mode (car/bicycle/pedestrian).

The easiest way to set it is on the route configuration dialog (the popup menu where you can set start and destination points): Tap the little settings "gear wheel" icon near bottom-center. On the pop-up menu, you can either toggle the switch in the very first line (Sound=ON/OFF), or you can in deed in the second line select "Voice guidance = Do not use".  Either one works for me. Not for you, you say??

**Comment by HolgerJeromin** [comment]
Thanks for your answer. Strange. 

Note that the setting (none instead of German or TTS German) is also in the main setting, so not profile independent. Thanks for the hint of the quick settings. 

Right now osmand works here as expected but I have no Bluetooth audio connected and have no movement. Will retry later.

**Comment by sonora** [comment]
Apologies, I was mistaken: It is in deed a global setting, it seems, and whatever you select in the route setup's quick settings should be  synchronized with the global setting (and vice versa). I will leave the issue open for you to double-check, but still cannot reproduce, I am afraid.
