### ISSUE TITLE
Vending machine name should include type

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/Osmand#3305]
All vending machines are displayed as _Vending machine_ if i tap on the POI

I think the vending type should be displayed, because so I see on first tap what there is vended.

Example:
http://www.openstreetmap.org/node/4268599855

First tap
![first](http://img5.fotos-hochladen.net/uploads/screenshot2016mij08zn54b.png)

have to open description
![second](http://img5.fotos-hochladen.net/uploads/screenshot2016nr9mwsict3.png)

**Comment by xmd5a2** [comment]
Don't agree. Some vending types are very long: "public_transport_tickets","public_transport_plans"

**Comment by Norbert80** [comment]
I don't agree too. I think it is possible to search for or filter vending type. This should be enough.
