### ISSUE TITLE
Problems with german translations

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/Osmand#3306]
The German language use capital letters, but OsmAnd not use same letters as in Weblate

Examples:

this should be: `Verkaufsart: Souvenier-Münze`
![1](http://img5.fotos-hochladen.net/uploads/screenshot2016gzxw40lqhf.png)    

this should be: `Religion: Christentum`
![2](http://www.fotos-hochladen.net/uploads/screenshot20165tyjr1l7v9.png)    

this should be: `Zahlungsart: Münzen`and `Verkaufsart: Zigaretten`
![3](http://img5.fotos-hochladen.net/uploads/screenshot2016wj4mg9ufe3.png)

**Comment by sonora** [comment]
I think this should fix it: https://github.com/osmandapp/Osmand/commit/9d39ff61530013398ab216a25feeee7c486de692, could you please double-check with latest nightly?

I am not sure why we forced lower case there. Also in English you would not categorically use lower case after a colon (although more so in British than in American English). In any case, I think unconditionally forcing to lower case after the colon was a bug, as your examples show.

**Comment by sonora** [comment]
Just tested, from what I see it is fixed.

With my fix in place now the capitalization present in the localized resource files is obeyed. I think this is the best way to handle it and caters for all languages.
