### ISSUE TITLE
The "Map orientation mode" button disappears when I tap on a POI, but only in "North up" mode.

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#3308]
I noticed this issue in the latest nightly (OsmAnd~ 2.5.0#19402M). 
But it could have been present earlier also.

The problem is that the "Map orientation mode" button disappears when I tap on a POI on the map. But this happens only when the map is in "North up" mode. (not in "compass" mode or in "direction of movement" mode).

As soon as I tap on a POI (e.g. ATM, shop, restaurant...), the button disappears. It does not re-appear. To make it re-appear, I have to either turn the map (with two-finger gesture) or re-start OsmAnd.

Sometimes the "North up" button does not disappear when I tap. But it disappears when I tap on the three-dotted "grippy" button of the POI's card (to swipe down the card). When the card goes down, the "North up" icon also disappears.

I have not found the conditions when this latter effect happens.

**Comment by sonora** [comment]
I guess this is by design, because we now have a setting "Compass" under "Configure screen" which controls exactly tis behavior (?).

**Comment by Barrocas** [comment]
Hi, it's the same as this:

Compass disappears #3294

-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by raindropsfromsky** [comment]
Well, on the surface this looks like a nice feature. But if I want to
change the map orientation mode, I cannot do it easily, because the button
itself is missing. So first I have to activate it by turning the map, and
then tap it. This is not intuitive.

Secondly, why remove this button only in "North up" mode? In fact, when the
navigation is on, the blue arrowhead on the purple route line makes it even
more obvious that the map is in "in direction of movement" mode. Still
OsmAnd keeps displaying it.

In fact, I would suggest a better idea: Hide all buttons after a while. To
make them visible, the user taps anywhere on the screen.
This trick is universally used by all video players on all devices (PC,
laptops, phones, tablets) on all OSs (Android, IOS, Windows, Linux).

**Comment by raindropsfromsky** [comment]
Even after the orientation button is hid, as many as 8 buttons still left
on the screen!
So, by hiding them all, the user gets an immersive experience of OsmAnd.
At the same time, all these buttons are just a tap away. (does not need a
twist)

**Comment by sonora** [comment]
So I guess we are ultimately talking about #2551, let me merge it there. Thx!

**Comment by raindropsfromsky** [comment]
Ok, thanks! I have copied the point in that issue.

My only concern is, it may be easier to hide the buttons using the same trick that is used currently for only one button. On the other hand, a full-screen display may need new coding, and therefore the whole combined project may be deferred. 

So wouldn't it be best to keep them separate and implement them independently, in their own time-frames?
