### ISSUE TITLE
[Feature request] Voice guidance improvement

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#3309]
Example from our user: when driving down the road 1, you do not get the voice guidance to turn right, thus, there's a risk of driving into the oncoming traffic (road 2). Request: give voice prompts on the turns even when there's only one way to go.
![rsz_screenshot_2016-10-13-17-15-04](https://cloud.githubusercontent.com/assets/12711814/20715202/157906f2-b657-11e6-8242-e8a8d3e4efd6.jpg)

**Comment by annasoloviova** [comment]
Also, they have asked to make traffic signs seen from 100m, not 30-50.

**Comment by hakuchi** [comment]
For me this crossing no need any voice guidance.
If we add to all crossings a voice guidance, we will have a never stopping voice.

So we have "turn right"/"turn slight right" on a lot of roundabouts like this:
https://www.openstreetmap.org/node/293839350 
or
https://www.openstreetmap.org/node/597820138

Also on a lot of intersections like this:
https://www.openstreetmap.org/node/1580036588
or
https://www.openstreetmap.org/node/939104023

**Comment by vshcherb** [comment]
I would close that issue because (2) road is oneway road, so it should a big sign that forbids movement in that direction. Our voice guidance relies on this so it doesn't give "extra" voice navigation. So without oneway road, I would expect voice prompt here.

**Comment by sonora** [comment]
Yes, exactly true. I see no simple action here to change things.
