### ISSUE TITLE
When GPS location is not available, show a gray circle for "My position" in Directions dialog 

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#3310]
In the **Directions** dialog, OsmAnd shows a light blue circle icon for "My position" point.
This display does not change even when the GPS reading is not available.
Only when the user presses "Go", OsmAnd produces an error: "position not yet known".

Instead, let the user know beforehand about this issue, by showing a gray circle icon instead of blue.
This is the standard trick used by Google map also.

The same holds true for the "Waypoints" dialog also.

**Comment by Chumva** [comment]
Possible duplicate https://github.com/osmandapp/Osmand/issues/7737. This issue was fixed here https://github.com/osmandapp/Osmand/commit/c4eceebe1e1f8cba6028861618f6918450a74ef8.
