### ISSUE TITLE
Add icons to the "You have already set a destination" dialog

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#3311]
All the menus of OsmAnd have icons, which help in instant cognition of the function. 
(The reader does not have to read the text).

The only notable exception is the **You have already set a destination** dialog.
(The dialog that pops up when we add a point to a route.)

Here, the text is long and confusing, and yet it does not have any icons.
As a result, the user has to read each option carefully and work out what it means.

It could not be rephrased because the more intuitive words are locked as keywords.
So an easy workaround is to provide buttons that graphically show each function!

I can provide sketches or even icons if needed (please let me know).

**Comment by Chumva** [comment]
This alert dialog was replaced with a bottom sheet that has all the necessary icons.
https://github.com/osmandapp/Osmand/blame/master/OsmAnd/src/net/osmand/plus/dialogs/AddWaypointBottomSheetDialogFragment.java
