### ISSUE TITLE
[Feature Request] Automatic maps management for offline navigation

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#3312]
Request from our user: make app automatically offer the maps necessary for a route.

The scenario:

The user chooses offline navigation from current the location to 
target location X. 
If any offline maps required for the requested navigation are missing, 
they get notified with a listing of the missing maps, suggesting to  download them.

**Comment by Norbert80** [comment]
Maps.me is excellent in this case.

**Comment by sonora** [comment]
Related: #2525 .

**Comment by sonora** [comment]
'In any case it could only be done by some guesswork (you can as well do manually), because as long as you do not have a map, no algorithm can be certain if it would contain a better route or not :)
