### ISSUE TITLE
Navigation notifications don't get sent to Pebble smartwatch

### ISSUE THREAD

**Issue by arwk** [osmandapp/OsmAnd#3313]
Hi!
I was happy when I realized that the last Osmand updates included notifications for the current navigation action.
I thought this would mean that every navigation-instruction gets automatically sent to my Pebble smartwatch (As most of the "other" notification do).
However the Pebble App does not send the Osmand navigation-notifications.
Is this a intended behaviour?
If so, it would be nice to have an option to change the type of notification Osmand creates.
(It seems as if there are two - or maybe more - types of notifications). Perhaps it has to to do with the fact that the Osmand notifications get frequently updated, whereas most "regular" notification don't.
Please tell me, if this a problem to be solved in Osmand itself, or if the Pebble app has to change its behaviour.
Thanks!

**Comment by vshcherb** [comment]
We did some fixes for Android Wear, possibly Pebble app will be able to process them as well.

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/12932
