### ISSUE TITLE
highway=corridor better rendering

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/Osmand#3315]
In OsmAnd the `highway=corridor` looks like a `highway=service` with `tunnel=yes`.
Sometimes this is confusing, when inside the mall is also a garage with service road.

can we change this to a thin white line?
http://www.openstreetmap.org/way/377901309
![pic 1](http://img5.fotos-hochladen.net/uploads/screenshot2016o2vpx5jgbk.png)

**Comment by xmd5a2** [comment]
The picture does not open (not found)

**Comment by hakuchi** [comment]
Updated picture

**Comment by d1g** [comment]
If you open history of `highway=corridor` (first tag in ~2012) in http://taghistory.raifer.tech/ there would be 2 spikes down in April and July of 2016. Corresponding talk at https://github.com/gravitystorm/openstreetmap-carto/issues/2332

@hakuchi `indoor=corridor` is a more recent tagging approach (proposal in 2014, first tag~2015), see https://github.com/gravitystorm/openstreetmap-carto/issues/2332#issuecomment-247737225

**Comment by hakuchi** [comment]
the best way to solve this, I think is changing _service_ to _footway_

![pic 2](http://img5.fotos-hochladen.net/uploads/screenshot20163056u7ysvg.png)
