### ISSUE TITLE
Displaying road ref=* tag according to the language.

### ISSUE THREAD

**Issue by BoFFire** [osmandapp/Osmand#3317]
Hi, OSMAnd dev team :)
Actually, we (OSMAlgeria) installed a tile server on which we are trying multilinguism.
We would like to know if it is possible when switching OSMAnd to a specific language to have the ref=* tag of the roads switching to the same map language. If not fallback to generic latin ref=*
For example, if I choose arabic, then the shields of the roads will be displayed and may be voiced in arabic.
And if there us no arabic on ref:ar=* will fallback to ref=* if exists.
Examples :
http://image.noelshack.com/fichiers/2016/48/1480804526-screenshot-2016-12-03-23-31-33-1.png

http://image.noelshack.com/fichiers/2016/48/1480804521-screenshot-2016-12-03-23-31-41-1.png

http://image.noelshack.com/fichiers/2016/48/1480804533-screenshot-2016-12-03-23-31-27-1.png

Thank you.

**Comment by sonora** [comment]
For reference: Looks like we are talking about e.g. http://www.openstreetmap.org/way/434883636, which seems to have 3 language-specific tags `ref=RN 12`, `ref:ar=طو 12` , `ref:ber=ⴰⴰ 12`, plus `ref:colour`, etc. 

Yes, it seems that currently our code supports showing names in the language you have selected as "Map language" in OsmAnd's "Configure Map" menu (using `name:XX` when present and falling back to just `name` where not). But apparently we do not do this for `ref` (or the more navigation related tagging like `destination:ref` or `destination:ref:forward`, etc.)

I currently have no good estimate for the effort to implement this, it may perhaps be significant.

**Comment by BoFFire** [comment]
Hi @sonora we are not in a hurry :). Tell me which on which file to betatest the changes. Tag ref:xx only for a test display.
Have a nice day.

**Comment by sonora** [comment]
Ok, I have just put some work in and produced this commit: https://github.com/osmandapp/Osmand/commit/ba04890f443f9e8c533b9b3c8d001e815d5b6f74. With this we treat `getRef` in analogy of how we treat `getName` (but from my testing this is not enough).

@vshcherb , @xmd5a2 : I have 3 things here I am currently not clear about.

(1) Do we include `ref:XX` in our map files at all? (`names:xx` on highways seems to work ok, you can test with e.g. http://www.openstreetmap.org/way/354118151, but ref:XX still open)

(2) Are the functions `getRef` and `getName` in RouteDataObject.java also used for rendering the map, or do we need some extra work elsewhere?

(3) I am not sure if in BinaryMapRouteReaderAdapter line `} else if (tags.equals("ref")) {` needs a modification. If yes, then the line above `if (tags.equals("name")) {` has the same issue (and always had).

I guess with looking at these 3 open points we could now fix this issue.

**Comment by BoFFire** [comment]
I'm ready to test :).
Thank you very much !

**Comment by sonora** [comment]
My work is in the latest nightly build. But from what I see, it works only for names:XX, not yet for ref:XX. (Neither in map rendering nor in the navigation instructions, hence I think we may not yet have ref:XX tags contained in our offline map files.)

**Comment by BoFFire** [comment]
Thank you again @sonora for the feed back. I'm upgrading nightly to test ;)

**Comment by vshcherb** [comment]
To be honest I'm very surprised about ref:XX and not sure how much we should invest in support. The issue that >90% refs are letter+number. I believe we should do something in entity convert during map preparation... though I'm not sure what exactly.

**Comment by vshcherb** [comment]
In this specific issue I would follow ground truth, so the user should see what is visible in reality. If both are displayed then both should be visible

**Comment by BoFFire** [comment]
Hi @vshcherb @sonora,
I have made some tests and It seems that only the shield on the highway still in latin chars when switching map language.
Look at the top banner of the navigation mode on these examples :
Link 1 : http://image.noelshack.com/fichiers/2016/49/1481165888-img-8bxi90.jpg

Link 2 : http://image.noelshack.com/fichiers/2016/49/1481165887-img-s6lba6.jpg

And on link 3, the name of the way (if any) matches perfectly the language map choosen by the user, top banner too, exception on the shield highway ^-^
Should it or not be in the same lang, I don't know. May be as you said @vshcherb, following ground truth :)

Link 3 : http://image.noelshack.com/fichiers/2016/49/1481165886-img-v4iw41.jpg
Salutations amicales.

**Comment by sonora** [comment]
@vshcherb Victor, yes, I was a little surprised too at first, any I guess one could argue that `ref` is what is written on the highway signs, not translatable.

But then I learned people do actually use `ref:XX` tagging. While I agree I do not fully understand the purpose: Supporting it is not very difficult, because it should be done in perfect code analogy to treating `name:XX,` and that is exactly what my commit does. Seems all we have to do is implement the `name:XX` analogy also in the rendering engine(s)?

**Comment by sonora** [comment]
@BoFFire : Re-reading your comment above: It sounds like you are suggesting I have already done the trick, and we should leave it as it is now, where the map always shows `ref`, and only all other text honors `ref:XX` ?

**Comment by BoFFire** [comment]
@sonora yes the changes you've made are okay for the moment. ref:xx (if it exists) is displayed visually and voiceable if adequate tts is choosen by the user. Nice job ! :)
Actually, ref:xx came when I was trying checkautopista2 to correct some exit_to and destination:ref (read destination:ref:xx ;) too). And I saw the shields generated like in the real world.
I'm not sure about the extent of the use of ref:xx on primary and secondary highways (I'll check it on OSM taginfo) but having "something internationally flexible to inclusion not exclusion" is a good thing :)
Can we consider the present issue closed for now ?

**Comment by sonora** [comment]
@BoFFire : Thanks!
@vshcherb : I think with the comments above we can leave my commit in place, and consider this issue closed for now, looks like we have the best compromise with not changing the map display but having `ref:(lang)` support in all text/voice fields, do you agree?

**Comment by vshcherb** [comment]
@sonora Good job! :)
