### ISSUE TITLE
[Feature Request] Settings: Hide Buttons

### ISSUE THREAD

**Issue by Thunichgud** [osmandapp/Osmand#3318]
- There should be an option in the settings to hide the Zoom+ and the Zoom- buttons. They are not needed, because zooming in and out is possible by using two fingers. Hiding them frees the screen.
- There should be options in the settings to hide the search button, the map profile button, the navigation button. For many people it is enough to start these functions from the menu.
- There should be an option to hide the menu button. On most devices the menu could be opened by the hardware menu button.
The screen is full of obligatory but unneccessary buttons !!

**Comment by sonora** [comment]
Maybe we should think about simply offering one optipn to have a fullscreen mode, where all these buttons would automatically disappear after a few seconds until the screen is touched again (similar to how we do it in the navigation mode)? We have always had a number of similar requests over the years.

**Comment by sonora** [comment]
I'd say let us merge this into #2551.

**Comment by Thunichgud** [comment]
Sonora wrote:
"Maybe we should think about simply offering one optipn to have a fullscreen mode, where all these buttons would automatically disappear after a few seconds until the screen is touched again (similar to how we do it in the navigation mode)? We have always had a number of similar requests over the years."

This is not an appropriate solution ! When I use two fingers for zooming in or out or when I move the map by my finger or I touch the screen by mistake, the buttons will appear. Very ugly !

**Comment by polarbearing** [comment]
> Zoom+ and the Zoom- buttons. They are not needed, because zooming in and out is possible by using two fingers

Disagree here. It might be possible with the squeeze gesture, but while driving I would prefer the buttons. Squeeze gesture is more distracting then a simple one-finger touch.

**Comment by Thunichgud** [comment]
polarbearing wrote:
"Disagree here. It might be possible with the squeeze gesture, but while driving I would prefer the buttons. Squeeze gesture is more distracting then a simple one-finger touch."

You are right, polarbearing. Because of that I prefer a settings option to hide or unhide the buttons. So everybody can decide by himself if he wants to see the buttons or not. The settings method is much better, than the automatic full screen method.

>

**Comment by raindropsfromsky** [comment]
IINW the user can exit the **immersive full screen** mode with a simple sweep from top. Is that not sufficient?

**Comment by AlexBlack772** [comment]
It's been so many years, the program has a lot of features for anything, but why is there no option to hide unnecessary buttons from the screen?

I don't use navigation at all, but this button is always on the screen. Please give us an option to hide every button on the screen independently as it is done for "Compass" and "3D" buttons

**Comment by Chumva** [comment]
@AlexBlack772 in new beta this option to hide buttons on screen should be available

**Comment by AlexBlack772** [comment]
Grean news, thank you, when can we expect to see this version in the app store (iOS)? I mean the regular version, not the testflight version.

**Comment by AlexBlack772** [comment]
I've updated to version 5.0 on IOS, and still have no option to hide navigation button, is any chance that this feature will be available in IOS ?
