### ISSUE TITLE
Noto font on OSMAnd

### ISSUE THREAD

**Issue by BoFFire** [osmandapp/Osmand#3320]
Hi,
This is not an issue but a font test for fun :
https://twitter.com/BoFFire/status/805363999927889920

About Noto fonts : https://en.wikipedia.org/wiki/Noto_fonts
(fr) version of the article : https://fr.wikipedia.org/wiki/Noto_(police_d'%C3%A9criture)
Licence : SIL Open Font License
Noto supporting "Tifinagh" script by the way which is `name:ber` or `name:zgh` in both Algeria and Morocco.
Link : https://fontinfo.opensuse.org/fonts/NotoSansTifinaghRegular.html

And with Noto fonts, bye bye squares even on `name:kab` ;) :+1:
Example : http://image.noelshack.com/fichiers/2016/48/1480853329-screenshot-2016-12-04-13-01-20.png
Salutations amicales.

**Comment by vshcherb** [comment]
Sounds good! Indeed main issue is that OsmAnd could write a label only from 1 font file. So if file contains chinese glyphs and doesn't contain digit, the font will be used but the digits won't be visible and so on.

We will plan soon to use custom fonts without change device fonts, it will be a workaround but it will be much handier to test and in future we could provide workaround for specific fonts by embedding them into OsmAnd or providing as downloads.

Closed in favor of related issue https://github.com/osmandapp/Osmand/issues/1161
