### ISSUE TITLE
River names and direction arrows are too prominent at night

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#3324]
See the attached screenshots:

![](https://cloud.githubusercontent.com/assets/982338/20886007/f81e89dc-bada-11e6-8fa2-356107480914.png)
![](https://cloud.githubusercontent.com/assets/982338/20886009/f858f3a6-bada-11e6-8b9b-713d8d90194d.png)

The river names and direction arrows are too light for the night mode. They should use a darker blue color.

**Comment by hakuchi** [comment]
I think for foot navigation this is OK, but for car navigation I agree with naoliv

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/06cb78aacaae90bda44b3d31de894c42805f9ad2
