### ISSUE TITLE
[Feature request]Add "hide planned future streets" to hiding selections

### ISSUE THREAD

**Issue by harvey637** [osmandapp/Osmand#3330]
Hi,
driving is a task, where one should avoid too much distraction.

Sometimes, especially in areas with a lot of planned new roads and buildings the map
gets really unreadable, cluttered with "planned roads".

Please allow them to be hidden, a menu already exists to hide other map items.
Thx

**Comment by sonora** [comment]
I guess we could also just hide them by default in the car profile, it may suffice and we save an additional setting?

**Comment by hakuchi** [comment]
And if I activate "additional details" in settings they can become visible again on the map.

**Comment by vshcherb** [comment]
I think planned should be hidden but not the streets under construction cause they help to understand current situation

**Comment by sonora** [comment]
@vshcherb , @xmd5a2  Yes, certainly, construction is very important! In Touring view I actually even accentuate "construction" much better (orange-white) than in the default renderer, because it is like a warning.

Maybe the solution we have in Touring view for "planned" can also be the solution idea here: Maybe we should simply render "planned" much much fainter (transparent grey, etc.). (Have not checked how it looks in default today, maybe it is simply too pronounced?)

**Comment by harvey637** [comment]
Agreed, constructions - like actual roadwork with trafficjams, temporary semaphores, special speed limits and modified roadwidth - are important to the driver (or the algorithems as penalty). 
They should be visable, may be even epmhasized.

On the other hand, planned roads - nothing visable in real life other than disscussions in the newspaper -
should be hidable in normal driving mode. There are already eight items hidable like borders, areas, buildings, etc. Is it hard work to add "planned objects" to this list? Or there is this details menu. If you
make street lightning configurable (which might be of interest in some situation), what about this menu
to configure "planned roads"?
planned Roads != under Construction

**Comment by xmd5a2** [comment]
Option "Configure map" - "Details" - "Hide proposed objects" hides highway=proposed too. @harvey637 is it what you need?

**Comment by harvey637** [comment]
yes, that sounds great. but not yet finished in nightly 19506? Ill try when I see it in nightlies. Thx.

**Comment by harvey637** [comment]
upps, al little bit to fast with closing :-)

**Comment by xmd5a2** [comment]
This option was introduced around half year ago

**Comment by harvey637** [comment]
great - will test in a few minutes. bye the way, the german translation "vorgeschlagene Objekte" is a bit misleading (as  may the english version also?) Proposed means "hey, take a lot at this, this is something you should see, it is great" - as in "10 countries to see before you get 70" or "other people suggested this". The objects in my issue (and what is hopefully configurable by now) is more "planned", in german "Objekte in Planung"  or "geplante Objekte".
Im not quite shure if the english "proposed" is the best wording, but im not native toungue in english.
May be it is perfect, but the german is sounds more like "suggested" :-)

**Comment by harvey637** [comment]
Hmmm, I changed into english, but only see 
- more details
- show road surface
- show road quality
- show access restrictions and toll
- Color code buildings by type
- street lightning
- OSM mapper assistent
but there is no "hide proposed objets" - am I looking at the wrong place?

**Comment by xmd5a2** [comment]
Yes, I meant "Configure map" - "Hide" category

**Comment by harvey637** [comment]
found it -  WORKS PERECT!
now I can close this issue.

**Comment by hakuchi** [comment]
@harvey637 fixed yesterday German translation. On the next update it will be fixed.
