### ISSUE TITLE
Missing "Use location" menu item

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#3331]
Hi,

in recent builds (OsmAnd+ 2 5.4) I am missing the "Use location" menu item. Has it been removed intentionally? If yes I vote for re-adding this item.
An alternative solution would be an implemenation similar to MAPS.ME. There a use location function is triggered by just clicking on the position arrow. I consider this an intuitive solution.

Best Regards,
Norbert

**Comment by njohnston** [comment]
sonora commented on this on a [separate issue](https://github.com/osmandapp/Osmand/issues/3272#issuecomment-261790515).

To summarise, you can tap the current position indicator. On the context menu you can then add a favourite or marker from the current location, or press the three dots button for more actions.

**Comment by Norbert80** [comment]
@sonora do you talk about very fresh development builds?

**Comment by Norbert80** [comment]
@sonora: Thanks for the information. I see this already works as requested in OsmAnd. Sorry for the confusion. Please close this issue.

**Comment by sonora** [comment]
Yes I know, it s a little paradigm change, but now with the fully interactive maps we have I guess that mid term it is even more intuitive like we have it now, the "Use location" menu was really just an interim solution.
