### ISSUE TITLE
Offline routing bug (regression)

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#3334]
The following report...
https://code.google.com/archive/p/osmand/issues/2580
...describes a bug that in OsmAnd 1.9.5 only has been triggered for certain starting points (that triggered the two-phase-routing bug #3023).

Now the situation on that scenario has become  worse with OsmAnd+ 2.4.6 build. Now OsmAnd ALWAYS chooses the bad route. Since all other OSM based routing services still and always  choose the good route on that scenario a change to the OsmAnd (offline) router seems to cause this degradation of OsmAnd's routing results.

**Comment by Norbert80** [comment]
@sonora @vshcherb Would you please comment on this issue?

**Comment by vshcherb** [comment]
It is fixed by this https://github.com/osmandapp/Osmand/issues/1195. Not sure if I see your point.

**Comment by Norbert80** [comment]
@vshcherb why do you close an issue while assuming to "not see the point".

I agree to keep this one closed. I did not notice that there is already an Github version files: #1195

**Comment by Norbert80** [comment]
Because this one has been closed, I needed to file a new one: #3368
