### ISSUE TITLE
Traffic warning priority

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#3335]
I was observing that _occasionally_ some known rail or pedestrian crossing were not announced. My first suspicion, that it could be navigation vs. non-navigation mode, appeared not to be the reason. 

In a current observation, a crossing was not announced while the speed limit warning was on. 

Could we please check what the priority order is for the warnings?

I'd say a warning about a spot hazard (rail/ped crossings, speed cam, stop, bumps) should temporally override active way hazards (speed limit).

**Comment by sonora** [comment]
Preliminary, I am pulling this off my memory without reviewing our code, but I think the current priority order is this (as far as is enabled):

1. Warnings
2. POI
3. Favorites
4. Waypoint

Inside the "Warning" category it is

1.1 SPEED_LIMIT (if you are actually over!)
1.2 STOP
1.3 SPEED_CAM (if enabled)
1.4 The other alarms

I think the logic is that

- the speed limit warning is circumstantial evidence that you are in definite violation already,, as it only sounds if your speed is over the limit plus tolerance. (BTW: If you are already over the speed limit, you are likely also over any proper reaction to a pedestrian crosswalk, railroad crossing, toll booth, or other warning.)
- A stop sign you have to react to regardless of any other circumstance
- The speed cam you explicitly set in settings to be announced or not, indicating if it is of priory for you or not.
- All other warnings may or may not require your reaction, it depends on circumstances unknown to the app, like if pedestrians are present, if a train approaches, etc.)

I am not sure I can find an objectively better order, but if you think you have one, please suggest.

Thx., Hardy

**Comment by polarbearing** [comment]
Well one idea was that a spot hazard temporarily overrides the speed limit, which seems to be the only way hazard. Effectively, even when driving a bit faster, people might want to obey ped crossings. 

I'm still observing if non-nav situations are less reliable in announcements than when navigating. 

Meanwhile we could have a look at the opposite problem, too many announcements: #3429

**Comment by sonora** [comment]
Regarding the non-nav case: Yes, please keep in mind that in that case we do not know where a user intends to go, so we can merely consider prompting warnings based on actual position and proximity to that (perhaps combined with extrapolating the direction of motion, but then it becomes fuzzy already), while in the nav case we evaluate the proposed route with all warnings attached to its path in the forward direction of travel.

Regarding our priority algorithm: It was not coded by me, so unless someone else jumps in here it would take me considerable research to investigate how we can safely "interleave" one warning with another and still always ensure a consistent and informative state.

**Comment by polarbearing** [comment]
For the visual warning, it could be possible to show 2..3 icons building up next to each other if there are that many warnings.

**Comment by polarbearing** [comment]
**Voice initialisation problem in non-nav?**
Today I had installed the latest nightly (13-Jan-2017 23:01), thus the app was freshly started. Only going _non-navigational_. 

On my way out, I got: 
Speed_limit (shown / no voice), Railway (not shown / no voice), several PedXing (shown / no voice).
On the return the same, PedXing (shown / no voice). 
Now I had the following interactions:
- checking setting for announcements (they all were on for traffic warnings)
- shifting the map, and then pushing the my-position button
- calculate a route, but not pressing go, and cancelling.

When continuing in non-nav mode, from now on I got **all the icon+voice** announcements (speed_camera, speed_limit, pedXing, railway (Interestingly the double railway only once, as opposed to #3429 example 1 in navigation mode), and a traffic_calming.

Thus my guess is that one of the interactions in between triggered some voice initialisation that was not done so far in non-nave mode?

**Comment by sonora** [comment]
The following is known behavior, we have had a discussion some time ago in the project team, and there decided to leave it as is: **The voice module is only activated upon starting the navigation follow ("GO") mode, and remains active thereafter.** (Voice can also initialized by starting the test voice activity, and maybe some other deliberate voice actions.)

I think the main reasoning was it is absolutely unclear that people appreciate voice warning prompts from a mapping app without ever having started a voice navigation. But we still wanted to facilitate acoustic warnings in the non-nav state, that so we leave the voice module active after a user has once started voice nav.

**Comment by polarbearing** [comment]
Hm, I was just about to confirm exactly this behaviour which I found out the hard way. It was very confusing since sometimes voice worked in non-nav and sometimes not. 

The warnings are generally unrelated to navigation, so they probably deserve an extra switch. Probably in General settings->voice->Voice guidance, there could be a tickbox like "voice warnings" or "voice warnings in map mode".

**Comment by vshcherb** [comment]
We don't do voice guidance in a Browse Map mode though we do in a Car mode. This solves use case that people don't need navigation but need to be warned about something on the road or speed limits.

**Comment by polarbearing** [comment]
I was only talking about the Car mode, with and without navigation. 
To expect people to start the navigation system and stop it again, just to initialise the voice to hear the hazard warnings in non-navigational car mode, is intransparent and strange.
