### ISSUE TITLE
OSM Live subscription with bitcoins

### ISSUE THREAD

**Issue by DFyson** [osmandapp/Osmand#3337]
I'd like to be able to subscribe to OSM Live using bitcoins. I contribute to mapping and get a little bit back in bitcoin and so it would be nice to circulate that back into the subscription. It would make it much for efficient by cutting out at least 3 transaction fees.
It would be nice if there were a button for a [bitcoin uri](https://bitcore.io/api/lib/uri) which would open a bitcoin wallet to make the payment.
I had written [a forum post](https://groups.google.com/forum/#!topic/osmand/mqc-qvd36CM) about this but it didn't get much attention.

**Comment by vshcherb** [comment]
Yes, we've always had it in mind, though what've missed how to calculate it properly to display in finance spreadsheet... I think it will be possible to have this option in OsmAnd~.

The simple way would be to create extra bitcoin wallet which will be dedicated to that purpose, than every month all collected bitcoins will be combined with bitcoins bougth from Google transferred money.

**Comment by aceman444** [comment]
I have also proposed this in the forum, that OSM Live recipients could somehow pay the bitcoins back to OsmAnd in exchange for getting the OSM Live feature (faster updates). Or you could of course provide OSM Live for free for all OSM Live recipients, then it would be easier to implement :)

**Comment by vshcherb** [comment]
OSM Live feature is available with nightly builds today.

**Comment by aceman444** [comment]
Do you mean OSM Live is free for all users of the nightly builds?

**Comment by vshcherb** [comment]
Kind of free :) Though it is not very official and advertised builds but as a workaround for people.

**Comment by aceman444** [comment]
Thanks, we will check it out.
