### ISSUE TITLE
Strange detour in navigation

### ISSUE THREAD

**Issue by vrtareg** [osmandapp/Osmand#3339]
Hi

I have noticed strange detour in navigation planning.

I am trying to navigate from Whinfell Close, St Neots PE19 8AB to Wansford NVR (Lat 52.56789 Lon -0.38845) and OsmAnd is doing weird detour at the end of route.

Maps.me which is using same OSM data doesn't do that so I assume data is correct.

Regards, 
Areg 

![screenshot_2016-12-10-19-34-30](https://cloud.githubusercontent.com/assets/2562730/21075727/e59bb818-bf10-11e6-91f9-b82441f5d27a.png)

![screenshot_2016-12-10-19-36-24](https://cloud.githubusercontent.com/assets/2562730/21075731/ee889900-bf10-11e6-9f1b-a1e855041b81.png)

**Comment by aceman444** [comment]
OsmAnd may just prefer the motorway more so it wins over the countryside road. You could check what type of road that is (old great north road), what the highway= tag value is. Then see if there is maxspeed tag set on the road and if not, we can see what default speed is assumed by OsmAnd on that type of road.

**Comment by vshcherb** [comment]
Not reproducible with latest maps (tested on latest version).
