### ISSUE TITLE
[Feature Request] display prow_ref and use for voice guidance

### ISSUE THREAD

**Issue by dmgroom** [osmandapp/Osmand#3340]
In the UK many footpaths and other public paths have been tagged with the tag prow_ref=*** .  This shows the public rights of way reference, which is often shown on path markers.  According to taginfo there are over 30,000 uses of this tag, so you can see it is in common usage.

It would be nice if OsmAnd  displayed the prow_ref on the path, and also used this in voice guidance.

**Comment by trigpoint** [comment]
I would say that this is a very bad idea. The tag prow_ref is used in OSM to prevent unmarked refs appearing on standard maps. They are intended for internal use by the local highway authority.
I have never seen these references signed on the ground, beyond on diversion notices.

If they really do appear on the ground then the ref tag, with a good explanation of the source, can be used, but the OSM community will remain to be convinced that any highway authority has the level of budget to produce this detail of signage.

**Comment by dmgroom** [comment]
The majority of footpath / bridleway signs on the Isle of Wight have the prow ref on them.  This includes new signs produced by the council this year, and very old signs where the paint as almost disspeared. [[1](https://www.google.co.uk/imgres?imgurl=http%3A%2F%2Fc8.alamy.com%2Fcomp%2FF8CCAC%2Fpublic-footpath-sign-on-the-isle-of-wight-coastal-path-england-uk-F8CCAC.jpg&imgrefurl=http%3A%2F%2Fwww.alamy.com%2Fstock-photo-public-footpath-sign-on-the-isle-of-wight-coastal-path-england-uk-91242212.html&docid=z_JRDz0szwZt1M&tbnid=uGlGnHKidxH6RM%3A&vet=1&w=1300&h=1065&itg=1&client=firefox-b-ab&bih=879&biw=1280&q=isle%20of%20wight%20footpath%20signs&ved=0ahUKEwikvLns3O_QAhXlLcAKHXEgBVAQMwgcKAAwAA&iact=mrc&uact=8)], [[2](https://www.google.co.uk/imgres?imgurl=http%3A%2F%2Fimages.redfunnel.co.uk%2Fimages%2Fisland-guide%2Factivities%2Fwalking%2Fwalking-sign_700x461.jpg&imgrefurl=http%3A%2F%2Fwww.redfunnel.co.uk%2Fisland-guide%2Fthings-to-do%2Fwalking%2F&docid=NAsTIdoA6RIVOM&tbnid=fmcSdzqfhMXTSM%3A&vet=1&w=700&h=461&client=firefox-b-ab&bih=879&biw=1280&q=isle%20of%20wight%20footpath%20signs&ved=0ahUKEwikvLns3O_QAhXlLcAKHXEgBVAQMwglKAkwCQ&iact=mrc&uact=8)], [[3](https://www.google.co.uk/imgres?imgurl=http%3A%2F%2Fl7.alamy.com%2Fzooms%2F684387f2fd5f4fd8aa0025334041b1ba%2Ffootpath-sign-for-shepherds-trail-isle-of-wight-with-border-collie-arjkcd.jpg&imgrefurl=http%3A%2F%2Fwww.alamy.com%2Fstock-photo%2Fcoastal-footpath-isle-wight-sign.html&docid=4mDPirnuOkevQM&tbnid=WBgmI6yExWEW3M%3A&vet=1&w=640&h=500&itg=1&client=firefox-b-ab&bih=879&biw=1280&q=isle%20of%20wight%20footpath%20signs&ved=0ahUKEwikvLns3O_QAhXlLcAKHXEgBVAQMwgfKAMwAw&iact=mrc&uact=8)]

The rights of way ref is referred to in many trail booklets [[4](http://www.visitisleofwight.co.uk/dbimgs/5.Sandown-Ryde.pdf)], [[5](https://www.iwight.com/azservices/documents/1376-Barnsley-Trail-Leaflet.pdf)], [[6](http://www.visitisleofwight.co.uk/dbimgs/9.Worsley%20Trail.pdf)].

The ref tag is not suitable for a number of reasons (mainly as there would be a potential conflict when the right of way also follows a numbered road), which is why the tag prow_ref is in common useage.

**Comment by hakuchi** [comment]
why do you not use relation with route=hiking or route=horse for this prow_ref?
a) So you can add in the relation the ref=F35 or ref=BS1.
b) Hiking relations you can make over streets with ref and over streets without ref. Also you can use more relations on the same way with different ref.

Other country's have also numbers for hiking and lokal maps what using these numbers, but they use relation and not some new/old ref-key.
I think UK-community have to rework this key.    
    
    
But I see also a solution to implement this in OsmAnd, without having to much numbers on the standard map.
I think we can add this to Configure map -> Routes -> Hiking symbol overlay
![hiking](http://img5.fotos-hochladen.net/uploads/screenshot20161q9kvtbwrx.png)

**Comment by dmgroom** [comment]
I think there are prpbably two reasons why these are not tagged as hiking_routes.

1) No one thinks of them as hiking routes.
2) In many cases there is only one way tagged with the prow_ref, as there is no need to split the way into multiple sgements.  It would seem overly complex to have a route relation with only one member.

In any case this whole discussion has turned into one about why does a well established use in OSM exist in the way it does.  This tag has been used for 4.5 years, with over 30,000 ways tagged with prow_ref, less than 10% of those contributed by me (so its not a "personal tag" that I just use), and I simply thought it would be nice if such a tag were displayed and used by OsmAnd.

Also I should add that it's not just me that would find this useful.  In fact personally it doesnt make much difference to me as I already have a custom map made with Map Creaor which I use, and  which does show the prow_ref.  However other OSM users are less technically able, and in order to get the prow_ref showing on their OsmAnd map they have been incorrectly using the name field with the prow_ref.

**Comment by sonora** [comment]
Looks like no action planned for this.

**Comment by Cj-Malone** [comment]
There is now [216, 081 ways](https://taginfo.openstreetmap.org/keys/prow_ref#overview) with this tag. I would still like to see it rendered.

But it go off topic a bit, I'd also like to see the ways rendered differently. England now often duel tags the England specific tag eg `designation=public_bridleway` along with the OSM standard tags eg `foot=designated` + `horse=designated` + `bicycle=yes`.

OsmAnd (with a pedestrian profile and "More details" and "Show access restrictions and toll") will render `access=private` as pink dots along the way. And since #14294, that doesn't trigger on `access=private` + `foot=designated`.

But I'd love for standard OSM tags `foot=designated`/`bicycle=designated` to get some kind of positive rendering. Green dots?

I've had to recommend to a few friends use `https://osm.cycle.travel/rights_of_way/{0}/{1}/{2}.png` from https://osm.cycle.travel/rights_of_way.html as an overlay. But that's obviously not ideal.
