### ISSUE TITLE
Short tap on map causes popup "Destination is not set", relating to ticket #2825

### ISSUE THREAD

**Issue by Boothy99** [osmandapp/Osmand#3341]
I see issue #2825 was closed, however -
On my tablet Samsung Galaxy Tab S 8.4 running android 6.0.1 I'm getting a popup message "destination not set" with any short taps on the map. Same issue with map set to walking, driving, cycling. There are no active or inactive map markers. All recent destinations cleared. Occurs on offline as well as online maps (UK, Cyprus, Ireland all the same issue).

Have latest OsmAnd+ 2.5.4 (22-11-16) with updated maps from 1st December '16. No difference before or after map updates.

If I try to use measurement tool, I'm unable to get it to measure. I simply get "destination not set" popup message after activating tool. No points are appearing on the map no matter what I try. No measurement is taken. Re-tapping the tool shows "finish editing" without points being made.
Same message appears without measurement tool activated anyway.

On my phone (HTC One M7), using android 5.0.2, with OsmAnd+ (all updated as on tablet) there are no problems. All works as expected with no "destination not set" message with short taps on the maps. Measurement tool works as expected.

See also - Ziel ist nicht festgelegt / Destination is not set Error
https://groups.google.com/forum/m/#!topic/osmand/n1Y6iCu8MUk

**Comment by Boothy99** [comment]
I just tried a fresh re-install of OsmAnd+, but disappointed to say the message still pops up when touching map briefly. Unable to use measurement tool.

**Comment by Boothy99** [comment]
@vshcherb 
FOUND THE PROBLEM !!
I just reinstalled OsmAnd+ yet again. This time, activating plugins one at a time.

Initially, the "Destination is not set" error was NOT there, with no plugins activated. Measurement tool worked properly.

As soon as Accessibility plugin was activated, the error started again. Even with no tick boxes activated in the plugin. Deactivate Accessibility, and everything works as expected.

Thank goodness for that.

**Comment by bjohas** [comment]
Thanks for figuring that out - that's excellent! I can confirm that disabling the accessibility plugin fixes the issue for me too (android 6).

**Comment by Boothy99** [comment]
@bjohas 
Glad the cause is at least found, and a fix for it works for you too, bjohas.

**Comment by vshcherb** [comment]
Accessibility is specially designed for disabled people, may be we should warn to not enable that plugin cause it changes normal workflow in many places. This plugin also maintained by other community, so I would not judge if that's wrong or correct behavior.

**Comment by Boothy99** [comment]
OK, thanks Victor. 
OsmAnd+ does not demonstrate the popup in devices prior to android 6, so I'm guessing it's unintentional. However, I don't actually use the Accessibility plugin, so actively turned it off now. The other community might be interested in this issue perhaps?
Yes, it's a good idea to inform folk to turn it (Accedibility plugin) off to prevent users coming across the issue inadvertently. 
Measurement tool becoming useless must reveal that there's a glitch. 
Cheers,
Dave.

**Comment by bjohas** [comment]
Hi both, 

It's the accessibility plugin maintained via github? Is this bug report OK, or should we open a new one? 

Thanks!

**Comment by Boothy99** [comment]
@vshcherb 
Is there someone who deals with Accessibility Plugin, that we could inform about this issue, or forward a message to, please?

**Comment by poretsky** [comment]
It's me.

The discussed behaviour is not a bug. It is just what should be when
accessibility plugin is activated.

>>>>> "Boothy99" == Boothy99  <notifications@github.com> writes:

    Boothy99> @vshcherb Is there someone who deals with Accessibility
    Boothy99> Plugin, that we could inform about this issue, or forward
    Boothy99> a message to, please?

    Boothy99> — You are receiving this because you are subscribed to
    Boothy99> this thread.  Reply to this email directly, view it on
    Boothy99> GitHub, or mute the thread.*

**Comment by Boothy99** [comment]
@poretsky 
Thanks for your reply and explanation.
As you deal with the plugin, I shall close the issue, seeing as it's expected behaviour. 
Thank you.

**Comment by vshcherb** [comment]
Thanks @poretsky for a reply! We might need to add something in Block letters don't activate the plugin unless you know what you are doing.
