### ISSUE TITLE
Boat and Plane mode on OSMAnd

### ISSUE THREAD

**Issue by BoFFire** [osmandapp/Osmand#3342]
Hi OSMAnd :)
How could we help to betatest Boat and Plane mode and which routing engine should we use.
I tried Strightline but annouces wrong duration.
Thank you for reading me.
Salutations amicales :)

**Comment by vshcherb** [comment]
Unfortunately now we realize it will take much more time than we planned. We need to dismiss that issue to be clear that it unlikely will be implemented.

**Comment by laplasz** [comment]
I think a boat application mode could be enabled with the current features - why is unlikely to be implemented?
