### ISSUE TITLE
ref displayed different as OSM data

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/Osmand#3343]
On this ways the ref is displayed different as in the OSM database:

https://www.openstreetmap.org/way/41590343 on zoom 17
https://www.openstreetmap.org/node/539124996 near this point on zoom 18
https://www.openstreetmap.org/node/2642332912 near this point on zoom 18

In Italy, the street numbers do not consist entirely of uppercase letters.
First letters are uppercase but the letters(dir,racc,var,bis,quater) after the number are always lowercase.

For example:

SS123dir or SS123dir/A, but no SS123DIR or SS123DIR/A etc.
Of course some of the numbers are wrong in the OSM database but the examples from above are displayed wrong.

Here some pictures from Mapillary(sry not the best one) or Google where you can see the lowercase "bis":
https://d1cuyjsrcm0gby.cloudfront.net/LnPHRtucPIxF_9Rv782Azw/thumb-2048.jpg
https://d1cuyjsrcm0gby.cloudfront.net/LJhbHNzlgeKjCXFSSPx4Ig/thumb-2048.jpg
https://www.google.com/maps/@46.7696649,11.6548433,3a,29.2y,38.76h,81.45t/data=!3m7!1e1!3m5!1spElnRfSkCEpm7Eh_cF63fA!2e0!5s20110801T000000!7i13312!8i6656

Tested on nightly 15602 and latest map Italy Trentino-Alto Adige and map language in German.

PS: If I zoom in and out some times I can see the correct ref from way. Can this be a error wit import from relations? Hope I can take a screenshot for you.

**Comment by hakuchi** [comment]
![pic](http://img5.fotos-hochladen.net/uploads/screenshot2016k5txwsl92f.png)

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-tools/commit/c49c861bb1dd29abc831d7573272da83b3030aff

**Comment by hakuchi** [comment]
not fixed
