### ISSUE TITLE
tunnel over motorway_link, residential, etc

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/Osmand#3346]
tunnel is over `motorway_link` and under `motorway`.
http://www.openstreetmap.org/#map=19/46.88431/11.43746
![tunnel](http://img5.fotos-hochladen.net/uploads/screenshot2016kugoz5nm6e.png)

tunnel over `service`, `residential` and `cycleway`
http://www.openstreetmap.org/#map=19/46.48867/11.34634
![tunnel2](http://img5.fotos-hochladen.net/uploads/screenshot20161qihft9846.png)

tested on nightly 15602 and latest map

**Comment by xmd5a2** [comment]
FIxed these and all possible cases
https://github.com/osmandapp/OsmAnd-resources/commit/dcb9da748bbbb956e6c2409dbc9cb9543b5fdb25
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot%20from%202016-12-15%2014-50-34.png
