### ISSUE TITLE
Honor the "unit of length" setting when showing peak elevations

### ISSUE THREAD

**Issue by ejain** [osmandapp/Osmand#3348]
Even after setting the "unit of length" to "miles/feet", peak elevations are shown in meters rather than feet.

**Comment by breversa** [comment]
I believe altitude data does not exist in other units than the International System ones.

**Comment by vshcherb** [comment]
Unfortunately altitude information same as SRTM is only present in meters.

**Comment by sonora** [comment]
No action planned here it seems.
