### ISSUE TITLE
OSM Live recipients: system abuse / region hopping / changeset flooding

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#3351]
I remember some discussion during the introduction of payouts to mappers, that this could influence the mapping style. It seems that point has been reached. 

I recently registered as a recipient this month, and was initially pleased to see that my current project to add more destination tagging and refine the turn:lanes on Berlin's motorways had led my to rank 1 for my region. Each of those changesets per junction, comparing multiple aerial views, mapillary imagery and own ground survey, costs me about 30-60 min. 

Today I found some other mappers competing for this rank. Good. But, when I looked at their changesets, I found them drawing one building from Bing, or even adding one address with no proper source given, in each. Uploading several changesets per minute, until they reach the number of the first rank, than hopping to another region across the world. Changeset comments ranged from meaningless to misleading. Source tags were partially wrong.

This makes peer-reviewing their changes difficult, and blows up the databases. And I don't think that these kind of changes are what the OSM-live users expect when they are paying their fee. 

A first mitigation would be to limit the payment for mappers to one region (until they start account spamming), but probably the whole system needs to be reconsidered.

**Comment by polarbearing** [comment]
Another method would be to limit the number of recognised changesets per day, e.g. 3.

**Comment by hakuchi** [comment]
Why is there a payout to Mapper? This makes no sense for me.
OSM is a non-profit organization, and so the mapper should not receive any payouts for changes. The payout should be given to [OSM Server] (https://donate.openstreetmap.org/) and not to mappers who do mass(non sense) changes to get payouts. 

OsmAnd should donate to OSM and not to the mapper.
When we donate to OSM, they can pay the server fees.
Without server the OSM project is not able to survive.

**Comment by hvdwolf** [comment]
Take a look at the finance balance sheets for OSM: https://wiki.osmfoundation.org/wiki/Finances. 
They could use some money. 
For me the better is also to split between OsmAnd team/servers/infrastructure and OSM itself. 
Not to the mappers.

**Comment by polarbearing** [comment]
Yes, redirecting the funds to the community as a whole is a good option also. 

Anything is fine for that does not lead to unnecessary ballast in the OSM databases caused by massive micro-uploads.

**Comment by vshcherb** [comment]
Today the maximum amount by a user is limited, so by doing microchanges you could reach only a certain level. BTW I checked couple of abuse sent by email and there were not registered.

I think competing for the rank (not abusing monetary system) is totally fine, there is no totally useless changes, people educate themselves for example, start doing something. May be some changes incomparably bigger and that's fine. Full changesets DB will keep growing and that's normal, to reach more or less full coverage of roads/buildings some countries will need to grow up to 10 times. Everything has pros and cons, though gamification is not necessarily bad. Actually the different rankings existed before and even more accurate. 

Redirecting to OSMF is definitely an option, though we donated before without OSM Live. Changing rules could have a big impact and we will need everybody subscribed agreement.

I'm not sure what could be done with that issue today, so I keep watching it but close it for now.

**Comment by vshcherb** [comment]
>> Another method would be to limit the number of recognised changesets per day, e.g. 3.
We already limit recongised changesets per month, it is not that huge, worldwide maximum is 220. And for some regions numbers are lower to 50-70
