### ISSUE TITLE
OsmAnd Core API sample 1 always crashes on startup

### ISSUE THREAD

**Issue by hvdwolf** [osmandapp/Osmand#3352]
For 3 days I'm now downloading the nightly "OsmAnd Core API sample 1 for Android OS" but it always crashes on startup. No further message apart from "Unfortunately, OsmAnd Core API sample 1 for Android OS has stopped".

Other installed apps: OsmAnd+, OsmAnd Contour Lines, OsmAnd parking plugin, OsmAnd Ski maps. All on latest version. OsmAnd+ on latest beta-channel version. I don't know whether the other "extra apps" also follow that beta-channel.

Samsung S5 mini, stock Android 5.1.1

**Comment by vshcherb** [comment]
Do you have any crash.log? To help us somehow..

**Comment by crimean** [comment]
Looks like you need to use Shared memory in OsmAnd+ app
