### ISSUE TITLE
Support for speed limited vehicles

### ISSUE THREAD

**Issue by sim6** [osmandapp/Osmand#3353]
Firstly, thanks for your work.

Please could you add an option to set the maximum speed of the vehicle?

Thanks again.

**Comment by aceman444** [comment]
Yes, this would be useful.

**Comment by polarbearing** [comment]
Useful indeed. Should be in Routing Preferences, along with the existing Weight and Height limits. 
There are legal limits for specific vehicles (trucks on motorway, car pulling a trailer), physical limitations or personal preferences.

**Comment by uwe347** [comment]
This would be a very helpful feature! It would bring up a better estimated time of arrival for slower vehicles as trucks or caravans.

**Comment by akaleeroy** [comment]
> Maybe the possibility to add multiple profiles for different types of vehicles they own would be another nice feature. That way they don't need to fiddle with settings every time they change vehicle.

Vehicle profiles could follow http://schema.org/Vehicle

**Comment by thuryn** [comment]
My motorbike can go on the highways but not by the maximum allowed limit - so navigation algorithm should consider the vehicle speed limit

**Comment by aceman444** [comment]
Until this is built into OsmAnd, you can use your own modified copy https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml, then put it into the OsmAnd folder and it will be picked up.

In the <way attribute="speed" type="speed"> block you can change he default speeds on various classes of roads. E.g. right now there is 110kph for a motorway (which is even too low for cars in many countries), you can decrease it.
for a motorcycle, you could also update the access restrictions block, as motorcycle can go to some places/roads/barriers where a car can't.

Yes, this will not override maxspeed when it is set explicitly on a road. E.g. if there is maxspeed=130 tagged on a motorway, OsmAnd will use that, unless you remove the line https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#L591 . But if you remove it, OsmAnd will also ignore lower maxspeed specified on a particular road, and use your defaults in the block.

Maybe for a moped running max 30kph, forcing that speed on all roads would be the preferred thing (and ignoring all the 40,50,60,90,130 signs no the roads).

**Comment by thuryn** [comment]
Thank you for the answer. It's nice one is able to modify the routing behavior. It seams I cannot use this approach - the maxspeed on the road is really important. The route would be really inaccurate when I ignore all the maxspeeds. The way usually contains several cities (50 km/h), limits inside the cities (40 or 30 km/h) and there are lot of speed limitations outside of cities also. As my motorbike can go 95 km/h I can go on maxspeed on all the roads except motorway (there is limit 130 km/h in my country - so OsmAnd things I can go by this speed and the time is not calculated accurate).

**Comment by aceman444** [comment]
The you can do this:
<way attribute="speed" type="speed">
<select value="95" t="highway" v="motorway"/>
<select value="95" t="highway" v="motorway_link"/>
<select value="95" t="highway" v="trunk"/>
<select value="95" t="highway" v="trunk_link"/>


<select value="$maxspeed:practical" t="maxspeed:practical"/>
<select value="$maxspeed:advisory" t="maxspeed:advisory"/>
<select value="$maxspeed" t="maxspeed"/>

... rest of the "speed" block...

Thus you force 95 kph on motorway regardless of what is tagged on it (usually maxspeed=130), but obey maxspeed tags (like 50/40/30) on lower-class roads.

**Comment by thuryn** [comment]
It seams it works fine. I've changed "car" profile and the time for the calculated route had been changed. So I created profile for motorcycle, but the routing engine ignores it. I've put profile:
<routingProfile name="motorcycle" baseProfile="car" 
or
<routingProfile name="motorcycle" baseProfile="motorcycle" 

and the routing profile is ignored even when I switch the profile to Motorcycle in the app. Could you help me, please?

**Comment by aceman444** [comment]
No, I'm not familiar with that. There are several routing modes (vehicles) in OsmAnd but they do not appear in routing.xml file. I don't know how they are implemented.
There was even a boat and a plane in the past :)

**Comment by thuryn** [comment]
The problem is probably in this part of the code:
public enum GeneralRouterProfile {
                CAR,
                PEDESTRIAN,
                BICYCLE,
                BOAT,
                PUBLIC_TRANSPORT
        }

The enum does not know about motorcycle profile.

**Comment by thuryn** [comment]
I've found some temporary solution:
1) I've added line: <parameter id="vehicle_limited_speed" name="Vehicle has limited max speed" description="Vehicle has limited max speed" type="boolean" /> just after the "height" parameter in "car" profile
2) Modified speed part of xml in this way:
<ifnot param="vehicle_limited_speed">
                <select value="$maxspeed:practical" t="maxspeed:practical"/>
                <select value="$maxspeed:advisory" t="maxspeed:advisory"/>
                <select value="$maxspeed" t="maxspeed"/>
			</ifnot>
            
			
            <select value="95" t="highway" v="motorway" />
            <select value="95" t="highway" v="motorway_link" />
			<select value="95" t="highway" v="trunk" />
			<select value="95" t="highway" v="trunk_link" />
            <select value="95" t="highway" v="motorway" />
            
            <if param="vehicle_limited_speed">
                <select value="$maxspeed:practical" t="maxspeed:practical"/>
                <select value="$maxspeed:advisory" t="maxspeed:advisory"/>
                <select value="$maxspeed" t="maxspeed"/>
            </if>

I can switch between profiles and can see the differences in calculations.

**Comment by pebogufi** [comment]
@thuryn 
I am VERY interested in your solution, but somthing does not work, how I used it. 
Could you please provide the complete routing.xml ?
Thanks a lot, Peter

**Comment by thuryn** [comment]
[routing.xml.zip](https://github.com/osmandapp/Osmand/files/3208069/routing.xml.zip)

you have to open the settings in Osmand and check the "Vehicle has limited max speed" checkbox. I have this option switched off by Car and on by Motorbike.

**Comment by pebogufi** [comment]
It works, thanks a lot !!!

**Comment by Chumva** [comment]
We have a dialog where you could set min/max/default speed for profile in vehicle parameters.

**Comment by Torvin** [comment]
Where's that dialog? I can't find it

**Comment by sim6** [comment]
- Tap menu button (bottom left)
- Select, or create a profile, via top menu dropdown
- Tap "Configure profile"
- Tap "Navigation settings"
- Tap "Vehicle parameters"

**Comment by Torvin** [comment]
Thank you! I could have sworn I checked there.
