### ISSUE TITLE
apk size increased significantly by new fonts

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#3354]
On Dec 12 we increased the apk size by some 4 or 5MB by adding some 9 MB in fonts in this commit: https://github.com/osmandapp/Osmand/commit/ab40c32273e2c5fae96f982fdc82d50153c2533b

Is it worth it? Can it be optimized?

**Comment by xmd5a2** [comment]
I think it worth it because different devices include different font packs (mostly old android 4 devices). This leads to unpredictable rendering of many asian and arfican names.

**Comment by sonora** [comment]
Ok, this sounds functionally justified then. I was just wondering why the file size is about 10-fold of what we used for fonts so far, or if there are unused font sizes or anything we could maybe leave out.

**Comment by BoFFire** [comment]
Thank you for adding Noto ;) I thought that may be it will be added in "Accessibilty" part of the App but no :D I was wrong.

**Comment by sonora** [comment]
apk size increased once again by 4 MB today, we are now at 61MB. Are we really sure we need all font sizes 05 / 10 / 15 / 20 / 25 / 30 / 35 / 40 / 45 / 50 / 55 / 60 / 65 in linear steps of 05 ?

Usually you would require smaller intervals for small sizes, but increasing spacing with higher values. From the size pool you have, I am wondering if you see any practical degradation if you approximate a size ladder "factor 1.5 spacing", like including only  05 / 10 / 15 / 20 / 30 / 45 / 65 ?

**Comment by vshcherb** [comment]
@sonora  I'm not sure your question is clear. Fonts are really vector based and not pixel based. We really need to include them to finally make map visible everywhere, I think with these fonts we make application consistent and nice map look and feel. Also @xmd5a2 did a great job of combining Noto fonts, so now that terrible issue of seeing squares in Japan is fixed.

Unfortunately we can't include all fonts in the app, so 4 Japanese, Chinese, Korean glyphs are excluded and should be downloaded separately after installation.

I feel this important step worth of increasing 4 MB, please keep in mind that maps are growing faster than 5MB per year.

I think the biggest concern for most of developers, that we don't need to update 60MB daily. We only need to update 5MB or even less? That's a different problem that doesn't touch end users really.

**Comment by sonora** [comment]
@vshcherb , @xmd5a2 Yes, everything Victor says above is true, and this definitely fixed many long-running issues we have had!

I have to admit I have not researched the matter much. I was (and to some extend still am) just baffled by the fact that now about **17%** of our apk size (15 out of 90MB uncompressed) are taken up by fonts! That simply seems like a lot, and I wanted to point that out before we lose sight of this, should there be ways to optimize this.

**Comment by vshcherb** [comment]
only compressed size matters. And yes 90% fonts take a lot for are quite rarely used, though worldwide software should be ready to all use cases.
