### ISSUE TITLE
Faulty turn detection when |through lanes are present

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/Osmand#3357]
if the turn:lanes(:forward/backward) have none|**through**|slight_right the voice is giving no turn instructions.
If I change these to none|**none**|slight_right the voice give correct turn instruction.

here a example to test.
tested with latest from PlayStore and latest nightly. Same bug.
**with** through:
https://www.openstreetmap.org/way/4401150
https://www.openstreetmap.org/way/153077009  -> München-Süd

**without** through:
https://www.openstreetmap.org/way/34492231
https://www.openstreetmap.org/way/256297941  -> München-Süd

Arround the [world](http://overpass-turbo.eu/s/kOg) are a lot of `turn:lanes=none|through|...` and none of them is used correct.

**Comment by polarbearing** [comment]
This is hard to understand. To my knowledge, the turn:lanes only influence the display of lane recommendations, not the turn instructions. You might need to specify from where to where your routing goes, make a screenshot of the turn and lane instructions, and take a note of the voice output.

**Comment by hakuchi** [comment]
If the exit from the motorway have **through** in `turn:lanes` this need a voice prompt.
If the `turn:lanes` not have _through_ as key, OsmAnd give correct "turn slight right" voice prompt.
But if there is _through_ in `turn:lanes`, OsmAnd not giving any voice prompt for exits.

**Comment by polarbearing** [comment]
OK, I was able to reproduce the problem, however it has nothing to do with voice, thus the issue title is misleading. 

I created a route leaving the A14 at exit 26 as in @hakuchi's first way. The route instructions recommend the correct way to exit, but fail to recognise the turn. The lane recommendation highlights the wrong lane. The A14 is perfectly straight here, so that cannot be the cause for failing to recognise the slight turn. The w4401150 has some other tagging such as lane placement, is that already evaluated?

![screenshot_20161222-010401](https://cloud.githubusercontent.com/assets/8266355/21410896/7e26f92c-c7e4-11e6-94e0-3e8177d72c58.png)![screenshot_20161222-010304](https://cloud.githubusercontent.com/assets/8266355/21410900/832ec062-c7e4-11e6-8400-1e64a178cfeb.png)

@hakuchi - do you know how to simulate a route?
@vshcherb - this reminds me to #1347, as I see the exit number in the description...

**Comment by hakuchi** [comment]
@polarbearing thanks for screenshots 👍 

The issue is that Osmand not giving voice prompts if the `turn:lanes` have `through` as key.

I think this can be fixed with the mapcreator when we change the `through` to `none`.
I will test(at home) if this work also, if I change `through;right` to `none;right`.

PS: Yes I know how to simulate a route.

**Comment by polarbearing** [comment]
@hakuchi : you must not change 'through' lanes to 'none', that is a different meaning. 'none' means you can turn in **any** direction, while 'through' means you can only go straight. 

@sonora : thanks for changing the title, however it is not only the lane selection, it does not give the correct turn in the route description. Thus picking the straight lane is only a consequence of pointing straight in the routing.

**Comment by hakuchi** [comment]
and why is on the exit Leipzig-Ost, if you come from south, [none|through|slight_right](https://www.openstreetmap.org/way/4401150) and if you come from north [none|none|slight_right](https://www.openstreetmap.org/way/4260883)? I can not see anything different on Bing image.

>'none' means you can turn in any direction, while 'through' means you can only go straight.

The arrow _through_(on the ground) shows that you not leave the motorway on this lane, but you can change the lane to left and right(you should change to right lane as early as possible, if you will exit).

On the example from north to south you can use [here](https://www.openstreetmap.org/way/232308737) all 3 lines(no turn:lanes on it), but the third lane change to a exit lane [here](https://www.openstreetmap.org/way/4260883), and so you have to change onto lane 1 or 2 if you will drive to Dresden/Kleinpösna.
If you not can change the lane, there should be used [change:lanes](http://wiki.openstreetmap.org/wiki/Proposed_features/change#Different_values_on_a_three-lane_motorway)=yes|not_right|no or similar([example](https://www.openstreetmap.org/way/318445902)).

PS: if the turn lanes have [through|through|right](https://www.openstreetmap.org/way/210448045) or [through|through|slight_right](https://www.openstreetmap.org/way/209197543), OsmAnd select correct lane and give voice prompts.
So I think the problem is when the key have a combination with `none` and `through`. And for this my suggestion to change the "through" in map creator to "none".

**Comment by hakuchi** [comment]
Tested wit changing **through** to **none** and I can not find any bug.
In the following screenshot I changed the turn lanes to `none|none|none;slight_right`

![ex1.1](http://img5.fotos-hochladen.net/uploads/screenshot2016l1sw9d5x0m.png)
![ex1.2](http://img5.fotos-hochladen.net/uploads/screenshot2016hwctoj891p.png)
______________________________________________________________________________________
![ex2.1](http://img5.fotos-hochladen.net/uploads/screenshot20161lj2sf9ahc.png)
![ex2.2](http://img5.fotos-hochladen.net/uploads/screenshot2016zqsji0bct9.png)

This is a simple solution for OsmAnd(not OSM), I don't know if there is a other solution to support `none|through|right`

**Comment by bitboy85** [comment]
Hi, i have another example A1 -> Blankenheim
The road is correctly highlighted but the lane instructions tells you to go through. The road is tagged "left;through|right"
http://www.openstreetmap.org/#map=19/50.46360/6.69598
Sadly i cant add a screenshot currently

**Comment by hakuchi** [comment]
![left;through](http://img5.fotos-hochladen.net/uploads/screenshot2017oxv4t6ayn2.png)
I tested with different modifications of the OSM data, but changing the key`left;through|right` to `left;none|right`, `none;left|right`, `left;|right` or `;left|right` have not solved the problem.

This bug need some code inside OsmAnd to detect turn lanes with **through** and **;through** correctly.

**Comment by vshcherb** [comment]
Please turn:lanes to the small segments as well to help algorithm to detect i.e. http://www.openstreetmap.org/way/150243725, http://www.openstreetmap.org/way/320168795. I think it will be enough on the other hand I'm not 100% sure if algorithm will detect split of turn:lanes when 1 lane splits to 2 roads!

**Comment by hakuchi** [comment]
@vshcherb adding `turn` or `turn:lanes` to the two road segments(10243725 / 320168795), not show correct turn lanes in OsmAnd.
Also If I turn left, OsmAnd show only through.

**Comment by vshcherb** [comment]
Fixed

**Comment by hakuchi** [comment]
on the above examples the issue is solved, but if the way have **none|through;slight_right** OsmAnd not use correct lane.     
In Austria ([overpass link](http://overpass-turbo.eu/s/o5b)) the most motorway exits have turn lanes with **none|through;slight_right**.

here an Example:
https://www.openstreetmap.org/#map=18/47.60138/15.72202
from west
![pic1](http://www.fotos-hochladen.net/uploads/screenshot2017r9qu60ao74.png)
from east
![pic2](http://www.fotos-hochladen.net/uploads/screenshot2017bwkzf0567n.png)

**Comment by sonora** [comment]
Looks like this is related: Going south on http://www.openstreetmap.org/way/122528751, turning right (onto http://www.openstreetmap.org/way/84975049), OsmAnd navigation misses the turn and interprets this as "straight", which is clearly misleading there.

**Comment by sonora** [comment]
Not sure about the other examples, the case I describe in the post above seems **not** fixed, though ...

**Comment by hakuchi** [comment]
the other examples are fixed.
the example from **sonora** is not fixed.

OsmAnd have some problem with turn:lanes:**backward**=left|**through;right** when the intersection after the turn lane not have a 90° angle.
[Example 1](http://www.openstreetmap.org/way/122528751)
![wrong 1](http://www.fotos-hochladen.net/uploads/screenshot2017m93ab2n6gf.png)
[example 2](https://www.openstreetmap.org/way/108496885)
![wrong 2](http://img5.fotos-hochladen.net/uploads/screenshot20175i3pbhcyw9.png)

On a intersection with turn:lanes:backward=left|through;right and a 90° angle, OsmAnd is able to detect correct turn.
[Example 1](https://www.openstreetmap.org/way/442940679)
![correct 1](http://img5.fotos-hochladen.net/uploads/screenshot20176xp2ir58h0.png)
