### ISSUE TITLE
Some roads are missing in topo map style

### ISSUE THREAD

**Issue by mwaschbu** [osmandapp/Osmand#3361]
Road https://www.openstreetmap.org/way/22724310 is not rendered in the Topo map style in any detail level when using the standard Namibia offline map from 1. October 2016 (see attached screenshots). But it is visible in the OsmAnd style. 

It is visible in the newest map data from 1. December. The road has been edited during that time according to the openstreetmap change history.

Tested in OsmAnd+ 2.5.4 on a Wileyfox Swift phone using Cyanogenmod  cm-13.0-20161220-SNAPSHOT-ZNH5YAO3XJ-crackling.

![screenshot_20161223-130543](https://cloud.githubusercontent.com/assets/24733240/21453869/0406d1cc-c914-11e6-8841-180aec6443be.png)
![screenshot_20161223-130601](https://cloud.githubusercontent.com/assets/24733240/21453868/040663fe-c914-11e6-88a9-5fbac51e03b8.png)

**Comment by xmd5a2** [comment]
Do you use OSM Live?

**Comment by mwaschbu** [comment]
Thanks for looking into it. I'm not using OSM live, and I'm not really an
OSM expert.

I was able to reproduce it today with the old Namibia map data from 1.
October. After upgrading to the map data from 1. December the issue was
gone.
The editing history of that street at
https://www.openstreetmap.org/way/22724310/history shows that the tags were
changed twice just recently. So it may be related to the old set of tags. I
looked for a similar issue on the current map data but I've not yet been
able to find one.


xmd5a <notifications@github.com> schrieb am Fr., 23. Dez. 2016 um 20:18 Uhr:
