### ISSUE TITLE
Please render lwn_ref and lcn_ref on nodes

### ISSUE THREAD

**Issue by HolgerJeromin** [osmandapp/Osmand#3363]
This nodes build a walking or cycling network by defining nodes. 
The Netherlands has many for cycling. But some cities build this for walking, too. 

One example 

Best would be render lwn in foot mode and lcn in cycle mode. 

http://www.openstreetmap.org/node/27485208#map=19/53.39680/10.04328

**Comment by xmd5a2** [comment]
It is already rendered
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot%20from%202016-12-27%2021-17-38.png
but have lower priority than route name and only from zoom 17
