### ISSUE TITLE
Allow copy and paste of poi name and address 

### ISSUE THREAD

**Issue by HolgerJeromin** [osmandapp/Osmand#3364]
Right now not every text info of a poi can be copied to clipboard. 
Address, name is missing. All other items can be copied with long press

**Comment by vshcherb** [comment]
I think share button should support it along with option copy to clipboard.

**Comment by HolgerJeromin** [comment]
No, i just tested it. 
The address itself is not included in the share function. Only the name is shared. In case of only a house number this is the pure number.
