### ISSUE TITLE
New POI category for coworking

### ISSUE THREAD

**Issue by Suncatcher** [osmandapp/Osmand#3365]
I didn't find separate category for but it seems that it should be there. Now [coworkings](https://en.wikipedia.org/wiki/Coworking) are usually listed among cafes and bars, but in fact it's neither of them but a type of amalgamation of cafe, shared office, bar, creative hub and etc.
It would be nice to have this separation for more convenient search.

**Comment by xmd5a2** [comment]
What OSM tags do you mean?

**Comment by Suncatcher** [comment]
Well, I am kinda new in these tags, but if you mean "to describe this facility in tags", then I'd described it in combination of these:
[Internet_access:wlan](http://wiki.openstreetmap.org/wiki/Tag:internet_access%3Dwlan)
[Rental](http://wiki.openstreetmap.org/wiki/Proposed_features/rental)
[Office:it](http://wiki.openstreetmap.org/wiki/Tag:office%3Dit)
[Cafe:time_cafe](http://wiki.openstreetmap.org/wiki/Tag:cafe%3Dtime-cafe)

**Comment by pebogufi** [comment]
It looks like this is meant:
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcoworking_space

**Comment by Suncatcher** [comment]
Exactly! Worth it a separate category, how do you think?

**Comment by pebogufi** [comment]
@xmd5a2:
In search options please add a tag in category office or service for
amenity=coworking_space

**Comment by Suncatcher** [comment]
How to search by tags in new search box? It doesn't work like this.

![screenshot_2016-12-29-12-09-15](https://cloud.githubusercontent.com/assets/6388034/21541642/a70a5cbc-cdc0-11e6-8244-8089aa9ba290.png)

**Comment by pebogufi** [comment]
No, it does not work as you tried it.
Open search / cagegories,
Then scroll down to last position "custom search".  
There you find categories. 
Check out what you find, but be aware, that coworking is not present yet (that means I did not find it).
Wait for comment in this thread, until it is fixed or closed.
Peter

**Comment by Suncatcher** [comment]
Well, I didn't find it too. Will wait a reply here.
In [this thread](https://github.com/osmandapp/Osmand/issues/2503) it was stated that tag search request is not actual, as it was solved with new search box, however I cannot see **how** it was solved. How one can search by tag there?

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/1fe5bbba77702acef8340834a87d16c6011b785c
