### ISSUE TITLE
City name is shown in wrong language: Keulen instead of Köln

### ISSUE THREAD

**Issue by arty-name** [osmandapp/Osmand#3366]
Hello. I am using OsmAnd+ 2.5.4 on Galaxy S3 with CyanogenMod 14.1 installed (based on Android 7, though I have observed the bug in earlier OS versions as well). The device language is German, and OsmAnd+ uses German as well. I have downloaded full offline maps for Deutschland Nordrhein-Westfalen (01.12.2016), also I have overview map of the world and  "Germany addresses-nationwide europe".

The name of Cologne was correctly shown as Köln (in German). Some months ago it started being shown as Keulen (in Dutch or Afrikaans). OpenStreetMap still shows Köln. 

I don’t know what could influence that. I thought that maybe offline map of Belgium influences that somehow (Dutch is also spoken in Belgium), but after deleting it and cleanly restarting OsmAnd the problem persists.

**Comment by arty-name** [comment]
Thank you for quick response, @sonora! It was set to Westfriesisch (fy), and changing it to German has resolved the issue! 

The troubling part is that I don’t remember ever changing it to that value, and it being the last in the list makes me think that maybe it is just a fallback value, which is most likely wrong. However it could be just my memory playing tricks on me, so I let you be the judge :)

**Comment by sonora** [comment]
Ok, thanks, I will watch out for this, but have not seen this anywhere else yet. The default is actually "Local names", always preferring the local characters and spelling in each region.
