### ISSUE TITLE
Request-Playgrounds as POI

### ISSUE THREAD

**Issue by Hadena** [osmandapp/Osmand#3367]
I am often out with young kids. Would it be possible to include playgrounds as a POI? At least under POi nearby would be great.thanx for making OSMAND

**Comment by sonora** [comment]
You can create a custom filter for it as follows: Go to Search / Categories / Custom search (near the bottom). Playgrounds are under Category Leisure. Select it. You can save it  as a custom filter "Playgrounds" or so, so you can always directly use it for searches and display.
