### ISSUE TITLE
Penalty for traffic signals changes the route from tertiary road to service road

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#3368]
OsmAnd+ 2.4.6 build ALWAYS calculates a bad route for every start coordinates at the given destination coordinates:
![OsmAnd+ 2.4.6](https://cloud.githubusercontent.com/assets/6921696/21363323/5bbdd016-c6ec-11e6-867d-07adfd96c5f6.png)

OsmAnd 1.9.5 has calculated a correct route (as long as the two phase bug for special start coordinates has not been triggered):
![OsmAnd 1.9.5](http://storage.googleapis.com/google-code-attachments/osmand/issue-2580/comment-0/OsmAnd195_04.png)

(Please also refer to #1195.)

**Comment by Norbert80** [comment]
@vshcherb this time please ask if you have difficulties to understand before closing this bug report overhasty.

**Comment by Norbert80** [comment]
Please note that this bug occurs for car fastest but not for car shortest.

**Comment by hakuchi** [comment]
@vshcherb This bug bring me some questions:
1. Avoid OsmAnd in fastest route calculation traffic signals, or have OsmAnd a code to search route without traffic signals?    
At the intersection are two `traffic_signals`([1th](http://www.openstreetmap.org/node/310412238) / [2th](http://www.openstreetmap.org/node/1890745587)) they get crossed. This two traffic signals have a direction and only the first should be considered in rout calculation.
2. Is Osmand using traffic_signals:direction?

The most service roads have no maxspeed and should used for navigation only if the end point is on it or if I set a waypoint.
The way from east is a [tertiary](http://www.openstreetmap.org/way/52530506) and the road up to north is a [unclassified](http://www.openstreetmap.org/way/23903479).

**Comment by vshcherb** [comment]
This has nothing to do with 2 phase routing. I think this is duplicate and it is related traffic_signals penalty.

**Comment by vshcherb** [comment]
I think, support of "traffic_signals:direction" definitely worth to be a separate issue or this one could be renamed. Though it is not clear yet if support of direction will change the route.

**Comment by Norbert80** [comment]
@vshcherb

I never said that THIS report is related to two-phase routing bug.

I said...

a) THIS report is a regression because older builds "normally" had a good routing result on this scenario.
b) Sometimes older builds also had this bad result for this destination but only for certain start coordinations. This implies that the old two-phase bug is no more triggered in this scenario because for recent builds the result is bad for every start coordinate. But since there is no known patch against the two-phase bug we must expect that is still there and is triggered for other scenarios. This is already proven with #3023 that you have closed without any patch. This is a scenary where the two-phase-bug is triggered for recnt OsmAnd builds.

**Comment by xmd5a2** [comment]
I've increased penalty transition for service and now this test passes
https://github.com/osmandapp/OsmAnd-resources/commit/fdea398129a868442b4181f39db47f35b4d0be34

**Comment by vshcherb** [comment]
Good
