### ISSUE TITLE
exception on start

### ISSUE THREAD

**Issue by jotwewe** [osmandapp/Osmand#3369]
osmand 2.5.4 installed using f-droid
samsung s4 mini with CM12.1

When starting the app an exception is shown. Markers for favourite points are shown, but no map. I don't know about a workaround.
I was able to use this osmand version for some times before this bug occured.

Log attached.
[osmand2016-12-27-06-22-57.txt](https://github.com/osmandapp/Osmand/files/674082/osmand2016-12-27-06-22-57.txt)

**Comment by sonora** [comment]
I would guess your issue is

> W/PackageManager(745): Failure retrieving resources for net.osmand.plus: Resource ID #0x0

No clue why your are getting this, no such problem on S4 Mini with stock ROM. Maybe some Out of Memory condition? Try removing some stuff?

**Comment by jotwewe** [comment]
I wasn't talking about that warning but about this exception which is visible in the log:

org.xmlpull.v1.XmlPullParserException: name expected (position:START_TAG <poi_additional name='product_lime' tag='product'>@615:51 in java.io.InputStreamReader@1c34f86b)

I don't think it is related to an "out of memory condition".

**Comment by sonora** [comment]
The line referenced has been in our code since October 19, 201**5**. I wonder if it is something In your data files we do not catch, I guess you could try to temporarily rename the OsmAnd data folder and see if the error persists.

**Comment by jotwewe** [comment]
The workaround you suggested did the job for me. Afterwards I copied
.obf-files, favourites and tracks to the data directory which had been
created by osmand and everything is still fine.

**Comment by sonora** [comment]
But it sounds like you could not identify a data file which had caused the issue?

**Comment by jotwewe** [comment]
After osmand seemed ok again, I didn't copy more of the files from the
original directory. However, the exception gave a hint:

  org.xmlpull.v1.XmlPullParserException: name expected (position:START_TAG <poi_additional name='product_lime' tag='product'>@615:51 in java.io.InputStreamReader@1c34f86b)

There was a file named poi_types.xml (which I didn't know about or
touched manually until trying your workaround) which includes this
text. It is not well formed (seems corrupt at some characters). For
example, there are the following lines (but it is easy to find many
more errors):

	<poi_additional name="product_lime" tag="product"$value="lime"/>
	<pki_additional name="whEelchair_dEscr�ptikn" uag="wheelchair:description" type="text" lang="true" order="133"/>
	=poi_additional name="blind_description" tag="blind:description" typg="text" lang="true" order="134"/>
	<poi_additional"n�me="defibri�lator^yes" tag="defibrillatkr" value="yes"/>
	<poi_additional name?"historic_civilization_ancient_egyptian" tag="historic:civilization" valu%="ancIent_egyptian"/>

The file is about 270kB; I can attach it if you want me to.

**Comment by sonora** [comment]
It looks like a character encoding issue. Did you ever process this file manually, like in a Microsoft Office tool?

Could perhaps also be an issue with your SD card, not sure. Re-installing OsmAnd should have produced a new, valid file. If not or, if the issue comes back, please let us know. But this seems a singular incident for now.

**Comment by jotwewe** [comment]
Definitely not a character encoding issue; wrong bytes appear anywhere.

I never processed this file manually, I just copied some lines with
typical errors out of it (not using microsoft tools on my linux system).

I did not re-install osmand and a new file has not been created after
renaming the old data directory. 

I'll let you know in case anything like this happens again. Thanks for
your help!
