### ISSUE TITLE
[Feature request]: give option to either merge or replace favorites

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#3370]
When you import a new favorite.gpx file, the files get merged with the older ones. Our user requests to add the option to replace the files with the ones you import.

**Comment by sonora** [comment]
Simple workaround: First delete all favorites (this only takes a few taps on the existing interface), then perform the import. I would not think that we need to put in extra code for such a basic operation.

**Comment by pebogufi** [comment]
@Hardy, your workaround has a severe disadvantage. All favs which are not in the new file but only in the (old) collection are lost.
But it is very easy to do a merge:
Just import the new file !
At first sight it looks like that there are now a lot of duplicates (which existed in new file AND old collection). But there is an automatism:
Just leave the app, then clear cache (or reboot device), them start osmand again. All duplicate favs (which had been *absolute* identical) are removed.
I suppose that is what you / we like.
Regards Peter

**Comment by pebogufi** [comment]
... removed my comment, was misunderstanding ???

**Comment by sonora** [comment]
@pebogufi  You sent this by mail, not sure why it does not show up here, let me paste it:

> 
> your workaround has a severe disadvantage. All favs which are not in the new file but only in the (old) collection are lost.
>  But it is very easy to do a merge:
>  Just import the new file !
>  At first sight it looks like that there are now a lot of duplicates (which existed in new file AND old collection). But there is an automatism:
>  Just leave the app, then clear cache (or reboot device), them start osmand again. All duplicate favs (which had been absolute identical) are removed.
>  I suppose that is what you / we like.
>  Regards Peter

Yes, my workaround meant to address the originally stated use case, which I understood to request an entire replacement:

> Our user requests to add the option to replace the files with the ones you import.

Regarding your workaround: Yes, I think we automatically remove duplicates when cleaning up the database. There may be more complex use cases, like
- updating favorites with the same name, or
- overwriting favorites with the same position and with new tags or with a new name.

But I guess these are hard to capture all, and I am not so sure we 100% understood the original request in this issue. :)

**Comment by pebogufi** [comment]
Hardy, sorry for the confusion.
After having posted my comment, I did read the original comment of annasoloviova again and came the conclusion that I had a misunderstanding, so I removed my own comment.
Sorry again.
Peter

**Comment by sonora** [comment]
Peter, problem. If you agree, I'd say let's leave it as is now, your hint contains information someone may in deed find very helpful. Best, Hardy

**Comment by soredake** [comment]
Any progress?

**Comment by dmpr0** [comment]
@soredake You can Replace existing favorite with new while adding a new favorite point.

**Comment by vshcherb** [comment]
No plans to fix this issue yet

**Comment by flobee** [comment]
The "hint/Help' above seems to not work anymore. so we have ±version 4.2.7++ now

 I'm tring to import the favorites of several devices and only that points that osmand knows in any way are not dublicated anymore (eg import the same file twice) just gps data an the same name seems to be not unique enough for an entry.

but that points where the gsp infomation counts (for me; being in the nature without roads etc...) they get dublicated (per device :-( and the list grows per device).
