### ISSUE TITLE
Text to close in parking plugin (in German)

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/Osmand#3372]
The Text is to close in parking plugin (in German).
See screenshot.
![screenshot_20161228-095829](https://cloud.githubusercontent.com/assets/11144987/21518309/d312f2a0-cce5-11e6-8caf-f40a97a25485.png)

It must be "zeitlich unbeschränkt zeitlich beschränkt“
Greetings Simon

**Comment by dmpr0** [comment]
We change dialog to default vertical view.
