### ISSUE TITLE
Feature Request: Quick Bug Button

### ISSUE THREAD

**Issue by bitboy85** [osmandapp/Osmand#3376]
I'm currently trying out osmand to check how good and precise routing is compared to other products. If i find a bug or missing Information in the map i usually try to corecct it on my own but i ôften i cant remeber where in the map the issue was. So i like to have a quick bug button (obviously you can't scroll through Options during driving). It should take a Picture with the phone camera if possible and save the current Position. This allows me to add informations (like lanes) in the map when i'm at home.

**Comment by quelbs** [comment]
There is a Plugin "Audio/video notes" which gives you a button to add a Audio/Video/picture note on the current location. This could help for your usecase.

**Comment by vshcherb** [comment]
Please try new build "design" or wait couple of days and this functionality will be in nightly builds.

**Comment by naoliv** [comment]
Isn't it possible to configure the button to use it at the left side?
![](https://cloud.githubusercontent.com/assets/982338/21716435/a3ed37de-d3f1-11e6-8a11-4461a7988c87.png)

Could we have a way to have a bigger button?

Also, it seems that we still need to click 2 times to mark some place:
![](https://cloud.githubusercontent.com/assets/982338/21716469/d577e0e2-d3f1-11e6-9745-20bd074335f8.png)

ie, click at the button and then we need to click again at some category.
Couldn't we have a single-click option only, with a defined action?

For example, I would like to click only one time and create a mark at the map (or mark the place in the GPX file). If I am driving, I need simple actions (only one click at the phone).

And it seems that it's not possible to remove the categories after we create them. In the example above, I didn't find a way to remove the 3 test categories buttons.
