### ISSUE TITLE
OsmAnd Editing: uploads incorrect opening_hours to OSM

### ISSUE THREAD

**Issue by pbb72** [osmandapp/Osmand#3378]
OsmAnd has a limited parsing of the opening_hours tag. This is understandable, the rules are very complicated and I don't think there is any application that supports the full ruleset.

However, the OsmAnd application needs to accept it's shortcoming, and be honest when failing to interpret a certain value.

One thing it must NEVER, EVER, do is modify a misinterpreted value and upload that back to OSM!

Example case: [node 1291410148](https://www.openstreetmap.org/node/1291410148) included opening hours exceptions for the holidays. Not the most complicated rules, but for example "Dec 27-30 18:00+ off" which means earlier closing times on those days. It seems like OsmAnd does not support "off" in combination with hours at all.

Opening this node for modification in OsmAnd, and then uploading without actually editing anything, writes the misinterpreted value to OSM.

Original value in OSM:
Mo-Fr 09:00-20:00; Sa 09:00-18:00; Dec 1-24 Su 14:00-19:00; Dec 7-24 Sa 09:00-20:00; Dec 12-22 Mo-Fr 09:00-21:00; Dec 24 **13:00+ off**; Dec 25-26 off; Dec 27-30 **18:00+ off**; Dec 31 **16:00+ off**; Jan 1 off

Value after uploading from OsmAnd (and not editing anything):
Mo-Fr 09:00-20:00; Sa 09:00-18:00; Dec 1-24 Su 14:00-19:00; Dec 7-24 Sa 09:00-20:00; Dec 12-22 Mo-Fr 09:00-21:00; Dec 24 **13:00-24:00**; Dec 25, 26 off; Dec 27-30 **18:00-24:00**; Dec 31 **16:00-24:00**; Jan 1 off

There is two things that need to change in OsmAnd:

(1) If a certain tag is not modified by the user, then OsmAnd must always maintain the original value, literally and without modification, when uploading. No "fixing" or "optimisation" done by OsmAnd. (Modifications that are not done by the user are considered "machine edits" in the OSM community, and should always be discussed before execution.) This original value should also be the one offered in the "advanced" tag editor in OsmAnd, not a (mis)interpreted one.

(2) OsmAnd needs to perform a grammar check on the opening hours value before allowing edits to it through the GUI widgets. If a value fails OsmAnd's interpretation (that is, OsmAnd does not understand every single word of it), then editing (of the original, uninterpreted value) should only be allowed through the "advanced" editor.

**Comment by vshcherb** [comment]
That's a non-intentional bug, the implementation needs to be checked.
