### ISSUE TITLE
Edit ways attributes with OSM editing plugin

### ISSUE THREAD

**Issue by rbovard** [osmandapp/Osmand#3380]
Is there a specific reason to restrict attributes editing to nodes in OSM editing plugin?

Since we can select some closed ways objects (ie. building mapped as amenity), it would be great to allow attributes editing on them. What do you think?

**Comment by DFyson** [comment]
This was brought up 2014 with #766 but I feel it's just as important to update outdated or wrong POIs as it is to add new ones. It's also changed my editing habbits somewhat. When I'm creating POI in other editors, I now tend to only create them as nodes, not attach them to ways incase someone wants to update it in OsmAnd.

**Comment by rbovard** [comment]
I totally agree with you about creating new POIs but sometimes you just want to improve existing features mapped as closed ways and you cannot.

The goal here is not to add the ability of creating new ways, but activate the edition of existing attributes. Thanks for the reference to the old issue, it would be great to have the feedback from the OsmAnd team now in 2017 (ping @vshcherb).

**Comment by DFyson** [comment]
Ya that's exactly what I'm getting at, I think updating the information attached to a way or area is just as important as being able to edit a node.

**Comment by vshcherb** [comment]
Unfortunately OsmAnd is not perfect tool for this, we have lots of data preprocessing and we can't effectively modify ways (even points sometimes) cause most of the information lost in OBF format. So we can't even properly detect ways when they are merged with each other, transformed etc.
