### ISSUE TITLE
show flags with numbers in waypoint list like on map

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/Osmand#3383]
While adding a lot of waypoints the flags on map has numbers. I like this. But when I want to add a waypoint for example between 7 and 8 I have to count the overview list in navigation mode. I would be great to have in this list the flags with numbers too.

![screenshot_20170103-114148](https://cloud.githubusercontent.com/assets/11144987/21605599/752b4560-d1aa-11e6-9f77-1540b2cf425c.png)
![screenshot_20170103-114141](https://cloud.githubusercontent.com/assets/11144987/21605605/79074760-d1aa-11e6-9c4c-f136a4dc6a5a.png)

**Comment by Alootje** [comment]
The number of the flag (on the map) is shown in the overview list (after the blue distance value).

**Comment by vshcherb** [comment]
Thanks pointing out.
