### ISSUE TITLE
Add App theme option "According to day/night map view"

### ISSUE THREAD

**Issue by quelbs** [osmandapp/OsmAnd#3384]
As stated in #2064 by @sonora, I also expect the theme of the map icons to respect my theme selection and not use the map style. I would also be happy to have "According to day-night-view (as default) / Dark / Light".

**Comment by vshcherb** [comment]
"According to day-night-view (as default) / Dark / Light".
Is really Nice to Have, we did big effort to support dark mode some screens which are likely to be used in navigation. For map style and other screens there are no immediate plans, but this is a good idea to have

**Comment by ilyaguy** [comment]
Not only map icons. I think menu and search results should follow day/night mode too.
Because now search shows results on a bright background when night mode is activated.

**Comment by snouup** [comment]
> Not only map icons. I think menu and search results should follow day/night mode too.
> Because now search shows results on a bright background when night mode is activated.

I agree. At the very least for search screen which is often used outdoors. Should improve battery life on some devices as well.

**Comment by snouup** [comment]
As well, there is the possibility to follow system dark mode setting in android os. For the menus at least. The map may benefit from a separate setting regardless - night map looks so different, some may not get used to it.

**Comment by vshcherb** [comment]
Related https://github.com/osmandapp/OsmAnd/issues/14550

**Comment by dmpr0** [comment]
## ToDo

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Day</th>
        <th>Night</th>
        <th>Sunrise/sunset</th>
        <th>Light sensor</th>
        <th>App theme</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/ad359027-83fe-41ba-850c-07fd1fd4b2a2"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/ff1756db-5f39-4cf3-8eec-2d0eeed43fb8"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/149cd3db-ce2f-4621-9b60-b8c4e9e674b6"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/b958cbfe-ecc9-4c4a-bf40-4619a82e0113"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/08640804-610d-447e-8839-b0d08ae95c1e"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>

**Comment by dmpr0** [comment]
# Review 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/dd81b867-ed65-4237-b692-7c5cb42fe066"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [ ] Add text labels for screen reading, label = mode

**Comment by MarioSwitch** [comment]
Just tested on 4.8.0#2575m, works as specified!

But, "App Theme" can only be full day, full night, or depends on device config.
You can't set it to "Sunrise/sunset" or "Light sensor" so it's impossible to sync app theme and map mode if you want to use these day/night settings 🤔

I don't know if this would be another Nice to Have, or if you want to add these 2 options right now... but I still propose 😅

**Comment by EugeneZmeuk** [comment]
**Docs**

- [ ] [Map mode](https://osmand.net/docs/user/map/vector-maps#map-mode)
   - New screen (adding a screenshot for Android)
   - New mode - "App theme" (table Android)
   - Add info about changing menu mode (dark or light) when changing Map mode.
