### ISSUE TITLE
Provide compass orientation only if device has a compass

### ISSUE THREAD

**Issue by quelbs** [osmandapp/Osmand#3385]
If a device does not have a compass available, the map orientation option using compass should not be provided, as the behaviour of ROTATE_MAP_NONE and ROTATE_MAP_COMPASS is the same in this case.

**Comment by sonora** [comment]
Please note that even devices without a magnetic sensor can in principle still know where "north" is, (via GPS during motion).

**Comment by quelbs** [comment]
For my Samsung J5 2016 ROTATE_MAP_NONE and ROTATE_MAP_COMPASS are always identical. Also I cannot imagine how a device could know where north is via GPS. The only option I can think of is that the rotation is identical to the rotate "by direction" option.

**Comment by sonora** [comment]
Via GPS, a device will know in which direction it is moving, hence it can also deduce where (relative to this vector of motion) north is. Apps like GPS Status have an implementation to display this direction (which is normally more precise than magnetic north, but works only while moving, of course).

I am not sure if we have code in OsmAnd to do the same, but we could. I would think this is the better investment than what you suggest in this issue, although, honestly, I do not think as we have it now there is much of an issue at all. I have just verified on several devices without magnetic sensor that (at rest) they display "north" as the "device top", however that is set, so no big issue here.

**Comment by quelbs** [comment]
Thank you for the longer explanation. It is not a big issue, it was just a bit confusing two have a "Rotate map by compass" option on a device without a compass.
A similar confusion occured when seeing the option "Light sensor" for map style selection on a device without light sensor. But I am fine with your judgement, these are no big issues.
