### ISSUE TITLE
OSM Editing: test name=* values for too many capital letters

### ISSUE THREAD

**Issue by sommerluk** [osmandapp/Osmand#3387]
Please test name=* values for too many capital letters

OSMAnd gives us the possibility to upload new POI to OSM (plugin). This is a great way to contribute to OSM, and I use it often.

There are quite some change-sets made with OSMand that use almost or exclusively uppercase letters for the “name” value. Example: https://www.openstreetmap.org/changeset/37042456#map=10/6.6182/2.2961 In practice, this is almost always wrong. Of course you have to use uppercase letters for abbreviations like “USA”. But from what I see in practice, in most cases people use names completely in uppercase letters like “COMPAGNIE DEPARTEMENTALE DES SAPEURS POMPIERS DE L'ATLANTIQUE”, what is wrong. Or you have half of the value in uppercase letters like in “Eglise Catholique SAINTE Jeanne d'Arc d'Allada”, what is also wrong.

The reasons might be:

- Many new mappers use OSMand for their first contributions to OSM, and they might just not know yet that writing in uppercase letters is not a good practice.

- OSMand is used on smart phones, so you don’t have a hardware keyboard like on a desktop computer, so typing is less comfortable and various special characters are difficult to type. Switching between uppercase and lowercase is less comfortable on smart phones. (Also emails coming from smart phones often have more errors that emails coming from desktop computers – also because, when using a smart phone, people often seem to care less about errors as when using a desktop computer.)

It would help if OSMand could display a warning message if too many uppercase letters are used. For a short “name” value with 3 characters, 100% uppercase letters is likely okay (“USA”). For long “name” values with 30 characters, having more than 25% uppercase letters is likely to be wrong. Osmose, the quality assurance tool, implements such a check:

- Class 803 "Name with uppercase" : word in capital letters.
- http://wiki.openstreetmap.org/wiki/Osmose/issues
- http://osmose.openstreetmap.fr/de/errors?item=5010&class=803

Implementing such a warning message would improve the data quality. At least in West Africa, it would make a big difference…

**Comment by sommerluk** [comment]
Thanks a lot!

**Comment by MiMoHo** [comment]
I understand the idea, but this should be rather a one-time warning that can be skipped for the future than a persistent notice every time one types ≥4 capital letters. There are some common brands in Germany, maybe also in Europe, whose name is an abbreviation and written in capital letters like IKEA, REWE, EDEKA. Confirming the unhelpful warning is nothing but obstructive.
@vshcherb please improve the implementation.
