### ISSUE TITLE
use geopackage sqlite instead of custom sqlite db

### ISSUE THREAD

**Issue by legrostdg** [osmandapp/Osmand#3388]
It would be cool if Osmand could use geopackage sqlite as an alternative to its custom sqlite db for maps: http://www.geopackage.org/

This format is a standard, uses sqlite (so is not much different from Osmand custom sqlite solution), and is supported by GDAL: http://www.gdal.org/drv_geopackage_raster.html

It would help a lot to convert maps for Osmand: no need to use mobac with its bogus UI, or a proprietary software, just use `gdal_translate -of GPKG byte.tif byte.gpkg`

**Comment by vshcherb** [comment]
It is not much about standards, it is still hard to say what is more standard on mobile devices. We don't plan to change it to keep backward compatibility.

**Comment by legrostdg** [comment]
OK. Note that I did not talk about replacing the current format, just adding support for another one. Geopackage seemed like a good candidate, but I do not care so much about the format. It would just be nice if it could be supported by GDAL, so that a lot of alternative format could be easily converted for Osmand.

**Comment by vshcherb** [comment]
I'm not against it, I just feel that our backlog full of other issues.

**Comment by legrostdg** [comment]
Another possibility would be to add Osmand's custom sqlite support directly to GDAL. It would reduce the need of custom scripts to build Osmand maps and would add direct support for all the formats GDAL supports. The MBtiles driver could be used as a basis.

**Comment by legrostdg** [comment]
Do you think it would be valuable to retitle the bug and reopen it, or do you prefer to keep it closed because you don't intend to work on this? I feel like it's better to have an open bug, as it avoids people from asking the same thing again and again, and gives ideas for new contributions.

**Comment by HarelM** [comment]
Has this been done in either direction? either support GeoPackage or Add a driver to GDAL?

**Comment by khimaros** [comment]
@vshcherb would you consider a pull request that added support for another format?

i agree with others here that it would be great to support a format which GDAL or QGIS can work with. this would open a wide variety of public government data maps to be used in OSMAnd where today a convoluted and quite resource inefficient method like https://github.com/khimaros/osm_land_use/ is needed. even then, this method produces very low resolution data.

notably, the Spatialite format mentioned at https://gdal.org/drivers/vector/sqlite.html is a vector based format, which results in much smaller databases which preserve the published shapedata perfectly when converting from GeoDB produced by many United States government agencies.

**Comment by HarelM** [comment]
@khimaros if you are willing to write this, I think maplibre might be a good place to facilitate this.
Feel free to PM me on maplibre's slack, see here: https://maplibre.org/community/
