### ISSUE TITLE
Update world basemap

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#3389]
With the world basemap reaching 6 months, isn't it a good time to update it?

**Comment by aceman444** [comment]
Are there any new continents created on the planet Earth? :)

Ok, seriously, yes it would be useful to update the World map from time to time, but it would be useful (and saving the server/user bandwith) to only push a new version onto users when something substantial has changed in the World map. Maybe the file could be periodically created but the compared to the previous version on the server to see if there are any worthy differences. If not, no new version would be published.

**Comment by naoliv** [comment]
I asked this mainly for the highways overview.

**Comment by xmd5a2** [comment]
Updated
