### ISSUE TITLE
add specification of the custom sqlite format used by Osmand.

### ISSUE THREAD

**Issue by legrostdg** [osmandapp/Osmand#3393]
It would help inter-compatibility if the specification of the custom sqlite format used by Osmand could be published somewhere in the doc.

**Comment by DFyson** [comment]
This would be nice to have. Otherwise have to look through one of the building scripts such as https://github.com/osmandapp/OsmAnd-tools/blob/master/obf-generation/hillshade/gdal2tiles_gray2alpha_sqlite.py for the hillshade tile database generation.

**Comment by vshcherb** [comment]
The class responsible for this support is this https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/SQLiteTileSource.java#L33. Though I think we could a small Readme.md file and show the table structure. OsmAnd basically supports "BigPlanet" format and slightly modified format in order to change zoom numbering. It also adds some columns to the format to support tile expiration and external url to download.

**Comment by vshcherb** [comment]
What needs to be done for this task is create a small Markdown table describing tables and colums we use. Short description from me:
- OsmAnd sqlite is based on "Bigplanet sqlite" which was supported by MOBAC before OsmAnd.
OsmAnd added couple of columns & tables to extend the format:
Table "info": 
- url - url template to download tiles with zoom - $1, x - $2 , y - $3
- rule - specific to osmand (mostly ""  or "beanshell" for evaluating url template for downloading tiles) 
- tilenumbering - supported "BigPlanet" or "". If BigPlanet zoom will be inverted and calculated as z = 17 - zoom 
- timeSupported - "yes", "no" - means that tiles table has column "time" means when tile was retrieved
- expireminutes - integer - if tiles should be expired in given minutes, they will be displayed but they will be downloaded again
- ellipsoid - integer 1/0. Elliptic mercator (Yandex tiles)
- minzoom, maxzoom - (also should be inversive in case of BigPlanet)
- referer (?)

**Comment by vshcherb** [comment]
@sonora Could we please added to documentation or to MD file somewhere.

**Comment by sonora** [comment]
I will put this in a TechArticle on our web site, ok?

**Comment by vshcherb** [comment]
Good

**Comment by sonora** [comment]
Ok, see here: http://osmand.net/help-online?id=technical-articles#OsmAnd_SQLite_Spec

It is not pretty yet, but that is work required in general on our overall style sheet or table setup used there.

But f there is a content issue, please let me know here.
