### ISSUE TITLE
Select polygons

### ISSUE THREAD

**Issue by QuestionsForThose** [osmandapp/Osmand#3396]
I would like to be able to select polygons in order to access the "Show Description" function. 
Perhaps there are 2 ways this can be accomplished.

For example there is a building nearby with a node on the perimeter as building = apartments. I would like to add more detail and access that information in osmand.

1. Make the node on the polygon that contains the tagging information obvious so that it can be selected.

2. Click anywhere in the polygon to select the tagging information

I think point 2 is the most intuitive and therefore best outcome.

**Comment by vshcherb** [comment]
For many polygons especially named, we are planning to add extra center icon which will be clickable. For example, forests with a name.

**Comment by sonora** [comment]
Badly needed also for mappers, as some POIs like shops etc. are increasingly mapped as areas (mostly buildings), and things like e.g. opening times for those cannot be edited in OsmAnd yet, I think (?).

**Comment by sonora** [comment]
Implemented, I think.

**Comment by QuestionsForThose** [comment]
Please note this has not been fully implemented. Yes you can select a polygon however insufficient information is returned. For example a polygon might have the tag of building=yes, office=estate_agent, hours=* etc. Only the Building tag will be returned. Can more detail be returned please?
All this detail is currently returned for POI but not polygon.
