### ISSUE TITLE
Announcing nearby favourites grossly miscalculates distance

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#3397]
I don't know why "announce nearby favourites" was switched on, either I did that by accident or it activated itself? Anyway, it announced far away favourites by misjudging the distance, quite a lot. 

On the example below, it announces [Poststadion](https://www.openstreetmap.org/way/4676150) while I drive [Tiergartenstr](https://www.openstreetmap.org/way/25041360), in reality 2218m away, shown as 81m (live screenshot):

![20170105-221146_poststadion](https://cloud.githubusercontent.com/assets/8266355/21741780/020ed0f8-d4e1-11e6-9441-57742e54c148.png)

OsmAnd-master-nb-2017-01-05

**Comment by sonora** [comment]
Not entirely sure here, but since the actual driving distance to an off-route favorite is unknown anyway (OsmAnd does not calculate routes to see how to get to them), chances are we do not actually display the "line of sight" distance to the fav itself, but rather the actual driving distance to the point on your route which is closest to that fav.

Debatable what makes more sense. But in any case, I have not checked the code, just a suspicion.

**Comment by polarbearing** [comment]
Hm that could be it. I have another case where it displays "20 m" before the route turns away from pointing towards that Fav. 

Highly misleading anyway.

**Comment by sonora** [comment]
From what I see in the updatePointInfoView code, the distance display should be something like
`"distance on route" + "distance to the side of the route"`, so in this case maybe something like `81m + 2000m`. Maybe it breaks into 2 lines and the "+" portion does not fit in the display or something ...

**Comment by sonora** [comment]
Something is weird here: I have tried to reproduce your issue on several devices, even some with Android system font size set to "Large", and cannot reproduce. For me it always displays the `on-route "+" off-route distance`, as I stated above (usually broken over 2-3 lines) ...

**Comment by polarbearing** [comment]
Turn the device in landscape mode. I just simulated a route, when the device is portrait I get the 2 lines you have as well, and turning in landscape brings only the single line as in my first screenshot. 

Still the voice announcement "you are passing Fav XYZ" is confusing if you are still 3 km away. If an announcement is made at all in this situation, the air distance should be told.

Screenshot might follow tomorrow.

**Comment by sonora** [comment]
- Ok sounds like a bug in the landscape view config file then, no need for another screenshot, I guess.

- Threshold radius can apparently be set on the Waypoints screen, in the second screenshot I posted above, (which should be accessible directly from the drawer menu, or also by tapping on the Waypoint flag icon on the config route dialog).

- Regarding the idea to add a distance to the announcement: Will have to check this. I never work with this functionality of announcing this, so I have no good feeling how much wording we can add before the functionality/talking becomes unusably crowded. I think someone using the feature should let us know here what makes sense, before I would implement anything. For now I guess "passing" is not incorrect wording, and how much off the route a point really is before it matters is hugely different in e.g. an inner city or a remote desert area, so manually configuring the threshold radius accordingly seems like a valid solution.

**Comment by polarbearing** [comment]
Ok I found the radius setting, however it is a bit obscure. I would expect this in either General or Profile Specific Setting, probably in the latter close to the "Announce..." settings. 

As said I stumbled accidentally over the problem, so as you said we can leave the usability discussion to those who use the feature.

**Comment by sonora** [comment]
@dmpr0  Dmitriy, The original issue sounds like a bug in landscape `map_hud_top.xml`? Maybe you can have a look when you get a chance? Thx - Hardy

**Comment by vshcherb** [comment]
Looks like a bug in landscape mode.
