### ISSUE TITLE
Tapping the Quick action button crashes OsmAnd

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#3398]
Log attached: [exception.log.txt](https://github.com/osmandapp/Osmand/files/691727/exception.log.txt)

**Comment by sonora** [comment]
Also: Tapping Quick action too early after app start can produce this NPE:  [exception.log.txt](https://github.com/osmandapp/Osmand/files/692512/exception.log.txt)

**Comment by sonora** [comment]
And: [exception.log.txt](https://github.com/osmandapp/Osmand/files/694852/exception.log.txt)

**Comment by vshcherb** [comment]
Fixed
