### ISSUE TITLE
Add Lower Sorbian Language as map lanuage

### ISSUE THREAD

**Issue by streckenkundler** [osmandapp/Osmand#3400]
Hello,

th Lower Sorbian (dsb) (german: Niedersorbisch) should be added to Osmand. This language is a language other than the Upper Sorbian (hsb).

Thanks an Regards,

Sven

**Comment by sonora** [comment]
http://osmand.net/help-online?id=technical-articles#What_Languages

**Comment by streckenkundler** [comment]
Sorry, i mean, the Lower Sorbian language (ISO-code dsb) should be display on the map. It is similar to the Upper Sorbian language- Compare https://github.com/osmandapp/Osmand/issues/2714 and specifically https://github.com/osmandapp/Osmand/issues/3043.

Thanks.

Sven

**Comment by sonora** [comment]
I understand, but where is the language file for it? I cannot add a language which nobody has translated yet?
