### ISSUE TITLE
Some comments about the quick button

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#3402]
From https://github.com/osmandapp/Osmand/issues/3376#issuecomment-270885789

Isn't it possible to configure the button to use it at the left side?
<img width="180" alt="a3ed37de-d3f1-11e6-8a11-4461a7988c87" src="https://cloud.githubusercontent.com/assets/845735/21836398/422cb632-d7c5-11e6-83e2-e7bf88c2648a.png">

Could we have a way to have a bigger button?

Also, it seems that we still need to click 2 times to mark some place:
<img width="180" alt="d577e0e2-d3f1-11e6-9745-20bd074335f8" src="https://cloud.githubusercontent.com/assets/845735/21836455/916f9548-d7c5-11e6-8260-d2ffadf20b53.png">

ie, click at the button and then we need to click again at some category.
Couldn't we have a single-click option only, with a defined action?

For example, I would like to click only one time and create a mark at the map (or mark the place in the GPX file). If I am driving, I need simple actions (only one click at the phone).

And it seems that it's not possible to remove the categories after we create them. In the example above, I didn't find a way to remove the 3 test categories buttons.

**Comment by jf-simon** [comment]
You can move the button with long tapping on it. 
Under menu->configure screen-> quick action you can manage your action

**Comment by naoliv** [comment]
Didn't know about the long tap, thanks!

But even with only one action, I still need 2 clicks: one at the quick action button and another click at the button with the action.

**Comment by jf-simon** [comment]
Yes, it would be nice to have the ability to add an action directly on the screen. like the blue button which opens the quick action screen. but it would runs the action directly.

**Comment by pebogufi** [comment]
Situation: The quick action button is activated and visible.
When I do a long tap somewhere on the screen to mark a position, the quick action button will be hidden, this is wrong (for me).
To show him again for connecting the position to a action I have to tap anywhere on the screen.
To wipe the window on bottom down, is not a good idea, then the position is lost.
Version: 2.6.0#20058 (last night).
Peter

**Comment by pebogufi** [comment]
Situation: The quick action button is activated and visible.
When I do a long tap somewhere on the screen to mark a position, the quick action button will be hidden, this is wrong (for me).
To show him again for connecting the position to a action I have to tap anywhere on the screen.
To wipe the window on bottom down, is not a good idea, then the position is lost.
Version: 2.6.0#20058 (last night).
Peter

**Comment by naoliv** [comment]
Another thing when configuring an action like this, where the name will use the address where I am:
![](https://cloud.githubusercontent.com/assets/982338/21816092/fdfa0296-d745-11e6-91ca-375ad7fa26c3.png)

osmand takes a lot of time calculating the location like this:
![](https://cloud.githubusercontent.com/assets/982338/21816094/00967ed0-d746-11e6-9dad-8d8e58d5f0f6.png)

Couldn't this step be made in a background task? (since it blocks the view when driving)

**Comment by pebogufi** [comment]
The Search window should have a abort button

**Comment by vshcherb** [comment]
Not sure if the github is proper place to have long discussions though it is a place where it is possible. Please make screenshots smaller or hide it under links somehow(?) so it would be easier to reply and follow up on all questions

**Comment by vshcherb** [comment]
Search Address would be good to have in background unfortunately we have single thread issue (concurrency around some code in the app), I think it is not done intentional, just worth to fix it later.

Single click actions were not purpose of that story, the main purpose to make it fully flexible and 2 click actions. I think there is a big value even in 2 click actions, especially if we could make 1st click connected to a physical button or a voice command.

**Comment by vshcherb** [comment]
```I have checked "dispay position always in center".
When I tap quick action button, the position marker is set to somewhere on the bottom, it should be in center due to my setting.```
During testing we discovered that moving map after click confuses people orientation and we decided to not move the map except cases described below. Actually it is quite easy to get used that marker appears on the bottom. Special use cases are 1) marker is visible on the map 2) map is linked to my location - in these cases marker will preserve the location

**Comment by vshcherb** [comment]
``Situation: The quick action button is activated and visible.
When I do a long tap somewhere on the screen to mark a position, the quick action button will be hidden, this is wrong (for me).``
Makes sense we will consider how to do it.

**Comment by sonora** [comment]
I have taken the liberty to re-size your screenshots above.

In general, most screenshots posted on github are much larger than needed to make the point, and really obscure the overall discussion, so I hope people can re-size to e.g. 50% before posting in the future. In this fashion, where appropriate, you can also put screenshots next to each other (in one line), not just below each other, which lengthens the threads.

**Comment by naoliv** [comment]
Sure, sorry for the big screenshots.

I am asking for a 1-click only button, if possible, since I am usually driving. Looking at the phone and clicking only one time should be a a little safer than doing this twice.
I only need to have a position marked in the map, to review it later.

What I imagine is to have an option to define the quick button behavior: do only one specific thing (this is what I need) or open the menu with all the possible actions.

TomTom GPSes has a similar feature, where we can configure a quick button for a specific action (ie, marking the current position).

**Comment by vshcherb** [comment]
@naoliv If you define only 1 action it is possible to make it default, though for many use cases I've heard 1 quick action is not enough. So this strategy would be very limited.

**Comment by naoliv** [comment]
@vshcherb Sure, I don't want to exclude the cases where people need multiple choices.
By "it is possible" you mean that it's possible right now (I really can't find a way for this) or that it could be implemented, please?

**Comment by vshcherb** [comment]
I meant that doesn't require big changes and easy to implement

**Comment by naoliv** [comment]
I would appreciate it, thanks!

**Comment by Alootje** [comment]
I would also like to have the 'one-click'  functionality in the quick button.

Furthermore I would like to know if it is possible to add a 'skip next waypoint' button?

**Comment by vshcherb** [comment]
Skip next waypoint sounds quite difficult cause we don't have that action at all and usually quick action only duplicate existing functionality.

**Comment by Spielmops** [comment]
More than 1 year later:anything new  with this request? I am waiting for it, because I need it for marking map errors while driving ...

Spielmops

**Comment by tduva** [comment]
I too would like to add a marker with a single click. Adding the marker already works fine, but I don't really need the quick action selection, since I only have one quick action. So if the action could execute immediately, that would be useful.

**Comment by MasterOut** [comment]
I really like the quick button feature for enable/disable groups of POI overlays. But sadly only standard POI's are available. Wouldn't it be cool to have a search like in the normal search for categories of POI types to be added to a quick button action?

**Comment by vshcherb** [comment]
@MasterOut  you can create Custom Poi Filter and give it a name (Save as) after that you should be able to use it with POI filuter.

That issue will be closed cause there are multiple unrelated requests, please open new separate issue for each request and it might help to prioritize some features over others.
