### ISSUE TITLE
Tile server minimum/maximum zoom config restricts users zooming. Bug or feature?

### ISSUE THREAD

**Issue by DFyson** [osmandapp/Osmand#3405]
I thought the zoom restrictions in the tile server configuration were strictly so OsmAnd isn't trying to request non-existent tiles. Is there a reason why the physical zoom is restricted from the min zoom to the max zoom + 2 ? I would expect if there are no tiles at a zoom level, OsmAnd would check other zoom levels (higher then lower) and fill them in.

To work around this, I can change the map magnifier to minimum zoom.
This also isn't an issue when I use the tile map as an overlay.

**Comment by vshcherb** [comment]
This is a feature. There is not many use cases found to support this.
