### ISSUE TITLE
allow to hide/reorder items in the context menu

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#3407]
When I have multiple plugins enabled (like OSM editing and Audio/Video notes), the context menu (shown when there is a location selected on the map and the 3-dot button is pressed) contains many items. It contains items I do not need and my most used item is always scrolled off the bottom of the screen. This became a problem in OsmAnd 2.5 where the spacing between the items was increased so that the items now do not fit all at once on the screen. It was fine in 2.4. but that was luck. If I had more plugins then again there could be too many items.

So I propose some way do hide items I do not need. E.g. from Video/Audio notes I only need the "Take photo" item but not the Take video item. 

Or if it is easier, reordering the items would be useful so the not needed items are the ones on the bottom of the list (thus offscreen).

Thanks.

**Comment by vshcherb** [comment]
Quick action suppose to solve this issue.
