### ISSUE TITLE
routing or map issue?

### ISSUE THREAD

**Issue by bitboy85** [osmandapp/Osmand#3410]
Using the red marked road would be shorter and faster. Maybe its a map issue and the road is tagged wrong.
![routing](https://cloud.githubusercontent.com/assets/6197580/21823448/542f5cc6-d77b-11e6-83dd-80af50df1310.png)
https://www.openstreetmap.org/edit#map=17/49.81151/6.42223

**Comment by bitboy85** [comment]
Here is another place where routing is wrong. i checked the map but i couldn't find the reason.
https://www.openstreetmap.org/edit#map=16/49.6559/6.1949
![screenshot_2017-01-10-21-43-42](https://cloud.githubusercontent.com/assets/6197580/21824366/6580441e-d77f-11e6-9d07-8aabd916d566.png)

**Comment by quelbs** [comment]
For the first example the computed time for the red route is significantly longer (4 minutes). 
[Mapzen](https://www.openstreetmap.org/directions?engine=mapzen_car&route=49.8090%2C6.4306%3B49.8112%2C6.4172#map=16/49.8111/6.4239) also takes the primary road  whereas [OSRM](https://www.openstreetmap.org/directions?engine=osrm_car&route=49.8090%2C6.4306%3B49.8112%2C6.4172) takes the secondary road.

In the second case I think it is a data problem. It looks like [Relation 5506793](https://www.openstreetmap.org/relation/5506793) is the problem. The relation states you are not allowed to make a u-turn from [way/372306797](https://www.openstreetmap.org/way/372306797) to [way/31661733](https://www.openstreetmap.org/way/31661733) which is probably confusing the Offline Routing as from and to are a continuous road. Other Routing algorithms seem to ignore this relation.

**Comment by bitboy85** [comment]
As i know the place in the first example you can believe me that the red one is faster, as tagged correctly there is a part of cobblestone where you can't drive that fast and next to it a market place where often pedestrians are crossing the road. Compared to google maps https://www.google.de/maps/@49.8118418,6.4249365,15.75z "Brückengasse" is not marked as primary.

No u_turn is right. You're not allowed to do so on this part, but choosing this way doesn't need a u_turn so i still don't understand why its not working. Mapzen and OSRM are doing fine: https://www.openstreetmap.org/directions?engine=osrm_car&route=49.6605%2C6.1957%3B49.6488%2C6.1862 (thx for showing me this)

**Comment by vshcherb** [comment]
@bitboy85 Could not reproduce bug with newly generated map https://www.openstreetmap.org/directions?engine=osrm_car&route=49.6605%2C6.1957%3B49.6488%2C6.1862

**Comment by vshcherb** [comment]
1st example:
According to engine everything is correct. 1st route is faster routing_time = "129.2089"   vs 
routing_time = "187.24547" . 
I could explain it only by 	<point 2 highway="crossing" crossing="uncontrolled"/>
Though it looks weird (every crossing adds 5 seconds penalty)

**Comment by vshcherb** [comment]
Funny enough explanation is very simple. This road https://www.openstreetmap.org/way/244665201#map=16/49.8107/6.4273 has speed limit 90kmh but the other road only 50kmh. Thus the first route is faster.
