### ISSUE TITLE
[Feature issue] Add organic food option in food search

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#3413]
Our user requests adding the option 'organic' for cafes and stores in the main search by category.
![scr](https://cloud.githubusercontent.com/assets/12711814/21848054/a830f8ca-d807-11e6-9b72-d214b49337f5.png)

**Comment by xmd5a2** [comment]
Fixed
https://github.com/osmandapp/OsmAnd-resources/commit/baccbe1d8c146805bded3426d15c614a686c2b26
