### ISSUE TITLE
Quick button "Add favorite" interim dialog does not show

### ISSUE THREAD

**Issue by quelbs** [osmandapp/Osmand#3415]
Steps to reproduce:
- Add Action "Add favorite", activate "Show an interim dialog" and set a "Name"
- Select quick action and select "Add favorite"

What happens:
- The favorite is added directly

What is expected to happen:
- The "Add favorite" dialog should be shown.

Note: For "Add GPX waypoint" the interim dialog works as expected.

**Comment by vshcherb** [comment]
As I see it is fixed already
