### ISSUE TITLE
Option to display GPS precision in the GPS info widget

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#3416]
While navigating and using the GPS info widget we can see only the number of used and visible satellites, like this:

![](https://cloud.githubusercontent.com/assets/982338/21862520/b532e2b8-d820-11e6-984b-f86a27a37cdd.png)

Clicking at it we can see only an option about the GPS wake-up interval and an option to open an external GPS status app.

Couldn't we have a way to configure it to display the precision instead the number of satellites?
For me, seeing that my current precision is 5m, for example, is more useful than the number of satellites.

**Comment by polarbearing** [comment]
The android reported "precision" is visualised as a blue circle around the current position. 

The android reported value is snake oil anyway, there is no such thing as a 5m precision.

**Comment by naoliv** [comment]
"Accuracy"
But anyway, we have a better feeling in seeing "7m" than "13/22".
It should not replace the number of satellites, but offer the accuracy (even if imprecise) for anyone who wants.

**Comment by sonora** [comment]
I have never fully done the research, but chances are that the Android documentation https://developer.android.com/reference/android/location/Location.html#getAccuracy() is not accurate. From what I have read about GPS math, the algorithm does not readily produce data to deduce something like "estimated accuracy of this location, in meters". Someone would have to go to the Android source code to evaluate what their code is and what it actually returns. My major question mark is whether it really relates to "meters", like most people think. It may be actually be "hdop".

Putting that aside, I guess we could somewhere provide a digit-display of the value (once we know what it is). (We include it in recorded GPX tracks under the <hdop> tag.)  Question is, where would we put the display, so it does not clutter the screen? Right in the widget, after the sat count? Or on some popup-dialog?

Having said that: Why is the optical indication on the map not enough for you? It has the "beauty" of essentially only being visible exactly when accuracy is a concern (at the selected map zoom). Isn't that the much more intelligent way of dealing with depicting this?

**Comment by naoliv** [comment]
What I imagine is:
The user goes to menu → `Configure screen` → click at `GPS info`
![](https://cloud.githubusercontent.com/assets/982338/21930052/181a3b50-d97b-11e6-887d-b6402356362a.png)


It will let the user choose how/what he would like to see.

One option is the current `using/visible` satellites number.

Another option would be the accuracy.
Taking a quick look at SatStat, [it uses `location.getAccuracy()`](https://github.com/mvglasow/satstat/blob/master/src/com/vonglasow/michael/satstat/ui/GpsSectionFragment.java#L161)

Example (it's the `Error`):
![](https://cloud.githubusercontent.com/assets/982338/21929147/0a26970a-d976-11e6-95f2-1366045871ea.png)

Third option would be a quality/strength bar.
At least when I used commercial GPSes, it was common to have a GPS signal strength bar, like this:
![](https://cloud.githubusercontent.com/assets/982338/21928745/b6800a70-d973-11e6-9774-f561a62086c8.gif)

Maybe it's possible to use [some DOP value](http://stackoverflow.com/a/30528938) (PDOP maybe?) [with this table](https://en.wikipedia.org/wiki/Dilution_of_precision_(navigation)#Meaning_of_DOP_Values) to create a quality/strength bar.

It's not about adding more widgets at the screen, but letting the user choose what he wants to see (number of satellites, accuracy, a quality/strength bar, etc)
![](https://cloud.githubusercontent.com/assets/982338/21930573/e3d661fe-d97d-11e6-823d-686189f57dfb.png)

**Comment by sonora** [comment]
Ok, thanks! I have to admit it looks nice! But I see no takers for coding it right now.

Frankly, I am also not convinced it should be done, reasoning is as follows:

- We are a map app. We already depict all the necessities of GPS reception in apt form, both on the map, and in the widget.
- Advanced users interested in signal or sensor quality can (and will) use a dedicated app much more specialized in this functionality
- We would complicate the app by yet another submenu, and frankly, without any additional map-relaed functionality at all. So I see no value-add.

**Comment by naoliv** [comment]
Sure, I understand.
Personally I would like the "accuracy" option (at least for me, the number of satellites doesn't say too much about the reception).
I would contribute with code if I could, but unfortunately I don't know.

Could we keep this ticket open as a feature request, please?

**Comment by sonora** [comment]
My advice would be to not bother with that at all. If there is an accuracy issue significant to the map zoom you are viewing, it will be clearly depicted "live and in color" by the hdop circle we draw on the map.

Whenever that is not visible, it is too small for you to bother at that map zoom. So also no need to even display the GPS widget or worry about the number of satellites in your case.

The one change I think about implementing, because it is unobstructive an easy, is to show the Android "accuracy" value, whatever it is, in the Position's Context menu description, maybe I will take a shot at that.

**Comment by vshcherb** [comment]
We can but you could always check it in the recorded track. No much you can about GPS in android (to affect it).

**Comment by sonora** [comment]
@vshcherb How about adding a live "hdop" display line (showing the value of `getAccuracy()`) in the "My Position" context menu, under where it shows the LatLon line? That should settle this for good?

**Comment by naoliv** [comment]
Sorry for the long delay to answer here, but the current blue circle isn't always a good indicator for the current accuracy.
For example:

![](https://cloud.githubusercontent.com/assets/982338/23342033/59c5645c-fc31-11e6-824a-454dc9f0e26f.png)

In the first picture, with the zoom at the `50m` scale, we may think that we are located inside that circle.
But if we zoom out to `100m`, the circle size just don't change.
It goes up to the penultimate screenshot, with a scale of `1 km`.
Only at the last screenshot we can properly see how accurate our location is.

Depending on the zoom level it's just not possible to have correct notion of the accuracy.

That is another argument to have an option to display a number-based accuracy in the GPS info widget.

**Comment by polarbearing** [comment]
A number-based value is misleading, as @sonora analysed correctly in #3445.

**Comment by naoliv** [comment]
As misleading as the blue circle.
Having an option to display the `location.getAccuracy()` value shouldn't be worse than the blue circle.

**Comment by sonora** [comment]
@vshcherb  The screenshots above seem to indicate a bug, but I cannot reproduce. On my devices the blue disk always scales correctly when zooming the map. (I always use "GPS only" as the Location method of choice in the Android settings.)

Victor, if you can reproduce the issue in @naoliv 's screenshots, it may be worth to reopen this and investigate?

Regarding a numerical display in meters/feet: I guess on the MyLocation context card is where it would not hurt (and would logically belong?).

**Comment by sonora** [comment]
PS: Some more testing, it looks like this: We seem to limit (cap) the diameter of the accuracy disk to the screen width. Not sure that is a bug or a necessity, because simply giving the entire screen a blueish background when zooming in very far would likely not be informative either.

So the "true" accuracy as reported by the Location module is likely the one reflected on your far right screenshot. I guess it scales correctly when you zoom further out?

I am rather convinced that such huge inaccuracy must come from using cell phone towers or WiFi hotspots for location determination, with GPS this seems unlikely.

**Comment by breversa** [comment]
For what it's worth, SatStat (https://github.com/mvglasow/satstat) uses different colours and displays different location providers (red for satellite, blue for cell/wifi, grey for passive/last known position).

**Comment by vshcherb** [comment]
@sonora That's a design when precision is too huge like 50km we don't fill the whole area with blue circle but always display a visible circle. If you zoom out, you will see the precision.

**Comment by sonora** [comment]
Yes, no change needed,to the circle-drawing, I think.

How about adding a single line "Accuracy = x meters" to the context menu of the "My Position" point (under the coordinates lines)? That would, upon tapping your position, provide the numerical information requested here in an unobtrusive way.

**Comment by polarbearing** [comment]
> about adding a single line "Accuracy = x meters" to the context menu 

if doing so you might call it "Android accuracy =..." to indicate it is some derived snake oil and not a reliable measurement. 

Personally I'm happy enough to get "bad" GPS fixes visualised with the circle as it is. I do not find it misleading, as it tells me "reception is poor, you are in this city here, but don't rely on anything else."

**Comment by sonora** [comment]
Yeah, we are on the same page there ... :)

But if someone is desperate for us displaying a numerical value, that would be the logical place to put it.
