### ISSUE TITLE
Unknown duplicate notification

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#3419]
Unknown duplicate notification while navigating https://goo.gl/photos/aYiLvVnvaLBmNJFv7

**Comment by sonora** [comment]
I think this is the same as #3386, I commented there what I found out about it.

**Comment by vshcherb** [comment]
I just don't remember it before may be it was caused that I upgraded to Android 7.0 and somehow correlated with Pebble notification. 
https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/voice/AbstractPrologCommandPlayer.java#L104
or 

https://github.com/osmandapp/Osmand/blob/762fbdc5086e676de6241844cf7edd5b2a095685/OsmAnd/src/net/osmand/plus/voice/TTSCommandPlayerImpl.java#L143

@crimean do we need this Android wear notification or it is deprecated and was a wrong path?

**Comment by sonora** [comment]
Yes, I do believe it was the Android upgrade. Not sure which event exactly Android now reacts to by flashing a notification here... but the issue I reference above (and I could reproduce that) reports it to pop up only if a voice prompt would sound **and the users has muted it under the route config settting**, so somehow Android seems to pick up some event when we do exactly that...

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/commit/26592ed7a270171961931395ededf091b61db3ce

**Comment by sonora** [comment]
So it's an Android feature, not a bug ;)
