### ISSUE TITLE
No notification on enforcement - speed_camera

### ISSUE THREAD

**Issue by bitboy85** [osmandapp/Osmand#3423]
I'm using the most recent version with maps from january 2017 but i do not get a notification for a speed camera. Nether visual nor accoustic.
https://www.openstreetmap.org/edit#map=17/49.68829/6.23455
This might be related to: https://github.com/osmandapp/Osmand/issues/3069

**Comment by vshcherb** [comment]
I checked that bug and actually the point of speed camera is not tagged on the line. Please tag it to the line or use relation:enforcement.

**Comment by polarbearing** [comment]
Well, more precisely, if the camera node already the correct device position beside the street, add the [enforcement relation](https://wiki.openstreetmap.org/wiki/Enforcement), and do _not_ move the node to the road line (though OsmAnd of course supports it for the old-fashioned tagging).
