### ISSUE TITLE
[Feature request] Free customizable hitching patterns as shader in renderer

### ISSUE THREAD

**Issue by Thunichgud** [osmandapp/Osmand#3425]
For a better visibility of specific areas hitching patterns as shaders (e.g. shader="danger", shader="hazard") are very helpfull. But the few in the renderer build in shaders are not customizable and reserved for specific use.  So it would be nice to add customizable hitching patterns in the renderer. 
Patterns could be: diagonal lines, horizontal and vertical lines, diagonal crossed lines, horizontal and vertical crossed lines. 
The customizable attributes could be: Line color, background color, line thickness, line distance, pathEffect, area text, text color, textHaloRadius, textHaloColor.

**Comment by vshcherb** [comment]
This is achieavable by using custom rendering style. There are no plans to implement it soon.
