### ISSUE TITLE
constant application_dir_change_warning3 moving instead copying?

### ISSUE THREAD

**Issue by kbs170** [osmandapp/Osmand#3427]
the constant application_dir_change_warning3 is defined with

Do you want OsmAnd to also copy its data files to the new destination?
and 
Soll OsmAnd auch die Datendateien an den neuen Ort kopieren?

The Translation ist correct. But it seems to be a "moving" instead of "copying"?

![screenshot_2017-01-13-08-25-06](https://cloud.githubusercontent.com/assets/1921140/21923701/ddc273d2-d975-11e6-9fc7-805414c4ad37.png)

**Comment by sonora** [comment]
Not quite sure, but I think it is a "move" if OsmAnd has write access to the "old" folder, and a copy if not ...

**Comment by kbs170** [comment]
ok. 
If there are no rights for delete? Better to check it before and replace "move" with "copy". Or after: read the return value from move-method, if not successfull: "Sorry, can't delete the source-files."

**Comment by sonora** [comment]
Looks like no action planned for this (?).
