### ISSUE TITLE
Aggregate subsequent identical warnings

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#3429]
There are some situations where multiple identical hazards lead to repetitive announcements (voice). 

Example 1 are the crossing of 2 parallel tram tracks with a street: [1](https://www.openstreetmap.org/node/1637970843) and [2](https://www.openstreetmap.org/node/1821850633) which are 23m apart due to the angle they cross the road. That could be easily aggregated into a single announcement. 

Example 2 are subsequent bumps for traffic calming, on [this road](https://www.openstreetmap.org/way/4396816) we have 12 traffic_calming=cushion mapped on all segments together. While the pairs in proximity could be aggregated into one announcements, you would still hear the warning 6 times. It would be better to have a separate warning about the multiple hazards, which would however need a different TTS text. 

Example 3 is different, as there is a [single speed](https://www.openstreetmap.org/node/27543311) cam announced twice, maybe the device and the enforcement-relation are counted separately? (actually there are 2 cams per direction in the tunnel, thus 4 announcements).

**Comment by sonora** [comment]
I think it's a valid request. But it still needs thinking about where we want to get to. My first impression is we would NOT want to aggregate the actually identified hazard points (meaning if there are really 3 pedestrian crosswalks in succession, we would still depict that as such on e.g our waypoints dashboard, waypoints screen, warning display on the map screen, etc. But we would somehow suppress the voice propmts for successive identical warnings for a certain grace period (time or distance, not sure)?

**Comment by sonora** [comment]
Thinking about it some more, an adequate solution may even be to aggregate still further, and announce ONLY ONE warning at all per a certain time interval. All warnings should have the same "wake up" effect, you mostly have to slow down and pay some attention to the road and traffic situation, so hearing several (even different) warnings in short succession may be counter-productive or even annoying (particularly if interspersed with turn prompts). I have had that experience myself.

**Comment by polarbearing** [comment]
Seems we agree that the visual icon should be displayed as long as valid and the voice reduced. 

As you mention the interspersing with turn instructions - another issue is when a hazard is announced before a turn prompt, i.e. it is not visible on the road, and the announcement is confusing because you hear "Ped crossing. Turn right in 20 m" instead of "Turn right in 20 m, then watch the ped crossing".

**Comment by vshcherb** [comment]
I think we have that logic already for POI along the road. Where number of POI could be a big list we announce periodically. https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/helpers/WaypointHelper.java#L297

@sonora Please correct me if I'm wrong.

**Comment by sonora** [comment]
Victor,
I think the mechanism for POI is we mark in the prepared list what should be announced, code ref https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/helpers/WaypointHelper.java#L572

The line you reference is the blank out (mute) period for announcing speed cams. And yes, such a blank out mechanism could be applied to all combined (or a certain aggregated subset of) Alarms.

But we also have https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/helpers/WaypointHelper.java#L265, meaning when a speed alarm is in effect, all other alarms will be blanked out. (This is issue #3335.)

I am unclear what our target behavior should be, and what we should change, if anything? Possibly simply add a blankout period for identical warnings? Or for an aggregate group of warning types (which?)?

**Comment by vshcherb** [comment]
If we are talking about POI, it is one story
We combine them into group here
https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/helpers/WaypointHelper.java#L385
If we talk about alarms, we skip some annoying repetetion here (for 5 seconds except speed cameras)
https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/helpers/WaypointHelper.java#L296

And I don't agree we should filter somehow else cause it is fine to have same alarm in a raw ( there is nothing wrong if you have 3 times traffic calming). Though the period you would hear the alarms should be configured, now it is not more often than 5 seconds.

**Comment by sonora** [comment]
So no action here. From my personal experience and testing I concur.

**Comment by polarbearing** [comment]
My double rail crossing is announced twice within 2 sec. (today's nightly)

**Comment by zyphlar** [comment]
Is there a reason this was closed? In my area there's generally four pedestrian crosswalks at each intersection, and I'm unsure if it waits 5 seconds but if so that's not enough. Duplicate announcements within perhaps 15-30 seconds are enough to drive someone insane especially in a major, well-mapped city. I don't want to disable the alert because the one lone crosswalk or speed hump in the middle of a road is good to be reminded of, but when all you can hear in a downtown area is "pedestrian crosswalk pedestrian crosswalk pedestrian crosswalk pedestrian crosswalk" you quickly want to disable the feature.

**Comment by vshcherb** [comment]
Merged into another issue

**Comment by xeruf** [comment]
@vshcherb which one?

**Comment by vshcherb** [comment]
Hm... not sure, it was 3 years ago and my message almost 1 year ago, but there for sure is  an issue in 4.1 milestone just for duplicate Train Tracks!
