### ISSUE TITLE
Traslation of "and go"

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#3431]
Where can I change the spanish traslation of "and go"?
Sorry but I can not found it.

I Will attach a picture with an example.
![screenshot_2016-11-19-01-12-06](https://cloud.githubusercontent.com/assets/12786225/21967101/deb14b62-db80-11e6-8a1b-621791a4c893.png)

**Comment by njohnston** [comment]
See the `route_roundabout` string in [OsmAnd/res/values-es/strings.xml](https://github.com/osmandapp/Osmand/blob/master/OsmAnd/res/values-es/strings.xml#L725). There's also `route_roundabout_short` which omits the "Roundabout:" or "Rotonda:" prefix.

**Comment by vshcherb** [comment]
All these strings https://github.com/osmandapp/Osmand/blob/master/OsmAnd/res/values/strings.xml#L2153
