### ISSUE TITLE
Map download: The download all button does not show correct state, and the progress bar is faulty

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#3432]
OsmAnd showed the **World Overview** map in orange (outdated). I switched to the **Updates** tab and tapped on the **Update all (199 MB)** button at the bottom of the screen. 

I expected the button to change to "depressed" state. But it remains unchanged. **[BUG#1]**

The status bar of the phone shows an animated downward arrow (denoting that a download is going on). If I tap on it, a notification shows "Downloading world map", but does not show the % completed. The bar showed approximately 20% completed.

But when I switched to OsmAnd, its **Updates** screen did NOT show any ongoing downloads! (no progress bar). So why did the device status+notification show a bogus progress?? **[BUG#2]**

I tried to tap on the **Update all (199 MB)** button once again. This time the app showed a progress bar, which started from 0% and progressed gradually. The device status+notification shows the same % progress this time. I do not know how/when it got re-adjusted.

**Comment by vshcherb** [comment]
Issue # 1  is reproducible but not critical, others are not reproducible.
