### ISSUE TITLE
Change the day color of the new cafe, restaurant etc. icons

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#3438]
I think we should change the color of the new gastronomy icons from the current orange to something more brownish (more like their night color, maybe), becauae the orange is too similar to our "highlighted POI" color which we use to accentuate POIs explicitly selected to be visible e.g. as a result of a search.

**Comment by sonora** [comment]
@xmd5a2 Leonid, demonstration: Check out this screenshot: I highlighted Convenience stores, but they do not stand out too well vs. the (non-highlighted) restaurants ...
<img width="135" alt="screenshot_2017-01-22-08-35-19" src="https://cloud.githubusercontent.com/assets/845735/22180890/5d011298-e07e-11e6-9c43-4618da4cfaae.png">

**Comment by xmd5a2** [comment]
Agree. Fixed
https://github.com/osmandapp/OsmAnd-resources/commit/2b2809c98f73fac70b6bdad9910c8c876ca2686e
