### ISSUE TITLE
Color code for piste:grooming tag

### ISSUE THREAD

**Issue by knusprjg** [osmandapp/Osmand#3439]
Hi,

at the moment all cross country ski routes have the same color (light blue) in ski map view ("winter and ski" map style). It is possible to visualize the grooming tag (classic/skating/classic+skating) by enabling "Piste grooming" in the details of map rendering. But this seems to result only in two small crossed lines for skating tracks and a single crossed line for mixed tracks (doesn't seem to be documented in the map legend!).

As a skater, classic tracks are basicly useless to me. With the current rendering style it is pretty tedious to distinguish the track types as I really have to look at each and every track section on its own to find a eligible way. Coloring the different grooming styles would ease this a lot. This is probably not to big a deal since the tag is already used und there are very view colors in use in the "winter and ski" map style at the moment.

Also the crossed lines could maybe be used for the difficulty tag?

Best regards,
knusprjg

**Comment by xmd5a2** [comment]
Can you provide a screenshot AND coordinates (or better link to osm)? I'm not sure what osm tag do you mean under "cross country ski routes".

**Comment by knusprjg** [comment]
I'm talking about the [piste:grooming](http://wiki.openstreetmap.org/wiki/Key:piste:grooming) tag for tracks. You can find examples around here: http://www.openstreetmap.org/#map=18/50.43651/12.96812

This is how it looks like in OsmAnd on Android in the winter and ski map style with "piste grooming" active in details. The red circled pistes are nordic only while the green one is also prepared for skating. Visually they are right now only to distinguish by those tiny perpendicular lines on the green highlighted track. 

![grooming](https://cloud.githubusercontent.com/assets/23284327/23823115/b181afa0-065b-11e7-99c5-f8113d2cab3c.png)

It's already hard to distinguish them in this screenshot but it's practically impossible on the phone in a real life outdoor situation, in particular when your hands are getting colder with every second you spend looking at it ;) I would therefore propose to find a solution that is easily to distinguish, even when looking from a low zoom level, so one can easily plan the remaining route.

**Comment by xmd5a2** [comment]
Fixed by making ticks wider and bigger https://github.com/osmandapp/OsmAnd-resources/commit/c339844ea1792b5a941e0453fb14906ff6949508
https://www.dropbox.com/s/ckthybwmz65sqc3/Screenshot%20from%202017-03-28%2017-07-16.png?dl=0
