### ISSUE TITLE
TTS interface vs local language

### ISSUE THREAD

**Issue by goblin** [osmandapp/Osmand#3440]
It seems OsmAnd currently synthesises street names in whatever language is set as the voice language. This makes them incomprehensible (or at least funny) - as it tries to pronounce local street names in English, for instance.

It would be nice if it switched the language appropriately to say the street name correctly.

In other words, phrases like "Turn left onto Świętojańska" should sound correctly, with the first three words spoken in English and the 4th word (made up a street name but I'm sure it exists somewhere) in Polish.

**Comment by sonora** [comment]
Sure, that would be nice :)

But 2 big problems here, not sure how to solve either one:
- How do you detect in what language a street name is best pronounced? When e.g in Switzerland, is a streetname you are looking at better pronounced in German, French, or Italian? When in Germany, how to discover that the "Henry Dunant" in an "Henry Dunant Street" should actually be pronounced in French?
-I know of no currently supported way in Android to change the TTS engine on the fly in mid-sentence ...

**Comment by goblin** [comment]
Oh, yeah, haven't thought of that, sounds hard indeed :-/ I guess some heuristics will be necessary.

Regarding Switzerland, I was hoping map features should have a language associated with the name, but they probably don't. In this case we'd need a best-guess based on the most popular language in a given Canton I guess?

Regarding Henry Dunant, well, unless it's possible to set this in a OSM feature somehow, then we'll have to live with bad pronunciation of this, I don't really see a way around it.

Regarding switching TTS engine - perhaps with this Speech Synthesis Markup Language thingy? This is raised in https://github.com/osmandapp/Osmand/issues/2983 . There's an [xml:lang](https://www.w3.org/TR/speech-synthesis/#S3.1.2) attribute that might work for that. If not supported, then you'd have to switch the engine in mid-sentence - the intonation will be off but I guess that's still better than trying to pronounce names in a different language.

**Comment by sonora** [comment]
I may be wrong, but from what I see it takes 4-7 seconds on most devices to initialize tts with a given language. So as long as the engines do not support better re-initialization on the fly, we may be out of luck here.

**Comment by goblin** [comment]
That looks bad indeed. Maybe it would work keeping both engines initialized and only using one when needed...

You're right, prioritisation of this should be low, this is just a "nice to have" thingy (although I do consider it a bug;-)

**Comment by vshcherb** [comment]
We can detect street language, we already do it to set a default TTS language if you define a region.  Cause we know for region languages, but again TTS-engine doesn't allow that today.

One of the feature we are going to implement to automatically detect left hand driving based on location. We have information about languages in the regions.ocbf and we could detect it by location. Of course there will be exception if you cross the country but that will be very rare.

**Comment by goblin** [comment]
I doubt crossing a country border is a rare circumstance, I've used OsmAnd in such a scenario and having to manually toggle all the settings was a nuisance (and didn't work perfectly at the time either, the roundabouts were rendered the wrong way round). Maaany other people cross country borders on a regular basis.
