### ISSUE TITLE
Feature request: create custom profile

### ISSUE THREAD

**Issue by andrasfuchs** [osmandapp/Osmand#3443]
In OsmAnd+ 2.5.4 we have 3 profiles: car, bicycle and pedestrian.

Those are sufficient in most cases, but where I live, there are no sidewalks, so the pedestrian mode is nearly never used, bicycles are a rarity, but on the other hand scooters are used by nearly everyone. I don't think it would make sense to add a separate motorcycle or scooter profile, because they are not typical worldwide, but it would be nice to have an option to create a custom profile (based on an existing one).
The reason why it would be important, is that all the route calculations' time estimation is now off by at least a 50% margin, since the traveling speed of the scooter is limited. On the other hand there are some routes which can be accessed by scooters, but not by cars, and also there are many parking lots where only scooters and motorbikes are allowed. 
These properties are now ignored, which results in sub-optimal route calculations.

I would say, that it is more like a nice to have feature, I just wanted to share my local experience.

**Comment by sonora** [comment]
It is probably not entirely what you need, but if you enable our development plugin, you will find a menu item "Application profiles" in its setting with several more choices. Maybe one fits better for your use case than our 3 default profiles.

**Comment by andrasfuchs** [comment]
Thanks, that would be exactly what I need. 

I have just added the profile, and tested some routes, but it looks like (as you mentioned) that it is not fine-tuned yet. 
It estimates exactly same time for both the motorcycle and the car profile, which is not too realistic here. (Normally the scooter is slower, but during the rush hours and traffic jams the scooter is significantly faster.)

I usually upload my tracks to OsmAnd. Does it help you guys if I set the profile, is that information included in the tracks, so can you theoretically use my speed information to help the route calculation?

Is there a way to define that I use a scooter and a bigger motorbike?

**Comment by vshcherb** [comment]
This is a feature request, but to be honest I think it is supported already (but didn't try yet). It means we don't have specific profiles for motorbike but they could be developed in routing.xml without rebuilding/republishing application

**Comment by andrasfuchs** [comment]
I'd like to play with those settings, but I can't find the `routing.xml` anywhere on my phone. 
I have OsmAnd+ 2.5.4 installed on Android 6.0.1.

In which folder should it be?

**Comment by polarbearing** [comment]
If I remember correctly, it is not in there by default. Grab it from github and put it in the same OsmAnd base folder where your maps are.

**Comment by andrasfuchs** [comment]
Okay, so I got the 'routing.xml' from here:
https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml

I copied it to my phone next to my map files (/storage/emulated/0/osmand), but then OsmAnd crashed. After I removed the file, it worked again.

I've sent the exception.log to crash@osmand.net.

The exception:
> java.lang.NullPointerException: Select tag filter outside road attribute < select > : 716

The XML part it refers to:
> < point attribute="obstacle_srtm_alt_speed">
> 	< select value="0.1" t="osmand_ele_incline_max" v="21"/>
> 	< select value="0.5" t="osmand_ele_incline_max" v="1"/>
> 	< select value="1"/>
> < /point>

**Comment by cascafico** [comment]
> Okay, so I got the 'routing.xml' from here:
> https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml
> 
> I copied it to my phone next to my map files (/storage/emulated/0/osmand), but then when I opened Menu / Settings / Navigational settings, OsmAnd crashed. It should have displayed the "Profile Specific Settings" dialog, listing my profiles.

I've just sent a crash report about the very same issue:
Huawei mYA-l11, oSMANS 2.9.3 293

**Comment by Beddhist** [comment]
I think this is more important than "nice to have". I live in Thailand and there are many places where cars can't go (narrow bridges and paths) and vice versa. Looking at my screen now I can see that I already have a motorcycle option. Should this be closed now?

**Comment by andrasfuchs** [comment]
@Beddhist when I created this issue in 2017 I lived in Thailand too :) I tried the motorcycle profile, but it didn't really worked the way I expect it to work.
A separate profile for scooters would be nice (even if it's just a subprofile under the motorcycles), but as both @cascafico and I tried to create one manually we both run into a bug and crashed OsmAnd, so I think we should keep this issue open.

**Comment by Beddhist** [comment]
The feature request was for a mbike profile and we now have one and without having to import a file. To me that says this request is fulfilled.

The fact that routing.xml crashes Osmand needs a new bug opened.

I just tried routing over a bike bridge and it failed majorly for both cars and bikes. I'll open a bug, if there isn't one already. However, routing is also broken using any of the other routing engines...

**Comment by MadWasp79** [comment]
Check the nightly builds.
