### ISSUE TITLE
Location "Accuracy"

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#3445]
> This is not an issue immediately actionable in our code, but more a documentation of research on (primarily GPS) "Location accuracy", and how we should treat it in OsmAnd. I will continue to edit this post to some degree. If you have anything to contribute, please do.
> 
> 

Position **Accuracy** and **Precision** are significant topics in a mapping app. Accuracy is the degree of scatter of a measurement, while precision describes how well the measurement average hits the "true" result. With position detection, precision estimates are desirable, but often impossible to get (when "true" position is completely unknown). Accuracy estimates can be obtained easier, but can be deceiving: Even when the estimated accuracy is high, the "true" position may still be considerably offset (lack of precision!).

GPS units report **DOP (Dilution of Precision)**, a unitless "sensitivity factor", i.e. the lever between the variance of "measurement data" vs. the variance of "concluded position". For GPS it considers satellite geometry only, no environmental factors or receiver characteristics.

**Position Error**: Ionospheric, multipath, and other environmental factors aside,
`Estimated Position Error = User Equivalent Range Error * HDOP`.
In the absence of deliberate biases (like the former 32m SA) UERE should be a device chipset property (the "receiver resolution"). It is unclear to me at this point if some or all devices report this or a derived/related parameter somehow in their NMEA strings, so Android can use it. And if yes, if they report a constant, or factor in more circumstantial background. For smartphones, literature often simply quotes UERE as a constant 5m (3m at best), i.e. (in 2D)  `EPE = 5m * HDOP`.

**Android's `getAccurcacy()`** claims to report some sort of horizontal "accuracy" in meters (accuracy, not precision!). The documentation implies `getAccuracy()` returns a 1-sigma (68%) Gaussian confidence interval (but unclear over what data, perhaps sliding time-averaged position readings?). It is unclear to me at this point what raw data Android uses or which statistics it performs. From testing, `getAccuracy()` does in deed differ from (and is greater than) `hdop`, and is also not just `hdop` multiplied by a constant.

**Code implications:**
- [x] **(1)** Our **accuracy circle** on the map screen is fine. We show a disk of radius `getAccuracy()`. Limitations: This is accuracy and not precision. And we do not know exactly what Android factors in on different devices to determine it.
- [x]  **(2)** Our **"Precision filter" in trip recording** is in fact an "Accuracy filter" (see above), and its unit is "meters/feet". EDIT: Done, wording adjusted and unit added: https://github.com/osmandapp/Osmand/commit/9176e5a37c824c547dd31c10d23a13daadd4f129
- [ ] **(3)** **Trip recording**: In our **GPX track** we report Android's `getAccuracy()` values in the GPX `<hdop>` tag, which by [TopoGrafix](http://www.topografix.com/gpx.asp) specs is wrong (`<hdop>` is reserved for the HDOP value of the position fix). Not sure yet if we should make a change here, I guess accuracy could/should really be included in a GPX file under `<extensions>`?

**Comment by sonora** [comment]
Reserved.

**Comment by naoliv** [comment]
For **(1)** see https://github.com/osmandapp/Osmand/issues/3416#issuecomment-282573067

**Comment by polarbearing** [comment]
> We show a disk of radius getAccuracy()

You might consider to show a circle with blurred (fading out) borders, to avoid the illusion that there would be a fixed boundary measurable in meters.

**Comment by sonora** [comment]
Let me close this one here, it was meant to docunent the "research" . :) We can follow up any UI bugs or improvement suggestions in the other issue.

**Comment by 17320** [comment]
@sonora 

> The documentation implies getAccuracy() returns a 1-sigma (68%) Gaussian confidence interval

I have compared the values being reported by OsmAnd and those obtained from Firefox's [geolocation API](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API), which [claims that](https://developer.mozilla.org/en-US/docs/Web/API/Coordinates/accuracy):

> The Coordinates.accuracy read-only property is a strictly positive double representing the accuracy, with a 95% confidence level

The two values are the same (implying that both are using the same underlying Android API?). Empirically, the output seems more consistent with a 95% confidence level.

**Comment by sonora** [comment]
Yes, same API I would think.

**Comment by endolith** [comment]
Number 3 is not fixed, correct?  (So why is this closed?)

**Comment by sonora** [comment]
True that we never acted upon (3). And while some other apps like Locus Maps also seem to simply save the results of Androud's `getAccuracy()` method to the gpx `hdop` field, I believe that is actually technically wrong.

At the same time I am not sure about the practical benefit of using a custom extension. Have not researched if there is a convention to what gpx field it would make more sense to write Andtoid's `getAccuracy() `values to. Perhaps someone can help out with that research here.

**Comment by endolith** [comment]
Well I was tripped up by the non-standard tags, thinking they were actually HDOP instead of meters.  I at least documented it in https://github.com/osmandapp/web/pull/428

**Comment by endolith** [comment]
> Have not researched if there is a convention to what gpx field it would make more sense to write Andtoid's `getAccuracy() `values to. Perhaps someone can help out with that research here.

https://www.geo-location-platform.com/map_matching.html mentions GPX files with horizontal accuracy:

```xml
			<trkpt lat="43.21843" lon="27.980333">
				<time>2019-11-20T12:00:00Z</time>
				<course>356</course>
				<speed>12</speed>
				<e:horaccur>10</e:horaccur>
			</trkpt>
```

> "e:horaccur" - horizontal accuracy of every GNSS position in meters. E.g. value of 3m means that position is within 9m radius with 99.73% probability. This value is not to be confused with HDOP. If horizontal accuracy is not available from GNSS device, please set this value to 0 for every position to disable horizontal accuracy in the map matching algorithm. 

Locus does the same as OsmAnd:

https://help.locusmap.eu/topic/23131-hdop-and-accuracy

> hdop field in the GPX file should match the "accuracy" value returned by the Android system itself. Its description is wrote here: https://developer.android.com/reference/android/location/Location.html#getAccuracy() . 

OpenTracks uses custom tags:

https://github.com/OpenTracksApp/OpenTracks/issues/1438

https://exiftool.org/forum/index.php?topic=15972.0

```xml
<trkpt lat="52.52437" lon="13.41053">
<ele>111.1</ele>
<time>2022-06-24T11:11:11.001+02:00</time>
<extensions><gpstpx:TrackPointExtension>
<gpstpx:speed>1.11</gpstpx:speed>
<opentracks:gain>0</opentracks:gain>
<opentracks:loss>0</opentracks:loss>
<opentracks:accuracy_horizontal>4</opentracks:accuracy_horizontal></gpstpx:TrackPointExtension></extensions>
</trkpt>
```

**Comment by sonora** [comment]
Yes, thanks for the research! That pretty much confirms my gut feeling that there is no good universal convention, and a certain degree of confision in various different implementations. With the only 'clean' solution probably being to define some custom extension.

We will need to leave it to Product Management in OsmAnd, @vshcherb , if to change anything. I personally feel there may not much to be gained, and perhaps no big damage to, stick with the current practice of writing the accuracy to the hdop field for now, even though technically incorrect.

**Comment by vshcherb** [comment]
If we documented, than I think to leave as it is. If somebody has valuable data stored and needs to be in a different formatn then it's always possible to convert. I think staying homogenous among thousands already recorded tracks would be more important

**Comment by jo-chemla** [comment]
Hi there, stumbled upon this closed issue thread looking to understand whether OsmAnd registers Android `FusedLocationProviderClient` accuracy or only the GPS HDOP. Very informative research on what each app uses as convention in above comment, thanks for that!



~~Also looks like the changes from referenced PR https://github.com/osmandapp/web/pull/428/changes have been reverted~~

<details><summary>Overlook from my side</summary>
<p>

Change from PR
> HDOP is one of the terms of GPS accuracy, abbrev. from Horizontal Dilution of Precision, determined as the error caused by the relative position of the GPS satellites. True HDOP is a dimensionless number, but https://github.com/osmandapp/Osmand/issues/3445. Beware that this is non-standard.

Currently in main
> HDOP is one of the terms of GPS accuracy, horizontal accuracy, calculated in meters, abbrev. from Horizontal Dilution of Precision, determined as the error caused by the relative position of the GPS satellites.

</p>
</details> 

Current doc definition of HDOP: 

> Horizontal Dilution of Precision (HDOP) is a measure of GPS accuracy, reflecting the potential error in location due to the positions of the satellites. Unlike the standard HDOP, OsmAnd GPX tracks use this value to represent horizontal accuracy in meters. Please note that this implementation differs from typical HDOP standards. [Learn more](https://github.com/osmandapp/Osmand/issues/3445).

Since OsmAnd calls the standard Android location API, would it be useful to record both gps hdop and android location's `.getAccuracy()` field (horizontal accuracy in meter)?  Thanks a lot! Feel free to re-openor open a dedicated thread instead - sorry for reviving that closed one!

**Comment by sonora** [comment]
Re
>Also looks like the changes from referenced PR https://github.com/osmandapp/web/pull/428/changes have been reverted

The current documentation is this https://osmand.net/docs/user/plugins/trip-recording#recorded-gpx-file , should be ok.

**Comment by jo-chemla** [comment]
Thanks for the hint, indeed current main branch is synced with doc with the right description - I wrongly looked at that file on main of the forked repo which contributed that doc change, sorry about that. Just updated my earlier comment to reflect that. 

Anyway, being able to track per point the fused android location accuracy and GPS hdop at the same time could be helpful - or eventually a precision on that doc that what's recorded as hdop "to represent horizontal accuracy in meters is Android FusedLocationApi accuracy". 

By the way, I just discovered this comment from 2022-10 https://github.com/traccar/traccar-client-android/issues/315#issuecomment-1281388830 in Traccar regarding bad/different readings between `FusedLocationAPI vs LocationManager` not sure if this is still helpful.
