### ISSUE TITLE
Improve visibility of bicycle routes

### ISSUE THREAD

**Issue by exaexa** [osmandapp/Osmand#3446]
Hello,

I created a patch to `default.render.xml` that lets users choose to render "highlighted" cycling routes (using a selector in the menu). Result looks a bit more like the one from OpenCycleMap, and fixes an issue where the default OSMAnd bike route highlight sometimes has the exact width of the road below, thus looks just like a re-colored road (e.g. making a small rural road look like a high-traffic one).

Picture that explain it better together with the code is in the pull request in resources repo, here:

https://github.com/osmandapp/OsmAnd-resources/pull/423

Would it be possible to merge this? Cycling "experience" with OSMAnd gets a LOT less clumsy (you don't have to zoom around to see whether the road is really a cycle route).

I'm not sure whether the same highlighting shouldn't apply to the mountain bike routes too. I assumed that since these are mostly off-road (I didn't manage to find a counter-example), the visibility problem won't appear in most cases, and let them unchanged.

Thanks!
-mk

**Comment by vshcherb** [comment]
That issue doesn't need to be open separately from pull request.
