### ISSUE TITLE
Non-Java plugins

### ISSUE THREAD

**Issue by KOLANICH** [osmandapp/Osmand#3447]
It'd be nice to have plugins exposing plugins' API to non-Java code, s.a. JavaScript, Lua, python and .Net. They are open source and there are apps they are used in through NDK. I have lot of ideas for plugins, but I don't want to use Java (Java IDEs are usually written in Java,, it's kind of terrible). I need the functionality to create own layer, to add there own shapes and POIs, to incorporate my shapes into osmand somehow to make them react on user input and settings, some primitive API to access network, s.a. send an http request and get the results, some API to store info, some API to play sounds and synth speech. For JavaScript I guess it will be very good if the API is compatible with WebAPI (the API used in web browsers).

**Comment by vshcherb** [comment]
I don't expect it to be done in a near future.
