### ISSUE TITLE
Averaging over time

### ISSUE THREAD

**Issue by KOLANICH** [osmandapp/Osmand#3451]
When a user wants to add a poi he may be ready to stay and not to move for some seconds. So I wonder if averaging position measurement can improve accuracy if a user guarantees that he is staying at the same place for the time of averaging. Can it be helpful in the case of GNSS? (I found that the errors are not very random, I guess it is because of reflections. I've seen position errors more than 500 meters today though the reported accuracy was tens of meters. Can this be solved by choosing approximate position to make the software a hint which solution should it stick to?)

**Comment by sonora** [comment]
I have done a lot of experimenting with this over the years, and all GPS chipsets I have investigated seem to do this automatically. While algorithm or procedure may not be well documented, geometric accuracy (its what you call "Reported accuracy" above) quickly improves after GPS is turned on, usually after a few seconds.

Please note that this is "geometric accuracy", I have an issue somewhere explaining the difference (Look for "Location Accuracy"). What you are looking for is "precision", and there is no easy telling ...

In any case, if  you are 500m off using a satellite fix, something is terribly wrong! You either have a lot of reflection, or shading, or an issue with your GPS receiver (if it behaves like that a lot). Or you fallback to WiF position fix (turn that off in Android Location settings, use "GPS only"!). If this is in mapped territory, I think your best bet is to manually select where you think you are on the map, relative to other mapped features (buildings, street corners, etc.). Then long-tap exactly the point you want, and add it as a POI.

If in adverse conditions you do not use this circumstantial evidence to "aid" your position fix, I am afraid determining the precision of your position fix is like finding out if your lottery ticket is a winner before they actually draw the numbers: Just no telling. Not sure that's a good analogy, but the best analogy I can find to this mathematical problem ...

**Comment by KOLANICH** [comment]
>Remediation: If this is in mapped territory, I think your best bet is to visually check where you think you are on the map, relative to other mapped features (buildings, street corners, etc.). Then manually long-tap exactly the point on the map you want, and via its context menu add that as a POI.

I always do this, but the issue here is the maps: they are traced from satellite images but the ones who have traced them didn't take in account that they are perspective-transformed and traced them using visible positions of rooftops as contours. Often some contours are traced from different sat maps (s.a. google maps) which have different coords for the same objects. So relying on maps often introduce additional error.

>If in adverse conditions you do not use this circumstantial evidence to "aid" your position fix, I am afraid determining the precision of your position fix is like finding out if your lottery ticket is a winner before they actually draw the numbers

I meant that there may be some approximate solutions for equation system taking in account errors of measuring pseudodistances and in general case the algorithm doesn't know which one it should choose, so I guess it averages them and their std deviation is included into an error somehow. I wonder if I can give a hint to the algorithm in a form my approximate position to improve accuracy.

**Comment by vshcherb** [comment]
Sounds quite hard to implement.
