### ISSUE TITLE
Include camp_type key

### ISSUE THREAD

**Issue by sim6** [osmandapp/Osmand#3452]
Please, could you include https://wiki.openstreetmap.org/wiki/Key:camp_type and use different icons?

**Comment by vshcherb** [comment]
I think we should have that tag to appear in the context menu but displaying it on the map would be quite difficult and not necessary needed. On the other hand we should support search for that info..

**Comment by xmd5a2** [comment]
camp_site=* tag is used much more often https://wiki.openstreetmap.org/wiki/Key:camp_site
Also this tag status is approved in wiki.
It is not clear what to do with these very similar tags - camp_site and camp_type.

**Comment by sim6** [comment]
I think tags camp_type and camp_site are different. camp_site (according to wiki) are about services and camp_type are about nature. On the other hand the most used camp_site values are not the specified by the wiki https://taginfo.openstreetmap.org/keys/camp_site#values

Please, could you reevaluate the inclusion of camp_type tags?

**Comment by sonora** [comment]
I do also see a value in having this ... but please see [https://wiki.openstreetmap.org/wiki/Proposed_features/camp_type%3D*](https://wiki.openstreetmap.org/wiki/Proposed_features/camp_type%3D*). The status of the proposal was finally set to "undefined" after long discussion. I wish someone in OSM could come up with a more refined and more generally accepted solution for this partially important functionality...
