### ISSUE TITLE
OSMAnd core iOS build issue

### ISSUE THREAD

**Issue by HimanshuDudhat** [osmandapp/Osmand#3453]
Getting issue during build OSMAnd core library by following step provided by @vshcherb under issue #2848 . 

Can you please let to sort out building issue?

[Here](http://pastebin.com/HXGSJ7VP) is log from terminal while executing **./prebuils-core.sh**

**Comment by cbenz** [comment]
Me, really? ^^

**Comment by jcatamaph** [comment]
I have the same issue.
