### ISSUE TITLE
Searching by addr:streetnumber broken in latest osmand

### ISSUE THREAD

**Issue by jirislaby** [osmandapp/Osmand#3454]
Search for `Prostějov, Zlechovská 4` in the `Czech Republic` data is not working anymore. (Using the new search.)

4 is `addr:streetnumber` and it used to work with older osmand versions. But nowadays, I have to use `addr:conscriptionnumber` (202) to actually find the address. But note that we do not use `addr:conscriptionnumber` in real-life addressing when streets exist in the city (when `addr:street` and `addr:streetnumber` exist on a node).

So we use:
- `Prostějov, Zlechovská 4` (`addr:street` and `addr:streetnumber`)
- `Hrubčice 181` (`addr:place` and `addr:conscriptionnumber`) when no streets are in cities.

BTW (maybe a separate issue, I have just found out that searching for the latter does not work either. 

Osmand used to show 202/4, today it only shows 202 in the search results.

**Comment by aceman444** [comment]
I'm not sure OsmAnd ever supported conscriptionnumber and streetnumber. Can you check what the addr:housenumber is on that building? I think OsmAnd (and all other apps) only support this key.

**Comment by jirislaby** [comment]
Sure, it is there. So osmand somehow filters what is behind `/`?
```
addr:conscriptionnumber=202
addr:country=CZ
addr:housenumber=202/4
addr:place=Krasice
addr:postcode=79604
addr:street=Zlechovská
addr:streetnumber=4
building:flats=1
building:levels=1
building:ruian:type=7
building=house
ref:ruian:addr=24793370
ref:ruian:building=24351407
source=cuzk:ruian
```

**Comment by aceman444** [comment]
I can't confirm this. I tried another address that has housenumber of the format XXXX/YY and searching for "city, street YY" worked fine (YY was NOT part of XXXX).

Anyway, for address searches the old search was much better so you can try enable it back by enabling the Development plugin in OsmAnd, and check "enable legacy search" option. This search was much requested by users and it should be brought back in new OsmAnd versions.

**Comment by jirislaby** [comment]
It does not differ with legacy search. I see only the XXXX part of the number in results. No /YY there. I have osmand 2.5.4.

**Comment by jirislaby** [comment]
I switched to non-beta version and it works there as expected.

**Comment by jirislaby** [comment]
And you know what? This was caused by the old version of OsmAndMapCreator 1.1. 1.8 fixed the issue. Note that the old file is significantly smaller:
```
-rw-r--r-- 1 xslaby xslaby 737M Feb  4 14:52 Czech_republic-2017-02-04_2.obf
-rw-r--r-- 1 xslaby xslaby 894M Feb  5 09:13 Czech_republic-2017-02-04_3.obf
```


wdiff of `inspector.sh -vaddress` output:
```
Binary index [-Czech_republic-2017-02-04_2.obf-] {+Czech_republic-2017-02-04_3.obf+} version = 2 edition = Sat Feb 04 [-14:31:53-] {+01:18:30+} CET 2017
1 Map data Czech_republic-2017-02-04 - [-567049002-] {+655225023+} bytes
        1.1 Map level minZoom = 15, maxZoom = 22, size = [-388682172-] {+424132356+} bytes 
                Bounds (left top - right bottom) : 11.375, [-53.9218-] {+55.0213+} NE - [-19.1199,-] {+24.2695,+} 48.1789 NE
        1.2 Map level minZoom = 13, maxZoom = 14, size = [-95400976-] {+119247350+} bytes 
                Bounds (left top - right bottom) : 11.375, [-53.9218-] {+55.0213+} NE - [-19.1199,-] {+24.2695,+} 48.1789 NE
        1.3 Map level minZoom = 12, maxZoom = 12, size = [-56018740-] {+72175839+} bytes 
                Bounds (left top - right bottom) : 11.375, [-53.9218-] {+55.0213+} NE - [-19.1199,-] {+24.2695,+} 48.179 NE
        1.4 Map level minZoom = 11, maxZoom = 11, size = [-12865176 bytes -]
[-              Bounds (left top - right bottom) : 11.375, 53.9218 NE - 19.1199, 48.179 NE-]
[-      1.5 Map level minZoom = 10, maxZoom = 10, size = 7985924-] {+39630736+} bytes 
                Bounds (left top - right bottom) : 11.375, [-53.9218-] {+51.0917+} NE - 19.1199, 48.179 NE
        [-1.6 Map level minZoom = 9, maxZoom = 9, size = 3188627 bytes -]
[-              Bounds (left top - right bottom) : 11.375, 53.9218 NE - 19.1199, 48.179 NE-]
[-      1.7 Map level minZoom = 8, maxZoom = 8, size = 2122216 bytes -]
[-              Bounds (left top - right bottom) : 11.3792, 53.9218 NE - 19.1131, 48.179 NE-]
[-      1.8 Map level minZoom = 7, maxZoom = 7, size = 773115 bytes -]
[-              Bounds (left top - right bottom) : 11.3792, 53.9218 NE - 19.1131, 48.179 NE-]
2 Routing data Czech_republic-2017-02-04 - [-53167845-] {+58115580+} bytes
        Bounds (left top - right bottom) : 12.0695, [-51.0886-] {+51.0768+} NE - 18.8831, [-48.3225-] {+48.5371+} NE
3 Address data Czech_republic-2017-02-04 - [-90364523-] {+152767195+} bytes
        3.1 Address part [-size=27766765-] {+size=28043681+} bytes
        3.3 Address part [-size=25554414-] {+size=53139168+} bytes
        3.2 Address part [-size=34154393-] {+size=66253417+} bytes
        Cities/Towns section, [-447-] {+449+} group(s)
        Postcodes section, [-1841-] {+3122+} group(s)
        Villages section, [-16294-] {+16351+} group(s)
4 Poi data Czech_republic-2017-02-04 - [-60900678-] {+68613280+} bytes
5 Transport data Czech_republic-2017-02-04 - [-580756-] {+2668234+} bytes
        Bounds (left top - right bottom) : [-12.2259,-] {+12.2258,+} 51.0601 NE - 18.63, 48.5793 NE
```

There are zoom levels 7,8,9,10, but also 50M more address data.

So sorry for your time, I didn't realize I have my own generated maps for Slovakia and Czech rep. Note that using the osmand's ones is OK too.

**Comment by aceman444** [comment]
Great, thanks for pursuing it and finding the problem.
