### ISSUE TITLE
OSM editing plugin: failure to upload newly created POI

### ISSUE THREAD

**Issue by christophgysin** [osmandapp/Osmand#3460]
Steps to reproduce:
1. Create a new POI 
2. Move POI
3. Upload POI

Expected result:
A new POI gets created.

Actual result:
Upload fails with the message: "Loading POI... -2 failed: Not Found"

Additional information:
After step 1, the POI shows up under "OSM edits" as "Action create". After step 2, it shows as "Action modify". When uploading, it tries to modify a POI with an invalid (negative) ID.

**Comment by xmd5a2** [comment]
Confirmed
