### ISSUE TITLE
OSM editing plugin: show new POI after upload

### ISSUE THREAD

**Issue by christophgysin** [osmandapp/Osmand#3461]
When uploading a new POI, it dissapears from the map. It will only show up again after downloading a new updated map that includes the change.

It would be great to continue to show uploaded POIs until the map is updated.

I often add new POIs while travelling. With the current behaviour, I have to add favorites for every POI I upload if I want to be able to still see it on the map. This is cumbersome, and clutters my map :(

**Comment by vshcherb** [comment]
The only option today is to use OSM Live.

**Comment by christophgysin** [comment]
Could we then have an automatic trigger to update the map with OSM live after POI upload? I have a OSM live subscription, but it needs to be manually triggered to get the POIs to show up.

**Comment by azrdev** [comment]
Another option would be to keep the local changes in osmand, but add to them a changeset id and/or date when they are uploaded. And whenever the maps are updated, all local changes with such tagging are checked if they are included (if the *.obf files contain that information) or at least are older than the available map of that area.
