### ISSUE TITLE
Opening lat, lon URLs from maps.google.com is slow

### ISSUE THREAD

**Issue by hyperknot** [osmandapp/Osmand#3463]
What version of OsmAnd are you using, on what device and Android/iOS version?
OsmAnd 2.5.4, Moto G, 4.4.4

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps? 
Offline

I'm opening OsmAnd via a maps.google.com web link. The link has specific lat, lon coordinates.

What should happen:
OsmAnd should immediately go to the coordinate.

What is happening:
OsmAnd starts searching, and after about 15 seconds it finds the coordinate.

This search is not needed, as the coordinate is already specified.

I tried both common Google Maps URL formats:
`https://maps.google.com/maps?daddr=lat,lon&saddr=My+Location`
and
`https://maps.google.com/maps?q=lat,lon`

**Comment by vshcherb** [comment]
Fixed in the new version
