### ISSUE TITLE
Car-Mode without Map in V 2.6.0#20230M 2017-01-29

### ISSUE THREAD

**Issue by cepesko** [osmandapp/Osmand#3465]
New version from two days ago doesn't display the map in car mode, only globe, bike and foot.

**Comment by sonora** [comment]
Cannot reproduce, at least not with today's build. Have you double-checked your settings for the car profile, most notably "Configure map/Map source", and "Configure map/Map style" ?

**Comment by cepesko** [comment]
@sonora: map sources are all the same with car, bike and foot profile, with only car profile in day/night_mode. Map stays black, only routing apperars with car profile.  I'll install the next build at w/e and check again.

**Comment by cepesko** [comment]
With V 2.6.0#20263M 2017-02-03 it's still the same: map becomes black when you zoom closer than 500m (by the way how do I see the zoom-level?) but only in car mode. (Samsung S6 Android 5.01)
cepesko

**Comment by sonora** [comment]
So your map source is "Vector maps",  and you use maps downloaded from our server?

The zoom level becomes visible jusr above the menu button during zooming while OsmAnd's Development plugin is actviated.

**Comment by cepesko** [comment]
strangely, somehow with new map Germany/Bavaria from Feb. 1, problem didappeared. (Still don't believe it had to do with setting,  as map only disappeared completely from certain zoom level on) Maybe it had to do with data transfer to SD card and memory handling.
