### ISSUE TITLE
In App-Routing-Error 

### ISSUE THREAD

**Issue by cepesko** [osmandapp/Osmand#3466]
![screenshot_2017-01-31-21-51-43](https://cloud.githubusercontent.com/assets/13084482/22484640/b5ecc6aa-e802-11e6-9f5c-fdcfc7ef80f1.png)

[https://www.openstreetmap.org/#map=19/49.98531/9.15116](url)

Routing should turn slight right into double lane shortpass. OSM Data seems to be ok, as other routers do it correctly.
Best regards and thanks to developpers!
Cepesko

Edit: Germany/Bavaria/standard_map 2017-01-01

**Comment by polarbearing** [comment]
I checked the OSM data including their history. While there were 2 edits in Jan 2017, however they did not affect routing. So the loop is explicable with a turn restriction, it remains unclear why the link road is not used in the first place. The number of traffic lights is equal.

**Comment by utack** [comment]
@polarbearing now turn restrictions are in places it seems

**Comment by polarbearing** [comment]
Those turn restrictions are wrong data, as turning is allowed on these junctions. No signposting restricting it. 

The bad thing is that the restrictions were added an hour before midnight on Jan 31, that means they will be in the February OsmAnd extracts. Thus they will mask the routing error and make debugging it more difficult :-(

**Comment by utack** [comment]
yes mapillary makes it seem like you are allowed to do u turns here, they do not seem correct

**Comment by polarbearing** [comment]
I had commented the changeset already, https://www.openstreetmap.org/changeset/45698433 . Maybe the user intended to help with this error here, but it was counter-productive. Still I'd like to wait a day for a response before reverting.

**Comment by polarbearing** [comment]
The user has removed the misleading restrictions, however the bug should therefore been tested against the original 2017-Jan-01 map or a February map with OsmAnd Live applied.

**Comment by stephan75** [comment]
... maybe the online service http://extract.bbbike.org can provide daily (?) refreshed map extracts also in Osmand format ... for testing purposes on that street crossing.

**Comment by aceman444** [comment]
What is the assumed speed set in your routing.xml file for the primary and primary_link class of roads? Maybe it is faster in OsmAnd calculations to take the primary roads and make the loop.

Also, if you don't want to add a simple no_turn_left e.g. at node 2088253270 (as you say there is no such restriction), you could make a no_u_turn restriction with "from way 198732136, via way 470799544, to way 198732021" members so only disallow loops.

**Comment by cepesko** [comment]
![screenshot_2017-02-04-13-48-11](https://cloud.githubusercontent.com/assets/13084482/22618599/d42a4d46-eae0-11e6-82ba-eeb3f8932039.png)
Error gone with map Feb 1st
