### ISSUE TITLE
Generated map for speed_camera not working

### ISSUE THREAD

**Issue by anonimou0** [osmandapp/Osmand#3467]
Hello there. First of all, this app is awesome and thanks for the great job you guys do!

I'm running Osmand 2.5.4, but I got this problem from older (but recent) versions.

My problem is with speed_camera announcements (maybe related: https://github.com/osmandapp/Osmand/issues/3423 and https://github.com/osmandapp/Osmand/issues/3069 ). 
However, instead of picking some data from openstreetmap, I'm creating my own map.

Brazil got this website, maparadar.com, which got tons of speed camera, traffic lights, etc. I got the data from it, on *.csv, and tried to import it in Osmand. I remember pretty well that I was able to do it easly on older versions (but don't know which one).

Here is the process I'm doing: 
1) get the *.csv file
2) convert it to *.osm file, in a xml-like format
3) use OsmAndMapCreator 1.8 to create the *.obf file

After MANY failures, changing tons of things on the *.osm file, I tried other things, like trying the *.kml file (from the maparadar website). No success. I've tried using csv2osm (https://github.com/OSMBrasil/csv2osm), osmosis (https://github.com/openstreetmap/osmosis) to convert the files. Still no luck. I can't stress enough that I tried a lot before posting such a maybe-dumb-issue. I've even download the whole *.osm map from Brazil (10+GB) to try to figure out what I could be doing wrong and see if speed_cameras where different there from what I was doing. It seemed OK. I've tried to merge the data from maparadar with the Brazil-osm data. No luck. I've tried using enforcement and just node. _necadecapibiriba_ (brazilian for no-nothing).

I've enabled everything I could on the OSM: Navigation preferences > alerts and announce [radar], details, POIs, transportation, routes, nodes details.

So, I came in here, asking for help, to make this generated map to work on Osmand.

Attached, below, are some of the many tries of generating the maps.

[examples.zip](https://github.com/osmandapp/Osmand/files/743500/examples.zip)

Thanks!

EDIT: the speed_camera from the map downloaded from the app seems to be working OK. However, there are many other points on this maparadar. Some may be accurate some not. So, I think that it is not good uploading all of them to openstreetmap, but I could live with some differences on my generated map.

**Comment by xmd5a2** [comment]
Try to use latest OsmAndMapCreator from here http://download.osmand.net/latest-night-build/

**Comment by anonimou0** [comment]
Using the latest OsmAndMapCreator didn't work out.
OsmAnd shows the speed_cameras from the Brazil_southamerica.obf (downloaded from OsmAnd) but didn't show the ones from the generated file.

[generated.zip](https://github.com/osmandapp/Osmand/files/750154/generated.zip)

tried to use the latest nightly of OsmAnd as well, but got this message: "a versão do índice "MAPHERE.obf" não é suportada " for all the maps that I have installed. Translated is something like: 'The index version of "MAPHERE.obf" is not supported.

**Comment by hakuchi** [comment]
Importing external speed cameras into OsmAnd is not supported.
#1196

**Comment by sonora** [comment]
Let's merge this to #1196.

**Comment by anonimou0** [comment]
@hakuchi , how does OsmAnd know that the map is "external" generated or from downloaded map?

**Comment by hakuchi** [comment]
If you use the OsmAndMapCreator with a *.osm from [osm.org](https://www.openstreetmap.org/export) or [geofabrik.de](http://download.geofabrik.de/) OsmAnd detect these external maps as normal maps.

If you convert speed cameras, OsmAnd can display them, but is not able to give any voice prompts.
The method what you use, works good for POI like parking, fuel, tourism etc.
For speed cameras your method is not working.

PS: remember that it is not allowed to import data from speed cam databases(*.csv, *.ov2, *.kml etc) into openstreetmap.org

**Comment by anonimou0** [comment]
> PS: remember that it is not allowed to import data from speed cam databases(*.csv, *.ov2, *.kml etc) into openstreetmap.org

I was not planning to do so, because there are few non-existing speed cameras on that database. When contributing to OSM, I do manually on stuff I know to be right =)

@hakuchi , how does OsmAnd differentiate a "external maps" from "normal maps" . I downloaded the [geofabrik.de Brazil's map](http://download.geofabrik.de/south-america/brazil-latest.osm.bz2) and merged, at the end, the nodes that I had from [Mapa Radar](maparadar.com). 

After that, I used OsmAndMapCreator to generate the now-merged-full-map of Brazil. Surprisingly, the nodes of speed_camera from the original geofabrik where there. However the ones I inserted no.

**Comment by hakuchi** [comment]
It make no sense adding nodes from speed cam to the end of the map.
OsmAnd is not able to give voice prompts for speed cameras imported in this way.

OsmAnd detect only [speed cameras](http://wiki.openstreetmap.org/wiki/Tag:highway%3Dspeed_camera) they are connected with the node of a highway or if they have a [enforcement relation](http://wiki.openstreetmap.org/wiki/Relation:enforcement).

If you add the nodes from the speed cam database in this way there is no connection to the highway that OsmAnd need to detect them correct
