### ISSUE TITLE
Can't change OSM Live Support region: "Error: Error"

### ISSUE THREAD

**Issue by fho** [osmandapp/Osmand#3469]
My OSM Live Subscription settings are the following:
[x] Dontation to OpenStreetMap Community
Support region: South Korea
mail: < my-email-address >
username: < my-openstreetmap.org-username >

When I change the Support to something else e.g. Albania, a dialog comes up for a few seconds with the text "Error: Error".

After leaving the "Subscription settings" screen, the OSM Live Overview screen still shows the old support region.
When I open the "Subscription settings" again, support region Albania is shown.

I'm using OsmAnd+ 2.5.4

**Comment by hariskar** [comment]
I have the same problem, any solution?

**Comment by vshcherb** [comment]
Looks like the issue is fixed, cause now it works.
