### ISSUE TITLE
[OSM Editing] Change category of POI

### ISSUE THREAD

**Issue by rbovard** [osmandapp/Osmand#3470]
When changing the category of a POI in OSM Editing plugin, the old value is kept with the new one.

See this example:
* Old:
  * amenity: `pub`
  * name: `Brasserie Artisanale`
* New:
  * amenity: `pub` --> Should be removed
  * name: `Pâtisserie Artisanale`
  * shop: `pastry`

*OsmAnd+ 2.5.4*

**Comment by vshcherb** [comment]
Merged to #2023
