### ISSUE TITLE
Collapse multiple search results into one, if it makes sense

### ISSUE THREAD

**Issue by andrasfuchs** [osmandapp/Osmand#3481]
I'm using OsmAnd+ 2.5.4.

Please take a look at this entry: 
![Screenshot of the map segment where this Starbucks is](https://cloud.githubusercontent.com/assets/910321/22615000/0c23bebc-eabe-11e6-90bd-3e04aeef3747.png)

Map: http://osm.org/go/4HtJD42SD?m=

This Starbucks is in its own building, on the island of Ko Samui, Thailand. It has the following tags:
name: Starbucks Coffee
amenity: cafe
building: yes
shop: coffee

When I enter "Starbucks" into the search in OsmAnd, I got the following 3 search results:
Starbucks Coffee - building
Starbucks Coffee - Coffee shop
Starbucks Coffee - Cafe

Ideally I would have only one result, since they are essentially the same thing. The search result list should collapse the 3 results into 1 item, something like this:
Starbucks Coffee - building, Coffee shop, Cafe

**Comment by breversa** [comment]
That's an OpenStreetMap issue : this coffee shop should (IMO) only be listed once, not three times.

**Comment by littlehelper** [comment]
Collapsing search results (as propsed by @andrasfuchs) with the option to fold them out again would be great to keep the search result list tidy.
