### ISSUE TITLE
bridge layer what cross railway

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/Osmand#3483]
from GooglePlay version:
![pic1](http://de.share-your-photo.com/img/6f59b76de1.png)

from latest nightly:
![npic1](http://de.share-your-photo.com/img/903be76b8b.png)
on this the footway have wrong layer.     
also the white man_made=bridge should be above railway
![npic2](http://de.share-your-photo.com/img/8901f4cf6b.png)

**Comment by pebogufi** [comment]
Looks like wrong tagging (wrong data), but not a problem within osmand.
Please check the data and correct it. If you don't have a openstreetmap account as mapper or if you don't know how to do it, tell us the node number or gps position.
Peter

**Comment by hakuchi** [comment]
there is no wrong data in OSM.

here the link to the data in OSM:
first two images: https://www.openstreetmap.org/way/172285696
third immage: https://www.openstreetmap.org/way/172285696

there I can not see any error in the data from OSM.
This error is not only on these 2/3 bridges. You can find them around the world

**Comment by hakuchi** [comment]
additional examples:
https://www.openstreetmap.org/way/165727532 and
https://www.openstreetmap.org/way/395675946#map=19/49.48791/8.44371&layers=N
![1](http://de.share-your-photo.com/img/35ff6094df.png)

https://www.openstreetmap.org/way/25185039
![2](http://de.share-your-photo.com/img/d5551c6fd9.png)

https://www.openstreetmap.org/way/25185020
![3](http://de.share-your-photo.com/img/10aed75d8b.png)

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/c44938ec1c361b13841081363532fada153518c6
