### ISSUE TITLE
Why is using offline maps "laggier"/slower than using online maps?

### ISSUE THREAD

**Issue by jfkimmes** [osmandapp/Osmand#3485]
It just seems weird to me that downloading and displaying a map tile is slower than just rendering it directly from my interal flash drive.

I am using a Nexus 6P, which should be able to handle the processing well enough, shouldn't it?

**Comment by sonora** [comment]
Not sure what you are asking here, but I am afraid this is not a valid question, you are comparing apples with pears ... :)

When you download maps, you are downloading mere bitmaps, the appearance of which was pre-processed on a server from the vector data in the map database.

When you use our offline maps, the app needs to, on the fly, create the bitmap to be displayed on your screen from similar vector map data, taking into account your parameters and preferences like map style, elements to highlight, day or night view, etc.
