### ISSUE TITLE
OsmAnd stops updating UI when unfocused on Android 7 multi window mode

### ISSUE THREAD

**Issue by TheLastProject** [osmandapp/Osmand#3489]
# How to reproduce
1. Launch OsmAnd
2. Start a route
3. Start moving
4. Hold app switcher button to add a second app
5. Open second app

# Expected behaviour
OsmAnd's UI keeps updating

# Actual behaviour
OsmAnd's UI stops updating

# Note
I believe OsmAnd probably stops drawing on onPause, which according to the Android documentation is also called when the app is unfocused in multi-window mode and OsmAnd should instead stop drawing on onStop and resume on onStart. See https://developer.android.com/guide/topics/ui/multi-window.html#lifecycle for more information.

# App / Device info
OsmAnd~ 2.5.4 (net.osmand.plus) from F-Droid on a Motorola Moto E 2015 LTE (surnia) running Android 7.1.1 (LineageOS 14.1-20170126-NIGHTLY-surnia). Also observed with an older 7.1.1 CyanogenMod release.

**Comment by vshcherb** [comment]
Duplicate #3730
