### ISSUE TITLE
Use maps downloaded in MAPS.ME

### ISSUE THREAD

**Issue by PanderMusubi** [osmandapp/Osmand#3490]
MAPS.ME also downloads maps in the directory MapsWithMe on the storage card of a mobile device. When these maps are not existing in OsmAnd or are newer than those in OsmAnd, automatically use these maps.

Offer a setting in general configuration to enable and disable this functionality.

**Comment by stephan75** [comment]
So you assume that Osmand can use offline map files from maps.me ??

Really???????

**Comment by PanderMusubi** [comment]
MAPS.ME uses also OSM. If download of a country is in a format which can be read by OsmAnd, why not? Saves the user storage space on their device.

PS   I am a big fan of OsmAnd, don't get me wrong on that.

**Comment by vshcherb** [comment]
Not possible, only if OsmAnd will use all the source code from mapsme

**Comment by PanderMusubi** [comment]
Before opening another issue, how about syncing or at least offering bookmarks from MAPS.ME in OsmAnd? Bookmarks in MAPS.ME are stored in zero or more KML files in the MapsWithMe directory. The default bookmark file is `My Places.kml`

**Comment by vshcherb** [comment]
OsmAnd mostly supports GPX files but has some basic support of KML. You can just open that file in OsmAnd.

**Comment by PanderMusubi** [comment]
Please, see https://github.com/osmandapp/Osmand/issues/2077 for a solution
