### ISSUE TITLE
[topo.render.xml] waterway: stream in tunnel not visible

### ISSUE THREAD

**Issue by Thunichgud** [osmandapp/Osmand#3493]
In OSMand default style a waterway stream in a tunnel (layer -1) is visible but in Topo style it isn't. Please make in the Topo style streams in the underground visible again. So it will be possible to see the relation of visible parts of streams.

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/00b8b03012415ce6f6bd403d8f17ee37601b86fb
