### ISSUE TITLE
Unexpected search behavior

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#3494]
There's this case with the search engine:

1. Download the map of Belguim.

2. Search for 'Rue des Masnuy'. No relevant results.

3. Search for 'Masnuy'. The result we were searching for, which is Rue des Masnuy, appears.

![bug_1](https://cloud.githubusercontent.com/assets/12711814/22784045/142e5884-eed7-11e6-8f8b-f528e204fc2d.png)
![bug_2](https://cloud.githubusercontent.com/assets/12711814/22784044/142df268-eed7-11e6-8815-b46ba18708a5.png)

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-tools/commit/fb88ac75aa0b21cd99b3446235e63ace79d78e14

**Comment by vshcherb** [comment]
The original issue seems to be fixed, new maps generation is required.
