### ISSUE TITLE
River Uruguay written in Hebrew

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#3496]
Some sections of River Uruguay are written in Hebrew. This is not caused by device language.

Additional info: 

16 Names [name(1) - Río Uruguay, name:es(32) - Río Uruguay, name:he(35) - נהר אורוגוואי, name:pt(34) - Rio Uruguai] id 5226804751 osmid 40834412
15 Names [name(1) - Río Uruguay, name:es(32) - Río Uruguay, name:he(35) - נהר אורוגוואי, name:pt(34) - Rio Uruguai] id 5226804751 osmid 40834412
14 Names [name:es(32) - Río Uruguay, name:he(35) - נהר אורוגוואי, name:pt(34) - Rio Uruguai] id 5226804751 osmid 40834412
13 Names [name:es(32) - Río Uruguay, name:he(35) - נהר אורוגוואי, name:pt(34) - Rio Uruguai] id 5226804751 osmid 40834412
12 Names [name:es(32) - Río Uruguay, name:he(35) - נהר אורוגוואי, name:pt(34) - Rio Uruguai] id 5226804751 osmid 40834412

![rsz_uruguay](https://cloud.githubusercontent.com/assets/12711814/22788515/b3340eea-eee8-11e6-8a0a-ae8548dda2fe.jpg)

**Comment by aceman444** [comment]
I didn't find any tagging problem at the river part in the picture (way 152198247). The way has a proper name tag with "rio uruguay". name:he is also there but shouldn't be shown if the user doesn't have OsmAnd set to Hebrew. Seems like an OsmAnd bug. The name:he was added 4 years ago and not changed since.

**Comment by xmd5a2** [comment]
This is not a problem with OSM data, rendering_types.xml or style. "name" tag just don't appear in map data at 12-14 zooms.

**Comment by vshcherb** [comment]
Fixed

**Comment by aceman444** [comment]
So what was the problem?

**Comment by vshcherb** [comment]
Some processing on the base zoom issues.
