### ISSUE TITLE
bad routing by treating "surface :wood" as "unpaved"

### ISSUE THREAD

**Issue by MAlfare** [osmandapp/Osmand#3498]
This Bridge should NOT be treated as "unpaved" in routing when "avoid unpaved ..."is set.
it has "suface: wood"
OsmAnd~ 2.6.0#20297M

![screenshots_20170209_112406](https://cloud.githubusercontent.com/assets/4406655/22806251/78841626-ef21-11e6-8c73-dc1e566ff6f1.png)

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/424d0c693560dade64786655a592e285a7c102e6
