### ISSUE TITLE
Two phones on a POI

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#3500]
If a POI has two or more phones (tag:phone_2, tag:phone_3...) OSMAND would show this tags clicking on POI.

**Comment by hakuchi** [comment]
D you have a example?
`_1`, `_2`, `_3` should nit be used in OSM. Same as `name_1`, `name_2`, etc. [Wiki link](http://wiki.openstreetmap.org/wiki/Names#Key_Variations).
you can add `phone=...`/`contact:phone=...` and `phone:mobile=...`/`contact:mobile=...` to OSM to display different numbers.

**Comment by OpenSourceForEver** [comment]
So phone_1 phone_2... Would be deleted from OSM.

**Comment by OpenSourceForEver** [comment]
It is not a issue for OSM. Sorry.

Thanks
