### ISSUE TITLE
I14e the level field

### ISSUE THREAD

**Issue by KOLANICH** [osmandapp/Osmand#3502]
OSM uses British notation for floors (0 is ground floor in British and first in common, 1 is first floor in british and second in common). OSMAnd displays these numbers even in the countries which use common notation. So I think you should add 1 to floor numbers of objects not situated in the countries using British floor notation.

**Comment by vshcherb** [comment]
OSM should ground-truth notation. So it is easy to check in the elevator.

**Comment by KOLANICH** [comment]
>OSM should ground-truth notation. So it is easy to check in the elevator.

It depends on the make of elevators. In Russia ground floor button has number one on itself.
