### ISSUE TITLE
Why does app communicate with osmand servers?

### ISSUE THREAD

**Issue by cxxuzbim** [osmandapp/Osmand#3508]
I thought this was an offline app. Why are there (unencrypted!) connections being made to the internet whenever opening the app?

In my opinion by default the only time after first run the internet is used should be when the user manually checks for map updates or is using an internet-enabled plugin.

**Comment by vshcherb** [comment]
It communicates to check if there are map updates, there is no personal information involved in check if map update exists or not.

There is also message of the day call but that will be configurable next release.
