### ISSUE TITLE
Double "dispensing" in pharmacy details

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#3510]
When displaying details of a pharmacy, the text "Dispensing: Dispensing: yes" is shown. 
It is probably caused by using both of poi_pharmacy_dispensing and poi_dispensing_yes strings, which both contain the word "Dispensing". That is a redundancy which should be fixed.

OsmAnd 2.5.4.

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/Osmand/commit/3e7066b39bc1ace8a06c255493e265da79044750

**Comment by aceman444** [comment]
Thanks.
