### ISSUE TITLE
[Feature request] Support searching highways using alt_name, loc_name, etc

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#3511]
Could osmand support/index highways with `alt_name`, `loc_name`, `old_name`, `reg_name`, `nat_name`, etc, please?

**Comment by hakuchi** [comment]
Alternative, local or regional name in search sounds good for me.
But `old_name` I think should not supported by search. The [Wiki](http://wiki.openstreetmap.org/wiki/Names#Key_Variations) say that it is for historical/old names(same as old_ref).
And if the name of a highway change, the new name is in `name=...` and the no longer in use name is in `old_name=...`

**Comment by naoliv** [comment]
About `old_name`, I was thinking when people still keep calling the place/street by its older name.
In practice (real life) people use the former name as if it was an alternative name.

Of course we won't map `alt_name` with the old street name, but I guess that we could allow to people search by it (and, even better, if it could display that this is the former name of such place).

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-tools/blob/master/OsmAndMapCreator/src/net/osmand/data/preparation/address/IndexAddressCreator.java#L937

**Comment by naoliv** [comment]
Hum... I wasn't aware of this.
But I think that I know why.

For example:
![](https://cloud.githubusercontent.com/assets/982338/23341843/0d1b7824-fc2e-11e6-9812-c59756b4c63e.png)

`Via Expressa` is the `alt_name` for `Avenida Maria Antônia Camargo de Oliveira`

Somebody trying to search for `Via Expressa` doesn't see anything about it in the screen.

Maybe osmand could display something like this:

![](https://cloud.githubusercontent.com/assets/982338/23341915/50115044-fc2f-11e6-80e7-9ca72c342acb.png)

Where it's clear that this result is the same street as the one that the user is looking for.

For `old_name` it could be the same case:

![](https://cloud.githubusercontent.com/assets/982338/23341923/699d07f6-fc2f-11e6-825d-76ad8c0dbf45.png)

Could we have this, please?
Could we also have `loc_name` supported?

**Comment by vshcherb** [comment]
Displayed on the 2nd line now.
