### ISSUE TITLE
Disappearing road

### ISSUE THREAD

**Issue by escoand** [osmandapp/Osmand#3513]
I have a problem with a disappearing road. When I scroll further it is appearing.
Start at http://www.openstreetmap.org/#map=17/50.81261/14.23159 and scroll the road 62 to the south until Decin and vice versa.

> What version of OsmAnd are you using, on what device and Android/iOS version?

OsmAnd+ 2.5.4

> Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?
> If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

Yes, official map of czech repulic.

![screenshot_20170212-102917](https://cloud.githubusercontent.com/assets/428567/22978359/bddc7fcc-f392-11e6-9c26-53cbcc606352.png)
![screenshot_20170212-102909](https://cloud.githubusercontent.com/assets/428567/22978360/bdf09a20-f392-11e6-966e-8a34b792c4c3.png)

**Comment by vshcherb** [comment]
This could be a known issue about OSM Live.

**Comment by escoand** [comment]
But I don't use OSM live.

**Comment by escoand** [comment]
For me the problem if gone with 2.7.5
