### ISSUE TITLE
[Feature request] Handle correctly intents from Airbnb, aka Could not parse geo intent 'geo:0:0?q=77.77%2C77.77

### ISSUE THREAD

**Issue by nicolas-raoul** [osmandapp/Osmand#3516]
The Airbnb app has a button to show a particular point on a map, the intent suggests OsmAnd as well as Google Maps (which handles it correctly).

OsmAnd opens but then shows:
```
Could not parse geo intent 'geo:0:0?q=77.77%2C77.77
```

While I understand that this feature has not been 'released', I guess it is a reasonable expectation for a maps app to handle it. That would be great if you could add the "Nice to have" label, thanks!

![screenshot_20170129-091939](https://cloud.githubusercontent.com/assets/99590/23015681/13172124-f477-11e6-9214-b68296a792a1.png)

**Comment by scaidermern** [comment]
That's not a valid geo URI, is it?

**Comment by vshcherb** [comment]
Doesn't look to be valid uri. https://developer.android.com/guide/components/intents-common.html
