### ISSUE TITLE
Unexpected bicycle routing (using cobblestone path)

### ISSUE THREAD

**Issue by quelbs** [osmandapp/Osmand#3518]
When routing from 48.18295/11.54089 to 48.18366/11.54107 with bicycle routing. The offline routing sends me via the cobblestone path. I would expect the routing to continue on the cycleways.
![route](https://cloud.githubusercontent.com/assets/570222/23064686/bad30a46-f511-11e6-9858-40f104af2ba9.png)

One remark: For "Driving style" _Speed_ the routing is as expected. The route in the screenshot is for "Driving style" _Safety_ and _Balance_

**Comment by xmd5a2** [comment]
Bicycle routing was significantly changed during last week. At that moment Driving style=speed leads forward, but "safety" and "balance" routes as on your screenshot. Please note that there is bicycle route which is more preferred that highway=path and even highway=cycleway without bicycle route.
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot%20from%202017-02-23%2012-05-42.png
Taking all these into account I can't see any unwanted behavior.

**Comment by quelbs** [comment]
I thought "cobblestone" should give quite a penalty, but in fact I did not realize the bicycle route. With your explaination I think it is a very special case where the routing is not optimal, but acceptable.
