### ISSUE TITLE
Examine if elevation data can be fetched from Brouter-interface

### ISSUE THREAD

**Issue by utack** [osmandapp/Osmand#3519]
Since Osmand 2.6 will support displaying elevation data of tracks, maybe you can see if Brouter can deliver the elevation data when called from within Osmand too
This would make things a lot easier for bike routing
Thanks for looking into it

**Comment by vshcherb** [comment]
The srtm data will be provided in OSM maps as well next release.

**Comment by utack** [comment]
That is cool, so elevation data can be displayed for ANY gpx?

**Comment by vshcherb** [comment]
You can try nightly builds to see how it looks, elevation data will be displayed from GPX itself.

**Comment by utack** [comment]
And if the GPX file is without elevation data, can the graph be displayed too?

**Comment by vshcherb** [comment]
Today, the only way it will be displayed if you calculate route along GPX.

**Comment by saemy** [comment]
See #3587 .

**Comment by utack** [comment]
Sweet, this makes bike routing even better
