### ISSUE TITLE
office=energy_supplier described as 'consulting office'

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#3520]
A POI with office=energy_supplier is described as 'Consulting office' in the POI details of OsmAnd (2.5.4). There is currently no string for Energy supplier (there should be one added), but using a non-related existing string is wrong.

**Comment by aceman444** [comment]
Sorry, I was in error, there were 2 nodes at the spot one with office=consulting, where only the 'consulting' node was shown as a POI and the other one invisible.

So please just add a string in phrases.xml for energy supplier and make it a POI.
Also, I think all office=* should be shown even if the value is unknown.

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/087e6dc0b743978eb6ba4b2988bd73f053e1fd96
