### ISSUE TITLE
Provide separate switches for "voice guidance" and "voice warnings"

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#3521]
As we learned in #3335, there is an obscure mechanism that switches voice traffic warnings on, and no mechanism to switch them off. 

As @sonora said, the "voice module is only activated upon starting the navigation, ... and remains active thereafter". 

This leads to an initial user experience that it sometimes works and sometimes not. (It works when there was some navigation before, and the app was only sent to background. It does not work once the app was fully closed, an update installed, or the phone rebooted. If I want to hear the warnings in non-nav mode, I need to start the routing process first and kill afterwards. )

Currently there is one switch "Voice guidance" in Global settings that selects the language. Please provide a second switch, or a tick-box within the language selection, that switches the "voice warnings" on/off, to provide predictable behaviour. Having those two switches, I have four options, to hear guidance or not, and to hear warnings or not. 

Please also consider to have these switches in the profile specific setting. Thus I could hear warnings in car mode, but not in browse or foot mode. 

(BTW, the "Navigation settings" should be labelled "Profile specific settings" or "Transport mode specific settings" in the first place, so settings that are profile-specific but non-navigational would fit in here more logically)

**Comment by Chumva** [comment]
This was added in `Configure profile` settings - `Navigation settings` - `Voice prompts`.

**Comment by cannycartographer** [comment]
Hi,
It would be useful to be able to have voice warnings even when the user is not navigating to a specific destination. For example, so drivers can receive warnings about speed limits while using Osmand, even when they are not using its routing functions to provide voice navigation.

I understood that to be the aim of this bug report, so could I reopen it to represent that feature request? Or should I start a new issue?
Thanks for a great app!

**Comment by sonora** [comment]
I actually think this works, all you have to do is activate the voice module, e.g. by briefly by starting  then stopping again an arbitrary turn-by-turn navigation.

Of course, without following a route, your results will be less precise, you may be alerted for e.g  things (based on mere proximity) in the vicinity but not immediately on the (not known 😉) actual path you intend to use.

**Comment by cannycartographer** [comment]
Good point about the results being less precise, makes sense. But still I think this could be useful for many people.

I tried as you suggested but it doesn't seem to be working - I understood from discussion upthread that this behaviour had been changed.
