### ISSUE TITLE
map language of 'local names' does not work on the global world map

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#3522]
If you set a specific map language (e.g. English or German) you properly get names in that language (or local name) regardless of the map zoom level.

But if you select language of "local names", it behaves differently. When map is zoomed in (close to the details), the local names are used from the map of that region. When you zoom out so that the World overview map gets used by OsmAnd, names suddenly switch to the language of the OsmAnd UI. Thus observing e.g. some capital city and changing zoom, you see the name of the city change from local to a translated name.

The switch occurs when going from zoom 11 to zoom 12. You can try it e.g. on Moscow (you do not eve need to have Moscov region map). On zoom 12 the World map is used too if no region map is available and the language switch occurs too.

OsmAnd 2.5.4, seen on 2 very different devices.

**Comment by pebogufi** [comment]
This discussion does not come up for the first time:
I try to point it out from a different view - where or how can I select the language for which purpose ?

From zoom level 12 and more **regional** maps are displayed.
The language for names is selected on menu / Configure map / Map language / which can be a specific language or "Local names", which works perfectly. Names of french cities are displayed in french, names of russian cities are displayed in russian, and so on.

With  zoom level lower than 12 **global** maps are displayed.
The language for names is selected on setting menu / Setting / General setting / display language, which can be System (Device language) or s specific language.
So the global map does NEVER use "local names", but a specific language can be used (which can be Device language). But then all names - independent of the contry they belong to - are displayed in this specific language.

What I would prefer very much, is having the option for use of "local names" as well for the **global** map (on zoom level less than 12). Then the confusion of changing names by zooming up and down would be gone.
Regards Peter

**Comment by sonora** [comment]
It is by design, think about it: Using "local names" on a world map would mean you see all sorts of languages and character sets like latin, greek, cyrillic, arab, chinese and many more all on the same map! This would hardly be of use to anybody.
