### ISSUE TITLE
(full) Tag removal is not synced with osm live 

### ISSUE THREAD

**Issue by HolgerJeromin** [osmandapp/Osmand#3523]
I have two ways which I removed all tags. Both removals are not synced to osm live :
https://www.openstreetmap.org/way/370767385/history still a highway on osmand 
https://openstreetmap.org/way/121414819/history still a swimming facility (in addition to the new multi polygon)

**Comment by vshcherb** [comment]
Not reproducible today, with new issues like that we will be able to catch with our new test framework but we can't catch > 1 month ago issues. This issue might be related to #3034

**Comment by HolgerJeromin** [comment]
This seems to be a generic "update" issue. The [Restaurant](https://www.openstreetmap.org/way/287241951) "opening_hour=" [change](https://www.openstreetmap.org/changeset/49753803) is not shown but the new "note=" from the same changeset is shown.

**Comment by vshcherb** [comment]
POI changes are not fully tested yet and have that issue, though the map change was tested recently and works fine.

**Comment by HolgerJeromin** [comment]
https://www.openstreetmap.org/node/4987765603/history

New in July with fixme
Lost its fixme and got gate

Current osm live has gate and fixme

**Comment by PaulStets** [comment]
The issue is irreproducible. The .obf file with the update (17.07.2017) has the node with correct tags:
```
<node id = '193831' version='1' lat='53.885834' lon='8.643751' >
	<tag k='barrier' v='gate' />
	<tag k='access' v='private' />
	<tag k='original_id' v='4987765603'/>
```
Screenshot:
![20641523_1896268197286652_1144947072_o](https://user-images.githubusercontent.com/20681525/28995175-6798f4a4-79ea-11e7-8849-0494f0c7bb14.png)
