### ISSUE TITLE
Incorrect adress

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#3524]
Osmand 2.6.0#16246D February offline maps without OSM Live

If I tap on the hostel here https://www.openstreetmap.org/#map=19/40.72517/-4.02078    OSMAND shows an incorrect adress (different from OSM data).

OSM data: Calle de la Tejera, 18
OSMAND shows: Calle Doctor Julio González Villasante 55

**Comment by vshcherb** [comment]
Possibly temporarily issue not reproducible with March maps.
