### ISSUE TITLE
Display "ref" for buildings

### ISSUE THREAD

**Issue by utack** [osmandapp/Osmand#3527]
Some buildings do not have a name, but only a "ref"
Example would be allotment huts or single units within a hotel (especially common on islands that are owned by one hotel)
Could you consider displaying the "ref" for a building, when it has no name tag?

**Comment by utack** [comment]
It seems like you currently dump "ref" tags when generating maps.
Depending on how the style is analyzed it might also need a new "nameTag3"

**Comment by xmd5a2** [comment]
Fixed
https://github.com/osmandapp/OsmAnd-resources/commit/5143a896354922ff12e90d26c59edb94d635c4b0

**Comment by utack** [comment]
Thanks for including it!
