### ISSUE TITLE
Split regions with more than 500Mb

### ISSUE THREAD

**Issue by morray** [osmandapp/Osmand#3528]
For the offline maps some regions are getting pretty big. Even with bigger memory in the phone this starts to get bothersome if you need several regions for traveling or other reasons. Also updating the maps each month takes long due to the large file sizes. It would be good to split regions with e.g. more than 500 MB into sub regions. 

Also allowing direct download of cities would be great especially for business travels and city tours.

**Comment by hakuchi** [comment]
there are about **11** maps with more then 500MB.     
Entire map of **Poland** is over 1000MB, but they is just split into **16 parts** from not over 140 MB.
Entire map of the **Netherlands** is over 890MB, also split into **12 parts** from not over 150 MB.
Entire map of **England** is over 820MB, also split into **10 parts** from not over 120 MB.
Entire map of **Spain** is over 770MB, also split into **19 parts** from not over 110 MB.

The only maps what have over 500MB are `Germany_nordrhein-westfalen - 590MB` and `Germany_bayern - 530MB`.
If you use a other navi(TomTom, Navigon, Sygic, Here) with offline maps they don't split the country into smaller parts. Also they give a message popup that downloading maps shold done only over home wlan connection.
Navi apps with data from OSM don't split there map data into smaller parts, they have one download for one country or into north and south with larger files.
I update my maps at home over my wifi and not on the way over data connection.

Final question: 
If you will have, for example, the complete country from Poland, you have to download 1010MB of data  to become the complete map, you have to download the same MB if you download the 16 parts of this country. So nothing change.

Also to many parts of one country make it difficult to find correct part from country if I travel to a unknown country.
Example:
I travel from _Amsterdam_(Netherlands 12 parts) over _Germany_(16 parts) to _Rome_(Italy 20 parts) or 
From _Amsterdam_(12 parts) over _Belgium_(1 part) and _France_(21 parts) to _Madrid_(Spain 19 parts).

**Comment by noci2012** [comment]
As much as i Like the idea of splitting the data in smaller maps it also means more of the geography of a country needs to be known  to select the right map.
To Travel from Rotterdam - Lelystad (100Km journey) you will need at least 3 maybe 5 of the maps (depending on exact route) and for all points in the planned travel,  the right map needs to be chosen.  So making maps smaller might need a change in point selection where it isn't needed to ALSO select the right map.

**Comment by morray** [comment]
The knowledge question can easily be addressed. Either in addition the whole country is downloadable or there is a check box "download all". Are more fancy way could even be do have a feature ala "download maps along route" while online.

The download on wifi is obvious. But 9 GB ( my take last month) still take some time even on my 50mbit/s line. Not to speak of using up a significant part of my 64 GB available on the phone.

**Comment by noci2012** [comment]
It won't help to download the whole contry piecemeal, you need to know that Rotterdam is in South-Holland and Lelystad is in Flevoland.... And if you need to pass through Utrecht & Amersfoort to get there (round trip) you also need to know Utrecht is in Utrecht and Amersfoort is in Gelderland.
and the map for North-Holland is needed as well.
And download all just before a trip is a no-go as well unless one starts planning the detailed trip a few days ahead... Any map is too large to download while walking from home to car f.e.
And downloads needs to be done While WiFi is still available.

**Comment by morray** [comment]
Not sure on which comment you are answering but my point in short was either you know your geography and download what you need or you don't and got the "download all" on the level there you are still sure that you know the geography.

**Comment by hakuchi** [comment]
@morray 
> It would be good to split regions with e.g. more than 500 MB into sub regions.

Give us some examples.

For me, OsmAnd no need more parts of maps or more minimaps.

Looks similar as #3144

**Comment by homersimpsons** [comment]
@hakuchi
I think he wants the same downloads as MAPS.ME

**Comment by morray** [comment]
@hakuchi let's use your own example: Bavaria. Now 530 MB. I would bet that 60 % or more of the people downloading this map are actually only interested in the largest city, i.e. Munich, it's surroundings and the region of the Alps. So splitting up Bavaria into it's seven subregions (Oberbayern, Niederbayern, Schwaben, Oberpfalz, Unterfranken, Mittelfranken, Oberfranken) would meliorate the situation for many people considerably. In this scenario, most users would probably download the much smaller  file of Oberbayern (containing Munich as well as most of the Alps & probably still the largest) While the users interested in the other areas would not be bothered with all the dead freight. This would alleviate not only the memory on users phones but also the upload bandwidth of the osmand severs. If wanted in addition the file Bavaria could stay for users who need whole Bavaria.  The same story can be run probably for any region: almost always there are hotspots of interest.

Speaking of hotspots: are there any download stats, which region is downloaded/updated how often?
If you point me to the point where the regions are defined for processing, I happily created a pull request. But it seems I did not find the correct repository yet.

@homersimpsons :What is Maps.me offering? Never used that app.

**Comment by homersimpsons** [comment]
@morray
Maps are updated each month, except for world one
MAPS.ME offer small region download only (the map is fragmented a lot )

**Comment by vshcherb** [comment]
The request is not quite clear, it looks like most of it is implemented. If it is about to download only 1 city, I'm afraid we're far to be ready. 
Anyway roads-only maps are recommended to use for people who concerned about huge maps. Road only maps much smaller and they have address, poi and map consists of roads.
