### ISSUE TITLE
L10N - easy fix - split extended description

### ISSUE THREAD

**Issue by Jibec** [osmandapp/Osmand#3541]
Hi,

can you please split osmand_extended_description_4000_chars in multiple strings to translate?
It scares me each time there is a change (hundreds of words), and if by change we don't have time to complete it, the full text probably won't be published, even for an added comma.

It also makes translator's work more difficult, because the diff provided by weblate is huge.

thanks for your outstanding work!

**Comment by vshcherb** [comment]
Thanks very nice idea! We also struggle every time to change 1-2 sentences cause then we know it will take a long time to get translation back.

**Comment by Jibec** [comment]
Le 8 mars 2017 14:46:29 UTC+01:00, vshcherb <notifications@github.com> a écrit :
>Thanks very nice idea! We also struggle every time to change 1-2
>sentences cause then we know it will take a long time to get
>translation back.

I assume country names are already available through CLDR database (it is annoying to translate), but it is a much bigger work to do.
-- 
Jean-Baptiste Holcroft

**Comment by dmpr0** [comment]
Split description into parts.
https://github.com/osmandapp/Osmand/commit/ac8d83c897fabe1aa57575d076b5df0873e5bc7e
https://github.com/osmandapp/Osmand/commit/c76f092e030dc5c07f6bcd41f7428e0d7a57336d
