### ISSUE TITLE
Map display language name:xxx

### ISSUE THREAD

**Issue by BoFFire** [osmandapp/Osmand#3542]
Hi,
As a betatester I would like to have an option in dev mode to test name:xxx for map POI display. For example, in Algeria and Morocco to test `name:ber` `name:kab` and `name:tgh`.
At the moment TTS and vocalizing is not important if this feature is enabled.
Thank you for reading me :)

**Comment by pebogufi** [comment]
Change language in Configure Map, I think it is that what you need.
Peter

**Comment by BoFFire** [comment]
:) Thank you @pebogufik I know :)
I'm a translator for OSMAnd on Weblate :)
(Arabic, french and kabyle).
Yeah; neither Kabyle nor Berber are present on map language map ;)

**Comment by BoFFire** [comment]
Taginfo https://taginfo.openstreetmap.org/keys/name:ber#map
https://taginfo.openstreetmap.org/keys/name:kab#map

**Comment by BoFFire** [comment]
Berber and kabyle keyboards are comming
https://github.com/AnySoftKeyboard/LanguagePack/issues/54

**Comment by sonora** [comment]
@BoFFire Forgot to post it here, but I have this morning added `kab` and `ber` to the list of "Map display languages" available in the "Configure map" menu. I think this is the easiest solution for you. You can test with our nightly build. `tgh` does not seem t be a valid ISO code?

Not sure if you require special fonts, though, but that would be another issue.

**Comment by BoFFire** [comment]
@sonora <3
zgh ISO sorry my bad :) is equivalent to ber.

**Comment by BoFFire** [comment]
Thank you ! Dr. @sonora
https://twitter.com/BoFFire/status/839407480044158976

**Comment by BoFFire** [comment]
Last tweak @sonora @vshchreb : name:ber ok on app GUI, I have the names in name:kab instead of ber. Can you check name:ber display on map.
Merci beaucoup :) Danke :)

**Comment by sonora** [comment]
Don't understand. From what I see, the implementation should be correct: Selecting Map display language "Berber" should prefer displaying `name:ber` (if present), and "Kabyle" should produce `name:kab`.

**Comment by BoFFire** [comment]
@sonora check my tweet :)
Now, if it is a font problem I'll try to test locally. Don't bother yourself.
https://twitter.com/BoFFire/status/839495971671257088
Have a nice day :)

**Comment by BoFFire** [comment]
I test a forged but non Unicode font and this is what it should display :
https://twitter.com/BoFFire/status/843447374563459072
@sonora
