### ISSUE TITLE
Missing hiking route relations

### ISSUE THREAD

**Issue by jlevente** [osmandapp/Osmand#3544]
Hi,

I noticed that some hiking routes are not rendered on the map. I'm using OsmAnd+ 2.5.4 on Android 6.0.1 (OxygenOS 3.5.6) with an OSM Live subscription.

I tagged some hiking routes with `osmc:symbol` and most of them appear on the map fine. However, I'm missing one of them which does not get rendered in OsmAnd (not even when picking `coloring according to route scope`). I think it has something to do with `osmc:symbol` but I couldn't find a list or description of the rules/symbols OsmAnd is using.

### Additional info:

Map: `Us_florida_northamerica`
Area on waymarked trails: https://hiking.waymarkedtrails.org/#route?id=7037710&map=15!27.0174!-80.1545 (all relations rendered correctly)
Missing relation: https://www.openstreetmap.org/relation/7037710
Screenshot:
![screenshot_20170309-102539](https://cloud.githubusercontent.com/assets/7226757/23756819/e89f65cc-04b2-11e7-8abe-35ecfb75b4de.png)

I was thinking that maybe `orange:white:orange_rectangle` is not rendered on the map but this wouldn't explain why that section doesn't appear when selecting a different rendering method. Also, another relation with the same `osmc:symbol` is visible in OsmAnd: https://www.openstreetmap.org/relation/1163455#map=8/28.922/-82.601

I also noticed (might be related) that hiking route relation names in OsmAnd can be different. This particular one was changed 3 days ago (https://www.openstreetmap.org/relation/6677191). OsmAnd renders `White loop` as opposed to `White loop (JDSP)`. So maybe relations are not updated as frequently as other map items?

**Comment by xmd5a2** [comment]
Relation was created just 4 days ago. OsmAnd uses osm database from first day of every month. Just wait for next update
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/Screenshot%20from%202017-03-09%2020-33-48.png

**Comment by jlevente** [comment]
I'm using OsmAnd+ with OSM Live subscription @xmd5a2 so that relation should also be there by now, I assume. Other relations I added around the same time are all there, that's why I found it strange.

**Comment by vshcherb** [comment]
Not reproducible any more but with new issues starting this month we will be able to catch and reproduce with our test framework for osmand live.
