### ISSUE TITLE
Additional reminder for contour lines

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#3545]
The first issue is “contour lines” and getting those working.  Essentially the issue is that contour lines need to be *downloaded* before they can be used. This is not immediately obvious when you are presented with menu options which let you choose at what zoom level the contour lines appear. If there’s a menu option there, you would assume that you should be seeing the lines!  Of course, you have to go to map management and find your area and then download the contours. Ah.  This is not intuitive. I think the contour line menu option should TELL you that there are no contour line maps available, instead of letting you select the level. It’s not at ALL obvious to the inexperienced user.
Likewise, if I select a zoom level for a contour line, I should be told that nothing will appear because there are NO contour line maps!

**Comment by vshcherb** [comment]
Covered by AND-497
