### ISSUE TITLE
Fix Configure map - show current track

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#3546]
When you are recording a GPX track, you have to go to the GPX menu and not only enable the switch, but you also have to go to the list of GPX files and specifically select “show current track”.  This is another of those “double action” things you have to do to get things working. I think that the “show current track” should a) be on by default and b) displayed as an option on the menu which lets you choose the frequency (5 seconds etc) of the point recording.
These sorts of related things which must be “correct” for a feature to work should NOT be distributed in disparate parts of the UI.  If I start a GPX, then the option for seeing the track or not should immediately be presented to me. It shouldn’t be buried in some menu unrelated to the action I’m taking.
Similarly, there are parts of the UI which are obscure and require online searching to use.  For example, just to enable GPX recording, particularly the onscreen “button”, I had to go to an obscure plugin menu and enable track recording.  Yet, the UI itself has a clear and always present GPX menu with “show current track” on it.  It’s just really messy.

**Comment by vshcherb** [comment]
Observation: It doesn't seem necessary that we show recorded track immediately, on all places where we record track the progress is shown.

To fix: the UI should not display "Show current track", if Plugin Trip recording is disabled.

**Comment by sonora** [comment]
Three more observations:
- (1) After tapping "Details" on our track analysis screen, we show the track on the map, together with a context menu card for the track. There is an "X" button in the top right corner of the map screen. Tapping it should not only make the context card disappear, but also the track itself, right? (Exactly lihht we do it when e.g. a bus or other transport line is displayed).
- (2) In the top left of that screen we againn display "Details", but should probably simply display the track name?
- (3) The button on the GPX analysis screen is also called "Details", but its meaning is actually "Show on map" (and can replace the "Show on map" switch in the first line, which currently uses a lot of real estate on small screens.

**Comment by vshcherb** [comment]
(1) Disagree cause in that case it is a good shortcut to display on the map (most likely to be used) , though I could X button may be misleading.
(2) Agree
(3) Disagree, it is actually to show combined graph & the map. So it is more detailed screen regarding the map than general. "Show on map" implicitly says to quit track analysis, "details" highlight that you can investigate track from different perspective.

**Comment by sonora** [comment]
Hello Victor, I think I found some simple fixes as follows:

- Regarding (3), I suggest we just call it "Analyze on map" then. (It does not provide more details, actually fewer, just offers more graph manipulation options and a better way to view on and correlate with the map)

- Regarding(1), the easy fix is we simply honor the "Show on map" switch correctly (curently we seem to auto-set it to ON when tapping "Details"): If the user selected ON for the track, the track must remain visible after exiting the map screen's GPX analysis via(X), but if the user did not set it to ON, the track should also disappear after exiting the map analysis. Currently we ALWAYS leave the track behind visible on the map screen, which is a nuisance if you analyze several tracks in a row for mutual comparison, as getting rid of them requires many clicks completely elsewhete in the UI (which is also Leonid's point hete)

- (4) I also suggest to rename the group of visible tracks in the GPX list from "Active" to simply "Visible".

**Comment by vshcherb** [comment]
(1) Partially agree though I believe we will switch to this implementation.

**Comment by sonora** [comment]
Regarding (1), if you want, as a compromise I can imagine we set "Show on map" to ON by default whenever entering the analysis screen. In this fashion nothing would really change for your use case at all. But people for the use cases I am talking about can simple move the slider to OFF before proceeding to "Analyze on map", and would still save many taps overall.

**Comment by vshcherb** [comment]
I think we reached an agreement to not display it, otherwise we will need to introduce a switcher "Show on map" on the screen which would take place.

**Comment by sonora** [comment]
Just to make sure we are talking about the same thing: I was talking about the "Show on map" switch on the previous screen, which is already there, right? (Just above the split interval and Color selection.)

**Comment by vshcherb** [comment]
Yes it is already there.

**Comment by vshcherb** [comment]
Suggested fix:
1) If recording is disabled, suggest dialog to record current track (same as clicking on widget)
2) If trip planning plugin disabled, open plugin page with trip recording

**Comment by sonora** [comment]
Victor, that sounds like helpful improvements. But unless I misunderstand Leonid, he is also talking about the following use case: A user is finally aware that he can start trip recording by tapping the on-map GPX recording widget. A dialog pops up letting the user chose the recording interval.

3. And I think Leonid is saying that very dialog should also contain a check box to immediately display this currently recorded track, so the user is aware this can be done, and also does not have to go *completely* elsewhere (to Configure map / GPX tracks) to enable it if desired.

**Comment by vshcherb** [comment]
Hm, yes. Though in that case that's extra question which is not necessary and it could be quite annoying in case person doesn't want to see the track. On the other hand it makes sense.
Let's add to todo list
3. In the dialo

**Comment by sonora** [comment]
@crimean "Show on map" checkbox on the "Set Interval" dialog seems still missing? (3. in Victor's last comment above.)

**Comment by sonora** [comment]
Let me re-open this unless I missed a decision to not implement "3."
