### ISSUE TITLE
Crash when canceling out of "Add a GPX track"

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#3547]
- Fresh app start (essential to reliably reproduce)
- Tap Configure map
- Tap GPX tracks
- Tap Add track (listing of Download folder will appear)
- Hit the device's BACK button 3 times to back out of related screens.

OsmAnd will crash without error log after 3rd tap.

**Comment by crimean** [comment]
Cannot reproduce. Hardy, could you please send exception log?

**Comment by sonora** [comment]
Sorry, am on a long trip, middle of nowhere... :)
There is no exception log created from what I see... weird. Will try a newer build, as soon as I can download one, and close this if gone.

**Comment by sonora** [comment]
Alexey, seems fixed, thanks!
Best, Hardy
