### ISSUE TITLE
Unwanted route deviation to current location

### ISSUE THREAD

**Issue by gaellafond** [osmandapp/Osmand#3548]
I'm planning my trip to Nepal from my home in Australia. I wanted to know the route from the airport in Nepal to my hotel in Nepal.

- From: Airport in Nepal
- To: Hotel in Nepal

Expected route: About 1km.

Result: Start from the airport in Nepal, goes all the way to my current location in Australia, then back to Nepal, to my hotel. Route of about 8000km.

Is there a way to actually calculate a route that doesn't include my current location?

**Comment by vshcherb** [comment]
Yes, if you click bottom button "Directions" you can select any From and any To.

**Comment by gaellafond** [comment]
That's exactly what I did!

The result was a route that goes from Nepal, to Australia (4000km) and back to Nepal (4000km) instead of staying in Nepal (1km). I can't find a way to tell it to ignore my current location! All the routes that it calculates goes like this:

"From" - current location - "To"

Example:
- From: Nepal
- To: Hong Kong

Result:

Nepal - Australia - Hong Kong

**Comment by njohnston** [comment]
@gaellafond: I have a similar problem. The workaround is to long press the location you want to directions *from*:

![osmand_directions_long_press_small](https://cloud.githubusercontent.com/assets/638458/23918030/54301090-08e9-11e7-8da5-665846a14339.jpg)

Tap the three dots button and select "Directions from":

![osmand_directions_three_dots_small](https://cloud.githubusercontent.com/assets/638458/23917902/d602e31e-08e8-11e7-9759-a3b8b9c707f2.jpg)

Then tap "Selection destination":

![osmand_directions_to_small](https://cloud.githubusercontent.com/assets/638458/23918066/67b291e2-08e9-11e7-87a4-b3f60bef62a7.jpg)

Sometimes (but not always) "Select on map" doesn't work as I'd expect--I get the same behaviour you do. Selecting a favourite is much more reliable, so you could create a favourite for your destination first as a workaround.
