### ISSUE TITLE
Unable to import favorites

### ISSUE THREAD

**Issue by allejok96** [osmandapp/Osmand#3549]
Trying to import favorites only results in a toaster message saying "error when reading GPX data". Have tried with and old favorites file I want to import. Also created some favorites, exported them and tried to import them again.

But manually replacing the favourites.gpx file in the Android/data directory and restarting OsmAnd imports the favorites. Apparently OsmAnd stores the "real" database of favorites somewhere else, because replacing that file does not remove previously saved favorites...

Tested on OsmAnd 2.5.3, OsmAnd~ 2.5.4 and OsmAndF~ 2.6.0#16590D on an OnePlus 3T running Nougat 7.0.

 Example file:
```
<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<gpx version="1.1" creator="OsmAndF~" xmlns="http://www.topografix.com/GPX/1/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
  <wpt lat="-0.6529877" lon="1.4735143">
    <name>test</name>
  </wpt>
</gpx>
```

**Comment by vshcherb** [comment]
Unfortunately could not reproduce it.
