### ISSUE TITLE
OSM Editing: cant upload poi if it was modified before upload

### ISSUE THREAD

**Issue by muzirian** [osmandapp/Osmand#3550]
If a poi was added to osmand and was modified (like moving the postion, by changing marker position again) before it was uploaded, then it throws error when uploading.First the error was poi not found, when now i retry its IO error or the first error with error unkown .

Looks like if the position was changed before upload, osmand then considers it only as change to an existing poi which then creates problems when uploading as osmand tries only to modify the poi, (not to add it).

**Comment by vshcherb** [comment]
Fixed
