### ISSUE TITLE
i18n/l10n selecting local language as map language

### ISSUE THREAD

**Issue by yabba** [osmandapp/Osmand#3552]
Selecting local language as map language causes the application to use the Application language as map selected language.

It's expected to see the language of each land/region of the map beeing used, not the application selected language.

If I eg. select German as Application language I don't like to see the naming of Polish or Spanish regions in German. I like to see them in Polish and Spanish.

**Comment by vshcherb** [comment]
Should you use "Configure Map" -> Map Language -> Native.
The app language is "General Settings" -> App language.

To be honest could not reproduce this issue 2 settings are independent.
