### ISSUE TITLE
Map Markers in widget or top should appear in same order as in list of Map Markers

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#3554]
I don't know in which order the Map Markers appear in widget or in top...
When I change order of Map Markers in list, or deleting some of them I would like to see them in same order in widget or in top.
This would be very helpfull.
- - -
I love Map Markers very much to organize the use of osmand!
OsmAnd is a VERY good peace of work, thanks !!!
Regards Peter

**Comment by vshcherb** [comment]
We need to investigate and document it. Do you see map markers appear while you approaching (the closest)? Top 1 should stay unchanged always, until you manually change order.

**Comment by pebogufi** [comment]
I am sorry for the dalay of my answer, I had some problems with notification by email.
- - -
May be there is a misunderstanding.
I have no problem of seeing the map markers in the map, that is ok.
I want always see the two markers which are in top of the list also as widgets. Upper as upper, second as second.
When I change the order in the list, maybe then there are two other markers on the two upper positions. Then the marker shown as widget, should also be changed to the new upper ones.
Do you understand what I mean?
