### ISSUE TITLE
Add Latin America to Driving region menu

### ISSUE THREAD

**Issue by ignaciolep** [osmandapp/Osmand#3555]
Latin America is missing in the "Driving region" menu. Recently it has been forced in the es_AR and es_US translations of driving_region_europe_asia.

Almost all countries in Latin America are Right-hand driving and use Kilometers per hour.

See this Wikipedia image: [Countries by handedness of traffic, coupled with the distance/speed unit](https://upload.wikimedia.org/wikipedia/commons/6/64/Countries_driving_on_the_left_or_right%2C_uses_kilometers_or_miles.png)

Thanks!

**Comment by vshcherb** [comment]
Now we have "Automatic" detection so it should not a big problem. Though we are going to update translations.
