### ISSUE TITLE
Background service can somehow "lock up" GPS reception

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#3556]
Not sure how to debug this, but it is really annoying:
- I have used OsmAnd for years to record long backcountry trips (2-12 hours)
- Phone would be in airplane mode, Location service is set to "GPS only"
- GPX recording interval is set to 30 sec to conserve battery, i.e. our background service lets GPS go to sleep between measurement points
- Lately, and only starting with builds about this calendar year, OsmAnd sporadically stops logging. When I look at the OsmAnd screen again, no points may have been logged in a while,, GPS reception is shown as 0/0 (no fix, of course), and it stays like this indefinitely
- Switching to another app like GPS Status also reports satellite status 0/0
- Stop/ restarting the trip logging does not help, neither does resetting the A-GPS status
- What does help immediately is force-closing OsmAnd and restarting it (so it seems OsmAnd related(
- I cannot rule out a hardware issue, but this is on a device which had worked reliably for years, and there was no recent Android update for ot
- Not quite sure, but it seems the issue only comes up when Android's "Power saving" feature is enabled (Android 4.4.2).
But the issue seems new, only our 2017 builds (very roughly) seem to exhibit it.

Any ideas?

**Comment by pebogufi** [comment]
Hi Hardy, I also had gaps in recording, only sometimes, but as well frustrating. The recording normally continues when opening osmand, and looses data again after some minutes, sometimes more then once during a tour.
Sometimes I use osmtracker parallel to osmand on same device (!) and - surprise - osmtracker creates tracks without gaps, while the osmand track has one or more gaps...
Peter

**Comment by sonora** [comment]
Hello Petrr, ok, thanks, could be the same issue, but not sure. I am talking my old work horse Samsung S4 mini, stock Android 4.4.2.

Do you see any correlation whether "Power saving" is on or off (Android settings or notification bar)? It is currently my prime suspect ...

Also: On my device I have never seen things resume without first killing OsmAnd, except once where I think pausing/restarting the recording from the notification bar seems to have helped. (But usually not.) Also strange that in my case GPS Status also lost all satellites until OsmAnd was manually killed.

I wish I could test more devices as always, but am currently on extended backcountry travel.

**Comment by pebogufi** [comment]
I always use Powersaving ON. For me it happens only when device goes to standby (during walking) but not always, I would say in less than 20% of situations. I often use navigation by hiking, but not really startet, only in "prepared mode". I don't need and don't like at all vocal comments in the forest!  But the line showing the planned way is very helpful if I switch divice on again to look whether I am still on the planned way. In this kind of usage I have sometimes gaps, while osmtracker never has gaps.
Hope, I could help, but know it is VERY difficult to investigate problems which occur only very rarely.
The gaps never occurs in real navigation by car when power is with cable.
Peter

**Comment by sonora** [comment]
I have been going with Power saving OFF for the last 2 days, No gaps yet... Also no visible change in power consumption, I burn roughly 3-5% per hour with Osmand logging at 30 sec intervals, regardless if PS is on or off, only depending on how often I turn on the screen to take pictures or look at the map. Would be interesting and a good hint if PS=OFF fixes it on your device, too?

**Comment by pebogufi** [comment]
I will observe on hiking next weekends, we will see...

**Comment by vshcherb** [comment]
On my device I sometimes observe complete GPS info lost, sometimes app restart helps but sometimes I need to reboot the phone. I didn't manage to correlate it with anything and I suspect some hardware issues, hopefully it happens very rarely. As always we could only fix issues which are somehow reproducible and better on dev devices, so it is possible to debug.
I will keep an eye on this issue.

**Comment by sonora** [comment]
Yes, I do see stuff like that on some different devices, and it seems to be issues specific to a device's chipset/driver implementation.

The issue I originally reported here, however, is a little different, because it happened on a well-known older and always reliable device with no Android upgrades in recent years. All that changed was our OsmAnd builds. I think the changed behavior of what I believe may be somehow sensitivity to the Android Power saving setting could have occurred when we introduced the new trip recording notification and buttons there, but this is a wild guess only. specific issues

**Comment by polarbearing** [comment]
Just another guess, could it be that the system's gps demon is crashed, but would only restart once all subscribed services are closed (i.e. all OsmAnd, GPS status, other apps)?

**Comment by sonora** [comment]
Yes, that would certainly fit. From all experiments I have done the last few days the version of the issue I am observing seems rather clearly associated with the Android Power Saving feature beinf turned on. But it is rather unclear whether we can do anything in OsmAnd to handle things more gracefully.

**Comment by rdoeffinger** [comment]
I have seen this issues as well, also with other apps than Osmand.
At first I rebooted (just killing e.g. Osmand would not work), but I later found out that disabling and re-enabling GPS in settings fixes it as well. Though I am hesitant to suggest that, even if Osmand could do something like that on its own...
This is on an LG G4 with Android 6.0.

**Comment by sonora** [comment]
Thanks for reporting! I find that sometimes disabling/re-enabling GPS in Android helps, sometimes not. I really suspect some sort of GPS cras on the system level and there may be nothing we can do in OdmAnd about it.

For my particular case I have found after 4 weeks of testing that on a Samsung S4 mini it seems to be 100% avoided when I do not activate the Android Power saving option. (I have to say I discover no adverse effect on actual power consumption either).

**Comment by martenjj** [comment]
I have seen similar symptoms with losing track logging, maybe in slightly different circumstances.  It usually happens when logging long car trips with continuous high speed stretches (i.e. on motorways).  If I regularly open the OsmAnd app there is no problem, but if I simply leave it in background and don't touch the phone the logging stops randomly - usually, but not always, the last point logged is at a place where GPS reception may have been lost such as under a bridge or toll barrier.  Once this has happened nothing more is logged until a stop for a few minutes where there is good reception, at which point the logging restarts.  I can make log files where this has happened available if necessary.

This has been a problem for probably about six months now, possibly starting with the last but one Play Store release, but appears to have got much worse with the previous 2.6.2 or current 2.6.3.

I have only observed it on one device so far, a Samsung Galaxy S5 with Android 6.0.1.  It does not appear to happen on a Galaxy Tab 5 with 4.4.2 simultaneously logging the same trip.  It also appears to not happen on the Galaxy S5 if I have Ultra GPS Logger active (logging) at the same time.

**Comment by sonora** [comment]
@martenjj  It sounds a lot like the issue I originally reported. And to this very day, I seem to have managed to avoid it 100% ever since I disabled the "Power saving" mode on the Galaxy devices I have tested. do you also find that it only happens when "Power saving" is selected in your Android settings?

**Comment by martenjj** [comment]
@sonora: I'm not using global power saving mode on the device, but with your hint I've looked at the selective app power saving options.  This is where apps that have not been used for 3 days or more are set to automatically save power.  You'd expect that an active app would not be affected by this anyway, but I have explicitly disabled this saving for both Osmand and GPS Status and Toolbox, and will try this out on my next long trip.

**Comment by tazva** [comment]
I don't know if this is similar, but, when using the app in walking mode, it will often just "lose" the GPS, even though it has full signal. It's as if OSM just stops interpreting the GPS data, and shows 0/0. About 30 seconds later, it starts working again. Then after about a minute, it stops. This cycle results in very jittery movement while walking.

Tested on Note 4 Edge.

**Comment by Zefling** [comment]
Same problem for me with a Wiko Fever. Sometimes, it's after 2 hour, sometimes after 5 minutes. Impossible to log all my walking. But I have the same problem with GPX Logger.

**Comment by sonora** [comment]
I believe this to be deprecated, as the implementation has been updated since.
