### ISSUE TITLE
Go to last known position if current position unknown

### ISSUE THREAD

**Issue by DFyson** [osmandapp/Osmand#3557]
I have quite frequently come across the case where I have scrolled somewhere on the map to look at something, turned the screen off, then later turn on the screen and want to immediately go to my current (approximate) location. However the GPS can be slow at acquiring a signal and thus in the meantime get "position unknown". I then find myself scrolling to where I think I am or to the end of my recorded track while waiting for a fix. Thus it would be nice if 'my position' went to the last known position if it is not too old. This is particularly relevant while recording tracks and the last gps fix was 5-10 seconds ago and so likely close to my current (but still unknown) location.

**Comment by DFyson** [comment]
Maybe hold-press on current location position button to make it jump to last known location? I can think of some situations where it may potentially be irritating to jump to last known location.

**Comment by Chumva** [comment]
Probably this was fixed here - https://github.com/osmandapp/Osmand/issues/5068

**Comment by sonora** [comment]
Personally, yes, I would say it was.

In addtion, I had also added an automatic, non-destructive A-GPS download for the case someone taps the Position widget while no GPS fix is available and if the device happens to be online. From feedback I get, this greatly assists finding a faster fix, particularly in cases where you have changed locations by a long distance (e.g. you just get off a plane), or if your device had been turned of for a while.

**Comment by breversa** [comment]
@sonora : where do you get this A-GPS data from ?

**Comment by sonora** [comment]
@breversa It depends on the chipset, usually the api injects at least the time and public almanac data which already helps a lot.

**Comment by breversa** [comment]
@sonora so you actually make a call to inject the data, and rely on the device's hardware to get the data itself ?

Just for the record, Derek Gordon used to provide improved A-GPS data, but not anymore : https://www.derekgordon.com/ntp

**Comment by sonora** [comment]
Yes, the Android implementation+documentation  is somewhat spurious to my taste. :) But from what I see, using the documented A-GPS injection as implemented now makes a noticeable difference in all test devices I have access to.

**Comment by breversa** [comment]
Glad it turned out fine. Thank you ! :-)
