### ISSUE TITLE
NPE while testing new GPX file analysis

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#3563]
Log  attached: [exception.log.txt](https://github.com/osmandapp/Osmand/files/853096/exception.log.txt)

**Comment by crimean** [comment]
@sonora can you explain how to repeat it? was chart visible when you press Details button?

**Comment by sonora** [comment]
Alexey, I think it must be certain GPX files causing this. I have a number of non-OsmAnd generated files or manually altered ("engineered" files for testing things. One is attached here, together with the log it produces (remove the .txt extension before trying). I have this gpx file directly in my tracks folder (not a subfolder) and the crash is after hitting "Details". Beforr that it produces a normal map sna
[_2016-08-11b1nonOsmAnd++_.gpx.txt](https://github.com/osmandapp/Osmand/files/853462/_2016-08-11b1nonOsmAnd._.gpx.txt)
[exception.log.txt](https://github.com/osmandapp/Osmand/files/853464/exception.log.txt)

pshot on the analysis screen.

**Comment by sonora** [comment]
PS: Different story, but maybe you also want to take a brief look at this simple test file of mine: This one does not crash, but the slope curve generated by your new UI seems somehow wrong /incomplete?
[test1.gpx.txt](https://github.com/osmandapp/Osmand/files/853474/test1.gpx.txt)

**Comment by crimean** [comment]
@sonora test1 not a bug since we calculate slope using interpolation

**Comment by sonora** [comment]
Alexey, crash is confirmed fixed, thanks!

Regarding the engineered test1.gpx file: I have not double-checked yet how we interpolate, but doesn't the green slope curve look weird? When I use the slider it shows -1% everywhere except for the last point whete it shows -2%. But the green slope curve reflects a different picture, it only shows values up to the 95m point at all, is missing the scale, and seems far from a constant -1% as indicated by the slider. So something seems not clean or inconsistent here?
