### ISSUE TITLE
OsmAnd messes up the GPS readings 

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#3569]
I ran OsmAnd side by side with Navmii. 
This makes it clear that OsmAnd suffers from two different problems:

**1. OsmAnd fails to sense GPS reading** 

In the following screenshots, OsmAnd shows "Position not yet known" error even when Navmii and Google Maps are already showing the current location.

![screenshot_20170320-073316](https://cloud.githubusercontent.com/assets/9047168/24139000/5b08798c-0e40-11e7-93ac-e7ccdee6f678.png)
![screenshot_20170320-073332](https://cloud.githubusercontent.com/assets/9047168/24139011/61dd361c-0e40-11e7-8ff7-8022426b366a.png)
![screenshot_20170320-073355](https://cloud.githubusercontent.com/assets/9047168/24139027/737be170-0e40-11e7-8d8a-62c3bc7a0334.png)

**2. OsmAnd shows the location with an offset.** 
Both OsmAnd and Navmii use the same OpenStreetMap, but Navmii shows the location correctly.

![screenshot_20170321-140258](https://cloud.githubusercontent.com/assets/9047168/24139028/73a4ddaa-0e40-11e7-8aa8-f44df295e55a.png)
![screenshot_20170321-140326](https://cloud.githubusercontent.com/assets/9047168/24139029/76d0fad6-0e40-11e7-89d0-73c8918bf54c.png)

Note that my actual position is at the checkered flag. OsmAnd shows me at the other side of the road. But Navmii shows me on the correct side of the road (it cannot show off-road positions, so this is the best-possible position).

**Comment by raindropsfromsky** [comment]
The bug#2 is responsible for showing my position on the wrong road (because of which OsmAnd ends up plotting a wrong route for me, which is totally misleading).

**Comment by sonora** [comment]
Looking at your accuracy disk, I am wondering if you have a GPS fix at all? I think you first need to investigate that. If in fact you have none, you need to investigate where the different tools take their position guess from in that case. It could be anywhere from simply extrapolating a last known position along a calculated route to different online location databases involving cell and wifi signals. Also snap-to-roade features come into play here. OsmAnd strictly uses whatevere you configure and allow in the Android location service settings. For an overall analysis I am afraid there is much too little data here about the system and all compared app configurations ..

**Comment by raindropsfromsky** [comment]
Well, that's the point I am making: Despite the large accuracy disk, the other apps get a GPS fix almost instantly.  Also, even if they are interpolating, **their result is damn accurate**!

But OsmAnd not only loses GPS readings, but it also shows the position in wrong place.

And that's why I say that it is worth following the logic followed by the other apps!
*****
And this is not a recent phenomenon: Over the years, I have the same result in three different flagship phones:  Optimus G Pro (LG), OnePlus 2 and OnePlus 3T.

I cannot possibly get a better GPS fix:  Both readings were taken from a balcony, facing open space in front. 
- The first location (facing East) is on 3rd floor (35 ft height), and 
- The second location (facing South) is on 4th floor  (45 ft height),  
No metal frames around to affect the reading. 
The different directions would nullify the influence of GPS satellites (my phone uses GLONASS also).

**Comment by raindropsfromsky** [comment]
Some articles say that both GPS and GLONASS are meant for Northern Hemisphere. But they should be giving pretty decent results in India (specifically in Bangalore), which is 12 degrees north of the equator.

**Comment by raindropsfromsky** [comment]
Sorry I forgot to answer your question if I have the GPS fix. The answer is **yes**.

See the Google Map screenshot: It shows a blue circle if the fix is available, and if not, it shows a gray circle at the last known position. Besides, the position updates continuously in both apps (Google maps and Navmii) and the dot keeps moving a little. Thus it does not seem to be averaging a few readings.

**Comment by sonora** [comment]
Narayan, not sure there is much to go by here in terms of information for any analysis. It would certainly help if you could include the OsmAnd GPS widget on your map screenshots, so we can at least see how many satellites are used. A high number of sats would also indicate that both GPS and Glonass are in use, as it should be.  Then it may be helpful to see a screenshot of a device analytics app like GPS Ststus at the same time. All results of OsmAnd and GPS Status shoul always be 100% in sync at all times,as they both use the same system location service. And if using GPS, I usually see the accuraxy value quickly drop down to 4-6 meters anywhere in the northern hemispbere if you have a view of the opem sky (that is what makes me suspicious in your case). Sat count imcluding Glonsss sjould essily be 15-20+.

Unfortunately I cannot talk for the otjer apps, have little or no info on what they do.

**Comment by raindropsfromsky** [comment]
My phone turns off the GPS when not needed (the notification bar shows a [**point marker** icon](https://cdn1.iconfinder.com/data/icons/mirrored-twins-icon-set-hollow/512/PixelKit_point_marker_icon.png) when GPS is on.)

When I turn on OsmAnd, the satellite count increases from 4/31 to 17/31 gradually (over 3-4 minutes).
The accuracy disk becomes smaller during this period. Indeed, my earlier screenshot may have been taken when the satellite count was low.

But although the disk size changes, the location does not.

**Comment by raindropsfromsky** [comment]
My phone turns off the GPS when not needed (the notification bar shows a [**point marker** icon](https://cdn1.iconfinder.com/data/icons/mirrored-twins-icon-set-hollow/512/PixelKit_point_marker_icon.png) when GPS is on.)

When I turn on OsmAnd, the satellite count increases from 4/31 to 17/31 gradually (over 3-4 minutes).
The accuracy disk becomes smaller during this period. Indeed, my earlier screenshot may have been taken when the satellite count was low.

But although the disk size changes, the location does not.

**Comment by polarbearing** [comment]
Narayan, in your experiments you need to include the "ground truth", that means the location where you physically are, so it can be compared to anythoing shown on the screen. That might be a street corner or similar recognisable reference point. 

> Some articles say that both GPS and GLONASS are meant for Northern Hemisphere.

any source for that statement? this is the first time I hear that, and I have used GPS successfully in Australia and South Africa. Otherwise, where do [these traces](https://www.openstreetmap.org/#map=18/-33.91377/151.16456&layers=G) come from?

**Comment by vshcherb** [comment]
Since it is not clear what's the expected result & how it could be achieved, the issue could not be fixed.

**Comment by sonora** [comment]
@polarbearing I have not done the research, but from what I know, all positioning satellites are in ewuato-symmetric orbits (necessarily so), so I cannot imagine any reason the positioning accuracy should make any systematic difference between hemispheres...
