### ISSUE TITLE
Suggestion: Switch the default map orientation automatically

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#3570]
The default map orientation should be changed automatically, depending on its mode:

1. In **browse** mode, North up orientation should be selected by default.

2. In **Navigation** mode, OsmAnd should switch between **Compass** and **Direction** modes:
    >> As long as the user is stationary, the map should be in "compass" mode. 
    >> when the user starts moving, the map orientation should switch to "in direction of movement".

**Comment by sonora** [comment]
Problem is compass mode is not too reliable:
- Works badly in cars (too much metal around).
- Some devices do not have magnetic sensors: Then you always achieve a 'North is up" effect whenever you stand at a stop light, very weird, I have tried that.
Overall I think not worth the hassle and side effects(?)

**Comment by breversa** [comment]
Why not have the following then :

1. Browse mode : default orientation = north up
2. Navigation in car mode : movement direction if moving, then keep last direction when immobile (typically at a red light)
3. Navigation in bike/pedestrian mode : movement direction if moving, then compass direction when immobile. If device has no compass, either keep last direction, or north up (I haven't put more thought into that).

**Comment by sonora** [comment]
1. and 2. is how we have it, that is our default settings (unless you changed them).

For 3. we have "Compass" all the time by default, I think,. For walking, "direction of motion" may be conceived as weird. But users can easily change.

All in all I think that switching between 2 modes based on whether you are moving or stationary may create strange effects and little benefit. Often, even at rest, some motion is perceived by the GPS unit while a found fix is improved.

**Comment by raindropsfromsky** [comment]
I agree, and in some cases, the location lurches here and there like a
drunk person. Very irritating!
