### ISSUE TITLE
Treat unknown shop=* values like shop=yes

### ISSUE THREAD

**Issue by sommerluk** [osmandapp/Osmand#3573]
Currently, some seldom used shop values like “shop=lightning” do not get an icon on the OSMand map. On the other hand there _is_ an icon for the generic shop value “shop=yes”.

I would suggest to treat all shop values that currently do not get an icon like the generic shop=yes nodes and assign the very same icon to them.

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/ab2510285e45f0693b23bb1a9aaa1d453872a32f

**Comment by sommerluk** [comment]
Thanks!
