### ISSUE TITLE
Announcement for "nearby favourites"

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#3577]
Even if announcement is activated for "nearby favourites" in navigation, it should be OFF if the visibility of favourite group is switched to OFF.
If I remember well, this happened in earlier versions. 
Watched at 2.6.0#20605, Android 5.1.1, Samsung S5 Neo
Peter

**Comment by vshcherb** [comment]
According to the code it doesn't seem to be working in previous versions.

**Comment by pebogufi** [comment]
Until now I could only test it in simulation mode, but there it works fine.
Thank you, Peter
