### ISSUE TITLE
Cars are led onto a horse track....?

### ISSUE THREAD

**Issue by noci2012** [osmandapp/Osmand#3579]
I had seen this before, but could not reproduce what happened. Now i have a clear image of what goes wrong.  While driving a car, the driver is told to go onto a horsetrack. A car cannot ride there, possibly a quad might.  Slightly further on a car driver is told to go left onto a bicycle track. 
a car is allowed on that track for about 500 mtr to get to a small gardens complex.  But definitely cannot go beyond that.

Location NL, Flevoland, Almere, windhoekweg.
The route has been set from schapenmeent onto kemphaanlaan (all streets obviously in Almere, NL)

![screenshot_2017-03-24-00-41-15](https://cloud.githubusercontent.com/assets/1962961/24274905/f66df68a-102b-11e7-85d2-4a91a0086a48.png)

**Comment by utack** [comment]
Wrong tagging on the track:
access=yes

**Comment by xmd5a2** [comment]
access=yes means that all transport types are legally allowed. Wrong tagging.

**Comment by noci2012** [comment]
Ok i can fix that ;-)

**Comment by noci2012** [comment]
Fixed that on openstreetmap.
