### ISSUE TITLE
Analyzing GPX track data per split interval (e.g km-per-km analysis for runners)

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#3583]
In our new GPX track analysis we have currently omitted the previous possibility to analyze the track and performance data per a set split (distance or time) interval. Discussion with some users indicate this could be a significant regression: Runners want to e.g be able to see their running time needed, average speed etc. per each kilometer or mile.

Suggestion to solve this is as follows:

(1) Let's add ALL available numerical data for a track  (even if it is also shown on the more specific tabs) on the GPX Analysis screen's existing first tab "General", rename tab to "Overview". That solves all issues with users who need to see all figures in one condensed fashion like we had it before. (Just copy all number buttons from the other tabs below the existing number buttons)

(2) Re-introduce the split duplication of the tabs for the case when a split interval is selected (i.e. one tab per split interval with vertical scrolling, like we have now for segments already). We had this already in the new interface during development, but dropped it at some point. This fixes the pace display for runners. As all data will be on the overview tab, if that tab becomes splittable again, we have re-instated the prior functionality and avoid any regression here.

**Comment by vshcherb** [comment]
Well (1) and (2) still quite separate, (1) is a good recommendation, (2) is good intention though I don't like implementation. First of all it is hard to scroll cause the graphs are scrollable, second I'm not convinced this will be easy to read & compare. We had an alternative with buttons left/right (next /previous interval) and table ( max/min speed) would be immediately updated with only visible segment part in the Details screen. 

Let's keep that issue for now as is and see how it is going to develop

**Comment by sonora** [comment]
The most frequent use case is to set e.g. split intervslal as 1 kilometer, and then quickly flip through the different kilometers to see your running time each, along with the key characteristics (like if it was uphill or downhill etc.). Thus works far better via scrolling than via tappibg. We may just split- duplicate the figures on the overview tab, not the graphs (keep graph as one piece showing the whole track at the top of the tab, that may work.

Alexey also interim had a useable implementation with splitting *everything* (all tabs including graphs). I had used it, the only issue we had then would be fixed by having the first tab woth ALL figures now: Before we had e.g. avg. speed for each km on the third tab, so when I split a track into say 15 km, I had to also tap 15 times on the thitd tab each to make it visible before doing the comparative scroll. But this would be solved by my suggestion 1, as we basically re-instate what we had and what had worked for a long time before: a splittable Overview tab with all the data.

**Comment by vshcherb** [comment]
@sonora one of the issue of that feature is UX to be honest it was quite hard to use. Do you have any examples of the app that has that information or any kind of prototype. 

One of the most important thing is comparing the pace as you said per each km which was not that easy to do and it was much more information available.

I disagree that we should split on the overview tab cause it is slow and quite unusable. I'm not trying to make everybody's life more difficult but it would be great to find better interface.

Anyway display split interval on the map is not the same setting as display graph & stats per each "kilometer".

**Comment by sonora** [comment]
As the primary experiment I would say go back to our January 31 build. You can use the 21km test track I once sent around and select a 1km split. Then simply scroll down the list of colored numbers. The blue "Time moving" figure is the pace for each, and can easily be viewed/compared on the fly.

I had been using this for years like this, and think it worked ok. I guess the color coding did its share to make this very comprehensive. But even now after we did away with the signature colors I think it should still work like this. O know of no better way, actually. (Not sure sure if doing away with the colors was a smart move, but we could always reintroduce and test.)

I do not understand your remark that displaying "split interval on the map is not the same setting as display graph & stats per each 'kilometer'". Why not? It is exactly equivalent, why add additional complication here?

**Comment by sonora** [comment]
PS: Quite a few trail runners using OsmAnd in this fashion. I would say fixing this should either be a milestone for 2.6.1, or we may have to advise people using this to remain on 2.5.x, which would be a shame.

The easiest quick-fix, also coding-wise, would be we simply treat split intervals, if selected at all, just like we currently treat track segments.

**Comment by vshcherb** [comment]
Many trail runners mobile applications mostly have only graph implementation, our split interval list was emulating the graph but somehow in non-traditional way and as I see the graph is much more interactive & provides same information as split interval.

One moment we had that simple implementation of split interval, we removed it on purpose (basically disconnected from map view) cause the implementation is poor. I guess we will find a better one.

Anyway your use case with color coding won't be fixed especially with today UI with tabs.

**Comment by sonora** [comment]
Yeah, but having NUMERICAL split-interval analysis was a unique selling point of OsmAnd over some other even more specifically athletics-oriented apps. Would be a pity to lose this.

**Comment by vshcherb** [comment]
Recently committed, most of the mentioned features are implemented in a separate screen.
