### ISSUE TITLE
Suppress straight line for GPS trace between different segments

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#3584]
There is a straight line from the end of a previously recorded trace to the start of the currently recording, even if the previous one was from a different route, or even a different day. 
I have observed that only recently (i.e. approx. February nightlies).
There should be some criteria to start a new trace segment (new route, new day, significant time or distance gap), and these segments should not be visually connected.
![20170325-straight_trace](https://cloud.githubusercontent.com/assets/8266355/24326229/46642676-11aa-11e7-93ed-7a9cb3029c1f.png)

**Comment by crimean** [comment]
Could you please provide gpx file(s) which cause such behaviour?

**Comment by vshcherb** [comment]
Not reproducible

**Comment by polarbearing** [comment]
When I retrospectively review the track, it does not have this straight line. 

So the issue is only visible while recording. Will keep observing.
