### ISSUE TITLE
New search: auto-"Find more"

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#3586]
In our new address search (may also be a valid idea for the POI name search), when looking up a rather far away city (with a unique name), I end up with an empty results list, and the desired search result is actually found only after manually tapping the "Find more" button. I guess it is rather clumsy that a user has to select "Find more" for the case nothing has been found yet (and some users may give up at this point). Shouldn't we automatically/programatically proceed with "Find more" if there are zero search hits?

**Comment by sonora** [comment]
PS: Also the "Show on map" button is displayed for the case of zero search results, which is of course useless.

**Comment by sonora** [comment]
PS2: I just notice there is a partial overlapvwith #3189. But I guess particularly for cities, and maybe also for POIs there is well a justification that people may look up where e.g. a city is >500km away (looking for something in another country/continent). And remember: we are here only talking about the odd cases with exactly zero results upon first try. I would not even bother re-introducing terminology like the "search radius" again. Where there are results displayed, a button "Find more" is totally self-explanatory. And while there are zero results, why not automatically keep searching through the entire index?

Often the use case is having mis-typed something, but even that is easily corrected on the fly, just tried it. And if you get tired of it, you can always hit the back key, tried that, too.

**Comment by vshcherb** [comment]
Not clear enough, does find more searches what you need. Could you give a concrete example, say locate the map to Berlin and search Amsterdam or it is a closer distance?

**Comment by sonora** [comment]
One ecample of many: Center the map to e.g. Las Vegas, Nevada, USA, then in address search look for Augsburg, a city in Bavaria, Germany (where the Audi cars are manufactured, that's how we hit on it).

**Comment by vshcherb** [comment]
Yes, that's a known issue in some sense. We don't want to auto enable search to give reasonable search time. Of course I certainly feel that you should not hit 3-4 times to find the city 2-3 should be enough, though auto-enable is a bad practice cause we want to give impression of fast search and unfortunately we can't give that impression when there are lots map downloaded.

**Comment by sonora** [comment]
Cities/towns/village/hamlets are usually the first thing someone searches for, before looking for a street name etc. So it is a rather negative user experience if you need to wait for a long time before this first search finishes, and this is even worse when he result is then "empty". 

I am wondering: Do we have (if not, should we) have a **separate/dedicated** index for these locality names?

My observation is that looking for a locality name in the Legacy search interface is orders of magnitude faster than in the new search interface.

**Comment by vshcherb** [comment]
I think the situation changed a lot since we introduced a special "Address" search. POI search limitation I think makes more sense and Find more is easier to understand.
