### ISSUE TITLE
Add pedestrian priority for sidewalk=left|right|both tags

### ISSUE THREAD

**Issue by PinkDuck** [osmandapp/Osmand#3588]
The routing.xml file currently has pedestrian priority 1.2 for sidewalk=yes tag pair. If this doesn't already apply to sidewalk=left, sidewalk=right, sidewalk=both, then those extra tags should presumably be added explicitly for equal favour when there's safety in using an available pavement.

**Comment by scaidermern** [comment]
Duplicate of 2567?

**Comment by PinkDuck** [comment]
A subset request of, sorry about that, will close.
