### ISSUE TITLE
amenity=library on whole library area rendered as a building

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#3590]
amenity=library on the whole library area (grounds) rendered as a building even without a building tag. That seems incorrect. Amenities are intended to be placed on the whole facility area/campus, not just the building. See and example at https://www.openstreetmap.org/way/406004026 . Notice osm.org renders it correctly as yellow area (similar to school grounds).

The bug only appears starting at some zoom level and continues to higher levels. Before that zoom level, other buildings are shown properly, but this library area is not shown as building (which is correct).

OsmAnd 2.5.4

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/272c5089cceaecdfcc5ed4b87bcf7bb940ef7c2e
