### ISSUE TITLE
permanently filter wikipedia articles/POIs based on user's wished laguages

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#3591]
In the past it was possible to download wikipedia articles only in wanted languages but for the whole world. Today it is only possible to download wikipedia articles in all languages for the wanted country.

In this way user sees a ton of unneeded articles (or wikipedia POIs if the layer is shown) in languages he can't read.

I know the menu offers a filter of wiki POIs only for the language of the UI. But this filter is not used e.g. in the "wikipedia articles around" section.

But many users can read multiple languages.
I propose to add a setting field containing a list of languages the user can read. Then, only wikipedia articles in these languages would be shown to the user in the map.
You already have the list of wikipedia languages in phrases.xml so you just need to show them to the user and he picks from the list. The language codes are behind those languages are then used to filter.

The filtering (hiding of unwanted languages) would be permanent and everywhere in the UI.

There could be a setting of "show all" for users that really want all the articles.

This would restore the past functionality but also keeping the benefit of having smaller per-country wiki files.

**Comment by dfszb** [comment]
I suspect there is also some funny bug in selecting the articles. For instance in Transylvania, Romania, most of the villages have their description article in cebuano (!), a language not used in Europe. Most likely the cebuano article is an automatic translation of the romanian / hungarian languages. Unfortunately, romanian / hungarian language articles are missing. For example, consider willage Mera, in Cluj county, romania.

**Comment by dfszb** [comment]
A new note: this was introduced with the end of march update of wikipedia files. I had an older non-updated device (with older maps, wikipedia files), and it worked well. For the above mentioned Mera willage, it had romanian, hungarian, ukrainian languages - the languages of the inhabitants, I guess. Now it only has cebuano :)

**Comment by aceman444** [comment]
I have observed exactly this problem. A wikipedia article in Cebuano and Swedish language with slightly different name than the article in Czech and other langs. These 2 groups of articles were grouped together 2 different wikidata IDs. But this is a problem in the Wikipedia site, I don't think OsmAnd caused it. For me, both groups of articles are shown in OsmAnd, just on different points and with different names.

**Comment by aceman444** [comment]
But this OsmAnd proposal of mine should actually help fix this problem inside OsmAnd. If you set your wiki languages in OsmAnd to Romanian and Hungarian, only those should be seen. Then it does not matter whether a ton of Cebuano articles exists, they will just not be shown.
Unless the Cebuano articles make articles in Romanian not be recognized and shown in OsmAnd. You seem to say than in your second comment. So that would be a different problem and please register it as New issue. Thanks.

**Comment by crimean** [comment]
Already fixed by https://github.com/osmandapp/Osmand/commit/42c0766f6d641c8a9f7573a3f1710875741a2832
Shows wiki in EN or user language.

**Comment by verdulo** [comment]
About a month ago I fixed some spam-articles in Cebuano (I merged them on Wikidata with proper Polish articles). I'm using the newest OsmAnd nightly with today-updated Wikipedia database and I still see duplicates, for example for [this mountain](https://pl.wikipedia.org/wiki/Ociemny_Wierch).

**Comment by aceman444** [comment]
@crimean Why not user's language first?
