### ISSUE TITLE
support for destination:street during navigation

### ISSUE THREAD

**Issue by james2432** [osmandapp/Osmand#3592]
https://github.com/mapbox/mapping/issues/220

Mapbox has been using destination:ref (which I think you support) and destination:street 
As well as the destination tag for highway exits

Example: 
http://www.openstreetmap.org/#map=19/45.41731/-75.67004

Which will tell you to turn on "5" which isn't really accurate, it's towards highway 5 via Nicolas/Mann Avenue

**Comment by sonora** [comment]
James, this was already discussed somewhere within #2968. Unfortunately it is rather hard to support all subtags of `destination`, together with possible combinations of` forward/backward`, `lang`, etc, and then compile a useful and concise turn instruction. I think the benefit in the navigation instructions is very likely limited, it would lengthen many announcements unnecessarily (and in some cases enormously) ... It is probably a good strategy for us to stick with the potentially shorter portions like locality names and ref, along with the necessary forward/backward and lang support (plus possibly exit numbers in the future). Sorry. :)

**Comment by ToeBee** [comment]
While I am not really a fan of this tag either, this issue may need to be revisited. In addition to the Mapbox team mentioned above, it looks like Telenav has also started using `destination:street`:  
https://lists.openstreetmap.org/pipermail/talk-us/2017-April/017259.html

There are now over 15,000 usages. I discovered this tag due to a [reddit post](https://www.reddit.com/r/openstreetmap/comments/7w91ih/i_need_an_android_navigation_app_osmand_sucks_for/) where a user was complaining that OsmAnd was giving terrible voice guidance on turns despite there being tags that seemed to give it information for guidance. But it was all in the `destination:street` tag.

**Comment by 1ec5** [comment]
> Mapbox has been using destination:ref (which I think you support) and destination:street
> As well as the destination tag for highway exits

Following mapbox/mapping#308, Mapbox’s data team stopped using `destination:street` for most purposes, except for the situations described in [this proposal to repurpose the tag](https://wiki.openstreetmap.org/wiki/User:Minh_Nguyen/destination:street).

**Comment by ToeBee** [comment]
Well never mind then. Time to go retag some things!

**Comment by ToeBee** [comment]
Well someone is still actively using this tag. There are now 32,000 usages. And I'm sitting in a SOTM US session right now where the speaker advocated using it. What about at least using the value in `destination:street` if there is no straight up `destination` tag? This could be done during map file generation so the app wouldn't have to change at all. That would have at least addressed the reddit problem above.

**Comment by 1ec5** [comment]
> Should OsmAnd read the destination= tag first, or the destination:street= tag first? In this particular image, you can say to read the :street tag first, but I can find other examples where the street name is last on the sign, or even in the middle.

Here are [727 examples](http://overpass-turbo.eu/s/D5e) where a place name comes before a street name on the sign. There could be more examples that `destination:street` has made ambiguous. (Besides voice guidance, the order would also matter for sign image generators like [CheckAutopista2](http://k1wiosm.github.io/checkautopista2/) and [Junction City](https://github.com/1ec5/junction-city/).)

**Comment by jfburke3** [comment]
@1ec5 Which is why I remove the destination:street tag every time I find it, and put the relevant information in the destination tag in the proper order.
