### ISSUE TITLE
Re: Incorrect address

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#3593]
Osmand 2.6.0#16852D Lastest offline maps (spain)

This bug is not fixed yet, I can reprodece it.
https://github.com/osmandapp/Osmand/issues/3524

**Comment by vshcherb** [comment]
Let's exchange screenshots, I will send you mine.  Also would be good to know if it is a Madrid map or full Spain.

**Comment by OpenSourceForEver** [comment]
Full Spain map.
![screenshot_2017-03-28-01-48-57](https://cloud.githubusercontent.com/assets/12786225/24382823/2be46f44-1359-11e7-8a86-2ef2d5c03450.png)
![screenshot_2017-03-28-01-49-11](https://cloud.githubusercontent.com/assets/12786225/24382824/2be632ac-1359-11e7-9748-ff4de0acf826.png)

**Comment by OpenSourceForEver** [comment]
Hotel appears with incorrect adress and restaurant appears with correct street name but without number

**Comment by OpenSourceForEver** [comment]
Maybe a easy way to solve this is placing address with other tags between "hostal" and "phone" with street name, number, postcode and city literally copied from OpenStreet
![screenshot_2017-03-28-02-04-48](https://cloud.githubusercontent.com/assets/12786225/24383151/8e6ffc9e-135b-11e7-8eee-b37f915a92cb.png)
Maps

**Comment by xmd5a2** [comment]
Wrong tagging https://www.openstreetmap.org/way/200284044
```
addr:street=Calle Tejera
```
But street is named as "Calle de la Tejera"
