### ISSUE TITLE
Incorrect shoreline in Tasmania

### ISSUE THREAD

**Issue by opottone** [osmandapp/Osmand#3596]
At a higher zoom lever estuary of Derwent river (Hobart, Tasmania, Australia) is incorrectly rendered as land. At a closer zoom level it's the other way around: large areas of land in Tasmania are rendered as water. Seems to only affect Tasmania. Possibly data issue in openstreetmap.

![screenshot_20170328-180242](https://cloud.githubusercontent.com/assets/8319326/24395209/378bd6b4-13e2-11e7-9d26-8c79b6ec3d04.png)
![screenshot_20170328-180251](https://cloud.githubusercontent.com/assets/8319326/24395211/3abccc9e-13e2-11e7-9a99-e18df96b930a.png)

**Comment by vshcherb** [comment]
#2805 is not related issue to this one, this one needs to be checked independently.

**Comment by alexanderdd** [comment]
Can reproduce this on android 4.4.2 osmand+ 2.6.3
Reproduce: Go to 849VRM4Q+XV and zoom out, when the scale shows 1 mile, the backgroud turns blue like in the pics above, also where there is land. Just that one zoom level though.

**Comment by alexanderdd** [comment]
Sorry forgot important info: this happens on the offline map "united states of america california" dated February 28.
I use a samsung galaxy s3 mini.

**Comment by vshcherb** [comment]
![screenshot_20171003-100630](https://user-images.githubusercontent.com/1042025/31115436-9c4c2c6e-a822-11e7-9e84-2f04dae0aa4f.png)
Hobart issue is not reproducible any more.
