### ISSUE TITLE
Broken search after fix for #3494

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#3598]
It seems that searching for some names is broken after fixing #3494

For example, in https://github.com/osmandapp/OsmAnd-tools/blob/master/OsmAndMapCreator/src/net/osmand/data/preparation/address/CommonWords.java we have `via` as a common word.

If I search for `expressa` I can see what I want:
![](https://cloud.githubusercontent.com/assets/982338/24429731/ac949c96-13e9-11e7-8800-78beb70a561d.png)

ie, I can find https://www.openstreetmap.org/way/233783810 or https://www.openstreetmap.org/way/223784472 for example.

But not if I search for `via expressa`:
![](https://cloud.githubusercontent.com/assets/982338/24429738/b69a316a-13e9-11e7-9b57-e36a14fac5d3.png)

I don't know if this make any difference, but for https://www.openstreetmap.org/way/233783810 the term `via expressa` is in its `old_name` and for https://www.openstreetmap.org/way/223784472 it's in its `alt_name`

The map was created today.
osmand is `OsmAndF~ 2.6.0#16868D`

**Comment by vshcherb** [comment]
Known issue, work in progress.

**Comment by vshcherb** [comment]
It is temporarily fixed basically reverted https://github.com/osmandapp/OsmAnd-tools/commit/d66465296b2a69e5aff42598d4770e94494e3fd3. Next month (once release is out) this fix will be back and it will be supported by new versions.
