### ISSUE TITLE
Streamlining all voice-guidance settings

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#3599]
The voice-announcement settings are scattered:

The **Route editor > Settings** path gives three settings: 
1 Sound yes/no (toggle)
2 Voice guidance TTS selection
3 Pause music (toggle)

But other three options are totally separated.
They are available through the **Navigation settings** option (last option in the list):
4 Announce...
5 Repeat navigation instructions 
6 Arrival announcement

Note that only these six options are related to a voice guidance.
All other settings are related to actual navigational behavior.

Therefore, all the six voice-guidance options should be combined in a single screen.

**Comment by vshcherb** [comment]
Merged to #3558, will be fixed soon.
