### ISSUE TITLE
Fire hydrants POI not displayed

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#3600]
Our user reported an issue recently.

Steps: 1. Open the map at 14.592097,121.037796 (the map of Manilla), go to search and select categories.

2. Go to Custom filter - Emergency - Fyre hydrant and press Show on Map.

3. Open the map - no hydrants shown. However, if you zoom closer on the mentioned location, the hydrant icon is there.

![sc1](https://cloud.githubusercontent.com/assets/12711814/24452399/c3e7567a-148b-11e7-8819-21441acd8cfb.jpg)
![sc2](https://cloud.githubusercontent.com/assets/12711814/24452402/c685323a-148b-11e7-83b6-81cfb136faa8.jpg)
Is this a bug?

**Comment by xmd5a2** [comment]
This is because we moved fire hydrants to separate category named "Emergency infrastructure" after 2.6 release. Will be fixed in 2.6 (or you can try nightly builds). Beta release is planned next week.

**Comment by cepesko** [comment]
Fire hydrants:type=underground started cluttering the map as they are tagged in many residential areas now. They are of use mostly only for emergency personnel and they give no orientation as they are underground whereas other emergency infrastructure, e.g. emergency_access_points, defibrillator is rather important for the general user.
At the moment there is no way to filter these undergound hydrants without losing the important emergency stuff. Could these maybe selected and suppressed with the existing feature "hide underground oblects"?
