### ISSUE TITLE
Layers of map info are not always accurate

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#3601]
Sometimes OsmAnd changes the order of the layers on the map. Example:

a footbridge over a highway: it's properly rendered in OpenStreetMap but 
in OsmAnd it seems the highway is on top of the footbridge:
![different layers not properly displayed](https://cloud.githubusercontent.com/assets/12711814/24453068/ff818928-148e-11e7-9875-dfb5371dbcd1.jpg)

(https://www.openstreetmap.org/#map=19/36.78285/31.42309)

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/293c565344c58b08653723a7a49c8d78e489ceaf
