### ISSUE TITLE
Add "Analyze" to the 3-dots menu of each GPX track

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#3603]
Currently you can not find our new GPX analysis textually in any menu, but  only by tapping directly on a track name, which some users may not discover. I guess we should explicitly add "Analyze", leading to the analysis screen for that track, to the "More" menu of each track (between "Show on map" and ""Move"). (Icon could be the circled "i" we use for POI in the Configure map menu, I guess.)

**Comment by vshcherb** [comment]
Nice point

**Comment by sonora** [comment]
@vshcherb  We have now fixed this for "Analyze on map", which was necessary and is great!

But we have not fixed this yet for "Analyze", our other GPX analysis screen (the one showing also the numerical data). Going forward, I am wondering if we really need to keep this "Analyze" screen. I see many users struggling with the concept of our 2 different GPX analysis screens, not know what the difference is or when to use which one (or even how to enter or when they are on which one).

Maybe we can somehow put the numerical track data on a tab on the "Analyze on map" card and thus combine both screens?
