### ISSUE TITLE
Proper reset of the background GPS wakeup interval broken

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#3604]
Reset of the GPS wakeup interval sbroken,after we introduced the new notifications, as follows: (This is a regression, but we decided to defer it past the 2.6 release)

- Start GPX logging via the widget, interval 30 sec. (You can verify this works ok and GPS correctly goes to sleep between measurements by putting OsmAnd in the background and watching the behavior of the Android GPS icon in the notification bar).
- Now start a navigation in Follow mode. -> GPS wakeup will correctly go to continuous, even when the app is in the background
 - Now stop the navigation again: GPS wakeup will remain continuous, instead of correctly going back to 30 sec.

**Comment by sonora** [comment]
@vshcherb I guess the removal of lines 98-108 in NavigationService.java in your commit https://github.com/osmandapp/Osmand/commit/0570e872073acfe020690c763c8fa5bf68ac5a43 may cause this issue?

**Comment by vshcherb** [comment]
Year ago change can't remember.
 Though this issue doesn't look high priority cause of A) workaround B) interruption of follow mode (it is even easier to introduce another bug while fixing this).
Workaround: stop GPX logging & start again.  
If somebody cares about battery he will notice it after navigation stop and proceed to workaround.
