### ISSUE TITLE
OsmAnd crash on MIUI 8

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#3606]
Our user reports continuous crashes on MIUI 8.
Steps:
1. Start Osmand
2. Osmand indicates that you are looking for a map to determine the location. (The map they user already has in its corresponding folder)
3. Here, at this moment Osmand goes out.

The user has also sent the report:
[osmand.txt](https://github.com/osmandapp/Osmand/files/881948/osmand.txt)

**Comment by vshcherb** [comment]
Duplicate

**Comment by Sergey82K** [comment]
The same bug: https://github.com/osmandapp/Osmand/issues/3065
