### ISSUE TITLE
Regression: Make the MyFavorites tab default instead of the MyTracks tab

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#3609]
Let me open this as an issue before it gets lost: https://github.com/osmandapp/Osmand/commit/7f9bc4d5ce8afe9d83d5a7dcdd8bb6af9258c910#commitcomment-21504954

Also the second point I mention there is still worth fixing, That you need to scroll to see all of the numbers. Some users may not find out this is scrollable. I think we can condese all margins a bit.

**Comment by vshcherb** [comment]
For me My Favorites are always default. Though I think in the past it was remembering last selected tab, thing might changed now.

Margins are hard to reduce, I had that request as well.

**Comment by sonora** [comment]
You are right:  After my fresh install it went back to remember the "last used". Maybe I had just overlooked that behavior.

 Margins only matter on small devices, so it may be ok.

I have renamed our first tab from 'General", which conveys no useful information, to "Overview", ok?

Do you have any objection if I copy the 4 numeric buttons each from the Altitude and Speed tabs also to the bottom of this overview tab? I would like to have one place where you can see all data in direct correlation. It would be below the lower screen edge on most devices and not visible without scrolling, so it should not have any adverse effect for anybody?
