### ISSUE TITLE
Display overall information for track (regardless segments)

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#3612]
The overview, graphics and statistics becomes better and better.
Often the tracks are splitted into trkseg due to stops, which reduces a good overview of hiking tour or simular recording.

I would like to have an enhancement:
"merge current tracksegment (trkseg) to previous one".

Regards Peter

**Comment by vshcherb** [comment]
We were planning to display combined graph/data for all segments. I will rename that issue to capture that momemnt.

**Comment by pebogufi** [comment]
Thanks !
Peter

**Comment by vshcherb** [comment]
fixed
