### ISSUE TITLE
Track analysis NPE

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#3614]
I think this one comes up for tracks with speed but no elevation data: 
[exception.log.txt](https://github.com/osmandapp/Osmand/files/888313/exception.log.txt)

**Comment by sonora** [comment]
Alexey, it is not fixed, as the graph is not necessarily empty when this occurs...

I attach the short test track I discovered this with. It still happens with build #21004M.

Thx - Hardy

[test.gpx.txt](https://github.com/osmandapp/Osmand/files/888493/test.gpx.txt)

**Comment by crimean** [comment]
Hardy, thank you for test example, but it is fixed. You need to install build #21005

**Comment by sonora** [comment]
Sorry, I pulled the build too quickly. The next build up (#21005M) works in deed!

**Comment by sonora** [comment]
Yes, just discovered when browsing our builder again! Good work, thanks!
