### ISSUE TITLE
"Rybinskoie vodokhranilischie" at basemap when map language = local names

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#3615]
Some map object names are written are transliterated even when "name" tag exist. Map language = local names, app lang = system.
Zoom 7 here:
https://www.dropbox.com/s/5r7b1f5d5ju3dgv/Screenshot_2017-04-02-20-01-30.png?dl=0
```
Рыбинское водохранилище -3092009 {natural=water, name:it=Bacino di Rybinsk,
 name:pl=Zbiornik Rybiński, name:de=Rybinsker Stausee, name:es=Embalse de Rybinsk,
 name:en=Rybinsk Reservoir, name:fr=Réservoir de Rybinsk, name=Рыбинское водохранилище,
 name:cs=Rybinská přehrada, name:sv=Rybinskreservoaren} ([644.0,314.0 - 804.0,382.0])
  order = 178 visible = true
```
This is annoying and very noticeable when user from central Russia (for example) launches app first time.
OsmAnd shouldn't transliterate cyrillic letters when app language refers to the Cyrillic family of languages.

**Comment by vshcherb** [comment]
There is no name:ru, basemap displays based on system settings and always transliterate names. There are pros & cons to transliterate or not as I see there are more places where we want to transliterate.

**Comment by xmd5a2** [comment]
Added exception for cyrillyc languages.
https://github.com/osmandapp/Osmand/commit/36f4e57f6a5e9c71756df39606b779ed4980a8cd
