### ISSUE TITLE
German Localisation: Wrong Map Name for "Bretagne"

### ISSUE THREAD

**Issue by ksaerdna** [osmandapp/Osmand#3620]
This map can hardly be found in the list because this French (!) region is named with the English (!) word "Brittany".

It must be **"Bretagne"**, i.e. in German we use the original French word.

-> https://en.wikipedia.org/wiki/Brittany
-> https://fr.wikipedia.org/wiki/Bretagne
-> https://de.wikipedia.org/wiki/Bretagne

**Comment by xmd5a2** [comment]
Should be fixed now but these translations are obtained directly from OSM
