### ISSUE TITLE
"Update all" is not showed properly

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#3621]
Osmand 2.6.0#16966D

On download Maps/updates the box where is written "update all" is black and letters are black too. 

![screenshot_2017-04-04-01-23-53](https://cloud.githubusercontent.com/assets/12786225/24636078/eedd715c-18d7-11e7-9db7-8dada4c1af85.png)

**Comment by vshcherb** [comment]
Fixed
