### ISSUE TITLE
During navigation mode, OsmAnd shows two current location markers simultaneously

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#3625]
During navigation mode, when the vehicle comes to a halt, OsmAnd shows two current location markers simultaneously, as show below:

![currentlocationmarker-2](https://cloud.githubusercontent.com/assets/9047168/24691353/973d8562-19f0-11e7-9f70-1058202fa6bd.jpg)

**Desired:** Only one marker should be shown (either the blue circle, or the arrow).

**Comment by vshcherb** [comment]
Fixed
