### ISSUE TITLE
Small new UI glitches with importing and handling Favorites

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#3628]
As follows: Import a `favorites.gpx` file (a "native" one which has previously generated by OsmAnd).

(1) the `<color>` tag (contained in the file for all favorites except those which are in our default color) is not respected.

(2) Instead, all favorites and favorite groups seem to have the same color, our default color `##eecc22`

(3) This default color is not in the list selectable colors colors for favorites, so once you manually change it, you cannot get back (which is a pity because it was a great mixture of noticeable but not annoying, so many users got used to having some or all favs in this color)

**Comment by PavelRatushnyi** [comment]
I have two groups in favourites: default one "Favourites" and custom one. In there groups I changed color to another color, not #eecc22. Then, I copy #favourites.gpx file to another folder and delete groups in OsmAnd. After that I import favourites.gpx file, which was copied to another folder. In OsmAnd I can see that my custom colors are respected. Maybe I do something wrong?

**Comment by vshcherb** [comment]
looks like fixed, not reproducible any more
