### ISSUE TITLE
Usability issue with search in offline mode (no GPS)

### ISSUE THREAD

**Issue by tYYGH** [osmandapp/Osmand#3629]
_What version of OsmAnd are you using, on what device and Android/iOS version?_
* Fairphone 2 (Qualcomm MSM8974PRO-AA) / Android 5.1 open-source build with security updates from 2017-03-05 / kernel 3.4.0
* OsmAnd~ 2.5.4 from F-Droid + OsmAnd Contour lines 1.0 from F-Droid
* BRouter 1.4 from F-Droid

_Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?_
Offline maps from within OsmAnd.

_Problem description_
The new one-line “intelligent search” is unusable when offline. When I have an address, say “18 rue Gustave Eiffel, Sainte-Luce sur Loire”, there is *no way* I can find such an address with this search ; I tried.

My phone has its GPS off most of the time to save battery, and getting the GPS to work inside an apartment or an office can not always be done anyway.

Ever since the “traditional search” disappeared, I am unable to perform searches, so I zoom the map to the approximate location, and search with my eyes, after having looked for the approximate location on the computer beforehand!

This is what I was using before:
http://osmand.net/features?id=find-something-on-map#traditional_search
It worked well.

The new search presents only irrelevant results, most of them hundreds of kilometres away from where I am, and it is slow at that… Besides, I don’t get the logic of the sorting order (it seems to be related to distance, but given that I don’t know what origin is considered, I’m not sure).

**Comment by njohnston** [comment]
You can access the old address search by enabling the development plugin (Plugins -> "OsmAnd development") and then selecting "Legacy search" from the main menu.

There has been lots of discussion about quick search (see #3261). Developers are working on a new, improved address search which will be included in OsmAnd 2.6.x (hopefully coming soon!).

**Comment by utack** [comment]
@tYYGH not directly related,  but the BRouter website has much newer versions, if you trust the authors officilal builds over F-Droid  
http://brouter.de/brouter/revisions.html

**Comment by vshcherb** [comment]
2.6 supports "18 rue Gustave Eiffel, Sainte-Luce sur Loire" search.

**Comment by tYYGH** [comment]
Thanks for the links and tips. It helped me a lot, including understanding how the smart search should actually be used!
