### ISSUE TITLE
ClassCastException on manual url for oline-tiles

### ISSUE THREAD

**Issue by emdete** [osmandapp/Osmand#3632]
when i entered an individual url for (online-)tiles usage i rendered Osmand unusable. logcat shows this exception (which is stored in `/sdcard/Android/data/net.osmand.plus/files/exception.log` as well):
```
Version  OsmAnd~ 2.5.4
05.04.2017 3:42:18
Apk Version : 2.5.4 254
Exception occured in thread Thread[pool-1-thread-7,5,main] : 
java.lang.ClassCastException: sun.net.www.protocol.ftp.FtpURLConnection cannot be cast to java.net.HttpURLConnection
	at net.osmand.osm.io.NetworkUtils.getHttpURLConnection(NetworkUtils.java:173)
	at net.osmand.osm.io.NetworkUtils.getHttpURLConnection(NetworkUtils.java:166)
	at net.osmand.map.MapTileDownloader$DownloadMapWorker.run(MapTileDownloader.java:265)
```

i admit, the url was a bad one (i used file:// to access tiles already downloaded to my phone). anyway, osmand did not like that, even worse: it can't even start anymore to fix that file:-url. 

thank you for providing osmand!

**Comment by vshcherb** [comment]
Sounds pretty bad, can you try to fix it on the file system?

**Comment by vshcherb** [comment]
Fixed by https://github.com/osmandapp/Osmand/commit/6079fbfd1ec77e5e0e530f15ed4a9002877ae738

**Comment by emdete** [comment]
i had to deinstall & install osmand :( i did not figure out where android stores preferences (is it possible to wipe preferences of an app over adb/shell or the like?)
