### ISSUE TITLE
New position arrow is ugly

### ISSUE THREAD

**Issue by verdulo** [osmandapp/Osmand#3633]
The new position arrow is too big and occupies too much of the screen space. Maybe the new size is good when you're driving a car (it's more visible) but it unnecessary clutters the screen when you're pedestrian. I suggest to add option to restore the previous arrow, or show bigger arrow in car/bicycle modes and smaller in pedestrian/explore map, or scale the arrow according to the setting "Map magnifier".

**Comment by vshcherb** [comment]
Please provide a screenshot to be sure we understand what's a reference.

**Comment by verdulo** [comment]
In the old style the arrow is reasonably small:
![screenshot_20170406-223656](https://cloud.githubusercontent.com/assets/16842967/24774705/3c8dd164-1b1a-11e7-8034-af631c3084fe.png)

In the new style the arrow looks too big:
![screenshot_20170406-223709](https://cloud.githubusercontent.com/assets/16842967/24774714/4527620e-1b1a-11e7-99d3-a394b19ac30b.png)

**Comment by dmpr0** [comment]
Hi, thank you for feedback, i fixed size bug, please check new nightly build.
