### ISSUE TITLE
Quick Action - Toggle OSM notes

### ISSUE THREAD

**Issue by rbovard** [osmandapp/Osmand#3635]
Thanks for the Quick Action, it's really powerful.

Just a feature request, is it possible to add an action to toggle OSM notes?

**Comment by rbovard** [comment]
Thanks a lot @crimean, that was quick!

**Comment by rbovard** [comment]
I just took a look and it work great.

@crimean Max I suggest you to put the entry menu just after Toggle POI in the second part of quick actions items?

**Comment by crimean** [comment]
Fixed by https://github.com/osmandapp/Osmand/commit/bba6beb1c1359d44cdc1253dbc99ddcba2de498c

**Comment by aceman444** [comment]
It seems to me the quick action does not work right (in 2.6.2). It does not toggle anything, at least not the green circles create with "add OSM note" action or the "open OSM note" menuitem. Can you please check it? Is it supposed to toggle something else, also called OSM notes (e.g. the online ones)?

**Comment by rbovard** [comment]
> Is it supposed to toggle something else, also called OSM notes (e.g. the online ones)?

Yes, that's it.

**Comment by aceman444** [comment]
Then it should be somehow made known, as there wording looks like the offline OSM notes (user made, not yet uploaded).

You will notice in the map settings menu, that there are 2 types, a "Notes layers" and "OSM notes (online)".

Maybe the toggle should toggle both types?

**Comment by rbovard** [comment]
It's the reason why that it's called "OSM notes" (for the online ones).

After that, I'm not sure that's a good idea to toggle both: because for a mapper the OSM notes are the online ones.

**Comment by aceman444** [comment]
I see. I was also a bit wrong. The "notes layer" in map configuration only toggles the audio/video/photo notes, not the offline OSM notes. So I wonder how to hide the offline OSM notes temporarily. But that is then a different issue.
