### ISSUE TITLE
Land disapears when zooming above 10 - Tasmania

### ISSUE THREAD

**Issue by skualos** [osmandapp/Osmand#3640]
Land disappears when zooming above level 10, in Launceston (-41.440013,147.129923) and all of Tasmania from what I've seen.

**Comment by sonora** [comment]
Cannot spot anything odd there ... screenshots demonstrating this would certainly help, as well as knowing which maps are using? Do you have the "World Oerview map" loaded? It produces he **global** map everywhere for zoom levels >=11, hence should be present on all devices.

**Comment by skualos** [comment]
I have the "World overview map" and the "Australia - Tasmania Standard map" loaded.
I think the issue is in the the Tasmania map, as at zoom levels 10 and lower the map looks correct
![screenshot_20170409-173852](https://cloud.githubusercontent.com/assets/6606412/24836296/dd97de5e-1d5b-11e7-871a-d2d2f73461ce.png)
![screenshot_20170409-173901](https://cloud.githubusercontent.com/assets/6606412/24836298/e744da10-1d5b-11e7-84fb-b6cfdeda4cad.png)

**Comment by sonora** [comment]
Now I see what you mean, thanks. It is actually a known issue and we have quite a few example locations for this. I am not currently sure what our status is on this, hence leave this issue open for Victor to review.

**Comment by vshcherb** [comment]
@sonora It is not a known issue actually, if you convert it manually the map is correct. Something happened in our batch process on the server. 
All coastlines problems are difficult to investigate and they are not very consistent but this one is very consistent across all zooms and areas. So it is unique problem I would say and it is not reproducible if you convert the map manually.

**Comment by skualos** [comment]
let me know if i can help in any way

**Comment by sonora** [comment]
Victor, ok, had not researched to depth at all. At first sight this seemed like many of the "flood" issues we see at singular zoom levels near Carrribean islands, South Florida, and bay cities with complex topology. If it helps, I can provide a few locations (have not found an open issue about it, actually). Most depend rather sensitively on where the map is centered at, so yes maybe this one is different

**Comment by vshcherb** [comment]
With new maps the issue seems to be solved
