### ISSUE TITLE
Icons of avoided roads are vanishing sporadically (needs app restart)

### ISSUE THREAD

**Issue by Rolf558** [osmandapp/Osmand#3644]
Icons of avoided roads are vanishing sporadically from the map. A restart of the OsmAnd app is required to have them displayed again.

Found with OsmAnd+ 2.6.2.

**Comment by Norbert80** [comment]
()

**Comment by vshcherb** [comment]
Very strange... I can't reproduce it, may be there are special actions to make them disappear.

**Comment by Norbert80** [comment]
At the moment I can't provide defined steps to reproduce the bug.

**Comment by beatnickgr** [comment]
They vanish when
1) i zoom the map with 2 fingers (workaround +/- button)
2) i scroll the map (workaround restart the app)
I have around 10~20 avoided roads. This does issue reproduces very sporadically.

**Comment by beatnickgr** [comment]
I cannot delete the "avoided roads" because icons disappear when i touch them.

**Comment by Norbert80** [comment]
Still reproducible with OsmAnd+ 3.1.5.
