### ISSUE TITLE
Small islands disappear at zoom 13 on shipping map

### ISSUE THREAD

**Issue by bjohas** [osmandapp/Osmand#3648]
Small islands are visibile at zoom 13-15 on "world map", and are visible at zoom 15 on "shipping map", but not visible at zoom 13 on "shipping  map", see e.g.coast near Ibiza city.

Shouldn't those small features be visible especially on the shipping map? Or is there a particular reason why they are hidden in the shipping map (but not the world map)? Normally a shipping map would have ​rocks etc. marked.

Thanks!

**Comment by xmd5a2** [comment]
Yes, this really makes a sense. Originally this was done for performance reasons but nautical rendering style do not render excessive number of details so it is not an issue.
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/3318bc9ed8de3274dff0bfc2b51ef8c1a4883ec0

**Comment by bjohas** [comment]
Thanks, that's great!
