### ISSUE TITLE
Wrong subway line coloring in Madrid, Spain

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#3650]
There are 2 lines with similar colors in Madrid: one is light-blue and one is dark-blue. However, OsmAnd shows them both the same.

![madrid](https://cloud.githubusercontent.com/assets/12711814/24961054/485eb5d2-1fa0-11e7-8f35-274f558e91bd.png)
![rsz_madrid_s](https://cloud.githubusercontent.com/assets/12711814/24961033/37a8195e-1fa0-11e7-9712-6ce0c682b069.jpg)

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-tools/commit/e91871c6044da44869a9d8d613006296879f8816
But there can be other rendered colour errors because we in OsmAnd use colour simplification.
