### ISSUE TITLE
Wrong map names coloring in Manage map files - Local

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#3652]
Red colour seems to be random. If user scrolls up and down list several times then all map names becomes red.
https://www.dropbox.com/s/v2us3zwlpm8f874/Screenshot_2017-04-12-17-56-40.png?dl=0

**Comment by AlexSyt** [comment]
https://github.com/osmandapp/Osmand/commit/d9589f286ddabdb063d1fe5000bcba31067887d2
