### ISSUE TITLE
Crash on Xiaomi Redmi 3

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#3653]
Every time user chooses the start point of an exemplary direction, OsmAnd crashes.

Device : ido 
Brand : Xiaomi 
Model : Redmi 3 
Product : ido 
Build : LMY47V 
Version : 5.1.1 
App Version : OsmAndF~ 
Apk Version : 2.6.0#16902D 240
[exception.txt](https://github.com/osmandapp/Osmand/files/919830/exception.txt)

**Comment by vshcherb** [comment]
Fixed
