### ISSUE TITLE
Re: Incorrect address 

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#3654]
This issue is not fixed yet. https://github.com/osmandapp/Osmand/issues/3593

Wrong tagging is fixed but with OSM Live (last map change: 12/04/2017 23:00) the bug is not fixed yet.

**Comment by vshcherb** [comment]
OSM Live doesn't support address section updates, so you need to update to April maps.

**Comment by OpenSourceForEver** [comment]
ok. Thank you
