### ISSUE TITLE
OsmAnd DPI bug on Android 7.x

### ISSUE THREAD

**Issue by valynor** [osmandapp/OsmAnd#3655]
As reported before in https://github.com/osmandapp/Osmand/issues/3255 :

Android 7.x Nougat has a new option in **settings > display > display size** for resizing all Android UI elements, which I set from _standard_ to _small_.

All UI elements in OsmAnd are now much _larger_ than usual (buttons, widgets, scale, even the menus).
With the setting set to _small_ they should be smaller or at least unchanged.

It looks like this: https://i.imgur.com/Fkhe7WJ.jpg (picture from user BOHverkill)

I'm running Osmand+ 2.6.2 on a Nexus 6P with stock Android Nougat 7.1.2 and today's update did not fix this bug.

**Comment by vshcherb** [comment]
The screen should be different cause there were some fixes in that area. As I understand correctly with  settings > display > display size (standard) everything works ok.

**Comment by valynor** [comment]
That's correct, display size "standard" works normally. 
Unfortunately the fixes didn't do anything for display size "small", OsmAnd 2.6.2 looks exactly the same as before (much larger icons, text etc.). 

I don't really _want_ the OsmAnd UI to be any _smaller_ than it is with the "standard"setting, maybe you can add code so that the app simply ignores the new Android UI DPI setting completely? 

Setting display size to "standard" isn't really an option either because the Android 7 UI wastes a lot of display space this way.

**Comment by casta** [comment]
I juste realised (thank's to othrer applications that change display too), that you get those big controls when Android switch to tablet mode.
This occurs as soon as the screen reaches 480 dpi.
And I agree that with quite big phone screens (mine is 5.5"), the osmand tablet mode is kind of annoying ;)

**Comment by valynor** [comment]
The bug I reported above is still present in the latest Osmand+ stable on Oreo 8.1.0
It would be really nice if you could look at this again. While it's not breaking Osmand functionality all the too-large UI elements are quite annoying as they waste precious space on the screen.

**Comment by alyonapinchuk** [comment]
The issue is still relevant in the latest OsmAnd release.
display size set to default
![image](https://user-images.githubusercontent.com/40493090/56866064-f6c05700-69dd-11e9-811c-dc8c173e0c25.png)
display size set to small
![image](https://user-images.githubusercontent.com/40493090/56866072-0a6bbd80-69de-11e9-88f5-e61ee5be96d3.png)

**Comment by disk0x** [comment]
Persists in Android 10 / Lineage 17.1

**Comment by Yarjk32** [comment]
I haven't this problem on Android 10, but after updating to Android 11 this problem occured.

Demonstration:

https://user-images.githubusercontent.com/65510612/132345751-4d701c27-6b3c-4d5b-a8ba-bb818d252359.mp4

OsmAnd Version: 4.0.7
Android version: 11
Device model: Motorola Moto G9 Plus

**Comment by guidot** [comment]
Still valid.
OsmAnd Version: 4.7 17
Android version: 14
Device model: Realme XT

My work around was to set dpi to 470.

**Comment by dmpr0** [comment]
* https://github.com/osmandapp/OsmAnd-Issues/issues/2552
* https://github.com/osmandapp/OsmAnd-Issues/issues/2437

**Comment by vshcherb** [comment]
Already planned 4.9 https://github.com/osmandapp/OsmAnd/issues/18357
