### ISSUE TITLE
selecting brouter navigation service

### ISSUE THREAD

**Issue by tobydickenson** [osmandapp/Osmand#3658]
The user interface for selecting a navigation service only lists brouter if the relevant app is installed. Osmand seems to be caching the result of this check, which is inconvenient in the common case where "install brouter" action immediately precedes the "select brouter in osmand" action. 

Today I observed the following sequence:

1. install brouter
2. open osmand (it was probably already running at this point)
3. open navigation settings; select navigation service
4. brouter IS NOT listed
5. close and reopen osmand
6. open navigation settings; select navigation service
7. brouter IS listed

**Comment by vshcherb** [comment]
Not going to be fixed, it is assumed OsmAnd needs to be restarted.
