### ISSUE TITLE
Local names not showing

### ISSUE THREAD

**Issue by jamesbankhead** [osmandapp/Osmand#3661]
I have noticed that in the most recent versions, place names are showing in English even though I have selected Local names in Map preferred language, e.g. Vienna shows as Vienna, not Wien, and diacritics are missing from letters, so French é è and ê all show as e. In earlier versions there was no problem.  Could anyone please tell me how to get version 2.5.4 to show local names?

**Comment by vshcherb** [comment]
The most recent version 2.6. You can configure language in Configure Map screen. Also world map uses your system language in case your system language is english it would use english names.

**Comment by jamesbankhead** [comment]
Yes, it is working. Thanks.  If I zoom in to country level, local names are showing.

**Comment by kreuzschnabel** [comment]
This issue disturbs me, too. When I want the map to show local names, I want them in zoom level 11 and below as well as above. Might be necessary for orientation.
