### ISSUE TITLE
Cycle node network nodes should be visible in higher zoom levels

### ISSUE THREAD

**Issue by tko** [osmandapp/Osmand#3664]
When planning / navigating via cycle network nodes it's very useful to see the nodes in higher zoom levels so one can plan ahead for longer distances. However OsmAnd only shows the nodes when zoomed in fairly close and planning ahead requires quite a bit of panning and zooming.

IMO the nodes should be visible at least two-three zoom levels more as in OpenStreetMap.

Location: http://www.openstreetmap.org/#map=14/52.3357/4.6127&layers=C

OsmAnd (zooming in once would show the nodes):
![OsmAnd](https://image.ibb.co/fJqCO5/Screenshot_20170416_110121.png)
OpenStreetMap:
![openstreetmap](https://preview.ibb.co/fZ2Ri5/Screen_Shot_2017_04_16_at_11_02_52.png)

OsmAnd+ 2.6.2

Maps:
* The Netherlands, 2017-04-01
* CycleMap online map
* "Show cycle routes" enabled in Routes configuration

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/d415a533cb41638dff28282723906b24e7c10ed0
Zooms 11-13 will be available after next map generation. 
![screenshot from 2017-04-18 20-40-15](https://cloud.githubusercontent.com/assets/5829014/25145333/9305172e-2479-11e7-836d-ec64a199fd84.png)
![screenshot from 2017-04-18 20-51-17](https://cloud.githubusercontent.com/assets/5829014/25145338/99643a0a-2479-11e7-8f79-148289a7cbc3.png)
