### ISSUE TITLE
Missing detection of the turn right on turn:lanes

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#3665]
the other examples are fixed.
the example from **sonora** is not fixed.

OsmAnd have some problem with turn:lanes:**backward**=left|**through;right** when the intersection after the turn lane not have a 90° angle.
[Example 1](http://www.openstreetmap.org/way/122528751)
![wrong 1](http://www.fotos-hochladen.net/uploads/screenshot2017m93ab2n6gf.png)
[example 2](https://www.openstreetmap.org/way/108496885)
![wrong 2](http://img5.fotos-hochladen.net/uploads/screenshot20175i3pbhcyw9.png)

On a intersection with turn:lanes:backward=left|through;right and a 90° angle, OsmAnd is able to detect correct turn.
[Example 1](https://www.openstreetmap.org/way/442940679)
![correct 1](http://img5.fotos-hochladen.net/uploads/screenshot20176xp2ir58h0.png)

**Comment by vshcherb** [comment]
Issue #3357

**Comment by hakuchi** [comment]
thx for pushing this into a new issue
