### ISSUE TITLE
consistency of highway=footway and highway=path in pedestrian mode

### ISSUE THREAD

**Issue by tobydickenson** [osmandapp/Osmand#3666]
When hiking, highway=footway and highway=path are equally good places to walk. When Osmand is set to pedestrian mode, it makes sense to render both types of way at the same zoom levels. But right now I see:

Zoom|path|footway
----|----|-------
16 | fine dashed | coarse dashed 
15 | fine dashed | solid line 
14 X | fine dashed | nothing X
13 | nothing | nothing

And with Extra Detail turned on:

Zoom|path|footway
----|----|-------
16 | fine dashed | coarse dashed 
15 | fine dashed | coarse dashed 
14 | fine dashed | solid line
13 X | solid line | nothing X
12 X | solid line | nothing X
11 | nothing | nothing

The zoom levels marked X are problematic because, at least for UK mapping, there are footpath networks which contain a mix of highway=footway and highway=path. These get rendered with unexpected gaps.

Here we see the footpath network through Shawford Down at zoom level 15:

http://www.openstreetmap.org/#map=16/51.0208/-1.3304

![screenshot_20170416-124957](https://cloud.githubusercontent.com/assets/292492/25070996/0b84d716-22a4-11e7-950c-eda2a3ae08af.png)

But at zoom level 14 the main path is missing:

![screenshot_20170416-125007](https://cloud.githubusercontent.com/assets/292492/25070997/14412a44-22a4-11e7-927e-3aca64c32cfb.png)

**Comment by tobydickenson** [comment]
The attached patch changes **pedestrian mode** rendering only, adding footway rendering to the cells marked X in the table above

[default.render.diff.txt](https://github.com/osmandapp/Osmand/files/924248/default.render.diff.txt)

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/4139d11fdfe699171a1c1b28535323b036514006
