### ISSUE TITLE
Waypoints are ignored during routing along a gpx 

### ISSUE THREAD

**Issue by therob84** [osmandapp/Osmand#3667]
If I start routing and do use a prior imported gpx (in my case from outdooractive.com) any additional waypoints which are not on track with the route are simply ignored. The route just follows the gpx-track and doesn't care about any waypoint.

Is this a bug or intended behaviour?

The option "calculate route from/to start/ending point" is activated.

Affected OSMAnd Version: 2.5.4

Cheers, Robert

**Comment by vshcherb** [comment]
It is intended behavior
