### ISSUE TITLE
 [Feature Request] Add possibility to place "own position" marker at bottom of screen

### ISSUE THREAD

**Issue by therob84** [osmandapp/Osmand#3668]
I would like to have an option (or as default) where the marker for my own position rests in the bottem part of the screen instead of in the middle to have a better overview of the still coming part of the map/route if compass orientation of "direction of movement" is chosen..

I noticed that this is already standard behavior for "cycling" mode without routing and compass to "direction of movement", but as soon as routing is started it switches back to "centered".

Cheers, [Ronert](url)

**Comment by sonora** [comment]
This is autonatically chosen whenever you have map orientation set to "direction of motion", which again is profile-dependent. If you do not see this in navigation mode, you are using a map profile for the navigation which uses compass or north is up orientation. Just change this by tapping the orientation button.

**Comment by therob84** [comment]
Your statement is true - but ONLY for the normal "map view" mode. 

But once you enter the "navigation" mode by defining a destination and starting route calculation the "own marker" is positioned back to the middle for all profiles and also for "movement" orientation - which my FeatureRequest/BugReport was all about and whose realization will help to have the behavior consistent throughout the different modes.

Can anybody confirm this behaviour?

I have it with v 2.5.4


Am 22. April 2017 00:32:04 MESZ, schrieb Hardy <notifications@github.com>:
>This is autonatically chosen whenever you have map orientation set to
>"direction of motion", which again is profile-dependent. If you do not
>see this in navigation mode, you are using a map profile for the
>navigation which uses compass or north is up orientation. Just change
>this by tapping the orientation button.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/osmandapp/Osmand/issues/3668#issuecomment-296320333

-- 
Diese Nachricht wurde von meinem Fairphone mit K-9 Mail gesendet.

**Comment by sonora** [comment]
I have tried to reproduce it and can actually not. For me it works regardless of whether there is a no route (just map viewing), a route calculated, or I am following a route in navigation mode.

So we have to investigate this closer, it must somehow depend on your app use history or installation history.  Maybe it goes away with installing 2.6.x. And I wonder if the following fixes it for you: While in the map profile where it fails (I guess bicycle in your case), go to "Settings / Configure screen", and tap the little "refresh" type icon near the top right corner of the screen. This resets your widgets for this profile to our installation defaults (you can re-adjust again afterwards as needed), and also resets the related internal settings to their default. Does this fix it?
