### ISSUE TITLE
Bring back sleep mode/keep GPS on option

### ISSUE THREAD

**Issue by rdoeffinger** [osmandapp/Osmand#3669]
Only now realized, pressing the satellite count sends you to a GPS info app instead of allowing to enable background GPS.
Unfortunately that makes the app unusable on my older phone (Galaxy S2) without internet connection that takes 1 - 20 minutes each time to get a GPS lock (Osmand is used purely as a map/"manual" navigation, not for routing etc).
A (not ideal) solution would be to add back the old dialog on long press, or as an option for the dialog that asks which GPS info app to use.
In a quick search for other apps to provide this functionality I found none that are either OpenSource or at least don't have questionable permissions, besides that being more inconvenient.

**Comment by sonora** [comment]
It is not needed on most devices, so we want to avoid turning on background services not linked to user-controlled tasks. I think the obvious solution for you is to simply start such a task like turn on GPX recording (with an intrrval of 15sec or les) whenever you need this?

**Comment by Zahnstocher** [comment]
I think it was a bad decision to remove this feature.
It is a waste of resources and not very intuitive to enable GPX recording (and it has some other drawbacks), just to keep the GPS on.
I used this feature very often, especially while hiking in the mountains, without routing and without mobile reception.

**Comment by sonora** [comment]
Actually, from my experience, even with test devices 5+ years old, when you are **outdoors in the mountains** and your device takes "1 - 20 minutes" to obtain a GPS fix, you have a significat  hardware issue?

**Comment by sonora** [comment]
I just found that there are specific apps to keep GPS on (for the few devices which may really require it) like "GPS Keeper Lite / Keep GPS Fix" at https://play.google.com/store/apps/details?id=com.webmajstr.gpson, so I guess we can close this issue?

**Comment by rdoeffinger** [comment]
I thought bringing it back would be a rather simple and straight-forward solution, e.g. as a long-press action (though I am not convinced that a long list of weird apps most users will have no clue about is a great usability feature that needs that easy to reach, and I can make a list of reason why I think the track recording work-around is a bad idea).
As I mentioned I found the app you quote, but it falls into the "isn't OpenSource, has ads and requires weird permissions (modify settings)".
There is also the other issue that it doesn't help people who are in a foreign country without internet and can't install it, and a lot of people won't have it installed just in case, as they probably aren't even aware of the issue. After all even you seem to be completely misinformed about how GPS works and wouldn't be prepared for it either.

So if you want to fix this "properly" instead, let me cut this down into 2 issues I think this feature was needed for:

- Even with a modern device, if it is switched off, moved for a long distance and then used without internet connection it is completely normal for a fix to take about 20 minutes BY DESIGN, as it needs to get constellation updates from the GPS signal. That is a typical thing someone travelling on holiday would encounter. As someone who in the past tried to "solve" this by manually keeping the phone screen on for 20 minutes, it just doesn't work. The problem is more significant with devices like the S2. Even if it's only 5 minutes it would be problematic, but in a city it is likely to be longer than that no matter the device used.
- With older devices, even after you had a GPS fix it can take a good 10-20 seconds to re-acquire it, which is at least inconvenient.
- Your testing might have been flawed if you had the Google location service enabled, that isn't an option everyone is willing to use (I just don't like having my location reported to Google regularly, so I'd never enable it on my main device).

Now one solution that I think would be user-friendly if possible to implement would be:
- Once the app was started, keep GPS on until you get the first GPS fix on, with maybe a safety timeout of maybe 30 minutes
- (possibly as a configuration option), keep GPS on as long as the app is in the foreground, even if the screen is off
If using a configuration option, it probably would be nice to have it called something like "keep GPS on" with the values "never/only if track recording", "until first fix", "while app in foreground even if screen off", "always", with "until first fix" as suggested default.
If that seems too risky for battery use, "until first fix while app is in foreground and only screen is off" seems a fairly risk-free option to me.

**Comment by enomat** [comment]
@sonora @vshcherb

Same here. Removing features is the worst habit of today's developers. Why do you want to make the app worse on purpose?

If you don't want to restore the original behaviour (pressing the satellite count), at least you should add an option in the developer settings to enable background service and sleep mode and to change GPS wake up interval.

**Comment by rdoeffinger** [comment]
Just pre-emptively: Please keep it constructive and flame-free. We all want Osmand to be better, even if in cases like these we might have strong feelings on the how (and personally I have to admit that I think the developers did a great job on usability so far, so I have to take their opinion on that seriously even if being slow to close tickets in my experience works better for avoiding conflict).

**Comment by sonora** [comment]
Again, I really do not see the use case. I try this very often really: When I get off a 12 hour flight, even devices as old as the Samsung S4 mini or the old Galaxy tab 3.7.0  (both Android 4.4.2, both supporting GPS and GLONASS only) take definitely less than one minute, more like 30 seconds actually, to obtain a GPS fix some 9000 km away from their last fix (device in airplane mode, and location detection is strictly set to GPS only).

Please understand that simply being able to wake-lock a system service not connected to any concrete OsmAnd user functionality like logging or navigating, caused some user's devices to drain the battery completely for no obvious reason they understood, and we received a lot of support cases, and unjustified feedback of being a battery hawk.

We are trying to be simply "functionality driven" here. The ability to manipulate the background service was actually never meant as a "feature" per se, it was an attempt to separately control the GPS behavior while GPX logging was on, something we now automated because it was little understood. So if you need OsmAnd to track your position even while your device is asleep, your workaround is plain and simple to turn on logging while you need it.  :)

Additional settings like "Keep GPS on while the app is in the foreground but the screen is off" or "Keep GPS on for the next 30 minutes" are exactly the kind of UI cluttering we want to avoid.

**Comment by enomat** [comment]
@sonora 
I understand your points. But that's why this option should be added in the developer settings (OsmAnd development plugin), so only the users (advanced users) who explicitly want to control the GPS behavior would use it, not the users who don't understand it. The option doesn't have to be as complicated and cluttering as @rdoeffinger requested. Simply it should be the same as it was before (enable background service and set wake lock interval), but moved to the developer settings. There is no need for anything more.

OsmAnd is the best, most customizable navigation app. It should offer this customizability for users who need it.

**Comment by sonora** [comment]
"Most customizable" and "best" in many people's eyes contradict each other, we have had to learn. :)  There seems a clear tendency towards "Do not bother me with settings, simply automate what you know works in most cases."

I can see your point that we could (and often do) accumulate stuff like this under "Development settings", but even that should not become a trashcan of things over time, I guess, in particular if there is an such an easy workaround like I said.

In any case, I will leave it at this for others to offer there opinion. From what I remember, this change came also about with a noticeable simplification in our code, so I am really hesitant to advocate putting this back in...

**Comment by rdoeffinger** [comment]
I could add a lot of arguments (for example the gpx track workaround would work much better if there was a "discard recorded data" action, instead of just "stop recording" and "save track"...) but I might just be wasting everyone's time, so I'd rather ask: what might be the best way to convince to add back a solution?
One idea I had would be to connect it to the button to show the current location.
Currently it just shows a "position not yet known" toast. It could instead e.g. show a "popup" (the kind you get when marking a position for example), saying something like "position not yet known, searching", including a "cancel" action.
As long as that one is shown, it would then keep GPS active even in the background.
That at least would solve the "getting initial fix" issue, is directly connected to user actions and I don't think will result in unexpected battery drain.

**Comment by sonora** [comment]
Another way to achieve what you want: Use GPS Status. (You can even link to open it from our GPS widget.) Select "Use GPS when screen is off" in its settings. Then turn off the screen while the app is in the foreground.

**Comment by rdoeffinger** [comment]
I guess I have been moving the goalposts a bit during the discussion, but my thoughts on that are
- I don't think the right solution to "options are bad and we should avoid them" is "use options in some other app"
- It might work for me (if ignoring issues like using an app that requires accepting a EULA), but I don't think this solution is something e.g. my mother would be comfortable using. It also doesn't allow working on something else, plus with some older phones at least switching between apps would disable GPS tracking for a short moment which then resets the whole (or at least part of?) progress...
- Plus, I'd like a GOOD solution that has benefits for others as well. I could always make a fork and revert that change (even though the license means I'd have to install the app manually everywhere, and I don't yet know which commit changed that...). The "position not yet known" message isn't really user-friendly anyway so replacing it might be a good idea anyway (especially when Google Maps actually does know my location to within a few m via network based location it's just confusing and wrong).
Maybe a new ticket would make sense, but I don't want to spam tickets especially when I don't know if I might have missed a better solution or a reason why it's clearly not a good idea.

**Comment by rdoeffinger** [comment]
And to pitch it specifically to you (which is hard since your GPS seems to work rather flawless): when getting the first GPS fix after a flight takes up to 90 seconds, wouldn't it be kind of cool if you could press the "show my location" button, then switch to making phone calls or whatever you need to do, and then when you switch back to the map it's all ready and shows you where you are?
(apart from that, if GPS isn't available - usually the case when in the middle of some building at least, I assume at least that also applies to your phone - but network location shows you at the other end of the world, it would be kind of nice if it at least optionally could position the map at least on the right country)

**Comment by sonora** [comment]
Yeah, but now we have totally moved to actually talking a "feature request" :). Something like 

- When I tap on 'MyPosition', and my device has GPS enabled, turn on GPS and leave it on with some limited timeout which will not fry your battery (perhaps 1 minute or so) even if OsmAnd is put in the background.

It would more fit into the philosophy of using system services automatically as a response to a user-selected action, but do not allow their direct manipulation per se which bears the risk of many users not knowing what they do.

If you like that version, it is probably worth a new "Feature request" ticket so it can be thought through and discussed if this is put in the development queue.

**Comment by sonora** [comment]
PS: For some evidence of what issues there are, see here ... #2528  :)

**Comment by rdoeffinger** [comment]
For anyone still looking for a replacement...
While not OpenSource, I found "GPS connected" (https://play.google.com/store/apps/details?id=org.bruxo.gpsconnected&hl=en) which is at least ad-free, simple to use, doesn't need funny permissions and provides at least the "keep GPS always on" functionality,
As part of this ticket, may I request that you add this or a similar app to the app list that now shows when pressing the satellite status, preferably on top? So that anyone suddenly missing the feature at least easily finds a replacement.

On the "feature request" thing: if more than 1 minute wouldn't be considered acceptable I'm not sure there is a point in opening one. What I'd really like is some built-in solution that works for a proper cold (non-AGPS) GPS lock, as described here: https://en.wikipedia.org/wiki/Time_to_first_fix
15 minutes is pretty much the official best-case time for that one, and with anything below maybe a 5 minute timeout (preferably a bit longer) you basically have to constantly stare at the screen for the whole time...
(the GPS logging is not user-friendly, disabled by default, not at all obvious etc so not really a good method).

**Comment by ilya-chumakov** [comment]
I was also disappointed by the disappearance of "Keep GPS" option. The initial GPS fix (after a long distance moving) can consume time (minites) and battery's power when waiting with the screen on. Moreover, each time when the device's screen is turned on it takes a few seconds to get the current position which is a bit irritating (yes, I have a modern and fast device).

Let me combine the three known possible solutions:

1.  Constantly record a GPS track (Actually I don't need the track in 95% of time)
2.  Use [GPS connected](https://play.google.com/store/apps/details?id=org.bruxo.gpsconnected&hl=en) app (big thanks to @rdoeffinger, I tested the app and it works)
3.  Downgrade to Osmand 2.2 =)

Which solution consumes the minimal amount of the battery's energy? 

As for me, it is important to extend the device life between recharges (on a several weeks trip without any possibility to re-charge the device except a powerbank etc.). Here is a real world scenario to clarify the question:
  - Osmand is rarely used: once a day maybe. 
  - When Osmand is running, the device's screen is turned off as long as possible (the screen is a battery eater).
  - The screen is turned on each 10-15 minutes (for less than a minute) just to ensure the path is correct.
  
Could you help me to find the best solution in this case?

**Comment by sonora** [comment]
That sounds a lot like my use case!
Here is what I do:

1. Use as few apps as possible on your phone. In particular, do not install any add-on apps trying to trick the OS into any background behavior like keeping GPS on, killing apps or cleaning the RAM.

2. Set your location service to GPS only (even though many Android versions label this as high battery usage). But out in the wild it is often the only thing you can get anyway, so no point wasting battery power allowing/trying other things.

3. If you do not expect to have cell phone coverage, or do not need it, put the phone into airplane mode. A huge battery saver for long term operation without recharge.

4. Now use OsmAnd like this: Use it plain, no track recording (or if you need to keep track of things chose a recoring time constant of 30 secs or longer, but this would limit you to about 24h run time on a single charge on most devices).

5. Turn on the phone and check the map whenever needed. Do not worry waiting for some second fo the GPS fic. You have already saved the battery power for that. Outdoors I use the screen in auto brightness mode, shading the sensof will darken it considerably during the search if desired.

6. After the GPS fix, first tap the device's home button, then put the device to sleep. Do neither leave OsmAnd in the foreground nor kill the app via a task manager before putting the device to sleep.

7. When you get a chance, once about every week or so suffices, run OsmAnd for a few seconds (3 or so) while your device is connected to the Internet. This will update the GPS almanach and considerably speed up GPS fixes for several days. Repeat after about a week, or after position changes of 500 km or more.

From my personal experience, that will optimize power consumption under the circumstances you describe. I am getting  up to a full week out of regular stock devices in this mode without a recharge.
