### ISSUE TITLE
"Turn screen on" doesn't turn on follow mode

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#3674]
The "turn screen on" option doesn't always follow the current position after turning the screen on. Sometimes it seems to work, sometimes the current position has already moved out of the map view being shown.

"Turn screen on" is set to 10 seconds. OsmAnd version is 2.6.2.

**Comment by sonora** [comment]
Perhaps "Auto-center Map View" is set rather high or "Never" ?

**Comment by scaidermern** [comment]
"Auto-center map view" is set to 15 seconds. I think this is the default unless I forgot about changing it.

Shouldn't the "turn screen on" feature behave independent from "auto-center map view"? "auto-center map view" is useful when panning the map _manually_ whereas "turn screen on" is never used for manual map panning (because otherwise the screen would already be turned on).

"Turn screen on" is only useful if it follows the user position.

**Comment by sonora** [comment]
Yes, 15 secs is the default. And I think you are right, relying on the Auto-center lead time here is probably more of a workaround. Looks to me we should likely have instant centering in this case. But I will have to leave this for others t review, had never used nor tested this portion of our functionality myself.

**Comment by scaidermern** [comment]
> PS: Is this a regression, or has it always been like this?

No idea, sorry. I've started to use this feature just recently. Also mainly for playing around, currently I don't have a real use-case except for saving some battery. Not sure how much though since GPS will be on nevertheless.

**Comment by breversa** [comment]
Screen-on is the major battery gulper in most use cases ; satellite location consumes battery as well, but never as much (from my findings at least), unless you keep your screen off at all time.

"Turn screen on" is actually an awesome battery-saving feature, especially for long road-trips (less for urban drives though). :-)

**Comment by Zahnstocher** [comment]
> PS: Is this a regression, or has it always been like this?

I think it is a regression.
We (I and one or two other contributors) implemented it 2014 and I tested it very long and heavily.
I never saw this issue...

**Comment by Zahnstocher** [comment]
Just did a quick simulation test.
I can confirm this issue, sometimes it does not follow the current position after the screen turned on.
My feeling is, that it actually shows the current position when the screen turns on, but then it seems to jump immediately back to the old position (approximately where the screen turned off).
But it jumps back so quickly, that I'm not sure, if it actually does...

**Comment by Zahnstocher** [comment]
Now I disabled the new feature "animate my position".
This seems to fix it.
Can you confirm?

**Comment by Goodingn** [comment]
I think the auto centre works fine with 'animate positon' turned off.

**Comment by scaidermern** [comment]
Thanks for investigation. I don't think an animation is useful here. The user wants to see the current position as fast as possible.
