### ISSUE TITLE
Automatic driving region overrides manual distance unit setting

### ISSUE THREAD

**Issue by njohnston** [osmandapp/Osmand#3679]
I use kilometres and metres in OsmAnd. After upgrading to 2.6, I noticed that the app kept switching to use miles.

Eventually I realised why: in 2.6, driving region detection is automatic. Being in the UK, miles and metres is the default measurement system.

Switching this setting to "automatic" is confusing.

Steps to reproduce:

1. Select pedestrian mode.
1. Set "Unit of length" to "kilometres/meters".
1. Simulate position somewhere in the UK (US might work too).
1. Select a destination which is >1 km away. OsmAnd will show the distance in km.
1. Press "Go": TTS now announces the distance in miles, even though the UI (distance remaining, speed, ...) uses km.
1. Close OsmAnd by swiping it away in the recent apps list.
1. Restart OsmAnd. "Unit of length" has been set to "miles/meters".

As I see it, there are several problems:

* Enabling automatic detection by default breaks manually-set units. It might not be obvious to users how to fix this.
* *Driving* region should not apply to pedestrian mode. It should only apply to car and bicycle derived modes.
* I think units and side of the road should be decoupled. Many people are only familiar with miles or km--they don't understand both. If someone is familiar with km and then uses OsmAnd somewhere which uses miles, they might be confused. For example, if someone from the Netherlands visits the US, will they really want OsmAnd to switch to miles?

My workaround for now is to select Japan as my region since it matches the side of the road and units I want, but this isn't ideal.

**Comment by sonora** [comment]
I have to say that I personally enjoy all units being automatically adjusted to local customs when travelling internationally, because it automatically reflects also all speed limit signs, roadside distance signs (in in some countries these do not specify a unit), instructions given by locals, etc.

But I can see that other users may have other preferences here. I guess what you are saying is that we should use the Auto-detection upon a fresh install, but when auto-detection later decides it should change the unit because you re-located to another country, we should prompt a dialog to approve or deny?

**Comment by njohnston** [comment]
I'm saying:

* Automatic detection should apply only to bicycle and car-derived routing modes.
* Prompting the user to accept changing units could work, but might be annoying. Instead, I think driving side detection should be automatic, and in the "Unit of length" settings there should be an "Automatic (based on location)" option. (Currently "Unit of length" is permanently changed by automatic detection, and the automatic detection is not repeated until navigation is started again.) Another possibility is to change units only during navigation (but still allow a user to always use the same measurement system if desired).
* The bug where units can be announced in miles but shown in km should be fixed.

I'm glad you see that some users might prefer to always use the same measurement system. Here in the UK, when I tell people I've walked 15 km, about 9 times out of 10 they ask "How many miles is that?". I imagine these people would not want to switch to km when travelling.

**Comment by njohnston** [comment]
There also been [some confusion about this on the forum](https://groups.google.com/forum/#!topic/osmand/hNkAXnbFuCs).
