### ISSUE TITLE
Allow elevation data to be used for pedestrian routing

### ISSUE THREAD

**Issue by njohnston** [osmandapp/Osmand#3680]
OsmAnd 2.6 added support for using elevation data in bicycle routing.

This would be useful for pedestrian mode too.

Please add support for elevation data in pedestrian mode. There has been some [discussion about it on the forum](https://groups.google.com/forum/#!topic/osmand/3qh6XpCF_zw).

If it's possible to enable this for pedestrian mode by changing routing.xml, please specify how. Thanks.

**Comment by xmd5a2** [comment]
This is planned and requires some testing. If you want to do it yourself, add to pedestrian profile
```xml
		<parameter id="height_obstacles" name="Use elevation data" description="Use terrain elevation data provided by SRTM, ASTER and EU-DEM" type="boolean"/>
```
and simple "obstacle_srtm_alt_speed" section.
```xml
		<way attribute="obstacle_srtm_alt_speed">
			<if param="height_obstacles">
				<gt value1="3" value2=":incline">
					<select value="2"/>
				</gt>
				<gt value1="7" value2=":incline">
					<select value="8"/>
				</gt>
				<gt value1="13" value2=":incline">
					<select value="16"/>
				</gt>
				<gt value1="25" value2=":incline">
					<select value="32"/>
				</gt>
				<select value="48"/>
			</if>
```
This should work, but these coefficients needs to be adjusted and tested.
