### ISSUE TITLE
Creating POIs show as deleted in 'my places'

### ISSUE THREAD

**Issue by DFyson** [osmandapp/Osmand#3681]
Create a POI and delete an existing one. Go to 'my places' and the 'deleted' label is reversed for all of them. That is new POIs are labeled as 'DELETE' and deleted ones are unlabeled.

Using 2.6.2+ from 2017-04-09

**Comment by xmd5a2** [comment]
![screenshot_2017-04-19-18-57-33](https://cloud.githubusercontent.com/assets/5829014/25189551/2c6791fe-2532-11e7-9ecd-5f6c31d8ee27.png)
![screenshot_2017-04-19-18-56-13](https://cloud.githubusercontent.com/assets/5829014/25189558/31059eb8-2532-11e7-85af-aef031f6a4a1.png)
