### ISSUE TITLE
Start of voice message is missing

### ISSUE THREAD

**Issue by IByte** [osmandapp/Osmand#3689]
Today, while I was using OsmAnd's voice navigation on my headphones, I noticed that the start of many directions was not pronounced, sometimes leaving only things such as "...street.", which is of course unusable for navigation. What could cause this and can it be fixed?

_Environment information:_
OsmAnd version: 2.6.2 (2017-04-09)
Offline map file: Netherlands Overijssel, December 1, 2016
Android version: 6.0.1
Device: Samsung Galaxy S5 mini (SM-G800F)
Voice: Dutch TTS, April 13, 2017

**Comment by sonora** [comment]
Can you please report what your setting is under Settings / Navigation settings / Voice guidance output.

Also: When you say "headphones", are we talking Bluetooth, right?

Thx - Hardy

**Comment by IByte** [comment]
- The voice guidance output setting is "Media/music audio" (default, as far as I know)
- No, this isn't Bluetooth, I used simple wired mini jack (3.5mm) earbuds
- I didn't try the phone's speaker yesterday (could be slightly tricky on a bicycle), I'll see if I get a chance to test this soon.

**Comment by sonora** [comment]
Ok, the settings seem ok, and if you are using the analog connector there cannot be any delay issue there either.

Just to make sure: You are using a TTS voice, no recorded voice, right? What TTS engine with whay settings? This is in the debice's Android (not OsmAnd) settings.

I just tested on my S5 mini test device (stock ROM) and find no such effect, so we have to dig a lot deeper. Can you please temporarily activate OsmAnd's Development plugin, then go to Settings / Dev settings / Test voice prompts. Can you reproduece any off the cut offs when tapping the test buttons? Try both with and without a 10 sec break between tapping different ones.

When this occurred, where you using any "Turn screen on/off" settings etc., or is your screen always on? Is your observation perhaps related to the screen being on or off when this occurs?

Last not least, in the Android notification bar, is the Samsung Power saving feature enabled?

**Comment by IByte** [comment]
It seems to make no difference to my tests whether I use the phone speaker or the wired earbuds.

Here's a bunch of [screenshots of my settings](https://www.dropbox.com/sh/nv1vmib1yvvv9v8/AABIyhWE8BysIce_YRnt4Gq3a?dl=0).

I am using Google TTS with a Dutch voice, so it can pronounce street names (that wouldn't happen with a recorded voice, of course, and the result of trying to have Dutch names pronounced by English TTS is... let's just say "hilarious").

I can sometimes reproduce the cut-offs, but only (and then only sometimes) when I use a 10s break or switch engines. It doesn't seem to matter whether I use the Google or Samsung TTS engine, and I get the cut-offs in the sample players of both OsmAnd and the Android settings, so it might be an Android/Samsung issue rather than something in OsmAnd's code (but of course, it nonetheless affects OsmAnd's performance).

My device is running the official Samsung OEM Android update, by the way, no rooting or custom ROM.

The screen being on or off doesn't seem to matter much. My screen was off yesterday when I noticed it (my phone was in my pocket), No "turn screen on" setting is in effect. Today's tests were performed with the screen on, of course. A cut-off was sometimes noticed after turning the screen on and playing a sample, but that might just be caused by the delay caused by that action, I'm not sure whether it has anything to do with the screen being on or off.

I do not use the Samsung power saving feature, it is off.

**Comment by sonora** [comment]
I have now tested this extensively on a Samsung S5 mini, Stock ROM  Android 6.0.1 (after all the latest OTA updates were installed for that device). TTS engine is google, language English (United States).

I find no such effect, neither via the device TTT-engine's "Listen to an example" test button, nor via OsmAnd when testing in live navigation or via "Test voice prompts".

I am wondering if you have any other apps loaded which may interfere with the voice synthesis timing. Maybe temporarily removing suspicious apps or a device factory reset could help. Or we are looking at hardware or memory-read issues, not sure.

I find no evidence that we are really looking at anything here we could try to fix in OsmAnd, really.... I will continue to monitor this, but there may not be much we can do.

**Comment by IByte** [comment]
Like I said, the issue may be with my device or Android installation somehow, as I am able to reproduce the problem outside of OsmAnd (it is still present in navigation as well). A reboot doesn't fix it, and I don't see any apps that are obviously "suspicious" for this purpose. Strange...

Well, I'll keep an eye on it, but I'm out of ideas for now as well. A quick Google search also fails to reveal any leads.

**Comment by sonora** [comment]
There is a thread on xda which talks about not the same but a similar issue. People claim it was solved by uninstalling the upgrades to google Search.
If that does not help, you may have to try factory-resetting the device. As I say, I testesd an S5 mini with almost identical software status as yours shows, and it has no such issue.

**Comment by IByte** [comment]
Uninstalling updates to the Google app does not appear to have solved the problem. Do you happen to have a link to the thread?

**Comment by sonora** [comment]
Sorry, forgot to record it. I must have probably googled something "like TTS voice cut off", and there were many hits. I read a few of them and the only I remember that offered a general solution worth trying seemed that one.

May be worth doing some searching yourself. But I do confirm that with exactly your hardware and firmware version I get fault-free TTS, so there should be a way ... :)

**Comment by IByte** [comment]
OK, I'll do some digging, thanks anyway. Until then, I'll have to take a look at the screen if the voice announcements are mangled.

**Comment by sonora** [comment]
Let me close this to clean up our issues list, as I think we have established this should be a device issue, not an OsmAnd issue.
