### ISSUE TITLE
Regression: Voice output to car stereos broken in latest release

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#3690]
From user complaints I just notice we broke

- **(1)** our test button 11.1 in Development settings / Test voice prompts testing and indicating a device's capability to connect to car stereos via phone call mechanisms. (It is and should not be profile aware, as it detects a device capability, but now acts profile-sensitive)

- **(2)** our settings button 11.2 allowing to adjust the phone call audio delay. (A global setting, but the button now acts profile-sensitive.)

- **(3)** Now that the voice settings are profile-based, things like "Voice  guidance output" for the Browse map profile cannot be selected at all: We support audio output (like traffic warning prompts and speed limit announcements) while just driving in our Browse map (default) profile (after stopping a navigation), but we have no menu or interface to select (or even display) which audio settings are used there.

@vshcherb The issue is caused by us making  `AUDIO_STREAM_GUIDANCE`  profile-based (3512b82). Before fixing, it would be good to know if we intend to leave all audio settings profile-based now? (There had been some criticism on the web.)

The issue is in complete analogy to us making all trip recording filter parameters profile-based (see #3437), but having no way to adjust (or even display to the user) the filters actually used for trip recording in the Browse map profile.

- To solve (3): We must either provide menus to also adjust the necessary Settings for our Browse map profile (adding more complications, because only a subset of all profile-based settings matters there), or simply be a lot more restrictive which parameters we actually offer profile-based vs. simply global. I usually lean towards global settings, it removes a certain layer of complexity (like we have to learn for the second time here now).

- If we leave things profile-based, I will have to investigate how to overhaul the BT SCO functionality in a profile-based context, and I foresee this may again not exactly "simplify" the overall app configuration for our users.

- Side note regarding (2): In any case, it may make sense to move the phone call delay setting (currently behind button 11.2 in development settings, because it is easier to test from that screen) over to our "regular" audio settings. But I do not think we would want that profile-dependent, too?

**Comment by sonora** [comment]
@vshcherb Looks like the issue is really caused by us making `AUDIO_STREAM_GUIDANCE` profile-based in a hurry.

Which has caused yet another issue: We support audio output (like traffic warning prompts and speed limit announcements) even while just driving in our Browse map (default) profile (without active navigation), **but we have no menu or interface** to select settings like `AUDIO_STREAM_GUIDANCE` for the default app profile...

The issue is in complete analogy to us making all trip recording filter parameters profile-based (see https://github.com/osmandapp/Osmand/pull/3437), but having no way to adjust (or even display to the user) the filters actually used for trip recording in the Browse map profile.

I am currently not sure what the best way out here is: Provide menus to also adjust necessary Settings for our Browse map profile (adding more complications, because only a subset of all settings matters there), or simply be a lot more restrictive which parameters we do actually make a available profile-based vs. simply global. Where in doubt, I am usually leaning towards global settings, it removes a certain layer of complexity, like we have to learn for the second time here now.

**Comment by vshcherb** [comment]
After reading that issue I'm still very confused how things are broken.
The only thing which is clear to me is (1). All other options are unclear. 
Making audio profile settings profile makes sense cause you can use different voice speaker in the car and on the bicycle. So, I'm confused how things get worse.

**Comment by sonora** [comment]
Ok, in a nutshell:

(1) Still works correctly if you, before entering the Development Plugin settings,
- put the app in the correct profile,
- and select "Phone call audio" for that profile.

But of course, many users --when testing their device's voice capability-- are in the default ("Browse map") profile, and we cannot even set that profile to use "Phone call audio" (which is issue (3) )

(2) is a minor issue: Adjusting the delay still works in principle, but I check if the app (i.e. I guess now the profile before entering the Dev settings) is set to phone call audio. We could simply drop that check, then the button would work again all the time. (I simply wanted to avoid users changing that setting by accidental taps on button 11.2 when their phone is not even in phone audio mode.)

**Comment by vshcherb** [comment]
(1) We need to fix may be by forcing "Phone call audio" , though correct me if I'm wrong, if you dont change settings at all it works by default installation.

**Comment by vshcherb** [comment]
(2) If I understand you've found how to fix it, so I think it is a good approach.

**Comment by sonora** [comment]
Yes, fixes for (1) and (2) are rather obvious.

The big principal issue is in (3), and we should solve it first: Where do we let the user adjust profile specific audio settings for the **default** profile?

**Comment by sonora** [comment]
I have fixed (1) and (2) by a larger overhaul of our TestVoiceActivity.java

The remaining question is (3): How can you set AUDIO_STREAM_GUIDANCE for the default (Browse map) profile. When entering our settings screen for profile-dependent settings (like the Navigation settings), we do not provide an option to select the Browse map profile. As a result, AUDIO_STREAM_GUIDANCE for the Browse map profile is currently "frozen" to whatever it happened to be when a device was upgraded to release 2.6.

The only low-impact workaround solution I can offer without a bigger UI overhaul seems that we simply always set **the setting for the Browse map profile to the same value the user choses for the CAR profile**, i.e. we keep it in sync with the CAR profile value. While this would be sort of undocumented, at least it provides a way to change the setting in the first place?

**Comment by sonora** [comment]
@vshcherb Done, see https://github.com/osmandapp/Osmand/commit/bae55067b3602eda4384f7b6d3993bd5d0697826.

I guess we can leave it like that, a rather low-impact workaround, even if somewhat undocumented.. 

Best- Hardy

**Comment by vshcherb** [comment]
Thanks!
