### ISSUE TITLE
Pressing 'Go' should zoom in

### ISSUE THREAD

**Issue by Goodingn** [osmandapp/Osmand#3692]
Would it just Go already?

When pressing Go, the map centres on my position and zooms in, a bit.

I have to actually start driving my vehicle for Osmand to change the zoom level to close up, then I can actually see where I'm going.

Shouldn't a press of Go zoom into the closed zoom available by the speed/zoom profile straight away? Aren't people using their satnav while not driving, and therefore are stationery when they press 'go'?

I have my Auto Zoom set to Mid Range and my Map Zoop set to 50%

Cheers,

**Comment by sonora** [comment]
Well, we immediately jump to zoom 16, I have just tested (even before the route is calculated). 2 Things here:
- You should use the latest release 2.6.x, it had a fix with respect to the Auto-zoom, I remember.
- Map magnification should be 100%, or for car mode even 125%, for the app profile you use in navigation. Choosing lower significantly lower than that will put "more map on the screen" to give you more overview, but in the navigation use case you are reporting here requiring more detail this is of course exactly counter-productive, and like exactly causes the issue you are reporting?

**Comment by Goodingn** [comment]
I use 50% for more map on screen because the 'sweet spot' of auto zooming for me is somewhere between the 'mid' and 'long' profiles.

I find there is adequate detail here in normal use- in my original report when I do start driving (and all other driving situations) I have adequate detail. 50% is therefore not counter-productive

It is when I press 'Go' there is not adequate detail. Granted '50%' may be a contributing factor, but it shouldn't be when it works for me at all other times.

The simple question remains- why not default to zoom to the closest zoom the selected profile allows (because you should be stationery), instead of some arbitrary fixed value of '16'?

**Comment by sonora** [comment]
Are you aware that as soon as you tap "Go" the app enters another app profile, (like "Car" if you chose car navigation), and that in each profile you need to adjust things like Map magnification factor etc. separately?

"Closest zoom" may actually just give you a few meters radius on small screens, which is not very helpful.

**Comment by Goodingn** [comment]
"closest zoom the selected profile allows" and "close[st] zoom available by the speed/zoom profile straight away" was my specification, not "closest zoom" as you've quoted me :)

Well aware of all things you've mentioned thanks.

All I want is for when I press Go for the zoom to be identical to if I've just driven to a stop- the closest zoom available in the auto zoom profile.

Ta

**Comment by sonora** [comment]
Ok, I see, thanks!

Done some more testing and it looks like there is really some issue here: The exact behavior of what happens seems to differ from try to try, perhaps based on whether the map is already locked to ones position when the 'Go' button is tapped, and perhaps also depending on what the actual zoom level to start with is, and whether the destination is actually shown on the screen or is off the edge. Needs some closer investigation, it seems, as I cannot off hand reproduce a consistent behavior.
