### ISSUE TITLE
2.6.2 regression: KML import is broken again

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#3693]
Hi,

in OsmAnd+ 2.6.2 KML import is broken again.

Several fixes have been introduced by
#3314
#3161
#3277
that had fixed the problem in the 2.5 branch.

Since build 2.6.x the KML import is broken again. You can test these attachments below from the bug reports listed above:

https://github.com/osmandapp/Osmand/files/628243/phuket-de.kml.zip
https://github.com/osmandapp/Osmand/files/600998/ClimateChangeEffects3.kml.zip

Best Regards,
Norbert

**Comment by vshcherb** [comment]
Can't reproduce, provided kml works and there were no changes done in that area.

**Comment by Norbert80** [comment]
@vshcherb in this case kml import into OsmAnd does not work on ny new LG G5 device. Any idea? (The gpx import failed toast pops up with every try.)

(Works perfectly with MAPS.ME.)

**Comment by Norbert80** [comment]
I found the reason and filed a correct bug report: #3697
