### ISSUE TITLE
"OSM live (beta)" string not translatable

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#3694]
It seems the main menu item "OSM live (beta)" string not translatable. I can't find it on Weblate.

**Comment by vshcherb** [comment]
That's a name same as OsmAnd, (beta) is translatable though it is clear for most of people.

**Comment by aceman444** [comment]
OK, but then in many other strings where 'OSM live' is part of sentence it is translatable. Then it should somehow be made announced to the translators that it is a name and you do not wish it being translated/modified.
