### ISSUE TITLE
Allow to hide needless POI info

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#3695]
Allow the user to set that he does not want some information about a POI when it is clicked. This should reduce the clutter in the pull up panel that shows when a menu is clicked.
I think at least these items should be hideable:
1. GPS coordinates (latitude, longitude)
2. Open location code (OLC)

I think these may be useless for most normal users and just get in the way.
There is another item that is "OSM object link", but this one is already dependent on enabling the "OSM editing" plugin, which is good idea.

Thanks.

**Comment by dmpr0** [comment]
I do not agree, adding an extra setting makes a mess. After people start to forget that they have disabled something, and how to get it back. If the POI has information, then the coordinates are at the very bottom of the screen, if there is nothing, only the coordinates remain there.

**Comment by aceman444** [comment]
There are some POI where the info takes whole screen height. You do not know if you are already at the end of the useful information before you scroll and expose the coordinates row. So, the needless info goes into way and has its cost being there.

**Comment by vshcherb** [comment]
I think it should be 1 option either OLC either coordinates and that could be configurable. Cause we already have #3708 for that purpose, that issue will be closed.

**Comment by aceman444** [comment]
This issue is for the possibility to have NONE of the coordinates. Me, even as an active OSM mapper, have absolutely no use for them. Then what is the use for map users/consumers...

**Comment by Norbert80** [comment]
OLC makes it is easy to share coordinates with Google Maps users. There is no syntax like comma, dots or spaces... Just copy and paste.
