### ISSUE TITLE
Quick actions -> add favourite -> address search    cannot be skipped

### ISSUE THREAD

**Issue by stephan75** [osmandapp/Osmand#3696]
Try the newly quick actions in latest nightly build from yesterday,

have "add favourite" as one of the quick actions,

add a favourite via that quick feature, and see the upcoming box that indicates an ongoing address search with a spinner animation ...

This address search is NOT skippalbe, in opposite to addess search when adding a favourite via old school way.

Please make that quick action address search **skippable**,

or even introduce a setting that this address search can be switched off by user in general.

**Comment by vshcherb** [comment]
If name is assigned then address is not searchable.

**Comment by stephan75** [comment]
Sorry @vshcherb , what do you mean with "If name is assigned then address is not searchable" ?

That mentioned address search ist starting **always** when adding a favourite via quick actions.

Can you explain your point of view?

**Comment by vshcherb** [comment]
I don't see your point *always*, if you specify a name for a favorite while adding quick action, search doesn't happen
