### ISSUE TITLE
KML import always fails if Android/data is used

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#3697]
Hi,

if OsmAnd is configured to use Android/data as storage path, trying to import a KML file from file manager always fails with an error message that GPX import has failed.

If I change the storage path to Android/obb it works as expected.

Bug found with OsmAnd+ 2.6.2.

Best Regards,
Norbert

**Comment by njohnston** [comment]
My data storage path is /storage/6461-6339/Android/data/net.osmand.plus/files/osmand and I was able to import your Phuket KML file fine.

If you can, try using `adb logcat` to see if you can get a more detailed error.

**Comment by Norbert80** [comment]
After changing the directory back I can no more reproduce the bug. Maybe it only happens on fresh profile with original path setting. You may close this issue as long as we don't have more information.

**Comment by vshcherb** [comment]
I guess issue is duplicate or the same as https://github.com/osmandapp/Osmand/issues/3819
