### ISSUE TITLE
Option to not centralize the map when we create an audio note

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#3700]
When we create audio notes the map gets automatically centered at that point, with a screen like this:

![](https://cloud.githubusercontent.com/assets/982338/25387447/4157c1f6-29a1-11e7-994c-586b727e2338.png)

Unfortunately when driving we usually don't want to get the map automatically centered at the recently created note (for example, I want to keep seeing where I actually am), nor we want to see that screen with `Play`, `Delete` and other information.

Could we have an option to disable the auto-centering of newly created notes and an option to disable this information screen, please?

OsmAnd is `OsmAndF~ 2.7.0#17191D`

**Comment by vshcherb** [comment]
Was already fixed the only issue is to keep centering by location #4693
