### ISSUE TITLE
GPX view: prevent map preview from scrolling, so all track segments can seen on the preview

### ISSUE THREAD

**Issue by njohnston** [osmandapp/Osmand#3701]
The improved GPX analysis in OsmAnd 2.6 is great. One minor problem though is that when viewing a track which has more than one segment, it's only possible to use the charts for the first segment interactively.

When you scroll to the next segment, the map preview scrolls off the screen, and is no longer visible. This means I can't find out what part of the track that segment is for without pressing "Analyse on map", which is slower.

To fix this, I think the map preview's position should always be fixed at the top of the window, so it doesn't move when scrolling. The rest of the content can be scrolled as currently. This means that all segments can be easily analysed on the preview map without having to press "Analyse on map".

Illustration of what I'd like:

![gpx_preview_scroll_changes](https://cloud.githubusercontent.com/assets/638458/25398562/74047b4c-29e4-11e7-90c6-3a35357f35c7.png)

**Comment by vshcherb** [comment]
The vertical scrolling is fixed.

**Comment by njohnston** [comment]
@vshcherb: thanks for your comment, but I compiled the latest code (from about 2000 UTC yesterday) and tested it in an emulator instance, and I don't see any change to the scrolling behaviour.

The preview map still scrolls off when I move down, rather than remaining fixed in the same place like I suggested.

This is less of a problem now that the track analysis shows combined stats and charts for the entire track (not just the first segment) first, but it still means that subsequent segments can't be analysed on the preview map.

**Comment by vshcherb** [comment]
Indeed we made another attempt to make it working better on sliding event. Please try again it works better though it is hard to achieve perfect result unless we completely block the touch on the graph.

**Comment by njohnston** [comment]
@vshcherb: I've just compiled the latest code and I don't see any changes to the scrolling behaviour.

Perhaps I haven't explained myself well. To summarise the problem: if a track has more than one segment, when I scroll down to see the stats for the second (or later) segment, the preview map / thumbnail scrolls off the top of the screen. This means that when I tap the chart for that segment, I can't see the blue dot on the map preview at the same time.

My suggestion is to change the layout so that the map preview is fixed in position at the top of the window, and does not scroll.

I often record tracks including different modes of transport, e.g. walking, then train, then cycling. I start a new segment for each part of the trip. Being able to see the start of subsequent segments on the preview map without having to press "Analyse on map" would be useful.

**Comment by vshcherb** [comment]
@njohnston Yep it was misunderstanding for that. Having map preview scrollable or not scrollable has pros / cons. Today according to design it's supposed to stay scrollable. The biggest drawback of having it not scrollable: it will be only 1 segment visible on the screen and if you have > 3 segments, it is hard to navigate between them. So in that case UI should not be scrollable at all but instead pageable (pages with button next/previous segment), which requires big changes.
You could use analyze on map for a specific interval.

**Comment by njohnston** [comment]
Thanks for the response. Like you say, pages would be better but it's a big change, so I guess it might be something to look at again in future, but not for 2.7.

**Comment by vshcherb** [comment]
definitely not 2.7, it is a last week for 2.7 and only bugs. The life doesn't stop after 2.7 and we will be collecting input.
