### ISSUE TITLE
Labels in track preview map disappear when returning from "Analyse on map"

### ISSUE THREAD

**Issue by njohnston** [osmandapp/Osmand#3703]
When selecting a GPX track in My Places, the track is displayed on a small preview / thumbnail map:

![map_preview_with_labels](https://cloud.githubusercontent.com/assets/638458/25398837/4e92e8fc-29e5-11e7-90e9-d6411a8d8322.png)

After pressing "Analyse on map" and then going back, the labels on the preview disappear, and the map appearance changes:

![map_preview_with_no_labels](https://cloud.githubusercontent.com/assets/638458/25398847/5906289e-29e5-11e7-87b4-5ddc9393b15f.png)

Changing device orientation fixes the problem (presumably because the activity is fully recreated?).

(This is on a Samsung Galaxy S5 running Android 6.0 if relevant.)

**Comment by xmd5a2** [comment]
Can't reproduce with some of my tracks. Can you share your track?

**Comment by njohnston** [comment]
@xmd5a2: I can reproduce it with this track and many others but not 100% consistently.

I see this in logcat, but I'm not sure if it's relevant:

```
I net.osmand: MapRenderRepositories RENDER MAP: Interrupt rendering map
```

Is there a difference between what happens when pressing back from "Analyse on map" and when changing orientation? Like I say, changing orientation fixes the problem, so if pressing back forced a similar redraw then perhaps that could fix the problem. But I understand it's difficult to investigate when it can't be reproduced.

**Comment by sonora** [comment]
I cannot reproduce this either ... are you tapping the "back" arrow shown in your screenshots near the top left corner, or the device's "BACK" key? Does it happen all the time, or only sporadically?

**Comment by njohnston** [comment]
This is a strange problem. Earlier today I could only reproduce it sporadically (maybe 1 in 3 attempts) but now I can reproduce it every time, even if I restart OsmAnd.

I can reproduce if I press my phone's back button or the "back" arrow on screen. (Side comment: I don't understand why the back arrows are necessary. On the overview tab, the back arrow goes back to "My Tracks", but the back key on the phone goes back to the map view. I'd prefer it if pressing back on the phone went back to "My Tracks".)

I've noticed that although I can reproduce it with the above track (Singapore), I cannot reproduce it with some other tracks. The problem could potentially be related to the zoom level and level of detail in the preview map. I can reproduce the problem in densely mapped areas (e.g. city centres) but not in less densely mapped areas. But this might just be a coincidence because earlier I couldn't always reproduce the problem with the Singapore track.

@sonora: did you download the map of Singapore before trying to reproduce?

**Comment by sonora** [comment]
No, I tried several of my tracks in different corners of the world, and never managed to observe the issue so far...

**Comment by vshcherb** [comment]
That's possible to happen on some devices (may be less or more powerful), when map rendering is cancelled in 1 thread and didn't finish in another thread. 

Cause the issue is not very critical (you can click slower or open track again) and hard to reproduce it will be closed.
