### ISSUE TITLE
Size in GPX list is multiplied by 1024

### ISSUE THREAD

**Issue by adrien-n** [osmandapp/Osmand#3706]
OsmAnd 2.6.2 from F-Droid, the size of GPX files in the list is wrong: for instance, it shows 3.9MB instead of 3.9KB. Device is Oneplus 3T with latest OxygenOS (based on Android 7.1).
![wrong-gpx-file-size](https://cloud.githubusercontent.com/assets/10911300/25401492/118d51fc-29f6-11e7-8ea5-ecd64c273661.png)

**Comment by sonora** [comment]
Weird, for me that screen displays "recorded distance", "number of waypoints", and "track time span" (like in line 1 of the screenshot above for "Show current track"). I am currently not sure why you have a date/time display at all ...

**Comment by sonora** [comment]
I think it is fixed by this https://github.com/osmandapp/Osmand/commit/81fae15d00f9e0dad87293a1a5f2ecbb68f9aaa4, but please double-check. Still not quite sure when we display size at all here.

**Comment by thinking-aloud** [comment]
As of today this Issue is still not fixed (OsmAnd+ 2.7.2). Please reopen the ticket.
![screenshot_20170801-091956](https://user-images.githubusercontent.com/1903874/28813685-a8cebab0-769a-11e7-8fc8-b782cafc7a99.png)

**Comment by adrien-n** [comment]
Just a note. I am using F-Droid and the OsmAnd builds are really lagging
behind. As a consequence, I haven't been able to test the fix for this
issue myself unfortunately.

**Comment by thinking-aloud** [comment]
It is fixed, but the display of file size is kinda bad, so I created another issue. https://github.com/osmandapp/Osmand/issues/4251

**Comment by adrien-n** [comment]
Just following up: an update to OsmAnd has finally reached F-Droid and I can confirm things work for me. Thanks!

(I don't know who did the update but you get my gratitude too)
