### ISSUE TITLE
Routing problem example with OsmAnd+ 2.6.3 vs OpenStreetMap.org

### ISSUE THREAD

**Issue by 5thdev** [osmandapp/Osmand#3709]
hi,
 
in this example you can see a simple route in OpenStreetMap.org:
http://www.openstreetmap.org/directions?engine=mapzen_car&route=44.50400%2C11.35905%3B44.50506%2C11.35789#map=18/44.50481/11.35899

and attached the same navigation performed by OsmAnd version 2.6.3:
![screenshot_20170426-123424](https://cloud.githubusercontent.com/assets/25363918/25435281/ccf8e0b6-2a8f-11e7-909e-ec959b2d4023.png)

I've tried with diffrent phone with same software version.
Hope it helps to improve it

**Comment by xmd5a2** [comment]
Adding
```xml
			<select value="185" t="highway" v="residential"/>
```
to https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#L236 fixes this, but not sure if this fix is correct and it will dot break other things because residential is already commented here.

**Comment by vshcherb** [comment]
@xmd5a2 I think this is the only correct fix for that situation, though I'm not sure if it breaks anything else. So we should find the maximum value for this penalty, does anything else work ">185"?

**Comment by xmd5a2** [comment]
@vshcherb no

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/9f341303bfa536af63e3468c586a1a3dc0f72359
