### ISSUE TITLE
Audio note function while playing music

### ISSUE THREAD

**Issue by CorentinLemaitre** [osmandapp/Osmand#3710]
Hello, 
I have a OSMAND Version 2.5.4. I use the note extension, and mainly the audio note or dictaphone. 
It works very good i have just a suggestion : 
Is it possible to create an option wich pause the music when you do an audio note? Just like the option for voice routing. 
If it is not the correct place to suggest something i am sorry to disturb.

Corentin

**Comment by pebogufi** [comment]
And not only stop music, but es well stop voice of navigation instructions during recording audio note.
