### ISSUE TITLE
Can't select a custom colour for a GPX route (regression?)

### ISSUE THREAD

**Issue by njohnston** [osmandapp/Osmand#3711]
GPX distinguishes between tracks and routes.

Custom colours can no longer be set for GPX *routes* ([example file](http://www.nationaltrail.co.uk/gpx_download?filename=national_trails_cotswold_way_2014.gpx)), because when tapping on the route in "My Places", only "Show on map" is shown:

![no_colour_for_gpx_route](https://cloud.githubusercontent.com/assets/638458/25438243/bdfbe300-2a90-11e7-839f-bc2ac7f0f69b.png)

This is because in [TrackSegmentFragment](https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/myplaces/TrackSegmentFragment.java#L340), the split_color_view part of the gpx_item_list_header.xml layout (which contains the split time/distance and colour selection) is set to `View.GONE` if there's nothing in the adapter:

```java
    if (adapter.getCount() > 0) {
        // ...
    } else {
      splitColorView.setVisibility(View.GONE);
      divider.setVisibility(View.GONE);
    }
```

The adapter is empty because it is only populated from tracks, not routes.

Being unable to select a custom colour for GPX routes is a problem for hiking routes, as they are often distributed as GPX files containing routes, not tracks.

OsmAnd's own distance calculation plugin also saves GPX files containing routes, so these cannot be shown in a custom colour either.

Workarounds for now are: add a colour to the GPX files themselves, or convert routes to tracks. It would be great to get this fixed properly though :)

**Comment by vshcherb** [comment]
The map should be displayed in that case and points connected with a line similar to what we see on the maps.

**Comment by vshcherb** [comment]
Today as a workaround you can change default color for all gpx tracks.
