### ISSUE TITLE
no "elevation details" for calculated route in 2.6.2

### ISSUE THREAD

**Issue by therob84** [osmandapp/Osmand#3713]
Any ideas why I do not see the new feature "elevation details" for calculated routes withbmy f-droid installation 2.6.2?
From which source they are loaded? The contour maps for the SRTM plugin?
Do I need to activate this feature in settings?

Analysing elevation profile for saved gpx-tracks does work nicely!

![screenshot_2017-04-27-10-46-44](https://cloud.githubusercontent.com/assets/15350793/25475552/688e0a9a-2b37-11e7-8f7b-be582d5697c6.png)

**Comment by xmd5a2** [comment]
Looks like you are using map without elevation data. 
https://github.com/osmandapp/OsmAnd-tools/issues/136

**Comment by therob84** [comment]
Ah, good point. That could be as I do not update my maps very frequently ([via](http://download.osmand.net/rawindexes/)). 
But for this feature I do need to update all maps, right?
Does this make the additionally downloaded/used contour maps now obsolet (from which before the contour/height-lines for displaying ontop of the map are gatherd from)?

**Comment by xmd5a2** [comment]
Yes, you need to update all regular maps. Contour lines/hillshading is a separate feature and it does not interfere with elevation data.

**Comment by therob84** [comment]
> Yes, you need to update all regular maps.
It works! Thanks for your fast and helpful answer!
