### ISSUE TITLE
Wrong osm link for fixme on osm ways

### ISSUE THREAD

**Issue by HolgerJeromin** [osmandapp/Osmand#3715]
I activated `fixme=` and `notes=` in osmand (via the details option osm-mapper assistant). It showed me the `fixme` value of this osm way:
https://www.openstreetmap.org/way/286059120
But in the details view there is an wrong url shown:
http://www.openstreetmap.org/node/26333761053

I have no idea where the number is coming from. It is not the id of the way itself, not an id of a node of the way and even not the changeset id.

**Comment by HolgerJeromin** [comment]
The normal poi view is sometimes buggy, too. 
http://www.openstreetmap.org/way/27388264
Is linked as 
http://www.openstreetmap.org/node/27388264

And most meta data is missing. No fee, no website, only the name is shown.

**Comment by xmd5a2** [comment]
Observation: some big objects can't be selected from map directly. Address search context menu is opened, but in this case osm link is present, but it points to node not way. 27388264 is park osm id.
![screenshot_2017-05-23-23-04-05](https://cloud.githubusercontent.com/assets/5829014/26374005/5f1eb07e-400c-11e7-8d29-a6eeaaede1e5.png)

**Comment by vshcherb** [comment]
The issue that we can't distinguish big polygon ids from node ids today. The most difficult part to keep backward compatibility of the map data, so we need to be very innovative in order to fix this issue and don't break maps for existing installations.

**Comment by vshcherb** [comment]
Duplicate #3684 the link should be fixed now.
