### ISSUE TITLE
Add route points to map markers function removed from myplaces/my tracks in version 2.6

### ISSUE THREAD

**Issue by MaxC70** [osmandapp/Osmand#3717]
Hi, 
I'm using OsmAnd on my Sansung S3 mini (GT-I8200), with Android 4.2.2.

In version 2.5, in my places-my tracks section, there was a flag that allowed to add route points to map markers. 
It was a very useful feature that allowed to plan and follow the gpx routes.
Is it possible to reintroduce it in version 2.6 too?
Thank you,
MaxC.

**Comment by vshcherb** [comment]
It has been moved to 3 points (3 dots on top)
