### ISSUE TITLE
InAppBillingService not available

### ISSUE THREAD

**Issue by Thunichgud** [osmandapp/Osmand#3718]
Since OSMand+ V2.6.1 (also in 2.6.2 and 2.6.3) I get an error message when I open the map management:
"Problem setting up in-app billing: lab result: InAppBillingService not available (response: -1009: Subscriptions not available)"
In previous versions I've never got this message. Downloading of maps ist still working without problems with one exception:
When I try to download the new "water depth map" the OSMand app closes itself immediately. So I can't download this new map.
For testing purposes I reinstalled the version 2.5.4 => no error message. But after updating again to version 2.6.3 the error message returned again. Obviously this problem is part of OSMand.

Samsung Galaxy S4, 
CyanogenMod 12.1 (Android 5.1.1), 
rooted, 
OSMand+ 2.6.3, 
no OSMand-Live account, 
no GoogleApps or -Services installed

**Comment by Thunichgud** [comment]
Why closed without any comment ? It's a real problem !!

**Comment by Zahnstocher** [comment]
It was closed with a commit:
https://github.com/osmandapp/Osmand/commit/31bf65bb119abecd8888a9f7e8cce1d7b7c1623e
It should be fixed.

**Comment by beatnickgr** [comment]
I have the same problem since the 2.6.3 update.
With 2.6.2 it was working fine.
I'm running Fairphone Open 17.03.0

**Comment by vshcherb** [comment]
That was closed with a commit https://github.com/osmandapp/Osmand/commit/31bf65bb119abecd8888a9f7e8cce1d7b7c1623e

**Comment by vshcherb** [comment]
Just to confirm every user that observes doesn't have Google Play? How the app was installed?

**Comment by beatnickgr** [comment]
No google accout, i have downloaded from F-Droid.

**Comment by offa** [comment]
Same issue here (v2.6.3 – F-Droid).

**Comment by TimoKramer** [comment]
Same Problem here without playservice and Android 7.1 and Land 2.6.3

**Comment by Zahnstocher** [comment]
I think it is fixed in 2.6.4 or 2.6.5, but F-Droid does only provide 2.6.3.

**Comment by offa** [comment]
From to [F-Droid Osmand Wiki](https://f-droid.org/wiki/page/net.osmand.plus):

> ### 2.6.5
> 
> We can't build this version: The build for this version was manually disabled. Reason: doesnt build, submodules issue
> 
> Version code: 265
