### ISSUE TITLE
Rendering of UNESCO World Heritage

### ISSUE THREAD

**Issue by kreuzschnabel** [osmandapp/Osmand#3722]
Using OsmAnd+ 2.6.3, Android 6.0.1, standard maps issued by OsmAnd.

I noticed a few days ago that the UNESCO World Heritage Upper Middle Rhine Valley (http://www.openstreetmap.org/way/246602883) is rendered entirely in a [pink tone](https://www.pic-upload.de/view-33062965/Screenshot_20170424-175315.png.html) in some important zoom levels.

Since that pink ink is covering (i.e. suppressing) any other area rendering, such as landuses, naturals, riverbeds and lakes, usability of the map rendering is severely impaired by this behaviour.

That area might be outlined in a modest way but not tinted all over. 

--ks

**Comment by xmd5a2** [comment]
Do you use vector or raster maps?

**Comment by xmd5a2** [comment]
Try using "OsmAnd" or "Topo" rendering style. These styles doesn't have such issue. Anyway, I'll fix it.
