### ISSUE TITLE
Live monitoring visual indication

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#3723]
In the menu of the widget "GPX record" you can start or stop tracking, but nowhere on the screen there are indicators of this. If it is necessary to temporarily stop, then it is very easy to forget about it. I propose to add some noticeable glow to "recording" icon on the widget.

**Comment by vshcherb** [comment]
A bit more clarification is needed

**Comment by vshcherb** [comment]
Dialog when we start online tracking from Widget is not needed (to double check)

**Comment by vshcherb** [comment]
Fixed with icons
