### ISSUE TITLE
Live monitoring does not use settings for filtering GPX points

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#3724]
such as save_track_min_distance, save_track_precision, save_track_min_speed. Thus, raw data is sent. I suggest that live monitoring use these settings by default, or let's introduce another option for this case.

**Comment by sonora** [comment]
Chances are in your tests Live monitoring is using the settings for our default (Browse map) profile, **which we cannot edit anywhere**? I am still hoping we can convince Victor to make all recording filter settings global again, as you and I had already suggested in another issue, but Victor had reservations. :)

**Comment by xmd5a2** [comment]
@sonora, I merged you pull-request https://github.com/osmandapp/Osmand/pull/3437 before release. So not, this behaviour was caught in bicycle profile.

**Comment by sonora** [comment]
Ah, true, I already forgot. Thanks, Leonid!
