### ISSUE TITLE
Wrong routing (unexpected U-turn via the street)

### ISSUE THREAD

**Issue by shadow-identity** [osmandapp/Osmand#3725]
Hello,
I have Nexus with Android 7.1.2, Osmand+ 2.6.3

I'm using your offline maps and I'm also a subscriber of OSM Live.

This is Brest, Belarus. I've faced with wery strange offline car routing issue. 
You can see it at position on the screenshot.

![screenshot_20170430-014434](https://cloud.githubusercontent.com/assets/1223112/25559694/8cf38924-2d48-11e7-94b0-46986c592852.png)

It is strange, also, that it didn't want me to make a turn back to Lenina street on the first street (Kommunistichnaya), but only near Gogalya street, 3.

![screenshot_20170430-020227](https://cloud.githubusercontent.com/assets/1223112/25559732/281332f6-2d49-11e7-941b-14d1b51b5280.png)

**Comment by xmd5a2** [comment]
Looks like it is because of incorrect U-turn relation https://www.openstreetmap.org/relation/5995237 . If I delete it locally then route is calculated correctly.

**Comment by shadow-identity** [comment]
I agree with you that this relation is incorrect, just fixed it. But for me it is strange that this relation causes this routing trouble.

**Comment by shadow-identity** [comment]
OK, another problem, in Hrodna, Belarus: geo:53.66868,23.82164?z=17
Both YOURS and OSRM builds correct route, but in native OsmAnd routing I see U-turn on the wrong street. I can't find any incorrect relations here.
![screenshot_20170501-150139](https://cloud.githubusercontent.com/assets/1223112/25579390/3b6f7b2e-2e80-11e7-9f80-70d7cba366ca.png)

**Comment by xmd5a2** [comment]
This is because of https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#L480 . OsmAnd tries to avoid traffic signals and considers two traffic lights in a row by different entities. This must be corrected.

**Comment by xmd5a2** [comment]
Also I don't think that tagging whole roundabout as primary_link is correct. There are penalties in routing.xml to prevent changing road class to lower https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#L204

**Comment by raindropsfromsky** [comment]
I also faced this problem on the latest nightly dated 29th April: While going along a Primary road (dual highway), OsmAnd asked me to take a U-turn, come back almost 500m, take a U-turn again, and then continue on the same half of the road.

This happened approximately in the middle of a 200+ km journey, and probably the fast algorithm had failed while calculating the route; and the slow algorithm had done the job. Not sure.

**Comment by homersimpsons** [comment]
For the @shadow-entity problem, maybe you can add penalty for entering and/or leaving a roundabout?
