### ISSUE TITLE
Live monitoring issue when internet connection is lost

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#3726]
During the trip with live monitoring enabled, I drove into a place where the cellular signal disappeared or only GPRS was available. However, I'm not sure if this was the reason for the next one. After I returned home, I found that OsmAnd kept saving track for an extremely long time (the action was started manually). Also I found out that my position in the Traccar is lagging behind the current for 2 hours. Judging by the log track, messages with coordinates come still. My position is moving, but the smartphone with OsmAnd is not. Looks like OsmAnd sends these messages with a huge lag.

**Comment by vshcherb** [comment]
The setting was introduced to send only last 5 minutes location in that case it will not annoy by sending missing hours. Http requests don't allow to bundle location, so for every point single http request is issued and that's why it slow to send 1000 missing locations.
