### ISSUE TITLE
30 strings in strings.xml lost whitespace

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#3729]
Something happened recently to exactly 30 strings in the file osmand/res/values/strings.xml that are available for translation via weblate. They seem as they have lost some whitespace and line breaks, so are then now mashed together. See e.g. string osmand_plus_extended_description_part2 and compare to the previous version. I can't see anything like this in the file history. Maybe weblate or some other mechanism mangled those files without leaving a trace in the history?

**Comment by vshcherb** [comment]
Strange but looks like quite late to investigate

**Comment by aceman444** [comment]
The strings are still in the same state so it would be useful to investigate whether that change was intentional and appear properly where they are displayed.

**Comment by vshcherb** [comment]
I didn't notice anything strange in the OsmAnd UI so far. Strings like osmand_plus_extended_description_part2 are used to combine and put to Google Play description manually, so if they change they are not automatically propogated.

**Comment by aceman444** [comment]
So why did they change? There must be a reason. The change looks like somebody ran a tool on the strings to remove trailing spaces on lines and remove some line breaks.
You should be able to simulate the process of putting osmand_plus_extended_description_part2 to Google Play manually and see if the results are correct with this damaged string now.

**Comment by aceman444** [comment]
This but was closed improperly.
Only recently have the strings been fixed back to the correct formatting, so the bug is fixed now (not in July 2017). So I was right.
