### ISSUE TITLE
Life rings as POI

### ISSUE THREAD

**Issue by rindlerblabla** [osmandapp/Osmand#3734]
Trying to add life rings as POIs for uploading to OSM but they're not in the list under 'emergency'.  Same when viewing POIs on the map. Is it possible to add?

http://wiki.openstreetmap.org/wiki/Tag:emergency%3Dlife_ring

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/61cac946722d5b69cbc406a4971320de14685325
