### ISSUE TITLE
Organic food incorrectly displayed

### ISSUE THREAD

**Issue by verdulo** [osmandapp/Osmand#3737]
If you click on properties of shop selling organic products, the wrong string is displayed: "poi_organic": "poi_organic_yes"; so it looks: "Organic food: Organic food: yes". Only the string "poi_organic_yes" should be displayed. Similar problem occurs with strings poi_organic_no/only.

**Comment by xmd5a2** [comment]
Fixed (english and russian phrases in this commit) https://github.com/osmandapp/Osmand/commit/77d0548b5e33d6b2ca1f9eec21a824a759bb199e

**Comment by verdulo** [comment]
Is the string "poi_health_specialty_palliative_medicine_yes" correct?

Currently it's "Health specialty: palliative medicine", shouldn't it be "Palliative medicine"?
