### ISSUE TITLE
Traffic circle bug in left-driving countries

### ISSUE THREAD

**Issue by aprokop** [osmandapp/Osmand#3741]
Just wanted to report an issue I've encountered using OsmAnd+ Android application. When in the car mode in OsmAnd+ navigation, the top left tooltip shows the next change (turns and such). I saw that in a left driving country (Cyprus in my case), it incorrectly showed going through circle in counter clockwise mode while it should have been a clockwise mode. I am not certain whether the exit it showed was correct or not.

Unfortunately, I'm no longer in the left-driving country, so cannot create the screenshots.

**Comment by vshcherb** [comment]
The issue was fixed in 2.6 with automatic detection of lefh driving countries before it was a manual switch (settings).
