### ISSUE TITLE
Turn on device screen (if off)

### ISSUE THREAD

**Issue by Goodingn** [osmandapp/Osmand#3743]
Much as I like this feature, why do I have to turn the screen off for this functionality to 'kick in'.

I need as little interaction as possible with the phone to get my preferred navigation experience.  Once I've pressed 'Go', that should be it- why do I have to then turn the screen off?

The screen turns off after a period when a navigation point has been reached (or thereabouts)- this should also happen from pressing Go- it should be on for a short while, then turn off, and then back on again as navigation points are reached.

Also, if I want to 'just check' what's going on and press the screen on button, I don't want to have to remember to turn the screen back off again.

Further- turning the screen off on my phone requires squeezing the phone, to get a button on the side of the phone to press, which is annoying in the car, but if the phone is in some kind of pouch type mounting on a bicycle, the off button is often inaccessible (I know a person who glues a ball-bearing into the pouch at a position perfectly lined up with a power button that is otherwise flush with the phone side, so a squeeze of the case presses the ball bearing into the power button).  Turning the screen on requires a press of a front facing button.  On previous phones without a front facing button, as using a side power button is pretty hit-and-miss or impossible, fighting with it once to get the screen on is bad enough, but again to turn it off?

I also recognise that after a navigation point the screen turns off 'quite soon' and this may not be desirable after pressing 'Go' or after turning the screen on to 'just check'.  Could Osmand not use the android screen timeout function more readily here?  Or have a separate setting for a timeout value for turning the screen off after an interaction with the phone?

Cheers,

**Comment by oliv3r** [comment]
This seems to be related to #4525 or vice versa, but that you need to turn the screen off for the feature to kick in only makes sense. If your screen is on, it doesn't have to turn on and shouldn't turn off, as this makes it very annoying for users who do want to screen on normally, but only get the screen-up when the screen was actually off (to save battery for example). Ideally this could be an option (keep screen always on).

**Comment by kousu** [comment]
Where is this option? I have OsmAnd 3.0.3 and I can't find it anywhere. Is this still relevant?

On my version the screen stays *on* whenever the map is in view (so, almost always, unless I switch entirely out of the app or open the global settings for some reason).

I really don't like this behaviour. I can see why you'd want this in car mode---where you can keep your device charging, usually---but for cycling to hiking it makes it way too easy to accidentally drain the battery and leave me stranded. I echo OP's observation that you shouldn't have to remember something special when you just want to check in on your surroundings; that's a kind of fail-open bug for us.

I propose OsmAnd just allows the normal android screen timeouts to kick in by default, and moves Keep Screen On to a prominent checkbox on the per-profile Configure Screen settings, and then that the feature OP is talking about becomes just a "Wake On Waypoint" checkbox, ideally just below Keep Screen On, which is a short handler that tries to wake the screen when a waypoint is passed (and if the screen is already on, no big deal, it just passes), and that should be active upon turning on the checkbox, not with the current secret konami code trigger.

With those two options, people travelling by car who want the screen always on for reference will choose choose Keep Screen On; if they want to dim their cabin they can press their power button. If they want the behaviour OP likes they can disable Keep Screen On but enable Wake On Waypoint. For cyclists and hikers, we can leave both disabled.

And also, is there any way to disable Keep Screen On in 3.0.3? I would really appreciate knowing that.

**Comment by scaidermern** [comment]
This option is located under settings -> navigation settings -> profile -> Turn screen on.

**Comment by oliv3r** [comment]
was using it last week or so and still happens

**Comment by Goodingn** [comment]
Still no option for screen to turn itself off? I can't be pressing the screen off button after every turn for this functionality to work??

**Comment by scaidermern** [comment]
> Still no option for screen to turn itself off? I can't be pressing the screen off button after every turn for this functionality to work??

After every turn? The screen should turn of automatically after the configured time *if* it turned on automatically before the turn. If not this is a separate bug and doesn't belong here.
