### ISSUE TITLE
Maxheight is ignored in offline routing

### ISSUE THREAD

**Issue by Carnildo** [osmandapp/Osmand#3744]
**What version of OsmAnd are you using, on what device?**

OsmAnd 2.6.2 on a Nexus 7/Android 6.0.1

 **Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps**?

Offline maps

 **If you use offline maps, tell us the exact name of the map file where the routing issue occurs, and its edition date.**

United States of America Washington, standard map, March 31, 2017 edition

 **Tell us whether you have used OsmAnd's in-app offline routing, or any online routing provider like YOURS, OpenRouteService or OSRM.**

In-app offline routing

 **What routing profile is choosen in OsmAnd app (car, bike or pedestrian)?**

Car, with a height limit of 4 meters.

 **Please specify as exactly as possible the start and end point of your route. If possible, tell us city name and street name for each. Also a Permalink from openstreetmap.org can be helpful.**

https://www.openstreetmap.org/#map=18/47.65544/-117.41944
In Spokane, from the intersection of 1st and Stevens (47° 39.39606, -117° 25.17334) to the intersection of 2nd and Stevens (47° 39.27109, -117° 25.17105) 

 **Tell us your expected routing, and how OsmAnd routes.**

The Stevens Street tunnel under the railroad has a clearance of 11 feet 6 inches, which is significantly less than four meters.  I'd expect the routing to send me either one block west, to the Howard Street tunnel with a clearance of 13 feet 10 inches, or two blocks east, to the Browne Street tunnel with a clearance of 14 feet 1 inch.

Instead, it sends me via the direct route, straight down Stevens Street.

**Comment by xmd5a2** [comment]
Confirmed. Works only in java routing.

**Comment by xmd5a2** [comment]
Test added

**Comment by vshcherb** [comment]
Fixed https://github.com/osmandapp/OsmAnd-core/commit/938294fbe5c0e80aa780fe380897b05e08fb2f5f
