### ISSUE TITLE
In current (2.6.3) osmand+ avnotes not write compass direction to images

### ISSUE THREAD

**Issue by progserega** [osmandapp/Osmand#3747]
1. Включаем avnotes плагин
2. Настраиваем плагин, чтобы по-умолчнию делать фото и делать фото средствами osmand.
2. Калибруем компас в GPS-status
3. фиксируем наличие направления на карте (синий сектор круга возле точки местоположения на карте)
4. Делаем фото-замеки, поворачиваясь в разные стороны.
5. Сгружаем, смотрим в josm - направления нет.

Немного ранее, более старой версией osmand  - направление записывалось.
Во вложении примеры без и с (старой версийе osmand) записанным направлением.

On english:
1. Turn on the avnotes plug-in
2. Configure the plugin to make a photo by default and take photos using osmand.
2. Calibrate the compass in the GPS-status
3. fix the presence of direction on the map (the blue sector of the circle near the point of location on the map)
4. Take photo-notes, turning in different directions.
5. We load, we look in josm - there is no direction.

A little earlier, an older version of osmand - the direction was recorded.
In the attachment, examples are without and with (old version of osmand) written direction.

**Comment by progserega** [comment]
![5 ek wz -- 1](https://cloud.githubusercontent.com/assets/1297163/25776963/4706092c-3311-11e7-9bf5-51dc058af937.jpg)
![5 ozmi42-- 1](https://cloud.githubusercontent.com/assets/1297163/25776964/470db140-3311-11e7-8560-cd9f0dd58531.jpg)
![5 ozmi42-- 2](https://cloud.githubusercontent.com/assets/1297163/25776967/470eca6c-3311-11e7-8618-e3c6a14850d6.jpg)
![5 ozmkhk-- 1](https://cloud.githubusercontent.com/assets/1297163/25776965/470e3fde-3311-11e7-8d9f-f81367113d6c.jpg)
![5 ozmkhk-- 2](https://cloud.githubusercontent.com/assets/1297163/25776966/470ebb76-3311-11e7-8ffc-fcd830ab8e4f.jpg)


# exiftran -d *.jpg |grep "jpg\|Direct"
5~eK~wz~--.1.jpg
      0x0010  GPS Image Direction Reference  T
      0x0011  GPS Image Direction            33.4099999
5~OzMi42--.1.jpg
      0x0010  GPS Image Direction Reference  T
5~OzMi42--.2.jpg
      0x0010  GPS Image Direction Reference  T
5~OzMkhk--.1.jpg
      0x0010  GPS Image Direction Reference  T
5~OzMkhk--.2.jpg
      0x0010  GPS Image Direction Reference  T

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/pull/4130
