### ISSUE TITLE
Area flooded with water

### ISSUE THREAD

**Issue by quelbs** [osmandapp/Osmand#3749]
When displaying an area near to Arezzo (IT) at zoom level 10 most of the area is displayed as water.
http://osmand.net/go.html?lat=43.610718&lon=12.081668&z=10

![screenshot_flooding_arezzo_z10](https://cloud.githubusercontent.com/assets/570222/25792909/c3a6d4bc-33c9-11e7-8ec1-6844bcf83b3f.png)

**Comment by njohnston** [comment]
Possibly related to #2805 and #3596.

**Comment by quelbs** [comment]
I created this as a new issue as no shoreline seems to be invoveld in this problem and it is in the mainland.

**Comment by xmd5a2** [comment]
Strange, but I can't reproduce issue

**Comment by PaulStets** [comment]
You can reproduce the issue here:  http://osmand.net/go?lat=-30.303083&lon=153.12384&z=16
Map: Australia New South Wales.
![screenshot_2017-06-15-19-35-15](https://user-images.githubusercontent.com/20681525/27186483-2b4eebf0-51f1-11e7-8714-fad83a742b83.png)

**Comment by xmd5a2** [comment]
https://github.com/osmandapp/Osmand/issues/4224

**Comment by xmd5a2** [comment]
https://github.com/osmandapp/Osmand/issues/4337

**Comment by xmd5a2** [comment]
https://github.com/osmandapp/Osmand/issues/4383

**Comment by jaller94** [comment]
Here you have a node that causes an asphalt flood between Vancouver and North Vancouver.
https://www.openstreetmap.org/node/39583708
In #4383 I included more information how it can not only be a water flood but also an asphalt flood.

**Comment by PaulStets** [comment]
Another place where this occurs: http://osmand.net/go.html?lat=51.88853&lon=0.85190&z=12

**Comment by jaller94** [comment]
Cannot reproduce in version 2.7.5

**Comment by vshcherb** [comment]
Issue spin off
https://github.com/osmandapp/Osmand/issues/4516
Original issue is not reproducible
![screenshot_20171003-101157](https://user-images.githubusercontent.com/1042025/31115879-49e675ae-a824-11e7-8dc9-878d66d4b68f.png)

**Comment by quelbs** [comment]
Still flooding for me with Osmand 2.7.0#22719M on zoom level 10
![screenshot_20171004-stillflooding](https://user-images.githubusercontent.com/570222/31164529-e56fd3bc-a8e7-11e7-8870-e106382965ce.png)

**Comment by jaller94** [comment]
Flooding next to Arezzo, Italy is also still around in 2.7.5, however, hard to reproduce. I only saw it once in 4 minutes of trying to find fauuty viewports.
