### ISSUE TITLE
Battery issue in 2.6

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#3751]
Our user explains the situation:

When OSMAnd is run on the display it drains 1% of battery charge per minute if the GPS is switched on. As soon another application is on the display (GPS still on and OSMAnd running in the background) the battery drain is reduced to the normal 10% per hour, even though the application on the display is using GPS as well. This is happening with or without track recording. As soon OSMAnd is on the display and GPS is on the battery drain at the high rate starts. It does not make a difference if the GPS is locked or not. If GPS is switched off there is no battery drain from OSMAnd, only of the display. Routing is not active. The Android Energy Manager shows that OSMAnd is taking about 40% of the energy, the display is taking about 20%. Normally display 70%, OSMAnd 6%..

I am not sure when that problem started to occur. But I noticed the problem first with the update to OSMAnd 2.6.2.

**Comment by vshcherb** [comment]
Good to know let's if we get other reports about 2.6 or it could be just another suspect that was not confirmed.

**Comment by pebogufi** [comment]
Can't provide exact values, but also observed severe loss of battery power in new versions when gps was on, most cases without recording.
Used versions in last weeks:
2.7.0#21411, 21321, 21293, 21296
Peter
