### ISSUE TITLE
Pin point unavailable roads during trip

### ISSUE THREAD

**Issue by Siltaar** [osmandapp/Osmand#3754]
When following directions, it often happen that a road reveals itself as temporarily unavailable (punctual event in a city, remaking of the road-surface by workers…).

It would be great to be able to pin a road on the map, when an unavailable road is discovered, to mark it as so (for 100m, 1k or 10km for instance), and avoid it when calculating new directions.

Without this feature, OSMand keeps getting you back to the unavailable road for the 5 next tries, and even longer after if did not manage to get far enough from the unusable road.

**Comment by vshcherb** [comment]
It is already available though you might not see it immediately. If you pin the point you might see it in context menu (3 dots) - Avoid road.
