### ISSUE TITLE
Bug. Empty node when using quick action

### ISSUE THREAD

**Issue by rindlerblabla** [osmandapp/Osmand#3758]
Have created quick actions for compressed air and bicycle parking but when uploading them they're just empty nodes. If there're more tags added (e.g. bicycle_parking=racks) only that tag can be seen. 

Made a quick action for a 'tree' and it worked just fine. Is this a 'transport' problem?

**Comment by xmd5a2** [comment]
Confirmed

**Comment by vshcherb** [comment]
I guess workaround is not to use POI type so far (just specify tag/value exactly). Clearly that's an issue and it will be fixed.

**Comment by rindlerblabla** [comment]
Thanks!

**Comment by pos-ei-don** [comment]
How can i find ALL emty nodes, i created using this tool? There should be several hundred empty nodes i created using this....

**Comment by vshcherb** [comment]
May be you can see all your changes? It is better to ask experts in OSM I'm afraid.  The History view is something to begin with

**Comment by pos-ei-don** [comment]
This is the http://overpass-turbo.eu/ - Code to find those empty nodes so every body can correct them.
Big thanks to Owla!
```
[bbox:{{bbox}}];
rel; > -> .r;
way; > -> .w;
(( node(if:count_tags()==0)(user:"OSMuserName"); - node.r; );  - node.w; );
out meta;
```
