### ISSUE TITLE
adding OSM notes very slow in 2.6

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#3759]
In the newest Osmand 2.6 when adding new OSM notes (offline, without uploading them yet) it often takes very long. I write the text of the Note and then wait until the message appears saying "note was added to the storage" and the circle point appear on the map. The bug is, in this version this may take even a MINUTE. That didn't happen in older OsmAnd, the adding was mostly instant.
Note that OsmAnd UI is NOT frozed white it is doing the saving. I can operate it normally and even add more OSM Notes and then later they get saved all at once as a batch. It looks like they are accumulating on a separate thread but that thread is often stuck waiting on something but it eventually finishes. The problem is my OsmAnd often restarts when taking Photo notes or just switching to other simple app (maybe low RAM?) so I worry I could loose OSM Notes not yet saved when the restart happens.

>What version of OsmAnd are you using, on what device and Android/iOS version?
OsmAnd 2.6.3, Android 5.0, 1GB RAM.

>Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?
Offline maps only.

**Comment by rbovard** [comment]
FYI it's fine on my OsmAnd+ 2.5.3 (Android 7.1.2)

Maybe something related to your device?

**Comment by vshcherb** [comment]
A minute is something really slow. Is it possible that your storage is too big. Can you try it please on fresh installation without data. We have several buidls http://download.osmand.net/latest-night-build/ so you can try to install a new one without deleting previous.

**Comment by aceman444** [comment]
Yes, I have now found it happens only when I have the "OSM notes (online)" layer enabled AND the network is NOT available (I have wifi and mobile data turned off most of the time). Disabling the layer makes the OFFLINE Notes saved at normal speed again (immediately).

So the fix would be:
1. can you make OsmAnd detect there is no network quickly and skip waiting/doing anything in the "OSM notes (online) layer? E.g. Google play store app detects missing network immediatelly.
2. can you move doing any work (also fetching data from network) for the "OSM notes (online)" layer as the last job after all internal offline data (including POIs, offline Notes, etc.) was rendered first? Even with network available, the data can arrive with unexpected delays so other local tasks should not be blocked by waiting on online data.

**Comment by vshcherb** [comment]
Here we also need to investigate symptoms from #3857 they might have the same cause.

**Comment by scaidermern** [comment]
I've experienced the same issue multiple times, usually when adding notes while or after moving for a long time. I already reported it in https://github.com/osmandapp/Osmand/issues/3898#issuecomment-314126648 since I thought it could be caused by the same problem. But maybe not.
