### ISSUE TITLE
displaying POIs on map very slow in 2.6

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#3760]
1. Click search, categories, choose e.g. Accommodation.
2. Results are shown.
3. Then click "show on map".
4. After a long while the POIs (orange circles) are shown. This may take up to a minute.

This is much slower than previous OsmAnd versions. Also consider OsmAnd already had those results (from the current location) found in step 2. Then why does it not show them immediatelly? Scrolling away from the location and having to search for new POIs would be understandable to take some time (and it does). 

>What version of OsmAnd are you using, on what device and Android/iOS version?
OsmAnd 2.6.3, Android 5.0, 1GB RAM.

> Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?
Offline maps only.

**Comment by rbovard** [comment]
FYI it's fine on my OsmAnd+ 2.5.3 (Android 7.1.2)

Maybe something related to your device?

**Comment by vshcherb** [comment]
I think something happened with your device cause we can't reproduce it.

**Comment by aceman444** [comment]
Yes, I have now found it happens only when I have the "OSM notes (online)" layer enabled AND the network is NOT available (I have wifi and mobile data turned off most of the time). Disabling the layer makes the POI speed fine again.

So the fix would be:
1. can you make OsmAnd detect there is no network quickly and skip waiting/doing anything in the "OSM notes (online) layer? E.g. Google play store app detects missing network immediatelly.
2. can you move doing any work (also fetching data from network) for the "OSM notes (online)" layer as the last job after all internal offline data (including POIs, offline Notes, etc.) was rendered first? Even with network available, the data can arrive with unexpected delays so other local tasks should not be blocked by waiting on online data.
