### ISSUE TITLE
[OSM Editing] Inconsistency in add POI UI

### ISSUE THREAD

**Issue by rbovard** [osmandapp/Osmand#3761]
I noticed an inconsistency in add POI UI:

![image](https://cloud.githubusercontent.com/assets/4549666/25885779/b5a53c72-355a-11e7-8d39-09b93f074d83.png)

* Top: `tourism` `fontain`
* Bottom: `amenity` `fontain`

It's confusing since [tourism](https://wiki.openstreetmap.org/wiki/Key%3Atourism) is a valid key and if we don't switch to second tab (*Etendue*), we could think the POI will be tagged as `tourism=fontain`.

I don't know if it's a simple translation issue or a more deeper one.

**Comment by vshcherb** [comment]
Historically fountain are in amenity OSM category. POI type and poi subtype we do on our own UX investigation. So inconsistence is fine.
