### ISSUE TITLE
One handed zooming using volume buttons

### ISSUE THREAD

**Issue by tobydickenson** [osmandapp/Osmand#3763]
For hiking navigation I normally use Orux maps, but Osmand is getting increasingly close to replacing it.

One comparative disadvantage of Osmand is the difficulty of one-handed map zooming. Pinch zoom, and the + and - buttons are only convenient if you have a second hand, or something else to support the device. Orux allows the map to be zoomed using the volume hard buttons, which make it easy to browse the map one-handed while hiking. The same feature in osmand would be useful.

Other menus require a second hand too, but those all get used much less frequently than map browsing.

I am surprised to see that Osmand previously had this feature, but it was removed by #3491, because it caused confusion. I agree any volume button zoom feature should be optional, and off by default.

**Comment by vshcherb** [comment]
There was confusion with navigation volume, the feature left only in Accessiblity plugin, it is not a good place cause you also get some unexpected features from it. We might need to move that setting somewhere to general settings.

**Comment by sonora** [comment]
Please note that we have also the slide zoom: Double tap on the map, but upon the second tap leave the finger down and slide up or down the screen.

**Comment by jej** [comment]
"Double tap on the map, but upon the second tap..."

Ohhh, thanks for this trick... quite handy. It will save my life and my mobile when cycling......

I feel that intuitively I would prefer to zoom in when going up and out going down (like piloting a plane with a joystick, pushing to go down).

**Comment by tobydickenson** [comment]
I was initially sceptical that this gesture would be too complicated to use effectively one-handed while hiking, but, having tried it, can confirm it works very well.

**Comment by sonora** [comment]
Yes, I like it, too.

Any agreement or strong feeling that we should reverse the slide up/down behavior?

**Comment by tobydickenson** [comment]
Google maps implements the same gesture, in the same direction. So simply reversing the direction seems like a bad idea.

An idea which might be an improvement: Behave as if there was a pinch-zoom with an "imaginary second finger" in the middle of the screen. So a double-tap followed by dragging out from the centre would zoom in. A double-tap followed by dragging in towards the centre of the screen would zoom out. A double-tap followed by a rotation around the centre point would rotate the map.

**Comment by jej** [comment]
Yes I agree the direction is just a feeling, not a real argument...

I like your proposal concerning the virtual finger in centre. It would disambiguate the gesture. It could even be drawn with 3 transparent dots so that it's self explicit. A small one for centre, and two bigger dots under the finger and it's symmetric position regarding centre.
J.

Le 25 mai 2017 11:52:32 GMT+01:00, tobydickenson <notifications@github.com> a écrit :
>Google maps implements the same gesture, in the same direction. So
>simply reversing the direction seems like a bad idea.
>
>An idea which might be an improvement: Behave as if there was a
>pinch-zoom with an "imaginary second finger" in the middle of the
>screen. So a double-tap followed by dragging out from the centre would
>zoom in. A double-tap followed by dragging in towards the centre of the
>screen would zoom out. A double-tap followed by a rotation around the
>centre point would rotate the map.
>
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/osmandapp/Osmand/issues/3763#issuecomment-303982113

J.

**Comment by sonora** [comment]
Ok, if we are aligned with the google UI I think let's close this issue.

If you feel like you want to suggest an overall new behavior for the gesture (or a different gesture), please open a separate suggestion so it can be discussed. (I personally feel that what we have is both conventional and sufficient.)

**Comment by tobydickenson** [comment]
> close this issue

Agreed. Conventional and sufficient. But hard to discover, so I've raised #3829

**Comment by TroyWolf** [comment]
I'm really late to the table, but voting for option to enable map zooming with volume buttons. I will be using OsmAnd primarily for motorcycle adventures and will have the sound turned off...but want to be able to zoom the map easy with gloves. Thanks for the tip about the double-tap and hold zooming!

**Comment by flamingm0e** [comment]
> I'm really late to the table, but voting for option to enable map zooming with volume buttons. I will be using OsmAnd primarily for motorcycle adventures and will have the sound turned off...but want to be able to zoom the map easy with gloves. Thanks for the tip about the double-tap and hold zooming!

Same here.  I would love to see this feature as an option, like Locus has.

**Comment by martinstingl** [comment]
Please reopen this issue as many people are requesting the Volume Button Zoom feature, including me.

**Comment by dmpr0** [comment]
@martinstingl You can find this option in Settings > Profile > General settings.
