### ISSUE TITLE
topo style omits bridleways

### ISSUE THREAD

**Issue by tobydickenson** [osmandapp/Osmand#3764]
http://www.openstreetmap.org/#map=16/51.0174/-1.2461

Screenshots of default and topo style of the same location. Topo style does not draw "Featherbed Lane" highway=bridleway

(I have few topo style glitches to report; I hope separate issues is the preferred way to report them)

![screenshot_20170511-112404](https://cloud.githubusercontent.com/assets/292492/25944969/17bfa36a-363d-11e7-8a26-09505869f5b8.png)
![screenshot_20170511-112449](https://cloud.githubusercontent.com/assets/292492/25944975/1b2b26dc-363d-11e7-995a-40ece1efac01.png)

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/cc6fef60693561f1d92571267077b1448f6b23b6
