### ISSUE TITLE
topo style - too many text labels

### ISSUE THREAD

**Issue by tobydickenson** [osmandapp/Osmand#3765]
https://www.openstreetmap.org/edit#map=15/51.0225/-1.2374

The topo style becomes overwhelmed by rendering the name of every individual patch of woodland.

Screenshots show the same area in default and topo style. The default style does a good job of only labelling the largest area of woodland, and other labels for smaller woodland progressively appear on higher zoom levels. The topo style labels **every** woodland at zoom level 13 or higher.

![screenshot_20170511-112553](https://cloud.githubusercontent.com/assets/292492/25945189/ec8dd10c-363d-11e7-8bce-8c22e0d2647e.png)
![screenshot_20170511-112615](https://cloud.githubusercontent.com/assets/292492/25945195/f0a6e102-363d-11e7-8b65-dc0b3de9fea4.png)

**Comment by vshcherb** [comment]
Not sure if it is bad.

**Comment by tobydickenson** [comment]
The default style is behaving as if there is a minimum size for the area being labelled, but I cant see where that is controlled in the rendering xml. I'm keen to provide a patch if you can point out the appropriate mechanism.

**Comment by xmd5a2** [comment]
Looks like this commit solves issue (but personally I prefer more details)
https://github.com/osmandapp/OsmAnd-resources/commit/d912b8956d07c1f3d96ebd8eb256271f9496431d
![screenshot_2017-05-23-21-34-04](https://cloud.githubusercontent.com/assets/5829014/26370901/e04ef3e4-4001-11e7-829d-d925aed1d0aa.png)
