### ISSUE TITLE
Show Ref of motorway-junctions (exit)

### ISSUE THREAD

**Issue by osmvermesser** [osmandapp/Osmand#3771]
It would Mord helpful to show (say) the REF when motorways had to leave.

In Madrid it would be more helpful to find the correct exit.

Regads Jan

**Comment by jfburke3** [comment]
You're referring to the exit number?

**Comment by osmvermesser** [comment]
yes - look to https://wiki.openstreetmap.org/wiki/Tag:highway%3Dmotorway_junction#Name_and_number

**Comment by polarbearing** [comment]
Duplicate of #1347

**Comment by vshcherb** [comment]
Yes it is duplicate
