### ISSUE TITLE
Icon when tunnel is coming

### ISSUE THREAD

**Issue by osmvermesser** [osmandapp/Osmand#3773]
When you drive to large cities the street offen very near to the next.

Sometimes then there are tunnels and bridges.

I think it would be helpful to show a tunnel icon when next the way will go into tunnel.

Regards jan

**Comment by sonora** [comment]
Can you please elaborate on why you think this could be helpful? I find no precedence for this in other nav systems. And my first impression is thatt 'bridge or tunnel warnings' would rather contribute to information overflow, particularly in cities with an already high frequency of other notifications and warnings being flashed? Looks like there is not generaly a specific reaction needed from the driver when approaching a bridge or tunnel (lights, perhaps...:) )?

**Comment by vshcherb** [comment]
Tunnel is useful, you need to switch on the light.

**Comment by Angyork** [comment]
Are they referring tunnel or bridge height warning if in a truck?

**Comment by polarbearing** [comment]
Hm I easily realise the darkness and switch the lights on, but I often forget to switch them off at the end.

**Comment by PaulStets** [comment]
Fixed with https://github.com/osmandapp/Osmand/pull/4973

**Comment by osmvermesser** [comment]
nice! 

but i think the distance before the information will show is very short for a good orientation in foreign area!

jan

**Comment by osmvermesser** [comment]
Additional for my comment.

The besteht way will be:
* 400m before Tunnel OR
* before the last possibility to change the way

Jan
