### ISSUE TITLE
OsmAnd crashes when handling many digits in geo intents or seaches

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#3774]
Hi,

I found that OsmAnd crashes when handling geo intents (shared locations) from Telegram messenger. This might be caused by many digits behind the decimal seperator.

Steps to reproduce:

- Open a shared location from Telegram in OsmAnd, or...

    - Alternatively paste the following line into OsmAnd's search box:

geo:27.756198861979026,-15.568285540975442?q=27.756198861979026,-15.568285540975442

- Tap on the resulted button that displays shortened latitude and longitude.

Result: OsmAnd crashes.

Note: OsmAnd won't crash when tapping "SHOW ON MAP" alternatively to the last step.

Found with OsmAnd+ 2.6.3.

**Comment by rindlerblabla** [comment]
Same for me when opening geo locations from Instagram.

**Comment by utack** [comment]
Whatsapp locatin also does that for me

**Comment by vshcherb** [comment]
Fixed after release 2.6.3
