### ISSUE TITLE
Wrong routing in Germany

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#3778]
There's a potentially dangerous routing on a roundabout in Germany. Can that be due to road tags?

http://www.openstreetmap.org/?mlat=51.45461&mlon=6.74103#map=17/51.45461/6.74103

![rsz_screenshot_2017-05-01-21-48-13](https://cloud.githubusercontent.com/assets/12711814/26066587/0dc76b8e-39a0-11e7-9259-1fa1f9c4d08e.jpg)

**Comment by polarbearing** [comment]
Yes. First, routing over roundabout flares can be fixed by adding a turn restriction. Second, the junction is mapped with fake bypasses which are only lanes, providing a mess of road ranking. I'm going to fix the data tonight.

**Comment by polarbearing** [comment]
Roundabout has been remodelled, using turn:lanes and change:lanes. Fake bypasses are removed. 

In the old version, the strange routing was explicable. It followed a road with higher ranking, but avoided a mapped restriction.

**Comment by annasoloviova** [comment]
Thank you for clarifying! A fresh report of the same sort came. User's comment: it is impossible to cross road 37 it is necessary to use road overpass. 
Šířka 49.96928 Délka 15.79891

![screenshot_2017-05-12-23-20-31](https://cloud.githubusercontent.com/assets/12711814/26156044/b3b9552e-3b1d-11e7-8fd8-a96f0d0f4f23.png)

I guess I'll just suggest the users leave an OSM note for this type of issues.

**Comment by stephan75** [comment]
... but I assume that Osmand is the only OSM based routing app that fails on this position. All others will work ok there. Or not?

**Comment by homersimpsons** [comment]
@annasoloviova I think that there should be a turn restriction here :) 
@stephan75 it depends on data processing, for example I think that OSRM use turn angle penalty, then maybe it won't be affected by this type of mapping, in any way there are a lot of fixes to do in OSM (especially for those kind of turn angles, if I remember there is OSMI or a such tool that report sharp angle without turn restriction), but for the major part of the map it's okay :)

**Comment by vshcherb** [comment]
Looks like the issue was fixed.
