### ISSUE TITLE
OsmAnd fails to initialize changed Favorite colors (requires re-start)

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#3779]
Hi,

When changing the color of a Favorites group and switching back to the map, the old color is still displayed for the icon the map. A re-start of OsmAnd is required to have the new color applied for the icons on the map.

Bug found with OsmAnd+ 2.6.3.

Best Regards,
Norbert

**Comment by vshcherb** [comment]
* Also we should not close dialog when we change visibility when we switch "Show on Map" or "Not show on map"

**Comment by dmpr0** [comment]
Hi, what version of Android do you have? On my Galaxy A7 (2016) Android 7, 2.6.3 i can't reproduce this.

**Comment by Norbert80** [comment]
Device is an LG G5 SE running Android 7.0.

I can't reproduce it myself anymore. (Maybe it is one of these problems that sporadically appear and vanish after a re-start...)
