### ISSUE TITLE
Favorite color is retained after moving a Favorite to an other group

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#3780]
Hi,

When moving a Favorite to group with a different color, the old color is retained.

(It looks like OsmAnd saves the color for each Favorite separately although the color only can be changed for whole groups.)

Bug found with OsmAnd+ 2.6.3.

Best Regards,
Norbert

**Comment by dmpr0** [comment]
Hi, we could not reproduce this on 2.6.3 and at nightly builds.

**Comment by Norbert80** [comment]
Strange. At the moment I am unable to reproduce it myselfe.

@vshcherb have you been able to reproduce it? You havevset a milestone some days ago.
