### ISSUE TITLE
Feature request:  investigate how to integrate the 4wd_only tag into routing

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#3781]
A subclass of unpaved roads involves those suitable for 4-wheel-drive vehicles only (or all-wheel-drive owners who want to get stranded so they can whine for attention).  Many passenger cars are very capable of driving on unpaved roads, but should never try very rough or uneven terrain simply because they will end up stuck.  As I envision it, the "allow unpaved" setting would presumptively exclude roads also tagged "4wd_only=yes" and seriously handicap routes tagged "4wd_only=recommended" unless a separate "allow 4wd" setting is enabled.

The 4wd_only tag is an approved OSM tag [1], with in-use values including Yes, Recommended, and No.

Proper implementation might (or might not) also need a new vehicle class in OsmAnd (e.g., a Jeep or Land Rover vehicle).

[1] http://wiki.openstreetmap.org/wiki/Key:4wd_only

**Comment by jfburke3** [comment]
I've spent some more time thinking about this, and want to add the following suggestions.

* The "allow unpaved" setting should penalize (or even disallow) smoothness=very_bad and below for most vehicle profiles.  My main reason for saying this is that those are defined in the wiki as needing at least high-clearance vehicles, because standard passenger cars would simply get stuck.

* If a new vehicle profile for offroading (Jeep/LR) is introduced, then it should allow smoothness=very_bad and below, maybe with a small penalty, unless a new "Allow 4WD" modifier is selected, in which case there would be no penalty.  If this modifier is deselected, then roads tagged "4wd_only=yes" should be avoided completely, but permitted if the modifier is enabled.

A sample scenario that could actually occur, where these changes would matter:

In the Chattahoochee National Forest (as well as other national forests in mountainous areas), there are quite a few campgrounds that are only accessible via unpaved roads.  For the maintained campsites, usually these unpaved roads are maintained to a level where the average passenger car can reach them (e.g., smoothness=bad).  However, there are also many many isolated campsites.  Some of them are on maintained unpaved roads (again, smoothness=bad), but some are on rarely-maintained tracks.  I've driven on several of them, and most are smoothness=very_bad or smoothness=horrible.  Someone who who wants to go camping at a campsite on one of these very_bad roads (e.g., new at camping, doesn't know the road, and is just picking a campsite at random from the map because it's remote) and has a normal street car should not be routed on these very_bad roads.  I can promise that he won't make it.

**Comment by jfburke3** [comment]
The new vehicle profile feature with the ability to use a specialized off-road profile partially implements what I had in mind for this. See also #7148

**Comment by vshcherb** [comment]
Merged into #7148
