### ISSUE TITLE
Cannot move imported Favorites

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#3785]
When tapping on "Move" nothing happens.

![capture _2017-05-17-10-39-28](https://cloud.githubusercontent.com/assets/6921696/26175945/bd307be6-3b54-11e7-98cc-a82831ad97ad.png)

Found with OsmAnd+ 2.6.3.

**Comment by vshcherb** [comment]
Unfortnately the bug is not reproducible on any devices we have.
