### ISSUE TITLE
Can't see Mapillary images

### ISSUE THREAD

**Issue by Athoss9** [osmandapp/Osmand#3786]
I'm using Android 4.2.2, I can see the Mapillary layer, I can click on them, and the box appears, but the image itself not.

![screenshot_2017-05-18-12-42-10](https://cloud.githubusercontent.com/assets/28255870/26198788/bcba8828-3bc7-11e7-9916-6fea6104a49a.png)

I have exactly the same bug in the Mapillary app too.

![screenshot_2017-05-18-12-42-35](https://cloud.githubusercontent.com/assets/28255870/26198820/d6e80450-3bc7-11e7-8196-854b7494a408.png)

**Comment by vshcherb** [comment]
Now image is displayed

**Comment by Athoss9** [comment]
I'm using the latest nightly build, but the images still don't appear. 

![screenshot_2017-05-29-14-18-57](https://cloud.githubusercontent.com/assets/28255870/26549559/eabb0224-4479-11e7-8705-1e304243578a.png)

The small images in the long tap menu have always appeared since the integration of mapillary.

![screenshot_2017-05-29-14-19-12](https://cloud.githubusercontent.com/assets/28255870/26549591/0c0f6794-447a-11e7-8874-3ba509274403.png)

**Comment by vshcherb** [comment]
The issue will be addressed by Mapillary. Your phone doesn't support WebGL in the browser unfortunately. We plan to integrate better with their API once that issue will be fixed. 
Thank you for your case.
