### ISSUE TITLE
OSM Live recipients: multiple accounts used by a single person

### ISSUE THREAD

**Issue by B0o0t-osm** [osmandapp/Osmand#3789]
This is a follow-up of https://github.com/osmandapp/Osmand/issues/3351, with the addition of using multiple accounts, each generating dumb changesets, in order to basically evict everyone else from the top category and collect all the bitcoins themselves.

An example can be seen when selecting "Czech republic" region and "May 2017" period. All accounts ending with "121" + accounts "seberm" and "temimima" belong to the same fraudulent person.

**Comment by vshcherb** [comment]
So far I've found theses accounts:
luna121, mica121, eliska121, terka121, mazlik121, ferda121, luland121, rover121, tapina121, harry121, somora121, jarko121, capka121, kolos121, voldas121.

"seberm" and "temimima"

**Comment by vshcherb** [comment]
How did you identify "seberm" and "temimima" belongs to the same family?

**Comment by vshcherb** [comment]
User deleted

**Comment by polarbearing** [comment]
> "seberm" and "temimima"

same pattern of meaningless micro-changes, same editor/locale, same constant CS-comment "info"
