### ISSUE TITLE
don't render shop=vacant

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#3794]
A shop=vacant is currently rendered by OsmAnd as the shoping basked similar to supermarket or convenience store. That is misleading. shop=vacant means the shop is not operating and does not sell anything (http://wiki.openstreetmap.org/wiki/Tag:shop%3Dvacant). I propose to just remove all shop=vacant tags while creating the map files (rendering_types.xml ?), not in OsmAnd itself.
There are about 12000 objects with this tag. There are also 2800 shop=no.

OsmAnd 2.6.3

**Comment by scaidermern** [comment]
This tagging scheme is broken. `shop=vacant` should be replaced by `disused:shop=*`.

**Comment by polarbearing** [comment]
> shop=vacant should be replaced by disused:shop=*.

That is different in meaning. 
The first is an empty shop that is ready to be rented to the next tenant. 
The second is something falling apart, or having a different use now.

**Comment by scaidermern** [comment]
>> shop=vacant should be replaced by disused:shop=*.
>
>That is different in meaning.
>The first is an empty shop that is ready to be rented to the next tenant.
>The second is something falling apart, or having a different use now.

No, see [Key:disused:](https://wiki.openstreetmap.org/wiki/Key:disused:)

> Use the disused: lifecycle prefix on tags that relate to features that are in a reasonable state of repair but which are currently unused. Examples include vacant or boarded-up dusty shop buildings or unused parking lots.

`disused:shop=*` is perfectly fine for a vacant shop. For a shop having a different use it would be wrong since such historical data doesn't belong into OSM.

Of course it will be helpful if OsmAnd ignores `shop=vacant` to mitigate tagging mistakes.

**Comment by aceman444** [comment]
> This tagging scheme is broken. shop=vacant should be replaced by disused:shop=*.

But that does not fix the occurences already in the database. So it would be best if OsmAnd preprocessed them away for now. Otherwise it is showing misleading info based on wrong interpretation (a supermarket icon).

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/fdb6da530f637bff697c61a54ae82ec4e10f3847

**Comment by aceman444** [comment]
Thanks.
