### ISSUE TITLE
Some addresses on OSM/Nominatim cannot be found by Osmand

### ISSUE THREAD

**Issue by yaomtc** [osmandapp/Osmand#3795]
Using OsmAnd~ 2.6.3 (Android) on a Nexus 5X, some addresses (including mine and my friend's which are on Nominatim, found by searching on openstreetmap.org) cannot be found, whether or not online maps are enabled. The offline map for my state is downloaded. No matter how I type it, unless it's a building with an address specifically attached (like a school or business), the address is not found.

If I find something on OpenStreetMap, and type it in to Osmand exactly as OSM writes it, I should be able to find it - but I can't. Why not?

**Comment by vshcherb** [comment]
Please specify example of address, not everything is supported, sometimes it's a known issue, sometimes it is a glitch in data processing.

**Comment by yaomtc** [comment]
I picked some random house on Google Maps in southeast Michigan. Entered the address into OpenStreetMap, and oops, Google shows it as being in Northville when it's actually Farmington Hills but whatever, let's fix that - OK, OpenStreetMap shows it: http://www.openstreetmap.org/search?query=21144 Woodfarm%2C Farmington Hills%2C MI

Then I type in the address into Osmand... nothing.

How about some random house in Springfield, Missouri? Here it is on Google Maps: https://www.google.com/maps/place/621+S+Park+Ave,+Springfield,+MO+65802/

OpenStreetMap: http://www.openstreetmap.org/search?query= 621 S Park Ave%2C Springfield%2C MO 65802

Now I download the map of Missouri in Osmand in case it's needed, hit Search, enter "621 Park Ave, Springfield, MO, 65802"... Loads for a while, then I get some streets and crossroads in the results below, but not a house. Never a house. There's no such thing as US house addresses, apparently.

**Comment by yaomtc** [comment]
One more for good measure. A random house in Colorado, found on Google Maps here:
https://www.google.com/maps/place/7596+E+Easter+Ln,+Centennial,+CO+80112/

7596 E Easter Ln, Centennial, CO 80112

http://www.openstreetmap.org/search?query=7596%20E%20Easter%20Ln%2C%20Centennial%2C%20CO%2080112

Try typing it into Osmand's search, this time without downloading the map. Eventually, results from Michigan show up, like "Centennial Drive" and "Centennial Oak Court". Oh, and and "0,0" (why does this even show up?)

So then I type in "Colorado" in the Download Maps section. I see Colorado (the state), I'm about to hit the button to download it, but then some other items load and push it down the list. (Why do "Colorado Springs" and "Santo Domingo Equador" show up before "Colorado"?) Oh well, that's a separate issue -- so I downloaded the standard map and repeat the search.

So, the top three items this time are East Easter Avenue, Lane, and Place. But regardless, there's no way to go to a specific address on a residential US street in Osmand, as far as I can tell.

**Comment by vshcherb** [comment]
Tested with 2.6
21144 Woodfarm, Farmington Hills, MI -> 1st result http://www.openstreetmap.org/way/8703501#map=16/42.4458/-83.4189

7596 E Easter Ln, Centennial, CO 80112  -> 1st result http://www.openstreetmap.org/#map=15/39.587814/-104.87523

621 Park Ave, Springfield, MO, 65802 -> 5th result
http://www.openstreetmap.org/#map=17/37.23574/-93.32258 (North Avenue?) according to Google Maps the screet is correct, though house not found

**Comment by vshcherb** [comment]
So I guess there could be 2 main issues:
1) Search is performed far away from target point i.e. more than 100 km, due to OsmAnd nature it searches everything locally and it doesn't try to search in the other states if the map is displaying MA for example. To help search find you can browse more or less to the targe state or click increase radius search
2) The houses are completely missing in the US so it creates a radical issue for find exact address. In case of Springfield it is just makes impossible navigation.

**Comment by yaomtc** [comment]
But OSM gives coordinate data for addresses that aren't attached to a building. Shouldn't Osmand be able to at least navigate to that coordinate? If I search for such a house (that's in Nominatim) within my search radius, within my neighborhood, there's no coordinate result in Osmand like there should be. How is that not an issue, that you can't find coordinates for a location that OSM has data for?

**Comment by vshcherb** [comment]
I didn't find any sign in OSM how does it find coordinates for building, this data is missing.

**Comment by yaomtc** [comment]
Found this relevant information: https://gis.stackexchange.com/questions/211161/how-does-nominatim-know-my-address-which-is-not-as-far-as-i-can-tell-in-osm-da
