### ISSUE TITLE
Issue with Ukrainian TTS

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#3796]
Voice guidance in Ukrainian (TTS) ends every sentence with the word 'крапка' [krapka], which means 'dot'.

**Comment by sonora** [comment]
Could the user please try in **Android** (not OsmAnd), settings, to go to the `Settings / Language and Input  / Text to Speech` (or similar), and there tap the "Listen to an Example" button. I am wondering if this is not a general issue with the TTS engine and needs to be upgraded there, I find no obvious mistake in the OsmAnd TTS wording file.

**Comment by annasoloviova** [comment]
User says the example sounds correct. No "dot" in the end.

**Comment by sonora** [comment]
Anna, Can you please instruct the user how to get to the Test voice prompts menu in our Development plugin.
 - I would like to know if the "dot" comes up after tapping **each** of the buttons there, or if there are exceptions.
 - Are there also "dots" in the middle of some statements, or strictly at the end?
 - Could the user please test English TTS (en-tts) in OsmAnd to see if there is a somilar effect or not?
 - Which TTS engine in Android does the user use? Is there a second one on the device the user could also test?

Thx Hardy

**Comment by annasoloviova** [comment]
Sure. Will let you know as soon as they respond.

**Comment by vshcherb** [comment]
fixed

**Comment by sonora** [comment]
How?

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-resources/commit/dcba6e269cf13548e5a17808ca23aed6a513911a
