### ISSUE TITLE
Proxy settings are not saved and not used after restart

### ISSUE THREAD

**Issue by merge** [osmandapp/Osmand#3799]
I'm using Osmand 2.6.3 (offline maps), but see that it connects to osmand.net. Since this connection is not necessary (navigation and everything works without internet connection), there shouldn't be this connection in the first place; except for downloading maps.

But even worse, when I configure a proxy (Orbot, so localhost:8118), I __still__ see the direct connection to osmand.net, and not to localhost. This is quite bad and the main problem here. So:

**How to reproduce**
* Have Orbot installed and connected
* configure Osmand proxy settings to Orbot's offered http proxy: localhost:8118
* close and re-open Osmand (I don't know if necessary, but whatever)
* Open a network analyzer and see the currently open TCP connections

**Expected behaviour**
Osmand either doesn't connect to the outside, or to localhost, as configured

**Actual behaviour**
Osmand connects to osmand.net directly; bypassing proxy settings

**Comment by vshcherb** [comment]
Note: In the code we have a setting but it is not used anywhere except settings
NetworkUtils.setProxy(settings.PROXY_HOST.get(), settings.PROXY_PORT.get());
