### ISSUE TITLE
Max weight problem in the routing.

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#3803]
the bridge is at this location in Herscheid in Germany :

http://www.informationfreeway.org/?lat=51.17751014050019&lon=7.739578639565038&zoom=17&layers=B0F00000

It is the bridge of the K6 over the L561.

In OSM it looks like this :

In JOSM it looks like this :

In OSMAND+ it looks like this :

I use OsmAnd+ 2.5.4 of 22.11.2016 at Android 6.0.1 at a Motorola Moto G 
Play (G4) with the latest updates for Android and OSMAnd+.

**Comment by aceman444** [comment]
What is the problem here? Is seems some information is missing from the report, or was hidden via the display on this page.

**Comment by vshcherb** [comment]
True I checked and I couldn't find maxweight at that location, though we have very similar problem with #3744 so I will merge that issue there.
