### ISSUE TITLE
Cyclemap needs an API key

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#3804]
Enable Cyclemap - Cyclemap needs an API key

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/Osmand/commit/bed975e05fa024def2ed99e667aa842ec19010c4

**Comment by vshcherb** [comment]
The main issue is fixed, though all users needs to delete the folder with existing cyclemap tiles (or at least metainfo file in the folder, so new url will be used).
