### ISSUE TITLE
Option to mute voice guidance when a call is going on

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/OsmAnd#3806]
Often when I am navigating, I get a call. 
But OsmAnd keeps giving voice guidance, which is overheard by both parties.
This spoils the call.

**Desired:** Provide an option to mute the voice guidance during calls.

**Comment by sonora** [comment]
Option may not be needed here - I guess ongoing calls should always mute nav prompts?

Trouble is how to achieve this, I have failed to find out so far...

**Comment by sonora** [comment]
@crimean Alexey, I have just discovered the work Pavel did to resolve #3710. Do you think Pavel would also have some time to research this topic, which is remotely similar? Thx - Hardy

**Comment by vshcherb** [comment]
@sonora  While we tested navigation it worked fine. There are different options to pause and to mute, today the api to Pause is used. It may not be supported properly on some devices.

**Comment by sonora** [comment]
Yes, also still testing this here. Been using a number of Samsung devices with OsmAnd set to use phone call audio while connected to car systems via Bluetooth. Looks like ongoing nav prompts seem neither interrupted when incoming phone calls are taken, nor are new nav prompts during a call suppressed or ducked. This can in deed be rather annoying.

I think we need some work on our audio focus code (around where I put the commit I referenced above), but I think this alone may not solve all issues. We may need a lot more research on this.

**Comment by sonora** [comment]
Outdated since 2021.
