### ISSUE TITLE
[Feature request] Improve integration with a hiking app

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#3812]
Our users ask to improve navigation with 'Wandeltochten' hiking app. It has the function navigating you to the start of your hiking route. Google maps do that, but OsmAnd fails to parse the coordinates.

These videos are provided by our user to illustrate the issue.

Part 1: https://www.dropbox.com/s/2e0us349z0dg1qb/Navigation%20step%201.mp4?dl=0
Part 2: https://www.dropbox.com/s/20zioaq8hv9esma/Navigation%20step%202.mp4?dl=0
Part 3: https://www.dropbox.com/s/gs087nkac2notlm/Navigation%20Step%203.mp4?dl=0

**Comment by vshcherb** [comment]
I will need to contact again to watch videos they are not available any more
