### ISSUE TITLE
English TTS omits all street names when not in Latin script

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#3813]
1. When "Map Language" is "English" and "Voice Guidance" is "TTS voice 
English", the voiced directions speak street names. (That's fine.)

2. When "Map Language" is "Local names" and "Voice Guidance" is "TTS 
voice English", the voiced directions omit street names. (They say, for 
example, "In 100 meters make a U-turn onto ; and then keep right".)

The issue takes place in Israel, so the local names are written in Hebrew or 
Arabic script, not in Latin script.

**Comment by sonora** [comment]
I am not sure this can be fixed. Sounds like the English TTS engine you use (or maybe all of them) simply does not process non-Latin script ...

**Comment by sonora** [comment]
PS: If I am correct and this is a feature/deficit of some or all English TTS engines, we can in OsmAnd very likely at most produce some workarounds like
- feeding the engine either with transcripted characters (which may produce rather bad results), 
- or with `name:en` (which for many street names may not exist)

So I am not sure we can solve the issue in OsmAnd at all. I will leave it open for some others to look at.

**Comment by vshcherb** [comment]
@sonora  Correct, in order to hear these names - Map language should be changed.
