### ISSUE TITLE
OsmAnd ver. 2.6.3 - Routing error:  Stuart, Florida, USA

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#3814]
OsmAnd version 2.6.3 released 2017-04-25, paid Play store version, and US Florida map dated April 30, 2017.  Also happens with nightly build version 2.7.0#21410M, released 2017-05-06 and the same Florida map.

Samsung Galaxy S5 Active, Android 5.0 (the Play store version) and Samsung Galaxy S7 Edge, Android 6.0.1 (the nightly build version).

Using OsmAnd's in-app routing for both.

Using car profile, navigation from https://osm.org/go/ZDzsI49z3--?m= to https://osm.org/go/ZDzs7t1A~--?m= makes a right turn at https://osm.org/go/ZDzsvDlFK--?m= followed by a U-turn at https://osm.org/go/ZDzsuT46m--?m=.  The right turn/U-turn are unnecessary.  Better routing would make a left turn onto Kanner Highway.

All routing modifiers are deselected (e.g., not using Fuel efficient way, not using avoid toll roads, not using avoid......).

The nodes at the intersection in question are connected on the map in OSM now (note: I have just updated the roads slightly to account for a physical divider, but I don't see that as being part of the problem).
![screenshot_2017-05-23-12-34-58r](https://cloud.githubusercontent.com/assets/11140831/26365735/791ab17c-3fb6-11e7-857b-ee718cb03102.png)
![screenshot_2017-05-23-12-34-13r](https://cloud.githubusercontent.com/assets/11140831/26365741/7d1df770-3fb6-11e7-92be-f42c893f7893.png)

**Comment by jfburke3** [comment]
I should note that the screenshots are taken from the Play store version on the S5, and the green dots and lines are from the Mapillary layer that I added.  I have *not* added a Mapillary layer to the nightly build versions I run on the S7.

**Comment by aceman444** [comment]
May it be there is some traffic signal or other penalized object (e.g. stop sign) on that intersection and the route OsmAnd is proposing is avoiding that object? It may be the route is less expensive in OsmAnd calculation when it routes around that object.
The fix would be to check if the object is properly placed. Because there usually isn't a way to avoid a traffic signal just by approaching the intersection from a different side.

In the current state of the map, your preferred route and OsmAnd's route both go through 2 traffic signals so I do not see anything obvious.

But if you observe the intersection, coming from the north via "South Kanner Highway" and turning right to "Southwest Monterey Road", you do not cross any traffic signal (on the map). Is that correct in reality?

**Comment by jfburke3** [comment]
The only traffic control devices at the intersection are traffic signals; there are no stop or yield (give_way) signs.  And your observation about the number of traffic signals the two routes go through is correct.  As far as I can tell. all of the objects are placed correctly, unless there was something wrong in OSM when y'all downloaded the maps to build your map files (I can't tell that there is anything wrong visually, but I don't know how to inspect the .obf files to find problems).  The intersection is partially captured in both Mapillary and OpenStreetCam, if you want to look at it yourself, but it's probably a waste of time to do so, because there is nothing unusual about it.  It's just a standard intersection with traffic signals.

> if you observe the intersection, coming from the north via "South Kanner Highway" and turning right to "Southwest Monterey Road", you do not cross any traffic signal (on the map). Is that correct in reality?

Whoops, no.  That's my mistake from dividing the section of Southwest Monterey Road.  I'll get that corrected in just a bit.

I should also note that on my S7 with the nightly build, I do have OSMLive integration enabled, but I do *not* have it enabled on my S5 with the Play store build, so that doesn't appear to be having an effect on the calculated route.

**Comment by jfburke3** [comment]
The only observation I can note is that the secondary_link where it routes for the U-turn doesn't have a speed limit set on it.  Is there any way that is influencing routing?  The secondary roads that it touches all have 45 mph set on them, so I don't see how that _link would have a higher priority, but.....

**Comment by aceman444** [comment]
On a secondary_link, OsmAnd assumes a speed of 50 kph.

**Comment by jfburke3** [comment]
That's what I thought, but was wondering if I had misunderstood what I saw in the routing.xml file.
So that can't be the problem, then....

I will also add that I've seen OsmAnd make similar unusual routing recommendations at other places. in the past few months, albeit pretty rarely  However, this was the first one that I could remember well enough a week after the fact to document.  If I come across another one again, I'll try to leave myself a voicemail or something to serve as a memory aid.

**Comment by PaulStets** [comment]
This issue is not reproducible anymore. Please update the map of the region and see if the route is still incorrect.
