### ISSUE TITLE
Size of tracks shows MB instead of KB

### ISSUE THREAD

**Issue by thinking-aloud** [osmandapp/Osmand#3820]
Hi,
At one point OSMAND started showing recorded tracks as if they were many megabytes big instead of the distance. (e.g. a file with 500kb size shows up as 500mb).
As you can see, this bug only applies to newly recorded tracks, the oldest on the bottom is displayed correctly.

Ps. I found the old view that showed the distance instead of size much more useful.

My current version is: 2.6.3
Somewere at that time I updated to android 7.1.2, so this might be related.

![screenshot_20170524-110645](https://cloud.githubusercontent.com/assets/1903874/26395694/2f220f32-4071-11e7-8f8d-b431ea4ed297.png)

**Comment by njohnston** [comment]
Most likely a duplicate of #3706, which was fixed in 81fae15d00f9e0dad87293a1a5f2ecbb68f9aaa4.

**Comment by thinking-aloud** [comment]
I did not search for closed tickets. Guess its fixed then.
