### ISSUE TITLE
Cycling on Trunk Roads

### ISSUE THREAD

**Issue by Goodingn** [osmandapp/Osmand#3821]
Routing from 54.540558,-1.4250152 to 54.539284,-1.420214 using the cycling profile doesn't work.

The problem is the Trunk Link Road.

This is a legitimate cycle route, a major (for here) cycle path terminates just West of here (54.540382,-1.4332737), this Trunk Link Road then crosses the Trunk Road 'A66'  and you then cycle on the cycle friendly Darlington Road to the East.  Using this Trunk Link Road is the ideal route when travelling a route similar to the A66, i.e. from West to East.

This Ordnance Survey mapping colouring appears to support the status of this road:-
https://www.ordnancesurvey.co.uk/opendata/viewer/?9&437471&516318

Also, although I agree cycling should avoid the Trunk Road 'A66', it is perfectly legal and reasonable to cycle upon it.  OSMAnd refuses point blank to route from a positon on this road.  Surely if you find yourself (mistakenly or otherwise) on this road, OSMAnd should still be offering a route?

**Comment by utack** [comment]
You can't go over an access=no road  
https://www.openstreetmap.org/way/155740733

**Comment by Goodingn** [comment]
That does need fixing- good spot, I can have a look at that. Also I notice now th  A66 incorrectly has cycle=no all over it, which is good advice, but not correct :) 

However, it still doesn't route across those link roads.

**Comment by Posteinwurf** [comment]
routing over trunk roads should work in the next update that should be rolled out in june. You have to set driving style to "balanced" or to "fast" (this mode does not avoid main roads at all - it might be renamed in the next update).

**Comment by Posteinwurf** [comment]
should already work in "fast" mode now - maybe you want to try your example route?
