### ISSUE TITLE
OpenVegeMap

### ISSUE THREAD

**Issue by dimqua** [osmandapp/Osmand#3824]
Hi. Can you please add [OpenVegeMap](https://github.com/Rudloff/openvegemap)'s layer to the app?

Thanks.

**Comment by xmd5a2** [comment]
This can't be easily done because most important info on this site is rendered as overlay over raster tile layer.

**Comment by Rudloff** [comment]
Hello,
OpenVegeMap is only displaying info from the OSM API, so Osmand can probably get and render the same info (`diet:*` tags).
