### ISSUE TITLE
OSMand crashes when reordering quick action over several pages

### ISSUE THREAD

**Issue by pos-ei-don** [osmandapp/Osmand#3825]
reordering them as little steps (just move them one or two above) works mostly, but moving one from the last page i have 4) to the first one chrashes.

**Comment by vshcherb** [comment]
Do you have a exception.log file with that crash?

**Comment by pos-ei-don** [comment]
I did send you several per mail, last one at 4. Mai 2017 um 21:54. 

(Device : addison
Brand : motorola
Model : XT1635-02
Product : addison
Build : NPNS25.137-24-1-4
Version : 7.0
App Version : OsmAnd+
Apk Version : 2.6.3 263)

**Comment by AlexSyt** [comment]
[exception.log.txt](https://github.com/osmandapp/Osmand/files/1141552/exception.log.txt)

**Comment by vshcherb** [comment]
Looks like the issue of Recycler view

**Comment by dmpr0** [comment]
Can't reproduce it now in the current 3.6.2 release version.
