### ISSUE TITLE
What has happened to the Address Search function,  it is some times useless

### ISSUE THREAD

**Issue by JesperKick** [osmandapp/Osmand#3827]
I have with pleasure used Osmand on my travels abroad for many years. The address search function has in my opinion always been one the weaker part of the app. but now it has turned to really bad, in many ways it is more or less useless.

The new search works very fine for local search, finally I can find my own street, Kramsvad, 2800 Lyngby Denmark, by just searching the street name. 

But if I want to find a street in a town long away from here, it is more or less impossible, if possible please explain how to do!

In the old version I could , select region, city, street and building (or gps location), but that functionality seems to have vanish. 

Please give us the old search function back (but keep the new one)

Thanks

**Comment by sonora** [comment]
Are you using v2.6.x ? Just tap on the "Search" magnifying glass near the top left of he map screen., **then go to tab "Address"**. There type in the city and wait for results. After seeing city/town/village results, tap on the one you need (multiple with the same name may appear). After that you should see a street list, etc.

You may also enter city, street, etc. separated by blanks, but I have found this to be a lot slower.

**Comment by JesperKick** [comment]
Hi Sonora
After some testing I now understand the adress search and it works very fine. Great.
Thanks a lot.
