### ISSUE TITLE
Persian TTS is silent

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#3828]
When using Persian TTS, it reads the names of the streets if you are using the transliteration feature, but other than that, it stays silent.

**Comment by sonora** [comment]
Could be related to #3813, not sure. If it is, it could mean that under some circumstances we somehow pass street names to the TTS engine using a wrong character set... But this is only a vague idea, this needs a detailed review.

**Comment by vshcherb** [comment]
Expected behavior if TTS doesn't support it.
