### ISSUE TITLE
Discoverability of the double-tap-slide zoom method

### ISSUE THREAD

**Issue by tobydickenson** [osmandapp/Osmand#3829]
I had raised suggestion #3763 because there is no **obvious** way to zoom the map one-handed.

But there already is a good way - slide zoom: Double tap on the map, but upon the second tap leave the finger down and slide up or down the screen.

Although that gesture is not unique to osmand (google maps has it too), it is not widely known (I'm assuming its not just me!) and currently difficult to discover. In practice I suspect many people using osmand one-handed are currently struggling with the + and - buttons which are great when using a second hand (or something else to support the device) but not so good for one-handed use.

What would make double-tap-slide zoom easier to discover?

**Comment by tobydickenson** [comment]
Just an idea: During any zoom animation, a small round target is shown at zoom centre. With double-tap-slide zoom this only appears after any slide movement. Having that appear as soon as the second tap was detected (but before any slide) would indicate that something involving zoom was occurring.

**Comment by vshcherb** [comment]
Not planned to implemented soon. The gesture is not widely useful that's the biggest problem of discoverability even in GMaps
