### ISSUE TITLE
Crash when tapping the globe icon after OsmAnd is launched from a geolocation URL.

### ISSUE THREAD

**Issue by foresto** [osmandapp/Osmand#3832]
After upgrading from 2.6.2 to 2.6.3, when OsmAnd is launched from tapping an SMS containing a Google Maps URL, a new intermediate screen offers several buttons to choose from instead of going directly to the map (#3705). If I tap the button with the globe icon, OsmAnd crashes:

    --------- beginning of crash
    E/AndroidRuntime( 8102): FATAL EXCEPTION: main
    E/AndroidRuntime( 8102): Process: net.osmand.plus, PID: 8102
    E/AndroidRuntime( 8102): java.lang.ClassCastException: net.osmand.util.GeoPointParserUtil$GeoParsedPoint cannot be cast to net.osmand.data.LatLon
    E/AndroidRuntime( 8102): 	at net.osmand.plus.search.QuickSearchListFragment.showResult(QuickSearchListFragment.java:239)
    E/AndroidRuntime( 8102): 	at net.osmand.plus.search.QuickSearchListFragment.onListItemClick(QuickSearchListFragment.java:108)
    E/AndroidRuntime( 8102): 	at android.support.v4.app.ListFragment$2.onItemClick(ListFragment.java:58)
    E/AndroidRuntime( 8102): 	at android.widget.AdapterView.performItemClick(AdapterView.java:305)
    E/AndroidRuntime( 8102): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1148)
    E/AndroidRuntime( 8102): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3059)
    E/AndroidRuntime( 8102): 	at android.widget.AbsListView$3.run(AbsListView.java:3866)
    E/AndroidRuntime( 8102): 	at android.os.Handler.handleCallback(Handler.java:739)
    E/AndroidRuntime( 8102): 	at android.os.Handler.dispatchMessage(Handler.java:95)
    E/AndroidRuntime( 8102): 	at android.os.Looper.loop(Looper.java:135)
    E/AndroidRuntime( 8102): 	at android.app.ActivityThread.main(ActivityThread.java:5294)
    E/AndroidRuntime( 8102): 	at java.lang.reflect.Method.invoke(Native Method)
    E/AndroidRuntime( 8102): 	at java.lang.reflect.Method.invoke(Method.java:372)
    E/AndroidRuntime( 8102): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
    E/AndroidRuntime( 8102): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
    W/ActivityManager( 2218):   Force finishing activity 1 net.osmand.plus/.activities.MapActivity
    W/ActivityManager( 2218): Activity pause timeout for ActivityRecord{b50d274 u0 net.osmand.plus/.activities.MapActivity t481 f}
    W/ActivityManager( 2218): Launch timeout has expired, giving up wake lock!

OsmAnd~ 2.6.3, Android 5.1.1 (LineageOS 12.1), Sony Xperia Z1 Compact.

Offline maps downloaded from within the app.

![Annoying Intermediate Screen](https://i.imgur.com/5Ra9rQr.png)

**Comment by vshcherb** [comment]
Fixed in 2.6.4 (coming next week)
