### ISSUE TITLE
Begin search from the map center, not the current location

### ISSUE THREAD

**Issue by verdulo** [osmandapp/Osmand#3836]
If user taps the 'search icon', the searching begins from the current location. Please change that behaviour, so the search begins from the current map centre. When I'll want to search from the current location, I'll simply click the 'my location' button.

I know that it's possible to overcome this behaviour by long-tapping the desired location, menu button, and 'search near here'; but in my opinion unintuitive.

**Comment by sonora** [comment]
Map center is actually used, you can see that by the background text in the search slot saying "Search xx km away". There may be a 50 km od so threshold if I  remember correctly  for that feature to kick in.

**Comment by verdulo** [comment]
What is the purpose of that limit? Why the map-center is not always used? Could you at least add an option to disable that behaviour?

**Comment by sonora** [comment]
Not sure. I  guess it covers cases where you have no location fix but are in the general area of your last fix. Not aware it makes muchactical difference , ghoigh 
..

**Comment by vshcherb** [comment]
This is designed like that cause search around my location make sense for most people. Your map could contain results from previous search which is irrelevant for a new one.
