### ISSUE TITLE
Zoom problem

### ISSUE THREAD

**Issue by jarry9** [osmandapp/Osmand#3842]
Hi,

I am using Android 5.0.1. I am using osmand from google play. Everything works great. But the only problem is the screen getting white when I zoom more than 5km.

Thanks in advance...

**Comment by sonora** [comment]
It sounds like you are missing a map file. Please make sure you have
 - the standard map for the region you try to zoom into
 - to zoom out to overview zoom levels you need to have the
 World basemap, which  covers the entire planet for large zooms.

**Comment by jarry9** [comment]
I am simulating the same case from openstreetmaps.com. I have downloaded the Turkey Marmara Region package. I am at the lowest level position from mobile phone same as on this position on the openstreetmaps:

https://www.openstreetmap.org/#map=17/41.01658/28.98613  --> Here the coordinates.

I click 11 times to zoom-out button. It shows the with "5 km". But when I click the 12th click which makes "10 km", the map screen goes white. But Marmara Region is bigger when this.

**Comment by sonora** [comment]
Yes, we package zooms 11 and higher in the world basemap, so you need to download that to view the high level zooms.
