### ISSUE TITLE
Umlaut like "ü" depends on zoom level

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#3849]
Umlaut "ü" depends on zoom level, **Brück** changes to **Bruck** when zooming out, apparently when changing from local to world-base map. Observed with other locations as well. 

map language is set to "Local names", display language is "system", did not find the transliterate switch mentioned in #3236 
Place node: [240095145](https://www.openstreetmap.org/node/240095145)

![bruck_zoom2](https://cloud.githubusercontent.com/assets/8266355/26552623/302dbb4a-4488-11e7-91c4-78bd5cc5844e.png)
![bruck_zoom1](https://cloud.githubusercontent.com/assets/8266355/26552622/302982fa-4488-11e7-9c60-7a4b2aaf3546.png)

**Comment by sonora** [comment]
Yes, we change from "Local names" to "English" on the world basemap. If we kept "Local names" on the world map, you would see a wild mixture of Chinese, Arabic, Japanese, German  etc. character sets which would likely serve nobody ...  :)

**Comment by polarbearing** [comment]
Understood. That means you also transliterate the name=* down to plain latin, even if there is no name:en=* ?
Anyway this is another situation where the transition between base and detail map should be more obvious, see my recent comment in #2818.

**Comment by aceman444** [comment]
sonora, but why English? Can you switch to system language? That would be much more intuitive and readable for the user. It's irritating if cities of his home country suddenly lose accents needlessly.

**Comment by sonora** [comment]
I think we use English because it globally has the best chance of there being a properly maintained name:en tag. After all, on the world map we are mainly talking about major towns and ultimately only cities. If we used the system language, chances are we would have to fall back to mere ttansliteration in almost all cases everywhere, and that is a rather bad fallback we should use only as last resort.

**Comment by aceman444** [comment]
Actually at least in OsmAnd 2.6, the world map is in system language. I have map language set to Local names, but when zoomed out to the world, all the country names are in system language and NOT English. In that case loosing accents in SOME city names, that are in that same system language (for home country where local language equals system language) is totally strange.

**Comment by aceman444** [comment]
Also, those cities losing accents do NOT have name:en defined. So you already do some unexpected transliteration/mangling of the names for SOME names only. Many other cities have the system language name also with accents. That is a mess this issue is about.

**Comment by frrrank** [comment]
Hello
just one observation: it seems to depend on the scale factor of the basemap not of switching from region map to basemap.
with only the the basemap loaded, Brück becomes Bruck when switching from 2km to 5km, but München stays München :)
