### ISSUE TITLE
High data on contour lines are missing

### ISSUE THREAD

**Issue by Sixtron** [osmandapp/Osmand#3853]
I am driving bicycle and i need more information about the high of the landscape to plan my way.
I can not find the meters of high on the contour lines because there are only few.
Can you fix this or include an entry in the menu to choose how many contour data will be displayed ?
I am using the offlinemap.
![tmp_21511-screenshot_2017-05-30-09-54-21421591526](https://cloud.githubusercontent.com/assets/29046323/26574041/2c3bd0ba-4520-11e7-9ddc-c35bebbede48.png)
![tmp_21511-screenshot_2017-05-30-09-54-33-2131036574](https://cloud.githubusercontent.com/assets/29046323/26574048/35ccd3e0-4520-11e7-9bbe-e1d99638c872.png)
Zipperberg
Raffenberg, Hattingen
Standort: geo:51.363194,7.171519?z=15
http://osmand.net/go?lat=51.363194&lon=7.171519&z=15

**Comment by xmd5a2** [comment]
Duplicate https://github.com/osmandapp/Osmand/issues/3802
