### ISSUE TITLE
OSM: "Always use offline editing" sometimes goes online!

### ISSUE THREAD

**Issue by pos-ei-don** [osmandapp/Osmand#3857]
I have checked: "Always use offline editing", but sometimes, when my Dataprovider is enabled and I have bad reception, saving a change lockes osmand until a timeout happens. Disabling my Dataconnection on the cellphone works as a workaround, but It would be gradt if this option really works and use everything just "offline".

**Comment by vshcherb** [comment]
Use offline editing doesn't mean you have offline usage i.e. you could still have layer enabled which will keep updating the OSM Notes map and so on. This is a duplicate issue I guess #3759

**Comment by pos-ei-don** [comment]
No, I don't hav an OSM-Notes layer, everything i use is offline, becuse i live in an part of the world where the reception is bad. That's why I need "Always use offline editing". When enabled AND I write a new note/create an OSM-POI, i think it should not need any online-data and so it should not wait for the timeout. Instead it should just write the new note or Data to the osmand-offline-database. So I don't think it is a duplicate of #3759, but maybe it can be solved in the same step.

**Comment by vshcherb** [comment]
We will investigate together.
