### ISSUE TITLE
Build number display broken for nighly builds

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#3860]
We lost any display of our build number (like #25500M) for the nightly builds, both inside the app as well as in the Android app manager, which creates issues when trying to support users or debug issues with users. (Think the issue is due to this commit: https://github.com/osmandapp/Osmand/commit/df2b14e5b90141a8d7465340dc2fcb7fee5a30be)

**Comment by vshcherb** [comment]
I'm not sure how was it working, I still see app_edition is updating. 
The line where specify versionName and app_edition was never used there
https://github.com/osmandapp/Osmand/blob/master/OsmAnd/build.gradle#L44

**Comment by sonora** [comment]
Ok, so it sounds like this was not on purpose, right? Then I guess I can get it working again, we had a similar issue some years back I had fixed (probably around the time when I added all the comments on the build-naming of our branches).

What was the underlying issue for your recent "Version" commits? Just making sure I do not cause a regression for whatever you meant to achieve.

**Comment by sonora** [comment]
At first sight, problem seems this commit: https://github.com/osmandapp/Osmand/commit/264c780952adf59cc0902001ec28d5832e5d2233 You commented out the code appending APK_VERSION_SUFFIX ?

**Comment by vshcherb** [comment]
app_version is not used as a version name anymore, so it is useless to change that string cause it is not used anymore.

**Comment by sonora** [comment]
Here is how it used to work:
 - **(1)** Our builder provides the build number via `APK_VERSION_SUFFIX` (dev builds only), and the release date as `APP_EDITION`. (This still works.)
 - **(2)** We manually maintained the old `app_version` string (like 2.7.0) in `no_translate.xml`. (We ignored the `APK_VERSION` parameter we could specify via the builder in favor of this value)
 - **(3)** Then we concatenated `app_version` as `app_version + APK_VERSION_SUFFIX`. **This was the meaningful value displayed e.g. in Android's App Manager.**
 - **(4)** In code displaying version info in OsmAnd (like in Help/About) we used `Version.getFullVersion(getMyApplication())` and separately appended the release date (from `APP_EDITION`). (This still works.)

So what is broken is (2) and (3): Since we now ignore the `app_version` string and specify our base version (like 2.7.0) elsewhere (where?), we must also append `APK_VERSION_SUFFIX` there.

Looks to me like we need to fix string `appVersion`, which is assembled in`private Version(OsmandApplication ctx)`, which now fails to append the build info `APK_VERSION_SUFFIX` (if present), which was previously imported there via `app_version` ?

Side note: As we have it now we have probably broken some other logic, too, like e.g. `public static boolean isProductionVersion(OsmandApplication ctx)` checks string `appVersion` for occurrence of `#`.

**Comment by sonora** [comment]
Victor, from what I am reading it is now recommended to **not** set `versionCode` and `versionName` in `AndroidManifest.xml`, but in the `build.gradle` file for better flexibility.

So I suggest this fix: https://github.com/osmandapp/Osmand/commit/70d70397d51b495edf86cd8632f4cba5274cf85d. Are you ok with it?

I had earlier committed a partial fix in https://github.com/osmandapp/Osmand/commit/53c0f01988566ed0d20a5f47908a961f2301268e but the flaw is this does not make the version suffix available system-wide at installation time.

 - **PS1:** I guess the reason why for https://github.com/osmandapp/Osmand/blob/master/OsmAnd/build.gradle#L44 we do not export `APK_VERSION` from the builder is that we would have to manually maintain it separately in all flavors on jenkins, while now we only maintain centrally in one place.

 - **PS2:** I still find many references to the old `@string/app_version` in our code which have never been cleaned out, but the string seems unmaintained now? An oversight?

**Comment by sonora** [comment]
For reference: Here is how I works now again (which is how it should be :))
![untitled2](https://cloud.githubusercontent.com/assets/845735/26815542/4194fc94-4a8d-11e7-92f4-e04b7af29601.png)
