### ISSUE TITLE
Replace code

### ISSUE THREAD

**Issue by EmrahNebiyev** [osmandapp/Osmand#3862]
values-az
<string name="show_something_on_map">%1$s-i xəritədə göstər</string>

The "-i" depends on the word. Please add the java codes for this string.

replaceAll("(I|A)-İ XƏRİTƏDƏ","$1NI XƏRİTƏDƏ");
replaceAll("(E|Ə|İ)-İ XƏRİTƏDƏ","$1Nİ XƏRİTƏDƏ");
replaceAll("(O|U)-İ XƏRİTƏDƏ","$1NU XƏRİTƏDƏ");
replaceAll("(Ö|Ü)-İ XƏRİTƏDƏ","$1NÜ XƏRİTƏDƏ");
replaceAll("(A|I)([A-DF-HJ-NP-TV-ZĞÇŞ]{1,4})-İ XƏRİTƏDƏ","$1$2I XƏRİTƏDƏ");
replaceAll("(E|Ə|İ)([A-DF-HJ-NP-TV-ZĞÇŞ]{1,4})-İ XƏRİTƏDƏ","$1$2İ XƏRİTƏDƏ");
replaceAll("(O|U)([A-DF-HJ-NP-TV-ZĞÇŞ]{1,4})-İ XƏRİTƏDƏ","$1$2U XƏRİTƏDƏ");
replaceAll("(Ö|Ü)([A-DF-HJ-NP-TV-ZĞÇŞ]{1,4})-İ XƏRİTƏDƏ","$1$2Ü XƏRİTƏDƏ");

**Comment by vshcherb** [comment]
Not clear what do you mean, please submit a pull request
