### ISSUE TITLE
OsmAnd source compilation

### ISSUE THREAD

**Issue by jasmeetsahni** [osmandapp/Osmand#3863]
This shows compilation errors and when i clone it from github to android studio it shows completely different files with sub-folders as compared to when i simply download zip file of source code and import it to android studio. Can anyone please help me, its urgent i need this source code for my openstreetmap project and please tell me which one is the root file means from which file compilation will start so that it will become easy for me to understand the code.

**Comment by vshcherb** [comment]
Looks like a duplicate issue anyway should be plenty of this answers in internet. The project is building completely fine using gradle on the server.
