### ISSUE TITLE
Postal code search

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#3865]
If in the postal code search and type in the first 4 digits of a U.S. postal code (e.g. "6018"), then I see all the matches beginning with those 4 digits. However, as soon as I type in the 5th digit, no matches are found.

**Comment by vshcherb** [comment]
As an example : Villa Park, IL 60181

**Comment by vshcherb** [comment]
The bug is reproducible in another, after 60181 is nothing displayed any more. Though after 6018 typed, all postcodes are listed.

**Comment by vshcherb** [comment]
Video attached.
