### ISSUE TITLE
Show numeric keyboard in coordinates search.

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#3868]
In latest OsmAnd version when open Coordinates search, we show default qwerty keyboard: 
![keyboard-1](https://cloud.githubusercontent.com/assets/9365308/26724385/c0de02be-47a1-11e7-8100-478370b8900d.png) 

But in this case we need only input numbers, i think we must show numeric keyboard:
![keyboard-2](https://cloud.githubusercontent.com/assets/9365308/26724406/dc985928-47a1-11e7-8630-4ad0d25447a9.png)

**Comment by sonora** [comment]
Please note that there are coordinate systems which require other characters, so we have to implemernt a more granular decision if we want to do this.

**Comment by naoliv** [comment]
Like #1720
