### ISSUE TITLE
Wrong routing on a highway

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#3870]
Similar issues have occurred before. The navigator tells you to take a turn against the direction of road traffic. Please see the coordinates of the place on the 2nd screenshot.
![screenshot_20170601-125319](https://cloud.githubusercontent.com/assets/12711814/26731055/7f09a2fc-47bb-11e7-98e3-97de603c81a8.jpg)
![screenshot_20170601-180200](https://cloud.githubusercontent.com/assets/12711814/26731056/7f10f318-47bb-11e7-9329-08062de318c8.jpg)

**Comment by raindropsfromsky** [comment]
Yes, I have reported this earlier (in response to someone else's bug). Happens occasionally, but not always.

**Comment by xmd5a2** [comment]
Simply missing turn relation.
