### ISSUE TITLE
Different routing results on different devices - why?

### ISSUE THREAD

**Issue by Posteinwurf** [osmandapp/Osmand#3875]
To allow quicker tests of Osmand bicycle routing, I installed the Android Emulator Genymotion. I created a virtual Galaxy S4, and installed the same Osmand APK as in my real galaxy S4. 

But: The virtual S4 is producing different routing results. In both devices, I am using the same routing.xml and the same settings. 

Is it possible that Osmand produces different routing results on different devices (even if you install the same Osmand version)? Maybe due to the heuristic coefficient? 

Thanks for your help

Malte

**Comment by Norbert80** [comment]
It might have to do with heutistics and memory-bound a-star algorithm. As far as I know, these algorithms can stop searching with a suboptimal (but within heuristc) result if available memory becomes low.

**Comment by Posteinwurf** [comment]
Thank you for the explanation. In the last weeks, I have not had that error again. The results now seem to be the same on both my devices.
