### ISSUE TITLE
  [Feature Request] mark closed lokations and mark  waterwell with drinkwater

### ISSUE THREAD

**Issue by Mannshoch** [osmandapp/Osmand#3877]
If I'm in a village and setup pois for some locations. it would be nice if i could see imediaty if they are open. Maybe you could colore it with three colored dots for open,close,unknown.
Many of our water wells deliver water to drink, but some are marked as no drinking water.

**Comment by sonora** [comment]
Filtering open and/or 24/7 POIs is implemented in our advanced filter, please use the tab button to the right of the "Show xxx on the map" button near the top of the  search results screen to access the advanced filter.

Regarding water, there is POI "Drinking water", I have not checked the osm docs but guess it should not include undrinkable sources anyway, so no need to even go to an advanced filter for this?

**Comment by Mannshoch** [comment]
I'm not really familiar about the OSM Properties but in a Village I visited are all "drink water supplier" are set-up as fountain.
http://www.wilnet.ch/Default.aspx?Command=PrdtDetail&prdtName=1c6e7f48-0cc4-4178-93ff-f10641e270c0
http://www.wilnet.ch/Default.aspx?Command=PrdtDetail&prdtName=b8fe1c25-1ccd-45d4-ae31-4d0ab3fc2936
I'm new in Mapping if needed I would change them and learn something.

**Comment by Mannshoch** [comment]
Wow. A whole new Option. I never saw them before. It's nice to get the open and close locations separated.

Thanks!
