### ISSUE TITLE
Regression: OLC codes no longer displayed in OsmAnd+ 2.6.5

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#3878]
Regression: OLC codes no longer displayed in OsmAnd+ 2.6.5.

**Comment by Norbert80** [comment]
Is see this change is intentially by issue #3708. Closing.

**Comment by sonora** [comment]
Yes exactly, OLC is displayed like any other coordinate system when selected in the General settings.

**Comment by Norbert80** [comment]
@sonora: I would like to suggest the solution of #3881. Your feedback there is appreciated.
