### ISSUE TITLE
Don't show context menu after audio recording

### ISSUE THREAD

**Issue by vlotorev** [osmandapp/Osmand#3879]
Hi

I'd like to inform you about my usage scenario and share some of my pain.

I'm using OsmAnd heavily for taking audio notes.
I have Audio note as default action for notetaking screen button.
I have following issue with notetaking: it takes too much redundant taps:
1. Tap Start recording audio note
2. Tap Stop recording, new window appears at the bottom with note info.
3. Tap somewhere so that note info to dissapear so that My location button to be visible.
4. Tap My location to go back to my current location.

Also please note that 1+2), 3), 4) should be tapped at different screen positions and must be aimed, which becomes tedious and disrupting from actual driving/cycling/walking.

Quick action button doesn't reduce number of taps and aimings.

My ideal notetaking scenario is 1+2) taps without note info window and nonlosing My location tracking (or even Bluetooth gadget with physical button).

It would be great if you'd take into account my concern.

**Comment by raindropsfromsky** [comment]
Indeed I have faced this too, and raised a suggestion already to bypass the **OK** stage after taking a note. But this suggestion is even better.

BTW I often want to take a photo in some cases and a audio note in others (depending on the circumstances). But OsmAnd allows me only _one_ default mode (either photo or video or audio).

**Desired scenario:**
1. Allow user to add any/all of the note-taking icons to the screen (photo and/or video and/or audio).
2. The user can directly tap on the icon to attach the note to the current position, or long-tap anywhere to attach the note there. Once the note is taken, bypass the OK stage, and straight away resume in the previous state (i.e., Navigation/Browsing mode).
