### ISSUE TITLE
Camera/crosswalks are warned too late

### ISSUE THREAD

**Issue by vlotorev** [osmandapp/Osmand#3880]
It seems that camera/crosswalks are notified at a fixed distance of 100-150m before the actual POI. I think it too near (to little time) to take an action as there are roads with allowed speed limit up to 130km/h ( I'm aware of).

Is it possible to make time/distance for warning to trigger before the actual POI configurable?

**Comment by sonora** [comment]
Your observation is not entirely to the point: Traffic warnings will be triggered latest at 150m before the occurrence, but the value is dynamically adjusted using your current speed, so if you are faster than e.g. 50 km/h for the car profile, the warning will accordingly (proportionally) be earlier.  (For this to work it is important you select the correct profile for navigation!)

I do not think I have seen many crosswalks in my life on roads where you can legally travel with 130 km/h. Most crosswalks are in residential areas, and there increasing the warning distance would make you lose coherence with where warnings actually apply.

For traffic cameras on high speed highways I have reports form several test users in my notes saying the current parameters work well: If I remember the logic correctly, at 130 km/h the warning should be triggered at roughly 400m before the occurrence. Please note that some TTS engines, particularly on older devices, seem to introduce some extra lag, but this is device specific and seems to increasingly disappear in newer versions of Android. (There is also extra delay needed for BT car stereos, but that is compensated via the dev settings and should not be a n issue here.)

**Comment by vlotorev** [comment]
Thanks for a quick reply.

5 июня 2017 г. 10:25 AM пользователь "Hardy" <notifications@github.com>
написал:

Your observation is not entirely to the point: Traffic warnings will be
triggered latest at 150m before the occurrence, but the value is
dynamically adjusted using your current speed, so if you are faster than
e.g. 50 km/h for the car profile, the warning will accordingly
(proportionally) be earlier. (For this to work it is important you select
the correct profile for navigation!)

I use car profile while driving.

I do not think I have seen many crosswalks in my life on roads where you
can legally travel with 130 km/h. Most crosswalks are in residential areas,
and there increasing the warning distance would make you lose coherence
with where warnings actually apply.

Yes, this makes sense.

For traffic cameras on high speed highways I have reports form several test
users in my notes saying the current parameters work well: If I remember
the logic correctly, at 130 km/h the warning should be triggered at roughly
400m before the occurrence.

400/(130/3,6) = 12 sec. I can't confirm whether it's the time I observed.
The camera is shooting in front of it at some distance so less time is left
for the user before his/her speed will be taken after notification.
Also once notified user can't change the speed immidiately.
I think I can't argument anymore. If you are already sure all distances
tested then I accept it and I should collect more facts in case it causes
any inconvenience to me.
My proposal is to close the ticket.

Please note that some TTS engines, particularly on older devices, seem to
introduce some extra lag, but this is device specific and seems to
increasingly disappear in newer versions of Android. (There is also extra
delay needed for BT car stereos, but that is compensated via the dev
settings and should not be a n issue here.)

I used Nexus 7 2013, which, IMHO, quite powerful. No BT.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/osmandapp/Osmand/issues/3880#issuecomment-306121983>,
or mute the thread
