### ISSUE TITLE
[Feature Request] Hide nearby bus stops in a drop-down list.

### ISSUE THREAD

**Issue by franco999** [osmandapp/Osmand#3883]
When a bus stop has many other bus stops around it but you want to see which bus lines pass through which is selected, the list of nearby stops is almost infinite. My idea is to put all those stops in a drop down menu where you can differentiate between nearby bus stops and those of the stop itself (and the list is not infinite).

What do you think?

It would look something like this:
![open](https://cloud.githubusercontent.com/assets/12088580/26799161/d6cdce4a-4a0a-11e7-8b76-30bd8f1d53b1.jpg)
![closed](https://cloud.githubusercontent.com/assets/12088580/26799160/d6c49bfe-4a0a-11e7-9dca-5eebe27dd100.jpg)

**Comment by vshcherb** [comment]
Too ambiguous, today we don't have good algorithm to combine data as described.

**Comment by franco999** [comment]
Fixed https://github.com/osmandapp/Osmand/commit/ebf26c79aa43177bbaac8dfee5cb3c568123b49d
