### ISSUE TITLE
indoor=yes should be recognised in bicycle routing

### ISSUE THREAD

**Issue by Posteinwurf** [osmandapp/Osmand#3885]
Sometimes, the bicycle routing will use long tunnels that lead to subway stations and that are marked as indoor=yes. All ways with indoor=yes have to be heavily downgraded, so that they are only used if they are a really big shortcut (if you dismount and push, and you are still faster, then it is wise to use them). 

The downgrade for indoor=yes is already in the routing.xml, but the routing engine has to "see" this tag (it needs to be rendered for the router). At the moment, even if I put the value for indoor to 0.01, it does not have any effect.

Here is an example of a long tunnel that was used for routing in Vienna.
![grafik](https://cloud.githubusercontent.com/assets/17393264/26805566/ba5b6212-4a4c-11e7-9967-d6a2cf563cd2.png)

**Comment by Posteinwurf** [comment]
Thank you for integrating this!
Also for the "sidewalk".

Could you also integrate cycleway=sidepath so that the routing engine recognises it?

That would be very important: Cycleways should get a very high value, but we need a downgrade for cycleways along main roads.

**Comment by xmd5a2** [comment]
cycleway=sidewalk already included to obf routing section https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml#L5577

**Comment by Posteinwurf** [comment]
are you talking of cycleway=sidepath ? 

 

I do not understand the structure of the rendering_types.xml, so maybe you could give a brief explanation: I cannot find “cycleway=sidepath” in the code. How does the command amend work? Does it amend only subtags that are specifically named in the following lines of the rendering_types.xml, or does it also amend subtags that are not explicitly named?

 

Thanks!

 

Malte

 

----------------------------

 

cycleway=sidewalk already included to obf routing section  <https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml#L5577> https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml#L5577

**Comment by xmd5a2** [comment]
It adds all possible values of tag "cycleway" to routing.

**Comment by Posteinwurf** [comment]
How does Osmand recognise if it is a value of cycleway or a separate tag?

 

For example when we have: 

 

    cycleway=sidepath

    footway=sidewalk

    highway=cycleway

    name=Ungererstraße

    oneway:bicycle=yes

    surface=paved

 

What is considered a sub-value of cycleway and what a separate tag?

 

Von: xmd5a [mailto:notifications@github.com] 
Gesendet: Mittwoch, 7. Juni 2017 23:34
An: osmandapp/Osmand
Cc: Malte; Author
Betreff: Re: [osmandapp/Osmand] indoor=yes should be recognised in bicycle routing (#3885)

 

It adds all possible values of tag "cycleway" to routing.

**Comment by Posteinwurf** [comment]
PS: It works now – great! I had to download the latest maps to make it work. Thank you for adding it (very important upgrade) – and also thanks for all the other help and revisions that you did.

 

If you have got the time, I would still be happy about a short explanation to my former question, so that I can understand the “amend” command exactly (for future suggestions).
