### ISSUE TITLE
Label placement for addresses

### ISSUE THREAD

**Issue by rbovard** [osmandapp/Osmand#3893]
Before all, I'd like to say that I like the improvements in map style you're making in every release. However I think the label placement for the addresses could be improved.

I noticed a strange effect of "moving labels" when zooming on area with addresses, because the labels are placed with a shift to south and not on the center of the building.

![image](https://user-images.githubusercontent.com/4549666/26947282-7706f8b2-4c92-11e7-8634-054dd045ddb4.png)

I took a look on another app wich also use OSM data, and this effect is not present because the labels are on the center of the building.

![image](https://user-images.githubusercontent.com/4549666/26947286-7c788a04-4c92-11e7-80d0-3bcfae5f81db.png)

What do you think about improving the label placement for the addresses to avoid this "moving labels" effect?

**Comment by vshcherb** [comment]
Fixed in 2.7 (currently in nightly)

**Comment by rbovard** [comment]
Great, thanks a lot! Looking forward to see it in action in `2.7`.

**Comment by rbovard** [comment]
Just tested, it's much better. Thanks guys!
