### ISSUE TITLE
Distinction between public and private parkings

### ISSUE THREAD

**Issue by rbovard** [osmandapp/Osmand#3894]
I notice that you're making a distinction between public `mm_amenity_parking.png` and private `mm_amenity_parking_private.png` parkings which is great but in case of private underground parking (and maybe other cases), the distinction is not made.

![image](https://user-images.githubusercontent.com/4549666/26947615-a723d988-4c93-11e7-8d8b-6fb08f4bd5b7.png)

Is it possible to reproduce this distinction not only for the "simple" parking?

**Comment by vshcherb** [comment]
I'm afraid too many options is not possible to make, please use POI filters and click on poi itself.

**Comment by rbovard** [comment]
Seriously? Can't you take the "Parking" icons and just dupplicate them? I can help if it's necessary.

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/dd964efb2700e0504290fa0a319bb20f46fb75c9

**Comment by rbovard** [comment]
Thanks a lot @xmd5a2!

**Comment by xmd5a2** [comment]
https://github.com/osmandapp/OsmAnd-resources/commit/7944493851b3864ac51d828dcfe191f3f1f701c9
