### ISSUE TITLE
App crashes when trying to add POI.

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#3897]
Latest version of OSM

Android 5 
Galaxy note 3

Crash log: https://drive.google.com/uc?id=0B19mmCKTPBRYWnB4LTJ2LXJEclE&export=download

**Comment by vshcherb** [comment]
Not fixed at all!

**Comment by rindlerblabla** [comment]
Still crashes. Version 2.7.2 https://www.dropbox.com/s/65pax3rfug8zokv/OsmAnd%20bug?dl=0

**Comment by vshcherb** [comment]
Where

**Comment by rindlerblabla** [comment]
Sweden.
