### ISSUE TITLE
RoutingHelper.java   -- evalWaitInterval

### ISSUE THREAD

**Issue by sabresailor** [osmandapp/Osmand#3899]
Line 875 in RoutingHelper.java should set the evalWaitInterval to non-zero value, similar to line 649 in the same file.  Otherwise a failed route calc causes a backlog of toast messages that cause screen interference.

suggested:   evalWaitInterval = Math.max(3000, evalWaitInterval * 3/2);   // from line 649

**Comment by sabresailor** [comment]
additional info:  issue is in the R2.6 master branch, osmand/plus/routing/RoutingHelper.java  
commit: 718fb65041bea094c12948946b0b71e837ce454c

**Comment by sonora** [comment]
From what I see,I think you are right. Implemented, but not tested yet, please test latest nightly. Thx!
