### ISSUE TITLE
An avoided road should not be just a point, but a length

### ISSUE THREAD

**Issue by Siltaar** [osmandapp/Osmand#3901]
Currently we can pin point a road and ask the Offline routing system to avoid this point (in case of rebuilding of the road for instance).

I suggest to add a dialog to choose for how-long to avoid the road.

Would be useful if you know there are 5 km of unavailability, or if you want to avoid the ring around Paris because you are at the office exit time and you will loose 1h30 using this road… (setting 99km would have been enough, but a "full road" checkbox would have work also).

**Comment by vshcherb** [comment]
We use the full length of OSM way, it varies on a location but it is definitely more than a point, though it doesn't block the whole street or something bigger which is good in many cases.
