### ISSUE TITLE
landuse=cemetery and natural=water

### ISSUE THREAD

**Issue by utack** [osmandapp/Osmand#3902]
Currently when there is a natural=water inside a landuse=cemetery it is not drawn on the map.
Examples
As way
https://www.openstreetmap.org/way/169867776
(actual water shape if you are wondering, not my fault)
As relation
https://www.openstreetmap.org/relation/2034616

Maybe you can "blend" the both, or render water over landuse in general?
Since the water is part of the cementery, It sounds like a rendering error, and not a missing "inner" error in the OSM data

**Comment by ivanatora** [comment]
I'm seeing the same thing, but it is concerning all landuse=* regions, including parks, leisure, cemetery, etc. For example this region: http://www.openstreetmap.org/#map=14/42.1453/24.7350 is displayed flat out white in Osmand. 

natural=water is also not displayed, for example this region with its many dams: http://www.openstreetmap.org/#map=11/41.8476/24.1555

I don't think they have overlapping natural=water as stated in OPs report.

**Comment by xmd5a2** [comment]
@ivanatora can't find anything improperly rendered in areas you mentioned.

**Comment by ivanatora** [comment]
Yeah, it looks fine now. Either the app updated or someone fixed the OSM data.
