### ISSUE TITLE
Incorrect Japanese characters display.

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#3911]
It seems that there is a defect in the specified Japanese font set. Not all Japanese characters are displayed incorrectly. Japanese katakana, Chinese kanji of some Japanese kanji, and garbled characters of numbers.
![photogrid_1497262465127-1440x1440](https://user-images.githubusercontent.com/20681525/27031105-967535a0-4f77-11e7-803b-c151dd5c4027.jpg)

**Comment by vshcherb** [comment]
Was japanese font downloaded? Is it possible to specify location.

**Comment by PaulStets** [comment]
The screenshots are made after the user installed the fonts. Waiting for the exact location.

**Comment by osMatt** [comment]
The location of the map shown in the screenshot is approximately [here](http://www.openstreetmap.org/#map=15/33.8414/132.7527)

**Comment by xmd5a2** [comment]
![screenshot_2017-06-23-17-34-50](https://user-images.githubusercontent.com/5829014/27486830-85e422de-583a-11e7-8e1e-7a6dfcb17e29.png)

**Comment by vshcherb** [comment]
Most likely old version or fonts are not correctly downloaded.
