### ISSUE TITLE
quick question: Exclude a command if in "avoid unpaved" mode?

### ISSUE THREAD

**Issue by Posteinwurf** [osmandapp/Osmand#3912]
It is great that you made it possible to use route=bicycle in routing.xml! This adds some great possibilities.

But some bicycle routes have unpaved parts (see my photo). So we have to exclude these parts in unpaved mode. Is it possible to SKIP a command line (in routing.xml), on the condition that unpaved mode is set to "ON"? If so: How? 

Thanks!

![20160323_130616](https://user-images.githubusercontent.com/17393264/27035615-498e9c6c-4f82-11e7-9c81-df612512dd9b.jpg)

**Comment by vshcherb** [comment]
You can use avoid roads functionality to avoid specific road for example.

**Comment by vshcherb** [comment]
@xmd5a2 is it possible to do in routing.xml?

**Comment by Posteinwurf** [comment]
The most efficient solution would be to just ignore that one command line in unpaved mode. The idea would be "if avoid unpaved is OFF, set the value for bicycle routes to 26kmh (if avoid unpaved is ON, set no special value here)"

Would be great if there is a command for this!

**Comment by Posteinwurf** [comment]
I currently doing an update of routing.xml. Therefore, I have to ask again:

In routing.xml, is it possible to say 

"only if avoid unpaved is OFF, use this command line"?
(I know how to program "use this command line only if avoid unpaved is ON" - but the opposite would be needed!)

**Comment by vshcherb** [comment]
"only if avoid unpaved is OFF, use this command line"?
You can try to check <ifnot param="short_way">

**Comment by Posteinwurf** [comment]
can try. what would be the syntax? 
if not param="avoid_unpaved"   ???
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.

**Comment by Posteinwurf** [comment]
have checked. Unfortunately, it does not work. (App crashes).

What else could be the syntax? Have tried with “else”, but do not know if I had the right order.

**Comment by vshcherb** [comment]
I checked it is in the code ```<ifnot param="short_way">``` and suppose to work but because it was never used it is possible that doesn't work.

**Comment by Posteinwurf** [comment]
yeeees it works! Thank you for looking it up.

i made a mistake before: i ended it with /if, but is has to end with /ifnot . seems logic...

now it works. great

**Comment by pebogufi** [comment]
What about posting that lines (with additional ~5 before/after) here ?
More people are interested how to solve it.
Regards Peter

**Comment by Posteinwurf** [comment]
the code seems to work in this form:

`			<ifnot param="avoid_unpaved">
				<select value="31" t="bicycle" v="designated"/>
			</ifnot>
`
