### ISSUE TITLE
Opening_hours syntax (additive separator not fully supported)

### ISSUE THREAD

**Issue by Jotam** [osmandapp/Osmand#3919]
The following problem occurred on **Android 7.1.2** with **OsmAnd~ 2.6.3**:

In cases where the **additive separator** (comma ",") is used on opening_hours, OsmAnd has a problem to interpret this correctly.

![20170608223057_screenshot_20170608-222629](https://user-images.githubusercontent.com/15984044/26950037-97f0e0c4-4c9c-11e7-9634-4a600789fa9e.png)

Printed in black is the literal content of the opening_hours tag. Marked in red is how OsmAnd interpreted that data. Note how "Sa" for Saturday was neglected and the second rule (10:00-15:00) was understood to **also** apply to the first rule (Mo-Fr). 

However, according to the [Evaluation Tool](http://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-Fr%2009%3A00-18%3A30%2C%20Sa%2010%3A00-15%3A00&lat=48.7769&lon=9.1844&mode=0&DATE=1497377880000), it is acceptable to use a comma to separate days. 

In this particular case, using a comma or a semicolon should lead to the **exact same result**, as the second rule for Saturday doesn't overlap with the first rule which applies Monday to Friday only.

**Comment by ypid** [comment]
opening_hours support in OsmAnd is a bit limited. There are starting to appear more issues about this here: https://github.com/osmandapp/Osmand/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20opening_hours

Those advanced features are more and more difficult to (re)implement. There are ideas to use an existing parser which already implements all of this: https://github.com/osmandapp/Osmand/issues/473

**Comment by Jotam** [comment]
Thanks @ypid for the rapid reply. I fully understand that it will take time before OsmAnd will be able to interpret all those advanced features of timing rules correctly. I just think this given example is a very basic rule and the issue of commas / semicolons should be addressed. Thanks a lot!

**Comment by Jotam** [comment]
Does anyone think we could have a quick solution to this problem? I know that opening_hours that use **only additive separators** (commas) are extremely widespread. (Not only from StreetComplete but other sources as well.) It would be great if OsmAnd could interpret those correctly. Thanks!

**Comment by ypid** [comment]
> quick solution to this problem?

Unfortunately I expect this to be rather difficult …

Ref: https://github.com/opening-hours/opening_hours.js/issues/86
Ref: https://github.com/simonpoole/OpeningHoursParser/issues/1

**Comment by vshcherb** [comment]
It is not going to be supported in OsmAnd ``` Mo-Fr 07:00-18:00; Sa 07:00-13:00 ```, if ';' could be used it is better to change it in the map.

As @ypid pointed out it is getting more & more complicated and as developer I would like to not implement some features on purpose (especially complex) so community attention will be brought to the horrible data design.

**Comment by vshcherb** [comment]
Here is the list what's not supported
https://github.com/osmandapp/Osmand/blob/master/OsmAnd-java/src/net/osmand/util/OpeningHoursParser.java#L1293

**Comment by Jotam** [comment]
I just want to point out one more time that we are **not talking** about a particularly **complex or advanced** kind of syntax. The problem at hand is **extremely basic and widespread**. Many mappers use the comma to separate different rules. According to the evaluation tool this is a valid way of tagging opening_hours.

I don't understand why you want to leave an issue unaddressed that applies to thousands and thousands of tags.

**Comment by vshcherb** [comment]
@Jotam It was not correct 4 years ago, the scheme evolved too much making it complex to support.
opening_hours failing the rule that there should be 1 canonic solution. The opening hours is a technical tag and it is not a free-format field.

Today if it is possible to move all opening_hours to canonical rule with ';', it is better to do that.

**Comment by ypid** [comment]
> opening_hours failing the rule that there should be 1 canonic solution.

Agreed. What you did not consider is that the additional rule was added to solve a particular problem. Compare:

`Mo-Fr 22:00-04:00, Sa-Su 22:00-02:00`

vs.

`Mo-Fr 22:00-04:00; Sa 00:00-04:00,22:00-02:00; Su 00:00-02:00,22:00-02:00`

Which one would you prefer to write and maintain as a mapper?

> Today if it is possible to move all opening_hours to canonical rule with ';', it is better to do that.

Not agreed.

**Comment by vshcherb** [comment]
OsmAnd supports properly syntax
```Mo-Fr 22:00-04:00; Sa-Su 22:00-02:00```
And it was supported before the change happened, I don't know why scheme 
```Mo-Fr 22:00-04:00, Sa-Su 22:00-02:00```
is recommended now

**Comment by ypid** [comment]
> OsmAnd supports properly syntax

https://github.com/osmandapp/Osmand/blob/1cd123ef2605cd9c8c85c8b2b524ec333a3a03a1/OsmAnd-java/src/net/osmand/util/OpeningHoursParser.java#L1389-L1424

> And it was supported before the change happened, I don't know why scheme

That addition has been there since 2011:

```
A basic_rule is applicable to a day on a all-or-nothing base. The result of evaluating a rule_sequenz is the result of the last rule, which is applicable to the particular day.
The components of a basic_rule are additive: the comma between the components is read as "and also". 
```

Refs:
http://www.netzwolf.info/en/cartography/osm/time_domain/
http://www.netzwolf.info/en/cartography/osm/time_domain/specification
https://wiki.openstreetmap.org/wiki/Talk:Key:opening_hours#Closing_time_on_the_next_day

I already made you aware of this incorrectly evaluated case but you seamlessly removed/ignored it in:
https://github.com/osmandapp/Osmand/commit/3bc4414a8577155914b54a21623c5095673e406d

We do have a [specification](https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification). Doing your own thing is not helpful. As said, the spec can be changed if you have a better idea to handle all cases. Related to: https://github.com/westnordost/StreetComplete/issues/305

**Comment by vshcherb** [comment]
I'm not doing things against, the support was added long time ago cause OSM is always driven by data and that data is much more popular. Nobody logically will split ```Mo-Fr 18:00-01:00``` cause it is not readable .

I do have ideas to make it better but I don't think I can change the system and this is about my ambition. The problem of supporting opening hours is much bigger than only detecting correct rules which is already hard but it also implies translation, readability and so on.
 
First of all I think the tag that looks like "human reading" & "human input"  and on the same time has quite a complex specification was a mistake. Second problem there are multiple ways to express the same opening hours with quite different syntax. 

So my main idea that I would vote for but it is not present at all in OSM which I think quite sad. We don't have "generated" tags builtin in OSM, I don't mind if there will be evaluated tags which will be much easier to support for developers. In that case 1 validator and 1 very complicated parser would be enough for OSM libraries. 

As a developer I would like format to be focused on something which is closer to UI:
hours:weekdays:mo="time-time" (comma separated)
hours:weekdays:mo:break="...."  (comma separated)
hours:dates="01 Jun-08 Jun,..." ...
hours:weeknumbers="? ... ?"
hours:holiday:rules="Netherlands" (global rules indicating schedule should follow exception or could be different)
hours:exceptions:1:date="Date or range"
hours:exceptions:1:time="Time range"
hours:exceptions="? other complciated cases"

For many application it is enough to support & display only weekdays.

What I don't like today happening that we had some data "de facto" - ```Mo-Fr 18:00-01:00```  and we are changing into data "de juro" ```Mo-Fr 18:00-00:00, Tu-Sa 00:00-01:00``` which to my taste looks incorrect and is breaking many sites/applications (especially in display format). I'm not trying to convince everybody that I'm right but looks it is getting worse with data getting more into details & having 2-3 good tools and hundreds sites/apps working with this data.

**Comment by ypid** [comment]
Thanks for your detailed answer!

> First of all I think the tag that looks like "human reading" & "human input" and on the same time has quite a complex specification was a mistake.

Not sure if the alternatives would be better. The opening hours need to be encoded somehow and the current format developed naturally driven. If you want to, you can already generate opening_hours values with tools like http://projets.pavie.info/yohours/.

> Second problem there are multiple ways to express the same opening hours with quite different syntax.

True, but opening_hours based syntax is used for all types of objects in OSM and so the syntax needs to support them. For some objects it is quite common to have different opening hours for different months so additive rules would be impractical.

So I guess with every reasonably complex date format, different variants to express the same thing become possible.

> As a developer I would like format to be focused on something which is closer to UI:

Hm, that would get pretty repetitive. If it is all generated that would not matter but then every editor would need to support it. Also, this syntax would be too limited then the currently used rule based approach. There are not always the same weekly opening hours for the whole year and all that stuff.

> In that case 1 validator and 1 very complicated parser would be enough for OSM libraries.

That is still the ideal end game which we will hopefully reach long term.

**Comment by vshcherb** [comment]
> If it is all generated that would not matter but then every editor would need to support it. 
Yes , every editor. We don't have too many generic editors (3-4) and their support is limited anyway. OsmAnd also provides interface to modify it in very simple way. That basically works even worse cause not all editors could support complex case and that becomes a mess. 

BTW cause you are the biggest contirbutor to OSM wiki page 
I checked how did it go, in 2011 on the page was this example
"Opening_Hours = Mo 10:00-12:00,12:30-15:00; Tu-Fr 8:00-12:00,12:30-15:00; Sa 8:00-12:00   complex opening hours" - supported by osmand

The first complex example happened (in talk):
"Consider this example opening_hours=22:00-02:00; Tu 12:00-14:00. Following the specification, the rule for Tuesday should completely overwrite that day. Netzwolfs code does interpret it like this opening_hours=Tu 00:00-02:00,12:00-14:00;We 22:00-00:00 for Tuesday and Wednesday, which is probably not what you want. opening_hours.js does follow the rules: opening_hours=Mo 00:00-02:00,22:00-00:00; Tu 12:00-14:00;We 00:00-02:00,22:00-00:00. But Netzwolf came up with a solution: opening_hours=22:00-02:00, Tu 12:00-14:00 which will be interpreted as expected (opening_hours=Tu 00:00-02:00,12:00-14:00,22:00-00:00;We 00:00-02:00,22:00-00:00) --Ypid (talk) 17:30, 1 September 2013 (UTC)"

Though even on wiki page of 2013 that example was not mentioned
https://wiki.openstreetmap.org/w/index.php?title=Key:opening_hours&oldid=969593

Anyway changing after 2013 was quite for OsmAnd implementation already & by some reasons I didn't get involved in this discussion. Anyway we end up in a bad situation, we have 1-2 reference implementations which could keep adding features and support even more complicated syntax. Unfortunately OsmAnd won't be able to keep up with this, may be we find a solution how to use or integrate reference implementation later. 

Meanwhile these bugs will stay & that's annoying.

**Comment by ypid** [comment]
> "Consider this example opening_hours=22:00-02:00; Tu 12:00-14:00. Following the specification, the rule for Tuesday should completely overwrite that day."

I will do some digging when I find the time. I think I discussed this with Netzwolf back then by mail.

> Anyway we end up in a bad situation, we have 1-2 reference implementations which could keep adding features and support even more complicated syntax.

Agreed.

> Unfortunately OsmAnd won't be able to keep up with this, may be we find a solution how to use or integrate reference implementation later.

Plans exist: https://github.com/osmandapp/Osmand/issues/2610#issuecomment-222830564, #473

**Comment by vshcherb** [comment]
@ypid What's your take / proposal?

**Comment by ypid** [comment]
Rewrite opening_hours.js in Haxe which can than be transcompiled into Java. Then build a jar lib for use in Osmand. Ref: https://github.com/opening-hours/opening_hours.js/issues/136

**Comment by Discostu36** [comment]
Is this still being worked on? Problem persists.
![screenshot_2019-03-02-22-26-07](https://user-images.githubusercontent.com/30999326/53687859-61d11280-3d3a-11e9-8860-5e9a1a648fdf.png)

**Comment by vshcherb** [comment]
That issue is outdated cause additive syntax should be properly supported now.
