### ISSUE TITLE
[Osmand~ 2.6.3 F-Droid][Sony Xperia Sp C5303][Android 4.3] Compass direction error 

### ISSUE THREAD

**Issue by Tranquille89** [osmandapp/Osmand#3926]
Hello 
On my phone the compass cursor show only pure north or pure south none of other angle.

Not cool for orientation at foot. 

This bug is only on Osmand~, not on other apps like Vespucci or GPS Status. 

Tranquille 
French OSM contributor 

Ps: sorry for my poor english ^^

**Comment by sonora** [comment]
Have you tapped on the widget, just to make sure it is not set to "North is always up" mode?

Then perhaps try this experiment: Enable the Development plugin, and change its setting "Use magnetic sensor". See if this changes anything.

**Comment by Tranquille89** [comment]
Hi, 
Dev option "use magnetic sensor" solve my problem. 
Thanks !
I didn't think to go in dev/debug option ^^
