### ISSUE TITLE
Handle missing maps

### ISSUE THREAD

**Issue by elgaard** [osmandapp/Osmand#3933]
Offline maps and routing:

![berlinputtgarten](https://user-images.githubusercontent.com/779040/27247957-15759334-52fe-11e7-8b67-5ba38fc06fd9.jpg)

This is not the best route from Berlin to Puttgarten. But unless the user like on the image zooms out to see the green downloaded maps, it is hard to discover.

IMHO, the user should be told that a route cannot be calculated without the Mecklenburg-Vorpommern map.
In the general case it can be difficult to determine if maps are missing for optimal routing.

The world basemap could be used.
I.e., if the shortest route passes a "missing" map using the basemap roads, it means that a map is missing for optimal routing and the user could be warned.

Another problem then is that the basemap is not well connected. But that can be fixed.
![salzburg](https://user-images.githubusercontent.com/779040/27248232-02bd94b4-5301-11e7-93ac-740a1bffa809.jpg)

**Comment by scaidermern** [comment]
Related: #2525

**Comment by vshcherb** [comment]
Reopened #2525
