### ISSUE TITLE
[TTS] Abbreviation periods wrongly pronounced as pause

### ISSUE THREAD

**Issue by ockham** [osmandapp/Osmand#3934]
In German place or street names, such as "Dr. Max Mustermann-Straße", the abbreviation period after "Dr" is rendered as a pause by TTS, which makes it sound very awkward (and a bit distracting to follow routing instructions). Interestingly, "Dr" is correctly pronounced as "Doktor". (Note that the abbreviation period in German, unlike [British] English, is mandatory.)

Maybe there's a way to add a whitelist of abbreviations after which a period shouldn't be rendered as a pause.

OsmAnd+ 2.6.5 on Android 7.0.

Punctuation in TTS first discussed here: https://github.com/osmandapp/Osmand/issues/2985

**Comment by sonora** [comment]
Rather clearly a bug in the TTS engine you are using. Many engines do actually get this right, I think. Any chance you try anothrr one?

**Comment by ockham** [comment]
Uh, how do I test this while not actually moving? 😄

**Comment by sonora** [comment]
I have added a special test for this: You can either use our latest nightly build, or wait for the next release version, then try this procedure:
- In OsmAnd's settings, enable the Development plugin
- Go to Settings / Development plugin / Test voice prompts, select 'de-tts', and tap test button **(3.6)**. This will play a prompt containing a "Dr." string.

Then: You may go to your Android (not OsmAnd) settings (usually under `Input and language / Text to speech` options) and check if you have another TTS engine present on your device (some devices have e.g. google's and Samsung's TTS engine present). Repeat the above test with the other engine, or even go to the Play Store and install, then try, a third party TTS engine).

As I said, I do not think it is a general issue in OsmAnd, I think it may only be bugs in certain engines which produce this. Please report your findings here, including device type and engines tested, ok?

**Comment by sonora** [comment]
PS. Here is my finding for the google TTS engine on several Samsung devices: 
- "Dr" is pronounced correctly without successive pause in English,
- while "Dr." is pronounced correctly without pause when using a German TTS voice in German TTS.
- "Dr." in English does, however, produce an artifact pause.

So it seems the google engine does correctly take into account regional acronym customs, although an English-speaking tourist traveling in Germany would experience the false pause. But your mileage with other engines may vary. I am rather hesitant to introduce language specific acronym substitutions, although in principle our code allows for this. We should have a real good repertoire of testing different engines before introducing any such workaround.

**Comment by sonora** [comment]
PS: Implementation reminder: Strings from Test voice prompt are not passed through the character substitution - need to fix.

**Comment by sonora** [comment]
From what I see, I think this is fixed. There will be the odd occurrence of other periods like maybe "Prof.", but I do not generally want to replace all dots in English, it may have side effects. So for now I leave it at just adjusting "Dr.". We can always revisit if there are new observations.

**Comment by ockham** [comment]
Thanks for your thorough sleuthing, and sorry for not having replied yet. I was going to wait for the update via Google Play since TBH I didn't want to install OsmAnd from elsewhere (fearing e.g. map storage location links might break).

BTW, another example I could think of is "Str." (Straße = street).

**Comment by polarbearing** [comment]
German spelling rules would demand a multi-part street name to by hyphened trough, i.e. "Dr.-Max-Mustermann-Straße".

(quote [duden.de](http://www.duden.de/sprachwissen/rechtschreibregeln/strassennamen): Straßennamen, die mit mehrteiligen Namen zusammengesetzt sind, schreibt man mit Bindestrichen: Dr.-Kissinger-Straße, Berliner-Tor-Platz, Ernst-Ludwig-Kirchner-Straße.)

So if you have a German street name without the hyphen after the "Dr." it is a tagging error.

**Comment by ockham** [comment]
Ah, good to know. I figure there was some sort of OSM style guide (been a while since I last did some mapping of my own), but yeah, I've certainly seen those other (discouraged) variations, too. Oh well.
