### ISSUE TITLE
TTS does not anounce street names while navigating a gpx track.

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#3937]
Street names using TTS are only announced when the user went off the route. When the user is navigating from gpx file, it just doesn't want to announce street names. The issue occurs with all gpx tracks and using the same language for the street names and TTS.

**Comment by sonora** [comment]
I think while you navigate from a GPX track, naturally, the data from the track and not the map is used. So if your track does not contain street names, you cannot hear any. What  is the source of your track?

**Comment by tjated** [comment]
I create map from Google Maps, then export via their KML export. I use kml2gpx.com to create the GPX file. I attached a sample file. Thanks!
[To-lake-geneva2.zip](https://github.com/osmandapp/Osmand/files/1084812/To-lake-geneva2.zip)

**Comment by sonora** [comment]
Yes, looks like that file contains no navigation instructions, just location information as treck points and waypoints. Just open the file in an editor and compare to a calculated route file saved by OsmAnd, which would also contain turn instructions.

Fixing this would mean we try, in some fashion, to combine the gpx and vector-map-information, which may be as tricky as ambiguous (we currently use gpx info if on the route, and map info to guide you back onto the route if off).

**Comment by tjated** [comment]
I know this sounds off, but I have used this mapping system for 5 years and have always had street names included in navigation. Does Google not include the navigation instructions in their KMl exports now? Attached is a file I know from last year gave street name directions by follow the previously mentioned KML to GPX directions. Take a look and see if more navigation information is included. Thanks, Tim.
[2016-ST-Day2.zip](https://github.com/osmandapp/Osmand/files/1086615/2016-ST-Day2.zip)

**Comment by sonora** [comment]
Looks to me like that file simply contains about 30 locations as mere POINTS, almost like a "Favorites" file. The file calls them `<placemark>`, and OsmAnd seems to correctly interpret and show them like waypoints (similar to Favorites).

The file contains no track information at all, I think (but I am not a specialist with KML files). But it seems to contain a 'line' defined by a long series of coordinates, apparently trying to specify what is called Directions from `Long Branch State Park to Roaring River State Park`. This line specificatio seems to contain no names at all, just the coordinate numbers.

I may be off here, but it looks to me that OsmAnd cannot use that line to navigate at all. Have you tried it? OsmAnd will not ask if to navigate along any specified track even though your file is displayed on the map. So if you simply used the file to pick one of its points, then tell OsmAnd to navigate to it, OsmAnd would use its normal vector maps to calculate a route, and that would naturally announce street names etc. But they do not come from this file (with the exception of the destination point name you selected). The file would only be used to specify the destination, all else is done by OsmAnd itself.

**Comment by sonora** [comment]
PS: Please see my Edit in the comment further up your first file, I just re-visited that one. It does contain routing information, but with only waypoint names, no street names. (Looks like the file was pulled of the GPSies.com repository).

**Comment by tjated** [comment]
Is there a solution? How to get street names from GPX track? I can choose a waypoint in OsmAnd and have it calculate the route, but I can use Google Maps for that, though.

**Comment by sonora** [comment]
Well, if you calculate a route in OsmAnd and save that as GPX file, the street names etc. will be saved into the GPX file in their respective places (i.e. with each each turn-by-turn instruction), and used when this file is used for navigation again later. Unfortunately other routing engines may have other conventions of including street names, or most actually leave out this information entirely.

 (To save an OsmAnd-calculated route as GPX file: After a route calculation has finished, on the route-config dialog tap on the line showing the route details, then on the route details screen tap the "Save" icon near the top-right corner.) To use that file for navigation later, display it on the map before starting a route calculation. OsmAnd will ask if you want to use the displayed GPX file for the route calculation or not.

**Comment by tjated** [comment]
The whole point is to create a route of MY choice, not Google Maps or OsmAnd, then get turn-by-turn directions which include street names. So, if I create a OsmAnd GPX and change the route and re-save it, it still won't have street names for the parts I changed, right?

**Comment by sonora** [comment]
Best way is probably to simply create the route in OsmAnd by adding intermediate destinations, e.g. by long-tapping places on the map, then use the blue 'flag' button on the point's context menu. (You can also use search or Favorites etc. to add destinations to the route.

If you use non-OsmAnd mechanisms to produce gpx route files, you would have to either find one which includes the street names and in the right format, or manually edit the file to add them which is probably tedious.

I guess we can close this issue, as it seems nothing which can be fixed in OsmAnd, right?

**Comment by tjated** [comment]
Yes,
