### ISSUE TITLE
[Contour lines plugin] Nice to have: Altitude in context screen

### ISSUE THREAD

**Issue by SergeyP2** [osmandapp/OsmAnd#3939]
It will be very convenient to have "Altitude" info in a context screen of POI and any other arbitrary point. 

Thanks!

(Attached are screenshots of my suggested UI changes)
<table style="width:100%">
  <tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/22505250/27260856-5c7ebdc6-5436-11e7-8a51-cb177723cef7.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/22505250/27260857-5c9aa2d4-5436-11e7-8d64-ed09180de3a0.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
It might duplicate, today we can't show that information cause we don't have full DEM files on device. These files could be very big.

**Comment by SergeyP2** [comment]
I don't know what the "full DEM" files are, my suggestion is to use existing data that is used to draw contour lines. You can use the altitude of the nearest line, or better use linear extrapolation between two lines. This will be already good enough.

**Comment by davidoe** [comment]
This seems to be possible now, as altitude is displayed for calculated routes, too.

**Comment by FTno** [comment]
OruxMaps has an Altitude from DEM (.hgt files) feature there altitude is measured in the center of the screen/map, and excellent data can be downloaded from here: https://data.opendataportal.at/dataset/dtm-europe.
These are big files, but why not let the user download the files he needs with a web browser and then unpack the hgt files to a folder where OsmAnd can read the files and display the altitude in a similar fashion like Orux or like OP asks for.

**Comment by scaidermern** [comment]
Related to #2487.

**Comment by vshcherb** [comment]
- Flow layout

<img width="200" src="https://user-images.githubusercontent.com/1042025/193859074-ff0e4613-a2f9-44a0-83ce-7f79af9ab43d.jpg" />
<img width="200" src="https://user-images.githubusercontent.com/1042025/193859106-c87a4220-03dd-4258-a297-791e064de808.jpg" />

**Comment by nazar-kutz** [comment]
**Pull Request**
* https://github.com/osmandapp/OsmAnd/pull/15501

**Comment by dmpr0** [comment]
Don't work or I don't understand how it should work.
