### ISSUE TITLE
Nice to have: Save custom POI filter in file and Restore from file

### ISSUE THREAD

**Issue by SergeyP2** [osmandapp/Osmand#3940]
I love functionality of "custom POI filters" and have gradually created 20+ of them. The problem arises when I buy new phone and want to transfer them -- the only way I know is to manually recreate them on new phone / tablet step by step. Since there are 20+ of them, and some of them have dozens of items checked, it takes me literally hour or even more. I want to suggest command in UI that would save the settings of custom filter (or all of them) in file(s), and another command that will be able to create them based on file(s). In order to do this you can add one more standard folder in "Android \ data \ net.osmand.plus \ files" folder, for example "filters" -- it will be a storage for saved filter files and for files that user want to restore. I am not sure where is the best place in UI to put this Save and Load command for custom POI filter, obviously there are several places to choose from. Also this would allow users to share custom filter.

Thanks! It would save a lot of time :)

![screenshot_2017-06-18-16-00-52](https://user-images.githubusercontent.com/22505250/27260944-e981eeda-5438-11e7-9bb7-63e2a8e060f3.png)

**Comment by vshcherb** [comment]
I know this could be a very annoying issue, could you please consider Backup tools. All poi filters are stored in the file anyway but that file is internal memory of application. It should be transferrable, we don't want to expose that file and other settings file to external memory. 

Backup tools allow to backup internal files, copy and modify them.
