### ISSUE TITLE
Incorrect route calculation.

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#3941]
Error when calculating route here: https://www.openstreetmap.org/note/new?lat=49.93144&lon=8.59595#map=19/49.93141/8.59687&layers=N

The route is calculated off any road. See screenshots.
![osmand-1](https://user-images.githubusercontent.com/20681525/27262050-a240e30e-5457-11e7-88c6-5d99a6dde0c6.jpg)
![osmand-2](https://user-images.githubusercontent.com/20681525/27262051-a2444de6-5457-11e7-933e-509ba3623943.jpg)

**Comment by xmd5a2** [comment]
Not reproducible with bicycle profile
![screenshot from 2017-07-13 20-48-19](https://user-images.githubusercontent.com/5829014/28180066-a27e04a0-680c-11e7-9b0e-2314ff6a24d3.png)
