### ISSUE TITLE
German names on some streets in Poland

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#3943]
Some street names are displayed in German in the Polish city of Szczecin: https://www.openstreetmap.org/note/1011853#map=16/53.4311/14.5543&layers=N

Setting the map language to Polish does not solve the issue.
![screenshot_2017-06-19-09-58-23](https://user-images.githubusercontent.com/20681525/27276939-5dd74666-54e5-11e7-94a5-89c5f7c4f528.jpg)
![screenshot_2017-06-19-10-23-51](https://user-images.githubusercontent.com/20681525/27276938-5dd6338e-54e5-11e7-9ba9-e8a21f56ffb2.jpg)

**Comment by xmd5a2** [comment]
Can't reproduce even if display language is polish

**Comment by PaulStets** [comment]
Another complaint with the same issue. This time in Gdańsk (Poland).
![screenshot_2017-06-30-11-53-18](https://user-images.githubusercontent.com/20681525/27740405-9a973b28-5dba-11e7-9612-866b9a440ece.png)

**Comment by polarbearing** [comment]
What has the note cited in the first post to do with the issue?

I checked the data history of one of the ways: https://www.openstreetmap.org/way/23461100/history
It has a tag ```name:de=Kaiser-Wilhelm-Straße```, however it has not changed for the last 5 years.
 
@PaulStets - could you check your OsmAnd languge settings, maybe they are set to show German labels?

**Comment by vshcherb** [comment]
The problem is reproduced with road-only maps (full maps work fine)

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-core/commit/be6fb6fe91e6add34c79362013eee424a8311505
