### ISSUE TITLE
Deprecated old-style multipolygons in OSM data

### ISSUE THREAD

**Issue by joto** [osmandapp/Osmand#3947]
I wanted to inform you about some changes in OSM data recently that might or might not be relevant for you.

OpenStreetMap has finally gotten rid of "old-style multipolygon relations". Those are relations of `type=multipolygon` where the tags are on the (outer) ways and not on the relation. For a long time this type of tagging and the more modern one of tagging the relation only have lived side-by-side, but now old-style multipolygons are deprecated and none are left in the data.

If your routing engine/data converter does support routing over areas you might want to change your data import functions to remove handling of old-style multipolygons simplifying the code greatly.

If you do not support routing over areas you might still be affected: Say you have a city square modelled as a relation tagged with `highway=pedestrian`. In modern multipolygon tagging those tags are on the relation only and the ways have no tags at all. If you don't read relations and match them to their member tags, you will not see those ways as routable. So even routing along the edges of the city square will not work. Details depend on the e
xact tagging of course, in many cases the ways will probably also be tagged with a `highway` tag. You have to decide yourself whether this warrants any changes in your program.

Our Github issue for this is https://github.com/osmlab/fixing-polygons-in-osm/issues/33 where you can find some additional information.

More background on multipolygon relations and the effort to fix them at http://area.jochentopf.com/ .

**Comment by vshcherb** [comment]
Thanks for information, we support the new way of multipolygons
