### ISSUE TITLE
In-app purchases in OSMAnd ???

### ISSUE THREAD

**Issue by KOLANICH** [osmandapp/Osmand#3948]
https://github.com/osmandapp/Osmand/search?q=net.osmand.plus.inapp
In-app purchases (glitchy ones in OSMAnd~, they show error messages sometimes, for example when I open list of downloads) for full version, maps, depth maps, "live", etc ...
Do you really expect in-app purchases working in a free open-source app?

**Comment by dmpr0** [comment]
Hi, nightly not stable version, it can have an errors, please use stable release versions from [Google Play](https://play.google.com/store/apps/details?id=net.osmand) or [Amazon.](https://www.amazon.com/gp/product/B00D0SEGMC/ref=mas_pm_OsmAnd-Maps-Navigation)

**Comment by vshcherb** [comment]
Question is not clear...
