### ISSUE TITLE
Custom renderer - Names do no longer show up

### ISSUE THREAD

**Issue by PhilippeDeFranclieu** [osmandapp/Osmand#3949]
Hi Osmand support,

I've created and used a custom renderer (attached PaPoPCn.render.xml file) which did work well last years (but the underscore in the file name long time ago).
It is supposed to render the limits of cadastral parcels and their nature (see PC_STYLN attribute, ie wood, meadow, water, etc.).

I've some problems now with the latest version(s) of Osmand as the names' values do no longer show up.
Thank you in advance for you help.
Would you have any question to clarify this issue, please let me know.

Best regards,

Philippe de FRANCLIEU
philippedefranclieu@gmail.com

see attached, in a zip file:
- 2 screenshots (when things did work well, when things do no longer work as expected); 
- PCn.osm; 
- PaPoPCn.render.xml; 
- 41-Les Bastes_Pcn.obf.

[NamesNoLongerShowUp.zip](https://github.com/osmandapp/Osmand/files/1092647/NamesNoLongerShowUp.zip)

**Comment by xmd5a2** [comment]
Can't figure out how this style worked and why it doesn't work. But try this:
1)Remove boundary=administrative,admin_level=12 tags from osm xml
2)Make obf using rendering_types.xml with something like that
```xml
	<type tag="parcel" value="boundary" minzoom="11"/>
	<type tag="PaPo:PC_STYLN" value="1" minzoom="11" additional="true"/>
	<type tag="PaPo:PC_STYLN" value="2" minzoom="11" additional="true"/>
	<type tag="PaPo:PC_STYLN" value="3" minzoom="11" additional="true"/>
	<type tag="PaPo:PC_STYLN" value="4" minzoom="11" additional="true"/>
	<type tag="PaPo:PC_STYLN" value="5" minzoom="11" additional="true"/>
	<type tag="PaPo:PC_STYLN" value="6" minzoom="11" additional="true"/>
	<type tag="PaPo

:PC_STYLN" value="7" minzoom="11" additional="true"/>
	<type tag="PaPo:PC_STYLN" value="8" minzoom="11" additional="true"/>
	<type tag="PaPo:PC_STYLN" value="9" minzoom="11" additional="true"/>
	<type tag="PaPo:PC_STYLN" value="10" minzoom="11" additional="true"/>
	<type tag="PaPo:Type" value="PF" minzoom="11"/>
```
3)Use this fixed style https://www.dropbox.com/s/e2i8sh8kdvhgpzf/PaPoPCn.render.xml?dl=0

**Comment by xmd5a2** [comment]
![screenshot from 2017-07-11 22-34-32](https://user-images.githubusercontent.com/5829014/28086869-257cfd00-6689-11e7-8f54-6b9599748dc5.png)

**Comment by PhilippeDeFranclieu** [comment]
Thank you xmd5a2.

_"Can't figure out how this style worked and why it doesn't work. "_
Yes, this why I did ask the question!

OK, your solution works.
Then I'll have to run OsmAndMapCreator and create quite a few OBf files again...

Best regards,

Philippe de FRANCLIEU
philippedefranclieu@gmail.com
