### ISSUE TITLE
File size of recorded gpx tracks shown wrong (MB instead of K(i)B)

### ISSUE THREAD

**Issue by csarn** [osmandapp/Osmand#3950]
When I want to navigate by a previously recorded GPX route, in the gpx file selection screen, the file size unit is wrong. For a 326 KiB file, it will show 326 MB. I have no files that are actually in the megabyte range, so I don't know if those would show up as GB or not.

**Comment by njohnston** [comment]
Possible duplicate of #3820 and #3706.

**Comment by csarn** [comment]
Alright, sorry for not searching closed tickets, then. I'll close this.
