### ISSUE TITLE
Osmand Crash if it has to open a googlemaps routing link

### ISSUE THREAD

**Issue by Mannshoch** [osmandapp/Osmand#3951]
Osmand 2.6.3 f-droid
Android 6.0.1
Example link created by SBB app: [http://maps.google.com/maps?saddr=47.366608,8.548463&daddr=47.364154,8.535725&dirflg=w](http://maps.google.com/maps?saddr=47.366608,8.548463&daddr=47.364154,8.535725&dirflg=w)

Crash on click on the coordinate entry as seen below.
![crash-osmand](https://user-images.githubusercontent.com/7795891/27420655-38c35574-5727-11e7-93b4-ad54bbde64eb.png)

there is no crash if click on "Auf Karte anzeigen"

**Comment by vshcherb** [comment]
It was fixed in 2.6.4 (F-droid releases might be different)
