### ISSUE TITLE
OSM Live sometimes does not update OSM changes correctly

### ISSUE THREAD

**Issue by beppec56** [osmandapp/Osmand#3955]
I edited an existing path moving it into a new position, following a local survey. The changes does not show up correctly on osmand, it does not reflect the current OSM data.
Furthermore, the vector used for navigation are not updated as well, in this case for new paths as well.

As a reference, geo data in osm can be downloaded using Josm, downloading this bounding box:
min lat 44.8401689, min long 7.1121025; max lat 44.8510011, max lon 7.129612
The following is the resulting screen shown on osmand.
![bug-osmand](https://user-images.githubusercontent.com/943979/27453125-a57168aa-5795-11e7-8866-fb1928a2b099.png)

I disabled the region update, removed the region from the downloaded regions.
Downloading it anew and then enabling the live update, but nothing changed.

The problem surfaced earlier on another occasion, but then it was corrected in the montly update.

Android 7, tablet Samsung Tab S2, OsmAnd+ version 2.6.5. The concerned region is updated hourly.
Geo region is 'Italia Piemonte'.
I checked the bug on 'highway=path' only, didn't check other highway types.

**Comment by xmd5a2** [comment]
Note:
Data at 1 june https://www.dropbox.com/s/z0hpdvwmvm75h0c/italy_piemonte_europe.zip?dl=0
Diffs https://www.dropbox.com/s/4rp600cw6lojm5r/italy_diff.zip?dl=0

**Comment by vshcherb** [comment]
This road is getting duplicated at 14-06
http://builder.osmand.net/aosmc/italy_piemonte_europe/Italy_piemonte_europe_16_04_14.obf.gz
http://builder.osmand.net/aosmc/italy_piemonte_europe/2017_06_14/
Investigating to a specific commit

**Comment by vshcherb** [comment]
The issue found and fixed, we will try to regenerate existing maps.
