### ISSUE TITLE
Error Message while attempting to update maps

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#3960]
OsmAnd+ 2.6.5 with contour line plugin  on a HTC One M9 with Android 7.0.
I have installed yesterday the App twice after a total deinstallation, 1x on internal memory and 1x on the ext. SD Card as it was before. Both installations are showing the same I/O Error "can't delete old file" and OSMAND+ is not able to download map files although there is NO map file at all. The only file i can Download into a new installation is the relief file. Internal memory has 16GB and SD Card has 50GB available space. I have full access to the SD card and the internal memory over Norton Commander App and if i hook up the device to my PC also over Windows Explorer. 
After installation of OSMAND i was giving the app full rights except for camera and microphone.  
![screenshot_3](https://user-images.githubusercontent.com/20681525/27506742-5f3b80bc-58c8-11e7-83c6-b87b7ff67731.png)
![screenshot_5](https://user-images.githubusercontent.com/20681525/27506743-5f542ae0-58c8-11e7-9c43-827c225d0cc8.png)

**Comment by vshcherb** [comment]
Most likely permission is missing the solution could be to delete via file explorer and download files again.
