### ISSUE TITLE
Gpx with multiple tracks show as one track

### ISSUE THREAD

**Issue by lenzwerf** [osmandapp/OsmAnd#3963]
When you load a gpx file with more tracks (eg a track per day of travel) Osmand will show it as one track. The workaround is exporting every track into a separate gpx-file but that's a hassle and if Garmin users send you a track you always have to  split the gpx. I use Garmin Basecamp to create gpx-tracks.
So it would be nice if the separate tracks remain separate. I'm at Osmand+ 2.6.5 but it has been like this from the start if I remember correctly.

Best,
Lennert

**Comment by lenzwerf** [comment]
I'm sorry to get back to this but I've tested more nav apps and most of them import the tracks as they should. Last summer I got a gpx file from another traveller but I couldn't get Osmand to load the tracks because the merge of all the seperate tracks made Osmand crash. Please look into it it's quite common to put more than one track in a gpx file and Osmand makes a mess of that files.

**Comment by peteperil** [comment]
I have had a similar problem with multiple tracks in one file too.

Maybe OsmAnd could simply split the file into different files. Something like:
My Track Collection - Track 1 (Trackname)
My Track Collection - Track 2 (Trackname)

That should really be easy enough because the file format is a simple one.

**Comment by lenzwerf** [comment]
Yes but there's on thing. Waypoints that are in the same gpx file get embeded into the track so with two tracks Osmand can't tell which waypoints go to which track. They used to get imported as favourites I wouldn't mind getting that back.

**Comment by lenzwerf** [comment]
Osmand ignores the simple gpx tags of ending a track and starting a new one.
</trkseg>
  </trk>

  <trk>
    <name>Track 058</name><extensions>
      <gpxx:TrackExtension>
        <gpxx:DisplayColor>DarkGray</gpxx:DisplayColor>
      </gpxx:TrackExtension>
    </extensions>
    <trkseg>

**Comment by lenzwerf** [comment]
Yes I can. This is a typical example. If it imports normally you have a choice of a long or short bikeride but now they show as one in OsmAnd. I had to zip it because gpx isn't supported by Git.
[ATB-Heerenveen.zip](https://github.com/osmandapp/Osmand/files/1957599/ATB-Heerenveen.zip)

**Comment by Chumva** [comment]
This should be added here - https://github.com/osmandapp/OsmAnd/pull/13640
