### ISSUE TITLE
[bug] Search for further name labels

### ISSUE THREAD

**Issue by Matthias84** [osmandapp/Osmand#3966]
While #3511 seemed to introduce more name tags, the search seems mostly only to find name=* tags. While this is the usual usecase, it would be great to bring back the local knowledge of the OSM community and allow the search for abbreviations, alt. spelling, ....

Some examples here in Rostock, that are currently not found:
* ["Grünes Ungeheuer"](http://www.openstreetmap.org/way/34070019)
* ["Pornobrunnen"](http://www.openstreetmap.org/way/31775880)
* ["JAZ"](http://www.openstreetmap.org/way/294662178)

Maybe there is a different problem with the data or processing?
Is it just limited to highways?

OSMand~ 2.6.1, Germany-M-V map file 2017-6-1, LineageOS / Android 7

**Comment by vshcherb** [comment]
Added loc_name
