### ISSUE TITLE
Hide private parking by default

### ISSUE THREAD

**Issue by pwithnall** [osmandapp/Osmand#3970]
In a large, well-mapped city, the parking for individual houses or apartment blocks is often mapped, and marked as `access=private`. osmand should not show these parking areas, since they just distract attention away from the public ones where non-residents can actually park. I realise you can look at the details of each parking area to see whether it’s public or private, but that doesn’t scale.

For example, look at the area around http://www.openstreetmap.org/search?query=Kendal#map=16/54.3247/-2.7475 in osmand.

Before entering an issue please read the information below. 

> What version of OsmAnd are you using, on what device and Android/iOS version?

Version 2.6.5 on Android 7.0

> Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

Offline maps.

> If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

United Kingdom England, 2017-06-01

**Comment by jfburke3** [comment]
The same should be done for access=no, i think.

**Comment by rbovard** [comment]
The first step could be to have different icons to distinguish them as noticed here https://github.com/osmandapp/Osmand/issues/3894

**Comment by pwithnall** [comment]
I had a thought the other day: `access=customers` should probably also not be shown by OsmAnd, *unless* your destination is set to a node whose name matches the `operator` of the car park and you’re using a mode of transport which will need to be parked (i.e. not walking).

**Comment by scaidermern** [comment]
> I had a thought the other day: access=customers should probably also not be shown by OsmAnd, unless your destination is set to a node whose name matches the operator of the car park and you’re using a mode of transport which will need to be parked (i.e. not walking).

What if you are just browsing the map and looking for a parking area near a museum, cinema etc.? parkings marked as private or for customers (sometimes used interchangeably) should not be hidden but only marked accordingly. Maybe grayed out or with a less prominent icon.

**Comment by jfburke3** [comment]
@pwithnall That won't work very well. I know of several parking lots where operator= is the shopping center name but my destination is a single store in that shopping center. 

@scaidermern +1

**Comment by rbovard** [comment]
@scaidermern @pwithnall +1

@xmd5a2 Could you please try to address #3894?

**Comment by polarbearing** [comment]
@pwithnall - and there are more reasons that won't work. Often the operator for a customer car park is not set at all, or typed slightly differently in OSM than the adjacent shop. Also some customer car park operators allow 60 or 90 min to park independent of what you do on this time, they just don't want office workers to park there all day.

**Comment by pwithnall** [comment]
@polarbearing: Indeed, that approach as I’ve suggested won’t work. However, it would be nice to try to prevent the user from accidentally planning their journey to end in a car park they’re not allowed to park in. Short of introducing a more detailed tagging scheme for car park access, I think the suggestions for rendering `access=customers` car parks differently are the most appropriate.

**Comment by xmd5a2** [comment]
Commit related to issue https://github.com/osmandapp/OsmAnd-resources/commit/905be198fbfa26cb94955220d919a26b32306bdd
