### ISSUE TITLE
[Feature Request] Change units for TTS in navigations

### ISSUE THREAD

**Issue by DrDoctor13** [osmandapp/Osmand#3973]
I don't know if this is a setting somewhere, but despite the on-screen stuff being in miles, the TTS still says meters and kilometers.

**Comment by sonora** [comment]
What TTS language are you reporting this for?

**Comment by DrDoctor13** [comment]
This is in the English TTS. I noticed that it wasn't doing it while driving but instead if I was simulating a drive with the debug plugin.

**Comment by pebogufi** [comment]
Does it (km vs. miles) depend in language or in 
settings / globlal setting / driving regions ?
Peter

**Comment by sonora** [comment]
The unit system used solely depends on the driving region setting, and not on the display language, voice language, or map language selected.

Of course, the TTS config file used needs to support the unit system. I think I have once added this support for close to 40, essentially all at the time, of our TTS files. English is definitely ok and must fuly support all our km/miles/yard/feet/meter combinations.

Please note that when changing a driving region on the fly, or when it is in auto-select mode and you use simulations in different countries, an app restart or at least a new voice initialization may be needed for a change to become fully reflected. I assume this is the issue you report.

**Comment by njohnston** [comment]
Known issue: more details in #3679, which is in the 2.7 milestone :)
