### ISSUE TITLE
Search within disabled My Places / Favourites

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#3975]
I understand that it is logically correct not to search in disabled things (favourites and other), as it is now.

But favourites are a kind of archive for positions with two "levels", level 1=currently visible and level 2=currently not visible (show on map = false).
When searching in an archive it would be very helpful to get it searched in both "levels", at least in some cases (as it was in older versions).
So - is it possible, to get a option (checkbox) for "extended search also in disabled groups"
or find an other solution for a "extended" search in disabled favs ?
Thanks, regards Peter

Version: latest 2.7.0#21836M

**Comment by vshcherb** [comment]
It goes a bit in contradiction that we want to use disable Favorites Groups as not active GPX files (where we don't allow search right now). But I do see the value to have an item that will highlight you might have the search results in Disabled Favorites or Not Active GPX files. If it doesn't overlap much every time with search results, i think it is very valuable.

**Comment by littlehelper** [comment]
In "My Places" the option to disable favorites groups is named "Show on map". I would not expect to disable them at all by just not showing them on the map.
- If any favorite is not visible on the map I would love to still find it using the search. To indicate that favorites are not visible on the map I would propose to show them in italic gray as in "My Places" already. If I tap on the favorite in the search result I would expect to see the favorite temporarily on the map but in italic gray.
- If any favorite group is not visible on the map I would love to still be able to add favorites to these hidden groups. Therefore it would be good if all favorite groups are shown in the "Add/Edit Favorite" dialog. To indicate that favorite groups are not visible on the map I would propose to show them in italic gray as in "My Places" already.

For me it would be great if in future it will be possible to set visible or not visible each single favorite within random favorite groups. Therefore I would recommend to provide the option "Show on map" for all favorites in the "Add/Edit Favorite" dialog.

**Comment by pebogufi** [comment]
The second point (add fav to hidden group) was possible until a few days ago. 
@vshcherb 
I also would love very much to get this feature back.

**Comment by vshcherb** [comment]
It clearly depends on the favorites usage, we've encountered people have groups that need to be  disabled cause they clutter map, search, add and so on. 
Though I would agree that cluttering list of categories to add could be very minor and could be added back.

There is no good solution for this issue except extra configuration which is also bad solution.

**Comment by vshcherb** [comment]
We made decision to display them in search of Favorites i.e. inside My places but not in the main search. Cause there are many users that have imported multiple points to Favorites and keep them disabled, so they shouldn't abuse the main search.
In Search of Favorite places: 
1. They should have grey icon
2. Be on the bottom of the search always
3. Have Italic font

**Comment by pebogufi** [comment]
Great idea, (for me) nothing more is needed. Thanks a lot.
