### ISSUE TITLE
"Unsupported attachment" when trying to share GPX-files 

### ISSUE THREAD

**Issue by Aiurek** [osmandapp/Osmand#3977]
OsmAnd+ 2.6.5, released 2017-05-31
Samsung GT-I8190 running Andorid 4.1.2

When trying to share recorded GPX-files via Messenger or E-Mail, the toast message "Unsupported attachment" appears and nothing is shared in the messenger, respectively a mail without attachment is send. 
Couldn't verify, whether this issue appears also for other sharing techniques, e.g. Wi-Fi Direct or Bluetooth.

![pic1](https://user-images.githubusercontent.com/27865200/27583458-bac22c06-5b34-11e7-9d71-c6581a24796d.jpg)

**Comment by vshcherb** [comment]
Share works with gmail and other programs like dropbox so it must be an issue with telegram.
