### ISSUE TITLE
Contour lines maps are not correctly generated if poly contains more than 1 rings

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#3979]
Malaysia, Mauritius and others. Only Borneo part of Malaysia is covered by contours in generated obf file.

**Comment by vshcherb** [comment]
Jenkins job that does it SRTM_CombineSRTMFIlesIntoCountryFile

**Comment by vshcherb** [comment]
Fixed
Just running in verbose mode gives
PROCESSING Mauritius lon [58 - 60] lat [-18 - -16] TOTAL 9 files [S16E058, S16E059, S16E060, S17E058, S17E059, S17E060, S18E058, S18E059, S18E060]

PROCESSING Mauritius lon [58 - 65] lat [-21 - -16] TOTAL 25 files [S16E058, S16E059, S16E060, S17E058, S17E059, S17E060, S18E058, S18E059, S18E060, S18E061, S18E063, S19E060, S19E061, S19E062, S19E063, S19E064, S20E061, S20E062, S20E063, S20E064, S20E065, S21E062, S21E063, S21E064, S21E065]

**Comment by vshcherb** [comment]
2 new parameters are added to CombineSRTMIntoFile to simplify run & testing:
--dry-run: will not do anything only print the tiles & countries
--filter=mauritania - will filter country by name (checks if substring exist)

@PaulStets @xmd5a2 may be we can create an utililty from this class in utilities.sh so we can run it
