### ISSUE TITLE
Visualization of house numbers

### ISSUE THREAD

**Issue by Aiurek** [osmandapp/Osmand#3980]
OsmAnd+ 2.6.5, released 2017-05-31
Samsung GT-I8190 running Andorid 4.1.2

The postitoning of house numbers is currently highly confusing. In OSM the house numbers seem to be centred relative to the buildings geometry, whereas in OsmAnd the house numbers are illustrated decentralized at the south side of the respective building. In many cases one can't really tell which building a house number belongs to. Furthermore, single house numbers are apparently hidden at low mag, due to limited illustration space.
Is it possible to illustrate the house numbers in the buildings center and maybe reduce the font size slightly to illustrate the house numbers in a less confusing and more structured way?

![pic2](https://user-images.githubusercontent.com/27865200/27585000-abaed484-5b3a-11e7-8e5d-c6fa8fdfe70d.jpg)

**Comment by vshcherb** [comment]
This is a duplicate and already fixed. It will require new maps for 2.7 and we plan to make it available in August maps with 2.7 version.
