### ISSUE TITLE
Incorrect bicycle route calculation.

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#3981]
The route calculation using bicycle navigation mode is incorrect here: http://www.openstreetmap.org/#map=16/56.0436/37.5030

Screenshot: 
![19549830_1874822912764514_2108929970_o](https://user-images.githubusercontent.com/20681525/27586188-fa380e06-5b47-11e7-96ba-34041aad6b82.png)

**Comment by vshcherb** [comment]
This is correct due to map coverage in this area.
