### ISSUE TITLE
Bicycle navigation ignores bicycle:conditional=yes

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#3984]
http://www.openstreetmap.org/node/1576569933#map=14/53.6626/9.5752

The bicycle route is not calculated through the gates.
![19532895_1874842202762585_923144621_o](https://user-images.githubusercontent.com/20681525/27587723-0d584162-5b4e-11e7-8ebb-b938f508bdb1.png)

**Comment by pebogufi** [comment]
Try using profile bicycle when you want to use bicycle routing. In the screenshot you use profile globe which internal uses profile car, as far as I know.
Regards Peter

**Comment by vshcherb** [comment]
Duplicate for time range conditional
