### ISSUE TITLE
Track recording does not work.

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#3985]
Many users complain, that the track isn't being recorded after they press Record. The notification says that the track is being recorded, but the distance is always 0.

Devices: Motorola G3, Huawei Mediapad M3.

![img_20170626_165132](https://user-images.githubusercontent.com/20681525/27591153-88c0fd66-5b59-11e7-8fa7-8c47c7ee3188.jpg)

**Comment by sonora** [comment]
Paul, I do test and use our GPX logging a lot, and have to say I cannot reproduce this. So I think we need more details here how exactly people start the logging (does it depend if they tap on the widget or on the start button in the notification bar), and also which of our filters for minimum displacement/motion detection, minimum accuracy, or minimum speed they use in the Trip logging plugin settings..

My current suspicion is that one of these filters may be set. While our default for all these now correctly is "Not selected", I think we may have had interim releases where some of these filters were set to some non-zero value, so please ask to check and disable these three and retry, ok?

**Comment by PaulStets** [comment]
Thanks, I'll do that. Will post an update here.

**Comment by sonora** [comment]
PS2: Newer versions of Android also seem to have a power saving set hindering apps from repeatedly accessing GPS, see https://github.com/osmandapp/Osmand/issues/3923#issuecomment-309232409 . That may also be worth checking.

**Comment by PaulStets** [comment]
That was my first guess. Didn't help.

**Comment by PaulStets** [comment]
Thanks, the advice about setting filters to "Not Selected" seems to work.
