### ISSUE TITLE
nautical feature request: waterway-routing

### ISSUE THREAD

**Issue by Dirk--** [osmandapp/Osmand#3990]
How about adding inland waterway routing?

I might be able to assist: http://routino.grade.de

Have a nice day, Dirk

**Comment by vshcherb** [comment]
Sounds really good, I like it. How can we make it?

**Comment by Dirk--** [comment]
all european navigabe waterways should have a key
- boat=yes
- motorboat=yes
- CEMT=*
( https://wiki.openstreetmap.org/wiki/User:Kannix/Routino )

Bridge clearance heights and locks (as an important limiting factor) should be part of this dataset:
- https://wiki.openstreetmap.org/wiki/Tag:seamark:type%3Dbridge
- https://wiki.openstreetmap.org/wiki/Seamarks/Gates
- https://wiki.openstreetmap.org/wiki/Key:lock (some might also have seamark:type=lock basin keys)

See also:
- https://wiki.openstreetmap.org/wiki/Inland_navigation
- https://wiki.openstreetmap.org/wiki/Category:Navigable_Waterways

**Comment by vshcherb** [comment]
I think there is no problem at all to include in our routing data all these tags https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml
Then we can change routing.xml and create necessary parameters. 
Please note that you can do it & test with any code writing today with MapCreator.

**Comment by vshcherb** [comment]
Beta navigation is added

**Comment by Dirk--** [comment]
Thanks!
Future plans like adding rules on vessel's height (most important criteria on inland waterways), width, draft?
