### ISSUE TITLE
Base background color of area under the maps should = defaultColor in the render stylesheet

### ISSUE THREAD

**Issue by GHMJT** [osmandapp/Osmand#3992]
I'm finding the background color of the area under the maps to be distracting when rotating or otherwise moving about the map, because this area is highly visible when newly appearing sections have not yet been rendered. For example, see the gray un-rendered section at the top of this screenshot...
http://tkis.com/osmand-bg/rendering.png

This is much more apparent and distracting when setting the map orientation to "Compass" or "Direction of Movement", because the area extends into all four sides of the display while turning.

To be clear, I'm not referring to the defaultColor in the render stylesheet, but rather the base color of the application under the map itself. I'm not exactly sure what this area is identified as. If someone knows, please let me know so I can locate the color setting for this in the app build.

I've noticed the color of this area changes based on the Map Mode being Day or Night.

For Day Mode, the color is 90% white. For example, see this screenshot...
http://tkis.com/osmand-bg/day.png

For Night Mode, the color is 40% gray. For example, see this screenshot...
http://tkis.com/osmand-bg/night.png

Ideally, this color should be configured to match the defaultColor in the render stylesheet. Doing so would eliminate this distraction and would make rendering apparently faster. Another alternative would be to pre-render an area beyond the size of the display, but this could consume more processing and battery. I'd really like to see this match the render stylesheet defaultColor.

**Comment by vshcherb** [comment]
Java OsmAndMapTileView https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/views/OsmandMapTileView.java#L596

**Comment by GHMJT** [comment]
So it's the canvas. Oh this is fantastic. Thank you.
