### ISSUE TITLE
"Turn right/left" instructions when following winding roads along gpx tracks

### ISSUE THREAD

**Issue by givemeallyourspam** [osmandapp/OsmAnd#3993]
OsmAnd 2.6.5 on Android, following a gpx track that was
- exported as kml from a Google My Maps route
- converted from kml to gpx using gpsies
Using the offline Schleswig-Holstein map offered within the OsmAnd app for download.

Frequently, when there are bends in the road (but no junctions), there is a voice command like "In 200 m, turn right". This can be confusing when there is an actual junction coming up, but you are expected to follow the road (which just happens to have a bend).
A good place to replicate the issue are cloverleaf highway exits that are often announced as a series of about 3 right turns.

**Comment by givemeallyourspam** [comment]
Adding some screenshots to illustrate the incorrect turns in the route.

![screenshot_20170629-005203](https://user-images.githubusercontent.com/29706134/27664123-03523a4c-5c66-11e7-90f4-bea1ceacb082.png)
![screenshot_20170629-005240](https://user-images.githubusercontent.com/29706134/27664137-0f3c9604-5c66-11e7-93f1-cc513318111f.png)

![screenshot_20170629-005430](https://user-images.githubusercontent.com/29706134/27664149-1da670c0-5c66-11e7-8548-b466eeb0d0bf.png)

**Comment by sonora** [comment]
Please compare with having that same route calculated by OsmAnd's own routing offline engine:. I suspect the bogus turn instructions result from your 3rd party kml file, so this is not really an OsmAnd  issue....

**Comment by givemeallyourspam** [comment]
True, direct routing in OSMand does not cause this. However, I would still have expected a different, more error tolerant behaviour in OSMand, a behaviour where the route is just overlayed on the map, OSMand fits the GPS track to the map, and derives correct turning points and instructions from that map data/track data combination.

I may be misunderstanding the inner workings of OSMand and/or gpx tracks, but my expectation was that slightly faulty or imperfect gpx tracks would cause no further issues for following the route, no matter what the source of the imported track is.

Btw, my motivation for the import from Mymaps is the easier collaboration on routes/tracks but I guess anyone trying to navigate along a gpx track that was not created in OSMand could run into this issue?

**Comment by sonora** [comment]
GPX tracks are very versatile, they can contain mere location information as recorded track points, or waypoints (points selected as of special interest, and usually given a name), or even routing/turn instructions.

Not 100% sure, but I think depending on what any file you specify contains, OsmAnd of course tries to honor what is in the file over what it could produce by itself. Meaning: If you tell it to use the file for routing, and it contains routing or turning information, that would be used. So either you remove any bogus routing information from such a file (using and editor), or you simply display the file, then manually select points it contains (either waypoints or select manually on the map) and set them as intermediate destinations one by one. Then, then tell OsmAnd to do the routing and ignore the GPX file (other than maybe displaying it).

**Comment by sonora** [comment]
Yes, we could solve this via #4065 and #3908, just to add those cross references here.

**Comment by rochus** [comment]
Any advances on this issue? 

The problem also occurs when there's no bogus information in the GPX file. The attached GPX track contains a portion of a road on which I drove recently, and OsmAnd+ told me to turn, alghouth there are no junctions (there's one, yes, but I'm talking about the twisty parts). 

This is mildly confusing when sitting on a motorcycle and only listening to turn instructions.

[Steinenbronn.gpx.gz](https://github.com/osmandapp/Osmand/files/2280908/Steinenbronn.gpx.gz)

**Comment by Spaitz** [comment]
Any news? 
Please let me describe why this is important: the cycling community is full of sites, happenings, races, events and maps that rely on gpx created by others by navigating. Standard practice is to download this gpx file to a navigator. The times I tried OsmAnd at this have been very frustrating, as every winding on the road becomes a turn instruction, rendering navigation impossible. Turning off voice navigation and rely on visual map is an option that by bike is not always recommendable, as sometimes you better keep your eyes on the road. Recreating from scratch the gpx file of a 200km event that turns around winding gravel roads in an unknown place is unpractical, to put it mildly, besides there seem to be no practical apps around that do it in a straight forward way. Having OsmAnd recognize a turn instead of a curve would make it usable.

**Comment by vshcherb** [comment]
Yes it depends on #3908 which is hard to implement. If the GPX is created by OsmAnd for example from a route that would be definitely easier but implementing for a generic GPX is a hard exercise unfortunately. 
Probably we can make use of Measure Distance tool which could give much better information about turns.

**Comment by realrill** [comment]
Hi @vshcherb 
#3908 closed now with your comment saying nightly has fix for that. Does that mean this issue will be solved?

**Comment by vshcherb** [comment]
Yes this issue could be probably closed as well in future, now before starting navigation there will be dialog to approximate GPX with downloaded map data and in that case turn left/right will be calculated based on actual road data

**Comment by mugaict** [comment]
I have the same issue, there's a workaround? When it will be addressed? Thanks

**Comment by scaidermern** [comment]
> I have the same issue, there's a workaround? When it will be addressed? Thanks

Did you snap your track to the road? This behavior should no longer happen after snapping tracks to the road.

**Comment by mugaict** [comment]
> > I have the same issue, there's a workaround? When it will be addressed? Thanks
> 
> Did you snap your track to the road? This behavior should no longer happen after snapping tracks to the road.

What do you mean? I created the GPX track on kurviger.de and then I use it in OsmAnd. I must do something in the app?

**Comment by scaidermern** [comment]
> What do you mean? I created the GPX track on kurviger.de and then I use it in OsmAnd. I must do something in the app?

Yes, if you need good routing instructions then this isn't enough. With your approach OsmAnd has just the information from the track and doesn't use the road information from the maps.

You can tell OsmAnd to attach the track to the road network. To do this, select the track for navigation, then go to Options / Follow Track / Attach track to road (something like this). Then follow the instructions and select the correct profile. The calculation can take a while. Then save the track and use it for navigation. The resulting navigation instructions should be significantly better now.

**Comment by mugaict** [comment]
@scaidermern thanks for the information but I can't find any "Attach track to road" (or similar) option, I tried to find it in every possible menu...

**Comment by scaidermern** [comment]
> @scaidermern thanks for the information but I can't find any "Attach track to road" (or similar) option, I tried to find it in every possible menu...

Which OsmAnd version are you using?

With OsmAnd 4.2.x (or 4.1.x, should be the same menu) do one of following:

Either:
* Navigation / Option / Follow track / Choose track
* Select "Attach to the roads"
![photo_2022-05-17_09-44-53](https://user-images.githubusercontent.com/1040784/168757465-78b8f2ad-2055-4d0c-9324-a1f4c799715b.jpg)

Or:
* My Places / Tracks / <your track> / Options / Edit track / Options / Attach to the roads
![photo_2022-05-17_09-44-50](https://user-images.githubusercontent.com/1040784/168757552-fad551c0-1c35-4123-a398-dba2404c91e2.jpg)

**Comment by mugaict** [comment]
My version is 4.4.11 released on 12/15/2021, its the latest version available in the play store, as you can see I don't have this option in the menu (it's in Italian but you can see what I mean).
![screen](https://user-images.githubusercontent.com/46482335/168759417-fa15faba-f0b1-4a63-9cdb-e2acf1a6ed1f.jpeg)

**Comment by scaidermern** [comment]
Well, then check the other one. I mentioned two possible ways to attach a track to the roads.

There is also a third one: Plan route / Open existing track / \<choose your track\> / Options / Attach to the roads.

**Comment by mugaict** [comment]
Sorry but I tried all suggested path and the result is always the same, no "Attach to the roads" option found...

**Comment by scaidermern** [comment]
Strange. Maybe someone else is able to shed some light on this.

**Comment by vshcherb** [comment]
Beta is already out but 4.2 release is not yet. You can try beta https://osmand.net/docs/versions/future-android#join-beta
