### ISSUE TITLE
nautical: seamark:type=bridge

### ISSUE THREAD

**Issue by Dirk--** [osmandapp/Osmand#3999]
how about replacing your bridge-icons by commonly used ones?
* lifting bridge: 
  * http://wiki.openstreetmap.org/wiki/File:Seamark_lifting-bridge.png
  * seamark:bridge:clearance_height_closed / seamark:bridge:clearance_height_open
* opening bridge:
  * http://wiki.openstreetmap.org/wiki/File:Seamark_opening-bridge.png
  * seamark:bridge:clearance_height_closed / -
* fixed bridge:
  * http://wiki.openstreetmap.org/wiki/File:Seamark_fixed-bridge.png
  * seamark:bridge:clearance_height
  
on the POI side, I would love some additional information:
* river:waterway_distance
* seamark:name
* seamark:bridge:category
* seamark:bridge:clearance_height_closed
* seamark:bridge:clearance_height_open
* seamark:bridge:clearance_width
* vhf

phrases/de:
* please replace 'Seezeichenbrücke' with 'Brücke (Seezeichen)'

Some of this is also true on http://wiki.openstreetmap.org/wiki/Seamarks/Gates

Thanks, Dirk

**Comment by xmd5a2** [comment]
Fixed

**Comment by Dirk--** [comment]
thanks guys!
