### ISSUE TITLE
nautical: locks

### ISSUE THREAD

**Issue by Dirk--** [osmandapp/Osmand#4000]
please replace icons with commonly used ones:
* https://github.com/OpenSeaMap/renderer/blob/master/searender/symbols/Lock.svg
* https://github.com/OpenSeaMap/renderer/blob/master/searender/symbols/Lock_Gate.svg

Most of the interesting information (poi) is tagged on the line segment tagged 'lock=yes':
* e.g. http://www.openstreetmap.org/way/35285655

(and not on the node 'waterway=lock_gate':
* e.g. http://www.openstreetmap.org/node/79443923
* and http://www.openstreetmap.org/node/413596599
)

Thanks, Dirk

**Comment by xmd5a2** [comment]
Icons were changed. I tried to add seamark:type=lock_basin (where most info lies) to POI but for unknown reason it doesn't works. https://github.com/osmandapp/OsmAnd-resources/commit/3a4f787b18120d6e8b9f5d205b768f731fd434be

**Comment by Dirk--** [comment]
Thanks Leonid!
seamark:type=lock_basin is less common than lock=yes!
https://taginfo.openstreetmap.org/keys/?key=lock
https://taginfo.openstreetmap.org/tags/?key=seamark%3Atype&value=lock_basin
Have a nice day, Dirk

**Comment by Dirk--** [comment]
just downloaded the nightly build to explore your work:

some examples:
no relevant info: https://www.openstreetmap.org/way/155850483
info at: https://www.openstreetmap.org/way/155778313

no relevant info: https://www.openstreetmap.org/way/30969787
info at: https://www.openstreetmap.org/way/155780600

**Comment by xmd5a2** [comment]
I already wrote that I tried to add seamark:type=lock_basin (and convert to this tag all possible combinations like waterway=canal + lock=yes) to POI but issue is not solved for some reason. No need to check this especially until new maps generation.

**Comment by PaulStets** [comment]
Fixed with https://github.com/osmandapp/Osmand/pull/4910 https://github.com/osmandapp/OsmAnd-resources/pull/478

**Comment by Dirk--** [comment]
issue is still not solved: No nautical POIs at locks ...
