### ISSUE TITLE
More Quick Action choices

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#4002]
While the Quick Action button became popular very quickly, the options it can be configured for are still quite sparse. 

This should be a meta-ticket for discussing which further options should be offered for this button, to avoid too many disparate tickets for this topic. 

So on top of my wishlist is an option for **"Finish navigation".** This is available via a number of clicks in the dashboard, but used very frequently, e.g. when the routing was just a test, or when a good parking spot was found 50 m before the system has recognised the destination.

**Comment by vshcherb** [comment]
Please share the actions you would like to see.

**Comment by polarbearing** [comment]
As said above, 
* Finish navigation
would be a good candidate, also 
* pause navigation 
would be used more frequently when going into a shop if it were quicker accessible. 

I just notice that I cannot find a method to **remove** a configured quick action from the list, thus probably a long tap on an action should offer removal. Alternatively, the "add" button could be "add/remove" or "configure", and the list of actions have option switches.

**Comment by polarbearing** [comment]
Thanks for implementing!

Now there is still no method to **remove** a configured quick action from the list, at least I cannot find one. Should we reopen for this part or make a new issue?

**Comment by AlexSyt** [comment]
@polarbearing Hello)

Try to see here: 
Configure screen -> Quick action
There you will see a list of all configured quick actions with button for remove.

**Comment by polarbearing** [comment]
Found, thanks. 
Now we have one method to only add actions, and one to add and remove. This is a bit confusing UX. 
My suggestion would be to drop the "add action" button from the Quick tableaux, and leave all configuration to the "configure screen" menu, which is the logical place for configurations.
Even more consequently, the individual actions in the config menu could be sliding switches.
