### ISSUE TITLE
Wrong instructions during routing

### ISSUE THREAD

**Issue by kroeckx** [osmandapp/Osmand#4003]
Hi,

I was going around this node:
https://www.openstreetmap.org/node/2298607026

And needed to pass this node:
https://www.openstreetmap.org/node/1494704286

But it told me to go right around this node:
https://www.openstreetmap.org/node/181315828

It also had the name of Spekstraat on the screen at that time, while I clearly didn't need to be there.

The route it displayed on the screen was correct, it was displayed straight, but it told me to go right while I needed to get left about 300 meter further.

I was using the offline routing. I'm using the 2.6.3 version on f-droid.

**Comment by sonora** [comment]
Is it reproducible? Or was it maybe just a transient matter of bad GPS reception.

I guess for anyone trying to reproduce you have to ate least specify the exact start and destination point...

**Comment by kroeckx** [comment]
I don't know if it's reproducible or not, but I can try again.

I do have a gpx track of it, but prefer not to post it here.

**Comment by sonora** [comment]
A track is not needed. If you just state the start and end point of the short piece on your route between which the issue occurs, any of our support staff can run a simulation to try to reproduce this.

I am confused with the 3 points you specified above because I cannot figure out from where to where you were trying to go vs. where you actually did go vs. where the issue occurred. So please again state the From: node, the To: node, and the point where you think the wrong turn instruction sounded in between.

**Comment by kroeckx** [comment]
The nodes above are in order: from, to, where it went wrong

**Comment by sonora** [comment]
I think it must have been some transient phenomenon, maybe with GPS reception causing OsmAnd to temporarily think you were elsewhere.

I happened to have an old Belgium map on my device (April 1, 2014, but that should not be an issue) and I created the route with this map, see screenshots below. When I simulate the route, neither turn announcements nor voice prompts said anything about a false right turn.

<img width="108" alt="screenshot_2017-07-01-13-00-07_" src="https://user-images.githubusercontent.com/845735/27761587-114795ac-5e5f-11e7-9b6e-62711cc209e6.png"> <img width="108" alt="screenshot_2017-07-01-13-00-12_" src="https://user-images.githubusercontent.com/845735/27761588-1472fc76-5e5f-11e7-9d99-84ef560c5329.png">

I guess you should try again with the current Belgium map and see if this is really reproducible.

**Comment by kroeckx** [comment]
I was unable to reproduce it.
