### ISSUE TITLE
Crashes on Xperia SGP511

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4005]
The app crashes at the start. Sometimes it is possible to activate the app when the user put the app in the background and then in the foreground again. Hard reset didn't helped.
Exception log:
https://www.dropbox.com/s/d0bk5wxaora8aqj/exception.log?dl=0

**Comment by vshcherb** [comment]
That issue is not possible to reproduce on any similar device, unfortunately we don't have xperia sgp511 available.
