### ISSUE TITLE
App restart needed after Storage folder change

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#4006]
We have occasional user complaints that OsmAnd under some circumstances does not correctly find already downloaded maps even after you set the Storage folder setting to point to the correct folder.

It is my experience that after the storage setting is corrected to point to the right folder, the maps get initialized ok, they are also immediately visible under Download maps / Local, but the map screen remains blank until the next app start. That causes some users to not recognize that everything is fine and only an app restart is required, so they continue experimenting.

I am not sure what the use case is when users get in this situation at all, but I guess it would not hurt if we either fixed that, or maybe just introduced a Toast after any Storage folder change saying that an app restart is required before the change fully functions?

**Comment by vshcherb** [comment]
Agree we should introduce message to restart the application in the same way we do for some other settings
