### ISSUE TITLE
Regression: Many motorway exits not recognized as turn anymore

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#4011]
What version of OsmAnd are you using, on what device and Android/iOS version?

Using nightly build 2.7.0 #21903M,released 2017-07-01 on Samsung Galaxy S4, Android 4.2.2

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

Using my own US Georgia map built using osmandMapCreator and the June 30 download from Geofabrik, and your US Florida map dated May 31.

__*In case of wrong routing:*__

Tell us whether you have used OsmAnd's in-app offline routing, or any online routing provider like YOURS, OpenRouteService or OSRM.

OsmAnd routing 

What routing profile is choosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest)

Car profile 

Please specify as exactly as possible the start and end point of your route by telling us city name and street name so that we can find it via in-app address search easily. Also a permalink from openstreetmap.org can be helpful.

Same as the lane guidance issue. Trip from Atlanta to Tampa. When i exited for gas at my planned destination  (as in, the gas station i marked as my destination for the first part of the trip), OsmAnd failed to give directions to exit the freeway. Instead, it told me where to turn after exiting. The appearance was as if it were an at-grade intersection instead of a grade-separated junction. 

The same thing happened on the second half of my trip. OsmAnd failed to actually tell me to "keep right" to exit. 

It doesn't seem to matter what the actual start and end points are.  Pick any random place near Atlanta and and gas station near an exit south of Atlanta.

**Comment by sonora** [comment]
Can you please specify an example so we know what we are talking about. Just specifying the node of an exit that fails to be recognized as a turn should suffice.

**Comment by sonora** [comment]
Also: You mentioned you use a brand new map you created yourself on June 30. Sounds to me like you should first consider the possibility that there is an issue with that map, and maybe test going back to your previous map and/or our OsmAnd Georgia map on the server. Using our 'official' map would also increase the chances that we can reproduce and debug this. Thx!

**Comment by jfburke3** [comment]
I'll get you the examples in a bit. It also fails with your official Florida map.

**Comment by jfburke3** [comment]
Ok, here's a route that will reproduce the problem.  To generate this, I used:

Start node:
Ramada Temple Terrace/Tampa North
http://osm.org/go/ZDd8vMVcn?way=37007313

Destination Node:
Brandon Regional Hospital
http://osm.org/go/ZDdv4VUXb--?way=408940337

(For privacy, not my real destination, but it reproduces the problem well.)

My Samsung Galaxy S7, Android 6.0.1, OsmAnd nightly build 2.7.0 #21654M, released 2017-06-06, your official US Florida map from May 31, 2017.  This produces "good" directions for the exit.

My Samsung Galaxy S4, Android 4.2.2, OsmAnd nightly build 2.7.0 #21903M, released 2017-07-01, your official US Florida map from May 31, 2017.  This fails to give exit directions.

For both of these, I used Shortest Way with none of the Avoid boxes selected.

Screenshots from the S7 route map and steps.  Step 7 appears to be the exit-from-the-freeway one that is missing from the S4 directions.

![osmand exit direction-works-s7-directions s](https://user-images.githubusercontent.com/11140831/27771106-5abc40c2-5f16-11e7-8420-ce45cd1a610d.png)
![osmand exit direction-works-s7-map view](https://user-images.githubusercontent.com/11140831/27771105-5abb392a-5f16-11e7-87a0-cc5c92728eb6.png)


Screenshots from the S4 route map and steps.

![osmand exit directions-fails-s4-directions s](https://user-images.githubusercontent.com/11140831/27771120-79d9daf0-5f16-11e7-8686-ca8ff1d47bb4.png)
![osmand exit direction-fails-s4-map view](https://user-images.githubusercontent.com/11140831/27771119-79d313be-5f16-11e7-9e1b-e91956ed6db9.png)

If you change the destination (keep the same start point) to:
Riverview High School
http://osm.org/go/ZDdrepXzV?node=358738860

to force a different exit, the same problem occurs.  As far as I can tell, every exit produces the same problem.


I will note that before I installed nightly build #21903M on the S4 (running whatever previous nightly build I had on it, not sure which, but likely the same one that is on my S7 now), I used it for general routing over the past week or two, and did not have any problems with exit directions.

**Comment by sonora** [comment]
Thanks for reporting! I can now reproduce in many places. Yes, it is a regression which slipped some time in June.@vshcherb

**Comment by vshcherb** [comment]
Duplicate to #4011

**Comment by polarbearing** [comment]
mine was 2.7.0#21876M/2017-06-28, and I had this observation in the south of Berlin; when driving northbound on the A113 , and had to fork onto the A117. No turn instruction, and display changed from "being on A113" to "being on A117". Behaviour confirms in simulation.
