### ISSUE TITLE
Notification interval

### ISSUE THREAD

**Issue by RobinRosseeuw** [osmandapp/Osmand#4014]
I have a question about the notification interval OsmAnd uses. I have a bicycle computer which gets the notifications from my Android smartphone. Now, when I use Osmand to navigate/to follow a GPX track, I get new notifications almost every 5sec. Is there any way to set a custom notification interval, or to get only a notification at the distances where there is spoken guidance (e.g. 200m and 50m before a turn)?
The Dutch notification message for a roundabout is a bit too long too. My bicycle computer screen is limited in number of words it can show for a notification, so could it be switched from "On the roundabout, take ....(the 3rd exit)" to "Take the 3rd exit... (on the roundabout.) The text between parentheses is the text my bicycle computer omits. Thank you in advance for your reply!

**Comment by jfburke3** [comment]
If you go into Settings->Navigation Settings->select Bike, then scroll down, you'll see Announce,  Repeat Navigation Instructions,  Arrival Announcement,  etc.  Not sure if one of those will help you. 

By the way, this type of question is probably more appropriate for the Google group. 

-jack
