### ISSUE TITLE
Change inconsistency of some strings.

### ISSUE THREAD

**Issue by franco999** [osmandapp/Osmand#4015]
Some inconsistent strings should be changed.
Also, it is better to clarify once in the category title than in each option value. For example, in the English version there are many categories with only the string "Type".

![1](https://user-images.githubusercontent.com/12088580/27773590-693cb89c-5f53-11e7-923a-06a8457447ee.jpg)
-
![2](https://user-images.githubusercontent.com/12088580/27773598-81a6e9d4-5f53-11e7-95ec-43d3d2634367.jpg)
-
![3](https://user-images.githubusercontent.com/12088580/27773588-6935d4dc-5f53-11e7-8301-cdd866ed9b50.jpg)
-
![4](https://user-images.githubusercontent.com/12088580/27773589-6937b8ec-5f53-11e7-9f36-ff3f22bbefe4.jpg)
-
![5](https://user-images.githubusercontent.com/12088580/27773591-693d4316-5f53-11e7-8232-a400c6e78af6.jpg)
-
![6](https://user-images.githubusercontent.com/12088580/27773592-693dac98-5f53-11e7-951a-a3ad6b7a3b44.jpg)

**Comment by xmd5a2** [comment]
> For example, in the English version there are many categories with only the string "Type".
''
<string name="poi_fire_hydrant_type">Type</string>
''
It is better to display only "Type:*" than duplicate POI type name here.
