### ISSUE TITLE
Auto download month map for osm live areas

### ISSUE THREAD

**Issue by HolgerJeromin** [osmandapp/OsmAnd#4034]
I have set an area to weekly osm live update.
The update stopped on the 4. June because i did not download the monthly base map.

It would be nice if i could optional configure to update the base map for an osm live area, too.

**Comment by vshcherb** [comment]
Should be working, we will double check the update mechanism.

**Comment by HolgerJeromin** [comment]
I have configured live to nightly download, which works (it downloads even today fresh stuff 2017-08-13), but the main map of this region dates 2017-07-01

**Comment by HolgerJeromin** [comment]
Not relevant anymore.
I can have live data with a many month old base map
