### ISSUE TITLE
Search results: more wrong housenumbers and strange results

### ISSUE THREAD

**Issue by CJTmmr** [osmandapp/Osmand#4042]
Using latest nightly,

My Location is somewhere near Gouda, The Netherlands (52.01731 / 4.71091)

Search using Adress: searching for Winterdijk 8 in Gouda:

Town: "Gouda" -wait for results - press "Gouda"
Enter streetname: "Winterdijk" - wait for results:
You get a long list with numbers, starting wiht 1-101, 1-102 etc. ; This is okay. There is one building (no 1) with many appartments, all with a unique subnumber; and many more numbers ofcourse.

Then in the search box", after "Winterdijk" enter "8, since you are looking for no. 8 and you don't want to scroll down 50 items or so.
This is result:
![2017-07-05 08 22 21](https://user-images.githubusercontent.com/15076257/27883025-5684c05e-61cf-11e7-8b14-8b9f306ef1c2.png)

The first results are POI-types:  Gasstation with octane **8**0... and Nuclear explosion site (altitude **8**0 km)
And then again housenumbers 1-101, 1-102 etc.

I would expect only housenumbers starting with 8 (or subnumber starting with 8)

This is just one example of many in The Netherlands

**Comment by vshcherb** [comment]
This is a duplicate issue which is already fixed (except benzine issue). There was a mistake in interpretation of "1-107", it was interpreting as "1,2,3,4,5, ... 107". 
I think the previous issue was reported by you as well. Fix will be in 2.7
