### ISSUE TITLE
Route calculation indication

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#4043]
In builds from recent weeks (I think including the last release) I notice that after you tap the navigation button (route calculation with a destination already set) the indication that "something happens" somehow became somewhat unreliable.

Particularly for each first route calculation after an app start, it seems that even during the route config dialog is visible, and with a position fix already found, there is no route progress indicator shown. This can stay like this for say 20 seconds or so, leading many uses to the false assumption that they still need to somehow tap something to start the route calculation. Formerly the route calculation progress indicator seemed to pop up instantaneously after the route progress dialog popped up (and a GPS fix was found).

**Comment by vshcherb** [comment]
Need to reproduce... May be some screenshots could help.

**Comment by sonora** [comment]
<img width="135" alt="screenshot_2017-07-10-08-05-24_" src="https://user-images.githubusercontent.com/845735/28008090-5ab277a4-6556-11e7-8a26-e3ebf1afbc74.png">

Here is the screenshot. (It does actually **not** depend on whether OsmAnd is still looking up the destination address or not.)

I have further investigated and it seems this happens **exactly for every first route calculation attempt after an app start**. (I think it is even regardless how long ago the app start was).

You can then either just wait (if you are aware of the issue), and the navigation bar will finally come on and the route gets calculated. Or you can stop the route calculation (it takes a little longer than usual before the route button turns gray again), than restart it, and then the progress bar comes on immediately as usual.

So my takeaway is that at every first start of a route calculation we initiate something and this keeps the progress bar from popping up for quite some time, while for any subsequent route calculation it shows instantaneously.

The fix would probably be a re-prioritization to somehow show the route calculation progress bar a little earlier, meaning **before** any init process we may start.

**Comment by vshcherb** [comment]
I'm afraid the issue quite complicated in sense, it could be thread concurrency - address lookup and route calculation. Good luck that it doesn't crash...

**Comment by sonora** [comment]
Yes, but it is weird that it systematically happens every first route calculation...

**Comment by polarbearing** [comment]
Is the position known in the example above? 
I have the case recently that the device comes up with a coarse, maybe 'last known' position, before that disappears and it waits for the regular GNSS fix.

**Comment by sonora** [comment]
I am strictly talking abut after the GPS already has a fix.

**Comment by vshcherb** [comment]
I think I notice what you say. Today I see only 2 updates from route progress bar and it used to be more frequent.

**Comment by vshcherb** [comment]
My mistake, no I didn't manage to reproduce.

**Comment by crimean** [comment]
Cannot reproduce

**Comment by sonora** [comment]
Looks like this may only be noticeable on older devices Android 4 or 5. It affects exactly only the first route calculation after the app start (but no matter how long ago the app start was). Looks like some route calculation related initialization is taking place. For any subsequent navigation starts the progress indicator then pops up immediately.

Not extremely problematic, I was just thinking if we could show the progress indicator before starting whatever we seem to initialize there.

**Comment by scaidermern** [comment]
I can confirm this issue with the current stable version (2.7.5). On the first start the progress bar is not visible until tapping on "Go". Subsequent route calculations show the progress bar immediately.

**Comment by sonora** [comment]
I think if you wait long enough, even without tapping 'Go' the progress indicator will pop up eventualky, but it takes some time. This seems exactly the issue I am reporting here.

**Comment by scaidermern** [comment]
Also reproducible with OsmAnd 2.8.0. See this video:

[route_calc.zip](https://github.com/osmandapp/Osmand/files/1384600/route_calc.zip)

The progress bar is not visible the whole time. After the route calculation finished the routing is aborted and a new route calculation is started. The progress bar appears immediately.

**Comment by vshcherb** [comment]
Clearly something goes wrong though I didn't manage to reproduce it all. Initially I've though the UI Doesn't refresh cause there is no GPS my location enabled, but I tested without it and it is still visible.

We plan to slightly redesign that screen next release, so the progress bar will be on the dialog itself & it might help.

It is almost clear that it is related to UI rather than backend.

**Comment by sonora** [comment]
Yes, UI issue only, from my testing. But it irritates many users because they are not sure their interaction is required or not at this point, so worth fixing.

**Comment by crimean** [comment]
@sonora may be you are using custom routing.xml?

**Comment by sonora** [comment]
Alexey, no, strictly standard routing xml. The only thing which is really non-standard on all my devices I use for testing is that I have both several hundred favorites and tracks, which I need both professionally and it helps detect efficiency issues with our new database approach. But I do not think this has any effect on this issue, though it may.

**Comment by sonora** [comment]
PS: I think this is unrelated entirely, but it seems there are circumstances where the first routing attempt somehow gets hung for rather long, but when you cancel it and tap on Directions again, the second attempt works rather quickly.

**Comment by crimean** [comment]
@sonora Hardy, could you please check if issue occurs when zoom < 10 ? :)

**Comment by sonora** [comment]
Alexey, good job, your commit fixed it ok!  The progress indicator is now visible immediately (even though every first navigation start is a bit delayed vs. all subsequent tries). Thanks, Hardy
