### ISSUE TITLE
Incorrect GPS track file size on list of GPS tracks

### ISSUE THREAD

**Issue by agilob** [osmandapp/Osmand#4047]
OsmAnd says this file is >4GB, but it's 4.5MB

The file was recorded using OsmAnd not imported.

![screenshot_20170706-105241](https://user-images.githubusercontent.com/2544251/27905992-afe657ec-6239-11e7-9333-b886ac269def.png)

**Comment by njohnston** [comment]
Duplicate of #3820, #3706 and #3950.
