### ISSUE TITLE
Support custom profiles

### ISSUE THREAD

**Issue by mathstuf** [osmandapp/Osmand#4048]
It would be nice to be able to create new profiles within Osmand. For example, not all travel-by-foot settings are comparable and switching all of the settings when changing between a city and the backcountry is annoying. For example, walking through a city requires no contour lines, diverse POI information, etc. while hiking in the mountains basically requires contour lines, specific POI information, etc. Then that changes again with hiking in the winter. See issue #3462 where winter vs. summer driving routes differ as well (one might conceivably also have different profiles for a sports car versus an SUV based on road conditions).

**Comment by vshcherb** [comment]
There are extra profiles in the Development settings already.

**Comment by jfburke3** [comment]
I've been considering putting in a similar request.  Just as examples of what I had in mind, it would be nice to have separate "local" vs "long distance" car profiles.  The points of interest that I want to know about are different if I'm just driving around town vs making a 500 mile trip.

Similarly, it would be nice to have an "offroad" profile for those of us who sometimes like to seek out smoothness=horrible or very_horrible roads to drive on for fun (which applies to Jeeps, dirt bikes, ATVs, etc.).

The extra profiles in the Development plugin don't really cover those cases.

**Comment by Siltaar** [comment]
I'm also interested in custom profiles, as one can use the same GPS in a sedan car and in a camper which won't have the same dimensions, speed, or right to reach hightways…

Without UI changes, we can currently have 5 to 6 more icons of navigation profiles and it would cover the majority of the needs.

**Comment by matthijskooijman** [comment]
This seems to be somewhat related to #4252, which requests more configurable POI display based on profile or custom settings.

**Comment by Discostu36** [comment]
This is now realized, isn't it?

**Comment by mathstuf** [comment]
Essentially, yes. Making multiple new profiles is now possible. How configurable the non-hiking ones are, I don't know, but the core issue here is resolved.
