### ISSUE TITLE
motorroad=no is avoided in motorcar routing

### ISSUE THREAD

**Issue by kreuzschnabel** [osmandapp/Osmand#4051]
The following issue just came up on the German Forum: 

When requesting a route from [Paderborn](http://www.openstreetmap.org/#map=12/51.7212/8.7582) city to the nearby town of Horn (30 km to the north-east), the by far optimum route is the excellently built B 1 road. However, OsmAnd surprisingly avoids that road, favouring narrow byroads instead.

There is no tagging on the B 1 suggesting such a behaviour. The only suspicious tag is a superfluous  "motorroad=no" on some of its ways, which actually means nothing (since it’s the default value when no motorroad=* is tagged) but might be misinterpreted by OsmAnd as an access restriction like "motor_vehicle=no" or "motorcar=no". 

It should be checked if OsmAnd routing does mistake motorroad=no in the way described above.  

While the issue came up on a "truck mode" request, it shows up in standard car mode as well: 

![screenshot_20170706-210446](https://user-images.githubusercontent.com/22165960/27930300-672b4870-6296-11e7-9bd7-2efdc1eb4af1.png)

--ks

**Comment by scaidermern** [comment]
OsmAnd definitely routes along motorroad=no in car mode (I've tried it [here](http://overpass-turbo.eu/s/qgg)). But maybe there is some sort of penalty?

**Comment by kreuzschnabel** [comment]
However, I see no reason for the routing given in my screenshot above. I’ve tried another OSM based router (MapFactor), which routes along the B 1 as expected. motorroad=no was the only reason I could think about. What routing does your client give on the same route? 

There must be a reason for this, and it should be fixed. I still cannot see anything wrong in the OSM data.

**Comment by scaidermern** [comment]
It routes roughly until [here](https://www.openstreetmap.org/?mlat=51.8505&mlon=8.9156#map=16/51.8505/8.9156). After this point it takes the long detour as shown in your screenshot, independently from the start position:

![photo_2017-07-09_22-02-48](https://user-images.githubusercontent.com/1040784/27997148-66eb7714-64f2-11e7-93bb-6957c3d2001d.jpg)


So it doesn't seem to be a penalty issue. This position also equals the start/end of an OSM way. However there have been no recent changes and various other online routers don't show this problem. Maybe a bug during OsmAnd's map generation?

**Comment by kreuzschnabel** [comment]
*clap*clap* Thanks for narrowing down the critical point – I’ve got the culprit! It’s indeed a mapping error, relation #4543816, which was supposed to be one of those pointless don’t-turn-around-on-the-way-itself-restrictions but somehow got the next way (instead of the same) into the from: role.

I'll fix that straight away and consider the issue closed.

--ks

**Comment by scaidermern** [comment]
Oh, great :) I noticed that there are various turn relations but didn't check them.

**Comment by kreuzschnabel** [comment]
Another point is, the turn restriction got invalid by this edit because the via member did not connect to both the to and from members any more. OsmAnd should ignore such restrictions which are technically broken. 

Therefore, I reopen this issue.

**Comment by kreuzschnabel** [comment]
No, better open a fresh one and close this to avoid confusion. Thanks again for your help!
