### ISSUE TITLE
animal_shelter subkeys

### ISSUE THREAD

**Issue by Viking81** [osmandapp/Osmand#4052]
Now there is no distinction between animal shelters in Osmand.
I need to search for animal shelters that take and release wildlife, and there is no way to search them in Osmand.
Moreover in the description of the POI there is not the information of animal_shelter=wildlife/dog/cat subkey.
I propose that you can search for the values of animal_shelter key, and that all subkeys are displayed in the description, once you open it.
For example for this [1], I need to find it if I search for animal_shelter=wildlife and in the description I need to see all subkeys:
amenity=animal_shelter
animal_shelter=wildlife
animal_shelter:release=yes

[1] https://www.openstreetmap.org/way/498896106#map=17/49.07674/0.33863

Thank you
Alberto

Osmand+ 2.6.2
Map of France-Normandie 2017-07-01

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/8f0bbe27cab72a10f6cb533deec442e2010b9753
