### ISSUE TITLE
Error on roundabout exits

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#4053]
Osmand nightly buid 2.7.0# 17828D
Spain offline maps. July, 1
Navigation service: OSMAND. Voice prompts: TTS voice.

Osmand says "take first exit to..." although the route calculated displays correctly you have to take second/thrid/fourth exit. That is voice prompts leaves the rest of exits out.

**Comment by sonora** [comment]
Spanish or English TTS Voice?

**Comment by OpenSourceForEver** [comment]
Spanish

**Comment by OpenSourceForEver** [comment]
Is it reproducible?

**Comment by sonora** [comment]
No, actually I cannot reproduce this. I clearly hear things like "Toma la segunda salida" for roundabouts I have tried using es-tts.. Can you please specify an example roundabout? I think it may be a mao and not an OsmAnd issue.

**Comment by sonora** [comment]
I have not tried a brand new Spain map yet, but quickly updated my Andorra map and simulated a route from Lat 42.52797 Lon 1.52594 through the 3rd exit of the roundabout just northwest from there. It seems to announce "tercera salida" just fine ...?!

Can you do this: In OsmAnd temporarily activate the Development plugin. Then tap Settings /OsmAnd development / Test voice prompts, select the tts voice you are reporting this for, and play button (5.3). What do you hear, does it correctly announce the **second** exit?

**Comment by OpenSourceForEver** [comment]
Examples: (some screenshoots are in english)

http://www.openstreetmap.org/#map=18/40.64033/-4.00534
![screenshot_2017-07-10-02-21-17](https://user-images.githubusercontent.com/12786225/28009250-08ba38ba-655b-11e7-9c74-f458c3ee9003.png)


http://www.openstreetmap.org/#map=18/40.65122/-4.00816
![screenshot_2017-07-10-02-21-27](https://user-images.githubusercontent.com/12786225/28009306-3e06a120-655b-11e7-9e37-6c8693e406cb.png)


http://www.openstreetmap.org/#map=18/40.68475/-4.01346
![screenshot_2017-07-10-02-21-37](https://user-images.githubusercontent.com/12786225/28014231-2ed34c60-656c-11e7-924a-fa404c67dd14.png)


http://www.openstreetmap.org/#map=17/40.72166/-4.02212
![screenshot_2017-07-10-02-21-44](https://user-images.githubusercontent.com/12786225/28014286-64ceabac-656c-11e7-9664-71136e9c290e.png)


http://www.openstreetmap.org/#map=17/40.38306/-4.20924
![screenshot_2017-07-10-02-23-21](https://user-images.githubusercontent.com/12786225/28014364-a7160cd0-656c-11e7-9e16-3e7f9d2e60d0.png)


http://www.openstreetmap.org/#map=17/41.65369/-0.87150
![screenshot_2017-07-10-02-26-29](https://user-images.githubusercontent.com/12786225/28014457-fbe3ced2-656c-11e7-9427-1a7259234bd6.png)

![screenshot_2017-07-10-02-27-40](https://user-images.githubusercontent.com/12786225/28014483-155f5a3e-656d-11e7-9da9-2024422a3c93.png)


http://www.openstreetmap.org/#map=17/41.65855/-0.89207
![screenshot_2017-07-10-02-28-49](https://user-images.githubusercontent.com/12786225/28014559-5714c13a-656d-11e7-93fb-556038e7b4b6.png)

**Comment by OpenSourceForEver** [comment]
Button 5.3 is correct. I think is not a map problem because I have tested the map.

**Comment by OpenSourceForEver** [comment]
Solved with latest nightly build.
