### ISSUE TITLE
POI layer disappears after a while

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#4064]
Displaying POI categories on the map (via configure map -> POI...) seems to be buggy. After some time this layer vanishes and no more POIs are shown on the map, although still being activated. Deactivating and activating the POI layer does *not* fix the problem. The only solution is to completely stop OsmAnd and start it again. After a restart POIs appear immediately.

I experienced this a lot of times. I haven't figured out the actual cause but it definitely happens eventually during navigation.

My wild guess is that there is a certain event that disables the POI layer (i.e. it becomes null) and it doesn't get reinitialized until restart. I have no experience with the code though.

**Comment by scaidermern** [comment]
Is there anything I can do to gather more information while experiencing this issue?

**Comment by vshcherb** [comment]
Hard to say what leads to it. I guess logs are empty in that case if you can make a small video stream from device may be it will be helpful. Anyway in that case the easiest would be for us to reproduce that issue.

**Comment by scaidermern** [comment]
I wonder if this could also be caused by geocoding requests piling up (#3898). This matches at least with my observations since the POIs disappear after moving for a significant time. Is this POI layer populated by the same thread/scheduler as the geocoding requests?

**Comment by vshcherb** [comment]
POI populated with completely different thread. And POI should be much faster at least this what we observe. Last time I saw POI crash the app was about to crash and it was under high memory usage with route calculation. So I couldn't say exactly what's going on.

**Comment by scaidermern** [comment]
I haven't encountered this issue for a long time. I will reopen it if it occurs again.
