### ISSUE TITLE
The program stops after downloading a large number of maps

### ISSUE THREAD

**Issue by mblbstaq** [osmandapp/Osmand#4069]
I have downloaded whole maps of Europe. When I download any additional map, the program stops. I have the latest OsmAnd and i have a fast phone and a fast memory card. I would like to have all maps of the world available offline. But it is not possible now by these errors. What can cause these program errors? Could you fix this?

**Comment by jfburke3** [comment]
Do you have the free or paid version?

**Comment by vshcherb** [comment]
Possibly you need to archive some maps.
