### ISSUE TITLE
Nightly build 2.7.0#21980M crashes on launch

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#4070]
What version of OsmAnd are you using, on what device and Android/iOS version?

Nightly build 2.7.0#21980M, on Samsung Galaxy S4, Android 4.2.2

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

Your official maps at the moment (the May 31 ones, June maps aren't available for the U.S. yet).

I downloaded the latest nightly build from within the app and installed it (the Menu->Builds feature).  After installation, it just crashes when I try to launch it.  Rebooted phone, still crashes.  Downloaded it again with a web browser on another phone, copied it to the S4 and reinstalled, still crashes.

Preparing to completely uninstall/reinstall, but wanted to post the exception log I'm getting first.

[exception.txt](https://github.com/osmandapp/Osmand/files/1133156/exception.txt)

**Comment by jfburke3** [comment]
Clearing cache didn't help.  Uninstalled the nightly build, the reinstalled it, but it still crashes on launch.

**Comment by jfburke3** [comment]
Deleting the regions.obcf, exception.log and ind.cache files didn't help, either.

**Comment by jfburke3** [comment]
I downloaded OsmAnd-master-nb-2017-07-06.apk from http://download.osmand.net/night-builds/ and it also crashes upon launch.

OsmAnd-master-nb-2017-07-05.apk appears to work.

**Comment by sonora** [comment]
No need to uninstall - just install the 2017-07-05 nightly.

**Comment by jfburke3** [comment]
Too late, but I'll keep that in mind for the future

**Comment by MAlfare** [comment]
All builds newer than  #21949 (2010-07-05) on two tablets running Android 4.x crash immediately after start. No problems running #21980 (2010-07-07 20:53) on my smartphone with android 7.x

**Comment by sonora** [comment]
To anyone considering uninstalling OsmAnd at any time: Before the uninstall,  consider using a file manager or PC or similar mechanism to rename OsmAnd's data folder, e.g. from net.osmand.plus to net.osmand.plus0, or else versions of Android since about 4.4 will remove the folder as well, which means losing all your maps, tracks, etc.

**Comment by jfburke3** [comment]
@sonora I wasn't sure what would happen, so I made a backup of my favorites, avnotes, etc., first.  Very good to hear what you'd expect to happen in some cases, so thank you very much for that info.

**Comment by vshcherb** [comment]
Fixed

**Comment by jfburke3** [comment]
I can verify that the night build I downloaded today is working fine.
