### ISSUE TITLE
Elevation of contour lines no longer shown   

### ISSUE THREAD

**Issue by cgogolin** [osmandapp/Osmand#4071]
I remember that the contour line plugin used to render the height of selected contour lines in meters next to the respective line, thereby providing very useful information on the absolute height. This is also still shown in the plugins config screen and there have been feature requests here to extend this functionality, like #3349 for example.
![2017-07-08 18 23 07](https://user-images.githubusercontent.com/6409421/27988616-39dacde6-6426-11e7-8e9a-d9847c155c72.png)
Unfortunately, this very useful feature seems to not work anymore, as is obvious from the following screenshot:
![2017-07-08 18 22 57](https://user-images.githubusercontent.com/6409421/27988617-3f9fbec6-6426-11e7-86cb-8afcab821bb0.png)
I have tried various settings for the map style, zoom level, color scheme of the contour lines, and so on, but non of them seems to show me the elevation of the contour lines anymore.

I am using v1.0 of the contour lines plugin (last updated Dec 27, 2016) and the most recent version of OSMAND (v 2.6.5, last updated May 31, 2017) from Google Play.

**Comment by sonora** [comment]
This is already fixed, it will be in the 2.7 release.
