### ISSUE TITLE
Strange routing, doesn't follow the road.

### ISSUE THREAD

**Issue by kroeckx** [osmandapp/Osmand#4073]
If I create this route with the offline maps: [https://www.openstreetmap.org/directions?engine=osrm_car&route=51.2108%2C3.1908%3B51.2185%2C3.1885#map=15/51.2069/3.2027](url)

It's showing me a very strange route. Instead of going straight, it says to go left where there is no road. This seems to be reproducible.

![screenshot_2017-07-09-20-54-34](https://user-images.githubusercontent.com/1616242/27996735-0dd035b0-64e9-11e7-97ac-512186b82ad7.png)

I'm using the 2.6.3 version on f-droid.

**Comment by vshcherb** [comment]
This is only possible if you use OSM Live (in that case routing still uses old data).

**Comment by vshcherb** [comment]
Routing is in the Beta status still

**Comment by kroeckx** [comment]
Are you saying someone changed the map recently, and that the old data from the start of the month still was different?

**Comment by kroeckx** [comment]
I guess https://www.openstreetmap.org/changeset/50019461 is related then ...

**Comment by kroeckx** [comment]
Turning live update off and deleting the live update shows why it was doing that, thanks for explaining.
