### ISSUE TITLE
Support Wiki Commons

### ISSUE THREAD

**Issue by utack** [osmandapp/OsmAnd#4075]
Hi,

have you considered supporting Wiki Commons?
It would really neat to have a POI layer of images, next to the one with Wikipedia articles.
Of course images would have to be loaded online, and only the index stored offline.

Thanks for feedback

**Comment by vshcherb** [comment]
It really depends on the library we process html from Wikipedia. Today the library we use sometimes not correctly prepares html for Wikipedia which leads to missing images. But the functionality you are talking, is already supported and works on some articles. Basically it loads images if the OsmAnd is online.

**Comment by utack** [comment]
@vshcherb the point was to have just the images on the map, as optional POI layer maybe  
Wiki commons has many images that are not used in articles, but still show interesting things

**Comment by MakiWolf** [comment]
In version 3.8 more data sources for online photos where added (Wikidata, Wikimedia Commons).
[https://osmand.net/blog/osmand-3-8-released](https://osmand.net/blog/osmand-3-8-released)
