### ISSUE TITLE
Incorrect pedestrian routing.

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4076]
While in pedestrian navigation mode, the route ignores the shortest way.

Location: https://www.openstreetmap.org/search?query=49.26270%2017.89813#map=16/49.2624/17.9041

Screenshots:
![19885871_1882405725339566_229206463_o](https://user-images.githubusercontent.com/20681525/28009066-b50e480c-6562-11e7-8fe4-e8604ee4ae4b.png)
![screenshot_2017-07-08-16-59-02](https://user-images.githubusercontent.com/20681525/28009067-b52caee6-6562-11e7-88d3-c4654d0bfac0.png)

**Comment by scaidermern** [comment]
This is an error in the map data. There is no connection between the road and the track:

![foo](https://user-images.githubusercontent.com/1040784/28010011-cb4ae67a-655d-11e7-8182-ce90d2c6140e.png)

Can you fix it in OSM yourself?

**Comment by PaulStets** [comment]
Fixed.
