### ISSUE TITLE
Some lakes are not rendered at zoom levels <=10

### ISSUE THREAD

**Issue by rbovard** [osmandapp/Osmand#4085]
> What version of OsmAnd are you using, on what device and Android/iOS version?

OsmAnd+ 2.6.5, Android 7.1.2

> Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?
> If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

Switzerland, 1st July 2017

Zoom level 10 and below:
![screenshot_20170710-224412](https://user-images.githubusercontent.com/4549666/28039544-035c75d2-65c3-11e7-92e3-57d042568b67.png)

Zoom level 11 and above:
![screenshot_20170710-224423](https://user-images.githubusercontent.com/4549666/28039560-186efe40-65c3-11e7-9df6-4b3e15bbff44.png)

OSM data: https://www.openstreetmap.org/relation/390323

**Comment by vshcherb** [comment]
![screenshot_20171003-102442](https://user-images.githubusercontent.com/1042025/31116107-29d11c1e-a825-11e7-9475-d0891f13fd72.png)
Fixed with new maps

**Comment by rbovard** [comment]
Thanks!
