### ISSUE TITLE
shop=funeral_directors displays coffin icon in POI details but a shop icon on the map

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#4089]
shop=funeral_directors displays coffin icon in POI details but a shop icon on the map.

Why not displaying the coffin icon on the map too? (Maybe this is a more generic question that also affects other POI types.)

![photo_2017-07-12_09-35-28](https://user-images.githubusercontent.com/6921696/28106945-165e8f48-66e6-11e7-8969-b988c26e340b.jpg)

http://www.openstreetmap.org/node/2329654678#map=19/47.69549/9.82486
http://wiki.openstreetmap.org/wiki/Tag:shop%3Dfuneral_directors

Found with OsmAnd+ 2.6.5.

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/1808ba0652513e226bfcd58bfdc0b183938a5c4c
