### ISSUE TITLE
Incorrect car route.

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4090]
Coming from Dwarsstraat or Uitgang it is not allowed to go left or right on the N284. You only may cross over. Routing does this nevertheless and gives a not allowed solution.

Location: https://www.openstreetmap.org/directions?engine=mapzen_car&route=51.36385%2C5.22595%3B51.36450%2C5.22634#map=19/51.36422/5.22660

**Comment by naoliv** [comment]
This relation https://www.openstreetmap.org/relation/5807121 is wrong.
There are 3 ways on it and it's missing the `from` and `to` roles.

**Comment by scaidermern** [comment]
Related to #4074.

**Comment by PaulStets** [comment]
Fixed by https://www.openstreetmap.org/changeset/50303470#map=18/51.36470/5.22620
