### ISSUE TITLE
Missing hiking icons.

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4091]
When 'Alpine hiking scale' and 'Color by OSMC hiking symbol' are enabled the signs are missing since a 
Map-Update (probably since the May/June-Map update of the 
Germany/Baden-Württemberg-Map).

An example of symbols:
![markierung](https://user-images.githubusercontent.com/20681525/28111104-0c9f34dc-66fd-11e7-8edb-bf892263cc82.jpg)

**Comment by PaulStets** [comment]
Today I've got the second report of this bug.
Here is the location: https://hiking.waymarkedtrails.org/#?map=13!45.3678!22.8934
Screenshots:
![screenshot_2017-07-17-15-04-53](https://user-images.githubusercontent.com/20681525/28306419-e41bff22-6ba7-11e7-9d7e-13a72206bb70.jpg)
![screenshot_2017-07-17-15-06-36](https://user-images.githubusercontent.com/20681525/28306420-e41feda8-6ba7-11e7-8688-6b2504bdb7fa.jpg)

**Comment by xmd5a2** [comment]
Don't need more reports. Issue is identified.

**Comment by xmd5a2** [comment]
Will be fixed with the next generation of maps
