### ISSUE TITLE
Parking icons displayed on zoom levels 16 and 18 but not on 17

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#4098]
Below you find three screenshots at zoom level 16, 17 and 18. You can see that the two parking icons (one at the orange marker, the second right of the orange marker) are not displayed on zoom level 17.

That is irritating while zooming during looking for parking space and forces the user to change the zoom level to 16 or 18.

**Zoom level 16**
![zl16](https://user-images.githubusercontent.com/6921696/28158278-84c304ae-67b9-11e7-85b4-3d2ea1feb513.jpg)

**Zoom level 17**
![zl18](https://user-images.githubusercontent.com/6921696/28158279-84c77642-67b9-11e7-98b8-000c002d7811.jpg)

**Zoom level 18**
![zl17](https://user-images.githubusercontent.com/6921696/28158277-84c1b806-67b9-11e7-9f18-d391cd31aa9d.jpg)

Found with OsmAnd+ 2.6.5.

**Comment by xmd5a2** [comment]
Not reproducible in nightly build
