### ISSUE TITLE
Correct symbol code "·" in strings

### ISSUE THREAD

**Issue by franco999** [osmandapp/Osmand#4115]
Weblate puts it as " \\022 " but it should be " \u2022 " for " · "

For example, in releases_2_6:
In Weblate: `\022 New feature: Quick action button`
Original:  `\u2022 New feature: Quick action button`

**Comment by franco999** [comment]
The problem still persists, because the problem is in Weblate.

1. In still untranslated strings (in Weblate) the code `\022` is still viewed and as a consequence, it will be translated instead of `\u2022`.

2. The strings already translated and corrected to `\u2022` in Weblate, by passing it in Github appears as `\\u2022` and the phone is seen in the code instead of the symbol it represents.

**Comment by vshcherb** [comment]
Looks like the issue is more on weblate side or we need carefully modify it only in non-translate.

**Comment by franco999** [comment]
@vshcherb Why not just put the symbol instead of your code? If you look closely, it only shows the error in the first line.

![1](https://user-images.githubusercontent.com/12088580/28826723-801bfc52-76a1-11e7-9814-9dab1d5b06df.png)
![2](https://user-images.githubusercontent.com/12088580/28826724-801d88b0-76a1-11e7-9d02-ca825c5909cb.png)

**Comment by vshcherb** [comment]
This is less important cause we always fix it later in release notes. Next release we will do it differently.

**Comment by aceman444** [comment]
You do not seem to fix this in the release notes. The current released version 3.0 shows those \022 strings verbatim in the translated release notes.

This is NOT solved yet.
