### ISSUE TITLE
Introduce transparency for MTB routes

### ISSUE THREAD

**Issue by littlehelper** [osmandapp/Osmand#4116]
Hi,
I like the way Osmand can display all known cycle and MTB routes. But I often switch between displaying and hiding the MTB routes because in the current version MTB routes are drawn without transparency and are covering the type of the underlying track.
Please introduce some transparency for drawing MTB routes so that the mtb:scale as well as the highway's track type can be seen at the same time (like it is implemented for cycling routes, refer #3077).

Greetings

**Comment by xmd5a2** [comment]
Transparency was removed because I found that often mtb:scale and cycling networks overlaps. It was difficult to distinguish one from another because all of them were transparent. But I can try to introduce slight transparency for mtb routes.

**Comment by xmd5a2** [comment]
Added transparency. But keep in mind that routes with class:bicycle:mtb=1,2,3 are rendered with yellow glow. This glow painted as underlying layer due to rendering engine limitations and adds more "non-transparency". These routes will be less transparent than regular mtb routes.
