### ISSUE TITLE
Test selected speech output.

### ISSUE THREAD

**Issue by dafoxia** [osmandapp/Osmand#4120]
If there is a test navigation speech button in the settings menue, users can check if the settings are correct. Otherwise it's hard to determinate if your car-stereo handles the settings.

**Comment by njohnston** [comment]
This already exists in the OsmAnd development plugin.

Go to main menu -> Plugins -> OsmAnd development -> (Enable if necessary) -> Settings -> Test voice prompts -> Select language -> Select message to play.
