### ISSUE TITLE
Show Wikipedia links on objects without downloading offline Wikipedia data

### ISSUE THREAD

**Issue by utack** [osmandapp/Osmand#4123]
Could you please keep the "wikipedia" key on objects, even when the offline Wikipedia data is not downloaded?  
That way people can easily click and open the articles in their web browser, when they are online  
Thanks for consideration

**Comment by scaidermern** [comment]
Isn't this already the case? Similar to the website there is a Wikipedia entry for a POI with a wikipedia key.

![photo_2017-07-16_19-38-26](https://user-images.githubusercontent.com/1040784/28249863-5df2121e-6a5e-11e7-8dff-47e663a57724.jpg)

**Comment by utack** [comment]
Oh, yes...turns out I tried it on an object that had no wikipedia tags when the map was converted to OsmAnd  
Sorry
