### ISSUE TITLE
Visually differentiate POI type and POI name

### ISSUE THREAD

**Issue by TimMagee** [osmandapp/Osmand#4124]
When a POI is selected on the map an 'info card' pops up with information on the POI. The title on the info card reads "POI Type POI Name". For a example, Rainbow Falls would be "Waterfall Rainbow Falls". 

Proposed change: Visually distinguish the name and the type. This could be as simple as adding a colon, "Waterfall: Rainbow Falls". Or the name could be on a different line or in a different font.

**Comment by pebogufi** [comment]
"Waterfall: Rainbow Falls"
+1, very good idea !
Peter

**Comment by jfburke3** [comment]
I agree.

**Comment by UAb5eSMn** [comment]
This seems to be fixed.
