### ISSUE TITLE
new names for modes in bicycle routing

### ISSUE THREAD

**Issue by Posteinwurf** [osmandapp/Osmand#4134]
I would suggest to rename the three modes in bicycle routing. 

old naming: **safety, balanced, speed**

New suggestion: **prefer byways, balanced, prefer main roads**
alternative suggestion: **less main roads, balanced, more main roads**
another suggestion: **less main roads, balanced, shorter route**

Reason: The new wording would tell users exactly what the routing engine does. I think users need to get a precise idea to make the right choice. The current naming can even be slightly misleading, in my opinion. Normally it is safer to avoid main roads, but when you cycle at night and are afraid of being robbed, you might want to take more main roads. Also, the "speed" mode is not always faster: Normally, it calculates a shorter route, but with more stops at traffic lights. So often, the "safety" mode will be as fast as the speed mode. 

I would prefer the third suggestion (if you think it is understandable). It makes clear what you gain on both ends (less car traffic or shorter route).

**Comment by sonora** [comment]
I can see your point, have implemented this for testing, I guess it provides maximum clarity:
**prefer byways, balanced, prefer major roads**

**Comment by xmd5a2** [comment]
"Prefer major roads" is not true because this setting will prefer cycleways and only in case of their absence will prefer major roads.

**Comment by Posteinwurf** [comment]
then we could name it 

 

prefer byways  -  balanced  -  shorter route

 

or also

 

less main roads – balanced – more main roads

 

 

I think these are clearer than the existing naming.

**Comment by sonora** [comment]
I have changed it to
**Prefer byways / Balanced / Accept major roads**

Let me now what you think.

**Comment by Posteinwurf** [comment]
That is good, but my favorite would be:

prefer byways  -  balanced  -  shorter route

Because also in „prefer byways“, major roads are accepted and frequently used for shortcuts. If you go 10 Kilometres in Berlin, you would normally have some parts of even primary (with bike path), and also some parts of tertiary without bike path.

I think “shorter route” is an idea that people also know from car routing where you have (for example) “faster route” vs “shorter route”
