### ISSUE TITLE
Opening wikipedia articles refers to wrong language

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#4144]
I use German user language (DE)
I open a Wikipedia article by calling "wikipedia Artikel zur Umgebung" / "EN:nearby acticle" and get a german text, ok.
Then I click on "weiter lesen" / "EN:read more" and get again a german text (so far ok), but in the upper right corner the language is shown as **EN**, which is wrong. see screen shot.
Here I can't switch EN to DE, only EN is available, which is wrong, I have a the German text.
When I want to click "Vollständigen Artikel lesen (online)" / "EN:read full article (online)" I get the english page of wikipedia, which is again wrong. The page does not exist on wikipedia-en-page but only on its de-page.
https://**en**.m.wikipedia.org ....

Version 2.7.0#22051
Regards Peter

![screenshot_2017-07-19-11-28-45](https://user-images.githubusercontent.com/18628183/28361002-8df8af52-6c77-11e7-9b28-1abe7512dfa8.png)

**Comment by crimean** [comment]
@pebogufi do you use latest wiki maps? If not - please try to update.

**Comment by pebogufi** [comment]
On Download Map
Register Local all lines are marked green
Register Updates -> All files up to date.
So I think: yes, all files are latest version.
Peter

**Comment by crimean** [comment]
I just tried the same article "Batterie Todt" at 50.84431 1.59988 and it has en, nl, fr, de, sp languages. If I switch to DE - it displays in DE as well as link to full article at wikipedia.org

**Comment by pebogufi** [comment]
I checked it again. 
In France some months ago was a huge reorganisation of regions. New regions had been created and delivered but old regions had NOT been removed. So there were duplicates with old and new data. And as well a german wiki for whole country, which is no more delivered but existed with a old date.
That was the problem, I suppose more people will have problems like that with old files...
Sorry to bother you.
Thanks, Peter
