### ISSUE TITLE
Osmand was crashing and asked me to send a bug report.

### ISSUE THREAD

**Issue by vi** [osmandapp/Osmand#4161]
[exception.log.zip](https://github.com/osmandapp/Osmand/files/1165117/exception.log.zip)

After rebooting Android 4.4.2 it works again. Offline maps.

**Comment by scaidermern** [comment]
The first crash in the log looks like #2513.

**Comment by vshcherb** [comment]
Looks like corrupted installation, please reinstall if it doesn't work or complete the full instalation.
