### ISSUE TITLE
Transit maps and lines (metro, bus, etc) 

### ISSUE THREAD

**Issue by fabeit** [osmandapp/Osmand#4171]
I have been searching for a while but I can't find any info. I know that in OsmAnd it's possible to see bus and metro stops, but what it is really useful is to have a layer with the metro and bus routes. Is there a way to display or add public transit maps?

This is incredibly useful, and even though bus lines might be more complicated, at least metro lines. Sometimes I have to manually follow the stops to see where a metro line is going, but I would like to have an overlay of the transit system on top of the map or more visible. Does this exist in OsmAnd or in any other offline map app for Android?

**Comment by scaidermern** [comment]
This is already possible. Displaying public transport lines can be enabled via Configure map -> Transport. There you can select ot show bus, tram and subway routes.

Example:
![photo_2017-07-22_12-35-17](https://user-images.githubusercontent.com/1040784/28490427-42b06106-6eda-11e7-814a-fc736eafa506.jpg)

(There is no subway in my city).

Of course these routes have to exist in OSM.

**Comment by vshcherb** [comment]
Configure Map -> Transport.

**Comment by fabeit** [comment]
@scaidermern ok Thanks, but the bus lines are most of the times completely unusable, is there a way to display only one bus line?

**Comment by pebogufi** [comment]
Yes, it is. Click on a bus stop, then on a line with the bus route you are interested in. Then this bus route will be displayed with a fat line.
This works only with good data in osm !!
Peter

**Comment by zimonth** [comment]
I was in Stockholm just couple of days ago. I wanted to go from A to B, using public transportation. Yes, its true OsmAnd can show public transportation routes and stops quite nicely, but what is missing is to route directions from A to B using different public transportation means (bus, tram, metro). And tell the time schedule when to take some bus, where and when to change to another one, and when one will arrive the destination. 

Switching to Google Maps, it was easy to find what busses and metros to take, where to change, how to walk between stops. Only thing it needed roaming data, but when the maps themselves were already pre-loaded to Google Maps (Offline maps), it didn't use much (kiB) roaming data.

Could this kind of routing via public transportation be possible in OsmAnd also? In many cities, there is public API to public transportation system. I wonder if there is some standard, so it could be done more easily and how Google is doing it now?
https://www.androidcentral.com/how-use-google-maps-public-transit

**Comment by elig0n** [comment]
@vshcherb is there any advance on this ? Some ability to plug into existing external APIs for times could enhance the usability quite a bit
