### ISSUE TITLE
Add 'is in' look-up mechanism to determine at least state/region/community the location is in

### ISSUE THREAD

**Issue by littlehelper** [osmandapp/OsmAnd#4174]
Hi,
Please add a kind of 'is in' look-up mechanism to determine and display information about in which state, region or community and country a selected location (or at least a city, town, suburb, hamlet etc. POIs) is in.
It would be great if Osmand can show e.g. that the selected location 'Innsbruck' is not just a city but also a 'City in Tyrol, Austria'. Or that 'Villalangua' is a 'Village in Aragon, Spain'.

In the latter example 'Aragon' and 'Spain' are also the names of the maps available for download and therefore indicating which maps cover the autonomous community or the whole country respectively around the selected location. (Maybe an indication that the loop-up process may not be too sophisticated since the information about region and country is already somehow used.)

This kind of information would also help to identify and distinguish several similar/identical spelled search results in different countries, like the information 'x.y km from city' already shown for hamlets and suburbs does. For that cases, the existing description should be extended by the proposed 'is in' information, e.g. '45.1 km from Huesca in Aragon, Spain'.

I think as a first step it would be a good idea to implement the proposed 'is in' look-up at least for locations/POIs (like cities, towns, suburbs, hamlets etc.) where currently no address look-up is performed. Later on this look-up information could be handsome for any selected or found location.
And maybe this would partially cover the interests of #3327.

Greetings

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/2993
