### ISSUE TITLE
online search

### ISSUE THREAD

**Issue by treakiandroid** [osmandapp/Osmand#4180]
In the early versions of osmand i had the option to search for a place (city, village, street) not only in the local database but also online. That was really helpful if you had not downloaded the region and had been in WiFi area. 
Also the local search was much faster because it was devided in several steps (country, region (file), city/village, street, had to be given step by step). When i now search for a far away little village i have to wait much longer then with that old method because i assume that it (the device/osmand) is first looking for a street in the local city and has to go through all databases (e.g. hamburg, lower Saxony, northreinwestfalia (german federal states) instead of just the one i have selected before.

In the current version 2.6.3 (froid) i am missing both features of the 1.x which had been in version

Could you please bring back both features again, the ability to send search strings to a server and get the map zoomed to (was good to discover forigin cuntrys at home that you didn't had on your device together with online tiles (now i have to use the browser for that ;( )) and the local place search divided into the different steps?

Thanks a lot in advance

**Comment by vshcherb** [comment]
Duplicate #3704
