### ISSUE TITLE
Map rendering freezes with GPX track "Show on map"=ON

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#4181]
Can anyone reproduce this:
- Fresh app start, build of 2017-07-22
- Go to My Places / My Tracks, tap on a track
- On the subsequent Track Analysis screen, activate the "Show on map" switch, then near the bottom tap on "Analyze on map"

With new builds, this freezes all subsequent map rendering for me. The map screen still responds as usual to zooming, panning, etc., but I only see the cached bitmap of any previously rendered map section, all new sections after panning or zooming remain gray.

**Comment by vshcherb** [comment]
It is possible that freeze related to GPX Database update to fix all previous issues. If you have too many gpx files it could be a long process.

**Comment by sonora** [comment]
Yes I can confirm this is on a device with several hundred gpx files. I had uninstalled then re-installed OsmAnd some time before (keeping my data by renaming the data folder beforehand), so it may quite possibly be related. Would we expect any corruption etc. issues if users kill OsmAnd due to issues like this in the middle of the (invisible) update process?

**Comment by sonora** [comment]
PS: When in this issue state, and I leave OsmAnd like this in the background, the task manager shows 0.00% CPU usage for OsmAnd, which does not seem to indicate OsmAnd is busy updating anything. So in which state woild I have to leave OsmAnd to make sure the db update is being performed? (Currently my only idea to check verify if this is really update related)

**Comment by sonora** [comment]
Intrestingly, map zooms<=6 work. the rendering seems frozen only every time the map is supposed to show zoom levels >=7.

**Comment by xmd5a2** [comment]
Sometimes this problem happens to me. I also have several hundred tracks.

**Comment by vshcherb** [comment]
Looks like not reproducible anymore

**Comment by sonora** [comment]
I still have this with 2017-07-28 build. It is not sporadic, it is 100% reproducable. And it only goes away after I disable the GPX layer again via Configure map. Again, far out zooms  work, but when I zoom in again the map content does not get refreshed any more, if a GPX track had been made  visible via the procedure described above.

**Comment by crimean** [comment]
@sonora may be it is some specific gpx? could you please send one to me?

**Comment by sonora** [comment]
Alexey, still investigating. I am testing with about 1600 gpx files in 28 subfolders of "tracks". So far it looks like this:

It seems to not be related to specific gpx files. The issue seems to occur for all of my files recorded with OsmAnd in recent weeks, and also for many or most older and third party files. But for very old files in the collection  the issue seems not present.  When I copy all files to a new tracks folder (and rename the old one before), the issue is unchanged. But when I delete many folders and keep only a few with files previously exhibiting the issue, they work ok then(!). I think it may somehow be related to the number of GPX tracks and/or the position in our database, can this make sense? When I revert to the build of July 5, the issue seems gone.

Possibly a bug or sizing issue in our new database?

**Comment by sonora** [comment]
PS: The issue seems to appear only when going via Analyze on map. When immediately selecting Show on map in a track's 3 dot menu in our My tracks screen, everything works fine.

**Comment by sonora** [comment]
It almost feels like we are putting the wrong activity in the foreground when running `MapActivity.launchMapActivityMoveToTop(getActivity());`

**Comment by sonora** [comment]
Received confirmation now from other users that this is a general issue. The bad thing is when it happens, OsmAnd's map display is essentially dead, and the conditions survives any app restart. Since there is no indication that all you have to do is disable the GPX layer again, I have seen people starting to uninstall the app. Guess this needs to be fixed urgently ...

**Comment by sonora** [comment]
Maybe it was a database conversion issue after all ...

It seems to me that struggling with this issue over the last few weeks, initially it seemed to affect all of my gpx tracks, while later it seemed to affect only 'newer' files, like e.g. recent recordings. After playing with it again for about one hour today I had reached a stage where only my very last recording was affected, and ever since a few minutes ago that file works ok, too. I have then tried both a new recording, and duplicated some old recordings in the file system with a new file name (via a file manager) but all these now worked from the start.

**Suggestion:** If there are possible transient issues with updating the database, maybe we could implement some sort of text info display in our dev settings, similar to the memory usage display we have there, indicating version and size of the gpx database, and if some sort of upgrade is currently ongoing or not?

**Comment by vshcherb** [comment]
To update on this issue: so far we didn't manage to reproduce it. We still keep investigating cause there were quite a lot of changes in this area and the last thing, we didn't try, is to download >200 tracks and test it.

**Comment by sonora** [comment]
Yes, it looks like the number of tracks in the track folder plays the decisive role how noticeable the issue is.

The funny thing is: Whatever is causing this, and if it is really about the database, I am wondering for what exactly this is in the critical path, and why it only affects the map rendering after tapping Analyze on map and only with Show on map enabled. Because all other functionality for the very same track, like displaying it on the map via some other method, or displaying that track on the map preview bitmap on the track analysis screen, analyzing the track, including all intrractive altitude/speed graphs and the split interval analysis, and even the Analyze on map interactive graphs on the map itself (only here with the map not rendered), that all works. So this is not about any track not being readable or similar.

**Comment by njohnston** [comment]
This happens to me as well, using OsmAnd 2.7.5 on a Samsung S8+ running Android 7.0. I have about 360 tracks.
