### ISSUE TITLE
Version 2.6.5 missing in F-Droid Store

### ISSUE THREAD

**Issue by Krawei** [osmandapp/Osmand#4182]
Dear developer team,

when I take a look in the play store I see that v2.6.5 is available.

In the F-Droid-repo the osmandapp's current version is 2.6.3.

What's the reason for this difference? Is there a bug in the build process?

Kind Regards,

Krawei

**Comment by vshcherb** [comment]
That issue is duplicate (you can search in the tracker). 
P.S. We are not publishing ourselves to F-Droid.

**Comment by sonora** [comment]
Cross ref: The bottom half of #3718 links to more details about this.
