### ISSUE TITLE
Screen doesn't turn off automatically

### ISSUE THREAD

**Issue by obifur** [osmandapp/Osmand#4196]
Version: OsmAnd 2.7.0#22169M (nightly)
Device: Samsung Galaxy S4 Mini (serranoltexx)
OS: LineageOS 14.1 nightly (21.07.17) Android 7.1.2, rooted

After choosing the option to activate screen (German: "Bildschirm aktivieren") the OS is asking for permission to be administrator as expected. Choose activate.

What happens:
The screen does turn on while routing as expected but stays on instead of switch of after the choosen period of time (e.g. 20 sec.).

Remark:
If checking device administrators, OsmAnd is missing (!)

I observe this behavior since I switched from CM13 to LineageOS 14.1

**Comment by vshcherb** [comment]
Device administrators could be added only manually.

**Comment by obifur** [comment]
What do I have to do?

**Comment by deerwood** [comment]
I observed similar behaviour since the last 2 or 3 uipdates of osmand+: altough it has permission to shut off / darken the screen, it does not, when first started.

My workaround is to manually hinting once by pressing the phones On/Off button ... osmand+ darkens the screen and then (often/mostly) behaves as expected:

- just in time switches the screen on to show the next turn
- darkens again after the configured amount of time

**Comment by obifur** [comment]
Is Osmand+ listed as a device administrator in your case? 
Your workaround doesn't work for me.

**Comment by deerwood** [comment]
yes, Osmand+ is listed as a device administrator on my Wiko Pulp with Android 5.1

**Comment by obifur** [comment]
Then it is probably another issue. My point is that the device administrator  isn't added.. Well I think that is the reason for the behavior I observed.
BTW, I would really be glad if someone could help me explaining how an device administrator could be added manually..

**Comment by deerwood** [comment]
Android 51: open Settings > Security > Device Administrators. You will see a list of apps wanting the permission, OsmAnd+ should be among them. Check the box to the right of it.

**Comment by obifur** [comment]
Thanks, but this is not the problem. OsmAnd is not listed. Therefore I can't check it...


Am 2. August 2017 02:25:23 MESZ schrieb Georg Rehfeld <notifications@github.com>:

**Comment by obifur** [comment]
I found the Problem resp. solution:

Even after I deinstalled / reinstalled the app it was installed at the sd-card, which is strange.. However after moving it to the internal storage, the app is listed as a device administrator and everything is working as expected.
