### ISSUE TITLE
Strange routing (unnecessary deviation) in Esher, UK

### ISSUE THREAD

**Issue by martenjj** [osmandapp/Osmand#4216]
This is using the internal routing engine (car, fastest route, no avoidance) across the crossroads in Esher, UK.  The starting point is on OSM way 152691912, the end point is on way 152680356.  See screen shot:

![screenshot_2017-07-27-12-57-57](https://user-images.githubusercontent.com/10631760/28669506-695d5962-72cc-11e7-9bc9-6e1daf05fdf5.png)

There are no traffic or turn restrictions to prevent simply carrying straight on at the crossroads where Osmand says to turn left and then right.  Every way along the calculated route and along the straight line route has the same maxspeed=30.  The straight line route does indeed pass through 2 sets of traffic lights, but the calculated route also needs to pass through the same traffic lights and also a "give way" junction.

OSRM, Mapzen and GraphHopper on www.openstreetmap.org all produce the straight line routing as expected.

**Comment by scaidermern** [comment]
There is a [broken turn relation](https://www.openstreetmap.org/relation/2571566) with two `to`-members. However it doesn't match the driving direction. Maybe it still confuses OsmAnd (#4074)?

**Comment by vshcherb** [comment]
#4074
