### ISSUE TITLE
Text-to-speech should pronounce road numbers depending on their length

### ISSUE THREAD

**Issue by martenjj** [osmandapp/Osmand#4217]
This is referring to the 'en-GB' voice, although the standard 'en' voice produces the same results.

The usual practice within the UK is to pronounce road numbers with one or two digits as their natural number, but to spell out numbers longer than that as digits.  For example, someone would say the name of the A1 or the A57 as "A one" or "A fifty seven" respectively, but would say A307 as "A three oh seven" or B3152 as "B three one five two".  Currently the TTS says the latter two as "A three hundred and seven" and "B three thousand one hundred and fifty two" respectively.

I'm not sure what is normally done in other countries or with other languages, but saying road numbers in this way (if it is technically possible) would sound more familiar and aid with reading road signs.

**Comment by polarbearing** [comment]
That is probably better addressed by the TTS engine than OsmAnd.

**Comment by polarbearing** [comment]
Dup of #3274

**Comment by jfburke3** [comment]
That's similar--but not completely identical--to how we pronounce them in the U.S., too.

I 75 is "eye seventy five" but I 285 is "eye two eighty five." US 101, however, seems to be "one oh one" so there appears to be some regional variation.

**Comment by sonora** [comment]
No feasible action detected for now.
