### ISSUE TITLE
[Question] Best way to get additional Map information added

### ISSUE THREAD

**Issue by Mannshoch** [osmandapp/Osmand#4218]
In the swiss alps many sheep's are protected by "herd protecting dogs". For that a map exist.

http://www.protectiondestroupeaux.ch/faq-was-tun/um-zu-wissen-wo-es-schutzhunde-hat/

Is Osmand the right place to get this kind of information added?
In my opinion its an important information for hiker especial for hiker with dogs.

**Comment by vshcherb** [comment]
OsmAnd supports Tiles prepared by OsmAndMapCreator, SasPlanet. So this data could be used but it should be prepared.
