### ISSUE TITLE
Kållandsö in Sweden: Land is rendered as blue water. 

### ISSUE THREAD

**Issue by gunnar22** [osmandapp/Osmand#4224]
OsmAnd renders land as water at some zoom levels. See attached screenshots. I have drawn some red line to focus the attention at the areas that disappear.

The issue occurs at Kållandsö in Sweden, in the lake Vänern. When being zoomed-in sufficiently, everything is OK. As one zooms out, first the northernmost part of the land (small islands) disappears, and on more zoom-out even much more land (large island) disappears, i.e., the area where the land was supposed to be is rendered as blue water.

Coordinates for a point arbitrarily selected on Kållandsö: lat, lon: 58.65146, 13.15427

Versions:
OsmAnd+ 2.7.2, released 2017-07-26
Offline map of Sweden, standard map, 2017-07-01
Device: Samsung Galaxy Note 8.0 GT-N5120, Android version 4.4.2

![land-as-water-1](https://user-images.githubusercontent.com/30504902/28682500-7f18b338-72fd-11e7-9e65-a0926c61ef76.png)
![land-as-water-2](https://user-images.githubusercontent.com/30504902/28682564-be8528da-72fd-11e7-8228-a2891fc7849e.png)
![land-as-water-3](https://user-images.githubusercontent.com/30504902/28682572-c342c6de-72fd-11e7-9cb1-228103fbae01.png)
![land-as-water-4](https://user-images.githubusercontent.com/30504902/28682578-c63c2f42-72fd-11e7-91f3-a5a0073528d6.png)
![land-as-water-5](https://user-images.githubusercontent.com/30504902/28682583-c863535e-72fd-11e7-9bfe-b960daffe96a.png)
![land-as-water-6](https://user-images.githubusercontent.com/30504902/28682588-cabb42d8-72fd-11e7-8b94-834c97600f37.png)

**Comment by gunnar22** [comment]
I discovered a similar problem at the south coast of Norway. Here there seems to be only one zoom level that is affected.
Offline map: Europe/Norway/Vestfold, standard map, 2017-07-01

![land-as-water-7](https://user-images.githubusercontent.com/30504902/28683778-258a2cb6-7302-11e7-9199-5b5dbeedab53.png)
Here everything is fine.

![land-as-water-8](https://user-images.githubusercontent.com/30504902/28683781-2816eff0-7302-11e7-9ddf-4ead0995b310.png)
Zoomed-in one step. Here some land is rendered as blue water.

**Comment by TimothyEBaldwin** [comment]
Also observed for Anglesey, an island in the sea in the north west of Wales, in the Europe, United Kingdom, Wales map. Only shows up on close zoom levels if the view is sufficiently close to the mainland. If the view is moved away the map displays correctly.

![screenshot_20170812-184259](https://user-images.githubusercontent.com/1309154/29243953-19b27480-7fa4-11e7-97dc-477910f03a0a.png)

**Comment by cgogolin** [comment]
The same phenomenon occurs also in central Bangkok (around 13.72189 100.50113), as can be seen on the attached screenshot.
![screenshot_20171208-204350](https://user-images.githubusercontent.com/6409421/33782491-3a2751c4-dc59-11e7-8525-61d515cb9e26.png)

**Comment by hugbe8** [comment]
Same issue
OsmAnd+ 2.9.3
![screenshot_2018-05-11-20-45-23](https://user-images.githubusercontent.com/1155637/39951956-0bce8040-555d-11e8-887c-ce43947df6cb.png)

**Comment by vshcherb** [comment]
Probably related to #5833
