### ISSUE TITLE
Routes "Show cycle routes" marked too intransparent

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#4225]
Using profile cycle, then Routes "Show cycle routes" the routes are marked with a fat intransparent line, which is too thick and too dark to see the way behind it.
see screenshot osmand-routes-ShowCycleRoutes.png
![osmand-routes-showcycleroutes](https://user-images.githubusercontent.com/18628183/28709235-c8faf9fc-737f-11e7-9178-3b9bc61981ed.png)

When using the cycle map (other screenshot) the cycle routes are as well marked, but very transparent so that I can see the lines of the ways behind.

Please make the marking in cyle routes transparant like in the cycle map.
Thanks, Peter
Map Germany Badem-Wuerrtemberg 2017-07-01
Version 2.7.0#22205

![mapsource-cyclemap](https://user-images.githubusercontent.com/18628183/28709245-d004a89c-737f-11e7-8722-7d8316bd8c40.png)

**Comment by xmd5a2** [comment]
What osmand version do you use? I can't reproduce such screenshot
![screenshot from 2017-07-28 12-03-26](https://user-images.githubusercontent.com/5829014/28710498-d8fcd9f8-738c-11e7-8f8a-9096d9a08af9.png)

**Comment by pebogufi** [comment]
Map Germany Badem-Wuerrtemberg 2017-07-01
Version 2.7.0#22205

**Comment by pebogufi** [comment]
Position Lat 48.04167 Lon 7.87405

**Comment by xmd5a2** [comment]
Looks like you have 2 or more maps of this place in osmand folder.

**Comment by pebogufi** [comment]
All maps removed except
Germany_baden-wuerttemberg_europe.obf
and
World_basemap.obf
Lines are thick and dark as before.

**Comment by xmd5a2** [comment]
Try to clean up folder osmand/rendering

**Comment by pebogufi** [comment]
I removed all files from folder rendering, then stopped processing /clear cache.
restart osmand, switch to profile cycle. switch map style to nautical, then back to osmand.
Now two files are in folder rendering (checked with file manager): nautical.render.xml and default.render.xml.
Lines are thick and dark as before.

**Comment by pebogufi** [comment]
Transparency now ok, so I close topic.
