### ISSUE TITLE
Multilingual names dont work with relations

### ISSUE THREAD

**Issue by juliannyca** [osmandapp/Osmand#4227]
Hello. In the OsmAnd app, names of relations (such as hiking trails or bicycle routes) dont always show multilingual names. As an example there is Krabat-Radweg (relation no. 60989), which has a "name:hsb"-tag for years now, but shows only the German "name"-tag, when viewed in OsmAnd.

**Comment by xmd5a2** [comment]
Note: multilingual names are cut here https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml#L1741
Relation for test: https://www.openstreetmap.org/relation/1675758#map=9/51.1763/6.5726

**Comment by vshcherb** [comment]
Fixed, requires new map to generate (March should include already)
