### ISSUE TITLE
Mapillary plugin still active after being deactivated.

### ISSUE THREAD

**Issue by vzsze** [osmandapp/OsmAnd#4230]
The latest OsmAnd+ has a feature to display Mapillary photos for points that are selected on the map. The photos are still downloaded and displayed when the Mapillary plugin is disabled. This can cause roaming costs when being abroad or leak information of the places you´re watching on the map.

The problem is also mentioned in this thread https://groups.google.com/forum/#!topic/osmand/kGy87sdKyRA

Is it possible to disable Mapillary plugin completely?

**Comment by vshcherb** [comment]
Yes Mapillary photos are disconnected from the plugin. This is a block in the context menu for Online Information about Places, technically we couldn't make it optional.

We plan  to delete Mapillary plugin to make it part of OsmAnd.

P.S. No internet is required until you click on Online Photos, we will change the description to make it clear.

**Comment by Chumva** [comment]
This should be fixed here - https://github.com/osmandapp/OsmAnd/pull/10756
