### ISSUE TITLE
Navigating external geo lat/lon

### ISSUE THREAD

**Issue by Goodingn** [osmandapp/Osmand#4233]
Regarding not fixed #3705

Since v2.6.3, when sharing a geo reference from another app, why is there now an un-necessary search screen?

When sharing a lat/lon from another app, Osmand used to show me an intermediary search screen that didn't do much but quickly went away and then I had the map with an orange pin on it. I just had to press it then start navigation.

Now, before I get the map and orange pin there's a new search screen that requires me to interact with it, to get to the map and the orange pin.

This screen is USELESS and requires additional interaction I shouldn't need to make.

A geo reference is EXACTLY where I need to be- not a guide for further searching.

**Comment by foresto** [comment]
Confirming that this is very problematic for usability, and still not fixed as of 2.7.5.

#3705 should be re-opened.

**Comment by Goodingn** [comment]
Still not fixed in 2.8.2. First a problem in 2.6.3. Has been annoying ever since. Thanks.
