### ISSUE TITLE
OSMAND osm maps not updated for Australia since Feb it is now July

### ISSUE THREAD

**Issue by Angyork** [osmandapp/Osmand#4234]
OSMAND osm maps not updated for Australia since Feb it is now July. There is normally and update every month.

**Comment by jfburke3** [comment]
@Angyork It looks like they've broken Australia up into separate maps by state.  When I look at the available maps for Australia, I see separate ones for New South Wales, Queensland, Northern Territory, Victoria, etc.

Try going to the All Downloads page for map downloads, then select Australia and Oceania, then Australia, and you'll see what I mean.

**Comment by Angyork** [comment]
Ah yes I see it now, Victoria is at 1/7/2017. Most likely Australia data is much bigger now hence the separation.

**Comment by Angyork** [comment]
Do they need to change how Australia is cataloged within the download section if this is the case?

**Comment by jfburke3** [comment]
Yes,  it probably has to do with the size of the data. By separating it, if a map for a state fails to build, they only have to rebuild that one map, instead of the entire country. 

I'm not sure I follow the question in your second post.

**Comment by Angyork** [comment]
second part, if the entire Australia download is no longer being updated it might be a good idea to no longer have it there and just have the states?

**Comment by jfburke3** [comment]
When I select Australia maps to download, I don't see the whole country, just the states & territories.  I'll guess that you still see the whole country map because you have it installed.  If you delete the whole country map, I don't think you will see it in the list of available downloads again.

This is probably a very rare circumstance, but it would probably be helpful to users if, when a map is obsoleted like this, that it is displayed differently in your list of maps (e.g., the map name is displayed in gray instead of black) to indicate that it is no longer available.

**Comment by jfburke3** [comment]
Wait--yes, I do see the whole country map at the top.  Don't know why my eyes skipped over it at first.  It's dated Jan. 31.  Not sure why it is still available, if they have separated out the states into their own maps....

**Comment by scaidermern** [comment]
> This is probably a very rare circumstance, but it would probably be helpful to users if, when a map is obsoleted like this, that it is displayed differently in your list of maps (e.g., the map name is displayed in gray instead of black) to indicate that it is no longer available.

This is something I would expect as a user, too. OsmAnd should check if locally installed maps are still available at the remote server. Care has to be taken to handle self-generated maps correctly.

**Comment by vshcherb** [comment]
The map we have generated for Australia is broken in some sense, the issue is being investigated.

**Comment by vshcherb** [comment]
Fixed this generation should be ok

**Comment by miloxxx** [comment]
,,,     ,
