### ISSUE TITLE
Option "Avoid stairs / dirt roads" for pedestrians too

### ISSUE THREAD

**Issue by deerwood** [osmandapp/OsmAnd#4236]
In the _BIKE_ routing options one may "avoid stairs" ("Treppen vermeiden" in German) and "avoid dirt roads" ("Unbefestigte Wege vermeiden" in German).

In _PEDESTRIAN_ routing settings these options are missing, although they are similarly important for many people. Consider e.g.:

- parents moving a pram ("Kinderwagen / Kinderkarre")
- people using crutches / walking sticks / prostheses ("Krücken / Gehhilfen / Prothesen")
- persons in wheelchairs ("Rollstühlen")

I don't want to open the "can of worms" to fully support people with whatever sort of handicap / feature.

But the algorithm / code to avoid these 2 barriers is already existent in bike mode, isn't it? Just enable the option settings for pedestrians too.

Thanks

**Comment by scaidermern** [comment]
Related to #4032.

**Comment by xmd5a2** [comment]
https://github.com/osmandapp/OsmAnd-resources/commit/d3045c9feacfb0fc2a35d1e721b4e8f52df20dac

**Comment by dmpr0** [comment]
Avoid stairs is already added.
