### ISSUE TITLE
OsmAnd+ 2.7.2: Route relations rendered like way/path names

### ISSUE THREAD

**Issue by kreuzschnabel** [osmandapp/Osmand#4237]
I just upgraded to 2.7.2, and in this version, all route relations using a path or track are rendered along this path or track like the name of the path/track itself would be. 

I do not approve of this. First, I cannot tell now whether this is the name of the path itself, or just of a route using it, because both are rendered the same way. Second, some of those route names are reather long and cover a lot of the way’s course and details (see attached screenshot). Third, those route names seem to cover the actual path names (the "Wiesbaden-Michelbach (roter Balken)" track in my screenshot below actually has the name of "Eisenstraße", and was labeled with this in previous versions). 

And apparently, this rendering of route names cannot be switched off.

So far, the option of "Karte konfigurieren → Routen" (german version) was used to highlight route relations and offered a very much nicer solution for this, with the coloured overlay which could be switched off when confusing, and stood clearly out from the map itself. 

Please change this back to previous behaviour. I do not need route relation names rendered unless I explicitly switch them on. I surely cannot see any benefit in this but the map is getting confusing and difficult to read, especially with long route names. In motorcar mode, I do not see why I should need hiking route names at all (covering up the next junction which I do need to see clearly).  

--ks
![screenshot_20170730-121825](https://user-images.githubusercontent.com/22165960/28752557-f729525c-7522-11e7-92d4-f6ae93df227e.png)

**Comment by xmd5a2** [comment]
Many ways are wrongly (?) named by route name in OSM. Can you provide exact location?

**Comment by kreuzschnabel** [comment]
Certainly, sorry. The ways in my example did not show those names until the software update. The location is here: https://www.openstreetmap.org/#map=15/50.1535/8.1388

Ways: https://www.openstreetmap.org/way/86343125 and https://www.openstreetmap.org/way/32402875

Both of the entries rendered as names above are not name=* tagged but relations these ways are members of. 

I consider this a bug.
