### ISSUE TITLE
Option to display landuse=residential (and other) areas

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#4240]
For example, here http://www.openstreetmap.org/#map=17/-21.80660/-48.20544 we can see some residential areas (with a color that differs from the background), while in OsmAnd we can't see any difference between a `landuse=residential` and the background:

![](https://user-images.githubusercontent.com/982338/28757528-813d19b4-755b-11e7-9010-6962d6c84f1c.png)

If I am not mistaken, OsmAnd only differs `landuse=industrial`
Could we have an option to differentiate `landuse=residential`, `landuse=retail` etc too, please?

**Comment by sonora** [comment]
I think this may be a simplification in our default Map style, possibly on purpose.. If you change to another Map style (under Confugure map), e.g. the Touring view, it offers **significantly** more detail, but may be a little slower in rendering.

**Comment by vshcherb** [comment]
Yes this is done on purpose to make map with clear view. More details / Mapnik style display more convenient way.
