### ISSUE TITLE
gps location disturb in determining another route

### ISSUE THREAD

**Issue by kompowiec** [osmandapp/Osmand#4241]
I noticed very little issue: if i have set gps location if i will want setting new routing it appoint to me with position gps and not location that i wanted to.

For example, i set route to blue star:
https://i.imgur.com/mtSrHUV.png
route however set from actual gps location:
https://i.imgur.com/RitUVzv.png  

version osmand: 2.7.0#18143D

_Sent from my HUAWEI NEM-L21 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by sonora** [comment]
I think your mistake may be that you tapped th 'Go' button, which in your first screenshot is labelled Naviguij. This button starts the turn by turn and voice navigation and does of course always reference your 'real' position. If you want to see a route starting from some other location, just wait and do not tap the Go button.

**Comment by kompowiec** [comment]
right, that worked i I did'nt think about it. You can be closed.
