### ISSUE TITLE
Incorrect search results

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4250]
When searching for Прорізна str. in Kyiv, the app displays two results one in Kyiv and the other in another city (Біличі) without any indication.

Screenshots:
![imgpsh_fullsize](https://user-images.githubusercontent.com/20681525/28786691-a09b74a0-7622-11e7-8b5e-0f3510cdc382.png)
![imgpsh_fullsize 1](https://user-images.githubusercontent.com/20681525/28786690-a09af476-7622-11e7-830a-81cb138404d2.png)
![imgpsh_fullsize 2](https://user-images.githubusercontent.com/20681525/28786692-a09d5888-7622-11e7-9c2b-86e68c40ab17.png)

**Comment by vshcherb** [comment]
Possibly Duplicate to #4284
