### ISSUE TITLE
'Defibrillator' POI category returns no results

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4265]
Selecting the POI type 'Defibrillator' in Configure map and clicking on it returns no results with the message "Nothing found" despite attempts to increase search radius. 
However, while searching for "defibrillator" in the quick search, pressing  "see on map" results in defibrillator objects correctly displayed.

**Comment by xmd5a2** [comment]
Can't reproduce. I don't understand what "Selecting the POI type 'Defibrillator' in Configure map" means. It is possible to select certain poi type only via search (or categories - customize search).

**Comment by PaulStets** [comment]
What I meant by that was: when searching for POI 'Defibrillator' in Configure map - show POI - Search.

**Comment by xmd5a2** [comment]
Looks like these are the consequences of moving some "emergency" POI to new poi category "Emergency infrastructure". Not all users updated OsmAnd or maps to latest version.
![screenshot_2017-08-07-15-25-05](https://user-images.githubusercontent.com/5829014/29026499-b9b42b0a-7b84-11e7-91bc-f6d16bc2d412.png)
