### ISSUE TITLE
Make the (orange) map marker "sticky" again.

### ISSUE THREAD

**Issue by Boothy99** [osmandapp/Osmand#4266]
I have OsmAnd+ 2.7.4 installed on my android devices.
Android 6.0.1

Since the above update, the orange map marker now disappears as soon as I move or touch the screen (I am aware this is intentional and that the developers aim to make markers more intuitive for users).

Previously, I found it helpful to have it as a "sticky" marker when I was exploring around the area marked. It was simple to remove by swipe-down after tapping the marker to show the details tab.

If one carries out a search (of any kind) and make a selection from the list, ...the orange marker appears as expected on the map, to highlight your selection. However, ...if you now move the map even a fraction (inadvertently or intentionally), your orange marker disappears, and one has to go back to the search again to find your selection.

I'm aware I could leave a flag marker in place, but I'm then left with flags I'd need to click on & remove.

Could the developers kindly consider adding a settings toggle to turn  "sticky" on or off for the map markers, please?
Many thanks,
Dave.

![screenshot_2017-08-05-10-44-01](https://user-images.githubusercontent.com/13983995/28994656-abe22d0c-79cb-11e7-8e83-6e92b3c2e0d4.png)

**Comment by koutekp** [comment]
Absolutely agree. Make the marker sticky again. The current behaviour makes search result unusable.

**Comment by Boothy99** [comment]
Yes, it's currently driving me nuts :-\ and I've got a steady hand, but still keep losing my search result marker.

**Comment by sonora** [comment]
This is really a nuisance and needs to be fixed, I think. No need for a setting, let us just go to the previous behavior.

**Comment by Boothy99** [comment]
Thanks Sonora. I agree with your change of title & comment.

**Comment by vshcherb** [comment]
The previous behavior was even more confusing for people. I'm not talking about myself I was always supporting previous behavior. Though now my opinion has changed when I saw 3 cases where people didn't know how to hide it. 

If you need to make it really "sticky" use marker. At least 1 use case I see which is unavoidable, we should have on the screen +/- so person could zoom in & zoom out without loosing the marker.

If we want to keep marker than we should not close the menu same as Google Maps. Though there is a big question how to hide it cause there is no button for it.

**Comment by Boothy99** [comment]
Thanks @vshcherb. 
Yes, I could use a marker, but was hoping for maybe current behaviour with addition of option to revert to sticky in settings, if this was possible. 
I've found that scrolling with two fingers keeps the orange marker on-screen. Two finger zoom also leaves marker on the map, so at least we've a work around.
I appreciate your input.

**Comment by Boothy99** [comment]
Thanks @crimean & @vshcherb for taking not and altering marker behaviour on this.
Much appreciated.
Dave.

**Comment by GammaSQ** [comment]
I still experience this problem. Installed through fdroid, I'm using version 2.8.2

Workaround: when orange marker appears, enter confiugre-map menu and close it again. The marker will be sticky.

**Comment by Boothy99** [comment]
@GammaSQ 
Just use 2 fingers when scrolling the map. The marker stays put. Zoom buttons now added since the update.
