### ISSUE TITLE
Map Legend images not loading

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4267]
In Help - Map Legend there are no images.

Screenshot:
![screenshot_20170805-120818](https://user-images.githubusercontent.com/20681525/28994710-8b0b3ce2-79dd-11e7-9e3c-68249c0e17fc.png)

**Comment by PaulStets** [comment]
Fixed: 27fd8bbc1697ccd2f568326d922176e4c50d1826

**Comment by vshcherb** [comment]
https://github.com/osmandapp/osmandapp.github.io/commit/27fd8bbc1697ccd2f568326d922176e4c50d1826
