### ISSUE TITLE
Road has incorrect district relation.

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4268]
Map: France Auvergne Rhone Alpes. 
The road "Route des Combes" is indexed as "Route des Combes (les Pècles)". It is not in the district of Les Pècles, but in Les Favrands as drawn on the map. 

Location: https://www.openstreetmap.org/way/22877043#map=18/45.91484/6.85557

Screenshot:
![20641388_1896244590622346_823594861_o](https://user-images.githubusercontent.com/20681525/28994889-2f7790ce-79e2-11e7-9285-d64bafdde0ad.png)

**Comment by vshcherb** [comment]
As I see we don't have boundaries for district https://www.openstreetmap.org/node/2422902184#map=17/45.91453/6.85209

**Comment by vshcherb** [comment]
https://nominatim.openstreetmap.org/details.php?place_id=24540112, so it looks like a map issue
