### ISSUE TITLE
POI wheel keeps spinning

### ISSUE THREAD

**Issue by gunnar22** [osmandapp/Osmand#4269]
To reproduce observation: Define a navigation from some point to some point, click on the flag button (at bottom between X and the gear wheel). Click the POI off-on sliding to ON. Dismiss the POI page. Now the "wheel" left of POI keeps spinning, and the off-on sliding button is non-responsive, see screenshot. (OsmAnd+ 2.7.4)
![spinning-poi](https://user-images.githubusercontent.com/30504902/28995019-df0e2b10-79dd-11e7-87d7-f980887aca8c.png)

**Comment by vshcherb** [comment]
Couldn't reproduce. After toggling the button the dialog appears to select POI type and everything works fine.

**Comment by gunnar22** [comment]
Did you Dismiss the POI page without selecting a POI? That is when it happens. If I select a POI there is no problem.

**Comment by Boothy99** [comment]
I followed the above & clicked on "dismiss" when the POI option list appeared, and yes, the wheel continues to spin. It's also stuck that way if I clear the route & try to plan another route & click on POI flag. Prevents a selection. 
Had to restart OsmAnd then everything on again.
