### ISSUE TITLE
Tiles from osmand.net are too slow

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#4270]
After sharing a location from osmand the user receives a nice message with a link like https://osmand.net/go.html?lat=-21.79190&lon=-48.17690&z=17

The problem is that tiles from osmand.net take too much time to be rendered/processed (sometimes leaving the user with a gray screen only)

Maybe osmand could share a link directly to osm.org site?
If yes, maybe it could use the Humanitarian style? (which usually is a cleaner and more pleasant style)

We would get this then:

http://www.openstreetmap.org/#map=17/-21.79190/-48.17690&layers=H

**Comment by vshcherb** [comment]
With the link broken (it doesn't open osmand) it was really a problem last 2 weeks. We had hard to render tiles cause it was overloaded by 1 % of "heavy" users. Right now the problem should be fixed on 2 sides

**Comment by f1mishutka** [comment]
I generated link in OsmAnd+ application. Opening this link in browser takes minutes and I still have grey tiles on map... http://prntscr.com/njcx3n

Totally unusable :(

**Comment by vshcherb** [comment]
We are working on it as of today the load is much higher than new tiles could be generated

**Comment by f1mishutka** [comment]
Good luck, guys! I suppose a lot of people miss this functionality.
