### ISSUE TITLE
Not opening shared locations from https://osmand.net/go.html

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#4271]
A friend was having some issues with shared locations from osmand not opening on other phones.
For example, he shared https://osmand.net/go.html?lat=-29.729378&lon=-53.380432&z=11 (via some instant messaging client), the other person clicked on it, opened on OsmAnd but didn't get placed on that location.

ie, OsmAnd properly understands the link, opens it but keep displaying where the person is currently located (instead displaying the shared location)

The person who can't properly see the shared locatgion is using Google Play's OsmAnd version.
I can confirm that with `OsmAnd Nightly 2.7.0#18130D` the problem exists too.

**Comment by scaidermern** [comment]
Confirmed with 2.7.4.

**Comment by vshcherb** [comment]
Fixed
