### ISSUE TITLE
Track recording does not work

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4274]
Sony Xperia Ultra 6 
Android  7.1.1

The problem always appears when the user saves the track before starting another, the recorded track has no time, km, tracking information, the files are always empty.

Setting Logging motion detection, Logging minimum accuracy and Logging minimum speed to Not Selected does not help.

Reinstallation helps for a short time.

**Comment by sonora** [comment]
I cannot reproduce this. Do you see the data accumulating ok during the recording, e.g. the recorded distance in the GPX widget on the map screen, or does this also remain at 0m?
