### ISSUE TITLE
Unable to add custom POI category to Show/Hide POI quick action

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4280]
In quick action when trying to add custom POI category via Search the search is not being displayed. Instead, the Custom filter field is added.

Screenshots:

![20746974_1898028880443917_1151197901_o](https://user-images.githubusercontent.com/20681525/29061264-c1f95cbc-7c25-11e7-943b-a5ebbdc3f29e.png)
![20706114_1898028723777266_1444693649_o](https://user-images.githubusercontent.com/20681525/29061263-c1f5705c-7c25-11e7-9972-3ef9c8c0b72c.png)

**Comment by vshcherb** [comment]
We shouldn't display search here.
