### ISSUE TITLE
Persian Translation

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4281]
Change مستراح to سرویس بهداشتی.

![screenshot_20170807-201431](https://user-images.githubusercontent.com/20681525/29065287-500162a8-7c34-11e7-8788-1892fb8ff915.png)

**Comment by hakuchi** [comment]
A other question is:
Why should OsmAnd change the description from **toilets** to **WC**?

**Comment by hakuchi** [comment]
fixed in Weblate
