### ISSUE TITLE
[REGRESSION] Search Results: Streetname en Town are truncated somehow

### ISSUE THREAD

**Issue by CJTmmr** [osmandapp/Osmand#4284]
Using latest nightly and also on Beta-Play-Store 2.7.4 from 2017-08-01
Map: The Netherlands; I am somewhere near town Gouda.

Using Search and directly entering a Streetname with number; e.g. Doormanstraat 2
Result: A list with many adresses - only the distance can tell you which one you mean.
![2017-08-07 11 20 51](https://user-images.githubusercontent.com/15076257/29090361-9f73146c-7c7f-11e7-93cd-5041f4558dee.png)

In former versions (in any case before 2017-06-25)
the result was: each adress with the according Town.
![2017-08-07 11 22 59](https://user-images.githubusercontent.com/15076257/29090489-0517b3cc-7c80-11e7-8a9a-68539821b62c.png)

With screen in landscape-mode all it still okay:
result with nightly:
![2017-08-07 13 16 26](https://user-images.githubusercontent.com/15076257/29091137-36a7d64a-7c82-11e7-9e3c-a0f70882d446.png)

With a short streetname the town is sometimes displayed: 
![2017-08-08 21 43 11](https://user-images.githubusercontent.com/15076257/29091236-8f28a344-7c82-11e7-8d29-87957b6b4b12.png)

With a longer streetname even the streetname is truncated:
"Julianastraat" is  often preceded bij "Koningin" (="Queen") 
![2017-08-08 21 46 28](https://user-images.githubusercontent.com/15076257/29091448-4a28cbd8-7c83-11e7-8d1f-163df978d999.png)

**Comment by sonora** [comment]
Same happens for city search. In portrait orientation, on many devices you just see
- Line 1: town/village name
- Line 2: Tag (like"Village"),  xx km
- Missing is the rest after km, like "from Barcelona"

**Comment by vshcherb** [comment]
<img width="493" alt="screen shot 2017-09-20 at 23 47 38" src="https://user-images.githubusercontent.com/1042025/30669344-4cde8280-9e5e-11e7-8c0f-14a58386a447.png">
<img width="571" alt="screen shot 2017-09-20 at 23 46 18" src="https://user-images.githubusercontent.com/1042025/30669345-4cf924f0-9e5e-11e7-8eda-d33b40fb5086.png">
The issue looks like is in Android UI backend provides proper data
