### ISSUE TITLE
nautical maps always listed for upgrade no matter what

### ISSUE THREAD

**Issue by yet-another-random-username** [osmandapp/OsmAnd#4285]
Hi,

Ages back I purchased the nautical maps extra and downloaded:

* world seamarks (dated: 02/07/2017)
* nautical depth contours (dated: 17/03/2017)
* nautical depth points northern hemisphere (dated: 17/03/2017)
* nautical depth points southern hemisphere (dated: 17/03/2017)

Ever since then they've been on my update list (except for world seamarks which is in good standing). I've tried updating them to no avail. I'm going to try removing them* (but I need to update before I'm offered the chance**) and reinstalling but I think I've tried that before.

I'm on the beta-test list and have the latest version of Osmand available. My Android version is 7.0 (though this was an issue with 6, also, from memory) running on a Samsung Galaxy S7.

Data storage folder is set to external storage.

I have the following extras installed:
* OsmAnd Contour Lines 1.0
* OsmAnd Nautical 1.0
* OsmAnd Ski Maps 1.0

OsmAnd has permission for Camera, Location and Storage.

\* I should really report after I've done this test but it always takes /ages/ to do the update and I wind up forgetting and needing to start over when I'm next to an access point without download quotas.

** I'll be filing another bug for this.

**Comment by vshcherb** [comment]
Not reproducible on dev devices.

**Comment by yet-another-random-username** [comment]
I don't know what's going wrong, then. I did a complete uninstall and, on a blank-slate, attempted to install and the same problem occurred.

I had the idea later that, perhaps, this might be due to my maps going on an sd card (not internal storage) but... I'm reluctant to try again (just to try it out) as I've a full compliment of maps installed. Will be happy to give it a go, though, if it's confirmed as a likely thing.

The latest beta version available on the play store is in use.

**Comment by mattmax42** [comment]
I am observing the same behaviour on Android 8.0 and now on a new device (so fresh install) on Android 9.0 as well.
Nautical depth contours; Northern hemisphere depth points; and Southern hemisphere depth points,
all dated 17 Mar 2017 are continuously showing as available updates, even though the latest version is already installed on the device. This is in OsmAnd 3.3.8.

**Comment by sjkosij** [comment]
Hi all,

I am also experiencing a similar issue. The nautical depth contours/points still appear in the download list even after updating it. This also happens for contour lines. Example:

![SmartSelect_20190812-131851_OsmAnd](https://user-images.githubusercontent.com/54013896/63128539-82470d80-bff8-11e9-85b4-9f5310544a2d.jpg)

For nautical depths, I have noticed this issue for > 12 months. For contour lines, I have only noticed this issue over the last few weeks when there were new updates. There does not appear to be any issues with the map display itself - the nautical depths and contours are visible. When I look at the relevant .obf map files, the 'last modified date' has the correct date - so it seems the files do get updated, but it just doesn't get removed from the download list in the app.

App/device details:
Samsung Galaxy S7 Edge, Android 8.0
Osmand Unlimited v3.4.6 (2019-08-03)

Thank you

**Comment by mattmax42** [comment]
Brief update, this problem now extends to other maps as well, currently affected are:
The three nautical maps as above
Australia South Australia Contour lines
Australia Ashmore and Cartier Islands
Australia Cocos (keeling) Islands
Australia Coral Sea Islands

OsmAnd 3.4.8
Samsung Galaxy Note 9 on Android 9
