### ISSUE TITLE
Buildings not shown in latest beta release

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#4287]
What version of OsmAnd are you using, on what device and Android/iOS version?

OsmAnd 2.7.5, released 2017-08-08 on Android 5.0, Samsung Galaxy S5

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

Offline maps from OsmAnd.  

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

Us_northamerica_georgia, dated June 30, 2017

In the latest beta channel release, buildings are no longer rendered on the map in any of the standard modes (browse, car, bike, pedestrian).  The building *numbers* are shown in place of the buildings.

Hide polygons and Hide buildings are NOT enabled.

I'm pretty sure this was working in the previous beta channel release.

Additional note:  if I enable Hide house numbers, they are still displayed for non-house buildings (e.g., retail stores).  Not sure if this is intended behavior or not, so I thought I'd mention it.

**Comment by vshcherb** [comment]
Please try disable/enable beta build again. There were only few fixes in 2.7.5 not related to map rendering. It is possible that installation was corrupted.

**Comment by vshcherb** [comment]
Not reproducible (tested on 3 devices)
