### ISSUE TITLE
Offline maps on iOS: empty parts of the map

### ISSUE THREAD

**Issue by rhaamo** [osmandapp/Osmand#4289]
Hello,

OsmAnd (1.3.2 it seems, latest from App Store at the moment) on iOS (10.3.2)
Maps : offline, Ile-de-France (294,2M, created on 01/08/2017 02:00)

I'm using Bike mode, map type OsmAnd, mode day, no underlay, for overlay I use Hillshade underlay.

When displaying the map from near "Gommecourt" (here: http://www.openstreetmap.org/#map=14/49.0793/1.5914) a whole part of the map is just empty, whatever zoom level I use, the country like "Sainte-Geneviève-lès-Gasny" or "Gasny" are not here.

I'm using offline maps, not online, online ones does not have this issue.

Any ideas why there is empty spots in the map using offline tiles ?

Example (http://www.openstreetmap.org/#map=13/49.1324/1.5939) using only offline tiles, then adding online as overlay to spot the missing parts:
![img_1776](https://user-images.githubusercontent.com/8625/29119749-b2ea5068-7d07-11e7-99e6-0bc8b09dde5e.PNG)
![img_1775](https://user-images.githubusercontent.com/8625/29119753-b853b53a-7d07-11e7-95d9-c7e7d0828473.PNG)

**Comment by xmd5a2** [comment]
That is obvious: you have downloaded only "Ile de France" map and this is its border.
