### ISSUE TITLE
Regression: opening http:osmand.net location does not work

### ISSUE THREAD

**Issue by HolgerJeromin** [osmandapp/Osmand#4297]
Osmand generates geo uri and http osmand.net when sharing the location. 

Clicking on the http link can open Osmand but does not load the position anymore.

Standort: geo:52.019035,8.501658?z=19
https://osmand.net/go?lat=52.019035&lon=8.501658&z=19

Tested with play store stable and beta (2.7.5)

**Comment by vshcherb** [comment]
Yes, it is a regression. Due to https protocol is used now (http is still supported). It is a duplicate issue and we will fix it in 2.8

**Comment by HolgerJeromin** [comment]
ref #4321
