### ISSUE TITLE
Maps are deleted on every update

### ISSUE THREAD

**Issue by rdoeffinger** [osmandapp/OsmAnd#4299]
When maps are stored in multiuser (obb storage) then after every update the "get started" screen appears.
At some point before that, all existing maps are deleted. I first thought I must have been done something stupid and/or that it just did not detect the storage location, but this time I double checked: Maps are there, install update, start app, maps are gone.
Most curious: it doesn't delete everything, for example all subdirectories for example SRTM, tile maps like hillshade and live map updates are there, just the main maps including the world map and altitude adjustment map are gone.

**Comment by vshcherb** [comment]
hm very weird

**Comment by rdoeffinger** [comment]
Agree that it is weird.
It still happened with the latest update, so for now I switched from obb path to standard internal storage to see if that avoids the issue next time (downloading several GB on every update is getting a bit old).
Unfortunately haven't had time to search the code much myself, couldn't see any obvious logic at least that would delete files...

**Comment by scaidermern** [comment]
Same problem as #13404?

**Comment by vshcherb** [comment]
Yes merged to #13404
