### ISSUE TITLE
Track navigation is not overwriting previous destinations causing misrouting

### ISSUE THREAD

**Issue by Cool-hand-fluke** [osmandapp/Osmand#4300]
osmand 2.6.3
lineages 14.1
android 7.1.2
LG g2 d802

If I have stopped routing the start and stop points are still in the destinations list. If I now show a track on the map and press the routing button I am asked if I want to choose the displayed track for navigation to which I choose 'yes'. Unfortunately this doesn't seem to overwrite the from destinations and misrouting occurs. If I remove the destinations manually and then try routing from the displayed track it works ok.

**Comment by sonora** [comment]
This is by design, I think. No reason why adding an interim GPX track to an existing setup of destinations should delete all these destinations. If desired, you can very simply do this manually. This is MUCH more simlle than the opposite: re- adding them all if we deleted them by default.

**Comment by Cool-hand-fluke** [comment]
I'm not trying to add to previous destinations, I'm loading a track which is the whole route but the previous start point is not cleared

Regards Paul

On 14 August 2017 17:16:29 BST, Hardy <notifications@github.com> wrote:
>This is by design, I think. No reason why adding an interim GPX track
>to an existing setup of destinations should delete all these
>destinations. If desired, you can very simply do this manually. This is
>MUCH more simlle than the opposite: re- adding them all if we deleted
>them by default.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/osmandapp/Osmand/issues/4300#issuecomment-322235542

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sonora** [comment]
Ah, I see, but that I cannot actually reproduce. Looks like it was maybe already fixed between v2.6.3 you report this for and our current 2.7.5. Maybe you can try again with the latest app version, and if you can still reproduce it please give specific step-by-step instructions how. Thx!

**Comment by Cool-hand-fluke** [comment]
I have reproduced it on 2.7.5, First I did a small local trip, then stopped it with the x,  lthen i loaded the track and used it for routing but the info from the previous routes start point hadn't been cleared and so the misroute occurs, I manually delete the destinations and then the routing works correctly, please let me know if there's any testing you would like me to do.

Best regards Paul

On 14 August 2017 18:48:03 BST, Hardy <notifications@github.com> wrote:

Ah, I see, but that I cannot actually reproduce. Looks like it was maybe already fixed between v2.6.3 you report this for and our current 2.7.5. Maybe you can try again with the latest app version, and if you can still reproduce it please give specific step-by-step instructions how. Thx!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼



On 14 August 2017 18:48:03 BST, Hardy <notifications@github.com> wrote:
>Ah, I see, but that I cannot actually reproduce. Looks like it was
>maybe already fixed between v2.6.3 you report this for and our current
>2.7.5. Maybe you can try again with the latest app version, and if you
>can still reproduce it please give specific step-by-step instructions
>how. Thx!
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/osmandapp/Osmand/issues/4300#issuecomment-322259171

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Cool-hand-fluke** [comment]
Once I've uploaded a screen recording to Dropbox I'll post the link

On 14 August 2017 21:44:00 BST, PaulO <p.a.oakley@gmail.com> wrote:
>I have reproduced it on 2.7.5, First I did a small local trip, then
>stopped it with the x,  lthen i loaded the track and used it for
>routing but the info from the previous routes start point hadn't been
>cleared and so the misroute occurs, I manually delete the destinations
>and then the routing works correctly, please let me know if there's any
>testing you would like me to do.
>
>Best regards Paul
>
>On 14 August 2017 18:48:03 BST, Hardy <notifications@github.com> wrote:
>
>Ah, I see, but that I cannot actually reproduce. Looks like it was
>maybe already fixed between v2.6.3 you report this for and our current
>2.7.5. Maybe you can try again with the latest app version, and if you
>can still reproduce it please give specific step-by-step instructions
>how. Thx!
>
>—
>You are receiving this because you authored the thread.
>Reply to this email directly, view it on GitHub, or mute the thread.￼
>
>
>
>On 14 August 2017 18:48:03 BST, Hardy <notifications@github.com> wrote:
>>Ah, I see, but that I cannot actually reproduce. Looks like it was
>>maybe already fixed between v2.6.3 you report this for and our current
>>2.7.5. Maybe you can try again with the latest app version, and if you
>>can still reproduce it please give specific step-by-step instructions
>>how. Thx!
>>
>>-- 
>>You are receiving this because you authored the thread.
>>Reply to this email directly or view it on GitHub:
>>https://github.com/osmandapp/Osmand/issues/4300#issuecomment-322259171
>
>-- 
>Sent from my Android device with K-9 Mail. Please excuse my brevity.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Cool-hand-fluke** [comment]
https://www.dropbox.com/sh/nbufb90azq6kkyf/AAAmI7iGgHTUeKjnqStkTkPLa?dl=0

This is a screen recording of the issue.

Regards Paul

On 14 August 2017 18:48:03 BST, Hardy <notifications@github.com> wrote:
>Ah, I see, but that I cannot actually reproduce. Looks like it was
>maybe already fixed between v2.6.3 you report this for and our current
>2.7.5. Maybe you can try again with the latest app version, and if you
>can still reproduce it please give specific step-by-step instructions
>how. Thx!
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/osmandapp/Osmand/issues/4300#issuecomment-322259171

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sonora** [comment]
I can reopen for another investigation, but it may still be by design. Have not managed to download the mp4.

**Comment by Cool-hand-fluke** [comment]
I'll record one with a smaller file size later today and upload it 

On 15 August 2017 07:33:03 BST, Hardy <notifications@github.com> wrote:
>I can reopen for another investigation, but it may still be by design.
>Have not managed to download the mp4.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/osmandapp/Osmand/issues/4300#issuecomment-322388234

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Cool-hand-fluke** [comment]
Try this link

https://www.dropbox.com/s/d0q7fa4qzn2l693/screenrecorder.20170815064543.mp4?dl=0

On 15 August 2017 07:33:03 BST, Hardy <notifications@github.com> wrote:
>I can reopen for another investigation, but it may still be by design.
>Have not managed to download the mp4.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/osmandapp/Osmand/issues/4300#issuecomment-322388234

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by vshcherb** [comment]
Start point in many situations for navigation is "My location" .
