### ISSUE TITLE
Avoid option ignored in pedestrian mode

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4301]
Pedestrian navigation mode ignores specified points to avoid.

Screenshot:
![20904366_1901498696763602_574143544_o](https://user-images.githubusercontent.com/20681525/29309309-cef3dd48-81b1-11e7-8b49-109dfd17af4d.png)

**Comment by scaidermern** [comment]
Could it be that the point to avoid is on the main road whereas the pedestrian route is along the footway next to the main road?

**Comment by PaulStets** [comment]
I highly doubt it.

![20883270_1901508750095930_834328871_o](https://user-images.githubusercontent.com/20681525/29309661-5e8db66c-81b3-11e7-9da0-527dbea67640.png)
