### ISSUE TITLE
Automatically enabled Mapillary layer in split screen view

### ISSUE THREAD

**Issue by homlett** [osmandapp/Osmand#4305]
Hi,

The integration of Mapillary data is a good move, good job! It's a shame that the official app isn't FOSS or at least work without Google Play, but it's another story https://github.com/mapillary/mapillary_issues/issues/1124. The display of Mapillary street level picture in OsmAnd is pretty good. However, I think it could be a little bit improved.

Obviously, it's not convenient to keep the Mapillary layer enabled all of the time (cf. because https://github.com/osmandapp/Osmand/issues/4263 for example). But clicking on a POI and displaying the Mapillary picture is enough in most of the case. That's why, it would be nice if the Mapillary layer is automatically enabled when a street level picture is displayed (in map area of the split screen) and then disabled when closed. Because like this it would be possible to see other pictures and pick an another one easily. Also, it would be possible to see in which angle the picture is taken, which is important to know I think.

Let me know if my point isn't clear enough, I'm not an native English speaker.

![screenshot_20170815-160956](https://user-images.githubusercontent.com/2879530/29340977-a87d31ee-81d6-11e7-845e-3e9eb2892c7c.png)

![screenshot_20170815-161034](https://user-images.githubusercontent.com/2879530/29340978-a89438ee-81d6-11e7-98bd-fd32bd7531f0.png)

**Comment by vshcherb** [comment]
The UI & UX need to be though through

**Comment by vshcherb** [comment]
Fixed
