### ISSUE TITLE
Inconsistent info cards for POIs

### ISSUE THREAD

**Issue by TimMagee** [osmandapp/Osmand#4306]
Right now if you click on a POI on a map an info card pops up with the name of the POI. 
Example: A waterfall named "Rainbow Falls" would have an info card with the label "Rainbow Falls".
However, if you open the same POI from the search menu, the info car label will be "POI Type POI Name". 
Example: The waterfall from the previous example would be "Waterfall Rainbow Falls". 

I propose that these be consistent across the UI no matter how we access the POI.

Attached are screenshots demonstrating the difference.
![screenshot_2017-08-13-17-01-34](https://user-images.githubusercontent.com/11220851/29374112-50764c26-827e-11e7-9172-9a90e355156e.png)
![screenshot_2017-08-13-17-01-26](https://user-images.githubusercontent.com/11220851/29374115-55a64bd8-827e-11e7-908c-c932ba51105c.png)

**Comment by pebogufi** [comment]
And have a look on the text categorie below the headline: 
"Waterfall" vs. "Water"
Prter

**Comment by hakuchi** [comment]
this is a wrong tagging on OSM.
https://www.openstreetmap.org/node/1899078856
a waterfall no need the key `natural=water`

**Comment by pebogufi** [comment]
May be, but we would like it to be consistent.

**Comment by TimMagee** [comment]
These info cards are inconsistent no matter what the tags are. I can produce more screenshots of correctly marked nodes of all different types. The cards are different when opened from search results than when opened by clicking on the maps.

**Comment by xmd5a2** [comment]
Obviously this is wrong tagging. This leads to 2 POI: 1)natural=water 2)waterway=waterfall because all of these tags are "main". No need to tag waterfalls with natural=water or at least I can't imagine reason. But there is more then 400 POIs in OSM with this tag combination so we can implement removing natural=water from such objects.

**Comment by TimMagee** [comment]
The bug is not the wrong tagging. Now I present to you another example of the inconsistent info cards. The first one is selected from the search and the second one is selected from the map. Please note that the one from search says "Gas station Exxon" while the one from the map says "Exxon". I am referring to the TITLE of the info card, not anything else. All bad tagging aside, this bug is still real.
![screenshot_2017-09-08-12-34-24](https://user-images.githubusercontent.com/11220851/30221772-9f6a0d06-9492-11e7-82ce-db75c518af41.png)
![screenshot_2017-09-08-12-34-46](https://user-images.githubusercontent.com/11220851/30221779-a92deede-9492-11e7-8ca2-e449e2b00e48.png)
Please not that this is the same POI just selected in two different ways. The same POI should always generate the same info card.

**Comment by pebogufi** [comment]
Yes, but in the first Screenshot there is the category + name, the second only with the name. But - again - of course, it should be identical.

**Comment by TimMagee** [comment]
Exactly @pebogufi. Thank you!

**Comment by TimMagee** [comment]
This issues, from a user standpoint, seems related to a previous issue I noticed, #3646. That issue relates to the fact that when searching by address the info card simply has the address and not the name of the business. Once again, those info cards are different then if you click on the same POI on the map.
