### ISSUE TITLE
Render error when part of a lake is part of the park

### ISSUE THREAD

**Issue by aleung** [osmandapp/Osmand#4308]
What version of OsmAnd are you using, on what device and Android/iOS version?
- OsmAnd 2.7.5 on Android 7.1.1

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?
- Offline maps: People's Republic of China, Guangdong Province, Aug 1, 2017

There is a lake and a park half surround the lake. But only partial of water area belongs the park.
On map the park in an area which covers partial of the lake. 

OsmAnd doesn't render the map correctly. The lake becomes hidden and is covered under the park.

![187807987](https://user-images.githubusercontent.com/271538/29402057-1d996836-8366-11e7-912e-436ac11b23ee.jpg)

On openstreetmap.org, the render has no problem. Here is the map of that place:
https://www.openstreetmap.org/#map=17/23.11780/113.28719 

Map.me Android hasn't render problem neither:
![1167041293](https://user-images.githubusercontent.com/271538/29402009-ef69db08-8365-11e7-902e-be9b1dbe663a.jpg)

**Comment by vshcherb** [comment]
This considered as incorrect mapping cause it creates ambiguity what's needs to be displayed. The default algorithm that sorts area by size in this case fluctuates due to rounding issue.
