### ISSUE TITLE
Error in the calculated route

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4309]
The app builds the route on the road with oncoming traffic. 

The coordinates of the intersection 43.936716, 42.727678

Screenshot:
![05-2_correct route](https://user-images.githubusercontent.com/20681525/29402209-cf68af56-833c-11e7-9463-986e0ec7f702.jpg)

**Comment by scaidermern** [comment]
What do you mean with "oncoming traffic"? According to the [data](https://www.openstreetmap.org/way/270376113) there is a `oneway=no` tag, meaning this road can be used in both directions. Is the data wrong?

**Comment by PaulStets** [comment]
Yes, seems like the data is wrong according to a user. Sorry, I was not able to check OpenStreetMap info, because the website wouldn't load for me.

**Comment by scaidermern** [comment]
Are you able to fix the data yourself or should some else fix it?

Are you really sure that this is a oneway road? Usually the `oneway=no` gets only added if it is definitely *not* a oneway road.

**Comment by scaidermern** [comment]
Looks like you are right. According to [mapillary](https://www.mapillary.com/app/?lat=43.936811456876455&lng=42.72737935730936&z=17&menu=false&pKey=QQ3E3VrNNHaAm2uHCC2msg&focus=photo) you are not allowed to enter this road from the other direction. And there is a double center line.

**Comment by PaulStets** [comment]
I'm experiencing the issue with osm.org right now. The map tiles are not loaded for me, so it would be great if someone else could make the correction on the map.

**Comment by scaidermern** [comment]
I've fixed it: https://www.openstreetmap.org/changeset/51200348

This issue can be closed.

**Comment by vshcherb** [comment]
@scaidermern Thanks
