### ISSUE TITLE
OsmAnd crashes when trying to use measurment tool from menu

### ISSUE THREAD

**Issue by MAlfare** [osmandapp/Osmand#4312]
OsmAnd~2.7.#22389 and before (since introduction of this tool)
Lenovo tablet Android 4.4
Asus tablet Android 4.3

Lots of exception logs sent.

The tool **does** work on smart-phone Motorola G4+ Android 7.0

**Comment by dmpr0** [comment]
This feature is still under development.

**Comment by MAlfare** [comment]
OsmAnd~2.7.0#22406 works on both tablets!

**Comment by vshcherb** [comment]
Should be fixed now.
