### ISSUE TITLE
Proposal: replace single-select vehicle height setting with input field or..

### ISSUE THREAD

**Issue by Alex-was-here** [osmandapp/Osmand#4314]
## .. offer a set of choices of 0.10 meter increment.

Now with a 3.80 meter high vehicle I use for work (or sometimes one of 3.60m) I can only choose 4.00m in the app to be on the safe side in practice - which routes me around bridges I can pass under.
Where I work, Amsterdam, the height of bridges below 4 meters varies by the decimeter. This is also the case in many other cities. In the app though, height can only be increased or decreased by half meters.

In my experience of making deliveries by truck in the city, height is the most restrictive vehicle dimension, followed by width and then by weight. Width cannot be set in the app[*] but is quite restrictive too. So if there could be a setting for that dimension too..

But first maybe someone would please consider allowing the height setting to be more precise ?
> Thank you!

_________
[*] Length neither, but the length and width of vehicles cannot be compared with relevant data from OSM, I guess. If that is so, length and width restrictions as displayed on traffic signs could perhaps be reported and confirmed by drivers through a button within the app. Good idea?

**Comment by pebogufi** [comment]
You can have your private specialized routing.xml.
Search in this file for
parameter id="height"
In this line add the values you need (3,60 3,80) and descriptions.
After restarting the app the values are in the selection list.
BUT: according to my experience the navigation with maxheigth is not very reliable, it blocks streets which should be ok. So be careful to use it. 
If you find problems, report it.
Regards Peter

**Comment by Alex-was-here** [comment]
Thank you Peter!

**Comment by sonora** [comment]
I only just come across this issue now, but I do think our "Height limit" feature does need some work, at least as follows:
- We offer only "meters", there is no menu for "ft", e.g. when Driving region is set to "North America"
- The current granularity of strictly 0.5m steps does in deed not make too much sense. There are "notorious" ranges where you would often need a better granularity, like the region between 3 and 4.5 meters (definitely between 3.5m and 4.0m), where a 0.1m step would make sense, and in the US probably the range around 12-14 feet, where you would normally use something down to the inch level for specification, e.g. 13'3''.

This is a vehicle-specific setting, hence for most users pretty much a one-time setting. Maybe we should really consider anther selector, like a manual input field or some sort of slider?
