### ISSUE TITLE
Displaying surveillance cameras in OsmAnd

### ISSUE THREAD

**Issue by bezin** [osmandapp/Osmand#4315]
Hello there,

I am planning to map surveillance cameras (man_made=surveillance) in my area and I would like to use OsmAnd for this. So I selected "Surveillance" under POI to see which are already mapped. I realized these are way less than are actually in the OSM database. In the area investigated, OsmAnd [displays a single node](http://www.openstreetmap.org/node/4345485961), while the [Overpass API returns 118 Nodes ](http://overpass-turbo.eu/s/r6A) in roughly the same area. 

I further analyzed the cameras displayed in OsmAnd in a larger area. I figured, that only all those with [["man_made"="surveillance"] AND ["name"]](http://overpass-turbo.eu/s/r6B) are displayed. For the aforementioned node (4345485961) the name tag might be applicable, but most surveillance nodes will never need and hence get a name tag. 

I would like to propose, that the name tag is to be made not mandatory for surveillance nodes and would love to here other opinions :)

Cheerio

**Comment by bezin** [comment]
Did not see #3155. Nevermind ;)

**Comment by erdmark** [comment]
I am using this code in a file /storage/extSdCard/osmand/rendering/camera.render.xml to display all surveillance cameras.
<renderingStyle name="" depends="default" version="1">
	<point>
		<case tag="man_made" value="surveillance" icon="camera" shield="white_orange_poi_shield"/>
	</point>
</renderingStyle>


I tried to highlight all cameras with surveillance=public but it didn´t work like this, maybe someone knows why:
<case tag="man_made" value="surveillance" icon="camera" shield="white_orange_poi_shield">
	<case additional="surveillance=public" icon="camera" shield="fav_red_shield"/>
	<case tag="surveillance" value="public" icon="camera" shield="fav_red_shield"/>
</case>

**Comment by erdmark** [comment]
<case tag="man_made" value="surveillance" icon="camera" shield="white_orange_poi_shield">
			<case additional="surveillance=public" icon="camera" shield="fav_red_shield"/>
			<case tag="surveillance" value="public" icon="camera" shield="fav_red_shield"/>
		</case>

**Comment by erdmark** [comment]
```
<renderingStyle name="" depends="default" version="1">
'''

**Comment by erdmark** [comment]
I am using this code inside /storage/extSdCard/osmand/camera.render.xml to show all surveillance cameras:
```
<renderingStyle name="" depends="default" version="1">
	<point>
		<case tag="man_made" value="surveillance" icon="camera" shield="white_orange_poi_shield"/>
	</point>
</renderingStyle>
```

I would like to highlight cameras with surveillance=public but that didn´t work, maybe someone can help me with this:
```
<case tag="man_made" value="surveillance" icon="camera" shield="white_orange_poi_shield">
	<case additional="surveillance=public" icon="camera" shield="fav_red_shield"/>
	<case tag="surveillance" value="public" icon="camera" shield="fav_red_shield"/>
</case>
```

**Comment by scaidermern** [comment]
#3155 got closed without adding rendering of surveillance cameras. Can we get this issue opened again?
