### ISSUE TITLE
Incorrect route

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4318]
Location: https://www.openstreetmap.org/#map=18/51.16806/-114.13165

Screenshot: 
![screenshot_20170816-011756](https://user-images.githubusercontent.com/20681525/29507675-d39dd748-8659-11e7-9443-b90f0b96ae29.png)

**Comment by xmd5a2** [comment]
Not reproducible. However this secondary_link was fixed a week ago. Looks like an OSM problem.
![screenshot from 2017-08-23 12-58-02](https://user-images.githubusercontent.com/5829014/29610406-bf9910c8-8802-11e7-85d5-d47d34a2796b.png)
