### ISSUE TITLE
Route calculation failure

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4319]
Setting destination to Lat 44.69337 Lon -121.07208 
From Lat 46.37537 Lon -120.32051

Setting subsequent destination to Lat 46.56225 Lon -120.50045 leads to the Error in route calculation with the toast: Fast route calculation failed (-50).

**Comment by PaulStets** [comment]
The issue happens only in native routing.

OsmAndMapCreator with native routing crashes when it allocates all the available free RAM.

Console output:
![screenshot from 2017-10-08 14-52-16](https://user-images.githubusercontent.com/20681525/31316576-dc7f549a-ac38-11e7-83d5-8d64932955da.png)

**Comment by vshcherb** [comment]
https://www.openstreetmap.org/#map=18/44.69289/-121.07338
https://www.openstreetmap.org/#map=18/46.37537/-120.32051
