### ISSUE TITLE
Incorrect river rendering

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4320]
Location: https://www.openstreetmap.org/#map=16/44.1540/-79.9071

Screenshots:
![screenshot_20170814-154629](https://user-images.githubusercontent.com/20681525/29517246-e620f3fa-867c-11e7-80f1-4f7865637a36.png)
![screenshot_20170817-105644](https://user-images.githubusercontent.com/20681525/29517247-e62324c2-867c-11e7-8f97-ead9e3b93bdc.png)

**Comment by xmd5a2** [comment]
Can't reproduce. Old maps?
![screenshot from 2017-08-23 11-38-38](https://user-images.githubusercontent.com/5829014/29606728-d4c585f4-87f7-11e7-9622-5dccf3f8ecc7.png)
