### ISSUE TITLE
No "please turn over" guidance when going wrong

### ISSUE THREAD

**Issue by kayb94** [osmandapp/Osmand#4326]
Hi there,

I went for a pretty far bike tour (several weeks) with Osmand as navigation - it mostly worked out pretty good. Compliment for that!
Anyway, there was one source of frustration I had almost every day: When I took the wrong way, Osmand would never tell me. I never had it tell me to "please turn over" or something. It would only tell me a new driving instruction when stopping with the distance I had gone since the last driving instruction ASSUMING I had turned over (this can be very confusing). This would be a huge improvement. I'm not sure, but some googling makes me think, this previously actually was a feature.

This was a huge issue for me, as I could not use the display for navigation (where going wrong would have been obvious of course). I actually had bought a bag to be able to use the display for navigation, but had to stop and use only voice guidance, because:
- Phone overheats and crashes, especially with some sunlight.
- Battery dies out way too far (roughly 1% per minute)
When it was raining and there was no shelter, I additionally was not able to unlock the screen to see which way to go, sometimes resulting in going wrong even further, which can be pretty frustrating (am I wrong, am I right?)
I'm not referring to the the cases, where Osmand is able to instantly calculate a new route. This might be working good in cities with many alternative routes, but rarely does work in rural regions with low density of roads (where it is even more bad to go wrong ;-) ).

To give you an idea of how much or not of an issue this was (for me): In average, I went about 5km/100km extra due to mistaken instructions.

**Comment by kayb94** [comment]
I'm willing to help or look for it myself, if someone can tell me approximately where in the code I have to look. I was not able to find something promising.

**Comment by sonora** [comment]
Let us please discuss this first, because we already have all the code and voice prompts in place, but it was mostly disabled on purpose years ago, I think probably with the car use case in mind.

**Comment by kayb94** [comment]
Okay, never mind! I would be willing to test (by bike) too, if that is an issue.

**Comment by kayb94** [comment]
sonora in #4368:

> ...where U-turns may be much more preferred and easier than longer detours, not sure yet.

Please note, that I actually did not get a longer detour (new routing) very often, but could be going the wrong way (practically) infinite. The maximum I went wrong without recognizing was ~10km. Of course, this only happens in rural regions, where a wrong turn is a huge issue.

Please also note I'm using BRouter (forget to mention), if that makes a difference.

PS: Sorry for the cross-posting!

**Comment by sonora** [comment]
Regarding "I'm using BRouter": Can you please specify specific instructions how to reproduce, preferably slso with an example, or else it will naturally be hard or impossible to fix.

**Comment by gammeredith** [comment]
This has proven to be a major issue for me as well when cycle touring. Detours as a result of missing turns  is frustrating. What is needed  are clear and concise instructions that one has deviated from the planned route.

**Comment by gammeredith** [comment]
"Automatic route recalculations will rarely (if ever!) consider a u-turn when someone missed their turn. This is in particular a problem when cycling or walking".

**In the real world this is a major issue. Off track notifications / warnings are imperative.**

**Comment by doctor-beat** [comment]
+1. Big alarm bel ringing when going off track, at least in bicycle + pedestrian mode.

**Comment by doctor-beat** [comment]
To illustrade my case for this:

This weekend I planned a 60km bike ride (created on gpsies + uploaded into osmand). To protect my phone and maximise battery life i put the phone in my backpocket and listened to the voice nav via an earpiece.  This turned out difficult. In many occasions, specifically when approaching a Y-like-roadsplit, when often osmand does not generate a navigation hint, we went the wrong way. (And there were many of these)

And then no warning, no nothing. One just keeps going until, maybe, osmand starts by saying something like 'The new distance is ...'. That is simply not good enough and makes me look bad in front of my cycle friends.

So please add a warning when going of track. See this screenshot of one of the junctions where we just went straight ahead:
![screenshot_20180819-200306](https://user-images.githubusercontent.com/11628099/44323582-da354d80-a452-11e8-86c2-728db1a97f0c.png)
:

**Comment by doctor-beat** [comment]
"many features in GPX are missing by nature of data." => being off track has nothing to do with 'missing data', imho.

**Comment by vshcherb** [comment]
> "many features in GPX are missing by nature of data." => being off track has nothing to do with 'missing data', imho.

You just referred to "Y-split" junctions which is missing but that's another issue I agree

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/commit/6c02e1caa116554d3e736effcaf70710761e7725

**Comment by gammeredith** [comment]
This thread has been closed without solving the original issue.

_Route recalculations will never consider a u-turn when someone has missed their turn. This is a particular  problem when cycling or walking and using turn by turn instructions.__

Could someone from Osmand please indicate why there is such an aversion to an off route alarm.
