### ISSUE TITLE
android oneplus5 osmand crash if i have load many local map

### ISSUE THREAD

**Issue by ryzenX** [osmandapp/Osmand#4327]
Hello, i use android version 2.7.5 (last version) in oneplus5.

I  insert to my phone french state and gps work perfectly.
But i want to insert in my phone all Europe state map in local. I insert my local maps in my phone (size of all map 40gb), omsand have update database but when i navigate in the map  (and dezoom map), omsand is very unstable and crash and close the application.

**Comment by pebogufi** [comment]
The government of France made a reorganisation of regions, so the maps were all reorganized. The older maps have different names and have to be *deleted manually* !
Delete all maps (*.obf) and wiki files of france which are older than 2017-07-01.

If you have duplicates (old and new) in maps or wiki you will have a lot of "surprising" effects.
Peter

**Comment by ryzenX** [comment]
ok, I will update all my Europe maps and I'll keep you informed

**Comment by vshcherb** [comment]
Do you consider to make them archived? They will be present but the search & map browsing will work faster. You can always activate when you need them offline.
