### ISSUE TITLE
Coutour lines on F-Droid?

### ISSUE THREAD

**Issue by 2Belette** [osmandapp/Osmand#4329]
I am trying to get Coutour lines plugin and I only have F-Droid store (no Play Store on my phone) and it is like it is missing on F-Droid and tries to get it from Play Store.

Any idea on how to get Contour lines without Play Store? or from F-Droid?

Thanks

**Comment by Zahnstocher** [comment]
APKs signed with MD5 signature have been archived:
https://forum.f-droid.org/t/many-old-unmaintained-apps-have-been-archived/670
If you take the APK download link and replace /repo/ with /archive/, you can still download them.

**Comment by 2Belette** [comment]
thanks for your reply, I don't see it, what is the address location to use ?
In archive means that there is no more update on it?
many thanks

**Comment by TimMagee** [comment]
Osmand and its plugins are not officially published on F-Droid. If you have a problem with the F-Droid version, file a bug report over at F-Droid, not here.
