### ISSUE TITLE
Parks overlapping water

### ISSUE THREAD

**Issue by DFyson** [osmandapp/Osmand#4335]
I've noticed a few places where parks (leisure=park) overlap water. For example Copp park in Ottawa ([45.45204,-75.66993](http://www.openstreetmap.org/#map=17/45.45204/-75.66993)), and Wasaga Beach Provincial Park ([44.5100,-80.0481](http://www.openstreetmap.org/#map=12/44.5100/-80.0481)). This has been in OsmAnd for awhile now.

**Comment by xmd5a2** [comment]
Already fixed
