### ISSUE TITLE
Unnecessary "keep left" announcements in routing

### ISSUE THREAD

**Issue by Aiurek** [osmandapp/Osmand#4336]
OsmAnd+ 2.7.5, released 2017-08-08
Samsung GT-I8190 running Andorid 4.1.2

The navigation sometimes tells you to keep left when you are driving on a perfectly straight highway=trunk and there's a highway=tertiary road to the right. I felt it pretty confusing when i got these "keep left" announces, although the main road I was driving on was straight and the tertiary road to the right was perpendicular to it.
It actually happens quit often and I wonder if it's an issue of OSM mapping or the recognition of intersections (road types, inclination between roads, etc.) by OsmAnd-Navigation. Is it possible to avoid these unnecessary announcements/notifications by slightly changing the recognition of turns by the routing engine or is it solely a problem of OSM mapping?

Here are 2 examples with OSM-link:

![bild2](https://user-images.githubusercontent.com/27865200/29716679-8da8a398-89ac-11e7-8727-6d441ff72e93.jpg)

https://www.openstreetmap.org/node/5027186909 ---- https://www.openstreetmap.org/node/2870171089

**Comment by naoliv** [comment]
I guess that the OSM data could be improved.
I would map it like this
![](https://user-images.githubusercontent.com/982338/29741096-73116ec6-8a3c-11e7-9a27-9f4c0691d8d6.png)

instead this, for example:
![](https://user-images.githubusercontent.com/982338/29741097-77ba7422-8a3c-11e7-8ad4-a9a01c4bef52.png)

Maybe the `highway=tertiary` like https://www.openstreetmap.org/way/60205660 should be `highway=trunk_link`?

Use `turn:lanes` https://wiki.openstreetmap.org/wiki/Key:turn#Turning_indications_per_lane too?

**Comment by kayb94** [comment]
I personally would consider "Stay straight" (or how ever to best say this in english) a useful instruction at that point.

**Comment by Aiurek** [comment]
@naoliv Your suggestion to use trunk linke instead of tertiary might definately fix this. Can't test it personally though, since I've no OSM Live subscription :/
But we couldn't use trunk link for the other shown example (https://www.openstreetmap.org/node/5027186909), right?
Besides highway=tertiary I've experienced the same announcments for highway=residential, crossing the highway=trunk.
Overall it seems like there are a lot of different ways such highways and the connectiong streets are mapped in OSM --> It would take a lot of mapping effort to fix it properly in order to achieve a smooth OsmAnd-Routing
Is there any way to change the way OsmAnd detects such "keep left" situations to avoid unnecessary announcements in situation where the relevant street is perpendicular to the street your traveling on?

**Comment by bitboy85** [comment]
i also know a few places where this happens and there is no standard how to map those exits. Both versions shown by naoliv seems to be quite common, there is also a third version using lane tags (http://wiki.openstreetmap.org/wiki/Key:turn#Turning_indications_per_lane motorway example at the bottom). I don't think that remapping is a good solution because this might break another routing software and their users will start to remap too...

**Comment by vshcherb** [comment]
if the roads are not connected via link, there will be a prompt which is good in many situations. Turn curve in general couldn't help to detect priority of announcement.
So if it should be ignored it should have an intermediate way like trunk_link. 

I think according to the map data indication is fine.
