### ISSUE TITLE
Water-like background for certain map positions

### ISSUE THREAD

**Issue by Aiurek** [osmandapp/Osmand#4337]
OsmAnd+ 2.7.5, released 2017-08-08
Samsung GT-I8190 running Andorid 4.1.2

Got a odd water like background for several map positions in the "Spain Valencian Community"-map, e.g.  at the following position:
https://www.openstreetmap.org/#map=16/38.9621/-0.1956
Seems to be somehow dependend on the actual map position, since it disappears when panning to the left (re-appears when panning to the right). I've seen this issue on multiple devices including android and iOS-systems.

![bild3](https://user-images.githubusercontent.com/27865200/29717214-a0a267ac-89ae-11e7-8b6f-a1250c740503.jpg)

**Comment by dawagner** [comment]
I've noticed a similar issue on an island near Lake Baikal: https://www.openstreetmap.org/#map=10/53.1851/107.1030
