### ISSUE TITLE
Contour lines out of position

### ISSUE THREAD

**Issue by Aiurek** [osmandapp/Osmand#4338]
OsmAnd+ 2.7.5, released 2017-08-08
Samsung GT-I8190 running Andorid 4.1.2

Recognized a pretty odd looking positioning of contour lines for "Spain Valencian Community". The contour lines do not follow the coast line, but they even are illustrated far from the coast in the water area. Is it just a map issue or a global contour line issue? Haven't realized this so far, but it's indeed harder to spot countryside if the contour lines are out of position. Experienced the same issue for iOS-devices.

![bild4](https://user-images.githubusercontent.com/27865200/29717922-4bfa9df2-89b1-11e7-8fa4-3c45b12d1d1a.jpg)

**Comment by sonora** [comment]
I actually think it is a resolution issue, part of it already in the original SRTM data, and then likely some contribution caused by our post processing and compression. Not sure much should be done about it.

**Comment by xmd5a2** [comment]
It's a resolution issue. We can't do anything with that unless more detailed elevation data is opened to public use.
