### ISSUE TITLE
Waypoints not taken into account using YOURS routing

### ISSUE THREAD

**Issue by dawagner** [osmandapp/Osmand#4340]
Using Osmand+ 2.7.5.
Using the YOURS routing for pedestrian, car or bicycle; witnessed with a short route and a longer route.

Trying to get a route between two points and through a waypoint, the calculated route does not pass through that waypoint.

**Comment by stephan75** [comment]
Are you aware that the YOURS routing database that I assume is used from http://yournavigation.org is OUTDATED for many years already??

**Comment by dawagner** [comment]
No, I wasn't; thanks for pointing that out.

In that case, does it make sense to offer it as an option for routing? Unfortunately, the OSRM API seems down right now so there's only the offline routing available.

**Comment by vshcherb** [comment]
Looks like it is not going to be used.
