### ISSUE TITLE
osmand 2.6.5 d'nt update on 2.7.5. F-droid

### ISSUE THREAD

**Issue by SergeyDjam** [osmandapp/Osmand#4342]
1. update in f-droid v2.6.5 on v2.7.5
2. download and start install
3. d'nt install, and unknown error. 

![screenshot_2017-08-26-19-56-11](https://user-images.githubusercontent.com/11427162/29743413-4066f564-8a9a-11e7-9c78-814e7091ae6c.jpg)

ASUS Zenfone T00I, Android 5.0, build number LRX21V.WW_ZenFone-V7.4.4-20150831, Kernel 3.10.20-i386_ctp-00001-g00e7e8b

**Comment by sonora** [comment]
F-Droid issue, not ours.

**Comment by SergeyDjam** [comment]
At a system installer too problem?
I downloaded a packet of apk and installed its standard means Android, but also here an error

![screenshot_2017-08-27-13-24-30](https://user-images.githubusercontent.com/11427162/29749041-054aeb74-8b2c-11e7-83dc-5c179bcb3b9c.jpg)

**Comment by sonora** [comment]
Are you updating from "new to old", i.e. from 2.7.5 to 2.6.5? Android will in general not perform any update from a newer APK number to an older one, without prior uninstallation (remember to rename your data folder before any uninstallation or you will lose all data and maps.).

But if you are updating "from old to new", you are likely experiencing signature issues: Chances are you are trying to update an older build with  new one signed differently. If both came from F-Droid, please raise a ticket with them. If you mixed sources for the apk yourself, you need to uninstall the old one first, see above.

**Comment by SergeyDjam** [comment]
I update "from old to new", with 2.6.5 on 2.7.5. I use one source. And if the problem was with the signature, then the installer will report about it. However the installer reports only about an unknown problem. 
This problem only with osmand.

**Comment by sonora** [comment]
Ok, as I said, I cannot reproduce it so I suspect this may be an issue with F-Droid only.

**Comment by TimMagee** [comment]
I got an error the first time I tried to upgrade on F-Droid. Then it worked it fine. I believe it is an F-Droid issue but it worked fine for me.
