### ISSUE TITLE
Some Road Segments not displayed at certain zoom levels

### ISSUE THREAD

**Issue by Urmel** [osmandapp/Osmand#4343]
Hi there!

I seem to have found a bug in this great software: I've come across two road segments that are not shown on certain zoom levels using the "Germany Brandenburg" default offline map.

Version etc:
* OsmAnd+ v2.7.5
* Android v 6.0.1 on Samsung S5 mini
* Offline map "Germany Brandenburg", standard version 1st of August, 2017

**Example 1**

On the OSM website, we see this:
![example_1-website](https://user-images.githubusercontent.com/1786902/29745766-9cb3725a-8ac4-11e7-9d51-3c4c9c46a54e.JPG)
and on my Smartphone, I'm missing out on a road segment:
![example_1](https://user-images.githubusercontent.com/1786902/29745755-1442dd3e-8ac4-11e7-9420-5c4d2db5a6b8.JPG)

**Example 2**

Similar situation here - on the OSM site:
![example_2-website](https://user-images.githubusercontent.com/1786902/29745776-cc207402-8ac4-11e7-9f7c-4ccd0a00aa0b.JPG)
And on the smartphone:
![example_2](https://user-images.githubusercontent.com/1786902/29745757-1aec55e8-8ac4-11e7-8d82-adb472c5e43d.JPG)

In any case: Thanks. I love the product!

Cheerio
Urmel

**Comment by aceman444** [comment]
So parts of the yellow (secondary?) road are missing in OsmAnd display. Do those parts differ from the others in any tags?

**Comment by Urmel** [comment]
Correct - some yellow ones.

I've looked at them in Potlatch, but could not find any difference in attributes. But I'm not an expert.
Did you mean that'

**Comment by xmd5a2** [comment]
Observation: road segments disappear at zoom level 12. Increasing roadsDensityLimitPerTile doesn't help to resolve issue.

**Comment by vshcherb** [comment]
![screenshot_20171003-103017](https://user-images.githubusercontent.com/1042025/31116320-f0a3454c-a825-11e7-9f92-29095b97e848.png)
![screenshot_20171003-102958](https://user-images.githubusercontent.com/1042025/31116321-f0a44aaa-a825-11e7-8488-9af56d3e37f9.png)
Fixed with latest (map data has changed?)
