### ISSUE TITLE
Illegible rendering of ferry

### ISSUE THREAD

**Issue by gjedeer** [osmandapp/Osmand#4344]
I think the picture speaks for itself:

![osmand](https://user-images.githubusercontent.com/315648/29748210-c3af5ec6-8b11-11e7-877d-4d292c96b799.jpg)

It seems to overlay "przeprawa promowa karsibor" (Karsibor ferry service) and "pl:national", whatever this is supposed to mean. National road, perhaps.

LineageOS 14.1, OsmAnd~ 2.7.5. 
Map type: offline
Map style: OsmAnd
Display language: System (English)
Map language: Local names
Map file: Poland @ Jul 1, 2017
Place:
geo:53.863037,14.280828?z=15
https://osmand.net/go?lat=53.863037&lon=14.280828&z=15

Higher zoom levels also result in illegible text. Zoom 16 overlays the text "93" (road number).

OSM metadata:
![selection_081](https://user-images.githubusercontent.com/315648/29748228-345d9e6c-8b12-11e7-945c-9188b2d49634.png)

**Comment by xmd5a2** [comment]
Ferry names fixed https://github.com/osmandapp/OsmAnd-resources/commit/c11a5cde56ddecb2abb72e5f4e8b062668abe643

**Comment by gjedeer** [comment]
Thank you @xmd5a2
