### ISSUE TITLE
"Add to GPX track" does not take into account existing GPX content

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#4351]
In new measure distance tool "Add to GPX track" option by default writes rtept even if GPX contains only trkpt. Such tracks can't be properly rendered by OsmAnd.

**Comment by PavelRatushnyi** [comment]
Fixed by https://github.com/osmandapp/Osmand/commit/348148cf2302a08d04b05cdeaf916fb42ff64809
