### ISSUE TITLE
Nautical Charts and Depth Contours incorrect data

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4353]
Attached are several screenshots showing the nautical contours 
passing over islands in Croatia and one instance where the 10m depth 
contour is shown next to a 51m spot height.

![screenshot_20170820-094812](https://user-images.githubusercontent.com/20681525/29810632-38f6124a-8ca9-11e7-83e6-25a37a3c4bf6.png)
![screenshot_20170820-094901](https://user-images.githubusercontent.com/20681525/29810634-38fd8c8c-8ca9-11e7-81a8-86720ee9694a.png)
![screenshot_20170820-094944](https://user-images.githubusercontent.com/20681525/29810635-39017a22-8ca9-11e7-8bca-f9089826f85a.png)
![screenshot_20170820-095009](https://user-images.githubusercontent.com/20681525/29810633-38fd2814-8ca9-11e7-8ab0-1fe15e2ca224.png)

**Comment by xmd5a2** [comment]
Obviously this is due to low source raster resolution. We are adding more detailed depth maps when they are ready.
