### ISSUE TITLE
Feature Request: Adjustable Leadtime before audio routing announce / Bluetooth output

### ISSUE THREAD

**Issue by connaisseur** [osmandapp/Osmand#4354]
Team,

as I'm hard of hearing I'd like to use a Bluetooth (BLE) transmitter for routing announcements. [http://www.resound.com/hearing-aids/accessories/phoneclip-plus](url)

The above device needs some lead time to wake up from sleep and connect to the hearing aids.

Would it be possible to create a means for adding an adjustable lead time before doing any audio output? Especially over Bluetooth,

This would be much appreciated!

Thanks for considering.

**Comment by sonora** [comment]
Can you please test the following, I think we already have what you are looking for:

1. Under Navigation settings / Voice guidance output, select Phone call audio
2. Enable the Development plugin
3. In its settings, go to Test voice prompts, and use my button 11.2 to page through different values.

I think this may achieve exactly what you are looking for?

**Comment by connaisseur** [comment]
Thanks for that excellent tip! Never looked around in the development plugin.

I was able to follow up your given steps to change the delay setting.

_Note to whom it may concern_: You have to change all routing types (car, pedestrian, bicycle) to "_phone call audio_" to get the above hint working.

The delay chosen to work was 2500 ms. This works out fine in my setup.
