### ISSUE TITLE
Not possible to hide house numbers

### ISSUE THREAD

**Issue by Aiurek** [osmandapp/Osmand#4372]
OsmAnd+ 2.7.5, released 2017-08-08

After selecting "Hide > House numbers" the house numbers are still illustrated. Seen it on multiple devices.

![grafik](https://user-images.githubusercontent.com/27865200/29927103-a22c211a-8e65-11e7-9c5a-952a91e438aa.png)

**Comment by Aiurek** [comment]
@xmd5a2 Could you fix it or did you just close the issue since it's not a relevant issue? I figured out that the setting actually hide house numbers that are modeled as single points in OSM, but doesn't hide the house numbers which are assigned to buildings or POIs :-/ It would be great if one could hide all the house numbers (in case he/she only needs to display the house numbers occasionally).

**Comment by xmd5a2** [comment]
@Aiurek it is fixed

**Comment by Aiurek** [comment]
@xmd5a2 Thank you! :)
