### ISSUE TITLE
Map doesn't render after certain zoom level

### ISSUE THREAD

**Issue by kayb94** [osmandapp/Osmand#4375]
I currently have installed version 2.7.5 and I believe the following did not happen in version 2.5.4. Sadly I somehow can't install older versions to verify this.
I'm using Lineage OS 7.1.1 on a Samsung S4 mini.

When I zoom out two times (hit the minus button two times), no map is ever rendered (blank). When zooming in again, the map is rendered.
The shown scale is the second one of 2km (more far out), in case this is screen size independent.

All my maps are up to date.

**Comment by scaidermern** [comment]
Sounds like the world basemap is not installed. Try (re)installing it.

**Comment by sonora** [comment]
Yes, go to Menu/Download maps and install the world basemap, it contains the global map data for overview zoom levels,

**Comment by kayb94** [comment]
Thanks for the support!
