### ISSUE TITLE
[Feature request] Favorites: Allow display of places by category

### ISSUE THREAD

**Issue by thinking-aloud** [osmandapp/Osmand#4377]
I have different categories for my favorites (my places). When I for example go out taking pictures I only care about my photo spots, so I would like to be able to hide my other categories.

**Comment by pebogufi** [comment]
Use the three dots menu in poi category, then switch off "Show on map".
Peter

**Comment by thinking-aloud** [comment]
Now I feel stupid ... thx

**Comment by pebogufi** [comment]
Sometimes it is too easy to see it.
Peter
