### ISSUE TITLE
[Request] Support for the network tag in POI

### ISSUE THREAD

**Issue by franco999** [osmandapp/Osmand#4381]
They could add support in OsmAnd for the label ``network=*`` to ``amenity=atm|bank|bicycle_rental + network=*`` and similar?. This would serve to look, for example, _"all nearby ATMs belonging to a specific network"_. In Argentina this is very useful.

**Comment by franco999** [comment]
Thanks!

**Comment by franco999** [comment]
@xmd5a2 I downloaded a version nightly updated with this change but I can't see the network string in PDIs or in the search filter. Has this been fully implemented already?

**Comment by xmd5a2** [comment]
@franco999 these tags should be in October maps.
