### ISSUE TITLE
Remaining issue with Measurement tool

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#4385]
- Start a longer route calculation (need not be in Follow mode)
- Now (while this route calculation is ongoing) start the Measurement tool, select a few points, then select its "Snap to road" option
- Then exit the tool via its x button. The tool will not disappear, somehow the situation is hung with the concurrent route calculation processes, it seems

**Comment by vshcherb** [comment]
Start a longer route calculation (need not be in Follow mode)
Now (while this route calculation is ongoing) start the Measurement tool, select a few points, then select its "Snap to road" option
Then exit the tool via its x button. The tool will not disappear, somehow the situation is hung with the concurrent route calculation processes, it seems

**Comment by AlexSyt** [comment]
Fixed with 1decb4e9fd0daa655ae7788e053fafa628425bd0
