### ISSUE TITLE
maxspeed:practical vs maxspeed - clarification

### ISSUE THREAD

**Issue by RicoZ-OSM** [osmandapp/Osmand#4392]
Hi,

there was a recent thread about it in OSM-talk and the question did arise what happens when maxspeed:practical > maxspeed . Does the router use maxspeed:practical even in this case? It may make sense in some special situations but  also cause trouble in many other situations. Perhaps it should be a personal preference what the router does in this case?

The old (and rejected proposal) did encourage maxspeed:practical > maxspeed (legal), the current description no longer mentions this explicitly and I would like to clarify the description in some way that is compatible with OsmAnd.

**Comment by scaidermern** [comment]
Why should OsmAnd encourage users to break the law? This sounds horribly wrong.

The only preference I would like to see is to reduce the expected speed if maxspeed:practical < maxspeed. This is mostly the case for very bendy roads or when having a poor surface.

**Comment by vshcherb** [comment]
maxspeed:practical is used by OsmAnd and it takes precedence over maxspeed. Though we should disallow maxspeed:practical > maxspeed
