### ISSUE TITLE
Allow for disabling route recalculation

### ISSUE THREAD

**Issue by tilusnet** [osmandapp/OsmAnd#4393]
It is often the case that a route is 'agreed upon' and it should not change during navigation.
In order to stick to it there should be an option (switch) for disabling route recalculation.

**Comment by sonora** [comment]
Unusual request, at first sight ... :)

But let's explore it: I am always very strictly opposing new settings, switches, or options which can be avoided by what I call "intelligent simplification", i.e. without creating the need for human choice or intervention.

And here I guess you have (as have I) experienced route-recalculations while following a route which on the fly produced sub-optimum routes, without the "justified" need for a new route, i.e. without having left the previous route? If that is your underlying issue, I suggest we first try to fix why that happens sometimes, only consider a new setting if we cannot fix that?.

**Comment by tilusnet** [comment]
Thanks for the reply and I appreciate your take on the matter.

Automatic route recalculations will rarely (if ever!) consider a u-turn when someone missed their turn. This is in particular a problem when cycling or walking.
Second scenario is when navigation is done by someone less good with orientation: they need a solid guide that "sticks with the route". Otherwise the "infinite loop disaster" may happen by which they start navigating in circles ─ something I witnessed not long time ago.

**Comment by sonora** [comment]
Yes, both issues need to be addressed.
- The first one is actually #4326, I think, and must be solved.
- The second one could be called "Make the route stickier", and probably needs to first be explored a bit better, under what circumstances what happens that should generally be avoided. So any examples or better descriptions would be good to try to reproduce it.

**Comment by tilusnet** [comment]
Thanks for the update. I am keeping an eye on #4326 from now on.

As for the second issue, I think it is fundamentally a matter of user decision whether route recalculation would be a problem or not, and therefore should be allowed or not. Taking you suggestion by making the route "stickier" (by means of parameter tuning I assume) does not solve the problem as it would only lessen the chance for route recalculation.
Thinking further, a "no recalculation routing" could deserve its own navigation mode by which the app would also warn the user that they are deviating from the original "locked" route.
What do you think? 
If you are -- totally understandably -- wary of additional Navigation switches, could this switch live under the OsmAnd Development plugin?

**Comment by sonora** [comment]
Still wondering here if there is a true, generally useful use case where you would like to suppress route-re-calculation unconditionally, no matter what.

And if there is, how is it different from simply using a GPX file (e.g. the "sightseeing tour" you want to take"), select to route by it, and then  OsmAnd would always guide you back to that GPX track for further use should you deviate from it.

Maybe that is simply what you try to achieve, and it can already be done like this, maybe needs some usability improvements...?

**Comment by tilusnet** [comment]
Indeed, I could use the route as I would a GPX file, however, I would have to generate a GPX file on a computer, import into OsmAnd, etc.
Isn't it much simpler to disable route recalculation on an OsmAnd route and achieve the same effect?
Alternatively, adding a bridge as you suggest, i.e. "export OsmAnd route to GPX"?

**Comment by scaidermern** [comment]
You can calculate the route with OsmAnd and then directly save the result as a GPX file. No computer involved.

- Calculate the route, tap on the routing button to open the routing menu
- Tap on the distance / time information at the bottom (this step isn't very obvious!)
- a new view appears, tap on the save icon on the top right to save as GPX

**Comment by tilusnet** [comment]
Oh wow. I would have never guessed that there is more under the time/distance line.
I think there is UX work to be done there.

In any case this tip is sufficient for my woes. Thanks!
Feel free to close this ticket now.

**Comment by scaidermern** [comment]
> Oh wow. I would have never guessed that there is more under the time/distance line.

Yes, unfortunately these pretty useful route statistics are hidden very well. They should be made more visible. Not sure how to do that, though.

**Comment by tilusnet** [comment]
I'm sure Android UX experts will know how. :-)

**Comment by vshcherb** [comment]
I agree that saving route as a GPX track should be much better cause it is exactly what preplaned route is.

**Comment by gammeredith** [comment]
_"Automatic route recalculations will rarely (if ever!) consider a u-turn when someone missed their turn. This is in particular a problem when cycling or walking"._

**This has caused major issues for me when cycle touring. If a turning has been missed I need to know ASAP.**

**Comment by dmpr0** [comment]
The option is already added, it can be found in Menu – Settings – Profile – Navigation settings – Route parameters – Minimal distance to recalculate the route
