### ISSUE TITLE
Offline use on another device

### ISSUE THREAD

**Issue by Extarys** [osmandapp/Osmand#4395]
Hey!

I didn't know where else to ask this.

I'm trying the OSMAnd~ version and I love it - bought the contour plugin and I love it.

Now, I have a small tablet with nothing on it (not even google stuff) and I would like (and I need) to be able to have offline maps on it.

Could I download all contours of North America on a SD Card and plug it into my other tablet?
I already downloaded all OBF of NA and its great although it doesn't show as installed so on my main tablet I won't see if there is update available.

I need this for hicking and little summer adventures and it would be an awesome asset to have.

I wouldn't mind paying for the full version to encourage dev if there is a way to transfer data on sd card.

Thanks guys!! <3

**Comment by njohnston** [comment]
If you configured OsmAnd to store its data on an SD card on your main tablet, copy the contours off the SD card onto your computer temporarily. You can use either Windows Explorer or adb for this. The files are in Android/data/net.osmand.plus/files/srtm/ (or maybe Android/data/net.osmand/files/srtm/ depending on what version of OsmAnd you have) on your SD card.

Make sure OsmAnd on your small tablet is configured to use the SD card too. Copy the contour files to the corresponding directory there.

**Comment by sonora** [comment]
Yes, it is perfectly possible as described. If you have any issues, please PM me. You will also be able to see which maps can be updated. The only thing you will not be notified about with an installation outside google Play is available upgrades for the app itself.

**Comment by Extarys** [comment]
Awesome! :D Thank you so much :)
Is there a way to download batch files? I found [thoses indexes](http://download.osmand.net/indexes.php) but I cannot guess the download url.

Thanks again!! <3

**Comment by sonora** [comment]
Cannot say off hand. I can only recommend the standard way of downloading, in the app go to Download maps, then use the tabs there for new downloads or to identify updates. About mirrors: I do not think we have a bandwidth issue, but you can open a new issue for that to get it commented by Victor.

**Comment by Extarys** [comment]
Thanks - then would it be possible in private to get the direct download link? would be much faster for my offline tablet than downloading everything manually :)

For the bandwidth - if you have no problem I won't bother.

Thanks for your help!

(Could I open another ticket for questions about layer, etc even if it's not an OSMand issue?)

**Comment by vshcherb** [comment]
There is not much bandwith issue at least for couple of people it is fully affordable. We have now around 30% capacity free especially during European night. If you find a link where you can download maps directly, please do it. Though please don't do it on a regular basis.

**Comment by Extarys** [comment]
Thanks - No it's for "fun" I downloaded everything on my sd card - I love maps.

Unfortunately, on my phone with internet, manually downloaded maps aren't "detected" by the package, but are shown on the map, quite sad since I won't get notified of updates and downloading everything I want would tike hours manually clicking on all those little arrows inside the app.

But I guess it's better than nothing.

**Comment by sonora** [comment]
Not sure why you say they are 'not detected'. You must be making some mistake I do not capture here. Either you do not unzip the package you manually downloaded (file extension needs to be .obf), or you put them in the wrong folder, or you write-protect them, or you use a wrong naming, or whatever. I recommend downloading one from inside the app, then use some sort of file manager to compare and detect how that one differs from one you placed manually. In the end, if you do it right, the app should treat both equally.

**Comment by Extarys** [comment]
Ok thanks I'll investigate this :)
