### ISSUE TITLE
Allow to type the address the "natural way" e.g. 123 Example Street

### ISSUE THREAD

**Issue by TimMagee** [osmandapp/Osmand#4402]
Currently when I copy paste an address into the OsmAnd search field, OsmAnd returns nothing useful. I propose that we make it search for the address entered. 
For example: if I type 123 Example Street, OsmAnd would search for a street called Example Street with a 123 housenumber on it rather than assuming a coordinates search and saying "Nothing found :("

**Comment by scaidermern** [comment]
Just a note: The "natural way" differs from country to country. Having the house numbers before the street name doesn't feel very natural to me. Address systems are complicated.

**Comment by vshcherb** [comment]
This was fixed in 2.7.5.

**Comment by TimMagee** [comment]
Awesome. Thank you and now I'm on 2.7.5!
