### ISSUE TITLE
OSM Live doesn't support POI updates

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#4408]
Seems like at least amenity=parking, amenity=bicycle_parking and highway=service aren't updated by OSM Live.

Examples: Sachsen, Germany (as of writing this post) at https://osmand.net/go?lat=50.99719&lon=14.229099&z=20 and https://osmand.net/go?lat=51.069706&lon=13.753235&z=20

Are there specific tags excluded from live updates or is this a bug?

**Comment by vshcherb** [comment]
Nope . Please help us to find specific obf file which is prepared for update here http://builder.osmand.net/osmlive/.

For example 
http://builder.osmand.net/osmlive/germany_sachsen_europe/Germany_sachsen_europe_17_09_04.obf.gz
http://builder.osmand.net/osmlive/germany_sachsen_europe/17_09_04/Germany_sachsen_europe_12_30.obf.gz (for the specific time)

The files could be checked with inspector tool from OsmAndMapcreator to confirm whether data is generated.

**Comment by vshcherb** [comment]
Please mind that we still dealing with "deleting" POI data issues. All other issues were recently fixed, so we should investigate this case in detail.

**Comment by scaidermern** [comment]
Not sure how to check them with OsmAndMapcreator. However I will provide more details.

For the first link I mentioned at least the following changesets are involved: https://www.openstreetmap.org/changeset/51681382 + https://www.openstreetmap.org/changeset/51702968
At this position a parking area is missing in the map (https://www.openstreetmap.org/way/520831283) as well as a service area (https://www.openstreetmap.org/way/521099679).

For the second link this changeset is involved: https://www.openstreetmap.org/changeset/51534792#map=16/51.0726/13.7446
At this position a bicycle parking is missing (node https://www.openstreetmap.org/node/5066002601), a parking area (https://www.openstreetmap.org/way/32966211) as well as service roads (updated: https://www.openstreetmap.org/way/235968041, newly added: https://www.openstreetmap.org/way/519569300).

I hope this helps to track down the cause of this issue.

**Comment by scaidermern** [comment]
I've found another bicycle parking added 18 days ago and still missing in the map: https://www.openstreetmap.org/node/5044347900

**Comment by vshcherb** [comment]
The new scheme has started since 1 September so previous changes may be related to old algorithm. Though we will check at which stage the checks failed.

**Comment by scaidermern** [comment]
Looks like this issue persists.

I made some changes yesterday: https://www.openstreetmap.org/changeset/51818633

I updated the map via OSM Live. The newly added fire hydrants show up in the map. I also added the covered=no tag to these bicycle parkings: https://www.openstreetmap.org/node/3556894671 and https://www.openstreetmap.org/node/1488272071. The newly added covered tag does _not_ get displayed by OsmAnd (while for other bicycle parkings OsmAnd displays whether they are covered or not, if this tag is present).

OSM Live says the last map change is from 08:15 and the last update from 08:37 (both times in UTC).

**Comment by xmd5a2** [comment]
I did a quick check: downloaded full map and live updates.
![screenshot_2017-09-08-12-22-36](https://user-images.githubusercontent.com/5829014/30205380-4953b1c0-9491-11e7-9a90-de969027f48e.png)
As you can see, "Covered: no" is here (look at 4th icon)

**Comment by scaidermern** [comment]
It isn't for me. How can we debug this issue?

What I just noticed: My `live` directory only contains Germany_sachsen_europe_17_09_00.obf, Germany_sachsen_europe_17_09_07.obf and Germany_sachsen_europe_17_09_08.obf. So 01-06 are missing. Could this be the reason? If so, why are these missing and won't get downloaded even if I manually hit 'update' from the OSM Live menu?

**Comment by vshcherb** [comment]
Unfortunately we can test only the files since september update cause we don't have historical files any more. 
Also the process completely changed since 1 September, please try to redownload full map & find another example. It would be very valuable to check if new process OSM diff is working better

**Comment by scaidermern** [comment]
These files are all from September. I didn't have OSM Live in August. However I will try re-downloading the base map and diffs when I'm back at home.

**Comment by vshcherb** [comment]
Your base files should be from September as well

**Comment by scaidermern** [comment]
> Your base files should be from September as well

Sure, they are.

I deleted everything from the live directory and redownloaded the base map for Saxony. The newly added fire hydrants didn't show up, as expected. Then I went to OSM Live -> Saxony -> three dot menu -> Update now. OsmAnd downloaded something in the background and now I have a 134 KB large Germany_sachsen_europe_17_09_08.obf file in the live directory which is the same as http://builder.osmand.net/osmlive/germany_sachsen_europe/Germany_sachsen_europe_17_09_08.obf.gz (uncompressed). Afterwards the newly added fire hydrants show up. But the covered tag on the bicycle parkings still don't. The same as before.

Am I doing something wrong here? I would expect OsmAnd to download all obf files for this region, not just the one for today. This seems wrong.

**Comment by scaidermern** [comment]
Now I got the updated map after switching from "daily" to "hourly" updates and restarting OsmAnd.

Could it be that the daily update mechanism is broken?

**Comment by vshcherb** [comment]
The poi are quite unstable, we detected couple of issues & fixing now. Map & routing should be fine.

**Comment by scaidermern** [comment]
Its not the POIs fault. OsmAnd isn't downloading Germany_sachsen_europe_17_09_00.obf.gz if daily updates are enabled. Only if set to hourly.

**Comment by scaidermern** [comment]
Another similar problem. I've updated the collection times of a post box (https://www.openstreetmap.org/changeset/51904290). This change is missing in the map, OsmAnd still displays the old collection times (17:00) instead of the new ones (16:30). _Afterwards_ I added several bicycle parkings ( https://www.openstreetmap.org/changeset/51918601). These changes _are_ included in the map.

Maybe this has something to do with updated vs. newly created POIs?

**Comment by scaidermern** [comment]
I can reproduce the missing update for the postbox collection times on two different devices.

Please tell me why this issue has been closed. There are several problems left. Closing issues of a subscription feature without fixing them isn't really nice and might make people think about canceling their subscription.

**Comment by vshcherb** [comment]
collection_times | Mo-Fr 16:30 is POI information. So yes it is POI and we are testing it.

**Comment by scaidermern** [comment]
Then please reopen this issue if you are aware of this bug. Or flag it as duplicate if this issue already exists elsewhere. Just closing it is clearly wrong.

**Comment by vshcherb** [comment]
WIP https://github.com/osmandapp/Osmand/pull/4418

**Comment by vshcherb** [comment]
Should be fixed now. Today requires nightly build (2.8 release) & september maps.

**Comment by scaidermern** [comment]
Great!

**Comment by tico-tico** [comment]
Are live uptades still borked? Changing *opening_hours* is ignored. Please take a look https://www.openstreetmap.org/node/1755019464 .
I have 1st May's map **Russia_yaroslavl_asia.obf** and an update **Russia_yaroslavl_asia_18_05_00.obf**.
