### ISSUE TITLE
Something went completely wrong with arrows

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#4415]
![screenshot_20170907-190419](https://user-images.githubusercontent.com/1042025/30213203-aef6ac3e-94b0-11e7-9d4d-6c668ccdcaba.png)

**Comment by xmd5a2** [comment]
Link to problematic way https://www.openstreetmap.org/way/231492896
turn:lanes=through|through|through|through|slight_right|slight_right

**Comment by CJTmmr** [comment]
I have seen this on many places, when a highway was changed after 1th of the month.
Related to Live Updates?
Next month with fresh map, everything was okay again.

**Comment by PaulStets** [comment]
Could not reproduce with OSM Live turned on/off.

![22279273_1923516167895188_1871386474_o](https://user-images.githubusercontent.com/20681525/31236643-5dbf2fa0-a9fd-11e7-9743-5684f93ebfca.png)

**Comment by vshcherb** [comment]
Is it possible to run simulate route to double check the issue?

**Comment by PaulStets** [comment]
The screenshot above was taken during the route simulation. I double-checked it now and was not able to reproduce the issue. The correct amount of lanes is displayed.
