### ISSUE TITLE
Hide topbar and widgets when context menu is open

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#4417]
Screenshot
![screenshot_20170909-145146](https://user-images.githubusercontent.com/1042025/30239916-bfe0aca2-956e-11e7-934f-750f2b589a4e.png)

**Comment by vshcherb** [comment]
The widgets & top panel should be hidden only in medium state of context menu.
The widgets should be hidden in bottom state, zoom in/out should be visible in the bottom state.

**Comment by PavelRatushnyi** [comment]
Fixed with https://github.com/osmandapp/Osmand/commit/a75978db5d4c1821eadb09a326b08ca992249164
