### ISSUE TITLE
Map being greyed out at particular zoom level

### ISSUE THREAD

**Issue by Nichtraucher** [osmandapp/Osmand#4419]
Hello there,

I believe I have the same or an issue that is similar to one that has been mentioned earlier: https://github.com/osmandapp/Osmand/issues/2648

At one point, zooming in (somewhere between zoom level 14-15) will result in a map that is almost entirely grey, with small fragments of streets displayed (see pics below).

I use Osmand+ 2.6.4 with Android 6.01 on a brand-new LeEco LeMax 2. I don't seem to have these problems when using "Topo" or "LightRS" as vector-renderer.
Using "safe mode" seems to help but I get "rendering error"-messages when zooming in. 

https://photos.app.goo.gl/ibplt95HkJUd8F9q2
https://photos.app.goo.gl/o7B4ReoKLUmVSBXu2

Any help is much appreciated. Let me know if you need further details.

cheers

**Comment by vshcherb** [comment]
It might be related to OSM Live data which could be cleared.

**Comment by sonora** [comment]
Just to rule out a simple file or SD card corruption, I suggest to delete all OSM Live data (if any), then refreshing the map from the server. Does this change anything?

**Comment by rlaggren** [comment]
Similar problem. In USA when I zoom to where the scale at the bottom of the screen reads somewhere (it varies) between 100m and 50ft, most usually at 200ft, the screen will go gray with only some "dust" (maybe 3 or 4 particles) from certain roads as well as the "Your Location" indicator remaining. Changing to SafeMode seems to correct the problem.

This is on a new Lenovo G5+ phone with Android 7.0 and OSM 2.75. I have never used online maps. After upgrading to OSM+ and dl'g new maps the problem did not occur until I adjusted a number of settings; however, I don't know if this directly relates or not. On seeing the problem, I tried changing many settings several times over but once the the rendering failed it stayed failed.

Thanks for you attention.

Rufus

**Comment by Adonai** [comment]
Have same issue on maps scaled to < 1km

**Comment by Adonai** [comment]
Disabling Mapillary (green marker lines) fixes the issue

**Comment by Nichtraucher** [comment]
> It might be related to OSM Live data which could be cleared.

I've never used Live data...

**Comment by sonora** [comment]
See here: https://github.com/osmandapp/Osmand/issues/4705#issuecomment-359165343. Is this your issue?

**Comment by Nichtraucher** [comment]
> See here: #4705 (comment). Is this your issue?

I'm not sure, where is the "Hide overground objects" option, that the other user mentioned? I'm using Osmand in german and can't find it. :-/

**Comment by scaidermern** [comment]
> where is the "Hide overground objects" option that the other user mentioned? I'm using Osmand in german and can't find it. :-/

Schau mal hier: Karte konfigurieren -> Ausblenden -> Oberirdische Objekte :)

**Comment by Nichtraucher** [comment]
> Schau mal hier: Karte konfigurieren -> Ausblenden -> Oberirdische Objekte :)

Bei mir finden sich unter "Ausblenden" Optionen wie "Flächen", "Wälder und Gebüsch", "Zufahrtsbeschränkungen etc. angegeben. "Oberirdische Objekte" als Option ist nicht aufgeführt

In english: I don't have this particular options but options like "Buildings", "House Numbers", "Text" etc.

(I have upgraded to 2.93 since my first post on the top. I believe that I still have this bug but am not sure. Hence my question).

**Comment by scaidermern** [comment]
> I have upgraded to 2.93 since my first post on the top

Why is your OsmAnd version so old? The current version is 3.1.

**Comment by Nichtraucher** [comment]
I updated to 3.1.5 but I'm still having these issues.

> Bei mir finden sich unter "Ausblenden" Optionen wie "Flächen", "Wälder und Gebüsch", "Zufahrtsbeschränkungen etc. angegeben. "Oberirdische Objekte" als Option ist nicht aufgeführt
> 
> In english: I don't have this particular options but options like "Buildings", "House Numbers", "Text" etc.

I believe that I didn't see this option as these are only being displayed if you're using LightRS, Topo e.g. If I use these and switch off "overground objects", I can zoom in without problems. 

I'd rather not give up the overground objects though :-/

**Comment by scaidermern** [comment]
> I believe that I didn't see this option as these are only being displayed if you're using LightRS, Topo

No, for me they are also displayed using the standard map style.

Not sure if this helps but try to delete the xml files in the rendering directory.
