### ISSUE TITLE
Add possibility to edit OSM notes that have not yet been uploaded

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#4423]
It would be nice to edit the text of newly created OSM notes that have not yet been uploaded. Sometimes you forget something important which you want to add to the notes' description.

Currently you have to either delete and add the note again. Or to upload it and add a new comment afterwards.

**Comment by PavelRatushnyi** [comment]
Fixed with https://github.com/osmandapp/Osmand/pull/4520
