### ISSUE TITLE
Feature request - Financial support available

### ISSUE THREAD

**Issue by Awermuller** [osmandapp/Osmand#4425]
Hi All,

First of all, I hope this isn't an inappropriate subject for this issue tracker. I've already tried asking directly to the support email address in the Osmand site, in Stackoverflow Osmand channels and in the Osmand Google mailing lists.

I work for a public transportation company, and we'd like a tool to show our drivers not only the route they need to follow, but also the deviation between the predefined times in the route versus the actual time.

I guess this might be possible by preloading timed GPX files, and in that case the feature request would be only show the deviation.

The company is willing to financially support the development of this and other features if it fits the budgetary restrictions.

Thanks for any help on this matter.

Best regards,
Awer

**Comment by vshcherb** [comment]
Hi Awer,

I think we contacted you by email. If you didn't receive email please let me know. 
Short answer: yes, we can do customization but it will be done by a special freelance team.

**Comment by Awermuller** [comment]
Hi vshcherb! I didn't receive your previous answer. Could you please let me
know the details via email to awermuller@gmail.com?

Thanks


El 11 sept. 2017 16:36, "vshcherb" <notifications@github.com> escribió:

Hi Awer,

I think we contacted you by email. If you didn't receive email please let
me know.
Short answer: yes, we can do customization but it will be done by a special
freelance team.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/osmandapp/Osmand/issues/4425#issuecomment-328635849>,
or mute the thread
