### ISSUE TITLE
Live updates not working after disabling and re-enabling

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#4427]
OsmAnd doesn't download live updates after disabling and re-enabling them again.

Steps to reproduce:

- Start OsmAnd with live updates disabled
- Enable live updates for one map (e.g. daily, morning) -> OsmAnd will download two files (e.g. Germany_sachsen_europe_17_01_00.obf.gz and Germany_sachsen_europe_17_01_11.obf.gz) to the live directory, as expected
- Disable live updates for this particular map again -> OsmAnd asks to clean the previously downloaded updates -> hit yes -> live directory is empty again, as expected
- Enable live updates for this map again -> OsmAnd is expected to download diff files again but actually does *nothing*
- Disable global live updates and reenable them again -> OsmAnd asks whether to update all maps -> hit yes -> OsmAnd still does *nothing*
- Open the three dot menu for the map -> select update now -> OsmAnd still does *nothing*

The live directory remains empty.

Reproducible on two different devices (Android 6.0.1 and 7.1.2).

After restarting OsmAnd and disabling and re-enabling global live updates it finally starts to download diffs again.

**Comment by PaulStets** [comment]
Fixed #4468
