### ISSUE TITLE
Unable to find interpolation addresses.

### ISSUE THREAD

**Issue by BalooUriza** [osmandapp/Osmand#4428]
Please give us the following information so that we can try to **reproduce** your issue:

Searches against locations using Karlsruhe address interpolation tagging does not locate any address except the endpoint of the interpolation.  Tested against addresses 4100-7101 on South Yale Avenue in Tulsa, Oklahoma in both the new and legacy search modes.

What version of OsmAnd are you using, on what device and Android/iOS version?

OsmAnd~ 2.7.5

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

Offline maps.

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

USA Oklahoma, August 31, 2017

**Comment by vshcherb** [comment]
Search on device is totally different than in the backend ?!
<img width="1225" alt="screen shot 2017-09-21 at 00 10 07" src="https://user-images.githubusercontent.com/1042025/30670159-8d4b3d4c-9e61-11e7-8353-b7b7973eab65.png">

![screenshot_20170921-001107](https://user-images.githubusercontent.com/1042025/30670146-7e4baa2a-9e61-11e7-893c-f0ac4036a60d.png)
