### ISSUE TITLE
Turning off GPX announcements in the settings doesn't turn off the GPX announcement?

### ISSUE THREAD

**Issue by DaanCxx** [osmandapp/Osmand#4435]
When I'm navigating a GPX file I always uncheck announce GPX waypoints in the settings. However, Osmand will still call out things like "In 300 meters you reach your GPX waypoint" and "you have reached your GPX waypoint". I'm navigating through an earpiece only (no screen). 

How can I really turn these announcements off?

**Comment by vshcherb** [comment]
Fixed
