### ISSUE TITLE
Mapillary images showing functionality should be moved into plugin completely

### ISSUE THREAD

**Issue by KOLANICH** [osmandapp/Osmand#4436]
When I long tap on a location and the Mapillary plugin is **disabled** in the pannel appears I see Mapillary images. I guess this kind of functionality should be moved into the plugin completely.

P.S. I use the version from F-Droid.

**Comment by vshcherb** [comment]
Actually the movement is other way around, Mapillary plugin will be integrated next release. To avoid any contextual information this section could be collapsed and then no http interaction will be done.

**Comment by KOLANICH** [comment]
@vshcherb, why don't you want to keep it as a plugin?
