### ISSUE TITLE
Intent-Filter breaks OAuth process for other apps

### ISSUE THREAD

**Issue by westnordost** [osmandapp/Osmand#4440]
OsmAnd [registers itself for handling http and https connections](https://github.com/osmandapp/Osmand/blob/master/OsmAnd/AndroidManifest.xml#L233) for the whole of www.openstreetmap.org - and a whole lot of other unrelated websites.

The issue is, that during an OAuth process, the browser is opened with https://www.openstreetmap.org/oauth/authorize?something. If the user has OsmAnd installed, hey may then select to open it with OsmAnd, which will break the process. This is even more problematic if the user selected to always open it with it, as he will never even be asked again.

**Comment by westnordost** [comment]
Any official statement about this?

**Comment by vshcherb** [comment]
> If the user has OsmAnd installed, hey may then select to open it with OsmAnd, which will break the process. 

I think that's the source of the problem, so far we don't see how to filter special requests. OsmAnd is listening to openstreetmap.org / lat / lon - to show the place and it is not intentional to interrupt OAuth process.

**Comment by westnordost** [comment]
It is possible to specify the intent-filter more specifically, see the [<intent-filter> -> <data> reference](https://developer.android.com/guide/topics/manifest/data-element.html).

I.e. to just catch the map lat/lon, an intent-filter data like
```    
<data 
    android:scheme="http"
    android:host="www.openstreetmap.org"
    android:path = "/" />
```
or similar should be enough. I did not test it, but according to the reference, this would only match http://www.openstreetmap.org on root level, not for any other link to the website (like https://www.openstreetmap.org/oauth/...)

**Comment by westnordost** [comment]
[Test Node](http://www.openstreetmap.org/node/2595324513)
[Test latlon](http://www.openstreetmap.org/#map=17/50.06644/19.93515&layers=C)
