### ISSUE TITLE
contact:* not displayed

### ISSUE THREAD

**Issue by Chris-programmer** [osmandapp/Osmand#4442]
Android OSMand~ 2.7.5
Contact data from POIs tagged with "phone=*", "website=*", ... is displayed, but no contact data with the "contact:*=" format, which is also used and correct. 
For example:
website=http://example.com is displayed
contact:website=http://example.com is not displayed

http://wiki.openstreetmap.org/wiki/Key:contact

**Comment by aceman444** [comment]
This could be solved by preprocessing when creating the maps (e.g. in rendering_types.xml), changing the key from 'contact:phone' to 'phone', etc.

And it seems it is already done, see https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml#L476

So is it not really working?

**Comment by Chris-programmer** [comment]
Oh, it's working now
thank you and sorry for the issue
