### ISSUE TITLE
Add option to avoid routing over ice roads and fords

### ISSUE THREAD

**Issue by littlehelper** [osmandapp/Osmand#4446]
Hi,

Please add the possibility to avoid routing over ice roads and fords, like it is already possible for toll roads, unpaved roads, ferries etc., at least for car routing.
Thanks.

Greetings

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/a5dd15cee5d811bb772099dc4f704bd748961c03
