### ISSUE TITLE
OSM Live map files are never deleted when their main map file is removed

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#4447]
1. have some maps downloaded
2. then download OSM Live updates for them
3. remove one of the maps (normally from inside OsmAnd UI).

Result:
look into OsmAnd data folder/live subfolder. live update files for the removed map (country) are still there.
For other maps, the live update files are removed when the main map is updated from the monthly full update files. But the removed maps never will have their live files cleared.

**Comment by PaulStets** [comment]
Fixed with 5182a72

**Comment by aceman444** [comment]
Thanks!
