### ISSUE TITLE
Routing ignores roundabout

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4448]
Map: The Netherlands Gelderland.
Coordinates: 51.77032, 5.33176

When calculating a long route the roundabout is ignored by the route. A shorter route is calculated correctly.

Screenshots:
![21706471_1915632798683525_1607337069_o](https://user-images.githubusercontent.com/20681525/30520833-e2a1a926-9bbd-11e7-8966-15c4dccfc473.png)
![screenshot_2017-09-17-13-17-48](https://user-images.githubusercontent.com/20681525/30520832-e2a196d4-9bbd-11e7-8011-525fbcbd3261.png)

**Comment by xmd5a2** [comment]
Confirmed but only for native routing. Java routing builds a route without problems.
Native:
![screenshot from 2017-09-19 15-35-25](https://user-images.githubusercontent.com/5829014/30592640-441bd9b8-9d50-11e7-94e3-ee8c2ca63c7d.png)
Java:
![screenshot from 2017-09-19 15-35-36](https://user-images.githubusercontent.com/5829014/30592647-48ec314a-9d50-11e7-8767-965cfe539efd.png)

**Comment by bitboy85** [comment]
Penalty for unclassified roads? https://www.openstreetmap.org/edit#map=17/51.77170/5.33190

**Comment by PaulStets** [comment]
Fixed osmandapp/OsmAnd-resources#448
