### ISSUE TITLE
OsmAnd+ 2.7.5 very slow tracing new route

### ISSUE THREAD

**Issue by bumbaras** [osmandapp/Osmand#4452]
Is it normal for OsmAnd offline navigation service to tracing 470km route for 10 to 15 minutes?
It is really pain in a.. When I started using OsmAnd in 2015 it didn't take too much time to trace the route.
The main issue are the moments where I can't take traced route and need to take a bypass. Then I am getting message that I am out of route and need to wait at least next 10 minutes for OsmAnd to correct the route. This is the main pain in a.. My smartphone is Xperia M. Can I speed up OsmAnd somehow?
I am not using any addons.
Region Poland.

YOURS service is very fast but don't know if reliable.

**Comment by vshcherb** [comment]
It really depends on the route itself though 10 minutes for 470 km route sounds more or less realistic. The route complexity depends very much on the area & the complexity of the map data is increasing yearly.

We will be working on improvements but this issue in general may not be fixed.
