### ISSUE TITLE
Incorrect route time calculation

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4457]
While calculating a 495 km long route, OsmAnd shows the approximate time of the trip to be approx. 27 hours, while other navigation apps show 10 hours.

Gpx track: https://www.dropbox.com/s/74q85o71j8zlb4l/track.gpx?dl=0

Screenshots:
![20170919_094528_resized](https://user-images.githubusercontent.com/20681525/30596097-da3355c4-9d5b-11e7-8bf1-27cab2b45572.jpg)
![screenshot_20170919-165756](https://user-images.githubusercontent.com/20681525/30596157-014dad94-9d5c-11e7-8494-62c13114fbba.png)

**Comment by vshcherb** [comment]
GPX track time is not correct.

**Comment by scaidermern** [comment]
Did you calculate a route along a GPX track? Or did you use the regular route calculation in OsmAnd?

**Comment by vshcherb** [comment]
It looks like GPX track time which obviously doesn't know about speed limitation.

**Comment by scaidermern** [comment]
In this case this is caused by #4065 / #3908 and also by #3807.

**Comment by vshcherb** [comment]
I think it is related to #3807.

**Comment by vshcherb** [comment]
@scaidermern thanks for analysis
