### ISSUE TITLE
Bicycle route ignores a road

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4461]
Both examples below avoid segments of the Cycle Superhighway CS3 in London. 
The route options are set to Shortest with the elevation option disabled. 
Also OSM Live has been disabled, with the stock latest (1 Sep 2017) Greater London standard file installed afresh for this test.

Coordinates of the roue: 
Start: 51.5095, -0.0268
End: 51.5120, -0.0955

Screenshots:
![2017-09-19 17 12 18](https://user-images.githubusercontent.com/20681525/30635244-7d32e0ca-9dfa-11e7-899f-bcaf56569c31.png)
![2017-09-19 17 12 35](https://user-images.githubusercontent.com/20681525/30635245-7d366092-9dfa-11e7-97b7-666e65c00cfc.png)

**Comment by scaidermern** [comment]
Regarding the first screenshot: Looks like OsmAnd ignores the first part of this way: https://www.openstreetmap.org/way/232178242. But why?

**Comment by PaulStets** [comment]
Routing ignores https://www.openstreetmap.org/way/232178242 because it has the footway=sidewalk tag. This tag lowers this road's priority and therefore the roting algorithm prefers other roads.

**Comment by tilusnet** [comment]
Sounds like a clear bug. Thanks for working on it.

**Comment by tilusnet** [comment]
Hi. OsmAnd 2.8.2+ still has the bug.
Was the fix merged in?

**Comment by PaulStets** [comment]
Hi, I've just checked and can't see the problem. Perhaps you have should change your Avoid... options for the bicycle profile.
Screenshot:
![23660714_1941962982717173_491646924_o](https://user-images.githubusercontent.com/20681525/32941912-10ea2e96-cb90-11e7-9846-61f4e897bbf2.png)

**Comment by tilusnet** [comment]
Hi,

Thanks for checking.
Mine still doesn't route as it should. Settings are all on default.


[image: 2017-11-22 11.03.55.png][image: 2017-11-22 11.01.44.png]

**Comment by PaulStets** [comment]
@tilusnet Please try to clean-install the newest OsmAnd free version from Google Play and check if the route is calculated correctly.

**Comment by tilusnet** [comment]
Hi Paul,

You are correct, latest OsmAnd works.
Why is latest OsmAnd+ broken then?

**Comment by PaulStets** [comment]
Hi, Attila.

OsmAnd and OsmAnd+ have the same source code. Perhaps the issue is caused by the old cached files in OsmAnd+. Please backup OsmAnd+'s data (Android/data/net.osmand.plus) and perform a clean installation of the app. Then, put all the .obf files, 'voice', 'tracks' and 'backup' folders.

**Comment by tilusnet** [comment]
Thanks, I'll try.

In the meantime I notice that OsmAnd is still not doing the route
correctly. Towards the end of the route an unexpected loop is still
present. This should not be there - there's a segregated cycling lane going
along Tower Hill road.

**Comment by PaulStets** [comment]
@tilusnet Could you please attach a screenshot of the loop and send the coordinates of the place?

**Comment by tilusnet** [comment]
Screenshot was in my email, got stripped?

Coords: just next to Tower of London,
https://tools.wmflabs.org/geohack/geohack.php?pagename=Tower_of_London&params=51_30_29_N_00_04_34_W_type:landmark_scale:3000_region:GB


[image: Screenshot_2017-11-22-14-44-25.png]

**Comment by PaulStets** [comment]
@tilusnet Sorry, the attachment still did not come through. I suppose you mean the detour on the screenshot I attached?
![23897049_1944549189125219_2033898614_o](https://user-images.githubusercontent.com/20681525/33138783-06b2dd88-cfb4-11e7-88bf-c7cf407d5ab7.png)

**Comment by tilusnet** [comment]
Strange, I attached it again last time inline.
I'll add it on github soon.

Yes, my loop is similar to yours, albeit not that large.

**Comment by tilusnet** [comment]
Here's mine (latest OsmAnd, fresh install) :
![screenshot_2017-11-22-14-44-25](https://user-images.githubusercontent.com/705606/33139028-fbca57da-cfa3-11e7-8ba2-13019676a651.png)

**Comment by PaulStets** [comment]
No need attaching the screenshot, I suppose it's like the one I attached this time. Anyway, this is another bug that needs to be fixed. I will create the new issue and post the link to it here.

![23848101_1944552302458241_1035356974_o](https://user-images.githubusercontent.com/20681525/33139079-ef9962a6-cfb4-11e7-8c12-7f77ef40c326.png)

**Comment by tilusnet** [comment]
Thanks!
Keep me posted.

**Comment by PaulStets** [comment]
Here's the link to the new issue: https://github.com/osmandapp/Osmand/issues/4798

We'll fix it soon.
