### ISSUE TITLE
Add GPX export for locally created OSM notes

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#4469]
I know there is the GPX record plugin which allows to create GPX waypoints.

Nevertheless I think it would be nice to allow locally created OSM notes to be exported to a GPX file (as GPX waypoints) as an alternative to uploading them. This allows to open these notes in an OSM editor such as JOSM or iD.

**Comment by KOLANICH** [comment]
... and POIs too ....

**Comment by vshcherb** [comment]
Sounds good

**Comment by KOLANICH** [comment]
Thank you.

**Comment by AlexSyt** [comment]
You are welcome.
