### ISSUE TITLE
Draw hiking symbols on top of turn arrows

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#4480]
Hiking symbols are currently hard to read during routing because they are often covered by navigation turn arrows:

![photo_2017-09-25_22-40-44](https://user-images.githubusercontent.com/1040784/30830119-23c85d10-a243-11e7-95f8-b6e03b71caf5.jpg)

I suggest to draw hiking symbols on top of turn arrows. This makes navigation easier because you can easily see which hiking symbols to follow.

**Comment by vshcherb** [comment]
Currently not possible with rendering engine, but indeed it is nice to have.

**Comment by njohnston** [comment]
@scaidermern: a possible workaround is to make the turn arrows transparent. I've done this with a custom rendering style. This is the XML you'll need to use:

```xml
  <!-- Make sure turn arrows on a route don't obscure road names and types
       (set alpha on color_3) -->
  <renderingAttribute name="route">
		<!-- fluorescent: filter attrColorValue="#CCFF6600"/ -->
		<!-- was badly visible on motorways: filter nightMode="false" attrColorValue="#960000FF"/ -->
		<!-- color_3 used for turn arrows on the route -->
		<case color="#88aa0088" strokeWidth="12:8" color_3="#aaffde5b" strokeWidth_3="7:6">
			<apply_if nightMode="true" color="#aa00fff7"/>
		</case>
	</renderingAttribute>
```

You can also get the [full custom rendering file](https://drive.google.com/file/d/0ByKX_Fubbb4QMzhITklWb19HblE/view?usp=sharing) if you want and delete the parts you don't need/want.

**Comment by dmpr0** [comment]
Fixed
<img src="https://github.com/osmandapp/OsmAnd/assets/9365308/ed983995-dc64-4e9e-b3c9-323999eae3c3"  width="300" height="auto"/>

**Comment by scaidermern** [comment]
Indeed, nice!
