### ISSUE TITLE
Use of AsyncTask.execute(Params...) in OsMoGroups.java

### ISSUE THREAD

**Issue by frankFic** [osmandapp/Osmand#4484]
Hi there,

I believe you might have already noticed the behaviour change of Async.execute(Params...) since Android API 11 ([Doc](https://developer.android.com/reference/android/os/AsyncTask.html#execute(Params...))). This API is still used on API 11 or later in OsMoGroups.java. E.g. [Line 384](https://github.com/osmandapp/Osmand/blob/73dcab7d0b944e54a7fb08ee0f323e9588a2dfdb/OsmAnd/src/net/osmand/plus/osmo/OsMoGroups.java#L384) to start a task to download some files.
 Running the AsyncTasks using this API may still cause some background tasks blocked since they will be executed on a single thread. I think it may be better if the tasks are executed in real multi-thread like you have implemented in other files such as OsmandMapLayer.

I didn't follow the report format but my report is closely related to the code.

Hope this information could help. :)

**Comment by vshcherb** [comment]
OsMo Plugin is deleted from UI & soon will be deleted from code
