### ISSUE TITLE
Routing uses one way route in wrong direction

### ISSUE THREAD

**Issue by psamim** [osmandapp/Osmand#4485]
Hi,
I am using Osmand 2.7.5 on Android 8.0. I use offline maps, have `OSM Live` enabled, and use OsmAnd (offline) navigation service. 

The routing suggests the wrong direction for a one-way route. The update to the route's direction is new (less than a month) but it is available on my map anyway, via OSM Live or regular updates.

![photo_2017-09-26_20-18-05](https://user-images.githubusercontent.com/1868679/30872728-9b8613f0-a2da-11e7-80bd-49b36c8ce578.jpg)
![photo_2017-09-26_20-18-11](https://user-images.githubusercontent.com/1868679/30872729-9b8e51aa-a2da-11e7-88bf-e95c945d2a6f.jpg)

**Comment by vshcherb** [comment]
OSM Live is not used in current release for routing but it will be used next release.
