### ISSUE TITLE
librem-5 

### ISSUE THREAD

**Issue by noci2012** [osmandapp/Osmand#4489]
About this phone:    https://puri.sm/shop/librem-5/
Or for:  https://www.postmarketos.org/  (on a lot of current big industry abandon phones)
based systems, how much effort would it be to get osmand running there?
(Both aim for native linux phones without Android compatible.)

What would be required.

**Comment by gjedeer** [comment]
I'd start looking at [offroad project](https://sourceforge.net/projects/offroadosm/) and swapping their swing UI with a toolkit that supports touch gestures.

**Comment by pitlochry** [comment]
librem5 support (or linux-support in general) would be much appreciated!
Thanks

**Comment by Xon2** [comment]
same here...proper linux support would be a dream come true. Eventually, i hope to be able to switch away from google's android once some properly working linux version is available for smartphones. OSMand is the singular tool i really,...i mean really hate to loose! I hope the devs give this some thought and help us get ouf of the walled garden :)

**Comment by Rik44444** [comment]
hi all , just to say I agree: OsmAnd for Plasma mobile would be great and really in line with both KDE's and OsmAnd's goals!

**Comment by noci2012** [comment]
@ vshcherb   - any news? the release of this phone is still on track for end of Q1 / Q2 this year.

**Comment by Rik44444** [comment]
plasma mobile is already available on the Google nexus 5 and 5x!

**Comment by chri2** [comment]
I already decided to switch to Librem5. After looking into Android a bit more because of problems and broken phones I realised that using Osmand with offline maps and mostly without network connection is just such a little step to stop constantly pushing personal data to Google and the like. 
Osmand is the only app I'd really hate to loose and I'd happely donate again if it'll be available for Librem5 or Linux in general when Purism finally delivers my new phone. 
I'd also be in for a campaign to finance a developer kit or a development phone and/or development and maybe Purism - when asked - would help also.

**Comment by noci2012** [comment]
Development can already be started with the VM version. (Qemu based).

**Comment by noci2012** [comment]
Any news? they still talk of delivery in Q3...
https://puri.sm/products/librem-5/

**Comment by noci2012** [comment]
@vshcherb 
librem-5 (Linux   gnome & plasma based phone, NOT Android) is in production it comes in 4 waves (each 1 month)  of early production models with progressively tightened milled cases and then production models with molded cases, from january/february.. 
Any news, are there any plans, issues, ...  for porting?
Or is this a no-go area.  (In that case you can close this issue).

**Comment by vshcherb** [comment]
Agree to close issue cause it is nearly impossible to port 500K LOC from Android. It took us 4 years to do similar on IPhone, so the chance to get it is 0.001% or so. 
Though this looks promising https://forums.puri.sm/t/is-it-possible-to-use-android-apps-on-the-librem-5/3169 ( anbox).

**Comment by ollieparanoid** [comment]
Regarding non-Android based Linux phones, and especially postmarketOS, there's work being done to package puremaps: https://gitlab.com/postmarketOS/pmaports/merge_requests/593

There were also some efforts to get anbox running on postmarketOS (which would then run android apps like osmand), but there's nothing working yet: https://gitlab.com/postmarketOS/pmaports/issues/17

Just leaving the links here for reference, in case somebody wants to check them out and possibly contribute. Thanks to everybody working on osmand, I use it often on my android phone!

**Comment by noci2012** [comment]
I guess that will be Puremaps for future non-Android users, as they are ready to go there.
Why try to get Android on a phone where you go to escape Android...
