### ISSUE TITLE
MTB downhill trail direction

### ISSUE THREAD

**Issue by Aiurek** [osmandapp/OsmAnd#4495]
For mountainbikers it is important to locate trails. Osmand's a great help here.
Though, a tiny but very important info is missing in the illustrated mtb routes: Some kind of indicator which illustrates the inclination and direction of the trail.
Especially when you want to explore new trails as a mountainbiker, it's hard to say on which end of the trail you should start riding when using Osmand, with "mtb routes" activated, for orientation.
Therfore, I'd suggest to add some kind of arrows to obtain info regarding incline=", where only the direction from trail top to trail end is illustrated (without any inclination values, e.g. 25°).
Maybe this could be merged with the mtb:scale:uphill=" tag, like proposed in the following figure, whereby I don't know whether the arrows are recognizable for a user...

Really looking forward to having some kind of indication for the trail inclination :)

![mtb](https://user-images.githubusercontent.com/27865200/31013087-cb3ae86e-a514-11e7-80b3-a5bf4e76b558.jpg)

**Comment by xmd5a2** [comment]
This can be solved only by adding standard arrows.

**Comment by Aiurek** [comment]
On the OSM website the value incline:down is illustrated with arrows. Though, this could be also due to oneway:yes...
Is it possible to add the one way arrows without the oneway value being actually there? Because some trails can also be used in both directions, whereby it's really helpful to know the inclination if you only want to go downhill.

https://www.openstreetmap.org/#map=17/48.83065/9.59145

![fghr](https://user-images.githubusercontent.com/27865200/73756208-79452680-4767-11ea-9af6-95731f0e80ab.jpg)

**Comment by vshcherb** [comment]
@xmd5a2 it is not bad idea to add standard oneway icons diff color

**Comment by Aiurek** [comment]
I'd say the arrow needs to be connected to the tag incline: and combine the values up and x% as wells as down and -x%.
The oneway tag is only used in a relatively rare number of mountainbike-trails, since most of them can also be used uphill.
But it'd be of really great value to have the downhill direction illustrated by an arrow. Thus, it's a lot easier for bikers to spot the trail entrance.

**Comment by xmd5a2** [comment]
For OpenGL engine only. Works only when 'incline' tag used.
![Screenshot_2022-11-29_13-54-11](https://user-images.githubusercontent.com/5829014/204510949-c01c3407-d5fe-4519-b164-0f085035a683.png)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.3.0#13991mqta, released: 2022-12-02
MTB downhill trail directions aren't displayed
[OSM incline down](https://www.openstreetmap.org/way/391337687#map=17/59.97510/10.91424)
[Map here](https://drive.google.com/drive/folders/18GncPZy9fhNqODjlEVm9E1U1vDBg68lb?usp=sharing)


https://user-images.githubusercontent.com/104760013/205288741-50c1aad3-cf7f-4e0b-81b5-0f76cd96f762.mp4

**Comment by xmd5a2** [comment]
![Screenshot_2022-12-02_16-47-26](https://user-images.githubusercontent.com/5829014/205307111-38c73eb3-3435-4c47-a34f-1b293ab59983.png)
https://www.dropbox.com/s/tddx0pyejolxvk0/Test_oslo2_2.obf?dl=0
You are using old rendering_types.xml

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.3.0#13998mqta, released: 2022-12-05
[Map](https://drive.google.com/drive/folders/18GncPZy9fhNqODjlEVm9E1U1vDBg68lb?usp=sharing)

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/205623566-6484f4c5-88b5-4ceb-8adc-3d7408da45d6.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by xmd5a2** [comment]
![Screenshot_2022-12-13_10-39-25](https://user-images.githubusercontent.com/5829014/207255419-9e9efb6e-1116-43be-b79a-a9b5ad563e53.png)
