### ISSUE TITLE
Updated relation cause object removal in OSM Live

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4499]
If a relation is updated (e. g. some of its elements are removed from the relation but not from the map) in OSM, Overpass start query will return the relation members, but the end query will not contain those elements. This causes a situation where a map object is being marked as deleted in the diff file.

Example:
These houses were removed from the relation: https://www.openstreetmap.org/way/526610870.
They were added here: http://builder.osmand.net/osmlive/_diff/17_09_26/17_09_26_08_15.obf.gz with osmand_change=delete tag.

**Comment by vshcherb** [comment]
Fixed

**Comment by rogerjames99** [comment]
Are you sure. I cannot see any buildings outlines at all now, anywhere in 
the map. Even in areas that used to render fine. Things like house numbers 
are rendered OK.

Roger

**Comment by PaulStets** [comment]
Please download October map updates and clear the old OSM Live update files by disabling the live updates.

**Comment by rogerjames99** [comment]
Hi Paul,

That fixed it thanks. Great support.

Roger

**Comment by rogerjames99** [comment]
Hi Paul,

I am sorry I seem to have broken OSM Live again somehow. I have attached 
two screenshots. One from Osmand and the other from the ID editor on 
openstreetmap.org. The area in question seems to be stuck at a very early 
stage of my edits of the building polygons as far as OSMLive is concerned.

The area concerned is at Lon: -2.7577695 Lat: 54.1062953. Not far from 
where the last problem was. There are no relations involved in this just 
quite a few removals and recreations of polygons in the same area as I 
learnt the idiosyncrasies of the JOSM buildings plugin.

Any ideas?

Roger

**Comment by rogerjames99** [comment]
Oops forgot to attach the screen shots.

**Comment by rogerjames99** [comment]
![screenshot_20171023-115640](https://user-images.githubusercontent.com/3677901/31899160-d5a49492-b812-11e7-9cd1-1c848e426618.png)
![screenshot_20171023-115419](https://user-images.githubusercontent.com/3677901/31899173-dcac9064-b812-11e7-9840-198bd828fdb7.png)

**Comment by PaulStets** [comment]
Hi, Roger.

I have tested this at our end. Everything is as it should be. Seems like you need to uncheck Polygons in Configure map - Hide.
![22810073_1931701047076700_1287609809_o](https://user-images.githubusercontent.com/20681525/31931341-97945734-b8ab-11e7-995d-8e4421678a8a.png)

**Comment by rogerjames99** [comment]
Paul,

I have checked that polygons not being hidden on two different devices,  
Nexus 10 and Nexus 5. No hides are set on either and both still show  the 
the wrong or old polygons.

The image you attached in your last message shows the incorrect rendering. 
All the buildings should have orthogonal corners. Is that image a new one 
or one of the ones I originally attached?

Building 8 is a good example of the bad rendering. Another strange thing is 
that if you single tap on the building/house number a different but still 
wrong polygon is drawn as a highlight.

Is there a way to clear any cached polygon data without reinstalling the app?

Roger

**Comment by vshcherb** [comment]
@rogerjames99 it might be related to OsmAnd rounding coordinates. OsmAnd doesn't store precise 31 coordinates.

**Comment by rogerjames99** [comment]
Thanks, that is what it is. I got confused by the polygon looking like one of my earlier versions, and thought it had not been updated.
