### ISSUE TITLE
Farsi/Arabic texts are incorrectly displayed LTR

### ISSUE THREAD

**Issue by psamim** [osmandapp/Osmand#4506]
Hi,
I am using Osmand 2.7.5. I enabled `More details` in map configuration. When I click on an area with Farsi names, the name is displayed incorrectly at the bottom of the screen. The letters are displayed from left to right, while Farsi is an RTL language. This has been tested and reproduced on Android version 6 and 8. 

Below is the screenshot. The title is incorrectly displayed `LTR` at the bottom of the screen.

![image](https://user-images.githubusercontent.com/1868679/31058295-d579cbba-a6e0-11e7-950f-e7fa70aa1b8b.png)

**Comment by FTABoy** [comment]
i can confirm and reproduce this issue and having same problem. the "More details" option should be selected to reproduce this issue. here is a sample shared location:
ﻩﺪﮑﻫﺩ
Location: geo:35.72811,50.96457?z=14
https://osmand.net/go?lat=35.72811&lon=50.96457&z=14
as it can be seen here the shared name is also incorrect , it should be "دهکده".
![screenshot_2017-10-01-13-39-48](https://user-images.githubusercontent.com/25687276/31058402-cc643000-a6ff-11e7-9d61-676172e9cefb.png)
![screenshot_2017-10-01-22-46-27](https://user-images.githubusercontent.com/25687276/31058410-e20f70c2-a6ff-11e7-8fca-9d60b15d8edc.png)
thanks in advance for this great app.
regards.
