### ISSUE TITLE
GPX auto-save

### ISSUE THREAD

**Issue by eMPee584** [osmandapp/Osmand#4507]
Hadn't there been such a feature before? I remember vaguely to have used it a couple of years ago.
#2641 #2721 seem to bring up the topic but without tangible conclusion.
So am I missing out on an obscure menu option, has it been removed or what is the matter with trip auto-saving?
Edit: »Auto-record track during navigation« seems to be half there, but I seldom use navigation because it lags a lot on my 2012 Droid 4.

**Comment by vshcherb** [comment]
GPX is auto saved after restart on the next day.

**Comment by eMPee584** [comment]
This is very much non-obvious. There should be visible feedback that one does not have to worry about manually saving tracks.
