### ISSUE TITLE
New Wales - Coffs Harbour flooded with water

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#4516]
You can reproduce the issue here: http://osmand.net/go?lat=-30.303083&lon=153.12384&z=16
Map: Australia New South Wales.
The issue is related to basemap determine land/water algorithm

![](https://user-images.githubusercontent.com/20681525/27186483-2b4eebf0-51f1-11e7-8714-fad83a742b83.png)

**Comment by jaller94** [comment]
Confirming lots of flooding problems in Coffs Habour, Australia with the standard map in OSMAnd 2.7.5.

**Comment by PaulStets** [comment]
Fixed with https://github.com/osmandapp/OsmAnd-core/commit/a6782a76959c94946e787ce4bdfc469b5194dfa3
