### ISSUE TITLE
Generated offline map lacks details.

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4518]
Location: https://osmand.net/go?lat=54.830383&lon=20.157423&z=14

Screenshots:
![screenshot_2017-10-02-21-46-49](https://user-images.githubusercontent.com/20681525/31117827-ef024db0-a833-11e7-814d-839ef915cd9f.png)
![screenshot_2017-10-02-21-57-06](https://user-images.githubusercontent.com/20681525/31117828-ef042626-a833-11e7-8b3e-a4bf469f844e.png)

**Comment by vshcherb** [comment]
Currently rendering of https://www.openstreetmap.org/way/520584957 not supported
