### ISSUE TITLE
Current position bounces during movement

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4519]
Device: Samsung Galaxy S8

While using OsmAnd the arrow is shown. After 10-20 seconds instead of the arrow the blue circle appears, it is a little off the current position, after a second the arrow is back. Osmand all this time showed 10-12 satellites out of 22. A few seconds pass and again the arrow disappears, the circle is further from the position, Osmand shows 0 satellites, the GPS Toolbox shows 0 satellites and writes "Search for satellites". The issue does not happen in any other navigation app.

Screen recordings:
https://www.dropbox.com/s/z5e91weqfywtz2c/2017_10_02_18_25_04.mp4?dl=0
https://www.dropbox.com/s/rsdplgun2cqeef4/2017_10_02_18_30_53.mp4?dl=0

**Comment by vshcherb** [comment]
Not visible on the video, anyway there are extra settings to configure recording settings.
