### ISSUE TITLE
Please show tag <charge> in POI information

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#4523]
With a lot of POIs tag <fee> (=yes/no) can be accessed, and additional to it the amount of the fee in tag <charge>. 
Charge can be used without fee !!
I know that charge is not filled very often, but may be due to the fact, that no program is displaying this tag.

So please:
add line charge with contens directly below line fee (if fee=yes) and if charge is filled
Example:
fee: yes
charge: 5 Eur
or
contens of charge instead of "yes" behind fee (example: "fee: 5 Eur").

Let us hope, this will help that more and more guys will collect information of charge when they see that it is used.
Thanks a lot, Peter
![screenshot_2017-10-03-18-37-42](https://user-images.githubusercontent.com/18628183/31137224-e4bd7280-a86a-11e7-9bbd-749db5ba9014.png)

**Comment by aceman444** [comment]
Yes this would be great to display charge=* on parkings or any objects that have fee=*.

**Comment by pebogufi** [comment]
Fixed since a few days. Thanks a lot.
