### ISSUE TITLE
Trip recording plugin creates annoying notification on every OsmAnd start

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#4524]
If the trip recording plugin is activated then OsmAnd will create a corresponding notifciation on every start, even if no GPX recording is activated:

![photo_2017-10-03_22-27-52](https://user-images.githubusercontent.com/1040784/31147445-42a13232-a88a-11e7-889d-051129e06208.jpg)

It would be nice if this notification would only show during active GPX recording. Without active GPX recording the notification doesn't contain any useful information.

**Comment by njohnston** [comment]
Is the "Trip recording (no data)" option at the bottom of Settings -> Trip Recording enabled? Disabling that could prevent the notification appearing.

**Comment by scaidermern** [comment]
> Is the "Trip recording (no data)" option at the bottom of Settings -> Trip Recording enabled? Disabling that could prevent the notification appearing.

Yes, disabling this option also disables the notification. Thanks! Actually I didn't understand the meaning of this setting (neither in English nor in my native language). Also so far I wasn't aware of the possibility of "opening" a notification to get the record button that is mentioned in the setting description. Pretty confusing in my opinion :)

Maybe the default state for this option should be changed from on to off?

**Comment by vshcherb** [comment]
Something wrong with description of that setting and we need to address it (@sonora)
