### ISSUE TITLE
Ignoring motorway

### ISSUE THREAD

**Issue by M1dgard** [osmandapp/Osmand#4526]
There's a new motorway in Belgium and we'd like to route over it. :)

![screenshot_20171004-074746](https://user-images.githubusercontent.com/4283376/31161675-f34b3a12-a8d8-11e7-9e75-6878b23f0509.png)
![screenshot_20171004-074801](https://user-images.githubusercontent.com/4283376/31161674-f3280dd0-a8d8-11e7-9281-5ed889422086.png)
![screenshot_20171004-074815](https://user-images.githubusercontent.com/4283376/31161676-f34e225e-a8d8-11e7-8764-0677a2789976.png)

Settings: car, no "avoid" options checked, fastest route, no height/width restrictions, don't allow private access.

Mapzen does the same: https://www.openstreetmap.org/directions?engine=mapzen_car&route=51.2482%2C3.1859%3B51.2970%2C3.3324

Possible penalties I can think of that may cause this:
* [movable bridge](http://www.openstreetmap.org/way/520414147#map=17/51.27386/3.21230),
* [traffic light](http://www.openstreetmap.org/node/5063062763) and [lift gates](http://www.openstreetmap.org/node/5063062760) on the motorway,
* [emergency cross-carriageway roads](http://www.openstreetmap.org/way/519176757#map=16/51.2727/3.2107).

Moving either the starting point or destination so that it has no choice but to route over this part succeeds.

**Update:** the motorway appeared first in the September dataset, the routing behaved in the same way back then.

**Comment by scaidermern** [comment]
Pretty sure the reason are the `barrier=lift_gate` notes. They lack a proper access tag. In my opinion they should have an `access=yes` tag because they are usually open for everyone that is allowed to use the motorway. So this is an error in the map data.

**Comment by M1dgard** [comment]
I've added `access=yes`. Let's see what this gives next month.
