### ISSUE TITLE
Cached position often shown in blue instead of gray

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#4536]
It is good that we now display the cached position while no location reception is available, but it can also be irritating: When on a hike, whenever I briefly turn on my phone to check my position, OsmAnd immediately displays one, but it is mostly first the outdated cached one, which can be very misleading. I suggest that we should display the icon for the cached position in another color, e.g. orange.

**Comment by scaidermern** [comment]
Or maybe display something like a blue question mark instead?

**Comment by sonora** [comment]
Yeah, simplest coding may just be using the existing icons but with different color like orange or maybe just gray, instead of blue.

**Comment by vshcherb** [comment]
I think today we display grey as I tested, so if it doesn't work (which in many situations I saw working), then we need to fix it.

**Comment by sonora** [comment]
Yes, gray is just fine. I have in fact now seen gray on a few occasions (however only for the stationary point, never for the moving arrow).

But in the vast majority of cases I do actually observe blue, either as point or as arrow, immediately after turning on the phone and before the position gets updated, i.e. clearly in the wrong position. So something seems broken.

It is most easily observed when you record your hike (time constant 30 sec so the GPS turns off between recording points), and display the currently recorded track. After turning on the phone the **blue** arrow will almost always display you walking some distance **behind** the current tip of the track.

**Comment by sonora** [comment]
Yes, this commit improves the behavior a lot, seems like the true positiom is updated more frequently now.

But the original issue reported remains in place: When while hiking every few minutes I turn on the device, OsmAnd displays the old, outdated position arrow (where and in which direction I walked when the device was last on!) in blue until a new position is found, i.e. the color is never updated to gray.

**Comment by crimean** [comment]
Please recheck it with time interval more than 30 sec (ie. put app to background and restore it after 30+ sec). I cannot reproduce. If I return to app after 30 seconds - my location is in gray color.

**Comment by sonora** [comment]
Could it be that it depends on whether your last position was taken while walking, and not at rest? Looks like for me it now works for the 'dot' icon, but not for any 'arrow' position icons?

**Comment by crimean** [comment]
You are right. The blue arrow was drawing for outdated location. Fixed by https://github.com/osmandapp/Osmand/commit/77decbff8ad1c31d1dddd997b248359e180e2ffa
