### ISSUE TITLE
External SD-Card issue since Android 7

### ISSUE THREAD

**Issue by MeCias** [osmandapp/Osmand#4537]
Hi guys,
I have an issue with my external SD-Card since my Android phone (Sony Xperia) was updated from Android 6 to 7 last month. I used Osmand+ in combination with Android 6 over a year now and up to yesterday I didn’t notice any strange behavior, but since my phone was updated to Android 7 during the last month and it was time to update the offline maps I noticed that this didn’t work as it used to be. After the map was downloaded only the error “I/0 error occurred: old file can’t be deleted” was displayed and nothing else was happening. So I decided to do a fresh installation. Even with this new installation and trying different external SD-Cards I could not make it work. As long I place the Osmand+ profile folder on the phone storage it works fine. My workaround for now is to do the setup on the phone storage – download all necessary maps, languages, voices, etc – and shift the folder afterwards to the external card. That seems to work, but might be quite uncomfortable if you wanna do this every month as soon the maps get updated. 
Anyhow since Android 7 it seems that Osmand+ has no write access on the SD-Card. Every other app that has access to the card works as expected. After a fresh installation of Osmand+ I adjust the storage to the SD-Card and get asked about the access to media and pictures that I of course allow. I also played around with access as device administrator but even then no change. 
What else can I try do? Thanks in advance for any advice.

<img width="203" alt="screenshot_20171005-213310" src="https://user-images.githubusercontent.com/4476171/31287984-7c3bfef6-aac3-11e7-9332-265365742655.png">

**Comment by jfburke3** [comment]
I just want to make the observation that I am NOT having this problem on my Samsung Galaxy S7 Edge, Android 7.0.1.  I have the map files on my SD card and they work well.

**Comment by MeCias** [comment]
Thanks a lot for your response. I probably just do a factory reset and start over. Maybe something during the update process from 6 to 7 wrecked it. Hope it will work.

**Comment by MeCias** [comment]
The factory reset did it. It is working now.
