### ISSUE TITLE
Wrong turn direction (offline routing)

### ISSUE THREAD

**Issue by reald** [osmandapp/Osmand#4546]
Same intersection as #4544 but this time another error from the other side:

Route goes to the right (which is correct) but osmand assumes it´s straight on. Also wrong lane in turn direction is shown:
![bierweg_right](https://user-images.githubusercontent.com/1385404/31288444-3d7c61ea-aac5-11e7-98b0-fab855a1c84f.png)

Turn lanes are mapped correctly:
```
turn:lanes = left|left;through;right
```
from the position (blue arrow) until the bend to the right (which is the correct route) and
```
turn:lanes = left|left;through
```
between the bend and the traffic lights. (Because you must take the bend before if you want to get right.)

The intersection is here:
http://www.openstreetmap.org/#map=17/49.48942/11.12497

Route to reproduce: Route from "Thuisbrunner Straße / Bierweg" to "Sieboldstraße 6" in Nürnberg. 

Version: osmand~ 2.7.5 on Android 7.1.2
Offline map: Europe -> Germany -> Bavaria Standard Map 1.10.2017
Routing profile: Car
![bierweg_right2](https://user-images.githubusercontent.com/1385404/31288450-41974f24-aac5-11e7-8ff4-9d50cb864f10.png)

**Comment by hakuchi** [comment]
looks like #3665 and #3357

**Comment by vshcherb** [comment]
Fixed

**Comment by xmd5a2** [comment]
Test added
