### ISSUE TITLE
OsmAnd and App Inventor 2 Activity Starter

### ISSUE THREAD

**Issue by anashe00** [osmandapp/Osmand#4547]
Hi,  there.

I would like to implement OsmAnd 2.7.5 in an application I'm building with App Inventor trough Activity Starter.

I have Android 5.1.1 version and use offline map I downloaded yesterday.

As the example here https://puravidaapps.com/images/snippets/2osmand4.png which is for starting OsmAnd and get in a specific place, I would like to know what are right commands for starting nagivation at a designed location using pedestrian routing profile.

After spending lot of time googling I founded the Activity Class is net.osmand.plus.activities.MapActivity.
For the syntax of Data URi I tried "geo:...,...?z=12" unfortunately I'm not sure if it is the right syntax because every time it start, there is a home page with "get started" button that I have to click. After that it ask me to download offline map (altough I already downloaded a map).

Such I'm looking help to find a way for going directly to the indicated navigation location without home page and without I need to skip the messages about downloading maps (because I already downloaded it and it's work well when I use it in offline mode).

PS: I'm not an android developper and sorry for my english.
Thanks in advance for helping me.

**Comment by vshcherb** [comment]
I think you need to define in AndroidManifest an activity that handles intent (geo or whatever), in case you define it as MapActivity you will be able to handle it just there.
