### ISSUE TITLE
Surface characteristic on tennis courts with incorrect value

### ISSUE THREAD

**Issue by franco999** [osmandapp/Osmand#4548]
On tennis courts with the tag in OSM `surface=clay`(in spanish "Polvo de ladrillo"), OsmAnd tagged them as if they were `surface=dirt` (in spanish "Tierra lodosa"). 
Can you add this surface **(clay)** to translations? Also `surface=artificial_turf` for soccer pitchs?

surface=clay https://wiki.openstreetmap.org/wiki/File:EVD-tenis-212.jpg
surface=dirt https://wiki.openstreetmap.org/wiki/File:Transportation_in_Tanzania_Traffic_problems.JPG
surface=* https://wiki.openstreetmap.org/wiki/Key:surface

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/9c7eeda870dca7ce3bc76ed65a95af79e259690f
