### ISSUE TITLE
Voice speed warnings are delayed

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4551]
When selecting "0"-tolerance in speed warning and closing and restarting the app then the visual warning is OK in working with "0"-tolerance. It appears right away, but the voice warning is delayed for 5 - 15 seconds after the visual sign is seen.

**Comment by sonora** [comment]
On purpose, I think. Immediate voice warnings without grace period used to annoy many users ... ;)

**Comment by PaulStets** [comment]
Thanks for the clarification:)
