### ISSUE TITLE
Building Osmand Plugins

### ISSUE THREAD

**Issue by Bubu** [osmandapp/Osmand#4552]
I want to rebuild/add all osmand plugins to f-droid again, as they are only available there in the archive right now.

Unfortunately I have found no documentation for building these plugins, I assume they are build with gradle as there is a build.gradle file present.

But the plugins dirs have been excluded from settings.gradle in https://github.com/osmandapp/Osmand/commit/b99cfc1127e8372bf4eeeb94719a734fba3e0375. Re-including them leads to a conflict in build tools version. 23 from the main app to 25 for one plugin I tried.

So if someone can point me in the right direction here this would be appreciated.

**Comment by vshcherb** [comment]
Plugins are empty and they don't have any code itself, so there is no need to rebuild them.

**Comment by Bubu** [comment]
Thanks for you answer. That actually clears things up quite a bit!
