### ISSUE TITLE
Our grade smoothing or curve looks somehow wrong

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#4553]
Discovered when analyzing #4481, with the test track provided there. Look at the correlation between altitude and grade, which seems clearly wrong. It may be a result of the smoothing applied, then this needs revisiting, or maybe the two curves just mismatch laterally in the graphics.

![screenshot_2017-10-09-08-22-56](https://user-images.githubusercontent.com/845735/31327491-e1bf3050-accf-11e7-8d63-289a00476aa8.png)

**Comment by crimean** [comment]
@sonora Hardy, I reduced value of slope proximity constant (https://github.com/osmandapp/Osmand/commit/d68606bd5de11ae0f2bf82cc069b49e9f537f9e1). The chart looks better now. Please check it with other tracks.

**Comment by sonora** [comment]
Alexey, yes, I think it is ok. It seems to only appear at large magnifications anyway.

The issue seems somehow related to #4481. I will look into that some, and if I find a better smoothing mechanism we can always revisit this issue here, too.

**Comment by vshcherb** [comment]
@sonora I will close that issue cause the primary source of the slope misalignment is the noise in the original file.
Actually for slope we do smoothening that's why it could be even more accurate than raw noisy data. Though it creates misalignment between raw height & slope data

**Comment by sonora** [comment]
Yes, exactly, I come to the very same conclusion. I think the final solution must be to apply a good smoothing to the elevation data, then derive the slope (and the ascent/desent accumulation) from it, so everyting would be better aligned.

**Comment by sonora** [comment]
I have not fully researched how the smoothing is currently done for our grade curve. But I guess a straightforward solution for a grade smoothing could be we simply use LPF smoothed elevation data (5 point running average, like I do here: https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/GPXUtilities.java#L435), then simply define the grade as difference between neighboring points of this smoothed data set divided by their 2D distance.
