### ISSUE TITLE
GUI improvement for adding waypoints

### ISSUE THREAD

**Issue by bitboy85** [osmandapp/OsmAnd#4555]
Last time i used osmand i tried to use waypoints and i find those are quite difficult to add. The way to do it is not obvious and also requires scrolling around the map (Search marker, tap on it, select "Add as waypoint")

Here is my auggestion how to make this more user friendly.
The additonal button opens a menu where a user can add a POI, Adress, Favorite, or map marker (colored flags) to add as waypoint before any route calculation is done. Already entered destinations and waypoints gets an additional arrow to rearange them.

![waypoint](https://user-images.githubusercontent.com/6197580/31333673-4dfa6f26-aceb-11e7-9bb2-d99b55b784c3.png)

**Comment by OpenSourceForEver** [comment]
+1

**Comment by Chumva** [comment]
It is possible to add waypoints in the new route preparation menu, just press plus or edit button - 
<img src="https://user-images.githubusercontent.com/19220417/178830404-e435286a-81c6-4f7d-bafb-4c0b161b1901.png" width="330" height="700">
