### ISSUE TITLE
TTS issue with waypoint

### ISSUE THREAD

**Issue by bitboy85** [osmandapp/Osmand#4557]
I used a waypoint to travel around a closed road. The map marker was set just somewhere on the road. (Usually osmand tries to search an adress to such a marker). As i reached the waypoint the following text was spoken: you reached waypoint adress is searched. I'm not sure about the correct translation because it was in german, but the issue should be clear.

**Comment by hakuchi** [comment]
can you give the link in OSM to the position where you set the waypoint.
I think this issue can be fixed if OsmAnd have a limit for searching a address.
So this is similar to #4288

**Comment by bitboy85** [comment]
I think it was here: https://www.openstreetmap.org/#map=18/51.31156/6.63336 on A 57
I'm not sure but is it possible that a waypoint is saved with the "name" "adress is searched" when its added as waypoint? I took me about 2 hours to reach the waypoint. I can't believe it was still trying to search the adress at this time.

**Comment by vshcherb** [comment]
Closed as related to #4288
