### ISSUE TITLE
Custom map source does not support Mapbox API

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4563]
When defining a new custom map source, nothing happens.

Screenshot:
![screenshot_2017-10-09-12-28-20](https://user-images.githubusercontent.com/20681525/31382031-fe6a6ebe-adbe-11e7-9e4a-4ff8d2e851a2.png)

**Comment by vshcherb** [comment]
Possibly Mapbox API is different than openstreetmap.org API. That issue might be related to permission or incorrect url scheme.

**Comment by tilusnet** [comment]
Can you please verify what the cause is?
The app doesn't expose any error message. Thanks.

**Comment by tilusnet** [comment]
Any updates on this please?
It would be great if the Custom Map Source feature worked.
Arguably if it only works with the openstreetmap.org API it is not really custom, is it?

**Comment by vshcherb** [comment]
I tried url like 
https://api.mapbox.com/styles/v1/cj8k1w4674ll42spo52tnjbb0/tiles/256/10/32/32?access_token=pk.eyJ1ljoidGlsdXNu - and it doesn't work, so the issue is in the url I guess.

**Comment by tilusnet** [comment]
Hi,

I regenerated the tileset.

Here's the OsmAnd URL pattern I am trying, it doesn't work:

https://api.mapbox.com/styles/v1/tilusnet/cj8k1w4674ll42spo52tnjbb0/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoidGlsdXNuZXQiLCJhIjoiY2lqZzZub29lMDAwa3YwbHdwcHdrNDRtdSJ9.GLUpQLVyLwrKcvoo3FGpXQ

To demonstrate it works, open a rendered tile for z=9, x=255, y=170:

https://api.mapbox.com/styles/v1/tilusnet/cj8k1w4674ll42spo52tnjbb0/tiles/256/9/255/170@2x?access_token=pk.eyJ1IjoidGlsdXNuZXQiLCJhIjoiY2lqZzZub29lMDAwa3YwbHdwcHdrNDRtdSJ9.GLUpQLVyLwrKcvoo3FGpXQ

Raising these again:
Can the app expose the error messages on the screen please?

Also, is OsmAnd catering for Secure HTTP (HTTPS) URLs?

Attila

**Comment by vshcherb** [comment]
Correct url is:
https://api.mapbox.com/styles/v1/tilusnet/cj8k1w4674ll42spo52tnjbb0/tiles/256/{0}/{1}/{2}?access_token=pk.eyJ1IjoidGlsdXNuZXQiLCJhIjoiY2lqZzZub29lMDAwa3YwbHdwcHdrNDRtdSJ9.GLUpQLVyLwrKcvoo3FGpXQ

It was in create example. {0}, {1}, {2}
P.s. @2x doesn't work correctly

**Comment by vshcherb** [comment]
BTW tested works correctly

**Comment by tilusnet** [comment]
You're my hero!

**Comment by rriemann** [comment]
For me it only works with Mapbox 256 px tiles, but not with 512.

Though,

- https://tile.osmand.net/hd/1/0/1.png and
- https://api.mapbox.com/styles/v1/mapbox/satellite-v9/tiles/512/1/0/1?access_token=pk.eyJ1IjoidGlsdXNuZXQiLCJhIjoiY2lqZzZub29lMDAwa3YwbHdwcHdrNDRtdSJ9.GLUpQLVyLwrKcvoo3FGpXQ

return both the same part of the map in 512px. The osmand tile url is preconfigured in Osmand. I don't understand why mabox does not work with 512px, too.

**Comment by vshcherb** [comment]
@rriemann recenlty we've fixed that issue, it used to configure in the code [tilesize], now it should work at least for sqlitedb files. If you have directory you can simply add/modify "tile_size=512" in .metainfo file

**Comment by rriemann** [comment]
> @rriemann recenlty we've fixed that issue, it used to configure in the code [tilesize], now it should work at least for sqlitedb files. If you have directory you can simply add/modify "tile_size=512" in .metainfo file

What do you mean with sqlitedb files? Are the tile APIs anyhow sqlitedb files? If not, how can this be configured for tile APIs?

In the meanwhile, I realised that while the Osmand and Mapbox tile API both deliver 512px pictures, osmand serves png files and mapbox jpg files instead. Maybe this can be the cause of the incompatibility?

Can you please open this issue again? While for some configurations mapbox is supported, there seems to be some issues for any other tilesize than 256px.

**Comment by vshcherb** [comment]
Try it with latest night build please
