### ISSUE TITLE
Wrong warning about STOP sign with direction tag.

### ISSUE THREAD

**Issue by laurentriffard** [osmandapp/Osmand#4567]
Hello, 
It seems that OsmAnd routing displays erroneous warning about STOP signs.

Let's assume : 
- we’re driving on highway A in _forward_ direction, 
- at next intersection, we have to turn in highway B, in _backward_ direction
- highway B has a STOP in forward direction (intended for drivers coming from highway B, about to cross highway A, but does not apply for us).

Then, OsmAnd display a warning about STOP sign. It should not, because the STOP sign is after the intersection, and is intended for cars coming in opposite direction.

Example1 : https://www.openstreetmap.org/node/5095826424, when coming from west Rue Saint-Théobald, and turning on south Rue du Creuzat 
Example2 : https://www.openstreetmap.org/node/5095826423, coming from south, and turning to east.

OsmAnd~ 2.7.5 from F-Droid, on Samsung Galaxy Ace II, running Android 4.4.4 (cyanogenmod 11).
- offline maps (detailed« France Rhône-Alpes », october 2017)
- in-app offline routing, car profile.

~~
laurent

**Comment by sonora** [comment]
Master issue for this is #2885, let us consolidate this there.
