### ISSUE TITLE
Can't download maps

### ISSUE THREAD

**Issue by ignaciolep** [osmandapp/Osmand#4568]
I can't download maps on Osmand stable (Play) or nightly versions.

Also the "Osmand Local Indexes List" (http://osmand.net/srtm-countries/) seems to be empty.

**Comment by cbehren** [comment]
Same problem here.

**Comment by njohnston** [comment]
Looks like it was a temporary problem. It's working again for me.

**Comment by vshcherb** [comment]
Fixed
