### ISSUE TITLE
[FAQ] Invoking osmand app from telegram bot

### ISSUE THREAD

**Issue by kirantpatil** [osmandapp/Osmand#4569]
Hi,

Usecase: We would like to use osmand android application for navigation purpose for taxi application. There by would like to contribute to osmand application and openstreetmap.

Edit: Also opentraffic project as well using osmand.

I want to open osmand app from telegram bot.

I tried below url but they are opening in browser rather than app. Those urls are opening from osmand app when they are invoked from google sms app.

1) https://www.openstreetmap.org/?mlat=13.09786862&mlon=77.5620893#map=null

2) http://osmand.net/go.html?lat=13.106962&lon=77.566299&z=

Please help me to resolve this issue.

Thanks.

**Comment by vshcherb** [comment]
```
https://osmand.net/go.html?lat=13.106962&lon=77.566299&z=18
http://osmand.net/go.html?lat=13.106962&lon=77.566299&z=18
https://www.openstreetmap.org/#map=18/53.896473/27.540071
geo:34.99393,-106.61568?z=11
```
Should be supported, we have more examples in GeoPointParserUtil file

**Comment by vshcherb** [comment]
We also have https://github.com/osmandapp/osmand-api-demo api-demo project how to integration via Intents & Background Service

**Comment by vshcherb** [comment]
http://download.osmand.net/latest-night-build/OsmAnd-API-demo.apk
