### ISSUE TITLE
Avoid Roads storage location

### ISSUE THREAD

**Issue by WindesValis** [osmandapp/Osmand#4570]
**Use case:**

We want to chance the way trucks drive inside the cities by adding extra roads to avoid. For this we need to
where the avoided roads are stored on the device so we can add more roads to it.

So where are the avoided roads stored? And can we interact with it? (SQLite database?)

**Comment by vshcherb** [comment]
Today they are stored in Settings and it is not a special database unfortunately. Most likely you would better prepare "special"  maps or may be even contribute to OSM.
Configuration of routing.xml is very flexible and supports many tags.

**Comment by vshcherb** [comment]
Because it is a question, issue will be closed
