### ISSUE TITLE
Automatic profile switch

### ISSUE THREAD

**Issue by tobydickenson** [osmandapp/Osmand#4571]
When navigating using the car profile, osmand automatically switches to the car display profile.

At the end of navigation osmand will:
1. announce "you have reached your destination"
2. pop up the end-of-nav UI panel.
3. automatically switch back to the "browse map" display profile. I find this problematic.

At this point **you are still driving**.... maybe parking, maybe looking for a house number. Swapping back to the "browse map" display profile is inappropriate because:
* zoom settings are different. The phone is still in the car dash mount at this point so you need the larger print to read street names.
* day/night settings are different. I'm not sure if I am on default or customised settings here, but swapping from the dark night-time driving display to a bright "browse map" display causes unwanted windscreen glare while parking.

I propose delaying the switch back to the "browse map" display profile until the end-of-nav UI panel is dismissed.

**Comment by scaidermern** [comment]
Another problem caused by this automatic profile switching has also been mentioned in #4533.
