### ISSUE TITLE
Quick actions - confusing icon for stopping navigation

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#4575]
version: nightly 2017-10-11

For adding the "Start/Stop navigation" action to the Quick actions button, the navigation arrow is used:
![screenshot_20171012-003537](https://user-images.githubusercontent.com/8266355/31488929-848e9b4c-af3f-11e7-9a7e-420d4b18b5bd.png)
Tha same icon is used in the quick action widget for "start". However when navigation is running, the "stop" version of the icon is the destination flag:
![screenshot_20171012-111557](https://user-images.githubusercontent.com/8266355/31489002-b894dda2-af3f-11e7-9079-136b2848a257.png)
This is confusing, since it is the same as "add destination". Also, stopping navigation does not mean I have reached any destination. It would be better to use a struck navigation icon, example:
![struck_arrow](https://user-images.githubusercontent.com/8266355/31489254-5e66527e-af40-11e7-80d8-73abdb08ac6e.png)

**Comment by scaidermern** [comment]
Or maybe a different icon for "add destination"? Like

![foo01](https://user-images.githubusercontent.com/1040784/31490350-ebb6810a-af43-11e7-95e6-d146bff16e0c.png)

or

![foo02](https://user-images.githubusercontent.com/1040784/31490356-f2c1560a-af43-11e7-9071-aad598371fcf.png)

**Comment by polarbearing** [comment]
Reviewing the other icons would be good as well, however that should be done independently of fixing the Stop Navigation icon. 

The "flag with +" is fine for "Add destination", but then all quick action that add something should get the + .

**Comment by PavelRatushnyi** [comment]
Fixed with https://github.com/osmandapp/Osmand/commit/6adc66b7b4548f90af2cc6027f422286cc5af687

**Comment by polarbearing** [comment]
Thanks a lot. Using the map-mode icons is even cooler than my idea :-)
