### ISSUE TITLE
an image of menu is still on the map screen

### ISSUE THREAD

**Issue by iriman** [osmandapp/Osmand#4577]
Hi. There is a tiny issue with location sharing.<br>
First of all, I don&apos;t have any enabled pluging.<br>
**Steps that lead to the problem:**<br>
I tap on a POI or long-tap on another location to bring up the context menu.<br>
Then tap the share button which brings up 4 choices.<br>
After tapping on &quot;send&quot;, &quot;geo:&quot; or &quot;qr-code&quot; I should choose an app or finally there will be another dialog to work with.<br>
When I&apos;m finished in that dialog, whether it is another app or OsmAnd qr-code dialog, I hit back button of my phone to back to the OsmAnd main screen.<br>
The problem is here. Now I see that &quot;share location&quot; menu is still visible, but it&apos;s not a real menu, just a picture of it. Since by tapping on it I&apos;m actually tapping on the map screen and if I remember the context menu position (3 dots on each other at right corner) I can blindly tap it and continue doing some works with OsmAnd blindly.<br>
This fake menu will remain there untill I go to home screen and then bring back the app via recent apps menu.<br>
I have tested this with:
- OsmAnd-2.7.0#22762M on my Android phone (v 6.0.1) and most of the time I have this issue.
- OsmAnd 2.7.5 (official) on Samsung Galaxy S5 and I faced this issue after viewing qr-code. tested once.

**Comment by iriman** [comment]
please whatch this clip. there is two cases which the problem is still occuring.

[osmandshare.zip](https://github.com/osmandapp/Osmand/files/1536316/osmandshare.zip)

thank you

**Comment by AlexSyt** [comment]
I can reproduce issue with bar code, but not with geo sharing.
I'll take a look.
