### ISSUE TITLE
List of gpx tracks in not available during online gpx tracking.

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4579]
Steps to reproduce:

1/ Start OsmAnd (with GPS on).

2/ Turn on GPX recording via GPX icon and select "Start GPS Logging" 
(with logging interval 5 secs and "Show on map" set).

3/ Go to My Favourites via "My Places" menu listing and click on the "My 
Tracks" tab. Previously recorded tracks will be listed properly.

4/ Back to map view and via the GPX icon select "Start online tracking".

5/ Go to My Favourites via "My Places" menu listing and click on the "My 
Tracks" tab. Tracks will not be listed and a rotating (processing/wait) 
progress bar will be shown.

**Comment by xmd5a2** [comment]
Confirmed
