### ISSUE TITLE
French TTS voice : Wrong pronunciation of some words as "Brain" or "quatre"

### ISSUE THREAD

**Issue by Rpnpif** [osmandapp/Osmand#4580]
Hello developers,

With the French TTS voice, the _Brain_ (village name) and _quatre_ words should be pronounced as respectively _Brin_ and _catre_.

- _Brain_ -> /brɛ̃/ in phonetic. [Listen](http://shtooka.net/listen/fra/brin).  In Osmand it is pronounced as in English.
-  _quatre_ -> /katr/ (in Osmand, the /a/ is too long). [Listen](http://shtooka.net/search.php?str=quatre&lang=fra) 

Regards.

**Comment by hakuchi** [comment]
this is a problem with the TTS you are using.
OsmAnd gives only the text to the TTS engine.
I think you should contact the service from your TTS engine

**Comment by polarbearing** [comment]
Not an OsmAnd issue. Can be closed.
