### ISSUE TITLE
GPX export is creating a closed way

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#4590]
After calculating a route from `-21:48.34690 -48:11.43536` to `-22:3.43963 -48:2.87627` we get this route:
![](https://user-images.githubusercontent.com/982338/31626203-9ae3a28e-b287-11e7-843e-850cb82085b3.png)

Which is correct.
But exporting it as GPX and opening it we can see this:

![](https://user-images.githubusercontent.com/982338/31626149-6b4a6ee0-b287-11e7-9e72-3fdeb6ae319c.png)

It seems that osmand is exporting it as a closed way or maybe it's exporting the proper route together with a simplified way?

Could we have the GPX exported exactly as we see in the calculated route?
Maybe this simplified route could also be exported, but as a separated track/file (ie, export 2 GPX files, being one the proper calculated route and the other one the simplified version)

The exported GPX is available here [route.gpx.txt](https://github.com/osmandapp/Osmand/files/1388485/route.gpx.txt) if needed.

osmand is nightly `2.7.0#18794D`

**Comment by xmd5a2** [comment]
OsmAnd exports route points (rtept) at the end of GPX. Some GPX viewers render them as secondary track but some not.

**Comment by vshcherb** [comment]
Nothing wrong in the gpx file itself, so it is a viewer issue
