### ISSUE TITLE
Question: Android studio setup

### ISSUE THREAD

**Issue by WindesValis** [osmandapp/Osmand#4613]
We are a group of students that want to edit OsmAnd in Android Studio. Sadly we are not able to get OsmAnd in our Android Studio envioroment. 

We put the "resources" and the "OsmAnd" into one folder (we even tried it with the core and the help). We build the project.
But evertime we build the project we get errors about missing variable. We just dont get it to work. 

![error 937](https://user-images.githubusercontent.com/32698388/31719238-0a7068da-b413-11e7-8fa8-c30063a3c684.png)

**Comment by vshcherb** [comment]
you need to check out all repositories into folders like here https://github.com/osmandapp/OsmAnd-manifest/blob/master/android_build.xml ( repo) & then you need to run gradle build first, so it copies missing resources
