### ISSUE TITLE
Outdated nightly versions?

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#4614]
Is there a problem with http://download.osmand.net/latest-night-build/ releases being outdated? Or the version numbers are not being updated, maybe?

With the latest OsmAnd-default.apk I see the version as `2.7.0#18822D`
With OsmAnd-nightly.apk the version is `2.7.0#22842M` (released on 2017-10-18)

But in http://download.osmand.net/releases/ there are higher versions in the 2.7 series (2.7.5 being the latest) and even 2.8+ versions

**Comment by sonora** [comment]
We actually only maintain the base version number in the nightlies, i.e. usually the ones ending in x.y.0. Then after the # the build number, simply incremented for each buid, per strain.

**Comment by naoliv** [comment]
So OsmAnd-default.apk and OsmAnd-nightly.apk are actually 2.7.5+?

**Comment by vshcherb** [comment]
Fixed https://github.com/osmandapp/Osmand/commit/2ec2337e791f85669cfac0705b171b3356b8cb9e
