### ISSUE TITLE
RTL display

### ISSUE THREAD

**Issue by iriman** [osmandapp/Osmand#4615]
Hi and thank you for the good job you're doing.

I've read #2841 and I also have a similar opinion and I think that there are some problems with right to left display in OsmAnd. But I think it needs more clarifications.
So I tried to describe this issue with some comparable screenshots of current LTR and RTL layouts.

The second picture in each pair is in Persian.
Because of legibility I only put links.

**- EXAMPLE 1 [Dashboard]**
As you see in screenshots below
[dashboard_en](https://user-images.githubusercontent.com/8467903/31745526-f0215afe-b46f-11e7-8c42-b56d3f3402b6.png)  **VS** [dashboard_fa](https://user-images.githubusercontent.com/8467903/31745527-f0634aea-b46f-11e7-94e8-41900011b1aa.png)
in LTR layout title of each card is placed at left and its button (text in blue) is at right side.
Now compare this with RTL layout.
In RTL, titles are pushed to the right but those blue buttons are still where they were.

Also below the title, there is card content which in LTR layout we have this order of items in a row:
Navigation arrow icon → a brief description → play and stop buttons.
Now again compare this with RTL layout.
In RTL, at begining we have play and stop buttons, then a brief description, and finally navigation arrow, which should be reversed because it is seen from right to left.

**- EXAMPLE 2 [Menu → Configure map]**
Like first example, in LTR layout we have item icon → description of item → [... (options button)] → toggle button.
But in RTL we have toggle button → [... (options button)] → description of item → item icon.
[configure_map_en](https://user-images.githubusercontent.com/8467903/31744220-dbfc6960-b46a-11e7-84ad-9b1e3435dbdb.png) **VS** [configure_map_fa](https://user-images.githubusercontent.com/8467903/31744418-87522c78-b46b-11e7-929f-45f3e20d304b.png)

**- EXAMPLE 3 [Menu → Map markers → Options]**
Notice at "distance indicator" row when display view is RTL, it sounds unsettled.
[map_markers_en](https://user-images.githubusercontent.com/8467903/31744756-fb71e0ac-b46c-11e7-916b-74741076c19e.png) **VS** [map_markers_fa](https://user-images.githubusercontent.com/8467903/31744758-fd860936-b46c-11e7-94b0-325064e80f92.png)

**- EXAMPLE 4 [Mapillary plugin]**
Here I would like you notice at "Dates" item.
In LTR, we start with "From" and then "To". Sounds natural.
But in RTL and with current layout we first will see "To" field and then "From" which doesn't sound good.
[mapillary_en](https://user-images.githubusercontent.com/8467903/31744884-911d1298-b46d-11e7-9572-0923e3301c65.png) **VS** [mapillary_fa](https://user-images.githubusercontent.com/8467903/31744885-91593fe8-b46d-11e7-8ad7-bb792089fde5.png)

**- EXAMPLE 5 [Settings → Navigation settings]**
Here, all are LTR except description of three first items.
[settings_navigation_en](https://user-images.githubusercontent.com/8467903/31745316-1378eb58-b46f-11e7-8861-229a12c49a73.png) **VS** [settings_navigation_fa](https://user-images.githubusercontent.com/8467903/31745317-13b4662e-b46f-11e7-9fdd-3514e7f3db37.png)

These examples are some samples of this issue that there is widely on other parts of the app, when we choose a RTL language like Persian, Arabic, etc. 

Android I used for screenshots is version 6.0.1.

thank you

**Comment by vshcherb** [comment]
Example 5 is controlled by Android API

**Comment by iriman** [comment]
I saw some improvements on recent nightly versions on this topic. I know it will take some time to be completely done, but you are welcome to tell me if you need any review from a native user, and I would kindly prepare some descriptive screenshots. Thanks

**Comment by vshcherb** [comment]
Most of it already fixed
