### ISSUE TITLE
Save markers into a file

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/OsmAnd#4617]
As markers are gaining importance for route planning in recent implementation, it would be helpful to save them into a file, e.g. ```markers.gpx```, in analogy to ```favourites.gpx```.

Talking about saving, it would be helpful, at least for testing purposes, to be able to save/read all app settings into a machine+human readable file, such as XML. If not for the general user interface, then in the developer settings.

**Comment by dmpr0** [comment]
Markers have "Save as Track" option, that create a gpx file from all markers.

**Comment by njohnston** [comment]
@polarbearing: you can get all the settings by using `adb backup` and then unpacking the data, for example:

```
  adb backup -f data.aab -noapk net.osmand.plus
```

And then:

```
  dd if=../data.aab bs=1 skip=24 | openssl zlib -d | tar -xvf -
```

You can then see your settings (net.osmand.plus_preferences.xml) and look at various SQLite databases for tracks, search history, ...

**Comment by polarbearing** [comment]
> Markers have "Save as Track" option, that create a gpx file from all markers.

Fine but then I'd need a method to load them. Thus I'd prefer the automatic writing/reading, as for favourites.

> get all the settings by using adb backup and then unpacking the data

Thanks for the hint. Again, having a fresh installation and populating it with my settings would get complicated, wouldn't it? As the settings are already in xml format as you write, it should be simple to have a save/load option in the dev menu.

**Comment by Loki-Afro** [comment]
Here another use case:
I have around 50 coordinates and want them to add them as Markers and mark them as passed as a I go along. unfortunately i don't see a way to import them.

There is no pre planned route for it, therefore no gpx file

**Comment by vshcherb** [comment]
Situation is changing now, in new 4.0 version there will be Backup Itinerary + Markers which generates 2 separate GPX inside OSF ( just rename to osf.zip and unpack)  which could be used later on.

**Comment by scaidermern** [comment]
> > Markers have "Save as Track" option, that create a gpx file from all markers.
> 
> Fine but then I'd need a method to load them. Thus I'd prefer the automatic writing/reading, as for favourites.

After importing the GPX file you can copy the waypoints to map markers. This will restore them.

**Comment by dbogdanov** [comment]
Hi @scaidermern, I can't find the option to copy the waypoints to map markers.

**Comment by scaidermern** [comment]
> Hi @scaidermern, I can't find the option to copy the waypoints to map markers.

Open the track, go to Points, tap on the three dots menu next to a waypoint group, select Copy to map markers.

![photo_2021-07-29_17-19-55](https://user-images.githubusercontent.com/1040784/127519084-09a55b88-3eff-46b4-94ea-b5bff40899a7.jpg)

**Comment by dbogdanov** [comment]
Thank you.

I see, this still results in the issue described in #12310. The copied points are waypoints, not markers, so they have different icons.

**Comment by dmpr0** [comment]
Markers have the option **Save as track file** and they also could be exported using the **Back up as file** option.
