### ISSUE TITLE
Performance issue with latest version

### ISSUE THREAD

**Issue by mathstuf** [osmandapp/Osmand#4619]
What version of OsmAnd are you using, on what device and Android/iOS version?

Nexus 5X with OsmAnd 2.7.5 from F-Droid on Android 8.0.0.

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

Offline.

Performance when browsing the map has tanked in the latest version. It's laggy enough that a simple drag is interpreted as a long press. This makes it very hard to use.

Unfortunately, trying to install older versions (2.6.3 and 2.6.5) are failing. I'll have to backup the app preferences before I do a full uninstall/reinstall to test the older versions. It may be Android 8.0.0 as well; that upgrade happened in between the last time I was using it and when I noticed the preformance regression.

**Comment by njohnston** [comment]
Duplicate of #4323. Fixed (mostly; zoom performance requires an update to Android itself) and will be released in 2.8 which is due very soon.

**Comment by mathstuf** [comment]
Cool, thanks. I had missed it since I searched for "performance", not "slow". I've subscribed to that issue.
