### ISSUE TITLE
When touching a multipolygon, Osmand does not show any contact info

### ISSUE THREAD

**Issue by dan980** [osmandapp/Osmand#4628]
When touching a multipolygon, Osmand does not show any contact info (phone, email, facebook, opening hours). Only the name.
It does not matter if the info is tagged using the contact:tag scheme or not.

If you use the search feature instead, and select the POI that way, all the contact info gets displayed. 

I tested this beaviour on iOS (Osmand 1.3.2)

check out this examples:

http://www.openstreetmap.org/relation/3725540
http://www.openstreetmap.org/relation/4264134
http://www.openstreetmap.org/relation/3944480

**Comment by aceman444** [comment]
I think on multipolygons many other tags are not shown correctly in the details slide-out.

**Comment by vshcherb** [comment]
@crimean  Proposed solution here is to identify by id that object is a multipolygon (we have that check when we are showing OSM url) and lookup in POI structure not by id but by name
