### ISSUE TITLE
Wrong-way routing on I-75

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#4629]
What version of OsmAnd are you using, on what device and Android/iOS version?

OsmAnd night build 2.7.0#22821M dated 2017-10-16, on Samsung Galaxy S4, Android 4.2.2 (AT&T baseband version I337UCUAMF3)

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

OsmAnd offline maps

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

Your US Georgia map dated September 30, 2017.

__*In case of wrong routing:*__

Tell us whether you have used OsmAnd's in-app offline routing, or any online routing provider like YOURS, OpenRouteService or OSRM.

OsmAnd's routing.

What routing profile is choosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest)

Car profile, with no route modifiers selected (e.g., not using "fuel economy" or "avoid motorways").

Please specify as exactly as possible the start and end point of your route by telling us city name and street name so that we can find it via in-app address search easily. Also a permalink from openstreetmap.org can be helpful.

Tell us your expected routing, and how OsmAnd routes, or add screenshots here.

Preface:  OsmAnd was reporting fast-route generation errors and other error messages.  

I started here: https://www.openstreetmap.org/way/375026096

I tried to put an intermediate waypoint on GA 20, but OsmAnd started throwing fast-route calculation errors and other errors at me, so I finally just removed it.  It might be because the marker wasn't *quite* on GA 20.

After removing that waypoint, OsmAnd finally did calculate a route.  However, I intentionally ignored OsmAnd's directions because I wanted to drive around the west side of Cartersville, Georgia, to get some GPS traces of new road construction.  (This is why I tried to place a waypoint, so it would direct me that way.)

After circumnavigating Cartersville, I got on I 75 here:  https://www.openstreetmap.org/way/440065111

OsmAnd kept trying to direct me off of the interstate and route me to my destination via non-motorways, even though staying on the Interstate was the fastest (and in the past, it has directed me that way).

When I got to Wade Green Road, I got off the freeway intentionally (at this junction https://www.openstreetmap.org/node/67552359 ) in order to get GPS traces of the new road configuration there (which I'll started editing into OSM soon).  I went south on Wade Green Road, turned around just south of the freeway area, and went north, then turned around at the pharmacy just north of the freeway and went south again, so I could get back on the freeway and resume my journey.  During this last southbound part is when OsmAnd directed me to go down the freeway exit ramp the wrong way, and onto the northbound lanes of I 75 to go south!

Here's the exit ramp it wanted me to drive down:  https://www.openstreetmap.org/way/437893460

Because I had to stop at a traffic signal, I was able to get screenshots showing the routing.  I'm uploading them full-size so you can see the details better.  If you want smaller versions, let me know.

I will note that this is not the first time OsmAnd has tried to direct me to drive the wrong way on a one-way road; this just happens to be the first time that I was stopped and able to get screenshots, and to be sure exactly where I was when it happened.  (The previous times were returning from Blue Ridge, Georgia, driving down GA 515, and at various places where there were turn lanes, it would try to tell me to turn left then right to drive south on the northbound lanes.  It's just that at 65 mph, I can't really take screenshots, and wasn't able to make notes about where it happened.)  So the problem isn't limited to this night build; it goes back a few months.  It is very rare, however.

I would prefer not to post my destination for privacy reasons, but I can e-mail it to you if you want.  (Although, I suspect that the exact destination might not matter for this....)

![screenshot_2017-10-21-19-10-14](https://user-images.githubusercontent.com/11140831/31856899-853ecaee-b69c-11e7-9b96-ee802a36264c.png)
![screenshot_2017-10-21-19-10-32](https://user-images.githubusercontent.com/11140831/31856902-89731e44-b69c-11e7-880c-3f729f31a43f.png)

**Comment by vshcherb** [comment]
Tested on latest maps and it is not reproducible. Please update maps.

**Comment by jfburke3** [comment]
I *am* using the latest maps.  As I mentioned, wrong-way routing has happened before, on other highways, in the past.  It is very rare, but it has happened before.
