### ISSUE TITLE
[Bug] German special characters in german maps not used.

### ISSUE THREAD

**Issue by Thunichgud** [osmandapp/Osmand#4630]
The german special characters äöüß are very often not used in the german maps. This happens at street names, stream names, town names and other objects with names or descriptions. 
E.g.: Butzow instead of Bützow (town), Altotting instead of Altötting (town), Gollstrasse instead of Göllstraße (street), Muhlenfliess instead of Mühlenfließ (stream).
At names of larger towns like München, Köln, Lüneburg the correct german special characters are used.
In OpenStreetMap all object names are written with correct german special characters, so it must be a problem of Osmand.

**Comment by sonora** [comment]
Please zoom in to double check. I think you may be too far out and actually  be viewing the data from the world overview map?

**Comment by Thunichgud** [comment]
I did zoom in - up to highest level and I changed the font size up to 300 % - No change.

**Comment by polarbearing** [comment]
Have a look at #3849 if that describes your problem. Otherwise provide a screen shot please, and the OSM loacation to compare. It has nothing to do with font size. Do you have the data for the Bundesland loaded that you zoom into?

**Comment by sonora** [comment]
Just tested looking at München - works for me. Are you sure you map langusge is set to local names?  Could you provide a screenshot?

**Comment by vshcherb** [comment]
Most likely the system language is English that's why on the basemap it displays English name. So it is a duplicate issue.
