### ISSUE TITLE
[Feature request] Easier Way to calculate a route with intermediate destinations

### ISSUE THREAD

**Issue by Thunichgud** [osmandapp/Osmand#4634]
There is no easy way to calculate a route with intermediate destinations. The actual method is rather circumstantial.
Because of that, in the navigation settings screen should be a (+) button which inserts an edit line for entering a intermediate destination with the options of selection from "Favorite", "Mark on map" or "Address".

**Comment by njohnston** [comment]
Possible duplicate of #4555.

**Comment by vshcherb** [comment]
Short answer, yes it is in a roadmap for next version. Closed as duplicate
