### ISSUE TITLE
Performance improvement by replacing AsyncTask.execute

### ISSUE THREAD

**Issue by frankFic** [osmandapp/Osmand#4636]
Hi,

I found that AsyncTask.execute is used in many places in OsmAnd (like in [ReportsFragment.java](https://github.com/osmandapp/Osmand/blob/564a8662b3899d008635c0c8cad8a21f454399e7/OsmAnd/src/net/osmand/plus/liveupdates/ReportsFragment.java), [AvailableGPXFragment.java](https://github.com/osmandapp/Osmand/blob/a2e513285f1a88c38844e314082ff71d3da24742/OsmAnd/src/net/osmand/plus/myplaces/AvailableGPXFragment.java), some methods starts more than one AsyncTask). The behaviour of this API has changed since API 11 and from there, tasks started by this API will be executed on the same thread. Replacing it with `executeOnExecutor` may improve the performance by running the tasks in real multiple threads.

By the way, I also found `executeOnExecutor` is already in use at some places. At some places, there's an API-level check before invoking the API (like [here](https://github.com/osmandapp/Osmand/blob/ba04890f443f9e8c533b9b3c8d001e815d5b6f74/OsmAnd/src/net/osmand/plus/GeocodingLookupService.java#L121)). However, this is no longer needed as the minSDK is 14 (I read this info from OsmAnd build.gradle, if the minSDK is not read from the environment variable) If you suppose minSDK could be lower than 11, some call sites of `executeOnExecutor` may crash like [here](https://github.com/osmandapp/Osmand/blob/d687b02eadd39bb07e814ba1430c53d124460f4b/OsmAnd/src/net/osmand/plus/liveupdates/OsmLiveActivity.java#L71).

Hope I did not make any mistakes. :)

Thanks.

**Comment by PavelRatushnyi** [comment]
Fixed with https://github.com/osmandapp/Osmand/pull/4637
