### ISSUE TITLE
Osmand Startup: Wait for SD to mount

### ISSUE THREAD

**Issue by bitboy85** [osmandapp/Osmand#4640]
I have a chinese Android head unit in my car car and noticed the following:
the HU starts automatically the last app used, this is sometimes osmand. But then osmand shows the "First steps" Screen, and asks for storage for the maps. If i close osmand, wait a few seconds and start it again, it works fine.
My guess is that osmand is startet first / faster than the sd card is mounted.
Any chance to improve this behaviour? As said, ist easy to work around so ist no important "bug".

**Comment by vshcherb** [comment]
It would be hard to workaround though you don't need to close application I think. May be you can press button "SKIP"

**Comment by bitboy85** [comment]
Hi, i've tried skipping but then it shows no map.

**Comment by bitboy85** [comment]
With osmand 2.9 this issue seems to be gone. Maps / SD is detected immediately.
