### ISSUE TITLE
The symbol for unlimited parking amd restricted parking time is now confusing.

### ISSUE THREAD

**Issue by frankFic** [osmandapp/Osmand#4642]
Hi, I found `android.text.format.Time ` is used in [ParkingPositionPlugin#getFormattedTime](https://github.com/osmandapp/Osmand/blob/2c2d4fcc303b6ee057cb1d19c2e8be3a08c759e0/OsmAnd/src/net/osmand/plus/parkingpoint/ParkingPositionPlugin.java#L547). This class has been deprecated due to multiple problems ([API guide](https://developer.android.com/reference/android/text/format/Time.html)). As suggested by the document, an alternative for this class is [GregorianCalendar](https://developer.android.com/reference/java/util/GregorianCalendar.html).

**Comment by pebogufi** [comment]
I can confirm that parking plugin with time based warning does not work at all.
Confusion of 12h timeshift or somerhimg else by using a 24h system.
Do you need a detailed test report ?
regards Peter

**Comment by vshcherb** [comment]
@pebogufi Yes please describe here the details, the bug will definitely increase priority for that issue.

**Comment by pebogufi** [comment]
I am sorry, I mixed up time of duration of parking with end time of parking. So this is ok.
--
A minor "bug" may be, the symbol for unlimited parking amd restricted parking time is now somtimes confusing. If I change portrait view to landscape and vice versa, first it may be wrong and after turning it may change and is then ok.
But after some tests I can only tell you, that it is confusing and SOMETIMES wrong. 
Peter

**Comment by AlexSyt** [comment]
At the moment we will not change the method or icons.
