### ISSUE TITLE
OsmAnd Nightlies crashes shortly after start

### ISSUE THREAD

**Issue by CJTmmr** [osmandapp/Osmand#4644]
Since about Yesterday the Nightly's always crash shortly after start, sometimes even before the map is rendered.
I guess related to commit #4637
this is the [exception.log](https://www.dropbox.com/s/u232dzyuzwdelpq/exception%202017-10-24.log?dl=0)

On Samsung Galaxy Camera2 EK-GC200; running Android 4.3

Good Luck and thanks for investigating

**Comment by mase76** [comment]
I have a similar crash on an Xperia X with Omnirom 7.1.2. Osmand is 2.8.2 from F-droid.
