### ISSUE TITLE
Incorrect direction of movement in the offline map 

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4650]
Location: http://www.openstreetmap.org/#map=18/36.70824/29.04129

The road is correct in OSM, while it has the incorrect direction in OsmAnd. This causes issues with navigation.

Screenshot:
![22906630_1933020713611400_474482865_o](https://user-images.githubusercontent.com/20681525/32098286-e1f120f8-bb14-11e7-9123-2fdae8094502.png)

**Comment by vshcherb** [comment]
We need somehow to rebuild the map but this is not clear how to do.
