### ISSUE TITLE
Chinese name variants in German map language

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4651]
If the display language is German and the street names also in German (with transliterate), then Chinese names appear in every zoom. Disabling the transliterate the street names will be given in their local names (Kanji). But then, while zooming out, the prefecture names and city names are written as Chinese characters. 
In English is everything ok. (the English screenshots made with English display language) But, setting the display language to German and the street names in English (transliterate enabled) only the street names are correct. The prefecture and city names will be written in Chinese characters.

Screenshots:
eng
![1 _english 1](https://user-images.githubusercontent.com/20681525/32100722-942043c8-bb1d-11e7-85ad-835ea1bfb178.png)
ger
![1 _german 1](https://user-images.githubusercontent.com/20681525/32100723-943adfa8-bb1d-11e7-86af-a7f70727064a.png)
eng
![2 _english 1](https://user-images.githubusercontent.com/20681525/32100724-94563438-bb1d-11e7-8e7b-fc8b6230573e.png)
ger
![2 _german 1](https://user-images.githubusercontent.com/20681525/32100725-94720b86-bb1d-11e7-96f1-401eab0e72c9.png)
eng
![3 _english 1](https://user-images.githubusercontent.com/20681525/32100726-94a86c26-bb1d-11e7-8675-32a8f08c47ed.png)
ger
![3 _german 1](https://user-images.githubusercontent.com/20681525/32100727-94c32016-bb1d-11e7-9499-47e23d53f2f8.png)

**Comment by aceman444** [comment]
Do you really mean Chinese language, as your screenshots are from Japan.

**Comment by PaulStets** [comment]
Yes, that's the problem. Chinese names are displayed for the cities in Japan when the Display language is set to German.

**Comment by vshcherb** [comment]
Duplicate issue https://github.com/osmandapp/Osmand/issues/3738
