### ISSUE TITLE
Routing uses the wrong primary_link

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4652]
http://www.openstreetmap.org/#map=19/40.45520/15.01637

![screenshot_2017-10-26-16-16-34](https://user-images.githubusercontent.com/20681525/32101752-26833898-bb22-11e7-941c-88e77c46bca7.png)

**Comment by scaidermern** [comment]
There are turn restrictions missing in the map data. I've added them (https://www.openstreetmap.org/relation/7685849 + https://www.openstreetmap.org/relation/7685848). 

Can be closed.

**Comment by PaulStets** [comment]
Many thanks for the correction.
