### ISSUE TITLE
Wrong subway line color

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4654]
The London Hammersmith & City line (http://www.openstreetmap.org/relation/7666924) has a pink color with #f491a8 (https://www.w3schools.com/colors/colors_picker.asp?color=f491a8) set correctly in the data. 
In the Transport Layer (for subways) however, this line shows as plain red. All other lines are displayed correctly. 

![image](https://user-images.githubusercontent.com/20681525/32109582-d9752eb4-bb3d-11e7-858a-6264caa747ae.png)

**Comment by xmd5a2** [comment]
We use colour simplification and pink is not among our colour set for this purpose.

**Comment by tilusnet** [comment]
Thanks for the answer.
Why not sticking with a single colour instead?
I find it misleading that line colouring applies partially.
In this case I'd assume that everything red is the Central Line.
If everything would be a single colour throughout (e.g. red) I wouldn't
make such assumption.

**Comment by contrapunctus-1** [comment]
Same problem in Delhi Metro's Violet Line, displayed as brown instead of violet. 🙁 Can anyone please say why this issue was closed, if it has not yet been fixed and a fix is planned?

**Comment by xmd5a2** [comment]
@contrapunctus-1 this is incorrect tagging. colour should be #9400d3, not 9400d3

**Comment by contrapunctus-1** [comment]
Ah, I wasn't aware of that. Fixed, sorry for the noise.
