### ISSUE TITLE
Feature request : make osmand zoom as fluid as the browser version of openstreetmaps.com

### ISSUE THREAD

**Issue by Sgt-Miller** [osmandapp/Osmand#4655]
Zooming in the browser is so fluid.
Zooming in osmand is awkward - the roads and other features load one by one, and the result looks like a old design. Of course, not a priority, but would be grateful if someone would look into it!

**Comment by scaidermern** [comment]
This depends mainly on your device hardware. OsmAnd needs to render the map on the fly whereas your browser just needs to download pre-rendered tiles. These are two very different mechanisms.

**Comment by sonora** [comment]
And map appearance can be chosen to your needs via setting "Configure map / Map style". Another feature you cannot have with pre-rendered maps. :)

To get what you want you can simply use OsmAnd with tile maps, enable the Online maps plugin for that. Tiles could be online or cached.

**Comment by vshcherb** [comment]
Not much could be done in the nearest future
