### ISSUE TITLE
Storage leak when updating maps

### ISSUE THREAD

**Issue by rdoeffinger** [osmandapp/Osmand#4656]
When updating maps, the available storage decreases more and more.
When rebooting or force-closing the app, suddenly more storage is available again.
This makes updating a large number of maps a very tedious process of downloading some updates, force-closing the app and repeating.
The behaviour suggests that after an update the old version of the maps are still around and open.
I do not know which code handles updates, but it needs to make sure to not clean out all references to the old map data, and in addition it must ensure to explicitly close all file handles (or, as a hackish and strongly not recommended method, forcing a gc pass might help).

**Comment by sonora** [comment]
Just restarting the app should help ... naturally you want to keep the old maps available until downloading the new ones has successfully finished, or else you may be left without map if anything gets stalled.

**Comment by rdoeffinger** [comment]
You misunderstood. The old maps will be around indefinitely, at least 10 minutes and more (but probably forever, but I haven't specifically tested that) after the updates have been downloaded and installed!
In particular, they will be around even after the files are no longer visible/have been overwritten on the file system, so tools like DiskUsage are not even able to pinpoint the issue.
This is typical of a file handle leak.

**Comment by rdoeffinger** [comment]
(In case you are more used to Windows: on Linux and Android it is perfectly possible to delete a file that is currently in use. That results in the directory entry being deleted so that the file is no longer visible, but it will still use up disk space until such time that the file has been closed by all its users. Everything points to that being what happens here)

**Comment by rdoeffinger** [comment]
As to "restarting", just returning to the home screen and touching the OsmAnd icon again to "restart" it DOES NOT help. You really have to force the app out of memory, e.g. via right-swipe in the app list or the "stop" in the app list etc. to get the space back.

**Comment by vshcherb** [comment]
That doesn't seem to be an OsmAnd issue. True in Linux systems the file will stay until it is used. Proper restart is helping to get the space back.
The issue doesn't seem to be very critical though.

**Comment by rdoeffinger** [comment]
This is absolutely classic resource leak and it is about as clearly a OsmAnd bug as it can be.
The Linux/Android behaviour means you are actually lucky, on an OS/file system with mandatory locking your update mechanism would be utterly broken, since it would be unable to delete/replace the old file and thus would fail to do any updates at all.
It is also a usability nightmare: if you have 10GB of maps (after decompression, so not download size) and e.g. 1 GB free this bug means you can update a handful of maps, then OsmAnd runs out of storage and you have to kill it, then you have to start the update again etc, overall at least 10 times.
And this is only after you figured out that what you need to is kill the OsmAnd app, for which a normal user will have no indication at all. It took me a good 6 months to figure out what happens, as any file explorer shows the old files as deleted, and I assumed Android was messing up.
I also don't understand your hurry to close issues, it makes reporting bugs here feel like pulling teeth and very antagonistic and I don't see what benefit you get from it. If people are discouraged from reporting things here where a proper discussion is possible they'll just report it on the play store instead and that is worse for just about everyone.

**Comment by rdoeffinger** [comment]
I am travelling so I don't even have an Android compilation environment set up, but I wonder if maybe what is missing is to close all files that need re-indexing before starting the re-index step:
`
--- a/OsmAnd/src/net/osmand/plus/download/DownloadIndexesThread.java
+++ b/OsmAnd/src/net/osmand/plus/download/DownloadIndexesThread.java
@@ -580,6 +580,7 @@ public class DownloadIndexesThread {
                                if (f.getName().endsWith(IndexConstants.BINARY_MAP_INDEX_EXT)) {
                                        vectorMapsToReindex = true;
                                }
+                               manager.closeFile(f.getName());
                        }
                        List<String> warnings = new ArrayList<String>();
                        manager.indexVoiceFiles(this);
`

**Comment by rdoeffinger** [comment]
Maybe manager.close() would be better and safer in fact, since as far as I can tell we always re-index and add to the lists all files, even the unchanged ones, and it looks to me like they would end up multiple times in the index?
Can't say I understand the code though, the low number of comments not helping much.

**Comment by vshcherb** [comment]
Thanks for the code provided & the pull request created!

**Comment by rdoeffinger** [comment]
That looks like a better solution, thanks!
If I'm pedantic, the closeFile potentially should happen before the remove, at least then the code would be robust to work on file systems with mandatory locking (i.e. where you cannot delete open files).
But admittedly that is rather theoretical issue, Android won't ever implement that behaviour I am quite sure.
