### ISSUE TITLE
Wrong TTS announcements for roundabout using YOURS

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4658]
OsmAnd announced "slight left, then slight right" for this roundabout: https://www.openstreetmap.org/way/4451565 and also for another one on that route. It totally ignored entering the roundabout but thought the curve was "slight left" and the exit was "slight right".

**Comment by sonora** [comment]
Can you check the routing instructions you received from YOURS here, just to rule out that YOURS does not support roundabouts in their instructions.

**Comment by mbirth** [comment]
I tried a short route from Beutersitz to Riesa and the roundabout above doesn't even show up in the instructions. As if it's not there.

But when routing from Borken to Beutersitz, there's this roundabout: https://www.openstreetmap.org/way/252911095#map=19/51.69599/13.24893 and there, OsmAnd says "slight left" and "slight right".

![screenshot_20171028-213228](https://user-images.githubusercontent.com/130302/32137837-d7330af0-bc27-11e7-97e4-7e818d2938b9.png)

![screenshot_20171028-213232](https://user-images.githubusercontent.com/130302/32137840-e0491062-bc27-11e7-89f5-b80d0b750158.png)

**Comment by sonora** [comment]
Looks to me like YOURS only provides turns, but no info about roundabouts.

**Comment by vshcherb** [comment]
Yours is not properly supported for these details
