### ISSUE TITLE
Mention if the seven free downloads includes updates or not

### ISSUE THREAD

**Issue by jidanni** [osmandapp/Osmand#4661]
The First Use section, and all other documentation, should mention if the seven free downloads include updates of those downloads too.
For instance the user downloads Taiwan. He is only interested in Taiwan. He worries that if he upgrades Taiwan once a month, then after 7 months he can no longer use the app. Or at least upgrade the map.

**Comment by aceman444** [comment]
Yes, in the past updates counted towards the limit. I agree this should be noted in the docs.

**Comment by sonora** [comment]
Fixed, I guess this is what you mean: https://github.com/osmandapp/Osmand/commit/123bc08758834946b21b052fa0045058b05d68d0

**Comment by jidanni** [comment]
Thank you. It now reads
"This free OsmAnd version is limited to %1$s map downloads (including update downloads) "
To me this means: If I download Taiwan once, and then update it N times, I can no longer update it.
Is that what you mean by this wording?

I thought you meant nowadays the limit is I can download only N countries, but then update them all forever.

**Comment by jidanni** [comment]
You will need to add an example, otherwise half of the readers will interpret it one way, and half the other.

**Comment by sonora** [comment]
I added this commit, just named it wrong: https://github.com/osmandapp/Osmand/commit/89b19a95b2a528ca3dc78fd9f6a3865c35324345

**Comment by jidanni** [comment]
Perhaps say
```
Updating current maps as well as downloading new maps both count against this total.
```
