### ISSUE TITLE
Missing Turn right

### ISSUE THREAD

**Issue by bitboy85** [osmandapp/Osmand#4666]
This issue might be related to https://github.com/osmandapp/Osmand/issues/3665 but i'm not sure. At this place https://www.openstreetmap.org/edit#map=19/52.44062/7.08363 coming from west and going to south, there is no turn right advice.
As far as i can say the mapping seems correct, maybe someone with more experience can have a look at it.

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/33526190-ea87f5b8-d845-11e7-8546-cb22d7969afe.png)
Not reproducible

**Comment by bitboy85** [comment]
Hi,
i meant this way
![missingright](https://user-images.githubusercontent.com/6197580/33549647-82fff80e-d8eb-11e7-8a33-e7e1ed1f3641.PNG)

**Comment by PaulStets** [comment]
@bitboy85 Sorry, but I could not reproduce the issue with the way you specified. Could you please send the exact location of the start and the end of the route that ignores this road? Also, please try performing a clean install of OsmAnd (don't forget to backup the Android/data/net.osmand.plus folder) and see if it helps.
![screenshot from 2018-01-20 18-18-42](https://user-images.githubusercontent.com/20681525/35280770-de924f88-0059-11e8-9634-f4c7d463f947.png)

**Comment by bitboy85** [comment]
Hi PaulStets, the drawing on the map during navigation is correct, but at this place, the lane assistant shows "go through" and there is no spoken "turn right in x meters"
