### ISSUE TITLE
POI names displayed though POIs turned off (probably bug)

### ISSUE THREAD

**Issue by gery-de** [osmandapp/Osmand#4670]
Posting this as issue after comment from Peter B on 29.10.2017 in 
[https://groups.google.com/forum/#!topic/osmand/Md5DzLLKPwA](url)
that this probably is a bug: 
Though all POIs are disabled, the POI names are still displayed (when I zoom in close enough). This should not be. 
**Issue in more detail:** 
Under Configure map/POI all POIs are disabled. 
Under Configure map/Hide the 'POI icons' are still active. Then I have <Screenshot_POI Icons ON.png>
![poi icons on](https://user-images.githubusercontent.com/33235059/32194390-8c1c1518-bdba-11e7-90c7-aca5031c19c5.png)

Now I deactivate the 'POI icons' under Hide. I still get the POI texts as in <Screenshot_POI Icons OFF.png>
![poi icons off](https://user-images.githubusercontent.com/33235059/32194403-9856f9ec-bdba-11e7-9db5-f661a32c6b64.png)

**Info on versions** (though does not seem to be dependent on these):
OsmAnd+ 2.8.2
Offline map Germany_hessen_europe.obf from 28.10.2017
Android 6.0.1

**Comment by sonora** [comment]
Probably did not disable Configure map / Point labels?

**Comment by pebogufi** [comment]
Is it intended to show poi names without poi symbols ?

**Comment by xmd5a2** [comment]
This is how "POI icons" in "Hide" category works. It is intended to use with POI layer without point labels option. If you don't need it - just don't use.

**Comment by gery-de** [comment]
**@sonora**: No, Point labels were disabled. It looks the 'Point labels' option refers only to the "always orange" POIs that I can enable under 'Show - POI…'. Why is it then not located inside that menu? 
When I enable these point labels then it looks fully silly, see this screenshot: 
![poi icons point labels on](https://user-images.githubusercontent.com/33235059/32488396-babf273c-c3ac-11e7-934f-fad31963841c.png)

**@xmd5a2**: Can you please explain the rationale why "Hide" works this way? Hiding the icons and keeping the texts makes no sense to me. 
Further, I still do not see how I could disable all the unwanted POI stuff. Am I forced to see that Google-like advertising of shops in OsmAnd?? Would very disappointing…

**Comment by sonora** [comment]
Now I see what you mean. Yes "Configure map / POI labels" only relates to the POI overlay, while our "Hide" menu relates to things which are integrated contents of the map.

And there is true, as Leonid says that "Hide / POI icons" does exactly what the menu item promises: It hides the icons only. This is needed e.g. in city areas where lots of POI icons would otherwise completely obscure the street layout. (A similar obstruction cannot happen by the POI labels, as we have a mechanism which limits text display and avoids text mutually overlapping.)

So the remaining question is, do we need a menu item "Hide / POI labels", in analogy to how we do it for the POI overlay. Really not sure here, I personally never missed that. I guess we should **not** automatically hide icons **and** labels using the existing "Hide / POI icons" item, because this would inhibit people detecting **any** POIs (even after zooming in sufficiently far) who have no choice but use the to use the "Hide POI icons" feature (e,g. in downtown Lisbon) because of the obstruction problem.

**Comment by gery-de** [comment]
@sonora: Good hints in your reply, helps me to understand why it is this way. 
> do we need a menu item "Hide / POI labels", in analogy to how we do it for the POI overlay ? 

I would rather call it consistency. As many functions as Osmand has, users will get confused or lost if they are not consistent. And obviously only few people understand how it works with POIs (otherwise the google group posting mentioned on top would have had a different result). 
I plead for a "Hide / POI labels" (in some way) for consistency with

- the POI overlay (as you say)
- other options to Hide unwanted details (like e.g. buildings, house numbers)

Still my comment on the POI (overlay) menu items in Configure map: 
You call it "POI overlay" and it gives an idea what is behind. Then in "Configure map - Show" it should also better be "POI overlay" instead "POI…". 
Since the "Point labels" refer to POI overlay only, they should better be inside that menu (or otherwise directly after "POI overlay" - instead of after "Transport" - and name "POI overlay labels" would be better than "Point labels").

**Comment by pebogufi** [comment]
I fully support the idea of gery-de.
Peter

**Comment by vshcherb** [comment]
The issue is a bit cumbersome. Indeed it feels the expectation is to hide POI rather than hide POI icons, I feel they need to be hidden both. So in that case we better fix the reported issue & change the label.

I think the idea is to clean the map from labels except house numbers.

**Comment by gery-de** [comment]
> it feels the expectation is to hide POI rather than hide POI icons
Thanks to sonora's earlier comment I understand why the current Hide 'POI icons' hides the icons only and not the POI labels. Think this should stay unchanged. 
> I think the idea is to clean the map from labels except house numbers
Wondering why you mention house numbers. Main point is to have some way to hide the POI labels, think best by a new Hide checkbox 'POI labels' (which does not affect the POI icons).

**Comment by xmd5a2** [comment]
I've added "Hide POI labels" option. It affects only POI which have an icon because it is difficult to say are some objects like landuse=residential POI or not.
https://github.com/osmandapp/OsmAnd-resources/commit/35e6b68305eac149f1130ce19aa02822828b5ac5
