### ISSUE TITLE
Wrong ETA when following GPX route and going out of it.

### ISSUE THREAD

**Issue by bagage** [osmandapp/Osmand#4675]
What version of OsmAnd are you using, on what device and Android/iOS version? **Android 3.0.0**
Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps? **Offline maps: France Rhones Alpes from 1st October 2017**

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

__*In case of wrong routing:*__

Tell us whether you have used OsmAnd's in-app offline routing, or any online routing provider like YOURS, OpenRouteService or OSRM. **Using OsmAnd in-app offline routing**

What routing profile is choosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest) **bike**

Please specify as exactly as possible the start and end point of your route by telling us city name and street name so that we can find it via in-app address search easily. Also a permalink from openstreetmap.org can be helpful. 

Tell us your expected routing, and how OsmAnd routes, or add screenshots here.

**If, while following some GPX route, you go outside of it, OsmAnd recompute directions (to join the GPX route again) and update the ETA / distance which is good. However, as I experimented lately (related to #4674), sometime the ETA is going to 0 minute even if just before you were 30 min left.
I recorded a video of this since it might be clearer: https://streamable.com/pz0fm**

[<img width="341" alt="image" src="https://user-images.githubusercontent.com/1451988/32251803-f17dfe02-be92-11e7-8911-c7f4758208e3.png">](https://streamable.com/pz0fm)

**Comment by scaidermern** [comment]
This is a duplicate of #3807.

**Comment by bagage** [comment]
Indeed, thanks @scaidermern for the info. I'll close that one then!
