### ISSUE TITLE
Corrupted favorites db inhibits app start

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#4676]
I sometimes use OsmAnd to temporarily import large GPX files (with several thousand wpt) into Favorites, then edit group names or display color. 

Every once in a while I believe the favorites db gets corrupted if these operations take very long like several minutes. (This seems especially true when changing the Category name for a favorites group containing a large number of POIs, maybe there is a glitch with that particular operation. Changing the e.g the POI color usually works ok and much faster). OsmAnd then stops responding after say 5 minutes.

After a restart, it will never open again, just saying "Unfortunately OsmAnd has stopped" pon any start attempt, with no log file is generated. The only thing that helps is deleting all data via Android-Settings / App manager.

I guess we should, with the advent of sites making POIs available as GPX files with potentially many hundred or thousand waypoints, try to capture corrupt db states and rather delete a corrupt db than risking OsmAnd becoming unusable for the users, or having the user delete all their data or having to un-install/re-install?

**Comment by sonora** [comment]
Also: when I tap on a GPX file in a file manager app, then select OsmAnd to process it, and then in the OsmAnd dialog which pops up select to import to Favorites, OsmAnd imports all waypoints to both Favorites and Map markers. Not sure that is intentional?

**Comment by AlexSyt** [comment]
Hello, @sonora 
Can you please share GPX that crash the application? I can not repeat this issue.

**Comment by sonora** [comment]
Alexander, I have sent one to Victor, as I could not find your PM / email address for now, ok?
Best, Hardy.

The way I could reproduce is: Tap on the GPX file, import to OsmAnd as Favorites, then in Osmand/MyPlaces change the Favorite category name ...

**Comment by AlexSyt** [comment]
Ok, thank you.
"Tap on the GPX file, import to OsmAnd as Favorites, then in Osmand/MyPlaces change the Favorite category name ..." - this works fine with my gpx files. 
I will try this with your gpx.

**Comment by sonora** [comment]
Yes, it works perfectly with smaller files - I think the really big files seem to be the issue ...
