### ISSUE TITLE
Flooding in the map of Taiwan

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4678]
Location: https://www.openstreetmap.org/#map=16/25.1066/121.8263

![screenshot_2017-10-27-14-49-41](https://user-images.githubusercontent.com/20681525/32268424-b27d71e6-bef7-11e7-9bff-2902c565a563.png)

**Comment by idenkov** [comment]
This is not a issue for me - tested on two devices on Osmand+ and regular.
Usually such rendering errors are wrong tagging in OSM, so better go check the map at osm.org before adding it as issue here.

![](mtp://[usb:001,005]/Phone/DCIM/Screenshots/Screenshot_2017-11-22-18-04-13.png)
