### ISSUE TITLE
Lake disappears on 20 m zoom

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4680]
Location: http://www.openstreetmap.org/#map=18/49.52750/29.93772

Screenshots:
![screenshot_2017-11-01-14-55-22-867 1](https://user-images.githubusercontent.com/20681525/32278480-8ba295b6-bf1e-11e7-91ed-e9d6e023f870.jpeg)
![screenshot_2017-11-01-14-55-30-209](https://user-images.githubusercontent.com/20681525/32278481-8bc43bc6-bf1e-11e7-816f-b5d2224c8c8e.jpeg)

**Comment by idenkov** [comment]
On osm.org this is tagged as basin, and others are as water. Also it have wrong relations with inner grass I believe. This is osm.org tagging/editing error more than a OSMand bug, so it needs to be edited in OSM to be rendered properly.

**Comment by pasharm** [comment]
Yes, there was an error in the card itself. Already fixed errors, tags. You can close it.

**Comment by PaulStets** [comment]
Thanks.
