### ISSUE TITLE
Quick action - map overlay/underlay - 

### ISSUE THREAD

**Issue by majkaz** [osmandapp/Osmand#4682]
It is possible to define several maps for quick action -> map overlay/underlay. However, only 2 maps are used for the quick action, every other defined overlay/underlay map is ignored, instead of cycling among all the defined maps. The same is true for both overlay and underlay.

App version Osmand 3.0.0 #22912M, dated 2017-10-25

**Comment by dmpr0** [comment]
I can't reproduce it, it work fine for me with 4 maps: CycleMap, Microsoft Earth, Hybrid, OsmAnd Online tiles, None.

**Comment by majkaz** [comment]
@dmpr0 
Just a confirmation - I have just installed the latest nightly (OsmAnd-master-nb-2017-12-04.apk) and it is working now.

**Comment by dmpr0** [comment]
@majkaz Thank you! Nice to hear it.
