### ISSUE TITLE
OSM editing plugin: Allow advanced editing mode

### ISSUE THREAD

**Issue by majkaz** [osmandapp/Osmand#4689]
The mapping feature is currently ideal for adding POIs for a casual mapper. 

As it is currently possible very fast and simple to map using the "quick action" (allows creating own presets), it becomes my to go way to map POIs. However, there is limited number of values for the "main" tag - I mean the pair beneath "name". **Would it be possible to allow advanced mode?** This would then allow to add additional values by allowing of editing of the second row in the second tab - see screenshot, **the marked fields**.

![poi](https://user-images.githubusercontent.com/23097386/32320927-bc85bea0-bfbf-11e7-8a16-c9d75bc9b1ff.png)

**Comment by iriman** [comment]
Yes, please consider doing some changes on it. Yesterday I corrected some bus stations which should be bus stops. Now I see that both `amenity=bus_station` and `highway=bus_stop` tags are present on nodes.

**Comment by vshcherb** [comment]
We don't want to make it very open so people create "empty POI". So far we were following the rule of adding missing "POI", though I think may be we could investigate how to limit it to "advanced" mode only.

**Comment by matthijskooijman** [comment]
I would also like to see this. I've been busy mapping benches and picnic tables, and you often see them with a trash bin. Now, I can quickly add a bench POI with a quick action, but then have to edit it again, go to advanced, tap add tag, type "bin", move to the value, type "yes". Ideally, I would just have a "Bench with bin" quick action, that adds a bench POI (`amenity=bench` IIRC) and adds `bin=yes` at the same time.

AFAIU this issue is about more tags for POIs created through quick action presets, so perhaps the issue title should reflect that?

**Comment by vshcherb** [comment]
@matthijskooijman I've thought advanced mode was already supported for quick action.  We will double check it.

**Comment by matthijskooijman** [comment]
I can't find that here (3.0.4, seems 3.1 has not landed in F-droid yet?)
![screenshot_20180815-081151](https://user-images.githubusercontent.com/194491/44134126-a4dcde02-a063-11e8-93cf-13bf80741031.png)

**Comment by majkaz** [comment]
@matthijskooijman 
You have to edit the quick action and add everything there what you need/want in the preset. It did always work for me, even if the way there is not a straightforward one. 
But it works, the initial issue was another one: You cannot define a tag Osmand doesn't have in the predefined set. This is completely different from your problem.

**Comment by matthijskooijman** [comment]
Woah, I must be blind, I completely missed the big "Add tag" button when adding a quick action. So indeed, my usecase is already covered (should have realized this before, would have saved me a lot of hassle :-p). Thanks for pointing this out :-)

>  the initial issue was another one: You cannot define a tag Osmand doesn't have in the predefined set. 

Ah, I think I understand. Does this not work for you by just leaving the type blank? I just tried creating an Add POI quick action with an empty type, and with an `amenity=foo` tag added. Create a POI from that, results in:

![bar](https://user-images.githubusercontent.com/194491/44139068-48675090-a076-11e8-8514-cfae61f2989a.png)

The empty "amenity" tag (shown by OsmAnd for an empty type) looks a bit scary, but it also shows the `amenity=foo` tag. When exporting this change as an osc file, I get:

```
<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<osmChange generator="OsmAnd" version="0.6">
  <create>
    <node lat="52.095071601490176" lon="5.120505332946777" id="-2" version="1">
      <tag k="amenity" v="foo" />
    </node>
  </create>
  <modify />
  <delete />
</osmChange>
```

So I *think* that means the POI is correctly generated and will be correctly uploaded.

Does this solve your issue? Or am I still misunderstanding your intention?

**Comment by vshcherb** [comment]
Empty values won't be stored anyway.
