### ISSUE TITLE
Follow mode gets disabled when switching to different app or turning display off/on

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#4693]
After turning the display off/on or switching to a different app and back to OsmAnd the follow mode is disabled. To get to the current position you either have to tap on the blue location button again or wait until the auto-center time has passed. This is really annoying, especially while navigating.

Is this intended or a bug?

**Comment by vshcherb** [comment]
This doesn't sound as a typical use case but it doesn't sound as intended anyway.

**Comment by scaidermern** [comment]
It is a typical use case, e.g. switching to a music app, messenger, camera and similar activities.
