### ISSUE TITLE
Display OSM notes - wish: filter out closed notes

### ISSUE THREAD

**Issue by majkaz** [osmandapp/Osmand#4694]
Would it be possible to show only opened notes when "Show OSM notes" is switched on?

It is only matter of convenience,  the resolved notes take 7 days to disappear, I think. During this time however, the note often overshadows the POI in the same place.

IMHO, the resolved notes are of no interest for mobile mapping.

**Comment by scaidermern** [comment]
> IMHO, the resolved notes are of no interest for mobile mapping.

Except if you accidentally closed a note and want to reopen it. Maybe make it configurable with the default option being to show only open notes?

**Comment by dmpr0** [comment]
Merged into https://github.com/osmandapp/Osmand/issues/4740
