### ISSUE TITLE
evaluate emergency=yes/no

### ISSUE THREAD

**Issue by Buntbart** [osmandapp/Osmand#4697]
Osmand should not indicate facilities as an emergency POI if the facility is marked emergency=no. 
For example: [https://osm.org/node/2973195659](https://osm.org/node/2973195659) 
You don't get any emergency care there.

**Comment by pebogufi** [comment]
+1
Peter

**Comment by xmd5a2** [comment]
"Emergency" is category name. We can't assign multiple "main" categories for single POI type depending on emergency=no tag. Also this will break POI editing.
Tag emergency=yes/no is displayed in the context menu of the POI.

**Comment by Buntbart** [comment]
Then the name of the category is obviously misleading and should be better called "health care" or similar. In an emergency, people don't want to check every entry in the context menu to see if it is really sorted correctly, I guess.
