### ISSUE TITLE
Plugin OSM Editing: collection (service) times not shown in editing tab

### ISSUE THREAD

**Issue by majkaz** [osmandapp/Osmand#4698]
In the advanced tab, collection times (and I suspect the same is valid for service times) are not shown when the POI has the entry (can be seen in the POI info).

Please, allow the editing either on advanced tab, or it might even be possible to implement switch for the opening hours part of the first editing tag (choose opening/collection/service times, with opening times set as the default selection).

Caveat: I didn't try to change collection times in the advanced tab using manual entry and don't know if this would add second tag or simply overwrite the already entered one.

**Comment by scaidermern** [comment]
For me the collection times are shown and can be edited without problems:

![photo_2017-11-06_12-44-44](https://user-images.githubusercontent.com/1040784/32439745-5706ade4-c2f0-11e7-8f02-01a2e461b295.jpg)

**Comment by majkaz** [comment]
I have never had the collection_times displayed, as far as I know. I have entered quite a lot of them, but could never edit it.
I have noticed additional problem on the screenshot - the ref tag does display as name tag and doesn't display as ref either.
See screenshot:

![comb](https://user-images.githubusercontent.com/23097386/32440389-3cd5c704-c2f3-11e7-8c21-05059164df3d.png)

Is it my version or perhaps that the collection_times:lastcheck overwrites some setting??

**Comment by vshcherb** [comment]
The node to test http://www.openstreetmap.org/node/4476032493

**Comment by AlexSyt** [comment]
We could not reproduce this issue.

**Comment by majkaz** [comment]
@AlexSyt 
Is there a way to find out why the problem is there? Log? 
I have the problem here even in newer nightly versions than the issue was opened for (latest is #23369m from 2017-12-12).
For some reason, this is now happening more and more for other POIs as well - anything except opening hours seems to be ignored. See [this video](https://drive.google.com/open?id=1oMpsXNYTRBhRZWG7_AzXhW-9Je-ORkdO) and compare the first view with details and the missing details when editing.
Having live updates on or off (and deleted) makes no difference.

**Comment by dmpr0** [comment]
@majkaz we try to reproduce it on different devices and versions, and now unfortunately can't reproduce it. Do you try reinstall OsmAnd?

**Comment by majkaz** [comment]
@dmpr0 
I didn't try to reinstall completedy - I am just updating with the latest beta and rebooting the phone. I can do it now. Should I clean it completely - including deleting the maps etc?

**Comment by dmpr0** [comment]
@majkaz You can leave maps, if you user shared memory, if you use another memory path it will be deleted.

**Comment by majkaz** [comment]
Additional comment:
The issue seems to come and go in different nightly installs on my phone see #4832 
2017-12-05 slightly different issue, 2017-12-06 present, 2017-12-07 not there any more, 2017-12-12 present. The same local map installed, osmand live updates on (but tested with off and deleted live upate maps as well when the issue was there).
Phone was rebooted every time after the issue came up to check if it would help.
