### ISSUE TITLE
error show map

### ISSUE THREAD

**Issue by progserega** [osmandapp/Osmand#4701]
OS: Android 6.0.1
Yotaphone2 YD201
OsmAnd+ 2.8.2 дата выпуска 2017-10-20

Установлен плагин контурных линий. И затемнённого рельефа.

1) Включены карты: затемнённый рельеф, контурные линии, векторная карта приморского края. 
2) Включил отображать сегодняшние треки (порядка 20 км).
3) Включил запись трека.

Через некоторое время перестала отрисовываться карта. И появилось сообщение: "Во время отрисовки карты произошла непредвиденная ошибка".

On english:
OS: Android 6.0.1
Yotaphone2 YD201
OsmAnd + 2.8.2 release date 2017-10-20

Plugin contour lines. And a darkened relief.

1) Maps are included: a darkened relief, contour lines, a vector map of the Primorye Territory.
2) Turned on to display today's tracks (about 20 km).
3) Enabled track recording.

After a while, the map ceased to be drawn. And a message appeared: "An unexpected error occurred while drawing the map."

**Comment by progserega** [comment]
Error yestarday:
![screenshot_20171105-102430](https://user-images.githubusercontent.com/1297163/32479675-b06f7da2-c3d6-11e7-93f9-4d4609550221.png)

Info today:
![photo5190828733450266727](https://user-images.githubusercontent.com/1297163/32479674-b03ad674-c3d6-11e7-9d7f-1dd7e5390d93.jpg)

**Comment by progserega** [comment]
жёлтая линия на карте - это путь из группы OsMo.

yello line on map - it is path from OsMo plugin.

**Comment by vshcherb** [comment]
В этой ситуации не хватает логов самого устройства, чтобы понять ошибку.

**Comment by progserega** [comment]
Сейчас уже поздно логи брать - потёрлись? Особо с тех пор османдом не пользовался...
В любом случае - где и как их брать?

**Comment by vshcherb** [comment]
есть програмы aLogCat и другие
В любом случае, такие ошибки бывают, но их практически невозможно исправить, если не знать какая ошибка. Поэтому баг будет закрыт . Насколько я вижу это возможно ошибка памяти 100 МБ из 100 МБ использовано.
