### ISSUE TITLE
wrong rendering city_wall instead of castle_wall

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#4703]
In the current rendering there is a minor bug:
castle_wall is shown as city_wall. In my opinion castle_wall does not need a own symbol to be displayed.
Example:
http://www.openstreetmap.org/relation/5513711
historic=castle
name=Burg Hohenzollern
tourism=attraction
website=http://www.burg-hohenzollern.com
wikipedia=de:Burg Hohenzollern

version osmand 3.0.0#23029, map current 2017/11/01

**Comment by sonora** [comment]
Yes, we simplify by transforming caste_wall to city_wall, as the mapping practice in many medieval places (Italian towns/villages/borgos) is fuzzy. But it is important to show both, even if we make no optical difference. What's the impact?

**Comment by pebogufi** [comment]
There is a difference in the importance.
city_wall are in most cases the last parts or a old city and therefore they are of historic importance.
castle_wall are only parts of a castle, where castle exists itself as tag and is often tagged with a polygon or single node.

In search (historic) city_wall are wellcome, but castle_wall not, because the castle itself is also found.
So FOR ME there is no need for finding castle_wall and seeing icons for it on the map but I am interested in seeing city_wall.

But that differentiation is of minor importace.
Regards Peter

**Comment by vshcherb** [comment]
I guess we should fix "Search POI" functionality which is independent from the rendering. For the rendering it may be less important but I concur we should not display the icon for the polygon.

**Comment by xmd5a2** [comment]
Not sure I understood correctly. What's wrong with rendering?
![screenshot from 2017-11-20 14-36-58](https://user-images.githubusercontent.com/5829014/33016937-71cb04d8-ce01-11e7-93ea-3896b2907f5e.png)

**Comment by pebogufi** [comment]
Currently castle_wall is rendered as city_wall.
When searching for Sightseeing, there are a lot of orange circles (city_wall) which are waste and overcrowd the object. I don't need to see all castle_walls (shown as city_wall) within a castle.
![castle with city_walls](https://user-images.githubusercontent.com/18628183/33017859-5146fa08-cdf4-11e7-8a09-02b97ab9b385.jpg)

**Comment by xmd5a2** [comment]
It turns out that the problem in POI? If I remove the castle_wall from the POI, but leave rendering the same, will it solve the issue?

**Comment by pebogufi** [comment]
In data, the tags for castle_wall or correct, but  castle_wall should not be displayed as city_wall.

**Comment by xmd5a2** [comment]
It will look like this
![screenshot from 2017-11-20 17-21-38](https://user-images.githubusercontent.com/5829014/33023560-a0db8a96-ce19-11e7-8ee1-3fe5d72aa63e.png)
