### ISSUE TITLE
in search term missing: historic=yes

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#4704]
In tourism I found 14 subcategories for historic
historic aircraft
historic cannon
...
I am missing something like "historic object" for historic=yes
version osmand 3.0.0#23029

**Comment by xmd5a2** [comment]
historic=yes is additional tag and we can't add category for it. Only "main" tags can be searched. Additional tags are searchable via filters.

**Comment by pebogufi** [comment]
Thanks, Peter
