### ISSUE TITLE
Blank map at high zoom

### ISSUE THREAD

**Issue by dvenza** [osmandapp/Osmand#4705]
Since a few versions (several months, but I did not keep track) it happens that when I zoom in (more details) after a certain level the map goes blank.

I have offline maps for the "provence-alpes-cote-azur" in France, the world base map and the altitude correction. Full maps, not street-only. I am testing in areas covered by the map.

This happens if I (or the auto zoom while navigating) go below 500 meters (so it starts at 200 meters). When I zoom back manually the maps comes back.

By blank map I mean that I have all the information around the screen and even the route to follow when navigation is active, but no map details, no roads, no green areas. Here and there, in the middle of the blank map, it draws something that I think are pedestrian tunnels. Basically I have a blank map showing unconnected pedestrian tunnels only.

My phone is an Android Zenfone MAX (ASUS Z010D) with Android 6.0.1.
OsmAnd version: OsmAnd+ 2.8.2 released 2017-10-20

**Comment by sonora** [comment]
It sounds like a problem with your regional map. Have you tried updating it?

If this still occurs after a map update, it would be interesting to know the exact map zoom where this occurs, and if this is consistently the same when zooming in anywhere in Cote'dAzur. You can briefly see the zoom level displayed above the menu button while zooming, if you temporarily enable OsmAnd's development plugin.

**Comment by dvenza** [comment]
I deleted the map and re-downloaded it (it was already the latest version). It happens when zooming in different areas of the map (I tried around Antibes, Nice and Aix-en-Provence).
I also tried with the Liguria map, same problem.

At zoom level "15" the map is blank, zoom level "14" the map is ok.

**Comment by PiGo86** [comment]
Same problem here with Pays-de-la-Loire map. The map goes blank from 500 meters zoom and under.

**Comment by nowindows** [comment]
OsmAnd+ 2.8.2, released: 2017-10-20
Zooming in, on any map or location, finer than 0.5 miles zooms momentarily then the map goes blank.  Map appears again at 0.5 mile on the lower scale and disappears at 0.25 miles and less.
Using United States of Michigan, Ohio, West Virginia, Virginia, North Carolina, and Washington.
![screenshot_2017-12-30-22-29-44](https://user-images.githubusercontent.com/6694526/34458898-3bbbd212-edb1-11e7-9baf-9ab20cc83fcb.png)

**Comment by nowindows** [comment]
If Overlay map is on - OsmAnd (online tiles), zoom-in works to 10ft.  Turn off Overlay map and zoom blanks below 0.5 miles.

**Comment by sonora** [comment]
@nowindows Can you temporarily enable the Development plugin under Plugin settings Then, while zooming, you will momentarily see some digits above the map screen's menu button, the first 2 digits of which are the target zoom level. If 12 and up are failing for you, it would mean that your detailed (in the US: State level) maps are failing for some reason, while the World basemap (zoom levels 1 to 11) does work.

It sounds like the original issue reported here by dvenza may be different, because there the first zoom level to fail is 15.

**Comment by nowindows** [comment]
Screen blanks when going from 14 3.4 to 15 3.4.  (0.5mi to 0.25mi).

I have found that zooming does work for Map Style: Topo, but BLANKS when zooming finer than 0.5 miles, for OsmAnd, Touring, and others. Thanks for looking into this!

**Comment by sonora** [comment]
@xmd5a2 Leonid, that sounds interesting, looks like the renderers which fail may all depend on default?

**Comment by nowindows** [comment]
Are there any more tests I need to run to help debug and solve this problem?

**Comment by xmd5a2** [comment]
Can someone give exact coordinates? I tried to reproduce issue but failed

**Comment by dvenza** [comment]
To me it was happening with all locations I tried (southern France and Italy) and other people reported the problem in the US, so I do not think it is linked to the location.

**Comment by nowindows** [comment]
Screen blanks when going from 14 3.4 to 15 3.4. (0.5mi to 0.25mi) for "Vector renderer OsmAnd, Touring view, Mapnik, UniRS, LightRS, Winter and Ski for **_ANY_** location I've tried in **US** - States WI, MI, IL, IN, OH, KY, WV, VA, TN, NC, SC, GA.

****Screen zooms (does not blank) ONLY for Topo - Vector renderer**.**

Overlay map off, Underlay map off, Contour lines on, Hillshade layer on.  When zooming from 14 to 15, all roads, contour lines, and other features disappear **_(except for Topo)_** but the Hillshades are still visible in the background.

I can give more information to help debug this.  Specify what is required?

LGV20, 64GB memory, 200GB SD Card, OsmAnd+ 2.8.2, released: 2017-10-20, Allocated memory 134MB, Total Native 140MB, A-GPS: 2017-01-18 8:44.

**Comment by sonora** [comment]
Can you post a screenshot of the last (14, I guess) zoom level which still works? I am trying to figure out if that screen is produced from the US state map all right, or is really just a blown-up version of the global world overview map.

Alternatively, I would like you to look at Menu/Download maps/Local tab, and check if OsmAnd really displays all state maps you expect are present on your device, e.g. "United States of America  California", **preceded by a green icon**.

**Comment by nowindows** [comment]
OsmAnd Vector Renderer - Screenshots of Charlotte, NC:  zoom 14,  15 (blank), Menu/Download/Local tab, overview map.

![screenshot_2018-01-18-12-01-37](https://user-images.githubusercontent.com/6694526/35110992-2bb518ba-fc48-11e7-8709-008ac4999533.png)
![screenshot_2018-01-18-12-01-46](https://user-images.githubusercontent.com/6694526/35110996-2ec7ced0-fc48-11e7-958b-22be5532dba9.png)
![screenshot_2018-01-18-12-03-39](https://user-images.githubusercontent.com/6694526/35111004-32932168-fc48-11e7-80dc-cfc6c7325bd5.png)
![screenshot_2018-01-18-12-03-53](https://user-images.githubusercontent.com/6694526/35111010-348dd3be-fc48-11e7-829e-e54976c654b6.png)

**Comment by sonora** [comment]
Ok, thanks. Very clearly, you have the correct state map, and it is used,  like your zoom 14 screenshot proves. So we have some real issue here. Will try to reproduce myself and report here.

**Comment by sonora** [comment]
Ok, here is my finding. It seems somehow specific to your setup. I have downloaded the North Carolina standard map, and see no issue. I can produce any zoom level. Then I downloaded North Carolina Hillshades, and still no issue. So we need to work on how to reproduce this, it seems.

Just to make sure: Can you please try some other Map styles in the Configure map menu, like Touring view and Topo. This would rule out you somehow have a corrupted custom render file on your device. It would also help to know if you can reproduce the issue on a second device?

**Comment by sonora** [comment]
What's interesting: Your zoom 15 screenshot shows 3 little segments of East 3rd, East 4th, and East Trade street about where the Overstreet Mall footpath crosses each ... very weird display issue..

**Comment by sonora** [comment]
I think I may have found it. Can y'all please go to your "Configure map" settings and make sure nothing is selected under "Hide"? I think you may have e.g. "Hide overground objects" selected, and we carry the "overground" information in our maps exactly from zoom level 15 and up, so this should be your issue??

**Comment by sonora** [comment]
@vshcherb Assuming my idea fixes this: 2 questions:

(1) Why did it happen in the first place? Users simply playing with the setting and forgetting to reset, or did we have some faulty build or commit which activated this setting as per a false default? Can you remember anything?

(2) I do not recollect why we would need such a setting "Hide overground objects" in the first place? It may cause more issues than it solves?

**Comment by nowindows** [comment]
Hooray, Hooray!!!!!  It was "Hide overground objects" that would blank the map from 15 up on any style except Topo.  Now I can zoom to 10 ft on any style.  (I can even see the bicycles going down the path - HA!).

Great detective work!!!!  

OsmAnd is so powerful and I love the support!  Thank you, thank you!!!!

**Comment by xmd5a2** [comment]
@sonora 
(2) It is useful when observing underground subway footway tunnels and stations

**Comment by nowindows** [comment]
Is there an easy way to save/reset settings/configurations?

**Comment by sonora** [comment]
Resetting: See my article here: http://osmand.net/help-online?id=faq#reset_without_data_loss

Leonid, point taken, but it seems it is a little 'dangerous' a setting. Maybe we have an idea, like displaying some sort of toast on the map screen etc. when the app is re-started and that setting is on or similar. Not sure.

**Comment by xmd5a2** [comment]
@sonora Agree. We need some indication of options like this.

**Comment by rlaggren** [comment]
I have had this same problem all over the USA. I confirm that disabling "Hide AboveGround" corrects the problem. (Motorola G5+; Android 7.0) 

SafeMode will also correct the problem, which was what I used prior to reading the thread here. Thanks for looking into this.

Rufus
