### ISSUE TITLE
Add parking meters preset in the OpenStreetMap editor plugin

### ISSUE THREAD

**Issue by Codain** [osmandapp/Osmand#4707]
Add the preset for a parking meter when creating a new feature. Tags to set are:

- amenity=vending_machine
- vending=parking_tickets

**Comment by xmd5a2** [comment]
It is already there. Also you can add this to osm using quick action button.

**Comment by Codain** [comment]
@xmd5a2 : Vending machines are on the map but with no differentiation regarding the type of sales items. Parking meters are a usefull POI whenever you drive a car in a city.

Also, what do you mean by "quick action button" ? I'm an OsmAnd+ owner with the OSM editing plugin and as far as I know the only way to add a POI is to make a long tap on the map, select Create a POI, select type "Vending machine" , go to "Advanced" tab, add vending=parking_tickets and then save... I don't think it is as quick as you mentioned.

For those reasons I don't see why this issue has been closed. Thanks for your help on this one.

**Comment by xmd5a2** [comment]
![screenshot_2017-11-08-11-01-23](https://user-images.githubusercontent.com/5829014/32537761-cd35167e-c474-11e7-853e-0fba88d7dfdb.png)
![screenshot_2017-11-08-11-02-02](https://user-images.githubusercontent.com/5829014/32537772-d8a397e2-c474-11e7-941e-942da59c7090.png)
![screenshot_2017-11-08-11-02-16](https://user-images.githubusercontent.com/5829014/32537803-edbf2a7e-c474-11e7-9314-13bbb9a394c2.png)
![screenshot_2017-11-08-11-02-27](https://user-images.githubusercontent.com/5829014/32537815-f3381e48-c474-11e7-8aa2-daf742698ec3.png)
![screenshot_2017-11-08-11-02-35](https://user-images.githubusercontent.com/5829014/32537833-06cb5056-c475-11e7-95a5-d59700a2fcaa.png)
![screenshot_2017-11-08-11-03-40](https://user-images.githubusercontent.com/5829014/32537849-11acd3dc-c475-11e7-9a8d-31850798fc4b.png)
![screenshot_2017-11-08-11-04-31](https://user-images.githubusercontent.com/5829014/32537859-197d2d3c-c475-11e7-84eb-c07907dd0f32.png)
![screenshot_2017-11-08-11-04-45](https://user-images.githubusercontent.com/5829014/32537869-1f8db78c-c475-11e7-81e1-a9125f6b52ed.png)
![screenshot_2017-11-08-11-04-56](https://user-images.githubusercontent.com/5829014/32537882-257753a6-c475-11e7-9fc2-3272919da716.png)

**Comment by xmd5a2** [comment]
Also you can create custom POI filter to display only parking ticket machines. 
![screenshot_2017-11-08-11-16-14](https://user-images.githubusercontent.com/5829014/32538347-c01cbddc-c476-11e7-81dc-61c5caa7f61c.png)
![screenshot_2017-11-08-11-16-04](https://user-images.githubusercontent.com/5829014/32538350-c395065e-c476-11e7-814e-70f5ef5f7300.png)
![screenshot_2017-11-08-11-17-08](https://user-images.githubusercontent.com/5829014/32538354-c5dea140-c476-11e7-8d45-4535af164bb4.png)
I think this is more than enough for most users.

**Comment by Codain** [comment]
Wow, thank you, that's a very nice feature I've discovered!
