### ISSUE TITLE
osmand shared links redirects to google map (opening with browser)

### ISSUE THREAD

**Issue by FTABoy** [osmandapp/Osmand#4708]
opening this shared links in browser will redirect the user to : https://www.google.com/maps?q=loc:34.717052,50.869064&z=16
آزادراه خلیج فارس, قم
Location: geo:34.717052,50.869064?z=16
https://osmand.net/go?lat=34.717052&lon=50.869064&z=16
why this is happening with osmand.net links ?
thanks

**Comment by PaulStets** [comment]
Fixed https://github.com/osmandapp/osmandapp.github.io/pull/107
