### ISSUE TITLE
Doesn’t works on Samsung galaxy tab S3

### ISSUE THREAD

**Issue by ytrezq** [osmandapp/Osmand#4715]
Osmand+ freshly installed, and I am stuck on this initial image : 
![screenshot](https://user-images.githubusercontent.com/3824869/32546735-5688e9d6-c480-11e7-9b34-73880036bb3e.png)

**Comment by vshcherb** [comment]
Is it possible to uninstall & install it again. Looks like it went completely wrong. Please also try with a different Locale in Global settings (at least for installation period).
