### ISSUE TITLE
Not easy to filter electric charging stations

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#4721]
1. Charging stations is a specific type
2. Also charging stations could be supported on regular gas stations

Synonym electric is needed

**Comment by PanderMusubi** [comment]
In the app, "Show POI" lists the option "Gas station". Could the option "Charge station" be added there?

Please, offer different icons for super chargers, normal chargers and what other types are available. See also https://github.com/osmandapp/Osmand/issues/3954

**Comment by PaulStets** [comment]
Added in: https://github.com/osmandapp/OsmAnd-resources/commit/84dd781ab61d07c024c7960e18768c0f447787f5#diff-bc091b281dee9cb9288fad5990fe5538, https://github.com/osmandapp/OsmAnd-resources/commit/a42db897a210b0e2864c7c9c6857a933c47b8b09

**Comment by vshcherb** [comment]
1. We are missing poi_additional_category for filtering UI options.
2. It is quite rare combination amenity=fuel+fuel:electricity=yes. Though
We need to do it with entity_convert and create new type. 
```
Victor OsmAnd, [03.02.18 15:05]
<poi_filter name="charging_station_filter" top="true">
        <poi_type name="charging_station" tag="amenity" value="charging_station">
      <poi_type name="charging_station_combined" tag="combined_amenity_fuel" value="charging_station">
```

Looks like situation is similar to ATM.

**Comment by vshcherb** [comment]
Example https://www.openstreetmap.org/node/4932650231#map=13/49.5174/0.9405

**Comment by PanderMusubi** [comment]
What is the reason for closing this, if I may ask?

**Comment by xmd5a2** [comment]
@PanderMusubi because issue was fixed (however will only work with march maps). Your issue is another case. It is better to create a new issue if you want.

**Comment by PanderMusubi** [comment]
Thanks. Looking forward to the result. Before I create another issue, is there already functionality for showing only gas stations near highways or has there been requests for that before?

**Comment by xmd5a2** [comment]
@PanderMusubi It is possible only during navigation but not in search

**Comment by PanderMusubi** [comment]
During navigation will also work for electric charging stations in March? Then I have no further request.

**Comment by xmd5a2** [comment]
@PanderMusubi yes

**Comment by vshcherb** [comment]
@xmd5a2 most likely we will need to create a new issue for filtering stations by power, socket types available. It should be simple enough and most likely most of the changes will happen in the backend size (by generating slightly augmented maps).

**Comment by PanderMusubi** [comment]
If you use OsmAnd, perhaps you would like to set in configuration of the app which kind of socket types you are interested in. This doens't change often as your car is pretty much stuck with what it has.
