### ISSUE TITLE
Trip Recording: allow to disable notification

### ISSUE THREAD

**Issue by shtrom** [osmandapp/Osmand#4723]
I have a Pebble Watch and GadgetBridge forwarding notifications to the watch. Though it has a blacklist, I want to keep receiving notifications from the OSMAnd TTS telling me where to go next.

However, the Trip Recording plugin, which I like to have on too, throws a spanner in the works, by constantly updating its own notification about the duration of the recording, and therefore triggering a new notification on the watch. This is not a very useful use case, but currently unavoidable.

The easiest solution would be to allow to disable (Android-level) notifications from the plugin altogether, in its settings page.

**Comment by PaulStets** [comment]
Hi, you can actually disable the trip recording notification. To do that, please go to the Settings - Trip recording and uncheck the last option (Enable recording quick start).

**Comment by zais** [comment]
@shtrom, same issue with constant spamming to pebble (due to change in notification).
@PaulStets, That doesn't help me.

**Comment by shtrom** [comment]
Ah, yeah, @PaulStets's solution also didn't work for me.
