### ISSUE TITLE
Crash and other wrong behaviour when GPS signal come back after lost

### ISSUE THREAD

**Issue by Rpnpif** [osmandapp/Osmand#4732]
OSMand 2.7.5 crashed when I drive out a tunnel.

Since the last updating of  Android 7 on a Huawei P8 lite 2017 smartphone (EMUI build PRA-LX1C109B131), OSMand has now a strange behaviour. When the GPS signal come back, the position of the cursor is shifted at between 0.5 to one km or until 5 km from the right position. After a while (15 min), the position error is still between 0.5 to two km. So OSMand is unusable at this moment.

To fix this behaviour, I must close Osmand. 

My maps are the last official France offline maps from Osmand with some live maps.
The tunnel where this issue is reproducible is here : https://www.openstreetmap.org/#map=19/47.49393/-0.57032

Regards.

**Comment by PaulStets** [comment]
Hi, could you please attach an exception.log file here? It's located in the data storage directory (the path to it is shown in the Settings - General Settings - Data storage folder).

**Comment by Rpnpif** [comment]
This issue appeared just after an updating of Android but now it is more rare.
OsmAnd 2.8  has less such issues.

A bit more rare is a permanent position shift after a loss of the GPS receiving. On other times, the position became erratic. A workaround is to restart OsmAnd and sometimes, I must restart Android.

You must know that this GPS Huawei driver seems unstable.
So I suggest to make more stable OsmAnd when the GPS signal is lost. 2.8 is on a good way.

I propose to send you the logs when a new crash (of 2.8) will appear.

**Comment by Rpnpif** [comment]
I had not observed this issue while months.

**Comment by vshcherb** [comment]
good news
