### ISSUE TITLE
No toast for  Online search if there is no internet

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#4735]
I think we should not hide the Online search item when the Online maps plugin is not activated. Using Online search is a very different use case than using online maps, and beneficial also for our standard users using our offline vector maps. They normally completely miss the online search feature as of now.

I also think we have no discussion about unintended Internet use, as the feature is clearly marked Online search.

**Comment by scaidermern** [comment]
Good idea. I've always wondered why the online search depends on the online maps feature.

**Comment by vshcherb** [comment]
I guess the online plugin could be fully integrated in the application cause I don't see much value to keep it separate cause it is hiding just few menu items & 2-3 settings.

**Comment by vshcherb** [comment]
Now It always displayed if the search is empty.

**Comment by sonora** [comment]
At least 2 remaining issues her:
1. We did not get rid of the Online maps plugin as Victor suggested
2. When you tap the onlibe search button, and no Internet connection is present, the Online search option simply disappears with no message about a missing Internet connection. Target scenario should be like for map updating.

**Comment by vshcherb** [comment]
1. Agree it is discussible do we need to get rid the plugin completely or not.
2. Disagree cause people can't do anyway without internet connection & we should not bring too much attention 
3. Discussible, that's a one of the reason why the plugin still exists
4. Agree the toast could be reasonable

**Comment by sonora** [comment]
Thx! But some test results: Works, sort of, but you only get to see the 'Search Online' button after a full round of offline search has finished, which  can easily take several minutes under some circumstances. I guess we need to cater for situations where you would like to use online search immediately, i.e. can we move the button to the top and display immediately?

Also: No toast, when there is no Internet connection at the time, only a remark that nothing was found and the online search option has disappeared then, so no way to retry?

**Comment by vshcherb** [comment]
Please open another issue for a first request cause we are not sure it is worth to implement it.
