### ISSUE TITLE
Misinterpretation of maxweight in offline routing

### ISSUE THREAD

**Issue by kreuzschnabel** [osmandapp/Osmand#4736]
Hi,

apparently, OsmAnd+ 2.8.2 offline navigation (car mode) gets confused with a maxweight=* tag on an OSM way and a vehicle weight specified within the navigation settings.

See this routing task: https://www.openstreetmap.org/directions?engine=mapzen_car&route=50.2128%2C8.2483%3B50.1978%2C8.2446#map=15/50.2053/8.2461

Both K707 and K708, giving the shortest and fastest route, have a maxweight=3.5. 

As long as I don’t specify a vehicle weight in Osmand’s navigation settings, the short route via the K roads is suggested.

As soon as I specify a vehicle weight of 1.5 tons and re-request a route, those roads are avoided, though the weight given is well within limit! 

I consider this a bug, maybe a kilograms vs. tons conflict in processing those values.

--ks

**Comment by PaulStets** [comment]
Fixed with https://github.com/osmandapp/OsmAnd-resources/pull/466

**Comment by pebogufi** [comment]
I am sorry, but I don't think it is now correct.
Example: there is street with a limit of 3,5 tons.
case-1 My car has 3,0 tons, street is used, OK.
case-2 My car has 3,5 tons, street is NOT used, **NOT OK**.
case-3 My car has 5,0 tons, street is NOT used, OK.
In case-2 the street should be used. 
I suppose there is a matching which uses less-than instead of less-equal (or something like that)
Please check that again.
Program-version 3.0.0#23280, routing.xml downloaded a few minutes ago.
Thanks Peter

**Comment by pebogufi** [comment]
After changing the weight in routing.xml from 3.5 to 3.499 the street is also used.

**Comment by PaulStets** [comment]
Yes, you made a valid point. I have fixed this here: https://github.com/osmandapp/OsmAnd-resources/pull/469. 
By the way, I have tested the smaller values and they work correctly, so perhaps you will need to reinstall the newest nightly to test it.

**Comment by aceman444** [comment]
Can you instead look in the java code how the <gt> operator used in the routing.xml file is implemented? Maybe it is actually "greater or equal", which causes the problem here.
The .99 hacks seem ugly to me.

**Comment by PaulStets** [comment]
The operator is indeed "greater or equal" in the code. However, this operator is used for multiple purposes further in the routing.xml. Introducing the new operator "greater than" would be too much for this task. Therefore we decided to implement it this way.

**Comment by aceman444** [comment]
In that case the 'gt' name is misleading and should be renamed.
