### ISSUE TITLE
Search results: list street name and suburb

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/OsmAnd#4738]
nightly 3.0.0#23024M
When searching for the name of a shop, all branches in town are listed. When I need a particular one and not the nearest, I am lost. 
Could you add the street address and/or suburb?

Another issue is that it is shown as building and not the the shop=doityourself type (similar to #3687, but there the cafe is shown in addition).

Finally, the direction arrows are too small to be recognised in the car, in particular with their shape any corner can be mistaken as the tip.

![20171111-132123_hornbach_search](https://user-images.githubusercontent.com/8266355/32694788-aea9a288-c749-11e7-8fb4-d5b9b67b0c11.png)

**Comment by littlehelper** [comment]
I agree, a kind of 'is in' and address look-up mechanism would be great for each search result.
See similar proposals #3327, #4174, #4176.

**Comment by scaidermern** [comment]
Good idea.

Regarding the direction arrows: How about "real" arrows consisting of a line and a triangle? They are far easier to interpret.

**Comment by polarbearing** [comment]
Probably even an open angle would do, such as  '>'

**Comment by elgaard** [comment]
If there is a branch tag that should be shown in the listing.

**Comment by jfburke3** [comment]
I agree that this would be a big improvement to the search results. I find that I frequently need to select several of the results, going back after each one, in order to find the one I'm interested in.

**Comment by sonora** [comment]
In my mind both the search result display enhancement and the arrow issue should be in one of our next milestones, looking at the number of issues we have collected over time here (see list in #2993))

**Comment by bambamal** [comment]
The screenshot in the first post also shows search results being indicated as a buildings. I feel the OSM standard is now to put POI information as building tags, so this will happen even more often.
This is technically correct but not helpful at all. The type indicator below the name should be chosen the same way its chosen for a POI node, at least for certain types (e.g. restaurant, shop, etc.).

For the average user its not important, if the POI is implemented as a building or a node, so no information lost here. Even if it might be important for some people, you could keep the building-icon as an indicator.

**Comment by IByte** [comment]
One way to do it (at least for some POIs) is to display the value of the "branch" key in the search results list, if it is provided. This is actually suggested on https://wiki.openstreetmap.org/wiki/Key:branch, therefore I was surprised to find it is not actually implemented in the current version of OsmAnd (3.0.4).

**Comment by EvanCarroll** [comment]
I think what the OP really wants here is "branch" to show up. Hornbach Baumarkt AG is a German DIY store. https://en.wikipedia.org/wiki/Hornbach_(retailer) I think this would solve this problem https://github.com/osmandapp/OsmAnd/issues/6947

Then when you search for the Hornbach you'd see the different branch names (which are based on the city).

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/2993
