### ISSUE TITLE
NPE in RoutingContext

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#4739]
See attached:  [exception.log.txt](https://github.com/osmandapp/Osmand/files/1464516/exception.log.txt)

**Comment by vshcherb** [comment]
This is issue is not reproducible as far as I see & it is related to a certain maps which may be corrupted, unfortunately it is hard to say which map is corrupted

**Comment by sonora** [comment]
Yes, very hard to reproduce consistently. I see this very rarely, but with maps which otherwise work, sometimes when using a destination "select on map", and usually rather early after the app start (maybe things are not completely initialized yet).
