### ISSUE TITLE
show osm notes later/higher zoom (configurable)

### ISSUE THREAD

**Issue by HolgerJeromin** [osmandapp/Osmand#4740]
I can overlay osm notes. 
But they are shown much too early and clutter the map.
Personaly i want them at the 500m level or even later.

**Comment by scaidermern** [comment]
Should be configurable or even adjusted automatically. They only clutter the map if there are lots of notes. If only a few notes are present and I'm actively searching for notes then I want them to be shown very early, i.e. at low zoom levels.

**Comment by dmpr0** [comment]
Also we need add setting to show only open or closed notes.
