### ISSUE TITLE
OsmAnd Live ignores newly added pedestrian ways for routing

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4742]
Example:

geo:34.075703,49.709606?z=18 
https://osmand.net/go?lat=34.075703&lon=49.709606&z=18

**Comment by scaidermern** [comment]
The [way](https://www.openstreetmap.org/way/538997170) is a highway=footway, not highway=pedestrian. However I've noticed the same behavior in my area.

Isn't the routing supposed to support changes from OsmAnd Live since OsmAnd 2.8?

**Comment by PaulStets** [comment]
Fixed with #4802, https://github.com/osmandapp/OsmAnd-core/pull/67
