### ISSUE TITLE
Some possible improvements for the APK size

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#4744]
Is it possible to distribute arch specific APKs?
https://developer.android.com/google/play/publishing/multiple-apks.html

For example, in `lib` we can see:

```
$ du -hs *
4,0M	armeabi
3,8M	armeabi-v7a
6,4M	mips
5,3M	x86
```

With their compacted size being:

```
$ du -hs *zip                             
1,7M	armeabi-v7a.zip
1,7M	armeabi.zip
2,6M	mips.zip
2,1M	x86.zip
```

ie, we could reduce, in average, the APK size by ~6M if we distribute it specifically to the supported architectures.

Another thing that could reduce it a little more:
`res` has 84M (85308KB) (compacted is 27M)
If we optimize the PNG files we could have it down to 83M (84012KB) (compacted as 23M)

I did use `optipng` for this.

With both it should gives us almost 10M.

**Comment by vshcherb** [comment]
This is not a case for Google distribution.

**Comment by KOLANICH** [comment]
@vshcherb, I don't understand what you mean. And how about F-Droid?
