### ISSUE TITLE
It takes too long to find address while adding favorite via quick action

### ISSUE THREAD

**Issue by iriman** [osmandapp/Osmand#4747]
It takes too long to find address while adding favorite via quick action button and there's no skip button, unlike adding it via context menu.
I think this is in contradiction with the aim of quick actions.
Also most of the time I use an specific name rather than the address of the point.

**Comment by stephan75** [comment]
Indeed!!

See #3696 where this already has been topic.

**Comment by iriman** [comment]
I didn't know that!
It's now so nice with the name I've wrote (a single space) and the interim dialog turned on.

But from where should someone know it? a hint on that would be so appreciated.

**Comment by iriman** [comment]
And of course a skip button makes the world somewhere easier to live in!

**Comment by vshcherb** [comment]
I think we should have button Skip & Enter name. Skip will assign a default Favorite name.
