### ISSUE TITLE
Feature request: option to copy profile-specific settings between profiles

### ISSUE THREAD

**Issue by iriman** [osmandapp/Osmand#4750]
For example to copy walking settings (such as quick actions, etc) for bicycle profile. Then it needs some small changes to best fit our needs. Now we should define settings for each profile from scratch.

**Comment by sonora** [comment]
I think that changes you make to the default (Browse map) profile are automatically copied to the other profiles (but not the other way round), so I guess this sort of creates some functionality to the effect you want.

**Comment by vshcherb** [comment]
I think it will only increase the confusion level in the end.
