### ISSUE TITLE
Add bus stop numbers in Vancouver

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4754]
In the Vancouver public bus system, the bus stop numbers are very prominent. The local operator Translink puts the numbers on every bus 
stop sign and uses them in their online system (e.g. to provide 
navigation and timetables).

Until this date, a lot of bus stop numbers can be found in the tags 
name=* and name:en=*. Often the bus stop number is only a substring and sometimes the values differ from each other.

In a local OSM meetup, it has been discussed that our bus stop numbers 
should be correctly mapped in ref=*. This will make it easier for 
applications to parse the bus stop number. Sadly, OSMAnd~ only shows 
ref=* if no name=* has been set. I ask you to make the ref tag more 
prominent, e.g.:

* Show it underneath the orange bus icon when clicking on the bus stop, 
* Include it in the list of details and/or 
* Make it part of the name as done with shops which include their 
house number in brackets.

The bus stop numbers of Vancouver consist of five digits. (e.g. 50583)

**Comment by xmd5a2** [comment]
https://github.com/osmandapp/OsmAnd-resources/commit/214a024cd9871a35b9a1da6b755cf3ac1cf50ee7

**Comment by xmd5a2** [comment]
Seems it's fixed now
