### ISSUE TITLE
development environment

### ISSUE THREAD

**Issue by ianmbetts** [osmandapp/Osmand#4756]
Hi Folks, newbie questions on dev environment

I have tried to interpret these notes ( https://groups.google.com/forum/#!msg/osmand/J0lcnZN0fLU/OT-4gQs_BwAJ ) however it appears the versions of JDK and SDK versions referenced are now obsolete and unavailable.

Is there a more up to date guide on setting up the development environment ?

So far by substituting JDK 8 (7 is no longer available) and using the default SDK version that is installed with Studio I can get a successful gradle build from the command line, allthough I do also see warnings about refusing to generate code for  .aidl files.

Is this even a reasonable setup ?
Should I expect these warnings ?

The .apk installs and runs but fails to render offline maps if I zoom out beyond 1km.
Any ideas what might be the cause ?

I am building r2.8 on a clean install ubuntu 16.04 host, I have tried with both open JDK and Oracle, both yield the same results.
 
The target is a quad core xgody chinese phablet (The playstore and F-droid versions both work perfectly on it).

Help much appreciated.
Thanks

**Comment by vshcherb** [comment]
It might googling could help though I'm not sure how we could help cause instructions looks pretty the same as should be. May be your question could answered on Google Groups
