### ISSUE TITLE
OSM Editing freezes the app while saving during navigation

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4757]
I have found that when the application is in navigation mode and I try to add an addition to the map using the editing plugin that the moment I hit the save button the interface goes into essentially a freezing mode where the save never completes and so I cannot return back to the main interface for navigation.

If I stop the navigation the problem with the editing plugin goes away.

**Comment by dmpr0** [comment]
I can't reproduce it on Samsung Galaxy A7 2016, Android 7.0, with and without internet.

**Comment by vshcherb** [comment]
Ok let's park it for now and see feedback later
