### ISSUE TITLE
[Minor bug] Misaligned bottom buttons.

### ISSUE THREAD

**Issue by franco999** [osmandapp/Osmand#4759]
**Hardware**: Motorola Moto E2 XT1527
**Software**: LineageOS 14.1 (Android 7.1.2), OsmAnd Nightly 3.0.0#19152D
**Problem**: When adding/editing a waypoint, the bottom buttons are misaligned. Once the keyboard of the device appears, it is re-aligned.
![1](https://user-images.githubusercontent.com/12088580/32850372-b0691c4c-ca10-11e7-933a-63b77b01290b.jpg)

**Comment by iriman** [comment]
Similar issue when trying to add a favorite through either quick actions or context menu, but you decide don't add it and hit cancel button.
In case of quick actions type a default name for Favorite "Name" and turn on "interim dialog".

**Comment by iriman** [comment]
thank you for fixing this. yet, there is tiny issue on latest build. Please see this short clip:
[osmandissue.zip](https://github.com/osmandapp/Osmand/files/1535218/osmandissue.zip)

**Comment by AlexSyt** [comment]
Was the interface corrected by itself or by your actions?

**Comment by iriman** [comment]
By itself. I didn't do any action.

**Comment by AlexSyt** [comment]
ok, i will take a look, thank you)
