### ISSUE TITLE
Bug: No "guide lines" for markers

### ISSUE THREAD

**Issue by SergeyP2** [osmandapp/Osmand#4761]
I turned "Show guide line" for markers, but there are no lines. I tried different combinations of options, closed and opened the app, yet there is still no guide lines. Looks like a bug. By the way, the name of the option isn't translated to Russian. The app version is 2.8.2 (2017-10-20).

![screenshot_2017-11-15-22-20-03](https://user-images.githubusercontent.com/22505250/32857120-893a7668-ca4f-11e7-99bd-e2ad8c5f43f3.png)
![screenshot_2017-11-15-22-20-15](https://user-images.githubusercontent.com/22505250/32857135-8f7418e0-ca4f-11e7-968d-a603d6b7ee7e.png)

**Comment by SergeyP2** [comment]
I've found the reason -- there is no guide lines when GPS is turned off, i. e. when app doesn't know my current location. Anyway this situation is looks misleading for user. I suggest to show guide lines from the center of the screen in case there is no current location.

**Comment by vshcherb** [comment]
Thank for report, It works as designed.

**Comment by SergeyP2** [comment]
OK, it works as designed, but why not to add guide lines from the screen center when there is no current location received from GPS?
