### ISSUE TITLE
Feature suggestion: Show direction only to top marker

### ISSUE THREAD

**Issue by SergeyP2** [osmandapp/Osmand#4762]
Right now the app shows directions to top two markers in the list. I should say that this behavior distract me as a user. I put my markers into some order and at any given moment of time I go or ride to only one point – the top one. When I see two arrows,  I need to do mental efforts every time to distinguish between the one I am going right now and some another that I will need only later – this is rather annoying. So I suggest to show direction to only one top marker, OR if there are some users that have explained why they need two directions simultaneously, then please add option "Show direction to one / two markers".

![screenshot_2017-11-15-23-15-11](https://user-images.githubusercontent.com/22505250/32858051-bfc5c96e-ca52-11e7-8c25-19cb99375344.png)

**Comment by pebogufi** [comment]
For me it is very helpful to have the *two* first markers.
Peter

**Comment by dmpr0** [comment]
Hello! Thank you for feedback. In current nightly version we already did setting for it, now you can choose quantity of active markers one or two, type of indication: top bar or widget, show arrows and show guide line or not. 
Here screenshot:
![screenshot_20171116-101138](https://user-images.githubusercontent.com/9365308/32880513-9b031028-cab6-11e7-927f-d70fc38e9d89.png)

**Comment by SergeyP2** [comment]
**dmpr0**, thanks a lot! :)
