### ISSUE TITLE
Bug: Excessive transliteration of default names

### ISSUE THREAD

**Issue by SergeyP2** [osmandapp/Osmand#4763]
When we choose the language of the map, there is an option to transliterate names is there is no name in specified language. I noticed then when I turn this option on for Russian language and I browse the map of Russia I see that 90% of Russian names became transliterated. I noticed that the chances to be transliterated are almost 100% for local objects (small streets, shops) and less for some prominent objects (rivers, towns). That led me to guess that the app transliterate "default" names (the names that don't have language tag in OSM database), even if actual language of the name is Russian. I assume that this is very widespread situation around the world, not only in Russia: most local names in OSM don't have language tag. To address this issue I suggest this algorithm:

IF we have "default" name (name that doesn't have language tag in OSM database)
THEN 
1) skip characters that belong to either chosen language alphabet or English alphabet 
2) transliterate other characters 

![01 screenshot_2017-10-11-14-54-21](https://user-images.githubusercontent.com/22505250/32859929-a550e20c-ca58-11e7-8026-6809d8b6f0c1.png)
![02 screenshot_2017-10-11-14-54-12](https://user-images.githubusercontent.com/22505250/32859938-ac7a4bb8-ca58-11e7-8b0b-7f166008a211.png)
![03 screenshot_2017-10-11-14-54-27](https://user-images.githubusercontent.com/22505250/32859962-bdf6be6c-ca58-11e7-851c-867c49d08b90.png)
![04 screenshot_2017-10-11-14-54-49](https://user-images.githubusercontent.com/22505250/32859966-c0fd0a3a-ca58-11e7-990a-8bbd4be09a31.png)

**Comment by vshcherb** [comment]
the option works only with  "name:ru" because language is not detected from the text itself
