### ISSUE TITLE
small distance precision

### ISSUE THREAD

**Issue by tobydickenson** [osmandapp/OsmAnd#4766]
In voice prompts, small distances up to 100m or 100 yards get rounded to multiples of 10 meters or yards.

The instruction "turn left, then in 10 meters turn right" can be misleading due this rounding. This particularly affects pedestrian voice guidance, where there can be several footpath turnings within 10 meters.

Ive been using a modified profile that uses 1m rounding for distances less than 18 meters. This is better, and no disadvantages observed so far.

**Comment by pebogufi** [comment]
Good idea !
Peter

**Comment by sonora** [comment]
If there was a pull request, I could probably find the time to review it ...  :)

**Comment by sonora** [comment]
PS: We also have to make a sanity / practice test: In most cases the exact location of a turn on a map is hard to specify with more than 5 m precision, while your GPS location usually comes with at least a 5 m error margin, plus the exact time when a voice prompt is prepared and actually sounds on a certain device and in a certain situation carries some spatial uncertainty while you are moving.

Pulling all this together I have severe doubt that pretending any precision better than 10 m in a voice prompt creates much benefit, or more benefit than confusion...

**Comment by tobydickenson** [comment]
Pull request to follow.

Re: GPS tolerance, and possible confusion. I agree we cant expect any distance measured __relative to your current position__ to be better than 5 or 10m. But that is not the goal here....

This is about voice guidance for distances __between mapped features__. For example heading northeast at https://www.openstreetmap.org/#map=19/50.88234/-1.26181 the footpath crosses a road, but the junctions are slightly staggered so the crossing is not exactly straight over. In reality I would guess staggered by maybe 3 or 4m. With 1m precision the voice guidance is "turn left, then in 6 meters turn right", which is not perfect, but definitely good enough to lead you down the right footpath.

However with 10m precision the voice guidance is "turn left, then in 10 meters turn right" which is most definitely misleading. Following that guidance will lead you down the driveway which is the second turning on the right.

That situation is probably very rare in car navigation - Ive certainly not heard my change make any difference yet in car use. But it is relatively common when using voice navigation on foot.

**Comment by hatzfeld** [comment]
I use OSMand often for bike routing. And there is a special issue with bike (and maybe pedestrian) routing when there are direction changes like: turn right, after 3 meters turn left, after 3 meters turn right, then go straight on for 2km. It is impossible to follow the single turns, and the voice creates more confusion (imagine what I get to hear when all the street names are mentioned!); so it would be better to neglect very short ways and to indicate a kind of "general direction", in this case: Turn right (into the xy road).
