### ISSUE TITLE
Cannot clear names of bus stops

### ISSUE THREAD

**Issue by jaller94** [osmandapp/Osmand#4767]
I'm trying to edit bus stops that have a bus stop number in their `name=*` instead of `ref=*´. Adding the `ref` tag works but it seems like cannot clear the `name` tag.

I cleared all stop numbers (from the `name` tag) in the following change set, however, they are still there:
https://www.openstreetmap.org/changeset/53827376

To confirm this I created another change set to remove the name of only one bus stop:
https://www.openstreetmap.org/changeset/53827607

### Setup:
- OSMAnd~ 2.7.5 for Android from the F-Droid store.
- Unofficial LinageOS 14.1 build for marmite (Wileyfox Swift 2 Plus); Android 7.1.2
- I use the Standard off-line map of British Columbia with OSM Live updates from today. (2017-11-16T03:27:00Z)

### Reproduce:
1. Start editing a bus stop.
2. Select the name of the stop and 'Cut' it (not sure if using cut is important).
3. Click Save
4. Upload the Changed POI to OpenStreetMap.

I had the suspicion that this was happening over the last couple of days before confirming it today. This might be a fairly fresh regression.

**Comment by xmd5a2** [comment]
Are you using OsmAnd live or creating new obf manually?
Also I've added ref from bus stops to map like house numbers https://github.com/osmandapp/Osmand/issues/4754

**Comment by jaller94** [comment]
I'm using the OSMAnd live updates.

**Comment by jaller94** [comment]
F-Droid has a new beta release 2.8.2.
The issue still exists for me.
Here is a new changeset where the name=* should be empty now. I wonder if its a problem of my configuration/system, the F-Droid releases or the app in general.
http://www.openstreetmap.org/changeset/54015809

**Comment by PaulStets** [comment]
@jaller94 Unfortunately, OsmAnd Live does not yet include the transport information in the updates. We will work to solve this in the nearest future.
