### ISSUE TITLE
Error with the running the Application

### ISSUE THREAD

**Issue by Keurmerk** [osmandapp/Osmand#4768]
I am currently trying to figure out how to get Osmand running in Android studio. 
I used this guide to do it: (https://groups.google.com/forum/#!msg/osmand/J0lcnZN0fLU/OT-4gQs_BwAJ) 
Only this part i failed: _"click on the project tab far left and open under Gradle Scripts the build.grade for module Osmand-SRTMPlugin 
change the dependencies at the bottom to this..

dependencies { 
   compile "com.android.support:appcompat-v7:23.0.+" 
}"_

 The build was still succesfull, but if i try to run the application on my Phone it gives errors. 

Phone= Samsung galaxy S7 with API 24, i enabled debugging. Other application from android studio worked correctly. 

**Android studio:**
Android Studio 3.0
Build #AI-171.4408382, built on October 20, 2017
JRE: 1.8.0_152-release-915-b08 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

**The errors**
Information:Gradle tasks [:OsmAnd:assembleFreeLegacyFatDebug]
Warning:The `android.dexOptions.incremental` property is deprecated and it has no effect on the build process.
Warning:string 'add_gpx_waypoint_bottom_sheet_title' has no default translation.
Warning:string 'add_route_point' has no default translation.
Warning:string 'build_route' has no default translation.
Warning:string 'driving_style_balance' has no default translation.
Warning:string 'driving_style_safety' has no default translation.
Warning:string 'driving_style_speed' has no default translation.
Warning:string 'map_route_by_gpx' has no default translation.
Warning:string 'marker_options' has no default translation.
Warning:string 'measurement_tool_altitude' has no default translation.
Warning:string 'measurement_tool_speed' has no default translation.
Warning:string 'osmand_extended_description_4000_chars' has no default translation.
Warning:string 'osmand_plus_extended_description_4000_chars' has no default translation.
Warning:string 'osmand_plus_extended_description_4000_chars_v2' has no default translation.
Warning:string 'osmo_use_https' has no default translation.
Warning:string 'poi_bedding' has no default translation.
Warning:string 'poi_building_poi' has no default translation.
Warning:string 'poi_car_wash_self_service' has no default translation.
Warning:string 'poi_conservation' has no default translation.
Warning:string 'poi_counselling_type_nutrition_no' has no default translation.
Warning:string 'poi_dishes' has no default translation.
Warning:string 'poi_furnace' has no default translation.
Warning:string 'poi_general_tourist_attraction_yes' has no default translation.
Warning:string 'poi_health_facility_type_clinic' has no default translation.
Warning:string 'poi_health_facility_type_health_centre' has no default translation.
Warning:string 'poi_health_facility_type_hospital' has no default translation.
Warning:string 'poi_health_facility_type_pharmacy' has no default translation.
Warning:string 'poi_health_facility_type_rehabilitation' has no default translation.
Warning:string 'poi_historic_monastery' has no default translation.
Warning:string 'poi_information_wildlife' has no default translation.
Warning:string 'poi_level_crossing' has no default translation.
Warning:string 'poi_medical_system_unknown_yes' has no default translation.
Warning:string 'poi_mill_pond' has no default translation.
Warning:string 'poi_payment_none' has no default translation.
Warning:string 'poi_sanitary_dump_station_customers' has no default translation.
Warning:string 'poi_stars_6' has no default translation.
Warning:string 'poi_stars_7' has no default translation.
Warning:string 'poi_team_handball' has no default translation.
Warning:string 'poi_tourism_attraction' has no default translation.
Warning:string 'range_min_max' has no default translation.
Warning:string 'relief_smoothness_factor_plains' has no default translation.
Warning:string 'routing_attr_driving_style_description' has no default translation.
Warning:string 'routing_attr_height_relief_smoothness_factor_description' has no default translation.
Warning:string 'routing_attr_height_relief_smoothness_factor_name' has no default translation.
Warning:string 'shared_string_create' has no default translation.
Warning:string 'shared_string_navigate' has no default translation.
Warning:string 'tip_day_night_mode' has no default translation.
Warning:string 'tip_faq' has no default translation.
Warning:string 'tip_navigation' has no default translation.
Warning:string 'top_bar' has no default translation.
Warning:string 'voice_not_use' has no default translation.
Warning:string 'widget' has no default translation.
/Users/jesperkeur/Osmand/Osmand/OsmAnd/src/net/osmand/access/AccessibilityAssistant.java
Error:(33, 34) error: incompatible types: Application cannot be converted to OsmandApplication
/Users/jesperkeur/Osmand/Osmand/OsmAnd/src/net/osmand/plus/AppInitializer.java
Error:(144, 19) error: cannot find symbol method getSharedPreferences(String,int)
Error:(256, 64) error: incompatible types: Application cannot be converted to OsmandApplication
Error:(332, 17) error: cannot find symbol method getString(Integer)
Error:(351, 80) error: incompatible types: OsmandApplication cannot be converted to Context
Error:(355, 18) error: incompatible types: OsmandApplication cannot be converted to Context
Error:(364, 67) error: incompatible types: OsmandApplication cannot be converted to Context
Error:(390, 16) error: cannot find symbol method getString(int)
Error:(392, 16) error: cannot find symbol method getString(int)
Error:(394, 16) error: cannot find symbol method getString(int)
Error:(396, 16) error: cannot find symbol method getString(int)
Error:(398, 16) error: cannot find symbol method getString(int)
Error:(400, 16) error: cannot find symbol method getString(int)
Error:(402, 16) error: cannot find symbol method getString(int)
Error:(404, 16) error: cannot find symbol method getString(int)
Error:(453, 77) error: cannot find symbol method getString(int)
Error:(454, 8) error: cannot find symbol method getString(int)
Error:(555, 45) error: cannot find symbol method getSystemService(String)
Error:(567, 19) error: incompatible types: OsmandApplication cannot be converted to Context
Error:(568, 50) error: incompatible types: OsmandApplication cannot be converted to Context
Error:(594, 18) error: cannot find symbol method getString(int)
Error:(632, 21) error: cannot find symbol method getString(int)
Error:(636, 18) error: cannot find symbol method getString(int)
Error:(778, 25) error: cannot find symbol method getPackageName()
/Users/jesperkeur/Osmand/Osmand/OsmAnd/src/net/osmand/plus/OsmandApplication.java
Error:(17, 32) error: package android.support.multidex does not exist
Error:(18, 32) error: package android.support.multidex does not exist
Error:(76, 40) error: cannot find symbol class MultiDexApplication
Error:(130, 2) error: method does not override or implement a method from a supertype
Error:(142, 3) error: cannot find symbol variable super
Error:(180, 2) error: method does not override or implement a method from a supertype
Error:(182, 3) error: cannot find symbol variable super
Error:(183, 3) error: cannot find symbol variable MultiDex
Error:(195, 13) error: incompatible types: OsmandApplication cannot be converted to Context
Error:(211, 2) error: method does not override or implement a method from a supertype
Error:(213, 3) error: cannot find symbol variable super
Error:(309, 2) error: method does not override or implement a method from a supertype
Error:(311, 3) error: cannot find symbol variable super
Error:(315, 2) error: method does not override or implement a method from a supertype
Error:(318, 4) error: cannot find symbol variable super
Error:(323, 67) error: cannot find symbol method getBaseContext()
Error:(323, 4) error: cannot find symbol method getBaseContext()
Error:(326, 4) error: cannot find symbol variable super
Error:(331, 26) error: cannot find symbol method getBaseContext()
Error:(349, 64) error: cannot find symbol method getBaseContext()
Error:(349, 4) error: cannot find symbol method getBaseContext()
Error:(354, 64) error: cannot find symbol method getBaseContext()
Error:(354, 4) error: cannot find symbol method getBaseContext()
Error:(516, 3) error: cannot find symbol method startActivity(Intent)
Error:(527, 33) error: no suitable constructor found for Intent(OsmandApplication,Class<NavigationService>)
constructor Intent.Intent(String,Uri) is not applicable
(argument mismatch; OsmandApplication cannot be converted to String)
constructor Intent.Intent(Context,Class<?>) is not applicable
(argument mismatch; OsmandApplication cannot be converted to Context)
Error:(528, 4) error: cannot find symbol method stopService(Intent)
Error:(565, 61) error: cannot find symbol method getBaseContext()
Error:(566, 39) error: cannot find symbol method getBaseContext()
Error:(583, 60) error: cannot find symbol method getPackageName()
Error:(583, 25) error: cannot find symbol method getPackageManager()
Error:(601, 40) error: cannot find symbol method getSystemService(String)
Error:(631, 44) error: cannot find symbol method getString(int,Object[])
Error:(640, 10) error: no suitable method found for makeText(OsmandApplication,String,int)
method Toast.makeText(Context,CharSequence,int) is not applicable
(argument mismatch; OsmandApplication cannot be converted to Context)
method Toast.makeText(Context,int,int) is not applicable
(argument mismatch; OsmandApplication cannot be converted to Context)
Error:(649, 44) error: cannot find symbol method getString(int,Object[])
Error:(658, 10) error: no suitable method found for makeText(OsmandApplication,String,int)
method Toast.makeText(Context,CharSequence,int) is not applicable
(argument mismatch; OsmandApplication cannot be converted to Context)
method Toast.makeText(Context,int,int) is not applicable
(argument mismatch; OsmandApplication cannot be converted to Context)
Error:(743, 65) error: cannot find symbol method getBaseContext()
Error:(743, 5) error: cannot find symbol method getBaseContext()
Error:(782, 34) error: cannot find symbol method getSystemService(String)
Error:(787, 58) error: cannot find symbol method getPackageName()
Error:(787, 23) error: cannot find symbol method getPackageManager()
Error:(796, 58) error: cannot find symbol method getPackageName()
Error:(796, 23) error: cannot find symbol method getPackageManager()
Error:(805, 32) error: no suitable constructor found for Intent(OsmandApplication,Class<NavigationService>)
constructor Intent.Intent(String,Uri) is not applicable
(argument mismatch; OsmandApplication cannot be converted to String)
constructor Intent.Intent(Context,Class<?>) is not applicable
(argument mismatch; OsmandApplication cannot be converted to Context)
Error:(815, 3) error: cannot find symbol method startService(Intent)
Error:(825, 12) error: cannot find symbol method getString(Integer)
/Users/jesperkeur/Osmand/Osmand/OsmAnd/src/net/osmand/plus/GPXUtilities.java
Error:(1195, 14) error: cannot find symbol method getString(int)
Error:(1271, 14) error: cannot find symbol method getString(int)
Error:(1274, 14) error: cannot find symbol method getString(int)
/Users/jesperkeur/Osmand/Osmand/OsmAnd/src/net/osmand/plus/GeocodingLookupService.java
Error:(175, 21) error: cannot find symbol method getString(int)
/Users/jesperkeur/Osmand/Osmand/OsmAnd/src/net/osmand/plus/TargetPointsHelper.java
Error:(174, 78) error: incompatible types: OsmandApplication cannot be converted to Context
Error:(196, 63) error: incompatible types: OsmandApplication cannot be converted to Context
Error:(217, 69) error: incompatible types: OsmandApplication cannot be converted to Context
Error:(511, 67) error: incompatible types: OsmandApplication cannot be converted to Context
Error:(546, 67) error: incompatible types: OsmandApplication cannot be converted to Context
/Users/jesperkeur/Osmand/Osmand/OsmAnd/src/net/osmand/plus/routing/RouteProvider.java
Error:(794, 50) error: cannot find symbol method getString(int)
Error:(796, 50) error: cannot find symbol method getString(int)
Error:(798, 50) error: cannot find symbol method getString(int,String)
Error:(833, 94) error: incompatible types: OsmandApplication cannot be converted to Context
Error:(1080, 25) error: cannot find symbol method getString(int,String)
Error:(1082, 20) error: cannot find symbol method getString(int,String)
Error:(1087, 20) error: cannot find symbol method getString(int,String)
Error:(1208, 34) error: no suitable method found for loadGPXFile(OsmandApplication,ByteArrayInputStream)
method GPXUtilities.loadGPXFile(Context,File) is not applicable
(argument mismatch; OsmandApplication cannot be converted to Context)
method GPXUtilities.loadGPXFile(Context,InputStream) is not applicable
(argument mismatch; OsmandApplication cannot be converted to Context)
/Users/jesperkeur/Osmand/Osmand/OsmAnd/src/net/osmand/plus/OsmandSettings.java
Error:(260, 55) error: cannot find symbol method getSystemService(String)
Error:(270, 55) error: cannot find symbol method getSystemService(String)
Error:(1514, 13) error: cannot find symbol method getFilesDir()
Error:(1519, 25) error: cannot find symbol method getExternalFilesDirs(<null>)
Error:(1529, 13) error: cannot find symbol method getNoBackupFilesDir()
Error:(1545, 25) error: cannot find symbol method getExternalFilesDirs(<null>)
Error:(1552, 25) error: cannot find symbol method getObbDirs()
Error:(1620, 26) error: cannot find symbol method getExternalFilesDirs(<null>)
Error:(2443, 77) error: incompatible types: OsmandApplication cannot be converted to Context
Error:(2455, 78) error: incompatible types: OsmandApplication cannot be converted to Context
Error:(2055, 77) error: incompatible types: OsmandApplication cannot be converted to Context
Error:(2077, 78) error: incompatible types: OsmandApplication cannot be converted to Context
Error:(2203, 77) error: incompatible types: OsmandApplication cannot be converted to Context
Error:(2229, 78) error: incompatible types: OsmandApplication cannot be converted to Context
Error:Execution failed for task ':OsmAnd:compileFreeLegacyFatDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED in 8m 32s
Information:101 errors
Information:52 warnings
Information:See complete output in console

I am really new to android studio and this whole world of developing, i googled alot but couldn't find an answer. I hope someone can help me...

**Comment by PavelRatushnyi** [comment]
Try adding this to build.gradle file.
dependencies {
  compile 'com.android.support:multidex:1.0.1'
}

**Comment by Keurmerk** [comment]
It worked Thanks!!
