### ISSUE TITLE
Unable to hide house numbers

### ISSUE THREAD

**Issue by bambamal** [osmandapp/Osmand#4772]
The menu item 'Hide -> House numbers' has no effect. It is exactly the same issue as #4372, but it doesnt seem to be fixed to me.

![screenshot_20171116-223826](https://user-images.githubusercontent.com/33735248/32917918-ebf89e98-cb20-11e7-964a-cec419a4ade0.png)

**Comment by xmd5a2** [comment]
Please provide exact issue location

**Comment by scaidermern** [comment]
Looks to be here: https://www.openstreetmap.org/#map=18/49.60170/10.97975

**Comment by bambamal** [comment]
Lat 49.60161 Lon 10.98060

As far as I can tell it happens everywhere though, independet of the location.

**Comment by scaidermern** [comment]
Hiding house numbers works for me. Except if they are mapped as entrances in which this case the hiding option has no effect on them (e.g. here: https://www.openstreetmap.org/#map=19/51.04782/13.78061). This doesn't seem to be the case in your area though.

**Comment by xmd5a2** [comment]
Can't reproduce with latest nightly
![screenshot from 2017-11-17 21-46-33](https://user-images.githubusercontent.com/5829014/32963417-e9bbca40-cbe0-11e7-8e29-43e0a6d89d8e.png)

**Comment by bambamal** [comment]
Im using Version 2.8.2. 
I tried another map (Austria, Lat 48.21191 Lon 16.35465) and found, that only some house numbers will be hidden.
![screenshot_20171117-194534](https://user-images.githubusercontent.com/33735248/32963463-4d80f2be-cbd0-11e7-869d-de698988b89d.png)
![screenshot_20171117-194548](https://user-images.githubusercontent.com/33735248/32963466-5067f144-cbd0-11e7-8ad6-5e92544b7bc9.png)

**Comment by xmd5a2** [comment]
@bambamal It does not seem to be a default rendering style

**Comment by bambamal** [comment]
Its a dependent style which only changes some colors. Same Issue with the default styles. I tested with 'OsmAnd'-style to make sure.

**Comment by xmd5a2** [comment]
Anyway, I can't reproduce issue with latest development version (nightly) http://download.osmand.net/latest-night-build/
If I can't reproduce then I can't fix it.

**Comment by scaidermern** [comment]
Regarding house numbers at entraces (my comment from above).

With house numbers enabled:
![photo_2017-11-17_20-31-47](https://user-images.githubusercontent.com/1040784/32965331-72753f8e-cbd6-11e7-8eac-c298016c4712.jpg)


With house numbers disabled:
![photo_2017-11-17_20-31-42](https://user-images.githubusercontent.com/1040784/32965341-7a18ed80-cbd6-11e7-9a29-167d5e1e0753.jpg)

House numbers at entrances are still getting displayed, e.g. https://www.openstreetmap.org/node/501955796

**Comment by bambamal** [comment]
@scaidermern I think this is a different issue. I deliberately picked an area without entrances.

@xmd5a2 Even if you try higher zoom levels, no house numbers are being shown in the mentioned area?

I find it very strange, that only some house numbers can not be hidden (see mypost above). Could it be different types of buildings? If nobody has any idea what might be the cause of this, I'll try the nightly build and compare.

**Comment by xmd5a2** [comment]
@bambamal It will be easier if you test the latest version because I don't see issue at all

**Comment by bambamal** [comment]
So I installed the latest nightly version, used shared memory as the data folder and house numbers were hidden as expected. Then i checked the normal version from the playstore again, and what do you know, it now also works as expected. Isnt that strange. Did the installation maybe update the rendering style?

As @scaidermern mentioned, entranced will be labeled with the house number anyway, which i think is unexpected and an issue in itself.

But for now it seems fixed, thanks for the help.
