### ISSUE TITLE
Multi Window / Split Screen in Android 8.0 not supported

### ISSUE THREAD

**Issue by alpha197** [osmandapp/Osmand#4774]
Behaviour:
Osmand UI stops updating UI in splitscreen mode on Android 8.0 (Nexus 5X) when using the other app (Osmand window unfocused).

Expected Behaviour:
UI working as intended when using the app running in the other splitscreen half.

I know issue #3730, but that belongs to Android 7.0 and issue is closed without solution.

**Comment by flohoff** [comment]
Same issue with CM14.1 aka Android 7.1.2 on HTC 10 - I'd like to have osmtracker + osmand running so i see passed streets on the map and still record button presses with osmtracker.
