### ISSUE TITLE
Feature Request: Add the ability to share the poi name.

### ISSUE THREAD

**Issue by itzikiap** [osmandapp/Osmand#4777]
Hi. In the case I find a poi I'm interested in, but it doesn't have a complete info, I would like to be able to "share" the poi name with the browser, to Google about it. 

Thanks.

And thank you for the app. 😀

**Comment by PaulStets** [comment]
Fixed with https://github.com/osmandapp/Osmand/pull/4956. Now you can share the name of a point in the Share menu - Copy Point/POI name.
