### ISSUE TITLE
OSM Live "Update now" does nothing

### ISSUE THREAD

**Issue by contrapunctus-1** [osmandapp/Osmand#4780]
OsmAnd v2.7.5 from F-Droid

Pressing overflow menu button - OSM Live (Beta) - <my region> - "Update Now" displays a spinner but does not do anything, even though there have been changes, and 'update size' is >0. The map is not updated.

Additionally, automatic update isn't working for me, either, regardless of whether I'm on mobile data or WiFi or whether I have "only download over WiFi" enabled or disabled.

I'm fairly certain that both of these features used to work earlier.

**Comment by majkaz** [comment]
Working for me right now. There was a period of about 2 days,  where OSM live didn't have updates (cca 17.11.-19.11). You can look at the "last map date" for info if Osmand sees new data. The size isn't as important,  it shows size since last full map download.

**Comment by vshcherb** [comment]
In 2.8 the date is displayed & it is also visible on website.
https://www.osmand.net/osm_live - Current processed OsmAnd Live date: 2017-11-19 13:45 UTC
The issue has been fixed

**Comment by contrapunctus-1** [comment]
It started working again for a few days, but the problem is now back. What causes this? It disrupts my editing (for some reason, I prefer adding POIs in OSMand on the ground, rather than in Vespucci, JOSM, or ID) - uploaded POIs disappear from the map, and aren't visible till one updates the map.
