### ISSUE TITLE
Group Drawer items by 'base-fuctionality' and 'configuration' related

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#4781]
Let me raise this https://github.com/osmandapp/Osmand/commit/5e1b3e053c9fcebed8d9fba682d18c83dea3a817#comments as  separate Issue here for better visibility.

The best Drawer appearance I can come up with for now is the following (division line is before Configure map)), and it can be achieved by simply reversing the commit referenced above.

<img width="108" alt="screenshot_2017-11-19-11-03-47_" src="https://user-images.githubusercontent.com/845735/32989608-f7b3e828-cd19-11e7-823c-0335e053ba5a.png">

**Comment by vshcherb** [comment]
Disagree but I already reacted in the  5e1b3e0#comments

**Comment by vshcherb** [comment]
I think 2 groups are mostly stable now.
