### ISSUE TITLE
Feature suggestion: add negative speed limitation alert

### ISSUE THREAD

**Issue by huitre39** [osmandapp/Osmand#4783]
Hello i have small suggerstion for osmand.
When i use this application in my phone, the speedometer in osmand is 5km/h less than the reality.

When i want use speed limitation alert, i want to add possibility to choose negative number.
Like -1.0, -2.0, -3.0, or -5.0km/h
![speed](https://user-images.githubusercontent.com/22101022/32989960-a2147dc2-cd20-11e7-98df-83f66a9219d5.png)

**Comment by scaidermern** [comment]
> the speedometer in osmand is 5km/h less than the reality

The speedometer is probably correct and represents reality. Cars however show you a higher speed than you are actually driving because this is the way their speedometers are calibrated.

**Comment by huitre39** [comment]
ok.
But do you think it would be possible to add a negative value?

**Comment by TimMagee** [comment]
Or how about add a "custom" option that allows the user to enter anything he/she wants including negative values?

**Comment by PaulStets** [comment]
Fixed with https://github.com/osmandapp/Osmand/pull/4955
