### ISSUE TITLE
Changing name of favourite sets map marker

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#4795]
when I change the name of a favourite, after saving is has been flagged with a map marker.
This was not indended.
Peter
osmand 3.0.0#23189M

**Comment by vshcherb** [comment]
Not clear how does it happen.

**Comment by pebogufi** [comment]
After making about 20 tests I could reproduce it only one time. It looks like when wiping down the window with the buttons edit/flag/share/3-dots-menu I touched the flag and so created the map marker. But only 1 of 20.
So I close that issue and try my best. Sorry to bother you...
Peter
