### ISSUE TITLE
Incorrect search result in Berlin

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4801]
While searching for 'Neue Jüdenstraße' in Berlin gives no result (both in quick and address search), search for 'Jüdenstraße' displays the correct 'Neue Jüdenstraße' as one of the results.

http://www.openstreetmap.org/way/43159545#map=19/52.51552/13.41049

**Comment by pebogufi** [comment]
This is my result using osmand 3.0.0#23189
![screenshot_2017-11-24-17-23-18](https://user-images.githubusercontent.com/18628183/33218331-aaad3b5c-d13c-11e7-9eb2-dd6ab86b4a4b.png)

**Comment by PaulStets** [comment]
Very strange, I have checked right now and was also able to find the street. But it was as I described this morning. Anyway since it works correctly, I will close the issue.
