### ISSUE TITLE
Deal with apostrophes as a word separator

### ISSUE THREAD

**Issue by Codain** [osmandapp/Osmand#4803]
In French we sometime use an apostrophe (or single quote). The OsmAnd search feature is not able to handle them as word separators.

For instance, whene "in" Paris, search for the shop "L'Art du papier" .

If I search for "Art du papier" it does not propose me the shops whereas if I search for "L'Art du papier" it gives me good results.

The proposal is to handle apostrophes in French as a regular word separator.

**Comment by int-ua** [comment]
Just curious, what Unicode symbol are you using as apostrophe? In Ukrainian apostrophe is the opposite, just another letter, and I've had some troubles when it was recognised as word separator instead causing wrong letter cases.

**Comment by Codain** [comment]
It's a good question.

The one we should use in French is the dactilographic one (U+2019) but computers and smartphones usually impose to the "straight" apostrophe (U+0027). To not mix with U+02BC which is like the first one instead that it is used **inside** a single word (and not to concatenate two words).

To conclude:
- Shall be considered as a word separator:
  - U+2019
  - U+0027
- Shall not be considered as a word separator:
  - U+02BC

Sources:
- https://fr.wikipedia.org/wiki/Apostrophe_(typographie)
- https://en.wikipedia.org/wiki/Apostrophe#Unicode

**Comment by int-ua** [comment]
Yes, there is no clear consensus about this in Ukrainian community but I completely agree on the U+02BC

Reference:
https://ukrainian.stackexchange.com/questions/40/Який-символ-використовувати-для-позначення-апострофа-в-електронних-текстах-украї

**Comment by Codain** [comment]
After digging in source code, I found that OsmAnd handles differently "common words" such as "la" , "le" , "de" ...

In French "L'" is a shorten of "Le" or "La" and "D'" is a shorten of "De" or "Du". Consequently a good way of solving this issue would be, in both the search string and the index:

1. to split words according to previous discussions (for instance replace apostrophes by a space or by an apostrophe+space?). "L'Art du Papier" would be handled the same way as "L' Art du Papier" or "L Art du Papier"
2. To make sure L or L' or D or D' is handled as a common word.

I hope to hear good news on this one in order to simplify and enhance searches :-)

**Comment by vshcherb** [comment]
Merged into #4491, it will be handled together. This we need to improve & french provides  a good case.

**Comment by vshcherb** [comment]
It is unclear why but since 2012 it was always "exceptional"
https://github.com/osmandapp/OsmAnd-tools/commit/aa57122150dbf13830cf682cc17d7b2cd82545a4.
Let's try to see what happens if change it.
@sonora @xmd5a2 if you recall anything about it, please let me know
