### ISSUE TITLE
Calculated route quirks

### ISSUE THREAD

**Issue by Siltaar** [osmandapp/Osmand#4809]
Hi,

I wanted to share some small issues on computed roads.

Using : OsmAnd 2.7.5
Map of France : 1 novembre 2017 

**First example Amailloux / La Couaillère**

On D19, from Amailloux to La Couaillère (south of Clessé, https://www.openstreetmap.org/relation/147247#map=15/46.7030/-0.4045) the navigation tels me to pass through the "city center" of Clessé, instead of the no-name route in front of the D46.

If I, nonetheless go through this last road, the re-calculation of the route is ok to go this way, and find that it's a few minutes shorter.

_May be an ongoing optimizer re-routing calculation may have find this short hand ?_

Could be linked to : https://github.com/osmandapp/Osmand/issues/3755

**Another example Amailloux / Thouars**

From Amailloux to Thouars, at the D938 / D170 crossroad, instead of sticking on the main 2x2 way road, the computed route tels to quit and use a small side road, for 1km or so before getting back to the main road. Here also, sticking on the main road is recognized as quicker when re-calculation occurs. (I also see that the 2 roads have the same name/number…).

https://www.openstreetmap.org/relation/147247#map=15/46.8482/-0.2089

It's worth noting that at the return time, the error is not made. So computing for both directions may help smoothening the route.

Like for the out-in at D938 / D162 crossroad from north to south… OSMand tells me to out the road and immediately turn back in, as if I was to use the entrance way while I'm already in. Here:
https://www.openstreetmap.org/relation/147247#map=14/47.0404/-0.1979

**Another example Noyen-sur-Sarthe**

From Sablé-sur-Sarthe to Mezeray.

At Parcé-sur-Sarthe, OsmAnd invite to take the D8 to pass through Malicorne. But I continue via the D309 toward Noyen-sur-Sarthe.

At Noyen-sur-Sarthe, OsmAnd invite me to turn on the right via the D41 to go back to Malicorne.
I continue on the D309.

200m away, OsmAnd have recalculated the way, throught D309. The new route is now 5 minute shorter than the 1st one, through Malicorne.

_Here, being able to trigger a full route calculation instead of letting OsmAnd trying to get me back to the 1st track would help._

**Comment by vshcherb** [comment]
2nd issue is fixed & will be in new maps. 1st might be related to 2nd.

The 3rd issue works as designed, so full recalculation happens after 3 quick attempts. It is done in order to improve the speed of calculation.
