### ISSUE TITLE
Speed limit and Speedcam warning not working correctly

### ISSUE THREAD

**Issue by juhanjuku** [osmandapp/Osmand#4810]
In Car mode 'Speed limit' is shown and Speedcam warning is working only when navigation is active. Without navigation 'Speed limit' is not shown regardless 'Configure screen' settings. Same time also speedcam warnings stop working.
Strange, but sometimes randomly all works correctly for short time.
Issue started few months ago, didn't noticed exactly after what update.
OsmAnd+ 2.8.2, Android 6.0.1, SonyXperia Z3C

**Comment by vshcherb** [comment]
You need to change the mode to "Car" or to "Bicycle" in Configure Map/Screen Settings.

**Comment by juhanjuku** [comment]
I don't understand your comment? I have Car mode activated when having this issue.

**Comment by sonora** [comment]
You need to start a navigation (using Go) to activate the voice guidance. I think then it may work (for that app session) even after stopping the navigation again.

**Comment by juhanjuku** [comment]
Sometimes this helps, but not always. 
I think this issue when I have chosen to see Speed limit for a road, but app is not showing it.

**Comment by polarbearing** [comment]
> You need to briefly start a navigation (using Go) to activate the voice guidance.

See proposal in #3521

**Comment by juhanjuku** [comment]
I'm not talking about voice guidance. I just like to see speed limit on screen during driving in Car mode, like it worked all the time.

**Comment by juhanjuku** [comment]
Your suggestion:
(You need to change the mode to "Car" or to "Bicycle" in Configure
Map/Screen Settings.)
does hot help me at all.
Can you please at least try to reproduce this bug before closing ticket.

**Comment by polarbearing** [comment]
@juhanjuku you should be more specific in your bug descriptions to avoid confusion.

I just switched on my device, and it does show the correct  max speed widget, according to the street it snaps on.
