### ISSUE TITLE
More efficient Quick Search UI behavior

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#4812]
Our Quick Search is comparatively slow vs. what users expect from an efficient map app. Bad user  experience is aggravated by the fact that our search UI does not behave very efficiently while the user types the `searchEditText`. Here are 2 common use cases and their desirable target behavior:

**(A)** User adds a character to the end of the search text:

- (A1) The list of any already previously found search hits must simply be filtered (as to whether they contain the new search text as well), but these filtered results need to **remain visible on the search results screen.** (Today we always delete all search results and face the user with the empty list of search hits being re-built form the start.)
 - (A2) If the search was already finished before the user added the new character, the search must not even be re-started, as the list of search hits is simply the above filtered sub-list of the already existing search hits (for the given search radius).

**(B)** User deletes a character from the end of the search text (by tapping the backspace key)
 - (B1) The search needs to be restarted, but any existing search results on the screen need to be remain visible! Today we always re-set the screen of current search results to being empty again..

**Comment by itzikiap** [comment]
I have another suggestion (I'll open a new issue if you'll requested):
Try searching first with very small radius, gradually increasing it and adding to the list, until it reaches the requested "search radius".

**Comment by sonora** [comment]
@itzikiap Yes, we have a number of search issues, I think, and there are different strategies how to improve. I think what you suggest is not the solution to what I report here. For the purpose of this issue, the strategy needs to be more something like "Do not throw away already found search hits when the users changes the searchEditText. Instead, intelligently re-use/re-search any found hits."

**Comment by vshcherb** [comment]
I couldn't agree with original issue cause it actually works more complicated. Though I will need to check & come back with detailed explanation, possibly some issues could be found.

**Comment by sonora** [comment]
@vshcherb Maybe we should broaden the initiative a little, I have an overall feeling there may be a problem with our search: #4829.

**Comment by vshcherb** [comment]
@crimean 
I think here we should document how the search works and give some numbers key indication where the time spent. Generic desription of the algorithm would be great.
1. I also see if we could print into debug what takes time & how much if development plugin is enabled
2.  If we explain the concepts of 2 phase search here and make it traceable it could help @sonora  to understand where do we loose so much time and speed up the process of suggesting new ideas.

**Comment by crimean** [comment]
Hello Hardy, I [added](https://github.com/osmandapp/Osmand/commit/79408dc5a7dc86f13f97d67ebf72f882a69bee73) logging of search steps. It work if development plugin is enabled. Please do some tests and may be send me log(s).

I will prepare generic description of the search algorithm soon.

**Comment by sonora** [comment]
Alexey, thanks!

Maybe some of the users participating in #4829 could assist by sending their logs, I am currently out traveling and have no access to Android SDK or a rooted device.

As I already stated: The main 2 issues seem to be:
- If you have a few dozen maps on your device, the search becomes unproportionally slow
- Successive typing or deletion of characters in the search text box seems to always delete reset the entire search results screen, i.e. deletes ALL previously found and displayed results. But of course, when adding a trailing character to the search string, some of the previously found results will remain valid hits and should remain visible, and when deleting a trailing character, all previously found results should remain valid and visible.

**Comment by crimean** [comment]
1. We have search phrase which contains resolved and unresolved part. Resolved part is like POI type City, Street, etc. Unresolved is a unknown word at the end of search phrase.

2. There are number of search API we are running during the search:

	- SearchAmenityByNameAPI (search any POI by unknown word and given location and radius)
	- SearchAmenityByTypeAPI (search POI of given type by unknown word and given location and radius)
	- SearchAmenityTypesAPI (search POI type by unknown word)

	- SearchAddressByNameAPI (search city, street, building or intersection by unknown word)
	- SearchStreetByCityAPI (search street in given city by unknown word)
	- SearchBuildingAndIntersectionsByStreetAPI (search building or intersection on given street by unknown word)

	and others - for searching Favorites, History, Wypoints, Location.

3. Search workflow:
	Start search > 
		Build new search phrase > 
			Filter current result set > 
				Display results / Start search in background > 
					Run APIs consequentially > 
						Inner API search: 
							1. Find suitable regions (.obf files) and do search whithin regions > Sort / Display region's result set after each region is processed.
							2. Sort / Display API's combined result set (summ of all collected result sets).

4. On the search fragment there are three tabs - History, Categories and Address. When you are on History tab - history API used only. On the Categories tab - all APIs runs. And on the Address tab - three address API used only. So when you need to find an address only (without POI) you may speedup search by choosing Address tab first.

5. There are 700ms delay between last char entered time and start search time.

**Comment by sonora** [comment]
Alexey, thanks!

@crimean @vshcherb  I would have to put in much more time and research to be of any real help. But at first sight it strikes me that we need so many processes starting in real time when a user actually searches something, I guess it is exactly this what bites us here performance-wise

It seems to me the strategy would be to perform as much work as possible up front and store it, meaning create an OVERALL index across ANYTHING downloaded (obf) or present (favorites, GPX) on the device . And then at real time when a user actually searches something, only filter hits from this one overall and linear index and display them (along with their classification and properties).

**Comment by vshcherb** [comment]
@sonora I just used the search extensively and indeed I feel something is broken.
1. If we started the search and we've got intermediate results for "ABC"
2. We should display them & filter while user types "ABC TEST" instead of displaying partial results from "ABC TE"

Another question may be we should start the search with delay but we should not interrupt it then each letter is typed. Cause then no intermediate results will be ever displayed.

**Comment by sonora** [comment]
One thing that would definitely help is a short delay after each key tapped to see if the user immediately taps another one, i.e. searching could only commence after a (however brief) break.

Secondly, once searching commences, former intermediate results should not disappear again completely (i.e. blanking the screen completely). but rather be filtered.

Both of these measures may not address more fundamental issues we may have, but may be a good "first aid".

**Comment by TheCapsLock** [comment]
As a warkaround I would find integrating [Photon](http://photon.komoot.de/) into osmand would solve the problem (but this needs Internet access). This is an opensource project with a android app which acts as search engine and coordinates provider for other navigation apps

**Comment by vshcherb** [comment]
Since original issue was created, the following steps have been implemented:
1. Trace level
2. Tests
3. Fixed around 10-15 critical search issues.

Search is far from being quick still but for now we aiming to make it correct first, probably we can talk how to speed it up next step
