### ISSUE TITLE
Minimum Android version required

### ISSUE THREAD

**Issue by Suncatcher** [osmandapp/Osmand#4816]
So trivial question but I wasn't able to find an answer anywhere in the issues. What is the minimum version of Android I can use? 

In store they say "varies by device". So where can I find this device database with allowed version?

**Comment by vshcherb** [comment]
The answer really depends on the set feature & ready to change. We used to compile with Android 2.3 - 4.0 though some features are enabled only with Android 5.

**Comment by Suncatcher** [comment]
>> The answer really depends on the set feature & ready to change.

Okay, where can I what feature set is supported by each API version?

**Comment by vshcherb** [comment]
I don't have such information, may be in the code.

**Comment by Suncatcher** [comment]
>> I don't have such information, may be in the code.

It's some type of trolling? You are marked as owner of the project and you don't have such information?
Then who have it?

**Comment by vshcherb** [comment]
I don't understand why should I have such information & why I should provide it to you. 
Yes, I'm marked as owner
