### ISSUE TITLE
Both YOURS and OSRM online routing is giving Error: Calculated route is empty

### ISSUE THREAD

**Issue by PlutoniumHeart** [osmandapp/Osmand#4817]
As the title states, both YOURS and OSRM online routing is giving  "Error: Calculated route is empty". I am using Android 4.4.2. and OsmAnd+ 2.8.2

**Comment by vshcherb** [comment]
They are both online services and cant be used offline. The issue is not reproducible.

**Comment by PlutoniumHeart** [comment]
I am using those services online, just so you know. 

I have a tablet as well, on the tablet only YOURS is giving those errors, OSRM works fine.

I have tried to reinstall the app, does not help.

**Comment by scaidermern** [comment]
Both YOURS and OSRM work for me. Did you try several different routes? Maybe there is a problem with your specific route.
