### ISSUE TITLE
Stay in night mode at the end of a trip.

### ISSUE THREAD

**Issue by Siltaar** [osmandapp/Osmand#4821]
At night, when arrived at the destination, the map exits from the guiding mode and switch to day-light map colors. Even if the general settings are the same than the guiding-cars settings.

The sudden light flash is disturbing and dazzling.

**Comment by vshcherb** [comment]
Was fixed in 2.8 and there is another small issue which will be fixed in 3.0 (probably could be found in tracker for 3.0)

**Comment by JustAnother1** [comment]
I see this issue again in OSMAnd+ 3.2.7 released on 2018-11-29
