### ISSUE TITLE
Special Rendering for Intermittent Lakes and Ponds 

### ISSUE THREAD

**Issue by Adamant36** [osmandapp/Osmand#4828]
Hello. Is any chance that there could be a special way ponds are lakes that get tagged with intermittent could be rendered? I seem to running into a lot of ponds lately that are completely dry on the satellite images and are tagged with intermittent, but still show up as normal bodies of water in OsmAnd. This seems like a problem to me. Since its not technically geographically accurate. I was thinking maybe they could be rendered the same way intermittent streams are, with dotted lines, around the polygons boundary or maybe put a letter in the polygon that separates it from normal ponds, like how nature reserves are rendered. 

Thanks

**Comment by sonora** [comment]
@xmd5a2 Leonid, I think the dotted line should be rather easy (?).

**Comment by xmd5a2** [comment]
@Adamant36 natural=water,riverbank,bay and landuse=basin with intermittent=yes are already rendered with dashed contour. Please provide exact location or link to osm object.

**Comment by Adamant36** [comment]
Here's the location https://www.openstreetmap.org/#map=17/39.95298/-120.02057 on further inspection I noticed that it says occurrence=intermittent, not intermittent=yes. Most of the other water bodies in the area have the same issue. Looking over the wiki it says that its a problem with the NHD miss labeling things. So I guess I will relabel them. Thanks for bringing my mistake to my attention.
