### ISSUE TITLE
Avoid Motorways doesn't always work (and sometimes is necessary to *cause* motorway routing) in nightly build 3.0.0#23309M, 2017-12-05

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#4835]
What version of OsmAnd are you using, on what device and Android/iOS version?

OsmAnd nightly build 3.0.0#23309M, 2017-12-05, on Samsung Galaxy S4, Android 4.2.2; and on Samsung Galaxy S7, Android 7.0.

The previous nightly build I tried (from 2017-12-01) seemed to work normally with the same map files.

As a control, Play Store release 2.8.2 dated 2017-10-20 using the same map files routes as expected.

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

Offline OsmAnd maps.

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

Your US Georgia and US Florida maps dated October 31, 2017.

__*In case of wrong routing:*__

Tell us whether you have used OsmAnd's in-app offline routing, or any online routing provider like YOURS, OpenRouteService or OSRM.

OsmAnd's in-app offline routing

What routing profile is chosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest)

Car

Please specify as exactly as possible the start and end point of your route by telling us city name and street name so that we can find it via in-app address search easily. Also, a permalink from openstreetmap.org can be helpful.

On an about 475 mile trip home yesterday, of which the normal, best route is about 470 miles of Interstate 75, the referenced nightly build misbehaved in several ways.  This issue relates to motorway routing.

Despite having Avoid Motorways deselected, OsmAnd persisted in trying to route me along numerous stretches of non-Interestate roads.  (The trip away from home on Dec. 1 using the previous-referenced night build properly routed me along the Interstate the entire way.)  It was not a complete avoidance of I 75, but numerous stretches did try to take surface roads.  Interestingly enough, *selecting* Avoid Motorways *did* try to route me along the freeway.

I am able to reproduce this odd behavior of routing on the freeway when Avoid Motorways is selected by using the following:

Start location:  https://osm.org/go/ZQqtvUzJX?way=288866558 (Bubbles Car Wash)

Destination:  https://osm.org/go/ZQq8zxfvb?m=&way=288866558 (a traffic signal at an intersection)

Be sure that all route modifers are deselected except for Avoid Motorways, which should be enabled.

Tell us your expected routing, and how OsmAnd routes, or add screenshots here.

With Avoid Motorways selected, OsmAnd should not route me up I 75, yet you can see in the screenshot that it does.  Deselecting Avoid Motorways doesn't seem to change the routing for this short trip.  (On my longer trip it did change things, as I mentioned in the "Please specify exactly..." paragraph.  Later when I have enough time, I'll try to add additional information, start/destination points, waypoints, etc., from the trip.)

![screenshot_2017-12-06-13-23-28](https://user-images.githubusercontent.com/11140831/33678938-4ea8ece0-da8b-11e7-943d-3e956b8442a1.png)

**Comment by jfburke3** [comment]
I always think of the good titles after I've written the issue.  A better title for this might be:

Enabling Avoid Motorways adds a routing bias *towards* them, while disabling it adds a routing bias *against* them.

It doesn't make it 100% either way, it just seems to make them more/less likely to be used.

If I remember correctly, the way it used to work was that Avoid Motorways would *always* avoid them for routing, even if you were driving on one while setting up a route (it would try to pick the nearest non-motorway road to start you on).

It's probably worth mentioning, also, that OSM Live was enabled on both the S4 and S7, but not turned on on the S4 (the last Live update on that phone was done Dec. 1).  It was turned on, on the S7, and was up-to-date with recent updates.

**Comment by jfburke3** [comment]
More additional information:  I turned off OSM Live for Georgia and let the app delete the map updates associated with it, so I was back on the original downloaded map file, and the routing on I 75 still happens, even with Avoid Motorways enabled.

**Comment by sonora** [comment]
Yes, I think this is the same as #4837.

**Comment by jfburke3** [comment]
The new nightly build with the changes added by @crimean for #4837 seem to have helped this problem. I'll give it a more thorough test in a few hours.
