### ISSUE TITLE
add directional analysis for stop/give_way/traffic_signals signs/tags in routing

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#4836]
Now that the algorithm doing directional analysis for STOP signs was implemented in issue #2885 (decides whether STOP sign is valid from the direction you are coming on your route in OsmAnd), it should be used also for routing decisions.

In routing.xml there are rules for highway=stop, highway=give_way, highway=traffic_signals which add a penalty if you cross a node with these tags on your route. The algorithm should ignore these tags if you are coming "from behind them" (from the nearest crossing/intersection, not towards it) because they do not apply to you in that case.

This would greatly improve routing and calculated route times in cities.

The algorithm should apply only to the 3 tags listed, not e.g. to highway=crossing or crossing=*.

**Comment by aceman444** [comment]
If the algorithm decides to ignore e.g. highway=traffic_signals, it should continue evaluating other rules in the routing.xml block. E.g. it may then hit crossing=* and match it (traffic signals from one direction often have pedestrian crossings, which apply to both directions).

The algorithm should also observe the tags traffic_signals:direction=forward/backward and direction=forward/backward which indicate in which direction the "obstacle" is valid. If there is no such tag, choose the direction towards the nearest intersection (as already said).

**Comment by sonora** [comment]
The detection code itself, including the "nearest intersection heuristics" I have already implemented in #2885 (for stop signs for now). It seems to work fine except in a few really bad (fortunately rather rare in most regions) cases where  no direction is tagged, and the heuristics fails due to a way being split in very short segments around a intersection due to the presence of ped islands etc.

But this issue now is about what (if anything?) to do in `routing .xml`, and I have to admit I am currently not sure about that, someone more familiar with that portion of our code would have to help out.

**Comment by vshcherb** [comment]
That should be changed in the C++ code I guess and no changes should be applied to the routing.xml itself at all.

**Comment by aceman444** [comment]
Yes, that is what I said in the description. Ideally, if you are coming from a direction where the algorithm determines the stop/giveway/signal does not apply, then the routing.xml file should not "set" the tag, as if it didn't exist. I.e. if there is a rule matching highway=stop and doing something, this rule will NOT be matched and evaluation in the block of routing.xml continues to other tags/rules.

**Comment by vshcherb** [comment]
Merged into #6774

**Comment by aceman444** [comment]
There is no logic merging this issue into a newer one that has no technical discussion compared to the current one. But whatever, if it gets the problem fixed.

Also, the issues are quite different, the #6774 talks about using the traffic_signals:direction tag, which rarely exists, so it is not as useful. The issue #4836 talks about automatically determining the direction, because OsmAnd already has an algorithm for that.

Both approaches could work together, traffic_signals:direction overriding the automatic determination.

**Comment by vshcherb** [comment]
This issue about direction tag but also about collapsing tags. There multiple traffic_signals which don't have direction but in theory should have. It could be solved by analyzing frequency or distance between signs and we need to do it cause it is even bigger issue for the current state of the map than supporting directions

**Comment by aceman444** [comment]
That's what I said. And that is what this issue is about, not the other one, to which this was was wrongly merged.
