### ISSUE TITLE
Severe wrong-way routing on oneway roads in nightly build 3.0.0#23309M, 2017-12-05

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#4837]
What version of OsmAnd are you using, on what device and Android/iOS version?

OsmAnd nightly build 3.0.0#23309M, 2017-12-05, on Samsung Galaxy S4, Android 4.2.2; and on Samsung Galaxy S7, Android 7.0.  It happens whether or not OSM Live is active or not.

The previous nightly build I tried (from 2017-12-01) seemed to work normally with the same map files.

As a control, Play Store release 2.8.2 dated 2017-10-20 using the same map files routes as expected.

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

Offline OsmAnd maps.

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

Your US Georgia and US Florida maps dated October 31, 2017.

__*In case of wrong routing:*__

Tell us whether you have used OsmAnd's in-app offline routing, or any online routing provider like YOURS, OpenRouteService or OSRM.

OsmAnd's in-app offline routing

What routing profile is chosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest)

Car

Please specify as exactly as possible the start and end point of your route by telling us city name and street name so that we can find it via in-app address search easily. Also, a permalink from openstreetmap.org can be helpful.

On an about-475 mile trip home yesterday, the referenced nightly build misbehaved in several ways.  This issue relates to wrong-way routing on oneway roads.  This appears to be the same problem that I described in #4629 but is very reproduceable now.

A simple example that reproduces this behavior uses the same start/destination points as my Avoid Motorways issue:

Start location:  https://osm.org/go/ZQqtvUzJX?way=288866558 (Bubbles Car Wash)

Destination:  https://osm.org/go/ZQq8zxfvb?m=&way=288866558 (a traffic signal at an intersection)

Note:  Enabling/disabling Avoid Motorways does not seem to affect this issue.

All routing modifiers deselected (e.g., using Fastest way, not fuel economy; etc.).

Tell us your expected routing, and how OsmAnd routes, or add screenshots here.

At several locations along the route, you can see it route you the wrong way on one-way roads.  The screenshots below were taken on my S7, but, in a bit I'll attach some screenshots from my S4 showing wrong-way routing on I 75 from my trip.

This first screenshot begins here
https://www.openstreetmap.org/way/282189284

![screenshot_20171206-170936](https://user-images.githubusercontent.com/11140831/33688818-e4b84e28-daaa-11e7-90aa-2346f0f566c2.png)

This second screenshot leaves the wrong-way route here
https://www.openstreetmap.org/way/427556497

And picks it up again here
https://www.openstreetmap.org/way/545113281#map=19/33.98176/-84.48397
(Note:  I have *just* edited that road to split a segment and add lane guidance.  That shouldn't matter for the issue I'm describing.)

![screenshot_20171206-171006](https://user-images.githubusercontent.com/11140831/33688823-ea8877f6-daaa-11e7-826a-42cd93f4b9b8.png)

**Comment by CJTmmr** [comment]
I can confirm.
Car mode now uses higway=cycleway, construction, proposed, even highway with motor_vehicle=no for routing. Routing through bollards and gate with acces=no.
Maybe caused by work on Weight-restriction routing

**Comment by jfburke3** [comment]
That might be what's also causing issue #4835 then.  Thanks for figuring out what the underlying issue is (and confirming that I'm not crazy!).

**Comment by sonora** [comment]
Nightly of 2017-12-03 is still fine, looks like this happened on Dec-04.

**Comment by polarbearing** [comment]
Could that be a map issue with the December maps? 
I observed this behaviour with the new map, but a bit older version 3.0.0. # 23121 2017-11-13

**Comment by jfburke3** [comment]
@polarbearing I don't see how it is a map problem. The same map files worked just fine with the nightly build I installed on December 1.

And in any event, the "official" December map files for the U.S. aren't out yet.

**Comment by CJTmmr** [comment]
Using map Netherlands from 1 nov 2017 with Live Updates., routing uses even
railways! in car mode!

Op 7 dec. 2017 15:48 schreef "jfburke3" <notifications@github.com>:

**Comment by jfburke3** [comment]
Motorcycle mode has the problem, too.

**Comment by xmd5a2** [comment]
Confirmed. Somewhat is accidentally broken.

**Comment by sonora** [comment]
Looks like safe mode works, so we have a core issue somehow, introduced on Dec 4.

**Comment by crimean** [comment]
Fixed. Please check it.

**Comment by sonora** [comment]
Yes, my test routes seem to work fine again. Thanks, Alexey!

**Comment by jfburke3** [comment]
A couple of quickie tests look good. I'll give it a more thorough workout in a few hours. 

The problem I described in #4835 seems to be better, too.

**Comment by jfburke3** [comment]
On my S4, with my trip route programmed in, including waypoints I used, it looks good.
