### ISSUE TITLE
Popular, but totally wrong usage of „aktuell“ in German localisation

### ISSUE THREAD

**Issue by ksaerdna** [osmandapp/Osmand#4838]
Version: 2.7.5~
Installed from F-Droid

Bug in German localisation.

Wrong: „Aktuell sind nur .. MB verfügbar.“
Correct: „Derzeit sind nur .. MB verfügbar.“ or „Es sind nur ... MB verfügbar.“

Note that the redundant word **"aktuell"** is a plague, epidemically used in a totally wrong context, often as false translation from English "actual(ly)". Here a temporal meaning is necessary, thus use "derzeit" (meaning "at this time" or "now") oder just omit the unnecessary word, as the sentence is in present tense anyway.

**Comment by sonora** [comment]
Thanks, I fixed a few instances, see https://github.com/osmandapp/Osmand/commit/2d9367d91d055d310e7365ba651cb23ed5234ff7. In other cases I am not so sure. I left all instances of "aktuell" in place where it refers to
- the current position you are at (aktuelle Position, aktuelle Geschwindigkeitsbegrenzung)
- or where it refers to something being displayed at the very time (aktueller Kartenmittelpunkt, aktueller Track, aktuelle Route, etc.)

There are still 15 occurrences of "aktuell" left in the German localization. If you think a more complete cleanup is helpful, please fee free to do so, via a pull request or via https://hosted.weblate.org/engage/osmand/, where any help with localizations is much appreciated. (There is currently also a good number of other rather clumsy German translations, but it is rather time consuming for me to always monitor that.)

**Comment by ksaerdna** [comment]
Looks fine, good criterion!
Thanks!
