### ISSUE TITLE
Message not correctly displayed when saving GPX

### ISSUE THREAD

**Issue by ldmpub** [osmandapp/Osmand#4839]
See screen shot (follow the 2 red arrows at the bottom): in french there are at least 2 problems:
- ' caracter misssing after first letter L (I've check translation in Weblate ... everything is ok there)
- {0} should be replace by a name or removed if name is empty.

![wrong sentence](https://user-images.githubusercontent.com/1452146/33740311-7a771a34-dba0-11e7-8fbc-5fe563c062c5.png)

**Comment by ldmpub** [comment]
Hi,

Thanks for the change.
Could you please explain me where the pb was coming from? Because I only see a type correction in the commit /  Fix #4839 .

Regards,

**Comment by AlexSyt** [comment]
Hi, Android MessageFormat did not work correctly with " ' " and " {0} " in the same string for some reason. So, the simplest solution, which does not require correction of this string in all languages, is to replace " ' " with " ` ".

**Comment by ldmpub** [comment]
Thanks for this clear answer.
