### ISSUE TITLE
Manually specified data location folder not working

### ISSUE THREAD

**Issue by JonnyTech** [osmandapp/Osmand#4844]
In order to share maps between release and nightly builds need to set same data folder.

Only enough space on external sd card.

Moved all files to /storage/0101-0101/osmand

When entered that location into settings it shows "maps could not be created in specified directory"

Am I doing something wrong?

**Comment by sonora** [comment]
Most newer versions of Android grant non-system apps write access to only their native (defined by the package name) data folder, so I guess what you are trying to achieve may be inhibited by the OS security policy.

**Comment by JonnyTech** [comment]
Hence why I created a folder in the root of the storage where any app with storage permission can access it. This should be possible. Or is there another way to share maps between the osmand builds?

**Comment by sonora** [comment]
Root is certainly protected, at least in e.g. Android 4.4.x. It depends on OS etc., there is no general solution.

**Comment by vshcherb** [comment]
The only possible way that worked for me that "Shared location" it is an old way to store data in Android but it might not be available in the new devices any more.
