### ISSUE TITLE
Directions button doesn't work without location permissions

### ISSUE THREAD

**Issue by haho16** [osmandapp/Osmand#4845]
What version of OsmAnd are you using, on what device and Android/iOS version?
_OsmAnd 2.8.2; Android 7.1.2; LineageOS 14.1-unofficial_
Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?
_The issue is on offline maps_
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.
_Barcelona, Spain Catalonia (1.12.2017)_

First, thanks for maintaining and working on this app - I use it on a regular basis and am very happy with it overall!

The issue I am having is with the directions button - both when appearing on the map, and when appearing after looking up an address. It appears to be linked to "location permission", in that it will not work unless I allow OSMand to use my location. When location permission denied, pressing the button doesn't open the dialogue with the two directions search fields. I am doing a work around where I directly go on a pin of an address->more actions->directions from, but would like to have the possibility of just naturally opening directions search without allowing the location permission. Not sure whether "location being a natural requirement for OSMand" means that it is really best to have it allowed, though...so correct me if I'm pushing in the wrong direction :).  Thanks!

**Comment by sonora** [comment]
Yes, naturally, having that permission is key for a map/navigation app. Even if there are use cases, as you say, for which it is not realy necessary, this is very likely not thought through and tested too well.

I am wondering what your reasoning is for denying that permission? If it is a battery savings issue, have you tried granting that permission but instead simply toggling the location sensors on/off on an OS level?

**Comment by haho16** [comment]
> I am wondering what your reasoning is for denying that permission? 

Primary issue is privacy, as I don't feel comfortable having the GPS constantly on. Also, as I am not using the app for navigation purposes (but rather for route planning for, both, bicycle and walking), I don't really need location "on" :) (nor do I need it in any other app / use case, really). 

> Even if there are use cases, as you say, for which it is not realy necessary, this is very likely not thought through and tested too well.

Well, I don't really get why a GUI element would depend on location permission? Is it because "directions" first checks for the "current location" before displaying the search fields?

**Comment by dmpr0** [comment]
@haho16 For route planning you could use our new tool Measure distance, it allow you add points and snap in to the road in different application mode. We ask for permission on Route button, because most of users use navigation with GPS.

**Comment by haho16** [comment]
@dmpr0 thanks for the answer. In all cases, I saw that - by allowing the location permission, but still keeping location provider off, the button works. I will also try out the "measure" tool for route planning :).

**Comment by duggulous** [comment]
This issue ought to be reopened.  We should not conflate looking up directions with live GPS navigation. Looking up turn-by-turn directions between two points unrelated to current location is a legitimate use case (and one I use often).  This was possible in older versions OSMAnd.

**Comment by sonora** [comment]
To be checked, if this is indeed a regression.

**Comment by vshcherb** [comment]
This is not a typical use case but we could check it with low priority. Indeed we don't need location permission for all operations though sometimes developers might overlook and use location function without checking permission. Though in majority of operations OsmAnd *requires* location.

**Comment by zanzibar7** [comment]
Offline direction retrieval without gps was one of the things I thought I would be able to use this for when I purchased. I have discouraged others from purchasing since learning about this permission requirement.  No advantages over free alternatives.
