### ISSUE TITLE
Please extend the "snap-to" measuring feature to rivers.

### ISSUE THREAD

**Issue by treestryder** [osmandapp/Osmand#4846]
Rivers being windy, twisty, things, it is very difficult to measure distances along them. It would be amazing, if the new snap-to measurement feature could be applied to measuring lengths along a river.

Even without this killer feature, I love OsmAnd. Thanks for the work you put into it!

**Comment by vshcherb** [comment]
I think it should already work with boat profile? Did we already enable navigation on waterways?

**Comment by treestryder** [comment]
Boat profile? That would awesome!

**Comment by PaulStets** [comment]
Our boat profile does not support the navigation yet, though it is present in the routing.xml and works fine in the MapCreator. I have added this to the app and it works fine with "Snap-to-road" option in the measurement tool. My only criticism is that the color of the line is barely visible against the blue backdrop of a river. Should we change the color of the line for the boat profile?

![25467943_1956541994592605_1931372362_o](https://user-images.githubusercontent.com/20681525/34071718-3921a98e-e283-11e7-944a-0e40b442bc6b.png)
