### ISSUE TITLE
Search query returns two similar results

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4847]
The street search returns two similar top results containing different buildings inside and different order of district/city.

Screenshot:
![25319706_1954405271472944_1167467658_o](https://user-images.githubusercontent.com/20681525/33878715-e45b94b0-df34-11e7-8767-608e053ad1bf.png)

**Comment by PaulStets** [comment]
Fixed with https://github.com/osmandapp/Osmand/pull/4864

**Comment by vshcherb** [comment]
Should be checked that we don't filter same streets with different buildings set.
