### ISSUE TITLE
Добавить в OsmAND API

### ISSUE THREAD

**Issue by GaMsh** [osmandapp/Osmand#4850]
Добрый день!

Большая просьба добавить в API OsmAnd следующие функции:
- удаление добавленного через апи gpx-трека
- возможность регулировать цвет-ширину трека при добавлении или после добавления
- возможность заполнять для точек описание
- возможность добавить полное название для точки (чтобы было сразу на карте видно его, как для POI) и главное менять его в процессе 

Заранее благодарим!
С уважением, 
Команда OsMo.

**Comment by AlexSyt** [comment]
Здравствуйте.
- возможность удалять трек, импортированный через api, добавили.
- задавать цвет трека возможность уже существует, при его импорте.
- возможность задавать для точек описание тоже существует (AMapPoint.details).
