### ISSUE TITLE
Maps OpenTopoMap, OpenPisteMap don't work

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#4851]
When I go by 
Configure Map / Map Source
I select OpenTopoMap
-> nothing happens, map will NOT be displayed.
Same if I select OpenTopoMap by Overlay.
Same problem with OpenPisteMap in both cases.

Selecting Microsoft Earth works in both cases.

OsmAnd Version 3.0.0#23344
Regards Peter

**Comment by xmd5a2** [comment]
OpenTopoMap works, but OpenPisteMap server was shut down in 2015. Removed from tile sources.
