### ISSUE TITLE
Organic food description unclear

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#4852]
For POIs with an organic food OsmAnd only shows the value "Yes", "No" or "Only" without providing any context:

![photo_2017-12-15_10-35-41](https://user-images.githubusercontent.com/1040784/34035883-b75bd7ee-e183-11e7-93a8-1612389eddd2.jpg)
https://www.openstreetmap.org/node/4181826924

It is unclear that "Only" actually means "only organic food".

This seems to be related to issue #3737. It looks like reverting commit 77d0548 fixes this issue. I wonder if there has been another commit that broke 77d0548 again.

**Comment by xmd5a2** [comment]
Can't reproduce in latest nightly
![screenshot_2017-12-20-16-03-13](https://user-images.githubusercontent.com/5829014/34209618-ec00deb2-e5a3-11e7-95d0-78fb7c913094.png)

**Comment by scaidermern** [comment]
Right. This problem exists in the latest stable version but not in the nightly any more.
