### ISSUE TITLE
Incorrect russian translation "ref" key for amenity=post_office

### ISSUE THREAD

**Issue by Prusaker** [osmandapp/Osmand#4856]
At the moment key named "ref" for amenity=post_office translated to russian as "метка". But according [russian wiki](http://wiki.openstreetmap.org/wiki/RU:Tag:amenity%3Dpost_office) this tag must be translated as "шестизначный почтовый индекс".

Could you please fix this issue?

Thanks in advance.

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/cde9aa0df346090a4708ffe12f84ff2b947b7a26
