### ISSUE TITLE
Map loses manual rotation at lower zooms

### ISSUE THREAD

**Issue by iriman** [osmandapp/Osmand#4857]
1. Map direction: north
2. Rotate map
3. Zoom out to world map
4. Map direction becomes North but should not.
5. Zoom in to see more details
6. Map direction changes to what it was.

**Comment by sonora** [comment]
Think it is by design - world map with compass rotation confused many people. :)

**Comment by iriman** [comment]
Compass rotation with world map is confusing :) but for manual two finger rotation may be useful.
I found a way to solve the problem I had using marker and guide line.
you may close this.
