### ISSUE TITLE
Long Farsi/Arabic names of POI and areas are showing from last word to first word.

### ISSUE THREAD

**Issue by FTABoy** [osmandapp/Osmand#4860]
hello,
Long Farsi/Arabic names of POI and areas are showing from last word to first word. please look at this picture examples.
as you can see in this picture this how openstreetmap site rendered this name , which its correct;
![1](https://user-images.githubusercontent.com/25687276/34078216-236e4cac-e32b-11e7-93cf-c6165c80297c.jpg)
"مجموعه
ورزشی شهید
محمد حسین ثمری"
"مجموعه ورزشی شهید محمد حسین ثمری" 👍 
but osmand show the above text from end. like this:
![2](https://user-images.githubusercontent.com/25687276/34078257-c7d9440e-e32b-11e7-81cb-1e9b977db092.jpg)
"حسین ثمری
شهید محمد
مجموعه ورزشی"
if we read it from up to down :
"حسین ثمری شهید محمد مجموعه ورزشی"! 👎 
which is wrong!
![3](https://user-images.githubusercontent.com/25687276/34078303-c6df6762-e32c-11e7-943f-dbb73866b393.jpg)
here is the shared location:
مجموعه ورزشی شهید محمد حسین ثمری
Near جاده ملارد, فردیس
Location: geo:35.700626,50.99081?z=17
https://osmand.net/go?lat=35.700626&lon=50.99081&z=17
this issue happens with all POIs or areas with long length names which cause the name to break into multiple lines (two or more line). please note that short names are showing OK with out any problem...
thanks

**Comment by shahinnia** [comment]
Hi.
That's true. in short words there's no problem.
But in long & more than two words which last words must go down, unfortunately, first words goes down.
And the user have to read from the end to beginning!!!
Maybe this problem is just for Persian & Arabic fonts.
Thanks for Solving this issue.
![2017-12-18 15 51 55](https://user-images.githubusercontent.com/34649890/34106026-e0c8f14a-e40b-11e7-9874-1eeb2bc70b40.png)

**Comment by BoFFire** [comment]
RTL rendering labels where name:xxx is is an RTL language.

**Comment by FTABoy** [comment]
hi , any news on this? i just saw 3.0 milestone is deleted... will this issue get fixed soon? please let me know.
thanks.

**Comment by BoFFire** [comment]
@FTABoy Not yet fixed. But it is not an urgent issue.
If you look at Berber language, it is not displayed at all on the map.

**Comment by BoFFire** [comment]
@FTABoy
I have just checked the : Air Algeria
الخطوط الجوية الجزائرية
It should be :
الخطوط الجوية
in the top line then :
الجزائرية
as final word on the bottom.

**Comment by vshcherb** [comment]
Fixed https://github.com/osmandapp/OsmAnd-core/commit/673f3beeb836e04eb28724ab18da5a9b43abd13c

**Comment by FTABoy** [comment]
Thank you@vshcherb, the issue is fixed but the commit you have made cause some other new issue, please take a look at this screen shots:
![img_20180125_120346_197](https://user-images.githubusercontent.com/25687276/35378519-559f50c0-01c8-11e8-9d59-1175bbe83030.jpg)
![img_20180125_120347_844](https://user-images.githubusercontent.com/25687276/35378535-67382f78-01c8-11e8-9854-cbf5e66efd6d.jpg)
![img_20180125_120351_948](https://user-images.githubusercontent.com/25687276/35378547-6fab97d0-01c8-11e8-9204-6c8617581a95.jpg)
Some character names are showing as rectangular.

**Comment by iriman** [comment]
Hi, yes it seems this has affected proper rendering of Persian/Arabic names.

Link of images FTABoy has posted (in order from top img):
[مجموعه ورزشی شهید محمد حسین ثمری](https://osmand.net/go?lat=35.700626&lon=50.99081&z=17)
[فاز ۲ اندیشه](https://osmand.net/go?lat=35.702126&lon=51.00169&z=15)
[شهرک کوثر](https://osmand.net/go?lat=35.704025&lon=50.997765&z=16)
Tehran districts
[بوستان جنگلی سرخه حصار](https://osmand.net/go?lat=35.661324&lon=51.5801&z=10)

**Comment by shahinnia** [comment]
Hi.
It seems that  wrong order of the words is solved.
bud changing into rectangular characters is some thing important and new!
Please solved this issue too.

**Comment by vshcherb** [comment]
Fixed with https://github.com/osmandapp/OsmAnd-core/commit/4e758ca2988b2bf33cffbe981dddc6f1de00303b
