### ISSUE TITLE
Add Strava Overlay map

### ISSUE THREAD

**Issue by joostschouppe** [osmandapp/OsmAnd#4861]
Strava is an excellent source to find missing paths. It can be added in Osmand using URL's like these:

https://heatmap-external-b.strava.com/tiles/both/bluered/{0}/{1}/{2}.png?px=256
https://heatmap-external-b.strava.com/tiles/ride/bluered/{0}/{1}/{2}.png?px=256
https://heatmap-external-b.strava.com/tiles/run/bluered/{0}/{1}/{2}.png?px=256

Since you still have to create a new Basemap to be able to add these, and it takes a while to find the correct URL for use in Osmand, could on of these be added to the repository of basemaps?
I would suggest "both" as it includes all Strava data, not just running or cycling data. The subdomain has an a, b and c switch, but I have the impression that Osmand doesn't understand that.

**Comment by pookdeveloper** [comment]
Hi @joostschouppe  how i can add strava maps to OsmAnd? Thanks

**Comment by sonora** [comment]
@pookdeveloper  #16361 explains how you can currently do it.

Please note that if we can offer something as predefined is certainly subject to the license situation.

**Comment by joostschouppe** [comment]
This issue was posted before Strava decided to make the map available only to people who are logged into Strava. As long as that stays the same, this issue is  way too much trouble to try to address. I'll close it.

**Comment by l-mb** [comment]
I saw the reasoning, but I'd love to add this would make an awesome paid/Pro feature. The Strava heatmaps are often really useful for understanding where other people actually walked.
