### ISSUE TITLE
The app does not recognize a u-turn [Add Turn lane test]

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4862]
Instead of listing a u-turn OsmAnd shows "Turn slightly right/left".

Location: http://www.openstreetmap.org/way/177634460#map=18/32.31195/50.83177

Screenshot
![2](https://user-images.githubusercontent.com/20681525/34102503-198fbd7a-e3f2-11e7-9cae-1affa73085dd.jpg)
:

**Comment by shahinnia** [comment]
Correct. 
Please solve it. 
Thanks.

**Comment by naoliv** [comment]
In fact it's a turn left, so saying `Turn left anf go` isn't actually wrong.

Besides this, how can a software decides if a curve is a simple turn or an U-turn?

**Comment by scaidermern** [comment]
> Besides this, how can a software decides if a curve is a simple turn or an U-turn?

In this case the tag `turn=reverse` already contains this information. Without this tag it will be difficult to detect u-turns correctly without too many false-positives or false-negatives.

**Comment by naoliv** [comment]
Using `turn=reverse` would be a solution, indeed.

**Comment by MadWasp79** [comment]
Everything seems in order as for now
![image](https://user-images.githubusercontent.com/13146346/84378222-7910d800-abec-11ea-8ea2-ef0629e65cbf.png)
![image](https://user-images.githubusercontent.com/13146346/84378249-81691300-abec-11ea-933e-51f7a7b54434.png)
