### ISSUE TITLE
Malwarebytes reports latest nightly build (3.0.0 #23413M, 12/19/17 11:33AM) contains ransomware

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#4867]
What version of OsmAnd are you using, on what device and Android/iOS version?

OsmAnd nightly build 3.0.0 #23413M, dated 12/19/17 at 11:33AM, on Android 4.2.2.

Malwarebytes is reporting that this build is infected with a ransomware virus.  I downloaded it from within the previous night build I was running (from a couple of days ago, I think) using the Builds menu selection.

While this may be a false positive, it also could mean that your build environment is infected, or that someone has managed to replace the download URL in the code.

**Comment by jfburke3** [comment]
Specifically, it's identifying the virus as Android/Trojan.Svpeng.rn.  Apparently Malwarebytes has false-positived this in other applications, too (ref:  https://forums.malwarebytes.com/topic/215997-trojansvpengrn-in-next-lock-screen/), however that doesn't necessarily mean that it's a false positive in this case.

**Comment by jfburke3** [comment]
It also claims the night build I just downloaded a few minutes ago has the virus (3.0.0 #23420M).

**Comment by BoFFire** [comment]
Hi,
Is there any way to generate a hash for nightlies ?

**Comment by vshcherb** [comment]
Not sure how can we fix it.
