### ISSUE TITLE
OsmAnd loses GPS after pressing 'Go'

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4874]
Tested on Android 4.4.2. To reproduce the issue it's enough to calculate any route and press 'Go'. The current position will grey-out.

**Comment by sonora** [comment]
Paul, I have many 4.4.2 devices ... cannot reproduce this.

**Comment by PaulStets** [comment]
I suppose it's connected to the bad GPS signal then. It's easy to reproduce in a building. Anyway, I don't think we can do anything about it, so I better close the issue. Thanks for the information.
