### ISSUE TITLE
Car routing - suggests U-turn across divider

### ISSUE THREAD

**Issue by contrapunctus-1** [osmandapp/Osmand#4880]
The correct route, in OSRM -
http://www.openstreetmap.org/directions?engine=osrm_car&route=28.54623%2C77.25102%3B28.54405%2C77.22547#map=13/28.5434/77.2303

OsmAnd routes this by taking a U-turn earlier (near the gas stations), across the road divider, instead of at the correct U-turn later under the flyover. I see nothing in the OSM data that would cause this.

**Comment by PaulStets** [comment]
Hi, I'm getting the identical route to the one you've sent in OsmAnd (see the screenshot). Please make sure to use the latest map update. If the issue persists, backup OsmAnd's data (Android/data/net.osmand.plus) and reinstall the app.
![photo_2018-01-23_16-58-32](https://user-images.githubusercontent.com/20681525/35282856-516f1a22-005f-11e8-9246-49fb80c734d3.jpg)
