### ISSUE TITLE
Contributing speed limits to OSM

### ISSUE THREAD

**Issue by Phyks** [osmandapp/OsmAnd#4883]
Hi,

I noticed Osmand is using OSM speed limits and can be configured to show them on screen while navigating. However (at least near my place), there a lots of roads without any street limit set in OSM.

Waze is also doing a similar thing, displaying the speed limit. But contrary to Osmand (as far as I know), when there is no data there is a nice UI to submit new speed limits. This is super useful and could be used to contribute while driving (for the passenger use, of course). As Osmand is quite widely used as a routing app, I guess it could help put speed limits in OSM quite easily.

I know about [StreetComplete](https://github.com/westnordost/StreetComplete) which is offering a nice UI as well for setting speed limits, although it is not super convenient to use while driving, and would require a switch of apps.

What do you think about it?

Thanks for all the work you are putting in Osmand!

**Comment by hakuchi** [comment]
A lot of driver are alone in the car. ~so there should be a automated tool to detect speed limit.~
But how is this working if there is a lower speed on high traffic, or a slow driver what no drive faster?

Around your living place I think it is not hard for you to add the correct speed limit manually in OSM.

you can use the [Max speed overpass](http://mijndev.openstreetmap.nl/~peewee32/maxspeed/Maxspeed.htm?map=cycleways&zoom=16&lat=0.39068&lon=9.44402&layers=0B00FFFFFFFFFFFFFFTFFFFFFF) to check your neighborhood.

**Comment by Phyks** [comment]
> A lot of driver are alone in the car.
On short distances (and mainly in urban areas), I guess this is true. I tend to think on highways and while travelling between cities, most people are not alone in the car. This is the use case I had in mind.

> Around your living place I think it is not hard for you to add the correct speed limit manually in OSM.
> you can use the Max speed overpass to check your neighborhood.

Sure, I was mainly thinking about highways and such roads, not commuting travels :)

**Comment by hakuchi** [comment]
You can use OSM Notes to mark changing speed limits(as passenger). After your trip you can open OSM in your browser and fix speed limits with the online editor.

Also there are country specific maxspeed in city or outside. In Austria for example are 50km/h in city, 100km/h outside the city and 130km/h on motorway.

**Comment by bitboy85** [comment]
Editing Speed Limits during driving is quite hard. In most cases the road Segment Needs to be cuted where the Limit starts and where it ends.
I suggest using mapillary. Take Pictures during driving upload and edit everything later in the web Editor. Much more precise and safe.

**Comment by scaidermern** [comment]
> Editing Speed Limits during driving is quite hard. In most cases the road Segment Needs to be cuted where the Limit starts and where it ends.

I agree. Either take photos or add an OSM note where the speed limit is missing or wrong so that others can fix or resurvey it.

**Comment by vshcherb** [comment]
Yes there are no nice widgets to use. Though you can use Quick Action button and create templates for several actions like creating quickly poi/notes and then later submit it to OSM.

**Comment by zayuim** [comment]
What about reading from GPX files? Otherwise, I would suggest taking photos for Mapillary.

**Comment by Phyks** [comment]
> IIRC there is an app to capture speed limits and other map features while driving:

This is definitely not the same thing as this issue. OSMAnd has a quite huge user base, extending well beyond the OSM "active" contributors. Most of them are probably willing to contribute at some point (think Waze-like contribution).

You will however lose them if they need to install any other app, even more if this is a geeky UX app and definitely loose all of them when they actually have to post-process their edits on a different device / website. :/

**Comment by bitboy85** [comment]
I don't think osmand will loose users because they don't provide a way to edit maps. In fact i cannot remember having a nav used which allows such an action.

I appreciate that you want to contribute to osm but there are far better ways. While driving you really shouldn't try to edit maps. Just use the note taking function and edit it afterwards. The note is stored with your current gps data so its easy to find the place and you can add many more information than just speed limit.

**Comment by Phyks** [comment]
I think you missed my point in my latest comment. OSMAnd will definitely not loose users by not providing a way to edit maps. OpenStreetMap ecosystem in general will definitely loose a very valuable way of getting consumers (in the sense of using the data without even noticing it) to contribute.

> While driving you really shouldn't try to edit maps. Just use the note taking function and edit it afterwards. The note is stored with your current gps data so its easy to find the place and you can add many more information than just speed limit.

This workflow is working for a geek or a tech-savvy user. Not for the average nav system consumer. Basically no one except OpenStreetMap active contributors will ever look into a workflow involving taking a note while driving, looking back at notes afterwards, opening openstreetmap.org (or JOSM or any other app) on a device afterwards, logging in and handling the form-based edition to update max speeds.

Correct me if I'm wrong, but I do think of OSMAnd as the perfect "Waze-like" alternative based on FOSS. It is also the nav system of choice for a large number of transportation modes (OSMAnd is definitely a thing for cycling for instance). I see it as a perfect entry point for OSM contribution through a very simple task which is max speed editing. From the user point of view, the info is already displayed on screen, easy to check and easy to fix (if we asbtract the OSM way splitting model which is a backend issue). Plus users definitely have a direct feedback on this and see the interest into fixing these.

**Comment by NotSoImportant** [comment]
Thanks @Phyks 👍 same thoughts from me.

Visual editing is much more intuitive and possible for any "normal" user (compare [StreetComplete](https://jakobmiksch.eu/img/osm_overview/streetcomplete_together.png))

> In fact i cannot remember having a nav used which allows such an action.

E.g. in [TomTom nav](https://sm.pcmag.com/t/pcmag_au/photo/t/tomtom-one-140-s-map-corrections-detail/tomtom-one-140-s-map-corrections-detail_xf89.1080.gif) you can easily [channel back speed limit changes](https://help.tomtom.com/hc/en-us/articles/360013898200) (unfortutately that is vendor locked data), but [users complain](https://discussions.tomtom.com/en/discussion/1037200/speed-limits-incorrect) that feedback does not get incorporated.
**This is a good chance for osm to do better.** 

Related issues/requests for osmand are:
- https://github.com/osmandapp/OsmAnd/issues/6124 Adding street numbers to buildings
- https://github.com/osmandapp/OsmAnd/issues/3380 Edit ways attributes with OSM editing plugin

**Comment by NotSoImportant** [comment]
I have not used waze yet, but there it seems to be possible to also [report back](https://assets.pcmag.com/media/images/631769-waze-police-alerts.png?thumb=y&width=980&height=577) a lot of data.

**Comment by itzikiap** [comment]
@Phyks I totally agree with you.  But a possible, although  not ideal, temporary solution is to write  an osm note,  and hope that someone will pick it up and add it to OSM.

**Comment by NotSoImportant** [comment]
Good that you agree :-) And yes there is an existing non-ideal & indirect solution.

And that's why this issue was opened (I guess): Request to implement a better (visual & direct) solution, because it has a great potential!

Also see #7655

**Comment by itzikiap** [comment]
Redesigning the ux of osmand mast take tons of effort. It's full with features within features, most of them are quite important.
I'm not a ux designer, but I began thinking about it, and how to solve at least some of the stuff.
But I'm  sorry, this is off topic for this issue

**Comment by NotSoImportant** [comment]
@itzikiap Agree that it's off topic here. Thanks. Too many ideas in my head ;-)

So let's contribute to discuss here if and how to provide an easy and stimulating way to contribute speedlimit changes.

**Comment by NotSoImportant** [comment]
From a technical point of view there is a long list of arguments why StreetComplete unfortutately has not yet implement this. Probably a lot of them also apply here, but maybe other people here have some ideas how to solve it. 
https://github.com/streetcomplete/StreetComplete/issues/1998#issuecomment-676787192
