### ISSUE TITLE
Where is the file which contains search history for street addresses?

### ISSUE THREAD

**Issue by aktivkohle** [osmandapp/Osmand#4887]
So OsmAnd worked absolutely perfectly on my device with offline maps for about a year until about three weeks ago I noticed in F-droid there was an update several versions newer which I thought I would install. It really (was) a wonderful app. Man if it ain't broken don't fix it.. I wish I knew the old version number that was on it before I might go back and install it if all else fails, maybe it is in the F-Droid log. Am probably too scared to ever update it again..

Anyway, so I noticed [this](https://github.com/osmandapp/Osmand/issues/3288) issue, a nesting of osmand directories. Here is a [link to the file with the directory tree.](https://github.com/osmandapp/Osmand/files/1594903/directory_tree_osmand.txt) I made a backup of that on the PC with Rsync, intend to completely remove all osmand directories from the phone and fresh install the latest version of the app and hopefully it will recreate the directories afresh as they should be. 

Two things were lost:
1. The offline maps I downloaded - this is replaceable, it's only a question of bandwidth. Anyway, it might be possible to simply copy the .obf file into the new directory on the phone from the PC. 
2. The search history for street addresses. 

I notice a file `favourites.gpx` with an xml like content with a few of my favourites. But I almost never used the favourites function - all the important addresses were basically within the search history.

So the main question - it's a big directory tree, does anyone know which file contains the search history and if it can simply be copied into a new directory?

Any general tips about the situation also welcome.
Device - Sony Xperia Mini
Android version 4.1.2
Kernel Version 2.6.32.9-FXP build03@cyanogenmod#1
Cyanogenmod-Version 10-20131006-NIGHTLY-smultron

**Comment by JonnyTech** [comment]
It is a database file: `/data/data/net.osmand.plus/databases/search_history`

**Comment by sonora** [comment]
As a side note: The file tree is fully backward compatible, meaning there is no need to delete it before updating. If you already deleted it, or are switching to a new phone, or are updating the Android OS from a version <4.4 (before the app folder was 'osmand', but then Andoid introduced the mandatory 'Android/data/net.osmand(.plus)/files convention on the external storage), these are the folders you may want to manually restore:
- all files in the root folder, especially the .obf, these are your previously downloaded offline maps.
- subfolder srtm, it contains the contour lines if you used that plugin
- hillshade files from subfolder tiles, contains the 3D relief shading if you used that.
- the subfolder tracks, it contains your trip recordings, saved routes, imported gpx files etc.
- all .obf files from subfolders backup (contains deactivated maps), roads (roads-only maps), and wiki (
Wkipedia POI), if you used any of these features.

All else comes with the update of OsmAnd itself and should be restored upon update-installing if not present.

The search history is only kept in the internal database referenced above, which is only accessible on rooted devices. It should be readable by updated Osmand versions unless you come from a very old version. On really old versions it may be advisable to manually transform to Favorites (Thes would the be in favourites.xml). You can maybe also share/export history entries to other apps on your device by long-tapping them, but depending on how old your OsmAnd version is your mileage may vary.

Hope this helps!

**Comment by sonora** [comment]
PS: I just notice you mention the old issue 3288. Do you really still experience /osmand/osmand/osmand ... successively being added to your data path? Or what is your exact symptom? If you just keep seeing a startup screen asking you to select a data folder, maybe this procedure helps:
1. Rename the old osmand data folder, e.g. by adding _old to its name
2. Start Osmand, when prompted to select a storage location, do so. Skip all map downloading.
3. Force stop OsmAnd. Then, using a file manager or your PC move the files I listed in my post above from the _old folder to the folder structure OsmAnd has now created new.

When you now restart Osmand things should work like before?

**Comment by aktivkohle** [comment]
@JonnyTech thanks I did not know other osmand things were hiding in `/data/data/net.osmand.plus` Unfortunately in my case, there is no `/databases/` in the level below only `/files/` and that its subdirectories contains no `search_history`

@sonora that sounds like a good idea, rename the directory, then let osmand create a new structure, stop it before it shuts down, and move the old structure back in its place. I found `Android/data/` which contained several subdirectories from some of the apps but none from osmand. Yes, 
> keep seeing a startup screen asking you to select a data folder
..was an intermittent issue as is nesting of osmand directories. 

I think that the `search_history` database, if it is on the phone at all is probably hiding in the _internal_ storage which you access through the adb connection. Maybe the fresh install deleted the database.. Yes, the device is rooted, will have a look in adb and see if `/data/data/net.osmand.plus/databases/search_history` is hiding in there. Was not a 'very old' version before, twelve months old is what it was not years..

**Comment by sonora** [comment]
Ok, an update install will not delete any files, only an uninstall will on most newet Android versions as per Android habit. So everything should still be there, both in internal memory as well as on external storage if it was used. I would say just rename the old osmand folder on external, reinstall OsmAnd without prior uninstall, select external storage when prompted, then copy or move the old files. That should solve the startip issue. As per the history issue: I think there may have been a version upgrade of the database used, so maybe just letting OsmAnd sit for a while may update your Favorite etc. database to the new version.(cf #4181)

PS I must have updated OsmAnd hundreds of times for testing, but had actually never experienced any such issues.

**Comment by aktivkohle** [comment]
Thanks @sonora sounds like that is what I did wrong - **uninstall** then reinstall. That probably deleted what was on the internal storage where the search history database was but didn't touch the external storage where the maps and favourites xml are. Did not know this was general Android behaviour.

Can close this thread as the main original question is answered, the location of the database of search history.

**Comment by sonora** [comment]
Yes. Interesting to know: While any app uninstall on Android before version 4.4 just deleted an app's internal data, Android after that also deletes all app data on the **external** storage (for OsmAnd this means all your maps, recorded tracks, etc.). So if you ever need to uninstall OsmAnd, better rename the app's external storage data folder first ...
