### ISSUE TITLE
Osmand manipulates a manually specified Data storage path

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#4888]
As an extension of Issue #3288, even in 2.8.3, we still have the following issue, not sure if it is still worth fixing:

When on an Android version <4.4 and in OsmAnd General settings you go to 'Data storage folder' and you manually specify the **Android 4.4+ convention** `(ext storage)/Android/data/net.osmand(.plus)/files` (some people do this to be able to swap SD cards between different devices with Android 4.4 and lower versions), OsmAnd automatically adds an extra `/osmand` to the end of the data folder path (making the path now `(ext storage)/Android/data/net.osmand(.plus)/files/osmand`), and thus manipulates the path a user manually specified. The user cannot avoid this, and it breaks the interoperability of OsmAnd SD cards in different devices even if the Data storage path in OsmAnd is manually set correctly.

**Comment by vshcherb** [comment]
Looks like the issue never going to be properly fixed cause we now focused on devices with > 80% domination Android 5.0+ as OsmAnd first runs there.

I guess it is no longer an issue for these devices.
