### ISSUE TITLE
E:\osmand\Osmand-master\OsmAnd\res\layout\fragment_edit_poi_advanced.xml

### ISSUE THREAD

**Issue by dykdykdyk** [osmandapp/Osmand#4890]
when  i download the  project，and import  android studio ，then  show this errors:

Error:(81, 39) No resource found that matches the given name (at 'text' with value '@string/tag_poi_amenity').
E:\osmand\Osmand-master\OsmAnd\res\layout\free_version_banner.xml
Error:(40, 39) No resource found that matches the given name (at 'text' with value '@string/tag_poi_name').
Error:(22, 27) No resource found that matches the given name (at 'text' with value '@string/osmo').
E:\osmand\Osmand-master\OsmAnd-java\src\com\google\protobuf\AbstractParser.java
E:\osmand\Osmand-master\OsmAnd\res\layout\dash_osmo_fragment.xml
E:\osmand\Osmand-master\OsmAnd\res\layout\osm_live_banner_list_item.xml
Error:(345, 51) No resource found that matches the given name (at 'text' with value '@string/osm_live_default_price').
Error:(121, 43) No resource found that matches the given name (at 'text' with value '@string/osmand_unlimited').
Error:(42, 31) No resource found that matches the given name (at 'text' with value '@string/osm_live').
E:\osmand\Osmand-master\OsmAnd\res\layout\fragment_edit_poi_advanced.xml
Error:(113, 7) 警告: catch 子句无法访问
已捕获到抛出的类型InvalidProtocolBufferException
Error:(150, 7) 警告: catch 子句无法访问
已捕获到抛出的类型InvalidProtocolBufferException
Error:(36, 27) No resource found that matches the given name (at 'hint' with value '@string/hint_value').
Error:(22, 27) No resource found that matches the given name (at 'hint' with value '@string/hint_tag').
E:\osmand\Osmand-master\OsmAnd\res\layout\poi_tag_list_item.xml
E:\osmand\Osmand-master\OsmAnd\res\layout\subscription_fragment.xml

how do  i  solve this errors ??  
thanks you  very  well.

**Comment by LonelyPluto** [comment]
@dykdykdyk How build it to android studio? Do you solved it？

**Comment by dykdykdyk** [comment]
i'm&nbsp; sorry ,&nbsp; i&nbsp; changed&nbsp; my work ,so , now&nbsp; i can't help you&nbsp; maybe you need change three files.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"LonelyPluto"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月10日(星期二) 下午5:30
收件人:&nbsp;"osmandapp/Osmand"<Osmand@noreply.github.com&gt;;
抄送:&nbsp;"浪人"<1825041608@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [osmandapp/Osmand] E:\osmand\Osmand-master\OsmAnd\res\layout\fragment_edit_poi_advanced.xml (#4890)




@dykdykdyk How build it to android studio? Do you solved it？
