### ISSUE TITLE
misleading code calculating turn penalties

### ISSUE THREAD

**Issue by tobydickenson** [osmandapp/Osmand#4896]
I have been reviewing router code, and found one aspect of the code misleading.....

https://github.com/osmandapp/Osmand/blob/a12a749d86693bde0f6e9fa81742670fae880028/OsmAnd-java/src/net/osmand/router/GeneralRouter.java#L418

This line calculates the angle difference between two route segments for calculating a turn penalty. The value of `diff` is:

`diff` value | meaning 
----- | -------
zero | no turn at all
small, and positive | a small turn, either left or right
pi/2 | 90° turn, either left or right
a little less than pi | nearly 180° uturn, either left or right

`diff` then gets compared to two thresholds: 2/3 pi and 1/2 pi, to split the turn into three bands, which I will describe as a severe u-turn, hard turn, or barely a turn at all.

"barely a turn" has zero penalty.

"severe u-turn" and "hard turn" have penalties determined by the methods `getLeftTurn` and `getRightTurn`, which correspond to the "leftturn" and "rightturn" attributes in `routing.xml. 

As implemented, "leftturn" is the penalty for a severe u-turn of more than 2/3 pi (120°) **in either direction left or right**. "rightturn" is the penalty for a hard turn between 90° and 120° **in either direction left or right**.

Unless I'm missing something, the `routing.xml` attribute names and method names are highly misleading.

**Comment by vshcherb** [comment]
Yes misleading but they are backward compatible with old versions. No plan to change it so far except documentation. They should not be used though because there are countries with left-hand & right-hand driving style
