### ISSUE TITLE
Incorrect city relation

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4897]
http://www.openstreetmap.org/way/52026203#map=17/49.85302/10.97064

This way and the parking and Arts center near it are shown to be located in Hirschaid (the city 4 km from the place), while they are located in Strullendorf.

**Comment by scaidermern** [comment]
They are only partly contained in the [relation for Strullendorf](https://www.openstreetmap.org/relation/1077562). The [relation for Hirschaid](https://www.openstreetmap.org/relation/1077550) however is even further away and has the same admin_level as Strullendorf. Strange.

**Comment by vshcherb** [comment]
https://www.openstreetmap.org/way/52026203 - is strangely addressed as Hirschaid

**Comment by vshcherb** [comment]
http://builder.osmand.net:8081/api/map?bbox=10.8926,49.7726,11.0773,49.8681
