### ISSUE TITLE
ref tag of a bus route displayed instead of ref tag of the highway

### ISSUE THREAD

**Issue by Codain** [osmandapp/Osmand#4900]
Using OsmAnd+ 2.8.2 I recently came in front of an error: the map is displaying as a highway ref one of its bus route ref.

One of the faulty highway: http://www.openstreetmap.org/way/81519928#map=16/45.7380/3.0615
The ref which shall be displayed is `D 944` (as in the top of my screenshot)
The ref displayed is `26` which match the bus relation http://www.openstreetmap.org/relation/3146707#map=14/45.7493/3.0653

I don't remember which one was in the routing instructions (both audio and displayed)

![screenshot_20180103-205817](https://user-images.githubusercontent.com/17512218/34583619-b7a2cfda-f198-11e7-8fde-3ecbc54cf743.png)

I'm not sure it is helpfull to display the route ref. What surprises me is that I can't reproduce this issue with other highways/bus relations.

**Comment by xmd5a2** [comment]
Issue is caused by this relation https://www.openstreetmap.org/relation/3146707#map=14/45.7492/3.0653
route=road

**Comment by Codain** [comment]
Nice catch, thanks! I fixed it. I should have seen it myself...
