### ISSUE TITLE
Crooked and unreadable labels for curvy paths

### ISSUE THREAD

**Issue by bambamal** [osmandapp/OsmAnd#4904]
Osmand aligns labels for rivers, roads, etc. with the path itself. This leads to unreadable text in medium zoomlevels. One example:

![1](https://user-images.githubusercontent.com/33735248/34655384-edede350-f408-11e7-9054-dc104f8cd1f3.jpg)

Possible solution: dont curve/warp the label. Instead adjust the angle, but keep the text straight. One example from locus maps, that is much more readable (hope this is allowed):

![2](https://user-images.githubusercontent.com/33735248/34655389-264b76cc-f409-11e7-97e5-0dfa961a630b.jpg)

Same problem for every label of a curvy path, for example contour lines. I think this produces a very cheap and unpolished look. Some more examples:

![3](https://user-images.githubusercontent.com/33735248/34655401-6356b75c-f409-11e7-9c55-9fb533eaf0d5.jpg)

![4](https://user-images.githubusercontent.com/33735248/34655402-674de43e-f409-11e7-84e6-905de2f6e620.jpg)

**Comment by ivanPyrohivskyi** [comment]
Map Upper Bavaria
<img src="https://user-images.githubusercontent.com/1040293/133293676-8f00197b-3460-49bc-938f-a8e26680c860.png" width="400" /> <img src="https://user-images.githubusercontent.com/1040293/133293263-a675feb1-a6f9-4829-b78b-79bf22cd5a96.png" width="400" />
<img src="https://user-images.githubusercontent.com/1040293/133294493-3a938c3d-18df-486f-9dba-98e545ea526c.png" width="400" /> <img src="https://user-images.githubusercontent.com/1040293/133293272-e9d68d75-b56c-4ade-8241-a6fde0c1a82f.png" width="400" />

**Comment by vshcherb** [comment]
Situation is much better now and probably we won't get complaints that these labels are unreadable
