### ISSUE TITLE
Making a route from Favorites Android does not work

### ISSUE THREAD

**Issue by nowindows** [osmandapp/Osmand#4905]
Following help instructions "Making a route from Favorites Android". After choosing locations to visit and tapping the flag option once again - the map markers DO NOT appear at the top of the screen nor the : button to add them to the route.  Only the map appears with the map marker icons showing.

OsmAnd+ 2.8.2, released 2017-10-20, LG V20

**Comment by vshcherb** [comment]
Can you please make a screenshot cause it is not clear what doesn't work

**Comment by nowindows** [comment]
It seem to remember that a single map marker DID appear on the top of the screen when OsmAnd+ was first installed.  Now the map markers do not appear.
First go to My Places / My Favorites and tap flag at bottom.  Then select location and tap Flag at upper right:
/home/joe/Desktop/Screenshot at 2018-01-09 09-55-57.png
Then map appears missing map markers at top
![screenshot_2018-01-09-09-46-10](https://user-images.githubusercontent.com/6694526/34727070-d2134e88-f523-11e7-875b-633162bbad61.png)

**Comment by dmpr0** [comment]
Just now OsmAnd does not have options to send favorites point from My places to the Route Preparation.
To show Top bar or widget with direction and distance to the markers, you must go to **Menu - Map Markers - More - Appearance on the map - Distance indication turn On**.

**Comment by nowindows** [comment]
My version of OsmAnd+ does not have option "More" in "Map Markers".  At the bottom "List", "Groups", "History" at the bottom and "OPTIONS" on the top. Proceeding through Options still does not show top bar to show Map Markers.

**Comment by dmpr0** [comment]
@nowindows Sorry, you right. In 2.8.2, you must open **OPTIONS - Direction indications, and choose Top Bar or Widgets**. Also in 2.8.2 you can find this options in **Menu - Configure screen - Map markers**. Notice that in navigation, we don't show top bar and widgets.

**Comment by nowindows** [comment]
My version of OsmAnd+ has Distance indication instead of Direction indication.

So, if I set Distance indication to Top Bar or Widgets, then I can make a route from Favorites on my Android device as per the Help instructions.  Thank your for resolving this "non-issue" so quickly.

OsmAnd+ is unbelievably powerful!  Thanks again!

**Comment by vshcherb** [comment]
Yes making favorites group active (transferring favorites to Markers) is a correct & desired way to Plan Route with multiple points. Then it is 1-2 click to create a route
