### ISSUE TITLE
Non-translatable map style in Ski-map plugin

### ISSUE THREAD

**Issue by sveinki** [osmandapp/Osmand#4911]
In the translation files for OSMAnd/Android at https://hosted.weblate.org/projects/osmand/main/is/, the description for the Ski-map plugin reads:

"This plugin for OsmAnd puts at your fingertips details of global downhill 
ski slopes, cross country ski runs, Alpine ski routes, cable cars and ski 
lifts. Routes and pistes are shown color-coded by difficulty, and depicted 
in a special 'Winter' map style which assimilates a snow-colored winter 
landscape. \n
\n
Activating this view changes the map style to 'Winter and ski', showing all 
landscape features under wintry conditions. This view can be reverted by 
either de-activating it again here, or by changing the 'Map style' under 
'Configure map' as desired."

I can see 'Winter and ski' as a map style in the Android app, but nowhere I can find any similar occurrence in the translation files. I'd guess it's not properly marked for translation, right?
Edit:
I am searching for the exact 'Winter and ski' which is used as a translation for the
`public final static String WINTER_SKI_RENDER = "Winter and ski"; //$NON-NLS-1$`
in OsmAnd/src/net/osmand/plus/render/RendererRegistry.java

**Comment by njohnston** [comment]
It is translated in many other languages so I wonder if it's a Weblate issue. If you're comfortable with using GitHub and git you could add a `plugin_ski_descr` string to the OsmAnd/res/values-is/strings.xml file manually and submit a pull request.

**Comment by sveinki** [comment]
Did a small test in Weblate, searching for 'Winter and ski' in French, Danish, German, and Spanish. Curiously no occurrence was found of either 'Winter and ski' or the above message, except for French and Danish where the description above is present.
The search applet in Weblate has a warning:  "The fulltext search might not work properly as the fulltext index for this translation is not yet up to date." so we can't exclude an indexing fault, but normally search is pretty robust.
So, where did you find the occurrences in other languages?
Is this add-on translated somewhere else?

**Comment by sveinki** [comment]
Did also a quick search on GitHub: https://github.com/osmandapp/Osmand/search?utf8=%E2%9C%93&q=%22Winter+and+ski%22&type=
and found no translation strings matching 'Winter and ski' other than inside the description above.
I am searching for the exact 'Winter and ski' which is used as a translation for the
`public final static String WINTER_SKI_RENDER = "Winter and ski"; //$NON-NLS-1$`
in OsmAnd/src/net/osmand/plus/render/RendererRegistry.java

**Comment by njohnston** [comment]
You can see that the string is translated to Italian here:
https://github.com/osmandapp/Osmand/blob/b654b3ee7529109a4c49bbe12c22e684a961ed0c/OsmAnd/res/values-it/strings.xml#L1687

It's also in Spanish, as another example:
https://github.com/osmandapp/Osmand/blob/b654b3ee7529109a4c49bbe12c22e684a961ed0c/OsmAnd/res/values-es/strings.xml#L1566

It has been translated to many other languages too.

GitHub search often works poorly in my experience. It's more reliable to clone and grep IMHO :)

I don't use Weblate as I only tweak English phrases, and have no desire to learn another tool just for that purpose.

**Comment by sveinki** [comment]
No, that's the description of the plugin, I have that alright. Maybe I was not clear in my first message: I am searching for the exact 'Winter and ski' which is used as a translation for the
public final static String WINTER_SKI_RENDER = "Winter and ski"; //$NON-NLS-1$
in OsmAnd/src/net/osmand/plus/render/RendererRegistry.java

**Comment by njohnston** [comment]
Sorry, I misunderstood your question. I think you're correct that currently "Winter and ski" cannot be translated.

**Comment by vshcherb** [comment]
@PaulStets Fixed with https://github.com/osmandapp/Osmand/pull/4937 ?

**Comment by PaulStets** [comment]
Yes, we made some styles translatable. Now you can translate the following xml values: 
```
winter_and_ski_renderer
nautical_renderer
touring_view_renderer
```

**Comment by sveinki** [comment]
Already appeared in Weblate.
Thanks a lot!
