### ISSUE TITLE
Plugin OSM editing: Modify OSM change - table is not updated after modification and before upload but is through show description

### ISSUE THREAD

**Issue by serpico** [osmandapp/Osmand#4914]
OsmAnd 2.8.2
Android 4.2.2
offline map

How to reproduce :

- Create POI ( in my case name was left blank and amenity=vehicle_inspection )
- Tap on the created POI ( green circle )
- Choose "Modify OSM change"
- Using the ADVANCED tab ; tap button "Add Tag" then Tag=brand (shows up in the list ) and Value=Autosur
- Tap SAVE at the bottom
- Tap on the POI ( green circle )
- Choose "Modify OSM change"
- Table showing the attributes is not updated with the change
- Tap on the POI ( green circle ) ;  this time choose "Show description" instead of "Modify OSM change" --> modification appears

Thanks

**Comment by dmpr0** [comment]
Hi! Thank you for feedback, we try and can not reproduce it, if you can, please try to download latest nightly build and try to do the same.
