### ISSUE TITLE
New Context Menu: Follow OsmAnd UI color conventions

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#4915]
For a long time now we have followed the convention that UI elements related to MyPosition and navigation are shown in blue.

Looks like in the new look of the context menu we so far break this in our latest nightlies, as follows:
 - Light theme: The "Description" button should be orange, not blue.
 - Dark theme: The "Directions" button, the arrow and "distance from MyPosition", and on the route dialog the "GO" button should be blue, not orange..

**Comment by sonora** [comment]
PS: I believe the related commits are by Alexander (@AlexSyt , maybe you could have a look? Thx - Hardy).

**Comment by dmpr0** [comment]
Hi! We don't always use blue as location color, all buttons text, always was blue in light theme. I think blue description button not a problem, but we change color of GO button in Route Preparation.

**Comment by sonora** [comment]
Yes, true, I overlooked that. May be worth to also change the light theme to consistently implement "use blue for position/nav related stuff" everywhere?

**Comment by vshcherb** [comment]
The link issues are mostly fixed there was some inconsistency. I don't think we should tight ourselves to Button colors! I support @dmpr0  in case of colors of buttons in sense it should be consistent and aesthetic. 
Anyway if you see similar buttons but different colors please let us know cause I think that is consistency question.

**Comment by sonora** [comment]
From what I see we can limit this to the points I already noted in my first post above, i.e. in **both the dark and the blue scheme**,

- the "Directions" button should be blue (now it is only in light scheme),
- the little "Distance and arrow" should be blue (now it is only in light theme), and
- the "Description" button should be orange (now it is only in dark theme)

This would be in line with what we had before the Context menu redesign started. And in case of the distance display, it creates the consistency again with how we have it on the search results screen.

**Comment by vshcherb** [comment]
I agree with:
- the little "Distance and arrow" should be blue (now it is only in light theme)
Others observations I don't think are critical but let me doube check.

**Comment by sonora** [comment]
Blue location/navigation related items make things easier with users coming from google maps, there it is the same convention (although I think we had it earlier :) ). 

In general: We now move away from the google convention of the "disk shaped" navigation button on the context menu, which is fine because we have an explicitly text-labeled button. But keeping the button in blue may still make things easier for some users.  :)

**Comment by vshcherb** [comment]
Orange is traditional for OsmAnd and it looks nicer in night theme, though I will let @dmpr0  react to that.
BTW the location arrow blue color is fixed and new color grey is introduced when location was just lost couple of minutes ago.
