### ISSUE TITLE
Include 'Voice guidance output' in the Route setup options

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#4917]
I received several user requests we should include the setting 'Voice guidance output' on the quick navigation settings menu (which is accessed from the route setup dialog by tapping the gear wheel button). The setting is currently missing (between ' Voice guidance' and 'Pause music') and would be helpful there for users frequently changing between e.g. car and bike routing and needing a different voice output for both.

**Comment by dmpr0** [comment]
I think we can try to add a button, that will open "Voice prompts" settings.
![Снимок экрана 2020-07-03 в 16 22 40](https://user-images.githubusercontent.com/9365308/86473352-6d2ab880-bd49-11ea-88ec-a5bd22b2a965.png)
