### ISSUE TITLE
[Enhancement Request] More specific settings for different Routingtypes

### ISSUE THREAD

**Issue by Mannshoch** [osmandapp/Osmand#4920]
If I'm Planing a Route by foot, Please allow better to setup specific settings.
For a hike, I wish also be able to setup the Underground of foot ways.
e.g.

**Street**
- [x]  Ground
- [x] Gravel
- [ ] Asphalt
- [x] Unknown Surface

**Footways**
- [ ]  Ground
- [x] Gravel
- [x] Asphalt
- [ ] Unknown Surface

**Comment by rindlerblabla** [comment]
Would it be possible to combine this with #4032 (e.g. smoothness, trail_visibility, lit)?

**Comment by xmd5a2** [comment]
I don't agree that this feature is really needed for users because surface doesn't matter much when hiking

**Comment by Mannshoch** [comment]
it matter if you do hike without shoos for hiking. 

E.g. that happens to me. in a forest near Zürich, we visited this dorest the first time and i tryed to plan a route. We als had a baby carriage with us.
Because Osmand was not able to exclude Ground tagged roads. We ended in such a road and had to turn. 
This maybe could also be an importand Tag for wheelchair users.

**Comment by xmd5a2** [comment]
It is possible to implement but without division into streets / footways

**Comment by xmd5a2** [comment]
But basically you just need "Avoid unpaved" option, right?

**Comment by Mannshoch** [comment]
I know that would it made easier but it's not if you really wish to use Osmand for walking.

As an example:
[https://www.openstreetmap.org/...](https://www.openstreetmap.org/?mlat=47.36533&mlon=8.57680#map=19/47.36533/8.57680)
This way you are able to walk with normal shoos and they Don't get dirty.
You could also use a baby carriage with you
It's not usable for wheelchair
The Bridge above do not have a surface set. But in a unknown forest I would not try to use ways without a known surface.

**Comment by scaidermern** [comment]
Also related to #4236.

**Comment by vshcherb** [comment]
Let's check that we have enough avoid unpaved / avoid paved (sometimes paved could be related to car roads and people would like to avoid them)
