### ISSUE TITLE
[Feature Request] Observe Low Emission Zones

### ISSUE THREAD

**Issue by Atalanttore** [osmandapp/Osmand#4922]
Hi

observing [Low Emission Zones](https://wiki.openstreetmap.org/wiki/Tag:boundary%3Dlow_emission_zone) for routing would be a useful feature for drivers of older cars which are not allowed to drive in Low Emission Zones.

Regards,
Ettore

**Comment by pietercolpaert** [comment]
Example of how this looks like on OSM: https://www.openstreetmap.org/relation/7966961#map=13/51.2179/4.4057

**Comment by zekooooo** [comment]
I would appreciate this too, and also a navigation setting for these. There are probably over a hundred of these zones in Europe nowadays and the only way to see them is to open osm.org, zoom in on the city and stab blindly with the "what's here" tool until you find it.

Millions of people in Europe drive Euro2 cars and worse and AFAIK no mobile nav app supports these zones.

**Comment by pietervdvn** [comment]
Hi Pieter! We meet again!

Rendering is implemented in https://github.com/osmandapp/OsmAnd-resources/pull/550
