### ISSUE TITLE
TTS spelling issue in hungarian for "400"

### ISSUE THREAD

**Issue by skyli91** [osmandapp/Osmand#4941]
Hi!

I have this issue long time ago with Hungarian tts, where the pronunciation for "four hundred" is "néCCSáz" instead of "néGYSZáz".

Now:    https://translate.google.com/#hu/en/n%C3%A9ccs%C3%A1z
Should be:    https://translate.google.com/#hu/en/n%C3%A9gysz%C3%A1z

It's pretty common to hear this.

Could someone fix this?

**Comment by vshcherb** [comment]
I think TTS spelling relies on TTS engine and not on TTS configuration in OsmAnd. The numbers are pronounced by TTS-engine itself.
