### ISSUE TITLE
Misaligned buttom sheet by going to quick actions via drawer

### ISSUE THREAD

**Issue by iriman** [osmandapp/Osmand#4948]
Hi, there is an issue similar to #4834 

- go to menu > configure screen > quick action
- go back to map screen

Look at the bottom of screen: 

![screenshot_20180126-125140](https://user-images.githubusercontent.com/8467903/35433186-5fc2fbe4-027a-11e8-9b05-eabc50a7df3b.jpg)

On SM-J510F, android 7.1.1 
OsmAnd~ 2.9.0#23627m, released: 2018-01-25

**Comment by vshcherb** [comment]
This is a draggable button .

**Comment by iriman** [comment]
I mean that whitish bar at the bottom of screen. Is it intended?
