### ISSUE TITLE
Speed limits from Live updates are not used for routing

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4952]
The way has a maxspeed of 50 km/h in OSM, but it's still shown with 30 km/h in OsmAnd. [https://www.openstreetmap.org/way/210580627]

Also on way 551099867 
(https://www.openstreetmap.org/way/551099867)

**Comment by 351293** [comment]
Also found on way 200985532

**Comment by vshcherb** [comment]
That was fixed recently cause OsmAnd Live didn't use new data for navigation

**Comment by 351293** [comment]
I still had this problem in the current version but yeah...

**Comment by vshcherb** [comment]
@PaulStets could provide more information and check if the new updates make it available

**Comment by 351293** [comment]
@vshcherb I reported the bug to Paul, so please tell me what information you require.
Bug found on OsmAnd (Unlimited) 2.8.2 Released 2017-10-20. (Offline-)Maps were from the 1st January with the most recent OsmAnd-Live patch. OsmAnd-Navigation service. No Updates in Google Play Store available.
Device: Samsung SM-N910F (Note 4) with Android 6.0.1
