### ISSUE TITLE
Find mountain ranges as POIs

### ISSUE THREAD

**Issue by Suncatcher** [osmandapp/Osmand#4954]
How one can find a mountain range on the map via POI search?
I know we can use natural=peak filter, but it is not what I supposed to do, I don't want separate peaks like Teide, Everest or Mont Blanc, I wanna see where are Andes, Appalachians or Sierra Nevada are located.
Is there such option? I didn't find it.
If it's not, probably we should make a POI for it.

What version of OsmAnd are you using, on what device and Android/iOS version?
2.8, on BB Priv

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?
Offline

**Comment by xmd5a2** [comment]
It is available as "Mountain area" but keep in mind that not every mountain areas are tagged correctly in OSM
