### ISSUE TITLE
OsmAnd avoids ways with the wrong maxweight

### ISSUE THREAD

**Issue by 351293** [osmandapp/Osmand#4957]
OsmAnd was unable to calculate a Route via Version 7 of Way 157628114 ([https://www.openstreetmap.org/way/157628114](url)) (maxweight=7.5) althought the maxweight in the OsmAnd-Settings were set to 3.5t. After removing maxweight from navigation settings OsmAnd was able to calculate the route.

**Comment by vshcherb** [comment]
That's a map issue looks like
