### ISSUE TITLE
House numbers missing

### ISSUE THREAD

**Issue by trampster** [osmandapp/Osmand#4961]
I can't seem to search by or even see street numbers.

When I go somewhere what I have is a street address this includes a street name and a house number on that street (for example 43 Bainton Street) . However  Osmand only seems to know about street names not numbers, This makes it really hard to use Osmand for navigation, if the street is long (hundreds of houses) then it's completely useless.

I've checked http://www.openstreetmap.org and it has the numbers, the information is available to you. Please use it.

**Comment by xmd5a2** [comment]
Can you provide exact issue location so we can check it?

**Comment by trampster** [comment]
I live in Christchurch New Zealand. 

I can't find street number in OsmAnd for any location in Christchurch.

For example:
Try searching for 97 Kendal Ave. All I get is a list of street Corners, (unfortunately most street address don't come with explanations about which corner they are closest to)
For this same address www.openstreetmap.org finds it no problem.
Going to the location in OsmAnd  also doesn't show any street numbers, not there and not for any other part of the city that I have tried.

**Comment by xmd5a2** [comment]
Have you checked "Configure map - Hide - House numbers" option? I can't reproduce this
![screenshot from 2018-01-29 13-55-32](https://user-images.githubusercontent.com/5829014/35506948-2b3b5838-04fc-11e8-9e4d-db99a748c4b0.png)

**Comment by trampster** [comment]
Configure Map -> Hide -> House numbers is not ticked

Interestingly Hereford street (as shown in your screenshot does have numbers), but not Kendal Ave (or any other road near my house) as I gave in my example. it looks like there are only numbers in the Central City not in the suburbs, but www.openstreetmaps.org does have the numbers, is it possible that the maps you are using are old and that the numbers have been added more recently.

Can you please check Kendal Ave and get back to me?

**Comment by xmd5a2** [comment]
This is newly generated map. What OsmAnd version do you use?
![screenshot from 2018-01-29 14-07-11](https://user-images.githubusercontent.com/5829014/35507465-ebc8e63c-04fd-11e8-84e6-aa76509f5a2d.png)

**Comment by trampster** [comment]
I have 2.8.2 installed from the play store, I have a Google Pixel.

Seems like my map must be old, How to I make it update my map, and why isn't it automatic?

**Comment by xmd5a2** [comment]
There was such a problem with house numbers in OsmAnd 2.8, not in the map. You can try to install latest nightly apk or wait for upcoming release.
