### ISSUE TITLE
Intents to switch GPS logging on and off

### ISSUE THREAD

**Issue by HisRoyalRedness** [osmandapp/Osmand#4966]
Posting here as requested by support team...

I'd like to log my tracks when in my vehicle, but not while wondering around the home / office / shopping mall etc. I have a Tasker profile on my phone that activates when it connects to the vehicle bluetooth handsfree. This launches Osmand, but I currently don't know how to enable GPS logging at this point. I'd also need to switch off GPS logging when the bluetooth hands free disconnects.

I suspect the best way to achieve this is to use intents (which Tasker supports), as there isn't a native Osmand plugin for Tasker.

So, my question is: are there intents to turn gps logging on and off, and what are they?

**Comment by vshcherb** [comment]
Please check here https://github.com/osmandapp/osmand-api-demo
They might be in the code.
https://github.com/osmandapp/osmand-api-demo/blob/master/app/src/main/java/net/osmand/osmandapidemo/OsmAndHelper.java#L220

**Comment by andreapx** [comment]
@HisRoyalRedness were you able to find and use intents with Tasker?
