### ISSUE TITLE
How to download old releases?

### ISSUE THREAD

**Issue by bumbaras** [osmandapp/Osmand#4969]
How to download older versions of OsmAnd?
I have found normal (not plus) versions here http://download.osmand.net/releases/
but there aren't any plus versions. I have bought plus two years ago, but didn't backup apk which I originally installed from Play. Now the new versions works bad on my phone, and I don't want to fight with free version limitations (because I paid for plus).
How to achieve archived plus app for sideloading?

**Comment by vshcherb** [comment]
https://www.osmand.net/downloads.
You can contact support team for a plus version if you have an email receipt
