### ISSUE TITLE
Promote name from stop_area to entrances

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#4972]
Example here
https://www.openstreetmap.org/relation/7588363#map=18/55.75227/37.61004

To make visible names on the entrances on the map

**Comment by xmd5a2** [comment]
```xml
		<type tag="railway" value="subway_entrance" minzoom="13" order="1" nameTags="name" relation="true" relationGroup="true"/>
```
has no effect. No 'name' tags are propagated from relation to child.

**Comment by vshcherb** [comment]
Option 1.
<type tag="public_transport" value="stop_area" minzoom="13" order="1" namePrefix="stop_area_" nameTags="name" relation="true"/>
    <type tag="railway" value="subway_entrance" minzoom="13" order="1" nameTags="stop_area_name" />

Point types [public_transport-stop_area (31), railway-subway_entrance (36)] add_types [color_red(26)] Names [ref(13) - 3, stop_area_name(15) - Александровский сад, Арбатская, Библиотека имени Ленина] id 45091867340 osmid 352280213

**Comment by vshcherb** [comment]
Option 2.
```xml
<type tag="public_transport" value="stop_area" minzoom="13" order="1" nameTags="name" relation="true"/>
		<type tag="railway" value="subway_entrance" minzoom="13" order="1" nameTags="name" /> 
```
Victor OsmAnd, [03.02.18 14:40]
Point types [public_transport-stop_area (30), railway-subway_entrance (35)] add_types [color_red(25)] Names [name(3) - Александровский сад, Арбатская, Библиотека имени Ленина, ref(13) - 3] id 45091867340 osmid 352280213

Point types [public_transport-stop_area (30), railway-subway_entrance (35)] add_types [color_red(25)] Names [name(3) - Александровский сад, Арбатская, Библиотека имени Ленина, ref(13) - 3] id 45091867340 osmid 352280213

**Comment by xmd5a2** [comment]
Fixed. Issue affects not only subway_entrances but also public_transport=platform
