### ISSUE TITLE
Enhancement - Harmonize bis, ter... house numbers displays

### ISSUE THREAD

**Issue by Codain** [osmandapp/Osmand#4976]
Because there is no clear concensus on OSM reguarding addresses with a `bis` or `ter` or `quater` (and maybe `A`, `B`, `C`...) different systems are currently used in `addr:housenumber` in a same city. Here are some statistics from Taginfo reguarding the `bis` case:

- 16098 results with `XX bis`, `XX Bis` or `XX BIS`
- 1621 results with `XXbis`, `XXBis` or `XXBIS`

It looks like the search engine in OsmAnd handles all those cases (to be checked).

**The issue:** I suggest during the creation of the map files on OsmAnd side to clean those tags by applying only one syntaxe. This would:

1. Make maps more professional thanks to a common syntaxe
2. Simplify the use of the search engine (the search engine is a complexe piece of software... having standardized syntaxe helps simplifying algorithms and detecting issues). Personnaly when OsmAnd don't find the answer I try with or without space, with or whithout upper case... because i've seen that those addresses are not standardized on the map.
3. Maybe reduce a little bit the map size depending on how data compression is made

Which syntaxe to choose? The better would be be to have a per-map rule which would detect which format is the more used for a given map to generate (maybe countries have different rules). Otherwise if a unique rule has to be devised:

- For bis, ter... I suggest to use the most popular one which is `XX bis` (lower case with a space).
- For A, B... I suggest to use the most popular one which is by far `XXa` (lower case no space).

But personnaly I'm open to any other syntaxe...

**Comment by franco999** [comment]
Any news on this?

**Comment by xmd5a2** [comment]
Housenumbers to test:
https://www.openstreetmap.org/node/3282527694
https://www.openstreetmap.org/node/2397249536
https://www.openstreetmap.org/way/73111901

https://www.openstreetmap.org/node/3287400918

**Comment by vshcherb** [comment]
Fixed with https://github.com/osmandapp/OsmAnd-tools/commit/389dc2d0f6c496cc915b09b7629c545b057da9fe
