### ISSUE TITLE
Problem with Translatable Map Styles

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#4977]
It looks like this commit is somehow buggy: https://github.com/osmandapp/Osmand/commit/3eb7dd51656e67321aa156f29650a0ef63fa8681

Users complain that in 2.9.0beta they receive error `renderer_load_exception` when e.g. having Osmand initially set to English and Map style is Touring view, then switch the OsmAnd display language to German. Others report they cannot select Touring view at all in German display language, but it works in Spanish or English. Others again report it does not even work in English after changing display language from German to English, but it works after an app restart in English and then manually changing back from OsmAnd default to Touring view.

**Comment by scaidermern** [comment]
I can confirm that selecting Touring view is not possible with the app language set to German but works with English.

**Comment by PaulStets** [comment]
Hi, the commit you referenced was fully tested in three different languages and had nothing to do with the problem. The issue was caused by the dash in the German translation, which was mistakenly removed in the old code. Anyway, I have fixed it now: https://github.com/osmandapp/Osmand/pull/4979. Thank you for the feedback.

**Comment by sonora** [comment]
Hey Paul, Thank you so much for spotting this, I had completely overlooked!
 Thx-Hardy

**Comment by sonora** [comment]
Unfortunately I'll have to re-open this, just tested and there are still issues, as follows: It seems that every change of the Display language now changes the Map style back to default, if you were in one of the translatable Map styles like Winter and ski, but it clearly should not.

**Comment by sonora** [comment]
Looks like the problem is that `getSettings().RENDERER.get()` returns the respective (call it 'display name') string from `RendererRegistry.java` like the `DEFAULT_RENDER` or `WINTER_SKI_RENDER` value.

We have now made some of these translatable. So now when the string value changes with a locale change it does no longer match what is in the Registry, (and for renderers not found any longer we always fall back to the default renderer).

If we want to keep this new feature of translatable Map styles:
- Ideally the render registry should be reworked to only contain a locale-independent identifier for each renderer?
- It may be a simpler fix (but not so clean) to keep the Registry as it is but now update its values immediately upon every locale change?

**Comment by vshcherb** [comment]
@sonora good finding, so we need to store not the translatable name but the key of the file

**Comment by Norbert80** [comment]
I also experience this bug.
