### ISSUE TITLE
Poland Automap (not full one) - no buildings numbers

### ISSUE THREAD

**Issue by bumbaras** [osmandapp/Osmand#4983]
I think that automap should has a detail like buildings numbers.
It doesn't, at least now.

**Comment by vshcherb** [comment]
No it won't have. It is done by design to reduce the size of the map

**Comment by bumbaras** [comment]
Well, can't agree with Ya this time, but can't be helped. Automap without street numbers - ridiculous.
Never mind.
Next problem: on Poland automap, city Łódź, the street Marii Skłodowskiej-Curie is displaying as Q7186. This bug is not on full map, only automap.
