### ISSUE TITLE
Phantom extra straight line shown when displaying trans-Pacific GPX track

### ISSUE THREAD

**Issue by njohnston** [osmandapp/OsmAnd#4984]
I'm using OsmAnd+ 2.8.2 on a Samsung S8+ running Android 7.0.

When viewing a [GPX track for a trans-Pacific flight](https://drive.google.com/open?id=1mF93BSIuI4T74lv_H03At-YggQ7jGD-1
) (from near Hong Kong to San Francisco), an extra straight line is shown for the track:

![osmand_pacific_track_straight_line](https://user-images.githubusercontent.com/638458/35756888-dddf1fe0-0864-11e8-90de-44e051952af7.jpg)

Aside from this, the track itself is displayed correctly, but just east of New Zealand the map rendering stops until you pan east a bit, and then the westerly part of the map is not rendered correctly:

![osmand_pacific_track_incorrect_rendering_2](https://user-images.githubusercontent.com/638458/35757002-3cff6f52-0865-11e8-8ea8-455322e84874.jpg) ![osmand_pacific_track_incorrect_rendering_1](https://user-images.githubusercontent.com/638458/35756994-376a2f6e-0865-11e8-9571-1b71c4abaf1a.jpg)

This does not seem to be related to the GPX display, so let me know if I should open another issue.

**Comment by cepprice** [comment]
- [ ] Fix solid track
- [ ] Fix gradient track
- [ ] Fix route and arrows of both track and route
