### ISSUE TITLE
Pedestrian multipolygons not rendering

### ISSUE THREAD

**Issue by zayuim** [osmandapp/Osmand#4985]
As an example use [Queen Street Mall in Brisbane](https://www.openstreetmap.org/relation/7781404). This simply won't render, whereas, Albert Street Mall (which is right next to it) will render since they are simple areas.

I'm using Live to grab updates, but i'm sure it happens on any source.

**Comment by vshcherb** [comment]
Do we need tag area=yes?

**Comment by xmd5a2** [comment]
Of course area=yes is needed

**Comment by zayuim** [comment]
The problem is that I'm not sure of an easy way to to have area = yes while it still being a multipolygon.

**Comment by xmd5a2** [comment]
Fixed, but it is better to add area=yes to such polygons
