### ISSUE TITLE
Regression: OsmAnd+ 2.9.1 does not display house numbers

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#4987]
OsmAnd+ 2.9.1 does not display house numbers on the map. I have verified that house numbers are not disabled.

**Comment by vshcherb** [comment]
Fixed in the nightlies, will be fixed in 2.9.2. https://github.com/osmandapp/OsmAnd-core/commit/b5bca8fed1897bb7efc2189a99bd1cf1a7e128c8

**Comment by Norbert80** [comment]
@vshcherb thanks!
