### ISSUE TITLE
Enhancement: Separate sections or files for routing profiles

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#4991]
According to a discussion here
https://groups.google.com/forum/#!topic/osmand/V7iEvdSVMSg
we want to ask you, if it would be possible to create either
separate sections
or 
separate files as routing_<profile_name>.xml
for each profile.
For trucks (and camping cars and other slower motor vehicles) the routing profile for car is used but the speed used for calculation is much too high. Trucks (and other) are in fact quite slower. So it would be a good idea to have a separate speed part in the routing...xml or a separate complete rounting section or file for the calculation.

**Comment by aceman444** [comment]
Yes, this would also be interesting for a 'bus' mode and similar.
The various modes do not only differ from car mode in the speed section, but also restrictions. E.g. hgv=no is applicable to 'truck/bus' but not 'car'. Even barriers may differ, see e.g. barrier=bus_trap.

**Comment by vshcherb** [comment]
Yes I agree that would be helpful for debugging & profiling purposes though obviously release will distribute as one file. In that file today is already allowed to have bus....
I agree
routing_bus.xml
routing_pedestrian.xml 
could have taken precedence for specific profile.

**Comment by pebogufi** [comment]
Please be so kind to add routing_truck.xml as well, I don't think it will need much additional work, if the other will be added.
Thanks a lot, Peter

**Comment by pebogufi** [comment]
The new routing profile is nearly ready, somi close this thread.

**Comment by vshcherb** [comment]
Yes please feel free to test it, we expect mostly UI glitches to be fixed this week

**Comment by aceman444** [comment]
So what possibilities does the new "profile" feature offer? What behaviour of the generic routing 'car' profile can be overridden?
