### ISSUE TITLE
Poland automap - bad street name

### ISSUE THREAD

**Issue by bumbaras** [osmandapp/Osmand#4992]
Poland automap, city Łódź, the street Marii Skłodowskiej-Curie is displaying as Q7186. This bug is not on full map, only automap.

**Comment by xmd5a2** [comment]
Issue is not clear. Can you provide additional info and screenshot?

**Comment by jfburke3** [comment]
@bumbaras By "automap" do you mean the roads-only map?

**Comment by bumbaras** [comment]
Yes, the smaller one. The full Poland map hasn't this issue at all.
About issue, don't know what is not clear. Whole street has Q7186 as a name.

**Comment by StenSoft** [comment]
“Q7186“ is used in tag `name:etymology:wikidata`. Probably map generator used this tag instead of `name` for name?

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/37199769-e96e89c0-2382-11e8-99c8-fb1b60e722e0.png) new map doesn't have that problem

**Comment by bumbaras** [comment]
I will try to make own screenshot. Or maybe this map is newer than 05.02.2018?
And what is 1170E? We don't have such naming system.

**Comment by StenSoft** [comment]
[Mikołaja Kopernika has street number (`ref`) 1079E](https://www.openstreetmap.org/way/492502703)

**Comment by bumbaras** [comment]
Ok, so these are OSM specific references. I will try to hide it from display and lecteur if this is possible.
