### ISSUE TITLE
"Change [orange] marker's position" not working

### ISSUE THREAD

**Issue by barteis** [osmandapp/Osmand#4994]
On the Android v. 2.9.0 on a Moto X4 and 2.9.1 on a Moto G Play:

From the orange marker menu, Actions/Change marker's position doesn't seem to work. As soon as I press "Apply", the marker disappears.

**Comment by AlexSyt** [comment]
This option is no longer needed since the marker does not remain on the map. We disabled "Change marker's position" item in the additional action menu.

**Comment by gammeredith** [comment]
Must disagree that this option is no longer needed. Sometimes it is neccessary to position the  orange marker with a high degree of accuracy.  Preferable to use "change markers position" function.
Users have no way of knowing the change marker function has been disabled. It just appears not to work.

**Comment by barteis** [comment]
I agree.  The orange marker is used for planning routes, and so its precise location can be important: even more so than for a favorite or a flag marker.  Please don't disable it.  Re-implement it.  Thanks.

**Comment by dmpr0** [comment]
We have considerably changed the behavior of the context menu. Now, when you close the menu, the yellow marker does not stay on the map. Previous behavior was confusing for the majority of users. With the new behavior, the marker is disappearing after you try to move it. Therefore, we decided to disable the ability to move the marker completely. 
The yellow marker is used to mark a place for which the context menu is opened. If you want to mark a place on the map or the future waypoints, you have other options like favorites and map markers.
