### ISSUE TITLE
Marker disappears on map movement

### ISSUE THREAD

**Issue by theirix** [osmandapp/Osmand#5000]
OsmAnd+ 2.9.3 and before, stock Android 6.0.1 on Moto X Play.
All plugins disabled.

Reproduced always.

Steps:
1. On a main screen choose Search icon
2. Find a POI that can reside in your screen (something near you)
3. Show it on a map. An orange bubble marker appears and a bottom pane appears.
4. Move, pan or zoom the map a little. 
5. The marker and bottom pane disappears.

This issue makes using of the OsmAnd almost impossible.

**Comment by sonora** [comment]
I tend to agree that this is one of our big usability issue, I watch many users struggling with this.

I think the marker should remain on the map until a user explicitly swipes down its context menu, or places another one.

**Comment by theirix** [comment]
Agreed. I think it is a bug (am I alone with this bug?) not a strange feature because I had been using movement with markers in OsmAnd for a long time . Other mapping applications also allow moving and it feels natural multitouch behavior.

**Comment by GinoPane** [comment]
Same here! Wanted to report this but searched at first.

**Comment by gammeredith** [comment]
Totally agree. The change marker position has apparently been disabled as well ( #4994).

**Comment by dmpr0** [comment]
https://github.com/osmandapp/Osmand/issues/4994

**Comment by vshcherb** [comment]
@sonora 
> @vshcherb I tend to agree that this is one of our big usability issues, I watch many users struggling with this.

We had another usability issue when Marker was stuck on the screen. There are plenty of options to pinpoint location i.e. Marker. GMaps approach, when you can pan the map while the bottom part of context menu is present, could lead to another challenge to explain how to close context menu.

Todays approach it is pretty easy to understand how it works and start using markers for example.
I've found myself that it causes some distraction initially but it doesn't look critical after all. Zoom in / out buttons are helpful enough.

**Comment by NoBorderz** [comment]
Hey,
still got this problem..
Version 3.2.2
Android 8.0.0

Can anybody help?
It's really really annoying

thanks

**Comment by vshcherb** [comment]
This is going to change in the next release. As of today please use buttons zoom in / out and Add Marker to keep it always on the map
