### ISSUE TITLE
A/V Notes plugin suggestion: option for a plain text note

### ISSUE THREAD

**Issue by martenjj** [osmandapp/Osmand#5004]
The three types of notes already available - audio, photo and video - are very useful for mapping or other notes, and I frequently use them for noting OSM updates - which I prefer to do later on, instead of live updating OSM from within OsmAnd.

Being able to make a plain text note would be useful in some situations: (a) where making an audio recording or even taking a photo would be indiscreet or would attract attention;  (b) where the spelling of a name has to be noted, and it is not possible to take a photo;  (c) noting a road feature (while not driving of course!) which passes too quickly for a photo.

Obviously these notes should be listed along with the existing types, and downloadable as plain text files.

**Comment by scaidermern** [comment]
You can create text nodes by either adding a GPX waypoint (trip recording plugin) or by adding an OSM note without uploading (OSM editing plugin).

**Comment by iriman** [comment]
I use GPX waypoints or favorites to store text notes. I don't recommend using OSM notes except it's useful for mapping (as it's intended for mapping tasks).

**Comment by vshcherb** [comment]
There is a GPX waypoint plugin indeed which may not be integrated with Audio/Video notes as today but anyway gives a possibility to work with it.
BTW Audio/Video notes also recorded in GPX.
