### ISSUE TITLE
Crash when opening dashboard if animations are disabled

### ISSUE THREAD

**Issue by olavmrk** [osmandapp/Osmand#5006]
After the latest update of OsmAnd on Android (OsmAnd version 2.9.3), the app crashes when I open the dashboard.

The exception is: java.lang.IllegalStateException: Animator has already started, cannot change it now!
(The full stack trace is in the attached file.)

A Google search pointed towards someone else experiencing this with animations disabled, so I tried enabling animations on my device, which did indeed allow the dashboard to be opened.

[OsmAnd bug.txt](https://github.com/osmandapp/Osmand/files/1713403/OsmAnd.bug.txt)

**Comment by olavmrk** [comment]
Just to clarify, as I just found a "Do not use animations" option in OsmAnd settings; I had disabled animations globally on my device through the developer option.

**Comment by Hocceruser** [comment]
You are not the only ones who have this problem: https://github.com/deltachat/deltachat-android/issues/255 and https://stackoverflow.com/questions/45419378/disabling-animations-on-a-device-crashes-the-app (There are answers to the StackOverflow question but I do not know if whoever wrote them was right).
