### ISSUE TITLE
Zoom in/out is very slow

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#5007]
Zoom in/out is very slow on android 8.0 and 8.1. It can only be fixed by disabling animation in OsmAnd. Also reproducible on OsmAnd 2.7.
![screenshot_einstellungen_20180207-132054](https://user-images.githubusercontent.com/12711814/36062775-a42240e4-0e7b-11e8-93a5-23f734702385.png)

**Comment by scaidermern** [comment]
Duplicate of #4323.

**Comment by ADepic** [comment]
Disabling animations doesn't fix this for me.

OS: Lineage OS 15.1 (oreo 8.1)
Device: Oneplus 2
