### ISSUE TITLE
[Bug] Unnecessary map redraw after context menu show and hide

### ISSUE THREAD

**Issue by SergeyP2** [osmandapp/Osmand#5011]
Today I updated OsmAnd+ from 2.8 to 2.9.3 and notices that when I press on POI to see context menu, the app erases the map behind and then draws it again. When I close context menu, the app again clears the whole screen and draws map again. This flickering is really annoying and slows down the app. In case you wouldn't be able to reproduce the bug, I can look for how to record the video.

**Comment by SergeyP2** [comment]
Today I noticed this in another place. In the Ruller tool when I add new points by pressing Add button on the bottom panel then there is no redraw, but if I add new points by pressing my finger somewhere on the map, the OsmAnd clears the map and draws it again.

**Comment by SergeyP2** [comment]
I really don't understand why this annoying flickering hasn't fixed yet? You spend a lot of work-days adding new features, some of them of dubious value, yet you don't spend a tiny fraction of this time to fix bug in a core functionality.

**Comment by vshcherb** [comment]
Ruler tool flickering was fixed in 3.1. Sorry for confusion. If it is a Measure distance ruler please let us know.

**Comment by SergeyP2** [comment]
Version 3.2.1 -- Flickering (unnecessary map redraw) is still here for context menu show, context menu hide, measure distance tool. Nothing is changed.

**Comment by vshcherb** [comment]
3.2.2 was already released and I don't see any issues in the latest build as well

**Comment by SergeyP2** [comment]
Still in 3.2.2.

Here how it looks https://www.youtube.com/watch?v=5QDstRxYWkQ

**Comment by vshcherb** [comment]
Yes, it looks different then on devices we have.

**Comment by SergeyP2** [comment]
Version 3.2.7 -- works good, looks like the bug is fixed
