### ISSUE TITLE
[Feature request] Add option to keep OsmAnd controls in Full Screen mode

### ISSUE THREAD

**Issue by SergeyP2** [osmandapp/Osmand#5014]
Now when you have Full Screen mode in which you hide bottom system panel (with Back, Home, Recent buttons) and in which, I hope, you will hide top system panel also (with clock, battery, and other icons) can you also add an option to keep OsmAnd controls in place in Full Screen mode? So some users will be able to choose to expand screen area available to app to full screen, but retain ability to effectively interact with all functionality of OsmAnd.

**Comment by vshcherb** [comment]
#4878
