### ISSUE TITLE
Allow the user to refresh online tiles

### ISSUE THREAD

**Issue by andrzej-r** [osmandapp/Osmand#5015]
I tried using OsmAnd with online tiles for verifying results of my OSM mapping work. Unfortunately, whether it is because OsmAnd or my device caches tiles, or online tiles haven't been updated on the server, I was unable to see changes I made several days ago. I've deleted files in `data/net.osmand/files/tiles/OsmAnd (online tiles)` but OsmAnd still displayed old tiles.

OsmAnd should have a UI element for refreshing online tiles, analogous to a refresh button in a web browser.

**Comment by littlehelper** [comment]
There exist context menu items for downloading and updating online tiles when long taping on the map.
But these menu items only appear when the online tile map is selected as main map. It does not if used as overlay or underlay map, although already proposed in #2534.

**Comment by andrzej-r** [comment]
Indeed, it works. Thank you! I've seen this option before but I assumed it was for updating local (offline) maps.

There is one problem with the way it is implemented, though:
I have to update every single view at each zoom level, which is a lot of work, especially on smaller screens. I'd much more prefer to zoom out to see the area I want to update, and update/invalidate the current view and all tiles in it at higher zoom levels.

**Comment by andrzej-r** [comment]
Was that issue resolved? Rejected?
