### ISSUE TITLE
change user_defined_other to fixme+note

### ISSUE THREAD

**Issue by Marc-marc-marc** [osmandapp/Osmand#5018]
When a mapper try to create a feature that doesn't exist in osmand preset, it seems that osmand create it with user_defined_other=*
It should be usefull to change it to fixme=* + note=I don't find the correct tag in presets of my editor.
that would allow other mapper to see/understand the problem more easily (a lot of tools diplay fixme tag) and help to fix it.

it would undoubtedly also be useful to propose that osmand send a copy of the values to devs in order to add the most requested preset. Top current values:
tree
Recycling
street
street_lamp
Hunting␣stand
station
lodging␣house
pension␣house
Bench
cng
shop
Spring | 6
Post␣box | 6

**Comment by dmpr0** [comment]
Hi! Could you please provide more details. We try to reproduce this behavior, and we can't do it. We don't find situation when OsmAnd change not existing tag name to user_defined_other.

**Comment by vshcherb** [comment]
Very likely that issue is related to old OsmAnd versions and it was fixed already.
