### ISSUE TITLE
USA: Business Interstate shields rendering request

### ISSUE THREAD

**Issue by rickmastfan67** [osmandapp/Osmand#5019]
Is it possible to support rendering these types of shields as well here in the USA?  Right now, when their route number is rendered, they look like the 'state' shield bubbles, which can be possibly confusing to users.

https://www.openstreetmap.org/relation/1014596
https://www.openstreetmap.org/way/316631719
https://en.wikipedia.org/wiki/List_of_business_routes_of_the_Interstate_Highway_System
http://www.aaroads.com/shields/show.php?image=PA19793763

All the routes are tagged with the network tag of "US:I:Business:Loop" or "US:I:Business:Spur" in the relations, and you could use the same 'Interstate' type shield for both without any problems (as long as it's green of course).

It would be great to see the proper shields for them if possible.  I've also attached an example of how it currently looks with the latest map data for Pennsylvania for the route mentioned above.
![business_interstates](https://user-images.githubusercontent.com/8424257/36141280-2299bf18-1072-11e8-913a-5c1caa3e086f.png)

Please don't let Google one-up this great app since they [already render them properly](https://www.google.com/maps/@40.4709088,-80.2019385,16.5z).

**Comment by xmd5a2** [comment]
Will be available in march maps.

**Comment by rickmastfan67** [comment]
@xmd5a2, Looks great in the update this month.  However, I noticed 2 small issues with the rendering.

1.) 3di Business shields look fine, however, the 2di ones seem to be using a 3di shield and look very squished compared to a normal Interstate shield. (see attachment below)

2.) It seems that a normal Interstate shield is getting rendered behind a Business Interstate shield, as you can see the top of the 'red' of the normal shield.  This is happen with both 2di (shown below) & 3di routes.

![busi-shield-issues](https://user-images.githubusercontent.com/8424257/37336827-edb58610-2688-11e8-910e-36d52cb21615.png)

For reference, here's the link to the [I-83 Business Loop on OSM](https://www.openstreetmap.org/relation/1070432).
