### ISSUE TITLE
Ski profile for planning routes

### ISSUE THREAD

**Issue by rindlerblabla** [osmandapp/OsmAnd#5021]
For planning ski routes it would be nice with a profile which accepts piste:type and aerialway. At least one other user agree on that, hehe, https://groups.google.com/forum/m/#!topic/osmand/Xp-tsITE8GI

Personally I don't need advanced routing rules but rather to be able to use the snap-function when using the measure tool.

**Comment by xmd5a2** [comment]
After some investigation I've found that OSM data related to ski aren't routable. In most cases there is no connection between aerialway stations and pistes. Also some pistes are mapped as areas hence we can't calculate route via them.

**Comment by rindlerblabla** [comment]
Okey, it was the other user in the Google group that suggested for other types of piste types than nordic. At least for piste:type=nordic it's clearly usable and would be nice to have as feature.

**Comment by scaidermern** [comment]
> In most cases there is no connection between aerialway stations and pistes.

There are several ski areas where pistes and aerialway stations do have connections. But I remember a discussion somewhere about how these connections should be tagged. Maybe someone is able to find it.

**Comment by pietervdvn** [comment]
Hey,

It is correct that most ski pistes are connected badly. However, I've been skiing and cleaned two ski areas (a small one [here](https://www.openstreetmap.org/relation/902341#map=14/47.4699/13.2850&layers=N) and [here](https://www.openstreetmap.org/search?query=serre%20chevalier#map=13/44.9286/6.5939&layers=N))

If you would include them into the map builds; I'll gladly create the routing.xml for skiing. Also, as soon as this is in beta; everyone OSM'er with Osmand Live who will go skiing next year; will gladly fix this up. Just communicate clearly that this feature is in beta.

**Comment by rindlerblabla** [comment]
@pitchblack1 But not only pistes but also aerialways should be connected to be able to use routing engine (?).  As far as I could see from the areas you had corrected still the aerialways are not connected to the piste? Think an unnamed piste:type=downhill way should be just fine.

**Comment by pietervdvn** [comment]
Hey,

I had a look again to Werfenweng (it's been a few years). Someone added a new chairlift (for which I don't know where it ends). The rest should be still properly connected (or I fixed it now).

The other area (Serre Chevalier) was more or less fixed last week.

**Comment by scaidermern** [comment]
@rindlerblabla Yes, exactly. Thanks :)

**Comment by mahlzahn** [comment]
Any news on that? With
```
<routingProfile name="car" restrictionsAware="false" minDefaultSpeed="4.0" maxDefaultSpeed="20.0" onewayAware="false">
  <way attribute="access">
    <select value="1" t="piste:type" v="nordic"/>
    <select value="1" t="route" v="piste"/>
    <select value="-1"/>
  </way>
</routingProfile>
```
in the [routing.xml](https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml) (here profile `"car"` is misused) the routing in Osmand app works already quite well for nordic skiing.

**Comment by pietervdvn** [comment]
Did you test that? AFAIK piste information (at least downhill) is not included in the routing-part of the .obf. If you roll your own file, that could work.

Anyway, I'm working on it and hope to have something workable by the weekend. You can find my code [here](https://github.com/pietervdvn/OsmAnd-resources/tree/features/skirouting). If you need a custom .obf for a certain region, let me know.

**Comment by mahlzahn** [comment]
I did not try with downhill, only nordic, and this worked well with included map. But it worked only with routes and not as it should with `piste:type=nordic`.

I would be happy in testing and working on the new feature (in particular for nordic skiing), could you give me indeed a custom .obf for some region, preferably including [this pull request](https://github.com/pietervdvn/OsmAnd-resources/pull/1). Thanks!

**Comment by pietervdvn** [comment]
@mahlzahn : I've left instructions to create your own maps here: https://wiki.openstreetmap.org/w/index.php?title=User:Pietervdvn/Skirouting-with-Osmand&wteswitched=1#A_few_other_pointers

I might roll a few maps this evening.

**Comment by pietervdvn** [comment]
@mahlzahn I've also set up automatic creation of maps. You can find them here: https://github.com/pietervdvn/pietervdvn.github.io/tree/master/Quickmaps/cache/SkiObf

Send me a message if you want to have a region added.

**Comment by mahlzahn** [comment]
@pietervdvn Thanks to your instructions I was able to create my own test maps.

I implemented ski routing in four different options (`downhill`, `nordic`, `skitour` and `sled`) in a dedicated ski profile. See here few [screenshots](https://wiki.openstreetmap.org/wiki/User:Petermahlzahn/osmand) of the routing and the current navigation settings menu.

My code is in branch `features/skirouting` of [Osmand](https://github.com/mahlzahn/Osmand/tree/features/skirouting) and [OsmAnd-resources](https://github.com/mahlzahn/OsmAnd-resources/tree/features/skirouting) repositories.

**Comment by pietervdvn** [comment]
Ah, god damn it! Now I'll have to build the app myself! Congrats on all the work though, it is pretty cool - you lifted my initial attempt to a further level.

TBH, I'm not really sure that the ski data is ready yet for prime time. My roadmap would be to distribute the routing amongst the OSM-community, have them fix up and only mainstream it when most routes would be fixed (with an intermediaty step of having OsmAnd build the ski routable maps but not yet providing actual routing unless explicitly enabled). On the other hand, having big exposure will mean that the ski routes will be fixed in no time.

This is however something that the OsmAnd team should decide on. We'll see how it works out.

**Comment by vshcherb** [comment]
We will continue to build maps with ski data included, also we will have routing profile for skiing in the app but it won't be configured by default to not confuse with preliminary results.

**Comment by pietervdvn** [comment]
A cool and pragmatic approach! Looking forward to go skiing again now.

**Comment by Romkabouter** [comment]
This is great, my season is over now but will check and fix next winter for sure!

**Comment by Discostu36** [comment]
Can this be closed now with the ski profile being part of the app or is there still some feature missing?

**Comment by pietervdvn** [comment]
IMHO yes
