### ISSUE TITLE
[Feature request] "Take a photo" shutter button

### ISSUE THREAD

**Issue by barteis** [osmandapp/Osmand#5022]
From the context menu, Actions/Take a photo" takes a photo with almost no opportunity to frame it:  you don't see what you've captured until you've already captured it. The refresh-arrow icon does start the process over--if you manage to tap it on time.  But I think most users would find a conventional shutter button less frustrating, more intuitive.

**Comment by dmpr0** [comment]
Hello @barteis!
You can use system camera, where you need to press shutter button, for take a photo. 
**Open Menu - Plugins - Audio/Video notes - Settings - Check: Use camera app**

**Comment by barteis** [comment]
I missed that. Thanks so much Dmitriy.
