### ISSUE TITLE
Water rendered as land 

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#5024]
On Android 7.1.1, lake Garda is rendered as land on closer zoom.
https://www.openstreetmap.org/relation/8569
![joxi_screenshot_1518620088156](https://user-images.githubusercontent.com/12711814/36210709-d4b054a6-11a7-11e8-9d6d-42ba5bedb4e9.png)
![screenshot_1 km](https://user-images.githubusercontent.com/12711814/36210719-d9a96786-11a7-11e8-854f-045feb504de7.jpg)

**Comment by xmd5a2** [comment]
Fixed
