### ISSUE TITLE
Add text label for hazard icon

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#5026]
![hazard](https://user-images.githubusercontent.com/9365308/36251288-52c302ac-1249-11e8-8582-e3631ef1b07c.png)
Hazard icons on map shows, but without explanation. We need add text label or open context menu for it.

**Comment by xmd5a2** [comment]
"hazard" tag is used mainly with highways. It can be useful to show notifications according to this tag while driving.
https://taginfo.openstreetmap.org/keys/hazard#values
http://overpass-turbo.eu/s/weH

**Comment by vshcherb** [comment]
https://www.openstreetmap.org/way/129388680#map=19/-33.87587/151.20585

**Comment by vshcherb** [comment]
https://www.openstreetmap.org/node/3420655036

**Comment by xmd5a2** [comment]
Fixed
