### ISSUE TITLE
House numbers not always shown, though they're present on OSM

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#5028]
House number is shown correctly for Public library (Fruitvale Avenue 3565)
![screenshot_2018-02-15-14-30-47-296_net osmand dev](https://user-images.githubusercontent.com/12711814/36257098-3cb87b08-125e-11e8-99eb-90231a5495d0.png)
![joxi_screenshot_1518698259852](https://user-images.githubusercontent.com/12711814/36257103-40631c4a-125e-11e8-850a-8f7a940c030d.png)

At the same time, it is not shown at Taqueria Los Comales, Oakland, California, MacArthur Boulevard, 2105.
![screenshot_2018-02-15-14-28-58-784_net osmand dev](https://user-images.githubusercontent.com/12711814/36257110-474f85e8-125e-11e8-8c94-89d5efa05713.png)
![joxi_screenshot_1518697647423](https://user-images.githubusercontent.com/12711814/36257116-4a3c98a4-125e-11e8-813a-42cf53695867.png)

**Comment by ADepic** [comment]
Yup, seen that too, but now island has this "online search" feature which searches online results databases (such as osm nomination) and gives the results openstreetmap has
Scroll down to the bottom of the results after making a search, and press (online search)

**Comment by nereocystis** [comment]
But that only works if you are online. :)

**Comment by ADepic** [comment]
I mean I added house numbers and now they have been downloaded. It takes a map update or two for osmand to realize house number changes. Most people have basic mobile data tho

**Comment by nereocystis** [comment]
These locations I have mentioned have had addresses for quite a while on openstreetmap, but the address doesn't show up in osmand.

I rechecked my examples today. The library at the top now does *not* show the address, just the street.

**Comment by nereocystis** [comment]
Thanks.

**Comment by ADepic** [comment]
If you turn on live updates, and then click "update now" on your map region, then the house numbers will show up.
