### ISSUE TITLE
Regression: We somehow messed up car routing

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#5030]
We may have other Issues in our list about this already, need to research:

Pick any test route of say 20 km or so. The route may for pedestrian mode calculate in about 2 secs or so, but it takes **about 5-20 times longer when car routing is selected**. As for bicycle routing, the situation is more unclear, but it is usually closer to the car time. Things seem independent of map creation date. Looks like the issue started to aggravate some time in December:

Identical start/end points, OsmAnd-master-nb-2017-06-20 build:
- pedestrian: 1-2 s
- car/bicycle: 13s      _--> [Question 1: Why is this so much longer than ped routng?]_

2018-02-09 build:

- pedestrian: 1-2s
- car: **40s**      _--> [Question 2: What happened early December? (Think this started around Dec8)]_

**Comment by sonora** [comment]
After some more testing, I am not sure the issue was entirely introduced in mid December.

Looks like with a December 3 build, car routing took already twice as long as pedestrisn routing. But then with mid December builds (after resolving #, the same route with car profile became slower by another factor of 2!

**Comment by scaidermern** [comment]
Why does car routing take so long compared to pedestrian routing? Pedestrian routing has to consider more ways than car routing. Is it because of additional constraints such as turn restrictions?

**Comment by bitboy85** [comment]
Pedestrian has more ways, thats true, but i think pedestrian has a "fixed" speed (maybe without penalties). For cars it is necessary to calculate speed Limit, turn penalities, maybe surface checks, as said turn restrictions. Did anything of this change during december?

**Comment by sonora** [comment]
@crimean https://github.com/osmandapp/OsmAnd-core/commit/d888ed81654fb377349963ca370a5210c27cf8e6 is a candidate, I guess?

**Comment by crimean** [comment]
@sonora core's master branch is not related to routing at all. The router's code is in core-legacy branch. Please provide an test start/finish points where routing is slow.

**Comment by sonora** [comment]
In fact, I think the issue is present everywhere, but for the specific test reported in post 1 above: I picked two neighboring cities off the Germany_Bavaria map (I got he August 1, 2017 edition), and used their alphabetically first street name, each with house number 1:
 - **From:** Nürnberg, Aachener Str. 1
 - **To:** Erlangen Adalbert-Stifter-Str. 1

**Comment by PaulStets** [comment]
@sonora I have checked the route you provided in the following versions: 2.6.5, 2.7.4, 2.8 and the current nightly build. The time of the calculation was absolutely identical for me on two devices (a rather slow Nexus 7 2013 with Android 7.1.1 and a fast Xiaomi redmi Note 3 pro with Android 6). However, I agree that the route calculation in the pedestrian mode is significantly faster than that for the cars. I suspect that the difference comes from the number of conditions in the routing.xml for the aforementioned profiles.

**Comment by bitboy85** [comment]
Maybe it is possible to add some timers in the code to meassure the time each check /condition takes to calculate and an additional "raw" value where the route is calculated without any additional conditions.
This Information could help to improve the (re) calculation.

**Comment by vshcherb** [comment]
@PaulStets @sonora the pedestrian routing is faster cause it is using Heuristic Coefficient 1.4 which is not producing 100% correct routes. Using 1.2 could give 3-5 times speed up but in car routing we removed that "optimization" 3 years ago due to many complaints of small detours.

**Comment by PaulStets** [comment]
@vshcherb The routing became slower after the commits into ```legacy_core``` branch dated December 4th.

**Comment by vshcherb** [comment]
@PaulStets which commits? So I think we should test it thoroughly and find it

**Comment by vshcherb** [comment]
Most likely this commit https://github.com/osmandapp/Osmand/issues/5030

**Comment by PaulStets** [comment]
@vshcherb This one: https://github.com/osmandapp/OsmAnd-core/commit/374b7bd92dcb27b4dc6ded6670b0e0a642de8bd7. I have even made a comparison table: https://drive.google.com/open?id=1dz-v-OLSEBrrcfqQusHhWtrsxN6KPx2GyWKtYbJP5Zg

**Comment by crimean** [comment]
@sonora Should be fixed now. Please check.

**Comment by sonora** [comment]
I have limited means testing right now, but I clock my test route at 33 sec now vs. 40 before (same device), so I guess there may still be  room for improvement,  respectively we may not have found the root cause...

**Comment by crimean** [comment]
@PaulStets please do tests again

**Comment by PaulStets** [comment]
@crimean Seems to be fixed: ``` RoutePlannerFrontEnd Native routing took 30.205 seconds ```. It's three seconds longer than 2.7.0, so I guess it's fine compared to 52 seconds before the fix.
