### ISSUE TITLE
Not possible to select charging station from "Add POI" dialog helper

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/OsmAnd#5031]
When typing "charging" in POI type field only "osmand_electricity_combined_charging" is suggested
![screenshot_2018-02-16-11-02-27](https://user-images.githubusercontent.com/5829014/36298462-544f2f0e-1309-11e8-915f-907e48bc78f5.png)

**Comment by dmpr0** [comment]
Looks like it fixed now.
![photo_2020-08-12 14 13 34](https://user-images.githubusercontent.com/9365308/90009045-041e5500-dca6-11ea-8f14-984ff1439e4a.jpeg)
