### ISSUE TITLE
Marker disappears after its movement and confirmation of this action

### ISSUE THREAD

**Issue by GinoPane** [osmandapp/Osmand#5035]
You can put a marker on the map, after that "actions" menu becomes available in the right bottom corner. There's an action something like "adjust position" there. After adjusting of position and pressing "apply" the marker disappears.

Here's the video demo: https://youtu.be/FPwze3WCGGM

**Comment by dmpr0** [comment]
Thank you for feedback, we already have same issue in milestone https://github.com/osmandapp/Osmand/issues/4994

**Comment by gammeredith** [comment]
#4994 has also been closed without the issue being resolved or explained adequately.

**Comment by GinoPane** [comment]
@gammeredith Yep. Fixing the issue by removing the feature 😄
