### ISSUE TITLE
Send geographic location to Nominatim when searching

### ISSUE THREAD

**Issue by BalooUriza** [osmandapp/Osmand#5036]
Osmand should send a bounding box equivalent to the search radius when making an online search, so that the most likely _local_ result is one of the first results, rather than a distant, possibly different-continent result.  For example, while sitting near Jenks, Oklahoma, [the entire first screen is filled with irrelevant results when searching for Walmart now](https://i.imgur.com/ukIRA4I.png).

_What version of OsmAnd are you using, on what device and Android/iOS version?_

Osmand~ 2.8.2 on Android 8.1.0

_Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?_

Offline with Bing imagery semi-transparent as overlay.

**Comment by vshcherb** [comment]
Strange enough it is not even sorted. Though the location should be provided and it could be double checked

**Comment by vshcherb** [comment]
I think there should be an option to "Natural Sort" "Sort by distance"

**Comment by vshcherb** [comment]
Just tried and the issue is not present any more. Search both via Categories -> Online and Nothing Found -> Online
