### ISSUE TITLE
Add hillshade layer transparency

### ISSUE THREAD

**Issue by littlehelper** [osmandapp/Osmand#5037]
Hi,
I use the hillshade layer quite often. Beside the noticable issue in rendering these hillshade data (#2183) it is very handy in getting an overview about a region with many valles.
In some regions the hillshade darkenes the whole screen when zooming in. So the proposal to provide the possibility to set a min and max zoom level for the hillshade layer in the corresponding 'configure map' submenu (#3359) would be a solution for that.
An additional improvement for me would be a possibility to change the hillshade layer transperancy. I would love to see a slider in the 'configure map' submenu to set the hillshade layer transparancy (as already possible for overlay and underlay maps).
greetings

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/issues/3359
