### ISSUE TITLE
Provide contour lines density and width settings for all rendering styles

### ISSUE THREAD

**Issue by littlehelper** [osmandapp/Osmand#5038]
Hi,
I very often use the possibility of the map style 'Topo' to set the contour lines density and width. It seems to me that reducing the contour lines density speeds up the map rendering.
It would be great if the two settings 'contour lines density' and 'contour lines width' are available for all map rendering styles (at least 'Touring view' which I use most often).
greetings

**Comment by rindlerblabla** [comment]
I think it would be nice if it was possible to have a value with even higher density (5m).

**Comment by xmd5a2** [comment]
@rindlerblabla that will double contour map data. Besides best available relief data have a distance between samples about 30m (horizontal axis), so 5m contour lines hardly will give useful information.

**Comment by rindlerblabla** [comment]
@xmd5a2 Okey! Thanks for your reply. The contour files for the regions (in Sweden) I am interested in the is about 8-24 mb, so not that big. There are open data for Sweden with 5m contour lines, see https://www.lantmateriet.se/globalassets/kartor-och-geografisk-information/kartor/produktbeskrivningar/eng/e_terrshmi.pdf but understand if that's not the priority to fix.
