### ISSUE TITLE
Is Osmand totally free software?

### ISSUE THREAD

**Issue by artoborty** [osmandapp/Osmand#5039]
My smartphone is running Lineage 7.1.2. with no GApps installed, in order to keep it free from proprietary software as much as possible. Before installing Osmand, I would like to know if this interesting app it is completely free software or if some parts of the software are proprietary or if there is any proprietary library. Thanks in advance!

**Comment by jfburke3** [comment]
It is open-source, and you can download the code and build it yourself. There are free (no charge) and paid (charge) versions in the Android store. I've heard that someone publishes it on f-droid.

It's pretty good software. Good enough for me to pay for it.

**Comment by artoborty** [comment]
@jfburke3 I found this link https://groups.google.com/forum/#!topic/osmand/CyCNIf0CXLg with a similar topic. Unfortunately I do not have the skills to analyze the source code, anyone can tell me if currently there are any proprietary dependencies like the old libGoogleAnalytics.jar? 
I have read that Osmand find images through the proprietary service Mapillary, is it possible to disable this service on my smartphone?

**Comment by sonora** [comment]
https://github.com/osmandapp/Osmand/blob/master/LICENSE

**Comment by zayuim** [comment]
This is from the F-Droid page:

Anti-Features:
* NonFreeAssets - Artwork and layouts are under a non-commercial license.
* NonFreeNet - May download images from nonfree Mapillary online service
* NonFreeAdd - Proposes to download a proprietary app (Mapillary) from Google Play Store to add photos to their service

I use it on the same sort of setup as you, and it seems to work a treat. Keep in mind that only applies to the F-Droid build, so more anti-features might be present on a Play Store build.

**Comment by vshcherb** [comment]
No OsmAnd is not  completely FREE software! It is open-source first of all. 

OsmAnd is FREE software if you want to build it yourself & use it.

OsmAnd is not FREE to distribute it, i.e. it has restrictions with distribution via Google Play and it has restrictions with selling the application.

Typo:
> NonFreeAssets - Artwork and layouts are under a non-commercial license.
Under a "commercial" license.

> NonFreeNet - May download images from nonfree Mapillary online service
Option could be disabled

> NonFreeAssets - Artwork and layouts are under a non-commercial license.
The copyright of some of artwork doesn't belong to OsmAnd. The copyright of layouts is present to restrict the app distribution.

**Comment by tuxayo** [comment]
@vshcherb 

> No OsmAnd is not completely FREE software! It is open-source first of all.

You mean source-available, right?
https://en.wikipedia.org/wiki/Source-available_software
https://en.wikipedia.org/wiki/Open_source

99.999% of free software are open source software and vice versa. So to simplify from a legal, license point of view, free software is the same as open source software.

> > NonFreeAssets - Artwork and layouts are under a non-commercial license.

> Under a "commercial" license.

non-commercial is really the common term to describe a license that forbids commercial usage: https://creativecommons.org/licenses/by-nc-nd/4.0/

I get what you mean by "commercial" license but it's a misunderstanding relating to Free Software understood as "free as in free beer" so no sold. (freeware is the unambiguous term for software where one does not pay) But Free Software is about being "free as in freedom" and it can be sold. Like Conversations (and XMPP messenger) is sold in the PlayStore.

**Comment by vshcherb** [comment]
Lots of terms that are defined differently in different situations doesn't help to make situation easier to understand.
I think scenarios of usage are much more important than terms "open-source", "free" cause they will be misleading in many cases.
