### ISSUE TITLE
Bus routes missing in the POI context menu

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#5045]
Location: bus stop at Lat 49.71924 Lon 11.04229.

The bus master route 206 includes the following bus routes: 
- VGN Linie 206 (Hauptweg) Forchheim - Zeckern 
- VGN Linie 206 (Weg 2) Forchheim - Thurn 
- VGN Linie 206 (Weg 3) Forchheim - Poppendorf 
- VGN Linie 206 (Weg 4) Forchheim - Oesdorf 

In the previous version of osmand+ all these routes were shown in the POI context menu. In the new version, only the last one is shown.

**Comment by OpenSourceForEver** [comment]
I think this is related to https://github.com/osmandapp/Osmand/issues/5540

**Comment by OpenSourceForEver** [comment]
I think this is fixed with #5831

**Comment by PaulStets** [comment]
Ok, thanks.

**Comment by OpenSourceForEver** [comment]
I have tested it and I think it is solved. It would be better if someone else could tested it

**Comment by PaulStets** [comment]
@OpenSourceForEver I have tested it before closing the issue. Thanks again for letting us know.
