### ISSUE TITLE
Wrong "Turn right"

### ISSUE THREAD

**Issue by bitboy85** [osmandapp/Osmand#5054]
I noticed in issue in the new version using the february map. The issue wasn't present in past versions.
It might be related or same issue as https://github.com/osmandapp/Osmand/issues/3714

Lane assistant and voice saying turn right but then you end up on the yellow way. Drawing is correct.
![screen](https://user-images.githubusercontent.com/6197580/36539853-1ce82c02-17d0-11e8-9684-0180d9fed12b.PNG)

https://www.openstreetmap.org/edit#map=19/49.77512/6.38176

**Comment by hakuchi** [comment]
I can confirm this.
tested with latest nightly and latest map.

Osmand is showing always the turn right arrow if I drive through.

**Comment by jfburke3** [comment]
I think I've encountered this, too, but I was driving at high speed, in traffic, and so couldn't take time to document/capture it.

**Comment by bitboy85** [comment]
Can you please fix this in the next version?

**Comment by MadWasp79** [comment]
fixed intersection in OSM
