### ISSUE TITLE
"Attention" on tunnel

### ISSUE THREAD

**Issue by bitboy85** [osmandapp/Osmand#5058]
With https://github.com/osmandapp/Osmand/issues/3773 was a warning for tunnels introduced. I noticed that in the Settings you can turn off and on the Icon which is displayed but it is not possible to turn off the spoken "Attention" at each tunnel, there is no setting.

Maybe it is already implemented but i think on very short tunnels it is not necessary to give a warning at all.

There is a typing in the german Translation. The plural of "Tunnel" is also "Tunnel", not "Tunnel**s**"

**Comment by scaidermern** [comment]
> There is a typing in the german Translation. The plural of "Tunnel" is also "Tunnel", not "Tunnels"

Actually "Tunnels" is valid but rarely used according to https://www.duden.de/rechtschreibung/Tunnel_Bauwerk and https://de.wiktionary.org/wiki/Tunnel :)

**Comment by hakuchi** [comment]
if you drive on a street with a lot of tunnels the "Attention" is annoying.

There should be a option to switch the  tunnel voice off.
Also the "Attention" is not the best solution. I think this can be better announced with "Tunnel ahead"

**Comment by vshcherb** [comment]
Looks like in previous release we didn't manage properly work out on vocal announcement.

**Comment by sonora** [comment]
@vshcherb Victor, I have now implemented the capability to announce "Attention, tunnel!" in all our 37 voice languages, see https://github.com/osmandapp/OsmAnd-resources/pull/490. This can be dry-tested using the new test voice button (9.9).

I have not yet tested this in live navigation, in particular I am not sure if we need not still create the appropriate AlarmInfo in `createAlarmInfo()`.

But whatever is left now should be independent of the voice prompt capability, namely the request to suppress (optical/voice) tunnel warnings in the settings, or to suppress successive warnings for repeated occurrences.

**Comment by sonora** [comment]
PS: I have just committed this https://github.com/osmandapp/Osmand/pull/5215 which should solve the original request put forward in this issue. Please test.
