### ISSUE TITLE
Deleting favourite contex menu not shown

### ISSUE THREAD

**Issue by pl71** [osmandapp/Osmand#5063]
When you click a favourite point on the map, there is a toolbox down, starting with "Edit".
When you touch "Edit", you can edit the favourite name and folder, but button for deleting the favourite point is not visible. It appears, AFTER starting editing the name.
In the previous versions it was not like that as I can remember.
In simple words - deleting a Favourite point is not easy.

OsmAnd Version: 2.9.3
Device: Samsung S8
Android: 7.0

**Comment by vshcherb** [comment]
Confirmed, delete is not shown when there is no keyboard

**Comment by vshcherb** [comment]
it was fully redesigned in 3.7
