### ISSUE TITLE
Feature request: center the map view on the last known position on GPS signal loss

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#5068]
Pressing the "Center on current location" when the GPS signal is lost leads to the toast 'Position is not yet known". It would be better to center the map on the last known position.

**Comment by pebogufi** [comment]
+1 !

**Comment by polhar** [comment]
+1

**Comment by Friptick** [comment]
This was added to a now-closed milestone, does that mean it has been officially forgotten? This is a consistently annoying problem, correcting it seems like low-hanging fruit.
