### ISSUE TITLE
Program not installed

### ISSUE THREAD

**Issue by SergeyDjam** [osmandapp/Osmand#5069]
I update 2.8.2 to 2.9.3
OsmAnd (Google Play) 2.8.2 to OsmAnd (Google play) 2.9.3 , 
OsmAnd~(f-droid) 2.8.2 to OsmAnd (f-droid) 2.9.3 
on ASUS  Zenfone 4 (T00I), Android 5.0

anyway the program is not installed without error message, reported just "the program is not installed"

**Comment by PaulStets** [comment]
Perhaps you had a nightly version installed before. Anyway, please backup the following path: Android/data/net.osmand.plus (or without .plus for OsmAnd), uninstall OsmAnd and install it again. After the installation put back the files you've copied.

**Comment by SergeyDjam** [comment]
No, is not nightly version. All OsmAnd installed from google play and f-droid only

**Comment by PaulStets** [comment]
@SergeyDjam Perhaps the PackageManager on your device is broken. The described behavior only happens when you are trying to install the older version instead of the newer. Anyway, please try the clean- install solution.

**Comment by SergeyDjam** [comment]
I doubt problems of the manager of packets. Such problem only with osmand packets. Remaining packets are set with hardly any trouble at all.

**Comment by dmpr0** [comment]
@SergeyDjam Try to delete F-Droid version and update OsmAnd from Google Play.
