### ISSUE TITLE
'Add favorite group' dialog displayed behind the keyboad

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/OsmAnd#5070]
The issue only happens on Moto G5, running Android v7.0.

when trying to edit the category of a favorite point the dialog is displayed behind the keyboard. Pressing the 'Back' button closes the dialog.

Suggestion: close the keyboard when the dialog is displayed.

Screenshot:
![screenshot_20180223-125437](https://user-images.githubusercontent.com/20681525/36678250-e95a1156-1b18-11e8-995a-22bc81849bea.png)

**Comment by vshcherb** [comment]
@PaulStets can we reproduce on another phone?

**Comment by PaulStets** [comment]
@vshcherb No, only reproducible on this particular device.

**Comment by dmpr0** [comment]
A new dialog for selecting a group is implemented.
