### ISSUE TITLE
Lost feature: Destinations no longer displayed on motorway ramps/links

### ISSUE THREAD

**Issue by mdroads** [osmandapp/Osmand#5071]
My normal usage is in free (non-navigation) mode, to display tags on each way traveled for possible later editing.  Mainly the display of the street name and ref (if present) at the top.  On and near ramps of interchanges, the destination:* tag info displayed at the top as well. Example "I 95 North >> New York" 

At some point this feature was lost for the motorway_links and other link ways as well, it only displays "Near (Road Name)."  However it still displays destination info on mainline motorways that happen to have destination info tagged.

**Comment by sonora** [comment]
We had explicitly introduced this, and am not aware this disappeared again ... needs to be verified if it is generally gone and why.

**Comment by vshcherb** [comment]
Needs to be verified, it is not clear what was the change. May be some screenshots will help

**Comment by Hedaja** [comment]
If I understand the issue correctly I can't reproduce it.
I tested it on a motorway link and the destination gets shown on top. It also switches to the destination of the next turn.
![screenshot_2018-05-17-11-02-53](https://user-images.githubusercontent.com/693781/40167825-4eb4010a-59c2-11e8-8ed1-a66f72c41225.png)
![screenshot_2018-05-17-11-03-11](https://user-images.githubusercontent.com/693781/40167858-61fdd434-59c2-11e8-9569-d13a12c8f3cf.png)
