### ISSUE TITLE
Opening wikipedia articles in browser does not work due to wrong language selection

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#5074]
I use GERMAN as display language for this test, because there is a language problem.
First be shure that you have installed:
Map+WIKI "France Grosser Osten" (=France Grand Est),

Open in menu "Suche" (EN:search), open ADRESSE (EN:ADDRESS)
Select "ORT WÄHLEN" (EN:SELECT CITY)
enter strasbourg
click on Strasbourg
click STRASBOURG AUF DER KARTE ZEIGEN (EN:SHOW STRASBOURG ON MAP)
Open BESCHREIBUNG (EN:DESCRIPTION)
Open "Wikipedia-Artikel zur Umgebung"
Click on "Hanauer Hof" (First line) --> "Hanauer Hof" is DE/German !!!
![screenshot_1](https://user-images.githubusercontent.com/18628183/36729615-19cd9df6-1bc5-11e8-9d44-f1bb93a69532.png)

Click on Artikel lesen (EN:READ Article)
![screenshot_2](https://user-images.githubusercontent.com/18628183/36729642-2a476e3c-1bc5-11e8-939c-104897890ac2.png)

now you see in the title"Hôtel de Hanau", this is the **french text** of "Hanauer Hof".
But the current language (top right corner) is DE. ---> HERE WE HAVE THE PROBLEM !!!
**Langue of title should match to language code** 

click on "VOLLSTÄNDIGEN ARTIKEL LESEN (ONLINE)" (EN:READ FULL ARTICLE(ONLINE)"
which will open the  bowser
Now I have the problem that I get the message "diese Seite existiert nicht" (EN:the article/page is not found)  because the selected language is (DE= German) but the text to search for "Hôtel de Hanau" is FR=French.

This problem we had already in summer, it was fixed.
osmand version 2.9.0#23876

**Comment by AlexSyt** [comment]
Fixed with 870bfe2e2b6cf21bbaa1e59b877c5f897ba660d0
