### ISSUE TITLE
A problem with font in persian

### ISSUE THREAD

**Issue by biomanw** [osmandapp/Osmand#5075]
Problem with persian litral in osmand~ (fdroid version)
Please use a free opensource persian font also that support persian "ی" letter

**Comment by FTABoy** [comment]
there is no problem with Persian font in osmand+ 2.9.3 and old version also are okay. the "ی" character is also ok too and is supported. can you demonstrate the problem in screenshot?
what exact version are you using?
![photo_2018-03-01_11-35-56](https://user-images.githubusercontent.com/25687276/36833478-bb489156-1d44-11e8-8ee6-3da22bfcec11.jpg)
as you can see in my screenshot , every thing is okay.

**Comment by touzainanboku** [comment]
The issue can only be seen on the F-Droid version. The one on the Play Store is fine. It's still there on version 3.0.3.
