### ISSUE TITLE
Bus route visualization

### ISSUE THREAD

**Issue by contrapunctus-1** [osmandapp/Osmand#5078]
OsmAnd seems to display bus routes for a stand in two ways, as demonstrated in this image -

![](https://cloud.woelkli.com/index.php/apps/files_sharing/ajax/publicpreview.php?x=1080&y=600&a=true&file=Screenshot_20180227-153047.png&t=xgxJhRuYoXiKI5V&scalingup=0)

In the first way ("85 85: Punjabi Bagh Terminal => Anand Vihar ISBT (2 m)"), tapping the name highlights the bus route and all of its bus stops. I'm not sure how OsmAnd decides which route to display in which style, but it'd be a great help to both users as well as mappers in cities with incomplete PT data if it was possible to visualize the route for every bus route in OsmAnd.

**Comment by dmpr0** [comment]
@contrapunctus-1 Hi! Please update your OsmAnd, we do a lol of work in transport context menu in new 2.9 version.

**Comment by contrapunctus-1** [comment]
@dmpr0 thanks for pointing that out! 2.9.3 isn't yet the recommended version in F-Droid, but I gave it a spin regardless [1]. Unfortunately, the problem still seems to persist. (I'll confirm once I get home to a laptop and JOSM.)

[1] off-topic - Jesus Christ, that improved OSM Edits screen is a life-changing material! And the new POI menu is just beautiful!

**Comment by contrapunctus-1** [comment]
Can confirm this is still an issue.

Example 1 -
https://www.openstreetmap.org/node/3744528116
![](https://i.imgur.com/TTKtK7n.png)

Example 2 -
https://www.openstreetmap.org/node/5124331006#map=18/28.54038/77.23588&layers=TN
![](https://i.imgur.com/IWqjwEw.png)

**Comment by PaulStets** [comment]
@contrapunctus-1 In both cases the transport routes were added less than a month ago: https://www.openstreetmap.org/relation/7964848 and https://www.openstreetmap.org/relation/6633896 for example. Please note that the transport changes are integrated into OsmAnd with the monthly map update. The next map update will be available in a few days. Please update the map and check that all the information is present. If it's still missing, feel free to re-open the issue.

**Comment by contrapunctus-1** [comment]
@PaulStets can the PT data be updated more frequently than monthly? It's not a dealbreaker or anything, but as someone who works on PT (nearly every day) it'd be nice to see the changes being useful sooner.

**Comment by PaulStets** [comment]
@contrapunctus-1 Unfortunately, this is not possible at the moment. In the future, we will try to add the transport data to the OsmAnd Live hourly map updates.
