### ISSUE TITLE
crash after installed all europe map

### ISSUE THREAD

**Issue by huitre39** [osmandapp/Osmand#5079]
Hello, use last stable version 2.9 of osmand.
I installed all europe map (40gb) but when i want to create a travel from paris to berlin osmand crash immediately and app exit.

i have samsung galaxy S7

**Comment by 3mg4** [comment]
Set waypoints on the route. 
See  [here](https://osmand.net/help/faq.html#long_route) and [here(Scroll to Navigation)](https://osmand.net/features?id=navigation)

**Comment by vshcherb** [comment]
That might be very long route that OsmAnd could handle. Approximate 300-500 km routes should work
