### ISSUE TITLE
[iPhone] Crash while calculating route

### ISSUE THREAD

**Issue by 3mg4** [osmandapp/Osmand#5080]
iPhone 6 64GB
iOS 10.3.3
OSMAnd for iPhone Version 2.0.1

When trying to calculate a route app crashes.
Example route is Vienna to Salzburg (AUSTRIA), it is longer than 250km, there is no way to route with Waypoints (like Start-Waypoint 1-Waypoint 2-Finish) I can enter Start and Finish but no waypoint in between.

_[Cheap workaround: Route from Start to Waypoint 1 than choose Waypoint 2 as destination from current position.]_

**Comment by hakuchi** [comment]
can you close this issue, because this is for Android.
If you use a iPhone, you shold report it in the iOS section: https://github.com/osmandapp/OsmAnd-ios/issues

**Comment by 3mg4** [comment]
Sorry, was not clear for me, since the official OSMAnd Website refers to this GitHub.
