### ISSUE TITLE
Strange routing at straight on junction - possibly affected by speed limits

### ISSUE THREAD

**Issue by martenjj** [osmandapp/Osmand#5082]
In the routing example below, the obvious way is just to go straight on:

![osmand-staines-road-routing-issuexxx](https://user-images.githubusercontent.com/10631760/36788638-9b7b7f14-1c86-11e8-95ff-86866768b548.png)

Enlarged, the junction looks like (with OSM way numbers):

![osmand-staines-road-routing-2-issuexxx](https://user-images.githubusercontent.com/10631760/36789004-0274a2a8-1c88-11e8-8d07-13531c208ddc.png)

The instructions given, though, say to turn right at the junction (onto 346593128), then immediately left (onto 346593127), then immediately right again (onto 492835187).

All the OSM map data seems to be reasonable.  The straight on ways 391333230 - 95468789 - 492835187 all have maxspeed=40mph, but 346593128 and 346593127 have no maxspeed.  There are no turn restriction relations at the junction.

Is it possible that the routing decides that taking the detour is better than following 95468789 because they have a higher (by default) speed limit?  This may be so, but for such a short stretch of faster road the turn penalties should count for more.

I have edited OSM to add maxspeed=40mph on 346593128 and 346593127, and also added an only_straight_on restriction where they cross.  I will check this issue again when the OsmAnd+ maps have been updated.

OsmAnd+ version = 2.9.3
Internal routing
Routing profile = Car, fastest
Driving region = Automatic (Should resolve to UK)
Starting point = 51.42055,-0.42904 on OSM way 391333230
Destination point = 51.41991,-0.42429 on OSM way 492835187
Offline map data file = United Kingdom England, 1 Feb 2018

**Comment by martenjj** [comment]
No longer appears to be an issue with 1 May 2018 data file (with maxspeed set on crossing ways).  Directions give straight on at junction.

**Comment by vshcherb** [comment]
Thanks.
