### ISSUE TITLE
The space is not cleared after the map update

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#5084]
Steps to reproduce:

1) Check how much free space you have ob the device.
2) Start updating any map in OsmAnd.
3) The free space will be decreasing during the download but will not go back after the map is updated.
4) Force-stop OsmAnd after the successful update and the space will be released.

**Comment by scaidermern** [comment]
Duplicate of #3108?

**Comment by vshcherb** [comment]
Yes it is duplicate
