### ISSUE TITLE
Routing: Better roads should be preferred

### ISSUE THREAD

**Issue by jkufner** [osmandapp/Osmand#5085]
Osmand likes to navigate through some really bad roads even when there is much better alternative of similar length available.

## Example:

(Screenshots are not taken from Osmand.)

Bad: As planned by Osmand (no waypoint set in Osmand). https://mapy.cz/zakladni?planovani-trasy&x=15.4178410&y=49.0926793&z=12&rc=9iztYxTowd1z8xTUE89i55KxSmyr&rs=ward&rs=coor&rs=ward&ri=14696&ri=&ri=10007&mrp=%7B%22c%22%3A111%7D&mrp=%7B%22c%22%3A111%7D&mrp=%7B%22c%22%3A111%7D&rt=&rt=&rt=
![screenshot_20180228_222108](https://user-images.githubusercontent.com/16572/36813725-cf18d6a6-1cd5-11e8-9818-b3b990c26925.png)

Good: https://mapy.cz/zakladni?planovani-trasy&x=15.4070505&y=49.0966578&z=11&rc=9iztYxTowd9i55KxSmyr&rs=ward&rs=ward&ri=14696&ri=10007&mrp=%7B%22c%22%3A111%7D&mrp=%7B%22c%22%3A111%7D&rt=&rt=
![screenshot_20180228_222146](https://user-images.githubusercontent.com/16572/36813732-d28ac128-1cd5-11e8-9911-b7ece92a54a4.png)

Osmand planned the route via low quality road, where we are theoretically allowed to go 90km/h, but practically it is not possible to do more than 50km/h. This particular road is 3m wide, not maintained in winter, and currently under solid layer of ice running through a dark forest. An unforgettable driving experience.

## Proposal

Let Osmand prefer roads of higher class and use only first and second class roads (yellow and orange on the linked map), then use the third class roads only to achieve the destination.

Use of the better roads would result in much faster long-distance routing since it would have to consider much smaller number of roads. Also, driving experience would be much better.

**Comment by naoliv** [comment]
Isn't it fixable by simply updating the data in OSM to reflect the road characteristics? `maxspeed`, `highway`, `surface`, etc

**Comment by scaidermern** [comment]
> Isn't it fixable by simply updating the data in OSM to reflect the road characteristics? maxspeed, highway, surface, etc

Yes. But please don't abuse the `maxpseed` tag. This should always represent the *legal* speed limit.

> where we are theoretically allowed to go 90km/h, but practically it is not possible to do more than 50km/h

For this case please use `maxspeed:practical`.

**Comment by StenSoft** [comment]
There are already weights based on road type, maybe these need to be skewed a bit

**Comment by matoromoto** [comment]
Rember some might be happy with the road chosen (eg. as it avoids driving through a city). Maybe opening options to play with the weights could help ?
