### ISSUE TITLE
Wrong announcement at roundabout

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#5090]
Usually, voice navigation names the number of roundabout exit. For example: take exit 2.

But sometimes, it just says "turn right". Example is this one https://www.openstreetmap.org/#map=18/38.75871/-9.20208

![osmand2 9 3-rotunda benfica-wide_20180301](https://user-images.githubusercontent.com/12711814/36899548-3f0ce3c8-1e28-11e8-87e4-e6f25be3c19f.png)

Should users just open an OSM note about tags or is it something else?

**Comment by naoliv** [comment]
It's missing `junction=roundabout` at the roundabout ways :-)

**Comment by hakuchi** [comment]
~I think this is not a roundabout.~
The tag junction=roundabout is used only on road intersections where traffic on the roundabout has right of way.(source=OSM-Wiki)
~I think this is a [junction=circular](https://wiki.openstreetmap.org/wiki/Tag:junction%3Dcircular)~

around your example I can find 3 with no roundabout or circular tagging
https://www.openstreetmap.org/way/95596582  =>`junction=roundabout`
https://www.openstreetmap.org/way/95210478  =>`junction=roundabout`
https://www.openstreetmap.org/way/93673390  =>no view on Mapillary

Edit:
This are roundabouts. see Mapillary.
There all incoming traffic have to give way.

On these roundabouts are missing the `highway=traffic_signals` and `junction=roundabout` tags.

**Comment by PaulStets** [comment]
The issue is caused by the incorrect tagging, I left the OSM note in the place. @naoliv, @hakuchi Thank you very much for investigating.
