### ISSUE TITLE
Incorrect pedestrian routing [Add test]

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#5097]
The pedestrian routing ignores the road: https://www.openstreetmap.org/way/24419555.
The approximate route to reproduce the issue: https://www.openstreetmap.org/directions?engine=graphhopper_foot&route=47.73307%2C8.98741%3B47.73274%2C8.98600#map=19/47.73287/8.98670

Screenshot:
![photo5251368711259007206](https://user-images.githubusercontent.com/20681525/36945887-29fef5ac-1fbd-11e8-9714-2360bb84f176.jpg)

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-resources/commit/a01fdecbf9fb4dc1c62f13fd41aef3b8af9a2c36
