### ISSUE TITLE
Renaming a currently displayed GPX track prevents disabling it again

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#5101]
OsmAnd+ 2.9.3.

Steps to reproduce:

* Go to "My Places" -> "My Tracks" and select "Show on map" for a GPX track
* Rename this GPX track (from within "My Tracks")
* Now, "My Tracks" doesn't list this GPX track as being shown on the map. Yet the track still gets displayed on the map, even after restarting OsmAnd → The GPX track can't get disabled any more via "My Tracks". Activating and deactivating it again doesn't help, either. It remains visible on the map.

The only option is going to "Configure map" and disabling option "GPX track..." completely, i.e. disabling _all_ GPX tracks.

**Comment by scaidermern** [comment]
This is assigned to the 3.1 milestone although the current milestone is 3.5.

Please reassign.

**Comment by vshcherb** [comment]
Not reproducible any more

**Comment by scaidermern** [comment]
I can still reproduce this problem with OsmAnd 3.7.4.

**Comment by vshcherb** [comment]
> Now, "My Tracks" doesn't list this GPX track as being shown on the map. 
Listed after renaming, at least as I see in nightly build

**Comment by scaidermern** [comment]
Then there must have been some fix between the latest stable release and the nightly version. Let's see if this is resolved in the next release.

**Comment by scaidermern** [comment]
You are correct, this is already fixed in the current nightly. Thanks.
