### ISSUE TITLE
Add "tourism:information" to guideposts

### ISSUE THREAD

**Issue by pbb72** [osmandapp/Osmand#5104]
When selecting "Guidepost" from the "POI type" menu in the "Create POI" window, only the tag "information:guidepost" is added to the node.

This is not enough. Not according to the OSM wiki, but also not enough to make the guidepost show up on the map after uploading.

Please make sure the "tourism:information" tag is also added to the POI!

**Comment by pbb72** [comment]
Sorry, what does it mean that you closed the issue? You don't mention anything. The comment in the changeset (finding this requires that I know about Git, don't know if you should demand that from everyone posting issues), says "PARTIAL fix", leading me to conclude that the issue is not fully fixed. Analysing the code change, it doesn't seem to be a fix at all (though I am not familiar with the code).

**Comment by vshcherb** [comment]
I think in that case people are advised to use custom editing with tags, so the poi type is not editable any more.
