### ISSUE TITLE
Change preset in editor for "water_tap"

### ISSUE THREAD

**Issue by zayuim** [osmandapp/Osmand#5112]
The editing functionality appears to be using outdated/not recommended tags in its POI editor.

Adding a water tap in the POI editor results in the tag: man_made=water_tap. However in JOSM, this tag preset is amenity=water_point.

I think the editor should be changed to JOSM's tagging.

**Comment by xmd5a2** [comment]
Please read https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dwater_tap
man_made=water_tap is not the same as amenity=water_point
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dwater_point
