### ISSUE TITLE
Dark theme readability issue

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#5113]
@vshcherb Any objections if we brighten our secondary text color for the dark app theme by quite a few shades? I am currently out in the desert and find our current 'dark-gray on black' a little hard to read, both at day time in bright sunlight as well as at night when the screen is dimmed for power saving.

I am talking about the text color we use for  most of our 'small print', like e.g. all secondary text and the buttons on our new context menu, the distamce and time figures in our gpx track list, the axis labels on our elevation graphs, and the secondary information on the search results screen.

**Comment by vshcherb** [comment]
Please share screenshots / colors with @dmpr0 . I'm usually the last tester with colors especially night colors which need to be tested at night.

**Comment by sonora** [comment]
Ok!
@dmpr0
![screenshot_2018-03-11-16-54-42](https://user-images.githubusercontent.com/845735/37260183-620f2c2e-254d-11e8-9712-e1fd20959cf2.png)

![screenshot_2018-03-11-16-56-16](https://user-images.githubusercontent.com/845735/37260186-6b65f190-254d-11e8-9ec3-b17cc8872258.png)

**Comment by quax2712** [comment]
The elevation graphs axis and lines are darc black, background darc gray. No chance to read the values.
Please change text and axis color in darc mode. Thank you
Rainer

**Comment by vshcherb** [comment]
I think recently another request was opened by @sonora , so this one could be closed

**Comment by sonora** [comment]
Exactly, I think the solution should be what I state in #9125,
