### ISSUE TITLE
Confusing translated abbreviations for the days of the week

### ISSUE THREAD

**Issue by IgorEliezer** [osmandapp/Osmand#5115]
Hello,

I've been working on [Brazilian Portuguese translation](https://github.com/osmandapp/Osmand/commits?author=IgorEliezer) for a few months, but there's just only one thing that I haven't managed to edit: the abbreviations for the days of the week. Which are a bit confusing, as follows:

Days EN | Abbr EN | Abbr PT-BR
--------- | ----------|-------------
Sunday | Su | Do
Monday | Mo | **Se**
Tuesday | Tu | Te
Wednesday | We | **Qu**
Thursday | Th | **Qu**
Friday | Fr | **Se**
Saturday | Sa | Sá

Monday & Friday and Wednesday & Thursday use the same  abbreviation, as you can see in the `Opening hours` and other similar fields:

![screenshot_2018-03-09-18-37-31](https://user-images.githubusercontent.com/4673289/37231471-189f511a-23ca-11e8-8768-6c521de28587.png)

`Se-Se` in en_US is Monday-Friday. Well, not helpful.

I would like to change them myself. But, if I can't, I would like the abbreviations to be: `Dom`, `Seg`, `Ter`, `Qua`, `Qui`, `Sex` and `Sáb`.

Just in case the three-letter form is not possible, I have this (ugly) alternative: `Do`, `Sg`, `Te`, `Qa`, `Qi`, `Sx` and `Sa`. :)

Regards,

**Comment by StenSoft** [comment]
I don't know how OsmAnd gets short week day names but on Android, there's [DateFormatSymbols.getShortWeekdays()](https://developer.android.com/reference/java/text/DateFormatSymbols.html#getShortWeekdays()) that returns them, no custom translations needed.

**Comment by IgorEliezer** [comment]
Thanks @vshcherb. :+1:

**Comment by franco999** [comment]
@vshcherb, I have seen that in the `OsmAnd Nightly 3.0.0#20676d` contains a bad syntax for opening_hours when uploading data to OSM. [According to OSM](https://wiki.openstreetmap.org/wiki/Key:opening_hours#Syntax), the days of the week are only 2 letters long and OsmAnd adds 3 letters.

Video: [opening_hours.mp4.zip](https://github.com/osmandapp/Osmand/files/1919968/opening_hours.mp4.zip)

**Comment by vshcherb** [comment]
@franco999 Agree - bad fix from my side. Corrected - https://github.com/osmandapp/Osmand/commit/d553e2ae722e72400caba09e39f5bc21c8dc1176

**Comment by iriman** [comment]
Hi, could you please use one-letter abbreviations for Persian week days? Current three-letters aren't so familiar to our eyes, alao one-letters are unique.

sa ش
su ی
mo د
tu س
we چ
th پ
fr ج
