### ISSUE TITLE
Context menu for transport stop is different than for poi icon

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#5117]
OSMAND 2.9.0#20141d              Maps: Spain 1 March

Some bus stops do not show own relations but show relations of nearest bus stop.
For example: https://www.openstreetmap.org/node/2085813868#map=19/40.74137/-4.05071&layers=D
https://www.openstreetmap.org/node/2085312074#map=19/40.73829/-4.05943&layers=D
https://www.openstreetmap.org/node/1819050003

Other bus stops show some relations but not others.
For example: https://www.openstreetmap.org/node/2083801735#map=19/40.63312/-4.00431&layers=D
on this bus stop OSMAND do not shows https://www.openstreetmap.org/relation/4019950
https://www.openstreetmap.org/relation/2661112
https://www.openstreetmap.org/relation/2990869

**Comment by ADepic** [comment]
These are probably osm mapping problems. Hop on to OSM and make a few changes and fix these

**Comment by OpenSourceForEver** [comment]
It is not a OSM mapping problem because selecting these routes on OSMAND the problematic bus stops are shown properly as part of these routes.

**Comment by OpenSourceForEver** [comment]
![screenshot_2018-04-07-19-59-23-791_net osmand dev](https://user-images.githubusercontent.com/12786225/38460381-d99a455a-3ab8-11e8-8cdb-ed390ebf718e.png)
![screenshot_2018-04-07-20-00-43-614_net osmand dev](https://user-images.githubusercontent.com/12786225/38460382-e351a67e-3ab8-11e8-8a6a-e8417a18c090.png)
![screenshot_2018-04-07-20-02-51-762_net osmand dev](https://user-images.githubusercontent.com/12786225/38460383-f09c4c62-3ab8-11e8-8e10-bb382a5fc1f7.png)
![screenshot_2018-04-07-19-56-30-499_net osmand dev](https://user-images.githubusercontent.com/12786225/38460384-f6d8a7a6-3ab8-11e8-8868-de1a03874e21.png)

**Comment by OpenSourceForEver** [comment]
Photos 2 and 4 show OSMAND recognises these bus stops as part of the routes but photos 1 and 3 show OSMAND shows only routes of nearest bus stops

**Comment by OpenSourceForEver** [comment]
In addition, Osmand only shows one direction of subway lines. Example:

**Comment by xmd5a2** [comment]
Regarding bus routes: I can reproduce only absence of 684N at https://www.openstreetmap.org/node/2085813868#map=19/40.74193/-4.05091
This is not the same route as 684 (it has different set of platforms).

**Comment by OpenSourceForEver** [comment]
Hi xmd5a2. At https://www.openstreetmap.org/node/2085813868#map=19/40.74193/-4.05091 Osmand only shows nearby routes (screenshoot 1). This nearby routes are from https://www.openstreetmap.org/node/2085813867#map=19/40.74134/-4.05082&layers=D (screenshoot 2)

![screenshot_2018-05-18-01-39-28-823_net osmand dev 1](https://user-images.githubusercontent.com/12786225/40208998-26668760-5a3d-11e8-9a4d-f0b0318617d6.png)

![screenshot_2018-05-18-01-40-27-324_net osmand dev 1](https://user-images.githubusercontent.com/12786225/40209002-2e3d5fc2-5a3d-11e8-9d44-e0a90218df8b.png)

**Comment by OpenSourceForEver** [comment]
The same with https://www.openstreetmap.org/node/1819050003  Osmand shows nearby routes (the routes with same ref but the opposite direction). 
![screenshot_2018-05-18-01-55-20-464_net osmand dev 1](https://user-images.githubusercontent.com/12786225/40209347-e7f60044-5a3e-11e8-9ef8-c26e8e2d8db0.png)

![photo osm](https://user-images.githubusercontent.com/12786225/40209447-7b4bc7d4-5a3f-11e8-9004-99587350ebd2.jpg)

OSM shows 8 bus routes, osmand shows 4 routes and all of them are nearby routes

**Comment by OpenSourceForEver** [comment]
The same with https://www.openstreetmap.org/node/2083801735#map=19/40.63312/-4.00431&layers=D

Osmand only shows nearby routes 
![screenshot_2018-05-18-02-08-43-811_net osmand dev 1](https://user-images.githubusercontent.com/12786225/40209662-dd0568ee-5a40-11e8-9242-0d381a31f490.png)

OSM shows 10 bus routes on this bus stop
![nueva imagen de mapa de bits](https://user-images.githubusercontent.com/12786225/40209706-1c00fcca-5a41-11e8-85c8-461798ad5190.jpg)

**Comment by vshcherb** [comment]
<img width="394" alt="screen shot 2018-05-20 at 15 40 54" src="https://user-images.githubusercontent.com/1042025/40279515-3ca0b470-5c44-11e8-99e8-c2f78465afcc.png">
Clicking on the transport stop produces correct result.

**Comment by ADepic** [comment]
I have seen this too

**Comment by OpenSourceForEver** [comment]
The same problem with public transport station

**Comment by OpenSourceForEver** [comment]
@xmd5a2

Regarding bus routes: I can reproduce only absence of 684N at https://www.openstreetmap.org/node/2085813868#map=19/40.74193/-4.05091
This is not the same route as 684 (it has different set of platforms).

absence of 684N is due to the fact that OSMAND only recognize one variant per direction of a route with the same "ref" tag. 684 and 684N are members of the same route_master

**Comment by OpenSourceForEver** [comment]
Thank you @crimean  but the problem is not solved at all. The problem still persists on bus stops that are very close to each other. Examples: 
https://www.openstreetmap.org/node/3183924699
https://www.openstreetmap.org/node/3183924698#map=19/40.72390/-4.02068&layers=D
(bus routes are different on OSM but OSMAND shows the same bus routes)


https://www.openstreetmap.org/node/1819050003#map=19/40.73075/-4.01003&layers=D 
https://www.openstreetmap.org/node/2085813874
(bus routes are different on OSM but OSMAND shows the same bus routes)

https://www.openstreetmap.org/node/3185537348
https://www.openstreetmap.org/node/3181917727
(bus routes are different on OSM but OSMAND shows the same bus routes)


https://www.openstreetmap.org/node/2083801735
https://www.openstreetmap.org/node/3894466790
(bus routes are different on OSM but OSMAND shows the same bus routes)

These are some examples but the problem is on all bus stops that are very close to each other.

**Comment by crimean** [comment]
Sorry for incomplete fix. Please check it now.

**Comment by OpenSourceForEver** [comment]
It is fixed thank you very much, although...

> @xmd5a2

Regarding bus routes: I can reproduce only absence of 684N at https://www.openstreetmap.org/node/2085813868#map=19/40.74193/-4.05091
This is not the same route as 684 (it has different set of platforms).

absence of 684N is due to the fact that OSMAND only recognize one variant per direction of a route with the same "ref" tag. 684 and 684N are members of the same route_master https://www.openstreetmap.org/relation/2684576
