### ISSUE TITLE
Can't upgrade from 2.8.2 to 2.9.3 on F-Droid.

### ISSUE THREAD

**Issue by OffifialMITX** [osmandapp/Osmand#5120]
All it says is "Installation failed due to an unknown error.".

**Comment by dmpr0** [comment]
We don't create this build, use Google Play or Amazon for updates.

**Comment by OffifialMITX** [comment]
Oh, sorry, didn't know.

On March 12, 2018 9:36:41 AM GMT+01:00, Dmitriy Prodchenko <notifications@github.com> wrote:
>We don't create this build, use Google Play or Amazon for updates.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/osmandapp/Osmand/issues/5120#issuecomment-372230078

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
