### ISSUE TITLE
Usability issue - Downloading regions

### ISSUE THREAD

**Issue by GinoPane** [osmandapp/Osmand#5121]
I think that OsmAnd is still pretty difficult to use for a simple user.

Let's consider a simple use case of downloading a required map of some city (for example, Paris). I don't want to download a full France map, so I need to determine a region to download (Ile-de-France in this case). 

Without world base map (which is not available by default) the user cannot navigate to required territory. And with base map downloaded the user need to go to the territory, put a marker there and press download in no-address-determined pop-up. 

Too many actions. And moreover, world base map is counted in free limit.

I think OsmAnd really needs a mapsme-like behaviour in this scenario. 

1.  World base map should be downloaded by default (and it **must** not be counted in free limit).
2. The application should give a direct prompt for downloading a region map when user navigates (searchs) to required region and zooms it to some level.

**Comment by littlehelper** [comment]
I agree, it is sometimes not obvious which map to download.
I have once proposed some ideas in #2663, #2664 which are also based on the idea to somehow automatically recommend a map for download.

**Comment by vshcherb** [comment]
1. World base map is not countable
2. The application gives help which region to download in the context menu of the place (after search of the city)
3. In configure Map / Dashboard app suggest to download region if it is not downloaded yet
4. The application allows to select regions on the base overview map (4-7 zoom)
5. Search by city supported in the Download Maps Screen.

**Comment by GinoPane** [comment]
@vshcherb 

> World base map is not countable

But UI says nothing about it.
