### ISSUE TITLE
repeated voice warnings

### ISSUE THREAD

**Issue by tobydickenson** [osmandapp/Osmand#5130]
Osmand has a voice warning for traffic calming features.

Very often a road will have multiple traffic calming features along its length. Right now Osmand gives the same voice warning for each one. The effect seems like the voice warning gets stuck, repeating the same phrase continuously.

"caution traffic calming caution traffic calming caution traffic calming caution traffic calming caution traffic calming caution traffic calming caution traffic calming caution traffic calming caution traffic calming caution traffic calming caution traffic calming"

I suggest suppressing voice warnings if they are a duplicate of an already spoken warning within the last minute, or from the same way, etc.

**Comment by vshcherb** [comment]
This could be a generic issue and you can always disable it. Please share location so we can understand if it is possible to do something else. Usually there are 2 approaches reduce the sound make a beer or say 3-4 traffic calming in advance

**Comment by tobydickenson** [comment]
I observe this problem heading west on Yew Tree Drive

https://www.openstreetmap.org/#map=18/50.88167/-1.25757

**Comment by vshcherb** [comment]
https://www.openstreetmap.org/way/344112644
https://www.openstreetmap.org/node/3814567004#map=19/50.88271/-1.26084
https://www.openstreetmap.org/node/3814567003#map=19/50.88268/-1.26077
https://www.openstreetmap.org/node/3508700484#map=19/50.88238/-1.25999
https://www.openstreetmap.org/node/3814567484#map=19/50.88210/-1.25922

Quite a lot!!!
