### ISSUE TITLE
Incorrect display for opening/closing time - tag value include comments

### ISSUE THREAD

**Issue by iriman** [osmandapp/Osmand#5137]
Here:
https://osmand.net/go?lat=34.078213&lon=49.71333&z=21

there is a fitness_centre that value of its opening_hours tag is `09:00-12:00 "بانوان";15:00-21:00 "آقایان"`.
Comments are in Persian and it's RTL so it looks untidy. If English, it would be `09:00-12:00 "women";15:00-21:00 "men"`. Looks better.

This is how OsmAnd displays it:

![screenshot_20180318-200239 1](https://user-images.githubusercontent.com/8467903/37568438-577c76fc-2aea-11e8-98a2-9ca48d858a5d.jpg)

In English, it says:
Will close at 21:00 - women

Below in description area it says in green:
Mo-Su 09:00-12:00 - women; Mo-Su 15:00-21:00 - women

Under it (text in black), it is what I entered for tag value.

**Comment by max-klaus** [comment]
![Screenshot_1592647201](https://user-images.githubusercontent.com/53395422/85199140-f7a8fc00-b2f5-11ea-8389-d0f5fb5fbd34.png)
Fixed already
