### ISSUE TITLE
Color and thicknes of GPX track display in car mode broken

### ISSUE THREAD

**Issue by matoromoto** [osmandapp/Osmand#5138]
When selecting a GPX track for display you can also select color and thicknes. This works fine in the 'maps view', but when changing to car (or bycicle or pedestrian) the track display doesn't respect the selected color and thickness.

Some details i noticed : 

- When switching from maps view to pedestrian color and thickness stay, but when resizing the map color changes back to standard (red). Thickness stays. Changing back to maps view color stays red, but a resize of the map brings back the selected color.
- When switching from maps view to car color and thickness change to standard (red / thin). Resize of map doesn't change anything. I noticed yesterday that the color changed in car mode when i started moving, but the thickness stayed thin. Changing back to maps view color brings back the selected color and thickness. 
- When switching from maps view to bycicke color and thickness stay, but when resizing the map color and thickness change back to standard (red / thin). Changing back to maps view color stays red / thin , but a resize of the map brings back the selected color.

osmand+ 2.9.3 on Google Nexus 5 and Motorola Moto G

**Comment by dmpr0** [comment]
Hello, @matoromoto this is not a bug. Every map mode have own map settings, when you switch from pedestrian to car, it would be different settings.

**Comment by matoromoto** [comment]
I do not agree. The color and thickness settings for the .gpx track are NOT correctly reflected in car / bycicle / pedestrian mode even if i especially change it for that mode.
Or else : How would you change color / thickness other than 
- pick 'configure card' (Karte konfigurieren) from the menu
- select car mode on top
- Select GPX track
- Switch color and thickness on top
- select the track you want to view ?

the color and thickness you selected in the menu is NOT reflected on the map in car / bycicle / pedestrian mode, only in the 'maps' mode.

**Comment by matoromoto** [comment]
Yes and no.

AFTER changing the color thickness in the menu you need to deselect the track you want to view, view another track (or leave the menu with OK). Come back, select the track you want to view.
Initially still rendered with the false colors, but a resize of the map brings up what's selected in the settings.
So, still seems to be buggy to me, but at least there is a workaround
