### ISSUE TITLE
Weird rendering of OsmAnd online tiles

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#5139]
OsmAnd online tiles show weird rendering. Is it normal?

![1](https://user-images.githubusercontent.com/12711814/37602089-52befb9e-2b94-11e8-8323-d5c5426cd374.png)
![2](https://user-images.githubusercontent.com/12711814/37602090-52eba5a4-2b94-11e8-8a6e-42fc135a6559.png)

![3](https://user-images.githubusercontent.com/12711814/37602091-53713020-2b94-11e8-8cb2-b1976e2a64b6.png)
![4](https://user-images.githubusercontent.com/12711814/37602092-539a617a-2b94-11e8-8b21-c4cec98c1f7a.png)

**Comment by scaidermern** [comment]
The location from the last screenshots is here: https://osmand.net/go.html?lat=56.017213&lon=47.34333&z=21
This problem does not exist at openstreetmap.org: https://www.openstreetmap.org/#map=15/56.0204/47.3631
And the orange way from the screenshot hasn't been touched for a long time: https://www.openstreetmap.org/way/42980099
Also no other relevant changes in this area: https://simon04.dev.openstreetmap.org/whodidit/?zoom=14&lat=56.023&lon=47.35267&layers=BTT&age=6%20month

Failed database update?

**Comment by iriman** [comment]
same issue here:
https://osmand.net/go?lat=34.08616&lon=49.6894&z=20

look at roads around square.
