### ISSUE TITLE
Underscore issue in Favorites

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#5151]
When you create a Favorite containing the underscore character, like name it e.g. Italy_Rome,  (leave the default category assignment to group 'Favorites'), OsmAnd actually creates the favorite as just Italy, and puts it in a new category called Rome. Looks like we somehow mistreat the '_' as a name/group separator.

**Comment by vshcherb** [comment]
That was needed at 1 point for backward compatibility in OsmAnd 1.0 may be, before we started using type tag as category. So now it looks weird.
