### ISSUE TITLE
Malicious Trojan detected by Malware Bytes

### ISSUE THREAD

**Issue by RayVermilion** [osmandapp/Osmand#5156]
I am using the OsmAnd~ Version 2.9.3.

Just after the Downloading Malwarebytes and Eset do not find anything suspicious.
But after a few hours I get the warning from Malwarebytes that Android/Tojan.Svpeng.rn
was found at /data/app/net.osmand.plus-1/base.apk

I can reproduce this everytime I download the App and wait for just a few hours.
Same result with 2.8.2.

![screen1](https://user-images.githubusercontent.com/4073576/37802899-3615d066-2e24-11e8-9d36-d0ca311e6d94.jpg)
![screen2](https://user-images.githubusercontent.com/4073576/37802904-3b14a808-2e24-11e8-999a-5070a04de77c.jpg)

**Comment by stephan75** [comment]
What is the source of your apk file?

Google playstore? Fdroid? Other?

**Comment by RayVermilion** [comment]
Hey, 

I am very sorry, you are right.
The source is f-droid: https://f-droid.org/en/packages/net.osmand.plus/

Best regards

**Comment by vshcherb** [comment]
Good.
