### ISSUE TITLE
Rename Czech Republic to Czechia

### ISSUE THREAD

**Issue by a903user** [osmandapp/Osmand#5163]
Hello, could you rename the Czech Republic to Czechia. It is "new" official name of our country. Also at Google Maps we are Czechia.

http://unstats.un.org/unsd/geoinfo/geonames/

Thanks

**Comment by vshcherb** [comment]
Once it is renamed in OpenStreetMap the names will be slowly changed first on detailed map than on basemap.

**Comment by a903user** [comment]
I mean also in the list of countries, under the menu item "Download maps".

**Comment by aceman444** [comment]
Yeah, the country names in the Download maps are internal to OsmAnd and can't even be translated via the normal tools (weblate). They contain multiple errors or wrong translations. Some of the regions also aren't real country names, so can't be fetched from OSM database.
I'll open a new issue for that.

**Comment by vshcherb** [comment]
Region names are pulled regularly from OSM and stored in https://github.com/osmandapp/OsmAnd-misc/blob/master/osm-planet/osm-data/states_places.osm
https://github.com/osmandapp/OsmAnd-misc/tree/master/osm-planet/osm-data

**Comment by a903user** [comment]
Ok, can someone rename the Czech Republic to Czechia in the internal country names list? I do not know how to do it. Thanks

**Comment by xmd5a2** [comment]
Translations were updated from OSM. This relation was used: https://www.openstreetmap.org/relation/51684

**Comment by aceman444** [comment]
When will this be seen inside OsmAnd Download maps list? When is the regions.ocbf file on phone updated?

**Comment by xmd5a2** [comment]
It will be available next release or nightly version

**Comment by aceman444** [comment]
Thanks. I am fixing some translations in OSM data, but there are some problem strings in issue #5178, can you help there?
