### ISSUE TITLE
Security issue: Open GPS Data 

### ISSUE THREAD

**Issue by juanjgit** [osmandapp/Osmand#5169]
Osmand: 2.9.3
Android: 7.1.1

Doing a routine nmap on my home network, I found port 7000 was open in my android device. Doing a telnet shows NMEA debug data:

```$ telnet  xxx.xxx.xxx.xxx 7000
Trying xxx.xxx.xxx.xx...
Connected to xxx.xxx.xxx.xx.
Escape character is '^]'.

$PMTK010,001*2E

$PMTK010,002*2D
$GNGGA,235942.011,8960.0000,N,00000.0000,E,0,0,,137.0,M,13.0,M,,*56
$GPGSA,A,1,,,,,,,,,,,,,99.99,99.99,99.99*30
$GLGSA,A,1,,,,,,,,,,,,,99.99,99.99,99.99*2C
$GPGSV,1,1,0*49
$GLGSV,1,1,0*55
$GNRMC,235942.011,V,8960.0000,N,00000.0000,E,0.000,0.00,050180,,,N*58
$GNVTG,0.00,T,,M,0.000,N,0.000,K,N*2C
$GNACCURACY,3162.1*21
$GNGGA,235943.010,8960.0000,N,00000.0000,E,0,0,,137.0,M,13.0,M,,*56
$GPGSA,A,1,,,,,,,,,,,,,99.99,99.99,99.99*30
$GLGSA,A,1,,,,,,,,,,,,,99.99,99.99,99.99*2C
$GPGSV,1,1,0*49
$GLGSV,1,1,0*55
$GNRMC,235943.010,V,8960.0000,N,00000.0000,E,0.000,0.00,050180,,,N*58
$GNVTG,0.00,T,,M,0.000,N,0.000,K,N*2C
```

I noticed than that port opens when starting osmand. 

I found no debug settings that matches this behavior. It is a big security issue as it shows my GPS position when connected to public networks.

**Comment by vshcherb** [comment]
This is really strange. I don't know how it is related to OsmAnd though I might think it is related to Android API.

Most of GPS devices still work via network (sometimes via socket), this is an internal format of GPS device itself. OsmAnd doesn't receive this information in any form it might get it from Location API. 

Most likely it is related to incorrect implementation of Location API in Android driver, obviously it should not be exposed to public network but it should be visible to local application which got that permission.

**Comment by juanjgit** [comment]
I tried again but this time opening Google Maps. Same issue. So you are right, it is not related to Osmand but to Android API.
