### ISSUE TITLE
Charging Staions are not shown any more

### ISSUE THREAD

**Issue by MAlfare** [osmandapp/Osmand#5174]
Hi!

Osmand latest nightly on differtn Android versions
Since some time Charging Stations are not shown any more.
When I try to
Search->Categories->Custom Search/Service/Charging station
or
......./Transportation/ Charging station
there is "Nothing found within the radius:  xx km"

But there is at least one included in in OSM.
When I zoom to this place Configure map->POI overlay-> Nearest POI
I can see it as an orange circle without an icon in it (once it was a gas station with a plug).
Opening it shows (beside other data) "Osmand electricity combined charging"
(It is an AC-only station, no CCS)

The main problem is, that I make my own obf-files from POI-files (.gpx) from here:
https://www.goingelectric.de/stromtankstellen/poi/
gpx-files are converted by GPSBabel to .osm, then to obf by OsmAndMapCreator, latest available version.X
In osm-file a POI looks like this:

<node id='-3' visible='true' lat='51.3161810' lon='9.4596310'>
    <tag k='created_by' v='GPSBabel-1.5.2'/>
    <tag k='name' v='22kW Ladenetz in Kassel'/>
    <tag k='note' v='Stadthalle in 34119 Kassel - Friedrich-Ebert-Straße 160, 1 x Typ 2 22 kW, 1 x Typ 2 11 kW, 2 x Schuko, andere, Parkplätze 2, Je nach Anbieter und Tarif'/>
    <tag k='amenity' v='charging_station'/>
  </node>

And these files worked until some time ago.
I use German as language in Osmand and had to filter for Tansport/Ladestation (in Englisch: Transportation/Charging station)and all the stations where shown in the map.

There must have been done some changes, wherever i don't know, but seems have to do with the bold formates text above.

So a lot of questions:
What should stand in the tag above instead of "amenity" and "charging_station"
What category and type must I set in filter.
Where can i find a list of POI-names and corresponding icons?

What must somebody else do, to make this work again?

Regards
Manfred

**Comment by xmd5a2** [comment]
Not so long ago there were changes in OsmAnd regarding charging stations. They will be available again in next release (or nightly versions).

**Comment by MAlfare** [comment]
Sorry for missing "In osm-file a POI looks like this:"

> ```
> <node id='-13171' visible='true' lat='49.6430440' lon='8.5519670'>
>     <tag k='created_by' v='GPSBabel-1.5.2'/>
>     <tag k='name' v='22kW EnBW in Lorsch'/>
>     <tag k='note' v='Autobahnraststätte Lorsch West in 64653 Lorsch - A67, 1 x Typ 2 22 kW, 1 x CHAdeMO, 1 x CCS, andere, Parkplätze 2,'/>
>     <tag k='amenity v='charging_station'/>
>   </node>
> ```

**Comment by PaulStets** [comment]
@MAlfare Perhaps you have an outdated version of OsmAndMapCreator. Please try using this version: http://download.osmand.net/latest-night-build/OsmAndMapCreator-main.zip

Let me know if it solves it.

**Comment by MAlfare** [comment]
Hi Paul!
I have generated files yesterday, an I used, as always, the latest OsmAndMapCreator.
Files have date: So 01 Apr 2018 16∶59∶02 CEST

Is there a difference between the ones from first and second of April?

**Comment by PaulStets** [comment]
@MAlfare Could you please send your .osm file for a test?

**Comment by MAlfare** [comment]
Hi Paul!
Made a new one, with newest OsmAndMapCreator dated: Mo 02 Apr 2018 10∶28∶08 CEST.

File is converted from GPX to OSM by this part of the script:
`if [[ -f "$GE" ]]; then
   ICON='charging_station'	

	gpsbabel -w \
		-i gpx,suppresswhite=0,logpoint=0,humminbirdextensions=0,garminextensions=0 \
		-f "$GE" \
		-o osm,tag
Added .TXT to the fiel name, as .osm files are not allowed.

[GE.osm.TXT](https://github.com/osmandapp/Osmand/files/1867735/GE.osm.TXT)
nd=amenity:$ICON,created_by=GPSBabel \
		-F "$OSMDIR"/GE.osm
fi`

Added .TXT to the file name, as .osm files are not allowed.

[GE.osm.TXT](https://github.com/osmandapp/Osmand/files/1867735/GE.osm.TXT)

**Comment by MAlfare** [comment]
Sorry script part was corrupted, should read:
`# GoingElectric
look_for_GE
if [[ -f "$GE" ]]; then
   ICON='charging_station'	

	gpsbabel -w \
		-i gpx,suppresswhite=0,logpoint=0,humminbirdextensions=0,garminextensions=0 \
		-f "$GE" \
		-o osm,tagnd=amenity:$ICON,created_by=GPSBabel \
		-F "$OSMDIR"/GE.osm
fi`

**Comment by PaulStets** [comment]
@MAlfare I have tested your osm on the latest OsmAndMapCreator build + one of the latest nightlies.

Here are the results:
Search after adding the map
![photo_2018-04-02_12-58-05](https://user-images.githubusercontent.com/20681525/38192478-c3f2de0c-3675-11e8-96b2-b8199d05496c.jpg)
Map without the regular map
![photo_2018-04-02_12-58-16](https://user-images.githubusercontent.com/20681525/38192479-c415d7c2-3675-11e8-83e9-e50ce412343e.jpg)
Map + regular offline map
![photo_2018-04-02_12-58-23](https://user-images.githubusercontent.com/20681525/38192480-c433ad42-3675-11e8-8589-4bfe451900a0.jpg)

My suggestion is to perform a clean install of OsmAnd and try again. I'm also attaching the resulting obf:

[Ge.zip](https://github.com/osmandapp/Osmand/files/1867803/Ge.zip)

**Comment by MAlfare** [comment]
For different files with different stations I use "man_made:windmill", and "man_made:adit" in osm files, and I can find these expressions the corresponding obf files.
In case of "amenity:charging-stations" in osm, I find "transportation$osmand_electricity_combined_charging*"

**Comment by MAlfare** [comment]
Got your Ge.obf right now. It contains "amenity*charging_station" as expected.
My obf file is 5.5MB in size, yours is 14.9MB.
There must be a large difference in creating. As we used the same  OsmAndMapCreator, perhaps there where changes in the config file?
I use this since ever:
`# write_mapper_config_file()
# generate xml setup file
write_mapper_config_file() {
cat > "$POI" << EOF
<?xml version="1.0" encoding="utf-8"?>
<batch_process>
	<process_attributes
		mapZooms=""
		renderingTypesFile=""
		zoomWaySmoothness="2"
		osmDbDialect="sqlite"
		mapDbDialect="sqlite" />

	<process
		directory_for_osm_files="$OSMDIR"
		directory_for_index_files="$OBFDIR"
		directory_for_generation="./Work"
		skipExistingIndexesAt="$OBFDIR"
		indexPOI="true"
		indexRouting="false"
		indexMap="false"
		indexTransport="false"
		indexAddress="false">
	</process>
</batch_process> 
EOF
}`

**Comment by PaulStets** [comment]
@MAlfare Please try using /OsmAndMapCreator-main/inspector.sh generate-obf ```<path_to_obf>```

**Comment by MAlfare** [comment]
Sorry, I do not understand, what you want to tell me :-(
In the script I use, obf creation is done by:

`java \
	-Djava.util.logging.config.file=logging.properties \ is
	-Xms256M -Xmx2048M \
	-cp "./OsmAndMapCreator.jar:./lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.data.index.IndexBatchCreator "$POI" > "$LOG" 2>&1`

where $POI  is created as in my last messages stated.

**Comment by PaulStets** [comment]
Try using ```java -Djava.util.logging.config.file=logging.properties -Xms64M -Xmx512M -cp "./OsmAndMapCreator.jar:$DIR/lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.MainUtilities generate-obf $PATH_TO_OSM```

**Comment by MAlfare** [comment]
This gives an error. " Error: A JNI error has occurred..."
Sorry but there are a lot of things, I do not understand.
I think, I should forget about "amenity:charging_stations" and its icon, and use "man_made:lighthouse" to produce my POI files, which is working. And have to keep in mind, that there are real lighthouses with no charging possibilities.

**Comment by MAlfare** [comment]
Did some investigation.
The only differnce  between your and my obf file "./inspector.sh -vpoi" shows, is:

`Binary index Ge.obf version = 2 edition = Mon Apr 02 11:41:01 CEST 2018
1 Map data Ge - 9422298 bytes
	1.1 Map level minZoom = 15, maxZoom = 22, size = 3368672 bytes 
		Bounds (left top - right bottom) : 6.0378, 55.0192 NE - 17.067, 45.8336 NE
	1.2 Map level minZoom = 13, maxZoom = 14, size = 3368672 bytes 
		Bounds (left top - right bottom) : 6.0378, 55.0192 NE - 17.067, 45.8336 NE
	1.3 Map level minZoom = 12, maxZoom = 12, size = 2684861 bytes 
		Bounds (left top - right bottom) : 6.0378, 55.0192 NE - 17.067, 45.8336 NE
2 Routing data Ge - 4 bytes
	Bounds (left top - right bottom) : 180, -90 NE - -180, 90 NE
3 Address data Ge - 41 bytes
	3.1 Address part size=2 bytes
	3.3 Address part size=2 bytes
	3.2 Address part size=2 bytes
4 Poi data Ge - 5455619 bytes`

and
`Binary index ALT_GE-dachl-typ2cee.obf version = 2 edition = Mon Apr 02 11:22:48 CEST 2018
1 Poi data Ge - 5455619 bytes`

which explains the difference in size.

Two screenshots of the beginning of the obf-files:

![yous](https://user-images.githubusercontent.com/4406655/38200706-a524df14-3695-11e8-98b2-37706e767be4.png)
![mine](https://user-images.githubusercontent.com/4406655/38200707-a53f9d90-3695-11e8-9a38-381386d2362e.png)
