### ISSUE TITLE
Routing error: Corners cut short

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#5175]
Coordinates:
Start - 49.12014, 9.21233
End - 49.10080, 9.20425

Screenshot:
![screenshot nr 2](https://user-images.githubusercontent.com/20681525/38018872-d06ee4f0-327e-11e8-832b-26aa5c7b77bf.png)

**Comment by aceman444** [comment]
Isn't it just bad rendering of the route? Instead of a real routing error.

**Comment by vshcherb** [comment]
Nope it is a routing error i.e. routing data error. Obviously the data needs to be checked, likely it is related to Live data may be i.e. if the map data is updated but not routing data (or it is disabled in settings)

**Comment by PaulStets** [comment]
@vshcherb Nope. Tested it, it is the regular map.

**Comment by sonora** [comment]
Somehow this is not fixed  I'm afraid: I can still find occurrences where occasionally a corner is shortcut.

Good chance to reproduce: Select a building 100m into a dead end street as an interim destination. The route should be such that you come on the base street, turn left entering the dead end street, turn around near the interim, and leave the back end street turning left onto the base street again (continuing the original direction of travel). The overall shape traveled forms a 'T' with the back end being its stem.

The turn into the dead end street is ok, the turn back out will somtimes slightly cut the corner (about 20m) of the turn where the dead end street meets the base street.

**Comment by sonora** [comment]
Illustration: (Map does not matter, I can reproduce around the world)

![image](https://user-images.githubusercontent.com/845735/84367031-f419c480-abd3-11ea-96b7-bf785e9f3fdb.png)

**Comment by vshcherb** [comment]
This doesn't look as latest version, can't reproduce it.

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/84387171-de67c780-abf2-11ea-9c77-c2de6d92c6f6.png)
![image](https://user-images.githubusercontent.com/1042025/84387177-e0318b00-abf2-11ea-8abb-53ab11e2b78d.png)
I managed to reproduce it on very short distances - http://www.openstreetmap.org/#map=18/52.306133/4.868813

**Comment by sonora** [comment]
Yes, I think you fixed it this time round!  ; l)
