### ISSUE TITLE
Allow translation of country/region names in Download maps

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#5178]
The country names in the Download maps dialog of OsmAnd are internal to OsmAnd and can't be translated via the normal tools (Weblate). They contain multiple errors or wrong translations. See e.g. https://groups.google.com/forum/#!topic/osmand/KhY8B5ETzS0 .
Some of the regions also aren't real country names, so can't be fetched from OSM even if the OsmAnd devs wanted to do it themselves.

Please allow translation of the regions in OsmAnd map download. Put the existing translations on Weblated and allow translators to fix/update them.

Then also issues like #5163 wouldn't be needed.

**Comment by aceman444** [comment]
Some artificial region names can be fixed at https://github.com/osmandapp/OsmAnd-misc/tree/master/osm-planet/osm-data . Real country names are apparently synced from OSM data.

**Comment by aceman444** [comment]
What about region names like "Australia-oceania Oceania Micronesia" (hillshade map in Oceania region)? It seems these are some composed strings but do not use translations, just use English version.

**Comment by aceman444** [comment]
Spratly islands is in osm-data/queries/countries_places.txt, but the node 3027436882 is deleted in OSM. Can you update your syncing scripts to flag this situation and you then manually update the node ID ?

**Comment by aceman444** [comment]
Palestine is translated in OSM to my language, but not so in OsmAnd. The file countries_places.osm does contain the translation too. The same problem with Azores and Portugal.

**Comment by aceman444** [comment]
Thanks, I see my updates in OSM have been picked up in your patches. You did update something with Spratly islands, Micronesia (French polynesia), Palestine, Portugal.

It seems you missed Azores yet.

**Comment by aceman444** [comment]
The problem with Palestina may be that there are 2, one in countries_places.osm and one in countries_admin_level_2.osm which differ in available translations (one had name in my language, one didn't).

**Comment by aceman444** [comment]
OK, I'm done now in OSM data. Please check if Azores are defined OK in the countries-info/regions.xml file. Then please run the sync script again and I can close this issue. Thanks.

**Comment by aceman444** [comment]
Hi, can you again paste the links to the new commits?

**Comment by vshcherb** [comment]
@aceman444 @xmd5a2 do we need to update anything from OSM data?

**Comment by aceman444** [comment]
Yes please. xmd5a2 updated the files before I was done in OSM. Please update again from OSM data and we are done. Thanks.

**Comment by aceman444** [comment]
Please run the update so that this doesn't miss OsmAnd 3.0.

**Comment by xmd5a2** [comment]
@aceman444 done

**Comment by aceman444** [comment]
Thank you very much, the region files look good to me now!

**Comment by sonora** [comment]
Could this somehow be connected with #5404 ?

**Comment by juliannyca** [comment]
In this context I noticed, that many countries and subdivisions (such as all German states) in the Download list are not shown with their name in hsb (Upper Sorbian), although their OSM relations have names in that languages for many years. Others bear their hsb name (Irska, Finska, Islandska) correctly. Would it be possible to update the list for hsb?

**Comment by aceman444** [comment]
Sometimes it is necessary to also have those names not only on the relation but also on the node that has the 'label' role in the relation. The node has most of the tags duplicated from the relation and also represents the region.
