### ISSUE TITLE
Avoid toll roads causes strange navigation

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#5181]
Building a route with a starting point on a highway with enabled option to avoid toll roads causes strange navigation behavior (the route is calculated offroad).
Location:
https://www.openstreetmap.org/way/314641358#map=17/37.60634/-1.32523

Screenshot:
![photo5321560026042706197](https://user-images.githubusercontent.com/20681525/38037810-507661e0-32b2-11e8-9f30-48668eabaf4f.jpg)

**Comment by vshcherb** [comment]
This is correct behavior and this bug is likely duplicated.
