### ISSUE TITLE
Unable to calculate route from fixed Start to Finish

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [osmandapp/Osmand#5182]
If I try to calculate route from fixed start (green flag) and current position is available Osmand will ignore fixed start position and will calculate route from current position.

**Comment by vshcherb** [comment]
If you already hit the button "Go" then it will use only current location. You need to cancel route and then click "Directions" and change start point.

**Comment by c-e-p-x-u-o** [comment]
So you confirm this bug, but closed it?

**Comment by vshcherb** [comment]
This is not a bug, this is how it is designed to work. Following mode always starts from your location, preparation you could move start location
