### ISSUE TITLE
Wrong lane guidance in car navigation

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#5184]
Lane widget is showing left turn while the road is bending slightly to the right. Similar to #5126 , but in car mode.

Please see 52°12'32.876"N, 20°54'49.155"E.

![screenshot_2018-03-22-21-41-18-044_net osmand](https://user-images.githubusercontent.com/12711814/38091924-8ccf7632-336f-11e8-9762-c32f6f9602d6.png)

**Comment by vshcherb** [comment]
The data need to be checked but it is not necessarily wrong, in case lane guidance is different it could be always fixed on the map itself

**Comment by naoliv** [comment]
Probably it says to stay at the left lane because coming from https://www.openstreetmap.org/way/154492101 there is a way to the left (https://www.openstreetmap.org/way/220492713) and a way to the right (https://www.openstreetmap.org/way/4891038)

**Comment by vshcherb** [comment]
Slightly changed OSM data, so now it should be an intersection
