### ISSUE TITLE
speed camera warning

### ISSUE THREAD

**Issue by kallegit1950** [osmandapp/Osmand#5191]
Hi,

I am using OsmAnd+ 2.9.3, speed camera warnings appear only if the speed camera node is on the highway, but not in a relation. Basically exactly the bug https://github.com/osmandapp/Osmand/issues/2803 which was reported and solved some time ago. Can someone check?

**Comment by hakuchi** [comment]
do you have a link to the not working relation?

**Comment by kallegit1950** [comment]
Hi, 
not sure how to give a link to exactly that relation. If you take a look at https://www.openstreetmap.org/relation/163312#map=19/50.70006/6.60527&layers=N there is the relation and the speed camera. it doesn't render in OSM, but it shows in JOSM. Same with that second relation https://www.openstreetmap.org/relation/163312#map=18/50.70510/6.66796&layers=N and I probably can give more examples. If you have an example where it works for sure, then I could compare how it is mapped - though I think these two entries are mapped correctly.

Thanks.

**Comment by bitboy85** [comment]
Usually osmand gives the warning if you reach the from point. Sometimes it helps to recreate the relation. Maybe at this place the relation should have only one Name (The Point of the Speed camera is named Radrafalle). Sadly there is another issue. Osmand does not recognise the direction of a relation.

**Comment by kallegit1950** [comment]
I cannot see that the point has a name. Anyways, the second example doesn't have a name either and I can give more examples. Recreating the relation does sound odd, I know too many speed cameras where this feature is not working. Do you have a link to an example where you have verified on-site with OSMAND that it is working?

**Comment by bitboy85** [comment]
Here is a working one https://www.openstreetmap.org/edit#map=18/49.68830/6.23403 it is excatly mapped as your first example, i couldn't find a difference.
In your second example the relation has no maxspeed tag, maybe thats the reason.

**Comment by kallegit1950** [comment]
I found another relation, without maxspeed tag, that new relation is working fine. Very odd.

**Comment by bitboy85** [comment]
I remember that i had Troubles adding / editing Relations using the webeditor. I never found out if it was a browser issue or maybe the relation or the editor was broken in some way. Thats why i suggested just recreating it. Maybe you can recreate one and check after the next map update.

**Comment by vshcherb** [comment]
> From the bug which was fixed: Since OsmAnd shifted from 2.2 to 2.3, speed cameras mapped as off road nodes into an enforcement=speed_camera relation (classic three points role=from,device,to where the speed camera is "device") don't generate an alert any more. An icon, neither.

So as of today the cameras which are not located on the roads should have proper relation enforcement
