### ISSUE TITLE
Sport tag as a collapsible list

### ISSUE THREAD

**Issue by IgorEliezer** [osmandapp/Osmand#5192]
Enhancement: [sport](https://wiki.openstreetmap.org/wiki/Key:sport)={list} could be handled as a collapsible list to save space, pretty much like cuisine and acceptable waste (from amenity recycling).

![screenshot_2018-03-31-11-37-28](https://user-images.githubusercontent.com/4673289/38168021-c03d5684-3517-11e8-9b07-128cda8cf75d.png)
OSM: https://www.openstreetmap.org/way/534338060

**Comment by ADepic** [comment]
This has been added to the roadmap to be included in the Osmand 3.1 release. Once that is out this can be closed

**Comment by IgorEliezer** [comment]
Thank you!
