### ISSUE TITLE
Non-optimal route

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#5195]
OsmAnd calculates a unnecessarily long route. Instead of staying on the primary road it routes through a residential area:

![photo5909190978965712580](https://user-images.githubusercontent.com/1040784/38172317-9f08ec10-35aa-11e8-9581-d5b9cdeae4b2.jpg)

GPX: [route.gpx.txt](https://github.com/osmandapp/Osmand/files/1866265/route.gpx.txt)

Happens both in car and bicycle mode but not with foot routing. Happens with and without OsmAnd live.

This is the location: https://www.openstreetmap.org/#map=16/50.6855/11.3134

Does not happen with OSRM: https://www.openstreetmap.org/directions?engine=osrm_car&route=50.6837%2C11.3192%3B50.6847%2C11.3003#map=16/50.6851/11.3098
Does not happen with GraphHopper: https://www.openstreetmap.org/directions?engine=graphhopper_car&route=50.6837%2C11.3192%3B50.6847%2C11.3003

I can't find any error in the OSM data.

**Comment by Zahnstocher** [comment]
> I can't find any error in the OSM data.

Is the road really unpaved?
> surface=unpaved

https://www.openstreetmap.org/way/550292490

OsmAnd tries to avoid unpaved roads.

**Comment by scaidermern** [comment]
> Is the road really unpaved?

No, of course not. I missed that. Thanks!

I've corrected the surface tag.
