### ISSUE TITLE
Version 2.9.3 and download speed of the maps

### ISSUE THREAD

**Issue by bumbaras** [osmandapp/Osmand#5204]
Do OsmAnd app artifically limit the speed of map download? For example, do this app detect what kind of connection I have got and make downloads artifically faster or slower?
I have made an Usb Reverse Tethering on my device, made settings to give apps a hint that GSM cellular network connection is on, and everything works quite fast except ... OsmAnd. OsmAnd is downloading about 200MB very slow, compared to real WiFi connection.
And I wonder if this is some coincidence or just made as intended by developer ...

EDIT: and without spoofing that I have cellular data network OsmAnd can't download anything, even if I can browse net normally and it is really fast by USB.

**Comment by vshcherb** [comment]
Nope there is no limitation though the maximum speed could be 150 Megabytes / s or 1Gbps. There is no indication on server side that limit is reached
