### ISSUE TITLE
better show arrows for exit main-way

### ISSUE THREAD

**Issue by osmvermesser** [osmandapp/Osmand#5207]
hi!

when you drive from https://www.openstreetmap.org/node/1455670423 to https://www.openstreetmap.org/node/378922541 then you passed https://www.openstreetmap.org/node/25231341. there will Show 3 arrows straight.

on the ground there are no lanes to "right ..."  and osm did not mapped for the router.
![osmand_luft](https://user-images.githubusercontent.com/6803899/38351121-b3dfa200-389d-11e8-8436-a9da5f946aaa.png)

i think it would be important to make this situation better. offen i have this sitiuation even when there no lanes - then symbols like this will be better.
![osmand_arrow](https://user-images.githubusercontent.com/6803899/38351090-95d55e6c-389d-11e8-8c1c-b310b8bb9eb8.png)

in hope you understand.

Jan

**Comment by franco999** [comment]
I suppose you should use the "[turn:lanes](https://wiki.openstreetmap.org/wiki/Key:turn)" tag. For example: 
`turn:lanes=through|through;slight_right`

**Comment by osmvermesser** [comment]
but on the ground is not a parallel lane like in the discription of https://wiki.openstreetmap.org/wiki/Key:turn#Turning_indications_per_lane

Jan

**Comment by bitboy85** [comment]
From my observation, if there is no turn-tagging, osmand tries to "guess" the lanes and i think it uses the angle between the motorway and the Exit lane/way. If the angle is very small (compared to a threshold) osmand will detect this way as "straight" so you have 2 straight lanes from the motorway + 1 straight Exit lane, and thus it shows 3 straight arrows.
This behaviour or the treshold seems to have changed in the last version, i've seen places where the lane guidance was correct in older versions and is wrong in new versions.

The obvious problem you have if you use a threshold for an angle, somewhere on the world is a place where this angle is a bit too large or too small and it will be wrong at this Point so tweaking this value is no solution, but i'd say that old the handling in older versions was better.

So doing a turn:lane tagging is the only future proof solution even if there are no arrows on the road itself.

For example this is a place where lane guidance was correct in the past (turn slight right): https://www.openstreetmap.org/edit#map=20/49.58138/6.13071 and is wrong in new Version (straight) so i have added the turn lane at this place which seems to fix it.

**Comment by vshcherb** [comment]
> I suppose you should use the "turn:lanes" tag in https://www.openstreetmap.org/way/524289020. For example:
turn:lanes=through|through;slight_right

This would be a supported way in Navigation. It is harmless even though it is not written on the surface itself but there are multiple examples when it is on the official road signs etc.
