### ISSUE TITLE
"Select street in" option in the search does not work properly

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#5214]
Very often the "Select street in..." option is stuck in one specific city. Instead, it should suggest either the current location or the centered location.

 As an example, mine is stuck on Berlin even though the map is centered elsewhere.

**Comment by ADepic** [comment]
It is stuck on your previously chosen city / most commonly chosen city. I don't see this as a big problem because you can scroll down and there are the nearest cities ...

**Comment by scaidermern** [comment]
This is indeed a rather annoying and strange behavior. The expected behavior is to be able to choose the city. Pre-filling it with some sane value is good, not being able to change it is bad and feels broken.

**Comment by scaidermern** [comment]
That doesn't really work. It is only possible to select nearest cities in the list below. Selecting arbitrary cities is not possible, unfortunately.

**Comment by vshcherb** [comment]
@scaidermern Agree that could be improved
