### ISSUE TITLE
Help because of a problem to create a language

### ISSUE THREAD

**Issue by Chistrouff** [osmandapp/Osmand#5216]
Hello, I contacted you via your email address and I was kindly written here; this is what brings me to:
I would like to add a new language: the "Francique Rhénan" is a regional language of eastern France and neighboring German regions but also spoken by 2 million Brazilian (there she is called "Hunsrik").

I followed your instructions on the page (http://osmand.net/help-online?id=technical-articles#What_Languages) but a problem occurred indeed, the DataExtractionOsm project where the files "theswing_messages_ {language } .properties " is " not found "error 404 .. I also saw that on the site" hosted.weblate.org "you opened a" translator space ", can you tell me if it would be possible to add the 
"Francique Rhénan" to this space or to give me the information for the site where the error is posted. 
                
                        Thank you in advance

**Comment by sonora** [comment]
I have added a resource file for ISO639 code hrx (Hunsrik), the only related reference I could find.

I think this will make it available at https://hosted.weblate.org/projects/osmand/main/, you can start translate it there, and we can take it from there once there is sufficient to work with, ok?

**Comment by sonora** [comment]
https://hosted.weblate.org/projects/osmand/main/hrx/

**Comment by Chistrouff** [comment]
Thank you very much
