### ISSUE TITLE
No default "Logging interval"

### ISSUE THREAD

**Issue by Rolf558** [osmandapp/Osmand#5226]
Hi,

There is no option selected by default for "Logging interval" in the "Trip recording" plug-in.

![photo_2018-04-11_20-05-12](https://user-images.githubusercontent.com/23729466/38634728-b01df59c-3dc3-11e8-9031-eab7f7e80c92.jpg)

Found with OsmAnd+ 2.9.3.

**Comment by peteperil** [comment]
There is some free screen-space before the cancel button. Why not show the default preset for the current app profile there. It would take away any confusion.

**Comment by sonora** [comment]
As I said above, we do have reasonable default values, so the issue the user reports here is simply that the default value is not displayed on the settings screen before you have used that screen at least once to change a value. I think there may be more settings screens with that issue, but is is only a display issue, nothing functional. (I guess Victor's commit does not fix the issue originally reported?)

**Comment by vshcherb** [comment]
The value is now highlighted because it is in the list, we can't use the default value which is not in the settings list. So the reported issue is fixed actually

**Comment by sonora** [comment]
@vshcherb Well spotted! Can't believe I missed that, thanks!
