### ISSUE TITLE
Road section missing in OsmAnd night build (with OSMLive)

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#5253]
What version of OsmAnd are you using, on what device and Android/iOS version?
Samsung Galaxy S7 Edge, Android 7.0 running night build 3.0.0#24385m released 2018-04-14 with OSMLive, and Samsung Galaxy S5 Active, Android 6.0 running Play store version 2.9.3, released 2018-02-08 (no OSMLive)

Note:  I haven't done enough testing to determine if OSMLive is an actual factor or if it's just the night build.  Also haven't tested a newer night build yet, but will soon.

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?
Your offline maps

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.
USA Georgia, dated March 31, 2018

__*In case of wrong routing:*__

Tell us whether you have used OsmAnd's in-app offline routing, or any online routing provider like YOURS, OpenRouteService or OSRM.
OsmAnd in-app routing

What routing profile is chosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest)
Car

Please specify as exactly as possible the start and end point of your route by telling us city name and street name so that we can find it via in-app address search easily. Also, a permalink from openstreetmap.org can be helpful.
A section of Windy Hill Road, and service roads into and out of a shopping center, are "missing" in the night build version with OSMLive.  The road *is* present in the Play store version without OSMLive, and I've verified that the roads exist in OSM and haven't been touched in a long time.
https://www.openstreetmap.org/way/304036323
https://www.openstreetmap.org/way/304036321
https://www.openstreetmap.org/way/304036340
https://www.openstreetmap.org/way/304036341

S7 with night build:
![screenshot_20180418-103221](https://user-images.githubusercontent.com/11140831/38939969-1b3092b2-42f7-11e8-879a-221f4c25ef65.png)

S5 with Play store build:
![screenshot_2018-04-18-11-24-51](https://user-images.githubusercontent.com/11140831/38941828-6507c7f8-42fb-11e8-979f-7f4b884b586d.png)

Tell us your expected routing, and how OsmAnd routes, or add screenshots here.
A test route from https://www.openstreetmap.org/node/2984734735 to https://www.openstreetmap.org/node/67643904 on the night build avoids the section of road.  The same from/to points on the Play store build route through it correctly.

Routing with night build:
![screenshot_20180418-104622](https://user-images.githubusercontent.com/11140831/38941505-b028ef9c-42fa-11e8-9bd1-0d62509e2aa4.png)

Routing with Play store build:
![screenshot_2018-04-18-10-58-44](https://user-images.githubusercontent.com/11140831/38941985-ab8ca5c2-42fb-11e8-9661-863fb6839dba.png)

**Comment by jfburke3** [comment]
The section is still missing in today's published night build version 3.0.0#24444m (with Live still enabled)

**Comment by jfburke3** [comment]
Disabled OSMLive and let it removed updates, and now the road section shows up again.

**Comment by jfburke3** [comment]
This is still an issue in today's "night build" that was published around noon Eastern time.

**Comment by jfburke3** [comment]
Just FYI I'm finding other roads with sections missing, too.

**Comment by xmd5a2** [comment]
Not reproducible with april maps
![screenshot from 2018-05-03 14-52-54](https://user-images.githubusercontent.com/5829014/39575041-d01a30d4-4ee1-11e8-90b7-11c01133a745.png)

**Comment by jfburke3** [comment]
@xmd5a2 @vshcherb April maps for Georgia aren't available yet. How did you test this???

**Comment by jfburke3** [comment]
@xmd5a2 @vshcherb I've been thinking about this some, and I want to offer that saying to "update to the latest map" is not a valid solution.  My reason is because when you download the latest map build, you're starting with a fresh map that OSMLive hasn't adulterated yet, and it is OSMLive that is the problem.  Of course I can download the newest map, but at some point, the bug in OSMLive will introduce some change (maybe in the area I'm in, or maybe in some remote location where it won't be noticed) that makes some roads sections disappear.  This might not happen until late in the month, but then of course updating to a new map will "fix" the problem again--until OSMLive mangles a road again.

I would ask that you consider reopening this case and treat it as a real problem in OSMLive.

--jack

**Comment by vshcherb** [comment]
Agree the issue is not fixed but it is also not reproduced. 
The way was not changing since 1 year.
https://www.openstreetmap.org/way/304036323#map=19/33.90346/-84.48580
@xmd5a2  checked all the date for April based on April maps and it was not reproducible. 


The issue is closed not because we don't believe that there was a glitch. We just not able reproduce it so we think there was no issue with data. All data is still available for OsmAnd live: http://download.osmand.net/aosmc/us_georgia_northamerica/

Another reason that we've found an issue with March generated maps (not Osm Live).
