### ISSUE TITLE
GPS Wake-up not working on newer devices

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#5255]
I received reports that the manual trip recording does not capture any points while the device is asleep (screen is off). Investigating this, I could in deed find devices where his happens, as follows:
- Samsung stock Android 7.0 (cannot reproduce on Android 4.4 devices)
- all OsmAnd recording filters set to off
- OsmAnd has Location and Storage permission
- disabling Android's Power saving and ticking "Device Administrator" for OsmAnd makes no difference

Looks like the problem only exists for recording intervals >= 30 sec, i.e. where we turn off GPS between recording points. So the issue may be a problem with the execution of the background task in sleep mode or turning on the GPS in sleep mode. Not sure if related or identical with #4274.

Any ideas?

PS: The web is full of info and best practice code examples of how to obtain background GPS locations, especially in light of Android's changes in Android 8, but this issue here already exists in Android 7.

**Comment by sonora** [comment]
I borrowed one of those devices and tested as follows:
- On a long drive (2 hours), performed a manual trip recording (without navigation) with interval 30sec, put phone to sleep. (The setting 'Show currently recorded track' was ON).
- After arriving, I turned on the device's screen and looked at the track. It was not entirely empty, it actually showed 2 (!) recorded points somewhere in the middle of the trip.
- Then I hit 'Stop recording' and 'Save recorded track'. Turns out that the recorded track actually did contain points almost to the second with 5min spacing.
Looks to me like either we have an issue in our code or there is something preventing apps to receive location updates more frequently than every 5 minutes while a device is asleep?

**Comment by sonora** [comment]
Yes, thanks. But strangely, I have  never observed this on Android 4.4 devices, files recorded there have a pretty reliable 30 sec spacing of points as expected.

When I investigate 30 sec files recorded using Android 7, after saving they contain a rather rigid point spacing of 5 min (almost to the second), plus VERY occasional (maybe 2 or so per hour) extra points somwhere between these 5 minute spacings (without shifting the original 5 min pattern). May those were recorded when the device happened to be awaken from doze or sleep by some other accidental process.

Looks to me like some mechanism somehow rather reliably keeps the GPS from waking up any more frequent than every 5 minutes with the code and alarm mechanism we use.

**Comment by sonora** [comment]
PS: I have just verified that the same issue exists on an Android 6.0.1 device.

**Comment by vshcherb** [comment]
Most likely fixed with https://github.com/osmandapp/Osmand/commit/0158fa496eaa111bf0b8a9b57374460f2cc87524

**Comment by sonora** [comment]
Victor, that may solve it for Android O, cannot currently test. But the issue is reported and verified on Android 6 and 7 devices ...

**Comment by vshcherb** [comment]
I'm afraid this issue won't be fixed cause a proper solution provided by Google was introduced since Android 8.0 (Foreground service), all other solutions looks like hacking on different devices (especially Samsung) OS tries to optimize battery sometimes too much and unexpected.

**Comment by sonora** [comment]
Yes, that also concurs with my research. Looks like this worked perfectly for all Android 4.4.x and before, and your commit should have also fixed it for 8. But for 5-7 it is a mess, with different manufacturers allowing different degrees of tweaking power saving options. Unfortunately I cannot find a general solution. To make things worse, there seem at least some, potentially many, devices where even completely turning off all power saving does not get it to work. (:

**Comment by sonora** [comment]
Researched the issue, updated the implementation,  and implemented workaround, see #5632.
