### ISSUE TITLE
Which version of "CC-BY-ND-NC" covers the "UI Design and UX work"

### ISSUE THREAD

**Issue by strypey** [osmandapp/Osmand#5256]
I'm wondering exactly which CC license you mean when you say "CC-BY-ND-NC"? I guess that you mean [CC BY-NC-ND](https://creativecommons.org/licenses/by-nc-nd/4.0/), but guessing can be pretty risky when it comes to legal stuff. If that is the license you're referred to, which version are you using? Is it 4.0, the latest version, or an earlier version? If it is an earlier version, is it the "unported version", or a country-specific version? Whichever version it was licensed under, do you trust CC enough as stewards of those licenses to add an "or later" to that?

If not asking to be pedantic. Obviously, each license has very different legal implications for how people can and can't use your work, but the different versions of the licenses have different legal implications too. The difference between 4.0 and earlier versions is major, since that upgrade dropped the country-specific "ports", and drafted one set of CC licenses that apply worldwide. IANAL but I use 4.0 for my own CC-licensed work to make sure that I'm free and clear of all that country-specific stuff, and that I benefit from all the clarification of what clauses like NC, ND, and SA mean in practice.

BTW I guess I'm not the first to note that a [non-free CC license](https://github.com/osmandapp/Osmand/blob/master/LICENSE) seems an odd choice for the UI of a program whose code is a licensed under either GPL (equivalent to CC BY-SA) and or a non-copyleft license (equivalent to CC-BY). But I also guess you have your reasons, and that's not the point I opened this Issue to raise.

**Comment by vshcherb** [comment]
Corrected.

Yes the reasons are very simple, so the application won't be distributed as is commercially except the company that has copyright. 
The code  GPLv3 could be used in commercial application as is.

**Comment by strypey** [comment]
Thanks for clarifying. Just a minor niggle; the "CC-BY-ND-NC" text appears a couple more places further down in the license file. Be good to have all mentions of the license say the same thing. Also, the spaces around the license text; [ text ](link), stop it making a link in Markdown, was that intentional?  If not, a link can be made by removing the spaces; [text](link). Thanks for making a great free code app, and keep up the good work!
