### ISSUE TITLE
Routing prefers much longer way

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#5261]
Route: https://www.openstreetmap.org/directions?engine=osrm_car&route=32.47620%2C3.70050%3B32.82640%2C3.76340#map=11/32.6514/3.7178

Screenshot:
![image](https://user-images.githubusercontent.com/20681525/39052765-bfd6e162-44b5-11e8-9ced-1bf8c6cda766.png)

**Comment by naoliv** [comment]
It seems that the map you have installed in osmand is at least 2 months old.
For example, this way https://www.openstreetmap.org/way/418945434/history was changed to `unclassified` while your screenshot has it as `secondary`.

Maybe the routing issue was fixed within these 2 last months and most probably an updated map will simply fix this issue?

**Comment by PaulStets** [comment]
The screenshot was made using the latest map. The outdated data is on the basemap, which is not updated that often.

**Comment by xmd5a2** [comment]
Not reproducible with latest 2018.04.23 data
![screenshot from 2018-04-23 21-31-53](https://user-images.githubusercontent.com/5829014/39146022-341f4d2c-473e-11e8-9b0f-148ad48590c2.png)
