### ISSUE TITLE
Choose tts voice languaje after installation

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#5264]
Osmand has 11 pre-installed tts voice languajes but I think most users only needs 1, 2 or at most 3 languajes, so I think it would be better if user could select which tts voice languaje does he/she want

**Comment by vshcherb** [comment]
We have special mapping for each country what are default languages and also we check what is the system language. Asking too many question in the beginning could be disturbing.

**Comment by OpenSourceForEver** [comment]
Oh. I think not long ago Osmand didn't check system languaje. It is a good solution. Thanks.
