### ISSUE TITLE
Pedistrians Routing around pedistrian zones/places

### ISSUE THREAD

**Issue by rriemann** [osmandapp/Osmand#5272]
I have a routing problem with latest OSmand for Android, offline routing engine.

The place is in front of the train station "Gare du Nord" in Paris. I opened an OpenStreetmap Note and people responded it's a Osmand issue.

OSM Note: https://www.openstreetmap.org/user/rriemann/notes

Problem: Routing leads one time around the place. Maybe it respects one-way routes also for pedistrians.

Expected Solution: close to straight-line route for the given start and destination positions.

![image](https://user-images.githubusercontent.com/111932/39123572-83883a54-46f8-11e8-828a-576cf5cae267.png)

**Comment by scaidermern** [comment]
This is a problem in the map data. The pedestrian area https://www.openstreetmap.org/way/153999197 is not connected to all highway=living_street ways running through it.

**Comment by scaidermern** [comment]
I've added the missing connections. You can close this issue.

**Comment by sonora** [comment]
Thanks!

**Comment by therob84** [comment]
Hey. I did encounter the same problem already in a lot of public places at different locations. 

@sonoa: You would say it is always a map error? I would say: If this error exists that often, it could be also thought about a change in the way OSMAnd handles these situation (map correction would be of course the royal way).

I guess, public places have a certain tag, right? If a street is very close (e.g. less than 1m) to a place and no distinct obstacle is in between, OSMAnd should ignore the missing connection and route along this "virtual" gap. 

Could anybody imagine this proceeding (and thus re-open this issue?)

For comparison here my latest example of this error: Lorenzer Platz in Nuremberg (Nürnberg, Germany) has no connection to Nonnengasse ending there. (Can't post the screenshot in mobile version of github, can try later)

Cheers, Robert

**Comment by scaidermern** [comment]
> If a street is very close (e.g. less than 1m) to a place and no distinct obstacle is in between, OSMAnd should ignore the missing connection and route along this "virtual" gap.

This would be a questionable feature. Sure, 1m is pretty close but there might be some edge cases (e.g. inaccurate data) where this will lead to wrong routes. Don't try to automagically "correct" map data if it is unclear whether there is an actual problem. OSM has [error detection tools](https://wiki.openstreetmap.org/wiki/Quality_assurance#Error_detection_tools) for these cases.
