### ISSUE TITLE
[Feature suggestion] Drop down menu for Quick Action buttons

### ISSUE THREAD

**Issue by iriman** [osmandapp/Osmand#5280]
Quick action buttons act like a toggle button and this is so useful when we defined two items for the button.
In my opinion it's a good idea that we have an additional drop-down menu (in addition to toggle behavior) at the bottom of button when we have defined more items (>2) for it, for example the button "change map underlay" with 4 map sources.
![20180425_171918](https://user-images.githubusercontent.com/8467903/39247037-7792b128-48ad-11e8-9fbe-838c9a12bc42.jpg)

**Comment by vshcherb** [comment]
There is a show dialog option already
