### ISSUE TITLE
Maximum maxheight selection

### ISSUE THREAD

**Issue by trigpoint** [osmandapp/Osmand#5294]
The maximum maxheight option in the app is only 4m, that is rather low considering signed maximum heights of 4.7m are not uncommon.
Would higher limits be possible? 4.5 and 5m for example.

**Comment by peteperil** [comment]
Are the developers searching for a 'Killer Feature' and good 'selling point'? Like this person implies: https://github.com/osmandapp/Osmand/issues/1444?

I recently spoke to a truck driver who told me they need to be able to take the max weight and max height. I actually thought that this wan't possible, but just learned that the features already exist.

They would also need to take into account for local traffic regulation that will or will not allow them to pass through some roads often close to schools or going through narrow village streets. 

At the moment they really need to buy a specific GPS system that will support routing for trucks.

Oh yes. And the current values counting up by 0.5 meters will not make them happy. They really like to set accurate values. In practice it really comes down to a few centimeters to be able to pass or not to be able to pass through a tunnel. Increments of 10 cm would be much more pleasing.

**Comment by vshcherb** [comment]
Fixed with https://github.com/osmandapp/OsmAnd-resources/commit/5e230e4b3577e4a18fad16be83f991f0ce159dc8

**Comment by sonora** [comment]
@vshcherb Victor, I think you may have fat-fingered that commit? Truckers requested 10 cm granularity in the settings, but you simply added more (and probably useless :) ) 0.5 m values?

I could imagine we need the 10 cm increments everywhere between 3 and 5 meters, outside 0.5m is likely ok. Or maybe a text input field for this, or a combination selection input "m + cm" (similar to what some alarm clocks use to set the time).

**Comment by vshcherb** [comment]
Yeah granularity is something else needs to be implemented though let's see if we got another request. I was fixing this one:

> Would higher limits be possible? 4.5 and 5m for example.

**Comment by sonora** [comment]
Yeah, I know. :) Just wasn't sure if you had gone through people's subsequent feedback and suggestions, that's why I pointed it out. :)
