### ISSUE TITLE
Non i18n strings (Time related terms)

### ISSUE THREAD

**Issue by yarons** [osmandapp/Osmand#5300]
Hey guys!
This string and the 2 following are non-i18n, I need the placeholder for the actual time in order to translate correctly:
https://github.com/osmandapp/Osmand/blob/f3e344f879cf8b163c45347e38435b856512fbe6/OsmAnd/res/values/strings.xml#L1361

In Hebrew we say something like: Before %d hours, there's also a difference between an hour, 2 hours and 3+ hours and there are not enough cases to cover all that.
With minutes and seconds it's different and 2 plural forms are enough (1 minute, 2+ minutes and 1 second, 2+ seconds).

Kind regards,
Yaron.

**Comment by yarons** [comment]
I can't find it in the code, even the word "ago" only appears in the strings XML.

Can these be simply eliminated?

**Comment by yarons** [comment]
Any progress on that?
Translation is 99%.

**Comment by yarons** [comment]
Also happens in Telegram, should I open an additional bug?

**Comment by vshcherb** [comment]
Is there any form like '%% hour(s) ago' ? We are not pretending to support all forms in translation, in russian there are different forms for 5-9, 10,  11, 12-15 though there are forms which are either short or accepted in the UI text

**Comment by yarons** [comment]
It's actually much simpler, In English: %% ago, in Hebrew (Transliteration): Lifney %%.
It's only a matter of the order of words, no special cases here (although there should be in a way, depending on the implementation).

**Comment by vshcherb** [comment]
@MadWasp79  please comment

**Comment by MadWasp79** [comment]
@yarons since none of these strings are used anywhere in the project we decided to remove them for now. In the future, if we will be adding similar time-related strings, we'll keep in mind all your suggestions about string's formatting to avoid such inconveniences with translation. Sorry to keep you waiting for so long!

**Comment by yarons** [comment]
Thank you! 😄
