### ISSUE TITLE
opening_hours="24/7 closed" interpreted as just 24/7

### ISSUE THREAD

**Issue by BalooUriza** [osmandapp/OsmAnd#5302]
What version of OsmAnd are you using, on what device and Android/iOS version?
Osmand~ 2.4.3 on Pixel XL, Android 8.1.0

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

Offline maps

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

Us_oklahoma_northamerica_2.obf.zip with Osmand Live enabled

Objects tagged with `opening_hours=24/7 closed` is interpreted as just 24/7, the exact opposite of what is expected.

**Comment by Codain** [comment]
I think that 24/7 is a kind of default value whenever the app can't parse the value, given that it shows 24/7 also for this node:
https://www.openstreetmap.org/node/5026052964

So even if those values are not valid (and should be retagged), the app should not sum up with 24/7  (which is nearly often wrong) but display the value content as it is.

**Comment by jfburke3** [comment]
I would argue that opening_hours=24/7 means that the place is open 24/7.  If it isn't, then the 24/7 should be *removed* from the tag, and *only* put closed.  It is common to say that a place is open 24/7, but you don't say that a place is "closed 24/7" -- you just say that it is closed.

**Comment by BalooUriza** [comment]
Most validators consider "24/7 closed" as valid, with "closed" modifier
applying to the timespan indicated prior.  So, for example, a bar that is
open all legal hours in Oregon, 7 days, could be indicated as "02:30-07:00
closed"

**Comment by scaidermern** [comment]
@jfburke3 Your argumentation is perfectly reasonable. However the opening_hours specification allows to use `24/7 closed` for indicating a permanently closed venue. Hence OsmAnd's behavior is a valid bug.

**Comment by vshcherb** [comment]
The bug is valid if we follow specification point to point. Unfortunately, I'm not sure if OsmAnd will be ever able to implement that unnecessary complex specification. If it is possible to specify the value that works in all programs it is better to do it. 
P.S. It is not about "24/7 closed" it is about all possible corner cases.

**Comment by Codain** [comment]
@vshcherb, is it possible to just display the rought value instead of 24/7 whenever a value is invalid or too complexe for the parser? It would solve the original issue of this thread and the one I added in one of my comment (which I did not fix in order for you to have a use case to test on).
