### ISSUE TITLE
Gpx route and lanes

### ISSUE THREAD

**Issue by ghost** [osmandapp/Osmand#5304]
Lanes arrows not working properly and stays always gray when using prepared GPX route . Is there any plans to fix this issue? This feature is very useful.

![picture](https://cdn.pbrd.co/images/HiY3hCy.png)

**Comment by scaidermern** [comment]
Related to #3908

**Comment by vshcherb** [comment]
Now at least lanes are exported for GPX routes created by OsmAnd
