### ISSUE TITLE
[Map markers] Too much space between title and items

### ISSUE THREAD

**Issue by franco999** [osmandapp/Osmand#5307]
App version: 3.0.0#20867d
System version: LineageOS 14.1 (Android 7.1.2)

![h](https://user-images.githubusercontent.com/12088580/39430672-ce9d1d22-4c64-11e8-9a28-6cb081d3618b.jpg)

**Comment by Chumva** [comment]
fixed with https://github.com/osmandapp/Osmand/commit/5473df3e429eeb6fdc6989a2a3afefd02b836765
