### ISSUE TITLE
Zoom animation is jerky while driving

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#5310]
If you are in driving mode and sync with location is enabled, also animation to smooth the movent is enabled, clicking zoom in & zoom out causes animation become jerky.

**Comment by ADepic** [comment]
I have seen a fix to this is by randomly changing from direction of map, zooming out and in fast and then recentering. 

Sometimes that fixes the issue, but the jerky animation shouldn't exist in the first place
