### ISSUE TITLE
display of calculated route is a straight line, instead of following the street. 

### ISSUE THREAD

**Issue by sisi-8** [osmandapp/Osmand#5316]
When navigation is on, the route is displayed just fine. However if you zoom out, at a certain level, the route becomes a straight line towards the destination. On a Android 7 system, with Osmand nightly of 2018-03-22

**Comment by PaulStets** [comment]
@sisi-8 Could you please attach a screenshot of the issue?

**Comment by dmromanov** [comment]
Might be the same issue #5437

**Comment by vshcherb** [comment]
Yes duplicate
