### ISSUE TITLE
Water disappears near Helgoland

### ISSUE THREAD

**Issue by sisi-8** [osmandapp/OsmAnd#5317]
Using the fine nautical view with the new display of nautical pois is so cool! However in some zoom levels the island becomes see (most of it is not displayed) and in others the see becomes land. Version is Osmand nightly of 2018-03-22, on a android 7 device.

**Comment by xmd5a2** [comment]
Issue is not related to nautical style
![screenshot_2018-06-04-17-34-28](https://user-images.githubusercontent.com/5829014/40923581-d2299efa-681d-11e8-924c-7553490e0ff1.png)
http://www.openstreetmap.org/?lat=54.1838458986544&lon=7.90945722587286&mlat=54.1838458986544&mlon=7.90945722587286&zoom=14
