### ISSUE TITLE
Wikipedia articles missing

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#5329]
Wiki articles in French are missing from the territory of France.

Steps:
1. Download any region of France (tested on Occitanie and Ile-de-France) and Wiki for that region.

2. Turn display language to French.

3. Go to POI - Wikipedia Francais.

No results for Occitanie, 1 result for Paris.
![screenshot_2018-05-02-18-46-56-915_net osmand dev](https://user-images.githubusercontent.com/12711814/39534274-ea89e610-4e39-11e8-8ca7-a55083193909.png)

**Comment by alyonapinchuk** [comment]
The same issue is with the Italian language.

**Comment by vshcherb** [comment]
Fixed with new wikipedia
