### ISSUE TITLE
Booderee national park not visible

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#5330]
National park is not visible and even doesn't have border name!
Compare 
https://www.openstreetmap.org/relation/6053102#map=11/-35.0292/150.7117 (less important from tourist perspictive)

https://www.openstreetmap.org/relation/4447256#map=14/-35.1188/150.6706 (very important)

Possibly it is a map issue.

**Comment by xmd5a2** [comment]
Not reproducible
![screenshot from 2018-05-04 10-15-51](https://user-images.githubusercontent.com/5829014/39616462-2421dcb6-4f84-11e8-804a-3cfb441bc04d.png)

**Comment by vshcherb** [comment]
I don't see Booderee on screenshot, it is wrong screenshot?
https://www.openstreetmap.org/relation/4447256#map=12/-35.1591/150.7086
<img width="510" alt="screen shot 2018-05-07 at 00 40 55" src="https://user-images.githubusercontent.com/1042025/39678567-4a7702bc-518f-11e8-98b7-6380307d5499.png">

**Comment by vshcherb** [comment]
On openstreetmap it also doesn't have NR polygon but at least it has the name
