### ISSUE TITLE
Car-Navigation using cycleway - not using Live-Updates

### ISSUE THREAD

**Issue by CJTmmr** [osmandapp/Osmand#5335]
Using OsmAnd-routing, nightlies.
Map: The Netherlands (April 2018) with Live Updates:
![2018-05-03 08 03 54](https://user-images.githubusercontent.com/15076257/39573712-9843560c-4ed4-11e8-8096-b4096722b373.png)

Making [this route](http://map.project-osrm.org/?z=18&center=52.162911%2C4.512650&loc=52.161458%2C4.513203&loc=52.162844%2C4.511406&hl=en&alt=0)
(Note Osrm-route is correct - already up-to-date)

This is the OsmAnd-route:
![2018-05-03 07 42 17](https://user-images.githubusercontent.com/15076257/39573801-f87ce5f6-4ed4-11e8-8336-9003b66f6e0f.png)
Still using [this cycleway with bollard](https://www.openstreetmap.org/way/584742693); 
it was changed from highway=residental to cycleway+bollard on April 30th.
Rendering of the changes is perfect!

On another location navigation is using Live-Updates correctly....:
Making [this route](http://map.project-osrm.org/?z=17&center=52.019045%2C4.644610&loc=52.019920%2C4.636391&loc=52.017100%2C4.641627&hl=en&alt=0) 
OsmAnd also uses the [new connection](https://www.openstreetmap.org/way/452640679), edited on April 29th 
![2018-05-03 13 36 05](https://user-images.githubusercontent.com/15076257/39574302-f4f8b3cc-4ed6-11e8-969d-2e8668c4c976.png)

**Comment by vshcherb** [comment]
Should be fixed now
