### ISSUE TITLE
Navigation-directions: Non-existing keep-right.

### ISSUE THREAD

**Issue by CJTmmr** [osmandapp/Osmand#5336]
Using OsmAnd Nightlies, Map The Netherlands (April 2018), with Live Updates.

Navigating [this route](http://map.project-osrm.org/?z=18&center=52.018205%2C4.716021&loc=52.018124%2C4.713183&loc=52.018332%2C4.717121&hl=en&alt=0)
OsmAnd displays a not-existing keep-right, (and showing two lanes forward; this piece is mapped with lanes=2, meaning 1 lane in each-direction, like [this wiki-example](https://wiki.openstreetmap.org/wiki/Key:lanes); first photo)

Both side-streets (to the right and to the left) are at an angle of about 90 degrees...
![2018-05-03 08 02 18](https://user-images.githubusercontent.com/15076257/39574874-e2225260-4ed8-11e8-9b88-f4c5e2d879c4.png)

**Comment by scaidermern** [comment]
The wrong turn instructions are a side effect of the wrong lane count already discussed at #5003.

**Comment by vshcherb** [comment]
Fixed with #5003
