### ISSUE TITLE
Travel Guide   Crash

### ISSUE THREAD

**Issue by CJTmmr** [osmandapp/Osmand#5337]
Using OsmAnd nightlies from the last days...
On Samsung Galaxy Camera 2, Android 4.3 JB

Trying to use New Travel-Guide section...:
![2018-05-03 14 10 48](https://user-images.githubusercontent.com/15076257/39575784-1092bce0-4edc-11e8-9ede-55370d464b40.png)

As soon as I press "Doorgaan" (continue in English?)  -->  crash.
See [this exception.log](https://www.dropbox.com/s/l1abze2gugh5uk7/exception%202018-05-03.log?dl=0)

I guess still work in progress, but a crash is no good.

**Comment by dmpr0** [comment]
Hi! Please try to update to the latest OsmAnd nightly, i think we already fix this.

**Comment by iriman** [comment]
I saw this too. But I renamed the travel folder and downloaded travel file again and then there was no problem.
