### ISSUE TITLE
Subway entrances displaying bus routes

### ISSUE THREAD

**Issue by contrapunctus-1** [osmandapp/Osmand#5343]
- OsmAnd v2.9.3 from F-Droid
- Nokia 6.1
- Android 8.1
- Offline maps, set to autoupdate hourly

Subway entrances, when tapped, are displaying nearby bus routes! 😄 No, it's almost certainly not a data issue, as these were never part of any bus route relation.

The node in these pictures is [this one.](https://www.openstreetmap.org/node/5511370878) The other subway entrances around it also display the same behavior.

![](https://i.imgur.com/Z2OeYwL.png)

![](https://i.imgur.com/NXwH7eJ.png)

**Comment by OpenSourceForEver** [comment]
Perhaps the solution would be to separate more clearly nearest routes from the stop routes. For example: routes: xxxx... Nearest routes:  yyyy (10m) zzzz (15m)....

**Comment by OpenSourceForEver** [comment]
Osmand only shows one direction of each subway line. Example: https://www.openstreetmap.org/node/5303173537

**Comment by Chumva** [comment]
fixed with https://github.com/osmandapp/Osmand/commit/6dd770c36c980f1728833ac06991cb5f5de62f9a

**Comment by OpenSourceForEver** [comment]
Osmand only shows one direction of each subway line. Example: https://www.openstreetmap.org/node/5303173537
