### ISSUE TITLE
Adjustable font size for Wkivoyage

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#5348]
I guess we need some sort of font size selector/scaler for our html screen. The new Wikivoyage screens looks ok on most devices, but the font size seems off for very small or very large screens. (Particularly on 4in it is rather  tiny).

**Comment by vshcherb** [comment]
That was in the original design though we still don't know how easy will it be to implement cause it is a WebView component.
Howerver...
https://stackoverflow.com/questions/3796176/how-to-change-the-fontsize-in-an-android-webview

**Comment by sonora** [comment]
Yes, concurs with my research: A manual bigger/smaller selector is probably the easiest and best.

**Comment by sonora** [comment]
Works great, thanks!
