### ISSUE TITLE
"\022" instead of bullet in What's New

### ISSUE THREAD

**Issue by IgorEliezer** [osmandapp/Osmand#5352]
The "What's New" window is printing raw "\022" instead of " •" in the 1st line:

![screenshot_2018-05-01-08-45-46](https://user-images.githubusercontent.com/4673289/39663109-697112e0-5043-11e8-971d-b266b5bea23f.png)

I tried to fix it on Weblate but the site won't let me add a blank space before the bullet icon. Perhaps that's why "\022" code is there but it was left uninterpreted.

**Comment by sonora** [comment]
You should either use `\u2022`, or `• `, I guess.

**Comment by IgorEliezer** [comment]
> You should either use \u2022, or •, I guess.

But the source text in English is _also_ using \022. Example: [release_2_6](https://hosted.weblate.org/translate/osmand/main/pt_BR/?checksum=2b3b01aefd7eb9f).

And I tried to reproduce the other lines of the bullet list which start with ` •`  (space+bullet), but Weblate complains I'm not allowed to put a space in the beginning of the 1st line.

**Comment by sonora** [comment]
What language file are you talking?  I thought I fixed it some hours ago for Brazilian Portuguese, but have not tested it.

**Comment by IgorEliezer** [comment]
> What language file are you talking?

Brazilian Portuguese, but since English strings also have "\022" I thought I was supposed to copy it to the translated strings expecting the app would convert it to •.

Based on your tip [here](https://github.com/osmandapp/Osmand/issues/5352#issuecomment-386805108), I used `\u0020\u2022` and the glitch is now fixed in the translation (just updated to nightly 20974d).

![screenshot_2018-05-05-18-50-31](https://user-images.githubusercontent.com/4673289/39667949-b869809a-5097-11e8-9601-06fd0bb2279e.png)

**Comment by sonora** [comment]
Ok, thanks for reporting and fixing!

Unicode 2022 is a bullet, hence equivalent to using the bullet character itself. Before my commit https://github.com/osmandapp/Osmand/commit/705f60620357ac2a7fb7ab74b11d8f4d8da89e67 the file may have tried to produce a quotation mark there (022), but then escaping that with 2 backslashes was faulty, I think. And yes, looks like that same issue exists in other language files, but likely little value in fixing old release notes before 2_9. Maybe I fix when I am back on a PC.

**Comment by IgorEliezer** [comment]
Oops, it seems that using `\u0020\u2022` no longer works.

![screenshot_2018-05-08-20-36-50](https://user-images.githubusercontent.com/4673289/39878535-03a3d6ae-544f-11e8-84d5-83a48db0c7ef.png)

I'm fixing back to using plain `•`.

Since Weblate hates the 1st character in the string is an empty space, I would suggest removing the empty space from before each bullet point, so that the items don't look misaligned.

**Comment by franco999** [comment]
duplicated https://github.com/osmandapp/Osmand/issues/4115

**Comment by sonora** [comment]
I agree, next release notes we should simply not use a blank before the bullet characters, easiest way to fix it.

There may be strings (other than release notes) which are concatenated by our code and hence may contain an initial or trailing space, have not researched. If this is an issue, it may deserve opening one in our issues list.

**Comment by aceman444** [comment]
I also see this in my translations. If the English version has the \022 then other languages will copy it. Please fix the English version, not propose using strange \u0020\u2022 characters, that are not in the English version. Also the other bullets in successive lines are shown as bullets in Weblate so the first one should be the same too. Why is there a space before each bullet?

**Comment by aceman444** [comment]
Issue #4115 isn't fixed either, dupe or not.

**Comment by sonora** [comment]
The English string is clean, and Weblate does also not show any escape sequences any more (in the source string display for release_3_0) . Looks like only the translations still need fixing?

**Comment by aceman444** [comment]
Yes, release_3_0 is OK on weblate, even thought the first line has no space before the bullet and the others have it. It still did display \022 when I updated OsmAnd to 3.0 yesterday. It may be the translation was not picked up as sadly the OsmAnd team does not announce the new versions and when translations are frozen or merged into a release. (E.g. when you translate strings now, it will never get into OsmAdn 3.x, only 3.1+)

So then only the older release notes need update of the English version. Or just need to be deleted if there is no use for them.

**Comment by sonora** [comment]
Definitely true that the old release strings should be removed, I had already done that yesterday.

Regarding "Merging": Please note that translations are permanently merged into the code, and will always become visible with the next minor release, e.g. 3.0.2 contains everything mended since 3.0.1, there is no "freeze".

**Comment by vshcherb** [comment]
There is a chance of 3.0.3 will be released next week or in a week but the changes need to be done carefully in r3.0 branch

**Comment by aceman444** [comment]
@sonora that would be great, but from my years-long observations, it never worked that way. Minor releases (X.Y.Z) never picked translations done between X.Y.0 and X.Y.Z. Only the next major version X.Y+1 picked them up. I mean translations done via Weblate.

**Comment by vshcherb** [comment]
Weblate translation won't be picked up unless they are manually moved to r3.0

**Comment by sonora** [comment]
Right, I overlooked we are building from a separate branch. That explains why more people still see this issue than is reflected in our master branch.

Victor, looking at our build log, it may also be about time to clean up the 'strings without default translation' again?
