### ISSUE TITLE
Move "Units of length" from "Global Settings" to "Navigation settings"

### ISSUE THREAD

**Issue by rmaryan** [osmandapp/Osmand#5353]
Is it possible to move "Units of length" from the "Global Settings" to "Navigation settings" and store it for each navigation profile separately? So it will work the same as "Unit of speed".

Thus for the "Boat" profile I can set up "Nautical miles", for the "Walking" mode - meters, and in the "Driving" mode use the "Driving region" settings.

This is not critical, but really a nice thing to have.

**Comment by vshcherb** [comment]
The settings were redesigned completely in 3.7
