### ISSUE TITLE
consider adding CONTRIBUTING.md file with build instructions

### ISSUE THREAD

**Issue by matkoniecz** [osmandapp/OsmAnd#5357]
I checked [FAQ](http://osmand.net/help-online) and there was no answer there.

I attempted to find build instructions and managed to discover

- https://github.com/osmandapp/OsmAnd-core#installation-on-ubuntu (for 14.04 LTS)
- http://osmand.net/help/TechnicalArticles.html#Install_Development_Environment that has different instructions
- https://code.google.com/archive/p/osmand/wikis/InstallDevelopmentEnvironment.wiki and https://code.google.com/archive/p/osmand/wikis/GradleCommandLineBuildEnvironment.wiki with yet another set of instructions

It is unclear which, if any, set of instructions is preferable to build Osmand app from source.

**Comment by vshcherb** [comment]
They are indeed outdated cause nowadays the process is very simple:
1. Checkout all projects https://github.com/osmandapp/OsmAnd-manifest/blob/master/android_build.xml
2. And run gradle OsmAnd:installFreedevLegacyArmv7Debug 
obviously as for normal Android development NDK, SDK should be properly set.

**Comment by EmmanuelMess** [comment]
It seems one needs to downgrade Gradle version to < 4.6 now. This can be done from `File > Project Structure... > Project`. 4.5 seems to work fine.

**Comment by EmmanuelMess** [comment]
I've noticed that there are some drawables missing that are making the compilation impossible, any suggestions?

See all of the drawables needed here (in TransportStopType):
```
	BUS(R.drawable.mx_route_bus_ref, R.drawable.mx_route_bus_ref, "routeBusColor", "route_bus_ref"),
	FERRY(R.drawable.mx_route_ferry_ref, R.drawable.mx_route_ferry_ref, "routeFerryColor", "route_ferry_ref"),
	FUNICULAR(R.drawable.mx_route_funicular_ref, R.drawable.mx_route_funicular_ref, "routeFunicularColor", "route_funicular_ref"),
	LIGHT_RAIL(R.drawable.mx_route_light_rail_ref, R.drawable.mx_route_light_rail_ref, "routeLightrailColor", "route_light_rail_ref"),
	MONORAIL(R.drawable.mx_route_monorail_ref, R.drawable.mx_route_monorail_ref, "routeLightrailColor", "route_monorail_ref"),
	RAILWAY(R.drawable.mx_route_railway_ref, R.drawable.mx_route_railway_ref, "routeTrainColor", "route_railway_ref"),
	SHARE_TAXI(R.drawable.mx_route_share_taxi_ref, R.drawable.mx_route_share_taxi_ref, "routeShareTaxiColor", "route_share_taxi_ref"),
	TRAIN(R.drawable.mx_route_train_ref, R.drawable.mx_route_train_ref, "routeTrainColor", "route_train_ref"),
	TRAM(R.drawable.mx_route_tram_ref, R.drawable.mx_railway_tram_stop, "routeTramColor", "route_tram_ref"),
	TROLLEYBUS(R.drawable.mx_route_trolleybus_ref, R.drawable.mx_route_trolleybus_ref, "routeTrolleybusColor", "route_trolleybus_ref"),
	SUBWAY(R.drawable.mx_subway_station, R.drawable.mx_subway_station, "routeTrainColor", "subway_station");
```
And a few more.

**Comment by krichter722** [comment]
Build instructions are more than just "nice" to have. They belong in `INSTALL(.md)` rather than `CONTRIBUTING` afaik and should be linked/mentioned in `README`.

**Comment by Bubu** [comment]
@vshcherb That still leaves open which NDK version you actually need. Is this documented somewhere?

**Comment by vshcherb** [comment]
currently we are using latest NDK 17b. Though previous release was done one 9d

**Comment by Bubu** [comment]
> currently we are using latest NDK 17b. 

@vshcherb Any update on this? Anywhere we (F-Droid) can follow the used ndk version per build?

**Comment by vshcherb** [comment]
@Bubu I added it here https://github.com/osmandapp/Osmand/blob/master/OsmAnd/build.gradle#L34

I would say gradle files became much cleaner and easier to configure from scratch though we still need to allocate time and update all documents

**Comment by bagage** [comment]
Since #9705 has been closed, please close this issue as well @vshcherb. Instructions are located in the [FAQ](https://osmand.net/help-online#dev-environment).

**Comment by vshcherb** [comment]
Though I'm not against that  contibuting.md could have link to website or to the file :-) Anyway thanks for contribution, PR was merged

**Comment by krichter722** [comment]
This issue is not resolved and instead ivory tower infrastructure is being created while actively block well known best practices.

**Comment by bgamari** [comment]
As someone who just spent several hours trying to work out how to build the application using the [limited documentation](https://docs.osmand.net/en/main@latest/development/build-osmand/how-to-compile-the-android-version) that exists, I would agree that this is not resolved.

**Comment by matkoniecz** [comment]
> As someone who just spent several hours trying to work out how to build the application using the limited documentation that exists, I would agree that this is not resolved.

If you will be more specific what was confusing and where you are stuck - there is chance for improving docs. (no matter their location)

**Comment by matkoniecz** [comment]
+

**Comment by matkoniecz** [comment]
-+
