### ISSUE TITLE
Start editing card bug - Travel

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#5359]
Device : g2
Brand : lge
Model : LG-D802
Product : g2_open_com
Build : KOT49I.D80220h
Version : 4.4.2
App Version : OsmAnd Nightly
Apk Version : 3.0.0#20987d 300
[exception (4).log](https://github.com/osmandapp/Osmand/files/1979578/exception.4.log)

**Comment by Chumva** [comment]
fixed with https://github.com/osmandapp/Osmand/commit/e75dfc58e84fc87576aceb7ceef00332464087ca
