### ISSUE TITLE
Calculate a route from GPX

### ISSUE THREAD

**Issue by Mannshoch** [osmandapp/Osmand#5361]
I wish to check the Route I have to drive in holyday with a prepared GPX file. Please allow to clculate a route with GPX and without a fixed location.

**Comment by scaidermern** [comment]
This is already possible. What are you missing?

**Comment by Mannshoch** [comment]
I was not able to do it.
If I open settings and add a GPX to the route I get a error because my Location is not available. And If I get a location I at first get only a Route from my location to the first waypoint and than a route to  the last. All other waypoints are ignored.

**Comment by scaidermern** [comment]
Can you attach your GPX file?

**Comment by njohnston** [comment]
Related to #3908 perhaps?

**Comment by vshcherb** [comment]
What you mentioned is already possible, you will miss some features available with Offline route calculation i.e. speed limits etc. #3908 is going to fix that issue
