### ISSUE TITLE
[Feature request] Show the names of graveyards

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#5364]
OsmAnd does not show the name on the map of the following elements: 
amenity = grave_yard 
landuse = cemetery.

It only shows the rendered image.

The request is to have the names shown.

**Comment by tazva** [comment]
I see cemetary names on mine.. Is the name tag in OSM set? It may not be. Can you include screenshots of what you mean, and the location of a cemetary in question?

**Comment by annasoloviova** [comment]
Unfortunately, this was a request from user who did not indicate location. But I tested on a random section of map in Marseilles. Looks like sometimes it shows the name and sometimes not (both cemeteries have names on the search list).
![screenshot_2018-05-11-15-48-52-920_net osmand plus](https://user-images.githubusercontent.com/12711814/39925476-84bf20fa-5534-11e8-8db8-7b4162efed36.png)
![screenshot_2018-05-11-15-49-54-733_net osmand plus](https://user-images.githubusercontent.com/12711814/39925478-84eb6f8e-5534-11e8-99e0-24e96782c9cb.png)
