### ISSUE TITLE
Wikivoyage - Internal Linking

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#5367]
Still some remaining issues with linking within the offline Wikivoyage file, example as follows:
- In the Wikivoyage search box type `Rome`
- Take the (first if device is in Emglish) search result called "Rome / Metropolitan Rome"
- It takes you to a disambiguation page saying "Roma - There is more than one place called Roma"
- On that page, tap on `Rome (Italy)` in the "Italy" paragraph
- This takes you back to the same disambiguation page, i.e. things are linked in a loop.

I guess that even "Metropolitan Rome" should not even put you on this disambiguation page?

BTW: All text with links in dark app theme is dark-blue-on-black, very hard to read outdoors. I guess bright blue text or something might work better.

**Comment by PaulStets** [comment]
Fixed with https://github.com/osmandapp/OsmAnd-tools/commit/a00cb1b15a509b54ef167fa0fd200f91c97c37e1

@sonora Thank you for noticing this. As for the link colors, could you please tell if use tried the latest nightly build? If yes, could you please specify the Android version on your device.

**Comment by sonora** [comment]
Paul, all observations above were for a build of 2018-05-08.

Regarding the "blue-on-black": This was on an Android 4.4.2, see screenshot attached. While it looks sort of ok on a PC indoors, the contrast was much worse on a mobile device outdoors. (Font size issue reported in #5348 and meanwhile fixed.)

<img width="135" alt="screenshot_2018-05-11-08-44-58_" src="https://user-images.githubusercontent.com/845735/39912336-b356f694-54fe-11e8-99e4-ecf81fb02f6e.png">

**Comment by sonora** [comment]
Regarding the linking: Yes it works now with the May 10 Wikivoyage file, thank you!

One thing that is annoying (any may actually deserve a separate issue) is this: From the Wikivoyage screen I had updated from the May 3 to the May 10 file. But after the update is finished, OsmAnd on that screen again notifies you to update to May 10. And the linking issue was still there, too, i.e. OsmAnd still used the old file. We either need to fix this, or force an app restart after the update so Wikivoyage starts using the new file, I guess.

**Comment by PaulStets** [comment]
@sonora Yes, please create an issue for this. It definitely should be fixed.

**Comment by sonora** [comment]
One more "linking" thing, but in the UI: When on a Wikivoyage page you tap on "Points", then on the GPX/Points tab you tap on any point, the map is centered ok on the point selected. But recently the map is in the background, now covered by the the Wikivoyage article which appears again in the foreground. Guess we should hide the article and show the map, so users do not miss this important feature.

**Comment by sonora** [comment]
Paul, another small issue : When you tap the top navigation line on a city's card, you get to a great navigation page starting from the current continent down to regions and cities. But I find no way there to change the continent, looks like we may need to display one more (root) level?

**Comment by PaulStets** [comment]
@sonora Regarding the visibility of the links, please download the latest nightly and see if it helps.
As for the points, there will be another screen for them in the future. It will fix this problem.
Finally, the navigation shows the regions the article belongs to. There is no way to determine all the continents there (except for hard-coding them manually). Frankly, I don't see why it would be convenient to display all the continents there, but you may ask **vshcherb**.
