### ISSUE TITLE
Unlimited parking to show the date parked

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#5374]
Selecting unlimited parking shows only the time car was parked. It would be better to also show the date parked.

Screenshot:
![image](https://user-images.githubusercontent.com/20681525/39870037-8a2cc0dc-5468-11e8-90ba-654032c4d720.png)

**Comment by jfburke3** [comment]
Actually, it would be best to show both.

**Comment by dmpr0** [comment]
Review:
Show date in another format: "The car is parked at 16:24 • Jul 29, 2020"
An additional issue, after adding a parking point, the context menu reopens for the same point that was shown before adding but should open for a new parking point.
