### ISSUE TITLE
What to call "aerial ways"

### ISSUE THREAD

**Issue by comradekingu** [osmandapp/Osmand#5382]
https://osmand.net/help-online?id=map-legend

From what I can tell, its only use is in the context of "ski lifts":

<string name="ski_map_render_descr">Skiing style. Key features: Renders pistes, aerial ways and other ski features in a convenient way. Less distracting secondary map objects.</string>

However, "aerial ways" is not a name in use outside of OsmAnd from what I can tell.

https://en.wikipedia.org/wiki/Cable_transport is the general name, but it includes elevators.

"Aerial lifts" does not cover https://en.wikipedia.org/wiki/Surface_lift , which I imagine to be included in downhill winter sport view.

In case it is both, 
"Cable transport networks" would eliminate elevators for general use
"Cable transport lifts" works for skiing views. Where an A- to -B thing for transportation that doesn't have to do with winter sports would not show up.

**Comment by sonora** [comment]
Here are possible alternatives, not sure I like any. Which one would you prefer? :)
![image](https://user-images.githubusercontent.com/845735/39915084-4710d01e-5507-11e8-8639-0d104a8de5f6.png)

**Comment by comradekingu** [comment]
Of those, cableways. Though I don't know if it applies to both cable cars and surface lifts.

What is wrong with "ski lifts"?

In a general sense, the word isnt used for anything other than the graphic overview that I can see. There i would prefer "Cable transport networks"
