### ISSUE TITLE
Open GPX without tracks in "Point" view

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#5384]
Our GPX handling is (and correctly so) also becoming a "Collection of Points" repository, i.e. not just for handling tracks.

I suggest that on our "Track analysis" screen, we put users directly to the "Points" tab if a GPX file does not contain `<trkpt>`. So far, we open the "Tracks" tab by default, but it is empty if no trkpts are contained. (This also regularly affects users getting there by selecting "Points" in a Wikivoyage article.)

**Comment by vshcherb** [comment]
I think it is already done.

**Comment by sonora** [comment]
Yes, done and works.

A "nice-to-have" could be to gray out or not even show tabs for which the GPX has no data, i.e. in the UI do e.g. not offer a "Track" tab if the GPX selected does not contain a track. But that can be a feature for the future changes we plan.
