### ISSUE TITLE
Osmand live not up to date? 

### ISSUE THREAD

**Issue by majkaz** [osmandapp/Osmand#5393]
I am using Osmand to update OSM and I am using the live map update to check it. 

For my map - Czech southwest, I am seeing last map change dated on the 3.5. The changes since then are missing. Usually, the live update is few days old at most and very often only few minutes to couple hours "old". 

Is the live update not running? Or is there any problem with this map?

**Comment by franco999** [comment]
Me too. Last map change on May 8th
OsmAnd 3.0.0#21061d

**Comment by tazva** [comment]
This goes back a few days ago.. #5368

**Comment by tuxayo** [comment]
@majkaz Can you retry? It should work now. https://github.com/osmandapp/Osmand/issues/5368#issuecomment-388632975

**Comment by majkaz** [comment]
Working OK:
Last map update shown as 13.5.2018, 22:20
my last changes were shown
