### ISSUE TITLE
Metroad shield not showing in OsmAnd map following update to OSM data

### ISSUE THREAD

**Issue by mrpulley** [osmandapp/Osmand#5397]
I recently updated the relations for Metroad routes in Brisbane, Australia to match the current tagging guidelines. Following this update, the route number on OSMAnd+ no longer has the hexagonal shield around the number.

Affected relations:
https://www.openstreetmap.org/relation/7936115 (Metroad 2)
https://www.openstreetmap.org/relation/541860 (Metroad 5)

Current route tagging:

network = MR
ref = 2

Old incorrect tagging on ways prior to my edit (this tagging rendered as '2' inside the hexagonal shield):

network = MR
ref = MR 2

Australian tagging guidelines at https://wiki.openstreetmap.org/wiki/Australian_Tagging_Guidelines#Non-Alphanumeric_Highway_Shields

**Comment by StenSoft** [comment]
Is this updated with OsmAnd Live? There seems to be an issue that roads don't use shields when updated over Live.
