### ISSUE TITLE
natural=rock has no icon and it is not searchable

### ISSUE THREAD

**Issue by AndreasTUHU** [osmandapp/Osmand#5407]
natural=stone POI is searchable in OsmAnd, but the simiral natural=rock is not. Only it's name tag visible on the map, without an icon.
https://www.openstreetmap.org/node/2339028880
https://wiki.openstreetmap.org/wiki/Tag:natural=rock

Please make it searchable, if it has a name tag.

**Comment by xmd5a2** [comment]
> Only it's name tag visible on the map, without an icon.
That's not true
![screenshot from 2018-05-16 10-27-06](https://user-images.githubusercontent.com/5829014/40102652-bb2b5524-58f3-11e8-9ab9-c7ad7a34fb99.png)
Problem with natural=rock lies in incorrect usage (bare_rock -> rock) https://overpass-turbo.eu/s/yQP
Mass retagging is needed. But ok, I've added rock to POI.
