### ISSUE TITLE
Prevent vertical scroll when scrolling horizontally in GPX activity

### ISSUE THREAD

**Issue by bagage** [osmandapp/Osmand#5410]
- What version of OsmAnd are you using, on what device and Android/iOS version?
**OsmAnd+ 2.9.3 from 2018-02-08 on Android 7.0**

When you record some GPX via osmand (cool feature that works reliably!) and save it on the phone, you can then see stats about it (speed for instance). 

You can move the X-axis point with the finger from the start to the end of the record, but when you do that, the activity/fragment also scrolls vertically which is a bit confusing/annoying.

**Comment by dmpr0** [comment]
We don't have problems with that. Horizontal scroll on graphs turn on after tapping on it, so it don't interrupt vertical scroll.

**Comment by bagage** [comment]
Thanks for the answer @dmpr0, but I'm not sure to understand it properly. I did a small video record to show the issue I'm having (unfortunately tap position is not shown, but basically my finger is just moving on screen) : http://webm.land/w/GXa0/

**Comment by vshcherb** [comment]
Yes, your video displays current desirable behavior. Though you could  avoid horizontal scroll, if you don't tap on the view. 
Vertical scroll is not desirable to prevent at all.

**Comment by bagage** [comment]
In general you only want to scroll in a single direction at a time. When you start to scroll horizontally, vertical scrolling should be disabled because it's not what you want (ie. it's impossible to keep your finger straight on the X-axis during the whole scrolling section).

But if it's designed to be used as-is, I won't interfere more though I'm curious of the reason behind this choice.
