### ISSUE TITLE
Wikipedia links don't work immediately after download

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#5419]
In Travel article click on the article name.
Dialog -> Download WIkipedia -> Go back to Travel -> Click on the Article name - no Dialog only suggestion to go to Internet

After restart everything works properly.

**Comment by PaulStets** [comment]
@vshcherb Perhaps the article you selected after the download wasn't found in the wiki database. I have tested on 100% existing article (Pariser Platz in Berlin/Mitte (en)) and wasn't able to reproduce.

**Comment by vshcherb** [comment]
Not reproducible any more
