### ISSUE TITLE
Play store beta version crashing when opening Travel screen

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#5425]
What version of OsmAnd are you using, on what device and Android/iOS version?
Current beta version available in the Play store:  3.0.0, released 2018-05-16
Samsung Galaxy S5 Active, Android 6.0

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?
Offline, but not map related

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.
Wikivoyage

I installed the latest beta version of OsmAnd+ from the Play store, then went to the new Travel (beta) menu item.  I started downloading the Wikivoyage file from this screen.  At or near the end of the download (I wasn't watching the screen), OsmAnd crashed.  (I mailed in the exception log.)  Now, when I relaunch OsmAnd+ and go back to the Travel screen, it starts to load the screen, then after a few seconds crashes the app completely.

I note that the Wikivoyage file appears to be downloadable from the map download menu item, so I'll try downloading it there and see if that works around the problem.

Please let me know if you need additional information.

**Comment by jfburke3** [comment]
Attempting to download the Wikivoyage data from the map download screen didn't help.  I ended up deleting the .sqlite file in the travel directory, which "fixed" the problem.  It appears if the Wikivoyage download fails, the app can't handle whatever corruption occurs in that file.

**Comment by jfburke3** [comment]
It took several attempts, but I was finally able to download the Wikivoyage data via the Download Maps function.  However, when I try to go into the Travel screen, it crashes the app.

I guess this means I have to stay home.

**Comment by vshcherb** [comment]
Duplicate #5431
