### ISSUE TITLE
"You have canceled your OsmAnd Live subscription"

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#5426]
What version of OsmAnd are you using, on what device and Android/iOS version?
OsmAnd+ beta 3.0.0, released 2018-05-16
Samsung Galaxy S5 Active, Android 6.0; and Toshiba Excite tablet, Android 4.2

When I exited out of the map download screen, the app took me to a screen that says I have canceled my Live subscription.  I don't have one in the first place.

**Comment by dmpr0** [comment]
Hi, thank you for feedback, we know about this issue and already fixed this. It issue only in beta version now.

**Comment by jfburke3** [comment]
Thanks, @dmpr0 !
