### ISSUE TITLE
"Travel", menu and marketing wording

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#5427]
@vshcherb  Victor, question affecting our menus, documentation, translators, and marketing: What would we call the new travel guide feature?

So far it is just called "Travel", with a capital T. But this is rather generic, and people already liberally translate it to other languages with little overall recognition value.
- Possible would be "OsmAnd Travel", in analogy to "OsmAnd Live", then we should probably make sure it remains untranslated

More altenatives are
- "Travel guide" (generic), or
- "OsmAnd Travel Guide" (more branded), or
- "Wikivoyage travel guide" or similar if we want to use their naming and branding (they do provide their translations on https://www.wikivoyage.org/)

**Comment by vshcherb** [comment]
Well yes. Initially it was just wikivoyage but the format is generic and it is simply a sqlite database with html article + gpx file. 

So I hope in future to publish a tool how to make the Travel book yourself. 
To be specific it is not a single Travel guide but rather a collection of Travel guides. Though I don't want to call it Wikivoyage and don't want to call it OsmAnd Travel cause we are not providing Travel guides ourselves.

**Comment by sonora** [comment]
In light of this I guess we should simply call the menu item 'Travel guides', just like I had already coined the corresponding section in 'Downloads'. And we can also allow people to translate the expression.

Travel guides explains exactly what this is about, is more specific than just 'Travel' (because in a sense our entire app with map viewing and navigation is about travel), but is generic enough to not imply that we are the content provider.  Ok?

In release notes and related documentation we can word that we now feature offline reading of travel guides, from which referenced sites' locations are directly linked to OsmAnd's map and can there be used to plan a trip and as navigation destinations.

**Comment by vshcherb** [comment]
English looks good.
