### ISSUE TITLE
Edited OSM Note fails to be published at OSM

### ISSUE THREAD

**Issue by dmromanov** [osmandapp/Osmand#5429]
OsmAnd+ 3.0.0, 2018-05-16
Android 8.0.0 OPR1.170623.027
Xiaomi Mi6 Global Stable ROM

A note, created by Osm Editor would not export to OpenStreetMap.

1) Enable `OSM editing` Plugin
2) Create a note on a map: enter text, click "Create Note"
3) Then, without loosing focus on the created note, in actions menu click "Modify OSM note"
4) Make a change and save
5) Try to send the note to OSM.

Login dialog will continually pop up.

To work around this, close the login dialog, select other POI and then select back the created note. Publish the note as usual.

https://www.youtube.com/watch?v=xNS53a6SfK8

**Comment by xmd5a2** [comment]
I observe the same behaviour
