### ISSUE TITLE
Street names in roundabouts

### ISSUE THREAD

**Issue by Aiurek** [osmandapp/Osmand#5441]
Lenovo Moto G4 plus, Android 7.0
OsmAnd+ 2.9.3, released 2018-02-08
May style: OsmAnd

The illustration of street names in roundabout leads to a pretty strange and clumsy placement of characters. Especially in low magnification the agglomeration of characters looks like some kind of odd black POI icon that easily catches someone's eye.

https://www.openstreetmap.org/#map=19/48.79716/9.69712

![screenshot from 2018-05-19 09-32-50](https://user-images.githubusercontent.com/27865200/40266229-c03247f2-5b47-11e8-94d1-380e54f69a86.png)

**Comment by jfburke3** [comment]
The OSM wiki on roundabouts says not to put a street name on them, unless it's the name of the roundabout. 

https://wiki.openstreetmap.org/wiki/Tag:junction%3Droundabout

**Comment by vshcherb** [comment]
This is a duplicate issue with curve streets and isolines (though I didn't find it yet).
