### ISSUE TITLE
Travel guide: Suggest articles near currently viewed map location

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#5445]
I think we could immensely boost the usability and explorability of the new travel guide feature if, when the travel guides activity is opened up, we would automatically suggest articles which focus on locations in the area the user currently viewed on the map.

I guess the way to implement is via -for each article- somehow attributing a (pseudo-) location which is the "mean" of the "Points" location references contained in the article, then suggesting articles whose mean location is close to the current map center.

**Comment by vshcherb** [comment]
We currently implement "Popular articles" following very similar paradigm. About 2/3 of articles in these sections are sorted by locations, other articles are random ones and they are from top 300 viewed on the wikivoyage website.

So in some sense it is implemented

**Comment by sonora** [comment]
Yes, that's true. I wonder if we should create an entry 'Nearby travel guide articles' in analogy to the already existing 'Nearby Wikipedia articles' on the context menu, that would open yet another path to finding relevant articles.

**Comment by vshcherb** [comment]
I think it's already implemented
