### ISSUE TITLE
German Search Mechanism: ß == ss

### ISSUE THREAD

**Issue by paskalito** [osmandapp/Osmand#5447]
prelude: There is a letter in german ß its a "sharp" s. And since the german word of street is Straße its all over the place when navigation however you can also write Strasse wich is what i'm used to  - and also is faster to type on a keyboard..
https://de.wikipedia.org/wiki/%C3%9F

problem: Whenever i try to find any streetname i don't find it because its saved  with "ß" instead of "ss"

proposed solution: make ß equal to ss for searches

edit:
obviously there is also a capital form of that letter..
https://de.wikipedia.org/wiki/Gro%C3%9Fes_%C3%9F
ẞ == SS
ß == ss

**Comment by vshcherb** [comment]
Umlaut like ä, ö, ü  should be supported cause we use Collator and it should be working fine.

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/40327420-19f9321c-5d43-11e8-86d1-eb30379f67cf.png)
Can't reproduce even with english locale

**Comment by sonora** [comment]
As I said, it works in POI search but not in the Wikivoyage search!

**Comment by vshcherb** [comment]
@sonora :( known issue, we use database search and not a binary format. I'm afraid today I don't know solution to support it, unless we invent a different search.

**Comment by sonora** [comment]
All right, I think in Wikivoyage it may not be too big a deal, then, because people can chose heir own language anyway in most cases. Just thought it might be an oversight in our new functionality.
