### ISSUE TITLE
Increase SQLite performance by changing synchronous mode to NORMAL

### ISSUE THREAD

**Issue by tico-tico** [osmandapp/Osmand#5456]
By default the **sqlite** library uses FULL synchronous mode which is very safe, but it's also slower. Sending `PRAGMA synchronous = NORMAL;` just after the db file loading should speed up sqlite transactions and (hopefully) prolong the sdcard life. According to the docs https://www.sqlite.org/pragma.html#pragma_synchronous

> The synchronous=NORMAL setting is a good choice for most applications running in WAL mode.

And i think it would be also a good idea to add a hidden (dev. menu) option 'brakes're for losers' which changes synchronous mode to OFF.

All this matters mostly for sqlite tiles maps i believe.

**Comment by vshcherb** [comment]
Please create a pull request in case you know what and where to change. Anyway I will keep this issue open till a technical review will happen.

**Comment by tico-tico** [comment]
I'm truly sorry, but i know nothing about the Java language. But after some code reading (they say all proggi languages are the same, hehe, liars), i'd add `execSQL("PRAGMA synchronous=NORMAL;");` in the very end of `SQLiteDatabaseWrapper` constructor, just after `this.ds = ds;`.

**Comment by dmromanov** [comment]
Did it work?
