### ISSUE TITLE
Bunch of unnecessary postcodes, cluttering up results

### ISSUE THREAD

**Issue by ADepic** [osmandapp/Osmand#5457]
When I search for a postcode, it is only the postcode I search for that I expect to appear. However, when I type a postcode that is not downloaded 100s of unnecessary, unrelated postcodes show up - normally not even closest matches so even if you mistyped the postcode it is no help:
![unnecessary results top](https://user-images.githubusercontent.com/24532838/40327754-9436f68c-5d33-11e8-8be0-ed1ce3eb4438.png)

The problem with this is that I have to scroll all the way to the bottom to access online search:
![unnecessary results bottom](https://user-images.githubusercontent.com/24532838/40327776-a74410e8-5d33-11e8-9855-20c969715594.png)
And that finally gives me the postcode:
![online search](https://user-images.githubusercontent.com/24532838/40327795-b2b386ac-5d33-11e8-8696-09dc8d6b5a93.png)
This makes searching through osmand a lot harder to use. Can you fix this?? It should be a SUPER easy fix for your next osmand version.

BTW this applies to postcodes that have been downloaded too: however the correct postcode is the first result and then 100s of unnecessary postcodes underneath

**Comment by vshcherb** [comment]
This postcode is not present in OSM data that's why it is not searchable.

**Comment by ADepic** [comment]
I don't think you understood the issue. With maps.me, I get exact results, and with osmand I get 100s and 100s of irrelevant postcodes. What you have to do is simply get osmand to return precise results like osm nominatim does. This a search query issue improving the ease of search - nothing else.

And I searched in the "Catagories" section although the postcode section does the same

**Comment by ADepic** [comment]
Maps.me does not use online search, since it gives the same results as osmand, just exact results not 100s of irrelevant ones.
I still think you are missing the point: this applies to working postcodes too:

![screenshot_osmand _20180521-222800](https://user-images.githubusercontent.com/24532838/40331031-ea084f3a-5d46-11e8-92a5-b8d60b1ee00b.png)

I should only see one result, not 100s

**Comment by ADepic** [comment]
Please can you open this? It is such a easy fix!! With maps.me, for me it only lists the required results - that is the ways listed with a postcode:
![screenshot_maps_20180522-192952](https://user-images.githubusercontent.com/24532838/40382805-d774d0d4-5dee-11e8-97da-d5e517d194c3.png)

But osmand, I have to scrool through a humoungous list of postcodes - when only one is correct (or no postcode is correct)!!
![screenshot_osmand _20180522-193014](https://user-images.githubusercontent.com/24532838/40382880-fcbd63e2-5dee-11e8-8528-6d7e3e7d791c.png)
![screenshot_osmand _20180522-193017](https://user-images.githubusercontent.com/24532838/40382892-028736c2-5def-11e8-9065-7c7362313bdf.png)
![screenshot_osmand _20180522-193021](https://user-images.githubusercontent.com/24532838/40382898-054e418e-5def-11e8-9c6e-26d42534e8bd.png)
![screenshot_osmand _20180522-193024](https://user-images.githubusercontent.com/24532838/40382907-08acb202-5def-11e8-91f6-787149647f4b.png)
![screenshot_osmand _20180522-193027](https://user-images.githubusercontent.com/24532838/40382915-0d03e9a6-5def-11e8-9db6-a1a02c4d9fc2.png)
![screenshot_osmand _20180522-193029](https://user-images.githubusercontent.com/24532838/40382918-10938270-5def-11e8-9fbf-7c86488b1da1.png)
![screenshot_osmand _20180522-193033](https://user-images.githubusercontent.com/24532838/40382926-1382e980-5def-11e8-989c-6c5aa84f5395.png)
![screenshot_osmand _20180522-193036](https://user-images.githubusercontent.com/24532838/40382933-162953e0-5def-11e8-90ea-c5182804c90f.png)
![screenshot_osmand _20180522-193039](https://user-images.githubusercontent.com/24532838/40382939-18a58058-5def-11e8-8bb0-ba32245c70a6.png)
![screenshot_osmand _20180522-193042](https://user-images.githubusercontent.com/24532838/40382947-1fed5e1c-5def-11e8-826b-0d8f07d12528.png)
![screenshot_osmand _20180522-193045](https://user-images.githubusercontent.com/24532838/40382952-23a11abc-5def-11e8-830f-2c89a572c3ce.png)

And then finally I reach the online search and increase search radius!!
![screenshot_osmand _20180522-193049](https://user-images.githubusercontent.com/24532838/40382989-3bd922dc-5def-11e8-8410-c59b94378189.png)

Only ONE result is correct, so why is osmand showing HUNDREDS of results!!

How come you misunderstood such a simple problem!!
