### ISSUE TITLE
Many postcodes missing unless in relation to a building

### ISSUE THREAD

**Issue by ADepic** [osmandapp/Osmand#5458]
Many postcodes that are existant on OSM are missing in osmand. This is because osmand seems to only download postcodes that are stored in building information. As an example, my home postcode was on OSM, but not on osmand, so I added house numbers and postcodes to all of houses in this area, and in the next update osmand recognized the address.

However, this is very problematic since I live in a town, and not a big city so most houses do not have house numbers and ip addresses attached to them. This means that many postcodes are missing unlesss you use online search (thankfully osmand has this, maps.me doesn't and it is a deal breaker).

I know these adresses are stored somehow on osm nominatim, and I can appreciate if you can't pull such specific details from such a vast database, but at least I have brought this problem into light, because coupled with issue #5457  it is sort of a ease of use problem...

**Comment by vshcherb** [comment]
Please tell which postcode is missing we could simply check it in obf data and understand how did we miss it. Please provide a link to openstreet map object like https://www.openstreetmap.org/way/73111901#map=19/48.90260/2.40353 if possible.

**Comment by ADepic** [comment]
Example: postcode IP1 1AG is shown from OSM nominatim:https://www.openstreetmap.org/search?query=ip1%201ag#map=19/52.05508/1.15367 but missing in osmand: (#5457) .

But another address: IP4 4QY has been added as info in ways (https://www.openstreetmap.org/way/566370682) and so it is recognized by osmand.

**Comment by vshcherb** [comment]
I checked on nominatim as well but I didn't find the OSM object, so I can't tell if it is OSM data or not.

**Comment by ADepic** [comment]
Its simply osm nomination database result ( I'm pretty sure) so unless you link it to some houses osmand does not recognize it as data.

**Comment by ADepic** [comment]
Okay I found were nomination gets UK postcodes.

Scrolling through the Nominatim documentataion I found this:
![screenshot_firefox_20180525-204852](https://user-images.githubusercontent.com/24532838/40563776-f49a2a3a-605d-11e8-812b-2e386b065638.png)
So there is a link to download these postcodes:
https://www.nominatim.org/data/gb_postcode_data.sql.gz

The file is around 33mb.

I downloaded the file, and it contains (what seems like) every single used postcode in the Uk. On each line, a postcode is listed , followed by a space and then a set of strings which I don't know the meaning of.
AB10 1AG  0101000020E6100000D4C563CFE6C500C02072705EF9924C40
As you can see "AB10 1AG" is the postcode, and it is followed by a set of numbers and letters which I don't understand. 

However these will be documented somewhere in nomination / osm documentation.

If you can get this to work, then I think the best solution is to have UK postcodes as a separate downloadable file in the "other maps" section along with the Norway trondelag maps and prompt the user that he/she can download these postcodes he/she is downloading a UK map.

**Comment by ADepic** [comment]
Okay, I'll close this and make a new issue.
