### ISSUE TITLE
Regression: Destination -> Favorites: Sort by distance not available without location

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#5467]
When OsmAnd has no current location it is no longer possible to sort favorites by distance from the direction dialog. Tapping on "sort by distance" simply does nothing. Previously, with no locations, OsmAnd did sort favorites according to the currently displayed map position.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/commit/521f87027c0ff38d62cbf55d37bb12e59e9f1bde
