### ISSUE TITLE
Full text search: Allow sorting by relevance

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#5469]
The current search dialog sorts search result only by distance. Having additional modifies like sort by relevance would be really useful.

Example: A search for the famous peak _Brocken_ displays tons of unrelated results: 
![photo_2018-05-22_22-42-55](https://user-images.githubusercontent.com/1040784/40389395-9db465a2-5e12-11e8-9149-bf84cbc9c0c9.jpg)

Notice the scroll position marked with the red circle. You have to scroll dozens of pages down in order to find the best match. Despite the object with the exact name being only 40 km away.

**Comment by vshcherb** [comment]
In order to find exact match you need to Hit enter on the keyboard or space

**Comment by vshcherb** [comment]
And now current sorting is mixed of prioritizing address, cities and places

**Comment by Marenz** [comment]
I would argue that a custom order adds undesired complexity to the user interface. Instead we should find a default sorting criteria that is good enough for the majority of the cases (including your case of course).

e.g. in your case the criteria "similarity to search term" should fix the sorting if it is weighted in with an adequate %. (70% distance, 30% name similarity for example..exact numbers to be determined)

**Comment by vshcherb** [comment]
Looking again at that issue it works correctly for partial search results, in order to search by full word it should be either click button finish search or put a space
