### ISSUE TITLE
Safe mode setting is not saved

### ISSUE THREAD

**Issue by dmromanov** [osmandapp/Osmand#5470]
OsmAnd+ 3.0.0, 2018-05-16
Android 8.0.0 OPR1.170623.027
Xiaomi Mi6 Global Stable ROM

Switching on a "Safe mode" option on OsmAnd setting is not saved and switches off upon restarting OsmAnd.

1) Open OsmAnd settings
2) Check "Safe mode" checkbox in a general settings menu.
3) Close settings menu and terminate OsmAnd
4) Open OsmAnd and check the setting.

The setting will be switched off.

**Comment by vshcherb** [comment]
Safe mode should not be used cause it has limited functionality

**Comment by dmromanov** [comment]
@vshcherb It was needed for testing #5463
