### ISSUE TITLE
Set default map style for pedestrian and bicycle view to Topo and for car set Touring

### ISSUE THREAD

**Issue by erik55** [osmandapp/Osmand#5472]
This is a something I tell everybody when I recommend them to install OsmAnd, and all of them change it, because they find it useful:
- Pedestrian view: map style _topo_ and _routes with osmc symbols_ enabled
- Bicycle view: map style _topo_ and _bicycle routes_ enabled
- Car view: map style _touring_

This should be defaults in the different views. All of my hiking clients (~ two hundred a year) to which I show this, like and appreciate it.

Maybe you could change that for the next release. And also change, that elevation is considered by default for navigation time calculation, see #4455.

This is a usability feature request.

**Comment by sonora** [comment]
Default map styles: Same here, I wholeheartedly agree. These styles are the true strength of OsmAnd and for many users a killer argument vs. other app. Some users tell me they use Touring view also for hiking/biking, because under some circumstances or light conditions it provides more contrast when being outdoors.

But there may be a more "novice" user base liking simplified map views, not sure. Not the folks I normally get contacted by about OsmAnd ... :)

**Comment by ADepic** [comment]
This is very important. Good default settings are NECESSARY if you want a bigger userbase.

If the default settings are bad, many people will uninstall without giving a second book. People do judge a book by it's cover, sadly, because they don't have the time to read the whole book.

**Comment by scaidermern** [comment]
Touring for car sounds good. However I'm against using touring for bicycle/pedestrian since it almost contains no POIs (such as restaurants). Displaying POIs is a very important feature most users don't want to miss.

**Comment by vshcherb** [comment]
Today we don't support changing rendering options and map style based on profile. We don't collect that data to say how many people could have changed it.
The question about default settings is always difficult, I believe we should not try to mix "Profile" with "Map purpose", pedestrian doesn't mean hiking or city navigation. Profile means set of settings enabled for specific navigation. 

We have extra profiles like "hiking", "motorcycle", "boat" we still plan to enable them in the main version.

Our default styles are mostly focused on city usage.

**Comment by erik55** [comment]
Ok, I understand the city usage argument, of course many people need the *city view map style* when walking in the **city** – and not hiking with backpacks. By the way: This map style is still called *osmand* – please rename it to *city view*, because that is its main use case and is selfexplanatory, where *osmand* map style is just of historical importance (I suppose it was the first map style).

So for now we have four profiles:
* world (which I use with the *city view* (you call it *osmand*))
* car (touring view would be the most obvious map style)
* bicycle (both city view and topo would match)
* pedestrian (again: both city view and topo would match).

Ideas for improving (usability):
* change the logo of the world profile to a city (skyline) and make it use the city view map style (= *osmand* map style).
* use the *city view* also for (city-)bicycle and (city-)pedestrian
* activate two more profiles: mountain bike and hiking person (logo with a backpack and walking sticks) and make them use the topo map style as default.

Problem: Many profiles! To many?
Komoot has many profiles https://www.komoot.de/plan/ but only one map style as far as I know (because they use their application only for outdoor sporty activities). I think it would not be to bad to have more profiles with appropriate map styles in Osmand.

Well, when I compare with Komoot: They have racing bike, mointain bike and city bike!!! Oh my god.

And what about motorcycle? Could use the car profile. Unless somebody complains. ;-)

**Could we discuss this?** The topo map style is really, really good (with Routes in OSMC style turned on). My clients are really amazed and delighted every time when I turn them that features on and show them the map. No mapping application has that!! But it is not turned on by default (neither topo map style nor hiking route symbols).

**Comment by ADepic** [comment]
How is touring a good option for car. The roads are to thick, meaning you can easily miss moterway exits (you don't see them) and junctions are rendered as one big blob. Touring is also touted as the style that shows the most information, not good for car navigation (you need to see roads and maybe a few POIs)

Also topo doesn't look attractive, which isn't a big problem - the actual problem is that it shows no POIs (when walking it is useful). Also Maps.Me with 3d buildings with heights is really useful . For normal navigation I think maps.me is better in that situation. However I still think Topo should be used for bicycle and maybe pedestrian too.

**Comment by vshcherb** [comment]
@erik55 Thx for Komoot example . Indeed they represent much more valuable app for outdoor activity i.e. navigation with alt profile (we are only planning it) and multiple focused profiles on different outdoor activities . 
Indeed Topo style is a perfect choice for that. Of course OsmAnd has quite a lot of features and settings for that but they are not structured yet.

**Comment by vshcherb** [comment]
As of today we have profiles that could be created and shared, so I think the core of this issue is fixed.

**Comment by ADepic** [comment]
What do you mean by this? If the better options aren't defaultz then the issue isn't fixed.
