### ISSUE TITLE
Travel guides: unbookmark disable GPX points

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/OsmAnd#5473]
Unbookmarking travel POIs does not hide them from the map.

OsmAnd+ 3.0.0 (Today's PlayStore beta release)
----- Developers comment ---- 
- [x] Bookmarking article without viewing it, adds empty GPX to My Places.
- [x] Unbookmarking travel article should hide GPX file

**Comment by sonora** [comment]
True. But also: Boomarking does not add them to the map, right? Guess we need to think about what actions the bookmarking should trigger at all ..

**Comment by Norbert80** [comment]
Adding seems to work the first time. Then removing is only possible by deleting the gpx. If you don't remove the blank gpx (folder) adding by bookmarking does nit work as long it us not deleted.

**Comment by Norbert80** [comment]
Is it intended that these bookmarks are of "a special type", not accessible as normal bookmark?

**Comment by Norbert80** [comment]
@sonora: Please not that not all guides contain coordinates. Perhaps that's the reason why you couldn't see travel POIs on the map.

**Comment by sonora** [comment]
Tested again. When I bookmark an article which contains points, the corresponding gpx data does not become visible on the map (neither is the corresponding file marked as visible on our gpx ("Tracks") tab). This is regardless whether I tap 'Bookmark' for an  article on the travel guide article overview page or open the article ('Read') then tap its Bookmark button.

The points are for me placed on the map only via tapping an article's 'Points' button, and then on the screen with the point list tap on any one point. (Tapping the map on that screen also hides all points again). Points subsequently remain visible until I deselect them under Configure map/ GPX layer. Do you see a different behavior?

**Comment by Norbert80** [comment]
There is another problem: There is always an update offered although there is still the data file from May 16, 2018 available that I have already installed.

**Comment by Norbert80** [comment]
@sonora: What you describe in yesterday's commt sounds like the same that I experience. But I don't understand/experience the following part in brackets:
"(Tapping the map on that screen also hides all points again)."

**Comment by vshcherb** [comment]
This issue will be  potentially patched in 3.0 though first the decision needs to be made. There is indeed something to decide and now after 3.0 is rolled out we hope to get enough feedback.

**Comment by sonora** [comment]
Have not investigated too much, but I guess displaying/hiding the associated GPX data on the map with bookmariking/unbookmarking an article may not be a bsd idea.

**Comment by sonora** [comment]
Just for completeness: With current behavior there seem at least 2 more ways to display the travel guide points on the map:
3. Article -> Points -> Tap on any single point
4. Article -> Points -> Tap on the miniature map displayed
In both the cases, the points will be removed again after tapping the device's back button twice, as this will get you back to the Article, but only if
- you did not activate the new 'Show on map' on the Points tab, and
- as long as after being on the map screen you do not start any other action which 'deletes' the 'back button history', like performing a search.

This overall behavior is 'sort of ok', we have improved from before, but I guess there is still room for improvement. In particular the effect of the new 'Show on map' option seems a little obscure?

**Comment by dmpr0** [comment]
Bookmarking article without viewing it, adds empty GPX to My Places.
![Снимок экрана 2021-04-08 в 14 42 36](https://user-images.githubusercontent.com/9365308/114020835-abc14680-9878-11eb-9a74-32fd7fa96a45.png)
