### ISSUE TITLE
Address search: Incorrect building relation

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#5479]
Searching for the Auhofstraße in Vienna returns two results. One is correct and has most of the house numbers and the other only contains building 181. Pressing on the building centers the map in the incorrect place.
Correct:
![image](https://user-images.githubusercontent.com/20681525/40477866-39d264f0-5f50-11e8-9dc8-92b3ff92c3ba.png)
Shown in OsmAnd:
![image](https://user-images.githubusercontent.com/20681525/40477898-4c714e96-5f50-11e8-9a66-1b1caa381233.png)

**Comment by vshcherb** [comment]
This issue is fixed
