### ISSUE TITLE
Routing ignores turn:lanes of a way and highlights a wrong lane of another way

### ISSUE THREAD

**Issue by oxxm** [osmandapp/Osmand#5487]
Hello all,

way 1 has 2 lanes set:  left;through|right
https://www.openstreetmap.org/way/106634223

way 2 has 4 set: left;through|through|right|right
https://www.openstreetmap.org/way/476885983 

Expected behavior while driving, coming from the bridge through way 1 and 2 is:

Highlighting the right lane of way 1, then the lanes right|right of way 2.

Currently Osmand is highlighting only the second lane (through) of way 2 and totally ignoring way 1.

Are the lanes of way 1 not set correctly in OSM? or is it an Osmand routing issue?

Thank you

P.S.: Using map updates from live osmand of 25.05.2018 and v. 2.9.3

**Comment by scaidermern** [comment]
A screenshot would be helpful. Is this the same problem as #5235?

**Comment by oxxm** [comment]
As you can see in the screenshot, way 1 is ignored and -through- is highlighted.

This issue could be relates to #5235, but i am not totally sure.

![osmand](https://user-images.githubusercontent.com/39620251/40586304-09a73cf8-61b0-11e8-9a46-11dddf5559a8.jpg)

**Comment by vshcherb** [comment]
There was not enough OSM information to determine proper turn:lanes - added here https://www.openstreetmap.org/changeset/59713972#map=17/48.57021/7.79374

**Comment by vshcherb** [comment]
https://www.openstreetmap.org/way/106634223 is not considered as a turn that's why lanes are not displayed. 

The issue with wrong lane is fixed by adding data to OSM.
