### ISSUE TITLE
osmand crashes during installation of new nightly.

### ISSUE THREAD

**Issue by MAlfare** [osmandapp/Osmand#5495]
Since:
Version  OsmAnd~ 3.0.0#24895m
22.05.2018 12:07:32
Apk Version : 3.0.0#24895m 300

Until now:
Version  OsmAnd~ 3.0.0#24964m
25.05.2018 9:55:47
Apk Version : 3.0.0#24964m 300

Installation of new nightly from within osmand - Builds behalves different on my three devices:

Works O.K. on the smartphone

osmand crashes on the asus tablet after downloading
osmandToInstall.apk
[exception.log](https://github.com/osmandapp/Osmand/files/2040817/exception.log)

osmand does nothing on the lenovo tablet after downloading
osmandToInstall.apk

on both tablets I can install osmandToInstall.apk manually with Total Commander (filemanager)

Details of the three devices:

Device : smartphone
Brand : lenovo
Model : Moto G4 +
Android Version : 7.0
osmand folder in osmand settings: /storage/emulated/0/Android/data/net.osmand.plus/files
osmand folder in Total Commander: /storage/emulated/0/Android/data/net.osmand.plus/files
 
Device : tablet
Brand : asus
Model : ME302C
Android Version : 4.3
osmand folder in osmand settings: /storage/sdcard0/osmand
osmand folder in Total Commander: /storage/emulated/0/osmand

Device : tablet
Brand : lenovo
Model : A3500-F
Android Version : 4.4.2
osmand folder in osmand settings: /storage/emulated/0/osmand
osmand folder in Total Commander: /storage/emulated/0/osmand

**Comment by vshcherb** [comment]
This is caused with upgrade to Android O version which have to do anyway
https://github.com/osmandapp/Osmand/commit/bbc14193c535160cdb2c35b17fb16c81f4197062#diff-6ae2effb1e06d20d324a0900e427f6a2

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/commit/ac14f84aafd6a6a69f8c03ae4345719d4bfdf38f
