### ISSUE TITLE
OSM Live Updates broken again

### ISSUE THREAD

**Issue by tazva** [osmandapp/Osmand#5498]
Observed on 3 different android versions, running latest OSMAnd+.

The web status (https://osmand.net/api/osmlive_status) shows current date (5/26 1455), but the last available update was 5/21, despite updates being made since then.

North America Virginia file, for reference.

**Comment by tazva** [comment]
No it's not road only, it's the full map for the whole state.

No, I didn't re-install, because that's not a requirement. I did re-download the state file (which again, isn't necessary when Live is working), but it's still out of date.

**Comment by tazva** [comment]
Appears to be working again, map updates finally came through.

**Comment by ADepic** [comment]
Working?? Then close the issue

**Comment by scaidermern** [comment]
Not working, they are stuck again. E.g. OsmAnd still says the last change for Thuringia, Germany has been at 05:45. This is not true. The update process is stuck for at least 7 hours.

**Comment by vshcherb** [comment]
Investigating the issue and couldn't trace it yet. According to the server logs there was no outage in the pipeline at all. So the issue could be related to the file download process.

**Comment by vshcherb** [comment]
I would like to keep that issue open for a while though I didn't manage to find evidences yet. In case somebody notices it again, please check:
1. Run update now
2. Check Date in the top bar of android application (Should show same timestamp as osmlive_status)
3. Please check if the file for your region is generated and you possibly can download it manually - http://download.osmand.net/aosmc/germany_thueringen_europe/

**Comment by xraMsamohT** [comment]
No live update in Germany (NW and BY) since `2018-05-28 12:10`.

**Comment by vshcherb** [comment]
From 2018-05-28 12:10 GMT was a problematic change produced in OSM only now we've got it fixed. Soon it will be updated

**Comment by tazva** [comment]
Thanks for the update, I was going to post that I see the live status is out of date, and haven't seen new data. Same issue as the last time it broke?

**Comment by vshcherb** [comment]
I will close that issue to not confuse with future issue. 
This time the OsmAnd Live was broken cause somebody put in OSM: "direction"="300000000000" and we had a poor algorithm of parsing direction without handling overflows.

**Comment by scaidermern** [comment]
Broken again. https://osmand.net/api/osmlive_status says `2018-06-23 15:20`.

**Comment by xraMsamohT** [comment]
Any news? Should we open a new issue every time the updates do not work again? OsmAnd Live is unreliable since some weeks and obviously the servers are not monitored.

**Comment by scaidermern** [comment]
Looks like it is catching up slowly: `2018-06-26 11:30`. Still more than a full day behind.
