### ISSUE TITLE
Make transparent widgets default

### ISSUE THREAD

**Issue by ADepic** [osmandapp/Osmand#5500]
White Widgets take up WAY to much space when navigationing and can be seriously overwhelming for beginners. I would HIGHLY suggest to make the transparent widgets default, since they show you more of the make and there is less clutter.

This goes hand in hand with issue #5472 which is necessary as well.

**Comment by erik55** [comment]
Interesting. Where can you set this?

**Comment by ADepic** [comment]
The Osmand Menu > Configure Screen (scroll all the way to the bottom) > Enable Transparent Widgets
![screenshot_osmand _20180526-224128](https://user-images.githubusercontent.com/24532838/40580443-b20e7966-612d-11e8-9dde-1385b380cc25.png)
![screenshot_osmand _20180526-224133](https://user-images.githubusercontent.com/24532838/40580447-b9880b08-612d-11e8-8c15-63c08d82ffda.png)

**Comment by erik55** [comment]
Thanks. But I have to say, that in my installation it was: 

- world view: transparency ON
- car view: off
- bicycle view: off
- pedestrian view: ON
- ship view: ON

I don't remember that I have ever changed that, maybe it is already turned on for some views? For me it looks good like that, but I'm not really sure if that was the default. 

Offtopic: I'm also a Syncthing user. ;-)

**Comment by sonora** [comment]
Yes, that's exactly the default fior the ressons I explained. Whoever does not like it can change it individually.

**Comment by ADepic** [comment]
Oh right.

But I still think something needs to be done about the clutter in car mode while navigation.

I think the best solution would be to have a bar at the bottom just like MAPS.ME and google maps

The widgets add too much clutter

**Comment by erik55** [comment]
@ADepic Maybe you are right, at least some major car-navigation device vendors designed their userinterface like that.
- [Example 1](https://www.google.com/search?hl=de&q=navigation%20tomtom&ie=utf-8&tbm=isch)
- [Example 2](https://www.google.com/search?hl=de&q=navigation%20navigon&ie=utf-8&tbm=isch)

But then please open a separate issue and do not just complain, but tell us or better show us in an image or screenshot with additional painting how you would think it could be better. But the widgets have then to be moved consistently in all views (pedestrian, bicycle, car, world, …) to have a good usability.

**Comment by sonora** [comment]
Please note that unlike most car nav systems which mostly come with certain hardware we have to support a wide variety of screen sizes and resolutions in both portrait and landscape orientation, and many more use cases. What appears cluttered on a small 4in screen for a hiker may seem too small and empty on a 10in tablet in a truck, etc., that's why there is likely no good "one size fits all" solution.
