### ISSUE TITLE
GPX editing issue

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#5501]
If there are more than 1 segment in the gpx file, you can only save the modifications to the first segment. After saving changes to the 2-nd or further segment, they are lost when you reopen the gpx file for routing or for editing in the track editor.

**Comment by fanheuser** [comment]
Seems to be still present in OsmAnd's nightly build of 23-Apr-2019 (used on Android 8.0 or 6.0.1, common storage storage/emulated/0/osmand):
- Saving the track after moving or deleting points from the first segment (of a 2-segment track) leaves the track unchanged (i.e. the move or deletion is not saved)
- Saving the track after moving or deleting points in the second segment (same track as before) is successful (thus, access right problems can apparently be ruled out)
