### ISSUE TITLE
No speed limit widget while (re-)calculating a route

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#5503]
During route (re-)calculation no speed limit information is shown.

**Comment by vshcherb** [comment]
Known issue. Not planned to be fixed.

**Comment by scaidermern** [comment]
Oh :( Is it too hard to fix? (Re-)calculations for long routes can take a while. It would be really nice to have speed limit information during route calculations.

**Comment by vshcherb** [comment]
Speed information is retrieved from the route itself, if there is no route - there is no speed information. Also access to the routing files is single threaded, so we can't schedule another parallel operation for where am i.
