### ISSUE TITLE
Spinoff of #4149 (route calculation progress bar)

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#5506]
I have a few minor observations we may want to look at at some point, as follows:
- **Color:** The progress bar now borders on the map, so it should have a color with good contrast vs. the map. I suggest instead of the generic light blue we could use the route color as defined by the rendering style? (Which is an intense dark blue for most cases)
- **Placement:** On some devices (maybe those with non-standard screen sizes, not sure) like the Samsung S4 Mini, the progress bar when attached to the route config dialog is not at the very top of the dialog but about 1.5 progress bar widths further down. Conversely, when the dialog is hidden, the progress bar is not at the very bottom of the map screen, but about 2 progress bar widths up from the bottom (with a small strip of the map being visible between the bar itself and the lower screen edge). Probably a rounding error of some sort when placing the bar? (Screenshot regarding this see https://github.com/osmandapp/Osmand/issues/4149#issuecomment-392263621)

DONE:
- **Value:** We have always had this: when our normal 2 phase routing is active, the progress bar runs across the screen twice before the route is finished. Should not be a problem to predict when 2 phases will occur and simply adjust so that the end of the first phase is simply the 50% value (screen center), and the right hand screen edge is only reached after the second round (100% value)?
- **Initially no progress visible** for some time after route calculation starts: I have seen users stare at the route config dialog wondering if they need to still tap anything because the route calculation had not visibly started yet. (This e.g. can be due to the position still not found so the app waiting for that, or some initialization still going on, see e.g. #4043). This could maybe be solved by immediately starting the progress bar at its say 5% level (if a destination is already selected, not to be confused with if not, i.e. where the user really has to become active first), so the user clearly sees if OsmAnd is in the progress of calculating already, or if a user input is still needed?

**Comment by vshcherb** [comment]
Initially no progress visible - fixed

**Comment by vshcherb** [comment]
Value with 2 progress bars is fixed.

**Comment by AlexSyt** [comment]
Color: fixed.
Placement: fixed for the map screen.

**Comment by AlexSyt** [comment]
Color and placement: fixed for the map screen.

**Comment by scaidermern** [comment]
+1 for making the bar wider. Even on my low-res 1280x720 device the progress bar is hardly readable if the phone is not directly in front of you, e.g. in a car.
