### ISSUE TITLE
[UI Issue] Wiki "Read Full Article" button

### ISSUE THREAD

**Issue by SergeyP2** [osmandapp/OsmAnd#5513]
I've updated from 2.9 to 3.0 and noticed that when I read Wiki article the button "READ FULL ARTICLE (ONLINE)" always hover over bottom of an article. As far as I remeber it wasn't this way in 2.9 but may be my memory let me down. 

Anyway, the button occupies too much space, and even more in Russian locale. Obviously, you can hide it. I would prefer to hide it under "Menu" button that you already have in this window, but if you afraid that a new user will miss this functionality, at least hide this huge button after a few seconds or scrolling. Or add button "Online" next to "language" button in top tollbar, anyway the title at the top doesn't have big value.

**Comment by vshcherb** [comment]
We need to hide it when scrolling.

**Comment by dmpr0** [comment]
The button should not disappears while scrolling to the bottom.
