### ISSUE TITLE
OSMAnd Live: Map Payouts

### ISSUE THREAD

**Issue by tazva** [osmandapp/Osmand#5523]
I've heard something may have changed in the payouts to people who are contributors to OSM. I'm guessing that's the case, because I haven't received my small payment since December.

What's changed?

**Comment by vshcherb** [comment]
Not much should have changed. Please check yourself in underpaid report http://builder.osmand.net/reports/report_underpaid.json.html

and please check if you are present in recipients page on OsmAnd live

**Comment by tazva** [comment]
Maybe my understanding of it isn't accurate, perhaps you can help. I am to understand that 50% of collection goes to OSM/Fees, and 50% to the contributors. My presumption is, N amount collected in M month is split 50/50, and sent out, however, it doesn't seem to be processed that way.

I looked back 18 months and noticed some months collect money, but no transactions are generated. For instance, Dec 2017 & May 2017, the most recent. What a person earns in M month, let's say Z amount, isn't always what's paid in the transaction log. It appears to "build up" over time, and is sometimes paid a month or more down the road. This is why none of my payments added up to what was on the page, per-month. I checked some other recipients as well. I am to believe this is supposed to be due to the fees, but they're not found in the underpaid report--I wasn't in any underpaid report.
