### ISSUE TITLE
Sorting in Legacy search / Favourite is no more by distance/nearest first

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#5524]
Sorting in Legacy search / Favourite is no more by distance/nearest first which was was until a few days. 
Now it is by name.
It should be as it was by distance / nearest, because it refers to a position selected on top line.
Thanks Peter
Version 3.0.0#25001

![screenshot_20180531-100518 01](https://user-images.githubusercontent.com/18628183/40770532-38e63682-64bb-11e8-9446-1d3578e1e874.png)

**Comment by guerda** [comment]
Fully agree. In addition to that: The list of favorites could also be sorted by distance. My use case is getting around and finding my favorites in the distance. Usually I don't want to go to the fancy restaurant I visited in my last vacation which is 6000 km away.
Maybe that's possible?
Thanks for considering this.

**Comment by jfburke3** [comment]
Personally, I think it should be selectable (e.g., a drop-down menu on the search screen) to sort by distance or name.  There are times I want one, and times I want the other.

/NiceToHave

**Comment by WallKit0** [comment]
If legacy search is gone, is this still relevant? Did I miss something?
