### ISSUE TITLE
3rd party plugin

### ISSUE THREAD

**Issue by Yditquoilui** [osmandapp/Osmand#5525]
I'm working on a plugin for OsmAnd+ on Android, I'd like to be able to load it without necessity of repackaging.
Is it possible to create a 3rd party plugin as mentioned here #2173, without having to modify too much of the code and make updates too complex?

Also, will it eventually be implemented?

**Comment by vshcherb** [comment]
Probably you can use OsmAnd API otherwise there is no such mechanism.
