### ISSUE TITLE
First time route calculation peculiarities

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#5529]
We have old, separate issues for this, but let me consolidate under a new aspect, maybe it helps solving these:

Exactly, and only, after each app start, when you first start a route calculation, the following behavior occurs:
- No matter how long ago the app start happened, the beginning of the actual route calculation seems delayed, as if something is initializing then. This may not be very apparent on fast devices but, will easily cause a 15+ seconds or so pause on some mid grade or slower hardware. (We recently mitigate this by showing a 5% generic progress in the progress bar.)
- If (at the same time, or subsequently) the "GO" button is tapped, i.e. navigation is started in "Follow" mode, the big arrow widget (direction for the first segment/turn) in the top left corner of the map screen does display the distance ok, but the arrow itself is missing (until after the first turn is completed).

The 2 effects may be connected, not sure. What they definitely seem to have in common is that they (100% reproducibly) appear only for the first route calculation (respectively navigation) after each app start, after that they are reliably gone.

**Comment by sonora** [comment]
By more testing with different devices I have found newer hardware (Android 6.0.1) which does not always seem to  produce the 'missing arrow' issue at the first navigation attempt, and an Android 7.0 device which has never shown the issue yet, while the behavior seems 100% reproducible on Android 4.4.2. This may be a tough one to kill with so little reproducability across devices...

**Comment by vshcherb** [comment]
Possibly I need to close that issue cause it is a known issue. Definitely there is a delay and tons of initialization, possibly more than for maps. Though it is very important to know start/end before any init process should start.

Following statistics 90% of starts people don't use navigation, so I don't think we are going to improve something here. 

P.S. you can think that all headers need for map rendering are not used at all, cause routing has completely separate data section.
