### ISSUE TITLE
Invalid street lookup when "selecting" a way for more information

### ISSUE THREAD

**Issue by rich123** [osmandapp/Osmand#5532]
What version of OsmAnd are you using, on what device and Android/iOS version?

OsmAnd 3.0.2 - installed via F-Droid, Android 7.1.1.

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

Offline download maps.

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

United States of America Virginia Apr. 30, 2018.

See this image:
![image1](https://user-images.githubusercontent.com/305956/40860811-c26e72da-65b4-11e8-995b-81da13df85b5.png)

Note the way in the center for "Safeway (3713)"  The house number displayed is correct.

Now, if I 'select' the icon in the center of the Safeway "way", and pull up the details, I get this image below:

![image2](https://user-images.githubusercontent.com/305956/40860881-ecba0edc-65b4-11e8-8478-9b675b26f3a5.png)

Note that the reported street for the Safeway is "North Oakland Street".

Now, if one goes to OSM and opens the "way", using the OSM URL provided by OsmAnd in the above screen shot, one finds this data below:

![way-144376874](https://user-images.githubusercontent.com/305956/40860912-10654ca2-65b5-11e8-8154-49300d7dcfdc.png)

Note here that the Safeway "way" has an "addr:street" tag, but the value of the tag is "Lee Highway".

Why did OsmAnd report "North Oakland Street" as the street address for this way when the way itself is tagged with a street address value of "Lee Highway"?

**Comment by OpenSourceForEver** [comment]
Maybe this issue is similar to:
https://github.com/osmandapp/Osmand/issues/5065

**Comment by vshcherb** [comment]
I think those are interrelated. It's not clear if the issue will have a quick fix or not cause the POI information doesn't store any link to addr:street today and it uses algorithm to determine current location address just from location.

Though here the main issue that building is not registered in the address data at all, so it is impossible to search it by the housenumber, possibly it is related that it is building=retail.
