### ISSUE TITLE
Apps seems to intermittently lose GPS

### ISSUE THREAD

**Issue by mvdwege** [osmandapp/Osmand#5535]
Since the 2018-05-26 update the app is showing an intermittent loss of position with an interval of 1-2 seconds. The current position dot/arrow will disappear and be replaced by the grey 'no position' dot. Any widgets dependent on an active GPS signal disappear too, leading to an irritating 'blinking' effect.

I have checked with other GPS using apps, and they work fine.

Device is a Blackview BV8000Pro, Android 7.0

**Comment by Nick-Tallguy** [comment]
Other comments are on https://groups.google.com/forum/#!topic/osmand/IJbCpWYXvkg

I'm now on Osmand+ 3.0.3 released 2016-06-02 and the problem still exists.

**Comment by sonora** [comment]
Seems to affect certain systems only - have tried an Android 4.4.2, 6.0.1, and 7.0 device, and could not reproduce.

**Comment by Nick-Tallguy** [comment]
My wife's phone is a Samsung Galaxy A5, Android 7 and she is currently on version 3.02, and her phone is working as expected.

My phone is a Ulefone Armor 2, also running Android 7, but versions 3.02 & 3.03 each produce the annoying intermittent gps. 

Looking at the specs for the Ulefone and Blackview, they have similarities - each is using 4x2.6GHz ARM Cortex-A53, 4x1.6GHz ARM Cortex-A53, Cores: 8    I don't know about the phones for the other reports.

**Comment by naoliv** [comment]
Maybe some error/warning can be seen with logcat?

**Comment by mvdwege** [comment]
It seems Nick found the commonality: Both the Blackview BV8000Pro and the Ulefone Armor 2 run on a MediaTek Helio P25 chipset.

**Comment by mvdwege** [comment]
It's a lot of output for only a couple of seconds, but here's the output of logcat | grep -i gps.


[bv8000.txt](https://github.com/osmandapp/Osmand/files/2065739/bv8000.txt)

**Comment by vshcherb** [comment]
```
06-03 09:23:03.483   486   754 W MNLD    : main_event_hdlr: GPS2MAIN_EVENT_UPDATE_LOCATION  lat=52.063587 lng=4.329472 acc=4.200000
06-03 09:23:04.465   486 31622 E mpe     : mtk_gps_mnl_trigger_mpe: [MNL2MPE]Send to MPE failed, No such file or directory
06-03 09:23:04.478   486 31622 E mpe     : mtk_gps_mnl_trigger_mpe: [MNL2MPE]Send to MPE failed, No such file or directory
06-03 09:23:04.481  1345  1744 W SettingsInterface: Setting auto_time_gps has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
06-03 09:23:04.485   486   754 W MNLD    : main_event_hdlr: GPS2MAIN_EVENT_UPDATE_LOCATION  lat=52.063587 lng=4.329472 acc=4.200000
06-03 09:23:05.466   486 31622 E mpe     : mtk_gps_mnl_trigger_mpe: [MNL2MPE]Send to MPE failed, No such file or directory
06-03 09:23:05.479   486 31622 E mpe     : mtk_gps_mnl_trigger_mpe: [MNL2MPE]Send to MPE failed, No such file or directory
06-03 09:23:05.482   486   754 W MNLD    : main_event_hdlr: GPS2MAIN_EVENT_UPDATE_LOCATION  lat=52.063587 lng=4.329472 acc=4.300000
06-03 09:23:05.487  1345  1744 W SettingsInterface: Setting auto_time_gps has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
06-03 09:23:06.466   486 31622 E mpe     : mtk_gps_mnl_trigger_mpe: [MNL2MPE]Send to MPE failed, No such file or directory
06-03 09:23:06.479   486 31622 E mpe     : mtk_gps_mnl_trigger_mpe: [MNL2MPE]Send to MPE failed, No such file or directory
06-03 09:23:06.482   486   754 W MNLD    : main_event_hdlr: GPS2MAIN_EVENT_UPDATE_LOCATION  lat=52.063587 lng=4.329472 acc=4.300000
06-03 09:23:06.486  1345  1744 W SettingsInterface: Setting auto_time_gps has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
06-03 09:23:07.467   486 31622 E mpe     : mtk_gps_mnl_trigger_mpe: [MNL2MPE]Send to MPE failed, No such file or directory
06-03 09:23:07.480   486 31622 E mpe     : mtk_gps_mnl_trigger_mpe: [MNL2MPE]Send to MPE failed, No such file or directory
06-03 09:23:07.483   486   754 W MNLD    : main_event_hdlr: GPS2MAIN_EVENT_UPDATE_LOCATION  lat=52.063587 lng=4.329472 acc=4.300000
06-03 09:23:07.483  1345  1744 W SettingsInterface: Setting auto_time_gps has moved from 
```
Logs from file
Indeed there were some changes with GPS actually fixing a problem that GPS was lost after 20 seconds. Let's investigate

**Comment by vshcherb** [comment]
Actually according to the code we have location to become stale only after 2 minutes
LOCATION_TIMEOUT_TO_BE_STALE = 1000 * 60 * 2; // 2 minutes

So primarily I suspect that "Time from GPS" is completely different then "Current time", though I would like to understand what has changed so far

**Comment by vshcherb** [comment]
Please check it nightly and we will try  to plan for a new release

**Comment by sonora** [comment]
Victor, good thinking, a commit worth testing! :)

**Comment by mvdwege** [comment]
Hi,
I would love to check the nightly (if this was addressed to me), but I
have no idea how.
Regards,
Mart

**Comment by vshcherb** [comment]
This one to download & install http://download.osmand.net/latest-night-build/OsmAnd-default.apk

**Comment by mvdwege** [comment]
Yes, that works.

It's looking for maps in the wrong location, so it's a blank screen,
but the position arrow is solid blue and does not blink anymore.

Mart

**Comment by Nick-Tallguy** [comment]
Hi & thanks for your work on this.

I've installed the nightly build, altered the settings, and as far as I can see everything is performing perfectly. I'll be using the app for long periods of time tomorrow, and will update if I find any problems, but so far everything is perfect.

Thanks again.
