### ISSUE TITLE
Context menu related NPE

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#5536]
Not sure how to reproduce, got this  immediately after tapping the device's back button to hide a context menu for a POI tapped on the map (nightly of May 31, design build with no context related deviations).
[exception.log.txt](https://github.com/osmandapp/Osmand/files/2065083/exception.log.txt)

**Comment by vshcherb** [comment]
Let's see if we've get it reproducing or more requests. The stacktrace doesn't obviously explain the issue.

**Comment by sonora** [comment]
Could not reproduce ever since. I think it happened some time after changing the display language for some testing, so it may possibly not be a mainstream issue.

**Comment by vshcherb** [comment]
let's keep it closed for a while
