### ISSUE TITLE
GPX import folder

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#5537]
Is it on purpose or an oversight that some of our import mechanisms (like importing a file from the GPX file / 'Tracks' tab) import them to the tracks root folder, while other mechanisms (like tapping a file in an external file manager) import them to the 'tracks/import' subfolder?

**Comment by vshcherb** [comment]
I think it is on purpose cause here it is not an "Import" action rather than "add".
Main reason behind creating an import folder, so person won't put too many files accidentally into the root and not mix with more important tracks. 

So in my humble opinion it does seem logical to me

**Comment by sonora** [comment]
Yes, I can live with it, too. Just wanted to point this one out, as I am testing a lot of GPX related functionality lately, it may be one of the next strategic areas for the app.
- If you want we can close the issue.
- Potentially we can unify all import/add operations to always target the import subfolder, I guess.
