### ISSUE TITLE
Wrong MyPosition icon displayed on larger devices

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#5538]
This is an old issue, no regression: It looks like all my larger screen devices (5 inch and up) never display "MyPosition" on the map screen **at rest** with the correct 'circle' type icon (`map_default/car/bicycle/etc._location.png` ). Instead the 'moving' (i.e. directional arrow) icon (`_bearing.png` variant) is always displayed, continuously pointing straight north while at rest.
- Both day and night mode map views are affected,
- and all app profiles.
- The only exception is stale (lost) positions, which are correctly indicated via the gray dots, i.e. the variants of `_location_lost.png`
- I have never seen the issue on a 4.5 inch or smaller screen device.

**Comment by sonora** [comment]
Looks like this was not fixed via #5892. I still see the blue arrow position pointing straight north when at rest instead of the small blue position disk, on all my larger devices of 5 inch and up.

**Comment by AlexSyt** [comment]
Hi. This isn't the bug, if location isn't outdated and has bearing - bearing icon is shown.
https://github.com/osmandapp/Osmand/blob/b1961ac6a694f1e251dc2c137ca078026e4f7ad1/OsmAnd/src/net/osmand/plus/views/PointLocationLayer.java#L126-L135

**Comment by vshcherb** [comment]
@sonora please check the icon, if the icon name is map_* then it is not a problem of large vs small device and it is something either by design or another issue.

**Comment by sonora** [comment]
Alexander, Victor, yes, I agree, it may not be an icon issue after all, may be some other bug in our code perhaps in connection with how hasBearing is reported on some devices.

Behavior is like this:
 - On **all** devices I observe this on, which includes 2 different generation 7 inch Samsung tablets and the Samsung XCover 4 (5 in), I do **never** see the regular "Position at rest" icons (except the grey outdated version), not in any app profile.
 -  Instead, while the device is at rest, the blue "moving" icon is shown floating around with fluctuating bearing is shown as usual while the device is obtaining a better fix and the position still "floats" randomly. But then as soon as the position is stable, the same blue "moving" position arrow remains visible and now always points towards the map's north, regardless of how the device is held and how the map orientation is set.

So whatever it is, what is being displayed on those devices is not the "last remembered" bearing, but bearing 0 as soon as GPS reports "at rest". Again, the devices displaying this have always shown this behavior (in some cases since years ago), so this is not a regression, but something we have always had.
