### ISSUE TITLE
Bus route shown incorrectly when separate relations are used for forward and back routes

### ISSUE THREAD

**Issue by njohnston** [osmandapp/Osmand#5540]
Recently I noticed a problem with how OsmAnd shows bus route 167 in Singapore. The route runs north-south, and there are some differences between the [southerly route](https://www.openstreetmap.org/relation/1154918) (Svc 167 (Sembawang Interchange => Bukit Merah Interchange)) and the [northerly route](https://www.openstreetmap.org/relation/6622979) (Svc 167 (Bukit Merah Interchange => Sembawang Interchange)).

One difference is around Plaza Singapura and Dhoby Ghaut station. The southbound route travels east along Orchard Road, which is one way. The northbound route travels west along Penang Road (one way), slightly to the south:

![bus_route_issue_1](https://user-images.githubusercontent.com/638458/40888110-4bc95d9c-674a-11e8-90a2-bcf8a610d9f1.png)

If I select the [bus stop on Penang Road](https://www.openstreetmap.org/node/410471106) and then select route 167, the route is shown correctly.

However, if I select the [bus stop on Orchard Road](https://www.openstreetmap.org/node/410468328), which is in the correct [north-south relation](https://www.openstreetmap.org/relation/1154918), the northerly route is shown instead (note how the route is shown on Penang Road when it should be on Orchard Road):

![bus_route_issue_2](https://user-images.githubusercontent.com/638458/40888157-df9b422e-674a-11e8-9c81-246311ff9f19.jpg)

The bus routes seem correctly mapped, but I don't know much about public transport mapping. Some routes have a relation for the route, and then relations for each direction, which this one is lacking, so I wonder if that's part of the problem.

I'm using OsmAnd 2.9.3 on a Samsung Galaxy S8+ running Android 7.0, with Singapore map from 1st May 2018.

**Comment by OpenSourceForEver** [comment]
Some problems with transport stops were solved with Osmand 3.0 however there is still a problem to solve. Where 2 routes with the same "ref" tag  coincide in the same stop only one route is shown (for example 2 directions or different variants of the same route coincide in the same bus stop).

**Comment by miklcct** [comment]
Reproduceable on locations where multiple variants of route using the same ref share a same stop.

**Comment by OpenSourceForEver** [comment]
I think this is fixed with #5831

**Comment by miklcct** [comment]
How about the problem of both directions on the SAME platform?

**Comment by OpenSourceForEver** [comment]
I have tested it and I think it is solved. It would be better if someone else could tested it

**Comment by vshcherb** [comment]
It should be solved we have several fixes in that area. 
>> both directions on the SAME platform?
The both should be displayed
