### ISSUE TITLE
Fiat Currency Donation?

### ISSUE THREAD

**Issue by ADepic** [osmandapp/Osmand#5542]
Can I not donate to osmand through something such as paypal or just normal credit card?
Do I have to use the environmental disaster that is bitcoin that costs $10 just to transact?

I want to donate quite a high amount to the osmand team but currently there is no way of doing that...

**Comment by sonora** [comment]
@vshcherb

**Comment by vshcherb** [comment]
Likely we should be registered as non-commercial organization and deal with papers to accept direct donations. 
As of today we will need to create special invoice to deal with it and it could be done so far between business entities. So it is definitely not a public option.

**Comment by tuxayo** [comment]
> Likely we should be registered as non-commercial organization and deal with papers to accept direct donations.

You can sell the app and OsmAnd Live subscriptions but take donations?

**Comment by vshcherb** [comment]
Selling the app is a standard procedure where the VAT and other required operations are handled by Google Play for instance. 
Donation is a different procedure from Tax Authorities and requires special treatment, so far we didn't  see much interest in donation to deal with it.
