### ISSUE TITLE
Can't edit bus stop nodes

### ISSUE THREAD

**Issue by contrapunctus-1** [osmandapp/Osmand#5543]
v.3.0.2 from F-Droid

1. Tap on bus stop node
2. 'Actions'

I expect to see a 'modify POI'. Instead I see a 'Create POI', and nothing to modify it.

Nodes I've observed this with -
geo:28.51366,77.23496?z=18
geo:28.516083,77.22498?z=18

It didn't occur with e.g. this toilet -
geo:28.515839,77.22644?z=18 

Edit - it also seems that OsmAnd no longer displays whether a bus stop has a shelter, tactile paving, and benches. Is this intentional?

**Comment by crimean** [comment]
Fixed by https://github.com/osmandapp/Osmand/commit/6854d9e69059bee98c2aa9fbe69fc9999b2ec9b6
