### ISSUE TITLE
Problem with voice

### ISSUE THREAD

**Issue by ask34** [osmandapp/Osmand#5545]
Because I don't want to post the topic twice, below in German.

Hello, I hope I'm right here in the forum.
I have had a problem with OsmAnd since updating to LineageOS 15.1.

I am using OsmAnd+ 3.0.3 and have Android 8.1.0 (LineageOS 15.1).
But I'm not sure if the problem is caused by OsmAnd or LineageOS.

In the German TTS there are errors in the voice output. For example, "Vier eins" is said instead of "Einundvierzig". 
The problem also exists with the English TTS voice output: e.g. "Eight Five Zero" instead of "eight hundred fifty".

Thanks for all the helpful answers.
(Translated with www.DeepL.com/Translator)

---German---
Hallo, ich hoffe ich bin hier richtig im Forum.
Ich habe ein Problem mit OsmAnd, seitdem ich auf LineageOS 15.1 geupdated habe.

Ich benutze OsmAnd+ 3.0.3 und habe Android 8.1.0 (LineageOS 15.1).
Ich bin mir aber nicht sicher, ob das Problem mit OsmAnd oder LineageOS zu tun hat.

In der deutschen TTS gibt es Fehler bei der Sprachausgabe. Bsp. wird "Vier Eins" statt "Einundvierzig" gesagt. 
Das Problem besteht auch bei der englischen TTS-Sprachausgabe: bspw. "Eight Five Zero" statt "eight hundred fifty".

Danke für alle hilfreichen Antworten.

**Comment by sonora** [comment]
Thanks for reporting. Unfortunately you do no specify in which voice prompt you observe the behavior, but I doubt anyway we can influence this much in OsmAnd. How things are pronounced is largely a matter of the TTS voice engine you use. You may want to use different ones (some devices have several built-in ones, and you can also install more) to find out and investigate.

Most engines I have come across will actually speak series of digits like a number, i.e. you would hear "1234" as "one thousand two hundred thirty four", while separated series like  "1 2 3 4" may sound as "one two three four". 

Please note hat the task is tricky in general, and sometimes even depends on regional preferences: Little doubt that a "100" speed limit should probably read as "speed limit one hundred", but for 120 you would find many people preferring the shortened "one twenty" over "one hundred and twenty," and there is hardly anybody in LA not calling I-405 the "four oh five freeway". A daunting task for TTS engines to know .... :)
