### ISSUE TITLE
Roundabout: Exit Numbering

### ISSUE THREAD

**Issue by bitboy85** [osmandapp/Osmand#5550]
Hi,

in the german osm Forum was an issue dicussed today.
In some special cases the Exit numbering of roundabouts is wrong because there is a footway linked to it.
See here for an example: https://www.openstreetmap.org/directions?engine=graphhopper_foot&route=54.51493%2C13.64070%3B54.51474%2C13.63964#map=19/54.51468/13.64043
In car Routing those ways should not Count but Count in foot routing.

**Comment by vshcherb** [comment]
Yes they should not be count, we don't count roads that are not accessible for the vehicle.
