### ISSUE TITLE
Bus routes listed on a bus stop barely legible in dark mode

### ISSUE THREAD

**Issue by ADepic** [osmandapp/Osmand#5556]
Bus routes are sometime barely legible in dark mode:
![screenshot_osmand _20180608-221257](https://user-images.githubusercontent.com/24532838/41192535-c9035288-6bee-11e8-997d-fd043fc12398.png)
This happens because in dark mode, the background colour switches to it's opposite colour. For example, if the colour of the route is dark purple in light mode, it will be light pink in dark mode. However, in light mode the background colours are made to contrast white coloured text.

But when we change to dark mode, the text stays white (which does not contrast with the now very light background colours.)
![screenshot_osmand _20180608-221325](https://user-images.githubusercontent.com/24532838/41192557-1eade20c-6bef-11e8-88cc-3c26ed049262.png)
My proposed solution is to turn the text black in dark mode

**Comment by xmd5a2** [comment]
Duplicate https://github.com/osmandapp/Osmand/issues/5539

**Comment by ADepic** [comment]
Thanks for pointing out that thread
