### ISSUE TITLE
Instalation forces restart in Android 6.0

### ISSUE THREAD

**Issue by EmmanuelMess** [osmandapp/Osmand#5557]
Don't know if this should be here or FDroid.

Android: 6.0
Phone: Moto E Gen 2 4G
Osmand version: 2.9.3

To replicate:

0. Have version 2.9.3
1. Try to update to 3.0.0 or 3.0.2 via FDroid

Now, installation will go either of 3 ways:
1. It will fail with "package analysis failed"
2. FDroid will stop running 
3. App will start installing and then the screen goes black and phone restarts

**Comment by sonora** [comment]
I think you are periencing this issud https://github.com/osmandapp/Osmand/issues/5505 , a compiler issue affecting some versions of Android,  which was solved by falling back to an older version, but only with release 3.0.3.

**Comment by EmmanuelMess** [comment]
Ok, I made a mistake when writing the issue, the failing version is 3.0.3 (not 3.0.2), really sorry, thanks for your time.
Will read issue #5505 and ask for reopening if necessary.
