### ISSUE TITLE
Different routing using location and start point

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#5559]
Setting the start point calculates a different result than the route from the location.

https://osmand.net/go?lat=59.71859&lon=30.085157&z=18

![image](https://user-images.githubusercontent.com/20681525/41217179-bec7c976-6d5f-11e8-8af1-a28260fe5547.png)
![image](https://user-images.githubusercontent.com/20681525/41217184-c30eceda-6d5f-11e8-95e0-701edc011542.png)

**Comment by scaidermern** [comment]
Maybe because the manual start point doesn't have direction information whereas the current location needs a u-turn to take the other route?

**Comment by vshcherb** [comment]
@scaidermern is right. Direction takes priority and it is important to keep it for auto-route recalculation
