### ISSUE TITLE
Bad OsmAnd performance on Huawei p10 plus (Android 8)

### ISSUE THREAD

**Issue by Aiurek** [osmandapp/Osmand#5565]
Huawei p10 plus, Android 8.0.0
OsmAnd 3.0.3, released 2018-06-02

A friend told and showed me that it's almost impossible to use Osmand on his new, above mentioned phone due to severe lags when scrolling and zooming the map. Is there still a general issue with Android 8 or might this be a phone-specific issue?

**Comment by vshcherb** [comment]
It is a duplicate issue and it is an Android issue. There was a fix already in Android Core but unfortunately it didn't reach some devices yet. 
You can't say exactly which build is fixing cause some devices on Android 8.0 have already fixed.
https://github.com/osmandapp/Osmand/issues/4323
