### ISSUE TITLE
Please revert wording from "trespass private roads" back to "allow access to private roads"

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#5566]
What version of OsmAnd are you using, on what device and Android/iOS version?

OsmAnd+ 3.0.3, released 2018-06-02, Samsung Galaxy S5, Android 5.0.

Previous versions of OsmAnd would prompt the user to "allow access to private roads" when the destination required traveling on a road with access=private (or possibly also when it was necessary to pass through a gate that was access=private).  Apparently the wording has been changed to "trespass private roads."  Please consider changing this back to the earlier wording.  The English word "trespass" means to enter property without permission, and carries with it the strong connotation of an illegal act (the crime of "criminal trespass" is in the law of every U.S. state, for example).  The earlier wording was "nicer" and didn't make the user think he would be breaking the law :-) .

**Comment by IByte** [comment]
I was going to report this, but it's already here. Unfortunately, it doesn't appear to have landed on the release branch yet (I have v3.0.4, released 2018-06-11). I guess I'll just have to wait.

The word "trespass" does indeed imply performing an illegal act. But it's my own driveway! Yes, it should be marked "private" on the map, and no, I am not trespassing.

Kudos for having fixed this quickly.

**Comment by jfburke3** [comment]
Hi @IByte !  Glad to have another person mentioning this. 

No, it hasn't shown up in any of the public beta/official releases.  But, I can confirm that it has been changed in the nightly development builds, so the next public release will have the correction.

And I'll make a note that I've been very impressed that the developers have responded to feedback about English language issues on the few occasions where I've mentioned it.  (Thank you @vshcherb and your team!)
