### ISSUE TITLE
Ascend and descend looks wrong

### ISSUE THREAD

**Issue by Sixtron** [osmandapp/OsmAnd#5568]
Osmand+ 3.0.4
Android 6.0.1
Offline vector map
bike routing
Location Lat 51.28419 Lon 7.25069

When calculating a route it shows ascend and descend on a totally flat bicycle way that
was before a railway. The problem is maybe that the surroundings ascend and
descent is true, but the street is flat inside the environment.
This looks like a terrible way for driving bicycle but in real it's a perfect way.
I would prever an average line for ascent and descent instead of this spikes.

![1](https://user-images.githubusercontent.com/29046323/41349474-388b9fec-6f10-11e8-82dd-6726e812e58c.png)
![2](https://user-images.githubusercontent.com/29046323/41349482-42ebb13e-6f10-11e8-9c38-7025d8111c54.png)
The way look's so the whole time:
![img_20180613_170205-1024x1820](https://user-images.githubusercontent.com/29046323/41369107-36c80b9e-6f44-11e8-9cfb-5c7248f3f1fb.jpg)

The same area in Google Maps:

![img_20180614_092432-1024x640](https://user-images.githubusercontent.com/29046323/41397818-a8707f26-6fb5-11e8-93f2-4a3b40e36626.jpg)
![img_20180614_092507-1024x634](https://user-images.githubusercontent.com/29046323/41397819-a899bdbe-6fb5-11e8-9f77-fae7506e7baf.jpg)

To make it complete the recorded gpx track:

![screenshot_2018-06-14-10-47-06-324_net osmand plus-768x1365](https://user-images.githubusercontent.com/29046323/41401979-733aeeb6-6fc1-11e8-805d-85c38fed160b.png)

This has not much to do with the pre calculated ascend and descend.

**Comment by sonora** [comment]
But look at the amplitudes! We are talking +-10 m or so in the examples you show. I hardly believe we can expect more accuracy from the global data we use...

**Comment by Sixtron** [comment]
I have added Google Maps ascend and descend. They can handle it nice.

**Comment by scaidermern** [comment]
With some smoothing the height profile from OsmAnd would look quite similar I guess. Unsure if this is a good idea though. Maybe add a button to switch between raw data and a smoother version.

**Comment by vshcherb** [comment]
Recorded track looks much smoother even than Google Maps Data. Obviously Google Maps has access to more detailed data. Unfortunately we could  investigate whether it is data (we're Aster SRTM data) noise or algorithms. 
The investigation could take a while and still don't bring any result.  Let's see.

**Comment by erik55** [comment]
We need Tandem-X data!! :-) https://en.wikipedia.org/wiki/TanDEM-X
Smoothing is not a good idea. When you use the map, you notice quite quickly, that the height data is not that accurate and smooth it in your mind.

**Comment by xmd5a2** [comment]
With current elevation data it looks like adequate graph to me. Spikes are only at tunnels or intersections with primary roads.
![Screenshot_2022-06-23-11-26-16-739_net osmand plus](https://user-images.githubusercontent.com/5829014/175254200-659e966c-ff01-475d-94bc-a6804dac65e0.jpg)
