### ISSUE TITLE
POI hard to click/select

### ISSUE THREAD

**Issue by ceever** [osmandapp/Osmand#5572]
When trying to click a visible Point of Interest (POI) (the ones introduced just a few versions ago and that can be hidden from the map using the setting) to receive more information (name, etc.), often the focus is not set on that POI, but instead the functional buttons disappear from the map as if I would not have tapped the POI exactly. This happens very often and is quite frustrating. Maybe the threshold to accept taps near a POI as an intended POI tap should be lowered.

**Comment by vshcherb** [comment]
Please specify the screen size (phone) and if possible send screenshot to illustrate what is the area.

**Comment by ceever** [comment]
This issue does not seem to exist in the 3.xxx version anymore.

My screen is 4.7" and attached a screenshot of my screen.

![screen](https://user-images.githubusercontent.com/40247591/41768907-e3bfffb2-760d-11e8-9a33-e99c89081798.png)

**Comment by vshcherb** [comment]
Thanks for feedback let's watch it if it comes back
