### ISSUE TITLE
Zoom buttons loose additional functionality

### ISSUE THREAD

**Issue by ceever** [osmandapp/Osmand#5573]
If a Point of Interest is selected and the zoom buttons have moved up, it is not possible to set the zoom level/magnification from the zoom buttons anymore (by long press).

**Comment by vshcherb** [comment]
We are going to disable or limit that functionality for base map as well. Zoom magnifier is not the feature to be changed very often

**Comment by ceever** [comment]
I beg the differ. I often change the zoom level between cities and countryside. Having this feature in the zoom buttons, is really helpful, instead in the menu at the very bottom.
