### ISSUE TITLE
Zoom level/magnification different, depending on way of setting

### ISSUE THREAD

**Issue by ceever** [osmandapp/Osmand#5574]
The zoom level/magnification set from the zoom button (by long press) supports values as low as 20%. However, the values settable through the regular menu only 33%. This is kind of inconsistent.

**Comment by ceever** [comment]
Attached 4 screenshots to show the difference.

![screen - zoom buttons](https://user-images.githubusercontent.com/40247591/41769094-79873196-760e-11e8-878f-2cc180b74be6.png)
![screen - zoom buttons - behaviour](https://user-images.githubusercontent.com/40247591/41769095-79a6a0b2-760e-11e8-94af-a825a7a0c22a.png)
![settings - map magnifier](https://user-images.githubusercontent.com/40247591/41769096-79c64ce6-760e-11e8-8581-be65e8cf5de6.png)
![settings - map magnifier - behaviour](https://user-images.githubusercontent.com/40247591/41769097-79f39a7a-760e-11e8-81a2-8982b723aed7.png)

**Comment by sonora** [comment]
Aligned, thanks for pointing this out.

Also added 125% to the scale, a value some users requested for small devices.
