### ISSUE TITLE
Usability: Fix the 'Select on map' Start/End Point Selection

### ISSUE THREAD

**Issue by ceever** [osmandapp/Osmand#5575]
When I use the navigation, I often use it to determine how long a future track would take. Hence, I select a destination, but since the starting point is often not my current location, I continue trying to change the starting point via "select on map". However, your app already started calculating the route and is often quite fast in figuring it out, after which it automatically zooms out. This is a little annoying and hindering because while looking for the actual future starting point of this route, I get forcefully interrupted by this automatic zoom-out. I do not know how other people are using the navigation, but maybe it is a general issue for many.

**Comment by vshcherb** [comment]
It could be an issue, we will try to think how to avoid it or put something smarter in this zoom out.

**Comment by sonora** [comment]
Often observed this myself. I guess pausing the route calculation after the user tapped 'Select on map' and before the user actually tapped a point on the map would solve the issue.

**Comment by ceever** [comment]
This sound very reasonable and would be a great improvement.

**Comment by AlexSyt** [comment]
Now automatic zoom-out will happen only if app is not in "select on map" mode.
