### ISSUE TITLE
Ferry route not being taken in account properly in routing

### ISSUE THREAD

**Issue by IgorEliezer** [osmandapp/OsmAnd#5581]
OsmAnd 3.0.0 r21521d Android

In short: while OsmAnd does use a ferry route for routing, it doesn't take in account `duration` nor does it list it in the route details.

### Example and testing

https://www.openstreetmap.org/way/199126828, the relevant data are `name=Balsa Santos - Guarujá` and `duration = 00:10`, it supports `foot`, `bicycle` and `motor_vehicle`. The region is `Brazil - sao paulo southamerica`.

I created a route between this pedestrian crossing (https://www.openstreetmap.org/node/4715104715) and this node (https://www.openstreetmap.org/node/3622807322), it can be on any mode.

### The result

![image](https://user-images.githubusercontent.com/4673289/41420066-00807fa4-6fca-11e8-8790-06edb77933e3.png)
As you can see here, OsmAnd says the route would take 2 minutes by car (and if you wanna try: 9 min by bicycle, and 7 min on foot) but the ferry route itself is 10 minutes.

Now the route details: tap on "Distance/Time" panel to see the route details.

![image](https://user-images.githubusercontent.com/4673289/41420102-1c4b949e-6fca-11e8-92de-16f100f0596e.png)

Here I would expect something like ":ferry: 380 m / 0:10 | #. Take _Balsa Santos - Guarujá_ ferry" between the direction 2 and 3. Perhaps the direction 2 should be split into 3 parts: "Turn right and go" (57 m), "Take the {name} ferry" (380 m) and "Leave the ferry and head {highway name}" (187 m). (Edit: it is also ignoring the highway name ["Avenida Ademar de Barros"](https://www.openstreetmap.org/way/48452408) after leaving the ferry route)

Also using < > doesn't list the said ferry route. At least the distance is included in the direction 2 so the _Total distance_ is correct.

(In case you want another example: https://www.openstreetmap.org/way/203890192 the issue is the same.)

Regards,
Igor

**Comment by vshcherb** [comment]
Moved to #5815
