### ISSUE TITLE
Numeric/elevation data missing in travel guide articles

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#5582]
See e.g.the article about the Black Forest, quote:

> The Black Forest is a mountainous terrain at about above sea level, the highest point being the Feldberg (the field mountain) at .

**Comment by njohnston** [comment]
I looked at the Wikivoyage SQLite file, and the elevation is missing in there too. From looking at the source Mediawiki markup, it appears that such numbers can be marked up specially:

```
mountainous terrain at about {{m|200-1500}} above sea level, the highest point
being the ''Feldberg'' (the ''field mountain'') at {{m|1493}}
```

This suggests that OsmAnd's conversion code isn't handling this particular macro correctly. [This method](https://github.com/osmandapp/OsmAnd-tools/blob/e724cb0966e9cc47645d5e8def412211d9a7b0d5/java-tools/WikipediaConverter/src/main/java/net/osmand/osm/util/WikiDatabasePreparation.java#L105) could be the problem.

**Comment by sonora** [comment]
Yes, good research, thanks! Looks like in deed we do not support this macro ok.

**Comment by PaulStets** [comment]
@sonora ```|``` is a special char in regex, so, in order to escape it (to split by this character literally) we need to add an escape character ```\``` and another one to escape the escape character. This is common regex syntax in Java.

As for this particular issue, this data isn't shown because we remove all the text inside the curly braces and then parse them manually. At the moment of the generation, I wasn't aware of this placeholder. I will add it later.

**Comment by sonora** [comment]
Paul, thanks! Yes, I wasn't aware why you had placed two escapes here. Yes, with that being correct then, we need to parse the content correctly. Certainly nothing urgent, just a finding in my testing. Thanks!

**Comment by Evgenij27** [comment]
Fixed with https://github.com/osmandapp/OsmAnd-tools/pull/274

**Comment by njohnston** [comment]
I noticed this problem in Wikipedia data too (using the latest version of Gb_england_europe.wiki.obf from 21st July). Here's an example from the article for [North Hill, Malvern](https://en.wikipedia.org/wiki/North_Hill,_Malvern):

![wikipedia_elevation_issue](https://user-images.githubusercontent.com/638458/43995158-fbf1d33e-9da0-11e8-8116-160c421e2292.jpg)

This article uses a similar type of mark-up to that used in the article which @sonora pointed out:

```
It has an elevation of {{convert|397|m|ft|0}}
```

It converts values in metres to feet and includes the feet figure in parentheses after the value in metres.

Let me know if you'd prefer a new issue for this.
