### ISSUE TITLE
[Feature request] Add Lithuanian voice guidance

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/OsmAnd#5584]
A user requested adding Lithuanian voice guidance.

**Comment by embar-** [comment]
Already implemented and included in OsmAnd app v4.7. See: 
- https://github.com/osmandapp/OsmAnd/issues/19502
- https://github.com/osmandapp/OsmAnd-resources/pull/1061
- https://github.com/osmandapp/OsmAnd-resources/pull/1065
- https://github.com/osmandapp/OsmAnd-resources/pull/1066
Can be closed now.
