### ISSUE TITLE
Error in the UTM coordinates

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#5586]
The coordinates of the screenshot should be 47(96)798 instead of 47(94)798.

![image](https://user-images.githubusercontent.com/20681525/41464004-3decc348-70a1-11e8-9a01-3b2064ee023a.png)

**Comment by Chumva** [comment]
It looks like coordinates were correct, you could check them by this links: 

- link for 47(94)798 - https://www.openstreetmap.org/search?query=43.321294%2C%2045.78988658876131#map=15/43.3213/45.7899&layers=D

- link for 47(96)798-  https://www.openstreetmap.org/search?query=43.303287%2C%2045.78965340945973#map=18/43.30329/45.78966&layers=D
