### ISSUE TITLE
Geo intent bug (size of downloaded map displayed)

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#5591]
If I open a geo intent while OsmAnd is **not running** before, it always displays file size of already downloaded map.

![photo_2018-06-15_18-56-36](https://user-images.githubusercontent.com/6921696/41480270-30ee5864-70ce-11e8-8214-badb8d4aa289.jpg)

This does not happen if OsmAnd is **already running**.

![photo_2018-06-15_18-56-42](https://user-images.githubusercontent.com/6921696/41480278-3c377390-70ce-11e8-8c8a-6407f8db6fd8.jpg)

Found with OsmAnd+ 3.0.4.

**Comment by AlexSyt** [comment]
We cannot reproduce this issue.

**Comment by Rolf558** [comment]
@ did you really close OsmAnd before in task manager?

**Comment by AlexSyt** [comment]
@Rolf558 ,Yes. If you can reproduce it, please provide some instruction. Ideally with location and screenshots)

**Comment by Norbert80** [comment]
Intent is:
geo:47.365600,9.307300?z=15&q=47.365600,9.307300 (Hundwiler Tobel)

Contrary to my initial comment it looks like this bug happens also if OsmAnd is already running in the background. (At least for my other phone.)
