### ISSUE TITLE
Rendering: Water covered by overlay

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#5593]
Have not researched yet, it looks like we sometimes cover water by an overlay when we should not. Example is Lake Garda in Italy_Veneto from zoom 13 and up, when it appears olive green in Default style, or pink in Touring view (may be 'attraction', not sure).

**Comment by xmd5a2** [comment]
Yes, green tint is caused by tourism=attraction. I agree that in this particular case it is not necessary, but in many other cases rendering of tourism=attraction is useful. May be it is better to remove tourism=attraction when used with natural=water in preprocessing?

**Comment by sonora** [comment]
Yes, that may be a solution. If an attraction is just a big lake like this, I guess many people are confused by rendering attraction instead of water... cannot think of a better solution for now either.

**Comment by xmd5a2** [comment]
@sonora Yes you are right. Hopefully it is fixed now

**Comment by sonora** [comment]
Leonid, that should work,  thank you!
