### ISSUE TITLE
Allow edit tags for non-point objects

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#5595]
As of today we can allow to change tags of non-linear objects but not geometry.

**Comment by scaidermern** [comment]
Looks good (in the new beta).

Which tags must be present to allow editing of non-node objects? For example parking spaces can be edited but for places like https://www.openstreetmap.org/way/27763773 there is no edit button available. It is clear that OsmAnd's main purpose is not to be an OSM editor, I'm just asking.

**Comment by scaidermern** [comment]
@AlexSyt / @Chumva

**Comment by Chumva** [comment]
Currently, editing of non-node objects works with type "way" and they must be POI

**Comment by scaidermern** [comment]
Alright, thanks.
