### ISSUE TITLE
Nodes and areas displaying key:note

### ISSUE THREAD

**Issue by IgorEliezer** [osmandapp/Osmand#5596]
According to the [wiki](https://wiki.openstreetmap.org/wiki/Key:note), a note is used to inform other mappers about information about an element. I think it's not meant for the end-user to see.

Place nodes such as `place=suburb` and `place=locality` and `natural=water` are showing `note` value on the POI detail panel even if the "OSM Mapper Assistant" is disabled. Other objects usually don't display `note` values.

Examples: 
* Suburb: [node](https://www.openstreetmap.org/node/5228565029
), [screenshot](https://user-images.githubusercontent.com/4673289/41569986-54390252-7343-11e8-8f5d-ecc8b557d705.png)
* Lake: [area](https://www.openstreetmap.org/way/602285292)
* Ridge: [way](https://www.openstreetmap.org/way/608262774)

**Comment by AlexSyt** [comment]
Now notes will be displayed only if "OSM editing" plugin is enabled
