### ISSUE TITLE
Can't edit Stairs

### ISSUE THREAD

**Issue by mahdi1234** [osmandapp/Osmand#5597]
v.3.0.4 from play store

- Tap on Stairs overlay icon
- Select "Actions"

I expect to see a "Modify POI". Instead I see "Create POI" and nothing to modify it.

I've observed this with e.g. https://www.openstreetmap.org/way/4318377

I know there's limitation to multi-object editing at the moment - #5595 - is this somewhat related or different issue?

**Comment by vshcherb** [comment]
Duplicate #5595
