### ISSUE TITLE
OsmAndMapCreator does not create obf-files any more

### ISSUE THREAD

**Issue by MAlfare** [osmandapp/Osmand#5599]
Hi!
I use a bash-script to generate POI-files for charging stations regularly.
most resent MapCreator is downloaded therein with this line:
wget http://download.osmand.net/latest-night-build/OsmAndMapCreator-main.zip -O ${MAPPER}.zip
As it does not work any more today, I found out, that:

OsmAndMapCreator-2018-06-15.zip
works well,
since
OsmAndMapCreator-2018-06-16.zip
until at least
OsmAndMapCreator-2018-06-21.zip 2018-06-21 13:28 	
do not produce obf-files from osm-files.
(manually downloaded from here: http://download.osmand.net/night-builds/) 

used config-file:
================================================
```
# write_mapper_config_file()
# generate xml setup file
write_mapper_config_file() {
cat > "$POI" << EOF
<?xml version="1.0" encoding="utf-8"?>
<batch_process>
	<process_attributes
		mapZooms=""
		renderingTypesFile=""
		zoomWaySmoothness="2"
		osmDbDialect="sqlite"
		mapDbDialect="sqlite" />

	<process
		directory_for_osm_files="$OSMDIR"
		directory_for_index_files="$OBFDIR"
		directory_for_generation="./Work"
		skipExistingIndexesAt="$OBFDIR"
		indexPOI="true"
		indexRouting="false"
		indexMap="false"
		indexTransport="false"
		indexAddress="false">
	</process>
</batch_process> 
EOF
}
```
================================================

MapCreator started with this:
================================================
```
# finally we're ready to create the obf files
write_mapper_config_file
cd "$MAPPER"

cat <<- EndNote

** Converting osm files to obf.
If you wish to view the output, you can do the following:
tail -f $LOG
EndNote

java \
	-Djava.util.logging.config.file=logging.properties \
	-Xms256M -Xmx2048M \
	-cp "./OsmAndMapCreator.jar:./lib/OsmAnd-core.jar:./lib/*.jar" net.osmand.data.index.IndexBatchCreator "$POI" > "$LOG" 2>&1
```
================================================

Regards
Manfred

**Comment by vshcherb** [comment]
It has changed please use utilities.sh in the zip, there is a help in OsmAndMapCreator but it is definitely easier to  support for us and it was tested already. 
./utilities.sh generate-obf-files-in-batch  <path to batch.xml> <optional path to the file with regions list>: generates multiple obf files with different options

**Comment by MAlfare** [comment]
Hi Victor!
Can you give me a hint, how the options should read for doing the same as what I have/had in my config-file?
To make an obf from an osm, POIs only?

Regards
Manfred

**Comment by vshcherb** [comment]
You need to keep same config-file! Nothing changes wit it. You need to start with 
OsmAndMapCreator/utilities.sh generate-obf-files-in-batch <path-to-your-config>

**Comment by MAlfare** [comment]
Hi Victor!
Thank you for your reply.
But I think, I am too stupid.

Regards
Manfred

**Comment by vshcherb** [comment]
```OsmAndMapCreator/utilities.sh``` this command produces help how to use.
```OsmAndMapCreator/utilities.sh generate-obf-files-in-batch``` will take your config file as parameters and does exactly what it did before.
