### ISSUE TITLE
Inefficient routing (offline)

### ISSUE THREAD

**Issue by ADepic** [osmandapp/Osmand#5612]
Inefficient routing from Tower Ramperts bus station, Ipswich, Suffolk, UK  to Revolution bus stop, Ipswich, Suffolk, UK.
![annotations with osmand error](https://user-images.githubusercontent.com/24532838/41821098-24357fae-77cb-11e8-9907-02d897655091.png)

I don't understand the spike at the bottom. It's taking another road which makes the journey longer for absolutely no reason. Maybe it is some sort of bug in the routing engine?

**Comment by startailcoon** [comment]
This looks like some sort of issue with street access details.

Example on this is the following street that has `Access: motor_wheicles = no`


![image](https://user-images.githubusercontent.com/12114550/41821281-719ae050-77de-11e8-8cbc-a9a3adeab4a7.png)


Why it suggests you to not take Falcon Street isn't clear though.

**Comment by ADepic** [comment]
Nothing seems wrong in the Falcon Road tags--
highway=tertiary
lit=dusk-dawn
maxspeed=20 mph
name=Falcon Street
sidewalk=both

Why is Osmand not routing through falcon road?

But High street has moter_vehicle = no.

That's interesting, because Googlemalware suggests going that way.

But looking at Googlemalware streetview, we can see it says no motor vehicles... So Openstreetmap better???

But as suggested by OSRM, going by Elm Street is more efficient, so I have no idea why graphhopper didn't go that way.

**Comment by ADepic** [comment]
Any updates on this? Another issue, called "Wrong routing" was given a milestone so why not this?

**Comment by prototype99** [comment]
well i tested it, and you only need to tell it to avoid princes street and it will take elm street. going by that i imagine it's either the fact elm street is 20 mph and civic drive is 30 mph so you get a little bit more time in the 'fast lane' OR the fact prince street is listed as a tertiary road so perhaps it uses road classification to aid decisions as well. (or a combination of both). i'm not sure what motivates it to take that sharp detour near the end, if you change the startpoint to stand KK it magically disappears funnily enough.

**Comment by vshcherb** [comment]
The spike is caused by the road which is impossible to achieve by motor vehicle https://www.openstreetmap.org/way/4370754. And the detour is caused by the priorities which are set to prefer higher class roads.
