### ISSUE TITLE
[Suggestion] String translation looks bad on the interface.

### ISSUE THREAD

**Issue by franco999** [osmandapp/Osmand#5615]
In several languages, the translation of the phrase **"Add GPX file"** is very long (along with the phrase _"ok"_ and _"cancel"_) and looks bad on the interface. Instead of **"Add GPX"**, it could be displayed correctly on the interface.
My question is, is it possible to change the original string or does it depend on each translation? (https://github.com/osmandapp/Osmand/blob/master/OsmAnd/res/values/strings.xml#L511)

For example:
Spanish: Bad. (add GPX file)
![es](https://user-images.githubusercontent.com/12088580/41855950-49f324fe-786a-11e8-9cbf-da9595c907b9.jpg) 
Spanish: Good. (add GPX)
![es2](https://user-images.githubusercontent.com/12088580/41855951-4a21e6d6-786a-11e8-9410-3a058ccd29b0.jpg)
German:
![de](https://user-images.githubusercontent.com/12088580/41855949-49c20112-786a-11e8-8da1-a99d5da63db1.jpg)
French:
![fr](https://user-images.githubusercontent.com/12088580/41855952-4a51439a-786a-11e8-8b8b-fa90ea76a432.jpg)
Italian:
![it](https://user-images.githubusercontent.com/12088580/41855953-4a80a57c-786a-11e8-8419-4601a4736daa.jpg)

**Comment by sonora** [comment]
I have changed the string to "Add more…", let's see if that fixes the issue. thx-

**Comment by IgorEliezer** [comment]
I had the same problem with OsmAnd Live → Live Updates, where you find `update_now`, `cancel` and `ok` at the bottom.

If `update_now` button was anything longer than 11 characters all the 3 buttons kept breaking lines and going off screen. I ended up [dropping the "now" part](https://hosted.weblate.org/translate/osmand/main/pt_BR/?type=comments&offset=78#comments) to make the translation shorter. I think buttons should "cut off" long strings to avoid going off screen or breaking lines, but I'm not sure if it's a better approach.

**Comment by dmpr0** [comment]
It is the default behavior of dialogs with 2 or 3 buttons. We support all languages. Our main goal it good understanding of what that button does, how it looks, in one line or in a column not so important.

**Comment by comradekingu** [comment]
"Add more…" seems imprecise.
"+GPX" is nice and short.

**Comment by ldmpub** [comment]
Hi,

I agree with @comradekingu, to make sense the label "GPX" should be part of the sentence in all languages ... Maybe we should think to an other layout for labels / buttons in this dialog box.
