### ISSUE TITLE
Minor bug: live update does not update description

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#5619]
Live update shows description if it is new in a poi, but if it was already present and changed, the tag is not updated.

version 3.0.0#25194

**Comment by vshcherb** [comment]
Closed in favor #6052, now we can deeply test and reproduce

**Comment by pebogufi** [comment]
@vshcherb 
Immedialely after live update, a new description is **not** shown.
After leaving the app and clear cache and restart description is visible.

**Comment by pebogufi** [comment]
sorry I forgot version:
3.2.0#25948
