### ISSUE TITLE
Feature: Working location out on tunnels

### ISSUE THREAD

**Issue by rafacouto** [osmandapp/OsmAnd#562]
It is a little bit annoying when **GPS location is lost in tunnels** and the current position on map becomes freezed until to the end of the tunnel. For example, Osmand does not inform when there is a speed trap in the tunnel or at its end.

I propose an **improvement consisting in to calculate the estimated location** based on speed before entering in the tunnel as a constant and the seconds from the lost of GPS signal.

The current location can be calculated over the main line of the route in the tunnel and **navigation will be usually more comfortable**. User must be informed that he or she is under a tunnel and location is calculated virtually (voice notification and a label titled something like "Under tunnel: estimated position").

**Comment by Tchiller** [comment]
has this been distributed already? At least in not-navigating mode, it is not working OA+ 2.1.1

**Comment by stephan75** [comment]
I can confirm that this feature is working for over one year now, even in the "Elbtunnel" in Hamburg, when in Navigation mode.

About the cruising mode: What is when a tunnel is forking under the earth ... where should Osmand know what direction you proceed?

So I fear: no artificial position when just in cruising mode.

**Comment by Tchiller** [comment]
Fair enough. Thank you for the update, Stephan.

**Comment by reibax-marcus** [comment]
@vshcherb , can you point out what commits resolve this problem? As of OsmAnd+ v4.2.5 the navigation halts at the entrance of tunnels and doesn't resume until gps signal comes back. This results in missed directions and warnings.

**Comment by vshcherb** [comment]
It was 2013, so I don't think it's relevant any more to comment here

**Comment by reibax-marcus** [comment]
We should either re-open this issue, or open a new one then. Which approach is better?

**Comment by vshcherb** [comment]
reopen is not possible for issues of previous release i.e. > than 1 year. Please open new one and add all details you have, is it reproducible with simulation, recorded screenshot or recorded track.
