### ISSUE TITLE
OSM Live Updates Broken? North America Virginia

### ISSUE THREAD

**Issue by tazva** [osmandapp/Osmand#5629]
All of my OSMA+ devices have the same issue: No updated beyond 5/31. I've cleared cache, deleted maps, etc. The only thing which comes up for Virginia map, is up through May 31. One is running version 3.0.4, the others running the previous (2.9 I believe). I've tried different network connections too. 

The files appear to be available here, but I am not able to grab them through live updates: http://download.osmand.net/aosmc/us_virginia_northamerica/?C=M;O=D

I have not tried manual updating, because this is supposed to be a Live Updates system.

**Comment by vshcherb** [comment]
I hope you are updating through UI. We tried to reproduce but so far it looks good updated 1 hour ago. Please send a screenshot how do you check.

**Comment by tazva** [comment]
I open the App. It used to simply auto-download when it detected a new map. It doesn't do that anymore. 

So now I go to Menu -> Download Maps -> Updates, and it says all files are up to date (May/31)

I have verified that live updates are in fact 'turned on' under the OSMA Live Menu.

**Comment by tazva** [comment]
![osmandplus_may31_va_stuck](https://user-images.githubusercontent.com/29614385/42380502-26ecbf7a-80fc-11e8-8c66-4e5754f120ed.PNG)

When I go to download Maps from a new install, this is what shows.

**Comment by tazva** [comment]
For reference, this is happening to my 2.9.3 devices and my 3.0.4 devices.

**Comment by vshcherb** [comment]
To summarize it means, that Automatical download doesn't work and only "Update now" is working.
This is quite strange cause at every app start, it schedules an immediate Live Update.

**Comment by tazva** [comment]
Yes, that is a good summary. Perhaps it's trying to live update but something stops, I can't see. If I have the time I'll capture network traffic on loading up the device to see what's going on. It made me think maybe something was wrong with my OSM Live account, but the fact I can do it through 'update now' makes me think it's something else.

**Comment by tazva** [comment]
On one of my 2.9.3 devices, which I haven't updated in awhile, I looked at it yesterday. It didn't say there were any new updates on bootup. When I went to Download Maps, into the Updates section, it would come up and say that a new monthly map was available (June 30). So it can see that much. I downloaded that.

I then had to go apply the additional differential updtates through the menu. Android hasn't updated on this device at all, and since this is happening on both 2.9x and 3.x versions of OSMA, it's got to be something on the server side right?

**Comment by tazva** [comment]
Just an update, the 2.9.3 device self-updated its maps as it normally should, a couple of days ago. I haven't checked the other devices. On bootup, OSM detected & downloaded new maps.

I'm not saying it's 100% resolved as I haven't tested other devices yet, and there's been no changes since then.
