### ISSUE TITLE
Display of opening_hours with date range is wrong

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#5630]
![screenshot_20180704-081211 01](https://user-images.githubusercontent.com/18628183/42259849-76fbb8f4-7f62-11e8-9130-881e2dad3aea.png)
Date range "May 24 - Nov 04" is shown as "May 1-4, 24-31"
Regards Peter

**Comment by vshcherb** [comment]
I guess we only support May-Nov 04-30 and don't support specified case

**Comment by pebogufi** [comment]
please test syntax with   http://openingh.openstreetmap.de/evaluation_tool/
with example
May-Nov 04-30
it won't work, this date range is not valid.

Make the test with 
May 24 - Nov 04 
or 
May 24 - Nov 04: Mo-Fr,PH 08:00-12:00
which will work.
In german wiki you will find more examples,  like that
    aufeinanderfolgende Tage im Monat getrennt durch "-" · ( z. B.> Dec 20-26 ) oder ( z. B.> Dec 20-Jan 06 )
and 
        ein Bereich von Tagen im Monat geschlossen "mo md-md off" ( z. B.> Dec 24-26 off ) or "mo md — mo md off" ( z. B.> Dec 25-Jan 06 off )

**Comment by vshcherb** [comment]
Closed in favor of #6079
