### ISSUE TITLE
Sharp Right identified as Left U-Turn in routing via GPX track

### ISSUE THREAD

**Issue by gri-ghb** [osmandapp/Osmand#5635]
Hi.
When navigating a track and approaching a U turn I regularly get a turn indication in the wrong direction.
The U turn goes right but is announced as Left.
See Picture below:

![42273379-49a00b40-7f89-11e8-94ca-b9f0b6c8cd3d](https://user-images.githubusercontent.com/845735/42722091-47b8afc0-8746-11e8-818f-6338156c070e.jpg)

Osmand+ 3.0.4
Android 8.0.0
Samsung Galaxy A3 (2017)
Offline Map Germany North Rhine-Westphalia, however this also happened on other (offline) maps (Netherlands).

Thanks, Geert

Before entering an issue, please read the information below.

```GitHub is a main development tool for developers. There are hundreds requests a month and there are only few developers. So by opening an issue, please know that your issue will be sent out to all developers and acknowledge that it could be closed without explanation or with a brief message. Comments on the closed issues are also sent to all developers, so you will definitely will be heard. However, there is no guarantee that a developer will pick up the issue to work on it.```

In case you are not sure to open issue or not, please send your request to support support@osmand.net. For **general questions** about OsmAnd, please use the [Google group](https://groups.google.com/forum/#!forum/osmand).

Please be sure to have read our [FAQ](http://osmand.net/help-online) before creating an issue here. (Also, tell us in Google Groups when the FAQ is wrong or outdated.)

The best way to get help about an OsmAnd issue is to create a valid and detailed issue content.
Please give us the following information so that we can try to **reproduce** your issue:

What version of OsmAnd are you using, on what device and Android/iOS version?

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

__*In case of wrong routing:*__

Tell us whether you have used OsmAnd's in-app offline routing, or any online routing provider like YOURS, OpenRouteService or OSRM.

What routing profile is chosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest)

Please specify as exactly as possible the start and end point of your route by telling us city name and street name so that we can find it via in-app address search easily. Also, a permalink from openstreetmap.org can be helpful.

Tell us your expected routing, and how OsmAnd routes, or add screenshots here.

**Comment by sonora** [comment]
Thanks for reporting! Looks like your screenshot was taken for Germany. For the sake of completeness, could you please report
- What is your setting under Settings/Driving region?
- For this route, was it simply calculated using a destination or also using a GPX track file?
Thx!

**Comment by gri-ghb** [comment]
Region for cardriving is set to automatical.
But I was navigating a track (gpx) in bike profile. No route calculation
going on.
It happens with U-turns only.
I have seen it more often.

Regards, Geert

Op vr 6 jul. 2018 18:53 schreef Hardy <notifications@github.com>:

**Comment by gri-ghb** [comment]
Hi.

Since I'm not there now I can't simulate your questions (don't know how 
to at least).

Attached is the gpx file which you can check yourself then.
And the position where this happened is 
https://www.openstreetmap.org/#map=17/51.14247/8.44683
Of with routing: 
https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=51.14274%2C8.44538%3B51.14189%2C8.44479

Regards, Geert Ribbers

------ Original Message ------

**Comment by sonora** [comment]
Hi,

I have tested a route across the turn in question using the standard OsmAnd routing engine (i.e. under Settings / Navigation setting / Navigation service use 'OSMAND'). It correctly indicates "Turn sharply right onto K52", as you can see in these screenshots.

<img width="81" alt="screenshot_2018-07-14-09-00-34" src="https://user-images.githubusercontent.com/845735/42722119-da0dec1e-8746-11e8-9d95-fd09ba682547.png">  <img width="81" alt="screenshot_2018-07-14-09-00-38" src="https://user-images.githubusercontent.com/845735/42722122-dcd8dc38-8746-11e8-9e8a-3a009de5f530.png">  <img width="81" alt="screenshot_2018-07-14-09-05-02" src="https://user-images.githubusercontent.com/845735/42722123-de651bfc-8746-11e8-95eb-bd05c1340e60.png">

Here is the corresponding route file saved as GPX (renamed by adding .txt to the end). When you open it, you can find the entry 
```
    <rtept lat="51.1436558" lon="8.4476709">
      <desc>Turn sharply right and go K 52 479 m</desc>
      <extensions>
        <time>102</time>
        <turn>TSHR</turn>
        <turn-angle>127.77977</turn-angle>
        <offset>5</offset>
        <ref>K 52</ref>
      </extensions>
    </rtept>

```
[_2018-07-14_.gpx.txt](https://github.com/osmandapp/Osmand/files/2194754/_2018-07-14_.gpx.txt)
So OsmAnd does in deed detect a turn angle >120 degrees here, but still gets it right that this is no U-turn.

Not sure where your bogus information comes from, possible sources: You used a GPX file which contains the faulty information (I did not see one attached to your prior post), or you used another (perhaps even online) navigation service instead of the default 'OsmAnd offline'?

**Comment by gri-ghb** [comment]
Hi.

As mentioned before I was not routing with a calculated route.

I used the gpx file that was connected to my last mail.
So the routing engine may be fine, it was not used since I navigated on 
track from gpx.

This was not the first time this happened so I decided to report.
Not because I had a problem, just to let you improve Osmand.

The gpx file with the track is attached again.
This time I have zipped it, maybe then it stays attached for you.

Again: I don't have a problem, it's just that when this happens on 
tracks with me, it will happen with other people as well.
And this is _not_ routed, it's a track.

Regards, Geert Ribbers

------ Original Message ------

**Comment by JonnyTech** [comment]
@gri-ghb email attachments do not make it to GitHub, can you attach at the issue page by browsing to https://github.com/osmandapp/Osmand/issues/5635

**Comment by sonora** [comment]
Yes, I would need the GPX file to debug (source would also be interesting). If the file contains routing information, I believe we honor this as contained, so if it says 'U turn' here I would argue the file is faulty. But should the file indeed contain only track information, I could check if there is a flaw in OsmAnd in evaluating it. Thx!

**Comment by gri-ghb** [comment]
geert@groothagenbeek.nl sent you some files

1 file, 124 KB in total
・ Will be deleted on 21 July, 2018


Download link:
https://wetransfer.com/downloads/a3c74b6c254173b4af7b42133f886cec20180714153318/346c8adc96fda88e0fac75ebb02bdb5820180714153318/6af0dc


Message:
Re[2]: [osmandapp/Osmand] Turn indication wrong direction (#5635)
Last attempt to get the gpx file with the used TRACK to you.
Regards, Geert Ribbers



1 file

45Weg-RondAlbrechtsplatz.gpx


[Get more out of WeTransfer, get Plus](https://wetransfer.com/plus?trk=WT201704_email&utm_campaign=WT_email_tracking&utm_content=general&utm_medium=plus_footer_ad_link&utm_source=notify_recipient_email)



About WeTransfer: https://wetransfer.com/about
Help: https://wetransfer.zendesk.com/hc/en-us
Legal: https://wetransfer.com/legal/terms


To make sure our emails arrive, please add noreply@wetransfer.com to [your contacts](https://wetransfer.zendesk.com/hc/en-us/articles/204909429).

**Comment by gri-ghb** [comment]
Hi.

The gpx file _was_ attached _again_.
Apparently it is not possible to mail attachments to you this way?
I have now sent it with WeTransfer, hope that helps.

And no, the gpx file did NOT contain routing information.
It contains a TRACK.
Only points with gpx-coordinates.

Osmand has NOT calculated a route, just showed a Track.

See the beginning of it below:

<?xml version="1.0" encoding="utf-8"?><gpx creator="Garmin Desktop App" 
version="1.1" 
xsi:schemaLocation="http://www.topografix.com/GPX/1/1http://www.topografix.com/GPX/1/1/gpx.xsdhttp://www.garmin.com/xmlschemas/WaypointExtension/v1http://www8.garmin.com/xmlschemas/WaypointExtensionv1.xsdhttp://www.garmin.com/xmlschemas/TrackPointExtension/v1http://www.garmin.com/xmlschemas/TrackPointExtensionv1.xsdhttp://www.garmin.com/xmlschemas/GpxExtensions/v3http://www8.garmin.com/xmlschemas/GpxExtensionsv3.xsdhttp://www.garmin.com/xmlschemas/ActivityExtension/v1http://www8.garmin.com/xmlschemas/ActivityExtensionv1.xsdhttp://www.garmin.com/xmlschemas/AdventuresExtensions/v1http://www8.garmin.com/xmlschemas/AdventuresExtensionv1.xsdhttp://www.garmin.com/xmlschemas/PressureExtension/v1http://www.garmin.com/xmlschemas/PressureExtensionv1.xsdhttp://www.garmin.com/xmlschemas/TripExtensions/v1http://www.garmin.com/xmlschemas/TripExtensionsv1.xsdhttp://www.garmin.com/xmlschemas/TripMetaDataExtensions/v1http://www.garmin.com/xmlschemas/TripMetaDataExtensionsv1.xsdhttp://www.garmin.com/xmlschemas/ViaPointTransportationModeExtensions/v1http://www.garmin.com/xmlschemas/ViaPointTransportationModeExtensionsv1.xsdhttp://www.garmin.com/xmlschemas/CreationTimeExtension/v1http://www.garmin.com/xmlschemas/CreationTimeExtensionsv1.xsdhttp://www.garmin.com/xmlschemas/AccelerationExtension/v1http://www.garmin.com/xmlschemas/AccelerationExtensionv1.xsdhttp://www.garmin.com/xmlschemas/PowerExtension/v1http://www.garmin.com/xmlschemas/PowerExtensionv1.xsdhttp://www.garmin.com/xmlschemas/VideoExtension/v1http://www.garmin.com/xmlschemas/VideoExtensionv1.xsd" 
xmlns="http://www.topografix.com/GPX/1/1" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xmlns:wptx1="http://www.garmin.com/xmlschemas/WaypointExtension/v1" 
xmlns:gpxtrx="http://www.garmin.com/xmlschemas/GpxExtensions/v3" 
xmlns:gpxtpx="http://www.garmin.com/xmlschemas/TrackPointExtension/v1" 
xmlns:gpxx="http://www.garmin.com/xmlschemas/GpxExtensions/v3" 
xmlns:trp="http://www.garmin.com/xmlschemas/TripExtensions/v1" 
xmlns:adv="http://www.garmin.com/xmlschemas/AdventuresExtensions/v1" 
xmlns:prs="http://www.garmin.com/xmlschemas/PressureExtension/v1" 
xmlns:tmd="http://www.garmin.com/xmlschemas/TripMetaDataExtensions/v1" 
xmlns:vptm="http://www.garmin.com/xmlschemas/ViaPointTransportationModeExtensions/v1" 
xmlns:ctx="http://www.garmin.com/xmlschemas/CreationTimeExtension/v1" 
xmlns:gpxacc="http://www.garmin.com/xmlschemas/AccelerationExtension/v1" 
xmlns:gpxpx="http://www.garmin.com/xmlschemas/PowerExtension/v1" 
xmlns:vidx1="http://www.garmin.com/xmlschemas/VideoExtension/v1">

   <metadata>
     <link href="http://www.garmin.com">
       <text>Garmin International</text>
     </link>
     <time>2018-07-03T20:59:16Z</time>
     <bounds maxlat="51.16832971572876" maxlon="8.486208915710449" 
minlat="51.097540855407715" minlon="8.376710414886475" />
   </metadata>

   <trk>
     <name>45Weg-RondAlbrechtsplatz</name>
     <extensions>
       <gpxx:TrackExtension>
         <gpxx:DisplayColor>DarkGray</gpxx:DisplayColor>
       </gpxx:TrackExtension>
     </extensions>
     <trkseg>
       <trkpt lat="51.156773334369063" lon="8.463426902890205">
         <ele>704.96875</ele>
       </trkpt>
       <trkpt lat="51.15633487701416" lon="8.46297025680542">
         <ele>706.25390625</ele>
       </trkpt>
       <trkpt lat="51.156249046325684" lon="8.462884426116943">
         <ele>706.65625</ele>
       </trkpt>
       <trkpt lat="51.156184673309326" lon="8.462862968444824">
         <ele>706.70703125</ele>
       </trkpt>
       <trkpt lat="51.155605316162109" lon="8.462755680084229">
         <ele>706.65625</ele>
       </trkpt>
       <trkpt lat="51.155004501342773" lon="8.462734222412109">
         <ele>706.62109375</ele>
       </trkpt>
       <trkpt lat="51.15509033203125" lon="8.462111949920654">
         <ele>709.34765625</ele>
       </trkpt>
       <trkpt lat="51.15509033203125" lon="8.46172571182251">
         <ele>710.73828125</ele>
       </trkpt>
       <trkpt lat="51.155154705047607" lon="8.461747169494629">
         <ele>710.73828125</ele>
       </trkpt>

Regards, Geert Ribbers

------ Original Message ------

**Comment by sonora** [comment]
Ok, thanks! I have downloaded your GPX file and attach it to this post. I also attach a very small track GPX file I generated using OsmAnd's Measure Distance feature, which just contains the turn in question.
[45Weg-RondAlbrechtsplatz.gpx.txt](https://github.com/osmandapp/Osmand/files/2195533/45Weg-RondAlbrechtsplatz.gpx.txt)
[2018-07-15_08-52_Sun.gpx.txt](https://github.com/osmandapp/Osmand/files/2195534/2018-07-15_08-52_Sun.gpx.txt)

With both files, I can now reproduce the issue as follows:
 - When OsmAnd calculates a route without using a GPX track for the navigation, the turn is correctly identified as a "Sharp Right".
 - If, however, you display any GPX track traversing the turn, and when prompted answer "yes" to the question if the displayed track is to be used for the navigation, the turn is falsely identified as a U-turn.

**Comment by gri-ghb** [comment]
Hi.

Nice this finally works.
It is not only indentified as a U-turn.
It is also in the wrong direction. Which is even more interesting.

Regards, Geert Ribbers

------ Original Message ------

**Comment by sonora** [comment]
Ok, thanks again for reporting. I think I identified the issue and corrected it. Tested ok, looks like it works.

@vshcherb  While I think I got it all right, it touches a central portion of our code, hence let me please ask for a brief review of this commit https://github.com/osmandapp/Osmand/commit/4ed2414c95fed3de46a240ba80f4bf5ff6565d41

**Comment by sonora** [comment]
PS: @vshcherb Have not investigated why we have 2 rather similar but separate code blocks for turn type determination,
 - one in `RouteCaclucaltionResult` under `addMissingTurnsToRoute` (this one caused the issue here)
 - and in `RouteResultPreparation` under `getTurnInfo`, which already had it right before my fix.

I guess we could call the same code for both cases, but it takes a little tweaking as the angle coordinate systems we use seem offset by 180 degrees.
