### ISSUE TITLE
OsmAnd Live does not update search results

### ISSUE THREAD

**Issue by ADepic** [osmandapp/Osmand#5636]
If I update the map using osmand live, and new house numbers appear on the map, and I try to search for the house numbers, then the search does not find those house numbers. However, if I do not use osmand live, and wait one month for normal map update, then the search does find those house numbers.

**Comment by ADepic** [comment]
Confirmed. I got a normal map update, and the search results now indexed the new house numbers.
Anything on this issue please? It's quite annoying

**Comment by vshcherb** [comment]
It must be a duplicate, OsmAnd LIve doesn't support address search yet.

**Comment by scaidermern** [comment]
Looks like there is already more than one similar issue: #5601, #5376, #4714
