### ISSUE TITLE
No hillshade tiles in Krasnoyarsk Krai

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#5637]
Hillshades disappear starting from zoom 20+ km.

Example location: https://www.openstreetmap.org/relation/3511823#map=14/56.0967/94.5926

**Comment by alyonapinchuk** [comment]
The issue persists in the 3.3.7 version
![image](https://user-images.githubusercontent.com/40493090/56294417-a7536e80-6133-11e9-90fd-1186fd9db605.png)

**Comment by katerynakocherhina** [comment]
There is a popular National park, therefore the hillshades map is essential in this area. 
52.83862 93.37968 
In 3.3.8 OsmAnd version the hillshades are not displayed at all.

**Comment by xmd5a2** [comment]
regions.xml fixed (added hillshades for subregions). Hillshade sqlitedb must be regenerated.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-Issues/issues/27

**Comment by xmd5a2** [comment]
Fixed 
![Screenshot_2020-07-22-13-42-29-329_net osmand plus](https://user-images.githubusercontent.com/5829014/88167423-78bf2000-cc21-11ea-97aa-271e71d956ff.jpg)
