### ISSUE TITLE
Incorrect opening time

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#5639]
Instead of 8:30 OsmAnd shows 14:30.
Location: https://www.openstreetmap.org/node/3731829394

![image](https://user-images.githubusercontent.com/20681525/42319060-8481a7fc-8059-11e8-8763-8479bd682ae8.png)

**Comment by ADepic** [comment]
I changed "Mo-Fr 8:30-12:30; Mo-Fr 14:30-19:00" to "Mo-Fr 8:30-12:30, 14:30-19:00" for that shop in JOSM.

Update your map with OSMand LIVE. Is the error still there?

**Comment by vshcherb** [comment]
The format is incorrect, so it is a map issue which was already fixed by @ADepic
