### ISSUE TITLE
Map profile resets after closing route preparation

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#5642]
When a user chooses pedestrian map mode, opens route preparation and builds a route in pedestrian mode, and then closes the navigation panel, the main profile is switched back to ¨world¨ despite the standard profile set as pedestrian.

**Comment by AlexSyt** [comment]
When navigation ends, the main profile is switched to the default profile, specified in the settings. (settings -> general -> default profile)
