### ISSUE TITLE
Osmand ignores no_u_turn restriction

### ISSUE THREAD

**Issue by ronnystandtke** [osmandapp/Osmand#5645]
I'm using Osmand 3.0.3 (with the current offline maps and offline routing) on a Samsung S5 with LineageOS 14.1.

Yesterday I noticed while driving (car routing profile) through Zurich (capital of Switzerland) that Osmand wanted me to take a U-turn where it was forbidden (exactly here: https://osm.org/go/0C0Uk_BVs?m=)

![no_u_turn osmand buggy](https://user-images.githubusercontent.com/1651625/42367033-1da1c418-8103-11e8-8ae0-ab88769363db.jpg)

At first I thought that it was a missing restriction in the OSM data set but after checking with JOSM the restriction is clearly there and the GraphHopper route planner on the OSM website also takes the restriction into account.

![no_u_turn graphhopper correct](https://user-images.githubusercontent.com/1651625/42367032-1d8199d6-8103-11e8-9f77-d4b8437cfc44.jpg)

So it looks like it is a bug in Osmand (software or map data).

**Comment by vshcherb** [comment]
Strange enough but I could confirm it though it is supposed to work. So it looks like regression.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-tools/commit/1b8833d6a40fa8fc5729499094a69acb2a0ce6df
