### ISSUE TITLE
Wrong routing [ Add test]

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#5646]
Germany, Bruchsal, Zeiloch 1 
Germany, Bruchsal, Stegwiesenstraße 7
![image](https://user-images.githubusercontent.com/1042025/42368194-adb418be-8106-11e8-8ccb-c8cf2e48a24f.png)
![image](https://user-images.githubusercontent.com/1042025/42368232-cc60eca6-8106-11e8-9760-2e224ec8018f.png)

https://www.openstreetmap.org/directions?engine=osrm_car&route=49.13700%2C8.58748%3B49.13635%2C8.59162#map=17/49.13738/8.58842

**Comment by MadWasp79** [comment]
Everything seems okay as of today
![image](https://user-images.githubusercontent.com/13146346/84376567-0272db00-abea-11ea-8918-7bd8622de927.png)

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-resources/commit/a01fdecbf9fb4dc1c62f13fd41aef3b8af9a2c36
