### ISSUE TITLE
Add used GPX  and Long tap -> Directions to the History

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#5648]
When you select a point on the map using a long tap, I think we should add that point to our search history as soon as it is used for an actual route calculation. As of now it seems we suppress it so it is hard to find again for re-use.

**Comment by sonora** [comment]
As an extension of my request, and as a result of the growing significance of GPX files, I think we should add displayed GPX files to the History.

**Comment by vshcherb** [comment]
I like both requests and I think first we definitely need to implement. About second I'm not sure if we need to change UX but I like that idea too.

**Comment by vshcherb** [comment]
@crimean we need to add to IOS version too

**Comment by dmpr0** [comment]
The idea of showing the previous destinations or waypoints, during the Route Preparation is good. But it has nothing to do with the search. This is a problem with the poor UI of the Route Preparation, on this screen during the selection of the start point, waypoint or destination, OsmAnd should show the list of previously used points, but it does not, the solution must be the redesign of Route Preparation.

GPX in the search history can be shown only if we found it. If the user simply turns it on or off the Configure map, it should be displayed somewhere in the Configure map.

**Comment by dmpr0** [comment]
After testing, we found that we are already adding all the points used in navigation to search history.

**Comment by sonora** [comment]
Dmitriy is correct saying that, conventionally, our UI should provide a 'last used' journal on all relevant dialogs, in particular also on the  also on route configuration dialog. Users do simply expect that.

The closest thing we have as such a journal, so far, is the search history. That is why for now I focus on making it as complete as possible. There should also only be one such journal, hence we should eventually also unify with the map marker history.

As to the issue on hand: Select any point (not a POI or tag) by long-tapping it on the map. On its context menu, tap Directions. After the route is calculated, tap the (x) on the route config dialog. The destination point will be missing in the history, and can later not be recovered.

**Comment by sonora** [comment]
PS: I just  notice the issue of such selected points missing in the history is not 100% reproducible. I have currently no idea when it works and when not ...

**Comment by nazar-kutz** [comment]
PR "Add used GPX to history": https://github.com/osmandapp/OsmAnd/pull/11035

**Comment by dmpr0** [comment]
# Review 
- [ ]  Hide file extension (.gpx).
- [ ] After enabling "Configure Map > Tracks" all selected tracks from the dialog would be added to the history.
- [ ] @vshcherb simple map points are added to the history only after the point was used for the navigation.
