### ISSUE TITLE
Insane space requirements

### ISSUE THREAD

**Issue by ADepic** [osmandapp/Osmand#5650]
Storage requirements for OSMAND are insane. The base-map takes around 300mb, and the East of England map takes around 200mb. The roads only maps takes 80mb, which is very big for a roads only map.
Overall Osmand takes 1.2 gigabits of storage! This is simply for the necessary maps (roads only maps I find unusable). So for my family who I have got osmand, I haven't got the world base-map, because it is too big.
Lets look at a [maps](https://gitlab.com/axet/omim) (100% FOSS fork of maps.me) comparison.

East of England (full) is two maps 36mb + 46mb which is 82mb total.

World base-map is 40 MB .

The app takes around 80mb.
The MapsWithMe folder (I sent it to the computer to check the size) takes around 200mb (193mb precise)

200 + 80 = 280mb

So MapsME = 280mb
Osmand = 1.19 GB

See the insane difference?

I realize Maps.Me contains less data, but probably not 5x less data...

And especially for the world basemap, which shouldn't have to be so detailed - 
Here is a map of moscow. I have not downloaded any part of Russia, this is simply the level of detail from the World Basemap. I think that is really high, especially for a region that I will never want.

You could simply reduce the world basemap data a bit, and it would take a lot less space. 
![screenshot_osmand _20180707-142323](https://user-images.githubusercontent.com/24532838/42411297-f72628e2-81e8-11e8-9654-9a07b1c83b6a.png)

An issue (#2808) exists for this, but was closed without solving the problem.

This is even bigger of a problem as sd cards are getting removed from phones and phone manufacturers charge massive amounts for extra storage.

**Comment by njohnston** [comment]
The easiest way of fixing this is to get a phone with an SD card slot. Contrary to your claim, many phones (even those released recently) still have SD card slots. Vote with your money while you still can.

I have a 128 GB SD card in my phone and it's great. I can store maps (plus contours and hillshades, and Wikipedia articles) for everywhere I travel to, without worrying about space.

As for the world basemap, I find it useful and interesting. For example, when on a long flight, it's interesting to explore the places I'm flying over. Even the basemap is often more detailed than the in-flight map.

**Comment by sonora** [comment]
Yes, in deed, OsmAnd aims at more than just being your regular navigation app. Mappers for instance need to see every bit of detail present in the maps or else they cannot reliably improve the maps. Hikers and mountain bikers need all details on e.g.paths. Travelers appreciate details on POIs, like opening times, and obviously Wikipedia data or the new travel guides. And all that needs storage space. We are not wasting the space, it is used for data. I use OsmAnd on expeditions, and appreciate every bit of data I can pack. In general over many years storage has become more available, not less, hence I strongly feel it would be a mistake to sacrifice detail.

If you want to sacrifice detail, maybe consider using the roads only map or a use a raster map?

**Comment by ADepic** [comment]
Brace yourselves, this is a insanely long post.

Okay, there is a lot to answer here, and both of you & me seem to have made some misunderstandings.
Lets start with @njohnston 

> The easiest way of fixing this is to get a phone with an SD card slot. Contrary to your claim, many phones (even those released recently) still have SD card slots. Vote with your money while you still can.

Okay. I realised that we were just throwing claims around, and that wouldn't do any good. I couldn't find many statistics on this, and while browsing I found [this article](https://www.zdnet.com/article/the-real-reason-why-micro-sd-card-slots-are-disappearing-from-smartphones/) which showed how xiaomi and Google started removing sd cards. This wasn't good enough evidence though.

After some more searching, I found [this chart](https://www.productchart.com/smartphones/) which ,very luckily, had a "Sd Card" button. I tinkered with the options (including turning up the price so only recent phones would be included) and the results showed that you, @njohnston , where correct.

There are phones with sd cards, mainly new Samsung phones & Sony Xperias.

However, I do think that you should not have to be limited on your phone choice simply by  Osmand.

If for example, like many, you do not have the expertise to install a custom ROM, and you want a stock like experience (not Samsung), then you'd probably go for something like oneplus or nexus/pixel, which both don't have sd card, then you are a bit busted.

My second point is that if sd card is your solution, then that will severely harm the market reach, since people who have less storage won't use osmand. Is that what you want?

> As for the world base-map, I find it useful and interesting. For example, when on a long flight, it's interesting to explore the places I'm flying over. Even the base-map is often more detailed than the in-flight map.

No. I'm pretty sure, for people who don't have SD cards, they would heavily prefer space saving over seeing the base-map over being able to "see details about the places you are flying over". If the osmand team are not willing to reduce base-map size simply because you can "see details about the places you are flying over", then that is quite ridiculous IMHO.

But even if they wanted to do that, my proposed solution is a "mini-basemap". Suggest this at first app start, but suggest that they can download a more detailed base map in "Download Maps" section. I'm pretty sure lots of people would appreciate this. You can't navigate using the world base-map, you don't see POI's and lots of other details, so I think it would be better to just have a mini base-map.

Now onto Hardy's claims.

>Yes, in deed, OsmAnd aims at more than just being your regular navigation app. Mappers for instance need to see every bit of detail present in the maps or else they cannot reliably improve the maps. Hikers and mountain bikers need all details on e.g.paths. Travellers appreciate details on POIs, like opening times, and obviously Wikipedia data or the new travel guides.  And all that needs storage space.

Agreed. You know, I had a idea after you suggested this. Separate the maps into even more sections, so the basic map is smaller. For example - Cycling & Hiking maps could be separate. Bus routes could be separate. However this could be too confusing. You tell me what you think.

>  I use OsmAnd on expeditions, and appreciate every bit of data I can pack

However, different people use maps with different uses. Many people probably won't use all the data that Osmand downloads. Maybe the maps separating idea could be a solution, but like I said it could be too confusing.

> In general over many years storage has become more available, not less, hence I strongly feel it would be a mistake to sacrifice detail.

However scummy manufacturers have started charging up to $100 for just a bit of extra space, and it is RIDICULOUS. So many people won't be buying phones with 128 GB, 256 Gb storage (unless you have a sd card, then lucky you) and many people take lots of photos, which can eat 64 gb really fast.

>hence I strongly feel it would be a mistake to sacrifice detail.

No, I was not suggesting sacrificing detail for normal maps, only the basemap, which is not SO important that it needs to take 300mb. It is the least important map that you download yet it takes the most space...

The solution the would hope for in reducing size is #2808 . However I suggested reducing info as a quicker and easier solution for the basemap, which is the root of this issue.
Also, as a comparison, here is the basemap details of Moscow in Maps (100% FOSS fork of Maps.Me)
![screenshot_maps_20180707-222846](https://user-images.githubusercontent.com/24532838/42414812-9083c05a-822d-11e8-812d-4b4024274b58.png)

As you can see it is less detailed. I do not mind this and I think the mini-basemap is a (along with base-map) is a good idea, although I would prefer indication of terrain (such as forest, farmland etc.) over roads, which don't serve that much purpose.


>If you want to sacrifice detail, maybe consider using...

Let me answer every suggestion you made one by one.

>... the roads only map

The roads only map has not got any POIs, house numbers and is pretty much unusable for many cases. Maps.Me full maps takes less space then roads only map (for east of england) and yet it has house numbers, POIs (I think it has opening hours too (and obviously phones, emails, website)) and houses, infact it has 3d houses with house height, with is really useful for routing through some big city centre, for example where all the buildings are different height and you can compare the map with real life.

> a raster map

Because it will take quite a lot of data. It doesn't have clickable POI's, like Magic Earth or Google Maps.

**Comment by sonora** [comment]
Ok, thanks for the detailed explanation, but it seems you pretty much concur that the degree of detail in our standard maps, much of which is associated with POIs, is useful for a broad audience. This is exactly the reason why many people find the roads-only maps not useful enough, (they contain basically the data needed for navigation, probably only useful if you want to navigate across a region without any intention to stop or sightsee).

I feel that both splitting maps into still smaller regions as well as into layers, like POIs vs. roads etc. would considerably complicate it for users to have all the data needed available when they need it. So far you mainly have to watch your regional coverage (while we already have separated off hilllshades, contour lines, Wikipedia data , and travel guides)).

Re-reading your thread above, it seems anyway that we are mainly having a discussion about saving a portion of a 300 "MB" file, the world map? Is there really a point, as the storage in phones is of the order of "GB"s. Plus, the world map is not really mandatory, you will get along fine if you only use OsmAnd in a small region? But for those, who travel a lot it is interesting... Not sure how much we could reduce the file size by, but if it was 100MB, would it be worth it at all?

**Comment by ADepic** [comment]
@sonora I think you are misunderstanding me.
A combination of compression methods and quality removal (not too much) could create a "mini-basemap" that should around 40mb. You can still keep the full basemap, just have a mini basemap too.

> a 300 "MB" file, the world map? Is there really a point, as the storage in phones is of the order of "GB"s. Plus, the world map is not really mandatory, you will get along fine if you only use OsmAnd in a small region?

But even 100mb can be very precious. To many people, those "GB"s are taken up by photo and video.

I think if a user sees a 300mb basemap on osmand and 40mb basemap in maps.me, most will go for maps.me. I think that many user - unfriendly features in osmand is why maps.me has a much bigger userbase. 

You need to take steps to attract normal users, and a mini-basemap of 40mb would be useful, if not necessary.

**Comment by vshcherb** [comment]
There is no technical plan so far how the data could be reduced. We have the basemap of 18 MB but it contains too few data.
If that question is only about basemap, we are going to address it soon. We're not going to change maps format so far in any nearest future

**Comment by leggewie** [comment]
> I think if a user sees a 300mb basemap on osmand and 40mb basemap in maps.me,
> most will go for maps.me.

Me, for example.

**Comment by erik55** [comment]
I also like the details and need them for excursions, hiking, traveling, exploring the world (like an atlas). But yes, the basemap is quite big. Many of my guests that go hiking with me and who install Osmand, are really surprised, that the basemap is that big. And I always tell them, that they really should install it, otherwise the map turns blanc if you zoom out to much.

Maybe a bit of reduction of details would be really good. For me it is ok, I have an 128 SD card and 32 GB internal memory. But Osmand is my most used application of my telephone, and I knew that before buying that phone.

I am a bit undecided, because the basemap is not mandatory. I really don’t like the idea of a mini and a basemap – that’s really confusing. Osmand already has soooo many options and possibilities (good for me, but not easy to start with for new users).

**If anybody has a specific idea of how to save space** (which details, roads, objects should be simplified or removed), please **write it down.** Otherwise I would vote for closing this issue.

**Comment by aceman444** [comment]
These days there exists a "world basemap mini" map that comes with OsmAnd and is around 40MB unpacked. The large World basemap of 320MB can be downloaded optionally.

OsmAnd shows much more data then the simplistic Maps.me. Please do not remove any details from the OsmAnd maps (actually add more), only the compression method can be investigated if it can be improved.

**Comment by Lee-Carre** [comment]
All this makes me glad that I'm on a small island-nation ([Jersey](//www.openstreetmap.org/relation/6956667) (Channel Islands, Europe); [<10MiB](//download.osmand.net/list.php) 😀).

> Plus, the world map is not really mandatory, you will get along fine if you only use OsmAnd in a small region?

Can confirm!

I've left the basemap-mini installed, not installed the larger basemap, and I could probably get away with uninstalling the mini if I wanted.

Seldom do I zoom out enough to view the whole island, and never enough to need the basemap.

If I want to examine other parts of the world, I'll use online tiles.

If I were travelling, that would be different.

As a user, and especially an OSM contributor (one of very few, locally), I greatly appreciate that OsmAnd includes the full OSM treatment of detail.

As an on-foot surveyor, I make a point of adding small features (defibrillators, bins (regular & recycling), benches, fire hydrants, street lamps, post boxes, etc.).

Organic Maps (the new Maps.me) is far too simplistic for my liking.
