### ISSUE TITLE
As first route error, following a gpx file (offline) not working any more

### ISSUE THREAD

**Issue by Oops03x** [osmandapp/Osmand#5651]
Hi,

As soon as you make an error in the route, the option "follow the whole track/Pass along entire track" is not working any more.

Related to the above problem, you can't follow (at least offline) a GPX starting right on the track but not at its beginning.
(my Garmin Edge supports this feature)

I'll raise a new issue even it was already well documented in issue #5547 (status "Observed").

See below the "problem" description / particulary Test 2.

Regards

Samsung S6
Android 7.0
OSMAND 3.0.4

OffLine
Goal: follow a basic GPX track with a road bike so as to test the behavior of the application on taking a wrong direction.

Test 1:
-Option set None
After the wrong turn, the application guides me toward the ending point.
->OK (but this is not what I am looking for)

**Test 2:
-One unique option set "Follow whole track"
After the wrong turn:
   the application says "recalculating" (KO)
   an arrow is displayed toward the ending point crossing buildings (means recalculation?)
   when back on track the "wrong" arrow is still there (->KO).
   "recalculating messages keep going on"
   (I just need  a message saying "you're out of the track" WITHOUT any (forever?) recalculation)
->KO
**
 
  
Test 3:
-One unique option set "Follow whole track"
-I start exactly on the track somewhere between the starting and ending points
There is a calculation of the route (arrow pointing towards the end; messages ...)
->KO

**Comment by roadbike16** [comment]
Hi Chumva, #5651 refers also onto #5547 above. Are the issues in #5547 fixed too ?
