### ISSUE TITLE
opening_hours: translation of "off" into german is wrong

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#5656]
In opening_hours  attribute "off" (en:closed) is translated into german as "aus" which is wrong and  unclear.
Please change german franslation to "geschlossen"
Example:
https://www.openstreetmap.org/node/2853835605
which has more bugs (date range).
Version 3.0.0.#25258
Peter

**Comment by sonora** [comment]
Think I fixed it - Thanks!
