### ISSUE TITLE
Translation feedback required

### ISSUE THREAD

**Issue by StanislavTichy** [osmandapp/Osmand#5665]
Hi, I am doing translation of OsmAnd on weblate and came across some veird strings I am unable to think of how, in what place and under what circumstances will it be rendered for user in app.
It is all about charging stations and their connectors, power and current output. As electrical engineer I know it very well in real world but the strings are just veird.
Code lines from 3244 to 3306.

One example:
Line 3281 
Context: "poi_socket_tesla_supercharger_current" 
Source:
"Socket: Tesla Supercharger: current"

Is it legit to display whole translated string for end user including colon divider?

**Comment by sonora** [comment]
Thanks for bringing this up, brief research shows the strings are displayed on the context menu of charging stations, see this example:
<img width="135" alt="screenshot_2018-07-15-09-32-07_" src="https://user-images.githubusercontent.com/845735/42731693-0cab3b6e-8813-11e8-8ecd-4659c41d6ff6.png">

and they seem to refer to these OSM's tags: https://wiki.openstreetmap.org/wiki/Key:socket, so OSM mixes the socket type with additional qualifiers in one tag,

@xmd5a2  I have the following suggestions:
 - `socket:<type>`indicates their number, so we could use "Connector type: XXX, socket count"
 - `socket:<type>:current`: "Connector type: XXX, current (A)"
 - `socket:<type>:output`: "Connector type: XXX, output (kW)"   _(or maybe we display Watts, not sure)_

**Comment by sonora** [comment]
PS: On second thought, maybe we can even shorten to
 - `socket:<type>` "Socket type: XXX, count
 - `socket:<type>:current:` "Socket type: XXX, current (A)"
 - `socket:<type>:output:` "Socket type: XXX, output (kW)"

**Comment by StanislavTichy** [comment]
Well. If it is only place these strings are rendered as shown on screenshot. I will translate it for best user experience as something like this:
 "Number of tesla supercharger sockets:"
"Maximum current for supercharger socket (A) : "
"Maximum output for supercharger socket ( kW) :"

**Comment by vshcherb** [comment]
I believe the original issue is explained.
Probably @xmd5a2  could answer better. I will remind him to bring feedback here.
