### ISSUE TITLE
Possibility of using map data from maps.me app

### ISSUE THREAD

**Issue by comradekingu** [osmandapp/Osmand#5669]
The maps.me app also uses OSM data. It would be nice to make use of it if you install OsmAnd afterwards, or for some reason want to have both, without essentially keeping two version of the maps.

**Comment by vshcherb** [comment]
I believe it is a duplicate, but the short answer it is not possible

**Comment by devurandom** [comment]
Possibly related to / duplicated in:
* #2808
* #3490
* #5650
