### ISSUE TITLE
Rendering error

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#5670]
The area is rendered as a swamp.

Location: https://www.openstreetmap.org/way/148711416#map=16/50.6134/3.1514

Screenshot:
![image](https://user-images.githubusercontent.com/20681525/42722285-f8d6e7e4-8751-11e8-84ca-b8d9e17e1a92.png)

**Comment by xmd5a2** [comment]
https://www.openstreetmap.org/relation/3369566/history
This is not related to OsmAnd. Search for "wetland" here.
