### ISSUE TITLE
README.md: How to Build section

### ISSUE THREAD

**Issue by fbarriga** [osmandapp/Osmand#5674]
`README.md` change:
Can you please add a **How to Build** section that has a link to https://github.com/osmandapp/OsmAnd-core ?
I spent a lot of time trying to build this repo directly and probably I'm not the only one. This creates a barrier for new developers that doesn't want to spend the few free hours we have trying to help/use this project.
Thanks,

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-core -  this project is not buildable and used in android so far. So I think this issue is not related to the OsmAnd - android
