### ISSUE TITLE
Reveal Hiking Trail data

### ISSUE THREAD

**Issue by petenz** [osmandapp/OsmAnd#5675]
For hiking trails (on Openstreetmap, highway=path), Osmand does a good job of showing trail type (a trail I've tagged as more demanding shows as a different dashed line to a regular trail), but it would be nice if there were a way for a user to select a section of trail and see the actual designations (Hiking Difficulty rating/Trail Visibility rating etc.) with a key or scale so they can easily discern the likely difficulty of the trail.

**Comment by vshcherb** [comment]
It is hard to come up with such idea how to "click" on the road, we are thinking it will be very useful for "route planning", so "Measure distance" tool could be very useful

**Comment by rindlerblabla** [comment]
I think it would be very usable to have that view during active routing as well (for bicycle, hiking and future ski profile).

**Comment by littlehelper** [comment]
To me it sounds similar to the feature request #2232.

**Comment by petenz** [comment]
Yep, pretty much the same, it's definitely broader than just hiking trails, MTB and ski runs etc.

My suggestion came from concerns over a 'path' I'd added to Openstreetmap that in my local (New Zealand) parlance is what would be called a route rather than a hiking track. It's an established route but poorly marked at best, and potentially challenging in terms of terrain too - it's almost climbing, exposed, well prepared people have had falls and needed helicopter evacuation etc. Delighted to see tagging it correctly in Openstreetmap (both visibility and difficulty scales used) means it's shown differently in Osmand but without revealing the underlying data someone could still find themselves well out of their comfort zone on the path I added.

**Comment by petenz** [comment]
This is the kind of scenario I'd be hoping to avoid: https://www.reddit.com/r/searchandrescue/comments/8wlz88/rescue_due_to_marking_of_trails_on_openstreetmap/?utm_source=reddit-android

**Comment by matthijskooijman** [comment]
This is very similar to #7299 (maybe even a duplicate), which suggests showing hiking routes in the details shown when you drop a marker on a road on the map (similar to what happens when you view details for a transport stop).

**Comment by Lee-Carre** [comment]
See [#9800 (comment)](/osmandapp/OsmAnd/issues/9800#issuecomment-1023890898):

> There are already a few ways of doing this:
> * from within OsmAnd
>   * enable the editing plugin
>   * select the element of interest
>   * in the details, the URL for the element is a clickable link
>   * tapping it will open it in a browser of your choosing, and show all the data which OSM has about the element
> * use OSMfocus (or the newer OSMfocus Reborn), which is intended for exactly the desired use-case described here. It can follow your GNSS position, so you literally just have to walk up to an element to have its tags listed

**Comment by scaidermern** [comment]
> See [#9800 (comment)](/osmandapp/OsmAnd/issues/9800#issuecomment-1023890898):
> 
> > There are already a few ways of doing this:
> > 
> > * from within OsmAnd
> >   
> >   * enable the editing plugin
> >   * select the element of interest
> >   * in the details, the URL for the element is a clickable link
> >   * tapping it will open it in a browser of your choosing, and show all the data which OSM has about the element

This works only for POIs but not for regular ways like roads and paths.

**Comment by alensiljak** [comment]
This is literally a life saver. Please!
Some other implementations, like Bergfex, show the difficulty as "T3" next to the path, but no visibility.
An important distinction is also whether the path is exposed or not. While a non-exposed T3 is just a difficult path, an exposed T3 is a Russian roulette.

**Comment by vshcherb** [comment]
Well I think the situation has changed a lot, so now it's clickable on the shields and all relations tags should be displayed

**Comment by vshcherb** [comment]
I think sac_scale rendering is supported - https://wiki.openstreetmap.org/wiki/Key:sac_scale. You can select in rendering options for Hiking routes

**Comment by alensiljak** [comment]
Yes, thanks. I've used that before but, for some strange reason, on the new phone the trail difficulty was on but none of the grading systems. I had to manually select the SAC.

I'm still getting used to the colours and the trail visibility lines but this is pretty good. I assume it follows the guidelines at https://wiki.openstreetmap.org/wiki/Hiking_maps in some way.
