### ISSUE TITLE
Use Kalman Filter to smooth map scrolling when following current position

### ISSUE THREAD

**Issue by jkufner** [osmandapp/OsmAnd#5681]
When current position is updated and map scrolls to the new position, it scrolls at wrong speed -- position updates are visible and distracting when watching the map at more detailed zoom levels. It would be nice to let Osmand predict the next position and smooth scroll (almost) perfectly as the next position arrives from GPS.

[Kalman Filter](https://en.wikipedia.org/wiki/Kalman_filter): The math behind Kalman Filter may look scary and complicated, but the idea is rather simple. It uses current value and difference from previous value (the first derivation) to extrapolate the next value. In Osmand's case it means that the next position to be received from GPS is likely to be last known position plus last known speed multiplied by GPS update interval. There will be (small) error in the extrapolation when speed changes, but it can be easily compensated during the next update by adding acceleration (the second derivation) into the calculation.

The proposal: Use (simplified) Kalman Filter to smoothly scroll map when moving. Then when moving at any constant speed the map scroll position will perfectly match the real current position. The GPS updates will no longer be noticable.

**Comment by MayeulC** [comment]
Related to https://github.com/osmandapp/Osmand/issues/562#issuecomment-31344631
(Use the same feature to approximate location in tunnels or no-GPS areas)

**Comment by tbertels** [comment]
The gyroscope could also be used to check which way the car turns if the tunnel gets divided.

**Comment by aleung** [comment]
Isn't it implemented?
