### ISSUE TITLE
Incorrect city relation [ Boundary Singapore / Malaysia ]

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#5685]
Quite a number of streets in Singapore are categorized wrongly, under another city in Malaysia called 'Pasir Gudang'.
![image](https://user-images.githubusercontent.com/20681525/42803012-508a3574-89ad-11e8-8227-328444d3ded5.png)
![image](https://user-images.githubusercontent.com/20681525/42803026-5713d724-89ad-11e8-9532-b5e0f68e2b45.png)

**Comment by vshcherb** [comment]
We need to check the boundary of Malaysia / Singapore. Pure singapore map doesn't have such problem.

**Comment by xmd5a2** [comment]
Can't reproduce. No "Admiralty Drive" when 2 maps installed.
![Screenshot_2020-07-07-12-32-38-687_net osmand plus](https://user-images.githubusercontent.com/5829014/86760913-4375d800-c04e-11ea-9d19-289df4bd6f17.jpg)
