### ISSUE TITLE
GPX - Link parameter not visible in Context Menu

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#5691]
![2018-07-18 12 14 16](https://user-images.githubusercontent.com/9365308/42871906-21956f22-8a84-11e8-8c78-0e1289162383.jpg)

[Berlin.gpx.zip](https://github.com/osmandapp/Osmand/files/2205166/Berlin.gpx.zip)

**Comment by nazar-kutz** [comment]
Seems like it's already fixed
