### ISSUE TITLE
Restore settings

### ISSUE THREAD

**Issue by UAb5eSMn** [osmandapp/OsmAnd#5701]
While on the move, I sometimes press at the wrong location of the touchscreen and some setting is changed by accident. Or sometimes rain drops are registered as touch events.
It's not always obvious what happened and how it can be undone. Especially while on the move when things have to be fixed quickly. Some ideas:
* Add a settings save / restore option
* Add a way to undo changes
* Log all actions (but it might be difficult to find out which GUI menu / button belongs to a  description in the log)

**Comment by pebogufi** [comment]
A save / restore setting to external (xml) file could also to be used for transfering setting to other device, when buying a new one or sync to second device (example smartphone to tablet).
This would be VERY fine !!!
Peter

**Comment by ijackson** [comment]
I think this is implemented now.  There's Menu / Settings / Backup and restore
