### ISSUE TITLE
Map profile and display position change after accessing the navigation menu

### ISSUE THREAD

**Issue by UAb5eSMn** [osmandapp/Osmand#5703]
Example to reproduce on version 3.0.4:
Default profile [Driving] (with the display position at the bottom, so not at the center)
* Switch the map to cycling
* Press the directions button
* Press X
Now the map has been switched to driving and (if the GPS is off) the display position is at the center
* Switch the map to cycling
The display position is still at the center
* Press the directions button
* Pres the GO button
* Tap the screen to unhide the buttons
* Press the directions button
* Press X
* Select YES to dismiss the route and stop the navigation
The map has been switched to driving again, but the display position is at the expected location, at the bottom
* Switch the map to cycling
The display position is at the expected location, at the bottom

**Comment by vshcherb** [comment]
Default profile [Driving] - is it specified in General Settings Default profile?

**Comment by UAb5eSMn** [comment]
Yes, the Settings / General Settings / Default profile has been set to [Driving]

I've only used Navigation a few times, so I just found out that I incorrectly assumed X to be cancel / back (it's dismiss route / stop navigation). I usually end up in navigation mode by accident because I press at the wrong location, so I just press X to get out again.
The problem could be caused by having 'From' and 'To' set. I've not figured out how I can clear those fields. It's probably possible, because I only just discovered other hidden features like the 'Route details' menu, which can be displayed by tapping on the 'Distance / Time' area.

I've noticed different behaviour for X and the Android back button. The behaviour with a GPS fix (which is better than without GPS, so ignore my first post):

When using the android back button:
* Switch the map to cycling mode
* Press the navigation button at the bottom left
A route is immediately calculated (because of old From and To locations) and is displayed on the map
* Press the Android back button
The calculated route is still displayed on the map
The screen position is moved to the center instead of the bottom
The navigation button is blue
The map stays in cycle mode
I don't know if there's a better way to clear the calculated route, so here's what I do:
* Press the navigation button at the bottom left again
* Press the X
The map is switched to driving mode
The screen position is moved to the  bottom again
* Switch the map back to cycling mode

When using the X button:
* Switch the map to cycling mode
* Press the navigation button at the bottom left
A route is immediately calculated (because of old From and To locations) and is displayed on the map
* Press the X button
The calculated route isn't displayed anymore
The map is switched to driving mode
* Switch the map back to cycling mode

**Comment by vshcherb** [comment]
We can't reproduce it with 3.8.0

**Comment by ossilator** [comment]
i'm not sure it's the exact same problem, but i'm observing similar behavior: the display position changes after opening the routing menu. it has something to do with the display position being set to automatic and the map orientation being "movement direction", but i couldn't identify a reliable sequence of events.
