### ISSUE TITLE
When the "From" and "to" are swapped, change their positions instantly

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#5707]
Currently the "Set destination" window shows **From** and **To** fields. A button allows us to swap them.
But if we tap this button, apparently nothing happens for a while.
After a small delay, the **route calculation** progress bar starts growing at the top of the dialog box.
When the route is calculated fully, the **From** and **To** buttons are swapped.

**Suggestion:** Please swap the **From** and **To** buttons as soon as the swap button is tapped.
Let OsmAnd calculate the route after that.
This is more logical sequence.

**Comment by ADepic** [comment]
Oh, thats why it was slow. I thought it was because if my phone being slow or something
