### ISSUE TITLE
Downloads Maps - Change map icon color

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#5708]
I have download map of Wales, and HillShade for the Uk, but map icon on Download Map > Europe is still grey, but must be an orange.
![untitled-1](https://user-images.githubusercontent.com/9365308/42953513-4c07e6fe-8b83-11e8-848e-e6ea9a4ebe6c.png)

**Comment by sonora** [comment]
Ornange/green is our color set depicting present/latest maps: Orange is our color for 'a map is present locally, but not in its latest version'.

What we are talking here is how we want ot depict **category headlines,** for which in one or several sublevels you have maps present locally.

That's another dimension, would requiire a different concept to illustrate: like maybe a folder (not map) icon cut in two diagonal halves, one is gray (depicting portions are not present locally), the other is green/orange, depicting dowloaded portions are all latest, or not latest.

**Comment by scaidermern** [comment]
Let's not overcomplicate this. Currently a folder becomes orange if it contains at least one outdated map and it becomes green if all downloaded maps are up to date while files are allowed to be missing. In my opinion this is fine except for the fact that this color is not propagated to the parent folders. Just propagate it to all parent folders to make it easier to see for which continents/countries/regions maps have been installed.

The suggested diagonal approach isn't worth it and may even do harm. For example for certain countries there are both country-wide contour lines and hill shade files as well as region-specific contour lines and hill shades. Having downloaded the country-wide files it doesn't make sense to download the region-specific files, too. However with the proposed diagonal approach the folder will be half green, half grey. This will be misleading and not helpful at all.

**Comment by dmpr0** [comment]
![Group 110](https://user-images.githubusercontent.com/9365308/89399992-e8520680-d71b-11ea-820d-ca59dbabb256.png)
Screenshot illustrate some issue with a road-only map.
Review:
- If the country or region has one map download (any type) all icons up to the main Download screen must be green or orange if updates are available. For example, if I have Upper Babaria Wiki map (or any other map type) downloaded, icons at all levels: Upper Bavaria > Bavaria > Germany > Europe should be green or orange.
