### ISSUE TITLE
Routing error with trunk link

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#5709]
Route: https://www.openstreetmap.org/directions?engine=graphhopper_car&route=37.9263%2C-6.7148%3B37.9202%2C-6.7199

OsmAnd offers an unreasonably long detour.
Screenshot:
![image](https://user-images.githubusercontent.com/20681525/42986372-f47ccc6c-8bfd-11e8-8cec-4ea8a238eb94.png)

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-tools/commit/66f0096b13b691062b475396638887d7b8336041

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/commit/22e9fe318a3fa0c1fa81f0d99dee58329cedbf40

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-core/commit/1e04447abe32d3028f4028a71b7f73a0d4dcf9cb

**Comment by vshcherb** [comment]
Fixed. This issue will require new data & new app
