### ISSUE TITLE
OSM live updates broken completely

### ISSUE THREAD

**Issue by ADepic** [osmandapp/Osmand#5710]
No, this is not issue #5629 .

I cannot update the map using OSMand Live at all, OSMand live says "2018-17-19 17:30", meaning it is a day old. All maps I try and update using "Update now" update only to that point, not any later. It is a day old.  

I added some POIs yesterday that were quite important and was expecting to get then on osmand live today, but osmand live broke today morning...

**Comment by scaidermern** [comment]
https://osmand.net/api/osmlive_status says `2018-07-19 12:40` (= one day behind). So this is #5498 again.

**Comment by ADepic** [comment]
Isn't this the third time now?

Today was the first time I've actually needed osmand live (before it was just a luxury) ...
And it breaks. What sort of irony is this?

**Comment by vshcherb** [comment]
This happens once a month sometimes. It is not broken, it is delayed. We are aware of the problem and we plan to reduce the gap to 12 hours maximum per month. Average delay is 30 minutes so far.
We are catching up

**Comment by ADepic** [comment]
Wait, what? Average delay is not 30 minutes, its now like 26 hours behind.

**Comment by ADepic** [comment]
And yes it is sort of slowly catching up, but that is still irritating ng

**Comment by vshcherb** [comment]
Average delay this month. I would say by the end of today, the delay will get back to 25 minutes

**Comment by ADepic** [comment]
Okay, thanks thats what you meant. For me live delay is now around 18 hours. :)

**Comment by vshcherb** [comment]
We monitor it every 15 minutes, for last day delay was 21 hours, now it is around 18 hours. It will speed up though ETA to reach is about 12 hours.
