### ISSUE TITLE
Move "App Profiles" to general settings

### ISSUE THREAD

**Issue by ADepic** [osmandapp/Osmand#5711]
Currently they are in development settings, although they are useful for average users (e.g. truck mode for truc users.)

Also modify the pop-up menu to the image below so that you can see the profile names, because icons aren't always clear (The box with the letter "i" inside represents the icon)
![app profiles](https://user-images.githubusercontent.com/24532838/42990843-92b29024-8c21-11e8-80d9-8afe866a4fcb.png)

Maybe you can add a little dropdown button on the right which gives a description of the profile

**Comment by vshcherb** [comment]
I'm pretty sure that's duplicate of another issue and we have plans to do it in short term but let's keep that open until we could implement it or reference to another issue.

**Comment by ADepic** [comment]
yup this has been fixed a long time ago
