### ISSUE TITLE
GPX - Incorrect data are cumulate in Ascent and Descent

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#5715]
![image](https://user-images.githubusercontent.com/9365308/43011471-39a28d38-8c4c-11e8-9028-6b4ed7235e58.png)

**Comment by sonora** [comment]
Well, start point end end point seem to be roughly at the same elevation (maybe the track is even a closed loop trail?), and the sum of Ascent vs. Descent shown only differs by a negligible 5 meters, over a distance of over 30 kilometers(!).  I am inclined to say that speaks for outstanding accuracy of the  algorithm I had implemented a long time ago.

So the question here is why in this case it does not report what is being expected and what the expectation is for this particular GPX recording: We are talking about a 35km trip, and the algorithm parameters applied conclude that a hiker following this GPX would in deed have to cover an elevation change much larger than simply 2 **perfectly smooth** ascents to the two mountain tops. Now terrain surface (e.g. trails) are never perfectly smooth and actual elevation change may accumulates over large and small ups and down of e.g. 10, 20, 50 etc. elevation meters each. Hence 'true' changes may come from rough terrain. In addition, fake changes may come from excessive, uncompensated receiver noise in the track. We would need the GPX to analyze.

Brief remarks on theory, several effects here:
- Accumulation topics are always tricky, bordering fractal problems. Imagine that a human hiker walking across rough terrain 'performs' much fewer elevation changes than e.g. an ant having to 'hike' up and down every pebble sized stone the human simply 'steps over'. (Needless to say: I parameterized our algorithm for the human dimension :) )
- GPS has limited elevation accuracy, creating noise not reflecting 'real' elevation changes. The solution is to use smoothing to a reasonable degree, and a threshold for when an elevation change is perceived sustained and real.  
- The discussion is of course not unique to the elevation accumulation, see also e.g. https://github.com/osmandapp/Osmand/issues/3923 regarding horizontal distance.

**Comment by vshcherb** [comment]
Thanks for detailed explanation, this issue doesn't look wrong and without reference application / algorithm it is hard to discuss it. 
Probably the discussion should be around special parameter which user can calibrate with its own device but it is still not clear what that parameter will look like

**Comment by sonora** [comment]
It is a fairly standard noise filtering problem, for which well documented solutions exist. They all have in common that where your S/R ratio is small,
- if you filter too little, you count some noise as signal, which in an accumulation value will mean you overestimate the true result,
- while if you filter too generously, you throw away actual signal, leading to an accumulated result being too small vs. the expectation.

From my practical testing how we have it now is not a bad compromise for both hiking and car use, and unless you have bad GPS reception, and/or are accumulating over a large number of points where such accumulated values become inherently less precise.
