### ISSUE TITLE
Live monitoring: https hostname validation is disabled

### ISSUE THREAD

**Issue by stefanb** [osmandapp/Osmand#5718]
https://github.com/osmandapp/Osmand/blob/20889babbd6bfc8eb38873ac2657a7713236c01e/OsmAnd/src/net/osmand/plus/monitoring/LiveMonitoringHelper.java#L189

Given the general availability of free https certificates (Let's encrypt) there likely is no need anymore to intentionally break hostname validation when user tried to increase their privacy by setting up a secure (https) endpoint.

**Comment by vshcherb** [comment]
I agree let's remove it and if we need to reimplement it then it is for sure should be optional
