### ISSUE TITLE
Search - Address search don't find street

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#5722]
Location 51.60276 Lon 7.19101, has the street "Auf den Flachsbeckwiesen". It possible to find in thru normal search, but not from address search if start from "Auf den", if just write Flachsbeckwiesen, OsmAnd will find it.
Screen 1, street on the map.
Screen 2, adress search without "Auf den".
Screen 3, adress search with "Auf den" 
Screen 4, normal search.
![search_issue](https://user-images.githubusercontent.com/9365308/43072996-aebbfc9a-8e80-11e8-871c-844a457873ed.png)

**Comment by vshcherb** [comment]
![Uploading image.png…]()

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/84036285-4f15a680-a99d-11ea-929a-3d548321e05d.png)
