### ISSUE TITLE
Swap <cmt> and <name> for exported gpx file of osm edits

### ISSUE THREAD

**Issue by ADepic** [osmandapp/Osmand#5725]
If you want to export your osm notes and POIs as a gpx file so that you can edit it in JOSM, once you load it into JOSM all you see in "Note create" "Note Modify" etc. To actually show notes and POIs, you have to go into a text editor and use the "Find and Replace" tool to replace "cmt>" with "xyz>", " name>" with "cmt>" and then "xyz>" with "name>".

This is quite annoying, and yes it improves gpx displaying in osmand (because osmand interprets cmt as comment), but exporting to gpx's main use is JOSM. So please put the actual contents of notes and POIs in "name"

**Comment by scaidermern** [comment]
This has already been done, see #5528.

**Comment by ADepic** [comment]
It just hasn't been done though!!!
Cmt still has the contents????

**Comment by scaidermern** [comment]
I guess there hasn't been a new release since the fix. Just be patient.
