### ISSUE TITLE
Radius ruler issue

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/OsmAnd#5726]
Correct distance: 
![image](https://user-images.githubusercontent.com/20681525/43120091-a8449dc6-8f21-11e8-801a-03a0dc980b59.png)

Incorrect:
![image](https://user-images.githubusercontent.com/20681525/43120101-b17407e2-8f21-11e8-9195-cfe2987aaa1a.png)
![image](https://user-images.githubusercontent.com/20681525/43120112-b797da36-8f21-11e8-8987-698b066236d8.png)

**Comment by dmpr0** [comment]
I think it happens only on tablets.
![screenshot_20180723-130515](https://user-images.githubusercontent.com/9365308/43123358-98613dc8-8f2c-11e8-84a1-4b6c81923849.png)

**Comment by vshcherb** [comment]
We need to disable ruler on such zooms cause it doesn't make sense.

**Comment by dmpr0** [comment]
Fixed
