### ISSUE TITLE
Map rendering - Water covered surface

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#5727]
First place:
Coordinates: 53.26273, 6.39576 
![screenshot_20180722-164328_osmand](https://user-images.githubusercontent.com/9365308/43075378-55a0ea86-8e89-11e8-8fa8-b730539e2216.jpg)

Second place:
Coordinates: 53.26602,  -4.15895
![screenshot_2018-07-09-08-04-30](https://user-images.githubusercontent.com/9365308/43124376-b3d39116-8f2f-11e8-8bd9-1bcb587ad3ac.png)

In both cases, user uses Touring view map style.

**Comment by vshcherb** [comment]
Unfortunately can't reproduce

**Comment by treestryder** [comment]
Try browsing slowly around the edges of Boston, MA. It happens often. Here is a screenshot I just took, near Castle Island.

Location: geo:42.33507,-71.03988?z=14
https://osmand.net/go?lat=42.33507&lon=-71.03988&z=14

![screenshot_20180810-090238](https://user-images.githubusercontent.com/3682967/43960876-68564a80-9c81-11e8-88ba-88ab65f9d9c9.png)
