### ISSUE TITLE
Store osm modifications in net.osmand.plus

### ISSUE THREAD

**Issue by ADepic** [osmandapp/Osmand#5728]
I don't know where they are stored, but if you backup the net.oamand.plus folder and reinstall island, you lose all your modifications.

**Comment by dmpr0** [comment]
Hi, thank you for the feedback. We check if we could add it to Google App Backup.

**Comment by ADepic** [comment]
I lost all my island notes a few hours ago because of this...

Now I only use favourites to store info because favourites are stored in net.osmand.plus.

Luckily I have my photo notes (phew)

**Comment by ADepic** [comment]
What is the Google app backup? I have a google-free phone

**Comment by dmpr0** [comment]
@ADepic Do you use Internal memory? Do you see files in net.osmand.plus folder when copied folder?

**Comment by scaidermern** [comment]
Look for a file called `osm_modification.gpx` located inside `net.osmand.plus/files/`.

**Comment by ADepic** [comment]
No that's way out of date. Its from when I last exported to gpx. These notes I hadn't exported to gpx sadly :(

**Comment by ADepic** [comment]
That was fast.

**Comment by ADepic** [comment]
Uhhhh... where are they stored? On the free (as in price) version of osmand, I can find it in net.osmand
