### ISSUE TITLE
Boat navigation: support waterway:fairway (navigation on polygons)

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#5733]
Example route from lon="12.652177" lat="53.274924" to lon="12.705074" lat="53.327257".

**Comment by xmd5a2** [comment]
At the moment we do not have a routing for the polygons. Many fairways are polygons, so now there is no easy way to add the opportunity to build a route on the fairway. For example, route from A to B will be built along the polygon boundary, which makes no sense
![screenshot from 2018-07-26 12-05-39](https://user-images.githubusercontent.com/5829014/43448102-ab3a37b8-94b5-11e8-9c92-f31a18e8b90f.png)

**Comment by vshcherb** [comment]
Support for navigation over waterway=fairway is added and enabled. So new maps will have it enabled 
https://github.com/osmandapp/OsmAnd-resources/commit/c5bde00ce876ef77b2ea22801e4b45b039c14d11
Maps will also contain seamark:type=fairway polygons but support for them will be disabled for now cause it has some inconsistent results when waterway=fairway is also present.
```
<!-- disable polygon routing to avoid intersection with waterway=fairway -->
			<!-- <select value="1"  t="seamark:type" v="fairway"/>  -->
```
P.S. routing.xml could be changed on sdcard directly
