### ISSUE TITLE
OsmAnd doesn't recognize an opening hours field

### ISSUE THREAD

**Issue by marmistrz** [osmandapp/Osmand#5737]
I have recently added opening hours to this building and fixed its name:

https://www.openstreetmap.org/way/230105382#map=17/42.01954/23.10228

I have downloaded the latest updates via OSM Live. While the changeset fixing the case of the building's name (from all letters in caps to only the first letter in caps) is recognized on the map, the opening hours are not shown at all.

It may be important that after entering the building details, the address is shown in caps, as if the changeset was not recognized.

F-Droid build, 3.0.4

**Comment by PaulStets** [comment]
Seems related to #6052, should be fixed now.
