### ISSUE TITLE
"Starting point too far from nearest road" when ON the road.

### ISSUE THREAD

**Issue by Bugsbane** [osmandapp/OsmAnd#574]
Hi there,

Whenever I try to use Osmand for routing, I constantly just get the following error:
"Error calculating route. Starting point too far from nearest road"

This happens even when the blue circle / arrow, indicating where I am is entirely on a road, even a main road, in a well mapped area of Toronto, Canada. It updates correctly as I move. I have location services turned on. It happens almost all the time.

I actually have this hunch that it may be something about running short of memory to calculate routes or something

I tried with version 1.5-ARM from the Fdroid repos and and nightly version #1796D on a Samsung Nexus S phone running Android 4.1.2.

**Comment by tapirbait** [comment]
Hi there, same issue here since upgrading to version 2.0.1. I'd like to hear what the solution was.

**Comment by vshcherb** [comment]
If that exception happens everywhere there could be 2 causes:
- map is corrupted (map needs to be downloaded) 
- installation (native library) corrupted - reinstall would help

Otherwise everybody wil report it, please try another nightly build for example
