### ISSUE TITLE
Supermarket appears as building

### ISSUE THREAD

**Issue by HubMiner** [osmandapp/Osmand#5740]
Shop=supermarket POIs that are also tagged as building, appear only as building in OsmAnd search by-name results, no mention of shop or supermarket. 

Expected search results: store first & building as secondary or not shown, or combined with store. Please check if this affects everything with multiple major tags, not just shop.

Sample node: https://www.openstreetmap.org/way/517482850

**Comment by scaidermern** [comment]
shop=supermarket was added on June 25th. I guess it was already too late to make it into July maps.

**Comment by vshcherb** [comment]
Please check July maps

**Comment by HubMiner** [comment]
Confirmed.
