### ISSUE TITLE
add highway=emergency_access_point as visible POI

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/Osmand#5745]
I think this can be helpful to make `highway=emergency_access_point` permanently visible on the map. Something like the `emergency=phone`

If I activate the access point in the POI option it is visible, but a lot of users dont know that the emergency access points existing and so they dont search for this type of poi.
If the point is permanently visible, it can be found fast in a case of emergency. 
Some of them are near streets and can be helpful also for car driver.

**Comment by fermi78** [comment]
All "emergency" should be visible and/or searchable in the "Emergency" category of POI
