### ISSUE TITLE
Text on the map (POI, Favorites) fails to display '('

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#5747]
Hi.

In the map OsmAnd fails to display the "(" of the favorite's name.

It looks like this happens only if there is a automatic wrap (new line) before the bracket.

Found with OsmAnd+ 3.0.4.

![screenshot_2018-07-28-12-02-36](https://user-images.githubusercontent.com/6921696/43369539-a6659188-9370-11e8-9005-2e113b9ce470.png)

![screenshot_2018-07-28-12-06-08](https://user-images.githubusercontent.com/6921696/43369542-b284b57a-9370-11e8-8279-6c09f245a5ed.png)

**Comment by vshcherb** [comment]
Fixed
