### ISSUE TITLE
Sometimes photo notes have different positions in JOSM than in osmand

### ISSUE THREAD

**Issue by ADepic** [osmandapp/Osmand#5751]
How come this is possible?
I checked one of my photo notes, and in properties they are stored like 18; 19; 39.49099999999 etc.

Can't they just be store as 18.49430?

Most the times the photo note is positioned correctly in JOSM, but sometimes it is incorrect.

This needs to be considered because it could lead to incorrect map data... 

Maybe this is a JOSM problem.

**Comment by vshcherb** [comment]
This is a standard for Image format. Please use GPX export of AV notes to have precise data.
