### ISSUE TITLE
Make a form to send faulty routing to osmand team

### ISSUE THREAD

**Issue by ADepic** [osmandapp/Osmand#5754]
@scaidermern suggested [something quite brilliant](https://github.com/osmandapp/Osmand/issues/2625#issuecomment-407387200) in this comment, and I think the osmand website should have a form to do what he suggested. 

He suggested that to improve the routing algorithm, the team needs to collect a large number of tests.

I think a form on the website would do that quite nicely.

The form should require users to upload a gpx file of the faulty routing. (Next to that section there should be a little link "How do I obtain this?" which will give step by step instructions with gifs on how to save / share the faulty routing's gpx file and send it to your computer.)

The form should require a email, so the team can contact the user if needbe. It must also require a description telling the team what is wrong and a screenshot showing the team what is wrong. Another field that should be required is a link / screenshot of routing on openstreetmap.org to show this is not a osm error but as osmand one.

The last thing I think the form should have is two input-boxes, one asking for the lattitude, longitude of the place you wer routing from, and the latittude, longitude of the place you were routing to.

The app should possibly notify the user somehow that there is a form online to submit faulty routing. That would also be necessary.

Once you have multiple instances of faulty routing, you can start tinkering with the engine to see what fixes all / most of these. This is much more accurate than fixing each routing issue one by one and relying on small sample sizes (e.g #2625)

EDIT: One more thing, have a dropdown with options of what kind of routing error it is, e.g "inefficient route", "avoids traffic lights unnecesarily" etc.

**Comment by vshcherb** [comment]
I think I will close that issue and even not keep for now cause there is no man-power today to investigate these cases anyway.
