### ISSUE TITLE
OsmAnd Maps crashes on attempt to navigate imported route (iOS)

### ISSUE THREAD

**Issue by CrapsJeroen** [osmandapp/Osmand#5757]
**What version of OsmAnd are you using, on what device and Android/iOS version?**
OsmAnd Maps version 2.1
iPhone SE 32GB
iOS 11.4.1

**Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?**
Offline Maps of Belgium (01/07/2018 02:00) and the World Overview (16/03/2018 12:13).

While loading the file attached to this message, the route is correctly added to my trips. The issue occurs when I try to navigate this route. The OsmAnd Maps application turns to black and closes after a very short delay.

Additional information: A friend of mine has used to same file on Android without any problems.

[test_route_crash_ios.zip](https://github.com/osmandapp/Osmand/files/2248243/test_route_crash_ios.zip)

**Comment by Yermo** [comment]
I am seeing this issue as well. iOS 11.4 iPhone 7.

**Comment by CrapsJeroen** [comment]
This issue was fixed in the recent 2.2 update of the OsmAnd Maps app.
