### ISSUE TITLE
Travel Guide articles incorrectly linked

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#5759]
Some travel guide articles are incorrectly linked.
- open Travel Guide
- search for Bunnik
- click on Bunnik
- article Bayeux (i.s.o. Bunnik) is opened

**Comment by PaulStets** [comment]
Fixed with https://github.com/osmandapp/OsmAnd-tools/commit/b232cd97d71920dd64229e61e960c67bf951d202. Needs map regeneration.

**Comment by ArjanOnwezen** [comment]
Still not working after latest Wikivoyage update

**Comment by ArjanOnwezen** [comment]
Thanks!
