### ISSUE TITLE
Shortcut taken or not depending on arrival point (shall always be taken)

### ISSUE THREAD

**Issue by Codain** [osmandapp/Osmand#5764]
Consider a routing which needs to go from https://www.openstreetmap.org/way/50561715 to https://www.openstreetmap.org/way/162596564. Turning right, the shortcut (https://www.openstreetmap.org/way/8300999) shall always (or never) be proposed. However a strange behaviour happens: It is proposed depending of arrival point. In both cases thos arrival points required to use the same both ways linked by the shortcut.

Cases where routing goes throught this shortcut (which is a good thing):
- from https://www.openstreetmap.org/way/226660426 to https://www.openstreetmap.org/node/1604077639
- from https://www.openstreetmap.org/way/226660426 to https://www.openstreetmap.org/node/1604077594
- from https://www.openstreetmap.org/way/226660426 to https://www.openstreetmap.org/node/1753109086

Cases where routing goes throught this shortcut (which is a bad thing):
- from https://www.openstreetmap.org/way/226660426 to https://www.openstreetmap.org/way/85316065
- from https://www.openstreetmap.org/way/226660426 to https://www.openstreetmap.org/node/5324552370
- from https://www.openstreetmap.org/way/226660426 to https://www.openstreetmap.org/way/85313961
- from https://www.openstreetmap.org/way/226660426 to https://www.openstreetmap.org/node/25210072

I use OsmAnd+ 3.0.4 with offline routing and OsmAnd Live enabled (update for this map: Aug 1st 2018 09:30 AM)

**Comment by vshcherb** [comment]
@Evgenij27 
BUG is in the routing engine, so the test should be added:
Now:
<img width="594" alt="screen shot 2018-10-17 at 01 58 26" src="https://user-images.githubusercontent.com/1042025/47054075-4365e280-d1b0-11e8-903e-137e8c4340b3.png">

After fix:
<img width="557" alt="screen shot 2018-10-17 at 01 57 30" src="https://user-images.githubusercontent.com/1042025/47054067-347f3000-d1b0-11e8-8dc2-1462641450aa.png">

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-core/commit/db655c2ea9d258dad55d9d21fc79fad3e7bd68e8
