### ISSUE TITLE
biergarten: include biergarten=yes

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#5768]
Currently the "biergarten" preset only searches for `amenity=biergarten`. However there are also restaurants, pubs etc. with a biergarten, usually indicated by `biergarten=yes`.

Searching for "biergarten" should include both `amenity=biergarten` and `biergarten=yes`.

**Comment by vshcherb** [comment]
Usually to make this trick we need to use fairly complex tag transformation as for "amenity=atm" and "atm=yes", gas_station=electric_charging.

So it ends up this object are not modifiable in OsmAnd itself. Until it becomes very popular we will avoid to introduce that complexity.

**Comment by scaidermern** [comment]
Oh. Isn't it enough to just look for this additional tag when searching for this type of POI? Sounds complicated :/

**Comment by vshcherb** [comment]
Search doesn't work with additional tags, it works only with poi types / sub types.

**Comment by pietervdvn** [comment]
Also see #6040 ; I've changed the tagging in OSM to use a separate node for the drinking water. Guess that is indeed simpler.

**Comment by scaidermern** [comment]
@pietervdvn But changing the data just for one end-user application is not a good solution.

@vshcherb Is there no way to make this possible? There are a lot of [similar sub tags](https://taginfo.openstreetmap.org/search?q=yes#values) (`biergarten=yes`, `drinking_water=yes`, `shelter=yes`, `bench=yes`, `atm=yes`, `bin=yes`, `toilets=yes`, `fireplace=yes` and so on). 

Can't you make `biergarten=yes`, `drinking_water=yes` etc. a POI type which then gets merged with the "real" POI type (`amenity=biergarten`, `amenity=drinking_water`)?

**Comment by vshcherb** [comment]
The tagging schema is correct and broken for the same time:
1. amenity=* represents main tag to search
2. *=yes represents extra facility

So basically there are 2 types of search: find me real amenities with Type T and find me anything that has facility B.

OsmAnd doesn't support 2 type  search naturally. Though the data is messy as well there is no indication when people will create 2 points for 2 POI's amenity=cafe and amenity=fuel_station or when they add food=yes. It looks like the extra features tag should have a special search.

For example, 
If you are looking for wifi, you are interested in Wifi points and not all possible amenities that has restricted or personal wifi connection.

**Comment by scaidermern** [comment]
I agree that OSM's tagging scheme is indeed not very ideal for these things.

**Comment by vshcherb** [comment]
Let me drag into 3.2 cause we want to test an idea of "duplicated" poi types in the data but we need to make sure the old software will handle this correctly.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-resources/pull/533

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-resources/commit/766be3542142ef3868d9f0b3cc846b59cc7a4492
