### ISSUE TITLE
Search history: include recently searched categories

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#5769]
It would be nice if not only specific POIs but also selected categories will show up in the search history. For example when searching for the generic category "restaurant". Afterwards "restaurant" doesn't show up in the search history. However it happens rather often to me that I will later search the same category again.

**Comment by dmpr0** [comment]
Also, we need to show in history, custom search poi categories.

**Comment by scaidermern** [comment]
Yay, thanks! :)
