### ISSUE TITLE
food category: remove natural=spring

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#5771]
`natural=spring` is an interesting POI but not really food. Nevertheless it gets shown when selecting the foot category.

**Comment by vshcherb** [comment]
The category is called sustenance, so it is viable there but it is not generic food I aggree

**Comment by scaidermern** [comment]
What does this mean? Has it been fixed? Springs are valuable but not the things I want to see when looking for a place to eat.

**Comment by scaidermern** [comment]
Nope, looks like nothing has changed with version 3.2.2.

![photo_2018-10-01_21-12-08](https://user-images.githubusercontent.com/1040784/46310117-ba9b5400-c5be-11e8-9731-d00970a4ab5e.jpg)

**Comment by shiftee** [comment]
I came here to create this exact issue.

@vshcherb - Can you give us more information as to why this was closed?

For others the "sustenance" category mentioned seems to be an OSM category: [here](https://wiki.openstreetmap.org/wiki/Template:Map_Features:amenity#Sustenance)

That category specifically mentions drinking water.

OsmAnd 3.7.4 (F-Droid) shows me a spring where the drinkable parameter is not set. This in theory could be a safety/liability issue for the project.

**Comment by vshcherb** [comment]
Yes it came from OSM category template here - https://wiki.openstreetmap.org/wiki/Template:Map_Features:amenity#Sustenance. 
We don't want to move it to another category cause it could break backward compatibility and there is no better category. It could be renamed or changed to Sustenance from Food. 

We also don't plan to remove Springs from POI information. To search cafes, bars more specific search should be used

**Comment by vshcherb** [comment]
Correction: indeed spring should be part of Natural category and not Food
