### ISSUE TITLE
Map sometimes disappears when creating osm note

### ISSUE THREAD

**Issue by matthijskooijman** [osmandapp/OsmAnd#5774]
While creating osm notes on the map, sometimes my map disappears. All the osmand interface remains working, except the map is blank. It seems like the current viewport no longer has a valid position somehow, since all marks in the list show a distance of 0m.

While the map is gone:
 - all marks show 0m distance
 - restarting the app does not seem to help
 - moving or zooming the map does not change anything (though the minimum zoom level message is still shown)
 - selecting or activating a marker seems to restore the map
 - selecting an osm edit shows the edit in the side pane, but does not restore the map
 - deleting a note (not necessarily the last) seems to restore the map

When the map disappears:
 1. The message "Osm changes added to local changeset" is shown
 2. Either directly after the message or at the same time (cannot remember), the map becomes blank
 3. After a few seconds, "could not draw selected area" appears

![screenshot_2018-08-02-16-56-13](https://user-images.githubusercontent.com/194491/43593458-0f5090e4-9678-11e8-8937-07e90d02feef.png)

I cannot reproduce this issue reliably, unfortunately...

Regarding when it does or does not occur:
 - I started mapping last week, then it did not occur at all. In think it first occurred one a few days ago, and then a lot more today. I suspect it might be related to the number of local osm changes, the ratio between pois and notes, or the number of notes created in a row...
 - after deleting a note, the issue seems to not immediately reoccur. Deleting more notes seems to postpone the issue longer, but not in a 1to1 way.
 - I cannot seem to reproduce it now (after creating two dozens of notes and deleting some, intermixing creates and deletes, which did reproduce the issue a few times)
 - I have not observed any relation between the location and whether it occurs

I'm using osmand+ 3.0.4 on a rooted Acer Icionia tab A1-810 running Android 4.4.2. I'm usimg offline vector maps, with Osmand Live enabled. I wanted to try the nightly version, but since maps and data are not shared, this is not feasible right now (I'm on a mobile connection).

**Comment by matthijskooijman** [comment]
I just triggered this issue once more, by selecting a poi edit and zooming in. I could not reproduce by following the same steps, though.

**Comment by Prusaker** [comment]
I confirm. I too meet this issue. Unfortunately, it's impossible to accurately reproduce it, but when you create points, the screen becomes empty from time to time. I know for sure that in older versions of the program this problem was not. I tested it on version 2.7.5, and there is definitely no such problem.

**Comment by Rpnpif** [comment]
I confirm also this issue with 3.0.4 release.

**Comment by Prusaker** [comment]
For several months, this fault does not occur. I tested on nightly builds.

**Comment by Rpnpif** [comment]
I agree with @Prusaker (v3.2.7).

**Comment by matthijskooijman** [comment]
I also have not observed this issue in the past few years, so I'm assuming it was fixed somehow. I'm closing this issue.
