### ISSUE TITLE
Moving a map marker deletes the user's edited marker name

### ISSUE THREAD

**Issue by gunnar22** [osmandapp/Osmand#5776]
I use map markers a lot and really appreciate that their name can be edited by the user. However, the marker's user-given name can become deleted due to something that looks like a bug.

Here is how to reproduce:
- long click to bring up the orange 'blob'
- click on Marker in the bottom toolbar to get a new marker flag on the map
- click on the newly created Marker on the map
- click on Edit in the toolbar
- write some text (under the heading: Enter new name:)
- save
- click on the newly edited Marker on the map
- click on Actions
- click on Change marker position
- move the map a little bit to change the marker position
- APPLY
- click on the newly moved Marker on the map
- Observe that the edited name has been deleted by OsmAnd during the move operation
and replaced by some automatically generated marker name, so that the user's text that was
entered at the "Enter new name:" prompt has been lost.
Version: OsmAnd+ 3.0.4, released 2018-06-11

**Comment by vshcherb** [comment]
Typically markers are filled in automatically and they don't have persistent names as favourites. This is unexpected behavior cause markers supposed to be immoveable

**Comment by gunnar22** [comment]
Here is a OSM and marker scenario.
I often place a new marker when I am out walking and see something to edit in OSM. In OsmAnd I edit the marker on location to tell myself what it is. If I have placed the marker with a "fat finger" on the screen, typically a little bit imprecise, it is very useful to be able to move it slightly, to get the best possible accuracy in OSM. I do the OSM work on the PC when I am back home. I need a descriptive text on the marker. Without a text I will easily forget what I saw, and I can just skip the whole editing. 
As you now know: I must first place the marker correctly, and then edit it. If I reverse this sequence, then I risk losing my text.
It does not feel right to use Favourites for this purpose. There is not any "favourite" quality about a collection of details to be edited into OSM, and I get rid of the markers after editing. Dear developers, please be nice :-) don't take away useful functionality, and please modify the current behaviour that can delete my text.

(Version 3.1.5)

**Comment by vshcherb** [comment]
we're not trying to delete it, we just have now 2 unexpected scenarios 1) we want to change it 2) we don't want to change it
2) scenario showed up when we allow to modify the name. Let's whether it is difficult to change now.

**Comment by gunnar22** [comment]
Here is a suggested solution:
1. Auto genereate the name when the marker is placed (i.e., no change from current behaviour).
2. Do not auto generate the name again for this marker. (Particularly, not when it is being moved). The code has to keep track of whether a marker has just been created (and does not have a name) or is moved (and already has a name). Auto generate only in the first case, not the second.
3. Add a new menu item in (three dots) Actions menu: "Generate name (based on location)"

This will be stable, unsurprising, and give the user all possibilities.
