### ISSUE TITLE
Boat Routing issues

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#5777]
Some users are really excited about our ability of marine routing, claim it could be truly a killer feature for OsmAnd,. Unfortunately, as it is implemented today, it seems buggy: Works rather well in channels and along rivers, or along dredge channels in lakes, and similar. But it also has major issues at sea along shorelines and around islands, see screenshots attached.

- First one is fine in principle, perfectly follows channels in the Venice lagoon. But is of course not the short path most boats would actually take between start and destination. (Channel seems over-preferred)
- Second one is even worse: Routing prefers going up and down an inland river, rather than leading to the destination point.
- Third one routes partially over land, then perfectly follows a narrow bay, then again fails to lead to the final destination.

<img width="135" alt="screenshot_2018-08-02-23-49-09_" src="https://user-images.githubusercontent.com/845735/43616189-8bbc7d80-96bb-11e8-8190-4dadb644a538.png"> <img width="135" alt="screenshot_2018-08-02-23-56-08_" src="https://user-images.githubusercontent.com/845735/43616192-9274f7ce-96bb-11e8-883f-9ed00c69ea45.png"> <img width="135" alt="screenshot_2018-08-03-00-06-24_" src="https://user-images.githubusercontent.com/845735/43616193-948f7e58-96bb-11e8-8018-5a6c8e328005.png">

I wonder how complex it would be to improve the behavior? Are we talking a mere parametrization of the routing.xml, or is this a much more fundamental issue?

**Comment by sonora** [comment]
In essence, the first but huge step would be having a combination of "straight line" routing plus circumventing coast lines in some defined minimum distance of say 300m.

**Comment by Evgenij27** [comment]
Boat navigation uses only canals and fairways for navigation. Navigation using coast lines is not implemented now. We may add it in the future.
