### ISSUE TITLE
3.0.4 update, lost ability to specify track color

### ISSUE THREAD

**Issue by dmpiq** [osmandapp/Osmand#5786]
I run seven different gpx files on Osmand, and I put code at the top of each .gpx file to load them in the color I specify:

`<metadata>
	<name>Black</name>
    <extensions>
        <color>#BB000000</color>
    </extensions>
</metadata>`

Since the update to 3.0.4, my colors are ignored and all tracks show up as the default color.

**Comment by baerrus** [comment]
Note that adding <extensions>/<color> tag will prevent a GPX file from loading into Garmin Basecamp as it would not validate with the schema. Alternatively, since most tracks come from Garmin anyways, I would propose to support Gamin's way at least for read only:

    <extensions>
      <gpxx:TrackExtension>
        <gpxx:DisplayColor>Green</gpxx:DisplayColor>
      </gpxx:TrackExtension>
    </extensions>

**Comment by dmpiq** [comment]
@njohnston thanks, that works.  Next thing I'm going to try to do is to specify weight for the tracks, and making them dashed or dotted.  You have any quick clues to help?
