### ISSUE TITLE
Serious trouble with opening_hours

### ISSUE THREAD

**Issue by gunnar22** [osmandapp/Osmand#5792]
OsmAnd may report wrong information about when a restaurant is open.
See:
https://wiki.openstreetmap.org/wiki/Proposed_features/Time_domains
https://wiki.openstreetmap.org/wiki/Key:opening_hours

I suspect that OsmAnd does not understand the rules/grammar of OSM Key:opening_hours.
If that is the case I suggest that it would be better for OsmAnd (as a temprary solution) to NOT display the current open/closed status (instead of, as now, taking the chance and display something that may be totally bogus). Of course I hope and recommend that it can be fixed and comply with the rules soon.

![screenshot_2018-08-05-15-50-47-](https://user-images.githubusercontent.com/30504902/43689308-dbf43e8e-98f8-11e8-8d16-e470a6df6327.png)

Data in OSM is: opening_hours="16:00-24:00; Fr 16:00-01:00; Sa 14:00-01:00; Mo,Su off". 
This is perfectly legal and verified at
http://projets.pavie.info/yohours/
see next figure.
This restaurant is closed on Monday and Sunday. The opening hours is first given as a general 16:00-24:00; and then overridden by more specific times for Fr and Sa, and finally Mo,Su off. Rules following a semicolon override those before it. The screenshot was taken on Sunday at 15:50. The restaurant was then closed. The problem is that the status says that it opens at 14:00. Where does that come from? The only 14:00 is on Saturday. Besides that, it was Sunday, and it does not open the next day (no day is shown so that would be the same or next day), it opens two days later (Tue) at 16:00. (I recommend showing a day when first opening is not later on the current day).

![yohours-capture](https://user-images.githubusercontent.com/30504902/43689366-b81fa164-98f9-11e8-944e-946115e52c25.jpg)
Verification of the opening_hours specification.

![screenshot_2018-08-05-21-03-18-](https://user-images.githubusercontent.com/30504902/43689372-d178cb4a-98f9-11e8-8871-0b88a4785f32.png)
Screenshot later on Sunday. Here the open/closed status in OsmAnd says that the restaurant is open, but that is wrong. It only displays the first rule (Mon-Sun 16:00-24:00) and skips the following overriding rules.

I suggest:
1. Don't display any current status.
2. Fix the underlying problem of complying with the opening_hours specification
3. Reintroduce the status in correct form.

Thanks a lot to the developers for working on OsmAnd, which is a great app.

- gunnar22

**Comment by scaidermern** [comment]
As you can see from your screenshot even http://projets.pavie.info/yohours/ fails to interpret it correctly. Look at Sunday on which this restaurant is closed but http://projets.pavie.info/yohours/ shows it to be opened form 14:00-01:00 :/

But of course you are correct that this is a bug in OsmAnd. Not the easiest format to parse, though.

**Comment by gunnar22** [comment]
@scaidermern. Actually, http://projets.pavie.info/yohours/ is entirely correct. 
If you look into
https://wiki.openstreetmap.org/wiki/Proposed_features/Time_domains
under the heading "Time part", item 4:
"For time intervals, if the start time is later than the end time, the time interval wraps onto the next day.
Example: 22:00-06:00
This is equivalent to 00:00-06:00, 22:00-24:00.
Note that while the wrap is onto the next day, it is treated as if it belongs to the same day (see following examples which explain how this is meant)."

This is also the case for the restaurant that I have in my example. The late Saturday wraps into Sunday, but is treated as if it belongs to Saturday. Apart from the midnight wrap, Sunday is closed.

I guess that this has been well thought through by the community and evolved over time into a solution that is easy to handle and makes sense.

/gunnar22

**Comment by gunnar22** [comment]
The grammar is specified here
https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification
Should be quite "mechanical" to take care of this since all the hard thinking has been done already and documented so well. Maybe there are third-party open source code or libraries available too(?)

/gunnar22

**Comment by scaidermern** [comment]
@gunnar22 Oh you are correct, sorry.

Yes, there are open source libraries available for `opening_hours`, for example https://github.com/opening-hours/opening_hours.js which is used at http://openingh.openstreetmap.de/evaluation_tool/.

Maybe OsmAnd should use this library, too. Not quite ideal since it is implemented in JavaScript. However this solves a lot of hassle since OsmAnd developers don't have to solve these bugs on their own any longer. This library is also used by JOSM (see [ticket 9157](https://josm.openstreetmap.de/ticket/9157)).

**Comment by vshcherb** [comment]
OsmAnd doesn't unerstand that format properly with exception rules.
It is better to specify:
opening_hours="Tu-Th 16:00-24:00; Fr 16:00-01:00; Sa 14:00-01:00" which will work  and is much better readable

**Comment by scaidermern** [comment]
@vshcherb but this is nevertheless a bug in OsmAnd, not in the data, isn't it? So this is a "won't fix"?

**Comment by gunnar22** [comment]
@vshcherb If you're serious and consistent, then you ought to remove the calculation and presentation of "Open from xx:xx" and "Open till xx:xx".
It can't be trusted. Much better, then, to only present the raw data verbatim.
