### ISSUE TITLE
Emergency access points not rendering

### ISSUE THREAD

**Issue by StanislavTichy** [osmandapp/OsmAnd#5793]
Emergency access points not rendered in osmand at any zoom level. These are important outdoor signs used for telling emergency operator an exact location in low density areas like woods or national parks. They are inside database, reachable by search option but not displayed on any map.

http://i67.tinypic.com/i36sg9.png
http://i66.tinypic.com/35lhw93.png
http://i67.tinypic.com/2yjvujb.png
 

Wiki https://wiki.openstreetmap.org/wiki/Tag:highway%3Demergency_access_point

Samsung Galaxy S4 mini, Android 4.4.4, offline maps in osmand 3.0.4

**Comment by fermi78** [comment]
All "emergency" should be visible and/or searchable in the "Emergency" category of POI

**Comment by xmd5a2** [comment]
![Screenshot from 2020-11-17 18-50-57](https://user-images.githubusercontent.com/5829014/99412518-df212a00-2905-11eb-894a-653d937a5a15.png)
