### ISSUE TITLE
Cycling route shows repeatedly

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#5796]
Example place in Bonn, Germany: https://www.openstreetmap.org/#map=19/50.73883/7.11314
![2018-08-06 15 44 08](https://user-images.githubusercontent.com/9365308/43717248-96fd0b2a-998f-11e8-8118-9f2ec4767660.jpg)
![2018-08-06 15 44 01](https://user-images.githubusercontent.com/9365308/43717249-971c4c1a-998f-11e8-8bcf-f1bb7c87454b.jpg)

**Comment by xmd5a2** [comment]
https://github.com/osmandapp/OsmAnd-resources/commit/ca9bb901d6e437ab000f524b29f059a8385c04bd
