### ISSUE TITLE
[Feature Request] Adding Driving Analytics

### ISSUE THREAD

**Issue by esrefozturk** [osmandapp/Osmand#5799]
Hi all,

I am planning to open a pull request for adding driver analytics to OsmAnd using an SDK. I wanted to create an issue beforehand so that I can get early feedback from people.

Driver Analytics will include risk scores of the driver that is calculated using many parameters like phone usage of the driver while driving, hard breaks, sudden turns, speed limit violation and many other things. This information will make people realize their mistakes and they will be getting better scores as they progress. Hopefully, roads will be much safer when people use the app.

Any feedback will be appreciated.

**Comment by scaidermern** [comment]
How will you know whether the driver uses the phone or a passenger?

Is GPS really accurate enough to detect hard breaks and sudden turns, especially in cities?

I can't imagine this feature will make driving any more safer.

**Comment by esrefozturk** [comment]
Hi  @scaidermern ,
Only GPS is not enough, other sensors like accelerometer and gyroscope are also used to determine such events.
Driver and passenger patterns are different for these sensor values so we can distinguish them. 
If people can see their dangerous aspects of their driving, hopefully, they will able to correct them.

**Comment by vshcherb** [comment]
So far OsmAnd stays away from external SDK cause it could lead to leaking user data and it could also make the software less open-source as it is today.
