### ISSUE TITLE
Buildings disappeared after latest Android update

### ISSUE THREAD

**Issue by MeCias** [osmandapp/Osmand#5800]
Hello,

after the latest android update 3.1.2 the buildings on the offline maps disappeared (only house number are still displayed) and I am not able anymore to select a POI. If I pick one I get the street name displayed but there is noting to select and nothing else around.

![screenshot_20180807-083700](https://user-images.githubusercontent.com/4476171/43758802-89a5eabc-9a1d-11e8-803a-01b2bc5e9b82.png)

![screenshot_20180807-083941](https://user-images.githubusercontent.com/4476171/43758807-8c3b13ba-9a1d-11e8-8636-eaa1860d0318.png)

**Comment by scaidermern** [comment]
Did you activate "Configure map -> Hide -> Buildings" by accident?

**Comment by MeCias** [comment]
Hi,

thanks for the quick response. I just checked and there is nothing hidden by configuration. It just changed with the update yesterday evening.

**Comment by MeCias** [comment]
Seems to be fixed with the new release 3.1.3
