### ISSUE TITLE
Measure distance: position on the bottom

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#5802]
In Measure distance if center of the screen is not in center, center icon is hidden by toolbar. 
![screenshot_20180807-121957](https://user-images.githubusercontent.com/9365308/43766967-87280cc4-9a3c-11e8-96a6-ac007b1acebb.png)
![screenshot_20180807-122043](https://user-images.githubusercontent.com/9365308/43766969-87516736-9a3c-11e8-89e8-1bd76db9e013.png)

**Comment by vshcherb** [comment]
need to be tested
