### ISSUE TITLE
Osmand Live suspected to keep both old and new highways

### ISSUE THREAD

**Issue by Rpnpif** [osmandapp/Osmand#5803]
To reproduce :
1. Modify significantly a highway on Openstreetmap (Of course, as in the real way).
2. Wait that the modification is seen in OsmAnd by Osmand Live (some minutes or hours after).
3. The drawings is right but when a routing is calculated, It seem calculated with the old highway before the modification.

Another user confirmed this issue with a new roundabout junction.

I do know a user that has observed the same issue with the monthly updates so only Osmand Live is concerned.

Expected : 
OsmandLive should use only the new drawing to calculate the routing.

Regards.

**Comment by pietervdvn** [comment]
This can be enabled via the 'OsmAnd developmen' plugin, where an option 'OsmAnd Live navigation' can be enabled.

AFAIK, this is somewhat experimental and therefore disabled by default.

**Comment by scaidermern** [comment]
OsmAnd Live navigation should be enabled by default meanwhile as far as I know.

**Comment by vshcherb** [comment]
should be fixed already please provide an example fi you have still
