### ISSUE TITLE
[Feature Request] In OsmEdit plugin, allow login through osm website.

### ISSUE THREAD

**Issue by itzikiap** [osmandapp/OsmAnd#5804]
I've signed into openstreetmap.com using Google OAuth, so I can't log in using user and password.
StreetComplete implemented it and it works well for me, however I would like to use osmand for adding poi.

thanks

**Comment by StanislavTichy** [comment]
Itzikiap: Please do all edits of map responsibly with great care. It is better to use proper editor like Vespucci if you plan to add more than few POIs. Osmand or street complete are not primarily meant to modify map. Thank you in the name of community.

**Comment by itzikiap** [comment]
I have no intention of ruining anything, of course. But I know I can fill a lot of missing information in my area, instead of just waiting for "somebody" to do it. 
Using Osmand is the most convenient way for me and it would be discoraging to have to resort to other apps.
But of course I'll try to be as complicit and precise as I can.
Is this the reason this feature was not implemented by now?

**Comment by dmpr0** [comment]
Already implemented both Android and iOS version.
