### ISSUE TITLE
Coastline land disappears on close zoom.

### ISSUE THREAD

**Issue by tico-tico** [osmandapp/Osmand#5817]
It happens at lat 58.145, lon 38.780 while using Osmand 3.1.3 free with the official maps.

Original image from the OSM site:
![osm](https://user-images.githubusercontent.com/10702026/43897494-d09e9996-9be4-11e8-8f03-a795fa84f553.png)
And two Osmand images with different zoom level.
![1a](https://user-images.githubusercontent.com/10702026/43897579-320f742a-9be5-11e8-82c3-c144eddf6c7d.png)
![2](https://user-images.githubusercontent.com/10702026/43897591-39e315e4-9be5-11e8-925e-a06b40720cdf.png)

I know there are plenty shoreline-related issues here on the tracker, but i'm not sure if they have the same origin as mine.

UP:
It look like the coastline is broken even more (unrelated to this issue):
![broken](https://user-images.githubusercontent.com/10702026/43899719-7e1042c2-9beb-11e8-8be3-166871a5fcc2.png)
Osmand vs self-made Mapsforge map
![compare_](https://user-images.githubusercontent.com/10702026/43912574-4f7cfeb2-9c0b-11e8-857b-d65dd247eaba.png)

**Comment by VacheMeuh** [comment]
You have the same issue i have at lat 48,6383591, lon -2,0258745, but i use the paid live option.
