### ISSUE TITLE
Map sources do not work [Solved]. Plus some new ones

### ISSUE THREAD

**Issue by gunnar22** [osmandapp/Osmand#5818]
Some of the map sources in OsmAnd don't work, i.e., tiles that OsmAnd downloads from a server. I have done some research and found some solutions. For Statkart Topo (NO) the topo number has been upgraded to 4, (see below). For Eniro, https does not work, however, http works.
There are also two new map sources that I discovered:
Norway's official 1:50000 raster/paper map of the whole country, and
Norway's official nautical map.

If a user reads this, I would like to remind that the user can edit (add) these directly in OsmAnd on the device (phone) under Configure Map / Map Source... / Define/Edit

Hopefully, the developers will fix this too, so that it works "out of the box".

-----

Statkart Topo (NO)
old, does not work:
```
https://opencache.statkart.no/gatekeeper/gk/gk.open_gmaps?layers=topo2&zoom={0}&x={1}&y={2}
```

Statkart Topo4 (NO)
works:
```
https://opencache.statkart.no/gatekeeper/gk/gk.open_gmaps?layers=topo4&zoom={0}&x={1}&y={2}
```

Eniro Map (NO,SE,FI,DK,PL)
old, does not work:
```
String getTileUrl(int z, int x, int y) {return "https://map.eniro.com/geowebcache/service/tms1.0.0/map/"+z+"/"+x+"/"+((1 << z) - 1 - y) + ".png";}
```

Eniro Map (NO,SE,FI,DK,PL)
works:
```
String getTileUrl(int z, int x, int y) {return "http://map.eniro.com/geowebcache/service/tms1.0.0/map/"+z+"/"+x+"/"+((1 << z) - 1 - y) + ".png";}
```

NEW: (1:50000 raster/paper map of whole Norway)
Statkart Toporaster3 (NO)
```
https://opencache.statkart.no/gatekeeper/gk/gk.open_gmaps?layers=toporaster3&zoom={0}&x={1}&y={2}
```

NEW: Norway's official nautical map
Statkart Sjokartraster (Nautical) (NO)
```
https://opencache.statkart.no/gatekeeper/gk/gk.open_gmaps?layers=sjokartraster&zoom={0}&x={1}&y={2}
```

-gunnar22

**Comment by gunnar22** [comment]
Hi developers!

I have done the research for you. If you follow up this issue and do some minor edits then these Map Sources will start working again.
The issue is this: Some map sources stopped working. Editing the URLs will solve the problem

-gunnar22

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/osmandapp.github.io/commit/6003a8bbe95f31d166cb973084fd2e1cd3cd3d00

**Comment by simurq** [comment]
> Statkart Topo4 (NO)
> works:
> 
> https://opencache.statkart.no/gatekeeper/gk/gk.open_gmaps?layers=topo4&zoom={0}&x={1}&y={2}

Are you sure that it works? Fail to see any tile downloaded... Can you pls verify on your side as well? Thanks!

**Comment by gunnar22** [comment]
I tested Statkart Topo4 (NO) now, in OsmAnd+ 3.2.7, and it works; downloads tiles and displays them.
