### ISSUE TITLE
Latest nightly build (10-Aug-2018, around 1:00pm Eastern Standard Time US) crashes during launch

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#5824]
What version of OsmAnd are you using, on what device and Android/iOS version?

OsmAnd night build released today (10-August-2018) at about 1:00pm Eastern Standard Time, on Samsung Galaxy S7 Edge, Android 8.0.  I can't give  you the exact build number of OsmAnd because of the crash.

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

Offfline

This nightly build crashes upon launch every time.  I installed it by downloading it through the OsmAnd Builds menu option in whatever previous nightly build I was using (from several days ago, not sure exactly when, and of course downloading the latest one overwrote the .apk file).  I tried deleting ind.cache and regions.obcf (or whatever the extension is) to see if that would help, but it doesn't.  The files are NOT being recreated during launch, so whatever it is, is happening before it gets to that point.  An exception log is NOT being generated.

I'll see if I can find an earlier nightly build that works and report that back.

**Comment by sonora** [comment]
The built number is always visible under Android's Settings/App manager.

@vshcherb I can confirm this: 
25626m fails to launch, our latest nightly of 2018-08-09 (25612master) seems the last stable one. Hope it is not in the 3.1.5 release of Aug 10.

**Comment by MAlfare** [comment]
Every version newer than 25612, including 3.0.0.#25628,  crashes immediately after start.
No entry in log-file

**Comment by Zahnstocher** [comment]
It is fixed:
https://github.com/osmandapp/Osmand/commit/65a8abe29cbaca57cb5e9aa2eeff83d8d717433c

Thanks!
Fix confirmed. :-)

**Comment by jfburke3** [comment]
@sonora Thanks for that tip, it never occurred to me to look there.

The beta 3.1.5 release in the Play store appears to be stable.  I just installed it on my S5, and it opens all the way.  

Concur with @Zahnstocher .  Installed latest nightly build on my S7, and it is fixed in nightly build 3.2.0#25631m released 2018-08-11.

Thanks for the quick fix, guys!
