### ISSUE TITLE
When Search fails, the "tell us about this" area includes a button with text in Cyrillic

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#5827]
When you use Search to look for (e.g.) an address, and there is no result found, the bar across the bottom where it says "No results? Tell us about this" includes a button with Cyrillic text, even though my phone and OsmAnd are configured to use English.

![osmand tell us about this cyrillic](https://user-images.githubusercontent.com/11140831/43981564-57a85798-9cc0-11e8-8b4e-11922883b4ad.jpg)

**Comment by vshcherb** [comment]
Fixed
