### ISSUE TITLE
Provide changelogs for minor updates

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#5830]
Currently there is no changelog for minor updates, at least I fail to find any.

The last few days there have been multiple minor updates (3.1.3, 3.1.4, 3.1.5). Unfortunately it is unclear how important they are regarding bug fixes and minor improvements. Especially if I'm on mobile I would like to know if it is worth upgrading or if I will waste my rather limited mobile data volume (German user here...).

Providing a short changelog of important fixes would be really nice.

**Comment by njohnston** [comment]
The developers create a branch in git for each major release, so while it's not quite a changelog, you can look at commits in that branch, for example [r3.1](https://github.com/osmandapp/Osmand/commits/r3.1).

The changes are usually for crashes and minor problems, so if you haven't had any problems like that, I wouldn't rush to install the new version.

**Comment by scaidermern** [comment]
This isn't really helpful, sorry.

The commit messages (e.g. "fix possible NPE) don't tell me which feature is affected.

Also I'm not using OsmAnd daily. So I can't always tell if I have problems with a particular version. Moreover maybe I'm using feature A today and will use feature B tomorrow. So while the crash doesn't occur today it could occur the next day.

Even if I have crashes there is no way to know whether the update will fix it without proper changelogs.

**Comment by vshcherb** [comment]
I do understand that concern but mostly all minor releases are all bug fixes. After first major release all features are frozen.
