### ISSUE TITLE
Offline maps only working/visible when downloading thru the menu direct after first start. 

### ISSUE THREAD

**Issue by bartatgithub** [osmandapp/Osmand#5834]
Dear 

Offline maps only working/visible when downloading thru the menu direct after first start. 
Downloading offline maps from settings menu after first start works but maps will not be working/visible, still they are downloaded. 

Osmand~ Version 3.0.4 - f-droid 
LineageOS 14.1
Android 7.1.2

App runs on internal storage, maps from external SD-card. 

Deleted and reinstalled Osmand~ gives the same problem.

**Comment by vshcherb** [comment]
The permission should be provided and the settings should be changed very likely before the data downloaded.

**Comment by bartatgithub** [comment]
Hi 

Could you explain this more clear with steps to follow or is there some webpage with the steps to follow? 
Thanks! 


Regards 
Bart

**Comment by vshcherb** [comment]
I'm not sure if I understand initial issue itself, mostly because I don't know how to reproduce it. 
In general settings there is a location where the maps are downloaded if you didn't change it and first maps are stored in a similar locations as all other maps, there should be no issue at all!
Of course you can download the maps manually and put it yourself http://download.osmand.net/list.php

**Comment by bartatgithub** [comment]
Hi 

Thanks, will check later out that that will work.  
Anyway, i will try to explain more properly step by step: 


What i did: 

1 Installed Osmand thru F-Droid. 
2 Run Osmand and looked at it, without direct downloading maps
3 Few day’s later downloaded some maps and wiki info. 
4 But maps where never visible but they where in the list of downloaded maps 
5 Downloaded other map, same problem 
6 Maps where never visible but they where in the list of downloaded maps 
7 Erased Osmand

Reinstall: 

1Installed same Osmand thru F-Droid. 
2 Run Osmand and thru the first time popup, that asked if i want to download some maps, i direct downloaded same maps
3 Maps are visible, and they work, even like the wiki info pages


Maybe it’s my Android system, settings or the use of an external SD-Card (not for the app, only for the maps). 

Regards
Bart
