### ISSUE TITLE
Request a location/pin from osmand using intent

### ISSUE THREAD

**Issue by gsantner** [osmandapp/Osmand#5835]
Hi! I want to request a freely selectable position from osmand, frommy app eg using intent. The target is to not download maps separately, and ship libs over and over again in apps, but just request location from osmand/gmaps, where the user also has his favourites and preferred view options in.

Is this possible currently with osmand? If not, is this is something that is likely to get in?

(ref use case: https://github.com/gsantner/markor/issues/308 )

**Comment by vshcherb** [comment]
Yes we have pretty extended list of API's, I think which you requested via Intent or AIDL. Please check full api list here https://github.com/osmandapp/osmand-api-demo.

**Comment by gsantner** [comment]
thx!
