### ISSUE TITLE
Offer Online Search from the start

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#5839]
Spillover from #4735: You only get to see the 'Search Online' button after a full round of offline search has finished, which can easily take several minutes under some circumstances. I guess we need to cater for situations where you would like to use online search immediately, i.e. can we move the button to the top and display immediately?

**Comment by vshcherb** [comment]
I'm against using online features by 2 reasons:
1) we're not hosting this online features
2) once people get offline they could be very confused with search results

though in that case I would say it is an easy call to do.

**Comment by vshcherb** [comment]
Online search is available in the category underneath. We will focus on search speed soon, so it should not be an important issue.
