### ISSUE TITLE
Coastline rendering issue

### ISSUE THREAD

**Issue by VacheMeuh** [osmandapp/Osmand#5841]
Here is the issue : i edited the coastline around Saint Malo (France) and updated my OsmAnd Live (paid version). The version of OsmAnd is 3.0.4 on Android with paid version.
Here is before the update : http://chocoistoolate.000webhostapp.com/before.png
After the update : http://chocoistoolate.000webhostapp.com/after.png
Osm website version : http://chocoistoolate.000webhostapp.com/osm.png

Just edited coastline geometry and got totaly corrupted.

**Comment by VacheMeuh** [comment]
http://chocoistoolate.000webhostapp.com/After.png

**Comment by vshcherb** [comment]
Bug is related to World seamarks object, if you delete it will be gone. We will try to fix that next map won't contain it.

**Comment by vshcherb** [comment]
New world seamarks generated
