### ISSUE TITLE
Mistake in offline navigation 

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#5847]
When calculating a route from a start point (Lat 32.70096 Lon 13.1442) to Destination (Lat 32.52710 Lon 13.21698) (Libya), OsmAnd calculates 213 km as a circle, while the actual distance between the points is 21 km. 
![screenshot_20180810-111119](https://user-images.githubusercontent.com/40493090/44038482-8f97876c-9f1f-11e8-89bf-8ad10409a63b.png)
![screenshot_20180810-111319](https://user-images.githubusercontent.com/40493090/44038485-91348d68-9f1f-11e8-978c-adb583995595.png)

**Comment by Rpnpif** [comment]
Hi,
I saw that this way has a wrong direction which is fixed some minutes ago.
Here : https://www.openstreetmap.org/way/153035293

It is perhaps the explanation of your issue. Please update in some hours or minutes your map.

I think that OsmAnd had not bug here.
Regards
