### ISSUE TITLE
Crashing on opening Public Transport Prague

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#5848]
When tapping on some of the metro icons or bus station icons on the Prague map, the app hangs completely and then crashes.

**Comment by alyonapinchuk** [comment]
The same issue can be seen on the Tokyo map.

**Comment by alyonapinchuk** [comment]
The app also hangs on tapping bus stops icons in Minsk. 
xiaomi redmi 3, miui 9.6, Android 5.1.1 OsmAnd 3.2.6

**Comment by MadWasp79** [comment]
fixed with https://github.com/osmandapp/Osmand/pull/6443/commits/f7d3e72fb113f346e11e420bb591fbcb752bbc30
