### ISSUE TITLE
[Feature request] Show ID of POI when selecting it

### ISSUE THREAD

**Issue by matthijskooijman** [osmandapp/Osmand#5850]
Could the ID of a POI be shown when selecting it on the map (at least for edited / newly created POIs)?

I've used OsmAnd to add new POIs to OSM, which works rather well. However, in some cases I would (while riding my bike) add a lot of POIs (mostly benches and other simple stuff) during the day. Then in the evening, I would upload them to OSM, but often I group related, adjacent changes together in one changeset. However, it's now not so easy to relate changes shown on the map to changes shown in the OSM Edits list (where you can select multiple ones for upload). Showing the id on selected POIs would improve this situation, while being fairly to implement (I expect).

How does that sound?

**Comment by vshcherb** [comment]
ID of poi is part of openstreetmap link which is context menu when editing plugin is enabled

**Comment by matthijskooijman** [comment]
@vshcherb, I believe that only applies to uploaded (or rather, downloaded as part of the map) POIs. My request is mostly about locally added, not yet uploaded POIs with a negative ID, which do not have an OSM link AFAICS.

**Comment by vshcherb** [comment]
So your request is to display negative id in the context menu.

**Comment by matthijskooijman** [comment]
Correct.
