### ISSUE TITLE
Change the color of the bottom panel in night mode 

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#5865]
When the map is switched to night mode, while navigating, the bottom panel with buttons remains white. It is not really convenient in the darkness. It would be nice to have an opportunity to change the color of this panel to black as well. 
![f8a1e7c3-84a5-4e2f-aa3c-075ea607670f](https://user-images.githubusercontent.com/40493090/44144224-499aaaca-a08f-11e8-82ed-f83bcc33b524.jpeg)

**Comment by vshcherb** [comment]
https://stackoverflow.com/questions/29069070/completely-transparent-status-bar-and-navigation-bar-on-lollipop
