### ISSUE TITLE
Transliteration should be in the target alphabet of the set language

### ISSUE THREAD

**Issue by miklcct** [osmandapp/Osmand#5868]
When the transliteration is set in the map language, if the name does not exist in the selected language, the local name is transliterated. However, no matter what the map language is selected, the name is transliterated into the Latin alphabet, not in the alphabet of the selected language.

For example, if I select Russian as the language and switch transliteration on, I expect all local names to be transliterated into the Russian alphabet, not the Latin alphabet.

**Comment by vshcherb** [comment]
We have only transliteration to English

**Comment by miklcct** [comment]
In such case please modify the UI such that the transliteration option does not appear in languages other than English.

**Comment by vshcherb** [comment]
It still make sense for other languages. In case you don't read chinese but almost all people could read english leters

**Comment by miklcct** [comment]
Sorry, but in my experience in travelling to Russia, most of the people there have no knowledge of English, creating a "language barrier".

Related #4763
