### ISSUE TITLE
Is Osmand project totally free? 

### ISSUE THREAD

**Issue by code4rox** [osmandapp/Osmand#5869]
I know the Osmand openresource project but I want to know, is there any resources like (icons, layouts ,libs) or any thing that have non free services ?

**Comment by code4rox** [comment]
@njohnston Thanks for this info can u tell me which icons and graphics are not freely licensed?

**Comment by vshcherb** [comment]
The question is rather vague and there is no "FREE" concept when the code is open, please check LICENSE for all details
