### ISSUE TITLE
Unexpected routing / Map issue?

### ISSUE THREAD

**Issue by bitboy85** [osmandapp/Osmand#5871]
Hi,

please compare those 2 routing suggestions.
1. https://www.openstreetmap.org/directions?engine=osrm_car&route=49.7959%2C6.6893%3B49.7852%2C6.6898#map=15/49.7905/6.6891

2. https://www.openstreetmap.org/directions?engine=graphhopper_car&route=49.7959%2C6.6893%3B49.7852%2C6.6898#map=15/49.7905/6.6890

osmand routing is the same as osrm in this case, but i'm wondering why 2 roundabouts are preferred instead of a straight road.

**Comment by vshcherb** [comment]
This is confusing with rendering but it is explainable with data
> https://www.openstreetmap.org/way/341802494 - tertiary (more priority)
> https://www.openstreetmap.org/way/341802488 - unclassified (less priority)
