### ISSUE TITLE
Tile (sqlite) map expiration time issue.

### ISSUE THREAD

**Issue by tico-tico** [osmandapp/Osmand#5883]
While trying to understand why my super-duper-amazing (he-he) map is getting deleted by Osmand i did some code reading and found that when you're calculating the expiration time in milliseconds you're using the `int` type.
But imagine that someone want the expiration time to be equal half a year:
`262800 min * 60 * 1000 = 15768000000`,
it's way bigger than 4-bytes `int` can consume. I'd change the var type to `long` 

https://github.com/osmandapp/Osmand/blob/990842d7756707652d59b9a0939aa501d19db768/OsmAnd/src/net/osmand/plus/SQLiteTileSource.java#L46

and return type of `getExpirationTimeMillis()` should be changed of course.

I guess something similar is in https://github.com/osmandapp/Osmand/blob/master/OsmAnd-java/src/main/java/net/osmand/map/TileSourceManager.java too.

BTW i think the whole idea of `clearOld();` is wrong. You don't even check for the Internet connection before deleting map tiles. I really believe that expiration time should be checked only for the tiles currently on screen and deleted only if you already downloaded the new ones.

**Comment by tico-tico** [comment]
Another super weirdness. You never actually check if `expirationTimeMillis == -1`. If the `expireminutes` column does not exist (or zero value) then `expirationTimeMillis == -1` but still used in calculation `db.execSQL("DELETE FROM tiles WHERE time<"+(System.currentTimeMillis()-getExpirationTimeMillis()));`. And booom, everything is deleted. Not kewl at all.

**Comment by vshcherb** [comment]
There is a check on 0 
```
if(expireminutes != -1) {
		int minutes = (int) cursor.getInt(expireminutes);
		if(minutes > 0) {
				this.expirationTimeMillis = minutes * 60 * 1000;
```
Feel free to make pull request. So far this feature was designed for Traffic maps which may be a different use case you need

**Comment by tico-tico** [comment]
If there is no `expireminutes` column you create it with value 0. In both cases you don't change the default `expirationTimeMillis` value **-1**. `if(minutes > 0) change_the_value; else keep_it_-1;` I suppose -1 means *never expire* (see the line 46), but you never check for -1. Just change line 465 from `if(timeSupported)` to `if(timeSupported && expirationTimeMillis > 0)` or something similar.

I read about wtf is java only a week ago, and now for me it's enough c-plusplusish to read but not to trying to fix anything myself.

**Comment by vshcherb** [comment]
Double checked the code and it looks correct

**Comment by tico-tico** [comment]
Are you for real can put 15768000000 in int variable?

**Comment by tico-tico** [comment]
ooops, sorry, found the commit

**Comment by tico-tico** [comment]
OK, your desktop tool makes the sqlite map with time column but without expiration time thingie. And osmand deletes all the map because you add it with zero value. It is not my imagination, it's my experience.

**Comment by vshcherb** [comment]
It is definitely not my code (not sure if it makes it my tool or not), and indeed it was super ugly w/o check proper check
