### ISSUE TITLE
Hiking mode OSCM coloring very random not taking into account cycling/horse etc

### ISSUE THREAD

**Issue by mahdi1234** [osmandapp/Osmand#5888]
Osmand 3.1.5 with "Colouring according to OSMC" and Cycling/MTB/Horse routes disabled.

Offline maps with Osmand live, same with live disabled.

It seems Osmand shows randomly OSMC coloring regardless of some types disabeld, also for multiple foot tracks it shows only one.

Here's some examples

#1 - Osmand shows only yellow

![screenshot_20180817-184546](https://user-images.githubusercontent.com/1097047/44279996-b8ba4300-a253-11e8-8590-4560458ac32c.png)

in reality https://www.openstreetmap.org/way/147915519 with osmc:symbol set to

red:white:red_bar
green:white:green_bar
yellow:white:yellow_bar

#2 - Osmand shows blue cyclepath

![screenshot_20180817-184611](https://user-images.githubusercontent.com/1097047/44280065-ef905900-a253-11e8-81d4-dbcb90e92cea.png)

in reality - https://www.openstreetmap.org/way/94446603 with osmc:symbol set to

foot:
red:white:red_bar
green:white:green_bar

bicycle:
blue:yellow:blue_bar (which is displayed on map)
green:yellow:green_bar

#3 - Osmand shows red

![screenshot_20180817-184633](https://user-images.githubusercontent.com/1097047/44280084-fae38480-a253-11e8-9847-e962425646b6.png)

in reality - https://www.openstreetmap.org/way/171722722 with osmc:symbol set to

foot:
blue:white:blue_bar
green:white:green_bar

horse:
red:white:red_dot (which is displayed on map)

I would expect in pedestrian mode with "Colouring according to OSMC" and having Cycling/MTB/Horse routes disabled to see colors applicable to that selection only, it is very confusing now.

**Comment by xmd5a2** [comment]
#1 The order (and colouring) is determined by the algorithm. It is constant on roads with the same set of tags, so there is no random.

**Comment by mahdi1234** [comment]
@xmd5a2 you're right first one is probably different issue. If I log it separately to show something like http://mtbmap.cz/#zoom=18&lat=49.135132&lon=16.236521 i.e. all colors is there any point or you say straight-away it would be declined? I will of course wait for this one getting fixed as this has high impact, multiple colors is more of nice-to-have.

**Comment by vshcherb** [comment]
Yes, it is not random, so we are going to close that issue. We have another issue to highlight fully 1 specific "route" and we have a nice-to-have to display multiple "routes", unfortunately it is quite complicated so it is not planned in the nearest future

**Comment by mahdi1234** [comment]
Thanks for info, multiple routes is indeed nice to have, but cases #2 and #3 in this report is imo high prio as it mixes varios types of routes and causing confusion.

**Comment by mahdi1234** [comment]
@vshcherb Could you please point me to "We have another issue to highlight fully 1 specific "route"" - I'm unable to find it.

I'd just like to make sure it's same as examples 2 and 3 in this report, as this report is mainly about showing horse or bike route when those are disabled and I want to see only hiking.

**Comment by vshcherb** [comment]
I've got comment about @xmd5a2 2, 3 that's they are fixed and will be available in new maps next month.

**Comment by mahdi1234** [comment]
Fantastic, thanks!
