### ISSUE TITLE
Voice instructions truncated when following GPX

### ISSUE THREAD

**Issue by benc153** [osmandapp/Osmand#5890]
Using Osmand+3.1.5 on a Sony Xperia phone. I have the sound bluetoothed to my car (although not sure if that makes any difference or not).

I load a GPX track into Osmand, navigate, and when it says "Use displayed track for navigation?" I say yes.

It follows the track all right but for the last few months the voice instructions are truncated, annoyingly just at the point where you need them. "After 500 metres turn ..." so you don't know if it's left or right. Super-frustrating as I rely on the voice instructions and don't want to look at the screen because I'm trying to drive.

For some reason it seems to be all right when it's figuring out its own navigation because you went off-route rather than following the GPX track. But I haven't tested this extensively.

**Comment by vshcherb** [comment]
What language do you use, could you attach any track?

**Comment by benc153** [comment]
I'm using TTS voice English (United Kingdom).

**Comment by benc153** [comment]
I'm using TTS voice English (United Kingdom). Did you want me to attach a GPX track?

**Comment by vshcherb** [comment]
At least par of it, so we will have less troubles to reproduce it. Anyway we can try first without it.

**Comment by benc153** [comment]
Here's a sample GPX file that results in the issue for me (I get it with all GPX files but this is one I have actually used so know for sure).

Obviously it needs to be gunzipped.

[Bristol.gpx.gz](https://github.com/osmandapp/Osmand/files/2321867/Bristol.gpx.gz)

**Comment by vshcherb** [comment]
Please try in Development Plugin -> Settings to click and pronounce TTS instructions separately. I think it is device specific issue or may be it is not reproducible any more

**Comment by benc153** [comment]
It seems to have been fixed a few months back anyway, by accident i guess.

**Comment by sonora** [comment]
Please open a new issue if it comes up again. I had fixed a number of bugs on the fly over the years, as I detected them in different languages, but I do not off hand remember anything that would fit your issue description.

There was indeed one issue crippling announcements in the middle (at positions where commas were in the prompt), but it should not have affected the TTS voices.

The closest I can think of what happens in your case is that somehow in the middle of the prompt the routing engines believes you are way off the calculated route, in such a cases we mute prompting immediately and start route-recalculation. If that happens to you, it may correlate with bad GPS reception and hence be not universally reproducible. On the other hand, something like that should not have happened frequently or even repeatedly.
