### ISSUE TITLE
Bad code: improve date display

### ISSUE THREAD

**Issue by ldmpub** [osmandapp/Osmand#5891]
See below actual mark screen: date is displayed with format "month + YY".
![activer la marque](https://user-images.githubusercontent.com/1452146/44297355-358b0280-a2d0-11e8-9345-9ffc6fe71b13.jpg)

At least display year in YYYY format (ie 2018 there).
Even better: add day of the month.

**Comment by njohnston** [comment]
The number shown is actually the day of the month, *not* the year:

https://github.com/osmandapp/Osmand/blob/c9d960387a4a4ed9b2984a7db19c58d55db7cece/OsmAnd/src/net/osmand/plus/mapmarkers/adapters/MapMarkersHistoryAdapter.java#L132

**Comment by ldmpub** [comment]
Ok I see: this date is not localized at all, for instance in french day is always displayed before month.

"localized date" are already available in Osmand code, what about reusing on the above script the map date displayed in the maps update list?

**Comment by vshcherb** [comment]
```
Date date = new Date(marker.visitedDate);
			String month = new SimpleDateFormat("MMM", Locale.getDefault()).format(date);
			if (month.length() > 1) {
				month = Character.toUpperCase(month.charAt(0)) + month.substring(1);
			}
			month = month.replaceAll("\\.", "");
			String day = new SimpleDateFormat("d", Locale.getDefault()).format(date);
			String desc = app.getString(R.string.passed, month + " " + day);
```
This code is totally wrong and should be replaced with proper date formatting

**Comment by ldmpub** [comment]
Thanks, waiting to test this in the next build.
