### ISSUE TITLE
Large screen icons update (Gradle)

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#5892]
Technical task. Automatically call from Gradle
1. https://github.com/osmandapp/Osmand/blob/master/OsmAnd/copy_widget_icons.sh
2. Update icons Markers which are on the map (should be bigger as other) 
3. @dmpr0 suggest to align other icons ?

**Comment by sonora** [comment]
Is #5538 related and could be fixed in the process?

**Comment by vshcherb** [comment]
Yes, cross-linked

**Comment by vshcherb** [comment]
+ Check Map Markers icon sizes
