### ISSUE TITLE
Mistake in navigation

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#5893]
Start point: 40.456000, 15.012083
End point: 40.38975,15.060569
OsmAnd navigates by the road that is not allowed by the highway code.
Navigation led by OsmAnd (incorrect):
![screenshot_2018-08-13-09-49-15](https://user-images.githubusercontent.com/40493090/44299907-d694b000-a306-11e8-9a71-66ee4a64819b.png)
How it should be (correct):
![screenshot_2018-08-13-09-54-49](https://user-images.githubusercontent.com/40493090/44299916-edd39d80-a306-11e8-9bb1-3f3aafd4c298.png)

**Comment by naoliv** [comment]
It can be fixed by creating a `no_u_turn` relation from https://www.openstreetmap.org/way/84975147 to https://www.openstreetmap.org/way/30076845

**Comment by StanislavTichy** [comment]
That would be workaround for one place only. OsmAnd should not be allowed to make such very sharp turn in first place.

**Comment by naoliv** [comment]
It could penalize sharp turns, but not avoid them completely (which would also be a wrong result).
