### ISSUE TITLE
Island naming

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#5894]
When viewing some of the islands, the first name you see as you zoom in is the names of the largest towns. It would be much better if the first thing you see when zooming in is the name of the island like the standard osm online map. The examples of the islands that show only the largest cities when zooming in are Bornholm and Gotland.

**Comment by erik55** [comment]
Same for the Canary Islands and the Azores.

**Comment by xmd5a2** [comment]
https://github.com/osmandapp/OsmAnd-resources/commit/9668e9104840e86467b57573e64ad3da0030468c

**Comment by vshcherb** [comment]
@xmd5a2  please confirm it is fixed or not and what are the observations

**Comment by alexbodn** [comment]
i see the changes in my default.render.xml, but unfortunately I can't see the island names on the map yet.
