### ISSUE TITLE
Barrier=hedge areas are not represented

### ISSUE THREAD

**Issue by Robot8A** [osmandapp/Osmand#5897]
Mapnik rendering:
![imagen](https://user-images.githubusercontent.com/19521377/44307853-5b84d580-a3aa-11e8-83ce-a1edc10ee52f.png)

OsmAnd rendering:
![imagen](https://user-images.githubusercontent.com/19521377/44307858-6a6b8800-a3aa-11e8-9624-181b4ae59145.png)

https://www.openstreetmap.org/#map=19/41.61608/-0.91972

**Comment by hakuchi** [comment]
If I look on the Bing image, I can see only the shadow from the hedge. 
For me this not looks like a large hedge.

**Comment by Robot8A** [comment]
They are large hedges, I can confirm, I live only a couple kilometres away from it.
