### ISSUE TITLE
Osmand does often not generate a turn-by-turn navigation hint when aproaching a Y-like split

### ISSUE THREAD

**Issue by doctor-beat** [osmandapp/Osmand#5901]
android 7.1.2, Samsung S4 mini, latest osmand, osmand offline nav, bike profile

I found many, many cases when osmand would not generate a navigation hint when aproaching a Y-like split. One thinks, when not looking to the screen, that the correct way is to continu over the obvious road but that is wrong.

Examples:
![screenshot_20180819-200306](https://user-images.githubusercontent.com/11628099/44323755-955de680-a453-11e8-9a1d-4628d14f3dc7.png)
![screenshot_20180819-132214](https://user-images.githubusercontent.com/11628099/44323759-998a0400-a453-11e8-96a4-a66e1115c9f1.png)
![screenshot_20180819-124732](https://user-images.githubusercontent.com/11628099/44323762-9ee74e80-a453-11e8-9f5e-33eed23b330a.png)
![screenshot_20180819-120849](https://user-images.githubusercontent.com/11628099/44323767-a575c600-a453-11e8-985b-cbc5d5023d9e.png)
![screenshot_20180819-120455](https://user-images.githubusercontent.com/11628099/44323769-a9094d00-a453-11e8-93ae-6b2a0af1cf36.png)
![screenshot_20180819-120445](https://user-images.githubusercontent.com/11628099/44323771-adce0100-a453-11e8-9e57-cad9a8a990e2.png)

Then again in this example there is a nav hint every 50m while there is no junction or crossing in sight:
![screenshot_20180819-121131](https://user-images.githubusercontent.com/11628099/44323820-d229dd80-a453-11e8-9a6e-0e8821aa48bd.png)

**Comment by utack** [comment]
https://www.openstreetmap.org/way/60772642  
This one even has turn:lanes mapped, but Osmand did not generate a hint and just said continue to "Lagerhausstraße"

**Comment by Rpnpif** [comment]
I saw same issue when Osmand Live was enabled. Is your choice ?
This is perhaps the same issue as #5803.

**Comment by utack** [comment]
I did not have live enabled

**Comment by doctor-beat** [comment]
Me neither. And besided, I don't see how this issue can be related to highways being re-routed.

**Comment by vshcherb** [comment]
It is not said here but I think it is GPX navigation used so it is impossible to get that information from GPX cause it doesn't have adjacent roads.
We have another request to enable "merge" with real road data.

**Comment by doctor-beat** [comment]
Why is this issue closed? It is not solved nor does it have to do with 'adjacent roads' or with 'real road data'.

**Comment by scaidermern** [comment]
It looks like you choose to navigate along a GPX track. Currently in this mode OsmAnd does not match the track to real road data, see #3908.
