### ISSUE TITLE
Navigation issue

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#5909]
When calculating the route from Valfrejus to Chambery and setting Avoid toll roads, OsmAnd calculates the route normally. 
![image](https://user-images.githubusercontent.com/40493090/44344501-869a2280-a499-11e8-8601-29c0bd12e3e5.png)

But when the route is reversed, OsmAnd calculates a significantly longer route. 

![image](https://user-images.githubusercontent.com/40493090/44344507-8e59c700-a499-11e8-8fee-07e0c37e9d35.png)

**Comment by Evgenij27** [comment]
Fixed with https://github.com/osmandapp/OsmAnd-tools/commit/f5cb92392d014a8eafa300c992f7a2583cb21613
