### ISSUE TITLE
Moving of GPX point needs double tap

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#5913]
Moving an existing GPX point (change marker position) needs a double tap on the apply button (similar to shooting a zombie, always double tap). The first button press doesn't do anything.

This problem does not occur when moving favorites.

**Comment by AlexSyt** [comment]
@scaidermern
Hi, I cannot reproduce this issue. Can you provide some more info please?

**Comment by scaidermern** [comment]
@AlexSyt 

1. Select position on map
2. Actions -> Add GPX waypoint
3. Select the newly created waypoint (or keep it selected)
4. Actions -> Change marker position
5. Move marker
6. Tap apply, nothing happens
7. Tap apply again, the widget closes and the new position gets saved

**Comment by AlexSyt** [comment]
@scaidermern , I can reproduce it with currently recording track, but not with regular tracks. Do you have the same behavior?

**Comment by scaidermern** [comment]
@AlexSyt Yes. Never tried to reproduce it with regular or previously recorded tracks but it only occurs with the currently recorded one.

Thanks! :)

**Comment by AlexSyt** [comment]
You are welcome)
