### ISSUE TITLE
Problems searching for destination

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#5918]
It is difficult to understand what algorithm OsmAnd uses for its search function.

Feedback from a user:

1. Finding an address 
- locate yourself in Newbury UK 
- select the magnifying glass 
- select Address: type in "Newbury " (trailing space is important) and pick it: list of roads appears 
- type in "gore end": results in zero hits within 6.21 mi 
- select "increase search radius" and there are some results within 6.21 mi 
? So OSMAND knows of "gore end ..." near Newbury but doesn't show it?
![screenshot_20180809-115736_osmand](https://user-images.githubusercontent.com/40493090/44469331-f3dfbc00-a62f-11e8-83f3-359e666e3b11.jpg)
![screenshot_20180809-115744_osmand](https://user-images.githubusercontent.com/40493090/44469347-f8a47000-a62f-11e8-9cb6-8f14e1ea1be5.jpg)
![screenshot_20180809-115749_osmand](https://user-images.githubusercontent.com/40493090/44469353-fb06ca00-a62f-11e8-98ee-e44713d3fec1.jpg)

2. Finding a category 
- locate yourself in the UK 
- select magnifying glass 
- select "Categories" and pick "Public Transportation" 
- enter "airport" and search 
- increase the radius as much as you like: you never see an airport (but lots of bus stops and ...) 
- alternatively, select mag.glass and simply type in "Oxford airport" - without having to increase radius there it is, 2nd entry?

 What is the point of categories if they don't narrow the search domain?
![screenshot_20180809-121129_osmand](https://user-images.githubusercontent.com/40493090/44469454-32757680-a630-11e8-8aa8-42d8fe23200a.jpg)
![screenshot_20180809-120650_osmand](https://user-images.githubusercontent.com/40493090/44469464-35706700-a630-11e8-9029-7feead5e3d99.jpg)

**Comment by PaulStets** [comment]
@alyonapinchuk Please explain the following to the user.

1. The Gore End Road is not in the Newbury, therefore it is not shown in the street search. As you can see from the third screenshot, the street is in the East Woodhay. Please explain to the user that it is better to use the regular search if you are not sure to which city the street belongs. 

2. Airports are not included in the Public transportation. If a user needs to search specifically for the airports, he/she can do so by creating a custom POI filter in the Search - Categories - Custom Search - Transportation - Airport.
