### ISSUE TITLE
Android crashes when opening Osmand on LineageOS 15.1

### ISSUE THREAD

**Issue by chilliger** [osmandapp/Osmand#5923]
When I open Osmand on my device the app shows the change log screen and after this the system is completely unresponsive, meaning no touch input is recognized. The system hangs. After some seconds the screen gets black with a white device LED. The only way to exit this state is to long press the power button so the device shuts down to reboot. I managed to log the device on my Linux system through adb (attached txt file). The logcat stops immediately after the phone hangs. Is there is any additional log file that I can provide? Nightly version 3.0.0#20626d from the official website is working fine on the same device and I am kind of afraid to update it resulting in the same issue as the stable version. 
Device:  Oneplus 3T
OS: LineageOS 15.1 for microG
Osmand: 3.1.6 from F-Droid
[logcat_only_osm.txt](https://github.com/osmandapp/Osmand/files/2311975/logcat_only_osm.txt)

**Comment by chilliger** [comment]
The thing is that this happens upon the first start of the app. The app should request the permission it self when first started, right? To be safe to have a fresh state I tried to delete the app data. The funny thing is android also crashes when I try to do this. I would like to provide another log file if this issue gets reopened. Do you think that this could be a lineage problem?

**Comment by vshcherb** [comment]
Hm... I was confused it is not related to GPS because that excepction was caught.  I think it might be related to https://github.com/osmandapp/Osmand/issues/5857, so the app crashes on the start when it has some problems with fonts.  We know about that issue and try to recompile with different NDK. 
Please give a try to http://download.osmand.net/latest-night-build/test/OsmAnd-nightly-skia_oreo-full.apk

**Comment by chilliger** [comment]
Tried the provided apk. Same result. I had to uninstall the installed F-Droid version to be able to install the provided one. Even the uninstallion did cause a system crash. Do you any logcats of the named processes that also crash the system (uninstallation, clearing data)?

**Comment by vshcherb** [comment]
the logcats don't contains the crash itself unfortunately, all stacktraces are related to warnings

**Comment by chilliger** [comment]
Can you please reopen the issue? In #5857 the app crashes when already opened. I don't even get that far and the complete android system crashes not only the app.

**Comment by chilliger** [comment]
I did not filter the output. I just provided the log starting from opening osm. I did one more test granting the location permission in the system settings before opening osm (and also disabled lineage's privacy guard on the app). Did also crash android. This is the untouched logcat for the granted permission test: 
[2logcat_osm.txt](https://github.com/osmandapp/Osmand/files/2321849/2logcat_osm.txt)

**Comment by vshcherb** [comment]
Yes but the last message 
> 08-26 21:32:29.069 17442 17468 D net.osmand: CachedOsmandIndexes Initializing db /storage/emulated/0/Android/data/net.osmand.plus/files/Germany_baden-wuerttemberg_europe.obf 2469ms
> 08-26 21:32:29.072 17442 17468 D net.osmand: ResourceManager All map files initialized 2499 ms
which is good and then nothing :-(
Let's see if get more info in future for that issue or we fix it with #5887 together
