### ISSUE TITLE
Routing error with roundabout

### ISSUE THREAD

**Issue by ronnystandtke** [osmandapp/Osmand#5931]
I use OsmAnd v3.1.6 with offline maps, in-app offline routing and the car profile on several Samsung devices with LineageOS 14 and 15.

I run reproducibly into a case of wrong routing at this roundabout:
https://osm.org/go/0Ccj_xVgV?m=

I checked the map data and everything looks fine. GraphHopper on the OSM website also calculates a reasonable route:
![2018-08-23 graphhopper](https://user-images.githubusercontent.com/1651625/44536394-a41af680-a6fc-11e8-9924-c42214ae8a2d.png)

But for whatever reason OsmAnd calculates this strange route:
![2018-08-23 osmand](https://user-images.githubusercontent.com/1651625/44536437-c57be280-a6fc-11e8-8fbb-04e8c22a6bba.png)

There is only a roundabout and some highway crossings on the expected route. Is this something that can influence OsmAnd's offline routing this much?

**Comment by vshcherb** [comment]
Fixed with https://github.com/osmandapp/OsmAnd-resources/pull/529/files
