### ISSUE TITLE
UI Painpoints: Inability to copy addresses creates huge user friction and makes app useless

### ISSUE THREAD

**Issue by t4777sd** [osmandapp/OsmAnd#5932]
One thing that has always kept me on Google maps and never using Osmand as my default map is that Osmand has anti-features restricting the ability to copy addresses. For example of a common use-case:

1. A location is received via whatsapp / telegram, etc. It opens in OSM

2. The addresses displays and map goes to the specific location

3. PROBLEM: OSM provides no ability to copy the address. Sometimes the address needs to be edited. Sometimes it needs to be pasted into other applications such as conversations or uber, etc.

Other mapping platforms do not have anti-features like this. They will let the user copy the address. Usually this is done by long-pressing the address

Strangely, OSM will let a user copy the latitude and longitude. However, the address it restricts the users ability to copy.

Even clicking "directions" and changing the view to the direction screen will restrict the users ability to copy. It will display the address in the "To" or "From" field but it will restrict any user attempt to copy that address. A complete anti-feature.

OSM is the only mapping application that does this and it probably prevents a lot of people from utilizing it as their primary app. It basically becomes a useless applciation for a lot of use cases.

Want to use OSM to find a restaurant and take an Uber to it? IMPOSSIBLE. Better use google maps or any other competing alternative because there is no way to go from OSM to Uber due to the anti-copying anti-features in OSM.

**Comment by contrapunctus-1** [comment]
Hi
Have you tried the Share button?

Tap on a POI or long press at any location -
![](https://i.imgur.com/ACgPZl7.png)
Press the Share button -
![](https://i.imgur.com/oDIqGx9.png)
'Send' or 'Copy' seem to do what you ask.

Admittedly, the resulting address isn't very accurate nor makes good use of the OSM data, but that's another issue.
