### ISSUE TITLE
HTTPS for Map Source OsmAnd

### ISSUE THREAD

**Issue by mritzmann** [osmandapp/Osmand#5936]
I noticed that tiles from `OsmAnd (online tiles)` are loaded over insecure HTTP.

* Version: OsmAnd~ 3.1.6

https://github.com/osmandapp/Osmand/blob/9a574e2064a5d629a411b4c6d0aa7e77e7bf2d5b/OsmAnd-java/src/main/java/net/osmand/map/TileSourceManager.java#L39

---

Feature Request:

- [x] Provide HTTPS on `tile.osmand.net` _(With [Letsencrypt](https://letsencrypt.org/) for example)_
- [ ] Change the [stored URL](https://github.com/osmandapp/Osmand/blob/9a574e2064a5d629a411b4c6d0aa7e77e7bf2d5b/OsmAnd-java/src/main/java/net/osmand/map/TileSourceManager.java#L39) to https

---

I see the following benefits:

* Better for data protection reasons
* Maybe faster due HTTP/2 _(can only be used with https)_
* There's probably no reason for http...

**Comment by MarcelWaldvogel** [comment]
*Nice to have*? It would be better to label this *catching up with what everyone else has for years now*.

**Comment by mritzmann** [comment]
I noticed two weeks ago that `tile.osmand.net` now has HTTPS. Configured it manually in the app and didn't notice any problems in the last two weeks. Work well!

[SSL Labs gives an A rating](https://www.ssllabs.com/ssltest/analyze.html?d=tile.osmand.net&latest). I think that's good so far.
