### ISSUE TITLE
multiple uploaded tracks have same description

### ISSUE THREAD

**Issue by 532910** [osmandapp/OsmAnd#5938]
![screenshot](https://user-images.githubusercontent.com/14617699/44613389-6791ec80-a81b-11e8-82a4-fb5082ac0b86.png)

My Places -> tracks -> press upload -> select multiple tracks (the Rec folder with autorecorded tracks)
All uploaded tracks will have the same description (as the first track name)

**Comment by vshcherb** [comment]
Currently it is a common description for all tracks, it's actually supposed to be human-readable description like "Trip by car" or "Trips to City", it doesn't make much sense to generate same description as track name to be honest.
