### ISSUE TITLE
'Flooded' areas in Ecuador map

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#5944]
https://www.openstreetmap.org/relation/2403848 
In normal zoom level, the city of Guayaquil is quite okay; when zooming in the whole town is "flooded".
![screenshot_2018-08-25-19-01-40](https://user-images.githubusercontent.com/40493090/44670807-608df880-aa2c-11e8-9b2f-6b6c89d9190f.png)
![screenshot_2018-08-25-19-00-16](https://user-images.githubusercontent.com/40493090/44670828-6c79ba80-aa2c-11e8-98ea-25efef62ed9b.png)
![screenshot_2018-08-25-19-00-27](https://user-images.githubusercontent.com/40493090/44670851-7bf90380-aa2c-11e8-8ab0-45fb2654db37.png)

In opposite (low zoom level) the Riu Babahoyo disappears suddenly in the 
middle of the town.
![screenshot_2018-08-25-19-01-24](https://user-images.githubusercontent.com/40493090/44670841-70a5d800-aa2c-11e8-8f67-971e13933e64.png)

Some national parks are somewhat "square". (although the same is in OSM: https://www.openstreetmap.org/relation/225653) 
![screenshot_2018-08-25-19-01-59](https://user-images.githubusercontent.com/40493090/44670855-7f8c8a80-aa2c-11e8-8bb6-4e29642a871a.png)

**Comment by xmd5a2** [comment]
Fixed in new basemap (starting from tomorrow)
