### ISSUE TITLE
Straumen: Water rendering broken

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#5945]
At zoom 15 the rendering of water is broken:

![screenshot_20180828-112038](https://user-images.githubusercontent.com/1040784/44714020-98d91980-aab4-11e8-8532-d821c98a10ab.png)

Location: 63.868736,11.296025

**Comment by scaidermern** [comment]
Same problem here at zoom levels 14, 13 and lower(?):

![screenshot_20180831-130815](https://user-images.githubusercontent.com/1040784/44909415-81519900-ad1f-11e8-9eee-fd43f407eeab.png)

At zoom levels 15 and 16 the problem from #5833 occurs, maybe both issues are related.

**Comment by thompehw** [comment]
Another report of water "flooding" into land was in the users' forum [here](https://groups.google.com/forum/#!topic/osmand/mOodl0zAOWM). The OP thinks the problem is solved, but I don't. (Current Google release, all maps up to date; I am "A Thompson" in that forum.)

**Comment by xmd5a2** [comment]
Can't reproduce original issue and issue near Brevik. The reason may be in a broken coastline in the area.

**Comment by scaidermern** [comment]
@xmd5a2 Can't reproduce it either with new maps.

However, if this has been caused by a broken coastline then there must be a way to circumvent such errors. For example you could check for a broken coastline _before_ generating new maps. If the coastline is broken then either:

- Wait a little. Broken coastlines usually get fixed rather fast. Or
- Fall back to the previous coastline. Ccoastlines don't change that often and changes are usually small. Or - Use the coastline from services such as http://openstreetmapdata.com/data/coastlines. This source will never serves broken coastlines and will only update them if they are closed.

This will prevent having to deal with this issues in the future. Neither OsmAnd users want to have to look at water rendering issues similar to above nor do OsmAnd developers have to investigate these issues only to find out that it wasn't caused by OsmAnd itself but by a broken coastline instead :)

**Comment by vshcherb** [comment]
@scaidermern it is something to definitely consider though before start building tools around it I would prefer if we fix other coasltine issues which we have reported so we avoid false-positives cases for broken data in OSM

**Comment by scaidermern** [comment]
@vshcherb Not sure if I understood you correctly. You will have a hard time detecting false-positives if broken coastlines don't get handled correctly.

Do you intent to create a new ticket (or reopen this one) as a reminder for correct handling of broken coastlines?

**Comment by scaidermern** [comment]
Yes, that's true. That's why I listed several approaches for handling broken coastlines correctly. There might be some others, though.
