### ISSUE TITLE
Repeated jumps to shared location on resume

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#5948]
When opening OsmAnd via a shared location it jumps back to this location on each resume, i.e. when switching between apps and back to OsmAnd or when turning the display off and one again.

This jumping to the shared location can only be stopped by closing OsmAnd and opening it again (manually).

**Comment by vshcherb** [comment]
This should be checked cause it should happen only if OsmAnd was inactive for some period (period needs to be checked but I guess it is 30 min)

**Comment by dmpr0** [comment]
I can reproduce it, it is happens even after 3-5 minutes.
