### ISSUE TITLE
[Feature request] Map source setting for each profile (global, driving, cycling, walking)

### ISSUE THREAD

**Issue by gunnar22** [osmandapp/OsmAnd#5950]
I suggest letting the Map source selection be remembered for each profile (global, driving, cycling, walking). 
(As you all know, for the similar purpose Map style, the profile specific setting has been in place a long time.) Map source and Map style are similiar in the sense that they have to do with the overall appearance of the map.
Example: 
Let's say that I have set the Mapnik Map style for "walking" and LightRS Map style for "driving". One day I decide that I want a rastermap (Map source) for "walking" instead of Mapnik, and still keep the LightRS for "driving".
What happens is that it now shows the rastermap in both profiles. However, if OsmAnd could remember Map source for each profile, the switch between rastermap for walking and LightRS for driving would be as convenient as just switching profiles.

**Comment by bege10** [comment]
This concerns all "Show" settings but the last two ("Contour Lines" and "Hillshade layer"). As these two are already per profile I hope the settings above can be per profile, too.
Thank you very much.

**Comment by dmpr0** [comment]
Implemented.
