### ISSUE TITLE
Question (documentation): Custom rendering

### ISSUE THREAD

**Issue by majkaz** [osmandapp/Osmand#5956]
Not sure if this is the right place to ask:

The documentation for [custom rendering](http://osmand.net/help/docs/Custom_Rendering_How-To.htm) is linking to [rendering_types.xml](https://github.com/osmandapp/OsmAnd-jni/blob/master/java/net/osmand/osm/rendering_types.xml) but the document seems to be missing.

Where can I find it? Or better yet, is somewhere more recent documentation?

**Comment by vshcherb** [comment]
The document is back

**Comment by majkaz** [comment]
@vshcherb 
Where is the document? The linked [rendering_types.xml](https://github.com/osmandapp/OsmAnd-jni/blob/master/java/net/osmand/osm/rendering_types.xml) is getting 404 response, the whole repository "OsmAnd-jni" seems to be missing.

**Comment by majkaz** [comment]
@sonora 
I am still seeing the wrong link. What I mean is in the part "Add new Features to the Map".
![link](https://user-images.githubusercontent.com/23097386/45310862-bd5ada00-b527-11e8-9eb1-438bbbfdcf4c.png)
