### ISSUE TITLE
JS voice (de) misses many street names, refs and destinations

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#5957]
nb 3.2.0#25764m
Announce/street name TTS = on

Going through the "Test voice prompts (de-tts)" it sometimes misses the announcements of street names, refs and destinations. 

E.g. 3.4 "after 3100 m turn right into SR80 toward Rome", I hear:
"Demnächst nach ca 3km rechts abbiegen."
Some are ok however:

3.2 miss
3.4 miss
3.5 ok
3.6 miss
4.2 miss
4.3 miss
4.4 miss street, ok destination name
5.2 miss
5.3 miss
6.3 miss
7.3, 7.4 intermediate+final destination ok
7.6,7.7 favorite/POI ok
8.x ok

Looking in the de_tts.js now, I see some old prolog statements commented off. Does that mean there are some implementations to be done?

**Comment by hakuchi** [comment]
this is not only with German TTS!
I think that all non English TTS have this problem.

**Comment by polarbearing** [comment]
test prompt 3.5 confuses me. It is assembled in (de) line 402 and "Main Street" is spoken as ```toRef``` while "Route 23" spoken as ```toStreetName```

**Comment by polarbearing** [comment]
in (en) the ```function turn_street(streetName)``` has 5 clauses, in (de) only 3. 
That's not just a typo, so better to be fixed by @PaulStets

**Comment by PaulStets** [comment]
@polarbearing Could you please provide the test prompts as you hear them in German and a correct variant? Also, please check that the Street name announcements are enabled in the Navigation settings - Announce...
For me, the 3.4 is: "Demnächst nach ca 3km rechts abbiegen auf die SR 80 richtung Rom." 

As for the 3.5, this is caused by the incorrect order of names in the testing method, it should be correct during the navigation.

**Comment by polarbearing** [comment]
In nb 3.2.0#25764m, I hear:
3.4 de-tts: ```Demnächst nach cirka drei kilometern rechts abbiegen.```
(not mentioning SR 80 or Rome)
In en-tts that is included. 
I double checked that Announce... Street name (TTS) is on, for car navigation which is currently selected.
I also checked that 3.5 runs through  line 402 in the de-tts file by inserting a voice marker, while the other 3.x command do not run though this line.

Idea: could we have a debug setting that writes the assembled TTS command on the screen? That would help a lot when people try to separate OsmAnd issues from TTS-Engine problems.

**Comment by PaulStets** [comment]
@polarbearing I have fixed the German tts file and tweaked the testing activity. Please download a new nightly (in an hour or so) and re-download the voice asset. Though it is not ideal still (some articles are missing), all the street names are announced properly. Let me know if it's ok now.

**Comment by hakuchi** [comment]
what about other language TTS?
France, Spanish, Italian, Russian, etc.

**Comment by polarbearing** [comment]
@hakuchi - it's probably good to test one language first, but if you look into the commit you see that Paul refines other languages as well. 

@PaulStets 
Tested # 25778 and all voice prompts are semantically complete now. As you said, there are minor grammar mismatches with articles, but I have to think if they depend on the situation. The only missing article was in 5.1 ... in _den_ Kreisverkehr. 

6.4 ```When possible, make a U-turn``` lacks the when possible (de: Wenn möglich, ) .

thanks
