### ISSUE TITLE
Nightly update not working - Android 6

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/Osmand#5959]
If I will make a **update** by selecting a build in the app, the installation give me a "installation not successful" or similar message.
Same if I manually download the Nightly from the Homepage.

If I make a **deinstallation**, the **installation** work, but not if I make only a update.

Testet with a lot of different builds(installed) and over days with the latest builds(for update).

I have a Moto G2(XT1068) with Android 6

**Comment by vshcherb** [comment]
Looks there was a temporarily glitch or we misused android versioncode in between the builds. We couldn't reproduce the issue with latest builds

**Comment by hakuchi** [comment]
Do you have tested this on a Android 6 device?
Not working for me with build from 9.9.18 21:05

![pic versions](http://fs5.directupload.net/images/180910/q2lgrvi4.png)
![fail](http://fs5.directupload.net/images/180910/d3ji6nen.png)

so I deinstalled old nightly version and tested to make a update with build from 8.9.18 18:08(3.2.0#22260d) to build from 9.9.18 21:05(3.2.0#22272d)
Same **non working** result.

Deinstalling nightly and installing 3.2.0#22272d works without problems.

For me this is not solved!
I can easy reproduce this issue on My Android 6 phone!

**Comment by hakuchi** [comment]
Also not working with latest versions

**Comment by hakuchi** [comment]
thx for reopening.

Tested today with complete uninstalling and new installing(same way as above).
And then I tested to update when new version comes.

Now it works. Also updating again and again with new version.
Now I con no longer reproduce this bug.

If this bug come back, I will send a message in this thread.
