### ISSUE TITLE
Zoom level after search not preserved

### ISSUE THREAD

**Issue by mahdi1234** [osmandapp/Osmand#5961]
Osmand 3.1.5 on Android.

Offline maps with Osmand live, same with live disabled.

- Search on anything POI, town whatever

![screenshot_20180831-220336](https://user-images.githubusercontent.com/1097047/44933698-5476a380-ad6a-11e8-80fb-acce545f71ca.png)

- Change zoom level with plus/minus buttons

![screenshot_20180831-220345](https://user-images.githubusercontent.com/1097047/44933714-62c4bf80-ad6a-11e8-9e11-a2257038dbd8.png)

- Swipe down info about the item to see whole map

Observed:
Zoom level back to original one right after search

Expected:
Keep altered zoom level when dismissing item info

![screenshot_20180831-220404](https://user-images.githubusercontent.com/1097047/44933727-6eb08180-ad6a-11e8-9c6a-02dc58cd2a47.png)

Scenario #2

- have POI labels enabled
- choose any POI
- zoom using buttons
- dismiss POI detail

Same behavior as above, zoom level back to one before POI detail invoked.

**Comment by pebogufi** [comment]
+1 !
For me this is as well very annoing quite often.
Peter
