### ISSUE TITLE
Wikipedia missing some numbers in Czech articles

### ISSUE THREAD

**Issue by mahdi1234** [osmandapp/Osmand#5965]
Osmand 3.1.5 on Android.

Offline maps with Osmand live + latest offline Wikipedia articles.

It seems when number is followed by link reference it's not correctly parsed and is missing from offline Wikipedia articles.

Example 1

https://cs.wikipedia.org/wiki/Nyklovice

> Žije zde 166[1] obyvatel.

in the same article thing in brackets is also missing

> Nyklovice (německy Niklowitz) jsou

![screenshot_20180901-134531](https://user-images.githubusercontent.com/1097047/44945641-04d9bb80-adee-11e8-97af-1373da4a1e07.png)

Example 2

https://cs.wikipedia.org/wiki/Bystr%C3%A9_%28okres_Svitavy%29

>  Žije zde přibližně 1 600[1] obyvatel.

![screenshot_20180901-134618](https://user-images.githubusercontent.com/1097047/44945643-0c00c980-adee-11e8-9503-f826fb45358b.png)

**Comment by vshcherb** [comment]
It is a duplicate issue and it will be addressed in the new wikipedia maps
