### ISSUE TITLE
Add development setting 'Display TTS utterance'

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#5966]
When debugging/improving TTS issues it is often not clear if some statements comes from OsmAnd or is modifies/interpreted by the respective TTS  engine installed on the device. 

I propose a setting in the ```OsmAnd development``` section called ```Display TTS utterance```, which causes the statement to be displayed on screen as it is handed to the TTS engine.

**Comment by scaidermern** [comment]
This could even become a regular feature for users who prefer text instead of audio instructions.

**Comment by sonora** [comment]
Would you please test, using the nightly, if that's along the lines of what is requested here.

I have not make a special UI for it, you can simply toggle it on and off using test button (11.3) under `Development plugin settings / Test voice prompts`.
