### ISSUE TITLE
Translation of certain phrases

### ISSUE THREAD

**Issue by debyos** [osmandapp/Osmand#5974]
Dear Developers,

I have been a keen translator of [OsmAnd into Hungarian](https://hosted.weblate.org/projects/osmand/phrases/hu/) but now I am a bit stuck with two words. Please, describe what they mean.

- **quize** (it should be some kind of hike checkpoint)
- **course** (what kind of course is meant here)

Thanks in advance

Gábor

**Comment by scaidermern** [comment]
`quize` could be a mispronunciation of `quiz`. So far there are only 10 occurences of `checkpoint:type=quize` (see https://taginfo.openstreetmap.org/tags/checkpoint%3Atype=quize) and the OSM wiki has no documentation of this tag.

**Comment by debyos** [comment]
Dear Scaidermern,
this seems a plausible answer, however, [for quiz](https://taginfo.openstreetmap.org/tags/checkpoint%3Atype=quiz) there are absolutely no tags, not even 10…
Isn't here someone who created these tags in OsmAnd? Perhaps, they could answer.
Kind regards
Gábor

**Comment by scaidermern** [comment]
> however, for quiz there are absolutely no tags, not even 10…

All `checkpoint:type=quize` nodes have been created by the same user in a single changeset: https://www.openstreetmap.org/changeset/13360653. So it looks like he/she invented this tag without documenting it.

> Isn't here someone who created these tags in OsmAnd? Perhaps, they could answer.

It has been introduced with this commit: https://github.com/osmandapp/Osmand/commit/0cc402d89afbb4c0bb8a45602445064460bf01ea. I guess in a somehow automated way without manual checking of each individual tag.

**Comment by debyos** [comment]
Dear Scaidermern,

thank you for your detective work. I have written to [the creator](https://www.openstreetmap.org/user/hayashi) of the changeset containing the only "quizes" in the whole OSM (dating back to 2012). Luckily, he is active even nowadays so let's hope he will explain what they actually are, perhaps even change them to quiz (if that is the right solution).

On the other hand, thinking more generally, I wonder (i) whether we really need an infinite (i.e. ever growing) number of tags and (ii) whether these tags should be included into OsmAnd without any human verification… I think the answer in both cases is no but this is only my opinion and has nothing to do with the original issue.

Anyway, thanks a lot. I will report on the results.
Kind regards

Gábor

**Comment by xmd5a2** [comment]
"Couse" is used with checkpoints. Still not sure what it means but it is used 773 times. https://taginfo.openstreetmap.org/keys/course#overview
