### ISSUE TITLE
Charging stations show up as "Osmand electricity combined charging"

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#5975]
Charging stations in OsmAnd show up under the name "Osmand electricity combined charging". Also various charging station attributes have similar weird names like "Osmand_socket_type2_yes", "Socket_type2", "Car_yes", "Bicycle_no" etc.

![photo_2018-09-03_13-17-28](https://user-images.githubusercontent.com/1040784/44984136-fcaf8680-af7b-11e8-9402-4e332068ae08.jpg)

Looks like there are several translations missing, even into English?

Additionally the charging station category seems to be broken. When searching for "charging station" OsmAnd lists "Charging station" as category. However after selecting to show this category on the map, charging stations are _not_ highlighted.

**Comment by gunnar22** [comment]
Thanks. This gave me a good laugh!

**Comment by ADepic** [comment]
@gunnar22 same :laughing: :laughing:

**Comment by xmd5a2** [comment]
Can't reproduce. May be you have an outdated map?
![screenshot_2018-09-10-15-45-00](https://user-images.githubusercontent.com/5829014/45298444-2a16aa00-b511-11e8-9345-bb27ed512d81.png)

**Comment by scaidermern** [comment]
No, no outdated map. However I've deleted `poi_types.xml` from the files directory and now the problem is gone. This is weird and should be fixed in OsmAnd.

**Comment by vshcherb** [comment]
@Chumva  we need to check code which updates poi_types.xml (usually after upgrade or new version), somehow it didn't work

**Comment by scaidermern** [comment]
When does this file get created and what is it used for? After deleting it it didn't reappear again so far.

**Comment by Chumva** [comment]
This file is used for 3rd party poi types like routing.xml for routing customization. There was a discussion about it `s processing in #3381.
