### ISSUE TITLE
JS Voice Regressions (de and others) 

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#5976]
I am the principal author of our old  PROLOG based TTS voices, unfortunately had little time so far to participate in the JS migration. As a follow-up to #5957, I have ran a quick comparison test and it seems there are still quite some regressions of JS versions vs. the long-tested old ones. Let me collect here the findings so we can tackle one by one:

**Grammar:**

- (G1) de_tts.js: The Prolog logic of needing masculine/feminine/no article depending on the Ref/Name/Dest combination seems to have been ported with a bug.

**Wording:** (Not a good time to change long stable wording at the time of the js porting ...)

- (W1) de_tts.js: Now uses "einordnen" instead of "halten" for "keep". Need to check with the community if we like the new wording, and test if it fits all real.life situations.

**Rounding:**

- (R1) Distance, all languages, I guess: The sanity-checked rounding scheme we had in Prolog seems to be ported with a glitch. It rounded to e.g. the nearest 50m for 100m>x>100m, reflecting that the accuracy of GPS, the time how long a prompt sounds, and the speed of travel all create uncertainty. It seems different now, we announce e.g. "370" instead of "350", i.e. we bother drivers with a 5% difference which is invalid anyway vs. the uncertainty. (Hope we do not announce "377" :) )
- (R2) Time rounding, return result: "Dot nought" issue, see #5985

Note to testers: My old **Voice system info:** button 11.1 on the Test Voice Prompts menu does not display if the JS or Prolog file is being tested. When comparing both, it is advisable to move the old `_ttsconfig.p` Prolog file to a separate voice folder like e.g. en_old-tts.

Let's extend the list if anybody has more findings in any tts language. Would be a pity if we released with many regressions in our long-tested voice prompts.

**Comment by pebogufi** [comment]
> Rounding:  ... (Glad we do not announce "377" :) )

Currently exact numbers like this ARE spoken, version from 1st sept.
(can't test newer versions due to  https://github.com/osmandapp/Osmand/issues/5969)
Peter

**Comment by vshcherb** [comment]
@PaulStets Math.round as used in function time(seconds) should return an integer as per JS documentation, but it seems we somehow cast into a decimal number before passing to the voice engine?

**Comment by PaulStets** [comment]
@vshcherb @sonora I have fixed the "dot ogg" issue and improved the time prompt for the other languages. Will continue fixing the other issues.

**Comment by PaulStets** [comment]
@sonora R1 fixed with https://github.com/osmandapp/OsmAnd-resources/commit/d7afd8138f8d259f570ae57c6987fd50d3b7e4af Please check, it should be ok in all the languages.

**Comment by PaulStets** [comment]
@sonora Also fixed the G1: https://github.com/osmandapp/OsmAnd-resources/commit/d797f7a214e4c3bac447c75440c36fbcb43471c9

As for the W1, it was suggested by one of our contributors. If it sounds odd, feel free to change it back.

**Comment by pebogufi** [comment]
@PaulStets @sonora. R1 looks good now, good rounding. Tested with version today 15:29 german, simulation mode, pressing turn hint quite often.
Peter

**Comment by sonora** [comment]
Paul good work, this is looking good now, I think!
Best - Hardy
