### ISSUE TITLE
Late announcements 

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#5979]
During navigation using a GPX track, the announcements about destinations and leaving the track are too late. 
Destination announcement (when changing announcement settings):
Normal 350 meters
Early 500 meters
Late 400 meters
Announcement after leaving a track: 450 meters.
For instance,  at 48.13831, 11.37815 OsmAnd did not announce that you have to turn left,
at 48.12332, 11.52199 that you have to turn right.

**Comment by scaidermern** [comment]
The missing turn announcements are caused by #3908.
