### ISSUE TITLE
Echinger lake missing (road only maps)

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/OsmAnd#5980]
![screenshot_20180626-170311](https://user-images.githubusercontent.com/40493090/45039921-652a6080-b06d-11e8-97fe-2ee432575c09.png)
 Coordinates: 48.288662, 11.631612
https://www.openstreetmap.org/#map=16/48.2890/11.6306

**Comment by xmd5a2** [comment]
Can't reproduce. Do you have latest maps and/or use live updates?

**Comment by vshcherb** [comment]
Unfortunately something went wrong but we can't reproduce it yet.

**Comment by hman2** [comment]
Almost 2 years have passed, there were serveral new release of the app AND of the maps - and the lake is STILL missing! Interestingly, the error does not come from Open Street Maps. In their maps the lake is contained. I opened an issue with them, and they reported it must be a bug in Osmand, and asked me to open a ticket there. Which I have done years ago...

If you can't reproduce, then please make sure that you are on the STREET MAP of Bavaria. Street map only. It could well be that the full map contains the lake, but the street map does not.

**Comment by pebogufi** [comment]
I suppose you mean the "road-only-maps". This map has reduced contence / reduce details to get a reduced size. 
If you want all details please use the normal map.

**Comment by vshcherb** [comment]
Road only maps are limited to certain objects size

**Comment by hman2** [comment]
"Reduced details" ? Look at the screenshot I provided! Road-only maps does show the MUCH smaller environmental habitat just south of the lake. This habitat cannot be seen from the roads, while the much larger lake is clearly visible and serves as a landmark when you walk or ride there, you can even see it from the car road.

I would understand if this reduction would include ALL lakes, but it doesn't, and it removes only the bigger and not the smaller even invisible lakes. That absolutely makes NO SENSE, at least to me.

**Comment by hman2** [comment]
If you want to save some bytes, then eliminate the environmental habitat, because it is a) totally invisible when you walk the area and b) no one except for the autorities is allowed there, while the large lake is the (the only) landmark there.
So if those couple of bytes really concern you, then eliminate the habitat, but include the lake.

Don't you think it looks "strange" that you have a label "Echinger See" (Eching lake) on the map, but the lake itself is missing altogether?

**Comment by vshcherb** [comment]
https://www.openstreetmap.org/way/7991217

**Comment by hman2** [comment]
Yep, in this view the large orange thing is the missing lake, you can see the pedestrians way (bicycles allowed) around it,  in the northeast you can see the building of the lifeguard including their landing stage for the rescue boat. Even further nortwest is the large parking area of the recreational area including the bus line that runs there. In the northeast you can see a small kiosk that sells food and drink to all the people visiting the recreational area, going for a swim in the lake. The small light blue south of the orange is the habitat, which is currently contained on the street map.

**Comment by hman2** [comment]
Several versions of the app and of the maps later - the lake is still missing...

**Comment by xmd5a2** [comment]
Still can't reproduce. Only Germany_bayern_europe_2.obf map is downloaded.
![Screenshot_2021-04-02_16-55-55](https://user-images.githubusercontent.com/5829014/113421808-5dbdc600-93d4-11eb-8429-7edfa3ea3e0a.png)
![Screenshot_2021-04-02_16-53-33](https://user-images.githubusercontent.com/5829014/113421814-5eeef300-93d4-11eb-8027-2a0712704bcb.png)

**Comment by hman2** [comment]
Wrong map! Use "road map only"! On the road map the lake is missing, but the habitat just south of it is included.

**Comment by hman2** [comment]
![Screenshot_20210403-215825](https://user-images.githubusercontent.com/56226787/113490075-3e07ca00-94c8-11eb-918b-39bafe1b7397.png)

**Comment by hman2** [comment]
Update: Discovered another missing lake in the area: "Pullinger Weiher" in Pulling, next to 85354 Freising, is also missing completely on "road maps". 24 hectares... 48° 21′ 11″ N, 11° 42′ 31″ E. And just like the lake in Eching, it's listed on openstreetmaps.org, so I suspect it's an encoding issue that drops the layer in which both lakes are drawn... https://www.openstreetmap.org/search?query=Pullinger%20Weiher#map=16/48.3523/11.7112

**Comment by hman2** [comment]
So I checked for other lakes, and found another missing lake: Mallerhofer See, https://www.openstreetmap.org/search?query=mallertshofer%20see#map=18/48.26459/11.60083 is also missing on "road maps"...

**Comment by hman2** [comment]
And a fourth, Fasaneriesee (14,7 hectares) https://www.openstreetmap.org/search?query=Fasaneriesee#map=17/48.20415/11.52929 missing, too.

**Comment by hman2** [comment]
With the latest maps from December 2021, the lake is STILL missing. Three years after I reported the problem!

**Comment by vshcherb** [comment]
We don't consider it's critical cause road-only maps are missing lots of features by the size anyway. It's probably not going to be fixed at all

**Comment by hman2** [comment]
Perhaps you should reconsider. Not only is the lake a major (the major) local recreational area, at the moment there is a music festival going on there.

**Comment by scaidermern** [comment]
It is not feasible to decide for every large landmark of the world whether to include it in the road only maps. The name road only maps already tells that not every feature will be present.

**Comment by vshcherb** [comment]
Once we have more tags that could indicate OSM features prominent or not and if it wouldn't affect the size we could consider to fix it.

Meanwhile you can use POI because they are present in road only maps
