### ISSUE TITLE
Initial voice announcement after route calculation gives time estimate as "12 dot ought" minutes (for example)

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#5985]
What version of OsmAnd are you using, on what device and Android/iOS version?

OsmAnd+ night build 3.2.0#25808m, released 2018-09-04 (but also other recent night builds)

Samsung Galaxy S9+ running Android 8.0; Samsung Galaxy S7 Edge running Android 8.0

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

Your offline maps

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

US Georgia, US Florida, released August 2018, but the problem was only recently introduce in the last couple of weeks.

US English

When OsmAnd finishes calculating a route and gives the initial announcement of the distance and time estimate, the time is given as (e.g.) "12 dot ought" minutes, or sometimes "50 dot ought 2 dot ought" minutes.

I'm not sure about UK English, but in US English we rarely use "ought" for zero.  Also, certain route calculations result in two time announcements in a row.  Also also, the time estimates announced are incredibly wrong (too short by far).  The displayed time estimate in the upper right appears correct.

If you want me to get an audio recording of a route between specific start/end points, I will do what I can.

**Comment by jfburke3** [comment]
Perhaps; I'm not familiar enough with what they're doing in the code to be able to tell.

**Comment by sonora** [comment]
@PaulStets `Math.round` as used in `function time(seconds)` should return an integer as per JS documentation, but it seems we somehow cast into a decimal number before passing to the voice engine?

**Comment by jfburke3** [comment]
This made it into the just-released play store beta version....

Personally, I don't think you should do a non-beta new version release until this is fixed.
