### ISSUE TITLE
Feature request: add relative bearing angle between two points

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#5987]
Is it possible to display the bearing angle in addition to the distance between two points? This can help - with the offline map - to determine the current position in case the GPS reception is failed.

Example photo montage how the relative bearing could be displayed

![image](https://user-images.githubusercontent.com/40493090/45099419-e1857800-b12f-11e8-9b83-6d0df4d442fc.png)

**Comment by breversa** [comment]
Agreed !

And while you're at it, offer to display bearing in either degrees or milliradian (https://en.wikipedia.org/wiki/Milliradian). Soldiers will love it ! :)

**Comment by breversa** [comment]
Also, reverse bearing (from point B to point A) might come in handy too.

It would then help to display the 0° line on the point of origin, to prevent mistakes.

**Comment by vshcherb** [comment]
Added
