### ISSUE TITLE
Search: sorting is not correct

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#5991]
When searching for a destination, the first search results OsmAnd gives are in another city instead of offering the results that are the nearest to the current position (which are at the end of the results list). 
![image](https://user-images.githubusercontent.com/40493090/45164167-908e8600-b1fa-11e8-8e4d-2c4c4e9e8230.png)

**Comment by crimean** [comment]
Please don't use space between house number and index(letter) of building. For example: Lenina 30A is correct.
