### ISSUE TITLE
Voices that I've removed keep coming back

### ISSUE THREAD

**Issue by martenjj** [osmandapp/OsmAnd#5994]
I like to keep things tidy, and also keep scrolling lists as short as possible to make them easy to flick through.  So, since I don't understand any of those languages, I usually remove the Asian and East European languages from the Download Maps - Local - Voice prompts (TTS) section.  This appears to work, but at some time in the future the removed ones come back again.

Possibly this happens on an update of the app, because of those entries in Osmand/OsmAnd/assets/bundled_assets.xml using the option:

<asset source="voice/ja/ja_tts.js" destination="voice/ja-tts/ja_tts.js" mode="alwaysOverwriteOrCopy" />

and the use of the alwaysOverwriteOrCopy option.  Obviously this is done to provide a useful set of voice defaults when the app is installed for the first time, but if my reading of the comments above is correct it also reinstalls the voices on every update.

Suggest that the default set of languages should use alwaysCopyOnFirstInstall instead, which should also imply overwriteOnlyIfExists for subsequent updates.

**Comment by beatnickgr** [comment]
Same problem here (I was gonna open the same issue).

**Comment by hakuchi** [comment]
I reported this years ago https://github.com/osmandapp/Osmand/issues/3279

**Comment by Rowin63** [comment]
Same here. I don't remember how many times I removed all the voices I'll never need, they are back again and again.

**Comment by Suncatcher** [comment]
any update about that?

**Comment by vshcherb** [comment]
No updates so far, TTS is not visible any more on Local Maps

**Comment by Suncatcher** [comment]
it is visible in local maps

![image](https://user-images.githubusercontent.com/6388034/169077381-3c1ddcb5-78b2-4714-8f62-deaf6e14f05e.png)

**Comment by Rowin63** [comment]
Chinese, French, Italian, Dutch, Polish, Portuguese, Russian and Spanish are the languages appearing again and again. 
About English and German I can´t say, those are the ones I have installed for use.

**Comment by vshcherb** [comment]
Fixed
