### ISSUE TITLE
Missing numbers in Wikipedia articles

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#5996]
Wikipedia article: https://fr.wikipedia.org/wiki/Refuge_de_l%27%C3%89tang_d%27Araing
The examples of the sentences where the numbers are missing in OsmAnd (missing numbers are in bold): 
Le refuge de l'Étang d'Araing est un refuge des Pyrénées françaises, situé à **1 965** m d’altitude dans la commune de Sentein, à l’extrême sud-ouest du département de l'Ariège au pied du pic du Crabère, sur le GR 10.
Un an et **880 000** francs plus tard, le refuge est fini, proposant 52 places.
![screenshot_20180817-162718_osmand](https://user-images.githubusercontent.com/40493090/45217263-233b2d80-b2ac-11e8-8d24-f67597fce918.jpg)
![screenshot_20180817-162709_osmand](https://user-images.githubusercontent.com/40493090/45217265-23d3c400-b2ac-11e8-8bb9-c0144fb94879.jpg)

**Comment by njohnston** [comment]
Similar to #5582, but for Wikipedia rather than Wikitravel. It's the same type of issue that I reported [in a comment](https://github.com/osmandapp/Osmand/issues/5582#issuecomment-412295478) on #5582.

**Comment by PaulStets** [comment]
Fixed with https://github.com/osmandapp/OsmAnd-tools/pull/303. @njohnston I made the search for the placeholders with distance data more generic, so it will also fix the issue described in your comment in #5582 and similar issues in other languages.
