### ISSUE TITLE
Wrong openstreetmap link

### ISSUE THREAD

**Issue by Chumva** [osmandapp/Osmand#5998]
Sometimes links to openstreetmap show wrong type of object, usually node instead of a way. 
You could check it here - https://www.openstreetmap.org/way/33742191 it is way, but in osmand it is node.

![image](https://user-images.githubusercontent.com/19220417/45220031-8b424180-b2b5-11e8-92c0-fb002109acc0.png)

**Comment by ADepic** [comment]
I have seen this too, and then when you click on the link it opens some random node in another country
