### ISSUE TITLE
Feature request: view elevation profile during navigation

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6000]
It would be really great if, while one leaves a track, OsmAnd could show the height profile. So the map and in a small window the height profile and at which point you are.

**Comment by pietervdvn** [comment]
Use the gpx-tracker to record your track. Aftertwards you can see the elevation profile using 'my places'. Adding an extra screen during navigation clutters the user experience and is not relevant for most users.

Please close the issue if this fixed your request.

**Comment by vshcherb** [comment]
I think it is a duplicate anyway
