### ISSUE TITLE
Dashboard only displays a maximum of 3 tracks

### ISSUE THREAD

**Issue by quelbs** [osmandapp/Osmand#6002]
In the dashboard settings you can select the number of tracks (1-10) to be shown. Selecting 1-3 works fine, but every selection larger than 3 only displays 3 tracks.

OsmAnd 3.2.0#25837m
Android 7.1.1

**Comment by vshcherb** [comment]
Thanks a lot, please test it with nightly version

**Comment by mtelgkamp** [comment]
Nightly version works as expected for me, thank you for merging.

**Comment by quelbs** [comment]
Nightly version works as expected for me. Thank you for merging.
