### ISSUE TITLE
Rename "Mapillary" to "street-level imagery" in configure map settings

### ISSUE THREAD

**Issue by ADepic** [osmandapp/OsmAnd#6003]
A average user scrolling through these settings will have no idea what mapillary is if they have never seen it before. Most people dont bother to search it up either.

Then when you click on mapillary images, then it should show Mapillary.

**Comment by jfburke3** [comment]
Considering that it only loads Mapillary images right now, I'm not sure changing it to something generic is completely the right thing.

Maybe "street-level imagery (Mapillary)" would work?

**Comment by ADepic** [comment]
Travel guides only shows wikivoyage yet it is called travel guides...

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by vshcherb** [comment]
Should be considered definitely to make it more clear. Travel guides supports any custom travel guides it is only wikivoyage provided by us today though.

**Comment by vshcherb** [comment]
Adding milestone to get it fixed next release

**Comment by ADepic** [comment]
Its been a year - any news?

**Comment by ADepic** [comment]
Surely all this requires is renaming mapillary to street-level imagery in the strings.xml?
` <string name="mapillary">Mapillary</string>`
changes to
 `<string name="mapillary">Street-level Imagery</string>`

**Comment by vshcherb** [comment]
We need to add 2nd line in configure map [street level imagery] or swap them

**Comment by dmpr0** [comment]
I think while renaming option we loose the next screen with filters.
