### ISSUE TITLE
Switch off travel guide announcements

### ISSUE THREAD

**Issue by MeCias** [osmandapp/Osmand#6004]
Hi,

Why do I see Travel Guide announcements, even if I haven't used it yet or downloaded something for it? How can I switch it off? I do not want to see every time I open osmand this kind of announcements / advertisements.  

![screenshot_20180906-131257](https://user-images.githubusercontent.com/4476171/45255514-c57c1380-b387-11e8-963c-fa8c30f70caa.png)

**Comment by njohnston** [comment]
Does Settings -> General Settings -> "Don't show startup messages" (which also controls "special local event messages") work?

**Comment by MeCias** [comment]
Thanks a lot njohnston,
I overlooked that switch since I was under the impression it had to be a travel guide setting.
It seems to work for now, if some announcement still shows up I will re-open that issue.
Thanks again
