### ISSUE TITLE
OSM TAG in routing and rendering not available(ramp:bicycle=yes, highway=steps)

### ISSUE THREAD

**Issue by quax2712** [osmandapp/Osmand#6006]
Hello all,
I changed Routing and Rendering XML files to improve OSMAnd for Cycling.
In Routing.xml (section Access) I tried something like:
<if t="highway" v="steps">
		<select value="1" t="ramp:stroller" v="yes"/>
		<select value="1" t="ramp:bicycle" v="yes"/>
		<select value="1" t="ramp" v="yes"/>
		<select value="-1" param="avoid_stairs"/>
 </if>
but no effect.

In Rendering.xml same Problem:
…
 <filter additional="ramp:bicycle=yes" strokeWidth_5="8" color_5="#00aa00"/>
<filter additional="ramp:stroller=yes" strokeWidth_5="8" color_5="#00aa00"/>

I found one information telling something about tags build like this:
Use "ramp bicycle" or use "ramp (bicycle)", but this although has no effect.
Can anyone help me?
regards
Rainer

**Comment by vshcherb** [comment]
You code is not visible.
You need to check if the tags are available in the map itself. You can do it with OsmAndMapCreator and utility inspector.sh
