### ISSUE TITLE
Land/Bridge is missing from nautical view.

### ISSUE THREAD

**Issue by noci2012** [osmandapp/Osmand#6007]
Before entering an issue, please read the information below.

What version of OsmAnd are you using, on what device and Android/iOS version?
Osmand+ v3.1.5
Samsung S5 mini, Galaxy TAB-A 
V6.0.1 , V7.0

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?
Offlinemaps (august 2018, edition)

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.
On the OsmAnd view land is visible
On the Nautical view the land has sunk beneath the waves.

Map: Netherlands, Flevoland and Netherlands, OverIjssel

**Comment by noci2012** [comment]
how to upload files here, i just get the message  "Something went really wrong, and we can't process that file, try again"   Tried .jpg, .png and a .zip containing a version of those.

**Comment by noci2012** [comment]
The problem show near locations:
lat 52.51411 lon 6.08844 Missing bridge for bicycle path
lat 52.32683 lon 5.13977 The new location of Atlantis.   (sunken land)
lat 52.33929 lon 5.13273 much of the land is missing as well, only the jetties of the harbour are drawn.
The last one is even missing some land in Osman rendering.

**Comment by noci2012** [comment]
Just downloaded the Sep 2018 version of the maps.
Still a problem,  lat 52.32957 lon 5.15562 might show a clue Why it goes horribly wrong.
There is some line the clips part of rendering., anything outside of the line is incompletely rendered.
There is a road Gooimeerdijk-West, which is definitely NOT in the water, it's on the dike, about 4 meters above water.
Which goes on to lat 52.33025, lon 5.21417 where the buildings for AQUAVITE, Scouting & Reddingsbrigade definitely are very well established on land.

**Comment by xmd5a2** [comment]
Duplicate (lat 52.32683 lon 5.13977, lat 52.33929 lon 5.13273). https://github.com/osmandapp/Osmand/issues/6008
Problem is in basemap coastline. Other locations issued here are fixed.
