### ISSUE TITLE
World basemap: Lake Huron rendered as coastline causes problems

### ISSUE THREAD

**Issue by robfors** [osmandapp/Osmand#6008]
# Screenshots
Lets start with some screenshots of the problem.
### Zoomed Out
![zoomed out](https://user-images.githubusercontent.com/5009573/45260906-997d8400-b3c1-11e8-9016-754f018972a1.jpg)
### Zoomed In
![zoomed in](https://user-images.githubusercontent.com/5009573/45260944-80c19e00-b3c2-11e8-8764-7eaf8503358b.jpg)
### Zoomed Out
![zoomed out](https://user-images.githubusercontent.com/5009573/45260948-a9e22e80-b3c2-11e8-87f0-745d11a027a0.jpg)
### Zoomed In
![zoomed in](https://user-images.githubusercontent.com/5009573/45260949-b6668700-b3c2-11e8-843c-b383d05efcad.jpg)
# Problem
A few rendering issues can be observed from the screenshots when _World overview map_ is installed:

- The white polygons near _Hawarden Island_ and _Maud Island_
- The shoreline in the center of the image that disappears when zoomed in to that level
- There is no need to see the line that represents (what I am assuming is) the approximated shoreline for the _World overview map_, given that I have the local map installed (_Canada Ontario_).

# Details

The location of interest can be found near `45.24388 -80.13922` on OsmAnd+.

Maps:

- _Canada Ontario_: Jul 31, 2018
- _World overview map_: Mar 16, 2018

OsmAnd+: 3.1.6
Android: 7.1.1
Phone: ASUS Zenphone 4

**Comment by vshcherb** [comment]
Due to inconsistency between coastline rendering and water rendering these problems occur.
There is only one solution as I see:
Basemap should contain Great Lakes as lake relation

**Comment by xmd5a2** [comment]
Fixed by removing inner coastlines from basemap. Already available for downloading.
