### ISSUE TITLE
Bad navigation in roundabout

### ISSUE THREAD

**Issue by gunnar22** [osmandapp/Osmand#6010]
OsmAnd ignored the roundabaout and instead of telling me to enter the roundabout and take the second exit, it told me to turn right and then sharply left, which is wrong.
See screenshot.

OsmAnd+ 3.2.0
Offline maps from Sep 1, 2018 + Live update.
OsmAnd's in-app offline routing, profile for car. Fastest route.
Position 63.40877, 10.44740. City Name: Trondheim, (Trondelag) Norway.
https://www.openstreetmap.org/#map=19/63.40878/10.44740
Navigation from SW to NE through the roundabaout.
I have opened an OSM editor on my PC and examined the OSM map data and could not find any problem.

![navigation-roundabout](https://user-images.githubusercontent.com/30504902/45264113-9d4bed80-b437-11e8-89a2-6d37cd04853a.png)
Bad navigation in roundabout.

**Comment by jfburke3** [comment]
Could this be related to #5689 ?

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-resources/commit/3d70dd61f33432c4052f76cf17d1ebeb617e1326
