### ISSUE TITLE
Ferry is not taken into account in routing

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/OsmAnd#6012]
Planning a route by car from Jægerspris, Denmark to Växjö, Sweden. Suggested route is via the Øresund bridge, Malmö, Helsingborg
There's a much shorter route via the ferry Helsingor-Helsingborg which OsmAnd does not take into account. Even if the destination is set directly to Helsingborg, Sweden, the suggested route is via Øresund bridge, Malmö etc. It seems that the ferry alternative isn't taken as an option.
Navigation settings by car. Fastest route. 
NOT ticked any of the "Avoid..." options
![image](https://user-images.githubusercontent.com/40493090/45265332-e446dc80-b451-11e8-8402-d6f2064454c6.png)

**Comment by Drudoo** [comment]
This is still a huge issue when commuting between Denmark and Sweden. Even when routing from the ferry terminal and across the water it reroutes you hours away over the bridge.

**Comment by vshcherb** [comment]
Moved to https://github.com/osmandapp/OsmAnd/issues/5815
