### ISSUE TITLE
Insufficient information in the seach results 

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/OsmAnd#6013]
It is difficult to distinguish between the results when there is no information about the street, city, etc. You have to check every option in the results which is not user-friendly. 
![image](https://user-images.githubusercontent.com/40493090/45265462-bebad280-b453-11e8-9f41-b6ebb8a23598.png)

**Comment by ADepic** [comment]
Can you PLEASE bump this up to 3.2/future milestone? All it requires is showing the street that the POI is on, e.g. 
Urfa Grill
Fast Food - Foobar street

**Comment by bitboy85** [comment]
Yes, please add city and street. Maybe the text "POI type" (Fast Food, Restaurant) could be omitted because the type is visualised by the icon.

**Comment by scaidermern** [comment]
Not sure if removing the description is a good idea. The icons from the screenshot above are pretty self-explanatory but this doesn't apply to all icons. Better keep the description and add city (+ street?) in the same or an additional line.

**Comment by breversa** [comment]
Adding City + street + number (in case of a very long street) would be enough IMO.

**Comment by littlehelper** [comment]
+1
(see also #2993, #3327, #4738, #4174, #4176)

**Comment by EvanCarroll** [comment]
I think what the OP really wants here is "branch" to show up. Urfa Grill is a Fast Food restaurant. I think this would solve this problem https://github.com/osmandapp/OsmAnd/issues/6947

Then when you search for the Urfa Grill you'd see the different branch names.

Maybe we could close this or triage it after branch name is there. Personally, I'd like to know the branch name in 100% of the cases I'm searching. I don't typically want to know the street name or suburb.
