### ISSUE TITLE
OSM TAG ramp.* I could not find in OBF File of OSMAnd

### ISSUE THREAD

**Issue by quax2712** [osmandapp/Osmand#6015]
I changed Routing and Rendering XML files to improve OSMAnd for Cycling.

But additional tag "ramp" used in compination of highway=step seems to be left in OBF File.

so this lines could not work 
In Routing.xml (section Access) I tried something like:
select value="1" t="ramp:stroller" v="yes"
select value="1" t="ramp:bicycle" v="yes"
select value="1" t="ramp" v="yes"

Regards
Rainer

**Comment by xmd5a2** [comment]
Line like this should be in rendering_types.xml in routing section
`		<routing_type tag="boat" mode="amend"/>
`
