### ISSUE TITLE
Improve LIVE Updates

### ISSUE THREAD

**Issue by gunnar22** [osmandapp/OsmAnd#6028]
OsmAnd LIVE Update seems to only add information, not remove old information. See example in the figure below. If this is correct, let me suggest that the Update action should remove obsolete data.
https://www.openstreetmap.org/#map=19/63.39695/10.54531
OsmAnd+ 3.2.0

![image](https://user-images.githubusercontent.com/30504902/45361167-d15b1600-b5d1-11e8-83e7-7663a5b540e8.png)
A road junction was moved slightly in OSM a few days ago. The obsolete data are indicated with red hand drawing and the new data from LIVE Update with blue.

**Comment by gunnar22** [comment]
It turns out that closing and opening OsmAnd fixed the apparent issue. So this ticket can be immediately closed.

**Comment by gunnar22** [comment]
Now that I know, I'll restart OsmAnd, and that is OK. You might consider automating this internally in OsmAnd to make the experience smoother for the average user(?)

**Comment by pebogufi** [comment]
Most changes with live work with automatic refresh of screen.

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/18153
