### ISSUE TITLE
Unnecessary redrawing of map with "Measure distance" tool

### ISSUE THREAD

**Issue by gunnar22** [osmandapp/Osmand#6032]
There is some unnecessary(?) redrawing when using "Measure distance" tool, which slows down the UI and leaves the screen without map or with map being redrawn for too long.

Here is how to reproduce the phenomenon:
Select "Measure distance" in the main menu.
Set many points on the map, one tap on the map for each point to be included. The map is centered for each point. (No NOT use the move-map and press +Add technique)
Keep placing points a few cm apart so that it really has to "sweat" centering the map for each time. over and over (once for each point).
After a while one can see that the map is first being centered and in a glimpse of a fraction of a second _there is a perfectly centered map there_. But then this map is _blanked out_, and a (slow) redrawing is done. Maybe this blanking and redrawing is redundant and can be avoided.
Version: OsmAnd+ 3.2.0, Offline maps.

**Comment by gunnar22** [comment]
See video of using the "Measure distance" tool (video file in the attached zip-file). 
On most of the taps it centers the map, shows the centered map perfectly very briefly, then blanks it and redraws it.

[center-blank-redraw.zip](https://github.com/osmandapp/Osmand/files/2379789/center-blank-redraw.zip)

**Comment by AlexSyt** [comment]
This happens because of disabled animations. I'll see what I can do about it.
