### ISSUE TITLE
"Search nearby" broken in latest nightlies

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#6033]
Long-tap anywhere on the map, then on the context menu select "Search nearby", then tap a Category like "Accommodation". OsmAnd now announces "no results found", asks to increase the search radius, although nearbyresults are present. Not observed with August builds.

**Comment by jfburke3** [comment]
I just noticed this, too.

**Comment by vshcherb** [comment]
Couldn't reproduce yet

**Comment by sonora** [comment]
I am not sure if this is sporadic now or in fact gone, am on a 9-22 nightly now and can in deed not reproduce for now.

**Comment by vshcherb** [comment]
that was very strange though it could be possible because of broken build... ok let's monitor in future
