### ISSUE TITLE
"postbox" POI category duplicated (in German locale)

### ISSUE THREAD

**Issue by RalfJung** [osmandapp/Osmand#6039]
I just searched for "Briefkasten" (German for "postbox"), which surprisingly turned up *two* categories as result, both with the same name "Briefkasten" but with a different icon.  One of these categories showed a nearby postbox, while the other showed no result.

Either these two POI categories are meaningfully different, then they should get a different name, or they are the same and should be merged.

This is using OsmAnd 3.1.6 installed via F-Droid.

**Comment by RalfJung** [comment]
This is what it looks like:

![screenshot_20180913-185430](https://user-images.githubusercontent.com/330628/45503300-ba115980-b786-11e8-9ef0-d061de8cb021.png)

If I wait a bit longer, individual POIs start showing up, but usually I anyway just want the category highlighted on the map.

**Comment by scaidermern** [comment]
According to https://hosted.weblate.org/languages/de/osmand/search/?q=Briefkasten one is a "post box" and the other one a "letter box". A [letter box](https://wiki.openstreetmap.org/wiki/Tag%3Aamenity%3Dletter_box) is a "private mailbox where mailmen or other people deposit letters to specific addresses".

I think the second one needs a better translation. According to https://de.wikipedia.org/wiki/Hausbriefkasten we could either use "Hausbriefkasten" or "Privatbriefkasten". What do you think?

**Comment by RalfJung** [comment]
Ah, I suspected it might be something like that. Indeed the German word has two distinct meanings here, and we usually disambiguate by context. I do not think I have ever had to use the words "Hausbriefkasten" or "Privatbriefkasten".

What is most surprising to me here is the idea that a "letter box" would even be marked on a map -- every single house has one, but only the people living there (and the mailmen) care about it. I cannot imagine a situation where I would look for a letter box on a map.  But that might well be different elsewhere.

Google shows way more results for "Hausbriefkasten" than "Privatbriefkasten", so I think I'd use "Hausbriefkasten".

**Comment by scaidermern** [comment]
"Hausbriefkasten" is also my preference, I've changed the translation accordingly.

You can close this issue if you think the problem has been resolved.
