### ISSUE TITLE
Toilets which offer drinking water don't show up in category search

### ISSUE THREAD

**Issue by pietervdvn** [osmandapp/Osmand#6040]
Some restrooms have a tag 'drinking_water=yes', e.g. if they have a lavabo where it is possible to refill a drinking bottle.

When searching in category search for 'drinking water', only 'amenity=drinking water' shows. It would be cool if these restrooms could show up too.

Per example:
Restroom
Location: geo:45.86285,17.650223?z=19
https://osmand.net/go?lat=45.86285&lon=17.650223&z=19

**Comment by scaidermern** [comment]
Nice idea.

However I guess this can't get implemented for the same reasons as #5768? :/

**Comment by pietervdvn** [comment]
Yes, seems like this makes it a duplicate of #5768. I'll close the issue.
