### ISSUE TITLE
POIs don't update in OsmAnd Live

### ISSUE THREAD

**Issue by Discostu36** [osmandapp/Osmand#6052]
When using OsmAnd Live, POI information doesn't update correctly. When clicking on an POI, outdated information is shown, even when opening the advanced information. Interestingly, when editing the POI, all the current information is shown.

OsmAnd 3.1.5
Samsung Galaxy S5
Android 6.0.1
Map: Germany - Schleswig-Holstein
![screenshot_2018-09-16-21-51-08](https://user-images.githubusercontent.com/30999326/45600459-43ca5c80-b9fd-11e8-8a8b-bf9a6e1abbcf.jpg))
![screenshot_2018-09-16-21-51-21](https://user-images.githubusercontent.com/30999326/45600458-43ca5c80-b9fd-11e8-9792-078a804b2b5f.jpg)
![screenshot_2018-09-16-21-51-34](https://user-images.githubusercontent.com/30999326/45600457-43ca5c80-b9fd-11e8-9fef-bbf35f575a84.jpg)

**Comment by pebogufi** [comment]
See also
https://github.com/osmandapp/Osmand/issues/5619

**Comment by PaulStets** [comment]
Fixed with https://github.com/osmandapp/OsmAnd-tools/commit/1018dc18de3a2d7d10579d830d4dac3497d65cfb. This should not happen in the future though it will not affect this particular problem this month.
