### ISSUE TITLE
Better search experience

### ISSUE THREAD

**Issue by jancborchardt** [osmandapp/Osmand#607]
Search is a central part of any maps app. In OsmAnd »Search« is shown prominently in the menu, but it actually is more of a »Browse« function rather than simple search. I really like OsmAnd but the way search currently works really bugs me. So let’s improve it! :)

There currently are six (!) different ways to search/browse:
* Points of interest (default)
* Address search
* Coordinates
* Favorites
* Search history
* Transportation

If you’re looking for a restaurant for example, POI → Search by name is fastest (if you find it among the options).

If you want to look up an address, it gets cumbersome:
1. choose a region
2. choose a city
3. choose a street
4. choose a number

Which is kind of backwards from how people normally approach it. First you search for street+number, and if there are multiple results you either just choose one, or you add the city.

Then it comes to actually _seeing_ the result. In the address search, it takes some time to find out what you actually are supposed to do: Press one of the icons in the bottom bar (not knowing what they are for):

* routing/directions
* add as waypoint
* show on map (the thing I want!)
* add as favorite
* the arrow → gives me »online search«

Interesting, online search is actually the thing I wanted when I pressed »search« in the first place. Or rather: One input field where I can put in what I want to search.

All the other things like history, favorites etc could be suggestions in the results. But not separate categories which make me confused about what I need to select to simply get results.

Then there’s another thing which bars me from simply seeing what I wanted to search: I get a popover asking me if I want
* Directions
* add as waypoint
* Show on map
* add to Favorites

Where instead it could simply just show it on the map automatically and I could then decide what I want to do with it.

If that is a direction you are generally willing to go into, I would be happy to provide mockups, design consultation, and the like. :)

**Comment by vshcherb** [comment]
Thanks for input, This is going to be changed.

**Comment by jancborchardt** [comment]
@vshcherb can you let me know in which way it’s going to be changed? I’d be happy in assisting further to improve the design of OsmAnd.

**Comment by vshcherb** [comment]
Please take a look at POI Search latest version or if possible at iOS port
