### ISSUE TITLE
Search: "Santa" (and Saint) overloads search with unknown city results 

### ISSUE THREAD

**Issue by cgogolin** [osmandapp/Osmand#6076]
I love OSMAND but hardly use the search feature because it almost never yields useful results.

Here an example: I was trying to find the Carrer de Santa Anna in Sant Pol. It is very close to 41.60207 2.622229 (see screenshot). But even when I imitate a search there OSMAND is unable to find the street even though it is clearly visible in the map. I open search at this location and type "santa clara" into the search box. After the search finishes the first hit is Calle Aguamarina in Santa Cruz de Tenerife (2250km away!). Ok, so I try searching for an address explicitly. At the same location I go to the ADDRESS tab. Sant Pol is not listed in the "nearest cities" - fine, it is a small town. I tap SELECT CITY and type sant pol into the search box. The fist result is La riviere du Sant (212km away). I give up and find the street by manually scrolling through the town at a very high zoom level (because of #4881) 

Am I using the search in the wrong way or is it really not possible to find a simple street in a small town?

**Comment by cgogolin** [comment]
![screenshot_20180921-140439](https://user-images.githubusercontent.com/6409421/45880715-2b659380-bda9-11e8-8a2b-9cef93919d5f.png)

**Comment by cgogolin** [comment]
![screenshot_20180921-140945](https://user-images.githubusercontent.com/6409421/45880788-69fb4e00-bda9-11e8-9854-5b9063724019.png)

**Comment by scaidermern** [comment]
I guess this is caused by the name "Carrer de Santa Clara" whereas you are searching for "Santa Clara" (without the "Carrer de"). OsmAnd expects the beginning of the search term to match the address and doesn't perform a substring match.

Either OsmAnd should perform a substring match (unsure if possible, could be rather expensive) or "Carrer de" needs to be handled specially.

**Comment by gunnar22** [comment]
I made it work a few times. At one time when it was virtually impossible to repeat, it seemed to help to close OsmAnd and restart it.
Here is what I did. I am not sure if everything is relevant. You may try it and write your version :-)

Put the orange blob marker on the map somewhere in east Spain (not sure if this is significant) maybe not very far from Sant Pol de Mar. (Let it finish its own search before you proceed)
Search (magnifier glass)
ADDRESS
SELECT CITY
Type: sant pol de mar
(It finds Sant Pol de Mar. Wait until it is at the top of the list)
Select it on the list
SHOW SANT POL DE MAR ON THE MAP
Search (magnifier glass)
X (to exit from the same list which is still there)
SELECT STREET IN "WHEREEVER"
(There is typically another "WHEREEVER" city name there)
Erase "WHEREEVER" from the search field
Type: Santa Clara
(NOTE: Not Carrer de.... just "Santa Clara" is enough, as you wrote)
Success. It finds Carrer de la Santa Clara in Sant Pol de Mar (number 3 on the list) (222 m)
Tap on it, and it is shown in the map. SUCCESS.

**Comment by cgogolin** [comment]
It would be rather problematic if the search string had to match the beginning of the street name. There are streets here who are called "Carrer de X", "Carrer X", "Carrer del X", "X", "Calle X", "Calle de X",... depending on which map or road sign you look at, so it would be impossible to know what to search for. 

A substring match would be a bit more expensive, but still scale the same with the numbers of elements to search, so that I would highly recommend it.

**Comment by cgogolin** [comment]
After restarting OSMAND, the address search via city+street name worked. Can I do anything to help make this always work?

**Comment by vshcherb** [comment]
I'm completely confused. 1) Do we have reproducible 100% issue 2) please say term and what should find.
"santa clara".
I guess main issue is that you don't hit space or click button search in the end like  "santa clara ".  Please make it a list, otherwise we could easily miss a use case.

Search of city "Sant Pol" didn't work?

**Comment by cgogolin** [comment]
The trailing space shouldn't matter. I hope it is trimmed by OSMAND before the search? It looks like it is.

I can confirm that the search now "works" in the sense that it doesn't find the street and the town. For some reason it didn't when I reported this before restarting OSMAND. I think there is some type of bug here. Maybe a race condition?

The second problem is that during a "search near here" the street santa clara, that is just a fee meters away, ends up pretty far down in the result list. For example far below "Calle Antonio Jose Melo y Novo" which is more than 2200km away. Not exactly what I would expect in a "search near here". I would consider this a bug as well, at least from a user experience perspective...
-- 
Christian Gogolin
http://www.cgogolin.de

**Comment by vshcherb** [comment]
OK now the issue is very clear. 
The word "Santa" produces too many cities far way and causes search to be overloaded.  Search  "Clara" and you will get expected results

**Comment by vshcherb** [comment]
"Sant pol" is not visible because it is a small village which might be a separate issue we need to fix though it is searchable easily in "Select city"

**Comment by cgogolin** [comment]
I see. Then maybe the balancing of small vs. far away needs some tweaking? At least in a "search near here" I would expect local results to receive a higher relevance. 
-- 
Christian Gogolin
http://www.cgogolin.de

**Comment by vshcherb** [comment]
We need to add more frequent words (like saint and others)

**Comment by cgogolin** [comment]
Is there a way to extract common names automatically from OSM data? That would probably be the best solution and also make sure that this works properly in non English speaking regions.

**Comment by scaidermern** [comment]
Is this the right approach to this problem? Is this even necessary after implementing #6149?

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/commit/980c4997995a25f93a08150ef895e3884f223744
