### ISSUE TITLE
Map orientation widget suddenly disappears if set to north

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#6077]
The map orientation widget suddenly disappears if set to no orientation (north always up).

Steps to reproduce:

1. Switch to any mode, e.g. car mode. The map orientation widget is displayed and stays displayed forever.
2. Switch map orientation to no orientation (north always up)
3. The map orientation widget disappears after a few seconds and won't reappear again
4. Switch to a different mode and back. The map orientation widget reappears.

This is quite irritating since the user has no idea how to switch the map orientation again once the widget disappears.

I'm not sure if this is intended as a feature. However during navigation I occasionally switch the orientation to north up to get a better overview of the map and the route. If the widget suddenly disappears I can't switch back without switching to world view and back  to car mode.

**Comment by scaidermern** [comment]
> I think this is considered a feature. The current behaviour was introduced a few years ago to reduce clutter on the map view IIRC.

Oh, interesting. However I doubt that having a widget magically disappear and reappear really improves user experience :/

> To get the widget back, rotate the map with two fingers.
> 
> Also, you can force the widget to appear all the time by going to "Configure Screen", scrolling down to "Left panel" and then enabling "Compass".

Thanks, didn't know that. Both solutions work, even though my phone doesn't have a compass.

**Comment by vshcherb** [comment]
This is how it is designed and works > 1 year. We are still collecting feedback.
