### ISSUE TITLE
opening hours: end month missing

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#6079]
OsmAnd omits the end month for opening hours containing a start and end date.

Example:
![photo_2018-09-22_08-39-37](https://user-images.githubusercontent.com/1040784/45914496-29054700-be46-11e8-8c14-ecfdd92a7545.jpg)

Here, only the start month April is shown but not the end month October.

Object https://www.openstreetmap.org/node/4172730188 with opening hours `opening_hours=Apr 05-Oct 24: Fr 08:00-16:00`.

**Comment by scaidermern** [comment]
But the above opening hours example is pretty simple :\

**Comment by vshcherb** [comment]
It is mentionned as not supported for now 
```
// 0. not supported MON DAY-MON DAY (only supported Feb 2-14 or Feb-Oct: 09:00-17:30)
		// parseOpenedHours("Feb 16-Oct 15: 09:00-18:30; Oct 16-Nov 15: 09:00-17:30; Nov 16-Feb 15: 09:00-16:30");
```
https://github.com/osmandapp/Osmand/blob/master/OsmAnd-java/src/test/java/net/osmand/util/OpeningHoursParserTest.java#L124

**Comment by scaidermern** [comment]
Great, thanks :)
