### ISSUE TITLE
Osmand~ 3.1.6 crashes in FT_Set_Char_Size()

### ISSUE THREAD

**Issue by oliver** [osmandapp/Osmand#6082]
When zooming into Hurghada in Egypt using a downloaded map, Osmand is suddenly closed. Logcat shows a crash in or below the FT_Set_Char_Size() function. Full logcat output is attached: [osmand-crash-1.txt](https://github.com/osmandapp/Osmand/files/2408779/osmand-crash-1.txt).

This crash happens each time I zoom into Hurghada, and also happens for other locations in middle-east area (example: Bizerte in Tunisia). In fact I haven't found any location in Northern Africa or Middle East where I could fully zoom in without crashing.

The crash in Hurghada happens when zooming to about 1:200000. Usually, in other areas of the world I can zoom in all the way without any problems.

I'm using maps downloaded with the built map manager. For Hurghada it probably used the "world overview map" (271.9 MB, 2018-03-16) since I have not downloaded a detailed map of Egypt. There is also hillshading visible, though I'm not sure where that comes from (I guess it's downloaded on the fly when viewing an area?).

This happens with Osmand~ 3.1.6 from F-Droid under Android 7.1.2 (LineageOS 14.1), on a Samsung Galaxy S4 Mini.

**Comment by vshcherb** [comment]
Issue is fixed in 3.2 and already available in Beta.
