### ISSUE TITLE
OsmAnd offers "Create POI" instead of "Modify POI"

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6083]
When trying to modify some of the already existing POIs, OsmAnd offers only to create POI. Is there any reason why OsmAnd does not allow to modify certain POIs or is it a bug?
The example of such a POI: https://www.openstreetmap.org/node/4732579720.
![image](https://user-images.githubusercontent.com/40493090/45929275-03686280-bf58-11e8-8227-d9def358ba9b.png)

**Comment by scaidermern** [comment]
Looks like you didn't select the existing POI but a position nearby. Try to select the existing POI.

**Comment by alyonapinchuk** [comment]
The thing is this position is always selected when you tap precisely on this POI; it is also chosen as the depicted POI, so no, it's not the case. Here is another example:
![image](https://user-images.githubusercontent.com/40493090/45930074-5f84b400-bf63-11e8-8fe8-5201ad1c6c82.png)

**Comment by vshcherb** [comment]
I think it's fixed with precise position for polygons
