### ISSUE TITLE
Meaningful metrics when saving a GPX track

### ISSUE THREAD

**Issue by comradekingu** [osmandapp/Osmand#6085]
When saving a track, it would be nice to know something about it.

Total time travelled
Time travelled (during current GPX track)
Stop time (during current GPX track)
Top speed
Average speed
Ascent/descent
Stop time

This makes a lot of sense for touring cyclists.

They make sense as widgets too, depending on the activity.

**Comment by scaidermern** [comment]
Dup of #6084?

**Comment by comradekingu** [comment]
@scaidermern yes X)
