### ISSUE TITLE
Change avoid motorway routing

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#6086]
As of today we completely forbid motorways/trunks using this settings this leads to totally undesirable behavior that car routing can't have a start point from a motorway.

Instead, of using "-1" we should rather change strategy to have a maximum penalty (deprioritize) to motorways. 
As part of this change we need to test that 
1) routing doesn't become significantly slower
2) we don't have any significant flaws (especially when motorway is bridge).

**Comment by scaidermern** [comment]
This is the same as #5210, isn't it?

**Comment by vshcherb** [comment]
yes
