### ISSUE TITLE
Crash (race condition?) when "screen lock" is active in the phone, screen can be turned off when inactive and navigation is used

### ISSUE THREAD

**Issue by FreddieChopin** [osmandapp/Osmand#6087]
> What version of OsmAnd are you using, on what device and Android/iOS version?

Latest OsmAnd+, but the issue is present for at least half a year. Sony Xperia Z5 Compact (E5823), Android 7.1.1.

> Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

Offline maps.

---

In OsmAnd I have enabled the feature to turn of the screen after some period of inactivity. This works well, with very minor glitches. In my phone I have also enabled the lock screen (I need to "swipe" a proper pattern to unlock it or use my fingerprint). Now the issue happens sometimes in the following scenario:
1. I navigate to somewhere
2. During the period od navigation the screen was disabled at least once.
3. The navigation ends (either canceled or I reached my destination).
4. I want to access the phone now so I either quit OsmAnd or use the "home" button of the phone.

In this scenario _SOMETIMES_ an infinite race condition appears. The screen shows the map for a split second, then the lock screen (usually with a notification bar about a new e-mail, SMS message or sth like that), then the map again, then the lock screen, and this goes on forever. To quit I actually have to reboot the phone. This does not happen always, but I'd say that in 2 out of 3 cases.

If this happens, the next time I start OsmAnd I'm offered to send a crash report (which I did some time ago) - I attach the file that I sent back then, maybe it will be useful.

[exception.log](https://github.com/osmandapp/Osmand/files/2410054/exception.log)

Let me know what more details shout I send to you.

**Comment by scaidermern** [comment]
Sounds like #4667.
