### ISSUE TITLE
TTS messages with numbers of roads use wrong forms in Polish language

### ISSUE THREAD

**Issue by FreddieChopin** [osmandapp/OsmAnd#6088]
This is probably going to be very hard to describe, as the problem is specific to some languages only and English is definitely _NOT_ one of them.

Let's say that there's a road called "Szosowa" and it's number is 796.

https://www.openstreetmap.org/?mlat=50.38025&mlon=19.28503#map=17/50.38025/19.28503

Now the problem is not entirely on OsmAnd side (I'm using OsmAnd+, but I guess this doesn't matter anyway), but probably also in the Google's TTS engine. The issue here is that in Polish language OsmAnd sometimes says the routing instructions as if the road number - 796 - was not a number but the amount of something. This is the tricky part to describe (; Instead of giving instructions like "skręć w lewo w siedemset dziewięćdziesiąt sześć Szosowa" ("turn left to seven hundred ninety six Szosowa") it says something like "skręć w lewo w siedmiuset dziewięćdziesięciu sześciu Szosowa". This is impossible to easily translate to show the problem, but instead of using "siedemset dziewięćdziesiąt sześć" as a 796 number (raw number, with no grammar transformations) it says "siedmiuset dziewięćdziesięciu sześciu", as if it meant there are 796 "somethings" (for example as in the name of the "12 Angry Men" movie the "12" refers to the amount of people involved). This sounds really silly...

What I was thinking, maybe it would be possible to alter the generated strings before feeding them to the TTS engine so that it would pronounce the number of the road as a raw number? Maybe it would be enough to insert a coma (semicolon?) before and after the number, or maybe alter the string otherwise (move the number to the end? put it in parentheses, surround it with dashes? ...?).

**Comment by vshcherb** [comment]
We don't have enough knowledge and rely very much on contributors please take a look at https://github.com/osmandapp/OsmAnd-resources/blob/master/voice/pl/pl_tts.js the idea like here
https://github.com/osmandapp/OsmAnd-resources/blob/master/voice/de/de_tts.js#L307

**Comment by vshcherb** [comment]
It is javascript. Numbers are pronounced directly by TTS, so we pass the number itself.

**Comment by FreddieChopin** [comment]
But which item of the dictionary is the number? Is it in `streetName["toRef"]`?

**Comment by PaulStets** [comment]
Yes, it's ```streetName["toRef"]```.

**Comment by ticotaco72** [comment]
Hello, I believe adding "." at the end of the number before passing it to the TTS could help, as that would mark the number as cardinal (first, second, third... instead of one, two, three...), and TTS possibly could interpret the number in better way.

**Comment by FreddieChopin** [comment]
Here are two GPX tracks which can be used for "emulated navigation" and show the problem.

[Sun 17 Nov 2024_1.zip](https://github.com/user-attachments/files/17792355/Sun.17.Nov.2024_1.zip)
This one has a routing prompt "skręć w prawo w siedemdziesięciu ośmiu wojska polskiego", where something like "skręć w prawo w drogę numer siedemdziesiąt osiem wojska polskiego" would be more appropriate, also a shorter version "skręć w prawo w siedemdziesiąt osiem wojska polskiego" would be acceptable.

[Sun 17 Nov 2024_3.zip](https://github.com/user-attachments/files/17792357/Sun.17.Nov.2024_3.zip)
In here the navigation suggests "zajmij prawy pas w kierunku jednym..." where it should be "zajmij prawy pas w kierunku drogi numer jeden" or sth like this. Notably the first prompt has two route numbers (1 and 91), and only the first one is messed up grammatically, the second one is fine - "zajmij prawy pas w kierunku jednym, dziewięćdziesiąt jeden..."

Some thing worth noting. The problem is ONLY with roads that have "just a number" in the "ref" field. What I mean by that is that it affects only Polish "drogi krajowe" (1-99) and "drogi wojewódzkie" (100-999). There is no problem with Polish "autostrady" and "drogi szybkiego ruchu", because their ref is a letter followed by a number (like "A1" or "S1") - in those cases, the navigation prompt is perfectly fine.

@akotynski

**Comment by akotynski** [comment]
I will try to dig into it this week

**Comment by akotynski** [comment]
I investigated it a little bit. The example generated TTS text is:
`za 200 metrów skręć lekko w prawo na S1 w kierunku 1, 86, Łódź, Częstochowa`
To solve this exact case I had to transform it into 
`za 200 metrów skręć lekko w prawo na S1 w kierunku drogi nr 1 86 Łódź Częstochowa`
So I had to add `drogi nr` (road number) before the road name which is not entirly correct (it is the full road name, not number only).

Failed attempts:
`za 200 metrów skręć lekko w prawo na S1 w kierunku drogi 1 86 Łódź Częstochowa` - `w kierunku drogi **jednego**`
`za 200 metrów skręć lekko w prawo na S1 w kierunku drogi nr 1, 86, Łódź, Częstochowa` - `w kierunku drogi **jedne**`
`za 200 metrów skręć lekko w prawo na S1 w kierunku drogi 1. 86. Łódź. Częstochowa`
`za 200 metrów skręć lekko w prawo na S1 w kierunku drogi 1; 86; Łódź; Częstochowa`
`za 200 metrów skręć lekko w prawo na S1 w kierunku drogi '1', '86', Łódź, Częstochowa`

There are a few issues with the proposed solution:
1. I need to be cautious when adding the `drogi nr` string because it should only be included if the road name begins with a number.
2. It might not cover all the edge cases, anyway.
3. It could potentially break other edge cases.
4. As mentioned earlier, it’s not entirely accurate. I couldn’t find a perfect TTS prompt.

**Comment by FreddieChopin** [comment]
I've installed some TTS tester app and have something promising, which (probably) works for both numbers and `A1` or `S1`. If you put all the road numbers (all `toRef` elements) within parentheses, the TTS stops messing around. So this works for me:

`... skręć w kierunku (1, 81) Łódź, Częstochowa` (also works with a comma right after the closing parenthesis)
`skręć w prawo w (78) wojska polskiego`

Obviously I'm not sure whether it fixes all the edge cases or not, but this seems promising.

**Comment by akotynski** [comment]
Sometimes it works, sometimes not...
`za 350 metrów zajmij lewy pas w kierunku (1)  Łódź  Częstochowa  Warszawa` works
`za 400 metrów skręć lekko w prawo w kierunku (1)  Łódź  Częstochowa  Warszawa` does not work

But...
`za 350 metrów zajmij lewy pas w kierunku [1]  Łódź  Częstochowa  Warszawa` works
`za 200 metrów skręć lekko w prawo na S1 w kierunku [1]  [86]  Łódź  Częstochowa` does not work 

Also tried 
`za 400 metrów skręć lekko w prawo w kierunku [(1)]  Łódź  Częstochowa  Warszawa` but it is not working correctly

**Comment by akotynski** [comment]
Ok, I just replaced all numbers with string values :) 
As a result the text sent to TTS is:
`Prosto przez około jeden kilometr do dziewięćdziesiąt jeden` 
`za 400 metrów skręć lekko w prawo w kierunku jeden, Łódź, Częstochowa, Warszawa`
`za 200 metrów skręć lekko w prawo na S1 w kierunku jeden, osiemdziesiąt sześć, Łódź, Częstochowa`

details are in the attached PR

**Comment by FreddieChopin** [comment]
Fantastic (; I was thinking about changing the numbers to test, but it seem a bit too much work. Your commit looks very short, so great that I was wrong about that (;

Thanks a lot for looking into this and making that PR!
