### ISSUE TITLE
Search UI issues

### ISSUE THREAD

**Issue by gunnar22** [osmandapp/Osmand#6092]
There is definitely a need to do some improvements with the users' experience of Search in OsmAnd. It has left me "stunned" a couple of times and unable to complete a search before I gave up. Now that I have learned some tricks (see my comment in #6076), I am able to succeed. 

I shall describe some search issues that are 100% reproducible.
I pretend to be the average novice user here who has not learned the tricks. Here it goes:
Let's say that I want to search for a street in Oslo (Norway). I assume that I have to first select city and then street. (This assumption is normal, isn't it, for a user in general, and also because on the ADDRESS tab of the main search page, OsmAnd offers both SELECT STREET in .... and SELECT CITY.)
When I see SELECT STREET IN "some other city", I assume that first I have to change that other city into the one that I want to search in now.
- Tap Search (magnifier glass)
- ADDRESS tab
- SELECT CITY
- Type city or town: Oslo
- Tap on result: Oslo (City)
- Tap on SHOW OSLO ON THE MAP
It shows Oslo on the map. Good! Now, at this stage, I assume that I am done selecting city, and can now concentrate on selecting street in that city. 
On the screen I see at the top

<-- Oslo        X
SHOW OSLO ON THE MAP
...list of streets in Oslo...

I do not want to scroll, I want a text field where I can write the street name to search for. 
(And besides, I wonder: Why does it propose to SHOW OSLO ON THE MAP when that is what I just did?)

ISSUE 1 (minor): Why propose to do again what it just did, i.e., SHOW 'found city' ON THE MAP?

Particularly, I want to tap the SELECT STREET on the main search page, ADDRESS tab.

I continue like this:
X (upper right corner) to get done with selecting City and get to the main search page.

It takes me to the main search page.
It is still on the ADDRESS tab, which is fine.
Here is the SELECT STREET that I want.
However, it does **not** say
SELECT STREET IN OSLO
actually, it says
SELECT STREET IN **BERGEN**
because some time earlier today I was searching in Bergen.

**ISSUE 2: After selecting a new city, it proposes the previous city for SELECT STREET**

One more little issue:
I saw different behavior if I searched for Oslo or Orkanger in the SELECT CITY search. After the Oslo search and tapping on the search result it offered me to SHOW OSLO ON THE MAP. After the Orkanger search and tapping on the search result it went straight to showing Orkanger on the map. Why?
I did this many many times back and forth, Oslo, Orkanger, Oslo, Orkanger, Oslo, Orkanger, Oslo, Orkanger. Via SELECT CITY. 100% reproducible.

ISSUE 3: Some searches offer SHOW xxx ON THE MAP, others just go straight to the map

Now, my final searches were like this:
- SELECT CITY
- Oslo
Result:
Oslo \n City \n Could not find anything: 10.0 km

I.e., it both found Oslo and could not find anything
I got this result several times, over and over again.

ISSUE 4: It reports both that it found the city that I searched for and that it can not find anything.

**REBOOT OSMAND**

ISSUE 3 vanished after reboot. The search for Orkanger now offered SHOW ORKANGER ON THE MAP.
Although it was 100% reproducible as described above, it vanished after reboot.

ISSUE 4 vanished after reboot.
After reboot it went like this:
- SELECT CITY
- Oslo
Result:
Oslo \n City \n Increase search radius

ISSUE 1 and ISSUE 2 are still reproducible after reboot.
If I were a OsmAnd developer I would start with ISSUE 2. (But do not forget the others).

Anyway, OsmAnd is awesome. I use it every day. Thanks to the developers who give us this nice product!

(OsmAnd+ 3.2.1)

**Comment by vshcherb** [comment]
That's pretty long issue it would be good to summarize in short or make a video. Probably you can join our telegram channel and explain in details https://t.me/joinchat/F23xLkRF4r5Er262jSsHww. 
Again it looks like you issue is related not to search but to the sequence of "Show on map" actions which might be buggy but it is not clear why "show on map" would be used at all.

**Comment by gunnar22** [comment]
Thanks, I would like to join. In the meantime let us focus only on Issue 2. It can be summarized like this. 
Step 1. I want to first search for a city and then 
Step 2. search for a street in that city. 
After completing step 1, then in step 2 it presents for me not the city from step 1 but some arbitrary city from old search unrelated to the current task.

**Comment by scaidermern** [comment]
> After completing step 1, then in step 2 it presents for me not the city from step 1 but some arbitrary city from old search unrelated to the current task.

Yep. And If I remember correctly this has already been discussed in some other issue but without a real explanation why this behavior is so weird.

**Comment by vshcherb** [comment]
Yes, the several commits are done related to that issue.
