### ISSUE TITLE
Wrong routing on the roundabout

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#6097]
Location: geo:50.42983,30.385012?z=19
https://osmand.net/go?lat=50.42983&lon=30.385012&z=19

![image](https://user-images.githubusercontent.com/20681525/46070495-9e468400-c186-11e8-9950-102b3cf5fca2.png)

**Comment by scaidermern** [comment]
Looks like a problem in the map data. There is a turn restriction "no straight on" which prevents routing through the roundabout: https://www.openstreetmap.org/relation/7644954 and a similar one right next before it: https://www.openstreetmap.org/relation/7644958

**Comment by PaulStets** [comment]
@scaidermern Thank you for the investigation. I have contacted the user who reported this and removed the restrictions accordingly.
