### ISSUE TITLE
Track coloring based on speed

### ISSUE THREAD

**Issue by ThibaultLemaire** [osmandapp/OsmAnd#6099]
This is only a suggestion of improvement based on my user story.

I use OsmAnd~ mainly for cycling, and record all of my trips to work (by bike of course). It was great to explore shorter/better routes.

What I hate the most when cycling, is having to stop, although slowing down is fine (I have an old racing bycicle with poor brakes and due to my saddle setting I'm quite unstable when at a stop. But anyway those are my personal preferences, the user is king, you shouldn't be questioning that).

So I'm currently trying to determine, among the alternative routes that I've tried, which one is statistically the best in terms of the number of stops.

For this use case, __what I would love to have is a heat map on the track in function of speed__. (That could be an added option of the "Color" drop down).

À la runtastic ![runtastic track speed heat map screenshot](https://www.amstore.fr/wp-content/uploads/2017/08/Runtastic-maps.png)

This way, when displaying multiple tracks on the map, I could easily pinpoint the cold spots and try to avoid them.

Of course that feature could be useful for a lot more use-cases.

PS: As I've tried to make explicit, this is nothing urgent. Also, I don't know much of development on Android, but I can try and implement this, if someone would be willing to waste a bit of their time to guide me :)

**Comment by dmpr0** [comment]
We need to:
– Add coloring based on Speed, Altitude, and Slope into track appearance dialog.
– Add expanded bubble switcher to the "Color" section of the "Appearance" menu with the options: Solid (for the current color selection), Speed, Altitude, Slope.
– Below "Speed, Altitude, Slope" buttons show legend for colors used in coloring

**Comment by vshcherb** [comment]
Implemented in nightly to test

**Comment by ThibaultLemaire** [comment]
Tested functional in release 4.0.9 on my device. It's awesome, thanks a lot :tada:

**Comment by ven1999** [comment]
How can I change the colors so that a low speed value is indicated in red and a high speed value in green?

￼

**Comment by ThibaultLemaire** [comment]
To the extent of my knowledge, you can't. Please open a new issue (possibly referencing this one)

**Comment by breversa** [comment]
> How can I change the colors so that a low speed value is indicated in red and a high speed value in green?
> 
> ￼

Also, red/green is a very bad combination for colorblind people.
