### ISSUE TITLE
Destination Null and dot ott minutes spoken

### ISSUE THREAD

**Issue by seahorse41** [osmandapp/Osmand#6104]
This is running Osmand version 3.2.0 on Samsung G900A
offline maps, not connected to internet.
In app offline routing for car.
Seems to be a bug in the application, not in the maps. I did not hear this in 3.1.6

Every time I get close to my destination, it now speaks the words "NULL"
"Keep right on Stanley Street, and arrive at your destination NULL.  You have reached your destination Baker Street 401 Royal Bank of Canada."
or
"Turn Left, then continue for 289 feet and arrive at your destination NULL. ... You have reached your destination 33 North Lambert Lane Porch."

Also it speak an undecypherable word sounds like  "OTT"
"The trip is 112 Mi. Time is 2 hours 16 dot ott minutes."
Then every time I go off route, like a parking lot or rest area I get:
"Route recalculated. Distance 111 miles, time is 2 hours 16 dot ott minutes."
"Route recalculated. Distance 25 miles. Time is 30 dot ott 4 dot ott minutes."

That last one really makes it look like a bug.
At first I thought it was saying dot Naught or dot ODD but sounds more like OTT
Is that a non-english word?

**Comment by PaulStets** [comment]
@seahorse41 Please remove the English tts file and download it again. Let me know if it helps.

**Comment by seahorse41** [comment]
Please clarify, where?
The closest file I can see is in /Android/data/net.osmand.plus/files/voice/en-tts/
2 files
en_tts.js 29773 bytes matches file in the 3.2.0 apk
_ttsconfig.p 18289 bytes dated from August 27, that would be from 3.1.6 I think.

**Comment by seahorse41** [comment]
Also I have it configured: in settings, Storage, to use External storage device.
When I look at /sdcard/Android/data/net.osmand.plus/files/
there are some orphans left here, including in voice/ several *-tts/ directories, and in en-tts/ is 1 file
_ttsconfig.p 18289 bytes dated August 12.

**Comment by seahorse41** [comment]
Ok, I found several other languages enabled, probably defaults, I removed all but english, started a navigation, got the same "hours dot ogg dot ogg minutes" voice, Removed the final english entry, started a new route, same result. I see the /voices/ directory is empty now under /storage/extSdCard/ but no change to the /sdcard/ tree.
Proceeding as directed, I press "download" next to english, and as I expected it says, "Downloads not found, please check your connection to the internet."
So I'll either need to reinstall the apk? or acquire a wireless connection after all.

**Comment by seahorse41** [comment]
Downloaded english as instructed. No change.

**Comment by PaulStets** [comment]
Sorry for the incovenience. As it turns out, the download of the tts files is indeed not available without the Internet. You can either reinstall the app, or download this file https://github.com/osmandapp/OsmAnd-resources/blob/master/voice/en/en_tts.js and put it into the "en-tts" folder in the voice folder.

**Comment by seahorse41** [comment]
I compared the file it downloaded via Osm with md5sum, and found it matched the file in the 3.2.0 apk.
When I downloaded the file your link to github provided, it is different, and after pushing it, the problem is fixed. Thank you.

**Comment by PaulStets** [comment]
I'm really not sure why your OsmAnd copy downloads an old version of the file. I have used the Google Play 3.2.1 version and wasn't able to reproduce this. Anyway, I'm glad it helped. The next version of the app should contain the correct file
