### ISSUE TITLE
Crashing on zooming in the area in the Brandenburg region

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6105]
This happens only in the specific area near https://www.openstreetmap.org/#map=16/52.7045/13.2904. When zooming in to 1 km, the app closes. 
Reproducible on Samsung 8 and Sony Experia XZ2 Compact (H8324) with Android 8.0.0. The map is updated.

**Comment by slarti-zak** [comment]
I also noticed a crash after the update (v 3.2.1) around [this region](https://www.openstreetmap.org/#map=14/52.2687/7.9354). Especially when scrolling or zooming in (also to 1km).
Crash happens on LG G6.

**Comment by simonpoole** [comment]
Crashes on zooming and panning here too (near Zürich), doubt that this is region specific issue. Samsung Note 8 and Android 8.0, worked before last update.

**Comment by coffeemakr** [comment]
I also had crashes while zooming. In safe mode I had no crashes so far.

**Comment by vshcherb** [comment]
Today we are releasing beta build 3.2.2 which should be avalaible by the end of the day

**Comment by vshcherb** [comment]
Fixed with 3.2.2
