### ISSUE TITLE
Routeplaner from map.search set a point in nowhere

### ISSUE THREAD

**Issue by Mannshoch** [osmandapp/Osmand#6110]
A friend of mine had Problem with navigation to addresses. He use map.search.ch to get the correct location for a navigation. If he click to Routplaning, Osmand get started and show me a position on Lat 0, Lon 0

**Comment by vshcherb** [comment]
It is not clear which url was used and whether it is correct url (geo intent for example) or not.

**Comment by Mannshoch** [comment]
Experimenting with the App gave me this example URI from Search.ch
https://www.google.com/maps?daddr=Bahnhofplatz+3,+7000+Chur@46.853582,9.529903
