### ISSUE TITLE
Custom search - same item under multiple categories behaves differently

### ISSUE THREAD

**Issue by mahdi1234** [osmandapp/Osmand#6115]
Osmand 3.2.1 with offline maps with Osmand live.

Zoom in somewhere where's Picnic table, just to see it's really Picnic table.

![screenshot_20181001-153608](https://user-images.githubusercontent.com/1097047/46292196-91fc6580-c590-11e8-815e-98d0438f2deb.png)

Scenario #1

- Search - Categories - Custom search
- Select "Leisure"
- check "Picnic site" + "Picnic table"
- Tap "Apply"
- Tap "Show"

Observed:
No "Picnic table" found

![screenshot_20181001-153842](https://user-images.githubusercontent.com/1097047/46292216-9de82780-c590-11e8-97e2-8f0ad76578bf.png)

Scenario #2

- Search - Categories - Custom search
- Select "Tourism"
- check "Picnic site" + "Picnic table"
- Tap "Apply"
- Tap "Show"

Observed:
Many "Picnic table" items found.

![screenshot_20181001-153942](https://user-images.githubusercontent.com/1097047/46292225-a6406280-c590-11e8-96ce-a9b25107ba96.png)

This seems to be really confusing to have same POI under two categories and returning different result.

Should it matter this item was used for tests - https://www.openstreetmap.org/node/5646158495

**Comment by jfburke3** [comment]
According to the wiki, it's supposed to be tourism=picnic_site and leisure=picnic_table  :-D

So OsmAnd is doing it half right....

**Comment by vshcherb** [comment]
We should consolidate picnic_site / picnic_table under 1 category, either Leisure or Tourism.

**Comment by mahdi1234** [comment]
I'm not sure whether it's relevant or not, running query below reveals several other items being mentioned multiple times in xml file
`cat ./poi_types.xml | grep 'name=' | perl -pe 's/.*?name="(.*?)".*/$1/' | sort -n | uniq -c | sort -n`
and here's those with multiple instances

>       2 accountant
>       2 alpine_hut
>       2 ambulance_station
>       2 attraction
>       2 beach_resort
>       2 bench
>       2 bicycle_parking
>       2 bicycle_rental
>       2 bicycle_repair_station
>       2 boat_sharing
>       2 brothel
>       2 bureau_de_change
>       2 capacity_disabled
>       2 car_rental
>       2 car_repair
>       2 car_sharing
>       2 car_wash
>       2 clinic
>       2 club_sport
>       2 club_tourism
>       2 cross
>       2 cuisine
>       2 drinking_water
>       2 driving_school
>       2 educational_institution
>       2 emergency_phone
>       2 financial
>       2 firepit
>       2 fitness_centre
>       2 fitness_station
>       2 funicular
>       2 golf_course
>       2 government
>       2 guide
>       2 harbour
>       2 horse_riding
>       2 hospital
>       2 hot_spring
>       2 ice_rink
>       2 island
>       2 islet
>       2 landuse_railway
>       2 leisure_track
>       2 library
>       2 mall
>       2 military_landuse
>       2 miniature_golf
>       2 motorcycle_parking
>       2 motorcycle_repair
>       2 museum
>       2 nature_reserve
>       2 office_administrative
>       2 office_camping
>       2 park
>       2 parking_entrance
>       2 picnic_site
>       2 picnic_table
>       2 pitch
>       2 police
>       2 post_box
>       2 post_office
>       2 recycling
>       2 religious
>       2 reservoir
>       2 residential
>       2 rest_area
>       2 route_hiking_iwn_poi
>       2 route_hiking_lwn_poi
>       2 route_hiking_nwn_poi
>       2 route_hiking_rwn_poi
>       2 sanatorium
>       2 sauna
>       2 shower
>       2 ski_rental
>       2 ski_resort
>       2 slipway
>       2 sports_centre
>       2 stadium
>       2 studio
>       2 supermarket
>       2 tax_advisor
>       2 telephone
>       2 theme_park
>       2 townhall
>       2 travel_agent
>       2 vehicle_inspection
>       2 waste_basket
>       2 waste_disposal
>       2 water_park
>       2 water_well
>       2 zoo
>       3 beach
>       3 lighthouse
>       3 parking
>       3 spring
>       3 toilets
>

**Comment by xmd5a2** [comment]
Looks like custom search works incorrectly. <poi_reference name="picnic_site"/> is in "entertainment" category and <poi_type name="picnic_site" is in "tourism" category. POI reference is not searchable using custom search.
