### ISSUE TITLE
Osmand + v3.2.1 crashes 

### ISSUE THREAD

**Issue by Harribo19** [osmandapp/Osmand#6125]
Osmand + update crashes.
Update 19 sept 2018, v3.2.1

The app starts with free offline vector map. When zooming it zooms and then after a moment it crashes

Never had this before with osmand in all those years I have been using this.

Specs: Android 6.0.1, Nubia m2, gps off

I wonder if I can go back to a previous version of osmand + and how?
I use this app very often.

Regards Harrold
Netherlands

**Comment by dmpr0** [comment]
Hello @Harribo19. Please try to update to the new beta version https://play.google.com/apps/testing/net.osmand.plus

**Comment by Harribo19** [comment]
Ok thanks I will try.
But Id rather go back to a previous version of osmand + which works

**Comment by Harribo19** [comment]
The beta version did solve the problem. Thanks

**Comment by dmpr0** [comment]
@Harribo19 Thank you for the feedback, we make the stable release version from this beta in a few days.

**Comment by Harribo19** [comment]
Thank you!


Verzonden door TypeApp<http://www.typeapp.com/r?b=13685>
Op 3 okt. 2018, om 12:49, Dmitriy Prodchenko <notifications@github.com<mailto:notifications@github.com>> schreef:

@Harribo19<https://github.com/Harribo19> Thank you for the feedback, we make the stable release version from this beta in a few days.

**Comment by Harribo19** [comment]
I dont know what solved the crash in this beta version?
I hope this problem will be also solved for others
Not that this was solved by, for example, a new install of an other version.
I assume you have the knowledge :-)

Success and thanks again!

Verzonden door TypeApp<http://www.typeapp.com/r?b=13685>
Op 3 okt. 2018, om 12:49, Dmitriy Prodchenko <notifications@github.com<mailto:notifications@github.com>> schreef:

@Harribo19<https://github.com/Harribo19> Thank you for the feedback, we make the stable release version from this beta in a few days.
