### ISSUE TITLE
Search: parking category shows up twice

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#6137]
The "parking" category shows up twice in the list of search results:

![photo_2018-10-05_10-35-15](https://user-images.githubusercontent.com/1040784/46524889-780d9c00-c88a-11e8-9d65-f1e025370642.jpg)

Similar to #6021.

Looks like the first "parking" category is for all parking spaces (cars, bicycles, ...) whereas the second "parking" category is specifically for cars. Rename the second one to "car parking"?

**Comment by scaidermern** [comment]
Now (OsmAnd 3.2.7) the parking category shows car and bicycle parking. Is this really the intended behavior?

In my opinion this new behavior is not really helpful. You are either searching for one or the other, but never for both. Also, there is still a separate bicycle parking category. The regular parking category should *not* list bicycle parking results. Please reopen.

**Comment by scaidermern** [comment]
Thanks.

I suggest to just remove bicycle parking from the parking category. There is a separate bicycle parking category so nothing gets lost.

**Comment by crimean** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/7c485f1ec802f0cec246df2cd28386bcdb39cced

Please check it.

**Comment by scaidermern** [comment]
Now the parking categories don't show up in the category search any more. Neither the regular parking category, nor bicycle parking, nor motorcycle parking. Also no parking spaces in the results. Except if you select "Parking" from "Categories", i.e. without using the search function.

![photo_2018-12-05_10-08-00](https://user-images.githubusercontent.com/1040784/49502660-d0a2ea80-f875-11e8-809f-3fc970d9f137.jpg)

OsmAnd Nightly 3.2.0#22850d.

**Comment by crimean** [comment]
Sorry, please try 22852

**Comment by scaidermern** [comment]
Now we have the initial behavior back again. Two parking categories with the same name, the first shows all parking (bicycle, car, ...) and the second one shows car parking only.

![photo_2018-12-05_10-56-59](https://user-images.githubusercontent.com/1040784/49505681-92f59000-f87c-11e8-8adf-3355fdd73a26.jpg)

My initial suggestion was to just rename the second category to "car parking" so fix the duplicated category name.

**Comment by crimean** [comment]
You are right. Now reason of the issue was corrupted build. Please check #22854.
BTW - we decided to drop second category.

**Comment by romusprime** [comment]
unsubscribe me
