### ISSUE TITLE
Wrong routing 

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6139]
When calculating a route from Lat. 47.82409 Lon. 1.93095 (Gustave Flaubert st, Orléans) to Lat. 47.76763 Lon. 2.37530 (castle of Sully sur Loire,) OsmAnd makes a turn right and a U-turn when nothing prevents from turning left directly.
![image](https://user-images.githubusercontent.com/40493090/46534052-88843d80-c8af-11e8-8a09-939bd87ef07c.png)

This, however, does not happen with Fuel-efficient way enabled.
![image](https://user-images.githubusercontent.com/40493090/46534082-a94c9300-c8af-11e8-8c90-c8d5e1b804e3.png)

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/47050751-d1869c80-d1a1-11e8-934b-831c391a1643.png) New maps don't have that problem
