### ISSUE TITLE
Saving snapped to route GPX track to new track

### ISSUE THREAD

**Issue by qnob** [osmandapp/Osmand#6140]
Hello, 
I've been using the GPX Editor in Osman. All great. Specially, the snap to route feature for correcting my tracks. Unfortunately, I wasn't able to save this corrected track. When I save it, it goes back to the original track. 
Wouldn't be possible to save this new track to another file? Similarly to the mesure tool feature?

**Comment by qnob** [comment]
Hello,

No worries. I’ve put a sample gpx track and images with instructions on my dropbox in order to reproduce my issue.

https://www.dropbox.com/sh/pdkjgpb4o292k2z/AAAfNzHT13pMDEEXP3GSkj6ba?dl=0 <https://www.dropbox.com/sh/pdkjgpb4o292k2z/AAAfNzHT13pMDEEXP3GSkj6ba?dl=0>

Thanks a lot.

And tell me if you need something else.$
Kuno

**Comment by MadWasp79** [comment]
Closed with https://github.com/osmandapp/Osmand/commit/662dc8c8b991913f8a56349a14fd36dcf5044863
