### ISSUE TITLE
opening hours 24/7

### ISSUE THREAD

**Issue by Lukas458** [osmandapp/Osmand#6141]
Hello,

please look at this changeset for example: https://www.openstreetmap.org/changeset/62972618 there were many amenity=taxi tagged wth opening_hours and the values are "Mo-Su 00:00-00:00", according to the Wiki, in this case it's better to use "24/7" (see https://wiki.openstreetmap.org/wiki/Key:opening_hours#Values) - my question is: is that possible with OSMAnd?

**Comment by vshcherb** [comment]
It clearly looks like mistake as well it should be "Mo-Su 00:00-24:00"

**Comment by scaidermern** [comment]
> it should be "Mo-Su 00:00-24:00"

Or just "24/7".
