### ISSUE TITLE
Handling of street name abbreviations and inconsistent naming during search

### ISSUE THREAD

**Issue by cgogolin** [osmandapp/Osmand#6154]
In an attempt to help further improve OSMAND search, I would like to submit the following issue:

German street names such as "Rolandstraße", "Hautstraße", ... are often abbreviated to "Rolandstr.", "Hauptstr.". Similarly, quite often, streets are inconsistently listed as either "Rolandstraße", "Roland Straße" or "Roland-Straße", on/in different maps/road signs/address registers.

Especially when an address is copy&pasted into the OSMAND search box, or a search is initiated by sharing a location, abbreviated street names with the "str." suffix appear as inputs to the OSMANS search. Unfortunately they are not handled very well by OSMAND. A search for "Rolandstr.", for example, does yield zero results while one for "Rolandstraße" or "Rolandstr" (without the trailing ".") initiated at the same location does find the correct street. This is counter intuitive and makes the search function less useful than than it could be.

Similarly, when searching for an Address, it is impossible to know beforehand whether OSM will list that particular street under "Rolandstraße", "Rolandstr.", "Roland Straße" or "Roland-Straße". The same happens with "...-Ufer" "...-Weg" and probably a bunch of other suffixes. All these search terms should hence be "treated equally" and produce identical or at least very similar results.

Would it make sense to simply ignore all non-alpha-numeric characters when comparing the search string against street names? Or maybe at least do that after a regular search didn't yield any results?

**Comment by vshcherb** [comment]
We definitely need to drop '.' at the end of result and other special-characters like ':', ';' I think. At least we could start with dot and see if there are no negative examples

**Comment by sonora** [comment]
There is definitely room for improvement here. One thing to keep in mind is that there are also regular street names containing a dot, e.g. if a street is named after some doctor (Dr.-Smith-Straße) or professor (Prof.-xx), these must still be found.

**Comment by sonora** [comment]
@vshcherb I have looked into this and think we should apply the following immediate fix:
When using the search string (specified by the user), replace all dashes '-' by a blank ' ', and all dots '.' by nothing ''. I have tried it and that simple measure alone solves many issues explained above.

**Comment by cgogolin** [comment]
That sounds like a very good first step.

**Comment by vshcherb** [comment]
Added tests https://github.com/osmandapp/OsmAnd-resources/commit/1e698ea9e6414b8df3cec365a2d38c68df5706e2

**Comment by vshcherb** [comment]
The issue with dots is fixed https://github.com/osmandapp/Osmand/commit/8298dbdf17d9ece341fa7b790019c193e01698c5

**Comment by sonora** [comment]
Victor, have not tested yet, but looking at your commit, have you accounted for the fact that the dot may not just occur at the end of a search term, e.g. in cases like Dr.-Martin-Luther-King-Boulevard, or Mainstr. 1100

**Comment by vshcherb** [comment]
nope only last symbol, '-' is not considered as separation symbol.
In german-kind languages '-' is mutually same 'Noord Holland' = 'Noord-Holland' but it not equal to 'NoordHolland'. In other languages it could be different

**Comment by sonora** [comment]
I have tested many European languages using these 2 rules:
- replace each dot '.' by "nothing"
- replace dash '-' by a "blank".

You say these did not work too well? What were the issues?

**Comment by vshcherb** [comment]
Rolandstr. 8 - didn't work and it doesn't work if you type "Rolandstr 8"
