### ISSUE TITLE
Golf Cart Path

### ISSUE THREAD

**Issue by monikarora** [osmandapp/Osmand#6157]
Hey guys, I'm  android developer, In my app I want to add golf cart path. Please let me know open street map provides Golf cart path option.

Thanks!

**Comment by scaidermern** [comment]
Is your question about OsmAnd or OSM? If it is about OSM you are wrong here, ask it at http://help.openstreetmap.org/ instead.

**Comment by matkoniecz** [comment]
@monikarora Github issue trackers are place to report bugs (and maybe request features) in projects.

It is NOT a place to ask for help in developing your software.

Also, in places where you can ask for help (stackoverflow or similar) you should ask it in way that shows a research effort.

Also, spam is never welcomed - and you spammed this malformed question in https://github.com/osmdroid/osmdroid/issues/1165 and https://github.com/westnordost/StreetComplete/issues/1230 and https://github.com/MKergall/osmbonuspack/issues/347 and https://github.com/osmandapp/Osmand/issues/6157 and https://github.com/mapbox/mapbox-navigation-android/issues/1403 and maybe also somewhere else.
