### ISSUE TITLE
Several new issues with TTS French voice notifications

### ISSUE THREAD

**Issue by Rpnpif** [osmandapp/Osmand#6159]
With OsmAnd 3.2 and 3.2.2 from F-droid, the TTS French messages have several issues.

Examples:
"L'itinéraire" is pronounced as "el itinéraire". The apostrophe is ignored.
Before arriving to a roundabout, "Dans environ un km entrez dans le rond-point et prenez la et prenez la deuxième sortie". Note the repetition of "et prenez la".
"Dans environ un km entrez dans le rond-point dans". Note the last "dans" that is without meaning.

These issues are annoying.

Regards.

**Comment by breversa** [comment]
I'll add some more :

When getting satellite position back :
"Signal GP S restauré" (audible pause between P and S) instead of "Signal GPS restauré" (no issue with "Signal GPS perdu")
Also, since most devices now use more than just GPS (GLONASS, Beidou, and Galileo soon), it should say "Signal **satellite** perdu/restauré"


"Tournez à droite" sounds like "Tournez à [drwa:t]" (with a long [a]) instead of "Tournez à [drwat]"

**Comment by g-goessel** [comment]
The issue is also in the Play Store edition. I tried to modify the file but it is probably far from safe to merge. If a dev could guide me towards a compilation guide I could test it myself.

**Comment by sonora** [comment]
@g-goessel Look for the voice subfolder in the (active, there may be 2) osmand folder under Android/data, probably on your SD card. It will contain a folder named fr-tts, and in it a file fr_tts.js. You may duplicate the folder to e.g. fr2-tts, then play with the file therein. No need to merge anything, you can just test in OsmAnd directly. Pronunciation results vary depending on the tts engine your phone uses. If you enable the development plugin, you will find my 'Test voice prompts' in its settings, this will make testing easier. If you finally have a better fr_tts.js file, please post here.

**Comment by sonora** [comment]
@xmd5a2  Looks like we may not support arbitrary folder names like e.g. fr2-tts any more?

**Comment by Rpnpif** [comment]
@sonora Thank you. The apostrophes are doubled instead of single. Very fine !

**Comment by sonora** [comment]
I  have made the changes pointed out / suggested above, and corrected the file for you.  :)

**Comment by f6fvy** [comment]
The abbreviation "Pte" (meaning "Porte") is pronounced as "Pteu" which is rather annoying ;-)  Is there some kind of mapping which could be fixed / added ?

**Comment by Rpnpif** [comment]
@f6fvy : I think that this issue was from Openstreetmap (OSM), not OsmAnd. "Pte" is not a common short name for "Porte". It is required to OSM contributor to write the full name instead of short name in name=* attributes. So fix this in OSM to "Porte" or write the latitude and longitude here so that another contributor will fix it.

**Comment by Rpnpif** [comment]
Yes you can modify them. The tag destination is designated for the  navigation so it should be intelligible.
The error is from the highway official service.

**Comment by RunasSudo** [comment]
Re: Arbitrary folder names – Naming a folder e.g. "fr2-tts" per @sonora will now interfere with OsmAnd's detection of the TTS language. To duplicate a folder but allow OsmAnd to detect the correct language, name the folder e.g. "fr---foo-tts", where "foo" can be an identifier of your choosing.

See https://github.com/osmandapp/Osmand/blob/19a8d63ecc389c0753b411d94e69fec856bbe110/OsmAnd/src/net/osmand/plus/voice/TTSCommandPlayerImpl.java#L185

**Comment by sonora** [comment]
@RunasSudo Ah ok, I see, thanks for the info. I may have one or two tech articles about it on the website, will need to check at some point if they need an update.

But a general hint @vshcherb : I guess we should avoid as much as possible dependencies on file or folder names, and rather use file name extensions or tags in the files for identification purposes.
