### ISSUE TITLE
A lot of bright objects in dark mode at high zoom level.

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [osmandapp/Osmand#6161]
V 3.2.2

![screenshot_20181010-015123_osmand](https://user-images.githubusercontent.com/14617699/46703310-333d8880-cc2f-11e8-83e6-10eece10480e.png)
![screenshot_20181010-015129_osmand](https://user-images.githubusercontent.com/14617699/46703313-3a649680-cc2f-11e8-9da1-e4dfc7384ab8.png)
![screenshot_20181010-015135_osmand](https://user-images.githubusercontent.com/14617699/46703314-3a649680-cc2f-11e8-959d-6bbca7dbcc52.png)

**Comment by scaidermern** [comment]
The bright parking spaces have already been fixed in #6150.
