### ISSUE TITLE
Darc Design, bad colors for hight graph

### ISSUE THREAD

**Issue by quax2712** [osmandapp/OsmAnd#6162]
Here is a situation normal design compared with darc design.
In darc mode lines and values could hardly be read. As this informations are not only usefull at home, where light conditions are good, but outside, where darc mode ist much better in most situations, the hight graph is not readable.
It would be very helpfull to see hight graphics always displaying the part of track I adjust on screen, but it disappears when handy switch off and on when next routing information come.
May bee a quick help could be made by adding display hight graph to quick start button.

![normal_screenmode_hight_display_all1](https://user-images.githubusercontent.com/42236280/46730339-2600b800-cc88-11e8-8851-3012656b0f73.jpg)

![darc_screenmode_hight_display_all](https://user-images.githubusercontent.com/42236280/46730352-2ef18980-cc88-11e8-904e-192173c5c6f8.jpg)

![normal_screenmode_hight_display](https://user-images.githubusercontent.com/42236280/46731121-2ef28900-cc8a-11e8-87e7-e004a18f203b.jpg)

best regards
Rainer

**Comment by dmpr0** [comment]
Graph has changed a lot for the past year, colors are changed too.
