### ISSUE TITLE
French region name "Auvergne-Rhone-Alpes" is missing the "Auvergne" in the maps download screen

### ISSUE THREAD

**Issue by sicherist** [osmandapp/Osmand#6169]
Hi,

when I was looking to install the map of the French region "Auvergne" I couldn't find it at first, because in the Osmand-App this region is only called "Rhone-Alpes" - when it should be named "Auvergne-Rhone-Alpes". I don't know however if this Problem only exists in the German language Version or if it affects all languages.

Best regards!

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/cdb6572e6016e028895c2144d2680b0b7c23fee1
