### ISSUE TITLE
Search: some annoyances and suggestions

### ISSUE THREAD

**Issue by bugzillus** [osmandapp/Osmand#6172]
Osmand 3.22 on Lineage 14, offline maps:

While the new all-in-one search function is a giant step forward in terms of usability and speed, there is some minor annoyances:

- When clicking on the right list item while search is not completed, Osmand often jumps to the wrong destination, as it first removes the list and redraws it before accepting the tap (which then points to another entry at the same list position). This wait until the list is completely complete needs time and leads to usage errors. Can't the list be redrawn in place, so that added items are placed on the correct position?

- Sometimes, search finds no result at all at correctly spelled names, not even the capital of the country. In thi state, no search finds any result. No idea, why this happens and how it disappears, usually after a restart it works again. Sometimes, names that are visible on the map are not found via search.

- If typing a street name, it will not be found, but only POI with that name, not even when the map already shows that street name. To find a street, first the city name has to be entered (even when in that city), then ... wait ... select the city, then enter the street name, then ... wait ... the street appears. The rule that city names are not accepted as city names when entering "city street" is not obvious to users. As with above behaviour, search finds insanely many POI within larger cities, a "wrong" search uses up to half a minute.

- Maybe, a division mark (like a comma) between items could help that the search does not use time to go the wrong way not being able to distinguish if a term with two or more words or cascaded key words are meant (New York, Main Street, London main station, San Francisco bay bridge).

- Sometimes, something like a "rough" or phonetic search toggle would be helpful, if the target is spelled slightly different and cannot be found, although you know, it's there.

- In larger cities with several occurrances of the same street name or with similar town names, it would be helpful to have the postal code / zip code shown as well (or to toggle the display of zip codes), otherwise one has to go through the list trial-and-error, and that needs a lot of time.

- Sorting order of the results: POI and close results seem to have highest priority. This makes it difficult to quickly find high-priority items somewhere way down (country, region, city, district, area, street name). In these cases, toggling the sorting order to alphabetically and/or type of entry would be helpful.

- A "back" button to jump back to the result list without having to repeat the search would often be helpful.

Thanks.

**Comment by vshcherb** [comment]
This is quite a long list of everything and it is hard to say what's wrong here. So it is better to go 1 by 1 with concrete example.
1. If typing a street name, it will not be found
Can you please give an example, What's typed, where and what is the street name?
2. Maybe, a division mark (like a comma) 
There is some improvements in the new version, though please give just 1 example, so we can double check.

**Comment by bugzillus** [comment]
>     1. If typing a street name, it will not be found
>        Can you please give an example, What's typed, where and what is the street name?

Example 1: "Unter den Linden" (famous street in Berlin)

- While typing "unter", there appear five items at the top of the list that read like "area of nuclear weapon testing under water". There is no nuclear weapon testing area in Germany and no reason why these entries appear, although they dissapear (and reappear and re-disappear) again when typing on.

- If the map already shows Berlin, typing "unter den linden" brings mostly correct results, except that the first item is "Unter den Kastanien" and 200 km away.

- If the map shows another area than Berlin, typing "unter den linden" will list POI in Berlin including the term "Unter den Linden", but not streets. It appears that street names, urban districts, and parts of towns are only found in the current map, not in other active maps, but POI and city names are found in all active maps.

- When typing "unter den linden" **with** quotation marks as a term delimiter, results are completely weird: only the two items "Unter dem Storchennest" (building) and Unterloquitz (train station) show up.


Example 2: "Berlin" (famous city in Germany)

- If the map shows any other area than Berlin, then typing "berlin" will bring a list with hundreds of results of streets like "Berliner Straße" and a broad mixture of POI including "Berlin", but not the city Berlin as first entry.

- If adding a blank space at the end, "berlin ", then suddenly Berlin and other cities including the name Berlin are found. So, for advanced users the blank space seems like a trick to denote the city. This does not work on terms which include a blank space. Plus, many people are used to start with street name, then city name.


>     2. Maybe, a division mark (like a comma)
>        There is some improvements in the new version, though please give just 1 example, so we can double check.

I don't know which new version you mean (3.22?) and which improvements. Using a comma in v3.22 does not seem to change anything.

**Comment by vshcherb** [comment]
Thanks for examples, we are working on improving search that's why some weird issues appear. As I understood we will focus on 2 very main use cases:
1. "Unter den linden" without quotes (search nearby Berlin and far away)
2. "berlin" 
For these cases we will focus to not bring results too fast or if they are brought then they should be consistent.

**Comment by crimean** [comment]
Seems to be fixed already
