### ISSUE TITLE
shop=shoe_repair doesn't show POI overlay

### ISSUE THREAD

**Issue by mahdi1234** [osmandapp/Osmand#6175]
Osmand 3.2.2 with offline maps with Osmand live.

Have "POI overlay" set to "Nearest POIs".

Zoom to this shop https://www.openstreetmap.org/node/5097780341 and notice default map shows "shop" icon, but overlay shows nothing. I assume this is same for all shop=something_we_do_not_have_icon_for. I would say show default shop overlay similar to icon on basemap.

![screenshot_20181014-091610](https://user-images.githubusercontent.com/1097047/46913704-864a6f00-cf92-11e8-948b-9368990fbc3f.png)

clicking into map though it's possible to invoke details, so I assume it's some blank/transparent icon.

![screenshot_20181014-091631](https://user-images.githubusercontent.com/1097047/46913712-9cf0c600-cf92-11e8-9caf-3aee8efb8e75.png)

Having different map source without rendered shops no idea about shop exists.

**Comment by vshcherb** [comment]
I guess it should be in Custom Filter search - Shop

**Comment by xmd5a2** [comment]
https://github.com/osmandapp/OsmAnd-resources/commit/e549e2e8b8f731b061e8ccc765ff0b5d25939b30
