### ISSUE TITLE
Re: Subway problem

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#6176]
Sorry for insisting on https://github.com/osmandapp/Osmand/issues/6095 I think it was closed because theoretically it was solved

Can the problem with subway stations be solved? I know the problem was fixed for bus stops but it is not fixed for subway. I refer to the problem of subway station, not problem of colours

**Comment by vshcherb** [comment]
I concur as of today - Subways lanes contain too many stops as subway_entrance which is technically not correct.

**Comment by OpenSourceForEver** [comment]
> Subways lanes contain too many stops as subway_entrance which is technically not correct.

I have not realized that ever.

**Comment by OpenSourceForEver** [comment]
Subway stops are rendered on zoom 15 and higher diferently than 14 and lower.

![screenshot_2018-10-16-22-25-10-572_net osmand dev](https://user-images.githubusercontent.com/12786225/47046391-499a9580-d195-11e8-8268-51c674855897.png)
![screenshot_2018-10-16-22-25-05-075_net osmand dev](https://user-images.githubusercontent.com/12786225/47046414-54552a80-d195-11e8-9041-df8c41bc5f6b.png)

**Comment by OpenSourceForEver** [comment]
Does the screenshoot refers to a lot of subway routes with the same ref? I do not understand it.

**Comment by Chumva** [comment]
Yes, there were several routes with the same ref without a name - https://www.openstreetmap.org/node/266835847

Fixed with https://github.com/osmandapp/Osmand/commit/fdd52c087c570713607b84d4ec54df43db271c68

**Comment by OpenSourceForEver** [comment]
I think it is not fixed.
Osmand nightly 3.2.0#22557d
