### ISSUE TITLE
Preselect all changes in OSM editing plugin for uploading

### ISSUE THREAD

**Issue by simboel** [osmandapp/OsmAnd#6178]
When I want to upload my changes I always have to mark the _select all_ checkbox to select everything. 

Most of the time, the user will upload everything. And even if he doesn't want to upload everything, he most probably will just exclude a few things.

You could improve the upload dialog, if **every change is pre selected for upload**.

![upload-changes](https://user-images.githubusercontent.com/5895949/46971556-98c0c780-d0bc-11e8-927c-7e006d2cf3c8.png)

As you can see, I have to click the "Ihre Änderungen" (translates to "your changes") in order to select everything I want to upload.

**Comment by vshcherb** [comment]
Well not sure if it's an imporvement but this just 1 click difference
