### ISSUE TITLE
Voice instructions inaccuracy

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6184]
Start: 45.04826, 41.98454. End: 45.04088, 41.97833
OsmAnd voice instructions tell to turn left, ignoring the turn right which is before that.
![image](https://user-images.githubusercontent.com/40493090/47088250-b0b45a80-d226-11e8-9aef-7b0e2b67efc7.png)

**Comment by vshcherb** [comment]
This road has private access https://www.openstreetmap.org/way/86483622, so it is forbidden and not considered to be announced.
