### ISSUE TITLE
Tracks - Show on map button re-opens wrong sub-folder

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#6187]
Small issue I just notice, as follows:

Go to My Places - Tracks. Open a subfolder. Now tap on the Show on map button, intending to select several tracks from the expanded subfolder to be displayed. But our UI now closes the previously expanded subfolder and instead expands the next one down the list. No catastrophe, but annoying.

**Comment by sonora** [comment]
Not yet fixed by the above commits, it seems.

**Comment by sonora** [comment]
I think the underlying root cause is as follows: The first group of our ExpandableListView for GPX files is the group named 'Visible'', which we remove while `enableSelectionMode(true)`, and that exactly shifts the pattern of expanded groups by 1, creating this issue.

**Comment by sonora** [comment]
Looks like there is a second bug in the same place: When you select on or more track's check boxes  to show the gpx files on the map, these files are not marked to be shown on map after hitting the top-right check mark button.

**Comment by sonora** [comment]
The fact that for the selection mode we shift the GPX ExpandableListView's displayed groups (see post above) can also lead to inconsistencies of what is registered as "visible on map" GPX files between the screens "My Places/Tracks" and "Configure map/GPX files".

Eventually, when going back and forth, you can create this NPE: [exception.log.txt](https://github.com/osmandapp/Osmand/files/2974170/exception.log.txt)

**Comment by sonora** [comment]
This fixes it nicely by displaying the 'Visible' group also in selection mode: https://github.com/osmandapp/Osmand/commit/c10b0bc506471a14d746e8f123dde8a16833cbb3.

The only occurence left where the Issue now still appears is after the number of tracks in 'Visible' changes from zero to non-zero or vice versa, because we hide/display the group depending on whether it has children. Could change to always display the 'Visible' group even when empty, but let's see if that is desired.

**Comment by sonora** [comment]
@vshcherb This fix was much requested by users working a lot with GPX tracks, definitely worth including in the next minor release.

**Comment by vshcherb** [comment]
all the fixes in branch 3.3 will be included. We will have 2-3 more minor releases

**Comment by sonora** [comment]
I had comitted to master so far. @MadWasp79 see also my comment at https://github.com/osmandapp/Osmand/commit/a37111260e464fe3c58eca8c8a18f5f6e339c07e#commitcomment-32785636, looks like good additional work to me.

**Comment by vshcherb** [comment]
@MadWasp79 probably could transfer it.

**Comment by MadWasp79** [comment]
Will do. @sonora thank you for help.
