### ISSUE TITLE
Feature request: Apple CarPlay integration

### ISSUE THREAD

**Issue by leonid-shevtsov** [osmandapp/Osmand#6188]
Since iOS 12, you can now add support for CarPlay navigation to your app. 

(CarPlay is an iOS feature that lets an Apple iPhone use a compatible car's infotainment screen and controls as a dumb terminal. Before this fall, only Apple Maps could be used on CarPlay, but now any navigation app can implement support.)

I fully realize that this is not an easy undertaking, but on the other hand it would be a perfect match for OsmAnd's offline, open source maps. And it would also be a big competitive advantage, as so far only Google Maps, Waze, and Sygic have CarPlay support.

So it makes sense to at least get this feature out on the table.

The developer documentation is at https://developer.apple.com/documentation/carplay, and there's a good introductory article at https://blog.flitsmeister.nl/start-developing-your-navigation-app-for-carplay-6e4c6c2b4e47

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-ios/issues/158
