### ISSUE TITLE
Newest nightly builds ignore Standard map files, instead display only world overview map

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#6193]
What version of OsmAnd are you using, on what device and Android/iOS version?

Nightly builds 3.2.0#26110m released 2018-10-18, and 2.3.0#26111m released 2018-10-18

The problem did NOT exist in nightly build 3.2.0#26087m released 2018-10-17 (the last one I'd installed before finding this problem).

Samsung Galaxy S9+ and S7 Edge, running Android 8.0

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

Your offline maps.

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

Several US state standard maps (Georgia, Florida, Alabama, Mississippi), all dated September 30, 2018.

At high zoom levels, OsmAnd appears to be acting as if the Standard map files are not installed, and is instead reading only the world overview map.  (At least, that's what it looks like to me.)  See screenshots.

If I reinstall 26087 over 26110/26111, the problem goes away, so it appears to be the app and not the map files.

Good older build:
![screenshot_osmand build26087_2018-10-17](https://user-images.githubusercontent.com/11140831/47182430-651bb280-d2f3-11e8-82a6-2956c972d4c5.jpg)

Bad new build:
![screenshot_osmand build26111_2018-10-18](https://user-images.githubusercontent.com/11140831/47182422-5e8d3b00-d2f3-11e8-9163-34db6a9c21cb.jpg)

**Comment by franco999** [comment]
Me too..

**Comment by vshcherb** [comment]
My bad - fixed

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-core/commit/48e0077fa60ff947ff058a337c15aac6d6dae762

**Comment by jfburke3** [comment]
Thanks @vshcherb .  Looks good in build 26121.
