### ISSUE TITLE
Cross region public transport routes are not shown completely.

### ISSUE THREAD

**Issue by miklcct** [osmandapp/Osmand#6194]
When browsing public transport routes in the map, the routes which cross map boundaries are not shown completely.

For example, consider the following bus route, with Kaliningrad and Lithuania map loaded into the app:

https://www.openstreetmap.org/relation/2717061

The app can't show the route completely no matter which stop I choose.

**Comment by CJTmmr** [comment]
Also in The Netherlands when a bus route goes into anotter province. Probable cause is merging Netherlands map from the province maps.

**Comment by vshcherb** [comment]
This is related to the fact how we cut the maps and indeed we can try to preserve it.

**Comment by vshcherb** [comment]
should be fixed now
