### ISSUE TITLE
Seamark colours and topmark wrong

### ISSUE THREAD

**Issue by mist** [osmandapp/Osmand#6205]
As we were sailing through the IJsselmeer I realized at least one wrongly rendered lateral:
[MA 3-MW 2](https://www.openstreetmap.org/node/1333851710#layers=D)

This is a two-colour-lateral, green on the top and red on the bottom. Additionally there is a green triangle on top. In the app it is rendered as red lateral with green sphere on the top.

And as I look at the map I see the [VF 2-MA 1](https://www.openstreetmap.org/node/1333826580#layers=D) is wrong aswell, as it is red in the app but green-red as the data says.

The edit-poi screen shows the correct data.

I'm using f-droid OsmAnd (though I bought it earlier), `OsmAnd~ 3.2.2`, Semarks map from 2018-10-03 and 2018-10-17.

**Comment by mist** [comment]
![photo5940359036941741383](https://user-images.githubusercontent.com/85930/47293585-ce106c80-d60a-11e8-8f5c-93e4b3d53e91.jpg)
![photo5940359036941741382](https://user-images.githubusercontent.com/85930/47293595-d23c8a00-d60a-11e8-9681-20aca53bfc1f.jpg)
![photo5940359036941741386](https://user-images.githubusercontent.com/85930/47293598-d5d01100-d60a-11e8-9524-189b8576e601.jpg)

**Comment by vshcherb** [comment]
Looks indeed strange. I could recommend as part of technical investigation to run ./inspector.sh (part of mapcreator) and export obf to osm and investigate in JOSM. 
Obviously it is possible the data was changed recently.

**Comment by mist** [comment]
The data wasn't changed recently as you can see in the osm.org data (last change two years ago).
If I get it up running I'll try inspector later this week.

**Comment by xmd5a2** [comment]
Not all rare variants are supported.
MA 3-MW 2 shape is fixed by https://github.com/osmandapp/OsmAnd-resources/commit/d5d05f23364ef3822dcb365b193dfc0dedb32a4c

**Comment by mist** [comment]
Would it be possible for OsmAnd to show when it isn't able to parse and draw the buoys (e.g. as an blue checkered buoy)? It is very confusing when looking at the map and not finding the buoy you see there with your binocular, so knowing the image is wrong can help a lot there.

**Comment by xmd5a2** [comment]
@mist yes, that makes sense. I've done that for lateral buoys https://github.com/osmandapp/OsmAnd-resources/commit/10e4c3e91635e4e914ac8a4a58b358376f051b47

**Comment by xmd5a2** [comment]
https://github.com/osmandapp/OsmAnd-resources/commit/3ffebdfecd171d185905f997edcabf4f5fd0a57e
https://github.com/osmandapp/OsmAnd-resources/commit/dd6c318ee7ff96b0766f3f1fdd10bf94ffb6bbbd
