### ISSUE TITLE
Review increase radius search: 100km -> 400km -> 1600 km ?

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#6208]
Issue is as follows: When I am in Europe and search for a smaller town in North America,  it takes all of 30 sec to display that no result was found within 100 km. Then I tap 'increase search radius', wait another 30sec for the same 'nothing' result in the 200 km range, then again for the 400. It takes several minutes to finally see the result.

It seems the entire index is searched everytime anyway, and just the results are filtered? So couldn't we just display ALL search results after one round, and maybe in the list introduce colored headline bars (or collapsed sections) to show which entries are >100km, >200km etc. away?

**Comment by vshcherb** [comment]
The algorithm you described wouldn't work, though I'm confused that we are increasing just by 100km that might need to be checked

**Comment by vshcherb** [comment]
No complains so far
