### ISSUE TITLE
Finland map broken

### ISSUE THREAD

**Issue by Zahnstocher** [osmandapp/Osmand#6211]
Finland map is not displayed correctly.
Tested with latest OsmAnd nightly build and OsmAnd nigthly from August.
So it seems that the Finland map is broken.
See:
https://groups.google.com/forum/#!topic/osmand/o7veC76bzQY

**Comment by xmd5a2** [comment]
Maps were regenerated. Please check.

**Comment by Zahnstocher** [comment]
Still broken.
For example, the street "Suezintie" does not exist:
https://www.openstreetmap.org/?mlat=63.52011&mlon=25.85101#map=18/63.52011/25.85101

**Comment by hakuchi** [comment]
if I download the Standard Finland map, the northern part is missing(Northern Ostrobothnia/Lapland).
If I download only the map region "Northern Ostrobothnia", the street "Suezintie" is displayed correct and also the city Oulu from first screenshot in Google Groups.

@xmd5a2: Maybe the subfolder in Northern Finland is the problem. I think that these two files get not detected correct for the download of the Standard map.

**Comment by Zahnstocher** [comment]
New Map does not have this issue.
