### ISSUE TITLE
Fix UI alignment for RTL languages

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6214]
UIs for languages that are read from right-to-left (RTL) should be mirrored.
![image](https://user-images.githubusercontent.com/40493090/47364669-8b21c800-d6e2-11e8-8d85-36cb000eaa6c.png)

**Comment by vshcherb** [comment]
It is a known issue we will be working on it. And no it won't be mirrored, it will be different UI.
