### ISSUE TITLE
Search: Show category results first?

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#6218]
I'm wondering whether matching categories should be displayed first in the search.

Example: I'm searching for "Biergarten" and the first three pages contain POIs. The "Biergarten" category is not displayed until page 4.

1st page:
![photo_2018-10-24_08-50-41](https://user-images.githubusercontent.com/1040784/47411874-5c4f3480-d76a-11e8-9958-27fb6f2a1115.jpg)

4th page:
![photo_2018-10-24_08-50-37](https://user-images.githubusercontent.com/1040784/47411882-6113e880-d76a-11e8-84ec-1739e8ae99f1.jpg)

Also the sorting looks weird, the first match has a distance of 1.39 km while the result directly after the matching category is only 304 m away. But this is a different issue.

**Comment by vshcherb** [comment]
Yes fixed, it was a bug
