### ISSUE TITLE
Freeze when selecting public transport element and world overview map is active

### ISSUE THREAD

**Issue by adrien-n** [osmandapp/Osmand#6219]
Hi,

Using OsmAnd~ 3.2.2 from F-Droid (but this has been an issue for at least a year or so but finding a good reproducer wasn't trivial).
Device is Oneplus 3T. ROM is Oneplus' latest.
Reproduced on another Oneplus 3T with a recent LineageOS.

Steps to reproduce:
- enable only the world overview map,
- display Paris, France on the map,
- zoom in and select a public transport element,
- observe that osmand has frozen.

Note that this also happens when there are other maps used in addition to the world overview one but having only world overview makes for a better reproducer.

My current hypothesis is that the world overview map does not have the details that the public transport view queries (e.g. public transport lines) and that this induces a freeze one way or another.

**Comment by MadWasp79** [comment]
Fixed with https://github.com/osmandapp/Osmand/pull/6443/commits/f7d3e72fb113f346e11e420bb591fbcb752bbc30
