### ISSUE TITLE
Navigation inaccuracy

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6235]
Start: Sedona, AZ 
End: San Diego, CA
OsmAnd makes a u-turn instead of turning right directly. 
![image](https://user-images.githubusercontent.com/40493090/47660358-7e4c1b00-db9f-11e8-8786-91245b96409e.png)

**Comment by scaidermern** [comment]
It is the same here: https://www.openstreetmap.org/directions?engine=graphhopper_car&route=33.77106%2C-112.13048%3B33.76965%2C-112.13341#map=18/33.77008/-112.13095

Although I don't understand why. There is no turn restriction.

**Comment by Zahnstocher** [comment]
It was a map error.
New OsmAnd map does not have this issue.
