### ISSUE TITLE
bug report: pedestrian routing with altitude correction and custom routing.xml: Wrong time displayed

### ISSUE THREAD

**Issue by christofkn** [osmandapp/Osmand#6241]
There seems to be a bug in the displayed routing time for pedestrian routing with altitude correction in Osmand 3.2.2 of the playstore:
I use a routing.xml with pedestrian altitude correction according to swiss alpine club:
Extra time for 400m upwards: 1 hour, for 800 m downwards also 1 hour.
Code: 
		
		<way attribute="obstacle_srtm_alt_speed">
			<if param="height_obstacles">
				<gt value1="0" value2=":incline">
					<select value="9"/>
				</gt>
				<select value="4.5"/>
			</if>
		</way>

There is no change in the displayed routing time compared to the default routing.xml (as long, as the route is the same).
Sometimes the route changes, therefore I know, that I copied customized routing.xml to the right location and it is really used by Osmand.

Actually, if I take 
		
		<way attribute="obstacle_srtm_alt_speed">
			<if param="height_obstacles">
				<select value="0"/>
			</if>
		</way>
I still get the same routing-time displayed (if the route stayes the same).
A bug in Osmand code, isn't it?
I activated "Höhendaten berücksichtigen" of course.

**Comment by christofkn** [comment]
The routing code is not displayed above. Here it is:
[routing_code.txt](https://github.com/osmandapp/Osmand/files/2537821/routing_code.txt)

**Comment by sonora** [comment]
I think it is like this: The parametrization in routing.xml is used by the routing engine to determine the route, but it is not used to calculate the human travel time a found route is then predicted to take. For pedestrian routing with 'Use elevation data' this is done in the route preparation code, and uses Naismith's rule (ascent correction only, 1 extra hour for every 600m).
