### ISSUE TITLE
Object properties window is not automatically removed when moving a map.

### ISSUE THREAD

**Issue by Prusaker** [osmandapp/Osmand#6244]
In OsmAnd 3.2.2 and earlier, the pop-up window of the properties of the selected object was automatically removed if the map was moved. In OsmAnd 3.2.3, the window always remains on the screen, and it has to be specially removed. It is very uncomfortable.

Is it possible to do as it was in previous versions?

Thanks in advance.

**Comment by LLlypuk82** [comment]
I am joining to the issue. It's makes me need for additional actions.

**Comment by sonora** [comment]
A simple tap in the map will still close it. What was changed is the ability to leave the marker visible on the map while panning or zooming as this is often needed to check out surroundings.

**Comment by vshcherb** [comment]
Here we will be gathering feedback for 3.3

**Comment by max-klaus** [comment]
Fixed
