### ISSUE TITLE
wrong rounting OsmAnd (offline) Navigation service

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [osmandapp/Osmand#6245]
![screenshot_20181102-051613_osmand](https://user-images.githubusercontent.com/14617699/47890115-7bcb1900-de5e-11e8-8959-f991c035986c.png)
OsmAnd (offline) Navigation service

From: 60.00502, 30.32685
To: 60.00185, 30.32810

[osm graphhopper_car ](https://www.openstreetmap.org/directions?engine=graphhopper_car&route=60.00502%2C30.32685%3B60.00185%2C30.32810#map=18/60.00345/30.32764)
and
[osm osrm_car ](https://www.openstreetmap.org/directions?engine=osrm_car&route=60.00502%2C30.32685%3B60.00185%2C30.32810#map=18/60.00345/30.32764)
shows correct routing.

**Comment by scaidermern** [comment]
There are many turn restrictions at this intersection. One of them is wrong (I'm not gonna fix it immediately to investiage this issue): https://www.openstreetmap.org/relation/4270227. This is a no_u_turn where members from and to are the same ways. OsmAnd should ignore such a broken restriction.

**Comment by c-e-p-x-u-o** [comment]
It's correct restriction. Only straight from this direction.
Moreover, separation this path will be correct:
![screenshot_20181102-160245_osmand](https://user-images.githubusercontent.com/14617699/47916922-e01ac680-deb8-11e8-96fe-918d52672905.png)
![screenshot_20181102-160330_osmand](https://user-images.githubusercontent.com/14617699/47916923-e0b35d00-deb8-11e8-9ddd-540085733983.png)

**Comment by scaidermern** [comment]
Oh you are right. In case of a `u_turn` `to` and `from` are allowed to be identical.

So in this case I'm unsure why OsmAnd fails to find the shorter route.

**Comment by c-e-p-x-u-o** [comment]
Please reopen this bug. It present in OsmAnd~ 3.2.5

**Comment by c-e-p-x-u-o** [comment]
sometimes it shows correct (straight) routing
sometimes it shows wrong routing (as on the first picture)

**Comment by c-e-p-x-u-o** [comment]
I don't know what it depends on.
