### ISSUE TITLE
iOS Wikimedia photos/Wikipedia articles integration and external links

### ISSUE THREAD

**Issue by krosola** [osmandapp/Osmand#6250]
Hello,

This is an issue/request that I find confusing. I am really interested in learning more information about landmarks, sights and monuments. When one taps on a POI, different results are presented. A lot of POI have no external links whatsoever. In other cases, Wikimedia photo urls are present but not clickable. When one visits the website, one is shown wikipedia articles where the POI is listed and an external link to a national database website which talks about the POI. This is very useful and would be ideal to always include within the app if available. I also believe it would be better to swap the Wikimedia photo url, with the wikipedia article that lists the POI, although I noticed the article does not always directly concern the POI. In yet another case, the POI doesn't include any external links, but can be found listed in a Wikipedia article but without any photo, thus no Wikimedia photo url exits.

Strangely enough, it appears that there are cases for different monuments where the app does after all include direct external clickable links to the national database website I previously referred to. My question is, why is this external link present in only certain cases?

It appears to me that that the ideal scenario with relevant external links can and does exist within the app, but I wish it would always be the case.

Best regards

**Comment by pebogufi** [comment]
Please give some axamples.

**Comment by krosola** [comment]
Here are some random examples to help demonstrate the different cases.

First case, no information:
![img_0122](https://user-images.githubusercontent.com/6968255/47953162-e15ff800-df79-11e8-955e-1a624f7534d1.PNG)
But Wikimedia has an image for this POI here, 
![](https://commons.wikimedia.org/wiki/File:Heist-op-den-Berg_Swane_Pomp.JPG) and within it links to a national directory that talks more about this POI here, https://inventaris.onroerenderfgoed.be/erfgoedobjecten/2855.

Second case, similar to first. No information but Wikimedia does have a photo link, and it exists in the national directory but the Wikipedia article linked does not talk specifically about the POI. This is common.
![img_0119](https://user-images.githubusercontent.com/6968255/47953430-e45ce780-df7d-11e8-9481-38c963c58c1b.PNG)
Wikipedia indirect article, [](https://nl.wikipedia.org/wiki/Lijst_van_onroerend_erfgoed_in_Boechout)
National directory link, [](https://inventaris.onroerenderfgoed.be/erfgoedobjecten/12562)

Third case, Wikimedia photo link, but not the direct wikipedia article link here.
![img_0123](https://user-images.githubusercontent.com/6968255/47953189-64814e00-df7a-11e8-930e-b005451a9ce8.PNG)
The Wikimedia link,[]( https://commons.wikimedia.org/wiki/File:Tomphamont.jpg)
Wikipedia article link,[]( https://nl.wikipedia.org/wiki/De_Tomp)
Ideally, the national directory [](http://www.molenechos.org/molen.php?AdvSearch=1211) here would be also included. It is also linked within the Wikimedia page.

Fourth case, wrong link.
![img_0121](https://user-images.githubusercontent.com/6968255/47953252-77485280-df7b-11e8-9085-0947910ecaf1.PNG)
The link suggested is not relevant to the POI. Additionally the Wikimedia photo link is used, but I found an English Wikipedia article [](https://en.wikipedia.org/wiki/Sorghvliedt_Castle). Finally, the national directory link [](https://inventaris.onroerenderfgoed.be/erfgoedobjecten/11463), which again is referred to within Wikimedia should be listed.

Fifth case, correct link but no Wikimedia/Wikipedia reference:
![img_0120](https://user-images.githubusercontent.com/6968255/47953352-b1662400-df7c-11e8-9056-6de7fb2e95ed.PNG)
The link here is very relevant, but I'm not sure if it could be found for all the relevant POIs.

Finally, ideal case with relevant external link to national directory, although no Wikipedia/Wikipedia link exists.
![img_0117](https://user-images.githubusercontent.com/6968255/47953482-8ed50a80-df7e-11e8-9c74-662f1c8ce63c.PNG)

I'm sorry if this may be confusing. I am just trying to help understand how to keep the information consistent.

**Comment by vshcherb** [comment]
Moved to https://github.com/osmandapp/OsmAnd-ios/issues/156
