### ISSUE TITLE
Favorite color menu off-screen

### ISSUE THREAD

**Issue by IgorEliezer** [osmandapp/OsmAnd#6251]
OsmAnd 3.2.3 Unlimited, Android

The first option of the color menu in Favorites (default or custom folder) is half off-screen.

![image](https://user-images.githubusercontent.com/4673289/47948297-77aa0480-df0d-11e8-91e0-cd99970aa2ac.png)

**Comment by IgorEliezer** [comment]
> Have you scrolled the selection all the way down?

I have, I still can't select the "Red" option.

**Comment by sonora** [comment]
Yeah, and there is even a 'dark-yellow', our default, above that. Must depend on screen resolution, though, I canot reproduce on any of my devices. Interim workaround may be to use portrait orientation.
