### ISSUE TITLE
Please use only nb language code for Norwegian Bokmål

### ISSUE THREAD

**Issue by petterreinholdtsen** [osmandapp/Osmand#6252]
On Weblate, Norwegian Bokmål appear twice, with the two language codes nb and nb_NO, see https://hosted.weblate.org/projects/osmand/#languages .  These two language codes are for the same language, and those of us translating to Norwegian Bokmål recommend the 'nb' code is used whenever possible.  Please consider merging the nb_NO translations into the nb translation and removing the nb_NO translation from the list of translation options for osmand.

**Comment by sonora** [comment]
Should be fixed via https://github.com/osmandapp/Osmand/commit/168740b72e2ffaa1597e6a47daaf8d8fcc69115f, thanks for reporting.

**Comment by petterreinholdtsen** [comment]
[Hardy]
> Should be fixed via
> https://github.com/osmandapp/Osmand/commit/168740b72e2ffaa1597e6a47daaf8d8fcc69115f,
> thanks for reporting.

Very good.  Thank you very much Any idea when it will take effect on
<URL: https://hosted.weblate.org/projects/osmand/#languages >?

--
Happy hacking
Petter Reinholdtsen

**Comment by sonora** [comment]
Not quite sure myself, I think the next replication with Weblate should pick it up automatically without further intervention, I will monitor until tomorrow or so.
