### ISSUE TITLE
iOS, no audio navigation when phone locked or app running in background

### ISSUE THREAD

**Issue by krosola** [osmandapp/Osmand#6254]
Hello,

I've given Osmand a go for the first time today and I discovered what I consider a bug. The voice navigation on an iPhone x only works when the app is active and the screen is on. This is unfortunate as it costs a lot of battery life and is restricts the use of the smartphone for other uses. I wished to listen to the audio navigation while the phone was locked in my pocket, but I had to keep the screen on to receive audio navigation.

I hope you can update the app with this functionality working soon as I find it's of great importance. 

Regards

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-ios/issues/157
