### ISSUE TITLE
Is more complex opening_hours valid when generated by OSMand?

### ISSUE THREAD

**Issue by mahdi1234** [osmandapp/Osmand#6255]
OSMand live 3.2.2 from GP.

Have edited opening hours and uploaded.

![screenshot_20181105-091627](https://user-images.githubusercontent.com/1097047/47995174-c239a580-e0f4-11e8-9377-e4d5344aa29a.png)

Both validators below complain that's generated code is invalid
`Mo, We-Fr 07:30-11:30; Mo-Fr 12:30-15:00`

altering it to below shows in latter one as well (but both show opening at 12:30 ignoring morning part)
`Mo,We-Fr 07:30-11:30; Mo-Fr 12:30-15:00`

http://openingh.openstreetmap.de/evaluation_tool/?setLng=en

http://projets.pavie.info/yohours/

Opened in JOSM which complains as well and created anew in JOSM; new code passed the validators

`Mo-Fr 07:30-11:30,12:30-15:00; Tu 12:30-15:00`

Here's node history - https://www.openstreetmap.org/node/5620418279/history

I'm not sure whether OSMand is incorrect or the validators are wrong.

**Comment by scaidermern** [comment]
> Both validators below complain that's generated code is invalid
> `Mo, We-Fr 07:30-11:30; Mo-Fr 12:30-15:00`

No. Both http://openingh.openstreetmap.de/evaluation_tool/?setLng=en and http://projets.pavie.info/yohours/ accept it. http://projets.pavie.info only tells that it "is valid, but too complex to be shown here".

**Comment by mahdi1234** [comment]
@scaidermern they accept it but show only afternoon time, they don't parse morning part. Same does OSMand it shows at the night it will be open at 12:30 which is incorrect.

**Comment by scaidermern** [comment]
Sorry, you are right. Looks like the format is valid but the meaning is wrong. https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification states:

> if multiple rules match a specific date then the last rule will overwrite all previous ones

Which means that `Mo-Fr 12:30-15:00` completely overwrites `Mo, We-Fr 07:30-11:30`. If this opening_hours value has been generated by OsmAnd then this is clearly a bug.

**Comment by mahdi1234** [comment]
Yes,
https://www.openstreetmap.org/api/0.6/changeset/64188835/download is generated by Osmand https://www.openstreetmap.org/api/0.6/changeset/64188835

**Comment by vshcherb** [comment]
The issue is not clear, you can generate all combinations in OsmAnd and this is one as well.
```Mo-Fr 07:30-11:30,12:30-15:00; Tu 12:30-15:00```
If you click "Add time span" it will add a span with comma separated and if you click "Add opening hours" it will be ";" separated. So you have control and you can always validated in Advanced tab. OsmAnd doesn't have complete validation, so you need to know the rules unfortunately.
