### ISSUE TITLE
Integrate take photo with mapillary

### ISSUE THREAD

**Issue by QuestionsForThose** [osmandapp/Osmand#6261]
Pressing the Start widget allows user to take audio, video or photo note consequently creating an icon on the map.
When user selects this icon the photo note is displayed. From this screen I would like to be able to send the photo note to Mapilliary - therefore creating an online picture. Can this be done please.

**Comment by vshcherb** [comment]
Today Mapillary API suggests to create a sequence of the photos (not single), so we will discuss about this integration in future.

**Comment by Bibi56** [comment]
Currently the app does that. Why is the ticket still open?
https://osmand.net/features/mapillary

**Comment by QuestionsForThose** [comment]
THanks
