### ISSUE TITLE
on map missing, please offer download or actvate

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#6266]
when tapping on a white area (no map downloaded), 
sometimes I get a menu which offers a download of the map,
but sometimes this is missing. Instead I get an info "No adress determinated". see screenshot
Especially after the new splitting of maps (in europe) it would be helpful, to get a menu with option to download the map or activate the map (if it was only deactivated).  See https://github.com/osmandapp/Osmand/issues/5623

Version: 3.2.0#26245
Thanks, Peter

![unknownadress](https://user-images.githubusercontent.com/18628183/48303170-3c0fcb80-e507-11e8-80bc-44110e42ea6e.png)

**Comment by vshcherb** [comment]
Needs to be checked, we will try to reproduce it  and fix

**Comment by pebogufi** [comment]
Activate instead of download works now (if map is deactivated).
So I am happy with it and close it.
