### ISSUE TITLE
Add support for routing on reversible roads & lanes utilizing a tagged schedule

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#6267]
Please consider adding support for routing on reversible roads & lanes using a schedule included in an appropriate tagging mechanism.  (Note:  this partially relates to my earlier Github issues #6147 and #6148 regarding toll roads.)

Real-world use cases:

* I 75 & I 575 Express Lanes north of Atlanta (aka the "Northwest Corridor"):
https://en.wikipedia.org/wiki/Northwest_Corridor_Project
http://www.dot.ga.gov/DS/GEL/NWC

* I 75 South Metro Express Lanes south of Atlanta:
http://www.peachpass.com/where-can-i-use-peach-pass/i-75-south-metro-express-lanes/

* the Lee Roy Selmon Crosstown Expressway elevated express lanes (separate from the dedicated one-way lanes of the expressway) in Tampa:
https://en.wikipedia.org/wiki/Lee_Roy_Selmon_Expressway

I'm sure there are more somewhere else in the world, too.

For now, I've been adding an opening_hours tag on the barrier nodes on the entrance lanes (and on the entrance lanes themselves) for the Atlanta express roads, mainly so that the information gets captured and is available in OSM.  I haven't touched this on the Selmon Expressway because it has a more complex reversal schedule.  I have specifically avoided putting opening_hours on barrier nodes on the exit lanes, though, because you can exit even after the barriers on the entrance lanes go down.

Another way to approach this might be to utilize route relations.  However, this is significantly more complex.

I've started a discussion on the OSM Tagging mailing list, which I invite everyone to join in on:

https://lists.openstreetmap.org/pipermail/tagging/2018-November/040753.html

One person has brought up using conditional hours tagging for lanes, which might be easier to implement in software than "opening_hours" tags on route relations.

**Comment by RicozOSM** [comment]
One possibility is outlined in #6271.. sorry didn't see that you created this issue, should merge them somehow.

**Comment by jfburke3** [comment]
No prob, @RicozOSM .  I'm glad to see someone else is also following up with nav app devs on this.

I don't think they can merge Github issues; they'd have to just close one out and use the other to track the work.

**Comment by vshcherb** [comment]
Combined with #6271
