### ISSUE TITLE
Rendering of hiking symbols broken in November maps

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#6268]
After updating to November maps the rendering of hiking symbols got broken. I confirmed this with a second device. October maps were fine, November maps don't display symbols of hiking routes any longer.

October maps:
![photo_2018-11-11_13-44-59](https://user-images.githubusercontent.com/1040784/48313105-1393da00-e5b8-11e8-9b1b-9fc2d5a5a8ec.jpg)

November maps:
![photo_2018-11-11_13-44-55](https://user-images.githubusercontent.com/1040784/48313123-332b0280-e5b8-11e8-86c5-e50d4ac0684a.jpg)

OsmAnd 3.2.4.

**Comment by mahdi1234** [comment]
I have it repro with Nov maps Osmand 3.2.5 btw it's here - https://www.openstreetmap.org/node/5155474237#map=17/50.65624/11.21841 - took me some time to find it :)

Just a wild guess it may have something do with https://github.com/osmandapp/Osmand/issues/5888 in particular https://github.com/osmandapp/Osmand/issues/5888#issuecomment-431949106

```
I've got a comment from @xmd5a2 that 2. and 3. are already fixed and will be available in new maps next month.
1 is mentioned in internal tracker and it is a long running issue.

```
and it's not fixed on Czech maps , still showing all symbols not only hiking when only hiking selected ... but colors are still shown unlike here in Germany.

**Comment by scaidermern** [comment]
Sorry, I didn't mention the position because I thought this is a global issue. However it looks like you are right. Hiking symbol rendering broke for Germany but not for Czechia:

![photo_2018-11-11_19-52-56](https://user-images.githubusercontent.com/1040784/48317008-823e5b00-e5eb-11e8-943a-b69eb07972b3.jpg)

Top left is Germany, bottom right is Czech Republic.

geo:50.902042,14.384807?z=14
https://osmand.net/go?lat=50.902042&lon=14.384807&z=14

**Comment by scaidermern** [comment]
@vshcherb @xmd5a2 Please consider fixing this *before* December maps will get generated. This is a serious regression for any hiker using OsmAnd.

**Comment by xmd5a2** [comment]
Fixed and checked https://github.com/osmandapp/OsmAnd-tools/commit/e22882488a5b38d05b01f4b307c1b33cf2b0c01c

**Comment by scaidermern** [comment]
Great, thanks.
