### ISSUE TITLE
support for oneway=reversible and conditional acces

### ISSUE THREAD

**Issue by RicozOSM** [osmandapp/Osmand#6271]
There is a discussion in the ml how to tag roads with reversible traffic according to some schedule. 

One of the possible ways to tag those would be
```
oneway=reversible
oneway:conditional= yes  @ (09:00-17:00); -1 @ (17:01-8:59)
```

Here "oneway=reversible" is supposed to be the fallback for routers that don't support conditional restrictions yet (https://github.com/osmandapp/Osmand/issues/1794) and should mean don't route there - but would it work that way in osmand?

https://wiki.openstreetmap.org/wiki/Tag:oneway%3Dreversible

Better ideas for a fallback for routers that don't know conditional restrictions?

**Comment by vshcherb** [comment]
I would say always make backward compatible especially what's critical for navigation. So the proposed change won't work without changes.
It is better to use:
oneway=1, oneway=-1, oneway=yes.

And make completely different tag 
```
oneway:reversible=yes
oneway:reversible:conditional=...
```

**Comment by RicozOSM** [comment]
Don't see how oneway=1, oneway=-1, oneway=yes could work for reversible highways - the router would still send the cars there and it would be the wrong direction half of the time?

It needs some celver way to prevent the router from sending there any cars unless it understands ```oneway:reversible:conditional```.
My hope was that ```oneway=reversible``` would do that trick - if the router doesn't understand the value of ```oneway=reversible``` it should not send any cars there?

Otherwise a rather unwieldy combination like
```
access=no
access:conditional=yes @ (09:00-17:00); yes @ (17:01-8:59)
oneway:conditional= yes  @ (09:00-17:00); -1 @ (17:01-8:59)
```
would be needed: first two lines to make (reasonably) sure that routers don't send there anyone unless they understand time conditional restrictions and last line with the actual logic.

**Comment by RicozOSM** [comment]
On Sun, Nov 25, 2018 at 03:21:29PM -0800, vshcherb wrote:
> oneway=reversible means half-time it will be closed for one direction and half-time for another direction?

imo it does not say whether half-time or any other schedule - it says this
road is oneway in unpredictable direction and unpredictable times. So routers
that do not understand this should just avoid this way.

The interesting question, what will OsmAnd do if it sees a oneway=reversible?

The actual direction and schedule could be specified with oneway:conditional
but that was a recent change of mine to the wiki.

**Comment by vshcherb** [comment]
Today it will interpret as oneway=yes.  
For us it should be an easy fix cause we will introduce other tags conversion:
```
oneway=reversible -> access = no 
```
Like here https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml#L70

**Comment by RicozOSM** [comment]
> Today it will interpret as oneway=yes.  

not good.

> For us it should be an easy fix cause we will introduce other tags conversion:
> oneway=reversible -> access = no 

would be important to have soon to avoid sending cars in the wrong direction in express lanes.

Later it can be refined when support for conditional-time restrictions is on the horizon. What isn't quite ideal about the ```oneway=reversible -> access = no``` conversion is that it won't work in a combination like

```
oneway=reversible
oneway:conditional= yes  @ (09:00-17:00); -1 @ (17:01-8:59)
```

because the first line would be now ```access=no``` which afaics won't be overriden by the second statement. However for now it is more important to make sure OsmAnd doesn't send cars wrong way and there is plenty of time to worry about this detail later.

> Like here https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml#L70

so you just recreate maps and it will become effective even for somewhat older 
versions of OsmAnd? That's good.

**Comment by SviMik** [comment]
I'll add my own example too.
https://www.openstreetmap.org/way/49923023
[code]oneway=reversible
oneway:conditional=yes @ (12:00-05:50); -1 @ (06:00-11:50)[/code]

**Comment by vshcherb** [comment]
Hopefully the work on this issue will fix https://www.openstreetmap.org/way/258043188 from #1329

**Comment by vshcherb** [comment]
Changes already merged into master
Pull requests to 3.4
https://github.com/osmandapp/OsmAnd-core/pull/89/files
https://github.com/osmandapp/Osmand/pull/7302/files

**Comment by vshcherb** [comment]
Tested.
