### ISSUE TITLE
Blagdon Lake, Somerset (~Lat 51.335 Lon -2.7) missing from UK roads only 1 Nov

### ISSUE THREAD

**Issue by mikehgentry** [osmandapp/OsmAnd#6272]
It's present in the full maps, but not roads only. Nearby Chew Valley lake is unaffected.

https://osmand.net/go.html?lat=51.335&lon=-2.7

Possibly a duplicate of #5980

Osmand+ 3.2.5, Android 8.1.0

**Comment by mikehgentry** [comment]
Cheddar Reservoir is also missing on roads only, present on full maps.

https://osmand.net/go.html?lat=51.28&lon=-2.8

**Comment by vshcherb** [comment]
Yes, road only maps are cutting small polygons to make the map as small as possible

**Comment by mikehgentry** [comment]
Ok, thanks - I guess with space constraints it's always going to be a trade-off.

I'll leave you to close this if you want, since you've tagged it.

**Comment by mikehgentry** [comment]
Closing on the assumption that this is working as intended
