### ISSUE TITLE
No visible keyboard in search after manually switching screen off and on

### ISSUE THREAD

**Issue by mikehgentry** [osmandapp/OsmAnd#6273]
1) Open Osmand

2) Hit the phone's power button to switch screen off

3) Hit again to switch screen back on

4) Menu -> Search won't produce a keyboard (if you hit the 'back' arrow to exit search, you'll see it briefly)

Tapping the home button gets you to the lock screen. When you exit the lock screen you can briefly see the keyboard. If you now re-enter Osmand, it'll work as expected.

Osmand 3.2.5, Android 8.1.0 (Moto g5)

**Comment by dthgeek** [comment]
I also have this problem on a Moto G5 Plus running Android 8.1.0. However, I wanted to point out that I can use the keyboard when I'm adding a GPX waypoint after the screen has been turned on and off but I still can't uses the keyboard to search for a POI under the same circumstances.

**Comment by mikehgentry** [comment]
Seems to be fixed

**Comment by mikehgentry** [comment]
Seems to be broken again as of OsmAnd+ 3.4.8, Moto G5, Android 8.1.0

**Comment by AntiSol** [comment]
I'm not sure whether I should file this as a separate issue or as part of this one. Let me know if you'd prefer it to be a separate issue.

For me, on LineageOS 14 / OsmAnd 3.7.4 :
1. Start OsmAnd
2. Press power button to turn off / lock the screen
3. Press power again to turn screen back on. OsmAnd will be in foreground.
4. Perform any action that tries to pop up the keyboard (search, add a favourite and select the 'name' field, etc)

For me, this creates a fun infinite loop of the keyboard trying to show, which gets overridden by the lock screen, which is overridden by OsmAnd and the keyboard, then the lock screen, etc etc. The only solutions I've found are to either restart the phone or to long-press the back button to kill the keyboard.

video demo: https://antisol.org/osmand_loop.mp4

**Comment by mikehgentry** [comment]
I don't have this phone any more, so closing as indeterminate.
