### ISSUE TITLE
Wikivoyage - Search for Bunnik incorrect

### ISSUE THREAD

**Issue by ArjanOnwezen** [osmandapp/Osmand#6275]
- Open Travel Guide
- Search for Bunnik
- Click on Bunnik
- Bayeux is shown

Should have been solved in 3.2, but this is not the case
https://github.com/osmandapp/Osmand/issues/5759

Even with the latest Wikivoyage update(today)

**Comment by xmd5a2** [comment]
Fixed

**Comment by ArjanOnwezen** [comment]
Where has been fixed? Can I test this? With the latest nightly the issue isn't resolved.

**Comment by xmd5a2** [comment]
You should download new wikivoyage database to test it.

**Comment by ArjanOnwezen** [comment]
Oops sorry. It pops up now and issue has been fixed. Thanks!
