### ISSUE TITLE
Avoid motorways does not work properly

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6278]
Although Avoid motorways is selected, OsmAnd uses the motorway (A7) for routing. 
https://www.openstreetmap.org/directions?engine=osrm_car&route=50.8608%2C9.7287%3B51.3124%2C9.4816#map=10/51.0518/9.7462 
![image](https://user-images.githubusercontent.com/40493090/48416601-55a85180-e759-11e8-8440-5b1fd7b2c356.png)

**Comment by jfburke3** [comment]
What version are you using?

**Comment by jfburke3** [comment]
I **can** reproduce this in the latest play store beta version 3.2.5 released 2018-11-03, and today's nightly build 3.2.0 26256m, released 2018-11-13.

**Comment by scaidermern** [comment]
Could be related to #5210. Maybe the motorway penalty isn't high enough.

**Comment by xmd5a2** [comment]
Fixed by increasing penalty

**Comment by vshcherb** [comment]
Needs some rework, penalties should not be bigger than 1000-3000

**Comment by crimean** [comment]
Already fixed by penalty 2900-3000
