### ISSUE TITLE
highway=milestone tag is missing in render

### ISSUE THREAD

**Issue by hvdwolf** [osmandapp/Osmand#6284]
In the OsmAnd-Resources repository in the rendering_types.xml you will find
highway -> milestone and historic -> milestone.
https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml#L1706
https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml#L4187

But the default_render.xml only knows the historic->milestone:
https://github.com/osmandapp/OsmAnd-resources/blob/master/rendering_styles/default.render.xml#L6209
https://github.com/osmandapp/OsmAnd-resources/blob/master/rendering_styles/default.render.xml#L7661

The highway=milestone should actually be added to the default_render as well.
As I do not know how you exactly want to embed it, I did not make a pull request but instead I made a quick render file.
Note that I renamed the milestones.render.xml to milestones.render.xml.txt as I am not allowed to attach xml files
[milestones.render.xml.txt](https://github.com/osmandapp/Osmand/files/2586415/milestones.render.xml.txt)

**Comment by xmd5a2** [comment]
@FF-Schelldorf Hello. How specifically do you plan to use this data? Through the search interface or visually on the map?

**Comment by FF-Schelldorf** [comment]
Ideally we would like the info as POIs (show / hide).

**Comment by vshcherb** [comment]
For POI you would need to create custom maps cause we don't want any regular points to be searchable. Any POI is about to search and Map data is to be displayed on the map itself. 
For Map data there are switches to show or not, so it is not exactly same as for POI layer but similar

**Comment by hvdwolf** [comment]
It will be difficult to convert it into a POI map. I did a quick osmconvert/osmfilter on "--keep=highway=milestone"  for the "bayern.osm.pbf", but in this case the points have just a kilometer name and two refs. There is no relation either to the road.
Most nodes however only have the kilometer value and nothing more.
You get something like:
```
	<node id="6051022008" lat="48.8809013" lon="11.4320742" version="3">
		<tag k="distance" v="1.5"/>
		<tag k="highway" v="milestone"/>
		<tag k="ref" v="EI 20"/>
		<tag k="ref:section" v="120"/>
	</node>
	<node id="6051710723" lat="48.8613163" lon="11.4551043" version="2">
		<tag k="distance" v="4.5"/>
		<tag k="highway" v="milestone"/>
		<tag k="ref" v="EI 20"/>
		<tag k="ref:section" v="120"/>
	</node>
```
But also
```
	<node id="5122165118" lat="50.0660449" lon="10.9790404" version="1">
		<tag k="distance" v="78"/>
		<tag k="highway" v="milestone"/>
	</node>
```
which tells you absolutely nothing.

So it would require some shell script or python programming and/or awk/grep work to combine the distances and ref values into a searchable name. And that will only be possible for the complete ones.

@FF-Schelldorf : I think it is better to make a special favorites section (Meine Orte) with the 27 nodes. If you click on the nodes in overpass, you will see the coordinates, kilometer and reference. If the highway=milestone is added on the map, you will be able to see them (or temporarily use the milestone render I sent you), but you will not be able to search them.

If all of the fire brigades in Germany use this, it might be worthwhile to think of some better solution.
(But only a fraction of the milestones have good references, like you gave them some days ago. Some only have the kilometer value without any reference. This makes it really unworkable: Is the "4.5" on the A8 or the A3 or ...?)

**Comment by hvdwolf** [comment]
Just remembered something.

After having osmfilter-ed it to osm, you can use osmconvert to make it into a csv file, like
 `osmconvert <name>.osm --csv="@lat @lon highway:milestone distance ref ref:section" --csv-headline --csv-separator=, -o=<name>.csv`

This will lead to
```
@lat,@lon,highway:milestone,distance,ref,ref:section
50.3889606,11.9770286,,15.5,,
48.5506566,11.5919436,,485.5,,
48.8809013,11.4320742,,1.5,EI 20,120
48.8564926,11.4189385,,2.5,EI 11,140
48.8663215,11.4446543,,3.5,EI 20,120
```
where the two top lines do not have a ref and ref:section, which means they are useless.
Actually the highway:milestone is not working, but I left it in to show I did not forget it.
This csv can easily be converted back into an osm file (with the highway=milestone tag) and then into an osm.pbf osmand  milestone POI file.

That is: if fire brigades in Germany and perhaps other countries use this. Otherwise it is too much work.

**Comment by FF-Schelldorf** [comment]
What a bummer,
but maybe someday.

Thank you for the information

**Comment by hvdwolf** [comment]
For entire Bayern there are 1464 milestones, with only 71 having a reference. Were 53 of those 71 are yours. That is good work.

And some of the other references are like "St 2070; Abschnitt 500; Km 1" or "st2240/420/2 000".
We need a lot of standardisation here.

I still think that creating a separate section with favorites might be the best.
I converted your osm file to csv
`osmconvert km_Angaben_Schelldorf.osm --csv="@id @lat @lon distance ref ref:section" --csv-headline --csv-separator=, -o=km_Angaben_Schelldorf.csv`
I used one of my existing python scripts which only needed a few lines of change to convert to a "favorites.gpx" file which can be imported as favorites into a section kilometersteine.

I also replied in the mail via the osmand googlegroups.

[milestones.zip](https://github.com/osmandapp/Osmand/files/2592098/milestones.zip)

**Comment by FF-Schelldorf** [comment]
Could I do it myself if I want to change my milestones?

**Comment by IgorEliezer** [comment]
Out of curiosity: was this entirely dismissed?

What if just a number (`distance`) is rendered next to the node?

**Comment by xmd5a2** [comment]
> What if just a number (distance) is rendered next to the node?
Topicstarter wants milestones to be displayed on the POI layer, so this is not a solution.

**Comment by IgorEliezer** [comment]
> Topicstarter wants milestones to be displayed on the POI layer, so this is not a solution.

I know, but if at least there's a number on the map (e.g. •123 or ▾123) you have a point of a reference in a highway where housenumbers are quite rare or totally absent, or where there isn't enough elements near the motorway/trunk way to be used as reference. And normally, amenities by the highway use milestones as reference or housenumber.

BTW, Gmaps doesn't render them. :)

**Comment by franco999** [comment]
Just out of curiosity, was this already discarded or could it have been included somehow? I'm interested in being able to see the "distance" KM values for reference, as shown with the _"addr:housenumber"_ nodes.

**Comment by vshcherb** [comment]
Issue 5 years ago things are changed and not clear what do we want to do only with specialized rendering.
