### ISSUE TITLE
Flooded: Germany Free and Hanseatic City of Bremen

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6285]
Galaxy a5 Android 8.0.0 
OsmAnd 3.2.5
Map updated 01.11.18
![image](https://user-images.githubusercontent.com/40493090/48639652-e04cb300-e9dc-11e8-8870-e3e209b8b94d.png)

**Comment by xmd5a2** [comment]
Fixed by https://github.com/osmandapp/OsmAnd-core/commit/b5caf37d261063b92f76a039b72857fb9080aa99
