### ISSUE TITLE
Feature request: keep the saved current track visible on the map

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6287]
When you save the currently recording track, it disappears from the map and one has to look for it in My tracks. This is not always convenient when you have a lot of tracks. Please add the option to keep the saved track visible on the map after saving.

**Comment by gunnar22** [comment]
+1

**Comment by scaidermern** [comment]
Suggestion: Implement this feature together with #5033. When saving a track, show a dialog with an editable name field (already containing the automatically generated name) and a checkbox similar to "[X] Display track on map".

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/55955438-bdf45400-5c61-11e9-80fc-831cd3c6bdb9.png)

**Comment by scaidermern** [comment]
Why "Cancel"? It sounds like this button will delete the track again, i.e. cancel saving it. Isn't "Close" better?

**Comment by sonora** [comment]
"OK", "Close". or "Dismiss" would be correct, I guess.

**Comment by vshcherb** [comment]
I think we've replaed it with details and show on the map, to close you need to click on the map.
https://github.com/osmandapp/Osmand/pull/7206
