### ISSUE TITLE
Unable to update with OsmAnd live: java.io.FileNotFoundException: https://osmand.net/check_live[...]

### ISSUE THREAD

**Issue by tuxayo** [osmandapp/Osmand#6288]
Up to yesterday it was working

### Reproduice
- Try to update live data
- see a toast with a long URL
- no update

### Logs
[logcat.txt](https://github.com/osmandapp/Osmand/files/2593217/logcat.txt)

### Context
- version 3.2.2 from F-Droid
- Phone: Nexus 5
- Android 7.1.2 (LineageOS for microG 14.1)

**Comment by tuxayo** [comment]
I forgot to update the map and thus was only relying on OsmAnd Live (which was working until now but is it a good practice? That would save a lot of downloading compared to just using OsmAnd Live right?)

But the update didn't change anything.

**Comment by tuxayo** [comment]
Well it works now, I did nothing. That might have been a temporary (less than 24h) server-side issue.
Thanks for this great app :)

**Comment by vshcherb** [comment]
Yes, it was server side issue, we've noticed later than expected. Please use Telegram channel https://t.me/joinchat/F23xLkRF4r5Er262jSsHww to notify quick issues
