### ISSUE TITLE
Make Japanese transliteration

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#6292]
We need to make correct Japanese to Roman transliteration.
https://stevemorse.org/japanese/kan2eng.html
https://en.wikipedia.org/wiki/Romanization_of_Japanese
https://github.com/nicolas-raoul/jakaroma

**Comment by c933103** [comment]
Please also add Cantonese transliteration for Hong Kong and Macau.

**Comment by vshcherb** [comment]
Will be Fixed with new Feb maps. We will also try to update January maps to get it.

**Comment by c933103** [comment]
@vshcherb Is the fix only for Japanese? If so then should I open a new issue specifically for Cantonese in Hong Kong and Macau area?

**Comment by vshcherb** [comment]
Sorry long reply. This fix is only for japanese though we are ready to use the same trick to prepare better transliteration for other regions as well
