### ISSUE TITLE
Fantom Costco.

### ISSUE THREAD

**Issue by HubMiner** [osmandapp/Osmand#6294]
https://www.openstreetmap.org/node/3462704140/history

This Costco store appears strangely: 
(1) when selected, it does not show OSM link, and it does not show any details from tags.
(2) when searching nearly for _all_ POIs, I see nearly "Costco Tire Center", but not this "Costco".

**Comment by vshcherb** [comment]
We need to add to POI types
 ```
shop=wholesale
```
