### ISSUE TITLE
Incorrect search results

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6306]
When searching for a locaiton, OsmAnd gives the correct results first, but then incorrect results appear, as in the attached video. 
https://drive.google.com/open?id=1XFwKZ5ESowHCH7kcFCcvM_YYzkMRs-Ks

**Comment by crimean** [comment]
Fixed https://github.com/osmandapp/Osmand/commit/0a4d386abc8910b44757af2eaa69a97eed481eb4
