### ISSUE TITLE
Routing mistake

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6308]
Start 11.16043  -4.28041
End 11.50497  -3.52413
Instead of using the RN1 road, OsmAnd gives a longer route with an unpaved route. 
No options are enabled in the navigation settings
![image](https://user-images.githubusercontent.com/40493090/48978219-e1eb3a80-f0b0-11e8-8ee4-d3b189aceb27.png)
When "Avoid unpaved roads" is enabled, OsmAnd uses RN1 road; however, the last 3 km of the route is an unpaved road, so  "Avoid unpaved roads" cannot be used.
"Avoid unpaved roads" is enabled
![image](https://user-images.githubusercontent.com/40493090/48978221-f62f3780-f0b0-11e8-8028-ce735714ef0d.png)

**Comment by xmd5a2** [comment]
Problematic segment https://www.openstreetmap.org/way/230003447#map=17/11.49102/-3.51986
Changing type to "tertiary" (as it should be) solves the issue.
Test placing end point near problematic way results in completely different routes, but segment length is only 45 m when complete distance is 132 km.
Routing time when end when target_lat="11,49155" target_lon="-3,52082"  routing_time="6733"
Routing time when end when target_lat="11,49119" target_lon="-3,52046"  routing_time="4028,36"
![Screenshot from 2019-04-15 17-07-04](https://user-images.githubusercontent.com/5829014/56139262-34b28980-5fa1-11e9-9179-25f10b2ea0e2.png)
![Screenshot from 2019-04-15 17-06-49](https://user-images.githubusercontent.com/5829014/56139263-34b28980-5fa1-11e9-811a-dcc4dba4d0d8.png)

**Comment by vshcherb** [comment]
fixed

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/60824834-ae29d480-a1aa-11e9-802d-749af3b0e00a.png)
Avoid unpaved roads doesn't go to finish point on that road any more
