### ISSUE TITLE
Strange routing results

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6309]
Start  -34.10826  20.94772
End   -34.08818  20.98008
Bike navigation 
![image](https://user-images.githubusercontent.com/40493090/48978678-c9cae980-f0b7-11e8-80de-8fa15e6c68a7.png)
![image](https://user-images.githubusercontent.com/40493090/48978693-2201eb80-f0b8-11e8-95b7-4db227f1563a.png)

**Comment by issgg** [comment]
Противоракетные манёвры. В лучших традициях Навитела)

**Comment by vshcherb** [comment]
I think the routing is correct given assumptions it is a bike routing and there is no chance to avoid motorways.

**Comment by scaidermern** [comment]
@vshcherb It really depends on the local rules. It is *not* a motorway but a trunk road, also there is no `motorroad=yes` tag present. However I don't know the implications for bicycles in South Africa.

**Comment by scaidermern** [comment]
Meanwhile I think this is mainly a tagging error. In my opinion this road doesn't really match the criteria for a trunk road (https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtrunk). Trunk roads are usually without intersections whereas the road in question has intersections every few kilometers.

In my opinion it should be changed from trunk to primary. However this must be discussed with the local community first. I've created a note: https://www.openstreetmap.org/note/1600868
