### ISSUE TITLE
"Dedicated places for disabled" filter is missing in Parking POIs search

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6312]
The filter is shown when searching in Custom search - Transportation - Parking - Search - filter.
![image](https://user-images.githubusercontent.com/40493090/49011794-082bdb80-f180-11e8-86c3-dae1caef0508.png)

The filter is missing when searching in Search - Categories - Parking - filter. 
![image](https://user-images.githubusercontent.com/40493090/49011897-648efb00-f180-11e8-8e3f-1c7a7e73af92.png)

**Comment by xmd5a2** [comment]
The issue is in fact that when searching using poi_filter https://github.com/osmandapp/OsmAnd-resources/blob/master/poi/poi_types.xml#L1598 child's inner poi_additional_category filters (i.e. capacity_disabled) are not shown in filter search UI. This clearly is an UI bug.
