### ISSUE TITLE
App still uses http protocol

### ISSUE THREAD

**Issue by mahdi1234** [osmandapp/Osmand#6313]
With Lineage OS 15.1 + OsmAnd~ 3.2.5 from f-droid.

During map updates/live update plain http protocol is used. Would it be possible to switch completely to https?

![screenshot_20181126-153351_net_monitor](https://user-images.githubusercontent.com/1097047/49020928-d6bc0b80-f191-11e8-9c44-dc052a7b825e.png)

**Comment by vshcherb** [comment]
We need to checked where exactly
