### ISSUE TITLE
No language update lately?

### ISSUE THREAD

**Issue by IgorEliezer** [osmandapp/Osmand#6314]
_OsmAnd v3.2.6 Unlimited on Android_

Hello,

During this month or so I've received two OsmAnd updates: one in the beginning of the month -- I can't remember the exact day -- and the 2nd on 15th. But I noticed the interface texts have been the same since last month and there have been no commits into this Git from Weblate since 12th, even though I've submitted [a few translations](https://github.com/osmandapp/Osmand/commits?author=igoreliezer) during the period.

Just to give an idea, [this commit](https://github.com/osmandapp/Osmand/commit/25008364f071041088507c5860978df30af3d0b5) wasn't included in both updates.

(Edit: BTW, I can receive the translation updates via OsmAnd Nightly. I'm wondering about the release version)

Sorry if I'm mistaken. :)

**Comment by vshcherb** [comment]
3.2.6 was the last release on 3.2 branch. Next one will be on the master branch and should have all translations in. We plan to release it in 2-3 weeks
