### ISSUE TITLE
Loch Ness is not displayed on the overview map

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6315]
The lake is visible only at close zooms
![image](https://user-images.githubusercontent.com/40493090/49089332-05a2b200-f264-11e8-8574-73d05947999f.png)
![image](https://user-images.githubusercontent.com/40493090/49089345-0a676600-f264-11e8-9aa2-bce4634d781b.png)

It is also not visible on the world overview map
![image](https://user-images.githubusercontent.com/40493090/49089395-25d27100-f264-11e8-86de-56300c30a46a.png)

**Comment by xmd5a2** [comment]
Database updated. Will be fixed with next basemap update.
