### ISSUE TITLE
"Wikipedia <Language>" search results should show results in configured language

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#6317]
The search offers two Wikipedia categories, "Wikipedia" and "Wikipedia _Current Language_". For "Wikipedia _Current Language_" I would expect to see the results in the current language, however they are shown in English instead.

Example:
![photo_2018-11-29_08-07-13](https://user-images.githubusercontent.com/1040784/49205268-d3519b80-f3ae-11e8-93c9-1393afc2eb22.jpg)

Left: OsmAnd language set to English, search results for Wikipedia _English_.
Center: OsmAnd language set to German, search results for Wikipedia _German_. Names are expected to show up in German but they don't.
Right: After tapping on the first search result (highlighted in red). The German name for the POI *is* shown.

So the translated names are definitely available, OsmAnd just doesn't use them in the result list. It even looks like OsmAnd tries to use the English POI names, despite the language being set to German.

geo:51.10945,17.03471?z=16
https://osmand.net/go?lat=51.10945&lon=17.03471&z=16
OsmAnd 3.2.6

**Comment by vshcherb** [comment]
Should be fixed now
