### ISSUE TITLE
Feature request: add Guaraní voice guidance

### ISSUE THREAD

**Issue by CarlosBrys** [osmandapp/Osmand#6319]
Please consider adding the Guaraní language in the list of available voices.
The Guaraní language is widely used and is official in Paraguay, Bolivia and Argentina. It is also used in the southwest of Brazil.
The ISO 639-1 code for the Guarani language is "gn", so the identifier must be: "gn-py"

**Comment by CarlosBrys** [comment]
[gn-py_tts.js.TXT](https://github.com/osmandapp/Osmand/files/2629155/gn-py_tts.js.TXT)

**Comment by MadWasp79** [comment]
Added with #6319

**Comment by franco999** [comment]
I added the Guarani language through Weblate (https://github.com/osmandapp/Osmand/commit/d99f26d4561a111331b0e18904699c26ebc342ca and https://github.com/osmandapp/Osmand/commit/7636ea2314fd21d1541e1e5a7454cada9de28f3f), thinking that @CarlosBrys wanted to translate the whole interface with this language and he told me that he was only interested in the voice file. 

In this case the folder "values-gn" should be deleted if it is not maintained by someone.
