### ISSUE TITLE
Acute accent are not taken into account in search

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6329]
Sometimes the app doesn't take into account acute accents when searching for streets. Ex ; é, è.
![image](https://user-images.githubusercontent.com/40493090/49376422-d8e11580-f70f-11e8-8b2a-06a42b33aee8.png)
![image](https://user-images.githubusercontent.com/40493090/49376428-de3e6000-f70f-11e8-9016-e182d3dbf6e0.png)

**Comment by vshcherb** [comment]
Already fixed in the master branch, I guess

**Comment by crimean** [comment]
Fixed https://github.com/osmandapp/Osmand/commit/ad11a081f9d4d58c7777d84bedf45e4fdc0a0974
