### ISSUE TITLE
Quick action: Day/night mode

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6330]
Light sensor map mode is frequently wrong during the evening transition. Phone sensor is not sensitive enough to detect transition especially when the phone is mounted inside the car. The map mode stays in Day screen when outside and car is dark. Goes to Night screen too early, which I find very difficult to navigate the complicated menu to switch back to Day screen because inside the car is dark while outside is still bright! 
The Sunrise/sunset does not work properly as well, failing to change its view from day to night or night to day, even when the time on a device shows the correct time. 
Therefore, it would be easier to include an icon on the screen to manually select day or night look.

**Comment by pebogufi** [comment]
What about to create a quick action for that ?

**Comment by vshcherb** [comment]
Let's add quick action to switch between day/night.

**Comment by MadWasp79** [comment]
Closed with https://github.com/osmandapp/Osmand/commit/713a3b9d4bf84abb94cfc09c22fc411e3bd779c5
