### ISSUE TITLE
Changeset contents not included in live update

### ISSUE THREAD

**Issue by contrapunctus-1** [osmandapp/Osmand#6335]
I created this changeset yesterday - https://www.openstreetmap.org/changeset/65125771#map=17/28.56759/77.24653

But while the changes from my later changesets have appeared in live updates, the changes from this one have not e.g. two of the parks (Lala Lajpat Rai Memorial Park and Shri Shrinivas Gupta Park) and the new buildings to the west of Shiv Mandir Marg aren't rendered. I've tried deleting and re-downloading the live updates for Delhi, but to no avail.

OsmAnd v3.2.5 from F-Droid, Android v9 (Pie), Nokia 6.1

**Comment by Zahnstocher** [comment]
This park is in live updates:
https://www.openstreetmap.org/way/651977813
This one is not:
https://www.openstreetmap.org/way/651977789
They are both in the same changeset, this is really strange.

**Comment by vshcherb** [comment]
https://www.openstreetmap.org/changeset/65125771#map=17/28.56838/77.24821
https://download.osmand.net/aosmc/india_asia/India_asia_18_12_03.obf.gz, needs investigation.

**Comment by vshcherb** [comment]
Strangely enough 651977789 is not part of osm.change file we have 
https://builder.osmand.net/aosmc/_diff/18_12_03/src/18_12_03_13_50_diff.osm.gz
```
OVERPASS_QUERY_DIFF="
[timeout:3600][maxsize:2000000000]
[diff:\"$START_DATE\",\"$END_DATE\"];
(
   node(changed:\"$START_DATE\",\"$END_DATE\");
   way(changed:\"$START_DATE\",\"$END_DATE\");
   relation(changed:\"$START_DATE\",\"$END_DATE\");
)->.a;
	.a out geom meta;
"
```

**Comment by vshcherb** [comment]
651977813 -  timestamp="2018-12-03T13:40:01Z", should have been processed in diff 13:40-13:50. And it is present at https://builder.osmand.net/aosmc/_diff/18_12_03/src/18_12_03_13_50_diff.osm.gz.

651977789 - timestamp="2018-12-03T13:39:59Z", should have been processed in diff 13:30-13-40. And it is present at https://builder.osmand.net/aosmc/_diff/18_12_03/src/18_12_03_13_40_diff.osm.gz.

**Comment by vshcherb** [comment]
Strangely enough right now query to overpass returns 651977789 correctly, though back to that time https://builder.osmand.net/aosmc/_diff/18_12_03/src/18_12_03_13_40_after.obf.gz, doesn't contain at all 651977789. 
```
[timeout:3600][maxsize:2000000000]
[date:"2018-12-03T13:40:00Z"];
(
  node(changed:"2018-12-03T13:30:00Z","2018-12-03T13:40:00Z");
  way(changed:"2018-12-03T13:30:00Z","2018-12-03T13:40:00Z");
  relation(changed:"2018-12-03T13:30:00Z","2018-12-03T13:40:00Z");
)->.a;
(way(bn.a);.a) ->.a;
(relation(bn.a);.a) ->.a;
(relation(bw.a);.a) ->.a;
(way(r.a);.a) ->.a;
(node(w.a);.a) ->.a;
.a out geom meta;
```

**Comment by vshcherb** [comment]
Adding 60 seconds delay should help overpass
