### ISSUE TITLE
Unnecessary zoom in/out when checking the full info of a selected POI on the map

### ISSUE THREAD

**Issue by oxxm** [osmandapp/Osmand#6337]
Hello all,

for this test case please chose a POI with a lot of info that fills at least the whole display.

1- Select a POI that is located in the lower third of the display
2- The map is pushed upwards so that the marker with a bit of info (address etc..) stays visible too

Note: If the info field is swiped down, the marker on the map disappears and the map does not move in this case. Well not any more after a certain version of osmand, thank you for that.

3- Swipe the info field upwards to the max to read all the info of the POI 
4- Swipe the info field downwards again, back to 1/3 of the display

Result: The map with the marker moves downwards/upwards and zooms in and out very quickly, which is a bit annoying. 

As it seems, swiping the info field upwards moves the map behind it upwards as well.

Can you please change this behaviour like you did for the smaller info field?

Thank you.

**Comment by vshcherb** [comment]
Indeed, it looks like we do unnecessary action when we open full screen (swipe up quickly) and after swipe down the unnecessary animation happens.

**Comment by oxxm** [comment]
A wierd behaviour occures with the same steps above, the map recenters and zooms out! Osmand 3.4.8

**Comment by oxxm** [comment]
Can we please re-open this issue?

**Comment by max-klaus** [comment]
It should not zoom in/out anymore. Could you please provide video may be?

**Comment by oxxm** [comment]
Here are the steps to reproduce this behaviour with 3.4.8:

1- choose a POI on the map in the **lower third** of the screen
2- tap on the POI symbol. The map is pushed upwards and the small info field of the selected POI is visible
3- swipe upwards so that the info field of the POI is on full screen. The map is in the background now.
4- swipe downwards. The small info field is back and a zoom out occurs

As is seems the zoom out occurs when the map is pushed upwards in order to show the small info field of the POI (step 2).

**Comment by max-klaus** [comment]
Cannot confirm/reproduce zoom in/out. The map is only shifting a bit.

**Comment by oxxm** [comment]
Did you tap on a POI in the lower part of the map? If the map is not pushed upwards after selecting the POI (step 2) the zoom out does not happen after swiping the info field down (step 4)

**Comment by max-klaus** [comment]
> Did you tap on a POI in the lower part of the map?
yes

**Comment by oxxm** [comment]
very weird! Do you see the map moving upwards after you select a POI in the lower part of the map?

I can reproduce it every single time! Will try to catch a video of the steps.

Thank you for your reply.
