### ISSUE TITLE
Up to date maps are shown as outdated

### ISSUE THREAD

**Issue by Self-Perfection** [osmandapp/OsmAnd#634]
Sometimes up to date maps are shown as outdated (blue) on download screen. See screenshot below.

![screenshot_2014-05-10-12-13-17](https://cloud.githubusercontent.com/assets/3757038/2935835/3702a20e-d830-11e3-9e66-50bd26be973b.png)

After re-dwnloading such maps it still shows as outdated.

Looks like OsmAnd compares date string of local map and map file on the server and shows downloaded map as blue if these strings do not match.

When I encounter this issue date string for local map is always one day off. I suppose this issue is caused by timezone difference between  the server and my device.

**Comment by Self-Perfection** [comment]
This bug is immortal
![screenshot-05-06-15-10-15-13](https://cloud.githubusercontent.com/assets/3757038/8091668/da792884-0fbd-11e5-9e08-1eacda1d217a.png)
Screenshot from OsmAnd 2.0.4, released at 2015-05-10

**Comment by vshcherb** [comment]
There is an open one already. Indeed it is immortal because only 1-3% devices, don't support timestamp on sdcard and these devices are not available for our testing.
