### ISSUE TITLE
Feature request: show azimuth when measuring distance

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6345]
Please add the feature to show azimuth (with distance) when the user draws lines by Measure distance tool.

**Comment by MadWasp79** [comment]
closed with https://github.com/osmandapp/Osmand/commit/c452d8429dbd34d9463788c4ae3a79033235ffcc

**Comment by breversa** [comment]
From what I can gather from the pull request, the azimuth will be shown in degrees.

Would it be possible to display it as milliradians (https://en.wikipedia.org/wiki/Milliradian), with 360° = 6400mil ?
Along with UTM/MGRS, it's highly useful for land navigation in a military context.

**Comment by vshcherb** [comment]
I think we can display it when UTM is enabled

**Comment by MadWasp79** [comment]
We'll add angular measurement unit selection to settings.
