### ISSUE TITLE
Wrong routing: Ronda de la Muralla, Lugo, Spain

### ISSUE THREAD

**Issue by rodrigorega** [osmandapp/Osmand#6346]
I am using OsmAnd 3.2.2 in-app offline routing. The profile used is car.

From: 47, Ronda de la Muralla, San Roque, Lugo, Galicia, 27002, Spain
To: 38-36, Avenida de A Coruña, Centro Recinto amurallado, Lugo, Galicia, 27003, Spain

This is the route offered by OsmAnd:
![image](https://user-images.githubusercontent.com/3441785/49615285-5e352600-f9ad-11e8-8b08-c2c3a5c53561.png)

This is the expected route:
![image](https://user-images.githubusercontent.com/3441785/49615340-90468800-f9ad-11e8-95bf-24b53de19e88.png)
https://www.openstreetmap.org/directions?engine=osrm_car&route=43.01241%2C-7.55379%3B43.01581%2C-7.55933#map=16/43.0118/-7.5550

**Comment by naoliv** [comment]
It doesn't seem to be related with traffic signals, but instead with missing `maxspeed`.
The tertiary way has `maxspeed=30` while all the residential ones have nothing (https://www.openstreetmap.org/way/81604540, for example)

**Comment by rodrigorega** [comment]
Could it be related to this speed camera? https://www.openstreetmap.org/node/5633761338

**Comment by naoliv** [comment]
I don't think so.
If I am not wrong, osmand assumes that a residential highway without `maxspeed` has an implicit speed of 35 km/h
Thus, they are considered faster than the tertiary segment with a maxspeed of 30 km/h

**Comment by rodrigorega** [comment]
>Thus, they are considered faster than the tertiary segment with a maxspeed of 30 km/h


I tried to reproduce the issue in a nearby route without "maxspeed" tags in some of the highways. The route works as expected:
![image](https://user-images.githubusercontent.com/3441785/49646821-a6d9f700-fa20-11e8-802f-d567b090da26.png)

The highways painted in red by hand does not have "maxspeed" tags (or > 30km/h) and the routing are ignoring them as expected:
![image](https://user-images.githubusercontent.com/3441785/49646992-46978500-fa21-11e8-977f-f11ddedeee54.png)

**Comment by Zahnstocher** [comment]
@rodrigorega 
Probably you enabled the "avoid unpaved" routing option.
surface=compacted seems to be wrong:
https://www.openstreetmap.org/way/235025696

**Comment by rodrigorega** [comment]
@Zahnstocher you are right, I fixed it. I checked the city and this is the only way tagged with "surface=compacted.

Thank you.
