### ISSUE TITLE
craft=confectionery bad render

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [osmandapp/Osmand#6350]
1. No icon for craft=confectionery

2. huge name that looks like building name

![screenshot_20181209-200821_osmand](https://user-images.githubusercontent.com/14617699/49700484-51544480-fbf0-11e8-9c60-7481e3042dea.png)
![screenshot_20181209-200827_osmand](https://user-images.githubusercontent.com/14617699/49700485-51ecdb00-fbf0-11e8-82a9-b0753937bccd.png)
![screenshot_20181209-200832_osmand](https://user-images.githubusercontent.com/14617699/49700486-51ecdb00-fbf0-11e8-97dd-57b66dc7323c.png)
![screenshot_20181209-200839_osmand](https://user-images.githubusercontent.com/14617699/49700487-51ecdb00-fbf0-11e8-9bbb-d30861d63ab4.png)
![screenshot_20181209-200847_osmand](https://user-images.githubusercontent.com/14617699/49700488-51ecdb00-fbf0-11e8-82d8-f689860e27a4.png)
![screenshot_20181209-200857_osmand](https://user-images.githubusercontent.com/14617699/49700489-52857180-fbf0-11e8-8896-b0aa27995883.png)

**Comment by vshcherb** [comment]
Indeed text size is strangely bigger and probably we can use same icon as for shop=confectionery
