### ISSUE TITLE
BUG: deleted favourites are returned after some time

### ISSUE THREAD

**Issue by pbb72** [osmandapp/Osmand#6354]
Since I use favorites to make notes of things I need to edit on OpenStreetMap (in those situations where I can not do the edit in OsmAnd), I regularly create and delete favorites.

Several times, I have been wondering why I found a favourite in OsmAnd for an item I had already fixed on the map. Could it be that OsmAnd is "recovering" the favorites I deleted, or did I do something wrong myself.

Then, to test this situation better, I went into "My Places" and changed the name of the "Favourites" group into "My notes". So, now there was no more Favourites group. I also processed some of my notes and deleted them from the list in OsmAnd.

And indeed, several days later, suddenly there was a "Favourites" group again, containing all my old notes, including the ones I had deleted.

So there is definitely a process going on that is restoring deleted favourites in the background. It is not immediate, it takes a few days. (Maybe even a few weeks?)

I am using OsmAnd+ 3.2.7, on a Samsung S7 with Android 8.0.0.

**Comment by ithink314** [comment]
I've saved a large number of favorite locations, in several different named groups. It seems some favorites are moved into the "favourites" group, almost at random. I've just tried renaming "favourites" and will see what happens.

**Comment by vshcherb** [comment]
it is not reproducible with latest version 3.7
