### ISSUE TITLE
Map orientation threshold 

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6359]
The map orientation threshold seems to only work once. I've set it to 5 km/h. When I start navigation, it starts in "direction up" orientation but at the first stop (getting <5 km/h) it switches to "north up" and stays this way for the rest of the trip.

Isn't it supposed to switch back to "direction up" when I get faster than my selected threshold of 5 km/h?

**Comment by vshcherb** [comment]
Need to check:

https://github.com/osmandapp/Osmand/blob/4c9cfae0f548e140cf950d977a79b97ab816129b/OsmAnd/src/net/osmand/plus/base/MapViewTrackingUtilities.java#L186
and
https://github.com/osmandapp/Osmand/blob/4c9cfae0f548e140cf950d977a79b97ab816129b/OsmAnd/src/net/osmand/plus/base/MapViewTrackingUtilities.java#L132

**Comment by ilyaguy** [comment]
Also, could you implement functionality to have different values in different navigation modes?

**Comment by MadWasp79** [comment]
closed with #6359
