### ISSUE TITLE
Zoom level and coordinates search screen

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6361]
When working with OsmAnd in a taxi, the zoom level is not close enough when opening a location; it is always necessary to zoom in. And for some reason, the coordinate search screen remains, you have to press "back" once more to remove it. 
https://drive.google.com/file/d/1XGNhGYbhV8TILvlZdaeCeuEvHLwm1KVZ/view

**Comment by sonora** [comment]
I think both views are needed, an overview where something is located and a zoomed-in view.

Are you aware that a single tap on the point name in the context menu automatically zooms in? Somehow this has always been a 'hidden' feature, not sure how it can be made visible, perhaps using some sort of button look.

**Comment by vshcherb** [comment]
It is hard to say how the integration done cause there is a way to pass zoom level while opening i.e.
``` geo:37.7749,-122.4194?z=10&q=restaurants```
