### ISSUE TITLE
Flooded: Germany Lower Saxony 

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6362]
![image](https://user-images.githubusercontent.com/40493090/50043435-d621e100-007c-11e9-9981-e90287a83ddd.png)
https://www.openstreetmap.org/search?query=Wittmund%20#map=11/53.6775/7.8323

**Comment by jfburke3** [comment]
It's "global warming," not an OsmAnd bug :-D

**Comment by sonora** [comment]
LOTFL :)

**Comment by alyonapinchuk** [comment]
The same issue is with the Isle of Anglesey.
https://www.openstreetmap.org/search?query=%20Isle%20of%20Anglesey#map=10/53.2813/-4.3597
![image](https://user-images.githubusercontent.com/40493090/50727968-ac178800-112b-11e9-9dbb-e49af3716bdc.png)

**Comment by alyonapinchuk** [comment]
https://www.openstreetmap.org/relation/1650407#map=8/60.140/20.303
![image](https://user-images.githubusercontent.com/40493090/50737387-47166d80-11d1-11e9-9a0f-c971583945d7.png)

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-core/commit/b5caf37d261063b92f76a039b72857fb9080aa99
