### ISSUE TITLE
Feature request: measure distance with multiple routing methods

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/OsmAnd#6364]
It would be very useful to be able to change, after each point you add, the routing method. For example, I try to make a route between different islands in Greece and if I use the snap to road option, the ferries encountered block the routing method. For example, I use the bicycle routing option and add points on the map creating a route on an island. When I arrive at the ferry departure, if I disable the routing method to add a straight line to the next island all the track calculated for bicycle routing changes to straight lines and I lose the bicycle routing track calculated. It would be very useful if OsmAnd could memorate the track for the routing method I choose and when I disable the routing option to add a straight line, the track created until the changing, saves. So the idea is that OsmAnd saves the track between the points added and doesn't modify when I change between the options for routing.

**Comment by jfburke3** [comment]
@alyonapinchuk The description you gave is...a little confusing to me.  Could you provide a specific example to help?

The devs might understand what you're asking for, though, in which case that might not be necessary.

**Comment by pgavrilov** [comment]
It would be especially useful for planning future bicycle route.
Fast long distance segments of bicycle route better to made in auto mode (through wide streets, even highways, etc).
Short shortcut segments of bicycle route better to made in pedestian mode (through pedestrian ways, paths and even stairs).

**Comment by pgavrilov** [comment]
Another moment is a route planning through missed paths, ways and way links (small mistakes on OSM map).
