### ISSUE TITLE
rendering problem with access=private

### ISSUE THREAD

**Issue by marius851000** [osmandapp/Osmand#6370]
There is problem when rendering with access=private & highway=service. The fact there are private ( red dot ) are seem to appear randomly, changing when I zoom in / out. When I zoom a lot, I can see it appear to have two way ( there is only one on JOSM ), and it only display it on one way, the way displaying it changing randomly when I dezoom / zoom. It appear the other way hide it. This problem still appear when I dezoom a lot.

The position when I've seen this is here: https://www.openstreetmap.org/#map=19/46.58801/-1.40476

What version of OsmAnd are you using, on what device and Android/iOS version?
osmand~ 3.2.2 from fdroid

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?
I use the offline map downloaded from osmand

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.
The file name is France_pays-de-la-loire_europe. I didn't know it's edition date.

**Comment by xmd5a2** [comment]
Can you provide some screenshots illustrating this issue? I can't find anything abnormal in this area.
