### ISSUE TITLE
Finish navigation prompt does not clear

### ISSUE THREAD

**Issue by Goodingn** [osmandapp/Osmand#6373]
If you have turned the screen off at some point during navigation- the screen comes back on due to the 'turn screen on if off' setting- when you reach your destination, pressing the 'Finish navigation' option returns me to the lock screen.

When I clear the lock screen, OSMand is still showing the finish navigation options, but you cannot dismiss it- any screen presses go 'through' the options and operate the map instead.

Ta,

**Comment by vshcherb** [comment]
Fixed recently
