### ISSUE TITLE
Un-necessary lane guidance

### ISSUE THREAD

**Issue by Goodingn** [osmandapp/Osmand#6375]
When travelling along a major dual carriageway, OSMAnd shows the upcoming turn-off or roundabout for the miles away turn off, but in the interim there is lane guidance and a navigation arrow on the map for EVERY junction I pass.

The navigation arrow on the map shows to carry on straight, which is distracting.

The lane guidance shows to stay in the right two straight on lanes and to not use the left-hand straight on lane (UK).

There is a slip-road (Trunk Link), but the physical layout of these are that there is a dashed line between it (starting at 0m width) and the two main lanes and as soon as the lane becomes wide enough to be a full lane, it detaches from the main carriageway (Trunk Road) (the 'lane' is a wedge shape until it is a full lane width, when it detaches).
https://www.google.com/maps/@54.5522505,-1.3708049,110m/data=!3m1!1e3
https://www.openstreetmap.org/#map=18/54.55248/-1.36918

https://www.google.com/maps/@54.5424438,-1.4747012,383a,35y,10h/data=!3m1!1e3
https://www.openstreetmap.org/#map=19/54.54218/-1.47460
![screenshot_20181217-151953_osmand](https://user-images.githubusercontent.com/13037960/50273578-f661ef00-0432-11e9-88e3-6355c60b47f4.jpg)

This is not an additional lane to the current road and OpenStreetMap reflects this- a constant two lane carriageway.  Why does OSMAnd therefore invent one?

Also, the left-hand lane guidance has a straight-on symbol, but this is a turn-off.  The sliproads in OpenStreetMap are marked as such, but bear the same name as the main carriageway.

Ta

**Comment by scaidermern** [comment]
Interestingly there are only 2 lanes mapped, not 3: https://www.openstreetmap.org/way/49133910

**Comment by naoliv** [comment]
https://www.openstreetmap.org/way/49133910 has 2 lanes, but isn't osmand counting https://www.openstreetmap.org/way/95507449 as a third lane?

ie, before https://www.openstreetmap.org/node/747815097 osmand is assuming that the driver would have 3 lanes options at the road (and to keep ahead, the driver must not take the most left one)

**Comment by jfburke3** [comment]
With respect to lane guidance appearing at each intersection/exit/junction, I would say that it is doing what it's supposed to do:  provide you with lane guidance as you approach each road so you know which lane(s) to be in to reach your next turn.

@scaidermern With respect to the guidance displaying 3 lanes when lanes=2, that is, I believe, intentional on the part of the developers when there is no turn:lanes guidance in place.  I think it was their best-effort workaround to figure out how to display lane guidance when the app can't determine how the exit/turn configuration exists on the road.  If you needed to exit/turn ahead, then the left arrow would have been highlighted instead, to help inform you that you need to be looking for your exit/turn approaching.  Adding turn:lanes to the road approaching exits/turns results in a much better lane guidance display in OsmAnd, because then it knows exactly how the exit/turn configuration will look to you, the driver.  I'm spending a great deal of time mapping freeway exits to include that information in areas I drive in (and a lot of poorly-imported or out-of-date road data gets cleaned up in the process).

**Comment by Goodingn** [comment]
At all of these sliproads there is no overhead lane signeage and no preceding lane guidance on the road. I can't update Openstreetmap with what isn't there? The arrows on the road (Google maps links) are point data- the node at which the road junction is at, nothing for lanes preceeding the turn. The sliproad is never wholly a lane alongside the main carriageway, so there never is a lane whith which to attribute a turn.

Therefore, being a turn at a node and never wholly a lane, I'd never expect to be shown any guidance to contiue following the road, in much the same way I'm never shown guidance to carry on passing all the junctions off a major road in a built-up area?

Further, IF I were to turn, being a departure at a node, not wholly a lane, I'd expect lane guidance to look like the split arrow on the Google Map?

**Comment by jfburke3** [comment]
I would split A66 at the trunk_link, and then on the section of A66 between the bridge and the trunk link, I would add this:

turn:lanes=slight_left;through|through

(Personally, I would add that on the section of A66 that is the bridge, too.  I typically add lane guidance beginning 1/2 mile before the exit node.)

I will note that there's a minor OsmAnd bug involving slight_left;left that is documented in issue #5235.  However, it still produces good lane guidance when you should exit.

**Comment by jfburke3** [comment]
And I base that on how the lanes visually appear from satellite imagery.  Signage is nice, but you can still add lane guidance when there isn't any simply based on the fact that that's how the road looks.

**Comment by Goodingn** [comment]
Thanks, I'll give that some thought.

However, having seen the screenshot on the referenced bug, I think the default behaviour can be improved still.

If there are two lanes before the junction node and two after, without guidance recorded, instead of inventing a whole new lane as it currently does, how about instead it invents 'slight left' and 'through' for the left lane instead? For my examples this would be better default behaviour in lieu of specific lane guidance.

Still not sure we need the guidance to show at all when passing and not taking a turn-off where it have been marked as, or defaulted to, slight left- however I haven't knowingly seen one yet :)

**Comment by jfburke3** [comment]
If the app invented a slight left and through, then it would be giving incorrect guidance when it was actually a sharp left, which could give a driver false expectations.

Regarding the need to show guidance when you're just passing the exit, I've encountered several places where that helps, especially in large cities.  Not so much in rural areas, but OsmAnd can't tell which one it's in.

**Comment by Goodingn** [comment]
I would expect any 'trunk link' road to be approprately curved for the speed of the road to not have any unreasonable expectations as to the severity of the turn? In the example given it is pretty tight and the road markings are still slight left. Anything more severe wouldn't be a Trunk Link because any link road from a Trunk road would have been constructed speed appropriate?

**Comment by Goodingn** [comment]
This is a very tight turn-off, but it is not Trunk Link:-
https://www.openstreetmap.org/#map=17/54.54452/-1.40711

I would be very happy for this not Trunk Link road to not be a Slight Left :)

**Comment by jfburke3** [comment]
Not all connecting roads will have a trunk_link going to them.  I know of some trunk roads that have an intersection with other road types (primary, secondary, etc.), and there is no _link road, so they're an actual right turn (turn:lanes=through;right)  Since I live in the U.S., my lane guidance is the opposite of yours, of course, but the same principle applies.

**Comment by Goodingn** [comment]
I think we agree on the non existance of a trunk link would indicate a tighter turn that expected, but where there is a Trunk Link I'd prefer it to default to slight left?

**Comment by Goodingn** [comment]
I've been distracted by the angle of the junction and the pretty arrows, but I will consider use of slight left on main carriageway- thanks.

However, people can sleep-drive up dual carriageways and motorways without once mistakenly turning off it. I don't think lane guidance is necessary for passing a junction, unless specific lane guidance indicates one of the lanes will take you off the route.

Putting up lanes for me to check (notably where the lane being shown doesn't even exist) and an arrow on the map are inputs I now have to process and attempt to match to real surroundings, and they don't, so they distracting from driving.

**Comment by jfburke3** [comment]
"Slight left" fails here.  https://www.openstreetmap.org/#map=18/34.14014/-84.74568&layers=G

If  you're travelling northeast on Old Alabama Road / Red Top Mountain Road, and want to get on US 41 (north or southbound), you have to make a sharp left onto the trunk_link.

**Comment by Goodingn** [comment]
That junction layout looks considerably different to the roads I'm talking about.
https://www.google.com/maps/place/Joe+Frank+Harris+Pkwy+SE,+Emerson,+GA,+USA/@34.1405441,-84.7450441,154m/data=!3m1!1e3!4m5!3m4!1s0x88f54f6aec71bf67:0x64026b76863cd706!8m2!3d34.1222077!4d-84.750077

That sharp turn is clearly preceded by a new third lane and should be described as such as a 'right' only lane in the main carriageway?  However, there are currently only 2 lanes in OpenStreetmap?
https://www.openstreetmap.org/way/656849654

I'm talking about the trunk-link roads that immediately depart from the main carriageway without a stretch of an alongside dedicated lane.

That's not to say that some aren't also sharp turning, but the guidance from the main carriageway would always be slight left.  The 'sharp turning' nature of the road is a visual thing- there would be signage for the sharp turn as there would be on any other minor road with a sharp turn (that OSMAnd also wouldn't show).

However, I'd like to look around a bit for some good examples of this to see how they are marked up, to see if a left turn lane somewhere is useful.

However, the top and bottom of this, I don't see how three forward lane guidance can be the default position for these junctions?

The three lane guidance is still very distracting and the default should be a straight/slight left in the left lane for the join between a trunk and a trunk link.  And to not show if you're just passing them by because both the available lanes take you where you need to be- continuing onwards.

**Comment by Goodingn** [comment]
Also, is this a 'UK' thing, as per original post describing the junction layout:-

> There is a slip-road (Trunk Link), but the physical layout of these are that there is a dashed line between it (starting at 0m width) and the two main lanes and **as soon as the lane becomes wide enough to be a full lane, it detaches from the main carriageway** (Trunk Road) (the 'lane' is a wedge shape until it is a full lane width, when it detaches).
> https://www.google.com/maps/@54.5522505,-1.3708049,110m/data=!3m1!1e3
> https://www.openstreetmap.org/#map=18/54.55248/-1.36918

**Comment by vshcherb** [comment]
Assumptions are always wrong in some cases, so there is no way to guess right if information missing.
Please feel free to add "turn:lanes" so it will indicate "turn_left,straight;straight"

As of today there is no issue cause you can still select two lanes straight and they are correct and the "extra" lane indicates there will be an exit.

**Comment by Goodingn** [comment]
Thanks for considering this. However, you state there is no way to guess right if information is missing and this is partly my point- it is guessing and it is adding a third lane :/

**Comment by Goodingn** [comment]
On all the roads? I'll just get cracking on with that then :)

Look, I'm fine with this being closed. It's the wrong decision as far as I see it, but any decision is better than no decision.

**Comment by Goodingn** [comment]
This request has been closed on the grounds that a change to the tags would 'help' and being told to 'stay on the road' is fundamentaly 'correct', but I personally think this is still too much direction, distracting from safe driving, and would like to leave that stated here, thank you very much :)

**Comment by vshcherb** [comment]
@Goodingn this would be indefinite discussion, the information is incomplete and it doesn't matter which decision should be taken cause in % cases it will be wrong.
