### ISSUE TITLE
Osmand Live error

### ISSUE THREAD

**Issue by oxxm** [osmandapp/Osmand#6378]
Hello all,

since today morning the following error message is shown whenever I try to get the newest live maps:

https://osmand.net/check_live?aosmc=true&timestamp=.............&file=................

Is it only me? Thank you.

**Comment by scaidermern** [comment]
Same problem here.

**Comment by vshcherb** [comment]
Please check

**Comment by vshcherb** [comment]
should be fixed

**Comment by oxxm** [comment]
fixed. thank you.

**Comment by scaidermern** [comment]
Broken again? https://osmand.net/check_live?aosmc=true&timestamp=1546526400000&file=Germany_sachsen_europe returns 404.
