### ISSUE TITLE
More intelligent display of opening hours during search

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#6380]
Consider the following example: It is Saturday evening and I'm searching for a pharmacy:

![photo_2018-12-21_14-28-57](https://user-images.githubusercontent.com/1040784/50345068-fabf0280-052d-11e9-9173-5bcd902f3107.jpg)

Unfortunately all of the pharmacies around me are already closed. The displayed opening hours don't help me really much here because their time span is located in the past. Instead it would be more helpful to display the *next* opening of this facility. Either by replacing the currently displayed values or by displaying them in an additional row.

Sure I could tap on each pharmacy to see when they will open next by looking at the full opening hours. But this is tedious. I want to see when they will open _again_.

**Comment by scaidermern** [comment]
An alternative representation of opening hours aka "opens next at..." is already implemented and displayed when tapping on a POI:

![img_20181224_131347](https://user-images.githubusercontent.com/1040784/50399249-5089e980-077e-11e9-9722-d5d1c1c655f2.jpg)

Would be great to see this information in the search results _if_ the POI won't open today anymore.

**Comment by scaidermern** [comment]
Thanks!

**Comment by vshcherb** [comment]
- UI: Use the same clock icon in search UI from Context menu

**Comment by sonora** [comment]
We have a filter 'Open now', why dom't you simply use it? No extra code required  heere at all?

**Comment by scaidermern** [comment]
> We have a filter 'Open now', why dom't you simply use it? No extra code required heere at all?

This issue isn't about filtering. If everything around you is already closed then it is not helpful at all to display the opening hours for the current day. Instead it is way more interesting to know at which time currently closed POIs will open _again_.

**Comment by sonora** [comment]
@scaidermern Ah sorry, yes, I misread your description. Mea culpa!

**Comment by scaidermern** [comment]
@sonora No big deal. Maybe my description wasn't clear enough.
