### ISSUE TITLE
Add default units of measurement if not specified in the object

### ISSUE THREAD

**Issue by IgorEliezer** [osmandapp/Osmand#6383]
This is totally cosmetic. According to the [wiki](https://wiki.openstreetmap.org/wiki/Map_Features/Units#Default_units), we can omit the units of measurement in the objects since there are assumed "default units".

Example: https://www.openstreetmap.org/way/549184447
![image](https://user-images.githubusercontent.com/4673289/50365415-a3378b80-055b-11e9-9a4a-5425c6e1f634.png)

As you can see in depth, height and width there is no unit explicit. It would be more "human readable" if the measurements had units.

I think it would be safe to add unit of measurement for the following:
* " m" for length measurements (width, height, depth);
* " km" for `distance`;
* " m³" for [`capacity`](https://wiki.openstreetmap.org/wiki/Key:capacity) of `water_tower` and `storage_tank`;
* " t" for `maxweight`;
* " students" for kindergarten and school.
* " spots" for parking, bicycle parking and taxi.
* " seats" for restaurants and biergarten.

### Addendum:
To avoid plural vs. singular cases, which is not consistent across languages, OsmAnd would show a label atop the number instead of as unit of measurement on the right.

**Comment by MadWasp79** [comment]
Closed with https://github.com/osmandapp/Osmand/commit/88c75bf52425861e89a4631fe8a275c4c85163da

**Comment by verdulo** [comment]
The key "[capacity](https://wiki.openstreetmap.org/wiki/Special:WhatLinksHere/Key:capacity)" has also another function! It is for number number of rooms in hotels, cars at charging station, bikes for rent, etc; so another error occurs:
![bildo](https://user-images.githubusercontent.com/16842967/53306826-5ee5a600-3892-11e9-90a7-d1508fb0655c.png)

The unit should only be showed for objects:
man_made=water_tower
amenity=waste_disposal (currently not showed in OsmAnd)

**Comment by IgorEliezer** [comment]
> The key "[capacity](https://wiki.openstreetmap.org/wiki/Special:WhatLinksHere/Key:capacity)" has also another function! It is for number number of rooms in hotels, cars at charging station, bikes for rent, etc [...]

That was something I suggested in the 1st post:
> I think it would be safe to add unit of measurement for the following:
> * " m³" for [`capacity`](https://wiki.openstreetmap.org/wiki/Key:capacity) of `water_tower` and `storage_tank`;
> * " students" for kindergarten and school. (<-- it is also `capacity`)
> * "spots" for parking, bicycle parking and taxi. (<-- same)
> * " seats" for restaurants and biergarten. (<-- same)

I think it's safe to say "spots" would be the unit for any amenity related to vehicles of any kind.

**Comment by MadWasp79** [comment]
closed with https://github.com/osmandapp/Osmand/pull/6584/commits/2fcb8d27486121faa07f92918e0abf16df6f75f6

**Comment by ArjanOnwezen** [comment]
Now parking capacity is not shown anymore.  It's empty.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/pull/6592
