### ISSUE TITLE
Bug: importing favourites deletes ALL existing favs

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#6384]
If I click on a gpx file at a file manager, osmand is openend and then I choose import as favourite.
The file is imported, but ALL existing favourites are deleted.
see also https://groups.google.com/forum/m/#!topic/osmand/CLCRswBmStM
version 3.3.0#26434

**Comment by vshcherb** [comment]
Need to check
BTW there are file backups, so it should be able to restore

**Comment by MadWasp79** [comment]
fixed with https://github.com/osmandapp/Osmand/commit/40f47fc9d18656211c9586fd395c983e694c0746
