### ISSUE TITLE
Feature request: retain the original color coding when importing GPX

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6386]
Some large GPX files have hundreds (if not thousands) of segments which are color-coded for different types of trails (full-size vehicle, motorcycle, snowmobile, restricted, etc.). This color coding is lost when importing the file. Appearance in OsmAnd can be changed but they are all the same. Please include the opportunity to have the original GPX track color coding retained. Even better would be to have the ability to filter by segment types (colors). I.e., I don’t want to see motorcycle trails when I’m in a full-size vehicle.

**Comment by pebogufi** [comment]
The color coding works in import, if you use it like this:

<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<gpx version="1.1" creator="OsmAnd~" xmlns="http://www.topografix.com/GPX/1/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
  <wpt lat="48.00" lon="7.888675">
    <name>testPOI</name>
    <type>aaaTest</type>
    <extensions>
      <color>#b4eeeeee</color>
    </extensions>
  </wpt>
</gpx>

**Comment by scaidermern** [comment]
Maybe we can add support for additional color codings. How does the color coding of your GPX file look like?

**Comment by RKCRLR** [comment]
The files can be found here:
http://www.owlsheadgps.com/owlshead/index.php/extras/downloads

I've attached a representative file.  
[central_sierra_nevada_gpx.zip](https://github.com/osmandapp/Osmand/files/2708876/central_sierra_nevada_gpx.zip)


Another option for me would be to save the segments by type in separate files but I couldn't figure out a good way to do that.  

Thanks

**Comment by RKCRLR** [comment]
Thanks, but you may be overestimating my abilities!  
Do I just copy the GPXUtilities.java file somewhere?  If so, where?  
Thanks

Sent from Mail for Windows 10

**Comment by RKCRLR** [comment]
OK, I downloaded and installed the latest OsmAnd Android nightly build.  I then imported the GPX file.  All of the tracks are still red.  
Is this was what I was supposed to do?  
I didn't download any maps for this test if that matters.  
Thanks

**Comment by vshcherb** [comment]
Please try with latest build - https://download.osmand.net/latest-night-build/OsmAnd-default.apk

**Comment by RKCRLR** [comment]
Thanks for reopening the ticket.

**Comment by RKCRLR** [comment]
So, did the feature get added?  
Thanks

Sent from Mail for Windows 10
