### ISSUE TITLE
(Meta) Are third-party trackers in OsmAnd?

### ISSUE THREAD

**Issue by pietervdvn** [osmandapp/Osmand#6389]
Hello,

According to [some site on the internet](https://reports.exodus-privacy.eu.org/en/reports/49071/), there are some tracker built into OsmAnd (or at least, some vague 'static code analysis' detected it). 

When doing a quick search, I stumbled upon [this code](https://github.com/osmandapp/Osmand/blob/284fd9a4697802637933edbde3fac39a9727b053/OsmAnd/src/net/osmand/plus/OsmandApplication.java#L904).

1) What are these builtin-trackers? Why are they useful for OsmAnd?
2) How much information do they leak to FB and Google?
3) Should and can they be disabled, preferably by default? The privacy-respecting part of OsmAnd is one of the selling points I often use.

**Comment by scaidermern** [comment]
The Facebook related part of this question is probably answered at #5155.

**Comment by vshcherb** [comment]
We're planning to remove all trackers and update with only question-based information which will only be shared with OsmAnd and no other third-parties.

Unfortunately, this part is scheduled after some major app improvements like public transport and we have limited developer-power, though the privacy is very important question for 2019 and we hope to achieve in 2019 Q1.

BTW: OsmAnd+ is free of all trackers

**Comment by pietervdvn** [comment]
Hey! I'm currently building a PT-library too, which should run on android
too. If you happen to be at CCC, plz search me

**Comment by scaidermern** [comment]
> We're planning to remove all trackers and update with only question-based information which will only be shared with OsmAnd and no other third-parties.

> Unfortunately, this part is scheduled after some major app improvements

IANAL but as far as I know you are violating [GDPR](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation) if you share personal data with third parties or export it outside of the EEA (European Economic Area) without explicit, informed consent of the user.

You should change this behavior now, not with the next major update.

**Comment by vshcherb** [comment]
@scaidermern As far as I understand  we don't share any personal data with Firebase or Facebook, it is not possible to identify a person by the data is collected automatically i.e. app installation, session time and used screens. We also don't store and don't have access to it. 

Personal data is the data that could identify the person, any location data is not submitted through the network.

**Comment by pietervdvn** [comment]
As the latest versions don't include the trackers anymore, this issue can be closed.
