### ISSUE TITLE
overlay map is not visible in night mode

### ISSUE THREAD

**Issue by 532910** [osmandapp/Osmand#6393]
Overlay map (Yandex Traffic RU) is not visible due to yellow routing line

As overlay map has transparency setting it (overlay map) must be shown at the top level, above all, including routung line.

![screenshot_20181225-193443_osmand](https://user-images.githubusercontent.com/14617699/50425333-05a6c980-0885-11e9-84ea-0adde49d8fff.png)

**Comment by pebogufi** [comment]
Looks like there is more corrupted with overlay...
https://github.com/osmandapp/Osmand/issues/6385

**Comment by c-e-p-x-u-o** [comment]
Really I don't nothing common with  #6385.

**Comment by vshcherb** [comment]
Can't be fixed

**Comment by 532910** [comment]
What does it mean "can't be fixed"?
The easiest fix is to make yellow line transparent as a blue one in day mode.

**Comment by vshcherb** [comment]
You can create a custom style and override though we don't plan to fix it now

**Comment by 532910** [comment]
I'm disagree with this decisions and would like it to be reviewed by someone else.

The fix is easy: yellow line (navigation in night mode) should be transparent same as blue one (navigation in day mode)

Anyway, if you don't want to fix it it's not the reason to close this issue.

**Comment by des-esseintes** [comment]
why is this issue closed? it's very annoying and looks like actually _can_ be fixed pretty easy, as day mode is working properly.

**Comment by vshcherb** [comment]
Night mode has limitations of colors we can display and people can recognize, light yellow will conflict with other features. It is always possible to have a custom style and we plan to make it easier in future

**Comment by 532910** [comment]
OK, what is the problem to put overlay layer above the routing line?

**Comment by vshcherb** [comment]
In theory no problem to put over, in practice it will need a separate setting cause not all overlays are transparent

**Comment by 532910** [comment]
):
