### ISSUE TITLE
No TTS voice at all on Samsung Galaxy A6 (after choosing Dutch) -- fixed but with suggestion

### ISSUE THREAD

**Issue by fslori** [osmandapp/OsmAnd#6397]
This issue is related to #2166 and does a suggestion for an in-app solution. My issue uses Dutch as an example, but will be applicable to the many languages that are not by default installed in the Samsung TTS engine.

Using OsmAnd 3.2.7 in Android 8.0.0 on Samsung Galaxy A6:

**I get no TTS voice during navigation, after selecting the 'Dutch' language in OsmAnd.**

Eventually, I figured out this was caused by the default text-to-speech settings of the device (under _Settings > General management > Language & input > Text-to-speech_):

1. The Samsung text-to-speech engine is selected by default. Google is available as alternative, but not selected. I've left it that way.
1. The Dutch language was not installed for the Samsung TTS engine.
    - Selecting the already available English language here (Samsung TTS) and selecting English in Osmand made TTS voice in Osmand work - in English.
    - Installing the Dutch language for Samsung TTS, which can be done from within the TTS settings window, solved my issue (with Osmand TTS language set to Dutch).

**Problem to be addressed IMHO**: the above is hard to find out for the average user. OsmAnd gives no clue about it (it just gives no voice during navigation), even though all settings in OsmAnd are correct (voice guidance activated, preferred language apparently available in OsmAnd * and selected). It would be very useful if OsmAnd does give **a message to the user** when it cannot produce TTS voice for a reason like the above, with at least a hint **where (and ideally how) to solve the problem**.

\* regarding the fact that Dutch voice navigation was already listed as an option in OsmAnd in advance: perhaps that may have to do with Dutch already being available (indeed) for the Google TTS engine. However, this engine is not selected by default on this device.

**Comment by noci2012** [comment]
In my experence the Samsung voice had issues anyway, so i selected Google Voice in the past and had no issues anymore.  (S5-mini)

**Comment by sonora** [comment]
I think this was an issue with some versions of the Samsung TTS engine not initializing properly when the language specified by an app did not match the language selected as TTS device default. Recent versions would use the device default, which will at least produce the sound, even if with false intonation. I think that's as much of a warning as can usefully be produced.

We could in fact produce prompts like 'voice language not supported', but the situation differs from device to device and it  is hard to find out if any language is just not supported by the TTS engine the user has set (but they could use another one), or if that engine just did not download required voice data upon device install.

**Comment by equaeghe** [comment]
Just to add a data point: Samsung A51 with latest updates still exhibited this issue. The described approach to installing Dutch TTS for the Samsung TTS system works. (I do not suggest that this issue be reopened.)
