### ISSUE TITLE
opening hours: comment-only value is interpreted as 24/7

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#6400]
Opening hours just consisting of a comment, e.g. `opening_hours="Mo-Fr by appointment"`, are interpreted as `24/7` by OsmAnd.

Example:
https://www.openstreetmap.org/node/4574580692

![photo_2018-12-27_10-11-16](https://user-images.githubusercontent.com/1040784/50474063-c3ce6e00-09bf-11e9-8db1-3506c27bb13e.jpg)

Instead they should probably be displayed as permanently closed, including the comment. The opening hours specification is not quite clear about this case, though.

**Comment by pebogufi** [comment]
So, what about a neutral color (black) in this case where we don't have a clear open or close situation.
Peter

**Comment by scaidermern** [comment]
Yes, this could be a reasonable solution.

**Comment by crimean** [comment]
@scaidermern you put Mo-Fr inside quotes. Please do that for comment only. I.e. Mo-Fr "by appointment".
![screenshot_1549441156](https://user-images.githubusercontent.com/4689586/52328656-6affe580-2a01-11e9-9a43-095b7ed43933.png)

**Comment by scaidermern** [comment]
I see. I've fixed it. Thanks!
