### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6402]
The "B51" road is interrupted, all roads around Dümmer are completely missing.
https://www.openstreetmap.org/search?query=52.5132528%2C8.3034979#map=12/52.5188/8.3656
![image](https://user-images.githubusercontent.com/40493090/50512046-afaa6f80-0a98-11e9-8a7b-548ed9c24b54.png)

![image](https://user-images.githubusercontent.com/40493090/50512058-b5a05080-0a98-11e9-9a7d-baefaca4aa70.png)

**Comment by scaidermern** [comment]
Could it be that you just downloaded Oldenburg and don't have a map for the eastern area (Bremen or Niedersachsen) installed?

**Comment by alyonapinchuk** [comment]
@scaidermern all the required maps for this area are installed.

**Comment by alyonapinchuk** [comment]
The data for this area is present in the map of Free and Hanseatic City of Bremen and is missing in the map of Lower Saxony.

**Comment by xmd5a2** [comment]
Fixed
