### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6403]
Galaxy J7 
Android 8.1
OsmAnd 3.2.7
The app often crashes on startup, although can open normally after trying for the 5-10th time. However, then it also crashes after scrolling through the map several seconds after opening the app. 
[Osmand_BugReport.txt](https://github.com/osmandapp/Osmand/files/2714894/Osmand_BugReport.txt)

**Comment by scaidermern** [comment]
Could this be caused by a broken map? Just a guess, but you could try deleting and redownloading your map file(s).

**Comment by MadWasp79** [comment]
@hubaishan 

> Arabic locale
> crash after pressing menu button

This bug already fixed in Osmand Nightly.

**Comment by MadWasp79** [comment]
@hubaishan 

> Arabic locale
> crash after pressing menu button

This bug already fixed in Osmand Nightly.
