### ISSUE TITLE
Wikivoyage: unhandled mark-up macros remove important information

### ISSUE THREAD

**Issue by njohnston** [osmandapp/OsmAnd#6407]
While looking at the [Wikivoyage article for Frankfurt](https://en.wikivoyage.org/wiki/Frankfurt) in OsmAnd (latest Wikivoyage file), I noticed that there are some more unhandled macros (similar to #5582 and #5996) which remove important information from the article.

For example:

![wikivoyage_macro_issue1](https://user-images.githubusercontent.com/638458/50540213-a0edb680-0b85-11e9-8449-4c0bebd4b973.jpg)

Note:

* The empty brackets. These should include the IATA code for Frankfurt airport (FRA), specified using the IATA macro: `{{IATA|FRA}}`.
* The link syntax (`[http://www.lufthansa.com Lufthansa]`) which is shown literally instead of being rendered as a link.

![wikivoyage_macro_issue2](https://user-images.githubusercontent.com/638458/50540220-be228500-0b85-11e9-9439-c9777d46da1f.jpg)

Note:

* The German name for Frankfurt South Station (Frankfurt Süd) is not shown, since the station name macro (`{{station|Frankfurt Süd(bahnhof)|u1|u2|u3|u8|s5|s6}}`) is not handled. The list of U-Bahn and S-Bahn lines serving the station is not shown either.
* The lines to take to get to the city centre from the airport are not shown, since they are specified in a macro (which renders the line numbers in coloured circles): `{{rint|frankfurt|s8}}`.
* Other station names are not shown (again, because the station macro is not handled).

Without these station and line names, the article is much less useful.

As well as adding support for these common macros, I think it would be good to include text inside unsupported macros literally. This seems better than omitting important information.

**Comment by scaidermern** [comment]
Another example: The source of article [Miroir d'eau](https://en.wikipedia.org/wiki/Miroir_d%27eau) contains `covering {{convert|3450|m2}}` which is converted to `covering 3,450 square metres (37,100 sq ft)` when viewed in the browser. OsmAnd however omits this number completely, just showing `covering `:

![photo_2020-03-04_16-10-51](https://user-images.githubusercontent.com/1040784/75894061-f7165380-5e33-11ea-9ec8-fbb372cd32ac.jpg)

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-tools/pull/374

**Comment by vshcherb** [comment]
New maps will be generated
