### ISSUE TITLE
Support restriction:forward:conditional

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6409]
Many roads in the world are like this pic.

line 1: all Vehicles can be going forward
line 2: bus and taxi can be going backward
Line 2: vehicles can u-turn all time
Line 2: all Vehicles can backward from 23:00 to 6:00
line 1: all vehicles can U-TURN from 23:00 to 6:00

and in osm, we use these tags for all roads like this. 

bus:backward=designated 
lanes:forward=2 
lanes=3 
restriction:forward:conditional=no_u_turn @ (06:00-23:00) 
taxi:backward=designated 
vehicle:backward:conditional=yes @ (23:00-06:00) 
vehicle:backward=no

I hope OsmAnd can support all these tags.

![image](https://user-images.githubusercontent.com/40493090/50547209-7c094a00-0c3e-11e9-8cfe-dffd9a1cf4f5.png)

**Comment by vshcherb** [comment]
We are going support conditional restrictions and this issue is merged into 
#1329 
#6271
