### ISSUE TITLE
Zoom center bug

### ISSUE THREAD

**Issue by contrapunctus-1** [osmandapp/Osmand#6411]
OsmAnd+ v3.2.7 from F-Droid
Android v9 (Pie)
Nokia 6.1

I've noticed this change in behavior since the last 1~2 versions of OsmAnd.

To reproduce -
1. Select a POI or long-press on a location
2. Zoom in using the button, one or more times

Earlier, preferable behavior - the zoom focuses on the POI/location, so that it stays at the center of the screen when you zoom.

Current behavior - the zoom focuses elsewhere, so the POI/location goes off the screen if you zoom enough time.

(This seems to be because the zoom focus (the crosshair?) isn't modified when selecting a POI/location anymore.)

**Comment by scaidermern** [comment]
This also applies to favorites, track points and so on.
