### ISSUE TITLE
Feature request: Continue to display added POI

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6413]
Would it be possible to keep displaying POI I've added and uploaded until the map has been updated at the beginning of the month?. 
I often add points while I travel but only upload them once I've left the area. Else I would no longer see these POIs.

**Comment by scaidermern** [comment]
This (really nice feature) has already been requested at #2890.

**Comment by vshcherb** [comment]
Indeed it is a duplicate
