### ISSUE TITLE
Please provide a build with ᴀʀᴍ⁶⁴ binaries on Google Store

### ISSUE THREAD

**Issue by ytrezq** [osmandapp/Osmand#6414]
This type of ᴄᴘᴜ become more and more common. Because I have more memory than the process can actually address, OsmAnd is constantly crashing because of the larger maps I installed.

This wouldn’t be a problem if Osmand+ would use full available ʀᴀᴍ.

**Comment by vshcherb** [comment]
Current release has ARM-v64 libs ( arm64-v8a).
