### ISSUE TITLE
`if_region_name` transforms should work with OsmAnd Live map data

### ISSUE THREAD

**Issue by bsidhom** [osmandapp/Osmand#6415]
The `if_region_name` filter as used in [`rendering_types.xml`](https://github.com/osmandapp/OsmAnd-resources/blob/344098b84cf4566ccd8a68550a15d7d86e061a03/obf_creation/rendering_types.xml#L2058) appears to match on map file names rather than underlying map metadata. As a result, rendering styles that use regions extracted this way ([for example, region-based ski piste coloring](https://github.com/osmandapp/OsmAnd-resources/blob/344098b84cf4566ccd8a68550a15d7d86e061a03/rendering_styles/skimap.render.xml#L290)) do not work as expected. Instead, behavior seems to fall back to the default (European?) style.

I noticed this while trying to test out some new map data from the White Pass ski area with OsmAnd Live. This should render the runs as green, blue, and black (as in the `us_canada_au` style), but instead renders as blue, red, black, and yellow:
![image](https://user-images.githubusercontent.com/1359900/50622750-9e13fe00-0ec4-11e9-8578-b1a276ccf180.png)

I suspect this is due to the way regions are extracted from the map names. However, I have not been able to test whether having the data reside in the main map files fixes the issue since the relevant data has not yet been published to the OsmAnd base map.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/pull/7714
