### ISSUE TITLE
Namespace "car:" instead of "service:vehicle:"

### ISSUE THREAD

**Issue by franco999** [osmandapp/OsmAnd#6420]
I recently found out from the [wiki](https://wiki.openstreetmap.org/wiki/Key:service:vehicle) and message by OSM that the prefix `"service:vehicle"` ([supported by OsmAnd](https://taginfo.openstreetmap.org/projects/osmand#tags)) is not recommended, as it causes conflicts with the label `service=*` and `highway=service`.
Instead the namespace` "car:"` is recommended and documented.

https://wiki.openstreetmap.org/wiki/Tag:shop%3Dcar
https://wiki.openstreetmap.org/wiki/Tag:shop%3Dcar_repair
https://wiki.openstreetmap.org/wiki/Key:service:vehicle

**Could this problem be solved by removing the support for `"service:vehicle"` and changing it to `"car:"` ?**

Thank you for all the hard work you do to improve the app.

**Comment by Adamant36** [comment]
There's currently a disscussion going on about it on the tagging mailing list and its disputed tag. So I wouldn't go with it yet. At least maybe wait until the disscussion there gets worked out and there's actually wiki pages for the values. Currently the just redirect to shop=car page. https://lists.openstreetmap.org/pipermail/tagging/2019-January/041773.html

Its also mentioning that the person pushing the car: tag did some shady things, like undisclosed mass tag migrations and pushing a tag that was never voted on etc, in the past with the motorcycle: tag. Which was eventually reverted (although he seems to have migrated the usages back again under the rader). See this changeset for where he was reverted for using car: tag without getting wider community support of it. https://www.openstreetmap.org/changeset/66009901

**Comment by frasty** [comment]
As adamant36 mentioned, car:* seems to have been pushed with [mass editings](https://www.openstreetmap.org/user_blocks/4743) by its author following the use of motorcyle:\*. Despite this, according to taginfo service:vehicle:* is now widely more used than car:\* thanks to ID editor using the service:veichle namespace, so osmand should support both tagging scheme and primarly support service:vehicle:*.
