### ISSUE TITLE
Do not render 'razed' or 'dismantled' keys

### ISSUE THREAD

**Issue by ignaciolep** [osmandapp/Osmand#6429]
The tags railway=razed, railway=dismantled and railway=historic are used to tag a former railway, where all evidence of the line has been completely removed and therefore should not be rendered.

Wiki:
https://wiki.openstreetmap.org/wiki/Demolished_Railway
https://wiki.openstreetmap.org/wiki/Key:razed:
https://wiki.openstreetmap.org/wiki/Tag:highway%3Drazed

Osmand reference:
https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml#L2905
https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml#L2906

**Comment by xmd5a2** [comment]
I partially agree, but in my area there are many railway=abandoned on disused peat cutting quarries. These former railways are located on the mounds that have been preserved. These mounds are often the only possible way through these places, so it is not correct to remove them completely.

**Comment by russell-phillips** [comment]
> I partially agree, but in my area there are many railway=abandoned on disused peat cutting quarries. These former railways are located on the mounds that have been preserved. These mounds are often the only possible way through these places, so it is not correct to remove them completely.

That doesn't contradict the original issue, which doesn't mention railway=abandoned. I think rendering railway=abandoned makes sense, but not the others.

Locally, OSMAnd shows an apparent railway (tagged railway=dismantled) where there is no trace of the former railway.

**Comment by aceman444** [comment]
@xmd5a2 railway=abandoned means there are traces of the railway still left, so rendering it is OK, albeit maybe not with the dashed line resembling a railway as it is now.

However, railway=razed (as the original request) must not be rendered as it means there are no traces of the railway anymore. Yes, maybe those objects shouldn't even be in the OSM data anymore, but some people like them.

OsmAnd intentionally renders 'razed' the same as 'abandoned', see https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml#L3344 , which is a clear bug and must be removed. Unless you tie it to some map option like 'show non-existent objects' , similar to how you can currently toggle proposed/planned objects or underground objects.

**Comment by IgorEliezer** [comment]
> railway=abandoned means there are traces of the railway still left, so rendering it is OK,

I agree since it is still a visible terrain feature (e.g. embankments, cut-and-fill) and some people like to explore abandoned rail structures ([video](https://www.youtube.com/watch?v=Pi-sk-kxCRE)), but it doesn't help when it's rendered in conjunction with a highway, such as rail-to-trail cycleways and roads built upon.

**Comment by NotSoImportant** [comment]
> OsmAnd intentionally renders 'razed' the same as 'abandoned', [...] which is a clear bug and must be removed

Are there any plans when to fix this issue? It is frustrating to see some railway lines on the map where nothing actually exists in reality nor can be even imagined to have been there. Map readability of the currently visbible structure is disturbed bis this.
Can we please hide "razed" or make it configurable?
Thanks

**Comment by aceman444** [comment]
I can see this already took effect in the maps of 1st Aug 2020.

**Comment by NotSoImportant** [comment]
Yes, seeing it as well now. Thanks
