### ISSUE TITLE
Add historic=heritage rendering 

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6432]
Please add heritage and historic places rendering in OsmAnd. 
https://wiki.openstreetmap.org/wiki/Key:heritage?uselang=en-US
Example: https://www.openstreetmap.org/way/662173135#map=15/49.0446/-122.8783&layers=N

**Comment by xmd5a2** [comment]
I don't think that this feature can be useful to most of users. Rendering of heritage should create unnecessary complexity in map look.
