### ISSUE TITLE
gpx/rpt not opened correctly

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6433]
![image](https://user-images.githubusercontent.com/40493090/51035171-ca5d0800-15b1-11e9-8ae8-b4a331594010.png)
![image](https://user-images.githubusercontent.com/40493090/51035178-cdf08f00-15b1-11e9-84d0-3c706798594d.png)

**Comment by vshcherb** [comment]
File is needed.

**Comment by vshcherb** [comment]
File will be provided by @dmpr0
