### ISSUE TITLE
name from man_made=bridge conflict with POI category

### ISSUE THREAD

**Issue by hakuchi** [osmandapp/Osmand#6435]
OsmAnd can not find the bridge if the name include some type of POI category.
Maybe also with other names, but I tested only `man_made=bridge`

tested with OsmAnd+ 3.2.7

Examples for OsmAnd in DE:
https://www.openstreetmap.org/way/426987138 - POI category "Burg"
https://www.openstreetmap.org/relation/6273552 - POI category "Markthalle"
https://www.openstreetmap.org/way/370838212 - Poi category "Wald"

Example for OsmAnd in IT:
https://www.openstreetmap.org/way/641026259 - POI category "Ponte"

Examples for OsmAand in NL:
https://www.openstreetmap.org/way/563515435 - POI category is "Aluminium" <- also in DE/IT/etc.
https://www.openstreetmap.org/way/481446235 - POI category is "Bos"
https://www.openstreetmap.org/way/603879436 - POI category is "Planten"

If I change to a other in-app language, these bridges can be found in search.

**Comment by vshcherb** [comment]
Should be fixed now
