### ISSUE TITLE
Routing issue at highway: Unnecessary exit and re entry

### ISSUE THREAD

**Issue by oxxm** [osmandapp/Osmand#6436]
As in title: While routing from 48.98650, 8.37320 to 48.97970, 8.37370 Osmand suggests exiting the highway, unlike osm.org. Using version 3.2.7.

![osm](https://user-images.githubusercontent.com/39620251/51061033-b03f1c00-15e9-11e9-96ec-475b21f7a458.png)

**Comment by naoliv** [comment]
Probably because the trunk has `maxspeed=70` and that link has no `maxspeed` (and thus is being assumed to be faster)

**Comment by oxxm** [comment]
OSRM is handling the situation the right way, despite the missing tag maxspeed. A lot of links are missing this tag in general.

**Comment by naoliv** [comment]
Different routers make different assumptions on missing data.

OsmAnd assumes that both `trunk` and `trunk_link` without `maxspeed` have an implicit `maxspeed=100`
https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#L609

Of course, OsmAnd could be improved but the missing data could (should) also be included in OpenStreetMap.

**Comment by oxxm** [comment]
In case of missing `maxspeed` from `trunk_link`, could OsmAnd just assume that `trunk_link` always has lower `maxspeed` than `trunk`? This might solve the issue.

**Comment by vshcherb** [comment]
It is assumed already, for some points it is not enough to make a right decision. Default speed for trunk is 100 kmh , trunk_link = 0.95 * 100 kmh - 95 kmh and there is an extra penalty for moving from trunk to trunk_link. 
So I guess trunk_link should have a maxspeed as well
