### ISSUE TITLE
No map at low zoom levels wo world overview map

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [osmandapp/Osmand#6437]
With "World overview map" (installed and activated) all works fine.
But with "World overview map" (uninstalled or deactivated) osmand shows nothing at 7-10 zoom levels:

![screenshot_20190112-092945_osmand](https://user-images.githubusercontent.com/14617699/51070128-c03c1780-164c-11e9-8ed4-24253e8c21f4.png)
![screenshot_20190112-092943_osmand](https://user-images.githubusercontent.com/14617699/51070127-c03c1780-164c-11e9-98c9-5f1827b148a4.png)
![screenshot_20190112-092940_osmand](https://user-images.githubusercontent.com/14617699/51070126-c03c1780-164c-11e9-8d47-6f03cfb7e88b.png)
![screenshot_20190112-092938_osmand](https://user-images.githubusercontent.com/14617699/51070125-bfa38100-164c-11e9-83f5-36aca932f85f.png)
![screenshot_20190112-092935_osmand](https://user-images.githubusercontent.com/14617699/51070124-bfa38100-164c-11e9-9b2e-82e607273a82.png)
![screenshot_20190112-092923_osmand](https://user-images.githubusercontent.com/14617699/51070123-bfa38100-164c-11e9-84dd-47391e641e44.png)
The last one is zoom level 11.

**Comment by sonora** [comment]
Yes, that's by design: The detailed zoom levels are in the detail maps (per country or region), while the overview zoom levels are consolidated in one (global) map file.

**Comment by pebogufi** [comment]
@c-e-p-x-u-o 
>There is nothing shown at zoom level 10 while the region map is downloaded.
You are right in this point: At zoomlevel 10 and lower regional maps DON'T EXIST. 

>I don't need the "World overview map" to see 10, 9, 8 and 7 zoom levels
In this point you are wrong.
If you want to see a map at these zoomlevels you have to install/activate "World overview map". This is the only way.
Peter

**Comment by c-e-p-x-u-o** [comment]
> At zoomlevel 10 and lower regional maps DON'T EXIST.

What does it mean "DON'T EXIST"? Map is a vector data, OSMAND just renders it. Zoom level is just a program parameter.


For high zoomlevels I need high details (regional map). This is absolutely clear. But for low zoomlevels I don't need more data. So
> If you want to see a map at these zoomlevels you have to install/activate "World overview map". This is the only way.

just the program restriction. So, please, make osmand possible to render regional map at low zoomlevels.

**Comment by pebogufi** [comment]
> > At zoomlevel 10 and lower regional maps DON'T EXIST.
> 
> What does it mean "DON'T EXIST"? Map is a vector data, OSMAND just renders it. Zoom level is just a program parameter.

DON'T EXIST means "will not be available".
I personally suppose, rendering would be too slow, because there are many details in the map, filtering is time consuming.
For me it is fine like it works now.
Peter

**Comment by c-e-p-x-u-o** [comment]
There is a cache for rendering speed up.
For me it is not fine like it works now.

Please reopen. I'll rename it feature request.

**Comment by vshcherb** [comment]
I think this feature might existed before switching between raster / vector maps on the fly, doesn't exist any more. So you need to have vector basemap.
