### ISSUE TITLE
Wrong lanes: add test A, B, C

### ISSUE THREAD

**Issue by 532910** [osmandapp/Osmand#6439]
# case A
prospect Сизова (Sizova) -> Полевая Сабировская (Polevaya Sabirovskaya)
![screenshot_20181225-154703_osmand](https://user-images.githubusercontent.com/14617699/51071775-9a703c00-1667-11e9-8424-82c349b6f5a5.png)

wrong arrow is chosen: it must be the **slight_left**, (the choosen **left** is to the Богатырский (Bogatyrsky) prospect)

```turn:lanes=left|slight_left|right```
is correct

https://www.openstreetmap.org/directions?engine=graphhopper_car&route=60.00027%2C30.26976%3B59.99661%2C30.27101#map=17/59.99840/30.27052
https://www.openstreetmap.org/way/212803162
https://www.openstreetmap.org/way/601495226

# case B
Репищева (Repisheva) street straight
![screenshot_20190112-125713_osmand](https://user-images.githubusercontent.com/14617699/51071896-a2c97680-1669-11e9-8011-f407f7306899.png)

no arrow is choosen, but the **slight_left** must be highlighted

```turn:lanes=sharp_left|slight_left|right```
is correct

https://www.openstreetmap.org/directions?engine=graphhopper_car&route=60.02733%2C30.28427%3B60.02817%2C30.28427#map=19/60.02782/30.28457
https://www.openstreetmap.org/way/335238546

# case C
Испытателей (Ispytateley) prospect -> Светлановский (Svetlanovsky) prospect via Светлановская (Svetlanovskaya) square
![screenshot_20181224-164924_osmand](https://user-images.githubusercontent.com/14617699/51071959-7d893800-166a-11e9-8e0f-e663f853d269.png)
![screenshot_20181224-165153_osmand](https://user-images.githubusercontent.com/14617699/51071961-824dec00-166a-11e9-9bea-bf61cb79b071.png)
![screenshot_20181224-165327_osmand](https://user-images.githubusercontent.com/14617699/51071965-8aa62700-166a-11e9-88fa-5471e272396e.png)

wrong arrow is chosen:
it must be the **throught** (the choosen **left** is to the Энгельса (Engelsa) prospect)

```turn:lanes=left;through|through|through|through;right|right```
```turn:lanes=left;through|through|through```
is correct

https://www.openstreetmap.org/directions?engine=graphhopper_car&route=60.00282%2C30.32269%3B60.00400%2C30.32949#map=16/60.0034/30.3260
https://www.openstreetmap.org/way/95947985
https://www.openstreetmap.org/way/380808605

**Comment by c-e-p-x-u-o** [comment]
#case D

Фёдора Абрамова (Feudor Abaramov) street -> Заречная (Zarechnaya) steet

![screenshot_20190114-093955_osmand](https://user-images.githubusercontent.com/14617699/51099303-ff02d680-17e0-11e9-840e-30f3c3c846bd.png)

no arrow is chosen, but the rithg must be highlighted

turn:lanes=reverse|right|right
is correct

https://www.openstreetmap.org/directions?engine=graphhopper_car&route=60.08110%2C30.34230%3B60.08340%2C30.34610
https://www.openstreetmap.org/way/660181954

**Comment by vshcherb** [comment]
Case A: *[not pronounced] Go ahead (+TL|+TSLL|TR) - it is not 100% correct but highlights correct lane. 
Case B: same as on screenshot - Go Ahead (TSHL|TSLL|TR)
Case C: FIXED
Case D: FIXED Now

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/84160746-d41cc080-aa6e-11ea-93ed-882b6bda6796.png)
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/84160795-e0a11900-aa6e-11ea-8fbd-bcf8c239d808.png)
![image](https://user-images.githubusercontent.com/1042025/84160805-e3037300-aa6e-11ea-995e-040fa8108de1.png)
![image](https://user-images.githubusercontent.com/1042025/84160813-e434a000-aa6e-11ea-8f2e-5e82997826f7.png)

**Comment by vshcherb** [comment]
@xmd5a2 we need to add Case C to the tests.

**Comment by vshcherb** [comment]
Case A, B - Fixed with https://github.com/osmandapp/Osmand/commit/45095ff4545f111493be95471924a1feb876528b
