### ISSUE TITLE
Transfer OsmAnd+ Settings

### ISSUE THREAD

**Issue by thg57** [osmandapp/Osmand#6441]
Hi all
I was redirected by OsmAnd Support to open an issue here.
I’m using OsmAnd+ 3.2.7 on a Samsung S8+ with Android 8.0.
The device is encrypted and not rooted.

I try to transfer all settings to another device by using adb backup / adb restore.
The command adb backup -f osmand.ab net.osmand.plus creates an empty backup file.
Backup of other apps are working correctly.

Is adb backup disabled in the AndroidManifest.xml?
Any other hints why this is not working or how I can transfer all settings?

Thanks,
Thomas

**Comment by thg57** [comment]
I used the following command:

adb backup -f osmand.ab net.osmand.plus

 

not much possibilities for typos here

 

Von: vshcherb <notifications@github.com> 
Gesendet: Samstag, 19. Januar 2019 20:23
An: osmandapp/Osmand <Osmand@noreply.github.com>
Cc: Gerber Thomas <thomas.gerber@ace.ch>; Author <author@noreply.github.com>
Betreff: Re: [osmandapp/Osmand] Transfer OsmAnd+ Settings (#6441)

 

Shouldn't be, we support standard backup mechanisms and there are only few files that should be migrated. Probably there are some typos?

**Comment by njohnston** [comment]
I have the same problem with backing up OsmAnd data on a Samsung S8+.

Other apps can be backed up fine.

As far as I can tell, backup is not disabled in the manifest.

It's a shame this doesn't work as it's really useful, particularly for such a configurable app as OsmAnd.

**Comment by pebogufi** [comment]
This is not the first time to ask for a export/import of all settings to a xml file or somethimg else.
This would be the best solution.

**Comment by Sunbird** [comment]
As of #6675 I'd love to export my settings like the navigation settings to be able to conveniently switch between versions.
The [help](https://download.osmand.net/help-online#reset_without_data_loss) should mention, that all settings are lost and not saved in "net.osmand.plus" folder.
Having uninstalled OsmAnd+ 3.3.8 I've lost all my "quick actions" as well as my custom search profiles. :'(

**Comment by dmpr0** [comment]
In the current release version. 3.6.2 you can Export profile with all settings plus the full list of Quick Actions, map sources, renderings styles, and routing files, avoid road pins.
