### ISSUE TITLE
OsmAnd freezes when tapping 

### ISSUE THREAD

**Issue by cserpell** [osmandapp/Osmand#6451]
I get OsmAnd to crash every time I try the following:

- Go to Beijing West railway station, zooms 15 or 16.
- Tap everywhere near the center of the station (for example, to add a favorite, or see description).

Just that, I don't have to do anything else. Other times that OsmAnd crashes, it writes a debug file, but in this case it seems it cannot do it, so I cannot give more details of what's happening.

I am using:

- OsmAnd version 3.2.7, released 2018-11-29
- Xiamoi Mi A1 Android 8.1.0, security patch November 1, 2018, Kernel version 3.18.71-perf-g022146d
- Complete offline maps (not just roads). Currently, I have installed: Chile, China, Texas Dallas, World overview map
- Plugins: Online maps (not actually using it, but it is active), Contour Lines (the same), Audio/video notes, OSM editing. I also tried activating OsmAnd development for more info, but it crashes the same.

Maybe I can help further if you point me something.

**Comment by vshcherb** [comment]
This issue is fixed and it was related to Combined maps (non-region ones) and public transport. Coming next release in early February.

**Comment by cserpell** [comment]
Thanks for you answer. I will gladly wait.
