### ISSUE TITLE
Ruler is not shown in landscape mode during route preparation

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6454]
![image](https://user-images.githubusercontent.com/40493090/51399563-eb43d100-1b4e-11e9-8aa3-3164b9f19173.png)
![image](https://user-images.githubusercontent.com/40493090/51399572-ef6fee80-1b4e-11e9-994b-13ba25cae593.png)

**Comment by MadWasp79** [comment]
Closed with https://github.com/osmandapp/Osmand/commit/be33d0cfc80b5c62611e183bc0236aad875a72da
