### ISSUE TITLE
Basemap: Highway exhibits huge gaps and even vanishes with different zoom levels

### ISSUE THREAD

**Issue by Aiurek** [osmandapp/Osmand#6456]
Lenovo Moto G4 plus, Android 7.0
OsmAnd+ 3.2.7, released 2018-11-29
May style: OsmAnd
Map: Tanzania (Jan 1, 2019) (Standard map + Contour lines + Hillshades)

Throughout Tanzania the highways are illustrated with huge gaps, whereby the gaps change and finally vanish with increasing zoom level:

![picture3](https://user-images.githubusercontent.com/27865200/51411851-b5f8ac80-1b69-11e9-82d7-5b1d6365f65d.png)

 
 
Sometimes the highways vanish optically if the zoom level is increased:

![picture2](https://user-images.githubusercontent.com/27865200/51411731-3bc82800-1b69-11e9-948c-354f1f49d618.png)

**Comment by Aiurek** [comment]
Lenovo Moto G4 plus, Android 7.0
OsmAnd+ 3.4.xx, before the play store release 2019-08-03
May style: OsmAnd
Map: New Aquitaine (June 1, 2019)

Highways and secondaries exhibiting gaps

https://www.openstreetmap.org/#map=11/45.8781/-1.1721

![Bild8](https://user-images.githubusercontent.com/27865200/62705719-43a8c600-b9ee-11e9-9199-9d725b4c48c4.jpg)

**Comment by sjkosij** [comment]
Hi all,

I am also experiencing a similar issue for the Australia and New Zealand maps. At lower zoom levels, some of the roads do not connect properly. When zooming in (a few zoom levels), the roads connect. Example screenshots - gaps indicated by a red circle:

![SmartSelect_20190812-151529_OsmAnd](https://user-images.githubusercontent.com/54013896/63128684-df42c380-bff8-11e9-8ac5-fa7a049372c6.jpg)

![SmartSelect_20190812-132020_OsmAnd](https://user-images.githubusercontent.com/54013896/63128694-e5d13b00-bff8-11e9-9f01-954c2fbcb991.jpg)

App/device details:
Samsung Galaxy S7 Edge, Android 8.0
Osmand Unlimited v3.4.6 (2019-08-03)

Thank you

**Comment by vshcherb** [comment]
New mini basemap (delete normal basemap) + new maps don't have that problem.

Normal basemap is going to be released next weeks.
