### ISSUE TITLE
Could not calculate route: Starting point too far from nearest road

### ISSUE THREAD

**Issue by Aiurek** [osmandapp/Osmand#6457]
Lenovo Moto G4 plus, Android 7.0
OsmAnd+ 3.2.7, released 2018-11-29
May style: OsmAnd
Map: Tanzania (Jan 1, 2019) (Standard map + Contour lines + Hillshades)
Navigation service: OsmAnd (offline)

It wasn't possible to use navigation at all around Singida in Tanzania. Tried different destinations around Singida, but unfortunately I ended up receiving the same error message over and over.

![picture4](https://user-images.githubusercontent.com/27865200/51412098-c52c2a00-1b6a-11e9-8cec-2a31346b3351.png)

**Comment by xmd5a2** [comment]
Already fixed https://github.com/osmandapp/Osmand/issues/6458
Checked with April maps
