### ISSUE TITLE
Break down of confusing error message: Fast route calculation failed

### ISSUE THREAD

**Issue by Aiurek** [osmandapp/Osmand#6458]
Lenovo Moto G4 plus, Android 7.0
OsmAnd+ 3.2.7, released 2018-11-29
May style: OsmAnd
Map: Tanzania (Jan 1, 2019) (Standard map + Contour lines + Hillshades)
Navigation service: OsmAnd (offline)

Finally, I ended up receiving this weird error toast message (#2573). 
It might be pretty confusing to users.
Thus, I suggest to break this one down to "Fast route calculation failed, fallback to slow calculation".

![picture6](https://user-images.githubusercontent.com/27865200/51412658-88f9c900-1b6c-11e9-8683-bb138eb93d5a.png)

**Comment by vshcherb** [comment]
This indicates internal error, we would like to get coordinates so we can reproduce that error and fix it.

**Comment by Aiurek** [comment]
I was travelling from Mwanza to Arusha and tried to establish a proper routing several times with different destinations and intermediate destinations. I ended up receiving different error messages: also "Could not calculate route: Starting point too far from nearest road" #6457.

The following points are just rough estimations of the route illustrated in the previous comment.

From:
Nyezegi Bus Station
Near T4
Location: geo:-2.5945685,32.924694?z=17
https://osmand.net/go?lat=-2.5945685&lon=32.924694&z=17

Intermediate destination:
No address determined
Location: geo:-4.5983267,34.62809?z=10
https://osmand.net/go?lat=-4.5983267&lon=34.62809&z=10

To:
Arusha
Location: geo:-3.3696783,36.688072?z=12
https://osmand.net/go?lat=-3.3696783&lon=36.688072&z=12

**Comment by xmd5a2** [comment]
SEVERE: Error occurred
java.lang.NullPointerException
	at net.osmand.router.PrecalculatedRouteDirection.build(PrecalculatedRouteDirection.java:78)
	at net.osmand.router.RoutePlannerFrontEnd.searchRoute(RoutePlannerFrontEnd.java:187)
	at net.osmand.swing.MapRouterLayer.selfRoute(MapRouterLayer.java:730)
	at net.osmand.swing.MapRouterLayer$17.run(MapRouterLayer.java:351)

**Comment by xmd5a2** [comment]
Fixed. Please re-download map of Tanzania.

**Comment by Aiurek** [comment]
Thanks!
Just now I deleted the Tanzania map, re-dowloaded it and tried the above mentioned route.
Unfortunately, it seems to be still there + an additional toast message, which appears immediately after the first one vanished.
Whereby, I'm currently still using the latest play store build (OsmAnd+ 3.2.7, released 2018-11-29).

![bild1](https://user-images.githubusercontent.com/27865200/52645040-46fc4280-2ee0-11e9-8461-20944daaef93.jpg)
Left toast message appears first

**Comment by vshcherb** [comment]
We really need to reproduce and fix issue in the code, there is NullPointerException somewhere. So regenerating map doesn't sound as a solution!

**Comment by utack** [comment]
Is fast route calculation native code?

**Comment by vshcherb** [comment]
Yes it is a native code.

**Comment by vshcherb** [comment]
Fixed

**Comment by utack** [comment]
Thank you  
Which commit fixed it?

**Comment by vshcherb** [comment]
As I understand it was fixed with another bug this release.https://github.com/osmandapp/Osmand/issues/6599
