### ISSUE TITLE
deactivated favourites groupes are also visible

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#6462]
Some of my favourites groupes are marked as deactived, but all groups are visible.
File favourites.gpx is ok, the deactivated groupes are marked as hidden.
Peter
version 3.3.0#26585

**Comment by pebogufi** [comment]
Buggy version:
- On opening My places / favourites all groups have coloured stars, activated and DEactivated
- on looking on map all favourites are visible with its colours, activated and DEactivated

After install old version (3.3.0#26384) which works as expected:
- On opening My places / favourites only activated groups have coloured stars,  DEactivated groups are sorted behind them with grey stars
- on looking on map only activated favourites are visible with its colours,  DEactivated are not visible

**Comment by MadWasp79** [comment]
@pebogufi do you still encounter this bug in newer versions? In 3.3.0#26645 for example?

**Comment by pebogufi** [comment]
In  3.3.0#26645. it is reproducable.

**Comment by pebogufi** [comment]
...and also in 26656

**Comment by MadWasp79** [comment]
@pebogufi I wasn't able to reproduce this bug, so I'll ask you to provide additional data, if possible. Maybe there is something particular about your favorite points/points groups? Unusual names?  Maybe you are using those group as map markers? (not that it helped me to reproduce this bug so far, but every bit of info will help)

**Comment by MadWasp79** [comment]
@pebogufi glad to inform you, that yes, its definitely helped. ) Bug found and fixed. Think this will be added in next nightly build. 
Closed with https://github.com/osmandapp/Osmand/commit/db5164163c6d3c076f436db050927839b631a2cf
