### ISSUE TITLE
Delete selected favorites bug

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#6465]
Try to delete the group of favorites by check group checkbox, then unselect a few points all group will be deleted anyway.
![screenshot_20190122-102828](https://user-images.githubusercontent.com/9365308/51521981-cdb58680-1e30-11e9-8ce6-3b42d1225ff1.png)
![screenshot_20190122-102833](https://user-images.githubusercontent.com/9365308/51521982-cdb58680-1e30-11e9-93c2-ce9ba440e1e7.png)
![screenshot_20190122-102843](https://user-images.githubusercontent.com/9365308/51521983-cdb58680-1e30-11e9-92d6-b664c83fd5f6.png)
![screenshot_20190122-102848](https://user-images.githubusercontent.com/9365308/51521984-cdb58680-1e30-11e9-952b-7c420352e1e9.png)

**Comment by MadWasp79** [comment]
Closed with https://github.com/osmandapp/Osmand/commit/6ccc7b50970072eb2a5bf73caa6f64bce3358cbc
