### ISSUE TITLE
Two AIDL items in the drawer

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#6466]
In the latest nightly, I have two OsmAnd Telegram items.
![photo_2019-01-22 10 32 35](https://user-images.githubusercontent.com/9365308/51522074-0fdec800-1e31-11e9-9334-5a7a7c4082a3.jpeg)

**Comment by MadWasp79** [comment]
closed with https://github.com/osmandapp/Osmand/commit/07f839d4081a4a81beef71fd50901f1d9ae53496

**Comment by MadWasp79** [comment]
closed with  https://github.com/osmandapp/Osmand/commit/f33f4eed5f516792dfac5f436f4aea2503cb3a66
