### ISSUE TITLE
Navigation display

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6477]
After the route has been calculated, the map zooms to a scale of 200km. This happens with different routes but only in the landscape mode; reinstallation did not help. 
Samsung Galaxy Tab A2016Modell SM-T585Android 8.1.0 
![image](https://user-images.githubusercontent.com/40493090/51798433-da642100-221a-11e9-9f34-28da07e4a5dc.png)

**Comment by vshcherb** [comment]
Fixed
