### ISSUE TITLE
Private parking shows "Change delete"

### ISSUE THREAD

**Issue by Danysan1** [osmandapp/Osmand#6480]
This is a bug report for OsmAnd Android 3.2.7 with OsmAnd Live enabled.
When selecting an amenity=parking with access=private I would expect getting "private parking" in the details. Instead I get "Change delete", both in the device language (italian) ...

![screenshot_20190127-224318](https://user-images.githubusercontent.com/8406735/51807342-f18c2880-2285-11e9-9aa9-469c9f03df04.jpg)

... and in english ...

![screenshot_20190127-224611](https://user-images.githubusercontent.com/8406735/51807347-fe108100-2285-11e9-8ff1-5ae0a9a88578.jpg)

The parking in the screenshots is https://osmand.net/go.html?lat=44.385227&lon=11.732669&z=18 but the problem happens in any private parking.

**Comment by scaidermern** [comment]
Interesting. For me private parkings don't have any name or description at all, which is also weird:

![img_20190128_192300](https://user-images.githubusercontent.com/1040784/51857298-2786e680-2332-11e9-8222-ce51401d677e.jpg)

**Comment by xmd5a2** [comment]
@Danysan1 Do you have a changed rendering style or standard on your device?

**Comment by Danysan1** [comment]
@xmd5a2 I am using the default style, however the problem happens also in all the styles that let you select parkings

**Comment by xmd5a2** [comment]
It seems that this is an bug in overpass. It does not returns all the data for a request regarding changes to this parking lot. We can do nothing about it.

**Comment by scaidermern** [comment]
The same just happened for [changeset 67459249](https://www.openstreetmap.org/changeset/67459249). For example the caravan site at [way 194297400](https://www.openstreetmap.org/way/194297400) is now shown with old data and with a "change delete" entry.

Somehow I'm not quite convinced that this is really the fault of Overpass API. Look for example at [achavi](https://nrenner.github.io/achavi/?changeset=67459249) which uses augmented diffs and is able to show the changes correctly.

**Comment by vshcherb** [comment]
The bug was definitely in Overpass and it is related to synchronization issue, so overpass can heal itself overtime but the immediate exports after 2-3 minutes could be broken.
Though there is a second issue here cause it is not clear how "Change delete" is displayed at all. It should be a special UI I guess to display "Deleted" POI object

**Comment by scaidermern** [comment]
> The bug was definitely in Overpass and it is related to synchronization issue, so overpass can heal itself overtime but the immediate exports after 2-3 minutes could be broken.

However it looks like OsmAnd "keeps" the bug. It still shows old information and "change delete" after several days.

**Comment by vshcherb** [comment]
OsmAnd won't be able to update the bug cause the maps are already generated based on the wrong snapshot of the overpass. We have historical exports and they show that overpass osc file was different then now. I believe this issue is a mixture of 2 different issues and that's why it causes confusion

**Comment by scaidermern** [comment]
I see. Are the upstream developers aware of this bug in Overpass?

**Comment by vshcherb** [comment]
As I talked to Overpass developers, they  definitely know about it on the other hand I put a bigger delay to let Overpass heal itself
