### ISSUE TITLE
Track "Analyze on map" disappears after switching apps

### ISSUE THREAD

**Issue by DFyson** [osmandapp/Osmand#6484]
Analyze a track on the map, switch apps, then switch back to OsmAnd. The track and analysis tool disappeared and need to be reloaded.

This is slightly similar to #2271 in which the map auto-rotates back to North-up after switching apps.

**Comment by seahorse41** [comment]
It also disappears when Auto-rotate is on, and the device is rotated. Therefore any change in orientation then redraws the display without Analyze subroutine running. 
Workaround is to turn off auto-rotation first, but that usually only gets remembered after losing the analysis in progress.
