### ISSUE TITLE
Remove the close button for the layer transparency seekbar

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#6485]
Many users complain that this button is redundant and it is easy to press it accidentally.
![image](https://user-images.githubusercontent.com/20681525/51968429-9707ed80-247a-11e9-9808-5434a14599b9.png)

**Comment by as4tik** [comment]
+

**Comment by MadWasp79** [comment]
Closed with https://github.com/osmandapp/Osmand/commit/90e14cc691f1ca28ef27b137cb7650a209b079fb

**Comment by dmpr0** [comment]
New issue with this.
Tap on the switch at Overlay/Underlay item, and then in the dialog with available map tap "Cancel", seekbar will appear on the screen, without the option to disable it.

**Comment by dmpr0** [comment]
In the Overlay map, it still reproduces.
