### ISSUE TITLE
Offline Inv/Geocode code

### ISSUE THREAD

**Issue by lhorus** [osmandapp/Osmand#6487]
I've been considering creating my own geocoder and inverse geocoder, for mobile offline uses, out of curiosity, as I've been thinking how these work for quite some time now.

All I could find for sources, are CartoDB's implementation (but they do not provide the tool to generate their NutigeoDB format databases, so the whole process becomes quite useless) and OsmAnd's, which seems to be fully open source.

I know this sounds lazy but I've been digging this for quite some time now with no success: where is the code for Osmand's offline rev/geocoder? Does it use any particular format, or does it simply scan through the .mbtile?

Thanks in advance and I apologize for the apparently lazy question!

**Comment by vshcherb** [comment]
Please check GeocodingUtilities in OsmAnd though it requires to have OsmAnd files.
