### ISSUE TITLE
Add POI category for park and ride (P+R)

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#6489]
Looks like there is no category for [park and ride (P+R)](https://en.wikipedia.org/wiki/Park_and_ride), i.e. `amenity=parking` in combination with [`park_ride=*`](https://taginfo.openstreetmap.org/keys/?key=park_ride#values) (except for `park_ride=no`).

**Comment by scaidermern** [comment]
Thanks!

Does this only include `park_ride=yes`? There are many objects tagged with `park_ride=train`, `park_ride=bus` and similar values.

**Comment by xmd5a2** [comment]
https://github.com/osmandapp/OsmAnd-resources/commit/87afb3ec7d0032e214479fc759dbed9ca5cf866a

**Comment by scaidermern** [comment]
Thanks again :)
