### ISSUE TITLE
Osmand fails to find the shortest route

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#6490]
Using OsmAnd~ 3.3.0 #26668m (released on 31-1-2019)

It fails to find the shortest route.
![failstofindthedirectroute](https://user-images.githubusercontent.com/9047168/52061546-8cda1200-2594-11e9-8fad-f614e36e4319.jpg)

It should have headed south from starting point, and taken sharp let to go along a service road that is parallel to the orange-colored double road in 2 o'clock direction, and then turn southward. Instead, it turns North and goes through a much longer loop.

The coordinates of the starting point are-
12 55' 26.31" N
77 40' 8.832" E

**Comment by scaidermern** [comment]
Probably the service road has a high penalty. It is a really long service road.

The route on openstreetmap.org:
https://www.openstreetmap.org/directions?engine=graphhopper_car&route=12.9237%2C77.6696%3B12.9163%2C77.6678#map=16/12.9210/77.6706&layers=N

**Comment by raindropsfromsky** [comment]
No this is a daily route for me, and I am the mapper. So I have all the
facts.

The service road does not have any restriction, and it is short.

**Comment by raindropsfromsky** [comment]
![serviceroadavailability](https://user-images.githubusercontent.com/9047168/52065967-a0d64180-259d-11e9-8cfd-c324f0dc947b.jpg)

I selected a nearby destination in the same route, and OsmAnd selected the correct route, along the service road. So why did it not select the same path in the case above?

**Comment by raindropsfromsky** [comment]
Oh! so this is not to turn off the display?

BTW I was not using the pedestrian mode. I always use BROWSE and CAR modes.
Then this control should not have appeared on the screen at all.

**Comment by xmd5a2** [comment]
Can't reproduce with latest map. Maybe map data has changed recently?
![screenshot from 2019-02-11 11-28-01](https://user-images.githubusercontent.com/5829014/52552127-2fde2780-2df0-11e9-96cd-212d0d460602.png)

**Comment by raindropsfromsky** [comment]
No it is just the same for the last few years.
