### ISSUE TITLE
Elevation shown even if the "Use elevation" button is turned off

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#6491]
Using Osmand~ 3.3.0 26668 on Asus ZenFone 5z running on Android 8.0.0.

![elevationyesorno](https://user-images.githubusercontent.com/9047168/52063122-f90a4500-2597-11e9-81cf-654c331e0da4.jpg)
As the screenshot shows, the use elevation is off.
But still the display shows elevation profile for the route.

**Comment by njohnston** [comment]
From what I can tell, in pedestrian mode at least, "Use elevation" just means that elevation data will be used to calculate a more accurate time for the route using Naismith's rule or similar.

See #4804 and #4455.

**Comment by vshcherb** [comment]
Use Elevation will be renamed cause we want to introduce new options
