### ISSUE TITLE
Route editor has redundent display

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#6492]
Using Osmand~ 3.3.0 26668 on Asus ZenFone 5z running on Android 8.0.0.

when we edit the route, the GUI shows two nearly identical displays.
![doubledisplay](https://user-images.githubusercontent.com/9047168/52063285-556d6480-2598-11e9-93c0-a18a5317792f.jpg)

As can be seen, all the route points are duplicated.
This can be avoided by having just one display.

**Comment by vshcherb** [comment]
Merged into #6655
