### ISSUE TITLE
Migrar Codigo a Android Studio

### ISSUE THREAD

**Issue by freddycalderonp1990** [osmandapp/Osmand#6496]
Hola comunidad de Osmand, Soy el Ing. Freddy Calderon Pazmiño alguien me podría ayudar o indicar los pasos para migrar el código fuente a Android Studio, o que IDE me recomiendan para poder compilar el código sin problemas de antemano Gracias. 

Hello, community of Osmand, I am Mr. Freddy Calderon Pazmiño someone could help me or indicate the steps to migrate the source code to Android Studio, or that IDE recommend me to compile the code without problems in advance Thanks.

**Comment by vshcherb** [comment]
For future refs: Please check - https://osmand.net/help-online#dev-environment
