### ISSUE TITLE
POI with landuse=winter_sports not displaying POI tag information

### ISSUE THREAD

**Issue by DFyson** [osmandapp/Osmand#6497]
POI's using the [landuse=winter_sports](https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dwinter_sports) do not show information tags other than the name.
For example way [475720359](https://www.openstreetmap.org/way/475720359) has phone number, website, etc. However this information is missing in OsmAnd as seen in screenshot below.
<img src="https://user-images.githubusercontent.com/12941728/52090721-2ba84380-2580-11e9-9a03-da430b53cc8b.png" width="200">
Tested on latest OsmAnd+ and todays nightly version.

**Comment by scaidermern** [comment]
Same problem for this tourism=camp_site:

Tapping on it on the map, no details visible:
![photo_2019-06-05_14-58-57](https://user-images.githubusercontent.com/1040784/58958111-78a45c80-87a2-11e9-9ca1-165cb5631036.jpg)

Searching for it and tapping on the search results, full details visible:
![photo_2019-06-05_14-59-01](https://user-images.githubusercontent.com/1040784/58958112-793cf300-87a2-11e9-94d0-21c40fd304ce.jpg)

It is the same [way ID 28180565](https://www.openstreetmap.org/way/28180565) so really the same object (although OsmAnd shows a slightly different position).

Interestingly this doesn't happen for all camp sites.

**Comment by scaidermern** [comment]
@xmd5a2 Do you know if this could be caused by the same problem or are they two distinct bugs? In the latter case I will open a separate issue.

**Comment by xmd5a2** [comment]
@scaidermern bugs are identical and there is no need to open new issues

**Comment by carstenhag** [comment]
Would be great to get this fixed, or at least know what values make this happen

**Comment by vshcherb** [comment]
It is a difficult issue to address so the timeline is very unclear

**Comment by pebogufi** [comment]
I want to describe two different situations:
- I open a search, then "show on map" then click on orange circle which is result of search. 
The poi description is OK !
![Identify from orange circle from search result](https://user-images.githubusercontent.com/18628183/67634533-a1e29800-f8bd-11e9-9361-e918e5c064dd.jpg)


- I click on the brown symbol "musem" which is in the map.
The poi name is correct identified, but the other poi info is missing.
Both examples refer to the same object.
![identify from brown museum circle](https://user-images.githubusercontent.com/18628183/67634572-2f25ec80-f8be-11e9-9e9d-cbd5b1299eaa.jpg)

**Comment by scaidermern** [comment]
This is the same behavior as described by me in the second comment

**Comment by MadWasp79** [comment]
We fixed issues with misaligned POIs (like in the first comment from @scaidermern), but it seems that the original issue with winter_sports is still there. Will post updates.

**Comment by MadWasp79** [comment]
fixed.
