### ISSUE TITLE
While calculating the route between known points (favorites, points on map), don't wait for GPS availability

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#6498]
Suppose someone gives a paper map, and asks us to draw a route between two specific points on the map. For that, we don't need to know our current location.

But this is what happens with OsmAnd: It always waits for GPS availability before calculating the route, even when the current location is NOT involved. The problem is, GPS is not available sometimes. This prevents us from planning the trip.

For example, I am at office, and I want to plan a trip from my home to a vacation spot. For this trip planning, the current location is irrelevant.

OsmAnd has the entire map **offline**. So it does not need to know the current location to fetch the map. So, if the route does not include the current position, OsmAnd should be able to plot the entire route without knowing its current position.

**Comment by vshcherb** [comment]
Could not reproduce it as well, may be a mistake
