### ISSUE TITLE
Time scale in track analysis.

### ISSUE THREAD

**Issue by as4tik** [osmandapp/Osmand#6499]
Hi. OsmAnd provides a lot of great features. In track analysis as well. 

There is now two scale for track: 
-time from the begin and 
-distance from the begin
![image](https://user-images.githubusercontent.com/27757437/52118238-da9f5a80-2626-11e9-9d44-54f0846984f2.png)

This request is to make the third scale. 
It is time scale as well. 
Not time from the begin of track, but time stamp from the points. Time scale is providing calculated time from the begin track (from the first point in track) to the end of it.
What this request for is to have raw timestamp from points in scale. Just in time of the day, but not from begin of track. At least UTC, in the best case  in local time of the user taken from UTC+time zone shift. 
For example UTC time of point is 14:15, local time is +5, scale time 19:15 for the particular point. 

![image](https://user-images.githubusercontent.com/27757437/52119106-1c310500-2629-11e9-9eb0-3d0b1161b948.png)

The main idea if the particular point is selected to know when (by day time) the device has saved the point, but not how many time past from the begin of tracking.

EN name of scale could be "Time stamp" or "Time of the day". RU name could be "Время дня".

So in total the list of scales could be: 
EN "Time stamp / Time from begin (or just time) / Distance
RU "Время дня / Время от начала (или просто время) / Расстояние"

The proposal is made to make time in particular point more formal and obvious on stage of analysis of tracks from competitions.

Best regards. Ilja.

**Comment by njohnston** [comment]
Great idea. @vshcherb: since the timestamps in the tracks themselves are always in UTC, would it be possible to allow the user to specify the timezone for this? For example, if I record a track in UTC+0800, but then return to UTC, it would be good to see the times in the original time zone.

**Comment by MadWasp79** [comment]
Closed with https://github.com/osmandapp/Osmand/pull/6585
