### ISSUE TITLE
(-) is not recognized in GPS format input

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6505]
Recently, the (-) for West Lon in format input, e.g. 37:59:16 -0:39:18 no longer accepted, you land accordingly in East. However, the direct display of a GPS point on the map is displayed correctly with (-)!
The format 37.9872 -0.65483 works correctly.

**Comment by vshcherb** [comment]
The number "-0" is treated as "0" so it creates an error in our parsing

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/pull/6627/commits
