### ISSUE TITLE
osrm updates

### ISSUE THREAD

**Issue by ADepic** [osmandapp/Osmand#6506]
osrm now supports cycling and walking, pleas add support for osrm navigation in these modes.

also, sometimes osrm returns "Calculated route is empty"

**Comment by OpenSourceForEver** [comment]
https://github.com/osmandapp/Osmand/issues/6081

**Comment by ADepic** [comment]
Osrm still works fine a lot of times, I don't know why vscherb just closed that issue saying osrm was removed. A bit more work done on it, and you have a perfect online navigation, since it now supports walking, cycling and driving. Heck, osrm on their website also give alternative routes. I've seen that fails to calculate route on osrm's website as well. On their website half the time it doesn't calculate routes

**Comment by scaidermern** [comment]
It looks like the future of OSRM is currently unclear, see https://github.com/Project-OSRM/osrm-backend/issues/5209

**Comment by vshcherb** [comment]
Supporting Online services causing quite a lot of trouble and also usually it is paid feature cause backend services need to maintain all these requests. We are planning to have OsmAnd online routing service based on OSRM on the future so the situation will be more reliable.
As of today it is advised to calculate route and download as GPX file and use it for navigation.

**Comment by scaidermern** [comment]
> As of today it is advised to calculate route and download as GPX file and use it for navigation.

This is not really an option unless #3908 gets implemented. With the current implementation you are very likely to miss important motorway exits due to missing announcements. Also there will be no speed limits, no lane guidance and so on.
