### ISSUE TITLE
Quick Action: Incorrect position when creating "My places" point

### ISSUE THREAD

**Issue by Prusaker** [osmandapp/Osmand#6508]
If create "My places" point via fast action, it appears in other place.
For example. I try to create point at this place:
![screenshot_2019-02-02-23-36-42](https://user-images.githubusercontent.com/32092837/52169170-e54c1380-273c-11e9-893f-33739ec940e9.png)

But the point created in the other place:
![screenshot_2019-02-02-23-36-59](https://user-images.githubusercontent.com/32092837/52169179-12002b00-273d-11e9-8d7b-961ccc127cbb.png)

Also, when trying to build any route, the program ends with an error:
![screenshot_2019-02-02-23-57-06](https://user-images.githubusercontent.com/32092837/52169285-4cb69300-273e-11e9-847d-3a771071d089.png)

This is observed in the version OsmAnd Nightly 3.3.0#23226d and in all builds nearly for a last week.
The oldest builds (tested at OsmAnd Nightly 3.3.0#23118d and more oldest) works correctly.

**Comment by pebogufi** [comment]
The position is created from center of screen.

**Comment by francois2metz** [comment]
I managed to fix this issue in 2ef320548e7112d0060c03a1b3bb36a1193b9873. The regression happened in 713a3b9d4bf84abb94cfc09c22fc411e3bd779c5. I still don't know the reasons behind this. Still investigating...
