### ISSUE TITLE
Issues with Dutch voice guidance

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6509]
Voice guidance works well with other languages, but Dutch voice guidance is more a mix of English and practically unintelligible Dutch.

**Comment by sonora** [comment]
This usually results from a mismatch of the language file selected in OsmAnd and the engine language selected in your Android (device)  TTS setting. Setting BOTH to Dutch should correct the situation?

**Comment by vshcherb** [comment]
Yes, I've tested so far and it is good. The issue just remained open as it was overlooked.
