### ISSUE TITLE
Add OpenFlightMaps overlay

### ISSUE THREAD

**Issue by svenstaro** [osmandapp/OsmAnd#6510]
I think it would be really neat if this app had support for overlaying information from [OpenFlightMaps](https://www.openflightmaps.org).

**Comment by lpirl** [comment]
👍 

One "simply" needs to find the right parameters for the online maps plugin. We could then [add the map to the online map plugin manually](https://osmand.net/features/online-maps-plugin) or add the tile source to the list of predefined tile sources. The latter has been requested (osmandapp/osmandapp.github.io#185) to be done for [OpenAIP](http://openaip.net/) aeronautical maps, which could be of interest here.

I tried to add the tile URL of OpenFlightMaps (`
https://nwy-tiles-api.prod.newaydata.com/tiles/{0}/{1}/{2}.png?path=latest/aero/latest`) to the online maps plugin (Pseudo-Mercator) but the tiles don't fit:

<img src="https://user-images.githubusercontent.com/1379476/127784295-e9da22bc-ef61-40f9-8947-79630eecd8af.png" height="500em">

The tiles are from roughly the correct area but shuffled a bit. Maybe anyone with more experiences has a hint?

**Comment by lpirl** [comment]
After having learned that there is the file `.metainfo` where more parameters can be set, I found a working combination (see osmandapp/osmandapp.github.io#186). Adding OpenFlightMaps manually cannot be achieved via the UI only.

**Comment by vshcherb** [comment]
That bug with supporting hd tiles was fixed actually in latest versions
