### ISSUE TITLE
Missed short routing

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#6512]
As shown below, OsmAnd fails to find the shortest path in the route.
![wrongroute](https://user-images.githubusercontent.com/9047168/52212464-8c05f080-28b2-11e9-8f52-fc47f025473b.jpg)

The close up (see below) shows how OsmAnd fails to follow the link.
![wrongroutecloseup](https://user-images.githubusercontent.com/9047168/52212475-90caa480-28b2-11e9-876a-2c5eee46080b.jpg)

Instead of taking the link, it take a 1 km detour, and then takes a U-turn to come back and follow the right path.

**Comment by scaidermern** [comment]
Next time please provide coordinates or a link to the area.

Seems to be this route: https://www.openstreetmap.org/directions?engine=graphhopper_car&route=12.96691%2C77.62307%3B12.96897%2C77.61979#map=19/12.96785/77.62144

**Comment by raindropsfromsky** [comment]
Oops. Will do in future.

You have shown the desired path correctly. (OsmAnd does not follow that.)

**Comment by xmd5a2** [comment]
![Screenshot from 2019-04-04 14-34-01](https://user-images.githubusercontent.com/5829014/55552693-bcb5ab00-56e6-11e9-8f3b-dd6d2eb67abd.png)
Not reproducible any more
