### ISSUE TITLE
Preview of the route is not intuitive in the latest design

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#6513]
When we tap on the **Details** button in the **Route Editor** dialog, OsmAnd is supposed to show us the spot on the route. 

In the past versions, this was implemented very well. We could view the route segment by segment, by pressing the < and > buttons. OsmAnd used to pan+zoom smoothly to show that spot. Thus the viewer's continuity was maintained.

However, the present version does not serve this purpose very well:
When we press the **Details** button, OsmAnd shows the entire route in a very small portion of the screen. Most of the screen is occupied by the dialog itself, as shown below.
![screenshot_20190204-230110](https://user-images.githubusercontent.com/9047168/52225687-02b1e680-28d1-11e9-9440-7e1da986ac88.jpg)

The view is so cluttered, and zoomed out that we cannot have a good look at the spot at all.

Worse, OsmAnd replaces the **maneuver list** (Details view) with the standard **Route Editor**. So if we want to tap several points on the route and check them out on the map, every time we have to press the **Details** button and trigger the Details view once again.

The < and > buttons are missing. Therefore we are unable to step through the route (segment-by-segment).

**Desired:**

1. In the route preview mode, the **Route editor** GUI should not be shown. Maximize the screen space, and zoom in.
2. Reintroduce the < and > buttons.

**Comment by dmpr0** [comment]
Hello! Thank you for the feedback. 
Route details screen is not ready yet, it will come back with new features.
