### ISSUE TITLE
Quick Action: Show/Hide track on the map

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#6515]
Add action to show/hide tracks: all tracks or selected by the user.

**Comment by as4tik** [comment]
Better for pre selected by user. The idea is to have the same list of tracks on the map after switch on as before switch off.

**Comment by pgavrilov** [comment]
Main idea (it's mine) is to have quick ability to check road properties hided behind GPX track line.

Quick Action button would be a good case.

**Comment by vshcherb** [comment]
To simplify development and UX, the action should just enable previously disabled tracks.  Hide obviously should disabled tracks.

**Comment by MadWasp79** [comment]
Closed with https://github.com/osmandapp/Osmand/pull/6573

**Comment by MadWasp79** [comment]
syncronize checkboxes in "Show GPX data" dialog with actually selected tracks

**Comment by MadWasp79** [comment]
Closed with https://github.com/osmandapp/Osmand/pull/6905
