### ISSUE TITLE
Quick Action "Change Overlay" mode "without dialog" - always switch to first layer from list

### ISSUE THREAD

**Issue by pgavrilov** [osmandapp/Osmand#6516]
Device: Xiaomi Redmi 3S, Android 6.0.1, MIUI Global 10.2
Osmand+ 3.2.7, 2018-11-29
Offline vector maps set as main source.
Offline raster file set as overlay source.

Added QuickAction button with action "Change overlay".
Overlay modes list:
- No overlay
- Raster file

If I set mode "without dialog", click on this button always set overlay to "No Overlay" mode.
If I swap modes in list, click on this button always set overlay to "Raster file" mode.

If I set mode "with dialog", all works fine.
____________________

Russian:
В меню QuickAction создана кнопка "Сменить карту покрытия".
В настройках кнопки указано первым пунктом "Нет покрытия", а вторым выбран растровый файл.
Если в настройках кнопки выбрать "Без промежуточного диалога", то щелчок по кнопке всегда включает первый вариант из списка. Циклического перебора вариантов не происходит. Если поменять варианты списка местами, тоже выбирается первый вариант (уже другой). Если включить параметр "Показывать промежуточный диалог", при нажатии кнопки открывается весь список слоёв, выбор слоя в этом меню работает корректно для обоих вариантов.

**Comment by MadWasp79** [comment]
The same issue was for underlay. Fixed with https://github.com/osmandapp/Osmand/commit/56326b68347e4a9c2842b172023780fbf450390e
