### ISSUE TITLE
OSM Edits - Failed to upload - Error: Unknown problem

### ISSUE THREAD

**Issue by byronigoe** [osmandapp/Osmand#6520]
I created a Point of Interest (POI), and it won't upload to OpenStreetMaps. The toast says, "Committing node... failed : Bad Request".

The POI is a Museum In Arizona, and I have included information on the Basic tab. In the Advanced tab I see it has specified these tags:
name
tourism
addr:street
addr:housenumber
phone
website
description
opening_hours

**Comment by raindropsfromsky** [comment]
To upload edits, you need OSM editing account. Do you have one? 
Have you entered those credentials in OsmAnd?

**Comment by byronigoe** [comment]
Yes and yes

**Comment by byronigoe** [comment]
I tried again, running
`adb logcat net.osmand:D *:S`
and I see
```
02-06 11:11:31.199  6917  7318 I net.osmand: OpenstreetmapRemoteUtil Sending request https://api.openstreetmap.org/api/0.6/changeset/create/
02-06 11:11:31.918  6917  7318 I net.osmand: OpenstreetmapRemoteUtil Response : OK
02-06 11:11:31.923  6917  7318 I net.osmand: OpenstreetmapRemoteUtil Sending request https://api.openstreetmap.org/api/0.6/changeset/66972051/upload
02-06 11:11:32.272  6917  7318 E net.osmand: OpenstreetmapRemoteUtil Committing nodeΓÇª failed : Bad Request
02-06 11:11:32.273  6917  7318 D net.osmand: OpenstreetmapRemoteUtil null
02-06 11:25:42.723  6917  9160 I net.osmand: OpenstreetmapRemoteUtil Sending request https://api.openstreetmap.org/api/0.6/changeset/66972051/upload
02-06 11:25:43.911  6917  9160 E net.osmand: OpenstreetmapRemoteUtil Committing nodeΓÇª failed : Bad Request
02-06 11:25:43.911  6917  9160 D net.osmand: OpenstreetmapRemoteUtil null
```
(Those odd characters after "node" are a charset conversion of the ellipsis character: …)

Is there any other information I can collect to help diagnose the problem?

**Comment by MadWasp79** [comment]
@byronigoe can you check if this problem still exists?

**Comment by byronigoe** [comment]
Yes. I just updated my Android app this morning, tried to upload my OSM Edit, and got the same "Failed to upload. Error: Unknown problem" message.

**Comment by byronigoe** [comment]
I created a POI with:
name=Huhugam Heritage Center
tourism=museum
addr:street= S Maricopa Rd
addr:housenumber=21359
phone=(520) 796-3500
website=http://www.grichhc.org
description=This modern cultural center highlights the ancestral, historic, and current cultures of the Gila River Indian Community, made up of two tribes = the Akimel O'otham and the Pee Posh. Our mission is to ensure our Akimel O'otham and Pee Posh cultures flourish for future generations.
opening_hours=We-Fr 10:00-16:00
Lat 33.25387 Lon -111.97304

**Comment by MadWasp79** [comment]
@byronigoe it seems that problem is in the length of "description" field. OSM didn't accept more than 255 chars per field and you tried to send 280. 
We will add the appropriate warning in POI editor in future releases of OsmAnd and for now, you could make it shorter and try to upload again.  Please inform us about the result.

**Comment by byronigoe** [comment]
@MadWasp79 That was the problem! Thanks!

**Comment by dmpr0** [comment]
I need to reopen it because I found one issue.
I try to save changes > warning dialog to appear > tap "OK" > change screen orientation > now I can save changes without warning.

**Comment by MadWasp79** [comment]
Closed with https://github.com/osmandapp/Osmand/commit/a234845a9d4e5bca3d43e8ce791fa425a13739c3
