### ISSUE TITLE
My build of Osmand doesn't render correctly

### ISSUE THREAD

**Issue by Bjwebb** [osmandapp/Osmand#6521]
I've made a build of Osmand, following the instructions at https://osmand.net/help-online/technical-articles#Install_Development_Environment

Some items are not rendered, most notably the land/sea.

Build of `r3.2` branch:
![screenshot_20190206-225946](https://user-images.githubusercontent.com/634/52347230-c7e0b780-2a64-11e9-8585-d412cb7cb559.jpg)

Latest Osmand+ (expected behaviour):
![signal-2019-02-06-230316](https://user-images.githubusercontent.com/634/52347226-c6af8a80-2a64-11e9-8092-6dcf7965719a.jpg)

**Comment by vshcherb** [comment]
Looks like you didn't compile Native Library. https://github.com/osmandapp/Osmand/blob/master/OsmAnd/old-ndk-build.sh

**Comment by Bjwebb** [comment]
Thanks! The build works now.

**Comment by vshcherb** [comment]
For future refs: Please check - https://osmand.net/help-online#dev-environment
