### ISSUE TITLE
Interpretation of eastern longitudes in google maps urls is wrong

### ISSUE THREAD

**Issue by mfischerq** [osmandapp/Osmand#6522]
Hi all, 

when OsmAnd gets activated by a google maps URL that contains a eastern longitude, OsmAnd translates this into a geo coordinate with a negative longitude. Example:

OsmAnd reacts to: 
http://maps.google.com/maps?q=N51.02000,E014.77000 
by showing the Position:
Lat 51.02000 Lon -14.77000

The error is: since it's an eastern longitude, it has to be positive, but is negative which causes OsmAnd to show the wrong location.

I'm using OsmAnd version 3.2.7 (from F-Droid store) on a Honor KIW-L21 (5 X) using offline maps.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/pull/6627/commits
