### ISSUE TITLE
Quick Action crash after selecting empty Overlay/Underlay/Map Style actions

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#6524]
Reproduced on: Change Overlay Map, Change Underlay Map, Change Map Source.
[exception (8).log](https://github.com/osmandapp/Osmand/files/2845090/exception.8.log)

**Comment by MadWasp79** [comment]
fixed with https://github.com/osmandapp/Osmand/commit/bb477d32727444ddecd5f0af348138037528ad0d
