### ISSUE TITLE
Adress from contact is set to 0.0000 0.000 in Osmand

### ISSUE THREAD

**Issue by cmburg** [osmandapp/Osmand#6534]
I am using the current f-droid version (3.2.7) and am not able to navigate to adresses given in android contacts.

Steps to reproduce:

1. Create an arbitrary contact and add an address, e.g., "Kiel, Holtenauer Straße 20" (german map), save

2. After saving the contact details shows an arrow next to the address

3. Touch the arrow, (choose osmand, if a question appears what to open it)

4. you get the message "address not found" (or similar) and the flag is set to lat:0.000 lon:0.0000

**Comment by vshcherb** [comment]
1. Obviously we shouldn't set 0,0 flag at all. This is just misleading
2. Yes we need to check the search address

**Comment by crimean** [comment]
In the current version (3.3.7) you should be forwarded to search screen at step 4. Thus if you have maps of required region in the OsmAnd - search should show correct result(s).
