### ISSUE TITLE
Serious Coastline Rendering Errors in OsmAnd Live

### ISSUE THREAD

**Issue by InsertUser** [osmandapp/Osmand#6535]
OsmAnd Live updates to coastlines are causing the land/water boundary to incorrectly render the surrounding area when the edit is either on screen or was recently on screen.

In some instances this will disappear when sufficiently zoomed out. Rendering appears to be affected in all available map styles (OsmAnd (both day and night), LightRS, Mapillary, Nautical, Offroad, Topo, Touring view, UniRS, Winter and Ski). 

An example of this issue can be seen with:

Active offline maps: Bahamas (2019-02-01) and World overview map (2018-10-09)
Last live update: 2019-02-11

 Near: geo:25.075811,-77.31988 

Panning west at an indicated zoom 18 2.6 shows spontaneous fixing of the area incorrectly shaded as land between Potters Cay and New Providence proper.

I think this is likely related to recent edits to [way 522612354](https://www.openstreetmap.org/way/522612354), [way 440466968](https://www.openstreetmap.org/way/440466968) and creation of [way 669620386](https://www.openstreetmap.org/way/669620386). Panning sufficiently away from these areas appears to resolve the issue. 

Rendered land/sea boundary appears to correspond to the word overview map, rather than the up to date Bahamas map.  Disabling the world map fixes the most egregious errors, but the fill can still be made to jump between what I assume to be the old and new coastline layout depending on where the map is centred. 

Another example of this error can be seen in the vicinity of : geo:26.572287,-78.5739 where tweaks to canal geometry appear to cause some or all of the island to 'flood'.

Software: OsmAnd+ 3.2.7, released: 2018-11-29. Active plugins: Trip recording, Contour lines, Nautical Map view, Ski map view, Audio/video notes, Parking Position, OSM editing, OsmAnd Development. 

Hardware: Nokia 7.1 with Android 9 security patch: 2019-01-01

This appears to show some similarities to issues #6265 #5841.

**Comment by DiJuMx** [comment]
I am also experiencing the same/similar issue. 

geo:51.40048,0.53513587?z=18 
![Screenshot](https://user-images.githubusercontent.com/350375/56509121-0cd1a180-651e-11e9-9a37-3a7c26beeda4.png)

Software: OsmAnd~ 3.3.7
Hardware: Nexus 5x, Android 8.1.0, Patch 5 Dec 2018

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-core/commit/a384739a94450e3d22c4d52f0d34ade3e02adbaf
