### ISSUE TITLE
feature request: browser / web version of OsmAnd

### ISSUE THREAD

**Issue by Rik44444** [osmandapp/Osmand#6536]
hi all, a feature request to make available a browser / web version of OsmAnd. This in itself would be a great addition (since OsmAnd is better at several actions than openstreetmap.org. It would be even better if this web/browser version could be linked via a login to OsmAnd on your mobile, so you could send locations and/or routes to your mobile from the desktop/laptop.

**Comment by scaidermern** [comment]
How is this different from improving https://openstreetmap.org directly?

**Comment by Rik44444** [comment]
Hi, i noticed that OsmAnd has a lot of data and features that openstreetmap.org does not have, it seems to be a plus over openstreetmap. Eg when i search for "hairdresser" in my city, OsmAnd gives a clear overview of the hairdressers on the map, openstreetmap.org does not. 
So it would be useful for me to have an OsmAnd web/browser version. 
Improving openstreetmap.org is also possible i guess; it would be really nice if there was an OsmAnd integration then: so you could send locations and routes to your mobile with a press of the button.
sounds reasonable?

**Comment by scaidermern** [comment]
OsmAnd has the same data as https://openstreetmap.org. The interface is more powerful but this is partly due to a lack of developers. Maybe you can help? https://github.com/openstreetmap/openstreetmap-website

**Comment by vshcherb** [comment]
I'm afraid we are not going to do something similar in the nearest future, it is too much work I think

**Comment by Rik44444** [comment]
OK:) how about the plugin for openstreetmap.org, so you can send locations/routes to OsmAnd - is that a feasible addition, in terms of time/work? i think it would make a great addition!

**Comment by scaidermern** [comment]
You can already send locations to OsmAnd and similar services via the share button on the right and the Geo URI.
