### ISSUE TITLE
Incorrect navigation directions

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/OsmAnd#6539]
The directions of the route in OsmAnd differs from the same route in OSM, although the map data in OsmAnd is up to date. 
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=49.8185%2C6.7487%3B49.6985%2C6.5736#map=11/49.7953/6.7052
![image](https://user-images.githubusercontent.com/40493090/52638281-5082ac00-2eda-11e9-9a61-0da34a7d5f38.png)

**Comment by xmd5a2** [comment]
Straight route contains 15 traffic signals but OsmAnd route contains only 4. I don't think it is a bug. If intermediate point is set in the middle of Krahnenufer then OsmAnd builds a route through it without problem.

**Comment by scaidermern** [comment]
Probably also a problem in the map data. Some traffic signals are wrongly mapped, for example [node 3258357811](https://www.openstreetmap.org/node/3258357811) is mapped as
`highway=traffic_signals`
`crossing=traffic_signals`
instead of
`highway=crossing`
`crossing=traffic_signals`
The latter would be correct since this traffic signal only applies to pedestrians, not to cars (the one for cars is [node 3258357820](https://www.openstreetmap.org/node/3258357820)).

**Comment by scaidermern** [comment]
@xmd5a2 Does OsmAnd honor `traffic_signals:direction=*`?

**Comment by xmd5a2** [comment]
> @xmd5a2 Does OsmAnd honor `traffic_signals:direction=*`?

No

**Comment by scaidermern** [comment]
> > @xmd5a2 Does OsmAnd honor `traffic_signals:direction=*`?
> 
> No

Oh. This means OsmAnd is applying a penalty even for traffic lights that don't affect the current driving direction :/

**Comment by vshcherb** [comment]
Yes, there must be an issue about traffic_signals group

**Comment by OpenSourceForEver** [comment]
Is this issue fixed?

Maybe it can be closed.

**Comment by vshcherb** [comment]
There are much more traffic signals on 1 part of the road (13 vs 5)
Also there are combinations of such nodes which gives extra penalties as well.
https://www.openstreetmap.org/node/206155039#map=19/49.75159/6.62761
https://www.openstreetmap.org/node/7418981896

It could be fixed if traffic signals penalty will be `10 seconds`

**Comment by OpenSourceForEver** [comment]
> There are much more traffic signals on 1 part of the road (13 vs 5)
> Also there are combinations of such nodes which gives extra penalties as well.
> https://www.openstreetmap.org/node/206155039#map=19/49.75159/6.62761
> https://www.openstreetmap.org/node/7418981896
> 
> It could be fixed if traffic signals penalty will be `10 seconds`

10/15 seconds would be a correct time, other routes would benefit from this, since routes with many traffic lights are calculated with excess time
