### ISSUE TITLE
Can't search address in nearby cities

### ISSUE THREAD

**Issue by bauxx** [osmandapp/Osmand#6542]
I have the same issue with address search in the OsmAnd+ app (version 3.2.7 installed via google play) under android 8.1. I am using offline maps, downloaded via the app.
If I go to search > select city first and choose a city (in my case Wien), instead of being able to search the street, OSM And directly shows the location of the city on the map. Thus, I am not able to search any particular street.

Seems to be some kind of bug in the app, maybe it is trivial but I haven't been able to find solution for it for some time already. This behavior comes when I try to look up addresses in any cities, which I get suggested as "nearby cities" (in my case Vienna and nearby cities). Curiously, I can't reproduce the bug on the same version of OsmAnd on other Smartphone device, although similar problems seem to have occured in the past.

I haven't tried reinstalling the app yet.

I will be thankful for any advice/tips!

Edit: seems to be a duplicate of https://github.com/osmandapp/Osmand/issues/5967

**Comment by dson66** [comment]
Just downloaded the app and maps to my android device in my car thru the play store and the app is still having the same problem. We cannot search for an address with house numbers, it only pulls up the street. From the different forums I have read seems the developers have not fixed this bug that was brought up over a year ago. Too bad my wife really likes this gps

**Comment by scaidermern** [comment]
Please tell us exactly which steps you perform and which text you entered into the search field.

**Comment by bauxx** [comment]
1. I go to search (magnifying glass)
2. Address
3. Select the city first
4. I type "Wien"
5. Pickup the desired city from suggestions (Vienna)
6. then, instead of being able to proceed with street search, the app switches to map view and marks the position of city of Vienna.

I hope this helps you somehow. I can not give you precise steps to reproduce the bug, it seems a bit random to me, respectively I do not fully understand the app-context which might be causing the bug. As a matter of fact, it disappeared today from my phone (I am able to lookup streets in Vienna), but this happened in the past already. Only thing different from yesterday is, that I do not get Vienna suggested under nearby cities (my GPS is turned off at the moment).

**Comment by scaidermern** [comment]
This really sounds like #5967.

**Comment by bauxx** [comment]
Yes I also think it is the very same issue.  #5967 was closed and commented as fixed, but obviously the bug still persists in the latest version. Just for the record.
Should this issue remain open until it is reliably fixed?

**Comment by dson66** [comment]
If I am searching for 1234 main street it only lists main street not the
exact location, if main street is 10 miles long what good is it to be
directed to possibly the farthest point. USA uses house numbers and streets
as the location, think of it as gps coordinates. Every other gps works this
way cant beleive this one doesnt

**Comment by scaidermern** [comment]
> If I am searching for 1234 main street it only lists main street not the exact location

Probably because there is no house number 1234 for main street in OSM. But we can't know unless you are tellung is the exact address you are searching for.

> Every other gps works this way cant beleive this one doesnt

This one does, too. If the address exists in OSM (and if the above bug doesn't occur).

**Comment by dson66** [comment]
Its an example your product will not let you search any addresses by
house/business physical address. If its so hard for you to understand try a
garman or tom tim unit and search for a physical address of a police
station or post office in any town and state you choose. It will give you
the building number, street, city and state and direct you to the actual
location not just the street it is on. Just being directed to the street is
useless especially if the street runs for many miles you could end up at
the opposite end of where you need to be. Im uninstalling your product and
am going to give it a poor review

**Comment by dson66** [comment]
Dowloaded it to an android based incar entertainment system, this is where
you bug lies, this is what many of the other posters have tried to explain
but you are testing it on the wrong devices

**Comment by vshcherb** [comment]
Can't reproduce if the map is downloaded. The object is selected and goes to the map if the map is not downloaded. I checked both "Address" tab and "Categories" tab and both work fine.

![image](https://user-images.githubusercontent.com/1042025/53348711-dd3a5a80-391b-11e9-8702-687e34b851ff.png)

**Comment by dson66** [comment]
Whatever, if your product doesn't work in the United States as it should
and you aren't smart enough to try it with addresses within the US then you
shouldn't market to the US. Keep your foreign CRAP out of our country

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by bauxx** [comment]
dson66: you are off topic already in this issue. In fact, you are also annoying with your tone. OSM is an open-source project. You may contribute to it to become better yourself (for instance by adding missing house-numbers to the map). But if you can't handle your frustrations, go and search another forum to ventilate, please.

**Comment by bauxx** [comment]
@vscherb: I am sorry, I also can't reproduce this reliably. Usually, when Wien the bug comes and disappears again randomly, as it seems. My guess was, that it is connected to the context of nearby cities. But don't know it for sure.

**Comment by vScherb** [comment]
@bauxx
The response was probably meant for @vshcherb

**Comment by vshcherb** [comment]
Will keep it in our list of find and fix issue, once we reproduce it ourselves or find a stable way, it will be addressed by developers
