### ISSUE TITLE
Check duplicate street names in some cities

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#6544]
In Kiev check duplicate street names via binaryInspector.sh . Suspects: Саксаганского.

Probably it should be fixed on the map or if possible algorithms could be justified.

**Comment by xmd5a2** [comment]
Wrong OSM data
https://www.openstreetmap.org/node/6135123901 (wrong street name)
https://www.openstreetmap.org/node/3729386369 (far away from street)
