### ISSUE TITLE
The Route Editor shows wrong number of waypoints (It counts the destination point also)

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#6546]
Reporting for OsmAnd ~3.3.30#26750m (2019-02-14), running on Android 8.0.0 (ZenFone 5z)

The Route Editor shows wrong number of waypoints: It counts the destination of the journey also. Technically the destination not a waypoint (via point).

Note that when the route consists of only a starting point and a destination, the GUI does not show the number of waypoints. This can be rightly construed to mean there is no waypoint.

Thus the GUI would become consistent if the destination is not counted as a waypoint.

**Comment by sonora** [comment]
I think this was a wording issue. I have meanwhile changed the headline on that screen to say "Destinations" (in line with https://github.com/osmandapp/Osmand/issues/6606#issuecomment-469153546), so this issue should be obsolete.
