### ISSUE TITLE
The "Apply" button in the Route Editor needs some tweaks

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#6547]
Reporting for OsmAnd ~3.3.30#26750m (2019-02-14), running on Android 8.0.0 (ZenFone 5z)

The "Apply" button in the **Route Editor** has some consistency issues:

1. When the OsmAnd calculates the route, the same button acts as a progress bar. Moreover, OsmAnd does not wait for us to press this button: as soon as a new point is added, OsmAnd starts calculating the route automatically. Considering this, this button should not be labelled "Apply", but given a hourglass (="please wait", or "calculating...") icon.

2. In some cases the button contain a dual-colored (blue+light-blue) up-arrowhead. But in most cases this icon is missing, but the "Apply" label remains. This should be consistent.

3. Sometimes OsmAnd recalculates the route, but without showing a progress bar in the button. (The button remains white, with a "Apply" label.) This should be consistent.

4. In some case the button contains the dual-shaded arrow button and "start" label. I have not found the condition when the "apply" label changes to "Start". 

5. If I tap on the "Apply" button, I see some momentary movement in the map. Apart from that, there is no change (e.g. no progress bar).

6. Its design could be tweaked to display the "Waiting for GPS" condition also. Currently the user gets no such indication. While the GPS is not available, please show the current location in the map with a gray circle (not a blue circle).

7. When the GPS is not available, OsmAnd shows the button in full blue (which amounts to 100% progress bar). It shows the double-shaded arrowhead icon and the "Start" label. This is misleading, because the route is yet to be calculated, ONLY AFTER the GPS is available.

**Comment by vshcherb** [comment]
I think it would make sense to revise this report in 2-3 weeks, once Route editor is polished.
