### ISSUE TITLE
Strange navigation detour

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6551]
Start   Lat 48.85270 Lon 2.28109 
End   Lat 48.83724 Lon 2.29644
The route avoids the Rue Linois street although it is possible to drive there (bike mode), in the right direction and it seems straighter.
![image](https://user-images.githubusercontent.com/40493090/52793766-1e5a8100-3077-11e9-9c6e-f7d897670c8f.png)
![image](https://user-images.githubusercontent.com/40493090/52793771-22869e80-3077-11e9-9b3a-a9af67ae82c6.png)

**Comment by utack** [comment]
It is a tertiary street with 4 lanes and many traffic lights
I don't think this is a bug

**Comment by xmd5a2** [comment]
Agree. There are 4-5 traffic lights on this street while Rue de Javel has much less of them.
