### ISSUE TITLE
translate app store texts directly on Weblate

### ISSUE THREAD

**Issue by eighthave** [osmandapp/Osmand#6554]
[Fastlane](https://github.com/fastlane/fastlane/blob/2.28.7/supply/README.md#images-and-screenshots) and Triple-T are two tools for syncing app store texts/graphics/screenshots/etc from a git repo to Google Play.  Both of them are also [directly supported](https://f-droid.org/docs/All_About_Descriptions_Graphics_and_Screenshots/) by F-Droid.  Weblate just launched a beta feature for directly translating the app store name/summary/description/whatsnew texts.  As far as I know, no other translation platform supports these file formats.

See this in action for F-Droid's Android client:
https://hosted.weblate.org/projects/f-droid/f-droid-metadata/

Follow the beta here: https://github.com/WeblateOrg/weblate/issues/1525

The F-Droid community is already maintaining some translations for OsmAnd in Fastlane format, which could be directly copied into Osmand:
https://gitlab.com/fdroid/fdroiddata/tree/master/metadata/net.osmand.plus

@comradekingu

**Comment by vshcherb** [comment]
Very interesting need to check how does it look

**Comment by verdulo** [comment]
Please regard that version for F-Droid is "OsmAnd~", replace the text:
`OsmAnd+ is the full version of this app. Please donate to support the project, fund the development of new features, and receive the latest updates. `
with 
`OsmAnd~ is special edition of application without limits for users of F-Droid.`

and add the paragraph:
`Anti-Features:
* NonFreeAssets - Artwork and layouts are under a non-commercial license.
* NonFreeNet - May download images from nonfree Mapillary online service
* NonFreeAdd - Proposes to download a proprietary app (Mapillary) from Google Play Store to add photos to their service `

and also to list of regions add Australia/Oceania.

**Comment by vshcherb** [comment]
I think we've already provided screenshots with translations to F-Droid in OsmAnd-misc project
