### ISSUE TITLE
Short/medium trips do not use motorways even when best, but long-distance trips do

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#6559]
What version of OsmAnd are you using, on what device and Android/iOS version?

_OsmAnd night build 3.3.0#26782m, dated 2019-02-17_
_Samsung Galaxy S7 Edge, Android 8.0_

_The problem does not appear in night build 3.3.0#26595m, dated 2019-01-21 on my S9+ with Android 9; I can install that .apk on the S7 if you want me to confirm it there, but I'm reasonably certain that release will route properly on the S7.  I'm trying to think of if/when, between those two releases, I might have tried a different short/medium trip with OsmAnd that would have used an intermediate night build.  At the moment, can't remember specifically enough, but I'll keep working on it._

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

_OsmAnd's offline maps_

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

_Your provided US Florida and US Georgia maps, both dated January 31, 2019.  Tested with Live updates both on and off; there is no difference._

__*In case of wrong routing:*__

Tell us whether you have used OsmAnd's in-app offline routing, or any online routing provider like YOURS, OpenRouteService or OSRM.

_OsmAnd's in-app offline routing_

What routing profile is chosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest)

_Car, fastest route enabled (fuel-efficient route disabled).  All "avoid" options disabled._

Please specify as exactly as possible the start and end point of your route by telling us city name and street name so that we can find it via in-app address search easily. Also, a permalink from openstreetmap.org can be helpful.

_Start point:  this gas station https://osm.org/go/ZDdub~w6D?layers=NG&way=562335286
Destination:  this restaurant https://osm.org/go/ZGIpwOYcK?layers=NG&way=587311460
Add subsequent destination:  Atlanta city hall https://osm.org/go/ZF~~90iCp?layers=NG&way=113041909_ 

Tell us your expected routing, and how OsmAnd routes, or add screenshots here.

_Preface:  I know you were tinkering with motorway penalties recently; I don't know if this is related to that, or something else._

_From the gas station to the restaurant, OsmAnd avoids motorways completely, even though heading up I 75 is both the shortest and fastest route.  Screenshot:_

![screenshot_20190217-110814_osmand](https://user-images.githubusercontent.com/11140831/52916327-f4d66b00-32ab-11e9-980a-f00498096857.jpg)

_After adding Atlanta city hall as a subsequent destination, OsmAnd does select I 75 from the restaurant into downtown Atlanta, although it still avoids it for the leg TO the restaurant.  Screeenshot:_

![screenshot_20190217-111230_osmand](https://user-images.githubusercontent.com/11140831/52916329-fb64e280-32ab-11e9-9bcc-033bf24b7272.jpg)

_Route overview:_

![screenshot_20190217-111318_osmand](https://user-images.githubusercontent.com/11140831/52916334-0750a480-32ac-11e9-97db-a340d3c27c52.jpg)

**Comment by xmd5a2** [comment]
As you mentioned in issue this is not reproducible on latest nightly. So we can't do anything about that
![screenshot_2019-02-18-11-30-10-473_net osmand plus](https://user-images.githubusercontent.com/5829014/52937660-d2f2ec00-3370-11e9-915b-af4d592411f7.png)

**Comment by jfburke3** [comment]
@xmd5a2 No, the latest nightly (when I reported it) DID produce the problem route.  An OLDER nightly (from January) did not produce it.

I'll try the latest nightly from today as soon as I get a chance.

**Comment by aceman444** [comment]
Can you inspect the motorway that is avoided, node-for-node if there may be some barrier entered in the OSM data (like a height_restrictor) that OsmAnd may try to avoid?

**Comment by jfburke3** [comment]
This one does seem to have gone away now.
