### ISSUE TITLE
Indicate fuel type(s) offered by fuel stations

### ISSUE THREAD

**Issue by benedetto** [osmandapp/OsmAnd#656]
Recently I was searching for a fuel station and was glad to have found one rather close and more or less close to my route (still would love to see [the search POI along route feature](https://code.google.com/p/osmand/issues/detail?id=1593)). When I arrived there I found out that this station was offering [LPG](https://en.wikipedia.org/wiki/Liquefied_petroleum_gas) only, which I cannot use.

Therefore it would be nice if it could be indicated somehow which sorts of fuels are available at a certain fuel station (if such information is available through the `fuel=*` tag of openstreetmap).

**Comment by strannik-j** [comment]
It's important to me too.
