### ISSUE TITLE
strange sorting order of search results

### ISSUE THREAD

**Issue by 532910** [osmandapp/Osmand#6562]
![image](https://user-images.githubusercontent.com/14617699/52921376-68698e00-3327-11e9-97a1-44c29c1c001e.png)

**Comment by vshcherb** [comment]
Додо is prioritzed as exact match comparing Додо Пицца. If you click on search or enter space results will be more precise

**Comment by nils-werner** [comment]
> Додо is prioritzed as exact match comparing Додо Пицца. If you click on search or enter space results will be more precise

So the search result ordering is by quality of match first, distance second?

Is that really sensible behavior, given that it mixes in results from 7000km away? And is there a way to change this?

**Comment by vshcherb** [comment]
search has changed a lot in last release with exact matches
