### ISSUE TITLE
Rename regions Brandenburg/Niedersachsen to Brandenburg+Berlin/Niedersachsen+Bremen

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#6575]
When using the address search with coordinates that are located in Berlin (e.g. 52.44, 13.57) they are  shown as being located in Brandenburg instead.

Berlin is a separate state although it is enclosed by Brandenburg.

Possibly related to #6572.

**Comment by scaidermern** [comment]
The same applies to Bremen for which coordinates are falsely shown as being located in Niedersachsen.

**Comment by vshcherb** [comment]
This is a minor issue cause this is a hint and in the context menu the map is displayed correctly. So only coordinate search is quite misleading.

**Comment by vshcherb** [comment]
We've made decision to not exclude the content of the super-regions and enclaves, so we will need to rename enclosing regions to remove confusion later. Cause this issue could be misleading for OsmAnd Live changes, it will be kept open.

BTW it was fixed for Context menu by displaying the smallest possible region to download
