### ISSUE TITLE
Hungarian voice updates

### ISSUE THREAD

**Issue by debyos** [osmandapp/Osmand#6580]
Dear All,

I have made some small update in the Hungarian voices (both [formal](https://github.com/osmandapp/OsmAnd-resources/tree/d7afd8138f8d259f570ae57c6987fd50d3b7e4af/voice/hu-formal) and [informal](https://github.com/osmandapp/OsmAnd-resources/tree/d7afd8138f8d259f570ae57c6987fd50d3b7e4af/voice/hu)). Please, implement them.

Here are they: [hu-versions.zip](https://github.com/osmandapp/Osmand/files/2898447/hu-versions.zip)

Thanks in advance

Gábor

**Comment by vshcherb** [comment]
Could you please make pull request, it would be much more efficient. https://help.github.com/en/articles/creating-a-pull-request-from-a-fork
You can edit the files in the browser.

**Comment by debyos** [comment]
I can't make any pull request (it may be my fault: I am not a programmer just(?) a translator). On other GitHub sites I can click on the pencil to edit the file but here it says that I must be on a branch to do it. 

I don't know what is a branch and how I could be there…

**Comment by vshcherb** [comment]
You can click pencil but first you need to click button Fork and Edit in the file.
![image](https://user-images.githubusercontent.com/1042025/53951357-904e4500-40ce-11e9-8087-0b21ee525a07.png)
If you already forked, you need to open your fork and edit file in your fork and then create pull request

**Comment by debyos** [comment]
Thank you!
Did I succeed?

**Comment by sonora** [comment]
Looks like this is your fork: https://github.com/debyos/OsmAnd-resources/commits/master, so now if you are done you simply have to tap the 'Create pull request'?

**Comment by debyos** [comment]
OK, thanks, now I have made a try? Does it work?

**Comment by sonora** [comment]
Thank you very much! There were extensive changes you have made, but it looked ok to me from a technical point of view so I have merged it. Please test with our nightly builds.
