### ISSUE TITLE
texts not added to translation | tekstoj ne aldonitaj al traduko

### ISSUE THREAD

**Issue by verdulo** [osmandapp/Osmand#6581]
The following texts are not extracted for translation (in the latest Nightly release):

"Charging station"
![bildo](https://user-images.githubusercontent.com/16842967/53306556-d0bbf080-388e-11e9-8396-a511f5c158fe.png)
The string "phrases/poi_charging_station_filter" should be used.

"Payment coins"
![bildo](https://user-images.githubusercontent.com/16842967/53306567-fe089e80-388e-11e9-9a8c-7fc5c327e505.png)
Probably should be "phrases/poi_payment_coins_0.5".

"Health speciality radiotheraphy yes"
![bildo](https://user-images.githubusercontent.com/16842967/53306584-360fe180-388f-11e9-9938-caf9cfeecd42.png)
No string on Weblate.

"Wikipedia"
![bildo](https://user-images.githubusercontent.com/16842967/53306641-f695c500-388f-11e9-9c46-60ab22f7d509.png)
Should be "phrases/poi_wiki_link".

**Comment by hakuchi** [comment]
`payment coins 0.5` should be changed to `payment:coins=yes`
payment cons make only sense with `yes` or `no`

**Comment by verdulo** [comment]
Another string "Hazard":
![bildo](https://user-images.githubusercontent.com/16842967/53561854-32f74880-3b50-11e9-8465-01ae15875d89.png)

**Comment by verdulo** [comment]
I have the question:
Where is used the string "home_button" in the program, is it used only on Navigation screen in sense "place where I live" (https://github.com/osmandapp/Osmand/blob/165b3b98909279ad55b67249374fa9098cde1177/OsmAnd/res/layout/home_work_card.xml) or also somewhere else?
I ask because it was previously used in the sense "home/beginning screen"; such it is translated for Polish, Esperanto, probably for French, Galician, Catalan, Portugal, Italian: https://hosted.weblate.org/translate/osmand/main/eo/?checksum=b8954e6846c99fab#translations
