### ISSUE TITLE
Basemap: wrong processing of multipolygons

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/OsmAnd#6587]
Inner ways of multipolygons aren't processed correctly. For example (polygon_lake_water.osm):
![screenshot from 2019-02-27 15-04-33](https://user-images.githubusercontent.com/5829014/53490282-6d0b1080-3aa4-11e9-9238-53db65c16210.png)

But in basemap it looks like this:
![screenshot from 2019-02-27 15-04-46](https://user-images.githubusercontent.com/5829014/53490320-7d22f000-3aa4-11e9-88c1-16de0af77376.png)

https://www.openstreetmap.org/relation/2426031

This is the source of some "flooded" islands (zoom 11)
![screenshot from 2019-02-27 15-11-47](https://user-images.githubusercontent.com/5829014/53490405-acd1f800-3aa4-11e9-9d1a-5d61b0fd1dc1.png)

**Comment by vshcherb** [comment]
With default basemap now of zoom up to 7, it is less of a problem

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/9713
