### ISSUE TITLE
osmand telegram canadian area code 1-873

### ISSUE THREAD

**Issue by gignacnic** [osmandapp/Osmand#6591]
We are using OsmAnd and Telegram to share GPS location in my organization. We are training 300+ persons to use these excellent tools!
All worked well, except for users that has a specific area code (1-873-XXX-XXXX) in Canada. Each time these users goes into osmand telegram they are banned from telegram (see screen shot), even if this area code it is a real one in Canada: https://en.wikipedia.org/wiki/Area_codes_819_and_873. I have written to: recover@telegram.org and it looks that the problem is in osmand telegram not telegram it self, because user can create their account in telegram before without any problem, when they try to start a new sharing location in osmand telegram they are banned. Any idea if osmand telegram is validating the list of area code? If so, please add 1-873-XXX-XXXX.
![telegram_osmand_ban](https://user-images.githubusercontent.com/5321940/53568261-7b523e80-3b2f-11e9-8bb6-9337a97aab21.jpg)

**Comment by vshcherb** [comment]
Do you type +1 873? Does it work with other codes like +1 XXX ?
Did you try it with latest release, where we have updated telegram native library tdlib.

So, far we have no idea and we don't have tools to properly test unfortunately, so it looks like we need to make a blind guess or probably get some clarity from Telegram to understand why this ban occurs.

**Comment by gignacnic** [comment]
It works for other area code 1-819- or other in Canada, area code 873 is a new area code introduce in 2017. I have also shared this issue with telegram, but I think it is related to osmand telegram, not telegram it self. When we register with osmand telegram, where it goes (API?) for phone number validation and send a code by SMS to the user? I might think that is that is there that it is banned. We use the up-to-date app osmand telegram on the Google Work Store.

**Comment by vshcherb** [comment]
All API goes via https://core.telegram.org/tdlib which is owned by telegram recently we've updated it to the latest version.
If a Telegram client is installed on the phone, the code is not sent via SMS but it is sent via Telegram client. So, it is not clear at which point the account is blocked when user tries to register a number or when user shares location to the chat.

**Comment by gignacnic** [comment]
It is blocked when the user register a number in osmand telegram, way before he can share its location.

**Comment by vshcherb** [comment]
It is better to try with installed telegram client upfront probably it will work.

**Comment by gignacnic** [comment]
What do you mean? telegram client? We use up-to-date telegram app nd osmand telegram app on Android 7.1.1.

**Comment by jfburke3** [comment]
Do you know of any other Telegram users with a phone number where the area code has a middle digit that is anything other than 0 or 1 (e.g., 678)?  Are they able to use it?

**Comment by gignacnic** [comment]
Finally, writing an email with phone number with an error ban to: recover@telegram.org solved the issue.
