### ISSUE TITLE
Small navigation mistake

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6595]
Lat 49.01016 Lon 8.38757
![image](https://user-images.githubusercontent.com/40493090/53640503-0d903a80-3c35-11e9-811a-58a72686ebf9.png)

**Comment by scaidermern** [comment]
[way/149710116](https://www.openstreetmap.org/way/149710116) has two traffic signals. Maybe OsmAnd thinks the loop is faster because it has no traffic limits? :/

**Comment by MadWasp79** [comment]
fixed
