### ISSUE TITLE
OsmAnd+ not at google play no more?

### ISSUE THREAD

**Issue by MeCias** [osmandapp/Osmand#6600]
Hi,

just did a reset of my phone and was about to install OsmAnd+ again until I noticed it is not available anymore at google play.

https://play.google.com/store/apps/details?id=net.osmand.plus

Is there any reason for that? Do I miss something?

**Comment by vshcherb** [comment]
We will use Twitter to notify others about the status https://twitter.com/osmandapp/status/1101771221493002240

**Comment by MeCias** [comment]
Thanks a lot.

**Comment by vshcherb** [comment]
We hope it will be restored soon and meanwhile please use the free version
