### ISSUE TITLE
Measure Distance tool: please suggest last saved gpx file as first for adding to

### ISSUE THREAD

**Issue by pgavrilov** [osmandapp/OsmAnd#6602]
Suggestion.

Currently, if I want to add some lines to one GPX file, I must save first line as new GPX file, and seek this filename for every next line in a long-long alphabetical list of files, placed in Tracks subfolder.

I have very large list of files there, and always I want to use same file as last created. Please add it (or even five last created tracks) to the top of this list.

OSMand+ 3.2.7

**Comment by vshcherb** [comment]
Done
