### ISSUE TITLE
Locale problem with OsmAnd+ 3.3.2

### ISSUE THREAD

**Issue by asereze** [osmandapp/Osmand#6604]
App version: OsmAnd+ 3.3.2 (2 march 2019)
Device: Xiaomi Redmi Note 4X
OS: Android 8.1 (LineageOS 15.1)

After the last update the display language changed from the one I choose (Sardinian) to English. If I select any language from the list nothing changes, and I always get English. Only if I select "System (Device language)" I get a different one, but it's not the one I want (my device language is Italian, since Sardinian is still not available for Android, but I use Sardinian in OsmAnd). The app always worked fine up until today.

**Comment by sonora** [comment]
Cannot actually reproduce this so far ... Sardinian seems to work fine on my test devices.

**Comment by asereze** [comment]
@sonora that's weird, I don't know why with your devices it works fine and with mine it doesn't, I still get the same problem even if I uninstall and reinstall the app. Again, it's never been an issue until the last update. Is there a way to save a log or something that I could upload here to find out what the problem is?

**Comment by vshcherb** [comment]
This is the problem of using Android Bundle looks like. The pros: 
- Size became much much smaller and now contains small basemap as well
The cons:
- Looks like it trims non-locale languages for the apk to be used

**Comment by sonora** [comment]
Issue not present in nightly builds, though, right?

**Comment by vshcherb** [comment]
This issue is only for Google Play releases

**Comment by asereze** [comment]
I've installed the new 3.3.3 update today, but the issue is the same even with the new version.

**Comment by asereze** [comment]
Same with 3.3.4. Is it going to be fixed in the next update?

**Comment by crimean** [comment]
@asereze could you confirm it with non LineageOS, but official Android OS?

**Comment by crimean** [comment]
@asereze issue confirmed. Thank you!

**Comment by asereze** [comment]
It works fine, now. Thank you very much to all of you.
