### ISSUE TITLE
Crash: WaypointsFragment not attached to a context

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#6605]
Testing our new v3.3.2, this comes up quite frequently when playing around with intermediate destinations during route setup. Not quite sure how to reproduce, mostly observed when removing an intermediate dest.

[exception.log.txt](https://github.com/osmandapp/Osmand/files/2922877/exception.log.txt)

**Comment by sonora** [comment]
Similarly, an NPE occurs when using the feature Show POIs along route.

[Exception.log.txt](https://github.com/osmandapp/Osmand/files/2923522/Exception.log.txt)

**Comment by Chumva** [comment]
Fixed with https://github.com/osmandapp/Osmand/pull/6597/commits/82045c95e00a33576ed459879b6721f775af1678
