### ISSUE TITLE
Small UI glitches in v3.2.2

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#6606]
Observed in dark theme, as follows:
(1) Wrong font color for summary numbers, see picture
(2) Turn-by-turn details in light color pattern
(3) Start / destination lines only half visible (on some devices only)

![untitled 2png](https://user-images.githubusercontent.com/845735/53694829-47d41600-3db4-11e9-9b53-762d8f9e48af.png)   ![untitled1](https://user-images.githubusercontent.com/845735/53694826-460a5280-3db4-11e9-9c1f-e1f9e3da750c.png)   
![untitled 3png](https://user-images.githubusercontent.com/845735/53694881-ebbdc180-3db4-11e9-863b-09526d41213d.png)

(4) In addition, some users are still confused when a route calculation has started, or when not (e.g. because they still have to specify a destination).
 (a) Maybe we should put "Select destination" in red font?
 (b) Maybe we can add a spinner to the "Cancel button" while route is being calculated
 (c) Maybe we should change the 'Cancel' text caption to 'Discard' after a route has been calculated?

(5) Also a general reminder:There is still some inconsistency between text "Add waypoint" and "Add intermediate" in different screens but meaning the same.

**Comment by Chumva** [comment]
1,2 and 3(I will add fix tomorrow) will be fixed in this request - #6597,  4-5 need a little bit more time for UI decisions

**Comment by sonora** [comment]
Ok, cool, thanks.!

Yes, (4) are iust ideas we may want to consider.

And (5) is already under discussion elsewhere, we have to make a little quality initiative to systematically make the textual separation between waypoints and intermediate destinations also in our new UI where it makes sense.

**Comment by sonora** [comment]
Regarding (5), let me document some remarks:

(A) An **intermediate destination** is a point you specify as part of your route, i.e. you mean to go there, and it is used in the route calculation.

(B) A **waypoint** is a point interesting for you on or near your route, it could be a restaurant, gas station, or even traffic sign. The route does not necessarily traverse it. I think we use 'Waypoints' also as a headline for a list /screen containing both (A) and (B).

(C) There is also a **'GPX waypoint'**, a location specifically xml-tagged in a GPX file independent of any routing information. Meaningwise it is hence closer to (B), but it is actually a fixed feature of the GPX specification.

**Comment by sonora** [comment]
(1) - (3) fixed, thanks @Chumva !

**Comment by sonora** [comment]
I have fixed (5) in along the principles of https://github.com/osmandapp/Osmand/issues/6606#issuecomment-469153546 above.

**Comment by vshcherb** [comment]
Most of the issues fixed (4) will require a separate thinking and discussion.

**Comment by sonora** [comment]
I have implemented 4(c) here https://github.com/osmandapp/Osmand/commit/91be1a1249e7e2b10c39a3e30695191f9310187b and here https://github.com/osmandapp/Osmand/commit/e1392212dbd36ecc3ed8b37b861e51b7cbcd0fe7. Think it is fine now.
