### ISSUE TITLE
"Analyse on map" does not work anymore

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6608]
In the new OsmAnd version (3.3.2), there is no option to analyze the profile of a track on the map during navigation. Has this feature been removed from the new version?
old version:
https://youtu.be/CtAJqqDIQOE
new version:
https://youtu.be/dGtcOHgrFFI

**Comment by barteis** [comment]
The feature still works for analyzing GPXs, but, seemingly, no longer for simple From:/To: navigation.  For outdoor activities, especially, it's highly useful.

**Comment by quax2712** [comment]
this function is very important! May bee color for darc mode could bee made better blue is to darc!

**Comment by sdebarra0** [comment]
I note here that I am missing this excellent feature also. It is sorely missed.

**Comment by crimean** [comment]
Fixed by https://github.com/osmandapp/Osmand/commit/d7592a693bc2465aab0ad87d598cdc060e1ad061

**Comment by Ciantic** [comment]
Was this released? I can't find it either, and I have a mountain in front of me.

**Comment by xmd5a2** [comment]
@Ciantic there was a glitch with the maps and we restarted the process of their generation. Please wait 1-5 days for new June maps.
