### ISSUE TITLE
Improve airport rendering

### ISSUE THREAD

**Issue by morray** [osmandapp/Osmand#6610]
Large airports are often not shown on overview zoom levels while much smaller ones are highlighted.
E.g. looking at Munich at the 10km scale you see the small airfield of Dachau and the one of the museum Schleißheim, while Munich airport (top ten of Europe) is not shown.

**Comment by sonora** [comment]
Looks like we are talking e.g. https://www.openstreetmap.org/way/664709068 vs. 
https://www.openstreetmap.org/way/487185364#map=13/48.3538/11.7861

**Comment by xmd5a2** [comment]
Current detailed basemap doesn't have this issue. I've checked most of large European airports and they are rendered adequately in most cases. Rendering depends of tags iata,icao,faa,ref,wikipedia.
![Screenshot from 2020-06-25 12-35-21](https://user-images.githubusercontent.com/5829014/85695178-76c87680-b6e0-11ea-96b7-9a65f789978c.png)
