### ISSUE TITLE
Cannot change rendering style due to GUI buttons not showing

### ISSUE THREAD

**Issue by pietervdvn** [osmandapp/Osmand#6612]
OsmAnd v3.3.2 (release date 2019-03-02), Android (LineageOS with GApps)
Offline maps

I have an extra map style installed. When clicking 'Configure Map' > 'Map Style', the dialog is shown full-screen. No 'Apply' or 'Cancel' button show up, neither can I swipe down the dialog or click outside it. The only solution is to press the 'back' button, effectively cancelling the new selection.

![screenshot_20190304-145422_osmand](https://user-images.githubusercontent.com/1466478/53737767-b76a0400-3e8d-11e9-8b47-ad1781c0ee78.png)

**Comment by alyonapinchuk** [comment]
Sony Xperia X Android 8.0
![image](https://user-images.githubusercontent.com/40493090/53740072-03bc4080-3e9c-11e9-9930-52d45d229d56.png)

**Comment by MadWasp79** [comment]
closed with https://github.com/osmandapp/Osmand/commit/b119f2f572caabcbb6daef6abeae362fe6f3e5be

**Comment by pietervdvn** [comment]
Hey,

While this fix already helps, the buttons are not showing up for me - so I'm still stuck without buttons (v3.3.3) and no way to change rendering.

**Comment by vshcherb** [comment]
3.3.4 should have it
