### ISSUE TITLE
Routing details show wrong colours with custom surface pavement colours

### ISSUE THREAD

**Issue by pietervdvn** [osmandapp/Osmand#6613]
OsmAnd v3.3.2 (release date 2019-03-02), Android (LineageOS with GApps)
Offline maps
**Custom map style**

I've changed the rendering colours of cobblestone on OsmAnd - they show up in brown now.

However, when using the fresh 'details of route' feature, the surface section does _not_ pick up those colours but still uses the old blue colour.

The new rendering style; notice the brown for 'sett':
![screenshot_20190304-145826_osmand](https://user-images.githubusercontent.com/1466478/53738223-e5037d00-3e8e-11e9-9c17-b0617965e2b3.png)

The details section - no brown is visible:
![screenshot_20190304-145803_osmand](https://user-images.githubusercontent.com/1466478/53738098-8fc76b80-3e8e-11e9-92ea-b0f4423983ce.png)

Extract of the map style, where I applied changes

        		<case additional="surface=asphalt" attrColorValue="#6f687e">
			<apply_if nightMode="true" attrColorValue="#eae6f3"/>
		</case>
		<case additional="surface=paved" attrColorValue="$surfacePavedColor"/>
		<case additional="surface=concrete" attrColorValue="#949997"/>
		<case additional="surface=sett" attrColorValue="$surfaceCobblestone"/>
		<case additional="surface=cobblestone" attrColorValue="$surfaceCobblestone"/>
		<case additional="surface=paving_stones" attrColorValue="$surfacePavedColor"/>

		<case additional="surface=pebblestone" attrColorValue="$surfacePavedColor"/>
		<case additional="surface=stone" attrColorValue="$surfacePavedColor"/>
		<case additional="surface=metal" attrColorValue="$surfacePavedColor"/>
		<case additional="surface=wood" attrColorValue="$surfacePavedColor"/>
		<switch>
			<case additional="surface=gravel"/>
			<case additional="surface=fine_gravel"/>
			<case additional="surface=compacted"/>
			<apply attrColorValue="#cbcbe8"/>
			<apply_if nightMode="true" attrColorValue="#c5c5dc"/>
		</switch>
		<case attrColorValue="$null"/>
	</renderingAttribute>

	<renderingConstant name="surfaceGradeExcellentColor" value="#00d8ff"/>
	<renderingConstant name="surfaceGradeGoodColor" value="#7debff"/>
	<renderingConstant name="surfaceGradeIntermediateColor" value="#b1f3ff"/>
	<renderingConstant name="surfaceGradeBadColor" value="#febcbc"/>
	<renderingConstant name="surfaceGradeVery_badColor" value="#fea9a9"/>
	<renderingConstant name="surfaceGradeHorribleColor" value="#ff7f7f"/>
	<renderingConstant name="surfaceGradeVery_horribleColor" value="#fe5050"/>
	<renderingConstant name="surfaceGradeImpassableColor" value="#ff1111"/>

**Comment by Chumva** [comment]
Fixed https://github.com/osmandapp/Osmand/pull/6663/commits/9440f61360fcd7866391c1596d54d568e347a2d0
