### ISSUE TITLE
Extra routing option does not show up

### ISSUE THREAD

**Issue by pietervdvn** [osmandapp/Osmand#6614]
OsmAnd v3.3.2 (release date 2019-03-02), Android (LineageOS with GApps)
Offline maps

[I've added an extra option to avoid cobblestones.](https://github.com/osmandapp/OsmAnd-resources/pull/546). In the new version, this extra version has no attached text:

![screenshot_20190304-145845_osmand](https://user-images.githubusercontent.com/1466478/53738377-59d6b700-3e8f-11e9-9f2c-601a7c0d044d.png)

In the 'old' parameter settings, it is still shown however:

![screenshot_20190304-145855_osmand](https://user-images.githubusercontent.com/1466478/53738393-63601f00-3e8f-11e9-96da-2b7c62f7bcf5.png)

**Comment by quax2712** [comment]
I added 
 `<parameter id="bike_touring" group="Fahrrad" name="Tracking" description="für Touren" type="boolean" default="true"/>
<parameter id="bike_racer"   group="Fahrrad" name="Rennrad" description="Rennrad radeln" type="boolean"/>
<parameter id="bike_std"     group="Fahrrad" name="Standard" description="Freizeit radeln" type="boolean"/>`

This shoud appear as a Combobox, but now it is far down as single checkboxes
![screenshot_20190304-200900](https://user-images.githubusercontent.com/42236280/53756660-ff9f1b80-3eb9-11e9-851f-043a9cfac670.jpg)

**Comment by dmpr0** [comment]
@quax2712 Hello! Please create another issue for this request.

**Comment by pietervdvn** [comment]
I forgot to mention: the screenshots I made are both of the latest 3.3.2 beta version - where the old and new interface coexist. The new one does not show it, going via the the old navigation settings does show it.
