### ISSUE TITLE
Bugs in 3.3.3

### ISSUE THREAD

**Issue by Thunichgud** [osmandapp/Osmand#6625]
1. It is not possible to change the stile. It is possible to select another stile, but after closing the stile menue the previous stile is still active.
2. New: "Navigation on public transport, support of all kinds of transport: Metro, Buses, Tram and so on.", but when trying to use train navigation "Route couldn't calculated. Application mode 'train' is not supported."

**Comment by sonora** [comment]
1. is probably identical with #6612, meaning the Apply button is off the screen?

**Comment by vshcherb** [comment]
Navigation on public transport doesn't have all profiles and it has only 1 mixed profile. The profiles is part of another task to be finished.
#6612 is a duplicate bug.

**Comment by Mannshoch** [comment]
Osmand 3.3.8
I also only get 'Application mode trainis not supported'
