### ISSUE TITLE
No data available in OsmAnd Live recipients report for Poland

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6626]
March Recipients report for Poland indicates there is no data available in table.

**Comment by asier70** [comment]
In web browser, the problem looks like this:
![obraz](https://user-images.githubusercontent.com/25247594/54116469-27790c80-43ef-11e9-872a-50faa5c6b82c.png)

**Comment by vshcherb** [comment]
We don't produce global Poland OSM country anymore that's why that support is lost. 
That rule is applicable to all big countries like US, Germany etc. We will need to either redesign whole structure or to ask to put donations to a specific Poland Region

**Comment by asier70** [comment]
I suggest removing global Poland country from the list and dividing donations equally among all 16 regions.

**Comment by vshcherb** [comment]
List is updated
