### ISSUE TITLE
New navigation UI: no options for motorcycle and trucks

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#6629]
With the new UI it is no longer possible to configure motorcycle and truck routing options such as voice announcements, avoid roads, route along GPX track, show along route and so on.

These options have been present with the old UI. Please make them accessible again.

**Comment by vshcherb** [comment]
There should be no difference between previous release but new feature of configuring profiles not polished yet and will be followed in this release.

**Comment by scaidermern** [comment]
These options are still missing in 3.3.4.

**Comment by c-o-m-p-i** [comment]
Still no options available in 3.3.6.
@vshcherb Which release should contain the options?

**Comment by vshcherb** [comment]
It will be 3.3.7, now you can still configure it in Settings - > Navigation Settings
