### ISSUE TITLE
In "Russian + transliteration" language mode, some Russian names are displayed transliterated

### ISSUE THREAD

**Issue by pgavrilov** [osmandapp/Osmand#6633]
In "Russian + Transliterate if Russian name is missed" map language mode, some Russian names are displayed transliterated.

If object have name only in "name" tag (not in "name:ru"), OSMand always transliterate its name.

I think OSMand must interpretate "name" tags as "name:language" for official (or most often usable) language for region where object is placed.

EXAMPLE:

1. Map language mode: Local Names
![1 map language local names](https://user-images.githubusercontent.com/3817702/53956135-dbc31c00-40eb-11e9-83e2-bec4272e329b.jpg)

2. Map language mode: English
![2 map language english](https://user-images.githubusercontent.com/3817702/53956134-dbc31c00-40eb-11e9-9cf7-5e9221f8afe7.jpg)

3. Map language mode: Russian with transliteration
![3 map language russian with transliteration](https://user-images.githubusercontent.com/3817702/53956136-dbc31c00-40eb-11e9-8bbf-f97ada77a984.jpg)

Point of attached example images:
https://www.openstreetmap.org/#map=15/56.2751/37.3333

Objects:
https://www.openstreetmap.org/way/98327637
place=hamlet
name=Селявино

https://www.openstreetmap.org/way/98327633
place=village
name=Ольгово
name:ru=Ольгово

https://www.openstreetmap.org/way/453603504
landuse=meadow
name=конно-спортивный клуб

**Comment by vshcherb** [comment]
This is intented behavior now, only name:ru will be stay untouched for non-transliteration option, everything else will be transliterated
