### ISSUE TITLE
Rename "Description" to "Details"

### ISSUE THREAD

**Issue by IgorEliezer** [osmandapp/Osmand#6637]
OsmAnd 3.3.3 Unlimited, Android

Suggestion: rename "Description" to "Details" in the POI panel.

![image](https://user-images.githubusercontent.com/4673289/54016733-a3125980-4162-11e9-8a35-3208707c789b.png)

Reasons:
* It's more descriptive about the feature. The POI panel contains all info about contacts, address, physical data etc, not only its description.
* To distinguish from Description (given by the key [`description`](https://wiki.openstreetmap.org/wiki/Key:description)) of the POI itself.
* It's a better opposite to "Collapse".

**Comment by sonora** [comment]
Yes, I think in principle this makes sense. But we should keep in mind we can go even further and assimilate or style with how we handle things in the new Route details screen: There the Expand/Collapse is handled by the conventional arrow icon buttons, I think we should find a common style now across most/all of our screens.
