### ISSUE TITLE
More appropriate opening states of the new route definition screen

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#6639]
@crimean I had hidden this suggestion in a Commit comment, not sure if it is visible enough there: https://github.com/osmandapp/Osmand/commit/f0b4d4140192dc96b118ed219e989152b2d1b90d#commitcomment-32652483

**Comment by crimean** [comment]
It is visible, but new issue is ok.

**Comment by vshcherb** [comment]
(1) While the route is being calculated, reduce the dialog size to just include everything from the top to the progress bar (below the "Options" line). As it is today, I also see, while a route is being calculated, a half a screen of just 'empty' area below this progress bar (and above the Cancel/Start) button line

(2) After a route has finished calculating (or when you tap the map screen's navigation button with a route already calculated), show/open everything until (and including) the "Details" button, in particular this also includes the calculated distance/time and profile.

Also, for case (2) I suggest we change the caption of the Cancel button from 'Cancel' to 'Dismiss' ?

**Comment by sonora** [comment]
I have meanwhile already implemented the Cancel/Dismiss wording, so that portion is fixed.

**Comment by vshcherb** [comment]
I think we have now other issues open regarding state of new dialog
