### ISSUE TITLE
3.3.2:  From in Directions does not work correctly

### ISSUE THREAD

**Issue by hvdwolf** [osmandapp/Osmand#6644]
OsmAnd 3.3.2
Internal OsmAnd routing

When creating a route "From:" some location to "Destination:", the "From:" does not work correctly.

OsmAnd always starts to calculate a route immediately after having specified the Destination. It does this from the "From:" position "My Position".
If you don't specify a "From:" address/location before it has already calculated a route based on current location (My Postion) to "Destination", which can happen especially in case of shorter routes, you can forget it. If you're not fast enough, OsmAnd will calculate a route from your current location towards the start point (From:) you actually want and specified (too late), and then to the Destination.
You really need to exit OsmAnd, restart it and be faster than the route calculation (by using history or something like that).

**Comment by hvdwolf** [comment]
Update
OsmAnd 3.3.4.

Now in OsmAnd 3.3.4 I can no longer reproduce the mentioned bug in 3.3.2.
I will leave the ticket open for the time being to see whether it returns in one of the following beta releases.

**Comment by vshcherb** [comment]
No need to keep it open, that's part is been actively fixed
