### ISSUE TITLE
Zoomlevel 13 and lower inconsistent between normal maps and roads_only maps 

### ISSUE THREAD

**Issue by hvdwolf** [osmandapp/Osmand#6645]
OsmAnd 3.x
Using Netherlands Roads_Only Map 01 Feb 2019 and using Netherlands Normal Map 01 Feb 2019.
Render file: default.render.xml
Map style: OsmAnd (1)
Road style: Bold outline (1)
Details -> More Details (1)

(1): Those last 3 were used for the screenshots, but make absolutely no difference on the bug mentioned here.

I'm referring here to roads! Not to other map details like greenery, parks, etc. Of course they are not displayed or not displayed in equal details in roads_only maps.

On zoomlevel 14 and up the number of details in streets is identical. On zoomlevel 13 and lower, the roads-only maps shows only a reduced number of roads. I'm using roads_only maps for car navigation. I don't care at all about other details (I don't want them), but I want to see the same number of streets.
See attached 4 screenshots. I left them on purpose on "high"-resolution 1080x1920.
The location is around the Rijskmuseum in Amsterdam. That does not matter though as the difference is the same everywhere on every location in every region/country/map.
In zoomlevel 14:3 the detail in streetlevel is the same (other details are not relevant when comparing normal and roads_only maps).
In the zoomlevel 13:3 the roads_only maps only show a limited amount of roads compared to the normal maps. The same issue occurs on zoomlevel 12.

I tried to find the differences in  the default.render.xml but I don't see it. Is it in the map making? If so please correct it as especially in a roads_only map you expect all roads.

**Roads Only map zoomlevel 13:3**
![RoadsOnly-Zoom13_3](https://user-images.githubusercontent.com/4520361/54070852-d12c9200-4265-11e9-9336-f08229904436.jpg)
**Normal map zoomlevel 13:3**
![NormalMap-Zoom13_3](https://user-images.githubusercontent.com/4520361/54070850-d12c9200-4265-11e9-911b-3a2909a45ed0.jpg)
**Roads only map zoomlevel 14:3**
![RoadsOnly-Zoom14_3](https://user-images.githubusercontent.com/4520361/54070853-d1c52880-4265-11e9-901a-cd1739196d22.jpg)
**Normal map zoomlevel 14:3**
![NormalMap-Zoom14_3](https://user-images.githubusercontent.com/4520361/54070851-d12c9200-4265-11e9-897c-a4343d546352.jpg)

**Comment by hvdwolf** [comment]
Hi, it's now in November and it still has not changed. Is there a version planned where this will be corrected. It is even worse now. See attached image where the top half is the full map of the Netherlands and the bottom half is the roads-only map of Belgium with the "big city" of Antwerpen (image reduced in size)
![roads_only_vs_full](https://user-images.githubusercontent.com/4520361/68525562-57a4e200-02d3-11ea-95a7-8bbbf9f329eb.jpg)

**Comment by hvdwolf** [comment]
**Assumption:** I do not think roads_only maps are directly generated anymore. I do think it is done via the "utilities.sh  extract-roads-only <full map>" command.
I downloaded the full Netherlands map and the roads_only Netherlands map and created a roads_only map from the full_map using the utilties script. Then I did a "diff" on the downloaded and created roads_only map. They were equal on byte level.

I spent the past hours looking through the code and scripts and ended up in the OsmAnd-tools repository.
The routing, poi and address data is in the the roads_only map. 
I do think that the utilities script does not extract the map data in zoom level 9-10 ( Map level minZoom = 9, maxZoom = 10) from the full map.
Disabling a roads_only map in zoom level 9-10 gives the exact same map view as enabling it: You only see the world-map.
So, no map data on zoom level 9-10.

Unfortunately I lack the skills to fix this. I simply can't find where it goes wrong.
Please fix.

**Comment by vshcherb** [comment]
Yes it is the same as 7919
