### ISSUE TITLE
Shared location in search history wrong

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#6651]
While a new shared location turns up at the beginning of the search history it doesn't have the correct coordinates. Instead it seems to use the coordinates from a very old shared location.

Also multiple shared locations don't turn up in the search history. There is always only one, with outdated coordinates.

Seems to be a regression since the latest stable version.

**Comment by MadWasp79** [comment]
https://github.com/osmandapp/Osmand/commit/32d4f5a42a37ce1552c07ccb4d30966304a8349e
