### ISSUE TITLE
3.3.x missing prompt to navigate displayed tracks

### ISSUE THREAD

**Issue by barteis** [osmandapp/Osmand#6653]
In previous versions, when pressing the directions button, users were prompted as to whether they wanted to use the displayed track, or tracks, for navigation.  That function seems to be missing from 3.3.  Without it, navigating a displayed track is more difficult and less obvious.  From the directions screen:

Options > GPX route > Select GPX > [find displayed GPX from your entire collection of GPXs]. 

The screen capture below shows the missing prompt.  

<img width="285" alt="Use track" src="https://user-images.githubusercontent.com/36173950/54089167-62ae0980-4323-11e9-8152-14fcd3b475bb.png">

**Comment by quax2712** [comment]
If you have tracks visible they are shown in the new start window, one can be selected for Routing.

**Comment by barteis** [comment]
I'm not sure what you mean by "start window", but on v. 3.3.4, on not seeing this in the Directions menu or the Details submenu, nor in Options except as I mentioned above. Is it somewhere else?

**Comment by quax2712** [comment]
here you ca see 3 of 11 tracks.  
![TrackSelection](https://user-images.githubusercontent.com/42236280/54160749-ae120600-4450-11e9-8ef9-6855eba42138.jpg)

**Comment by barteis** [comment]
Thanks.  I'm seeing them on Osmand 3.3.3, but not Osmand+ 3.3.4.  What version is your screen capture from? Maybe that's the difference, or perhaps there is some difference in settings.

**Comment by quax2712** [comment]
I have 3.3.4, have a look at my "my places" > tracks, there you must see all Visible Tracks too

**Comment by barteis** [comment]
I guess the problem isn't related to 3.3.4.  Below are three short GPXs as seen in My Places and on the map.  But as you can see, the Directions menu doesn't show any of them. 

![My Places](https://user-images.githubusercontent.com/36173950/54162477-d2e78880-4412-11e9-86d8-21f2f9c64e19.png)
![Map](https://user-images.githubusercontent.com/36173950/54162486-d9760000-4412-11e9-95bd-9cc0b9933c36.png)
![Directions menu](https://user-images.githubusercontent.com/36173950/54162493-de3ab400-4412-11e9-96d6-f8dd9718ca9d.png)

**Comment by sonora** [comment]
In your last screenshot, the route has already been calculated. To check if/which gpx has been used, tap the Options button on that screen.

The screenshot further up from quax2712 shows the situation before the route is calculated (simply after tapping the Directions button on the map screen). There you can simply tap any displayed track and it will be used.

**Comment by barteis** [comment]
You're right--that was the problem. But there was no obvious way to stop the calculation: the cancel button didn't do it, even when I was prompted to dismiss the route. So I cleared the storage and cache, effectively starting over: problem solved.  Thanks quax2712 & sonora.
