### ISSUE TITLE
Routing over closed road [vehicle:conditional =no @ (2019 Mar 1-2019 Jun 30)]

### ISSUE THREAD

**Issue by majkaz** [osmandapp/Osmand#6654]
Using osmand 3.3.0#26929m (FDroid), with latest maps and live updates.

Osmand is trying to route over a primary road closed for road works (https://www.openstreetmap.org/way/447744664).

Should Osmand take this into account or does the app need some other format to avoid routing here?

**Comment by scaidermern** [comment]
So far there is no support for conditional access restrictions, see #1794.

**Comment by vshcherb** [comment]
There is no support for conditional routing but for such long restriction > 3 months, you can always mark it is access=no and then revert back in 3 month.

**Comment by mahdi1234** [comment]
> you can always mark it is access=no and then revert back in 3 month.

Sorry, but I totally disagree. With this approach anyone without live maps will be penalized until next maps update. That's what conditional is for that even not latest data will let you drive via such street when road closure is gone. If you are serious into car navigation Osmand will be behind without supporting it.
