### ISSUE TITLE
[3.3.4] COnfusing GUI for selecting multiple points

### ISSUE THREAD

**Issue by pietervdvn** [osmandapp/Osmand#6655]
Hello,

v3.3.4 (beta channel), LineageOS, Android Orea (8.1)
v3.3.5 (nightly 2019-03-07), Res. Remix

In the window to setup navigation, removing an intermediate point in the interface is a bit confusing.

When pressing `edit`, an extra card pops up (IMHO it is awkward having two 'cards' on top of each other).
Then, when removing the intermediate point, the number in the upper left is not immediately decreased.

In the mean time, removing the point is applied, but the apply button stays grayed out - forcing the user to use the back-arrow to return (which should be the 'cancel'-option).

![ezgif-4-d794f114a265](https://user-images.githubusercontent.com/1466478/54091325-548dd680-437f-11e9-85ed-41143ebf6d4d.gif)

**Comment by raindropsfromsky** [comment]
I have already raised this point, but apparently the GUI is WIP; so hopefully this will be dealt with soon.

**Comment by sonora** [comment]
Cannot fully reproduce: 

I can confirm that the number behind "Destinations" is only updated **after** the route finishes re-calculation, not immediately upon removing the intermediate. Room for improvement here, I guess.

 But contrary to the screenshot above, for me the number (initially and finally) is correct: With initially 1 intermediate it correctly displays "Destinations: 2", and after removing the intermediate (when the route finishes re-calculation) is displays "1".

**Comment by pietervdvn** [comment]
After experimenting a little, i think it waits for the toast (the pop-up
text) to finish before updating, not the routing.

**Comment by sonora** [comment]
Yes, true!

Undo button does not work for me after removing an intermediate, all else seems fine?
