### ISSUE TITLE
[3.3.4] Selecting "Replace start" introduces an intermediate waypoint instead

### ISSUE THREAD

**Issue by pietervdvn** [osmandapp/Osmand#6656]
3.3.4, Android 7.1 (LineageOS 15.1)

When routing and asking directions, selecting "replace start point" changes the original start point into an intermediate waypoint instead of removing it. See video:

![IntermediateHQ](https://user-images.githubusercontent.com/1466478/54091517-1db8c000-4381-11e9-9ff3-cdf7a5bda8c9.gif)

**Comment by raindropsfromsky** [comment]
To rephrase the limitation, you cannot replace the start point by selecting a point on map and then tapping **Directions** button from its card. OsmAnd allows you to make it ANY point on the route, but it does NOT allow you to make it the start point. 

Probably the logic was that mostly you start from your current location, and not from any random point selected on map. But this prevents us from checking out the route between any two points on the map.

Suggested improvement: Add the **Start point** option in the **Directions** menu.

**Comment by raindropsfromsky** [comment]
Confirmed. Nightly dated 11th March, running on Android Pie.

**Comment by vshcherb** [comment]
"Make this start point" should replace Start point. I would consider it is a buggy behavior.

**Comment by MadWasp79** [comment]
closed with https://github.com/osmandapp/Osmand/commit/fc77c1efb5c4e3fd0bf47a8c3eaf5e0d576bce90
