### ISSUE TITLE
Routing option buttons appear and disappear

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#6664]
![grafik](https://user-images.githubusercontent.com/6921696/54201069-143c6e80-44cd-11e9-8e5c-18d053ad86b5.png)

I cannot see a concept behind these buttons. They appear and disappear sporadically.

Found with OsmAnd+ 3.3.

**Comment by dmpr0** [comment]
Hello!
The main concept allows quick access to the main options.
In Bicycle and Pedestrian profiles main options are preselected. In Car profile, they appear after the user turn on one of the settings.

**Comment by Norbert80** [comment]
This doesn't sound like a intuitive concept to me. It feels buggy. @vshcherb what do you mean?

**Comment by dmpr0** [comment]
@Norbert80 We still in development and fixing process of Direction menu, if you have suggestions about the options, we will glad to hear it.
