### ISSUE TITLE
v3.3.x: Frequent OutOfMemoryError for Transport Routing

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#6667]
Frequentlly observed with new trasnport routing in versions 3.3.3, 3.3.4, etc.:  [exception.log.txt](https://github.com/osmandapp/Osmand/files/2960125/exception.log.txt)

**Comment by crimean** [comment]
@sonora Could you please send start/finish location of the route?

**Comment by sonora** [comment]
Alexey, it happens in lots of cases, particularly in big cities like Rome or Munich with many public transport options. (I had picked random locations via "Select on map" for my tests.) 

Worth noting that the issue is history-dependent: In some cases the VERY SAME route works after OsmAnd has restartet, so it seems that somehow you can use up memory by e.g. searching or map panning, and then receive OoM when you subsequently start bigger transport routes. On the very same devices, I never received OoM for any other operation in OsmAnd.

**Comment by sonora** [comment]
Here is a random example which fails: Rome, latest Italy-Latium map, PT route
- from: Viale Tiziano (https://osmand.net/go?lat=41.924744&lon=12.471542)
 - to: Near Via Ettore Petrolini (https://osmand.net/go?lat=41.92934&lon=12.498322)

Just about any other PT route in Rome or other big cities longer than say 1km fails after 1-3 minutes of calculation, while shorter routes or routes in smaller cities (probably with fewer PT lines available) work.

**Comment by vshcherb** [comment]
Not much could be done, it needs proper investigation.

**Comment by vshcherb** [comment]
I will reopen issue once we've got more examples but recent changes provide a decent fix for it.
So I was able to calculate these routes

**Comment by vshcherb** [comment]
The problem is back. Long term solution will be provided only when that code will be migrated to C++ but it might happen only next release

**Comment by vshcherb** [comment]
Timing and errors now  could be traced in MapCreator or in Logs of application. I've found 1 parameter (zoom to load tiles) which affects speed and in Rome specifying 15th zoom provides 4 times faster results.

**Comment by njohnston** [comment]
I get frequent crashes (out of memory) when using public transport routing on OsmAnd+ 3.3.8 on a Samsung Galaxy S8+.

Stack trace:

```
Version  OsmAnd+ 3.3.8
06.05.2019 8:25:55
Apk Version : 3.3.8 338
Exception occured in thread Thread[Calculating public transport route,5,main] : 
java.lang.OutOfMemoryError: Failed to allocate a 24370680 byte allocation with 16777216 free bytes and 18MB until OOM
	at java.util.Arrays.copyOf(Arrays.java:3231)
	at java.util.Arrays.copyOf(Arrays.java:3204)
	at java.util.PriorityQueue.grow(PriorityQueue.java:300)
	at java.util.PriorityQueue.offer(PriorityQueue.java:339)
	at java.util.PriorityQueue.add(PriorityQueue.java:321)
	at net.osmand.router.TransportRoutePlanner.buildRoute(TransportRoutePlanner.java:136)
	at net.osmand.plus.routing.TransportRoutingHelper$RouteRecalculationThread.calculateRouteImpl(TransportRoutingHelper.java:469)
	at net.osmand.plus.routing.TransportRoutingHelper$RouteRecalculationThread.run(TransportRoutingHelper.java:607)
```

I can reproduce this crash in urban areas with many transport lines. Any route >~2 km in Singapore (wiht the most recent map, 1st April) triggers it, for example from [1.28939,103.83660](https://osmand.net/go.html?lat=1.28939&lon=103.83660) to [1.34442,103.83769](https://osmand.net/go.html?lat=1.34442&lon=103.83769).

Unlike @sonora , the problem does not seem to be history-related for me.

**Comment by sonora** [comment]
I can confirm that in cities with extended public transport networks the OoM error comes up unconditionally and upon first try already, if only the distance selected exceeds a certain threshold (presumably creating a big number of possible paths).  In e.g. downtown Rome/Italy, I seem to hardy be able to calculate a public transport route for distances longer than 2-3 km. Unless there is still a memory leak in the routing algorithm (i.e. a bug which needs fixing), we may just have to wait for the code to be ported to C.

**Comment by vshcherb** [comment]
We're planning to migrate code to C++ and make it more compact / faster, so it will serve 2 purposes:
1. Make it available for IOS
2. Make it more robust

**Comment by vshcherb** [comment]
New release likely will help with OOM issue but it didn't make it faster though
