### ISSUE TITLE
Localization: "OSMand Live" advantages description in Russian

### ISSUE THREAD

**Issue by pgavrilov** [osmandapp/OsmAnd#6668]
Вместо непонятной фразы "Разблокировать все функции OSMand" следует написать что-то вроде "Доступ к любым новым функциям в будущем"
![OSMand Live description](https://user-images.githubusercontent.com/3817702/54275169-03f2c500-459b-11e9-95e2-4216619b50e5.jpg)

**Comment by vshcherb** [comment]
Да уже поменяли вроде
