### ISSUE TITLE
OSM Editing screen: show Save button above keyboard.

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#6669]
When editing POIs the save button is hidden below the keyboard.

**Comment by dmpr0** [comment]
Additional: Keyboard overlaps part of the input fields, the scroll doesn't work, so they are hidden, and could be visible only after keyboard minimized.

**Comment by scaidermern** [comment]
Example of the keyboard overlapping save/cancel buttons as well as the input field and the list of suggestions:
![photo_2019-03-22_11-25-32](https://user-images.githubusercontent.com/1040784/54816700-397f6880-4c95-11e9-926d-958e8d5a59b5.jpg)

**Comment by Boothy99** [comment]
Until this is fixed - (at least on my mobile phone)... - if you flip the phone to landscape mode, the text becomes visible so you can see what's being typed again.
