### ISSUE TITLE
Where is the quick action show/hide OSM notes?

### ISSUE THREAD

**Issue by rbovard** [osmandapp/Osmand#6670]
It was added here https://github.com/osmandapp/Osmand/commit/8a2ee80157b75239e6be4edf6753d249810133ab

But I cannot see it anymore in quick action menu (OsmAnd+ v3.3.4):

![image](https://user-images.githubusercontent.com/4549666/54292886-41614d80-45af-11e9-8730-4cea458a04bd.png)

**Comment by mds08011** [comment]
That's odd.  On my app it shows up in the "Configure map" category.

**OSMAnd version:** 3.3.4 (OSMAnd+)
**Device:** Pixel 2
**Android version:** 9.0 (P/Pie)

<img src="https://user-images.githubusercontent.com/8010709/54325262-850f8380-45be-11e9-998e-ea1d373cfb7f.jpeg" width="50%">

**Comment by mds08011** [comment]
Which profile are you using (Browse map, Driving, Cycling, Walking)?  This action only shows when I am using the "Browse map" profile (the globe icon).

**Comment by rbovard** [comment]
Yes, I'm "Browse map" profile.

* OsmAnd+ 3.3.4
* Nokia 6.1
* Android 9

Any idea why I have only these 5 actions in Configure map group?

**Comment by dmpr0** [comment]
@rbovard Hello! You need to turn on OSM Edits plugin first. All actions or menus relate for OSM Editing shows in the app only after the plugin is turned on.

**Comment by rbovard** [comment]
It was already on. I tried to turn it off and on again, but I still do not have these quickactions...

**Comment by rbovard** [comment]
FYI the action "Add POI" is removed when turning plugin off and is back when turning it on...
