### ISSUE TITLE
Context menu now missing coordinate display under "Details"`?

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#6672]
Title says it all: I am missing the coordinate indication we used to have on any point's context menu when tapping its 'Details' button. Was needed for geocachers etc.

**Comment by sonora** [comment]
I just notice the Lat/Lon display is present for POIs, but missing for e.g. Favorites, My Position, or orange markers obtained by long tapping the map or by short tapping map objects.

**Comment by dmpr0** [comment]
Hello, @sonora!
You are right, we have discovered it yesterday too, we will fix it today.

**Comment by Chumva** [comment]
Fixed https://github.com/osmandapp/Osmand/commit/c2472e016a7bf384284320f22c657d27c3da186a
