### ISSUE TITLE
Directions differ between OSMAnd and OSRM website for same route

### ISSUE THREAD

**Issue by mds08011** [osmandapp/Osmand#6674]
### Bug description

The OSRM navigation directions in OSMAnd are different than what I see for the same route in the OSRM website.

I initially noticed that in OSMAnd, the route highlight lines seem closer to simplified jagged approximations than the complex OSRM routes I am used to seeing in a web browser.  When I enter the same origin and destination in both OSMAnd and the OSRM website, I see the same general path of travel but the list of directions is different.  OSMAnd seems to only be giving directional steps but not the usual more complex routing instructions.  For example, for the same point in my route where I will be exiting a highway, the OSRM website says to “Take Exit 9 towards Main Street”, while OSMAnd states “turn slightly right” for the same action.  My screenshots below highlight this example.

My OSMAnd should be using OSRM for routing, so I am not sure why this discrepancy is occurring.

This topic initially started on the Google Groups Forum: https://groups.google.com/forum/#!topic/osmand/PV6JayvXZPI 

### Device info
**OSMAnd version:** 3.3.4 (OSMAnd+)
**Device:** Google Pixel 2
**Android version:** 9.0 (P/Pie)

### OSMAnd Settings

**Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?**

I use downloaded maps and am an OSMAnd Live subscriber.

### Routing

**Tell us whether you have used OsmAnd's in-app offline routing, or any online routing provider like YOURS, OpenRouteService or OSRM.**

OSRM Navigation service

**What routing profile is chosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest)**

Car profile, fastest route.

**Starting Location**
3000 E Street San Diego, CA 92102
* *House Number*: 3000
* *Street*: E Street
* *City*: San Diego
* *State*: California (CA)
* *Country*: USA
* *Postal Code*: 92102
* *OSM Link*: https://www.openstreetmap.org/way/447053230 

**Ending Location**
9449 Balboa Avenue San Diego, CA 92123
* *House Number*: 9449
* *Street*: Balboa Avenue
* *City*: San Diego
* *State*: California (CA)
* *Country*: USA
* *Postal Code*: 92123
* *OSM Link*: https://www.openstreetmap.org/way/605759198 

**OSRM Route**: http://map.project-osrm.org/?z=13&center=32.765914%2C-117.117090&loc=32.715299%2C-117.129285&loc=32.821954%2C-117.126434&hl=en&alt=0 

### Screenshots

OSMAnd (using OSRM) route from `3000 E Street San Diego, CA 92102` to `9449 Balboa Avenue San Diego, CA 92123`:
<img src="https://user-images.githubusercontent.com/8010709/54324206-01ec2e80-45ba-11e9-9bf0-5bb447b35f3a.png" width="50%">

OSRM website route from `3000 E Street San Diego, CA 92102` to `9449 Balboa Avenue San Diego, CA 92123`:
![OSRM-Demo](https://user-images.githubusercontent.com/8010709/54324211-057fb580-45ba-11e9-9dbc-fe812e9beed9.png)

**Comment by vshcherb** [comment]
I checked the source code and it is also visible in the logs but URL is correct:
https://router.project-osrm.org/route/v1/driving/
So I have no idea why routing is different for API and the website

**Comment by mds08011** [comment]
That's odd.  Thank you for looking into it!

The route highlight lines I am seeing in OSMAnd look very simplified with straight lines even on curved roads (screenshots below).  Are there any settings in OSMAnd I should check, or does this seem entirely related to the API?  I use online OSRM routing with downloaded OSMAnd maps.

<img src="https://user-images.githubusercontent.com/8010709/54460849-f74fa780-4727-11e9-9ed9-4488f09aa28c.png" width="50%">

<img src="https://user-images.githubusercontent.com/8010709/54460848-f74fa780-4727-11e9-9237-597e5bb9c94a.png" width="50%">

**Comment by jfburke3** [comment]
Just from my observation as a user, it looks like OsmAnd is treating the OSRM route as a gpx track with sparsely placed waypoints, especially given the text directions shown.

**Comment by jfburke3** [comment]
Is OSRM only returning a sparce gpx route to OsmAnd?

**Comment by sonora** [comment]
Yes, the first two screenshots in this thread indicate the native OSRM route with all sorts of details while the route details screen in OsmAnd shows only very basic turn info. Could well be that the API only returns a gpx with track points and no full route info, or maybe the API allows for an option we are not setting. But at first sight I find no info on their web site.

**Comment by danpat** [comment]
👋 OSRM dev here.

Looking at the OSMAnd code - https://github.com/osmandapp/Osmand/blob/c8ccf21c737e239dda267c89ef2edf504ad9d3e6/OsmAnd/src/net/osmand/plus/routing/RouteProvider.java#L1076

it looks like there are a bunch of API parameters missing that would fix this.

I would add:

  `?steps=true&overview=full`

to the request being made.

`overview=full` will give you a non-simplified geometry back - the default that OSRM returns is a simplified response designed for route overview, not for rendering at high zoom levels on a map.

`steps=true` will return all the correct step-by-step instructions that you can see on the OSRM demo website.  In the API response, the `steps: []` element will be populate with objects that describe the step-by-step instructions that you'd want to present to a user:  http://project-osrm.org/docs/v5.22.0/api/#routestep-object

I have no idea if these map through to existing OSMAnd concepts, but I'd say that because they're not being used, you're missing out on a bunch of OSRM's functionality by default.

**Comment by vshcherb** [comment]
Hi @danpat 
Thanks for introduction we are planning to upgrade it in future release!

**Comment by vshcherb** [comment]
OSRM option is removed for now and we decided to postpone that task a bit.
